### ISSUE TITLE
test-path-lookup failed.

### ISSUE THREAD

**Issue by osiris1147** [systemd/systemd#10002]
**systemd version the issue has been seen with**
> master

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > test-path-lookup should succeed.

**Unexpected behaviour you saw**
 > test_user_and_global_path() in src/test/test-path-lookup.c is failing even if all entries in the global search path also exists in the user search path.

```
Looking for unit files in (higher priority first):
        /etc/systemd/system.control
        /run/systemd/system.control
        /run/systemd/transient
        /etc/systemd/system
        /run/systemd/system
        /run/systemd/generator
        /usr/lib/systemd/system
Ignoring unit files.
Looking for unit files in (higher priority first):
        /home/osiris/.config/systemd/user.control
        /run/user/1000/systemd/user.control
        /run/user/1000/systemd/transient
        /etc/systemd/user
        /usr/lib/systemd/user
Ignoring unit files.
Looking for unit files in (higher priority first):
        /etc/systemd/user
        /usr/lib/systemd/user
Ignoring unit files.
/* test_user_and_global_paths */
+ /home/osiris/.config/systemd/user.control
+ /run/user/1000/systemd/user.control
+ /run/user/1000/systemd/transient
+ /run/user/1000/systemd/generator.early
+ /home/osiris/.config/systemd/user
  /etc/systemd/user
+ /run/user/1000/systemd/user
  /run/systemd/user
+ /run/user/1000/systemd/generator
+ /home/osiris/.local/share/systemd/user
+ /usr/share/systemd/user
  /usr/local/share/systemd/user
+ /usr/local/lib/systemd/user
+ /usr/lib/systemd/user
+ /run/user/1000/systemd/generator.late
  /usr/share/systemd/user
Assertion 'u[k]' failed at ../src/test/test-path-lookup.c:60, function test_user_and_global_paths(). Aborting.
Aborted (core dumped)
```
`/usr/share/systemd/user` is an entry in the user search path since it was already printed above, but is reported as not found.

**Comment by yuwata** [comment]
Which version do you use?

**Comment by osiris1147** [comment]
I am using version 239.

I think the problem is that if one entry of the global search path is found, the next one is only searched in the rest of the user search path and not the whole one.

**Comment by yuwata** [comment]
> I think the problem is that if one entry of the global search path is found, the next one is only searched in the rest of the user search path and not the whole one.

I think the test expects that the list are in a 'proper' order.
BTW, I cannot reproduce this... Did you set any specific build option?

**Comment by poettering** [comment]
@osiris1147 do you have any XDG_xyz env var set?

**Comment by poettering** [comment]
(i figure we should unset $XDG_DATA_DIRS and friends explicitly in this test to make sure this passes in all cases.)

**Comment by osiris1147** [comment]
These are all XDG env variables.

```
XDG_VTNR=1
XDG_SESSION_ID=2
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_CLASS=user
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=KDE
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
```
