### ISSUE TITLE
machinectl pull-raw hangs forever

### ISSUE THREAD

**Issue by indradhanush** [systemd/systemd#10016]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
> $ machinectl pull-raw https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
>
> Expected this command to download the image.

**Unexpected behaviour you saw**
 > $ machinectl list-transfers
 > No transfers.

**Steps to reproduce the problem**
Use systemd v239 and run:

```
machinectl pull-raw https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
```

**Comment by yuwata** [comment]
I guess that this is a duplicate of #9527, which is fixed by #9536. If possible, could you test with the recent git snapshot?

**Comment by dongsupark** [comment]
I have seen this issue with the current master (21224070e802878f81c342835364880ef1a63e88), when I looked into other issues earlier in this week. The thing is, `machinectl list-transfers` shows nothing, and no file is downloaded.
If it were just a matter of verbosity, then it could have been no big deal. In fact, it still looks like a valid issue.
What I know is only that it worked fine with systemd v238. I have not managed to pin-point its exact reason (or bisect) yet.

**Comment by yuwata** [comment]
Hmm. I cannot reproduce this. Could you show the output of `machinectl` and logs by `systemd-importd.service` (please set `SYSTEMD_LOG_LEVEL=debug` in the unit file).

I get the following:
```
$ machinectl pull-raw https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso', saving as 'coreos_production_iso_image.iso'.
Downloading 370.0M for https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso.
Downloading 264B for https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso.roothash.
HTTP request to https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso.roothash failed with code 403.
Root hash file could not be retrieved, proceeding without.
Downloading 262B for https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso.sha256.
HTTP request to https://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso.sha256 failed with code 403.
Failed to retrieve SHA256 checksum, cannot verify. (Try --verify=no?)
Exiting.
```
And it works with `--verify=no`, which is suggested in the above output.

**Comment by yuwata** [comment]
I guess, you use `machinectl` from the recent snapshot, but use `systemd-importd` from v239. Please check that you certainly use both from recent snapshot.

**Comment by indradhanush** [comment]
I saw the same output as @yuwata and was able to download the image with `--verify=no`.

**Comment by yuwata** [comment]
So, is it possible to close this?

**Comment by indradhanush** [comment]
Sorry, forgot to press the button. :sweat_smile:
