### ISSUE TITLE
LXC doesn't like the namespacing logic in systemd git

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10011]
commit 1beab8b0d0ff2d7d1436b52d4a0c3d56dc908962 introduced lots of failing tests when run under LXC. See https://github.com/systemd/systemd/issues/9700#issuecomment-418450626 for a full ```ninja test``` log.
Reverting that commit, makes the test suite pass again (aside from test-execute, which already failed before)

**Comment by poettering** [comment]
@mbiebl btw, please always consider adding @brauner as CC to LXC related systemd issues, he's very friendly, helpful and attentive for these kinds of things!

**Comment by brauner** [comment]
So, let's operate under the assumption that the first unshare indeed fails:
- I've seen this happen on CentOS when creating mount namespaces in user namespaces is forbidden. Don't know if Debian has a similar restriction. If you use privileged containers this is likely not the case.
- The container is dropping capabilities on startup that prevents it from creating new namespaces. The obvious one is `CAP_SYS_ADMIN`. To test this you can set:
```
lxc.cap.drop =
```
which should ensure that no capabilities are dropped.
- The used AppArmor profile causes a very strict confinement hindering namespace creation. Not sure what kind of AppArmor profile Debian carries.

**Comment by yuwata** [comment]
It seems that AppArmor prevents changing mount propagation flag. So, I've created #10012.

**Comment by poettering** [comment]
So, I posted issue #10505 now, which will skip the relevant tests if namespacing is prohibited (i.e. unshare() and friends are not available). I am not running LXC/AppArmor myself hence I didn't test this against that. However, I did test this through `systemd-run -t -p SystemCallFilter=~unshare -p SystemCallErrorNumber=EPERM` which should have a similar effect of making namespacing unavailable.

**Comment by poettering** [comment]
OK, let's close this, as suggested by @evverx over in #10505, and focus on fixing #9700 which should be fixed by #10505. The issues this issue #10011 is about are outside of systemd really, only the part described in #9700 is inside of systemd's territory, hence let's focus on that. Hope this makes sense.
