### ISSUE TITLE
systemctl does not show some failures e.g. NAMESPACE for Type=simple services

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#10024]
**systemd version the issue has been seen with**
v239-713-g3457a7a93

**Used distribution**
Fedora 28

**Expected behaviour you didn't see**
systemctl detects errors that occur inside systemd code, even for `Type=simple` services.

It would be rather nice to have this behaviour, because `Type=simple` is the default type of service if you don't specify one.

**Unexpected behaviour you saw**
`systemctl start` does not show this failure for `Type=simple` services (but `Type=oneshot` works as desired).

**Steps to reproduce the problem**

This test was run inside a systemd-nspawn container.

Unit file:

```
# /etc/systemd/system/test.service
[Service]
Type=simple
ExecStart=/bin/true
BindPaths=/does/not/exit
```

Example results:

```
$ sudo systemctl start test
$ echo $?
0
$ sudo systemctl status test
● test.service
   Loaded: loaded (/etc/systemd/system/test.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-09-06 09:42:04 BST; 7s ago
  Process: 111 ExecStart=/bin/true (code=exited, status=226/NAMESPACE)
 Main PID: 111 (code=exited, status=226/NAMESPACE)

Sep 06 09:42:04 fedora-28 systemd[1]: Started test.service.
Sep 06 09:42:04 fedora-28 systemd[111]: test.service: Failed to set up mount namespacing: No such file or directory
Sep 06 09:42:04 fedora-28 systemd[111]: test.service: Failed at step NAMESPACE spawning /bin/true: No such file or directory
Sep 06 09:42:04 fedora-28 systemd[1]: test.service: Main process exited, code=exited, status=226/NAMESPACE
Sep 06 09:42:04 fedora-28 systemd[1]: test.service: Failed with result 'exit-code'.
```

**Describe the solution you'd like**

I imagine this issue is due to the lack of a readiness protocol for `Type=simple` services.  If this is the problem, I think there is a natural answer - define an internal readiness protocol :-).  I think we could make this to cover everything up to and including the final exec(), by using a pipe with the close-on-exec flag set.

EDIT: ah, the exec() part is genuinely tricky.  PID1 can wait for an error return from the exec() using this trick.  But the child's pipe being closed might instead mean we were killed at an earlier point e.g. by segfault.

So we can detect segfaults until just before exec().  Then we can write "good so far, about to exec" to the pipe.  Then if exec fails, we write "oops" to the pipe before exiting.

**Comment by lucaswerkmeister** [comment]
Isn’t this exactly the problem which the new `Type=exec` in v240 (#9620) solves? It even uses the same solution, a close-on-exec pipe.

**Comment by sourcejedi** [comment]
Thanks for the pointer!

In my original case I could have used `Type=oneshot`, but it was a quick test and I mistakenly thought it wouldn't matter.

It's a pity that `Type=simple` is still the default, but at least the updated doc makes it clear.

> But more importantly, blanket adopting Type=exec instead of Type=simple everywhere might potentially create deadlocks. Note that we resolve NSS and doe PAM between the fork() and in the execve().
