### ISSUE TITLE
Runnings tests with LXC/AppArmor -> detects legacy cgroup hierarchy

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10027]
Version: git master

When running the test-suite inside an LXC container with AppArmor enabled, I have several tests like this:
```
====== test-bpf =======
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
...
====== test-bus-creds =======
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
...
====== test-cgroup-util =======
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
...
====== test-engine =======
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
...
```
When running the same tests inside the LXC container but with AppArmor confinement disabled, I instead get
```
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
```

Is this expected or a bug?

**Comment by poettering** [comment]
uh, i don't have much idea about LXC and how it sets up stuff and how apparmor affects it. @brauner any idea?

@mbiebl what's the precise setup of /sys/fs/cgroup/ you are seeing in both cases? i.e. which mounts are precisely located there and below?

**Comment by mbiebl** [comment]
@brauner lxc is version 2.0.9-6.1, apparmor 2.13-8. The apparmor version seems pretty recent to me.

**Comment by brauner** [comment]
On Tue, Sep 11, 2018 at 03:47:25AM -0700, Michael Biebl wrote:
> @brauner lxc is version 2.0.9-6.1, apparmor 2.13-8. The apparmor version seems pretty recent to me.

As I said, the AppArmor profile must explicitly allow the cgroup2 mount
otherwise it will refuse it. That's the default AppArmor strategy.

Something like:

### Feature: cgroup namespace\n"
mount fstype=cgroup -> /sys/fs/cgroup/**,\n"
mount fstype=cgroup2 -> /sys/fs/cgroup/**,\n"

**Comment by mbiebl** [comment]
I read it like newer apparmor versions fixed that and given that apparmor in Debian is the latest version, I'm wondering if I'm missing  something?

**Comment by brauner** [comment]
On Tue, Sep 11, 2018 at 04:42:33AM -0700, Michael Biebl wrote:
> I read it like newer apparmor versions fixed that and given that apparmor in Debian is the latest version, I'm wondering if I'm missing  something?

No, it is an AppArmor rule that needs to be added. This has been done
in:
https://github.com/lxc/lxc/commit/1800f9247357948fd11c9da73b1943a8a7b6882b

which is not in 2.0.9. So you need to add it to the default AppArmor
profile that ships with Debian.

I do honestly wonder why that matters whether systemd is using the empty
unified or the legacy named systemd cgroup.

**Comment by poettering** [comment]
so where are we with this now?

**Comment by poettering** [comment]
Has this been fixed in LXC? Is this still an issue? Can we close this? @mbiebl? @brauner?

**Comment by poettering** [comment]
OK, closing, since it appears to be fixed.
