### ISSUE TITLE
test-catalog does not work as installed test as it hard-codes CATALOG_DIR

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10045]
test-catalog uses
```
         '', '', '-DCATALOG_DIR="@0@"'.format(build_catalog_dir)],
```
This absolute path is embedded into the binary. As a result, it does not really work as an installed test and the binary simply abort with an assertion when run from /usr/lib/systemd/tests/
Another side effect is, that it trips up our reproducibility checks in Debian. See
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908365#25

Given that, should we stop installing test-catalog or is there a way to avoid encoding an absolute path in the binary and make it also work when installed?

**Comment by yuwata** [comment]
Please test #10046.
