### ISSUE TITLE
USB Vendor ID 0x4255 Is Not GoPro

### ISSUE THREAD

**Issue by changyp6** [systemd/systemd#10049]
**systemd version the issue has been seen with**
>238

**Used distribution**
 >Fedora 28

**Expected behaviour you didn't see**
 >USB Vendor ID 0x4255 should be chip provider **Ambarella**

**Unexpected behaviour you saw**
 >USB Vendor ID 0x4255 is shown as _GoPro_

**Steps to reproduce the problem**

**Comment by poettering** [comment]
We regularly import the USB database from upstream here:

http://www.linux-usb.org/usb-ids.html

Please submit a fix there, we'll then update our version with the next release from there. Thank you.
