### ISSUE TITLE
Troubleshooting steps of systemd socket activation, systmd-journald, systemd-logind, dbus

### ISSUE THREAD

**Issue by rameshsahoo11** [systemd/systemd#10048]
**Is your feature request related to a problem? Please describe.**
I'm unable to get proper documentation on the internet for the troubleshooting steps of systemd socket activation. 

For example, removing '/etc/machine-id' creates problem to start systemd-journald and systemd-journald.socket Units. If we have to troubleshoot this, what would be the troubleshooting steps? 

What is the procedure to debug systemd socket Units ? 

Are there any troubleshooting steps available to debug DBUS and systemd-logind issue?

**Comment by yuwata** [comment]
> removing '/etc/machine-id' creates problem to start systemd-journald and systemd-journald.socket Units.

At least currently, /etc/machine-id must exists. Please do not remove the file.

In general, setting `systemd.log_target=debug` to kernel command line, or `Environment=SYSTEMD_LOG_LEVEL=debug` in the unit files you want to debug, produce many logs in journal. Please try them.

BTW, here is not a support forum. So, I will close this. If you have any concrete bugs, then please file them with relevant logs. Thank you.
