### ISSUE TITLE
systemctl revert doesn't undo edit --full for a "generator" unit

### ISSUE THREAD

**Issue by Forkest** [systemd/systemd#10053]
$ systemctl cat virtualbox.service
    # /run/systemd/generator.late/virtualbox.service
    # Automatically generated by systemd-sysv-generator
    ...
    $ sudo systemctl edit --full virtualbox.service

Revert doesn't work:

    $ sudo systemctl revert virtualbox.service
    $ systemctl cat virtualbox.service
    # /etc/systemd/system/virtualbox.service
    ...

Removing manually works:

    $ sudo rm /etc/systemd/system/virtualbox.service
    $ systemctl daemon-reload
    $ systemctl cat virtualbox.service
    # /run/systemd/generator.late/virtualbox.service
    ...

Is it by design?

**Comment by poettering** [comment]
Nope, this looks like a bug
