### ISSUE TITLE
systemd-boot hangs if no display is attached

### ISSUE THREAD

**Issue by p4block** [systemd/systemd#10052]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > PC completes POST and boots

**Unexpected behaviour you saw**
 > PC hangs at VGA POST (as indicated by motherboard debug lighting)

**Steps to reproduce the problem**
> Set systemd-boot as your bootloader and boot without a display attached

This issue could very much be hardware specific, here I am using an RX 480 and an Asus Z97-AR board. 
I suspect on a specific interaction with Asus's old UEFI code. 

This behavior has been long lasting (since systemd-boot is a thing, iirc) and it doesn't happen with rEFInd.

The issue is annoying because I use a DisplayPort monitor, and due to DP power savings, the monitor being off equals to the monitor not being there at all.

With this bug present, I cannot rely on WoL to access my computer from outside, or reboot it remotely.

**Comment by poettering** [comment]
hmpf. does playing around with "console-mode" in loader.conf make this work?

**Comment by p4block** [comment]
I tried all available modes and the behavior doesn't change.

Also, I want to note something that could have been confusing in my original report, this motherboard will light up the VGA error led if no monitors are present on boot. However, boot continues successfully on other bootloaders.

**Comment by poettering** [comment]
do you know where precisely it hangs? for that you'd probably have to add a bit of logging to sd-boot, rebuild, install, reboot...

I am not sure we can do much about this in the end, if the bios hangs on output it hangs on output...

**Comment by p4block** [comment]
Sadly, I'm not very knowledgeable in C, but just looking at the main method of the EFI app I see a few things I can poke. Will try commenting a few and report back.

**Comment by psottek** [comment]
I found the same issue on Gigabyte-AB350-gaming3, Ryzen and rx-460.
It is very annoying, because no watchdog, WoL not working without plugged monitor.
Maybe some options ?

**Comment by medhefgo** [comment]
Is this still an issue with systemd-boot v250?

**Comment by p4block** [comment]
@medhefgo Personally haven't had the issue for a long time. 
I know some uefis go and fake a screen if you don't plug anything in, but the amount of hardware I run at this point with systemd-boot and no screen attached is probably in the dozens now with 0 issues.

**Comment by poettering** [comment]
ok, let' close then.
