### ISSUE TITLE
Do not encode ABS_{BUILD,SRC}_DIR into binaries

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10065]
We do embed ABS_BUILD_DIR and ABS_SRC_DIR into libsystemd-shared and our test binaries:

```
meson.build:conf.set_quoted('ABS_BUILD_DIR',                              meson.build_root())
meson.build:conf.set_quoted('ABS_SRC_DIR',                                meson.source_root())
src/shared/tests.c:        r = path_startswith(s, ABS_BUILD_DIR);
src/journal/test-catalog.c:                assert_se(catalog_dir = path_join(NULL, ABS_BUILD_DIR, "catalog"));
src/shared/tests.c:                        assert_se(snprintf(testdir, sizeof(testdir), "%s/test", ABS_SRC_DIR) > 0);
```

This is problematic, as it breaks reproducible builds [1].
I've outlined two possible approaches for this:
https://github.com/systemd/systemd/pull/10046#issuecomment-420156375
and
https://github.com/systemd/systemd/pull/10046#issuecomment-420165657
 

[1] https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/systemd.html

**Comment by yuwata** [comment]
If I understand the discussion in #10046 correctly, this is just for CI tests?

**Comment by mbiebl** [comment]
It's for making the build reproducible, https://reproducible-builds.org/ has a bit more information on this topic. The idea is, that one should be able to produce bit-to-bit identical binaries from the same sources by making the build deterministic.
To test that, the package is built twice in a row. For the second build, the build environment is different: different timezone, date, build path, sort order of files is different (using disorderfs) and stuff like that.
The results are then compared. See also
https://wiki.debian.org/ReproducibleBuilds
