### ISSUE TITLE
Impossible to prepend/append to PATH using system-environment-generator

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#10068]
**systemd version the issue has been seen with**
> all

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > using a generator in C/python, I expect PATH variable to be set in the environment

**Unexpected behaviour you saw**
 > PATH is not set in certain cases
 * initramfsless-boot
 * lxd container

**Steps to reproduce the problem**
 * install a system-environment-generator
 * not a shell script (shells have built-in PATH if path is not set)
 * reboot container / initramfs-less boot
 * observe that PATH is not set, thus one cannot prepend/append things to it

I believe regular system generators are similarly affected.

Example bugs:
* cloud-init generator written as a shell script fails on Suse, as the /bin/sh built-in path lacks `sbin` dirs in the built-in path
* snapd environment generator that tries to append /snap/bin to PATH fails

I'm tracing this down to this:
 * main() calls `manager_new()` -> `manager_default_environment()`
 * later `manager_startup()`o is called which calls -> `manager_run_environment_generators()`
 * that in turns calls `execute_directories` and passes `&m->environment` as the target for `gather_environment`
 * However, `execute_directories` -> `do_execute` -> `do_spawn` -> uses `execv(path, argv)` instead of something like `execve` with `&m->environment` passed or copied.

Imho, `m->environment` should be passed to the generators, but I'm not sure of the implications of changing `execute_directories` by default. Would it be acceptable to extend `execute_directories` to allow passing an environment in?

**Comment by poettering** [comment]
i figure such a change would be OK an desirable. @keszybz ?

**Comment by xnox** [comment]
I am digging more into this. I think exec-v-vs-ve is irrelevant, and I think this can be fixed entirely inside the gather_environment callback thing.

Finding out how things exactly work with improved test cases! Stay tuned.

**Comment by dev-harsh1998** [comment]
I can confirm this issue thanks for pointing this out
