### ISSUE TITLE
Allow more fine-grained control for services via PolicyKit

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1006]
This is a followup for the discussion started on the mailing list at http://lists.freedesktop.org/archives/systemd-devel/2015-August/033964.html

If one wants to grant an unprivileged user the privilege to restart a given service, this is currently not possible, since the existing PolicyKit rules are too coarse-grained and only provide an all-or-nothing access.

This should be extended so the PolicyKit rules can be specified per unit.

**Comment by poettering** [comment]
This is implemented in #1159 now. Closing.
