### ISSUE TITLE
Q: how to run "installed tests"

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#10069]
This is a question or a possible RFE, depending on how things pan out.
I know the push to have installed tests came from the Debian/Ubuntu side. The tests are in `/usr/lib/systemd/test`, but it isn't obvious how to run all of them an report the status. Is there some "driver" to collect and run them?

/cc @mbiebl, @xnox, @martinpitt

**Comment by mbiebl** [comment]
fwiw, test-catalog can now be dropped from EXFAIL:
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/root-unittests#L6
Thanks to @yuwata fixing that in #10046

**Comment by xnox** [comment]
I wonder if some meson.build file should be shipped in /usr/lib/systemd/test such that one can use like meson & ninja to "run" the tests target. and like ship a wrapper script `systemd-selftest` or some such which would create tmpdir, run meson, and run ninja, to run the tests "as one would normally expect".
