### ISSUE TITLE
How to setup the timeout timer with the old d-bus version 

### ISSUE THREAD

**Issue by wenxuwan** [systemd/systemd#10075]
Dbus version:

My D-Bus version is D-Bus Message Bus Daemon 1.12.0

Probolem：
When i call sd_bus_message_new_method_call or sd_bus_call_method under high system IO, all the method will be timeout after 25s,  i want them return after 2s, how can i change the timeout timer. i have tried:
1. setenv("SYSTEMD_BUS_TIMEOUT","1",1); (does not work)
2. int sd_bus_set_method_call_timeout(sd_bus *bus, uint64_t usec); (Old version don't have the function)

So , anybody can tell me how to change the timeout ?

thanks

**Comment by yuwata** [comment]
The environment variable and the function was added in v239. It seems you use systemd older than v239, and the version of dbus not related.

So, please use v239 or recent snapshot.

Please understand that here is not a support forum. I will close this.

**Comment by wenxuwan** [comment]
hi
        when i use sd_event_run(event, (uint64_t) -1); with special timer(eg 1000), the sd_event_run doesn't work.

       r = sd_event_default(&event);
	r = sd_bus_attach_event(bus, event, SD_EVENT_PRIORITY_NORMAL);
	fprintf(stderr, "create success full\n");
	//r = sd_bus_add_match(bus, &slot, "type='signal'", NULL, NULL);
	m = sd_bus_call_method_async(bus,
							&slot,
							"org.freedesktop.systemd1", 
							"/org/freedesktop/systemd1", 
							"org.freedesktop.DBus.Properties", 
							"Get", 
							get_prpertys_handler, 
							event, 
							"ss",
							"org.freedesktop.systemd1.Manager",
							"SystemState"
							);
	//r = sd_event_loop(event);
	//ref = sd_event_ref(event);
	while (sd_event_get_state(event) != SD_EVENT_FINISHED){
		r = sd_event_run(event, (uint64_t) -1);
		if(r >= 0){
			break;
		}
	}

but when i use like this sd_event_run(event, (uint64_t) -1); the callback will be called, but if i use  sd_event_run(event, 1000); The callback can't be called.  

I want try 3s, and if failed, i want exist.

**Comment by wenxuwan** [comment]
Hi yuwata 

Can you give some comments for use it ?

My code:
int is_system_running(void){
    sd_bus  *bus = NULL;
    _cleanup_free_ char *state = NULL;
    int r = 0;
    r = acquire_bus(&bus);
    if(r == 0){
        HA_LOG(HA_LOG_LEVEL_WARN_E, LOG_MASK_COM_C, "sd_bus_open_system failed: %s\n",strerror(-r));
        return DVM_SYSTEM_STATE_READ_ERR;
    }
    r = sd_bus_get_property_string(
                    bus,
                    "org.freedesktop.systemd1",
                    "/org/freedesktop/systemd1",
                    "org.freedesktop.systemd1.Manager",
                    "SystemState",
                    NULL,
                    &state);
    if (r < 0){
        return DVM_SYSTEM_UNKNOWN;
    }else{
        if(streq(state, "running"))
            return DVM_SYSTEM_RUNNING;
        if(streq(state, "degraded"))
            return DVM_SYSTEM_DEGRADED;
        return DVM_SYSTEM_UNKNOWN;
    }
 
But when the system with high IO , sd_bus_get_property_string will bock for default 25s(systemd default time out timer) and my system will restart after 10s, so i want to change it with asyn method, and after 3s to return the result. 

Can you give some comments for this scenes with my systemd version is old.

Thanks

**Comment by wenxuwan** [comment]
Hi yuwata 

Can you give some comments for use it ?

My code:
int is_system_running(void){
    sd_bus  *bus = NULL;
    _cleanup_free_ char *state = NULL;
    int r = 0;
    r = acquire_bus(&bus);
    if(r == 0){
        HA_LOG(HA_LOG_LEVEL_WARN_E, LOG_MASK_COM_C, "sd_bus_open_system failed: %s\n",strerror(-r));
        return DVM_SYSTEM_STATE_READ_ERR;
    }
    r = sd_bus_get_property_string(
                    bus,
                    "org.freedesktop.systemd1",
                    "/org/freedesktop/systemd1",
                    "org.freedesktop.systemd1.Manager",
                    "SystemState",
                    NULL,
                    &state);
    if (r < 0){
        return DVM_SYSTEM_UNKNOWN;
    }else{
        if(streq(state, "running"))
            return DVM_SYSTEM_RUNNING;
        if(streq(state, "degraded"))
            return DVM_SYSTEM_DEGRADED;
        return DVM_SYSTEM_UNKNOWN;
    }
 
But when the system with high IO , sd_bus_get_property_string will bock for default 25s(systemd default time out timer) and my system will restart after 10s, so i want to change it with asyn method, and after 3s to return the result. 

Can you give some comments for this scenes with my systemd version is old.

Thanks

**Comment by yuwata** [comment]
Hmm? You seems not set time out by `sd_bus_set_method_call_timeout()`. Have you set by the environment variable?

**Comment by wenxuwan** [comment]
Hi yuwata

Really thanks for your response,
 I don't know there have an method to set method call timeout. I just try to use export SYSTEMD_BUS_TIMEOUT=10 in my enviroment, but it doesn't work. And i will try to use sd_bus_set_method_call_timeout() in my code. 

My test steps:
1.run my code(loop run sd_bus_get_property_string method)
2.ps -aux | grep dbus-daemon
3.kill -19 dbus-dameon Id

The code will be block on sd_bus_get_property_string. I want the method exist after 3s. The method sd_bus_set_method_call_timeout() can be work for this scene?

Thanks

**Comment by wenxuwan** [comment]
Hi 

Mysdbus version is too old, and there don't have the sd_bus_set_method_call_timeout()..


bus_client.c: In function ‘is_system_running’:
bus_client.c:15:5: warning: implicit declaration of function ‘sd_bus_set_method_call_timeout’; did you mean ‘sd_bus_get_timeout’? [-Wimplicit-function-declaration]
     sd_bus_set_method_call_timeout(bus,3);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     sd_bus_get_timeout
/tmp/ccuRqhnL.o: In function `is_system_running':
bus_client.c:(.text+0x64): undefined reference to `sd_bus_set_method_call_timeout'
collect2: error: ld returned 1 exit status

If there have another method to implement the function  without update the version of dbus

Thanks

**Comment by yuwata** [comment]
Please use `sd_bus_message_new_method_call()+sd_bus_call()`. `sd_bus_call()` can take timeout.
See bus-convenience.c

BTW, please understand here is not a support forum, but a bug tracker...

**Comment by wenxuwan** [comment]
Hi yuwata 

Thanks for your response, I will try the method follow your comment, BTW, where is the support forum, it just because i can't find the support forum, i raise an bug here. And really thanks for your help.

**Comment by yuwata** [comment]
From README,
> If you are looking for support, please contact our [mailing list](https://lists.freedesktop.org/mailman/listinfo/systemd-devel) or join our IRC channel.
