### ISSUE TITLE
detect_vm_uml() fails on large systems

### ISSUE THREAD

**Issue by justinrernst** [systemd/systemd#10074]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > sles12sp3

**Expected behaviour you didn't see**
 > "systemd-detect-virt -v" returns "none"
 > services that depend on ConditionVirtualization start

**Unexpected behaviour you saw**
 > "systemd-detect-virt -v" returns "Failed to check for VM: Argument list too long"
 > services that depend on ConditionVirtualization fail to start: ConditionVirtualization=false was not met

**Steps to reproduce the problem**
I've found the reason for this failure:
detect_vm_uml() reads /proc/cpuinfo with read_full_file() 
read_full_file() has a file max limit size of READ_FULL_BYTES_MAX=(4U\*1024U\*1024U)
Unfortunately, the size of my /proc/cpuinfo is bigger, approximately:
echo $(( 4* $(cat /proc/cpuinfo | wc -c)))
9918072
This causes read_full_file() to fail and the Condition test fallout.

I'm unsure of a proper fix. Is there a reason we have to read in the entire /proc/cpuinfo file? If not, one solution would be to read in a smaller amount of /proc/cpuinfo, or read in just the first CPU's info. 

Thanks

**Comment by keszybz** [comment]
Can you attach your `/proc/cpuinfo` file here for testing?

**Comment by justinrernst** [comment]
Here is my /proc/cpuinfo cat into a file.
[cpuinfo-justin.txt](https://github.com/systemd/systemd/files/2380426/cpuinfo-justin.txt)

**Comment by poettering** [comment]
Let's close this as #10076 has been merged.
