### ISSUE TITLE
systemd-resolved should use per-link dns to handle reverse dns lookups

### ISSUE THREAD

**Issue by witosx** [systemd/systemd#10081]
**Is your feature request related to a problem? Please describe.**
Lets say I have two interfaces:

internet0:
- address: 10.0.0.100/24
- dns: 10.0.0.1

mynet0:
- address 172.20.100.100/14
- dns: 172.20.0.1
- domain: ~mynet.com

With this setup I execute ping command:    
`ping somehost.mynet.com`
    
- It knows that mynet.com is a routing-only domain on mynet0, so it will query 172.20.0.1 for IP of somehost
- DNS answers with 172.20.100.101
- ping request is sent to 172.20.100.101
- ping reply is received from 172.20.100.101
- ping does reverse dns lookup (101.100.20.172.in-addr.arpa), but it will go to 10.0.0.1 which doesn't know about my local network

(Yes, I know I can use ping -n to skip reverse lookup)

**Describe the solution you'd like**
There should be some option to allow resolved to use per-link dns when it sees a reverse dns lookup matching given subnet

For now I have to manualy write reverse route-only domains, which in this case (172.20.0.0/14) are:
- ~20.172.in-addr.arpa
- ~21.172.in-addr.arpa
- ~22.172.in-addr.arpa
- ~23.172.in-addr.arpa

**Comment by poettering** [comment]
Fixed by #18613
