### ISSUE TITLE
Typo in os-release(5) man page

### ISSUE THREAD

**Issue by mikeweilgart** [systemd/systemd#10083]
**systemd version the issue has been seen with**
> 239

There is a typo in the os-release(5) man page.  The line:

> Links to resources on the Internet related the operating system.

is missing the word "to."

(On a related note, I can not find the man page sources for systemd, nor an easy reporting process for simple typos such as this.)

**Comment by yuwata** [comment]
Please update https://github.com/systemd/systemd/blob/master/man/os-release.xml.
