### ISSUE TITLE
TEST-02-CRYPTSETUP randomly fails

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#10093]
Please see https://github.com/systemd/systemd/pull/10070#issuecomment-421354500.

**Comment by evverx** [comment]
The test is going to be skipped on Ubuntu CI (https://salsa.debian.org/systemd-team/systemd/commit/2c194b155b1e97e) but the flakiness is still here so the issue probably should be kept open.

**Comment by keszybz** [comment]
Let's close this. I haven't seen TEST-02-* failing in a while. This might be the same issue as  #10179, and if not, we're better off with a new bug with no stale history.
