### ISSUE TITLE
test-barrier seems to be failing sporadically

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10092]
Since f57d003cb6ccda702d2 was merged `test-barrier` has been failing sporadically. I'm not sure why the test has been made "slow" because judging by the comment that was removed the test isn't slow, but flaky.

**Comment by yuwata** [comment]
I've never seen that. Could you give any logs?

**Comment by yuwata** [comment]
Ah, so you mean that the test should be a manual test?

**Comment by evverx** [comment]
The most frequent failure seems to be the following:
```
Assertion 'WIFEXITED(status)' failed at ../src/test/test-barrier.c:210, function test_barrier_wait_next_twice_sync(). Aborting.
Aborted
```
but I also saw at least another one. If it's OK for a manual test to be flaky, I think it should be manual :-)

**Comment by evverx** [comment]
Having read [the rationale behind turning the test off](https://github.com/systemd/systemd/commit/fd23f9c9a70e1214507641d327da40d1688b74d7), I'm pretty sure it should be disabled again. Apart from what is written there, the test isn't quite ready to be run under ASan/Varlgrind because the timeouts aren't adjusted accordingly. I guess making it "manual" would make sense (as far as I can tell, "manual" is just a way to say that a test is almost never run or fails if you don't happen to have "/home/lennart/projects" :-)) I'll try to send a patch next week.

**Comment by evverx** [comment]
I was going to send a patch but at the time I was in the process of turning off the testing infrastructure I used and the part of it where the tests were run under ASan was [the next in the queue](https://github.com/systemd/systemd/pull/10678#issuecomment-436787267) so I didn't even bother :-) If you sent a PR I'd approve it.
