### ISSUE TITLE
systemd-ask-password should allow entering a TAB character

### ISSUE THREAD

**Issue by rsteppleton** [systemd/systemd#10100]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > TAB is a regular character. Pressing TAB key should produce a character in input, just like any other key.

**Unexpected behaviour you saw**
 > TAB key is treated as a UI control key rather than a character input key. Passwords including a TAB character are impossible to enter.

**Steps to reproduce the problem**
Press TAB key while inputting a password. A change in behavior of the dialog is triggered instead of a TAB character being entered.

**Comment by lucaswerkmeister** [comment]
> Press TAB key while inputting a password. A change in behavior of the dialog is triggered instead of a TAB character being entered.

To clarify: the change in behavior is that the tool switches into no-echo mode (the default is to mask the input with asterisks). How should that change be triggered instead?

One possibility would be that pressing backspace when there is nothing to erase has this effect; I feel like I remember some password input doing that, but I can’t recall which.

**Comment by rsteppleton** [comment]
> To clarify: the change in behavior is that the tool switches into no-echo mode (the default is to mask the input with asterisks). How should that change be triggered instead?

In my opinion this is something that should not be part of the UI at all. 

But for the sake of argument, the backspace option is more or less ok, or maybe pressing ESC or PrintScreen or some other key that is supposed to be a "control" key, rather than "input" key. By "input" key I mean a key that, under common circumstances, generates an actual non-control input, such as character keys, backspace/delete (deleting a character is part of common input imo) and whitespace characters (excl. carriage return/line feed of course).

Maybe pressing a ctrl, super, or other "mod" key can temporarily switch to echo mode if it is disabled. 

PrintScreen is actually the best candidate I can think of right now.

**Comment by poettering** [comment]
Quite frankly I very much disagree with this request. We are using TAB for this as almost all UIs I ever have known bind it to some non-text action, i.e. on graphical UIs it almost always moves the input focus from one widget to the next. I am not sure it's worth supporting something here that is generally not supported in other, similar UIs either. Or to say this differently: if you can tell me how I'd unlock such a disk with let's say gnome-disks, then I'd be a lot more interested...

I am not sure we need to support non-textual passwords like this. If you want to support arbitrary binary disk keys, then the ask-password stuff is really not the way to input it anyway. It's supposed to be a middle ground, somewhat low-level but also slightly user-friendly way to input passwords, and that's all.

**Comment by poettering** [comment]
> PrintScreen is actually the best candidate I can think of right now.

PrintScreen is not known by classic terminals, i.e. VT100 and friends, and hence i nothing we genreally can process on the console. TAB is universally supported by text consoles however, and generally non-textual and hence a somewhat suitable key for our needs.
