### ISSUE TITLE
crypsetup stuff is still running after entering in emergency mode

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#10131]
If for any reason `local-fs.target` fails at startup while a password is requested by `systemd-cryptsetup@.service`, we end up with the emergency shell competing with `systemd-ask-password-console.service` for the console.

Another issue is that `systemd-cryptsetup@.service` is still running while in emergency mode. This means that the password won't be prompted again after exiting from the emergency shell.

A quick fix would be to conflict systemd-cryptsetup@.service as well as systemd-ask-password-console.service with emergency.target but I'm not sure this is the right thing to do...

**Comment by arvidjaar** [comment]
I confirm it. It makes it literally impossible to log in in emergency mode.

> A quick fix would be to conflict `systemd-cryptsetup@.service` ...  with `emergency.target` 

If root itself is encrypted, it will attempt to stop `systemd-cryptsetup@root.service`. It will probably fail but it means this is not clean. It will also tear down all filesystems on encrypted containers, which likely is not what we want.

> as well as `systemd-ask-password-console.service`

What if you want to start encrypted container while in emergency mode?

**Comment by fbuihuu** [comment]
Another option might be to use `OnFailureJobMode=isolate` in `local-fs.target`, after all no services are supposed to run in emergency mode according to systemd.special(7).

**Comment by fbuihuu** [comment]
> Another option might be to use OnFailureJobMode=isolate in local-fs.target

well that's not an option since we want to keep `systemd-cryptsetup@.service` alive if we switch to a different runlevel for example.

**Comment by arvidjaar** [comment]
> Another option might be to use `OnFailureJobMode=isolate` in `local-fs.target`

This was used in the past and explicitly changed to preserve failure conditions. See 80cfe9e163b1c92f917e0a5e053b148fca790677.

> after all no services are supposed to run in emergency mode

With all respect - `systemd-cryptsetup` are not services, they are integral part of device.

**Comment by poettering** [comment]
I am tempted to say that systemd-ask-password-console.service should just add Conflicts= on systemd-ask-password-console.service, and that's it. i.e. all our services that use `tty-force` as output should kick off other console users first...

I don't think it's necessary/disarable to kick out systemd-cryptsetup, as this might mean block devices are torn down, too, which is not really desirable.

**Comment by fbuihuu** [comment]
> and that's it. i.e. all our services that use tty-force as output should kick off other console users first...

I was wondering if there's a way for the process having the controlling terminal to get notified (via signal or another mechanism) if another process steals the controlling terminal.

> I don't think it's necessary/disarable to kick out systemd-cryptsetup, as this might mean block devices are torn down, too, which is not really desirable.

At least systemd-cryptsetup needs to deal with the case it waits for the password and the password agent get killed. In this case systemd-cryptsetup should exit too so it is properly restarted when exiting from the emergency shell for example.

**Comment by poettering** [comment]
> > and that's it. i.e. all our services that use tty-force as output should kick off other console users first...
> 
> I was wondering if there's a way for the process having the controlling terminal to get notified (via signal or another mechanism) if another process steals the controlling terminal.

kernel sends SIGHUP (that is in fact how SIGHUP is originally defined), but it's messy.

**Comment by poettering** [comment]
> At least systemd-cryptsetup needs to deal with the case it waits for the password and the password agent get killed. In this case systemd-cryptsetup should exit too so it is properly restarted when exiting from the emergency shell for example.

systemd-cryptsetup doesn't care what happens to password agents, and how many are running. It just enqueues its query and waits until some agent replies. This should be pretty robust, but is also pretty dumb

**Comment by fbuihuu** [comment]
@arvidjaar I prep a fix in #10172, could give it a try ? Thanks.
