### ISSUE TITLE
RFE: CI by Coverity

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#10180]
I am not sure it is possible, but I hope that PRs are also checked by Coverity.
Sometimes, a PR merged, then soon after Coverity reports new defects. It is ok, as we usually fix soon later (does't it? I hope so). But if it is reported _before_ the merge, then it is better.

**Comment by evverx** [comment]
That would definitely be great, but, unfortunately, the number of weekly builds is [limited](https://scan.coverity.com/faq#frequency), which makes it impossible to send data to Coverity Scan every time a new PR is opened.

**Comment by yuwata** [comment]
Oh...

**Comment by evverx** [comment]
That limit aside, I'm not sure Coverity Scan's UI is ready to show defects fixed and introduced in a PR in a way that would be similar to, for example, LGTM's UI, so probably sending builds of the master branch once a day is the best we can do right now (and probably in the foreseeable future).

**Comment by keszybz** [comment]
Yeah, I think this is good enough. Coverity also restricts access, so it's unlikely that this will possible unless coverity significantly changes their policies. Let's close this, and reopen if this ever becomes possible.
