### ISSUE TITLE
Failed state DBUS notification not received on sigkill of service

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#10185]
**systemd version the issue has been seen with**
> ...

**Used distribution**
 >230

**Expected behaviour you didn't see**
 >
Failed state DBUS notification not received on sigkill of service for service that supports restart

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
send sigkill to a service that supports restart

Failed state DBUS notification  for  ActiveState property
is not received on  sigkill of service, for the service that supports restart ('Restart' value in service faile). But i see that unit goes to failed state in journal logs

++
Sep 25 08:52:00 mynode systemd[1]: alarmd.service: Unit entered failed state.
Sep 25 08:52:00 mynode systemd[1]: alarmd.service: Triggering OnFailure= dependencies.
Sep 25 08:52:00 mynode systemd[1]: alarmd.service: Failed with result 'signal'.
Sep 25 08:52:00  mynode   systemd[1]: alarmd.service: Service hold-off time over, scheduling restart.
Sep 25 08:52:00  mynode   systemd[1]: Stopped "Alarm agent on RE".
Sep 25 08:52:00  mynode   systemd[1]: Started "Alarm agent on RE".
++

Logs from my app which monitors dbus notifications:
+++
Updated Result=signal for service alarmd.service in cache contents: activeState=active subState=running result=signal" }
Updated ActiveState=deactivating for service alarmd.service in cache contents: activeState=deactivating subState=running result=signal" }
Updated SubState=stop-post
Updated Result=signal for service alarmd.service in cache contents: activeState=deactivating subState=stop-post result=signal" }
Updated ActiveState=activating for service alarmd.service in cache contents: activeState=activating subState=stop-post result=signal" }
Updated SubState=auto-restart for service alarmd.service in cache contents: activeState=activating subState=auto-restart result=signal" }
Updated Result=success for service alarmd.service in cache contents: activeState=activating subState=auto-restart result=success" }
Updated ActiveState=active for service alarmd.service in cache contents: activeState=active subState=auto-restart result=success" }
Updated SubState=running for service alarmd.service in cache contents: activeState=active subState=running result=success" }
+++++

If service does not support restart (Restart=no), then I see that we get  Failed state DBUS notification , as  ' ActiveState=failed '.
Logs from my app which monitors dbus notifications:
++
Updated Result=signal for service alarmd.service in cache contents: activeState=deactivating subState=stop-post result=signal" }
Updated ActiveState=failed for service alarmd.service in cache contents: activeState=failed subState=stop-post result=signal" }
Updated SubState=failed for service alarmd.service in cache contents: activeState=failed subState=failed result=signal" }
++

**Comment by poettering** [comment]
hmm, indeed we internally pass through "failed" but we don't report this on the bus

**Comment by poettering** [comment]
fix waiting in #10963
