### ISSUE TITLE
Set a next best time when the device is missing time

### ISSUE THREAD

**Issue by kwizart** [systemd/systemd#10195]
**Is your feature request related to a problem? Please describe.**
On device missing rtc (and network, so no ntp). It's difficult to have a reliable source for time. This is often the case on armhfp where there is no battery backed rtc or even when network requires a certificate (that relies on time) to authenticate and have access to an accurate time source.

In the current situation, if the time is older than the systemd build time, time is set at this systemd build time. This is a partial workaround, because few issues remains:
- journalctl entries from several boot are mixed
- There is a bigger time gap to fill when the time is corrected.
- The system might store a better reliable source for the "last seen time".

**Describe the solution you'd like**
When there is no accurate source for time (ntp,rtc), systemd might set time based on the last journalctl time entry. (after the switch_root step) It would be a better alternative than using the systemd build time.
Alternative would be to use the last mounted time for the root device.

**Describe alternatives you've considered**
There are many projects that tries to workaround this issue by using a script that store a timestamps in the filesystem every few minutes, so the "last time seen" can be recovered on the next boot.
Simply writing the timestamps on shutdown would not always worked because in case of a crash, the timestamps wouldn't be set.

Also another corner case to have in mind is that some battery backed rtc are using a specific external kernel module. So the time isn't accurate when the kernel load the initrd (where the rtc module might be).
Once the module is loaded (during the initramfs) the system time is still wrong, because there is a need to explicitely run hwclock -rf /dev/rtc0
There is maybe a way to automatically update the system time when the rtc module is loaded ? (like in a deffered probe procedure ?)
Right now the workaround is to bundle hwclock and a systemd unit in the initramfs and set it as an early target, but it's difficult to know the condition when to apply this workaround.

**Comment by poettering** [comment]
> When there is no accurate source for time (ntp,rtc), systemd might set time based on the last journalctl time entry. (after the switch_root step) It would be a better alternative than using the systemd build time.
> Alternative would be to use the last mounted time for the root device.

This is actually already implemented by timesyncd. Instead of using the journal or supreblock timestamp we use a touch file for this, specifically /var/lib/systemd/timesync/clock. 

However, that file is only looked at after /var has become available, which might be later during boot.

Closing, as we already have this and it should be good enough for this, afaics. Or are you missing something regarding this?
