### ISSUE TITLE
There should be way to assign ipv6 addresses locally from delegated prefixes

### ISSUE THREAD

**Issue by vanaf** [systemd/systemd#10199]
**Is your feature request related to a problem? Please describe.**
Usually the only source for global ipv6 connectivity is DHCPv6 PD. We are already able to route delegated prefix to proper interface and to announce it using RAs. But on our host itself there is still no ipv6 connectivity, we still don't have addresses assinged from this prefix to ourselfs.

**Describe the solution you'd like**
It would be great to be able to specify per-interface address postfix to be added to interface's prefix and assigned to this interface.

**Describe alternatives you've considered**
Maybe another solution will be receiving and processing RAs from ourselfs.

**Comment by wget** [comment]
@vanaf Hello there. I'm currently porting to the excellent systemd-networkd my Stateless DHCP with DUID + SLAAC configuration based on ifupdown + dhclient.
My working ifupdow+dhclient config: https://gist.github.com/wget/186a0489a0a751260444a5c09af7be49
My non working systemd config:
https://gist.github.com/wget/37d7f0a94befdfda13708093c453afda

However, when I restart the systemd-networkd service, I can see with tcpdump/radvdump the DUID id not being sent. And therefore, I'm not receiving an RA and the IPv6 address is not being defined to the interface. Any idea of what I'm missing here?

The configuration is a VM on a hypervisor. The hypervisor gets a /56 properly, and I receive a /64 on the host with ifupdown+dhclient. Haven't succeeded with systemd yet. I have tried on two VMs: a Debian 9 (systemd 232) and on Arch Linux (systemd 238) without much results.

Wondering if the issue I have is related to this one. Or Maybe I'm just missing something in my config?

**Comment by wget** [comment]
@vanaf Ok. Maybe I'm not able to receive the PD properly because v 239 doesn't have the needed code integrated. https://github.com/systemd/systemd/pull/9981
Maybe this should be sorted out with a new systemd release.
Correct me if I'm wrong :-)

**Comment by wget** [comment]
@vanaf About this bug, yeah, this is pretty annoying because we have to define the IPv6 address manually to the interface while systemd networkd should infer it for us from the prefix he receives and take by default a /128 like what we have with ifupdown + dhclient on Debian.

**Comment by vanaf** [comment]
I've checked with 
net.ipv6.conf.br0.accept_ra_from_local=1
net.ipv6.conf.br0.autoconf=1
still no success

**Comment by poettering** [comment]
I guess #15259 implements this.

**Comment by vanaf** [comment]
Yes, looks like it is! Thanks a lot!

**Comment by wget** [comment]
Wow. Thanks a lot ! 🎉

This is huge news as it could be the opportunity for projects like Proxmox VE to start a great switch from ifupdown to systemd-networkd.👌

Sure it means we will have to wait for Debian 11, but at least, #15259 will avoid systemd detractors to open their mouths against using systemd-network for containers deployments 💪  I'm looking at you, [put a big French cloud provider here]. 👀
