### ISSUE TITLE
tmpfiles removal is not ordered for related paths

### ISSUE THREAD

**Issue by jameysharp** [systemd/systemd#10191]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > NixOS

**Expected behaviour you didn't see**
 > `tmpfiles.d(5)` says, "When two lines are prefix and suffix of each other, then the prefix is always processed first, the suffix later," but I would expect removals to be in exactly the opposite order: `systemd-tmpfiles --remove` with two `r` entries where one is a suffix of the other should remove the suffix first and then the parent, regardless of what order they're specified in the input file.

**Unexpected behaviour you saw**
 > The removal order apparently depends strictly on the order in which entries appear in the input file.

**Steps to reproduce the problem**

This fails to delete `/tmp/test-prefix`:

```sh
mkdir /tmp/test-prefix
touch /tmp/test-prefix/file
systemd-tmpfiles --remove - <<EOF
r /tmp/test-prefix
r /tmp/test-prefix/file
EOF
```

While this successfully deletes both paths:

```sh
mkdir /tmp/test-prefix
touch /tmp/test-prefix/file
systemd-tmpfiles --remove - <<EOF
r /tmp/test-prefix/file
r /tmp/test-prefix
EOF
```

**Comment by poettering** [comment]
Fix waiting in #10858
