### ISSUE TITLE
[DOC] No mention of systemctl suspend-then-hibernate in man page of systemctl

### ISSUE THREAD

**Issue by jdorel** [systemd/systemd#10192]
**systemd version the issue has been seen with**
> systemd 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Indication that systemctl suspend-then-hibernate exists and what it does in systemctl man page.

**Steps to reproduce the problem**
```
man systemctl | grep suspend-then-hibernate # Output is empty
```
I would make a pull request, but I don't know if the following statements in suspend, hibernate and hybrid-sleep is also true:
```
This command is asynchronous, and will return after the suspend operation is successfully enqueued. It will not wait for the suspend/resume cycle to complete.
```

**Comment by keszybz** [comment]
On Fri, Sep 28, 2018 at 01:11:29AM -0700, Jonas DOREL wrote:
> This command is asynchronous, and will return after the suspend operation is successfully enqueued. It will not wait for the suspend/resume cycle to complete.

It's also true in this case.

**Comment by jdorel** [comment]
I tried to document it in the following pull request:
systemd/systemd#10194
