### ISSUE TITLE
Add support for U2F dongles to udev

### ISSUE THREAD

**Issue by davidstrauss** [systemd/systemd#102]
I'm currently adding this rule (which I obtained from someone else) so I can use my YubiKey Neo's U2F support with Google Chrome -- or any other regular user application:

```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"
```

**Comment by poettering** [comment]
See:

http://lists.freedesktop.org/archives/systemd-devel/2014-November/024824.html

Their plan is to write a proper U2F driver for this, without using hidraw.
