### ISSUE TITLE
polkit prompts are not localized

### ISSUE THREAD

**Issue by piotrdrag** [systemd/systemd#10209]
**systemd version the issue has been seen with**
> systemd-239-3.fc29.x86_64

**Used distribution**
 > Fedora 29

**Expected behaviour you didn't see**
 > polkit prompts in my language.

**Unexpected behaviour you saw**
 > polkit prompts in English.

![zrzut ekranu z 2018-09-29 23-08-53](https://user-images.githubusercontent.com/139229/46250567-8ea49500-c43d-11e8-9486-c3f1d5e75b7a.jpg)

**Steps to reproduce the problem**
> 1. Boot with LANG=pl_PL.UTF-8
> 2. $  systemctl mask livesys

**Comment by mbiebl** [comment]
po/pl.po has translations for those strings.
I suspect that polkitd is not picking up the locale you want.

**Comment by mbiebl** [comment]
What does ```cat /proc/$(pidof polkitd)/environ``` say

**Comment by piotrdrag** [comment]
```
LANG=pl_PL.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binINVOCATION_ID=eb6af55243b940bc9ac68f741a881bd3JOURNAL_STREAM=9:22503
```

Other (non-systemd) polkit prompts I tested are localized correctly.

**Comment by mbiebl** [comment]
Works fine here, fwiw. I suspect that this is not a systemd issue but related to gnome-shell or one of its dependencies.
systemd does not embed the translations into the .policy files as most other .policy files do. The translations are shipped in /usr/share/locale/*/LC_MESSAGES/systemd.mo and the .policy file references them via ```gettext-domain="systemd"```

**Comment by piotrdrag** [comment]
When #8162 was introduced, I suspected that it may not work well in non-Debian distributions. On the other hand, I don’t have any Fedora installations before that change to test, so I don’t know if maybe it never worked in its GNOME Shell.

**Comment by mbiebl** [comment]
I just pulled the F29 beta life CD and the polkit prompts are properly localized there. So this looks like F28 specific issue and I think it's best to raise it there.

**Comment by piotrdrag** [comment]
I am on Fedora 29. I’m going to look into reporting it downstream, though.

**Comment by mbiebl** [comment]
![screenshot_fedora29_2018-09-30_19 53 10](https://user-images.githubusercontent.com/3609611/46260772-82c2dc80-c4ea-11e8-9fad-6f5c0a9dda5c.png)

**Comment by piotrdrag** [comment]
Weird, `systemctl restart systemd-journal` is localized here as well. It’s coming from a .c file, though, not .policy.

**Comment by mbiebl** [comment]
Does the Fedora systemd package do something special regarding translations? Does it pull additional translations from somewhere?

**Comment by mbiebl** [comment]
ok, seems the F29 live system does not show localized content for mask here as well (whereas it does on my Debian sid system)

**Comment by piotrdrag** [comment]
It doesn’t, as far as I can tell: https://src.fedoraproject.org/rpms/systemd/tree/f29

**Comment by mbiebl** [comment]
@piotrdrag For testing purposes I tried an openSUSE Leap 15.0 live system and it works fine as well.
This doesn't really help to nail down the issue but at least it hints at a Fedora specific problem.

**Comment by poettering** [comment]
we only provide the translations, we are not involved in picking the right ones, that's between polkit and gnome-shell really.

(i am pretty sure something is seriously hosed there though as on my system which runs with LANG=de_DE.UTF-8 but LC_MESSAGES=C.UTF-8 — i.e. german everything except for the message strings which shall be displayed in their untranslated original — i usually get translated polkit queries. i.e. it appears that polkit's translation logic does not correctly honour LC_MESSAGES and only honours LANG)

Anyway, please file this against polkit/gnome-shell in your distribution.
