### ISSUE TITLE
kdbus: systemd user instance installs too many matches

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1020]
With systemd 53496ca and current kdbus, I get lots of errors from my user instance that look like this:

```
systemd[942]: Failed to subscribe to NameOwnerChanged signal: Too many open files
systemd[942]: dbus-org.freedesktop.FileManager1.service: Cannot watch bus name org.freedesktop.FileManager1: Too many open files
```

I have 133 generated busname units. systemd v224 is fine. Reverting bbc2908 seems to solve this problem.

**Comment by zonque** [comment]
Yes, this limit needs a bump on the kernel side. Now that we track each client individually, we need to allow the peers to install more matches.

**Comment by dvdhrm** [comment]
You get that warning roughly ~12 times, right?

Feel free to bump `ipc/kdbus/limits.h: KDBUS_MATCH_MAX` to something like 2048.

**Comment by heftig** [comment]
No, I get it 66 times.

**Comment by heftig** [comment]
systemd v225 + latest kdbus (with raised match limit) seem to have solved the issue.

**Comment by mbiebl** [comment]
@dvdhrm this can be closed then, right? It's basically the same issue as #1137

**Comment by dvdhrm** [comment]
Yes, the patch is pending on LKML and should go upstream once Greg is back.

Thanks for the patience!
