### ISSUE TITLE
meson: 'ccache cc' not found

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#10211]
When I try to setup a new build directory, then I get the following:
```
src/boot/efi/meson.build:163:8: ERROR:  Program or command 'ccache cc' not found or not executable
```
This is caused by df7cacae696ae3c1d13d2f9a4db24815e07e29a1, reverting the commit fixes this issue.

**Comment by yuwata** [comment]
cc @helmutg.

**Comment by floppym** [comment]
@yuwata Please give my patch a try.

**Comment by yuwata** [comment]
@floppym Thank you!
