### ISSUE TITLE
[machined] enhanced error output for machinectl pull-*

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#10215]
**Is your feature request related to a problem? Please describe.**
There are several moments, where more verbose error output would be nice. For example:

When pulling images or tarballs via `machinectl pull-raw` or `machinectl pull-tar` there is no error output. So if your target server has an invalid TLS certificate and you start pulling from it you will get the following output:
```
❯ sudo machinectl pull-raw https://ritsuko.nullday.de/archlinux/image.raw.xz --verify=signature test
Enqueued transfer job 1. Press C-c to continue download in background.
```

You can test the line above. (I didn't fixed the error on my server yet)

Another example is, when you try to use `machinectl pull-tar` on a raw image, machinectl will show the same output as above without any error message.

**Describe the solution you'd like**
I would like to have a --debug or --verbose flag for machinectl transfer operations for better debugging for errors. This includes debugging of wrong checksum files or invalid signatures of `SHA256SUMS.gpg` files.

**Describe alternatives you've considered**
The current alternative is curling all files before pulling them via `machinectl pull-*` and checking if everything would work..

**Comment by yuwata** [comment]
???
```
$ sudo machinectl pull-raw https://ritsuko.nullday.de/archlinux/image.raw.xz --verify=signature test
Enqueued transfer job 2. Press C-c to continue download in background.
Pulling 'https://ritsuko.nullday.de/archlinux/image.raw.xz', saving as 'test'.
Transfer failed: Peer certificate cannot be authenticated with given CA certificates
Transfer failed: Peer certificate cannot be authenticated with given CA certificates
Settings file could not be retrieved, proceeding without.
Transfer failed: Peer certificate cannot be authenticated with given CA certificates
Failed to retrieve image file. (Wrong URL?)
Exiting.
```
```
$ sudo machinectl pull-raw https://ritsuko.nullday.de/archlinux/image.raw.xz test
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'https://ritsuko.nullday.de/archlinux/image.raw.xz', saving as 'test'.
Transfer failed: Peer certificate cannot be authenticated with given CA certificates
Failed to retrieve SHA256 checksum, cannot verify. (Try --verify=no?)
Exiting.
```

**Comment by shibumi** [comment]
Hi @yuwata  check my asciinema: https://asciinema.org/a/3H5SAZYAuJgJJlWo6mZvc6uF3 
Do you have any idea why you get such error output and I don't get it?

**Comment by yuwata** [comment]
> are you running a newer version of systemd?

v239+ (a507737).

**Comment by yuwata** [comment]
Ah, v239 has a bug, and it is already fixed.

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/pull/9536

**Comment by shibumi** [comment]
so the bug is definitely in the v239 release? Can you also test pulling a raw image via `pull-tar`? This doesn't produce error output as well (but it should)

**Comment by yuwata** [comment]
`pull-tar` also shows verbose message similar to the above.

**Comment by shibumi** [comment]
Ok cool. Then I can close this issue here :) I should start searching for issues first, before I open one.
