### ISSUE TITLE
[machined] machinectl pull-raw --verify=signature does not work

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#10216]
**systemd version the issue has been seen with**
systemd 239
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 `machinectl pull-raw http://ritsuko.nullday.de/archlinux/image.raw.xz --verify=signature test` should download the raw image, decompress it, check the signature and checksum and import it to `/var/lib/machines/`

**Unexpected behaviour you saw**
The download process will run (according to the tool wireshark), but the image will not get imported and I have no debugging output why. Enhanced debugging or error output would be nice.

**Steps to reproduce the problem**
Get the public key for the checksum file:
```
# cd /etc/systemd/
# curl http://ritsuko.nullday.de/archlinux/import-pubring.gpg -O
```

Then run the following line:
```
$ sudo machinectl pull-raw http://ritsuko.nullday.de/archlinux/image.raw.xz --verify=signature test
```

According to `machinectl list-transfers` it will start downloading, but there will no import happen.

**Comment by shibumi** [comment]
@yuwata is this fixed here as well?

**Comment by yuwata** [comment]
I hope so. Though, the download has not finished yet. Now, my network is very slow...
```
$ sudo machinectl pull-raw http://ritsuko.nullday.de/archlinux/image.raw.xz --verify=signature test
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'http://ritsuko.nullday.de/archlinux/image.raw.xz', saving as 'test'.
Downloading 169B for http://ritsuko.nullday.de/archlinux/image.raw.xz.sha256.
Downloading 169B for http://ritsuko.nullday.de/archlinux/image.nspawn.
HTTP request to http://ritsuko.nullday.de/archlinux/image.nspawn failed with code 404.
Settings file could not be retrieved, proceeding without.
Downloading 169B for http://ritsuko.nullday.de/archlinux/image.roothash.
HTTP request to http://ritsuko.nullday.de/archlinux/image.roothash failed with code 404.
Root hash file could not be retrieved, proceeding without.
Downloading 543B for http://ritsuko.nullday.de/archlinux/SHA256SUMS.gpg.
Download of http://ritsuko.nullday.de/archlinux/SHA256SUMS.gpg complete.
Downloading 318.3M for http://ritsuko.nullday.de/archlinux/image.raw.xz.
Downloading 79B for http://ritsuko.nullday.de/archlinux/SHA256SUMS.
Download of http://ritsuko.nullday.de/archlinux/SHA256SUMS complete.
Got 1% of http://ritsuko.nullday.de/archlinux/image.raw.xz. 20min 11s left at 266.4K/s.
```

**Comment by shibumi** [comment]
I will get your systemd version running on my system.. maybe I will see the reason why the download fails with better debugging output.

**Comment by yuwata** [comment]
The error message shows bad error code now. See #10207 and #10208.

**Comment by yuwata** [comment]
(Unfortunately, my laptop does not have enough space to download the file... I need to cleanup my disk.)

**Comment by yuwata** [comment]
Anyway, please test with #9536 and #10208.

**Comment by poettering** [comment]
So this looks like it has been fixed a while back. Lets close this.

**Comment by shibumi** [comment]
@yuwata sorry. The systemd build process was failing for me on Arch linux due to some arch linux specifics. I will checkout the newest version with your commits and give feedback. Should be fine.
