### ISSUE TITLE
radv_recv can use an uninitialized value as the second argument of radv_send

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10223]
The following code assumes that `src` has been initialized if `icmp6_receive` returns `0`:
https://github.com/systemd/systemd/blob/f21f31b24be27c8eb245d47507b0f482929c5b08/src/libsystemd-network/sd-radv.c#L235-L259

This assumption isn't correct because `icmp6_receive` can return `0` after `recvmsg` has failed with `EAGAIN` or `EINTR`:
https://github.com/systemd/systemd/blob/f21f31b24be27c8eb245d47507b0f482929c5b08/src/libsystemd-network/icmp6-util.c#L175-L183

The most straightforward fix would be to initialize `src`
```diff
diff --git a/src/libsystemd-network/sd-radv.c b/src/libsystemd-network/sd-radv.c
index b4de6bda9..9479c1eec 100644
--- a/src/libsystemd-network/sd-radv.c
+++ b/src/libsystemd-network/sd-radv.c
@@ -214,7 +214,7 @@ static int radv_send(sd_radv *ra, const struct in6_addr *dst,
 static int radv_recv(sd_event_source *s, int fd, uint32_t revents, void *userdata) {
         sd_radv *ra = userdata;
         _cleanup_free_ char *addr = NULL;
-        struct in6_addr src;
+        struct in6_addr src = {};
         triple_timestamp timestamp;
         int r;
         ssize_t buflen;
```
, but I'm not sure that this is the right approach.

**Comment by pfl** [comment]
>  if (IN_SET(errno, EAGAIN, EINTR))

If a packet was not received, the error should be forwarded to the caller. So no special treatment for these two errors, since nothing useful has been received, there is no message the caller can reply to. Looks like something left dangling after a previous rearrangement of the code, or some other glitch in the logic.

**Comment by evverx** [comment]
@pfl thank you for taking a look! Looking at the code, I think I know why `EAGAIN` and `EINTR` were treated differently. It's most likely because the code handling the errors was part of `ndisc_recv`, which being an event handler would be simply turned off if it returned a negative error code (which is usually [undesirable](https://github.com/systemd/systemd/commit/f134289ac59560946e6559d9487e60c7690396ba)). So it seems correct to simply return `-errno` to the callers (as long as `icmp6_receive` isn't used as an event handler anywhere and, judging by the output of `git grep icmp6_receive`, it isn't).

**Comment by pfl** [comment]
Yes, that was the cause! I remembered vaguely this was refactored, but didn't look too deep into the history...
