### ISSUE TITLE
libsystemd0 (237-3ubuntu10.3), libpam-systemd (237-3ubuntu10.3), systemd (237-3ubuntu10.3), libnss-systemd (237-3ubuntu10.3)

### ISSUE THREAD

**Issue by DeVIL-I386** [systemd/systemd#10222]
TestSystem: Linux Mint 19 Xfce (32 bit & 64 bit)

It's about the following packages: 
**libsystemd0** (237-3ubuntu10.3), 
**libpam-systemd** (237-3ubuntu10.3), 
**systemd** (237-3ubuntu10.3), 
**libnss-systemd** (237-3ubuntu10.3)

I have created an [updated live system](http://downloads.sourceforge.net/linuxmintdeutsch/linuxmint-19-xfce-32bit-de-20180727.sync.iso).

If you install a live system with the current packages (237-3ubuntu10.3), and select the option "**Encrypt my home folder**" during the installation, you cannot log in to the installed system. **If you log in, you will immediately land on the login screen without seeing the desktop.**

With the old versions of the packages (237-3ubuntu10) there is no problem. But with the new packages it is.

**Comment by yuwata** [comment]
Please test with v238 or newer.

From docs/CONTRIBUTING.md
> We only track bugs in the two most recently released versions of systemd in the GitHub Issue tracker. If you are using an older version of systemd, please contact your distribution's bug tracker instead.
