### ISSUE TITLE
RFE: portablectl `--enable` option

### ISSUE THREAD

**Issue by jaymzh** [systemd/systemd#10232]
It would be convenient if `portablectl` had an `--enable` option so that you could both activate and enable a portable service in a single command.

**Comment by lucaswerkmeister** [comment]
And perhaps also `--now` in analogy to `systemctl enable --now`, to activate, enable, and start a service?

**Comment by bluca** [comment]
Opened a PR adding --enable and --now, even though I'm bluca rather than lucab :-)
