### ISSUE TITLE
RFE: Per-unit journal settings

### ISSUE THREAD

**Issue by jaymzh** [systemd/systemd#10230]
There is a desire to change journaling settings per-unit.

For some settings such as rate-limiting, this is very easy and we should just do it.

However, for things like disk-space, this cannot be done as-is and requires different files. At ASG 2018 there was some discussion on how this could work and this aims to document that as an RFE.

The general conclusion is that it should use roughly the same design as #10229. For services or units that request different settings that require a separate buffer to implement, a separate buffer file would be written to `/run`.

It is worth noting that the more files we have to write, the more files have to be consumed which can have a performance penalty.

**Comment by jaymzh** [comment]
This overlaps with https://github.com/systemd/systemd/issues/3045 btw.

**Comment by evverx** [comment]
Having read this issue, https://github.com/systemd/systemd/issues/3045 and https://github.com/systemd/systemd/pull/10308#issuecomment-430280434, I'm not sure I understand how the client side is supposed to look like. More precisely, I'm a bit puzzled about how all these settings scattered across the global configs, unit files and dynamic transient services should be managed in a way that wouldn't be chaotic. What is expected to happen when, for example, `journalctl --vacuum-files=10` is used and there're ten unit files with their own journal-related settings apart from the global journal. Could anyone expand on this?

**Comment by davide125** [comment]
I think that's something we'll have to figure out on a per-option basis. For `--vacuum-files`, one reasonable default could be to apply it to both the global journal and to any subgroups we might have (though we'd likely want the ability to target it to something specific if needed). I do agree that this will increase complexity in general, and that's something we'll have to keep in mind while we work on the implementation.

**Comment by evverx** [comment]
I'd also add that, as far as I can see, after my failed attempt to enforce the global rate-limiting policy, the current mechanism isn't flexible enough to implement the kind of policy where there's a global default for every setting. It's probably not that bad for rate-limiting, but for everything else especially related to disk space it seems to be very problematic.

**Comment by poettering** [comment]
ok, looks good. let's merge it like this. tweaks what overrides what we can still do later.

**Comment by xocasdashdash** [comment]
Hi!
Sorry to _drop in_ on this, but could this change include the possibility of adding some tags to the messages produced by a unit? Something similar to what docker does with tags.
I'm thinking of something akin to this:
```
[Service]
ExecRun=myservice
JournalTag=VERSION=1
JournalTag=COMMIT=faoisd
JournalTag=Product=Wordpress
```
This would help downstream reader of the journal be able to route this log messages using this info. I've implemented something similar with docker containers and it's been very useful.

**Comment by poettering** [comment]
@xocasdashdash that already exists. `LogExtraFields=`…

**Comment by piotrjurkiewicz** [comment]
Does this also limit messages generated by systemd itself on unit start/stop?
```
Nov 01 23:46:01 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 23:46:01 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 23:30:01 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 23:30:01 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 23:14:41 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 23:14:41 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 22:59:01 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 22:59:01 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 22:43:01 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 22:43:01 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 22:27:01 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 22:27:01 alarmpi systemd[1]: Starting Periodically saves system time to file...
Nov 01 22:11:41 alarmpi systemd[1]: Started Periodically saves system time to file.
Nov 01 22:11:41 alarmpi systemd[1]: Starting Periodically saves system time to file...
```

**Comment by simonbcn** [comment]
I think it would be very useful to allow indicate "_LogLevel_" by unit/service.

**Comment by anitazha** [comment]
@simonbcn `LogLevelMax=` does that.
