### ISSUE TITLE
RFE: Better error message for systemd-sysusers

### ISSUE THREAD

**Issue by jgmdev** [systemd/systemd#10241]
Currently a syntax error in /etc/group or /etc/passwd will cause systemd-sysusers to fail with the following message: 
```
Failed to write files: Invalid argument
```
This message can be reproduced when introducing a syntax error like this one on /etc/group
```
users:x:100:http:myuser
```
which correct syntax should be
```
users:x:100:http,myuser
```
The error message returned by systemd-sysusers doesn't tells much and can leave you scratching your head while searching what is the cause of the issue (for reference: https://bugs.archlinux.org/task/58873).

The proposal would be to output a more useful error message which specifies if syntax errors where found while trying to update the /etc/group,passwd... files, for example:
``` 
Failed to update file /etc/group: Syntax error detected on line 7
```

**Comment by kirbyfan64** [comment]
Not 100% sure, but this is probably a side effect of all errors being just the error code, meaning no semantic information can be included. 

Maybe the code causing detecting the syntax error could log it instead?
