### ISSUE TITLE
[RFE]: Allow for time based retention of file descriptors with the FDSTORE mechanism

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#10243]
Currently, until the job type is JOB_RESTART, or more precisely, if the unit is not referenced as part of the transaction, PID1 will drop all file descriptors from that service. This leads to confusion, for when one uses the `stop` and `start` operations as opposed to `restart`, file descriptors are lost in the first case (and this is somewhat non-obvious to those coming from SysV, since stop+start is no longer equivalent to restart). 

This is also why the journald manpage documents this pitfall and recommends one to avoid it (otherwise all log streams are practically hosed until all the affected services are restarted).

I think time based retention of file descriptors would be useful on its own, but it could probably be used in the journal to also fix the currently non-obvious behaviour.

**Comment by boucman** [comment]
I think that would fit nicely in the GarbageCollection= parameter that already exists... maybe allowing a time-based syntax, like

GarbageCollection=3d

**Comment by poettering** [comment]
well, uh, i am not a fan of this idea i must say... this sounds like a racy hack to me. I think it *does* make semantic sense to distinguish stop+start from restart, and it is expressly documented in the man page that there's a difference. Or to say this differently, we really must have a way to tell systemd to "totally" restart a service, and I think the manual "stop" + "start" is a good way to do that. But if suddenly you mix time into this, then you never know what you'll get: sometimes the fully flushed out restart and sometimes the not-flushed out restart...

Hence, not convinced this proposal really has good semantics, and is desirable...
