### ISSUE TITLE
make "systemd-analyze cat-config" useful for finding hwdb files and suchlike

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#10256]
systemd-analyze cat-config currently cannot be used for hwdb file enumeration, since it insists on a "main" configuration file. We should fix that. (which might mean we should add a new verb for this, as "cat-config" then is a bit of a misnomer, or maybe w eshould jsut rename it)

**Comment by yuwata** [comment]
I think `udevadm`, instead of `systemd-analyze`, should take `cat-config` or something.
