### ISSUE TITLE
Inconsistent behavior of org.freedesktop.login1.Manager.CanHibernate

### ISSUE THREAD

**Issue by henryptung** [systemd/systemd#10250]
**systemd version the issue has been seen with**
> systemd 239.2-1

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
If `org.freedesktop.login1.Manager.CanHibernate` returns `yes` for a user, it should also return `yes` for `root`.

**Unexpected behaviour you saw**
When Chrome has a video open, `org.freedesktop.login1.Manager.CanHibernate` returns `yes` for the logged-in user but inconsistently returns either `challenge` or `no` for `root`.

Of note, this interacts poorly with UPower, and makes it think hibernate is unavailable, so it powers off on critical battery instead.

**Steps to reproduce the problem**

1. Create **test-can-hibernate.sh**:
```bash
#!/bin/bash

for ((i=0;i<100;i++)); do
    dbus-send --system \
        --print-reply=literal \
        --dest=org.freedesktop.login1 \
        /org/freedesktop/login1 \
        org.freedesktop.login1.Manager.CanHibernate
    echo
done | sort | uniq -c
```
2. Run script as user and as root:
```
$ ./test-can-hibernate.sh 
    100    yes
$ su
# ./test-can-hibernate.sh 
    100    yes
```
3. Play YouTube video in Chrome.
4. Repeat step 2.
```
$ ./test-can-hibernate.sh 
    100    yes
$ su
# ./test-can-hibernate.sh 
     81    challenge
     19    no
```

**Relevant(?) information**

```
     Who: htung (UID 1000/htung, PID 1107/gsd-media-keys)
    What: sleep
     Why: GNOME handling keypresses
    Mode: delay

     Who: htung (UID 1000/htung, PID 1062/gsd-power)
    What: sleep
     Why: GNOME needs to lock the screen
    Mode: delay

     Who: htung (UID 1000/htung, PID 820/gnome-session-b)
    What: shutdown:sleep
     Why: user session inhibited
    Mode: block

     Who: htung (UID 1000/htung, PID 1107/gsd-media-keys)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key
     Why: GNOME handling keypresses
    Mode: block

     Who: UPower (UID 0/root, PID 1017/upowerd)
    What: sleep
     Why: Pause device polling
    Mode: delay

     Who: NetworkManager (UID 0/root, PID 434/NetworkManager)
    What: sleep
     Why: NetworkManager needs to turn off networks
    Mode: delay

6 inhibitors listed.
```

The third inhibitor is the one present when Chrome is playing video.

**Comment by henryptung** [comment]
As an addendum, would note that `CanHybridSleep` and `CanSuspend` exhibit very similar behavior:

```
$ ./test-login1-dbus.sh CanHybridSleep     
    100    yes
$ sudo ./test-login1-dbus.sh CanHybridSleep
     84    challenge
     16    no
$ ./test-login1-dbus.sh CanHibernate  
    100    yes
$ sudo ./test-login1-dbus.sh CanHibernate  
     86    challenge
     14    no
[htung@HPT-Laptop-2 ~ ]$ ./test-login1-dbus.sh CanSuspend       
    100    yes
$ sudo ./test-login1-dbus.sh CanSuspend
     84    challenge
     16    no
```

and to clarify, the bug does not exhibit if the video is paused.

**Comment by henryptung** [comment]
Update: so, on this line:

https://github.com/systemd/systemd/blob/master/src/login/logind-dbus.c#L2260

If `result` is already `"yes"` and the polkit test returns `1`, `result` gets set to `"no"`. I'm guessing that's incorrect behavior; not sure of the exact semantics of what's being tested, but I'm guessing the logic flow of those if blocks needs some attention.

**Comment by poettering** [comment]
Your suggested patch looks great. I turned it into a commit (attributed to you) and added it to PR #10495. PTAL.

**Comment by henryptung** [comment]
@poettering Thanks! I'm still using the patch locally, and haven't run into any recurrence of the issue on my box, so it definitely meets my needs. If you need a field test of a branch build, let me know, but otherwise LGTM.
