### ISSUE TITLE
nspawn should allow preconfiguring the machine's network interface

### ISSUE THREAD

**Issue by mildred** [systemd/systemd#1025]
In case the container doesn't run a full system, but is used to isolate a single application, it would be nice if we could preconfigure the network interface inside the container from the nspawn command line. Otherwise, we have to manually execute ip commands from the startup script given environment variables settings.

**Comment by poettering** [comment]
I am pretty sure that nspawn should not become another IP configuration tool. Please either share the network namespace and hence configuration with the host, or run an IP configuration tool of your choice inside of the container (such as networkd). But adding the same concepts as we already implemented in networkd a second time, but this time to networkd is really nothing we should do.

Sorry.
