### ISSUE TITLE
Add structured journal message when service transitions to DEAD

### ISSUE THREAD

**Issue by jlebon** [systemd/systemd#10265]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the journal API to figure out if a service exited cleanly or not *in the previous boot*. The issue is that there is no good way to do that without resorting to e.g. string matching the `MESSAGE` like `Failed with result`.

**Describe the solution you'd like**
Log a structured journal entry detailing exactly what the service result was in a separate field when entering the DEAD state.

**Describe alternatives you've considered**
Not using the journal for this and instead using e.g. stamp files in `/var` for my service to know if it exited nicely or not.

**Comment by jlebon** [comment]
Specifically, changing https://github.com/systemd/systemd/blob/9a21d8b9fd1e5f640e1bfb2dfc95b53f6ae05c66/src/core/service.c#L1686 to a structured entry with a separate result field.

**Comment by boucman** [comment]
could we generalize the request for a message whenever a unit changed state, not just go to failed ? might be usefull...

**Comment by coretemp** [comment]
I have no requirement for @boucman's request, but it sounds sensible.

**Comment by poettering** [comment]
> could we generalize the request for a message whenever a unit changed state, not just go to failed ? might be usefull...

We have that already actually, but only when debug logging is enabled. For example it's generated here for service units:

https://github.com/systemd/systemd/blob/master/src/core/service.c#L1097

The other unit types have something similar.

And I am not convinced that dumping the internal state changes to the logs at anything higher than debug is really a good idea. THere are a lot of those, and most folks probably shouldn't care...

**Comment by poettering** [comment]
Fix waiting in #10770
