### ISSUE TITLE
Way to disable tmpfs on /tmp in nspwan container?

### ISSUE THREAD

**Issue by vlada-dudr** [systemd/systemd#10260]
**Is your feature request related to a problem? Please describe.**
I have certain (bit) broken apps, which are doing rename to move files from /tmp. I know it is not good solution, but patching them will take time, so disabling tmpfs would make the trick. Anyway, I don't see point why we should be forced to fill our RAM, when it is not needed nor necessary.

**Describe the solution you'd like**
Way to disable mounting tmpfs to /tmp in nspawn containers. Ideally, this would be left to configure from inside the container via fstab as usual.

**Describe alternatives you've considered**
Using LXC instead of Nspawn.

**Comment by lucaswerkmeister** [comment]
You could also unmount `/tmp` inside the container once it’s running (`umount -l /tmp` – not sure why the `-l` is necessary, but the unmount seems to go through pretty quickly).

**Comment by poettering** [comment]
I hacked this up in #10294.
