### ISSUE TITLE
cloned repository fails on ./configure with meson error

### ISSUE THREAD

**Issue by KernelXitron** [systemd/systemd#10272]
**systemd version the issue has been seen with**
> I do not know how to tell the version based on a git pull.  The version that could be obtained at 12:00PM on Thursday, October 4th, the day I file this bug report, via the following command:
git clone git@github.com:systemd/systemd.git

**Used distribution**
 > Attempting to ./configure && make && make install from github repository.  See above for version info.
Computer setup is as follows: 4 core laptop with 8GB RAM and an almost empty 2TB hard drive.  Running LinuxMint 18.1

**Expected behaviour you didn't see**
 > Completion of the ./configure command.

**Unexpected behaviour you saw**
 > ~/repository/systemd
$ ./configure
+ exec meson build
The Meson build system
Version: 0.40.1
Source dir: <path-to>/repository/systemd
Build dir: <path-to>/repository/systemd/build
Build type: native build

Meson encountered an error in file <path-to>/repository/systemd/meson_options.txt, line 161, column 53:
Expecting rparen got id.
option('dynamic-uid-min', type : 'integer', value : 0x0000EF00,
      ^______________________________________________^

The section of the file in question is this one, with a little context above and below:

157) option('system-uid-max', type : 'integer', value : '-1',
158)       description : 'maximum system UID')
159) option('system-gid-max', type : 'integer', value : '-1',
160)       description : 'maximum system GID')
161) option('dynamic-uid-min', type : 'integer', value : 0x0000EF00,
162)       description : 'minimum dynamic UID')
163) option('dynamic-uid-max', type : 'integer', value : 0x0000FFEF,
164)       description : 'maximum dynamic UID')
165) option('container-uid-base-min', type : 'integer', value : 0x00080000,
166)       description : 'minimum container UID base')

The issue isn't clear above in the error, because the font on this page is not fixed width.  The carats (^) are pointing to the left paren by the word "option" and the "x" in the number at the end of the line, as though it expected a right paren at that location.

**Steps to reproduce the problem**
As far as I know, git clone the repository to a new, clean location, cd to the repository, and run './configure'.

**Comment by yuwata** [comment]
Please try to use `meson` and `ninja`. Our `configure` script is a wrapper of them. But it may not be maintained, and nobody use that now...

**Comment by yuwata** [comment]
```
 Version: 0.40.1
```
Ah, the version of meson is too old. systemd requires meson-0.46 or newer.

**Comment by yuwata** [comment]
Now, I've tried to run `configure` and it works fine for me with meson-0.47.2. Please update meson.

**Comment by poettering** [comment]
hmm, i wonder why meson didn't refuse building on its own. We do declare the required meson version in project(), hence meson really should have refused building early on with 0.40... or is that something that only works on more recent meson? @keszybz any idea?

**Comment by mbiebl** [comment]
this is odd indeed, maybe a bug in earlier meson versions (which we can fix retroactively). 
If I (artifically) bump the required meson version to 0.49.0, I get
```
$ ./configure
+ exec meson build
The Meson build system
Version: 0.48.0
Source dir: /tmp/systemd
Build dir: /tmp/systemd/build
Build type: native build

meson.build:3:0: ERROR:  Meson version is 0.48.0 but project requires >= 0.49.

A full log can be found at /tmp/systemd/build/meson-logs/meson-log.txt
```
