### ISSUE TITLE
Resolved: I get too many nameservers, resolved ignores my VPNs DNS

### ISSUE THREAD

**Issue by towolf** [systemd/systemd#10279]
I get 3 nameservers from my cable modem, 1 for IPv4 and 2 for IPv6.

And then I connect to VPN and resolved thinks 3 are enough and disregards the DNS from VPN.

**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Ubuntu 18.10

**Expected behaviour you didn't see**
Resolved should use the DNS coming from VPN 

When I disable resolved, then NetworkManager `default` mode manages to put my VPN DNS on top
```
$ cat /etc/resolv.conf 
# Generated by NetworkManager
search home
nameserver 192.168.9.250 ←←
nameserver 192.168.0.1
nameserver 2a02:xxx:2:a::1
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 2a02:xxx:2:b::1
``` 

**Unexpected behaviour you saw**
No `192.168.9.250` (the DNS from my VPN) is being used
 ```
$ cat /run/systemd/resolve/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 192.168.0.1
nameserver 2a02:908:2:a::1
nameserver 2a02:908:2:b::1
```

**Comment by towolf** [comment]
```
Link 5 (vpn0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp6s0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 2a02:908:2:b::1
         DNS Servers: 192.168.0.1
                      2a02:908:2:a::1
                      2a02:908:2:b::1
          DNS Domain: ~.
                      home
```

**Comment by towolf** [comment]
Actually, I was wrong about the "too many nameservers" part.

When I disabled the IPv6 nameservers I still did not get the VPN DNS on connection:

```
Link 5 (vpn0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp6s0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 192.168.0.1
         DNS Servers: 192.168.0.1
          DNS Domain: ~.
                      home

```

So, not sure what to do with this issue, going to look for duplicates ...

**Comment by yrro** [comment]
Are you sure your VPN client is pushing `192.168.9.250` to `resolved`? It's not showing up in the info for your `vpn0` link...

**Comment by yrro** [comment]
Sounds like the plugin passes the DNS to NM, but maybe NM doesn't push it to resolved. In `NetworkManager.conf` make sure you have

```
[main]
dns=systemd-resolved
```

And restart everything.

**Comment by towolf** [comment]
No cookie:

```
$ ll /etc/resolv.conf
lrwxrwxrwx 1 root root 37 Okt 11 00:55 /etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf
$ resolvectl dns 
Global:
Link 19 (wwp0s20f0u9):
Link 6 (vpn0):
Link 3 (wlp6s0): 192.168.0.1 2a02:xxx:2:a::1 2a02:xxx:2:b::1
Link 2 (enp0s31f6):
$ grep dns /etc/NetworkManager/NetworkManager.conf 
# dns=default
dns=systemd-resolved
```

Unless you have something else, I'll just go back to `dns=default`, because that works.

**Comment by towolf** [comment]
Two more lines:
```
Okt 11 00:56:03 denkbrett480 NetworkManager[27646]: <info>  [1539212163.2867] dns-mgr[0x5633915f28f0]: init: dns=systemd-resolved, rc-manager=symlink, plugin=systemd-resolved
Okt 11 00:56:52 denkbrett480 NetworkManager[27646]: <info>  [1539212212.6781] vpn-connection[0x56339170e130,f7695b5c-1201-436e-be88-e83c25c9bd9c,"GF AnyConnect",6:(vpn0)]: Data:   Internal DNS: 192.168.9.250
```

**Comment by yrro** [comment]
You could use `busctl capture` to spy on NM pushing the DNS info to resolved to confirm that it's doing it I suppose...

**Comment by towolf** [comment]
_Sigh_, I did `busctl capture` and inspected the output briefly with Wireshark. But there are 724 packets and I have no idea what I am looking for ...

![image](https://user-images.githubusercontent.com/345210/46820810-5bd89600-cd87-11e8-8272-5aba3298665f.png)

**Comment by yrro** [comment]
You've found the right packet, but there is something wrong with the body. The signature for the method is `ia(iay)`:

```
$ busctl introspect org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager
NAME                               TYPE      SIGNATURE     RESULT/VALUE                             FLAGS
...
.SetLinkDNS                        method    ia(iay)       -                                        -
...
```

This decodes as two parameters.

The first (`i`) is the interface ID. Does `7` correspond to the id of `vpn0`? (Note that this changes as the interface is added and removed by the VPN client, so you will probably have to run the test again and note the interface ID once connected...)

The second (`a(iay)`) is the list of DNS servers. This is encoded as an array of structs, each of which has an address family (int) and an address (array of bytes). This is missing.

If I'm interpreting this message in the same way that `resolved` does, then I think I'm seeing a call to set the list of DNS servers for interface `7` to the empty array. i.e., NM is telling `resolved` that there are no dns servers for this interface.

If I were you I'd first check to see if there are any other calls to `SetLinkDNS`. If not then this appears to be a problem on the `NetworkManager` side of things.

BTW, I wanted to provide an example of how things should look on a working system for you to compare against. I gave WireShark a go and I think it's actually not a great tool for hunting through captured D-Bus traffic: the filters don't appear to let you filter on useful fields like source/destination/method name...

I have had a bit more luck with `busctl monitor > somefile` and then searching through that file with a text editor. For instance, here's what I see when I connect to an ethernet network:

```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=4761
  Sender=:1.28495  Destination=:1.66213  Path=/org/freedesktop/resolve1  Interface=org.freedesktop.resolve1.Manager  Member=SetLinkDNS
  UniqueName=:1.28495
  MESSAGE "ia(iay)" {
          INT32 2;
          ARRAY "(iay)" {
                  STRUCT "iay" {
                          INT32 2;
                          ARRAY "y" {
                                  BYTE 192;
                                  BYTE 0;
                                  BYTE 2;
                                  BYTE 1;
                          };
                  };
                  STRUCT "iay" {
                          INT32 2;
                          ARRAY "y" {
                                  BYTE 192;
                                  BYTE 0;
                                  BYTE 2;
                                  BYTE 2;
                          };
                  };
                  STRUCT "iay" {
                          INT32 2;
                          ARRAY "y" {
                                  BYTE 192;
                                  BYTE 0;
                                  BYTE 2;
                                  BYTE 3;
                          };
                  };
          };
  };
```

To decode the numbers...

 * running `busctl` confirms that `:1.66213` is `resolved` and `:1.28495` is `NetworkManager`.
 * link 2 is my ethernet interface
 * each DNS server is an IPv4 address (address family 2 which is the value of `AF_INET`) and the actual addresses should be easy to read. ;)

**Comment by towolf** [comment]
Ok, I get SetLinkDNS twice, once for vpn0 (id 7) which is empty and once for  wlp6s0 (id 3), which contains 3 hostnames:
```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1309
  Sender=:1.1515  Destination=:1.1516  Path=/org/freedesktop/resolve1  Interface=org.freedesktop.resolve1.Manager  Member=SetLinkDNS
  UniqueName=:1.1515
  MESSAGE "ia(iay)" {
          INT32 7;
          ARRAY "(iay)" {
          };
  };
```
```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1306
  Sender=:1.1515  Destination=:1.1516  Path=/org/freedesktop/resolve1  Interface=org.freedesktop.resolve1.Manager  Member=SetLinkDNS
  UniqueName=:1.1515
  MESSAGE "ia(iay)" {
          INT32 3;
          ARRAY "(iay)" {
                  STRUCT "iay" {
                          INT32 2;
                          ARRAY "y" {
                                  BYTE 192;
                                  BYTE 168;
                                  BYTE 0;
                                  BYTE 1;
                          };
                  };
                  STRUCT "iay" {
                          INT32 10;
                          ARRAY "y" {
                                  BYTE 42;
                                  BYTE 2;
                                  BYTE 9;
                                  BYTE 8;
                                  BYTE 0;
                                  BYTE 2;
                                  BYTE 0;
                                  BYTE 10;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 1;
                          };
                  };
                  STRUCT "iay" {
                          INT32 10;
                          ARRAY "y" {
                                  BYTE 42;
                                  BYTE 2;
                                  BYTE 9;
                                  BYTE 8;
                                  BYTE 0;
                                  BYTE 2;
                                  BYTE 0;
                                  BYTE 11;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 0;
                                  BYTE 1;
                          };
                  };
          };
  };

```

Going to try one more time with a full reboot ...

**Comment by towolf** [comment]
Tried two more things. I added `resolve` to `/etc/nsswitch.conf` and installed `libnss-resolve`, which did not help.

Manually calling this method does the trick, but I wonder why NM+openconnect is sending a dbus message with an empty server list. Is that an Ubuntu or NetworkManager bug? 

But it seems to be unrelated to resolved itself, then. Should we close this?

`sudo busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDNS 'ia(iay)' 5 1 2 4 192 168 9 250`

**Comment by towolf** [comment]
So, I made a hook script for NetworkManagerDispatcher now, which pokes resolved via `busctl call`. 

For the time being, I can ignore this problem.

Please decide if this ticket can be closed or not.

**Comment by yrro** [comment]
I am pretty sure the problem is with NM, or more likely, the VPN plugin. I don't have the rights to close this bug though so feel free to do that yourself. :)

**Comment by towolf** [comment]
closing then
