### ISSUE TITLE
meson.build cpp variable is created without specified cpp_args from properties (cross compiling)

### ISSUE THREAD

**Issue by egtvedt** [systemd/systemd#10288]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > embedded

**Expected behaviour you didn't see**
 > src/basic/generate-cap-list.sh script execute cross compiler with specified CPP arguments, typically -Ipath entries.

**Unexpected behaviour you saw**
 > generate-cap-list.sh is not able to locate header files since the $1 argument in the shell script is only the /path/to/compiler....-gcc.

**Steps to reproduce the problem**
Use an old toolchain without BTRFS, but include a cross file that contains a -Ipath to a more up to date kernel. The step ninja -C build will fail to execute.

**Comment by yuwata** [comment]
Could you test #10289?

**Comment by egtvedt** [comment]
> Could you test #10289?

Tested, and it did not work. I added some simple debug:
error('options are \'@0@\''.format(get_option('c_args')))

And it prints:
meson.build:405:0: ERROR:  Problem encountered: options are '[]'

**Comment by yuwata** [comment]
BTW, do you use cpp_args instead of c_args?

**Comment by yuwata** [comment]
> error('options are '@0@''.format(get_option('c_args')))

The syntax seems strange. Please try the following:
```
warning('@0@'.format(get_option('c_args')))
```

**Comment by egtvedt** [comment]
Ah, this forum removed my escapes:
`error('options are \'@0@\''.format(get_option('c_args')))`

**Comment by yuwata** [comment]
How do you specified the include path? I guess you use `meson -Dc_args=-I/path/to/include`, no?

**Comment by egtvedt** [comment]
I have a cross file, that contains the arguments:
```
[binaries]
c = 'arm-unknown-linux-gnueabi-gcc'
cpp = 'arm-unknown-linux-gnueabi-g++'
ar = 'arm-unknown-linux-gnueabi-ar'
strip = 'arm-unknown-linux-gnueabi-strip'
pkgconfig = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'

[properties]
c_args = ['-I/path/to/something/include', '-I/path/to/different/include']
c_link_args = ['-L/path/to/something/lib', '-L/path/to/different/lib']
cpp_args = ['-I/path/to/something/include', '-I/path/to/different/include']
cpp_link_args = ['-L/path/to/something/lib', '-L/path/to/different/lib']
```

**Comment by yuwata** [comment]
I see. Then the `error()` or `warning()` above shows empty c_args or cpp_args?

**Comment by egtvedt** [comment]
> I see. Then the `error()` or `warning()` above shows empty c_args or cpp_args?

Correct.

**Comment by yuwata** [comment]
Confirmed. I guess this is a bug of meson, or we should use other method... I am not sure.

**Comment by egtvedt** [comment]
Thanks for the quick answers and suggestions, I applied the workaround and it works for me. I will address the issue with the meson developers.

**Comment by yuwata** [comment]
#10289 does not fix this. Moreover, it is reverted by #10361. Let's reopen this.
But, to fix this, it is necessary https://github.com/mesonbuild/meson/issues/4331 or https://github.com/mesonbuild/meson/issues/4345 to be fixed.

**Comment by yuwata** [comment]
https://github.com/mesonbuild/meson/pull/5263 may solve this issue.

**Comment by cpackham** [comment]
What was the conclusion on this? I'm experiencing the same problem on master when cross-compiling. The original change from #10289 does workaround the issue for me but based on other threads I'm wondering if I need something different in my cross-compile.txt file

<details><summary>cross-compile.txt</summary>

    [binaries]
    c = 'mips64-unknown-linux-gnu-gcc'
    cpp = 'mips64-unknown-linux-gnu-g++'
    ar = 'mips64-unknown-linux-gnu-ar'
    pkgconfig = '/usr/bin/pkg-config'
    [properties]
    c_args=['--sysroot=output/mips64/systemd/staging','-Ioutput/mips64/systemd/staging/usr/include', '-Ioutput/mips64/systemd/staging/usr/include/libmount', '-Ioutput/mips64/systemd/staging/usr/include/blkid']
    c_link_args=['--sysroot=output/mips64/systemd/staging']
    [host_machine]
    system = 'linux'
    cpu_family = 'mips'
    cpu = 'mips64'
    endian = 'big'

</details>

**Comment by keszybz** [comment]
We were waiting for enhancements in meson. Those seem to be available now. Somebody would need to take a look and prepare a new patch...

**Comment by cpackham** [comment]
I'd be happy to give it a go. Any sign of the meson changes being documented?
