### ISSUE TITLE
networkctl statically configured link is in state "configuring"

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#1028]
I have a statically configured link using kernel command line option `ip=`, ie. `ip=172.17.0.209::172.17.42.1::hostname::off` this gives me static IP, gateway, hostname and disables dhcp configuration.

However, in networkd / networkctl output the ethernet device is stuck in "configuring" setup stage. My expected for it to be either configured, or unmanaged, or something else.

The side effect of this, is that systemd-networkd-wait-online fails, which is undesired in such a configuration.

How can this be resolved? Please advise.

**Comment by teg** [comment]
Strange. Could you paste the "networkctl status" output for your link? And also the .network file applied to the link?

**Comment by teg** [comment]
(it should indeed be unmanaged)

**Comment by poettering** [comment]
Closing, as there's no reply since last September.

**Comment by DirkSchmitt** [comment]
I have here the same problem.

IDX LINK             TYPE               OPERATIONAL SETUP  
  1 lo               loopback           carrier     unmanaged 
  2 bslave1          ether              carrier     configuring
  3 bslave2          ether              carrier     configuring
  4 bond0            ether              off         unmanaged 
  5 bond1            ether              carrier     configuring
  6 ovs-system       ether              off         unmanaged 
  7 lan1             ether              routable    unmanaged 

7 links listed

**Comment by joconcepts** [comment]
Same problem here:

```
  4 eth0             ether              carrier     configuring
  5 eth1             ether              carrier     configuring 
  6 bond0            ether              routable    configured
```

eth0 and eth1 are slaves of bonding interface bond0.

networkctl status of:

```
● 4: eth0
       Link File: n/a
    Network File: /etc/systemd/network/eth0.network
            Type: ether
           State: carrier (configuring)
          Vendor: Intel Corporation
           Model: [...]
      HW Address: [...]
             MTU: 9000
```

**Comment by q2dg** [comment]
Same problem here, but with bridging: I have a br0.netdev, a br0.network (with static address)  and a bridgedInterfaces.network file and when I run networkctl I get the same "configuring" state showed on bridged interfaces . Systemd 231, Ubuntu 16.10

**Comment by q2dg** [comment]
Well, it seems bridge works well...but when I do ip address show, status of bridged interfaces are shown as "UNKNOWN".
