### ISSUE TITLE
How to create a copy of systemd-nspawn container

### ISSUE THREAD

**Issue by sant527** [systemd/systemd#10295]
Hi,

Sorry i am not sure whether to ask this question here.

I am trying to create container to run archlinux:

1) Create an Archlinux distribution in a container
pacstrap -i -c ~/MyContainer base [additional pkgs/groups]

2) Boot into container
systemd-nspawn -b -D ~/MyContainer

After booting i have setup certain things.

Now how to clone the container so that if in future i can use again rather than creating and configuring again.

```
$ machinectl show Mycontainer
Name=Mycontainer
Id=c4256c29c1354ae3b2429255f3672990
Timestamp=Sat 2018-10-06 11:54:47 IST
TimestampMonotonic=4298605337
Service=systemd-nspawn
Unit=machine-Mycontainer.scope
Leader=2592
Class=container
RootDirectory=/srv/container/Mycontainer
State=running
```

```
$ machinectl list-images  
No images.
```

```
#  machinectl clone Mycontainer Mycontainer2
Could not clone image: No image 'Mycontainer' known

```

I found that the container should be in the folder /var/lib/machines

then cloning is working

but cloning is very slow. is there any other way.

**Comment by poettering** [comment]
If you need help or support, please contact the systemd mailing list.

This is a bug and issue tracker, not a support forum. Thank you for understanding.
