### ISSUE TITLE
Nice and CPUSchedulingPolicy properties set via systemd-run are not effective

### ISSUE THREAD

**Issue by pfactum** [systemd/systemd#10290]
**systemd version the issue has been seen with**

239

**Used distribution**

Arch Linux

**Expected behaviour you didn't see**

`systemd-run` should be able to set `CPUSchedulingPolicy` and `Nice` properties for transient services.

**Unexpected behaviour you saw**

`CPUSchedulingPolicy` and `Nice` properties are not effective when set by `systemd-run`.

**Steps to reproduce the problem**

```
$ systemd-run --user --pty --quiet --property=CPUSchedulingPolicy=idle chrt -p 0
pid 21327's current scheduling policy: SCHED_OTHER
pid 21327's current scheduling priority: 0
```

`chrt` should return `SCHED_IDLE` instead.

```
$ systemd-run --user --pty --quiet --property=Nice=19 nice                      
0
```

`nice` should return `19` instead.

```
$ systemd-run --user --pty --quiet --nice=19 nice   
0
```

Again, `19` should be returned.

`strace` on the user `systemd` instance shows that no `setpriority()` or `sched_setscheduler()` syscalls were performed.

On the other hand, I/O class gets set up correctly:

```
$ systemd-run --user --pty --quiet --property=IOSchedulingClass=idle ionice
idle
```

`strace` on the user `systemd` instance shows that `ioprio_set()` syscall was indeed performed.

OOM score is set just fine too:

```
$ systemd-run --user --pty --quiet --property=OOMScoreAdjust=1000 cat /proc/self/oom_score_adj
1000
```

If these options are set up via user service like this:

```
$ cat /etc/systemd/user/test.service 
[Unit]
Description=test

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c 'chrt -p 0; nice; ionice'
CPUSchedulingPolicy=idle
Nice=19
IOSchedulingClass=idle

[Install]
WantedBy=multi-user.target
```

then it works:

```
$ systemctl --user start test
$ sudo journalctl -f
…
říj 05 15:02:48 butterfly systemd[615]: Starting test...
říj 05 15:02:48 butterfly bash[20696]: pid 20697's current scheduling policy: SCHED_IDLE
říj 05 15:02:48 butterfly bash[20696]: pid 20697's current scheduling priority: 0
říj 05 15:02:48 butterfly bash[20696]: 19
říj 05 15:02:48 butterfly bash[20696]: idle
říj 05 15:02:48 butterfly systemd[615]: Started test.
```

**Comment by pfactum** [comment]
As a side note, `CPUAffinity` works just fine as well:

```
$ systemd-run --user --pty --quiet bash -c 'taskset -cp $$$'            
pid 24886's current affinity list: 0-3

$ systemd-run --user --pty --quiet --property=CPUAffinity=0-1 bash -c 'taskset -cp $$$'
pid 24895's current affinity list: 0,1
```

**Comment by yuwata** [comment]
@pfactum Fix is waiting in PR #10292. If possible, please test the PR.

**Comment by pfactum** [comment]
@yuwata Thanks for the quick fix. I can confirm that with this PR applied on top of Arch's systemd v239 it works:

```
$ systemd-run --user --pty --quiet --property=CPUSchedulingPolicy=idle chrt -p 0
pid 540's current scheduling policy: SCHED_IDLE
pid 540's current scheduling priority: 0

$ systemd-run --user --pty --quiet --property=Nice=19 nice
19

$ systemd-run --user --pty --quiet --nice=19 nice
19
```

**Comment by yuwata** [comment]
@pfactum Thank you for testing!
