### ISSUE TITLE
Add Wait/Tiemout parameters when killing service's processes

### ISSUE THREAD

**Issue by kjonca** [systemd/systemd#10299]
Sometimes tasks spawn background processes to do tasks, and main foreground process exits 
(Most notably exim MTA behave this way.)

When such process is a part of service (especially oneshot), background process is killed by systemd and sometimes cannot complete task.
So far we can set "KillMode=none" for such service.
But it would be nice to have 
TermTimeout or similar parameter for service and DefaultTermTiemout config option for systemd, which give some grace period for background processes.
Some background: 
https://lists.freedesktop.org/archives/systemd-devel/2018-September/041393.html

**Comment by poettering** [comment]
well, there's already `TimeoutStopSec=` that configures the time between SIGTERM/ExecStop= and SIGKILL. What else do you want? a timeout before the SIGTERM?

You should easily be able to implement this with ExecStop=/bin/sleep 50.

I am not sure a system-wide default logic for this would make sense. I mean, generally services don't magically shut down, but do so after being told so through SIGTERM or through an ExecStop= command. It's an absolute exception of services processes know when to exit magically on their own, hence I am not sure this is really something to add at all, and particularly not as a global option.

Or what are you asking for, what am I missing?

**Comment by kjonca** [comment]
I cannot comment, so I reply by mail.

I have problem with systemd-exim cooperation.
Exim (when acts as replacement for sendmail, for mail generated by local users) takes message (put in queue)  and then forks background process to deliver mail.
So when I use exim in "oneshot' service - this background process can be killed by systemd before it can complete delivery. 
Of course I can use KillMode=none, but I would have, a generic/global solution for this, especially since I do not know if someone put 'mail' command in script ...
I do not insist for timeout parameter. Maybe using session group ids would be enough. I do not know.

Lennart Poettering <notifications@github.com> writes:

> well, there's already TimeoutStopSec= that configures the time between SIGTERM/ExecStop= and SIGKILL. What else do you want? a timeout before the SIGTERM?
>
> You should easily be able to implement this with ExecStop=/bin/sleep 50.
>
> I am not sure a system-wide default logic for this would make sense. I mean, generally services don't magically shut down, but do so after being told so through SIGTERM or through an ExecStop= command. It's an absolute exception of services processes know when to
> exit magically on their own, hence I am not sure this is really something to add at all, and particularly not as a global option.
>
> Or what are you asking for, what am I missing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
>

-- 
http://stopstopnop.pl/stop_stopnop.pl_o_nas.html
Ray's Rule of Precision:
	Measure with a micrometer.  Mark with chalk.  Cut with an axe.

**Comment by poettering** [comment]
> I have problem with systemd-exim cooperation. Exim (when acts as replacement for sendmail, for mail generated by local users) takes message (put in queue) and then forks background process to deliver mail. So when I use exim in "oneshot' service - this background process can be killed by systemd before it can complete delivery.

Quite frankly this looks like something that is better fixed in Exim than worked around in systemd. Exim should not fork off stuff in the bg from user commands, that might have been OK in 1995, but not today.

**Comment by poettering** [comment]
Let's close this. I really don#t think we need to do anything here. The usecase is flawed if you ask me, exim shouldn't work like that. And `ExecStop=sleep 50` should do what you are looking for. Hence closing.
