### ISSUE TITLE
systemd-networkd force immediate DHCP reload

### ISSUE THREAD

**Issue by stfl** [systemd/systemd#10302]
I have a modem in an embedded setup which i configure using OpenWRT's uqmi library.
for IP config I use systemd-networkd.
After the connection is established, I need to reload the DHCP config to properly assign the IP and routing rules. This happens automatically after a couple of seconds. sometimes 30sec.

I want systemd-networkd to immediately get an IP address from the DHCP.

I have restricted user in the application that configures the modem that is not allowed to run systemctl.
systemctl restart systemd-networkd would do the trick but I don't have root access in the application

Either have systemd-networkd with a DHCP request interval of like 3 seconds.
or a way to trigger the reload with sth like a signal like 
    kill -0 $NETWORKD_PID

This feature might aleady be availabe but I couldn't find any doc?!
Thanks, Stefan

**Comment by ssahani** [comment]
> After the connection is established, I need to reload the DHCP config to properly assign the IP and routing rules. This happens automatically after a couple of seconds. sometimes 30sec.

That could be because of the DHCP TMO. 

>I have restricted user in the application that configures the modem that is not allowed to run systemctl.
systemctl restart systemd-networkd would do the trick but I don't have root access in the application

> Either have systemd-networkd with a DHCP request interval of like 3 seconds.

Isn't that playing with the RFC

> or a way to trigger the reload with sth like a signal like
kill -0 $NETWORKD_PID

Well can you send a process a signal which is running under another user ?

**Comment by ssahani** [comment]
Please take a look https://github.com/systemd/systemd/issues/10820

**Comment by ssahani** [comment]
```networkctl reconfigure``` can do this @yuwata ? we Can close it

**Comment by yuwata** [comment]
Right.
