### ISSUE TITLE
vsftpd service does not ask admins for the passphrase to decrypt private key. No clear documentation available about how to configure this kind of units.

### ISSUE THREAD

**Issue by tatoarg** [systemd/systemd#10319]
**systemd version 201-83.2**
> ...

**SLES 12**
 > …

**vsftpd with signed private key should ask for the passphrase to admins**
 > …

**Passphrase for the encrypted key is not asked to admins. No clear documentation explaining how to configure this case available.**
 > …

**
Configure vsftpd using certificate with encrypted private key .
Start the service with systemctl start vsftpd.service .
**

**Comment by poettering** [comment]
Well, the vsftpd startup scripts would have to support systemd's ask password api for this to work. they can also call the "systemd-ask-password" tool for that.

https://www.freedesktop.org/software/systemd/man/systemd-ask-password.html
https://www.freedesktop.org/wiki/Software/systemd/PasswordAgents/

There's little we can do about this from outside, this is something the upstream maintainers/packagers of vsftp have to take care of. Sorry

**Comment by tatoarg** [comment]
Hi Lennart,Thank you very much for your valuable help!Kind Regards,Alejandro.-----Lennart Poettering <notifications@github.com> escribió: -----Para: systemd/systemd <systemd@noreply.github.com>De: Lennart Poettering <notifications@github.com>Fecha: 09/10/2018 05:37Cc: tatoarg <alejandro.belucci@inaxissa.com>, Author <author@noreply.github.com>Asunto: Re: [systemd/systemd] vsftpd service does not ask admins for the passphrase to decrypt private key. No clear documentation available about how to configure this kind of units. (#10319)Well, the vsftpd startup scripts would have to support systemd's ask password api for this to work. they can also call the "systemd-ask-password" tool for that.
https://www.freedesktop.org/software/systemd/man/systemd-ask-password.html
https://www.freedesktop.org/wiki/Software/systemd/PasswordAgents/
There's little we can do about this from outside, this is something the upstream maintainers/packagers of vsftp have to take care of. Sorry
