### ISSUE TITLE
systemd-notify --ready  : systemd: Received notify message without valid credentials. Ignoring

### ISSUE THREAD

**Issue by KumarShrawan** [systemd/systemd#10326]
I have integrated systemd_234 on an old yocto distribution running systemd_225.  I see that services with type=notify fails .

To narrow down the problem here is what I did :
export NOTIFY_SOCKET=/run/systemd/notify
systemd-notify --ready

**//Journelctrl log :**
**systemd: Received notify message without valid credentials. Ignoring**

Looks the credential received  is not correct  , here is the strace message that I received while sending systemd-notify --ready : 
etuid32()                              = 0
getgid32()                              = 0
sendmsg(3<UNIX:[89545]>, {msg_name(21)={sa_family=AF_LOCAL, sun_path="/run/systemd/notify"}, msg_iov(1)=[{"READY=1", 7}], msg_controllen=24, [{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=4367, uid=0, gid=0}}], msg_flags=0}, MSG_NOSIGNAL) = 7
close(3<UNIX:[89545]>)                  = 0

Can someone please  provide a quick help and help me understand what has gone wrong and where should I start looking to fix this ?

Regards
Shrawan

**Comment by poettering** [comment]
That message looks fine to me, what makes you say it's "not correct"?

This is not a support forum btw, but a bug and feature request tracker. If you need help/support for something, please contact the mailing list instead. Please let's continue the discussion there. Thank you for understanding.
