### ISSUE TITLE
Clarify meaning of “in memory” in systemctl manpage

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#10338]
**Is your feature request related to a problem? Please describe.**
I was confused about whether `systemctl start '*.timer'` should start stopped timers or not. The general descriptions of globs at the end of `systemctl(1)` says:

> Note that alias names of units, and units that aren't in memory are not considered for glob expansion.

However, “in memory” seems to be used inconsistently in the manpage. The documentation for the `start` subcommand is much more explicit:

> Note that glob patterns operate on the set of primary names of units currently in memory. Units which are not active and are not in a failed state usually are not in memory, and will not be matched by any pattern. In addition, in case of instantiated units, systemd is often unaware of the instance name until the instance has been started. Therefore, using glob patterns with `start` has limited usefulness. Also, secondary alias names of units are not considered.

Here, inactive units are “not in memory”. However, the descriptions of the `list-units`, `list-timers` and `list-sockets` commands are more ambiguous: they all say that these commands

> list (socket|timer)? units that systemd currently has in memory

and to me this sounds like the units included by the  `--all` option must be “in memory” in some sense, since they could not be listed otherwise.

It sounds like “in memory” usually means “active or failed”, and perhaps the description of the listing commands should clarify that with `--all`, units that are not “in memory” will be included. (But perhaps “in memory” actually means “not garbage collected”? In that case, “active or failed” would only be a rough approximation.)

**Comment by poettering** [comment]
Fix waiting in #10569
