### ISSUE TITLE
Ignore remote filesystems in test-execute

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#10337]
**systemd version the issue has been seen with**
> systemd-239

**Used distribution**
 > RHEL

**Expected behaviour you didn't see**
 > **test-execute** finishes without timeout

**Unexpected behaviour you saw**
 > **test-execute** asserts on a timeout

**Steps to reproduce the problem**

In our test infrastructure (at Red Hat) we have several large remote filesystems mounted by default under /mnt. The **test-execute** test case runs the [exec-dynamicuser-statedir.service](https://github.com/systemd/systemd/blob/master/test/test-execute/exec-dynamicuser-statedir.service#L16) which executes `find` command over the entire filesystem, including /mnt, which - in this case - results in a test timeout:

```
# meson test -v test-execute
...
++ find / '(' -path /var/tmp -o -path /tmp -o -path /proc -o -path /dev/mqueue -o -path /dev/shm -o -path /sys/fs/bpf ')' -prune -o -type d -writable -print
++ sort -u
++ tr -d '\n'
...
Test timeout when testing exec-dynamicuser-statedir.service
1/1 test-execute                            FAIL    122.43 s
...
# ps aux | grep find
...
65388    23592  1.9  0.1  21616  4344 ?        D    11:19   0:00 find / ( -path /var/tmp -o -path /tmp -o -path /proc -o -path /dev/mqueue -o -path /dev/shm -o -path /sys/fs/bpf ) -prune -o -type d -writable -print
...
```

I managed to temporarily workaround this issue by adding `-fstype nfs -o -fstype nfs4` to the `-prune` part of the condition[0], but that doesn't cover all possible remote filesystems. Another possibility would be to ignore `/mnt` altogether.

[0]
```diff
--- ../test/test-execute/exec-dynamicuser-statedir.service	2018-10-09 12:07:04.793759716 -0400
+++ exec-dynamicuser-statedir.service	2018-10-09 12:07:01.321759716 -0400
@@ -12,7 +12,7 @@
 ExecStart=test -f /var/lib/private/quux/pief/yayyay
 
 # Make sure that /var/lib/private/waldo is really the only writable directory besides the obvious candidates
-ExecStart=sh -x -c 'test $$(find / \( -path /var/tmp -o -path /tmp -o -path /proc -o -path /dev/mqueue -o -path /dev/shm -o -path /sys/fs/bpf \) -prune -o -type d -writable -print 2>/dev/null | sort -u | tr -d '\\\\n') = /var/lib/private/quux/pief/var/lib/private/waldo'
+ExecStart=sh -x -c 'test $$(find / \( -fstype nfs -o -fstype nfs4 -o -path /var/tmp -o -path /tmp -o -path /proc -o -path /dev/mqueue -o -path /dev/shm -o -path /sys/fs/bpf \) -prune -o -type d -writable -print 2>/dev/null | sort -u | tr -d '\\\\n') = /var/lib/private/quux/pief/var/lib/private/waldo'
 
 Type=oneshot
 DynamicUser=yes
```
Is any of the aforementioned solutions reasonable?

**Comment by poettering** [comment]
Hmm, i wonder if we shouldn't add a new conditionalization for this, similar to the slow test logic we already have `$SYSTEMD_SLOW_TESTS` already. maybe `$SYSTEMD_LARGEFS_TESTS` or so, which could be used to turn off tests that don't perform on overly large file system hierarchies... @keszybz ideas?

In general I think it#s kinda nice that the test does what it currently does, i.e. guarantees that nothing is writable that shouldn't be writable, and is really comprehensive in that.
