### ISSUE TITLE
init segfaults during boot: null dereference due to DefaultTasksMax override

### ISSUE THREAD

**Issue by itayperl** [systemd/systemd#10362]
**systemd version the issue has been seen with**
> v237 (seems to be still an issue on the latest master)

**Used distribution**
 > Ubuntu 18.04

**Unexpected behaviour you saw**
 > /sbin/init segfaults at boot => kernel panic.

**Steps to reproduce the problem**
> Add the following configuration to /etc/systemd/system.conf.d:

```
[Manager]
DefaultTasksAccounting=no
DefaultTasksMax=
```

**More info**
> The segfault seems to occur at this line:
https://github.com/systemd/systemd/blob/8e04444385ddf6cbf9e172cc63e59a351ad39d74/src/core/load-fragment.c#L3096
(Seems that userdata is NULL.)

> The same config file worked fine on v229.

**Comment by yuwata** [comment]
Fix is waiting in #10364.
