### ISSUE TITLE
nspawn: $PATH when executing COMMAND is not correctly set

### ISSUE THREAD

**Issue by aude** [systemd/systemd#10377]
**systemd version the issue has been seen with**
 > ```
 > $ systemd-nspawn --version
 > systemd 239
 > +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
 > ```

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > ```
 > # systemd-nspawn -q -i debian.img rm
 > /bin/rm: missing operand
 > Try '/bin/rm --help' for more information.
 > ```

**Unexpected behaviour you saw**
 > ```
 > # systemd-nspawn -q -i debian.img rm
 > execv(rm) failed: No such file or directory
 > ```

**Steps to reproduce the problem**
 > ```
 > # systemd-nspawn -q -i debian.img rm
 > # systemd-nspawn -q -i debian.img /bin/rm
 > ```

**Discovery**
See https://github.com/systemd/mkosi/pull/266#issuecomment-428608161 for analysis of the bug, by @lucaswerkmeister.

**Comment by lucaswerkmeister** [comment]
The lazy solution would be to do `setenv("PATH", DEFAULT_PATH_COMPAT, 1)` right before the `execvpe`, but that probably causes headaches if the `execvpe` fails and we need to call any other programs as part of error handling.

Is there an existing library function to look up a binary in a `$PATH`-like string? I couldn’t find one in glibc or systemd.

**Comment by poettering** [comment]
> The lazy solution would be to do `setenv("PATH", DEFAULT_PATH_COMPAT, 1)` right before the `execvpe`, but that probably causes headaches if the `execvpe` fails and we need to call any other programs as part of error handling.

We don't execute any external programs after the execvpe() fails in the container child. We just exit then with a failure code, hence things should be fine, if we just update $PATH

**Comment by poettering** [comment]
> Is there an existing library function to look up a binary in a `$PATH`-like string? I couldn’t find one in glibc or systemd.

we actually do have something there we could easily extend to support this: find_binary() in src/basic/path-util.c. That said, I think just setting $PATH correctly is the better solution.

**Comment by poettering** [comment]
Fix waiting in #10389.
