### ISSUE TITLE
Provide proofs for the graph theory used in systemd

### ISSUE THREAD

**Issue by foouzer** [systemd/systemd#10370]
Provide formal proofs and tests for the graph made use of in PID1 to determine if the implementation works exactly as intended, provable mathematically.

**Comment by poettering** [comment]
Well, we are software engineers, not scientists, we write software not papers. Note that the graph theory we do is not particularly fancy, it's first semester CS at uni...

I mean, we'd welcome if there's somebody who'd like to work on this, but this here is a bug and RFE tracker, and I am not sure a scientific paper could be considered a bugfix nor a feature. Hence closing.

**Comment by foouzer** [comment]
You don't have to be a scientist to provide formal proofs, this is ofcourse a much recent practice that was not very popular before (esp back when systemd waa written, which I do understand), these days even some of the kernel code (eg. in WireGuard) is mathematically provable. It's usually a good idea to verify the implementation mathematically so that it has some gurantees of working as intended, considering its application is in a critical part of Linux's infrastructure.

Do keep in mind that both of systemd's counterparts, SMF and launchd, implemented provable graph theory, and their authors themselves worked on it because they knew the code best. This was just a reminder because systemd is the only software in the same class of service managers which hasn't done so yet.

**Comment by poettering** [comment]
> Do keep in mind that both of systemd's counterparts, SMF and launchd, implemented provable graph theory, and their authors themselves worked on it because they knew the code best.

links?
