### ISSUE TITLE
systemd-resolved fails to start with MemoryDenyWriteExecute=yes

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#10386]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > OpenMandriva Lx Cooker

**Expected behaviour you didn't see**
 > systemd-resolved starts without errors
as a workaround i've just commented out MemoryDenyWriteExecute=yes in systemd-resolved.service

**Unexpected behaviour you saw**
 > in journald i see these errors:
/lib/systemd/system/systemd-resolved: error while loading shared libraries: libgmp.so.10 cannot enable executable stack as shared object requires: Operation not permited

**Steps to reproduce the problem**
Download this ISO https://abf.openmandriva.org/platforms/cooker/products/50/product_build_lists/2260
and observe the issue.

**Comment by poettering** [comment]
That's a linking problem in Mandriva. Please report this to mandriva, they should require an executable stack really...
