### ISSUE TITLE
System has not been booted with systemd as init system (PID 1)

### ISSUE THREAD

**Issue by gauloics** [systemd/systemd#10396]
when i run
`systemctl`
>System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

I installed Archlinux on my Android device, it seems successful, but I encountered that problem, what happened?

**Comment by kirbyfan64** [comment]
This is the systemd bug tracker, not a support place. That being said, if you installed Arch inside Termux, you're not using systemd and can't use systemctl.
