### ISSUE TITLE
bls: Section about unified kernel image violates the spec itself and seems out of scope

### ISSUE THREAD

**Issue by i-c-o-n** [systemd/systemd#10399]
The formal bikeshedding first: It says earlier in the spec:
"`$BOOT/loader/` is the directory containing all files defined by this specification"
The current path to unified kernel images `$BOOT/EFI/Linux` violates this.

I don't know where/when/if this addition has been discussed, please point me to any discussion. If there wasn't any we should have it now, I guess.

That the path doesn't match is also a hint that it doesn't belong into *this* spec. I guess it could be handled in an EFI addendum, though?

Also, the spec seems to try to be OS independent on one end. I guess it should try to be architecture/platform/firmware independent on the other end, too.

**Comment by poettering** [comment]
> I don't know where/when/if this addition has been discussed, please point me to any discussion. If there wasn't any we should have it now, I guess.

This has been discussed in various places (in particular offline) for a long time. In particular the dracut initrd generator had support for this kind of image for quite long, and sd-boot support was added a bit back too. Only recently we documented this in the spec though.

> That the path doesn't match is also a hint that it doesn't belong into _this_ spec. I guess it could be handled in an EFI addendum, though?

Well, it's kinda an "addendum" already. It's the optional part of the spec. Right now it's specific to UEFI, but I think we could extend this to other firmware types too, if it's interesting there. The main reason to have them is support for signed kernels, as it means the whole metadata, the kernel and the initrd can be signed as a whole with the firmware validating things for us.

But you are right, this definitely could use some rewording, to make things clearer. I'll cook up a PR for that.

**Comment by poettering** [comment]
I prepped #10415 now, trying to clear up the difference between two kinds of snippets and calling them Type #1 and Type #2. I hope this addresses your points somewhat.

**Comment by poettering** [comment]
> Also, the spec seems to try to be OS independent on one end. I guess it should try to be architecture/platform/firmware independent on the other end, too.

Well, it's not though, I mean we do support the "efi" stanza in the Type #1 entries already...

I mean, we are talking about boot loaders. I figure we'll always have to cater for some pecularities of firmwares and archs, we can't be completely generic. 

Anyway, I hope by distinguishing Type #1 and Type #2 clearly I hope it's more obvious now what the generic and what the UEFI specific part is.

**Comment by i-c-o-n** [comment]
On 10/16/18 11:57 AM, Lennart Poettering wrote:
>> I don't know where/when/if this addition has been discussed, please point me to any discussion. If there wasn't any we should have it now, I guess.
> 
> This has been discussed in various places (in particular offline) for a long time. In particular the dracut initrd generator had support for this kind of image for quite long, and sd-boot support was added a bit back too. Only recently we documented this in the spec though.

This seems to be a common industry style to weaken standards. Somebody
already implemented something differently, so let's just add it to the
standard? That doesn't feel right.

I didn't think too much about it when opening this issue, but now... I
see that this really redefines the core of BLS, which used to be about
plain configuration snippets, for simplicity.

It also raises compatibility questions (I didn't go through your PR yet,
maybe it's already answered), e.g. is it mandatory to support unified
kernel images on a UEFI system? What if the author of a boot loader
doesn't know that it will run on a UEFI system? Is it still BLS com-
pliant if not?

Now it seems to me (I'm tired, maybe it looks better tomorrow) to be
asking for chaos that the BLS originally tried to avoid. We could miti-
gate this by specifying that each unified image should have a redun-
dant configuration snippet, I guess.

> 
>> That the path doesn't match is also a hint that it doesn't belong into _this_ spec. I guess it could be handled in an EFI addendum, though?
> 
> Well, it's kinda an "addendum" already. It's the optional part of the spec. Right now it's specific to UEFI, but I think we could extend this to other firmware types too, if it's interesting there. The main reason to have them is support for signed kernels, as it means the whole metadata, the kernel and the initrd can be signed as a whole with the firmware validating things for us.

Having all in one file sounds wrong. But I don't know PE signatures,
maybe they did it right. Generally, you'd want to parse as little as
possible before you verify a signature.

**Comment by poettering** [comment]
> This seems to be a common industry style to weaken standards. Somebody already implemented something differently, so let's just add it to the standard? That doesn't feel right. 

Well, it's the same people (Kay, Harald, Lennart, …) who wrote the original spec who came up with the unified kernel stuff. it's the same people who implemented the initial spec in dracut, gummiboot/sd-boot, systemd, mkosi, … who then slightly later added the unified kernel stuff too. We discussed this in the same forums as the original stuff, i.e. in person, at conferences in those relevant code repos. But yes, you are right to some point: the boot loader spec is not the result of a long public discussion with input from a comprehensive number of stakeholders, but is simply an agreement with a limited set of people who wanted to play along and worked toward a common goal.

In general, I think to a certain degree specs should focus on what is real, not on wishes. Given that that the unified kernel stuff is closely aligned with the older text dropins, and that it is *real* (as in "implemented") and makes sense to the editors (i.e. the same folks who implemented it), I think it's only natural to cover it too in the same spec.

> I didn't think too much about it when opening this issue, but now... I see that this really redefines the core of BLS, which used to be about plain configuration snippets, for simplicity. It also raises compatibility questions (I didn't go through your PR yet, maybe it's already answered), e.g. is it mandatory to support unified kernel images on a UEFI system? 

Well, not it's not. And these are guidelines anyway, they are recommendations only. We have no certification process or any kind of control that people follow it closely anyway. I mean, even if we wanted to make it "mandatory", what would that even mean? we are not the police, and really shouldn't be.

In general, the concept of the spec is to describe how you discover boot menu items, and then filter all out that don't apply to you, by architecture, by firmware reqs, by kernel image format and so on. I'd include in that that you don't have to support unified images if you don't want to have code for extracting the PE metadata.

I'll add a paragraph making this kind of "filter what you don't like" logic clearer.

> What if the author of a boot loader doesn't know that it will run on a UEFI system? Is it still BLS com- pliant if not? Now it seems to me (I'm tired, maybe it looks better tomorrow) to be asking for chaos that the BLS originally tried to avoid. We could miti- gate this by specifying that each unified image should have a redun- dant configuration snippet, I guess.

The idea of the spec is that the boot loader only uses the discovered boot entries that match what it can start and ignores the rest. And similar, somebody who puts together an OS image should figure out which kind of systems they want to support and then adds entries exactly matching exactly those.

**Comment by i-c-o-n** [comment]
> In general, I think to a certain degree specs should focus on what is real, not on wishes. Given that that the unified kernel stuff is closely aligned with the older text dropins, and that it is _real_ (as in "implemented") and makes sense to the editors (i.e. the same folks who implemented it), I think it's only natural to cover it too in the same spec.

That would be documentation not specification in my understanding. Seems also a way to justify the shortcut to signed images instead of adding that in a generic manner. I do understand why you are doing this, I just wouldn't call it specification then.

> > I didn't think too much about it when opening this issue, but now... I see that this really redefines the core of BLS, which used to be about plain configuration snippets, for simplicity. It also raises compatibility questions (I didn't go through your PR yet, maybe it's already answered), e.g. is it mandatory to support unified kernel images on a UEFI system?
> 
> Well, not it's not. And these are guidelines anyway, they are recommendations only. We have no certification process or any kind of control that people follow it closely anyway. I mean, even if we wanted to make it "mandatory", what would that even mean? we are not the police, and really shouldn't be.

Right, there is no police that can enforce something. But that doesn't mean you shouldn't try at least to specify what you think is right. And optional parts in a spec are dangerous, IMHO. If you don't take very special care, they'll lead to incompatibilities.

> > What if the author of a boot loader doesn't know that it will run on a UEFI system? Is it still BLS com- pliant if not? Now it seems to me (I'm tired, maybe it looks better tomorrow) to be asking for chaos that the BLS originally tried to avoid. We could miti- gate this by specifying that each unified image should have a redun- dant configuration snippet, I guess.
> 
> The idea of the spec is that the boot loader only uses the discovered boot entries that match what it can start and ignores the rest. And similar, somebody who puts together an OS image should figure out which kind of systems they want to support and then adds entries exactly matching exactly those.

Here lies the point, to "figure out which kind of system" is also what an OS installer has to do. Assuming it finds an empty hard drive, that's easy, it would just install a boot loader and know what it supports. But if there are already both BLS configs and unified kernel images on a hard drive, an OS installer might see that and ask the user "Hey, you seem to be using BLS. Do you want our new and fancy boot loader installed?". What if that new boot loader doesn't support unified kernel images?

Of course, this can be averted by telling OS developers what to do and what not to do. But it makes the overall process more complex than necessary and leaves setups more fragile. And that's what my original impression of the BLS was, that it wants to avoid unnecessary complexity to have something reliable.

**Comment by poettering** [comment]
> That would be documentation not specification in my understanding. Seems also a way to justify the shortcut to signed images instead of adding that in a generic manner. I do understand why you are doing this, I just wouldn't call it specification then.

Well, the actual signing is highly firmware specific. On EFI signed images need to be PE, hence a completely generic solution is not really possible in this case. 

But dunno, call it spec, call it documentation, I am not too concerned about the name, I just think we should declare clearly how this all is supposed to work, what the interfaces are that we think make sense and that are implemented in the various tools already.

**Comment by poettering** [comment]
> Here lies the point, to "figure out which kind of system" is also what an OS installer has to do. Assuming it finds an empty hard drive, that's easy, it would just install a boot loader and know what it supports. But if there are already both BLS configs and unified kernel images on a hard drive, an OS installer might see that and ask the user "Hey, you seem to be using BLS. Do you want our new and fancy boot loader installed?". What if that new boot loader doesn't support unified kernel images?

One of thing on the TODO list in git is currently to document how to correctly identify boot loader spec partitions, i.e. how to determine whether the ESP is used for boot loader spec or not. My current thinking there is to make it simple: make it dependent on the existance of a directory /loader/entries wether the the spec is supported or not. Now, to address your point, we could take this one step further: if a boot loader supports both drop-in snippets then it should create /loader/entries, and if it supports drop-in unified kernels /EFI/Linux. That means there's a clear way to determine whether Type #1 or Type #2 are supported: just check if the relevant directory is around.

With that approach it's relatively straight-forward to determine where to drop kernels:

1. If there's a dedicated boot loader spec partition use it, and there's /loader/entries or /EFI/Linux use it
2. If there's a dedicated partition and it lacks both, install a boot loader, and create the two dirs, matching what you support.
3. If there is no dedicated partition, but there's an ESP and it has /loader/entries or /EFI/Linux, use either of it.
3. If there is no dedicated partition and the ESP has neither directory, but it is large enough, install a boot loader into it, and one or both dirs (depending on what you want to support)
4. Otherwise, create a dedicated boot loader spec partition, install a boot loader supporting it, and create the dirs, as supported
