### ISSUE TITLE
split shared/ into several directories with well-defined dependency rules

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#104]
We need to sort out the cyclic linking errors. Proposed layout:

generic library code, everything in the tree can use it, but it itself cannot use anything outside of its own directory:
  src/util/strv.c
  src/util/hashmap.c
  ...

public libraries, they cannot use anything in shared/
  src/libsystemd/sd-bus/bus.c
  src/libsystemd/sd-event/mainloop.c
  ...

specialized internal libraries with a specific topic in a subdirectory, they can use libsystemd/
  src/shared/machine/container.c
  src/shared/bus/convenience.c
  ...

**Comment by poettering** [comment]
Looks good to me.

**Comment by teg** [comment]
Sounds perfectly reasonable to me. One question to see if I got it right: each of the folders in src/shared/ will have its own internal library, or will they all be linked into one? I'd have hoped for the former to avoid proliferation of obscure external dependencies.

**Comment by poettering** [comment]
I think we should keep the libraries we build at a minimum, and only do so when this is worth it due to deps reduction.

**Comment by zonque** [comment]
This was fixed with #160
