### ISSUE TITLE
udev rules as units

### ISSUE THREAD

**Issue by joukewitteveen** [systemd/systemd#10406]
`systemctl enable foo` indicates that `foo` should be associated with uptime: `foo` is started when the system is booted and stopped as it halts. Some units should, however, not be associated with uptime, but with the presence of a device. We might want foo to be started when some USB device is plugged in and stopped as it is pulled out. For this, we can use udev rules.

It would be nice if such a dependency on a device could be managed via units and the `systemctl` command. A naive way would be to implement something along the lines of `systemctl enable-udev --with-device USBGADGET foo`. Alternatively, the `[install]` section of a unit could be extended to support something like `WantedByUdev=`. With the latter option we would simply use `systemctl enable foo` again.

Both options seem very nontrivial to me. Perhaps someone can come up with a simpler solution.

**Comment by poettering** [comment]
Use ENV{SYSTEMD_WANTS} in udev rules, see systemd.device(5) for information. This will pull in units unconditionally though. To uncouple this, and make this subject to enable/disable insert an intermediary target, i.e. that ENV{SYSTEMD_WANTS} pulls in some target unit, and the WantedBy= inside your actual unit specifies that target unit instead.

**Comment by joukewitteveen** [comment]
This much I knew already. However, the udev rules system is currently quite distinct from systemd units. They cannot be controlled via anything like `systemctl` and their syntax is very different. I maintain a network manager that generates systemd units and would have hoped to avoid having it interface with udev rules too.

**Comment by joukewitteveen** [comment]
So you see no route to tighter integration? No friendlier syntax for simple udev rules that only interface with systemd units? No `udevctl` to `enable' or `disable' rules?

**Comment by boucman** [comment]
can't you use WantedBy=<the device unit> so you can enable/disable that unit exactly like you want ? If you need something a bit more generic, you can declare a generic Alias for a specific device on the udev side, and then use WantedBy=<the alias>

**Comment by poettering** [comment]
> So you see no route to tighter integration? No friendlier  syntax for simple udev rules that only interface with systemd units? No udevctl to enable or disable rules?

As mentioned, I think a nice way to allow the effect of udev rules pulling in services be subject to effect of enable/disable is by adding an intermediary target unit, and then hooking the actual service to pull in into that with its [Install] section. That delivers the desired behaviour, as the user only has to enable/disable the unit he's interested in, and doesn't have to care about the udev rule logic in the background.

**Comment by poettering** [comment]
To given an example how this could work: 

1. write a .rules file that matches all devices of the kind you care about and sets the "systemd" tag on it, as well as the SYSTEMD_WANTS property pointing to "myintermediarytargetunit.target".

2. Define myintermediarytargetunit.target as something like this:
```
[Unit]
StopWhenUnneeded=yes
Description=My kind of hw got plugged in
```

3. inside of the actual service unit you care about write:
```
…
[Install]
WantedBy=myintermediarytargetunit.target
…
```

That way, the intermediary target is always pulled in when at least one device of the kind you care about is around and automatically cleaned up if all devices of that kind go away. And if your actual service is enabled then it is hooked into that.

**Comment by joukewitteveen** [comment]
Which is precisely not what you want, right? The unit should be triggered by the device, but only when the multi-user target is (soon to be) reached. For instance, when booted into `rescue.target` we may not want to start a device-triggered unit.

**Comment by mbiebl** [comment]
I don't think that is necessarily true. That really depends on the type of service you want to start.

**Comment by poettering** [comment]
> Which is precisely not what you want, right? The unit should be triggered by the device, but only when the multi-user target is (soon to be) reached. For instance, when booted into `rescue.target` we may not want to start a device-triggered unit.

Add Requisite= to your service unit file, expressing requirement on basic.target and myintermediarytargetunit.target

**Comment by joukewitteveen** [comment]
Thanks for all your help, things are not as bad as I thought they were.
Taking the risk of turning this feature suggestion into a support thread, may I ask why you suggest `basic.target` instead of `multi-user.target`?
