### ISSUE TITLE
outdated documentation for systemd and possibly logind dbus apis

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#1042]
Hello.
I actually do not know if this is an appropriate place to report this, I have noticed that systemd dbus api documentation is outdated slightly.
I do not know if all methods and properties are described, but I am sure that the documentation that I saw says that systemd does not check/use policykit for permission checks, and that is no longer the case it seems.
About logind, I believe the documentation does not contain new methods, but I did not check that.

**Comment by kayrus** [comment]
bump
