### ISSUE TITLE
versioning of predictable interface names

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#10448]
During AllSystemsGo2018 we decided to version the logic to assign "stable" names to network interfaces, so that installed systems can commit to a certain naming pattern for the lifetime of the system.

In 938d30aa98df887797c9e05074a562ddacdcdf5e naming of infiniband interfaces was changed. Let's not forget to put this under the versioning mechanism.

**Comment by yuwata** [comment]
@keszybz What do you think about also introducing versioning for sata, sas or other devices? See #3943 and #10601.

**Comment by poettering** [comment]
Fix waiting in #11110
