### ISSUE TITLE
RFE: add a way to specify additional files/dirs to relabel after selinux policy loading

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#10466]
As requested by @lucab:

Implementation idea: in mount-setup.c simply open /run/systemd/relabel.files or so, with one path per line, relabel everything recursively below each, then delete the file. This way ignition can make changes to the host fs from the initrd, and still get properly labelled selinux file in a safe and race-free way, without having systemd unconditionally relabel the whole OS tree all the time.

**Comment by lucab** [comment]
For reference, this is coming from the issues @jlebon highlighted in https://github.com/coreos/ignition/issues/635#issuecomment-425493251.

**Comment by lucab** [comment]
Browsing around, it seems that this feature would be beneficial for other producers too (e.g. https://github.com/ostreedev/ostree/pull/872). To avoid file single-contention from multiple writers, as a minor addition to the RFE above, it would be better to have a directory of list-files (`relabel.d`) and scan-apply-delete each one in order.

**Comment by poettering** [comment]
Fix waiting in #11131.
