### ISSUE TITLE
Creating VTI(6) interface using netdev files does not work

### ISSUE THREAD

**Issue by 1848** [systemd/systemd#10479]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > VTI interface is created.

**Unexpected behaviour you saw**
 > VTI is not showing up.

**Steps to reproduce the problem**
> Just try the example 7 from https://www.freedesktop.org/software/systemd/man/systemd.netdev.html

**Description**
I am trying to create a VTI interface using netdev.
This is the file I am using:
```shell
[NetDev]
Name = vti4
Kind = vti
 
[Tunnel]
Local = LOCAL_IP
Remote = REMOTE_IP
Key = 44
```
When I do a systemd-networkd restart nothing shows up using ip link show.
When I create the interface manually using:
```shell
ip tunnel add vti4 local LOCAL_IP remote REMOTE_IP mode vti key 44
```
it works fine.
I also noticed that the required kernel modules (e.g. ip_vti) are not getting loaded using the systemd approach.
networkd log shows nothing about vti.
I did check if the .netdev file is even loaded by putting a syntax error in it. networkd complained about it so the file is getting loaded.
I could reproduce this issue on debian9.
Someone else could reproduce it too.

Any more information which could help?
Thanks.

**Comment by yuwata** [comment]
Please also see the example in systemd.network(5). It requires a corresponding .network file which has e.g. `Tunnel=vti4`. Or, please add `Independent=yes` in the .netdev file.

**Comment by 1848** [comment]
Aww, "Independent=yes" did it.
I dont know how I missed that, thank you very much!
