### ISSUE TITLE
Forwarded ports are not listened to on the host

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#10478]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Fedora 29

**Expected behaviour you didn't see**
 > `systemd-nspawn --network-zone=blah --port=12345 …`
This should start listening on the host's port 12345.

**Unexpected behaviour you saw**
 > same command
`netstat -nl` doesn't show that port 12345 is listened to.

**Steps to reproduce the problem**
I'll work on a set of minimal commands.

Is there some way to debug what's going on? There aren't any error messages about failing to forward a port. `iptables -L` shows nothing (I've disabled `firewalld` on the host).

**Comment by mathstuf** [comment]
This might be the same as #6106.

**Comment by poettering** [comment]
These port mappings are done with netfilter and hence won't show up in netstat. That's a limitation of the Linux kernel/netstat, but systemd can't do much about it. To list the "nat" table. `iptables -t nat -L`.

Anyway, closing this here as there isn't any bug here.

**Comment by mathstuf** [comment]
Thanks for the info. FWIW, I've been able to get ports exposed from the container to the host, but from outside the host, additional routing still seems to be necessary so far (the ports are on the bridge interface, but the external ethernet needs forwarding rules it seems). Still working on it.
