### ISSUE TITLE
[Question] Dependencies for "DNS-over-TLS" support

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#10480]
Hi, I curious at "DNS-over-TLS" support in "resolved". I glad to add support for this feature in my Linux distribution. So, what dependencies I need to install for that? Thanks!

**Comment by poettering** [comment]
This is not a support forum but a bug and RFE tracker. Please contact your downstream distribution for help regarding how they packaged stuff for you. Thank you for understanding.
