### ISSUE TITLE
add ephemeral to nspawn-settings.

### ISSUE THREAD

**Issue by sequencer** [systemd/systemd#10485]
**Is your feature request related to a problem? Please describe.**
I wanna use `systemctl enable systemd-nsapwn@mycontainer.service` to control my nspawn, but I also wanna use `--ephemeral` to boot `mycontainer`, so that it can't be changed. 

**Describe the solution you'd like**
Add this parameter to [nspawn-settings.c](https://github.com/systemd/systemd/blob/41159592f80796a2b14158f352912d1b3cf7bf61/src/nspawn/nspawn-settings.c) file

**Describe alternatives you've considered**
write a service in `/etc/systemd/system/` not in `/etc/systemd/nspawn` with `mycontainer.nspawn` file.

**Comment by poettering** [comment]
#10488 has been merged. closing
