### ISSUE TITLE
Fedora CI seems to have vanished

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10489]
I was going to open an issue regarding [not installing `libasan`](https://github.com/systemd/systemd/pull/10190#issuecomment-425300630) there when I noticed that it has vanished altogether in the sense that I couldn't find it in the last 5 PRs including https://github.com/systemd/systemd/pull/10476 I created 2 days ago. Does anybody know what happened to it?

**Comment by keszybz** [comment]
@mrc0mmand any idea?

**Comment by mrc0mmand** [comment]
@keszybz after a quick glance it looks like it keeps crashing quite frequently (it was down for the past hour or so when I last checked). Anyway, given the description I thought it's part of the [Fedora CI](https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/) project, but apparently it's something completely different (at least according to the [landing page](http://38.145.33.116/systemd-pr/status_report.html)). Is there some *wiki* page with details for this CI?

**Comment by keszybz** [comment]
> Is there some wiki page with details for this CI?

None, afaik.

**Comment by mrc0mmand** [comment]
I went through the logs and the target [copr repo](https://copr.fedorainfracloud.org/coprs/flepied/systemd-pr-x86_64/) is owned by @flepied. Hopefully he knows what's going on with the rawhide CI.

**Comment by evverx** [comment]
Now that it's working what should be done to install `libasan` and pass `-Dslow-tests=true` to `meson` there?

**Comment by fredericlepied** [comment]
@evverx you need to make a PR to https://src.fedoraproject.org/rpms/systemd/branch/rpm-master to change the spec file that is used to build the proposed changes.

**Comment by evverx** [comment]
@fredericlepied thank you. This will help to run the fuzzers against the crash reproducers, but, as far as I can see, it isn't possible to change the way the tests are run. Currently there're a lot of tests (some of which are kind of important like `test-execute`) that are just skipped because they aren't run as `root`. Is there a way to make it work too?

**Comment by fredericlepied** [comment]
@evverx we need to discuss to resurrect the Fedora pipeline if we want to run tests like these. @johnbieren what do you think?

**Comment by johnbieren** [comment]
@fredericlepied Resurrecting the Fedora rawhide pipeline to run the standard-test-roles defined tests has been on my TODO list for months, but has been low priority so I haven't gotten to it. I still have not totally figured out how to trigger only if the DLRN part succeeds. If it is something that is actively being asked for I can try scheduling it into one of my next sprints

**Comment by evverx** [comment]
By the way, Fedora CI seems to be broken again: http://38.145.33.116/systemd-pr/1e/8a/1e8af114ef479392b54ed7178a95031b87252803_dev/rpmbuild.log.

**Comment by evverx** [comment]
@keszybz it seems that Fedora CI isn't suitable for being continuous in the literal sense of the word. Apart from that, it doesn't run important tests so it isn't as useful as it might seem to be and, as far as I can see, it's unlikely to be fixed any time soon. Could it be just turned off? If anyone needs to build `systemd` on Fedora and run the unit tests there, it's possible to do that by utilizing Travis CI.

**Comment by evverx** [comment]
Reverting 3f4b547a55f4fd2599d and tweaking `.travis.yml` should be enough to make everything work.

**Comment by evverx** [comment]
This way it would be possible to control what is installed there and how the tests are run and we can do it all ourselves without CCing people who rarely show up here.

**Comment by evverx** [comment]
Anyway, there isn't much left to discuss here regarding the original issue. I'm closing it.

**Comment by mrc0mmand** [comment]
@evverx well, *theoretically* it should be possible to reuse scripts from the [CentOS CI](https://github.com/systemd/systemd-centos-ci) (+ a simple docker wrapper) and run them in Travis, which should reduce the CI fragmentation a little bit. However, I'm not sure in which state was the Travis CI in the last time it was up, so hard to say if wouldn't be a step back.

**Comment by evverx** [comment]
Frankly, the state was far from ideal given that that part had never worked :-) If I recall correctly it took about a year to generate the correct secure strings and rip off "unnecessary" bits so that it would start send data to Coverity at least.

**Comment by evverx** [comment]
Regarding the fragmentation, I think it's not that bad providing that every environment is more or less real. Running containers on Ubuntu Trusty (or whatever else is currently being used on Travis CI) won't help to see how the code works with different versions of the kernel. But it's, nonetheless, better than a CI system that fails more often than not.

**Comment by evverx** [comment]
@mrc0mmand having said that, it'd be great if you could reuse the scripts form the CentOS CI. I suggested reverting 3f4b547a55f4fd2599df5101d4be3b95fe0222c4 and tweaking `.travis.yaml` a bit because It's just something that could be used as a kind of foundation to build on. Anything that works would suffice :-)

**Comment by mrc0mmand** [comment]
@evverx I'd be happy to play with Travis, just don't want to mess with someone else's work

**Comment by evverx** [comment]
@mrc0mmand as far as I know, Travis CI isn't maintained by anybody. @keszybz and I finally made the coverity part work in https://github.com/systemd/systemd/issues/9186 and then I just added commits like 1e79d09ef9f7befe5 to stabilize it and f5dd4eeca299c86 to make it easier to see when something goes wrong. Frankly, I have never seen anybody except me reacting to failures. I hope I understood what messing with someone else's work means correctly.

**Comment by evverx** [comment]
@mrc0mmand just to sum up, basically in https://github.com/systemd/systemd-centos-ci/issues/18 I'm watching you making what I though was impossible possible, so, I personally would be very happy if you started playing with Travis CI however you like be it adding a lot of targets like CentOS, Arch, Ubuntu, Fedora and so on or just building `systemd` on Fedora.

**Comment by mrc0mmand** [comment]
@evverx will definitely look into that tomorrow, thanks!
