### ISSUE TITLE
Logitech Performance MX Resolution

### ISSUE THREAD

**Issue by waucka** [systemd/systemd#1049]
Lines from mouse-dpi-tool:

```
mouse:usb:v046dp101a:name:Logitech Performance MX:
 MOUSE_DPI=1000@166
```

**Comment by waucka** [comment]
@whot : I can't figure out how to assign this issue to you.

**Comment by zonque** [comment]
@waucka could you submit this as pull request?

**Comment by waucka** [comment]
Sure, but it will take a few hours (at work right now).

**Comment by phomes** [comment]
The performance mx mouse is already in the hwdb:
https://github.com/systemd/systemd/blob/master/hwdb/70-mouse.hwdb#L245

However, I only measured it to 800@166. While looking for the specs I can see that the DPI for it can be adjusted. I wonder if the one I tested was perhaps not in its default setting. Can you tell if 1000 is the default?

**Comment by waucka** [comment]
Huh.  I didn't see that when I checked the file previously.  I'll have to check the mouse again tomorrow, since it's at work.  I didn't have the greatest measuring tools there, just a piece of paper that I assume is 11.5 inches long.  I'll use a ruler tomorrow.

**Comment by whot** [comment]
dunno how you assign it to me, but as soon as mentioned my nick I got emails :)

logitech's website claims 100-1500 dpi, so there is the off chance of the device shipping with different default resolutions

**Comment by waucka** [comment]
Confirmed: mine is 1000 DPI.  It looks like there's a way to to change the DPI on Linux (http://derhofbauer.at/blog/blog/2012/08/28/logitech-performance-mx/), so I'll poke at that a bit.  How do we handle variable-DPI devices?

**Comment by whot** [comment]
@waucka https://github.com/libratbag/libratbag is what we started recently for the mouse configuration. still quite raw, but hopefully it'll get enough inertia to replace all the custom tools that work for exactly one device.

as for the question: we don't. we use the default DPI and ignore the rest. the default DPI is important so the out-of-the-box behaviour is useful. when you toggle DPIs, then we assume you know what you're doing and we still assume the original DPI

**Comment by waucka** [comment]
OK, well it looks like the default DPI for mine is 1000 and the default DPI somebody else's is 800.  (Assuming that person didn't change it under Windows, and that the Windows software doesn't automatically change the DPI to 800 even though the firmware's default is 1000, etc.)

What are the ramifications of a situation like this?

**Comment by whot** [comment]
could be that Logitech used different sensors on the device, or that the software sets a default of 800 when you plug it in the first time. Not much we can do here at this point, but fortunately the 
ramifications are limited. the difference between 800 and 1000 is small enough that it's probably not worth worrying about. see if you can tell the difference between the two settings, chances are you won't notice much.

**Comment by phomes** [comment]
The mouse does not have hardware buttons to adjust the DPI. It can only be set from software. The mouse I tested was used and if the mouse stores the selected DPI then the 800 I tested may very well not be the default. If the default for your mouse is 1000 then I think it would make sense to go with that.

**Comment by waucka** [comment]
Yeah, my mouse has never been used by anyone other than me, and only on Linux.  So, 1000 is presumably the factory default setting, although I won't be surprised if somebody else shows up with a brand new mouse with a different default.

**Comment by whot** [comment]
right, I'll update this to 1000 dpi then. since 1000 is the default, that's a better value to have anyway.

https://github.com/systemd/systemd/pull/1087
