### ISSUE TITLE
revert IMA copy_bytes() hack

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#105]
We really should figure out what's going on here:

http://lists.freedesktop.org/archives/systemd-devel/2015-June/032797.html

**Comment by poettering** [comment]
And we should revert the half-baked patch unless we really understand the issue.

**Comment by keszybz** [comment]
I'd prefer to keep this open for now. It seems we are moving towards a resolution.

**Comment by zonque** [comment]
Fixed via #167
