### ISSUE TITLE
Unit activation via path units eats a lot of cpu if PathExistsGlob= is used

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#10503]
**Reproducer**
Reproduced on the latest master (commit d1db1c438f04a6d511dd5c825451fbe156d3507e).
The path unit:
```
# systemctl cat test-path.path
# /etc/systemd/system/test-path.path
[Unit]
Description=TestPath Path
[Path]
PathExistsGlob=/var/spool/test/d*
```
The service unit:
```
# systemctl cat test-path.service
# /etc/systemd/system/test-path.service
[Unit]
Description=TestPath
[Service]
ExecStart=/usr/bin/bash -c "while true; do sleep 1; done"
```
Rest of preparation:
```
# mkdir -p /var/spool/test/
# systemctl stop test-path.service test-path.path
# systemctl start test-path.path
# top -d 1
```
Now, in another terminal, run the following loop:
```
# for i in $(seq 1 20000); do touch /var/spool/test/d-$i; done
```
What you can observe in the output of `top` is that the main systemd process is eating a lot of the cpu and getting progressively worse over time. What appears to be happening is that transactions are started and inotify watches created over and over again, even though after the first trigger of the service unit, the rest should be noop.

**Expected behavior**
When the service is activated for the first time, the watches should no longer be there and no jobs should be created. This is probably simplistic, but something along those lines should happen. As a result, systemd would not be "thrashing" the cpu.

**Comment by jsynacek** [comment]
The following path fixes the issue, even though it's likely not correct:
```
diff --git a/src/core/path.c b/src/core/path.c
index 1c6b6a880..d6a7631df 100644
--- a/src/core/path.c
+++ b/src/core/path.c
@@ -29,6 +29,7 @@ static const UnitActiveState state_translation_table[_PATH_STATE_MAX] = {
 };
 
 static int path_dispatch_io(sd_event_source *source, int fd, uint32_t revents, void *userdata);
+static int path_stop(Unit *u);
 
 int path_spec_watch(PathSpec *s, sd_event_io_handler_t handler) {
 
@@ -472,6 +473,11 @@ static void path_enter_running(Path *p) {
                 return;
         }
 
+        if (UNIT_IS_ACTIVE_OR_ACTIVATING(unit_active_state(UNIT(p)))) {
+                path_stop(UNIT(p));
+                return;
+        }
+
         r = manager_add_job(UNIT(p)->manager, JOB_START, trigger, JOB_REPLACE, &error, NULL);
         if (r < 0)
                 goto fail;
```

**Comment by poettering** [comment]
> ExecStart=/usr/bin/bash -c "while true; do sleep 1; done"

btw, "sleep infinity" is your friend

**Comment by poettering** [comment]
i gues we should stop watching the inotify fd as soon as activated something
