### ISSUE TITLE
man pages should say that "systemctl reset-failed" also resets start limit counter and more

### ISSUE THREAD

**Issue by Spongman** [systemd/systemd#10529]
debian 9.5

my unit has
```
StartLimitBurst=3
StartLimitIntervalSec=120
```

if it enters failed state with `start-limit-hit` and i then quickly fix the issue, after a `systemctl restart` it immediately fails to start for the same reason.

shouldn't the burst count be reset if the service is manually restarted? `restart --force` doesn't help.

**Comment by poettering** [comment]
use "systemctl reset-failed" on the unit. That will reset the counters.

In systemd we make no distinction how a request of a unit was triggered in regards to the start rate limit checker. That's because "systemctl" might very likely be started from a script, i.e. as automatic as any other form of start...

Anyway, this deserves better documentation as the man page for systemctl does not explain this facet of "systemctl reset-failed". I will now convert this into an issue about fixing the man page in this regard. I hope this makes sense.

**Comment by poettering** [comment]
Fix waiting in #10569

**Comment by Spongman** [comment]
> In systemd we make no distinction how a request of a unit was triggered in regards to the start rate limit checker
couldn't we have a simple way to override this on the command line? many other tools have safety mechanism (like noclobbler) that can be simply overridden by passing a `-f` or `-q` switch.

**Comment by renukamanavalan** [comment]
I ran a script to restart rsyslog service repeatedly, which failed after 5 restarts.
So I made the script to call "systemctl reset-failed rsyslog" and resume the restart loop.
But the next attempt to "restart rsyslog" fails. 
I had to add a 7 seconds sleep after reset-failed, to let the next restart succeeds.
If I have to pause, I really don't need reset-failed.

So why is the reset-failed not helping ?

Any tips would be very helpful.

Thank you,

```
PAUSE_AFTER_FAILED_RESTART = "6s"

def _service_restart(svc_name):
    rc = os.system(f"sudo systemctl restart {svc_name}")
    if rc != 0:
        # rc = os.system(f"sudo systemctl reset-failed {svc_name}")
        rc = 0
        if rc == 0:
            os.system(f"sleep {PAUSE_AFTER_FAILED_RESTART}")
            rc = os.system(f"sudo systemctl start {svc_name}")
            if rc == 0:
                print(f"--------- succeeded to restart after reset {svc_name}")
            else:
                print(f"--------- failed to restart after reset {svc_name}")
                sys.exit(-1)
        else:
            print(f"failed to reset service {svc_name} rc={rc}")
            sys.exit(-1)

    if rc == 0:
        print(f"Restart succeeded for {svc_name}")
    return rc == 0

```
