### ISSUE TITLE
TEST-13-NSPAWN-SMOKE seems to be failing again under qemu

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#10544]
**systemd version the issue has been seen with**
> 239 (latest master - e6b538d06680857fb25e2a6da94fc416bb2340f5)

**Used distribution**
 > CentOS 7.5.1804

It's basically the same issue as in https://github.com/systemd/systemd/issues/8543:

```
[root@localhost systemd]# make -C test/TEST-13-NSPAWN-SMOKE/ clean setup run clean-again 2>&1 | tee qemu-log
...
+ systemd-nspawn --register=no -D /var/lib/machines/unified-no-cgns-no-api-vfs-writable-yes --network-namespace-path=/proc/self/ns/net --private-network -b
--network-namespace-path cannot be combined with other network options.
+ ip netns add nspawn_test
+ _netns_opt=--network-namespace-path=/run/netns/nspawn_test
+ grep -v -E '^1: lo.*UP'
+ UNIFIED_CGROUP_HIERARCHY=no
+ SYSTEMD_NSPAWN_USE_CGNS=no
+ SYSTEMD_NSPAWN_API_VFS_WRITABLE=yes
+ systemd-nspawn --register=no -D /var/lib/machines/unified-no-cgns-no-api-vfs-writable-yes --network-namespace-path=/run/netns/nspawn_test /bin/ip a
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Setting RLIMIT_CPU to infinity.
Setting RLIMIT_FSIZE to infinity.
Setting RLIMIT_DATA to infinity.
Setting RLIMIT_STACK to 8388608:infinity.
Setting RLIMIT_CORE to 0:infinity.
Setting RLIMIT_RSS to infinity.
Setting RLIMIT_NPROC to 1841.
Setting RLIMIT_NOFILE to 1024:4096.
Setting RLIMIT_MEMLOCK to 65536.
Setting RLIMIT_AS to infinity.
Setting RLIMIT_LOCKS to infinity.
Setting RLIMIT_SIGPENDING to 1841.
Setting RLIMIT_MSGQUEUE to 819200.
Setting RLIMIT_NICE to 0.
Setting RLIMIT_RTPRIO to 0.
Setting RLIMIT_RTTIME to infinity.
Spawning container unified-no-cgns-no-api-vfs-writable-yes on /var/lib/machines/unified-no-cgns-no-api-vfs-writable-yes.
Press ^] three times within 1s to kill container.
Path /run/netns/nspawn_test doesn't refer to a network namespace
[[0;1;31mFAILED[0m] Failed to start Testsuite service.
See 'systemctl status testsuite.service' for details.
...
```
Full log: https://paste.fedoraproject.org/paste/GclNXflsOfkfPWmQYDiJTw

**Comment by evverx** [comment]
I doubt the test has ever passed there because `fd_is_network_ns` used in `nspawn` can't correctly detect whether `/run/netns/nspawn_test` refers to a network namespace if the nsfs pseudo-filesystem isn't supported by the kernel (which seems to be the case here). It's basically a bug in `nspawn`.

**Comment by poettering** [comment]
> I doubt the test has ever passed there because `fd_is_network_ns` used in `nspawn` can't correctly detect whether `/run/netns/nspawn_test` refers to a network namespace if the nsfs pseudo-filesystem isn't supported by the kernel (which seems to be the case here). It's basically a bug in `nspawn`.

hmm? a bug? how can we have a network namespace fd if nsfs is turned off? That's the file system namespace handles are backed by, and if that file system is not available then the fds can't work?

Or are you saying that on old centos kernels the file system reported for netns file handles is something different from nsfs? procfs?

**Comment by poettering** [comment]
hmm, ok, i prepped #10589 now, to make this work. I only test this on my new kernel, so ensure it doesn't break anything. it's supposed to fix the centos issue though. would be great @mrc0mmand if you could give this a whirl, to see if it actually fixes your issue, so that we can merge it. thanks!
