### ISSUE TITLE
RFE:  Add  StandardInputPre and StandardInputPost

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#10545]
**Is your feature request related to a problem? Please describe.**
I'm trying to do the following:
```
RuntimeDirectory=minecraft
ExecStartPre=/usr/bin/mkfifo  /run/minecraft/stdin
ExecStart=/usr/bin/minecraft-server
StandardInput=file:/run/minecraft/stdin
```

However  `ExecStartPre` crashes because `StandardInput` points to an Non-existent file  (which `ExecStartPre` is going to create)

**Describe the solution you'd like**
Have a separate
```
StandardInputPre
StandardInput
StandardInputPost
```

So that `ExecStartPre` can setup the `StandardInput` of the service

**Describe alternatives you've considered**
Make a wrapper script around the unit executable ala:
```
bash -c "exec /usr/bin/minecraft-server < /run/minecraft/stdin"
```
But this is a bit less elegant

**Comment by bl33pbl0p** [comment]
I don't think this will work cleanly, if there is more than one `ExecStartPre=,` which one of those are we pointing to with `Standard*Pre=`? Perhaps add something like ? or so which if prefixed for that line makes it use the default stdin/out/err.

**Comment by coretemp** [comment]
This sounds like a horrible idea.

**Comment by arianvp** [comment]
Do you have a better idea how to solve the issue of allocating a FIFO, or Unix domain socket, on demand for services? I'm not saying this is the solution we would want. Another way of attaching something to StandardInput reliably is probably also existent. I just don't know how.   Ideas about that would be appreciated

**Comment by lucaswerkmeister** [comment]
> Do you have a better idea

Use a socket unit? Create `minecraft.socket` with `ListenFIFO=%t/%N/stdin` and `RuntimeDirectory=%N`, and use `StandardInput=socket` in `minecraft.service`. (Usually, sockets units used to start services on demand as soon as the socket is accessed, but you can also start the service as soon as you want to.)

Though I do like this proposal’s potential for a “standard input pretext” option, if you fudge on the capitalization a bit ;)

**Comment by boucman** [comment]
yes most people know that starting a .socket will create the socket, but the service will be start on first access

But it also works the other way round, if you start the service, the socket will be created automatically by systemd first, thus making sure it looks the same to the service

**Comment by arianvp** [comment]
I didn't know about `ListenFIFO`. That seems exactly what I Was looking for. I'm going to close this, as the socket-based activation approach seems like the elegant solution here.
