### ISSUE TITLE
sd-bus: support for signal reception?

### ISSUE THREAD

**Issue by anyc** [systemd/systemd#1054]
Hi, I'm trying to receive signals with sd-bus using `sd_bus_add_match` but the header `bus_message.h` for the required structure `sd_bus_message` is private. Would it be possible to add the required structures to a public header? Thank you!

**Comment by poettering** [comment]
No. The sd_bus_message struct is private, you are supposed to access it only via the `sd_bus_message_xyz()` APIs. The internals are not part of the API and can change any time. The public accessor functions OTH are API stable.
