### ISSUE TITLE
Broken links in systemd.io index.html

### ISSUE THREAD

**Issue by dnicolodi** [systemd/systemd#10546]
The "The systemd Community Conduct Guidelines" and "Contributing" links point to the Markdown files instead that to the rendered HTML. Looking at the generated `index.md` file I have no clue why this is the case. Accessing the `.html` version of the links does not bring up the HTML either. It seems that GitHub is treating `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` files specially.

**Comment by poettering** [comment]
#10495 fixes that, but hasn't been merged yet.

**Comment by dnicolodi** [comment]
Does it? The `index.html` as generated in #10495 uses an explicit`https://systemd.io/CONTRIBUTING` link, but that currently results in a 404 error.

**Comment by poettering** [comment]
hmm, true, two files are not converted to .md yet.

**Comment by dnicolodi** [comment]
I don't think that's the problem: `master/docs/CONTRIBUTING.md` is a .md file and it displays just fine here: https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md

**Comment by poettering** [comment]
hmm, this is so weird. it seems github handles these specially because they are "magic" to it...

**Comment by filbranden** [comment]
Followed up with a better fix on #11317.

Cheers!
Filipe
