### ISSUE TITLE
Assertion 'r < 0' failed at ../systemd-239/src/journal/test-compress.c:235, function test_lz4_decompress_partial(). Aborting.

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#10550]
**systemd version the issue has been seen with**
systemd-239

**Used distribution**
Gentoo

**Summary**
With lz4-1.8.3, `LZ4_decompress_safe_partial` appears to work.

test_lz4_decompress_partial should be adjusted not to expect failure.

**Comment by yuwata** [comment]
Duplicate of #10259.
