### ISSUE TITLE
[systemd-boot] change resolution/refresh rate of the boot loader screen

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#10557]
**Is your feature request related to a problem? Please describe.**
the boot loader screen, console/DM screen, and xorg screen use different resolutions/refresh rates. The caused flickers are little annoying.

**Describe the solution you'd like**
I'm able to adjust the later two screen, but not the boot loader. i would be great if we can set this in loader.conf.

**Describe alternatives you've considered**

**Comment by poettering** [comment]
You can change the resolution since 68d4b8ac9b9673637fa198b735f6e64b78b35d3b

**Comment by enihcam** [comment]
i think the best way to make the screen not flickering is to load edid bin at boot loader, because both kms and xorg consume it. if same edid bin is loaded, the resolution/refresh rate will stay consistent.

https://wiki.archlinux.org/index.php/Kernel_mode_setting#Forcing_modes_and_EDID
https://kodi.wiki/view/Creating_and_using_edid.bin_via_xorg.conf
