### ISSUE TITLE
PrivateUsers=yes fails with systemd --user instance.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#10576]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > PrivateUser=yes being used and the process running in its own user namespace, and then potentially allowing bind mounts and fuse mounts and similar things to work as they usually do, and any other namespaces to be used, but user namespaces alone don't work to begin with, so not tested others.

**Unexpected behaviour you saw**
 > Successfully forked off '(sd-userns)' as PID 15281.
 > Skipping PR_SET_MM, as we don't have privileges.
 > run-u126.service: Failed to set up user namespacing: Operation not permitted

**Steps to reproduce the problem**
systemd-run --user -t -p PrivateUsers=yes /bin/bash

**Comment by poettering** [comment]
yeah, we don't support unprivileged userns right now.

**Comment by anitazha** [comment]
@poettering We're also interested in using `ProtectHome=` with the user bus and this seems related. Is adding unprivileged user namespace support, or another plan to make these options possible for user units being considered?
