### ISSUE TITLE
runtime mask have lower priority than units in /etc/systemd/systemd or ~/.config/systemd/user

### ISSUE THREAD

**Issue by jnpkrn** [systemd/systemd#10583]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Fedora Rawhide

**Expected behaviour you didn't see**
 > ... that `systemctl --user mask <service>` (an possibly `--runtime`)
 > would work as expected

**Unexpected behaviour you saw**
 > `systemctl --user status <service>` now even shows the service
 > is `enabled-runtime`, and can be started freely

**Steps to reproduce the problem**

Complete interaction to demonstrate the unexpected behaviour:

```
$ > ~/.config/systemd/user/loremipsum.service cat <<EOF
[Unit]
Name=loremipsum

[Service]
Type=simple
WorkingDirectory=/tmp
ExecStart=/usr/bin/sleep 100
EOF

$ systemctl daemon-reload  --user

$ systemctl --user status loremipsum
● loremipsum.service
   Loaded: loaded (/home/USER/.config/systemd/user/loremipsum.service; static; vendor preset: enabled)
   Active: inactive (dead)

$ systemctl --user disable loremipsum

$ systemctl --user status loremipsum
● loremipsum.service
   Loaded: loaded (/home/USER/.config/systemd/user/loremipsum.service; static; vendor preset: enabled)
   Active: inactive (dead)

$ systemctl --user mask loremipsum
Failed to mask unit: File /home/USER/.config/systemd/user/loremipsum.service already exists.

$ systemctl --user mask --runtime loremipsum
Created symlink /run/user/1000/systemd/user/loremipsum.service → /dev/null.

$ systemctl --user status loremipsum
● loremipsum.service
   Loaded: loaded (/home/USER/.config/systemd/user/loremipsum.service; enabled-runtime; vendor preset: enabled)
   Active: inactive (dead)

$ systemctl --user start loremipsum; sleep 2; systemctl --user status loremipsum
● loremipsum.service
   Loaded: loaded (/home/USER/.config/systemd/user/loremipsum.service; enabled-runtime; vendor preset: enabled)
   Active: active (running) since Tue 2018-10-30 22:03:38 CET; 2s ago
 Main PID: 8153 (sleep)
   CGroup: /user.slice/user-1000.slice/user@1000.service/loremipsum.service
           └─8153 /usr/bin/sleep 100

Oct 30 22:03:38 HOST sleep[8153]: loremipsum.service: Executing: /usr/bin/sleep 100
```

The most stumbling part is that `--user mask --runtime` actually
made the service marked as `enabled-runtime.
And did nothing to prevent the start.

**Comment by jnpkrn** [comment]
Slightly unrelated but still relevant; apparently I made an error when
quick-coding a sample service file (in `Name=`), and I see that when
I repeat the same with system mode (`/usr/lib/systemd/system/t.service`),
I'll get a respective warning immediately visible with no extra
intersteps:

```
# systemctl status t.service
> ● t.service
>    Loaded: loaded (/usr/lib/systemd/system/t.service; static; vendor preset: disabled)
>    Active: inactive (dead)
> 
> Oct 31 18:13:56 HOST systemd[1]: /usr/lib/systemd/system/t.service:2: Unknown lvalue 'Name' in section 'Unit'
```

(upon subsequent `status` invocations, the last line gets duplicated,
likely implying that repeated reparsing attempts occur)

Only upon closer examination of journal is when I could have noticed
this error in the user service specification.  Just noting as another
behaviour that could be better aligned with standard system counterpart,
unless it would contradict the documentation or anything.

Anyway, this mistake doesn't appear to have any bearing on the core
of this report.

**Comment by keszybz** [comment]
There's some bugs here.

Once we consider a unit enabled, and find a link to /dev/null with lower priority, it is considered as valid, and we report the unit as enabled. That's an obvious bug.

A more fundamental issue is that runtime mask (b) has lower priority than user unit (a), so `mask --runtime` can never work for a unit in the "configuration" directory. I'm not sure what the proper solution is. @poettering opinions?
```console
$ systemd-analyze --user unit-paths
/home/zbyszek/.config/systemd/user.control
/run/user/1000/systemd/user.control
/run/user/1000/systemd/transient
/run/user/1000/systemd/generator.early
/home/zbyszek/.config/systemd/user         <------------- (a)
/etc/systemd/user
/run/user/1000/systemd/user
/run/systemd/user                          <------------- (b)
/run/user/1000/systemd/generator
/home/zbyszek/.local/share/systemd/user
/home/zbyszek/.local/share/flatpak/exports/share/systemd/user
/var/lib/flatpak/exports/share/systemd/user
/usr/local/share/systemd/user
/usr/share/systemd/user
/var/lib/snapd/desktop/systemd/user
/usr/local/lib/systemd/user
/usr/lib/systemd/user
/run/user/1000/systemd/generator.late
$ systemd-analyze unit-paths
/etc/systemd/system.control
/run/systemd/system.control
/run/systemd/transient
/run/systemd/generator.early
/etc/systemd/system                        <------------- (a)
/etc/systemd/system.attached
/run/systemd/system                        <------------- (b)
/run/systemd/system.attached
/run/systemd/generator
/usr/local/lib/systemd/system
/usr/lib/systemd/system
/run/systemd/generator.late
```

Finally, there's a bug that we get confused and remove the unit file itself with `unmask`. Might be somehow caused by the first issue.

**Comment by poettering** [comment]
> A more fundamental issue is that runtime mask (b) has lower priority than user unit (a), so `mask --runtime` can never work for a unit in the "configuration" directory. I'm not sure what the proper solution is. @poettering opinions?

Not allow it? User configuration beats runtime configuration was so far our rule...
