### ISSUE TITLE
ExecStartPre conditional service hook

### ISSUE THREAD

**Issue by stangerm** [systemd/systemd#10596]
**Feature Request**

**Desire:** Be able to define a custom conditional start without considering the service as failed, as ExecStartPre does.

**In Example:** New 'Unit' option named 'ConditionScriptRun' which takes path to executable/script & if it target returns non-zero does not start the service, and the service is NOT considered failed. 

**Reason:** As a BSP engineer I want to be able to (not) start services conditionally such that users aren't concerned by a failed unit. While the 'Condition...=' keywords currently provided are great there are always custom conditions that are just not going to be practical to pre-define thus a custom method is desirable. 'ExecStartPre' is close but non-zero error codes results in services as failed.

I can submit a patch if the feature was desired/approved.

Cheers,

**Comment by boucman** [comment]
I have seen a very common use-case for that :offline bacups.

Test if the backup is reachable and only start the service if it is. If it isn't, just skip the backup and wait for the timer to retrigger...

**Comment by poettering** [comment]
This has been requested before and there's even a TODO list item for it already.

My current thinking is that we should add ExecCondition= or so, which are ExecXYZ= lines run before ExecStartPre=, and that when exit with 0 cause normal start-up of the service, when they exit with 0…254 result in skipping and if exit 255 or die abnormally (i.e. by signal/coredump) will cause the service to enter a failure state.

By moving this closer to ExecXYZ= I think we can model better that these checks actually have a duration, i.e. very different from ConditionXYZ= which have no runtime but are are "instant" checks that take zero time. Of course doing ExecXYZ= means this only naturally fits into .service units, and not units like target units and such which currently have no execution context, i.e. never fork off payload. But I think this is pretty much a good thing.

If you'd like to prep a patch adding ExecCondition= to service units, that'd be very welcome.

**Comment by poettering** [comment]
> I don't really like the idea of a special ExecCondition= for services and nothing equivalent for target units.

Quite frankly, the idea that target units suddenly have a start-up phase, i.e. can be "activating" state, if what you are asking for is implemented makes me very very uncomfortable.

I think I am very sure we should only implement something like this for unit types that have an ExecContext anyway, and maybe initially even just in service units, and nothing else.

Also, I am kind afraid of becoming too much of a hookable script mess this way. I think doing this for services is probably fine, after all the whole point for services is to invoke foreign code. But for the other stuff, such as targets and so on, I am actually now pretty sure that this is really not desirable.

**Comment by poettering** [comment]
> PS: I also think what follows is really needed: About the execution context, I think at some point there needs to be some way to specify exactly what the execution context needs to be for a ExecXYZ= and not just opt-out of service defaults with '-' prefixed, this has come up before in the StandardOutputPre= request and will keep coming up. IDK that kt fits into the INI syntax, but perhaps something like ExecCondition.StandardOutput= to namespace them looks clean enough to me.

Well, I'd really like to keep things simple. if we suddenly need nested data structures to express what we are doing I think we are beyond the line where things become too complex.

Or to say this differently: so far we always said, if you want to more finally tweak the settings for individual ExecXYZ= lines, then the right approach is to have multiple service files. it's similar for socket units: if you want to have different socket settings on sockets you want to pass to some service, then place them in separate .socket units, that's entirely fine.

But anyway, that's a discussion for another place...

**Comment by anitazha** [comment]
Hey @poettering , we discussed during DevConf about implementing ExecCondition= (or something like it) in order to check binaries, host-wide, that are being run by services. I'm looking into implementing this soon and was wondering, for the particular use case FB has, does it make sense to have a special string or something to denote all the binaries on the ExecXYZ= lines to pass to the binary on the ExecCondition= line? Or is there some other way to go about it?

**Comment by poettering** [comment]
@anitazha i figure the process invoked that way could just do the equivalent of `busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/self org.freedesktop.systemd1.Service ExecStart` (and similar for the other props) to get a list of its own ExecXYZ commands, no? What else do you need?
