### ISSUE TITLE
fusedav automount support

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#10599]
I tried to migrate from davfs2 and autofs to a systemd .automount /.mount unit, but couldn't quite figure it out.
I created a `/sbin/mount.fusedav` symlink to `/usr/bin/fusedav` and a `/etc/systemd/system/srv-cloudstore.automount` with

```
[Unit]
Description = TU Cloudstore auto mounting
ConditionPathExists=/srv/cloudstore

[Automount]
Where = /srv/cloudstore
TimeoutIdleSec=30

[Install]
WantedBy = multi-user.target
```

`/etc/systemd/system/srv-cloudstore.mount`:
```
[Unit]
Description = TU Cloudstore mount

[Mount]
What=cloud
Where=/srv/cloudstore
Type=fusedav
```

but how do I give the credentials to fusedav when it needs a `-u username` and `-p password`?
couldn't find a way to give other parameters than `-o` in `systemd/src/mount/mount-tool.c` ...

**Comment by bl33pbl0p** [comment]
Use `Options=` to pass it (and you probably want to look into how it can use a key because units are introspectable easily and any user may be able to read the password - unless you explicitly disallow that).

**Comment by poettering** [comment]
Use The Options= setting, as mentioned.

And generally, support in .mount units is really up to the fuse module to implement properly. If they install "mount.<fstype>" then they should just work the right way also with .mount units. If they instead install their own binaries with incompatible cmdline syntax then this cannot work. But this is really something to fix in those projects, not in systemd.

Anyway, I don#t think there's anything to fix here in systemd. Hence closing.
