### ISSUE TITLE
Fedora CI failing all builds due to lack of filesystem space

### ISSUE THREAD

**Issue by cdown** [systemd/systemd#10592]
Currently failing on all builds with things like:

```
DEBUG: Error: Transaction check error:
DEBUG:   installing package glibc-all-langpacks-2.28.9000-12.fc30.x86_64 needs 14MB on the / filesystem
```

**Comment by evverx** [comment]
I more or less notified the maintainers in https://github.com/systemd/systemd/issues/10489#issuecomment-434732593. [Last time](https://github.com/systemd/systemd/issues/10098) it took 2 days for it to get back to normal. Hopefully, this time it will be a little bit faster.

**Comment by evverx** [comment]
As far as I can tell, Fedora CI has been turned off so I think the issues can be closed.
