### ISSUE TITLE
Trailing backslash in comment is parsed resulting in comment line continuation

### ISSUE THREAD

**Issue by nakato** [systemd/systemd#10598]
**systemd version the issue has been seen with**
> 239
> 237

**Used distribution**
 > 239 - 239.2-1 - Arch Linux
 > 237 - 237-3ubuntu10.3 - Ubuntu Bionic

**Expected behaviour you didn't see**
 > A comment does not effect any non-comment lines after the comment

**Unexpected behaviour you saw**
 > A comment that ends with a trailing backslash results in the following line being counted as a comment.

**Steps to reproduce the problem**

```
[Unit]
Description=Comment continuation test unit

[Service]
Type=simple
# This is comment that ends in a line continuation \
ExecStart=/usr/bin/sleep 900

[Install]
WantedBy=multi-user.target
```

Attempting to start this unit results in

```
Nov 01 09:12:30 hostname systemd[1]: test-unit.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

**Comment by poettering** [comment]
Hmm, is this really a bug? I mean, our documentation doesn#t really clearly say whether `#` or trailing `\` bind more strongly. I am not to convinced that one order would be demandingly better than the other order and for compat reasons this makes me leaning towards considering this merely a docs issue, but not a bug...

**Comment by kuroneko** [comment]
@poettering So let me get this straight - you think it's a good idea to define the behaviour of a comment-to-end-of-line construct in a manner that differs from every other implementation?

Secondly, I believe precedence is established:

"Empty lines and lines starting with "#" or ";" are ignored,..."

If you are parsing the backslash off of that line for a continuation, you are violating the constraints of that definition.

**Comment by mty22** [comment]
Although my comments may not add weight to the discussion, but I do agree with what kuroneko had said (from a logical standpoint):

> "Empty lines and lines starting with "#" or ";" are ignored,..."
> 
> If you are parsing the backslash off of that line for a continuation, you are violating the constraints of that definition.

..and would be more leaning towards the side of this issue, as originally defined, being a bug.. and the documentation should be corrected to be more explicit for those who ..actually read the documentation..

**Comment by yuwata** [comment]
I think the current behavior seems weird. I've proposed #10651.
