### ISSUE TITLE
Documentation on how to properly escape Evironment= values

### ISSUE THREAD

**Issue by raffomania** [systemd/systemd#10604]
Arch Linux, systemd 239

**Is your feature request related to a problem? Please describe.**
I'm trying to include double quotes (`"`) in an environment variable specified via the `Environment=` option in a service file. The only information I have found regarding `Environment=` is [the systemd.exec manpage](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment). But it doesn't specify anything regarding escaping - which leaves me with more questions than I had before. What if I want to use a backslash in an environment variable? Is that safe? How do single quotes relate to this?

**Describe the solution you'd like**
I would like an exact specification of the escaping rules for `Environment=` lines. Which characters have a special function? Which characters are safe?

**Describe alternatives you've considered**
I have searched various forums and mailing lists without finding any answers to this.

**Comment by bl33pbl0p** [comment]
See https://github.com/systemd/systemd/issues/8136 for some hints.

**Comment by raffomania** [comment]
Thanks @bl33pbl0p, but variable substitution is already documented - the problem here is escaping, without any substitution whatsoever.
