### ISSUE TITLE
SAS disks connected to an expander have the same by-path name

### ISSUE THREAD

**Issue by dannf** [systemd/systemd#10601]
**systemd version the issue has been seen with**
> v239 and current master

**Used distribution**
 > Ubuntu 18.04/18.10

**Expected behaviour you didn't see**
 > Unique by-path names for each disk attached to a SAS expander.

**Unexpected behaviour you saw**
 ```
lrwxrwxrwx 1 root root 9 May 30 20:02 pci-0000:74:02.0-sas-exp0x500e004aaaaaaa1f-phy0-lun-0 -> ../../sdb
lrwxrwxrwx 1 root root 10 May 30 20:02 pci-0000:74:02.0-sas-exp0x500e004aaaaaaa1f-phy0-lun-0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 May 30 20:02 pci-0000:74:02.0-sas-exp0x500e004aaaaaaa1f-phy0-lun-0-part2 -> ../../sda2
```
Observe no ../../sda symlink. This is because both sda and sdb are assigned the same ID_PATH:
```
ubuntu@d06-1:~$ udevadm info /dev/sda | grep ID_PATH=
E: ID_PATH=pci-0000:74:02.0-sas-exp0x500e004aaaaaaa1f-phy0-lun-0
ubuntu@d06-1:~$ udevadm info /dev/sdb | grep ID_PATH=
E: ID_PATH=pci-0000:74:02.0-sas-exp0x500e004aaaaaaa1f-phy0-lun-0
```

**Steps to reproduce the problem**
See above

**Comment by yuwata** [comment]
Are there any chance to submit your fix as a PR?

**Comment by dannf** [comment]
At this point we believe the issue is in libsas, not systemd:
  https://marc.info/?l=linux-scsi&m=155016227312186&w=2
