### ISSUE TITLE
Easier execution of several systemd commands in one row?

### ISSUE THREAD

**Issue by tr37ion** [systemd/systemd#10600]
I often have to type one systemctl command after another. Like one 'restart' then 'status' and maybe 'stop'. 

It would be nice to be able to input eg:

    $ systemctl restart,status,stop some.service

instead of 

    $ systemctl restart some.service
    $ systemctl restart some.service
    $ systemctl restart some.service

or

    $ systemctl daemon-reload,status,enable,stop some.service

instead of 

    $ systemctl daemon-reload some.service
    $ systemctl status some.service
    $ systemctl enable some.service
    $ systemctl stop some.service

**Comment by bl33pbl0p** [comment]
Just write a script that iterates over the arguments you pass to it and does it all in one go (using spearators of your choice).

Doing it in systemctl means it would mangle exit codes of each of these operations and something valuable could be missed. Moreover, things become complex when you add things like `edit` into the mix in that if you wanted to reedit the file and accidently closed the editor it would instead go on to do whatever is queued next.

**Comment by poettering** [comment]
I am not convinced we should turn "systemctl" into an imperative scripting language... Shell scripts have been defined for exactly what you are doing, and I see no benefit in doing that in systemctl.

Moreover, the examples you gave don't really make too much sense to me, they are not realistic command lines...

Also, we allow combination of certain operations that make a ton of sense already. For example "systemctl enable" implies "systemctl daemon-reload" already (unless you say --no-reload), and "systemctl enable" understands "--now" to combine it with "systemctl start".

I think it might make sense to add more of the latter kind if their are stron usecases behind them, but I think for stuff that doesn't have such strong usescases and where shell scripts work too, we should just leave things they are.

(I mean, besides that, plenty of systemctl's verbs actually take further arguments — such as systemctl set-property — and how would your proposed syntax even cover that)

The points @bl33pbl0p regarding exit statuses also are good points. 

So, I don't think we should do that, and I hope the explanations above make clear why I don't think. I will close this hence, and I hpoe this makes some sense at least.
