### ISSUE TITLE
60-sensor.hwdb

### ISSUE THREAD

**Issue by imayoda** [systemd/systemd#10636]
I'll leave you a suggestion, as on my Lenovo MIIX310 the search rule in 60-sensor.hwdb won't match 
```
# IdeaPad Miix 310 note this only is for BIOS version (bvr) 1HCN4?WW, which has
# a portrait LCD panel, versions with bvr 1HCN3?WW have a landscape panel
sensor:modalias:acpi:KIOX000A*:dmi:bvnLENOVO:bvr1HCN4?WW:*:svnLENOVO:pn80SG:*
 ACCEL_MOUNT_MATRIX=0, 1, 0; 1, 0, 0; 0, 0, 1
```
as DMI is dmi:bvnLENOVO:bvr1HCN26WW:, and this works ok

Maybe a wider dmi approximation is needed for this 2in1 lenovo series :)

**Comment by poettering** [comment]
@imayoda please provide the suggested addition/change as a proper PR, thank you! Then, we can easily merge this, properly attribute it to you.

/cc @hadess

**Comment by hadess** [comment]
Closing as #10661 got merged.
