### ISSUE TITLE
[networkd] Support for additional bridge link properties

### ISSUE THREAD

**Issue by chr0mag** [systemd/systemd#10649]
**systemd 239 on Arch**
I'm running a bridge that includes 2 wireless/hostapd links. I'm currently enabling *hairpin_mode* for these wireless links as shown below and would like to be able to set *multicast_to_unicast* on each of these bridge ports in the same way.

```
[Match]
Name=wifi*

[Network]
Bridge=br0

[Bridge]
HairPin=true
```
While my specific use case is for *multicast_to_unicast* support, there are additional bridge port properties available that can't currently be set via networkd.

My solution at the moment is just to write directly to the sysfs property when the bridge link appears using a separate systemd path/service.

**Comment by ssahani** [comment]
yes there are bunch of them. Please add all  for your use case. thanks.

**Comment by chr0mag** [comment]
I actually only require _multicast_to_unicast_ for my use case so that's enough to satisfy this RFE for me. 

I mentioned the other properties only with the thought they could get added at the same time, but understand its almost certainly not that simple.

**Comment by ssahani** [comment]
@chr0mag my kernel is not configured with ``` CONFIG_BRIDGE_IGMP_SNOOPING ```.  Could you please test with https://github.com/systemd/systemd/pull/10988

**Comment by chr0mag** [comment]
Sure. After building systemd + #10988 locally on my machine, here are my verification steps:
_zgrep -i igmp /proc/config.gz_
`CONFIG_BRIDGE_IGMP_SNOOPING=y`

_ls -l /etc/systemd/network_ 
```
total 16
-rw-r--r-- 1 root root 34 Nov 29 18:58 1-testbr0.netdev
-rw-r--r-- 1 root root 41 Nov 29 19:25 1-testbr0.network
-rw-r--r-- 1 root root 90 Nov 29 19:09 1-testbr0-slaves.network
-rw-r--r-- 1 root root 40 Nov  4 17:35 10-wired.network.bak
```
_cat /etc/systemd/network/1-testbr0.netdev_
```
[NetDev]
Name=testbr0
Kind=bridge
```

_cat /etc/systemd/network/1-testbr0-slaves.network_
```
[Match]
Name=en*

[Network]
Bridge=testbr0

[Bridge]
HairPin=true
MulticastToUnicast=true
```
_cat /etc/systemd/network/1-testbr0.network_
```
[Match]
Name=testbr0

[Network]
DHCP=yes
```

Status after reboot:
_ip address_
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
	link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
	inet 127.0.0.1/8 scope host lo
	   valid_lft forever preferred_lft forever
	inet6 ::1/128 scope host 
	   valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master testbr0 state UP group default qlen 1000
	link/ether 52:54:00:3b:e2:05 brd ff:ff:ff:ff:ff:ff
	inet6 fe80::5054:ff:fe3b:e205/64 scope link 
	   valid_lft forever preferred_lft forever
3: testbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
	link/ether b2:d1:b7:71:43:e4 brd ff:ff:ff:ff:ff:ff
	inet 192.168.4.216/24 brd 192.168.4.255 scope global dynamic testbr0
	   valid_lft 3067sec preferred_lft 3067sec
	inet6 fd60:fac9:adf9:11cc:b0d1:b7ff:fe71:43e4/64 scope global dynamic mngtmpaddr noprefixroute 
	   valid_lft 3527sec preferred_lft 3527sec
	inet6 fe80::b0d1:b7ff:fe71:43e4/64 scope link 
	   valid_lft forever preferred_lft forever

```
_cat /sys/devices/virtual/net/testbr0/lower_enp1s0/brport/hairpin_mode_
`1`
_cat /sys/devices/virtual/net/testbr0/lower_enp1s0/brport/multicast_to_unicast_
`0`

_systemctl stop systemd-networkd.service_
_sudo build/systemd-networkd &_
```
testbr0: Gained IPv6LL
enp1s0: Gained IPv6LL
Enumeration completed
testbr0: netdev exists, using existing without changing its parameters
testbr0: DHCPv4 address 192.168.4.216/24 via 192.168.4.1
enp1s0: Configured
testbr0: Configured
```

_cat /sys/devices/virtual/net/testbr0/lower_enp1s0/brport/hairpin_mode_
`1`
_cat /sys/devices/virtual/net/testbr0/lower_enp1s0/brport/multicast_to_unicast_
`1`

Looks good to me. Let me know if there is anything else you'd like me to verify.
