### ISSUE TITLE
[networkd] Ability to selectively ignore IPv6 prefixes supplied via router advertisement

### ISSUE THREAD

**Issue by chrsmrtnx** [systemd/systemd#10647]
**Is your feature request related to a problem? Please describe.**

On networks where multiple prefixes are supplied via router advertisements, it can be difficult to keep control of the addresses assigned to your hosts. For instance, when I manually assign a ULA to a host, but on the network that prefix is also advertised via RA (for the benefit of Android devices, let's say), then my host will wind up with: (1) the assigned ULA; (2) an address formed from the ULA prefix plus the EUI-64 interface ID; and (3) a privacy address formed from the ULA prefix - when the only one I actually want is the manually assigned ULA. Aside from being a mess, this creates problems in situations where the exact source address matters. And yes, I need to accept RAs in order to obtain the global prefixes that change periodically from my provider.

**Describe the solution you'd like**

An option to ignore specific prefixes from RAs, or classes of prefixes (such as 'global' or 'ULA') would allow more precise control over IPv6 networking in general. A further option could accept the prefix/prefix class in question, but not generate privacy addresses.

**Comment by kpfleming** [comment]
What you're asking for is to disable SLAAC, not to ignore prefixes received in RAs. This is already being discussed in other issues, including #969.

**Comment by chrsmrtnx** [comment]
Not exactly the same as #969. What I requested was a more fine-grained ability to control which prefixes (obtained via RA) are actually processed and used. I don't want to disable SLAAC entirely.

**Comment by kpfleming** [comment]
Fair point; unfortunately SLAAC is processed in the kernel, not in systemd, and the kernel doesn't offer this type of control at this point.

**Comment by yuwata** [comment]
Does #11716 help this issue/RFE? @ssahani What do you think about?

**Comment by ssahani** [comment]
This issue about selecting one or more prefixes  from multiple  prefixes . So It does not look like that fixes it.

**Comment by yuwata** [comment]
Please test #12603 if possible. Thank you.
