### ISSUE TITLE
How to build systemd-nspawn? 

### ISSUE THREAD

**Issue by liugenping** [systemd/systemd#1065]
I can't find some description in readme for build the systemd-nspawn or whole systemd.

**Comment by martinpitt** [comment]
systemd follows a fairly standard autotools workflow: `./autogen.sh`, `./configure [options]`, `make`, `make install`. However, please do note that just using it like this without the proper configure options will most likely completely break your system.

Judging by your question you aren't very familiar with building software for linux, so I strongly recommend to not begin with something like systemd which is very intrusive and easy to get wrong. Use the packages provided by your distribution instead.

**Comment by liugenping** [comment]
@martinpitt 
Sorry, Maybe I didn't give the enough error info. 
I run "systemd-nspawn -D ./debian-tree/" on ubuntu 14.04, but get error:
root@zenlin-HP-Compaq-8100-Elite-CMT-PC:~# systemd-nspawn -D ./debian-tree/
Spawning container debian-tree on /root/debian-tree.
Press ^] three times within 1s to kill container.
/etc/localtime is not a symlink, not updating container timezone.
Failed to retrieve machine ID: No such file or directory
And the machine ID is here:
root@zenlin-HP-Compaq-8100-Elite-CMT-PC:~# more ./debian-tree/etc/machine-id 
8aed435e5bf84716b28ca21320478656

So, I want to debug and find why is wrong,  
when I run ./autogen.sh give the follow error, it seem to need libgcrypt lib, but I don't why the 
liugenping@zenlin-HP-Compaq-8100-Elite-CMT-PC:~/gopath/src/github.com/systemd/systemd$ ./autogen.sh
configure.ac:686: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: linking file`build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
configure.ac:686: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
configure.ac:49: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:686: error: possibly undefined macro: AM_PATH_LIBGCRYPT
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by martinpitt** [comment]
@liugenping : systemd and hence nspawn are not supported yet in Ubuntu 14.04. Use Ubuntu 15.04 (or later) for that. On Ubuntu (including 14.04) the primary and supported container technology is LXC.

**Comment by poettering** [comment]
systemd (and its component systemd-nspawn) are not an app you can install on top of a distro. Instead, it needs to be adopted by the distro itself, and that's a non-trivial amount of work for distro developers. Hence, please use an Ubuntu version that incldudes systemd, it's not really practical to move an old one to systemd without support from Ubuntu upstream. Sorry.

**Comment by liugenping** [comment]
@poettering @martinpitt   Thx, I'm upgrading Ubuntu to 15.4.
