### ISSUE TITLE
systemd-rc-local-generator: Please document why a unit with ConditionFileIsExecutable doesn't suffice

### ISSUE THREAD

**Issue by joshtriplett** [systemd/systemd#10675]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian

Please consider documenting, in the manpage for systemd-rc-local-generator why a unit with `ConditionFileIsExecutable=/etc/rc.local` does not suffice instead of a generator. I've seen this question come up more than once.

**Comment by mbiebl** [comment]
@joshtriplett https://github.com/systemd/systemd/pull/268 is related

**Comment by poettering** [comment]
Fix waiting in #10815
