### ISSUE TITLE
udev assigns the same ID_PATH for different usb devices

### ISSUE THREAD

**Issue by ShikChen** [systemd/systemd#10683]
**systemd version the issue has been seen with**
> 239

**Expected behaviour you didn't see**
 > The USB bus number in included in `ID_PATH` correctly.

**Unexpected behaviour you saw**
 > `usb-0` is hard coded in `ID_PATH` in it.

**Steps to reproduce the problem**

```
# /dev/video0 is a USB camera
$ udevadm info --query=all /dev/video0
P: /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/video4linux/video0
...
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/video4linux/video0
...
E: ID_PATH=pci-0000:00:14.0-usb-0:9:1.0
```

The device at `1-9:1.0` is encoded as `usb-0:9:1.0` in its `ID_PATH`, so there is a collision if we have both `1-9:1.0` and `2-9:1.0` at the same time. I found this potential issue when trying to utilize https://github.com/systemd/systemd/blob/0ccc48b5b8319ece4d8b87d8d9e0816df3991099/rules/60-persistent-v4l.rules#L17 to access the camera with persistent symbolic links.

Why we strip the part before `'-'` in https://github.com/systemd/systemd/blob/f402ce827daf8556dc5ec058889c031a9dfd55a5/src/udev/udev-builtin-path_id.c#L480-L486 and hard code `usb-0` instead?

**Comment by arvidjaar** [comment]
You need to provide actual example of duplicate **full** names (not just USB part of it). Part that is stripped is controller number which is result of run-time enumeration and is not persistent across reboot; but full `ID_PATH` includes parent (e.g. PCI) which makes it unique.

**Comment by ShikChen** [comment]
Here is an example of duplicate `ID_PATH`, including the PCI part:

```
$ udevadm info -q all /dev/video15
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.2/1-2.2:1.0/video4linux/video15
...
E: ID_PATH=pci-0000:00:14.0-usb-0:2.2:1.0

$ udevadm info -q all /sys/class/net/eth0
P: /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2.2/2-2.2:1.0/net/eth0
...
E: ID_PATH=pci-0000:00:14.0-usb-0:2.2:1.0
```

**Comment by arvidjaar** [comment]
Can you provide output of `lspci -nnv` and full `ls -lR /sys`?

**Comment by ShikChen** [comment]
Sorry I don't have the devices on my hand now to reproduce the scenario I posted above. I borrowed some USB adapters and random shuffled things on it to make the exact collision. Is the data still needed? It looks like that we already knew the causes.

**Comment by arvidjaar** [comment]
> It looks like that we already knew the causes.

We know one possible cause; we do not know whether your case is the same.

Anyway, it is not a bug. `ID_PATH` is supposed to encode topological connection path to device (i.e. - it is supposed to be unique and hopefully persistent for each USB port on your device). While xHCI has two logical USB hubs (and buses), both share the same underlying hardware and so have the same topology. So it is entirely correct that `ID_PATH` is the same for USB 2.0 and USB 3.0 devices because both share the same physical USB port, and port numbers of both logical hubs match.

```
lrwxrwxrwx 1 root root 0 ноя 10 09:26 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-0:1.0/usb3-port1/peer -> ../../../usb2/2-0:1.0/usb2-port1/
lrwxrwxrwx 1 root root 0 ноя 10 09:26 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-0:1.0/usb3-port2/peer -> ../../../usb2/2-0:1.0/usb2-port2/
lrwxrwxrwx 1 root root 0 ноя 10 09:26 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-0:1.0/usb3-port3/peer -> ../../../usb2/2-0:1.0/usb2-port3/
lrwxrwxrwx 1 root root 0 ноя 10 09:26 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-0:1.0/usb3-port4/peer -> ../../../usb2/2-0:1.0/usb2-port4/
```

Unless you can demonstrate that two devices connected to two different USB ports simultaneously get same `ID_PATH` (or that USB 2.0 and USB 3.0 devices on the same physical port get different `ID_PATH`), there is nothing to fix.

**Comment by ShikChen** [comment]
I think the collision above satisfy the condition you said:
> two devices connected to two different USB ports simultaneously get same ID_PATH

IIRC, it's constructed by connecting some devices simultaneous (power/webcam/ethernet) on USB adapters (C to A/A to A) on a laptop. I randomly shuffled devices into different ports to see if there is a collision. The `ID_PATH` collision is happened between

* ethernet <=> USB-C adapter <=> USB-C port
* webcam <=> USB-A hub <=> USB-A port

Not sure if this information is enough for you to identify whether the cause is the same.

**Comment by arvidjaar** [comment]
> Not sure if this information is enough for you to identify whether the cause is the same.

It is not. For a start, this is the first time you mentioned USB-C. If you claim devices were connected to different ports, please provide

```
lspci -nnv
lsusb -v
udevadm info --export-db
ls -lR /sys
```

with both devices connected simultaneously. Also information about your hardware would be helpful. Until this information is available there is not much that can be done.

**Comment by poettering** [comment]
Closing due to lack of response.
