### ISSUE TITLE
hwdb: Double airplane mode key events on Dell laptops

### ISSUE THREAD

**Issue by seb128** [systemd/systemd#10704]
The issue happens on Ubuntu 18.10 and FC29 , systemd 239, the system is an inspiron 3138

Using the 'airplane' key under GNOME is reliable, the mode is often flickering or not changed.

Look to evemu-record the KEY_WLAN events are duplicated
(the system lists a keyboard input device and a "DELL Wireless hotkeys" one so it could be that each one is generating an event)

Editing hwdb 60-keyboard to include

"#disable double airplane key events on Inspiron 3138
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnDell*:pnInspiron*3138:pvr*
 KEYBOARD_KEY_88=unknown"

Fixes the issue here, I'm going to submit a PR with those changes

(note that we got similar report from XPS13 users which probably need similar changes)

**Comment by martinpitt** [comment]
So this confirms my suspicion from PR #8762 unfortunately. So I think it's best to revert that, and limit the explicit wlan key setting to specific models instead, as before.

**Comment by poettering** [comment]
I figure we can close this now that #10709 has been merged.
