### ISSUE TITLE
systemd dbus interface GetProperty "ExecStart" is empty

### ISSUE THREAD

**Issue by remueller** [systemd/systemd#10700]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Ubuntu 18.10

**Expected behaviour you didn't see**
 > 1. execute dbus call to get all members of a service
 > 2. Property "ExecStart" of a service should have valid information

**Unexpected behaviour you saw**
 > **This failure only occurs only sometimes.**
  > 1. execute dbus call to get all members of a service
  > 2. Property "ExecStart" of the service shows only 0 (see [dbus-monitor.txt](https://github.com/systemd/systemd/files/2565412/dbus-monitor.txt))
 > DICT_ENTRY "sv" {
                          STRING "ExecStart";
                          VARIANT "a(sasbttttuii)" {
                                  ARRAY "(sasbttttuii)" {
                                          STRUCT "sasbttttuii" {
                                                  STRING "/usr/sbin/ModemManager";
                                                  ARRAY "s" {
                                                          STRING "/usr/sbin/ModemManager";
                                                  };
                                                  BOOLEAN false;
                                                  UINT64 0;
                                                  UINT64 0;
                                                  UINT64 0;
                                                  UINT64 0;
                                                  UINT32 0;
                                                  INT32 0;
                                                  INT32 0;
                                          };
                                  };
                          };
                  };

**Steps to reproduce the problem**

**Comment by poettering** [comment]
This almost definitely is a result of the service being garbage collected after it exited. 

systemd generally will garbage collect all services that have exited cleanly and that have no dependency on them in place. Garbage collection means that systemd unloads the unit from memory, and that also means it forgets about runtime data it collected, such as precise exit codes and stuff.

note that a good chunk of that info is written to the journal though and not lost.

Clients can also "pin" a unit into memory (RefUnit on the dbus Manager interface) . if they do, then the units will not be unloaded (and thus all runtime data they entail is kept), as long as the client doesn't unpin them again and doesn't disconnect. There's currently no nice utility to invoke this from the command line however...

hence, what you are seeing is pretty much expected. Closing hence.
