### ISSUE TITLE
systemd-udevd[3569]: Process 'net.sh wwan0 start' failed with exit code 1.

### ISSUE THREAD

**Issue by mmokrejs** [systemd/systemd#1070]
I just upgraded on my Gentoo Linux from sys-fs/udev-219 to sys-fs/udev-224-r2 and I started to see complains that wwan0 does not start. Of course, because it was just renamed to wwp0s29u1u2i1.

<pre>
[   38.555093] usb 4-1.2: new high-speed USB device number 4 using ehci-pci
[   38.667252] usb 4-1.2: New USB device found, idVendor=12d1, idProduct=15ca
[   38.667266] usb 4-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   38.667272] usb 4-1.2: Product: HUAWEI Mobile
[   38.667278] usb 4-1.2: Manufacturer: HUAWEI
[   38.667283] usb 4-1.2: SerialNumber: FFFFFFFFFFFFFFFF
[   38.712629] usb-storage 4-1.2:1.0: USB Mass Storage device detected
[   38.713026] scsi host7: usb-storage 4-1.2:1.0
[   39.720655] scsi 7:0:0:0: CD-ROM            HUAWEI   Mass Storage     2.31 PQ: 0 ANSI: 2
[   39.722566] sr 7:0:0:0: [sr1] scsi-1 drive
[   39.723223] sr 7:0:0:0: Attached scsi CD-ROM sr1
[   39.723516] sr 7:0:0:0: Attached scsi generic sg3 type 5
[   39.724821] scsi 7:0:0:1: Direct-Access     HUAWEI   TF CARD Storage  2.31 PQ: 0 ANSI: 2
[   39.725491] sd 7:0:0:1: Attached scsi generic sg4 type 0
[   39.728184] sd 7:0:0:1: [sdc] Attached SCSI removable disk
[   40.881563] usb 4-1.2: USB disconnect, device number 4
[   41.889234] usb 4-1.2: new high-speed USB device number 5 using ehci-pci
[   42.001527] usb 4-1.2: New USB device found, idVendor=12d1, idProduct=1506
[   42.001540] usb 4-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   42.001547] usb 4-1.2: Product: HUAWEI Mobile
[   42.001552] usb 4-1.2: Manufacturer: HUAWEI
[   42.338172] usb-storage 4-1.2:1.4: USB Mass Storage device detected
[   42.338428] scsi host8: usb-storage 4-1.2:1.4
[   42.338996] usb-storage 4-1.2:1.5: USB Mass Storage device detected
[   42.339223] scsi host9: usb-storage 4-1.2:1.5
[   43.345076] scsi 8:0:0:0: CD-ROM            HUAWEI   Mass Storage     2.31 PQ: 0 ANSI: 2
[   43.345724] scsi 9:0:0:0: Direct-Access     HUAWEI   TF CARD Storage  2.31 PQ: 0 ANSI: 2
[   43.346507] sd 9:0:0:0: Attached scsi generic sg3 type 0
[   43.347863] sr 8:0:0:0: [sr1] scsi-1 drive
[   43.348639] sr 8:0:0:0: Attached scsi CD-ROM sr1
[   43.348709] sd 9:0:0:0: [sdc] Attached SCSI removable disk
[   43.348917] sr 8:0:0:0: Attached scsi generic sg4 type 5
[   44.628540] sr 8:0:0:0: [sr1]  
[   44.628546] Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[   44.628548] sr 8:0:0:0: [sr1]  
[   44.628549] Sense Key : Medium Error [current] 
[   44.628551] Info fld=0xfffe
[   44.628552] sr 8:0:0:0: [sr1]  
[   44.628554] Add. Sense: Unrecovered read error
[   44.628555] sr 8:0:0:0: [sr1] CDB: 
[   44.628556] Read(10): 28 00 00 00 ff fe 00 00 02 00
[   44.628604] blk_update_request: critical medium error, dev sr1, sector 262136
[   44.634996] sr 8:0:0:0: [sr1]  
[   44.634998] Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[   44.634999] sr 8:0:0:0: [sr1]  
[   44.634999] Sense Key : Medium Error [current] 
[   44.635001] Info fld=0xfffe
[   44.635002] sr 8:0:0:0: [sr1]  
[   44.635003] Add. Sense: Unrecovered read error
[   44.635004] sr 8:0:0:0: [sr1] CDB: 
[   44.635005] Read(10): 28 00 00 00 ff fe 00 00 02 00
[   44.635010] blk_update_request: critical medium error, dev sr1, sector 262136
[   44.635024] Buffer I/O error on dev sr1, logical block 32767, async page read
[   44.700122] sr 8:0:0:0: [sr1]  
...
[   45.206898] usbcore: registered new interface driver option
[   45.207218] usbserial: USB Serial support registered for GSM modem (1-port)
[   45.207326] option 4-1.2:1.0: GSM modem (1-port) converter detected
[   45.208067] usb 4-1.2: GSM modem (1-port) converter now attached to ttyUSB0
[   45.208201] option 4-1.2:1.2: GSM modem (1-port) converter detected
[   45.208475] usb 4-1.2: GSM modem (1-port) converter now attached to ttyUSB1
[   45.208512] option 4-1.2:1.3: GSM modem (1-port) converter detected
[   45.208760] usb 4-1.2: GSM modem (1-port) converter now attached to ttyUSB2
[   45.418312] usbcore: registered new interface driver cdc_ncm
[   45.464538] huawei_cdc_ncm 4-1.2:1.1: MAC-Address: 82:a9:4a:09:84:2e
[   45.487038] huawei_cdc_ncm 4-1.2:1.1: cdc-wdm0: USB WDM device
[   45.487646] huawei_cdc_ncm 4-1.2:1.1 wwan0: register 'huawei_cdc_ncm' at usb-0000:00:1d.0-1.2, Huawei CDC NCM device, 82:a9:4a:09:84:2e
[   45.487721] usbcore: registered new interface driver huawei_cdc_ncm
[   45.533169] huawei_cdc_ncm 4-1.2:1.1 wwp0s29u1u2i1: renamed from wwan0
[   45.556728] systemd-udevd[3569]: Process 'net.sh wwan0 start' failed with exit code 1.
</pre>

**Comment by floppym** [comment]
Why are you reporting this here? It is almost certainly a Gentoo bug.

**Comment by teg** [comment]
As @floppym pointed out this seems unlikely to be a systemd bug. It may be worth noting though that we now log this warning at a higher level than we used to, so the regression may not be new (something is likely wrong though). I'll close, but please reopen if this turns out to be systemd related after all.

**Comment by floppym** [comment]
Gentoo bug report, for reference.

https://bugs.gentoo.org/show_bug.cgi?id=554510

**Comment by mmokrejs** [comment]
Thank you, I tried to lookup the error message at Gentoo but forced search to udev, did not know netifrc is the culprit. Anyway, the line says systemd-udevd and per wikipedia udevd got merged into systemd, so that is why I came here. @floppym: should I file a new bug report at Gentoo or hijack the 554510 bug or ... ;-) Thank you.

**Comment by floppym** [comment]
@mmokrejs Just CC yourself on the bug. We do not require any additional information; someone just needs to fix it.
