### ISSUE TITLE
RFE: please provide a way to start user systemd sessions pn boot

### ISSUE THREAD

**Issue by nim-nim** [systemd/systemd#10705]
**Is your feature request related to a problem? Please describe.**
I want fetchmail to be periodically started by a systemd timer in my user sessions on my home server, to collect my mail in my user environment.
Unfortunately, the timer does not engage automatically on boot, I have to remember login in manually  just to kick it every time the server reboots

**Describe the solution you'd like**
Some conf parameter that tells the system systemd to start user systemd timers on boot (optionally, with user or group whitelists/blacklists if you prefer)

**Describe alternatives you've considered**
Various hacks to try to kick the user systemd session on boot float on the internet. They all suck and provide no assurance they will keep working with new systemd versions.

**Comment by poettering** [comment]
That already exists. Use "loginctl enable-linger <youruser>" to enable it for any user you like.

**Comment by nim-nim** [comment]
Thanks, I had missed this somehow
