### ISSUE TITLE
nspawn containers with too long names conflict regarding veth name if `--network-veth` is used

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#10721]
**systemd version the issue has been seen with**
> all up to v239

If you start
```
$ systemd-nspawn -M helloabcdef1 --private-network
```
allocates a `veth` named `ve-helloabcdef`

Then if you do

```
$ systemd-nspawn -M helloabcdef2 --private-network
```

it fails with:
```
Nov 10 11:47:50 t430s container helloabcdef2[5146]: Spawning container helloabcdef2 on /var/lib/containers/helloabcdef2.
Nov 10 11:47:50 t430s container helloabcdef2[5146]: Press ^] three times within 1s to kill container.
Nov 10 11:47:50 t430s container helloabcdef2[5146]: /etc/localtime does not point into /usr/share/zoneinfo/, not updating container timezone.
Nov 10 11:47:50 t430s container helloabcdef2[5146]: Failed to add new veth interfaces (ve-helloabcdef:host0): File exists
Nov 10 11:47:50 t430s container helloabcdef2[5146]: Parent died too early
```

**Possible Fix**
Perhaps we should document somewhere that containers names can **not be longer than 11 characters**? 

~~Why are the veth names truncated anyway? Is there a good reason for it?~~
Edit: There seems to be a limitation on how long interface names can be.

**Other possible fixes**
* Docker derives the `veth` pair name from the container _id_ instead of the container _name_ and keeps
a mapping from name to id out of band. perhaps we can do the same for nspawn?
* Make the Veth pair name `truncate(sha256(name),11)`

**Comment by poettering** [comment]
> * Docker derives the `veth` pair name from the container _id_ instead of the container _name_ and keeps
>   a mapping from name to id out of band. perhaps we can do the same for nspawn?
> 
> * Make the Veth pair name `truncate(sha256(name),11)`

Well, that certainly doesn't make things more discoverable…

**Comment by poettering** [comment]
I figure you mean --network-veth btw, right? Not just "--private-network"...

**Comment by poettering** [comment]
To me this sounds like something to document and be done with it. And users should use `--network-veth-extra=` instead, if the automatic naming doesn't work for them if the names get too long

**Comment by arianvp** [comment]
> I figure you mean --network-veth btw, right? Not just "--private-network"...

Yes, definitely.

> To me this sounds like something to document and be done with it. And users should use --network-veth-extra= instead, if the automatic naming doesn't work for them if the names get too long

Documenting this sounds like a good solution to me

**Comment by poettering** [comment]
docfix pending in #11989.
