### ISSUE TITLE
sd-dhcp6-client does not unregister timeout_t2 causing spurious event notifications

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#10749]
This can be seen with NetworkManager master and the issue also exists in systemd master at this point.

See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/73 for this causing trouble in NetworkManager.

The core of the issue is that `client_start` with `DHCP6_STATE_BOUND` will always register the `timeout_t2` event. However, this event is only cleaned up in `client_reset` which may not be called in all code paths. To be exact, I imagine that a T1 timeout will result in the state to go into `DHCP6_STATE_REBIND` and then back to `DHCP6_STATE_BOUND` without ever calling `client_reset`.

The easy fix is probably to just make sure the timeouts are all unref'ed at the start of `client_start`. However, I am not familiar with the code, so am not sure whether that is correct.

**Comment by yuwata** [comment]
@benzea I hope that this issue is fixed by #10751. If possible, could you test the PR?

**Comment by benzea** [comment]
@yuwata, oh, nice that was quick and thorough!

Sure, I can look into updating my network manager and test. That will take at least two days though (I reproduce it by suspending my laptop overnight).

**Comment by benzea** [comment]
So far I did not reproduce any issues. But, I am not sure if this happened every day.

**Comment by yuwata** [comment]
@benzea Thank you!

**Comment by benzea** [comment]
OK, one more day of testing, and it is looking good. So, I feel confident the issue has been addressed.
