### ISSUE TITLE
systemd-resolved: "strict" resolution for DNSOverTLS?

### ISSUE THREAD

**Issue by fgont** [systemd/systemd#10755]
It seems systemd-resolved currently only supports "opportunistic" DNSOverTLS resolution. From a privacy point of view, if I enable DNSOverTLS I'd most likely expect it to work over TLS, or fail (otherwise one would be subject to downgrade attacks).

Is there any plan to support "strict" mode, other than "opportunistic"?

Thanks,
Fernando

**Comment by rsclarke** [comment]
Related issue, RFE: Certificate checking for Resolveds DNS over TLS feature #9397
