### ISSUE TITLE
udev: some devices are not initialized

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#10754]
With current git master cc9cc1b12648a31c82d7c6acfb16391c5af6150d, some devices are not initialized by udev. Booting with `udev.children_max=1` works as expected.

**Comment by yuwata** [comment]
```
$ SYSTEMD_LOG_LEVEL=debug ./test-sd-device &> log
$ sudo udevadm trigger --type=devices --action=add
$ SYSTEMD_LOG_LEVEL=debug ./test-sd-device &> log-after-trigger
$ diff log log-after-trigger | grep '>' | grep 'initialized:yes' | sed -e 's/^> //'
subsystem:input syspath:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input11 initialized:yes
subsystem:input syspath:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input11/event9 initialized:yes
subsystem:drm syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/card0 initialized:yes
subsystem:drm syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1 initialized:yes
subsystem:drm_dp_aux_dev syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1/drm_dp_aux0 initialized:yes
subsystem:drm syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1 initialized:yes
subsystem:drm syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-2 initialized:yes
subsystem:drm syspath:/sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/hwC0D0 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input12 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input12/event10 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input13 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input13/event11 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input14 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input14/event12 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input15 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input15/event13 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input16 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/input16/event14 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/pcmC0D10p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/pcmC0D3p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/pcmC0D7p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/pcmC0D8p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/pcmC0D9p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:03.0/sound/card0/controlC0 initialized:yes
subsystem:bluetooth syspath:/sys/devices/pci0000:00/0000:00:14.0/usb2/2-7/2-7:1.0/bluetooth/hci0 initialized:yes
subsystem:rfkill syspath:/sys/devices/pci0000:00/0000:00:14.0/usb2/2-7/2-7:1.0/bluetooth/hci0/rfkill0 initialized:yes
subsystem:mei syspath:/sys/devices/pci0000:00/0000:00:16.0/mei/mei0 initialized:yes
subsystem:net syspath:/sys/devices/pci0000:00/0000:00:19.0/net/enp0s25 initialized:yes
subsystem:ptp syspath:/sys/devices/pci0000:00/0000:00:19.0/ptp/ptp0 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/hwC1D0 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/input10 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/input10/event8 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/input9 initialized:yes
subsystem:input syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/input9/event7 initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/pcmC1D0c initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/pcmC1D0p initialized:yes
subsystem:sound syspath:/sys/devices/pci0000:00/0000:00:1b.0/sound/card1/controlC1 initialized:yes
subsystem:rfkill syspath:/sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0/ieee80211/phy0/rfkill1 initialized:yes
subsystem:net syspath:/sys/devices/pci0000:00/0000:00:1c.3/0000:02:00.0/net/wlp2s0 initialized:yes
```

**Comment by yuwata** [comment]
I may need to bisect between dcfbde3a43d632ff6e286c77e1081087eca59d8e..8ecbc4b880b91e997babc924fccb7cbebb8b0943.

**Comment by yuwata** [comment]
Hmm, recent Ubuntu bionic-arm64 failures may be related to this. E.g. https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/arm64/s/systemd-upstream/20181117_101019_169d6@/log.gz

**Comment by yuwata** [comment]
Below are workarounds.
- set `--children-max=1` or relevant kernel command line option.
- If you can login the system, then run `udevadm trigger --type=devices --action=add` or `--type=subsystems`.

**Comment by yuwata** [comment]
If some one hit by this issue, please give us debug logs of `udevd`.

**Comment by yuwata** [comment]
Hmm, I am not sure yet... Please try with the default parameter as the first step.

**Comment by yuwata** [comment]
If I remember correctly (now I cannot touch the machine which is affected by this. Fortunately(?), my laptop works fine.), I observed the following when this issue occurs:
1. `udevd` receives an uevent for `/sys/devices/pci0000:00/0000:00:19.0`, which is a NIC, as expected.
2. I have not measured the duration time, but initialization `/sys/devices/pci0000:00/0000:00:19.0` seems to take slightly longer than the case that everything is fine. But no error is shown.
3. kernel log shows that driver is loaded and eth0 is created.
4. But no uevent received for `/sys/bus/pci/drivers/e1000e`, `/sys/devices/pci0000:00/0000:00:16.0/mei/mei0`, `/sys/devices/pci0000:00/0000:00:19.0/net/eth0` nor `/sys/devices/pci0000:00/0000:00:19.0/net/ptp0`. Note that now `sd-device-monitor` shows all received uevents in the debug log. But these devices are not shown in the udev logs.
5. After system boot, I can find these syspath exists, but `test-sd-device` shows these are not initialized.
6. Run `udevadm trigger` to regenerate 'add' or 'change' uevent, then `udev` processes these devices, and everything works fine, fortunately...

So, my current conclusion about this issue is that we may need to initialize some devices or subsystems before loading some (all?) drivers. But I do not know what syspaths are important.

Or, is it a kernel bug? I am not familiar with the kernel source code. Where is the most core part to publish uevents? Please suggest the relevant codes. Thank you.

**Comment by mbiebl** [comment]
@yuwata looks like I'm not able to produce a useful journal log.
I've booted with ```udev_log=debug```, but the journal just stops after flushing to /var.
[journal.txt](https://github.com/systemd/systemd/files/2605083/journal.txt)

**Comment by mbiebl** [comment]
@yuwata so, this was rather painful to bisect on real hardware.

The first faulty commit is c4b69e990f962128cc6975e36e91e9ad838fa2c4
```
commit c4b69e990f962128cc6975e36e91e9ad838fa2c4
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Thu Oct 25 17:41:17 2018 +0900

    udev: drop redundant initializations for file descriptors
    
    As udev_ctrl_new_from_fd() or udev_monitor_new_from_netlink_fd()
    creates fd if negative fd is passed.
```

**Comment by mbiebl** [comment]
This was merged on 2018-11-12, so roughly ten days ago.

**Comment by mbiebl** [comment]
reverting that particular commit is not easily possible, with all the sd_device refactoring that has happened in the mean time. Otherwise I would have given that a try.

**Comment by yuwata** [comment]
@mbiebl @grawity @Keruspe Could you try #10919? I hope, this fixes c4b69e990f962128cc6975e36e91e9ad838fa2c4.

**Comment by mbiebl** [comment]
detecting lid switch events seems to be rather slow. When I close my laptop, it takes several seconds before the system suspends, ```systemctl suspend``` is almost immediate.

**Comment by mbiebl** [comment]
nvm, seems to be a completely unrelated problem:
```
Nov 25 11:44:04 pluto systemd-logind[702]: Suspending...
Nov 25 11:44:09 pluto systemd-logind[702]: Delay lock is active (UID 1000/michael, PID 2083/gnome-shell) but inhibitor timeout is reached.
```
For some reason gnome-shell is not properly interacting with logind.

**Comment by yuwata** [comment]
@mbiebl Thank you for testing the PR!
