### ISSUE TITLE
ExecStopPost does not get executed if 'systemctl daemon-reload' is being run in parallel

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#10756]
**systemd version the issue has been seen with**
> 230

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > ExecStopPost should get get executed if 'systemctl daemon-reload' is being run in parallel

**Unexpected behaviour you saw**
 > ExecStopPost does not get executed if 'systemctl daemon-reload' is being run in parallel

**Steps to reproduce the problem**
have ExecStopPost=myscript.sh
kill -9 `myapp_pid` or sigterm app and in parallel in another terminal run : while true; do echo "running systemctl daemon-reload"; systemctl daemon-reload; done
you will notice ExecStopPost does not get run and hence myscript.sh wont get run

**Comment by poettering** [comment]
This has been fixed in v234.

In general, this is a bug and request tracker for issues in the two most recent upstream systemd versions only (238 + 239 at this pont). For everything else please contact your downstreams for help. 

The submission form should actually have made that abundantly clear.
