### ISSUE TITLE
journald json format incorrectly escapes characters

### ISSUE THREAD

**Issue by ceecko** [systemd/systemd#1076]
Steps to replicate:
1) `echo "└── mystring" | systemd-cat"`
2) `journalctl -o json | tail -n1`

The JSON output looks as following (majority of fields ommited):
`{..., "MESSAGE" : "\uffffffe2\uffffff94\uffffff94\uffffffe2\uffffff94\uffffff80\uffffffe2\uffffff94\uffffff80 mystring", ...}`

The escaped parts `\uffffffe2` are not valid in JSON since JSON supports only 4 hex digits after \u and cannot be parsed properly.

E.g. in JS `JSON.parse('"\uffffffe2\uffffff94\uffffff94"')` returns `￿ffe2￿ff94￿ff94`

**Comment by sztanpet** [comment]
this was already fixed by https://github.com/systemd/systemd/commit/561a0efdcb72bec897e9ac1792b5ea0d3f279582
do you still hit this issue on git HEAD?

**Comment by ceecko** [comment]
Thanks for the fix.
I'm running the latest CentOS 7, so not the HEAD version.

```
# journalctl --version
systemd 208
+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ
```

**Comment by poettering** [comment]
Duplicate of #987 and #992 btw.
