### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by GitSoftwareNow** [systemd/systemd#10772]
when I build systemd216 it says in a console:

Making all in .
  CC     src/libsystemd/sd-bus/libsystemd_la-bus-objects.lo
In file included from ./src/shared/missing.h:33,
                 from ./src/shared/util.h:88,
                 from ./src/shared/strv.h:27,
                 from src/libsystemd/sd-bus/bus-objects.c:24:
/usr/include/linux/input.h:23: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:39: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:46: 错误：expected specifier-qualifier-list before ‘__s32’
/usr/include/linux/input.h:821: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:831: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:848: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:860: 错误：expected specifier-qualifier-list before ‘__s16’
/usr/include/linux/input.h:871: 错误：expected specifier-qualifier-list before ‘__s16’
/usr/include/linux/input.h:887: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:916: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:937: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/input.h:965: 错误：expected specifier-qualifier-list before ‘__u16’
In file included from /usr/include/linux/if_link.h:5,
                 from ./src/shared/missing.h:34,
                 from ./src/shared/util.h:88,
                 from ./src/shared/strv.h:27,
                 from src/libsystemd/sd-bus/bus-objects.c:24:
/usr/include/linux/netlink.h:44: 错误：expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/netlink.h:134: 错误：expected specifier-qualifier-list before ‘__u16’
In file included from ./src/shared/missing.h:34,
                 from ./src/shared/util.h:88,
                 from ./src/shared/strv.h:27,
                 from src/libsystemd/sd-bus/bus-objects.c:24:
/usr/include/linux/if_link.h:42: 错误：expected specifier-qualifier-list before ‘__u64’
/usr/include/linux/if_link.h:76: 错误：expected specifier-qualifier-list before ‘__u64’
/usr/include/linux/if_link.h:330: 错误：expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_link.h:401: 错误：expected specifier-qualifier-list before ‘__u8’
/usr/include/linux/if_link.h:499: 错误：expected specifier-qualifier-list before ‘__u8’
In file included from ./src/shared/missing.h:35,
                 from ./src/shared/util.h:88,
                 from ./src/shared/strv.h:27,
                 from src/libsystemd/sd-bus/bus-objects.c:24:
/usr/include/linux/loop.h:45: 错误：expected specifier-qualifier-list before ‘__u64’
In file included from /usr/include/netinet/if_ether.h:26,
                 from /usr/include/netinet/ether.h:26,
                 from ./src/shared/socket-util.h:26,
                 from ./src/core/unit.h:39,
                 from ./src/core/busname.h:27,
                 from src/libsystemd/sd-bus/bus-kernel.h:26,
                 from src/libsystemd/sd-bus/bus-internal.h:38,
                 from src/libsystemd/sd-bus/bus-objects.c:26:
/usr/include/linux/if_ether.h:133: 错误：expected specifier-qualifier-list before ‘__be16’
In file included from ./src/shared/socket-util.h:30,
                 from ./src/core/unit.h:39,
                 from ./src/core/busname.h:27,
                 from src/libsystemd/sd-bus/bus-kernel.h:26,
                 from src/libsystemd/sd-bus/bus-internal.h:38,
                 from src/libsystemd/sd-bus/bus-objects.c:26:
/usr/include/linux/if_packet.h:10: 错误：expected specifier-quali

**Comment by keszybz** [comment]
Sorry, but such ancient versions are not supported upstream.

**Comment by GitSoftwareNow** [comment]
how can I get the new version of libudev?

**Comment by keszybz** [comment]
This is the upstream, you should consider updating your distribution of choice to a more recent version. It should include a newer systemd version, integrated properly with the other programs in the distribution.
