### ISSUE TITLE
syslog.target: Failed to load configuration: No such file or directory

### ISSUE THREAD

**Issue by soconte** [systemd/systemd#10776]
**systemd version the issue has been seen with**
> systemd 229
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

**Used distribution**
 > Linux tx6s-8035 4.1.15-tx6-edduv+g77f6154 #5 SMP PREEMPT Wed Nov 14 14:28:10 CET 2018 armv7l GNU/Linux

**Expected behaviour you didn't see**
 > i would like to see syslog message but the service syslog.target did not run.

**Unexpected behaviour you saw**
 > I have the following message error: 
[    5.262340] systemd[1]: syslog.target: Failed to load configuration: No such file or directory
[    5.444277] systemd[1]: run-systemd-journal-syslog.mount: Failed to load configuration: No such file or directory
[    5.722574] systemd[1]: syslog-ng.service: Installed new job syslog-ng.service/start as 85
[    6.411533] systemd[1]: run-systemd-journal-syslog.mount: Collecting.
[   14.484549] systemd[1]: syslog-ng.service: Forked /usr/sbin/syslog-ng as 250
[   14.522337] systemd[1]: syslog-ng.service: Changed dead -> running
[   14.534694] systemd[1]: syslog-ng.service: Job syslog-ng.service/start finished, result=done
[   16.890082] systemd[1]: Child 250 (syslog-ng) died (code=exited, status=1/FAILURE)
[   16.915924] systemd[1]: syslog-ng.service: Changed running -> failed
[   16.925618] systemd[1]: syslog-ng.service: Unit entered failed state.
[   16.934590] systemd[1]: syslog-ng.service: Changed failed -> auto-restart
[   16.945863] systemd[1]: syslog-ng.service: cgroup is empty
[   17.204646] systemd[1]: syslog-ng.service: Trying to enqueue job syslog-ng.service/restart/fail
[   17.238779] systemd[1]: syslog-ng.service: Installed new job syslog-ng.service/restart as 101
[   17.274843] systemd[1]: syslog-ng.service: Scheduled restart job.
[   24.587381] systemd[1]: syslog-ng.service: Changed auto-restart -> dead
[   24.632130] systemd[1]: syslog-ng.service: Converting job syslog-ng.service/restart -> syslog-ng.service/start
[   24.767108] systemd[1]: syslog-ng.service: Changed dead -> running
[   24.807191] systemd[1]: syslog-ng.service: Job syslog-ng.service/start finished, result=done

**Comment by poettering** [comment]
As the submission form should make abundantly clear this is an upstream bug and RFE tracker for the two most recently released upstream systemd versions. That's 238 and 239 rigt now. For everything older, please contact your downstream distribution. Thank you.
