### ISSUE TITLE
libsystemd: Should each thread open its own dbus connection (sd_bus*)?

### ISSUE THREAD

**Issue by FabianKnapp** [systemd/systemd#10784]
I have an executable that opens a dbus connection with sd_bus_open_system at init time and cleanup and close this connection only on exit.
This connection is used in multiple threads (in a thread safe manner) and im wondering if this is suitable since sd_bus_add_match seems to time out if the sd_bus* object is created from another thread than the call to sd_bus_add_match happens.

**Comment by poettering** [comment]
This is a bug an RFE tracker. Please ask support questions on a more appropriate forum, such as the systemd mailing list. Thank you for understanding.
