### ISSUE TITLE
binary sizes for systemd-udevd and udevadm exploded

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10807]
building current git master, the sizes of the udevadm and systemd-udevd binary have increased over 10 times, both are over 33M in size.
```
michael@pluto:~/debian/trunk-ci/systemd-239+upstream20181116 (master)$ du -hs debian/udev/lib/systemd/systemd-udevd debian/udev/bin/udevadm 
33M	debian/udev/lib/systemd/systemd-udevd
33M	debian/udev/bin/udevadm

michael@pluto:~/debian/trunk-ci/systemd-239+upstream20181116 (master)$ file debian/udev/lib/systemd/systemd-udevd debian/udev/bin/udevadm 
debian/udev/lib/systemd/systemd-udevd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=02d261727ce051abc0ebbccaa94d3adfb3d08292, stripped
debian/udev/bin/udevadm:               ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=981a95a0fad1a6d10d42752189e595af0d690f61, stripped
```

This seems to be a recent regression, so marking that as a blocker for v240.

**Comment by poettering** [comment]
any chance you can bisect that?

**Comment by mbiebl** [comment]
git bisect shows 6cf0a204912e8fe21c681ca038c2ff1b9d9ffeb9 as the faulty commit
/cc @ssahani

**Comment by poettering** [comment]
@mbiebl that is *very* strange, that commit doesn't change anything with the linking at all... are you sure?

**Comment by poettering** [comment]
oh, frickin christ, indeed.

**Comment by ssahani** [comment]
oops sorry  indeed @mbiebl I opened a PR.

**Comment by yuwata** [comment]
Oh! I've created almost same PR...

**Comment by ssahani** [comment]
yes 255 we should not allocate when we using only 8.

**Comment by mbiebl** [comment]
I'm sorry if this caused duplicate work by explicitly CCing @ssahani :-/

**Comment by ssahani** [comment]
> I'm sorry if this caused duplicate work by explicitly CCing @ssahani :-/
no issues I spent litter under 10m . But please make sure no one is duplicating my work.
