### ISSUE TITLE
resolved has issues when too many A records

### ISSUE THREAD

**Issue by BryanQuigley** [systemd/systemd#10816]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Ubuntu 18.10 (and 18.04 and 19.04)

**Expected behaviour you didn't see**
> $ nslookup testing.irongiantdesign.com 1.1.1.1 | grep Name | wc -l
> 30
(bypassing systemd resolver returns the full 30 number of A records)

**Unexpected behaviour you saw**
 > $nslookup testing.irongiantdesign.com 127.0.0.53 | grep Name | wc -l
29 
(using systemd resolver it misses one)
If not greping it starts with ;; Truncated, retrying in TCP mode.

** Another reproducer **
telnet testing.irongiantdesign.com
telnet: could not resolve testing.irongiantdesign.com/telnet: Temporary failure in name resolution

$ telnet irongiantdesign.com
Trying 173.236.158.228...

(neither of these should work for telnet, but the name failure indicates to me it never gets there)

I also tried a build from git and in that case it fails earlier:
;; Truncated, retrying in TCP mode.
;; Connection to 127.0.0.53#53(127.0.0.53) for testing.irongiantdesign.com failed: connection refused.

even though resolutions work fine.

telnet behaves the same way in git or 239 (and 237).

Note: testing.irongiantdesign.com doesn't actually have that many valid IP addresses, done to illustrate the issue.

**Comment by poettering** [comment]
do you know any site that has that many addresses set up, that we can use to test?

**Comment by BryanQuigley** [comment]
Appears to be EDNS related as, reproducible with dig.
$ dig +noedns +noall +answer testing.irongiantdesign.com @127.0.0.53 | wc -l
29
$ dig +noall +answer testing.irongiantdesign.com @127.0.0.53 | wc -l
30

**Comment by vtapia** [comment]
It seems that the TCP stub is cutting down the payload to <512 when EDNS is disabled. This makes non-EDNS clients (nslookup) receive a "shortened" answer even when UDP returns a truncated reply for a new TCP query. Using systemtap:

EDNS enabled:
$ dig +noall +tcp +answer testing.irongiantdesign.com @127.0.0.53  |wc -l 
30

dns_packet_validate_query(): packet_size:68
on_dns_stub_stream_packet(): RC:return=1
dns_stub_process_query(): Packet:{.n_ref=1, .protocol=0, .size=68, .allocated=3928, .rindex=12, .max_size=65535, ._data=0x0, .names=0x0, .opt_start=18446744073709551615, .opt_size=18446744073709551615, .question=0x0, .answer=0x0, .opt=0x0, .ifindex=0, .family=2, .ipproto=6, .sender={...}, .destination={...}, .sender_port=59217, .destination_port=53, .ttl=64, .more=0x0, .on_stack=0, .extracted=0, .refuse_compression=0, .canonical_form=0}
dns_query_new(): Question:{.n_ref=1, .class=1, .type=1, ._name="testing.irongiantdesign.com"}
dns_stub_query_complete(): opt:1
dns_stub_finish_reply_packet(): add_opt:1 truncated:0 packet_size:525
dns_packet_append_opt.constprop.21(): EDNS:0

$ dig +noall +tcp +noedns  +answer testing.irongiantdesign.com @127.0.0.53  |wc -l
29

dns_packet_validate_query(): packet_size:45
on_dns_stub_stream_packet(): RC:return=1
dns_stub_process_query(): Packet:{.n_ref=1, .protocol=0, .size=45, .allocated=3928, .rindex=12, .max_size=65535, ._data=0x0, .names=0x0, .opt_start=18446744073709551615, .opt_size=18446744073709551615, .question=0x0, .answer=0x0, .opt=0x0, .ifindex=0, .family=2, .ipproto=6, .sender={...}, .destination={...}, .sender_port=50435, .destination_port=53, .ttl=64, .more=0x0, .on_stack=0, .extracted=0, .refuse_compression=0, .canonical_form=0}
dns_query_new(): Question:{.n_ref=1, .class=1, .type=1, ._name="testing.irongiantdesign.com"}
dns_stub_query_complete(): opt:0
dns_stub_finish_reply_packet(): add_opt:0 truncated:1 packet_size:509

**Comment by vtapia** [comment]
I think I've found the problem: systemd-resolved uses the same reply size for UDP and TCP, for both EDNS on and off. In the code:

- dns_stub_query_complete()@resolved-dns-stub.c :

r = dns_stub_make_reply_packet(&q->reply_dns_packet, DNS_PACKET_PAYLOAD_SIZE_MAX(q->request_dns_packet), q->question_idna, q->answer, &truncated);

- where DNS_PACKET_PAYLOAD_SIZE_MAX() is:

static inline uint16_t DNS_PACKET_PAYLOAD_SIZE_MAX(DnsPacket *p) {

        /* Returns the advertised maximum datagram size for replies, or the DNS default if there's nothing defined. */

        if (p->opt)
                return MAX(DNS_PACKET_UNICAST_SIZE_MAX, p->opt->key->class);

        return DNS_PACKET_UNICAST_SIZE_MAX;
}

This translates DNS_PACKET_UNICAST_SIZE_MAX to 4096 if p->opt is present (EDNS is enabled), 512 if it's not, regardless of the protocol used. I'm running some tests now with the following patch:

--- a/src/resolve/resolved-dns-packet.h
+++ b/src/resolve/resolved-dns-packet.h
@@ -136,11 +136,14 @@
 
 static inline uint16_t DNS_PACKET_PAYLOAD_SIZE_MAX(DnsPacket *p) {
 
-        /* Returns the advertised maximum datagram size for replies, or the DNS default if there's nothing defined. */
+        /* Returns the advertised maximum size for replies, or the DNS default if there's nothing defined. */
 
         if (p->opt)
                 return MAX(DNS_PACKET_UNICAST_SIZE_MAX, p->opt->key->class);
 
+        if (p->ipproto == 6)
+                return DNS_PACKET_SIZE_MAX;
+
         return DNS_PACKET_UNICAST_SIZE_MAX;
 }

**Comment by vtapia** [comment]
These are the results with the previous patch on 327:

```
# TCP and UDP with EDNS disabled and ignoring truncate flag:
root@bionic-dev:~# dig +tcp +ignore +noedns +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
30
root@bionic-dev:~# dig +notcp +ignore +noedns +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
29

# TCP and UDP with EDNS disabled and retrying with TCP after truncate:
root@bionic-dev:~# dig +tcp +noedns +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
30
root@bionic-dev:~# dig +notcp +noedns +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
30

# TCP and UDP with EDNS enabled
root@bionic-dev:~# dig +tcp +ignore +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
30
root@bionic-dev:~# dig +notcp +ignore +noall +answer testing.irongiantdesign.com 127.0.0.53 | wc -l
30

```

The only scenario where we miss results is when UDP does not retry with TCP, having EDNS disabled. I'll prepare a PR with this patch.
