### ISSUE TITLE
pam_systemd(su:session): Cannot create session: Already running in a session or user slice

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10822]
**systemd version the issue has been seen with**

239

**Used distribution**
 
Debian sid
Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825949

Running ```su``` or ```su -l``` will yield the following warning message in the journal
```
Nov 17 17:29:39 pluto su[2490]: pam_systemd(su:session): Cannot create session: Already running in a session or user slice
Nov 17 17:29:39 pluto su[2490]: pam_unix(su:session): session opened for user root by (uid=1000)
```
```
Nov 17 17:30:27 pluto su[2978]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
Nov 17 17:30:27 pluto su[2978]: pam_unix(su-l:session): session opened for user root by (uid=1000)
```

**Comment by bl33pbl0p** [comment]
This works as intended. See the comments on:
https://github.com/systemd/systemd/issues/7451
https://github.com/systemd/systemd/issues/8021

The bottom line is, as long as something in your session executes su/sudo that goes through pam_systemd, a new session will not be spawned. See PAMName= in user@uid.service, this is special-cased in pam_systemd to not spawn a session in (and thus can be used to emulate this effect elsewhere, say with cron). `machinectl shell` was added and works as PID1 will fork off the binary, however, you can just use systemd-run -t /bin/su -l to achieve roughly the same effect.

**Comment by mbiebl** [comment]
If this is working as intended, then we should not log about it as this or demote to debug level as  otherwise it will only create noise and confuse users.

**Comment by bl33pbl0p** [comment]
I think there is some value in logging about this, it indicates that a pristine new session was not spawned (and therefore the user should not expect the runtime directory to be present and systemd --user to be running), and the fact that some part of the execution environment is inherited (perhaps that is obvious already).

**Comment by mbiebl** [comment]
@bl33pbl0p as you see from the referenced downstream bug report, there are apparently many users which are concerned about this log message turning up in their /var/log/auth.log.

**Comment by poettering** [comment]
I think we should downgrade the log message. It's not a bug or anything to be concerned about hence we should log at debug level, but not above.

**Comment by poettering** [comment]
Fix waiting in #10832.

**Comment by mantel** [comment]
Then the wording of the message should be changed from "cannot create session" to "will not create session". Currently it is suggesting failure while in fact it is intentional. Even debug messages should not be misleading.

**Comment by frosty939** [comment]
Here for exactly that reason; confusion about what was failing. the "cannot"  part especially

I second the change to "will not", at the very least.
