### ISSUE TITLE
Add support for variable appending

### ISSUE THREAD

**Issue by flungo** [systemd/systemd#1082]
This is a feature request to add support for the required syntax and functionality to enable appending to variables. I feel this would be extremely useful with `$OPTIONS` variables and the like allowing multiple drop-ins to add to the options for a command run in a systemd unit. Support should be added in both Unit files and Environment Files.

The obvious and natural syntax would (in my opinion) be along the lines of `+=` so for example:

In `Unit`:

```
Environment='OPTIONS+=--verbose'
```

In `EnvironmentFile`:

```
OPTIONS+=--verbose
```

At the moment the only way to do this, would be something like:

```
ExecStartPre=/usr/bin/bash -c '/usr/bin/systemctl set-environment OPTIONS="$OPTIONS --verbose"'
```

This syntax is rather cumbersome and not very robust.

**Comment by johannbg** [comment]
Systemd since it's interception obsoleted the need for environment files. 
Today you overwrite unit files via drop-ins so you put there what you would previously put into environment files for example changing the parameter of a startup of an daemon

**Comment by poettering** [comment]
Sorry, but no.

Unit files are supposed to be simply key-value files, and adding such special appending semantics would separate us even further from that goal. Also files compatible with `EnvironmentFile=` are supposed to be valid shell scripts, hence extending the env file syntax like you suggest is not OK at all.

Generally, env files we only support for compat reasons, and we don't introduce new features in compatibility support.

To make this clear: we think that unit files and the daemon's own configuration files are where configuration should be placed, and not in split-out environment files. That's just making things worse, by adding another configuration file. Now, while it's OK if people do things like this anyway, even though we think it's not how daemons should work these days, but if you want to do that, you actually are looking for a proper shell, and that's what you should be using then. We explicitly do not want to turn systemd's unit files into yet another shell engine.

Sorry!

**Comment by flungo** [comment]
This is typically how I would add functionality to a unit but the problem is without being able to append to the environment variable (rather than set - which overwrites the value) I need multiple variables placed in the main unit to allow this.

I can't see that this is uncommon issue, particularly having seen some _workarounds_ for this sort of thing in other unit files.

# Example

For an exact use-case scenario, I use docker containers and create a unit for each container that fetches the latest image from a server, prepares the host and runs the container.

One common task I perform is using the (jwilder/nginx-proxy)[https://github.com/jwilder/nginx-proxy] image which requires images that I wish to be auto configured are run with the `-e VIRTUAL_HOST=foo.bar.com` flag.

Assuming this given unit file for the docker image I am running:

```
[Unit]
Description=Generic Docker image for %p
After=docker.service
Requires=docker.service

[Service]
Environment='DOCKER_IMAGE=docker/generic'

ExecStartPre=/usr/bin/docker pull ${DOCKER_IMAGE}
ExecStartPre=-/usr/bin/docker rm %p

ExecStart=/usr/bin/docker run --rm --name %p \
    ${DOCKER_RUN_ARGS} ${DOCKER_IMAGE} ${DOCKER_CONTAINER_ARGS}

ExecStop=-/usr/bin/docker stop %p
```

I would create a drop-in `docker-image.d/80-nginx-proxy.conf`

```
[Unit]
After=nginx-proxy.service
Wants=nginx-proxy.service

[Service]
Environment='DOCKER_RUN_ARGS=-e VIRTUAL_HOST=foo.bar.com'
```

This sort of thing works all well and good but now I can't have another drop-in that also sets `DOCKER_RUN_ARGS`: with the current system I can only have one drop in that sets each variable.

Say I also want to add a volume to the docker image. I would probably want to go about this without modifying the main unit file and would create a drop-in, say `docker-image.d/20-volumes.conf` which would look something like this:

```
[Service]
Environment='DOCKER_RUN_ARGS=-v /srv/docker/generic/data:/data'

ExecStartPre=/usr/bin/mkdir -p /srv/docker/generic/data
```

It would be nice to keep the main unit file as generic as possible (meaning it can be shared and provide just the core functionality it needs) but then have the ability for others to arbitrarily extend this functionality.

The way I would like to see this solves would be with the ability to use `+=` so rather than `'DOCKER_RUN_ARGS=...'` in each drop-in it would be `'DOCKER_RUN_ARGS+=...'` and (using the assumed file names for the drop ins I have exemplified above) would result in `DOCKER_RUN_ARGS=-v /srv/docker/generic/data:/data -e VIRTUAL_HOST=foo.bar.com`. The naming of the drop ins (which is already enforced, if I am not mistaken) will provide the ordering of the concatenation.

The only way I have seen something similar to this done is to provide many variables that can be assigned to (almost assuming you can know all the possible extension that a user may want to a unit). This does not solve the problem but alleviates it to some extent.

**Comment by flungo** [comment]
Hi @poettering 

It would seem we were both replying to this at the same time. I hope you have time to read though what I have written and can understand the use case I have set out.

Just to response some additional points you raise:
-  `+=` is completely valid shell syntax in most modern-day shells. I am sure there probably is one that doesn't but I think this form of concatenation is fairly common. If anything in terms of compatibility, this is something that is missing because when I used `sysvinit`, using `+=` would make for a much more maintainable and manageable file in the `/etc/default/...' files.
- In a lot of cases it is not possible to modify the configuration of a config file in order to get such functionality particularly when it comes to things which can only be specified by a command line argument.

At the moment drop-ins (with the exception of directives that can be listed more than once), can only override functionality and not add functionality and I feel this takes away somewhat from their potential.

If you are still strongly against this idea, or feel it does not fit with the goals of the systemd project then I understand. I just feel this would be a simple addition that would make units more extensible and configurable and improve the boundaries between units.

**Comment by ageis** [comment]
I'm in support of this appending to Environment File.I can think of many use cases. Imagine a socket and a separate service untit. Being able to append to EnvironmentFile from within the unit would be great.

**Comment by Frank-Steiner** [comment]
Here's a use case that I just ran into:

systemd-udev.service as shipped by SuSE defines this:
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6

I'd like to add AF_BLUETOOTH so that I can "hciconfig %k up" in an udev rule. Of course I can overwrite the whole RestrictAddressFamilies line with my drop-in, but then I will miss any changes made to the global default.

Using "RestrictAddressFamilies+=AF_BLUETOOTH" would be the perfect solution in this case. So the "+=" operator is useful in general, not just for environment variables.

**Comment by yuwata** [comment]
`RestrictAddressFamilies=` can be specified multiple times. So, in such a case, just adding `RestrictAddressFamilies=AF_BLUETOOTH` in a drop-in .conf file is sufficient. It is not necessary to re-assign all families.

**Comment by Frank-Steiner** [comment]
Ah, ok, thanks a lot. I knew I could do that for ExecStart etc. but wasn't aware this holds in general for systemd assignments. It's indeed somewhat confusing. udev for example also uses "RUN+=..." to add a command to be run and "RUN=" to overwrite former definitions, just like bash. Maybe it would have been better if systemd had followed this scheme. For anyone using bash or udev, the systemd way of adding or overwriting values is not intuitive.

Anyway, thanks for your answer, helps me a lot here!

**Comment by lafrech** [comment]
Came here from https://stackoverflow.com/questions/35439123/systemd-environment-directive-to-set-path.

My use case: the service calls an executable (ipopt), so it needs it in the path. I could parametrize the service to pass the absolute file path to the executable rather than rely on `PATH`, but it also needs the `LD_LIBRARY_PATH` set correctly and I don't know how to pass that another way.

I can run the service in my development environment thanks to

```
export PATH=$PATH:/my/path/to/ipopt/IpoptBuilder.v3.12.10.x86_64-linux-gnu-gcc4/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/my/path/to/ipopt/IpoptBuilder.v3.12.10.x86_64-linux-gnu-gcc4/lib/
```

but I don't know how to reproduce this (append/prepend paths) within in a service file.

Should I be doing this another way?

**Comment by lafrech** [comment]
I managed to do it in two steps. It looks convoluted but maybe it is the way to go.

Basically, the conf file passes an envvar that is prepended or appended by the unit file.

Unit file

```
[...]
ExecStart=/bin/sh -c ' \
  PATH=${IPOPT_PATH}bin:${PATH} \
  LD_LIBRARY_PATH=${IPOPT_PATH}lib:${LD_LIBRARY_PATH} \
  ${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} \
  --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} \
  --loglevel=${CELERYD_LOG_LEVEL} \
  --queues=${CELERYD_QUEUES} ${CELERYD_OPTS}'
[...]
```

Config

```
[...]
Environment="IPOPT_PATH=/path/to/ipopt/"
```

**Comment by mbiebl** [comment]
Tbh, I would just put all that setup stuff in a shell script and exec the binary as a last step.
And then start the script via `ExecStart`

**Comment by hvisage** [comment]
Yet another painful stuff of Systemd that doesn't work as expected...
A service might (like rpcbind) have some settings that is expected, ie. forcing foreground mode for systemd, but then the user would add extra options to that... a simple way of appending would've been nice, but, knowing @poettering he'll not head that hope as he has his own ideas

**Comment by hedayat** [comment]
Well, this is just unfortunate. The syntax might not be suitable, but the functionality is certainly missing and has NO proper answer from systemd. We must look for workarounds... :(

I have a service, and I'd like its command line parameters to be extensible using drop-in files for the service. So that packages can add cmdline parameters to the executable without overwriting existing ones. And this is simply impossible to do properly. All solutions for this are just workarounds like calling a shell script instead of the executable...

**Comment by boucman** [comment]
see how sshd.service (for example) do it:
ExecStart=sshd $SSHD_OPTS
EnvironmentFile=/etc/default/sshd

and in the environment file you can set your options...

**Comment by hedayat** [comment]
Doesn't work. Please read my message carefully. What if two packages want to add their own SSHD_OPTIONS? In what you suggest, the packages must _Edit_ the file /etc/defaults/sshd and append their own options to SSHD_OPTIONS. And they should make sure that they correctly undo what they've done during uninstallation. This method doesn't allow drop-in files to customize SSHD_OPTIONS.

And if packages want to edit files, they can directly edit .service file, or better provide their own drop-in file which overwrites ExecStart completely. These are undesirable, and editing a file from another package is not any better.

**Comment by boucman** [comment]
you can have multiple EnvironmentFile=, each one added by a specific package through a specific dropin, if you wan to to go fancy...

And honestly, I can understand an admin wanting to tweak the CLI of a daemon, but a package tweaking the CLI of another package ? that sounds like a very bad idea...

Can you describe your use case ? how do you deal with  the different daemons wanting contradicting options ? should the order of drop-ins matter ?

I'm not asking about syntax, i'm asking about semantic here... I'm not sure how you could handle that in a sane, comprehensible way. I'm not sure any distro would accept a package that work that way, independently of systemd being able to do it or not...

**Comment by HellScre4m** [comment]
@Bouceman no offense but systemd is a daemon doing the same thing. It
intercepts logs from syslog before handing them over to syslog, if it does
it at all. It changes the way mountpoints work and creates unheard
dependencies like local-fs.target that by default pulls your system into
rescue mode on failure, which is totally nonsense, as mush as mapping
nofail property of mount syntax to change type of depndency between mount
unit and target unit. Systemd changes a lot, it's ok people who use it
accepted it as is, but your logic is undoubtedly flawed.

**Comment by hedayat** [comment]
@boucman 
The first option is not valid: the main package is unaware of the third party packages. If it was aware, there were no need for multiple EnvironmentFile=s, it can just use a separate environment variable for each of the third party packages.

About the use case, if it is a bad idea or not, contradicting options: it is very similar to projects allowing drop-in configuration files. Tweaking the CLI of a daemon is very similar to tweaking its configuration using drop-in config files, for projects supporting it. But if a project doesn't support drop-in configs, or even it is just configurable using CLI, it is another opportunity to tweak its config. There is nothing new about it. All the problems, weirdness you mention are also valid about drop-in config files.

Does the order of drop-ins matter? Yes it does, and it already does matter in systemd: What if multiple drop-ins define the same env-var? Well, according to systemd docs:

> Multiple drop-in files with different names are applied in lexicographic order, ...
So, the order does matter, and systemd already supports it. It is again similar to how config drop-ins work.

Distros (AFAIK) happily allow packages which alter behavior of other packages using drop-in config files (and also drop-in systemd files!); so I wonder why they shouldn't allow drop-in CLI config files.

**Comment by Anveena** [comment]
> Came here from https://stackoverflow.com/questions/35439123/systemd-environment-directive-to-set-path.
> 
> My use case: the service calls an executable (ipopt), so it needs it in the path. I could parametrize the service to pass the absolute file path to the executable rather than rely on `PATH`, but it also needs the `LD_LIBRARY_PATH` set correctly and I don't know how to pass that another way.
> 
> I can run the service in my development environment thanks to
> 
> ```
> export PATH=$PATH:/my/path/to/ipopt/IpoptBuilder.v3.12.10.x86_64-linux-gnu-gcc4/bin/
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/my/path/to/ipopt/IpoptBuilder.v3.12.10.x86_64-linux-gnu-gcc4/lib/
> ```
> 
> but I don't know how to reproduce this (append/prepend paths) within in a service file.
> 
> Should I be doing this another way?

A long time has passed, do you have a more'elegant' solution, please
