### ISSUE TITLE
Keymap not set at password prompt when when using plymouth + deferred takeover + silent boot

### ISSUE THREAD

**Issue by real-or-random** [systemd/systemd#10826]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch 

**Expected behaviour you didn't see**
 > password entered in plymouth password prompt is accepted when using deferred framebuffer takeover and quiet boot

**Unexpected behaviour you saw**
 > I can enter a password in plymouth (bullets shown) and I can press enter but the password will be rejected.

**Steps to reproduce the problem**
1. Enable deferred framebuffer takeover (default in Arch on kernel 4.19)
2. Make sure the boot is quiet, i.e., nothing is written to console before the password prompt is shown.
3. Type a password and press enter. Everything looks normal, even the password prompt disappears.
4. Even a correct password is rejected, the password prompt reappears.

We can continue:

5. Press ESC to switch to console to force that some messages are written to console.
6. Press ESC again to switch to plymouth again.
7. Now the password works.

Either setting `fbcon=nodefer` or removing `quiet` from the kernel command line (and thus forcing messages to be written before the password prompt) fixes the problem. It seems that some init step is missing that is forced when something is written to the console.

And yes, I'm not too stupid to spell my password. I've verified it many times.

**Comment by poettering** [comment]
What makes you think systemd is at fault here? We have not made any adjustments whatsoever for the late-take-over stuff, hence it appears to me that if something breaks now it's the fault of something else, not systemd...

Is it possibly that your kbd mapping isn't loaded properly? i.e. you are using a non-american keyboard but your password contains characters that are located on different keys on your local keyboard?

**Comment by real-or-random** [comment]
> What makes you think systemd is at fault here?

I encounter a bug when interacting with systemd service, so this was my best first guess. Maybe changes are necessary for the late-take-over stuff? I don't know.

> Is it possibly that your kbd mapping isn't loaded properly? i.e. you are using a non-american keyboard but your password contains characters that are located on different keys on your local keyboard?

I had checked this, and verified again now. Even when I type the password assuming a American keymap, the behavior is the same.

**Comment by poettering** [comment]
So, I fear there's nothing we can do about this upstream. You have to debug this yourself I fear. There might be a bug in systemd, but I think it's unlikely, and with the available information there isn't much we can say about this.

One approach for debugging this is maybe renaming the systemd-cryptsetup binary and replacing it with a script that calls the real binary but through `exec strace -s 500 -o /tmp/log -f -D systemd-cryptsetup "$@"`. With that you should get a dump of all syscalls executed by systemd-cryptsetup at boot. This should include the messages recvd from the ask-password protocol socket, i.e. the path the pw takes towards systemd-cryptsetup.

**Comment by real-or-random** [comment]
Okay, I need to apologize. This IS a keymap issue. As I said, this was one of my first ideas, too, and I double-checked it but I consistently overlooked a key press that needs to be replaced by a different one.

I guess vconsole-setup fails because the console is not yet properly initialized (whatever that means). What can I do to help debug that? Do you think that's the fault of the kernel?

**Comment by poettering** [comment]
hmm @jwrdegoede hmm, any idea about that?

**Comment by jwrdegoede** [comment]
I wonder if this is a problem with the keymap not being set, or the keymap being different between console and X?

real-or-random, what happens if you switch to a text console (CTRL + ALT + F4) and then login there, start vi and then type your diskcrypt password as you would do under X, does it show up correctly then?

Also I see you are using arch, does our initrd contain the keymap you use under /lib/kbd/keymaps ?

Looking at a dracut generated initrd under Fedora it simply includes all files under  /lib/kbd/keymaps is this the same under arch ?

**Comment by real-or-random** [comment]
@jwrdegoede 
Hm, as I wrote in the initial report, the problem disappears when anything is written to console.  For example, I can press ESC at the graphical password prompt to switch to a console prompt. From that point on, the keymap is correct. I can now even press ESC again to switch to a graphical prompt again and the password will work. 

Actually now that I think about it that implies that vconsole-setup sets the keymap correctly (unless the forked call to loadkeys waits until I press ESC. That's another possibility. I don't know...)

> then type your diskcrypt password as you would do under X

Hm, I think you're misunderstanding. I never type my password under X, I type it at the graphical/plymouth/framebuffer prompt. So this is not a problem with keymaps being different on X and console. (And yes, my keymap works on the console.)

> Also I see you are using arch, does our initrd contain the keymap you use under /lib/kbd/keymaps ?

Yes, yes, all of this works, and the keymap always worked in initrd stage and works when I disable deferred takeover.

**Comment by jwrdegoede** [comment]
Ah ok, I think I'm starting to understand the problem now.

Lennart (or some other systemd team member) when does systemd loads the keymap? I guess it loads it based on some trigger which happens when fbcon takes over the console from the dummycon driver?

But there really is no reason for this, plymouth will use the vt/console subsys for input even when the dummycon is loaded and AFAIK the keymap can be loaded immediately at boot.

Imagine e.g. no fb driver loading for whatever reason (e.g. a bug in the fb driver) then the user can still blindly type his password, in which case it would be nice if the keymap worked.

I guess that currently loading the keyboard-map is done at the same as loading the console-font and that is why this does not happen when fbcon does not take over?

**Comment by halfline** [comment]
happens from a udev rule when vtcon changes i believe

**Comment by real-or-random** [comment]
Indeed, it's a udev rule, which doesn't apply to dummy devices. The issue disappears when I remove the exception for dummy devices. Opened a PR.

**Comment by jwrdegoede** [comment]
Removing the dummy exception sounds like a good fix to me, thanks.

Have you checked that this does not cause any error messages in the logs ?

**Comment by jwrdegoede** [comment]
Great, thank you to all involved for catching and fixing this.

Since Fedora 29 uses deferred fbcon takeover by default, I've filed a bug asking the Fedora systemd maintainers to cherry-pick this patch into Fedora systemd for now:

https://bugzilla.redhat.com/show_bug.cgi?id=1652473

**Comment by real-or-random** [comment]
> Have you checked that this does not cause any error messages in the logs ?

Hm good catch. I see the output of this line in the system log https://github.com/systemd/systemd/blob/7fa0269bcaf1e1f7060b2c393b3e71b501f4296f/src/vconsole/vconsole-setup.c#L237 and consequently also 
https://github.com/systemd/systemd/blob/7fa0269bcaf1e1f7060b2c393b3e71b501f4296f/src/vconsole/vconsole-setup.c#L273

It's not a huge problem: These messages will be emitted only when a quiet boot is used, and then they're suppressed on the console and only shown in the system log. Still not great I guess.

**Comment by jwrdegoede** [comment]
On 22-11-18 15:12, Tim Ruffing wrote:
> Hm good catch. I see the output of this line in the system log https://github.com/systemd/systemd/blob/7fa0269bcaf1e1f7060b2c393b3e71b501f4296f/src/vconsole/vconsole-setup.c#L237 and consequently also
> https://github.com/systemd/systemd/blob/7fa0269bcaf1e1f7060b2c393b3e71b501f4296f/src/vconsole/vconsole-setup.c#L273
> 
> It's not a huge problem: These messages will be emitted only when a quiet boot is used, and then they're suppressed on the console and only shown in the system log. Still not great I guess.

Can you copy and paste the actual error as it is seen in the log here?

Then we can deduct the errno value from the message and write a patch
to not log an error for that errno.

**Comment by real-or-random** [comment]
"Function not implemented"

**Comment by jwrdegoede** [comment]
Or maybe we actually need something like this:

         /* get metadata of the current font (width, height, count) */
         r = ioctl(src_fd, KDFONTOP, &cfo);
	if (r < 0 && errno = ENOSYS)
		return; /* Dummy console driver can't set font */
         if (r < 0)
                 log_warning_errno(errno, "KD_FONT_OP_GET failed while trying to get the font metadata: %m");

**Comment by real-or-random** [comment]
Your first suggestion should be enough actually. I'll test it and submit a PR.

**Comment by jwrdegoede** [comment]
On 22-11-18 15:52, Tim Ruffing wrote:
> Your first suggestion should be enough actually. I'll test it and submit a PR.

Looking at the code there is a bunch of further error logs in
that function which I expect to also show up with the
dummy driver.

E.g. this line will trigger then:

         if (cfo.op != KD_FONT_OP_SET)
                 log_warning("Fonts will not be copied to remaining consoles");

Since we skip the setting of cfo.op = KD_FONT_OP_SET in the error path.

**Comment by real-or-random** [comment]
Hm, I noticed that even if I suppress this message, I get "KD_FONT_OP_GET failed while trying to get the font metadata: *invalid argument*" twice later in the boot process. So I don't know if it's really important or desirable to suppress the one instance caused by the dummy console

 If you think that suppressing is a good idea, feel free to cherry pick  https://github.com/real-or-random/systemd/commit/725b9d31b999b9953b3bb1dfd2e7fa8cefa3faec This doesn't terminate early but converts the second warning to a notice. This suffices because some warning will always be shown before the notice  whenever the notice is triggered.

**Comment by jwrdegoede** [comment]
On 23-11-18 00:07, Tim Ruffing wrote:
> Hm, I noticed that even if I suppress this message, I get "KD_FONT_OP_GET failed while trying to get the font metadata: /invalid argument/" twice later in the boot process. So I don't know if it's really important or desirable to suppress the one instance caused by the dummy console
> 
> If you think that suppressing is a good idea, feel free to cherry pick real-or-random@725b9d3 <https://github.com/real-or-random/systemd/commit/725b9d31b999b9953b3bb1dfd2e7fa8cefa3faec> This doesn't terminate early but converts the second warning to a notice. This suffices because some warning will always be shown before the notice whenever the notice is triggered.

Thank you for investigating. I'm fine with keeping things as is, but ultimately
this is up to the systemd devs.
