### ISSUE TITLE
service menu

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#10833]
**Create one service menu, that allows user to show, start, restart, stop, debug all service that available or registered in system.**

- lightweight shell script that available with all default service, that allow to manage all registered service in system. it could show one menu, that has some choice like: list of all available service, list of all running service, particular service manager(start,stop,restart,debug).

**Comment by poettering** [comment]
Well, I can see how this could be useful, but I am also very sure that UIs involving menus and such really should not be part of systemd, but can be shipped very well outside of systemd.

Cockpit is a project that provide a nice web browser UI to managing services btw. Please consider using that.

Closing this hence. I don't disagree with the goal, but I do not think this is right for inclusion in systemd upstream. Hope that makes some sense.
