### ISSUE TITLE
Allow wildcards in networkctl status

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#10840]
**Is your feature request related to a problem? Please describe.**
We can use wildcards in .network files but not via command-line.

**Describe the solution you'd like**
Would be nice to make networkctl behave similar to systemctl with regards to wildcards:
```
systemctl status 'lol*'
networkctl status 'enp*'
```
First command will work, second won't. Having those behave consistently would simplify things for newcomers.

**Describe alternatives you've considered**
Some ugly glue scripting around it.

**Comment by yuwata** [comment]
#11719.
