### ISSUE TITLE
SysV init service managed PID collides with systemd SysV generated PID

### ISSUE THREAD

**Issue by moneytoo** [systemd/systemd#10870]
**systemd version the issue has been seen with**
> 239 (+SYSVINIT)

**Used distribution**
 > Fedora 29

**Expected behaviour you didn't see**
 > SysV init service of 3rd party RPM (Apache Cassandra) works fine on CentOS 7 but not on latest Fedora.

**Unexpected behaviour you saw**
 > Unable to manage specific SysV service on Fedora.

**Steps to reproduce the problem**

I've installed latest Apache Cassandra 3.11.3 RPM from cassandra.apache.org (because it's the version we use on CentOS and it's newer than the version in Fedora repos). 
Apache Cassandra RPM doesn't include systemd service as it has only SysV init script. Proper systemd service would resolve this issue but following case might be interesting one  for backward compatibility (if it's cared).

(IMHO probably because) SysV service manages pid file on its own, it colides with the "systemd-sysv-generator" generated pid file (?) and causes:

```
systemd[1]: Starting LSB: distributed storage system for structured data...
su[20314]: (to cassandra) root on none
su[20314]: pam_unix(su:session): session opened for user cassandra by (uid=0)
su[20314]: pam_unix(su:session): session closed for user cassandra
cassandra[20300]: Starting Cassandra: OK
systemd[1]: cassandra.service: New main PID 20438 does not belong to service, and PID file is not owned by root. Refusing.
systemd[1]: cassandra.service: New main PID 20438 does not belong to service, and PID file is not owned by root. Refusing.
systemd[1]: cassandra.service: Failed with result 'protocol'.
systemd[1]: Failed to start LSB: distributed storage system for structured data.
```

This prevents me from stopping or viewing status of this service using ``systemctl``, ``service`` or even with ``/etc/rc.d/init.d/cassandra status`` as all are wrapped by systemd.

SysV service that sets and works with ``pid_file=/var/run/cassandra/cassandra.pid``: https://github.com/apache/cassandra/blob/cassandra-3.11.3/redhat/cassandra

PID:

```
$ ll /var/run/cassandra/cassandra.pid 
-rw-------. 1 cassandra cassandra 5 21. lis 12.04 /var/run/cassandra/cassandra.pid
```

Systemd generated service: 

```
$ systemctl cat cassandra
# /run/systemd/generator.late/cassandra.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/rc.d/init.d/cassandra
Description=LSB: distributed storage system for structured data
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target
After=remote-fs.target
After=network-online.target
After=nss-lookup.target
After=time-sync.target
After=ntp.service
After=mdadm.service
Wants=network-online.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=no
PIDFile=/var/run/cassandra/cassandra.pid
SuccessExitStatus=5 6
ExecStart=/etc/rc.d/init.d/cassandra start
ExecStop=/etc/rc.d/init.d/cassandra stop
ExecReload=/etc/rc.d/init.d/cassandra reload
```

**Comment by moneytoo** [comment]
Thank you very much for your replies. Hopefully they will help me in pushing changes and eventually moving to systemd service with that package. I will try using setpriv. Many thanks

**Comment by saphireee** [comment]
The same as above is on RedHat 7.7 with cassandra so maybe /etc/rc.d/init.d/cassandra script should be changed in cassandra distro for Redhat?

**Comment by saphireee** [comment]
Better then sysv init cassandra starting script (turn it off) make native systemd service entry /etc/systemd/system/cassandra.service like this:

[Unit]
Description=Apache Cassandra
After=network.target

[Service]
PIDFile=/var/run/cassandra/cassandra.pid
User=cassandra
Group=cassandra
ExecStart=/usr/sbin/cassandra -f -p /var/run/cassandra/cassandra.pid
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by jonixmobile** [comment]
Hi, I prefer this config for the service:

[Unit]
Description=Apache Cassandra
After=network.target

[Service]
User=cassandra
Group=cassandra
ExecStart=/usr/sbin/cassandra -f -p /var/run/cassandra/cassandra.pid
Restart=always
ExecStartPost=/bin/sh -c "echo $MAINPID > /var/run/cassandra/cassandra.pid"
StandardOutput=journal
StandardError=journal
LimitNOFILE=100000
LimitMEMLOCK=infinity
LimitNPROC=32768
LimitAS=infinity

[Install]
WantedBy=multi-user.target

**Comment by mbiebl** [comment]
> ExecStartPost=/bin/sh -c "echo $MAINPID > /var/run/cassandra/cassandra.pid"

This is weird. Why would you do that?
Also, you are not using Type=forking, so what's the point of maintaining a pid file?
