### ISSUE TITLE
journald incorrectly complains about missing /var/log/journal user journal directory

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10879]
This is a regression in git master, the problem does not exist in v239.

When starting a system which has *not* enabled persistent journal storage, i.e. there is *no* /var/log/journal, I get the following message in dmesg

```
[    4.671955] systemd-journald[214]: Failed to open user journal directory '/var/log/journal/02bbd76228274574b05bf55b6d32cdff/': No such file or directory

[   78.232390] systemd-journald[214]: Failed to open user journal directory '/var/log/journal/02bbd76228274574b05bf55b6d32cdff/': No such file or directory
```

Obviously, if no persistent journal is enabled, it doesn't make sense to log such an error to kmsg

**Comment by poettering** [comment]
Fix waiting in #10937.
