### ISSUE TITLE
Read IPForward=kernel option in networkd

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#109]
See https://github.com/systemd/systemd/pull/41#issuecomment-110145054 for details

**Comment by teg** [comment]
Renamed this issue as the patch was reverted, with the intention of readding it once we have a working version.

**Comment by mischief** [comment]
re https://github.com/systemd/systemd/pull/41#issuecomment-110175886 what about the reverse? how should converting _ADDRESS_FAMILY_BOOLEAN_INVALID back to "kernel" string be handled?

**Comment by poettering** [comment]
> re #41 (comment) what about the reverse? how should converting _ADDRESS_FAMILY_BOOLEAN_INVALID back to "kernel" string be handled?

Hmm, do we actually need that somewhere? I don't think we do, do we?

**Comment by mischief** [comment]
guess not, unless you guys plan to write something like `systemctl show ...` for networkd

**Comment by mischief** [comment]
there already are conversion routines for the other AddressFamilyBoolean values to strings

**Comment by poettering** [comment]
> guess not, unless you guys plan to write something like systemctl show ... for networkd

We certainly do want that eventually (currently networkd has no bus API), but then we can still add address_family_bool_to_string_with_kernel() or so, which handles this, and which we only use for this case.

**Comment by poettering** [comment]
> there already are conversion routines for the other AddressFamilyBoolean values to strings

But do we use them anywhere where the "kernel" case would matter?
