### ISSUE TITLE
`systemd-networkd-tests.py` is failing in the CentOS CI infrastructure

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#10908]
The `systemd-networkd-tests.py` doesn't like the CentOS CI infrastructure as discussed in https://github.com/systemd/systemd-centos-ci/issues/18#issuecomment-441191519.

Full log: https://paste.fedoraproject.org/paste/jnhwagD3-saGbeCNzYYk0w/raw

@ssahani could you, please, take a look?

**Comment by evverx** [comment]
@mrc0mmand as you might have noticed I've just transferred the issue to the systemd bug tracker where it belongs.

@ssahani I'm not sure what's going on, but as as a person who often disagrees with everyone else and vice versa, I'd say that it's perfectly normal when PRs and ideas are rejected sometimes (though I'd prefer it if my brilliant ideas would never be rejected :-)).

**Comment by yuwata** [comment]
Note that @mrc0mmand's log seems to be almost same as [I pasted](https://github.com/systemd/systemd/issues/10662#issuecomment-436483211), which I got on fedora 28.

**Comment by ssahani** [comment]
Ok let's debug this .

First isolate these DHCP tests.  We will take just one case.

1.  Please take a wireshark dump at the veth-peer. See the **DHCP Discoverer** messages are reaching there from networkd.
2.  Attach the dump file .

IMP: Verify we have disabled the Firewall. 

Now see **DHCP Discoverer** are reaching veth-peer.

If that is the case.

- Option 1: Disable firewall 
                   systemctl disable firewalld.
- Option 2:
          Add a FW rule for DHCP.

**Comment by mrc0mmand** [comment]
Thank you, you're right, the DHCP requests are blocked by firewalld. Now the question is whether we write rules for firewalld to avoid this issue or just disable firewalld altogether.

**Comment by ssahani** [comment]
adding rule should be nice I think 
'''
 firewall-cmd --add-service=dhcp --permanent
'''

But again we not testing FW. We testing networkd :) @evverx  and @yuwata ?

**Comment by yuwata** [comment]
I think the test script should not touch firewalld. I prefer the following:
- check whether firewalld is running or not,
- check its rule if enabled,
- warn if the setting is not suitable,
- and skip corresponding tests.

**Comment by ssahani** [comment]
> I think the test script should not touch firewalld, as it may run on bare systems. Of course, it is not recommended way, but some lazy person like me runs the test on their laptop. So, I prefer the following:
> 
> * check whether firewalld is running or not,
> * check its rule if enabled,a
> * warn if the setting is not suitable,
> * and skip corresponding tests.

yes I  think since these setting depends on the environment ( we can't guess which distribution and which FW) . So we should keep a note that FW rules required to run these tests. 

**The Caller is responsible for setting and cleaning up the environment.**

TEST_RUNNER ->

- Setup env
- Run tests
- Cleanup env

**Comment by mrc0mmand** [comment]
@ssahani I went with your recommendation and added something among these lines to our bootstrap script:

```bash
if systemctl status firewalld.service; then
    firewall-cmd --permanent --add-service dhcp --add-service dhcpv6
    firewall-cmd --reload
fi
```

which did the trick for most of the issues we've seen. However, there are still two issues, which still occur even with the aforementioned rules or with firewalld completely disabled:

```
======================================================================
FAIL: test_erspan_tunnel (__main__.NetworkdNetDevTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./systemd-networkd-tests.py", line 391, in test_erspan_tunnel
    self.assertTrue(self.link_exits('erspan-test'))
AssertionError: False is not true

======================================================================
FAIL: test_ip_route_gateway (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./systemd-networkd-tests.py", line 557, in test_ip_route_gateway
    self.assertRegex(output, 'default')
AssertionError: Regex didn't match: 'default' not found in '149.10.124.48/28 proto kernel scope link src 149.10.124.58 \n149.10.124.64 proto static scope link'
```

Going through the history I noticed that both tests are pretty recent (~2 days):
 - ERSPAN (@ssahani) https://github.com/systemd/systemd/commit/2266864b04257d7a92d1f2064797ec239068895b#diff-d0096f157a976d0716ba5fc6f93ec01f
 - ip route gateway (@yuwata) https://github.com/systemd/systemd/commit/f5050e48aee0de888cdea68580e577325ed0d1f8#diff-d0096f157a976d0716ba5fc6f93ec01f

**Comment by ssahani** [comment]
erspan is pretty new. So I don;t think it would be there we need to skip it .

**Comment by yuwata** [comment]
>     * ip route gateway (@yuwata) [f5050e4#diff-d0096f157a976d0716ba5fc6f93ec01f](https://github.com/systemd/systemd/commit/f5050e48aee0de888cdea68580e577325ed0d1f8#diff-d0096f157a976d0716ba5fc6f93ec01f)

@mrc0mmand I have not changed `test_ip_route_gateway`, but does it pass now?

**Comment by mrc0mmand** [comment]
@yuwata yes, the `test_ip_route_gateway` passes as well.

**Comment by yuwata** [comment]
OK. I do not know what fixes the failure. But let's close this.
