### ISSUE TITLE
hibernation and kernel image with Arch Linux

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#10900]
**systemd version the issue has been seen with**
> current git master, including edda44605f06a41fb86b7ab8128dcf99161d2344

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > System hibernates.

**Unexpected behaviour you saw**
 > System does not hibernate, assumes kernel image is missing.

**Steps to reproduce the problem**
Install systemd from git master on an Arch Linux system and try to hibernate.

Commit edda44605f06a41fb86b7ab8128dcf99161d2344 introduced a mechanism to check that the currently running kernel image is still available to boot after hibernation. The current code fails for Arch Linux, though: Basically our linux packages contain the modules in `(/usr)/lib/modules/$(uname -r)/` and the kernel image `/boot/vmlinuz-$pkgname`, without a version (as installing the same package multiple times in different versions is not supported).

To make this work with our current linux packages we could assume that the correct kernel image is available if the modules are, so ...

- check for a file inside `/lib/modules/$(uname -r)/`, for example `modules.dep` or
- check for the existence of `/lib/modules/$(uname -r)/` itself.

CC @heftig (maintainer Arch Linux package `linux`)

**Comment by heftig** [comment]
Please try linux 4.19.3.arch1-2 or 4.19.4.arch1-1 from the [testing] repo. I added the symlink `/lib/modules/$(uname -r)/vmlinuz` which is the very first thing systemd tests for.

**Comment by poettering** [comment]
(btw, I'd recommend arch to place the kernel in /lib/modules directly, and then only copy it out to /boot with kernel-install, i.e. so that the the OS is fully monopolized in /usr, and /boot only contains redundant copies of the boot loader and the kernels)

**Comment by heftig** [comment]
Following the boot loader spec would be nice, but we'd immediately hang anyone who currently uses a static boot loader configuration out to dry. (Not that we didn't make changes like this in the past, but there's also significant internal resistance to the idea.)

Even grub-mkconfig is currently run only by the user. I'm not sure if GRUB 2.02 and Syslinux support BSL at all. We'd also need support for managing multiple loader entries per kernel with differing options and initrds.

**Comment by eworm-de** [comment]
The idea is to stop packaging to `/boot/`, instead the linux package contains the file (not symlink) `/usr/lib/modules/$(uname -r)/vmlinuz`. In `post_install()` and `post_upgrade()` we add another line:

```
install -D -m0644 usr/lib/modules/%KERNVER%/vmlinuz boot/vmlinuz-%PKGBASE%
```
From bootloader's view this does not change anything. No more changes should be required, no?

**Comment by eworm-de** [comment]
We have packages now that work with recent systemd.
Whether or not to move the kernel image to /usr/ remains to be discusses.
