### ISSUE TITLE
Timed out waiting for device dev-console.device

### ISSUE THREAD

**Issue by blochl** [systemd/systemd#10914]
**systemd version the issue has been seen with**
systemd 239

**Used distribution**
Custom

**Expected behaviour you didn't see**
 systemd starting smoothly

**Unexpected behaviour you saw**

Upon boot, I see the message:
```
[ *** ] A start job is running for dev-console.device (xxs / 1min 30s)
```

And then:
```
[ TIME ] Timed out waiting for device dev-console.device.
[DEPEND] Dependency failed for Serial Getty on console.
```

I have read the comments in issue #3446 (which looks somewhat similar to mine) and I do have `CONFIG_FHANDLE` enabled in the kernel config, as well as all the other recommendations for the kernel configuration from [README](https://github.com/systemd/systemd/blob/master/README).

I do have udev on my system, and in the output of `udevadm info --export-db` I see the following (don't know if it's indeed related):
```
P: /devices/virtual/tty/console
N: console
E: DEVNAME=/dev/console
E: DEVPATH=/devices/virtual/tty/console
E: MAJOR=5
E: MINOR=1
E: SUBSYSTEM=tty
```

**Steps to reproduce the problem**

Boot the system.

**Comment by yuwata** [comment]
Could you try the workarounds in https://github.com/systemd/systemd/issues/10754#issuecomment-440513058?

**Comment by blochl** [comment]
@yuwata, Just did (your branch, 986ab0d) - exactly the same result.
I tend to think that it has something to do with the kernel config options - my kernel is the most "non standard" part of the system. But I have followed the suggested kernel config in the systemd [README](https://github.com/systemd/systemd/blob/master/README) exactly, so there may very well be a bug in the documentation. I use Linux 4.14.67 with a minimalistic, hand-modified config.

The error looks like Getty is missing, but in the config I checked all the reasonable character devices, to no avail. Also, as mentioned before, the console device appears in `udevadm info`.

**Comment by blochl** [comment]
> My educated guess is that you instantiated serial-getty@.service on /dev/console or so? don't do that, it's not supposed to be used for that.

Thanks!! This was the problem!

##### Explanation for whoever will have the same problem:

My system is built with Buildroot, and by default it has the setting `BR2_TARGET_GENERIC_GETTY_PORT="console"`. When it installs systemd, it uses this setting to instantiate serial-getty@.service on the corresponding device. Changing the value of `BR2_TARGET_GENERIC_GETTY_PORT` to `tty1` fixed it!

Thanks again for your time and effort!

**Comment by poettering** [comment]
buildroot appears quite borked there.

To bind a getty onto a physical serial port instantiate `serial-getty@.service` on the serial port. In this case the .device unit of that physical serial port is a dependency and all behaves the way it should

To bind a getty on a classic Linux VT (i.e. /dev/tty1, /dev/tty2/ …) instantiate `getty@.service`. If systemd-logind is uses this happens automatically.

To bind a getty on /dev/console enable `console-getty@service`. It doesn't do the physical device dependency stuff and doesn't assume to point to a Linux VT either.

(And there's a fourth kind of getty: `container-getty@.service` can be instantiated on pty pseudo-devices to add additional logins in container environments)

It's a pity these four kind of getty services are required, but it's simply a fact of life that tty devices are not as similar as people assume they are. And you shouldn't use the wrong one for the wrong kind of device.

It appears BuildRoot doesn't get this right. Please file a bug there about this, asking them to fix that.
