### ISSUE TITLE
systemctl exits with return code 3 after reporting status of non-existing unit

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#1092]
It has been reported in RHBZ [1] that it is useful to be able to distinguish between services which are stopped and don't exits at all, i.e. `systemctl status iamstopped.service` returns with exit code 3 and `systemctl status idontexist.service` returns the same exit code. According to [2] better exit code seems to be 4. Btw, not that we are obliged to follow what is written in LSB, but because `service` shell script on Red Hat based distros uses systemctl by default, it would be nice to fix it there instead of working around the problem. 

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1256858
[2] http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic.html#INISCRPTACT

**Comment by poettering** [comment]
Note that this must be done carefully, as units lacking unit files may be started (for example, if a user started a service, deleted its unit file, and reloaded systemd -- in this case the service will continue to run, even though the unit file is missing).

Hence, there would need to be a clean fall-back logic: we should check the load state only if the unit is actually stopped.
