### ISSUE TITLE
loader.conf(5) documents unimplemented loader.conf.d

### ISSUE THREAD

**Issue by 9ary** [systemd/systemd#10923]
https://github.com/systemd/systemd/blob/e9c026c2bf787c412cf71e1c53f5dccb8e5cff80/man/loader.conf.xml#L26
https://github.com/systemd/systemd/blob/e9c026c2bf787c412cf71e1c53f5dccb8e5cff80/man/loader.conf.xml#L33-L38

This feature is specified by the manpage, but sd-boot does not appear to implement it at all. I don't really see any benefit in implementing it considering how little there is to configure, maybe it's just a mistake?

**Comment by yuwata** [comment]
Fix is waiting in #10925.
