### ISSUE TITLE
Broken trailing whitespace trimming in sd-boot

### ISSUE THREAD

**Issue by 9ary** [systemd/systemd#10922]
I was reading the code to understand the configuration format better (the Boot Loader Specification is very elusive), and this caught my attention:
https://github.com/systemd/systemd/blob/e9c026c2bf787c412cf71e1c53f5dccb8e5cff80/src/boot/efi/boot.c#L983-L985

If the intent here is to trim trailing whitespace, then `sep` is incorrect. It should be `(CHAR8 *)" \t"` like in the leading whitespace trimming loop just above. Otherwise, `config_entry_add_linux` will cause this loop to trim trailing `=` instead.

**Comment by yuwata** [comment]
Fix is waiting in #10925.
