### ISSUE TITLE
hwdb: Introduce some kind of sorting for the models in 70-mouse.hwdb

### ISSUE THREAD

**Issue by claell** [systemd/systemd#10941]
Currently the model list for a manufacturer does not seem to follow any logic regarding sorting and formatting (new lines). I suggest to take a bit more care of it to make it easier for humans to retrieve information more quickly. I think this lead to the two entries for the MX1000 mouse:
https://github.com/systemd/systemd/blob/f5050e48aee0de888cdea68580e577325ed0d1f8/hwdb/70-mouse.hwdb#L371
https://github.com/systemd/systemd/blob/f5050e48aee0de888cdea68580e577325ed0d1f8/hwdb/70-mouse.hwdb#L528

**Comment by claell** [comment]
@yuwata This was not only about #10943. There are also rather unrelated devices in manufacturer sections that are below each other because they share the same DPI rate.

To me this might be easier and can save a few lines, but makes it harder to sort the devices. Maybe it is better to unbound these entries to be able to sort them. Unfortunatly that will lead to more lines of the same DPI entry.

@all What do you think about this?

**Comment by whot** [comment]
I'd prefer the devices to be sorted correctly over saving a few lines.

**Comment by claell** [comment]
@whot Alright, since nobody else responded until now, I will probably create a PR which unbinds the devices and then resort them in a second PR. Might take a while, until I have time, though.
