### ISSUE TITLE
Information leakages when using DoT

### ISSUE THREAD

**Issue by fgont** [systemd/systemd#10953]
I'm running a Ubuntu 18.10 with systemd 239. I've edited
/etc/systemd/resolved.conf as:

[Resolve]
DNS=1.1.1.1
#FallbackDNS=
Domains=~.
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
DNSOverTLS=opportunistic
#Cache=yes
#DNSStubListener=yes

Still, when running tcpdump it seems systemd-resolved still tries to use
(in parallel with 1.1.1.1) the DNS advertised by my local DHCP server.

My assumption was that setting: Domains=~.
would prevent that.

However, when looking at other issues reported here, it seems the documentation is simply incorrect, and that the aforementioned setting just means "use this DNS resolver for all domains".

However, if DNS queries are being sent to other non-DoT resolvers, what's the point of using DoT in the first place?

Thanks,
Fernando

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

**Comment by poettering** [comment]
Please provide "resolvectl status" when this happens.

most likely the interface this is sent to has "~." or so as domain configured, which has the effect to bind al traffic to it, too.

**Comment by poettering** [comment]
Closing due to lack of response.
