### ISSUE TITLE
systemd-boot: boot menu seems to be invisible

### ISSUE THREAD

**Issue by roberdorfer** [systemd/systemd#1095]
I'm dual booting with windows. When I boot my system, I do not see the systemd-boot menu that allows me to choose which OS to boot. The screen stays entirely black. I can use the keyboard to choose both operating systems though and boot into them successfully as soon as I press enter.

What I'm trying to say is that it feels like the menu is black on black. Functionality is there, but I can't see anything.

This is on arch linux 64 bit. Kernel 4.1.6-1-ck, systemd version 224-1.

**Comment by michich** [comment]
This happened to me too on a HP Z230 workstation. A change of a setting in the UEFI firmware fixed it, but I cannot remember what setting it was.
What hardware do you have?

**Comment by roberdorfer** [comment]
I've been trying everything I could find in UEFI, to no avail. 

What hardware are you talking about? MOBO?

**Comment by michich** [comment]
In the HP setup the guilty option was Advanced -> Power-On Options -> POST Messages. As long as it was set to Enabled, I could not see the boot menu.
Yes, the motherboard is likely relevant. If you have a discrete graphics card, that may be too. Or whether you have multiple displays.

**Comment by roberdorfer** [comment]
MOBO: MSI Z87M-G43

Graphics: Nvidia GTX 770

3 Screens

**Comment by poettering** [comment]
@kaysievers ?

**Comment by dvdhrm** [comment]
`POST Messages` enables display of debugging messages. Sounds like a reasonable culprit, that might break graphics access. @RoBi89, do you see a similar option in your BIOS menu?

**Comment by roberdorfer** [comment]
I'm currently traveling, but I do know that I don't have POST messages enabled. The thing is, I never had, and I've had the menu working fine before, so I doubt it's related. In fact, the one change I actually made which seemed to cause the whole ordeal, was to enable my bios password. Ever since then it hasn't worked properly.

And before you ask, yes, I've disabled the password again, but that did not fix the problem with systemd-boot.

**Comment by roberdorfer** [comment]
I seem to have found the culprit: 

If I enable "Full screen logo display" the menu is visible, otherwise it's invisible. But, like I said before, it also used to work with full screen logo display disable. But there definitely is some connection between the two.

**Comment by dvdhrm** [comment]
I presume `Full screen logo display` is a firmware option on your machine? If you're entirely sure that this used to work, and you didn't do a firmware update, I'd be interested in the gummiboot/sd-boot version that this worked with? This should help us checking whether we introduced a regression.

**Comment by roberdorfer** [comment]
Yeah, sorry, I should have been clearer. "Full screen logo display" is an option in my UEFI settings. It basically just displays the MSI logo when booting.

It worked fine with 224-1, it was just setting a bios password that broke it. I'll try to explain it a bit differently.
- 224-1, fsld disabled, no bios pw -> worked fine
- I enable the bios pw -> Menu is invisible
- I disable the bios pw again -> Menu is still invisible
- I enable fsld -> Menu is visible again

**Comment by dvdhrm** [comment]
TBH, this sounds like a bug in your firmware; some obscure internal state-tracking that is toggled by BIOS-PW and FSLD. I checked the log of sd-boot and couldn't find any interesting changes there. We just use the basic text/graphics APIs.

Maybe there's a workaround by resetting the graphics API in sd-boot, or doing some other resets. But without a machine to reproduce it, I doubt we'll be able to figure out what exactly goes wrong in your firmware. And to be honest, it really sounds like a bug in the FW.

Does the windows boot-selector work fine for you?

Btw., you might wanna try setting a boot-logo via sd-boot and using timeout=0. Then look whether the logo is displayes (you need timeout=0 to make the logo display, btw).

**Comment by rhssk** [comment]
I have the same problem. It started occurring about 3 weeks ago, shame that I didn't note systemd version. My MoBo is MSI A78M-E35 with v30.6(latest) BIOS. I tried turning on Full Screen Logo Display, but that didn't change a thing for me.

**Comment by kaysievers** [comment]
This does not sound like a boot manager issue.

**Comment by thenickdude** [comment]
I have the Asrock Rack EP2C602 motherboard and was experiencing this exact same problem. Turning on "Full screen logo display" fixed it for me too, thanks!
