### ISSUE TITLE
Broken journals because of power loss.

### ISSUE THREAD

**Issue by alexzk1** [systemd/systemd#10965]
Today I got power loss which made journals broken silently.
Then later I tried to run qtcreator and got "bus error". Spent some time debugging into and googling,
found that sd_journal_open () fails.
Next I tried journalctl --disk-usage which showed true reason for error (https://stackoverflow.com/questions/33687786/qt-creator-doesnt-start/53508840#53508840 2nd answer 2018 year).

So I think systemd should notify somehow directly to stdout/stderr such a cases, even if it tried to write error to sys journal, you know, its broken, that's why we fail...

Also add some SIGBUS handler maybe, which will print to stderr something meaningfull, like "was not able to map to ram file xxxx" instead "Bus error" only. Actually I thought it is qt d-bus error initially...

**Comment by poettering** [comment]
That stackoverflow message is not correct.

Which systemd version is this?Is this pre or post 43767d9d5e0ce8923828aebf9154da7af83916f7? Please always fill in the issue form, it is very relevant for us to know which systemd version you are using.

SIGBUS happens for memory mappings which are not backed by file data, for example when a mapping is established and accessed for a file that is shorter than the mapping. It's also generated when there are actual IO errors on disk, i.e. hw/file system errors.

**Comment by alexzk1** [comment]
`systemctl --version

> systemd 239
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

Issue was with qtcreator. It was not starting with message "Bus error.", then I did "gdb qtcreator" and got stack trace mentioning sd_journal_open (). Googled a little, then tried journalctl --disk-usage which showed-up that some file in /var/log/journals has problems. I had power loss before, so all went clear - because of power loss/fsck journal went unreadable/writable properly.

**Comment by poettering** [comment]
> Issue was with qtcreator. It was not starting with message "Bus error.", then I did "gdb qtcreator" and got stack trace mentioning sd_journal_open ().

please provide the full backtrace of this

**Comment by alexzk1** [comment]
> Thread 1 "qtcreator" received signal SIGBUS, Bus error.
> 0x00007ffff5666d56 in ?? () from /usr/lib/libsystemd.so.0
> (gdb) help
> List of classes of commands:
> 
> aliases -- Aliases of other commands
> breakpoints -- Making program stop at certain points
> data -- Examining data
> files -- Specifying and examining files
> internals -- Maintenance commands
> obscure -- Obscure features
> running -- Running the program
> stack -- Examining the stack
> status -- Status inquiries
> support -- Support facilities
> tracepoints -- Tracing of program execution without stopping the program
> user-defined -- User-defined commands
> 
> Type "help" followed by a class name for a list of commands in that class.
> Type "help all" for the list of all commands.
> Type "help" followed by command name for full documentation.
> Type "apropos word" to search for commands related to "word".
> Command name abbreviations are allowed if unambiguous.
> (gdb) bt
> #0  0x00007ffff5666d56 in ?? () from /usr/lib/libsystemd.so.0
> #1  0x00007ffff5667e10 in ?? () from /usr/lib/libsystemd.so.0
> #2  0x00007ffff5667f35 in ?? () from /usr/lib/libsystemd.so.0
> #3  0x00007ffff5668c80 in ?? () from /usr/lib/libsystemd.so.0
> #4  0x00007ffff5667f7f in ?? () from /usr/lib/libsystemd.so.0
> #5  0x00007ffff56681ff in ?? () from /usr/lib/libsystemd.so.0
> #6  0x00007ffff5668375 in ?? () from /usr/lib/libsystemd.so.0
> #7  0x00007ffff56689c6 in sd_journal_open () from /usr/lib/libsystemd.so.0
> #8  0x00007fffe61f204f in ?? () from /usr/lib/qtcreator/plugins/libProjectExplorer.so
> #9  0x00007fffe61f58ab in ?? () from /usr/lib/qtcreator/plugins/libProjectExplorer.so
> #10 0x00007fffe602a599 in ?? () from /usr/lib/qtcreator/plugins/libProjectExplorer.so
> #11 0x00007fffe6019693 in ProjectExplorer::ProjectExplorerPlugin::initialize(QStringList const&, QString*) ()
>    from /usr/lib/qtcreator/plugins/libProjectExplorer.so
> #12 0x00007ffff7faa53e in ExtensionSystem::Internal::PluginSpecPrivate::initializePlugin() ()
>    from /usr/bin/../lib/qtcreator/libExtensionSystem.so.4
> #13 0x00007ffff7fa0b38 in ExtensionSystem::Internal::PluginManagerPrivate::loadPlugin(ExtensionSystem::PluginSpec*, ExtensionSystem::PluginSpec::State) () from /usr/bin/../lib/qtcreator/libExtensionSystem.so.4
> #14 0x00007ffff7fa1fc9 in ExtensionSystem::Internal::PluginManagerPrivate::loadPlugins() ()
>    from /usr/bin/../lib/qtcreator/libExtensionSystem.so.4
> #15 0x000055555555e1c0 in ?? ()
> #16 0x00007ffff671a223 in __libc_start_main () from /usr/lib/libc.so.6
> #17 0x000055555555e80e in ?? ()
> (gdb) quit

**Comment by alexzk1** [comment]
Broken file was

> var/log/journal/606980f452a14d4bb7327a74a7ff41ee/system@00057ba473706a85-48f3052664924467.journal~, ignoring file: Input/output error

So i just deleted whole folder "journal" and restarted.

**Comment by poettering** [comment]
Can you get that backtrace with debug symbols installed? Otherwise there's little we can do...

**Comment by alexzk1** [comment]
No...that will not help actually, bcs latest compilers use -pie by default.
To get traces need to recompile with -no-pie.

Also I don't know how to repeat that broken file. Next time it will happen will be 2 years later. That's why I asked to add message, because in 2 years will have to google again..

**Comment by kirbyfan64** [comment]
Kind of related (but also unrelated), as I watch this issue tracker, I'm kind of starting to get the vibe that distros should include systemd debug symbols by default in non-minimal installations... There have been quite a few issues here that were unsolvable due to lack debug symbols, and considering that systemd is a core system component, it would be beneficial to at least have a chance of fixing these.

**Comment by poettering** [comment]
Anyway, the I am not convinced that the connection between SIGBUS and the broken journal file are that obvious as they appear to you. Without a backtrace this is not really debuggable though.

BTW: is it possible that your fs created some I/O errors? anything interesting regarding that in dmesg? what kind of fs is that? I find it interesting that journalctl reports "Input/Output Error" on that "broken" file. That's not an error journalctl normally generates on its own, but looks like an error passed in from the kernel. Now, if the fs generates IO errors then yes, to programs that memory map the journal files this will indeed result in a SIGBUS. But note that when you have a bad fs, then this is nothing particular to journal files. For example, executables and shared libraries are mmaped the same way and any IO error accessing them during execution will also result in SIGBUS... Or to say this differently: if there are indeed errors reported by the fs itself, then I'd say that it's probably OK to SIGBUS in this case. (Note that journalctl actually installs a SIGBUS handler to catch IO errors and exit cleanly, but qtcreator can't really do that).

Anyway, without more information, such as a backtrace with debug symbols or at least a copy of the journal file there's little we can do about this. Any chance you can sitll supply that?

**Comment by poettering** [comment]
> Kind of related (but also unrelated), as I watch this issue tracker, I'm kind of starting to get the vibe that distros should include systemd debug symbols by default in non-minimal installations... There have been quite a few issues here that were unsolvable due to lack debug symbols, and considering that systemd is a core system component, it would be beneficial to at least have a chance of fixing these.

Well, yes, every distro should be built with minimal debug symbols on. Fedora does that for example. systems without debug symbols or simply not debuggable, and we probably should refuse even taking bug reports from such systems...

**Comment by alexzk1** [comment]
No sorry. I have fixed all errors (deleted journals, restarted) prior to write here. So no more errors - all works.
Except, file name looks like temporary (ends by ~). Is it possibly write of it was not finished by loss, then on next boot it tried to load this file? Question why, all temps must be deleted.

**Comment by poettering** [comment]
> No sorry. I have fixed all errors (deleted journals, restarted) prior to write here. So no more errors - all works.
> Except, file name looks like temporary (ends by ~). Is it possibly write of it was not finished by loss, then on next boot it tried to load this file? Question why, all temps must be deleted.

It's not a temporary file. if journald detects a file that isn't in a clean state at start-up it will rename it by appending "~" to it. This is how it marks "invalid" files. It's indication for "read this if you can, but never ever write to it again, which would make things worse". It explicitly won't delete them though, we are very careful in not removing any log data needlessly. The journal file parser is actually very careful with parsing the files it reads, so that it can make the best even from corrupted files. However this only works if the file isn't affected by read errors reported from the underlying fs. i.e. we can only make sure we are good with handling internal inconsistency in our own files, but if the underlying OS has trouble even getting these files to us, then we can't make things better.

So I checked our codebase, we never generate IO ourselves, except on SIGBUS or when the fs reported it (which is the same pretty much). This fact really strongly indicates that the fs below was corrupt.

But I am not sure we can do much about it, if we can reproduce this, and no logs or artifacts from the case survive...

> Also first I tried, i rebooted with --fsck.mode=force - error still was there, this means, this broken file was created prior power loss.

Again, which file system was this?

**Comment by alexzk1** [comment]
Archlinux, 4.18.7-2-ck-haswell #1 SMP PREEMPT Wed Sep 12 16:36:14 EDT 2018 x86_64 GNU/Linux

**Comment by poettering** [comment]
Hmm, ext4 should be stable enough to not cause this too randomly.

But I figure if not logs or artifacts survive from the incedent we can't do much about this. If you ever run into this again, please copy out all journal files (including the ones suffixed with '~' — actually in particular those), anything that you see in dmesg, and so on. Backtraces with debug symbols would be great too. Otherwise this is all a black box for us and we cannot fix this.

Thank you for understanding!
