### ISSUE TITLE
 missing.h redefines the ethtool_link_settings structure

### ISSUE THREAD

**Issue by galaxy4public** [systemd/systemd#10966]
In the missing.h header the ethtool_link_settings is defined twice which results in a compiler bailing out if the conditions are met (no structure is available from the system-wide headers).

The first definition is at https://github.com/systemd/systemd/blob/master/src/basic/missing.h#L1310 and the second definition is at https://github.com/systemd/systemd/blob/master/src/basic/missing.h#L1467 .

I think the fix for this is just to drop the ethtool_link_settings at the first location since the second one is better defined (covers more fields).

**Comment by poettering** [comment]
Indeed! Fix waiting in #10968.
