### ISSUE TITLE
po: Update Zanata template

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#10975]
It looks like that the translation template and translations on Zanata are outdated. I wanted to update Czech translation using Zanata, but was not able to find any of the recently added strings, only the ones that were added 9 or more months ago. Please, consider updating it.

**edit:** [Here](https://github.com/systemd/systemd/commit/9ecb603f906cbaeacc9711023b570e17be0931ce) are instructions how to do it.

**Comment by poettering** [comment]
As I understand Zanata is dead now, hence let's close this.
