### ISSUE TITLE
Clarify docs for default resource accounting

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#10973]
**Is your feature request related to a problem? Please describe.**
According to https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html the "DefaultTasksAccounting= defaults to on, DefaultMemoryAccounting= to yes, the other three settings to off." It does not state the reasons for this decision though.

**Describe the solution you'd like**
Would be nice to clarify why some accounting options are enabled while others are disabled. Does it pose significant overhead on the system? If so - what kind of? It would be of great help to sysadmins when deciding which resource accounting to enable and on which level. It would come in handy for package maintainers as well to decide which config shall be shipped as default.

**Describe alternatives you've considered**
Checked https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html but it did not help.

**Comment by poettering** [comment]
I am not sure that systemd man pages are the right place for quantitatively discussing the perfomance impact of kernel functionality. I am sure the right place to discuss that is, … wel …l, the kernel docs if anything. 

Moreover these things tend to get out of date quickly: the negative impact of these forms of accounting is being worked on continously in the kernel community. Adding estimations about performance behaviour of the kernel to our own docs is hence something that very quickly would get out of date,

That said, we actually *do* document this somewhere: in the NEWS file whenever we change the defaults of these options (grep it for `Accounting`). And we'll continue to do that whenever we change the defaults again (and we will), with our current findings. For this kind of progressive development I think NEWS is the best fit.

hence I think we should close this issue now. I hope this makes sense?
