### ISSUE TITLE
Misleading error message when ReadWritePaths doesn't exist

### ISSUE THREAD

**Issue by ebourg** [systemd/systemd#10972]
Hi,

Using systemd 239 in Debian sid, the service as defined below failed to start with the error :

    Nov 28 14:34:34 icare systemd[1]: Starting Apache Tomcat 9 Web Application Server...
    Nov 28 14:34:34 icare systemd[1210]: tomcat9.service: Failed to set up mount namespacing: No such file or directory
    Nov 28 14:34:34 icare systemd[1210]: tomcat9.service: Failed at step NAMESPACE spawning /usr/libexec/tomcat9/tomcat-update-policy.sh: No such file or directory
    Nov 28 14:34:34 icare systemd[1]: tomcat9.service: Control process exited, code=exited status=226
    Nov 28 14:34:34 icare systemd[1]: tomcat9.service: Failed with result 'exit-code'.
    Nov 28 14:34:34 icare systemd[1]: Failed to start Apache Tomcat 9 Web Application Server.

I traced that back to one of the `ReadWritePaths` options which was pointing to a non existent directory (`/var/lib/tomcat9/webapp/` instead of `/var/lib/tomcat9/webapps/`).

The error message was rather misleading, I thought there was an issue with the `ExecStartPre` script (`tomcat-update-policy.sh`). It would be nice to mention the wrong path whenever a `No such file or directory` error occurs.

Here is the service file used:

    #
    # Systemd unit file for Apache Tomcat
    #
    
    [Unit]
    Description=Apache Tomcat 9 Web Application Server
    Documentation=https://tomcat.apache.org/tomcat-9.0-doc/index.html
    After=network.target
    
    [Service]
    
    # Configuration
    Environment="CATALINA_HOME=/usr/share/tomcat9"
    Environment="CATALINA_BASE=/var/lib/tomcat9"
    Environment="CATALINA_TMPDIR=/tmp"
    Environment="JAVA_OPTS=-Djava.awt.headless=true"
    EnvironmentFile=-/etc/default/tomcat9
    
    # Lifecycle
    Type=simple
    ExecStartPre=+/usr/libexec/tomcat9/tomcat-update-policy.sh
    ExecStart=/bin/sh /usr/libexec/tomcat9/tomcat-start.sh
    SuccessExitStatus=143
    Restart=on-abort
    
    # Logging
    SyslogIdentifier=tomcat9
    
    # Security
    User=tomcat
    Group=tomcat
    PrivateTmp=yes
    AmbientCapabilities=CAP_NET_BIND_SERVICE
    NoNewPrivileges=true
    LogsDirectory=tomcat9
    LogsDirectoryMode=750
    CacheDirectory=tomcat9
    CacheDirectoryMode=750
    ProtectSystem=strict
    ReadWritePaths=/etc/tomcat9/Catalina/
    ReadWritePaths=/var/lib/tomcat9/webapp/
    ReadWritePaths=/var/log/tomcat9/
    ReadWritePaths=/var/cache/tomcat9/
    
    [Install]
    WantedBy=multi-user.target

**Comment by poettering** [comment]
Which systemd version is this?

Please fill in the submission form properly, it asks for such things precisely that we don't have to ask every time.

**Comment by ebourg** [comment]
That's with systemd 239, sorry sir. I edited the initial message.

**Comment by aburch** [comment]
I found similar error messages confusing myself.  A message such as "Failed to set up mount namespacing: No such file or directory" will not point people to the `ReadWritePaths=` option.

It would be nice if the specific option could be mentioned, certainly the path should at least be included to allow easier guessing (just search for the problematic path in the service's config).

**Comment by poettering** [comment]
(btw, LogsDirectory=tomcat9 also implies ReadWriteDirectory=/var/log/tomcat9, that line is redundant hence, similar for CacheDirectory=)

(And you could use ConfigurationDirectory= and StateDirectory= to cover the other two dirs.)

(Neither of these recommendations are going to make the bad error messages any better though)

**Comment by ebourg** [comment]
Thanks a lot for the review, I'll try that.

**Comment by ebourg** [comment]
Thank you

**Comment by qome** [comment]
Why should systemd fail at all when something in a ReadWritePath directive doesn't exist? Is there a behind-the-scenes technical reason?

Simply authorizing a service to access a path doesn't mean the path is mandatory for the service to function.
