### ISSUE TITLE
Wifi not connecting...

### ISSUE THREAD

**Issue by AndrieVorster** [systemd/systemd#1101]
Hi, I am using a Mecer/Mustek laptop and I cannot connect to Wifi.
Since I have no Internet connection I am posting this screenshots... Via my Mothers Laptop.
The current driver (ipw2200-fw) is installed and up to date... I think this is a systemd problem.

I am using netclt/wifi-menu...
`wifi-menu -o`

Here I try to connect to our Wifi Router (my phone, Mothers laptop etc. is connected, so it's working).
`journald -xe`
[Wifi Router.](https://drive.google.com/file/d/0B4QLBt770Wyuc01mTVJ1dHRIc2M/view?usp=sharing)

Here I try to connect to my phones Wifi Hotspot with no success as well (my Mothers laptop can connect to it, so it's working).
`journald -xe`
[Phone Hotspot.](https://drive.google.com/file/d/0B4QLBt770WyuN0x4bFlsWW52VVk/view?usp=sharing)

Regards,
And thanks,
Andrie Vorster.

**Comment by poettering** [comment]
THis is not a systemd problem, systemd has not concept of "wifi" or anything like that. Please ask for help at your distribution of choice.

Sorry,

**Comment by AndrieVorster** [comment]
Thanks I did but I can't get it fixed!
Sorry for the trouble!
Andrie...
