### ISSUE TITLE
fails to build reproducibly on armhf

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11022]
**systemd version the issue has been seen with**

v239

**Used distribution**
 
Debian sid

During a test build on https://tests.reproducible-builds.org/ the systemd package failed to build reproducibly on armhf https://tests.reproducible-builds.org/debian/rb-pkg/unstable/armhf/systemd.html

If you look at the diff between the two builds at https://tests.reproducible-builds.org/debian/logdiffs/unstable/armhf/systemd_239-13.diff.gz one noticable difference I could spot is
```
-Build machine cpu family: aarch64
-Build machine cpu: aarch64
+Build machine cpu family: arm
+Build machine cpu: armv7l
```

Somehow the build architecture seems to leak into the bootctl binary if you look at the resulting diffoscope diff https://tests.reproducible-builds.org/debian/dbdtxt/unstable/armhf/systemd_239-13.diffoscope.txt.gz which compares all resulting files between the two builds.
E.g. I see in this diff
```
│ │ │ │ │ -  0x000046b0 2d626f6f 74616136 342e6566 69000000 -bootaa64.efi...
│ │ │ │ │ +  0x000046b0 2d626f6f 7461726d 2e656669 00000000 -bootarm.efi....
```

Why does bootctl embed the build-architecture into the binary?

**Comment by floppym** [comment]
> Why does bootctl embed the build-architecture into the binary?

bootctl needs to know what name to give to the EFI binary when it copies it to /boot. This file name varies depending on the CPU architecture.

https://wiki.debian.org/UEFI#Booting_a_UEFI_machine_normally

See EFI_MACHINE_TYPE_NAME in meson.build, which is derived from `host_machine.cpu_family()` value. You can grep the source to see where this is utilized.

https://github.com/systemd/systemd/blob/v239/meson.build#L1243

By default, this value is auto-detected by meson. 

https://github.com/mesonbuild/meson/blob/0.48.2/mesonbuild/environment.py#L196

If you need some consistent value other than what meson auto-detects, you can utilize a meson cross file and set the cpu_family there.

http://mesonbuild.com/Cross-compilation.html

**Comment by mbiebl** [comment]
@floppym I'm not cross-compiling here...

**Comment by floppym** [comment]
Are you not building 32 bit binaries on a 64 bit system?

**Comment by floppym** [comment]
In the reference build, meson outputs `Build machine cpu family: aarch64`.

In the second build, meson ouputs `Build machine cpu family: arm`.

Was there some system configuration or hardware change between the two builds?

Regardles of whether you are cross compiling, you can use a cross file to override meson's system auto-detection.

**Comment by mbiebl** [comment]
It is my understand that it's a hardware change on the second build.

How would you use a cross-file as part of the Debian package build process?

**Comment by floppym** [comment]
I'm not really familiar with the process of creating Debian packages.

In case it helps, here's the eclass (bash) code we use on Gentoo to do meson-based builds.

https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/meson.eclass

The `_meson_create_cross_file` function auto-generates a cross file based on some environment variables (like CHOST and CC). We do this for both cross-compiles, and multi-lib compiles

An example cross file for doing an x86 build on amd64 is below. This also includes some system-specific CFLAGS from my workstation.

```
[binaries]
ar = ['x86_64-pc-linux-gnu-ar']
c = ['x86_64-pc-linux-gnu-gcc', '-m32']
cpp = ['x86_64-pc-linux-gnu-g++', '-m32']
fortran = ['x86_64-pc-linux-gnu-gfortran', '-m32']
llvm-config = 'llvm-config'
objc = ['cc']
objcpp = ['c++']
pkgconfig = 'i686-pc-linux-gnu-pkg-config'
strip = ['strip']

[properties]
c_args = ['-O2', '-pipe', '-march=amdfam10']
c_link_args = ['-O2', '-pipe', '-march=amdfam10', '-Wl,-O1', '-Wl,--as-needed']
cpp_args = ['-O2', '-pipe', '-march=amdfam10']
cpp_link_args = ['-O2', '-pipe', '-march=amdfam10', '-Wl,-O1', '-Wl,--as-needed']
fortran_args = ['-O2', '-pipe', '-march=amdfam10']
fortran_link_args = ['-O2', '-pipe', '-march=amdfam10', '-Wl,-O1', '-Wl,--as-needed']
objc_args = []
objc_link_args = ['-Wl,-O1', '-Wl,--as-needed']
objcpp_args = []
objcpp_link_args = ['-Wl,-O1', '-Wl,--as-needed']

[host_machine]
system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
```

**Comment by floppym** [comment]
It also occurs to me that the reference build might have been running with wrong the CPU "personality". Perhaps you just need to call `setarch` to make the kernel report the CPU as 32-bit ARM on your ARM64 build system(s).

**Comment by mbiebl** [comment]
The point of reproducible-builds.org is to inject invariability into the build process. Faking the  build CPU architecture as part of the (Debian) build process would be counter productive.

Afaics the problem is, that the systemd build system embeds the build architecture when it should use the target architecture.

**Comment by floppym** [comment]
setarch examples:
```
floppym@naomi test % setarch x86_64 meson build
The Meson build system
Version: 0.48.2
Source dir: /home/floppym/tmp/test
Build dir: /home/floppym/tmp/test/build
Build type: native build
Project name: test
Project version: undefined
Native C compiler: ccache cc (gcc 8.2.0 "cc (Gentoo 8.2.0-r4 p1.5) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 0
Found ninja-1.8.2.git.kitware.dyndep-1.jobserver-1 at /usr/bin/ninja

floppym@naomi test % setarch i686 meson build32
The Meson build system
Version: 0.48.2
Source dir: /home/floppym/tmp/test
Build dir: /home/floppym/tmp/test/build32
Build type: native build
Project name: test
Project version: undefined
Native C compiler: ccache cc (gcc 8.2.0 "cc (Gentoo 8.2.0-r4 p1.5) 8.2.0")
Build machine cpu family: x86
Build machine cpu: i686
Build targets in project: 0
Found ninja-1.8.2.git.kitware.dyndep-1.jobserver-1 at /usr/bin/ninja
```

**Comment by floppym** [comment]
> Afaics the problem is, that the systemd build system embeds the build architecture when it should use the target architecture.

If the target (aka host) architechture is different from the build architechture, you are cross-compiling, and should use a cross file.

**Comment by floppym** [comment]
In any case, this is not a systemd bug, but a limitation of meson. If you want the auto-detection improved, create a bug in their issue tracker.

**Comment by mbiebl** [comment]
@floppym Thanks a lot for your input so far. If I read https://tests.reproducible-builds.org/debian/index_variations.html correctly, what they vary for the armhf build is that sometimes they use arm64 kernels and sometimes not.

```
kernel-version
on amd64 systematically varied, on armhf not systematically, on i386 and arm64 not at all

on armhf one of: 
   Linux 4.17.0-0.bpo.3-armmp-lpae #1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) armv7l 
   Linux 4.18.0-0.bpo.1-arm64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) aarch64 
   Linux 4.18.0-0.bpo.1-armmp #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) armv7l 
   Linux 4.18.0-0.bpo.1-armmp-lpae #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) armv7l 
   Linux 4.19.0-rc7-arm64 #1 SMP Debian 4.19~rc7-1~exp1 (2018-10-07) aarch64 
   Linux 4.9.0-8-armmp #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) armv7l 
   Linux 4.9.0-8-armmp #1 SMP Debian 4.9.130-2 (2018-10-27) armv7l 
   Linux 4.9.0-8-armmp-lpae #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) armv7l 
   Linux 4.9.0-8-armmp-lpae #1 SMP Debian 4.9.130-2 (2018-10-27) armv7l
```

If I boot an armhf system with an arm64 kernel to build armhf binaries, that's not cross-compiling. Or am I getting this wrong?

**Comment by mbiebl** [comment]
Anyway, I'll try to get more information from the reproducible-builds.org people first, how exactly they are setting up the environment for the second build to know why ```host_machine.cpu_family()``` thinks it runs on arm64

**Comment by poettering** [comment]
It appears on the offending build meson's `host_machine.cpu_family()` simply returns unstable data. The way I read meson's docs, we are using `host_machine` here correctly, but it's not giving us the correct data sometimes. probably something to loop the meson people in about. @jpakkane @nirbheek any idea?

**Comment by jpakkane** [comment]
The platform detection logic on Meson is based on Python's `platform.system()`. We rely on it to tell us what the actual platform is. If you look at the returned value from above this is obvious:

```
-Build machine cpu family: aarch64
-Build machine cpu: aarch64
+Build machine cpu family: arm
+Build machine cpu: armv7l
```

On one run the system reports to have a 64 bit processor and on another a 32 bit one. AFAICR we had an autodetection issue on x86 when people when running 32 bit userland on a 64 bit kernel. Maybe something similar is going on here?

On an unrelated note, the cross file above has things like this:

```
c_link_args = ['-O2', '-pipe', '-march=amdfam10', '-Wl,-O1', '-Wl,--as-needed']
```

The only one of these that should be there is the `--march` one. `-O2` and `-Wl,-O1` come from the build type (unless you want to use `plain`), `-pipe` is added always by default and `-Wl,--as-needed` should be set with the `b_asneeded` option.

**Comment by mbiebl** [comment]
meson's ```host_machine.cpu_family()``` utilizes  Python's platform.machine() which in turn uses uname.
That particular arm buildd has a arm64 cpu and kernel and builds the package inside a armhf chroot.
"uname -a" in such place returns ```Linux jtx1a 4.18.0-0.bpo.1-arm64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) aarch64 GNU/Linux```
dpkg-architecture, which consults gcc to dermine host/target prints
```
DEB_BUILD_ARCH=armhf
DEB_BUILD_ARCH_ABI=eabihf
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=arm
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=arm
DEB_BUILD_GNU_SYSTEM=linux-gnueabihf
DEB_BUILD_GNU_TYPE=arm-linux-gnueabihf
DEB_BUILD_MULTIARCH=arm-linux-gnueabihf
DEB_HOST_ARCH=armhf
DEB_HOST_ARCH_ABI=eabihf
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=arm
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=arm
DEB_HOST_GNU_SYSTEM=linux-gnueabihf
DEB_HOST_GNU_TYPE=arm-linux-gnueabihf
DEB_HOST_MULTIARCH=arm-linux-gnueabihf
DEB_TARGET_ARCH=armhf
DEB_TARGET_ARCH_ABI=eabihf
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=arm
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=arm
DEB_TARGET_GNU_SYSTEM=linux-gnueabihf
DEB_TARGET_GNU_TYPE=arm-linux-gnueabihf
DEB_TARGET_MULTIARCH=arm-linux-gnueabihf
```
So at first glance this does indeed look like a meson issue to me. Maybe consulting gcc instead of uname is a better way to determine the target cpu?

**Comment by poettering** [comment]
@mbiebl well, but `setarch` exists to change the uname to a 32bit one. did they do that correctly in the build servers? If you do differently arche'd chroot()s, you really need to call `setarch` too

**Comment by poettering** [comment]
> So at first glance this does indeed look like a meson issue to me. Maybe consulting gcc instead of uname is a better way to determine the host cpu?

that's awfully C and gcc specific though?

**Comment by mbiebl** [comment]
Faking the architecture data so meson get's the target type correct, doesn't feel right either...

**Comment by mbiebl** [comment]
I made one more experiment. I've setup a i386 chroot on an amd64 host.
Inside the i386 chroot, I get
```Linux pluto 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux``` and ```platform.machine()``` gives me ```x86_64```.

Yet meson detects the following:
```
Build machine cpu family: x86
Build machine cpu: i686
```

**Comment by jpakkane** [comment]
That's because we have special case code for that combination. See `environment.py` line 237 onwards. Presumably we'd need the same for arm32/64 combinations. That would require someone with detailed knowledge how arm platform defines on compilers behave.

**Comment by poettering** [comment]
@jpakkane hmm, maybe meson should derive the arch to build for from python's `sysconfig.get_config_var("BUILD_GNU_TYPE")`. That would mean it's not relevant what kernel is used, but what python itself was compiled for. And the idea would would be that what python is compiled for matches what the rest of the system's userspace is compiled for.

**Comment by mbiebl** [comment]
Maybe this is helpful. I can run that on more architectures if wanted.
```
amd64
~~~~~
python sysconfig.get_config_var()
=================================
HOST_GNU_TYPE x86_64-pc-linux-gnu
BUILD_GNU_TYPE x86_64-pc-linux-gnu

gcc -dumpmachine
================
x86_64-linux-gnu

dpkg-architecture
=========================
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu


i386
~~~~
python sysconfig.get_config_var()
=================================
HOST_GNU_TYPE x86_64-pc-linux-gnu
BUILD_GNU_TYPE x86_64-pc-linux-gnu

gcc -dumpmachine
================
x86_64-linux-gnu

dpkg-architecture
=========================
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu


armel
~~~~~
python sysconfig.get_config_var()
=================================
HOST_GNU_TYPE armv7l-unknown-linux-gnueabi
BUILD_GNU_TYPE armv7l-unknown-linux-gnueabi

gcc -dumpmachine
================
arm-linux-gnueabi

dpkg-architecture
=========================
DEB_BUILD_ARCH=armel
DEB_BUILD_ARCH_ABI=eabi
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=arm
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=arm
DEB_BUILD_GNU_SYSTEM=linux-gnueabi
DEB_BUILD_GNU_TYPE=arm-linux-gnueabi
DEB_BUILD_MULTIARCH=arm-linux-gnueabi
DEB_HOST_ARCH=armel
DEB_HOST_ARCH_ABI=eabi
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=arm
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=arm
DEB_HOST_GNU_SYSTEM=linux-gnueabi
DEB_HOST_GNU_TYPE=arm-linux-gnueabi
DEB_HOST_MULTIARCH=arm-linux-gnueabi
DEB_TARGET_ARCH=armel
DEB_TARGET_ARCH_ABI=eabi
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=arm
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=arm
DEB_TARGET_GNU_SYSTEM=linux-gnueabi
DEB_TARGET_GNU_TYPE=arm-linux-gnueabi
DEB_TARGET_MULTIARCH=arm-linux-gnueabi


armhf
~~~~~
python sysconfig.get_config_var()
=================================
HOST_GNU_TYPE armv8l-unknown-linux-gnueabihf
BUILD_GNU_TYPE armv8l-unknown-linux-gnueabihf

gcc -dumpmachine
================
arm-linux-gnueabihf

dpkg-architecture
=========================
DEB_BUILD_ARCH=armhf
DEB_BUILD_ARCH_ABI=eabihf
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=arm
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=arm
DEB_BUILD_GNU_SYSTEM=linux-gnueabihf
DEB_BUILD_GNU_TYPE=arm-linux-gnueabihf
DEB_BUILD_MULTIARCH=arm-linux-gnueabihf
DEB_HOST_ARCH=armhf
DEB_HOST_ARCH_ABI=eabihf
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=arm
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=arm
DEB_HOST_GNU_SYSTEM=linux-gnueabihf
DEB_HOST_GNU_TYPE=arm-linux-gnueabihf
DEB_HOST_MULTIARCH=arm-linux-gnueabihf
DEB_TARGET_ARCH=armhf
DEB_TARGET_ARCH_ABI=eabihf
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=arm
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=arm
DEB_TARGET_GNU_SYSTEM=linux-gnueabihf
DEB_TARGET_GNU_TYPE=arm-linux-gnueabihf
DEB_TARGET_MULTIARCH=arm-linux-gnueabihf


arm64
~~~~~
python sysconfig.get_config_var()
=================================
HOST_GNU_TYPE aarch64-unknown-linux-gnu
BUILD_GNU_TYPE aarch64-unknown-linux-gnu

gcc -dumpmachine
================
aarch64-linux-gnu

dpkg-architecture
=========================
DEB_BUILD_ARCH=arm64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=arm64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=aarch64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=aarch64-linux-gnu
DEB_BUILD_MULTIARCH=aarch64-linux-gnu
DEB_HOST_ARCH=arm64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=arm64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=aarch64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=aarch64-linux-gnu
DEB_HOST_MULTIARCH=aarch64-linux-gnu
DEB_TARGET_ARCH=arm64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=arm64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=aarch64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=aarch64-linux-gnu
DEB_TARGET_MULTIARCH=aarch64-linux-gnu
```

**Comment by poettering** [comment]
@mbiebl the i386 output you pasted looks very much not right? copy/paste mistake?

**Comment by poettering** [comment]
So, I wonder how portable checking `BUILD_GNU_TYPE` is. I mean, I think that might be an autoconf thing, and hence isn't set if Python is built using a different build system maybe? (or do they only support autoconf builds?)

(It might be a bit funny though if meson checks an autoconfism to configure itself, no? ;-))

Anyway, @jpakkane, is checking `BUILD_GNU_TYPE` maybe a good option here, at least when it is set? Appears to make these things nicely deterministic...

**Comment by mbiebl** [comment]
@nirbheek according the dpkg-architecture, it uses gcc as well:
```
       dpkg-architecture provides a facility to determine and set the build and host architecture for package building.

       The build architecture is always determined by an external call to dpkg(1), and cannot be set at the command line.

       You  can  specify  the  host  architecture  by providing one or both of the options --host-arch and --host-type. The default is determined by an external call to
       gcc(1), or the same as the build architecture if CC or gcc are both not available. One out of --host-arch and --host-type is sufficient, the value of  the  other
       will  be  set  to  a  usable  default.  Indeed, it is often better to only specify one, because dpkg-architecture will warn you if your choice does not match the
       default.
```

**Comment by nirbheek** [comment]
> @nirbheek according to the dpkg-architecture man page, it uses gcc as well:

Sounds like we should skip the middle-man and call the compiler ourselves like we already do on x86_64. In Meson it will, of course, work with whatever compiler you have configured (gcc/clang/icc/etc), which might be correct than `dpkg-architecture` in the general case (f.ex., when not building a deb package).

If you're building, say, a project that only builds Rust or D code it may do unexpected things, but that's something to be fixed when that use-case gets hit.

**Comment by nirbheek** [comment]
FWIW, the direction we're taking in meson to reduce reliance on autodetection is with a new feature called a [`native file`](https://github.com/mesonbuild/meson/commit/0ab27add49cedb6f5985dfba7ba40c8d29ae91dc) (similar to `cross file`) which allows you to specify the build machine. Currently it only supports a `[binaries]` section, but we can also add a `[build_machine]` section to specify the `cpu`, `cpu_family`, etc.

**Comment by nirbheek** [comment]
I don't really disagree with you, Lennart. Checking Python is definitely more likely to give a correct answer than `uname` for the reasons you mentioned. However, it's not the 'primary source' of that information, the compiler is.

I think there's a bit of a misunderstanding of how the arch is fetched from the compiler. We don't check just the C compiler, we check the following compilers (whichever are in use): C/C++/ObjC/ObjC++/Fortran and trust that the toolchain environment is sane (i.e., different compilers aren't targeting different archs). We don't check D, Swift, Rust and that's fine for now.

**Comment by floppym** [comment]
> The only one of these that should be there is the --march one. -O2 and -Wl,-O1 come from the build type (unless you want to use plain), -pipe is added always by default and -Wl,--as-needed should be set with the b_asneeded option.

Gentoo (and probably most distros) build with build type "plain". The referenced cross file is auto-generated based on environment variables.

**Comment by poettering** [comment]
Anyway, I think we can close this here though, right? I mean, I doubt this is important enough to deserve a work-around in our upstream meson scripts (and a temporary down-stream fix should be easy), and is something that should be fixed in Meson instead. @mbiebl can you file this as bug against meson instead?

**Comment by nirbheek** [comment]
> Anyway, I think we can close this here though, right? I mean, I doubt this is important enough to deserve a work-around in our upstream meson scripts (and a temporary down-stream fix should be easy), and is something that should be fixed in Meson instead. @mbiebl can you file this as bug against meson instead?

Yes, please file a bug with meson.

**Comment by mbiebl** [comment]
Yes, I'll move this over to meson. Thanks all for your input so far.
