### ISSUE TITLE
systemd-nspawn should support ephemeral systems using overlayfs

### ISSUE THREAD

**Issue by thiagomacieira** [systemd/systemd#11054]
**Is your feature request related to a problem? Please describe.**
When using `systemd-nspawn --ephemeral`, the entire dir seems to be copied to a temporary path in /tmp. It would be more efficient if it used an overlay instead, though the user needs to be warned not to change the lower dir.

**Describe the solution you'd like**
Please add an option such as `--overlay-ephemeral`, `--overlay-root`, or similar so that the root mount be an overlay, such that any modifications be written to the ephemeral storage.

**Describe alternatives you've considered**
I've tried `--overlay=+/::/` but that did not boot (see #3847). A shorthand would be appreciated, though.

**Comment by poettering** [comment]
the problem with overlayfs is that it has really weird, non-posixish semantics. but i gues that doesn't matter too much, given that it is there...

On file systems that support snapshorts or reflinks I figure those are still preferable over overlayfs though

**Comment by thiagomacieira** [comment]
Agreed, it would be preferable for others, though note that there's a behaviour change if someone does go and modify the lower overlayfs dir.

In my case, the reflink didn't work because I was running this on /tmp (tmpfs). If I had been using /var/tmp (btrfs), I wouldn't have noticed.

**Comment by poettering** [comment]
Fix in #11243
