### ISSUE TITLE
hwdb; lenovo yoga 11e 3rd gen orientation

### ISSUE THREAD

**Issue by Alderich** [systemd/systemd#11057]
I'm not sure if this is the right place for me to post this. If not, apologies. 

My machine is running Pop!_OS version of Ubuntu 18.10. iio-sensor-proxy is packaged with the installation. The accelerometers  are being detected, but the orientation is 90 degrees counter-clockwise from where it should be.  

I'm having some difficulty correcting orientation of the screen. I added /etc/udev/hwdb.d/60-sensor-local.hwdb as per the documentation, including the following:

`sensor:modalias:acpi:BOSC0200:BOSC0200:dmi:*ThinkPadYoga11e3rdGen*
ACCEL_MOUNT_MATRIX=0, 1, 0; -1, 0, 0; 0, 0, 1`

I also updated with the following commands:

`systemd-hwdb update`

and 

`udevadm trigger -v -p DEVNAME=/dev/iio:device0`

This doesn't change the incorrect orientation. Am I missing something?

**Comment by hadess** [comment]
> This doesn't change the incorrect orientation. Am I missing something?

Did you check that your changes made a difference in the `udevadm info --export-db` output, eg. that `ACCEL_MOUNT_MATRIX` was applied to the IIO device correctly? (if you actually typed the quirk all on one line as in your comment above, it's certainly not going to work)

**Comment by poettering** [comment]
Let's close this due to lack of response.
