### ISSUE TITLE
HWDB: Logitech MX Master 2S Revision

### ISSUE THREAD

**Issue by esoleyman** [systemd/systemd#11079]
**Is your feature request related to a problem? Please describe.**
The Logitech MX Master 2S mouse is capable of connecting through the unifying receiver (RF) and bluetooth. The current HWDB entry only has it for the unifying receiver and is missing one for bluetooth.

**Describe the solution you'd like**
I have created a pull request to revise the existing entry to make it clearer while adding another entry for the bluetooth connectivity.

#11078

**Comment by poettering** [comment]
Let's close this, as #11078 has been merged.
