### ISSUE TITLE
Core dump when using %tmpfiles_create_package during rpm-ostree compose tree

### ISSUE THREAD

**Issue by rfairley** [systemd/systemd#11124]
**systemd version the issue has been seen with**

```
# systemctl --version 
systemd 238
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
# cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Fedora 28.340 (Atomic Host)"
```

**Expected behaviour you didn't see**

Using the RPM specfile macro `%tmpfiles_create_package` should either succeed, or give a message along the lines of "File <path> not found" if it fails during the pre-install.

**Unexpected behaviour you saw**

The command fails and dumps core, with the following output in the pre-install script of `console-login-helper-messages` during an rpm-ostree compose.

```
console-login-helper-messages.prein: /usr/console-login-helper-messages.prein: line 9:     3 Aborted                 (core dumped) systemd-tmpfiles --replace=/usr/lib/tmpfiles.d/console-login-helper-messages-issuegen.conf --create -  &> /dev/null <<SYSTEMD_INLINE_EOF
console-login-helper-messages.prein:  
console-login-helper-messages.prein: SYSTEMD_INLINE_EOF 
console-login-helper-messages.prein: 
console-login-helper-messages.prein: 
console-login-helper-messages.prein: systemd-tmpfiles --replace=/usr/lib/tmpfiles.d/console-login-helper-messages-profile.conf --create - <<SYSTEMD_INLINE_EOF &>/dev/null || : 
console-login-helper-messages.prein:  
console-login-helper-messages.prein: SYSTEMD_INLINE_EOF
```

Stack trace is as follows, and the entry is given in coredumpctl:

```
# journalctl -xe
...
Dec 11 19:26:33 localhost.localdomain rpm-ostree[1161]: Executed %prein for console-login-helper-messages in 64ms
Dec 11 19:26:33 localhost.localdomain systemd-coredump[1313]: Process 1311 (systemd-tmpfile) of user 0 dumped core.
                                                              
                                                              Stack trace of thread 3:
                                                              #0  0x00007f7e53a0c53f n/a (/usr/lib64/libc-2.28.so)
-- Subject: Process 1311 (systemd-tmpfile) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 1311 (systemd-tmpfile) crashed and dumped core.
...
```

```
# coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Tue 2018-12-11 19:26:33 UTC    1311     0     0   6 present   /usr/bin/systemd-tmpfiles

```

A stack trace that might be more useful when I tried this on my Fedora 29 host (not in a virtual machine):

```
$ journalctl -xe
Dec 11 10:18:05 comp systemd-coredump[4343]: Process 4339 (systemd-tmpfile) of user 0 dumped core.
                                             
                                             Stack trace of thread 3:
                                             #0  0x00007fd02dd6c53f raise (libc.so.6)
                                             #1  0x00007fd02dd56895 abort (libc.so.6)
                                             #2  0x00007fd02df75d5f n/a (libsystemd-shared-239.so)
                                             #3  0x00007fd02e000aa9 path_startswith (libsystemd-shared-239.so)
                                             #4  0x00007fd02dfd87a3 conf_files_insert (libsystemd-shared-239.so)
                                             #5  0x00007fd02dfd8c3a conf_files_list_with_replacement (libsystemd-shared-239.so)
                                             #6  0x000055fd5248eb2f n/a (systemd-tmpfiles)
                                             #7  0x00007fd02dd58413 __libc_start_main (libc.so.6)
                                             #8  0x000055fd5248f19e n/a (systemd-tmpfiles)
-- Subject: Process 4339 (systemd-tmpfile) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 4339 (systemd-tmpfile) crashed and dumped core.
```

**Steps to reproduce the problem**

```
$ git clone https://github.com/rfairley/fedora-coreos-config
$ cd fedora-coreos-config
$ git checkout rfairley-coredump
$ vagrant up
$ vagrant ssh

[vagrant@localhost] $ sudo su
# Switch to the CI/CD branch to get rpm-ostree at master
[root@localhost] # ostree remote add fahc --set=gpg-verify=false https://ci.centos.org/artifacts/sig-atomic/fahc/ostree/repo/
[root@localhost] # rpm-ostree rebase fahc:fahc/28/x86_64/buildmaster
[root@localhost] # systemctl reboot

$ vagrant ssh

[vagrant@localhost] $ sudo su
[root@localhost] # cd sync
# Do the compose
[root@localhost] # ostree init --repo=repo --mode=bare-user
[root@localhost] # rpm-ostree compose tree --repo=repo --unified-core ./fedora-coreos.yaml

# Watch output
```

The line in the specfile where the macro is used is as follows:

https://github.com/rfairley/console-login-helper-messages/blob/systemd-core-dump/console-login-helper-messages.spec#L91

The `console-login-helper-messages` RPM is built on COPR: https://copr.fedorainfracloud.org/coprs/rfairley/console-login-helper-messages/build/836266/

The tmpfiles in the package do get installed to the proper place, but it's possible my usage of `%tmpfiles_create_package` in `console-login-helper-messages.spec` is incorrect. In any case though, the core dump is unexpected.

First found in: https://github.com/coreos/fedora-coreos-config/pull/32#issuecomment-445392607

**Comment by rfairley** [comment]
The core dump file from `/var/lib/systemd/coredump/`: [core.systemd-tmpfile.0.ece4358331d14eb9bd07e84c12ffc4ba.1311.zip](https://github.com/systemd/systemd/files/2669337/core.systemd-tmpfile.0.ece4358331d14eb9bd07e84c12ffc4ba.1311.zip)
(uncompressed from .lz4 and compressed as .zip)

**Comment by poettering** [comment]
Is this reproducible with systemd-tmpfiles from current git? it has received a lot of fixes in this area.

/cc @keszybz

**Comment by dustymabe** [comment]
hey @poettering - it will be much easier to attempt to reproduce for robert if there is an RPM somewhere in a CI system that follows upstream pretty close. Is there a place we could pull and rpm (copr?, CI?) and test ?

**Comment by dustymabe** [comment]
> Is there a place we could pull and rpm (copr?, CI?) and test ?

or... is testing rawhide sufficient?

**Comment by poettering** [comment]
> hey @poettering - it will be much easier to attempt to reproduce for robert if there is an RPM somewhere in a CI system that follows upstream pretty close. Is there a place we could pull and rpm (copr?, CI?) and test ?

nope, we don't have that. But it should be trivial to build it from source and and do "ninja -C build install" to install it over the RPM maintained version. That's what I do for testing myself. 

Of course, that's probably something to better do on a throw-away machine than on your work laptop system itsef...

```shell
sudo dnf builddep systemd
git clone https://github.com/systemd/systemd.git
cd systemd
meson build
ninja -C build
sudo ninja -C build install
```

**Comment by filbranden** [comment]
@dustymabe I've been building RPMs from systemd development tree.

I want to turn this into a more reliable method... But for now, [this script build-rpm.sh](https://github.com/filbranden/systemd/blob/fedora1/doc/hacking/fedora/build-rpm.sh) I wrote has been doing the job.

Just check out the Fedora RPM tree (from https://src.fedoraproject.org/rpms/systemd.git) under `~/fedora-src/systemd` and then run `build-rpm.sh` on the top of the tree of systemd sources. (Just put this script anywhere in your path...)

This will produce a set of RPMs with really long names (such as `systemd-239-10.git9f3aed1.20181213101906.v239_3400_g421e3b45f03d.master.fc30.x86_64.rpm`) suitable for use with `rpm -Fvh` on.

I guess you can reproduce this same setup easily. If you can't, maybe let me know, I can build you a set of RPMs from top of tree and push them somewhere you can find.

Cheers!
Filipe

**Comment by keszybz** [comment]
> The tmpfiles in the package do get installed to the proper place, but it's possible my usage of %tmpfiles_create_package in console-login-helper-messages.spec is incorrect. 

Yes. The second argument is supposed to be an actual file in the build or source directories. The contents are supposed to be included inline in the macro definition. The part between `<<SYSTEMD_INLINE_EOF` and `SYSTEMD_INLINE_EOF` must not be empty.

Unfortunately I can't reproduce this. But if you can reproduce this on F29, then please provide a proper backtrace (with debuginfo installed). (Or at least report with what systemd.rpm version this occurs.)

**Comment by keszybz** [comment]
OK, I found the issue. Patch coming up.

**Comment by rfairley** [comment]
Thanks @keszybz - will take a look as to why the field given to the macro is being given as empty in my case. Will make sure to use debuginfo and include the rpm version (from `rpm -q systemd`) as well in future.

Thanks @poettering for the detailed build/install steps - I did try this to install master, and then `systemd daemon-reexec`, and could reproduce this. I did also try building the RPM and installing from the tree at https://src.fedoraproject.org/rpms/systemd/tree/85e1a222f7ed8e74003f781436d8a134cb4b768d with the same result (thanks @filbranden for the link and the script).

**Comment by rfairley** [comment]
Just in case it wasn't clear (as I gave two stack traces in the original comment), the stack trace from when I tried on F29 is:

>                                              Stack trace of thread 3:
>                                             #0  0x00007fd02dd6c53f raise (libc.so.6)
>                                             #1  0x00007fd02dd56895 abort (libc.so.6)
>                                             #2  0x00007fd02df75d5f n/a (libsystemd-shared-239.so)
>                                             #3  0x00007fd02e000aa9 path_startswith (libsystemd-shared-239.so)
>                                             #4  0x00007fd02dfd87a3 conf_files_insert (libsystemd-shared-239.so)
>                                             #5  0x00007fd02dfd8c3a conf_files_list_with_replacement (libsystemd-shared-239.so)
>                                             #6  0x000055fd5248eb2f n/a (systemd-tmpfiles)
>                                             #7  0x00007fd02dd58413 __libc_start_main (libc.so.6)
>                                             #8  0x000055fd5248f19e n/a (systemd-tmpfiles)

Will use debuginfo in the VM in future though - shouldn't have needed to use my host F29 to get this.
