### ISSUE TITLE
systemd-nspawn fails mounting ext2/4 with data integrity partition (dm_verity)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11123]
**systemd version the issue has been seen with**
 ```
$ systemd-nspawn --version
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Used distribution**
Debian Testing 
```
$ cat /etc/debian_version
buster/sid
 ```

**Expected behavior you didn't see**
```
$sudo systemd-nspawn --quiet --read-only -i partitions.img --root-hash eb8b4b2778909322cb617474c915b7c760cae2ba8ad9fe611783a9742289053b   helloWorld
Hello, World!
```

**Unexpected behavior you saw**
```
$sudo systemd-nspawn --quiet --read-only -i partitions.img --root-hash eb8b4b2778909322cb617474c915b7c760cae2ba8ad9fe611783a9742289053b   helloWorld
Short read while reading cgroup mode.
```

**Steps to reproduce the problem**

1. Unzip [partitions.zip](https://github.com/systemd/systemd/files/2668822/partitions.zip)
2. Call `sudo systemd-nspawn --quiet --read-only -i partitions.img --root-hash eb8b4b2778909322cb617474c915b7c760cae2ba8ad9fe611783a9742289053b  helloWorld`

**Additional Information**

In case the root hash is not provided nspawn shows the expected behavior:
```
sudo systemd-nspawn --quiet --read-only -i partitions.img   helloWorld
Note: image /home/dev/src/helloWorld/partitions.img contains verity information, but no root hash specified! Proceeding without integrity checking.
Hello, World!
```

The file `partitions.img` contains a gpt disk image with partitions according to https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/
```
$ fdisk -l -o "Name,Start,End,Size,Type,Type-UUID,UUID" partitions.img
Disk partitions.img: 20 MiB, 20971520 bytes, 40960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: B5964133-9DEF-49E7-9A0A-8B1BAB7AEE7D

Name Start   End Size Type                Type-UUID                            UUID
root  2048 20480   9M Linux root (x86-64) 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 EB8B4B27-7890-9322-CB61-7474C915B7C7
hash 22528 40926   9M unknown             2C7357ED-EBD2-46D9-AEC1-23D437EC2BF5 60CAE2BA-8AD9-FE61-1783-A9742289053B

```

**Comment by EBGeorg** [comment]
I used `veritysetup` to fill the hash partition. I suppose `veritysetup` makes use of the respective crypto features provided by the kernel.

Also:
```
$ cat /boot/config-4.18.0-2-amd64 |grep -i verity
CONFIG_DM_VERITY=m
# CONFIG_DM_VERITY_FEC is not set
```

```
$ lsmod |grep verity
dm_verity              24576  0
...
```

**Comment by poettering** [comment]
hmm, so the image looks superficially OK, and systemd-dissect is able to set up everything correctly, but then actually mounting the file system inside of it fails, i.e. mount() of the ext4 fs returns -EINVAL.

In the kernel logs this appears:

```
EXT4-fs (dm-1): bad block size 1024
```

Not sure what that means, and where that comes from.

How did you generate the image?

BTW, it's crucial you never mount the image without verity enabled in writable mode, because just mounting something updates the superblock already, and thus the verity data won#t check out anymore.

**Comment by EBGeorg** [comment]
> hmm, so the image looks superficially OK, and systemd-dissect is able to set up everything correctly, but then actually mounting the file system inside of it fails, i.e. mount() of the ext4 fs returns -EINVAL.

... should've looked there as well...
I'll try a different FS to check if I get a similar error.

> How did you generate the image?

1. Create image file with `dd`
2. Setup partitions in disk image file with `gdisk` with the correct partition types
3. Setup loopback devices with `losetup -P`
4. Create filesystem
5. Mount root partition 
6. Copy files to root partition
7. Umount root partition
8. Use `veritysetup format` to create hash tree on 'hash partition'
9. Delete loopback device
9. Set UUID of partitions in disk image file with `gdisk` to first/second half of the root hash

> BTW, it's crucial you never mount the image without verity enabled in writable mode, because just mounting something updates the superblock already, and thus the verity data won#t check out anymore.

Yeah. Figured that out already :). 

In case validation with dm-verity fails a different error message is shown:
```
Failed to decrypt image: Input/output error
```

**Comment by EBGeorg** [comment]
> I'll try a different FS to check if I get a similar error.
- Fails with ext2 (which uses the ext4 subsystem)
- Works with squashfs

Not sure if systemd is of the hook though...

**Comment by poettering** [comment]
(btw, mkosi is a tool that makes building images like this easy)

**Comment by poettering** [comment]
hmm, i wonder if there's some sector size incompat between ext2 and dm-verity that we need to take care of... weird stuff.

**Comment by EBGeorg** [comment]
> (btw, mkosi is a tool that makes building images like this easy)
Thanks for the hint. I'll give it try.

**Comment by poettering** [comment]
Did you figure anything out? Can we close this here?

**Comment by EBGeorg** [comment]
Sorry for the late answer...
I stopped investigating using ext4 as squashfs works quite fine.

**Comment by poettering** [comment]
Ok. Then lets close this for now. Of there's interest in figuring out what is going on please reopen.

**Comment by jluebbe** [comment]
It also had this symptom. The solution was to create the ext4 image with block size 4k (`-b 4096` for mkfs.ext4).

**Comment by leitogithub** [comment]
> It also had this symptom. The solution was to create the ext4 image with block size 4k (`-b 4096` for mkfs.ext4).

you are good
