### ISSUE TITLE
journalctl json and json-pretty missing commas between objects

### ISSUE THREAD

**Issue by hasenbalg** [systemd/systemd#11120]
**systemd version the issue has been seen with**
>238

**Used distribution**
 > Fedora 28

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 >json output of `journalctl -o json`and `journalctl  -o json-pretty` is malformed. commas are missing between the objects and surrounding brackets

**Steps to reproduce the problem**
>run `journalctl -o json` and paste the output to e.g. https://jsonformatter.curiousconcept.com/

**Comment by poettering** [comment]
it's a stream of json objects, but not an object itself. Modelling something that inherently is a stream as a single object is highly problematic, as json parsers are almost always implemented in a dom-style, and not a stream-style if you so wish.

I mean, there are reasons why concepts like "json-seq" exists, and it doesn't use a single object either for modelling things.

**Comment by hasenbalg** [comment]
Ok, thanks!
