### ISSUE TITLE
Not getting a login prompt on console with systemd

### ISSUE THREAD

**Issue by coveritytest** [systemd/systemd#11133]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Kernel log and serial console login prompt on the very same physical serial console.

**Unexpected behaviour you saw**
 > If I start the kernel with the cmdline parameters console=ttyS5,115200 console=tty1 systemd.journald.forward_to_console=1 I do see all the kernel messages from /dev/kmsg and systemd logs, but I never see a login prompt. If I omit console=tty1 the kernel log is still beeing printed, but the systemd logs appear with a 30 seconds timeout for each line.

**Steps to reproduce the problem**

**Comment by poettering** [comment]
systemd-getty-generator would normally invoke a serial getty on each non-VC tty listed in /sys/class/tty/console/active. What does that file list for you?

Where do you never see a login prompt? on the VC or on the serial port?

**Comment by coveritytest** [comment]
If I write a service that does

`#!/bin/sh

/bin/cat /sys/class/tty/console/active > /dev/kmsg`

I get the output:

ttySC5 tty1
ttySC5 tty1
ttySC5 tty1
ttySC5 tty1
ttySC5 tty1

Oddly it's beeing printed 5 times. I have to remark, that I'm on an embedded system.

**Comment by poettering** [comment]
hmm, "ttySC5" looks like a strange kind of device. Note that systemd-getty-generator "validates" serial devices before generating units for them. Maybe that device doesn't pass muster?

https://github.com/systemd/systemd/blob/master/src/getty-generator/getty-generator.c#L78

**Comment by poettering** [comment]
but dunno, check if a serial getty instance got generated in /run/systemd/generator*

**Comment by coveritytest** [comment]
I have a system with a ttySC4 which works just fine, when using only 

> console=ttySC4,115200

I just checked, it creates a file /run/systemd/generator/serial-getty@ttySC5.service.

**Comment by coveritytest** [comment]
> 
> 
> systemd-getty-generator would normally invoke a serial getty on each non-VC tty listed in /sys/class/tty/console/active. What does that file list for you?
> 
> Where do you never see a login prompt? on the VC or on the serial port?

I don't see a login prompt on the serial port, where I expected both kernel logs and the login prompt. But apparently I only see what's in /dev/kmsg on the serial port. Which means, that the serial console per se works.

**Comment by poettering** [comment]
> I have a system with a ttySC4 which works just fine, when using only
> 
> > console=ttySC4,115200
> 
> I just checked, it creates a file
> 
> > /run/systemd/generator/serial-getty@ttySC5.service

Hmm, ttySC4 or ttySC5?

**Comment by poettering** [comment]
> I don't see a login prompt on the serial port, where I expected both kernel logs and the login prompt. But apparently I only see what's in /dev/kmsg on the serial port. Which means, that the serial port per se works.

And did a serial-getty@.service instance get started for it? did the generator create the service? what does systemctl status say about such an instance?

**Comment by poettering** [comment]
are ttySCx ports properly tagged with "systemd" in udev?

**Comment by coveritytest** [comment]
> 
> 
> > I have a system with a ttySC4 which works just fine, when using only
> > > console=ttySC4,115200
> > 
> > 
> > I just checked, it creates a file
> > > /run/systemd/generator/serial-getty@ttySC5.service
> 
> Hmm, ttySC4 or ttySC5?

Sorry that was confusing. I meant that the same filesystem works with another embedded device that uses ttySC4. In the current embedded device which differs a bit, ttySC5 is used, which fails. And in this current device

> /run/systemd/generator/serial-getty@ttySC5.service

is created. I proofed this by creating a service that does this:

`ls /run/systemd/generator/ > /dev/kmsg`

**Comment by coveritytest** [comment]
I just checked

> ps aux > processes

gives this output

`USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 28.5  3.4  11188  6336 ?        Ss   13:11   0:03 /sbin/init
...
root       583  4.7  4.3  25388  8020 ?        Ss   13:11   0:00 /lib/systemd/systemd-journald
...
root       598  0.1  0.2   1472   400 tty9     Ss+  13:11   0:00 /bin/sh
root       846  7.0  2.4  18488  4532 ?        Ss   13:11   0:00 /lib/systemd/systemd-udevd
systemd+  1013  3.6  1.2  18456  2220 ?        Ssl  13:11   0:00 /lib/systemd/systemd-timesyncd
root      1039  2.0  1.1   9056  2068 ?        Ss   13:11   0:00 /lib/systemd/systemd-logind
root      1042  0.3  0.8   2704  1496 ?        Ss   13:11   0:00 /usr/sbin/cron -f
root      1045  1.3  1.4  25704  2740 ?        Ssl  13:11   0:00 /usr/sbin/rsyslogd -n -iNONE
message+  1057  3.6  1.4   6784  2732 ?        Ss   13:11   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root      1080  2.5  2.5  10336  4636 ?        Ss   13:11   0:00 /usr/sbin/sshd -D
root      1083  0.5  0.5   1560  1080 ttySC5   Ss+  13:11   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttySC5 vt220
...
root      1109  0.0  0.2   1472   380 ?        Ss   13:11   0:00 /bin/sh /usr/local/bin/myservice
root      1112  0.0  1.1   6292  2040 ?        R    13:11   0:00 /bin/ps aux`

**Comment by poettering** [comment]
> root      1083  0.5  0.5   1560  1080 ttySC5   Ss+  13:11   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttySC5 vt220

So the getty gets started? If you don't see the prompt on the terminal, then it's somewhere between that getty and the kernel driver for that serial port...

systemd is not involved anymore at that point. or what am I missing?

**Comment by coveritytest** [comment]
Yeah, seems so. I guess I have to dig deeper here. Serial interface as such seems to work, otherwise I wouldn't see the printks. Thanks for your time.
