### ISSUE TITLE
[RFC] pid1: possibly wrong code ordering in execute.c

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#11162]
**systemd version the issue has been seen with**
systemd-239

**Used distribution**
Fedora

**Unexpected behaviour you saw**
I didn't observe any issues per say but we may have been just lucky until now that kernel delivered wake-up to journald always after the migration (possibly due to ```execve()```)

**Steps to reproduce the problem**

I think we have a potential problem in ```execute.c``` in the child process setup code. Basically, we first connect child process to journal and then we do cgroup migration. I don't think this is correct. journald looks up cgroup of the logging client by looking at ```/proc/PID/cgroup``` first and only if that is not available it falls back to ```unit_id``` provided by the client.

I think we should put 
```C
        if (params->cgroup_path) {
                _cleanup_free_ char *p = NULL;

                r = exec_parameters_get_cgroup_path(params, &p);
                if (r < 0) {
                        *exit_status = EXIT_CGROUP;
                        return log_unit_error_errno(unit, r, "Failed to acquire cgroup path: %m");
                }

                r = cg_attach_everywhere(params->cgroup_supported, p, 0, NULL, NULL);
                if (r < 0) {
                        *exit_status = EXIT_CGROUP;
                        return log_unit_error_errno(unit, r, "Failed to attach to cgroup %s: %m", p);
                }
        }
```
before ```setup_input()``` at https://github.com/systemd/systemd/blob/master/src/core/execute.c#L3031

If this is valid I'd be happy to submit a PR with the fix.

**Comment by poettering** [comment]
True, this sshould be swapped. And please add a comment to an appropriate place, explaining why cgroup stuff needs to come first!

**Comment by poettering** [comment]
@msekletar if you prep a patch quickly we can still put it in v240
