### ISSUE TITLE
TEST-13-NSPAWN-SMOKE seems to be failing under KVM

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#11173]
**systemd version the issue has been seen with**
> 239 (latest master)

**Used distribution**
 > CentOS 7.6

In attempts to further improve the CentOS CI, I'd like to run the integration test suite under both systemd-nspawn and KVM (systemd/systemd-centos-ci#29). However, there's a one test, which keeps failing under KVM (TEST-13-NSPAWN-SMOKE).

```
...
Remounting /nc-container/sys/fs/cgroup/cpuset (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /nc-container/sys/fs/cgroup/systemd (MS_NOSUID|MS_NODEV|MS_NOEXEC "none,name=systemd,xattr")...
Remounting /nc-container/sys/fs/cgroup (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_STRICTATIME "mode=755")...
Failed to fork inner child: Invalid argument
(sd-namespace) failed with exit status 1.
[[0;1;31mFAILED[0m] Failed to start [0;1;39mTestsuite service[0m.
See 'systemctl status testsuite.service' for details.
```

Full log: https://ci.centos.org/job/systemd-ci-build/32/artifact/artifacts_agNShu/testsuite-logs.DBo/TEST-13-NSPAWN-SMOKE-kvm.log
CI job: https://ci.centos.org/job/systemd-ci-build/32/

**Comment by evverx** [comment]
Judging by the error message, It seems to be a variation of the issue that can be fixed with https://github.com/systemd/systemd-centos-ci/commit/4f068d8558221aabeb9082f5c36653a1dad3f7c9 and https://github.com/systemd/systemd-centos-ci/commit/8d862f2bc5d2c1af5aa038c4392c7e6b6e863c03.

**Comment by mrc0mmand** [comment]
> 
> 
> Judging by the error message, It seems to be a variation of the issue that can be fixed with [systemd/systemd-centos-ci@4f068d8](https://github.com/systemd/systemd-centos-ci/commit/4f068d8558221aabeb9082f5c36653a1dad3f7c9) and [systemd/systemd-centos-ci@8d862f2](https://github.com/systemd/systemd-centos-ci/commit/8d862f2bc5d2c1af5aa038c4392c7e6b6e863c03).

I totally forgot it's not present in the KVM, thanks for pointing that out (and sorry for the noise).

**Comment by mrc0mmand** [comment]
Well, I tried to write a small patch for the failing test, but there's apparently something obvious I keep missing...

So, here's the (currently non-working) patch:
```patch
diff --git a/test/TEST-13-NSPAWN-SMOKE/test.sh b/test/TEST-13-NSPAWN-SMOKE/test.sh
index 75e214c008..f27ee9a3cf 100755
--- a/test/TEST-13-NSPAWN-SMOKE/test.sh
+++ b/test/TEST-13-NSPAWN-SMOKE/test.sh
@@ -4,6 +4,11 @@
 set -e
 TEST_DESCRIPTION="systemd-nspawn smoke test"
 TEST_NO_NSPAWN=1
+# if user namespaces are supported on the host, enable them
+# in the VM/container as well
+if unshare -U sh -c :; then
+    KERNEL_APPEND="user_namespace.enable=1"
+fi
 
 . $TEST_BASE_DIR/test-functions
 
@@ -12,6 +17,7 @@ test_setup() {
     mkdir -p $TESTDIR/root
     mount ${LOOPDEV}p1 $TESTDIR/root
 
+
     # Create what will eventually be our root filesystem onto an overlay
     (
         LOG_LEVEL=5
@@ -72,6 +78,7 @@ fi
 is_user_ns_supported=no
 if unshare -U sh -c :; then
     is_user_ns_supported=yes
+    sysctl -w user.max_user_namespaces=10000
 fi
 
 function check_bind_tmp_path {
```

The `user_namespace.enable=1` is correctly appended to the kernel command line inside of the VM (according to journal and `/proc/cmdline`), however the `unshare` syscall still fails:

```
+ strace unshare -U sh -c :
execve("/usr/bin/unshare", ["unshare", "-U", "sh", "-c", ":"], [/* 8 vars */]) = 0
...
open("/usr/lib/locale/C.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/C.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/C/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
unshare(CLONE_NEWUSER)                  = -1 EINVAL (Invalid argument)
write(2, "unshare: ", 9unshare: )                = 9
write(2, "unshare failed", 14unshare failed)          = 14
write(2, ": ", 2: )                       = 2
write(2, "Invalid argument\n", 17Invalid argument
)      = 17
close(1)                                = 0
close(2)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

I'm not even sure if I'm trying to fix it on the correct side, so any guidance in my enlightenment is definitely welcome.

**Comment by evverx** [comment]
I'm afraid I can't help here right now because what I see is a little bit worse than `unshare`:
```
[  110.720567] BUG: unable to handle kernel NULL pointer dereference at 0000000000000102
[  110.721000] IP: [<ffffffff918b7b02>] __queue_work+0x32/0x3e0
[  110.721000] PGD 0
[  110.721000] Oops: 0000 [#1] SMP
[  110.721000] Modules linked in:
[  110.721000] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 3.10.0-957.1.3.el7.x86_64 #1
[  110.721000] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 0.5.1 01/01/2011
[  110.721000] task: ffffa0551d478000 ti: ffffa0551d4f0000 task.ti: ffffa0551d4f0000
```
:-) I'll try to take a closer look on Monday.

In the meantime, could you try passing `KERNEL_APPEND="user_namespace.enable=1` explicitly when you run the test with `make run KERNEL_APPEND=...` to see how it goes?

**Comment by mrc0mmand** [comment]
Unfortunately, it didn't help, the `unshare` error is still present (for the reference, I'm running the test using `make -C test/TEST-13-NSPAWN-SMOKE/ clean setup run KERNEL_APPEND="user_namespace.enable=1"`). I tried even editing the `KERNEL_APPEND` (and various other variables) directly in the `test/test-functions` file, but to no avail.

**Comment by mrc0mmand** [comment]
Thank you, @evverx! Until now I thought the `unshare` syscall would work *prior* to `sysctl -w user.max_user_namespaces=10000` (i.e. ony with `user_namespace.enable=1`), but as I can see I was mistaken. Editing my proposed patch appropriately the `TEST-13-NSPAWN-SMOKE` finally passes!

I'll open an PR shortly.
