### ISSUE TITLE
LINK_SEARCH_DOMAINS_MAX too small for some VPNs

### ISSUE THREAD

**Issue by iainlane** [systemd/systemd#11175]
**systemd version the issue has been seen with**
239

**Used distribution**
Ubuntu disco

**Expected behaviour you didn't see**
Working name resolution of internal DNS names over my VPN.

**Unexpected behaviour you saw**
Non-working - the internal DNS server isn't queried, because the search domains haven't been set - see below.

**Steps to reproduce the problem**
Use NetworkManager to connect to a VPN that provides more than 32 domain suffixes.

**What happens**
NetworkManager duly hands everything it gets off to `SetLinkDomains`, but they aren't applied because `LINK_SEARCH_DOMAINS_MAX` is set to 32. It gets `-E2BIG` back.

This is my company VPN. It advertises many internal network segments, and also `in-addr.arpa` suffixes for reverse dns for a few different subnets. In total there are more than 32 of them.

Would there be a problem with bumping this limit up?

**Comment by ssahani** [comment]
should be configurable . RFE

**Comment by poettering** [comment]
This is merely a safety limit to us. Let's bump it substantially higher, so that it never can conflict with real-life setups. For now I prepped PR #11184 which bumps it to 256. I hope that's high enough for your setup?

**Comment by iainlane** [comment]
Thanks! Yeah, I think it's actually 39 in our case. Something which nobody will realistically hit is a fine solution.
