### ISSUE TITLE
Coverity Scan hasn't analyzed the code since the beginning of January

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11185]
This is mostly a reminder that the cron job sending data to Coverity Scan should be turned on when it gets better.

~~Currently Coverity is having trouble analyzing builds: https://community.synopsys.com/s/question/0D53400004UEpchCAD/submitting-builds-appears-to-return-a-404, https://community.synopsys.com/s/question/0D53400004TCWI4CAP/whats-occupying-build-queue-right-now-i-see-there-are-183-builds-ahead-of-it-does-it-mean-our-project-made-that-many-submissions-or-build-queue-is-shared-between-different-projects and https://community.synopsys.com/s/question/0D53400004TGHG9CAP/is-coverity-scan-dead.~~

https://community.synopsys.com/s/article/Coverity-Scan-Update

> What’s happening to Coverity Scan?
On Monday, January 7, 2019 our team was notified that our Coverity Scan hosting service provider unexpectedly ceased operations, making the servers that support Scan unavailable. We are working to stand up new servers to restore the service as soon as possible. We apologize for any inconvenience.

**Comment by evverx** [comment]
I'm wondering what happens with the badge if the criteria from https://bestpractices.coreinfrastructure.org/en/projects/1369#analysis aren't met.

**Comment by evverx** [comment]
Not that it matters but we could check "dynamic_analysis_unsafe" (there're 20 fuzzers after all) and "static_analysis_often" (we send data to coverity every day when it works).

**Comment by keszybz** [comment]
I updated the CII report for systemd a bit. We improved on a number of metrics over the last year.

**Comment by filbranden** [comment]
Unfortunately, it looks like #9183 is back though :-(

Lots of false positives with assert_se()...

I'll consider reopening that one and following up on the Coverity forum message I have about that.

**Comment by evverx** [comment]
I wouldn't say #9183 is back. It's just that Coverity doesn't like it when an assignment operator is used in a condition. I'm not sure why it marked those assertions as "Side effect in assertion" given that the help messages says that "Did you intend to use a comparison ("==") instead?". I usually simply use `a = ...; assert_se(a);` so as not to trigger it.

**Comment by evverx** [comment]
If it is #9183 it seems to have been back since the beginning of August: https://scan6.coverity.com/reports.htm#v36250/p10110/fileInstanceId=87505452&defectInstanceId=26840718&mergedDefectId=1394611.

**Comment by keszybz** [comment]
Yeah, I have been marking them as "dismissed", and they have been happening regularly as far as I can remember. Maybe we should remove the workaround from #9183 since it isn't helping?

**Comment by evverx** [comment]
As far as I understand, it worked when @filbranden manually built the code and send it to Coverity Scan. As soon as Travis CI started to do it automatically, it appears to have stopped working. @filbranden did you use `tools/coverity.sh`? Could it be that `tools/coverity.sh` should be tweaked a bit somehow to make everything work again?

**Comment by evverx** [comment]
To judge from https://twitter.com/CoverityScan/status/1082446527493066752 and https://travis-ci.org/systemd/systemd/jobs/477159173 Coverity Scan is broken again. I'm going to turn cron jobs off.

**Comment by evverx** [comment]
https://community.synopsys.com/s/article/Coverity-Scan-Update
> What’s happening to Coverity Scan? 
On Monday, January 7, 2019 our team was notified that our Coverity Scan hosting service provider unexpectedly ceased operations, making the servers that support Scan unavailable. We are working to stand up new servers to restore the service as soon as possible. We apologize for any inconvenience.

**Comment by evverx** [comment]
1/25/19 Update: Coverity Scan is back up and running in read-only mode. This means you can access your previous scan projects. We have re-built Scan using a cloud platform that will reduce dependencies and hopefully improve overall performance. We expect to be ready for new projects within the next few days once the final migration work is complete. We thank you for your patience as we work to make the platform better. For any questions in the mean time, please email sig-scan-admin@synopsys.com.

**Comment by evverx** [comment]
[The last cron job](https://travis-ci.org/systemd/systemd/jobs/493173440) has successfully sent data to Coverity Scan but it's unclear whether the build was analyzed or not.

**Comment by evverx** [comment]
Looks like it wasn't. Probably that part of Coverity Scan isn't fully operational yet. I'll close the issue once it gets better.

**Comment by evverx** [comment]
Yesterday Coverity Scan got stuck and I terminated the analysis manually. Now although its UI keeps sending mixed signals it seems to be working so I'm closing the issue.
