### ISSUE TITLE
udevadm: attribute walk fails if called with syspath where corresponding kobject doesn't expose uevent attribute

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#11183]
**systemd version the issue has been seen with**
* systemd-239

**Used distribution**
 * Fedora

**Expected behaviour you didn't see**
 * Usual ```udevadm info -a``` output

**Unexpected behaviour you saw**
 * ```syspath not found```

**Steps to reproduce the problem**
* ``` udevadm info -a --path /sys/class/block/sda/queue ```

**Additional information**
To be honest I am not sure if this is a bug because previously we printed sysfs attributes of an object that is actually not device.

Udev code now uses symlink chasing routines from systemd. ```/sys/class/block/sda/queue``` is a directory and not a symlink, however, we resolve eventually resolve it (by dereferencing symlinks along the path) to syspath that starts with ```/sys/devices```. Because resulting syspath starts with ```/sys/devices/``` prefix we assume that uevent attribute is present. However ```queue``` directory is missing the attribute. Looking at kernel source ```queue``` never exposed ```uevent``` but in the past we used less smart symlink chasing algorithm which did nothing to original syspath pointing to directory.

https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-device/sd-device.c#L176

```
access("/sys/devices/pci0000:00/0000:00:0d.0/ata3/host2/target2:0:0/2:0:0:0/block/sda/queue/uevent", F_OK) = -1 ENOENT (No such file or directory)
write(2, "syspath not found\n") = 18
```

**Comment by poettering** [comment]
I am not convinced this is really a bug, because such a path doesn't refer do a device...

**Comment by msekletar** [comment]
Shouldn't we then skip it and continue handling other devices up the syspath?

**Comment by keszybz** [comment]
The argument is documented as "The /sys path of the device to query, e.g.  [/sys]/class/block/sda.". I get the error: `Unknown device "/sys/class/block/sda/queue": No such device`. Looks correct to me.

**Comment by msekletar** [comment]
Fair enough...
