### ISSUE TITLE
Incomplete group list in DBus-initiated systemd --user session

### ISSUE THREAD

**Issue by dargad** [systemd/systemd#11198]
Tested on:
* Fedora 29
* Ubuntu 18.04 & 18.10

Steps to reproduce (tested on Fedora & Ubuntu):
1. Add entry to `/etc/security/group.conf`
```
*;*;*;Al0000-2400;dialout
```
2. Add pam_groups entry to `/etc/pam.d/gdm-password` &
`/etc/pam.d/systemd-user`:
```
auth    optional    pam_group.so
```
3. Login to Gnome.
4. Start gnome-terminal & check groups the user belongs to with `id`.

Expected result:
User's groups consist of the /etc/group and extra pam_group entries.

Actual result:
Groups that should be added according to `/etc/security/group.conf` are missing.

This is caused by the way gnome-terminal is launched: a minimal binary reaches out to DBus service org.gnome.Terminal on the session bus. If it is not running (and this is the case after logging in) the responsible process (gnome-terminal-server in this case) is launched under `systemd --user` and displays the UI.

In that context PAM config is read from `/etc/pam.d/systemd-user` - even if it find pam_group entry there it doesn't change anything, since pam_sm_setcred function of the module that parses the `/etc/security/group.conf` file and sets up the groups is not called. For that to happen in the PAM setup process applications needs to call the pam_setcred function before opening a
session.

In case of terminal emulators with more "standard" launch procedure (like xterm) the behavior is as expected (groups are there), but this issue may include all DBus-triggered processes that need to utilize extra groups.

**Comment by keszybz** [comment]
A patch would be welcome.

**Comment by poettering** [comment]
Let's close as #11199 has been merged.
