### ISSUE TITLE
Shortcomings with autopkgtest Ubuntu CI

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#11195]
Opening this issue since I believe the autopkgtest Ubuntu CI has been source of issues that, at least in part, make some developers lose confidence and pay less attention to the CI status, in some cases contributing to merging bad PRs even though the CI actually caught the bugs.

I think most of the issues stem from the large log file produced by it, which takes a long time to load and is cumbersome to work with in a browser tab...

Personally, I'd cite these as areas where the autopkgtest integration could be improved:

1. Report a summary of passes/failures, so we can quickly know which of the tests failed.

Right now, when it fails, our only option is to open the log file (wait until it fully loads), then scroll to the bottom to see the summary:

```
boot-smoke           PASS
autopkgtest [22:10:28]: @@@@@@@@@@@@@@@@@@@@ summary
timedated            PASS
hostnamed            PASS
localed-locale       PASS
localed-x11-keymap   PASS
logind               PASS
unit-config          PASS
storage              PASS
networkd-test.py     PASS
build-login          PASS
boot-and-services    PASS
udev                 PASS
root-unittests       PASS
upstream             FAIL timed out
boot-smoke           PASS
```

Ah ok, so "upstream" tests timed out... Maybe we can rule that as a flake quickly and just ignore it, but it took me a long time (and slowed down my browser significantly) just to get that information... Can we just export that summary in a page we can quickly look at to see *which* tests failed and *why* (at least a high level "error" vs. "broken" vs. "timeout" etc.)?

2. Split log details per test.

So, again, if the only problem was "upstream FAIL timed out", it would be best if I could concentrate on the snippets relevant to that particular part of the test... Can we split the log into separate logs for each part of the test, so we can concentrate on that one only when investigating the failures?

3. (optional) Perhaps even each part is too big?

Maybe it would be useful to be able to even summarize each part that failed, perhaps grepping for strings like "error" or "fail" or "timeout" with a few lines of context and present that first as an overview of failures (perhaps the problem is already apparent from there?)

4. (important!) Ability to relaunch a test.

Sometimes there are flakes... So re-running would be nice. Right now there's not really a good way to relaunch a test. (Well, we can amend a commit just to change the SHA1 through the timestamp and do a force-push... But that's silly if all we want to do is rerun a single autopkgtest.)

Would it be possible to have a way to request a re-run in case of failure?

5. Takes too long...

But I guess that's a hard one to tackle, unless we can get more dedicated infrastructure to keep running these tests...

---

As an example, Travis-CI implements most of those. The screenshot below shows an example of Travis-CI for a failed commit, it's easy to tell the problem was a memory leak (or something similar) since the "ASan" tests were the ones that failed... It's also easy to deal with sporadic flakiness, since there's a "restart job" button for each specific job (and there's also a way to restart all of them), so we don't need to re-push to re-run a test we suspect might succeed on a second try...

<img width="911" alt="travis-ci" src="https://user-images.githubusercontent.com/106037/50129841-b383f980-022f-11e9-8570-dad9123e33d0.png">

---

Another question is whether the autopkgtests are still catching bugs that aren't really caught by other tests, whether it's really that important that we keep running them (or, at least, keep running them for each PR, instead of maybe only nightly...)

Anyways, just trying to get some constructive feedback on how we might be able to make this set of tests easier to interact with.

/cc @evverx, who I know cares about this issue. Also /cc @martinpitt and @mbiebl who I believe keep these tests running.

**Comment by cdown** [comment]
At the very least, I can say that even after a little while contributing to systemd, it still takes me often 5+ minutes to find the actual failure in autopkgtests.

**Comment by mbiebl** [comment]
fwiw, I agree that the huge, single log file makes the CI results difficult to use.
autopkgtest itself is actually able to break down the logs in separate files. If I run it manually, this is what I get:
```
$ ls -sh logs/ 
total 16M
4.0K binaries
8.0K boot-and-services-packages
4.0K boot-and-services-stdout
 12K boot-smoke-packages
4.0K boot-smoke-stdout
4.0K build-login-packages
4.0K build-login-stdout
4.0K hostnamed-packages
4.0K hostnamed-stdout
4.0K localed-locale-packages
4.0K localed-locale-stdout
4.0K localed-x11-keymap-packages
7.7M log
4.0K logind-packages
4.0K logind-stdout
4.0K networkd-test.py-packages
4.0K networkd-test.py-stdout
4.0K root-unittests-packages
3.2M root-unittests-stderr
1.4M root-unittests-stdout
4.0K storage-packages
4.0K storage-stdout
4.0K summary
4.0K systemd-fsckd-packages
4.0K systemd-fsckd-stdout
8.0K testbed-packages
4.0K testinfo.json
4.0K testpkg-version
4.0K timedated-packages
4.0K timedated-stdout
4.0K udev-packages
4.0K udev-stderr
 28K udev-stdout
4.0K unit-config-packages
4.0K unit-config-stderr
4.0K unit-config-stdout
4.0K upstream-packages
100K upstream-stderr
2.6M upstream-stdout

$ cat logs/summary 
timedated            PASS
hostnamed            PASS
localed-locale       PASS
localed-x11-keymap   PASS
logind               PASS
unit-config          PASS
storage              PASS
networkd-test.py     FAIL non-zero exit status 1
build-login          PASS
boot-and-services    PASS
udev                 PASS
root-unittests       PASS
upstream             PASS
boot-smoke           PASS
systemd-fsckd        PASS
```
I guess having access to the individual files would already go a long way to make this more accessible.
That said, I dunno how the Ubuntu CI system works and if it's possible to get those files.
@xnox and @martinpitt will most likely know.

**Comment by evverx** [comment]
I think Ubuntu CI is ignored because it fails more often than not, which is the source of that continuous fatigue, so to speak. As far as I know, that happens due to the flakiness of the upstream test and, technically, has nothing to do with Ubuntu CI. The test should be either fixed (which is unlikely to happen) or just skipped as [on CentOS CI](https://github.com/systemd/systemd-centos-ci/pull/29). As for Ubuntu CI specific issues, it would be nice to figure out what's going on in https://github.com/systemd/systemd/issues/11104 and either turn arm64 off until it's done or skip the test there.

I doubt the UI can be improved drastically anytime soon but in theory it shouldn't be critical as long as it is green.

**Comment by filbranden** [comment]
> As far as I know, that happens due to the flakiness of the upstream test [...]
> The test should be either fixed (which is unlikely to happen) [...]

Is there an issue for the flakiness in the "upstream" test?

Otherwise, I fully agree with your comments, we should probably just skip it in Ubuntu CI for now, especially since we're also skipping it in CentOS CI.

(Also, so we're on the same page, the "upstream" test is covered by something else, like Travis CI for example, is my understanding correct here?)

**Comment by evverx** [comment]
The upstream test runs the tests from `test/TEST-*`. Some of them along with the code they supposedly check (where various timeouts are used) are expected to be flaky as in https://github.com/systemd/systemd/commit/3edc0c590d3a9212267d0a7cf56e95efa7f61039, so there is no point in running them in VMs or containers. TEST-02-CRYPTSETUP fails due to a race of some kind which is referred to at https://github.com/systemd/systemd/issues/10093.

Travis CI doesn't run those tests but it's safe to say that the working subset is going to be run on CentOS CI but running them on as many platforms as possible would still be useful.

**Comment by evverx** [comment]
It seems that the upstream test can be skipped altogether by removing https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/control#L112-144. Could anyone do that?

I've just turned off the webhook running the tests on arm64. Given that the test has been failing there for months and nobody apparently cares what's going on there I don't think anyone is going to be upset. If anyone thinks it should be turned on again just let me know.

**Comment by evverx** [comment]
Just to clarify, #11104 was opened just 9 days ago but the issue itself is older than that as can be seen in, for example, https://github.com/systemd/systemd/pull/10669#issuecomment-437467409.

**Comment by martinpitt** [comment]
@mbiebl: All the individual files and artifacts are actually exported, just not very visible. You can replace "log.gz" with "artifacts.tar.gz" in a result URL, see  https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/

@evverx: Do you want me to disable the *entire* upstream test  suite, or just blacklist an individual test or  two that are flaky?

**Comment by evverx** [comment]
@martinpitt I think it would be better to just skip some tests like test/TEST-02-CRYPTSETUP and test/TEST-16-EXTEND-TIMEOUT because they're 100% flaky. The problem is that I stopped tracking what else is failing there so I can't say which tests should also be skipped. It's not hard to monitor what's going on there and turn them off one by one but I'm not sure who is willing to do that.

**Comment by martinpitt** [comment]
Ack, I disabled these two for now: https://salsa.debian.org/systemd-team/systemd/commit/2c194b155b1e97e . If there are more, I'm happy to adjust further.

**Comment by evverx** [comment]
@martinpitt thank you! Would it possible to skip __main__.JournalTest on arm64 so that I could turn it on again (because skipping all the tests on arm64 is overkill)?

**Comment by evverx** [comment]
Anyway, with those two tests skipped and bionic-arm64 turned off, Ubuntu CI is likely to become green and less flaky soon which hopefully should make it hard to keep ignoring it.

**Comment by keszybz** [comment]
> 4. (important!) Ability to relaunch a test.

We can do that already, but it requires privileges. I can do that, just put a request in a comment and mention me.

**Comment by mbiebl** [comment]
> @mbiebl: All the individual files and artifacts are actually exported, just not very visible. You can replace "log.gz" with "artifacts.tar.gz"

Nice! Having to download the complete .tar.gz and unpacking it manually is still a bit cumbersome, though. Would be great if such tarballs could be uncompressed on the fly.

**Comment by filbranden** [comment]
>> @mbiebl: All the individual files and artifacts are actually exported, just not very visible. You can replace "log.gz" with "artifacts.tar.gz"
>
> Nice! Having to download the complete .tar.gz and unpacking it manually is still a bit cumbersome, though. Would be great if such tarballs could be uncompressed on the fly.

So I think the main issue I have with it is that the links we have from GitHub point to the "log.gz" file which is really big and slow to load...

Can we redirect that to, say, an HTML page that would include the summary (so we can already tell which of the tests failed at a high level, and for which reason, e.g. time out) and then include links to the full logs (the "log.gz") or the full artifacts (tarball) in which case we *know* we're looking at digging deeper and we're probably doing it from a shell / less / etc.?

Thanks!
Filipe

**Comment by evverx** [comment]
@martinpitt  to judge from https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20181219_144448_a9df3@/log.gz and https://github.com/systemd/systemd/issues/10274, TEST-17-UDEV-WANTS could be skipped too.

**Comment by evverx** [comment]
Judging by https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/i386/s/systemd-upstream/20181219_171124_87f7e@/log.gz, the test can hit the global timeout on the Ubuntu CI side. I'm not sure what to do about it.

**Comment by evverx** [comment]
@filbranden I'm sorry. It seems that I'm kind of hijacking the issue. Is it OK or would it be better to keep discussing the UI here and open another issue to track all those failures?

**Comment by filbranden** [comment]
@evverx No this is totally fine! Please continue discussion here. I think at this point if we get some improvement that doesn't make tests get ignored anymore, we've solved an issue. We can go back and address some of the harder to address points later on... Cheers!

**Comment by martinpitt** [comment]
@evverx : Wrt. the global timeout, in that log it just looks like TEST-13-NSPAWN-SMOKE hung forever. I doubt that it makes sense to wait even longer than 2:10 hours, these tests should usually just take a minute or two at the most.

I blacklisted TEST-17-UDEV-WANTS as well. However, note that IMHO it's better to control these upstream instead of downstream, as you can go via PRs that run CI.
