### ISSUE TITLE
Regression: TEST-02-CRYPTSETUP fails

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11209]
Since 89f9752ea08f516b5d77f8e577bb772073c70c01 was merged, 
TEST-02-CRYPTSETUP fails here (amd64, Debian sid).

Commit fcfb1f775ed0e9d282607bb118ba788b98952855 did not help.

Reverting both commits makes the test pass again.

**Comment by evverx** [comment]
> Reverting both commits makes the test pass again.

I don't think this is entirely correct because the test is [flaky](https://github.com/systemd/systemd/issues/10093) and regularly failed on Ubuntu CI until it was finally turned off today. It could be that those two commits make the race mentioned in that issue more likely to happen.

**Comment by mbiebl** [comment]
It is certainly correct here. I get 100% failure rate with both commits applied and 100% success rate without them.

**Comment by evverx** [comment]
@mbiebl I didn't mean to say that it isn't a regression or anything like that. What I was trying to say that it's possible to hit at least two different issues trying to reproduce this.

**Comment by mbiebl** [comment]
Fwiw, I have no idea if the two commits are the root cause or simply make an underlying problem much more apparent. The result though is that on my system this test now fails reliably.

**Comment by mbiebl** [comment]
I suspect it's a race somewhere (if in the test or an actual bug, no idea). The system is currently pretty busy doing other stuff. That it's more prone to fail on arm64 CI, which I suspect is run on powerful systems, would also hint in that direction.
