### ISSUE TITLE
os-release(5) has outdated reference to CPE

### ISSUE THREAD

**Issue by bjh21** [systemd/systemd#1121]
(forwarded from https://bugs.debian.org/797768)

os-release(5) includes this description of the "CPE_NAME" parameter:

```
   CPE_NAME=
       A CPE name for the operating system, following the Common Platform
       Enumeration Specification[2] as proposed by the MITRE Corporation.
       This field is optional. Example:
       "CPE_NAME="cpe:/o:fedoraproject:fedora:17""
```

This example name seems to be formatted according to CPE 2.2, which specified a single URI-like textual format for CPE Names.  CPE 2.2 was superseded in August 2011 by CPE 2.3, which specifies an abstract CPE Name and two different textual bindings.  By simply referring to "A CPE name", os-release(5) fails to specify which of these formats is meant.

I'd suggest that the reference be updated to either explicitly refer to the URI binding of a CPE name for the operating system, or to explicitly refer to CPE 2.2. Since CPE 2.3 URI bindings are meant to be backward-compatible with CPE 2.2, I'd suggest that the former is the better approach.

As of CPE 2.3, it seems that NIST have taken over maintenance of CPE, so the reference to MITRE should probably be replaced by a reference to NIST, and the Web reference changed to point to http://scap.nist.gov/specifications/cpe/.

**Comment by dvdhrm** [comment]
Suggestions for a better wording?

I assume you want to make clear it's a URI-binding, not a WFN. How about this:

```
   CPE_NAME=
       A URI binding of a CPE name for the operating system, following the
       Common Platform Enumeration Specification[2] as proposed by
       the NIST. This field is optional. Example:
       "CPE_NAME="cpe:/o:fedoraproject:fedora:17""
```

**Comment by poettering** [comment]
I'd write this as `A CPE name for the operating system, in URI binding syntax, following...`.
