### ISSUE TITLE
systemd-networkd fails to use DHCP on VLAN interface

### ISSUE THREAD

**Issue by mxork** [systemd/systemd#11219]
**systemd version the issue has been seen with**
systemd 239

**Used distribution**
Arch

**Expected behaviour you didn't see**

Attempting to use DHCP to obtain addresses for an interface and a related vlan interface, the vlan does not receive an IP address.

Running dhcpcd on the vlan device obtains and assigns the address appropriately.

**Steps to reproduce the problem**

Router is configured to serve different address ranges to untagged and vlan 16 

Contents of `/etc/systemd/network` are below (following https://wiki.archlinux.org/index.php/VLAN#systemd-networkd):

```
# /etc/systemd/network/eno1.network
[Match]
Name=eno1

[Network]
DHCP=ipv4

VLAN=eno1.16
```

```
# /etc/systemd/network/eno1.16.netdev
[NetDev]
Name=eno1.16
Kind=vlan

[VLAN]
Id=16
```

```
# /etc/systemd/network/eno1.16.network
[Match]
Name=eno1.16

[Network]
DHCP=ipv4
```

**Comment by mxork** [comment]
`journalctl --boot -u systemd-networkd` (with `SYSTEMD_LOG_LEVEL=debug`)

[networkd-log.txt](https://github.com/systemd/systemd/files/2696339/networkd-log.txt)

**Comment by mxork** [comment]
Closed: user error.

**Comment by ssahani** [comment]
I can reproduce this. Look at the wire networkd is sending the DHCPDISCOVER no response from server
even  dhclient can not with dnsmasq 

```
 dhclient -i veth-test.16 -d 
Internet Systems Consortium DHCP Client 4.3.6
Copyright 2004-2017 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/veth-test.16/be:72:83:f8:9a:dc
Sending on   LPF/veth-test.16/be:72:83:f8:9a:dc
Sending on   Socket/fallback
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 6 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 6 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 15 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 7 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 13 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 7 (xid=0xf56cd46b)
DHCPDISCOVER on veth-test.16 to 255.255.255.255 port 67 interval 7 (xid=0xf56cd46b)
No DHCPOFFERS received.
No working leases in persistent database - sleeping.

```

Which DHCP server is this ? Any clue from the server log ?

**Comment by yuwata** [comment]
@ssahani So, should we reopen this?

**Comment by yuwata** [comment]
Ah, I see. Thanks.

**Comment by Fanysh** [comment]
Hi @mxork,  meet the same situation. How can you fix this?
