### ISSUE TITLE
unit files cannot use %j in Wants/After directives.

### ISSUE THREAD

**Issue by williamspatrick** [systemd/systemd#11217]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Custom

**Expected behaviour you didn't see**
 > Wants with %j operate successfully.

**Unexpected behaviour you saw**
 > Dec 19 17:45:03 d07dda9541c9 systemd[1]: /lib/systemd/system/foo-0.target:9: Failed to resolve specifiers, ignoring: No error information

**Steps to reproduce the problem**
Create bar-0.target and foo-0.target.  foo-0.target should look like:
```
[Unit]
Description=Foo %j
Wants=bar-%j.target
```

**Comment by williamspatrick** [comment]
Might be solved by (currently untested):
```
diff --git a/src/core/unit-printf.c b/src/core/unit-printf.c
index d5475d748b..364eb05801 100644
--- a/src/core/unit-printf.c
+++ b/src/core/unit-printf.c
@@ -214,6 +214,7 @@ int unit_name_printf(Unit *u, const char* format, char **ret) {
                 { 'N', specifier_prefix_and_instance, NULL },
                 { 'p', specifier_prefix,              NULL },
                 { 'i', specifier_string,              u->instance },
+                { 'j', specifier_last_component,      NULL },

                 { 'U', specifier_user_id,             NULL },
                 { 'u', specifier_user_name,           NULL },
--
```

**Comment by williamspatrick** [comment]
Above patch appears to work.  I don't know enough about the code base to know which unit tests should also be updated, so I don't feel competent enough to submit a PR.

**Comment by poettering** [comment]
patch looks good. by all means submit it as a PR!

**Comment by williamspatrick** [comment]
Thanks @poettering.  Done.
