### ISSUE TITLE
Mute audio on suspend-to-hibernate

### ISSUE THREAD

**Issue by oompf** [systemd/systemd#11213]
`suspend-then-hibernate` should mute audio before the lid is closed.

Otherwise, if audio is played before `suspend-then-hibernate` and the system finally wakes up for hibernation, audio is played for a short amount of time.

However, one should expect that the system hibernates quietly.

This is especially a problem on mobile devices as audio could be played in situations (meetings, etc.) where it is not acceptable.

**Comment by poettering** [comment]
This is certainly a good idea, but it's the duty of the drivers to manage this on their own. Most drivers do. if yours does not, then please file a bug against it. 

This is really a job for the kernel drivers themselves, they know best what to do, and userspace should not and should not have to interfere on this.

Closing hence, hope this makes sense.
