### ISSUE TITLE
How to force systemd to reconcile cgroups

### ISSUE THREAD

**Issue by georgethebeatle** [systemd/systemd#11228]
Hi,

Due to historical reasons Garden, the Cloudfoundry containerizer, manages containers cgroups via creating directories directly into the cgroup hierarchy and we are facing the very same issue as the one described in https://github.com/systemd/systemd/issues/4079. We realise that we should probably set the `Delegate` property but we want to implement a regression test to make sure that the issue is fixed for good on our side. 

We figured out that `systemctl start systemd-tmpfiles-clean.service` if run up to 15 minutes after system boot manifests the issue but it is not repeatable. In order to implement the regression test we would like to be somehow able to force whatever the invocation above does (i.e. make systemd reconcile its cgroup hierarchy). Is there a way to achieve that via e.g. API, changing files on the file system, etc.?

Thanks! 

cc @danail-branekov

**Comment by poettering** [comment]
I am not sure what you mean by "reconcile"?

Note that this is a bug and RFE tracker, for everything else please use the mailing list. Is there a bug or RFE in systemd in this issue? I can't see it. The submission form is actually supposed to make this very clear...

if you are writing your own container manager, please read this:

https://systemd.io/CGROUP_DELEGATION

It will let you know both what to do if you want to run systemd as payload of your containers and as host to your container manager.

Anyway, closing this here, as it appears to be neither a bug report nor an RFE, but some support question. For those → mailing list. Thank you for understanding.
