### ISSUE TITLE
systemd-tmpfiles-setup executes too early

### ISSUE THREAD

**Issue by steelcowboy** [systemd/systemd#1122]
I was trying to have systemd automatically enable tap-to-select via a tmpfile like so:

```
w /sys/devices/platform/i8042/serio1/serio2/press_to_select - - - - 1  
```

However, this does not get written to (I believe because the systemd-tmpfiles-setup either does not wait for /sys to be populated or doesn't wait for /sys to be fully populated. When I run systemd-tmpfiles --create after boot, sure enough it works out perfectly. Creating an override.conf for this service causes it to never execute (I was trying `After=graphical.target`)

**Comment by michich** [comment]
For configuring a specific device like this, a udev rule would be more suitable.
We can never know when /sys is "fully populated". There is no such moment. Devices can appear at any time. This is not a bug.
