### ISSUE TITLE
Assertion '!server->receive_message' failed at ../src/libsystemd-network/sd-dhcp-server.c:1026, function sd_dhcp_server_start().

### ISSUE THREAD

**Issue by rogerjames99** [systemd/systemd#11231]
**systemd version the issue has been seen with**
> Logs are for systemd 232 + commit 45a9eac9a0c85c0c76b46388a530edd335ae44af but believe issue exists from this commit onwards as there have been no further commits in this area. I gave up trying to build an armhf version of master head, my knowledge of debian package management and quilt is not up to it.

**Used distribution**
 > rasbian stretch lite

**Expected behaviour you didn't see**
 > No assert and succesful completion of address configuration for the dhcp server.

**Unexpected behaviour you saw**
 > Dec 21 04:16:24 heathers systemd-networkd[188]: meshpoint: Gained carrier
Dec 21 04:16:24 heathers systemd-networkd[188]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=31 reply_cookie=0 error=n/a
Dec 21 04:16:24 heathers systemd-networkd[188]: Copying NTP server information from wired
Dec 21 04:16:24 heathers systemd-networkd[188]: Assertion '!server->receive_message' failed at ../src/libsystemd-network/sd-dhcp-server.c:1026, function sd_dhcp_server_start(). Ignoring.
Dec 21 04:16:24 heathers systemd-networkd[188]: meshpoint: Gained carrier 

**Steps to reproduce the problem**
Have an external agency cause a carrier gained event. In my case this was a combination of a wpa_supplicant service and networkd-dispatcher running a script with iw commands on the meshpoint interface. 

I can supply full logs and details of  all the systemd units involved if you are prepared to accept this issue. Otherwise just treat it as information only.

**Comment by ssahani** [comment]
It would be great to see the detail logs  in debug mode . Thanks in advance

**Comment by rogerjames99** [comment]
[networkd.log](https://github.com/systemd/systemd/files/2703852/networkd.log)
Here is the debug log. When I get back to my test system I will upload the other service and network files.

**Comment by rogerjames99** [comment]
Here are some additional information files. I have also created a pull request against master with a suggested simple fix.

[10-eth0.link.txt](https://github.com/systemd/systemd/files/2705214/10-eth0.link.txt)
[10-meshpoint.link.txt](https://github.com/systemd/systemd/files/2705215/10-meshpoint.link.txt)
[10-meshpoint.network.txt](https://github.com/systemd/systemd/files/2705216/10-meshpoint.network.txt)
[10-portal.txt](https://github.com/systemd/systemd/files/2705217/10-portal.txt)
[10-wired.network.txt](https://github.com/systemd/systemd/files/2705218/10-wired.network.txt)
[networkd-dispatcher.service.txt](https://github.com/systemd/systemd/files/2705219/networkd-dispatcher.service.txt)
[wpa_supplicant_mesh@.service.txt](https://github.com/systemd/systemd/files/2705220/wpa_supplicant_mesh.service.txt)
[wpa_supplicant_mesh-meshpoint.conf.txt](https://github.com/systemd/systemd/files/2705221/wpa_supplicant_mesh-meshpoint.conf.txt)

**Comment by yuwata** [comment]
#11245 was merged.
