### ISSUE TITLE
Main process exits on reload if `ExecReload` command is failing.

### ISSUE THREAD

**Issue by kiniou** [systemd/systemd#11238]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian Stretch (with stretch-backports enabled in order to get v239)
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch
```

**Expected behaviour you didn't see**
 > After doing a `systemctl reload apache2` with a bad configuration, apache2 processes should be still running.

**Unexpected behaviour you saw**
 > After doing a `systemctl reload apache2` with a bad configuration, the apache2 main process is killed somehow and apache2 is not running anymore:
```Dec 21 13:02:59 debian-stretch apachectl[1320]: The Apache error log may have more information.
Dec 21 13:02:59 debian-stretch systemd[1]: apache2.service: Control process exited, code=exited status=1
Dec 21 13:02:59 debian-stretch systemd[1]: apache2.service: Failed with result 'exit-code'.
Dec 21 13:02:59 debian-stretch systemd[1]: Reload failed for The Apache HTTP Server.
```

**Steps to reproduce the problem**
1. Install apache2: 
```
apt install apache2
```
2. Check for apache2 processes running:
```
# ps --forest -o user,pid,ppid,command -C apache2
USER       PID  PPID COMMAND
root      1226     1 /usr/sbin/apache2 -k start
www-data  1227  1226  \_ /usr/sbin/apache2 -k start
www-data  1228  1226  \_ /usr/sbin/apache2 -k start
#
```

2. Set bogus directive somewhere in apache2 configuration:
```
echo "-bogus-configuration-" > /etc/apache2/conf-enabled/bogus.conf
```
3. Reload `apache2.service`:
```
systemctl reload apache2.service
```
4. check again for apache2 processes running:
```
# ps --forest -o user,pid,ppid,command -C apache2
USER       PID  PPID COMMAND
#
```
5. The status of `apache2.service` states that control process exited and apache2 main process has exited as well.

**Notes**
This is the current service unit shipped with `apache2` package:
```# /lib/systemd/system/apache2.service
[Unit]
Description=The Apache HTTP Server
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
Environment=APACHE_STARTED_BY_SYSTEMD=true
ExecStart=/usr/sbin/apachectl start
ExecStop=/usr/sbin/apachectl stop
ExecReload=/usr/sbin/apachectl graceful
PrivateTmp=true
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

I think it's worth noting that doing an `apachectl -k graceful` do not kill the current running apache2 processes but only raise a return code != 0 if configuration is wrong.

```
# apachectl -k graceful; echo "APACHECTL_RETCODE=$?";ps --forest -o user,pid,ppid,command -C apache2
AH00526: Syntax error on line 1 of /etc/apache2/conf-enabled/bogus.conf:
Invalid command '-bogus-configuration-', perhaps misspelled or defined by a module not included in the server configuration
Action '-k graceful' failed.
The Apache error log may have more information.
APACHECTL_RETCODE=1
USER       PID  PPID COMMAND
root      1361     1 /usr/sbin/apache2 -k start
www-data  1362  1361  \_ /usr/sbin/apache2 -k start
www-data  1363  1361  \_ /usr/sbin/apache2 -k start
```

It seems weird actually since I used to do many reload with systemd in the past 2 years and never experienced this as far as i can recall ... :thinking: 

Also, this may be related to #2175 but I'm not sure if it's relevant.

**Comment by poettering** [comment]
Hmm? I think there's some confusion here. In systemd every service may has 0, 1 or 2 special processes. The latter two are the "main" and the "control" process. The "main" process is as the name suggests the main process of the service, the one that primarily defines the service's lifecycle. The "control" process otoh is a helper process that is used to control the state of the service, and is how we internally expose ExecReload=, ExecStop= and similar, i.e. the processes that PID 1 forks off *in addition* to the main service process, to effect changes in its lifecycle.

hence, yes, if ExecReload= fails and you see complaints about the control process failing, then this is not suprising but the reason, because the process you specified in ExecReload= *is* the control process.

So, not sure what precisley this issue is about, did I musinderstand what you are saying?

**Comment by boucman** [comment]
(as a side note, the process that systemd forks for ExecStart is also called control-process until it execve the main process... at least in error messages if it fails)

**Comment by kiniou** [comment]
@poettering Thanks your excellent explanation: now I understand a bit more what's behind the `systemctl status` output :wink:.

Also, I have been confused by the term "control" and I supposed this control process was referring to the main apache2 process. I can replace "Control" by "Main" in the report's title and edit the report accordingly.

Still, this issue is more about the behaviour of ExecReload which killed the main process somehow  because it fails to reload the apache configuration (this is mostly a supposition here since I have no clue about it and I did not take the time to dig in the source code :mag:). And what I've tried to explain in the last part of the report is that it might not be a bug, but it looks like one.

**Comment by poettering** [comment]
nah, systemd does not kill the main process of a service if reload fails. maybe apache died on its own?

**Comment by kiniou** [comment]
mmmh ... i don't think it died on its own here since the error logs states that it received a SIGTERM (still don't know who send the signal and I'm actually struggling with auditd).

I did the same tests with Nginx as well with `nginx -s reload` and it's the same behaviour.

I'm now wondering if the .service files are missing a configuration directive like `PIDFile=`.

**Comment by kiniou** [comment]
From what I'm reading in the following auditd logs, PID1 is sending SIGTERM to the main apache2 process:
```
type=PROCTITLE msg=audit(12/22/18 19:00:20.793:2521) : proctitle=/usr/sbin/apache2 -k start
type=OBJ_PID msg=audit(12/22/18 19:00:20.793:2521) : opid=5074 oauid=unset ouid=www-data oses=-1 obj==unconfined ocomm=apache2
type=SYSCALL msg=audit(12/22/18 19:00:20.793:2521) : arch=x86_64 syscall=kill success=yes exit=0 a0=0x13d2 a1=SIGTERM a2=0x3 a3=0x0 items=0 ppid=1 pid=5073 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=apache2 exe=/usr/sbin/apache2 subj==unconfined key=(null)
----
type=PROCTITLE msg=audit(12/22/18 19:00:20.793:2524) : proctitle=/usr/sbin/apache2 -k start
type=OBJ_PID msg=audit(12/22/18 19:00:20.793:2524) : opid=5075 oauid=unset ouid=www-data oses=-1 obj==unconfined ocomm=apache2
type=SYSCALL msg=audit(12/22/18 19:00:20.793:2524) : arch=x86_64 syscall=kill success=yes exit=0 a0=0x13d3 a1=SIGTERM a2=0x3 a3=0x0 items=0 ppid=1 pid=5073 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=apache2 exe=/usr/sbin/apache2 subj==unconfined key=(null)
```
And here is the `systemctl status apache2` output showing the main pid 5073 after the reload:
```
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/apache2.service.d
           └─pidfile.conf
   Active: failed (Result: exit-code) since Sat 2018-12-22 19:00:20 CET; 9min ago
  Process: 5064 ExecStop=/usr/sbin/apachectl stop (code=exited, status=0/SUCCESS)
  Process: 5169 ExecReload=/usr/sbin/apachectl graceful (code=exited, status=1/FAILURE)
  Process: 5069 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 5073 (code=exited, status=0/SUCCESS)
```

I think the following code piece of `service_enter_running` function could cause the SIGTERM when `service_enter_reload` fails:
 https://github.com/systemd/systemd/blob/8f9f3cb72414a831699d9012601e09d0daa1051e/src/core/service.c#L1940-L1941
I don't have yet setup a dev environment for systemd to debug and check what's in `s->result` but I suspect it is not set since the `service_enter_reload` set `s->reload_status`.

PS: In doubt, I've just tested `PIDFile=/var/run/apache2/apache2.pid` (hence drop-in `pidfile.conf`) but this does not help.

**Comment by sbraz** [comment]
I'm seeing the same thing with another service (icinga2) and systemd 239. Strace shows PID 1 killing it with SIGTERM and I can see that using `ExecReload=-` makes it behave as expected (ExecReload failing doesn't cause the main PID to be killed).

I guess this regression was introduced in v239 by https://github.com/systemd/systemd/commit/ec5b1452ac73e41274f9b3ca401f813fa079b9f0?

**Comment by kiniou** [comment]
@sbraz I agree that `ExecReload=-` can be a workaround from a Systemd POV but some other tools like SaltStack or Ansible rely on the code result from `systemctl reload` to check if the service has been correctly reloaded and some other states could depend on it.

I'm currently trying to fix it but I'm not sure if I understand the fix in ec5b145.

**Comment by sbraz** [comment]
@kiniou oh it's not a good workaround :smile:, it was just to check the hypothesis that systemd is the one killing the process and not the process dying on its own.

@poettering Would it be possible for you to look at this issue again? It is rather problematic for everyone who got used to the reload action being rather fail-safe.

**Comment by dqminh** [comment]
@poettering i'm seeing this too, and looks like https://github.com/systemd/systemd/commit/ec5b1452ac73e41274f9b3ca401f813fa079b9f0 does cause this.

When `ExecReload` failed, the unit result is set to `SERVICE_FAILURE_EXIT_CODE`, which then trigger SIGTERM when we enter `service_enter_running`.

**Comment by benhubert** [comment]
I stumbled over the same issue. Is there any information missing to get this fixed? Because I think with all the information above, the label `needs-reporter-feedback` can be removed.

**Comment by poettering** [comment]
I prepped a fix proposal in #13098, any chance you could test this and see if it works for you?

**Comment by kiniou** [comment]
Yes! :raised_hands:
I will test your PR as soon as possible. :wink:

**Comment by sbraz** [comment]
@poettering just applied the patch from your PR and it works as expected.

**Comment by kiniou** [comment]
I've managed to test your patch against a recent 242 version and this is working as expected.
Thanks a lot @poettering !

**Comment by kfix** [comment]
Adding a `test/TEST-NN-EXECRELOAD/test.sh` seems prudent.
