### ISSUE TITLE
See issue 5427: Process org.freedesktop.systemd1 exited with status 1

### ISSUE THREAD

**Issue by udovdh** [systemd/systemd#11246]
**systemd version the issue has been seen with**
> systemd-239-6.git9f3aed1.fc29.x86_64

**Used distribution**
 > Fedora 29 but issue has been present elsewhere for a while now, see issue 5427.

**Expected behaviour you didn't see**
 > Started vino service without any fuss.

**Unexpected behaviour you saw**
 > See below.

**Steps to reproduce the problem**
$ systemctl --user start vino-server
Failed to start vino-server.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status vino-server.service' for details.
$ systemctl --user status dbus.service
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1
$ 

System has been to runlevel 3 and back, and was previously logged out from Gnome

**Comment by poettering** [comment]
please provide an excerpt of the system logs when this happens

**Comment by poettering** [comment]
Closing due to lack of response

**Comment by udovdh** [comment]
Trying to reproduce this almost every 10 days or so due to memory leak in gnome-shell.

**Comment by udovdh** [comment]
$ systemctl --user status vino-server
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1

So what do we do now?

**Comment by udovdh** [comment]
$ rpm -q systemd
systemd-239-12.git8bca462.fc29.x86_64

**Comment by yuwata** [comment]
Do you use XFCE?

**Comment by yuwata** [comment]
Please see @poettering's comments in #10291.

**Comment by udovdh** [comment]
Gnome.
And what logs are needed?

**Comment by udovdh** [comment]
$ busctl monitor --user
Monitoring bus message stream.
‣ Type=method_call  Endian=l  Flags=1  Version=1  Priority=0 Cookie=353
  Sender=:1.79  Destination=org.gtk.Notifications  Path=/org/gtk/Notifications  Interface=org.gtk.Notifications  Member=RemoveNotification
  UniqueName=:1.79
  MESSAGE "ss" {
          STRING "org.gnome.Terminal";
          STRING "12f60f27-0d54-459c-9e85-f0acfad9ca93";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1
  Sender=:1.5263  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.5263
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=1  ReplyCookie=1
  Sender=org.freedesktop.DBus  Destination=:1.5263
  MESSAGE "s" {
          STRING ":1.5263";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=10300
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.5263";
          STRING "";
          STRING ":1.5263";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.5263  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.5263";
  };

‣ Type=method_call  Endian=l  Flags=4  Version=1  Priority=0 Cookie=2
  Sender=:1.5263  Destination=org.freedesktop.systemd1  Path=/org/freedesktop/systemd1/unit/vino_2dserver_2eservice  Interface=org.freedesktop.DBus.Properties  Member=GetAll
  UniqueName=:1.5263
  MESSAGE "s" {
          STRING "";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=3  ReplyCookie=2
  Sender=org.freedesktop.DBus  Destination=:1.5263
  ErrorName=org.freedesktop.DBus.Error.Spawn.ChildExited  ErrorMessage="Process org.freedesktop.systemd1 exited with status 1"
  MESSAGE "s" {
          STRING "Process org.freedesktop.systemd1 exited with status 1";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=5
  Sender=org.freedesktop.DBus  Destination=:1.5263  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.5263";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=10301
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.5263";
          STRING ":1.5263";
          STRING "";
  };

‣ Type=method_call  Endian=l  Flags=1  Version=1  Priority=0 Cookie=354
  Sender=:1.79  Destination=org.gtk.Notifications  Path=/org/gtk/Notifications  Interface=org.gtk.Notifications  Member=RemoveNotification
  UniqueName=:1.79
  MESSAGE "ss" {
          STRING "org.gnome.Terminal";
          STRING "9b43496c-5a3e-44fa-a3bd-36a03d0e4025";
  };

‣ Type=method_call  Endian=l  Flags=1  Version=1  Priority=0 Cookie=355
  Sender=:1.79  Destination=org.gtk.Notifications  Path=/org/gtk/Notifications  Interface=org.gtk.Notifications  Member=RemoveNotification
  UniqueName=:1.79
  MESSAGE "ss" {
          STRING "org.gnome.Terminal";
          STRING "9b43496c-5a3e-44fa-a3bd-36a03d0e4025";
  };

^C

**Comment by udovdh** [comment]
So we see growing gnome-shell processes. Once in a while we do `init 3` on a VT.
This does NOT kill all gnome-shell and related so we kill the rest manually. (old behaviour of init was perfect)
Once we are sure all gnome is killed we do `init 5` to have the gui return.
After one or more of such workaround attempts we get the 
$ systemctl --user status vino-server
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1

**Comment by yuwata** [comment]
(Still I do not catch the issue well, but let's reopen this.)

**Comment by udovdh** [comment]
What other logs would be useful?

**Comment by yuwata** [comment]
First of all, please try the following:
```
$ SYSTEMD_LOG_LEVEL=debug systemctl --user status vino-server
```

**Comment by udovdh** [comment]
$ SYSTEMD_LOG_LEVEL=debug systemctl --user status vino-server
running_in_chroot(): Permission denied
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → CLOSED
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Successfully forked off '(pager)' as PID 1907.
Skipping PR_SET_MM, as we don't have privileges.
Showing one /org/freedesktop/systemd1/unit/vino_2dserver_2eservice
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.5507 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/vino_2dserver_2eservice interface=org.freedesktop.DBus.Properties member=GetAll cookie=2 reply_cookie=0 signature=s error->
Got message type=error sender=org.freedesktop.DBus destination=:1.5507 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.Spawn.ChildExited error-message=Process org.freedesktop.s>
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1
Bus n/a: changing state RUNNING → CLOSED

(`ps -ef` does not show a vino process)

**Comment by udovdh** [comment]
$ SYSTEMD_LOG_LEVEL=debug systemctl --user start vino-server
running_in_chroot(): Permission denied
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → CLOSED
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Executing dbus call org.freedesktop.systemd1.Manager StartUnit(vino-server.service, replace)
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.5509 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnit cookie=3 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.DBus destination=:1.5509 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=3 signature=s error-name=org.freedesktop.DBus.Error.Spawn.ChildExited error-message=Process org.freedesktop.systemd1 exited with status 1
Failed to start vino-server.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status vino-server.service' for details.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=4 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state RUNNING → CLOSED

**Comment by yuwata** [comment]
Also please try `ps xauwf` and show dbus related results as I requested in https://github.com/systemd/systemd/issues/10291#issuecomment-442905819.

**Comment by yuwata** [comment]
Hmm, your output is truncated... Please try with `--no-pager` option.

**Comment by yuwata** [comment]
Also, please check the journal.

**Comment by udovdh** [comment]
$ ps xauwf|grep dbus
dbus      1635  0.0  0.0  11108  5660 ?        Ss   jan27  18:07 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
gdm      13691  0.0  0.0   8148  4028 ?        Ss   feb24   0:00  \_ /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
gdm      13715  0.0  0.0   7608  3620 ?        S    feb24   0:00  |   \_ /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
udo      14170  0.0  0.0   8916  4772 ?        S    feb24   0:17 dbus-daemon --print-address 4 --session
udo       3369  0.0  0.0   8692  5076 tty2     S+   mrt02   0:09          \_ dbus-daemon --print-address 4 --session
udo       3626  0.0  0.0   7608  3672 tty2     S+   mrt02   0:01  \_ /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
udo       3221  0.0  0.0 215752   960 pts/1    S+   17:09   0:00  |   \_ grep --color=auto dbus

**Comment by udovdh** [comment]
Where do I apply --nopager?
How do I filter the journal to see what we need and not too much of the rest?

**Comment by yuwata** [comment]
> Where do I apply --nopager?

E.g., `systemctl --no-pager --user status vino-server.service`.

> How do I filter the journal to see what we need and not too much of the rest?

`journalctl` has e.g., `--grep`, `--unit`, `--user-unit`, `--priority` options. Please see journalctl(1).

**Comment by udovdh** [comment]
Ah, no-pager instead of nopager.

**Comment by udovdh** [comment]
Mar 04 17:23:22 surfplank2.hierzo /usr/libexec/gdm-x-session[3351]: dbus-daemon[3369]: [session uid=500 pid=3369] Activating service name='org.freedesktop.systemd1' requested by ':1.5757' (uid=500 pid=5289 comm="systemctl --no-pager --user status vino-server.ser")
Mar 04 17:23:22 surfplank2.hierzo /usr/libexec/gdm-x-session[3351]: dbus-daemon[3369]: [session uid=500 pid=3369] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

**Comment by udovdh** [comment]
So what can we conclude here?

**Comment by machitgarha** [comment]
@yuwata, I think this issue should be closed.

**Comment by pabloab** [comment]
I'm getting this on systemd journal every ~10' (around 5' to 25'). systemd 245 (245.4-4ubuntu3.13), Ubuntu 20.04 LTS.

> /usr/lib/gdm3/gdm-x-session[2249]: dbus-daemon[2249]: [session uid=139 pid=2249] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
> gsd-sharing[2645]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1                             
> gsd-sharing[2645]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1
> gsd-sharing[2645]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1                             
> gsd-sharing[2645]: Failed to StopUnit service: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1

**Comment by hopefulwalker** [comment]
@pabloab 
I'm getting the same output in /var/log/syslog Ubuntu(20.04.3 LTS). But everything is fine too.

**Comment by machitgarha** [comment]
The main thread is the issue #5247. Please everyone go there for further discussions and other info.
