### ISSUE TITLE
adding udev_log=debug to /etc/udev/udev.conf causes udev failing to start

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11258]
**systemd version the issue has been seen with**

v240

**Used distribution**
 
Debian sid

Trying to debug #11255 , I wanted to add `udev_log=debug` to /etc/udev/udev.conf  to get a more vebose debug log.
Unfortunately this causes systemd-udevd.service failing to start.

**Comment by mbiebl** [comment]
![udev](https://user-images.githubusercontent.com/3609611/50385361-9ab69080-06d4-11e9-8dee-bf486d50b010.png)

**Comment by mbiebl** [comment]
`journalctl -u systemd-udevd`
[udev.txt](https://github.com/systemd/systemd/files/2706094/udev.txt)

full journalctl dump of the boot
[journalctl.txt](https://github.com/systemd/systemd/files/2706095/journalctl.txt)

**Comment by philmmanjaro** [comment]
@mbiebl: you may want to add https://github.com/systemd/systemd/pull/11244 to your build of systemd.

**Comment by yuwata** [comment]
Yeah, #11244 fixes this.
