### ISSUE TITLE
switch-root: Cryptic error message

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#11261]
Hello!

I'm developing my own distro with systemd (v240), Dracut, and OSTree. Today I spent multiple hours debugging a boot issue. `systemctl switch-root /sysroot` would just restart the initramfs instead of entering the main system. Eventually I figured out that the error was caused by missing `/sys`, `/run`, and `/proc` mountpoints. The closest thing to an error I got was: `Failed to mount /sys to /sysroot/sys: Success`, which only made sense once I've traced systemd's code to its source [Here](https://github.com/systemd/systemd/blob/master/src/shared/switch-root.c). `/sysroot` is mounted read-only, so when systemd tries to create the mount points, it fails. Once it tries to actually mount the folders, it will print the error and fail to switch root. `do_reexecute`, however, continues running, and will restart systemd, restarting the initramfs and creating the problem I've experienced.

The error message is confusing, contradictory, and does not show any sign that it comes from `switch_root`.  It would be nice if the error looked something like `Failed to mount /sys to /sysroot/sys: REASON. Failed to switch root.`, ~~or even if `do_reexecute` printed out an error if the switch-root failed (which it did not)~~ EDIT: It does this, but the error handling is borked so as far as `do_reexecute` is concerned, there were no errors

Thanks!

**Comment by kirbyfan64** [comment]
(FWIW I'm not that familiar with the internals here, but my personal guess is that something is overwriting `errno` before it's printed, leading to the bizarre `Failed to...: Success`.

**Comment by AdrianVovk** [comment]
@kirbyfan64 Actually the mount operation never stores its return value...

**Comment by AdrianVovk** [comment]
Quick correction (thanks to @kirbyfan64)

mount's return value shouldn't be stored. `log_error_errno` should be passed `errno`, not `r`

Theoretically, here's the fix:
Replace line 86 in switch_root.c with
`return log_error_errno(errno, "Failed to mount %s to %s: %m", i, chased);`

**Comment by yuwata** [comment]
Fix is waiting in #11266.
