### ISSUE TITLE
HDD name under /dev/disk/by-id has changed in systemd 240

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#11264]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > $ sudo /lib/udev/ata_id /dev/sda
 > ST500LT012-1DG142_S3PDHAMW

**Unexpected behaviour you saw**
 > $ sudo /lib/udev/ata_id /dev/sda
 > ST500LT012-1DG142____S3PDHAMW

**Steps to reproduce the problem**

Look under /dev/disk/by-id/ for names that have lots of underscores.

Seems to have started with commit df8ba4fa0e8be1ff7899d08a4b6be0196c8405a0.

**Comment by yuwata** [comment]
Fix is waiting in #11265.
