### ISSUE TITLE
240 breaks kde : system takes ages to start, kdeinit5 is stuck at 100 %cpu 

### ISSUE THREAD

**Issue by EricV2** [systemd/systemd#11260]
**systemd version the issue has been seen with**

240

**Used distribution**
 debian unstable. Same setup works with 239

**Expected behaviour you didn't see**
 Normal kde start.

**Unexpected behaviour you saw**
10 min fro login screen to desktop, stuck with a dark background and a mouse cursor.
**Steps to reproduce the problem**

Install debian unstable kde and upgrade to systemd 240. There are currently tree reports of the problem.

**Comment by mbiebl** [comment]
Not really an upstream bug in systemd.
It's both a bug in kinit (see https://github.com/systemd/systemd/issues/10921#issuecomment-449654746) and pam_limits in Debian
