### ISSUE TITLE
systemd 240 creates log entries for systemd-tmpfiles

### ISSUE THREAD

**Issue by userbugs** [systemd/systemd#11282]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian Sid Kernel 4.20

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 >Since version 240 many log entries are created. This wasn't in 239 yet, so I'm assuming an error in the query. Can this query be corrected?
Many thanks in advance.

**Steps to reproduce the problem**
with each system start

Here are some examples of the logs:
systemd-tmpfiles[248]: Detected unsafe path transition / → /dev during canonicalization of /dev.
systemd-tmpfiles[485]: Detected unsafe path transition / → /var during canonicalization of /var.
systemd-tmpfiles[485]: Detected unsafe path transition / → /var during canonicalization of /var/lib.

**Comment by poettering** [comment]
This suggests that your root dir, /dev and /var are owned by differing users. What does `stat / /dev /var` output?

**Comment by userbugs** [comment]
hello Lennart,
stat /dev and /var were ok, but not stat /. I didn't see that before. I changed that and now there are no more errors in the log.
Thank you very much for your hint.
Sorry for my question and a happy new year.
kind regards
MB

**Comment by sunshinertoo** [comment]
Setting up systemd (244.1-2) ...
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.

This is not solved

**Comment by sunshinertoo** [comment]
On debian sid:

# apt install dialog
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dialog
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 0 B/279 kB of archives.
After this operation, 1219 kB of additional disk space will be used.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Setting up systemd (244.1-2) ...
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 73
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by sunshinertoo** [comment]
apt-get install whiptail
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnewt0.52 libpopt0
The following NEW packages will be installed:
  libnewt0.52 libpopt0 whiptail
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 163 kB of archives.
After this operation, 683 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://192.168.2.1/debmirrorsid sid/main amd64 libnewt0.52 amd64 0.52.21-4 [73.5 kB]
Get:2 http://192.168.2.1/debmirrorsid sid/main amd64 libpopt0 amd64 1.16-14 [49.5 kB]
Get:3 http://192.168.2.1/debmirrorsid sid/main amd64 whiptail amd64 0.52.21-4 [39.7 kB]
Fetched 163 kB in 1s (272 kB/s)    
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 3.)
debconf: falling back to frontend: Readline
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Setting up systemd (244.1-2) ...
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 73
Errors were encountered while processing:
 systemd

**Comment by sunshinertoo** [comment]
# apt install dialog whiptail
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnewt0.52 libpopt0
The following NEW packages will be installed:
  dialog libnewt0.52 libpopt0 whiptail
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 0 B/441 kB of archives.
After this operation, 1902 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 4.)
debconf: falling back to frontend: Readline
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
Setting up systemd (244.1-2) ...
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
Detected unsafe path transition / → /var during canonicalization of /var/log/journal/173d937f233341feaee2b3cbeeeb776f/system.journal.
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 73
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by theAkito** [comment]
Solved! My `/` wasn't owned by `root`, either.
