### ISSUE TITLE
Forcibly rebooting with Ctrl-Alt-Del does not work

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#11285]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian Sid/unstable

**Expected behaviour you didn't see**
 > After pressing Ctrl+Alt-Del the system should reboot immediately.

**Unexpected behaviour you saw**
 > The system only rebooted after the two minute time-out of the “hanging“ service.

**Steps to reproduce the problem**

If a service cannot be stopped and the time-out message is shown, try to reboot the system.

**Comment by mbiebl** [comment]
For such a case, where you want immediate shutdown/reboot, without having to wait for services to stop, you can hit ctrl+alt+delete quickly 7 times.

**Comment by paulmenzel** [comment]
Am 28.12.18 um 13:39 schrieb Michael Biebl:
> For such a case, where you want immediate shutdown/reboot, without
> having to wait for services to stop, you can hit ctrl+alt+delete
> quickly 7 times.

Sorry, that is what the bug report is supposed to be about, and I now 
see, that I did not mention this at all.

Pressing it quickly seven times (in two seconds I believe), the message, 
that I pressed it seven times, is shown, but the system does not reboot 
immediately.

**Comment by poettering** [comment]
not sure i understand what the problem is precisely?

you want that any service that times out during stopping results in an immediate shortcut to a reboot? I am not sure that works...

If the system does not reboot immediately after C-A-D is pressed 7 times this suggests that there's something wrong in your storage stack or so, and the system hangs in some kernel code which systemd can do little about...

We could probably tweak systemd that if C-A-D is pressed 7 times twice then it will just issue reboot() and not wait for sync, but I this is never going to be complete: if the storage PID 1 runs from (or any of its deps) is borked then PID 1 might have serious problems to continue, for example if code needs to be paged in by the kernel but cannot...

Hence, dunno, I'd need to know more about the nature of this shutdown freeze...

**Comment by paulmenzel** [comment]
Am 30.12.18 um 12:07 schrieb Lennart Poettering:
> not sure i understand what the problem is precisely?
> 
> you want that any service that times out during stopping results in
> an immediate shortcut to a reboot? I am not sure that works...

Now, I do not understand what you mean. ;-) I just want, if I press
C-A-D seven times, and the system tells me that immediate reboot is
requested, that it reboots.

> If the system does not reboot immediately after C-A-D is pressed 7
> times this suggests that there's something wrong in your storage
> stack or so, and the system hangs in some kernel code which systemd
> can do little about...

Understood.

> We could probably tweak systemd that if C-A-D is pressed 7 times
> twice then it will just issue reboot() and not wait for sync, but I
> this is never going to be complete: if the storage PID 1 runs from
> (or any of its deps) is borked then PID 1 might have serious problems
> to continue, for example if code needs to be paged in by the kernel
> but cannot...
> 
> Hence, dunno, I'd need to know more about the nature of this shutdown
> freeze...

Can this be debugged with SysRq stuff? What do you need?

**Comment by Hello71** [comment]
> We could probably tweak systemd that if C-A-D is pressed 7 times twice then it will just issue reboot() and not wait for sync, but I this is never going to be complete: if the storage PID 1 runs from (or any of its deps) is borked then PID 1 might have serious problems to continue, for example if code needs to be paged in by the kernel but cannot... Hence, dunno, I'd need to know more about the nature of this shutdown freeze...
> Can this be debugged with SysRq stuff? What do you need?

please take a picture of your screen while it is "waiting" (i.e. *after* pressing ctrl-alt-del 7 times), then press alt-sysrq-w, then take another picture. you may need to first increase the resolution to see a useful amount of output.

**Comment by net147** [comment]
I have had this occur in the following case:
1. Mount network CIFS share
2. Disconnect from network without unmounting CIFS share
3. Switch to terminal and press ctrl-alt-del to issue reboot
4. Notice it hangs trying to stop the user session
5. Press ctrl-alt-del 7 times in 2 seconds
[  !!  ] Forcibly rebooting: Ctrl-Alt-Del was pressed more than 7 times within 2s
[ 8103.426907] watchdog: watchdog0: watchdog did not stop!
[ 8113.470463] systemd-shutdown[1]: Waiting for process: at-spi-bus-laun, kwin_x11, systemd, dbus-daemon, pulseaudio, dbus-daemon
System hangs here...

To get it to force reboot without hanging, I need to edit /etc/systemd/system.conf and add the following in [Manager] section:
CtrlAltDelBurstAction=reboot-immediate

The default value of CtrlAltDelBurstAction=reboot-force hangs for the above test case.

**Comment by poettering** [comment]
> please take a picture of your screen while it is "waiting" (i.e. _after_ pressing ctrl-alt-del 7 times), then press alt-sysrq-w, then take another picture. you may need to first increase the resolution to see a useful amount of output.

This was never provided, hence let's close. We don't know enough about the issue, and from all it looks like it's a local issue with storage/kernel
