### ISSUE TITLE
machinectl fails if "mkfs.btrfs" is not installed

### ISSUE THREAD

**Issue by maxmeyer** [systemd/systemd#1129]
``` bash
% sudo machinectl pull-dkr --dkr-index-url https://index.docker.io maxmeyer/docker-centos-nginx --verify=no
Failed transfer image: mkfs.btrfs died abnormally.
```

It would be great to have a better error message.

**Comment by Celti** [comment]
I just got bit by this one myself, not realising that machined would try to create a btrfs loop device if there is nothing in /var/lib/machines — I've used it without the loop device on other non-btrfs systems by creating containers manually. Ideally it would warn with 'mkfs.btrfs not found, container cloning will have reduced performance' and continue without the loop device.
