### ISSUE TITLE
(sd-passwd)[602]: Assertion 'keyname' failed at ../src/shared/ask-password-api.c:164, function ask_password_keyring().

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11295]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Fedora Rawhide

**Expected behaviour you didn't see**
 > Success

**Unexpected behaviour you saw**
 > Dumps core

**Steps to reproduce the problem**
Set up a system to use Clevis-luks

**Comment by yuwata** [comment]
@doverride Could you test #11297?

**Comment by doverride** [comment]
if @zbyszek or someone else @fedora can provide me a link to a scratch built on koji.
