### ISSUE TITLE
Hibernation sometimes freezes

### ISSUE THREAD

**Issue by MikkoMMM** [systemd/systemd#11296]
**systemd version the issue has been seen with**
> [mikko@localhost lvdata]$ systemctl --version
> systemd 239
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux
> [mikko@localhost lvdata]$ uname -a
> Linux localhost 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > Hibernation successful

**Unexpected behaviour you saw**
 > The computer stays fully powered but the screen turns black and doesn't respond to input.
> Here's what journalctl -b -1 says:
> [hibernate-journalctl.txt](https://github.com/systemd/systemd/files/2717095/hibernate-journalctl.txt)
> I can still log in through ssh but calling killall systemd-sleep doesn't return a picture on the screen. This is what journalctl has to say about that:
> [killall-systemd-suspend.txt](https://github.com/systemd/systemd/files/2717097/killall-systemd-suspend.txt)
> After forcing a shutdown, fsck starts and gives me some "print_req_error: I/O error, dev sdf" messages which is atypical. The sdf drive is an encrypted ext4 external USB drive that is used by automatic backup through rsnapshot and, after that has ended, hdparm -y is called on the drive.

**Steps to reproduce the problem**
> I've had this happen two times with different versions of systemd. The last one was with the latest systemd version available on my platform. However, the freezing happens only sometimes; not every time I try to hibernate.
> I've used a script that waits for inactivity, then calls "xset dpms force off" and after some more inactivity it calls "systemctl hibernate". However, it's worked fine when I have used systemctl suspend in it so I don't think the script is the problem.

**Comment by bl33pbl0p** [comment]
Does it happen after you set `HibernateMode=` to shutdown as per https://www.freedesktop.org/software/systemd/man/systemd-sleep.conf.html?

**Comment by MikkoMMM** [comment]
> Does it happen after you set `HibernateMode=` to shutdown as per https://www.freedesktop.org/software/systemd/man/systemd-sleep.conf.html?

It just might have helped. I noticed that there are also [instructions regarding that on the Arch wiki as well](https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#System_does_not_power_off_when_hibernating) and followed those. Then I rebooted and tried systemctl hibernate five times in a row (two of which were done after calling hdparm -y on my external drive). The hibernation was successful each time. Of course I can't say it definitely is working now seeing how it didn't occur every time before.

**Comment by keszybz** [comment]
This is a kernel driver / firmware issue. Sorry — nothing we can do about this.

In particular "kernel: Xorg: page allocation failure: order:4" suggests that there's some memory fragmentation. It's possible that subsequent issues stem from this relatively simple failure. The kernel could be fixed to not require such big allocations or to prepare the memory more carefully. IIUC, this is the external nvidia module, so it's hard to hope for a fix.
