### ISSUE TITLE
networkd: missing /prefixlen results in strange defaults

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#11307]
**systemd version the issue has been seen with**
> 240.0-1 (Arch)

**Expected behaviour you didn't see**

If I do not specify the "/prefixlen" in addresses (e.g. `Address=10.147.32.113`), networkd should assume a full-length netmask (/32 or /128) by default, similar to the existing documented behavior for route destinations.

Full-length netmask is a safe default, and would match `ip addr add` behavior.

**Unexpected behaviour you saw**

If I do not specify the "/prefixlen", networkd (or the kernel, not yet sure which) picks completely useless default netmasks.

 * For IPv6, it defaults to `/0`, which can break network connectivity in mysterious ways.
 * For IPv4, it defaults to class-based netmasks based on initial address bits (e.g. /8 for 10.x.x.x, or /24 for 192.x.x.x) – a behavior that has been obsolete for more than 25 years.

**Steps to reproduce the problem**

 1. Apply this example configuration:

    ```
    [Network]
    Address=10.0.0.1
    Address=192.168.0.1
    Address=2001:db8::1
    ```

 2. Run `ip addr` and check the /prefixlen shown next to each address; this will probably show /8, /24, and /0.

 3. Compare this to `ip addr add 10.0.0.2 dev ...`, which results in a /32 netmask.

**Comment by yuwata** [comment]
I guess 'fixing' this is not so hard, but may break backward compatibility. @poettering and @ssahani WDYT?

**Comment by grawity** [comment]
Backwards compatibility is a concern, but IMO, the current defaults are such that I doubt many people would have wanted to rely on them anyway. I guess you could log a red warning/error to the journal for a few releases before changing the default – or even completely deprecate Address= values without a /prefixlen and have the user always be explicit about their configuration.

For IPv4, most networks these days don't match the 1980s 'class' assignments anymore, so they would have required the config to have an explicit /prefixlen already. (Except perhaps 192.168.x.x LANs, but those are more likely to just use DHCP.) For IPv6, the default of /0 doesn't even result in functional networking if it's used on Ethernet (though it does work on a p-t-p tunnel interface) so it's even more unlikely that anyone would be using it. (That said, if the config _explicitly_ has an address with `/0`, that of course still needs to be honored...)

**Comment by yuwata** [comment]
So, what do you think about the following process to change the behavior.
1. Let's warn about addresses without prefixlen (v242?), but keep the current behavior.
2. Then, refuse addresses without prefixlen (v243?).
3. Finally, treat addresses without prefixlen /32 or /128 (v244?).

**Comment by yuwata** [comment]
So, v241 was released with the step 1 in the above. Should we step to 2 in v242, or wait for a while?

**Comment by poettering** [comment]
i'd probably wait a year or so, after all downstream distros are unlikely to pick up every release we do upstream in their stable releases.

**Comment by yuwata** [comment]
OK.

**Comment by grawity** [comment]
Thanks, the warning should already help with avoiding accidental misconfigurations.

**Comment by yuwata** [comment]
Let's close this, as we now strongly warn about that.
