### ISSUE TITLE
Parser may be attempting to validate fields prematurely

### ISSUE THREAD

**Issue by kiplingw** [systemd/systemd#11306]
**systemd version the issue has been seen with**
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
Ubuntu 18.10 (amd64)

**Expected behaviour you didn't see**
Expected parser to not attempt validation of After, Requires, BindsTo, PartOf, and ConditionPathExists until after final value assigned from drop-in. I experienced this while attempting to write a unit test to start / stop my daemon as --user from within my local build tree.

**Unexpected behaviour you saw**
$ systemctl --user link $PWD/foo.service
$ mkdir -p ~/.config/systemd/user/foo.service.d/
$ ln -f -v foo_service_dropin.conf ~/.config/systemd/user/foo.service.d/
$ systemctl --user start foo.service
$ systemd-analyze --user --man=no verify foo.service
/home/kip/Projects/foo/build/foo.service:29: ConditionPathExists= path is not normalized, ignoring: /home/kip/Projects/foo/build/../prefix/foo/server.conf
foo.service: Failed to create foo.service/start: Unit postgresql.service not found.

**Steps to reproduce the problem**
```
# Common configuration options for units of all types...
[Unit]
 
# Human readable description...
Description=Foo Server (0.0.244)
 
# Where to find documentation...
Documentation=man:foo(1) man:foo(1)
 
# Don't start us until we have these things...
After=network.target                                                            \
    postgresql.service                                                          \
    auditd.service                                                              \
    remote-fs.target                                                            \
    time-sync.target                                                            \
    sound.target
 
# If the daemon is started but the database is not, start the database first...
Requires=postgresql.service
 
# Stop daemon if database is not active...
BindsTo=postgresql.service
 
# When database is stopped or restarted, so should we...
PartOf=postgresql.service
 
# Server configuration must exist before launching. This is an array type so
#  overriding it in a drop-in requires resetting the value first...
ConditionPathExists=!/home/kip/Projects/foo/build/../prefix/foo/server.conf
 
# Configuration specific to system service...
[Service]
 
# Expect notification from daemon's ::sd_notify(3) usage...
Type=notify
 
# Location daemon writes out its process ID. This isn't really necessary because
#  systemd(1) can already identify the PID because it does the forking itself...
PIDFile=/var/run/foo/foo.pid
 
# Expect service updates (e.g. ::sd_notify(3)) from the main process only...
NotifyAccess=main
 
# Don't automatically restart the service if it exits, crashes, or a timeout is
#  reached...
Restart=no
 
# Expect that the daemon should not take any longer than five minutes at most to
#  receive READY notification after attempting to activate it...
TimeoutStartSec=5m
 
# If the daemon is still running after this much time from having asked it
#  politely (SIGTERM) to quit, terminate via SIGKILL...
TimeoutStopSec=1h
 
# Path to binary. This is an array type so overriding it in a drop-in requires
#  resetting the value first...
ExecStart=/home/kip/Projects/foo/build/../prefix/bin/foo --pidfile=/var/run/foo/foo.pid --verbose
 
# Common configuration options for units of all types. This is used by
#  systemctl(1) during enable and disable commands only...
[Install]
 
# Add our daemon as a dependency for setting up a non-graphical multi-user
#  system...
WantedBy=multi-user.target
 
 
# /home/kip/.config/systemd/user/foo.service.d/foo_service_dropin.conf
[Unit]
Description=Foo Server (unit test)
After=
Requires=
BindsTo=
PartOf=
ConditionPathExists=
ConditionPathExists=!/home/kip/Projects/foo/build/Configuration/server.conf
[Service]
PIDFile=/home/kip/Projects/foo/build/foo.pid
ExecStart=
ExecStart=/home/kip/Projects/foo/build/foo --pidfile=/home/kip/Projects/foo/build/foo.pid --verbose
```

**Comment by poettering** [comment]
systemd validates all input it takes before accepting it. It will complain about all errors it finds, and if the errors are in essential configuration settings it will refuse loading it, otherwise just skip over them. ConditionXYZ= settings it doesn't consider essential, and thus complains, ignores the line and proceeds. That's what you are seeing here.

Validating all input at the moment of reading it is essential for computer security. We should never allow data that is obviously bogus loaded into memory, and even if later configuration fixes up earlier broken configuration we should still complain about the earlier broken configuration, and not hide errors.

Hence, I think systemd is doing the right thing here, it's how this *should* work.

Note that starting your unit doesn't fail because of the bad condition, but because postgresql.service is not known but you defined a Requires= dependency on it.

Hence, I don't see anything to fix here. Closing hence. Hope that makes sense?

**Comment by boucman** [comment]
Ok, this is a bit of a special case, so i'll develop it a bit, if only for the record.

what @kiplingw is trying to do is to unit-test a .service that is meant to be used as a system service, but as a user service.

drop-ins are used to avoid changing the service itself (to not modify the unit we are testing)

**Comment by keszybz** [comment]
The general rule is that each (logical) line must be syntactically valid. Having an invalid setting that is later on overriden is such a corner case that we don't want to support this (and actually I don't think we should, even if it was easy).

> unit-test a .service that is meant to be used as a system service, but as a user service

There are much easier way to do this, for example by filtering the unit file.

**Comment by poettering** [comment]
> what @kiplingw is trying to do is to unit-test a .service that is meant to be used as a system service, but as a user service.

You can't really do that: Requires= gets validated for existence, and that's what fails here, as the service listed doesn't exist in user context. If you want to validate system services you need to use the system context, otherwise the result is misleading and incomplete I fear...

**Comment by kiplingw** [comment]
Putting aside for a moment any disagreement on whether the parser should evaluate each assignment, be it syntactically or semantically prior to final assignment, and in this case, it's arguably half way between, I think the solution in this scenario is to simply write a separate .service unit test to be activated as --user.

But moving forward, this is a common scenario I'd imagine other daemon writers experience. They write a system daemon that they need to have some unit tests performed on it from within a local build tree and unprivileged. The daemon needs to be spawned, a number of unit tests performed, perhaps in parallel, on the running daemon, and the daemon shutdown cleanly. A solid Init system should of course be able to handle elegantly the first and the last of these.

It is true the spawning and shutdown could be done with each unit test, but this is not elegant, does not test any of the Init system's logic, and does not allow a large number of unit tests to hammer the single instance daemon in parallel to stress test it (e.g. think of an http / REST API server as examples). To try and re-invent this spawning, tracking, and clean shutdown logic, along with everything else useful that systemd or another Init system lends itself in this scenario to do would be painful to re-implemented in make or another build tool. This is actually fairly complicated.

**Comment by poettering** [comment]
well, systemd is a system manager, running system services unprivileged in user context is hence really hard, doing cgroups and stuff usually requires privs, or explicit delegation.

If you can use privs everything gets a lot easier as you can quickly put together a container, fire it up, do tests and shut it down again, for example with "mkosi" (which uses nspawn or qemu for that internally).
