### ISSUE TITLE
Pulling from Docker Hub fails

### ISSUE THREAD

**Issue by maxmeyer** [systemd/systemd#1130]
Hi,

I tried to pull an image from Docker Hub. But that fails. 

``` bash
% sudo machinectl pull-dkr --dkr-index-url https://registry.hub.docker.com feduxorg/centos --verify=no
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'feduxorg/centos' with reference 'latest', saving as 'centos'.
Download of https://registry.hub.docker.com/v1/repositories/feduxorg/centos/images complete.
Index lookup succeeded, directed to registry registry-1.docker.io.
HTTP request to https://auth.docker.com/v2/token/?scope=repository:feduxorg/centos:pull&service=registry.docker.com failed with code 503.
Failed to retrieve layer data.
Exiting.
```

Maybe they assume `v2`? Why is `v2` not used? Is there a commandline switch to activate this? I search the manual, but didn't found one. Is that a problem on their or your side?

**Comment by richardmaw-codethink** [comment]
`--dkr-index-url` points to an index server, not a registry server.
I'm given to understand that hub.docker.com is supposed to behave like the index for Docker v2.

Last time I looked machined was hard-coded to assume v2 repositories. The way you are communicating with the hub appears to be triggering it into thinking that you are a v1 client.

**Comment by vito** [comment]
Could this have just been a flake? Looks like it returned 503. Maybe the registry was down for a bit.

**Comment by poettering** [comment]
We decided to drop dkr support form importd, see #2133. closing.

**Comment by maxmeyer** [comment]
Ok. Does importing docker tar files work? Something similar to `docker save` and `docker load` (see https://www.fedux.org/articles/2015/10/29/ship-docker-images-to-remote-isolated-islands-in-your-infrastructure.html#export-image) for a full description.

**Comment by poettering** [comment]
we have "machinectl import-tar".
