### ISSUE TITLE
Configuration File for systemd-importd

### ISSUE THREAD

**Issue by maxmeyer** [systemd/systemd#1131]
Hi Lennart,

would it be possible to give "systemd-importd" a system/user configuration file? It's quite tedious to enter the docker index url again and again... 

``` ini
[pull-dkr]
index-url = https://registry.hub.docker.com
verify = no
```

We discussed this on the mailinglist some months ago and you added an option to your `configure`-script I think, but I normally use `systemd` from stock (Arch Linux) which does not have this option set.

**Comment by poettering** [comment]
We decided to drop dkr support form importd, see #2133. closing.
