### ISSUE TITLE
missing /etc/systemd/sleep.conf

### ISSUE THREAD

**Issue by shaba** [systemd/systemd#11310]
man for systemd-sleep.conf exist, but /etc/systemd/sleep.conf is missing.

**Comment by mrc0mmand** [comment]
This is imho expected, at least according to the `systemd-sleep.conf(5)` manpage:

```
CONFIGURATION DIRECTORIES AND PRECEDENCE
       The default configuration is defined during compilation, so a configuration file is only needed when it is necessary to
       deviate from those defaults.
```

But it's hard to say without the distro and systemd version you're filing this against.

**Comment by keszybz** [comment]
Yeah, it is missing intentionally. Originally it only contained low-level overrides, but the scope has changed over time. I guess we could consider installing it by default.

**Comment by yuwata** [comment]
I've created #11312.
