### ISSUE TITLE
"make check" broken since unified cgroup rework if cgroupfs is not mounted

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1132]
Since commit efdb02375beb ("core: unified cgroup hierarchy support") I am seeing 4 test case failures during "make check", in `test-engine`, `test-path`, `test-sched-prio`, and `test-bus-creds`. They all fail for the same reason:

```
$ SYSTEMD_LOG_LEVEL=debug ./test-path
Cannot determine cgroup we are running in: Exec format error
Assertion 'r >= 0' failed at src/test/test-path.c:47, function setup_test(). Aborting.
Aborted (core dumped)
```

This negative `r` result comes from `manager_new(MANAGER_USER, true, &tmp);`

This only happens in a build chroot, the test programs run fine in my "real" system. Once I bind-mount `/sys/fs/cgroup` into the chroot it works again, but introducing this requirement would mean that we have to stop running these tests on package build as our production buildds don't do this. Was introducing this requirement deliberate, or at least unavoidable? If so I'm okay with disabling the tests, but I'd like to ask first.

**Comment by poettering** [comment]
I'd be willing to add a patch that changes the tests in question to run cg_unified() early, and if that fails exits with the right exit code that causes the tests to be skipped... If cgroupfs is not accessible the tests are not useful anyway... I am surprised this worked earlier though...

**Comment by martinpitt** [comment]
> I am surprised this worked earlier though...

It worked because these tests already skip themselves on a handful of known errno codes. But commit efdb023 now makes `cg_unified()` return the (admittedly a bit strange) code `ENOEXEC`, which needs to be added there. Either that, or we make `cg_unified()` return an (IMHO a bit more obvious) `ENOENT`?

PR  coming.

**Comment by martinpitt** [comment]
This got merged, closing.
