### ISSUE TITLE
RFE: More uniform processing of specifiers

### ISSUE THREAD

**Issue by elgow** [systemd/systemd#11324]
The currently defined set of specifiers provide very useful parameterization of *some* things. For `--user` units in particular it would be very helpful if specifiers could be used in more places. For example:

```
[Path]
PathExists=%h/some_file_name
``` 
and 
```
[Service]
ExecStart=/usr/bin/env  %h/some_executable
```
work but 

```
[Service]
ExecStart=%h/some_executable
```
does not. 

It would be very helpful if specifiers were just handled more uniformly so that they would work in most any property value.

**Comment by bl33pbl0p** [comment]
Works in v240.
