### ISSUE TITLE
dracut fails to determine correct version from the PROJECT_VERSION string

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#11330]
**systemd version the issue has been seen with**
> 240 (latest master)

**Used distribution**
 > CentOS 7.6

This is followup for my monologue in https://github.com/systemd/systemd/pull/11226.

Since https://github.com/systemd/systemd/pull/11230 dracut (v044) fails to determine a correct systemd version on CentOS due to how the version string is parsed - see https://github.com/dracutdevs/dracut/blob/044/modules.d/00systemd/module-setup.sh#L7

e.g.:
```bash
        SYSTEMD_VERSION=$($systemdutildir/systemd --version | { read a b a; echo $b; })
        (( $SYSTEMD_VERSION >= 198 )) && return 0
```
This condition fails, because `$SYSTEMD_VERSION=239-3560-g4802097`, which results in using the default `init` [script](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/init.sh) instead of the systemd module.

By overriding the version string manually, e.g:
```bash
        echo "SYSTEMD_VERSION: $SYSTEMD_VERSION"
        SYSTEMD_VERSION=240
        (( $SYSTEMD_VERSION >= 198 )) && return 0
```
the systemd version is detected correctly and the initrd image contains a correct symlink.

This, among other things, means, that some mounts (e.g. `/dev/shm`) are mounted with unexpected options (like `/dev/shm` with `noexec`), which causes fails in our testsuite.

**Comment by mrc0mmand** [comment]
Just a note why it got missed by CentOS CI:

The `PROJECT_VERSION` string for #11230 was `240-27-g6f791ae`:
```bash
$ (( 240-27-g6f791ae >= 198 )); echo $?
0
```

However, when I tried to reproduce it, the `PROJECT_VERSION` was `239-3560-g4802097`:
```bash
$ (( 239-3560-g4802097 >= 198 )); echo $?
1
```

*Brought to you by Beauty of Bash, vol. 12.*

**Comment by keszybz** [comment]
Oh, for heaven's sake.
