### ISSUE TITLE
changed behaviour of "udevadm trigger" with missing /sys

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11333]
**systemd version the issue has been seen with**

v240

**Used distribution**
 
Debian sid
Related downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917633

Inside a chroot, /sys is usually not mounted.
Running "udevadm trigger" inside such a chroot yields the following error with v240:
```
# udevadm trigger
Failed to scan devices: No such file or directory
# echo $?
1
```

In comparsion, older udev versions handled this differently:
```
# udevadm trigger
# echo $?
0
```
This is a change in behaviour caused by https://github.com/systemd/systemd/commit/13aca847695#diff-e3e322f67caf1b94a0008af64eadfaf5R303

In Debian we have quite a few package which run `udevadm trigger` in their maintainer scripts and now fail to install unless they ignore errors via `|| true`
Possibly affected packages: https://codesearch.debian.net/search?q=udevadm+trigger

Before I start filing bug reports to get every affected package updated to use `udevadm trigger || true` I wanted to ask if this change in behaviour was intentional.
@yuwata your input would be welcome.

**Comment by poettering** [comment]
i guess we could add an explicit chroot protection to this command, like we have it for systemctl
