### ISSUE TITLE
systemd-journald CRASH due to %n$ in metadata field

### ISSUE THREAD

**Issue by dcheckoway** [systemd/systemd#1133]
Put something like `%1$` in a metadata field.  Crashorama.

```
Sep 03 07:12:14 stage1-api-2 docker[21799]: *** invalid %N$ use detected ***
Sep 03 07:12:14 stage1-api-2 systemd-coredump[13167]: Failed to get COMM, falling back to the command line.
Sep 03 07:12:14 stage1-api-2 systemd-coredump[13167]: Failed to get EXE.
```

I assume it's due to one of these functions (or sprintf or fprintf or something) tripping up on what it thinks is an "Nth" argument reference:
http://www.freedesktop.org/software/systemd/man/sd_journal_print.html

I'm working around this by deliberately escaping it with an extra leading `%` like `%%1$`.  If there's a way to avoid this, that'd be lovely!

**Comment by michich** [comment]
Are you saying systemd-journald crashed? Not the process that produces the message?
Could you paste the part of your code where you send the message?

**Comment by dcheckoway** [comment]
@michich I think you're right, that the process crashed.  It's a scala app using `logback-journal`, which does the send here:
https://github.com/gnieh/logback-journal/blob/master/src/main/java/org/gnieh/logback/SystemdJournalAppender.java#L99

**Comment by michich** [comment]
Where is the code that calls the append function, where you do the escaping? What field is the one with "%1$" in it?

Is it MESSAGE_ID? As far as I can see, it's the only one here through which one could smuggle an invalid format string. But it's supposed to be used only for 128-bit hexadecimal strings.

**Comment by poettering** [comment]
The logs suggest that something run inside a docker container crashed and that systemd's coredump tool collected a coredump. What makes you think the journal is involved at all?

Does "coredumpctl" show the collected coredump?

**Comment by dcheckoway** [comment]
@michich It happens when any metadata field has the pattern in it, but it's easy to reproduce with `MESSAGE_ID`.
@poettering Exactly.  It's a JVM running inside a Docker container.  The JVM is what crashes.  `coredumpctl` doesn't show the collected coredump.  I'm not sure where it went, to be honest.

Having slept on it, I now believe this is more a bug in `logback-journal` than `systemd`.  I think `logback-journal` just needs to escape % sequences that aren't intended for conversion.

**Comment by dcheckoway** [comment]
https://github.com/gnieh/logback-journal/pull/4
