### ISSUE TITLE
Allow whitespace before comments in unit files

### ISSUE THREAD

**Issue by najamelan** [systemd/systemd#11343]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Linux computer 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > system boots

**Unexpected behaviour you saw**
> Service xxx:  invalid argument
> Failed to isolate default target, freezing.
> I suppose boot failed because the unit that didn't load have "RequiredBy = multi-user.target", but there was no other output, no shell and similar behavior when booting in rescue mode. No other ttys available, just reboot and fix from a live distro with chroot. There was no bootlog for these boots either. Fortunately enough there was the unit name, so disabling that I was able to boot.

**Steps to reproduce the problem**
```
[Unit]

	Description = "show the date"

[Service]

	Type                = oneshot
	# RemainAfterExit     = yes
	ExecStart           = date
	ExecStop            = date
```
Systemd chokes because the comment is indented. Happens with both spaces and tabs. 
`/etc/systemd/system/date.service:7: Unknown lvalue '# RemainAfterExit' in section 'Service'`

**Suggestion**
- Ignore leading and trailing whitespace, as well as whitespace before and after "=" signs.
- Drop to some shell if multi-user.target fails so the user can at least disable units and debug things.
- Start the bootlog before multi-user.target

**Comment by keszybz** [comment]
The docs say
> Empty lines and lines starting with "#" or ";" are ignored, which may be used for commenting.

I guess we could allow comments to also start after whitespace. I see no reason to be so strict here.

Nevertheless, the warning about the line with "RemainAfterExit" is purely cosmetic: systemd warns about this line and otherwise ignores it.

> Ignore leading and trailing whitespace, as well as whitespace before and after "=" signs.

That's mostly true already, except that comment lines are not allowed to have leading whitespace.

> Drop to some shell if multi-user.target fails so the user can at least disable units and debug things.

That's already done. See `emergency.target`.

> Start the bootlog before multi-user.target

The logs are gathered since early boot. In fact, they are already gathered in the initramfs, and stored in permanent storage after the switch to the real root. `journalctl` should show logs from the start of the kernel. (There's also `/var/log/boot.log`, which is a transcript of the boot console, nowadays written by dracut, but it's not very interesting for debugging.)

**Comment by najamelan** [comment]
Thanks for the feedback.

I'm sorry for the confusion. It seems that the exec is being ran even though there is this warning. At the time of boot there was another warning about "=" missing from a line which obviously had the "=" sign, and in the process of debugging I must have resolved that but stumbling on the comment issue.

However when the unit broke, there was no shell, and nothing logged by journalctl. It's as if I never turned my machine on at that hour. It's not in `journalctl --list-boots`.  On arch apparently no `/var/log/boot.log` either. I just don't have this file.

I probably can't reproduce the error now. Don't understand what happened, only that it was very unpleasant.

Still, I propose at least getting rid of the comment warning.

**Comment by yuwata** [comment]
> At hindsight, I think systemd stopped at parsing the unit file, not at the moment of starting the service. That might be why nothing is logged.

With v240, the unit file is parsed.
```
$ systemctl cat hoge.service
# /etc/systemd/system/hoge.service
[Unit]

        Description = "show the date"

[Service]

        Type                = oneshot
        # RemainAfterExit     = yes
        ExecStart           = date
        ExecStop            = date

$ journalctl -b -u hoge.service --no-hostname
-- Logs begin at Wed 2018-12-19 14:50:29 JST, end at Tue 2019-01-08 12:45:43 JST. --
Jan 08 12:44:28 systemd[1]: /etc/systemd/system/hoge.service:5: Unknown lvalue '# RemainAfterExit' in section 'Service'
Jan 08 12:44:28 systemd[1]: Starting "show the date"...
Jan 08 12:44:28 date[9514]: Tue Jan  8 12:44:28 JST 2019
Jan 08 12:44:28 date[9515]: Tue Jan  8 12:44:28 JST 2019
Jan 08 12:44:28 systemd[1]: hoge.service: Succeeded.
Jan 08 12:44:28 systemd[1]: Started "show the date".
```

**Comment by yuwata** [comment]
I've posted #11355. If possible, please test the PR.
