### ISSUE TITLE
Log failed resource for socket units

### ISSUE THREAD

**Issue by Glandos** [systemd/systemd#11348]
**Is your feature request related to a problem? Please describe.**
A socket unit can failed with the following message:
```
janv. 07 11:34:48 belette64 systemd[1]: Failed to create listening socket: Address already in use
janv. 07 11:34:48 belette64 systemd[1]: rpcbind.socket: Failed to listen on sockets: Address already in use
janv. 07 11:34:48 belette64 systemd[1]: rpcbind.socket: Failed with result 'resources'.
```
However, in this case `rpcbind.socket` have 8 `ListenStream` and 7 `ListenDatagram` directives. This is very hard to tell which resource(s) failed.

**Describe the solution you'd like**
The failed resource should be logged in the journal. E.g.:
```
Failed to create listening socket: Address already in use (/run/rpcbind.sock)
```

**Describe alternatives you've considered**
Using `strace -e trace=%network -yy -p1`. This is not nice.

**Comment by yuwata** [comment]
I've posted #11352. If possible, could you test the PR?

**Comment by Glandos** [comment]
Sorry, I don't have a setup for compiling systemd.

But if you have a Debian (or any distribution) using `rpcbind.socket`, you can try the following:

```
# /lib/systemd/system/rpcbind.socket
[Unit]
Description=RPCbind Server Activation Socket
DefaultDependencies=no

[Socket]
ListenStream=/run/rpcbind.sock

# RPC netconfig can't handle ipv6/ipv4 dual sockets
BindIPv6Only=ipv6-only
ListenStream=0.0.0.0:111
ListenDatagram=0.0.0.0:111
ListenStream=[::]:111
ListenDatagram=[::]:111

[Install]
WantedBy=sockets.target
```
```
# /etc/systemd/system/rpcbind.socket.d/override.conf
[Socket]

# RPC netconfig can't handle ipv6/ipv4 dual sockets
BindIPv6Only=ipv6-only
ListenStream=127.0.0.1:111
ListenDatagram=127.0.0.1:111
ListenStream=[::1]:111
ListenDatagram=[::1]:111
```
Starting the unit should be enough to trigger the error.
