### ISSUE TITLE
systemd-240 fails to mount squashfs again, waiting for loop0 till timeout

### ISSUE THREAD

**Issue by mgorny** [systemd/systemd#11342]
**systemd version the issue has been seen with**
> 240 (this is a regression compared to 239)

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > I have the following in fstab:
 > ```
 > /home/mgorny/repos.ro.sqfs      /var/db/repos   squashfs        comment=systemd.automount       0 0
 > ```
 > 
 > The filesystem is mounted on boot. After unmounting it, both auto-mounting and `systemctl start var-db-repos.mount` used to mount it again.

**Unexpected behaviour you saw**
> After unmounting the filesystem once:
```
$ systemctl start var-db-repos.mount                                                                                        
A dependency job for var-db-repos.mount failed. See 'journalctl -xe' for details.
$ journalctl -xe
[...]
sty 06 10:10:11 pomiocik systemd[1]: dev-loop0.device: Job dev-loop0.device/start timed out.
sty 06 10:10:11 pomiocik systemd[1]: Timed out waiting for device /dev/loop0.
-- Subject: Unit dev-loop0.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit dev-loop0.device has failed.
-- 
-- The result is RESULT.
sty 06 10:10:11 pomiocik systemd[1]: Dependency failed for /var/db/repos.
-- Subject: Unit var-db-repos.mount has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit var-db-repos.mount has failed.
-- 
-- The result is RESULT.
sty 06 10:10:11 pomiocik systemd[1]: var-db-repos.mount: Job var-db-repos.mount/start failed with result 'dependency'.
sty 06 10:10:11 pomiocik systemd[1]: dev-loop0.device: Job dev-loop0.device/start failed with result 'timeout'.
```

**Steps to reproduce the problem**

1. Get or make a squashfs.
2. Add it to fstab as pasted above (with either automount or regular mount).
3. Reboot.
4. `umount /my/squashfs`
5. `systemctl start my-squashfs.mount`

**Comment by bl33pbl0p** [comment]
Is the loop module loaded (and does /dev/loop0 device node exist)?

**Comment by bl33pbl0p** [comment]
OK, thank you, I can reproduce this (We chatted a bit on IRC).

It looks like after the first mount, systemd polls for /proc/self/mountinfo and internally binds the mount unit to the loop device. Then, any subsequent mount unit triggers will fail as a start job for device is enqueued (but the loop device can only be plugged in when something attaches image to it) so it fails each time with JOB_DEPENDENCY result.

A workaround is to do systemctl daemon-reload after every such umount, but yes, this looks like a bug.
