### ISSUE TITLE
240.0 breaks -networkd.service in unprivileged lxc guest

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11371]
**systemd version the issue has been seen with**
> 240.0

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-networkd.service starting/working the same as v239.370 does

**Unexpected behaviour you saw**
 > systemd-networkd.service: Failed to set up mount namespacing: Permission denied
 > systemd-networkd.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-networkd: Permission denied

On the host

> audit: type=1400 audit(1547125168.853:722): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-container-default-cgns" name="/" pid=8426 comm="(networkd)" flags="rw, rslave"

**Additional info**
> host ubuntu cosmic with lxc 3.0.3 and aa 2.12

**Steps to reproduce the problem**

in the unprivileged lxc guest upgrade systemd from 239.370 to 240.0 and restart unprivileged lxc guest.

**cross references**
https://bugs.archlinux.org/task/61313
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1811248
___
@poettering @mbiebl @brauner @yuwata @evverx 

It is likely this being caused by https://github.com/systemd/systemd/commit/1beab8b0d0 which was  known at the time https://github.com/systemd/systemd/commit/1beab8b0d0#commitcomment-30393464

> This causes a lot of regressions for LXC, see [#9700 (comment)](https://github.com/systemd/systemd/issues/9700#issuecomment-418450626)
> 
> Should this commit be reverted?

and

https://github.com/systemd/systemd/issues/9700#issuecomment-418460002

>  I think that the tests have started to fail when [1beab8b](https://github.com/systemd/systemd/commit/1beab8b0d0ff2d7d1436b52d4a0c3d56dc908962) was merged. It's probably worth opening an issue because it's clearly a regression.

**Comment by tomty89** [comment]
Wonder if this is related as well:
https://bugs.archlinux.org/task/61320
