### ISSUE TITLE
kdbus: Cannot watch bus name org.gnome.GConf: Too many open files

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1137]
systemd: 225
kdbus: 0c05fbd

with kdbus enabled, I noticed problems in applications using gconf.

Looking at the journal, I get:

```
Sep 03 23:41:08 pluto systemd[866]: dbus-org.gnome.GConf.service: Cannot watch bus name org.gnome.GConf: Too many open files
Sep 03 23:41:08 pluto systemd[866]: org.gnome.GConf.busname: Bus service dbus-org.gnome.GConf.service not loaded, refusing.
Sep 03 23:41:08 pluto systemd[866]: Failed to listen on DBUS1: org.gnome.GConf.
Sep 03 23:41:26 pluto systemd[1599]: dbus-org.gnome.GConf.service: Cannot watch bus name org.gnome.GConf: Too many open files
Sep 03 23:41:26 pluto systemd[1599]: org.gnome.GConf.busname: Bus service dbus-org.gnome.GConf.service not loaded, refusing.
Sep 03 23:41:26 pluto systemd[1599]: Failed to listen on DBUS1: org.gnome.GConf.
Sep 03 23:43:16 pluto systemd[1744]: dbus-org.gnome.GConf.service: Cannot watch bus name org.gnome.GConf: Too many open files
Sep 03 23:43:16 pluto systemd[1744]: org.gnome.GConf.busname: Bus service dbus-org.gnome.GConf.service not loaded, refusing.
Sep 03 23:43:16 pluto systemd[1744]: Failed to listen on DBUS1: org.gnome.GConf.
Sep 03 23:46:43 pluto systemd[12451]: dbus-org.gnome.GConf.service: Cannot watch bus name org.gnome.GConf: Too many open files
Sep 03 23:46:44 pluto systemd[12451]: org.gnome.GConf.busname: Bus service dbus-org.gnome.GConf.service not loaded, refusing.
Sep 03 23:46:44 pluto systemd[12451]: Failed to listen on DBUS1: org.gnome.GConf.
Sep 03 23:47:09 pluto google-chrome.desktop[12914]: [12914:12914:0903/234709:ERROR:gconf_listener.cc(116)] Error with gconf key '/apps/metacity/general': Der Konfigurationsserver konnte nicht kontaktiert werden: D-BUS-Fehler: Name org.gnome.GConf is currently not owned by anyone.
```

**Comment by poettering** [comment]
kdbus kernel issue with too low maximum of matches allowed. If you compile kdbus.ko from the kdbus git repo this is supposedly fixed.

**Comment by dvdhrm** [comment]
If you mention git-commits from the out-of-tree module, please also mention the commit-message. The out-of-tree module is rebased (except for the 'master' branch), so the commit-ids are kinda irrelevant.

Anyway, I assume your head-commit is:

```
commit 0c05fbdc82fb13e2a80be4f7939e6388258195e5
Author: Daniel Mack <daniel@zonque.org>
Date:   Fri Aug 7 16:36:36 2015 +0200

    kdbus: selftests: add more name registry tests
```

Can you update your module and pick either `v4.X` or the `devel` branch? (always use `git checkout -f` with them, never use `git pull/merge`). Greg is currently on vacation so the necessary limit-bumps haven't been pushed to his tree, yet.

**Comment by dvdhrm** [comment]
Alternatively, apply the patch labeled `[PATCH] kdbus: raise hard-coded limit of matches` on top.

http://thread.gmane.org/gmane.linux.kernel/2032167

**Comment by mbiebl** [comment]
@dvdhrm This is indeed the commit and afaics the last commit in master [1].
I'm running a 4.1 kernel and the v4.1 branch doesn't have any newer commits (i.e. is identical to master)
Am I missing something?

[1] git@github.com:systemd/kdbus.git

**Comment by dvdhrm** [comment]
Ugh? The v4.1 branch differs from master:
https://github.com/systemd/kdbus/commits/v4.1

v4.1 HEAD is: 245fe938ca0907dd0db36a123a875320c96ddd35

**Comment by mbiebl** [comment]
Hm, somehow my git fetch && git reset --hard orig/v4.1 did not work. Anyways, I see the commits now.
But now I'm more confused: Why does master not have those commits? I somehow thought, master contained the canonical source and the individual branch only commits specific for that particular kernel version.

**Comment by dvdhrm** [comment]
Greg's tree is the canonical kdbus-tree. It's the ultimate authority on what patches are considered part of kdbus. In the out-of-tree module, `master` tracks Greg's tree. It's not rebased, because anything that hits Greg's tree will stay there forever. As such, we can just apply patches that go upstream onto `master` unmodified.
`v4.X` contain contain patches required for the given kernel version. However, I _also_ include development patches there, which haven't hit Greg's tree, but fix known issues. Occasionally, I also include new features or reworks, which should see wider testing before I send them to Greg.

The out-of-tree module should be perfectly fine for developers or external modules. If anyone intends to include kdbus in their kernel as an integrated module, I recommend basing this on Greg's tree. Just run `git log --oneline HEAD..gregkh/kdbus` and cherry-pick exactly these patches. Note that this will not produce bi-sectable histories! If you want to preserve bisect, you should merge Greg's tree.

**Comment by mbiebl** [comment]
thanks for the explanation @dvdhrm

**Comment by mbiebl** [comment]
Updating kdbus including 

```
commit b0d09ab45b93f09ace4405264a383faa31c59c8b
Author: David Herrmann <dh.herrmann@gmail.com>
Date:   Mon Aug 31 22:40:27 2015 +0200

    kdbus: raise hard-coded limit of matches
```

did fix the issue. Thus closing.
