### ISSUE TITLE
pam_limit does not work properly in X when systemd is 240

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#11386]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > limits like memlock and rtprio applies properly

**Unexpected behaviour you saw**
 > they seem to be applied to a certain extent but things are definitely broken

**Steps to reproduce the problem**

For example, i need rtprio set to 99 and memlock set to unlimited for jackd to start; with systemd 240, jackd does start, but I play something with `mpv -ao jack`, I can see mpv spits the following error:
```
cannot lock down memory for RT thread (Cannot allocate memory)
```
In this case, it doesn't stop jack/mpv from actually working, but on the other hand, for vfio passthrough in qemu, I also need memlock set to unlimited; with systemd 240, I can no longer start qemu as if memlock is not set/changed:
```
qemu-system-x86_64: -device vfio-pci,host=00:1b.0: VFIO_MAP_DMA: -12
qemu-system-x86_64: -device vfio-pci,host=00:1b.0: vfio_dma_map(0x7fd6ff891640, 0x0, 0x80000000, 0x7fd4f7e00000) = -12 (Cannot allocate memory)
qemu-system-x86_64: -device vfio-pci,host=00:1b.0: VFIO_MAP_DMA: -12
qemu-system-x86_64: -device vfio-pci,host=00:1b.0: vfio_dma_map(0x7fd6ff891640, 0x100000000, 0x180000000, 0x7fd577e00000) = -12 (Cannot allocate memory)
qemu-system-x86_64: -device vfio-pci,host=00:1b.0: vfio 0000:00:1b.0: failed to setup container for group 5: memory listener initialization failed for container: Cannot allocate memory
```
The weird thing is, none of these occurs if I run the programs in ttys (with the same user of course), the issue only occurs when I'm in X (I start i3-wm with `startx`/`sx`, if that matters). (And I did rebooted, see `2.` below)

Also, there's one thing I'm not sure if it's related, that is, when I "stop" X/i3-wm with `i3-msg exit`, before systemd 240, it would just terminate X and I would remain logged in in the tty as expected, but with systemd 240, I would be logged out automatically for some reason.

I am not entirely sure if it's a systemd upstream fault, but it definitely has something to do with systemd 240, as I reverted and reverted only systemd to 239 to make sure that these go away with it and comes back when I upgraded and upgraded only systemd to 240 again.

There are some more things that may be relevant:
1. In every first shutdown after upgrading to systemd 240, systemd will have problem stopping User Manager of any ever logged in users. I will to wait 2 mins for the stop job to timeout.
2. Changes to things like supplementary groups or limits of a user needs a reboot to apply in X, that is, after killing X and relogin, I can see them being updated when I'm logged in the tty, but once I start X again, I can see settings remain unchanged. This happens even when I'm with systemd 239.

**Comment by tomty89** [comment]
One update: `jackd` does not actually need memlock being set to unlimited to start, but only rtprio being set to 99. Before systemd 240, if I do not set memlock to unlimited, `jackd` will spit the error `cannot lock down memory for jackd (Cannot allocate memory)` when I start it, but it will be started anyway; with systemd 240, it will not spit the error anyway; instead, mpv will spit the error if memlock is not set to unlimited

**Comment by tomty89** [comment]
Okay just done two bisects for this issue.

First of all, https://github.com/systemd/systemd/commit/91cfdd8d29b353dc1fd825673c9a23e00c92a341 is the commit that make `cannot lock down memory for RT thread (Cannot allocate memory)` "shifts" from the starting of `jackd` to playback with `mpv -ao jack`, when I don't have `memlock` set to unlimited (or anything). I am not sure if this is a problem itself, but perhaps it gives you some hint where the bug(s) lies.

For the main problem in this issue, that is, the setting of `memlock` applies in ttys but not in X (more precisely, bash in gnome-terminal, if it matters) even after a reboot, is caused by https://github.com/systemd/systemd/commit/a17c17122c304ff3f67f1cbf119fa7116315a7df.

For the problem that pam_limit settings (and supp. groups, if they are related) only applies in X after a reboot, since I have no clue at all when it was introduced, so I can't really do a bisect for it. I suspect that it might be related to the main problem of this issue in a way (can be the root cause) though, but that's just my hunch.

@poettering Any ideas?

P.S. The problem that the user will be logged out unexpected when X is terminated appears to be an unrelated problem. I will probably do bisect for it tomorrow and open another issue.

**Comment by poettering** [comment]
Could you try #11448? There's a good chance it fixes your issue?

**Comment by poettering** [comment]
Are you sure pam_limits is in the PAM stack of "systemd-user"?

**Comment by tomty89** [comment]
> Could you try #11448? There's a good chance it fixes your issue?

https://github.com/systemd/systemd/pull/11448#issuecomment-454792345

> Are you sure pam_limits is in the PAM stack of "systemd-user"?

https://github.com/systemd/systemd/pull/11448#issuecomment-454820015

@poettering Btw, is it now an expected behaviour that user@$uid.service (and whatever under it, e.g. pulseaudio.service) remains running, even after the user is *entirely* (as in, no remaining login sessions) logged out? It's probably not related to the main problem of this issue but apparently the cause of the pre-240 problem I mentioned:

> Changes to things like supplementary groups or limits of a user needs a reboot to apply in X, that is, after killing X and relogin, I can see them being updated when I'm logged in the tty, but once I start X again, I can see settings remain unchanged. This happens even when I'm with systemd 239.

I can't see how this behaviour is desirable btw (in addition to the aforementioned problem, I don't think we would want pulse to remain either after the user is logged out?). Should I open another issue for that?

**Comment by poettering** [comment]
> @poettering Btw, is it now an expected behaviour that user@$uid.service (and whatever under it, e.g. pulseaudio.service) remains running, even after the user is _entirely_ (as in, no remaining login sessions) logged out?

For a short while it will stay around, yes. See 9afe9efb9340588db553950727a2a9672dc3db24.

**Comment by poettering** [comment]
> I can't see how this behaviour is desirable anyway (in addition to the aforementioned problem, I don't think we would want pulse to remain either after the user is logged out?). Should I open another issue for this?

Already has been reverted now. See c0f34168d4c5691fccb62e81d6d49dd2f730a17b
