### ISSUE TITLE
Invalid code exposed with GCC 9

### ISSUE THREAD

**Issue by marxin** [systemd/systemd#11394]
Using GCC 9 one can see wrong usage of FOREACH_STRING macro.
It's detailed explained in here:
https://bugzilla.opensuse.org/show_bug.cgi?id=1121387#c0

note that the same affects systemd/casync

**Comment by poettering** [comment]
So I figure the problem is that we use a STRV_MAKE() array (i.e. a compund literal) outside of the `({})` block we allocated it in.

**Comment by poettering** [comment]
I prepped a fix in #11441. Would be great if you could verify this works, as getting access to gcc 9 means work I'd rather avoid. Thanks!

**Comment by marxin** [comment]
> I prepped a fix in #11441. Would be great if you could verify this works, as getting access to gcc 9 means work I'd rather avoid. Thanks!

Yes, I can confirm that the patch fixes the issue with GCC 9!
Thanks for the patch.
