### ISSUE TITLE
networkd removes static IPv6 addresses when RA expires

### ISSUE THREAD

**Issue by Farom** [systemd/systemd#11398]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > debian stable + backports

**Expected behaviour you didn't see**
 > I expect that statically configured  IP-Addresses does stay unmodified by RouteAdvertisements and the lifetime stays forever. When using ifupdown 'valid_lft' stays 'forever'

**Unexpected behaviour you saw**
 > A configured IPv6 Address gets a lifetime and is thrown away after its lifetime ends, when radvd is stopped.

**Steps to reproduce the problem**
<file uplink.network>
[Match]
Name=en0

[Network]
DHCP=no
Address=2001:your:net:here:1d::28/64
IPv6Token=::1d:0:0:28
</file>

**Comment by yuwata** [comment]
I am not sure, but is it related to #11458? @Farom If possible, Could you test #11460?

**Comment by yuwata** [comment]
So, I guess, the address specified by `Address=` and generated address with `IPv6Token=` are same, no?
Could you paste the results of `ip addr show dev en0`?

**Comment by Farom** [comment]
> So, I guess, the address specified by `Address=` and generated address with `IPv6Token=` are same, no?

Yes. The Address is the same as the generated one.

> Could you paste the results of `ip addr show dev en0`?

```
# ip -6 a show dev en0
2: en0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2001:your:net:here:1d::28/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 86399sec preferred_lft 14399sec
    inet6 fe80::5054:ff:fe76:91d8/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by yuwata** [comment]
> > So, I guess, the address specified by `Address=` and generated address with `IPv6Token=` are same, no?
> 
> Yes. The Address is the same as the generated one.

The configuration sounds strange for me... @ssahani Please comment on this.

**Comment by ssahani** [comment]
@farom could you explain how both addresses are same? Looks arrange to me.

**Comment by Farom** [comment]
> @Farom could you explain how both addresses are same?

The Icinga-server is one of the first machines starting after a full power failure. The radvd servers are redundant virtual machines which comes up long after the virtualisation hosts were started. So i setup the IPv6 statically and they get the routes via radvd. Icinga works from minute 1 after power comes back and tells you whats broken.

**Comment by ssahani** [comment]
> So i setup the IPv6 statically and they get the routes via radvd. Icinga works from minute 1 after power comes back and tells you whats broken.

You need to chose some other address for static conf. That's why it's getting removed. but what's the issue it's not renewing ?


@yuwata https://github.com/systemd/systemd/issues/11458 here the same issue what the user was doing with DHCP.

**Comment by yuwata** [comment]
> but what's the issue it's not renewing ?

Because radvd is stopped...

> #11458 here the same issue what the user was doing with DHCP.

#11458 does not have any dynamic setting for networkd, only static address, and the same address is dynamically assigned before networkd starts (by dhclient?). I have no sympathy with the network design, but #11458 does not have any conflicts within .network file.

However, in this case, both static and dynamic setting is in .network and conflicts each other. So, networkd first assigns static address, then updates its lifetime after the dynamic address is generated. This is clearly misconfiguration, I think. At most, we can do is adding warning when networkd detects such situation.

**Comment by Farom** [comment]
> > So i setup the IPv6 statically and they get the routes via radvd. Icinga works from minute 1 after power comes back and tells you whats broken.
> 
> You need to chose some other address for static conf. That's why it's getting removed. but what's the issue it's not renewing ?

And which address do i write into my DNS?
It is not renewed if the radvd stops. And then after the lifetime ends a machine looses its statically configured network setup.

Please stop discussing about my usecase. Networkd shortens the lifetime of a statically configured address with an infinite lifetime to a finite value. This is wrong. It is wrong for IPs and for Routes. The Kernel does not do this. 

> @yuwata #11458 here the same issue what the user was doing with DHCP.

I do not think you can compare IPv6 Autocofiguration with DHCP. It may look wrong for me but its his system and his responsibility.

**Comment by ssahani** [comment]
> > but what's the issue it's not renewing ?
> 
> Because radvd is stopped...
>


They need to fix that. 
> > #11458 here the same issue what the user was doing with DHCP.
> 
> #11458 does not have any dynamic setting for networkd, only static address, and the same address is dynamically assigned before networkd starts (by dhclient?). I have no sympathy with the network design, but #11458 does not have any conflicts within .network file.
> 
> However, in this case, both static and dynamic setting is in .network and conflicts each other. So, networkd first assigns static address, then updates its lifetime after the dynamic address is generated. This is clearly misconfiguration, I think. At most, we can do is adding warning when networkd detects such situation.

Agree. We should a warning .

**Comment by ssahani** [comment]
> > > So i setup the IPv6 statically and they get the routes via radvd. Icinga works from minute 1 after power comes back and tells you whats broken.
> > 
> > 
> > You need to chose some other address for static conf. That's why it's getting removed. but what's the issue it's not renewing ?
> 
> And which address do i write into my DNS?
> It is not renewed if the radvd stops. And then after the lifetime ends a machine looses its statically configured network setup.

Fix your radvd server first. networkd is working as expected.

> 
> Please stop discussing about my usecase. Networkd shortens the lifetime of a statically configured address with an infinite lifetime to a finite value. This is wrong. It is wrong for IPs and for Routes. The Kernel does not do this.

To be precise you configured a dynamic address to static.
> 
> > @yuwata #11458 here the same issue what the user was doing with DHCP.
> 
> I do not think you can compare IPv6 Autocofiguration with DHCP. It may look wrong for me but its his system and his responsibility.

You conf also does not look right to me.

**Comment by Farom** [comment]
> > It is not renewed if the radvd stops. And then after the lifetime ends a machine looses its statically configured network setup.
> Fix your radvd server first. networkd is working as expected.

It is a network laboratory. We develop Hardware there. We stop the radvd intentionally. I expect statically configured IPs to be static.
Networkd behaves different than the kernel. I do not expect this behaviour. Thats why i opened a ticket.

I can restart networkd and get my statically configured IPs back. So the configured IPs depends on the time networkd was restarted. I'd never expect this behaviour and think this is a bug.

**Comment by Emantor** [comment]
Hi, I took a look into the [RFC 4862](https://tools.ietf.org/html/rfc4862#section-5.5.3) subheading d:
```
If the prefix advertised is not equal to the prefix of an
address configured by stateless autoconfiguration already in the
list of addresses associated with the interface (where "equal"
means the two prefix lengths are the same and the first prefix-
length bits of the prefixes are identical), and if the Valid
Lifetime is not 0, form an address (and add it to the list) by
combining the advertised prefix with an interface identifier of
the link as follows: [...]
```
which to me reads like the address  (and its lifetime) should not be replaced since it was configured already.

**Comment by yuwata** [comment]
```
 e)  If the advertised prefix is equal to the prefix of an address
      configured by stateless autoconfiguration in the list, the
      preferred lifetime of the address is reset to the Preferred
      Lifetime in the received advertisement.
```

**Comment by yuwata** [comment]
These docs are about addresses assigned by dynamically. But this issue is dynamic vs static.

**Comment by Emantor** [comment]
Does the `configured by stateless autoconfiguration` statement relate to the prefix already configured or the prefix which should be configured?

**Comment by ssahani** [comment]
> These docs are about addresses assigned by dynamically. But this issue is dynamic vs static.

yes right . 

@Emantor ```stateless autoconfiguration``` if I interpret correctly means dynamic not static and here magically both are same.

**Comment by Emantor** [comment]
@yuwata, @ssahani, I understand that this is static vs dynamic. My expectation was that the RFC which defines SLAAC also includes a specification for the situation where the address was already assigned to the interface. However it is not clear to me whether the RFC says that you should replace adresses (and their lifetimes) which were assigned through SLAAC previously or if you should replace all addresses configured for the interface.
To my understanding the RFC says that you are only allowed to replace addresses which were configured through SLAAC previously, which would exclude the statically configured address with an infinite lifetime.

**Comment by yuwata** [comment]
Hmm, I have no idea... If we can find clear statements about the issue in a RFC or any documents, then I'd like to make `networkd` obey that. But if not, I cannot find any reason to support such a configuration.

**Comment by motp** [comment]
I think, Emantor is right: rfc4862, 5.5.3.  states for the first received prefix announcement:

> If an address is formed successfully and the address is not yet in  the list, the host adds it to the list of addresses assigned to the interface, initializing its preferred and valid lifetime values from the Prefix Information option.  

This means, to my understanding: Because in this case, there is already a static assignment, the newly formed address AND the valid lifetime values from the Prefix Information option should be discarded. Otherwise, it should add the "dynamic" flag to this address assignment and furtheron manage also the lifetimes. 

I did a quick test and saw this behaviour with NetworkManager and the Linux Kernel. They only configure the Default Route, but do not touch the manually assigned address and lifetimes as long as there is no dynamic flag on the address.

Then, there is the question of Updates. The rfc states:

>  If the advertised prefix is equal to the prefix of an address configured by stateless autoconfiguration in the list, the preferred lifetime of the address is reset to the Preferred Lifetime in the received advertisement.

This means, to my understanding: Because the stateless autoconfiguration didn't happen in the first place, this whole section is irrelevant for the currently discussed cornercase. Networkd should not touch the limetime configuration, but may update the default route. 

So, the rfc is quite clear about this (IMO).

**Comment by ssahani** [comment]
> So, the rfc is quite clear about this (IMO).

Not really. RFC does not said if there is a static address. BTW how you figured out this is your static address ?  If you want to use static address why use dynamic ?

**Comment by Farom** [comment]
>  If you want to use static address why use dynamic ?

Cause you need DNS-configuration, routes and it may happen that you move your server to another network.

**Comment by yuwata** [comment]
> > If you want to use static address why use dynamic ?
> 
> Cause you need DNS-configuration, routes and it may happen that you move your server to another network.

Then, please use the follwong:
```
[IPv6AcceptRA]
UseAutonomousPrefix=no
```

Closing.
