### ISSUE TITLE
Can't set PATH environment variable via systemd-nspawn

### ISSUE THREAD

**Issue by trusch** [systemd/systemd#11392]
I can set all environment variables in my container via the command line flags, but PATH always gets overridden.

Is this a bug, or expected behaviour?

I'm using the 239 release.

**Comment by poettering** [comment]
Hmm, this is weird. nspawn will set PATH on its own, but actually --setenv= should always override that.

**Comment by trusch** [comment]
I'll post an minimal repro snippet tomorrow, I hope that will help.

**Comment by keszybz** [comment]
It works for me, I find it very unlikely that there's a bug in systemd.
```console
$ systemd-nspawn -M rawhide --bind=/home -n --setenv=PATH=/usr/sbin:/usr/bin:/sbin:/bin /bin/bash
Spawning container rawhide on /var/lib/machines/rawhide.
Press ^] three times within 1s to kill container.
bash-4.4# echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin
$ systemd-nspawn -M rawhide --bind=/home -n --setenv=PATH=/usr/sbin:/usr/bin:/sbin:/bin /bin/bash -l
Spawning container rawhide on /var/lib/machines/rawhide.
Press ^] three times within 1s to kill container.
[root@rawhide /]# echo $PATH
/usr/lib64/ccache:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin
$ systemd-nspawn -M rawhide --bind=/home -n --setenv=PATH=/usr/sbin:/usr/bin:/sbin:/bin             
Spawning container rawhide on /var/lib/machines/rawhide.
Press ^] three times within 1s to kill container.
[root@rawhide ~]# echo $PATH
/usr/lib64/ccache:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin
```
Note that systemd-nspawn starts bash as `-bash`, which has the same effect as `-l`.

Please reopen if it turns out to be a bug after all.

**Comment by asdf8dfafjk** [comment]
I know I'm by far the stupidest person in this thread but I've scoured the internet reasonably wide-- how do you guys manage to get environment variables passed using `setenv` to reflect in your shells?
