### ISSUE TITLE
LLMNR prevents DNS search domains from being used

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#11410]
Probable duplicate of #11325 but that issue has insufficient information to judge.

**systemd version the issue has been seen with**
> $ systemctl --version
systemd 240
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**

Regardless of LLMNR status, per-interface DNS search domain of `sovereign.i.intelfx.name` should be applied to an unqualified lookup of `router` (demo with LLMNR off):

```
$ systemd-resolve --status wlp2s0
Link 3 (wlp2s0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 10.159.230.1
         DNS Servers: 10.159.230.1
          DNS Domain: ~.
                      sovereign.i.intelfx.name

$ ping -c1 router
PING router.sovereign.i.intelfx.name (10.159.230.1) 56(84) bytes of data.
64 bytes from _gateway (10.159.230.1): icmp_seq=1 ttl=64 time=0.835 ms

--- router.sovereign.i.intelfx.name ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.835/0.835/0.835/0.000 ms
```

**Unexpected behaviour you saw**

When LLMNR is enabled, per-interface DNS search domain of `sovereign.i.intelfx.name` is not used during an unqualified name lookup for `router`:

```
$ systemd-resolve --status wlp2s0
Link 3 (wlp2s0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 10.159.230.1
         DNS Servers: 10.159.230.1
          DNS Domain: ~.
                      sovereign.i.intelfx.name

$ ping -c1 router
ping: router: Name or service not known
```

**Steps to reproduce the problem**

1. Get a network that provides local DNS of some form and uses per-interface DNS search domains (via DHCP option 119 or otherwise).
2. Verify that LLMNR is enabled for this particular interface.
3. Attempt to do an unqualified name lookup that should be fulfilled via DNS search domains.

**Comment by intelfx** [comment]
https://github.com/systemd/systemd/issues/11325#issuecomment-453616064 by @aaronp24 apparently describes this exact problem, but I lack sufficient knowledge to be sure of this.

**Comment by poettering** [comment]
Yes, this looks a look like #11391. Let's close this as duplicate
