### ISSUE TITLE
Behavior of FailureAction and posisbly StartLimitAction with retries

### ISSUE THREAD

**Issue by b1tninja** [systemd/systemd#11419]
Similar to issue #8398 FailureAction directive should wait till retries are exhausted

**Comment by bl33pbl0p** [comment]
Indeed.

**Comment by bl33pbl0p** [comment]
@b1tninja On second thought, I think this probably does not make sense for FailureAction=, FailureAction= is triggered from the function unit_notify. This is called on *every* sub-state change for the service, hence it must happen as soon as triggered. I expect StartLimitAction= instead to only trigger when the rate-limit has been hit (and takes similar args like this).

**Comment by b1tninja** [comment]
ok, fair enough. Closing

**Comment by b1tninja** [comment]
Just for reference... the reason I thought the current behavior was questionable, the retries are ignored in the case of FailureAction being configured, so I had to more or less manually recreate what seemed to be easily configured:

[Unit]
Description=Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
After=network.target
BindsTo=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
#FailureAction=reboot-force
OnFailure=systemd-reboot.service
StartLimitBurst=3
StartLimitIntervalSec=600

[Service]
ExecStart=/usr/bin/hostapd /etc/hostapd/%i.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
