### ISSUE TITLE
Enable protected_regular and protected_fifos sysctls

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#11414]
systemd has enabled the `fs.protected_hardlinks` and `fs.protected_symlinks` sysctls since v199 (8f27a2212ee8d6311c88ef4358953ad0d7bfa851), shortly after they became available upstream (torvalds/linux@800179c9b8a1e796e441674776d11cd4c05d61d7, first released in Linux 3.6). More recently in Linux 4.19, `fs.protected_regular` and `fs.protected_fifos` joined the club (torvalds/linux@30aba6656f61ed44cba445a3c0d38b296fa9e8f5). I think it would make sense for systemd to enable these as well.

**Comment by poettering** [comment]
Send a patch please!

**Comment by lucaswerkmeister** [comment]
Well, I thought there might be objections to this, or at least more discussion :) patch now at #11442.

**Comment by poettering** [comment]
Closing as #11442 has been merged.

**Comment by lucaswerkmeister** [comment]
Right, I forgot that “implements” isn’t one of the magic issue-closing words on GitHub.
