### ISSUE TITLE
udevadm segfaults when using --subsystem-match containing '/'

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11416]
**systemd version the issue has been seen with**

v240
git master

**Used distribution**

Debian sid
Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919206

When running udevadm with --subsystem-match= containing a '/' it segfaults.
This is a regression compared to v239.

backtrace attached.
[gdb.txt](https://github.com/systemd/systemd/files/2753547/gdb.txt)

**Comment by yuwata** [comment]
Ugh, sorry. #11417 fixes this.
