### ISSUE TITLE
Failure to set time during a short while after NTP is disabled

### ISSUE THREAD

**Issue by mine260309** [systemd/systemd#11420]
**systemd version the issue has been seen with**
systemd 239 (Also applies to 240 and master as well)

**Used distribution**
[OpenBMC 2.6.0-rc1][https://github.com/openbmc/openbmc/tree/2.6.0-rc1]

**Expected behaviour you didn't see**
* When NTP is disabled, user shall be able to set time manually;
* When NTP is enabled, user shall be unable to set time manually;

**Unexpected behaviour you saw**
* During a short while (e.g. 5~8 seconds) after NTP is disabled, user fails to set time;
* During a short while after NTP is enabled, user is still able to set time.

**Steps to reproduce the problem**
Run below commands:
```bash
timedatectl set-ntp 1
sleep 10  # Wait for a while for NTP service to start
timedatectl set-ntp 0
timedatectl set-time "2019-01-12" # This is expected to work, but it fails
echo $?
timedatectl set-ntp 1
timedatectl set-time "2019-01-12" # This is expected to fail, but it works.
echo $?

```

We got below output, which indicates that it fails to set time after ntp is disabled, and it successfully set the time after ntp is enabled.

```
Failed to set time: Automatic time synchronization is enabled
1
0
```

**Comment by yuwata** [comment]
I think, at least the case that setting time just after NTP is enabled needs to be fixed:
```
timedatectl set-ntp 1
timedatectl set-time "2019-01-12" # This is expected to fail, but it works.
```
But, for the inverse case, just after disabling NTP, I think we should reject until the NTP clients are certainly stopped for safety. WDYT?

**Comment by yuwata** [comment]
Please test #11424.
