### ISSUE TITLE
Interactive service running on boot is overwritten by systemd status messages after their disabling

### ISSUE THREAD

**Issue by thehejik** [systemd/systemd#11447]
**systemd version the issue has been seen with**
> systemd 239 (Fedora 29)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

and

> systemd 234 (SLE15-SP1)
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=hybrid

**Used distribution**
 > Fedora 29 (Workstation Edition) + SLE15-SP1 x86_64 running under qemu KVM 

**Problem description**
I would like to execute an interactive ncurses service on boot to do some user actions (for eg. to set root password). Within the service I first disable systemd status messges by sending SIGRTMIN+21 signal to PID 1 and then I run dialog command to interact with user. 

But the standard output of the interactive systemd service is often (~5 of 10 attempts) overwritten by systemd status messages output even when these messages are disabled. 

Appending "systemd.show_status=0" to kernel bootargs is not a solution for me because I would like to see status of services just before running this interactive service.

**Steps to reproduce the problem**
After installation of Fedora 29 WS perform following steps:
* remove "rhqb quite" kernel options from /etc/default/grub and run grub2-mkconfig -o /boot/grub2/grub.cfg
* install "dialog" command
* run `systemctl set-default multi-user.target`
* define a custom interactive service:
```
cat << EOF > /etc/systemd/system/interactive.service
[Unit]
Description=Simple interactive service
After=basic.service
Before=getty@tty1.service 

[Service]
Type=oneshot
Environment=SYSTEMCTL_OPTIONS=--ignore-dependencies TERM=linux
RemainAfterExit=yes
ExecStart=/bin/sh -c "/bin/kill -SIGRTMIN+21 1; setterm -msg off 2>/dev/null; dialog --msgbox \"This is sample interactive service.\" 10 40"
ExecStartPost=/bin/sh -c "/bin/kill -SIGRTMIN+20 1; setterm -msglevel 4 2>/dev/null"
StandardInput=tty
StandardOutput=tty

[Install]
WantedBy=default.target
EOF
```
* run `systemctl daemon-reload`
* run `systemctl enable interactive.service`
* perform reboot
* see at the screen

![interactive service problem](https://ibin.co/w800/4Ti4a3CsaPM9.png)

**Comment by fbuihuu** [comment]
IIRC, I saw the output of systemd-firstboot conflicting with the status messages as well.

**Comment by fbuihuu** [comment]
Maybe we could disable the status messages automatically when a service is started during boot and it uses StandardInput=tty and re-enable them once the service finished...

**Comment by boucman** [comment]
isn't that what Type=idle is kinda supposed to be ?

The semantic of that one are not clear, but it could be related...

**Comment by fbuihuu** [comment]
@boucman, something like Type=idle indeed but in this case we want something that behaves like Type=oneshot.

Type=idle behaves like Type=simple currently (except that it waits for the active jobs to be done before starting the service).

**Comment by poettering** [comment]
Is plymouth installed? if so: it turns on the status output on its own... removing it should fix this for you then.

**Comment by Vogtinator** [comment]
> Is plymouth installed?

Nope.

**Comment by fbuihuu** [comment]
Disabling systemd status messages by sending a signal make the whole mechanism asynchronous, IOW you have absolutely no guaranty that PID1 will stop emitting status messages right after sending the signal hence this issue.

**Comment by fbuihuu** [comment]
@poettering can we try to make progress here ?

It sounds like any type of services could be also be scheduled when the transaction becomes "idle", IOW the idle property seems orthogonal to the type of the service, no ?
