### ISSUE TITLE
[RFE] Add the ability to systemd-journald-audit to filter Audit events recording based on rules, like auditd does

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#11464]
**Is your feature request related to a problem? Please describe.**
There's no way to filter Audit messages to Journald

**Describe the solution you'd like**
Something similar to /etc/audit/rules.d files

Thanks!

**Comment by poettering** [comment]
any rules applied with auditctl will also apply to the audit logs journald collects. Why isn't auditctl not good enough for your usecase?

**Comment by q2dg** [comment]
Because of two reasons:
*I don't want to mess with log files: I just want to collect logs in journald
 *I don't want to have an extra service (auditd) when systemd-journald-audit works just fine. If I'm not wrong, auditctl is a client designed to work only with auditd service

So, do you mean if there some /etc/audit/rules.d/file.rules, systemd-journald-audit will parse them?

Thanks a lot for your patience

**Comment by doverride** [comment]
auditctl should work fine without running auditd (try it out), auditctl actually loads the rules from /etc/audit/.*
in other words you can just disable auditd, and create a service that calls `auditctl -R /etc/audit/audit.rules` to load your ruleset.

The only issue is that journalctl cannot compete with ausearch (journalctl does not translate the syscalls, event types etc so journalctl output its unparseable practically)

auditd does have various benefits such as dispatcher plugins but if you dont need those then, if journalctl would be good enough, journald should be fine

**Comment by doverride** [comment]
I suppose one idea would be to package the audit-utils and audit-daemon separately, and to add "journal awareness" to the audit-utils. That way you can just have audit-utils installed and use those to work with journal

**Comment by doverride** [comment]
all it does currently is give a 50% overhead of I/O since now it logs to both audit.log as well as journal. Depending on your ruleset I/O can be expensive as-is. This makes it double that

**Comment by bl33pbl0p** [comment]
@doverride

You can mask the systemd-journald-audit.socket, and it stops processing them.

**Comment by doverride** [comment]
I know but its a "hack"

**Comment by poettering** [comment]
> all it does currently is give a 50% overhead of I/O since now it logs to both audit.log as well as journal. Depending on your ruleset I/O can be expensive as-is. This makes it double that

well, the kernel audit guys promised to fix that on their side: not log to the kmsg buffer if any audit mcast  client is listing (such as journald). They never came through though.

I think the proper fix is definitely to do this in the kernel, not just give up. After all the maintainers already agreed that this would be a good idea

**Comment by doverride** [comment]
I really do not want take the risk of sounding like an asshole yet again but i don't think this is a case of giving up, its a case of knowing when you lost.
