### ISSUE TITLE
hidden feature of dot '.include' syntax is not documented / deprecated

### ISSUE THREAD

**Issue by gdraheim** [systemd/systemd#11479]
**Is your feature request related to a problem? Please describe.**

I have a bug report on  gdraheim/docker-systemctl-replacement#54 that the Puppet module for Postgres installs a 'postgresql-.service' using some '.include file' syntax. However this syntax feature is not documented anywhere. 

     .include /usr/lib/systemd/system/postgresql-10.service

The documentation on systemd-syntax does not have a hint about it. 
https://github.com/systemd/systemd/blob/master/man/systemd.syntax.xml

The documentation on systemd-unit has an invisible comment marking it as "mostly obsolete"
https://github.com/systemd/systemd/blob/master/man/systemd.unit.xml

The tool "systemd-analyze" accepts the ".include" syntax without any remark.

..... so it is actually an official syntax? Or is it deprecated but forgotten?

**Describe the solution you'd like**

It depends on what this dot-include syntax is intended for.

If it is depracated then it would be a good idea to put it on an official list of "deprecated" stuff and mark a time when the syntax will be removed.

If it is an offical feature hower then it should not be just hidden syntax. Instead it should documented on how it should be used.

Note that the feature is not completely hidden in code as there in article about it the comes out quite prominently on a google search =>

https://www.certdepot.net/rhel-7-systemd-unit-file-customization/

**Describe alternatives you've considered**

The bug reporter will also open a ticket at Puppet labs so that Puppet may be removing the usage of the dot-include syntax usage somewhen.

Other than that, systemctl.py does now support the syntax by simply making a recursive call to the parser of systemd unit files. I do not know if that is the way it should be used howerver - the https://github.com/gdraheim/docker-systemctl-replacement project allows to run Puppet / Ansible scripts on docker containers that use an operating system (centos, ubuntu, opensuse) that would otherwise require a running systemd daemon but the systemctl.py script can emulate start/stop/check service operations without the help of a real systemd. The setup of virtual machines and docker images becomes the same thing with it.

**Comment by keszybz** [comment]
The policy in systemd is to remove deprecated things from documentation but keep the implementation working for backwards compatibility. Systemd now warns when .include is used. But you are right that this is not described anywhere. I created a PR for a small patch that adds a mention in the NEWS file. Please point anyone who still uses .include to it.
