### ISSUE TITLE
MemoryDenyWriteExecute should block memfd_create

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#11473]
**Is your feature request related to a problem? Please describe.**
`memfd_create()` together with `mmap()` can be used to generate arbitrary executable memory contents, circumventing `MemoryDenyWriteExecute=yes`.

**Describe the solution you'd like**
`MemoryDenyWriteExecute=yes` should install a seccomp filter for `memfd_create()`. This could be a problem for compatibility.

**Describe alternatives you've considered**
- Administrators could install a seccomp filter for `memfd_create` with `SystemCallFilter` directive, so no changes would be needed.
However, `systemd-analyze security` could educate them about the need of such filter. Supplied systemd service unit files should also include the filter when possible.

- Compatibility could be kept while still using `MemoryDenyWriteExecute` for blocking `memfd_create()`, with a new non-boolean setting to it, like `MemoryDenyWriteExecute=strict`.

**Comment by poettering** [comment]
not sure i follow? MDWE= filters mmap() already. What does memfd_create() add new to that?

**Comment by topimiettinen** [comment]
It's not needed to use the blocked `mmap(PROT_WRITE | PROT_EXEC)`, only `PROT_EXEC`, which is allowed by MDWE=yes. Making the executable contents can be done with just `write()` to the file descriptor.

This small program demonstrates the problem:
```
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>
//#include <sys/memfd.h>
#include <sys/mman.h>

int main(int argc, const char **argv) {
        int fd;
        static const char retq = 0xc3;
        void *mem;
        void (*fn)(void);

        fd = syscall(__NR_memfd_create, argv[1], 0);
        write(fd, &retq, sizeof(retq));
        mem = mmap(NULL, sizeof(retq), PROT_EXEC|PROT_READ, MAP_PRIVATE, fd, 0);
        fn = (void (*)(void))mem;
        fn();
}

```

**Comment by poettering** [comment]
but why involve memnfd_create with that? i mean, any file you mmap is like that, memfds are in no way special there. what am i missing?

MDWE doesn't block that executable pages can be modified, it just prohibits mappings that are both.

**Comment by topimiettinen** [comment]
When using regular files there's still requirement that the process can write to a file system which is not mounted  `noexec`. This can be avoided by not giving the services access to such locations.

**Comment by poettering** [comment]
> When using regular files there's still requirement that the process can write to a file system which is not mounted `noexec`. This can be avoided by not giving the services access to such locations.

well, but IRL, does this really matter? $XDG_RUNTIME_DIR is defined to be "fully featured" in the spec, and that means that it allows executables. Hence any typical unpriv process will have some place where it can do that...

dunno, it appears to me that this is a documentation issue mostly: our docs should say clearly that this is just about mappings, and if there's another way to modify the backing store for a MAP_EXEC mapping then you are always fucked...

(note that hugepages and stuff also allow something like this...)
