### ISSUE TITLE
pulseaudio can't detect audio cards with udev 240

### ISSUE THREAD

**Issue by terrible-broom** [systemd/systemd#11496]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > Pulseaudio detects audio cards using udev.

**Unexpected behaviour you saw**
 > Pulseaudio can't detect any audio cards and lists only dummy sink.
Pulseaudio log shows:
`I: [pulseaudio] module-udev-detect.c: Found 0 cards.`
Downgrading to udev 239 fixes this problem.

**Steps to reproduce the problem**
Upgrade udev from version 239 to 240 and reboot. Pulseaudio doesn't detect any audio cards and plays sound to dummy sink.

**Comment by poettering** [comment]
and "aplay -L"?

**Comment by floppym** [comment]
> Has gentoo updated its udev?

It would be really nice if upstream would cut a new release to avoid duplicating effort on every Linux distro.
