### ISSUE TITLE
systemd-journald debug symbols missing.

### ISSUE THREAD

**Issue by MDan-ali** [systemd/systemd#11509]
GDB output:
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGABRT, Aborted.
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1 0x00007fac63b1c54a in __GI_abort () at abort.c:89
#2 0x00007fac64301fd2 in log_assert_failed () from /usr/lib/systemd/libsystemd-shared-232.so
#3 0x00007fac643b06dd in ?? () from /usr/lib/systemd/libsystemd-shared-232.so
#4 0x00007fac643b2460 in journal_file_append_entry () from /usr/lib/systemd/libsystemd-shared-232.so
#5 0x000055ab0d49f5fa in ?? ()
#6 0x000055ab0d4a14c5 in ?? ()
#7 0x000055ab0d49b31c in ?? ()
#8 0x000055ab0d49d5dd in ?? ()
#9 0x00007fac6438697b in ?? () from /usr/lib/systemd/libsystemd-shared-232.so
#10 0x00007fac643880b4 in sd_event_dispatch () from /usr/lib/systemd/libsystemd-shared-232.so
#11 0x00007fac64388279 in sd_event_run () from /usr/lib/systemd/libsystemd-shared-232.so
#12 0x000055ab0d49910a in ?? ()
#13 0x00007fac63b08260 in __libc_start_main (main=0x55ab0d498f80, argc=1, argv=0x7ffcede53d58,
init=, fini=, rtld_fini=, stack_end=0x7ffcede53d48)
at ../csu/libc-start.c:289
#14 0x000055ab0d49929a in ?? ()
(gdb)

I am not able to  find the debug symbols to complete the gdb back trace.
Please help.

**Comment by poettering** [comment]
First of all, this issue tracker is about issues in current upstream systemd versions only. At the moment that's v239 and v240. You are using 232, which is *waaaay* too old for that. Please report any such issues to your downstream distribution's bug tracker instead. They will help you.

Also, debug symbol installation is a job for your distro, we are not involved in that upstream. Please ping your downstream distro about that anyway.

FInally, we provide a template to fill in. Please do so when you submit an issue. Don't delete it and write something else. Thank you for understanding.
