### ISSUE TITLE
systemctl --user enabled service do not autostart after reboot

### ISSUE THREAD

**Issue by yhnavein** [systemd/systemd#11507]
**systemd version the issue has been seen with**
> systemd 232 and systemd 239

**Used distribution**
 > debian stretch

**Expected behaviour you didn't see**
 > My --user services (which were all enabled) should autostart after system reboot

**Unexpected behaviour you saw**
 > After reboot services were not started. State of them is as follows: (example from one, others are similar)
```
● traveler.service - traveler
   Loaded: loaded (/home/yhnavein/.config/systemd/user/traveler.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
```

**Steps to reproduce the problem**
1. Prepare service config file and put it in `~/.config/systemd/user/traveler.service`
2. `systemctl --user enable traveler`
3. `systemctl --user start traveler` to see if it works. It does
4. `sudo loginctl enable-linger yhnavein` Apparently without it all my services are killed just when I close my SSH connection...
5. Reboot
6. Check status of the service. Not working. Crying

Contents of my `traveler.service`:
```
[Unit]
Description=traveler
After=network.target
Wants=network.target

[Service]
WorkingDirectory=/home/yhnavein/apps/traveler
Type=simple
ExecStart=/usr/bin/node app.js
Restart=always
RestartSec=5
StandardError=syslog
SyslogIdentifier=traveler

[Install]
WantedBy=multi-user.target
```

A sidenote: I have 3 servers where I do use systemctl --user services and I haven't had any issues so far, but this time instead of using ubuntu I chose debian. And these services were migrated from prehistoric ubuntu 14.04. On other systems I did not even have to configure things like `loginctl enable-linger`.

Is there areny way to make it working properly on debian? Is it supported at all?

**Comment by yhnavein** [comment]
@boucman Yup. It does fix my issue. Closing

Thanks!

**Comment by DocMAX** [comment]
No fix here, although i have default.target. Linger is on.
systemctl --user reenable syncthing.service

![grafik](https://user-images.githubusercontent.com/5351323/234228789-143a87f3-11ac-4304-8e1d-e31ffe4db37d.png)

It works if i reastart user@1000.service
