### ISSUE TITLE
systemd-logind failures

### ISSUE THREAD

**Issue by gaizeror** [systemd/systemd#11503]
**systemd version the issue has been seen with**
> 219-62.el7_6.2

**Used distribution**
 > Centos7

**Unexpected behaviour you saw**
 > SSH to servers takes lots of time (almost a minute), every ssh based application we use (Ansible/Paramiko/Fabric) fails.

**Steps to reproduce the problem**
* yum install -y systemd
* reboot

It happens to all of our servers, but not always, most of the times when we boot the servers, there is this problem and we have to restart it again and again untill it works.

Things that I have already tried:
1. Update to latest systemd
2. Reinstall systemd
3. Disable SELINUX
4. Reboot server
5. Recreation of servers

Image:
<img width="1436" alt="systemd problems" src="https://user-images.githubusercontent.com/18627927/51437414-b8acec00-1ca6-11e9-8778-be9a7c2f39ca.png">

**Comment by keszybz** [comment]
Sorry, but we don't deal with bugs in old systemd versions upstream. Please take this to the maintainers of your distributions. We simply don't have the resources.
