### ISSUE TITLE
Rotate screen button not sending XF86RotateWindows after moving from v224 -> v225 on Dell XPS12 9Q33

### ISSUE THREAD

**Issue by seragunn** [systemd/systemd#1151]
In v224 xev registers the following when the button is pressed down (nothing on release).

```
KeyPress event, serial 36, synthetic NO, window 0x2200001,
    root 0xd4, subw 0x0, time 2571504, (178,178), root:(1138,236),
    state 0x40, keycode 161 (keysym 0x1008ff74, XF86RotateWindows), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x2200001,
    root 0xd4, subw 0x0, time 2571510, (178,178), root:(1138,236),
    state 0x40, keycode 161 (keysym 0x1008ff74, XF86RotateWindows), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x2200001,
    root 0xd4, subw 0x0, time 2571514, (178,178), root:(1138,236),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

However in v225 the XF86RotateWindows up/down events are not sent, just Super_L.

This is on Arch Linux with kernel version 4.1.6.

**Comment by poettering** [comment]
@martinpitt any idea about issues like these?

**Comment by martinpitt** [comment]
@trevorgunn , I don't see relevant changes in `git diff v224..v225 hwdb/`, so I need some further info: Can you please install `evtest`, run it as root, select the keyboard, and give me the output when you press/release the rotate key? If there is no reaction to it at all, please try other devices which might sound plausible ("Extra Buttons", or "WMI" -- you can ignore power/lid switches, cameras, etc.).

**Comment by seragunn** [comment]
With 224:

```
Event: time 1441463787.231203, -------------- SYN_REPORT ------------
Event: time 1441463790.732167, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1441463790.732167, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 1
Event: time 1441463790.732167, -------------- SYN_REPORT ------------
Event: time 1441463790.734099, type 4 (EV_MSC), code 4 (MSC_SCAN), value 65
Event: time 1441463790.734099, type 1 (EV_KEY), code 153 (KEY_DIRECTION), value 1
Event: time 1441463790.734099, -------------- SYN_REPORT ------------
Event: time 1441463790.737144, type 4 (EV_MSC), code 4 (MSC_SCAN), value 65
Event: time 1441463790.737144, type 1 (EV_KEY), code 153 (KEY_DIRECTION), value 0
Event: time 1441463790.737144, -------------- SYN_REPORT ------------
Event: time 1441463790.744082, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event time 1441463790.744082, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 0
```

With 225:

```
Event: time 1441463957.514662, -------------- SYN_REPORT ------------
Event: time 1441463960.228627, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1441463960.228627, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 1
Event: time 1441463960.228627, -------------- SYN_REPORT ------------
Event: time 1441463960.231401, type 4 (EV_MSC), code 4 (MSC_SCAN), value 65
Event: time 1441463960.231401, -------------- SYN_REPORT ------------
Event: time 1441463960.238027, type 4 (EV_MSC), code 4 (MSC_SCAN), value 65
Event: time 1441463960.238027, -------------- SYN_REPORT ------------
Event: time 1441463960.246360, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1441463960.246360, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 0
```

**Comment by martinpitt** [comment]
So with 225 there is no `EV_KEY` event _at all_ for the rotation key. I had expected a wrong key code, but this looks deeper than just a broken hwdb map. Did you really just switch the systemd version, or is there a different kernel involved as well? (neither systemd nor udev are directly in between the line of communication between the kernel, evdev, and evtest).

It could perhaps be that the driver doesn't report `EV_KEY` events if there is no key code assigned. So let's compare: Can you please run

```
udevadm info  --export-db > 224.txt
```

then update to 225 again, and do the same command with `> 225.txt`, then put both files into a pastebin and link them here? Thanks!

**Comment by seragunn** [comment]
224: http://pastebin.com/NmaAC7RU

225: http://pastebin.com/myd7LW1f

There's no difference between the packages other than systemd.

Edit: accidentally pasted twice for the v224 text.

**Comment by extermistmonk** [comment]
I have the same issue happening on a Thinkpad x201t. evtest shows the following when I press the button:

```
Event: time 1441932512.198133, -------------- SYN_REPORT ------------
Event: time 1441932512.498496, type 4 (EV_MSC), code 4 (MSC_SCAN), value 6c
```

**Comment by poettering** [comment]
@martinpitt does the stuff @trevorgunn help you in any way?

**Comment by martinpitt** [comment]
There's no relevant difference between the 224 and 225 udevadm dumps either, so I'm afraid that didn't help. Could you try and disable the keyboard builtin with

```
touch /etc/udev/rules.d/60-evdev.rules
```

and rebooting? Do you still only get an `MSC_SCAN` event without an `EV_KEY` event then? (the key code is likely wrong, but you should at least get _some_ key code).
- If there's still no key event, then I'm afraid I don't have the slightest idea right now what udev could do to the kernel to completely drop the `EV_KEY` event. 
- If there is a key event, please run
  
  ```
  strace -fvvs1024 -o /tmp/trace udevadm test-builtin keyboard /devices/platform/i8042/serio0/input/input0/event0
  ```
  
  and copy&paste the result and pastebin `/tmp/trace`. After that, does the `EV_KEY` event once again stop appearing?
  
  If this case is true then it would really be a miracle as the keyboard builtin didn't change at all between 224 and 225. But let's verify this, in case that version was e. g. built against different kernel headers.

**Comment by martinpitt** [comment]
In issue #1440 and #1539 we discovered that assignments to the "direction" key are broken. Are you able to check PR #1558 if that happens to fix this issue? There's a chance that this fixes this issue too. Thanks!

**Comment by seragunn** [comment]
No luck with `/etc/udev/rules.d/60-evdev.rules`. I'll get back to you on the PR.

**Comment by seragunn** [comment]
That fixed it!

**Comment by martinpitt** [comment]
Cool, thanks trevor. Closing this feels a bit premature, but as we have two other open issues for the rotate key these will do, so let's keep it closed if you agree.

**Comment by seragunn** [comment]
Yeah sorry, I like pushing buttons and thank you for coming up with a solution.
