### ISSUE TITLE
systemd-nspawn: unnecessary SIGPIPE with no child IO

### ISSUE THREAD

**Issue by owtaylor** [systemd/systemd#11533]
**systemd version the issue has been seen with**
systemd-239-3.fc29.x86_64

**Used distribution**
Fedora

**Unexpected behaviour you saw**
If the stdout of systemd-nspawn is closed before it exits, it dies with SIGPIPE, even if the child isn't trying to write anything

**Steps to reproduce the problem**
`strace systemd-nspawn -q -D <path-to-any-image> true | true`

produces:

```
[...]
copy_file_range(5, NULL, 1, NULL, 9223372036854775807, 0) = -1 EINVAL (Invalid argument)
sendfile(1, 5, NULL, 9223372036854775807) = -1 EINVAL (Invalid argument)
fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x5, 0x2), ...}) = 0
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
fcntl(1, F_GETFL)                       = 0x1 (flags O_WRONLY)
splice(5, NULL, 1, NULL, 9223372036854775807, 0) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=7588, si_uid=0} ---
```

**Comment by poettering** [comment]
urks. SIGPIPE...
