### ISSUE TITLE
timesyncd: Synchronized to time server is only printed first, not each time

### ISSUE THREAD

**Issue by nh2** [systemd/systemd#11548]
**systemd version the issue has been seen with**
> 237

**Expected behaviour you didn't see**

`journalctl -u systemd-timesyncd.service` shows `Synchronized to time server ... ` whenever it synchronised the time to a time server.

**Unexpected behaviour you saw**

It shows the message only the first time in the unit's lifetime. This is confusing when investigating clock drift problem, because it suggests that timesyncd only synced at boot, and you cannot tell when it synced last.

Commit 481b3f9e998d1981e01915bed34f55ea99af1542 introduced this logic.

I think either the message should be printed on every sync, or the message text should be updated to indicate that this is about the _first_ contact with that time server, e.g. `Synchronized to time server for the first time`, so that the user is not surprised by the lack of further messages.

**Comment by nh2** [comment]
> or the message text should be updated to indicate that this is about the _first_ contact with that time server

If you want to go for this route, I've made PR #11549 for it.

**Comment by brubbel** [comment]
@nh2 The new message sounds weird.
> Synchronized to time server for the first time 193.104.37.238:123 (2.debian.pool.ntp.org).

**Comment by keszybz** [comment]
@brubbel please file a new issue. Comments on old PRs are easy to overlook.
