### ISSUE TITLE
nspawn boot through qemu hangs

### ISSUE THREAD

**Issue by fgervais** [systemd/systemd#11557]
**systemd version the issue has been seen with**
> systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

**Expected behaviour you didn't see**
 > Was expecting to boot an armhf root filesystem through:
sudo systemd-nspawn -bD root_rw --bind ~/PC/qemu-static/qemu-arm-static-v3.1.0-2:/usr/bin/qemu-arm-static

**Unexpected behaviour you saw**
 > Boot hangs at
/usr/bin/qemu-arm-static /usr/bin/journalctl --flush

> That process hangs using 100% cpu (single thread) and if I strace -p on it I get that in a loop:
**getsockopt(31, SOL_SOCKET, SO_PEERSEC, 0x7ffc54279168, [4]) = -1 ERANGE (Numerical result out of range)**

**Steps to reproduce the problem**

- Build buildroot v2018.11 for arm 32bits
- Try to launch the boot image using the nspawn command above

**Comment by fgervais** [comment]
I tried multiple qemu versions up to 2.0.0 and get the same behavior on all of them.

Would different kernel versions the next best thing to try out?

**Comment by poettering** [comment]
hmm, so your host is x86-64 but the container is arm and you use the static qemu translation stuff through binfmt to make the binaries executable?

It appears that there's a bug in qemu's translation layer for SO_PEERSEC. The semantics of the sockopt go like this: we specify a buffer to it, and if it is too small, getsockopt() returns ERANGE, and sets the size actually needed. We then free the buffer and try again with the right size, and call back into getsockopt() again. This appears to result in an endless loop however for you, i.e. it appears that the size returned is not actually the size really needed, and thus we end up in a tight loop.

This is really something to fix in qemu's translation code, as it appears.

**Comment by fgervais** [comment]
Yes this is it, thanks for taking the time to answer even though this is a pretty twisted use-case.

I will look on qemu's side then.

**Comment by lueschem** [comment]
I am also facing this issue when running a Debian buster arm64 container (using qemu 3.1) on Ubuntu 18.04 amd64.
Can you point me to a location where this is followed up on the qemu side?
Let me know if I can help something!

**Comment by lueschem** [comment]
For others that might be affected - here is the report I did on QEMU/Launchpad:
https://bugs.launchpad.net/qemu/+bug/1823790
