### ISSUE TITLE
Regression: nofail no longer causes devices to mount asynchronously

### ISSUE THREAD

**Issue by CyberShadow** [systemd/systemd#11558]
systemd.mount says the following on `nofail`:

> Moreover the mount unit is not ordered before these target units. This means that the boot will continue without waiting for the mount unit and regardless whether the mount point can be mounted successfully.

This doesn't seem to be true any more in systemd 240.

A bisection points at d54bab90e64f70c1ecf9b0683a98adb8485ed09e as the culprit. Reverting the commit on master also restores the previous behavior.

Here is a comparison of `critical-chain` on my machine before and after d54bab90e64f70c1ecf9b0683a98adb8485ed09e.

Before:

```
nodm.service @18.700s
└─basic.target @3.925s
  └─sockets.target @3.925s
    └─virtlogd-admin.socket @5.806s
      └─sysinit.target @3.915s
        └─sys-fs-fuse-connections.mount @25.694s +4ms
          └─systemd-modules-load.service @189ms +17ms
            └─systemd-journald.socket @187ms
              └─system.slice @177ms
                └─-.slice @177ms
```

After:

```
nodm.service @1min 45.637s
└─basic.target @1min 31.577s
  └─sockets.target @1min 31.577s
    └─virtlogd-admin.socket @1min 35.908s
      └─sysinit.target @1min 31.565s
        └─systemd-update-done.service @1min 31.526s +38ms
          └─ldconfig.service @1min 31.063s +460ms
            └─local-fs.target @1min 31.060s
              └─run-user-1003.mount @1min 32.507s
                └─local-fs-pre.target @3.138s
                  └─lvm2-monitor.service @174ms +2.963s
                    └─lvm2-lvmetad.service @190ms
                      └─systemd-journald.socket @172ms
                        └─-.mount @167ms
                          └─system.slice @167ms
                            └─-.slice @167ms
```

~~Looking at the commit message in question, it seems the commit is intended as a refactoring, and from what I see can be safely reverted as a workaround. It's not clear to me what "as they should only be generated if default deps are on" refers to though, as from my quick glance, the code in question seems to be executed pretty much unconditionally.~~

**Comment by yuwata** [comment]
@CyberShadow Could you test #11558?

**Comment by CyberShadow** [comment]
@yuwata #11562 fixes the issue for me, thanks.

How would one avoid the `local-fs.target` dependency with an explicit (not fstab) systemd `.mount` unit?

**Comment by yuwata** [comment]
I guess setting `Options=nofail` in the mount unit also works. No?

I noticed that we also need to update systemd.mount(5).
