### ISSUE TITLE
I need a pre_remove scriptlet to check if users have a user service enabled and stop it for them BEFORE the package manager removes the executable... how?

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#1156]
I need a package manager to call a pre_remove scriptlet that will use `systemd --user` to check if users have a user service active, and if so, stop it for them before removing the executable.  Below is what I came up with but when root (the package manager) runs it, none of the systemctl --user commands work since root has no D-Bus connection.

Is there an alternative or tweak to my code to achieve the expected result?

```
users=$(getent passwd | grep home | awk -F: '{print $1}' | awk 1 ORS=' ')
for i in $users; do
 running="$(su $x -c 'systemctl --user is-active psd')"
 if [[ "$running" = "active" ]]; then
  su "$i" -c 'systemctl --user stop psd.service'
 fi
done
```

Output on a 2-user system when executed as root:

```
Failed to get D-Bus connection: No such file or directory
Failed to get D-Bus connection: No such file or directory
```

Thank you.

**Comment by poettering** [comment]
This is not supported, sorry. privileged code should not connect and be client to unprivileged client code. That's simply the wrong way round.

I fear what you are trying to do is not supported. It's not a problem intrinsic to systemd though, it's the way how things are on UNIX/Linux with package managers, for any program.

Also, please understand that this is a bug tracker, not a help forum. Please redirect questions like yours to the systemd mailing list instead. Thanks!
