### ISSUE TITLE
Stop jobs for secondary swap units remain endlessly when primary swap unit fails to stop

### ISSUE THREAD

**Issue by d-hatayama** [systemd/systemd#11577]
**systemd version the issue has been seen with**
> ...

v241-rc1

**Used distribution**
 > …

fedora release 29

**Expected behaviour you didn't see**
 > …

When primary swap unit fails to get stopped, the failure is expanded
to all the remaining stop jobs of the corresponding secondary swap
units.

**Unexpected behaviour you saw**
 > …

When primary swap unit fails to get stopped, all the remaining stop
jobs of the corresponding secondary swap remain endlessly.

**Steps to reproduce the problem**

There is a primary swap unit dev-mapper-fedora\x2dswap.swap and
secondary swap units that follow the parimary swap unit on this system
as follows:

```
# LANG=C systemctl --no-pager --no-legend list-units --type=swap --all
dev-disk-by\x2did-dm\x2dname\x2dfedora\x2dswap.swap                                                          loaded active active /dev/disk/by-id/dm-name-fedora-swap
dev-disk-by\x2did-dm\x2duuid\x2dLVM\x2dyuXWpCCIurGzz2nkGCVnUFSi7GH6E3ZcQjkKLnF0Fil0RJmhoLN8fcOnDybWCMTj.swap loaded active active /dev/disk/by-id/dm-uuid-LVM-yuXWpCCIurGzz2nkGCV
nUFSi7GH6E3ZcQjkKLnF0Fil0RJmhoLN8fcOnDybWCMTj
dev-disk-by\x2duuid-2dc8b9b1\x2da0a5\x2d44d8\x2d89c4\x2d6cdd26cd5ce0.swap                                    loaded active active /dev/disk/by-uuid/2dc8b9b1-a0a5-44d8-89c4-6cdd2
6cd5ce0
dev-dm\x2d1.swap                                                                                             loaded active active /dev/dm-1
dev-fedora-swap.swap                                                                                         loaded active active /dev/fedora/swap
dev-mapper-fedora\x2dswap.swap                                                                               loaded active active /dev/mapper/fedora-swap
```

As a preparation, replace swapoff command with false command to make
swapoff command intentionally fail.

```
# mv /usr/sbin/swapoff /usr/sbin/swapoff.orig
# cp /usr/bin/false /usr/sbin/swapoff
# chcon --reference=/usr/sbin/swapoff.orig /usr/sbin/swapoff
```

Try to stop the primary swap unit and confirm its failure:

```
# LANG=C systemctl --no-pager stop dev-mapper-fedora\\x2dswap.swap
Job for dev-mapper-fedora\x2dswap.swap failed.
See "systemctl status "dev-mapper-fedora\\x2dswap.swap"" and "journalctl -xe" for details.
```

Then, there are still the running stop jobs for all the secondary swap units:

```
# systemctl list-jobs
 JOB UNIT                                                                                                         TYPE STATE
3233 dev-disk-by\x2duuid-2dc8b9b1\x2da0a5\x2d44d8\x2d89c4\x2d6cdd26cd5ce0.swap                                    stop running
3232 dev-dm\x2d1.swap                                                                                             stop running
3231 dev-disk-by\x2did-dm\x2duuid\x2dLVM\x2dyuXWpCCIurGzz2nkGCVnUFSi7GH6E3ZcQjkKLnF0Fil0RJmhoLN8fcOnDybWCMTj.swap stop running
3230 dev-disk-by\x2did-dm\x2dname\x2dfedora\x2dswap.swap                                                          stop running
3234 dev-fedora-swap.swap                                                                                         stop running

5 jobs listed.
```

This remains endlessly because their JobTimeoutUSec is infinity:

```
# LANG=C systemctl show -p JobTimeoutUSec dev-fedora-swap.swap
JobTimeoutUSec=infinity
```

**Comment by d-hatayama** [comment]
If this issue happens during system shutdown, the system shutdown appears to get hang and the system will be forcibly shutdown or rebooted 30 minutes later by the following configuration:

```
# grep -E "^JobTimeout" /usr/lib/systemd/system/reboot.target
JobTimeoutSec=30min
JobTimeoutAction=reboot-force
```

The scenario in the real world seems that there is some service unit with KillMode=none,
processes whose memory is being swapped out are not killed during stop operation
in the service unit and then swapoff command fails.

On the other hand, it works well in successful case of swapoff command because the
secondary jobs monitor /proc/swaps file and can detect deletion of swap file.

**Comment by d-hatayama** [comment]
I created PR#13182 that fixes this issue. Any comments?

**Comment by d-hatayama** [comment]
Any comments? Or there is no comments because there are two failures of CentOS CIs, right? Although they doesn't seem to be caused by the change by my PR...

**Comment by yuwata** [comment]
The PR is simply not reviewed yet. Please wait for a while, sorry.

**Comment by julien-lecomte** [comment]
I have a similar issue with systemd v241 on a debian:buster with an encrypted ext4 swap. The easiest workaround to be able to get the laptop to boot and work again was to remove the swap from the fstab.
