### ISSUE TITLE
remote logging no longer works with libmicrohttpd

### ISSUE THREAD

**Issue by chowbok** [systemd/systemd#11571]
At some point, systemd-journal-upload stopped working with libmicrohttpd. systemd-journal-upload doesn't send a Content-Length: header, and therefore libmicrohttpd rejects the upload with a 411 HTTP error. Here's an example session:

```
POST /upload HTTP/1.1
Host: myhost.example
Transfer-Encoding: chunked
Content-Type: application/vnd.fdo.journal

HTTP/1.1 411 Length Required
Connection: close
Content-Length: 35
Content-Type: text/plain
Date: Thu, 24 Jan 2019 01:21:41 GMT
```
The libmicrohttpd maintainers recognize this as a bug (according to the HTTP/1.1 spec, it's okay to omit "Content-Length" if you specify "Transfer-Encoding: chunked"), but they say they won't have time to fix it in the near future. So... either somebody else is going to have to send them a patch, or systemd-journal-remote is going to have to invoke some other method of receiving remote logs.

**Comment by bedouin67** [comment]
On Arch I noticed that behavior starting with systemd 240.34. Downgrading to 240.0 and journal-upload -> journal-remote works without the 411 error.

**Comment by bedouin67** [comment]
Has this been addressed? I've been holding back systemd updates for a while now due to the broken remote journaling. I'd like to get back to current releases, obviously.

**Comment by bedouin67** [comment]
Checked with latest systemd stable, issue still exists. Journal-upload -> journal-remote DOES NOT WORK AT ALL! I can't believe nobody else is using distributed logs and runs into the same issue?

**Comment by stueja** [comment]
I have just run into the same situation. 
```
[bbx@server ~]# systemctl status systemd-journal-upload.service
● systemd-journal-upload.service - Journal Remote Upload Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-journal-upload.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-03-10 22:16:48 CET; 6min ago
     Docs: man:systemd-journal-upload(8)
  Process: 1143 ExecStart=/usr/lib/systemd/systemd-journal-upload --save-state (code=exited, status=1/FAILURE)
 Main PID: 1143 (code=exited, status=1/FAILURE)
   Status: "Shutting down..."

Mar 10 22:16:48 server systemd[1]: Started Journal Remote Upload Service.
Mar 10 22:16:48 server systemd-journal-upload[1143]: Upload to http://a.b.c.d:19532/upload failed with code 411: gth Required
Mar 10 22:16:48 server systemd[1]: systemd-journal-upload.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 22:16:48 server systemd[1]: systemd-journal-upload.service: Failed with result 'exit-code'.

```
I could really need some gth here.

**Comment by yuwata** [comment]
I've created #11953.

**Comment by stueja** [comment]
Installed `systemd 241 (241.67-1-arch)` on two hosts, behavior is still the same.

```
Apr 02 00:39:40 server systemd[1]: Started Journal Remote Upload Service.
Apr 02 00:39:40 server systemd-journal-upload[448]: Upload to http://192.168.122.11:19532/upload failed with code 411: gth Required
Apr 02 00:39:40 server systemd[1]: systemd-journal-upload.service: Main process exited, code=exited, status=1/FAILURE
Apr 02 00:39:40 server systemd[1]: systemd-journal-upload.service: Failed with result 'exit-code'.

```

**Comment by yuwata** [comment]
@stueja `systemd 241 (241.67-1-arch)` does not include this PR.

**Comment by stueja** [comment]
Oh, sorry then. Is there an easy method to find this information myself? ('easy' compared to searching the pr# in any given release).

**Comment by stueja** [comment]
Works wonderfully in v242.

**Comment by heyakyra** [comment]
Is this the same issue or something else? It says "Content-Length hHTTP/1.1 411 Length" instead of "gth Required".

```
● systemd-journal-upload.service - Journal Remote Upload Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-journal-upload.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-05-08 16:35:03 CDT; 13min ago
     Docs: man:systemd-journal-upload(8)
 Main PID: 26659 (code=exited, status=1/FAILURE)
   Status: "Shutting down..."

May 08 16:35:03 localhost.localdomain systemd[1]: Started Journal Remote Upload Service.
May 08 16:35:03 localhost.localdomain systemd-journal-upload[26659]: Upload to http://192.168.1.201:19532/upload failed with code 411: Content-Length hHTTP/1.1 411 Length
May 08 16:35:03 localhost.localdomain systemd[1]: systemd-journal-upload.service: Main process exited, code=exited, status=1/FAILURE
May 08 16:35:03 localhost.localdomain systemd[1]: systemd-journal-upload.service: Failed with result 'exit-code'.
```

It looks like the newer version of systemd isn't available in f30. Are there no workarounds for v241?

**Comment by yuwata** [comment]
@heyakyra Please file that in RedHat Bugzilla and request the fix to be back-ported.

**Comment by heyakyra** [comment]
> The libmicrohttpd maintainers recognize this as a bug (according to the HTTP/1.1 spec, it's okay to omit "Content-Length" if you specify "Transfer-Encoding: chunked"), but they say they won't have time to fix it in the near future.

@chowbok Is there a bug report this was mentioned in just for reference? I'm finding their tracker extremely difficult to navigate/search. For example, here's a link to their tickets, which is empty unless you clear the (what should already be clear) filter: https://bugs.gnunet.org/view_all_bug_page.php?filter=5cd4abd2cc443

> @heyakyra Please file that in RedHat Bugzilla and request the fix to be back-ported.

Reported: https://bugzilla.redhat.com/show_bug.cgi?id=1708213

Although I've now installed v242 from the rawhide repository, and still get the same error as I pasted above, so I guess it is a different issue. Maybe I've misconfigured something.

**Comment by yuwata** [comment]
> Although I've now installed v242 from the rawhide repository, and still get the same error as I pasted above, so I guess it is a different issue. Maybe I've misconfigured something.

@heyakyra If it is not caused by misconfiguration, then please file as a new bug with your configs and debugging logs. Thank you.

**Comment by mbiebl** [comment]
> Although I've now installed v242 from the rawhide repository, and still get the same error as I pasted above, so I guess it is a different issue. Maybe I've misconfigured something.

I assume you rebooted your system(s) or at least restarted the affected services?

**Comment by chowbok** [comment]
@heyakyra No, I just reported it to their mailing list. The thread is [here](http://lists.gnu.org/archive/html/libmicrohttpd/2019-01/msg00018.html) if you want to read it.
