### ISSUE TITLE
systemd 241 doesn't set wireguard peer endpoint

### ISSUE THREAD

**Issue by Hello71** [systemd/systemd#11579]
**systemd version the issue has been seen with**
systemd 241_rc1, regression from 240

**Used distribution**
Gentoo Linux

**Steps to reproduce**
set wireguard endpoint in netdev. I used IPv4 literal with port, possibly that is relevant.

**Expected results**
wireguard endpoint is set

**Actual results**
wireguard endpoint is not set

**Additional information**
probably caused by #11418 (cc @yuwata).

**Comment by yuwata** [comment]
Could you provide logs of network and relevant kernel logs? Also, if possible, please provide a simple reproducer.

**Comment by yuwata** [comment]
Ah, indeed, I can reproduce the issue, and confirm that e1f717d4a02e15ae11a191dd4962b2f4d117678d fixes this issue.

**Comment by yuwata** [comment]
Fix is waiting in #11580. If possible, please test the PR. Thank you.

**Comment by MorphBonehunter** [comment]
As https://github.com/systemd/systemd/commit/e1f717d4a02e15ae11a191dd4962b2f4d117678d is also in systemd-stable/tree/v240-stable, please backport this fix also to the 240er branch (i'm using arch linux and it is broken there atm).

**Comment by yuwata** [comment]
@MorphBonehunter https://github.com/systemd/systemd-stable/pull/39
