### ISSUE TITLE
usb-gadget target

### ISSUE THREAD

**Issue by andrzejtp** [systemd/systemd#11587]
Linux can be run on a device meant to act as a USB peripheral. In order for a machine to act as such a USB device it has to be equipped with a UDC - USB Device Controller.

I would like to have a target reached when UDC becomes available. It can be used for activating e.g. a service unit which composes a USB gadget with configfs and activates it. The service unit can specify a WantedBy dependency and can be controlled with systemctl enable.

I created a pull request:  units: add usb-gadget target #11586.

**Comment by poettering** [comment]
#11586 has been merged. Closing.
