### ISSUE TITLE
systemd-networkd don't set mac addres for VLAN interface

### ISSUE THREAD

**Issue by napaster** [systemd/systemd#11585]
**systemd version the issue has been seen with**
> 240.34-3

**Used distribution**
 > ArchLinux testnetwork 4.17.13-arch1-1-nfcustom #1 SMP PREEMPT Tue Aug 7 14:54:21 +07 2018 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > Set an address different from the parent mac interface on the vlan interface

**Unexpected behaviour you saw**
 > If you install a great mac address, the interface either does not rise at all, or rises with the original mac address
![default](https://user-images.githubusercontent.com/10761151/51885304-804f9100-23bd-11e9-8ee5-32b424e84d6a.png)
**Steps to reproduce the problem**

- 99-default.link
empty
- gig0.link 

> [Match]
MACAddress=00:1a:4a:4b:1c:63
[Link]
Name=gig0

- gig0.network

> [Match]
MACAddress=00:1a:4a:4b:1c:63
[Network]
LLDP=true
EmitLLDP=true
Address=100.100.101.41/24
Gateway=100.100.101.1
DNS=8.8.8.8
DNS=8.8.4.4
VLAN=vlan123
[Link]

- vlan123.link

> [Match]
OriginalName=vlan123
[Link]
Description=testvlan
MACAddress=10:c3:7b:4f:58:a4
MTUBytes=1500

Systemd-newtorkd docs
[Link] section
    MACAddressPolicy= persistent or random addresses, or
    MACAddress= a specific address

- vlan123.netdev

> [NetDev]
Name=vlan123
Kind=vlan
[VLAN]
Id=123

- vlan123.network

> [Match]
Name=vlan123
[Network]
Description=testvlan
Address=10.100.21.62/26
[Link]

and restart test machine

**Comment by yuwata** [comment]
I thought that `MACAddress=` or `MTUBytes=` should be in .netdev file. But it does not work...
```
test1: Could not join netdev: Cannot assign requested address
```

@ssahani Please comment on this.

**Comment by yuwata** [comment]
Hmm, but by `ip link add` command, the mac address can be set arbitrary for vlan interface.
```
ip link add link test1 name vlan99 address 00:11:22:33:44:55 type vlan id 11
```

**Comment by yuwata** [comment]
Gha, I set wrong mac address... With correct `MACAddress=` it works fine for me.

@napaster Please try to drop vlan123.link and set MACAddress= and MTUBytes= in .netdev file.

**Comment by napaster** [comment]
Good. I'll try.
Link to sections link is the variable MACAddress

That is, permernnaya MACAddress is in section 2 [Match] and [Link]

https://freedesktop.org/software/systemd/man/systemd.link.html#MACAddressPolicy=

Is this a documentation error? Or what is the purpose of the second function?

If without the first in the match section it is not, so to speak, hung up on the physical interface, then what does it do in the link section?

**Comment by yuwata** [comment]
Hmm? Sorry I cannot catch your question... Note that .link files are used by udevd, not networkd.

I mean, please try the following
```
# vlan123.netdev
[NetDev]
Name=vlan123
Kind=vlan
MACAddress=10:c3:7b:4f:58:a4
MTUBytes=1500
[VLAN]
Id=123
```

**Comment by napaster** [comment]
Yes, it works.
In this case, how to change the mac address on the physical interface? As an example, gig0 interface. Create a netdev file for it?

**Comment by yuwata** [comment]
For physical interfaces, setting like the following in .link file
```
# gig0.link
[Match]
(snip)
[Link]
Name=gig0
MACAddress=00:11:22:33:44:55
```

Anyway, this is not an issue of networkd, but misconfiguration. Let's close this.
