### ISSUE TITLE
test: test-json fails on PPC64, ARM, and ARM64

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#11600]
https://koji.fedoraproject.org/koji/taskinfo?taskID=32265809
```
GOT: [{"x":true,"y":{"this":null}},null,null,null,null,77,["foobar","zzz"],["","","ð\u0013","ð\u0013"]]
Assertion 'json_parse(s, &b, NULL, NULL) >= 0' failed at ../src/test/test-json.c:297, function test_build(). Aborting.
```

**Comment by yuwata** [comment]
The `GOT` line should be
```
GOT: [{"x":true,"y":{"this":null}},null,null,null,null,77,["foobar","zzz"],["one","two","three","four"]]
```

**Comment by yuwata** [comment]
@keszybz Is it possible to build systemd-241~rc1 for F29 without pushing it to the updates-testing repository? I am not sure, but I guess this may be a bug of gcc-9. So, I want to know building on F29 succeeds or not.

**Comment by yuwata** [comment]
Should we ignore this? At least drop from v241 milestone?

**Comment by keszybz** [comment]
> Is it possible to build systemd-241~rc1 for F29 without pushing it to the updates-testing repository?

https://koji.fedoraproject.org/koji/taskinfo?taskID=32720972

> I guess this may be a bug of gcc-9

I'm not sure. The code that is failing is doing something like this:
```C
json_build(..., ({ char **_x = ((char**) ((const char*[]) {"one", "two", "three", "four", NULL })); _x; })
```
What provides the guarantee that the array where the pointers to the strings are stored survives past the end of the block where `_x` is defined?
