### ISSUE TITLE
org.freedesktop.systemd1 doesn't work suddently, but daemon-rexec can recover

### ISSUE THREAD

**Issue by suxiaobei1024** [systemd/systemd#11601]
**systemd version the issue has been seen with**

```
[root@iZwz959djw7jznons1li1gZ ~]# systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Used distribution**

systemd-219-42.el7_4.1.x86_64

**Steps to reproduce the problem**

Hi, anyone seen a issue(I am not sure is this a bug yet?) like this: After a long time great running systemd, the dbus object: `org.freedesktop.systemd1` doesn't work suddently (doesn't reply anymore). 

I checked that only `org.freedesktop.systemd1` doesn't reply anymore(when I use dbus-send to test it),but others dbus object (such like: org.freedesktop.DBus,  org.freedesktop.login1) and after I execute `systemctl daemon-rexec`  system can recover a good running, So I think this issue maybe only relates to systemd, but not dbus-daemon. 

So far, I still don't know how to reproduce this issue. ..

org.freedesktop.systemd1 doesn't work anymore: 

```
[root@iZwz959djw7jznons1li1gZ ~]# dbus-send --system --dest=org.freedesktop.systemd1 --type=method_call  /org/freedesktop/systemd1 --print-reply org.freedesktop.DBus.Introspectable.ListUnitFiles


Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

org.freedesktop.DBus can works well : 

```
[root@iZwz959djw7jznons1li1gZ ~]# /bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.Introspectable.Introspect | head
method return sender=org.freedesktop.DBus -> dest=:1.178987108 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <interface name="org.freedesktop.DBus">
    <method name="Hello">
      <arg direction="out" type="s"/>
    </method>
    <method name="RequestName">
```

org.freedesktop.login1  can works well : 

```
[root@iZwz959djw7jznons1li1gZ ~]# dbus-send --system --dest=org.freedesktop.login1 --type=method_call  /org/freedesktop/login1 --print-reply org.freedesktop.DBus.Introspectable.Introspect | head
method return sender=:1.1 -> dest=:1.178987110 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
 <interface name="org.freedesktop.DBus.Peer">
  <method name="Ping"/>
  <method name="GetMachineId">
   <arg type="s" name="machine_uuid" direction="out"/>
  </method>
 </interface>
```

what confuse me is another thing that `systemctl list-unit-files` can works well, I checked systemctl.c code , I think  this command : `systemctl list-unit-files`  will make a `method_call` 
  request to conection ( org.freedesktop.systemd1 ) and this behavior should be same as command : `dbus-send --system --dest=org.freedesktop.systemd1 --type=method_call  /org/freedesktop/systemd1 --print-reply org.freedesktop.DBus.Introspectable.ListUnitFiles`

```
    systemctl_main(bus) 
        list_unit_files
            r = sd_bus_call_method( 
                     bus,
                     "org.freedesktop.systemd1",
                     "/org/freedesktop/systemd1",
                     "org.freedesktop.systemd1.Manager",
                     "ListUnitFiles",
                     &error,
                     &reply,
                     NULL);
            if (r < 0) {
                    log_error("Failed to list unit files: %s", bus_error_message(&error, r));
                    return r;
            }
```

Maybe there are someplace I have misunderstanding with code, and the scene, can anyone direct me to debug this issue futher?  regards.

**Comment by yuwata** [comment]
If `install_client_side()` is true, then `systemctl` read unit files by oneself, and not call any dbus method. Thus, `systemctl` behavior seems intended.

**Comment by yuwata** [comment]
BTW, please provide version number of systemd. And, do you find any relevant logs in journal? Booting with `systemd.log_level=debug` kernel command line may help you.

**Comment by muahao** [comment]
> BTW, please provide version number of systemd. And, do you find any relevant logs in journal? Booting with `systemd.log_level=debug` kernel command line may help you.

Thanks for your reply , I update version infomation, and if I add `systemd.log_level=debug` to reboot, the scene will be destroyed , and I still don't know how to reproduce this issue so far. 

Is there some way others  can direct me to monitor what systemd side is doing when I do `dbus-send` command to this dbus object: `org.freedesktop.systemd1`

**Comment by muahao** [comment]
BTW, I found some special log as bellow: 

```
Jan 30 22:40:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31684.scope: The maximum number of pending replies per connection has been reached
Jan 30 22:50:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31685.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:00:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31686.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:01:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31687.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:10:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31688.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:20:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31689.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:30:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31690.scope: The maximum number of pending replies per connection has been reached
Jan 30 23:40:01 iZwz959djw7jznons1li1gZ systemd-logind: Failed to start session scope session-31691.scope: The maximum number of pending replies per connection has been reached
[root@iZwz959djw7jznons1li1gZ ~]# cat /var/log/messages | grep systemd
```

**Comment by yuwata** [comment]
Oh, v219... Sorry, the version is too old. Please see https://systemd.io/CONTRIBUTING.html
> We only track bugs in the two most recently released versions of systemd in the GitHub Issue tracker. If you are using an older version of systemd, please contact your distribution’s bug tracker instead.

Please try to use v239 or newer. And if you find the issue still exists in the recent version, then please request to reopen this page.
