### ISSUE TITLE
xdm refuses login when starting it from emergency console

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11616]
**systemd version the issue has been seen with**
240-5

**Used distribution**
Debian unstable

**Expected behaviour you didn't see**
I started xdm by running the binary normally from an emergency root login (see #11615 for background). I expected to be able to log in with xdm. The home dir for the relevant user was mounted, and the normal root dir (including /etc) was also present.

**Unexpected behaviour you saw**
It showed an error that login was prohibited by a policy setting.

**Steps to reproduce the problem**
See above.

**Comment by wm4** [comment]
Is there any reason why it doesn't remove that file when the boot is arguably finished (even if it booted into the emergency prompt)?

**Comment by poettering** [comment]
> Is there any reason why it doesn't remove that file when the boot is arguably finished (even if it booted into the emergency prompt)?

emergency means the boot is not finished. It means "give me a shell really really early on and when I exit it continue booting". 

The file is removed when the system is fully up, but emergency does not qualify as that.
