### ISSUE TITLE
How to use tc (shaper) in systemd-networkd

### ISSUE THREAD

**Issue by napaster** [systemd/systemd#11618]
Good day. Tell me how to use tc instead of systemd-networkd.
Netctl has a hook for this: 

> ExecUpPost = ('tc qdisc add dev imq0 root descriptor 1: 0 htb r2q 10 by default 19;
tc class add dev imq0 parent 1: 0 classid 1: 1 speed htb 20 Mbit, package 15k mtu 16000;
tc class add dev imq0 parent 1: 1 classid 1:11 htb rate 512Kbit ceil 20Mbit burst 15k prio 1 mtu 16000 ')

Which is applied during startup. How can I implement the scheme through systemd-networkd?

**Comment by napaster** [comment]
In RPM base system have script in /sbin/ifup-local

Example:
> vlan666)                                                                                                                                                                                                                                     tc qdisc add dev $1 root handle 1:0 htb r2q 10 default 11                                                                                                                                                                                    tc class add dev $1 parent 1:0 classid 1:1 htb rate 10Mbit mtu 1500                                                                                                                                                                          tc class add dev $1 parent 1:1 classid 1:11 htb rate 5Mbit prio 1 mtu 1500                                                                                                                                                                   tc qdisc add dev $1 parent 1:11 handle 11 sfq perturb 10

**Comment by napaster** [comment]
Yes, I would like this opportunity to be

**Comment by ssahani** [comment]
I am starting to working on this now. Huge feature.
