### ISSUE TITLE
systemd hangs on boot for 1 minute 30 seconds if fstab entry uses non-existent device

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11614]
**systemd version the issue has been seen with**
240-5

**Used distribution**
Debian unstable

**Expected behaviour you didn't see**
systemd complains that a fstab entry is wrong, and then either continues booting, or shows an emergency login.

**Unexpected behaviour you saw**
It waits for 1 minute 30 seconds doing absolutely nothing. It can't be interrupted (or at least I didn't find a way to do so). Once it was done making you wait, it finally showed an emergency login.

The incorrect entry was a disk that was not present. It did not contain any system files, and no critical system mount points. The system booted normally after I commented the fstab entry.

The entry was a local disk. It was not anything that could be expected to appear after some time.

**Steps to reproduce the problem**
Add an entry with a non-existent device to /etc/fstab.

**Comment by yuwata** [comment]
Please use `nofail` mount option. See systemd.mount(5).

**Comment by wm4** [comment]
I doin't think that is an appropriate solution in general. When for example the root filesystem is mounted, I don't want to wait for 1 minute 30 seconds either, and at the same time I don't want it to continue booting "normally".

**Comment by yuwata** [comment]
Please try to set `x-systemd.mount-timeout=` mount option.

**Comment by wm4** [comment]
Yes, that's more like it. Is it possible to set this as default option for all mounts? (And preferably, no wait should be the systemd default configuration upstream.)

**Comment by yuwata** [comment]
No. But it is possible to set that for _all units_. See systemd-system.conf(5).

**Comment by wm4** [comment]
That's good, but I still think no waiting should be the upstream default.

What exactly is the reason/use case for the timeout?

**Comment by kirbyfan64** [comment]
Basically, without nofail, it is considered an error for a device listed in the fstab to not exist. As a mount is just another unit, if it's not yet available, systemd will wait the normal timeout for a unit before failing, again just like a normal required unit.

**Comment by wm4** [comment]
>Basically, without nofail, it is considered an error for a device listed in the fstab to not exist.

That seems to be wrong. It's fine for the device not to exist, as long as it appears before the timeout has elapsed.
