### ISSUE TITLE
resolved does not respond to UDP DNS queries with too small a buffer size

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#11625]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > `dig +bufsize=1200 +noad +nocookie -t srv @127.0.0.53 _ldap._tcp.example.com` succeeds after outputting `;; Truncated, retrying in TCP mode.`

**Unexpected behaviour you saw**
 > `dig +bufsize=1200 +noad +nocookie -t srv @127.0.0.53 _ldap._tcp.example.com` fails with `;; connection timed out; no servers could be reached`

**Steps to reproduce the problem**
I am trying to debug the following:

```
$ ldapsearch -o ldif-wrap=no -b dc=example -H 'ldap:///dc%3Dexample' '(userPrincipalName=sam.morris@example)'
DNS SRV: Could not turn domain=example into a hostlist 
```
Its function `ldap_domain2hostlist` ends up calling `res_query("_ldap._tcp.example", C_IN, T_SRV, reply, sizeof(reply));` where `reply` is a 64 KiB buffer. This returns `-1` which is, I think, all you'll get out of libresolv. However the dig commands I quoted above reproduce exactly the query that libresolv sends to resolved; resolved does not respond to the query and the client times out after waiting for a bit.

If I substitute my network's recursive resolver in `/etc/resolv.conf` and re-run `ldapsearch` then it receives a reply with the truncated bit set and re-tries the query with TCP, which works.

**Comment by poettering** [comment]
Fix waiting in #11993
