### ISSUE TITLE
systemd-networkd - call scripts on certain events

### ISSUE THREAD

**Issue by amishmm** [systemd/systemd#11629]
**Is your feature request related to a problem? Please describe.**
No. A new feature.

I request a feature that systemd.network should call a script when a Link is configured or un-configured. (and may be other events)

**Describe the solution you'd like**
I would like a solution similar to what PPPD does when pppd connection is established or disconnected.

May be like this: (foo.network file)

[Scripts]
OnConfigure=script1
OnUnConfigure=script2
OnMatch=script3

Parameters can be passed similar to pppd. (whichever possible based on case)
interface-name tty-device speed local-IP-address remote-IP-address (gateway) ipparam

See man pppd (SCRIPT section) for more details

This will act like plugins where one can add customized scripts (for eg. send email alert  OR implement ip route or ip rule features which are not yet implemented in systemd-networkd. It opens up many more possibilities.

**Comment by boucman** [comment]
there is https://gitlab.com/craftyguy/networkd-dispatcher that can help...

**Comment by amishmm** [comment]
Great. Thats what I wanted. Thanks. Good thing is its already in Archlinux AUR repository.

**Comment by hgl** [comment]
What would be the recommended way to implement DDNS on top of networkd for example, where an external script is called whenever there is an interface ip change?
