### ISSUE TITLE
machinectl reports wrong machine image not existing

### ISSUE THREAD

**Issue by jonesmz** [systemd/systemd#11628]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > When attempting to start multiple machines with machinectl, if one of the named machines does not exist, machinectl should report the machine name that isn't found as not existing.

**Unexpected behaviour you saw**
 > machinectl told me that the first machine named in the list was not found, even though it exists.

**Steps to reproduce the problem**

Have 3 machines configured in /etc/systemd/nspawn
* userfiles
* multimedia
* companydocs

run
`machinectl start userfiles multimedia company`

Get error
Machine image 'userfiles' does not exist.

Expected to get error
Machine image 'company' does not exist.

**Comment by yuwata** [comment]
Fix is waiting in #11632.

**Comment by jonesmz** [comment]
Thank you!
