### ISSUE TITLE
systemctl State degraded although responsible service is masked

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#11644]
**systemd version the issue has been seen with**
systemd 240
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
`systemctl status` should not show a `Degraded` state.

**Unexpected behaviour you saw**
 `systemctl status` shows a `Degraded` state although the reponsible service is masked via `systemctl mask`

**Steps to reproduce the problem**
For some reason `systemd` tries to start the service: ` systemd-cryptsetup@Root.service`, but this service doesn't seem to exist:
```
chris motoko ~ 22:08:43 2c327e1a master 
❯ systemctl cat systemd-cryptsetup@.service
No files found for systemd-cryptsetup@.service.
chris motoko ~ 22:09:13 2c327e1a master 
❯ systemctl cat systemd-cryptsetup@Root.service 
No files found for systemd-cryptsetup@Root.service.
```

Therefore I masked the service to get a right `systemctl status` output, but even when I mask the service `systemd` still tries to start the service.

my `/etc/crypttab` looks like this:
```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/crypttab
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # Configuration for encrypted block devices.
   2   │ # See crypttab(5) for details.
   3   │ 
   4   │ # NOTE: Do not list your root (/) partition here, it must be set up
   5   │ #       beforehand by the initramfs (/etc/mkinitcpio.conf).
   6   │ 
   7   │ # <name>       <device>                                     <password>              <options>
   8   │ # home         UUID=b8ad5c18-f445-495d-9095-c9ec4f9d2f37    /etc/mypassword1
   9   │ # data1        /dev/sda3                                    /etc/mypassword2
  10   │ # data2        /dev/sda5                                    /etc/cryptfs.key
  11   │ # swap         /dev/sdx4                                    /dev/urandom            swap,cipher=aes-cbc-essiv:sha256,size=256
  12   │ # vol          /dev/sdb7                                    none
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

bootloader is `systemd-boot` with systemd kernel hooks enabled:
```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: entries/arch-hardened.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ title   motoko-hardened
   2   │ linux   /vmlinuz-linux-hardened
   3   │ initrd  /initramfs-linux-hardened.img
   4   │ options rd.luks.uuid=1aa50d23-d139-4367-b552-448a1b14b086 rd.luks.name=71f4088d-e06f-43b2-818f-7a34de921460=Root root=UUID=71f4088d-e06f-43b2-818f-
       │ 7a34de921460 rw
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: entries/arch-lts.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ title   motoko-lts
   2   │ linux   /vmlinuz-linux-lts
   3   │ initrd  /initramfs-linux-lts.img
   4   │ options rd.luks.uuid=1aa50d23-d139-4367-b552-448a1b14b086 rd.luks.name=71f4088d-e06f-43b2-818f-7a34de921460=Root root=UUID=71f4088d-e06f-43b2-818f-
       │ 7a34de921460 rw
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

`systemctl status`:
```
● motoko.nullday.de
    State: degraded
     Jobs: 0 queued
   Failed: 1 units
    Since: Sun 2019-02-03 18:56:20 CET; 3h 16min ago
   CGroup: /
[...]
```

**Comment by poettering** [comment]
masking and failing are orthogonal. If you mask a failed unit the failed state doesn't vanish. If you want it to vanish, you have to do "systemctl reset-failed" on it.

Masking vs. not masking is an enablement state, while failure is a runtime state, and those state machines are orthogonal in systemd. And I think that's kinda nice, and we should not start mixing up both (after all it might be that a service you masked is still running, and a service that failed can be masked or not).

is it possible that the failed crytpsetup instance you see is done in the initrd?

either way, if you want to reset failed states, please use systemctl reset-failed, not systemctl mask, that has a different purpose.

I am not sure there's anything to fix here?

**Comment by shibumi** [comment]
I guess my actually problem is that I don't know where this failed cryptsetup instance is coming from. My goal was to bring my system back in a good state.

You are right, there is not much to fix here. I thought this is might a bug, but seems like I just didn't understand what impact masking a service has. Thanks for clearing this up. Closing this issue.

**Comment by shibumi** [comment]
I finally find out where this cryptsetup service is coming from. Looks like my systemd-boot configuration is wrong:
```
title	motoko-hardened
linux	/vmlinuz-linux-hardened
initrd  /intel-ucode.img
initrd	/initramfs-linux-hardened.img
options rd.luks.uuid=1aa50d23-d139-4367-b552-448a1b14b086 rd.luks.options=discard rd.luks.name=71f4088d-e06f-43b2-818f-7a34de921460=root root=UUID=71f4088d-e06f-43b2-818f-7a34de921460 rw
```

I am curious what might be wrong with it. I suspect a wrong `rd.luks.name` line.

**Comment by shibumi** [comment]
Ok, I finally fixed this behavior for me after more than a year.
Maybe it's useful for somebody who is encountering the same issue.
My systemd-boot entry file has been wrong.
The correct line is:

`options rd.luks.uuid=1aa50d23-d139-4367-b552-448a1b14b086 rd.luks.options=discard rd.luks.name=1aa50d23-d139-4367-b552-448a1b14b086=root root=UUID=71f4088d-e06f-43b2-818f-7a34de921460 rw`

`rd.luks.name` is asking for the UUID of the device not of the /dev/mapper.

It's funny, that systemd still found the right device for over a year and attached it
