### ISSUE TITLE
Need alternatives to RequiresMountsFor

### ISSUE THREAD

**Issue by neilbrown** [systemd/systemd#11646]
**Is your feature request related to a problem? Please describe.**
The nfs server mustn't start until all exported filesystems are mounted, else clients can get confusing results.  So we have a generator which creates dependencies between nfs-server.service and the various exported directories (which may or may not be mount points).  The only directive that can be used here is RequiresMountsFor, but we really only want an "After" dependency.
Because Requires is used, when one of the exported filesystems gets unmounted, the nfs server gets stopped.
This would make sense if we really wanted "Requires" -  but we don't.

**Describe the solution you'd like**
There is no "obviously correct" solution, but it would be nice to be able to have, for example
   MountsFor(/some/path/name)
wherever a list unit names is expected.  This would expand to all foo.mounts that are needed for that path.  I could then describe exactly the dependency I need.
Actually, it probably only needs to expand to the leaf-most mountpoint in the path.

**Describe alternatives you've considered**
Probably the simplest extension to achieve my goal would be to add a "WantsMountsFor" directive.

**Comment by poettering** [comment]
So far our thinking was to not make deps too fine grained. i.e. instead of having explicit deps on really every single dir you need you should just use an ordering dep on local-fs.target, and that in turn is responsible for pulling in all mounts configured on the system.  So, why would be a local-fs.target dep not enough for your case?

**Comment by neilbrown** [comment]
local-fs.target is not sufficient when the file system being exported is not local.
The specific case where this came up was with a filesystem mounted over iSCSI, but now that there is limited support for NFS reexport, that might need this handling too.

**Comment by poettering** [comment]
So what about adding After=remote-fs.target on top of that then?

**Comment by bl33pbl0p** [comment]
Also: The MountsFor() macro idea won't work well as systemd likes resolving that stuff at load time, and then won't be able to dynamically update dependencies as mount units are added (in contrast to RequiresMountsFor=, which has special logic to take care of that).

**Comment by neilbrown** [comment]
> So what about adding After=remote-fs.target on top of that then?

Then if you have an NFS mount from the local host (and there are valid use-cases for that) you deadlock because the NFS server is waiting for the NFS mount, which cannot complete until the NFS server starts.

I really think that the policy of "no fine-grained deps" is a problem.  It is perfectly fine as a general preference, but there will be exceptions, and I think systemd needs to support them.

**Comment by neilbrown** [comment]
I've been thinking about what it means  "not make deps too fine grained".  Of course, we do have fine grained deps between local-fs.target and individual filesystems, and again between remote-fs.target and individual filesystems.
So maybe the real goal is  to *not make deps *between non-targets* too fine grained".
Applying this idea, I could create a new target, nfs-exports.target, and create RequiresMountsFor dependencies between this and each exported directory.
Then I can create Wants and After dependencies between nfs-server.service and nfs-exports.target.
That should get me the result that I want.
"Any problem in computer science can be solved with another level of indirection" ???
I'll come back and close this once this approach has been implemented and confirmed.
