### ISSUE TITLE
udev kills all processes on reload, when it thinks it is running under systemd (but it is not)

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#11645]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
Invoking `udevadm trigger` should not kill unrelated processes

**Unexpected behaviour you saw**
Invoking `udevadm trigger` kills unrelated processes.

**Steps to reproduce the problem**

If udev is executed outside a systemd unit, udev sometimes thinks it has been started as a systemd unit and enables the killing spree, which ends up killing unrelated processes. This affects mostly users of other PID1 implementations.

It seems to me that this check is too simplistic:

https://github.com/systemd/systemd/blob/v240/src/udev/udevd.c#L1817-L1828

I wonder what is a better way to check this. Maybe using `$INVOCATION_ID` is a better way to answer the question: am I running as a systemd unit?

This is forwarded from [debian bug 918764](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918764)

**Comment by fsateler** [comment]
> I wonder what is a better way to check this. Maybe using $INVOCATION_ID is a better way to answer the question: am I running as a systemd unit?

Another option is to check that the cgroup looks like `/system.slice/*.service` :

```c
        if (getppid() == 1) {
                /* get our own cgroup, we regularly kill everything udev has left behind
                   we only do this on systemd systems, and only if we are directly spawned
                   by PID1. otherwise we are not guaranteed to have a dedicated cgroup */
                r = cg_pid_get_path(SYSTEMD_CGROUP_CONTROLLER, 0, &cgroup);
                if (r < 0) {
                        if (IN_SET(r, -ENOENT, -ENOMEDIUM))
                                log_debug_errno(r, "Dedicated cgroup not found: %m");
                        else
                                log_warning_errno(r, "Failed to get cgroup: %m");
                }
                else if (!(startswith(cgroup, "/system.slice/") && endswith(cgroup, ".service")))
                        cgroup = mfree(cgroup);
        }

```

**Comment by poettering** [comment]
hmm? so the system in question has the systemd cgroup hierarchy mounted, but doesn't run systemd?

Quite frankly, it's their own fault then. If people want to emulate systemd they may, but it's not our problem if they do so badly? What am I missing?

**Comment by fsateler** [comment]
You can trigger this bug on a systemd system by launching udev outside systemd (using a forking caller like setsid or start-stop-daemon). Udev then detects a cgroup, but it is the calling users .scope, so instead of killing its spawns, it kills the user sessions.

It seems to me that udev wants to know if its running as a systemd service. But the current code is easily tripped.

> so the system in question has the systemd cgroup hierarchy mounted, but doesn't run systemd?

Pardon the ignorance, but how do I determine this? As per the linked bug, I don't see systemd in the quoted cgroups file contents.

**Comment by poettering** [comment]
> Pardon the ignorance, but how do I determine this? As per the linked bug, I don't see systemd in the quoted cgroups file contents.

You invoke this:

```c
r = cg_pid_get_path(SYSTEMD_CGROUP_CONTROLLER, …);
```

This returns the path of the specified PID in the specified controller. And `SYSTEMD_CGROUP_CONTROLLER` is the "name=systemd" controller, i.e. systemd's own. This call will fail with ENOMEDIUM if the controller is not available, which is why the code excerpt you linked checks explicitly for that error, using it as indication whether we are on a systemd system or not.

So, two options:

1. either that affected system defines the name=systemd hierarchy, but doesn't run systemd. Which is really broken, and things will break here and everywhere.

2. there's cgroupsv2-only mode in use, which doesn't know the controller concept, and hence the check doesn't actually work.

**Comment by fsateler** [comment]
It seems to me that cgroups v2 is enabled. At least one reported says so:

> This is done in cgroup2, old cgroup is not mounted at all.

I'll ask other reporters to check this.

**Comment by poettering** [comment]
well, in that case the ENOMEDIUM thing will never be regenerated. I figure there could be an sd_booted() > 0 check be added to the getppid() == 1 line.

**Comment by yuwata** [comment]
I've created PR #11660 based on @poettering's suggestion in the above. PTAL.

**Comment by linkfanel** [comment]
As highlighted during the discussions in #11660, this is only a partial fix; nothing has been advanced yet to detect or address the cgroup coupling issues between their setup in systemd, and the checks and reliance on them in udev, which can still result in wrongful process killing under systemd.

Shall this be reopened? Or maybe you'd also want to open a separate issue for specifically sorting this out?
