### ISSUE TITLE
getty@.service: time to drop UnsetEnvironment=LANG= ...?

### ISSUE THREAD

**Issue by aburch** [systemd/systemd#11668]
**Is your feature request related to a problem? Please describe.**
systemd 240 started to set LANG=C.UTF-8 by default, however there is one exception: getty@.service unsets the variable again.

I think it is not good that console logins get a different value here.

**Describe the solution you'd like**
Drop
```
UnsetEnvironment=LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION
```
from getty@.service.m4

It was introduced in 1640944a847249d3f5f0fb0d5a5f820a82efaed0 which already stated
```
Eventually we probably want to drop this again since the system locale
should be read and set at one place, and not at multiple, and that one
place should be PID 1.
```

**Comment by poettering** [comment]
well, did display of indian characters get fixed in the Linux console? i don't think so?

**Comment by poettering** [comment]
Let's close this. We can revisit this once the linux console gains support for more than 512 glyphs at a time, because otherwise we shouldn't set arbitrary locales that are heavy on undisplayable glyphs.
