### ISSUE TITLE
systemd-journal-upload doesn't start anymore: Error 411: gth required

### ISSUE THREAD

**Issue by heini** [systemd/systemd#11669]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian Buster

**Expected behaviour you didn't see**
 > systemd-journal-upload starts up and pushes journal to remote host

**Unexpected behaviour you saw**
 > systemd-journal-upload[7781]: Upload to http://<remotehost>:19532/upload failed with code 411: gth Required

**Steps to reproduce the problem**
systemctl start systemd-journal-upload

**Comment by yuwata** [comment]
Duplicate of #11571.
