### ISSUE TITLE
User unit limitations not documented

### ISSUE THREAD

**Issue by zoqaeski** [systemd/systemd#11677]
**Is your feature request related to a problem? Please describe.**
I've been trying to create a user unit on a timer that wakes my desktop from suspend. The documentation lists a `WakeSystem` directive that does exactly what I want. However, using `WakeSystem=true` in a user timer (e.g. `~/.config/systemd/user/daily-backup.timer`) results in the timer being unable to be started with the following error:
```
daily-backup.timer: Failed to enter waiting state: Operation not permitted
daily-backup.timer: Failed with result 'resources'.
Failed to start daily backup.
```
The `backup-daily.timer` unit consists of:
```
[Unit]
Description=daily backup

[Timer]
OnCalendar=07:00
Persistent=true
Unit=daily-backup.service
WakeSystem=true
RandomizedDelaySec=10m

[Install]
WantedBy=default.target
WantedBy=timers.target
```
The `daily-backup.service` works as expected when run manually, so I haven't bothered to provide the service file here.

**Distribution and systemd version**
Arch Linux with systemd 240

**Describe the solution you'd like**
Ideally, the user instance would be able to wake the system from suspend. If there are reasons for why this cannot be done, be them security, resource limitations or otherwise, the documentation for `SYSTEMD.TIMER(5)` should be amended to add that this directive does not work for user units. If it can be made to work, but requires an additional set of steps to be performed by the user, these should be documented in some way.

**Describe alternatives you've considered**
The solution I've come up with for the time being involves creating a `wake-up.timer` system unit that wakes the system up a few minutes before the user unit is scheduled to run. As units have to do something, the `wake-up.service` is a dummy service that prints out a random piece of wisdom. Both of these units are provided below:
```
[Unit]
Description=Daily piece of wisdom

[Timer]
OnCalendar=06:55
Persistent=true
Unit=wake-up.service
WakeSystem=true
RandomizedDelaySec=5m

[Install]
WantedBy=timers.target
```

```
[Unit]
Description=Daily piece of wisdom

[Service]
Type=oneshot
User=nobody
ExecStart=fortune
```
The end result is that I'll get a few lines of harmless noise in my journal once a day, and the user service for backing up works as intended after removing the `WakeSystem=true` line from the `daily-backup.timer` given above.

**Comment by poettering** [comment]
Fix waiting in #13036
