### ISSUE TITLE
Fix rotation for Nuvision Solo 10 Draw

### ISSUE THREAD

**Issue by ShapeShifter499** [systemd/systemd#11683]
The following information should help fix rotation for the Nuvision Solo 10 Draw. Before the below changes attempting to enable "auto-rotation" would result in the display rotating in opposite of how the tablet was held. i.e. Holding the tablet in upright portrait would result in "flipped upside down" display.  

Auto-rotation was enabled with https://github.com/hadess/iio-sensor-proxy on a Arch Linux install. Desktop environment is Gnome 3

Name: Nuvision Solo 10 Draw
Model number: TM101W610L

hwdb settings
```
sensor:modalias:acpi:KIOX000A*:dmi:*:svnTMAX:pnTM101W610L:*
 ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1
```

Attached file is the dump of the following command after above change.  ```udevadm info --export-db```
[udevadm_info.txt](https://github.com/systemd/systemd/files/2848568/udevadm_info.txt)

**Comment by ShapeShifter499** [comment]
Ok I've submitted a PR fix. https://github.com/systemd/systemd/pull/11684

**Comment by ShapeShifter499** [comment]
I think the build is failing because of a whitespace character, I'm not entirely sure how to fix this.

**Comment by ShapeShifter499** [comment]
First, accidentally clicked "close and comment" in GitHub
Secondly, I think I fixed this with PR #11686. Builds are failing but they appear to fail on something other than my white space fixed updated PR change.

**Comment by yuwata** [comment]
It is not necessary to open an issue page if you submit a fix for that soon. Also, you can use force-push to update PRs :-)

**Comment by ShapeShifter499** [comment]
@yuwata Good to know for next time.

So for future reference. Don't make a issue ticket if I I think I'm pretty certain about what needs to be changed to fix an issue?

I deleted my original PR because I had messed up the git commit history with one too many 'git revert' commands. I didn't want a PR accepted with a messy commit history.

**Comment by yuwata** [comment]
In the PR page you can explain what the issue is.

If you find any problems in your PR, then please update commit e.g. by `git commit -a --amend`, and force push by e.g. `git push origin branchname --force`.
Or, if the PR is small enough, then adding fix commits is also OK. Then we squash them on merge.

**Comment by yuwata** [comment]
Anyway, please do not mind that so seriously :-)
