### ISSUE TITLE
Can not bind `/sys/fs/cgroup`

### ISSUE THREAD

**Issue by pavel** [systemd/systemd#11703]
**systemd version the issue has been seen with**
> Host: 240.95. Container: 240.95

**Used distribution**
 > Arch Linux (for host and container). Kernel: 4.20.7

**Expected behaviour you didn't see**
 > `/sys/fs/cgroup` mounted with `rw` inside a container.

**Unexpected behaviour you saw**
 > Various errors based on a flag used:
###### `--bind=/sys/fs/cgroup`
> Failed to create /init.scope control group: No such file or directory
> Failed to allocate manager object: No such file or directory
> ...

###### `--bind=$(pwd)/cgroup:/sys/fs/cgroup`
Here `$(pwd)/cgroup` is a local empty directory.
> Failed to mount n/a (type n/a) on /sys/fs/cgroup: Device or resource busy
> Child died too early

###### `--bind=+/sys/fs/cgroup:/sys/fs/cgroup`
> Failed to mount cgroup (type cgroup) on /sys/fs/cgroup/memory: No such file or directory
> Child died too early

**Steps to reproduce the problem**
1. `pacstrap -i -c ./my-container base --ignore=linux docker`
2. `systemd-nspawn -b --capability=all --system-call-filter="add_key keyctl" --bind=/sys/fs/cgroup -D ./my-container`

**Comment by poettering** [comment]
Hmm. What are you trying to do? Nspawn will mount cgroupfs on its own. No need to use --bind=. And given that nspawn employs cgroup namespaces mounting your own version cannot work anyway

**Comment by pavel** [comment]
@poettering Trying to run `docker` inside `nspawn`'ed container.

**Comment by poettering** [comment]
But why would you moutn cgroupfs on your own then? nspawn's own setup should suffice, no?

**Comment by pavel** [comment]
docker requires `rw` access to `/sys/fs/cgroup`.
Using nspawn's own setup docker errors during `docker run`:
> mkdir /sys/fs/cgroup/cpuset/docker: read-only file system

I do not like the idea of mounting host's `cgroup` folder to a container, but what other options do I have to make `/sys/fs/cgroup` writable in a container (preferably fully isolated from host)?

**Comment by pavel** [comment]
I also tried to run
```
--overlay=/sys/fs/cgroup:$(pwd)/cgroup:/sys/fs/cgroup
```
where `$(pwd)/cgroup` is an empty directory on the host.
This produces the following error:
> Cannot determine cgroup we are running in: No medium found
> Failed to allocate manager object: No medium found

**Comment by poettering** [comment]
it's simply broken if docker wants to write to the top of the container's cgroup tree. This is explicitly against the concept of delegation of subtrees in cgroup, i.e. the stuff documented here:

https://systemd.io/CGROUP_DELEGATION

docker really should follow the documented behaviour of the kernel and systemd there. It's just broken if the fuck around at the top of the tree.

That said, you should be able to remount /sys/fs/cgroup from inside of the container, after the fact, to make writable what normally isn't writable.

**Comment by poettering** [comment]
Anyway, let's close this here. Docker really shouldn#t do what it is doing. And by manually remounted from inside there's a hacky way out already, which should be OK: addressing broken behaviour with hacky tools sounds acceptable to me.

**Comment by pavel** [comment]
Understood.
Mind me asking if any software is doing `mkdir /sys/fs/cgroup/cpuset` this is against systemd as mentioned in https://systemd.io/CGROUP_DELEGATION, right?

**Comment by poettering** [comment]
well, they can do this, if they ask for a delegated subtree and make these changes only under their delegated subtree. But making changes at the top of the tree is just broken and not supported.

**Comment by HuJK** [comment]
So...... how to tell systemd-nspawn mount cgroups ```rw``` ?

**Comment by srd424** [comment]
@HuJK, I've just turned up this script which one of my containers has been using - looks like a umount and then a mount is required?

```
#! /bin/bash

cd /sys/fs/cgroup
for i in blkio cpu,cpuacct cpuset devices memory net_cls,net_prio \
                freezer hugetlb perf_event pids rdma; do
        umount $PWD/$i
        mount none -t cgroup $PWD/$i -o $i,rw
done

exit 0

```
