### ISSUE TITLE
bridge: missing sethello

### ISSUE THREAD

**Issue by pomac303** [systemd/systemd#1171]
Quote from the gentoo wiki
"It is important to include setfd 0 and sethello 10 in the /etc/conf.d/net file in order to bring the bridge interface up quickly. Other values will cause network packets to be dropped for the first 30 seconds after the bridge has become active. This, in turn, could prevent DHCP from working as intended."

**Comment by poettering** [comment]
Let's close this one, and keep track of it in #1172 instead.
