### ISSUE TITLE
networkd bridge support: missing settings: "setstp", "sethello", "forward delay"

### ISSUE THREAD

**Issue by pomac303** [systemd/systemd#1172]
In many cases you want to disable spanning tree, if you f.ex. want to have a bridge hidden

**Comment by poettering** [comment]
Let's merge #1171, #1170 into this one, and only keep this one around for all three options.

**Comment by poettering** [comment]
@ssahani maybe something you want to work on?

**Comment by poettering** [comment]
Note that #1171 and #1170 have more information about the settings, please have a look when intending to work on this.

**Comment by ssahani** [comment]
@poettering Sure .

**Comment by grawity** [comment]
(Side thought: I wonder if it would be better to run `mstpd` for RSTP support, rather than use the older/slower in-kernel STP...)

**Comment by poettering** [comment]
I think we have all of these now, closing. Please open a new bug, if there are still props missing.
