### ISSUE TITLE
bridge: doesn't enable a fully hidden bridge.

### ISSUE THREAD

**Issue by pomac303** [systemd/systemd#1173]
A bridge that has no ip isn't started. Whats missing is equivalent of ifconfig $bridge_if up

**Comment by ssahani** [comment]
I guess this is what we are looking for.

```
# cat br.netdev
[NetDev]
Name=br-test
Kind=bridge
```

```
# cat br.network
[Match]
Name=br-test
```

```
12: br-test@NONE: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether 82:db:f3:92:47:fe brd ff:ff:ff:ff:ff:ff
```

**Comment by pomac303** [comment]
bridge.netdev:

```
[NetDev]
Name=br0
Kind=bridge
```

bridge.network:

```
[Match]
Name=enp0s20f2
Name=enp5s0f0

[Network]
Bridge=br0

[Bridge]
Cost=0
UseBPDU=no
```

And then i have to manually do ifconfig br0 up before it works.
So it sets up the bridge but doesn't "bring it up".

So my current workaround to fix systemd is:

```
function setup_bridge {
        echo "Setting up bridge on $IFACE"
        ip link set dev $IFACE up
        brctl setfd $IFACE 0
        brctl sethello $IFACE 10
        brctl stp $IFACE off
}
```

How do I notice that it doesn't bring up the bridge interface? Well, this bridge has my entire internet connection - it's hard not to notice.

**Comment by poettering** [comment]
@pomac303 note that you need a .network file that matches the bridge interface, otherwise the interface for it will never be upped. Do you have one?

**Comment by pomac303** [comment]
@poettering ? I have a bridge.network that adds the interfaces to the bridge - do i need a separate empty one to make sure the interface is upped?

**Comment by poettering** [comment]
yes, that's what @ssahani already suggested.

basically: interfaces without a .network will never be upped. To up a network. drop in a .network file that matches them. With configuration in case you want IP on them. Without any configuration if you don't.

**Comment by pomac303** [comment]
So i need two network files to bring a interface up?

Wouldn't it be better to move the match rules for the "slaves" to the netdev file and make it so that you only need one network file?

It would be a much nicer solution, from a configuration perspective, and it would be more logical...
Imagine all bonds done like this in the future..

**Comment by poettering** [comment]
Well, the thinking so far was that if you have 5 network devices, you want to do different things with them at different times. hence, what you _do_ with an interface is independent of the description of _what_ they are... The latter is encoded in .netdev files, the former is encoded in the .network files of the originating devices.

**Comment by poettering** [comment]
But I understand that everything works for you now, if you add that second .network file?

if so, i guess we can turn this into a documentation bug, asking for improveent of the docs how to do what you wanted to do, so that the next one finds this easier.

**Comment by pomac303** [comment]
I'll check when i get home, don't want to risk rebooting machines remotely =)

**Comment by pomac303** [comment]
Sorry, closed by mistake - will update when i have more information but for now, lets reopen

**Comment by pomac303** [comment]
Sorry, been very busy and forgot all about it - And no, it doesn't work... =P

**Comment by poettering** [comment]
Is this still an open issue? If you run "systemctl status -a" see yout the net .network files properly assigned to your ifaces? i.e. you should have a .network file that is assigned to your links that shall join the iface, and a different one that is assigned to the bridge interface itself.

**Comment by poettering** [comment]
closing due to lack of response
