### ISSUE TITLE
On systems with SELinux, consider labeling the root inode of TemporaryFilesystem= that same as the mountpoint

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11742]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when TemporaryFilesystem=/run causes inconsistencies with labeling of /run, the root inode label of the tmpfs is not the same as mountpoint label.

**Describe the solution you'd like**

I would like it that when i use TemporaryFilesystem=/run that the /run label remains the same as it was before an tmpfs was mounted on it

**Describe alternatives you've considered**

The mount command has an option rootcontext= and if i understand correctly that could be used to explicitly label the root inode with a specified context. I would look into way's to "get" the label of the target mountpoint of TemporaryFilesystem= and then use rootcontext= to label to root inode of the tmpfs accordingly so that the label of the target mountpoint remains consistently the same.

**Comment by doverride** [comment]
I am closing this because this whole idea would apply to all the scenario's where systemd mounts tmpfs (and there is a huge amount of those). The stuff i wanted this for does not work anyway regardless of whether this would be fixed or not
