### ISSUE TITLE
ExecStop runs after service exits sucessfully

### ISSUE THREAD

**Issue by DanielG** [systemd/systemd#11744]
**systemd version the issue has been seen with**
240

**Used distribution**
Debian sid

**Expected behaviour you didn't see**
After the `ExecStart` process exits successfully a unit should be considered stopped and `ExecStop` should not be run to stop it some more.

**Unexpected behaviour you saw**
When `ExecStart` exits `ExecStop` is run which will probably fail because $MAINPID is no longer running.

**Steps to reproduce the problem**
Using the following unit as `test.service`:

```
[Service]
Type=simple
ExecStart=sh -c 'echo started; sleep 1; echo exiting'
ExecStop=echo stopping
```
After

    $ systemctl start test.service

we can see in the following in the journal:

```
sh[921]: started
sh[921]: exiting
echo[924]: stopping
```

The documentation for `ExecStop=` has the following to say on the matter:

> When the commands specified with this option are executed it should be assumed
> that the service is **still fully up** and is able to react correctly to all
> commands.

Which is obviously not the case when the service's main process has already exited.

This issue seems to be quite old I can also reproduce this with v215 on Debian jessie.

**Comment by poettering** [comment]
I figure this is mostly a documentation issue. Whether the main process is up or not is nothing to rely on, due to RemainAfterExit= and a daemon process exiting on its own with success. We should improve the docs about that, and clarfiying that ExecStop= is always called.

**Comment by DanielG** [comment]
I agree the documentation should at least mention that the service being up can not be relied upon when `RemainAfterExit=yes` but I think always calling `ExecStop` is quite inconvenient for users. 

Consider the following unit simulating a service which performs a graceful shutdown when some IPC command is sent to it. (I guess I should have lead with that since that's closer to my actual use-case but I didn't want to overcomplicate the report)

```
[Service]
Type=simple
ExecStart=sh -c 'echo started; rm -f %t/test; mkfifo %t/test; read _ < %t/test; echo exiting'
ExecStop=sh -c 'echo stop > %t/test'
TimeoutStopSec=1s
```

This works just fine when only starting/stopping the service through systemd but what happens when the service decides to quit on it's own?

```
$ systemctl start test2.service
$ echo > $XDG_RUNTIME_DIR/test

[wait for ExecStop to timeout]
$ systemctl status test2.service
● test2.service
   Loaded: loaded (/home/dxld/.config/systemd/user/test2.service; static; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2019-02-18 17:55:27 CET; 4s ago
  Process: 18386 ExecStart=/bin/sh -c echo started; rm -f /run/user/1000/test; mkfifo /run/user/1000/test; r
  Process: 18395 ExecStop=/bin/sh -c echo stop > /run/user/1000/test (code=killed, signal=TERM)
 Main PID: 18386 (code=exited, status=0/SUCCESS)
```

Now the unit is considered failed even though a perfectly clean shutdown was performed. That's hardly satisfactory. In this case the write to a named pipe without a reader causes a timeout, but you can imagine a similar thing happens with a socket if the service is not listening anymore.

The only way I can see to avoid this is to check if the service is still running in `ExecStop`. So either the IPC channel supports checking if something is listening on the other side, which named pipes don't as far as I'm aware, or I have to use `$MAINPID` to check if the process is still there.

I found using `$MAINPID` as a workaround is actually quite nice, but it does depend on some rather strange behaviour. It turns out `$MAINPID` expands to nothing if the main process has already quit but the pid number of the process if it's still running. So I end up with something like this:

```
[Service]
Type=simple
ExecStart=sh -c 'echo started; rm -f %t/test; mkfifo %t/test; read _ < %t/test; echo exiting'
ExecStop=sh -xc "if [ x$MAINPID != x ]; then echo > %t/test; fi"
TimeoutStopSec=1s
```

This behaviour of `$MAINPID` being set or not depending on the status of the main process is what lead me to belive this must be a bug since obviously systemd already knows that the main process has exited! It only doesn't use this information to not run `ExecStop`.

If this intended behavour maybe this workaround should be documented? Though I would still prefer `ExecStop` just doesn't run in case `RemainAfterExit=no` but if the ship has sailed on changing this I guess an additional option to control this behaviour would be appreciated.

**Comment by keszybz** [comment]
We cannot set $MAINPID to a stale process, because the PID might be recycled at any time. I'll push an update tot he docs to clarify the behaviour.
