### ISSUE TITLE
Somehow surprisingly nspawn container has CAP_NET_ADMIN when [Network] Private=no

### ISSUE THREAD

**Issue by dnicolodi** [systemd/systemd#11755]
**systemd version the issue has been seen with**
Tested with 232 but I verified that the code in master does the same thing. [0e26567](/systemd/systemd/commit/0e2656744f6d2e2cf65788a497f266d469865e30) should maybe have fixed this, but it does not seem so (as this commit in included, accordingly to github, in v232).

**Used distribution**
 Debian stable

**Expected behaviour you didn't see**
 The documentation is not crystal clear on this but, I would have expected that when a container does not have a private network namespace (either through the `nspawn` command line switch, or through the corresponding `/etc/systemd/nspawn/name.spawn` configuration file entry) it does also not have CAP_NET_ADMIN capability.

**Unexpected behaviour you saw**
 With the
```
[Network]
Private=no
```
setting in the corresponding `.nspawn` configuration file, the container still has a CAP_NET_ADMIN capability.

I think one underlying issue is that it is not very clean which is the recommended mechanism to customize how containers are spawn by machined. This can be done altering the command line parameters passed to nspawn in the corresponding `systemd-nspawn@name.service` unit or with configuration entries in the `name.nspawn` files.

**Comment by poettering** [comment]
I added a fix for this on top of #9762
