### ISSUE TITLE
RFE: systemd timer support for "every 2nd week"

### ISSUE THREAD

**Issue by fabiscafe** [systemd/systemd#11768]
**Is your feature request related to a problem? Please describe.**
We need a unit to run every secound saturday a month and another unit to run every 2 month.
While the last one isnt to much of a hazzle to do, the first one seems to be not possible with a systemd timer right now. Or I'm just not able to find how to do

**Describe the solution you'd like**
```
OnCalendar=2-weekly:saturday #or something like this
```

**Describe alternatives you've considered**
Our altenative is that we run a script every week right now, that checks for a lock file, if not there, runs another script that creates a lock file and if there do not run another script and remove that lock file.
An ugly workaround for now.

It would be nice to have this supported by systemd timers itself

**Comment by poettering** [comment]
> We need a unit to run every secound saturday a month:

This should work with `OnCalendar=Sat *-*-8..14`, no? i.e. any saturday of any year and any month that is between the 8th and the 14th of every month?

> and another unit to run every 2 month

`OnCalendar=*-1/2-1` should work for this one? i.e. any year, on the first month plus every 2nd month after that.

**Comment by Tids** [comment]
Ahh, sorry my bad. Its not every second saturday a month, it's actually only "every secound saturday". So all 14 days, that saturday like in:

* feb 9th
* feb 23th
* mar 9th
* mar 23rd
* apr 6th
* apr 20th
...

**Comment by poettering** [comment]
Support for that is indeed missing.

**Comment by poettering** [comment]
But has been requested before: #6024 — closing as duplicate hence.
