### ISSUE TITLE
systemd-cgtop no longer shows memory (and io) usage

### ISSUE THREAD

**Issue by szab100** [systemd/systemd#11773]
**systemd version the issue has been seen with**
v239 + some cherry-picked upstream commits. Tested / same result on HEAD master.

**Used distribution**
Our custom built RPM for CentOS 7, but found a recent bug report for [Debian #921280](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921280)

**Expected behaviour you didn't see**
cgtop utility shows memory, io, etc (as per enabled controllers)

**Unexpected behaviour you saw**
Only CPU column is shown

**Steps to reproduce the problem**
Run systemd-cgtop while memory / io controllers are enabled

**Comment by poettering** [comment]
that patch you prepped linked above looks great. could you submit it as a PR? will merge then, and it will be attributed to you
