### ISSUE TITLE
systemd-resolve: Stub resolver cache is corrupted (CNAME hide A record)

### ISSUE THREAD

**Issue by Abam** [systemd/systemd#11789]
It seems that when systemd-resolve cache an non-existent CNAME record for a domain, any attempt to resolve A record for the same domain fail.

**systemd version the issue has been seen with**
Installed: 237-3ubuntu10.13
**Used distribution**

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Expected behaviour you didn't see**
 
Return A record for a domain when it exists.

**Unexpected behaviour you saw**
 
Resolution failed.

**Steps to reproduce the problem**

Whait for 1 minutes (github.com TTL for A record)

Try to resolv github.com CNAME record  `dig CNAME github.com`

This will return an empty result.

Then try to resolve github.com A record `dig A github.com`.

This will now return empty result unless you restart systemd-resolved or wait for cache expiration.

At  the same time using another DNS will resolve correctly `dig A github.com @8.8.8.8`.
 
Exemple :

Wait for 1 minutes to let cache expire, then run

```bash
dig CNAME github.com
dig A github.com
# no result
dig A github.com @8.8.8.8
# ;; ANSWER SECTION:
# github.com.		59	IN	A	192.30.253.113
# github.com.		59	IN	A	192.30.253.112

````

PS: Don't forget to restart systemd-resolve, before trying to post an answer.

**Comment by poettering** [comment]
Please update to a newer systemd, 237 is pretty old already, and resolved has received many fixes since then. If you can reproduce this on 241, please report back. Thank you!

**Comment by poettering** [comment]
(btw, our bug submission form is supposed to be very clear that we only track issues in the two most recent systemd versions here, which are 240 and 241 right now. For everything else, please contact your downstream distro instead, they'll help you)
