### ISSUE TITLE
test: intermittent fail in systemd-networkd-tests.py (NetworkdNetWorkBondTests/test_bridge_property)

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#11806]
This is an issue already discovered by @yuwata, but it seems to be intermittent, see https://github.com/systemd/systemd/pull/11767#issuecomment-465508541

```
======================================================================
FAIL: test_bridge_property (__main__.NetworkdNetWorkBondTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 1119, in test_bridge_property
    self.assertRegex(output, 'State: degraded \(configured\)')
AssertionError: Regex didn't match: 'State: degraded \\(configured\\)' not found in 'â— 73: bond99\n       Link File: /usr/lib/systemd/network/99-default.link\n    Network File: /run/systemd/network/bond99.network\n            Type: bond\n           State: no-carrier (configured)\n          Driver: bonding\n      HW Address: 66:d2:07:7e:e8:85\n         Address: fe80::64d2:7ff:fe7e:e885'

```

Full log: https://ci.centos.org/job/systemd-pr-build/4945/artifact/systemd-centos-ci/artifacts_QMIwe9/testsuite-logs.Fpx/systemd-networkd-tests.py_FAIL.log

**Comment by yuwata** [comment]
Yeah, I've not found the root of the error... But #11767 updates the relevant test, and I do not find similar failure in #11767.

**Comment by yuwata** [comment]
@mrc0mmand I've created #11808. Though, it may need to run CentOS CI several times to confirm whether the PR fixes this issue or not.

**Comment by mrc0mmand** [comment]
@yuwata I'll run it several times manually in the CentOS CI infra (and only the `systemd-networkd-tests.py`) to make it faster.
