### ISSUE TITLE
Support `User` and `Group` identifiers up to `LOGIN_NAME_MAX`

### ISSUE THREAD

**Issue by cipriancraciun** [systemd/systemd#11801]
## Edit

Apparently the current `systemd.exec` [manual](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) states that:
> The user/group name must have at least one character, and at most 31. These restrictions are enforced in order to avoid ambiguities and to ensure user/group names and unit files remain portable among Linux systems.

However, at least the length, seems quite limiting, especially since as mentioned other tools like `sudo`, `ssh` and including `adduser` / `useradd` allow longer names...

Therefore I would say that, at least according to `systemd`'s own manual, this is not a "bug", but a "feature request"?

----

## Original

**systemd version the issue has been seen with**
> systemd 234
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=hybrid

I understand that this is quite an old version of `systemd`, however quickly looking at the commits and other issues, no other seems to mention this issue, therefore I suspect this issue is still present.

**Used distribution**
 > openSUSE Leap 15.0

**Expected behaviour you didn't see**
 > `systemd` should allow the usage in unit files of `User` and `Group` identifiers longer than 32 characters (including), and up to `LOGIN_NAME_MAX`, as all the other tools, including `sudo`, `ssh`, etc.

**Unexpected behaviour you saw**
 > `systemd` fails with an `Invalid user/group name or numeric ID: services--app-123456789--staging` error, and a simple removal of a `g` at the end of the username would make this error disapear, and instead an (expected) error of `Failed to determine user credentials` to be issued.

**Steps to reproduce the problem**
> Just create a simple unit file and for the `User` or `Group` attributes put a name that is 32 characters or longer.

**Comment by poettering** [comment]
I am all on board with that. However, the `utmp` database only supports user names up to 32ch currently. Given that that's an integral API of Linux, and exposed through glibc and whatnot, we don't permit user names that couldn#t be stored in utmp.

I am all on board with extending the limit, but this really should be done in glibc first, i.e. please work with the libc maintainers first to raise the utmp size limit. After that, a simple recompile of systemd will suffice to make the longer names available.

**Comment by poettering** [comment]
(UT_NAMESIZE is the limit to look for in the glibc APIs btw. it's the same for classic utmp and for utmpx in glibc, at 32.)

**Comment by cipriancraciun** [comment]
> I am all on board with that. However, the `utmp` database only supports user names up to 32ch currently.

The `UT_NAMESIZE` constant you are mentioning is actually used in `struct utmp` as `char ut_user[UT_NAMESIZE];`, thus I have serious doubts that anyone would touch that without breaking a lot of already existing tools and libraries...

Moreover the `utmp` manual states:
>  The  utmp file allows one to discover information about who is currently using the system.  There may be more users currently using the system, because not all programs use utmp logging.

Thus taking into account the previous two, and that here I'm speaking about actual `.service` units, therefore with no `utmp` interaction, I think a concession could be made.
