### ISSUE TITLE
Remove backslashes in file names from Git repository

### ISSUE THREAD

**Issue by GSPP** [systemd/systemd#11817]
It is currently not possible to check out the Git repository on Windows. There is a file with a backslash in it's name. Such a file cannot exist on Windows.

I was just trying to look at the systemd source code out of curiosity so this is not really a showstopper issue.

> error: unable to create file test/fuzz/fuzz-unit-file/dev-mapper-fedora_krowka\x2dswap.swap: No such file or directory

**Comment by poettering** [comment]
This file is named like that for a reason. I doubt that ability to looking at the systemd sources from Windows is a strong enough usecase to do anything about this, hence don#t hold your breath...

**Comment by mwleeds** [comment]
This also means you can't copy the systemd repo to a FAT32 formatted flash drive:
```
$ cp dev-mapper-fedora_krowka\\x2dswap.swap /run/media/mwleeds/flash_drive/Desktop/systemd/test/fuzz/fuzz-unit-file/
cp: cannot create regular file '/run/media/mwleeds/flash_drive/Desktop/systemd/test/fuzz/fuzz-unit-file/dev-mapper-fedora_krowka\x2dswap.swap': Invalid argument
```
