### ISSUE TITLE
systemd.show_status=no or auto  still displays boot information

### ISSUE THREAD

**Issue by tnemeth** [systemd/systemd#11813]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > debian testing

**Expected behaviour you didn't see**
 > I expected to see no messages about started services displayed at boot time (and stopped
 > services messages stopping at shutdown time).

**Unexpected behaviour you saw**
 > I saw services messages even though I had tried either/both the kernel bootparam "quiet" and
 > "systemd.show_status=no", and even played with the loglevel bootparam:

cat /proc/cmdline 
> BOOT_IMAGE=/boot/vmlinuz-4.19.0-2-amd64 root=UUID=c5a933aa-80c8-454c-8028-77b2b295e0e4 ro quiet loglevel=1 systemd.show_status=no

The man page says :
 > ...
 >          If off, no such status information is shown. If set to
 >          auto behavior is similar to off, except that it is automatically
 >          switched to on, as soon as the first unit failure or significant
 >          boot delay is encountered.

**Steps to reproduce the problem**
- set  the kernel boot parameters in /etc/default/grub so that the GRUB (`GRUB_CMDLINE_LINUX_DEFAULT`) configuration line about kernel parameters is `quiet systemd.show_status=no`  or `quiet systemd.show_status=auto`
- run `update-grub`
- reboot

**Comment by poettering** [comment]
So, what boot msgs did you see? What makes you think systemd printed those?

**Comment by tnemeth** [comment]
Honored to see you reply in person :)

Since systemd is the init system on my machines, I assumed it was its role to start and stop services. Moreover messages are typical systemd stuff such as "Reached target timers", and general look&feel that is not sysV style boot.

As you can see in the attached files. If you think these are not systemd message, I'd be happy to
know where they come from and close the report.

![20190225_180433](https://user-images.githubusercontent.com/280279/53354835-fba65300-3927-11e9-9504-9222db644f53.jpg)
![20190225_180436](https://user-images.githubusercontent.com/280279/53354836-fba65300-3927-11e9-9734-9a70b7d90775.jpg)
![20190225_180453](https://user-images.githubusercontent.com/280279/53354837-fba65300-3927-11e9-8bef-d1ffe904b524.jpg)
![20190225_180455](https://user-images.githubusercontent.com/280279/53354839-fba65300-3927-11e9-957d-675fb047cb54.jpg)

**Comment by poettering** [comment]
those are indeed systemd msgs. Can you please check whether `systemd.show_status=no` shows up in /proc/cmdline? Also, what does `busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ShowStatus` output?

**Comment by tnemeth** [comment]
Le lundi 25 février 2019, 18:28:30 CET Lennart Poettering a écrit :
> those are indeed systemd msgs. Can you please check whether
> `systemd.show_status=no` shows up in /proc/cmdline? Also, what does
> `busctl get-property org.freedesktop.systemd1
> /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager
> ShowStatus` output?


The kernel command line is almost the same as in the initial bug 
report.


```
thomas@hellaynnea:~$ cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-4.19.0-2-amd64 
root=UUID=c5a933aa-80c8-454c-8028-77b2b295e0e4 ro quiet loglevel=0 
systemd.show_status=no
```

(although putting "auto" instead of "no" gives the same results)

```
thomas@hellaynnea:~$ busctl get-property org.freedesktop.systemd1 /org/
freedesktop/systemd1 org.freedesktop.systemd1.Manager ShowStatus
b false
```

HTH but to me it seems prefectly in sync but the boot messages :(
I'll put back auto since it's really what I want (when it works).


Can it be debian-specific ? I browsed the debian documentation about
systemd but found nothing relevant (maybe I just skipped it so I'll
try to take a look at it again, not with very much hope however).


Thomas.

**Comment by yuwata** [comment]
It works fine for me. systemd is started with `--show-status` command line (not kernel command line) option?

**Comment by tnemeth** [comment]
Le 26/02/2019 à 05:53, Yu Watanabe a écrit :
> It works fine for me. systemd is started with |--show-status| command 
> line (not kernel command line) option?

In my case systemd should be started as `/sbin/init` by the kernel. Or
I hope so as it is the init system. On my systems `/sbin/init` is a
symlink to `/lib/systemd/systemd` which is a binary. As the kernel does
not start `/sbin/init` with command line arguments, kernel command line
should be used to parse any init argument.

How do you boot up you system using that command line ? As an embedded
systems developper the only way to use a command line option is to have
another init that would start systemd with the necessary parameters. It
doesn't seem to be the case here :)

Are you talking about / using containers for that ?

If indeed you can make systemd start correctly using the command line
it means that (at least for me) there is a bug in kernel bootparams
parsing :) Not that it is really important, just some annoying messages
when they are not needed since everything boots fine.

By the way, I found a `/etc/systemd/system.conf` file that has a section
called `[Manager]` containing (on my debian testing systems) a commented
out line : `#ShowStatus=yes`

I'll try to uncomment it today in order to see if it has an effect...

Thanks.

**Comment by poettering** [comment]
do you have plymouth running or something similar?

**Comment by tnemeth** [comment]
Installed but without splashscreen. Removing it now... And after removing it, indeed, boot messages do not appear anymore.

What's the link between plymouth and systemd boot messages ?

Anyway, thanks for all. It did the trick.

**Comment by poettering** [comment]
ply explicitly enables the status output in systemd, since it wants to show it.

**Comment by garyvdm** [comment]
FYI there is a plymouth build time config option to disable this behaviour: `PLY_ENABLE_SYSTEMD_INTEGRATION`

I've logged a bug with plymouth to add this as a runtime config option: https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/177
