### ISSUE TITLE
Unit.ConditionNull and/or Unit.AssertNull not documented

### ISSUE THREAD

**Issue by SJrX** [systemd/systemd#11812]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > N/A

**Expected behaviour you didn't see**
 > Documentation for Unit.ConditionNull and/or Unit.AssertNull

**Unexpected behaviour you saw**
 > No documentation

**Steps to reproduce the problem**
1) Look at https://github.com/systemd/systemd/blob/master/src/core/load-fragment-gperf.gperf.m4
2) Notice parameters Unit.AssertNull and/or Unit.ConditionNull
3) Look at documentation for Conditions (https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=)
4) Look at https://www.freedesktop.org/software/systemd/man/systemd.directives.html 
5) Look at https://github.com/systemd/systemd/blob/master/NEWS#L3446 no mention of this setting being removed or deprecated.

**Comment by kirbyfan64** [comment]
https://github.com/systemd/systemd/blob/v241/man/systemd.unit.xml#L1014-L1017

```
        <!-- We do not document ConditionNull=
             here, as it is not particularly
             useful and probably just
             confusing. -->
```

IMO it'd be nice for the sake of complete documentation at minimum, maybe with a warning.

**Comment by SJrX** [comment]
I guess I'd concur that it should be documented, but I'm biased since I'd have to write my own documentation for it to display to users, and I don't know what it does :smile:

**Comment by poettering** [comment]
We deprecate concepts all the time by removing things from the documentation while still supporting it in the code. We explicitly don't want to confuse users with long-unsupported options, this is just one among many. This is the modus operandi we picked to keep the documentation digestable while maintaining compatbility behind the curtains.

I am sorry, but this is not going to change. Sorry!

**Comment by SJrX** [comment]
Hi @poettering that makes complete sense. There are other options in the documentation that have disappeared, and that's fine I can work around them and manually handle the cases. There are others that are marked as DISABLED_LEGACY or whatever that I can handle, or DISABLED_EXPERIMENTAL ( I think these are the consts, but maybe not exactly I can't check right now). 

My concern is the following, I could see unit files with these keys. I don't know how to handle them. it's syntactically valid so I shouldn't mark them invalid. If I don't mark them invalid i don't really have an option of not documenting it. 

Other than the fact that they seem to take a Boolean, I don't know what they do. I also don't know what the semantics of that Boolean are. So what should I put as the documentation for it on my end? 

I don't think these are deprecated so I don't think I should tell users to switch to something else. Ultimately what is your recommendation for what an editor should do when it sees those keys if that makes sense.

**Comment by poettering** [comment]
> My concern is the following, I could see unit files with these keys. I don't know how to handle them. it's syntactically valid so I shouldn't mark them invalid. If I don't mark them invalid i don't really have an option of not documenting it.

well, they are valid, but deprecated. I figure we should print a log message about that when parsing such unit files...

> Other than the fact that they seem to take a Boolean, I don't know what they do. I also don't know what the semantics of that Boolean are. So what should I put as the documentation for it on my end?

in your tool, mark them as valid but deprecated, and use a short string such as "This is deprecated, do not use." as description string if you need to add something.

**Comment by SJrX** [comment]
Sounds great, thanks!

**Comment by poettering** [comment]
Added the deprecation warning when it is used in #11890 now.
