### ISSUE TITLE
Restarting systemd-logind drops user inhibitors and polkit auth

### ISSUE THREAD

**Issue by Vladimir-csp** [systemd/systemd#11825]
**systemd version the issue has been seen with**
> since v238 or v239, still seen on v240

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
 > inhibitors and polkit auth from user session are preserved

**Unexpected behaviour you saw**
 >  inhibitors and polkit auth from user session are dropped

**Steps to reproduce the problem**
1. Run a user session with power management tool. (`lxqt-powermanagement` in my case).
2. `systemctl restart systemd-logind`
3. `systemd-inhibit --list` - lxqt-powermanagment block inhibitor is no longer present.
4. restart lxqt-powermanagment to restore inhibition, trigger suspend
5. auth dialog is shown since auth for `org.freedesktop.login1.suspend` action was lost.

Prior to systemd v238 systemd-logind restart did not cause the loss of inhibitors and authentication.
This problem was also seen [affecting cinnamon](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906231)

**Comment by keszybz** [comment]
Right now, restarting `systemd-logind` crashes `gnome-shell`. I strongly suspect that there's more than one bug here, and we if we start poking this, we'll end up with bigger changes. So I'm inclined to move this to v243, so we can release quickly, and figure out a fix in proper time.

**Comment by poettering** [comment]
I am very sure losing the polkit priv makes sense, and is not fixable in logind anyway (since we lose the bus name, and thus appear to be a new client to polkit)

The losing of the inhibitor is fixed in #13143.

**Comment by Vladimir-csp** [comment]
> I am very sure losing the polkit priv makes sense, and is not fixable in logind anyway (since we lose the bus name, and thus appear to be a new client to polkit)

Why logind restart was harmless before v238?
