### ISSUE TITLE
"systemctl reboot <arg>" broken since v240

### ISSUE THREAD

**Issue by johnkeeping** [systemd/systemd#11828]
It seems that commit d85515edcf ("units: use SuccessAction=reboot-force in systemd-reboot.service") has broken `systemctl reboot <arg>` when `-f` is not specified.

As far as I can tell, the initial `systemctl reboot` writes `/run/systemd/reboot-param` correctly but then `systemd-reboot.service` runs and the SuccessAction causes the reboot parameter to be reset by calling `update_reboot_parameter_and_warn()` unconditionally from `emergency_action()`.

Prior to this commit, `systemd-reboot.service` invoked `systemctl reboot -f` which only updates the reboot parameter if an additional argument is specified.

**Comment by poettering** [comment]
PR pending in #11602

**Comment by poettering** [comment]
Fixed by #11602. Closing.
