### ISSUE TITLE
systemctl is-active / is-enabled exit status code is always zero when multiple arguments are given

### ISSUE THREAD

**Issue by christidis** [systemd/systemd#11826]
**systemd version the issue has been seen with**
> systemctl --version
>systemd 232
>+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

> systemctl --version
>systemd 237
>+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
Debian `9.8` for systemd `232`
 > uname -a
>Linux deb00 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

Ubuntu `18.04` for systemd `237`
>uname -a
>Linux ub00 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Expected behaviour you didn't see**
I would expect `is-enabled` / `is-active` subcommands to exit with a non-zero exit status code when multiple arguments are given and one of them is not enabled (or active in case of `is-active`).

**Unexpected behaviour you saw**
 > \# systemctl is-enabled docker.service ; echo $?
>disabled
>1
> \# 
> \# systemctl is-enabled docker.service ssh.service ; echo $?
> disabled
> enabled
> 0

**Steps to reproduce the problem**

Example is given for the `is-enabled` subcommand but the same thing applies for the `is-active` subcommand when multiple mounts are given.

> \# systemctl is-enabled cron.service ssh.service ; echo $?
> enabled
> enabled
> 0
>
> \# systemctl is-enabled ssh.service ; echo $?
> enabled
> 0
>
> \# systemctl disable ssh.service 
> Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install disable ssh
> Removed /etc/systemd/system/sshd.service.
>
> \# systemctl is-enabled ssh.service ; echo $?
> disabled
> 1
>
> \# systemctl is-enabled cron.service ssh.service ; echo $?
> enabled
> disabled
> 0
>
> \# systemctl enable ssh.service 
> Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable ssh
> Created symlink /etc/systemd/system/sshd.service → /lib/systemd/system/ssh.service.

**Comment by poettering** [comment]
is-enabled does the exact opposite currently: it returns 0 if at least one of the specified units are enabeld.

This is even documented explicitly in systemctl(1):

> Returns an exit code of 0 if at least one is enabled, non-zero otherwise.

**Comment by poettering** [comment]
(It's similarly documented for is-active btw.)

(And I just played around with this, all works as it should there. Closing hence, as this appears to work as documented. Or what am I missing?)
