### ISSUE TITLE
Unknown lvalue 'WatchdogSignal' in section 'Service'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [systemd/systemd#11835]
**systemd version the issue has been seen with**
> systemd 239
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Watchdog send `SIGTERM`.

**Unexpected behaviour you saw**
 > Unknown lvalue 'WatchdogSignal' in section 'Service'.

**Steps to reproduce the problem**

```
[Service]
ExecStart=...
Restart=on-failure
RestartSec=1
Type=simple
WatchdogSec=30
WatchdogSignal=SIGTERM
```

**Comment by anitazha** [comment]
`WatchdogSignal=` was not available until v240.

**Comment by Alexander-Shukaev** [comment]
Ouch!
