### ISSUE TITLE
Script to run before any shutdown action

### ISSUE THREAD

**Issue by macielbassp** [systemd/systemd#11847]
**Is your feature request related to a problem? Please describe.**
I need to do some "stop" actions with our DB2 database servers, even denying shutdown in certain situations.
The way DB2 starts under TSAMP clusters put it under "user.slice", and systemd at shutdown kill user processes first, and then starts to stop services.
I wrote an unit file with After=multi-user.target and WantedBy=multi-user.target - but was not enough. The ExecStop script is called too late, systemd has already killed some DB2 processes.

**Describe the solution you'd like**
I need systemd run a script before any shutdown action (before killing user.slice processes!), and the script could have a way to deny shutdown (e.g. failing, return code<>0)

**Describe alternatives you've considered**
Replacing "shutdown" and "reboot" utilities... is not elegant, and our sysadmins use automated tools to reboot our servers, I not sure this workaround will intercept a vmware-commanded reboot. And what to do with "systemctl reboot"?

**Comment by poettering** [comment]
This is not a support forum, but a bug and feature request tracker. Please use your distros forums or our mailing list for support, but please do not file support tickets here. Thank you for understanding.

The issue submission form should have made that clear btw, please read it before submitting. Thank you for understanding.
