### ISSUE TITLE
loginctl show-user -p Session does not work anymore

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#1184]
After moving to sd-bus loginctl show-user is no longer able to print Display and Sessions:
systemd-208:
[lnykryn@notas systemd-rhel(rhel-7.1)]$ ./loginctl show-user -p Display -p Sessions lnykryn 
Display=1
Sessions=1

and current git:
[lnykryn@notas systemd(master)]$ ./loginctl show-user -p Display -p Sessions lnykryn 
Display=[unprintable]
Sessions=[unprintable]

**Comment by msekletar** [comment]
Problem is that `bus_print_property` can't print complex types and `Sessions` property has type `a(so)`.

**Comment by poettering** [comment]
I am surprised this is supposed to have worked once upon a time.

**Comment by lnykryn** [comment]
https://github.com/systemd/systemd/commit/2a998c74028a109d6bd8888951abfa8e25a15fb1 -> fixed
