### ISSUE TITLE
networkd sometimes fails to start in LXC: Could not enumerate rules: Device or resource busy

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#11848]
**systemd version the issue has been seen with**
> 241, master

**Used distribution**
 > Debian unstable, Ubuntu 18.04

When setting up tests in LXC in PR #11814, I found that two networkd tests are unreliable in a container (specifically in LXC, I haven't tried nspawn or lxd yet) when that runs in a VM:
```
======================================================================
ERROR: test_route_only_dns_all_domains (__main__.NetworkdClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.sk515c20/downtmp/build.oPb/src/test/networkd-test.py", line 504, in test_route_only_dns_all_domains
    extra_opts='IPv6AcceptRouterAdvertisements=False')
  File "/tmp/autopkgtest-lxc.sk515c20/downtmp/build.oPb/src/test/networkd-test.py", line 355, in do_test
    subprocess.check_call(['systemctl', 'start', 'systemd-networkd'])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', 'start', 'systemd-networkd']' returned non-zero exit status 1.
```
This also happens to the related `test_route_only_dns()` test case.

Corresponding networkd journal when this happens:
```
systemd-networkd[3202]: /run/systemd/network/myvpn.network:4: An address '192.168.42.100' is specified without prefix length. The behavior of parsing addresses without prefix length will be changed in the future release. Please specify prefix length explicitly.
systemd-networkd[3202]: dummy0: netdev ready
systemd-networkd[3202]: dummy0: Gained IPv6LL
systemd-networkd[3202]: eth0: Gained IPv6LL
systemd-networkd[3202]: rtnl: received unexpected message type when processing route, ignoring
systemd-networkd[3202]: Could not enumerate rules: Device or resource busy
systemd[1]: systemd-networkd.service: Child 3202 belongs to systemd-networkd.service.
Feb 26 21:48:29 bionic-amd64 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 21:48:29 bionic-amd64 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
```

This happens both in [semaphore (xenial)](https://semaphoreci.com/systemd/systemd/branches/pull-request-11814/builds/2) as well as [Debian](https://ci.debian.net/data/autopkgtest/unstable/amd64/s/systemd/2018852/log.gz). In both cases, the container runs in a VM (OpenStack in Ubuntu CI, Amazon EC2 in Debian CI).

The test (with a recent version of systemd with taking binaries from a PR) can be run on Fedora 29:
```
sudo lxc-create -n bionic-amd64 -t download -- -d ubuntu -r bionic -a amd64
curl https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190226_181418_8a58c@/artifacts.tar.gz | tar -C /tmp -xz
cd ~/debian/systemd  # master branch of Debian systemd packaging
autopkgtest -B . /tmp/binaries/*.deb --test-name networkd-test.py -s -- lxc -s bionic-amd64
```
But when running it on bare metal, it works (at least for me). But when it's running in a VM, I can reproduce this really reliably locally (in fact, I haven't ever seen it to not fail).

The failure happens even after a `time.sleep(5)`, or with stopping networkd and downing the interface before running the test, and also with additionally stopping resolved before.

`manager_rtnl_enumerate_rules()` has several things that can go wrong, I'll need to add additional debugging to see what fails exactly.

This isn't a recent regression, it happens with 241 as well.

I'm filing this to collect further data/debugging notes, and also to have something to refer to for adjusting these two checks to EXFAIL in a container (it's better to get CI to green again, and investigate this particular issue, than continuing this "all PRs are red" madness, IMHO).

**Comment by yuwata** [comment]
@vaibhav-rustagi Hm, v239 is too old here for now... And not sure, but it seems your issue is already fixed by #18545, which is included in v248.

Please test v248 or newer.

**Comment by vaibhav-rustagi** [comment]
@yuwata Thanks for providing the reference to the above commits. 

I am still having difficulty in understanding as how the problem specified in the above commits will result in the actual issue of `Device or resource busy` when enumerating the routing rules? Can you help in explaining your understanding? Thanks in advance.

**Comment by yuwata** [comment]
Hm? `-EBUSY`? No, I do not know where it comes from.

My comment is about the log message `rtnl: received unexpected message type when processing route, ignoring`.

**Comment by yuwata** [comment]
@martinpitt and @vaibhav-rustagi Is still this issue relevant to a recent release? If so, please provide debugging logs of networkd with a newer version.

**Comment by martinpitt** [comment]
I'm not actively working on systemd these days, so I honestly can't tell how stable the test is now. The test still runs in current CI (e.g. [here](https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/amd64/s/systemd-upstream/20221031_221328_dfa0c@/log.gz)), so if it's not flaky any more, I suppose it's fixed and you can close this. Thanks!

**Comment by yuwata** [comment]
Thanks. IIRC, networkd tests in Ubuntu CIs are not flaky now. Closing.
