### ISSUE TITLE
automount with ssh keys doesn't work

### ISSUE THREAD

**Issue by ktmdms** [systemd/systemd#11860]
/etc/fstab entry:
user@10.30.1.16:/fs/kevintest/4118171/upload_zip /chroot/home/kevintest/home/kevintest/upload fuse.sshfs x-systemd.automount,x-systemd.device-timeout=2min,uid=1648,gid=21002,_netdev,allow_other,nonempty,StrictHostKeyChecking=no,IdentityFile=/root/keys/ftp.key 0 0

/root/keys has permissions 700, /root/keys/ftp.key has permissions 600

 cat /run/systemd/generator/chroot-home-kevintest-home-kevintest-upload_zip.automount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=remote-fs.target
[Automount]
Where=/chroot/home/kevintest/home/kevintest/upload_zip

 cat /run/systemd/generator/chroot-home-kevintest-home-kevintest-upload_zip.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)

[Mount]
What=user@10.30.1.16:/fs/kevintest/4118171/upload_zip
Where=/chroot/home/kevintest/home/kevintest/upload_zip
Type=fuse.sshfs
Options=x-systemd.automount,uid=1648,gid=21002,_netdev,allow_other,nonempty,StrictHostKeyChecking=no,IdentityFile=/root/keys/ftp.key

systemctl restart chroot-home-kevintest-home-kevintest-upload_zip.automount fails with:

chroot-home-kevintest-home-kevintest-upload_zip.automount: Directory /chroot/home/kevintest/home/kevintest/upload_zip to mount over is not empty
Failed to initialize automounter: No such file or directory
Failed to set up automount chroot-home-kevintest-home-kevintest-upload_zip.automount.

help greatly appreciated.

**Comment by poettering** [comment]
Please fill in the issue submission form properly. We need to know which systemd and kernel version you are using, which distro and so on. The form exists for a reason, please don't simply delete the form data.

> Failed to initialize automounter: No such file or directory

This suggests your kernel has no automounter support. Has it?

**Comment by ktmdms** [comment]
Issue submissions form?  When I clicked on New Issue I saw no such form.  but for the sake of argument:

Distro is Oracle Linux 7
Kernel 4.1.12-124.23.2.el7uek.x86_64
systemd-219-62.0.3.el7.x86_64

It certainly supports autofs automounting as it's used daily to mount user home directories on login.  Is there more to the kernel support that I should be looking for?  And I'm happy to fill out the "form" if you can point me to it.

Kevin

**Comment by poettering** [comment]
As the issue submission form should have made abundantly clear this bug tracker is only for the two most recent *upstream* systemd versions, i.e. 240 and 241 right now. For everything older, please contact your downtsream distribution, they'll help you. Thank you for understanding.

Given the error `Failed to initialize automounter: No such file or directory` you are seeing it appears your kernel doesn't do autofs at all though. Please ask your OS vendor for help on that, and why autofs support might be missing.

Anyway, closing, as this version is too old for it to be tracked here upstream, and the issue appears to be a distro problem anyway.

**Comment by ktmdms** [comment]
Hey poettering, Since it's closed I'll go ahead and add one more comment to let you know what the final problem was:

chrooted directory structure, mount point was a point like /a/b/c/b/c/d that was actually a link back to a directory of /a/b//c/d that systemd gagged on.  the issue had nothing to do with our version of systemd (unless systemd has become smarter about links or gives better error output about this issue), nor did it have to do with our kernel not supporting automount.  but thanks for the snarky responses and unhelpful commentary.  It's crap like this that really draws the community in to "loving" systemd (by the way, in case you're too stupid to pick up on that, it's sarcasm).

**Comment by poettering** [comment]
When you create a bug report issue, you see the text field pre-filled with this:

```
<!-- **NOTE:** Do not submit bug reports about anything but the two most recently released systemd versions upstream! -->
<!-- For older version please use distribution trackers (see https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#filing-issues). -->
```

We'd be happy to reword that, if it would make things clearer. What would you suggest?

Please understand that we can't deal with every support request upstream, we need to cut down a bit on that, otherwise we'd drown in giving free support without actually doing any development work. To keep frustration low for people seeking help we try to make this clear in the issue submission form. I am sorry if this wasn't clear enough, but GitHub doesn't really allow us any stricter control about issue submission than the pre-filling of the text field.
