### ISSUE TITLE
RestartPreventExitStatus= and ExecStartPre= 

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11868]
Version: 241

I'm seeing a odd or at least unexpected behaviour wrt. `RestartPreventExitStatus=`

The service in question is
```
~# systemctl cat ssh
# /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
Documentation=man:sshd(8) man:sshd_config(5)
After=network.target auditd.service
ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

[Service]
EnvironmentFile=-/etc/default/ssh
ExecStartPre=/usr/sbin/sshd -t
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/usr/sbin/sshd -t
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
```

In case of a syntax error in sshd_config, sshd will return `255`. The idea of `RestartPreventExitStatus=255` was to avoid systemd needlessly respawning the service.
But here it is actually `ExecStartPre=/usr/sbin/sshd -t` which will fail with `255`,  and systemd will respawn ssh.service until it hits a restart limit.

```
# echo bla >> /etc/ssh/sshd_config

# systemctl start ssh.service
Job for ssh.service failed because the control process exited with error code.
See "systemctl status ssh.service" and "journalctl -xe" for details.

# systemctl status ssh.service
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-03-02 14:23:36 CET; 5s ago
     Docs: man:sshd(8)
           man:sshd_config(5)
  Process: 14514 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=255/EXCEPTION)

Mär 02 14:23:36 pluto systemd[1]: ssh.service: Service RestartSec=100ms expired, scheduling restart.
Mär 02 14:23:36 pluto systemd[1]: ssh.service: Scheduled restart job, restart counter is at 5.
Mär 02 14:23:36 pluto systemd[1]: Stopped OpenBSD Secure Shell server.
Mär 02 14:23:36 pluto systemd[1]: ssh.service: Start request repeated too quickly.
Mär 02 14:23:36 pluto systemd[1]: ssh.service: Failed with result 'exit-code'.
Mär 02 14:23:36 pluto systemd[1]: Failed to start OpenBSD Secure Shell server.
```

Is it expected behaviour that `RestartPreventExitStatus` has no influence on `ExecStartPre`? And if so, could we clarify the docs in `systemd.service` please.

**Comment by poettering** [comment]
> Is it expected behaviour that `RestartPreventExitStatus` has no influence on `ExecStartPre`? And if so, could we clarify the docs in `systemd.service` please.

It already is pretty clear about that:

https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartPreventExitStatus=

> Takes a list of exit status definitions that, when returned by the main service process, will prevent automatic service restarts, regardless of the restart setting configured with Restart=. 

i.e. by main service process it is indicated that ExecStartPre= is not relevant here... I'll prep a patch that makes this even clearer.

**Comment by poettering** [comment]
Fix waiting in #11994

**Comment by pzakha** [comment]
Sorry to highjack this, but is there a way to prevent a service from restarting when it fails in ExecStart? The logic that we're using is:
1. ExecStart forks MainProcess, which does an initial boot-up.
2. ExecStart monitors the pid of MainProcess while this one is in the initial boot-up phase. If MainProcess fails here, I want the service to not restart.
Is there a way to achieve this?

**Comment by boucman** [comment]
usually, you want to try to cut out the middle man, use Type=forking and let systemd monitor your main PID directly... you can use a PIDFile= to tellsystemd what the main pid is, or use sd_notify if a PIDFile does not match your need.

Anyway, this is not related to this bug, please start a thread on the mailling list if you want to discuss this some more

**Comment by nlippis** [comment]
@mbiebl what did you ultimately end up doing?  Your use case seems valid.
