### ISSUE TITLE
Some of logs are glued together

### ISSUE THREAD

**Issue by decaz** [systemd/systemd#11867]
**systemd version the issue has been seen with**
> $ systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Used distribution**
 > $ cat /etc/system-release
CentOS Linux release 7.6.1810 (Core)
$ uname -a
Linux my.host 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > $ sudo journalctl -u my-service
...
Mar 02 15:28:23 my.host my-service[3660]: Log 123 / timestamp: 2019-03-02T12:28:23.926772Z
Mar 02 15:28:23 my.host my-service[3660]: Log 124 / timestamp: 2019-03-02T12:28:23.928605Z
Mar 02 15:28:23 my.host my-service[3660]: Log 125 / timestamp: 2019-03-02T12:28:23.928614Z
Mar 02 15:28:23 my.host my-service[3660]: Log 126 / timestamp: 2019-03-02T12:28:23.928514Z
...

**Unexpected behaviour you saw**
 > $ sudo journalctl -u my-service
...
Mar 02 15:28:23 my.host my-service[3660]: Log 123 / timestamp: 2019-03-02T12:28:23.926772Z
Mar 02 15:28:23 my.host my-service[3660]: Log 124 / timestamp: 2019-03-02T12:28:23.928605ZLog 125 / timestamp: 2019-03-02T12:28:23.928614Z
Mar 02 15:28:23 my.host my-service[3660]: Log 126 / timestamp: 2019-03-02T12:28:23.928514Z
...

**Steps to reproduce the problem**

There was 641 logs within 1 second at 15:28:23 and 14 of them was glued together so the problem can be reproduced with service which outputs logs with such high rate.

**Comment by decaz** [comment]
@yuwata do you mean that I have to upgrade systemd to the latest version and try again or it is known issue which was already fixed in a certain version of systemd?

**Comment by yuwata** [comment]
Sorry, it seems that I forgot to push the 'comment' button.

Please check v240 or v241, or please report this at downstream, RHBZ.

**Comment by poettering** [comment]
Let's close this here. As the submission form should have made abundantly clear, this issue trackers is only for issues in the two most recent upstream systemd versions. For everything else, please contact your downstream distro. They'll help you. Thank you very much.
