### ISSUE TITLE
Ordering dependency option for conflicting units (Conflicts=)

### ISSUE THREAD

**Issue by loblik** [systemd/systemd#11865]
I have two services which are mutually exclusive (both directly talks to the sound card). I want systemd to switch between these two making sure the other one is not started before the first one exits and releases the resource.

I came up with these two unit files. /home/user/systemd_test/waity is just a binary which ignores SIGTERM (to simulate the problem).

```
[Unit]
Description=Waity2
Conflicts=waity.service
Before=waity.service

[Service]
ExecStart=/home/user/systemd_test/waity
TimeoutStopSec=5
```

```
[Unit]
Description=Waity
Conflicts=waity2.service
After=waity2.service

[Service]
ExecStart=/home/user/systemd_test/waity
TimeoutStopSec=5
```
And it seems to work. However I'm not sure if this is really expected to work (and will work in the future) or I'm just lucky here. Documentation only says Before=/After= specify ordering during startup and shutdown of services but nothing about Conflicts= situation where one service is shutting down and other is being started.

I think there are three ways how to solve this:
- introducing new ordering option (something like NotAtOnce=),
- Conflicts= would always wait until running service is really stopped before it desired one is started,
- adjust documentation if there is reliable and meaningful way to have this with just Before=/After= .

**Comment by poettering** [comment]
When a unit is started while another is stopped and they have either kind of ordering dep defined between them (i.e. either After= or Before=), then the stop is executed first and the start only after that completed.

This behaviour is documented here:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=

or in other words: you already should get the behaviour you are looking for, and it's documented and explicitly supported.

Closing hence.
