### ISSUE TITLE
Any way to run instantiated units from templates one after the other 

### ISSUE THREAD

**Issue by dmitryint** [systemd/systemd#1187]
I have a template for creating the backup:
#### backup@.service

```
[Unit]
Description=Instance %i
[Service]
ExecStart=/bin/sh -c "echo do backup job for %i"
[Install]
WantedBy=maintenance.target        
```

and some target:
#### maintenance.target

```
[Unit]
Description=target for maintenance
StopWhenUnneeded=yes         
```

As can be seen, instances from backup@ start with maintenance.target. But they run in parallel.
There is some way to run them one after the other?
I thought that specifying `Conflicts=backup@*.service` in the template should lead to this, but it is not.

**Comment by poettering** [comment]
The github issues tracker is not a support forum. Please direct question like yours to the systemd mailing list, thank you.
