### ISSUE TITLE
systemctl [shutdown/reboot] --graceful option

### ISSUE THREAD

**Issue by damianatorrpm** [systemd/systemd#11876]
**Is your feature request related to a problem? Please describe.**
Logic in desktop environments is to "close" all windows on reboot/shutdown/logout
instead of killing everything and executing the action.
(ex. gedit is running with unsaved changes to file, desktop will not  reboot/shutdown/logout 
until one says to gedit Save/Not Save)
 
I could't find a proper SIGnal for doing this as well.

**Describe the solution you'd like**
systemctl-reboot --ask-close-everything

**Describe alternatives you've considered**
n/a

**Comment by poettering** [comment]
This already exists, it's the "inhibitor" logic, that systemd-logind exposes. GNOME knows a similar API that acts as frontend to logind.

Programs simply have to use that, and if they don't there's little we can do. Many do however. If yours don't please file a bug requesting support for it.

Hence, closing, as this already exists.

https://www.freedesktop.org/wiki/Software/systemd/inhibit/
