### ISSUE TITLE
systemd-sleep hangs

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#11873]
**systemd version the issue has been seen with**
> 239-241

**Used distribution**
 > Manjaro

**Expected behaviour you didn't see**
 > Laptop goes to sleep after 10min idle.

**Unexpected behaviour you saw**
 > Laptop did not go to sleep. I have to kill systemd-sleep for manual sleep (because manual sleep works)

**Steps to reproduce the problem**
Constantly repro on Dell Vostro 14-5468. Here is the logs:
https://bugs.freedesktop.org/attachment.cgi?id=142821&action=edit

and when systemd-sleep is killed:
```
[  +0.000118] i915 0000:00:02.0: GEM idle failed, suspend/resume might fail
[  +0.000004] device_prepare(): 0xffffffff91261160 returns -512
[  +0.000002] PM: Device 0000:00:02.0 not prepared for power transition: code -512
[  +0.000001] PM: Some devices failed to suspend, or early wake event detected
```
`-512` means the sleep process of i915 is manually terminated.

**Comment by philmmanjaro** [comment]
In our [current stable update](https://forum.manjaro.org/t/stable-update-2019-02-23-kernels-systemd-browsers-plasma5-python-haskell/76825) we are at **v241.244**. You may see the changes on top of **v241** [here](https://github.com/systemd/systemd/compare/v241...7e85b07).

**Comment by enihcam** [comment]
@philmmanjaro Yes, the dot version is 241.244:
```
$ yaourt -Qs systemd
core/systemd 241.244-1 (base-devel)
    system and service manager
```

**Comment by poettering** [comment]
Those msgs are kernel msgs. This is hence a kernel issue, it fails to resume prpoerly, and userspace can do little about it.

Please report this to the kernel project, this is somewhere between the kernel, the i915 driver and your firmware, but systemd can't do much about this. Sorry!
