### ISSUE TITLE
Add a PrivateKeyFile option to Wireguard Netdev

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#11878]
**Is your feature request related to a problem? Please describe.**
In NixOS  `/etc` is always world-readable the way it's symlinked to the `/nix/store`
This means that you always need to proceed with caution when handling secrets and config files.  Most config files that involve secrets allow you to define a path to a secret, instead of inlining the secret directly, however for `.netdev` files this isn't currently possible. 

**Describe the solution you'd like**
Add a new key `PrivateKeyFile` that reads the wireguard private key from disc instead of verbatim from the config file itself. This means the config file can remain world-readable, whilst the private key can be stored somewhere else (for example a ramfs in `/var/run/secrets`) 

**Describe alternatives you've considered**
Currently I use `wireguard` without `systemd-networkd` using the following script, that does allow this way of configuration:

```
ip link add dev wg0 type wireguard
ip address add ${ip} dev wg0
wg set wg0 private-key /var/run/secrets/wireguard-private-key
wg set wg0 peer ${peer-private-key}
ip link set dev up wg0
```

**Comment by yuwata** [comment]
Implementation is waiting in #11861.

**Comment by arianvp** [comment]
That was crazy quick. Thanks @yuwata !!
