### ISSUE TITLE
Resolved sets TC-flag when EDNS buff-size is to small over TCP.

### ISSUE THREAD

**Issue by simonvik** [systemd/systemd#11884]
**systemd version the issue has been seen with**
> 241

**Used distribution**
`Arch Linux, Ubuntu`

**Expected behaviour you didn't see**
> ```dig TXT txtt.sa7s.se +tcp +bufsize=1200 @127.0.0.53```

Should give me a response.

**Unexpected behaviour you saw**
> ```dig TXT txtt.sa7s.se +tcp +bufsize=1200 @127.0.0.53```

Return empty response with TC-flag set.

**Steps to reproduce the problem**
Query a record that returns a response bigger than EDNS0 udp-buffert size.

```dig TXT txtt.sa7s.se +tcp +bufsize=1200 @127.0.0.53```

I've tested multiple other DNS-servers and they dont seem to care about the EDNS0 udp buff-size when using TCP.
This is possible a duplicate of https://github.com/systemd/systemd/issues/11625 but the problem I see here is over TCP and not UDP.

**Comment by poettering** [comment]
Fix waiting in #11993
