### ISSUE TITLE
Hangs at "starting reboot". reboot -f works

### ISSUE THREAD

**Issue by tomchiverton** [systemd/systemd#11886]
**systemd version the issue has been seen with**
239

**Used distribution**
Fedora 29

**Expected behaviour you didn't see**
A reboot after running "reboot"

**Unexpected behaviour you saw**
Nothing happens after "starting rebootworking" line is printed after all other shutdown logs

**Steps to reproduce the problem**
as root run "reboot"

I've followed https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1 - "reboot -f" works so I believe this is not a kernel issue.

Attaching /shutdown-log.txt produced by above link
[shutdown-log.txt](https://github.com/systemd/systemd/files/2926144/shutdown-log.txt)
.

**Comment by poettering** [comment]
The logs show that systemd-shutdown works correctly and reaches its final stages. After the final messages the only thing left to do is transition back into dracut, which might disassemble storage backing the root fs. If things hang then this happens in that, i.e. after systemd handed control back to dracut.

Hence, please contact the dracut folks, this is not systemd's territory anymore. Let's hence close this here.

**Comment by tomchiverton** [comment]
I understand that you are saying its been handed off at the end of the systemd part of shutdown OK, but this other part is either not receiving the instruction from systemd or ignoring it. 
Can you help me confirm what systemd is sending and where to? Maybe this is in the attached log but I do not see it. 
As '-f' works is there someway to configure systemd to do this as part of its shutdown instead of whatever it is currently doing?

**Comment by poettering** [comment]
systemd simply invokes a script provided by dracut after it is fully done. That script is called /run/initramfs/shutdown.

This is where this all happens btw:

https://github.com/systemd/systemd/blob/master/src/core/shutdown.c#L442

It's not very complex. First you see the execute_directories() call that invokes the scripts in /usr/lib/systemd/system-shutdown/ (i.e. where the debuggin script is placed). All it does then is either switch root to /run/initramfs and then call the `shutdown` executable there. Or it sync()s and calls the Linux reboot() system call. That#s really all there is to it. If things hang, then they can only hang in the dracut script (if that's provided) or in the sync() or reboot() system calls (if the script is not available). In the former case, please report this to the dracut folks, in the latter case it looks like the kernel syscalls hang, in which case you have to report that to the kernel folks.

(given the URB and DRM kernel msgs in your logs there's a good chance it's the kernel/driver problem btw. might be worth tracking those down first)

**Comment by tomchiverton** [comment]
WFM on Fedora 30 now
