### ISSUE TITLE
systemd got segfault but core dump failed 

### ISSUE THREAD

**Issue by sugarfillet** [systemd/systemd#11885]
hi everyone. I have a centos7.3 machine whose systemd verison is systemd-219-57 & kernel version is kernel-3.10.0-514.
Once I reboot the machine, It must hung.

First I opened the sysetemd debug in kernel params & collected the series port log. Here is it ...
```
systemd[1]: segfault at f6f686ab ip 00007fc4e9a79361 sp 00007ffef196eb30 error 4
..
Caught <SEGV>, core dump failed (child 770, code=killed, status=11/SEGV).
Reboot execution.
```
the remain log makes no sense for me, so i don't post it.

Obviously, the root cause can't be found without the core or call stack. So I aimed to the dumping of the core.

Then I read the systemd crash() code, what confuses me is that why crash process killed itself by signal 11 but the wait return is CLD_KILLED instead of CLD_DUMPED.
Is it related about the default signal 11's handler which lives in kernel ? Or there is a switch control the wait return ? As I know, systemd.dump_core is not the switch. 

So, Can I get the systemd's core dumped or just log call stack to console? Any advise?

Thanks.

**Comment by poettering** [comment]
As the issue submission form should have made very clear: this is an issue tracker for upstream issues only, specifically the two most recently released *upstream* systemd versions. That is v240 and v241 currently. v219 is very much too old. For older releases please contact your downstream distro instead, they will help you. Thank you for understanding.
