### ISSUE TITLE
Hostname is set late in the boot process

### ISSUE THREAD

**Issue by jpalus** [systemd/systemd#11880]
Recently I've upgraded from systemd 239 to 241 and new issue appeared with LightDM -- first login session after boot always segfaults, while subsequent login attempts succeed. After quick googling it turned out that most probable cause is hostname change between LightDM startup and login attempt. Indeed that changed significantly between those two versions.

In 239 hostname setting is first operation after switching root:

    Mar 03 23:10:38 localhost systemd[1]: Switching root.
    Mar 03 23:10:38 localhost systemd-journald[242]: Journal stopped
    Mar 03 23:10:38 kalarepa systemd-journald[242]: Received SIGTERM from PID 1 (systemd).
    Mar 03 23:10:38 kalarepa kernel: printk: systemd: 17 output lines suppressed due to ratelimiting
    Mar 03 23:10:38 kalarepa systemd[1]: systemd 239 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hi>
    Mar 03 23:10:38 kalarepa systemd[1]: Detected architecture x86-64.
    Mar 03 23:10:38 kalarepa systemd[1]: Set hostname to <kalarepa>.

While in 241 it happens much later:

    Mar 03 23:15:07 localhost systemd[1]: Switching root.
    ...
    Mar 03 23:15:14 localhost NetworkManager[1121]: <info>  [1551651314.1340] dhcp4 (em1):   hostname 'kalarepa'
    ...
    Mar 03 23:15:14 localhost NetworkManager[1121]: <info>  [1551651314.1450] policy: set-hostname: set hostname to 'kalarepa' (from DHCPv4)
    ...
    Mar 03 23:15:14 kalarepa systemd-hostnamed[1391]: Changed host name to 'kalarepa'

It actually even looks as if NetworkManager was setting hostname. Is this all intentional? Is there a way to bring back old behavior?

**Comment by jpalus** [comment]
After some debugging it turned out issue is on my end after all.

**Comment by Jcpetrucci** [comment]
Can you share what you found the issue to be please?

I am seeing a difference between CentOS 7 (systemd 219) and CentOS 8 (systemd 239).  On 239, the hostname during early boot is "localhost.localdomain" but then switches:

$ sudo journalctl -b | grep hostname
Aug 13 17:24:11 localhost.localdomain systemd[1]: Set hostname to <localhost.localdomain>.
Aug 13 17:24:16 real-hostname.real-domain systemd[1]: Set hostname to <real-hostname.real-domain>.
Aug 13 17:24:24 real-hostname.real-domain dbus-daemon[1039]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.8' (uid=0 pid=1278 comm="/usr/sbin/NetworkManager --no-daemon " label="system_u:system_r:NetworkManager_t:s0")
Aug 13 17:24:26 real-hostname.real-domain dbus-daemon[1039]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug 13 17:24:26 real-hostname.real-domain NetworkManager[1278]: <info>  [1597339466.5408] hostname: hostname: using hostnamed
Aug 13 17:24:26 real-hostname.real-domain NetworkManager[1278]: <info>  [1597339466.5410] hostname: hostname changed from (none) to "real-hostname.real-domain"
Aug 13 17:24:27 real-hostname.real-domain systemd-resolved[1562]: Using system hostname 'real-hostname.real-domain'.

**Comment by jpalus** [comment]
IIRC at that time it was a faulty patch in my distribution of choice. You should most likely customize your hostname with hostnamectl.

**Comment by Jcpetrucci** [comment]
@jpalus Thanks for the reply.  I had indeed customized the hostname with `hostnamectl set-hostname` already, but the strange behavior I observed was that the customized name was not being "applied" (?) until shortly after the boot process.  The system was somehow holding on to the original (from kickstart) hostname.

For anyone else having the issue, I determined that the unwanted hostname was being pulled from /boot/initramfs/etc/hostname.

For my issue, I will continue by looking into whether I am doing something fundamentally incorrect by setting a temporary hostname during my builds, or if it is possible to exclude the temporary hostname from being forever burned into initramfs.

**Comment by TriMoon** [comment]
@Jcpetrucci 
> For my issue, I will continue by looking into whether I am doing something fundamentally incorrect by setting a temporary hostname during my builds, or if it is possible to exclude the temporary hostname from being forever burned into initramfs.

IMHO, it's definitely wrong to hard-code/burn a hostname into an initramfs, a system's hostname should be dynamic in respect to static files like an initramfs.
The actual installed system can then later decide to "fix" it to some static name or use DHCP etc, but that should not be in an initramfs unless you intent to use that initramfs for only a single special-use boot (imho even in such case it shouldn't be in initramfs)

**Comment by jpalus** [comment]
Actually observed behavior seems wrong for two reasons:
* I would have expected that initramfs packs your /etc/hostname with actual hostname, perhaps you need to regenerate initramfs?
* systemd is started early in initramfs where it sets hostname from initramfs, but after switching root to actual system it reexecutes and sets hostname again, therefore you should end up with proper hostname anyway

Proof from one of my VMs:
```
Aug 14 13:04:35 pld-early systemd[1]: systemd 246 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Aug 14 13:04:35 pld-early systemd[1]: Detected virtualization kvm.
Aug 14 13:04:35 pld-early systemd[1]: Detected architecture x86-64.
Aug 14 13:04:35 pld-early systemd[1]: Running in initial RAM disk.
Aug 14 13:04:35 pld-early systemd[1]: Set hostname to <pld-early>.
--
Aug 14 13:04:36 pld-early systemd-journald[202]: Journal stopped
Aug 14 13:04:37 pld-late systemd[1]: systemd 246 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Aug 14 13:04:37 pld-late systemd[1]: Detected virtualization kvm.
Aug 14 13:04:37 pld-late systemd[1]: Detected architecture x86-64.
Aug 14 13:04:37 pld-late systemd[1]: Set hostname to <pld-late>.
```

**Comment by Jcpetrucci** [comment]
> * I would have expected that initramfs packs your /etc/hostname with actual hostname, perhaps you need to regenerate initramfs?
> * systemd is started early in initramfs where it sets hostname from initramfs, but after switching root to actual system it reexecutes and sets hostname again, therefore you should end up with proper hostname anyway

True, I ultimately end up with the correct hostname.  It just bothers me to have a residual artifact of the temporary hostname during the early stages of every boot.  I use systemd-journal-upload, so in addition to the cosmetic issue in the logs on the local host, I have an issue of filtering by `_HOSTNAME` on the server which aggregates the journals of many hosts.

For clarification, here are the steps to reproduce:

1. Install CentOS 8.2.2004 with `ks.cfg` containing `network  --bootproto=dhcp --device=link --hostname=name-early.domain --activate`
2. After first boot, change hostname using `systemctl set-hostname name-late.domain`
3. Reboot
4. Execute `journalctl -b` and observe name initially set to name-early.domain and later set to name-late.domain

It looks like the solution may just be to run `dracut --force` after the host gets its official name in Step 2.
