### ISSUE TITLE
systemd-journal-upload.service is crashing regularly

### ISSUE THREAD

**Issue by luzianscherrer** [systemd/systemd#11904]
**systemd version the issue has been seen with**
> systemd 237
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 18.04.1 LTS

**Unexpected behaviour you saw**
 > systemd-journal-upload.service is crashing regularly (about once every other day)

How can I find out the reason for those crashes in order to submit a proper bug report?

**Comment by poettering** [comment]
We only track issues in the two most current upstream systemd versions here, which is 240 and 241 currently. For older stuff please report this to your downstream distro instead, i.e. on Ubuntu, they'll help you. Ubuntu has a crash reporting tool (apport iirc) which will also help you submitting crashdumps to launchpad, but you'd have to ask the Ubuntu folks about it, as it is not an upstream systemd tool. Thank you for understanding.

**Comment by q2dg** [comment]
Maybe it's time to do a issue tracker cleanup, thus. See https://github.com/systemd/systemd/issues/2102 for instance
