### ISSUE TITLE
GPG errors with machinectl pull-raw --verify=signature

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#11913]
**systemd version the issue has been seen with**
systemd 241 (241.7-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
`machinectl pull-raw https://nspawn.org/image.raw.xz` should work as expected

**Unexpected behaviour you saw**
 `machinectl pull-raw https://nspawn.org/image.raw.xz` fails with the following error message:
```
Downloading 79B for https://nspawn.org/SHA256SUMS.
Download of https://nspawn.org/SHA256SUMS complete.
Got 18% of https://nspawn.org/image.raw.xz. 9s left at 2.2M/s.
Got 40% of https://nspawn.org/image.raw.xz. 4s left at 3.3M/s.
Got 62% of https://nspawn.org/image.raw.xz. 2s left at 3.8M/s.
Got 84% of https://nspawn.org/image.raw.xz. 950ms left at 4.2M/s.
Download of https://nspawn.org/image.raw.xz complete.
SHA256 checksum of https://nspawn.org/image.raw.xz is valid.
gpg: Signature made Wed 06 Mar 2019 11:26:22 PM CET
gpg:                using RSA key A232A512E7D0BA83
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search failed: Invalid packet
gpg: Can't check signature: No public key
DOWNLOAD INVALID: Signature verification failed.
```

**Steps to reproduce the problem**
Import the GPG key: `575DE88794A45D84456D8897A232A512E7D0BA83`
Try `machinectl pull-raw https://nspawn.org/image.raw.xz` 

I have generated the image via `mkosi` with the following default file:
```
[Distribution]
Distribution=ubuntu
Release=bionic

[Output]
Format=raw_gpt
Bootable=no
Hostname=bionic
```

and the following mkosi line:
`/usr/bin/mkosi  --sign --key E7D0BA83 --xz --default bionic.default -O /usr/share/nginx/html/nspawn.org/public/`

**Comment by shibumi** [comment]
The public key is imported on my system:
```
❯ gpg --list-keys
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2021-03-05
/root/.gnupg/pubring.kbx
------------------------
pub   rsa4096 2019-03-06 [SC] [expires: 2021-03-05]
      575DE88794A45D84456D8897A232A512E7D0BA83
uid           [ultimate] Christian Rebischke (nspawn.org masterkey) <nspawn@nspawn.org>
sub   rsa4096 2019-03-06 [E] [expires: 2021-03-05]

```

**Comment by shibumi** [comment]
Ok I think I see my issue here.. I need to import the GPG key into:
```
he public key for this verification step needs to be available in /usr/lib/systemd/import-pubring.gpg or /etc/systemd/import-pubring.gpg.
```

**Comment by shibumi** [comment]
Ok, works as expected when I place the pubring on the right position. Sorry for the noise.

**Comment by q2dg** [comment]
What awesome surprise is nspawn.org !!!! Great great great idea!!!!!
