### ISSUE TITLE
how to test tmpfiles.d configuration

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#11914]
This is related to #8818, "systemd-tmpfiles should provide way to dump current tmpfiles configuration".

I have a configuration like this:

    $ cat .config/user-tmpfiles.d/screen.conf
    # does this do anything?
    # https://unix.stackexchange.com/questions/219814/why-is-systemd-tmpfiles-clean-not-working
    d /tmp/uscreens 0755 frederik frederik -

However, it seems that screen sessions disappear after some time (what is the default? ten days?). It's difficult to debug because I have to wait for some number of days before I can reproduce the problem.

I would like (and it would seem natural to have) some kind of guidance in the "tmpfiles.d" manpage which explains how, after reading the lovely documentation and trying my hand at a configuration, I can get output from the system indicating whether the configuration is as I the user had intended. This would be similar to a compiler giving an error message when I have e.g. a syntax error in my code.

Maybe there is a bug in Systemd too, but before I can figure that out I need to have some way to verify my configuration. Since other users seem to be asking the same question, maybe the documentation should cover it.

Maybe, just as a suggestion, this could involve some kind of example like:

    touch -t $(date ...) /tmp/...
    sudo env SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --clean |& grep ...

in the manual page...

**Comment by poettering** [comment]
(btw, that file is cleaned up because of system-wide clean-up of /tmp I figure, i.e. /tmp is usually managed by the system tmpfiles instance)
