### ISSUE TITLE
Call the machine-id setup machinery from the nspawn --as-pid2 stub init

### ISSUE THREAD

**Issue by emanueleaina** [systemd/systemd#11925]
Booting a rootfs with an empty `/etc/machine-id` with `systemd-nspawn` results in a new value being set (randomly or by using the value of the `--uuid` flag) when running with `--boot`, but nothing special happens when using the init stub with the `--as-pid2` flag.

It would be nice if `machine_id_setup()` got called from `nspawn-stub-pid1.c` and thus `--as-pid2` would run the same machinery as `--boot` to ensure a valid `/etc/machine-id`.

To provide more context, I've hit this (ab?)using `systemd-nspawn` as a supercharged `chroot` to set up a device image and calling `bootctl install` (which requires a valid machine-id, even if it doesn't really need to match the machine-id of the installation that it is going to boot).

**Comment by poettering** [comment]
the writing of /etc/machine-id actually takes place regardless if --boot or --as-pid2 is used or neither. It's unconditionally done.

**Comment by em-** [comment]
Mh, weird, it didn't happen in my tests.

My understanding is that it is not `nspawn` itself that sets it up, but it is up to the contained PID1 (hence not working unless `--boot` is specified, as `machine_id_setup()` is called in `main.c`).

I guess I will need to check again. :) If you happen to have any pointer at hand about where it is unconditionally done I can try to backtrack why it was not happening for me.

**Comment by poettering** [comment]
true, it's not nspawn that write it to disk, it's the init system. But the stub init that --as-pid2 uses really shouldn't be a proper init system, it exists explicitly if you want no init system and still invoke programs...

What you are basically asking for is that nspawn comes with a more comprehensive, full init system, no? why not use the init system contained in the container image then?

**Comment by poettering** [comment]
Let's close this. Either use an init system that sets things up for you. Or, if you have no init system inside the image, you can just call the systemd-machine-id-setup tool, which sets things up right too. Call it from whatever script (or other program) you invoke in the container.

I don#t think we should do that in the container mgr though.

Hope that makes sense.
