### ISSUE TITLE
machinectl list output formatting

### ISSUE THREAD

**Issue by vbatts** [systemd/systemd#11923]
**systemd version the issue has been seen with**
> 238

**Used distribution**
Fedora 28

**Expected behaviour you didn't see**

`machinectl list -l` to not show ellipsed ip addresses.
`machinectl [-o json] list [-o json]` to show JSON formatted output.

**Unexpected behaviour you saw**
```shell
[root@getdown] ~# machinectl list -l
MACHINE      CLASS     SERVICE        OS     VERSION ADDRESSES
REDACTED container systemd-nspawn fedora 27      10.0.0.53...
REDACTED  container systemd-nspawn fedora 28      10.0.0.83...
REDACTED container systemd-nspawn fedora 27      10.0.0.43...
REDACTED   container systemd-nspawn fedora 27      10.0.0.18...
redis        container systemd-nspawn fedora 28      10.0.0.77...
REDACTED container systemd-nspawn fedora 28      -

6 machines listed.
[root@getdown] ~# machinectl list -o json
MACHINE      CLASS     SERVICE        OS     VERSION ADDRESSES
REDACTED container systemd-nspawn fedora 27      10.0.0.53...
REDACTED  container systemd-nspawn fedora 28      10.0.0.83...
REDACTED container systemd-nspawn fedora 27      10.0.0.43...
REDACTED   container systemd-nspawn fedora 27      10.0.0.18...
redis        container systemd-nspawn fedora 28      10.0.0.77...
REDACTED container systemd-nspawn fedora 28      -

6 machines listed.
```

**Steps to reproduce the problem**
see above

**Comment by vbatts** [comment]
i see the note about most recent 2 releases, now. current release is 241, and this is against 238. Let me get a host to validate against newer version...

**Comment by vbatts** [comment]
testing on systemd 239 (fedora 29) it is still the case.

**Comment by poettering** [comment]
can you try with 241?

**Comment by poettering** [comment]
Actually, I am pretty sure  3bfb1010b26ccb5beefd6986e655330747dbdf79 is your fix, which is in v240:

```
git describe 3bfb1010b26ccb5beefd6986e655330747dbdf79
v239-2858-g3bfb1010b2
```
Let's close this hence. If you can reproduce this on v241, please reopen.

**Comment by vbatts** [comment]
that commit could not be it. What about `machinectl list --output=json`?

**Comment by poettering** [comment]
-o json is not about table output, but about logs output... its's a bit confusing.

**Comment by poettering** [comment]
(in particular, as we are slowly hooking tools up so that -o json actually applies to tables too, not just log output)

**Comment by vbatts** [comment]
Oh good. It is not clear that it's for logging output only, it doesn't error that it isn't applicable. And it would be surely useful to have machine parsable output for things like listing.

-------- Original Message --------
