### ISSUE TITLE
Allow to disable  mount of /run/user/$something

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11949]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806885

Dear Maintainer,

(thats mostly a bug/feature for upstream, please forward to wherever needed,
thanks).

It seems that the mounting of /run/user/$something as tmpfs can not be
disabled. Would be nice if it has an option for this.

Background / Use case: We have a login server here, the only way to
reach our internal machines.  This is pretty restricted, down to the
inability of any new mount while the system is running. Yet, logind
does try to mount the /run/user/$id on every users login (well, inital
session creation), which gets denied.

As the directory gets created before the mount (and thankfully chmod
700 too), there is no trouble - it is there for whatever wants to use
it (nothing, really), but every mount try spits out an error.

An option to turn off this behaviour would be nice.

I tried setting RuntimeDirectorySize to 0, hoping that this may be
seen as "mount of size 0 isnt useful, not doing it". Well, no, it
still tries to mount it. If I allow mounts so i can test things, the
mount doesn't appear, as a tmpfs of size 0 doesn't work out inside the
tmpfs driver.  But the mount call is still issued. As such, in the
restricted system, it spits out an error.

Not using logind would be a possibility, but it does other nice things
(killing user processes on logout, removing IPC, ...), so we would
like to keep it.

**Comment by kirbyfan64** [comment]
Try `systemctl mask user-runtime-dir@`.

**Comment by mbiebl** [comment]
Good point, @kirbyfan64 
Although overriding `user-runtime-dir@` and replacing the `ExecStart` with a simple `mkdir + chown` is probably a better idea.

**Comment by poettering** [comment]
(Note that prohibiting u-r-d@.s to do its works isn't really helping your security. We mount the per-user tmpfs there, because we want to enforce per-user quota for the directory. If you turn that off then users can fuck up other users and the system because they can allocate as much as they want from /run, thus DoSing everybody else.)

**Comment by mbiebl** [comment]
We made the original bug reporter aware about that. He does use a seperate /run/user tmpfs, so at least the system angle is not an issue anymore.
