### ISSUE TITLE
machinectl pull-tar triggers lsetxattr errors

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#11940]
**systemd version the issue has been seen with**
> systemd 241 (241.7-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
Host: Arch Linux
Build Host for the Container: Fedora 29
**Expected behaviour you didn't see**

`machinectl pull-tar` should not show lsetxattr warnings/errors.

**Unexpected behaviour you saw**

`machinectl pull-tar` triggers `lsetxattr errors` on systems without selinux, when the container was build on a system with enabled selinux.

**Steps to reproduce the problem**

build a container via `mkosi` on a selinux enabled system and try to pull it on a system without selinux.

Suggestion: Implement a way to hide such errors/warnings

**Example output**
```
[..]
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Mexico': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Brazil': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/SystemV': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Chile': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Indian': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Canada': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Pacific': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Etc': Operation not permitted
tar: setxattrat: Cannot set 'security.selinux' extended attribute for file './usr/share/zoneinfo/right/Europe': Operation not permitted
[..]
```

**Comment by yuwata** [comment]
Could you test #11955?
