### ISSUE TITLE
timedated SetNtp: wrong PropertiesChanged value on disabling NTP

### ISSUE THREAD

**Issue by marusak** [systemd/systemd#11944]
**systemd version the issue has been seen with**
241-1

This seems like regression that was discussed in #9672
Possibly related to #11424

**Used distribution**
Debian

**Expected behaviour you didn't see**
When **disabling** NTP `PropertiesChanged` signal for `NTP` should be `false`.

**Unexpected behaviour you saw**
When disabling NTP `PropertiesChanged` signal for `NTP` is `true`.  When enabling is correctly `true`.

**Steps to reproduce the problem**

    $ busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
    b true

    $ busctl call org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 SetNTP bb false false

And listening with `dbus-monitor --system "type='signal', member='PropertiesChanged', path='/org/freedesktop/timedate1'"` outputs:

    signal time=1552111878.797211 sender=:1.47 -> destination=(null destination) serial=12 path=/org/freedesktop/timedate1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
    string "org.freedesktop.timedate1"
    array [
       dict entry(
          string "NTP"
          variant             boolean true
       )
    ]
    array [
    ]

**Comment by martinpitt** [comment]
Since this broke twice now, I'll take it on me to write a systemd regression test for this, so that we notice regressions right away.

**Comment by yuwata** [comment]
Ugh,,, I will take a look this tomorrow...

**Comment by martinpitt** [comment]
I [created a test](https://salsa.debian.org/systemd-team/systemd/commit/1626b6c5ba993) for this which reproduces this regression. On systemd 239 this works fine (tested in LXC and QEMU), with 241 it fails as described:
```
re-disable NTP
FAIL: 'boolean false' not found in:
signal time=1552218663.646040 sender=org.freedesktop.DBus -> destination=:1.50 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.50"
signal time=1552218663.646106 sender=org.freedesktop.DBus -> destination=:1.50 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.50"
signal time=1552218663.765482 sender=:1.19 -> destination=(null destination) serial=99 path=/org/freedesktop/timedate1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.freedesktop.timedate1"
   array [
      dict entry(
         string "NTP"
         variant             boolean true
      )
   ]
   array [
   ]
```

I won't commit that to Debian master yet, to avoid turning all PRs red.

**Comment by yuwata** [comment]
@martinpitt If possible could you enable the test in #11951?

**Comment by martinpitt** [comment]
I started a bisect run (with the test that's now trivial), and it found that  commit b4356b5720ae0 from PR #11420 indeed is the culprit. This makes sense, as that introduced the assumption that an unfinished  operation means that NTP is enabled (but the operation could also be  to disable it).  Reverting that on top of master fixes the property again.

PR #11951 also fixes this, and makes the test happy. Thank you!
