### ISSUE TITLE
cryptsetup options for performance tuning are not available in crypttab; dm-crypt not usable this way

### ISSUE THREAD

**Issue by bitclick** [systemd/systemd#11946]
on my system, multithreaded dm-crypt is way slower than singlethreaded, only 24MiB/s write speed. 
dm-crypt and cryptsetup have documented parameters for this case (since 2015 i believe)

>   --perf-same_cpu_crypt
>   --perf-submit_from_crypt_cpus

see 
https://gitlab.com/cryptsetup/cryptsetup/commit/4f7b4136386aff41a1608727d0ca362e5589149d

with these parameters i can setup dm-crypt for full speed on my system 
there seems to be no way to use these with systemd crypttab

**systemd version the issue has been seen with**
current  master  ( i looked in the source) in cryptsetup-generator.c and cryptsetup.c
today last commit
https://github.com/systemd/systemd/commit/c20db3887569e0c0d9c0e2845c5286e7edf0133a

and ubuntu 18.04 systemd v 237  (i have it running on my system)

**Used distribution**

ubuntu 18.04 amd64

**Expected behaviour you didn't see**
be able to specify dm-crypt parameters in crypttab, alongside with "discard" parameter

> same_cpu_crypt
> submit_from_crypt_cpus

systemd would pass these to dm-crypt

**Unexpected behaviour you saw**
parameters get ignored in boot (warning in syslog)

**Steps to reproduce the problem**
setup crypttab this way (with valid uuid)

> $ sudo cat /etc/crypttab 
> sda5_crypt UUID=594f01cd-bfe1-400b-8af3-f770af9317b2 none luks,discard,same_cpu_crypt,submit_from_crypt_cpus

see warnings in syslog and check dm-crypt with command

> dmsetup table 

the parameters will not be listed, as they should next to "allow_discards"

**Comment by yuwata** [comment]
I've created #11957. If possible, please test #11957.
