### ISSUE TITLE
machinectl clean: Total freed exclusive disk space (null)

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#11941]
**systemd version the issue has been seen with**
> systemd 241 (241.7-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `machinectl clean` should specify the size of the freed disk space.

**Unexpected behaviour you saw**
 > `machinectl clean` sets `(null)` for the freed disk space:
```
Removed image '.tar-https:\x2f\x2fnspawn\x2eorg\x2fstorage\x2fdebian\x2fstretch\x2ftar\x2fstretch\x2etar\x2exz.\x225c82e563-2f75538\x22'. Freed exclusive disk space: (null)
Removed 1 images in total. Total freed exclusive disk space (null).
```

**Steps to reproduce the problem**

`machinectl clean`

**Comment by shibumi** [comment]
Ok I think I can better reproduce this issue:
1. pull an image
2. remove the image via `machinectl remove <image name>
3. clean the disk via `machinectl clean`

Step 3 will trigger the bug. When I change the order of step 2 and step 3 into something like this:
1. pull an image
2. clean the disk via `machinectl clean`
3. remove the image via `machinectl remove <image name>

It will work as expected and it will show the correct size.

**Comment by yuwata** [comment]
Could you test #11954?
