### ISSUE TITLE
unexpected interaction between `systemctl restart --user dbus.service` and GDK_DPI_SCALE

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#11959]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**, **Unexpected behaviour you saw**

I don't know what `systemctl restart --user dbus.service` does exactly, although I was trying to use it to debug a problem with [Boomaga](https://github.com/Boomaga/boomaga). When I ran this command, I found that some of my GTK UIs were 1.5x bigger. I didn't expect it to have this result at all.

The problem is obviously related to the fact that I have "export GDK_DPI_SCALE=1.5" in `~/.zprofile`. But it is unclear that I did something wrong here, or that I should have known this would affect D-bus. After the restart command, this setting is being picked up twice, i.e. the magnification is 2.25x the default, while my usual setting is 1.5x the default.

I'm confused that `systemctl restart` would pick up environment variables from the calling environment; I'm also confused that GDK_DPI_SCALE would be read by some machinery inside Systemd in such a way that it causes the scaling factor to be applied twice.

**Steps to reproduce the problem**

    # configure shell profile so that:
    $ echo $GDK_DPI_SCALE
    1.5
    # then:
    $ evince doc.pdf
    $ systemctl restart --user dbus.service
    # GUI appears huge
    $ evince doc.pdf

You'd think this would fix it but it doesn't:

    $ GDK_DPI_SCALE=1  systemctl restart --user dbus.service
    $ evince doc.pdf # still huge
    $ GDK_DPI_SCALE= systemctl restart --user dbus.service
    $ evince doc.pdf # still huge
    $ GDK_DPI_SCALE=0.75 systemctl restart --user dbus.service
    $ evince doc.pdf # still huge

I have to fix it by restarting Xorg, or setting GDK_DPI_SCALE="" in my shell profile or in the shells where I run evince from.

Firefox is also affected, Gedit, etc.

**Comment by poettering** [comment]
some gnome component (as well as some X11 session init scripts) uploads its env block to systemd iirc, thus propagating its env vars to every process of your user, that is started afterwards...

Please contact GNOME for help about this. There's nothing systemd can do about that really...

**Comment by archenemies** [comment]
I don't know if it's as simple as you make it sound. For the value "1.5" to get multiplied by itself, would mean that it is entering as both an environment variable and as some other configuration parameter picked up from the same environment variable. Either way that's a Gnome problem, though, agreed...

However I'm unclear as why `systemctl` is looking at its environment in the first place. Surely in the interests of reproducibility, services should be completely specified by unit configuration and not pick up anything from the environment. I think this would be particularly true when they are restarted. The very meaning of the word "restart" would seem to suggest a perfect repetition of something that was done before.

I submitted this to Gnome Gitlab GTK, hope that was what you wanted:

https://gitlab.gnome.org/tmiasko/gtk/issues/1

**Comment by archenemies** [comment]
And thanks for the quick reply.
