### ISSUE TITLE
Alias drop-in is always flagged as changed on disk

### ISSUE THREAD

**Issue by qb-syn** [systemd/systemd#11972]
**systemd version the issue has been seen with**
> systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian/sid

**Expected behaviour you didn't see**
 > When creating drop-in in the name of an aliases services, systemctl will complain that the configuration on disk has changed after the daemon has been reloaded.

**Unexpected behaviour you saw**
 > Either prohib definition of drop-in for service alias or remove the warning. In the former case, probably add information that this is ok to do so on `systemd.unit(5)`.

**Steps to reproduce the problem**
1. Create a service file, I do experiment the problem with Debian/sid provided `ssh.service` that define an alias for that service to be `sshd.service`:

```ini
# /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
Documentation=man:sshd(8) man:sshd_config(5)
After=network.target auditd.service
ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

[Service]
EnvironmentFile=-/etc/default/ssh
ExecStartPre=/usr/sbin/sshd -t
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/usr/sbin/sshd -t
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
Alias=sshd.service
```

2. Create any drop-in in the name of the aliases service, in that case it could be `/etc/systemd/system/sshd.service.d/user.conf`:
```ini
[Service]
User=daemon
```

3. Reload the systemd "daemon" and check that everything works from journalctl?:

```
# systemctl daemon-reload
```
```
systemd[1]: Reloading.
```

At that point probing the status of `ssh.service` will return no error, but `sshd.service` will issue a warning that the on-disk configuration changed:

```
#  systemctl status ssh.service 
● ssh.service - OpenBSD Secure Shell server
```

```
# systemctl status sshd.service
Warning: The unit file, source configuration file or drop-ins of ssh.service changed on disk. Run 'systemctl daemon-reload' to reload un
```

Note that when probing for `sshd.service` one will get the above warning. If, after, I probe the `ssh.service` again the warning will appear for that unit too:
```
# systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
```

```
# systemctl status sshd
Warning: The unit file, source configuration file or drop-ins of ssh.service changed on disk. Run 'systemctl daemon-reload' to reload un
```

```
# systemctl status ssh
Warning: The unit file, source configuration file or drop-ins of ssh.service changed on disk. Run 'systemctl daemon-reload' to reload un

● ssh.service - OpenBSD Secure Shell server
```

Finally I do understand that creating a drop-in for a service alias is not probably a good thing to do but this is what I found on a production system and I believe some clarification might be helpful.

I also do understand that this is just a warning and that in the end the service is started and nothing is really impacted.

Thanks,

Q.

**Comment by keszybz** [comment]
Let's reassign this to v243. I'm working on a patch, but right now this is turning a rewrite of most of the unit file finding code and I don't think I'll finish it today. So I think it's better to postpone this for now, current state is not bad enough to delay a release.

**Comment by ClydeByrdIII** [comment]
@keszybz I'm seeing similar behavior in drop-in files when setting SourcePath in v241. Before making a separate issue. I just wanted to know if you think this is the same underlying issue? Easy repro is to set the SourcePath in any drop-in and do a systemctl daemon-reload.

**Comment by keszybz** [comment]
> @keszybz I'm seeing similar behavior in drop-in files when setting SourcePath in v241. Before making a separate issue with proper details. I just wanted to know if you think this is the same underlying issue? Easy repro is to set the SourcePath in any drop-in and do a systemctl daemon-reload.

Not sure. Please test with v243 after it's released.
