### ISSUE TITLE
Poor error message from journalctl -u when specified unit has no logs

### ISSUE THREAD

**Issue by pwaller** [systemd/systemd#1200]
I have been puzzled by this behaviour a few times.

In the fog of war, I've had problems with [various](https://github.com/coreos/bugs/issues/322) problems with [seemingly spurious](https://github.com/coreos/bugs/issues/334) errors from `journalctl` - and it has been very hard to identify that:

```
$ journalctl -u foo
Failed to get journal fields: Cannot assign requested address
-- Logs begin at Fri 2015-09-04 16:49:22 UTC, end at Tue 2015-09-08 10:57:18 UTC. --
```

Is simply `journalctl` legitimately telling me that `foo` doesn't have any logs.

`Failed to get journal fields: Cannot assign requested address` sounds scary and has no useful search results. (It also sounds like a bizarre syscall failure, but you won't find `EADDRNOTAVAIL` with `strace` - it's coming from [somewhere like this](https://github.com/systemd/systemd/blob/a7adabc96ef9c34b6e05404169158c8eee6dce76/src/journal/sd-journal.c#L2009-L2014))

The problem is worsened because I expected `foo` in this case to have logs, but the logs had been rotated out - to my inexperienced surprise. So I was left (erroneously) feeling that `journalctl -u` was buggy and crashing for no reason - and worse, not letting me view my logs!

Searching the internet for the error message [lead](https://duckduckgo.com/?q=%22Failed+to+get+journal+fields%3A+Cannot+assign+requested+address%22) me to [nowhere](https://encrypted.google.com/search?hl=en&q=%22Failed%20to%20get%20journal%20fields%3A%20Cannot%20assign%20requested%20address%22) useful.

**Comment by poettering** [comment]
which systemd version are you runninng?

systemd versions >= 223 will show "-- No entries --" instead. Are you running at least 223?

**Comment by pwaller** [comment]
I'm running systemd 220, which could explain this. Thanks for the response and apologies for the noise.
