### ISSUE TITLE
\r in path confuses mount units

### ISSUE THREAD

**Issue by zyga** [systemd/systemd#12018]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > ubuntu 18.10

**Expected behaviour you didn't see**
 > systems should have parsed the mount directory as `/tmp/foo\rbar`

**Unexpected behaviour you saw**
 > systemd apparently parsed `mountinfo` data as `/tmp/foo`, representing inexistent mount point.

**Steps to reproduce the problem**
```
mkdir "$(echo -e foo\\rbar)"
sudo mount -t tmpfs tmpfs foo^Mbar/
systemctl list-units | grep tmp-foo.mount
```

**Comment by poettering** [comment]
hmm, this sounds like an attempt to play games with systemd. we filter some chars early on, because things like ^M or ^H are generally just a way to hide things in the output

**Comment by zyga** [comment]
While I agree no sane administrator would do this I think systemd should not be tricked by that. The mountinfo parser needs to consider only `' '` as field separator.

**Comment by poettering** [comment]
there might be a bug in systemd, but in general I think it would be fine if systemd would simply ignore such mounts. i.e. so that the mounts can be established in the kernel if you bypass systemd, but systemd would totally ignore their existance...

**Comment by keszybz** [comment]
Dunno, should we just escape this and continue? We have a very generic escape mechanism to be able to include anything in unit names.

**Comment by zyga** [comment]
@poettering I think ignoring it entirely is probably impossible since you need to know the entire chain of mounts that may happen. Let's say that `/tmp/foo\rbar` is represented, either in fstab or as runtime-inferred mount unit. A mount unit under /tmp/foo\rbar/froz.mount` (or a socket or anything that has filesystem presence and systemd understands it) should be put on the right dependency chain.

While silly I think it is a kernel feature that anything apart from `/` and NUL is a valid path name.

**Comment by poettering** [comment]
> @poettering I think ignoring it entirely is probably impossible since you need to know the entire chain of mounts that may happen. Let's say that `/tmp/foo\rbar` is represented, either in fstab or as runtime-inferred mount unit. A mount unit under /tmp/foo\rbar/froz.mount` (or a socket or anything that has filesystem presence and systemd understands it) should be put on the right dependency chain.

Well, if people do stupid stuff they get to keep the pieces. If I'd see an \r embedded in a mount I am very sure it's more likely an attack attempt than a real-life valid usecase. In an ideal world the kernel would already refuse this. Unfortunately it doesn't, but I think it's fine to refuse working with such stuff in systemd still. Or to say this differently: this will trigger bugs sooner or later, and create vulnerabilities. If it's not systemd which breaks if you have mounts like this then something else will break. If we break sensibly, willfully and early then I think that's a lot better than breaking accidentally and thus becoming vulnerable.

Hence I still think it's bettre to filter these, maybe make issues like this discoverable and then refusing them (and yes, possibly breaking operation of some setups that really really want to use it) then to accept them and pretend nothing was wrong.

I mean, let's not forget that any tool naively prints out file names (and I think we have plenty of those already in the standard tool set, for example I am sure 'find' doesn't escape filenames it discovers when printing them?) will output `/tmp/foo\rbar` as `barp/foo`, and that's highly confusing to the user and likely results in security issues.

Anyway, I not saying there wasn't something to improve in systemd here, but I am inclined to say that the option of "refuse and warn" is preferable over "just make this work as if it was all totally good and in no way questionnable".

**Comment by zyga** [comment]
I think filtering out _and_ refusing to work would be okay. I agree this is something that would come out via a system attack, not from a opinionated system administrator.

**Comment by jdebp** [comment]
systemd's `mountinfo` parsing is incorrect, here.

[It uses](https://github.com/systemd/systemd/blob/49bd196d693efe0acfc8d56c4e3d8f7ba9f91b5d/src/shared/mount-util.c#L55) [`fscanf()` in lots](https://github.com/systemd/systemd/blob/b82f71c7ff3f21fd07037c085c824ae78cf7442e/src/udev/cdrom_id/cdrom_id.c#L100) [of ad-hoc](https://github.com/systemd/systemd/blob/36dbf9717030d0a9d69df2e6180284834fa8a851/src/mount/mount-tool.c#L734) [parsers](https://github.com/systemd/systemd/blob/49bd196d693efe0acfc8d56c4e3d8f7ba9f91b5d/src/shared/mount-util.c#L162) to separate fields in the table.  But `fscanf()` will split fields on whitespace, and what counts as whitespace is both locale-specific and *different to* the actual file format (even in the C locale).  The Linux kernel, the  GNU C library, and other utilities are quite specific that only SPC and TAB are field separator characters; whereas `fscanf()` will *also incorrectly* split fields on VT and CR.

* GNU C library [using `__strsep()` with TAB and SPC](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/misc/mntent_r.c#L159)  and [decoding field contents](https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/misc/mntent_r.c#L67)
* [netdata specifying only TAB and SPC as the the separators](https://github.com/netdata/netdata/blob/8fbf817ef83b3524b15f908251909d9d6feb5532/collectors/proc.plugin/proc_self_mountinfo.c#L182) in the call to `procfile_open()`
* [Linux only encoding *some* whitespace characters](https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/fs/proc_namespace.c#L146) in the first place
* [source of `fstab-decode`](https://sources.debian.org/src/sysvinit/2.93-8/src/fstab-decode.c/#L42)

Whether or not CR is a good idea in a mount point name, one should *parse the data file correctly*.

**Comment by keszybz** [comment]
OK, let's reject such mount names as @poettering says.

To parse /proc/self/mountinfo, we use libmount. So this should be fixed in libmount first and foremost. Then there are the cases that @jdebp listed. I think we should convert all /proc/self/mountinfo parsing to libmount, so we don't have multiple differing implementations.

I'll open a bug against util-linux.

**Comment by keszybz** [comment]
https://lists.gnu.org/archive/html/bug-coreutils/2019-04/msg00005.html

I see one bright side to all of this: under zsh, tab completion gives me a beautiful commandline:
![Screenshot from 2019-04-04 10-23-04](https://user-images.githubusercontent.com/349618/55540658-b4984400-56c3-11e9-9e8e-532b5238e8a7.png)

**Comment by karelzak** [comment]
Nice. The problem will be fixed in util-linux v2.33.2.

**Comment by karelzak** [comment]
Fixed in the util-linux master and stable/v2.33 branches. The ugly mountpoint also added to the libmount regression tests. Thanks for your report! ;-)

**Comment by poettering** [comment]
Given this was fixed in util-linux a long time ago I guess we ca nclose this here now.

**Comment by keszybz** [comment]
> [It uses](https://github.com/systemd/systemd/blob/49bd196d693efe0acfc8d56c4e3d8f7ba9f91b5d/src/shared/mount-util.c#L55) [`fscanf()` in lots](https://github.com/systemd/systemd/blob/b82f71c7ff3f21fd07037c085c824ae78cf7442e/src/udev/cdrom_id/cdrom_id.c#L100) [of ad-hoc](https://github.com/systemd/systemd/blob/36dbf9717030d0a9d69df2e6180284834fa8a851/src/mount/mount-tool.c#L734) [parsers](https://github.com/systemd/systemd/blob/49bd196d693efe0acfc8d56c4e3d8f7ba9f91b5d/src/shared/mount-util.c#L162)

mount-util.c: converted to libmount
cdrom_id: removed in 14cd12b3d50f21cb9be7e27785142c6c321fac39
mount-tool.c: converted to libmount
mount-util.c: converted to libmount

Seems all fixed.
