### ISSUE TITLE
 test-stat-util fails with SIGABRT when /dev/random is bind-mounted from /dev/urandom

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#12023]
**systemd version the issue has been seen with**

v241

Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923674

If /dev/random is bind-mounted from /dev/urandom, test-stat-util fails in
https://github.com/systemd/systemd/blob/master/src/test/test-stat-util.c#L148

Quoting from the bug report:
```
The reason I would still consider this as a bug (with whatever severity
you like) is that symlinking /dev/random to /dev/urandom is a common
workaround for lack of entropy, which in turn has traditionally been a
common problem for anybody who tries to build a lot of packages in a row.

BTW: After building 28500 source packages in buster, I only found
another package which failed for this very reason:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907191
```

While I find this practice rather questionable, dropping the line
`test_device_path_make_canonical_one("/dev/random");` would probably not hurt a lot, since `device_path_make_canonical` is also checked with other device nodes.

**Comment by poettering** [comment]
Humm. I wished people wouldn't steal our time with bogus nonsense like this. Can't you tell the reporter, to simply not do that? I am not sure we have to support every crazy setup people want to use... Or if they want to bind mount mount stuff like that, they should also fix /dev/char/* to match it...

**Comment by mbiebl** [comment]
@poettering I basically already told that to the (downstream) bug reporter (i.e. don't do that):
```
I confirm that dropping the /dev/urandom line from
/etc/schroot/default/fstab makes the package to build again.

Now I fear that crypto packages with random-intensive test suites
start to FTBFS again...
```
I'll pass the info along about fixing /dev/char/*
