### ISSUE TITLE
'BindsTo=' not respected in LVM/LUKS scenario and causes failure upon and after start up with a bunch of "Unnecessary job for ... removed." messages

### ISSUE THREAD

**Issue by Alexander-Shukaev** [systemd/systemd#12031]
**systemd version the issue has been seen with**
> systemd 239
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Steps to reproduce the problem**

Acronyms used:

- P2: Partition 2;
- PV: Physical Volume;
- VG: Volume Group;
- LV: Logical Volume.

There is the following LVM/LUKS/LVM configuration:

```
HDD -> P2 -> PV -> VG -> LV -> LUKS -> PV -> VG -> {LV1, ..., LV7}
```

```
sdc                                         8:48   0 232.9G  0 disk  
├─sdc1                                      8:49   0     8G  0 part  
└─sdc2                                      8:50   0   224G  0 part  
  └─st9250315as.storage.vg-boss.lv        254:6    0   224G  0 lvm   
    └─st9250315as.storage.vg-boss.lv.luks 254:7    0   224G  0 crypt 
      ├─st9250315as.boss.vg-1.lv          254:8    0    24G  0 lvm   
      ├─st9250315as.boss.vg-2.lv          254:9    0     8G  0 lvm   
      ├─st9250315as.boss.vg-3.lv          254:10   0    24G  0 lvm   
      ├─st9250315as.boss.vg-4.lv          254:11   0    48G  0 lvm   
      ├─st9250315as.boss.vg-5.lv          254:12   0    96G  0 lvm   
      ├─st9250315as.boss.vg-6.lv          254:13   0    16G  0 lvm   
      └─st9250315as.boss.vg-7.lv          254:14   0     8G  0 lvm   
```

The idea was to create a convenience service that opens/closes (and tracks) the LUKS container (`st9250315as.storage.vg-boss.lv.luks`).  Thanks to an established naming convention and accompanying scripts which implement all that logic, the following templatized `--user` service has been successfully used:

```
luks@.service
```
```
[Unit]
Description=LUKS Configuration for '%I'
After=cryptsetup-pre.target
After=dev-mapper-%i.device
Before=cryptsetup.target
Before=umount.target
Conflicts=umount.target
DefaultDependencies=no
IgnoreOnIsolate=yes
RequiresMountsFor=/home
##
[Service]
ExecStart=/usr/bin/sudo /usr/local/lib/systemd/systemd-luks attach '%I'
ExecStop=/usr/bin/sudo /usr/local/lib/systemd/systemd-luks detach '%I'
KillMode=none
RemainAfterExit=yes
TimeoutSec=0
Type=oneshot
##
[Install]
WantedBy=default.target
```

This works well starting manually and even if `enable`d for start up given that the external device `/dev/sdc` is physically plugged in.  However, there are limitations if somebody runs first

```
systemctl --user start luks@st9250315as.storage.vg\\x2dboss.lv
```

and then

1.  manually runs

    ```
    /usr/bin/sudo /usr/local/lib/systemd/systemd-luks detach st9250315as.storage.vg-boss.lv
    ```

    the service would be left in a misleading state, i.e. `active`, while practically it should not be;

2.  somebody does something that a parent LVM container (`st9250315as.storage.vg-boss.lv`) is gone (whatever that action is), the service would be left in a misleading state, i.e. `active`, while practically it should not be;
3.  somebody physically plugs out `/dev/sdc`, the service would be left in a misleading state, i.e. `active`, while practically it should not be.

So I decided to improve the service and came up with the following version:

```
luks@.service
```
```
[Unit]
Description=LUKS Configuration for '%I'
After=cryptsetup-pre.target
After=dev-mapper-%i.device
Before=cryptsetup.target
Before=umount.target
Before=dev-mapper-%i.luks.mount
BindsTo=dev-mapper-%i.device
BindsTo=dev-mapper-%i.luks.device
Conflicts=umount.target
DefaultDependencies=no
IgnoreOnIsolate=yes
RequiresMountsFor=/home
##
[Service]
ExecStart=/usr/bin/sudo /usr/local/lib/systemd/systemd-luks attach '%I'
ExecStop=/usr/bin/sudo /usr/local/lib/systemd/systemd-luks detach '%I'
KillMode=none
RemainAfterExit=yes
TimeoutSec=0
Type=oneshot
##
[Install]
RequiredBy=dev-mapper-%i.luks.device
WantedBy=default.target
```

Now there are multiple new problems with this implementation, which I don't understand, while the only limitation 1 out of 3 (from above) is solved.

First of all, `enable` now results in some strange messages on start up:

```
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for /dev/dm-6 was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for /sys/devices/virtual/block/dm-6 was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for /dev/disk/by-id/dm-name-st9250315as.storage.vg-boss.lv was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:41:17 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:42:47 g75vw systemd[1101]: dev-mapper-st9250315as.storage.vg\x2dboss.lv.device: Job dev-mapper-st9250315as.storage.vg\x2dboss.lv.device/start timed out.
Mar 18 01:42:47 g75vw systemd[1101]: Timed out waiting for device /dev/mapper/st9250315as.storage.vg-boss.lv.
Mar 18 01:42:47 g75vw systemd[1101]: Dependency failed for LUKS Configuration for 'st9250315as.storage.vg-boss.lv'.
Mar 18 01:42:47 g75vw systemd[1101]: luks@st9250315as.storage.vg\x2dboss.lv.service: Job luks@st9250315as.storage.vg\x2dboss.lv.service/start failed with result 'dependency'.
```

and obviously the LUKS volume is not open after the start up even if `/dev/sdc` is physically plugged in.  Trying to manually run

```
systemctl --user start luks@st9250315as.storage.vg\\x2dboss.lv
```

results in similar messages and fails:

```
Mar 18 01:45:01 g75vw systemd[1101]: Unnecessary job for dev-mapper-st9250315as.storage.vg\x2dboss.lv.luks.device was removed.
Mar 18 01:45:32 g75vw systemd[1101]: dev-mapper-st9250315as.storage.vg\x2dboss.lv.device: Job dev-mapper-st9250315as.storage.vg\x2dboss.lv.device/start timed out.
Mar 18 01:45:32 g75vw systemd[1101]: Timed out waiting for device /dev/mapper/st9250315as.storage.vg-boss.lv.
Mar 18 01:45:32 g75vw xfce4-panel[1284]: A dependency job for luks@st9250315as.storage.vg\x2dboss.lv.service failed. See 'journalctl -xe' for details.
Mar 18 01:45:32 g75vw systemd[1101]: Dependency failed for LUKS Configuration for 'st9250315as.storage.vg-boss.lv'.
Mar 18 01:45:32 g75vw xfce4-panel[1284]: A dependency job for luks@st9250315as.storage.vg\x2dboss.lv.service failed. See 'journalctl -xe' for details.
Mar 18 01:45:32 g75vw systemd[1101]: luks@st9250315as.storage.vg\x2dboss.lv.service: Job luks@st9250315as.storage.vg\x2dboss.lv.service/start failed with result 'dependency'.
Mar 18 01:45:32 g75vw systemd[1101]: dev-mapper-st9250315as.storage.vg\x2dboss.lv.device: Job dev-mapper-st9250315as.storage.vg\x2dboss.lv.device/start failed with result 'timeout'.
```

__Why__ ❓

OK, fine, if we start with this new version of `luks@.service` from the beginning, it appears to be completely broken.  But, surprise, when I implemented this, I obviously started up with the original version, which was fine, and only later turned it into a new version.  So let's go over that scenario.  Of course I ran `systemctl --user daemon-reload` for `systemd` to absorb the new changes to `luks@.service`.  I then did

```
systemctl --user start luks@st9250315as.storage.vg\\x2dboss.lv
```

and in this case it worked?!  __Why__ ❓  The LUKS container was open and the service became `active`.  That was good and even thanks to `BindsTo=dev-mapper-%i.luks.device`, the limitation 1 out of 3 was gone, i.e. manually running

```
/usr/bin/sudo /usr/local/lib/systemd/systemd-luks detach st9250315as.storage.vg-boss.lv
```

did trigger stopping of the service and deactivated it.  However, physically unplugging `/dev/sdc`, which includes limitations 2 and 3, did not trigger stopping of the service regardless of `BindsTo=dev-mapper-%i.device`.  __Why__ ❓

**Comment by arvidjaar** [comment]
This post really belongs to mailing list.

> physically unplugging `/dev/sdc`, which includes limitations 2 and 3, did not trigger stopping of the service regardless of `BindsTo=dev-mapper-%i.device`

Because `/dev/mapper/%i` continues to be active so nothing triggers this `BindsTo` condition. And it is not systemd issue, you need to discuss this behavior with LVM folks.

**Comment by Alexander-Shukaev** [comment]
> This post really belongs to mailing list.

There are 3 issues summarized which to me look more like bugs, so in my opinion it belongs here.  Furthermore, LVM is just an example, I'm almost sure there will be the same issue with other container-like devices.

> Because `/dev/mapper/%i` continues to be active so nothing triggers this `BindsTo` condition. And it is not systemd issue, you need to discuss this behavior with LVM folks.

No, it's not active, if you unplug `/dev/sdc`, it's gone (see `lsblk`).  Tracking `/dev/*` to propagate `BindsTo` conditions is not a responsibility of LVM but of `systemd`.

**Comment by arvidjaar** [comment]
> No, it's not active, if you unplug `/dev/sdc`, it's gone (see `lsblk`). 

You did not include any lsblk output. And I tested what happens when I unplug device with active VG and LV on top and I see that `/dev/mapper/VG-LV` remains.

**Comment by Alexander-Shukaev** [comment]
@arvidjaar, you are right.  I checked on my system and I see the same issue, namely stale symbolic links in `/dev/mapper`.  Any solution or workaround to deal with those is welcome.  My other two questions/sub-issues are still valid.  In a particular, I question `Unnecessary job for ...`, how to avoid it, and its consequences.

**Comment by poettering** [comment]
We have no clue about LVM here. Can you provide a minimal reproducer of any issues you found, without LVM in the mix? Anything LVM specific needs to be discussed with LVM people, they install their own rules, and we have no idea.

**Comment by poettering** [comment]
Closing due to lack of response. Given it's an LVM issue, not really an issue on our side anywa.y
