### ISSUE TITLE
journald crash with SIGBUS

### ISSUE THREAD

**Issue by cmtm** [systemd/systemd#12042]
**systemd version the issue has been seen with**
> 239
Bug still exists in ToT though

**Used distribution**
 > custom

**Expected behaviour you didn't see**
 > When moving clock forward, journald should not crash

**Unexpected behaviour you saw**
 > journald crashes with SIGBUS when moving clock forward

**Steps to reproduce the problem**

journald gets SIGBUS on boot after the clock is set.

**Stack trace**
```
Thread 0: CRASHED [SIGBUS / 0x00000000 @ 0x00000000 ]

(libsystemd-shared-239.so -journal-file.c:114)   journal_file_set_offline_internal
(libsystemd-shared-239.so -journal-file.c:137)   journal_file_set_offline_thread
(libpthread-2.27.so -pthread_create.c:463)       start_thread
(libc-2.27.so+ 0x0009fa6b)                       clone

Thread 1

(libc-2.27.so+ 0x000172d6)                       __libc_do_syscall
(libc-2.27.so -ftruncate64.c:30)                 __ftruncate64
(libsystemd-shared-239.so -fs-util.c:1150)       unlinkat_deallocate
(libsystemd-shared-239.so -journal-vacuum.c:307) journal_directory_vacuum
(systemd-journald -journald-server.c:529)        do_vacuum
(systemd-journald -journald-server.c:546)        dispatch_message_real
(systemd-journald -journald-syslog.c:383)        server_process_syslog_message
(systemd-journald -journald-server.c:1151)       server_process_datagram
(libsystemd-shared-239.so -sd-event.c:3103)      source_dispatch
(libsystemd-shared-239.so -sd-event.c)           sd_event_dispatch
(libsystemd-shared-239.so -sd-event.c:3573)      sd_event_run
(systemd-journald -journald.c:92)                main
(libc-2.27.so -libc-start.c:308)                 __libc_start_main
(systemd-journald+ 0x00003b63)                   _start
(systemd-journald -elf-init.c:87)                __libc_csu_init
(?)
(systemd-journald+ 0x00003b2f)                   _init
```
**What's happening**

This occurred on a file system without support for `fallocate FALLOC_FL_PUNCH_HOLE`. The system doesn't have a hardware clock, so the system time starts at 2017-01-01 and is set later in boot when the time can be fetched over the network. When the time moves forward, the journal rotates the file since it's appears to be more than a month old. The journal-offline thread is spawned to fsync the journal file. The rotation also triggers a vacuum because the disk size fills up. Due to the incorrect clock value at boot, the rotated file is deemed to be the oldest. The main journald thread tries to use `fallocate FALLOC_FL_PUNCH_HOLE`, but since this isn't supported on the file system, falls back to truncating it. The journal-offline thread then accesses a memory mapped area of the file (the `state` in the file header) triggering a SIGBUS since the file was truncated and the access is now beyond the end of it.

The journal-offline thread has SIGBUS blocked when it occurs. If SIGBUS is generated while it's blocked, the result is undefined in Linux. On all the systems I tested, it just killed the whole process with SIGBUS (as if executing the default handler).

**How we can fix this**
The problem stems from journal-offline accessing a memory mapped file when it has SIGBUS blocked. I see a couple of possible solutions. For one, we could just unblock SIGBUS in the journal-offline thread. It looks like the sigbus handler is thread-safe. This won't change behavior when SIGBUS is sent to the journal with `kill, sigqueue, or raise`, even though the signal will be delivered to one of two threads instead of always going to the main one.

If we aren't comfortable with having threads unblocked on multiple threads (which I think is a reasonable concern), we can have the file access occur on the main thread, and only have the fsync occur on the journal-offline thread. journal-offline currently calls fsync, then sets the `state` in the header, and then fsyncs again. We could have it fsync and then exit. The main thread would then set the header variable upon the thread join event occurring, and the main thread could also do the last fsync since it's only one word and I wouldn't expect it to take much time.

**Comment by vcaputo** [comment]
Excellent bug report, thanks!

At a glance it seems like the fsync thread should just have SIGBUS enabled.
