### ISSUE TITLE
systemd-networkd should call IFF_UP on dummy interfaces

### ISSUE THREAD

**Issue by chr4** [systemd/systemd#12051]
**Is your feature request related to a problem? Please describe.**

When creating a `dummy` interface in `systemd-networkd`, e.g. by creating `/lib/systemd/network/90-dummy.netdev` with this content:

```
[NetDev]
Name=dummy0
Kind=dummy
```

The interface status is `DOWN`

```
`: dmmy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 5a:b0:9e:dd:2a:cf brd ff:ff:ff:ff:ff:ff
```

Some services do not work with `DOWN` interfaces. For example, `keepalived` automatically goes to the `FAIL` state, if it detects a managed interface is `DOWN`.

**Describe the solution you'd like**

While the interface state `UP` doesn't seem to be [implemented](https://serverfault.com/questions/629676/dummy-network-interface-in-linux/629815#629815), `IFF_UP` should be called regardless, which would put the interface in the `UNKNOWN` state.

I suppose this could be done by implementing a `netdev_dummy_post_create()` function in `src/network/netdev/dummy.c`, analogue to `src/network/netdev/bridge.c` and call the following:

```c
sd_rtnl_message_link_set_flags(m, IFF_UP, IFF_UP)
netlink_call_async()
```

**Describe alternatives you've considered**

The root cause why I've tried using a dummy interface as a workaround is described in https://github.com/systemd/systemd/issues/12050

**Comment by poettering** [comment]
Please drop in a .network file matching the dummy device. The device will then be IFF_UP'ed as configured.

.netdev files are purely for creating network devices. .network files are then to apply network configuration to them and ultimately IFF_UP them.

(you can even drop in a catchall .network file that matches against Driver=dummy in the [Match] section and thus automatically IFF_UPs all devices of this driver).
