### ISSUE TITLE
systemd-networkd prunes floating virtual IPs for high-availability environments

### ISSUE THREAD

**Issue by chr4** [systemd/systemd#12050]
**Is your feature request related to a problem? Please describe.**

When maintaining virtual floating IPs (VIPs) on high-available systems, I'm seeing them pruned when restarting `systemd-networkd` (even with no config changes) which results in a downtime.

This problem is especially severe when DHCP is used, as it is also triggered when the DHCP lease gets renewed (some cloud providers use DHCP by default to configure network interfaces). But also on static IP configurations, systemd-networkd might get restarted from time to time (automatic security patches, etc.).

I'm aware that this is a [feature](https://github.com/systemd/systemd/issues/780#issuecomment-126067240) (which I agree is useful for desktops, etc.). In high-available environments with VIPs this backfires when using Linux distributions that rely on `systemd-networkd` (like Ubuntu, via [netplan](netplan.io)).

**Describe the solution you'd like**

I'm suggesting a flag that disables this behaviour, or would allow whitelisting certain VIPs to prevent them from purging. I've tried `CriticalConnection=true`, but this doesn't prevent the pruning.

**Describe alternatives you've considered**

1. Using a `dummy` interface and rely on weak host mode (ES): This doesn't work, as the gratitious ARPs/ unsolicited neighbour adverts can't be send using a dummy interface. There's another issue with this approach, which I described in https://github.com/systemd/systemd/issues/12051
2. Filing a patch to keepalived to support sending out NA/GARP via another interface (which is currently considered by them, see https://github.com/acassen/keepalived/issues/1170, but might not work
3. Migrating back to `ifupdown`
4. Migrating to a distribution without `systemd-networkd`
5. Migrating to BSD

**Comment by poettering** [comment]
I figure instead of removing them right away we could just mark them with some short remaining lifetime.

In general though: either networkd manages an interface or it doesn't. Just leaving old configuraion on the interface will become a problem sooner or later. I mean, somebody needs to clean that up, and simply ignoring everything is not just going to be a major source of headaches.

**Comment by chr4** [comment]
> In general though: either networkd manages an interface or it doesn't. Just leaving old configuraion on the interface will become a problem sooner or later. I mean, somebody needs to clean that up, and simply ignoring everything is not just going to be a major source of headaches.

I was wondering what's the best practise regarding floating IPs then? As far as I'm aware this is a quite common solution for implementing high-availability - especially with protocols like VRRP and CARP available. Mixing systemd-network and ifupdown (or reverting to the latter) increases the likelyhood of headaches imho...

**Comment by ssahani** [comment]
It seems to me your link is getting down and then getting up . Try with ```IgnoreCarrierLoss```

**Comment by chr4** [comment]
I've tried that, but `IgnoreCarrierLoss` doesn't help.

After further discussion in https://github.com/acassen/keepalived/issues/1170, there is an option to make it work using macvlans, but only when using multicast.

Currently, there seems to be no option to run systemd-networkd alongside a high availability service that doesn't create a custom interface (e.g. via macvlan) but uses existing interfaces. I suppose this doesn't only affect VRRP but also things like CARP.

I'm not sure how this would be best solved, I can't think of anything better than a flag that prevents address pruning altogether or some flag that allows whitelisting certain IPs that won't be pruned upon reload.

**Comment by ssahani** [comment]
Could you please give a reproducer ?

**Comment by chr4** [comment]
> Could you please give a reproducer ?

A implified version can be reproduced by just adding an address to an interface and then restarting `systemd-networkd`. The addres will be purged.

```bash
ip a a 1.2.3.4/24 dev eth0
systemctl restart systemd-networkd
```

This becomes a problem in cases where the additional address is used as a virtual or floating IP in higih-available environments (where a master IP is swapped to a different service upon failovers, e.g. by services like [Pacemaker](http://linux-ha.org/wiki/Pacemaker), [keepalived](https://keepalived.org/) and alike, usually using protocols like Corosync, VRRP or CARP). Those addresses are not handled by `systemd-networkd` and are therefore purged upon DHCP renewals or when an update triggers a restart of `systemd-networkd`, therefore potentially resulting in downtimes or at least unecessary failovers.
