### ISSUE TITLE
journal logs entries under incorrect unit

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#12064]
**systemd version the issue has been seen with**
> 241.7-2

**Used distribution**
 > Archlinux

**Unexpected behaviour you saw**
 > the systemd-journald started logging entries under incorrect unit

log-messages for `nginx` started under the `php-fpm` unit - this is the second time I've seen this happening. Here is the redacted `json-pretty` output from journalctl, first the last correct message, and then an incorrect one

```
{
        "MESSAGE" : "2019/03/21 01:30:07 [error] 3153#3153: *117641 access forbidden by rule, client: *",
        "_UID" : "0",
        "_HOSTNAME" : "*",
        "_MACHINE_ID" : "*",
        "SYSLOG_IDENTIFIER" : "nginx",
        "PRIORITY" : "3",
        "_TRANSPORT" : "stdout",
        "_GID" : "0",
        "__MONOTONIC_TIMESTAMP" : "816766790486",
        "_PID" : "2308",
        "_STREAM_ID" : "c1851a60d5bc406d8a7de039c9caa20f",
        "__REALTIME_TIMESTAMP" : "1553128207708929",
        "__CURSOR" : "*",
        "_SYSTEMD_INVOCATION_ID" : "de0d4182e5de4564939557eaec5b5690",
        "_SYSTEMD_UNIT" : "nginx.service",
        "_BOOT_ID" : "c691cf5655064373bfed9c5425f82ef8",
        "SYSLOG_FACILITY" : "3"
}
* no relevant messages - other then a few systemd-timers running *
{
        "_HOSTNAME" : "*",
        "_SYSTEMD_UNIT" : "php-fpm.service",
        "_SYSTEMD_CGROUP" : "/system.slice/php-fpm.service",
        "_CAP_EFFECTIVE" : "0",
        "_COMM" : "php-fpm",
        "_SYSTEMD_SLICE" : "system.slice",
        "_STREAM_ID" : "c1851a60d5bc406d8a7de039c9caa20f",
        "SYSLOG_FACILITY" : "3",
        "_MACHINE_ID" : "*",
        "__REALTIME_TIMESTAMP" : "1553128385506539",
        "_PID" : "2308",
        "_GID" : "33",
        "SYSLOG_IDENTIFIER" : "nginx",
        "_BOOT_ID" : "*",
        "_TRANSPORT" : "stdout",
        "_SYSTEMD_INVOCATION_ID" : "97b0c3eb75fa484eb73adb905a03d286",
        "__MONOTONIC_TIMESTAMP" : "816944588097",
        "_EXE" : "/usr/bin/php-fpm",
        "__CURSOR" : "*",
        "PRIORITY" : "3",
        "_UID" : "33",
        "_CMDLINE" : "php-fpm: pool *",
        "MESSAGE" : "2019/03/21 01:33:05 [error] 3153#3153: *117672 access forbidden by rule, client: *"
}
```

It seems the `SYSLOG_IDENTIFIER`, `MESSAGE` and timestamps are correct, but the unit-related stuf (I think even the `PID`) is incorrect. Since this started happening, messages from nginx consistently end up under the incorrect unit.

**Steps to reproduce the problem**
I'd love to help - but this happens in the middle of the night when nothing really happened

**Comment by poettering** [comment]
when the "stdout" transport is used for logging (i.e. output just written to stdout/stderr) then systemd can't distinguish which process precisely the messages are coming from, it will all attribute them to the initial process systemd forked off. This is a limitation of how AF_UNIX stream sockets work (as for the we can only query the peer connecting originally, but not the process actually writing data into it), and hence there's little we can do about it.

This is documented in all detail here:

https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Stream%20logging

It's recommended to use a different log protocol (i.e. syslog or journal native) if you have multiple processes logging and need correct per-process attribution.

Yes, this sucks hard, but it's a limitation of the technical underpinnings I fear. There's not much we can do about that from our side I fear. At least not without a kernel patch that teaches AF_UNIX new tricks. :-(

Closing hence, as there's nothing actionable of fixable here, and this behaviour is documented. Hope that makes sense...

**Comment by SjonHortensius** [comment]
Thanks for your extensive explanation. It is sub-optimal - but I understand this cannot be fixed by systemd. Thankfully this all works fine most of the time.
