### ISSUE TITLE
Autologin on ttys doesn't work anymore

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#12083]
**systemd version the issue has been seen with**
> In v239 (Fedora29) . In v237 too (Ubuntu 18.04)

**Expected behaviour you didn't see**
 > I did long time ago a trick (which worked!) to enter automatically into a specific user session when pressing CTRL+ALT+FX (ttyX) without having to write its password. The trick (which is documented in https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console, for instance) is simply adding the option --autologin username to the ExecStart line (which invokes agetty binary) in /usr/lib/systemd/system/getty@.service file. But doing this currently, username is automatically catched but its password is asked anyway. If tried removing the -o parameter from agetty arguments because it's a "new kid on the block" but without luck. 

Maybe it's a problem in PAM. Maybe it's in login binary or in agetty itself. But maybe systemd-logind is related to it, so I've thought this issue was worth to be written and known. If it isn't, sorry for the inconvenience and feel free to close it.

Thanks

**Comment by poettering** [comment]
systemd is not involved in asking for a password. That's "login"'s job. Please report this to util-linux instead! Thanks!
