### ISSUE TITLE
.network files without any directives should be logged and/or ignored

### ISSUE THREAD

**Issue by mahkoh** [systemd/systemd#12098]
**Is your feature request related to a problem? Please describe.**

Commented-out .network files are applied to all interfaces. By commented-out I mean that all lines in the file start with a `#`. All later .network files are ignored. When I comment out a configuration file I expect it to be ignored.

The docs say `The network file contains a "[Match]" section`. One might argue that the current networkd behavior is a bug because a commented-out file does not contain a Match section and is therefore not a network file and should therefore not be applied to anything. Not that such a pedantic reading would have helped me because I didn't read this paragraph until I was well into debugging the problem.

**Describe the solution you'd like**

networkd should log when it encounters and applies a network file without any directives. By *directive* I mean any non-empty non-comment line.

**Describe alternatives you've considered**

networkd could log and then ignore such files.

**Comment by mahkoh** [comment]
I forgot to mention that ignoring such files would also make the existing special cases surrounding *empty* files more consistent. The current behavior is not ideal:

`echo -n > 00.network` causes `00.network` to be ignored.

`echo > 00.network` causes *all other* .network files to be ignored.

**Comment by poettering** [comment]
So, empty .network files have an effect, and a useful one even: they cause all network devices to set to IFF_UP as they appear.

Hence, yes, most likely it is misconfiguration, but also possibly not. If do anything about this issue we shouldn't break the usecase of ensuring all ifaces are put into IFF_UP.

**Comment by mahkoh** [comment]
I agree which is why I put log-and-continue as the preferred solution. I believe there already is a warning for netdev files that don't contain certain required sections.

**Comment by yuwata** [comment]
I thought that we should warn about the `[Match]` section is empty. But, for example, `99-default.link` does not contain `[Match]` section, and it is intended. So, now I do not have any good idea when we warn about that...

**Comment by keszybz** [comment]
We already had a long discussion about this... What about this:
1. add `[Match] Name=*` to `99-default.link`
2. warn if there's no [Match] section or if it is empty
?

**Comment by yuwata** [comment]
Sounds nice.

**Comment by yuwata** [comment]
I've created #12358. PTAL.

**Comment by amishmm** [comment]
Sorry I am late to the party and just came across this bug today.

But I think

> `echo -n > 00.network` causes `00.network` to be ignored.

This can be used to set IFF_UP (existing behavior which @poettering wants to retain)
 
> `echo > 00.network` causes _all other_ .network files to be ignored.

This (OR `echo '#' > 00.network`) should be ignored. i.e. file with no section at all should be warned and **ignored**.

If admin doesnt want it to be ignored. Admin can add
```
[Match]
OriginalName=*
```

Because general expectation is that commented out file would be ignored instead of being applied to all interfaces.
