### ISSUE TITLE
[networkd] secondary routing table memory usage

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#12093]
I have a few small servers used as "routers" among various other tasks, and they have the full IPv6 routing table loaded from BGP into a secondary kernel routing table. (The main table is reasonably small.)

```
$ ip -6 route show | wc -l
62
$ ip -6 route show table 2 | wc -l
64839
$ ip -6 route show table all | wc -l
64946
```

It seems that systemd-networkd loads _all_ routes from all tables into its memory, which results in significant memory usage (~120 MB RES) for the process. That's actually more than the BGP daemon itself. (And I have a suspicion it's not the only program doing so; Postfix seems to have a similar issue as well...) This doesn't cause networkd to _fail_, but you can see that the memory usage quickly multiplies this way.

As far as I know, networkd doesn't really _need_ to know all routes at once – just default routes, device routes, and routes that it added by itself. At most, it really should be enough to just load the "main" table (table 254) and ignore the rest. (If it needs to determine whether _a_ route exists to a given destination, it could use RTM_GETROUTE for that, I believe.)

**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > networkd's RSS usage should be a few megabytes

**Unexpected behaviour you saw**
 > networkd's RSS usage is ~115 MB, large parts of which hold the entire IPv6 routing state

**Steps to reproduce the problem**
 > \>Be an a networking hobbyist and an IPv6 enthusiast  
 > \>Establish a BGP peering with e.g. Tunnelbroker  
 > \>Load ~65k IPv6 routes into the kernel

**Comment by yuwata** [comment]
Maybe related to #11575. But the workaround for #11575 does not help this issue, unfortunately.

**Comment by petabyteboy** [comment]
On my router with ipv4 and ipv6 full table systemd-networkd will start allocating up to 900MiB memory until it runs oom and gets killed in a loop. I only have one .network file to enable DHCP on my main interface.

**Comment by petabyteboy** [comment]
https://asciinema.org/a/gUP5wuFcqNn2nvt5p3ldxhkZt

**Comment by ssahani** [comment]
hmm I think in this case the foreign routes we need to have a setting that we don't load in networks memory.

**Comment by Kloenk** [comment]
> On my router with ipv4 and ipv6 full table systemd-networkd will start allocating up to 900MiB memory until it runs oom and gets killed in a loop. I only have one .network file to enable DHCP on my main interface.

I have a similar setup as @petabyteboy and at boot it idles by around RES 390M. If I restart systemd-networkd it goes up, until my server does not respond anymore.

**Comment by ssahani** [comment]
We can close this.
