### ISSUE TITLE
Automatic propagation of cgroup protection tunables

### ISSUE THREAD

**Issue by cdown** [systemd/systemd#12099]
In cgroup v2 we have protection tunables -- currently MemoryLow and MemoryMin (there will be more in future for other resources, too). The design of these protection tunables requires not only intermediate cgroups to propagate protections, but also the units at the leaf of that resource's operation to accept it (by setting MemoryLow or MemoryMin).

This makes sense from an low-level API design perspective, but it would also be good to have a higher-level abstraction that can, by default, propagate these resources to children recursively. This would happen by having descendants set `MemoryXXX=max` implicitly, if their ancestor has `PropagateProtection=MemoryXXX`. Of course, that name is up for discussion -- there may be better ones. :-)

Any affected unit could opt out of this propagation by manually setting `MemoryXXX` to some value in its unit configuration. A unit could also stop propagation by setting `PropagateProtection=` with no argument to remove propagated tunables.

Our use case in production is simplifying the configuration of machines which heavily rely on memory protection tunables, but currently require tweaking a huge number of unit files to make that a reality. This directive would make that significantly less fragile, and decrease the risk of misconfiguration.

If this sounds good, I'll get to work on a patch to this effect. :-)

**Comment by poettering** [comment]
Hmm, what about doing a "DefaultMemoryLow=" or so in slice units. And service units would default to the DefaultMemoryLow= setting it's closest parent has set?

This would do what we are looking for, no?

I thinking about this as "default" would make things a lot simpler, and we could even get rid of DefaultMemoryAccounting= (and similar) in /etc/systemd/system.conf then, as these could just become settings of slices too then, and the global one you'd set on "-.slice", so that it propagates everywhere.

Does that make sense?

**Comment by cdown** [comment]
I had thought about this but came to the conclusion that I didn't like the name with "Default" since it doesn't have identical semantics to things like `DefaultMemoryAccounting`. If you're ok with making them unit properties as well, though, sounds excellent to me. I can take a look at doing both of those. :-)

In which case, I'll go ahead and get on with these.

**Comment by poettering** [comment]
yeah, I think moving some of the DefaultXYZ= settings currently in system.conf into slices would make a lot of sense.

Let's exercise some constraint though. I think moving the DefaultXYZAccounting= ones over makes sense, and so does DefaultTasksMax= and then the memory ones you are asking for. On top of that people would probably love to see DefaultEnvironment=, DefaultCPUAffinity=, DefaultLogExtraFields= I guess... But the other's we should probably not bother with for now. And I guess if you work on this you shouldn't really bother with all of those either, just the ones which matter to you, but htat's up to you...

**Comment by cdown** [comment]
I mostly just want to make sure that eventually we end up with some kind of coherence in the `DefaultXYZ` settings, but yeah, it's less urgent than getting `DefaultMemoryLow` and the like.

**Comment by cdown** [comment]
PR out at #12211. :-)

**Comment by cdown** [comment]
#12211 and #12332 merged.
