### ISSUE TITLE
The host suddenly lost power, after the virtual machine started, BindsTo device service is inactive，mount point service not ok for ever.

### ISSUE THREAD

**Issue by hexiaowen** [systemd/systemd#12094]
**systemd version the issue has been seen with**
> 219

**Used distribution**
 > centos

**Expected behaviour you didn't see**
 > Mount Point Mount Succeeded

**Unexpected behaviour you saw**
 > The host suddenly lost power, after the virtual machine started. BindsTo device service is inactive，mount point service not ok for ever.
>
>status in systemd-analyze plot:
opt-gaussdb.mount (1d 7h 37min 28.461s)
>
>The following prints always appear in /var/log/messages :
03-21T13:03:44.079642 systemd: opt-gaussdb.mount mount process exited, code=exited status=32
 03-21T13:03:44.080290 systemd: Failed unmounting /opt/gaussdb.
 03-21T13:03:44.081081 systemd: Unit opt-gaussdb.mount is bound to inactive unit dev-gaussdb_vg-gaussdb.device. Stopping, too.
 03-21T13:03:44.081313 systemd: Unmounting /opt/gaussdb...
 03-21T13:03:44.085593 systemd: opt-gaussdb.mount mount process exited, code=exited status=32
 03-21T13:03:44.086340 systemd: Failed unmounting /opt/gaussdb.
 03-21T13:03:44.087124 systemd: Unit opt-gaussdb.mount is bound to inactive unit dev-gaussdb_vg-gaussdb.device. Stopping, too.
 03-21T13:03:44.087415 systemd: Unmounting /opt/gaussdb...

**Steps to reproduce the problem**
>None

**Comment by hexiaowen** [comment]
I want to know what caused it. Who can help me.

**Comment by poettering** [comment]
This is the upstream bug tracker for systemd, and we only cover issues in the two most recently released systemd versions here. The issue submission form is supposed to make this very clear. Currently that's systemd v240 and v241. For everything older (and 219 is much much older), please contact your downstream distribution for help. Thank you for understanding.
