### ISSUE TITLE
journalctl not honoring `kernel.dmesg_restrict`

### ISSUE THREAD

**Issue by evict** [systemd/systemd#12112]
**systemd version the issue has been seen with**
> systemd 241 (241.7-2-arch)

**Used distribution**
 > Arch Linux 

**Expected behaviour you didn't see**
 > Just like running `dmesg`, `journalctl -ef -k` should state: permission denied.

**Unexpected behaviour you saw**
 > running `journalctl` displays dmesg.

```bash
Ʋ dmesg                                                                                                                                              INSERT
dmesg: read kernel buffer failed: Operation not permitted
evict@UNLIGHT:/home/evict
Ʋ journalctl --dmesg -e | head -10                                                                                                                   INSERT
-- Logs begin at Thu 2018-10-18 17:25:11 CEST, end at Tue 2019-03-26 16:07:39 CET. --
Mar 26 15:50:46 UNLIGHT kernel: check: Scanning 1 areas for low memory corruption
Mar 26 15:50:46 UNLIGHT kernel: Base memory trampoline at [(____ptrval____)] 97000 size 24576
Mar 26 15:50:46 UNLIGHT kernel: Using GB pages for direct mapping
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c01000, 0x336c01fff] PGTABLE
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c02000, 0x336c02fff] PGTABLE
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c03000, 0x336c03fff] PGTABLE
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c04000, 0x336c04fff] PGTABLE
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c05000, 0x336c05fff] PGTABLE
Mar 26 15:50:46 UNLIGHT kernel: BRK [0x336c06000, 0x336c06fff] PGTABLE
```

**Steps to reproduce the problem**

1. Set `kernel.dmesg_restrict` to `1`.
2. Run `dmesg`
3. Run `journalctl -k`

**Comment by mvduin** [comment]
Would it not suffice to simply remove the user from group `systemd-journald` if it is not desirable that they can access the system's logs? Or do you mean that you want two "levels" of system logs, one restricted to privileged access and one with wider access?

**Comment by evict** [comment]
It is not about being able to read system logs, it is more about being able to read `dmesg`. As described [here](https://lwn.net/Articles/414813/) there is already a feature embedded in the kernel, that allows only users with the `CAP_SYS_ADMIN` to read the kernel buffer when the `kernel.dmesg_restrict` option is set. `systemd-journald` is executed with `CAP_SYS_ADMIN`, meaning that anybody calling `journalctl` can read this buffer, bypassing the protection.

My solution would be to check if  `dmesg_restrict` is set, and the user has the corresponding capability, as explained in the article referenced. 

1.https://lwn.net/Articles/414813

**Comment by mvduin** [comment]
> It is not about being able to read system logs, it is more about being able to read dmesg.

The kernel log isn't the only system log (yes, the kernel is part of your system :P ) that contains potentially sensitive information.

> As described here there is already a feature embedded in the kernel, that allows only users with the CAP_SYS_ADMIN to read the kernel buffer when the kernel.dmesg_restrict option is set.

Yes, it uses a crude mechanism that restricts kernel log access to CAP_SYS_ADMIN (which seems a bit excessive), since this is sufficient to allow more appropriate access control (e.g. based on group membership) to be handled in userspace by your system logging daemon (e.g. journald), the kernel doesn't need to concern itself with such system administration policy details.

> systemd-journald is executed with CAP_SYS_ADMIN, meaning that anybody calling journalctl can read this buffer

No it doesn't "mean" that. journald applies appropriate ACLs to ensure normal users can only access their own journal, which does not include the kernel log. Only users in group `systemd-journal` are permitted access to the system journal (which includes the kernel log), which is the exact purpose of that group.

That's why I asked:

> Would it not suffice to simply remove the user from group systemd-journald if it is not desirable that they can access the system's logs? Or do you mean that you want two "levels" of system logs, one restricted to privileged access and one with wider access?

But you didn't actually answer that.

**Comment by evict** [comment]
>Yes, it uses a crude mechanism that restricts kernel log access to CAP_SYS_ADMIN (which seems a bit excessive), since this is sufficient to allow more appropriate access control (e.g. based on group membership) to be handled in userspace by your system logging daemon (e.g. journald), the kernel doesn't need to concern itself with such system administration policy details.

Ah, in that case I think we should close this issue. I will contact the `linux-hardened` project instead, and propose to remove the `systemd-journal` group permission from the user.  I think this would suffice.

Thank you for you time and explanation.
