### ISSUE TITLE
Incorrect Wireguard backoff timing

### ISSUE THREAD

**Issue by legonigel** [systemd/systemd#12134]
Seen in git master code. I am not running and cannot test. 

Comments in code for function exponential_backoff_milliseconds says "Given the number of retries this function will return will an exponential increasing time in milliseconds to wait starting at 200ms and capped at 25 seconds." However the code reads that it starts at 25s and works upwards. 

Current: `return (2 << MAX(n_retries, 7U)) * 100 * USEC_PER_MSEC;`

Corrected: `return (2 << MIN(n_retries, 7U)) * 100 * USEC_PER_MSEC;`

See [wireguard.c](https://github.com/systemd/systemd/blob/c6335c3b51801e5750ec043dde45100e2a07d1df/src/network/netdev/wireguard.c#L325)

**Comment by poettering** [comment]
fix waiting in #12139
