### ISSUE TITLE
documentation of dbus activation for --user

### ISSUE THREAD

**Issue by shawnl** [systemd/systemd#12143]
**Is your feature request related to a problem? Please describe.**
I have to manually load gedit when I start a desktop session to get the behaviour I want. This is because when it starts it checks if gedit is listening on dbus, if so it asks the running session to open the file, otherwise it starts, however I do not want to run gedit from a terminal, even with bash's `&` fork.

**Describe the solution you'd like**
Create a gedit.service in /usr/lib/systemd/user, and a d-bus service file...somewhere, and have gedit automatically launched when it queries if it is listening on dbus.

**Describe alternatives you've considered**
Autostart on session doesn't work, because gedit sometimes crashes on large files.

---

I was one of the early contributors to systemd, and would look into solving this if my proposal is accepted, and we can decive where the d-bus service files go. (also, does this need coordination with dbus?)

**Comment by poettering** [comment]
dbus activation for the --user instance should just work, dbus had that since its inception. 

To work this just means you need to pair a dbus .service file (i.e. the dbus description of a service for the purpose of service activation, not to be confused with a systemd unit file that also has the .service suffix) with a native systemd .service file. Then, inside of the dbus.service file use SystemdService= to attach the native systemd .service file to it, and that's all that should be necessary...

**Comment by poettering** [comment]
Hence afaics all you need to do is make sure gedit is properly set up for this and doesn't actively avoid talking to gedit's bus service if it detects that activation hasn't yet taken place. But either way, that would all be fixes to gedit, not to systemd.

Or what am I missing?

**Comment by shawnl** [comment]
> Or what am I missing?

Documentation. The documentation in `systemd.service` doesn't say where to put user service files, only system d-bus service files. Now that I know I will find out (and send a patch), but the documentation should be better.
```
       For bus-activatable services, do not include a "[Install]" section in
       the systemd service file, but use the SystemdService= option in the
       corresponding DBus service file, for example
       (/usr/share/dbus-1/system-services/org.example.simple-dbus-service.service):

           [D-BUS Service]
           Name=org.example.simple-dbus-service
           Exec=/usr/sbin/simple-dbus-service
           User=root
           SystemdService=simple-dbus-service.service
```

**Comment by shawnl** [comment]
Oh, its just `services` lol, because that came first. Yeah I'll send a patch.
