### ISSUE TITLE
swap hell & console login

### ISSUE THREAD

**Issue by babouaya** [systemd/systemd#12154]
Hi systemd folks.

I'm a Linux user for, well, 20 years now, and truly in spite of all the flame around systemd I really think it is the Right Thing To Do. But there is a little thing it could do better.
Linux still have a disease. Although it pops up extremely rarely, sometimes Linux get lost in a swap hell. In the past, when that happened, I *could* have a chance to switch to a virtual terminal, there getty or mingetty or whatever was sitting there, it was sometimes possible to log on & kill -9 -1. Nowadays, I sometimes have a chance to switch to a VT, but logind or whatever doesn't even start. Most of the time it ends up with a press on the reset button, but once I decided to give it a chance & went away doing something else. 45 minutes later, the swap fest was still going on, and logind was still expected, the VT showing a lonely blinking cursor.
Again, I insist, this happens very rarely and it's basically not a systemd issue. But I feel I had more control when getty was already up & waiting for input. I may be wrong, it may be just a feeling, anyway it is. I know it would break the dynamic behavior of systemd, but what if it unconditionally launched a logind on a VT at startup ?

This is a very minor rant, but I felt the need to share my impressions. Overall, systemd was the missing piece of the Linux desktop, what it accomplished is a huge step. Thanks a lot :+1:

**Comment by mbiebl** [comment]
If you want, you can can statically enable a getty.  Say you want to run that on tty6, then do the following:
`systemctl enable --now getty@tty6`

I think that should cover your use-case, right?

**Comment by FOSSONLY** [comment]
https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

Use this and forget about swap-hell.

**Comment by poettering** [comment]
@mbiebl is right. if you want to pre-allocate a getty, you can enable it persistently, and then don't have to rely on the start-on-demand logic. Of course by doing that you keep more services started that you don#t actually need most of the time.

Anyway, let's close this, as what you are looking for is totally doable already, and easily done.

**Comment by babouaya** [comment]
Sorry for the late reply, and thank you for your help.

**Comment by vcaputo** [comment]
You can also leverage cgroups to better memory reclamation and mitigate "swap hell" scenarios.  Systemd has some integration with this, see systemd.resource-control(5) for more info.
