### ISSUE TITLE
hwdb: false match

### ISSUE THREAD

**Issue by vfjpl** [systemd/systemd#12178]
Hello.

I didn't find any information about what to do if rule matches me but is shouldn't. The rule in question is from 60-keyboard.hwdb file:
```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pn*
```

I will provide any information that is needed.

And related question. How to check what rules got matched on my system?

**Comment by poettering** [comment]
This was added in e09dba97b96f877e36cd3f1afdb321922eed064b.

**Comment by poettering** [comment]
> And related question. How to check what rules got matched on my system?

Use 

```udevadm info /sys/class/input/event8```

on the event device that belongs to your keyboard. To determine which one that is look into `/proc/bus/input/devices` and check which of the entries therein lists which eventXYZ device in its Handlers= line.

but note that you need to rebuild the hwdb and trigger the device to make sure they are applied correctly:

```
udevadm hwdb --update
udevadm trigger -s input
```

**Comment by vfjpl** [comment]
Sorry, I didn't understand what you was trying to say. I know which eventX is my Keyboard. But I didn't understand the rest.

Let me make my question again. :)
There are many files like 70-mouse.hwdb, 60-keyboard.hwdb and so one. In this files there are strings like
`mouse:usb:v046dpc065:name:Logitech USB Laser Mouse:`
and so one. How to check which of this strings matched my computer. Like list of this strings from every .hwdb file that got applied on my system. :)

**Comment by poettering** [comment]
try "udevadm test" on the device

**Comment by vfjpl** [comment]
udevadm test show things like
` KEYBOARD_KEY_b2=www
 KEYBOARD_KEY_b3=euro
KEYBOARD_KEY_b4=dollar`
and so one. But it doesn't tell my what rule applied them.
It doesn't tell me that it was
`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pn*`
:)

This laptop is pretty old.
This is /sys/class/dmi/id/modalias
`cat /sys/class/dmi/id/modalias
dmi:bvnPackardBell:bvrV0.22:bd07/11/2007:svnPackardBellBV:pnEasyNoteMZ35:pvr:rvnPackardBellBV:rnEasyNoteMZ35:rvrD3B:cvnPackardBellBV:ct10:cvrN/A:`
Do you need any more info to exclude my laptop from matching `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pn*`?

**Comment by poettering** [comment]
the hwdb source files are compiled into binary patricia trees to optimize lookup. At that time the source line information is not retained. Hence I am sorry, but what you are asking for can't really be done in the current model

**Comment by poettering** [comment]
(you could modify the hwdb entry you presume is at fault so that it doesn't match your device anymore, then recompile the hwdb, to verify that it's causing your entry to be created)

**Comment by vfjpl** [comment]
> udevadm info /sys/class/input/event4
> P: /devices/platform/i8042/serio0/input/input4/event4
> N: input/event4
> L: 0
> S: input/by-path/platform-i8042-serio-0-event-kbd
> E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
> E: DEVNAME=/dev/input/event4
> E: MAJOR=13
> E: MINOR=68
> E: SUBSYSTEM=input
> E: USEC_INITIALIZED=21787402
> E: KEYBOARD_KEY_86=wlan
> E: KEYBOARD_KEY_a5=help
> E: KEYBOARD_KEY_a6=setup
> E: KEYBOARD_KEY_a7=battery
> E: KEYBOARD_KEY_a9=switchvideomode
> E: KEYBOARD_KEY_b2=www
> E: KEYBOARD_KEY_b3=euro
> E: KEYBOARD_KEY_b4=dollar
> E: KEYBOARD_KEY_ce=brightnessup
> E: KEYBOARD_KEY_d4=bluetooth
> E: KEYBOARD_KEY_d5=wlan
> E: KEYBOARD_KEY_d6=wlan
> E: KEYBOARD_KEY_d7=bluetooth
> E: KEYBOARD_KEY_d8=bluetooth
> E: KEYBOARD_KEY_d9=brightnessup
> E: KEYBOARD_KEY_ee=brightnessup
> E: KEYBOARD_KEY_ef=brightnessdown
> E: KEYBOARD_KEY_f1=f22
> E: KEYBOARD_KEY_f2=f23
> E: KEYBOARD_KEY_f3=prog2
> E: KEYBOARD_KEY_f4=prog1
> E: KEYBOARD_KEY_f5=presentation
> E: KEYBOARD_KEY_f6=power
> E: KEYBOARD_KEY_f8=fn
> E: KEYBOARD_KEY_f9=prog1
> E: ID_INPUT=1
> E: ID_INPUT_KEY=1
> E: ID_INPUT_KEYBOARD=1
> E: ID_BUS=i8042
> E: ID_SERIAL=noserial
> E: ID_PATH=platform-i8042-serio-0
> E: ID_PATH_TAG=platform-i8042-serio-0
> E: LIBINPUT_DEVICE_GROUP=11/1/2:isa0060/serio0
> E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
> E: TAGS=:power-switch:

After commenting out `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pn*` from `/usr/lib/udev/hwdb.d/60-keyboard.hwdb`

> sudo udevadm hwdb --update
> sudo udevadm trigger -s input
> udevadm info /sys/class/input/event4
> P: /devices/platform/i8042/serio0/input/input4/event4
> N: input/event4
> L: 0
> S: input/by-path/platform-i8042-serio-0-event-kbd
> E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
> E: DEVNAME=/dev/input/event4
> E: MAJOR=13
> E: MINOR=68
> E: SUBSYSTEM=input
> E: USEC_INITIALIZED=21787402
> E: ID_INPUT=1
> E: ID_INPUT_KEY=1
> E: ID_INPUT_KEYBOARD=1
> E: ID_BUS=i8042
> E: ID_SERIAL=noserial
> E: ID_PATH=platform-i8042-serio-0
> E: ID_PATH_TAG=platform-i8042-serio-0
> E: LIBINPUT_DEVICE_GROUP=11/1/2:isa0060/serio0
> E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
> E: TAGS=:power-switch:

**Comment by poettering** [comment]
@vfjpl so, what's the plan here, are you going to submit a patch for the hwdb that adds a corrected, less broad check?

@mschiu77 any chance you can look into fixing the rule to not cover @vfjpl's laptop?

**Comment by vfjpl** [comment]
> so, what's the plan here, are you going to submit a patch for the hwdb that adds a corrected, less broad check?

I would love to. But don't know how this rules works. How to make exceptions? Maybe every `PackardBell` laptop except `EasyNote` or `EasyNoteMZ35`?

**Comment by mschiu77** [comment]
@vfjpl <https://github.com/vfjpl> As you mentioned, the machine is pretty
old per dmi:bvnPackardBell:bvrV0.22:bd07/11/2007. Could you verify if
there's any BIOS update? Because per Acer's BIOS spec 20170802, the
PackardBell Easynote series follows the same scan code rules as other Acer
series. Please `apt-get install evtest` and then execute evtest to verify
the which scan code is fired when you press the airplane mode hotkey. I
have to make sure it already complies with the latest SPEC or not.

If BIOS update still fails on your case. Please try to add the following
strings in your keyboard rule.

evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell:pnEasynote*:pvr*
  KEYBOARD_KEY_86=wlan

I'll try to get other PackardBell machines to separate different cases.

**Comment by vfjpl** [comment]
@mschiu77 wlan on/off key is completely controlled in hardware. It doesn't even send any key do system. Is that what you meant by airplane key? If no then there is no more "wlan" keys.

My bios is from here. I didn't find any more "official" bios on elsewhere.
ftp://ftp.download.packardbell.com/NOTEBOOK/EasyNote%20MZ35%20series/Bios/

**Comment by vfjpl** [comment]
I have two keyboards.

![56790951_392859144884647_4495054626726346752_n](https://user-images.githubusercontent.com/18666007/55707219-5c26b680-59e3-11e9-8b03-6248d4a1b784.jpg)
![56645706_989586651430648_6008956780963430400_n](https://user-images.githubusercontent.com/18666007/55707224-6052d400-59e3-11e9-9b45-0f68f9e0a539.jpg)
![56795491_621826664908773_7889564990984683520_n](https://user-images.githubusercontent.com/18666007/55707226-62b52e00-59e3-11e9-911a-b45fe9b0521b.jpg)

I can swap keyboard if you also want to check the "broken" one. And send more pictures.

**Comment by mschiu77** [comment]
Thanks. I just need to know if Fn+F2 works for you and does it fire any
scan code when pressing.

**Comment by vfjpl** [comment]
@mschiu77 It's just couple of screws ;). I have changed the keyboard to the "broken" one. Both of them don't send any signal to system on wlan keys.

Here is back of "working" keyboard. 
![56726608_291001411797306_1156111368227651584_n](https://user-images.githubusercontent.com/18666007/55736159-1093fd00-5a23-11e9-9273-a61fe84f5dd8.jpg)

Have you seen my previous message?
"@mschiu77 wlan on/off key is completely controlled in hardware. It doesn't even send any key do system. Is that what you meant by airplane key? If no then there is no more "wlan" keys.

My bios is from here. I didn't find any more "official" bios on elsewhere.
ftp://ftp.download.packardbell.com/NOTEBOOK/EasyNote%20MZ35%20series/Bios/
If you have any pleas tell me. :)"

**Comment by vfjpl** [comment]
Additionally this laptop model have separate wlan on/off key. Which is also controlled in hardware and don't send any signal to system.
(I have lost keycap)
![56448976_1054621098066509_8390413295013593088_n](https://user-images.githubusercontent.com/18666007/55736978-abd9a200-5a24-11e9-89d1-fe41e264b400.jpg)

**Comment by mschiu77** [comment]
@vfjpl Thanks for your information. So I don't have to create any new rules
for the PackardBell Easynote Series. I'll upstream an update hwdb rule for
this later.

**Comment by jprvita** [comment]
@vfjpl Could you please elaborate better on what is the problem you are experiencing here? I.e., which action are you performing, what is that you expected to happen, and what happens instead?

Also, it would be helpful to see the output of `evtest` when you perform the action you believe is being handled incorrectly, assuming is is a key press that is not performing the action you expect. Please run `evtest` as root, select the event device number that corresponds to "AT Translated Set 2 keyboard" and then perform the action and paste the output here.

At the time the original patch was implemented, we have verified other machines with sys_vendor `Packard*Bell` and product_name `Easynote*` that need the 86->wlan mapping for their WLAN switch hotkey to behave correctly, so we can't simply remove that rule and risk regressing these other machines (which unfortunately we don't have access to anymore).

**Comment by vfjpl** [comment]
@jprvita For example:
Right arrow key
```
Event: time 1556133643.421928, type 4 (EV_MSC), code 4 (MSC_SCAN), value f5
Event: time 1556133643.421928, type 1 (EV_KEY), code 425 (KEY_PRESENTATION), value 1
Event: time 1556133643.421928, -------------- SYN_REPORT ------------
Event: time 1556133643.542071, type 4 (EV_MSC), code 4 (MSC_SCAN), value f5
Event: time 1556133643.542071, type 1 (EV_KEY), code 425 (KEY_PRESENTATION), value 0
Event: time 1556133643.542071, -------------- SYN_REPORT ------------
```
Up arrow key
```
Event: time 1556133643.552063, type 4 (EV_MSC), code 4 (MSC_SCAN), value f4
Event: time 1556133643.552063, type 1 (EV_KEY), code 148 (KEY_PROG1), value 1
Event: time 1556133643.552063, -------------- SYN_REPORT ------------
Event: time 1556133643.737784, type 4 (EV_MSC), code 4 (MSC_SCAN), value f4
Event: time 1556133643.737784, type 1 (EV_KEY), code 148 (KEY_PROG1), value 0
Event: time 1556133643.737784, -------------- SYN_REPORT ------------
```

Mine modalias:
`dmi:bvnPackardBell:bvrV0.22:bd07/11/2007:svnPackardBellBV:pnEasyNoteMZ35:pvr:rvnPackardBellBV:rnEasyNoteMZ35:rvrD3B:cvnPackardBellBV:ct10:cvrN/A:`

Rule that was before:  `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pnEasynote*:pvr*` wasn't triggering on my system because of `pnEasynote*` is different than `pnEasyNoteMZ35`

When it was changed to  `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnPackard*Bell*:pn*` it started triggering on my system. Maybe just include every packardbell laptop except `pnEasyNoteMZ35` then?

**Comment by poettering** [comment]
Let's close this as #12487 has been merged.

**Comment by vfjpl** [comment]
@mschiu77 I see that we are still adding KEYBOARD_KEY_86=wlan for every PackardBell laptop. Is it how you wanted it? As I said, my laptop don't need that. wlan key is controlled in hardware.

I can confirm that arrow keys are working correctly.

**Comment by mschiu77** [comment]
@vfjpl Yes. We still need that rule because we verified that the 2017
PackardBell machines need this rule to get the airplane mode toggle hotkey
work. I think it won't affect your machine. Please let me know if any.
Thanks.
