### ISSUE TITLE
#12055 broke my boot (argc/argv handling and tty password agent)

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#12180]
**systemd version the issue has been seen with**
> current git HEAD

**Used distribution**
 > Exherbo

**Expected behaviour you didn't see**
 > system boots

**Unexpected behaviour you saw**
 > rescue shell, journalctl show this assertion failed: https://github.com/systemd/systemd/blob/c0b471e1970fa6ae523c65aba5c2414a327c3d95/src/tty-ask-password-agent/tty-ask-password-agent.c#L729

**Steps to reproduce the problem**

- update systemd to current git HEAD
- regenerate dracut initrd
- try to boot

Reverting changed introduced in #12055 fixes the boot.

**Comment by yuwata** [comment]
@Keruspe Could you test PR #12182?

**Comment by Keruspe** [comment]
@yuwata works like a charm, thanks!

**Comment by yuwata** [comment]
Thank you for testing the PR.

**Comment by poettering** [comment]
I prepped an alternative fix now in #12183
