### ISSUE TITLE
networkd.service: set NoNewPrivs=yes?

### ISSUE THREAD

**Issue by aburch** [systemd/systemd#1219]
I'm wondering if systemd-networkd.service could set NoNewPrivileges=yes? As far as I understand the documentation it shouldn't execute any external process anyway and thus not need the ability to regain privileges via set[gu]id and the like.

This might also apply to other services like systemd-timesyncd.

**Comment by marcosfrm** [comment]
It is on TODO#L190 .

**Comment by poettering** [comment]
Fix waiting in #10743.
