### ISSUE TITLE
udevadm: attribute-walk incomplete - not showing ATTRS below queue/ subdirectory

### ISSUE THREAD

**Issue by BlueMax** [systemd/systemd#12191]
**systemd version the issue has been seen with**
> systemd 241 (241.67-1-arch)

**Used distribution**
 > Arch Linux 5.0.5-arch1-1-ARCH

**Unexpected behaviour you saw**
 > Some ATTRS not listed

**Steps to reproduce the problem**
`queue/rotational` is not listed:
```
$ udevadm info -a -p /sys/block/sda |grep queue
    ATTRS{queue_ramp_up_period}=="120000"
    ATTRS{queue_type}=="simple"
    ATTRS{queue_depth}=="32"
```
But it's there:
```
$ cat /sys/block/sda/queue/rotational 
1
```
And the rule is working indeed:
```
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
```
There are many more ATTRS candidates in `ls /sys/block/sda/queue` that can be used as udev rule that don't get caught with the above `udevadm` command.

The udevadm man page says:
```
-a, --attribute-walk
Print all sysfs properties of the specified device that can be used
in udev rules to match the specified device. It prints all devices
along the chain, up to the root of sysfs that can be used in udev
rules.
```
So, shouldn't the above `udevadm` command list all sysfs properties indeed (inclusive `queue/rotational` and `queue/scheduler`)?

**Comment by poettering** [comment]
It doesn't go down thre tree. Only up. And queue/ is in a subdirectory.

I figure we can't really fix that as we cannot reasonably discern subdevices from directories such as queue/ that merely group attributes...

**Comment by poettering** [comment]
Quite frankly, I am not sure there's anything actionable here... I am tempted to close this bug hence. Or does anyone have an idea how we sanely could discern such subdirs with only attributes and subdirs-as-sub-devices from each other?

**Comment by yuwata** [comment]
(hence, please drop the 'bug' tag.)

**Comment by kadamski** [comment]
@poettering Wouldn't subdirs-as-sub-devices contain "uevent" file while the subdirs-as-attribute-groups will not? Also, it should not be a symlink. Are there any exceptions from that?
