### ISSUE TITLE
Timed out waiting for device dev-ttyPS0.device occasionally after rebooting box

### ISSUE THREAD

**Issue by hustzhouzhou** [systemd/systemd#12200]
**systemd version the issue has been seen with**
systemd 230
udevd 230

**Used distribution**
Custom

**Unexpected behaviour I saw**
The error showed in /var/log/messages:
Jan  1 00:00:02 fhs daemon.info systemd-networkd[944]: eth0: Gained IPv6LL
Jan  1 00:01:30 fhs daemon.warn systemd[1]: dev-ttyPS0.device: Job dev-ttyPS0.device/start timed out.
Jan  1 00:01:30 fhs daemon.err systemd[1]: Timed out waiting for device dev-ttyPS0.device.
Jan  1 00:01:30 fhs daemon.warn systemd[1]: Dependency failed for Serial Getty on ttyPS0.
Jan  1 00:01:30 fhs daemon.notice systemd[1]: serial-getty@ttyPS0.service: Job serial-getty@ttyPS0.service/start failed with result 'dependency'.
Jan  1 00:01:30 fhs daemon.notice systemd[1]: dev-ttyPS0.device: Job dev-ttyPS0.device/start failed with result 'timeout'.

**systemctl cat serial-getty@ttyPS0.service**

[[0;1;32m�[7m[[0m dev-ttyPS0.device - /dev/ttyPS0
[[0;1;34m# /lib/systemd/system/serial-getty@.service[[0m
This file is part of systemd.
  systemd is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation; either version 2.1 of the License, or
  (at your option) any later version.

[Unit]
Description=Serial Getty on %I
Documentation=man:agetty(8) man:systemd-getty-generator(8)
Documentation=http://0pointer.de/blog/projects/serial-console.html
BindsTo=dev-%i.device
After=dev-%i.device systemd-user-sessions.service plymouth-quit-wait.service
After=rc-local.service

If additional gettys are spawned during boot then we should make
 sure that this is synchronized before getty.target, even though
 getty.target didn't actually pull it in.
Before=getty.target
IgnoreOnIsolate=yes

[Service]
Environment="TERM=xterm"
ExecStart=-/sbin/agetty -8 -L %I 115200 $TERM
Type=idle
Restart=always
RestartSec=0
UtmpIdentifier=%I
TTYPath=/dev/%I
TTYReset=yes
TTYVHangup=yes
KillMode=process
IgnoreSIGPIPE=no
SendSIGHUP=yes

[Install]
WantedBy=getty.target

 udevadm info -qall -p /sys/class/tty/ttyPS0
### P: /devices/platform/amba/ff000000.serial/tty/ttyPS0
N: ttyPS0
E: DEVNAME=/dev/ttyPS0
E: DEVPATH=/devices/platform/amba/ff000000.serial/tty/ttyPS0
E: MAJOR=248
E: MINOR=0
E: SUBSYSTEM=tty

And no corresponding c248:0 and c248:1 under directory /run/udev/data/

When the problem happened, it can be recovered by the command
"udevadm trigger /sys/devices/platform/amba/ff000000.serial/tty/ttyPS0"

**How to reproduce, possible sources**
Reboot box. The frequency is about 1 of 40 times' reboot.

**Comment by poettering** [comment]
systemd only marks .device units as up whose corresponding udev database entry has a "systemd" tag. The tag is applied in 99-systemd.rules to many generic serial ports in this line:

```
SUBSYSTEM=="tty", KERNEL=="tty[a-zA-Z]*|hvc*|xvc*|hvsi*|ttysclp*|sclp_line*|3270/tty[0-9]*", TAG+="systemd"
```

the tag apparently didn't get added on your device, as the "udevadm info" shows. You need to figure out why. Maybe the device is not properly triggered on your system (systemd-udev-trigger.service does that normally early during boot)

**Comment by yuwata** [comment]
> **systemd version the issue has been seen with**
> systemd 230
> udevd 230

Too old...
