### ISSUE TITLE
systemd-networkd not sending DHCPv6 solicit message

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#12224]
**systemd version the issue has been seen with**
systemctl --version
systemd 237
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK +SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid
 > …
systemd-networkd should send the solicit message, and subsequently acquire the dhcp ipv6 address.
 > …
systemd-networkd not sending DHCPv6 solicit message.
 > …

My conf file is as below :  /etc/systemd/network/00-bmc-eth0.network

[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
DHCP=yes
IPv6AcceptRA=yes
[Route]

I tried changing the DHCP to DHCP=ipv6 as well.

**Comment by poettering** [comment]
This upstream bug tracker is only for the two most recently released systemd versions, i.e. 240 and 241 right now. Please test on one of those versions before reporting here. For everything else please contact your downstream distro first, thanks!

**Comment by poettering** [comment]
(and the issue submission form should have made that really really clear)
