### ISSUE TITLE
Mount /var/lib/systemd/coredump/ with archivemount out of the box

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#12237]
Systemd stores compressed coredumps, but gdb cannot open compressed coredumps.  Please fuse-mount /var/lib/systemd/coredump/ somewhere, with archivemount or a like, so that storing and opening coredumps does not need explicit unpacking.

For the record, here is a PR to add support in gdb to read compressed coredumps: https://sourceware.org/bugzilla/show_bug.cgi?id=15989

**Comment by poettering** [comment]
I am sorry, but FUSE for such things is always going to be a hack. I think we already provide a much nicer approach in "coredumpctl debug" which will decompress the coredump and invoke gdb with the right parameters. (including the binary path and so on). I'd argue that coredumpctl is a much ncier interface for that than FUSE... 

I hope that makes sense? Let's close this hence

**Comment by dilyanpalauzov** [comment]
Yes, coredumpctl sufficies, I wasn’t aware of it.
