### ISSUE TITLE
systemd-inhibit: Failed to execute : No such file or directory

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#12246]
**systemd version the issue has been seen with**
> 242 RC3

**Used distribution**
 > Fedora 31

**Expected behaviour you didn't see**
 > Execute commands with inhibit

**Unexpected behaviour you saw**
 > Cannot execute commands with inhibit

**Steps to reproduce the problem**
$ systemd-inhibit true
Failed to execute : No such file or directory
true failed with exit status 1.

**Comment by poettering** [comment]
Fix waiting in #12249
