### ISSUE TITLE
PATH is not updated from environment.d

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#12259]
**systemd version the issue has been seen with**
> .systemd 239
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Lubuntu 18.10

**Expected behaviour you didn't see**
 > The $PATH variable being updated.

**Unexpected behaviour you saw**
 > The $PATH remains the same.

**Steps to reproduce the problem**
I've added following to `~/.config/environment.d/00-default.conf`:
```
PATH=$HOME/.local/bin:$PATH
EDITOR=emacsclient
VISUAL=$EDITOR
```
The latter variables are set as expected:
```
~ % systemctl --user show-environment|grep emacs
EDITOR=emacsclient
VISUAL=emacsclient
```
but the PATH isn't:
```
~ % systemctl --user show-environment|grep PATH
DEFAULTS_PATH=/usr/share/gconf/Lubuntu.default.path
MANDATORY_PATH=/usr/share/gconf/Lubuntu.mandatory.path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
```
The reason seems to be that it's somehow ignored by generators:
```
~ % /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
EDITOR=emacsclient
VISUAL=emacsclient
```
The syntax seems to match https://www.freedesktop.org/software/systemd/man/environment.d.html

Is there some kind of debug log for 30-systemd-environment-d-generator to figure out what's causing it to ignore $PATH? The https://www.freedesktop.org/software/systemd/man/systemd-environment-d-generator.html looks rather empty.

**Comment by poettering** [comment]
We generally only track issues with the two most recently released systemd versions here. That's 240 and 241 right now. For everything else please contact your downstream distro instead.

Since the env var handling received major changes since 239 please test this with 241 hence.

**Comment by zabbal** [comment]
I've tried it with ubuntu 19.04 which uses systemd 240 and I got exactly the same results.

**Comment by keszybz** [comment]
I tested this, and I get the correct result with latest master, but also with v240 as well. So maybe it's some typo in your setup or ~/.config is configured differently or something.

I'll submit a PR to enhance the logging at debug level:
```console
$ SYSTEMD_LOG_LEVEL=debug build-rawhide/30-systemd-environment-d-generator
Looking for environment.d files in (higher priority first):
	/home/zbyszek/.config/environment.d
	/etc/environment.d
	/run/environment.d
	/usr/local/lib/environment.d
	/usr/lib/environment.d
Loading /home/zbyszek/.config/environment.d/00-default.conf…
/home/zbyszek/.config/environment.d/00-default.conf:2: setting PATH=/home/zbyszek/.local/binXX:/home/zbyszek/.local/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/home/zbyszek/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin
/home/zbyszek/.config/environment.d/00-default.conf:3: setting EDITOR=emacs -nw
/home/zbyszek/.config/environment.d/00-default.conf:4: setting VISUAL=emacs -nw
Loading /usr/lib/environment.d/99-environment.conf…
Loading /usr/lib/environment.d/990-snapd.conf…
/usr/lib/environment.d/990-snapd.conf:2: setting PATH=/home/zbyszek/.local/binXX:/home/zbyszek/.local/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/home/zbyszek/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/var/lib/snapd/snap/bin
PATH=/home/zbyszek/.local/binXX:/home/zbyszek/.local/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/home/zbyszek/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/var/lib/snapd/snap/bin
EDITOR="emacs -nw"
VISUAL="emacs -nw"
```

**Comment by xtexChooser** [comment]
@keszybz hey, I tested with debug level and found that some variables are set correctly:
```
PATH=/opt/zvm/bin:/opt/zvm/self:/home/xtex/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin
SDKMAN_DIR=/opt/sdkman
SSH_ASKPASS=/usr/bin/ksshaskpass
```
however, the other variables are working but these three variables are not set.

**Comment by romuald** [comment]
@keszybz thanks for the log, it helped a lot while trying to figure this out

For anyone ending up here trying to setup their PATH environment variable locally:

At least on Ubuntu 24 the `/usr/lib/environment.d/99-environment.conf` file will reset the PATH variable and drop any change made in `~/.config/environment.d`
