### ISSUE TITLE
systemd-coredump won't clean corefile after reboot

### ISSUE THREAD

**Issue by ddkdhans** [systemd/systemd#12256]
i have set maxUse and KeepFree, but it doesn't work. everytime i reboot my device,the corefile locate at /var/lib/systemd/coredump will be more and more. how can i solve this problem?

**Comment by poettering** [comment]
Sorry, but this is not a useful bug report. Please fill in the supplied issue form, it exists for a reason. We try to make very clear during issue submission that we need the data included, and it's not cool to just ignore that.

Moreover, your question appears more like a support question than a real bug report. Hence, please contact the amiling list for help anyway, not this bug tracker.
