### ISSUE TITLE
during upgrades, spurious messages "Current command vanished from the unit file"

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#12258]
On F29 or F30, I see those quite often:
Apr 09 14:51:33 fedora systemd[1]: getty@tty1.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Apr 09 14:51:33 fedora systemd[1]: man-db-cache-update.service: Current command vanished from the unit file, execution of the command list won't be resumed.

The last time getty@.service was modified was in db6aedab9292678918f15807a0d835be35511667, May 2017, so I think our detection of changed commands is somehow off.

**Comment by MichaIng** [comment]
I also face this on Raspberry Pi with systemd version 241-3+rpi1 on several services in boot log (journalctl).

Bug I could not see any related error/issue. Some of those services (custom ones) create logs and according to them those have fully finished all their tasks. So not sure why this message is shown, especially where services explicitly `exit 0` as last step, which, according to the logs, has been definitely reached.

**Comment by kkm000** [comment]
FWIW, I am getting the same message on every `systemctl daemon-reload` for the `serial-getty@ttyS2.service` unit. This is the only getty I have.

No-frills Debian 10 x64 VM, generic (non-VM) kernel.

```
$ uname -a
Linux localhost 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
$ systemd --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```
The command did not vanish in the end, if I understand what systemd is complaining about
```
$ systemctl show serial-getty@ttyS2.service | grep ^ExecStart
ExecStart={ path=/sbin/agetty ; argv[]=/sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS2 $TERM ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
```
The unit is explicitly enabled, not generated.

**Comment by kkm000** [comment]
Ok, I think I see something interesting. Output of `systemctl show` is wrapped for clarity. Note that the `pid =` in this output changed from the correct PID to 0 after `daemon-reload`.
```
$ systemctl stop serial-getty@ttyS2.service
$ ps ax | grep agetty
  783 pts/0    S+     0:00 grep --color=auto agetty
$ systemctl start serial-getty@ttyS2.service
$ systemctl show serial-getty@ttyS2.service | grep ^ExecStart
ExecStart={ path=/sbin/agetty ; 
   argv[]=/sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS2 $TERM ; 
   ignore_errors=yes ; start_time=[Sat 2019-07-06 00:07:05 PDT] ; stop_time=[n/a] ;
   pid=786 ; <<<<< NOW IT'S THERE
   code=(null) ; status=0/0 }
$ systemctl daemon-reload
$ systemctl show serial-getty@ttyS2.service | grep ^ExecStart
ExecStart={ path=/sbin/agetty ; 
   argv[]=/sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS2 $TERM ; 
   ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; 
   pid=0 ;  <<<< NOW IT'S NOT!
   code=(null) ; status=0/0 }
$ systemctl status serial-getty@ttyS2.service
● serial-getty@ttyS2.service - Serial Getty on ttyS2
   Loaded: loaded (/lib/systemd/system/serial-getty@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-07-06 00:07:05 PDT; 53s ago
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html
 Main PID: 786 (agetty)
    Tasks: 1 (limit: 1962)
   Memory: 280.0K
   CGroup: /system.slice/system-serial\x2dgetty.slice/serial-getty@ttyS2.service
           └─786 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS2 vt220

Jul 06 00:07:05 xa-login systemd[1]: Started Serial Getty on ttyS2.
Jul 06 00:07:27 xa-login systemd[1]: serial-getty@ttyS2.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

**Comment by kkm000** [comment]
Oh, and this is a single-thread virtual CPU VM, thus no hardware concurrency. Just thought I'd mention this--multi-CPU races are sometimes trickier to track down.

**Comment by dimitris-triantafyllidis** [comment]
I got this earlier today during upgrading from 249.7-2 to 250-1 on Arch Linux:
```
$ journalctl -b -1 | grep vanished
Dec 27 15:18:29 dtr-pc systemd[1]: getty@tty1.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Dec 27 15:18:29 dtr-pc systemd[1]: getty@tty3.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Dec 27 15:18:29 dtr-pc systemd[1]: getty@tty2.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```
I only checked the logs because the ttys seemed to behave kind of strangely, i.e. tty numbers no longer appear at the top of the screen (I get a `(-)` instead of `(ttyX)`) and there is also a 4-5 second delay before the login prompt appears after typing `exit`. I am not quite sure whether this behavior actually started today and whether it is related though.
