### ISSUE TITLE
 systemctl cat 'foo*' (using shellglob patterns) only lists active units

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#12273]
This is copied verbatim from the downstream bug report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904913

Package: systemd
Version: 239-7
Severity: normal

Hi,

I think this behavior is wrong, or at least confusing:

```
 root@debian-sid01:~# systemctl cat ssh.service
 # /lib/systemd/system/ssh.service
 [Unit]
 Description=OpenBSD Secure Shell server
 Documentation=man:sshd(8) man:sshd_config(5)
 After=network.target auditd.service
 ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

 [Service]
 EnvironmentFile=-/etc/default/ssh
 [...]
 root@debian-sid01:~# systemctl status ssh.service
 ● ssh.service - OpenBSD Secure Shell server
    Loaded: loaded (/lib/systemd/system/ssh.service; disabled; vendor preset: enabled)
    Active: inactive (dead)
      Docs: man:sshd(8)
            man:sshd_config(5)

 Jul 29 15:02:10 debian-sid01 systemd[1]: Starting OpenBSD Secure Shell server...
 Jul 29 15:02:10 debian-sid01 sshd[414]: Server listening on 0.0.0.0 port 22.
 Jul 29 15:02:10 debian-sid01 sshd[414]: Server listening on :: port 22.
 Jul 29 15:02:10 debian-sid01 systemd[1]: Started OpenBSD Secure Shell server.
 Jul 29 15:03:01 debian-sid01 sshd[414]: Received signal 15; terminating.
 Jul 29 15:03:01 debian-sid01 systemd[1]: Stopping OpenBSD Secure Shell server...
 Jul 29 15:03:01 debian-sid01 systemd[1]: Stopped OpenBSD Secure Shell server.
 root@debian-sid01:~# systemctl cat 'ssh*'
 root@debian-sid01:~#
```
When using a (shellglob) "PATTERN" (quoting from manpage) as
demonstrated above with 'ssh*', this seems to apply only to *active*
units. Thanks to Felipe Sateler nowadays I'm aware of the unit
garbage collection (see `LESS='+/UNIT\ GARBAGE\ COLLECTION' man
systemd.unit` in more recent systemd versions), though the behavior
is still confusing/inconsistent to me.

Shouldn't either:

1) "systemctl cat ssh.service" NOT list its unit if it's not running, or
2) "systemctl cat 'ssh*'" *list* its unit file even if it's not running,
but known to the sysstem (since `systemctl cat ssh.service` lists it too)?

**Comment by mbiebl** [comment]
Still reproducible with v241, fwiw

**Comment by mrc0mmand** [comment]
I'd just add that this affects all `systemctl` verbs, not only the `cat` one:

```
$ systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:sshd(8)
           man:sshd_config(5)

## Non-glob version
$ for verb in status cat show; do systemctl $verb sshd | head -n3; echo $?; done
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
0
# /usr/lib/systemd/system/sshd.service
[Unit]
Description=OpenSSH server daemon
0
Type=notify
Restart=on-failure
NotifyAccess=main
0

## Glob version
$ for verb in status cat show; do systemctl $verb ssh* | head -n3; echo $?; done
0
0
0
```

**Comment by mrc0mmand** [comment]
Also, as a *workaround*, you can use either `systemctl --state=inactive,dead status ssh*` or `systemctl --all status ssh*`

**Comment by keszybz** [comment]
I think cat with a glob makes limited sense, but in the narrow case where we know that there's a few units that match a pattern, it can be useful.
We can divide units into three categories: loaded/active, loaded/inactive, not loaded. So @mrc0mmand's patch will show the first two categories, but does nothing for the third. This might be OK.

A bigger change would be to make cat with a glob behave more like `list-unit-files`, and load all units that match a pattern from disk.

**Comment by mrc0mmand** [comment]
Fixed by https://github.com/systemd/systemd/commit/4eb5312079962fceb22c1b730087d724d02fee8b.
