### ISSUE TITLE
udev-rules: give permissions to /dev/udmabuf

### ISSUE THREAD

**Issue by elmarco** [systemd/systemd#12283]
Hi,

I am not sure which permissions should be granted to the udmabuf device (added in 4.20 kernel)

I suppose the "video" group would be fine.

**Comment by elmarco** [comment]
@kraxel any idea? thanks

**Comment by poettering** [comment]
Please provide a patch for this one, I don#t even know what udmabuf really is...

**Comment by keszybz** [comment]
IIUC, the main user will be qemu. Maybe we should make this owned by 'kvm', like /dev/kvm?

**Comment by kraxel** [comment]
group "kvm" would be a better fit than "video" I think, at least for the qemu use case.

udmabuf allows userspace to compose dma-bufs from memfd memory.
qemu wants use that to create host dma-bufs for guest graphics buffers.
I wouldn't be surprised if people find this useful for other cases too though.

**Comment by poettering** [comment]
@kraxel is this stuff useful for anything but video I/O? is this useful for anything but VM environments?

if only useful in context of video I/O it should probably be in the "video" group. If only useful in the context of VM stuff it should be in the "kvm" group...

And I presume you want an access mode of 0660?

**Comment by elmarco** [comment]
@kraxel fwiw, I experimented with it for vhost-user-gpu, and it seems to work (https://lists.nongnu.org/archive/html/qemu-devel/2019-04/msg02197.html). I think the group "video" is more appropriate.

**Comment by kraxel** [comment]
> @kraxel is this stuff useful for anything but video I/O? is this useful for anything but VM environments?

Both ;)
It's about displaying the guest video output on the host.

> And I presume you want an access mode of 0660?

Yes.

**Comment by poettering** [comment]
So, which kind of processes will end up opening these devices? qemu? or some display manger/wayland thingy? If the former, it should be "kvm", if the latter it should be "video" i guess...

Also, if qemu also gets access to other video hw would that be worse than display managers getting access to /dev/kvm? if it would we worse, then "kvm" would be right, otherwise "video"...

**Comment by kraxel** [comment]
> So, which kind of processes will end up opening these devices? qemu?

Yes, qemu.

**Comment by poettering** [comment]
So if it's only going to be "qemu" in clean codepaths, then I figure it should be owned by "kvm"
