### ISSUE TITLE
Systemd 239 loses timer configuration information upon reboot

### ISSUE THREAD

**Issue by noloader** [systemd/systemd#12297]
I am working on Fedora 29 x86_64 Server fully patched. The server provides Systemd 239. I have a timer that should fire once an hour. The timer starts a service, and the service runs a Bash script. The script takes about 10 seconds to run and then exits.

Each time I update Fedora and reboot the machine I have to `systemctl enable ftc-data.timer` and then `systemctl start ftc-data.timer`. For whatever reason Systemd does not persist the information.

This may be related to [Issue 6680, .timer doesn't fire](https://github.com/systemd/systemd/issues/6680). I can provide remote access to the server if needed. For remote access I need a SSH public key; email to *noloader*, gmail account.

-----

Here's the code for the ftc-data timer. The damn thing about it is, I have another timer/service to update Let's Encrypt certificates, and it works as expected. The ftc-data is damn near a copy/paste of Let's Encrypt.

```
# cat /etc/systemd/system/ftc-data.timer
[Unit]
Description=Run ftc-data.service every hour

[Timer]
OnCalendar=00/1:00
RandomizedDelaySec=600
Persistent=true

[Install]
WantedBy=timers.target
```

And after reboot:

```
# systemctl list-timers > ~/systemd.txt
# cat ~/systemd.txt
NEXT                         LEFT                LAST                         PASSED             UNIT                         ACTIVATES
Fri 2019-04-12 10:03:23 EDT  50min left          Fri 2019-04-12 09:03:18 EDT  9min ago           dnf-makecache.timer          dnf-makecache.service
Fri 2019-04-12 10:26:18 EDT  1h 13min left       Thu 2019-04-11 10:26:18 EDT  22h ago            systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Sat 2019-04-13 00:00:00 EDT  14h left            Fri 2019-04-12 00:00:18 EDT  9h ago             mlocate-updatedb.timer       mlocate-updatedb.service
Sat 2019-04-13 00:00:00 EDT  14h left            Fri 2019-04-12 00:00:18 EDT  9h ago             unbound-anchor.timer         unbound-anchor.service
Mon 2019-04-22 02:41:30 EDT  1 weeks 2 days left Tue 2019-03-26 14:42:17 EDT  2 weeks 2 days ago renew-letsencrypt.timer      renew-letsencrypt.service

5 timers listed.
```

And:

```
# systemctl status ftc-data.timer > ~/systemd.txt
# cat ~/systemd.txt
? ftc-data.timer - Run ftc-data.service every hour
   Loaded: loaded (/etc/systemd/system/ftc-data.timer; enabled; vendor preset: disabled)
   Active: inactive (dead)
  Trigger: n/a
```

**Comment by arvidjaar** [comment]
You may have dependency loop in which case systemd may drop job for some unit. Log after booting with `systemd.log_level=debug printk.devkmsg=on` may provide some hints.

**Comment by poettering** [comment]
Please provide boot-time logs (ideally with debugging on). Also please provide "systemctl show -p Wants timers.target" output (which shows whether the dep was properly created)

Also, please check whether /etc/systemd/system/timers.target.wants/ contains the symlink to the timer unit properly

**Comment by poettering** [comment]
Closing due to lack of response
