### ISSUE TITLE
pam_systemd prints debug messages to default log level when you do a systemctl mask user@`id -u joe`.service runtime-user-dir@`id -u joe`.service

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#12294]
**systemd version the issue has been seen with**
> ...
242 RC3

**Used distribution**
 > …
Fedora Rawhide

**Expected behaviour you didn't see**
 > …
No debug messages in default log level

**Unexpected behaviour you saw**
 > …
pam_systemd is printing debug messages about how it cannot stat() /run/user/`id -u joe` and it warns me about how it is not setting up XDG_RUNTIME_DIR env variable because /run/user/`id -u joe` is not set up properly. These messages should probably be downgraded to debug as i fully understand what it means to disable the runtime-user-dir for user joe.

**Steps to reproduce the problem**
```
useradd joe
passwd joe
systemctl mask user@`id -u joe`.service runtime-user-dir@`id -u joe`.service
ssh joe@localhost
journalctl --grep pam_systemd
```

**Comment by poettering** [comment]
well, humm, maybe you understand that, but I am not sure "debug" is appropriate for that. It looks like misconfiguration and misconfiguration should be logged above debug logging I think

**Comment by doverride** [comment]
Why is this misconfiguration? If i have a sftp-only user, then i do not need 1. a systemd --user instance for tthis user 2, a xdg runtime directory for this user.

Why would user@service and runtime-user-dir@service be tunable otherwise? Arent you suppose to be able to mask these?

**Comment by boucman** [comment]
should you use pam_systemd for that type of non-interactive session ? (this is a legitimate question, i'm not 100% sure when pam_systemd should or should-not be included in the pam stack)

**Comment by poettering** [comment]
> should you use pam_systemd for that type of non-interactive session ? (this is a legitimate question, i'm not 100% sure when pam_systemd should or should-not be included in the pam stack)

yes, all code of regular users should go through pam_systemd. If you don#t it's a security problem since it enables the user to run code without resource management for the user applied.

**Comment by poettering** [comment]
well, support for masking user@.service and runtime-user-dir@.service is not really supported. Yes, you mostly get away with in in many cases, but it's not entirely supported. It will break at many othe rplaces, because you make essential functionality unavailable. So yes, I think we should warn about this, but proceed anyway, like we currently do.

**Comment by doverride** [comment]
On Thu, Jun 20, 2019 at 06:41:54AM -0700, Lennart Poettering wrote:
> well, support for masking user@.service and runtime-user-dir@.service is not really supported. Yes, you mostly get away with in in many cases, but it's not entirely supported. It will break at many othe rplaces, because you make essential functionality unavailable. So yes, I think we should warn about this, but proceed anyway, like we currently do.

There use to be similar debug messages at default log level for user@.service too, but those we're downgraded (back then user-runtim-dir@.service did not exist) I do not see how user-runtime-dir@.service is any different.
xdg-runtime-dir is a desktop thing, so on a headless server you should be able to do without just fine, provided that you also mask user@.service

Regardless i respect your decision

> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/12294#issuecomment-504030418

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift
