### ISSUE TITLE
udev: RUN assignments and PROGRAM results

### ISSUE THREAD

**Issue by atar-axis** [systemd/systemd#12291]
This bug report is based on the latest sourcecode of udev, I had a really hard time to debug my [udev rule](https://github.com/atar-axis/xpadneo/issues/91) and therefore had a closer look into the sourcecode.

**The first set of issues is about the `RUN` key**

Problematic code: [here](https://github.com/systemd/systemd/blob/15de23a0b24f6073d527c6a8c22556ad5101a160/src/udev/udev-rules.c#L2442)

1. <strike>Final assignments on the `RUN` key cannot work. This is because `event->run_final` exists, but is never set or checked. I therefore suggest to add the following:
    ```
    if (event->run_final)
        break;
    if (cur->key.op == OP_ASSIGN_FINAL)
        event->run_final = true;
    ```
    If this behaviour is intended, then please document it :blush:
   </strike> (fixed by [PR](https://github.com/systemd/systemd/pull/12309))

2. <strike>Using `=` or `:=` on the `RUN{builtin}` key does clear the whole `event->run_list`, even `RUN{program}` entries (and vice versa). This is not documented either. I suggest to separate both `RUN` commands or documenting this behaviour.</strike> (fixed by [PR](https://github.com/systemd/systemd/pull/12310))

3. <strike>It should be documented that `RUN` commands are not executed sequentially</strike> (fixed by https://github.com/systemd/systemd/pull/11891/commits/541d8bd4b18a4b97a381ae6caea4aba2baaa063c)

**The next issue is about the `PROGRAM` and `RESULT` keys**

Imagine the following situation:
* You have two different rules, both fire on the same uevent.
* Both rules have an `PROGRAM` command and both are using the `$result` variable in their `RUN` commands.

Now the problem is, that the `PROGRAM` commands are executed before the `RUN` commands, meaning that the second rule is overriding the `$result` of the first one.
Therefore the `RUN` command of the first rule does now have the `$result` of `PROGRAM` of the second rule.

I suggest to evaluate `PROGRAM` first and replacing the `$result` variable in `RUN` commands before it gets added to the `event->run_list`. At the moment the substitution does happen shortly before execution, see [here](https://github.com/systemd/systemd/blob/3661dc349ec0e0e8f19fb3a542ccbc813753ef8b/src/udev/udev-event.c#L907). Otherwise, please document this behaviour! :relaxed:

**Comment by poettering** [comment]
BTW, consider submitting code changes as PRs!

**Comment by atar-axis** [comment]
I will do so if somebody confirms my points, maybe I have overlooked something

**Comment by yuwata** [comment]
>     3. It should be documented that `RUN` commands are not executed sequentially

Which version do you use? I found the issue and I think it is already fixed by #11891, which is included in v242 and already [backported](335c248f0a0df88dffdc8f7e5e5695312a7d81aa) in v241-stable repository.

**Comment by atar-axis** [comment]
I am on v241, this is the only thing I haven't checked in the source.
But I am not sure whether we talk about the same thing or not, what I mean is that if you add some than one `RUN` command using the `+=` operator, then you cannot be sure that the first command is finished before the second starts.

**Comment by yuwata** [comment]
> I am on v241 (according to `udevadm --version`), 

Thanks.

**Comment by atar-axis** [comment]
"3." Seems to be the same issue in fact so I stroke it out in my first post. Thanks!

**Comment by yuwata** [comment]
Thank you for confirming that.

**Comment by yuwata** [comment]
Closed with #12309 and #12310.

**Comment by atar-axis** [comment]
There is a Last point open :)

**Comment by yuwata** [comment]
I came back to this issue. 

> **The next issue is about the `PROGRAM` and `RESULT` keys**

> Imagine the following situation:
> * You have two different rules, both fire on the same uevent.
> * Both rules have an `PROGRAM` command and both are using the `$result` variable in their `RUN` commands.

> Now the problem is, that the `PROGRAM` commands are executed before the `RUN` commands, meaning that the second rule is overriding the `$result` of the first one.
> Therefore the `RUN` command of the first rule does now have the `$result` of `PROGRAM` of the second rule.

> I suggest to evaluate `PROGRAM` first and replacing the `$result` variable in `RUN` commands before it gets added to the `event->run_list`. At the moment the substitution does happen shortly before execution, see [here](https://github.com/systemd/systemd/blob/3661dc349ec0e0e8f19fb3a542ccbc813753ef8b/src/udev/udev-event.c#L907).

That sounds reasonable for me. But changing that may break backward compatibility...

**Comment by atar-axis** [comment]
Hum, I would think that backwards compatibility is not a thing here because this behaviour is absolutely not what you would expect. Not changing that feels like keeping a bug because some ppl. already implemented a workaround.

Anyhow, at least es should document it, right? 😊

**Comment by yuwata** [comment]
I've posted a commit in #12416 which adds an option to evaluate `RUN=` rules earlier. PTAL.

**Comment by atar-axis** [comment]
Ah nice, thank you for the information! But Is there a way to determine which one (early/late) is set? For someone who delivers udev rules this adds even more uncertainty of how the rule is executed :) there should be exactly one way in my eyes, and this one should be documented :)

**Comment by yuwata** [comment]
Thank you for the comments. I will add a log message about the option, and update man page.

**Comment by atar-axis** [comment]
Thanks! So then I think this issue is completely covered now :grin:
