### ISSUE TITLE
install: systemctl preset-all does not work with --root= option

### ISSUE THREAD

**Issue by wblaszcz** [systemd/systemd#12304]
**systemd version the issue has been seen with**
242

**Used distribution**
 LFS

**Expected behaviour you didn't see**
After booting system the login prompt should come up

**Unexpected behaviour you saw**
Boot process stops at
Starting Update UTMP about System Runlevel Changes...

**Steps to reproduce the problem**
build and install from tarball systemd-242.tar.gz, then boot system.
Same build process for version 241 works with no issue.

**Further info**
Looks like nothing is created under /etc/systemd/system except for two empty directories, getty.target.wants and multi-user.target.wants .

Creating the following symlink fixes the immediate issue.

ln -s /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service

**Comment by yuwata** [comment]
From v242, you need to run `systemctl preset-all` or enable services by hand. See https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/NEWS#L223-L230.

**Comment by wblaszcz** [comment]
`systemctl preset-all` does not work in my case.
I build and install systemd as a non-root user to a non standard prefix, /tools.
`systemctl --root=/  preset-all` not only creates symlinks for unit files that are under /tools, but also from the main host system which I do not want.
`systemctl --root=/tools  preset-all` does something strange in that not only does it try to create links under /tools/tools/.. but returns with some kind of failures like
`Failed to preset unit, file /tools/tools/etc/systemd/system/ctrl-alt-del.target already exists and is a symlink to /lib/systemd/system/poweroff.target.`
The above was done from a clean /tool directory.
BTW, /tools is a symlink to /home/lfs/tools.
`systemctl --root=/home/lfs/tools  preset-all` doesn't come back with any failures but still tries to create things under tools/tools/....
I just don't get it as far as what the --root= option should be doing.
How do I get unit files that are under /tools linked from /tools/etc/systemd/system?

Thanks.

**Comment by yuwata** [comment]
Maybe, a workaround for this is chroot to /tool and run `systemctl preset-all` without `--root=` option.

**Comment by wblaszcz** [comment]
Please ignore my previous comment. There were two factors involved, 1) PATH and 2) the assumption that --root was the same as --prefix.
The PATH affected which systemctl was being used, the system one or the just built one.
--prefix is relative to --root. --prefix was set to /tools.
So my final systemctl command looks like this:
`/tools/bin/systemctl --root=/home/lfs preset-all` where /tools is a symlink to /home/lfs/tools
which pretty much gives me what I want.

However I still think there is a bug in that above command which still produces errors.

```
/tools/bin/systemctl --root=/home/lfs preset-all
Created symlink /home/lfs/tools/etc/systemd/system/sysinit.target.wants/debug-shell.service → /tools/lib/systemd/system/debug-shell.service.
Created symlink /home/lfs/tools/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /tools/lib/systemd/system/systemd-networkd-wait-online.service.
Created symlink /home/lfs/tools/etc/systemd/system/ctrl-alt-del.target → /tools/lib/systemd/system/poweroff.target.
Created symlink /home/lfs/tools/etc/systemd/system/dbus-org.freedesktop.resolve1.service → /tools/lib/systemd/system/systemd-resolved.service.
Created symlink /home/lfs/tools/etc/systemd/system/multi-user.target.wants/systemd-resolved.service → /tools/lib/systemd/system/systemd-resolved.service.
Created symlink /home/lfs/tools/etc/systemd/system/dbus-org.freedesktop.timesync1.service → /tools/lib/systemd/system/systemd-timesyncd.service.
Created symlink /home/lfs/tools/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service → /tools/lib/systemd/system/systemd-timesyncd.service.
Created symlink /home/lfs/tools/etc/systemd/system/multi-user.target.wants/remote-fs.target → /tools/lib/systemd/system/remote-fs.target.
Created symlink /home/lfs/tools/etc/systemd/system/multi-user.target.wants/machines.target → /tools/lib/systemd/system/machines.target.
Failed to preset unit, file /home/lfs/tools/etc/systemd/system/ctrl-alt-del.target already exists and is a symlink to /tools/lib/systemd/system/poweroff.target.
Created symlink /home/lfs/tools/etc/systemd/system/getty.target.wants/getty@tty1.service → /tools/lib/systemd/system/getty@.service.
Failed to preset unit, file /home/lfs/tools/etc/systemd/system/ctrl-alt-del.target already exists and is a symlink to /tools/lib/systemd/system/poweroff.target.
Failed to preset unit, file /home/lfs/tools/etc/systemd/system/ctrl-alt-del.target already exists and is a symlink to /tools/lib/systemd/system/poweroff.target.
Created symlink /home/lfs/tools/etc/systemd/system/boot-complete.target.requires/systemd-boot-check-no-failures.service → /tools/lib/systemd/system/systemd-boot-check-no-failures.service.
Created symlink /home/lfs/tools/etc/systemd/system/getty.target.wants/console-getty.service → /tools/lib/systemd/system/console-getty.service.
Created symlink /home/lfs/tools/etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /tools/lib/systemd/system/systemd-networkd.socket.
Created symlink /home/lfs/tools/etc/systemd/system/dbus-org.freedesktop.network1.service → /tools/lib/systemd/system/systemd-networkd.service.
Created symlink /home/lfs/tools/etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /tools/lib/systemd/system/systemd-networkd.service.
Created symlink /home/lfs/tools/etc/systemd/system/sysinit.target.wants/systemd-time-wait-sync.service → /tools/lib/systemd/system/systemd-time-wait-sync.service.
Failed to preset unit, file /home/lfs/tools/etc/systemd/system/ctrl-alt-del.target already exists and is a symlink to /tools/lib/systemd/system/poweroff.target.

```
The Failed to preset unit error does not make sense. It implies that the ctrl-alt-del.target is created 5 times?

**Comment by poettering** [comment]
It's not supported to set the prefix to anything other than /usr. This is documented explicitly in README.

systemd is not an app you can install at arbitrary places, it's a core part of the OS, hence we make stricter requirements there.

Sorry.
