### ISSUE TITLE
Problem accessing systemd-resolved from a user namespace

### ISSUE THREAD

**Issue by Perdu** [systemd/systemd#12318]
**systemd version the issue has been seen with**
> 241.93-1-arch

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > Resolving domain name from a user space

**Steps to reproduce the problem**
Hello,
I submitted a bug to the lxc project, and it seems the bug ultimately comes from systemd-resolved. The script lxc-download calls wget from a user namespace, and this wget fails to resolve a DNS domain, while calling wget manually does not create this issue. See these 2 comments for more details:
https://github.com/lxc/lxc/issues/2931#issuecomment-482488447
https://github.com/lxc/lxc/issues/2931#issuecomment-482876559

**Comment by poettering** [comment]
I am pretty sure this is fixed already by #11785 which is included in v242. Please update. If the problem persists, please reopen.
