### ISSUE TITLE
Broken build: error: invalid use of undefined type ‘struct ethhdr’

### ISSUE THREAD

**Issue by Werkov** [systemd/systemd#12319]
**systemd version the issue has been seen with**
> master 4d48eabf3781c17c22649f11c4bb287d7de434be
> glibc-2.26-lp150.11.9.1.x86_64
> linux-glibc-devel-4.15-lp150.1.23.noarch
> kernel 4.12.14-lp150.12.48-default

**Used distribution**
 > openSUSE Leap

**Expected behaviour you didn't see**
 > Build succeeds.

**Unexpected behaviour you saw**
> FAILED: src/libsystemd-network/src@libsystemd-network@@systemd-network@sta/lldp-network.c.o 
> ccache cc -Isrc/libsystemd-network/src@libsystemd-network@@systemd-network@sta -Isrc/libsystemd-network -I../src/libsystemd-network -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -include config.h -fPIC  -MD -MQ 'src/libsystemd-network/src@libsystemd-network@@systemd-network@sta/lldp-network.c.o' -MF 'src/libsystemd-network/src@libsystemd-network@@systemd-network@sta/lldp-network.c.o.d' -o 'src/libsystemd-network/src@libsystemd-network@@systemd-network@sta/lldp-network.c.o' -c ../src/libsystemd-network/lldp-network.c
> In file included from ../src/libsystemd-network/lldp-network.c:3:0:
> ../src/libsystemd-network/lldp-network.c: In function ‘lldp_network_bind_raw_socket’:
> ../src/libsystemd-network/lldp-network.c:14:52: error: invalid use of undefined type ‘struct ethhdr’
>                  BPF_STMT(BPF_LD + BPF_W + BPF_ABS, offsetof(struct ethhdr, h_dest)),      /* A <- 4 bytes of destination MAC */
>                                                     ^
> ../src/libsystemd-network/lldp-network.c:17:52: error: invalid use of undefined type ‘struct ethhdr’
>                  BPF_STMT(BPF_LD + BPF_H + BPF_ABS, offsetof(struct ethhdr, h_dest) + 4),  /* A <- remaining 2 bytes of destination MAC */
>                                                     ^
> ../src/libsystemd-network/lldp-network.c:22:52: error: invalid use of undefined type ‘struct ethhdr’
>                  BPF_STMT(BPF_LD + BPF_H + BPF_ABS, offsetof(struct ethhdr, h_proto)),     /* A <- protocol */
>                                                     ^
> [18/1063] Compiling C object 'src/shared/src@shared@@systemd-shared-242@sta/conf-parser.c.o'.

**Steps to reproduce the problem**
> ./configure -Dman=false -Dhtml=false -Dlocaled=false
> ...
>          enabled features: PAM, IMA, SMACK, zlib, xz, bzip2, openssl, libcurl, idn, binfmt, vconsole, quotacheck, tmpfiles, environment.d, sysusers, firstboot, randomseed, backlight, rfkill, logind, machined, portabled, hostnamed, timedated, timesyncd, networkd, resolve, DNS-over-TLS(openssl), coredump, polkit, efi, xkbcommon, blkid, glib, nss-myhostname, nss-mymachines, nss-resolve, nss-systemd, hwdb, tpm, SysV compat, utmp, ldconfig, hibernate, adm group, wheel group, gshadow, link-udev-shared, link-systemctl-shared
> 
>          disabled features: libcryptsetup, AUDIT, AppArmor, SELinux, SECCOMP, lz4, ACL, gcrypt, qrencode, microhttpd, gnutls, libidn2, libidn, libiptc, elfutils, importd, localed, DNS-over-TLS(gnutls), legacy pkla, gnu-efi, kmod, pcre2, dbus, man pages, html pages, man page indices, debug hashmap, debug mmap cache, debug siphash, debug udev, valgrind, trace logging
> make

I assume it's related to 01234e1fe777602265ffd25ab6e73823c62b0efe but can't figure it out.
Cc: @yuwata

**Comment by yuwata** [comment]
Confirmed. I will prep a patch.

**Comment by yuwata** [comment]
Fix is waiting in #12325. If possible, could you test the PR?

**Comment by Werkov** [comment]
I confirm that I can build 571c02994de10be3107f59ccb0ef802d939689aa in my environment. Thanks!
