### ISSUE TITLE
DNS lookup broken in version 242 until restarting networkd

### ISSUE THREAD

**Issue by izenja** [systemd/systemd#12315]
After booting, I have an IP and internet access (through a home router), but no DNS resolving. I use Arch Linux systemd-networkd from the testing repo (version 242), and I have systemd-resolved set up in the stub mode. The network conf is set to use DHCP. I have an ethernet device (enp5s0) and a bridge (br0) set up in a simple bridge configuration through systemd. Restarting systemd-networkd makes everything work fine. This seemingly started happening with 242 with no system configuration changes.

The previous version I was using is 241.93. Downgrading to that version seems to fix this issue, with some caveats: if I log into a non-graphical console after boot, and ping google right away, it fails to resolve. But if I ping again right after, it works. If I just log in to a DE, no apparent issues are visible for a while. However, at some point a DNS lookup will immediately fail (e.g., clicking a link while web browsing), but works upon trying again. This seems maybe related to issue #12142. I've been noticing this for a while, which is potentially the period of time I was using 241.7 (updated to on Feb 20).

When broken, output of resolvectl shows "Current Scopes: none" for the bridge, and no DNS servers. After networkd restart, scopes are "DNS LLMNR/IPv4 LLMNR/IPv6". 

Setting the networkd unit to use debug mode shows some seemingly relevant info and differences. This is the journalctl output during the initial boot: [systemd-networkd-broken.log](https://github.com/systemd/systemd/files/3077616/systemd-networkd-broken.log)

Note that enp5s0 gets renamed to eth0, then back to enp5s0 for some reason (not sure if this is normal). Afterward, there's a
`br0: Could not bring up interface: Invalid argument`
and
`enp5s0: Failed to add to bridge master's slave list: File exists`

And this is it when restarting it, which shows no such issues:
[systemd-networkd-good.log](https://github.com/systemd/systemd/files/3077617/systemd-networkd-good.log)

Here is resolved on boot (not working: 
[resolved-bad.log](https://github.com/systemd/systemd/files/3077619/resolved-bad.log)

And this is after restarting networkd: 
[resolved-good.log](https://github.com/systemd/systemd/files/3077620/resolved-good.log)

I'm using linux 5.0.7. Both r8169 and r8168 ethernet drivers give the same behavior. This did not start happening along with a kernel update.

edit:
Removing the bridge from the configuration fixes the issue too (in that it behaves as it did previously to 242). I also noticed that on occasional boots, even with the bridge, it behaves as in pre-242. Maybe it's a race condition?

**Comment by yuwata** [comment]
Could you also provide .network and .netdev files?

**Comment by yuwata** [comment]
The interface is initialized twice. 
```
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: New device has no master, continuing without
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Flags change: +MULTICAST +BROADCAST
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Link 2 added
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: udev initialized link         <================
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Saved original MTU: 1500
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Created
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Link state is up-to-date
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: found matching network '/etc/systemd/network/bridge.network'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/br0/proxy_ndp' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/br0/use_tempaddr' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/br0/accept_ra' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Setting address genmode for link
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Bringing link up
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Bridge parameters set success
Apr 13 13:03:34 zryzen systemd-networkd[427]: lo: Link state is up-to-date
Apr 13 13:03:34 zryzen systemd-networkd[427]: lo: Unmanaged
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Link state is up-to-date
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: found matching network '/etc/systemd/network/50-wired.network'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/enp5s0/proxy_ndp' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/enp5s0/use_tempaddr' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: Setting '/proc/sys/net/ipv6/conf/enp5s0/accept_ra' to '0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Setting address genmode for link
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Enslaving by 'br0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Enslaving link 'enp5s0'
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Flags change: +UP
Apr 13 13:03:34 zryzen systemd-networkd[427]: br0: Could not bring up interface: Invalid argument
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Flags change: +MULTICAST +BROADCAST
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: Link 2 added
Apr 13 13:03:34 zryzen systemd-networkd[427]: enp5s0: udev initialized link         <================
```
I hope #12316 fixes this issue. @izenja Could you test the PR?

**Comment by ssahani** [comment]
How this PR going to fix the issue. What is the assumption ? BTW @izenja could you paste the conf file so that we can reproduce this. 

I think it's failing to add to hash ```link_append_to_master``` is more relevant here.
```
Apr 13 13:03:35 zryzen systemd-networkd[427]: enp5s0: Joined netdev
Apr 13 13:03:35 zryzen systemd-networkd[427]: enp5s0: Failed to add to bridge master's slave list: File exists
Apr 13 13:03:35 zryzen systemd-networkd[427]: br0: Adding route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a
Apr 13 13:03:35 zryzen systemd-networkd[427]: br0: Adding route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a

```

**Comment by yuwata** [comment]
@ssahani When a link with `Bridge=` or `Bond=` setting initialized twice, then `hashmap_put()` returns `-EEXIST`.

**Comment by ssahani** [comment]
How it gets initialized twice ? What is the reproducer here ?

**Comment by izenja** [comment]
Whoops, sorry for not including the config. These are in /etc/systemd/network/
[network.zip](https://github.com/systemd/systemd/files/3082507/network.zip)

**Comment by izenja** [comment]
PR #12316 doesn't seem to fix the issue.

**Comment by izenja** [comment]
Here's a full journal from the point of systemd starting, in case it helps. There's some kernel log messages in there that could be useful.
[journal.log](https://github.com/systemd/systemd/files/3082692/journal.log)

**Comment by izenja** [comment]
Here's a full journal from the point of systemd starting up, in case it helps. There's some messages from kernel in there could be useful.

[journal.log](https://github.com/systemd/systemd/files/3082696/journal.log)

**Comment by yuwata** [comment]
@izenja Thank you for testing the PR. I've added one more commit on top of the PR. Could you test the PR again?

**Comment by izenja** [comment]
Thanks - that seems to fix it. I had limited time to test this morning (4 reboots), so I'll check again after work since the issue was never 100% consistent.

**Comment by davispuh** [comment]
Something very very similar is happening to me too. I just updated systemd on ArchLinux and DNS resolving doesn't work, but it does work if I restart `systemd-networked`.

I just compiled latest git master and this issue is still happening.

```
$ systemctl --version
systemd 242 (242.120-1-git)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

```
$ sudo systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-04-16 23:43:24 EEST; 21min ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 850 (systemd-network)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 3.1M
   CGroup: /system.slice/systemd-networkd.service
           └─850 /usr/lib/systemd/systemd-networkd

apr 16 23:43:24 ArchLinux systemd-networkd[850]: eth0: Interface name change detected, eth0 has been renamed to enp11s0.
apr 16 23:43:24 ArchLinux systemd-networkd[850]: br0: Could not bring up interface: Invalid argument
apr 16 23:43:24 ArchLinux systemd-networkd[850]: br0: Gained carrier
apr 16 23:43:24 ArchLinux systemd-networkd[850]: enp11s0: Failed to add to bridge master's slave list: File exists
apr 16 23:43:26 ArchLinux systemd-networkd[850]: br0: Gained IPv6LL
apr 16 23:43:26 ArchLinux systemd-networkd[850]: br0: Lost carrier
apr 16 23:43:27 ArchLinux systemd-networkd[850]: enp11s0: Gained carrier
apr 16 23:43:27 ArchLinux systemd-networkd[850]: br0: Gained carrier
apr 16 23:43:30 ArchLinux systemd-networkd[850]: br0: DHCPv4 address 192.168.1.12/24 via 192.168.1.1
apr 16 23:43:31 ArchLinux systemd-networkd[850]: br0: Configured
```
```
$ sudo systemctl status -l systemd-resolved
● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-04-16 23:43:25 EEST; 23min ago
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
 Main PID: 876 (systemd-resolve)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 6.8M
   CGroup: /system.slice/systemd-resolved.service
           └─876 /usr/lib/systemd/systemd-resolved

apr 16 23:43:24 ArchLinux systemd[1]: Starting Network Name Resolution...
apr 16 23:43:25 ArchLinux systemd-resolved[876]: Positive Trust Anchors:
apr 16 23:43:25 ArchLinux systemd-resolved[876]: . IN DS 19036 8 2 49aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb5
apr 16 23:43:25 ArchLinux systemd-resolved[876]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
apr 16 23:43:25 ArchLinux systemd-resolved[876]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in->
apr 16 23:43:25 ArchLinux systemd-resolved[876]: Using system hostname 'ArchLinux'.
apr 16 23:43:25 ArchLinux systemd[1]: Started Network Name Resolution.
```

```
$ resolvectl query google.com
google.com: resolve call failed: No appropriate name servers or networks for name found
```


my config
```
$ cat /etc/systemd/network/br0.netdev 
[NetDev]
Name=br0
Kind=bridge
```

```
cat /etc/systemd/network/bridge.network 
[Match]
Name=br*

[Network]
DHCP=yes
```

```
$ cat /etc/systemd/network/dhcp.network 
[Match]
Name=en*

[Network]
Bridge=br0
DHCP=yes

[Address]
Address=192.168.1.10/32
Broadcast=192.168.1.255
```


After restarting


```
$ sudo systemctl restart systemd-networkd
$ sudo systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-04-17 00:12:39 EEST; 20s ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 105715 (systemd-network)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 1.6M
   CGroup: /system.slice/systemd-networkd.service
           └─105715 /usr/lib/systemd/systemd-networkd

apr 17 00:12:38 ArchLinux systemd[1]: Starting Network Service...
apr 17 00:12:39 ArchLinux systemd-networkd[105715]: br0: netdev ready
apr 17 00:12:39 ArchLinux systemd-networkd[105715]: br0: Gained IPv6LL
apr 17 00:12:39 ArchLinux systemd-networkd[105715]: Enumeration completed
apr 17 00:12:39 ArchLinux systemd[1]: Started Network Service.
apr 17 00:12:39 ArchLinux systemd-networkd[105715]: br0: netdev exists, using existing without changing its parameters
apr 17 00:12:39 ArchLinux systemd-networkd[105715]: br0: Configured
apr 17 00:12:40 ArchLinux systemd-networkd[105715]: br0: DHCPv4 address 192.168.1.12/24 via 192.168.1.1
```

**Comment by izenja** [comment]
Confirming that the PR fixes the issue. It also seems to fix the more minor issue I described with the previous versions where the first resolve attempt after a boot would fail, but subsequent ones would work.

@davispuh that seems very much like the same issue. The fix in the PR is not in master yet (I think). You can try the 2nd PKGBUILD attached to https://bugs.archlinux.org/task/62347 if you want to also test the PR.

**Comment by davispuh** [comment]
Thanks @izenja that PR also fixed it for me :smile:

**Comment by yuwata** [comment]
@izenja Could you test with #12316 again? I've updated whole ref and unref logic.

**Comment by izenja** [comment]
Tested with the new commits and it still works.
