### ISSUE TITLE
DHCPV6 Client is needlessly sending the SOLICIT packet

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#12324]
**systemd version the issue has been seen with**
systemd 241 (241-9-gc1f8ff8+)
> ...

**Expected behaviour you didn't see**
If I disable the DHCP then systemd.networkd should not sent the DHCP SOLICIT packet.
 > …

**Unexpected behaviour you saw**
If I disable the DHCP then systemd.networkd was sending  the DHCP SOLICIT packet.
 > …

**Steps to reproduce the problem**
My configuration file is as below.

cat /etc/systemd/network/eth0.network
[Match]
Name=eth0
[Network]
DHCP=no
DuplicateAddressDetection=yes

Systemctl restart systemd-networkd.

bunch of  following systemd-networkd traces which suggest that networkd keeps sending the SOLICIT packet even if DHCP = no is wrriten in the config file.

DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 9s
NDISC: No RA received before link confirmation timeout.

**Comment by yuwata** [comment]
Could you show the result of `networkctl status eth0`?
And also, please provide the debugging logs, which is generated by creating the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by ssahani** [comment]
Surely this is not reproducible with current git.

**Comment by yuwata** [comment]
No response. Let's close this.
