### ISSUE TITLE
Please let non-root users ask for passwords

### ISSUE THREAD

**Issue by madduck** [systemd/systemd#1232]
The file systemd-ask-password being in /bin suggests that users can use it. However, writing a service unit just now using User= to start a process as non-root exposed that /run/systemd/ask-password is not writeable by non-root.

```
# sudo -u backuppc env SSH_AUTH_SOCK=/run/backuppc/ssh-agent.sock DISPLAY=:0 SSH_ASKPASS=/bin/systemd-ask-password ssh-add </dev/null
Failed to create password file: Permission denied
```

Is there any technical reason why not anyone can register password-ask requests with the system? Ideally, the requests would get a target user such that e.g. systemd-tty-ask-password-agent can be fired off by the target users to respond to queries.

E.g., reusing the above example:

   SSH_ASKPASS='/bin/systemd-ask-password -t backuppc,madduck,%backupops'

Which would create the password query and inform the given users (and members of the %bacupops group) that a password is needed, and also authorise them to provide it.

**Comment by grawity** [comment]
This seems useful for cronjobs.

Regarding the first part though: systemd doesn't really have a distinction between `/bin` and `/sbin` – only whether a tool is in anyone's $PATH or not at all. Especially when many tools have polkit-secured APIs, "`/sbin` = admin-only" makes little sense.

**Comment by madduck** [comment]
Regarding `admin-only` — neither does Unix. The exact and only purpose is `$PATH` and indirectly tab-completion.

**Comment by poettering** [comment]
I figure we should rework this to be based on the kernel keyring, and then support this at the same time.

**Comment by Firstyear** [comment]
Given that sockets are authenticated, the responses can only come from root to the ask-password client. So why not make an ask-password group, that members can write to, then when they drop the socket / inf in, they can make the sck.XXXX and ask.XXXX owned as their own private uid / gid. Root still has all the access to RW the sck and the inf, other applications cannot read or write the sck and inf, or mitm it, and members of a systemd-ask-pass group can request this material without needing root.

**Comment by jsynacek** [comment]
The kernel keyring support was added in e287086b8aa2558356af225a12d9bfea8e7d61ca.

@poettering Is there any reason why not to make /run/systemd/ask-password owned by root:ask-password or similar?

**Comment by poettering** [comment]
> @poettering Is there any reason why not to make /run/systemd/ask-password owned by root:ask-password or similar?

Hmpf, I am not a fan of using UNIX groups as access check for every little facility I mus say, they are just too scarce...

**Comment by antofthy** [comment]
Issue is resolved with the use of the kernel keyring.  Non-root users can now use "systemd-ask-password" and in fact is a great alternative method for password reading (interactive star output) from a tty.
See   http://www.ict.griffith.edu.au/anthony/info/crypto/passwd_input.txt

However I have had other problems with this.

**Comment by petere** [comment]
Here is a slightly evil workaround:

    ExecStartPre=+/usr/bin/setfacl -m u:someuser:wx /run/systemd/ask-password
    ExecStartPost=+/usr/bin/setfacl -x u:someuser /run/systemd/ask-password

😬

**Comment by Firstyear** [comment]
I have this exact work around in an officially accepted and shipped fedora/rhel package. 

It's quite clear this bug will never be resolved, so please continue to hack around it with this excellent technique :D

**Comment by RaitoBezarius** [comment]
Still important to me, is there anything we can do to help?

**Comment by Firstyear** [comment]
Given that this issue has been open for 6 years, I think "no, there is nothing that can be done" because there is no interest from the systemd developers in this matter. You probably need to use the work arounds listed.

**Comment by batrick** [comment]
> Here is a slightly evil workaround:
> 
> ```
> ExecStartPre=+/usr/bin/setfacl -m u:someuser:wx /run/systemd/ask-password
> ExecStartPost=+/usr/bin/setfacl -x u:someuser /run/systemd/ask-password
> ```
> 
> grimacing

I have a better workaround that I use for openvpn:

```
ExecStartPre=!/bin/stat --printf '' /etc/openvpn/client/%i.conf
ExecStartPre=!/bin/sh -c 'if grep auth-user-pass /etc/openvpn/client/%i.conf; then { /usr/bin/systemd-ask-password --echo --icon network-vpn "Enter Auth Username:"; /usr/bin/systemd-ask-password --icon network-vpn "Enter Auth Password:"; } > /tmp/user-pass; fi'
ExecStart=/usr/sbin/openvpn --suppress-timestamps --nobind --config %i.conf
PrivateTmp=true
Group=openvpn
User=openvpn
```

Basically: ask for the password if the config requires one, put it in a file in the service's private tmp, then have the config reference that.

**Comment by batrick** [comment]
> Amazing. I'm sure nothing bad has ever happened because passwords were left in temp files on disks right upside_down_face

It's a tmpfs only the service can see. I think the risk here is pretty low. I've also just made a change which removes the file after 60 seconds. Long enough for openvpn to try to pick it up and authenticate.

**Comment by Firstyear** [comment]
Wasn't meant to be a dig at you @batrick - more that by systemd developers ignoring this request, we have to resort to such work arounds.

**Comment by Freso** [comment]
> It's a tmpfs only the service can see.

I think you might misunderstand how `PrivateTmp` works, at least by default. `PrivateTmp` makes it so that the system `/tmp` is not available for the service, but the service’s `/tmp` will still be available from the system `/tmp` (as `/tmp/systemd-private-*-*.service-*/tmp/`). Of course, this is still only accessible with root privileges, but a number of units and other services _do_ run as root and as such will have access to read/cache/copy/… the contents of `/tmp`. I do agree that the risk is pretty low, but possibly less low than you think. (And then there’s also the risk of tmpfs data getting stored in swap on disk, esp. if said swap-on-disk is not encrypted.)

(Again, this is assuming default behaviour/setup other than shown in the workaround examples.)

**Comment by scj643** [comment]
Good news you no longer need root to do this. I am working on using this for ssh-askpass. The one issue I'm running into is prompting to touch the key since ksshaskpass has different prompts
