### ISSUE TITLE
systemd v242 may go into loop when ListenDatagram socket units are stopped.

### ISSUE THREAD

**Issue by buczek** [systemd/systemd#12335]
When we upgrade systemd from v241 to v242 on our systems, they  can no longer be shut down cleany, because systemd goes into an endless loop when it receives syslog data on the socket of the stopping `rsyslog.socket` unit. The problem originates in PR #12271. After commit 4ff9bc2ea6e5daf08b5c9de17c0dcf16c3b7379e ("tree-wide: port users over to use new ERRNO_IS_ACCEPT_AGAIN() call"), flush_accept() calls poll() and accept() in a loop as long as accept() returns EOPNOTSUPP, which is assumed to be a transient error [1]. This is done regardless of the socket type. However, accept() on SOCK_DGRAM sockets returns EOPNOTSUPP persistently.

Early Debug Shell session in the blocked state after  `shutdown -h now`  (manually re-typed from a vncviewer window, so typos are possible):
```
sh-4.3# uname -r
4.19.19.mx64.244
sh-4.3# strace -p 1
poll([{fd=41, events=POLLIN}],1 ,0)    = 1 ([{fd=41, revents=POLLIN}])
accept4(41, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EOPNOTSUPP (Operation not supported)
poll([{fd=41, events=POLLIN}],1 ,0)    = 1 ([{fd=41, revents=POLLIN}])
accept4(41, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EOPNOTSUPP (Operation not supported)
poll([{fd=41, events=POLLIN}],1 ,0)    = 1 ([{fd=41, revents=POLLIN}])
accept4(41, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EOPNOTSUPP (Operation not supported)
[...]
^C
sh-4.3# lsof -p 1
[...]
systemd   1 root   41u     unix 0x0000000085ff6bd2      0t0      16686 /dev/log type=DGRAM
[...]
sh-4.3:# gdb -p 1 /bin/systemd
[...]
(gdb) where
#0  0x................ in accept4 (fd=41, addr=..., addr_len=0x0, flags=526336) at ../sysdeps/unix/sysv/linux/accept4.c:32
#1  0x................ in flush_accept () from /lib/systemd/libsystemd-shared-242.so
#2  0x................ in socket_enter_running ()
#3  0x................ in socket_dispatch_io ()
#4  0x................ in source_dispatch () from /lib/systemd/libsystemd-shared-242.so
#5  0x................ in sd_event_dispatch () /lib/systemd/libsystemd-shared-242.so
#6  0x................ in sd_event_run () /lib/systemd/libsystemd-shared-242.so
#7  0x................ in manager_loop ()
#8  0x................ in main ()
```
[1] https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/src/basic/socket-util.c#L1222

**Comment by poettering** [comment]
Urks, grmbl... So accept(2) suggests handling EOPNOTSUPP as transient error, but it can also be a non-transient error? Yikes. I figure flush_accept should use SO_TYPE first to check the socket type and if not SOCK_STREAM or SOCK_SEQPACKET should just exit early...

**Comment by poettering** [comment]
Thanks for tracking this one down btw, much appreciated!

**Comment by mbiebl** [comment]
I've been running into boot failures with v242 when running the autopkgtests suite for Debian.
We do enable syslog forwarding in Debian/Ubuntu:
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/patches/debian/Re-enable-journal-forwarding-to-syslog.patch

The result with v242 is that `boot-and-services` and `boot-smoke` fail with
```
autopkgtest [22:23:26]: test boot-smoke: [-----------------------
reboot #0
bash: line 1: 14229 Killed                  /tmp/autopkgtest.MfWhkU/build.bwc/src/debian/tests/boot-smoke 2> >(tee -a /tmp/autopkgtest.MfWhkU/boot-smoke-stderr >&2) > >(tee -a /tmp/autopkgtest.MfWhkU/boot-smoke-stdout)
autopkgtest [22:23:28]: test process requested reboot with marker 1
qemu-system-x86_64: terminating on signal 15 from pid 24187 (/usr/bin/python3)
<VirtSubproc>: failure: timed out waiting for "login prompt on ttyS0"
autopkgtest [22:24:30]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```

I tried running git master (with #12346 applied), but now I get:
```
test_rsyslog (__main__.ServicesTest) ... FAIL
test_tmp_cleanup (__main__.ServicesTest) ... FAIL
``` 
(full log attached).

So something is still broken.

**Comment by mbiebl** [comment]
Please disregard what I wrote earlier. This was a mistake on my part.
