### ISSUE TITLE
Clarify status of user special units that would be bound to udev (e.g. bluetooth.target)

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#12330]
Systemd has a number of system wide units that are automatically started by `SYSTEMD_WANTS` udev rules. These are documented to exist for the system instance of systemd.

Now, the odd thing is that these units are also defined for the systemd user instance. However, because these are bound to `SYSTEMD_USER_WANTS` rather than `SYSTEMD_WANTS` they are effectively useless unless some other software installs the corresponding udev rules first.

Maybe this behaviour is expected. Though I could also imagine either removing the targets from the user instance or changing things so that they work as expected by default.

**Comment by poettering** [comment]
Yeah, this is a bit borked... I figure we should make these targets work the same as for the system mode, i.e. add SYSTEMD_USER_WANTS for these whereever we pull in these targets via SYSTEMD_WANTS.
