### ISSUE TITLE
pam_systemd have zram option to tmpfs

### ISSUE THREAD

**Issue by StuartIanNaylor** [systemd/systemd#12342]
With pam_systemd &  systemd-logind.service is it or could it be possible to use zram rather than tmpfs?

With zram compression of 250-400% depending on alg would be possible and allow more user space in less ram?

**Comment by poettering** [comment]
Hmm, so why bother with zram and patch every consumer like that? isn't it more useful to use zswap instead, and thus have every tmpfs and every other memory subject to such compression? i.e. why limit this to logind's own tmpfs mounts?

If zram/zswap is a good idea, it really sounds like something you want for the whole system, no? or what am I missing?

**Comment by StuartIanNaylor** [comment]
/run/user/1000 rather than say 90M for a user and mounting as tmpfs you could do the same with a zram device so that user space would be approx 200-400% less depending on lzo-zstd.

zwap is just a cache and great for purpose zram can be a drive of any files ystem that is mounted on it.

**Comment by poettering** [comment]
I don't get it.

So there are two approaches:

1. Mount file system X as ramfs
2. Mount file system X as tmpfs, but enable zswap?

It appears to me that option 2 is always the better approach, since tmpfs is backed by swappable memory anyway, and thus by enabing zswap you allow to the kernel freedom to choose what precisely to swap out or not, regardless if that's file system X or anything else. i.e. why make the link between compressed RAM backing and specific file systems explicit if you might as well make it implicit, and let the kernel choose what to swap out and what not?

**Comment by StuartIanNaylor** [comment]
Zram is just not swap you can make any filesystem on it, ignore swap totally.
It would mean that all /run/user/xxx would be on a compressed memory device.

Falls down though as after checking the backing device can only be a single partition like the of snippet from zram.
So nothing to get really a shame zram doesn't support more than just a singular partition but it doesn't.

**Comment by poettering** [comment]
> Zram is just not swap you can make any filesystem on it, ignore swap totally.
> It would mean that all /run/user/xxx would be on a compressed memory device.

Right, but why would I ever use a compressed RAM file system if I could also just use a tmpfs file system in conjunction with swapping to compressed RAM? it's effectively the same, but the latter gives the kernel the freedom to choose what to swap out: the tmpfs contents or any other userspace memory.

**Comment by StuartIanNaylor** [comment]
I guess so and even use zswap also its just singular so you can define a singular partition.
I was just thinking with higher user numbers it would reduce system swapping even if it is zram.
But guess its negligible, apols.

**Comment by poettering** [comment]
OK, then let's close this here. I think doing zswap + tmpfs is the better approach.  Hope that makes sense.
