### ISSUE TITLE
Handling of encoded slice unit names: bash completions and on accepting the unencoded name as parameter

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#12347]
I have slices containing unencoded “-”, which is encoded to “\x2d”,
```
systemctl list-units|grep sendm
  sendmail.service loaded active running   sendmail
  sendmail@sendmail\x2dmail.cf.service loaded active running   sendmail sendmail-mail.cf            
  sendmail@sendmail\x2dpost\x2dlistserv.cf.service loaded active running   sendmail sendmail-post-listserv.cf
  sendmail@submit\x2dssl.cf.service loaded active running   sendmail submit-ssl.cf
  sendmail@submit\x2dtls.cf.service loaded active running   sendmail submit-tls.cf
  system-sendmail.slice loaded active active    system-sendmail.slice
```

Pressing `systemctl status sendmail@s<TAB>` shows the completions:
 * sendmail@sendmail\x2dmail.cf.service
 * sendmail@submit\x2dssl.cf.service
 * sendmail@sendmail\x2dpost\x2dlistserv.cf.service
 * sendmail@submit\x2dtls.cf.service

Pressing `systemctl status sendmail@send<TAB>` completes to `systemctl status  sendmail@sendmail\\x2d`.  Notice how the completion correctly inserted a second slash.

Pressing `journalctl --unit sendmail@send<TAB>`  completes to `journalctl --unit  sendmail@sendmail\x2d`, but it should complete to `journalctl --unit  sendmail@sendmail\\x2d` (two slashes).

Pressing `journalctl --unit  sendmail@sendmail\x2<TAB>` or `journalctl --unit  sendmail@sendmail\\x2<TAB>` does not complete.

Pressing `systemctl status sendmail@sendmail\\x2d<TAB>` does nothing.  It should suggest `sendmail@sendmail\\x2dmail.cf.service` and `sendmail@sendmail\x2dpost\x2dlistserv.cf.service`.

Teach `journalctl --unit=<x>` and `systemctl status <x>` to accept also the unencoded version of the service-slice, here handle `journal --unit=sendmail@submit\x2dtls.cf.service` and `journal --unit=sendmail@submit-tls.cf.service` as equivalent.  It was very hard to me to find out how to extact the logs of a service

I use systemd 241.

**Comment by dilyanpalauzov** [comment]
How about accepting as unit names the unescaped names, too?

**Comment by mrc0mmand** [comment]
> How about accepting as unit names the unescaped names, too?

Hmm, I guess it should be possible as well, will try to look into it.

**Comment by dilyanpalauzov** [comment]
I mean to tweak `journalctl --unit=` to accept the unescaped unit name.  With escaping I mean the proceudure behind https://www.freedesktop.org/software/systemd/man/systemd.unit.html#String%20Escaping%20for%20Inclusion%20in%20Unit%20Names, so that `--unit='sendmail@submit-ssl.service'` and `--unit=
sendmail@submit\\x2dssl.cf.service` are handled as eqivalent.
