### ISSUE TITLE
No getty started on tty1 anymore

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#12345]
Updating systemd from 239 to 242, and rebooting the system, no getty is started on tty1 anymore.

```
$ systemctl status getty@tty1.service
● getty@tty1.service - Getty on tty1
   Loaded: loaded (/lib/systemd/system/getty@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html
```

Also hitting a key doesn’t start one. gettys are started *correctly* switching to tty2 to tty6, but not tty1. Only the start-up messages are shown there.

Manually starting the service, makes the getty appear.

```
$ sudo systemctl start getty@tty1.service
$ systemctl status getty@tty1.service
● getty@tty1.service - Getty on tty1
   Loaded: loaded (/lib/systemd/system/getty@.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-04-18 12:40:01 CEST; 4min 18s ago
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html
 Main PID: 3018 (agetty)
    Tasks: 1 (limit: 4915)
   Memory: 228.0K
   CGroup: /system.slice/system-getty.slice/getty@tty1.service
           └─3018 /sbin/agetty -o -p -- \u --noclear tty1 linux
```

**Comment by poettering** [comment]
I figure this is an artifact of https://github.com/systemd/systemd/blob/master/NEWS#L244

**Comment by mbiebl** [comment]
Since this is not the first bug report in that regard, would it make sense to call `systemctl preset-all` as part of `ninja install` if `$DESTDIR` is not set?

**Comment by paulmenzel** [comment]
I manually ran `sudo systemctl enable getty@tty1.service` now to restore the old behavior. Should I submit a change, updating `NEWS`?

**Comment by mbiebl** [comment]
@paulmenzel This changes is already listed in `NEWS`

**Comment by paulmenzel** [comment]
On 04/18/2019 01:36 PM, Michael Biebl wrote:
> @paulmenzel This changes is already listed in `NEWS`

No, getty@ is not mentioned as far as I can see.

>         * During package installation (with `ninja install`), we would create
>           symlinks for systemd-networkd.service, systemd-networkd.socket,
>           systemd-resolved.service, remote-cryptsetup.target, remote-fs.target,
>           systemd-networkd-wait-online.service, and systemd-timesyncd.service
>           in /etc, as if `systemctl enable` was called for those units, to make
>           the system usable immediately after installation. Now this is not
>           done anymore, and instead calling `systemctl preset-all` is
>           recommended after the first installation of systemd.

**Comment by poettering** [comment]
Yeah, we should document that for getty's too, and retroactively add that to NEWS I guess. Would be happy to review  PR for htat!

**Comment by keszybz** [comment]
> Since this is not the first bug report in that regard, would it make sense to call `systemctl preset-all` as part of `ninja install` if `$DESTDIR` is not set?

No, that'd make installing onto an existing system very painful.

**Comment by dilyanpalauzov** [comment]
The NEWS file states, that `systemd preset-all` is recommended after the first installation.  But the report here is about an upgrade from v239 to v242.  So this is not the first installation.

Please clarify whether `systemctl preset-all` shall be called after upgrading systemd, or after setting ul the system initially.

**Comment by keszybz** [comment]
Just after the initial installation. During upgrades, existing symlinks are not touched (and should not be touched). With current master:
```console
$ rm -rf /var/tmp/inst1 && DESTDIR=/var/tmp/inst1 ninja -C build install
....
$ systemctl --root=/var/tmp/inst1 is-enabled getty@
disabled
$ systemctl --root=/var/tmp/inst1 enable getty@
Created symlink /var/tmp/inst1/etc/systemd/system/getty.target.wants/getty@tty1.service → /usr/lib/systemd/system/getty@.service.
$ DESTDIR=/var/tmp/inst1 ninja -C build install
...
$ systemctl --root=/var/tmp/inst1 is-enabled getty@
enabled
```

> Updating systemd from 239 to 242

How do you update?

**Comment by mbiebl** [comment]
> > Since this is not the first bug report in that regard, would it make sense to call `systemctl preset-all` as part of `ninja install` if `$DESTDIR` is not set?
> 
> No, that'd make installing onto an existing system very painful.

I think it would be pretty easy to only run `preset-all` upon first installation. Just check if `/run/systemd` exists when running `ninja install`

**Comment by floppym** [comment]
Distro packages must take care not to remove the symlinks on upgrades. Since the symlinks would no longer exist in the installation image, most package managers would remove them by default.

**Comment by mbiebl** [comment]
@floppym this would not affect distro packages (see my comment earlier regarding `$DESTDIR`)

**Comment by floppym** [comment]
@mbiebl I was responding to @keszybz's comment about upgrades removing symlinks on existing installations.

**Comment by anonymous7002** [comment]
I also have this same issue, except not on the same systemd version.

**Comment by adrelanos** [comment]
> I also have this same issue, except not on the same systemd version, and `sudo systemctl enable getty@tty1.service` didn't help. Debian Bullseye.

Got the same issue.
