### ISSUE TITLE
Have option to force nspawn into unified cgroup hierarchy mode without checks

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#12368]
UNIFIED_CGROUP_HIERARCHY=1 is documented to force nspawn into unified cgroup hierarchy mode, however it still goes through a code path to check files in an attempt to detect the version of systemd installed (https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L445) and could error out if the files are not there. We would prefer to skip this check if the environment variable is provided, or make a new option to do so. Can work on patches if this sounds like a reasonable request.

**Comment by poettering** [comment]
hmm, this actually feels like a bug. If the env var is specified it should take precedence, and the payload shouldn't matter. hence the behaviour you want shouldn't be an option, but the unconditoinal logic...

**Comment by poettering** [comment]
And yupp, happy to take a patch to fix this, of course!

**Comment by anitazha** [comment]
False alarm here. Environment variable is taking precedence, just had a user error. Sorry!
