### ISSUE TITLE
journalctl --file does not accept file

### ISSUE THREAD

**Issue by stueja** [systemd/systemd#12369]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > output of journal entries contained in the given file

**Unexpected behaviour you saw**
 > `File is neither a device node, nor regular file, nor executable: /var/log/journal/remote/remote-192.168.1.2.journal`

**Steps to reproduce the problem**
```
[jan@brick ~]# sudo journalctl -f /var/log/journal/remote/remote-192.168.1.2.journal
```

**Comment by keszybz** [comment]
@stueja please don't try to report the same issue in three different places.

**Comment by stueja** [comment]
Apologies.
