### ISSUE TITLE
Wrong SMACK label of /etc/mtab when '--with-smack-run-label' is enabled.

### ISSUE THREAD

**Issue by again4you** [systemd/systemd#1237]
/etc/mtab should always be labeled as "_", even though systemd has its own smack label using '--with-smack-run-label=' configuration. This is mainly because all processes could read that file and the origin of this file (i.e. /proc/mounts) is labeled as "_".

However, current systemd doesn't work like that.  Below example is configured as "--with-smack-run-label=System". 

```
root@localhost:~# ls -alZ /etc/mtab 
lrwxrwxrwx. 1 root root System 19 Dec 31 16:03 /etc/mtab -> ../proc/self/mounts
```

Because of this reason, below SMACK denied errors occur when systemd user session access that file. 

```
Dec 31 16:31:33 localhost systemd[4268]: <audit-1400> lsm=SMACK fn=smack_inode_getattr action=denied 
subject="User" object="System" requested=r pid=4268 comm="systemd" path="/etc/mtab" dev="mmcblk0p2" ino=24525
```

**Comment by poettering** [comment]
We rely on external patches for SMACK related stuff.
