### ISSUE TITLE
systemd-network ignores ListenPort in [WIREGUARD]

### ISSUE THREAD

**Issue by MorphBonehunter** [systemd/systemd#12377]
**systemd version the issue has been seen with**
> v242

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > systemd-networkd should honor the `ListenPort=` in the `[WIREGUARD]` section

**Unexpected behaviour you saw**
 > systemd-networkd ignores the `ListenPort=` in the `[WIREGUARD]` section

**Steps to reproduce the problem**
After upgrading from latest 241 to 242 the `ListenPort=` seems to be ignored or is set to "auto" in all cases. 
* Prepare an Test netdev File:
```
cat /etc/systemd/network/02-wg-uv.netdev
[NetDev]
Name = wg-uv
Kind = wireguard

[WireGuard]
PrivateKey = uKHTCAv8+nKh5fmRtE7j/QucwGGPJeZmiU5Vkry/2Fo=
ListenPort = 12345
```
* generate an (ugly) systemd-networkd restart and remove WG interface loop:
```
for i in {1..5}; do ip l d wg-uv && systemctl restart systemd-networkd; sleep 2; wg | grep -E "interface|listening"; done
interface: wg-uv
  listening port: 40243
interface: wg-uv
  listening port: 41474
interface: wg-uv
  listening port: 43267
interface: wg-uv
  listening port: 55313
interface: wg-uv
  listening port: 48652
```
* everytime i get an random listen port

**Comment by yuwata** [comment]
I think this is a bug in `wg` command. Please try `wg show wg-uv listen-port`. I hope the correct port number will shown.
Or, have you confirmed that the correct port number is shown with v241 or earlier version of systemd?

**Comment by MorphBonehunter** [comment]
Hey @yuwata, as i wrote, the behavior ocurred after upgrade systemd on one of my systems today.
Others systems with 241 and the same wireguard Version work without Problem.
As my Produktion environment are based on fixed Ports, i can confirm that the right Port was used before the upgeade.

**Comment by yuwata** [comment]
So, `wg show wg-uv listen-port` also returns random port number?

**Comment by yuwata** [comment]
Ouch. I confirm that...

**Comment by yuwata** [comment]
Fix is waiting in #12382.

**Comment by MorphBonehunter** [comment]
Thanks @yuwata and @keszybz for fast response and fix!
Could this also be backported to systemd-stable please so that distris which based on this repo could upgrade there packages?

**Comment by keszybz** [comment]
Yep, will do.
