### ISSUE TITLE
systemd-networkd generic DHCP option interface

### ISSUE THREAD

**Issue by b1tninja** [systemd/systemd#12370]
**Is your feature request related to a problem? Please describe.**
Can only configure supported DHCP options

**Describe the solution you'd like**
A generic way to configure any dhcp option for a request, knowing it may not be handled.

**Describe alternatives you've considered**
https://www.ietf.org/rfc/rfc2132.txt

https://web.archive.org/web/20190306231413/https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcp-options

**Comment by ssahani** [comment]
Sure thanks RFE

**Comment by ssahani** [comment]
@b1tninja The link is not there could you please update it thanks!

**Comment by b1tninja** [comment]
https://web.archive.org/web/20190306231413/https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcp-options

**Comment by ssahani** [comment]
which precise option you want to be impelented according to the RFC ? option vendor-encapsulated-options? 43

**Comment by ssahani** [comment]
That is ok but I am asking which rfc option you want to implemented else it it will dropped by the firewall under the impression of spam

**Comment by b1tninja** [comment]
I'm trying to mimic the request a CPE gateway makes (AT&T forces me to use their router). A dhcp "interceptor" / proxy option would be an amazing alternative ;D. Here is the discovery and request... 

Frame 59: 384 bytes on wire (3072 bits), 384 bytes captured (3072 bits) on interface 0
    Interface id: 0 (br0)
        Interface name: br0
    Encapsulation type: Ethernet (1)
    Arrival Time: Jul  6, 2017 13:29:10.839720644 UTC
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1499347750.839720644 seconds
    [Time delta from previous captured frame: 0.769471145 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 12.172770103 seconds]
    Frame Number: 59
    Frame Length: 384 bytes (3072 bits)
    Capture Length: 384 bytes (3072 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:vlan:ethertype:ip:udp:dhcp]
Ethernet II, Src: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
    Destination: Broadcast (ff:ff:ff:ff:ff:ff)
        Address: Broadcast (ff:ff:ff:ff:ff:ff)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
    Source: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        Address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 3, DEI: 0, ID: 0
    011. .... .... .... = Priority: Critical Applications (3)
    ...0 .... .... .... = DEI: Ineligible
    .... 0000 0000 0000 = ID: 0
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 99.105.33.21, Dst: 172.9.164.1
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x28 (DSCP: AF11, ECN: Not-ECT)
        0010 10.. = Differentiated Services Codepoint: Assured Forwarding 11 (10)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 366
    Identification: 0xc33a (49978)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 128
    Protocol: UDP (17)
    Header checksum: 0x6193 [validation disabled]
    [Header checksum status: Unverified]
    Source: 99.105.33.21
    Destination: 172.9.164.1
User Datagram Protocol, Src Port: 68, Dst Port: 67
    Source Port: 68
    Destination Port: 67
    Length: 346
    Checksum: 0x54f8 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 28]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
Dynamic Host Configuration Protocol (Release)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x6949beeb
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
        0... .... .... .... = Broadcast flag: Unicast
        .000 0000 0000 0000 = Reserved flags: 0x0000
    Client IP address: 99.105.33.21
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Release)
        Length: 1
        DHCP: Release (7)
    Option: (61) Client identifier
        Length: 20
        Type: 0
        Client Identifier: 00D09E-15171N098922
    Option: (56) Message
        Length: 14
        Message: clean shutdown
    Option: (54) DHCP Server Identifier (172.9.164.1)
        Length: 4
        DHCP Server Identifier: 172.9.164.1
    Option: (125) V-I Vendor-specific Information
        Length: 48
        Enterprise: The Broadband Forum (3561)
            Length: 43
            Option 125 Suboption: (1) DeviceManufacturerOUI
                Length: 7
                DeviceManufacturerOUI: 00:d0:9e (2Wire Inc)
            Option 125 Suboption: (2) DeviceSerialNumber
                Length: 10
                DeviceSerialNumber: homeportal
            Option 125 Suboption: (3) DeviceProductClass
                Length: 6
                DeviceProductClass: 5268AC
            Option 125 Suboption: (4) GatewayManufacturerOUI
                Length: 12
                GatewayManufacturerOUI: 15171N098922
    Option: (255) End
        Option End: 255

0000  ff ff ff ff ff ff d4 b2 7a 6b b1 4c 81 00 60 00   ........zk.L..`.
0010  08 00 45 28 01 6e c3 3a 40 00 80 11 61 93 63 69   ..E(.n.:@...a.ci
0020  21 15 ac 09 a4 01 00 44 00 43 01 5a 54 f8 01 01   !......D.C.ZT...
0030  06 00 69 49 be eb 00 00 00 00 63 69 21 15 00 00   ..iI......ci!...
0040  00 00 00 00 00 00 00 00 00 00 d4 b2 7a 6b b1 4c   ............zk.L
0050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0100  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0110  00 00 00 00 00 00 00 00 00 00 63 82 53 63 35 01   ..........c.Sc5.
0120  07 3d 14 00 30 30 44 30 39 45 2d 31 35 31 37 31   .=..00D09E-15171
0130  4e 30 39 38 39 32 32 38 0e 63 6c 65 61 6e 20 73   N0989228.clean s
0140  68 75 74 64 6f 77 6e 36 04 ac 09 a4 01 7d 30 00   hutdown6.....}0.
0150  00 0d e9 2b 01 07 30 30 44 30 39 45 00 02 0a 68   ...+..00D09E...h
0160  6f 6d 65 70 6f 72 74 61 6c 03 06 35 32 36 38 41   omeportal..5268A
0170  43 04 0c 31 35 31 37 31 4e 30 39 38 39 32 32 ff   C..15171N098922.

Frame 86: 408 bytes on wire (3264 bits), 408 bytes captured (3264 bits) on interface 0
    Interface id: 0 (br0)
        Interface name: br0
    Encapsulation type: Ethernet (1)
    Arrival Time: Jul  6, 2017 13:29:35.857360856 UTC
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1499347775.857360856 seconds
    [Time delta from previous captured frame: 3.936313803 seconds]
    [Time delta from previous displayed frame: 25.017640212 seconds]
    [Time since reference or first frame: 37.190410315 seconds]
    Frame Number: 86
    Frame Length: 408 bytes (3264 bits)
    Capture Length: 408 bytes (3264 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:vlan:ethertype:ip:udp:dhcp]
Ethernet II, Src: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
    Destination: Broadcast (ff:ff:ff:ff:ff:ff)
        Address: Broadcast (ff:ff:ff:ff:ff:ff)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
    Source: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        Address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 3, DEI: 0, ID: 0
    011. .... .... .... = Priority: Critical Applications (3)
    ...0 .... .... .... = DEI: Ineligible
    .... 0000 0000 0000 = ID: 0
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 0.0.0.0, Dst: 255.255.255.255
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x28 (DSCP: AF11, ECN: Not-ECT)
        0010 10.. = Differentiated Services Codepoint: Assured Forwarding 11 (10)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 390
    Identification: 0xa529 (42281)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 128
    Protocol: UDP (17)
    Header checksum: 0x5416 [validation disabled]
    [Header checksum status: Unverified]
    Source: 0.0.0.0
    Destination: 255.255.255.255
User Datagram Protocol, Src Port: 68, Dst Port: 67
    Source Port: 68
    Destination Port: 67
    Length: 370
    Checksum: 0x390f [unverified]
    [Checksum Status: Unverified]
    [Stream index: 29]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
Dynamic Host Configuration Protocol (Discover)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x4d579ac2
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
        0... .... .... .... = Broadcast flag: Unicast
        .000 0000 0000 0000 = Reserved flags: 0x0000
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Discover)
        Length: 1
        DHCP: Discover (1)
    Option: (61) Client identifier
        Length: 20
        Type: 0
        Client Identifier: 00D09E-15171N098922
    Option: (57) Maximum DHCP Message Size
        Length: 2
        Maximum DHCP Message Size: 1500
    Option: (60) Vendor class identifier
        Length: 12
        Vendor class identifier: 2WHPL 10.5.3
    Option: (124) V-I Vendor Class
        Length: 5
        Enterprise: 2Wire, Inc. (4839)
        CableLab Address Mode: 0
        NetInfo Parent Server Tag: [Empty]
    Option: (55) Parameter Request List
        Length: 19
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (2) Time Offset
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (6) Domain Name Server
        Parameter Request List Item: (15) Domain Name
        Parameter Request List Item: (42) Network Time Protocol Servers
        Parameter Request List Item: (44) NetBIOS over TCP/IP Name Server
        Parameter Request List Item: (46) NetBIOS over TCP/IP Node Type
        Parameter Request List Item: (47) NetBIOS over TCP/IP Scope
        Parameter Request List Item: (23) Default IP Time-to-Live
        Parameter Request List Item: (24) Path MTU Aging Timeout
        Parameter Request List Item: (25) Path MTU Plateau Table
        Parameter Request List Item: (26) Interface MTU
        Parameter Request List Item: (35) ARP Cache Timeout
        Parameter Request List Item: (36) Ethernet Encapsulation
        Parameter Request List Item: (119) Domain Search
        Parameter Request List Item: (121) Classless Static Route
        Parameter Request List Item: (249) Private/Classless Static Route (Microsoft)
        Parameter Request List Item: (212) 6RD
    Option: (125) V-I Vendor-specific Information
        Length: 48
        Enterprise: The Broadband Forum (3561)
            Length: 43
            Option 125 Suboption: (1) DeviceManufacturerOUI
                Length: 7
                DeviceManufacturerOUI: 00:d0:9e (2Wire Inc)
            Option 125 Suboption: (2) DeviceSerialNumber
                Length: 10
                DeviceSerialNumber: homeportal
            Option 125 Suboption: (3) DeviceProductClass
                Length: 6
                DeviceProductClass: 5268AC
            Option 125 Suboption: (4) GatewayManufacturerOUI
                Length: 12
                GatewayManufacturerOUI: 15171N098922
    Option: (255) End
        Option End: 255

0000  ff ff ff ff ff ff d4 b2 7a 6b b1 4c 81 00 60 00   ........zk.L..`.
0010  08 00 45 28 01 86 a5 29 40 00 80 11 54 16 00 00   ..E(...)@...T...
0020  00 00 ff ff ff ff 00 44 00 43 01 72 39 0f 01 01   .......D.C.r9...
0030  06 00 4d 57 9a c2 00 00 00 00 00 00 00 00 00 00   ..MW............
0040  00 00 00 00 00 00 00 00 00 00 d4 b2 7a 6b b1 4c   ............zk.L
0050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0100  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0110  00 00 00 00 00 00 00 00 00 00 63 82 53 63 35 01   ..........c.Sc5.
0120  01 3d 14 00 30 30 44 30 39 45 2d 31 35 31 37 31   .=..00D09E-15171
0130  4e 30 39 38 39 32 32 39 02 05 dc 3c 0c 32 57 48   N0989229...<.2WH
0140  50 4c 20 31 30 2e 35 2e 33 7c 05 00 00 12 e7 00   PL 10.5.3|......
0150  37 13 01 02 03 06 0f 2a 2c 2e 2f 17 18 19 1a 23   7......*,./....#
0160  24 77 79 f9 d4 7d 30 00 00 0d e9 2b 01 07 30 30   $wy..}0....+..00
0170  44 30 39 45 00 02 0a 68 6f 6d 65 70 6f 72 74 61   D09E...homeporta
0180  6c 03 06 35 32 36 38 41 43 04 0c 31 35 31 37 31   l..5268AC..15171
0190  4e 30 39 38 39 32 32 ff                           N098922.

Frame 88: 420 bytes on wire (3360 bits), 420 bytes captured (3360 bits) on interface 0
    Interface id: 0 (br0)
        Interface name: br0
    Encapsulation type: Ethernet (1)
    Arrival Time: Jul  6, 2017 13:29:36.381822463 UTC
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1499347776.381822463 seconds
    [Time delta from previous captured frame: 0.503117469 seconds]
    [Time delta from previous displayed frame: 0.524461607 seconds]
    [Time since reference or first frame: 37.714871922 seconds]
    Frame Number: 88
    Frame Length: 420 bytes (3360 bits)
    Capture Length: 420 bytes (3360 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:vlan:ethertype:ip:udp:dhcp]
Ethernet II, Src: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
    Destination: Broadcast (ff:ff:ff:ff:ff:ff)
        Address: Broadcast (ff:ff:ff:ff:ff:ff)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
    Source: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        Address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 3, DEI: 0, ID: 0
    011. .... .... .... = Priority: Critical Applications (3)
    ...0 .... .... .... = DEI: Ineligible
    .... 0000 0000 0000 = ID: 0
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 0.0.0.0, Dst: 255.255.255.255
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x28 (DSCP: AF11, ECN: Not-ECT)
        0010 10.. = Differentiated Services Codepoint: Assured Forwarding 11 (10)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 402
    Identification: 0xedd1 (60881)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 128
    Protocol: UDP (17)
    Header checksum: 0x0b62 [validation disabled]
    [Header checksum status: Unverified]
    Source: 0.0.0.0
    Destination: 255.255.255.255
User Datagram Protocol, Src Port: 68, Dst Port: 67
    Source Port: 68
    Destination Port: 67
    Length: 382
    Checksum: 0xa4ba [unverified]
    [Checksum Status: Unverified]
    [Stream index: 29]
    [Timestamps]
        [Time since first frame: 0.524461607 seconds]
        [Time since previous frame: 0.524461607 seconds]
Dynamic Host Configuration Protocol (Request)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x4d579ac2
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
        0... .... .... .... = Broadcast flag: Unicast
        .000 0000 0000 0000 = Reserved flags: 0x0000
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: ArrisGro_6b:b1:4c (d4:b2:7a:6b:b1:4c)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Request)
        Length: 1
        DHCP: Request (3)
    Option: (61) Client identifier
        Length: 20
        Type: 0
        Client Identifier: 00D09E-15171N098922
    Option: (57) Maximum DHCP Message Size
        Length: 2
        Maximum DHCP Message Size: 1500
    Option: (50) Requested IP Address (99.105.33.21)
        Length: 4
        Requested IP Address: 99.105.33.21
    Option: (54) DHCP Server Identifier (172.9.164.1)
        Length: 4
        DHCP Server Identifier: 172.9.164.1
    Option: (60) Vendor class identifier
        Length: 12
        Vendor class identifier: 2WHPL 10.5.3
    Option: (124) V-I Vendor Class
        Length: 5
        Enterprise: 2Wire, Inc. (4839)
        CableLab Address Mode: 0
        NetInfo Parent Server Tag: [Empty]
    Option: (55) Parameter Request List
        Length: 19
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (2) Time Offset
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (6) Domain Name Server
        Parameter Request List Item: (15) Domain Name
        Parameter Request List Item: (42) Network Time Protocol Servers
        Parameter Request List Item: (44) NetBIOS over TCP/IP Name Server
        Parameter Request List Item: (46) NetBIOS over TCP/IP Node Type
        Parameter Request List Item: (47) NetBIOS over TCP/IP Scope
        Parameter Request List Item: (23) Default IP Time-to-Live
        Parameter Request List Item: (24) Path MTU Aging Timeout
        Parameter Request List Item: (25) Path MTU Plateau Table
        Parameter Request List Item: (26) Interface MTU
        Parameter Request List Item: (35) ARP Cache Timeout
        Parameter Request List Item: (36) Ethernet Encapsulation
        Parameter Request List Item: (119) Domain Search
        Parameter Request List Item: (121) Classless Static Route
        Parameter Request List Item: (249) Private/Classless Static Route (Microsoft)
        Parameter Request List Item: (212) 6RD
    Option: (125) V-I Vendor-specific Information
        Length: 48
        Enterprise: The Broadband Forum (3561)
            Length: 43
            Option 125 Suboption: (1) DeviceManufacturerOUI
                Length: 7
                DeviceManufacturerOUI: 00:d0:9e (2Wire Inc)
            Option 125 Suboption: (2) DeviceSerialNumber
                Length: 10
                DeviceSerialNumber: homeportal
            Option 125 Suboption: (3) DeviceProductClass
                Length: 6
                DeviceProductClass: 5268AC
            Option 125 Suboption: (4) GatewayManufacturerOUI
                Length: 12
                GatewayManufacturerOUI: 15171N098922
    Option: (255) End
        Option End: 255

0000  ff ff ff ff ff ff d4 b2 7a 6b b1 4c 81 00 60 00   ........zk.L..`.
0010  08 00 45 28 01 92 ed d1 40 00 80 11 0b 62 00 00   ..E(....@....b..
0020  00 00 ff ff ff ff 00 44 00 43 01 7e a4 ba 01 01   .......D.C.~....
0030  06 00 4d 57 9a c2 00 00 00 00 00 00 00 00 00 00   ..MW............
0040  00 00 00 00 00 00 00 00 00 00 d4 b2 7a 6b b1 4c   ............zk.L
0050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
00f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0100  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0110  00 00 00 00 00 00 00 00 00 00 63 82 53 63 35 01   ..........c.Sc5.
0120  03 3d 14 00 30 30 44 30 39 45 2d 31 35 31 37 31   .=..00D09E-15171
0130  4e 30 39 38 39 32 32 39 02 05 dc 32 04 63 69 21   N0989229...2.ci!
0140  15 36 04 ac 09 a4 01 3c 0c 32 57 48 50 4c 20 31   .6.....<.2WHPL 1
0150  30 2e 35 2e 33 7c 05 00 00 12 e7 00 37 13 01 02   0.5.3|......7...
0160  03 06 0f 2a 2c 2e 2f 17 18 19 1a 23 24 77 79 f9   ...*,./....#$wy.
0170  d4 7d 30 00 00 0d e9 2b 01 07 30 30 44 30 39 45   .}0....+..00D09E
0180  00 02 0a 68 6f 6d 65 70 6f 72 74 61 6c 03 06 35   ...homeportal..5
0190  32 36 38 41 43 04 0c 31 35 31 37 31 4e 30 39 38   268AC..15171N098
01a0  39 32 32 ff                                       922.

**Comment by b1tninja** [comment]
I'd be totally fine with the meaning of the options being ignored and just a way to specify the encoded bytes.... The interceptor comment was about passively learning dhcp leases and applying them to an interface.

One other interesting thing I noticed was 8021q being used

**Comment by ssahani** [comment]
We should close this now.
