### ISSUE TITLE
Systemd forgets ExecStart/ExecStartPre/ExecReload metadata on daemon-reload

### ISSUE THREAD

**Issue by mphilipps** [systemd/systemd#12375]
Tested with 241.

**Used distribution**
Debian Stretch with systemd from backports.

**Expected behaviour you didn't see**
 > I expected to see when the service was last reloaded.

**Unexpected behaviour you saw**
 > start_time gets reset to n/a after a daemon-reload

**Steps to reproduce the problem**

systemctl reload ssh.service
systemctl show ssh.service --property ExecReload
systemctl daemon-reload
systemctl show ssh.service --property ExecReload

hi,
It appears that the moment I do a systemctl daemon-reload systemd immediately forgets the metadata for ExecStart,ExecStartPre and ExecReload. While the ExecStart time can still be retrieved from ExecMainStartTimestamp, I don't see a similar way to get a timestamp of the last time a service was reloaded.

**Comment by poettering** [comment]
hmm, is it possible that "ssh.service" simply isn't pinned into memory? i.e. if sshd.service is stopped then "systemctl show" will load the unit into memory temporarily and then unload it right after. This means the status data is not retained...

**Comment by mphilipps** [comment]
It is not specific to ssh. I just used ssh as an example of a reloadable service that presumably exists on every system.

What do you mean with pinned into memory?  If I were to write a service unit file, how would I alleviate the issue?

**Comment by poettering** [comment]
Please have a look at the docs:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20Garbage%20Collection

**Comment by mphilipps** [comment]
ok according to the docs the service should be pinned into memory, because 2. (ssh.service is running) and 7. ( the cgroup contains the sshd process ).

Therefore according to:
> Use systemctl daemon-reload or an equivalent command to reload unit configuration while the unit is already loaded. In this case all configuration settings are flushed out and replaced with the new configuration (which however might not be in effect immediately), **however all runtime state is saved/restored**.

The runtime state for property ExecReload shouldn't have been lost in step 3 of the reproduction.

**Comment by hochraldo** [comment]
any update on this? I am currently facing the same issue

**Comment by poettering** [comment]
There was a bug in the reload code, which has long been fixed. Update to current systemd.

Closing.

If you can reproduce this with 249 we can reopen.

**Comment by mphilipps** [comment]
I just reproduced that using 249 using the instructions from the first post. The ssh service is called sshd here.


```
# systemctl --version
systemd 249 (249) +PAM -AUDIT -SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 +LZ4 -XZ -ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
# systemctl reload sshd.service
# systemctl show sshd.service --property ExecReload
ExecReload={ path=/bin/kill ; argv[]=/bin/kill -HUP $MAINPID ; ignore_errors=no ; start_time=[Thu 2021-08-12 14:04:11 CEST] ; stop_time=[Thu 2021-08-12 14:04:11 CEST] ; pid=4888 ; code=exited ; status=0 }
# systemctl daemon-reload
# systemctl show sshd.service --property ExecReload
ExecReload={ path=/bin/kill ; argv[]=/bin/kill -HUP $MAINPID ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
```

@poettering Please reopen so that it may get fixed.

**Comment by mphilipps** [comment]
@poettering ping.
