### ISSUE TITLE
%h and %u specifier documentation misleading

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#12389]
The behaviour of the `%h` specifier changed a few times over the years
See e.g.

https://github.com/systemd/systemd/blob/master/NEWS#L3926
or
https://github.com/systemd/systemd/blob/master/NEWS#L6855

systemd.unit(5) says
```
       │"%h"      │ User home directory                     │ This is the home directory of the user   │
       │          │                                         │ running the service manager instance. In │
       │          │                                         │ case of the system manager this resolves │
       │          │                                         │ to "/root".     
```

So I made this little test service
```
# systemctl cat test.service 
# /etc/systemd/system/test.service
[Unit]
Description=specifier test

[Service]
Type=oneshot
ExecStart=/bin/echo %u
ExecStart=/bin/echo %h

...
# journalctl -u test.service
Apr 25 11:43:53 pluto systemd[1]: Starting specifier test...
Apr 25 11:43:53 pluto echo[16015]: root
Apr 25 11:43:53 pluto echo[16017]: /
Apr 25 11:43:53 pluto systemd[1]: test.service: Succeeded.
Apr 25 11:43:53 pluto systemd[1]: Started specifier test.
```

So, not only the path in the documentation seems incorrect (`/root` vs `/`) , we should also make it much more obvious in the documentation that setting the `User` has no influence on `%h`.
We just had (another) downstream bug report where a user expected `%h` to be resolved to the home directory of the running user.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927911

**Comment by mbiebl** [comment]
The same is probably true for `%u`
```
# systemctl cat test2.service 
# /etc/systemd/system/test2.service
[Unit]
Description=specifier test

[Service]
Type=oneshot
ExecStart=/bin/echo %u
ExecStart=/bin/echo %h
User=michael

# journalctl -u test2.service 
Apr 25 11:47:02 pluto systemd[1]: Starting specifier test...
Apr 25 11:47:02 pluto echo[14039]: root
Apr 25 11:47:02 pluto echo[14043]: /
Apr 25 11:47:02 pluto systemd[1]: test2.service: Succeeded.
Apr 25 11:47:02 pluto systemd[1]: Started specifier test.
```

**Comment by bl33pbl0p** [comment]
I assume the reason it doesn't work for User= is doing lookups in the user db and potentially calling into NSS is not desired (since loading of units happens in PID 1 and specifier resolution happens at load time).

I must say this choice makes things a whole lot less useful, I have seen continually seen people (on IRC and other places) wanting this to work for the specified user, not the instance it is run under (system or user)...

**Comment by mbiebl** [comment]
@bl33pbl0p yes, it's because of avoiding NSS in PID1. See the linked references to the NEWS file in my original message.

**Comment by mbiebl** [comment]
Has it been considered to use a helper binary which would do the user name/home directory lookup outside of PID1 and pass back the result?

**Comment by poettering** [comment]
> Has it been considered to use a helper binary which would do the user name/home directory lookup outside of PID1 and pass back the result?

there are two problems with NSS: nss modules are crap and lookups synchronous (with individual modules doing local IPC which systemd might be involved in, for example for socket or bus activation). doing something out of process will help on the first issue, but definitely not on the second issue: we can't really have configuration file parsers block on external IPC regardless if it blocks on that diretcly or indirectly through a child process

**Comment by pombredanne** [comment]
The documentation is still highly misleading leading to wasting time trying to get `%u` or `%h` working somehow based on `User`. It should be explicit. There should be a way to get to `$HOME` or `~` though but it seems impossible for `WorkingDirectory`

**Comment by class101** [comment]
This should be changed or removed, in my opinion, updating the comment is not enough.

There is no point of a variable that is static , not variable and always resolving to `root`.

It is not even useful to get the user from the `User=` directive either.

Ideally, I want the name of the user running the current session `/usr/lib/systemd/systemd --user`
