### ISSUE TITLE
Assert in device_enumerator_scan_devices() within device_compare()

### ISSUE THREAD

**Issue by here-abarany** [systemd/systemd#12384]
**systemd version the issue has been seen with**
242

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
Assert is not fired.

**Unexpected behaviour you saw**
The following assert is thrown, aborting the application:

    Assertion 'sd_device_get_devpath(a, &devpath_a) >= 0' failed at ../systemd-stable/src/libsystemd/sd-device/device-enumerator.c:285, function device_compare(). Aborting.

**Steps to reproduce the problem**
This was observed in a Qt-based application on a KDE system when default constructing a QFileDialog. I tried other Qt applications which worked, so I don't know if there's some other way they call into QFileDialog (e.g. constructing it with a directory to start at) that avoids this assertion. There was a KDE function in the callstack, so I can't say if this would only be visible on a KDE system or if running a Qt application on Gnome would also run into this assertion.

I have two SSDs attached to this machine with multiple partitions, some of which are unmounted. (partitions for Windows on a dual-boot machine)

Downgrading to 241 fixed the assertion.

**Comment by yuwata** [comment]
Could you provide more information? Are there any relevant logs in journal?

**Comment by here-abarany** [comment]
I've attached a journal from a boot that had the issue. There are a couple of errors at boot time, though they don't seem to be related.

There are a few messages from the application that shows the problem (geoviz.nero), and while they are unrelated (about QDockWidget not part of the layout), they at least give you a place to look. While that log has some log messages from FUSE and ntfs-3g, those are from mounting a Windows partition through the file manager and don't appear to be related to the assert. (other runs I have don't have those logs around when the assert occurred) There are some XCB errors as well, but those also seem unrelated, since I was running the application in the debugger and the debugger stopped at the assert within the call to device_enumerator_scan_devices(), ruling out an X11 error aborting the program.

[journal.txt](https://github.com/systemd/systemd/files/3114745/journal.txt)

**Comment by here-abarany** [comment]
I installed a debug build locally and managed to track down the issue. greedy_realloc() was recently optimized to use malloc_usable_size(). However, at least with the version of glibc that currently ships with Arch Linux, realloc() isn't guaranteed to copy the data in-between the originally requested size and the end of malloc_usable_size(). As a result, when the enumerator array is built up elements would be lost.

I have a pull request to revert the optimization that introduced the issue. https://github.com/systemd/systemd/pull/12438 The assert no longer fires with this assert applied.

**Comment by dotkrnl** [comment]
@here-abarany

Could you please help me to find the code of this version of `glibc` which copies only the originally requested size?  I don't see a version of `glibc` which has this behavior, and I am actually running into another issue caused by the `malloc_usable_size()` usage in `greedy_realloc()` -- segmentation fault.  This issue happens when I am running Vivado inside an LXC container, which called `greedy_realloc()` from `libudev`.

I am trying to track down the actual reason for my issue, but since removing the `malloc_usable_size()` optimization makes it work, I would like to know if you have any suggestions.

Thanks!

**Comment by here-abarany** [comment]
I would have been running whatever version of glibc was the latest released version at the time the original issue was reported. This was based on the observed behavior, seeing that not all of the memory was copied over in the realloc, I didn't trace into the actual glibc code.

**Comment by dotkrnl** [comment]
Thank you for taking the time replying this!  I will get a debug build to see what went wrong in my case.
