### ISSUE TITLE
VT switching, sd_pid_get_session and sd_uid_get_graphical for systemd based sessions

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#12399]
Unfortunately, there seems to be some confusion as to which session processes belong to when they are started through systemd. This currently means for example that we cannot VT switch if we start `gnome-shell` using systemd, as the DBus call fails with:
```
Caller does not belong to any known session
```

As `sd_pid_get_session` cannot work in this case, GNOME is adding code in various places to instead use `sd_uid_get_display` with a fallback to iterating the session and also including ones of type `greeter`[(in mutter)](https://gitlab.gnome.org/GNOME/mutter/commit/4837ea3434962f10d403fc8b7c65d411926c461b) or iterating users sessions to find the oldest graphical one [(e.g. in gnome-session)](https://gitlab.gnome.org/GNOME/gnome-session/merge_requests/13/diffs?commit_id=dcdb7630881c9fd4362ee568b257bedae60a60f0).

It seems like logind itself needs the same kind of heuristics to allow gnome-shell/mutter to do VT switching when it is being launched through systemd. `sd_uid_get_display` cannot currently be used for this because `greeter` type session are excluded.

I imagine that this heuristic could be public API.

CC: @smvc, @ iainlane

**Comment by hadess** [comment]
CC: @smcv and @iainlane

**Comment by poettering** [comment]
services forked off "systemd --user" belong to no session. or if you so will are shared by them all.

We should probably tweak the logic so that sd_uid_get_display() picks a greeter session if nothing else is around.

**Comment by poettering** [comment]
Fix waiting in #12424.

**Comment by benzea** [comment]
@poettering does this really fully address the issue?

I do see how this means we can use `sd_uid_get_display` in places, and things will work appropriately. However, it looks to me like the internal logind usage still uses the equivalent of `sd_pid_get_session` for authentication purposes of DBus calls. So the VT switching and other method calls will still fail if the services making the requests has been started using the systemd user instance.

**Comment by poettering** [comment]
What is the precise gnome-shell makes? ActivateSession()? What#s the argument? The "Caller does not belong to any known session" is only generated if you then specify an empty parameter, i.e. leave the session ID empty. In that case we'll determine the session of the client and use that.

The assumption would always be that the client specifies the session... We could of course tweak that and if the caller is not member of a session then switch to the user's display session, if that's what you are asking?

Anyway, what's the precise bus call gnome-shell/gdm does? What are its arguments? Why can't it specify the session to activate anyway?

**Comment by benzea** [comment]
Ah! I didn't realise that you could specify the session the process belongs to. In that case it should work fine with a few more changes scattered around in places.

**Comment by iainlane** [comment]
I'm not set up ATM to test this, but [here's the call](https://gitlab.gnome.org/GNOME/mutter/blob/master/src/backends/native/meta-launcher.c#L555) to `ActivateSession()`, i.e. we do pass `NULL` there. We've already found our own session ID at that point though, so we could indeed save it and pass that in. Would that fix the problem? I think I'm missing a detail as TBH I'm not completely clear why `ActivateSession()` is in the frame for VT switching and not `SwitchTo()`, though.

**Comment by benzea** [comment]
The call to `SwitchTo()` was the one that produced the error for me, it is just a few lines down in the same file. Either way, it is perfectly viable to fix the NULL parameter on the mutter side (and I suspect we might need changes in g-s-d too, need to double check).

**Comment by iainlane** [comment]
Sounds correct to fix it, just not sure it'll address the initial problem. Is it that `SwitchTo` is looking up the caller's session?

**Comment by poettering** [comment]
So, I added another commit to the aforementioned PR that also ensures that when you specify an empty session you get your user's display session if you are not a member of any session. This should hence magically fix things for you too, right? ptal

**Comment by benzea** [comment]
Backported the relevant patches to F30 and tested it together with the GNOME session running on systemd.

VT switching is working without any issues now. So I would say the systemd change is good.

Can we rely on systemd v243 for the next GNOME release (3.34)? If not, then I'll add the workarounds on the GNOME side.

**Comment by poettering** [comment]
When's the next GNOME release? We try to do releases often, but it never works as quick as we'd like to ;-)

**Comment by benzea** [comment]
About 5 months :)

**Comment by poettering** [comment]
That sounds totally doable then.
