### ISSUE TITLE
loginctl enable/disable-linger error: read-only file system

### ISSUE THREAD

**Issue by oddfellow** [systemd/systemd#12401]
**systemd version the issue has been seen with**
> 242.0-1

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > loginctl enable-linger USERNAME
working

**Unexpected behaviour you saw**
 > loginctl enable-linger USERNAME
gives "Could not enable linger: Read-only file system"

**Steps to reproduce the problem**
using a non-modified Arch Linux systemd install and try to enable (or disable) lingering for a user with the commands above.

**Workarounds/solutions**
The upstream provided unit file for systemd-logind.service had some modifications in this release which prevents writing the username file to /var/lib/systemd/linger/

Modifying the unit file (e.g. with an override) and adding the path above

`ReadWritePaths=/etc /run /var/lib/systemd/linger`

seems to work. At least the lingering works again. I don't know if this is the right workaround though...

**Comment by poettering** [comment]
Fix waiting in #12424

**Comment by b1tninja** [comment]
https://github.com/systemd/systemd/commit/6996df9b864981980f5b713dc5c7d506a7a4b9bf

**Comment by dmp1ce** [comment]
As a workaround, until `v243` is released, I'm using `touch /var/lib/systemd/linger/$USER` to enable lingering.

**Comment by nesadi** [comment]
touch /var/lib/systemd/linger/$USER doesn't work for me

**Comment by dmp1ce** [comment]
@nesadi How do you know it isn't working to enable lingering? It seems to be working for me to run user timers. I can see `systemd` running when checking with `ps -u myuser` from another user when `myuser` is not logged in.

```
$ ps -u myuser
  PID TTY          TIME CMD
  857 ?        00:01:13 systemd
  862 ?        00:00:00 (sd-pam)
```
