### ISSUE TITLE
Version 242 causes docker issues

### ISSUE THREAD

**Issue by returntrip** [systemd/systemd#12412]
**systemd version the issue has been seen with**
> 242.0-1and above

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `docker info` should work correctly

**Unexpected behaviour you saw**
 > `docker info` stops working with this error: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Steps to reproduce the problem**
1) Upgrade to systemd 242.0-1 or above
2) Issue `docker info` or `docker ps` and docker will report the following issue: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

N.B.: Downgrading to 241.93-1 restores docker functionalities

**Comment by poettering** [comment]
This is not actionable. Please provide logs. Output of "systemctl status" on the docker service and so on.

**Comment by returntrip** [comment]
Apologies, I have upgrade to version 242 and now providing more info:

The docker service is running correctly according to its status.

See gist:https://gist.github.com/returntrip/702c635e81f5339504c4f98979ba4417

I might a bit of hand holding if specific logs are needed

**Comment by poettering** [comment]
is it possible that /var/run is not a symlink to /run on your system? It appears that the socket unit listens on /run/docker.sock but your client expects it in /var/run/docker.sock? normally it shouldn't matter which ones is used, since the dirs should be the same by means of the /var/run symlink, but maybe your system is borked in this regard?

Note that /var/run *must* be a symlink for systemdto operate on it safely, and this is documented in README.

**Comment by poettering** [comment]
(note that current systemd will patch paths in .socket units from /var/run to /run if it encounters them, and even warns about that. Older systemd didn't do that and thus didn't react allergic in this regards if /var/run isn't a symlink to /run. However, even without that it's still broken to have a system like that, and it always has been on systemd)

**Comment by laloch** [comment]
On Archlinux /var/run is `run -> ../run`, so yes, it is a relative symlink to /run.

**Comment by returntrip** [comment]
@poettering You were indeed right. The symlink was not there. I have symlinked `/run` correctly and docker is working again. I am not sure why/how the symlink was not present and I do not understand why all works fine with 241.93-1 and below. Thanks for the help in fixing this and apologies for stealing your time.

**Comment by grazzolini** [comment]
@returntrip can you please provide more information. I'm running Arch here with systemd 242.0-3 and this is not an issue for me.

**Comment by returntrip** [comment]
@grazzolini it might be human error, I am not excluding it. I am not sure since when the symlink was removed. Unfortunately, I cannot find anything in history concerning the removal of the symlink

**Comment by poettering** [comment]
> … and I do not understand why all works fine with 241.93-1 and below.

As mentioned, older versions of systemd didn't implicitly patch /var/run/ into /run/ in socket units. current systemd versions do and log about that. Hence previously you got away with the two dirs being separate as everything used the /var/run/ socket, and nothing the /run/ one. But now systemd will create the listening socket in /run/ but the docker client wants to talk to the /var/run/ one, and that's where it fails.

Anyway, let's close this, as the symlink is a clearly documented requirement of systemd.
