### ISSUE TITLE
UseRoutes=false still leads to dropped routes on dhcp renew

### ISSUE THREAD

**Issue by sulaweyo** [systemd/systemd#12426]
**systemd version the issue has been seen with**
> systemd 242 (242.0-3-arch)

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > If UseRoutes=false static routes should be stable on dhcp ip refresh

**Unexpected behaviour you saw**
 > The static route is working but as soon as the dhcp lease expires and a new lease is acquired the static route is dropped

**Steps to reproduce the problem**
> Set a static route on a dhcp managed interface, set useroutes=false, wait for dhcp renew

**My config on the interface**
The host has 1 nic, a vlan vnic (with the default gateway on it) and a bridge for kvm as well as other local network stuff. The first route is to have a route to the private network, the second is to get announcements of a upnp streaming server to the correct interface.
This config used to work until arch updated from systemd 241.67-1 to 242.0-3. 

> [Match]
> Name=br0
> 
> [Network]
> DHCP=ipv4
> Domains=my.domain
> LinkLocalAddressing=no
> IPv6AcceptRA=no
> BindCarrier=eno1
> 
> [DHCP]
> UseRoutes=false
> SendHostname=true
> Hostname=my-hostname
> ClientIdentifier=mac
> 
> [Route]
> Destination=192.168.1.0/24
> Scope=link
> 
> [Route]
> Destination=239.255.255.250
> Scope=link

**Comment by ssahani** [comment]
fix is https://github.com/systemd/systemd/pull/12427

**Comment by sulaweyo** [comment]
I have to say i'm highly impressed by your speed! This is just awesome

**Comment by ssahani** [comment]
Thank you.
