### ISSUE TITLE
missing driver information for DAX pmem device

### ISSUE THREAD

**Issue by sayeedh** [systemd/systemd#12436]
**systemd version the issue has been seen with**
> libudev version 1.6.2

**Used distribution**
 > Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Expected behavior you didn't see**
 > The API udev_device_get_driver returns null (instead of the driver path) for a DAX mounted pmem device.
**Unexpected behavior you saw**
 > Based on the underlying code, the current code expects to find the driver link under syspath. However, for a DAX persistent memory device, the driver link is under syspath/device. 
```
ll /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region1/pfn1.1/block/pmem1/
total 0
-r--r--r-- 1 root root 4096 Apr 19 09:38 alignment_offset
-rw-r--r-- 1 root root 4096 Apr 19 09:38 badblocks
lrwxrwxrwx 1 root root    0 Apr 19 09:38 bdi -> ../../../../../../../../virtual/bdi/259:3
-r--r--r-- 1 root root 4096 Apr 19 09:38 capability
drwxr-xr-x 2 root root    0 Apr 19 09:38 dax
-r--r--r-- 1 root root 4096 Apr 19 09:38 dev
lrwxrwxrwx 1 root root    0 Apr 19 09:38 device -> ../../../pfn1.1
-r--r--r-- 1 root root 4096 Apr 19 09:38 discard_alignment
-r--r--r-- 1 root root 4096 Apr 19 09:38 ext_range
drwxr-xr-x 2 root root    0 Apr 19 09:38 holders
-r--r--r-- 1 root root 4096 Apr 19 09:38 inflight
drwxr-xr-x 2 root root    0 Apr 19 09:38 power
drwxr-xr-x 2 root root    0 Apr 19 09:38 queue
-r--r--r-- 1 root root 4096 Apr 19 09:38 range
-r--r--r-- 1 root root 4096 Apr 19 09:38 removable
-r--r--r-- 1 root root 4096 Apr 19 09:38 ro
-r--r--r-- 1 root root 4096 Apr 19 09:38 size
drwxr-xr-x 2 root root    0 Apr 19 09:38 slaves
-r--r--r-- 1 root root 4096 Apr 19 09:38 stat
lrwxrwxrwx 1 root root    0 Apr 19 09:38 subsystem -> ../../../../../../../../../class/block
drwxr-xr-x 2 root root    0 Apr 19 09:38 trace
-rw-r--r-- 1 root root 4096 Apr 19 09:38 uevent
```

**Steps to reproduce the problem**
```
struct udev* uDev = udev_new();
struct udev_device* udevDevice = udev_device_new_from_devnum( uDev,  'b', deviceId);
const char* driverPath  = udev_device_get_driver(udevDevice);
```

**Comment by poettering** [comment]
Block class devices have no drivers, they never do. It's a kernel design decision. Only the originating devices, i.e. what you find in device/ have that, hence only they expose a "driver" symlinks

Moreover, this bug tracker focusses on issues on the two most recently released upstream systemd versions, i.e. 241 and 242. your version is a lot older than that. For such old versions, please contact your downstream distro instead. To minimize disappointments in this regard the issue submission form tries to be very clear about that actually.

Closing. Hope that makes sense.
