### ISSUE TITLE
journal: add USER_INVOCATION_ID to all messages generated by user managed unit

### ISSUE THREAD

**Issue by tchernomax** [systemd/systemd#12474]
It is not possible to filter user unit logs by _SYSTEMD_INVOCATION_ID as all the user unit shares the INVOCATION_ID of the user@UID.service they run under.

However there is a USER_INVOCATION_ID which isn't documented and seems to be the equivalent of _SYSTEMD_INVOCATION_ID for user unit.
But USER_INVOCATION_ID is only set to message written by systemd itself (eg. message written by the by the process managed by a user unit doesn't have the USER_INVOCATION_ID metadata).

**Describe the solution you'd like**

USER_INVOCATION_ID should be documented (maybe prefix it with a "_" ; same as _SYSTEMD_INVOCATION_ID) and added to all message of user unit logs.

**Comment by anitazha** [comment]
Does it make sense to fix the behavior of `_SYSTEMD_INVOCATION_ID` for user units so that it matches the behavior of system units? Rather than making another field? I'm not sure what the benefit of the current behavior is except that it might break people using the field as is.
