### ISSUE TITLE
[resolved] IPv6 DNS servers do not expire once RAs stop arriving

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#12477]
**systemd version the issue has been seen with**
242 and 239

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
After removing a rogue router from my network, the IPv6 DNS server it was advertising should have eventually expired and disappeared from the `resolvectl` output.

**Unexpected behaviour you saw**
Two weeks and a systemd upgrade later, and the invalid DNS server address is still reported by `resolvectl` as one of the DNS servers in use.  When the system decides to start using that IP address, DNS breaks until `systemd-resolved` is restarted.  After a restart the active server changes to a working one, but the invalid one remains in the list and eventually gets selected again.

**Steps to reproduce the problem**
Difficult to say as I'm not sure exactly how the IP address appeared originally.  I imagine if you have a machine broadcasting IPv6 RAs or similar with a DNS server address included then this problem will happen.

I am somewhat stuck as to how one might clear out these long expired DNS server entries.  Even if I delete /etc/resolv.conf, `resolved` just writes it out again complete with the expired DNS servers that haven't been advertised for over two weeks.

Where does `resolved` store its IP addresses for DNS servers?  Can we get an expiration time added that is reset on each RA advertisement, so that accidental RA broadcasts won't fill the system's DNS server list with random junk?

Perhaps a larger issue is that a rogue machine on the network can broadcast an RA with the address of a rogue IPv6 DNS server, which systemd will happily start using, allowing DNS to be hijacked with no warning to the user.

**Comment by poettering** [comment]
which ipv6 ra client do you use? networkd? networkmanager?

**Comment by Malvineous** [comment]
I'm using `systemd-networkd`.  I have `/etc/systemd/network/50-static.network` with a static IPv6 address (but no other IPv6 config options).

**Comment by poettering** [comment]
what does "networkctl status -a" say when this happened?

(note that resolved just consumes the RA data networkd collects. most likely it is networkd that didn't flish out the RA data not resolved that kept it)

**Comment by Malvineous** [comment]
I'm going to close this as I had the issue come up again under slightly different circumstances.  This time my router was advertising IPv6 routes and I wanted to remove an old DNS server.  Once I removed it from the router advertisements, systemd-networkd immediately dropped the old DNS server and `resolvectl` stopped showing it as well.

So it looks like the problem appears to be fixed.
