### ISSUE TITLE
nss-systemd not behaving properly during early boot

### ISSUE THREAD

**Issue by rhertzog** [systemd/systemd#12492]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Kali / Debian Testing (package version 241-3)

**Expected behaviour you didn't see**
 > a quick boot process

**Unexpected behaviour you saw**
 > sudo calls during boot process taking 3 minutes each

**Steps to reproduce the problem**

Grab a weekly Kali light image, for example here: http://cdimage.kali.org/kali-weekly/kali-linux-light-2019-W19-amd64.iso
Boot it in live mode and see how live-config.service is taking 6 minutes to start.

live-config is a set of scripts configuring the machine in the early boot process (DefaultDependencies=no, Before=basic.target, After=local-fs.target systemd-tmpfiles-setup.service) and some of the scripts are using "sudo -u" to operate as non-root. I traced the delays to those sudo calls.

If you want to debug a little bit, you can enable the debug-shell in the kernel command line (just press TAB in syslinux to show the command line, add "systemd.debug-shell=1"). Any call to "su", "sudo" or "runuser" in the debug shell during the 6 minutes where it's blocked during boot results in the process being stalled. I installed strace in the debug shell (`dhclient -i eth0; apt install strace`) and found out that it was trying to send a message to the DBUS socket and was waiting a reply (that never comes as dbus is not started yet).

Then I tried to disable nss-systemd (dropped "systemd" in /etc/nsswitch.conf) and all the su/sudo/runuser calls are now working instantly again.

So there's something fishy in the behaviour of nss-systemd in the early boot while dbus is not running yet. This problem is relatively recent in Kali (it was not there in our previous release, 2019.1, eg. here http://cdimage.kali.org/kali-2019.1a/kali-linux-light-2019.1a-amd64.iso).

**Comment by poettering** [comment]
Hmm, i guess these are services that are ordered between dbus.socket and dbus.service. i.e. where the dbus socket is already connectible but that delay dbus.daemon to be actually started. 

I guess we should stop using dbus for these kinds of things altogether.
