### ISSUE TITLE
RootDirectory with User not working

### ISSUE THREAD

**Issue by skupkosk** [systemd/systemd#12498]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Debian 9 with backported system (241-3~bpo9+1)

**Expected behaviour you didn't see**
 > start rsyslog under User privileges with root set to RootDirectory
Want to mimic the startup of the service in init script on Debian8 (which is running fine):
`~# start-stop-daemon --start --quiet --pidfile "/srv/inst/var/run/rsyslogd.pid" --chuid user:group --chroot "/srv/inst" --exec "/usr/sbin/rsyslogd" -- -i  /var/run/rsyslogd.pid -4 -x`
More information on https://manpages.debian.org/dpkg/start-stop-daemon.8.en.html

**Unexpected behaviour you saw**
 > service complains about CHROOT/Operation not permitted

**Steps to reproduce the problem**
Proposed service file
```
~# cat 
[Unit]
Description=System Logging Service in chroot
ConditionPathExists=/srv/%i

[Service]
Type=simple
User=user
Group=group
PermissionsStartOnly=true
WorkingDirectory=/var/spool/rsyslog
# adding these capabilities does not help
AmbientCapabilities=CAP_SYS_CHROOT CAP_NET_BIND_SERVICE
RootDirectory=/srv/%i
RootDirectoryStartOnly=true
ExecStart=/usr/sbin/rsyslogd -n
StandardOutput=journal

[Install]
WantedBy=multi-user.target
Alias=syslog-chroot.service
~# systemctl status rsyslog-chroot@inst.service
<some lines>
  Process: 29898 ExecStart=/usr/sbin/rsyslogd -n (code=exited, status=210/CHROOT)
<some lines>
 rsyslog-chroot@inst.service: Changing to the requested working directory failed: Operation not permitted
 rsyslog-chroot@inst.service: Failed at step CHROOT spawning /usr/sbin/rsyslogd: Operation not permitted
```
When User commented out, the service just start successfully.

**Comment by poettering** [comment]
Hmm, yeah, if you use plain chroots then this is currently a bit ugly and we end up setresuid() first, and chroot/chdir second. This is caused by 56ef8db9f5e.

**Comment by behrmann** [comment]
Sorry for this game of whack-a-mole.

I can reproduce this (on the same setup as @skupkosk) with
```
[Unit]
Description=Debug chroot

[Service]
Type=oneshot
User=daemon
AmbientCapabilities=CAP_SYS_CHROOT 
RootDirectory=/srv/stretch-chroot
ExecStart=/bin/bash -c 'echo hello world from $(id -u) and $(id -ru) at $(pwd)'
```
after debootstrapping a minimal system to `/srv/stretch-chroot` (and running `mkdir /srv/stretch-chroot/tmp/inchroot`)

I see that after calling [`ensure_user`](https://github.com/systemd/systemd/blob/master/src/core/execute.c#L1083) the privileges to call `chroot` in [`apply_working_directory`](https://github.com/systemd/systemd/blob/master/src/core/execute.c#L2512) might be lacking, but isn't this what `AmbientCapabilities=` and the dance in `ensure_user` is for?

Could this problem be sensibly solved by splitting `apply_working_directory` into two functions (one to `chroot` and one to `chdir`) or is this the point to collect all sensible [orderings](https://github.com/systemd/systemd/pull/10577#discussion_r229650125)?

**Comment by poettering** [comment]
yeah, i guess we need to split this

**Comment by disaster123** [comment]
Is there any workaround available for users running debian buster which has broken systemd 241?

**Comment by behrmann** [comment]
@disaster123 Please open a Debian bug with a note to this upstream bug and the [PR](https://github.com/systemd/systemd/pull/12860) that fixes it. I'm sure they will backport the patch then.

If it is an option and you need quicker relief, I recommend backporting a newer version. Unfortunately a systemd newer than 241 is not yet in buster-backports. If you must stay on 241, you can build that version yourself and drop the patch into `debian/patches` (don't forget to update the `series` file).
