### ISSUE TITLE
regression: crashing journal due to watchdog

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#125]
The for (;;) loop in server_process_datagram might prevent journal
from feeding the watchdog if there is always something to receive in
the syslog socket. Potentially journald is restarted, applications
stall if the syslog socket is staying full....

I thought about fixing it by checking the watchdog on every iteration
of for (;;) by using watchdog_last, watchdog_period and feeding
watchdog if necessary but none of those properties are public.

Current rate limit check is done right before we store the message
(after we receive it, after we forward it to console, wall, kmsg). I
think it is too late.

Maybe the best approach is having a rate limit on sd-event
(sd-event-source) so we can map rate limit options in journald.conf to
journal's sd-event.

Thoughts?

PS: Moving the discussion off the mailing list to get it tracked.

**Comment by poettering** [comment]
Wouldn't it suffice if we simply bump the priority of the watchdog event source to something very high, so that it is always dispatched before anything else?

**Comment by poettering** [comment]
Hmm, ignore that, that made no sense, we always dispatch the watchdog event, in every single loop, if it's due, and we do so before anything else.

Not sure I grok the issue then. Can you elaborate how precisely this can happen?

**Comment by utezduyar** [comment]
Imagine there is always something to fetch at this fd, https://github.com/systemd/systemd/blob/cde40acc805b855909b95f15fd9a3111e40be672/src/journal/journald-server.c#L1171.

In this case, the loop (https://github.com/systemd/systemd/blob/cde40acc805b855909b95f15fd9a3111e40be672/src/journal/journald-server.c#L1116) will never quit. We will never return back to event processing where we feed the watchdog. 

Guy with bad intention starts multiple processes, `while (1) logger "hello"` and it should be enough to clog the journal.

**Comment by poettering** [comment]
Can you check if PR #150 fixes the issue for you please, @utezduyar? Thank you!

**Comment by poettering** [comment]
@utezduyar if this fixes the issue for you this can be promptly merged!

**Comment by utezduyar** [comment]
@poettering Verified!
