### ISSUE TITLE
default_system_bus didn't set to NULL when using sd_bus_default_flush_close()

### ISSUE THREAD

**Issue by Dixiashui** [systemd/systemd#12528]
**systemd version the issue has been seen with**
>latest version

**Used distribution**
 > loop create bus connection though
-sd_bus_default_system() ->sd_bus_default_flush_close()->sd_bus_default_system()[here will failed] in the same process context.

**Expected behaviour you didn't see**
 >function return value shows successful, but dbus connection can't be created

**Unexpected behaviour you saw**
 >function return value shows successful, but dbus connection can't be created

**Steps to reproduce the problem**
-invoke sd_bus_default_system()  to create a connection.
-invoke sd_bus_default_flush_close() to close the connection
-invoke sd_bus_default_system() to create a connection again
all steps is in the same process context.

**Comment by poettering** [comment]
Not sure I follow. Can you provide a minimal reproducer program (i.e. a short C source file) that shows this?

**Comment by poettering** [comment]
Let's close this due to lack of response.
