### ISSUE TITLE
UseDomains= seems ignored/bugged in [DHCP] section since 242 

### ISSUE THREAD

**Issue by msoltyspl** [systemd/systemd#12531]
**systemd version the issue has been seen with**
systemd 242 (242.19-1-arch)

**Used distribution**
Archlinux

**Expected behaviour you didn't see**
This after update from 241 to 242 - [DHCP] section seems to be ignoring UseDomains= regardless if it's set or to what, the domain provided by dhcp is now ignored.

**Steps to reproduce the problem**
Following network config reproduces the issue 100% for me:

```
[Match]
Name=eno1

[Link]
Unmanaged=no
RequiredForOnline=yes

[Network]
Description=direct cable
DHCP=ipv4
LinkLocalAddressing=no
MulticastDNS=no
DNSSEC=no
LLDP=routers-only
DNSDefaultRoute=yes

[DHCP]
UseDNS=true
UseDomains=true
UseRoutes=true
RouteMetric=200
```

resolvectl after that (missing: `DNS Domain: touk.pl` which was present in all earlier versions):

```
Link 3 (eno1)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 192.168.0.2
         DNS Servers: 192.168.0.2
```

**Comment by yuwata** [comment]
Could you test #12548?
