### ISSUE TITLE
Non-latin characters not rendered properly

### ISSUE THREAD

**Issue by chiraag-nataraj** [systemd/systemd#12532]
**systemd version the issue has been seen with**
> systemd 242 (242)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian sid/experimental

**Expected behaviour you didn't see**
 > Paths with mixed latin and non-latin characters rendered properly

**Unexpected behaviour you saw**
 > Non-latin characters don't appear

**Steps to reproduce the problem**
1. Create a folder (e.g. ದಸ್ತಾವೇಜುಗಳು) in `~`
2. Run a long-running process with `~/ದಸ್ತಾವೇಜುಗಳು` in one of the arguments as a `systemd` service
3. Note that `htop` (or similar) will display the process just fine
4. Note that `systemctl --user status <service>` will just...hide(?) the ದಸ್ತಾವೇಜುಗಳು part

I noticed this after running backup processes in various folders which were taking a long time (so `systemctl --user status` actually had processes to display).

**Comment by keszybz** [comment]
Indeed.
```
$ systemctl --user status run-r5257864b949841049646d2ced64f6df1.service
● run-r5257864b949841049646d2ced64f6df1.service - /home/fedora/ದಸ್ತಾವೇಜುಗಳು/sleep.sh ದಸ್ತಾವೇಜುಗಳ
   Loaded: loaded (/run/user/1000/systemd/transient/run-r5257864b949841049646d2ced64f6df1.service; transient)
Transient: yes
   Active: active (running) since Fri 2019-05-10 18:07:50 CEST; 6s ago
 Main PID: 1797 (sleep.sh)
   CGroup: /user.slice/user-1000.slice/user@1000.service/run-r5257864b949841049646d2ced64f6df1.service
           ├─1797 /bin/sh /home/fedora/ /sleep.sh
           └─1798 sleep 10000

May 10 18:07:50 fedora systemd[989]: Started /home/fedora/ದಸ್ತಾವೇಜುಗಳು/sleep.sh ದಸ್ತಾವೇಜುಗಳ.
```

**Comment by floppym** [comment]
That output looks correct to me in Google Chrome on Windows 10. Perhaps this is a problem with display in a terminal on Linux?

![issue12532](https://user-images.githubusercontent.com/504287/57650314-89ddbd00-7598-11e9-8b45-552b4fd60202.png)

**Comment by keszybz** [comment]
No, it's really a problem with our code which only considers ASCII printable characters as is clearly visible in the line that starts with 1797. The browser which is used to view the screenshot is not relevant.
