### ISSUE TITLE
make unable to run ninja

### ISSUE THREAD

**Issue by rdp** [systemd/systemd#12533]
CentOS 7.6.1810 building v242

$ make
ninja -C build
make: ninja: Command not found

though ninja-build exists.

**Comment by poettering** [comment]
old centos has renamed ninja to ninja-build. The compat makefile we include does not cater for that deviation. Please don't use the makefile, use meson/ninja directly.

**Comment by rdp** [comment]
How do you do a "make install" using ninja directly in this instance? Anyway my work around was to create a symlink to just "ninja" ...

**Comment by mbiebl** [comment]
I think I was the one asking for the `./configure` and `make` wrapper to be added to satisfy https://github.com/cgwalters/build-api

Not sure if that idea really took off and if we shouldn't just drop them. They seem to cause more confusion then actually help.

**Comment by mrc0mmand** [comment]
@rdp ```
meson build
ninja-build -C build
ninja-build -C build install
```
