### ISSUE TITLE
IPv6 address not getting listed in ifconfig/ip addr show

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#12550]
**systemd version the issue has been seen with**
systemd 241 (241-9-gc1f8ff8+)

**Expected behaviour you didn't see**
I am receiving the IPv6 address from the dhcp server. I expect that should be listed when i issue ip addr show command

**Unexpected behaviour you saw**
Below are the logs from the networkd, where i see that the ipv6 address is getting fetched. The address_configure() is getting invoked to assign the address to the eth0. But i am not seeing that assigned to eth0 when ip addr show is executed. I am not able to figure out where this ip address is getting stored in the systemd-networkd.

May 11 18:02:07 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 11 18:11:02 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 11 21:05:38 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 11 21:07:27 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 11 21:09:43 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 11 21:12:14 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 11 21:22:14 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 11 21:30:09 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 11 22:43:25 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 01:24:22 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 12 01:34:34 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 01:58:51 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 02:52:22 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 05:09:54 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 07:42:06 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 07:50:20 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 08:13:39 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 12 08:23:34 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 12:04:25 abc systemd-networkd[7639]: eth0: DHCPv6 address 2001:501:ffff:101::1500/128 timeout preferred 600 valid 600
May 12 12:14:44 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost
May 12 17:23:32 abc systemd-networkd[7639]: eth0: DHCPv6 lease lost

I had configured the server to send the prefix as :
subnet6 2001:501:ffff:101::/64 {
        # Two addresses available to clients
        #  (the third client should get NoAddrsAvail)
        range6 2001:501:ffff:101::1000 2001:501:ffff:101::1500;
        # Some /64 prefixes available for Prefix Delegation (RFC 3633)
        prefix6 2001:501:ffff:101:: 2001:501:ffff:101:: /64;
        default-lease-time 600;
        max-lease-time 600;
        min-lease-time 600;
}

The client has the below config:
[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
DHCP=ipv6
IPv6AcceptRA=yes
IPv6PrivacyExtensions=yes
[DHCP]
ClientIdentifier=duid
IAID=15
CriticalConnection=true
DUIDType=link-layer-time
RapidCommit=false
UseDNS=true
UseHostname=false
SendHostname=false

**Steps to reproduce the problem**
Start the DHCP server-client with the above configuration.

**Comment by yuwata** [comment]
Could you enable to produce debugging logs?

**Comment by sunharis** [comment]
I dont have them saved. I will reproduce this again and put the logs. 
Meanwhile, do you see any possible miss/issue in the configuration ?

**Comment by sunharis** [comment]
eth0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
NDISC: Sent Router Solicitation, next solicitation in 4s
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
DHCPv6 CLIENT: Started in Managed mode
eth0: Acquiring DHCPv6 lease on NDisc request
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1s
lo: Link state is up-to-date
lo: Unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
IPV4ACD: Probing 169.254.36.40
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 2s
IPV4ACD: Probing 169.254.36.40
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 4s
IPV4ACD: Probing 169.254.36.40
IPV4ACD: ANNOUNCE
eth0: IPv4 link-local claim 169.254.36.40
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 8s
IPV4ACD: ANNOUNCE
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 16s
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 32s
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1min 5s
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1min 53s
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
eth0: Acquiring DHCPv6 lease on NDisc request
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1min 53s


root@abc:/etc/systemd/network# /sbin/ip -6 route show dev eth0
2001:501:ffff:101::/64 dev eth0  metric 1024  expires 86227sec <<<=== this is the dhcpv6 subnet which i specified at the server. I see this is added to the route.
fe80::/64 dev eth0  metric 256 
default via fe80::62e2:d540:c8c5:d9c6 dev eth0  metric 1024  expires 1627sec
anycast fe80:: dev eth0  metric 0 
ff00::/8 dev eth0  metric 256 
root@abc:/etc/systemd/network# 

I dont see an ip address getting assigned

**Comment by ssahani** [comment]
```
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
```

Thanks for the logs. it says your RA Daemon asked networkd to talks to DHCP6 and networkd has started the DHCP6 client . But it's not receiving anything .  Now how to debug ?

Please capture the logs in Wireshark and see network has initiated the client request. On the other end you can capture the logs of dhcp6 server and capture the packets to verify whether dhcp6 requests reached to your sever. If possible please attach all the logs.

**Comment by ssahani** [comment]
I am pretty sure this is not a network's bz. This is more like user's setting which not related to us.

**Comment by yuwata** [comment]
Lacks of response. Closing.
