### ISSUE TITLE
busctl call broken (or badly documented)

### ISSUE THREAD

**Issue by jbulow** [systemd/systemd#12551]
**Is your feature request related to a problem? Please describe.**
I'm always frustated when simple examples does not work work with busctl, such as busctl call.

According to documentation it should be possible to call a method using busctl call with the signature parsing is broken or badly documented.

E.g

Setting a property by using the Set method on the org.freedesktop.DBus.Properties interface does not work.

```
$  busctl call com.example.service  /com/example/service org.freedesktop.DBus.Properties Set sss com.example.service.Foo MyStringProperty MyStringValue
```

Incorrect parameters for property 'MyStringProperty', expected 's', got ''.

I'm aware of "busctl set-property" but I want to be able to use the generic call mechanism for other purposes.

**Describe the solution you'd like**
Should work.

**Describe alternatives you've considered**
Create custom tools to replace busctl.

**Comment by poettering** [comment]
The "Set" method expects "ssv", not "sss" as signature, that's why this fails. The error doesn't really make this clear though.

Try this:

```
busctl call com.example.service /com/example/service org.freedesktop.DBus.Properties Set ssv com.example.service.Foo MyStringProperty s MyStringValue
```

**Comment by jbulow** [comment]
The working command line is:

> busctl call com.example.service /com/example/service org.freedesktop.DBus.Properties Set ssv com.example.service.Foo MyStringProperty s MyStringValue

It's not obvious from the man page how to format the call command line.

**Comment by jbulow** [comment]
I just found out before I saw your reply. Thanks anyway!

**Comment by poettering** [comment]
BTW, you can hit "Tab" and it actually autocompletes the parameter list for you, i.e. gets the "ssv" right. It won't fill in the parameter values themselves though of course.

The serialization of variants is briefly described here: https://www.freedesktop.org/software/systemd/man/busctl.html#Parameter%20Formatting

there's even an example there!

but anyway, we should output a clearer error message here.

**Comment by jbulow** [comment]
Another weird error message I encountered during my trial and error session was:

> busctl call com.example.service /com/example/service org.freedesktop.DBus.Properties Set "ss(s)" com.example.service.Foo MyStringProperty MyStringValue
Incorrect parameters for property 'MyStringProperty', expected 's', got 's'.

Quite confusing with "expected 's', got 's'" :-)

**Comment by jbulow** [comment]
I don't have any completion mapped for busctl. Will try to find that. 

I've read all documentation and blog posts I could find. It was when I read the source code for set-property in busctl.c I finally understand the use of per-argument signature.
