### ISSUE TITLE
networkd: wrongly automatically increases MTU for a 4 bytes

### ISSUE THREAD

**Issue by k0ste** [systemd/systemd#12552]
**systemd version the issue has been seen with**
> systemd 242 (242.29-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Linux r1.opentech.local 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > systemd-networkd is set user-defined MTU values.

**Unexpected behaviour you saw**
 > systemd-networkd is set MTU +4 bytes for underlayer interfaces.

**Steps to reproduce the problem**

po1.netdev:
```
[NetDev]
Name=po1
Kind=bond
MTUBytes=1500

[Bond]
Mode=802.3ad
TransmitHashPolicy=layer2+3
LACPTransmitRate=fast
MIIMonitorSec=0.1
```

po1.network:
```
[Match]
Name=po1

[Network]
VLAN=vlan6
```

ten0.link:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f8

[Link]
Name=ten0
```

ten0.network:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f8

[Network]
Bond=po1
```

ten1.link:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f9

[Link]
Name=ten1
```

ten1.network:
```
[Match]
MACAddress=3c:fd:fe:aa:5e:f9

[Network]
Bond=po1
```

vlan6.netdev:
```
[NetDev]
Name=vlan6
Kind=vlan
MTUBytes=1500

[VLAN]
Id=6
```

vlan6.network:
```
[Match]
Name=vlan6

[Address]
Address=100.100.100.2/24
```

**Comment by k0ste** [comment]
This is result:

![2019-05-13_16-03](https://user-images.githubusercontent.com/7759548/57609281-bf82a600-7598-11e9-8ccc-7f6fa29bc0ac.png)

But if MTUBytes is not declared, interfaces gets default MTU 1500byte's (as expected).
Seems this caused by #11807.

I'm not against this, but this may (and do!) break some systems on upgrade:
![2019-05-13_16-10](https://user-images.githubusercontent.com/7759548/57610164-77648300-759a-11e9-9982-738780c0b811.png)

On our luck this router (40km from city) have second NIC on LACP with another chip with support MTU more than 1500.
I think this "+4 byte for vlan automatically" may be switched off by some parameter and enabled by default. @yuwata?

**Comment by yuwata** [comment]
@k0ste Thank you for the report. I hope #12574 fixes the issue.

**Comment by k0ste** [comment]
@yuwata, thanks. #12574 fix this issue.
