### ISSUE TITLE
systemd-user-session

### ISSUE THREAD

**Issue by marcelhollerbach** [systemd/systemd#1255]
It removes /etc/nologin , but on stop /etc/nologin is not created anymore, only /run/nologin.

According to the pam_nologin module, /etc/nologin is checked.

Is there a reason that this is not created ?

**Comment by grawity** [comment]
Hmm, my copy of the manual page says:

<pre>
OPTIONS
       file=/path/nologin
           Use this file instead the <b>default /var/run/nologin or /etc/nologin.</b>
</pre>

So it only needs either one, not both.

**Comment by marcelhollerbach** [comment]
ok agreed, I just wondered when I saw the code, two files where removed, one is just added.

**Comment by poettering** [comment]
We consider `/etc/nologin` legacy. We support it for compat only: we check it, but we will never create it on our own. If either file exists everything is good. hence nothing to fix here.

**Comment by marcelhollerbach** [comment]
OK, thanks for the detailed description :)
