### ISSUE TITLE
Cannot use AF_UNSPEC in RestrictAddressFamilies

### ISSUE THREAD

**Issue by ema** [systemd/systemd#12563]
**systemd version the issue has been seen with**
241

**Used distribution**
 Debian

**Unexpected behaviour you saw**

`/lib/systemd/system/ssh.service:18: Failed to parse address family, ignoring: AF_UNSPEC`

**Steps to reproduce the problem**
Include `AF_UNSPEC` in `RestrictAddressFamilies` and run `systemctl daemon-reload`.

For example:
`RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_UNSPEC`

**Comment by poettering** [comment]
Why would you want to specify that? socket() with AF_UNSPEC will fail anyway, so what's the problem? What do you think socket(AF_UNSPEC) should do if not fail?

**Comment by ema** [comment]
> Why would you want to specify that? socket() with AF_UNSPEC will fail anyway, so what's the problem?

You're right! Calling socket() with AF_UNSPEC and listing an address family as restricted produce the same behavior (make the socket call return -1). It might be useful to explicitly mention in systemd.exec(5) that this is what happens when a restricted AF is used, but other than that there's nothing to see here. Closing.
