### ISSUE TITLE
Logind Ignoring Powerkey Config

### ISSUE THREAD

**Issue by DeathKhan** [systemd/systemd#12582]
**systemd version the issue has been seen with**
> systemd-242.29-1

**Used distribution**
 >Arch Repo

**Expected behaviour you didn't see**
 > logind handling command bound in config

**Unexpected behaviour you saw**
 > logind ignoring configuration settings for power binding

**Steps to reproduce the problem**
change logind.conf powerkey to desired setting, watch as logind ignores setting and powers down anyway

**Comment by poettering** [comment]
this is not actionable.

What does your logind.conf look like precisely? Have you restarted logind after making your change? Anything relevant in the logs?

**Comment by poettering** [comment]
which desktop are you using btw? are you sure it's not the desktop itself that is handling these keys? normally, whenever a desktop runs it takes over key handling and returns it to logind only when exiting.

**Comment by DeathKhan** [comment]
I am using i3, and the key is configed to use a power script I wrote, but is ignoring this setting from the i3 config.
I did not have this issue until I updated systemd. My logind.conf is as follows:
`[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
#HandlePowerKey=power
#HandleLidSwitch=suspend
#HandleLidSwitchExternalPower=suspend
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192`
The script I wrote is power and is included in /bin/sh
It works running from command prompt, and the binding worked fine before the update.

**Comment by poettering** [comment]
the configuration you pasted only contains commented lines and no change made by you?

**Comment by poettering** [comment]
Let's close this, due to lack of response
