### ISSUE TITLE
 "~/.config/user-tmpfiles.d/screen.conf" is being ignored

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#12596]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Arch

**Expected behaviour you didn't see**

I expected that this configuration would prevent files in `/tmp/uscreens` from getting deleted:

    $ cat .config/user-tmpfiles.d/screen.conf
    # FHE 30 Jan 2019
    # does this do anything?
    # https://unix.stackexchange.com/questions/219814/why-is-systemd-tmpfiles-clean-not-working
    d /tmp/uscreens 0755 frederik frederik -

**Unexpected behaviour you saw**

The files get deleted anyway. However, since the deletion happens after many days (weeks?), it is very difficult to debug.

**Steps to reproduce the problem**

Compile your own version of GNU screen, so that sockets go in `/tmp/uscreens`. Start a session. Wait two weeks or so. The socket disappears and is no longer visible in the output of `screen -ls`.

Please let me know if there is a better way to reproduce this. Ideally I could give an argument to `systemd-tmpfiles` which simulates what will happen in two weeks' time, and outputs the various file deletions on STDERR together with which config file caused or prevented which deletion. Or maybe there is a way to disable `systemd-tmpfiles`.

I looked around and found the documentation and debugging facilities lacking. This has been bothering me for several years now.

**Comment by arvidjaar** [comment]
`/tmp/` is normally cleaned up by system instance of systemd and your configuration is for user instance.

**Comment by archenemies** [comment]
Thanks, that's very helpful.

Can we add your information to the documentation (e.g. to "tmpfiles.d(5)")?

Now, `/tmp/` is world-writable on my system (is that OK?) and `/etc/tmpfiles.d/` is only writable by root. How can an unprivileged user which is interested in having files stay in `/tmp` configure this?

How do I disable `systemd-tmpfiles`?

How do I debug the configuration when I run into a problem like this?

**Comment by poettering** [comment]
Yeah, we should probably document that, explicitly.

**Comment by archenemies** [comment]
I think there were three other questions in my last comment. I'm still interested in knowing the answers to them.

**Comment by archenemies** [comment]
Also, I read the patch. The additions look well written and the description of the design seemed understandable to me.

I am a bit surprised that this is the design which has been selected as satisfactory. How can an unprivileged user protect files in `/tmp/`? This is basic to many programs. Have we been given a standard workaround? Is there like a newsletter for Systemd that I should be subscribed to, to know these things? I'm not trying to be sarcastic, I'm just interested in being better informed. Is there an O'Reilly book?

Thank you.

**Comment by refi64** [comment]
- For the unprivileged user preserving their files, you can using [the third or fifth options here](https://systemd.io/TEMPORARY_DIRECTORIES.html#automatic-clean-up).
- You can disable the cleaning functionality via ` 
`systemd-tmpfiles-clean.timer`, but note that by doing so you risk /tmp becoming full and causing programs to crash. Disabling tmpfiles fully altogether is also highly discouraged, as some software depends on tmpfiles creating and linking items as expected. On some systems disabling it could actually prevent the system from booting (like Silverblue).
- You can run systemd-tmpfiles manually to make it easier to trace instead of just waiting for it to clean up. Other than that, just read the docs.

**Comment by archenemies** [comment]
I found the linked document very helpful, thank you.

**Comment by poettering** [comment]
"Protecting" files in /tmp is generally not safe, except if those files are created during early boot, before any unprivileged code runs, since doing so means referencing such files by path, and that means the name is guessable and since /tmp is a shared namespace somebody else might take the name before you and you just created a DoS. Since doing that is not safe we generally don't bother supporting that.

**Comment by archenemies** [comment]
Can you be more specific about what kinds of protection of files in /tmp is not supported, and in what way it is not supported (i.e. does Systemd delete the files anyway or what?)? Thanks.

**Comment by poettering** [comment]
the systemd-tmpfiles system instance will "age" everything in /tmp, except what it is configured not to. It's that simple. If any componet creates files in /tmp they will thus be removed sooner or later (unless you take a bsd lock on the dirs, see linked doc)

**Comment by archenemies** [comment]
You said:

> "Protecting" files in /tmp is generally not safe, except if those files are created during early boot, before any unprivileged code runs, since doing so means referencing such files by path, and that means the name is guessable and since /tmp is a shared namespace somebody else might take the name before you and you just created a DoS. Since doing that is not safe we generally don't bother supporting that.

I still have no idea what this means. What is meant by "'Protecting' files in /tmp is generally not safe", and what is meant by "Since doing that is not safe we generally don't bother supporting that."? What is "that"? What are you not supporting? There are about 5 of the numbered paragraphs in the "Automatic Clean-Up" section of the systemd.io link which I would say describe ways of "protecting files in /tmp". Which one are you saying is not safe, and why?

**Comment by poettering** [comment]
"Protecting" is a quote from you, please see your earlier comment, i put it in quotes to indicate that.  hope you know what you mean by  what you wrote there?

**Comment by archenemies** [comment]
@poettering I'm still not understanding you, sorry.

**Comment by archenemies** [comment]
Maybe you can give an example using shell commands? For example, here is how I understand [option number 5](https://systemd.io/TEMPORARY_DIRECTORIES.html#automatic-clean-up):

    T=$(mktemp); chmod +t $T

Now when you say

> "Protecting" files in /tmp is generally not safe, except if those files are created during early boot, before any unprivileged code runs, since doing so means referencing such files by path, and that means the name is guessable and since /tmp is a shared namespace somebody else might take the name before you and you just created a DoS. Since doing that is not safe we generally don't bother supporting that.

are you talking about the above example or not? If yes, can you explain how it is not safe or not supported? If no, can you give an example (in shell commands) of what you are talking about as being unsafe and unsupported? Where is the DoS?

When you ask if I understand what I wrote myself, it sounds like you think I'm trying to play games. But I'm just trying to figure out how you want your software to be used. I would prefer to keep this interaction as simple as possible by just answering the questions which we are able to answer. Thanks.
