### ISSUE TITLE
Not able to launch Weston via Service file 

### ISSUE THREAD

**Issue by rajashekharsanda** [systemd/systemd#12595]
Hello, 

We are working on Genivi14, in which we are trying to launch weston via service file. It is not working if iam giving Type=notify in service file. 

my build configuration is as follows:

Build Configuration:
BB_VERSION           = "1.36.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "h3ulcb"
DISTRO               = "poky-ivi-systemd"
DISTRO_VERSION       = "14.0.0"
TUNE_FEATURES        = "aarch64 cortexa57-cortexa53"
TARGET_FPU           = ""
SOC_FAMILY           = "rcar-gen3:r8a7795"
meta                 
meta-poky            
meta-yocto-bsp       = "rocko:5f660914cd7eec8117efccdf1eb29c466b4e74f7"
meta-oe              
meta-filesystems     
meta-multimedia      = "rocko:eae996301d9c097bcbeb8046f08041dc82bb62f8"
meta-rcar-gen3       
meta-ivi             
meta-ivi-bsp         
meta-optee           = "<unknown>:<unknown>"
meta-networking      
meta-python          = "rocko:eae996301d9c097bcbeb8046f08041dc82bb62f8"
meta-rtlwifi-master  
meta-aac             = "<unknown>:<unknown>"

*******************************************************************************************

weston service file is as follows:

[Unit]
Description= launch weston
Requires=  dbus-session.service dbus.service systemd-user-sessions.service
After= dbus-session.socket dbus.service  dbus-session.service systemd-user-sessions.service  session-c1.scope
ConditionPathExists=/dev/tty0

[Service]
Type=notify
User=root
Restart=on-failure
ExecStart=/usr/bin/weston  
NotifyAccess=all
PAMName=login
StandardInput=tty-fail
TTYPath=/dev/tty7
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
UtmpIdentifier=tty7
UtmpMode=root
TimeoutStartSec=60
WatchdogSec=20
#ExecStart=/usr/bin/weston

[Install]
WantedBy=basic.target
****************************************************************************************************

weston.ini file is as follows:

[core]
shell=ivi-shell.so
modules=systemd-notify.so

[ivi-shell]
ivi-module=ivi-controller.so
ivi-input-module=ivi-input-controller.so
ivi-shell-user-interface=/usr/lib/weston/weston-ivi-shell-user-interface

#developermode=true

cursor-theme=default
cursor-size=32

base-layer-id=1000
base-layer-id-offset=10000

workspace-background-layer-id=2000
workspace-layer-id=3000
application-layer-id=4000

transition-duration=300

background-image=/usr/share/weston/background.png
background-id=1001
panel-image=/usr/share/weston/panel.png
panel-id=1002
surface-id-offset=10
tiling-image=/usr/share/weston/tiling.png
tiling-id=1003
sidebyside-image=/usr/share/weston/sidebyside.png
sidebyside-id=1004
fullscreen-image=/usr/share/weston/fullscreen.png
fullscreen-id=1005
random-image=/usr/share/weston/random.png
random-id=1006
home-image=/usr/share/weston/home.png
home-id=1007
workspace-background-color=0x99000000
workspace-background-id=2001

[input-method]
path=/usr/libexec/weston-keyboard

[ivi-launcher]
workspace-id=0
icon-id=4001
icon=/usr/share/weston/icon_ivi_flower.png
path=/usr/bin/weston-flower

[ivi-launcher]
workspace-id=0
icon-id=4002
icon=/usr/share/weston/icon_ivi_clickdot.png
path=/usr/bin/weston-clickdot

[ivi-launcher]
workspace-id=1
icon-id=4003
icon=/usr/share/weston/icon_ivi_simple-egl.png
path=/usr/bin/weston-simple-egl

[ivi-launcher]
workspace-id=1
icon-id=4004
icon=/usr/share/weston/icon_ivi_simple-shm.png
path=/usr/bin/weston-simple-shm

[ivi-launcher]
workspace-id=2
icon-id=4005
icon=/usr/share/weston/icon_ivi_smoke.png
path=/usr/bin/weston-smoke

[ivi-launcher]
workspace-id=3
icon-id=4006
icon=/usr/share/weston/icon_ivi_flower.png
path=/usr/bin/weston-flower

[ivi-launcher]
workspace-id=3
icon-id=4007
icon=/usr/share/weston/icon_ivi_clickdot.png
path=/usr/bin/weston-clickdot

[ivi-launcher]
workspace-id=3
icon-id=4008
icon=/usr/share/weston/icon_ivi_simple-egl.png
path=/usr/bin/weston-simple-egl

[ivi-launcher]
workspace-id=3
icon-id=4009
icon=/usr/share/weston/icon_ivi_simple-shm.png
path=/usr/bin/weston-simple-shm

[ivi-launcher]
workspace-id=3
icon-id=4010
icon=/usr/share/weston/icon_ivi_smoke.png
path=/usr/bin/weston-smoke
***************************************************************************************
systemctl status launchWeston.service output is as follows:

â— launchWeston.service - launch weston
   Loaded: loaded (/etc/systemd/system/launchWeston.service; disabled; vendor preset: enabled)
   Active: failed (Result: protocol) since Fri 2019-02-22 04:56:02 UTC; 3min 12s ago
  Process: 3177 ExecStart=/usr/bin/weston (code=killed, signal=TERM)
 Main PID: 3177 (code=killed, signal=TERM)

Feb 22 04:56:01 h3ulcb systemd[1]: launchWeston.service: Unit entered failed state.
Feb 22 04:56:01 h3ulcb systemd[1]: launchWeston.service: Failed with result 'protocol'.
Feb 22 04:56:02 h3ulcb systemd[1]: launchWeston.service: Service hold-off time over, scheduling restart.
Feb 22 04:56:02 h3ulcb systemd[1]: Stopped launch weston.
Feb 22 04:56:02 h3ulcb systemd[1]: launchWeston.service: Start request repeated too quickly.
Feb 22 04:56:02 h3ulcb systemd[1]: Failed to start launch weston.
Feb 22 04:56:02 h3ulcb systemd[1]: launchWeston.service: Unit entered failed state.
Feb 22 04:56:02 h3ulcb systemd[1]: launchWeston.service: Failed with result 'protocol'.

******************************************************************************************************

journalctl -xe logs as follows: 

-- Unit getty@tty1.service has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:55:59 h3ulcb systemd[1]: Starting launch weston...
-- Subject: Unit launchWeston.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit launchWeston.service has begun starting up.
Feb 22 04:56:00 h3ulcb systemd[1]: Started Serial Getty on ttySC0.
-- Subject: Unit serial-getty@ttySC0.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit serial-getty@ttySC0.service has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb PAS[3076]: PAS >> Daemon process PersistenceAdminService starting.
Feb 22 04:56:00 h3ulcb systemd[1]: Reached target Login Prompts.
-- Subject: Unit getty.target has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit getty.target has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb systemd[1]: Reached target Multi-User System.
-- Subject: Unit multi-user.target has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit multi-user.target has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb systemd[1]: Starting Update UTMP about System Runlevel Changes...
-- Subject: Unit systemd-update-utmp-runlevel.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-update-utmp-runlevel.service has begun starting up.
Feb 22 04:56:00 h3ulcb systemd[3108]: pam_unix(login:account): account root has password changed in future
Feb 22 04:56:00 h3ulcb systemd[3108]: pam_unix(login:session): session opened for user root by (uid=0)
Feb 22 04:56:00 h3ulcb systemd[1]: Started Update UTMP about System Runlevel Changes.
-- Subject: Unit systemd-update-utmp-runlevel.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-update-utmp-runlevel.service has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb systemd[1]: Created slice User Slice of root.
-- Subject: Unit user-0.slice has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user-0.slice has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb connmand[3067]: Checking loopback interface settings
Feb 22 04:56:00 h3ulcb connmand[3067]: System hostname is h3ulcb
Feb 22 04:56:00 h3ulcb dbus[3064]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Feb 22 04:56:00 h3ulcb connmand[3067]: lo {newlink} index 1 address 00:00:00:00:00:00 mtu 65536
Feb 22 04:56:00 h3ulcb dbus[3064]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Feb 22 04:56:00 h3ulcb connmand[3067]: lo {newlink} index 1 operstate 0 <UNKNOWN>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {create} index 2 type 1 <ETHER>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {update} flags 4098 <DOWN>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 address 76:52:48:4C:23:63 mtu 1500
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 operstate 2 <DOWN>
Feb 22 04:56:00 h3ulcb systemd[1]: Starting User Manager for UID 0...
-- Subject: Unit user@0.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit user@0.service has begun starting up.
Feb 22 04:56:00 h3ulcb systemd[3121]: pam_unix(systemd-user:account): account root has password changed in future
Feb 22 04:56:00 h3ulcb kernel: audit: type=1006 audit(1550811360.143:2): pid=3121 uid=0 old-auid=4294967295 auid=0 tty=(none) old-ses=4294967295 ses=1 res=1
Feb 22 04:56:00 h3ulcb systemd[3121]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Feb 22 04:56:00 h3ulcb systemd-logind[3068]: New session c1 of user root.
-- Subject: A new session c1 has been created for user root
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID c1 has been created for the user root.
-- 
-- The leading process of the session is 3108.
Feb 22 04:56:00 h3ulcb systemd[1]: Started Session c1 of user root.
-- Subject: Unit session-c1.scope has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-c1.scope has finished starting up.
-- 
-- The start-up result is done.
Feb 22 04:56:00 h3ulcb systemd[1]: Starting Hostname Service...
-- Subject: Unit systemd-hostnamed.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-hostnamed.service has begun starting up.
Feb 22 04:56:00 h3ulcb systemd[1]: Starting WPA supplicant...
-- Subject: Unit wpa_supplicant.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wpa_supplicant.service has begun starting up.
Feb 22 04:56:00 h3ulcb kernel: Micrel KSZ9031 Gigabit PHY e6800000.ethernet-ffffffff:00: attached PHY driver [Micrel KSZ9031 Gigabit PHY] (mii_bus:phy_addr=e6800000.ethernet-ffffffff:00, irq=179)
Feb 22 04:56:00 h3ulcb kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Feb 22 04:56:00 h3ulcb connmand[3067]: Adding interface eth0 [ ethernet ]
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {update} flags 36931 <UP,RUNNING>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 address 76:52:48:4C:23:63 mtu 1500
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 operstate 0 <UNKNOWN>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {update} flags 36867 <UP>
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 address 76:52:48:4C:23:63 mtu 1500
Feb 22 04:56:00 h3ulcb connmand[3067]: eth0 {newlink} index 2 operstate 2 <DOWN>
Feb 22 04:56:00 h3ulcb systemd[1]: Failed to start launch weston.
-- Subject: Unit launchWeston.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit launchWeston.service has failed.
-- 
-- The result is failed.

***********************************************************************************************
please help me to solve this issue.

**Comment by keszybz** [comment]
This is not a support forum, but a bug tracker, and we know very little about weston. This belongs on the weston mailing list or some other place for general questions. Thanks for understanding.
