### ISSUE TITLE
Allow to enforce DNSOverTLS

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#12606]
**Is your feature request related to a problem? Please describe.**
no 

**Describe the solution you'd like**
DNSOverTLS only supports opportunistic and false. It should follow the same syntax as DNSSEC with also allowing to enforce it with DNSOverTLS=true.

Also if one currently specifies DNSOverTLS=true, the feature is counter intuitively not enforced, but disabled.

**Describe alternatives you've considered**
none, except using a different dns resolver.

**Comment by antipatico** [comment]
The feature request is already resolved in [#12815](https://github.com/systemd/systemd/pull/12815).
