### ISSUE TITLE
Do Requires= go into [Unit] and RequiredBy= in [Install]?

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#12600]
Reading https://www.freedesktop.org/software/systemd/man/systemd.unit.html my understanding is, that both Requires= and RequiredBy= are used to create symlinks in .requires/ directory.

And RequiredBy= cannot be used directly as a unit configuration setting.

The manual states “The preferred way to create symlinks in the .wants/ directory of a unit file is with the enable command of the systemctl(1) tool which reads information from the [Install] section of unit files (see below). A similar functionality exists for Requires= type dependencies as well, the directory suffix is .requires/ in this case.”

Table “Forward" and "reverse" unit properties” says after “Requires= | RequiredBy”: “A unit file option; an option in the [Install] section”.

The RequiredBy= option is described in section “[Install] Section Options”.

The Requires= option is described in section “[Unit] Section Options”.

* If this mean, that Requires= goes in the Unit section, but RequiredBy= in the [Install] section, this needs to be articulated explicitly.

* If Requires= can be used only in the [Install] section, then it must appear under “[Install] Section Options”.

**Comment by arvidjaar** [comment]
> my understanding is, that both `Requires=` and `RequiredBy=` are used to create symlinks in .requires/ directory.

`Requires` does not create any symlinks, not is it stated anywhere in manual page you mention. I can see that _A similar functionality exists for `Requires=` type dependencies_ is rather vague; may be the whole paragraph could be rewritten to treat both `Wants` and `Requites` equally to avoid ambiguity.

> If this mean, that `Requires=` goes in the Unit section, but `RequiredBy=` in the [Install] section, this needs to be articulated explicitly.

This is quite explicitly articulated.

https://github.com/systemd/systemd/blob/e7b621ee1f1abfbcaae1cd17da4d815daf218679/man/systemd.unit.xml#L1442

If this is unclear, feel free to suggest better description.

**Comment by dilyanpalauzov** [comment]
I propose changing the last column of the “"Forward" and "reverse" unit properties” table , the lines with Requires and Wants from “A unit file option; an option in the [Install] section” to “Requires goes in the [Unit] section, RequiredBy= is for the [Install] section” to have a place, stressing on this difference.
