### ISSUE TITLE
localectl: add /usr/local/ to keymap search list

### ISSUE THREAD

**Issue by quibo** [systemd/systemd#1260]
**Problem:** cannot put local keymaps in `/usr/local/...`

**Description:**
The list of system directories searched for keymaps is hard-coded in `src/basic/def.h`:

``` c
    51  #ifdef HAVE_SPLIT_USR
    52  #define KBD_KEYMAP_DIRS                         \
    53          "/usr/share/keymaps/\0"                 \
    54          "/usr/share/kbd/keymaps/\0"             \
    55          "/usr/lib/kbd/keymaps/\0"               \
    56          "/lib/kbd/keymaps/\0"
    57  #else
    58  #define KBD_KEYMAP_DIRS                         \
    59          "/usr/share/keymaps/\0"                 \
    60          "/usr/share/kbd/keymaps/\0"             \
    61          "/usr/lib/kbd/keymaps/\0"
    62  #endif
```

Sysadmins may need to add local keymaps, and they put them somewhere below `/usr/local/`; for example in `/usr/local/share/keymaps`.

The simpler workaround (creating a symbolic link in `/usr/share/keymaps/local -> /usr/local/share/keymaps`) does not work, since the `nftw` implementing the keymaps search skips symbolic links and does not cross mount points.

The only choice left is to copy local keymaps in `/usr/lib/...` which is not good :-)

**Comment by poettering** [comment]
Does kbd actually support looking in those dirs? i.e. if you invoke "loadkeys foo" on the cmdline, will it look in /usr/local?

If not, could you get this fixed in kbd first? If yes, I'd be happy to take a patch that adds the paths to the localectl search path.

**Comment by poettering** [comment]
I'll mark this as postponed, as long as it isn#t clear that kbd actually looks in /usr/local too.
