### ISSUE TITLE
DNS parallel request or priority issue

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#12607]
I think this may just be a documentation issue.

Scenario:
NetworkManager provides DNS-Servers on one interface.
Within /etc/systemd/resolved.conf DNS and FallbackDNS are specified
e.g.
DNS=1.1.1.1
FallbackDNS=8.8.8.8
And NetworkManager provides us 192.168.178.1

Now the documentation https://www.freedesktop.org/software/systemd/man/resolved.conf.html within the DNS= section states:
`DNS requests are sent to one of the listed DNS servers in parallel to suitable per-link DNS servers`
When looking at the network traffic using wireshark only the per-link DNS Server (192.168.178.1 in this example) gets queried and no additional query is sent to 1.1.1.1 as the documentation states.

**Comment by poettering** [comment]
what's the full configuration of your host? can you provide the full "resolvectl" output? most likely the domain you looked up belong to a domain configured as routing domain on that iface, which takes precedence then. See the "Protocols and Routing" section on https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html

**Comment by agowa338** [comment]
The interface configuration looks like:

```
Global
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 1.1.1.1
         DNS Servers: 1.1.1.1
Fallback DNS Servers: 8.8.8.8
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 3 (wlp2s0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 192.168.178.1
         DNS Servers: 192.168.178.1
          DNS Domain: ~.
                      rz.fooBarFoo.de
```

**Comment by poettering** [comment]
So, the `~.` line means traffic is preverably routed to your "wlp2s0" interface, thus the global config is not used. Drop that from the domains list of the interface and things should work as you expect
