### ISSUE TITLE
btrfs without an initramfs fails to boot

### ISSUE THREAD

**Issue by prototype99** [systemd/systemd#12615]
**systemd version the issue has been seen with**
> 241-242

**Used distribution**
 > gentoo 17.0

**Expected behaviour you didn't see**
 > system successfully boots into desktop environment on any kernel version (within reason) despite having no initramfs, as it does with kernel 4.16.0

**Unexpected behaviour you saw**
 > system becomes stuck, sometimes silently, sometimes printing the output on screen, sometimes hiding it behind a grey screen and spinner. prior to being closed so that it may be migrated to github if still relevant, [in the freedesktop bug](https://bugs.freedesktop.org/show_bug.cgi?id=84689) it was shown that there does appear to be an automatic fix in the kernel, however it happens after systemd gives up. the same bug also mentions the problem is that btrfs initially mounts the volume as /dev/root, rather than /dev/sd*. the seemingly related text is
`systemd-gpt-auto-generator[313]: Failed to determine block device of root file system: No such file or directory
systemd[302]: /lib64/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.`
on this particular system boot seems to exclusively work with [4.16.0](https://github.com/systemd/systemd/files/3195338/kernel-4.16.0.log), below is a list of the tested not working kernels, with the log output as well.
kernels that do not work include but most likely are not limited to: 
[4.9.76,](https://github.com/systemd/systemd/files/3195311/kernel-4.9.76.log) [4.16.9,](https://github.com/systemd/systemd/files/3195312/kernel-4.16.9.log) [4.16.11,](https://github.com/systemd/systemd/files/3195314/kernel-4.16.11.log) [4.16.12,](https://github.com/systemd/systemd/files/3195321/kernel-4.16.12.log) [4.18.3,](https://github.com/systemd/systemd/files/3195328/kernel-4.18.3.log) [4.19.23,](https://github.com/systemd/systemd/files/3195298/kernel-4.19.23.log) [4.19.27,](https://github.com/systemd/systemd/files/3195302/kernel-4.19.27.log) [4.19.37,](https://github.com/systemd/systemd/files/3195306/kernel-4.19.37.log) [4.20.0,](https://github.com/systemd/systemd/files/3195332/kernel-4.20.0.log) 
[5.1.3](https://github.com/systemd/systemd/files/3198537/kernel-5.1.3.log)(![kernel-error](https://user-images.githubusercontent.com/11457027/58032311-4516d080-7b1a-11e9-8bde-c7f9f1928e15.jpg))

**Steps to reproduce the problem**
according to the [bug at kernel.org](https://bugzilla.kernel.org/show_bug.cgi?id=89721) you must have btrfs with no initramfs. fstab used is [fstab.txt](https://github.com/systemd/systemd/files/3197790/fstab.txt) (extension added just to make it github friendly). raid is not present on the system. systemd version used is 242, kernel version used is 5.1.3. system is UEFI.

**Comment by poettering** [comment]
There's an IO error on your storage:

```
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#1 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#1 Sense Key : Illegal Request [current] 
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#1 Add. Sense: Read of scrambled sector without authentication
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#1 CDB: Read(10) 28 00 00 00 02 00 00 00 02 00
May 19 06:35:04 gay.memes kernel: print_req_error: I/O error, dev sr0, sector 2048 flags 80700
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#2 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#2 Sense Key : Illegal Request [current] 
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#2 Add. Sense: Read of scrambled sector without authentication
May 19 06:35:04 gay.memes kernel: sr 4:0:0:0: [sr0] tag#2 CDB: Read(10) 28 00 00 00 02 00 00 00 02 00
May 19 06:35:04 gay.memes kernel: print_req_error: I/O error, dev sr0, sector 2048 flags 0
May 19 06:35:04 gay.memes kernel: Buffer I/O error on dev sr0, logical block 256, async page read
May 19 06:35:05 gay.memes kernel: BTRFS info (device sdc4): turning on discard
May 19 06:35:05 gay.memes kernel: BTRFS info (device sdc4): disk space caching is enabled
```

It appears you have hw encryption on on the device, given the error "Read of scrambled sector without authentication"

Either way, this is an error between you, your harddisk, your firmware and your kernel. Not a systemd issue though, we are not involved in catching IO errors ro configuring hw disk passwords.

Closing hence.

**Comment by prototype99** [comment]
that... was a dvd in my optical drive. 5.1.3 log has been updated with an empty optical drive boot, i do not use encryption

**Comment by poettering** [comment]
OK, please provide debug logs (i.e. `systemd.log_level=debug` on the kernel cmdline) on a current kernel with current systemd, when this hangs. What is your /etc/fstab? Also, if you boot with `systemd.debug_shell` on the kernel comdline you'll get a debug shell on tty9. Please use that, and have a look at "systemctl list-jobs" when the boot-up hangs. Does the btrfs fs involve raid or so? anything fancy?

**Comment by prototype99** [comment]
original post now includes fstab. i do not use raid or lvm, i like to keep it simple so i just have a single boot/data ssd, partitions are the bootloader partition, the efi partition, the swap partition and the / partition. other internal hard drives are attached, but i don't always need them, so i just mount them as and when needed. i don't think of my fs setup as being particularly fancy, but obviously that is a matter of opinion. may be worth mentioning that the ssd is a samsung 850 evo, it has some drm code that makes the kernel disable queued trim, it probably isn't relevant though. i will now do as you said and see what i get, i will use systemd 242 (243 isn't available in official repositories but if you would like me to test with that version i can probably add it to my personal one relatively painlessly) and kernel 5.1.3 (same story as systemd when it comes to newer versions)

**Comment by prototype99** [comment]
log has been updated, there is definitely more detail. i am unable to get to tty 9 or any other tty (shouldn't it be a simple matter of control+alt+f9?) so i was unable to satisfy that request. there does appear to be some output that never made it to the journalctl file, would you like to see the photograph i took?

**Comment by poettering** [comment]
which log has been updated? the 5.1 log appears to be the same?

yes, photo works too

**Comment by prototype99** [comment]
oh. it appears it never saved when i told it to... that has been fixed now, as well as the added image

**Comment by poettering** [comment]
the screenshot shows a kernel segfault in the hrtime code... Please report to the kernel people, userspace can't fix segfaults in kernel code.

Consider updating to a new kernel...

**Comment by prototype99** [comment]
unable to update kernel because of this bug... but i will be sure to do that

**Comment by Gatak** [comment]
I see the same issue on a Gentoo VM with no initram and a Btrfs root.

```
[    4.789437] Run /usr/lib/systemd/systemd as init process
[    5.880435] systemd[1]: systemd 241 running in system mode. (+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
[    5.890433] systemd[1]: Detected virtualization oracle.
[    5.895392] systemd[1]: Detected architecture x86-64.
[    5.959764] systemd[1]: Set hostname to <vbox>.
[    6.152752] systemd-gpt-auto-generator[539]: Failed to determine block device of root file system: No such file or directory
[    6.551898] random: systemd-crontab: uninitialized urandom read (24 bytes read)
[    6.711447] systemd[527]: /lib64/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
[    7.531845] systemd[1]: /lib/systemd/system/rpc-statd.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/rpc.statd.pid → /run/rpc.statd.pid; please update the unit file accordingly.
[    7.584393] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    7.599477] systemd[1]: Listening on Process Core Dump Socket.
[    7.606550] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    7.613755] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    7.673918] BTRFS info (device nvme0n1p3): enabling auto defrag
[    7.675809] BTRFS info (device nvme0n1p3): using free space tree
```

Kernel command line:
```
[    0.000000] Linux version 5.1.5-gentoo (root@vbox) (gcc version 9.1.0 (Gentoo 9.1.0 p1.0)) #1 SMP Thu May 30 13:27:56 CEST 2019
[    0.000000] Command line: BOOT_IMAGE=/volume/boot/vmlinuz-5.1.5-gentoo root=/dev/nvme0n1p3 ro rootflags=space_cache=v2,nossd,barrier,compress-force=zstd,subvol=volume/root init=/usr/lib/systemd/systemd elevator=bfq
```

**Comment by smopucilowski** [comment]
Ditto on a gentoo baremetal with no initram and a btrfs root:

```
[    1.463702] systemd[1]: systemd 243 running in system mode. (+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT +GNUTLS -ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
[    1.474893] systemd[1]: Detected architecture x86-64.
[    1.475704] systemd[1]: Set hostname to <snip>.
[    1.483200] systemd-gpt-auto-generator[149]: Failed to determine block device of root file system: No such file or directory
[    1.484114] systemd[143]: /lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
[    1.543005] systemd[1]: /lib/systemd/system/smbd.service:7: PIDFile= references a path below legacy directory /var/run/, updating /var/run/samba/smbd.pid → /run/samba/smbd.pid; please update the unit file accordingly.
[    1.543079] systemd[1]: /lib/systemd/system/winbindd.service:7: PIDFile= references a path below legacy directory /var/run/, updating /var/run/samba/winbindd.pid → /run/samba/winbindd.pid; please update the unit file accordingly.
[    1.543142] systemd[1]: /lib/systemd/system/nmbd.service:7: PIDFile= references a path below legacy directory /var/run/, updating /var/run/samba/nmbd.pid → /run/samba/nmbd.pid; please update the unit file accordingly.
[    1.543987] systemd[1]: unit_file_find_fragment: getty@tty1.service has alias autovt@tty1.service
[    1.584726] BTRFS info (device sda2): use lzo compression, level 0
[    1.584728] BTRFS info (device sda2): disk space caching is enabled
```

With:

```
[    0.000000] microcode: microcode updated early to revision 0x27, date = 2019-02-26
[    0.000000] Linux version 4.19.66-gentoo (root@wanderweg.smoddom.local) (gcc version 8.3.0 (Gentoo 8.3.0-r1 p1.1)) #1 SMP Wed Aug 14 01:43:45 AEST 2019
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-4.19.66-gentoo root=/dev/sda2 ro init=/usr/lib/systemd/systemd quiet
```

**Comment by Karlson2k** [comment]
Still valid for kernel 5.7.7 and systemd 244
Gentoo on BTRFS without initramfs.

```
systemd 244 (244)
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

It's not crashed, but reports errors:
```
[    2.236089] systemd-gpt-auto-generator[302]: Failed to determine block device of root file system: No such file or directory
[    2.237822] systemd[296]: /lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
....
[    2.760648] BTRFS info (device nvme0n1p2): device fsid 43c74ec4-9cb8-4bdf-96a3-9024b881b015 devid 1 moved old:/dev/root new:/dev/nvme0n1p2
```

Linked bug: https://bugzilla.kernel.org/show_bug.cgi?id=89721

I don't think that it is a kernel bug. Kernel provides all required information, but later than systemd expects.
I believer systemd should be immune for such situations.
