### ISSUE TITLE
Report resource usage after process has finished

### ISSUE THREAD

**Issue by matthijs** [systemd/systemd#12634]
**Is your feature request related to a problem? Please describe.**
I already asked this question on stackexchange (https://unix.stackexchange.com/questions/519915/report-memory-usage-systemd). I would like a way to get a resource report when a process has finished. The main motivation for this is that we have running cronjobs which sometimes take a large amount of memory / cpu resources. We would like to identify those processes. With systemctl we can query the current process usage but after the process has finished there is no way to get this information. (I have searched for this but could not find it).

**Describe the solution you'd like**
I would lilke to have a command that reports the resource usage of finished processes / cronjobs.

Regards, Matthijs

**Comment by poettering** [comment]
On current systemd versions all services that have MemoryAccounting=1 or CPUAccounting=1 will get a log record written that contains that info. It has message ID ae8f7b866b0347b9af31fe1c80b127c0 assigned, hence you can easily search for it like this:

journalctl MESSAGE_ID=ae8f7b866b0347b9af31fe1c80b127c0

You can combine that with an INVOCATION_ID= search to look for the resource data of a specific invocation.

Anyway, closing, as this is already available in current versions.
