### ISSUE TITLE
60-sensor.hwdb TP500LA

### ISSUE THREAD

**Issue by ivoihlemann** [systemd/systemd#12654]
On my Asus TP500LA (seems to be a rare version of the TP500L) i needed to change the DMI:

_sensor:modalias:acpi:SMO8500*:dmi:*svn*ASUSTeK*:*pn*TP500LB*
ACCEL_MOUNT_MATRIX=0, 1, 0; 1, 0, 0; 0, 0, 1_

to

_sensor:modalias:acpi:SMO8500*:dmi:*svn*ASUSTeK*:*pn*TP500L**A**B*
ACCEL_MOUNT_MATRIX=0, 1, 0; 1, 0, 0; 0, 0, 1_

to get the accelerometer working correct.

**Comment by poettering** [comment]
Please submit a PR that adds the line as an extra line, or adjusts the line otherwise to match both cases.

**Comment by Edelschwarz** [comment]
Sorry for the delay, I was busy the last days and wanted to confirm, that this was the correct change I made. I'm not sure how to create a pull-request to upload my changes.

**Comment by poettering** [comment]
I converted this into a PR now: #14628
