### ISSUE TITLE
systemd-cryptsetup: Missing dependencies for header= if it points to a block device

### ISSUE THREAD

**Issue by nadiamoe** [systemd/systemd#12650]
**systemd version the issue has been seen with**
> 242.29 and earlier

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Sometimes it is useful to have a detached header on another block device, and to reference this device using `/dev/disk/by-partlabel/`. If this is the case, systemd-cryptsetup does not generate a dependency for the mentioned block device, which leads to a race condition and /sometimes/ an unsatisfied dependency, causing the decryption process to fail.

**Unexpected behaviour you saw**
 > No dependency is generated for the `header=` parameter, which causes the mentioned race condition.

**Steps to reproduce the problem**
Put a line in /etc/crypttab whith a `header=` option pointing to a different disk or partition using the `/dev/disk/by-partlabel/` path.

```tsv
fancy    PARTLABEL=fancy    /etc/fancy.key    header=/dev/disk/by-partlabel/fancyheader
```

Since parsing the path of the `header` option is maybe not a good approach, I think that allowing a syntax like `header=PARTLABEL=fancyheader` could be a feasible option.

**Comment by roobre** [comment]
I confirm this can also happen when `header` points to block devices through other paths, like `/dev/disk/by-uuid/`, and not only with partlabel.
