### ISSUE TITLE
network: networkctl status: add more link information

### ISSUE THREAD

**Issue by k0ste** [systemd/systemd#12657]
Currently when we execute `networkctl status <link>` output lack of mtu, speed, duplex, media, link_uptime, packets/bytes/errors counters.

![111](https://user-images.githubusercontent.com/7759548/58309233-e27d4780-7e2d-11e9-9909-c9c3c849b3c9.png)

For link speed, duplex, media we need to use `ethtool <link>`

![222](https://user-images.githubusercontent.com/7759548/58309276-fe80e900-7e2d-11e9-9252-6fa580d7b887.png)

For statistic counters we can use `ethtool -S <link>` or `ip -s link show dev <link>`

![333](https://user-images.githubusercontent.com/7759548/58309900-96330700-7e2f-11e9-8ae2-869116ce4d2c.png)

It's will be good if we can see this brief information in `networkctl status` like on physical switch output, for example:

![444](https://user-images.githubusercontent.com/7759548/58310189-3852ef00-7e30-11e9-8e36-2bac7ac069ff.png)

**Comment by yuwata** [comment]
Quite recently, MTU was added :-)

**Comment by yuwata** [comment]
In #12646 I've implemented statistics counters.

**Comment by yuwata** [comment]
@k0ste Please test #12806.

**Comment by k0ste** [comment]
@yuwata, patch stuck at moment were some files are moved. May be you know some option to avoid this?

```
patching file rules/50-udev-default.rules.in
patching file sysusers.d/basic.conf.in
patching file src/shared/ethtool-util.c (renamed from src/udev/net/ethtool-util.c)
patching file src/shared/ethtool-util.h (renamed from src/udev/net/ethtool-util.h)
Hunk #1 succeeded at 7 with fuzz 2 (offset 1 line).
Hunk #2 succeeded at 86 (offset 1 line).
patching file src/shared/meson.build
patching file src/udev/meson.build
Hunk #1 succeeded at 39 (offset -1 lines).
patching file src/udev/net/link-config-gperf.gperf
patching file src/udev/net/link-config.c
patching file src/udev/net/link-config.h
can't find file to patch at input line 442
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|
|From 3256854405ca267e37c674ae91477c2e49e9290c Mon Sep 17 00:00:00 2001
|From: Yu Watanabe <watanabe.yu+github@gmail.com>
|Date: Mon, 17 Jun 2019 14:57:54 +0900
|Subject: [PATCH 2/6] ethtool-util: use structured initializers
|
|---
| src/shared/ethtool-util.c | 35 +++++++++++++++++++----------------
| 1 file changed, 19 insertions(+), 16 deletions(-)
|
|diff --git a/src/shared/ethtool-util.c b/src/shared/ethtool-util.c
|index 0b0fb47212f..c0617b27710 100644
|--- a/src/shared/ethtool-util.c
|+++ b/src/shared/ethtool-util.c
--------------------------
File to patch: ^C
```

**Comment by yuwata** [comment]
@k0ste 
```
git clone git@github.com:systemd/systemd.git
cd systemd
git remote add yuwat git@github.com:yuwata/systemd.git
git fetch yuwata networkctl-ethtool-12657
git checkout networkctl-ethtool-12657
```
Then you can build the PR.

**Comment by k0ste** [comment]
@yuwata sorry, to busy at this week. Usually I make Arch package - this make test faster on various hardware.

**Comment by yuwata** [comment]
No problem. The PR was already merged. So, it is easier to test I guess.

If you find any error or further request, then please file as a new issue. Thank you!
