### ISSUE TITLE
System idle time detection- before IdleAction

### ISSUE THREAD

**Issue by BryanQuigley** [systemd/systemd#12668]
**Is your feature request related to a problem? Please describe.**
[BOINC](https://boinc.berkeley.edu/download.php) distributed computing project's goal is to  donate idle computer time to help solve scientific/math problems.

BOINC can suspend work based on configurable CPU use, or "in use" detection by last mouse/keyboard touch.  It also has another option to suspend work and let the system actually suspend after X minutes. It can suspend all work when "in use" or just the more intensive GPU tasks.

Currently in-use detection is primarily down via querying every Xservers ScreenSaver extensions (also does tty detection).  This has caused various bugs, and will fail on Wayland.

**Describe the solution you'd like**
In an ideal world... 
  * we tell systemd to let us know when the all users on the system have been Idle for X minutes.
  * once triggered: we do compute work, and ask systemd to let us know when any user gets back
  * once a user gets back: systemd informs us and we stop work as configured - either stopping all work, or just GPU tasks.

From what I can tell IdeAction doesn't work, because it's only one action - and we don't want to change the users lock/suspend preferences.

**Describe alternatives you've considered**
GNOME specific solution - https://unix.stackexchange.com/questions/396911/how-can-i-tell-if-a-user-is-idle-in-wayland.  But I'd prefer something that is more DE agnostic or for servers.

**Comment by Germano0** [comment]
[int KIdleTime::addIdleTimeout | ( | int | msec | )](https://api.kde.org/frameworks/kidletime/html/classKIdleTime.html#a1d97581e86bd6dc763e71f7156116f16) seems to be the best example of what you just said

**Comment by poettering** [comment]
why precisely do you want to detect idle time? it appears to me you just want to schedule your stuff at a very low priority (i.e. SCHED_IDLE or so). but why start/stop it all the time?

systemd/logind cannot really detect when the system is idle, only the desktop environment really knows that and it informs logind about that via the SetIdleHint() bus call. This is currently used to implement automatic suspend on idle. Not all DEs implement that, it's up to them to do so. 

Some DEs might have their own APIs for that layered on top and they just propagate this info to logind from time to time (i think that's what gnome does).

logind sends out bus notifications when the idle hint changes already, you can subscribe to that and act on it. But of course, this alls falls flat if your DE doesn't want to talk to logind. There's nothing we can do about that really...

Hence, I think all you need that we can do something about from our side already exists. Please work with the DEs you care about, to make sure they all implement that. Closing hence.

**Comment by BryanQuigley** [comment]
>why precisely do you want to detect idle time? it appears to me you just want to schedule your stuff at a very low priority (i.e. SCHED_IDLE or so). but why start/stop it all the time?

* That matches what BOINC does on other platforms, the general goal is to let users choose "Definitely no impacts - only run when not in use".
* Even setting some tasks as idle they still can affect performance of the system
* a lot of projects also use GPUs, which to my knowledge don't have a SCHED_IDLE equivalent.

BOINC allows a user to define a different Idle then the system,  that way BOINC can run for X minutes before system wide idle causes a suspend for instance.
