### ISSUE TITLE
Faile to generate some man page

### ISSUE THREAD

**Issue by axionl** [systemd/systemd#12680]
**systemd version the issue has been seen with**

> systemd 242 (242.626-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
> Arch Linux (With `testing`  and `gcc9` repos)

**Expected behaviour you didn't see**

The man page should be correctly installed in the directory.

```/usr/share/man/man8/{halt,poweroff,reboot,runlevel,shutdown,telinit}.8```

**Unexpected behaviour you saw**

No such man page files there.
https://gist.github.com/axionl/9284893ce16672ccc17d0d3b9b4ec762#file-systemd-git-log-L3376

**Steps to reproduce the problem**

https://github.com/archlinuxcn/repo/blob/bed5941d6c6ed4ba5d85e051db8015453b0d40c7/archlinuxcn/systemd-git/PKGBUILD#L113

Please help me to correctly generate these manual pages and thank you very much.

**Comment by keszybz** [comment]
The build script needs to pass `-Dman=true` and/or `-Dhtml=true` as desired.
