### ISSUE TITLE
udev-test seems to fail (in lxc containers on Semaphore and docker containers on Travis CI)

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#12698]
I'm not sure what that was and how often it happens but in https://semaphoreci.com/systemd/systemd/branches/pull-request-12697/builds/1 `test-udev` failed with
```sh

TEST 95: symlink %c substitution
device '/devices/pci0000:00/0000:00:1d.7/usb5/5-2/5-2:1.0/tty/ttyACM0' expecting node/link 'test'
add:         error
test/tmpfs/dev
├── block
├── char
│   └── 166:0 -> ../ttyACM0
├── null
└── ttyACM0

2 directories, 3 files

remove:      ok
```
@mbiebl I'm wondering if you've seen anything like that before.

**Comment by yuwata** [comment]
If I remember correctly, %c substitution has a bug. I hope #12700 helps this.

**Comment by yuwata** [comment]
Is this fixed?

**Comment by evverx** [comment]
It's hard to tell. On June 5 (which was after #12700 was merged) [it failed with](https://semaphoreci.com/systemd/systemd/branches/master/builds/6799) 
```
TEST 36: substitute the second to last argument
device '/devices/pci0000:00/0000:00:1f.2/host0/target0:0:0/0:0:0:0/block/sda/sda5' expecting node/link 'my-foo8'
add:         error
test/tmpfs/dev
├── block
│   └── 8:5 -> ../sda5
├── char
├── my- -> sda5
├── null
└── sda5

2 directories, 4 files
```

**Comment by evverx** [comment]
Judging by https://travis-ci.org/systemd/systemd/jobs/554331370 the test has just failed on Travis CI. I'll change the description a bit.

**Comment by mrc0mmand** [comment]
Looks like the issue resolved itself or migrating to Semaphore v2/GH Actions helped, closing.
