### ISSUE TITLE
theoretical security issue: sd_bus_creds_get_exe should not allow deleted files

### ISSUE THREAD

**Issue by shawnl** [systemd/systemd#12704]
deleted programs would be fine if the Linux API to this was non-ambiguous, and failing that, if it could be disambiguated in a race-free manner. If an attack executable picks an attack filename that ends with " (deleted)" then it can impersonate a process without that suffix.

**Comment by poettering** [comment]
Well, the `exe` thing is purely informational anyway, it's not usable for security purposes, as by the time you read it and want to use it it might already have changed underneath you.

It appears to me that we might want to document this, but otherwise leave it as it is...

**Comment by poettering** [comment]
Fix waiting in #12868
