### ISSUE TITLE
man: CONFIG_SCHEDSTATS is specified in systemd-bootchart man page

### ISSUE THREAD

**Issue by again4you** [systemd/systemd#1272]
If Linux Kernel is built without CONFIG_SCHEDSTATS configuration, systemd-bootchart is fail to execute with the below _simple_ error.

```
sh-4.3# /usr/lib/systemd/systemd-bootchart 
Failed to open /proc/schedstat: No such file or directory
```

IMO, a lot of newbies in this field are having a hard time to find out the right reason. What about specifying the CONFIG_SCHEDSTATS option in systemd-bootchart man page?

**Comment by sztanpet** [comment]
it is clearly indicated in the README

**Comment by again4you** [comment]
@sztanpet Thanks for quick reply.
