### ISSUE TITLE
[udev] Device naming Python script silently terminated when using subprocess or ArgumentParser

### ISSUE THREAD

**Issue by IAXES** [systemd/systemd#12742]
---

**systemd version the issue has been seen with**
> systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

---

**Used distribution**
 > Ubuntu Server 18.04.2 LTS x86/64

---

**Expected behaviour you didn't see**
 > USB ethernet device wasn't named `eth-spam-42` according to rules in test Python script.

---

**Unexpected behaviour you saw**
 > Python script silently terminated (no exceptions raised) if the script calls argparser.ArgumentParser.parse_args(), or if a sub-process is spawned by the naming script. Interface uses the default name that would be assigned in the absence of my naming script.

---

**Steps to reproduce the problem**

- Configure a rule (i.e. `/etc/udev/rules.d/80-net-setup-link.rules` to pass off naming a USB NIC to a Python script):
```
ACTION=="add", SUBSYSTEM=="net", SUBSYSTEMS=="usb", ATTR{address}=="?[014589cd]:*", PROGRAM="/usr/bin/renamer.py --kernel %k", NAME="%c"
```
- Attempt a simple "static" naming rule, works as expected:
```
print("{}".format("eth-spam-42"))
```

Try again, but attempt to run code in a sub-process function, or invoke the argument parser, and the script silently dies, when it runs just fine via the CLI when launched via bash/python.
```
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("-k", "--kernel", dest="kernel", default="", type=str)
# Following one-liner crashes.
args = parser.parse_args()
kernel = args.kernel
print("{}-custom".format(kernel))
```

I've also tried the `OptionParser` tool, and a few other sub-process-centric examples. In all cases, the Python script appears to be terminated silently.

---

If this is a valid use case, can we add a logging call so that udev is informing the user that the script/app for renaming interfaces is being deliberately terminated?

**Comment by yuwata** [comment]
Hmm... v237 is too old here. Could you test with v242 or current git master?

**Comment by poettering** [comment]
have you used udevadm test on this?

**Comment by poettering** [comment]
Let's close this due to lack of response
