### ISSUE TITLE
sd-boot displays a blue screen with no text

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#12747]
**systemd version the issue has been seen with**
> current git master

**Used distribution**
 > Exherbo

**Expected behaviour you didn't see**
 > Boot menu displayed

**Unexpected behaviour you saw**
 > Blue screen with white caret

**Steps to reproduce the problem**
I don't really know when was the last time I ran "bootctl update" (might have been late 2018 given https://github.com/systemd/systemd/issues/10869), it used to work just fine back then, but when I ran it today, I ended up with sd-boot only displaying a blue screen with no entry, and getting stuck in this state.
I'm not sure how to debug this, nor which information could be useful. It might be related to the fact that I switched to lld (8) as the system linker a couple of months ago? (fwupdmgr works though, so efi executables creation seems ok).

**Comment by keszybz** [comment]
I doubt this is going to get fixed, unless you debug it yourself. Trying without lld would be one thing to test.

**Comment by Keruspe** [comment]
So, rebuilding it with gold makes it work

**Comment by poettering** [comment]
hmm, any chance you can bisect that?

Is this reproducible? i.e. does gnu ld linked sd-boot consistently fail for you?

**Comment by Keruspe** [comment]
Heh, it fails only with when linked with lld.
I don't really know how to debug this, but it's probably an lld bug and not a systemd one though, I guess

**Comment by poettering** [comment]
has it every worked with lld? if you downgrade lld, does it work then?

**Comment by Keruspe** [comment]
I didn't try with lld before hitting this and only thought this might have been the cause when actually writing this issue.

**Comment by poettering** [comment]
Hmm, so what do we do with this issue now? Any chance you can further track this down, i.e. bisect, verify it's really lld that causes this, and so on? Otherwise I fear there's nothing actionable about this issue, and we probably should close it?

**Comment by Keruspe** [comment]
I don't really know what to use as a basis for bisecting.
I confirmed the issue is lld related (rebuilding without lld fixes the problem).
Either you have the slightest idea of what's going on or how I could dig further, or we probably can close this.

**Comment by keszybz** [comment]
OK, let's close this. I don't think we have any idea.
