### ISSUE TITLE
Modifying systemd DHCP client to work standalone?

### ISSUE THREAD

**Issue by juga0** [systemd/systemd#12746]
**Is your feature request related to a problem? Please describe.**
systemd implements a DHCP client that supports the Anonymity Profiles (RFC 7844, #6436).
It would be great to have a DHCP client implementation that can be used in many different devices, including microcontrollers.
How feasible would be to base a DHCP client on the systemd implementation to work even when systemd is not available?

**Describe the solution you'd like**
I'm not sure actually what would be the best way to achieve this.

An option in systemd to compile only the DHCP client without systemd support doesn't sound like the goal of systemd and it doesn't make sense to require all the source code.

Copying just the systemd DHCP client files to a different repository and making the needed changes to work standalone has the inconvenient of having to maintain a copy to update from systemd changes when applicable.

**Describe alternatives you've considered**
Patch the ISC DHCP [0] client, or some other C implementation, to support the Anonymity Profiles. It seems to me however that systemd implementation is better designed and maintained.

[0] https://www.isc.org/dhcp/

**Comment by zdzichu** [comment]
You can take example from NetworkManager. Since NM-1.0.0, it is using systemd's DHCP code as internal client.

**Comment by juga0** [comment]
Thanks @zdzichu for the answer.
I actually saw there was a systemd directory in NetworkManager code 2 years ago, but i didn't realize the reason was that one.
I guess that then the question on how to maintain duplicate code or how to don't duplicate can be answered by them.

**Comment by juga0** [comment]
I asked in NetworkManager [0] and the question has been answered there too, so i guess this issue can be closed.
[0] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/192
