### ISSUE TITLE
Bond interface not considered online/routable if degraded

### ISSUE THREAD

**Issue by AlD** [systemd/systemd#12752]
**systemd version the issue has been seen with**
242

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
This system has a wifi and an ethernet interface bonded. The ethernet cable is unplugged, but wifi is connected and working correctly (I'm ssh-ing in e.g.):
```
# networkctl
IDX LINK             TYPE               OPERATIONAL      SETUP
  1 lo               loopback           carrier          unmanaged
  2 eth0             ether              no-carrier       configuring
  3 bond0            bond               degraded-carrier configured
  4 wlan0            wlan               enslaved         configured
```

Everything should be working fine, including e.g. `timesyncd`.

**Unexpected behaviour you saw**
The system time is far off, although timesyncd is running.

```
# timedatectl
               Local time: Do 2019-06-06 00:43:03 CEST
           Universal time: Mi 2019-06-05 22:43:03 UTC
                 RTC time: n/a
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: no
              NTP service: active
          RTC in local TZ: no

# timedatectl timesync-status
       Server: (null) ((null))
Poll interval: 0 (min: 32s; max 34min 8s)
 Packet count: 0
```

The reason is that `timesyncd` checks `network_is_online()`, which fails, because it only considers `routable` and `degraded` as valid states:
https://github.com/systemd/systemd/blob/c0d11245d2bdcf2a4333c3d49c973d83dfbe3791/src/timesync/timesyncd.c#L158
https://github.com/systemd/systemd/blob/c0d11245d2bdcf2a4333c3d49c973d83dfbe3791/src/libsystemd/sd-network/network-util.c#L17-L18

Here, the oper state is `enslaved`, though:

```
# cat /run/systemd/netif/state
# This is private data. Do not parse.
OPER_STATE=enslaved
DNS=192.168.20.1
```

**Steps to reproduce the problem**

1) Set up a bond interface with one interface down and the other one working correctly.
2) Start `systemd-timesyncd`.
3) Run `timedatectl`, `timedatectl show-timesync` and notice that NTP synchronization isn't working.

```
# grep -r ^ /etc/systemd/network/
/etc/systemd/network/30-bond0-eth0.network:[Match]
/etc/systemd/network/30-bond0-eth0.network:Name=eth0
/etc/systemd/network/30-bond0-eth0.network:
/etc/systemd/network/30-bond0-eth0.network:[Network]
/etc/systemd/network/30-bond0-eth0.network:Bond=bond0
/etc/systemd/network/30-bond0-eth0.network:PrimarySlave=yes
/etc/systemd/network/30-bond0-wlan0.network:[Match]
/etc/systemd/network/30-bond0-wlan0.network:Name=wlan0
/etc/systemd/network/30-bond0-wlan0.network:
/etc/systemd/network/30-bond0-wlan0.network:[Network]
/etc/systemd/network/30-bond0-wlan0.network:Bond=bond0
/etc/systemd/network/30-bond0.netdev:[NetDev]
/etc/systemd/network/30-bond0.netdev:Name=bond0
/etc/systemd/network/30-bond0.netdev:Kind=bond
/etc/systemd/network/30-bond0.netdev:
/etc/systemd/network/30-bond0.netdev:[Bond]
/etc/systemd/network/30-bond0.netdev:Mode=active-backup
/etc/systemd/network/30-bond0.netdev:MIIMonitorSec=1s
/etc/systemd/network/30-bond0.network:[Match]
/etc/systemd/network/30-bond0.network:Name=bond0
/etc/systemd/network/30-bond0.network:
/etc/systemd/network/30-bond0.network:[Network]
/etc/systemd/network/30-bond0.network:DHCP=both
```

**Comment by yuwata** [comment]
@AlD If possible, could you test #12762?

**Comment by keszybz** [comment]
I'm probably missing something, but why don't we simply treat `degraded-carrier` as connected:
```diff
-  if (STR_IN_SET(state, "routable", "degraded")) 
+ if (STR_IN_SET(state, "routable, "degraded", "degraded-carrier"))
        return true; 
```
"degraded-carrier" means that the bond/bridge interface may be functional and we should try to use it. In your PR, the check is changed to address check, but I don't see why that is better. In case of a statically configured network, the fact that an address is assigned does not say anything about the usability of the network.

**Comment by AlD** [comment]
Sorry, didn't get around to any testing. Thanks for fixing!
