### ISSUE TITLE
Incorrect use of the BIO mem ptr buffer

### ISSUE THREAD

**Issue by t8m** [systemd/systemd#12763]
The line:

https://github.com/systemd/systemd/blob/9a311429977daab43aa97b702e8f59337ff29f9b/src/resolve/resolved-dnstls-openssl.c#L37

is wrong. The code worked with OpenSSL 1.1.x only by accident. It would not work with 1.0.x and it does not work with 1.1.1c version anymore - see https://github.com/openssl/openssl/issues/9119

The code needs to keep the data pointer intact and move the rest of the non-written data in the place (BTW, this is not less efficient as the memmove was done by OpenSSL anyway in the older 1.1.1 releases where this worked.)

Or avoid the direct work with the BUF_MEM from the write BIO completely and use BIO_read() to get the data from the memory BIO.

**Comment by keszybz** [comment]
A patch would be great ;)
