### ISSUE TITLE
Systemd 225: --netwok-veth unusable

### ISSUE THREAD

**Issue by crequill** [systemd/systemd#1277]
All was working fine with systemd 218.  With systemd 225, my containers has no more network with veth. Archlinux on host and containers. If I boot one container with: systemd-nspawn -bD /var/lib/machines/ci-container -n
It's impossible to ping host from container or container from host. Network unreachable.

/sys/class/net show the host interfaces (enp3s1f0, ...)!
ip link show only the interfaces lo and host0 (as desired)

More infos from host:
    $ udevadm test-builtin net_setup_link /sys/class/net/ve-ognanrecoted
    calling: test-builtin
    === trie on-disk ===
    tool version: 225
    file size: 6656088 bytes
    header size 80 bytes
    strings 1714568 bytes
    nodes 4941440 bytes
    Load module index
    timestamp of '/etc/systemd/network' changed
    timestamp of '/usr/lib/systemd/network' changed
    Parsed configuration file /usr/lib/systemd/network/99-default.link
    Created link configuration context.
    ID_NET_DRIVER=veth
    Assertion 'udev_device' failed at src/libudev/libudev-device.c:126, function     udev_device_get_driver(). Ignoring.
    Config file /usr/lib/systemd/network/99-default.link applies to device ve-ognanrecoted
    ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
    Unload module index
    Unloaded link configuration context.

**Comment by poettering** [comment]
What are you precisely indicating here? The veth interface got created apparently, so what's precisely wrong?

Or are you using networkd and suggesting that networkd doesn't pick up the interface anymore? Does it work neither inside, nor outside of the container?

there seems to be an issue in libudev at least, which might be the cause of your problem, but for that we'd have to understand your problem first.

**Comment by crequill** [comment]
There is no more network usable in containers with veth interface:  this is the problem.
I don't use networkd. 
When I want to to add an address with iproute2 in the container, I get an error 'Network unreachable' . This is because there is a problem with veth: /sys/class/net show the host interfaces and ip show only lo and host0 (as desired). 
With system 218 and veth interface, /sys/class/net and iproute2 show the same things: container's interface.
The network is not working inside and outside of the container.

**Comment by poettering** [comment]
I am sorry, I do not understand a word. Are you sure you are running your containers with the --network-veth switch?

Can you paste the output of "ip link" and "ls /sys/class/net" when run _inside_ the container here please? And if you do that, what is there that should not be there, and what isn't there that should be there?

**Comment by crequill** [comment]
Sorry for my bad english!
Yes I'm sure I'm running a container with --network-veth (or -n):
systemd-nspawn -bD /var/lib/machines/ci-container -n

Here are the outputs asked inside the container with systemd 225:

```
[root@ci-container netctl]# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode
DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: host0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT
group default qlen 1000
    link/ether 36:15:87:7b:9a:dd brd ff:ff:ff:ff:ff:ff ip:

[root@ci-container ~]# ls /sys/class/net
enp3s1f0  enp3s1f1   lo ve-ci-container
```

Same outputs wiith systemd 218 always inside the container:

```
[root@ci-container netctl]# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: host0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 36:15:87:7b:9a:dd brd ff:ff:ff:ff:ff:ff

[root@ci-container ~]# ls /sys/class/net
host0 lo
```

**Comment by crequill** [comment]
Same problem with sytem226

**Comment by poettering** [comment]
Oha, same issue here. This is a major bug.

**Comment by poettering** [comment]
I figure we do not create the network namespace at the right time now, after we moved it around to deal with user namespacing...
