### ISSUE TITLE
--user --global for more actions

### ISSUE THREAD

**Issue by es20490446e** [systemd/systemd#12770]
It would be quite useful if "systemctl --user --global" could be used along more actions than "enable" and "disable". Like "daemon-reload", "start" and "stop".

This is valuable because it allows to activate services for user sessions without the need for them to log out. For example when installing or upgrading a software.

The work around for that is quite nasty actually, and somehow difficult to figure out.

**Comment by arvidjaar** [comment]
What is exact semantic of `systemctl --user --global daemon-reload|start|stop` and in what way is it (intended to be) different from `systemctl --user daemon-reload|start|stop`?

**Comment by es20490446e** [comment]
To apply those actions recursively to all logged in users, so the services can be instantly available for them after installation or upgrade.

**Comment by poettering** [comment]
I am sorry, but I am strictly against this: privileged clients should not by clients to unprivileged services like that. It's the wrong way round: unpriv user code should be able to listen for system events, but priv code should never synchronously call into unpriv user code, that's just wrong.

What's your usecase for this?

**Comment by es20490446e** [comment]
I'm writing a systemd service for the [xiccd](https://github.com/agalakhov/xiccd) daemon. That daemon executes on user space, acting as a bridge between colord and xserver in system space.

The package manager works in system space, so if an user installs xiccd there's no simple way to enable it for the current logged in sessions. All users would need to reboot for being able to have the service available after each installation or upgrade.

xiccd is required for color calibration tools to work, otherwise they fail. Since the package is already installed, many users would simply assume that the failure means that the software simply doesn't work. They won't know they need to reboot.

**Comment by anitazha** [comment]
What about for `systemctl daemon-reexec`? I noticed the RPM preinstall script runs `systemctl daemon-reexec` and it seems to make sense to also run that for user managers as well to minimize upgrade issues.

**Comment by es20490446e** [comment]
I will validate.

**Comment by es20490446e** [comment]
@poettering What works right now to manage user services on package scripts, without the need to reboot, is:

```
post_install () {
	systemctl --user --global enable "${service}"
	commandForAllUsers systemctl --user start "${service}"
}


pre_remove () {
	commandForAllUsers systemctl --user stop "${service}"
	systemctl --user --global disable "${service}"
}


post_remove () {
	commandForAllUsers systemctl --user daemon-reload
}


commandAsUser () {
	local user="${1}"
	local command="${*:2}"

	local userId="$(id --user "${user}")"
	local bus="unix:path=/run/user/${userId}/bus"
	local sudoAsUser="sudo -u ${user} DBUS_SESSION_BUS_ADDRESS=${bus}"
	
	${sudoAsUser} ${command}
}


commandForAllUsers () {
	local command="${*}"
	local users; readarray -t users <<< "$(loginctl --no-legend list-users | awk '{print $2;}')"
	
	for user in "${users[@]}"; do
		commandAsUser "${user}" "${command}"
	done
}
```

If having a "daemon-reexec" for user mode would be able to perform the same, it makes sense to me implementing it that way.

Otherwise those user services would only run properly after re-login. This is quite surprising in many cases, because sometimes an application depends of a particular daemon running to work.

When the user has just installed and launched that kind of application it will fail, then the user will wrongly attribute the problem to a software bug without realizing they just simply need to reboot.

This happened to me already with a couple of applications.
