### ISSUE TITLE
libudev does not refresh device list

### ISSUE THREAD

**Issue by fmorgner** [systemd/systemd#12776]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Updating the matches of an `udev_enumerate` instance, calling `udev_enumerate_scan_devices` and then iterating the list retrieved using `udev_enumerate_get_list_entry` should provide different different `udev_list_entry`s if the set of devices arising from the updated match differs from the the original match. 

**Unexpected behaviour you saw**
 > The resulting list does not differ.

**Steps to reproduce the problem**
Given the following program:
```c++
#include <libudev.h>
#include <iostream>

int main()
  {
  udev * ctx = udev_new();
  udev_enumerate * enumerate = udev_enumerate_new(ctx);

  udev_enumerate_add_match_subsystem(enumerate, "leds");
  udev_enumerate_scan_devices(enumerate);

  for(udev_list_entry * entry = udev_enumerate_get_list_entry(enumerate); entry; entry = udev_list_entry_get_next(entry))
    {
    std::cout << "entry: " << udev_list_entry_get_name(entry) << '\n';
    }

  udev_enumerate_add_match_subsystem(enumerate, "block");
  udev_enumerate_scan_devices(enumerate);

  std::cout << " ===== \n";

  for(udev_list_entry * entry = udev_enumerate_get_list_entry(enumerate); entry; entry = udev_list_entry_get_next(entry))
    {
    std::cout << "entry: " << udev_list_entry_get_name(entry) << '\n';
    }

  udev_enumerate_unref(enumerate);
  udev_unref(ctx);
  }
```
One would expect that the second loop also prints the syspaths of the devices in the `block` subsystem.

It seems that the issue lies in the way the `udev_enumerate_add_match_`... functions work. Considering the definition of `udev_enumerate` in [libudev-enumerate.c](https://github.com/systemd/systemd/blob/master/src/libudev/libudev-enumerate.c):

```c
struct udev_enumerate {
        struct udev *udev;
        unsigned n_ref;
        struct udev_list devices_list;
        bool devices_uptodate:1;

        sd_device_enumerator *enumerator;
};
```
a valid expection would be for the matching functions to set the non-static member variable `devices_uptodate` to `false`, similar to how the underlying implementation does (see [device-enumerator.c](https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-device/device-enumerator.c))

The documentation is silent about whether or not it is valid to adjust the matches of an enumerator after initial iteration of the original device list.

**Comment by yuwata** [comment]
Fix is waiting in #12777. If possible, please test the PR. Thank you.

**Comment by fmorgner** [comment]
Thanks @yuwata! Tested on Arch Linux and the client program now works as expected!

**Comment by yuwata** [comment]
Thank you for testing the PR.
