### ISSUE TITLE
Document that gpt-auto-generator supports LUKS root file systems

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#12786]
**Is your feature request related to a problem? Please describe.**
The manpage doesn't mention it is supported. It only mentions LUKS support for `/home` and `/srv`, but the source code suggests otherwise

**Describe the solution you'd like**
Add a line to the man page that root file system can also be LUKS-encrypted, just like `/home` and `/srv`

**Describe alternatives you've considered**
none

**Comment by keszybz** [comment]
There is no need to create an issue if you are going to immediately create a PR that fixes the issue. A plain PR with an explanation is good enough.
