### ISSUE TITLE
How can I get my systemd script to run (network issue)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#12780]
Hi!

I want this command after I login into Ubuntu before network is online.
"arpon -d -i enp0s3 -S"

I've been trying to get this systemd script to work:

[Unit]
Description=AntiSpoofing
ConditionFileIsExecutable=/usr/sbin/arpon
Before=network-online.target

[Service]
Type=forking
User=root
ExecStart=/usr/sbin/arpon -d -i enp0s3 -S
TimeoutSec=0
RemainAfterExit=yes
GuessMainPID=no

[Install]
WantedBy=network-online.target

When I start it manually, then it run.

What's wrong?
Please help, thanks!

Output-error-message:
systemd[1]: Starting AntiSpoofing...
arpon[922]: Jun 12 09:05:36 [ERROR] intf.c:467 intf_isvalidinterface: `No activate enp0s3 network i>
systemd[1]: AntiSpoofing-01.service: Control process exited, code=exited status=1
AntiSpoofing-01.service: Failed with result 'exit-code'.
systemd[1]: Failed to start AntiSpoofing.

Internet is working, but why systemd says "No activate enp0s3 network interface"?

**Comment by yuwata** [comment]
I am not familiar with `arpon`, but if you use `systemd-networkd`, then I recommend to add
```
Wants=network-online.target
After=systemd-networkd-wait-online.service
```

BTW, I am not sure, but I guess that `Type=simple` (default) and dropping `-d` seems ok.

**Comment by keszybz** [comment]
This is most likely an ordering issue. Waiting after `systemd-networkd-wait-online.service` is one option, but it shouldn't be necessary. Prolly enp0s3 is not there yet when your script is run. Maybe `After=sys-subsystem-net-devices-enp0s3.device` will work and be enough.

Anyway, this is not a support forum. Please take such questions to the mailing list.
