### ISSUE TITLE
Document of sysctl.d configuration files' piority is vague

### ISSUE THREAD

**Issue by duanyao** [systemd/systemd#12791]
**Is your feature request related to a problem? Please describe.**
I had a hard time understanding the piorities of `/etc/sysctl.d/*` and `/usr/lib/sysctl.d/*` by reading the man page of sysctl.d (and finally I did some experiments to figure it out):

<blockquote>
CONFIGURATION DIRECTORIES AND PRECEDENCE

       Configuration files are read from directories in /etc/, /run/, and /lib/, in order of precedence. Each configuration file in these configuration directories shall
       be named in the style of filename.conf. Files in /etc/ override files with the same name in /run/ and /lib/. Files in /run/ override files with the same name in
       /lib/.

      Packages should install their configuration files in /lib/. Files in /etc/ are reserved for the local administrator, who may use this logic to override the
       configuration files installed by vendor packages. All configuration files are sorted by their filename in lexicographic order, regardless of which of the
       directories they reside in. If multiple files specify the same option, the entry in the file with the lexicographically latest name will take precedence. It is
       recommended to prefix all filenames with a two-digit number and a dash, to simplify the ordering of the files.

       If the administrator wants to disable a configuration file supplied by the vendor, the recommended way is to place a symlink to /dev/null in the configuration
       directory in /etc/, with the same filename as the vendor configuration file. If the vendor configuration file is included in the initrd image, the image has to be
       regenerated.
</blockquote>

First, "configuration files are read from directories in /etc/, /run/, and /lib/, in order of precedence" looks like describing the piority, but it is not. Order of reading is not necessarily tied to piority, as it's a implementation detail.

Second, the man page doesn't describe the piority rules concisely, rather, mixing the rules in long paragraphs on "best practice" such as "packages should install their configuration files in /lib/ ..." and "If the administrator wants to disable ...".

Third, "override of a whole file" and "override of a single entry" are not discriminated clearly. They are the complicated part IMO.

**Describe the solution you'd like**
I'd like to describe the piority rules as follow:

Configuration files should reside in /etc/sysctl.d/, /run/sysctl.d/, or /usr/lib/sysctl.d/, and the filename should end with ".conf". /etc/sysctl.conf is deprecated and will not be applied.

If two or more configuration files have same name, the one in /etc/sysctl.d/ shadows those in /run/sysctl.d/ and /usr/lib/sysctl.d/, and the one in /run/sysctl.d/ shadows the one in /usr/lib/sysctl.d/ . Shadowed configuration files are not applied at all. 

Configuration files with different names are applied in lexicographic ascending order according to their names (directory names are not considered). That is, enitries in b.conf overrides those with same names in a.conf, no matter a.conf and b.conf reside in which directories above. Symbolic links are condidered by names of the links, not the targets.

**Describe alternatives you've considered**
None.

**Comment by keszybz** [comment]
Please submit this as PR.
