### ISSUE TITLE
"systemctl status <service>" to show last schedule time also.

### ISSUE THREAD

**Issue by ya1gaurav** [systemd/systemd#12797]
Currently, systemctl status shows the timings since service is running.
But it did not show time since the last time that particular service was scheduled.
Since a service will always be up, it is useful to know when the last time some event/processing happend on it. Thus, making it more interactive with system & to user also.

**Comment by arvidjaar** [comment]
It is unclear what you mean with "scheduled". Once service startup is completed systemd does not touch it anymore; it certainly does not "schedule" this service in any way. What service does while it is running is up to this service.

Can you provide example of information that you would like to see?

**Comment by ya1gaurav** [comment]
scheduled means when it got cpu by scheduler.
If could be helpful to make a decision on service state based on its last use. If a service has not been used from a long time & still running, some action can be taken on it for system optimization.

**Comment by keszybz** [comment]
Sorry, but this makes no sense. The kernel does not expose such information, because it's is very volatile and context dependent. Normally the kernel is very good at scheduling processes, so anything that wants to run will get to run.
