### ISSUE TITLE
Incorrect comparison of struct in_addr in sd-dhcp-client.c causes DHCP renewal to be treated like a new lease

### ISSUE THREAD

**Issue by mamarley** [systemd/systemd#12816]
**systemd version the issue has been seen with**
242

**Used distribution**
Ubuntu 19.10

Change f8862395e8f802e4106a07ceaaf02b6a1faa5a6d implemented support for receiving multiple "router" addresses from DHCP, and as a part of that, it replaced the "be32_t" type for that variable with "struct in_addr*".  However, in sd-dhcp-client.c (currently on line 1442), the comparison of the router from the old lease to the new one was not updated from "!=", so it appears to be comparing the pointer values, not the actual data inside them.  Because these pointers are always different, this is causing networkd to always behave as if it had gotten an entirely new lease instead of just a renewal of the existing lease, for example:

Jun 17 05:45:27 michaelmarley systemd-networkd[361]: enp0s25: DHCP lease lost
Jun 17 05:45:27 michaelmarley systemd-networkd[361]: enp0s25: DHCPv4 address 172.74.97.180/20 via 172.74.96.1

I would have submitted a PR to fix this instead of this bug report, but I wasn't sure what the best way to handle this would be regarding potential ordering differences in the response.

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #12817.
