### ISSUE TITLE
Enable waking up, and not just suspending on Lid Switch

### ISSUE THREAD

**Issue by blochl** [systemd/systemd#12811]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when my laptop enters suspend on lid close event, but does not wake up on lid open event - I need to press the power button to wake it up.

**Describe the solution you'd like**

I'd like the `HandleLidSwitch` option, if set to `suspend`, would also cause the laptop to wake up when the lid is opened.

**Comment by poettering** [comment]
systemd does not run when the system is suspended, it doesn't decide these things. It's your system's embedded controller which is on control then, and on most laptops it does what you want anyway. 

On ACPI the wakeup triggers can generally be configured in /proc/acpi/wakeup, where usually a device like "LID" is listed which may or may not be configured as a wakeup trigger

You can write to that file to make changes, but that's really out of scope for systemd, please see kernel docs about htat.

(Sometimes the firmware setup might allow you to configure wakeup sources too, maybe check that too)

Anyway, let's close this, as this is outside of systemd's scope, we cannot interfere with firmware, EC and hardware like this directly. Sorry!

**Comment by blochl** [comment]
@poettering, thanks a lot for your explanation! Indeed, it makes sense.
