### ISSUE TITLE
libgcrypt dependency on tarballs on debian jessie

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#1281]
I started getting complains about libgcrypt dependency of systemd when building systemd on debian jessie machines. 

Also found an old thread, http://lists.freedesktop.org/archives/systemd-devel/2013-November/014009.html. 

Since we generate tarballs through git achieve, I think the dependency to libgrypt is not optional anymore (due to libgrypt extention AM_PATH_LIBGCRYPT to automake). 

Lets either update the README or do some magic to detect the presence of AM_PATH_LIBGCRYPT extention.

**Comment by utezduyar** [comment]
`m4_ifdef([AM_PATH_LIBGCRYPT], [AM_PATH_LIBGCRYPT(...)])`

**Comment by utezduyar** [comment]
If http://lists.freedesktop.org/archives/systemd-devel/2013-November/014009.html is not valid anymore, I can create a PR with following patch from Olof Johansson Olof.Johansson@axis.com

```
If gcrypt's m4 macro files aren't installed, with this change, gcrypt
will be disabled. Without this change, autoconf would fail with not
being able to resolve AM_PATH_LIBGCRYPT.
---
configure.ac | 3 ++-
1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/configure.ac b/configure.ac
index 999f9f8..26e04da 100644
--- a/configure.ac
+++ b/configure.ac
@@ -677,12 +677,13 @@ AC_ARG_ENABLE([gcrypt],
                [have_gcrypt=auto])

if test "x${have_gcrypt}" != xno ; then
-        AM_PATH_LIBGCRYPT(
+        m4_ifdef([AM_PATH_LIBGCRYPT], [AM_PATH_LIBGCRYPT(
                [1.4.5],
                [have_gcrypt=yes],
                [if test "x$have_gcrypt" = xyes ; then
                        AC_MSG_ERROR([*** GCRYPT headers not found.])
                fi])
+        ])

        if test "x$have_gcrypt" = xyes ; then
                GCRYPT_LIBS="$LIBGCRYPT_LIBS"
-- 
2.1.4
```

**Comment by poettering** [comment]
I think it would be better to convince libgcrypt to just adopt pkg-config. Any chance you can ask gcrypt upstream to include one?

**Comment by utezduyar** [comment]
I can do that but could you please explain the advantage of using pkg-config (over going around libgcrypt upstream) so I can be more convincing to libgcrypt.

**Comment by poettering** [comment]
Well, pkg-config has the big advantage that optional build-time dependencies are truly optional, as no m4 sources of those deps are required to generate the configure script. If you do your own m4 scripts, this always means that the configure scripts can only be generated on systems where those m4 scripts are around, hence the build-time dependencies are not optional anymore on the system that generates the configure script.

In a world of git the distinction between the system that actually compiles the package and that generates the configure script is gone: it's both the same. In effect, optional deps which require m4 for the configure scripts are not optional at all anymore. By adopting pkg-config the problem goes away.

**Comment by olof** [comment]
I noticed that Werner Koch, the libgcrypt maintainer, has [previously rejected patches](http://lists.gnupg.org/pipermail/gcrypt-devel/2007-February/001109.html) proposing shipping pkg-config files. But that was 2007.

**Comment by dvdhrm** [comment]
The m4_ifdef looks good to me.

**Comment by utezduyar** [comment]
Doesn't seem like it is going to happen. https://lists.gnupg.org/pipermail/gcrypt-devel/2015-September/003569.html.

Are you against using `m4_ifdef`?

**Comment by dvdhrm** [comment]
@utezduyar: I just said, I'm fine with the m4_ifdef patch ;) Can someone prep a PR?

**Comment by poettering** [comment]
Well, it would have been good to let him know why precisely this would have been a good idea now.

**Comment by utezduyar** [comment]
@dvdhrm I must have missed your reply. Here we go - https://github.com/systemd/systemd/pull/1367
@poettering seems like the maintainer doesn't really want to mess with windows compatibility. We, systemd, go around them.
