### ISSUE TITLE
running system-wide checks on ExecStart= binary paths

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#12830]
**Is your feature request related to a problem? Please describe.**
I'd like to run a binary checker of sorts on all the systemd services on a system. The arguments to the checker should be the binary paths specified in `ExecStart=` (optionally, all the binaries for every `ExecXYZ=` field in a service).

**Describe the solution you'd like**
I think combined with `ExecCondition=` for services at https://github.com/systemd/systemd/issues/10596, I would need a way to make this a systemd-wide override (drop-in?) and also a special keyword (like the unit specifiers) to generically refer to the binary paths.

Would appreciate feedback on this proposal.

**Comment by topimiettinen** [comment]
I proposed in #11936 to extend `systemctl list-units` tool to analyze all units on the system. Perhaps this would also be useful in your case?

**Comment by poettering** [comment]
when do you want to run this? right before a service is started? or offline, after the system is up?

what's the precise usecase? i.e. what do you want to do in those checkers?

**Comment by anitazha** [comment]
@poettering Right before the service starts (why I think ExecCondition= might be useful for this).

Our end use case is to check if binary has a certain header and when it was last built in order to prevent service start up if it's too old. But the framework could have more generally applicable uses like checking signatures on ELF binaries or other validity checks.

**Comment by poettering** [comment]
i see. ExecCondition could work for that I presume?

**Comment by poettering** [comment]
(i.e. as discussed in that other bug)

**Comment by anitazha** [comment]
Yup ExecCondition= will work. But I'm not clear on the best way to generically apply this system-wide. I would like to avoid modifying/querying every service's unit individually by laying down one config somewhere (AFAIK this isn't possible).

In my head the config might look something like:
```
/etc/systemd/system/-.service.d/checker.conf:
  [Service]
  ExecCondition=/path/to/bin_checker %symbol that will pass in ExecStart= paths%
```

**Comment by poettering** [comment]
hmm, yeah we could probably extend the prefix drop-in logic so that a top-level dropin like you are suggesting is also honoured. But we should probably add a big big warning to the docs, that using this too much is a bad idea, except if you really know what you are doing.
