### ISSUE TITLE
Systemd output in Docker without -t switch

### ISSUE THREAD

**Issue by mvorisek** [systemd/systemd#12844]
When Docker image is started in terminal mode like:
```
docker run --mount type=tmpfs,destination=/run --mount type=tmpfs,destination=/run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --entrypoint '/bin/bash' -it jrei/systemd-debian:10
```
and then manually entered:
```
exec /lib/systemd/systemd
```
systemd displays the init log like:
```
ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Debian GNU/Linux 10 (buster)!

Set hostname to <e9366e98a874>.
File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  OK  ] Reached target Slices.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Swap.
[  OK  ] Reached target Local File Systems.
         Starting Create System Users...
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Paths.
....
```

When Docker image is started in WITHOUT terminal mode like:
```
docker run --mount type=tmpfs,destination=/run --mount type=tmpfs,destination=/run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --entrypoint '/bin/bash' jrei/systemd-debian:10 -c "exec /lib/systemd/systemd"
```
systemd displays no output. I can not use the `-t` or `-i` switch as the docker command is hardwired in the command executor I am using. How should the command above be modified to start the systemd with output and still with PID 1 (wth `exec` directly from the entry shell) but without the `-t` Docker tty switch?

**Comment by poettering** [comment]
pid 1 writes its status output to /dev/console. Does docker provide that?

container managers such as nspawn do provide that just fine, in all cases, in interactive and non-interactive mode.

**Comment by poettering** [comment]
but anyway, you probably should ask this in a docker forum, i am not sure this is the right audience, we are no docker people

**Comment by poettering** [comment]
(i do wonder though why your second cmdline involves bash?)

**Comment by mvorisek** [comment]
I was able to start the systemd up to the `default` service with `exec systemd`.

How can I then tell the systemd to exit with defined exit code from the `default` service, i.e. return from the command `exec systemd` above?

**Comment by poettering** [comment]
this is not a support forum, but a bug and feature tracker. Please contact the mailing list for support.

(I figure you are looking for the `SuccessAction=exit` + `FailureAction=exit` options though)
