### ISSUE TITLE
--system switch not working

### ISSUE THREAD

**Issue by mvorisek** [systemd/systemd#12843]
Systemd man says for `--system` switch:
```
Run a system instance, even if PID != 1
```

but currently the check for PID = 1 is still done even if this switch is used.

**Used distribution**
Debian 10

**Expected behaviour you didn't see**
systemd will start

**Unexpected behaviour you saw**
Can't run system mode unless PID 1.

**Steps to reproduce the problem**
start Docker image with bash entrypoint and run
```
/lib/systemd/systemd --system
```

**Comment by poettering** [comment]
Documentation needs updating. We cannot support what you want to do, PID 1 is very different from other processes, and we rely on that. --system is not useful except in combination with --test.

**Comment by mvorisek** [comment]
I would vote to support running the systemd under different PID with the `--system` flag defined in the docs currently as then in CI/CD enviroment it will be very handy to run the systemd like `systemd &`.

**Comment by poettering** [comment]
Fix waiting in #12868

**Comment by mvorisek** [comment]
Very good, thanks everyone involved!

**Comment by wavexx** [comment]
I stumbled upon this today. The --help output has not been updated that --system only works with --test.

**Comment by keszybz** [comment]
What do you mean? The patch changes `--help` output too.

**Comment by wavexx** [comment]
You're right - I always have trouble to see which PRs have landed in which release...

**Comment by sargun** [comment]
@poettering Would you ever reconsider in enabling systemd to run as not pid 1, without requiring a systemd to be pid 1?
