### ISSUE TITLE
Clearing udev enviroment variables

### ISSUE THREAD

**Issue by PavelAtr** [systemd/systemd#12849]
All versions

--- 60-persistent-storage.rules	2019-03-17 19:03:56.000000000 -0000
+++ 60-persistent-storage.rules.cd	2019-05-09 11:14:51.000000000 -0000
@@ -87,6 +87,7 @@
   IMPORT{builtin}="blkid --noraid"
 
 \# probe filesystem metadata of disks
+KERNEL!="sr*", ENV{ID_FS_UUID_ENC}="", ENV{ID_FS_LABEL_ENC}=""
 KERNEL!="sr*", IMPORT{builtin}="blkid"
 
 \# by-label/by-uuid links (filesystem metadata)

**Comment by poettering** [comment]
What is this supposed to be. If this is supposed to be a patch to merge it needs an explanation and should be submitted as PR and not as issue. Without any comment whatsoever this is not useful at all as the patch on its own doesn't really tell use anything about the why. Closing.
