### ISSUE TITLE
SSH processes are not put under the correct user slice consistently

### ISSUE THREAD

**Issue by beirnsi-ls** [systemd/systemd#12867]
**systemd version the issue has been seen with**
```
$ systemd --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

Also had the same issue on v232.

**Used distribution**
 Debian 9.9 and Debian 9.5

**Expected behaviour you didn't see**
To my understanding, either SSH processes for open connections should be put under the relevant user's slice, grouped by session (two SSH processes per session - privilege escalation), or they should be put under the ssh.service slice.

On my setup, this does not happen consistently.

**Unexpected behaviour you saw**
*Some* of the SSH processes are put under the ssh.service slice while *some* of the SSH process are put under the user.slice. This makes it impossible to correctly put limits on the amount of SSH process or the amount of user processes that are allowed to start. 

**Steps to reproduce the problem**
Use SSH to log into a single Debian 9 machine with a single user multiple times concurrently. Use `systemctl status user-<uid>.slice`, and `systemctl status ssh.service` to see the mix of SSH processes being assigned to either on or the other. 

My specific use case is a single machine to which about 5500 concurrent sessions to the same user are opened. I realize the is a lot, but it is what it is. These sessions are opened by multiple machines using `autossh`. This causes a thundering herd problem whenever we reboot the bastion machine (as all machines are continuously trying to connect to it from the moment it starts up). `autossh` slows down retries after failures so the thundering herd problem is resolved rather quickly and after a minute or two, all sessions will be opened successfully.

I opened a Debian bug before I came here, if you're interested, you can find it here:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929652

Here's an excerpt from it that might be useful:

> I did some digging around. Set the loglevel with systemd-analyze to debug
> and also added the debug flag to pam_systemd.so.
> 
> What I noticed is that on boot, when 5000+ machines try to
> authenticate at once, pam_systemd seems to fall on its ass and fail
> due to resource exhaustion. An excerpt from journalctl is attached
> below.
> 
> I thought this might've been the reason behind sshd processes not
> being assigned to the correct slice, but the processes for which
> these log entries are generated are not available on the system
> anymore, which I take as meaning that the sshd process exited
> because it couldn't open a session.
> 
> I tried to go about it the other way around and search for logs
> generated by any sshd process which is under the system.slice. I
> used this oneliner to do so:
> 
> for i in $(systemctl status ssh | grep 'sshd: <user>' | sed -E 's/[^0-9]*([0-9]*)[^0-9]*/\1/'); do echo "==> logs for process $i"; journalctl | grep '\[$i\]'; done | less
> 
> The search came up empty. For none of the currently 7000+ sshd
> processes which aren't in the correct user slice, there are any logs
> in journalctl. I verified and all logs since boot time are currently
> still in the journal, it hasn't rotated yet.
> 
> 
> 
> Jun 04 09:50:17 <hostname> sshd[8415]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[8691]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[8717]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[28538]: pam_systemd(sshd:session): Failed to connect to system bus: Resource temporarily unavailable
> Jun 04 09:50:17 <hostname> sshd[8652]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[8721]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[8716]: pam_systemd(sshd:session): Failed to create session: Connection timed out
> Jun 04 09:50:17 <hostname> sshd[28121]: pam_systemd(sshd:session): Failed to connect to system bus: Resource temporarily unavailable
> Jun 04 09:50:17 <hostname> sshd[28551]: pam_systemd(sshd:session): Failed to connect to system bus: Resource temporarily unavailable

**Comment by poettering** [comment]
this looks like dbus doesn't like us create that many requests. Do you see anything in the dbus logs about that? if you turn on dbus-daemon debug logging, to you see anything interesting there?

**Comment by poettering** [comment]
Let's close this, given there's no response.
