### ISSUE TITLE
systemctl suspend suspends twice

### ISSUE THREAD

**Issue by Tragetaschen** [systemd/systemd#12878]
**systemd version the issue has been seen with**
241

**Used distribution**
Yocto, Kernel 4.19.53

**Expected behaviour you didn't see**
Running `systemctl suspend` enters suspend once.

**Unexpected behaviour you saw**
Running `systemctl suspend` enters suspend twice. First for "mem" ("deep" in the kernel), then for "standby" ("shallow" in the kernel).

**Steps to reproduce the problem**
My ARM system supports the `freeze standby mem` states, which is also the default for the `SuspendState` configuration. I have set `SYSTEMD_LOG_LEVEL=debug` for the `systemd-suspend` unit and in the system log, I can see 
```
systemd-sleep[264]: Failed to write 'mem' to /sys/power/state: Invalid argument
systemd-sleep[264]: Failed to suspend system. System resumed again: Invalid argument
```
*after* the first wakeup and then the immediate shallow/standby suspend.

However, `echo mem > /sys/power/state && echo success` outputs `success` after resume.

Limiting the configuration to `SuspendState=mem` gives me a working system, but the systemd-sleep errors remain.

**Comment by poettering** [comment]
please do `systemctl edit systemd-suspend`. In the editor that opens, please add:

```
[Service]
ExecStart=
ExecStart=/usr/bin/strace -s 500 -f -o /tmp/sleep.strace /usr/lib/systemd/systemd-sleep suspend
```

Then, saved and exit the editor. And try to suspend agan. This changes the systemd-sleep command line so that it is run through strace. In /tmp/sleep.strace you will then find a trace of systemd-sleep actually does and what the kernel responds.

Please attach the result here (or maybe you see the issue already in the generated output yourself).

**Comment by Tragetaschen** [comment]
That's something I should have thought of...

```
[…]
299   write(4, "mem", 3)                = 3
299   write(4, "\n", 1)                 = -1 EINVAL (Invalid argument)
[…]
```

Which is not something `v241` or `v241-stable` can do...
Yocto to the rescue, though:
http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/systemd/systemd/0001-do-not-disable-buffer-in-writing-files.patch?h=warrior

Thanks for the hint, sorry to take up your time

**Comment by Tragetaschen** [comment]
But fixed already: http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/meta/recipes-core/systemd/systemd_241.bb?h=warrior&id=08dcc9965ba8979e46ae53334417bc198e6e9705
