### ISSUE TITLE
Any number of newlines chomped after continuation

### ISSUE THREAD

**Issue by srhb** [systemd/systemd#12883]
**v242 -- since 9adbfeb38ac101d6f73a033bb120d63513ffb240**

> Since this commit, surprising behaviour (to me, at least) has been introduced when a continuation is followed by newlines. Prior to this commit, the value of `setting1` is `1` for the following:

```
[Section]
setting1=1\

setting2=2
```

> After this commit, the value of `setting1` is `1 setting2=2`

> Any number of newlines after a continuing backslash appear to get chomped, and this is surprising to me at least, and I don't think that it's clear from `systemd.syntax` either. Is it intentional?

**Used distribution**
 > NixOS (which has a tendency to generate units with settings that have trailing continuations followed by newlines)

**Expected behaviour you didn't see**
 > (At most?) one newline is chomped

**Unexpected behaviour you saw**
 > Any number of newlines is chomped

**Steps to reproduce the problem**
> Start a continuation before any number of newlines followed by another setting.
> Here is a a small patch that applies to the aforementioned commit and reproduces the issue with `meson test test-conf-parser` in the hopes that it makes my confusion clear: https://gist.github.com/d45e8c6e93c6f544564e8366a41e5870

**References**
> https://github.com/NixOS/nixpkgs/issues/63533 and others

**Comment by yuwata** [comment]
@srhb Thank you for the report. Fix is waiting in #12890.
