### ISSUE TITLE
systemd-journald fails to send stream file descriptor, delays System shutdown

### ISSUE THREAD

**Issue by javashin** [systemd/systemd#12885]
hello this is happening to me all the time https://github.com/openbmc/openbmc/issues/2883
on gentoo using systemd from git 
[   10.776374] systemd[1]: systemd 242-1029-g330703f+ running in system mode. (+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=unified)

**Comment by poettering** [comment]
Not an actionable bug report. Closing.

Please contact your downstream distro for help first, and if they indicate it's actually an upstream problem, please report back, and fill in the issue form properly and provide logs of a minimal reproducer.

The submission form exists for a reason, and it's not to just erase it.
