### ISSUE TITLE
network: IPv6 Link local address is assigned even when LinkLocalAddressing=ipv4

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#12886]
**systemd version the issue has been seen with**
> ...systemd 242 (242-19-gdb2e367+)

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > … Based on LinkLocalAddressing value to "ipv4", i expected to see only IPv4 link local address.

**Unexpected behaviour you saw**
 > …i observed that ipv6 Link local addresses are not cleared after systemd-networkd restart with LinkLocalAddressing value set to "ipv4".

**Steps to reproduce the problem**
1.Configure LinkLocalAddressing to ipv4

cat /etc/systemd/network/00-abc-eth0.network
[Match]
Name=eth0
[Network]
LinkLocalAddressing=ipv4
....

root@abc:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 76:e2:84:14:16:6c brd ff:ff:ff:ff:ff:ff
    inet 10.7.8.7/16 brd 10.7.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2002:905:150e:301:72e2:84ff:fe14:555/64 scope global
       valid_lft forever preferred_lft forever
    inet6 2002:905:150e:301:72e2:84ff:fe14:444/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::74e2:84ff:fe14:166c/64 scope link
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

2.restart systemd-networkd service
root@abc:~# systemctl restart systemd-networkd

3.list ip addr show
root@abc:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 76:e2:84:14:16:6c brd ff:ff:ff:ff:ff:ff
    inet 169.254.15.240/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet 10.7.8.7/16 brd 10.7.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2002:905:150e:301:72e2:84ff:fe14:555/64 scope global
       valid_lft forever preferred_lft forever
    inet6 2002:905:150e:301:72e2:84ff:fe14:444/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::74e2:84ff:fe14:166c/64 scope link
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

**Comment by yuwata** [comment]
Is the network interface configured before `networkd` is started? `networkd` does not remove already configured ipv6 link local address.

**Comment by yuwata** [comment]
Please provide debugging logs of `networkd`. The log can be generated by creating e.g. the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by raviteja-b** [comment]
Please see if below logs of networkd helps for debug
systemd-networkd[1606]: eth0: Gained IPv6LL
systemd-networkd[1606]: Enumeration completed
systemd[1]: Started Network Service.
systemd-networkd[1606]: sit0: Could not acquire IPv                                                                                                                     4 link-local address: Invalid argument
systemd-networkd[1606]: eth0: Could not set route:                                                                                                                      Network is unreachable
systemd-networkd[1606]: eth0: Configured
systemd[1]: Starting Hostname Service...

systemd[1]: Started Hostname Service.
systemd[1]: Starting Cleanup of Temporary Directories...
systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
systemd[1]: Started Cleanup of Temporary Directories.
systemd[1]: systemd-hostnamed.service: Succeeded.

**Comment by yuwata** [comment]
The log does not contain enough information. Please do not cut the debugging logs...

And, if possible, could you test with the current git master?
