### ISSUE TITLE
ConditionKernelVersion=... doesn't work with quotes

### ISSUE THREAD

**Issue by simonbcn** [systemd/systemd#12881]
```
Arch Linux
systemd 242 (242.29-3-arch)
```

I'm trying to create a service for a program that can only run if the kernel version is equal to or greater than 5.1.
This is the `.service` file:
```
[Unit]
Description=gosearch file indexing server
ConditionKernelVersion=">=5.1"

[Service]
Type=simple
ExecStart=/usr/bin/gosearchServer

[Install]
WantedBy=multi-user.target
```

My kernel version is: 
```
$  uname -r                  
5.1.14-1-ck-skylake
```

But systemd refuses to start the service:
```
gosearch.service
● gosearch.service - gosearch file indexing server
   Loaded: loaded (/etc/systemd/system/gosearch.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2019-06-25 16:42:15 CEST; 2s ago
           └─ ConditionKernelVersion=">=5.1" was not met
```

I've looked for examples of how to use this option but I haven't found any and according to [your help page](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=) it should work.

**Comment by anitazha** [comment]
Removing the quotes worked for me. E.g.:
```
[Unit]
Description=gosearch file indexing server
ConditionKernelVersion=>=5.1
```

**Comment by simonbcn** [comment]
Yes, it's without quotes.

**Comment by mbiebl** [comment]
Hm, I would still consider it a bug if `">=5.1"` is not treated as a string.

**Comment by simonbcn** [comment]
@mbiebl I agree. I reopen the issue.

**Comment by yuwata** [comment]
We usually do not support quotation, e.g., `ProtectSystem="yes"` does not work. So, supporting quotation here sounds inconsistent for me. With #12889, now it support space between `=`, `!`, `|`. So, you can write the condition like `ConditionKernelVersion= >=5.1`, and its readability is OK I think.

I've preped a patch to support quotation, but now it is dropped. I'd like to also close this. WDYT?

**Comment by mbiebl** [comment]
@yuwata Hm, valid point regarding consistency. On the other hand, using a space doesn't feel very consistent either (and is not very intuitive).
