### ISSUE TITLE
Service Timestamps not being reported properly

### ISSUE THREAD

**Issue by sgilson7** [systemd/systemd#12902]
**systemd version the issue has been seen with**
> systemd 237

**Used distribution**
 > Ubuntu 18.04

**Unexpected behaviour you saw**
 > When using cloud-init to provision Ubuntu 18.04 on Azure, ActiveExitTimestampMonotonic and ExecMainStartTimestampMonotonic are not being reported properly, as they are 30 minutes ahead of InactiveExitTimestampMonotonic.

**Steps to reproduce the problem**
On Azure, if you deploy an Ubuntu 18.04 VM and check the timestamps of cloud-init
```
systemctl show cloud-init-local
```
the ActiveExitTimestampMonotonic and ExecMainStartTimestampMonotonic are about 30 minutes ahead of InactiveExitTimestampMonotonic, when they should be the same. By executing
```
cat /var/log/cloud-init.log | grep "running 'init-local'"
```
you will be presented a log that reports a timestamp of when cloud-init starts. This should be the same time as the ActiveStartTimestamp, but it is not.

We suspect this happens because early in cloud-init, there is a polling loop that waits to get a new DHCP lease from Azure and then connect to the internet. Once it connects to the internet there is a timesync, which I suspect is what breaks the 2 timestamps in question. Removing the polling loop fixes the problem, but the polling loop happens after quite a bit of the service has already run, so it doesn't make sense that the polling loop would occur before ActiveStartTimestamp is logged.

**Comment by poettering** [comment]
did your service get restarted maybe? 

maybe your service gets started twice? once in the initrd and once on the host?

this bug report is not really actionable. It's not clear at all what this has to do with systemd upstream. Can you describe a minimal reproducer (without azure and cloud-init and ubuntu and that stuff). It's very hard otherwise for us to understand what you are trying to do.

**Comment by poettering** [comment]
Let's close due to lack of response.
