### ISSUE TITLE
nspawn containers should be able to exit with a non-zero status

### ISSUE THREAD

**Issue by alban** [systemd/systemd#1290]
I have a nspawn container running systemd as pid1, and it runs several services. I would like that if any service fails, the container terminates and nspawn returns an non-zero exit code ($? in the shell).

I can configure the services to run `halt.target` on failure and the container will shutdown. But `systemd-nspawn` will always return the exit code 0. At the moment, this is not possible to return a different value when a service in the container fails.

The way it currently works in the container is:
- some service calls `systemctl halt`
- `systemd` calls `systemd-shutdown`
- `systemd-shutdown` calls the system call `reboot()`
- since we are not in the initial pid namespace, the kernel will not reboot the computer but instead ~~send `SIGINT` to pid1 (systemd)~~ pretend that `SIGINT` is sent to pid1 (systemd). The `systemd` process and all processes in the container get terminated.
- `systemd-nspawn` notices that `systemd` was killed by `SIGINT` and understands that as a normal shutdown
- `systemd-nspawn` returns the exit code 0

After discussion on irc, it could be implemented in this way:
- adds ExitCode as property to PID 1's "Manager" bus object
- adds a SetExitCode() bus call to set it on the same object, and that returns an error on baremetal, thus allowing early failure
- adds support for setting this to "systemctl exit 55"
- adds the exit.target + exit.service units to the system instance
- changes systemd-shutdown to actually exit with the configured exit code

This feature request was inspired by https://github.com/coreos/rkt/pull/1407#issuecomment-140816265

/cc @yifan-gu @iaguis @poettering

**Comment by poettering** [comment]
Looks good to me. 

Note that the `systemd --user` instance does not invoke systemd-shutdown but exits right-away. Of course, the exit code should work for that too.

**Comment by yifan-gu** [comment]
SGTM, thanks @alban !

**Comment by yifan-gu** [comment]
btw, I sent SIGINT to the systemd process in the nspawn. The nspawn does reboot.

**Comment by poettering** [comment]
@yifan-gu yeah, sending SIGINT to PID 1 results in reboot on SysV. The kernel actually never sends SIGINT to the PID1, but instead just reports to nspawn a reboot() called in the container as "killed by signal SIGINT"...

**Comment by alban** [comment]
- v1: https://github.com/systemd/systemd/pull/1301
- v2: https://github.com/systemd/systemd/pull/1310
- v3: https://github.com/systemd/systemd/pull/1313
- v4: https://github.com/systemd/systemd/pull/1318 => merged.

For the record, this feature will be available in v227.
