### ISSUE TITLE
How to quiet cron sessions logging with systemd (Again.)

### ISSUE THREAD

**Issue by CraigEC** [systemd/systemd#1291]
Ok, I'm new to Oracle 7 and the whole systemd thing.
I only really cared because cron is spamming my /var/log/messages file to death.

I've spent hours searching for a solution, and come across the 'religious zealots' ranting on both sides.
Please, cron spamming /var/log/messages IS a problem for me.
I need a solution to this specific problem that doesn't compromise some other unrelated component.

This is NOT an unreasonable request (despite some zealots claiming it is).

Does anyone have a working (simple?) solution to this really annoying 'feature'?

**Comment by michich** [comment]
As a workaround, rsyslog (which is what actually writes to /var/log/messages) has powerful filtering abilities.

**Comment by CraigEC** [comment]
I think I've got it,

#cat /etc/rsyslogd/cron_noise_collector.conf
:msg, regex, "^._Starting Session [0-9]_ of user" stop
:msg, regex, "^._Started Session [0-9]_ of user" stop
:msg, regex, "^._New session [0-9]_ of user" stop
:msg, regex, "^._Removed session [0-9]_" stop

Not sure if I've shot a foot with this yet or not..

Thanks for the suggestion

**Comment by poettering** [comment]
I don't think we should start and stop units without logging about that, sorry. If you don't want to see these messgaes, filter them out, but I am very sure we should always generate log messages when a unit starts or stops. Sorry.

**Comment by CraigEC** [comment]
With respect Lennart,
  I'm really wanting to keep clear of any 'religious debates' here,
which is why I attempted to state my very real problem clearly and ask
for more knowledgeable people to offer the best solution.

Simply stated, many of our systems have VERY active cron processes.
These add an unacceptable amount of 'noise' to /var/log/messages with
undesirable consequences.

I will most happily entertain and attempt any reasonable solutions
offered.

Simply stating (paraphrase) "I need these messages" is simply
invalidating what is for my business a valid concern/issue/problem.

I am hoping you have an alternative solution to offer.

Thanks in advance.

---

Craig Campbell   mailto:craigc@wil.com mailto:craigc@wil.com  
Waterfront International Ltd. 
95 Wellington Street West, 
Toronto, Ontario, 
Canada 
M5J 2N7 

[416] 368-6500

**Comment by poettering** [comment]
I am sorry, but we'll not allow turning off and on individual log messages in systemd. I can see that you want to filter this out, and go ahead to do that via rsyslog, but these messages should be generated by systemd in pretty much all cases, and I really don't want to see an option for individually turning activation messages on or off. Sorry.

**Comment by CraigEC** [comment]
Thanks for the reply.

While it is tempting to debate that stance with you - especially since
this specific case is so clearly defensible - I will refrain.

With Unix being what it is, eventually a solution will make it into the
default distributions.
It would be better if that solution were well thought out in advance
rather than a reaction to an annoying 'feature'.

All the best.

---

Craig Campbell   mailto:craigc@wil.com mailto:craigc@wil.com  
Waterfront International Ltd. 
95 Wellington Street West, 
Toronto, Ontario, 
Canada 
M5J 2N7 

[416] 368-6500

**Comment by mildsunrise** [comment]
I can see both of your positions, but filtering messages in with regexes seems pretty much like a hack to me. systemd could change the text of its messages at any time, or my regexes could have bugs for edge cases...

A more elegant & simple solution would be to filter out any messages coming from systemd with _info_ or _debug_ severity. **Edit:** this is explained [here](https://unix.stackexchange.com/a/330424/7079).

**Comment by otheus** [comment]
The solution already seems to exist within systemd. Simply raise the LogLevel threshold in the configuraiton. This will eliminate most messages users (and even admins) don't care about: 

    #LogLevel=info
    LogLevel=notice

A `systemctl daemon-reexec` will reload the file.

My question to @poettering is this: Why are such messages (session starting, slice creation) in "info" and not "debug"? The information itself is not very useful. It does not (only) indicate the start of a unit task, and I cannot ascertain the utility of knowing that a "slice" has been created, unless I'm doing some kind of debugging on systemd itself.
