### ISSUE TITLE
systemd-networkd: [IPv6AcceptRA] UseDNS=no has no effect.

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#12917]
**systemd version the issue has been seen with**
> systemd 242 (242.32-1-arch)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-networkd should not configure systemd-resolved to use IPv6RA advertised RDNSS for managed interface when UseDNS=no is set under [IPv6AcceptRA] in the .network file.

**Unexpected behaviour you saw**
 > UseDNS=no under [IPv6AcceptRA] has no effect and networkd still configures the advertised RDNSS to be used.

#5071 seems to reference fixing this issue in #5040 but I still see the described behavior.

I did see the blurb about DHCPv6 under DHCP= in systemd.network(5), but shouldn't IPv6AcceptRA.UseDNS still apply? If this behavior is intended, is there any way for me to get a IPv6 address and _not_ use the advertised DNS?

**Comment by yuwata** [comment]
Please provide .network file.

**Comment by RPigott** [comment]
Sure. Sorry for the brief OP.

Content of `/etc/systemd/network/25-wireless.network`:
```
[Match]
Name=wl*

[Network]
MulticastDNS=yes
DHCP=ipv4
IPv6PrivacyExtensions=yes

[DHCP]
UseDomains=yes
UseDNS=yes
RouteMetric=1024

[IPv6AcceptRA]
UseDNS=no
```
Configured DNS servers for managed wlp2s0 interface:
```
$ resolvectl dns wlp2s0                                     
Link 2 (wlp2s0): 10.1.0.253 2600:8800:1e00:242::1
```
By repeatedly `systemctl restart systemd-{networkd,resolved}` I got some captures.

DHCPv4 exchange on wlp2s0 from networkd showing origin of ip4 server:
```
$ tcpdump -i wlp2s0 -n port 67 and port 68 -w dhcp.dump
$ tshark -r dhcp.dump -T fields -e dhcp -e dhcp.option.domain_name_server
Dynamic Host Configuration Protocol (Discover)	
Dynamic Host Configuration Protocol (Offer)	10.1.0.253
Dynamic Host Configuration Protocol (Request)	
Dynamic Host Configuration Protocol (ACK)	10.1.0.253
```
ICMPv6 RA exchange on wlp2s0 from networkd showing origin of ip6 server:
```
$ sudo tcpdump -i wlp2s0 -n icmp6 -w ip6ra.dump
$ tshark -r ip6ra.dump  -T fields -e icmpv6 -e icmpv6.type -e icmpv6.opt.rdnss
icmpv6	133	
icmpv6	134	2600:8800:1e00:242::1
icmpv6	135	
icmpv6	135	
icmpv6	134	2600:8800:1e00:242::1
```

I wish I had some log messages or something from systemd-{networkd,resolved} to show, but when debugging this I found that even with a drop in file:
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
there are no messages from either service indicating which dns servers are configured on what interface or for what reason, so it took me a little while to figure out what (I think) is going on.

I tried disabling IPv6AcceptRA entirely, however that results in no IPv6 address for the interface, which is also undesirable.

The result I want is to configure wlp2s0 to use _only_ the DHCPv4 advertised 10.1.0.253 for DNS, however networkd consistently gives it the ip6 address as well. Being a networkd managed interface, I cannot change it, so I need some way to tell networkd to ignore the ipv6ra advertised server. After reading `systemd.network(5)`, I thought IPv6AcceptRA.UseDNS would have the desired effect, but it does not.

Hopefully that is more clear. Here are the referenced pcap capture files if it helps:
[captures.zip](https://github.com/systemd/systemd/files/3347765/captures.zip)

**Comment by yuwata** [comment]
Thanks.

cc @ssahani.

**Comment by ssahani** [comment]
Let's isolate the issue with only IPv6RA and I can't reproduce with radvd and networkd conf.
```
interface veth-peer
{
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 4;
        AdvSendAdvert on;
        AdvManagedFlag on;
        prefix 2001:db7::/64
        {
        AdvValidLifetime 14300; AdvPreferredLifetime 14200; }
        ;
        RDNSS 2001:db7::3 2001:db7::6
        {
                AdvRDNSSLifetime 30;
        };
};
```

```

cat veth.netdev                                                                                                          ✔  ⚡  638  16:08:31
[NetDev]
Name=veth99
Kind=veth
MACAddress=12:34:56:78:9a:bc

[Peer]
Name=veth-peer
MACAddress=12:34:56:78:9a:bd
 root@Zeus  ⚙ /etc/systemd/network  cat veth.network                                                                                                         ✔  ⚡  639  16:08:36
[Match]
Name=veth99

[Network]
DHCP=no
IPv6AcceptRA=yes

[IPv6AcceptRA]
UseDNS=no
 root@Zeus  ⚙ /etc/systemd/network  cat veth-peer.network                                                                                                    ✔  ⚡  640  16:08:40
[Match]
Name=veth-peer

[Network]
IPv6AcceptRA=no
Address=2001:db8::30
Address=192.168.5.1/24

```


```

ink 14 (veth99)
      Current Scopes: LLMNR/IPv6
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes

```


If I turn yes then 

```
Link 14 (veth99)
      Current Scopes: DNS LLMNR/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes
  Current DNS Server: 2001:db7::3
         DNS Servers: 2001:db7::3
```

**Comment by yuwata** [comment]
So, the ipv6 nameserver comes from DHCPv6. Maybe, we need to extend `UseDNS=` setting to take boolean and `ipv4` and `ipv6`.

**Comment by yuwata** [comment]
I prep a patch for this in #12928. @RPigott If possible, could you test the PR?

**Comment by RPigott** [comment]
I have tested the PR and can confirm that it works in my case when applied to systemd-stable in the archlinux 242.32-2 PKGBUILD. Thanks to @yuwata @ssahani , it is clear the second server is actually installed by DHCPv6, not RA.

According to `radvdump`, my router sets the 'O' but not the 'M' bit in its RA, though I'm not certain how to configure it otherwise.

Do you think it would be sensible to add some debug-level messages indicating which nameservers networkd configures for which interface and for which reason? If you think that is sensible and is a low-hanging fruit, I am inclined to submit a PR to that effect myself in a separate issue.

**Comment by yuwata** [comment]
> Do you think it would be sensible to add some debug-level messages indicating which nameservers networkd configures for which interface and for which reason? If you think that is sensible and is a low-hanging fruit, I am inclined to submit a PR to that effect myself in a separate issue.

Patches are always welcome.
