### ISSUE TITLE
thumb buttons reversed on CHERRY MW 2310

### ISSUE THREAD

**Issue by texoft** [systemd/systemd#12914]
**systemd version**
```
systemd 242 (242.29-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
   Operating System: Arch Linux
             Kernel: Linux 5.1.15-zen1-1-zen
       Architecture: x86-64
```

**Hardware affected**
Wireless USB mouse CHERRY MW 2310
```
Input device ID: bus 0x3 vendor 0x1a81 product 0x1701 version 0x111
Input device name: "G-Tech Wireless Dongle Mouse"
```

**Expected behaviour you didn't see**
 > Pressing fore thumb button navigates back, pressing aft thumb button navigates forward.

**Unexpected behaviour you saw**
> The thumb buttons are reversed.
 > See https://bugzilla.kernel.org/show_bug.cgi?id=204025

**Proposed fix**
I've managed to create a local HWDB file `/etc/udev/hwdb.d/71-mouse-local.hwdb` that swaps the thumb buttons:
```
#:name:G-Tech Wireless Dongle Mouse:
evdev:input:*v1A81*p1701*
 KEYBOARD_KEY_90005=back
 KEYBOARD_KEY_90004=forward
```

I'd like to know if/how this solution can be contributed to other users.

**Comment by poettering** [comment]
If you have a patch, then submit it as PR please, not as issue.

**Comment by whot** [comment]
What does `libinput record` say about the mouse buttons without the hwdb quirk? I'm wondering if that's an instance of [this patchset here](https://patchwork.kernel.org/patch/10878483/), in which case fixing it right now may be making things worse

**Comment by texoft** [comment]
Hi @whot, 
I believe it's not. The scan codes should remain same even after kernel renames the buttons, but don't take my word for it, I'm no expert in this.

The output from evdev for this particular mouse seems to have those two buttons reversed, perhaps it's swapped in mouse HW. I don't have either time or skills to figure out. That's why I filed the kernel bug above, because I believed it should be fixed there not worked around in layers above. Unfortunately they nicely told me to go away.  

So again, the hwdb file in OP fixes it for me, but I was hoping you guys with more insight in architecture could tell me if this is a right way of fixing it. I'll be more than happy to provide a PR with above changes in say `70-mouse.hwdb`.

Thanks!

**Comment by whot** [comment]
cc @bentiss for any comments
