### ISSUE TITLE
[RFE] Recipe for correct handling of nfsroot

### ISSUE THREAD

**Issue by brianthelion** [systemd/systemd#12923]
**Is your feature request related to a problem? Please describe.**
`nfsroot` has been discussed time and time again here and on various downstream issue trackers. Broadly speaking, there is an aparent lack of consensus about what the "correct" setup of systemd looks like for `nfsroot` clients. If consensus does exist, it's difficult to find in the face of considerable search noise.

**Describe the solution you'd like**
What I would like is an official "recipe" -- an opinionated recommendation from the systemd maintainers -- for how to handle `nfsroot` on client machines. The focus should be on vanilla clients, eg, those typical of popular desktop distros. Specifically,
* What, if anything, needs to be added to `fstab`?
* What, if anything, needs to be added to the systemd units?
* What should the admin do in the face of typical error modes?

Note that's it's perfectly reasonable for the requested recipe to live here, in this issue's discussion thread.

**Describe alternatives you've considered**
* Trying to discover such a recipe by trial and error.
* Rummaging through various issue trackers.
* Bugging folks on IRC.

**Comment by poettering** [comment]
I am sorry, but you probably have to enquire nfs folks about this, we have no experience with that in systemd upstream.

If you want to extend systemd units (be it services or .mount units such as those generated from fstab), then do so from a generator (see https://www.freedesktop.org/software/systemd/man/systemd.generator.html). In fact, write a generator that runs in the initrd and on the host. If run in the initrd it should generate a sysroot.mount unit based on the NFS server info for the rootfs (for example, by parsing this from /proc/cmdline). If run on the host it should extend any unit files it wants to extend. Or generate additional .mount units if you like. 

/etc/fstab is user config, you should not extend that, and you don't need to as systemd just generates .mount units from that anyway (via a generator shipped with systemd) and hence if you create the .mount units you need yourself via a generator everything should be good.

Note that this is a bug and RFE tracker though. It appears to me what you are asking is mostly a general discussion/help/support question, which should really be moved to the systemd mailing list. If you need further help on this, please contact the mailing list instead.

The issue submission form tries to make this very clear, to minimize frustration. Anyway, I hope it's OK if I close this here now.

**Comment by brianthelion** [comment]
@poettering

## RE: recipes

> Note that this is a bug and RFE tracker though. It appears to me what you are asking is mostly a general discussion/help/support question, which should really be moved to the systemd mailing list. If you need further help on this, please contact the mailing list instead.

IMHO, "recipes" are a well-defined form of documentation and, consequently, I was making an RFE regarding documentation. Apologies if that wasn't clear. It's your show but, respectfully, I think this is a form of documentation that systemd could really benefit from. Recipes are the in-source-code version of a FAQ, one that would keep you from having to deal with excessive n00b traffic like mine on the mailing list and IRC. Just my two cents.

## RE: `nfs`

> I am sorry, but you probably have to enquire nfs folks about this, we have no experience with that in systemd upstream.

Forgive me but, unless I'm misunderstanding you, this seems like an odd position to take. systemd is an orchestration technology, `nfs` is the thing being orchestrated (specifically on startup and shutdown), and thus the `nfsroot` issue clearly falls under systemd's purview. Can you share a little more about your position here so I can do a better job positioning future requests?

## RE: `nfsroot`

> If you want to extend systemd units (be it services or .mount units such as those generated from fstab), then do so from a generator (see https://www.freedesktop.org/software/systemd/man/systemd.generator.html). In fact, write a generator that runs in the initrd and on the host. If run in the initrd it should generate a sysroot.mount unit based on the NFS server info for the rootfs (for example, by parsing this from /proc/cmdline). If run on the host it should extend any unit files it wants to extend. Or generate additional .mount units if you like.

> /etc/fstab is user config, you should not extend that, and you don't need to as systemd just generates .mount units from that anyway (via a generator shipped with systemd) and hence if you create the .mount units you need yourself via a generator everything should be good.

This is helpful, thanks!

For anyone else dealing with `nfsroot` issues, I'll try to pull some helpful resources into this thread as I go.

**Comment by poettering** [comment]
> IMHO, "recipes" are a well-defined form of documentation and, consequently, I was making an RFE regarding documentation. Apologies if that wasn't clear. It's your show but, respectfully, I think this is a form of documentation that systemd could really benefit from. Recipes are the in-source-code version of a FAQ, one that would keep you from having to deal with excessive n00b traffic like mine on the mailing list and IRC. Just my two cents.

Well, there can never be enough documentation, but I am not sure this is something to document as part of systemd. It's probably something to implement correctly in the NFS client package then document it once there, and then everything is great. But NFS is nothing we know much about, not anything too common that it deserves direct support in systemd.

systemd is one component of an OS of many. We are of course happy to work with devs who have questions regarding integration of their package into systemd, but this doesn't look like that. I understand you are asking for user/admin facing docs, but that's not really what we do here... Basically, NFS needs to be documented by NFS people.

**Comment by poettering** [comment]
> > 
> 
> Forgive me but, unless I'm misunderstanding you, this seems like an odd position to take. systemd is an orchestration technology, `nfs` is the thing being orchestrated (specifically on startup and shutdown), and thus the `nfsroot` issue clearly falls under systemd's purview. Can you share a little more about your position here so I can do a better job positioning future requests?

I don't know what "orchestration technology" is supposed to be. systemd is a system and service manager, plus auxiliary tools. Specific technologies such as NFS are something to cover in the NFS package, independently of systemd. We provide integration points (such as the aforementioned generators), but this integration needs to take place in NFS.

**Comment by brianthelion** [comment]
### systemd-devel, 2011
https://lists.freedesktop.org/archives/systemd-devel/2011-May/002375.html
OP had issues with the machine hanging on reboot.
