### ISSUE TITLE
systemd-networkd version 241 not setting up tunnel of type GRE with Local=any

### ISSUE THREAD

**Issue by frittentheke** [systemd/systemd#12922]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > CoreOS Container Linux

**Expected behaviour you didn't see**
 > After a recent update to systemd 241 my previously working GRE tunnel
does not work anymore.

I found https://github.com/systemd/systemd/issues/12041 which requires
the "Local" variable to be set.
As soon as I add a static IP to the "Local=" variable (the one eth0
received from DHCP) the tunnel works again.
According to https://github.com/systemd/systemd/issues/12041 a value of
"any" would be possible as well though.

So I tried to simply add _Local=any_:

The configs are:

--- cut ---

$ cat /etc/systemd/network/mytunnel.netdev

[NetDev]
Name=mytunnel
Kind=gre

[Tunnel]
Local=any
Remote=192.168.1.1

$ cat /etc/systemd/network/mytunnel.network

[Match]
Name=mytunnel

[Network]
Address=192.168.255.1/24
DHCP=no
LinkLocalAddressing=no

[Route]
Gateway=192.168.255.2
Destination=172.16.0.0/16

$ cat /etc/systemd/network/eth0.network

[Match]
Name=eth0

[Network]
DHCP=yes
Tunnel=mytunnel

[DHCP]
UseDNS=true
UseNTP=false

--- cut ---

Jun 28 13:58:54 localhost systemd-networkd[637]: mytunnel:
vti/ipip/sit/gre/gretap/erspan tunnel without a local IPv4 address
configured in /etc/systemd/network/mytunnel.netdev. Ignoring
Jun 28 13:58:54 localhost systemd-networkd[637]:
/etc/systemd/network/eth0.network:5: Tunnel is invalid, ignoring
assignment: mytunnel

**Steps to reproduce the problem**

Apply the above config to greate a GRE tunnel setup without specifying the "Local" IP of the tunnnel.

**Comment by yuwata** [comment]
#12041 is already fixed by bb9683e096f0f4db364885a71ae4e9b48e7b9ddf, and the commit is included in v242. Please contact to downstream to backport the commit.
