### ISSUE TITLE
all user's groups are set by default when only User= is specified, instead of just default group

### ISSUE THREAD

**Issue by nicki-krizek** [systemd/systemd#12936]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 in systemd unit, I specified
```
[Service]
...
User=knot-resolver
```

`Group=` *wasn't set* explicitly. According to `systemd.exec(5)`: ` If no group is set, the default group of the user is used.`

User `knot-resolver` has a primary group `knot-resolver`, and a secondary group `othergroup`. The service should have only `knot-resolver` group set.

**Unexpected behaviour you saw**
 Both groups, `knot-resolver` and `othergroup` are available in the service launched by sytemd.

**Steps to reproduce the problem**
reproducible, follow description above

**Comment by yuwata** [comment]
From systemd.exec(5)
> SupplementaryGroups=
> Sets the supplementary Unix groups the processes are executed as. This takes a space-separated list of group names or IDs. This option may be specified more than once, in which case all listed groups are set as supplementary groups. When the empty string is assigned, the list of supplementary groups is reset, and all assignments prior to this one will have no effect. **In any way, this option does not override, but extends the list of supplementary groups configured in the system group database for the user.** This does not affect commands prefixed with "+".

**Comment by poettering** [comment]
Fix waiting in #13036
