### ISSUE TITLE
How to restart a systemd service whenever Chromium-browser opens/launches?

### ISSUE THREAD

**Issue by hammadullah125** [systemd/systemd#12934]
I have a systemd service that must be restarted whenever Chromium-browser opens/launches.

```
[Unit]
Description=Load cgroup configs
After=multi-user.target

[Service]
Type=forking
ExecStartPre=/bin/echo "Processing /etc/cgconfig.conf ..."
ExecStartPre=/usr/sbin/cgconfigparser -l /etc/cgconfig.conf
ExecStartPre=/bin/echo "Processing /etc/cgrules.conf ..."
ExecStart=/usr/sbin/cgrulesengd --logfile=/var/log/cgrulesengd.log
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
This service is used to process the configuration files that are used to limit the CPU and Memory usage of Chromium-browser using CGroups.

This service is activated on the boot and then when I open the chromium browser and run the following commands, it return nothing.
```
cat /sys/fs/cgroup/cpu/browsers/tasks
cat /sys/fs/cgroup/memory/browsers/tasks
```
BUT then I have to restart the service manually `service <service_name> restart`. After that, above commands return the PIDs used by the Chromium browser. For example
```
5314
5347
5349
5403
5603
```
How can I automate this service to restart automatically whenever there is a chromium launch? and I don't have to restart the service manually again and again.

**Comment by poettering** [comment]
I am sorry, but this is not a support forum. Please use the systemd mailing list for that. THe submission forum should have made that really clear.

That said, cgroups are managed by systemd exclusively, and cgrulesengd and stuff are not compatible with that. You cannot mix systemd and cgrulesengd on the same system. If you do things will break and you are on your own. There can only be one component managing cgroups, and on systemd systems that is systemd. Applications can ask for their own subtrees to manage, but cgrulesengd doesn't do that, so it's simply incompatible.

See https://systemd.io/CGROUP_DELEGATION.html

**Comment by hammadullah125** [comment]
Sorry I posted the question in a wrong place that is why I closed the issue immediately.
