### ISSUE TITLE
TEST-34-DYNAMICUSERMIGRATE (maybe others) seem to fail due to problem with bus-api-system stopping/restarting

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#12932]
**systemd version the issue has been seen with**
> v242

**Used distribution**
 > Ubuntu CI

**Expected behaviour you didn't see**
 > Test pass, or at least complete

**Unexpected behaviour you saw**
 > Test fails to complete, times out

**Steps to reproduce the problem**

This happens intermittently in Ubuntu CI autopkgtests, e.g.:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/i386/s/systemd-upstream/20190701_175054_5f9ea@/log.gz

where during a test run, bus-api-system appears to stop, and while it's restarting, the testsuite completes but its notification of completion never reaches the testsuite's call to 'systemd-run --wait', so the test just waits forever for its test service to complete, until the test timeout is reached.

**Comment by ddstreet** [comment]
@evverx

**Comment by ddstreet** [comment]
This is from the log output of a test failing like this:

$ grep -E '(bus-api-system|run-u7)' upstream-stdout
...
run-u7.service: Installed new job run-u7.service/start as 322
run-u7.service: Enqueued job run-u7.service/start as 322
Bus bus-api-system: changing state RUNNING → CLOSING
Bus bus-api-system: changing state CLOSING → CLOSED
Bus bus-api-system: changing state UNSET → OPENING
Bus bus-api-system: changing state OPENING → AUTHENTICATING
run-u7.service: Failed to set 'memory.min' attribute on '/system.slice/run-u7.service' to '0': No such file or directory
run-u7.service: Failed to set 'memory.swap.max' attribute on '/system.slice/run-u7.service' to 'max': No such file or directory
run-u7.service: Failed to set 'memory.oom.group' attribute on '/system.slice/run-u7.service' to '0': No such file or directory
run-u7.service: Passing 0 fds to service
run-u7.service: About to execute: /usr/bin/test -f /var/lib/zzz/test
run-u7.service: Forked /usr/bin/test as 274
run-u7.service: Changed dead -> runningFound pre-existing private StateDirectory= directory /var/lib/private/zzz, migrating to /var/lib/zzz.
run-u7.service: Job 322 run-u7.service/start finished, result=done
run-u7.service: Executing: /usr/bin/test -f /var/lib/zzz/testsystemd-journald.service: Got notification message from PID 210 (WATCHDOG=1)
run-u7.service: Child 274 belongs to run-u7.service.
run-u7.service: Main process exited, code=exited, status=0/SUCCESS
run-u7.service: Succeeded.
run-u7.service: Changed running -> dead
run-u7.service: Consumed 59ms CPU time.
run-u7.service: Collecting.
Bus bus-api-system: changing state AUTHENTICATING → HELLO
Bus bus-api-system: changing state HELLO → RUNNING

**Comment by ddstreet** [comment]
opened debian MR to blacklist this test, for now:
https://salsa.debian.org/systemd-team/systemd/merge_requests/36

**Comment by evverx** [comment]
Thank you. I think TEST-34 can be skipped in QEMU only because as far as I know it has never failed in nspawn containers. On the other hand, this test is run in VMs and nspawn containers on CentOS and Arch so it should be OK for the time being.

In the meantime, it looks like @mrc0mmand saved TEST-15 and TEST-22 in https://github.com/systemd/systemd/pull/12992 so I hope it won't be necessary to turn them off.

**Comment by ddstreet** [comment]
@martinpitt @mbiebl can either of you review the debian MR if you have a chance?  I am looking into why the tests are flaky, and will try to fix them, but seems blacklisting them for now is best since they are currently flaky.
https://salsa.debian.org/systemd-team/systemd/merge_requests/36

**Comment by martinpitt** [comment]
@ddstreet: Done, thanks. Is this meant to be temporary? The blacklist is growing.. I don't think these tests run anywhere else in CI, and broken tests are not helping anyone.

**Comment by evverx** [comment]
@martinpitt all those tests except for TEST-16-EXTEND-TIMEOUT are run on CentOS and Arch. They fail on Ubuntu CI only.

**Comment by mbiebl** [comment]
> @martinpitt all those tests except for TEST-16-EXTEND-TIMEOUT are run on CentOS and Arch. They fail on Ubuntu CI only.

under qemu and with the same coverage of architectures?

**Comment by evverx** [comment]
They are run in QEMU both on bare-metal machines (CentOS) and in VMs launched by vagrant (Arch). Unfortunately, the only architecture available there is amd64 as far as I know but I hope @mrc0mmand will get a pool of at least arm64 machines eventually.

**Comment by ddstreet** [comment]
> @ddstreet: Done, thanks. Is this meant to be temporary? The blacklist is growing.. I don't think these tests run anywhere else in CI, and broken tests are not helping anyone.

yes, definitely temporary...i would like to get to the point where all of them can be removed from the blacklist.  Towards that goal, I have a branch that I keep up to date with debian/experimental code under debian/, and up to date with systemd upstream for the rest of the code:
https://code.launchpad.net/~ddstreet/ubuntu/+source/systemd/+git/systemd/+ref/systemd-upstream

I build it in:
https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream

and test the built packages both at autopkgtest.ubuntu.com, as well as in the private Canonical openstack lab (that also has non-intel arch systems).

I can't promise any timeline for fixing the flaky tests and removing them from the blacklist, but I am working on it.

**Comment by evverx** [comment]
Speaking of flakiness, since Debian Buster was released the tests have been failing on Semaphore with
```sh
dpkg-buildpackage: info: binary-only upload (no source included)
storage              SKIP Test requires machine-level isolation but testbed does not provide that
upstream             SKIP Test requires machine-level isolation but testbed does not provide that
autopkgtest [15:00:32]: test timedated: preparing testbed
autopkgtest [15:00:41]: @@@@@@@@@@@@@@@@@@@@ test bed setup
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
blame: ../systemd_242-1201-g7518c1d93e-0.dsc
badpkg: testbed setup commands failed with status 100
autopkgtest [15:00:42]: ERROR: erroneous package: testbed setup commands failed with status 100
+ '[' 12 -eq 2 ']'
```
I think I found the code dealing with retries on Ubuntu CI at https://git.launchpad.net/autopkgtest-cloud/tree/worker/worker#n490 so in principle it can be borrowed from there but I'm wondering where the Debian counterpart is.

**Comment by poettering** [comment]
Hmm, is there any chance to get the dbus logs from cases where this happens?

or even better, the dbus logs in debug mode?

is this dbus-daemon? or dbus-broker?

**Comment by ddstreet** [comment]
I ran test-34 in a loop until failure, on a i386 instance testbed, similar to the ones used for Ubuntu CI, and here is the console output:
https://pastebin.ubuntu.com/p/CpqJ3kjyJ6/

That is with this added to the test-34 test.sh setup:
KERNEL_APPEND="systemd.log_time=1 systemd.log_level=debug"
(log_time is a patch i have to prefix console output with a timestamp)

> is this dbus-daemon? or dbus-broker?

in the TEST-34 qemu environment, dbus-daemon appears to be running:

-bash-4.4# ps ax|grep dbus
  332 ?        Ss     0:01 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  438 ttyS0    S+     0:00 grep dbus

**Comment by ddstreet** [comment]
> Speaking of flakiness, since Debian Buster was released the tests have been failing on Semaphore with

@evverx did you open a new bug to track that?

**Comment by evverx** [comment]
> @evverx did you open a new bug to track that?

I "fixed" that in https://github.com/systemd/systemd/pull/13030.

**Comment by mrc0mmand** [comment]
I'll close this one since I haven't seen TEST-34 fail anywhere for a long time, including Ubuntu CI. If there still is an issue, please feel free to reopen this.
