### ISSUE TITLE
config files in /etc/environment.d/*.conf don't work

### ISSUE THREAD

**Issue by guoyunhe** [systemd/systemd#12938]
**systemd version the issue has been seen with**
```
systemd 242 (+suse.77.geaa7b8b148)
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
Operating System: openSUSE Tumbleweed 20190701
KDE Plasma Version: 5.16.2
KDE Frameworks Version: 5.59.0
Qt Version: 5.13.0
Kernel Version: 5.1.10-1-default
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 31.2 GiB
```

**Expected behaviour you didn't see**
 config files in `/etc/environment.d/*.conf` are not loaded.

**Unexpected behaviour you saw**
 should be loaded.

**Steps to reproduce the problem**
1. Create a file `/etc/environment.d/50-fcitx.conf`
2. Edit the file and add:
   ```
   INPUT_METHOD=fcitx
   ```
3. Reboot.
4. Run `echo $INPUT_METHOD`.

**Comment by dschepler** [comment]
The documentation seems to indicate to me that `/etc/environment.d` is only meant to take effect on system and user services, not in user sessions.  My guess would be that if you run something like
```bash
tr '\0' '\n' < /proc/$(pidof sshd)/environ
```
that should show the setting.

**Comment by poettering** [comment]
@dschepler is right. systemd-environment-d-generator gets run by systemd --user, and thus set environment variables for the systemd per-user service manager and their child processes only. Login shells (such as those started via getty on the console or ssh) are not children of systemd and hence the generators have no effect on them whatsoever.

For login sessions use pam_env or some .profile script or similar to set env vars... Sorry.

**Comment by guoyunhe** [comment]
Thanks for explanation. Then another question: how should I set environment variables for KDE Wayland? It is shipped from `fcitx` package so cannot be inserted into /etc/environment which owned by `pam` package.

**Comment by dschepler** [comment]
Many distributions provide `/etc/profile.d` as a drop-in directory for shell fragments to be executed at login time.

(Though come to think of it, it would be nice if they could provide the usual `/usr/lib/profile.d` / `/run/profile.d` / `/etc/profile.d` split.  I don't know of any that currently do.)

**Comment by guoyunhe** [comment]
@dschepler the problem is that GNOME/KDE Wayland doesn't read these `profile.d` directories.

**Comment by Gigadoc2** [comment]
@guoyunhe As a very belated answer: GDM imports the environment variables from the systemd user manager right before starting the session. And for a pure Wayland session (which, ironically, GNOME itself is not, it wraps itself in a login shell), that is currently the only way (apart from pam_env) to load environment variables.
If the display manager / login you use (SDDM?) does not do that, _and_ does not run your wayland session through a shell, there is nothing you can do at the moment. That is, anything you start through the systemd user manager would get your variables, but at the moment only GNOME starts (part of) its processes under the user manager.
systemd has no way of injecting environment variables into processes it didn't launch, and the user session (launched by GDM/SDDM/etc, cleared of environment variables) is such a process. That is why GDM voluntarily imports those variables into the process which finally spawns the user session.
If neither KDE nor SDDM are involving a login shell for your session, nor loading environment variables from somewhere else, I am afraid that the problem resides with KDE/SDDM, even without systemd.

As a side note, if you want to ship an environment file with a package, please put it in /usr/lib/environment.d/ (or the equivalent), and not /etc :)

**Comment by guoyunhe** [comment]
@Gigadoc2 thanks for the explanation! So I need to look for the implementation details in GDM and ask SDDM to do the same thing, right?

**Comment by Gigadoc2** [comment]
@guoyunhe I have searched around a bit to see what the situation with KDE Wayland and environment variables is, and the only thing I've found is [this forum thread](https://forum.manjaro.org/t/kde-is-not-running-users-environment-d/80632) where someone suspects that SDDM is not doing this on purpose, as to not grow a dependency on systemd.

I don't know if that is true, but if it is, I wonder if they have a different mechanism for setting environment variables? From the forum thread above, it seems that a _user_ can run scripts at the startup of a KDE session and variables from there will propagate to the rest of KDE, but I have no idea whether that is also possible from system locations (for packages such as yours).

If you want to look at what GDM is doing, I can give you some pointers. The relevant file is [gdm-wayland-session.c](https://gitlab.gnome.org/GNOME/gdm/-/blob/master/daemon/gdm-wayland-session.c), which is a small program that gets started by GDM as the first program to run in the users session, with the users uid (i.e. the thing that gets started with dropped privileges). There is the function `import_environment`, which gets the variables from systemd, and then later the function `spawn_session` will make use of those variables and export them to the new process (which is the session chosen by the user).

I have gotten a bit curious about the scope of the systemd user environment generators, and am wondering where they are used and where they were intended to be used. In that sense I am now also very curious to know what KDE is doing with environment variables for wayland sessions...

**Comment by guoyunhe** [comment]
Yes, I can understand that SDDM doesn't want to depend on Wayland. Maybe freedesktop.org should provide a standard for this and DMs or DEs can implement.

**Comment by adrelanos** [comment]
There's a feature request against PAM for `/etc/pam_environment.d`:

* https://github.com/linux-pam/linux-pam/issues/122

**Comment by 4lex11s** [comment]
For reference, this exact architectural limitation and the proposed transition to spawning terminal sessions as transient systemd user services is currently being discussed upstream in the KDE community here: https://bugs.kde.org/show_bug.cgi?id=485075
