### ISSUE TITLE
mount to nfs by the command "systemd-mount" but got  error

### ISSUE THREAD

**Issue by yanghaichao12** [systemd/systemd#12948]
**What happened:**
i want to mount to nfs by the command "systemd-mount" but got below error:
```shell
root@zxin10-virtual-machine:~# systemd-mount  -t nfs /10.47.184.131:/home/zxin10/test3 /home/zxin10/test
Failed to canonicalize path: No such file or directory
```
**What you expected to happen:**
no errors when mount nfs
**How to reproduce it (as minimally and precisely as possible):**
run "systemd-mount -t nfs .....
**Environment:**

OS (e.g: cat /etc/os-release):Ubuntu 17.10
Kernel (e.g. uname -a): 4.13.0-46-generic
Others:

**Comment by yuwata** [comment]
I think this issue is already fixed by 08185cff19efcb1d7d9fb7b546e7f516ab6dae91.
Please try the commit, and if it works please contact to downstream to backport the commit.

**Comment by yanghaichao12** [comment]
@yuwata thanks for the reply. i'll try it later.

**Comment by yanghaichao12** [comment]
/
