### ISSUE TITLE
sysusers: Please document interface portability/stability

### ISSUE THREAD

**Issue by smcv** [systemd/systemd#12952]
**Is your feature request related to a problem? Please describe.**
I would like to know whether I can safely recommend `sysusers.d` as a common interface, in environments where systemd isn't always used.

**Describe the solution you'd like**
Add a row to the table in https://www.freedesktop.org/wiki/Software/systemd/InterfacePortabilityAndStabilityChart/ for `sysusers.d`. I'm guessing its status would be the same as for `tmpfiles.d`?

**Describe alternatives you've considered**
Continuing to create system users in a distro-specific way.

**Comment by smcv** [comment]
I am not aware of any reimplementations of systemd-sysusers, although I'm tempted to write one for Debian so that we can guarantee this interface even on the minority of systems that boot with sysvinit or something.

**Comment by poettering** [comment]
why would you rewrite that? it's lgpl2. what are you trying to do? you have a project where lgpl2 is not a permitted license?

(but yeah, the iface should be stable, it's used all over the place already)

**Comment by smcv** [comment]
Partly because Debian is portable to more kernels than systemd is, and partly you're making the mistake of assuming the people who insist on avoiding the systemd codebase on Linux do so for some rational reason...

I'd like to be able to rely on these interfaces even when depending on bits of systemd is not politically or technically possible.

**Comment by keszybz** [comment]
systemd-sysusers doesn't really depend or have much to do with the rest of systemd. It should be easy enough to just compile and install just that one executable. It's possible that some minor adjustments to the code or the build system would be needed, but I'd rather see that than a complete rewrite.

**Comment by keszybz** [comment]
https://cgit.freedesktop.org/wiki/www/commit/Software/systemd/InterfacePortabilityAndStabilityChart.mdwn?id=02c801aea2391580dda559407a73738a8353da49

**Comment by smcv** [comment]
Thanks! I'll see what I can do about convincing others in Debian not to reinvent this particular wheel...
