### ISSUE TITLE
[networkd] Adding VLAN 4090 to VLAN-aware bridge is not working

### ISSUE THREAD

**Issue by rubensfig** [systemd/systemd#12958]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Fedora 30

**Expected behaviour you didn't see**
 > Expected to see the VLAN 4090 applied to the created bridge, able to see via `bridge vlan` command. 

**Unexpected behaviour you saw**
 > The VLAN wasn't applied to bridge, and systemd-networkd output:
```
dummy0: Could not append VLANs: Invalid argument
dummy0: Failed to assign VLANs to bridge port: Invalid argument                                                                                                            
dummy0: Could not set bridge vlan: Invalid argument
[...]
swbridge: Could not append VLANs: Invalid argument
swbridge: Failed to assign VLANs to bridge port: Invalid argument
swbridge: Could not set bridge vlan: Invalid argument
```

**Steps to reproduce the problem**
ip link add type dummy
Networkd files:

20-dummy0.network
```
[Match]
Name=dummy0
    
[Link]
RequiredForOnline=no
    
[Network]
Bridge=swbridge

[BridgeVLAN]
VLAN=4090
```
30-swbridge.netdev
``` 
[NetDev]
Name=swbridge
Kind=bridge
    
[Bridge]
VLANFiltering=1
ForwardDelaySec=2
DefaultPVID=none
STP=true
```
30-swbridge.network
```
[Match]
Name=swbridge

[Link]
RequiredForOnline=no

[BridgeVLAN]
VLAN=4090
```

**Comment by rubensfig** [comment]
Thanks for the reply.

More findings: 

* Apparently the range for the VLANs that are broken is between 4063-4094
* Adding the VLAN range 4062-4094 works as expected

**Comment by yuwata** [comment]
cc @ssahani

**Comment by yuwata** [comment]
Ah, apparently I found the root of the issue. Will post a fix.
