### ISSUE TITLE
/usr/share/factory/etc/pam.d/system-auth accepts any password on all accounts

### ISSUE THREAD

**Issue by dschepler** [systemd/systemd#12950]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Custom build

**Expected behaviour you didn't see**
 > Using factory version of `/etc/pam.d/system-auth` should behave sanely with services using PAM configurations with `include system-auth`

**Unexpected behaviour you saw**
 > Services accept any password for any valid account

**Steps to reproduce the problem**
Take system offline and backup correct `/etc/pam.d/system-auth` file, of course.
Copy `/usr/share/factory/etc/pam.d/system-auth` to `/etc/pam.d/system-auth`.
Switch to VT and login with existing account, typing in any password.

If I understand the contents of `/usr/lib/tmpfiles.d/etc.conf` correctly, that means that systemd will do the copying itself if somehow `/etc/pam.d/system-auth` is lost but the factory version isn't.  Which seems dangerous - unless I'm missing something, which I'm guessing I probably am.

In any case, if the lack of any lines such as `auth requisite pam_deny.so` is intentional, then it would be good to put a prominent warning into the factory file indicating that it is definitely not intended as a prototype for an actual `/etc/pam.d/system-auth` file.

**Comment by poettering** [comment]
Hmm, yeah, I guess this isn't tested very much. We probably should either remove this altogether or fix it. Fixing it is hard though given the differences in the distros.

**Comment by poettering** [comment]
Hmm, so I tried to reproduce the issue here on Fedora, but I can't. In this version at least getty/login don't allow logins without valid password, even without pam_deny.so in place.

**Comment by poettering** [comment]
(btw, the factory stuff is so that booting with "systemd.volatile=yes" or with systemd-nspawn's --volatile=yes just works, i.e. you can boot up with empty /etc, and everything is cool)

**Comment by poettering** [comment]
I posted #13038 which tightens the rules, but as mentioned, I am not able to reproduce the issue. PTAL

**Comment by keszybz** [comment]
Yeah, can't reproduce this either, but I'm also testing Fedora, so this doesn't mean much.
