### ISSUE TITLE
System hangs on shutdown

### ISSUE THREAD

**Issue by NoMore201** [systemd/systemd#12967]
**systemd version the issue has been seen with**
> 242.32 

**Used distribution**
 > Archlinux (Kernel 5.1.15, systemd 242.32-2)

**Expected behaviour you didn't see**
 > A normal shutdown process

**Unexpected behaviour you saw**
 > System shutdown hangs forever

**Steps to reproduce the problem**

I tested my system with Ubuntu 18.04.2 and it works without any problems (as I am writing this
ubuntu ships systemd version 237). On Archlinux, when I power off the system, it hangs undefinitely in a random stage of the shutdown process.

I followed [these steps](https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1) to see if the problem is related to systemd, with the following results:

- `reboot -f` works fine
- with `poweroff -f` really strange things happen. Last time I tried this command, motherboard fans turned off, LEDs remained on (motherboard, VGA and usb devices) and video output kept running (I could still see my Gnome session with the terminal open, althought it was freezed)

I'm attaching photo of the shutdown log and the last journalctl entries of the last boot. I don't know if this is directly related to systemd, but I will be grateful if you can point me to the right direction. Please let me know if you need other informations.

![IMG_20190704_234244](https://user-images.githubusercontent.com/3220188/60740527-91489380-9f55-11e9-8d18-45135a023570.jpg)
[journalctl.log](https://github.com/systemd/systemd/files/3363743/journalctl.log)

**Comment by NoMore201** [comment]
Actually kind of solved by disabling lvmetad as described [here](https://www.reddit.com/r/archlinux/comments/b5vqkn/my_system_sporadically_hangs_at_shutdown_or_reboot/). Still the shutdown process takes too much time, between 1-2 minute, but I guess that's a different issue.

**Comment by NoMore201** [comment]
Unfortunately problem isn't solved. For some reasons after disabling lvmetad it worked once, but issue is still there.

I tried to mask every lvm socket/service file,  machine can now reach target poweroff (even if it takes too much time compared to Ubuntu 18.04) but actually it won't poweroff entirely: fans turn off, while motherboard's LEDs and video output remain on.

Also, sometimes `/home` and `/tmp` fails to unmount, like showed in first comment.

I attached debug log with systemd debug flags enabled.
[journalctl-log.txt](https://github.com/systemd/systemd/files/3365406/journalctl-log.txt)
[shutdown-log-dmesg.txt](https://github.com/systemd/systemd/files/3365407/shutdown-log-dmesg.txt)

**Comment by poettering** [comment]
So, I presume you made the shutdown-log-dmesg.txt file from a shutdown hook in /usr/lib/systemd/system-shutdown/ ?

If you managed to shutdown that far that that directory's hooks are run then you are very close to the end. Realistically there are only three things that might hang shutdown then:

 1. some other shutdown hook script hangs. I see you have one from LVM there in the same directory, consider turning that off, plus any others

 2. optionally, systemd can transition back to the initrd during late shutdown, so that the root fs is unmounted too. Modern initrds such as dracut do that. Not sure if Ubuntu does. Inquire the ubuntu folks about that. If so, systemd is not in control anymore.

 3. it might be a kernel/firmware problem, i.e. that the reboot() system call just doesn't work correctly. For that, try to run "systemctl reboot -ff" (which will just call the syscall, doesn't shut anything down, hence make sure to sync/save everything first). If that hangs it's a kernel/firmware issue.

Either way, I doubt systemd has anything to do with this. The shtdown hooks are literally the last thing that runs before reboot() is invoked (or if configured we pass control back to the initrd, see above), and if things hang there, then it's unlikely systemd is doing anything.

Do things hang forever? or do they timeout eventually?

**Comment by poettering** [comment]
if you boot with "debug" and then shutdown, what's the lst thing you see on screen (assuming you turned off all boot splashes and stuff)

**Comment by NoMore201** [comment]
> So, I presume you made the shutdown-log-dmesg.txt file from a shutdown hook in /usr/lib/systemd/system-shutdown/ ?

Yes

> 3. it might be a kernel/firmware problem, i.e. that the reboot() system call just doesn't work correctly. For that, try to run "systemctl reboot -ff" (which will just call the syscall, doesn't shut anything down, hence make sure to sync/save everything first). If that hangs it's a kernel/firmware issue.

I tried the command above and it works. The system reboots correctly.

> Do things hang forever? or do they timeout eventually?

Actually while testing I found an interesting behaviour. As I mentioned in the first post, sometimes I can read on screen `failed unmounting Temporary Directory /tmp` and `failed unmounting /home` (like you can see in the image in the first comment), while other times all the logs are ok. Then I noticed that

- if tmp and home unmount correctly the system is going to shutdown eventually, even if it requires 3-4 minutes
- if I see those errors, the system will hang forever

> if you boot with "debug" on the kernel cmdline and then shutdown, what's the lst thing you see on screen (assuming you turned off all boot splashes and stuff)

The last thing I can see is always `Reached target Power-Off`, in both cases described above

**Comment by poettering** [comment]
please provide debug logs from a shutdown cycle when this hangs.

where do logs in the journal end when you shutdown like this? i.e. when you look at them on next boot, what do you see?

**Comment by NoMore201** [comment]
This is the journalctl entry for last boot. Before powering off the system, I logged out from gnome, switched tty and manually stopped GDM, to check if there was something preventing the correct unmounting of /tmp and /home.

[journalctl-23-07.log](https://github.com/systemd/systemd/files/3427856/journalctl-23-07.log)

At line 3379, during the poweroff there is an interesting kernel message about Xorg being blocked for more than 122 seconds, followed by a stack trace. This is strange since before typing `systemctl poweroff` I manually stopped GDM with `systemctl stop gdm.service` so there shouldn't be any Xorg process around.

Some additional notes about the system:

- I'm using the xorg backend for gdm/gnome since I'm using the nvidia driver (using an Nvidia 2070 RTX)
- Some days ago was updated systemd to 242.84-1

Could this be the issue?

**Comment by NoMore201** [comment]
After some tests I found the problem to be the linux kernel with NVIDIA drivers, keeping the Xorg process alive which in turn keeps the GDM process alive, causing the hang described above. To be more precise, it happens only with newer versions of the kernel (5.1.* and newer). Downgrading to the LTS kernel  solves the problem.

Just for reference, there's a thread on the NVIDIA devtalk forum [at this URL](https://devtalk.nvidia.com/default/topic/1057524/linux/system-seems-locked-while-rebooting-with-linux-5-2-1-and-nvidia-drivers-430-34-or-430-26/)
