### ISSUE TITLE
journalctl: handle inotify exhaustion nicer

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#1296]
We currently fail journalctl -f completely if we cannot get inotify to work because all inotify wds are gone. We should handle this more gracefully, since journalctl is the tool after all to check for errors like this one.

One option might be to log about the issue, and then turn off `-f` mode, thus reverting to `-n` mode.

https://kdecherf.com/blog/2015/09/12/systemd-and-the-fd-exhaustion/

**Comment by pik** [comment]
Currently journalctl is completely silent on `inotify_add_watch` failure (it's not even logged with `SYSTEMD_LOG_LEVEL=debug` see attached logs for an example) which seems very unfriendly. Comparatively tail -f will log inotify failure and switch to polling mode e.g. 

```
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
```

[journalctl-2.debug.txt](https://github.com/systemd/systemd/files/534593/journalctl-2.debug.txt)
[journalctl-2.strace.txt](https://github.com/systemd/systemd/files/534594/journalctl-2.strace.txt)

edit: 
@poettering 

I am re-reading your comment and I'm not sure this is the same bug. 

> We currently fail journalctl -f completely if we cannot get inotify 

In my testing `journalctl --follow` explicitly does not fail, but stays in follow mode without receiving any new input -- this is probably worse than an immediate failure.

**Comment by pik** [comment]
Bumping is not nice -- but: this is *extremely* user unfriendly! Does anyone plan to do something about this?

**Comment by poettering** [comment]
#9341 was merged. Closing.
