### ISSUE TITLE
hwdb: add axis range corrections for the Lenovo ThinkPad Yoga 11e

### ISSUE THREAD

**Issue by serbra** [systemd/systemd#12976]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by serbra** [comment]
new rules:

# Lenovo Yoga 11e
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnLENOVO:*pvrThinkPadYoga11e*
 EVDEV_ABS_00=1364:5677:72
 EVDEV_ABS_01=1123:4642:35
 EVDEV_ABS_35=1364:5677:72
 EVDEV_ABS_36=1123:4642:35

--
the output of 'udevadm info /dev/input/eventXX':

P: /devices/platform/i8042/serio1/input/input6/event10
N: input/event10
L: 0
S: input/by-path/platform-i8042-serio-1-event-mouse
E: DEVPATH=/devices/platform/i8042/serio1/input/input6/event10
E: DEVNAME=/dev/input/event10
E: MAJOR=13
E: MINOR=74
E: SUBSYSTEM=input
E: USEC_INITIALIZED=10328727
E: EVDEV_ABS_00=1364:5677:72
E: EVDEV_ABS_01=1123:4642:35
E: EVDEV_ABS_35=1364:5677:72
E: EVDEV_ABS_36=1123:4642:35
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_WIDTH_MM=96
E: ID_INPUT_HEIGHT_MM=55
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-1
E: ID_PATH_TAG=platform-i8042-serio-1
E: ID_INPUT_TOUCHPAD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/2/7:isa0060/serio1
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-1-event-mouse

--

**Comment by poettering** [comment]
Please submit this as proper github PR, so that we can merge it an attribute it correctly to you. Thank you!
