### ISSUE TITLE
Better error description for "Failed to set up mount namespacing: No such file or directory" 

### ISSUE THREAD

**Issue by kokizzu** [systemd/systemd#12974]
**Is your feature request related to a problem? Please describe.**
Always frustrated when writing service file but it didn't show which file/directory that does not exists.

example:
```
InaccessiblePaths=/some/typo /bunch/other/directory
ReadWriteDirectories=/some/non/existent/directory /bunch/other/directory
ReadOnlyPaths=/some/other/typo /bunch/other/paths
ProtectHome=true
ProtectSystem=full
```

**Describe the solution you'd like**
Show which rule that causes the error (at least the path/directory), instead of just `Failed to set up mount namespacing: No such file or directory`

**Describe alternatives you've considered**
I've tried to set `Environment=SYSTEMD_LOG_LEVEL=debug` on service file or `LogLevel=info` on `/etc/systemd/system.conf`  but it doesn't help much, the same unhelpful error "no such file or directory" without mentioning which directory/path that causes the error

**Comment by yuwata** [comment]
Please try `systemd-analyze log-level debug`.

**Comment by poettering** [comment]
This has been reworked in 7cc5ef5f1811c539ae7f20255c2a093f413cc64f already (which is going to be part of the next release). Let's consider this closed, hence.
