### ISSUE TITLE
systemd-networkd does not support [Route] Type=local

### ISSUE THREAD

**Issue by SpComb** [systemd/systemd#12975]
**Is your feature request related to a problem? Please describe.**
When configuring e.g. IPVS backend servers, it is useful to have incoming packets to a Virtual IP be handled as local addresses without actually configuring the address on any interfaces. This is possible using `ip route add local ... dev ...`. 

**Describe the solution you'd like**
The possibility to configure such VIP routes using systemd-networkd `[Route] Type=local`.

```
[Route]
Destination=192.0.2.1
Type=local
```

This is currently not possible:

```
Jul 06 21:29:28 foo-test systemd-networkd[1557]: /etc/systemd/network/eth-test.network:29: Could not parse route type "local", ignoring assignment: Success
```

**Describe alternatives you've considered**

Using a custom systemd service with  `ExecStart=/bin/ip route add local 192.0.2.1 dev eth-test`.

**Comment by yuwata** [comment]
Please try #12977.
