### ISSUE TITLE
Possible performance issues caused by compound literals in macros with gcc 9.1.x

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#12997]
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > Fedora Rawhide & Arch Linux

As mentioned in several other PRs/issues and on Telegram, there's a significant performance penalty when the current master is compiled with ASan under gcc 9.1.x along with the `ASAN_OPTIONS` env variable set to `detect_stack_use_after_return=1`. After an investigation by gcc guys in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c15 the issue stems from a potential abuse of compound literals in certain macros. (Hopefully, I transcribed it correctly, as that stuff a little bit out of my field of knowledge).

This issue should function as a tracker to reference from other threads and to keep the discussion at one place.

**Comment by jakubjelinek** [comment]
Well, that combined with the testing with -O0 when you tell the compiler not to optimize the code.

**Comment by mrc0mmand** [comment]
> Well, that combined with the testing with -O0 when you tell the compiler not to optimize the code.

I guess the surprising part here is that this issue appeared with the gcc 9.1.x release, as we've been (at least in CentOS CI) using `-O0` since... ever. I'm not arguing that it's correct, rather than pointing out the fact that it worked until now :-)

**Comment by poettering** [comment]
hmm a quick response to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c15 btw: we don't do `do {} while()` on that macro, since assert_cc() should work outside of any function, i.e. on top-level scope. (don't have a bugzilla account on gnu bugzilla, i hope it's ok if I reply here)

**Comment by poettering** [comment]
@jakubjelinek not sure I grok your criticism of our assert_cc() macro though. I mean with the current code we define an unused structre type, we don't actually instantiate it at all, i.e. defining a type that is not used should not affect msan/asan at all, should it?

**Comment by poettering** [comment]
(also note that assert_cc() is actually just an alias to static_assert() these days, our own implementation is used only on retro-compilers, so this really shouldn't have any effect on msan/asan whatsoever)

**Comment by jakubjelinek** [comment]
> hmm a quick response to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c15 btw: we don't do `do {} while()` on that macro, since assert_cc() should work outside of any function, i.e. on top-level scope. (don't have a bugzilla account on gnu bugzilla, i hope it's ok if I reply here)
You already end assert_cc with ;, so the do while (0) around isn't needed.
Anyway, seems I've misread the assert_cc, that is indeed just a type definition, not compound literal (though, extern char ... [cond ? -1 : 0]; would have been simpler).
I bet the problem is that IN_SET compound literal, where with -O0 you end up adding a frame due to that compound literal in a function that is called so often that the asan instrumentation of the frames kills the performance. And in  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c16 you have one possible alternative to that IN_SET compound literal.

**Comment by keszybz** [comment]
I implemented some of the suggested changes, I'll submit a PR. The remaining ones:
- `extern char ... [cond ? -1 : 0]` → this doesn't work because when assert_cc is used in function scope, we get warnings about unused variables
```
warning: unused variable ‘_assert_cc_16’ [-Wunused-variable]
```
Let's just keep the existing approach with struct.

-  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101#c16 you have one possible alternative to that IN_SET compound literal

I did the following:
```diff
-                assert_cc((sizeof((long double[]){__VA_ARGS__})/sizeof(long double)) <= 20); \
+                long double __assert_in_set[] __attribute__((__unused__)) = { __VA_ARGS__ }; \
+                assert_cc(sizeof(__assert_in_set) / sizeof(long double) <= 20); \
```
This seems to result in those variables being actually defined, and text sizes increases:
```
(old) $ size build/systemd
   text    data     bss     dec     hex filename
1674952  267068    1208 1943228  1da6bc build/systemd

(in_set rewrite) $ size build/systemd
   text    data     bss     dec     hex filename
1686444  267068    1208 1954720  1dd3a0 build/systemd
```

I think @mrc0mmand's approach in https://github.com/systemd/systemd-centos-ci/pull/144 is better. Let's just use `-O1` for sanitizers.

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/pull/13093

**Comment by keszybz** [comment]
> You can add `__attribute__((__unused__))` to the declarations.

Yeah, maybe, but then we get the variables again... This is not worth the trouble, since it's only the fallback path for old compilers.

> I meant `static const long double __assert_in_set[]` instead.

Oh thanks, this works. 36s → 3s. I pushed another commit in #13093.

**Comment by evverx** [comment]
It appears it didn't help much: https://github.com/systemd/systemd/pull/15886#issuecomment-632689604.

@mrc0mmand could you reopen https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101?

**Comment by mrc0mmand** [comment]
> It appears it didn't help much: [#15886 (comment)](https://github.com/systemd/systemd/pull/15886#issuecomment-632689604).
> 
> @mrc0mmand could you reopen https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91101?

Will do!

**Comment by evverx** [comment]
On the other hand, I've just noticed that `fuzz-unit-file` wasn't mentioned so it's probably a new issue.

**Comment by mrc0mmand** [comment]
> On the other hand, I've just noticed that `fuzz-unit-file` wasn't mentioned so it's probably a new issue.

Yeah, I'm filing a new one, but with a reference to the old/already closed one, as this is in a different codepath (or at least seems so).

**Comment by evverx** [comment]
While you're at it you could also open an issue about the UBSan issue caught by clang and missed by gcc: https://github.com/systemd/systemd/pull/15865#issuecomment-631373847 :-)

**Comment by mrc0mmand** [comment]
> While you're at it you could also open an issue about the UBSan issue caught by clang and missed by gcc: [#15865 (comment)](https://github.com/systemd/systemd/pull/15865#issuecomment-631373847) :-)

I'll try with the latest (or close to the latest) gcc and if it still fails I'll make another report :-)


> Anyway, in the meantime, I guess we can just skip those tests when systemd is built with gcc and keep using clang.

Definitely, will do that on the CentOS CI side as well.
