### ISSUE TITLE
Improve documentation for oneshot services

### ISSUE THREAD

**Issue by sjvudp** [systemd/systemd#13000]
**systemd version the issue has been seen with**
> 228

**Used distribution**
 > SLES12 SP3

**Expected behaviour you didn't see**
 > Explanation how the status of the service is being set

**Unexpected behaviour you saw**
 > Oneshot service isn't displayed as "started" after being started successfully, unless `RemainAfterExit=true` is set also.

**Steps to reproduce the problem**

1. Configure a oneshot service

1. Start the oneshot service

1. Run `systemctl status` for the service

**Comment by poettering** [comment]
Fix waiting in #13036
