### ISSUE TITLE
networkd: Allow tunnel without local and remote endpoint

### ISSUE THREAD

**Issue by 1848** [systemd/systemd#13014]
Found #12922 which is already fixed but I think the problem is not completely solved because there is still a need to specify at least one endpoint.
But it is possible to create tunnels without endpoints (e.g. using iproute2).

NetDev files I used for testing:

```
[NetDev]
Name = gre123  
Kind = gre
```

```
[NetDev]
Name = gre123
Kind = gre

[Tunnel]
Local = any
Remote = any
```

This results in 

> gre123: vti/ipip/sit/gre tunnel without a local/remote IPv4 address configured in /etc/systemd/network/gre123.netdev.

`ip link add gre456 type gre key 456` works fine:

> 16: gre456@NONE: <NOARP> mtu 1472 qdisc noop state DOWN mode DEFAULT group default qlen 1000
>     link/gre 0.0.0.0 brd 0.0.0.0 promiscuity 0 minmtu 0 maxmtu 0 
>     gre remote any local any ttl inherit ikey 0.0.1.200 okey 0.0.1.200 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535

Same with ip6gre or gretap (I assume, did not test).

**systemd version the issue has been seen with**
current master (242.1218)

**Used distribution**
 Arch Linux

**Comment by yuwata** [comment]
Please test the commit above.
(I do not know why now I cannot create PR...)
