### ISSUE TITLE
Setting keyboard layout via localectl for wayland

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#13029]
**Is your feature request related to a problem? Please describe.**
First of all I am not a window manager expert, so please correct me if I am wrong.
At the moment `localectl` is able to set the X11 keymap. This works as expected, is convenient and useful. I like it a lot. The problem is that there is no wayland support. It would be nice to be able to set the keymap for wayland as well. 

Disclaimer: I don't know if this is even possible. I think I've read that the window manager needs to set the keymap. I use `sway` and sway seems to read these environment variables (example below):
```
export XKB_DEFAULT_LAYOUT=de,us
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
```

So the questions are:

1. Do we use this environment variables? If yes, are these variables a standard and the current approach for more than one window manager?
2. Is there another way to set the keyboard layout for wayland?
3. Should systemd care for this at all? (We care for X11, so I think systemd should care about wayland as well)

**Describe the solution you'd like**
Implementing support for wayland in localectl either by creating a new standard for setting keymaps in wayland, or by using env variables that are already in use, or by another unknown way.

**Describe alternatives you've considered**
Setting the keymaps directly in the windowmanager via windowmanager internal commands/methods.

**Comment by poettering** [comment]
Well, wayland is a protocol, not a software package. I am pretty sure that GNOME (as one major wayland implementation) nowadays read /etc/vconsole.conf directly to make this work, and I think that's the right approach. Please contact your wayland implementation, asking them to do the same (or alternatively read the dbus props off localed)

**Comment by poettering** [comment]
Closing this, since I am very sure the consumers should pull the data from the config file or localed directly, and we shouldn't push it the opposite way in particular as there is no common configuration file for wayland servers even. Hope this makes sense.

**Comment by shibumi** [comment]
@poettering yep, this makes sense for me. I just have one follow-up question.
How would I adapt the following setup to a wayland native desktop environment:
```
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: de
       X11 Model: pc104
     X11 Variant: us
```

It looks like `sway` is reading already from `/etc/vconsole.conf`, but further configuration (like the one above) would need behavior like above. At least I don't know how I would set such a configuration with `/etc/vconsole.conf` only.
