### ISSUE TITLE
asprintf and _cleanup_free_

### ISSUE THREAD

**Issue by setharnold** [systemd/systemd#1304]
Hello, I noticed `efi_get_variable()` uses `_cleanup_free_` on a variable that is initialized with asprintf(3). The asprintf(3) manpage says that on error, "the contents of strp is undefined.", and may pass garbage values to free(3) when asprintf(3) returns an error. The AppArmor team has experienced this before and uses a small wrapper function that sets *strp to NULL on error to avoid exactly this:

```
int _aa_asprintf(char **strp, const char *fmt, ...)
{
    va_list args;
    int rc;

    va_start(args, fmt);
    rc = vasprintf(strp, fmt, args);
    va_end(args);

    if (rc == -1)
        *strp = NULL;

    return rc;
}
```

http://bazaar.launchpad.net/~apparmor-dev/apparmor/master/view/head:/libraries/libapparmor/src/private.c#L157

I only noticed this one instance while reviewing unrelated code; there may be more elsewhere, both the cleanup free and asprintf are useful things.

Thanks

**Comment by poettering** [comment]
That's a misunderstanding I guess. `asprintf()` doesn't clobber the pointer you pass in on failure (check the glibc sources). Not clobbering input parameters on failure is a really a good idea, so `asprintf()` is doing everything right there. In `efi_get_variable()` we pre-initialize the pointer we pass in, and hence are good. On return of the function the param is hence in an undefined state if you so will, in case the it was undefined on input too...

Sure, the man page is a bit misleading there, but the sources of glibc are clear. 

And even if this would break one day, we'd then (and only then) write our own wrapper around it, that guarantees that the parameters are not clobbered on failure. THe snippet you propose however always clobbers, which I think is a bad idea.

Anyway, I see nothing to change here for now. Closing.
