### ISSUE TITLE
Is there an alternative for firmware loading ?

### ISSUE THREAD

**Issue by magicse7en** [systemd/systemd#13040]
From systemd v239, below patches have been dropped.
>   0007-Revert-rules-remove-firmware-loading-rules.patch
>   0008-Revert-udev-remove-userspace-firmware-loading-suppor.patch
>     These two patches are dropped because they are for kernel < 3.7.
>     But the current minimal requirement of kernel to build systemd
>     is as below.
>     REQUIREMENTS:
>         Linux kernel >= 3.13
>         Linux kernel >= 4.2 for unified cgroup hierarchy support
>     So these two patches no long make any sense.
http://lists.openembedded.org/pipermail/openembedded-core/2018-July/152613.html 
Is there an alternative for firmware loading ?

**Comment by poettering** [comment]
Kernel does it on its own nowadays. Please just check the commit messages/PR for info about that.
