### ISSUE TITLE
systemd-cryptsetup-generator ignoring [rd.]luks.options=discard

### ISSUE THREAD

**Issue by liamdennehy** [systemd/systemd#13056]
**systemd version the issue has been seen with**
241

**Used distribution**
[Gentoo](https://bugs.gentoo.org/689360)

**Expected behaviour you didn't see**
After a successful boot with root on luks, ``dmsetup table`` should show luks volumes created with ``allow_discards`` when kernel cmdline contains ``luks.options=discard`` or ``rd.luks.options=discard``

**Unexpected behaviour you saw**
luks volumes are opened without ``allow_discards``

**Steps to reproduce the problem**

1. Using system already configured to discover and configure root-on-luks with systemd-cryptsetup-generator
2. add ``luks.options=discard`` to kernel cmdline
3. reboot

Will attempt to step through dracut via cmdline to provide more detailed steps, but this is not trivial...

**Comment by poettering** [comment]
what's the full kernel command line used?

**Comment by poettering** [comment]
also could you check what the precise contents of the systemd-cryptsetup@.service files generated on your machine are? best would be to break in the initrd, then have a look with "systemctl cat"

**Comment by liamdennehy** [comment]
Apologies for the quiet spell, finding a good time to tinker with my initrd takes planning.

**Comment by moviuro** [comment]
The correct option to add is `luks.options=allow-discard` (or is it `allow-discards`? doign that from memory).

I have just reinstalled my machine with `[rd.]luks[.*]=` cmdline and I have been able to run `fstrim` with no issue.

**Comment by liamdennehy** [comment]
A lot of work to replicate, will re-open if this is urgent and I have time. thanks for the responses.
