### ISSUE TITLE
IPv6AcceptRA ignores kernel default sysctl value

### ISSUE THREAD

**Issue by WRMSRwasTaken** [systemd/systemd#13061]
**systemd version the issue has been seen with**
> systemd 242 (242.32-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `br0` has just the delegated /64 prefix from dhcpcd assigned.

**Unexpected behaviour you saw**
 > `br0` has the delegated /64 prefix and a SLAAC address on it.

**Steps to reproduce the problem**

I'm using my Arch Linux box as home router. Upstream connectivity is done via pppd over an PPPoE link and acquiring a delegated IPv6 prefix on the WAN link is done via dhcpcd's `ia_pd` option. I'm using systemd-networkd to set up the local LAN bridge `br0` and to assign the IPv4 network address to it. Advertising the IPv6 prefix is done via radvd.

Having set 
```
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.br0.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
```
in `sysctl.d` is apparently ignored by systemd-networkd, as it still assigns a SLAAC address to the `br0` interface. I have to explicitely set `IPv6AcceptRA=false` on the `br0` network configuration file to keep systemd-networkd from assigning a SLAAC address to `br0`.

Starting systemd-networkd in debug mode reveals, that its definitely systemd-networkd, where that SLAAC address is coming from:
```
NDISC: Received Router Advertisement: flags none preference low lifetime 30 sec
NDISC: Invoking callback for 'router' event.
br0: No NDisc route added, gateway fe80::1 matches local address
br0: Configuring route: dst: 2001:16b8:3064:9007::/64, src: n/a, gw: n/a, prefsrc: n/a
br0: Configuring route: dst: 2001:16b8:3064:9007::/64, src: n/a, gw: n/a, prefsrc: n/a
br0: Updating address: 2001:16b8:3064:9007:3efd:feff:fe58:f7d0/64 (valid for 1d)
```

**Comment by yuwata** [comment]
Yes, please specify `IPv6AcceptRA=false`. Sysctl just disables kernel's implementation. But networkd use our own implementation, and it is not controlled by sysctl, but `IPv6AcceptRA=` setting.

**Comment by WRMSRwasTaken** [comment]
Would it be possible to update the according man page entry? Because it sais `If unset, the kernel's default is used, and RAs are accepted only when local forwarding is disabled for that interface.`.

The manpage is a big confusing here as it leads to think, that systemd is going to respect the sysctl value.

**Comment by yuwata** [comment]
I see.
