### ISSUE TITLE
Possible bug in journald-syslog.c

### ISSUE THREAD

**Issue by jimseg** [systemd/systemd#13078]
We are seeing some cases where logs are being written using journald configured to forward to syslog with no rate limiting or flow control on journald. No report is made of logs not being forwarded, but they don't turn up in the log file.
looking at the code in journald-syslog.c I see this

```
        if (sendmsg(s->syslog_fd, &msghdr, MSG_NOSIGNAL) >= 0)
                return;
​
        /* The socket is full? I guess the syslog implementation is
         * too slow, and we shouldn't wait for that... */
        if (errno == EAGAIN) {
                s->n_forward_syslog_missed++;
                return;
        }
```
What happens if a signal is caught before sendmsg() has transmitted any data? Sendmsg() returns -1 and errno is set to EINTR. The message is NOT resent and it's not counted as a syslog_missed message.

The correct code would be something like:
```
       while (1) {
            int res;
             if ((res = sendmsg(s->syslog_fd, &msghdr, MSG_NOSIGNAL)) >= 0) { 
               return;
            }
            if (errno == EINTR) {
                  // redo the sendmsg()
                  continue;
             }
             break;
         } 
        // and then the original code 
       /* The socket is full? I guess the syslog implementation is
        * too slow, and we shouldn't wait for that... */
       if (errno == EAGAIN) {
           s->n_forward_syslog_missed++;
            return;
        }
```

**Comment by jimseg** [comment]
A quick grep on EAGAIN over the systemd source tree suggests that this may not be the only place where EINTR probably should result in a retry

**Comment by poettering** [comment]
we use the socket in O_NONBLOCK mode, i.e. sendmsg() never blocks, and hence we should never get EINTR from it either.

See this thread: where this behaviour was discussed:

https://patchwork.ozlabs.org/patch/333758/

Are you saying you saw an EINTR from this socket even though it was in non-blocking mode? If so, this sounds like a kernel bug.

**Comment by jimseg** [comment]
You are correct, it appears you can't get EINTR on sendmsg, I've just run a test program flooding between a pair of sockets while another process signalled it in a tight loop, but never got an EINTR. This appears not to be an issue.

**Comment by poettering** [comment]
Ok. Lets close this then
