### ISSUE TITLE
machined should support a copy-based fallback for clone on non-btrfs file systems

### ISSUE THREAD

**Issue by rickysarraf** [systemd/systemd#1308]
It is not very clear from the man pages whether machinectl support operations on containers that are residing on non-btrfs file systems.

To quote the man page.

```
       clone NAME NAME
           Clones a container or VM image. The arguments specify the name of the
           image to clone and the name of the newly cloned image. Note that
           plain directory container images are cloned into subvolume images
           with this command. Note that cloning a container or VM image is
           optimized for btrfs file systems, and might not be efficient on
           others, due to file system limitations.

           Note that this command leaves host name, machine ID and all other
           settings that could identify the instance unmodified. The original
           image and the cloned copy will hence share these credentials, and it
           might be necessary to manually change them in the copy.
```

and

```
       Machines are identified by names that follow the same rules as UNIX and
       DNS host names, for details see below. Machines are instantiated from
       disk or file system images, that frequently but not necessarily carry the
       same name as machines running from them. Images in this sense are
       considered:

       ·   Directory trees containing an OS, including its top-level directories
           /usr, /etc, and so on.

       ·   btrfs subvolumes containing OS trees, similar to normal directory
           trees.

       ·   Binary "raw" disk images containing MBR or GPT partition tables and
           Linux file system partitions.

       ·   The file system tree of the host OS itself.
```

Can you please clarify if ext4 is supported?

Currently error message is not very helpful.

```
rrs@chutzpah:~$ machinectl clone debTemplate fooBar
Could not clone image: Inappropriate ioctl for device
16:30 ♒♒♒    ☹  => 1  
```

**Comment by ghost** [comment]
At least for importing machined or importd create an image file which is formatted with btrfs if you are using ext4 or something else as the hosts file system

**Comment by rickysarraf** [comment]
Yes. I think that's something @poettering has commented on this topic before, about transparently loop mounting a flat image to /var/lib/machines/ with btrfs as the file system.

While I can see the reasoning to do that (snapshots), I have raised this bug more as a Feature Request.
BTRFS is still not a mainstream file system. I don't think even Fedora has plans of choosing it as the default any time soon.

As a fallback, if there is not btrfs, machinectl should be capable of doing copy based clones on traditional file systems.

**Comment by ghost** [comment]
Than maybe add something like [FR] or [Feature Request] or [RFC] to the topic?

**Comment by mbiebl** [comment]
@dg-ratiodata we have labels for that, which are more flexible

**Comment by poettering** [comment]
@rickysarraf so, the idea so far was to implicitly create a btrfs loopback file to use for /var/lib/machines, if that's empty and not on btrfs. That is already in place and should work fine.

If you set up /var/lib/machines with containers in them, on non-btrfs we could of course support a copy-based fallback for clone, hence I renamed the issue accordingly, as that's what I understand you are asking for.

**Comment by richardmaw-codethink** [comment]
This already exists, since the clone operation turns into https://github.com/systemd/systemd/blob/2933d599c242ebfc70ddcffe59163916b02270f1/src/shared/machine-image.c#L600 which falls back to copying the directory.

I've used it before and the tree I was using was sufficiently large that the d-bus call timed out on the response, but it finished copying in the background.

It is difficult to opt-out of using the loopback file as a fallback, requiring one of making /var/lib/machines a mount-point, uninstalling mkfs.btrfs, or putting a file in /var/lib/machines before your first `machinectl import` command, but if you do this then the fallback works sufficiently well.
