### ISSUE TITLE
journalctl --show-cursor does not show cursor if --until or --since and --reverse is used

### ISSUE THREAD

**Issue by timo-schluessler** [systemd/systemd#13105]
The --show-cursor option has no effect when the journal output reaches the end specified by --until (or --since in combination with --reverse).
The attached patch fixes that.

[fix-show-cursor-when-reaching-end.diff.gz](https://github.com/systemd/systemd/files/3405761/fix-show-cursor-when-reaching-end.diff.gz)

**Comment by poettering** [comment]
Any chance you can submit this as proper github PR? If you do we can properly review and merge the patch, so that it is correctly attributed to you!

**Comment by timo-schluessler** [comment]
Sorry for the late reply. Please find the PR at https://github.com/systemd/systemd/pull/14552.

**Comment by poettering** [comment]
Closes as #14551 is merged. Thanks!
