### ISSUE TITLE
systemd-mount ignores mount options

### ISSUE THREAD

**Issue by fabiscafe** [systemd/systemd#13108]
**systemd version the issue has been seen with**
242.32

**Used distribution**
Archlinux

I'm trying to mount my /home via a systemd mount and automount file. This by itself works BUT it completely ignores the `Options=` line of my mount file. While I have set `Options=rw,lazytime` the mount command tells me that:
```
/dev/sda3 on /home type f2fs (rw,relatime,lazytime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix)
```
And I cant find any way to make it stop adding this. There is nothing in the fstab about this one partition.

```
[Unit]
Description=Mount /home directory

[Mount]
Where=/home
What=/dev/disk/by-uuid/668161ae-5e0f-42cf-9c30-9b32f48b5f7b
Type=f2fs
Options=rw,lazytime
```
```
mount | grep "/home "
systemd-1 on /home type autofs (rw,lazytime,fd=44,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12645)
/dev/sda3 on /home type f2fs (rw,relatime,lazytime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix)
```

This behavior is really unexpected

This might be somehow related to: https://github.com/systemd/systemd/issues/13099 but I dont know for sure, so I made an own report for it.

**Comment by poettering** [comment]
What the kernel shows in these options is not directly related to what you set as mount option: depending on the file system the mount option string is substantially extended, showing the various mount options in effect by default, without you configuring them.

Or are you saying that the mount options contradict the ones you configure? i.e. that you set x=y but you see x=z being set?

**Comment by Tids** [comment]
OKAY after a little help on reddit. This is the expected behavior for the defaults options. the actual "defaults" option is just a meta-option with nothing real behind ity and only there because the fstab otherwise where not able to work (there must be a mount option in fstab or its invalid, so there is defaults). Mount defaults are added anyways.

HOWEVER. I still think its very confusing that you have this double mount systemd-1 and /dev/sda3 in my case, because it looks like your mount options will not be added. 

Sorry for that trouble :)

**Comment by poettering** [comment]
The option to turn off discard is "nodiscard" btw

**Comment by poettering** [comment]
The autofs entry is because you defined a .autmount unit too. It's simply the way that is implemented in the kernel...

**Comment by Tids** [comment]
> The autofs entry is because you defined a .autmount unit too.

Thats good to know. Thanks again! :)
