### ISSUE TITLE
Capability not found inside a container when started using machinectl start

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#13128]
**systemd version the issue has been seen with**
> ...v241-8.git9ef65cb.fc30

**Used distribution**
 > …Fedora 30

**Expected behaviour you didn't see**
 > I have a Fedora 30 host computer and a Fedora 30 container. When I do _systemd-nspawn -bi fedora.raw_ , inside the container shell I can do ping without any problem. But when I do _machinectl shell fedora_, I get the "Can't open socket: operation not permitted". So I infer it's a problem of capabilities. 

> I've read systemd.nspawn man page when it says there's by default a bunch of capabilities passed except CAP_NET_ADMIN. I think ping requires CAP_NET_RAW (so in theory it would be passed) but just to try I've written a file called "/etc/systemd/nspawn/fedora.nspawn" with this content. No luck:

> [Exec]
Capability=CAP_NET_ADMIN
[Network]
Private=no

> I don't know why systemd-nspawn works well but machinectl shell no. I expected to have the same behaviour usin systemd-nspawn and machinectl.

> Thanks

**Comment by q2dg** [comment]
There's an interesting blog post about this specific topic but I suspect it's a bit outdated because the solution proposed here (basically, run setcap cap_net_raw+ep /usr/bin/ping inside container) doesn't work: http://k.japko.eu/systemd-nspawn-ping-debug.html

**Comment by poettering** [comment]
Note that systemd-nspawn by default enables user namespacing, which makes restrictions on this. (i.e. it uses "-U").

Consider dropping in a .nspawn file next to the image that sets `PrivateUsers=` to off, to override the systemd-nspawn defaults.

**Comment by q2dg** [comment]
Oooh, you're RIGHT!!
Thank you a lot, and sorry for the inconvenience...at least one positive thing is this issue will remain here for reference.

**Comment by MoonSweep** [comment]
> There's an interesting blog post about this specific topic but I suspect it's a bit outdated because the solution proposed here (basically, run setcap cap_net_raw+ep /usr/bin/ping inside container) doesn't work: http://k.japko.eu/systemd-nspawn-ping-debug.html

This solution still works for me with systemd 251.3 and kernel 5.18.2 on host (Debian stable with backports). Why ? Are my containers not properly unprivileged ? (`PrivateUsers` is indeed enabled).
