### ISSUE TITLE
"systemctl stop systemd-binfmt" should remove the registered entries?

### ISSUE THREAD

**Issue by junaruga** [systemd/systemd#13129]
**systemd version the issue has been seen with**

```
$ rpm -q systemd
systemd-241-8.git9ef65cb.fc30.x86_64
```

**Used distribution**

Fedora 30 on x86_64

**Expected behaviour you didn't see**

I think "systemctl stop systemd-binfmt" should removed entries (binary formats) (= `/proc/sys/fs/binfmt_misc/qemu-*` files) that were registered (added) by "systemctl start systemd-binfmt".

**Unexpected behaviour you saw**

After running `sudo systemctl stop systemd-binfmt`, below `qemu-*` files on /proc/sys/fs/binfmt_misc are still remaining.

```
$ ls -l /proc/sys/fs/binfmt_misc
total 0
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64_be
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-alpha
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-arm
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-armeb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-hppa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-m68k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblaze
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblazeel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-or1k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64le
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-s390x
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4eb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sparc32plus
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensaeb
--w------- 1 root root 0 Jul 21 18:51 register
-rw-r--r-- 1 root root 0 Jul 19 00:16 status
```

**Steps to reproduce the problem**

If you have already added registered entries, remove those by below command by root.

```
# find /proc/sys/fs/binfmt_misc -type f -name 'qemu-*' -exec sh -c 'echo -1 > {}' \;
```

See "qemu-*" files are not under the  `/proc/sys/fs/binfmt_misc` directory.

```
$ ls -l /proc/sys/fs/binfmt_misc
total 0
--w------- 1 root root 0 Jul 21 18:51 register
-rw-r--r-- 1 root root 0 Jul 19 00:16 status
```

Start `systemd-binfmt` service.

```
$ sudo systemctl start systemd-binfmt
```

Then new files `/proc/sys/fs/binfmt_misc/qemu-*` are added by `systemctl start systemd-binfmt`.
I assume below kind of logic is internally executed by `systemctl start systemd-binfmt` for each "qemu-$cpu" entries.

```
# echo ":qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:" > /proc/sys/fs/binfmt_misc/register
```

```
$ ls -l /proc/sys/fs/binfmt_misc
total 0
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64_be
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-alpha
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-arm
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-armeb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-hppa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-m68k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblaze
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblazeel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-or1k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64le
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-s390x
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4eb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sparc32plus
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensaeb
--w------- 1 root root 0 Jul 21 18:51 register
-rw-r--r-- 1 root root 0 Jul 19 00:16 status
```

Then stop systemd-binfmt service.

```
$ sudo systemctl stop systemd-binfmt
```

But `/proc/sys/fs/binfmt_misc/*` are remaining without updating.
I think this behavior is not great. Because when `systemctl start systemd-binfmt` creates new entries and the files, `systemctl stop systemd-binfmt` should remove the entries.

```
$ ls -l /proc/sys/fs/binfmt_misc
total 0
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-aarch64_be
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-alpha
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-arm
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-armeb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-hppa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-m68k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblaze
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-microblazeel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mips64el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsel
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-mipsn32el
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-or1k
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-ppc64le
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv32
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-riscv64
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-s390x
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sh4eb
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-sparc32plus
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensa
-rw-r--r-- 1 root root 0 Jul 21 19:34 qemu-xtensaeb
--w------- 1 root root 0 Jul 21 18:51 register
-rw-r--r-- 1 root root 0 Jul 19 00:16 status
```

I think below kind of logic to remove entries and the `/proc/sys/fs/binfmt_misc/qemu-*` files needs to be included in the logic of `systemctl stop systemd-binfmt`.

```
# find /proc/sys/fs/binfmt_misc -type f -name 'qemu-*' -exec sh -c 'echo -1 > {}' \;
```

## References

https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html

Target files

```
$ find . -name "*binfmt*"
./test/fuzz/fuzz-unit-file/proc-sys-fs-binfmt_misc.automount
./man/binfmt.d.xml
./man/systemd-binfmt.service.xml
./units/proc-sys-fs-binfmt_misc.mount
./units/proc-sys-fs-binfmt_misc.automount
./units/systemd-binfmt.service.in
./src/binfmt
./src/binfmt/binfmt.c
```

How do you think?
Thanks.

**Comment by junaruga** [comment]
I found `/usr/lib/binfmt.d/qemu-*-static.conf` files by qemu-user-static RPM package.

```
$ rpm -qf /usr/lib/binfmt.d/qemu-aarch64-static.conf
qemu-user-static-3.1.0-9.fc30.x86_64
```

So, a software that has the responsibility to remove the entries is not systemd but qemu-user-static?

**Comment by poettering** [comment]
We don't bother removing those rules, since it doesn't really matter, does it?

We could probably change the tool so that it deletes all rules currently not declared in binfmt.d/ rules, but this would mean systemd takes exclusive ownership of binfmt files, and people would hate us for that.

Hence, what are you trying to fix? if a rule is configured and the executing binary is not installed anymore, is that really a problem? i.e. all it does change the error you get when execv() fails slightly, and we waste a tiny bit of memory, but is that really a problem? It's not that these entries grow without bounds, they are limited to whatever the distro packages basically...

**Comment by poettering** [comment]
I am very sure that we shouldn't bother with removing the rules during stop, because that's needless work during shutdown. i.e. if anything then the systemd-binfmt should maybe be able to sync up whatever is configured in binfmt.d with the kernel version and thus remove lines currently in effect but not listed, but dropping them systematically at shutdown i am very convinced we should not do

**Comment by junaruga** [comment]
> We don't bother removing those rules, since it doesn't really matter, does it?
> ...
> Hence, what are you trying to fix?

## The case to use 2 programs registering same files but different content under `/proc/sys/fs/binfmt_misc`.

Current behavior can be a problem when working with 2 programs registering same files but different content under `/proc/sys/fs/binfmt_misc`.

1st program is Fedora's qemu-user-static RPM package.

```
$ sudo dnf install qemu-user-static
```

The process installs `/usr/lib/binfmt.d/qemu-$cpu-static.conf` files.
Then run `/bin/systemctl --system try-restart systemd-binfmt.service` to create `/proc/sys/fs/binfmt_misc/qemu-$cpu` files. See https://src.fedoraproject.org/rpms/qemu/blob/f30/f/qemu.spec#_1237

The process creates `/proc/sys/fs/binfmt_misc/qemu-aarch64` file from `/usr/lib/binfmt.d/qemu-aarch64-static.conf` with **`flags: F`** like this.

```
# echo ":qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:F" > /proc/sys/fs/binfmt_misc/register

# cat /proc/sys/fs/binfmt_misc/qemu-aarch64
enabled
interpreter /usr/bin/qemu-aarch64-static
flags: F
offset 0
magic 7f454c460201010000000000000000000200b700
mask ffffffffffffff00fffffffffffffffffeffffff
```

2nd program is https://github.com/multiarch/qemu-user-static .
The program is like above qemu-user-static RPM registering qemu's rules to binfmt_misc .
As registering rules is executed in the container to the host OS's `/proc/sys/fs/binfmt_misc/qemu-*` files, it's useful to set it on a host OS that does not have the latest qemu-user-static.

```
$ sudo podman run --rm --privileged multiarch/qemu-user-static:register
```
or

```
$ docker run --rm --privileged multiarch/qemu-user-static:register
```

But the difference is the rule is registered with no flag (**`flags: `**) in case of the 2nd program.

```
# echo ":qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:" > /proc/sys/fs/binfmt_misc/register

# cat /proc/sys/fs/binfmt_misc/qemu-aarch64
enabled
interpreter /usr/bin/qemu-aarch64-static
flags: 
offset 0
magic 7f454c460201010000000000000000000200b700
mask ffffffffffffff00fffffffffffffffffeffffff
```

The program executes below commands at https://github.com/multiarch/qemu-user-static/blob/master/register/register.sh#L18-L23 .

```
$ curl -O https://raw.githubusercontent.com/qemu/qemu/master/scripts/qemu-binfmt-conf.sh
$ chmod +x qemu-binfmt-conf.sh

# find /proc/sys/fs/binfmt_misc -type f -name 'qemu-*' -exec sh -c 'echo -1 > {}' \;
# ./qemu-binfmt-conf.sh --qemu-suffix "-static" --qemu-path="/usr/bin/"
```

The difference appears as below result.

For the 1st program, when registering the rule with `flags: F`, below 2 `podman run` commands work.

```
$ podman pull arm64v8/fedora

$ podman run --rm -t arm64v8/fedora uname -m
aarch64

$ podman run --rm -t -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/fedora uname -m
aarch64
```

But 2nd program when registering with no flag, 1st command does not work. 2nd command works.

```
$ podman run --rm -t arm64v8/fedora uname -m
standard_init_linux.go:207: exec user process caused "no such file or directory"

$ podman run --rm -t -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/fedora uname -m
aarch64
```

About the flags: F, here is the explanation.

https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html

```
F - fix binary

    The usual behaviour of binfmt_misc is to spawn the binary lazily when the misc format file is invoked. However, this doesn``t work very well in the face of mount namespaces and changeroots, so the F mode opens the binary as soon as the emulation is installed and uses the opened image to spawn the emulator, meaning it is always available once installed, regardless of how the environment changes.
```

I want to know which qemu-user-static is creating current `/proc/sys/fs/binfmt_misc/qemu-aarch64` file.

I also faced another issue due to the difference of this flag for `mock` command. (https://github.com/rpm-software-management/mock/issues/277). The `mock` command expected the rule with `flags: F`.

## Not intuitive

2nd issue is current behavior is not intuitive for me for example comparing with nginx service.
After `systemctl stop systemd-binfmt`, then the service still works. That's not intuitive.

```
$ sudo dnf install nginx
$ sudo systemctl start nginx
$ curl http://localhost
  => OK
$ sudo systemctl stop nginx
$ curl http://localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
```

```
$ sudo dnf instal qemu-user-static
$ podman run --rm -t arm64v8/fedora uname -m
aarch64
$ sudo systemctl stop systemd-binfmt
$ podman run --rm -t arm64v8/fedora uname -m
aarch64
  => Still works.
```

> We could probably change the tool so that it deletes all rules currently not declared in binfmt.d/ rules, but this would mean systemd takes exclusive ownership of binfmt files, and people would hate us for that.

I agree with this. I like to see that systemd-binfmt only removes rules (entries): `/proc/sys/fs/binfmt_misc/*` declared in `/usr/lib/binfmt.d/qemu-*-static.conf` rules.

Because sometimes people manually add a rule like this person's blog, https://rwmj.wordpress.com/2013/12/22/how-to-run-aarch64-binaries-on-an-x86-64-host-using-qemu-userspace-emulation/ .

```
# echo ":my-qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:" > /proc/sys/fs/binfmt_misc/register
```

**Comment by junaruga** [comment]
I found a clue that systemd-binfmt might be expected to have a logic to remove the registered rules.

There is a binfmt-support deb package on Ubuntu.
https://packages.ubuntu.com/bionic/binfmt-support

```
$ podman pull ubuntu
$ podman run --rm -it ubuntu bash
```

```
#  apt-get install binfmt-support

# apt-cache show binfmt-support | grep Version
Version: 2.1.8-2
```

There are configuration files for systemd and init.d in the package.

```
# dpkg-query -L binfmt-support
...
/etc
/etc/init.d
/etc/init.d/binfmt-support
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/binfmt-support.service
...
```

There is a logic `ExecStop=/usr/sbin/update-binfmts --disable` to do something.
I am not sure if this logic is to remove registered rules (entries) under `/proc/sys/fs/binfmt_misc` .

```
# cat /lib/systemd/system/binfmt-support.service
# Copyright (C) 2013 Colin Watson.
#
# This file is part of binfmt-support.
#
# binfmt-support is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# binfmt-support is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with binfmt-support; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

[Unit]
Description=Enable support for additional executable binary formats
Documentation=man:update-binfmts(8)
DefaultDependencies=false
After=local-fs.target proc-sys-fs-binfmt_misc.automount

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/update-binfmts --enable
ExecStop=/usr/sbin/update-binfmts --disable
Restart=no

[Install]
WantedBy=multi-user.target
```

**Comment by junaruga** [comment]
Sorry to post many comments. I also reported related issue to Fedora qemu project that has qemu-user-static. Because after uninstalling qemu-user-static RPM package, `/proc/sys/fs/binfmt_misc/qemu-*` files are not removed. As a result, below command still works after that.

```
$ podman run --rm -t arm64v8/fedora uname -m
aarch64
```

qemu-user-static: qemu-user-static works even after "dnf remove qemu-user-static"
https://bugzilla.redhat.com/show_bug.cgi?id=1732178

**Comment by poettering** [comment]
We actually do this now, since 846acb6798a63f35162f58e1146d1a1f40849e86
