### ISSUE TITLE
Add native zram swap support

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#13135]
Fedora's zram package contains a service file and a startup script to reserve a chunk of memory as a compressed filesystem. It works much better than having the same amount of disk-backed swap, and is more useful than zswap, which would still need a backing store.

Fedora files:
https://src.fedoraproject.org/rpms/zram/tree/master

Ideally one could have the maximum percentage of memory to use for swap in the service file (or in a separate configuration file?), and the script/unit would take care of create the swap on the RAM-backed block device and mount it as swap.

I'd be happy working on an upstream solution to this (which wouldn't need zram utilities), but I'd need some guidance on how to integrate it.

**Comment by keszybz** [comment]
We have https://github.com/systemd/zram-generator. It's a separate repo because it's rust. But it should work better than the script in Fedora.

**Comment by hadess** [comment]
> We have https://github.com/systemd/zram-generator. It's a separate repo because it's rust. But it should work better than the script in Fedora.

Would a C implementation get merged into systemd proper, or would that be rejected because zram-generator would be preferred?

**Comment by keszybz** [comment]
Is zram-generator inadequate? If something is wrong with it and cannot be fixed, then sure, let's discuss alternatives.

**Comment by hadess** [comment]
> Is zram-generator inadequate? If something is wrong with it and cannot be fixed, then sure, let's discuss alternatives.

No, but it's not upstream/out-of-the-box systemd. If a C implementation to add to systemd proper would be rejected, then I'll just try to package this Rust implementation.

**Comment by keszybz** [comment]
https://src.fedoraproject.org/rpms/rust-zram-generator

**Comment by hadess** [comment]
Haha. OK :)

**Comment by hadess** [comment]
I'm not sure why we'd need to put the implementation language in the name of the package though.

**Comment by keszybz** [comment]
It's follows the general packaging guidelines. I guess "zram-generator" would be an option too, but that's a bit too generic.

**Comment by hadess** [comment]
I saw that the binary package name was zram-generator, so that's not quite as bad.
