### ISSUE TITLE
systemd-update-utmp.service sometimes does not write 'shutdown' utmp entry at reboot

### ISSUE THREAD

**Issue by koct9i** [systemd/systemd#13138]
Steps to reproduce:
1. restart system by command reboot
2. after boot in output of last -x, sometimes no related 'shutdown' entry

In systemd debug log I see

```
[ 1326.298644] systemd[1]: reboot.target: Trying to enqueue job reboot.target/start/replace-irreversibly
[ 1326.300052] systemd[1]: systemd-update-utmp-runlevel.service: Looking at job systemd-update-utmp-runlevel.service/start conflicted_by=no
[ 1326.302241] systemd[1]: systemd-update-utmp-runlevel.service: Looking at job systemd-update-utmp-runlevel.service/stop conflicted_by=no
[ 1326.304490] systemd[1]: systemd-update-utmp-runlevel.service: Fixing conflicting jobs systemd-update-utmp-runlevel.service/start,systemd-update-utmp-runlevel.service/stop by deleting job s
ystemd-update-utmp-runlevel.service/stop
[ 1326.306858] systemd[1]: systemd-update-utmp.service: Deleting job systemd-update-utmp.service/stop as dependency of job systemd-update-utmp-runlevel.service/stop
[ 1326.309210] systemd[1]: shutdown.target: Fixing conflicting jobs shutdown.target/stop,shutdown.target/start by deleting job shutdown.target/stop
[ 1326.311634] systemd[1]: systemd-update-utmp-runlevel.service: Deleting job systemd-update-utmp-runlevel.service/start as dependency of job shutdown.target/stop
```

**Comment by rmetrich** [comment]
@koct9i Hi, could you tell us on which platform this is seen and which systemd release is that?

**Comment by koct9i** [comment]
Ubuntu Xenial 16.04, systemd 229 + ubuntu patches
Not sure how often this happens, we have really large fleet of servers.

Also reported for some old centos https://bugs.centos.org/view.php?id=12640

**Comment by rmetrich** [comment]
OK, this also happens on RHEL 7, but wasn't able to reproduce in recent Fedora or RHEL 8.
Hence, it's unlikely this will be fixed since issue is gone in recent systemd.
The shutdown sequence has been redesigned, there is no more this kind of conflicting units which makes systemd kill randomly one of the units.

**Comment by koct9i** [comment]
Yep, most like this is fixed but it's hard to deduce origin of issue from these messages.
This commit in v233 looks like fix: 33e28180939bd1e71c3d8322b4e2c3fb338bc2fb

**Comment by rmetrich** [comment]
Thanks, I will give it a try on RHEL7 and report.

**Comment by dtardon** [comment]
> OK, this also happens on RHEL 7, but wasn't able to reproduce in recent Fedora or RHEL 8.

This can be closed then, can't it?

**Comment by poettering** [comment]
OK, let's close

**Comment by wenjianhn** [comment]
Add a workround for the issue:

```
[root@localhost ~]# cat /etc/systemd/system/systemd-update-utmp-runlevel.service.d/empty-requisite.conf
# A workaround for the issue: system shutdown not properly detected by: last -Fxn2 reboot shutdown
# Link: https://access.redhat.com/solutions/5526311
[Unit]
Requisite=
```

Link: https://access.redhat.com/solutions/5526311
