### ISSUE TITLE
_gateway resolves to a non-default gateway

### ISSUE THREAD

**Issue by lilydjwg** [systemd/systemd#13132]
**systemd version the issue has been seen with**
> systemd 242 (242.32-3-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > _gateway resolves to only default gateways as the doc says

**Unexpected behaviour you saw**
 > _gateway resolves to multiple IPs including a non-default gateway

**Steps to reproduce the problem**
I have `ip r` results like below:

```
default via 192.168.199.1 dev wlan0 
some_ip via 192.168.58.3 dev wg0 
192.168.58.0/24 dev wg0 proto kernel scope link src 192.168.58.1 
192.168.199.0/24 dev wlan0 proto kernel scope link src 192.168.199.X 
```

(`some_ip` is a single IP, not a network.)

And I get from `getent ahostsv4 _gateway`:

```
192.168.58.3    STREAM _gateway
192.168.58.3    DGRAM  
192.168.58.3    RAW    
192.168.199.1   STREAM 
192.168.199.1   DGRAM  
192.168.199.1   RAW    
```

**Comment by poettering** [comment]
uh, this is weird... the code actually explicitly checks that the prefixlen of the destination is zero... not sure why that doesn't work for you. Is this a current kernel? any other weird routing or so being used?

any chance you can checkout systemd sources, build them (most distros have toolsets to make this easy, and automaticall acquire all all deps you need), and then maybe step through `test-local-addresses`, which you'll find in the build tree. It#s a simple test case that just prints your local addresses and gateways (only the latter is interesting here).

**Comment by lilydjwg** [comment]
Oops, I do have a route table 8 that has it as default route (this was an old config that I've forgotten).

So, is it expected that `_gateway` returns default gateways from all route tables?

**Comment by poettering** [comment]
so, hmm, i figure we should ignore all routing tables != RT_TABLE_MAIN
