### ISSUE TITLE
systemd-firstboot should configure /etc/localtime in system with fresh systemd installation

### ISSUE THREAD

**Issue by msehnout** [systemd/systemd#13183]
**Is your feature request related to a problem? Please describe.**
I work on a tool for OS image creation (specific to Fedora):
https://github.com/larskarlitski/osbuild/
While creating the image we install packages using `dnf` as usual and now we would like to use `systemd-firstboot` to configure the system. But in case of `/etc/localtime`, `systemd-firstboot` skips the configuration because the file already exists. It was created when the `systemd` RPM package was installed.

```
root@localhost /t/f/root# tar xf ../base.tar.xz # Extracting an image with installed packages
root@localhost /t/f/root# pwd
/tmp/fstree/root
root@localhost /t/f/root# ll etc/localtime
lrwxrwxrwx. 1 root root 25 Jul 24 09:52 etc/localtime -> ../usr/share/zoneinfo/UTC
root@localhost /t/f/root# systemd-firstboot --root=/tmp/fstree/root --timezone=Europe/Berlin
root@localhost /t/f/root# ll etc/localtime
lrwxrwxrwx. 1 root root 25 Jul 24 09:52 etc/localtime -> ../usr/share/zoneinfo/UTC
root@localhost /t/f/root# rm etc/localtime
root@localhost /t/f/root# systemd-firstboot --root=/tmp/fstree/root --timezone=Europe/Berlin
/tmp/fstree/root/etc/localtime written
root@localhost /t/f/root# ll etc/localtime
lrwxrwxrwx. 1 root root 35 Jul 25 07:40 etc/localtime -> ../usr/share/zoneinfo/Europe/Berlin
```

**Describe the solution you'd like**
Install the file even though it exists.

**Describe alternatives you've considered**
Don't install the file in the RPM package.

**Affected source code:**
https://github.com/systemd/systemd/blob/master/src/firstboot/firstboot.c#L419

I don't have any strong opinion on which solution is preferred but I'd like to avoid the workaround with `rm etc/localtime`.

**Comment by poettering** [comment]
This sounds like something to change in the RPM specfile: it should "ghost" the symlink but not create it. That way it's still owned by the RPM but not installed by default. Given that glibc defaults to UTC if the symlink is missing (and so do we with the default etc.conf snippet we ship) there should be no reason to include it directly in the RPM. @keszybz opinion?

This should really be filed on rhbz though against the rpm, not here, since it's a downstream issue, not an upstream one.

**Comment by msehnout** [comment]
> This should really be filed on rhbz though against the rpm, not here, since it's a downstream issue, not an upstream one.

Well that depends on the decision on how to fix it. If we fix it in RPM then yes it is a downstream issue, but if we fix it in systemd-firstboot then it is upstream issue.

**Comment by keszybz** [comment]
I agree that this is something to fix at the spec file level. Which rpm is creating it though? systemd owns the symlink, but it is ghosted, so it shouldn't be created. Please file a bugzilla and we'll figure it out.

**Comment by keszybz** [comment]
> Given that glibc defaults to UTC if the symlink is missing (and so do we with the default etc.conf snippet we ship) there should be no reason to include it directly in the RPM.

We run `systemd-tmpfiles --create` in %post. Either we need to stop doing that, or we should drop the symlink from tmpfiles. I think the latter is the way to go: why should we create the symlink, if it's not needed for anything?

**Comment by poettering** [comment]
hmm, the reason being that people might expect the symlink to be there, but you do have a point...

But i figure in @msehnout and @larskarlitski's usecase maybe they should be using the firstboot stuff to provision there settings even *before* installing any RPMs, i.e. before the tmpfiles.d/ stuff runs

**Comment by teg** [comment]
At least in principle, we are currently using firstboot after doing rpm's, however, I think it would be nice if /etc to the extent possible is just left empty by tmpfiles (and rpm), so if there is no reason to have the symlink by deault, it would be nice to drop it I think.

**Comment by poettering** [comment]
(btw, the design idea behind the firstboot stuff is that it would only fill in what is not provisioned yet elsewhere. that said, we could also add --force or so as switch, if that would make sense to you?)

**Comment by teg** [comment]
Hm, after some more discussion, I think that we should look into some of the other systemd-* tools before going the --force mode way.

I mean, ideally dnf would allow some sort of mode where tmpfiles would just not be triggered when not installing into a running system, then there wouldn't be the need of forcibly overwriting things.

However, it might also be that firstboot really isn't he right thing to run on image building time. It does a lot of the things that we want, but for instance setting the machine-id, is really something you only want to do when you are actually booting the instance, not when you are creating the golden image (which would be shared).

**Comment by poettering** [comment]
hmm, we don't initialize the machine ID in systemd-firstboot unless you specify --setup-machine-id though, no?
