### ISSUE TITLE
network: DHCP.SendRelease may not work as expected

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#13181]
I've tried to add a test for the setting to systemd-networkd-tests.py, but I could not. There are no DHCPRELEASE in dnsmasq's log. @ssahani Could you tell me howto test the option?

**Comment by yuwata** [comment]
Also, #11883 does not work.
I guess `dhcp_network_send_udp_socket()` or something around that is wrong, not sure. The function is only used with RELEASE and RENEW.

**Comment by ssahani** [comment]
Veth it won't work. Please verify in a real interface.

**Comment by yuwata** [comment]
Why it doesn't work with veth?

**Comment by ssahani** [comment]
I figure both end has to be up to the release packet to go throw. One end goes down hence packet does not pass.
