### ISSUE TITLE
RFE: [logind] Maybe TakeDevice should return the file descriptor to privileged callers anyway?

### ISSUE THREAD

**Issue by zb3** [systemd/systemd#1319]
Currently, `TakeDevice` method only works if the caller is a session controller, and the device has not been taken already. However, privileged process can already 1) become a session controller 2) open the device node directly.

The only difference is that the file descriptor returned by `TakeDevice` is bound to a session that is - it's automatically paused / resumed (read: a new fd is returned in case of event devices), and this is the kind of functionality that a privileged process currently has to reimplement if it wants to.

For instance, now in my program I need to do the following:
-get current session
-enumerate all (event) devices
-check what seat device belongs to
-if the seats match, add device
-watch session `.Active`, and pause devices manually

If `TakeDevice` returned the fd anyway, I'd just need to:
1. Enumerate all event devices
2. Call `TakeDevice` (it verifies seat)
3. Listen to signals.

A quick look at the code reveals:
->`TakeDevice`/`ReleaseDevice` currently don't count fd references as fd can be returned only once
->`session_device_notify` only notifies the session controller

So this is just a pure enhancement, and may not be reasonable at all :)
Thanks for reading this though

**Comment by poettering** [comment]
@dvdhrm something for you.

**Comment by dvdhrm** [comment]
Can you elaborate on the use-case?

**Comment by zb3** [comment]
For instance if an app wants to listen for gestures / shortcut keys globally, but only per session, and the app doesn't want to limit itself to particular display server / compositor / DE.

With X, you used to be able to capture keys / clicks, and even without being privileged (which can be viewed as a security issue), and this is not what I am asking for!

My point is that if the process is privileged, and can kick out the session controller and thereby get the fd anyway in a destructive way, why shouldn't it be able to get that fd in a non-destructive way?

Current design is a bit counter-intuitive, because non-privileged process gets the device (like Xorg), but a privileged process can't (unless it manually suspends the device)

(but of course, we're talking about an enhancement here, not a possibility, and the fact that this won't be implemented won't stop me from implementing this logic in the app)

**Comment by dvdhrm** [comment]
> For instance if an app wants to listen for gestures / shortcut keys globally, but only per session, and the app doesn't want to limit itself to particular display server / compositor / DE.

We explicitly don't support it. Keyboard handling must be managed by a global entity. Imagine your hack handles a shortcut, who tells the compositor to skip this key-press? If you don't, the key-press might have multiple effects.

> My point is that if the process is privileged, and can kick out the session controller and thereby get the fd anyway in a destructive way, why shouldn't it be able to get that fd in a non-destructive way?

There are a lot of things root can do, which we explicitly don't support. The force-takeover of session controllers should be solely used to recover from failed sessions in emergencies. I bet we could even remove the feature entirely and no-one would bother.

> Current design is a bit counter-intuitive, because non-privileged process gets the device (like Xorg), but a privileged process can't (unless it manually suspends the device)

Yes, this is intentional.

**Comment by zb3** [comment]
Okay, I understand, however, as this won't stop people from doing those things, note that workarounds may be even worse. In this case, **no** workaround is needed, so there's no problem.

**Comment by dvdhrm** [comment]
We cannot prevent people from shooting themselves in their foot. But we can make sure our API doesn't encourage them to do so.

Anyway, closing now. Feel free to re-open if there's a real need for this.
