### ISSUE TITLE
RoutingPolicyRule has no knob to create AF_INET6 rule

### ISSUE THREAD

**Issue by mweinelt** [systemd/systemd#13233]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > NixOS

**Expected behaviour you didn't see**
 > networkd should be able to add AF_INET6 policy rules (`ip -6 rule`)

**Unexpected behaviour you saw**
 > networkd is hardcoded to create rules for AF_INET only, while most of the code seems to handle AF_INET6.

https://github.com/systemd/systemd/blob/4ff296b02411bb4f0dc38f48cbab06f8645d2a08/src/network/networkd-routing-policy-rule.c#L25-L28

**Steps to reproduce the problem**

```
[RoutingPolicyRule]
IncomingInterface=vlan200
Table=100
Priority=100
```

will always result in an AF_INET rule, there is no knob to make it apply to AF_INET6 traffic.

```
# ip ru
0:	from all lookup local
100:	from all iif vlan200 lookup 100
32766:	from all lookup main
32767:	from all lookup default
# ip -6 ru
0:	from all lookup local
32766:	from all lookup main
```

**Comment by yuwata** [comment]
Maybe, a workaround for the issue is setting e.g. `To=::/0`.

**Comment by yuwata** [comment]
I've created #13235. If possible, please test the PR. Thank you.

**Comment by mweinelt** [comment]
> Maybe, a workaround for the issue is setting e.g. `To=::/0`.

Yes, that works, quite unexpected.

```
# ip -6 ru
0:	from all lookup local
100:	from all iif vlan200 lookup 100
32766:	from all lookup main
```

> I've created #13235. If possible, please test the PR. Thank you.

I have to talk to the package maintainer on how to apply this patch, I'm not familiar enough with the build system.

**Comment by ssahani** [comment]
Well please respect @yuwata. He opened the right pr. And I approved it with minor changes

**Comment by mweinelt** [comment]
@ssahani I've seen the pr and I intend to test it, I just have to check how to accomplish this on NixOS.

**Comment by iBug** [comment]
This is a good addition, but once upon a time I spent more than an hour wondering why it didn't work with systemd 242. May I ask that this PR be documented in [the `NEWS` file](https://github.com/systemd/systemd/blob/master/NEWS) (which is the factual changelog for systemd).
