### ISSUE TITLE
covscan issue in sd-bus: negative_returns

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#13237]
Found in the current master (5c76ca6093de7ca9695929db7b5497b15e681850).

https://github.com/systemd/systemd/blob/5c76ca6093de7ca9695929db7b5497b15e681850/src/libsystemd/sd-bus/bus-message.c#L3883-L3884

```
src/libsystemd/sd-bus/bus-message.c:3883: negative_return_fn: Function "bus_gvariant_get_alignment(t)" returns a negative number. 
src/libsystemd/sd-bus/bus-message.c:3883: assign: Assigning: "align" = "bus_gvariant_get_alignment(t)". 
src/libsystemd/sd-bus/bus-message.c:3887: negative_returns: "align" is passed to a parameter that cannot be negative. 
```

**Comment by keszybz** [comment]
There's `assert(align > 0)` right below the assignment. Error handling is done above in `signature_element_length()`.
