### ISSUE TITLE
systemd-resolved forwarding to a nonstandard port

### ISSUE THREAD

**Issue by jimc-leones** [systemd/systemd#13247]
This is for systemd-242.  In /etc/systemd/resolved.conf DNS parameter
(list of DNS servers that systemd-resolved should forward queries to),
it presently wants a space separated list of IP addresses, with the
standard port 53 being used implicitly.  Could we please be able to
forward to a nonstandard port?

Here's my use case: There's a master directory server, two slaves, and a
bunch of leaf nodes.  The master has dnsmasq with DHCP service for nodes
with centrally assigned fixed IPs, and for aleatory guest nodes. Dnsmasq
also sends out AAAA's from /etc/hosts and /etc/ethers (RFC 4862
addresses).  Multicast DNS (by Avahi) on each node provides $HOST.local.
The master and the slaves have Berkeley Bind ("named"), which is
authoritative for my internal domain and which provides recursive
service to internal clients, to forward queries to offsite DNS servers.

In the present setup, a leaf node's app calls gethostinfo from glibc,
which obeys /etc/nsswitch.conf and (not finding info in /etc/hosts) uses
the D-Bus API to contact its systemd-resolved, which forwards the offsite
query to the master's port 53 (dnsmasq), which forwards it to the
master's "named" running on nonstandard port 4253.  The slave dirsvrs'
"named" shares port 53 on all interfaces, competing with
systemd-resolved and causing a race condition at startup
(systemd-resolved will die if "named" has already opened the port) plus
other odd behavior.

I would like to move the slaves' "named" to port 4253 same as on the
master, but I see no simple and non-kludgey way to get systemd-resolved
to query a nameserver (local or remote) on a nonstandard port.  I have
written a kludge that listens on 127.0.0.253 port 53/udp and forwards to
one of the dirsvrs on port 4253, failing over to different ones during
system downtime.  The master is always preferred because it knows the
DHCP and RFC 4862 addresses.  This is working well (except that it's a
total kludge).  It would be really nice if systemd could include this
function.

A question came up about what should be the separator between the IP 
address and the port.  ':' is traditional including in the HTTP URI 
syntax, for example 2600:3c01:e000:306::c1:4253.  But this makes you
need to enclose the IPv6 address in brackets as for HTTP.  In my kludge
I just used '#' instead as the separator.  (I've just switched IPv6
tunnel brokers and I wish addresses already in /etc/hosts could be
used, bypassing the separator issue, but I think that would be a whole
other can of worms outside this RFE.)

**Comment by eliasp** [comment]
Another scenario where this would be useful: using [HashiCorp Consul and DNS forwarding](https://learn.hashicorp.com/consul/security-networking/forwarding#systemd-resolved-setup).

**Comment by zhoreeq** [comment]
:+1: Would be very useful

**Comment by LaserEyess** [comment]
As DoT and DoH become more common and more DNS servers support them, the ability to run them on non-standard ports would be ideal. I think even plain DNS could somehow benefit if you're forced to use a port that isn't 53.
