### ISSUE TITLE
systemd-logind assertion failure when closing lid

### ISSUE THREAD

**Issue by krinnewitz** [systemd/systemd#13255]
**systemd version the issue has been seen with**
> 243_rc1

**Used distribution**
 > gentoo testing

**Unexpected behaviour you saw**
 > When closing the lid of my Thinkpad T470p, systemd-logind crashes with the following message: ` Assertion 'handle > HANDLE_IGNORE && handle < _HANDLE_ACTION_MAX' failed at src/login/logind-action.c:65, function manager_handle_action(). Aborting.` 

**Steps to reproduce the problem**
Close the lid

**Comment by krinnewitz** [comment]
Seems to only happen if I have `HandleLidSwitch=ignore` in logind.conf.

**Comment by SoapGentoo** [comment]
Can confirm, same setup, `HandleLidSwitch=ignore`, core dumps on me too.

**Comment by yuwata** [comment]
Thank you for the reports. Fix is waiting in #13258.
