### ISSUE TITLE
mounting an USB device gives "Assertion 'key' failed at src/libsystemd/sd-device/device-private.c:34"

### ISSUE THREAD

**Issue by HJarausch** [systemd/systemd#13257]
On my Gentoo system, 
Version 243_rc1 crashes when I try to mount an (external) USB drive.
I get
kernel: sd 10:0:0:0: [sde] Assuming drive cache: write through
kernel:  sde: sde1 sde2 sde3 sde4 sde5 sde6 sde7
kernel: systemd-udevd[480887]: 
Assertion 'key' failed at src/libsystemd/sd-device/device-private.c:34, 
function device_add_property(). Aborting.

Furthermore, it looks like Virtualbox crashes when I try to run a virtual Windows10 system.

Version 242-r6 works just fine here.
Note: my system is started by openrc (not systemd)

**Comment by yuwata** [comment]
Could you generate debug log? Booting with `udev.log_priority=debug` kernel command line option generates that.

**Comment by yuwata** [comment]
Apparently, I found the root of this issue. If possible, please test PR #13259. Thank you.
