### ISSUE TITLE
Consistent machine-id and hostname on stateless systems

### ISSUE THREAD

**Issue by tanertas** [systemd/systemd#13261]
**Is your feature request related to a problem? Please describe.**
I'm trying to solve consistent machine-id and hostname issue for my client machines that relies on PXE and nfsroot . Client machines must have acquired unique and consistent hostnames and machine-id's. Since their 'common' file system is a read-only nfs export, I tried auto generate these hostname and machine-id files in /run folder (which is read-write) and make them available for systemd's corresponding units.

I'm able to generate these files in /run folder with a custom systemd service but the custom service script always kick in too late to make these files available for systemd. Systemd's hostname and machine-id check mechanism always considers that /etc/hostname and /etc/machine-id (which are symbolic links for /run/hostname and /run/machine-id in my exported rootfs) are not available:

```
localhost systemd[1]: Running with unpopulated /etc.
localhost systemd[1]: No hostname configured.
localhost systemd[1]: Set hostname to <localhost>.
localhost systemd[1]: Initializing machine ID from random generator.
localhost systemd[1]: Failed to populate /etc with preset unit settings, ignoring: Read-only file system
```
This is the service file I use. I tried basic.target, local-fs.target and sysinit.target.
```
[Unit]
Description=Init hostname, machine-id, domain
DefaultDependencies=no
Before=systemd-sysusers.service sysinit.target shutdown.target
ConditionPathIsReadWrite=/run

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/opt/dmb/bin/init.sh sethostname
StandardOutput=journal

[Install]
WantedBy=sysinit.target
```

**Describe the solution you'd like**
Proper method to populate /run folder right before systemd trying to check /etc/hostname and /etc/machine-id without relying on initramfs scripts. 

**Describe alternatives you've considered**
initramfs

**Comment by poettering** [comment]
we want that userspace can rely that the machine ID is always available, hence PID 1 will set it up very early on if it's not set up yet. If you want to se it before that you can do so from the initrd. (or in case you run this in KVM you can pass the UUID via the DMI data, or if in a container via $container_uuid).

Setting the uuid after PID 1 is already running is too late. early boot stuff like the journal want to include the machine ID in their log metadata and don't like it if it's not available.

Changing the uuid during runtime is not supported either.

And this all is not going to change... Sorry..

(We could probably add a way though to provision the uuid via the kernel cmdline, if you need)

You can change the hostname anytime btw, just use sethostname() for that.

(Please contact systemd-devel for discussins like this btw. This is mostly a bug tracker, and a feature request tracker, but not a discussion forum for "how do I…?" questions, that's what the mailing list is for. Thank you for understanding)

**Comment by tanertas** [comment]
Thanks for input. 

Btw, I solved my problem with very simple initrd script on Debian system. Script just removes dashes from product_uuid and writes it as /run/machine-id.

 In case someone need a solution like myself, I'm leaving some details here:

Create a script (eg: machineid) with content below and make it executable. Put it in "/etc/initramfs-tools/scripts/init-top". Then rebuild initrd.

```
#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac
sed 's/-//g' /sys/class/dmi/id/product_uuid > /run/machine-id
```
In stateless system's read-only rootfs, /etc/machine-id and /var/lib/dbus/machine-id must be symbolic links pointing at "/run/machine-id".
