### ISSUE TITLE
Requesting fix of freedesktop.org page

### ISSUE THREAD

**Issue by emanuele6** [systemd/systemd#13262]
I don't know where to report this, so I am reporting it here.
On this page "https://www.freedesktop.org/wiki/Software/systemd/hackfests/" there is this point: `Set up an event page on Google+, and make sure to ping Kay or Lennart so that they can share it on systemd's own Google+ page.`
Since Google+ has been shut down by google in april, this list should be updated.

**Comment by keszybz** [comment]
Yeah, this is a good place for the report.

I marked the page as obsolete. Systemd is now a big project, and the advice on that page doesn't apply anymore. https://cgit.freedesktop.org/wiki/www/commit/Software/systemd/hackfests.mdwn?id=efc14916a7ed4c0b7b7c07bd461cdc6628088fe4
