### ISSUE TITLE
systemd-nspawn: "--bind-ro" binds to inactive host unit

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#1326]
Using `systemd-nspawn --bind-ro=/home/johndoe/development:/development …` has the following side-effects:
- the boot output of the container isn't shown anymore
- the following error message is shown:

```
Unit development.mount is bound to inactive unit dev-dm\x2d0.device. Stopping, too.
```

`dev-dm\x2d0.device` is the device on the Host providing the blockdevice for `-.mount`.
The container will (besides not showing the boot output and showing the error message instead) work just fine and also the `bind-ro` mount is present.
The status of `development.mount` in the container:

```
● development.mount - /development
   Loaded: loaded (/proc/self/mountinfo)
   Active: active (mounted) since Tue 2015-09-22 09:38:28 CEST; 2min 50s ago
    Where: /development
     What: /dev/dm-0
```

I can reproduce this using 219 (on Fedora 22) and current git @8c710f3ce64110a4cfe977116c55bd87777e641c (on Gentoo).

Steps to reproduce:

```
cd /var/lib/machines
debootstrap vivid ubuntu-vivid http://archive.ubuntu.com/ubuntu/
systemd-nspawn -nbxD /var/lib/machines/ubuntu-vivid --bind-ro=/home/elias/development:/development
```

**Comment by poettering** [comment]
v219 is in the container I presume? Is this reproducible with something newer in the cotnainer? Please report bugs only regarding the two or three most recetn systemd versions upstream.

**Comment by eliasp** [comment]
The versions referred to the host (Fedora 22, running v219 and Gentoo, running @8c710f3).
The container (Ubuntu Vivid, 15.04 was running v219).
I'll bootstrap a container image with a more recent systemd version than what Ubuntu Vivid offers and report back.

**Comment by eliasp** [comment]
Looks good with v225 in the container (Ubuntu 15.10).
Although there are some other warnings:

```
Failed to install release agent, ignoring: File exists
display-manager.service: Cannot add dependency job, ignoring: Unit display-manager.service failed to load: No such file or directory.
```

…the initially reported issue is fixed.

**Comment by mbiebl** [comment]
@eliasp if you don't boot into a graphical environment, you can use

```
systemctl set-default multi-user.target
```

This will get rid of the missing display-manager.service link warning you get when you try to boot into graphical.target and there is no actual displaymanager (like gdm) installed
