### ISSUE TITLE
BMC does not switch to next address when DNS sends multiple IP address to a 'A record'

### ISSUE THREAD

**Issue by prkatti1** [systemd/systemd#13275]
**systemd version the issue has been seen with**
systemd 242 (242-19-gdb2e367+)
> ...

**Expected behaviour you didn't see**
When we get multiple IP addresses to same FQDN, and if 1st IP address is down system should switch to 2nd IP from list
 > …

**Unexpected behaviour you saw**
If the 1st IP is down, system does not pick 2nd IP.
 > …

**Steps to reproduce the problem**
Steps:
Configure DNS server on BMC
Configure DNS server to send 2 IP addresses (IP1 and IP2) to DNS A record. (Exa: test1.bmc.com)
Make 1st IP address IP1 down.
Try to access or ping test1.bmc.com
BMC only try IP1 and it does not time out and try to reach 2nd IP.

**Comment by poettering** [comment]
I am sorry, what? What is BMC? What's the context of this? what does this have to do with systemd?

**Comment by boucman** [comment]
a quick check of the original bug...

apparently OpenBMC is a Yocto-Based linux distribution. The bug was redirected here because (I assume) it uses resolved for  DNS resolution ?

**Comment by poettering** [comment]
Let's close this, due to lack of response.
