### ISSUE TITLE
systemctl unescapes Alias value

### ISSUE THREAD

**Issue by rbalint** [systemd/systemd#13276]
**systemd version the issue has been seen with**
> 243~rc1-0ubuntu1

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > Value in Alias= is used as the symlink name

**Unexpected behaviour you saw**
 > "\x" in Alias value is is transformed to "x" in symlink name

**Steps to reproduce the problem**
```
ubuntu@autopkgtest:~$ cat /lib/systemd/system/unit\\x2dr3B54.service 
[Unit]
Description=test unit

[Service]
ExecStart=/bin/sleep 1

[Install]
WantedBy=multi-user.target
Alias=foo\x2dtest.service
ubuntu@autopkgtest:~$ sudo systemctl --system --preset-mode=enable-only preset unit\\x2dr3B54.service 
Created symlink /etc/systemd/system/foox2dtest.service → /lib/systemd/system/unit\x2dr3B54.service.
Created symlink /etc/systemd/system/multi-user.target.wants/unit\x2dr3B54.service → /lib/systemd/system/unit\x2dr3B54.service.
```

This breaks autopkgtest of init-system-helpers: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-eoan/eoan/amd64/i/init-system-helpers/20190805_230313_4b9ce@/log.gz

**Comment by mbiebl** [comment]
@rbalint Could this be related / the cause for #13272 ?

**Comment by rbalint** [comment]
@mbiebl I think it is related, but I consider the other issue a GDM packaging bug.

**Comment by poettering** [comment]
@keszybz hmm, this sounds like something that might have to do with the alias rework?

**Comment by poettering** [comment]
so i take it this used to work correctly <= v242, but is a regression introduced with v243-rc1?

**Comment by rbalint** [comment]
@poettering yes i did not observe it with 242
