### ISSUE TITLE
243-rc1 fails on cryptsetup-generator assertion 'keyspec' failed

### ISSUE THREAD

**Issue by yoshi314** [systemd/systemd#13270]
**systemd version the issue has been seen with**
243-rc1

**Used distribution**
Gentoo

**Expected behaviour you didn't see**
Correct boot

**Unexpected behaviour you saw**
 
sie 05 18:27:50 box systemd-cryptsetup-generator[740]: Assertion 'keyspec' failed at src/cryptsetup/cryptsetup-generator.c:53, function split_keyspec(). Aborting.
sie 05 18:27:50 box systemd[733]: /lib/systemd/system-generators/systemd-cryptsetup-generator terminated by signal ABRT.

and recovery shell after a few minutes.

**Steps to reproduce the problem**

Install systemd 243-rc1, observe the problem. Downgrade systemd to 242, everything works fine.

**Comment by keszybz** [comment]
Fixed already by fef716b28b.
