### ISSUE TITLE
RFE: systemd should read unit files from ~/.local/lib in addition to ~/.config

### ISSUE THREAD

**Issue by aburch** [systemd/systemd#1328]
I cannot enable ~/.config/user/systemd/emacs.service using `systemctl --user enable emacs` where emacs.service is a symlink to ~/common/dot.config/user/systemd/emacs.service. The unit has `WantedBy=default.target`.

Following the systemd user manager with strace, I noticed that systemd recognizes emacs.service as a symlink:

   readlinkat(AT_FDCWD, "/home/ansgar/.config/systemd/user/emacs.service", "../../../common/dot.config/syste"..., 99) = 53

but later tries to open it with O_NOFOLLOW:

```
open("/home/ansgar/.config/systemd/user/emacs.service", O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC) = -1 ELOOP (Too many levels of symbolic links)
```

systemd then checks a few other location and finally returns "Failed to execute operation: No such file or directory" to systemctl.

Creating the symlink in default.target.wants works.

**Comment by aburch** [comment]
Oh, and I forgot to mention that I use systemd 226 from Debian.

**Comment by jsynacek** [comment]
In general, `enable` doesn't work on symlinks. This "safety feature" has been there for quite some time. I believe that this issue qualifies as an RFE.

There is also a request in the Fedora Rawhide bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1014311

**Comment by aburch** [comment]
If this is a safety feature, it would then be nice if trying to use `systemctl enable` would give a more descriptive error when encountering symlinks.

I'm also wondering if this also causes #902 where a different unit than the one expected is enabled when symlinks are involved. As mentioned in my initial report, systemd seems to continue searching for unit files in other locations after encountering a symlink. Maybe a further reason to abort with an error in case a symlink is encountered instead of silently ignoring them and continuing the search?

**Comment by poettering** [comment]
Also see #1240.

**Comment by poettering** [comment]
So,  ~/.config is the place for  configuration, it's where "systemctl enable" and "systemctl disable" add and remoev symlinks, and we refuse to use use configuration info to manipulate configuration info... Otherwise the configuration commands such as "systemctl enable" and "systemctl disable" could never be symmetric... I figure to allow what you want to do, we have to actually support to unit dirs in the home directory. The one below ~/.config, and then one below ~/.local/lib. The latter would be a static repo of units, and ~/.config would be where configuration managed by systemctl would be, similar to the separation between /etc and /usr/lib for the system systemd instance.

Of course, systemd currently does not support ~/.local/lib. But I figure it should...

**Comment by vivien** [comment]
Seems like this has been fixed, with the difference that ~/.local/share/ is used over ~/.local/lib.

That fixes my `systemctl --user enable foo.timer` when enabling a timer symlinked from a dotfile repository to ~/.local/share/systemd/user/ (as well as the corresponding service).

I get this message though, even if the timer as an Install section containing `WantedBy=default.target`, and the timer correctly starts after subsequent reboots:

```
The unit files have no [Install] section. They are not meant to be enabled                                
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
```

Anyway, it looks like this issue can be closed?

**Comment by keszybz** [comment]
Yep, this should be fixed now. There were a lot of improvements to the logic that prints warnings about [Install] sections. If something still doesn't work as expected, please open a new issue.

FTR, indeed `~/.local/share/` is looked at:
```console
$ systemd-analyze --user unit-paths
/home/zbyszek/.config/systemd/user.control
/run/user/1000/systemd/user.control
/run/user/1000/systemd/transient
/run/user/1000/systemd/generator.early
/home/zbyszek/.config/systemd/user
/etc/systemd/user
/run/user/1000/systemd/user
/run/systemd/user
/run/user/1000/systemd/generator
/home/zbyszek/.local/share/systemd/user  <-----------
/home/zbyszek/.local/share/flatpak/exports/share/systemd/user
/var/lib/flatpak/exports/share/systemd/user
/usr/local/share/systemd/user
/usr/share/systemd/user
/var/lib/snapd/desktop/systemd/user
/usr/local/lib/systemd/user
/usr/lib/systemd/user
/run/user/1000/systemd/generator.late
```
