### ISSUE TITLE
systemd-nspawn --ephemeral does not apply /etc/systemd/nspawn/*.nspawn configuration

### ISSUE THREAD

**Issue by dschepler** [systemd/systemd#13297]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Custom build

**Expected behaviour you didn't see**
 > Bind mounts configured in `/etc/systemd/nspawn/unstable-amd64-sbuild.nspawn` should take effect when running `systemd-nspawn -b -D /var/lib/machines/unstable-amd64-sbuild -x`

**Unexpected behaviour you saw**
 > Bind mounts take effect only when updating the base container image, not when trying to use an ephemeral copy.

**Steps to reproduce the problem**
Used `debootstrap` to create a container image in `/var/lib/machines/unstable-amd64-sbuild` (as a BTRFS subvolume) and added a placeholder directory for `/var/lib/local-apt-repo`.
File `/etc/systemd/nspawn/unstable-amd64-sbuild.nspawn`:
```
[Files]
BindReadOnly=/var/lib/local-apt-repo
```

(To be honest, though, I wasn't sure if this was actually a bug, or if it's by design.  If it *is* by design, then this would be a feature request to make it possible to apply some settings uniformly for all ephemeral containers created from a certain base.  In this particular case, I could work around it by running `machinectl bind` after starting the container; but for other possible settings in the future that wouldn't necessarily be an option.)

**Comment by bluca** [comment]
@dschepler if you pass `--machine unstable-amd64-sbuild` does it work? It works for me on v250:

```
$ sudo cat /run/systemd/nspawn/image.nspawn
[Files]
BindReadOnly=/tmp/foo
$ ls /tmp/foo
bar
$ sudo systemd-nspawn -b --image image.raw -x --machine=image
Spawning container image on /home/luca/git/systemd/.#machine.image.rawdd8cd19ddb5cbbd2.
Press ^] three times within 1s to kill container.
systemd 250 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Debian GNU/Linux bookworm/sid!

<...>

root@image:~# ls /tmp/foo
bar
```

It doesn't work without --machine though

**Comment by bluca** [comment]
This will be why:

> Sets the machine name for this container. This name may be used to identify this container during its
> runtime (for example in tools like machinectl(1) and similar), and is used to initialize the container's
> hostname (which the container can choose to override, however). If not specified, the last component of
> the root directory path of the container is used, **possibly suffixed with a random identifier in case
> --ephemeral mode is selected**. If the root directory selected is the host's root directory the host's
> hostname is used as default instead.

And:

> Files are searched for by appending the .nspawn suffix to the machine name of the container, as specified
> with the --machine= switch of systemd-nspawn, or derived from the directory or image file name.

If you don't specify a machine name, with ephemeral mode there's a random suffix, so the nspawn file name matching will not pick up the config file. Pass `--machine` to fix it.

**Comment by bluca** [comment]
> If it is by design, then this would be a feature request to make it possible to apply some settings uniformly for all ephemeral containers created from a certain base.

If using `--machine` doesn't work for some reason, let me know and I'll reopen as an RFE.

**Comment by bluca** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949843#20

> > As mentioned on https://github.com/systemd/systemd/issues/13297 adding
> > --ephemeral means the machine name has a randomized suffix. Passing --
> > machine=$chroot should ensure the config files are picked up as
> > expected.
> 
> OK, if I did that, then would that mean that it's no longer possible
> to have two sbuild processes using the same base chroot at the same
> time?  (Not that that would be too much of an issue in practice.
> Though I do admit it's convenient to be able to have my micro_buildd
> script running one sbuild instance, while on another terminal I can
> run a manual build with e.g. DEB_BUILD_OPTIONS=nocheck sbuild ...
> --profiles=nocheck tobootstrap_1.0 .)

I guess we should fix it, it makes sense as a use case. PR is open.
