### ISSUE TITLE
systemd-tmpfiles: Support writing to the same file twice

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#13291]
**Is your feature request related to a problem? Please describe.**
I'm using [acpi_call](https://github.com/mkottman/acpi_call) to call ACPI methods, in my case I use it to set a battery maximum charging percentage and changing the fan thermal tipping point to 58 degrees.

systemd-tmpfiles is the obvious choice, but it won't allow me to write to the same path twice (`Duplicate line for path`)

See also (another use-case): https://lists.freedesktop.org/archives/systemd-devel/2018-May/040717.html

**Describe the solution you'd like**

systemd-tmpfiles should be able to write to the same file twice.

**Describe alternatives you've considered**

Creating a systemd service with:
```
StandardOutput=/proc/acpi/call
ExecStart=echo \_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a # Change thermal tipping point to 58 degrees.
ExecStart=echo \_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # Stop charging the battery at 80%
```

**Comment by poettering** [comment]
Note that the tmpfiles.d argument column actually takes C escape sequences, hence you can embedd a newline with `\n`. Isn't that sufficient for your case?

**Comment by klausenbusk** [comment]
> Note that the tmpfiles.d argument column actually takes C escape sequences, hence you can embedd a newline with `\n`. Isn't that sufficient for your case?

It could work, but it is less clear what is going on (2 files (fan.conf & battery.conf) vs 1 file with a long line).

Anyways, I just tried, the following works:
```
echo -e '\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3b\n\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x52' > /proc/acpi/call
```
but the following does not (only first line is passed to /proc/acpi/call):
```
w /proc/acpi/call - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 58 degree / 80%
```

**Comment by poettering** [comment]
hmm,  this really should work.

**Comment by zachsmith** [comment]
I took a look at this and was able to reproduce the `Duplicate line for path` error with the following steps:

1. `echo > /tmp/13291.out`
1. `echo -e 'w /tmp/13291.out - - - - \\\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a' > ~/.config/user-tmpfiles.d/13291.conf`
1. `echo -e 'w /tmp/13291.out - - - - \\\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 58 degree / 80%' >> ~/.config/user-tmpfiles.d/13291.conf`
1. `systemd-tmpfiles --user --create`

> [/home/zach/.config/user-tmpfiles.d/13291.conf:2] Duplicate line for path "/tmp/13291.out", ignoring.

However, I was able to use the work-around that @poettering proposed with the `\n`

1. `echo > /tmp/13291.out`
1. `echo -e 'w /tmp/13291.out - - - - \\\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\\n\\\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 58 degree / 80%\\n' > ~/.config/user-tmpfiles.d/13291.conf`
1. `systemd-tmpfiles --user --create`
1. `cat /tmp/13291.out`

> \_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a
> \_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 58 degree / 80%

Both lines and no `Duplicate line for path` error.

@klausenbusk I haven't tried this with `acpi_call` but I wonder if you could see if this works with a regular file?

I'm using `v241-12` on Fedora 30 but have also run it with `243-154` built locally.

**Comment by klausenbusk** [comment]
> @klausenbusk I haven't tried this with `acpi_call` but I wonder if you could see if this works with a regular file?

I just looked at the `acpi_call` source code and it doesn't [support](https://github.com/mkottman/acpi_call/blob/ac67445bc75ec4fcf46ceb195fb84d74ad350d51/acpi_call.c#L284-L293) multiple "calls" in a single write.

**Comment by klausenbusk** [comment]
> > @klausenbusk I haven't tried this with `acpi_call` but I wonder if you could see if this works with a regular file?
> 
> ~I just looked at the `acpi_call` source code and it doesn't [support](https://github.com/mkottman/acpi_call/blob/ac67445bc75ec4fcf46ceb195fb84d74ad350d51/acpi_call.c#L284-L293) multiple "calls" in a single write.~
> 
> Edit: That doesn't make sense as the following works: `echo -e '\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3b\n\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x52' > /proc/acpi/call`, hmm..

Writing to a normal file works perfectly, but I can't get it to work with `acpi_call`, which is weird as this work: `echo -e '\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3b\n\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x52' > /proc/acpi/call`
```
$ echo -e 'w /proc/acpi/call - - - - \\\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\\n\\\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50\\n' > /etc/tmpfiles.d/acpi_call.conf
$ systemd-tmpfiles --create /etc/tmpfiles.d/acpi_call.conf
$ dmesg
[...]
[212014.318821] ACPI: \_SB.PCI0.LPCB.EC0.WRAM: Excess arguments - Caller passed 4, method requires 2 (20190703/nsarguments-237)
```

**Comment by zachsmith** [comment]
> > Edit: That doesn't make sense as the following works: `echo -e '\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3b\n\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x52' > /proc/acpi/call`, hmm..

So when you run this `echo`, there is no ACPI error and you can see the changes reflected when you `cat /proc/acpi/call`?

**Comment by zachsmith** [comment]
Would you mind trying your multi-line config with the changes in https://github.com/systemd/systemd/pull/13703 to see if that allows you to have multiple lines? Would probably look like this:

```
w+ /tmp/13291.out - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n
w+ /tmp/13291.out - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50\n
```
or 

```
w /tmp/13291.out - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n
w+ /tmp/13291.out - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50\n
```

**Comment by klausenbusk** [comment]
> So when you run this `echo`, there is no ACPI error and you can see the changes reflected when you `cat /proc/acpi/call`?

Correct. I just tried running both programs (`bash` and `systemd-tmpfiles`) with `strace`, and `bash` do the write in two `write` calls, where `systemd-tmpfiles` do the write in a single call.

That would explain why it doesn't work with `systemd-tmpfiles`, as the acpi_call [procfs write callback](https://github.com/mkottman/acpi_call/blob/ac67445bc75ec4fcf46ceb195fb84d74ad350d51/acpi_call.c#L257) is called once per write (I assume).

```
$ strace -s 256 -v bash -c "echo -en '\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50\n' >/proc/acpi/call"
[...]
openat(AT_FDCWD, "/proc/acpi/call", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
fcntl(1, F_GETFD)                       = 0
fcntl(1, F_DUPFD, 10)                   = 10
fcntl(1, F_GETFD)                       = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
dup2(3, 1)                              = 1
close(3)                                = 0
fstat(1, {st_dev=makedev(0, 0x5), st_ino=4026532211, st_mode=S_IFREG|0660, st_nlink=1, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=0, st_size=0, st_atime=1570087686 /* 2019-10-03T09:28:06.604771393+0200 */, st_atime_nsec=604771393, st_mtime=1570088187 /* 2019-10-03T09:36:27.359010262+0200 */, st_mtime_nsec=359010262, st_ctime=1570088187 /* 2019-10-03T09:36:27.359010262+0200 */, st_ctime_nsec=359010262}) = 0
write(1, "\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n", 35) = 35
write(1, "\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50\n", 35) = 35
[...]
$ strace -s 512 -v systemd-tmpfiles --create /etc/tmpfiles.d/acpi_call.conf
[...]
openat(3, "call", O_WRONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 4
write(4, "\\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a\n\\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50", 69) = 69
[...]
```

**Comment by klausenbusk** [comment]
> Would you mind trying your multi-line config with the changes in #13709 to see if that allows you to write multiple lines to `/proc/acpi/call`? Would probably look like this:

Sure, I will test your patch later.

**Comment by klausenbusk** [comment]
> Sure, I will test your patch later.

I can confirm that your patch fix the issue. Tested with:
```
w+ /proc/acpi/call - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x537 0x3a # 58 degree
w+ /proc/acpi/call - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 80%
```

**Comment by zachsmith** [comment]
> Correct. I just tried running both programs (`bash` and `systemd-tmpfiles`) with `strace`, and `bash` do the write in two `write` calls, where `systemd-tmpfiles` do the write in a single call.

I suspected that might be the case.

Thanks for confirming the patch - glad to hear it worked for your use case.
