### ISSUE TITLE
time synchornzation in multiple systems

### ISSUE THREAD

**Issue by harshalkwagh** [systemd/systemd#13293]
First of all this may not exactly a feature request but i need one help related to **timedatectl**.
I search alot on google but did not get satisfactory answer so i thought of rasing issue here.

Lets say I have 2 linux systems, both are in same time zone and both have “**System clock synchronized: yes**” or “**NTP synchronized: yes**” in the output of timedatectl,  does it mean that both the systems will have exact times.

**Comment by poettering** [comment]
Sorry, but this is not a support forum, and the submission form should really should have made this abundantly clear.

This is a bug and feature tracker. Please do not misuse this for anything else, to keep the noise ration low. Thank you for understanding.
