### ISSUE TITLE
Patch for orientation sensor of the Medion Akoya E3221 MD61237

### ISSUE THREAD

**Issue by EtherGraf** [systemd/systemd#13309]
Can someone add this patch to the hwdb/60-sensor.hwdb?
Or do I have to fork the whole repository to generate a pull request?

This patch is tested on real hardware and verified working.

    # Medion Akoya E3221 MD61237
    sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION:pnE3221MD61237:*
     ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1

**Comment by poettering** [comment]
please submit as PR, so that we can properly attribute this to you!
