### ISSUE TITLE
automount units should get after local-fs-pre.target just like mount units

### ISSUE THREAD

**Issue by sjoerdsimons** [systemd/systemd#13306]
**systemd version the issue has been seen with**
> 241
**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Automount unit creates new directory on boot and listens for automouns

**Unexpected behaviour you saw**
 > automount unit fails to start

**Steps to reproduce the problem**

According to the documentation of systemd.automount if the automoint point is automagically created if it doesn't exist yet. This ofcourse means the filesystem underneath has to be writable, which for `/` means not only does -.mount need to be started but also systemd-remount-fs.service has to be run, which isn't guaranteed by the default automount dependencies.

For `.mount` units there is an automatic default `After=` dependency  on `local-fs-pre.target`, would probably make sense to do the same for automount units to avoid it failing on the corner-case where it has to create a directory.

**Comment by poettering** [comment]
yeah, sounds right.
