### ISSUE TITLE
Port from iptables (libiptc) to nftables (libnftl or libnftables)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#13307]
systemd currently uses iptables (via libiptc):
```
src/nspawn/nspawn.c:#if ! HAVE_LIBIPTC
src/test/meson.build:         'HAVE_LIBIPTC'],
src/shared/firewall-util.h:#if HAVE_LIBIPTC
src/shared/meson.build:if conf.get('HAVE_LIBIPTC') == 1
src/core/kmod-setup.c:#if HAVE_LIBIPTC
meson.build:conf.set10('HAVE_LIBIPTC', have)
```
libiptc was never considered an official API but more of an internal implementation detail and there is a push to get everything moved to nftables.
E.g. the latest Debian buster release has nftables as default:
https://www.debian.org/releases/stable/amd64/release-notes/ch-whats-new.en.html#nftables

Mixing iptables with nftables can be problematic according to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934584#15

It seems worthwile getting systemd updated to use nftables instead of iptables.

**Comment by ssahani** [comment]
Yes I agree

**Comment by poettering** [comment]
libiptc has been more stable over decades than many other "stable" libraries I know...

That said, to me it appears nftables is a dead-end. It's clear that something bpf-based is going to win in the end, so why bother with the change to nftables, with the successor already coming along, and having decidedly more "cool" than nftables which is just the same stuff as iptables just a bit warmed up?

Anyway, if anyone preps a patch we'd surely merge it though.

**Comment by dngray** [comment]
I'm curious about this, because it does say https://www.redhat.com/en/blog/using-nftables-red-hat-enterprise-linux-8

> In Red Hat Enterprise Linux 8 the preferred low level firewall solution is nftables. This post is an introduction to using nftables.

Seems like there's also some movement to get Fedora 32 over to nftables https://fedoraproject.org/wiki/Changes/firewalld_default_to_nftables

nftables syntax is a *lot* nicer. From what I can tell eBPF is still a very young project that requires you to [write c-styled programs](https://lwn.net/Articles/740157/) or use some iptables translation tool https://lwn.net/Articles/747551/ the talk about iptables being more widely deployed was in January 2018, so I think this may very well change in the future given the direction Debian 10 and RHEL 8 has taken.

**Comment by Conan-Kudo** [comment]
I've received a report that we've been bitten in some form with this in Mageia 7. FirewallD in nft mode doesn't mix well with networkd-managed interfaces because of the mixture of iptables and nftables... :(

**Comment by dkg** [comment]
I've found on a buster system with no `iptables` installed, but with `nft` installed,  `IPMasquerade=yes` doesn't appear to have any effect, and no warnings are shown in the journal.  ☹ Perhaps there's some problem with detecting failures in `fw_add_masquerade`?

**Comment by Mic92** [comment]
Both [debian](https://wiki.debian.org/nftables#Current_status) and [Fedora](https://fedoraproject.org/wiki/Changes/iptables-nft-default) switched to `iptables-nftables` by default.

**Comment by Mic92** [comment]
Would be calling the `iptables` binary an option? Than both can be supported using the same interface.

**Comment by poettering** [comment]
nah, let's not do shell-out. If everyone switches to nftables, then let's add support for that natively. we don't need particularly complex features from nftables, that should be totally doable...

**Comment by Mic92** [comment]
It is feasible to implement this without any external dependency since it is just netlink under the hood: https://github.com/google/nftables/blob/master/chain.go

**Comment by poettering** [comment]
Of course, if we can use our own sd-netlink API that would be ideal. Given that we only do some minor, simple calls this would be quite doable.

**Comment by mbiebl** [comment]
> That said, to me it appears nftables is a dead-end. It's clear that something bpf-based is going to win in the end, so why bother with the change to nftables, with the successor already coming along, and having decidedly more "cool" than nftables which is just the same stuff as iptables just a bit warmed up?

Might be relevant here: https://lwn.net/Articles/822744/

**Comment by ssahani** [comment]
Subscription required ? hmm

**Comment by mbiebl** [comment]
Does this one work: https://lwn.net/SubscriberLink/822744/8cefc7dcba059079/

**Comment by ssahani** [comment]
yeah thanks !

**Comment by Mic92** [comment]
I think somebody should make fedora and debian aware that they will break systemd's usage of iptables with that. It's not listed here for example: https://fedoraproject.org/wiki/Changes/iptables-nft-default#Dependencies

**Comment by mbiebl** [comment]
@Mic92 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934584
arturo@debian.org, who is the nftables maintainer and driving this change in Debian, commented on that bug report, so should be aware.

**Comment by Conan-Kudo** [comment]
I'm pretty sure that @keszybz informed them accordingly on the Fedora side...
