### ISSUE TITLE
cant start polip start stop web cache plzzz help mee 

### ISSUE THREAD

**Issue by gh4reeb** [systemd/systemd#13315]
useruser@user:~$ sudo systemctl start polipo
Job for polipo.service failed because the control process exited with error code.
See "systemctl status polipo.service" and "journalctl -xe" for details.
useruser@user:~$ sudo journalctl -xe
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit polipo.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Aug 13 18:21:32 user systemd[1]: polipo.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit polipo.service has entered the 'failed' state with result 'exit-code'.
Aug 13 18:21:32 user systemd[1]: Failed to start LSB: Start or stop the polipo web cache.
-- Subject: A start job for unit polipo.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit polipo.service has finished with a failure.
-- 
-- The job identifier is 1933 and the job result is failed.

-------------------------------------------------------------------------------
**systemd version the issue has been seen with**
> ...

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

**Comment by poettering** [comment]
Please contact your distribution for help, or the maintainers of your "polipo" service. systemd is just telling you the service failed, but it's not the one causing it.

**Comment by mbiebl** [comment]
I couldn't find a polipo.service in the Debian archive, so I assume it's either a locally written service file or from a 3rd party package. Contacting Debian in this case will therefor not help much.
