### ISSUE TITLE
rootflags=i_version in cmdine is dropped

### ISSUE THREAD

**Issue by ampresent** [systemd/systemd#13324]
**systemd version the issue has been seen with**
> v242

**Used distribution**
 > CentOS 7u2

**Expected behaviour you didn't see**
 > "rootflags=i_version" in kernel command line take effect and i_version appear in mount option of "/" 

**Unexpected behaviour you saw**
 > i_version didn't appear in mount option of "/"

**Steps to reproduce the problem**
1. Add "rootflags=i_version" to the grub.cfg kernel command line
2. `reboot`
3. check `mount`.
/dev/vda2 on / type ext4 (rw,noatime,data=ordered)
No i_version.
4. Check `dmesg| grep -i mount`

> ...
> [   35.703773] EXT4-fs (vda2): mounted filesystem with ordered data mode. Opts: i_version,data=ordered
> ...
> [   47.663462] EXT4-fs (vda2): re-mounted. Opts: (null)

**More details & clues**

After looking into systemd code, I noticed that `src/remount-fs/remount-fs.c` doesn't specify any options other than `rw` when do_remount. 

And after looking into linux kernel code, I see that `MS_I_VERSION` is part of `MS_RMT_MASK`, which is cleared when not specified explicitly.

I guess that when we specify "rootflags=i_version" in the kernel command line, we expect it actually mounts "/" with i_version flag right ?

**Comment by poettering** [comment]
While in general kernel command line parameters take precedence over configuration file setting, this is not the case for root=/rootflags=/ro/rw on the kernel cmdline. For those the data in /etc/fstab takes precedence, and this is applied in systemd-remount-fs.service. Hence, if you want those flags to be set, make sure this is listed in /etc/fstab.

Yes, this is surprising but is in-line with how this always worked: traditionally "ro" was specified on the kernel cmdline, and then an entry in /etc/fstab remounted the root fs writable.

I figure we should document this exception to the rule better though.

**Comment by wuyihao14** [comment]
It's convincing.

Thanks Poettering.
