### ISSUE TITLE
Allow preset-all to operate on /usr

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#13337]
**Is your feature request related to a problem? Please describe.**
In the build process of my distro, one of the last steps I do before packing up the rootfs is to run this to make sure all of the systemd units that ship with the OS are properly enabled on bootup:
```
systemctl preset-all
systemctl preset-all --global
```
The first command to install/enable all of the system units, and then a second to install/enable all of the user units. The problem is, however, that all of the generated symlinks are put in /etc. This works, but it isn't considered as a system default if the units don't live in /usr/lib.

**Describe the solution you'd like**
A mode for `systemctl preset-all` that operates within `/usr/lib` and deals with both system and user units. Something that looks like this:
```
systemctl preset-all --distributor
```

**Describe alternatives you've considered**
Writing to /etc works fine, but it isn't the correct way to do things.

**Comment by AdrianVovk** [comment]
@refi64 pointed out to me that this could break the ability to disable units. Am I misunderstanding the separation between /usr/lib and /etc in this case? Upon closer inspection it seems that all of the units that are enabled with files in /usr cannot be disabled anyway, and systemd installs some of its units in /etc when I do preset-all.

Is this behavior intended?

**Comment by poettering** [comment]
the preset logic is explicitly just about applying "default" settings to /etc. If you make them to /usr anyway, then there's no point in having presets...

There have been plans in making it possible to enable a unit via /usr/lib in a way that allows masking this enablement via /etc again. But this never was implemented so far.

**Comment by AdrianVovk** [comment]
Alright that clears it up for me. Thank you

Is that plan tracked in another issue? I'm unsure if I should close this one

**Comment by AdrianVovk** [comment]
Alright, I'm closing because my original issue was solved 🙂. Thank you

**Comment by cgwalters** [comment]
See also https://github.com/coreos/fedora-coreos-config/pull/77
