### ISSUE TITLE
Backlight save/load not working

### ISSUE THREAD

**Issue by VichoReyes** [systemd/systemd#13334]
**systemd version the issue has been seen with**
> 242.84-1

**Used distribution**
 > Arch Linux

**Computer**
> Macbook Pro 8.1 IIRC

**Expected behaviour you didn't see**
 > Backlight intensity should be restored when rebooting.

**Unexpected behaviour you saw**
 > It isn't

**Steps to reproduce the problem**
Either reboot or run these commands on my computer:
```
/usr/lib/systemd/systemd-backlight load backlight:intel_backlight
/usr/lib/systemd/systemd-backlight save backlight:intel_backlight
```
With or without sudo, they don't do anything. They return reporting no errors.

Anyway, a short `gdb` fragment that could be useful is attached:
[gdb_fragment.txt](https://github.com/systemd/systemd/files/3511509/gdb_fragment.txt)

**Comment by poettering** [comment]
So it appears you have multiple backlight devices and this one is ignored in favour of the other one?

if you run this on the other one, does it work then?

Also, consider setting the SYSTEMD_LOG_LEVEL=debug env var when invoking these commands, they should tell you more about what they do.

**Comment by VichoReyes** [comment]
> if you run this on the other one, does it work then?

Yes, it does. Sorry for the inconvenience.
