### ISSUE TITLE
Allow to disable kernel-install at compile time

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#13336]
**Is your feature request related to a problem? Please describe.**
I'm building an OSTree-based distro, and running kernel-install can lead to a borked ESP configuration. It would be great to remove it from the system entirely

**Describe the solution you'd like**
A meson option like so:
```
meson build [...] -Dkernel-install=false
```

**Describe alternatives you've considered**
Right now, I just run sed on meson.build to remove `subdir('src/kernel-install')`. But this is very much a hack

**Comment by poettering** [comment]
Implemented in 5fa5c3e2d04622be74d0b7aa199ecdc8a02622fe
