### ISSUE TITLE
HIGH_RLIMIT_MEMLOCK too low for realistic systems

### ISSUE THREAD

**Issue by kainz** [systemd/systemd#13331]
**systemd version the issue has been seen with**
> Seen in systemd 240, systemd 243 will have the same behavior.

**Used distribution**
 > Ubuntu 19.04, also seen in current systemd master

**Expected behaviour you didn't see**
 > Allow setting a maximum memory locked size RLIMIT greater than 64MB

**Unexpected behaviour you saw**
 > Anything controlled by sytstemd setting maximum RLIMIT_MEMLOCK to 64MB.

**Steps to reproduce the problem**
Setup a unit or default LimitMEMLOCK > 64MB. Observe the clamping.

Realistic programs in use today (test case, jackd, osrm-backend) require a greater RLIMIT_MEMLOCK than 64mb.  Maybe this clamp should be configurable, or at least deactivated with an option?

**Comment by kainz** [comment]
FWIW, introduced in c8884aceefc85245b9bdfb626e2daf27521259bd.

**Comment by poettering** [comment]
hu?

this only sets limits for PID 1 itself, since it does cgroups trie stuff, which requires a bumped RLIMIT_MEMLOCK. This should not affect anything down the process tree, as the original rlimit is passed on and LimitMEMLOCK shouldn be unaffected anyway.

**Comment by kainz** [comment]
@poettering actually, I apologise. Upon further inspection, this looks like its a bug in only systemd 240 and was fixed in 241-rc1 with cda7faa9a5ae2fa1ebc27b08e84d5ce62e46e37b.  Prior to that, `systemd --user` was also using setrlimit_closest.

**Comment by shintakezou** [comment]
Any workaround for people stuck with distro-provided systemd 240, beyond lazily waiting for the distro to upgrade it or trying to upgrade it despite what's provided by the distro?

**Comment by kainz** [comment]
> Any workaround for people stuck with distro-provided systemd 240, beyond lazily waiting for the distro to upgrade it or trying to upgrade it despite what's provided by the distro?


@shintakezou this should work on systemd-240, say what's in ubuntu disco LTS and systemd-241, in debian buster today. https://gist.github.com/kainz/9895bc8f2f04eab5c629932c69e2b501

**Comment by shintakezou** [comment]
At last I took [a little longer path](https://askubuntu.com/questions/1150670/how-can-i-upgrade-to-systemd-241-in-disco/1182251#1182251), not the best but gives back control as it should be instead of relying on a now-raised hard-encoded default.

**Comment by bobrik** [comment]
> this only sets limits for PID 1 itself, since it does cgroups trie stuff, which requires a bumped RLIMIT_MEMLOCK.

@poettering, I'm facing the issue when I cannot enable `IPAccounting` because of the log memlock limit for root user (and consequently init process). This may be because we have lots of ebpf maps already.


When I run:

```
sudo systemd-run -p IPAccounting=yes --wait date
```

I can see the following:

```
$ sudo strace -e bpf -yy -p 1
strace: Process 1 attached
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_ARRAY, key_size=4, value_size=8, max_entries=2}, 72) = -1 EPERM (Operation not permitted)
```

And with some tracing I can pinpoint the issue here:

* https://elixir.bootlin.com/linux/v5.4/source/kernel/bpf/syscall.c#L192

```c
static int bpf_charge_memlock(struct user_struct *user, u32 pages)
{
	unsigned long memlock_limit = rlimit(RLIMIT_MEMLOCK) >> PAGE_SHIFT;

	if (atomic_long_add_return(pages, &user->locked_vm) > memlock_limit) {
		atomic_long_sub(pages, &user->locked_vm);
		return -EPERM;
	}
	return 0;
}
```

```
$ sudo perf probe -L bpf_charge_memlock
<bpf_charge_memlock@/cfsetup_build/build/linux-5.4.0/kernel/bpf/syscall.c:0>
      0  static int bpf_charge_memlock(struct user_struct *user, u32 pages)
      1  {
      2         unsigned long memlock_limit = rlimit(RLIMIT_MEMLOCK) >> PAGE_SHIFT;

      4         if (atomic_long_add_return(pages, &user->locked_vm) > memlock_limit) {
      5                 atomic_long_sub(pages, &user->locked_vm);
      6                 return -EPERM;
                }
      8         return 0;
      9  }

         static void bpf_uncharge_memlock(struct user_struct *user, u32 pages)
         {
```

If traced, this fails exactly due to breached 64MiB limit:

```
$ sudo perf probe --add 'bpf_charge_memlock:5 user->uid.val user->locked_vm memlock_limit'
$ sudo perf record -e probe:bpf_charge_memlock -aR
```

```
$ sudo perf script
         systemd     1 [039] 103246.715278: probe:bpf_charge_memlock: (ffffffff83162d26) val=0x0 locked_vm=0x5315 memlock_limit=0x4000
```

0x4000 is the number of pages allowed, which is 16384 pages and 64MiB of memory.

What is the right way to address this?

I think bpf errors should be logged regardless.
