### ISSUE TITLE
networkd v241: default route missing when other address has `PreferredLifetime=0`

### ISSUE THREAD

**Issue by frebib** [systemd/systemd#13341]
**systemd version the issue has been seen with**
> systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

from systemd package in debian `stretch-backports` repository

**Used distribution**
 > debian stretch (with backports). Initially seen on a `debootstrap` generated image running on bare metal with real network interfaces but I can also reproduce in docker containers running stretch, buster and sid.

**Expected behaviour you didn't see**
 > Default route to be added in both cases

**Unexpected behaviour you saw**
 > Default route was missing when `PreferredLifetime=0` was added to an unrelated address on the same interface. This did not happen in v239 on the same Debian image

**Steps to reproduce the problem**
This is the minimum I could do to reproduce the issue. Note that here I am using a `bridge` but we first noticed the same behaviour on `vlan` interfaces when running on bare metal. I used Docker to demonstrate this, but it happens the same on pretty much any platform

Dockerfile: https://gist.github.com/frebib/95a3bc1c180447549257dcaa7f1ed57b/raw
Docker run: `docker run --rm -dti --name=networkd-test --privileged --security-opt seccomp=unconfined -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $PWD/network:/etc/systemd/network frebib/systemd:sid`

`bind.network`:
```ini
[Match]
Name=eth*

[Network]
Bridge=net0
```

`net0.netdev`:
```ini
[NetDev]
Name=net0
Kind=bridge
```

`net0.network`:
```ini
[Match]
Name=net0

[Network]
# Work around https://github.com/systemd/systemd/issues/12784
LinkLocalAddressing=no

[Route]
Gateway=20.20.20.1

[Address]
Address=20.20.20.100/24

[Address]
Address=40.40.40.100/24
#PreferredLifetime=0
```

### Without `PreferredLifetime=0`
There is a default route added here as you would expect
networkd debug logs: https://gist.github.com/frebib/a7484747fe1056a8dbe6f49113b0bc75/raw
```
root@e9b1479b0efc:/# ip addr show dev net0
2: net0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:15:6d:d7:aa:fd brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.100/24 brd 20.20.20.255 scope global net0
       valid_lft forever preferred_lft forever
    inet 40.40.40.100/24 brd 40.40.40.255 scope global net0
       valid_lft forever preferred_lft forever

root@e9b1479b0efc:/# ip ro show dev net0
default via 20.20.20.1 proto static
20.20.20.0/24 proto kernel scope link src 20.20.20.100
40.40.40.0/24 proto kernel scope link src 40.40.40.100

root@e9b1479b0efc:/# networkctl status net0
* 2: net0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/net0.network
            Type: bridge
           State: routable (configured)
          Driver: bridge
      HW Address: 72:15:6d:d7:aa:fd
         Address: 20.20.20.100
                  40.40.40.100
         Gateway: 20.20.20.1
```

### With `PreferredLifetime=0`
The default route is now missing, and networkd seems to be waiting for something, note `(configuring)` state.
networkd debug logs: https://gist.github.com/frebib/9df21b551cdb197774d51f61539d7b20/raw
```
root@c555f11f732e:/# ip addr show dev net0
2: net0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:15:6d:d7:aa:fd brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.100/24 brd 20.20.20.255 scope global net0
       valid_lft forever preferred_lft forever
    inet 40.40.40.100/24 brd 40.40.40.255 scope global deprecated net0
       valid_lft forever preferred_lft forever

root@c555f11f732e:/# ip ro show dev net0
20.20.20.0/24 proto kernel scope link src 20.20.20.100
40.40.40.0/24 proto kernel scope link src 40.40.40.100

root@c555f11f732e:/# networkctl status net0
* 2: net0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/net0.network
            Type: bridge
           State: routable (configuring)
          Driver: bridge
      HW Address: 72:15:6d:d7:aa:fd
         Address: 20.20.20.100
```

**Comment by yuwata** [comment]
Please enable debug logs. By creating the following drop-in config, you can get the debugging logs. 
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by frebib** [comment]
@yuwata Debug logs are already attached via gist links

**Comment by yuwata** [comment]
Oh, Thanks.

**Comment by yuwata** [comment]
Fix is waiting in #13345.

**Comment by ssahani** [comment]
What it's the use case of setting `PreferredLifetime=0`.  networkd has the right behaviour now .  `PreferredLifetime=0` should not be treated as a valid address and that leads to interface ready.

**Comment by keszybz** [comment]
> What it's the use case of setting `PreferredLifetime=0`

It gives an address that is valid, but immediately deprecated. I think the PR does the most reasonable thing, i.e. allows this to work as expected.
