### ISSUE TITLE
`systemd-run --scope` should not require password

### ISSUE THREAD

**Issue by Hi-Angel** [systemd/systemd#13340]
**Is your feature request related to a problem? Please describe.**

As a user, you may want to run an app with constrained access to resources you own. For example:

```haskell
$ systemd-run --scope -p MemoryLimit=1G firefox
```

Here, it doesn't make sense to require authentification from the user, because user owns all of its memory and is able to run Firefox. The user simply wants to limit resources before running an app, which is a rational thing to do, and should not require a root password.

Another problem is, such approach is prone to mistakes when the user gonna decide to run the code above with `sudo` — which sure not what they wanted, because that would start `firefox` as a root, not as the user.

**Describe the solution you'd like**

Do not ask for password.

**Describe alternatives you've considered**

I tried to pass `--no-ask-password` explicitly, to no avail:

```haskell
$ systemd-run --no-ask-password --scope -p MemoryLimit=1G firefox
Failed to start transient scope unit: Interactive authentication required.
```

**Comment by Hi-Angel** [comment]
Another ⁺¹ to the report: password requirement interfere with non-interactive usage *(e.g. for unit-testing purposes)*, like for example [in this question](https://unix.stackexchange.com/q/44985/59928#limit-memory-usage-for-a-single-linux-process) which has 215k views at this point.

**Comment by Hi-Angel** [comment]
Found a workaround: if I pass `--user`, it does not ask for password:

```bash
$ systemd-run --user --scope -p MemoryLimit=1G firefox
```

**Comment by Hi-Angel** [comment]
Nvm: `--user` option is broken. I [reported a bug about it](https://github.com/systemd/systemd/issues/13347).

**Comment by boucman** [comment]
well systemd-run --scope is handled by the system version of systemd which is privileged, so it makes sense to ask for a password. so the correct answer to this bug is probably "try with --user" which you did.

so I guess this bug can be closed (this doesn't mean that your other bug should be closed, though, just the fact that systemd-run --scope requires a password)

**Comment by Hi-Angel** [comment]
I see, you're probably right.
