### ISSUE TITLE
systemctl clean does not clean private directories but it does clean symlinks to them

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13355]
**systemd version the issue has been seen with**
> ... 243rc1

**Used distribution**
 > …Fedora Rawhide

**Expected behaviour you didn't see**
 > …no cleaning of /var/lib/private/myapp

**Unexpected behaviour you saw**
 > …cleaning of /var/lib/myapp (symlink)

**Steps to reproduce the problem**
systemd-run -p DymanicUser=yes -p User=joe -p CacheDirectory=joe /usr/bin/bash -c 'echo joe > /var/cache//joe/joe'
systemctl clean
ls /var/cache/joe /var/cache/private/joe

**Comment by yuwata** [comment]
Fix is waiting in #13385.
