### ISSUE TITLE
Permissions on nodes created by systemd-tmpfiles-setup-dev.service don't match udev rules

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#13350]
From https://bugzilla.redhat.com/show_bug.cgi?id=1740664:

```console
$ ls -l /dev/net/tun
crw-------. 1 root root 10, 200 Aug 18 13:06 /dev/net/tun
$ modprobe -v tun
insmod /lib/modules/5.3.0-0.rc4.git1.1.fc32.x86_64/kernel/drivers/net/tun.ko.xz 
$ ls -l /dev/net/tun
crw-rw-rw-. 1 root root 10, 200 Aug 18 13:16 /dev/net/tun
```

/dev/net/tun is created by systemd-tmpfiles-setup-dev.service, based on information generated by `kmod static-nodes --format=tmpfiles`. `kmod` always uses 0600:
```console
kmod static-nodes --format=tmpfiles | grep tun
c! /dev/net/tun 0600 - - - 10:200
```

*If* the permissions on /dev/net/tun were 0666, any user could trigger autoloading of /dev/net/tun. But since the permissions are restrictive, this is only works for root.
The same problem occurs for e.g. /dev/fuse, /dev/btrfs-control, /dev/loop-control, /dev/snd/timer, /dev/snd/seq, where the "final" permissions are different from the kmod default.

I don't have a nice way how to solve this. We can't set the options initially permissive and wait for udev to make them stricter, because that would allow users to open the device when they shouldn't be allowed to. Forcing the loading of all modules for those nodes also seems wasteful. Maybe we could teach udev a mode where it spits out the desired mode of a path, even though the device doesn't exist as far as udev is concerned. Or maybe we could simply override the mode for the few static nodes that need this. This last option is not very elegant, but since we're talking about just a handful on nodes for which we provide explicit configuration in `50-udev-default.rules` anyway, maybe that'd be the best option. Ideas?

**Comment by boucman** [comment]
could tmpfiles "trigger udev" somehow with the node name and let udev do the creation ?

it could resort to its own permissions if, after the udev run, no device is created...

**Comment by keszybz** [comment]
> could tmpfiles "trigger udev" somehow with the node name and let udev do the creation ?

The is no node in sysfs, so we'd need to add a full new codepath to handle this. And udev needs to be running already, etc. Seems like a bit effort, and the result wouldn't be particularly elegant anyway.

**Comment by poettering** [comment]
mm, maybe not solve this at all, but find a nice way to allow packages to override tmpfiles.d/ lines created for this, so that people in addition to a udev rules file drop in a tmpfiles snippet that matches the same config?

**Comment by keszybz** [comment]
Well, *we* are the packagers in this case. kmod doesn't know the device names and numbers, but has nothing to say about permissions. The permissions are configured by us in udev rules.

> Or maybe we could simply override the mode for the few static nodes that need this.

After writing out this ticket in full I'm leaning fowards this. I'll submit a PR so we can see if it is very inelegant.

**Comment by poettering** [comment]
hmm, is there an actual usecase for this? i.e. where people ran into this problem? some device node that should be accessible to unpriv stuff, but isn't right now. The tun stuff doesn't appear to be one of those?

**Comment by keszybz** [comment]
I think it's is a valid concern. For example, I can legitimately use `/dev/kvm` as a normal user. If `kvm` is configured as a module, and if I don't have libvirtd started at boot, I might see /dev/kvm with wrong permissions. I suppose people don't notice this too much because stuff is often loaded by the time users are logged in, and even if they notice, they do `modprobe` to "fix" the issue.

**Comment by poettering** [comment]
ok, kvm is a good reason.

**Comment by doverride** [comment]
> hmm, is there an actual usecase for this? i.e. where people ran into this problem? some device node that should be accessible to unpriv stuff, but isn't right now. The tun stuff doesn't appear to be one of those?

Yes /dev/use (sshfs for example, but theres also other fuse scenarios)

https://bugzilla.redhat.com/show_bug.cgi?id=1734831#c23

**Comment by poettering** [comment]
ok, /dev/fuse is also a good reason
