### ISSUE TITLE
Before= dependencies on device units not respected

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#13362]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Fedora 30

**Expected behaviour you didn't see**
 > If a unit has a `Before=` dependency on a device unit, it shows up in `systemctl show`, and the device unit does not start until after the unit it depends on.

**Unexpected behaviour you saw**
 > `Before=` dependencies on device units are ignored.

**Steps to reproduce the problem**
Create a unit with a `Before=` dependency on a device unit.

This must be fixed before #10179 can be properly fixed.

**Comment by boucman** [comment]
I'm not sure I understand... .device units represent the physical presence of hardware. How could systemd start a unit Before= a hardware is plugged... when systemd is called by udev, the hardware is already there...

the device-unit itself could transition to "started" only once the other unit is started, but that would be a lie, since the unerlying hardware is already there.

**Comment by keszybz** [comment]
Before= is not support for device units. As @boucman said, .device units mirror the hardware state and cannot be delayed.

**Comment by DemiMarie** [comment]
@keszybz I would argue otherwise, due to udev’s `SYSTEMD_READY` concept.  Some devices, such as encrypted swap or tmp partitions, require userspace programs to be executed before they can be fully operational.

**Comment by mbiebl** [comment]
Related to this bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854697#21

**Comment by keszybz** [comment]
When SYSTEMD_READY=0 is set, systemd thinks the device doesn't exists.

>  the documentation does not mention that Before= dependencies on device units are not respected, and systemd issues no warning. I would consider at least the first to be a bug.

Hmm, if that's true, we need to fix that. I think we had something in the docs, but I'm too lazy to look it up now.

**Comment by boucman** [comment]
> When SYSTEMD_READY=0 is set, systemd thinks the device doesn't exists.
> 
does it ?  I thought i created the device but left it in the "starting" phase...
