### ISSUE TITLE
Don't assume gnu-efi is installed in /usr/

### ISSUE THREAD

**Issue by rossburton** [systemd/systemd#13371]
When cross-compiling systemd you really don't want to use anything from the host, but systemd's gnu-efi search defaults explicitly to `/usr/include/efi`.  As this can silently pick up the host gnu-efi (and either use it if it's binary compatible, or fail to link if it isn't) it might be better to use whatever the configured `includedir` is?

**Comment by keszybz** [comment]
We (the upstream developers) don't do much crosscompilation. Please provide a patch that does what is appropriate, we'll be happy to merge it.

**Comment by poettering** [comment]
is this still relevant? otherwise we should probably just close it

**Comment by rossburton** [comment]
Yes, I just need to get around to fixing it.

**Comment by Newbytee** [comment]
I think this is obsoleted by https://github.com/systemd/systemd/commit/5080a60a719da213fa90964b76cc90bd0d1cb8de

**Comment by YHNdnzj** [comment]
Let's close this then.

**Comment by rossburton** [comment]
Indeed it is.  For reference, why the desire to move away from gnu-efi?

**Comment by YHNdnzj** [comment]
> Indeed it is. For reference, why the desire to move away from gnu-efi?

Some comprehensive explanation can be found in https://github.com/systemd/systemd/pull/26097#issuecomment-1425969213
