### ISSUE TITLE
systemd[1]: ssss.service: Main process exited, code=killed, status=15/TERM

### ISSUE THREAD

**Issue by celcan** [systemd/systemd#13372]
**systemd version the issue has been seen with**
> v242

**Used distribution**
 > …

**Expected behaviour you didn't see**
 >All services to be terminated in time

**Unexpected behaviour you saw**
 > Main process exited, code=killed, status=15/TERM

**Steps to reproduce the problem**
Every time, after reboot the target

More detail

We have started to get this warning message from systemd for bunch of services during the termination process. We were not getting same messages while we were using v239. It has started to shown after v242 upgrade. Here are the systemd directive that we are using:
KillMode=control-group (it is written that is used as default on systemd doc.)
ExecStop option is not being used
Even though we have changed the TimeoutStopSec and DefaultTimeoutStopSec as 90sec, we are still seeing those warning messages. If we look at our side, we did not change any service configuration. I have also investigated the systemd side whether something has been changed or not regarding that option, but as far as I can see nothing had been changed. For now we are trying to understand why these related services have started to go over the timeout. Does anyone know why we are getting this warning and how to solve?

**Comment by poettering** [comment]
these aren't warning messages. They just say that the main process of that service exited after we killed it with SIGTERM. That's a clean error, we just log about it at LOG_DEBUG or LOG_NOTICE log level. 

On UNIX SIGTERM is generally the friendly way how to ask a process to exit, and that's what we call. The message shows that the process reacted to that and simply terminated.

This is hence not a bug.

**Comment by keszybz** [comment]
I think we should downgrade the log message though. It *looks* like a warning because of the elevated priority. I'll submit a patch.

**Comment by celcan** [comment]
Thanks for fast reply. For now we don't need to care those warning messages right? As you said those messages are going to be downgraded with a new patch.

**Comment by keszybz** [comment]
Yes.
