### ISSUE TITLE
AfterInactive=

### ISSUE THREAD

**Issue by xnoreq** [systemd/systemd#13386]
**Is your feature request related to a problem? Please describe.**
Consider two simple services A and B.

B.service has `WantedBy=A.service` but should only start when A has gone *inactive*.
Setting `After=A.service` will start B immediately after A has started which is not what I want.

Currently there does not seem to be a sane way to do this:
- either A.service has to be modified to start an extra A-inactive.service using `ExecStopPost` with B.service starting `After=A-inactive.service`

- or A.service has to be modified and changed into a `Type=oneshot` which is a hack at best

**Describe the solution you'd like**
`AfterInactive=`
With this, A.service does not have to be modified, B.service can simply set `AfterInactive=A.service`.

Now if A starts B will not start until A has gone inactive.

**Describe alternatives you've considered**
The alternatives are explained in the first section. They're hacks.
But maybe there are other alternatives?

**Comment by boucman** [comment]
I think you could do that with OnSuccess and OnFailure in A....

**Comment by xnoreq** [comment]
> I think you could do that with OnSuccess and OnFailure in A....

I am not aware that "OnSuccess" or "OnFailure" exists. Anyway, how would it be different from the `ExecStopPost` hack?
It's a hack because it hides dependencies from systemd and doesn't allow configuring it in reverse (by only modifying B).

I also consider `Type=oneshot` a hack because it is technically wrong to treat a service's running process as just "activating" and once the service's process has terminated as "active".

`AfterInactive=` would allow to do away with all of these and do it properly.

**Comment by boucman** [comment]
OnFailure is pretty old, OnSuccess has been added recently. These are dependencies, i.e they should be set to unit names that systemd will start

ExecStopPost is a command to run in the context of the unit in which it is declared.

And if A is a short-lived unit that is meant to be waited on,  setting A as a oneshot is not a hack... it's exactly what onshot services are meant to be...

I'm not a core-dev anyway, so my opinion doesn't matter much... I'm just trying to figure out if what you want is already doable, how much of a hack it currently is and thus what exactly is the missing brick in systemd's dependency tools

**Comment by xnoreq** [comment]
Is there a reverse OnFailure/Success like AfterFailure and AfterSuccess?

That would be what I'm looking for just more granular than a single
AfterInactive.

>

**Comment by boucman** [comment]
revers in the way Wants/WantedBy are reverse ? no, there is no such thing. 
WantedBy/RequiredBy are special cases, but most dependencies don't have a reverse, you use drop-ins on the other unit if you need the modularity...

**Comment by xnoreq** [comment]
> WantedBy/RequiredBy are special cases, but most dependencies don't have a reverse, you use drop-ins on the other unit if you need the modularity...

That's not right. systemd.unit man page contains a large table describing "forward" properties and their "reverse" counterparts. Before, After, Requires, Wants, PartOf, BindsTo, Requisite, Triggers etc. all have "reverse" properties.

And what do you mean by "you use drop-ins"?
Do you mean starting a dummy A-inactive.service?

**Comment by boucman** [comment]
that table are reverses that can't be set in units. They can only be read with "systemctl show" (that part of the man page might not be as clear as it should it's a new section)

and drop-ins are documented in man:systemd.unit they are files named *.conf in A.service.d/ directory that contain extra parameters that are appended to A.service.

In your case you would have B add a file for A at install time

**Comment by xnoreq** [comment]
> that table are reverses that can't be set in units. 

What are you talking about? Service files contain a [Unit] section that is used to specify `Before=`, `Requires=`, `Conflicts=` etc. or any of their "reverse" counterparts.

**Comment by boucman** [comment]
I'm pretty sure you can't set a "BoundBy" in a unit file... and the paragraph just above that table seems to agree with me...

**Comment by xnoreq** [comment]
> Note: ConsistsOf=, BoundBy=, RequisiteOf=, ConflictedBy= are created
implicitly along with their reverse and cannot be specified directly.

Boucman <notifications@github.com> schrieb am Mo., 26. Aug. 2019, 07:25:

**Comment by boucman** [comment]
Yes, that's what I mean.... you can't put BoundBy= in a unit file, you can only specify BindsTo= on the other unit and the BoundBy will be added implicitely

We probably just don't understand each other here...

**Comment by poettering** [comment]
what's the usecase for this? Why isn't Type=oneshot the right approach here?

**Comment by JojOatXGME** [comment]
@boucman, where did you find `OnSuccess`? I can neither find it in [the documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) nor in [the source code on GitHub](https://github.com/systemd/systemd/search?q=OnSuccess&unscoped_q=OnSuccess).
