### ISSUE TITLE
udevadm control --reload fails

### ISSUE THREAD

**Issue by san-sang** [systemd/systemd#13390]
**systemd version the issue has been seen with**
> ...
242.84-2

**Used distribution**
 > …
Arch Linux updated
**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …
```
# udevadm control --reload
Assertion 's' failed at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:1688, function sd_event_source_set_description(). Ignoring.
```
**Steps to reproduce the problem**
Not sure what causes this error. The error persists after system reboot and restarting systemd-udevd.

**Comment by yuwata** [comment]
Already fixed by 60ccab093e175f77f72f57eae59c8d0d1628d012.
