### ISSUE TITLE
Failed to start Load/Save screen brightness of backlight:intel_brightness. Any fix please?

### ISSUE THREAD

**Issue by rac-sri** [systemd/systemd#13394]
systemd-backlight@backlight:intel_backlight.service - Load/Save Screen Backlight Brightness of backlight:intel_backlight
   Loaded: loaded (/lib/systemd/system/systemd-backlight@.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-08-20 22:36:17 IST; 1h 40min ago
     Docs: man:systemd-backlight@.service(8)
  Process: 380 ExecStart=/lib/systemd/systemd-backlight load backlight:intel_backlight (code=exited, status=1/FAILURE)
 Main PID: 380 (code=exited, status=1/FAILURE)

**Comment by poettering** [comment]
Closing, the issue submission form was not filled in. please try again. Also provide logs, if possible debug logs.
