### ISSUE TITLE
nspawn fails with Failed to chown() cgroup in Fedora Docker container

### ISSUE THREAD

**Issue by sirredbeard** [systemd/systemd#13400]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > fedora:latest Docker image

**Expected behaviour you didn't see**
> Called systemd-nspawn: 
```
sudo systemd-nspawn --register=no --keep-unit -q -D ./dist /bin/bash << EOF
dnf -y reinstall crypto-policies --exclude=grub\*,dracut*,grubby,kpartx,kmod,os-prober,libkcapi*
dnf -y autoremove
dnf -y clean all
EOF
```
> Should have executed bash script inside ./dist without issue.

**Unexpected behaviour you saw**
 > Received error:
```
Failed to chown() cgroup /sys/fs/cgroup/systemd/azpl_job/f3e009088d7ae151c04ad40cc9f19addb7dc1a5dca6261bef78acd0c3c1f97d3/azpl_job/f3e009088d7ae151c04ad40cc9f19addb7dc1a5dca6261bef78acd0c3c1f97d3/payload: No such file or directory
Attempted to remove disk file system under "/run/systemd/nspawn/propagate/dist", and we can't allow that.
```

**Steps to reproduce the problem**
1. Run clean Fedora 30 install
1. `sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo`
1. `sudo dnf install docker-ce docker-ce-cli containerd.io`
1. `sudo systemctl start docker`
1. `docker pull fedora:latest`
1. `docker run -ti --privileged fedora`
1. `sudo dnf -y install qemu-user-static git systemd systemd-container`
1. `mkdir dist`
1. `sudo dnf install --releasever=30 --installroot=$(pwd)/dist --forcearch=x86_64 --repo=fedora --repo=updates -y generic-release dnf systemd passwd nano bash coreutils dbus-daemon`
1.`sudo systemd-nspawn --register=no --keep-unit -q -D ./dist /bin/bash echo 'hello world'`

Results:
```
[root@e5983cae44a5 /]# sudo systemd-nspawn --register=no --keep-unit -q -D ./dist /bin/bash echo 'hello world'
Failed to chown() cgroup /sys/fs/cgroup/systemd/docker/e5983cae44a516d2045d88229b7c3f95dbd5ef694697abd2c2528215a14bbfd8/docker/e5983cae44a516d2045d88229b7c3f95dbd5ef694697abd2c2528215a14bbfd8/payload: No such file or directory
Attempted to remove disk file system under "/run/systemd/nspawn/propagate/dist", and we can't allow that.
```

**Comment by poettering** [comment]
afaik docker is not setting up cgroupfs correctly in a way that would allow systemd to run as PID 1 in it. i.e. /run needs to be a tmpfs, and /proc/$PID/cgroup  and /sysf/fs/cgroup must have congruent information. 

Please work with the docker communities to fix this. The execution environment systemd expects is documented here:

https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/

Anyway, let's close this here, as we can't do anything about the borked way docker sets up the execution environment. Sorry!

**Comment by sirredbeard** [comment]
Interesting. Thank you.
