### ISSUE TITLE
Add syntax highlighting to "systemctl cat"

### ISSUE THREAD

**Issue by thaygiaoth** [systemd/systemd#13416]
When I run

systemctl cat systemd-sysctl.service

--> there is no output color

I want display output color same as vim editor

vim /lib/systemd/system/systemd-sysctl.service

Thanks

**Comment by poettering** [comment]
you mean, as in syntax highlighting? hmm, uh. maybe using `bat` is what you want? i.e. PAGER=bat? it currently doesn't have syntax highlighting for systemd unit files, but sounds like something they might be interested in to add?

**Comment by thaygiaoth** [comment]
yes, it will more easier to see

![image](https://user-images.githubusercontent.com/10233106/63906084-9b13e200-ca40-11e9-94ea-4fdc0356cc8d.png)

![image](https://user-images.githubusercontent.com/10233106/63906096-abc45800-ca40-11e9-9574-d17e1361913e.png)
