### ISSUE TITLE
journald: SystemMaxUse / SystemKeepFree settings do not affect persistent storage

### ISSUE THREAD

**Issue by gpomykala** [systemd/systemd#13410]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > ptxdist

**Expected behaviour you didn't see**
 > I expected that SystemMaxUse / SystemKeepFree will be effective on persistent storage (/var/log/journal). I would also expect that journalctl --rotate would trigger persistent storage rotation, but only runtime log is affected:
```
root@Test3:~ journalctl --rotate
Aug 27 08:09:43 Test3 systemd-journald[32118]: Runtime journal (/run/log/journal/de6ef081f0fe209c0bf11c7600ddca5a) is 1.0M, max 1.0M, 0B free.
```
On the other hand journalctl --vacuum-size does work as expected.

**Unexpected behaviour you saw**
 > journald keeps to write to persistent storage until whole log partition is filled (0 bytes free)

**Steps to reproduce the problem**

journald.conf:
```
[Journal]
Storage=persistent
#Compress=yes
#Seal=yes
#SplitMode=login
#RateLimitInterval=10s
#RateLimitBurst=200
SystemMaxUse=100M
SystemKeepFree=20M
#SystemMaxFileSize=
#SystemMinFileSize=
RuntimeMaxUse=1M
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMinFileSize=
#ForwardToSyslog=yes
#ForwardToKMsg=no
#ForwardToConsole=no
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info

root@Test3:~ df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/mmcblk1p6          232.0M    226.9M         0 100% /var/log

root@Test3:~ du -h /var/log/journal/
226.7M  /var/log/journal/de6ef081f0fe209c0bf11c7600ddca5a
226.7M  /var/log/journal/
```

**Comment by jklare** [comment]
It looks like i have run into a similar issue. Which values did you end up using ? Did you find any explanation why smaller/larger values workaround this issue?
