### ISSUE TITLE
Automatic multiseat for Plugable UD-Pro8 docking station

### ISSUE THREAD

**Issue by ezst036** [systemd/systemd#13427]
When I plug in a UD-Pro8 (USB 2.0) docking station, I would like for multiseat rules to automatically create a seat the same way they currently do for Plugable's other USB 2.0 docking devices such as a UD-160-M.

**Comment by poettering** [comment]
Well, then send a patch for 71-seat.rules as PR, that adds this. look at the existing Plugable rule, and extend it for your device.

Since we have no such device, there's little we can do from our side, we rely on patches for this.

**Comment by ezst036** [comment]
Thank you for letting me know what file in which this change would need to be made.  I created a small commit ( #14516) that covers this functionality, this request can probably be closed.

**Comment by poettering** [comment]
Closing, since #14516 has been merged.
