### ISSUE TITLE
systemd-detect-virt does not work in current installation.

### ISSUE THREAD

**Issue by janLo** [systemd/systemd#13429]
**systemd version the issue has been seen with**
242

**Used distribution**
Debian (testing)

**Expected behaviour you didn't see**
Relieable detection of Oracle VirtualBOX

**Unexpected behaviour you saw**
Virtualization got detected as KVM
```
# systemd-detect-virt 
kvm
```

**Steps to reproduce the problem**
* Install VirtualBOX
* install a distribution using systemd
* call `systemd-detect-virt`

The current version of VirtualBOX gives "Oracle Corporation" instead of "innotek GmbH" as BoardVendor. The code only looks for the latter: https://github.com/systemd/systemd/blob/master/src/basic/virt.c#L148. All the other Vendors (sys_vendor and bios_vendor) are passend through from the host:
```
# cat /sys/class/dmi/id/{product_name,sys_vendor,board_vendor,bios_vendor}
20N2S00600
LENOVO
Oracle Corporation
LENOVO
```

Ths causes the detection to fail.

**Comment by marcosfrm** [comment]
Arch (systemd 242.84-2, linux 5.2.9.arch1-1) under VirtualBox 6.0.10 running on Windows 10 Host:

```
# systemd-detect-virt
oracle

# cat /sys/class/dmi/id/{product_name,sys_vendor,board_vendor,bios_vendor}
VirtualBox
innotek GmbH
Oracle Corporation
innotek GmbH
```

I think (they use SVN for God's sake...) these defaults did not change since a long time:

https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Devices/PC/DevFwCommon.cpp
