### ISSUE TITLE
Support IPv6 Prefix Delegation and Multi-Addressing Models

### ISSUE THREAD

**Issue by HLFH** [systemd/systemd#13422]
Hi,

**Is your feature request related to a problem? Please describe.**
I have a IPv6 /48 prefix provided by my Online.net Local Internet Registry (LIR) with a /56 subnet dedicated to my main server. Between the LIR and my name servers, I have correctly set up the IPv6 reverse delegation.

Most of its dedicated server offers before 2016 do not support IPv6 SLAAC and we need to use DHCPv6 Prefix Delegation.
There is no downstream available interface, only _eno1_ interface is available for IPv4 & IPv6. So the Classic Routing Model with upstream and downstream interface cannot apply. 

<img width="555" alt="classic routing model" src="https://user-images.githubusercontent.com/2359059/63878009-9ad40200-c9c0-11e9-9dc0-5acabcde4454.png">     

**Describe the solution you'd like**
We definitely need IPv6 Prefix Delegation for Hosts That Act Like Routers, and systemd-networkd does not seem to support the Internet Draft **[IPv6 Prefix Delegation and Multi-Addressing Models](https://tools.ietf.org/html/draft-templin-v6ops-pdhost-24)** version 24. Especially explained in the _Figure 3: Upstream Interface Address Assignment_, where in this second alternative, the Requesting node could assign IPv6 addresses taken from the Prefix to the upstream interface over which the prefix was received.

<img width="437" alt="upstream interface address assignment" src="https://user-images.githubusercontent.com/2359059/63878038-a6bfc400-c9c0-11e9-9db0-f28a79f773a5.png">

Many thanks,
HLFH

**Comment by yuwata** [comment]
Sorry for late response. Could you provide an example .network setting?

**Comment by yuwata** [comment]
@ssahani Do you have any idea?

**Comment by ssahani** [comment]
@yuwata I am now travelling. I will see this on Tuesdays.

**Comment by Toniob** [comment]
Here is an example
```
# dummy.netdev
[NetDev]
Name=dummy0
Kind=dummy
```
```
# dummy.network
[Match]
Name=dummy0
[Network]
IPv6PrefixDelegation=dhcpv6
```
```
# enp1s0.network
[Match]
Name=enp1s0
 
[Network]
DHCP=ipv6
IPv6AcceptRA=True
# ns2.6clones.net
Address=x.x.x.x/32
# ns2.6clones.net
Address=xxxx:xxxx::xxxx/128

[Route]
Gateway=62.210.0.1
GatewayOnlink=yes

[DHCP]
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=xx:xx:xx:xx:xx:xx:xx:xx
ForceDHCPv6PDOtherInformation=yes
UseDNS=False
UseDomains=False

[IPv6AcceptRA]
UseDNS=False
UseDomains=False
UseOnLinkPrefix=False
UseAutonomousPrefix=False
```

I have to add the dummy interface if I want to trigger the start of the dhcpv6 client on enp1s0. We shouldn't need it.

**Comment by Shot2** [comment]
> I have to add the dummy interface if I want to trigger the start of the dhcpv6 client on enp1s0. We shouldn't need it.

Apparently the dummy interface is not always required - on vanilla Debian Buster's systemd 2.41, adding the 'IPv6PrefixDelegation=dhcpv6' stanza within the e.g. eno0 .network is enough to gain functional IPv6.

Also note that in such a case, even if everything works as expected, the connection remains in a "routable (configuring)" state forever as reported by networkctl status.

**Comment by albertofustinoni** [comment]
@Toniob I am also on Online.net and have been trying for days to get IPv6 working without any luck.

In my case the DHCPv6 client never gets started and does not request a prefix delegation, killing IPv6 connectivity.

I have the dummy netdev and network configured exactly like you, as well as an identical physical interface config (save for IP addresses and gateway).

What are you running? I'm on Ubuntu 20.04.

**Comment by albertofustinoni** [comment]
@Shot2 I have the same config as OP and my enp0 interface is stuck as "routable (configuring)" WITH a dummy interface. Is that the same for you?

**Comment by HLFH** [comment]
@albertofustinoni As [specified here](https://www.scaleway.com/en/docs/dedibox-network/ipv6/how-to/configure-ipv6-networkd/), maybe you forgot to remove "00:03" at the beginning of your Online.net DUID in the `DUIDRawData` line.

@Shot2 I'm checking now if I arrive to make it work without the dummy interface as well on my main `eno1` network. I removed the dummy interface and it seems to work.
```
[Match]
#The name must correspond to your interface name
Name=eno1
[Network]
DHCP=ipv6
IPv6AcceptRA=True
IPv6PrefixDelegation=dhcpv6
[...]

**Comment by HLFH** [comment]
DHCPv6 does not work well with `systemd-networkd`.
I have migrated to [`dhcpcd`](https://roy.marples.name/projects/dhcpcd).

As many commenters of this issue were using a Dedibox on the Scaleway network, here is my PR related to `dhcpcd`: https://github.com/scaleway/docs-content/pull/1919

**Comment by Shot2** [comment]
DHCPv6 now works fine with systemd ≥252, also with Online/Scaleway - dhclient or dhcpcd are thus no longer needed.

**Comment by HLFH** [comment]
@Shot2 Your configuration did not work for me and is kind of breaking my network :) [Let's follow the conversation here](https://github.com/scaleway/docs-content) where you can submit a feature request issue and a PR if you fully solved it ; the idea is to provide a working configuration for the doc: https://www.scaleway.com/en/docs/dedibox-network/ipv6/how-to/configure-ipv6-networkd/.

**Comment by Shot2** [comment]
Obviously I can not provide a configuration working for _any_ version of systemd-networkd, as would be required for Scaleway's documentation. As stated, the configuration snippets in my previous message work _only_ from version _≥252_ of systemd (as found in e.g. Debian Bullseye-Backports and Debian Bookworm).

Also note that the snippets above are deliberately lacking some settings and directives; the "..." represent ellipses, and "xx" obfuscation due to privacy concerns. One should not copy-paste and use them as is.

**Comment by HLFH** [comment]
@Shot2 Ok I think I got `systemd-networkd` working. 😳 For both IPv4 and IPv6 and for my two Scaleway Dedibox servers. Thanks for your help!
