### ISSUE TITLE
Document how `Conflicts=` interacts with `Before=` and `After=`

### ISSUE THREAD

**Issue by balaziks** [systemd/systemd#13421]
**Is your feature request related to a problem? Please describe.**

From the [documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Requires=) it is quite clear how `Requires=` interacts with `Before=` and `After=`, more specifically how to make one unit start after the other is already started.

However there is no such explanation for the interaction of `Before=` and `After=` with `Conflict=`, more specifically the documentation doesn't state how to ensure that one unit is started after some other unit is completely finished.

*Let me provide an example:*

Consider two service units:

`first.service`

``` ini
[Unit]
Description=first

[Service]
ExecStartPre=/usr/bin/ip addr add 192.0.2.1/32 dev lo
ExecStart=/tmp/slow_stop.sh
ExecStop=/usr/bin/ip addr del 192.0.2.1/32 dev lo
```

and `second.service`

``` ini
[Unit]
Description=second
Conflicts=first.service

[Service]
ExecStartPre=/usr/bin/ip addr add 192.0.2.1/32 dev lo
ExecStart=/usr/bin/ping -c 5 192.0.2.1 
ExecStop=/usr/bin/ip addr del 192.0.2.1/32 dev lo
```

as well as a `/tmp/slow_stop.sh` script that takes a non-trivial amount of time to stop when sent *normal* signals:

``` bash
#!/bin/bash
trap 'sleep 5; exit;' SIGHUP SIGINT SIGTERM
ping 192.0.2.1
```

Now when I run `systemctl start first` and `systemctl start second` a bit later `second` will fail to start immediately (it tries to add the address to the interface which is already present) and then `first` will be stopped after the 5 seconds (given in the `trap` command) elapse.

_**There is no documentations on how to specify the order of operations (stopping `first` and starting `second`).**_

_**In other words there is AFAIK no documented way of starting `first` after `second` is completely finished.**_

Moreover (rather counter-intuitively IMHO) the desired order (wait for `first` to stop (and _free-up_ the address) and then start `second`) can be achieved by adding `Before=first.service` to `second.service` like so:

``` ini
[Unit]
Description=second
Conflicts=first.service
Before=first.service

[Service]
ExecStartPre=/usr/bin/ip addr add 192.0.2.1/32 dev lo
ExecStart=/usr/bin/ping -c 5 192.0.2.1 
ExecStop=/usr/bin/ip addr del 192.0.2.1/32 dev lo
```

**Describe the solution you'd like**
Carefully document how to specify the order of stopping one service and starting the other when using `Conflicts=` in a unit file.

Explain how `Conflicts=` interacts with `Before=` and `After=` (rather than just saying it's _independent and orthogonal_).

**Describe alternatives you've considered**
None.

**Comment by Werkov** [comment]
> Carefully document how to specify the order of stopping one service and starting the other when using `Conflicts=` in a unit file.
> 
> Explain how `Conflicts=` interacts with `Before=` and `After=` (rather than just saying it's _independent and orthogonal_).

The statement is true though. What is it missing in your view, @balaziks?

Actually, the way how to specify the ordering is right below the `Conflicts=` paragraph, `Before=, After=`. I admit it is buried in the wall of text (highlight by me):
> The shutdown is ordered before the start-up in *all cases*. If two units have no ordering dependencies between them, they are shut down or started up simultaneously, and no ordering takes place.

**Comment by balaziks** [comment]
> What is it missing in your view?

Although `Requires=` is also _independent and orthogonal_ to `Before=` and `After=` the documentation for it goes to detail on how to achieve the proper ordering of the start of two services.

I would like to see the same kind of explanation in the `Conflicts` documentation. 

> Actually, the way how to specify the ordering is right below the Conflicts= paragraph, Before=, After=. I admit it is buried in the wall of text (highlight by me):

Thanks for pointing me to the right part of the documentation. I missed these few sentences. I still find it kind of weird that both `Before` and `After` behave the same when using `Conflicts`.

Just out of curiosity (i.e. I don't have a use case for it): Is there a way to order the shutdown of one service and start-up of some other _the other way around_ i.e. start-up `second` then shutdown `first`?

**Comment by Werkov** [comment]
> Is there a way to order the shutdown of one service and start-up of some other _the other way around_

No, not in the terms of the existing dependencies. (Not counting hacks like `ExecStartPost=systemctl stop other`.)

**Comment by keszybz** [comment]
@Werkov is saw your patch, but I don't think it goes far enough. I'll submit a PR.
