### ISSUE TITLE
[RFE] PipesTo= directive for services

### ISSUE THREAD

**Issue by danobi** [systemd/systemd#13431]
**Is your feature request related to a problem? Please describe.**
Pipes are a very useful unix primitive. There is not currently native support for piping. For example, a service may have a main binary. An administrator may want to pipe that output to a filtering program (eg grep) to keep log noise down. Currently the only way to do that is something like:

    ExecStart = /bin/bash -c "/bin/binary | /bin/tailer"

But if you're doing this, you must also do

    ExecStop = /bin/sh -c "/bin/pkill -SIGTERM -P $MAINPID binary"
    ExecStop = /bin/sh -c "while [[ -d /proc/$MAINPID ]]; do sleep 1; done"

so we do not lose output if the systemd kills the tailer before the main binary. We must also wait for the main binary to flush output and exit so that systemd does not immediately reap the pipe-ee before output is processed.

**Describe the solution you'd like**
systemd can correctly and more efficiently manage pipes for us. I propose a `PipesTo=` directive such that the above example can be simplified to

    ExecStart = /bin/binary
    PipesTo = /bin/tailer

systemd can take care to only reap the tailer after the main binary has had an opportunity to exit. This would be beneficial as writing shell scripts in unit files is error prone and hard to debug.

**Describe alternatives you've considered**
Note that this idea would have to be more fleshed out. eg stdout/stderr options. Support for piping to another service. Etc.

**Comment by boucman** [comment]
That sounds a bit more tricky than that... systemd has to monitor both processes now, with all that this implies... I'd just go with "sh -c" for that sort of cases (where systemd just monitors the shell as a whole) or do something complicated with two services where I connect the StandardOutput of one to a named pipe and red with the other...

**Comment by poettering** [comment]
Uh, I am pretty sure that if you want pipelines you should use a proper shell/shell script. Shell pipeliness are inherently a shell concept, and I really doubt that we should try to be another shell. If you want shell concepts, use shell.

The ExecStop= lines should not be necessary btw, the shell should propagate SIGTERM properly. Moreover, in systemd's default killing mode we kill all processes of the service with SIGTERM anyway, and wait for it, hence even if the shell's own logic doesn't work systemd should have you.

Anyway, sorry, but I am really not convinced this is desirable. There's no shame in shell, use it when you need it, but systemd should not be one. Hope that makes some sense.
