### ISSUE TITLE
systemd breaks ps3 boot

### ISSUE THREAD

**Issue by grepwood** [systemd/systemd#1343]
This happened after I've `apt-get dist-upgrade`'d to Debian Jessie and rebooted. Nothing happens afterwards.
![img_20150921_181555](https://cloud.githubusercontent.com/assets/4225739/10025599/58da6c42-615d-11e5-91a3-4652b1a08ca5.jpg)

**Comment by floppym** [comment]
This seems unlikely to be a bug in systemd. It's likely an outdated/misconfigured kernel, or possibly a debian packaging problem.

**Comment by poettering** [comment]
You need a newer kernel to run systemd. It must support /sys/fs/cgroup. Please ask your distro for a newer kerne.

**Comment by grepwood** [comment]
@floppym is correct. Here's the working kernel for anyone else who might stumble upon this issue: https://sucs.org/~grepwood/ps3/linux/kernels/ps3-kernel-3.15.10.tar.xz
@poettering That is not an option, since running Linux on a PS3 these days is preferred with custom firmware, which requires patches that haven't made it to the mainline kernel tree. Kernels available from distros don't ship those patches.

**Comment by johannbg** [comment]
@poettering is it not possible to add a hint that indicates to the user that he might need a newer kernel when systemd fails to mount /sys/fs/cgroup to prevent bugs like this from reoccurring?

**Comment by floppym** [comment]
I think the expectation is that you know what you are doing if you choose to use a kernel which has not been provided by your distro. Adding arbitrary runtime kernel version checks to systemd seems silly to me.

**Comment by johannbg** [comment]
@floppym you would not be adding arbitrary runtime kernel version checks to systemd. 

You would just be indicating to the user that he requires a kernel that supports and has CGroups enabled, which only requires adding a hint to the failure message as in

from 

"systemd[1]: Failed to mount tmpfs at /sys/fs/cgroup: No such file or directory" 

to 

"systemd[1]: Failed to mount tmpfs at /sys/fs/cgroup: No such file or directory. Ensure the kernel has support for and has CGroups enabled." ( or something along those lines )

Which should be enough to prevent bugs like this from reoccurring...

**Comment by floppym** [comment]
It would prevent this particular bug, maybe. But systemd depends on many other recent/optional kernel features, and adding "helpful messages" for them all in the right places would be quite an undertaking.

**Comment by poettering** [comment]
@johannbg To me it appears as if people who are capable enough of picking their own kernels should be able to make sense of the existing error message... I mean, seriously, what could it mean if /sys/fs/cgroup is missing? It's in /sys, so it is kernel stuff, people should know that, and something is missing there... So it's either a missing kernel feature or a too old kernel... It's not too difficult to come to that conclusion I think.
