### ISSUE TITLE
udevadm test --action -p /devices/virtual/misc/fuse yields "Invalid action '-p'"

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#13442]
**systemd version the issue has been seen with**

v242

**Used distribution**

Debian buster

With v241, it was possible to run `udevadm test --action -p /devices/virtual/misc/fuse` (and we have code in the Debian archive which does that), but with v242 this now triggers a failure:
```
$ udevadm test --action -p /devices/virtual/misc/fuse
Invalid action '-p'
```

The udev man page doesn't go into detail if `-p` is a valid action or not (and the docs should probably be improved in that regard).

Running git bisect lists  5ebd3fc3c18ba997fd22f84bdb90144669810953
```
commit 5ebd3fc3c18ba997fd22f84bdb90144669810953
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Fri Mar 8 17:25:00 2019 +0900

    sd-device: store parsed ACTION= and SEQNUM= udev properties
```
as the commit exhibiting this new behaviour.

@yuwata could you please verify that this new behaviour is actually wanted of if this is a regression.

**Comment by mbiebl** [comment]
Related downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935496

**Comment by yuwata** [comment]
I do not think it is an our bug, but the bug in the script used in the install script of fuse. `udevadm test` does not support `-p`, and `--action` option requires argument. Also, of course, `-p` is not a valid action.

Before the commit, we have not checked the action string. So, the invalid `-p` action is written in the `ACTION=` udev environment. But we should not accept that.

**Comment by mbiebl** [comment]
Thanks for the quick response @yuwata 
So I assume that it worked in the past was by accident?
Could the documentation be clarified what a valid action is?
I'm happy to file a new bug report for this or we repurpose this one.

**Comment by yuwata** [comment]
> So I assume that it worked in the past was by accident?

Right.

> Could the documentation be clarified what a valid action is?
> I'm happy to file a new bug report for this or we repurpose this one.

Implicitly documented. I will update that.

**Comment by yuwata** [comment]
The document update is waiting in #13444.
