### ISSUE TITLE
networkd doesn't recognise or add multiple DNS search domains

### ISSUE THREAD

**Issue by danboid** [systemd/systemd#1344]
The 'Domains='  option for networkd currently only recognises and adds the first domain given after 'Domains=' in the networkd config files.The man page fails to specify how the DNS domains should be listed but I tried separating the domains with both spaces and commas and neither worked and nor did using multiple Domain statements.

systemd 226 under Arch

**Comment by aewne** [comment]
Same issue on Gentoo running systemd 218. However, specifying Domains once per domain works.

**Comment by teg** [comment]
I'm not able to reproduce this.

If you have
`Domains=test.com test2.com`
in your .netorkwork file what does
`networkctl status <ifname>`
show?

If that looks ok, how are you observing the problem precisely?

**Comment by danboid** [comment]
Hi Tom

You're correct in saying networkctl status shows all the domains I specified for each interface but /etc/resolv.conf only shows the first domain specified and the additional domains don't work under FireFox (40.0.3) for me; I have to specify the full URL to addresses that fall under my specified domains, those that only show themselves under networkctl

**Comment by poettering** [comment]
This should work correctly now in resolved git, which implements full search domain support.
