### ISSUE TITLE
Warning message: Unsafe core_pattern used with suid_dumpable=2. Pipe handler or fully qualified core dump path required

### ISSUE THREAD

**Issue by rajubi1981** [systemd/systemd#13441]
**systemd version the issue has been seen with**
> ...

The warning from kernel "Unsafe core_pattern used with suid_dumpable=2. Pipe handler or fully qualified core dump path required" is seen in /var/log/messages

Operating System
Red Hat Enterprise Linux Server release 7.6 (Maipo)

Systemd-Version
systemd-219-67.el7_7.1.x86_64

The warning messages should not be seen.
```
[root@mrc001 ~]# cat /etc/sysctl.conf
# sysctl settings are defined through files in
# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
#
# Vendors settings live in /usr/lib/sysctl.d/.
# To override a whole file, create a new file with the same in
# /etc/sysctl.d/ and put new settings there. To override
# only specific settings, add a file with a lexically later
# name in /etc/sysctl.d/ and put new settings there.
#
# For more information, see sysctl.conf(5) and sysctl.d(5).
#RENin55665 and RENin66441
kernel.core_uses_pid = 0
fs.suid_dumpable = 0
kernel.core_pattern = core.%e.%p
[root@xxxxxxxxxxvmrf0001vm002mrc001 ~]#
```
ls /etc/sysctl.d/ is empty. 
```
[root@mrc001 ~]# ls /usr/lib/sysctl.d/
00-system.conf  10-default-yama-scope.conf  50-default.conf
```
These are default values and not changed.

Checked the source RPM of systemd-219-67.el7_7.1.x86_64, I observed a patch for ordering of sysctl parameters but with that problem will be solved. But the issue is still seen.

0493-sysctl-configure-kernel-parameters-in-the-order-they.patch

Linux version is 
Linux mrc001 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

Kernel RPM version: kernel-3.10.0-957.21.3.el7.x86_64

I saw the source code of the kernel, kernel/sysctl.c
```
static void validate_coredump_safety(void)
{
#ifdef CONFIG_COREDUMP
  if (suid_dumpable == SUID_DUMP_ROOT &&
   ¦ ¦core_pattern[0] != '/' && core_pattern[0] != '|') {
    printk(KERN_WARNING "Unsafe core_pattern used with "\
      "suid_dumpable=2. Pipe handler or fully qualified "\
      "core dump path required.\n");
  }
#endif
}
```
The warning is seen only when suid_dumpable is 2 and core_pattern first string is not '/' or '|'

But in my case the fs.suid_dumpable is 0 and kernel.core_pattern is core.%e.%p. Ideally I should get this errors.

I want to know does systemd set by mistake fs.suid_dumpable=2 or the kernel is doing so.
I browsed the code I was not able to get anything.

journalctl logs
```
Aug 29 15:43:42 localhost.localdomain systemd[1]: Started Create list of required static device nodes for the current kernel.
Aug 29 15:43:42 localhost.localdomain kernel: Unsafe core_pattern used with suid_dumpable=2. Pipe handler or fully qualified core dump path required.
Aug 29 15:43:42 localhost.localdomain systemd[1]: Starting Create Static Device Nodes in /dev...
```
"/var/log/messages"
```
Aug 29 15:47:39 vm001 kernel:[    0.707637] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
Aug 29 15:47:39 vm001 kernel:[    0.968064] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
Aug 29 15:47:39 vm001 kernel:[    1.661555] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
Aug 29 15:47:39 vm001 kernel:[    1.902208] Unsafe core_pattern used with suid_dumpable=2. Pipe handler or fully qualified core dump path required.
Aug 29 15:47:39 vm001 kernel:[    2.691994] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 10
Aug 29 15:47:39 vm001 kernel:[    2.949210] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
Aug 29 15:47:39 vm001 kernel:[    3.051763] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
```
So on every reboot the error is seen in both these places.

If you need more info to debug or resolve the issue kindly let me know i will be happy to supply. But I am looking for a solution.

**Comment by rajubi1981** [comment]
Even if I comments from the file "/etc/sysctl.conf"

#fs.suid_dumpable = 0
#kernel.core_pattern = core.%e.%p
#kernel.core_uses_pid = 0

The kernel warning is seen as put above.

**Comment by poettering** [comment]
Please talk to your distro maintainers first. We only track upstream issues here, in the two most recent systemd upstream releases. This does not qualify, sorry.
