### ISSUE TITLE
Support suspend modes "s2idle", "shallow", and "deep"

### ISSUE THREAD

**Issue by HaleTom** [systemd/systemd#13451]
## Problem
I use both [Suspend-to-RAM](https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#suspend-to-ram) as well as plain [Suspend](https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#standby) with `systemd`.

[The Linux kernel user's and administrator's guide says](https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#basic-sysfs-interfaces-for-system-suspend-and-hibernation):

> [T]here is only one way to make the system go into the suspend-to-RAM state (write `deep` into `/sys/power/mem_sleep` and `mem` into `/sys/power/state`).

[`systemd-sleep.conf(5)`](https://manned.org/systemd-sleep.conf.5) only mentions `/sys/power/disk` and `/sys/power/state` but not `/sys/power/mem_sleep`. 

[Searching the code for `mem_sleep`](https://github.com/systemd/systemd/search?q=mem_sleep) returns nothing.

## Desired solution

Allow `SuspendState` and `HybridSleepState` to additionally accept the values of [kernel command line `mem_sleep_default=`](https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html), namely `s2idle`, `shallow`, and `deep`:

>        mem_sleep_default=      [SUSPEND] Default system suspend mode:
>                        s2idle  - Suspend-To-Idle
>                        shallow - Power-On Suspend or equivalent (if supported)
>                        deep    - Suspend-To-RAM or equivalent (if supported)
>                        See Documentation/admin-guide/pm/sleep-states.rst.

For backward compatibility, if `mem` is used, then use the current default value in `/sys/power/mem_sleep` at the time of suspension.

## Alternatives considered

Adding additional configuration variables `SuspendMemSleep`, `HybridMemSleep` seems like unneeded clutter.

**Comment by HaleTom** [comment]
Prior art: https://unix.stackexchange.com/q/538541/143394

**Comment by poettering** [comment]
Hmm, d owe need to support this in systemd-sleep at all? Doesn't a "w" line in tmpfiles.d/ suffice for this?

**Comment by HaleTom** [comment]
If one wants to have `suspend` be the kernel's `standby`, that would require `shallow` in `/sys/power/mem_sleep`.

If one wishes to have `suspend-then-hibernate` be the kernel's `suspend-to-RAM`, then that would require `deep` in `/sys/power/mem_sleep`.

I don't see how a single value in `/sys/power/mem_sleep` could be used to cover the two cases, or how the value could easily be juggled between the two via `tmpfiles.d/ `

**Comment by russkel** [comment]
This does seem to be something missing. I would love for the system to `s2idle` for half an hour and then `deep` sleep. But as @HaleTom mentions this doesn't seem doable.

**Comment by bam80** [comment]
Friendly ping?

**Comment by webczat** [comment]
actually does anyone know why s2idle is the default? i am kinda sure previously it was not... wondering, if systemd-sleep would gain that support, whether it's appropriate to use deep as the preferred default or... I mean it's probably in line what it does for other values.

**Comment by superm1** [comment]
> actually does anyone know why s2idle is the default?

If the system's FADT indicates that low power idle is supported the [kernel](https://github.com/torvalds/linux/blob/55be6084c8e0e0ada9278c2ab60b7a584378efda/drivers/acpi/x86/s2idle.c#L518) will set this as the preference.

**Comment by webczat** [comment]
to be honest this specific thing can be regulated with a kernel parameter, i mean you can set one to switch to deep sleep as default. s2idle is the shiny new thing which at least in the future would be preferred over s3, as I've read, so... Going in that direction by making it the default for hardware advertising it

**Comment by superm1** [comment]
The way the kernel has implemented it if you use `mem` in `/sys/power/state` then `/sys/power/mem_sleep` dictates what value to use.  That is the current kernel code and the current systemd code are completely compatible.

It's not strictly necessary for systemd to do *anything* to support s2idle.  Most **new** systems on the market support s2idle in the FADT and systemd DTRT for them.

Considering the kernel command line can flip the default of `/sys/power/mem_sleep` on systems that support both `s2idle` and `deep`, what does explicitly adding `s2idle` and `deep` into the Suspend Modes for systemd actually **buy you**?

**Comment by vortigont** [comment]
[TLP](https://github.com/linrunner/TLP) supports switching sleep mode depending on power source by changing kernel parameter. Works like a charm.

**Comment by vortigont** [comment]
"When everything is working right" is the only part that usually missing :) just google for "C10 s0ix s2idle issues" or "battery drain in s2idle". It is far from good in a lot of default configurations.
In my own case even with very fine tuned setup s2idle mode drains battery twice as fast as S3, leave out default disto settings. (BTW, windows system is not any better here)

**Comment by superm1** [comment]
> "When everything is working right" is the only part that usually missing :) just google for "C10 s0ix s2idle issues" or "battery drain in s2idle". It is far from good in a lot of default configurations.

OK - so to be clear what TLP did is meant as a bandage more than anything.

**Comment by bam80** [comment]
> When everything is working right the power consumption of s2idle and s3 should be about the same. 

Hmm, there is no clear evidence of this from the description:
> Suspend-to-Idle
> This is a generic, pure software, light-weight variant of system suspend (also referred to as S2I or S2Idle). 
> ...
> This state can be used on platforms without support for [standby](https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#standby) or [suspend-to-RAM](https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#s2ram), or it can be used in addition to any of the deeper system suspend variants to provide reduced resume latency. 

https://www.kernel.org/doc/html/latest/admin-guide/pm/sleep-states.html#suspend-to-idle
> On a lot of AMD platforms it's actually lower in s2idle than it is in s3.

Is there a real sample of this for Intel platforms?
In my case it's pretty buggy:
https://github.com/MrChromebox/scripts/issues/187#issuecomment-1061216477

**Comment by keszybz** [comment]
As described in https://github.com/systemd/systemd/issues/25151#issue-1424648010, the kernel already tries to pick the appropriate default (show in `/sys/power/mem_sleep`). And systemd already DTRT (https://github.com/systemd/systemd/issues/13451#issuecomment-1276580111), when things work as expected. Systemd doesn't handle the case when the suspend doesn't work very gracefully, but #25152 should make that case better. So *this* ticket boils down to the question whether we should make the sleep type configurable. There certainly are systems on which it is necessary to override the kernel default because of bugs. But I don't think we should provide a top-level option for this. It is almost as easy to provide a drop-in file for tmpfiles, and this is a good-enough workaround until support in the kernel is improved.

Something like this would work:
```ini
# /etc/tmpfiles.d/sleep-mode.conf
w /sys/power/mem_sleep - - - - deep
```

Is my understanding correct?

**Comment by superm1** [comment]
> Is my understanding correct?

Yes.

> changing this on kernel command line also works.

Yeah.

> So this ticket boils down to the question whether we should make the sleep type configurable. There certainly are systems on which it is necessary to override the kernel default because of bugs. But I don't think we should provide a top-level option for this. 

I tend to agree with you.  If there is a system that really doesn't work well with it's default for some unfixable reason, it can either be quirked for a certain default in the kernel or either of the two suggestions you made.

**Comment by keszybz** [comment]
Thanks. I edited my comment to mention the kernel param, in case people look at this issue. Now the workaround is both at the beginning and the end of the thread ;)

I'll close this as WONTFIX: it seems that the workaround is good enough and we should just make the behaviour handle unexpected failure better, which is being discussed in #25152.

**Comment by main--** [comment]
While it is true that for many systems only one mode (s2idle, shallow, deep) works correctly I think a lot of the discussion in this issue is ignoring the fact that it is absolutely possible to have a system where e.g. both s2idle and deep are functional, and a usecase where I don't want to permanently commit to a single one of those modes. Such as the idea outlined by @russkel where instead of the traditional suspend-then-hibernate one might want to configure s2idle-then-deep.

In general systemd's power management (systemctl suspend, sleep.conf) seems like it's currently stuck with a very rigid model that supports suspend, hibernate, and nothing else.

The tempfiles.d workaround is totally fine if I always need the same mode. But today I ran into a usecase where I would like to be able to do something like `systemctl suspend --state=s2idle`. The only workaround I can think of is a wrapper (with suid) that writes a value to `/sys/power/mem_sleep` before invoking `systemctl suspend`.

**Comment by drws** [comment]
@main-- Take a look at the  `MemorySleepMode` and `SuspendState` options in [`systemd-sleep.conf`](https://www.freedesktop.org/software/systemd/man/latest/systemd-sleep.conf.html).
