### ISSUE TITLE
[RFE] resolvectl dns should work with networkd managed files

### ISSUE THREAD

**Issue by DamienRobert** [systemd/systemd#13459]
I have an interface configured as such:
~~~
[Match]
Name=en* eth* usb* wl*

[Network]
DHCP=ipv4
DNS=1.1.1.1
UseDNS=false
~~~

1) Contrary to what the documentation says, the dns servers received from the DHCP still are used, they just have less precedence than 1.1.1.1. So first feature request: have a 'UseDNS=never' that allows to never use these servers

2) Sometimes when the connection lags (after a resume from suspend for instance), resolved switch from the current DNS server to the next one. For instance on my laptop I currently have:
~~~
  Current DNS Server: 89.2.0.1
         DNS Servers: 1.1.1.1
                      89.2.0.1
                      89.2.0.2
~~~
so that at some point, resolved switched from 1.1.1.1 to 89.2.0.1.

I would like to ask resolved to go back to 1.1.1.1. Normally `resolvectl dns` should be able to do that, but the doc specifically says that it does not work with networkd managed files.

Note that in any case it would be nice to have this feature to dynamically change the DNS of interfaces managed by networkd. The current solution is to write an override file in /run/systemd/network and restart netword, which is way less convenient than a `resolvctl` cli interface.

**Comment by yuwata** [comment]
This is already implemented. Please use v243 or current git master.

**Comment by DamienRobert** [comment]
You are right, sorry, I missed it because it is not in the NEWS for 243 (I am on 242). Should have checked the latest version.

There sill remains my request for UseDNS=never, but I guess I can emulate it more or less by specifying a global DNS and using a non existent routing dns domain for the interface.

**Comment by yuwata** [comment]
Note that `UseDNS=` must be in [DHCP] section.
