### ISSUE TITLE
systemd-firstboot: enter key has to be pressed twice for some settings in the interactive wizard

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13468]
In the [systemd-firstboot](https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html) `--prompt` tool, I've noticed that some of the settings require the enter key to be pressed twice to continue to the next step in the wizard.

My system configuration:

- Hardware: Raspberry Pi 1 B+
- Kernel 5.2.11
- systemd 241

**Comment by poettering** [comment]
hmm, which settings precisely?

**Comment by keszybz** [comment]
ee41670ffbecb000db873f839a7381495bbe2bc6 should fix this (systemd v243).

Please reopen if you can still reproduce this issue post v243.
