### ISSUE TITLE
Fix rotation support for HP EliteBook 820 G1

### ISSUE THREAD

**Issue by jtsagata** [systemd/systemd#13463]
**Is your feature request related to a problem? Please describe.**
HP EliteBook 820 G1 sensor give reversed rotations

**Describe the solution you'd like**
A Fix is
```
sensor:modalias:platform:lis3lv02d:dmi:*svn*Hewlett-Packard*:*
  ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1
```
 a line like 
```
sensor:modalias:platform:lis3lv02d:dmi:*svnHP:pnHPEliteBook820G1*
```
seems that is not working 

sudo dmidecode| grep HP
Product Name: HP EliteBook 820 G1

**Comment by poettering** [comment]
please provide a PR for this.

/cc @hadess

**Comment by hadess** [comment]
Duplicate of https://github.com/systemd/systemd/issues/13543, fixed in https://github.com/systemd/systemd/pull/13545
