### ISSUE TITLE
systemd-firstboot: improve detection for empty root password

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13467]
The [systemd-firstboot](https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html) `--prompt` wizard skips those settings that have already been initialized.
To determine whether the root password is already initialized it seems that the wizard only checks if the `/etc/shadow` file is present or not.
In the situation where the `/etc/shadow` file already exists but with an empty root password, it would make sense to NOT skip the query of the root password.

Suggested solution:
In case the `/etc/shadow` file is already present, the `systemd-firstboot --prompt` wizard should also check the content of the file.
If the file contains the following line (which indicates an empty root password), the wizard should query the user to setup the password for security reasons:
`root::::::::`

My system configuration:

- Hardware: Raspberry Pi 1 B+
- Kernel 5.2.11
- systemd 241

**Comment by poettering** [comment]
THis is pretty much implemented via a777a59243ab3a8496642e330c377fff0769fdca.

(Though not via an empty pw, but by setting the pw to `!unprovisioned`, to make the case clearly distinguishable)

Closing.
