### ISSUE TITLE
systemd-firstboot: selected keymap not activated before password prompt

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13466]
The [systemd-firstboot](https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html) wizard has the `--prompt` option to interactively query the most basic system settings from the user at first boot.
This includes the console keymap and the root password.
From an end users point of view, I would expect that the selected keymap is immediately activated by the firstboot-wizard before the query of the root password.
In fact `systemd-firstboot` only creates the `vconsole.conf` file but does not activate the selected keymap on the running system.

Suggested solution:
`systemd-firstboot --prompt` should run `/usr/lib/systemd/systemd-vconsole-setup` to activate the selected keymap directly after the `vconsole.conf` file has been created and before the query of the root password.

My system configuration:

- Hardware: Raspberry Pi 1 B+
- Kernel 5.2.11
- systemd 241

**Comment by poettering** [comment]
makes sense.
