### ISSUE TITLE
Xubuntu 18.04 sometimes freezes when turned on on logo

### ISSUE THREAD

**Issue by stafik1993** [systemd/systemd#13478]
When I turn off the computer, it hangs on the logo. The light on the system unit continues to light. Does not respond to the keyboard. Kernel version 5.0.0-27. Here is the error:

info: task systemd shutdown:1 blocked for more than 120 seconds
Not tainted 5.0.0-20-generic #21-Ubuntu
«echo 0 /proc/sys kernel/hung_task_timeout_secs» disables this message

https://ibb.co/PcYvDLq

**Comment by poettering** [comment]
Please talk to your distro maintainers first. they'll escalate this to us if there's a problem in systemd. thank you for understanding.
