### ISSUE TITLE
Missing cgroup mounts or v2 only

### ISSUE THREAD

**Issue by OJFord** [systemd/systemd#13477]
**systemd version the issue has been seen with**
> 243-rc2-1

**Used distribution**
 > Debian 10

**Expected behaviour you didn't see**
 ```
$  ls /sys/fs/cgroup/
blkio  cpu,cpuacct  cpuset   freezer  net_cls		net_prio    pids  systemd
cpu    cpuacct	    devices  memory   net_cls,net_prio	perf_event  rdma  unified
```

**Unexpected behaviour you saw**
 ```
$ ls /sys/fs/cgroup
cgroup.controllers  cgroup.max.descendants  cgroup.stat		    cgroup.threads  system.slice
cgroup.max.depth    cgroup.procs	    cgroup.subtree_control  init.scope	    user.slice
```

**Steps to reproduce the problem**
1. I used Vultr's Debian 9 and 10 base images, but afaik nothing special there
1. `add-apt-repository 'deb http://deb.debian.org/debian experimental main'`
1. `apt update`
1. `apt install -t experimental systemd=243~rc2-1`
1. [no affect] I tried adding `systemd.legacy_systemd_cgroup_controller=yes` to `GRUB_CMDLINE_LINUX` in a grub drop-in
1. `shutdown -r now`

**Comment by mbiebl** [comment]
This is pretty much expected. See the relevant part from the v243 release notes:
```
        * systemd now defaults to the "unified" cgroup hierarchy setup during
          build-time, i.e. -Ddefault-hierarchy=unified is now the build-time
          default. Previously, -Ddefault-hierarchy=hybrid was the default. This
          change reflects the fact that cgroupsv2 support has matured
          substantially in both systemd and in the kernel, and is clearly the
          way forward. Downstream production distributions might want to
          continue to use -Ddefault-hierarchy=hybrid (or even =legacy) for
          their builds as unfortunately the popular container managers have not
          caught up with the kernel API changes.
```

**Comment by mbiebl** [comment]
I kept the the upstream default `unified` for the experimental and will likely keep in unstable for a while to get a clearer picture what will be broken by that change.
It's very likely that we will revert to hybrid once bullseye is in the final stages of development depending on the feedback we get.

**Comment by OJFord** [comment]
I see, thanks, sorry not sure how I missed that.

Should not `systemd.legacy_systemd_cgroup_controller=yes` in `GRUB_CMDLINE_LINUX` have kept it back though?

> get a clearer picture what will be broken by that change

For what it's worth, my reason to fall into this rabbit hole (but I learnt more about cgroups, so 👍) was `docker.service` needing to be manually started on every boot (or else complaining about `devices` and `cpu` not mounted), and `kubelet.service` not starting at all (`cpu` not mounted). I couldn't manually mount since it was 'already mounted' at new location, and couldn't create symlinks inside `/sys/fs/cgroupfs` to try to appease it that way.

**Comment by mbiebl** [comment]
Try `systemd.unified_cgroup_hierarchy=false` and don't forget to run `update-grub`

**Comment by OJFord** [comment]
`false` did the trick, (and seems the more obvious value now you say it..) many thanks!

Closing as this is an expected change in v243 as it currently stands; if you need 243 or later but also to use v1 cgroups, set the `systemd.unified_cgroup_hierarchy=false` boot parameter, e.g.
```
$ echo 'GRUB_CMDLINE_LINUX=systemd.unified_cgroup_hierarchy=false' > /etc/default/grub.d/cgroup.cfg
$ update-grub
```
and you should have legacy cgroup mounts and a new `unified` dir with v2 mounts on reboot:
```
dr-xr-xr-x  4 root root   0 Sep  4 22:20 blkio
lrwxrwxrwx  1 root root  11 Sep  4 22:20 cpu -> cpu,cpuacct
dr-xr-xr-x  4 root root   0 Sep  4 22:20 cpu,cpuacct
lrwxrwxrwx  1 root root  11 Sep  4 22:20 cpuacct -> cpu,cpuacct
dr-xr-xr-x  2 root root   0 Sep  4 22:20 cpuset
dr-xr-xr-x  4 root root   0 Sep  4 22:20 devices
dr-xr-xr-x  2 root root   0 Sep  4 22:20 freezer
dr-xr-xr-x  4 root root   0 Sep  4 22:20 memory
lrwxrwxrwx  1 root root  16 Sep  4 22:20 net_cls -> net_cls,net_prio
dr-xr-xr-x  2 root root   0 Sep  4 22:20 net_cls,net_prio
lrwxrwxrwx  1 root root  16 Sep  4 22:20 net_prio -> net_cls,net_prio
dr-xr-xr-x  2 root root   0 Sep  4 22:20 perf_event
dr-xr-xr-x  4 root root   0 Sep  4 22:20 pids
dr-xr-xr-x  2 root root   0 Sep  4 22:20 rdma
dr-xr-xr-x  5 root root   0 Sep  4 22:20 systemd
dr-xr-xr-x  5 root root   0 Sep  4 22:20 unified
```

**Comment by josteink** [comment]
I encountered this issue with LXC on Ubuntu for *some* of my Ubuntu/systemd-based LXC containers after upgrading to Ubuntu 22.04 (Jammy).

I can confirm the workaround suggested @OJFord works and my containers are now running again :+1:

**Comment by linas** [comment]
The matching LXC issue for this is `https://github.com/lxc/lxc/issues/4072` -- 

My host system is Debian stable 11.6 -- for whatever reason, Debian has not yet picked up the above suggestion, and/or has not picked up a matching version of LXC that supports this. I get this:
```
# lxc-checkconfig <my-container>
LXC version 4.0.6

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup namespace: required
```

The suggested fix above fixes it.
