### ISSUE TITLE
Add accel mount matrix for Medion Akoya E2292 MD63390

### ISSUE THREAD

**Issue by Tuxman2** [systemd/systemd#13480]
As the Medion Akoya E2293, the E2292 model is also a convertible Laptop. This configuration has been tested on Ubuntu 18.04 and derivates.

# Medion Akoya E2292 MD63390
sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION*:pnE2292MD63390:*
 ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1

Thanks.

**Comment by keszybz** [comment]
Can you submit this as PR? This will have your name attached, so you have a nice warm fuzzy feeling of contributing to systemd ;)

**Comment by Tuxman2** [comment]
@keszybz: Can you tell me how to submit a PR ? I never did it before.

Thanks.

**Comment by keszybz** [comment]
See e.g. https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR. It seems to be a good write up, easier to follow than the github docs.

**Comment by Tuxman2** [comment]
Hi, 

I tried but I can't do it. Can you do it for me ?

Thanks.

**Comment by matthiasroos** [comment]
PR (#13498) is submitted.

**Comment by Tuxman2** [comment]
@matthiasroos: Thanks. ;-)
