### ISSUE TITLE
sd_event_run man page problems

### ISSUE THREAD

**Issue by djh42** [systemd/systemd#13490]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > https://www.freedesktop.org/software/systemd/man/sd_event_loop.html#

**Expected behaviour you didn't see**
 > useful links for systemd(1) and GLib Main Event Loop

**Unexpected behaviour you saw**
 > the referenced page for systemd(1) doesn't mention events at all so its difficult to see the relevance. The supplied link for GLib Main Event Loop returns 403 Forbidden, which is at least as unhelpful

**Steps to reproduce the problem**
go to the page and click on the links

**Comment by poettering** [comment]
sd-event is part of systemd. All our man pages contain a link to systemd(1) hence, as that is pretty relevant.

And the glib event loop link works fine here.

Hence, closing, apparently the issues are all solved.

**Comment by keszybz** [comment]
Yep, the link works here too. Must have been some local issue.
