### ISSUE TITLE
Allow using environment variables in ListenStream=

### ISSUE THREAD

**Issue by vincent-olivert-riera** [systemd/systemd#13492]
**Is your feature request related to a problem? Please describe.**
I have multiple socket unit files, each one of them with it's own `ListenStream=`. All of them refer to the same service unit file which is parameterized. So, basically I have:
- foo@.service
- foo-8080.socket (refers to `foo@1.service`)
- foo-5079.socket (refers to `foo@2.service`)

Note there is no connection between the `%i` parameter in the service unit and the port number for the socket.

**Describe the solution you'd like**
I would like to have only one parameterized socket unit file (`foo@.socket`) where I can just load an environment file and grab the port number from there.

For example:

```
[Unit]
Description=Foo socket

[Socket]
EnvironmentFile=/etc/sysconfig/foo-%i
ListenStream=$PORT
Service=foo@%i.service

[Install]
WantedBy=sockets.target
```

**Comment by poettering** [comment]
Uh, no, let's not turn systemd unit files into an even more complex templating language. I am strongly against this. If you want a templating language, pleas euse m4 and generate unit files.

Through every level of interpretor logic in unit files we make it harder for other software pase these files, and eventually end up with another shell-like logic. 

Please, no. 

Please have a look at generators, they allow you generating unit files (both socket and service) or drop-ins for them from arbitrary external configuration files. It appears to me this is what you actually want.

EnvironmentFile= is only read at moment of fork()/exec(), and this is documented. This hence makes no sense at all in the context of socket units, where the bind() is done from PID 1, and no exec()/fork() is generally used.

Anyway, I am strongly against this, this is not the right approach. Let's close.

**Comment by peylight** [comment]
Hello guys
I have the same problem but instead of `ListenStream`, my problem is about `CPUAffinity` and i want to use variable inside this option. Also i think this is very needed for instance services. (i already seen same problem for other guys too..)
@poettering 
If you think `EnvironmentFile` is not a good way, making another option like `EnvironmentUnitFile` is better choice and it is make systemd more flexible.

**Comment by DrSensor** [comment]
I have a `swww-daemon.socket` that require `ConditionEnvironment` like this
```service
[Socket]
ListenStream=%t/swww-$WAYLAND_DISPLAY.sock

[Unit]
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Install]
WantedBy=graphical-session.target
```
Is there a workaround for this?

---
`swww-$WAYLAND_DISPLAY` is generated by `swww-daemon` program.
For the sake of completeness, here is my `swww-daemon.service`
```service
[Service]
ExecStart=swww-daemon
UnsetEnvironment=LISTEN_PID LISTEN_FDS LISTEN_FDNAMES
NonBlocking=true

[Unit]
Requires=%N.socket
Description=A Solution to your Wayland Wallpaper Woes
Documentation=man:swww(1)
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Install]
WantedBy=graphical-session.target
```
