### ISSUE TITLE
Router adverisements sent too seldom if  RouterLifetimeSec is smaller than SD_RADV_DEFAULT_MAX_TIMEOUT_USEC

### ISSUE THREAD

**Issue by georgmu** [systemd/systemd#13491]
**systemd version the issue has been seen with**
> 241 (but master source code checked that problem still persists)
libsystemd-network/sd-radv.c had only smaller fixes since then

**Used distribution**
 > debian 10 (buster)

**Expected behaviour you didn't see**
 > I do not lose my IPv6 connectivity if, for example RouterLifetimeSec=60s

**Unexpected behaviour you saw**
 > Link lost after 60s, restored sometimes between 200 and 600 seconds for the next 60 seconds, and so on

**Steps to reproduce the problem**
Configure IPv6 prefix delegation with RouterLifetimeSec=60s

The timeout in radv_timeout() should consider the value from RouterLifetimeSec and set max_timeout accordingly (and min_timeout to max_timeout/3 or so).

Otherwise, there should be a warning that RouterLifetimeSec is too low in the logs if router_lifetime_usec < SD_RADV_DEFAULT_MAX_TIMEOUT_USEC.

**Comment by georgmu** [comment]
I could prepare a pull request if you say what you prefer (lowering timeout vs. issuing a warning).

**Comment by yuwata** [comment]
> The timeout in radv_timeout() should consider the value from RouterLifetimeSec and set max_timeout accordingly (and min_timeout to max_timeout/3 or so).

This sounds reasonable for me, though I am not sure about the RFC.

**Comment by yuwata** [comment]
> I could prepare a pull request if you say what you prefer (lowering timeout vs. issuing a warning).

Yeah, please provide a patch.

**Comment by georgmu** [comment]
From the RFC: 
>      A router MUST allow for the following conceptual variables to be
>      configured by system management.  The specific variable names are
>      used for demonstration purposes only, and an implementation is not
>      required to have them, so long as its external behavior is consistent
>      with that described in this document.  Default values are specified
>      to simplify configuration in common cases.
>
>      ...
>
>       AdvDefaultLifetime
>                     The value to be placed in the Router Lifetime field
>                     of Router Advertisements sent from the interface,
>                     in seconds.  MUST be either zero or between
>                     MaxRtrAdvInterval and 9000 seconds.  A value of
>                     zero indicates that the router is not to be used as
>                     a default router.
>
>                     Default: 3 * MaxRtrAdvInterval
>
>      MaxRtrAdvInterval
>                     The maximum time allowed between sending
>                     unsolicited multicast Router Advertisements from
>                     the interface, in seconds.  MUST be no less than 4
>                     seconds and no greater than 1800 seconds.
>
>                     Default: 600 seconds

MaxRtrAdvInterval is hard-coded to 600s (SD_RADV_DEFAULT_MAX_TIMEOUT_USEC)

Thus, RouterLifetimeSec should be in the range of 600s and 9000s.

But since systemd does not have the option to set MaxRtrAdvInterval, I think it is okay to reduce the timeout here and then interpret RouterLifetimeSec as MaxRtrAdvInterval and reduce the timeout.

The other option would be to introduce a new option MaxRtrAdvInterval (with a default value of 600) and enforce a value for RouterLifetimeSec in the valid range.

**Comment by georgmu** [comment]
The pull request above is the simplest form.
If desired, I could also provide a pull request for one of the other options.
