### ISSUE TITLE
Allow setting slice MemoryMax in percents

### ISSUE THREAD

**Issue by kshcherban** [systemd/systemd#13497]
## Current state
Currently it's only possible to set `MemoryMax` in bytes. That doesn't work well with the immutable infrastructure paradigm. For example, you create an image of virtual machine and don't want to change it's root FS during runtime.
Because memory settings of launched VMs may be different you need to adjust systemd slices after boot or to create new image per VM configuration.

## Solution
It would be nice to allow setting `MemoryMax` in percents altogether with bytes or use parameter with another name, like `MemoryMaxPercents`.

**Comment by poettering** [comment]
Already implemented. See man page:

> Takes a memory size in bytes. If the value is suffixed with K, M, G or T, the specified memory size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively. Alternatively, a percentage
           value may be specified, which is taken relative to the installed physical memory on the system.

See https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemoryMax=bytes
