### ISSUE TITLE
hostnamed without polkit not able to set hostname

### ISSUE THREAD

**Issue by bjacquin** [systemd/systemd#13501]
**systemd version the issue has been seen with**
> systemd 242 (242+)
> +PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Gentoo Linux

**Expected behaviour you didn't see**
 > hostnamed able to set hostname from DHCP

**Unexpected behaviour you saw**
 > hostnamed is receiving Permission Denied

**Steps to reproduce the problem**
Build systemd without polkit support

```
meson --buildtype plain --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --localstatedir=/var -Dsupport-url=https://gentoo.org/support/ -Dpamlibdir=/lib64/security -Dbashcompletiondir=/usr/share/bash-completion/completions -Dsplit-usr=true -Drootprefix=/ -Dsysvinit-path= -Dsysvrcnd-path= -Dtelinit-path=/lib/sysvinit/telinit -Defi=true -Dima=true -Dacl=true -Dapparmor=false -Daudit=false -Dlibcryptsetup=false -Dlibcurl=false -Ddns-over-tls=true -Delfutils=false -Dgcrypt=true -Dgnu-efi=false -Defi-libdir=/usr/lib64 -Dmicrohttpd=false -Dimportd=false -Dbzip2=false -Dzlib=false -Dkmod=true -Dlz4=true -Dxz=true -Dlibiptc=false -Dpam=true -Dpcre2=true -Dpolkit=false -Dqrencode=false -Dseccomp=true -Dselinux=false -Ddbus=false -Dxkbcommon=false -Dntp-servers=0.gentoo.pool.ntp.org 1.gentoo.pool.ntp.org 2.gentoo.pool.ntp.org 3.gentoo.pool.ntp.org -Ddefault-kill-user-processes=false -Dcreate-log-dirs=false -Dbacklight=true -Dbinfmt=true -Dcoredump=true -Denvironment-d=true -Dfirstboot=true -Dhibernate=true -Dhostnamed=true -Dhwdb=true -Dldconfig=true -Dlocaled=true -Dman=true -Dnetworkd=true -Dquotacheck=true -Drandomseed=true -Drfkill=true -Dsysusers=true -Dtimedated=true -Dtimesyncd=true -Dtmpfiles=true -Dvconsole=true -Dlibidn2=true -Dlibidn=false /var/tmp/portage/sys-apps/systemd-242-r6/work/systemd-242 /var/tmp/portage/sys-apps/systemd-242-r6/work/systemd-242-abi_x86_64.amd64
```

Configuration:

```
# cat /etc/systemd/network/50-dhcp.network
[Match]
Name=eth*

[Network]
DHCP=yes

[DHCP]
UseDNS=true
UseNTP=true
UseMTU=true
UseHostname=true
```

hostnamed is unable to set hostname from DHCP:

```
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-networkd[18409]: Setting transient hostname: 'ip-10-97-15-12'
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-networkd[18409]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 member=SetHostname cookie=10 reply_cookie=0 signature=sb error-name=n/a error-message=n/a
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-networkd[18409]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
..
2019-09-08T16:43:29+00:00 daemon.info localhost systemd[1]: Starting Hostname Service...
..
2019-09-08T16:43:29+00:00 daemon.info localhost dbus-daemon[162]: [system] Successfully activated service 'org.freedesktop.hostname1'
..
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-hostnamed[18412]: Sent message type=error sender=n/a destination=:1.42 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=10 signature=s error-name=org.freedesktop.DBus.Error.AccessDenied error-message=Permission denied
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-networkd[18409]: Got message type=error sender=:1.43 destination=:1.42 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=10 signature=s error-name=org.freedesktop.DBus.Error.AccessDenied error-message=Permission denied
2019-09-08T16:43:29+00:00 daemon.debug localhost systemd-hostnamed[18412]: Failed to process message type=method_call sender=:1.42 destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 member=SetHostname cookie=10 reply_cookie=0 signature=sb error-name=n/a error-message=n/a: Permission denied
n/a
```

Looking a bit deeper into this, it seems `method_set_hostname()` in `src/hostname/hostnamed.c` is leveraging `bus_verify_polkit_async()` with ends up using `sd_bus_creds_has_effective_cap` with seems to be comparing `c->mask` (uint64_t) with `SD_BUS_CREDS_EFFECTIVE_CAPS` (int).

That part of the code is not really clear to me. However hijacking `bus_verify_polkit_async()` with the following patch solves the issue. This is obviously not the right way to address the issue.

```
diff --git a/src/shared/bus-util.c b/src/shared/bus-util.c
index e31fcfbd5a64..536589be1831 100644
--- a/src/shared/bus-util.c
+++ b/src/shared/bus-util.c
@@ -527,6 +527,8 @@ int bus_verify_polkit_async(
         }

         return 0;
+#else
+        return 1;
 #endif

         return -EACCES;
```

`systemd-hostnamed.service` uses `CapabilityBoundingSet=CAP_SYS_ADMIN`, hence it looks reasonable to think it would set the hostname accordingly if caller is systemd-networkd. Set hostname using CLI works like a charm however

**Comment by poettering** [comment]
well, networkd runs mostly unpriv, and it uses hostnamed to set the hostname, so that hostnamed verifies via polkit that it's ok to set the hostname and then allows it to unpriv networkd. Of course if you don't install polkit that's not going to work, networkd still won't have theprivs the change the hostname, and hostnamed doesn't allow it either, since there is no polkit to allow it...

So, it's the price you pay for avoiding polkit: permissions can't be placed fine-grained, and hence operations are forbidding to anything non-root.

You could run networkd as root so that hostnamed sees a privileged client and allows the hostname change even if polkit is not around, but that's dangerous...

I figure we could tweak networkd to first try the sethostname() syscall directly, before going via hostnamed to change it. That would allow people to add a drop-in for networkd if they wan, which adds CAP_SYS_ADMIN to networkd, which would allow networkd to do sethostname() directly without relying on hostnamed. Of course, running networkd with CAP_SYS_ADMIN is still ugly security-wise, but it's the best we could offer if you decide that finer-grained security via policykit is not your thing...

Anyway, @yuwata what do you think about trying sethostname() first in networkd, and only falling back to the hostnamed() logic if that results in EPERM/EACCES? that way @bjacquin could add the cap to networkd locally and it would just work.

**Comment by bluca** [comment]
FWIW I dealt with this (using Yocto where policykit's build is completely broken and nobody can figure out why) by running systemd-hostnamed as the systemd-network user, and with CAP_SYS_ADMIN as AmbientCap, and adding a new supplementary group systemd-hostnamed that owns the dbus service.
Requires dbus-broker, as dbus-daemon can't authenticate using supplementary groups, only via the primary.

This allowed me to avoid giving CAP_SYS_ADMIN or root to networkd.

**Comment by nefethael** [comment]
@bluca Thanks for details on Yocto workaround, is it implemented in open-source layer by any chance ? ;)

**Comment by bluca** [comment]
Unfortunately no, didn't have time to go through the yocto processes. But it's quite simple, there's no code change required - just configuration (and the dbus-broker dependency).

**Comment by bluca** [comment]
> FWIW I dealt with this (using Yocto where policykit's build is completely broken and nobody can figure out why) by running systemd-hostnamed as the systemd-network user, and with CAP_SYS_ADMIN as AmbientCap, and adding a new supplementary group systemd-hostnamed that owns the dbus service.
> Requires dbus-broker, as dbus-daemon can't authenticate using supplementary groups, only via the primary.
> 
> This allowed me to avoid giving CAP_SYS_ADMIN or root to networkd.

PR to implement this: https://github.com/systemd/systemd/pull/18608

**Comment by bluca** [comment]
> Unfortunately no, didn't have time to go through the yocto processes. But it's quite simple, there's no code change required - just configuration (and the dbus-broker dependency).

This is now merged in the yocto poky layer, and can be enabled via the 'polkit_hostnamed_fallback' PACKAGECONFIG (requires dbus-broker, also available in meta-openembedded):

https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=3dc37c12c17d5bb6d4701a425a4f79f6e31784ee

It can be fixed entirely with 2 drop-ins and an additional system group, no code changes required. Hence I think we can close this.

**Comment by xnox** [comment]
> > Unfortunately no, didn't have time to go through the yocto processes. But it's quite simple, there's no code change required - just configuration (and the dbus-broker dependency).
> 
> This is now merged in the yocto poky layer, and can be enabled via the 'polkit_hostnamed_fallback' PACKAGECONFIG (requires dbus-broker, also available in meta-openembedded):
> 
> https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=3dc37c12c17d5bb6d4701a425a4f79f6e31784ee
> 
> It can be fixed entirely with 2 drop-ins and an additional system group, no code changes required. Hence I think we can close this.

given above is only available out of tree / not in systemd project, i feel "close as not planned" is a better status. users interested in the workaround should see above.
