### ISSUE TITLE
predictable network device name change with kernel 5.2

### ISSUE THREAD

**Issue by dalu** [systemd/systemd#13514]
**systemd version the issue has been seen with**
> 242 243rc1 243rc2

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > Network device name remaining enp5s0

**Unexpected behaviour you saw**
 > Network device name changed from enp5s0 to p5s1 !!!

**Steps to reproduce the problem**

No effing clue

This took ages to resolve. This kept me busy at least 1 month.
At first I thought it was a megaraid_sas issue with the new kernel 5.2
But it turns out it was a network device naming issue.
Only when I had access to a remote kvm console I was able to see what really happened.

Idk why this isn't mentioned ANYWHERE! FFS. Yeah I'm pissed and I'm rightfully pissed.

How can you suddenly change the naming convention of devices without putting out some BIG ANNOUNCEMENT somewhere?

I'm not sure if it's just network devices or if more device names are affected.

Why would you DO something like this? It's not even consistent with the device ports on the hardware.

`05:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection`
yet
`2: p5p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP mode DEFAULT group default qlen 1000`

What the actual fuck?

Previously enp5s0, consitent. embedded network port 5 slot 0. bam. what does p5p1 say? not a thing.

**Comment by yuwata** [comment]
Please remove the swear words in your message, then provide the result of `SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/p5s1`.

**Comment by poettering** [comment]
It appears your bios has renumbered your slot assignments even though they are supposed to be stable. This is firmware misbehaviour. It sucks but theres nothing much we can do about that.

Not sure what triggered the renaming but we rely on the slot data the kernel provides us with and it usually gets that from the kernel. Hence ease contact the kernel peoe about this maybe they can fix something there but in userspace we have to rely on the data the kernel provides us with. As you noticed this changes when you update the kernel and if thats the only variable its something the kernel in interplay with the fimware is responsible for.

Hence, pelas contact your kernel maintainers (at distro or upstream level)
