### ISSUE TITLE
systemd-networkd fails completely if just one of the config files is not accessible

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13516]
Would it be possible to skip files that can't be opened due to EPERM without failing the entire systemd-networkd daemon? As it stands, the behavior of systemd-networkd is not very friendly.

First, systemd told me:

```
systemd-networkd[67775]: /etc/systemd/network/wg0.netdev has 0644 mode that is too permissive, please adjust the access mode.
```

I changed permission to 0600, and then:

```
Sep 10 04:56:46 l6 systemd[1]: Failed to start Network Service.
Sep 10 04:56:46 l6 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Sep 10 04:56:46 l6 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 04:56:46 l6 systemd-networkd[67765]: Could not load configuration files: Permission denied
```

See here, the fopen only skips config file on ENOENT error:

https://github.com/systemd/systemd/blob/f392c0656626824814704bdd624e02d56953dc2b/src/network/netdev/netdev.c#L663

A (requested) permission change on a non-essential interface should not cut all the network connectivity of the machine, completely.

**Comment by yuwata** [comment]
The file should owned by `systemd-network:systemd-network`, as the daemon is running with the user.

**Comment by megous** [comment]
Thank you very much for the improvement.
