### ISSUE TITLE
Can't use OnFailure with Restart

### ISSUE THREAD

**Issue by dmmarkov** [systemd/systemd#13517]
systemd v239

I have some service files where use Restart=Always and OnFailure handler
On previos versions every time when service fails systemd started handler and collect all information about system include core dumps. In the end archive of this information were sent to dev team. 
But now it's not work. It's restarting service but not triggering failure handler.

How can I fixed it?

**Comment by poettering** [comment]
Behaviour is clearly documented:

```
       OnFailure=
           A space-separated list of one or more units that are activated when this unit enters the "failed" state. A service unit using Restart= enters the failed state only after the start limits are reached.
```
