### ISSUE TITLE
DHCP did not send free ARP for address conflict detection when it got the address

### ISSUE THREAD

**Issue by 13242084001** [systemd/systemd#13525]
**systemd version the issue has been seen with**
> ...
systemd 237

**Used distribution**
 > …
ubuntu server 18.04
**Expected behaviour you didn't see**
 > …
Address collision detection without sending free ARP when using DHCP to automatically obtain address
**Unexpected behaviour you saw**
 > …
Send free ARP for address conflict detection；if conflict，Reuse DHCP request to get IP
**Steps to reproduce the problem**

**Comment by ssahani** [comment]
We have a library . Just need to hookup. But Why DHCP needs a address conflict? Can you explain.

**Comment by 13242084001** [comment]
My device is a dhcp client. I requested the obtained address to conflict with the address of other devices on the LAN. The device is manually configured. I need to do address conflict detection on the client side. Is systemd implemented?

**Comment by 13242084001** [comment]
> We have a library . Just need to hookup. But Why DHCP needs a address conflict? Can you explain.

My device is a dhcp client. I requested the obtained address to conflict with the address of other devices on the LAN. The device is manually configured. I need to do address conflict detection on the client side. Is systemd implemented?

**Comment by ssahani** [comment]
Should not be the static address with address conflict feature rather than the dhcp?

**Comment by 13242084001** [comment]
> Should not be the static address with address conflict feature rather than the dhcp?

LAN has many devices, some are automatically obtained using dhcp, some are using static configuration, we have no rules to avoid static configuration behavior, dhcp server does not have address conflict detection, so I hope dhcp client has this function

**Comment by ssahani** [comment]
I don't think the client also should have this feature since the IP is managed already by the dhcp server. It makes sense to have on static addresses where you set a ip just by guessing that no one would have it.

**Comment by 13242084001** [comment]
> I don't think the client also should have this feature since the IP is managed already by the dhcp server. It makes sense to have on static addresses where you set a ip just by guessing that no one would have it.

The address conflict detection function is indeed server-side behavior, but some clients implement this function, such as dhclient, which inserts arping to detect conflicts during the request address process, does not know if systemd provides this, or can help me add this function.
