### ISSUE TITLE
kernel panic during shutdown

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#13520]
**systemd version the issue has been seen with**
systemd 243.0-2

**Used distribution**
Manjaro testing

**Expected behaviour you didn't see**
Clean shutdown with no errors and no kernel panic

**Unexpected behaviour you saw**
Just by chance I saw that my PC throws errors incl. kernel panic whenever I shutdown the PC. The kernel with panic is 5.2.13.  Kernel 4.19.71-1 has no panic. There is no trace in the logs. But I have pictures:

![Bildschirmfoto_2019-09-10_18-01-00](https://user-images.githubusercontent.com/10911665/64636342-c82da080-d401-11e9-873e-f40241b80c43.png)

![Bildschirmfoto_2019-09-10_18-01-14](https://user-images.githubusercontent.com/10911665/64636351-cd8aeb00-d401-11e9-9458-5fcb8afd9209.png)

The issue was caused by this update:

```
[2019-09-06 22:31] [ALPM] upgraded systemd-libs (242.85-2 -> 243.0-2)
[2019-09-06 22:31] [ALPM] upgraded systemd (242.85-2 -> 243.0-2)
[2019-09-06 22:33] [ALPM] upgraded systemd-resolvconf (242.85-2 -> 243.0-2)
[2019-09-06 22:33] [ALPM] upgraded systemd-sysvcompat (242.85-2 -> 243.0-2)
```

Downgrading solves the issue:

```
[2019-09-10 18:53] [ALPM] downgraded systemd (243.0-2 -> 242.85-2)
[2019-09-10 18:54] [ALPM] downgraded systemd-libs (243.0-2 -> 242.85-2)
[2019-09-10 18:55] [ALPM] downgraded systemd-resolvconf (243.0-2 -> 242.85-2)
[2019-09-10 18:55] [ALPM] downgraded systemd-sysvcompat (243.0-2 -> 242.85-2)
```

**Comment by poettering** [comment]
Umm. Kernel oopses are never something userspace should be able to trigger. Unfortunately your second pic cuts off where the interesting bits follow.

Either way this doesnt look like a systemd prob. If the kernel oopses its a kernel problem. Please contact your distro about this first.

(Also drop vbox kernel modules which arent upstream before testing. Kernel folks dont like testing that.)

Anyway. Closing this here.

**Comment by philmmanjaro** [comment]
After doing a [git-bisect](https://raw.githubusercontent.com/philmmanjaro/systemd/master/git-bisect/git-bisect.txt) it all comes down to:

https://github.com/systemd/systemd/pull/12153

Also what is interesting is: it happens on **Ryzen** CPUs. From [given reports](https://forum.manjaro.org/t/testing-update-2019-12-16-kde-git-systemd-v244-1-upstream-rebuilds/115364/20) **Intel** seems to be fine.
