### ISSUE TITLE
RFE: option for creating fully locked accounts with systemd-sysusers

### ISSUE THREAD

**Issue by hunger** [systemd/systemd#13522]
**Is your feature request related to a problem? Please describe.**
Arch linux adds a systemd-sysusers configuration file for the user used by gdm.

This fails to work after upgrading to systemd 243: The user is now created as expired, which will stop gdm from working with the PAM configuration that has worked so far.

**Describe the solution you'd like**
It would be great if systemd-sysusers could create unexpired users as it did up to version 242 -- at least optionally.

**Describe alternatives you've considered**
I played with pam by adding "account require pam_permit.so" into gdm-launch-environment, and systemd-user.

It just feels terribly wrong to use pam_permit.so in response to systemd-sysuser creating expired users with the intention to improve overall system security!

**Comment by loqs** [comment]
The related arch bug report is https://bugs.archlinux.org/task/63706

**Comment by poettering** [comment]
hmm, i wonder why gdm even calls into the acct mgmt PAM hooks... i am a bit surprised it does that..

**Comment by Strit** [comment]
This also happens with SDDM.

**Comment by amishmm** [comment]
The said change broke all my scripts using "su postgres -c command" because postgres account is now created as "expired" account in new installation of Arch linux.

And su now does not run the script stating that user account has expired.

Am I doing anything wrong by using su? Or this change is indeed too paranoid?

**Comment by heftig** [comment]
> Am I doing anything wrong by using su?

It's an effect of `/etc/pam.d/su` including the line `account required pam_unix.so`.

You can either replace that with `account required pam_permit.so`, which will remove the account validity check; or you can use `sudo -u postgres command`, which checks validity for the *invoking* user and not the *target* user.

**Comment by keszybz** [comment]
Yeah, I don't think we should mark accounts as locked if we intend to use them.

**Comment by poettering** [comment]
Since #13813 was merged let's close this.

**Comment by keszybz** [comment]
The idea was to keep this one open to reimplement an (opt-in) mode in sysusers where the account is created locked. Making it unconditional was causing problems, but only sometimes, so I think it is a reasonable request to make that possible.
