### ISSUE TITLE
systemd.networkd - .network files - flushing addresses - if networkd is going to _manage_ interfaces...

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#1352]
Referencing Issue #969, where Lennart asserts:

"networkd should take precedence. If you don't want networkd to manage your interfaces, then don't tell it to. If you do want it to manage your interface, then it should do that comprehensive[l]y."

Consider comprehensive network interface management by networkd.  Currently, networkd does not reconfigure or "flush" addresses when they are configured.  But there are situations in which reconfiguration is required and must be applied through some management user interface.  In particular, for instance, a long-lived precision time server that must remain stable and cannot simply be re-booted, but which also must be reconfigured for occasional network changes, will require that the "old" interface address be removed.  More generally, any managed mobile device will require that an "old" interface address be removed.  

Supposing that "Address=" can be automatically revised in a .network file, some kind of "FlushAddresses=yes" setting would be very useful, to have networkd remove the "old" address or addresses when invoking "restart" or "reload-or-restart" on systemd-networkd.  Of course this desired behavior is different from when networkd is instead "started" or "stopped".   At the moment, systemd-networkd.service can be modified to include "ExecReload=" with "/usr/bin/ip addr flush dev <some-device-name>", but then each device name must be derived automatically or passed manually to the .service file.  In this case, using "ExecReload=" would be a bit of a "hack", and not "comprehensive network management" using .network files.

In a larger scope, assuming that networkd is managing interfaces, how should networkd, itself, be managed?  Suppose that networkd is managing interfaces on resource limited embedded devices, and that the various .network files require configuration or reconfiguration through some web-based User Interface system, for instance.  Are programmers "on their own", using automated text editors on .network files?   Or, is there some part of libsystemd that can be invoked to simplify, for instance, parsing and revising .network files, or, more directly, the systemd or networkd "state"?

**Comment by poettering** [comment]
This is a bug and feature request tracker, not a discussion forum. I don't see any bug or explicit feature request in this issue, will close. Please bring discussion issues up on the mailing list. Thanks.
