### ISSUE TITLE
Cannot login as root from console into systemd-nspawn container

### ISSUE THREAD

**Issue by jernst** [systemd/systemd#13532]
This behavior is new in 243.0-1 (Arch x86_64)

Attempting to log on as root from the console of a container started with something like:
```
systemd-nspawn -b -n -D dir --console=interactive
```
now produces error:
```
Login incorrect
```
and the journal says:
```
pam_securetty(login:auth): access denied: tty 'pts/0' is not secure !
FAILED LOGIN 1 FROM pts/0 FOR root, Authentication failure
```

If that tty is added to `/etc/securetty`, login works again.

It appears to be inconsistent with systemd-nspawn(1) which states:
```
       --console=MODE
           ...  If interactive a pseudo-TTY is allocated and made available as /dev/console in the container.
```

**Comment by poettering** [comment]
pam_securetty is a really bad idea. Just remove it. Most big distros did

Please work with your distro to either remove/disable it too or to at least whitelist all possible ttys (which makes the concept useless though)

Its a remnant from an old time that doesnt exist anymore.

Anyway. Lets close as this is something your distro has to figure out. Most big distros Already have. 

/dev/console is just an alias for a more specific tty hence the ambigutiy in the messages...
