### ISSUE TITLE
gdm does not spawn in a new vt after upgrade from 242.84 to 243.0 (in lxc container)

### ISSUE THREAD

**Issue by odror** [systemd/systemd#13531]
**systemd version the issue has been seen with**
> 243.0 

Distribution: Archlinux
 > …

I have archlinux running in lxc container (ubuntu 19.04 host) It is setup with complete passthrough to the nvidia graphics card (GTX 1070). I have recompiled gdm with the flag
--with-initial-vt=8. So that it will not conflict with the host gdm.

On version 242.84 and bellow gdm start with no issues.

On the current version of systemd (243.0-1) gdm starts, but does not spawn in any of the VTs. 
journalctl -b -u gdm has the folloing error:

```
Sep 11 19:04:50 arch gdm-launch-environment][167]: pam_systemd(gdm-launch-environment:session): Failed to create session: Seat has no VTs but VT number not 0
```
I am guessing it is some how connected to a change in pam_systemd.  Possibly it  detects that it is in lxc container and block access to the VTs.

The issue reproduces 100% of the time in version 243, when downgrading to version 242 the issues gone. reproducing just by starting the lxc container with systemd version 243 installed.

**Comment by poettering** [comment]
uh, sorry, but  device passthr in containers cannot really work. We check sysfs/udev to see if a device supports graphics, and since linux doesn't virtualize /sys and udev doesn't run a container we cannot support that sorry.

Please work with the kernel people to virtualize /sys, only then udev and logind and so on can work.

Sorry.

**Comment by galeksandrp** [comment]
Looks like this error not only giving me trouble with devices, but with `loginctl` as well.

Loggin on `/dev/tty1` gives me empty `loginctl`

```
[galek@xxl ~]$ loginctl
No sessions.
```

whereas loggin via `ssh` running in `container` gives me

```
[galek@xxl ~]$ loginctl
SESSION  UID USER  SEAT TTY    STATE  IDLE SINCE
     87 1000 galek -    pts/16 active no   -

1 sessions listed.
```

**Comment by galeksandrp** [comment]
Okay, I don't have any devices passthroughed to LXC container

But `pam_systemd` prevents `login` givin out sessions on LXC `VTs`

```
login[127]: pam_systemd(login:session): Failed to create session: Seat has no VTs but VT number not 0
```

Login on `/dev/tty1` provided by LXC
```
[root@xxl ~]# loginctl
No sessions.
```
Login on `/dev/console` provided by LXC
```
[root@xxl ~]# loginctl
SESSION UID USER SEAT  TTY     STATE  IDLE SINCE
     26   0 root seat0 console active no   -    

1 sessions listed.
```
