### ISSUE TITLE
Incomplete Documentation for TimeoutCleanSec= (Maybe)?

### ISSUE THREAD

**Issue by SJrX** [systemd/systemd#13546]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > N/A

**Expected behaviour you didn't see**
 > Documentation for `TimeoutCleanSec=` that applies to Mount, Socket and Swap unit file types.

**Unexpected behaviour you saw**
 > No Documentation

**Steps to reproduce the problem**
I maintain a syntax highlighter for systemd and I'm in the process of updating it for v243, and maybe v242. One of my CI tasks validates that I have documentation for every supported option., which I pull from the the macro processed version of this file: [load-fragment-gperf.gperf.m4](https://github.com/systemd/systemd/blob/master/src/core/load-fragment-gperf.gperf.m4#L141)

I am not sure about `TimeoutCleanSec`, in this commit from PR #13385 it was [moved from the Service to Exec context](https://github.com/systemd/systemd/commit/12213aed128456af33ff6131a14b637318227346), but the documentation wasn't updated, it is only documented for [Services](https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutCleanSec=)

I'm not familiar with the option of systemctl clean, but it also seems TimeoutCleanSec should also apply to Timers (at least that's my read of [this](https://www.freedesktop.org/software/systemd/man/systemctl.html#clean%20PATTERN%E2%80%A6).

**Comment by yuwata** [comment]
Fix is waiting in #13548.

**Comment by SJrX** [comment]
@yuwata I was just curious based on my read of the documentation, should Timers also have this feature? I noticed from the man page that this affects anything that can be cleaned, which timers can be.

**Comment by yuwata** [comment]
> @yuwata I was just curious based on my read of the documentation, should Timers also have this feature? I noticed from the man page that this affects anything that can be cleaned, which timers can be.

No. `[Timer]` section cannot contain any options explained in systemd.exec(5).
