### ISSUE TITLE
Assertion failure during daemon-reload

### ISSUE THREAD

**Issue by yshui** [systemd/systemd#13552]
**systemd version the issue has been seen with**
243

**Used distribution**
Arch Linux

**Unexpected behaviour you saw**
Assertion failure when running `daemon-reload`

**Steps to reproduce the problem**
Sorry but I don't have a way to reproduce this problem.

**Other information**
* Assertion failure message:
  ```
  Assertion '*_head == _item' failed at src/core/unit.c:673, function unit_free(). Aborting.
  ```
* systemd is stripped, so stack trace is not very helpful:
  ```
  Process 252322 (systemd) of user 0 dumped core.

  Stack trace of thread 252322:
  #0  0x00007f178aba6a5b kill (libc.so.6)
  #1  0x0000562135f5abbe n/a (systemd)
  #2  0x00007f178aba67e0 __restore_rt (libc.so.6)
  #3  0x00007f178aba6755 raise (libc.so.6)
  #4  0x00007f178ab91851 abort (libc.so.6)
  #5  0x00007f178a90a059 n/a (libsystemd-shared-243.so)
  #6  0x0000562135ef91e3 n/a (systemd)
  #7  0x0000562135f25ed5 n/a (systemd)
  #8  0x0000562135f581cf n/a (systemd)
  #9  0x0000562135eaf6ef n/a (systemd)
  #10 0x00007f178ab92ee3 __libc_start_main (libc.so.6)
  #11 0x0000562135eb052e n/a (systemd)
  ```

**Comment by yuwata** [comment]
Could you include debug information?

**Comment by keszybz** [comment]
This could be anything... Let's wait for the reporter to provide a usable backtrace.

**Comment by yshui** [comment]
I will build systemd with debug info, but I don't know when this will happen again.

**Comment by poettering** [comment]
Closing due to lack of response. if you manage to acquire a backtrace with symbols for this, please provide and reopen! thanks!
