### ISSUE TITLE
systemd-networkd dropping network configurations created by other applications

### ISSUE THREAD

**Issue by matthewbassett** [systemd/systemd#13555]
**systemd version the issue has been seen with**
> ...
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID
 +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > Upon a `sudo systemctl restart systemd-networkd` I expect for IP's and network configurations created by other applications to be kept, however they are lost. This happens with apt upgrade's as well as randomly if systemd-networkd restarts

**Unexpected behaviour you saw**
 > IP's and interfaces configured by other applications were lost

**Steps to reproduce the problem**
Install keepalived and create a floating IP address with it. then run `sudo systemctl restart systemd-networkd`

**Comment by yuwata** [comment]
Please use the following in your .network file:
- v242 or earlier (even if you do not use DHCP client in `networkd`)
```
[DHCP]
CriticalConnection=yes
```
- v243 or newer
```
[Network]
KeepConfiguration=yes
```

**Comment by matthewbassett** [comment]
Hi,

Thanks for the ideas. This does not work for me however, unless I am
missing something.

The .network files I am updating are in /lib/systemd/network

After attempting to add the CriticalConnection=yes to the DHCP block of the
config, I restart systemd-network, and it is still dropping the floating IP
I have on the VM using keepalived

Further thoughts?

Thanks!

**Comment by yuwata** [comment]
Have you add that block to the .network file which actually assigned to the interface?
Please show `networkctl status` and the .network file you modified.

**Comment by matthewbassett** [comment]
Thanks for the reply. I dug a bit deeper into it, and the reason it didn't
work is because all of the .network files I was editing were not the right
ones. If I'm understanding correctly then I think netplan actually creates
the .network file on the fly in /run/systemd/network
I am going to try to use networkmanager as the renderer instead of
systemd-networkd and see where that gets me.

Feel free to close this.
