### ISSUE TITLE
systemd-nspawn requires mqueue to be activated in the kernel

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#13560]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > buildroot

**Expected behaviour you didn't see**
 > systemd-nspawn -i <an image> should start

**Unexpected behaviour you saw**
 > systemd-nspawn fails with
Failed to mount mqueue (type mqueue) on /tmp/nspawn-root-BPVXoj/dev/mqueue (0 ""): No such device
**Steps to reproduce the problem**
start a container with a kernel without the POSIX_MQUEUE option compiled in. Adding that option to the kernel solves that problem.

I am reporting that because according to the README file, this option is not mentionned and (afaikt) is not required by systemd itself, only by systemd nspawn. 

I am not sure if the README must be fixed or if nspawn should test the kernel feature and just not mount /dev/mqueue if the kernel doesn't support it

**Comment by boucman** [comment]
I am not sure how to fix it if mqueue is supposed to be optional, but in case it's just a documentation
problem, I added a patch

**Comment by keszybz** [comment]
I would prefer to patch nspawn to not require mqueue... It is a bit of a fringe interface and it should be fairly easy to make this optional.

**Comment by keszybz** [comment]
Hmmm, I think you need to test this with recent systemd. With current, git, after s/mqueue/mqueuea/g, I get:
```
...
Mounting mqueuea on /dev/mqueuea (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Failed to mount mqueuea (type mqueuea) on /dev/mqueuea (MS_NOSUID|MS_NODEV|MS_NOEXEC ""): No such device
Mounting sysfs on /sys/full (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Bind-mounting /sys/full/block on /sys/block (MS_BIND "")...
...
```
The mqueue mount is not marked as `MOUNT_FATAL`, so it is expected that the failure will be ignored.

**Comment by boucman** [comment]
I tested with 240, i'll retest with 243 ASAP

**Comment by boucman** [comment]
ok, so it seems good with 243, sorry for the noise...
