### ISSUE TITLE
StatusUnitFormat setting has no effect

### ISSUE THREAD

**Issue by stanczew** [systemd/systemd#13563]
**systemd version the issue has been seen with**
systemd 243 (243.0-1-arch)

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
After setting `StatusUnitFormat=name` in system.conf/user.conf, system/user manager would use unit names instead of descriptions:
`(...) systemd[1]: Starting systemd-journal-flush.service...`

**Unexpected behaviour you saw**
System/user manager still uses description when printing unit names:
`(...) systemd[1]: Starting Flush Journal to Persistent Storage...`

**Steps to reproduce the problem**
Set `StatusUnitFormat=name` in any configuration file and reboot (or reexec + start/stop/restart any unit to trigger log message).

**Other info**
System manager will use names instead of descriptions when `systemd.status_unit_format=name` kernel command line option is used.

I did some debugging and found out that the configuration is parsed properly (`status_unit_format_from_string` returns 0 for `name` and 1 for `description`). However the `DEFINE_SETTER` macro used to generate `config_parse_status_unit_format` function doesn't actually store the computed value anywhere, so `arg_status_unit_format` variable will still have its old value (= the default, which is `description` on Arch) after the configuration is parsed.

I've prepared a change that helped in my case:
[0001-Fix-setting-StatusUnitFormat-from-config-files.patch.txt](https://github.com/systemd/systemd/files/3613578/0001-Fix-setting-StatusUnitFormat-from-config-files.patch.txt)
I don't know if this is the right approach – I just copy-pasted the relevant parts from the analogous setting, `ShowStatus`.

**Comment by yuwata** [comment]
Please submit as a PR. Thank you.

Note that please use `DEFINE_CONFIG_PARSE_ENUM()` macro.

**Comment by stanczew** [comment]
> Note that please use `DEFINE_CONFIG_PARSE_ENUM()` macro.
Well, that makes the change much simpler, thank you.
PR submitted: #13571
