### ISSUE TITLE
systemd-networkd does not clean up old IPv6 prefix delegation routes from downstream interfaces

### ISSUE THREAD

**Issue by georgmu** [systemd/systemd#13564]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > debian 10 (buster)

**Expected behaviour you didn't see**
 > When I get a new prefix via IA_PD from the router, the old routes should be deleted

**Unexpected behaviour you saw**
 > Routes don't get cleaned up.

**Steps to reproduce the problem**
I get a new IPv6 pool every day from my ISP. I use prefix delegation to provide IPv6 in the network. After 5 days, I saw 5 IPv6 prefixes on the internal interface. The old ones do not get cleaned up. I will try to get a PCAP from the router at the time of address change.

But even if there is no kind of "de-announcement" from the router for the old prefix, the prefix delegation has a valid lifetime of 2 hours. At least this should be honored and the route should be deleted after it is invalid.

Restarting systemd-networkd cleans up all IPv6 routes

**Comment by georgmu** [comment]
I checked the router advertisment messages.

The old prefixes are still in the router advertisment packets, with a preferred lifetime of 0 and a valid lifetime counting down to 0 as well.

So two hours after the address change, the valid lifetime reaches 0. The route is reported with both valid and preferred lifetime of 0 aftherwards. So every day the router advertisment message grows by 32 bytes for the new route.

I will check the RFC for what to do in detail, but if both valid and preferred lifetime is zero, the routes should be cleaned up.

**Comment by georgmu** [comment]
I have not found anything specific in RFC 4862 or RFC 6204, but since it makes no sense to provide invalid (valid lifetime = 0) route information, this should be the point to remove the prefix.

**Comment by georgmu** [comment]
The patch above is not enough:
It does not clean up the prefix in dhcp6 and does not remove the route. I will try to find a better place to clean up the routes.

Better would be to somewhere call dhcp6_prefix_remove() with the correct address after the route becomes invalid.

**Comment by yuwata** [comment]
@georgmu If possible, could you test #16585?

**Comment by georgmu** [comment]
I will prepare a test and see if it is fixed
