### ISSUE TITLE
RFE: Universal SyslogIdentifier Option in Service Files

### ISSUE THREAD

**Issue by archuserr** [systemd/systemd#13566]
I have several python programs that start from .service or .timer files. My problem is that in the journal, all of them have ```SYSLOG_IDENTIFIER=python3```. Sometimes It's difficult/impossible to determine which program generated the message.

I made the same mistake as bug #8687 thinking SyslogIdentifier would solve this. Can we either expand the functionality of SyslogIdentifier or add a new option to set ```SYSLOG_IDENTIFIER``` for all journal entries?

An alternative is using ```-o with-unit```, but I also need ```short-precise``` and I can't use both at the same time. Also with ```with-unit```, long file names don't leave much space for the message.

My current/temporary solution is adding the program name to the message python sends to the journal, but that uses valuable space. My screen isn't wide enough.

**Comment by archuserr** [comment]
I tried using ```prctl(PR_SET_NAME, ...)``` to change the process name. ps and top use the new name, but the journal does not.

**Comment by poettering** [comment]
How does your program log? Via stderr or via syslog() or an equivalent call?

**Comment by archuserr** [comment]
I solved my problem. I installed the python-systemd module. It lets me set the process name:

```
systemd.journal.send('my message', SYSLOG_IDENTIFIER='myProgram', PRIORITY=systemd.journal.LOG_INFO)
```

Thanks!
