### ISSUE TITLE
 main process exited, code=dumped, status=11/SEGV

### ISSUE THREAD

**Issue by guoyanzhang0817** [systemd/systemd#13574]
```
# journalctl -feu iot.service
Feb 24 14:27:16 huawei iot[226]: The data we received is: 0X4 0X1 0X50 0X86 0X67
Feb 24 14:28:21 huawei iot[226]: The data we receive
Feb 24 14:28:21 huawei systemd[1]: iot.service: main process exited, code=dumped, status=11/SEGV
Feb 24 14:28:21 huawei systemd[1]: Unit iot.service entered failed state.
Feb 24 14:28:21 huawei systemd[1]: iot.service holdoff time over, scheduling restart.
Feb 24 14:28:21 huawei systemd[1]: Stopping EC_iot service test...
Feb 24 14:28:21 huawei systemd[1]: Starting EC_iot service test...
Feb 24 14:28:21 huawei systemd[1]: Started EC_iot service test.
```
The iot is a C-compiled executable. There is no problem with running the ./iot executable alone, but when I turn it into iot.service, this problem occurs. Why?
```
cat /etc/systemd/system/iot.service
[Unit]
Description=EC_iot service test
After=network.target mosquitto.service
[Service]
Type=simple
ExecStart=/usr/bin/iot
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always
[Install]
WantedBy=multi-user.target
```

**Comment by yuwata** [comment]
Please enable debugging logs. Otherwise there is almost nothing we can do. `systemd-analyze log-level debug` may help you.

**Comment by guoyanzhang0817** [comment]
# systemd-analyze set-log-level debug
...
Feb 24 14:40:58 huawei iot[250]: The data we received is: 0X4 0X1 0X50 0X86 0X67
Feb 24 14:41:26 huawei iot[250]: The data we received i
Feb 24 14:41:26 huawei systemd[1]: Child 250 belongs to iot.service
Feb 24 14:41:26 huawei systemd[1]: iot.service: main process exited, code=dumped, status=11/SEGV
Feb 24 14:41:26 huawei systemd[1]: iot.service changed running -> failed
Feb 24 14:41:26 huawei systemd[1]: Unit iot.service entered failed state.
Feb 24 14:41:26 huawei systemd[1]: iot.service changed failed -> auto-restart
Feb 24 14:41:26 huawei systemd[1]: iot.service: cgroup is empty
Feb 24 14:41:26 huawei systemd[1]: iot.service holdoff time over, scheduling restart.
Feb 24 14:41:26 huawei systemd[1]: Trying to enqueue job iot.service/restart/fail
Feb 24 14:41:26 huawei systemd[1]: Installed new job iot.service/restart as 375
Feb 24 14:41:26 huawei systemd[1]: Enqueued job iot.service/restart as 375
Feb 24 14:41:26 huawei systemd[1]: iot.service scheduled restart job.
Feb 24 14:41:26 huawei systemd[1]: Stopping EC_iot service test...
Feb 24 14:41:26 huawei systemd[1]: iot.service changed auto-restart -> dead
Feb 24 14:41:26 huawei systemd[1]: Job iot.service/restart finished, result=done
Feb 24 14:41:26 huawei systemd[1]: Converting job iot.service/restart -> iot.service/start
Feb 24 14:41:26 huawei systemd[1]: Starting EC_iot service test...
Feb 24 14:41:26 huawei systemd[1]: About to execute: /usr/bin/iot
Feb 24 14:41:26 huawei systemd[1]: Forked /usr/bin/iot as 259
Feb 24 14:41:26 huawei systemd[1]: iot.service changed dead -> running
Feb 24 14:41:26 huawei systemd[1]: Job iot.service/start finished, result=done
Feb 24 14:41:26 huawei systemd[1]: Started EC_iot service test.
Feb 24 14:41:27 huawei systemd[259]: Executing: /usr/bin/iot
...

**Comment by keszybz** [comment]
Try running the service under valgrind:
...
ExecStart=/usr/bin/valgrind /usr/bin/iot
...

Anyway, this is not our bug.

**Comment by yuwata** [comment]
Also, `coredumpctl` may help you. Cheers.

**Comment by noahsdonaldson** [comment]
Was there a resolution to this?  I installed IoT Edge on Ubuntu 19.10 with ARM64 hardware and getting the exact same "iotedge.service: Main process exited, code=dumped, status=11/SEGV"

**Comment by boucman** [comment]
as pointed above, this is not a systemd bug but an iotedge bug. Pleaser report/check with your distro. There is nothing systemd can do about this...

Sorry.
