### ISSUE TITLE
timesyncd: sync log message construction

### ISSUE THREAD

**Issue by brubbel** [systemd/systemd#13586]
See https://github.com/systemd/systemd/issues/11548, https://github.com/systemd/systemd/commit/3a1e46f7ae8d11e44b61c1975f750bd26a2d1851

The new log message sounds weird.
`Synchronized to time server for the first time 193.104.37.238:123 (2.debian.pool.ntp.org).`

Suggested alternative:
`Initial sync to time server 193.104.37.238:123 (2.debian.pool.ntp.org).`

**Comment by brubbel** [comment]
On a related note, is there an official way to find out which one of the servers configured in /etc/systemd/timesyncd.conf is currently used?

**Comment by yuwata** [comment]
> On a related note, is there an official way to find out which one of the servers configured in /etc/systemd/timesyncd.conf is currently used?

Please use `timedatectl`.

**Comment by brubbel** [comment]
Thanks: `timedatectl timesync-status` did the trick.
