### ISSUE TITLE
Allow lapsed trigger to fire when oncalendar points to time that already passed

### ISSUE THREAD

**Issue by osce0** [systemd/systemd#13584]
**systemd version the issue has been seen with**
> 241, master as of 2019-09-17

**Used distribution**
 > Fedora 30 x86_64 stock rpm, master rebuilt rpm

**Expected behaviour you didn't see**
 > systemd timer unit that starts later in the day and had never run the event for the day should trigger an event when OnCalendar=daily

**Unexpected behaviour you saw**
 > when the event never occurred today, it will never occur until tomorrow 0:01am or so; if the timer is disabled due to shutdown overnight, it will never occur ever. This is a problem with logrotate unit which should definitely run any time it didn't run around 0:01am for the day.

**Steps to reproduce the problem**
systemd-run --user -d --on-calendar=daily touch z
ls z

**Comment by osce0** [comment]
Some further comments. Issue #12299 seems to be a regression of a fix for this issue that existed in 241.

This (could actually be a feature) could also solve the summer time skipping issue #5595. Basically, there needs to be a way to specify a repeating relative time event rather than absolute time event. If i mean 'daily', I really mean the beginning of the day, I don't really mean absolute 0:00am of that day. Another example is, 2:30am really means 2 hours and 30 minutes from 0:00am of the day, not an absolute 2:30AM of that day. The only time we should not trigger is if it's over 23 hours and there is only 23 hours in the day.

cron service mostly meant all time to be more or less relative time, not absolute time, because most repeating timed events were not meant for absolute time, but relative time. Even if one argues that 'oncalendar' really means absolute time, 'oncalendar=daily' really is not an absolute time, because it just means from the start of the day, whatever the start of the day is. And if the event didn't trigger for that day, it should trigger when the timer starts.

I guess one option is to add an argument '--relative-time' or something so one can be clear whether we really mean a relative repeating time interval from the beginning of some reference time. So then 'daily' would mean any time between 0am of today and now, rather than absolute 0:00AM. Not sure whether we can complicate this further by keeping track of whether the event was ever triggered between 0am and now. It will still be ok to just go ahead and trigger the event anyway if past the time rather than keeping the past states.

**Comment by poettering** [comment]
Well, I'd argue that if you have a daily timer and you want it to trigger immediately when the timer first started (because it always is after 0 o'clock of some day), then just add Wants=xyz.service too the timer unit (if it is called xyz.timer). i.e. the actual timer elapsing is just one way of activation, and you might as well combine it with direct pulling it in. This is a lot more powerful then what I understand you are proposing, i.e. that we should instantly trigger any repetitive calendar expression if it could ever elapse before, since it allows people to easily implement both options...

Or what am I missing?

**Comment by poettering** [comment]
let's close this, due to lack of response.
