### ISSUE TITLE
90-loaderentry.install isn't aware of LUKS

### ISSUE THREAD

**Issue by cognition9144** [systemd/systemd#13594]
**systemd version the issue has been seen with**
> 242.108-1

**Used distribution**
 > Description:	Manjaro Linux
Release:	18.1.0

**Expected behaviour you didn't see**
This is related to systemd-boot. `/usr/lib/kernel/install.d/90-loaderentry.install`, which is called after a new kernel is installed, should detect the LUKS configuration in the system and fill the correct kernel parameter in boot entries' `option` (e.g. `options cryptdevice=UUID=device-UUID:cryptroot root=/dev/mapper/cryptroot`).

As systemd-boot remembers the password when we enter the password at startup, it's unnecessary to add anything to `/etc/grub`. So auto-detect the LUKS configuration might be tricky.

**Unexpected behaviour you saw**
 `90-loaderentry.install` generates `options	root=PARTUUID= rw rootflags=subvol=/@ `

**Steps to reproduce the problem**
Install a kernel which isn't previously installed in the system.

**Comment by xcffl** [comment]
It seems not systemd itself, but https://gitlab.com/dalto.8/systemd-boot-manager/ to blame
