### ISSUE TITLE
systemd-random-seed.service lack of entropy 

### ISSUE THREAD

**Issue by Bundy01** [systemd/systemd#13602]
**systemd version the issue has been seen with**
> ...systemd  243.0-1

**Used distribution**
 > …Archlinux

**Expected behaviour you didn't see**
 > …This service is slow to launch due to lack of entropy

**Unexpected behaviour you saw**
 > …`systemd-analize blame: 16.746s systemd-random-seed.service ` on ssd

`systemctl status systemd-random-seed.service`: 
```● systemd-random-seed.service - Load/Save Random Seed
   Loaded: loaded (/usr/lib/systemd/system/systemd-random-seed.service; static; vendor preset: disabled)
   Active: active (exited) since Thu 2019-09-19 22:20:56 CEST; 1h 36min ago
     Docs: man:systemd-random-seed.service(8)
           man:random(4)
  Process: 258 ExecStart=/usr/lib/systemd/systemd-random-seed load (code=exited, status=0/SUCCESS)
 Main PID: 258 (code=exited, status=0/SUCCESS)

sept. 19 22:20:39 desktop systemd-random-seed[258]: Kernel entropy pool is not initialized yet, waiting until it is.
sept. 19 22:20:56 desktop systemd[1]: Started Load/Save Random Seed.
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

**Steps to reproduce the problem**
When installing the Systemd 243.0-1 package.
See https://bugs.archlinux.org/task/63738

Regards.

**Comment by poettering** [comment]
Yeah. This is the is kinda the point of the service. Its intended to be a sync point for services that require an initialized pool (for example luks swap devices that specify /dev/urandom as key source) to work safely and correctly. While it is generally pulled into the boot only services needing that should need to require and order themselves after it.

If you want to fix this either provide the entropy somehow or figure out which service blocks on it. Other than that there is no bug.

Also see:

https://systemd.io/RANDOM_SEEDS

**Comment by sharkwouter** [comment]
I'm experiencing this same issue, but it is much more severe on my system. The systemd-random-seed.service adds 2 minutes to the boot time of my system, even though I'm booting from an SSD. Is there an alternative way to make it start up faster?

**Comment by ShrirajHegde** [comment]
My system gets stuck in tty and to continue,I have to switch to a different tty and switch back 
Unable to fix it.

https://www.reddit.com/r/archlinux/comments/jx69y2/arch_startup_gets_stuck_at_tty1_on_fresh_install/
