### ISSUE TITLE
c# systemd api bindings

### ISSUE THREAD

**Issue by dorvan** [systemd/systemd#1360]
is planned the c# systemd api bindings  development?
thanks.

**Comment by zonque** [comment]
Not as far as I know. But if we did, we should definitely keep the glue code out of the main repository. The new repository could still live under the GitHub 'systemd' organization though.

**Comment by poettering** [comment]
This is not a discussion forum but a bug tracker. Please direct question like yours to the mailing list instead. Thanks. Closing.
