### ISSUE TITLE
Don't merge homed just yet major design flaw. Single file identiy.

### ISSUE THREAD

**Issue by oiaohm** [systemd/systemd#13616]
**systemd version the issue has been seen with**
homed branch by Poettering
https://github.com/poettering/systemd/blob/homed/docs/HOME_DIRECTORY.md
The mistake is documented here and in the code.

**Expected behaviour you didn't see**
Safe to update values without locking users out

**Unexpected behaviour you saw**
 Will lock users out.

**Steps to reproduce the problem**
Delete the ~/.identity as if a record update to file has resulted in file being lost in write and watch it not recover and lock the user out.

This is a major design flaw.  One of the reasons why apache and others added .d directory to their configurations was so that when programs were adding/modify settings the complete lot was not lost if there was a file system lose of file.

At a min you need like ~/.identity1 and ~/.identity2  In the documentation and implementation  ~/.identify1 to be written first once successful duplicated to .identity2 .   Yes on login both checked to be the same.  If ~/.identify1 is missing/damaged on login recreate using  ~/idenitity2 if it exists and is intact.   If ~/identity1 is ok and ~/identity2 does not match ~/idenitity on login sync to ~/identity2 as there was update failure on ~/identity2. 

This is the bare min that needs to be done.   User is only locked out then with 2 files have been screwed up by then things are normally majorly wrong.   Normally will not be some fluke chance.

 I would very much prefer a directory structure.

~/.identity/(Signed by)/ identity.d
Signed by the short of the signing key .   identity.d directory used for add on parts that you absolute don't want a screw up resulting not being able to login to fix or for parts particular hosts choose to allow users to modify unsigned.   Like you may not care as administrator if a person changes their display name/display icon so it does not need to be signed.

I am also not happy with the idea of allow user by who signed the record either.    You may only want to allow one person from a particular set of signed records on a particular system.

/etc/identity/(Signed by)/allowed
/etc/identity/(Signed by)/banned
Comes to mind allowed/banned directories holding copies identity files of those the system will accept.   This is another reason for identity.d when going this route you may not want ssh keys in central.   Yes setting can be anything not in allowed signed by a particular party is not allowed in.  

The (Signed by) directory could contain a overlay identify file.   A file that list what settings will be acceptable to the host in the identity file. 

Lets say there is a machine that a person need to submit records to archive the fact that user is a member of wheel group in there  identity would give them rights to modify the archive machine if you allowed them to use a mobile account but they are administrator for other systems.   Do we want to have to issue identity twice or do we want to say if on this machine with identity signed by X part following identity values in the portable home will be overwritten/ignored like that by identity its a wheel group user but on this machine they are not because the configuration of system says that value is not acceptable.

I can understand if homed does not end up with a directory structure like this.   Remember people with removeable media and network cables have habit removing connection at times before file syncs are properly complete so resulting in magically disappearing files.

/etc/passwd not being extendable is also because you don't want to be writing to it a lot.   Yes there is the historic bug where someone updates their password results in /etc/shadow disappearing because power was lost at exactly the wrong time.   The values in /etc/shadow and /etc/passwd are not changed that often so the risk of this happen it quite low.  

But when you say lets put all identity information in 1 file there is a lot more information so a lot more modifications so a lot more risk.   So mitigation against the disappearing file problem need to increase.

This is also a question with encrypted loop back files for home.  Should user have option to maintain a pair form synced.   Like you insert 2 USB keys to login not one.   So that one has a write error user is not screwed out the system and can just grab another key and go on.

This is all about making the options to make system durable are there.

**Comment by poettering** [comment]
These identity files are not subject to user modification. Only the possessor of the signing key can generate them, which typically is not the user themselves. 

The fact that the file is embedded in the home directory doesn't make it editable by the user. And the embedded copy is not the only copy, there's always one kept on the host as well (as some props need to be accessible even if the user is not currently logged in, for example enough metadata to populate the face browser and such), and there's another one in the LUKS2 header. The three copies are reconciled on login and the newest kept and the others updated. if one goes away it's hence totally OK.

Also, if people really modify their ~/.identity maybe we can set the immutable bit on it, but really, it's like protecting people from doing "exit 0 > .bashrc", which is also a way to lock yourself out...

Anyway, I don't think this is anything systematically to take into consideration. We have copies and the data is effectively immutable by the user anyway, hence I don't really see the problem. Hence, closing.

**Comment by boucman** [comment]
could the .ssh keys be kept in the non-encrypted copy of the .identity as a way to allow ssh login, or am I missing something in the design ?

**Comment by poettering** [comment]
It can and it does and we allow ssh logins that way. However its not that easy: the password to unlock the luks volume needs to come from somewhere. This means when you are already logged in once then ssh logins work fine. If you arent though you need to login locally once to provide the key or do so with a "jump account" that you log in via ssh and then transition from the to the other account to provide the password.

**Comment by boucman** [comment]
I was referencing your mention above that a copy is kept on the host... could that copy be used to allow ssh connections before mounting the luks ?

**Comment by poettering** [comment]
> I was referencing your mention above that a copy is kept on the host... could that copy be used to allow ssh connections before mounting the luks ?

yes, the ssh keys are made available to ssh and authentication works, but login doesn't, since without passphrase to unlock the LUKS volume with there's no $HOME you could then access. Hence: ssh auth is only sufficient for login if somehow before the home directory was unlocked otherwise, so that the kernel knows the LUKS password

**Comment by boucman** [comment]
ah, ok, I hadn't thought of that, thx

**Comment by oiaohm** [comment]
> The fact that the file is embedded in the home directory doesn't make it editable by the user. And the embedded copy is not the only copy, there's always one kept on the host as well (as some props need to be accessible even if the user is not currently logged in, for example enough metadata to populate the face browser and such), and there's another one in the LUKS2 header. The three copies are reconciled on login and the newest kept and the others updated. if one goes away it's hence totally OK.

I was looking at unencrypted portable home directory.   So no LUKS2 header. 

Remember if you have just moved from one machine to another the host stored copy is not there either.   This takes you down to one and a failure to write file correctly can be pulling out a removable media before sync is complete.

I will give you it right when the home is encrypted.   Its not right when its not encrypted.


With the ssh one there is way around that password problem.
https://linux.die.net/man/5/sshd_config
RequiredAuthentications2 publickey,password

ssh can require both the publickey then display a password prompt where you do the login again.

So depending on configuration of ssh the password to unlock the  LUKS can come in by ssh.  Yes it will mean you will need the key + the password for remote login.

Short term this could mean running two sshd.
1) sshd server for currently active users that only need the key.
2) sshd server for inactive users that requires the key and password.

Of course in time sshd could gain another login mode where password option could be like replaced with homed meaning if the user is not active it then asks for password.
