### ISSUE TITLE
RFE: portablectl update

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#13621]
Implement `portablectl update` to update the contents of an attached portable service from a new image.

**Comment by boucman** [comment]
in theory you don't even need to detach, 
 * update the units
 * reload systemd
and you're done.

**Comment by bluca** [comment]
Opened https://github.com/systemd/systemd/pull/18440 to add an "upgrade" verb, that allows changing the image, even with a new version suffix, with minimal downtime and preserving FD store and so on.
