### ISSUE TITLE
IPv6: Allow DNS=self or similar for IPv6 router advertisements

### ISSUE THREAD

**Issue by georgmu** [systemd/systemd#13639]
**Is your feature request related to a problem? Please describe.**
I have a router which also handles DNS and DHCP, which is feeded by another router with IPv6 prefix delegation. I do not have a stable global IPv6 prefix. The prefixes are used to provide IPv6 connectivity to the local subnets

To provide a DNS server to a local subnet, i use the link-local address via `DNS=fe80::aa:bb:cc:dd` in the `[IPv6PrefixDelegation]` section. 

This is not very portable: a change of the NIC would make this configuration invalid.

**Describe the solution you'd like**
I propose to allow `DNS=self` in this section (or maybe also in other sections, maybe including IPv4).
systemd-networkd would then chose the link-local address of the interface (this is what dnsmasq is doing).
Another option would be to take a global (but still dynamic) address of the router from the upstream interface instead of the link-local address.

**Describe alternatives you've considered**
Keep the status quo.

**Comment by ssahani** [comment]
A interface can have multiple IPs How about DNS=```Linklocal``` ?

**Comment by yuwata** [comment]
@georgmu I've created PR #14717. If possible, please test it. Thank you.
