### ISSUE TITLE
Hibernate when battery is low and computer is currently suspended

### ISSUE THREAD

**Issue by sbond75** [systemd/systemd#13633]
**Is your feature request related to a problem? Please describe.**

I often lose my open files when my laptop runs out of battery while suspended. Other operating systems like Windows and macOS will hibernate when the battery is low enough while the computer is suspended.

**Describe the solution you'd like**

Use the configuration file for UPower to determine what percentage or minutes left at which to hibernate while the computer is suspended/sleeping.

**Describe alternatives you've considered**

Hybrid sleep, but that is very unnecessary for a laptop because they only run out of power once the battery drains. Hybrid sleep is better for desktops because the power could suddenly go out, causing loss of data. On a laptop, the battery acts as a buffer.

**Comment by williamvds** [comment]
An alternative you may want to consider is `suspend-then-hibernate` mode instead of  the normal `suspend`. After a defined period of time the computer will be woken up and hibernated. You can enable and configure it in `logind.conf` and `sleep.conf`.  
I personally prefer using it to stop the battery draining too much while I'm not using it

There's already a TODO entry to implement what you're describing:
> beef up s2h to implement a battery watch loop: instead of entering
  hibernation unconditionally after coming back from resume make a decision
  based on the battery load level: if battery level is above a specific
  threshold, go to suspend again, only hibernate if below it

**Comment by OJFord** [comment]
> There's already a TODO entry to implement what you're describing:

>  >  beef up s2h to implement a battery watch loop: instead of entering
>  >  hibernation unconditionally after coming back from resume make a decision
>  >  based on the battery load level: if battery level is above a specific
>  >  threshold, go to suspend again, only hibernate if below it

That's a bit different - I have the same desire as OP and already use `suspend-then-hibernate` - I want to 'suspend then hibernate after time delay _or_ when the battery is low'.

The default `HibernateDelaySec=2h` is fine for me, but maybe I run out of battery in less than two hours? I could make it fast enough that it basically always wakes up to check in time, but then it might spend a lot of time pointlessly waking, and spend much longer than two hours (intermittently) suspended. I could make the limit it checks for when to suspend high enough that it has two hours, but that's way more than I would consider 'low battery' in this context; I want it to happen at about 5%, maybe 10%.

**Comment by OJFord** [comment]
#16052 (add a `callback` option to determine `HibernateDelaySec` value) would allow a solution for this by computing a reasonable value as `min(2h, remaining time on battery - buffer)`.

(Or if you didn't want the time delay behaviour, just `remaining time on battery - buffer`.)

**Comment by OJFord** [comment]
In case it helps anyone else, I ended up solving this for my use case by having the ACPI low battery alarm wake from sleep (that was enabled by default), and a udev rule that hibernates if the battery is below a certain level. The rule isn't triggered until it wakes, but at that point gets a flurry of events that happened while it was asleep, so there isn't even a delay while it waits for the next battery discharging event.

I used the default (~9.6% of `charge_full` on my system) `alarm` level for now, but if lowering that you'd thus want the udev rule to hibernate on values up to that or just slightly higher. It wouldn't make sense to have a gap (wake up only to waste more battery, and faster?) and setting it higher than `100 * alarm / charge_full` would be ineffective (unless already awake, but why would you want to hibernate sooner while running than while suspended).

**Comment by benzea** [comment]
Hrm, so, on the one hand, this kind of belongs into systemd, because should still consider the system suspended when we wake up because of low battery.

On the other hand, upower is currently in the business of doing the emergency suspending. And, this is a similar thing in some ways (and something that should likely happen at the same time).

Note that there are also cases of e.g. spurious wakeups. And, one might even tie the problem into modern-standby issues where e.g. a TCP/IP packet might cause waking up, but the system should just deal with it and appear as if sleeping otherwise.

**Comment by poettering** [comment]
There's an item in the TODO list or so, for natively adding support for a "suspend/hibernate loop" thing. i.e. suspending first, and then by time and ACPI wakeup recheck and go back to either suspend or hibernate depending on battery level. And leave that loop only if we woke up and neither acpi wakeup nor timer where triggered (i.e. some other reason for the wakeup was triggered).

I am not sure that "emergency hibernate" and this hibernate/suspend loop thing are really in the same territory. i think it would be totally OK to leave the emergency hibernate thing in upower land, and just implement the suspend/hibernate loop in systemd. That said, I am not opposed to doing both in systemd.

**Comment by poettering** [comment]
> ACPI low battery alarm wake from sleep

hm, do you have a link regarding API from linux userspace for that? how can we configure this? how can we figure out whether we were woken up due to an ACPI low battery event?

**Comment by benzea** [comment]
> hm, do you have a link regarding API from linux userspace for that?

The documentation is https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power-surface

Not sure how one can now why the system woke up.

**Comment by poettering** [comment]
> The documentation is https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power-surface

That's terrible vague... "system will be notified"... what does that even mean... ?

> Not sure how one can now why the system woke up.

**Comment by poettering** [comment]
does upower to emergency hibernate via that trip point or manually by looking at power level?

i wonder if thre's a sysfs file that tells us if the power supply assumes that the trip point is violated currently.

**Comment by benzea** [comment]
> > > The documentation is https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power-surface
> 
> Are you sure this isn't just stuff specific to MS Surface laptops?

Hmm, it is the only thing I found about the `alarm` sysfs entry. It does not seem to be MS surface specific though, my Lenovo laptop also has the file.

> does upower to emergency hibernate via that trip point or manually by looking at power level?

It does it all by itself. You can switch between a time based or percentage based approach. And, to be fair, you can have multiple batteries in a system, so one running low might not be relevant even.

> i wonder if thre's a sysfs file that tells us if the power supply assumes that the trip point is violated currently.

I don't think so. Though it should be as simple as comparing the `alarm` and `energy_now`/`charge_now` sysfs entries.

**Comment by poettering** [comment]
(btw, one reason why i really thing the suspend/hibernate loop belongs in systemd, is that we eventually should probably rework the cgroup stuff so that when suspending the machine we first put the largest part of the cgroup tree to sleep, except for PID 1 basically, and the sleep loop tool. That way we can be sure that processes which aren't suppsed to wake up while we need to check whether to go to sleep immediately again aren't woken up. but such service management/cgroup manageent things are really the domain of systemd, and not upower I am sure)

**Comment by sbond75** [comment]
Is the low battery alarm a specific predetermined battery level, and is it designed to be a reliable indicator of low battery by the manufacturer of the battery? Or is it just a tunable percentage? Also if it's integrated into ACPI specs then it would be nice to see if they detail what it could be used to do. If it's already an indicator of critical battery level then it might as well hibernate as a trigger from that specific event, but if it's just for spurious wakeups then it's a different story.

**Comment by sbond75** [comment]
Also it might be worth checking battery voltage instead of percentage

**Comment by yrro** [comment]
> does upower to emergency hibernate via that trip point or manually by looking at power level?

Looks like upower is polling batteries and deciding to perform a 'critical power action' when the battery charge or time left before battery is depleted is below a threshold, for _all_ batteries.

**Comment by OJFord** [comment]
> Is the low battery alarm a specific predetermined battery level, and is it designed to be a reliable indicator of low battery by the manufacturer of the battery?

It's configurable by writing to `/sys/class/power_supply/BATx/alarm`. The default is set by ACPI driver and I think I saw something to do with checking for a manufacturer's 'design' value (or else a fallback) there, but I don't still have it open. `drivers/acpi/battery.c`.

**Comment by arvidjaar** [comment]
> The default [battery alarm] is set by ACPI driver and I think I saw something to do with checking for a manufacturer's 'design' value

It is set only for LENOVO/ThinkPad, for all other models it is left unitialized (0).

**Comment by arvidjaar** [comment]
Also, battery alarm requires firmware support (`_BIP` method), it may not be present universally. If firmware does not support it, attempt to set should fail with `ENODEV`.

**Comment by OJFord** [comment]
> It is set only for LENOVO/ThinkPad, for all other models it is left unitialized (0).

It's set (non-zero) on my Framework (and works).

**Comment by dtardon** [comment]
I think this is fixed by https://github.com/systemd/systemd/pull/23895.

**Comment by bluca** [comment]
This has been implemented via https://github.com/systemd/systemd/issues/21165
