### ISSUE TITLE
IPv6 PD: make prefix assignments configurable

### ISSUE THREAD

**Issue by tokred** [systemd/systemd#13638]
**Is your feature request related to a problem? Please describe.**
In a typical home router / CPE environment, systemd-networkd can be set up to request an IPv6 prefix via DHCPv6 on WAN and then assign /64 networks to LAN interfaces. The assigned networks are sequentially selected by systemd, therefore limiting an admin's abilities to structure his network, e.g. by matching network addresses to "some logic".

_Example:_ 2001:db8:af::/48 is dynamically delegated and I'd like to assign 2001:db8:af:{vlan}::/64 according to each interface's VLAN tag, instead of consecutively 2001:db8:af:1::, 2001:db8:af:2::, etc.

**Describe the solution you'd like**
Following up / expanding the ideas of https://github.com/systemd/systemd/issues/9626:
> @Gigadoc2
> When networkd assigns available /64-prefixes to links with IPv6PrefixDelegation=dhcpv6, it should do so by **_choosing the next /64_** from the available prefix.

I'd like to propose to make this configurable to allow selecting a specific <delegated_prefix><chosen_suffix>/<network_size> setup, instead of simply "the next /64". Other use cases might exist where something else than /64 is required too. This could work by introducing additional configuration parameters for interfaces, e.g.

```
[Network]
IPv6PrefixDelegation=dhcpv6
IPv6PDNetworkSuffix=a101
IPv6PDNetworkSize=64
```
Checks would be required in order to ensure the length of the delegated prefix + network suffix + network size make sense overall.

**Comment by mmonaco** [comment]
I'd like to further motivate this a little bit more because the initial request might be interpreted as purely cosmetic. However, I think this also would help with stability. Since the ordering is not stable, every time networkd or the system overall restarts, the RA from each interface shuffles. So I have hosts on my network with SLAAC address for each subnet accumulating over time which is causing breakages. (Now, some of these hosts may be doing something wrong w.r.t. lifetimes but I don't have complete control over all of them).

**Comment by andir** [comment]
I started hacking on this this evening.... Will likely open a (draft) PR in the following days.

My current (dirty) WIP state is here https://gist.github.com/andir/6a0910dc62c7e0c763729156736f95db (in case I can't finish it and someone else is willing to pick it up).

**Comment by mmonaco** [comment]
That's awesome. I'm happy to test when you have a PR ready. TBH I stopped using `networkd` for IPv6 and setup `dhcpcd` + `dnsmasq` in the interim because this turns out to be a show stopper for me.

**Comment by yuwata** [comment]
#15669 was merged. Let's close this.
