### ISSUE TITLE
No way to not kill other processes in unit when main process crashes

### ISSUE THREAD

**Issue by iainlane** [systemd/systemd#13658]
We've just started using `systemd --user` units for managing GNOME session as of 3.34. Many parts of the session are now managed from systemd units instead of being directly forked off from `gnome-session`. This mostly works OK, but there's one wart that I'd like to talk about in this issue, which is a regression from the old world. In an Xorg session, it used to be that if your shell crashed, it would restart and you'd keep all of your applications. Now, when the shell crashes and restarts, some of the applications are lost: those which are in the shell's own unit, which is many of those that you might have launched during the course of your session. I'd like to avoid this happening.

We are using `KillMode=control-group` and `Restart=always`. In the normal case, this is what we want: when you log out, all of the units are stopped explicitly and other processes are killed as necessary. But the kill behaviour is *not* what we want when restarting due to a crash. I think we want something like `KillWhen=stopping` or `KillMode=<killmode>-stopping` to say that the reaping should only happen when we are finally stopping (or failing) the unit, but not if we are trying to restart it due to an abnormal exit. I'm hoping in this issue we can decide

  * There is indeed no reasonable way to achieve what I'm asking for already
  * That this is indeed a theoretically possible thing to do
  * The interface inside unit files that we'd like this to have

and then I can go away and work on it.

In the medium term we would like to move to having shells (via GLib?) execute their processes inside transient units, which would get around this problem. But then all programs that might launch processes inside the desktop will have to be modified to support this, and so I think we would do well to have something inside systemd too.

**Comment by topimiettinen** [comment]
Others can probably better comment on your question. I had a similar issue with KDE, when I was trying to push execution of parts of session to `systemd --user`. I also think that the medium/long term solution will be that the shell should always use systemd transient units to launch processes, never by itself. Then this will go away. The shell itself could even be running as a service for `systemd --user` if some assumptions of Xsession process life cycle and other details could be changed.

**Comment by 3v1n0** [comment]
>  I also think that the medium/long term solution will be that the shell should always use systemd transient units to launch processes

This is true indeed, although would be quite nice to have something in the short term to stop this to happen.

**Comment by poettering** [comment]
Hmm, the way I see it, gnome-session is kinda its own service manager no? In that case maybe it should be expected that it is more "responsibly written" that the typical user code, and thus if it wants its own kill logic on exit, should just disable systemd's and do the one on its own?

How relevant is this all in the long run? I mean, back in the day, you could even restart gnome-shell and your window manager while keeping X11 running. Isn't that all a thing of the past, i.e. in times of Wayland where all that is a single process anyway? i.e. aren't we just running behind a concept from the olden days that already ceased to exist half-way?

Anyway, I am not really opposed to extending the kill logic to operate differently on success and on abnormal exit. If you can come up with nice semantics and a patch for it, we certainly can merge something like that...

**Comment by iainlane** [comment]
We've come up with another idea which avoids having to make any systemd changes.

GNOME Shell and other things which spawn processes will call `StartTransientUnit` to start a new transient scope and put those spawned processes in the new scope. In that way, they aren't reaped by systemd when killing processes in the (previously) parent unit's cgroup; they aren't subject to the `OOMPolicy` of the parent (so won't be killed if something else OOMs and we don't have to set `OOMPolicy=continue`), and maybe other things too.

So I don't think this feature request is needed any more; will close it. Let me know if there's anything we missed that will mean we can't do this.
