### ISSUE TITLE
udevadm trigger fails when run in container

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#13652]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Ubuntu Bionic with custom systemd from latest upstream v243

**Expected behaviour you didn't see**
 > udevadm trigger return success

**Unexpected behaviour you saw**
 > udevadm trigger fails

**Steps to reproduce the problem**

Inside any container, run 'udevadm trigger' as root:

> $ udevadm trigger
> Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
> Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXCPU:00/uevent': Permission denied
> Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXCPU:01/uevent': Permission denied
> Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXCPU:02/uevent': Permission denied
> etc...
> 

This appears to have been caused by 97afc0351a96e0daa83964df33937967c75c644f which changed udevadm to return any encountered errors, instead of ignoring them.

Since unprivileged containers will never be able to write to write to device uevent files, maybe EACCES should also be ignored, or at least ignored when 'private-users' is true?

This also may be similar to #11333, fixed by c494b739a47359ab2697482f52545e2a6d1c86ad, so possibly something similar to that fix could be used?

**Comment by ddstreet** [comment]
I should note that, again similar to #11333, this change causes various other things to fail, such as package post-install scripts that were calling udevadm trigger.  For example:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1845314

**Comment by ddstreet** [comment]
Also, EACCES isn't the only possible error that this behavior change uncovers; some /sys/device/* devices have always returned error from any writes to their uevent file, such as the /sys/device/vio driver (only on ppc systems), which has always returned ENODEV but nobody has ever noticed before because udevadm just ignored it.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1845319

That actually is a kernel bug, IMO, and I'll send a patch there to try to correct the vio driver, but just wanted to mention it to illustrate that this behavior change might uncover more errors than just EACCES inside a container.

**Comment by ddstreet** [comment]
Oh, and this behavior change causes the systemd-udev-trigger.service to fail inside containers, or if udevadm trigger encounters any errors, which is how I first noticed this on ppc64el (win for systemd-upstream testing!)

**Comment by floppym** [comment]
> Oh, and this behavior change causes the systemd-udev-trigger.service to fail inside containers

systemd-udev-triger.service has ConditionPathIsReadWrite=/sys, which would generally evaluate to false in a container since /sys would be mounted read-only.

**Comment by ddstreet** [comment]
> which would generally evaluate to false in a container since /sys would be mounted read-only.

not in the lxd-managed container i just checked.

**Comment by ddstreet** [comment]
#13656 from @yuwata LGTM, I verified it does fix this.  thanks!
