### ISSUE TITLE
PackageKit service fails with a core-dump due to unsupported directive HookDir in pacman.conf.

### ISSUE THREAD

**Issue by ericonr** [systemd/systemd#13665]
**systemd version the issue has been seen with**

> 242.85-2

**PackageKit version**

> 1.1.12-1

**Used distribution**

 > Manjaro Stable

**Expected behaviour you didn't see**

 > PackageKit service should be able to parse a standard pacman.conf file without core dumping. Being able to deal with unknown directives could be the best solution for parameters that are not relevant to PackageKit working.

**Unexpected behaviour you saw**

 > The PackageKit service fails with a core dump when it encounters the unknown directive `HookDir`.

```
● packagekit.service - PackageKit Daemon
   Loaded: loaded (/usr/lib/systemd/system/packagekit.service; static; vendor preset: disabled)
   Active: failed (Result: core-dump) since Thu 2019-09-26 16:52:37 -03; 2min 38s ago
  Process: 31837 ExecStart=/usr/lib/PackageKit/packagekitd (code=dumped, signal=TRAP)
 Main PID: 31837 (code=dumped, signal=TRAP)

set 26 16:52:37 erico-xps systemd[1]: Starting PackageKit Daemon...
set 26 16:52:37 erico-xps PackageKit[31837]: daemon start
set 26 16:52:37 erico-xps packagekitd[31837]: Failed to initialize alpm: using /etc/PackageKit/alpm.d/pacman.conf: /etc/PackageKit/alpm.d/pacman.conf:8/etc/pacman.conf:17unrecognised directive 'HookDir'
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Main process exited, code=dumped, status=5/TRAP
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Failed with result 'core-dump'.
set 26 16:52:37 erico-xps systemd[1]: Failed to start PackageKit Daemon.
```

**Steps to reproduce the problem**

You just need a `HookDir` directive in the `[options]` header in `/etc/pacman.conf`.

**Observation**

* This issue has been present since 2016, at least: https://bbs.archlinux.org/viewtopic.php?id=213009
* https://bugs.freedesktop.org/enter_bug.cgi?product=PackageKit doesn't allow reporting bugs for PackageKit, nor is it available on freedesktop's GitLab instance.

**Comment by mcatanzaro** [comment]
Surely this has nothing to do with systemd.

PackageKit upstream is here: https://github.com/hughsie/PackageKit

**Comment by ericonr** [comment]
Well shit. Thanks! I searched for it on freedesktop.org, and ended up assuming the lack of links meant it resided here now.
