### ISSUE TITLE
Failed to start Network Service

### ISSUE THREAD

**Issue by Treverr** [systemd/systemd#13668]
**systemd version the issue has been seen with**
> systemd 237

**Used distribution**
  18.04

**Expected behaviour you didn't see**
 > On boot, the system should have started systemd-netwrokd

**Unexpected behaviour you saw**
 > "Failed to start network service"

**Steps to reproduce the problem**
Reboot system, it does not bring up the network until I Netplan apply

Sep 26 18:40:56 server systemd[1]: Starting Network Service...
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Failed with result 'exit-code'
Sep 26 18:40:56 server systemd[1]: Failed to start Network Service
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 5
Sep 26 18:40:56 server systemd[1]: Stopped Network Service
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Start request repeated too quickly
Sep 26 18:40:56 server systemd[1]: systemd-networkd.service: Failed with result 'exit-code'
Sep 26 18:40:56 server systemd[1]: Failed to start Network Service

**Comment by yuwata** [comment]
v237 is too old. Please contact to your distribution, or try current git master. Sorry.
