### ISSUE TITLE
luks boot locking (unmountable, ro) the keyfile device

### ISSUE THREAD

**Issue by moviuro** [systemd/systemd#13673]
**systemd version the issue has been seen with**
> 243.51-1

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > I can use the file `/key` on `/dev/sdd1` to unlock my both LUKS partitions; and mount `/dev/sdd1` to `/mnt/F862-7316` at boot time with no further instructions.
```
% cat /proc/cmdline 
initrd=\toxo\intel-ucode.img initrd=\toxo\initramfs-linux-lts.img luks.uuid=8378cf26-54fb-4cc3-9125-36e311178c21 luks.options=8378cf26-54fb-4cc3-9125-36e311178c21=allow-discards luks.key=8378cf26-54fb-4cc3-9125-36e311178c21=/key:UUID=F862-7316 luks.uuid=8d132091-30a9-448d-ac0b-53136589516a luks.key=8d132091-30a9-448d-ac0b-53136589516a=/key:UUID=F862-7316 root=UUID=66ddfdb0-47ee-4d2d-ba0e-f09f482f36fd rw i915.enable_rc6=0
```

**Expected behaviour you saw**
 > Both LUKS partitions were correctly opened and mounted.

**Unexpected behaviour you saw**
 > `mount` refuses to operate on the keyfile filesystem: `mount: /mnt/F862-7316: /dev/sdd1 already mounted on /run/systemd/cryptsetup/keydev-luks-8d132091-30a9-448d-ac0b-53136589516a.`
 > If I specify `UUID=F862-7316          /mnt/F862-7316  vfat            rw,sync,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro  0 2` in `fstab(5)` and reboot, I get to the emergency shell because my device can't be mounted
 > If I `--bind` mount the keyfile device, it gets mounted read-only.
```
# mount -obind,rw /run/systemd/cryptsetup/keydev-luks-8378cf26-54fb-4cc3-9125-36e311178c21 /mnt/F862-7316
# touch /mnt/F862-7316/foo
touch: cannot touch '/mnt/F862-7316/foo': Read-only file system
```
 > If I unmount my keyfile from `/run/systemd/cryptsetup/keydev-luks-*`, I can successfully mount it on `/mnt/F862-7316` -- but this is clearly subotimal

**Steps to reproduce the problem**
 > Use either `luks.key` or `rd.luks.key` options on `cmdline`; try to mount the filesystem where the keyfile is located.

**See also**
 > I have submitted an Archlinux forum post with similar information: https://bbs.archlinux.org/viewtopic.php?id=249473

**Comment by arvidjaar** [comment]
Yes, keydev mount unit remains active. I do not think there is "native" systemd way to stop keydev mount after cryptsetup unit completed. We need either `Conflict` or garbage collection. Garbage collection is not possible because cryptsetup unit needs to remain active to be able to run `ExecStop`.

Hmm ... actually, `Conflict` on encrypted container may work. First keydev is mounted, then cryptsetup runs and creates device which will trigger unmount.

One problem is retroactive dependencies. Running `systemctl start systemd-cryptsetup@foo` will attempt to trigger `Wants`/`Requires` and so (attempt to) mount keydev which - due to `Conflict` - will try to stop device. May be it just results in excessive noise in logs.

**Comment by poettering** [comment]
instead of mount the dir twice via the block device, you could mount the second location via bind mount from the first, and just leave both around?

**Comment by moviuro** [comment]
> ... bind mount from the first, and just leave both around?

Already tried that:

```
# mount -obind,rw /run/systemd/cryptsetup/keydev-luks-8378cf26-54fb-4cc3-9125-36e311178c21 /mnt/F862-7316
# touch /mnt/F862-7316/foo
touch: cannot touch '/mnt/F862-7316/foo': Read-only file system
```

**Comment by moviuro** [comment]
I rebooted today, and now my system will drop me to emergency mode because it can't unlock the second drive (HDD), which worked last time I turned the machine on (43 days ago).

* NVMe is auto-mounted at boot (LUKS unlock + BTRFS mount)
* HDD does not mount for whatever reason. I can use emergency mode to `cryptsetup luksOpen` it, then `mount`.
* USB device must still be manually unmounted from `/run/systemd/cryptsetup` before any write operation can be done on it.

**Comment by moviuro** [comment]
This is still an issue.

```
# cat /proc/cmdline
initrd=\toxo\intel-ucode.img initrd=\toxo\initramfs-linux-lts.img luks.uuid=8378cf26-54fb-4cc3-9125-36e311178c21 luks.options=8378cf26-54fb-4cc3-9125-36e311178c21=allow-discards rd.luks.key=8378cf26-54fb-4cc3-9125-36e311178c21=/key:UUID=F862-7316 root=UUID=66ddfdb0-47ee-4d2d-ba0e-f09f482f36fd rw i915.enable_rc6=0 luks.uuid=8d132091-30a9-448d-ac0b-53136589516a rd.luks.key=8d132091-30a9-448d-ac0b-53136589516a=/key:UUID=F862-7316
```

```sh
# If I want /boot to be mounted... I need to do...
umount /run/systemd/cryptsetup/keydev-luks-8378cf26-54fb-4cc3-9125-36e311178c21
umount /run/systemd/cryptsetup/keydev-luks-8d132091-30a9-448d-ac0b-53136589516a
mount /dev/sdd1 /mnt/F862-7316 && mount --bind /mnt/F862-7316/toxo /boot
```

* systemd 244.2-2 (archlinux)
* linux-lts 5.4.18-1 (archlinux)

**Comment by moviuro** [comment]
This is still not resolved.

```
# cat /proc/cmdline 
initrd=\toxo\intel-ucode.img initrd=\toxo\initramfs-linux-lts.img luks.uuid=8378cf26-54fb-4cc3-9125-36e311178c21 luks.options=8378cf26-54fb-4cc3-9125-36e311178c21=allow-discards rd.luks.key=8378cf26-54fb-4cc3-9125-36e311178c21=/key:UUID=F862-7316 root=UUID=66ddfdb0-47ee-4d2d-ba0e-f09f482f36fd rw i915.enable_rc6=0 luks.uuid=8d132091-30a9-448d-ac0b-53136589516a rd.luks.key=8d132091-30a9-448d-ac0b-53136589516a=/key:UUID=F862-7316
```

```
# mount -obind,rw /run/systemd/cryptsetup/keydev-luks-8378cf26-54fb-4cc3-9125-36e311178c21 /mnt/F862-7316
# touch /mnt/F862-7316/foo
touch: cannot touch '/mnt/F862-7316/foo': Read-only file system
```

Still have to:

```sh
umount /run/systemd/cryptsetup/keydev-luks-8378cf26-54fb-4cc3-9125-36e311178c21
umount /run/systemd/cryptsetup/keydev-luks-8d132091-30a9-448d-ac0b-53136589516a
mount /dev/sdd1 /mnt/F862-7316 && mount --bind /mnt/F862-7316/toxo /boot
```

* linux-lts 5.4.61-1
* systemd 246.3-1

**Comment by moviuro** [comment]
By total accident, this looks like it's been solved. I'm worried that it will randomly stop working again.

* linux-ck-skylake 5.9.14-1
* systemd 247.2-1

After boot, `/run/systemd/cryptsetup/keydev-luks-*` are now unmounted, and both mountpoints for my USB thumbdrive are properly mounted through `fstab(5)`.
