### ISSUE TITLE
IPv4 network stays in state "configuring" forever

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1368]
Our CI tests detected a networkd regression in trunk (still worked in 226): With a standard `.network` file like

```
# cat /run/systemd/network/test_eth42.network 
[Match]
Name=test_eth42
[Network]
DHCP=yes
```

the interface now stays in state "configuring" eternally:

```
# networkctl status test_eth42
● 14: test_eth42
       Link File: /lib/systemd/network/99-default.link
    Network File: /run/systemd/network/test_eth42.network
            Type: ether
           State: routable (configuring)
          Driver: veth
      HW Address: 5e:4b:19:a5:64:72
             MTU: 1500
         Address: 192.168.5.127
                  fe80::5c4b:19ff:fea5:6472
         Gateway: 192.168.5.1
             DNS: 192.168.5.1
```

The interface is actually fully configured, I'm not quite sure yet what it's still waiting on. Journal output from the point when networkd starts:

```
Sep 24 10:49:00 debian systemd[1]: Started Network Service.
Sep 24 10:49:00 debian systemd-udevd[4524]: Could not generate persistent MAC address for router_eth42: No such file or directory
Sep 24 10:49:00 debian systemd-udevd[4525]: Could not generate persistent MAC address for test_eth42: No such file or directory
Sep 24 10:49:00 debian kernel: IPv6: ADDRCONF(NETDEV_UP): router_eth42: link is not ready
Sep 24 10:49:00 debian kernel: IPv6: ADDRCONF(NETDEV_CHANGE): router_eth42: link becomes ready
Sep 24 10:49:00 debian systemd-networkd[4522]: test_eth42: Gained carrier
Sep 24 10:49:00 debian systemd-networkd[4522]: router_eth42: Gained carrier
Sep 24 10:49:00 debian systemd-timesyncd[3262]: Synchronized to time server 78.46.76.100:123 (0.debian.pool.ntp.org).
Sep 24 10:49:01 debian systemd-timesyncd[3262]: Network configuration changed, trying to establish connection.
Sep 24 10:49:01 debian systemd-timesyncd[3262]: Synchronized to time server 78.46.76.100:123 (0.debian.pool.ntp.org).
Sep 24 10:49:02 debian systemd-timesyncd[3262]: Network configuration changed, trying to establish connection.
Sep 24 10:49:02 debian systemd-timesyncd[3262]: Synchronized to time server 78.46.76.100:123 (0.debian.pool.ntp.org).
Sep 24 10:49:05 debian systemd-networkd[4522]: test_eth42: DHCPv4 address 192.168.5.127/24 via 192.168.5.1
Sep 24 10:49:05 debian systemd-networkd[4522]: test_eth42: Not connected to system bus, ignoring transient hostname.
Sep 24 10:49:05 debian systemd-timesyncd[3262]: Network configuration changed, trying to establish connection.
Sep 24 10:49:05 debian systemd-timesyncd[3262]: Synchronized to time server 78.46.76.100:123 (0.debian.pool.ntp.org).
```

I'll run a bisect and further investigations, but want to flag this for the upcoming 227 release.

**Comment by martinpitt** [comment]
The IPv6 tests still work fine for the record; the interface goes to `routable (configured)` quickly.

**Comment by martinpitt** [comment]
Bisected to https://github.com/systemd/systemd/commit/18d2955 from PR #1356 (landed yesterday). At first sight it looks like the intention of this was to restore DHCPv6 after resuming, but there is a bug that the initial DHCP after a fresh boot does not properly recognize that DHCPv6 is not being used? (`bool dhcp6_configured`).

I don't think the intention of this was to break `networkd-wait-online` for an interface that only gets IPv4 DHCP info, at least that would make it quite useless.

@pfl , this seems to be your's?

**Comment by pfl** [comment]
Hmm, indeed. Just started to wonder what the expectation actually is by setting DHCP=yes or ipv6 if a network does not support it in its Router Advertisments. At the moment the code only looks at that configuration file variable, not on the actual information from the network. I'll fix this.

**Comment by martinpitt** [comment]
Indeed the behaviour of "yes" isn't documented very well, but so far it seemed opportunistic: If you get v4 or v6, use it; but at least one is required.

**Comment by pfl** [comment]
Maybe that "yes" is indeed opportunistic so that either DHCPv4 or DHCPv6 gets the network configured. Then the keyword "ipv6" will wait until DHCPv6 completes (if ever), as DHCPv4 is not started.

**Comment by pfl** [comment]
After some Karnaugh map drawing the above patch seems to be correct. Please take a look.
