### ISSUE TITLE
RuntimeDirectoryPreserve makes writing to RUNTIME_DIRECTORY fail

### ISSUE THREAD

**Issue by superm1** [systemd/systemd#13688]
**systemd version the issue has been seen with**
> 242-6ubuntu1

**Used distribution**
 > Ubuntu eoan

**Expected behaviour you didn't see**
 > Unit executes properly

**Unexpected behaviour you saw**
 > Unit fails to execute

1. Create test unit
```
[Unit]
Description=test failures

[Service]
Type=oneshot
RuntimeDirectory=test
RuntimeDirectoryPreserve=yes
ExecStart=sh -c "echo test > $RUNTIME_DIRECTORY/test"
DynamicUser=yes
RestrictAddressFamilies=AF_NETLINK AF_UNIX AF_INET AF_INET6
SystemCallFilter=~@mount
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictRealtime=yes
```

2. run test unit
3. observe failure:
```/usr/bin/sh: 1: cannot create /run/test/test: Permission denied```
4. Check that directories properly made but no test file

```
# ls -alhR /run/test
lrwxrwxrwx 1 root root 12 Sep 30 13:23 /run/test -> private/test
# ls -alhR /run/test/
/run/test/:
total 0
drwxr-xr-x 2 63378 63378 40 Sep 30 13:23 .
drwx------ 4 root  root  80 Sep 30 13:23 ..
```

**Comment by yuwata** [comment]
I cannot reproduce this with the current git master. See #13695. Could you also test with the current git master or v243?

Also, if the issue is not fixed, please provide the debugging logs. Thank you.
