### ISSUE TITLE
Switch from laptop mode to tablet mode doesn't work on Medion Akoya convertible.

### ISSUE THREAD

**Issue by Tuxman2** [systemd/systemd#13680]
Hi,

**systemd version the issue has been seen with**
> Systemd 243

**Used distribution**
 > Fedora 31 beta

**Expected behaviour you didn't see**
 > Switch from laptop mode to tablet mode and switch from tablet mode to laptop mode. Touchpad and keyboard is not enable or disable when the laptop is turned. 

**Unexpected behaviour you saw**
 > Nothing

**Steps to reproduce the problem**

I turn the laptop to 360 degrees and nothing happens. I used the script from Alesguzik and it doesn't work (see it: https://github.com/alesguzik/linux_detect_tablet_mode).  I used an old version of Alesguzik script (support of accelerometers) and it doesn't work too. I know that new codes were added to systemd 243 and iio-proxy-sensor 2.8 version to support 2 accelerometers, but for me, I can't use switch tablet mode.

Is there a solution to solve this problem ?

Note: Model of the laptop : Medion Akoya E229x series.

Thanks.

**Comment by poettering** [comment]
Sounds like an issue for gnome/iio sensors proxy

/cc @hadess?

**Comment by hadess** [comment]
> Sounds like an issue for gnome/iio sensors proxy

I don't know what's supposed to turn the touchpad and keyboard on and off (usually that's done in hardware), but iio-sensor-proxy certainly doesn't implement this functionality (not sure why it would), and I know that it's not implemented in GNOME either.

**Comment by poettering** [comment]
ah, i assumed that gnome-settings-daemon had a module for something like that. 

which then raises the question: if we need some component to switch off kbd/touchpad in tablet mode, where should this logic be? given that iio-sensors-proxy is a layer above system it appears to me, that something above that needs to link that up. i.e. maybe if there currently is not module for that in gnome-settings-daemon, maybe there should be?

**Comment by poettering** [comment]
(that said, logind tracks the lid mode and docked mode currently. if there's a sane api to track tablet mode, maybe we should track that too. is there? or does this require talking to iio-sensors-proxy?)

**Comment by hadess** [comment]
I haven't seen a case where this can't be implemented in the kernel (in the same way that it's usually implemented in the EC, or in the firmware on certain brands of devices), or found a reason why we'd need a different behaviour from a "simple" kernel behaviour (turn off keyboard and touchpad when screen angle is above XX degrees).

In short, I don't think it makes sense to implement in user-space (yet).

**Comment by poettering** [comment]
@hadess ok, so this means it would make sense to just ask @Tuxman2 to file this as against the kernel laptop driver for his model as a feature request and we can close this here for now?

(if the EC/firmware/driver knows about the mode the laptop is in, would be awesome of course to export this to userspace)

**Comment by poettering** [comment]
Anyway, I am pretty sure it shouldn't be systemd that turns this off. Either the kernel or the desktop, but not systemd/logind. Hence, @Tuxman2 can you please ping the laptop drivers folks about this? I am sure they'll help you!
