### ISSUE TITLE
Allow boot stub to specify cmdline argument in secure boot mode

### ISSUE THREAD

**Issue by julian-klode** [systemd/systemd#13694]
**Is your feature request related to a problem? Please describe.**
We'd like to centrally build some kernel images with combined initramfs using the stub (but without .osrel and .cmdline sections), sign those, and then specify command-line operations on the bootloader.

**Describe the solution you'd like**
Check if the image the stub is part of contains no .cmdline, and if so, allow specifying the argument on the command-line.

**Describe alternatives you've considered**

Instead of an empty .cmdline section, we could use

- Another section which indicates that command-line arguments take precedence
- Empty .cmdline section
- A special .cmdline section value (like a control byte)

**Comment by xnox** [comment]
@poettering as discussed at ASG that for Ubuntu to use type-2 BLS binaries we may need a way to override and/or lockdown the cmdline that is either baked in or always passed in, or only sometimes passed in (as we are still designing / implementing things).

**Comment by poettering** [comment]
makes sense to allow it to be overriden if it's not built-in! happy to take a patch for this!

**Comment by xnox** [comment]
We've had a bit of a bus factor on this issue, as the reporter has both arms broken at the moment in a bicycle accident.

**Comment by xnox** [comment]
@poettering provided patch.... it builds, but not yet tested.
