### ISSUE TITLE
nspawn: forward sd_notify() messages

### ISSUE THREAD

**Issue by alban** [systemd/systemd#1369]
Note: this bug was initially filed on [bfo#89844](https://bugs.freedesktop.org/show_bug.cgi?id=89844) but I would like to continue the discussion here.

When an application is started in a container with systemd-nspawn, the application cannot just call [sd_notify()](http://www.freedesktop.org/software/systemd/man/sd_notify.html) from the container to notify systemd on the host because:
- the processes in the container will be in a different cgroup than the process executing systemd-nspawn. I think even `NotifyAccess=all` will not work. 
- if the container uses a new network namespace, the notify socket will not work if it uses an abstract unix socket. An file socket will also not work because the container does not have access to the file socket on the host. Systemd uses either an abstract unix socket or a unix socket file, depending on its version (see [email](http://lists.freedesktop.org/archives/systemd-devel/2014-December/026129.html) and [email](http://lists.freedesktop.org/archives/systemd-devel/2015-March/029096.html)).

Flannel would need that. To workaround this problem, [flanneld.service](https://github.com/coreos/coreos-overlay/blob/master/app-admin/flannel/files/flanneld.service) bind mount a proxy socket file and uses [sdnotify-proxy](https://github.com/coreos/sdnotify-proxy) to proxy it. It is using Docker today but it is the same problem with systemd-nspawn. It would be nice if `systemd-nspawn` made `sd_notify` easier to use.

We would like to have this feature for rkt, see https://github.com/coreos/rkt/issues/1464.

**Comment by poettering** [comment]
Do you intend to use this for anything else than ready or watchdog notifications? 

It think it would make a lot of sense if systemd running inside a container could let it's container manager know when it reached default.target or so. At the same time, we should hook up the watchdog support too, see #997.

**Comment by alban** [comment]
> Do you intend to use this for anything else than ready or watchdog notifications?

We would also want the host to be able to publish [events in the rkt event stream](https://github.com/coreos/rkt/blob/master/api/v1_alpha/api.proto#L227) (https://github.com/coreos/rkt/issues/1193) such as:
- `my-app-1.service` in the container was started ([EVENT_TYPE_APP_STARTED](https://github.com/coreos/rkt/blob/master/api/v1_alpha/api.proto#L238))
- `my-app-1.service` in the container exited with status 1 ([EVENT_TYPE_APP_EXITED](https://github.com/coreos/rkt/blob/master/api/v1_alpha/api.proto#L239))

/cc @yifan-gu @jonboulle

**Comment by poettering** [comment]
OK, good to know. Not entirely sure though how the forwarding should look like in detail. We shouldn't forward arbitrary messages really but only selected ones. Maybe one option to mark fields to send up with a special field prefix, such as using "PROPAGATE_X_FOO=bar" instead of just "X_FOO=bar" when the message is one that shall be forwarded.

**Comment by travisn** [comment]
What's the status on this? Having the ability to watch a unit launched by rkt would be most helpful, particularly for startup notifications.

**Comment by alban** [comment]
It has not been implemented, but I am giving this a try now.

**Comment by trusch** [comment]
@poettering:  This bug should be reopened. --notify-ready=yes doesn't fix all usecases of sd_notify. Notably the sd_notify("WATCHDOG=1") message will not be forwarded correctly so it is not possible to implement a watchdog for (in my usecase) rkt-containers based on systemd.

**Comment by Crafter6432** [comment]
Push
