### ISSUE TITLE
sd_journal_print and co truncate message to 2040 characters

### ISSUE THREAD

**Issue by leolchat** [systemd/systemd#13706]
**systemd version the issue has been seen with**
> current master branch

**Used distribution**
 > Ubuntu 18.04

**Unexpected behaviour you saw**
 > using `sd_journal_print` with a message longer than 2048 character result in a truncated record

Reading the source, the code is using `LINE_MAX` and there is a todo to fix this behavior https://github.com/systemd/systemd/blob/9e9213cd08ca82d6cc3565f753f343b1739cb263/src/journal/journal-send.c#L78

This should at least be written in the documentation / man pages as done in #13707

**Comment by poettering** [comment]
Fixed by 2eaf435a16f4ec9ba15509ef9d31eca7b4f7ace7. Let's close.
