### ISSUE TITLE
MACAddressPolicy=persistent results in the same MAC on 2 ends of a bond interface

### ISSUE THREAD

**Issue by ol-alexandra** [systemd/systemd#13712]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
 > I create bond device on 2 machines, and they communicate

**Unexpected behaviour you saw**
 > The 2 bond network devices on 2 machines get the same MAC address, and communication breaks.

**Steps to reproduce the problem**
With the default MACAddressPolicy=persistent, I get a constatnt MAC address when I creat a bonding device:
`sudo ip link add bond1 type bond mode 1`
Unlike old behaviour, this MAC address is not overwritten by the slave MAC.  And the most important thing: bond0 gets **the same MAC** on 2 machines connected with this bonding network.

**Comment by ssahani** [comment]
@AlexandraKossovsky Please share the configuration.

**Comment by ssahani** [comment]
@AlexandraKossovsky Please test with https://github.com/systemd/systemd/pull/13837

**Comment by AlexandraKossovsky** [comment]
I have not tried the patch yet (I will), but I thought that the new behaviour I'm complaining about was implemented to solve issues like https://blog.widodh.nl/2015/09/ubuntu-and-the-changing-mac-address-with-bonding/
As far as I can read your patch, you are reverting the udev behaviour to good old days, so that I'll be happy, but the person who wrote the story on the link above will be unhappy again...

**Comment by keszybz** [comment]
@AlexandraKossovsky do you have systemd-networkd running?

> And the most important thing: bond0 gets the same MAC on 2 machines connected with this bonding network.

Does this happen when creating the interfaces with `sudo ip link add ... type bond`?

Are the /etc/machine-id files different on the two machines?

**Comment by AlexandraKossovsky** [comment]
No, systemd-networkd is not running. 
I use Debian testing, see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941603 . 
I use static network configuration (and I do not want systemd to change it), and yes, I create the bond interface via "ip link add" (well, it is not me, it is automatic tests, but you probably do not care).

Yes, /etc/machine-id are the same.  Is it the core of the issue?

**Comment by AlexandraKossovsky** [comment]
We've fixed /etc/machine-id, and the bug have gone.  I guess you'll close this issue as invalid, but I have to say that "copy disk" is an old Linux tradition of cloning machines.  It is well-known that you have to fix machine name and ssh keys, but it is the first time I heard anything about /etc/machine-id.

**Comment by keszybz** [comment]
Yep, running multiple machines with the same `machine-id` on the same network is definitely not supported. In this particular case of a bond device, the generated mac address has only two stable things that can be used to generate it: the device name and the machine id. So there is no way in which we can have stable mac addresses without using the machine id.
