### ISSUE TITLE
[RFE] method for dynamically generating user name space ids (similar to /etc/sub{u,g}id)

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#13717]
**Is your feature request related to a problem? Please describe.**
Podman and other rootless container technologies use /etc/sub{u,g}id as a way to map user namespace identities to the user who owns the namespace.  On large systems with thousands of users (see large grid clusters) maintenance of these files is a hassle.

systemd's dynamic users might be a great way to lower that burden leveraging existing features.  Systemd already has a way to determine which IDs are not allocated.  Why not re-use it?

**Describe the solution you'd like**
This is the workflow I'm thinking of:

1. user runs some sort of container technology that requests a user namespace with X ids.
2. container technology asks systemd "can I have X ids?"
3. systemd sees if the user has reached their Dynamic ID limit. (should be some way to set this based on various user features, name, groups, etc)
4. If user is permitted more Dynamic IDs, systemd returns the requested IDs from the Dynamic Range

**Describe alternatives you've considered**
I've toyed with various login scripts and pam hooks, but nothing terribly satisfying.

**Comment by poettering** [comment]
Uh. The concept of subuids/subgids is just wrong, i am sorry. Static files in /etc is even worse. And there's no NSS for it either. 

I am sorry but I am so not convinced this is a good idea.

**Comment by storrgie** [comment]
Just to weigh in, not to necessarily defend the concept of `subuid` and `subgid`, but in terms of using podman and using ["rootless-podman-as-non-root" as Brian Smith states](http://www.youtube.com/watch?v=ZgXpWKgQclc&t=7m40s) there is a need to pre-enumerate the `subuid` and `subgid` for each user running podman in this fashion.

So, for example I'd like to run an application as a system user (non-root), but then further as a remapped user using [user namespace remapping](https://www.youtube.com/watch?v=Ac2boGEz2ww).

Not using `systemd-sysusers` or `systemd-tmpfiles`, the commands to prepare the system would be (for [thelounge](https://github.com/thelounge) for example):

````
sudo groupadd -g 450 thelounge
sudo useradd -u 450 -g 450 -c "System Account for thelounge" -d /opt/thelounge -s /sbin/nologin thelounge
sudo usermod --add-subuids 1200000-1265535 --add-subgids 1200000-1265535 thelounge
sudo -u thelounge mkdir /opt/thelounge/
sudo chmod -R 770 /opt/thelounge
```
Everything above can be handled by `systemd-sysusers` and `systemd-tmpfiles` except for the call to modify the user to create the sub-{uid,git} mappings.

I think that I'd weigh in that this remapping does create some irritations from the host view perspective when it comes to permissions because you have to be necessarily __more permissive__ with permissions (e.g. `o+rw`).

**Comment by frasertweedale** [comment]
> Static files in /etc is even worse. And there's no NSS for it either.

There is now support for querying subid ranges via NSS:
https://github.com/shadow-maint/shadow/pull/321

**Comment by mcassaniti** [comment]
@poettering @frasertweedale Since there is support in NSS using `libsubid`, is it possible to have a systemd library that ties into NSS to cover this? I'm no C programmer so I'd be next to useless for this kind of work.

**Comment by poettering** [comment]
Sorry, but I am pretty sure /etc/subuid is a bad idea and we should not go down this route. Static assignments of subuids are a bad idea, and so is reliance of suid/sgid and unnecessary in today's world with uidmapped mounts and stuff.

So I am pretty sure we shouldn't do this.

I am currently working on providing a small IPC service that clients can use to allocate a transient user namespace along with the optional acquire fsmount() instances of file systems matching that range. This means unpriv clients can get arbitrary stuff (including disk images) mounted safely in a way that matches their userns, and nothing from that range needs to be persisted ever (or can even be persisted).

**Comment by mcassaniti** [comment]
> Sorry, but I am pretty sure /etc/subuid is a bad idea and we should not go down this route.

@poettering I 100% agree. I was wondering if a systemd based NSS plugin to dynamically generate/provied the user namespace UID and GID mapping is reasonable considering there's NSS support for it. I'd assume that the dynamic ranges your IPC service are generating can also be queried for like this.

I'm sorry if I wasn't clear to begin with. I'm certainly not for maintaining any form of static mapping. I wouldn't even expect systemd to maintain a predictable mapping.

**Comment by keszybz** [comment]
Another option that should already work without any changes in systemd is to use userdbd. Once userdbd "knows" about some uid/gid entries, `nss-systemd` would make them available via the glibc APIs. The input to userdbd could be done in two ways: via the drop-ins in `/{etc,run,usr/lib}/userdbd`, or by providing a varlink service under `/run/systemd/userdb/` implementing https://systemd.io/USER_GROUP_API/. `podman` could use either of those mechanisms to allocate a range of uid/gids for a container. In the dynamic case, it could just respond to queries looking up what containers are visible in the file system. So systemd already provides a way to expose allocations. It just doesn't provide a mechanism to create those allocations.

**Comment by frasertweedale** [comment]
> I am currently working on providing a small IPC service that clients can use to allocate a transient user namespace along with the optional acquire fsmount() instances of file systems matching that range.

That sounds very nice and useful.

> Sorry, but I am pretty sure /etc/subuid is a bad idea and we should not go down this route. Static assignments of subuids are a bad idea,

Yes, that is the point of adding NSS support.  NSS providers can supply the appropriate values for a given user.  This is important in distributed environments (e.g. to ensure same user gets stable subuid/subgid assignments across an org's infrastructure, which can be helpful for audit/compliance objectives).

**Comment by poettering** [comment]
I guess we can close this since 8aee931e7ae1adb01eeac0e1e4c0aef6ed3969ec has been merged.

**Comment by mcassaniti** [comment]
@poettering So how would this interact with podman? Nicely some of those tools can be given a user namespace FD (bubblewrap comes to mind), but I wouldn't know from the PR documentation how to get these tied together.

Does this plug into the NSS sub-system?
