### ISSUE TITLE
EL 8: error when systemctl cat -.mount

### ISSUE THREAD

**Issue by thaygiaoth** [systemd/systemd#13710]
Hi all

I want to view systemd root filesystem mount configuration by command

systemctl cat -.mount

but it's show error on RHEL 8 systemd version 239 (others such as boot.mount is ok)

systemctl: invalid option -- '.'

![image](https://user-images.githubusercontent.com/10233106/66110972-0ded1b80-e5f2-11e9-859d-7482b47d366d.png)

**Comment by keszybz** [comment]
Try `systemctl status -- -.mount` or `systemctl status /`.
