### ISSUE TITLE
[hwdb] MOUSE_DPI incorrect for Microsoft Classic IntelliMouse

### ISSUE THREAD

**Issue by happyaron** [systemd/systemd#13711]
**systemd version the issue has been seen with**
> 247, but master has  the same hwdb entry

**Used distribution**
 > Debian buster with KDE/5.54

**Expected behaviour you didn't see**
 >  The mouse speed is very slow when display is Hi-DPI (3840x2160, scale 1.5), even if libinput accel setting is set to 1.0 (max)

**Device Information**

Device: 

> $ lsusb | grep Microsoft                                                                                                                                                                                
> Bus 001 Device 005: ID 045e:0823 Microsoft Corp.

evtest:

> Select the device event number [0-25]: 8
> Input driver version is 1.0.1
> Input device ID: bus 0x3 vendor 0x45e product 0x823 version 0x111
> Input device name: "Microsoft Microsoft® Classic IntelliMouse®"
> Supported events:
>   Event type 0 (EV_SYN)
>   Event type 1 (EV_KEY)
>     Event code 272 (BTN_LEFT)
>     Event code 273 (BTN_RIGHT)
>     Event code 274 (BTN_MIDDLE)
>     Event code 275 (BTN_SIDE)
>     Event code 276 (BTN_EXTRA)
>   Event type 2 (EV_REL)
>     Event code 0 (REL_X)
>     Event code 1 (REL_Y)
>     Event code 8 (REL_WHEEL)
>   Event type 4 (EV_MSC)
>     Event code 4 (MSC_SCAN)
> Properties:
> Testing ... (interrupt to exit)
> 

xinput properties:

> $ xinput list-props 13
> Device 'Microsoft Microsoft® Classic IntelliMouse®':
>         Device Enabled (179):   1
>         Coordinate Transformation Matrix (181): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
>         libinput Natural Scrolling Enabled (313):       0
>         libinput Natural Scrolling Enabled Default (314):       0
>         libinput Scroll Methods Available (317):        0, 0, 1
>         libinput Scroll Method Enabled (318):   0, 0, 0
>         libinput Scroll Method Enabled Default (319):   0, 0, 0
>         libinput Button Scrolling Button (320): 2
>         libinput Button Scrolling Button Default (321): 2
>         libinput Middle Emulation Enabled (322):        0
>         libinput Middle Emulation Enabled Default (323):        0
>         libinput Accel Speed (324):     0.000000
>         libinput Accel Speed Default (325):     0.000000
>         libinput Accel Profiles Available (326):        1, 1
>         libinput Accel Profile Enabled (327):   1, 0
>         libinput Accel Profile Enabled Default (328):   1, 0
>         libinput Left Handed Enabled (329):     0
>         libinput Left Handed Enabled Default (330):     0
>         libinput Send Events Modes Available (298):     1, 0
>         libinput Send Events Mode Enabled (299):        0, 0
>         libinput Send Events Mode Enabled Default (300):        0, 0
>         Device Node (301):      "/dev/input/event8"
>         Device Product ID (302):        1118, 2083
>         libinput Drag Lock Buttons (315):       <no items>
>         libinput Horizontal Scroll Enabled (316):       1

**Workaround/Fix**

Using mouse-dpi-tool, moving along an A4 paper, which is 297mm long, but the actual distance is slightly shorter than the paper. This suggests the matching resolution is between 1400dpi and 1600dpi.

> Mouse Microsoft Microsoft® Classic IntelliMouse® on /dev/input/event8
> Move the device 250mm/10in or more along the x-axis.
> Pause 3 seconds before movement to reset, Ctrl+C to exit.
> Covered distance in device units:    17045 at frequency 1227.0Hz        \^C
> Estimated sampling frequency: 1226Hz (mean 999Hz)
> To calculate resolution, measure physical distance covered
> and look up the matching resolution in the table below
>     1082mm         42.61in           400dpi
>      721mm         28.41in           600dpi
>      541mm         21.31in           800dpi
>      432mm         17.05in          1000dpi
>      360mm         14.20in          1200dpi
>      309mm         12.18in          1400dpi
>      270mm         10.65in          1600dpi
>      240mm          9.47in          1800dpi
>      216mm          8.52in          2000dpi
>      196mm          7.75in          2200dpi
>      180mm          7.10in          2400dpi
> If your resolution is not in the list, calculate it with:
>         resolution=17045/inches, or
>         resolution=17045 * 25.4/mm
> 
> Entry for hwdb match (replace XXX with the resolution in DPI):
> mouse:usb:v045ep0823:name:Microsoft Microsoft® Classic IntelliMouse®:
>  MOUSE_DPI=XXX@1226

And applying a local hwdb entry have fixed the behavior for me:

/etc/udev/hwdb.d/75-microsoft.hwdb:
```
# Microsoft Classic IntelliMouse
mouse:usb:v045ep0823:name:Microsoft Microsoft?? Classic IntelliMouse??:
 MOUSE_DPI=*1600@1000 3200@1000
```

Then ```systemd-hwdb update``` and reboot.

**Comment by poettering** [comment]
/cc @whot

If you already have a fix please submit as PR!

**Comment by happyaron** [comment]
@poettering I'm not quite sure whether this is correct for users without a Hi-DPI display and I'm new to this stuff, that's why I haven't submit it as PR. If you believe it is the same for normal displays, I can do the PR.

**Comment by whot** [comment]
the dpi is a hw feature of the mouse and is independent of whether you have hidpi or not. 1600 seems a bit much as a default, but the mouse can do [up to 3200](https://www.microsoft.com/accessories/en-au/products/mice/microsoft-classic-intellimouse#devkit-highlights).

Having said that - we default to 1000dpi in libinput, if your device has a higher dpi rate you'd make it *slower* since we now scale into a lower resolution. so while setting the dpi rate is correct, it would not resolve your original complaint here.

**Comment by happyaron** [comment]
Reading from the mouse's product materials it gives me an impression the DPI is dynamic in the hardware, and 1600 looks like to be the effective number to me even if we have 3200 in hwdb, i.e. the mouse isn't forced to use 3200. So changing this hwdb setting solves my problem, but I don't have the idea of how to explain it well.

This mouse worked in Debian Stretch that KDE/5.8.4 wasn't using libinput, after upgrading to Buster KDE/5.14.5 the mouse gets horribly slow can any acceleration doesn't improve the situation. The only tricky part I can think of  is that KDE allows to set a non-integeral scaling factor (1.5 in my case), but GNOME does not.

**Comment by whot** [comment]
try to measure multiple times with the `mouse-dpi-tool`, at different speeds. that should help with identifying whether it changes in hardware. Also attach the [`hid-recorder`](https://gitlab.freedesktop.org/libevdev/hid-tools) static output, maybe there's something interesting there (I doubt it though).

There's a known problem with hidpi screens in that libinput relies on the compositor to scale the deltas according to the pixel density. where that's not done, the movement is slower by whatever the high-dpi factor is. It's not a libinput issue per se though, it's the same with any driver - the only difference is that now there is a cap on random acceleration factors so previously we could adjust the acceleration method randomly upwards to work around this. GNOME on Wayland caters for hidpi and doesn't require it but the situation on X is still unsatisfactory. Not sure about KDE 5.14.

**Comment by poettering** [comment]
Closing due to lack of response.
