### ISSUE TITLE
selinux: random labels on /run/systemd/transient/*

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#13738]
I'm using systemd-230 with some backports (https://github.com/mikhailnov/systemd/tree/rosa-v230), sorry, did not try a newest version yet. selinux-policy is close to Fedora's.

The problem is that directory `/run/systemd/transient/` has correct label `systemd_unit_file_t`, but all files inside it (`session-*.scope`, `user-0.slice`) have random incorrect labels: `system_dbusd_var_run_t`, `avahi_var_run_t`, `cupsd_var_run_t`. They differ from boot to boot. When new tty is openned, new `session-*.scope` has the same incorrect label. If I do `touch /run/systemd/transient/test`, it correctly inherits `systemd_unit_file_t` from the parent directory.

I can't understand how this can happen. I've studied a bit how systemd hadles selinux labels and see that it labels directories only. Labels on other places in /run/systemd/ seem to be correct. These incorrect labels on /run/systemd/transient/* break many things.

System does not boot in selinux enforcing because of this (if I generate a special rule via audit2allow, it does boot), all this ivestigation was done in permissive selinux.

**Comment by mikhailnov** [comment]
ISO image to reproduce: https://abf.io/platforms/rosa2019.0/products/265/product_build_lists/28978 (append `enforcing=0` to cmdline to boot to working system).

**Comment by doverride** [comment]
Does a `restorecon -RvF /run/systemd/transient` "fix" the labels? If not then this seems to be a policy issue.

**Comment by mikhailnov** [comment]
`setfiles -F /etc/selinux/mls/contexts/files/file_contexts /run/systemd/transient` and `restorecon -RvF /run/systemd/transient` both do fix labels, so it's not a policy issue. I forgot to mention this.

**Comment by mikhailnov** [comment]
![image](https://user-images.githubusercontent.com/15802528/66272723-fb831400-e875-11e9-8c98-a58c8b2fcfe1.png)

**Comment by doverride** [comment]
Those PrivateTmp dirs for upower are mislabeled as well. Hard to say, v230 is acient,
I would probably add some "auditallow" rules to determine exactly what and how these entities are created, then I would compare and contrast that with any relevant type transition rules that sesearch lists. I would probably also try this with a "targeted" policy instead of "mls" just to see if that makes any difference at all.

**Comment by doverride** [comment]
Manual transitions override automatic transitions and default rules. Provided that `/run/systemd/transient` was created with the proper systemd_unit_t type and that the mislabeled files in there were not moved there from another location, I would say there is something wrong with the way systemd determines what labels to manually associate with these. Can you not produce this with a more recent systemd?

**Comment by mikhailnov** [comment]
As far as I understand, systemd does not associate labels fith files, only with directories. Systemd explicitly labels /run/systemd/transient:
`r = mkdir_p_label(m->lookup_paths.transient, 0755);`
(mkdir's and runs selinux labelling)

But systemd does not put any labels on _files_, at least I did not find relevant code.

Yes, I'm currently packaging systemd-243 to try it. Will write about results here. But any other ideas about how to debug this would be appreciated. I thought about transitions, but I'm not sure in which way they may be relevant.

**Comment by doverride** [comment]
On Sun, Oct 06, 2019 at 10:35:25AM -0700, mikhailnov wrote:
> As far as I understand, systemd does not associate labels fith files, only with directories. Systemd explicitly labels /run/systemd/transient:
> `r = mkdir_p_label(m->lookup_paths.transient, 0755);`
> (mkdir's and runs selinux labelling)
> 
> But systemd does not put any labels on _files_, at least I did not find relevant code.
> 
> Yes, I'm currently packaging systemd-243 to try it. Will write about results here. But any other ideas about how to debug this would be appreciated. I thought about transitions, but I'm not sure in which way they may be relevant.

Automatic transition rules can override default rules, and manual transitions can override automatic transitions.
If the /run/systemd/transient directory was labeled correctly when the files in there were created then the only way to override the default behavior would be either a auto transition, a manual transition or a `mv`.
To me the most likely candidate would be a manual (programmatic) transition overriding the default type rules.

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/13738#issuecomment-538769403

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by mikhailnov** [comment]
I've built systemd-243 with very minimal patchset (https://abf.io/mikhailnov/systemd-git/tree/rosa2019.0), this problem still remains. From time to time labels on `/run/systemd/transient` may be correct (`systemd_unit_file_t`), but in most cases they are incorrect: either `system_dbusd_var_run_t`, or or `avahi_var_run_t`, `cupsd_var_run_`t
![DeepinScreenshot_выберите-область_20191007010257](https://user-images.githubusercontent.com/15802528/66276787-a0b1e280-e89e-11e9-9c22-7172ce62c776.png)

Here is a LiveCD with that systemd-243 and this problem: https://abf.io/platforms/rosa2019.0/products/265/product_build_lists/28985

**Comment by mikhailnov** [comment]
To boot that LiveCD add `enforcing=0` like this:

![DeepinScreenshot_выберите-область_20191007010815](https://user-images.githubusercontent.com/15802528/66276828-fab2a800-e89e-11e9-8cdc-ae55c0ca9436.png)

**Comment by doverride** [comment]
On Sun, Oct 06, 2019 at 03:08:57PM -0700, mikhailnov wrote:
> To boot that LiveCD add `enforcing=0` like this:
> 
> ![DeepinScreenshot_выберите-область_20191007010815](https://user-images.githubusercontent.com/15802528/66276828-fab2a800-e89e-11e9-8cdc-ae55c0ca9436.png)

Weird...

I was not able to produce your issue by default, but when i boot in multi-user.target the issue starts surfacing (consistently).
running a `systemctl daemon-reload`, and relogging in *seems* to resolve the issue (but by then its too late i guess)

Another weird thing i noticed is something related to "cgroup_t" filesystem, not sure if its related and since i was unabled to reboot with modified policy (livecd) i wasnt able to look into this further

Can you try disabling the "policycap cgroup_seclabel" and see if that changes anything?

Can to confirm that running `systemctl daemon-reload` somewhere early in the boot process (before logging in) fixes this?

> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/13738#issuecomment-538792996

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
On Mon, Oct 07, 2019 at 12:35:43PM +0200, Dominick Grift wrote:
> On Sun, Oct 06, 2019 at 03:08:57PM -0700, mikhailnov wrote:
> > To boot that LiveCD add `enforcing=0` like this:
> > 
> > ![DeepinScreenshot_выберите-область_20191007010815](https://user-images.githubusercontent.com/15802528/66276828-fab2a800-e89e-11e9-8cdc-ae55c0ca9436.png)
> 
> Weird...
> 
> I was not able to produce your issue by default, but when i boot in multi-user.target the issue starts surfacing (consistently).
> running a `systemctl daemon-reload`, and relogging in *seems* to resolve the issue (but by then its too late i guess)
> 
> Another weird thing i noticed is something related to "cgroup_t" filesystem, not sure if its related and since i was unabled to reboot with modified policy (livecd) i wasnt able to look into this further
> 
> Can you try disabling the "policycap cgroup_seclabel" and see if that changes anything?
> 
> Can to confirm that running `systemctl daemon-reload` somewhere early in the boot process (before logging in) fixes this?

I can also tell you that i am unable to produce this issue on a Fedora livecd with kernel 5.3 and systemd 243. So it *seems* to be something specific to your configuration

> 
> > 
> > 
> > -- 
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/systemd/systemd/issues/13738#issuecomment-538792996
> 
> -- 
> Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
> https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
> Dominick Grift



-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by mikhailnov** [comment]
I've tried vanilla kernel 5.3 instead of Ubuntu's 4.15 and now system does boot in enforcing selinux and TTYs finally started to work, weird issues with croups and like "/bin/mount: no such file or directory" have also disappeared, labeles on `/run/systemd/transient` seem to be stabely correct (but I've not tested much yet).
Faceplam. Thanks for help!

**Comment by keszybz** [comment]
FTR, I have `init_var_run_t` not `systemd_unit_file_t`:
```console
$ ls -laZ /run/systemd/transient
drwxr-xr-x.  2 root root system_u:object_r:init_var_run_t:s0 140 Oct  8 09:14 ./
drwxr-xr-x. 24 root root system_u:object_r:init_var_run_t:s0 580 Oct  8 09:24 ../
-rw-r--r--.  1 root root system_u:object_r:init_var_run_t:s0 199 Oct  7 20:40 dbus-:1.3-org.freedesktop.problems\@1.service
-rw-r--r--.  1 root root system_u:object_r:init_var_run_t:s0 428 Oct  7 20:18 session-20.scope
-rw-r--r--.  1 root root system_u:object_r:init_var_run_t:s0 428 Oct  7 20:25 session-21.scope
-rw-r--r--.  1 root root system_u:object_r:init_var_run_t:s0 428 Oct  7 20:40 session-26.scope
-rw-r--r--.  1 root root system_u:object_r:init_var_run_t:s0 247 Oct  1 15:49 six.service
```

> I've tried vanilla kernel 5.3 instead of Ubuntu's 4.15 and now system does boot in enforcing selinux

OK, let's close this then. If the issue reappears, please reopen.
