### ISSUE TITLE
systemctl stuck when run start/restart

### ISSUE THREAD

**Issue by hongyi-zhao** [systemd/systemd#13736]
Hi,

I installed the latest git version of openssh-portable, and make the
following ssh.service file:

$ cat /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
After=network.target auditd.service
ConditionPathExists=!/usr/local/etc/sshd_not_to_be_run

[Service]
EnvironmentFile=-/usr/local/etc/default/ssh
ExecStartPre=/usr/local/sbin/sshd -t
ExecStart=/usr/local/sbin/sshd -D $SSHD_OPTS
ExecReload=/usr/local/sbin/sshd -t
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify

[Install]
WantedBy=multi-user.target
Alias=sshd.service

With the above service file, I will stuck on the following command:

$ sudo systemctl stop ssh
$ sudo systemctl start ssh
^C
$ sudo systemctl restart ssh
^C

If I don't hit ^C, the command will stuck there for ever.

Any hints?

ps.
```
$ sudo systemctl --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by mbiebl** [comment]
Make sure your locally compiled ssh actually supports `Type=notify`

Closing, as this is not a systemd issue.
