### ISSUE TITLE
`meson build` ends up in an endless loop with the latest meson (0.52.0)

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#13742]
One of the Centos CI jobs picked up the latest version of meson (v0.52.0) and all jobs started suddenly timeouting during the boostrap phase. After getting the version right, the issue is reproducible locally as well:

```
$ pip3 install -U --user meson==0.52.0
$ PATH=~/.local/bin:$PATH
$ meson -v
0.52.0
$ meson build -Dc_args='-g -O1 -fno-omit-frame-pointer -ftrapv' --werror -Dslow-tests=true -Dtests=unsafe -Dinstall-tests=true -Ddbuspolicydir=/etc/dbus-1/system.d -Dnobody-user=nfsnobody -Dnobody-group=nfsnobody -Dman=true -Dhtml=true
```

After waiting for an indefinite amount of time, pressing ctrl-c yields following stack trace:

```
^CTraceback (most recent call last):
  File "/home/mrc0mmand/.local/bin/meson", line 11, in <module>
    load_entry_point('meson==0.52.0', 'console_scripts', 'meson')()
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 226, in main
    return run(sys.argv[1:], launcher)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 217, in run
    return CommandLineParser().run(args)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate(intr)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 314, in generate
    self.generate_target(t)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 476, in generate_target
    self.generate_custom_target(target)
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 680, in generate_custom_target
    extra_bdeps=target.get_transitive_build_target_deps(),
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/build.py", line 2004, in get_transitive_build_target_deps
    bdeps.update(d.get_transitive_build_target_deps())
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/build.py", line 2004, in get_transitive_build_target_deps
    bdeps.update(d.get_transitive_build_target_deps())
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/build.py", line 2004, in get_transitive_build_target_deps
    bdeps.update(d.get_transitive_build_target_deps())
  [Previous line repeated 12 more times]
  File "/home/mrc0mmand/.local/lib/python3.7/site-packages/mesonbuild/build.py", line 2001, in get_transitive_build_target_deps
    if isinstance(d, BuildTarget):
KeyboardInterrupt
```

I'm not sure if the issue is on our side or theirs, but I'm going to pin CentOS CI to the last working version (0.51.2) for the time being.

**Comment by anitazha** [comment]
I've filed an issue for what I think is the blame: https://github.com/mesonbuild/meson/issues/6008

**Comment by poettering** [comment]
So, I guess we can close this as "not-our-bug"?

**Comment by keszybz** [comment]
Let's keep this open until we have a verified fix.

**Comment by jpakkane** [comment]
I started debugging this now. But I just want to say that please don't do this:

   meson build -Dc_args='-g -O1 -fno-omit-frame-pointer -ftrapv' --werror <rest of stuff>'

We have builtin functionality for `-O1`, optimization level, `-g`, which is debug (and which is enabled by default) as well as for `--werror`. Please use those instead of hardcoding your own stuff, because they integrate with all other parts in ways compiler flags don't.. `c_args` et al should only be used for uncommon special cases, such as some hypothetical `-Wnew-experimental-check`.

**Comment by jpakkane** [comment]
I went through the code, and the problematic snippet is this one here in `man/meson.build`:

                p2 = []
                foreach htmlalias : htmlaliases
                        link = custom_target(
                                htmlalias,
                                input : [],
                                output : htmlalias,
                                command : ['ln', '-fs', html, '@OUTPUT@'])
                        if want_html
                                dst = join_paths(docdir, 'html', htmlalias)
                                cmd = 'ln -fs @0@ $DESTDIR@1@'.format(html, dst)
                                meson.add_install_script('sh', '-c', cmd)
                                p2 += link
                        endif
                        html_pages += link
                endforeach

I don't really understand what this is supposed to do. `p2` starts empty, and on every round the generated html page is added to it so the next generated file has a dependency on all prior generated files, if I understand this correctly. Thus this requires an exponential amount of dependency lookup steps because every file `N` has a dependency on all files from `0` to `N-1`.

Is the input definition really correct here? I tried using plain `[]` as input (which is what the first generated file will use) and it at least configured correctly. I did not check if it does the right thing because I don't really have that knowledge.

**Comment by mrc0mmand** [comment]
> I started debugging this now. But I just want to say that please don't do this:
> 
> meson build -Dc_args='-g -O1 -fno-omit-frame-pointer -ftrapv' --werror '
> 
> We have builtin functionality for `-O1`, optimization level, `-g`, which is debug (and which is enabled by default) as well as for `--werror`. Please use those instead of hardcoding your own stuff, because they integrate with all other parts in ways compiler flags don't.. `c_args` et al should only be used for uncommon special cases, such as some hypothetical `-Wnew-experimental-check`.

Ah, thanks! I thought the related options (like `CFLAGS=-O1 vs --optimization=1`) are equally interchangeable, but apparently they're not. I fixed this in the CentOS CI and I'm going to fix it in the other places as well.

As for the man page shenanigans - these will need to be answered by someone with a bit more advanced meson-fu - @keszybz, @poettering.
