### ISSUE TITLE
Support NO_COLOR

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#13752]
Triggered by the discussions in https://github.com/systemd/systemd/issues/13561 we should evaluate whether it would make sense to support https://no-color.org

**Comment by poettering** [comment]
So weird a negated option... I wonder what the usecase for this is though... I.e. people who dislike color totally should probably tell their terminal emulator to use a grey or monochrome palette. And for shell pipelines we turn off color implicitly anyway. For individual selection for specific apps we already have an env var, so whats the point of this new env var that the other options dont solve better?

**Comment by poettering** [comment]
Also is this really a standard already? I dont know any of those apps that implement this. Are they real and relevant enough? Not sure this is something we should spearhead...

**Comment by mbiebl** [comment]
@thom311 bringing you into the loop here, since you raised that on #nm

**Comment by mbiebl** [comment]
Fwiw, I do see value in having a single env var that can be set to turn off colors in all cli applications.
Having to configure each application individually is cumbersome.
Is it already an established standard, probably not. But if we deem it a good idea, I don't see why we shouldn't pick this up.

**Comment by poettering** [comment]
I mean, if this is already commonly established standard this sounds OK to me to support, but I am not convinced we should spearhead this, this doesn't make too much sense to me, and we don't need twenty ways to do the same.

**Comment by keszybz** [comment]
It seems some people are quite unhappy with colors. Support for NO_COLOR turns out to be completely trivial, so let's do it, but without documenting it visibly. If it turns out to be widely used, we'll can always add it to docs.
