### ISSUE TITLE
networkd: New [IPv6AcceptRA] BlackList= feature affects prefixes that aren't listed

### ISSUE THREAD

**Issue by chrsmrtnx** [systemd/systemd#13767]
systemd version the issue has been seen with

  systemd 243

Used distribution

  Debian 10.1

Expected behaviour you didn't see

  Expected BlackList= option in [IPv6AcceptRA] section to block only the IPv6 prefix listed, not all prefixes received via router advertisement.

Unexpected behaviour you saw

  When a ULA prefix was listed (e.g., BlackList=fd00::), not only was the fd00:: prefix ignored, but my global prefix as well, thus breaking IPv6 Internet access.

Steps to reproduce the problem

Added:
    
    [IPv6AcceptRA]
    BlackList=fd00::
    
... to eth0.network on my desktop box. On my network, a server sends out RAs containing both the global prefix from my ISP, but also a ULA prefix (call it fd00::) that is useful for Android devices, but which complicates networking on my desktop box; hence my desire to ignore the ULA prefix, but accept the global prefix. I had thought that the BlackList= feature added in systemd 243 (https://github.com/systemd/systemd/pull/12603) would address this situation, but either I've misunderstood what it's trying to achieve or there is a bug.

Logs

Here's what it looks like when things are working (i.e. no BlackList=):
    
    Oct 05 16:01:11 systemd-networkd[14613]: NDISC: Sent Router Solicitation, next solicitation in 3s
    Oct 05 16:01:11 systemd-networkd[14613]: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
    Oct 05 16:01:11 systemd-networkd[14613]: NDISC: Invoking callback for 'router' event.
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Configuring route: dst: n/a, src: n/a, gw: fe80::1234:5678:9ABC:DEF0, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Configuring route: dst: 2607:1234:5678:9ABC::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Configuring route: dst: fd00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Updating remembered route: dst: n/a, src: n/a, gw: fe80::1234:5678:9ABC:DEF0, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Updating remembered route: dst: 2607:1234:5678:9ABC::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Remembering updated address: 2607:1234:5678:9ABC:1234:5678:9ABC:DEF0/64 (valid forever)
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Updating remembered route: dst: fd00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Remembering updated address: fd00::1234:5678:9ABC:DEF0/64 (valid forever)
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Configuring route: dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Setting routes
    Oct 05 16:01:11 systemd-networkd[14613]: eth0: Routes set
    Oct 05 16:01:12 systemd-networkd[14613]: eth0: Remembering foreign address: 2607:1234:5678:9ABC:1234:5678:9ABC:DEF0/64 (valid for 6d 23h 59min 59s)
    Oct 05 16:01:12 systemd-networkd[14613]: eth0: Remembering route: dst: 2607:1234:5678:9ABC:1234:5678:9ABC:DEF0/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
    Oct 05 16:01:12 systemd-networkd[14613]: eth0: Remembering foreign address: fd00::1234:5678:9ABC:DEF0/64 (valid for 6d 23h 59min 59s)
    Oct 05 16:01:12 systemd-networkd[14613]: eth0: Remembering route: dst: fd00::1234:5678:9ABC:DEF0/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
    Oct 05 16:01:13 systemd-networkd[14613]: eth0: Remembering updated address: fd00::1234:5678:9ABC:DEF0/64 (valid forever)
    Oct 05 16:01:13 systemd-networkd[14613]: eth0: Remembering route: dst: fd00::1234:5678:9ABC:DEF0/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
    Oct 05 16:01:13 systemd-networkd[14613]: eth0: Remembering updated address: 2607:1234:5678:9ABC:1234:5678:9ABC:DEF0/64 (valid forever)

...and here's what it looks like when things aren't (i.e. BlackList=fd00::):
    
    Oct 05 16:03:22 systemd-networkd[14655]: NDISC: Sent Router Solicitation, next solicitation in 4s
    Oct 05 16:03:22 systemd-networkd[14655]: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
    Oct 05 16:03:22 systemd-networkd[14655]: NDISC: Invoking callback for 'router' event.
    Oct 05 16:03:22 systemd-networkd[14655]: eth0: Prefix 'fd00::' is black listed, ignoring

**Comment by yuwata** [comment]
I've created #13768. If possible, please test the PR. Thank you.

**Comment by chrsmrtnx** [comment]
On my simple setup, #13768 fixes the issue. Thanks very much.

**Comment by yuwata** [comment]
Thank you for testing the PR.
