### ISSUE TITLE
systemctl restart nspawn container as a service still fails

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#13766]
**systemd version the issue has been seen with**
systemd 241 (v241-12.git1e19bcd.fc30)

**Used distribution**
fedora 30
**Expected behaviour you didn't see**
Container consistently restarting without errors - as it would be by stopping and starting the container.

**Unexpected behaviour you saw**
```
systemd-nspawn[310025]: Failed to register machine: Machine 'test' already exists
systemd-nspawn[310025]: Parent died too early
```

**Steps to reproduce the problem**
1. Create a "test" container and start it with a service file like `systemd-nspawn@test.service`
2. Use the restart command like `systemctl restart systemd-nspawn@test.service`
Job failed because the control process exited with error code.
`Active: failed` and `(code=exited, status=1/FAILURE)` with `Status: "Terminating..."`
```
systemd-nspawn[312645]: Failed to register machine: Machine 'test' already exists
systemd-nspawn[312645]: Parent died too early
systemd[1]: srvctl-nspawn@test.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: srvctl-nspawn@test.service: Failed with result 'exit-code'.
```
3. Try restart again - it works.
4. Try restart again - it fails.
5. Instantly try restart again, .. it works.
.. and so on. I can reproduce it well.

**More about the problem**

I was double checking my configs, but could not find anything that would explain this.
I was hoping that https://github.com/systemd/systemd/pull/10306 fixed this.

As a workaround:
`systemctl stop srvctl-nspawn@test.service && systemctl start srvctl-nspawn@test.service
`
Stopping and starting seem to work better, it works every time in this oneliner as the container boots up - unless it is restarted too quickly, then it may hang.

If logging in to the container and sending the `reboot` command from there, the container goes into a stalled state: `Active: inactive (dead)` with `Status: "Restarting..."` .. and it has to be restarted manually from the host.

I have a slightly modified service file, I don't think that is relevant, but in case you wonder about the service file, the extra-difference is in this line:
`ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --settings=trusted --machine=%i -D /srv/%i/rootfs`

**Comment by keszybz** [comment]
This is caused by systemd-machined. With `--register=no`, the container restarts fine. But with `--register=yes`, nspawn calls org.freedesktop.machine1.TerminateMachine, and this causes machined to send a signal to the machine. This is all circular and broken in many ways.
