### ISSUE TITLE
Commit 3b92c08 has been causing screen lockers to hang

### ISSUE THREAD

**Issue by mlindner** [systemd/systemd#13769]
Please see: https://bbs.archlinux.org/viewtopic.php?id=249053

Commit that caused the problem: https://github.com/systemd/systemd/commit/3b92c086a8d5338e2164ffa0ae48b3d03d10cfb5

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929834
https://github.com/the-cavalry/light-locker/issues/146
https://github.com/the-cavalry/light-locker/issues/126

**Comment by keszybz** [comment]
Hi,

the bug template asks for some things, in particular the **exact** version number. Without that it's hard to say anything about the bug. There have been a number of fixes for 3b92c08, in particular 5afb1f275e, 0917293072, 471cffcfb0.

Please also attach logs (Running logind with SYSTEMD_LOG_LEVEL=debug would be great).

**Comment by renataogarcia** [comment]
I'm experiencing this issue running `systemd 243.51-1`

logind logs  with debug:
[First lock success](https://gist.github.com/renataogarcia/824a60f6cfa9bd59341b0bf3d20c7112)
[Second lock fail](https://gist.github.com/renataogarcia/cf9d8795f8bc5300315f7a48bf333233)
After it fails to go to the login page I've unlocked it manually using `loginctl unlock-session 2`.

Hope this helps.

**Comment by Elliot2560** [comment]
> in particular the exact version number

Also, I believe 243.0-1 was the earliest version where this bug is present. A few users over at https://github.com/the-cavalry/light-locker/issues/146 also confirmed that after a downgrade to 242.84-2 the issue is gone.

**Comment by worldofpeace** [comment]
Hi, I'm the reporter at light-locker that confirmed reverting to a version of systemd directly before https://github.com/systemd/systemd/commit/3b92c086a8d5338e2164ffa0ae48b3d03d10cfb5 commit subverts the issue, and then building systemd with that commit causes it. So I'd say that's good as confirmed, as far as it comes to a commit that triggers the issue.

As for the additional fixes, I use NixOS which has a fork of systemd which is based off efb536d0cbe2e58f80e501d19999928c75e08f6a commit. Plus there's plenty of other people with "me too" reports.

I can make myself available for any logging or debugging efforts, just ask specifically.

**Comment by keszybz** [comment]
Thanks for the reports. Please give the PR a spin.

**Comment by worldofpeace** [comment]
@keszybz Great, currently running with this PR.
The particular issue where light-locker was affected appears to be gone, I've locally used the screenlocker 30 times in succession with no "hang".
