### ISSUE TITLE
machinectl and systemd-run have problems with variables inside curly braces

### ISSUE THREAD

**Issue by alkorsan** [systemd/systemd#13772]
using a variable with the curly brackets {}  inside machinectl or systemd-run does not work

**systemd version the issue has been seen with**
> 242

**Used distribution**
 > debian 10

**Expected behaviour you didn't see**
 > `a=1 a=1`

**Unexpected behaviour you saw**
 >` a= a=1` 

**Steps to reproduce the problem**
use machinectl:
`machinectl shell --uid=root --setenv="DISPLAY=:1.0" --setenv=SHELL=/bin/bash .host /bin/bash -lc ' a=1 ; echo a=${a} a=$a '
`

or use systemd-run:
`systemd-run --pty --pipe --wait --collect --service-type=exec --uid=root bash -lc ' a=1 ; echo a=${a} a=$a '
`

using ssh to run the command works fine:
`ssh -t root@localhost  'a=1 ; echo a=${a} a=$a '
`

**Comment by refi64** [comment]
Try using $${a}.

**Comment by alkorsan** [comment]
it works! thank you :)
can you explain to me please why it works? does machinectl really use bash to parse my command?  I never saw this $${} form in bash and could not find anything about it in machinectl or systemd-run help or google.
is this some type of escaping that I have to use always when using  machinectl/systemd-run? 
thank you

**Comment by q2dg** [comment]
See https://serverfault.com/questions/714592/how-does-this-variable-escaping-work-in-a-systemd-unit-file

**Comment by anitazha** [comment]
Pretty much the serverfault link above, but in some more detail, `machinectl` and `systemd-run` use `ExecStart=` over dbus to create services and run the commands. So it is subject to the substitutions described under "Command Lines" at https://www.freedesktop.org/software/systemd/man/systemd.service.html.
