### ISSUE TITLE
CanGraphical is "no" for X drivers with no DRM or framebuffer device (e.g. vesa)

### ISSUE THREAD

**Issue by AdamWill** [systemd/systemd#13773]
This is kind of a follow-up to https://github.com/systemd/systemd/issues/10435 , as that got closed but really, this problem never really got solved.

There's a `CanGraphical` property of seats which is supposed to be used by display managers to decide whether they should run on that seat or not. However, there have been several corner cases identified where it's wrong. One which is definitely still extant and causing problems is this.

If you boot Fedora (any recent Fedora at all) in BIOS mode with the `nomodeset` kernel argument, seat0 will wind up as `CanGraphical=no`, even though in fact a graphical session can run on the primary display just fine. This is because in this case we wind up using the X.org 'vesa' driver without any DRM or framebuffer device node, so nothing gets the 'master-of-seat' tag.

This likely affects other distros too, but it is *not* a problem if the kernel has uvesafb enabled, because in that case a framebuffer device shows up. That feature is not enabled on Fedora kernels, though. I'm not sure whether other major distros enable or disable it.

In any case, this is a clear case where `CanGraphical` is just flat out inaccurate, and it's a problem because it means display managers really can't trust it. GDM has never merged the proposed patch to trust `CanGraphical` because of this issue (and other corner cases that showed up), and we've just found out in Fedora 31 testing that SDDM is broken when booting this way because it trusts `CanGraphical`, so we're probably going to have to patch it out of SDDM too - see https://bugzilla.redhat.com/show_bug.cgi?id=1728240 and https://github.com/sddm/sddm/issues/1204 .

**Comment by parkerlreed** [comment]
I seem to have run into this issue but from the other direction. 

Nintendo Switch with Nvidia TX1. 

The seat attaches to the /sys/devices path but CanGraphical is still no

```
[root@alarm parker]# loginctl seat-status seat0
seat0
         Devices:
                  ├─/sys/devices/50000000.host1x/tegradc.0/graphics/fb0
                  │ graphics:fb0 "tegra_fb"
                  ├─/sys/devices/50000000.host1x/tegradc.1/graphics/fb1
                  │ graphics:fb1 "tegra_fb"
                  ├─/sys/devices/7000c500.i2c/i2c-2/2-0049/input/input0
                  │ input:input0 "touchscreen"
                  ├─/sys/devices/7000d000.i2c/i2c-4/4-003c/max77620-onoff/input/input1
                  │ input:input1 "max77620_onoff"
                  ├─/sys/devices/70030000.hda/sound/card0
                  │ sound:card0 "tegrahda"
                  │ └─/sys/devices/70030000.hda/sound/card0/input2
                  │   input:input2 "tegra-hda HDMI/DP,pcm=3"
                  ├─/sys/devices/70090000.xusb/usb1
                  │ usb:usb1
                  ├─/sys/devices/70090000.xusb/usb2
                  │ usb:usb2
                  ├─/sys/devices/backlight/backlight/pwm-backlight
                  │ backlight:pwm-backlight
                  ├─/sys/devices/gpio-keys/input/input4
                  │ input:input4 "gpio-keys"
                  ├─/sys/devices/sdhci-tegra.0/leds/mmc0::
                  │ leds:mmc0::
                  ├─/sys/devices/sound/sound/card1
                  │ sound:card1 "tegrasndt210ref"
                  │ └─/sys/devices/sound/sound/card1/input3
                  │   input:input3 "tegra-snd-t210ref-mobile-rt565x Headphone Jack"
                  └─/sys/devices/virtual/misc/rfkill
                    misc:rfkill
[root@alarm parker]# loginctl show-seat seat0
Id=seat0
CanMultiSession=yes
CanTTY=yes
CanGraphical=no
Sessions=
IdleHint=yes
IdleSinceHint=0
IdleSinceHintMonotonic=0
```

I've tried creating a udev rules to match to master but still nothing (This may just be formatted completely wrong)

```
[root@alarm parker]# cat /etc/udev/rules.d/71-nvidia.rules 
SUBSYSTEM=="sys", DEVPATH=="/devices/50000000.host1x/tegradc.0/graphics/fb0", TAG+="seat", TAG+="master-of-seat"
```

Any suggestions?

**Comment by parkerlreed** [comment]
Finally got this fixed. Simple in the end

```
SUBSYSTEM=="graphics", KERNEL=="fb[0-9]", TAG+="master-of-seat"
```

It doesn't advertise a driver name.
