### ISSUE TITLE
Alternative to allow a .timer unit to restart an already activate .service

### ISSUE THREAD

**Issue by rfrail3** [systemd/systemd#13780]
**Is your feature request related to a problem? Please describe.**
As the documentation of .timer [points](https://www.freedesktop.org/software/systemd/man/systemd.timer.html):

_Note that in case the unit to activate is already active at the time the timer elapses it is not restarted, but simply left running. There is no concept of spawning new service instances in this case. Due to this, services with RemainAfterExit= set (which stay around continuously even after the service's main process exited) are usually not suitable for activation via repetitive timers, as they will only be activated once, and then stay around forever._

If, for example, I install apache2 and set the following apache2.timer file:

```
[Unit]
Description=Restart apache2

[Timer]
OnCalendar=*:0/1

[Install]
WantedBy=timers.target
```

The timer executes once an keeps on 'n/a' since then:

```
# systemctl list-timers
NEXT                         LEFT          LAST                         PASSED    UNIT                         ACTIVATES
n/a                          n/a           Tue 2019-10-15 23:13:13 EDT  7min ago  apache2.timer                apache2.service
```

Using an other example, an execution script with the following script.service file:

```
[Unit]
Description=Script execution

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/usr/bin/script -a
ExecStop=/usr/bin/script -b

[Install]
WantedBy=multi-user.target

```

Adding a script.timer with the same content than above produces the same result.

**Describe the solution you'd like**
That behaviour match with the documentation, but there isn't any option to override it. It would be nice  to have an alternative or document the right way to cover this use case?

**Describe alternatives you've considered**
Keep the use of cron:
`* * * * * /usr/bin/script -a`

Tested on Debian systemd 242 (242)

Thanks,

**Comment by boucman** [comment]
I'm not sure I fully understand your problem, but isn't RemainAfterElapse supposed to solve that ? (I might be misreading the documentation, but that's my understanding...)

**Comment by rfrail3** [comment]
Thanks for the suggestions but applying RemainAfterElapse doesn't change the result. 
Basically, the problem is that is not possible to restart, from .timer unit a .service in active state.

**Comment by poettering** [comment]
i dont understand what the issue precisely is supposed to be? .timer units (like all other forms of activation) activate if needed, but are nops is the service is already active and thus activation unnecessary.

It's not and never has been about restarting stuff. So what precisely are you saying is not working correctly? I don't get it?

**Comment by rfmoz** [comment]
Duplicate of #17705
