### ISSUE TITLE
systemd-udevd fails to load IR BPF decoder due to SystemCallFilter= not allowing bpf

### ISSUE THREAD

**Issue by seanyoung** [systemd/systemd#13787]
systemd 243 (v243-2.gitfab6f01.fc31)

Fedora 31 on x86_64 (beta).

**Expected behaviour you didn't see**
Any rc_keymap can be loaded.

**Unexpected behaviour you saw**
If rc_keymap uses BPF keymap it cannot be loaded.

**Steps to reproduce the problem**
On Fedora 31:
 - install v4l-utils.
 - replace /etc/rc_maps.cfg with:
```
rc-loopback	*		imon_rsc.toml
```
 - $ udevadm control -l debug
 - $ modprobe rc-loopback
 - $ ir-keytable
   `Attached BPF protocols: ` is empty
 - $ journalctl -u systemd-udevd.service -b 0
   shows:
Oct 16 12:19:15 bigcore.mess.org systemd-udevd[2671]: event7: '/usr/bin/ir-keytable -a /etc/rc_maps.cfg -s rc0'(out) 'failed to create a map: 1 Operation not permitted'

Workaround:
In systemd-udevd.service, add bpf to SystemCallFilter.
```
SystemCallFilter=@system-service @module @raw-io bpf
```

**Comment by poettering** [comment]
hmm, i figure this should be something to fix in rc_keymap: they either shouldn't run their stuff from a udev rule, or they should include a drop-in for systemd-udevd.service that adds "bpf" to the syscall whitelist. i.e. include /usr/lib/systemd/system/systemd-udevd.service.d/50-rc-keymap.conf with the following contents:

```
[Service]
SystemCallFilter=bpf
```

So that this syscall is allowed.

I don't think we should whitelist the syscall unconditionally.

**Comment by seanyoung** [comment]
Thank you for your suggestion, I did not realise that was possible. I've added the workaround to v4l-utils: https://git.linuxtv.org/v4l-utils.git/commit/?id=7be954b74136a6bf31fc025c24d4f1db03630cea

**Comment by JamieKitson** [comment]
@seanyoung This fix appears to have caused some of our machines not to boot with udev failing to load: https://bbs.archlinux.org/viewtopic.php?id=256334 not sure how to report this bug on V4L.

**Comment by seanyoung** [comment]
@JamieKitson thanks for reporting this. Reading the thread on archlinux, it looks like users had an old `/etc/systemd/system/systemd-udev.service` file, and removing it fixed the issue. 

Although this is not ideal I'm not sure what can be done about this.

**Comment by seanyoung** [comment]
v4l bug reports can go to bugzilla.kernel.org linux-media@vger.kernel.org

**Comment by JamieKitson** [comment]
@seanyoung 
> Reading the thread on archlinux, it looks like users had an old `/etc/systemd/system/systemd-udev.service` file, and removing it fixed the issue.

I don't think this is true in every case, it's not true in my case:

    [jamie@jamie-laptop ~]$ ls /etc/systemd/system/systemd-udev.service
    ls: cannot access '/etc/systemd/system/systemd-udev.service': No such file or directory

**Comment by JamieKitson** [comment]
Ah, I do have a `/etc/systemd/system/systemd-udevd.service`. Do you understand why the two things combine to cause this issue?

**Comment by JamieKitson** [comment]
@poettering Do you have any idea why your `bpf` fix above would combine with a `/etc/systemd/system/systemd-udevd.service` file to cause udev to fail to load like this: https://pastebin.com/v8cBghez ?

**Comment by JamieKitson** [comment]
```
[jamie@jamie-laptop system]$ diff /usr/lib/systemd/system/systemd-udevd.service /etc/systemd/system/systemd-udevd.service.bak 
1,2d0
< #  SPDX-License-Identifier: LGPL-2.1+
< #
14c12,13
< After=systemd-sysusers.service systemd-hwdb-update.service
---
> Wants=systemd-udevd-control.socket systemd-udevd-kernel.socket
> After=systemd-udevd-control.socket systemd-udevd-kernel.socket systemd-sysusers.service
20d18
< # Note that udev also adjusts the OOM score internally and will reset the value internally for its workers
26d23
< ExecReload=udevadm control --reload --timeout 0
27a25
> WatchdogSec=3min
29,30c27
< PrivateMounts=yes
< ProtectHostname=yes
---
> MountFlags=slave
32d28
< RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6
34,40c30,31
< RestrictSUIDSGID=yes
< SystemCallFilter=@system-service @module @raw-io
< SystemCallErrorNumber=EPERM
< SystemCallArchitectures=native
< LockPersonality=yes
< IPAddressDeny=any
< WatchdogSec=3min
---
> #RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6
> # AF_BLUETOOTH

```

**Comment by poettering** [comment]
> @poettering Do you have any idea why your `bpf` fix above would combine with a `/etc/systemd/system/systemd-udevd.service` file to cause udev to fail to load like this: https://pastebin.com/v8cBghez ?

The new version of the service file defines a syscall filter, the old version didn't. The drop-in then extended the syscall filter. But extending a previously unset syscall filter, means extending the empty syscall filter, so that only the bpf syscall was allowed, which then quickly caused the service to conflict with it.

**Comment by seanyoung** [comment]
@poettering that's exactly right. The semantics of `SystemCallFilter=` depend on whether it was previously empty or not. If there was a way of explicitly saying "add this to the allow filter" that would be great.

**Comment by JamieKitson** [comment]
Thank you both for taking the time for a prompt response.

**Comment by JamieKitson** [comment]
A different solution would be a method of updating edited unit files. But maybe that's down to the distro?
