### ISSUE TITLE
Delegate=yes prevents from directly setting to real-time schedulers

### ISSUE THREAD

**Issue by realhezhe** [systemd/systemd#13781]
**systemd version the issue has been seen with**
> 243

**Unexpected behaviour you saw**
 > Fails to set scheduler of comand line applications to real-time scheduler, for example FIFO, with sched_setscheduler syscall.

**Steps to reproduce the problem**
If "Delegate=yes" is set in any service which boots up when the system boots up, /sys/fs/cgroup/cpu/user.slice and /sys/fs/cgroup/cpu/system.slice will be automatically created and cpu.rt_runtime_us under them will be set to 0. Which prevents command line applications from setting scheduler to real-time schedulers, since the kernel does not allow real-time tasks into groups that have no runtime assigned. See the link below.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/core.c#n4895

Users have to manually assign time to user.slice and/or system.slice to use real-timer schedulers.
One way to confirm this issue is to use the LTP case below.
strace /opt/ltp/testcases/bin/sched_rr_get_interval01
...
perf_event_open02 1 TBROK : perf_event_open02.c:316: sched_setscheduler(0, SCHED_FIFO, ...) failed: errno=EPERM(1): Operation not permitted
...

As "Delegate=yes" is said to only control the own private subhierarchy of control groups below the control group of the unit itself, see the link below, this might be a misbehaviour.
https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#Delegate=

**Comment by poettering** [comment]
we generally recommend turning off the rt group schedule in the kernel due to this, and that's what all big distros do.

The RT budget API in the kernel is really not thought to the end, it's not usable for systems like systemd since we cannot realistically assign an absolute RT budget to all groups automatically.

**Comment by realhezhe** [comment]
@poettering , thanks for your reply. But then the behaviours with "Delegate=yes" and without it should be the same. However what we have for the moment is:
1) When no Delegate is set, /sys/fs/cgroup/cpu/user.slice and /sys/fs/cgroup/cpu/system.slice are NOT created. All processes are under the root cgroup group so that they share the total cpu.rt_runtime_us(950000) and can use RT schedulers.
2) When Delegate is set to yes in ANY service, /sys/fs/cgroup/cpu/user.slice and /sys/fs/cgroup/cpu/system.slice ARE created, but cpu.rt_runtime_us in it is 0. Thus, all user processes that are under user.slice will not be able to use RT schedulers by default.

If we want not to assign any RT budget by default, we should do that no matter if an arbitrary service wants to Delegate the control. That is, whether a system assigns any RT budget by default should not depend on whether an arbitrary service sets its own Delegate variable to yes.

**Comment by realhezhe** [comment]
Any ideas folks?

**Comment by Werkov** [comment]
I cannot see what you describe with v234 and hybrid hierarchy. I have `Delegate=yes` for user@$UID.service and also for user@0.service. I suspect this changed with 02638280390d75f25efca683c5abd57a65c5a16f.

> But then the behaviours with "Delegate=yes" and without it should be the same. However what we have for the moment is:

Why do you think that? If a unit requests generic delegation, then a separate cgroup must be created for it that represents the delegated playground. The unfortunate consequence is that cgroups are created also for siblings and there you hit the non-initialized RT group issue.

**Comment by realhezhe** [comment]
> I cannot see what you describe with v234 and hybrid hierarchy. I have `Delegate=yes` for 
user@$UID.service and also for [user@0.service](mailto:user@0.service). I suspect this changed with [0263828](https://github.com/systemd/systemd/commit/02638280390d75f25efca683c5abd57a65c5a16f).

I'm on v243.

> 
> > But then the behaviours with "Delegate=yes" and without it should be the same. However what we have for the moment is:
> 
> Why do you think that? If a unit requests generic delegation, then a separate cgroup must be created for it that represents the delegated playground. The unfortunate consequence is that cgroups are created also for siblings and there you hit the non-initialized RT group issue.

By "the behaviours...should be the same", I meant that an arbitrary service should not have affected other processes that are not related to the service. Then should the "unfortunate consequence" be considered a bug? If not, should any other processes that wants to use RT group initialize rt_runtime_us in the created groups themselves?

Thanks.

**Comment by poettering** [comment]
RT group scheduling is simply not supported in systemd. Don't turn it on in the kernel. If you do anyway, you need to turn off all forms of CPU controller use by systemd and manage the hierarchy entirely on your own. But making systemd use the cpu controller means RT budgest will not be initialized and thus RT not available at all...

user@.service doesn't enable delegation for the "cpu" controller btw, so the question is what module does this enable for you?

**Comment by poettering** [comment]
(oh, and the RT group scheduler is not going to be supported on systemd in the future either, it's not semantically usable, sorry)

**Comment by realhezhe** [comment]
In my case, It's docker.service who enables the delegation and thus creates user.slice/system.slice and sets cpu.rt_runtime_us in them to 0. After removing "Delegate=yes", user.slice/system.slice would not be created.
https://github.com/docker/docker-ce/blob/master/components/engine/contrib/init/systemd/docker.service#L25

"Delegate=yes" is said to only control the own private subhierarchy of control groups below the control group of the unit itself, according to the document below.
https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#Delegate=
It seems reasonable for docker to use delegation according to the definition. But now it affects all of the rest of the processes.

Now that, as you mentioned, RT group scheduling is not supported in systemd, RT budget seems to have to be set to expected value by extra setting steps, when delegation is enabled.

Thanks.

**Comment by poettering** [comment]
Anyway, we do not support RT group scheduling. Please turn it off in the kernel. 

This may change if the RT group scheduling API semantics are made compatible with a model wherre units come and go dynamically. But right now, the semantics are too broken to be supportable by systemd.

hence, let's close this for now. Sorry!
