### ISSUE TITLE
Predictable network interface names unpredictable for Intel e1000e driver

### ISSUE THREAD

**Issue by vjraitila** [systemd/systemd#13788]
Systemd v243 (systemd-243.51-1)

Arch Linux

I have two Intel network interfaces on the motherboard - only one of which is plugged in. The one which is connected (eth0) is expected to be consistently renamed to eno1 - and has been in the past. 

However, this is no longer the case. A separate rmmod/modprobe dance works around this issue. 

The problem has not necessarily cropped up only in the latest version as the machine is not in active use, but might be an older issue. I only noticed it a while ago.

STEPS TO REPRODUCE

1. Boot to Arch Linux
2. Notice no network connectivity
3. Run `sudo rmmod e1000e && sudo modprobe e1000e`
4. Notice connectivity is restored (DHCP able to fetch an IP address for eno1)

DMESG

```
[    2.195381] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    2.195382] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    2.202919] e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    2.324969] e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
[    2.429763] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) xx:xx:xx:xx:xx:00
[    2.429769] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
[    2.429826] e1000e 0000:00:19.0 eth0: MAC: 10, PHY: 11, PBA No: FFFFFF-0FF
[    2.429941] e1000e 0000:03:00.0: Disabling ASPM L0s L1
[    2.429943] e1000e 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control
[    2.430174] e1000e 0000:03:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    2.479844] e1000e 0000:03:00.0 0000:03:00.0 (uninitialized): registered PHC clock
[    2.536379] e1000e 0000:03:00.0 eth1: (PCI Express:2.5GT/s:Width x1) xx:xx:xx:xx:xx:01
[    2.536381] e1000e 0000:03:00.0 eth1: Intel(R) PRO/1000 Network Connection
[    2.536402] e1000e 0000:03:00.0 eth1: MAC: 3, PHY: 8, PBA No: FFFFFF-0FF
--- RENAME UPON INITIAL BOOT (unexpected)
[    2.541457] e1000e 0000:03:00.0 eno1: renamed from eth1
--- RELOADED e1000e MODULE
[   89.992067] e1000e 0000:03:00.0 eno1: removed PHC
[   90.056325] e1000e: eno1 NIC Link is Down
[   90.139475] e1000e 0000:00:19.0 eth0: removed PHC
[   90.261633] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[   90.261634] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[   90.261812] e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[   90.372778] e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
[   90.473085] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) xx:xx:xx:xx:xx:00
[   90.473092] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
[   90.473144] e1000e 0000:00:19.0 eth0: MAC: 10, PHY: 11, PBA No: FFFFFF-0FF
[   90.473370] e1000e 0000:03:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
--- RENAME AFTER RELOADING MODULE (expected)
[   90.474444] e1000e 0000:00:19.0 eno1: renamed from eth0
[   90.525556] e1000e 0000:03:00.0 0000:03:00.0 (uninitialized): registered PHC clock
[   90.732800] e1000e 0000:03:00.0 eth0: (PCI Express:2.5GT/s:Width x1) xx:xx:xx:xx:xx:01
[   90.732803] e1000e 0000:03:00.0 eth0: Intel(R) PRO/1000 Network Connection
[   90.732820] e1000e 0000:03:00.0 eth0: MAC: 3, PHY: 8, PBA No: FFFFFF-0FF
[   96.960771] e1000e: eno1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
```

RELATED SYSTEMD NETWORK CONFIGURATION

[99-default.link.txt](https://github.com/systemd/systemd/files/3737533/99-default.link.txt)

**Comment by vjraitila** [comment]
Based on the logs it looks to me that there is some type of a race condition happening here. Upon initial boot the rename to eno1 occurs only after both interfaces have been assigned their 'original' names: eth0 and eth1, respectively.

However, when I reload the driver, the rename to eno1 already happens when then first interface (eth0) is recognized. As the name 'eth0' is now free after rename, the second interface now gets it instead.

**Comment by keszybz** [comment]
Please show the output of
```bash
SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_id /sys/class/net/eth0
SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_id /sys/class/net/eth1
SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/eth0
SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/eth1
```
(or whatever the devices are names after the renaming is done).

**Comment by vjraitila** [comment]
Attached outputs from
```
SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_id /sys/class/net/eth0
SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_id /sys/class/net/eno1
SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/eth0
SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/eno1
```
in the unexpected case where eth1 gets renamed to eno1 instead of eth0.

[e1000e_test-builtin_eth0.txt](https://github.com/systemd/systemd/files/3785539/e1000e_test-builtin_eth0.txt)
[e1000e_test-builtin_eno1.txt](https://github.com/systemd/systemd/files/3785542/e1000e_test-builtin_eno1.txt)
[e1000e_test_eth0.txt](https://github.com/systemd/systemd/files/3785545/e1000e_test_eth0.txt)
[e1000e_test_eno1.txt](https://github.com/systemd/systemd/files/3785547/e1000e_test_eno1.txt)

**Comment by vjraitila** [comment]
Running `dmidecode` shows
```
Handle 0x0025, DMI type 41, 11 bytes
Onboard Device
	Reference Designation: Intel(R) 82579V Gigabit Network Device
	Type: Ethernet
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:00:19.0

Handle 0x0026, DMI type 41, 11 bytes
Onboard Device
	Reference Designation: Intel(R) 82574L Gigabit Network Device
	Type: Ethernet
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:03:00.0
```

According to my limited understanding the 'Type Instance' should be unique here per device type. Buggy firmware?

**Comment by vjraitila** [comment]
It is an old Intel DZ77GA-70K motherboard and since they've exited that particular business years ago, there is next to no hope of getting the firmware updated.

Therefore, I've decided to work around the issue by switching to the 'path' naming policy instead for the e1000e driver.

```
# /etc/systemd/network/10-e1000e-quirks.link
[Match]
Driver=e1000e

[Link]
NamePolicy=path
```

By all means let me know if there is a better way.

**Comment by poettering** [comment]
yeah, the firmware is flawed here, it exposes the same slot multiple times.

**Comment by chris400** [comment]
oh dear, gr8 I found that issue! 👍 
I am using an Intel DQ77MK and this was driving me nuts.

@vjraitila thx for the workaround! :)

**Comment by yuwata** [comment]
As already concluded, this is not our bug. Closing.
