### ISSUE TITLE
ExecStopPost= support for Type=oneshot services

### ISSUE THREAD

**Issue by corsac-s** [systemd/systemd#13796]
This issue is cloned from #2582 following advice from @anitazha 

I'm unsure if it should be reported as a bug or as a feature request but anyway. ExecStopPost= doesn't seem to work with Type=oneshot, so it's not possible right now to nicely handle failure of an ExecStart= job (for example for notifying an administrator).

I'm unsure of the side effects, but it would be nice to have.

**Comment by avrittrohwer** [comment]
I would call this a bug.  systemd.service(5) makes no mention of this not working for oneshot services.

**Comment by andrejpodzimek** [comment]
This bug (sort of) explains why [this thread](https://lists.freedesktop.org/archives/systemd-devel/2019-October/043594.html) recommends `ExecStartPost` instead of `ExecStopPost`. The latter would make much more sense though &mdash; if it worked.

**Comment by alexlzhu** [comment]
This appears to have already been fixed. Below is the output when I ran ```sudo systemd-run --unit=oneshot1.service --wait -p StandardOutput=tty -p StandardError=tty -p Type=oneshot -p ExecStopPost='/bin/touch /run/oneshot1' true```

Output:

```
Running as unit: oneshot1.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 3ms
CPU time consumed: 3ms
```

**Comment by anitazha** [comment]
Can confirm the same on ExecStart= failure:
```
$ sudo systemctl cat test
[Service]
Type=oneshot
ExecStart=/bin/false
ExecStopPost=/bin/touch /tmp/testing
$ ls /tmp/testing
ls: cannot access '/tmp/testing': No such file or directory
$ sudo systemctl start test
Job for test.service failed because the control process exited with error code.
See "systemctl status test.service" and "journalctl -xeu test.service" for details.
$ ls /tmp/testing
/tmp/testing
```

Please reopen if there is a specific repro we're missing.
