### ISSUE TITLE
bootctl fails to install/copy files to EFI/Boot

### ISSUE THREAD

**Issue by oliv3r** [systemd/systemd#1379]
Due to various osx guides suggesting to put bootx64.efi into EFI/BOOT (note casing) I already had said file/directory.

Failed to open "/boot/efi/EFI/Boot/BOOTX64.EFI" for writing: No such file or directory

Not sure if it is because BOOT already exists (on a fat32 partition), but bootctl fails to install.
bootctl --version
225

**Comment by kaysievers** [comment]
"/boot/efi/EFI/" does not look like systemd's version of bootctl.
Which distro is that? 
What is in /etc/fstab for /boot?

**Comment by oliv3r** [comment]
I could have elaborated here more, I mount /dev/sda1 (ESP) in /boot/efi hence the path

the problem is, if a /EFI/BOOT exists (and bootctl wants to work with Boot) things go bad (tm).

**Comment by kaysievers** [comment]
systemd/bootctl expects the ESP to be mounted at /boot, it will not work with /boot/efi/.

**Comment by oliv3r** [comment]
That is not true, and bootctl has a seperate parameter specifically for this:
     --path=PATH     Path to the EFI System Partition (ESP)

**Comment by kaysievers** [comment]
I thought you were talking about the default, and you don't use --path. Please provide exact examples and don't just vaguely describe things. This is too confusing.

It seems to work fine here:

# bootctl install --path=/boot/efi

Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/efi/EFI/Boot/BOOTX64.EFI".
Created EFI boot entry "Linux Boot Manager".

**Comment by oliv3r** [comment]
i think i was reasonably clear

but here goes:

rm -rf /boot/efi/EFI/
mkdir /boot/efi/EFI/BOOT
touch /boot/efi/EFI/BOOT/BOOTX64.EFI

bootctl --path=/boot/efi install

it fails because it tries to copy/replace /boot/efi/EFI/Boot/, but that isn't accessible (note the capitilization)

**Comment by kaysievers** [comment]
This still works fine here. You might need the right options to mount the FAT volume, if you mount it yourself?

**Comment by oliv3r** [comment]
i'll check the mount options, see if I can force all upper case or something.

But it 'looks' feels that the fat partition think Boot and BOOT are the same, yet it's not. I'll double check if its reliably reproducable anyway. But since rm -r EFI/BOOT fixed it ... i may get lazy ;)

**Comment by oliv3r** [comment]
I went back to this to double-check things, here's the bug explained again.

oliver@mba:/boot/EFI$ sudo mv Boot BT
oliver@mba0:/boot/EFI$ sudo mkdir BOOT
oliver@mba:/boot/EFI$ sudo cp debian/grubx64.efi BOOT/BOOTX64.EFI

After this, we have a 'normal' EFI/BOOT structure. /dev/sda1 is mounted at /boot (the EFI partition)

oliver@mba:/boot/EFI$ sudo bootctl install
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Failed to open "/boot/EFI/Boot/BOOTX64.EFI" for writing: No such file or directory

So as you can see ,this is still broken with bootctl 225.

Also, i'm slightly questioning the use of Boot as directory name. I think normal EFI systems don't care about capitilization, but from what I've learned so far from various resources online, Apple prefers it's boot directory to be in all caps, BOOT, which is not unreasonable for a default for bootctl.

Kindly reopen this issue :)

**Comment by kaysievers** [comment]
Just tried, that still just works all fine. I still suspect you need to fix your FAT handling/mount-options for /boot to behave as expected.

**Comment by kaysievers** [comment]
"Boot" is the Windows default, and should just work as well as BOOT, if set up correctly.

**Comment by smurfix** [comment]
Sorry about the spurious reference, that was the Raspberry Pi kernel build number. :-/
