### ISSUE TITLE
Long shutdown duration

### ISSUE THREAD

**Issue by neuro-sys** [systemd/systemd#13804]
**Is your feature request related to a problem? Please describe.**

When systemd is shutdown, it takes a long time (or in some cases indefinitely) to finish when some processes do not respond to signals issued by systemd. This causes filesystem to get corrupt when there is no choice other than powering off the computer. 

I understand that the generous 90 seconds default is to give time for critical systems to shutdown gracefully, especially for servers for which systemd should be more careful for, and the assumption that user processes should properly handle signals, but more often than not this is not the case.
 
Based on google search results, this seems to be a common issue for many people for quite a long time.

**Describe the solution you'd like**

If systemd is capable/permitted to read/write to the active tty, ~can it by default print the name of processes that don't respond to shutdown signals~ (edit: it turns out it already does print the service description), and prompt the user if they want to force kill it before the timeout ends, and proceed the shutdown sequence?

**Describe alternatives you've considered**
None.

**Comment by poettering** [comment]
We have such output already that shows which service is delaying. Are you using a bootsplash or so that hides this?

What version of systemd are you running?

(We ask these questions not because we have nothing better to do, but because we want to know which version you run, given that some issues are already fixed in later versions)

**Comment by neuro-sys** [comment]
> We have such output already that shows which service is delaying. Are you using a bootsplash or so that hides this?

My bad. I created a test "unit" that traps all signals to reproduce the problem, and on poweroff the service "description" is printed.

I should mention that after I upgraded my system which was stale for some time, my previous issue has disappeared.

My confusion was because the log message I got at the time was like the following:

```
A stop job is running for Session 1 of user ...
```

Where I didn't realize `Session 1 of user` was the service description of a unit called `session-1.scope`. I still think printing the unit name instead could be more self evident.

Even though my issue has gone away, I know that the blocking unit was then called `session-1.scope`, which is another issue not related to systemd I believe.

Another problem related to this is that while waiting for the timeout on poweroff, I cannot switch to other virtual terminals using CTRL + ALT + Fn keys. Is this somehow related to the systemd behavior? If the user can fall into a shell, at least they can manually kill the offending service, in my case is still not possible.

**Comment by neuro-sys** [comment]
Closing this as my problem is gone.
