### ISSUE TITLE
Portablectl does not wait for loop module.

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#13805]
**systemd version the issue has been seen with**
> 22

**Used distribution**
 > minimal (buildroot)

**Expected behaviour you didn't see**
 > portablectl inspect <an image> succeeds at first attempt

**Unexpected behaviour you saw**
 > portablectl inspect fails at first attempt complaining that the ressource is busy
* second attempt works correctly
* loading the "loop" module before the first attempt makes the first attempt succeed

This might be a kernel bug (a call somewhere returning too early) but i don't have the technical level to make sure of that... so feel free to close if that's the case.

**Comment by poettering** [comment]
we access loopback devices through /dev/loop-control, which should trigger module auto-loading. Are you saying that doesn't work for you?

what is systemd version 22? Are you sure you mean that?

**Comment by boucman** [comment]
my bad : systemd version is v241

autoloading works correctly, it's just... too slow. I get an error from portablectl on the first attempt, but since autoloading is triggered, the second attempt works correctly.

**Comment by boucman** [comment]
is there something else I need to feedback ? 
my guess is that it's a kernel problem (call returns before loop module is ready) but I would like someone more knowledgeable to confirm...

**Comment by poettering** [comment]
can you strace -f portabled when this happens?

**Comment by boucman** [comment]
Ok, so....
When running portabled under strace, the problem disapears. I hate eisenbugs...

I tried a dozen times and I reliably reporduce the bug when launching portabled directly and never get it when under strace.

I am opened to any suggestion on how to move forward...

BTW, the exact message printed by portabled is:

`Event loop failed: Device or resource busy`

**Comment by poettering** [comment]
which systemd version did you see this with, btw?

**Comment by poettering** [comment]
i.e. does your version include 0f6519d43c37d5a855a6c9be52148908c15c3c9d? you didn't fill in that part of the form (please always do!)

**Comment by boucman** [comment]
I tested with 241,so without that commit.  but since I opened that bug I have the tooling in place with v243.

I'll do that and report back.

**Comment by boucman** [comment]
Ok, just tested with v243.4 and I can confirm the bug is gone

Thx for the hard work
