### ISSUE TITLE
Ubuntu CI: build self-test fails: 537/760 fuzz-dns-packet:oss-fuzz-13422:address  TIMEOUT 30.04 s 

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#13815]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Ubuntu CI

**Expected behaviour you didn't see**
 > test pass

**Unexpected behaviour you saw**
 > build self-test fails due to: 537/760 fuzz-dns-packet:oss-fuzz-13422:address  TIMEOUT 30.04 s 

**Steps to reproduce the problem**
Two PRs have failed due to this so far, #13806 (arm64 failed) and #13808 (amd64 failed)

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/arm64/s/systemd-upstream/20191020_135904_28655@/log.gz

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20191020_172524_bbc2f@/log.gz

**Comment by keszybz** [comment]
#13821 should fix this. But it needs more work.

**Comment by poettering** [comment]
@keszybz can we close this bug?

**Comment by yuwata** [comment]
I've never seen the failure recently. Closing.
