### ISSUE TITLE
Support kernel, initrd etc. GPG verification in systemd-boot

### ISSUE THREAD

**Issue by madaidan** [systemd/systemd#13816]
**Is your feature request related to a problem? Please describe.**

To increase security, it would be great if systemd-boot supported a form of verified boot that allows users to manually sign their kernel, initrd etc. with their own GPG keys.

This ensures that all code loaded by systemd-boot has not been tampered with.

UEFI secure boot is sometimes not optimal as it can't verify the initrd and Microsoft has [leaked the keys before](https://www.zdnet.com/article/microsoft-secure-boot-key-debacle-causes-security-panic/) allowing attackers to bypass it. UEFI secure boot could even be used in combination with this to ensure the bootloader is not compromised.

**Describe the solution you'd like**

Add a feature similar to GRUB's `check_signatures=enforce` (https://www.gnu.org/software/grub/manual/grub/html_node/Using-digital-signatures.html) for increased security.

**Describe alternatives you've considered**

None.

**Comment by grawity** [comment]
> This ensures that all code loaded by systemd-boot has not been tampered with.

What will ensure that systemd-boot _itself_ has not been tampered with?

**Comment by grawity** [comment]
> UEFI secure boot could even be used in combination with this to ensure the bootloader is not compromised.

If you trust Secure Boot, then you can already use the same Secure Boot (e.g. with your own keys) to secure the kernel and initramfs. A very common method is to use systemd's "EFI stub" `linuxx64.efi.stub` to create a combined (kernel+initramfs).efi image that will be verified by Secure Boot as a single unit.

The same can be applied to systems using TPM even without Secure Boot, as the combined (kernel+initramfs).efi binary will be hashed into PCR4 as a single unit – along with systemd-boot.efi itself.

If you do not trust Secure Boot, and if your system doesn't use TPM for boot verification, then there is nothing that prevents systemd-boot itself from being replaced with an older version that just skips the PGP check.

**Comment by poettering** [comment]
SecureBoot already does all this, and you can flush out Microsoft's keys from the firmware and replace them with your own.

I don't think we need to replicate the signing logic for this a second time, and certainly not with gpg, in particular as you have to use the SecureBoot stuff anyway for the first element in the chain, in which case you might as well use it for the other parts too until Linux takes over.

sd-boot is designed to rely on SecureBoot for signing stuff, and the `mkosi`(https://github.com/systemd/mkosi) tool even makes it easy to build properly secured kernels, with your own signing keys. I think that#s as good as it gets, since without signing the boot loader itself the whole excercise is pointless anyway...

**Comment by poettering** [comment]
Or what am I missing?

**Comment by flixman** [comment]
Hi @poettering. I am adding this message on this thread as you asked a question after closing it. If appropriate, I can ask the same on a new thread. I am facing a similar situation than OPs: I have sd-boot in place and I'd like to have a signature check on the initramfs besides than the kernel.

I have already seen that an efi image can be generated containing the kernel and initramfs, but this would involve recreating the efi image every time any of these elements gets updated. On systems with TPM-secured full disk encryption, this would imply to have to update also the TPM policies that contain the PCR registers.

Given this, I think there is a legitimate business case for systemd-boot having some way to validate kernel/initramfs images. The kernel is signed anyway if SB is enabled, the initramfs signing is enforced, and systemd-boot efi images do not change.

**Comment by grawity** [comment]
> On systems with TPM-secured full disk encryption, this would imply to have to update also the TPM policies that contain the PCR registers.

But if you're using the PCR 4 register, then you _already_ have to do this every time the kernel changes, don't you?
