### ISSUE TITLE
Option for EFI random seed crediting

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#13829]
**Is your feature request related to a problem? Please describe.**

I'm trying to figure out why the early boot process feels noticeably slower, and I suspect the EFI random seed feature is part of that.

I don't know if this has always been the case, but on this (old-ish) laptop, EFI variable access is currently quite slow – e.g. it takes 0.4–0.5 seconds to read `/sys/firmware/efi/efivars/LoaderRandomSeed-*` or any other variable. (Yes, this means running `bootctl` also takes quite a while.)

**Describe the solution you'd like**

 1. Something like `systemd.efi_random_seed=no`, to have pid1 avoid touching EFI variables
 2. Maybe a similar option for systemd-boot (this system doesn't have the EFI RNG protocol anyway)

**Describe alternatives you've considered**

I could configure _mkinitcpio_ to always create the `/run/systemd/efi-random-seed-taken` file in the initramfs before systemd starts, and/or switch to an older version of systemd-boot which doesn't create the variables.

I could try factory-resetting the firmware, in case it clears the EFI NVRAM and makes access fast again.

**Comment by poettering** [comment]
Note that LoaderRandomSeed is not stored in the NVRAM but is just a variable passed from EFI loader to OS, in plain RAM. It's not persisted.

Is there anything in the logs about this?

Are really all EFI var access that slow? Or only the RAM based ones? This is certainly very strange

That said, you can already turn this off:

https://www.freedesktop.org/software/systemd/man/loader.conf.html#random-seed-mode

i.e. drop "random-seed-mode off" in your loader.conf

**Comment by grawity** [comment]
> i.e. drop "random-seed-mode off" in your loader.conf

Thanks, I completely overlooked this option.

Although I'm no longer sure if this is actually related to my boot issue, it might be just the recent kernel RNG+ext4 mess (this system lacks even RDRAND, and someone just recently pointed out to me that the alternative fixes will only be in 5.4, not in 5.3).

> Are really all EFI var access that slow? Or only the RAM based ones? This is certainly very strange

The firmware-defined variables (e.g. ASUSFactoryControl, SLP2, OfflineUniqueIDRandomSeed – that's an interesting one) still seem to be reasonably fast (2–35 ms).

But all user-defined variables seem to be slow to read, whether they're in RAM (LoaderTime*, BootCurrent, ConInDev) or in NVRAM (Boot0001, LoaderEntryDefault). Oddly the volatile RAM variables are _slightly slower_ (490–500 ms) than the NVRAM variables (460–480 ms).

The same 5.3.7 kernel version has no issues on my other EFI-based PCs. This is an old Win7-era computer and definitely didn't have variable access anywhere as fast as newer systems do, but IIRC it used to be somewhere in the ~150ms range – I don't think it was quite _this_ slow previously...

Either way, I will try clearing the NVRAM and see if that helps.
