### ISSUE TITLE
Setting MemorySwapMax=0 for user slices ignored while it shouldn't

### ISSUE THREAD

**Issue by dev-zero** [systemd/systemd#13826]
**systemd version the issue has been seen with**

v234 (openSUSE 234-lp151.25.7), but based on code analysis most recent versions are likely to be affected.

**Used distribution**

openSUSE Leap 15.1

**Expected behaviour you didn't see**

Setting `MemorySwapMax=0B` in `[Slice]` should set `memory.swap.max=0`, effectively disabling swap for the user slice.

**Unexpected behaviour you saw**
 
```
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:3: Memory limit '0B' out of range. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:2: Failed to assign slice user.slice to unit user-7184.slice. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:3: Memory limit '0B' out of range. Ignoring.
Oct 23 11:08:31 myhost systemd[1]: /etc/systemd/system/user-7184.slice:2: Failed to assign slice user.slice to unit user-7184.slice. Ignoring.
```

**Steps to reproduce the problem**

With v234, create a user slice config `/etc/systemd/system/user-7184.slice`:

```
[Slice]
Slice=user.slice
MemorySwapMax=0B
```

**Extra notes**

Setting the `memory.swap.max = 0` is effectively possible. By using the following slice config:

```
[Slice]
Slice=user.slice
MemorySwapMax=1B
```

I effectively get:

```console
$ cat /sys/fs/cgroup/user.slice/user-7184.slice/memory.swap.max
0
```

It seems that a similar problem was fixed in de8776316e529dc21d0140a50f348f3ff2046b52, but user slice groups seem to take a different path and end up here:
https://github.com/systemd/systemd/blob/c199cc0704271378ea5eafc0bddb6b7453c4e71f/src/core/load-fragment.c#L3218-L3222

**Comment by yuwata** [comment]
v234 is too old here... de87763 was merged in v239. Please check the issue with v239 or newer.

**Comment by dev-zero** [comment]
@yuwata please read the cited source code line from `master`: the problem is still there: `bytes <= 0` should be `bytes < 0`

**Comment by yuwata** [comment]
No, we have `!STR_IN_SET(lvalue, "MemorySwapMax", "MemoryLow", "MemoryMin", "DefaultMemoryLow", "DefaultMemoryMin")`.

Anyway, please test the issue with newer systemd. Or report the issue to your distro.

**Comment by dev-zero** [comment]
@yuwata aah, right, I missed the `!` in `!STR_IN_SET`, sorry, my bad
