### ISSUE TITLE
Partial listing of units using 'systemd-analyze critical-chain'

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#13834]
OS: Fedora; Component: systemd.x86_64  243-3.gitef67743.fc31

No option related to a full listing present from `systemd-analyze` . That command which used to output a complete list of unit services lists in that version partially as illustrated:. 
```
$ systemd-analyze critical-chain | tail -2
                                          └─-.mount
                                            └─...
```

**Comment by poettering** [comment]
I am sorry, but I don't get what you are saying? Please fill in the supplied issue form, it exists for a reason, and I cannot understand what you are trying to say?

**Comment by Ricky-Tigg** [comment]
There was  certainly no need here for being sorry,, that may happen sometimes to some people anyway. Looks like English to me, ,your writings as well at least bor both  a kind of. Command's output;was explicit for a novice and it did not need to be interpreted. Though you must be developper! I take you by hand then for that time. 

As illustrated list of units started at boot was incomplete; complete list was expected. You should definitively close each time you feel so unsure. Issues would remain and nobody would blame you. That's just language.
```

                                            └─...
```

**Comment by poettering** [comment]
i don't get it. are you seeing the ellipsis "..." in the output and don't like that? what is this about?

**Comment by Ricky-Tigg** [comment]
Here we are; one's gets "ellipsis" for "...", one's –me then– gets "there is more"  for "...". You make me doubt you run at all same command.

**Comment by poettering** [comment]
i can't parse your sentences, I am sorry. I really don't get what you are trying to say?

**Comment by Ricky-Tigg** [comment]
At this time you should be ready to close.

**Comment by poettering** [comment]
OK, if you say so!

**Comment by mrc0mmand** [comment]
Just to make this (hopefully) a little bit clearer, the reporter is confused by the ellipsis at the end of the `systemd-analyze critical-chain` output, which suggests there is a certain part of the output missing. If that's indeed true, the reporter would like to have an option to see the un-truncated dependency chain/tree (something along the `-l/--full` option in `systemctl`).

The code responsible for the ellipsis seems to be https://github.com/systemd/systemd/blob/f4dad55b8b2861426a7b9e7104dec33acb770894/src/analyze/analyze.c#L957

**Comment by Ricky-Tigg** [comment]
Previous comment would have been mine if I had been developer and notice such behaviour, which was to find at last a mean provided by me, to close safely that way. Of course you should not had in that circumstance close and certainly not that way. It was not healthy for your self-dignity to grab my suggestion. How many reports had been already ended that way before that scenario? So  strange how some of us get in real life, –not within code– "Hello" when it is meant for "Hello", and some don't. Since all relies on the backgrounds of any "Hello", it is not surprising people do not understand themselves, no matter the language involved. All good.
