### ISSUE TITLE
Systemd-networkd is not creating static route

### ISSUE THREAD

**Issue by ne-vlezay80** [systemd/systemd#13830]
**systemd 243 (243.78-1-arch)*
> ...

**Used distribution**
 > Arch Linux
**Expected behaviour you didn't see**
 > Systemd networkd should create static route else add [Route] directive and destinatin route or Gateway param
**Unexpected behaviour you saw**
 > Systemd networkd is not create static route else add dual stack ipv4 and ipv6 address
**Steps to reproduce the problem**
Config:
```
[Match]
Name=eth0

[Address]
Address=172.17.100.18/24

[Address]
Address=30*:***:****:****::18/64

[Address]
Address=1**.**.**.*/32

[Address]
Address=2a**:**:****:*::5/128

[Route]
Destination=0.0.0.0/0
Gateway=172.17.100.1

[Route]
Destination=::/0
Gateway=3**:***:****:****::1
Source=2***:**:****:*::5
```
This config normally working is old version systemd.

**Comment by yuwata** [comment]
Please provide debugging logs. It can be generated by creating the following drop-in file:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by yuwata** [comment]
Lack of response. Closing.
