### ISSUE TITLE
PartOf= does not work on inactive units

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#13850]
**systemd version the issue has been seen with**
242-7

**Used distribution**
Debian Unstable

**Expected behaviour you didn't see**
`PartOf=` propagates stops/restarts recursively, even to units behind inactive intermediary units. In other words: with PartOf relationships A → B → C, stopping C should stop A even if B is inactive.

**Unexpected behaviour you saw**
Stopping C does not stop A. However, stopping B directly (that is, *stopping an already inactive unit*)  does stop A, which I find a tad surprising and perhaps inconsistent: if I can issue a stop request on an inactive unit and it propagates just fine, then how come `PartOf=` doesn't work on that very same unit?

**Steps to reproduce the problem**

`test-a.service`:
```
[Unit]
PartOf=test-b.service

[Service]
Type=oneshot
ExecStart=/bin/true
RemainAfterExit=yes
```

`test-b.service`:
```
[Unit]
PartOf=test-c.service

[Service]
Type=oneshot
ExecStart=/bin/true
```

`test-c.service`:
```
[Service]
Type=oneshot
ExecStart=/bin/true
```

Then run:

```
# systemctl start test-a.service test-b.service test-c.service
# At this point test-a.service is active, test-b.service and test-c.service are inactive
# systemctl stop test-c.service
```

Then observe that `test-a.service` is still in active state. Note that if you run `systemctl stop test-b.service` directly, `test-a.service` is stopped. Also, adding `RemainAfterExit=yes` to `test-b.service` (to keep it active) will prevent reproduction. It does not matter whether `test-c.service` is active or not.

**Comment by dechamps** [comment]
@keur I just upgraded my Debian Sid machine to systemd `245.2-1` which, as far as I can tell, contains your fix from 097537f. But I can still reproduce the issue using the same procedure as in my original post :( 

Can someone reopen this issue please? (I don't have permission to do so.)

**Comment by keur** [comment]
The patch caused a lot of problems and is reverted downstream. Please read the discussion in the PR.

**Comment by dechamps** [comment]
> The patch caused a lot of problems and is reverted downstream. Please read the discussion in the PR. 

Ah, apologies, I didn't realize there was a discussion on the PR. It's sad that this can't be fixed without introducing regressions, but I understand that it's unlikely to be worth it in this case.
