### ISSUE TITLE
Don't set a loading loop for a service if the hardware can't support it

### ISSUE THREAD

**Issue by dino99** [systemd/systemd#13852]
**Is your feature request related to a problem? Please describe.**

yes, log is  flooded with:

systemd: Failed to start TPM2 Access Broker and Resource Management Daemon

(On Ubuntu Focal with systemd 243-2ubuntu1)

This has the bad effect to heavily slowdown the network; mostly the url resolution 

**Describe the solution you'd like**

Digging that issue, that link gave me explanation and solution:
https://www.reddit.com/r/linuxquestions/comments/dhinl0/what_is_tpm2abrmdservice_and_why_does_it_try_fail/

so i've checked my hardware:
 ls /dev | grep tpm0      ===> nothing found; so going to disable that service

sudo systemctl disable tpm2-abrmd.service
[sudo] password for oem:
Synchronizing state of tpm2-abrmd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable tpm2-abrmd
Removed /etc/systemd/system/multi-user.target.wants/tpm2-abrmd.service.

After restarting the session, the error is no more logged, and url network resolution is now as fast as it have to.
**Describe alternatives you've considered**

So this is a workaround about that issue; but i can imagine some other services failing on non compatible hardware too. 
===> Systemd should check the hardware to load only on compatible system (if not yet done by udev, sysv or else indeed)

**Comment by keszybz** [comment]
This service is part of tpm project (https://github.com/tpm2-software/tpm2-tss).
