### ISSUE TITLE
 Closed

### ISSUE THREAD

**Issue by IceTrayz** [systemd/systemd#13858]

**Comment by poettering** [comment]
this requires that systemd is used in the initrd. does ubuntu do that?

**Comment by Lucapz** [comment]
Thanks for getting back to me , someone else suggested that initrd might be the issue on reddit.I'll ask on the ubuntu forum if they use initrd and get back to you as this is all a bit above me.

I have been using Debian FSprotect that gives a read only desktop but that uses AUFS with initramfs and was told it's similar idea but different so i might be out of luck. :(

**Comment by Lucapz** [comment]
https://ubuntuforums.org/showthread.php?t=2430299

Just posted , not sure if i asked the question correctly.

**Comment by mbiebl** [comment]
Fwiw, initramfs-tools, the default initramfs builder in Debian and Ubuntu does not use systemd.

Debian does also provide dracut (which uses systemd), but I dunno how well that works in Debian.

**Comment by Lucapz** [comment]
Thanks for clearing that up as i've spent the last couple of weeks going around in circles.

I wish everyone would just make life easier and move fully over to systemd as i need a simple point and click OS.

**Comment by Lucapz** [comment]
Can anyone suggest a (easy point and click) gnome based distro where this command works as intended as i'm going around in circles?

Due to my learning issues the distro would need to be like Ubuntu and include all necessary nvidia drivers , media codecs and Firefox graphic accelerations for media playback as i just don't have any tech skills , i can only follow step by step guides for dummies?

Thanks

**Comment by poettering** [comment]
If you have limited tech skills, then Ubuntu is an OK choice, and systemd.volatile= not really useful to you anyway. It's an option for system integrators, not users with limited tech skills.

**Comment by Lucapz** [comment]
https://github.com/sharhalakis/fsprotect

I thought systemd.volatile=overlay was like fsprotect where you add a command to boot for a read only immutable system that only ever writes to ram?

I've been using fsprotect for the last few years just by editing grub.

**Comment by Lucapz** [comment]
Does systemd.volatile=overlay create a read only immutable desktop where all changes are lost at power down?

**Comment by Lucapz** [comment]
Fedora 31 , I edited grub and replaced rhgb quiet with systemd.volatile=overlay and then ran grub2-mkconfig -o /boot/grub2/grub.cfg to rebuild the grub.

It didn't work so i'm guessing i've done this wrong , can anyone help?
