### ISSUE TITLE
Signal Trap Handler / Filter

### ISSUE THREAD

**Issue by b1tninja** [systemd/systemd#13873]
Currently there is no directive to configure a trap handler actions / conditions. In some instances I would like a service to ignore specific signals.

The ability to define actions / conditions similar to "trap" built-in of bash/sh, or a way to mask / filter specific signals. 

The alternative is to create a wrapper script that invokes trap and then runs the child process, which isn't ideal.

My specific use case is needing a work-around for libvirtd killing VMs with SIGTERM becuase of changes to USB devices... but I imagine other people may benefit from a generic feature

**Comment by poettering** [comment]
not sure i follow?

how a daemon handles signals or not is really up to the daemons themselves, and we can't hook into that, except if we'd use ptrace() and become a debugger of them, but that sounds like a pretty bad idea?

Hence, what precisely are you trying to do?

**Comment by b1tninja** [comment]
I guess the masked / ignored signals at least carry over... But maybe the
custom handlers is not practical

**Comment by b1tninja** [comment]
Yeah it's certainly not ideal, I think eventually SIGKILL does the trick, my use case isn't the greatest but I thought it could be worthwhile feature for other scenarios.

My need for this is a workaround for a bug in libvirt, see: https://bugzilla.redhat.com/show_bug.cgi?id=1758032

**Comment by poettering** [comment]
Sorry, but I don't think blocking SIGTERM wholesale is really a good idea. It just shifts the issue and breaks something else. Moreover most likely the daemon might reset the handler/mask for the signal anyway, making our setting without effect.

Hence, let's close this. I hope that is OK?
