### ISSUE TITLE
Running integration tests on host with encrypted root fs fails

### ISSUE THREAD

**Issue by lmb** [systemd/systemd#13883]
**systemd version the issue has been seen with**

`master`

**Used distribution**

Ubuntu 19.04

**Expected behaviour you didn't see**

Running the integration tests works out of the box using `sudo make -C test/TEST-04-JOURNAL clean setup run`

**Unexpected behaviour you saw**

The test hangs when trying to bring up the system:

```
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... cryptsetup: Waiting for encrypted source device
    UUID=85d2af0f-...
```

The UUID is from my laptop:

```
$ cat /etc/crypttab
nvme0n1p3_crypt UUID=85d2af0f-... none luks,discard
```

This can be fixed by adding `cryptops=` to KERNEL_APPEND:

```
sudo make -C test/TEST-04-JOURNAL KERNEL_APPEND="cryptopts=" clean setup run
```

**Comment by mrc0mmand** [comment]
Should be addressed by 14e0259b499c188de09040f2e5857a0193094d5a.
