### ISSUE TITLE
Problem with bootloader entries

### ISSUE THREAD

**Issue by PiccoliPaolo93** [systemd/systemd#13893]
**Is your feature request related to a problem? Please describe.**

My laptop (Asus GL753VD) need the line acpi -e in the row before the kernel specification in the bootloader. I can't find how to set this function. In Fedora 29 I had grub2 and I modified the grub config files. Now, in Fedora 30, I have bootloaderspec and I don't know how to set it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by poettering** [comment]
Sorry, but Fedora implements a weird form of the boot loader spec, not the upstream one. Please contact the Fedora maintainers about this instead.
