### ISSUE TITLE
systemd-networkd allows multiple default gateways on the system

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#13907]
I can see that current systemd-networkd allows multiple default gateway support.
Suppose if my network file as below, It adds two default routes in the routing table.

[Match]
Name=eth0
[Link]
MACAddress=xx:xx:xx:xx:xx:xx
[Network]
DHCP=false
[Address]
Address=10.10.10.2/24
[Route]
Gateway=10.10.10.1
[Route]
Gateway=10.10.10.3

Output of routing table.

```Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.10.10.1       0.0.0.0         UG    0      0        0 eth0
default         10.10.10.3      0.0.0.0         UG    0      0        0 eth0
```
My assumption is when kernel starts parsing the routing table then it gets the first route whose destination network is (0.0.0.0) which is considered as the default gateway and stops processing the further routing table.

If it is true then why systemd-networkd is allowing multiple default gateways.

@ssahani @yuwata ^^^^^

**Comment by ratagupt** [comment]
@yuwata @ssahani : Is it a bug that systemd-networkd allows multiple default gateways?

**Comment by ssahani** [comment]
hmm can you explain why you think this is a bug and kernel is allowing this ?

**Comment by ratagupt** [comment]
@ssahani I was thinking that once the destination network gets a match in the routing table, other routes will not be parsed.
My understanding if we want multiple default gateways then we can achieve it through policy based routing(source routing) where we can create one more policy routing table.

**Comment by ratagupt** [comment]
Any update please ^^^

**Comment by ratagupt** [comment]
@ssahani @yuwata : Can we close on this? If it is not a valid question/query we can close on this, just looking for your reply.

**Comment by yuwata** [comment]
`ip` command and kernel support that, as already commented by @ssahani. So, there is no reason that `networkd` prohibit that. Closing.
