### ISSUE TITLE
IPv6MTUBytes is applied too early, its setting isn't always retained by the interface

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#13914]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > value in IPv6MTUBytes is applied to corresponding interface

**Unexpected behaviour you saw**
 > ipv6 mtu value matches device mtu value

**Steps to reproduce the problem**

The ipv6 mtu is set fairly early in link processing, but after networkd sets its value, its value can be lost, because the kernel will reset the interface ipv6 mtu back to the device mtu anytime the interface is brought up (NETDEV_UP event in the kernel) or anytime the device mtu is changed (NETDEV_CHANGEMTU event).

This results in the ipv6 mtu being equal to the device mtu, instead of the IPv6MTUBytes configured value, if:

- an MTUBytes value is specified, that is different from the interface's current device MTU
- the interface is not in UP state when the ipv6 mtu is set

additionally at runtime, if the link is administratively brought down for any reason, when it's brought back up the ipv6 mtu will be reset to the device mtu (although the device mtu persists across down/up).

> $ cat /etc/systemd/network/10-ens3.network 
> [Match]
> Name=ens3
> 
> [Link]
> MTUBytes=1600
> 
> [Network]
> DHCP=ipv4
> LinkLocalAddressing=ipv6
> IPv6MTUBytes=1350
> 
> [DHCP]
> UseMTU=no
> 

at boot:

> root@lp1671951:~# ip l show ens3
> 2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1600 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
>     link/ether 52:54:00:8f:1d:6a brd ff:ff:ff:ff:ff:ff
> root@lp1671951:~# grep . /proc/sys/net/ipv6/conf/ens3/mtu 
> 1600
> 

restarting networkd will correct the ipv6 mtu, since the device mtu doesn't need changing and the link is already up:

> root@lp1671951:~# systemctl restart systemd-networkd
> root@lp1671951:~# ip l show ens3
> 2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1600 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
>     link/ether 52:54:00:8f:1d:6a brd ff:ff:ff:ff:ff:ff
> root@lp1671951:~# grep . /proc/sys/net/ipv6/conf/ens3/mtu 
> 1350
> 

(re)starting networkd if the interface is currently down will always reset the ipv6 mtu:

> root@lp1671951:~# ip l set down dev ens3
> root@lp1671951:~# ip l show ens3
> 2: ens3: <BROADCAST,MULTICAST> mtu 1600 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
>     link/ether 52:54:00:8f:1d:6a brd ff:ff:ff:ff:ff:ff
> root@lp1671951:~# grep . /proc/sys/net/ipv6/conf/ens3/mtu 
> 1350
> root@lp1671951:~# systemctl restart systemd-networkd
> root@lp1671951:~# ip l show ens3
> 2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1600 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
>     link/ether 52:54:00:8f:1d:6a brd ff:ff:ff:ff:ff:ff
> root@lp1671951:~# grep . /proc/sys/net/ipv6/conf/ens3/mtu 
> 1600
>

**Comment by ssahani** [comment]
Hmm why would the kernel will change this mtu value automatically?

**Comment by ddstreet** [comment]
> Hmm why would the kernel will change this mtu value automatically?

Well, the kernel won't change the device mtu, what it changes is the ipv6 mtu; but I think I'm misunderstanding what you are saying?

**Comment by ssahani** [comment]
I meant how the MTU is getting set ? Like how you triggered the MTU change event in the kernel.

**Comment by ddstreet** [comment]
@ssahani I'm pretty sure I'm misunderstanding what you're saying, but if you mean when (and why) did the kernel decide to reset the ipv6 mtu when the device mtu is set, I traced it all the way back to before the kernel changed over to git (2005):

NETDEV_CHANGEMTU:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/addrconf.c?id=1da177e4c3f4#n2024

NETDEV_UP:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/addrconf.c?id=1da177e4c3f4#n2010

I could try searching back before that to find why it's being reset, but if it's been this way for over 15 years I'm pretty sure the kernel probably won't think about changing now.

**Comment by ssahani** [comment]
I am trying to reproduce this  . Here is my conf

```
➜  network cat 99-eth2.network
[Match]
Name=eth2

[Link]
MTUBytes=1600

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6
```

1. Before starting networkd
```
❯ networkctl status eth2                                                                                                                                                                   ─╯
● 4: eth2                                                                                             
             Link File: /usr/lib/systemd/network/10-ens39.link                                        
          Network File: /usr/lib/systemd/network/99-eth2.network                                      
                  Type: ether                                                                         
                 State: routable (configured)                               
                  Path: pci-0000:02:06.0                                                              
                Driver: e1000                                                                         
                Vendor: Intel Corporation                                                             
                 Model: 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)
            HW Address: 00:0c:29:3a:bc:7e (VMware, Inc.)                                              
                   MTU: 1500 (min: 46, max: 16110)           <========                                         
  Queue Length (Tx/Rx): 1/1                                                                           
      Auto negotiation: yes                                                                           
                 Speed: 1Gbps                                                                         
                Duplex: full                                                                          
                  Port: tp                                                                            
               Address: 192.168.94.135                                                                
                        fe80::20c:29ff:fe3a:bc7e                                                      
               Gateway: 192.168.94.2 (VMware, Inc.)                                                   
                   DNS: 192.168.94.2   
```

2. I restarted networkd

```
❯ networkctl status eth2                                                                                                                                                                   ─╯
● 4: eth2                                                                                             
             Link File: /usr/lib/systemd/network/10-ens39.link                                        
          Network File: /usr/lib/systemd/network/99-eth2.network                                      
                  Type: ether                                                                         
                 State: routable (configuring)                        
                  Path: pci-0000:02:06.0                                                              
                Driver: e1000                                                                         
                Vendor: Intel Corporation                                                             
                 Model: 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)
            HW Address: 00:0c:29:3a:bc:7e (VMware, Inc.)                                              
                   MTU: 1600 (min: 46, max: 16110)                    <========                                
  Queue Length (Tx/Rx): 1/1                                                                           
      Auto negotiation: yes                                                                           
                 Speed: 1Gbps                                                                         
                Duplex: full                                                                          
                  Port: tp                                                                            
               Address: 192.168.94.135                                                                
                        fe80::20c:29ff:fe3a:bc7e                                                      
               Gateway: 192.168.94.2                                                                  
                   DNS: 192.168.94.2
```

Then I brought down the interface
```
❯ sudo ip link set dev eth2 down

❯ networkctl status eth2                                                                                                                                                                   ─╯
● 4: eth2                                                                                             
             Link File: /usr/lib/systemd/network/10-ens39.link                                        
          Network File: /usr/lib/systemd/network/99-eth2.network                                      
                  Type: ether                                                                         
                 State: off (configured)                                                 
                  Path: pci-0000:02:06.0                                                              
                Driver: e1000                                                                         
                Vendor: Intel Corporation                                                             
                 Model: 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)
            HW Address: 00:0c:29:3a:bc:7e (VMware, Inc.)                                              
                   MTU: 1600 (min: 46, max: 16110)      <===========                                              
  Queue Length (Tx/Rx): 1/1                                                                           
      Auto negotiation: yes                                                                           
                 Speed: 1Gbps                                                                         
                Duplex: full                                                                          
                  Port: tp  
```

then I brought up
```
❯ sudo ip link set dev eth2 up

❯ networkctl status eth2                                                                                                                                                                   ─╯
● 4: eth2                                                                                             
             Link File: /usr/lib/systemd/network/10-ens39.link                                        
          Network File: /usr/lib/systemd/network/99-eth2.network                                      
                  Type: ether                                                                         
                 State: routable (configured)                               
                  Path: pci-0000:02:06.0                                                              
                Driver: e1000                                                                         
                Vendor: Intel Corporation                                                             
                 Model: 82545EM Gigabit Ethernet Controller (Copper) (PRO/1000 MT Single Port Adapter)
            HW Address: 00:0c:29:3a:bc:7e (VMware, Inc.)                                              
                   MTU: 1600 (min: 46, max: 16110)        <==========                                            
  Queue Length (Tx/Rx): 1/1                                                                           
      Auto negotiation: yes                                                                           
                 Speed: 1Gbps                                                                         
                Duplex: full                                                                          
                  Port: tp                                                                            
               Address: 192.168.94.135                                                                
                        fe80::20c:29ff:fe3a:bc7e                                                      
               Gateway: 192.168.94.2                                                                  
                   DNS: 192.168.94.2  
```

The MTU is still `1600`. I am not sure . Am I missing something. Please provide the steps so that I can reproduce it.

But if I try to set it via ip command then it sets to 1500. But If restart networkd again it gets set 10 1600.
```
sudo ip link set dev eth2 mtu 1500

❯ ip -d link show eth2                                                                                                                                                                     ─╯
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000

**Comment by ddstreet** [comment]
> The MTU is still 1600. I am not sure . Am I missing something. Please provide the steps so that I can reproduce it.

The MTU is correctly handled; it's the ipv6-specific MTU that is not.  The ipv6 mtu isn't shown in the networkctl status output, you have to check its sysctl node:

> $ cat /etc/systemd/network/10-ens3.network 
> [Match]
> Name=ens3
> 
> [Link]
> MTUBytes=1400
> 
> [Network]
> DHCP=ipv4
> LinkLocalAddressing=ipv6
> IPv6MTUBytes=1300
> 
> [DHCP]
> UseMTU=no
> 

> $ networkctl status ens3
> ● 2: ens3                                                              
>              Link File: /lib/systemd/network/99-default.link           
>           Network File: /etc/systemd/network/10-ens3.network           
>                   Type: ether                                          
>                  State: routable (configured)
>                   Path: pci-0000:00:03.0                               
>                 Driver: virtio_net                                     
>                 Vendor: Red Hat, Inc.                                  
>                  Model: Virtio network device                          
>             HW Address: 52:54:00:8f:1d:6a                              
>                    MTU: 1400                                           
>   Queue Length (Tx/Rx): 1/1                                            
>       Auto negotiation: no                                             
>                  Speed: n/a                                            
>                Address: 192.168.122.20 (DHCP4)                         
>                         fe80::5054:ff:fe8f:1d6a                        
>                Gateway: 192.168.122.1                                  
>                    DNS: 192.168.122.1                       
> 

> $ cat /proc/sys/net/ipv6/conf/ens3/mtu
> 1300

or

> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1300


above is when the system has correct values.  To reproduce this problem, you should see the wrong ipv6 mtu at boot:

> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1400
> 

or, you can reproduce just by taking down the interface and (re)starting networkd:

> $ sudo sysctl -w net.ipv6.conf.ens3.mtu=1300
> net.ipv6.conf.ens3.mtu = 1300
> $ sudo ip l set down dev ens3
> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1300
> $ sudo systemctl restart systemd-networkd
> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1400

or, leave the interface up, but make sure the networkd configured device mtu is different (i.e. to force networkd to actually change the device mtu):

> $ sudo sysctl -w net.ipv6.conf.ens3.mtu=1300
> net.ipv6.conf.ens3.mtu = 1300
> $ sudo ip l set mtu 1700 dev ens3
> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1700
> $ sudo systemctl restart systemd-networkd
> $ sysctl net.ipv6.conf.ens3.mtu
> net.ipv6.conf.ens3.mtu = 1400
> 

notice also that the ipv6 mtu is reset immediately anytime the device mtu is changed.

**Comment by ssahani** [comment]
Sorry for the dealy . I figure there are some complexities here. I need sometime to figure how the kernel works. 

It's not simple like `NETDEV_CHANGEMTU` but also https://elixir.bootlin.com/linux/latest/source/net/ipv6/addrconf.c#L3607
```
                        /*
                         * If the MTU changed during the interface down,
                         * when the interface up, the changed MTU must be
                         * reflected in the idev as well as routers.
                         */
                        if (idev->cnf.mtu6 != dev->mtu &&
                            dev->mtu >= IPV6_MIN_MTU) {
                                rt6_mtu_change(dev, dev->mtu);
                                idev->cnf.mtu6 = dev->mtu;
                        }
```

**Comment by ddstreet** [comment]
> Sorry for the dealy . I figure there are some complexities here. I need sometime to figure how the kernel works.
> 
> It's not simple like `NETDEV_CHANGEMTU` but also https://elixir.bootlin.com/linux/latest/source/net/ipv6/addrconf.c#L3607

right, it's NETDEV_UP and NETDEV_CHANGEMTU, which are the 2 cases handled by #13915
