### ISSUE TITLE
nspawn: UNIFIED_CGROUP_HIERARCHY warning is printed to stdout

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#13919]
**systemd version the issue has been seen with**
> daily from 20191030 (be75c86)

**Used distribution**
 > CentOS 7

**Expected behaviour you didn't see**
 > the warning is printed to stderr

**Unexpected behaviour you saw**
 > the warning is printed to stdout

**Steps to reproduce the problem**
https://github.com/systemd/systemd/commit/c78c095b1e6c87f309bbae5166f94d1bedc4ce81 renamed UNIFIED_CGROUP_HIERARCHY to SYSTEMD_NSPAWN_UNIFIED_HIERARCHY for systemd-nspawn, and introduced a warning when the old variable is used. The warning is printed on stdout, which breaks anything that might be parsing the output of nspawn in a not too robust way. In turn, this will make deploying 244 a bit annoying, as one has to either code up an exception in the parsing, or set the right variable depending on the version of systemd. Options:
- print the warning, but print it to stderr
- do not print the warning if both variables are set
- add an option to silence the warning

**Comment by davide125** [comment]
cc @flpdnc

**Comment by keszybz** [comment]
> The warning is printed on stdout

It uses log_info, which prints to stderr normally. Are you sure it lands in stdout?

> do not print the warning if both variables are set

It is not printed if both are set.

> add an option to silence the warning

Setting the new variable is enough.

**Comment by davide125** [comment]
Uh, I definitely tested it with both variables set and it was still printing, but that was within our larger container build infra thing, so it's possible there was something else going on. Will try to get a minimal repro of this and report back.

**Comment by poettering** [comment]
> > 
> 
> It uses log_info, which prints to stderr normally. Are you sure it lands in stdout?

educated guess: if the child logs, we read that via the container's pty and everything written to the container's pty ends up on stdout. i.e. ttys don't distuingish between stdout/stderr, and hence both gets converted to stdout if it happens in the payload, and the pre-exec pid1 is considered payload starting at a certain point...
