### ISSUE TITLE
Criteria for creating user journals are unclear

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#13926]
The documentation for `systemd-journald` [states](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Access%20Control):

> By default, each logged in user will get their own set of journal files in /var/log/journal/.

And the documentation for `journald.conf` [states](https://www.freedesktop.org/software/systemd/man/journald.conf.html#SplitMode=):

> SplitMode=
> Controls whether to split up journal files per user, either "uid" or "none". [...] If "uid", all regular users will each get their own journal files, and system users will log to the system journal.

It is not clear at all what constitutes a "user" in this context.

The first quote uses the term "logged in user", which makes it sound like a user who logs in through `login` or PAM or SSH or something. (It's not.) One could also guess it might be a user running systemd in per-user mode. (It's not.) Or maybe it's just any user. (It's not.)

To figure it out, one actually has to go to the [source code](https://github.com/systemd/systemd/blob/df957acc6603a04e62dee7e911c65dc7dbcb6208/src/journal/journald-server.c#L401) (which I found through an [oblique reference](https://wiki.archlinux.org/index.php/Systemd/User#Reading_the_journal) in the ArchLinux wiki). From there we can conclude that journald will create a per-user journal file **if the user's UID is outside of the ranges 0-1000 (system users), 61184–65519 (dynamic users), and 65534 (nobody)**.

It would be nice to have this documented, as I was really confused trying to figure out why there were journals for some users but not others, and I would not have suspected that it would be based on comparing the UID against "magic" values.

**Comment by poettering** [comment]
This actually is kinda documented here:

https://github.com/systemd/systemd/blob/master/docs/UIDS-GIDS.md

(In particular, see the table down at the end)

I guess we should link that up better though.
