### ISSUE TITLE
iproute2 supports MTU specifying per route which is lacked of in systemd

### ISSUE THREAD

**Issue by poige** [systemd/systemd#13929]
Being behind "cable modems" and similar equipment it's not rare to have uplink's MTU slightly less than 1500, which is not obvious because LAN uses default one instead. With iproute2 it's possible to plant this information into kernel routing table:

`sudo ip ro change 0.0.0.0/0 via …defaultGatewayIP… mtu 1492`

Using Ubuntu 18.04 with systemd 237 I found no way to specify a route's MTU with systemd's primitives though.

Setting it globally per interface itself isn't clean solution because internal LAN doesn't have such limitation, and only external route(s) should be adjusted accordingly. Moreover, lowering interface's MTU would require corresponding change on all internal devices otherwise they might have connectivity issues assuming use of default MTU all-LAN wide.

**Comment by poettering** [comment]
There's MTUBytes= in [Route] already.

**Comment by poige** [comment]
That's might be good except that it's not told which release has it fixed. Did I overlook it in 237, didn't it?

Also, how does it couple with `Gateway=` statement for e. g.?
