### ISSUE TITLE
Please, let's revert #13406

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#13933]
Please, let's just revert #13406, thus closing #13469.

The concept of honouring the order is a bad idea. usermode helper always was bad, and we ignored this succesfully for 7 years, not sure why we would "fix" this bad idea now.

Other distros hate this too, and are going to opt-out/revert locally too, and this is really really not worth diverting distros about.

Compat kludges might be OK to have if there's a clear perspective to remove them eventually. This one is just dead.

Let's kill this, please!

**Comment by keszybz** [comment]
OK. We can have a downstream patch in Fedora until the need fully goes away.

**Comment by keszybz** [comment]
I implemented #13469, which I think is nicer. I'll comment there.
