### ISSUE TITLE
export environment variables in a user service

### ISSUE THREAD

**Issue by johschmitz** [systemd/systemd#13931]
**Is your feature request related to a problem? Please describe.**
Apparently environment variables in a user service can not be exported.
Documentation is here:
http://0pointer.de/public/systemd-man/systemd.exec.html#Environment=
This is a big Problem for Python services which require an `"export PYTHONPATH=[...]"`.

**Describe the solution you'd like**
Something like
`Environment=" export PYTHONPATH=[...]"`
should be possible.

**Describe alternatives you've considered**
The only workaround that comes to my mind would be to use a wrapper shell script and export the variables inside that. Not a nice solution.

**Comment by poettering** [comment]
Al variables listed are "exported" unconditionally, if you so will. Note that systemd is not a shell, and "exporting" env vars is a shell concept. i.e. systemd has no internal env vars, hence all env vars you specify are exclusively exported.

Closing hence.

**Comment by johschmitz** [comment]
So is it expected behaviour that PYTHONPATH doesn't work or are you trying to say that I am doing something wrong?
