### ISSUE TITLE
Persistent naming not working properly for iwlwifi

### ISSUE THREAD

**Issue by grazzolini** [systemd/systemd#13948]
**systemd version the issue has been seen with**
> 243.78-2-arch

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Usually wireless devices get renamed to something like wlp2s0. This is not working with iwlwifi devices. Did not test with other wireless devices.

**Unexpected behaviour you saw**
 > The system boots with old naming scheme, ie, like wlan0.

**Steps to reproduce the problem**

Running the current systemd version on Arch Linux this is easily reproducible by simply booting the system. Refer to downstream bug [report](https://bugs.archlinux.org/task/64393) as well, for more information.

**Comment by mbiebl** [comment]
Are you using iwd? If so, which version?

**Comment by grazzolini** [comment]
@mbiebl I'm using iwd 1.0. But, to make sure this behavior was not from any network managing software, I have disabled all of them on boot. I still get a wlan0 card, not wlp2s0. I have, however, determined that there's a separate issue when including the wireless drivers from the initramfs. Which isn't done by default.

The tests I've done do not have any wireless module on the initramfs itself.

**Comment by mbiebl** [comment]
@grazzolini iwd 1.0 installs a file /lib/systemd/network/80-iwd.link which disables the persistent interface naming for wlan devices.
It's irrelevant if iwd is enabled or not.

**Comment by grazzolini** [comment]
@mbiebl Yes, I have noticed this after posting a comment on our downstream bug report. I'm closing this and I'm going to deal with this downstream. Thanks for the help.
