### ISSUE TITLE
Please support on-the-fly compression of core dumps

### ISSUE THREAD

**Issue by wferi** [systemd/systemd#13968]
Some runtimes and libraries allocate a huge address space on startup, even if they use only a small fraction of it later. Dumping core of such applications is unnecessarily resource intensive, because even though such core files compress very well with little effort, systemd-coredump first writes the uncompressed image to be able to log the backtrace (I guess), and only then compresses the file. This requires great temporarily filesystem capacity and entails much wasted I/O. I think this automatic analysis is rather superficial and the admin either won't care or will have to redo it anyway in most of the cases. On another system, because the necessary software and resources may not even be available on the problem system. Unless the capacity requirement denied the creation of the core file to start with... even the default 2 GB may not be available on some systems, but the compressed core would fit easily.

I'd like to have the option of forgoing this automatic backtrace generation and any other analysis in exchange of on-the-fly core compression. This would also speed up dumping considerably by not writing the uncompressed data (which is removed short after anyway).

Otherwise I'll have to resort to using a home-grown compression script as my `core_pattern`, resulting in unnecessary non-uniformity amongst our servers.

**Comment by poettering** [comment]
hmm, if this is desirable it should probably have an automatism that we first try to write and process it like we now do, but if we notice it grows too large while doing so, we switch to off processing, compress what we already have and then write the rest only compressed. i.e. be nice when we can, and if we can't then handle that too. Would be one more size threshold to configure in coredump.conf.

**Comment by nolange** [comment]
I am tinkering with coredump these days. Turns out you can get ridiculous savings when writing sparse files (1.2GB vs 60MB uncompressed). Should be rather easy to do.

**Comment by bluca** [comment]
I am working on this. First part is a fix for the LZ4 compressor: https://github.com/systemd/systemd/pull/18941
Once that is merged after 248 is out, I'll follow-up with this which changes core handling to first use the STDIN FD to stream compress, and then if possible decompress+load for backtrace generation: https://github.com/bluca/systemd/commits/coredump_compress_on_the_fly
