### ISSUE TITLE
[networkd] Add "Label" options for DHCP and LinkLocal addresses

### ISSUE THREAD

**Issue by nahuel** [systemd/systemd#13967]
Using `networkd` you currently you can assign an `ip addr` label strings to each static address, for example in `/etc/systemd/networkd/eth0.network`:

```ini
[Network]
LinkLocalAddressing=yes
DHCP=ipv4

[Address]
Address=192.168.1.1/24
Label=eth0:lan
```

But the IP aaddresses assigned by DHCP or by IPV4LL will not have a label string. So I propose to add two new `[Network]/LabelLinkLocal` and `[DHCP]/Label` parameters:

```ini
[Network]
LinkLocalAddressing=yes
DHCP=ipv4
LabelLinkLocal=eth0:local

[DHCPv4]
Label=eth0:dhcp

[Address]
Address=192.168.1.1/24
Label=eth0:lan
```

**Comment by poettering** [comment]
hmm, shouldn't we rather set a fixed label? I am not convinced this needs to be configurable?

**Comment by tchernomax** [comment]
@poettering 

> shouldn't we rather set a fixed label? I am not convinced this needs to be configurable?
It can be useful when you have multiple interfaces and you want to assign a name/label to each ip without renaming the interfaces.

For example : adm, front, back

As it would be useful to me, I think it should be configurable :)
