### ISSUE TITLE
Adding an `OnRestart` for  [Unit] section

### ISSUE THREAD

**Issue by sbernard31** [systemd/systemd#13966]
I would like to be notified when a given service A restart because of failure.
My service A `Restart` `on-failure` rarely but I want to be notified each time it restart to look at the log and try to understand what happened.

I tried to achieve this by creating a new service B (notifier) which will be executed `onFailure` of service A. But I finally understand that this is only called after all restart retry. (see #8398) 

I suppose I can achieve this will something like `ExecStopPost` in addition of `$EXIT_STATUS` (like explained in https://github.com/systemd/systemd/issues/8398#issuecomment-418244338)

But a new `onRestart` entry in unit section would be more straightforward and elegant.
(as requested  at https://github.com/systemd/systemd/issues/8398#issuecomment-418139080)

**Comment by sbernard31** [comment]
I just saw that this is pretty much the same request as #13517

**Comment by anitazha** [comment]
Closing as duplicate. Please continue conversation on the other issue.
