### ISSUE TITLE
v243 breaks lvremove of snapshots

### ISSUE THREAD

**Issue by protegh** [systemd/systemd#13976]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
```
# lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql
  Logical volume "mysql_snapshot" created.
# lvremove -f /dev/SQL/mysql_snapshot 
  Logical volume "mysql_snapshot" successfully removed
```

**Unexpected behaviour you saw**
```
# lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql
  Logical volume "mysql_snapshot" created.
# lvremove -f /dev/SQL/mysql_snapshot
```
Here the lvremove hangs and I have to "kill -9" it. Oddly enough a second lvremove then is "successful":
```
# lvremove -f /dev/SQL/mysql_snapshot 
  WARNING: Reading VG SQL from disk because lvmetad metadata is invalid.
  Logical volume "mysql_snapshot" successfully removed
```

**Steps to reproduce the problem**
1. Create a volume group, say SQL.
2. `lvcreate -L 5G -n mysql SQL`
3. `mkfs.ext4 /dev/SQL/mysql`
4. `lvcreate -s --size=5116M --name=mysql_snapshot /dev/SQL/mysql`
5. `lvremove -f /dev/SQL/mysql_snapshot`
6. As this lvremove does not terminate, `kill -9` it.
7. `lvremove -f /dev/SQL/mysql_snapshot`
  `WARNING: Reading VG RAID from disk because lvmetad metadata is invalid.
  Logical volume "mysql_snapshot" successfully removed`

**Workaround**
Downgrade to systemd-242.

**Comment by poettering** [comment]
Please contact the LVM people about this. We don't know LVM. They'll help you and then report any issue they find back to us. Thank you!

**Comment by protegh** [comment]
Maybe the underlying "bug" is in the lvm code, but then the changes (probably in the udev code) from systemd-242 to -243 trigger it, as I didn't change anything in the lvm software on the affected host.

Investigating it further I found following lines in the journal just at the time of the lvremove stall:
```
systemd-udevd[2097]: dm-3: Failed to process device, ignoring: No such file or directory
systemd-udevd[2096]: dm-4: Failed to process device, ignoring: No such file or directory
```
On starting the systemd-udevd also states that it is
```
Using default interface naming scheme 'v243'.
```

**Comment by mbiebl** [comment]
@protegh If you are familiar with git, you could try to run a `git bisect` to identify the change in systemd which triggered this issue?

**Comment by yuwata** [comment]
Please test #13984.

**Comment by protegh** [comment]
> Please test PR #13984.

This fixed it. Thanks!
