### ISSUE TITLE
Ubuntu CI: TEST-25-IMPORT intermittently fails

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#13973]
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Ubuntu CI

**Expected behaviour you didn't see**
 > TEST-25 pass

**Unexpected behaviour you saw**
 > TEST-25 intermittently fails

In the logs, the failure usually looks like:

>          Starting Testsuite service...
> [  OK  ] Started /etc/rc.local Compatibility.
> [  OK  ] Started Permit User Sessions.
> + set -o pipefail
> + export SYSTEMD_PAGER=cat
> + SYSTEMD_PAGER=cat
> + dd if=/dev/urandom of=/var/tmp/testimage.raw bs=1048583 count=5
> ^M5+0 records in
> 5+0 records out
> 5242915 bytes (5.2 MB, 5.0 MiB) copied, 1.50478 s, 3.5 MB/s
> + machinectl import-raw /var/tmp/testimage.raw
> [  OK  ] Started D-Bus System Message Bus.
>          Starting Virtual Machine a… Container Download Service...
> [  OK  ] Found device /dev/hvc0.
> [  OK  ] Started Login Service.
> [  OK  ] Started Serial Getty on hvc0.
> [  OK  ] Reached target Login Prompts.
> [  OK  ] Reached target Multi-User System.
>          Starting Update UTMP about System Runlevel Changes...
> [  OK  ] Listening on Load/Save RF …itch Status /dev/rfkill Watch.
> Failed to transfer image: Connection timed out
> [FAILED] Failed to start Testsuite service.
> See 'systemctl status testsuite.service' for details.
> 

It's unclear why the image transfer times out.

Example logs:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-ddstreet-systemd-blacklist-debian/bionic/ppc64el/s/systemd/20191014_205058_d7b34@/log.gz
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-ddstreet-systemd-blacklist-debian/bionic/ppc64el/s/systemd/20191014_214142_d7b34@/log.gz

this log is slightly different:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-ddstreet-systemd-blacklist-debian/bionic/ppc64el/s/systemd/20191014_234519_d7b34@/log.gz

Failing with this instead:

> + machinectl import-raw /var/tmp/testimage.raw
> Started [0;1;39mD-Bus System Message Bus[0m.
> Starting [0;1;39mVirtual Machine a… Container Download Service[0m...
> Found device [0;1;39m/dev/hvc0[0m.
> Enqueued transfer job 1. Press C-c to continue download in background.
> Failed to start [0;1;39mTestsuite service[0m.
> See 'systemctl status testsuite.service' for details.
>

**Comment by ddstreet** [comment]
TEST-25 has been blacklisted in Ubuntu CI, so this bug is just to track debugging and fixing the test and/or Ubuntu CI so the test can be un-blacklisted.

**Comment by keszybz** [comment]
Oh, it's being tracked in https://github.com/systemd/systemd/issues/30250. Frantisek is ahead as usual.

**Comment by keszybz** [comment]
Anyway, is this still an issue? This report is four years old at this point, so it's likely that any issues have been fixed in the meantime.
