### ISSUE TITLE
root mount unit has cyclic After=systemd-journald.socket dependency

### ISSUE THREAD

**Issue by HiassofT** [systemd/systemd#13978]
**systemd version the issue has been seen with**
>241, 243 master (commit  7fd7dab90f)

**Used distribution**
 > Debian Buster (v241), LibreELEC (243, master)

**Expected behaviour you didn't see**
 >root mount unit only depends on system.slice

**Unexpected behaviour you saw**
 >root mount has After dependency on systemd-journald.socket

**Steps to reproduce the problem**

Boot the system, run `systemctl show -pAfter -- -.mount`

Systemd up to 239 outputs
```
# systemctl show -pAfter -- -.mount
After=system.slice 
```

with version 241 and up the output is
```
# systemctl show -pAfter -- -.mount
After=system.slice systemd-journald.socket
```

The cyclic dependency is not only odd, it seems to also trigger processing of the load queue before initial enumeration has finished (as the perpetual root mount exists,  mount_setup_existing_unit is called during mountinfo enumeration which leads to manager_dispatch_load_queue being called via mount_add_extras->unit_add_exec_dependencies->unit_add_dependency_by_name->manager_load_unit) which is a bit unexpected too (and may be a bug).

Bisecting identified commit a37422045f "mount: regenerate all deps whenever a mount's parameters changes" as the first bad one but it seems to me that the change just revealed an issue from 11222d0fe0 "core: make the root mount perpetual too" (or maybe even before that).

Setting std_output and std_error to EXEC_OUTPUT_NULL in mount_enumerate_perpetual prevents the issue from happening, mount_add_extras then won't add the journald socket dependency
```
--- a/src/core/mount.c
+++ b/src/core/mount.c
@@ -1717,6 +1717,11 @@ static void mount_enumerate_perpetual(Manager *m) {
         }
 
         u->perpetual = true;
+
+        /* The stdio/kmsg bridge socket is on /, in order to avoid a dep loop, don't use kmsg logging for -.mount */
+        MOUNT(u)->exec_context.std_output = EXEC_OUTPUT_NULL;
+        MOUNT(u)->exec_context.std_error = EXEC_OUTPUT_NULL;
+
         MOUNT(u)->deserialized_state = MOUNT_MOUNTED;
 
         unit_add_to_load_queue(u);
```

Maybe `u->default_dependencies = false;` should be added there as well, also mount_load_root_mount seems to miss setting std_error.

**Comment by poettering** [comment]
fix in #14040
