### ISSUE TITLE
udev ATTR command fails to write snd_hda_intel id attribute

### ISSUE THREAD

**Issue by aw32** [systemd/systemd#13985]
systemd version 243.78
Arch Linux

Background: On my system there are 2 sound devices using the same module (snd_hda_intel). The original problem is, that the recognition order of the devices is unstable, which results in unstable ALSA device names. I tried overwriting the device ids using udev rules (as described here https://alsa-project.org/wiki/Changing_card_IDs_with_udev and here https://alsa.opensrc.org/Udev#Writing_udev_rules).

Expected behavior:
Using the ATTR command in udev rules should write the specified string to the attribute.
DEVPATH=="/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card?", ATTR{id}="HDMI"

Unexpected behaviour you saw:
Using the ATTR command fails with the following debug log entries:

Nov 09 20:07:18 hostname systemd-udevd[331]: card0: /etc/udev/rules.d/97-alsa.rules:8 ATTR '/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card0/id' writing 'HDMI'
Nov 09 20:07:18 hostname systemd-udevd[331]: card0: /etc/udev/rules.d/97-alsa.rules:8 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card0/id}, ignoring: Invalid argument

Using the RUN command and a bash/echo command succeeds.
Using echo without the parameter "-n" also results in the "Invalid argument" error.

Steps to reproduce the problem:
Use the specified rule to change the id of your snd_hda_intel sound device.

By taking a short look at the udev code, my guess is, that the ATTR command might try to add a newline to the string, which seems not to be allowed for the id attribute. However, I don't know how to test this assumption.

**Comment by yuwata** [comment]
Fix is waiting in #13987. If possible, please test the PR.

**Comment by aw32** [comment]
I tested the commit and it works for my use case. Thanks.

**Comment by yuwata** [comment]
Thank you for testing.

This issue was introduced by 25de7aa7b90c23d33ea50ada1e50c5834a414237 (v243).
