### ISSUE TITLE
bogus "Process .. as been marked to be excluded from killing" warning from systemd-shutdown

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#13981]
This is copied verbatim from the downstream bug report at 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935471

Package: systemd
Version: 241-5
Severity: minor

Dear Maintainer,

on one of my systems, debian runs from a filesystem image loop-mounted
from an ntfs volume using ntfs-3g, and thus, the ntfs-3g process must be
running at all times, before mounting the root fs and during shutdown.

To accomplish this I have an initramfs-tools script that runs it something
like this:

  exec -a @ntfs-3g-root ntfs-3g ...

The @ prevents systemd-shutdown from killing it, which works. However, it
outputs the following warning (lifted from the code, can't copy&paste from
the real system):

                log_notice("Process " PID_FMT " (%s) has been marked to be excluded from killing. It is "
                           "running from the root file system, and thus likely to block re-mounting of the "
                           "root file system to read-only. Please consider moving it into an initrd file "
                           "system instead.", pid, strna(comm));

Since it is running from the initramfs, this warning is bogus (and indeed,
the root fs can be mounted ro with no problem), suggesting that the check
systemd-shutdown uses to detect this case is broken.

For additional reference, `/proc/<ntfs-3g-pid>/root` has a target of "/",
which probably causes this. `/proc/<ntfs-3g-pid>/exe` has a target of
'/usr/bin/ntfs-3g (deleted)', which makes sense as it was deleted when
cleaning up the initramfs before handing over to the actual root fs.

**Comment by poettering** [comment]
so, the targets of those pseudo-symlinks are misleading. These symlinks are "magic" if you so will, only if you actually use them in paths they have a magic effect, and point to something potentially different than their literal value. Hence, can you do stat on those two magic symlinks to see what they actually point to?

**Comment by mbiebl** [comment]
I've forwarded your question to the original bug reporter

**Comment by poettering** [comment]
hmm, playing proxy? I am sorry!

anyway, we need the /usr/bin/stat data, please ask him again of /proc/$PID/root and /proc/$PID/exe

**Comment by poettering** [comment]
hmm, reading through the bug report, the reporter appears to uncooperative, and not willing to help debug this, which makes me want to just close this... 

We really need that stat() data via those symlinks to see why the test doesn#t work for him. i.e. we compare st_dev + st_ino of those two magic symlinks and hence need to know what they say... Anyway, can you ask him to provide that? If not, let#s just close this...

**Comment by mbiebl** [comment]
Agreed
