### ISSUE TITLE
shutdown noisy if /proc/swaps doesn't exist

### ISSUE THREAD

**Issue by Sid-OS** [systemd/systemd#13993]
**systemd version the issue has been seen with**
>243

**Used distribution**
 > Debian Sid with Xfce 4.14
Kernel 5.3.10

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > Since version 243 I see these two messages at reboot or poweroff for about 1 second:
systemd-shutdown: Failed to parse (null): No such file or directory
systemd-shutdown: Failed to deactivate swaps: No such file or directory
Then the system is terminated without errors. 
I don't have a swap on this system.
These messages do not appear in version 242.
Is this an error or just an info?

**Steps to reproduce the problem**
always reboot or poweroff

**Comment by poettering** [comment]
Fix in #14043

**Comment by joewh** [comment]
I saw the same issue in version 239 just today
