### ISSUE TITLE
Failed to read time with suspend-then-hibernate fails

### ISSUE THREAD

**Issue by MinnML** [systemd/systemd#13999]
**systemd version the issue has been seen with**
> 237

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 >Running suspend-then-hibernate service should put the machine into sleep mode and then hibernate after the delay set in the sleep.conf file.

**Unexpected behaviour you saw**
 >suspend-then-hibernate fails. The status shows:
````
systemd[1]: Starting Suspend; Idle into hibernate...
systemd-sleep[13130]: Failed to read time: -9
systemd[1]: systemd-suspend-then-hibernate.service: Main process exited, code
systemd[1]: systemd-suspend-then-hibernate.service: Failed with result 'exit-
systemd[1]: Failed to start Suspend; Idle into hibernate.
````
Both suspend and hibernate services work fine. 

**Steps to reproduce the problem**
Running `sudo systemctl suspend-then-hibernate` generates the error.

**Comment by keszybz** [comment]
Please report this bug in the distro bug tracker. Version 237 is "ancient" by upstream standards, and we don't use this interface at all now (see 1bbbefe7a68059eb55d864c3e0e670d00269683a). Thanks for understanding.
