### ISSUE TITLE
nspawn: Capability=CAP_NET_ADMIN without effect

### ISSUE THREAD

**Issue by myrkr** [systemd/systemd#13995]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > none

**Expected behaviour you didn't see**
 > The container has the CAP_NET_ADMIN capability available

**Unexpected behaviour you saw**
 > Program within the container with file-based posix capability net_admin fails to start

**Steps to reproduce the problem**

When trying to update from version v241 to v243 I noticed a regression in the capability handling.

The systemd unit specifies:

[Unit]
Requires=net-ns@black.service
After=net-ns@black.service
JoinsNamespaceOf=net-ns@black.service

[Service]
Type=simple
ExecStart=/bin/systemd-nspawn --machine strongswan --user strongswan --keep-unit --register=no -- /usr/libexec/ipsec/charon
PrivateNetwork=yes

The according strongswan.nspawn file has the following related contents:

[Exec]
Capability=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW
User=strongswan

The charon binary has the following capabilities specified in its posix file capabilities: net_admin, net_bind_service, net_raw

This combination used to work with version v241. The Capability setting in the nspawn configuration would allow the execv call to apply the capabilities found in the binary.

However, starting with commit a3fc6b55acd3f37e50915304d87bed100efa9d9d the CAP_NET_ADMIN setting from my own configuration is dropped because the default value of PrivateNetwork=no is applied here. See issue #11755

I think the explicit setting of Capability= should be prioritized over the handling of the default value of PrivateNetwork=.

Torsten

**Comment by myrkr** [comment]
I have a suggested solution to this problem in

myrkr/systemd/tree/allow-capability-to-overrule-implicit-dropping-of-cap-net-admin@4b4431686b7efd3d1b87f2810877d25430c6d82d

It changes the ordering, first removing CAP_NET_ADMIN if no private networking is configured and the adding the setting of Capability=. The setting of DropCapability= is removed in the last step.

**Comment by anitazha** [comment]
@myrkr Your approach sounds reasonable. Can you submit as a PR so it gets more visibility?
