### ISSUE TITLE
network: accept RA without DHCPv6 client

### ISSUE THREAD

**Issue by fluboi** [systemd/systemd#13991]
**systemd version the issue has been seen with**
> systemd 243 (243-4)
> systemd 241 (241)

**Used distribution**
 > Debian Sid (unsable) with systemd 243
 > Debian Buster 10.1 (stable) with systemd 241

**Expected behaviour you didn't see**
 > If explicitly disabled, DHCPv6 client should not start, even if some RA with MANAGED flag received.

**Unexpected behaviour you saw**
 > DHCPv6 client start 

**Steps to reproduce the problem**

```
[Match]
Name=ens18

[Network]
DHCP=no
```
```
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Invoking callback for 'router' event.
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Started in Managed mode
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Acquiring DHCPv6 lease on NDisc request
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Configuring route: dst: n/a, src: n/a, gw: fe80::ce7:e6ff:feea:b6ad, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Nov 10 15:01:43 networkd02 systemd-networkd[260]: rtnl: received non-static neighbor, ignoring.
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 1s
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Updating remembered route: dst: n/a, src: n/a, gw: fe80::ce7:e6ff:feea:b6ad, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Nov 10 15:01:43 networkd02 systemd-timesyncd[271]: Network configuration changed, trying to establish connection.
Nov 10 15:01:45 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:45 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 2s
Nov 10 15:01:47 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:47 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 4s
Nov 10 15:01:51 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:51 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 8s
```

Seems the same issue reported in #12324 
Currently, the DHCPv6 client of systemd-networkd still have some problematic issues, and we should be able to disable it completely (to be able to use an other DHCPv6 client)

**Comment by yuwata** [comment]
Please also disable `IPv6AcceptRA=`.

**Comment by fluboi** [comment]
But I need to accept RA ! 
Of course, if I disable `IPv6AcceptRA`, DHCPv6 client do not start, but I also loose the default route. 

And I can't use the kernel implementation to handle the RA, as systemd-networkd disable it.

>Note that kernel's implementation of the IPv6 RA protocol is always disabled, regardless of this setting.

We need a clean way to just disable the networkd DHCPv6 client, and keep accepting RA (to learn the default route)

**Comment by yuwata** [comment]
@ssahani Is it possible?

**Comment by ssahani** [comment]
>We need a clean way to just disable the networkd DHCPv6 client, and keep accepting RA (to learn the default route)

networkd does not start the DHCPv6 client unlesss the router says so . You router is sending M or O bit. You need to disable in the router conf.

**Comment by fluboi** [comment]
@ssahani I just want to use an other DHCPv6 client (dhclient or dibbler for exemple, that work great in my case) because the DHCPv6 client included in systemd-networkd is not working with my ISP setup.

I can't change the router configuration (it is not under my control).

**Comment by yuwata** [comment]
> systemd-networkd is not working with my ISP setup

Could you investigate why?

**Comment by fluboi** [comment]
> > systemd-networkd is not working with my ISP setup
> 
> Could you investigate why?

Explained in #13770 (the ISP start sending RA only once the first DHCPv6 exchange is done, and I'm not able to force networkd to start his DHCPv6 client)

Anyway it could be a good idea to have the possibility to just disable the networkd's DHCPv6 client.

**Comment by ssahani** [comment]
> Explained in #13770 (the ISP start sending RA only once the first DHCPv6 exchange is done, and I'm not able to force networkd to start his DHCPv6 client)

No that is not the case. See the logs what you attached.
```
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Received Router Advertisement: <flags MANAGED preference medium lifetime 1800 sec <=================HERE
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Invoking callback for 'router' event.
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Started in Managed mode <= Here the DHCPv6v client starts
```
>Anyway it could be a good idea to have the possibility to just disable the networkd's DHCPv6 client.

The IPs are managed by your  ISP. Is this a good idea that you do not comply that ?

**Comment by fluboi** [comment]
@ssahani 

> > Explained in #13770 (the ISP start sending RA only once the first DHCPv6 exchange is done, and I'm not able to force networkd to start his DHCPv6 client)
> 
> No that is not the case. See the logs what you attached.
> 
> ```
> Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Received Router Advertisement: <flags MANAGED preference medium lifetime 1800 sec <=================HERE
> Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Invoking callback for 'router' event.
> Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Started in Managed mode <= Here the DHCPv6v client starts
> ```

The logs provided here are just to explain this specific issue of not being able to disable DHCPv6 client. It's a simplified test setup between 2 host I directly control. 
This is not the real production setup, to have something easily understandable and reproducible.
Please see logs in #13770 for the other issue.


> The IPs are managed by your ISP. Is this a good idea that you do not comply that ?

I just want to use an other DHCPv6 client that the one provided in networkd.

**Comment by ssahani** [comment]
Can you point me in the rfc where it works like this what you saying.

**Comment by fluboi** [comment]
I'm afraid to not understand what you are saying. :(
The finality is just to be able to use an other DHCPv6 client that the one provided in networkd. RFC are not here to describe that kind of things.

**Comment by ssahani** [comment]
Even I don't understand what your saying. Can you point me the rfc how it supposed to work. It simple as that.

**Comment by fluboi** [comment]
I don't want to fight against you. If you thing this issue should be closed, close it.

The fact is really simple. If networkd is enable, there is no way no use an other (working) DHCPv6 client (like dibbler or dhclient for exemple). 

Of course there is no RFC that said "networkd must allow other DHCPv6 client to cohabit with it".

**Comment by ssahani** [comment]
The point is the log what you provide is against what you say. I am only asking you how the rfc points how it works.

**Comment by fluboi** [comment]
The logs show that it's impossible to disable the DHCPv6 client and keep accepting RA. 
Result is that we can't use an other DHCPv6 client if networkd is enable. (as the default route is not learnt if RA not accepted)

I don't see any contradiction between what I say and the logs. Can you be more specific?
RFC has nothing to do with it. We are not talking about the DHCPv6 protocol itself. 

Maybe the real problem is just that networkd disable by force the RA kernel implementation and there is no way to tell it to leave it as is. 

> Note that kernel's implementation of the IPv6 RA protocol is always disabled, regardless of this setting.

**Comment by ssahani** [comment]
I do understand you want a knob that is kist a line of change but I do not know does DHCPv6 client same  as DHCPv4 as per the RFC for example please see 

[Explain the “M” and “O” bit in IPv6 DHCP server configuration. What are the associated flags ](https://community.arubanetworks.com/t5/Controller-Based-WLANs/Explain-the-M-and-O-bit-in-IPv6-DHCP-server-configuration-What/ta-p/177442https://community.arubanetworks.com/t5/Controller-Based-WLANs/Explain-the-M-and-O-bit-in-IPv6-DHCP-server-configuration-What/ta-p/177442)

**Comment by fluboi** [comment]
With my poor english, I am not sure of what do you mean in your previous message. 

DHCPv4 and DHCPv6 are indeed quite different. A main difference, important here, is that in DHCPv6 the gateway address is **not** provided. (never)
So, to learn the default route, an IPv6 host need to receive "Router Advertisement" from the router. 

Handling Router Advertisement is not the job of DHCPv6 clients. It is processed separately, usually directly by the kernel (or in networkd case by the userland implementation) 

That's why, if we want to use an alternate DHCPv6 client, we need the ability to accept Router Advertisement, even if networkd DHCPv6 client is disabled.

RouterAdvertissement also have secondary features, as informing hosts if they need to obtain an IPv6 using DHCPv6 or instead using SLAAC auto-configuration mechanism ("M" flag).

**Comment by ssahani** [comment]
Can you please test https://github.com/systemd/systemd/pull/14885. Is this you wanted ?

**Comment by amessina** [comment]
@ssahani, I'll leave it to @fluboi to answer your question directly but reading through this issue, it seems like the patch does the opposite of what is described.

The way I understand the request is that the host should receive and process RA with `IPv6AcceptRA=yes`, but when `DHCP=no`, the DHCPv6 client should *never* start automatically (the implication being that is was disabled by `DHCP=no`).

In my own case, I have a host that I want to have a consistent address in a network environment that has DHCPv6/SLAAC enabled on a router I don't control.  I don't want it to obtain the DHCPv6 address from the router. I only want the one I can set with `Address=` or *prefer* with `IPv6Token=` (SLAAC).  Also in my case, I need the default route to be obtained with RA.

```
[Match]
Name=eno1

[Network]
DHCP=no
IPv6Token=::1000
IPv6AcceptRA=yes

Address=2001:db8:dead:beef::1000/64
```

If a new flag needs to be created to disable DHCPv6 even when the M or O flag is received, then perhaps something like the following would make sense
```
[IPv6AcceptRA]
# Disable DHCPv6 client operations even if the M or O flag is received
DHCPv6Client=no|auto
```

**Comment by yuwata** [comment]
Please test #14887.

**Comment by ssahani** [comment]
I don't understand why you need the ra even. It seems you are something on your own. Why would the DHCPv6 client run without the m or O bit. This is wrong.

**Comment by legrostdg** [comment]
I think the initial report does explain the problem: 

> Currently, the DHCPv6 client of systemd-networkd still have some problematic issues, and we should be able to disable it completely (to be able to use an other DHCPv6 client)

**Comment by fluboi** [comment]
#14887 seems to solve this issue (#13991)
#14885 seems to solve #13770 

Both are useful. Need to test.

**Comment by yuwata** [comment]
@ssahani WDYT? If you agree with that, please reopen your PR.

**Comment by ssahani** [comment]
@yuwata Need to see the test result.
