### ISSUE TITLE
Cannot use $env/%E in PROGRAM

### ISSUE THREAD

**Issue by fleutot** [systemd/systemd#14009]
This is my udev rule:

    SUBSYSTEM=="tty", ATTRS{idVendor}=="1366", ATTRS{idProduct}=="1015", ATTRS{serial}=="000621000000", SYMLINK+="ttymkw", PROGRAM+="/bin/systemd-escape --path --template=offnet-uart-log@.service $env{ID_SERIAL_SHORT}", ENV{SYSTEMD_WANTS}+="'%c'"

My systemd unit file only outputs the template parameter to a temporary log file, on which I `tail -f`:

    [Unit]
    Description=Start log of UART for a Offnet unit
    
    [Service]
    ExecStart=/bin/sh -c "/bin/echo %i >> /tmp/asdf.log"

Connecting/disconnecting the USB unit gives nothing in the log file. The symlink is not created either.

If I replace `$env{ID_SERIAL_SHORT}` with a hard-coded value (000621000000), then I get that string in the log file, and the symlink.

Running udevadm info on that symlink:

    $ udevadm info -q property -n /dev/ttymkw --export
    DEVPATH='/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:02.0/0000:39:00.0/usb3/3-1/3-1.7/3-1.7.2/3-1.7.2:1.0/tty/ttyACM0'
    DEVNAME='/dev/ttyACM0'
    MAJOR='166'
    MINOR='0'
    SUBSYSTEM='tty'
    USEC_INITIALIZED='2399556118671'
    SYSTEMD_WANTS=''offnet-uart-log@000621000000.service''
    ID_BUS='usb'
    ID_VENDOR_ID='1366'
    ID_MODEL_ID='1015'
    ID_PCI_CLASS_FROM_DATABASE='Serial bus controller'
    ID_PCI_SUBCLASS_FROM_DATABASE='USB controller'
    ID_PCI_INTERFACE_FROM_DATABASE='XHCI'
    ID_VENDOR_FROM_DATABASE='SEGGER'
    ID_MODEL_FROM_DATABASE='DSL6340 USB 3.1 Controller [Alpine Ridge]'
    ID_VENDOR='SEGGER'
    ID_VENDOR_ENC='SEGGER'
    ID_MODEL='J-Link'
    ID_MODEL_ENC='J-Link'
    ID_REVISION='0100'
    ID_SERIAL='SEGGER_J-Link_000621000000'
    ID_SERIAL_SHORT='000621000000'                          # <--- This is the parameter I'm looking for
    ID_TYPE='generic'
    ID_USB_INTERFACES=':020201:0a0000:ffffff:080650:'
    ID_USB_INTERFACE_NUM='00'
    ID_USB_DRIVER='cdc_acm'
    ID_USB_CLASS_FROM_DATABASE='Miscellaneous Device'
    ID_USB_PROTOCOL_FROM_DATABASE='Interface Association'
    ID_PATH='pci-0000:39:00.0-usb-0:1.7.2:1.0'
    ID_PATH_TAG='pci-0000_39_00_0-usb-0_1_7_2_1_0'
    ID_MM_CANDIDATE='1'
    DEVLINKS='/dev/serial/by-path/pci-0000:39:00.0-usb-0:1.7.2:1.0 /dev/ttymkw /dev/serial/by-id/usb-SEGGER_J-Link_000621000000-if00'
    TAGS=':systemd:'

I am missing something in using `$env` in combination with `systemd-escape` in `PROGRAM`. That seems to make the whole rule fail (no symlink created). Single quoting the `$env{}` construct makes the rule partly work (symlink created), but what I get in the temporary log file is a dash.

    $ systemd --version
    systemd 241 (241)

**Comment by yuwata** [comment]
`ID_SERIAL_SHORT` is set by 60-persistent-storage.rules. Is your .rules file has a number greater than 60?

**Comment by fleutot** [comment]
@yuwata Good question, my file is 10-local.rules! I had no understanding of what set `ID_SERIAL_SHORT`, or when. Thanks for giving me that.

I just browsed 60-persistent-storage.rules, and only found `ID_SERIAL_SHORT` for disks and partitions. I didn't find any other `ID_SERIAL_SHORT` in `/{etc,lib}/udev/rules.d`, so now I'm wondering what sets the variable for my UART tty. Surely, the disk/partition rules in 60-persistent-storage.rules should not trigger on my UART tty?

I just only discovered that `$attr{serial}` works fine in the udev rule, and [this](https://unix.stackexchange.com/a/551913/38106) seems to work:

    SUBSYSTEM=="tty", ATTRS{idVendor}=="1366", SYMLINK+="ttymkw", ENV{SYSTEMD_WANTS}+="offnet-uart-log@$attr{serial}"

(it doesn't even seem to need the `TAG+="systemd"`)

My actual problem is solved, but it would still be nice to understand who's setting the `ID_SERIAL` env var for my UART tty.

**Comment by yuwata** [comment]
Ah, sorry, I show a wrong pointer. For tty, 60-serial.rules provides `ID_SERIAL`. You can find `IMPORT{builtin}="usb_id"` and the builtin set `ID_SERIAL` here: https://github.com/systemd/systemd/blob/437f48a471f51ac9dd2697ee3b848a71b4f101df/src/udev/udev-builtin-usb_id.c#L440-L442

**Comment by fleutot** [comment]
Oh! So `ID_SERIAL` is not explicitly set by the rules, but by the rule's import on the builtin! Good to know, I wouldn't have found that.

Any reason to increase the number of my rule file to above 60, rather than directly using `$attr{serial)`?

**Comment by yuwata** [comment]
`ID_SERIAL_SHORT` and `$attr{serial}` are equivalent (at least) for usb device. Please see the source code of `udev-builtin-usb_id.c`.

**Comment by yuwata** [comment]
Anyway, this is not a bug of udevd. Let's close.
