### ISSUE TITLE
systemd-nspawn: appears to be resolving symlinks before chroot

### ISSUE THREAD

**Issue by cgonyeo** [systemd/systemd#1400]
If systemd-nspawn is given a symlink to execute, it appears to be attempting to resolve it before chrooting to the given location, and if it cannot resolve the symlink it will refuse to execute it.

This is an issue with symlinks with absolute paths, because the binaries they're referencing inside of their chroot may not exist outside of the chroot.

To see the issue (on a system where `/bin/busybox` doesn't exist):
- `curl -L -o alpine.aci https://quay.io/c1/aci/quay.io/coreos/alpine-sh/latest/aci/linux/amd64/`
- `mkdir alpine`
- `tar xf alpine.aci -C alpine`
- `ls -l alpine/rootfs/bin/ls`
- `systemd-nspawn -D alpine/rootfs /bin/ls`
- Note the error
- `touch /bin/busybox`
- `systemd-nspawn -D alpine/rootfs /bin/ls`
- Note the lack of error

It also looks like this has been [reported on bugzilla](https://bugs.freedesktop.org/show_bug.cgi?id=86555), but it doesn't appear to have had any activity for a while.

**Comment by poettering** [comment]
Note that we generally do not copy bugs from bugzilla here. We still look at both bug trackers. Anyway, since we have this here now, I figure we can close the one in bugzilla.
