### ISSUE TITLE
Permit usage of `PrivateNetwork` with `PrivateUsers` in service files run by unpriviledged user

### ISSUE THREAD

**Issue by balaziks** [systemd/systemd#14005]
**Is your feature request related to a problem? Please describe.**

I would greatly appreciate if non-system services could be run in user and network namespace like a non-root user is able to using `unshare` command.

`PrivateNetwork=yes` option can't be used in non-system services.
`unshare -n` can't be run as non-root user. 

`PrivateUsers=yes` option can't be used in non-system services.
 `unshare -rU` **can** be run as non-root user. 

Moreover: `unshare -rUn` **can** be run as non-root creating **both network and user namespace** which is exactly what I need for my use-case.

Is there a reason why this is not possible in user services?

**Describe the solution you'd like**
Enable unprivileged users to run services in both user and network namespace equivalently to running executables after `unshare -rUn`.

**Describe alternatives you've considered**
I am currently running all the services that need running in network namespace as system services which *might* create a security risk.

**Comment by anitazha** [comment]
I have a PR open for this: https://github.com/systemd/systemd/pull/13823
