### ISSUE TITLE
Path instances with dashes do not work - mount

### ISSUE THREAD

**Issue by Dinth** [systemd/systemd#14000]
I believe this bug is related to https://github.com/systemd/systemd/issues/5072
Although the workaround proposed there doesnt work here.

**systemd version the issue has been seen with**
240

**Used distribution**
Ubuntu 19.04

**Expected behaviour you didn't see**
Being able to create a working .mount file which would mount SMB share to directory /Data-local/hassio/homeassistant/www/CCTV.

**Unexpected behaviour you saw**
Its not possible to create such file as it fails with 
`Data-local-hassio-homeassistant-www-CCTV.mount: Where= setting doesn't match unit name. Refusing`
Systemd-escape of that path:
```
$ systemd-escape -p --suffix=mount /Data-local/hassio/homeassistant/www/CCTV
Data\x2dlocal-hassio-homeassistant-www-CCTV.mount
```
This being said, \2d gets translated to - when creating the file. So according to systemd-escape the correct file name is Data-local-hassio-homeassistant-www-CCTV.mount. Except this doesnt work and even if it would, breaks the ability of systemd to translate escaped path back to the original name. 

**Steps to reproduce the problem**
Create a mount file which uses a path containing a dash/hyphen in Where= field.

**Comment by keszybz** [comment]
You need to escape the backslash when creating the file:
`emacs /etc/systemd/system/Data\\x2dlocal-hassio-homeassistant-www-CCTV.mount`.

```console
$ sudo emacs /etc/systemd/systemd/data\\x2dlocal-foobar.mount
$ systemctl cat /data-local/foobar
# /etc/systemd/system/data\x2dlocal-foobar.mount
[Mount]
What=/tmp/foobar.img
Where=/data-local/foobar
$ sudo systemctl start /data-local/foobar
$ systemctl status /data-local/foobar
● data\x2dlocal-foobar.mount - /data-local/foobar
   Loaded: loaded (/etc/systemd/system/data\x2dlocal-foobar.mount; static; vendor preset: disabled)
   Active: active (mounted) since Tue 2019-11-12 12:21:00 CET; 4s ago
    Where: /data-local/foobar
     What: /dev/loop6
    Tasks: 0 (limit: 9351)
   Memory: 408.0K
      CPU: 8ms
   CGroup: /system.slice/data\x2dlocal-foobar.mount

Nov 12 12:21:00 krowka systemd[1]: Mounting /data-local/foobar...
Nov 12 12:21:00 krowka systemd[1]: Mounted /data-local/foobar.
```

**Comment by keszybz** [comment]
(Though, I think the backslash escapes were not the best choice from usability perspective. Using a different escape mechanism then the shell would have been better. But this is baked very deeply in now, so changing this is unrealastic.)
