### ISSUE TITLE
Udevd is dropping  CHANGE events when REMOVE event gets queued

### ISSUE THREAD

**Issue by zkabelac** [systemd/systemd#14016]
**systemd version the issue has been seen with**
>  systemd-udev-243-4.gitef67743.fc32.x86_64

**Used distribution**
 > Fedora Rawhide 

**Expected behaviour you didn't see**
 > Every CHANGE event for DM device being processed

**Unexpected behaviour you saw**
 > When REMOVE event comes in close 'time' distance after a CHANGE event, the processing of CHANGE event gets dropped and only REMOVE event is processed

**Steps to reproduce the problem**

This simple shell script shows the issue easily:

-----------------

#!/bin/sh -x

cookie=$(dmsetup udevcreatecookie)
export DM_UDEV_COOKIE=$cookie
dmsetup create -u FAKEUUID fakezerodev --table '0 1000 zero'

#_with sleep it always works
#_without sleep it's known to work on f29
#_sleep 3

dmsetup remove fakezerodev

#_will endlessly wait here with  bad udevd version
dmsetup udevreleasecookie

unset DM_UDEV_COOKIE

-----------

On previously working udev (i.e. Fedora 29) - this script never freezes,
on newer udev (after some major rework of internal structure processing) this seems to freeze in case  udev  worker process in not 'fast enough' to process ADD +  CHANGE event from 'create'  before REMOVE arrives.

In lvm2 we manage to add workaround and avoid 'sending'  CHANGE & REMOVE in a single cookie transaction - but in case  3rd. part command like   'dmsetup'  works with device (i.e. dmsetup remove_all  being executed while lvm2 plays with device or clvmd activating device we can still easily end with 'blocked' processing  waiting for decrementing our semaphore.

So at this moment we expect CHANGE events are not being dropped.

**Comment by yuwata** [comment]
Could you provide a relevant debug log of udevd?

**Comment by yuwata** [comment]
Also, could you test the script with the current git snapshot? I hope this is already fixed by PR #13984.

**Comment by zkabelac** [comment]
Yes - issue  13984 looks like it's the same case -  in lvm2 we actually added 'workaround' for the snapshot issue sometimes ago - but from description it does look equivalent - so I'll wait till new systemd package gets to Rawhide repo with patch included and will check the above script.
