### ISSUE TITLE
system container execute "systemctl daemor-reload", cgroup memory is error

### ISSUE THREAD

**Issue by JackFangXN** [systemd/systemd#14014]
**systemd version the issue has been seen with**
> ...
systemd239

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …
free -g
memory is 3G
**Unexpected behaviour you saw**
 > …
free -g 
memory is 125G
**Steps to reproduce the problem**
1、docker create -i --env-target-file=/etc/environment --memory=3221225472 --memory-swap=3221225472 in /sys/fs/cgroup/memory/lxc， create  a system container and memory is 3G;
2、login system container and cat /sys/fs/cgroup/memory/memory.limit_in_byte, the value is 3G;
3、excute "systemctl daemon-reload", free -g, the memory change 125G, cat /sys/fs/cgroup/memory/memory.limit_in_byte, the value is -1;
4、i find that 125G is host's memory. cgroup.c->cgroup_context_apply()->is_root return false, memoryMax default value is infinity, so when excute "systemctl daemon-reload" , memory.limit_in_bytes is setted memoryMax, and memoryMax is -1(125G)。so i want to know that is there better way to solve the issue. Now do systemd support system container or not. 

code:
  if ((apply_mask & CGROUP_MASK_MEMORY) && !is_root) {
                if (cg_all_unified() > 0) {
                        uint64_t max, swap_max = CGROUP_LIMIT_MAX;

**Comment by JackFangXN** [comment]
execute setp:

64CD1EA1-729E-E711-9D18-143004D58ACE:/sys/fs/cgroup/memory/lxc # docker exec -it d98da8db bash
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# 
[root@localhost /]# cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
3221225472
[root@localhost /]# free -g
              total        used        free      shared  buff/cache   available
Mem:              3           0           2           0           0           2
Swap:             0           0           0
[root@localhost /]# systemctl daemon-reload
[root@localhost /]# free -g
              total        used        free      shared  buff/cache   available
Mem:            125           0         125           0           0         125
Swap:             0           0           0
[root@localhost /]# cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
9223372036854771712
[root@localhost /]#

**Comment by poettering** [comment]
Please update. Already fixed in be2c0327816.

Also, we try to make expressly clear that this bug tracker only trackes issues in the two most recent systemd versions. 239 does not qualify at all, we are currently at 242 and 243...

**Comment by JackFangXN** [comment]
tks, i like it.
