### ISSUE TITLE
propagation of errors in udev_event_execute_rules breaks kpartx in container

### ISSUE THREAD

**Issue by mwhudson** [systemd/systemd#14033]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > Ubuntu 20.10

**Expected behaviour you didn't see**
 > In a lxd container with a particular setup (see below), kpartx -sav on an image should work.

**Unexpected behaviour you saw**
 > kpartx hangs.

**Steps to reproduce the problem**

Run this script in an Ubuntu Xenial VM (needs to be Xenial to get an lxd version that works with this profile):

```
#!/bin/bash

set -eux

lxc profile create buildd || true

lxc profile edit buildd <<EOF
config:
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.cap.drop=
    lxc.cap.drop=sys_time sys_module
    lxc.cgroup.devices.deny=
    lxc.cgroup.devices.allow=
    lxc.mount.auto=
    lxc.mount.auto=proc:rw sys:rw
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
name: buildd
EOF

lxc delete --force test || true

# This build has systemd 242
lxc launch ubuntu-daily:f25ce363526247e376e29622f9f030dfbd839fa1c735b9934e4877831e930257 test -p buildd

wget https://launchpad.net/ubuntu/+source/systemd/243-3ubuntu1/+build/18003532/+files/udev_243-3ubuntu1_amd64.deb
wget https://launchpad.net/ubuntu/+source/systemd/243-3ubuntu1/+build/18003532/+files/libudev1_243-3ubuntu1_amd64.deb
wget https://launchpad.net/ubuntu/+source/systemd/242-7ubuntu3/+build/17878773/+files/udev_242-7ubuntu3_amd64.deb
wget https://launchpad.net/ubuntu/+source/systemd/242-7ubuntu3/+build/17878773/+files/libudev1_242-7ubuntu3_amd64.deb

lxc file push *.deb test/tmp/

lxc file push - test/root/test.sh <<\EOF
set +e
mknod -m 0660 /dev/loop-control c 10 237
for i in 0 1 2 3 4 5 6 7; do mknod -m 0660 /dev/loop$i b 7 $i; done
set -e
rm -f image.img
truncate -s1G image.img
parted --align optimal --script image.img -- \
  mklabel gpt \
  mkpart part ext2 2MiB -2MiB
kpartx -sav image.img
kpartx -d image.img
dpkg -i /tmp/udev_243-3ubuntu1_amd64.deb /tmp/libudev1_243-3ubuntu1_amd64.deb
kpartx -sav image.img
EOF

lxc exec test -- bash -eux /root/test.sh
```

What is going on is that this command specified by 95-dm-notify.rules:

ENV{DM_COOKIE}=="?*", RUN+="/sbin/dmsetup udevcomplete $env{DM_COOKIE}"

is not being run, because update_devnode fails (because /dev is a tmpfs not a devtmpfs and so /dev/dm-0 does not exist) and as of v243 udev_event_execute_rules now propagates this failure to worker_process_device and so this function does not call udev_event_execute_run.

I have no idea what's the best fix here. libdevmapper is relying on udevcomplete being called to know that udev has finished processing (and in this case, falls back to creating the device node it needs itself). On the other hand, I can see the argument for not running RUN commands if there is no device node at all.

**Comment by poettering** [comment]
Udev is not supported in containers. Sorry. The linux kernel does not virtualize the device model for containers hence you. Annot run more than one instance of udev sanely. If you do anyway all instances will constantly fight for device ownership. 

Sorry.
