### ISSUE TITLE
Fails to build on arm64

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#14031]
v243 fails to build on arm64 on Debian sid:
```

../src/test/test-seccomp.c: In function ‘test_protect_sysctl’:
../src/test/test-seccomp.c:307:5: error: "__NR__sysctl" is not defined, evaluates to 0 [-Werror=undef]
  307 | #if __NR__sysctl > 0
      |     ^~~~~~~~~~~~
../src/test/test-seccomp.c:314:5: error: "__NR__sysctl" is not defined, evaluates to 0 [-Werror=undef]
  314 | #if __NR__sysctl > 0
      |     ^~~~~~~~~~~~
cc1: some warnings being treated as errors
```

Full build log available at https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=arm64&ver=243-6&stamp=1573744894&raw=0

I'm not entirely sure what changed between 243-5 and 243-6 which could trigger that error.
243-5 built fine https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=arm64&ver=243-6&stamp=1573744894&raw=0

**Comment by poettering** [comment]
is it possible that not systemd changed but libseccomp? old libseccomp used to define __NR_sysctl and friends to negative values on systems that do not support them. The newest libseccomp doesn#t do that anymore. Maybe libseccomp was updated like that on debian at the same time?

**Comment by mbiebl** [comment]
Good call, libseccomp was updated between 243-5 and 243-6:

https://tracker.debian.org/news/1079515/accepted-libseccomp-242-1-source-into-unstable/

Seems like 2.4.2-1 does trigger this build failure.

**Comment by poettering** [comment]
Can you check if #14032 fixes this for you?

**Comment by mbiebl** [comment]
The above PR does fix the build failure on arm64.
