### ISSUE TITLE
Permit use of systemd with custom early-boot and late-shutdown scripts

### ISSUE THREAD

**Issue by joshudson** [systemd/systemd#14058]
EDIT: we are very close to option 2, and this may be a documentation issue. See comments below.

**Is your feature request related to a problem? Please describe.**

I've had a bunch of related failures of systemd to handle the hardware. It always comes down the same basic idea: the hardware is somehow weird, or an in untested case, or otherwise doesn't meet systemd's idea of dynamic hardware detection.

On my current home system, systemd fails to mount any disks with a timeout error, but `mount -a` has no problem doing so. On a different system, it tries to run commands before the filesystem that contains them is ready.

**Describe the solution you'd like**

I forsee two reasonably good solutions. 1) Well defined system interface for swapping out PID 1 with a much simpler system and run systemd's service manager as "PID 2". 2) Infrastructure to hand-off to systemd from a `#!/bin/sh` script installed as `/sbin/init` via `exec` after early startup, and hand-back PID 1 to yet another shell script in late shutdown.

**Describe alternatives you've considered**

sysvinit + gdb + #!/bin/sh + elogind

Unfortunately this loses the ability to use systemd's unit files, which is the best part of systemd.

**Comment by joshudson** [comment]
So I'm going to go ahead and drop a link here you might not like. https://ewontfix.com/14/ There's exactly one thing here worth looking at. He has a really really simple PID 1 program a little more than half way down. My belief is the reason systemd wants to run as PID1 is to be notified about system-wide zombies so it can do something in the service manager. So an interface could be readily designed to do exactly that. Perhaps the best way is to have the service manager take a pipe that receives an endless stream of notifications of this structure: { pid_t pid; int waitstatus; } which is the result from waitpid serialized in the simplest form.

**Comment by boucman** [comment]
you can already use a shell script as pid1 then exec into systemd

there is also a place where you can put binaries to run at shutdown, see man:systemd-halt.service that documents that part

**Comment by joshudson** [comment]
@boucman : The problem in late shutdown is systemd is still holding locks on /. Since it's PID1 I can't kill it, and the gdb trick doesn't work on multi-threaded processes.

**Comment by joshudson** [comment]
I think I should be a bit more clear. The gdb trick is essentially ordering process 1 to exec the shutdown script after a call to `pivot_root()`, which lets go of the locks on / so it can be unmounted.

**Comment by boucman** [comment]
I'm not sure what you mean, but pivoting  back to the initrd at shutdown is also supported...

I'm not sure how it works though. I think it's documented in man:bootup

**Comment by joshudson** [comment]
Found additional document: https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

The documented interface intercepts too late in the shutdown process. It's like I really need to say "run this binary instead of systemd-shutdown".

**Comment by refi64** [comment]
Both cases honestly sound like you have some sort of issue with your
fstab... Either way I'm not sure how making systemd pid2 would help?

**Comment by poettering** [comment]
I think it would be better to properly fix these drivers/subsystems...

But yeah, at boot you can already plug a shell script beforehand if you like, just pass its path to init= on the kernel cmdline, and make sure to invoke systemd afterwards via "exec" so that it becomes PID 1.

And for shutdown if you want to be invoked without PID1 blocking unmounts of the root dir, you have to implement the initrd interface, and that's perfectly well documented and supported. it's not trivial since we need to pivot root to something so that the we can stop referencing the root dir.

Hence, afaics everything you are asking for is already implemented, and pretty much documented, hence closing.

**Comment by joshudson** [comment]
@boucman : Nothing's wrong with fstab. mount -a works just fine.
