### ISSUE TITLE
make "networkctl status" show logs related to the specified iface

### ISSUE THREAD

**Issue by tomfitzhenry** [systemd/systemd#14050]
**systemd version the issue has been seen with**
> systemd 243

**Used distribution**
 > NixOS 19.09 and NixOS master

**Expected behaviour you didn't see**
 > systemd-networkd should listen on `67/udp`.

**Unexpected behaviour you saw**
 > systemd-networkd did not listen on `67/udp`

With hindsight, this systemd-networkd warning is relevant:
> systemd-networkd[489]: Failed to determine timezone: No such file or directory

**Steps to reproduce the problem**
```
[Match]
Name=eth0

[Network]
DHCPServer=true
Address=10.0.0.1/24

[DHCPServer]
DNS=10.0.0.1
PoolOffset=100
```

https://github.com/NixOS/nixpkgs/pull/73505 has an automated test to reproduce this, executable via https://nixos.org/nixos/manual/index.html#sec-running-nixos-tests-interactively .

**Mechanism**

In systemd 242, `systemd` would create `/etc/localtime` and `systemd-networkd` would grab timezone info from `/etc/localtime` as part of being a DHCP server. Everything is good so far.

systemd 243 introduced https://github.com/systemd/systemd/commit/09bef967d9cacb95bafab0882606cc3a57ac324e, which removed the creation of `/etc/localtime`, and thus `systemd-networkd` [fails to get timezone data](https://github.com/systemd/systemd/blob/efb536d0cbe2e58f80e501d19999928c75e08f6a/src/basic/time-util.c#L1393-L1395), and thus [fails to start a DHCP server](https://github.com/systemd/systemd/blob/efb536d0cbe2e58f80e501d19999928c75e08f6a/src/network/networkd-dhcp-server.c#L223-L225). In particular, not listening on `67/udp`.

https://github.com/systemd/systemd/commit/bc9ecd484f1ebfe0de8b567c90f6cd867fbd5894 will fix this by falling back to UTC if `/etc/localtime` does not exist.

**Workaround**
Set `EmitTimezone=false` under `[DHCPServer]`.

**Context**

Tracked in NixOS at https://github.com/NixOS/nixpkgs/issues/73504 .

**Comment by tomfitzhenry** [comment]
Though it looks like https://github.com/systemd/systemd/commit/bc9ecd484f1ebfe0de8b567c90f6cd867fbd5894 fixes this in HEAD, I've raised this bug to give awareness to others experiencing this issue, and to track:
* this being mentioned in NEWS (?)
* turning a warning into an error, which wouldn't allowed me to more quickly diagnose this on my machine.

**Comment by poettering** [comment]
So yeah, bc9ecd484f1ebfe0de8b567c90f6cd867fbd5894 coincidentally fixes this.

We usually don't mention bugfixes in NEWS. It'd simply be too many, NEWS is supposed to be for the highlights, i.e. feature additoins. If you want the full list of changes including bugfixes "git shortlog" is really the best option.

I am also tempted to say that the networkd should probably continue to warn but continue if we cannot initialize the DHCP server. Logging at error usually means something is withing some specific context fatal, but I don#t think this should be made fatal.

Instead, maybe we should turn this into an RFE that makes "networkctl status $IFACE" show the most recent logs for that interface among its output similar to how "systemctl status" does that for services. if we had that it would be easy to find this kind of stuff...

**Comment by tomfitzhenry** [comment]
> We usually don't mention bugfixes in NEWS. It'd simply be too many, NEWS is supposed to be for the highlights, i.e. feature additoins. If you want the full list of changes including bugfixes "git shortlog" is really the best option.

Fair.

> I am also tempted to say that the networkd should probably continue to warn but continue if we cannot initialize the DHCP server. Logging at error usually means something is withing some specific context fatal, but I don#t think this should be made fatal.

https://github.com/systemd/systemd/commit/a0fa3ef7ffe253ac72a2e6ed70f4facf884793d7 has already changed the warnings into errors, but if that isn't consistent with the rest of the source's log levels, I can see why you might want to revert it. Perhaps those warning messages could be modified to include the causal link between failure to get timezone, and DHCP server not starting.

e.g.

"Failed to determine timezone: %m"

might become

"Failed to determine timezone, refusing to start DHCP server: %m"

or some such?

> Instead, maybe we should turn this into an RFE that makes "networkctl status $IFACE" show the most recent logs for that interface among its output similar to how "systemctl status" does that for services. if we had that it would be easy to find this kind of stuff...

Yes, that sounds useful, and the consistency with 'systemctl status' makes it easy to understand and expected.
