### ISSUE TITLE
systemd-growfs: resizing partition tables

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#14052]
**Is your feature request related to a problem? Please describe.**

systemd introduced resizing filesystems with systemd-growfs in systemd 236.
This is enough for most usecases, but there are other usecases where resizing the partition table would make sense.

1. cloud images: Imagine a vendor who ships cloud images with 500M small images. Right now, systemd has the possibility to resize the filesystem, but there is no possibility to resize the partition table + resize the filesystem. With such a resize feature it would be possible to increase the hard disk size of the cloud VM and systemd will magically resize the partition table + the filesystem.

2. iot devices: Imagine raspberry pies or any other embedded board with linux support. The user could just buy a 64GB sd card, put their favourite linux on it and systemd would magically resize the partition table and resize the filesystem.

We could isolate this feature on the following partition table:

```
/dev/sda1 boot 100M
/dev/sda2 root 500M
EMPTY SPACE
```

In such a situation it would be cool if systemd could automatically detect (if the growfs service is enabled) that there is free space behind the sda2 partition, resize that to max size and resize the filesystem.

**Describe alternatives you've considered**
The alternative for such scenarios is the usage of cloud-init. But why using cloud-init, when systemd ships already a feature for resizing filesystems?

**Comment by poettering** [comment]
In the TODO list there's also an item for that: a small tool that can grow and augment the partition table during early boot. The idea was to have that separate from the fs growing though, so that they can be done independently and asynchronous.

**Comment by poettering** [comment]
I started implementing something like this here:

https://github.com/poettering/systemd/commits/repart

lacks docs and testing so far, and not entirely complete, but already pretty powerful.

**Comment by shibumi** [comment]
@poettering is there a way to easily get it in a container via `mkosi`? I am totally willing to test this and help out with the documentation part.
