### ISSUE TITLE
udev (incorrectly) complains about valid udev rules

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#14062]
**systemd version the issue has been seen with**

v243

**Used distribution**

Debian sid
Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944917
See also the discussion at https://lists.freedesktop.org/archives/systemd-devel/2019-November/043711.html

Since the upgrade to v243, I see udev complaining about a lot of udev rules files.

As an example:
```
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/56-lvm.rules:40 Invalid value for OPTIONS key, ignoring: 'event_timeout=180'
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/56-lvm.rules:40 The line takes no effect, ignoring.
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/90-libgpod.rules:19 IMPORT key takes '==' or '!=' operator, assuming '==', but please fix it.
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/90-libgpod.rules:23 IMPORT key takes '==' or '!=' operator, assuming '==', but please fix it.
```

Looking at e.g. 90-libgpod.rules, the rules look fine
```
ACTION=="add|change", ENV{USBMUX_SUPPORTED}=="1", IMPORT{program}+="/lib/udev/iphone-set-info", GOTO="libgpod_end"

ACTION=="add|change", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac",
ATTR{idProduct}=="129[0-9a]", IMPORT{program}+="/lib/udev/iphone-set-info"
```

The recommendation to replace `+=` with `==` is bogus afaics and the existing udev rules are valid.

**Comment by mbiebl** [comment]
In the mailing list discussion it was mentioned that this is likely a result of  commit 25de7aa7b90c23d33ea50ada1e50c5834a414237
```
Author: Yu Watanabe <watanabe.yu+github at gmail.com>
Date:   Thu Apr 25 01:21:11 2019 +0200

    udev: modernize udev-rules.c

    This does the following:
    - rename enum udev_builtin_cmd -> UdevBuiltinCmd
    - rename struct udev_builtin -> UdevBuiltin
    - move type definitions to udev-rules.h
    - move prototypes of functions defined in udev-rules.c to udev-rules.h
    - drop to use strbuf
    - propagate critical errors in applying rules,
    - drop limitation for number of tokens per line.
```

@yuwata maybe you want to chime in here.

I'm a bit worried that people might start to actually replace `+=` with `==`.

**Comment by mbiebl** [comment]
The relevant parts from 56-lvm.rules:
```
OPTIONS+="event_timeout=180"
```

**Comment by yuwata** [comment]
`systemd-udevd` does not support `OPTIONS+="event_timeout=180`.

**Comment by yuwata** [comment]
Since 25de7aa7b90c23d33ea50ada1e50c5834a414237, udev rules are evaluated more strictly. The behavior is intended. Maybe, we should update udev(7).

**Comment by mbiebl** [comment]
@yuwata what about the `IMPORT{program}+="` statements?

**Comment by yuwata** [comment]
`IMPORT` takes `==` or `!=`. We did not warn about that. Of course, we can silence the warning. But in the long term, `IMPORT` should use `==` or `!=`.

**Comment by mbiebl** [comment]
@yuwata huh? Even the systemd provided udev rules use `IMPORT{..}=`
Color me confused

**Comment by boucman** [comment]
yeah, '=' makes more sense... IMPORT{} add elements to the ENV, it's not a filter...

So far, all '==' and '!=' statements are pure filters, having them change the udev database is counter-untuitive.

'=' and '+=' makes more sense to me...

**Comment by yuwata** [comment]
If you run udevd in debug mode, you can find debug messages about `IMPORT{}=`.

OK. Let's also silence the `+=` case. But note that internally, it uses `==` or `!=`. We cannot change that because of backward compatibility.

**Comment by mbiebl** [comment]
> `systemd-udevd` does not support `OPTIONS+="event_timeout=180`.

Hm, since when is `OPTIONS+=` not supported anymore?
```
50-udev-default.rules:SUBSYSTEM=="rtc", KERNEL=="rtc0", SYMLINK+="rtc", OPTIONS+="link_priority=-100"
50-udev-default.rules:  OPTIONS+="static_node=snd/seq", OPTIONS+="static_node=snd/timer"
50-udev-default.rules:KERNEL=="loop-control", GROUP="disk", OPTIONS+="static_node=loop-control"
50-udev-default.rules:KERNEL=="tun", MODE="0666", OPTIONS+="static_node=net/tun"
50-udev-default.rules:KERNEL=="fuse", MODE="0666", OPTIONS+="static_node=fuse"
50-udev-default.rules:KERNEL=="kvm", GROUP="kvm", MODE="0660", OPTIONS+="static_node=kvm"
56-dm-parts.rules:ENV{DM_UDEV_LOW_PRIORITY_FLAG}!="1", OPTIONS+="link_priority=50"
56-lvm.rules:OPTIONS+="event_timeout=180"
60-block.rules:  OPTIONS+="watch"
60-cdrom_id.rules:KERNEL=="sr0", SYMLINK+="cdrom", OPTIONS+="link_priority=-100"
60-persistent-storage-dm.rules:OPTIONS+="watch"
63-md-raid-arrays.rules:ENV{DEVTYPE}=="disk", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}", OPTIONS+="string_escape=replace"
63-md-raid-arrays.rules:ENV{DEVTYPE}=="partition", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}-part%n", OPTIONS+="string_escape=replace"
63-md-raid-arrays.rules:OPTIONS+="link_priority=100"
63-md-raid-arrays.rules:OPTIONS+="watch"
70-uaccess.rules:  OPTIONS+="static_node=snd/timer", OPTIONS+="static_node=snd/seq"
80-debian-compat.rules:  SYMLINK+="cdrw", OPTIONS+="link_priority=-100"
80-debian-compat.rules:  SYMLINK+="dvd", OPTIONS+="link_priority=-100"
80-debian-compat.rules:  SYMLINK+="dvdrw", OPTIONS+="link_priority=-100"
```

**Comment by yuwata** [comment]
`systemd-udevd` has never supported `event_timeout=`. Only supported options are listed in udev(7).

**Comment by mbiebl** [comment]
Ah, k. So it's not the use of `+=` but the use of `event_timeout=`. Got you.
So this seems to be the only "real" bug afaics.

**Comment by mbiebl** [comment]
> If you run udevd in debug mode, you can find debug messages about `IMPORT{}=`.
> 
> OK. Let's also silence the `+=` case. But note that internally, it uses `==` or `!=`. We cannot change that because of backward compatibility.

Well, even in our own rules we use `=`. It's strange/unituitive to use `==` for `IMPORT`, especially when the documentation says about `==`:
```
       "=="
           Compare for equality.
```

**Comment by yuwata** [comment]
Yeah, I agree.

**Comment by boucman** [comment]
`PROGRAM` makes more sense since that statement is a filter on the return code (IIRC)

**Comment by yuwata** [comment]
IMPORT is the same.

**Comment by boucman** [comment]
ok, I see your point... it's not really a filter but a "skip this line on error"

**Comment by yuwata** [comment]
Right.
