### ISSUE TITLE
src/basic/locale-util.c variable vs glyph inconsistency

### ISSUE THREAD

**Issue by myllynen** [systemd/systemd#14075]
$ grep CROSS ./src/basic/locale-util.c | tail -n 1
                        [SPECIAL_GLYPH_CROSS_MARK]              = "\342\234\227",             /* ✗ */

The variable name refers to U+274C CROSS MARK but the code point (as well as the glyph in the comment) is actually U+2717 BALLOT X. This inconsistency should be fixed either by renaming the variable or correcting the codepoint (and the comment).

**Comment by poettering** [comment]
(I think it wouldn't hurt adding comments referencing the unicode names though)

**Comment by poettering** [comment]
Fix in #14502

**Comment by myllynen** [comment]
Looks perfect, thanks a lot!
