### ISSUE TITLE
Detect when program is started as a service

### ISSUE THREAD

**Issue by tmds** [systemd/systemd#14089]
Is there a way to detect a program was started from a (service) unit? And not from a terminal by the user.

I thought I had used `INVOCATION_ID` for this.
But when I run a terminal on Fedora 31, `INVOCATION_ID` is also set.

**Comment by boucman** [comment]
This is not a support forum, please ask on the mailing list... 

That being said, everything is a unit, since systemd is PID1.
(you might want to look for an environment variable added by your shell somewhere...)

**Comment by poettering** [comment]
as @boucman mentioned everything is running in a unit on systemd. Hence it's not clear what precisely you are trying to do? Do you mean "started as a service" as opposed to "running interactively from a tty"? If so, it's probably better to check explicitly for the latter, for example via "isatty(STDERR_FILENO)".

Anyway, this is not a feature request or bug report, hence let's close this here. Please contact the mailing list for support questions like this. Thank you.

**Comment by tmds** [comment]
@boucman @poettering I think for older versions of Fedora/systemd (Fedora 29 or 30), `INVOCATION_ID` was not set in a terminal. Are you aware of a change?

**Comment by boucman** [comment]
INVOCATION_ID is set for all services, systemd does not make a difference between a "daemon" and an "interactive session" so systemd always set INVOCATION_ID

The change is probably lower in the chain... i.e it's probably agetty/login/your shell that removes that variable. systemd doesn't know about interactive sessions
