### ISSUE TITLE
sd-boot: No menu displayed on keypress if timeout isn't specified

### ISSUE THREAD

**Issue by blochl** [systemd/systemd#14092]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > When no timeout is specified (EFI var `LoaderConfigTimeout-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f` deleted and no timeout item in the .conf file) the boot menu should appear when space or other key is pressed upon boot.

**Unexpected behaviour you saw**
 > The menu appeared only once out of ~15 boots done with the space key pressed. Tried both booting with the key constantly pressed, and with rapidly pressing it after boot.

**Steps to reproduce the problem**
> Remove the `LoaderConfigTimeout-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f` EFI variable, if existed, and try to reboot.

**Comment by poettering** [comment]
Not sure we can do much about this, we rely on the firmware to propagate keys instantly to us, but there might be firmwares that initialize hw async and thus if we ask for key state the kbd might not be probed and set up yet, and thus no key is reported... This is particularly the case for "slow" devices, such as USB (how is your kbd connected)?

in that case i am not sure whether there's much we can do...

**Comment by blochl** [comment]
Hi @poettering, thanks for the quick reply!
The device is quite new: Sony Vaio VJS132C11L - i5 8250U (2018).
Are there any more reliable or other possibilities for not having the boot menu displayed unless a key is pressed, besides removing the loader timeout EFI var and/or loader timeout .conf entry?

**Comment by blochl** [comment]
Just tried on another device - same thing. Is there a way not to show the menu, but to wait for the keyboard to become active? "Silent timeout" of sorts? If not, I'll try to cook something like that myself, in **src/boot/efi/boot.c**, I suppose.

**Comment by blochl** [comment]
Solved by #14217.
