### ISSUE TITLE
"No such file or directory" in systemd-cryptsetup when attempting to decrypt LUKS during init

### ISSUE THREAD

**Issue by initramfs** [systemd/systemd#14098]
**systemd version the issue has been seen with**
    
    systemd 242 (242-8~bpo10+1)
    +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

and

    systemd 241 (241)
    +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**

Debian Buster

**Expected behaviour you didn't see**

During init, `systemd-cryptsetup` should successfully open a LUKS-encrypted partition based on the provided kernel cmdline.

**Unexpected behaviour you saw**

systemd-cryptsetup throws the error:

    Failed to activate with key file '/run/systemd/cryptsetup/keydev-deviceluks/device-disk.key': No such file or directory

when using a keyfile or:

    Failed to activate with specified passphrase: No such file or directory

when using an interactive passphrase (the failure line appears after the interactive prompt is displayed and the correct password entered).

**Steps to reproduce the problem**

1. Begin new installation of a Debian 10 system
2. Setup manual partitioning and install the root system on an LUKS-based partition
3. Replace the initrd with dracut
4. Set the appropriate cmdline for booting using systemd
5. Attempt boot

---

When attempting to use systemd as an init (dracut as the initrd) to unlock a LUKS-based partition in which the root system resides on, the boot process fails when systemd-cryptsetup@<device>.service fails with the above error.
This is irrespective of whether an interactive passphrase is required or a key-file.

In my specific case, a keyfile is requested with the following boot cmdline:

    root=/dev/mapper/device--lvm-device--root ro rd.luks.name=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX=deviceluks rd.luks.key=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX=/device-disk.key:LABEL=keydisk intel_iommu=on

The keyfile named `device-disk.key` is located on an extermal USB memory stick with a single partition with the label `keydisk`.

Once dropped into the emergency shell by dracut, performing `ls -l` on `/run/systemd/cryptsetup/keydev-deviceluks/` indicated the directory was mounted and the keyfile was readable.

Output of `systemctl status systemd-cryptsetup@deviceluks.service` from the emergency shell:

```
● systemd-cryptsetup@deviceluks.service - Cryptography Setup for deviceluks
   Loaded: loaded (/etc/crypttab; generated)
   Active: failed (Result: exit-code) since Thu 2019-11-21 11:55:12 UTC; 18min ago
     Docs: man:crypttab(5)
           man:systemd-cryptsetup-generator(8)
           man:systemd-cryptsetup@.service(8)
  Process: 408 ExecStart=/lib/systemd/systemd-cryptsetup attach deviceluks /dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX /run/systemd/cryptsetup/keydev-deviceluks/device-disk.key discard (code=exited, status=1/FAILURE)
 Main PID: 408 (code=exited, status=1/FAILURE)

Nov 21 11:55:12 device systemd[1]: Starting Cryptography Setup for deviceluks...
Nov 21 11:55:12 device systemd-cryptsetup[408]: Key file /run/systemd/cryptsetup/keydev-deviceluks/device-disk.key is world-readable. This is not a good idea!
Nov 21 11:55:12 device systemd-cryptsetup[408]: WARNING: Locking directory /run/cryptsetup is missing!
Nov 21 11:55:12 device systemd-cryptsetup[408]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.
Nov 21 11:55:12 device systemd-cryptsetup[408]: Failed to activate with key file '/run/systemd/cryptsetup/keydev-deviceluks/device-disk.key': No such file or directory
Nov 21 11:55:12 device systemd[1]: systemd-cryptsetup@deviceluks.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 11:55:12 device systemd[1]: systemd-cryptsetup@deviceluks.service: Failed with result 'exit-code'.
Nov 21 11:55:12 device systemd[1]: Failed to start Cryptography Setup for deviceluks.
```
The actual unit file generated by systemd:
```
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/run/systemd/cryptsetup/keydev-deviceluks/device-disk.key
BindsTo=dev-disk-by\x2duuid-XXXXXXXX\x2dXXXX\x2dXXXX\x2dXXXX\x2dXXXXXXXXXXXX.device
After=dev-disk-by\x2duuid-XXXXXXXX\x2dXXXX\x2dXXXX\x2dXXXX\x2dXXXXXXXXXXXX.device
Before=umount.target

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/lib/systemd/systemd-cryptsetup attach 'deviceluks' '/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' '/run/systemd/cryptsetup/keydev-deviceluks/device-disk.key' 'timeout=0'
ExecStop=/lib/systemd/systemd-cryptsetup detach 'deviceluks'
ExecStartPost=/bin/umount /run/systemd/cryptsetup/keydev-deviceluks

```
The logs above show a line:

    Key file /run/systemd/cryptsetup/keydev-deviceluks/device-disk.key is world-readable. This is not a good idea!

indicating that to some capacity, systemd is able to read the key-file.

Attempting to start the service again in the emergency shell fails with the same error.
Attempting to directly call `systemd-cryptsetup` with the same parameters fails with the same error.

Attempting to start the service again with an invalid keyfile (i.e. non-existent file) results in a different error, namely the message:

    Failed to activate with key file '/run/systemd/cryptsetup/keydev-deviceluks/device-disk.key.1': Invalid argument

This bug was initially reported [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945208) on the Debian bug tracker but I was told to post it upstream instead.

**Comment by poettering** [comment]
my educated guess is that the error msg is just misleading, and your initrd might miss some kmods necessary for cryptsetup to work, for example the right AES crypto modules or so? the kernel isn't particularly helpful when it misses something, and returns ENOENT in a couple of different, unrelated cases, so it's hard to know what really is going on

**Comment by initramfs** [comment]
Turns out @poettering was indeed correct, a kernel module was missing due to the specific way I performed installation.

For reference the missing kernel modules were `af_alg` and `alg_skcipher` which prohibits cryptsetup from being able to use `aes-xts-plain64` and failing out with `ENOENT`.

Thanks again.

**Comment by MoonSweep** [comment]
Hi, sorry for noecroposting...

I'm struggling with a very similar problem (except I use `initramfs-tools` instead of `dracut`) : `systemd-cryptsetup` works fine in booted system but not in the initramfs. 

@initramfs How did you debug to find which modules were missing ?

**Comment by Isopod** [comment]
Sorry for another necropost, but I just had the same problem here in 2026 because I followed the guide in the Arch wiki which uses `cipher=aes-xts-plain64` everywhere for some reason. I tried every trick in the book and still got obscure errors like

```
Jan 21 20:01:39 arch systemd[1]: Starting Cryptography Setup for swap...
Jan 21 20:01:39 arch systemd-cryptsetup[493]: Set cipher cipher=aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-partuuid/[...].
Jan 21 20:01:39 arch systemd-cryptsetup[493]: device-mapper: reload ioctl on swap (253:2) failed: No such file or directory
Jan 21 20:01:39 arch systemd-cryptsetup[493]: The device size is not multiple of the requested sector size.
Jan 21 20:01:39 arch systemd-cryptsetup[493]: Failed to activate with key file '/dev/urandom': Invalid argument
Jan 21 20:01:39 arch systemd[1]: systemd-cryptsetup@swap.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 20:01:39 arch systemd[1]: systemd-cryptsetup@swap.service: Failed with result 'exit-code'.
Jan 21 20:01:39 arch systemd[1]: Failed to start Cryptography Setup for swap.
```

Adding the modules `af_alg` and `algif_skcipher` to my `mkinitcpio.conf` as suggested in a comment here did not help, either. I was sitting here cursing for hours. Tried every partition scheme I could think of. Tried UUIDs, PARTUUIDs, various /dev/ paths, LABELS, various partition formats, tried using a hardcoded key just to rule out `/dev/urandom` as a culprit. Nothing helped.

Then I changed the cipher to the default one that's commented out in the default `/etc/crypttab`, `aes-cbc-essiv`:

```
# swap      /dev/sdx4     /dev/urandom    swap,cipher=aes-cbc-essiv:sha256,size=256
```

And voilà, everything suddenly worked out of the box 😓. Not even any special kernel modules needed.

Frankly, I don't even know what the exact difference between those two cipher modes is and which one is preferable. I'm not generally a big fan of CBC, but I don't even know what XTS *is* exactly, except that it seems to be used by most full disk encryptions (but is slowly being superseded by AES-GCM, I think, which I at least understand somewhat).

I was also wondering: Is `/dev/urandom` really safe for this purpose or should we be using `/dev/random` instead, since this is used quite early during boot where the system has not had much chance to gather entropy? Well, I replaced it at least on my system, seems safer to me. Haven't noticed any negative effects on boot time or otherwise.
