### ISSUE TITLE
ExecStartPre exec twice when systemctl daemon-reload

### ISSUE THREAD

**Issue by liuliqiang** [systemd/systemd#14097]
**systemd version the issue has been seen with**
> $ systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Expected behaviour you didn't see**
 > systemd running service with old configs

**Unexpected behaviour you saw**
 > systemd running with new config and run ExecStartPre twice

**Steps to reproduce the problem**

### 1. service file

```
# systemctl cat test
# /usr/lib/systemd/system/test.service
[Unit]
After=network.target

[Service]
ExecStartPre=/bin/test -f /tmp/txt
ExecStartPre=/bin/sh /tmp/test00.sh
ExecStartPre=/bin/sh /tmp/test01.sh
ExecStart=/bin/sh /tmp/run.sh
```

### 2. scripts 

```
# cat /tmp/test00.sh 
echo "i am test00, begin"
sleep 30
echo "i am test00, end"
# cat /tmp/test01.sh 
echo "i am test01, begin"
sleep 1
echo "i am test01, end"
# cat /tmp/run.sh 
while :
do
    sleep 1
done
```

#### Terminal 1

```
# service test start
```
and quickly goto terminal 2  

#### Terminal 2

```
# touch /tmp/txt
# systemctl daemon-reload
```

### 4. result

After 1 minute , check the logs of service `test`: 

```
# systemctl status test
... ...
   CGroup: /system.slice/test.service
           ├─195920 /bin/sh /tmp/run.sh
           └─199100 sleep 1

Nov 21 14:16:28 host-69 systemd[1]: Starting test.service...
Nov 21 14:16:28 host-69 sh[194539]: i am test00, begin
Nov 21 14:16:58 host-69 sh[194539]: i am test00, end
Nov 21 14:16:58 host-69 sh[195344]: i am test00, begin
Nov 21 14:17:28 host-69 sh[195344]: i am test00, end
Nov 21 14:17:28 host-69 sh[195886]: i am test01, begin
Nov 21 14:17:29 host-69 systemd[1]: Started test.service.
Nov 21 14:17:29 host-69 sh[195886]: i am test01, end
```

It happen.

**Comment by yuwata** [comment]
> systemd 219

It's too old here... Please test with v243 or v242, or current git master.
