### ISSUE TITLE
systemctl suspend instantly turns off Dell Latitude 7490

### ISSUE THREAD

**Issue by przemub** [systemd/systemd#14106]
**systemd version the issue has been seen with**
```
systemd 243 (243.162-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
`systemctl suspend` should move the computer (Dell Latitude 7490) to the suspended state.

**Unexpected behaviour you saw**
The computer suddenly turns off. The last entries in journalctl are:
```
Nov 21 20:10:43 ami systemd[1]: Starting Suspend...
Nov 21 20:10:43 ami systemd-sleep[1462]: Suspending system...
Nov 21 20:10:43 ami kernel: PM: suspend entry (deep)
```

**Steps to reproduce the problem**
Run `systemctl suspend`.

**Additional info**
BIOS upgrade does not solve the issue. It occurs with Linux 4.14, 4.19 and 5.3. A similar issue was reported in the forums with Dell XPS 15 9530: https://bbs.archlinux.org/viewtopic.php?id=243364

Full logs: [suspend_journalctl.txt](https://github.com/systemd/systemd/files/3876935/suspend_journalctl.txt)

**Comment by poettering** [comment]
Hmm, so it appears systemd is doing the right thing here, as the kernel entered suspend on its behalf, but apparently you cannot get the system back from suspend? If so, it's something between the kernel and firmware of your laptop, systemd is out of control at that point.

Please contact your kernel community (distro or upstream) about this, from systemd's side we cannot help there anymore. Sorry.
