### ISSUE TITLE
networkd: Change IPForward= default to "kernel"

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1411]
Currently networkd defaults to setting `/proc/sys/net/ipv4/conf/<iface>/forwarding` to 0 unless you explicitly add `IPForward=kernel` to the `.network` config file. This is a rather inconvenient default as it breaks firewall scripts and related "global" configuration which usually sets `/proc/sys/net/ipv4/ip_forward` to 1 and expect it to be respected. But by explicitly changing the per-interface config to 0 by default this breaks forwarding.

It seems to me that `IPForward=kernel` would be a better default, in the spirit of "don't change system configuration unless explicitly configured". I'd hate to change this downstream only, as it's by far not distro specific.

@teg, if you generally agree, I'll send a PR for adjusting the default and documentation.

(Reported by @stgraber via https://launchpad.net/bugs/1500992)

**Comment by mischief** [comment]
coreos submitted a bug a long time ago about this at https://bugs.freedesktop.org/show_bug.cgi?id=89509.

coreos now carries a patch to use IPForwarding=kernel by default https://github.com/coreos/systemd/commit/a38567ccac098f3bae0fa88be9ac37d0ce486a6b, since we needed to maintain backward compatibility with sysctl setting ipforwarding to on.

**Comment by martinpitt** [comment]
Thanks @mischief . In that bug it seems @teg wasn't keen on changing the default to "kernel", but not doing so is too intrusive for us too; so I'll pull that into the Debian/Ubuntu packages if we can't apply it upstream.

**Comment by poettering** [comment]
Sorry, but no. I think if you pass control of an interface to networkd, then networkd should manage it in full. And that certainly includes managing the per-interface ip forwarding state. 

I think for the sake of security we should really stop thinking about the global ip forwarding bool and strictly encourage use of the per-interface one, and that managed by networkd. And the usual policy regarding security is to forbid what isn't explicitly allowed, hence the setting in the .network files needs to default to off.

The kernel global default will still apply to all interfaces not managed by networkd, and that's good that way. But if you let networkd manage an interface, then expect to manage it in full: we'll not just reset this setting but many others too, starting from IP configuration, to basic things like the up/down state and so on. It's just wrong to exclude on single setting from this, just because of some old firewall scripts. Consider fixing this and the assumptions they make instead.

So, no, this should not get merged. You can of course do whatever you want downstream, but I would encourage to not change this downstream in order to avoid further confusion, and mismatch with documentation.

**Comment by martinpitt** [comment]
@stgraber, WDYT?

**Comment by martinpitt** [comment]
@stgraber and I discussed this on IRC. Summary:
- LXC or similar packages need some way to enable forwarding programmatically. Right now, init scripts/units do that with `echo 1 > /proc/sys/net/ipv4/ip_forward` style.b
- From my side I don't want to deviate from the current status, as this would be an eternal change from upstream, and more importantly it's against the spirit of "put your interfaces in an explicit and defined state".

We could introduce a packaging helper script like `enable-ip-forwarding` which would do the above echo for all `/proc/sys/net/ipv{4,6}/conf/<iface>/forwarding` to apply this immediately, and create a `/run/systemd/network/00_enable_forwarding.network` with `[Network]\nIPForward=yes`. Init scripts/units would then call that if they need to.

This provides the semantics that these packages needs without having to compromise/change the default behaviour of networkd.

Opinions?

**Comment by poettering** [comment]
@martinpitt but why would LXC do that for other interfaces? it should do that on its own interfaces, that's all...

**Comment by stgraber** [comment]
Because forwarding must be set on the outgoing interface too.

**Comment by poettering** [comment]
but well, that's really something that the network management solution that is managing those external interfaces should decide on. turning this on for everybody seems wrong, in particular since the global setting undoes the per-interface ones iirc: hence you break the system of people who want to control the forwarding stuff per interface...

**Comment by martinpitt** [comment]
The global `/proc/sys/net/ipv4/ip_forward` is merely providing the default, like `/proc/sys/net/ipv4/conf/default/forwarding`; it doesn't trump per-device config like `/all/forwarding`, this is the reason why this issue popped up in the first place.

Apparently if you install a container and want to use forwarding, you indeed need to enable that on the host's outgoing interface for it to actually work. I suppose it could be a bit more clever than enable it for all devices, but just enable forwarding on the one which is currently providing the default route. That still won't work well if you use alternative ways to get online.

> hence you break the system of people who want to control the forwarding stuff per interface...

I thought that if a particular `.network` config file set s `IPForward=`, this will be respected; i. e. `zz_enable_forwarding.network` (not `00_` as I originally wrote) merely provides a fallthrough default for `.network` definitions which don't explicitly set it. At least this seems to work reasonably well in my experiments.

**Comment by martinpitt** [comment]
FTR, I was fooled by networkd not actually dropping existing IP addresses on an interface on restart -- if you do `00_enable_forwarding.network` with just `[Network]\nIPForward=true`, then all real `*.network` files stop being respected (in particular, `DHCP=yes`). And if you use `zz_*` then this will not actually be read. I. e. it appears like `*.network` files are not actually additive in that way, there is only exactly one file which applies to a set of interfaces. Thus with networkd you can't currently have separate files which set options which you want to apply to all of your interfaces.

We really don't want to go and modify existing `*.network` files to add `IPForward=yes` programmatically. We can't also modify the particular one for the default route only (if that would even make sense for the use case above), as a `*.network` file can very well apply to multiple interfaces. Without the feature above (additive `*.network`) I'm afraid there is no clean way to globally enable IP forwarding.

So we are back to 
- patching the default to `IPForward=kernel`, or
- asking admins to "please modify all relevant `*.network` files to add `IPForward=yes` in order to use containers (but that sounds like a no-go), or
- use a `systemd-networkd.service` drop-in to reapply `echo 1 > /proc/sys/net/ipv4/conf/all/forwarding` on restart (but that doesn't catch hotplugged interfaces managed by networkd).

Of these, I figure the CoreOS patch to default to `kernel` together with an according manpage update still feels like the least bad thing. If/when `*.network` configs become a bit more flexible in the future we still retain the option to drop that patch at least.

**Comment by joshtriplett** [comment]
Given the suggestion of discouraging the global option in favor of per-interface options, would it be reasonable for networkd to check the global ip_forward setting and emit a warning if that option is set but a .network file doesn't have an _explicit_ IPForward setting?  That would quickly tell admins why their forwarding configuration doesn't work, and point them directly to the setting that needs fixing.

**Comment by martinpitt** [comment]
Even with such a warning, this isn't really something which you can "sell" to people. So far packages or projects were able to enable IP forwarding programmatically. With current networkd there is no way to do this, so starting to ask users "please set IPForward=yes in all `*.network` files" isn't exactly friendly.

**Comment by poettering** [comment]
@stgraber well, those outgoing ifaces should set it to "on" then, or even "kernel", but should do that explicitly. I am pretty sure the defaults should be secure, and if packet forwarding is enabled for an interface, then it should be done so explicitly. Now whether you explicitly enable if via "on", or via "kernel" is just a matter of implementation: the former really enables it, the latter just says "set it to the globally configured default"...

**Comment by poettering** [comment]
@martinpitt iirc networkd is a very very recent addition to ubuntu is it not? I am not sure why it would matter at all, to ask people to set "IPForward=1" for all interfaces they want traffic to leak into the local containers from... It's not that you have a huge body of systems where suddenly something was broken...

**Comment by poettering** [comment]
@joshtriplett yeah, i am open to adding such warnings.

**Comment by joshtriplett** [comment]
@poettering Should I open a separate issue for that?

**Comment by martinpitt** [comment]
Lennart Poettering [2015-10-06  6:14 -0700]:

> I am not sure why it would matter at all, to ask people to set
> "IPForward=1" for all interfaces they want traffic to leak into the
> local containers from... It's not that you have a huge body of
> systems where suddenly something was broken...

No, this isn't an upgrading problem for sure. Just a "this used to be
all automatic and now it needs to be done manually" change, which
currently make networkd harder to use than ifupdown or NM. I do see
why networkd wants to default to secure settings, but without a
programmatic interface to change them there is zero integration
possibility with other packages/projects.
