### ISSUE TITLE
Can't prune /dev without losing CAP_SYS_RAWIO

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#14117]
**Is your feature request related to a problem? Please describe.**
I can't find a solution for dropping unwanted devices from `/dev`, or creating a new minimal `/dev` tree without losing `CAP_SYS_RAWIO`. I'd like to harden smartmontools wrt. `/dev`, but it needs access to block devices and also needs the capability.

**Describe the solution you'd like**
Allow overriding hard-coded logic for `/dev` and/or `CAP_SYS_RAWIO`.

**Describe alternatives you've considered**
`PrivateDevices=yes` drops `CAP_SYS_RAWIO`. It would be possible to complete the directory with `BindPaths=/dev/sda /dev/sdb`.

`TemporaryFileSystem=/dev:dev,noexec,nosuid,ro` and` BindPaths=/dev/null /dev/sda /dev/sdb` does not work. In this alternative `CAP_SYS_RAWIO` can be retained.

**Comment by topimiettinen** [comment]
Third alternative I tested is to use `RootImage=` with suitably populated `/dev` (and other needed files) and `MountAPIVFS=no`. However, `/dev` from host is always mounted for some reason. For this alternative, a solution could be a new setting `MountAPIVFS=really-no` which doesn't force host `/dev`.

**Comment by topimiettinen** [comment]
I found a workaround that `BindReadOnlyPaths` can be used to mount an existing device directory over `/dev`. This works for both `RootImage=` and using system root.

For the system root case, the paths which are mounted over are not pruned for some reason:
```
1133 1132 0:6 / /dev rw,nosuid,noexec,relatime - devtmpfs udev rw,size=8168120k,nr_inodes=2042030,mode=755
1135 1133 0:20 / /dev/pts ro,nosuid,noexec,relatime - devpts devpts ro,gid=5,mode=620,ptmxmode=000
1140 1133 0:22 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw
1141 1133 0:40 / /dev/hugepages rw,nosuid,nodev,noexec,relatime - hugetlbfs hugetlbfs rw,pagesize=2M
1425 1133 0:18 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
2159 1133 7:0 / /dev ro,nosuid,noexec,noatime - squashfs /dev/loop0 ro
```
vs. `RootImage=`
```
1132 928 7:1 / / ro,nodev,relatime - squashfs /dev/block/7:1 ro
1133 1132 7:0 / /dev ro,nosuid,noexec,noatime - squashfs /dev/loop0 ro
```

Perhaps `RootImage` should also mount new root as `nosuid`, or maybe there should be a new option `RootImageMountFlags`. Or even more generic: complement `ReadOnlyPaths`/`ReadWritePaths` with `NoSUIDPaths` / `SUIDPaths` to make arbitrary paths `nosuid`/`suid` (also `NoExecPaths`/`ExecPaths` for `noexec`/`exec`).

**Comment by poettering** [comment]
Can this even work? I mean block devices come and go all the time, we live in a hotplug world after all... A statically configured list is unlikely going to be anything but a locally feasible... Wouldn't DeviceAllow=block-* the better approach?

**Comment by topimiettinen** [comment]
In this case, I'm not so interested in smart status of removable devices I happen to plug, so I can limit this to `/dev/sda` and `/dev/sdb`.

Isn't `DeviceAllow` also going away with cgroupsv2?

**Comment by poettering** [comment]
It's available already on cgroupsv2, implemented via BPF.

**Comment by topimiettinen** [comment]
What about the mount flags for `RootImage`, should I open another issue or can you comment on preferred solution here?
