### ISSUE TITLE
kernel-install: Allow installation of files to $XBOOT without $MACHINE_ID in directory name

### ISSUE THREAD

**Issue by t-8ch** [systemd/systemd#14115]
**Is your feature request related to a problem? Please describe.**

We want to create a virtual machines that use the kernel-install infrastructure to manage their kernel image lifecycle.
These machines will be instantiated from a template.

During the setup of the template kernel-install will install kernels to `/efi/$MACHINE_ID/...`, with the templates machine-id.
The machines however should all get random machine-ids at their first boot.

This creates a mismatch between the persisted machine-id of the template and the newly generated of the VM itself.

The template itself is never booted, so if kernel-install does not need machine-id during template creation time will remove the necessity of every writing it into the template.

**Describe the solution you'd like**

A possibility to inhibit the creation of a subdirectory based on the machine-id.
Instead a generic subdirectory should be chosen.
These virtual machines will never have more than one operating system installed.

As an addition having the option of freely choosing the subdirectory name would provide even more flexibility.

**Describe alternatives you've considered**

Not using kernel-install:
* We will have to switch to a different bootloader or rebuild the integration with the packaging system ourselves.

Leaving the kernel installed with the template machine-id:
* Will be confusing
* kernel-install won't be able to uninstall the loader directory on kernel uninstallation, because the calculated directory won't exist.

**Comment by t-8ch** [comment]
This will probably also need changes in `bootctl` not to require the machine id during install.
It would be fairly easy to work around that for our usecase though.

Related to #12363

**Comment by t-8ch** [comment]
Given this was not tagged "needs-discussion" would this feature have chances of getting merged if I implemented it?

**Comment by poettering** [comment]
I guess we can close this now that #16687 + #16777 are merged.
