### ISSUE TITLE
Possible Documentation Issues

### ISSUE THREAD

**Issue by SJrX** [systemd/systemd#14126]
> v244-rc

**Used distribution**
> N/A

**Expected behaviour you didn't see**
 > Documentation for CPUSetsMems and CPUSetCpus

**Unexpected behaviour you saw**
 > No documentation

**Steps to reproduce the problem**
1) Checkout master/v244-rc
2) grep codebase for CPUSetMem / CPUSetCpus
```
grep -R CPUSetMem *
src/core/load-fragment-gperf.gperf.m4:$1.CPUSetMems,                   config_parse_cpuset_mems,           0,                             offsetof($1, cgroup_context)
```

3) No reference in any documentation (also I'm not sure if the properties actually do anything, since I don't see any reference in any code).

**Comment by SJrX** [comment]
This seems to have been introduced here: https://github.com/systemd/systemd/pull/13481/files

**Comment by boucman** [comment]
I don't know about that particular property, but systemd removes deprecated properties from the documentation while keeping them in the code for backward compatibility...

**Comment by SJrX** [comment]
Yeah these were merged in 3 months ago, so I'm not sure if that's it.
