### ISSUE TITLE
networkd: [Route] Type=local should default to Table=local

### ISSUE THREAD

**Issue by pyropeter** [systemd/systemd#14122]
**systemd version the issue has been seen with**
> systemd 243 (243.162-2-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**

Routes created with `Type=local` should be added to table 255 (local) by default. This would mimic the behavior of `ip-route(8)`. (This also applies to types `broadcast`, `nat` and `anycast`, as can be seen in [the code](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/ip/iproute.c#n1523), but not in the manual page, which is incorrect.)

Routes with `Type=local` added to the main table seem to be dropped by the kernel.

**Unexpected behaviour you saw**

The routes are added to the main table unless `Table=255` is explicitly specified.

Please note that this is the documented behavior (well done, thanks!), so the documentation needs to be updated as well if this is fixed.

**Steps to reproduce the problem**

Add something like the following to an existing `.network` file:

> [Route]
> Destination=2001:db8::/32
> Type=local

The debug logging claims that the route was created, but `ip -6 r` will not show it, nor will addresses within the prefix be considered local (can e.g. be checked by pinging them; they should appear to be loopback addresses).

**Comment by pyropeter** [comment]
For some reason the required code [already exists](https://github.com/systemd/systemd/blob/master/src/network/networkd-route.c#L1497), but is restricted to handling IPv4 routes?! It was introduced by #13031. @yuwata could you explain?

Also, this means the documentation is wrong at the moment.

**Comment by yuwata** [comment]
If I remember correctly, the behavior is taken from `ip` command.

**Comment by yuwata** [comment]
Hmm. Maybe I was wrong. See [here](https://salsa.debian.org/debian/iproute2/blob/master/ip/iproute.c#L1513). I will update that.
