### ISSUE TITLE
Running "sudo udevadm trigger -s input" results in touchpad configuration being reset

### ISSUE THREAD

**Issue by jroovy** [systemd/systemd#14123]
**systemd version the issue has been seen with**
> Systemd 243.162

**Used distribution**
 > Arch Linux, KDE Plasma 5.17.3
> Kernel 5.3.11-arch1-1, x86_64

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > Touchpad behavior in Plasma Desktop is reset to defaults

**What caused this issue**
> Using KDE's Partitionmanager to modify partitions caused this issue since the debug info provided here: https://bugs.kde.org/show_bug.cgi?id=413973 shows that Partitionmanager runs `udevadm trigger` as root which in turn caused this touchpad issue

**Steps to reproduce the problem**
1) Open KDE Plasma's touchpad configuration dialog
2) Enable tap-to-click and inverse scrolling and apply changes
3) Run "sudo udevadm trigger -s input"
4) Touchpad behavior is reset back to defaults (tap-to-click disabled, scrolling uninversed)

**System specs**
>  Lenovo Ideapad 320 (2016)
> Intel i5-7200U
> Elan touchpad (based on the vendor-provided Windows touchpad drivers)

**Comment by poettering** [comment]
well, it's probably libinput or KDE which resets the settings on a "change" uevent. @whot any idea?

I doubt this is an upstream systemd issue though, and we should probably close that here hence.

**Comment by poettering** [comment]
(that partitionmanager really shouldn't trigger the whole system though. That's just a bad idea, and not necessary)

**Comment by whot** [comment]
libinput doesn't do anything with the "change" signal, [we only handle add/remove](https://gitlab.freedesktop.org/libinput/libinput/blob/master/src/udev-seat.c#L176). So this must be somewhere within KDE.

**Comment by poettering** [comment]
Anyway, let's close this here. Please report to KDE.
