### ISSUE TITLE
RHEL8 no longer has btrfs. machinectl requires btrfs.

### ISSUE THREAD

**Issue by fignew** [systemd/systemd#14130]
**systemd version the issue has been seen with**
> 239 (up to current)

**Used distribution**
 > RHEL8

**Expected behaviour you didn't see**
 > machinectl creates container

**Unexpected behaviour you saw**
 > no container. Error about btrfs-tools missing (In addition to kernel module)

**Steps to reproduce the problem**
* Run Lennart's employer's latest stable OS ;)

Also see bug #7776

**Comment by refi64** [comment]
What command did you run? Afaik machinectl itself doesn't require btrfs
depending on how the container is being stored.

**Comment by fignew** [comment]
Hi Refi64,

Please see #7776. machinectl pull-tar is (one of)(?) the commands that requires BTRFS

Quote from Lennart in that thread:

> I think we should probably just drop the logic for this sooner or later. newer xfs has reflinks which isn't as good as proper subvol support but should get us close enough so that the benefits of btrfs there aren't clear enough to do the loop device logic...

**Comment by shibumi** [comment]
@fignew this is not true. I run arch linux on EXT4 and I can pull-tar any other tarball that comes with EXT4 filesystem. works fine for me.

systemd-machined will only use btrfs, if possible, for saving disk space due to snapshotting etc

**Comment by vcaputo** [comment]
From machinectl(1)
```
       Note that many image operations are only supported, efficient or atomic
       on btrfs file systems. Due to this, if the pull-tar, pull-raw,
       import-tar, import-raw and set-limit commands notice that
       /var/lib/machines is empty and not located on btrfs, they will
       implicitly set up a loopback file /var/lib/machines.raw containing a
       btrfs file system that is mounted to /var/lib/machines. The size of
       this loopback file may be controlled dynamically with set-limit.
```

**Comment by shibumi** [comment]
Here, is a successful `pull-tar` without btrfs-progs:
```
chris motoko ~ 11:46:02 05e05f6a master  
❯ sudo machinectl list-images
No images.
chris motoko ~ 11:46:06 05e05f6a master  
❯ sudo pacman -Ss btrfs-progs
core/btrfs-progs 5.3.1-3
    Btrfs filesystem utilities
chris motoko ~ 11:46:24 05e05f6a master  
❯ sudo pacman -Ss swaylock
community/swaylock 1.4-2 [installed]
    Screen locker for Wayland
chris motoko ~ 11:46:28 05e05f6a master  
❯ sudo nspawn init fedora/30/tar
chris motoko ~ 11:48:06 05e05f6a master  
❯ sudo machinectl list-images
NAME          TYPE      RO USAGE CREATED MODIFIED
fedora-30-tar directory no   n/a n/a     n/a     

1 images listed.
chris motoko ~ 11:48:36 05e05f6a master  
❯ 

```

Note: `nspawn` is a small shell wrapper, written by me that pulls tar images via `machinectl pull-tar` from https://nspawn.org

**Comment by keszybz** [comment]
Some operations that are only possible on btrfs require btrfs, but otherwise it is optional. If you think RHEL should support btrfs, please open a support ticket in Red Hat's bugzilla. This is not something that the upstream systemd project has any influence over.
