### ISSUE TITLE
ERROR: Neither directory contains a build file meson.build.

### ISSUE THREAD

**Issue by Ankele** [systemd/systemd#14136]
**systemd version the issue has been seen with**
> in tag v219

**Used distribution**
 > fedora31   5.3.7-301.fc31.x86_64

**Expected behaviour you didn't see**
 > Execute command `meson build` normally

**Unexpected behaviour you saw**
 > result in "ERROR: Neither directory contains a build file meson.build."

**Steps to reproduce the problem**
compile `systemd` and execute `meson build`  in my Fedora31 virtual machine
has executed `dnf builddep systemd ` and `dnf install mkosi`
then edit my target file src/cryptsetup/cryptsetup.c
and executed `meson build`
but I got 
> ERROR: Neither directory contains a build file meson.build.

**Comment by boucman** [comment]
wasn't 219 before systemd switched to meson ?

anyway... v219 is ancient and not supported upstream. If you have trouble building this, please open a bug on the fedora forums...

**Comment by Ankele** [comment]
Thanks boucman, and I am sorry for my mistake, I want the compiled systemd to run on CentOS7.5。CentOS7.5 systemctl --version is v219.
