### ISSUE TITLE
networkd link Duplex inverted

### ISSUE THREAD

**Issue by iangehc** [systemd/systemd#14144]
Duplex=full in .link file is programmed as half, and vice-versa.

Function ethtool_set_glinksettings does not map enum Duplex to the linux/ethtool.h enumeration used by the SIOCETHTOOL ETHTOOL_GLINKSETTINGS ioctl.

Compare:
```
        if (duplex != _DUP_INVALID)
                u->base.duplex = duplex;

```
With ethtool_set_speed:
```
        switch (duplex) {
                case DUP_HALF:
                        if (ecmd.duplex != DUPLEX_HALF) {
                                ecmd.duplex = DUPLEX_HALF; 
                                ...
```

**Comment by poettering** [comment]
I guess fixed already in 9432a05c541d64e807949c416604cc04f4107307, right @ssahani
