### ISSUE TITLE
compile systemd/cryptsetup/cryptsetup.c

### ISSUE THREAD

**Issue by Ankele** [systemd/systemd#14143]
**systemd version the issue has been seen with**
> v219

**Used distribution**
 > CentOS7.6 kernel 3.10.0-957.el7.x86_64

**Expected behaviour you didn't see**
 > compile it successfully

**Steps to reproduce the problem**
I will modify the source cryptsetup.c to programmatically enter the password before the root partition is mounted rather than manually.
I want to know how to compile it correctly with gcc or ninja.

**Comment by yuwata** [comment]
Please use ./configure and make (if I remember correctly).

Anyway, v219 is too old here. Please use the mailing list.

**Comment by poettering** [comment]
Sorry, we only track issues in current systemd versions here (242 and v241 right now). Also please use the mailing list

**Comment by poettering** [comment]
hehe, @yuwata we both did the same thing the same time ;-)
