### ISSUE TITLE
OnFailure for scopes does not make sense

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#14142]
**systemd version the issue has been seen with**
> systemd-241-12.git323cdf4.fc30.x86_64

**Used distribution**
 > Fedora

You can set OnFailure as a property in systemd-run. But systemd never considers scopes as failed. So the unit will never be started.

**Steps to reproduce the problem**

`# systemd-run -p OnFailure=fail.service --scope /bin/sleep 30000`

**Comment by poettering** [comment]
yeah, we should refuse such deps to be configured. And similar for various other dep types, such as JoinsNamespaceOf=

**Comment by poettering** [comment]
Actually OnFailure= does make sense on scope units, as they do have a failure state. However, that failure state is only reached if we can#t allocate the cgroup or so, but not when the main process of the scope ideas (like it does for services), for the simple reason that there is no "main" process defined for scope units.

Will add documentation for that, and prep a patch that ensures that units that really know no failure state (such as targets) will not be allowed to have OnFailure= deps.

**Comment by poettering** [comment]
Fix waiting in #14505

**Comment by jlebon** [comment]
> Will add documentation for that, and prep a patch that ensures that units that really know no failure state (such as targets) will not be allowed to have OnFailure= deps.

Hmm, though this did work, right? We've been using `OnFailure=` in our target units for a while and it would fire whenever any unit which is required by the target failed. Is there a way to express this now? Or do we have to pepper `OnFailure=` in all the member units?

**Comment by dustymabe** [comment]
I'd like to know as well.

**Comment by geissonator** [comment]
> Hmm, though this did work, right? We've been using OnFailure= in our target units for a while and it would fire whenever any unit which is required by the target failed. Is there a way to express this now? Or do we have to pepper OnFailure= in all the member units?

Yeah, a little late to the party here but this was a pretty common use case for us over in OpenBMC world. Put a bunch of services in a target. Some with a required relationship and some with a wants. If any of the required services failed, the target would fail, and start a different target for recovery.

**Comment by geissonator** [comment]
Having this discussion in a closed issue probably doesn't help with responses so I opened up a feature request via https://github.com/systemd/systemd/issues/16778 to see if we can get any more discussion going.

**Comment by keszybz** [comment]
This was already partially reverted in 94d1ddbd7cd15b1073757eb5ae0645c83f0b414c. Targets were failing before, and now they can fail again.
