### ISSUE TITLE
test-libudev fails when the loopback device has a randomized mac address

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#14152]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > debian

**Expected behaviour you didn't see**
 > test-libudev should succeed

**Unexpected behaviour you saw**
 > test-libudev fails:

```
418/528 test-libudev                            FAIL     0.57 s (killed by signal 6 SIGABRT)
[…]
"[net/lo]hoge" → expect: "", 0, actual: "", 0
"[net/lo]/hoge" → expect: "", 0, actual: "", 0
"[net/lo]address" → expect: "00:00:00:00:00:00", 0, actual: "92:15:8e:33:cb:a3", 0
Assertion 'streq(result, expected)' failed at src/test/test-libudev.c:411, function test_util_resolve_subsys_kernel_one(). Aborting.
-------
```

**Steps to reproduce the problem**

I think the reason this VM has this odd configuration is that i have the following in `/etc/systemd/network/99-default.link`

```
[Link]
MACAddressPolicy=random
```

You could also probably reproduce it by manually setting the loopback device's hwaddr (e.g. `ip link set lo address 12:34:56:78:9a:bc`).  (but be warned, it might be impossible to set it back to `00:00:00:00:00:00` -- when i try to manually reset it, `ip` complains: `RTNETLINK answers: Cannot assign requested address`)

**Comment by poettering** [comment]
weird, maybe for safety reasons we should just refuse changing the MAC of the loopback device. This sounds like something that happens by accident, not on purpose.

**Comment by yuwata** [comment]
How about changing the name "lo"? Or, mtu? I mean [link_config_apply()](https://github.com/systemd/systemd/blob/6eee88577ddf9e3d7f8d3298fca596b52f9017a0/src/udev/net/link-config.c#L326) should return earlier for "lo" or only refuse changing mac address.

**Comment by poettering** [comment]
we hardcode the name of the loopback device, and yeah, if it can be changed we should refuse that too I guess...

**Comment by dkg** [comment]
fwiw, this still appears to be the case on master, which makes it more difficult to develop on a system where `MACAddressPolicy=random`, or where the user has set the MAC address manually to something else.  I'm not asking for `udev` to special case the loopback: i'm asking for the test suite to be more robust.

**Comment by yuwata** [comment]
The commit 70f32a260b5ebb68c19ecadf5d69b3844896ba55 makes loopback interfaces not configured by .link files. Closing.
