### ISSUE TITLE
Multiple DynamicUser with the same StateDirectory produces permission denied

### ISSUE THREAD

**Issue by zonggen** [systemd/systemd#14158]
**systemd version the issue has been seen with**
- systemd 243 (v243-4.gitef67743.fc31)

**Used distribution**
 - Fedora30

**Expected behaviour you didn't see**
 - Multiple instances of `DynamicUser=yes` should be able to share the same `StateDirectory=`

**Unexpected behaviour you saw**
 - If the state directory already exists, the second dynamic user process would fail with permission denied error, even if the first dynamic user process exits.

**Steps to reproduce the problem**
```
$ sudo systemd-run --pty --property=DynamicUser=yes --property=StateDirectory=wuff /bin/sh
Running as unit: run-u32.service
Press ^] three times within 1s to disconnect TTY.
sh-4.4$
[CTRL+D]

# This will fail with permission error since /var/lib/wuff already exists
$ sudo systemd-run --pty --property=DynamicUser=yes --property=StateDirectory=wuff /bin/sh
```
`LogsDirectory=` however would work nicely with `DynamicUser=yes` on the same example and there's no permission issues.

Similar to https://github.com/systemd/systemd/issues/7090 with different behavior.
Might be related to https://github.com/systemd/systemd/issues/5394.

**Comment by zonggen** [comment]
Closing, turns out to be a Fedora SELinux policy bug. 
See https://github.com/coreos/fedora-coreos-pinger/pull/29#issuecomment-558791303.

**Comment by TheArcaneBrony** [comment]
I'm running into this issue with 3 services sharing the same StateDirectory and WorkingDirectory (no SELinux or similar in the stack), ideas?
