### ISSUE TITLE
Shutdown-very-long

### ISSUE THREAD

**Issue by Pask-66** [systemd/systemd#14163]
Hello all,
sorry for my bad English
here I am installing an archlinux32bits on an old laptop (Acer Aspire 1680). Everything works startup, reboot, wifi, touchpad etc ... except the shutdown of the pc which is incredibly long.
I managed to copy the messages that are displayed before the shutdown of the laptop:

INFO: task shutdown:1 blocked for more than 120 seconds.
Tainted: G W 4.19.81-1.0-lts #1
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Call Trace:
__schedule+0x264/0x8e0
schedule+0x2e/0x80
schedule_timeout+0x2a5/0x420
? acpi_ut_delete_internal_object_list+0x2a/0x2e
wait_for_common+0x9e/0x130
? wake_up_q+0x60/0x60
wait_for_completion+0x17/0x20
flush_workqueue+0xf9/0x3d0
acpi_os_wait_events_complete+0x2b/0x30
acpi_power_off_prepare+Ox1c/0x20
kernel_power_off+040/0x70
sys_reboot+0x104/0x200
? do_iter_write+0xc2/0x190
? vfs_wrtiev+0x7d/0xe0
do_fast_syscall_32+0x87/0x1f0
entry_SYSENTER_32+0x6b/0xbe
EIP: 0xb7ee2d19
Code: Bad RIP value.
EAX: ffffffda EBX: fee1dead ECX: 28121969 EDX: 4321fedc
ESI: 00000000 EDI: bfee8c1c EBP: bfee8d18 ESP: bfee8b78
DS: 007b ES: 007b FS: 0000 GS: 0033 SS: 007b EFLAGS: 00000292

This problem is no longer present by compiling the kernel 3.16.78 (recovered on https://www.kernel.org). I tested the compilations of several kernel 4.x and 5.x but this problem comes back.

Do not hesitate to ask log or other files to try to allow me to understand where the problem lies.

I performed a debug of the system shutdown by following the instructions of https://freedesktop.org/wiki/Software/systemd/Debugging/#Diagnosing_Shutdown_Problems and i attach the result file: 

http://www.mediafire.com/file/jfzgif4l4v43wqq/shutdown-log.txt/file

**Comment by poettering** [comment]
not a systemd problem, but a kernel problem! Please ping your kernel maintainers. Thank you!
