### ISSUE TITLE
systemd umounts foo if bar doesn't get mounted

### ISSUE THREAD

**Issue by 7eggert** [systemd/systemd#14174]
I have a unit mounting a number of nfs shares. When an update caused one share to not be accessible, entirely unrelated shares got unmounted:
---Unit---
```
[Unit]
Description = mount -a -T fstab.nfs
After = network-online.target
[Service]
Type = exec
RemainAfterExit = yes
ExecStart = !/bin/mount -a -T /etc/fstab.net
ExecStop = /bin/bash -c '/bin/umount /srv/mergerfs_data*; /bin/umount /mnt/nas2b-*; /bin/umount /mnt/nas{1,2,3}-*'

[Install]
WantedBy = multi-user.target
```
---fstab.net---
```
...
nas1:/mnt/HD/HD_b2/d1           /mnt/nas1-a             nfs     vers=3,soft,local_lock=all,rsize=1048576,wsize=1048576 0 0
...
nas2:/mnt/disk1/d1              /mnt/nas2-a             nfs     vers=3,soft,local_lock=all,rsize=1048576,wsize=1048576 0 0
...
/mnt/nas2-a                     /mnt/nas2b-a            bindfs  map=99/1000:@99/@1000,chmod-ignore,chown-ignore,chgrp-ignore,create-with-perms=664:+X,create-for-user=99,allow_other 0 0
...
/mnt/nas1-*/mhddfs_data         /srv/mergerfs_data      mergerfs        defaults,(...) 0 0
/mnt/nas2b-*/mfs:/mnt/nas3-*/mfs        /srv/mergerfs_data2,3 mergerfs defaults,(...) 0 0
...
be1:/var/mail                   /mnt/mail               nfs     vers=4,soft 0 0
```

---journalctl -eu fstab.net---
```
Nov 27 10:53:54 be10 systemd[1]: Starting mount -a -T fstab.nfs...
Nov 27 10:53:54 be10 systemd[1]: Started mount -a -T fstab.nfs.
Nov 27 10:53:55 be10 mount[1128]: Created symlink /run/systemd/system/remote-fs.target.wants/rpc-statd.service → /usr/lib/systemd/system/rpc-statd.service.
Nov 27 10:56:57 be10 mount[1128]: mount.nfs: Connection timed out
Nov 27 10:56:57 be10 systemd[1]: fstab-net.service: Main process exited, code=exited, status=64/USAGE
Nov 27 10:56:57 be10 systemd[1]: fstab-net.service: Failed with result 'exit-code'.
```

/mnt/mail  failed. The bindfs and mergerfs mounts were undone. The other nfs shares remained active.

My system: OpenSuse Tumbleweed, installed version was 243-2.1 (or 2.34-2.1).

**Comment by yuwata** [comment]
Why do not you simply use pure fstab instead of fstab.net + custom service?

**Comment by yuwata** [comment]
And I do not see any bug in this report. Please use the mailing list.

**Comment by 7eggert** [comment]
Why a separate fstab? Because systemd creates circular dependencies or tries to mount these before DNS works. On my current system (OpenSuse) I decided to give systemd a chance but to still be cautious (obviously correctly). On my last system (Debian) the nfs mounts failed half of the time (and I put a second attempt of mounting them into rc.local).

Do you really think /srv/mergerfs_data2,3 should be **un**mounted after **having successfully been mounted** if later /mnt/mail fails to mount?
