### ISSUE TITLE
systemd.io/RANDOM_SEEDS - elaborate on /dev/random

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#14199]
* https://systemd.io/RANDOM_SEEDS.html
* https://github.com/systemd/systemd/blob/master/docs/RANDOM_SEEDS.md

is an excellent write-up. Thank you for that!

Quote:

> (Strictly speaking there are more APIs, for example `/dev/random`, but these should not be used by almost any application and hence aren’t mentioned here.)

Could you please elaborate on this?

Which applications can/should use `/dev/random` and which ones should not?

I am asking, because I am packaging the [tirdad](https://github.com/Whonix/tirdad) kernel module (TCP Initial Sequence Numbers Randomization to prevent TCP ISN based CPU Information Leaks), which should be load before networking, needs a bit entropy and I am unsure if it's best to use `/dev/random`, `/dev/urandom` or `openssl`.

**Comment by boucman** [comment]
This is not a support forum but a bug-reporting tools. Please send a mail to the mailing list instead

moreover, your question is not a systemd question at all, but a generic linux question.

That being said, i'm pretty sure modules should not read any files in /dev but directly get random numbers from whatever internal kernel API is meant for that... so please ask the kernel people... they'll know better
