### ISSUE TITLE
PrivateTmp does not work when systemd-tmpfiles is disabled

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#14197]
**systemd version the issue has been seen with**
> 243.4

**Used distribution**
 > buildroot

**Expected behaviour you didn't see**
 > PrivateTmp works (or is ignored) when systemd-tmpfiles is not compiled int

**Unexpected behaviour you saw**
 > Units using PrivateTmp fail with an error "no such file or directory"

**Steps to reproduce the problem**
enable the following unit:
```
[Unit]
DefaultDependencies=False
Before=basic.target
After=sysinit.target

[Service]
ExecStart=date
Type=oneshot
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
(The ordering is here to guarantee that the bug always happen. Without it, the bug appears randomly)

My guess is that systemd-tmpfiles creates some infrastructure directories under /run that is missing when it is not available.

since systemd-tmpfiles is an optional feature of systemd, things should be handled gracefulyl when systemd-tmpfiles is missing. I can probably work something, but I need some direction

* stop considering systemd-tmpfiles as optional and remove the compile option
* gracefully handle this case by creating the missing directories if they don't exist
* gracefully handle this case by ignoring PrivateTmp when systemd-tmpfiles is not available

I would tend to go with the first option because various upstream packages (PHP) are starting to provide tmpfiles.d files to ease their installation, so system without tmpfiles.d will start breaking in creative ways. Moreover, the module-autoloading infrastructure relies on systemd-tmpfiles and won't work without it.

Thx for any direction
Boucman

**Comment by poettering** [comment]
hmm, i am not sure why that specifically fails, and would prefer if we'd understand that first.

tmpfiles is only really optional on the most trivial of embedded machines i guess. it's not optional on a desktop or server or any general purpose distro i guess.

**Comment by boucman** [comment]
ok, i'll dig deeper 
(and, for the record, that was reported on buildroot, so yes... most trivial embedded machines)

**Comment by boucman** [comment]
Ok, after digging, the root problem seems to be that /var/tmp is not created, so the call to mkdtemp in namespace.c:setup_one_tmp_dir fails when creating /var/tmp/systemd-private-XXXXX-test.service-XXXX

one more way to deal with that would be to document what needs to be done to run without tmpfiles.d (which could include running cross-systemd-tmpfiles from the host when generating the rootfs, so we can easily rely on what upstream-systemd and other packages provide...)

**Comment by poettering** [comment]
I'd probably just sprinkle in an mkdir_p to create it if it is missing. Sounds simpler and more robust
