### ISSUE TITLE
when using pager: color output has escape codes "escaped"

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#14193]
**systemd version the issue has been seen with**
> 243 and 244rc1

**Used distribution**
 > own buildroot

**Expected behaviour you didn't see**
 > systemctl (and other tools) detect color capability,
but output the escape codes themself. this happens both
with a serial device and over ssh
```
# systemctl --help

systemctl [OPTIONS...] COMMAND ...

[[0;1;39mQuery or send control commands to the system manager.[[0m

[[0;4mUnit Commands:[[0m
  list-units [PATTERN...]             List units currently in memory
  list-sockets [PATTERN...]           List socket units currently in memory,
```
interesting enough I get the correct colored output when piping through cat:
```
# SYSTEMD_COLORS=1 systemctl --help | cat
```

or disabling the pager seems to do the trick aswell.

**Steps to reproduce the problem**

Well, would probably need the buildroot image, can provide instructions for building it.

**Comment by nolange** [comment]
Invalid, sorry.

was using busybox less as pager without the option to pass raw escapes (thought systemd had its own pager).

**Comment by SimonSimCity** [comment]
I just ran into this issue myself and was a bit puzzled about how I could continue here. If you're facing the same problem, and you build your system using yocto, this thread might get you on the right track: https://www.yoctoproject.org/pipermail/yocto/2015-January/023334.html

For me, it was about adding `packagegroup-core-full-cmdline` to the `CORE_IMAGE_EXTRA_INSTALL` setting which ensured that the BSD-licensed version of `less` is used.

**Comment by AleXoundOS** [comment]
In my case the problem was caused by `~/.less` file existence.
