### ISSUE TITLE
Bogus error: Failed at step NAMESPACE spawning /usr/sbin/start_apache2

### ISSUE THREAD

**Issue by archiecobbs** [systemd/systemd#14205]
**systemd version the issue has been seen with**
> systemd-234-lp150.20.15.1.x86_64

**Used distribution**
 > openSUSE Leap 15.0

**Expected behaviour you didn't see**
 > No error reported

**Unexpected behaviour you saw**
 > Error reported

**Steps to reproduce the problem**

Unfortunately, this one is not reproducible. In fact this same scenario has worked fine for years on multiple computers. So I'll understand if there's no way to debug this, but I thought it was worth submitting an issue just in case it is useful.

Note this issue is copied from [openSUSE bug #996203](https://bugzilla.suse.com/show_bug.cgi?id=996203). There is additional info there.

**Problem Description**

I have an RPM that includes the SSL certificate. To update the SSL certificate I build and install a new version of the RPM. The RPM contains this script:

```
    %post

    # Reload apache
    if systemctl -q is-active apache2.service; then
        systemctl reload-or-try-restart apache2.service
    fi
```

This has worked normally for years on 10+ different machines.

Suddenly today instead I got this error:

```
apache2.service: Failed at step NAMESPACE spawning /usr/sbin/start_apache2: No such file or directory
```

Here is the relevant `journalctl` output:

```
Nov 22 12:42:19 prod systemd[1]: Stopping The Apache Webserver...
Nov 22 12:42:19 prod systemd[2793]: apache2.service: Failed at step NAMESPACE spawning /usr/sbin/start_apache2: No such file or directory
Nov 22 12:42:19 prod systemd[1]: apache2.service: Control process exited, code=exited status=226
Nov 22 12:42:19 prod systemd[1]: Stopped The Apache Webserver.
Nov 22 12:42:19 prod systemd[1]: apache2.service: Unit entered failed state.
Nov 22 12:42:19 prod systemd[1]: apache2.service: Failed with result 'exit-code'.
Nov 22 12:42:19 prod systemd[1]: Starting The Apache Webserver...
Nov 22 12:42:19 prod systemd[1]: Started The Apache Webserver.
```

I then logged in and did `systemctl restart apache2` and everything was fine.

Running `rpm -V apache2` showed nothing amiss. The file `/usr/sbin/start_apache2` was indeed exactly where it should be.

This smells to me like some kind of `systemd` internal race condition bug.

Versions:
```
openSUSE Leap 15.0
apache2-2.4.33-lp150.2.23.1.x86_64
systemd-234-lp150.20.15.1.x86_64
```

**Comment by poettering** [comment]
We only track  issues in the two most recent upstream systemd versions here, and the isse submission form really should have made that clear. We are at 243 and 244 now, i.e. your version 234 is waaaaay too old.

Please talk to downstream for issues with older versions.
