### ISSUE TITLE
Static routes via DHCP gateway

### ISSUE THREAD

**Issue by mahkoh** [systemd/systemd#14204]
I want to be able to write

```
[Match]
Name=wlan0

[Network]
DHCP=ipv4

[Route]
Destiation=1.2.3.4
Gateway=DHCP
```

The intended behavior is that networkd updates the route's gateway (via a.b.c.d) whenever the DHCP server announces a new gateway.

Afaict, at the moment such routes cannot be used if the gateway is not constant. (Which is normal for a wireless device.)

**Comment by yuwata** [comment]
Duplicate of #8213?

**Comment by mahkoh** [comment]
It is.

**Comment by yuwata** [comment]
@mahkoh If possible, please test PR #14499.
