### ISSUE TITLE
The introduction of networkd's speed meter broke DBus.Properties' GetAll

### ISSUE THREAD

**Issue by Tragetaschen** [systemd/systemd#14222]
**systemd version the issue has been seen with**
243

**Used distribution**
Yocto "zeus"

**Expected behaviour you didn't see**
```bash
# busctl call org.freedesktop.network1 /org/freedesktop/network1/link/_34 org.freedesktop.DBus.Properties GetAll s org.freedesktop.network1.Link
a{sv} 5 "OperationalState" s "no-carrier" "CarrierState" s "no-carrier" "AddressState" s "off" "AdministrativeState" s "configuring" "BitRates" (tt) 1844674407370955264 1844674407370955264
```
(maybe without `BitRates`)

**Unexpected behaviour you saw**
```bash
# busctl call org.freedesktop.network1 /org/freedesktop/network1/link/_34 org.freedesktop.DBus.Properties GetAll s org.freedesktop.network1.Link
Call failed: Speed meter is disabled.
```

**Steps to reproduce the problem**
Run systemd-networkd with `SpeedMeter=no` (the default)

https://github.com/systemd/systemd/blob/99b8517ca7eb0a9015155cc1e0a9ae66e07240f0/src/network/networkd-link-bus.c#L44-L45

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #14227.
