### ISSUE TITLE
dbus-org.freedesktop.resolve1.service alias was lost in meson conversion

### ISSUE THREAD

**Issue by StefanBruens** [systemd/systemd#14220]
The old build scripts created a symlink `/usr/lib/systemd/system/dbus-org.freedesktop.resolve1.service` -> `systemd-resolved.service`

https://github.com/systemd/systemd/blob/d60c527009133a1ed3d69c14b8c837c790e78d10/Makefile.am#L5608-L5610

This has been lost in the meson conversion:

https://github.com/systemd/systemd/blob/cb515608030fe05f4a46ed32e1cd30aaca6e3381/units/meson.build#L150-L151

Equivalent snippet for `hostname1`:

https://github.com/systemd/systemd/blob/d60c527009133a1ed3d69c14b8c837c790e78d10/Makefile.am#L4977

https://github.com/systemd/systemd/blob/cb515608030fe05f4a46ed32e1cd30aaca6e3381/units/meson.build#L187

As `dbus-org.freedesktop.resolve1.service` is referenced from `system-services/org.freedesktop.resolve1.service`, e.g. resolvectl fails with
`Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.`

See also
- https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1795852
- https://bugs.archlinux.org/task/61738

**Comment by mbiebl** [comment]
Afair this was a deliberate change to not duplicate the information that is already in the `[Install]` section.

**Comment by mbiebl** [comment]
01d2041e41f4886a6dff16a53a950ae8d5b66bc7

**Comment by poettering** [comment]
This was a misunderstanding, see comments on #14426, closing.
