### ISSUE TITLE
Getting "Unsafe symlinks encountered in /var/log, refusing." Don't understand why.

### ISSUE THREAD

**Issue by ForceConstant** [systemd/systemd#14226]
**systemd version the issue has been seen with**
> 237 

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > systemd-tmpfiles working correctly.

**Unexpected behaviour you saw**
 > I get multiple errors on startup, and various files are not created correctly.

**Steps to reproduce the problem**
systemctl restart systemd-tmpfiles-setup

So I am getting lots of errors in syslog regarding unsafe symlinks. Looking at the code it looks like this is just a check that user is root, and they all seem to be. Any ideas? Note /var is a symlink to another drive, but is that not allowed now?

Dec  2 10:19:04 server systemd-tmpfiles[497]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/log, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/lib, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/cache/man, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/run/postgresql, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/log/postgresql, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/run/screen, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/run/sshd, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/run/sudo, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/run/sudo/ts, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/lib/systemd, refusing.
Dec  2 10:19:04 server systemd-tmpfiles[497]: Unsafe symlinks encountered in /var/lib/systemd/coredump, refusing.

brian@server:/mnt/media/aux/linux/home/gekko$ ls -ld /
drwxr-xr-x 24 root root 4096 Nov 30 13:53 /
brian@server:/mnt/media/aux/linux/home/gekko$ ls -ld /var
lrwxrwxrwx 1 root root 24 Nov 15  2017 /var -> /mnt/media/aux/linux/var
brian@server:/mnt/media/aux/linux/home/gekko$ ls -ld /var/log
drwxrwxr-x 14 root syslog 4096 Dec  2 08:13 /var/log
brian@server:/mnt/media/aux/linux/home/gekko$

**Comment by poettering** [comment]
most likely some dir the path /mnt/media/aux/linux/var is writable by non-root (ie. not owned by root, or world-writable or so)

**Comment by ForceConstant** [comment]
> most likely some dir the path /mnt/media/aux/linux/var is writable by non-root (ie. not owned by root, or world-writable or so)

```
ls -ld /mnt/media/aux/linux/var
drwxr-xr-x 19 root root 4096 Nov 15  2017 /mnt/media/aux/linux/var
```

**Comment by poettering** [comment]
you need to check *every* dir in the path /mnt/media/aux/linux/var. i.e. try:

```
ls -ld /mnt /mnt/media /mnt/media/aux /mnt/media/aux/linux /mnt/media/aux/linux/var
```

**Comment by ForceConstant** [comment]
> you need to check _every_ dir in the path /mnt/media/aux/linux/var. i.e. try:
> 
> ```
> ls -ld /mnt /mnt/media /mnt/media/aux /mnt/media/aux/linux /mnt/media/aux/linux/var
> ```

Thanks that was it.
