### ISSUE TITLE
During shutdown, the crypto device containing the rootfs shouldn't be detached by PID1

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#14224]
Please note that this is independent from the fact that all cryptsetup services are not ordered at all against their counterpart mount units. There's already issue #8472 for that.

This bug happens also during shutdown but when the root device is an encrypted one.

In this case there're shouldn't be any attempts  to detach the encrypted device that contains the rootfs during the 'regular' shutdown process handled by PID1.

This should be done until the very last moment, either by systemd-shutdown or after switching back to initrd.

We already skip `-.mount` during shutdown. This (special) case is automatically detected by PID1 and the mount unit is not stopped but for cryptsetup units it's a different story since it's not easy to detect that the encrypted device will be used as the device holding the rootfs.

Maybe we should add a new option `x-systemd.root` to crypttab for that purpose ?

**Comment by poettering** [comment]
hmm, we should probably have the same new mount option in both fstab and crypttab... but I am not convinced that "x-systemd.root" is the best name, after all in an env where /usr is mounted into a tmpfs it's the same thing.

Internally we call them "extrinsic" in mount.c, see comment in mount_is_extrinsic(). Maybe use the same nomenclature here too?

**Comment by fbuihuu** [comment]
Maybe it's just me but I find "extrinsic" quite obscure unless you know the details about API filesystems and such. IMHO "ignore" would just have been fine.

But in this case we want PID1 to take care of the cryptsetup services and mount units during the boot process through the usual logic (i.e. through mount/service units) but ignore them during shutdown.

"extrinsic" doesn't really seem appropriate for that, does it ?

**Comment by poettering** [comment]
naah, the root volume is something we should bother with during boot nor during shutdown from the main system. It has to be something that the initrd and the shutdown initrd deal with and remains "fixed" in between. This is what "extrinsic" stuff generally is for us: not managed by us, i.e. not by PID 1 during normal operation.

**Comment by fbuihuu** [comment]
Ah now with this definition (neither in initrd nor shutdown initrd, ...) it's clearer as otherwise systemd does take care of mounting the rootfs and bringing up the crypto root device from within initrd...

We also have the concept of "perpetual" units (in fact `-.mount` is already described as such in systemd.unit man page) which aren't stopped via the usual mechanisms. Maybe that could be a possible alternative ?

**Comment by fbuihuu** [comment]
@poettering please take a look at https://github.com/systemd/systemd/pull/14235
