### ISSUE TITLE
nic names swapped around after kernel update (5.3.0-0.bpo.2-amd64) Debian 10 (Buster)

### ISSUE THREAD

**Issue by jamesdrum** [systemd/systemd#14225]
I am having an issue with .link files in systemd after upgrading Debian 10 to the latest kernel 5.3.0-0.bpo.2-amd64.
When  i run **udevadm /sys/class/net/eth0** I am seeing the following error.
**eth0: Failed to rename network interface 2 from 'eth0' to 'eth2': Device or resource busy**

For some reason all of the nics have been swapped around even though I have individual .link files for each interface.

This seemed to work fine on the previous kernel.

Thank you in advance for your help.

**Comment by mbiebl** [comment]
Renaming from ethX to ethY was never safe and always racy.

If you are going to renaming interfaces, please chose names which don't collide with kernel names.

**Comment by poettering** [comment]
Network interface enumeration is not stable in the default kernel policy. Use a different one:

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

**Comment by jamesdrum** [comment]
Hi,

Thanks for coming back to me.

My issue is that the name doesn't bind to the mac address.

So for example I can have an interface called 'eth0' but it will swap to another NIC after the kernel update. The mac is not linked to the interface name even though I've set this in the .link file.

If I don't set net.ifnames=0 in the grub.conf then there shouldn't be an issue, eth0 never existed.

It shouldn't be using those names.

Regards

James

**Comment by mbiebl** [comment]
You can't "bind" eth0 to an interface name via .link files.
If you have multiple interfaces and the interfaces you want to name eth0 is actually called eth1 by the kernel, then a rename will happen. This is racy though.
If you want to bind names to mac adresses, use names that don't collide with the kernel provided names, say name it network0
