### ISSUE TITLE
systemctl --failed no longer shows failed units

### ISSUE THREAD

**Issue by dalu** [systemd/systemd#14238]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > gentoo

**Expected behaviour you didn't see**
 > a list of failed units

**Unexpected behaviour you saw**
 > no list of failed units

**Steps to reproduce the problem**
`systemctl --failed` while having at least 1 unit fail to start

**Comment by keszybz** [comment]
Dunno, seems to work here. Does `systemctl --state=failed` show anything?
Please make sure you have some failed units, e.g. by running `systemd-run false`.

**Comment by dalu** [comment]
Hmm. I fixed the error...

```
[Unit]
Description=domain.tld frontpage
After=local-fs.target network.target mongodb.service keycloak.service
Requires=mongodb.service keycloak.service

[Service]
User=nginx
Group=nginx
Type=simple
Environment=GIN_MODE=release
ExecStart=/var/www/domain.tld/go/forum frontpage
WorkingDirectory=/var/www/domain.tld/go/
Restart=on-failure
RestartSec=3s

[Install]
WantedBy=multi-user.target
```

this unit wasn't marked as failed altough it did fail several times and after a while was (inactive|failed), cant't remember.

The reason was it depended on keycloak.service, which ran, but was misconfigured after an update.
So the domain.tld service wasn't able to connect to the keycloak server on start and exited with code 1,
which lead to restarts. So this unit failed or was inactive. Checking with `systemctl --failed` returned 0 units failed.

Your example works as it should.

But meanwhile I fixed the issue so I can't reproduce it anymore.

**Comment by keszybz** [comment]
Let's close this then.

**Comment by dalu** [comment]
It's still an issue though, a different one but yeah.
