### ISSUE TITLE
virtualization detection API break

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#1423]
Previously systemd's `Virtualization` bus property used to return an empty string on bare metal systems, but now it returns the string `"none"` instead.

This broke gnome-settings-daemon, which expects an empty string as per API documentation http://www.freedesktop.org/wiki/Software/systemd/dbus/, and now mistakenly detects all systems as virtualized.

**Comment by poettering** [comment]
A fix for this is in #1426.
