### ISSUE TITLE
Exec reboot the os hangs

### ISSUE THREAD

**Issue by zhucan** [systemd/systemd#14236]
**systemd version the issue has been seen with**
> systemed version: systemd-219-42.el7.x86_64

**Used distribution**
 >centos version: CentOS Linux release 7.4.1708 (Core)  kernel version: 3.10.0-693.el7.x86_64

**Expected behaviour you didn't see**
 >os reboot successfully

**Unexpected behaviour you saw**
 >![image](https://user-images.githubusercontent.com/13997135/70039530-19aa8d80-15f5-11ea-9831-236dd6f9535c.png)

**Steps to reproduce the problem**
mount  as many iscsi devices as possible on the client node, and rebooting the client node.

**Comment by yuwata** [comment]
v219 is too old here. Please contact to your downstream, or try to use v244 or v243.

**Comment by zhucan** [comment]
@yuwata Is there a compatibility list between os version with the systemd？

**Comment by yuwata** [comment]
No. But the requirements to build systemd are written in [README](https://github.com/systemd/systemd/blob/master/README).

**Comment by zhucan** [comment]
Thanks @yuwata
