### ISSUE TITLE
Alienware M17X R3 laptop ejectcd fix.

### ISSUE THREAD

**Issue by lothrond** [systemd/systemd#14232]
**Every** distribution i have used , i have to _manually_ setup my ejectcd button. After reading the comments in `/lib/udev/hwdb.d/60-keyboard.hwdb`, i would like to try and fix this issue.

in /lib/udev/hwdb.d/60-keyboard.hwdb there is this line:

`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*`
`KEYBOARD_KEY_8a=ejectcd`

This can be changed by creating:

`/lib/udev/hwdb.d/70-alienware-fix.hwdb`

with the contents of:

`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*`
` KEYBOARD_KEY_89=ejectcd`

However, the output of `udevadm info /dev/input/event4` looks like this:
(event4 being the AT keyboard)

P: /devices/platform/i8042/serio0/input/input4/event4
N: input/event4
S: input/by-path/platform-i8042-serio-0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: DEVNAME=/dev/input/event4
E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_SERIAL=noserial
E: KEYBOARD_KEY_89=ejectcd
E: KEYBOARD_KEY_8a=ejectcd
E: KEYBOARD_KEY_bf=!prog1
E: KEYBOARD_KEY_c1=!prog2
E: KEYBOARD_KEY_c2=!power
E: LIBINPUT_ATTR_KEYBOARD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/1/1:isa0060/serio0
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=44528998
E: XKBLAYOUT=us
E: XKBMODEL=pc105

While editing rules directly in `/lib/udev/hwdb.d/60-keyboard.hwdb`, afer running `udevadm info /dev/input/event4` i get:

P: /devices/platform/i8042/serio0/input/input4/event4
N: input/event4
S: input/by-path/platform-i8042-serio-0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: DEVNAME=/dev/input/event4
E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_SERIAL=noserial
E: KEYBOARD_KEY_89=ejectcd
E: KEYBOARD_KEY_bf=!prog1
E: KEYBOARD_KEY_c1=!prog2
E: KEYBOARD_KEY_c2=!power
E: LIBINPUT_ATTR_KEYBOARD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/1/1:isa0060/serio0
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=44528998
E: XKBLAYOUT=us
E: XKBMODEL=pc105

As you can see, it's really only one character that needs changing...

These are some of the best sources i can find on the subject (aside from the comments in `/lib/udev/hwdb.d/60-keyboard.hwdb`):

https://wiki.archlinux.org/index.php/Keyboard_input
https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes#Using_udev

**Comment by yuwata** [comment]
Please submit as a PR.
