### ISSUE TITLE
`systemd-gpt-auto-generator` should not be enabled by default.

### ISSUE THREAD

**Issue by hyasynthesized** [systemd/systemd#14248]
The `systemd-gpt-auto-generator` feature is extremely useful, however, having disks auto-mount on you can be incredibly confusing if you don't know it exists. As such, it should be disabled by default.

**Comment by poettering** [comment]
We introduced explicit GPT partition types for te stuff gpt-auto-generator auto-mounts, precisely not to surprise people with that. If you use these GPT partition types then you get the automatic behaviour. if you don't want the automatic behaviour don't use them and stick to "Linux generic" or so.
