### ISSUE TITLE
nspawn --volatile=overlay: Keep overlayfs when rebooting a container

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14243]
**Is your feature request related to a problem? Please describe.**

I use nspawn to simulate a system for testing purposes where machines are sometimes rebooted. Each of these systems starts from the same base image but has custom changes that are applied during the tests. To avoid copying the image for each started container, I tried to use `--volatile=overlay` to start the containers. Unfortunately, any changes made are lost when the container reboots.

**Describe the solution you'd like**

Ideally, the overlayfs created by `--volatile=overlay` would not be discarded when rebooting a container.

**Describe alternatives you've considered**

I can copy the image for each container and not use `--volatile=overlay` but that would require me to copy the image which I would like to avoid if possible.

**Comment by DaanDeMeyer** [comment]
I had a look at implementing this myself. It seems we will somehow have to persist the tmpfs of the overlayfs between multiple calls to systemd-nspawn and give it a predictable name so we can check if it already exists in systemd-nspawn. However, I'm not entirely sure what to use as the predictable name for the tmpfs.

Any idea if a pr implementing this is likely to be accepted? I'll give it a go but of course I need to know if keeping the overlay around on reboot would be considered correct behavior in the first place.

**Comment by poettering** [comment]
if you have an efficient fs (i.e. recent xfs or btrfs) you can use --template= which will do a reflink copy or subvol snapshot for you...

--volatile= is not what you want if you actually want persistency. --overlay= is the option you want, but we currently don't support it for the root fs. Patch that makes that work would be very welcome.

**Comment by DaanDeMeyer** [comment]
Closing this in favor of https://github.com/systemd/systemd/issues/3847.
