### ISSUE TITLE
Systemd 244 Hibernation failed due to sys/power/resume and /sys/power/resume_offset has no matching entry in /proc/swaps

### ISSUE THREAD

**Issue by helloworld1** [systemd/systemd#14249]
`systemctl hibernate` was working in 243 but failed in 244 with error:

```
Dec 04 17:21:09 liberty-pc systemd-logind[551]: /sys/power/resume and /sys/power/resume_offset has no matching entry in /proc/swaps; Hibernation will fail: resume=259:7, resume_offset=52582877
```

The resume_offset in kernel parameter is correctly set and hibernation works in version 243.

```
% cat /proc/swaps 
Filename				Type		Size	Used	Priority
/swapfile                               file		20971516	0	-2

% cat /proc/cmdline 
initrd=\intel-ucode.img initrd=\initramfs-linux.img root=PARTUUID=fd43dfa1-32dd-444e-a802-b1c696bd57be rootflags=subvol=/root resume=PARTUUID=fd43dfa1-32dd-444e-a802-b1c696bd57be resume_offset=52582877 zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold rw
```

**Used distribution**
 > Arch linux

**Expected behaviour you didn't see**
 > systemctl hbiernate should succeed

**Unexpected behaviour you saw**
 > systemctl hibernate failed

**Steps to reproduce the problem**
* Use BTRFS swap file 
* Follow instruction https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file_on_Btrfs to create swapfile
* Verified swap file works and has enough space.  
* Verified Hibernation works by running `echo disk > /sys/power/state`
* Run `systemctl hibernate`
* `systemctl hibernate` failed saying not enough space
* `journalctl -ae` shows error Hibernation failed due to sys/power/resume and /sys/power/resume_offset has no matching entry in /proc/swaps

**Comment by keszybz** [comment]
@zachsmith ?

**Comment by AlvinZhu** [comment]
I'm affected as well by this since the upgrade to systemd 244. 
Arch Linux

**Comment by diabonas** [comment]
Looking at the relevant code in [`sleep-config.c`](https://github.com/systemd/systemd/blob/master/src/shared/sleep-config.c), it appears as if the following happens:

- [`calculate_swap_file_offset`](https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L216) does not support calculating the file offset on Btrfs file systems, returning an offset of 0 instead: https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L237-L238
- [`location_is_resume_device`](https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L283) compares the file offset calculated by `calculate_swap_file_offset` (i.e. 0 on Btrfs) with the `resume_offset` kernel command line parameter, which fails: https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L288
- As a result, the [loop](https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L321-L391) in [`find_hibernate_location`](https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L300) never finds the correct swap entry, using the ["highest priority swap with most remaining space"](https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L366) instead: https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L387-L389
- Finally, `location_is_resume_device` is used on the selected swap entry, which fails again (even if it is indeed the correct entry) and produces the warning mentioned in the bug report: https://github.com/systemd/systemd/blob/9142bbd19c932e9fd248f613abfc39fad66e9f23/src/shared/sleep-config.c#L396-L398

An (untested) quick fix would be to use
```c
return streq(sys_resume, location->resume) && ((location->resume_offset == 0) || (sys_offset == location->resume_offset));
```
in `location_is_resume_device` so that the comparison can succeed on Btrfs filesystems. This means if the device given by the `resume` kernel command line argument has a Btrfs file system, `find_hibernate_location` will use the first swap file on the device listed in `/proc/swaps`.

The only situation where I can see this failing is when there are multiple swap files on a single Btrfs device and the one specified by `resume_offset` is not the first one listed in `/proc/swaps`. However in this case we cannot do any better at the moment anyway since calculating the file offset for Btrfs to find the correct file is not implemented. On the other hand, the most common case of at most one Btrfs swap file is covered.

**Comment by zachsmith** [comment]
Thanks for reporting this and sorry for the headache. I'll get a fix up for this soon.

**Comment by diabonas** [comment]
Apparantly on Btrfs even the [device ID from `fstat` does not match the actual device ID](https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg57667.html), so the quick fix above should read
```c
return location->resume_offset == 0 || (streq(sys_resume, location->resume) && sys_offset == location->resume_offset);
```
instead (i.e. use the swap file on any Btrfs file system that is listed first in `/proc/swaps`). I was able to successfully test this workaround on a system with a single swap file on a (LUKS-encrypted) Btrfs file system.

**Comment by zachsmith** [comment]
I posted a fix here: https://github.com/systemd/systemd/pull/14270.

@diabonas and @helloworld1, I have not had a chance to setup an environment to test this fix with so if you have the time and are willing to confirm the fix I would be grateful. Otherwise, I will pick this back up over the weekend.

**Comment by helloworld1** [comment]
I am have applied the patch to 244 and testing it today

**Comment by zachsmith** [comment]
@diabonas ahhh, yes. I forgot that Btrfs doesn't return correct device information from `stat` calls... Thanks for reminding me of that and providing the helpful link with more info.

I pushed up a new change that removes the comparison for `sys_resume` and `location->resume` but tries to make a guess only in situations where there is a `resume_offset=` value `>0` in an attempt to more accurately guess that the user is in fact trying to use a swap file. 

Again, I haven't had a chance to setup my test environment for this but will a bit later today or tomorrow. If you or @helloworld1 are willing to test it on your setups (especially with LUKS), that would be very helpful.

**Comment by zachsmith** [comment]
Actually, hold off. I think there are a few more kinks to work out in this patch.

**Comment by helloworld1** [comment]
Just tested your patch and the hibernate works great on system with unencrypted BTRFS and a single physical drive. Once you have the kinks, I will test again :)

**Comment by zachsmith** [comment]
Thanks for confirming @helloworld1! I've pushed up a few more changes to handle some edge cases. I'm setting them up to test now but would very much welcome your testing help as well.

I realized while revisiting this code that the check to verify enough space cannot work consistently in cases where the user has multiple swap files configured on Btrfs. As a result, I made a small change that will intentionally cause hibernation will fail unless you set `Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1` in your `systemd-logind.service`.

**Comment by zachsmith** [comment]
I was finally able to test these changes on a VM. Seems to be working but would love to know if it's working on real systems. :+1:

**Comment by helloworld1** [comment]
Unfortunately the latest patch does not work. hibernation failed  `journalctl` does not give error log anymore also.
```
% systemctl hibernate
Failed to hibernate system via logind: Not enough swap space for hibernation

% SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1 systemctl hibernate
Failed to hibernate system via logind: Not enough swap space for hibernation
```

**Comment by zachsmith** [comment]
You'll need to set `SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1` in the `[Service]` section of the `systemd-logind.service`. You should be able to do that with `systemctl edit systemd-logind.service`

```
[Service]
Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1
...
```

I believe you'll need to reboot after making that change.

**Comment by helloworld1** [comment]
Hibernation works with SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK in /etc/systemd/system/systemd-logind.service.d/override.conf
Why is SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK needed? I have single swap file unencrypted and single physical device. The image size is smaller than swapfile size.
```
% cat /sys/power/image_size 
13233156096

% ls -l swapfile
-rw------- 1 root root 21474836480 Sep 10 21:42 swapfile
```

**Comment by zachsmith** [comment]
@helloworld1 to try and answer your question, in order to correctly detect the remaining swap space, we need to know how much space is already in use. We do that by parsing `/proc/swaps` and attempting to match a swap entry with `resume=` and `resume_offset=` values to make checking for space on the right file. With swap files we need to calculate the offset...which we don't have support for right now when using Btrfs.

Because we can't correctly identify the swap file, we can't correctly see how much space is in use or is remaining. 

In the past we were just returning the first swap in the list and the space calculation would run and if you only had one swap entry that was your swap file configured for `resume` and resume_offset`, it would pass...but that was just coincidence.

**Comment by helloworld1** [comment]
Thanks for the explanation. Is the problem specific to BTRFS or all swap files? If it applies to all sway files, should we make space check bypass default for all swap files?

**Comment by zachsmith** [comment]
@helloworld1 @diabonas I've updated the patch a bit to focus more on giving Btrfs swapfile users a way to disable the swap discovery logic. I think this is the best course of action for a few reasons:  if you are intending to use a swapfile on Btrfs you must have your system configured correctly (`/sys/power/{resume, resume_offset}` must be set with correct device id and offset which must be calculated) and if the system is not configured correctly, systemd will not be able to help discover the swap file for you by parsing `/proc/swaps`.

The current patch will require that you add:
```
[Service]
Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1
```

to `systemd-logind` (logind checks for memory) and `systemd-hibernate` (attempts discovery to match swap files with configured devices) services. 

I've tested the patch and it seems to work ok but if you're open to testing again I'd appreciate it.

I'm waiting on additional feedback so there may be more changes to come so if you'd prefer to hold off that's fine too.

**Comment by helloworld1** [comment]
I tried latest patch. I got this error:
```
Dec 14 10:07:52 liberty-pc systemd-sleep[1501]: Unable to find a matching swap in /proc/swaps for /sys/power/resume and /sys/power/resume_offset; Hibernation will fail
```

```
% cat /sys/power/resume
259:7
% cat /sys/power/resume_offset
52582877
% cat /proc/swaps
Filename				Type		Size	Used	Priority
/swapfile                               file		20971516	0	-2
% cat /etc/systemd/system/systemd-logind.service.d/override.conf
[Service]
Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1
```

**Comment by zachsmith** [comment]
Thanks @helloworld1!  You'll also need to add the same value to the `systemd-hibernate` service. It needs to be in both.

**Comment by helloworld1** [comment]
Yes, I added the same config to `/etc/systemd/system/systemd-hibernate.service.d/override.conf` and hibernation works fine now.

**Comment by OSantt** [comment]
Hi @zachsmith. Thanks for your work. I have been affected by this bug as well, like @helloworld1, I use a swapfile. The steps described in OP are identical in my case. Differences are :

- swapfile on the /home partition
- filesystem is **ext4**, not Btrfs.
- distribution is manjaro.

In that case, the patch you applied allows hibernation to proceed successfully. So either my swapfile being on the /home partition creates a problem, or the problem is more related to swapfiles than to the file system.

Have a good day.

**Comment by lkjell** [comment]
> The current patch will require that you add:
> 
> ```
> [Service]
> Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1
> ```
> 
> to `systemd-logind` (logind checks for memory) and `systemd-hibernate` (attempts discovery to match swap files with configured devices) services.
> 

Hope this should not be the case in the final patch since it clearly breaks existing setup.
Systemd should just see if there is a swapfile on btrfs and disable the check.
Why does it works in version 243? Why not use the explicit offset that is set in the kernel parameters?

**Comment by helloworld1** [comment]
Thanks a lot @zachsmith for the hard work to fix the problem. Just report back the latest patch works great on my system.

**Comment by IPlayZed** [comment]
Hi!

This problem appears to be present on my system:

````~ 
❯ systemctl --failed
  UNIT                                                  LOAD   ACTIVE SUB    DESCRIPTION                                               
● systemd-hibernate-resume@dev-mapper-cryptswap.service loaded failed failed Resume from hibernation using device /dev/mapper/cryptswap

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.

~ 
❯ systemctl status systemd-hibernate-resume@dev-mapper-cryptswap.service
× systemd-hibernate-resume@dev-mapper-cryptswap.service - Resume from hibernation using device /dev/mapper/cryptswap
     Loaded: loaded (/usr/lib/systemd/system/systemd-hibernate-resume@.service; static)
     Active: failed (Result: exit-code) since Tue 2022-09-27 02:49:03 CEST; 1min 56s ago
       Docs: man:systemd-hibernate-resume@.service(8)
   Main PID: 284 (code=exited, status=1/FAILURE)
        CPU: 4ms

Sep 27 02:49:03 archlinux systemd[1]: Starting Resume from hibernation using device /dev/mapper/cryptswap...
Sep 27 02:49:03 archlinux systemd-hibernate-resume[284]: Failed to write '254:1' to /sys/power/resume: No such file or directory
Sep 27 02:49:03 archlinux systemd[1]: systemd-hibernate-resume@dev-mapper-cryptswap.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 02:49:03 archlinux systemd[1]: systemd-hibernate-resume@dev-mapper-cryptswap.service: Failed with result 'exit-code'.
Sep 27 02:49:03 archlinux systemd[1]: Failed to start Resume from hibernation using device /dev/mapper/cryptswap.

~ 
❯ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0           7:0    0     4K  1 loop  /var/lib/snapd/snap/bare/5
loop1           7:1    0   114M  1 loop  /var/lib/snapd/snap/core/13425
loop2           7:2    0    62M  1 loop  /var/lib/snapd/snap/core20/1611
loop3           7:3    0 346.3M  1 loop  /var/lib/snapd/snap/gnome-3-38-2004/115
loop4           7:4    0  91.7M  1 loop  /var/lib/snapd/snap/gtk-common-themes/1535
loop5           7:5    0    20K  1 loop  /var/lib/snapd/snap/hello-world/29
loop6           7:6    0 193.9M  1 loop  /var/lib/snapd/snap/storage-explorer/40
sda             8:0    0   1.8T  0 disk  
├─sda1          8:1    0     5G  0 part  /boot
├─sda2          8:2    0    12G  0 part  
│ └─cryptswap 254:1    0    12G  0 crypt [SWAP]
├─sda3          8:3    0   512G  0 part  
│ └─cryptroot 254:0    0   512G  0 crypt /
└─sda4          8:4    0   1.3T  0 part  
  └─crypthome 254:2    0   1.3T  0 crypt /home

~ 
❯ sudo bat /etc/crypttab 
Please touch the device.
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/crypttab
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # Configuration for encrypted block devices.
   2   │ # See crypttab(5) for details.
   3   │ 
   4   │ # NOTE: Do not list your root (/) partition here, it must be set up
   5   │ #       beforehand by the initramfs (/etc/mkinitcpio.conf).
   6   │ 
   7   │ # <name>       <device>                                     <password>              <options>
   8   │ crypthome         UUID=f31e19f6-9410-4b89-8c9c-440367a2043f none    tpm2-device=auto
   9   │ # data1        /dev/sda3                                    /etc/mypassword2
  10   │ # data2        /dev/sda5                                    /etc/cryptfs.key
  11   │ cryptswap    /dev/sda2  none    tpm2-device=auto
  12   │ # vol          /dev/sdb7                                    none
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~ 
❯ sudo bat /etc/fstab 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/fstab
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # Static information about the filesystems.
   2   │ # See fstab(5) for details.
   3   │ 
   4   │ # <file system> <dir> <type> <options> <dump> <pass>
   5   │ # Static information about the filesystems.
   6   │ 
   7   │ # /dev/mapper/cryptroot
   8   │ UUID=ddfddb25-b786-45ce-93c7-c2ae5a8b6b4c       /               btrfs            rw,relatime,ssd,space_cache=v2,subvol=/     0 1
   9   │ 
  10   │ # /dev/sda1 LABEL=EFI
  11   │ UUID=9BF7-50FC          /boot           vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro   0 2
  12   │ 
  13   │ # /dev/mapper/home
  14   │ UUID=009c12d7-da85-4664-9010-3817dc795efb       /home           btrfs           rw,relatime,ssd,space_cache=v2,subvolid=5,subvol=/      0 0
  15   │ 
  16   │ # /dev/mapper/cryptswap
  17   │ #UUID=edca29ce-c08c-437f-b370-ab74f49128c8      none            swap            defaults        0 0
  18   │ /dev/mapper/cryptswap    swap    swap    defaults    0 0
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~ 
❯ sudo bat /boot/loader/entries/unified-arch-hardened.conf 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /boot/loader/entries/unified-arch-hardened.conf
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ title Unified Secure Image for Arch Linux Hardened
   2   │ efi /archlinux-hardened-unified-kernel-image.efi
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~ 
❯ sudo bat /boot/loader/entries/arch-hardened.conf 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /boot/loader/entries/arch-hardened.conf
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ title   Arch Linux Hardened
   2   │ linux   /vmlinuz-linux-hardened
   3   │ initrd  /amd-ucode.img
   4   │ initrd  /initramfs-linux-hardened.img
   5   │ options kernel.yama.ptrace_scope=3 rd.luks.name=dab05272-8d83-4239-8c2f-51a111db882d=cryptroot rd.luks.options=dab05272-8d83-4239-8c2f-51a111db882d=tpm2-device=auto root=/dev/mapper
       │ /cryptroot rd.luks.name=3f0eb4d5-227d-4725-8fee-b6529841f41b=cryptswap rd.luks.options=3f0eb4d5-227d-4725-8fee-b6529841f41b=tpm2-device=auto resume=/dev/mapper/cryptswap rw
   6   │ 
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~ 
❯ sudo blkid
/dev/loop1: TYPE="squashfs"
/dev/mapper/cryptswap: UUID="edca29ce-c08c-437f-b370-ab74f49128c8" TYPE="swap"
/dev/loop6: TYPE="squashfs"
/dev/loop4: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/mapper/crypthome: UUID="009c12d7-da85-4664-9010-3817dc795efb" UUID_SUB="360eb0bd-5b1a-42e2-aab3-316a9a526518" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/loop0: TYPE="squashfs"
/dev/mapper/cryptroot: UUID="ddfddb25-b786-45ce-93c7-c2ae5a8b6b4c" UUID_SUB="4bccda4c-3b6b-4205-a537-c634757cc6a9" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sda4: UUID="f31e19f6-9410-4b89-8c9c-440367a2043f" TYPE="crypto_LUKS" PARTLABEL="Linux filesystem" PARTUUID="f7f97f2f-712a-44ba-bb8b-db0bc65d5ebb"
/dev/sda2: UUID="3f0eb4d5-227d-4725-8fee-b6529841f41b" TYPE="crypto_LUKS" PARTLABEL="Linux swap" PARTUUID="49ac85a0-834f-409b-82bf-d25728fd2813"
/dev/sda3: UUID="dab05272-8d83-4239-8c2f-51a111db882d" TYPE="crypto_LUKS" PARTLABEL="Linux x86-64 root (/)" PARTUUID="680de8a8-9417-45d0-9efb-e0db52938539"
/dev/sda1: LABEL_FATBOOT="EFI" LABEL="EFI" UUID="9BF7-50FC" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI system partition" PARTUUID="2cbd89e4-e430-46c4-a3ec-31d7f70a6530"
/dev/loop5: TYPE="squashfs"
/dev/loop3: TYPE="squashfs"

~ 
❯ cat /sys/power/state
freeze mem

~ 
❯ indmnt -R /sys
fish: Unknown command: indmnt

~ 
❯ findmnt -R /sys
TARGET                      SOURCE     FSTYPE     OPTIONS
/sys                        sysfs      sysfs      rw,nosuid,nodev,noexec,relatime
├─/sys/kernel/security      securityfs securityfs rw,nosuid,nodev,noexec,relatime
├─/sys/fs/cgroup            cgroup2    cgroup2    rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot
├─/sys/fs/pstore            pstore     pstore     rw,nosuid,nodev,noexec,relatime
├─/sys/firmware/efi/efivars efivarfs   efivarfs   rw,nosuid,nodev,noexec,relatime
├─/sys/fs/bpf               bpf        bpf        rw,nosuid,nodev,noexec,relatime,mode=700
├─/sys/kernel/tracing       tracefs    tracefs    rw,nosuid,nodev,noexec,relatime
├─/sys/fs/fuse/connections  fusectl    fusectl    rw,nosuid,nodev,noexec,relatime
└─/sys/kernel/config        configfs   configfs   rw,nosuid,nodev,noexec,relatime

~ 
❯ sudo cat /sys/power/resume
Please touch the device.
cat: /sys/power/resume: No such file or directory
```

I unlock my swapfile via TPM with systemd-style hooks.
