### ISSUE TITLE
mention in udev man about waiting behaviour of scripts, executed by RUN attribute of rule

### ISSUE THREAD

**Issue by JSkrat** [systemd/systemd#14259]
**Is your feature request related to a problem? Please describe.**
The problem is that it is totally not obvious, that udev will wait not only ending of main script, but its subprocesses, spawned by & (bash for example) too. Man page contains no info about that(

**Describe the solution you'd like**
The solution is to mention in man, in section, describing RUN attribute, what udev waits for, how determines, that program is finished and how to make it not to wait for program end
(solution [here](https://unix.stackexchange.com/questions/28548/how-to-run-custom-scripts-upon-usb-device-plug-in/28711#28711) with "at now" helped)

**Describe alternatives you've considered**
The alternative is to wonder and google it, spending whole evening to a task, which in other way could be done in a half of hour :) (not really understand, what that paragraph in an issue template is for, sorry)

**Comment by mbiebl** [comment]
> (solution [here](https://unix.stackexchange.com/questions/28548/how-to-run-custom-scripts-upon-usb-device-plug-in/28711#28711) with "at now" helped)

That's not a solution (using "at") . Use the documented mechanism of SYSTEMD_WANTS, which will pull in the service of your choice from a udev rule.

**Comment by JSkrat** [comment]
> > (solution [here](https://unix.stackexchange.com/questions/28548/how-to-run-custom-scripts-upon-usb-device-plug-in/28711#28711) with "at now" helped)
> 
> That's not a solution (using "at") . Use the documented mechanism of SYSTEMD_WANTS, which will pull in the service of your choice from a udev rule.

Ok, let me describe the source problem :)

I need: when usb wifi dongle being inserted, an internal wifi to switch off and specified networkmanager connection reconnect with new wifi device. When wifi dongle being removed i need to switch back to internal and trigger networkmanager to reconnect specified connection using internal one. 

I created one rule to uniquely name network interface of the internal wifi, and two rules on add and remove usb wifi which triggers switching internal wifi on or off (and managed or unmanaged by NM) and triggers reconnectng my managed by special daemon NM connection (nmcli con down and then nmcli con up), because for some reason NM does not do that automatically.

And here is the problem: there is no usb wifi network interface until rules are completed, so without at i don't know how to defer NM reconnection.

But anyway, i think it is important part of rule behaviour not mentioned in man page.

**Comment by poettering** [comment]
BTW, the udev man page is already very explicit about RUN, and that long running processes cannot be forked off via it:

> This can only be used for very short-running foreground tasks. Running an event process for a long period of time may block all further events for this or a dependent device.
>
> Starting daemons or other long-running processes is not appropriate for udev; the forked processes, detached or not, will be unconditionally killed after the event handling has finished.
>
> Note that running programs that access the network or mount/unmount filesystems is not allowed inside of udev rules, due to the default sandbox that is enforced on systemd-udevd.service.

I am not sure how we could be clearer than that.

(I will prep a PR that extends the text a bit and suggests SYSTEMD_WANTS use)

**Comment by JSkrat** [comment]
Thank you. Now, looking back, I can not say why it was not obvious in that form, unfortunately. It really is there. 
But I still would like to see there some reference to that udev sandbox to understand how does it know forked process pid, for example, and what are my options if i want to spawn something long-living there.
