### ISSUE TITLE
Script targetting network is executed before ip address is acquired

### ISSUE THREAD

**Issue by LCvanDinteren** [systemd/systemd#14260]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Arm debian buster

**Expected behaviour you didn't see**
 > Network should be up when service with `Wants=network-online.target` and `After=network-online.target` is triggered.

**Unexpected behaviour you saw**
 > `ip addr` shows no ip address

**Steps to reproduce the problem**
Place attached service in `/etc/systemd/system/` and script in `/home/pi/`

[after-network.service.txt](https://github.com/systemd/systemd/files/3931279/after-network.service.txt)
[my-script.sh.txt](https://github.com/systemd/systemd/files/3931280/my-script.sh.txt)

Note: our local DHCP server can be a bit slow at times, but I'd still expect this service to only trigger after network is really up & running.

**Comment by poettering** [comment]
did you read https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/?

Did you enable the "wait-online" service of the network management tool you use?

**Comment by LCvanDinteren** [comment]
Thanks a lot! Enabling the wait-online indeed did the trick.
