### ISSUE TITLE
[RFC] Switch sd-boot from gnu-efi to clang+lld

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#14262]
sd-boot currently uses gnu-efi to generate an efi executable.

Nowadays, clang and lld support doing that natively without all of the gnu-efi hacks (see e.g. https://dvdhrm.github.io/2019/01/31/goodbye-gnuefi/ or https://github.com/yoppeh/efi-clang for an example).

While you might not want to require clang and lld for the whole systemd project, it could be great to see how things would look like using them for sd-boot.

**Comment by AdrianVovk** [comment]
Just my 2¢: Super minimal build environments (like my own) would seriously struggle at this. Building gnuefi to get sd-boot is one thing. Building pretty much a second toolchain that's only there to build sd-boot and then promptly discarded is another.

**Comment by tpgxyz** [comment]
Worth to mention that if sd-boot is linked with `ld.lld` then it will not work due to missing functionalities in `ld.lld`
https://github.com/systemd/systemd/issues/19005

**Comment by medhefgo** [comment]
Basically, not going to happen now that #26641 is in.

Building PE binaries natively is too much pain with how (cross) toolchains and meson work (see #26097). And then we'd also be dropping arches we currently support.
