### ISSUE TITLE
Medion Akoya E-Models Matrix in 60-sensor.hwdb

### ISSUE THREAD

**Issue by cvoinf** [systemd/systemd#14272]
I've got two devices from Medion, both have the same Matrix:

 `# Medion Akoya E3222`
`sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION:pnMEDION*:*`
` ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1`

And the other one:

`# Medion Akoya E2293`
`sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION:pnE2293MD61144*:*`
` ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1`

Since up to now all Akoya E* models have the same Matrix, I would suggest to add the following lines to the file /usr/lib/udev/hwdb.d/60-sensor.hwdb:

`################`
`# Medion Akoya E Models`

`sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION:pnE*:*`
` ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1`

`sensor:modalias:acpi:KIOX010A*:dmi:*:svnMEDION:pnMEDION*:*`
` ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1`

`################`

**Comment by poettering** [comment]
Please file as PR so that we can properly attribute this to you, test it via CI and so on. Thank you for understanding.

/Cc @hadess
