### ISSUE TITLE
Systemd sandboxing fails when using a full system apparmor policy

### ISSUE THREAD

**Issue by madaidan** [systemd/systemd#14277]
**systemd version the issue has been seen with**
> v241

**Used distribution**
 > Debian Buster

**Expected behaviour you didn't see**
 > Systemd services with sandboxing work fine when using a full system apparmor policy.

**Unexpected behaviour you saw**
 > Systemd services fail when sandboxing is being used with a full system apparmor policy.

**Steps to reproduce the problem**

1) Setup a [full system apparmor policy](https://gitlab.com/apparmor/apparmor/wikis/FullSystemPolicy).

2) Create a service with sandboxing such as `PrivateDevices=yes`.

3) Enable the service. The service will fail with this error message:

```
Failed to execute command: Operation not permitted
Failed at step EXEC spawning /usr/bin/example: Operation not permitted
```

Apparmor logs:

```
AVC apparmor="DENIED" operation="exec" info="no new privs" error=-1 profile="init-systemd" name="/usr/bin/example" pid=386 comm="(example)" requested_mask="x" denied_mask="x" fsuid=0 ouid=0 target="/usr/bin/example"
```

This is not an issue with the apparmor policy as the service works fine when sandboxing is disabled.

The policy being used is https://github.com/Whonix/apparmor-profile-everything.

The only potential explanation I could find is https://forums.grsecurity.net/viewtopic.php?t=4326#p15815.

> It would be because that option causes Tor to be run with a private mount namespace created on demand, so any inode associated with /dev/urandom inside that namespace isn't knowable from the point where RBAC is loaded. That option shouldn't be enabled with RBAC.

Is there any way to fix this without having to disable the sandboxing?

**Comment by poettering** [comment]
Hmm. That sounds like an issue with the apparmor policy you use. Not sure what we are supposed to do about this? I.e. maybe file an issue against that policy package instead?

**Comment by poettering** [comment]
Note that upstream we dont really have apparmor people upstream, we pretty much rely on external contributions for that. Hence this is not really actionable for us anyway, besides that it looks like a policy prob (and not a systemd prob). Hence i am tempted to just close this?

**Comment by madaidan** [comment]
> That sounds like an issue with the apparmor policy you use. Not sure what we are supposed to do about this? I.e. maybe file an issue against that policy package instead?

I don't think it's an issue with the policy. If the policy was the problem, the service would fail regardless if sandboxing is used or not but the services fail *only* when sandboxing is enabled which seems to indicate that it's an issue with either systemd or the apparmor module (not the policy).

**Comment by poettering** [comment]
nah, the policy apparently forbids the namespacing operations we need to execute. If it doesn't allow that it needs updating. 

I am sorry, but this is not actionable for us, this needs someone who knows and cares about apparmor to look into. None of the systemd core team qualify as that. Apparmor support in systemd requires maintainers to look into that, and we have no 

/cc @mscherer

**Comment by mscherer** [comment]
Isn't it related to https://lists.freedesktop.org/archives/systemd-devel/2014-October/023909.html ?

**Comment by madaidan** [comment]
> Isn't it related to https://lists.freedesktop.org/archives/systemd-devel/2014-October/023909.html ?

No, in this case, apparmor is enforcing before systemd is even started. An initramfs hook makes systemd run confined in an apparmor profile.

**Comment by poettering** [comment]
Anyway, this is not actionable to us. This appears to be some issue with the Apparmor policy, i.e. that it disallows us to execute the operations we need to set up the sandboxing, such as setting up new namespaces. Please contact your distro for help, to update the apparmor policy. That policy is maintained downstream, and we can't do anything about it.

**Comment by madaidan** [comment]
I believe I have identified the issue here: it's the `no_new_privs` bit which prevents a process from gaining further privileges. AppArmor respects this and prevents a process from transitioning to another AppArmor profile that grants increased permissions: https://github.com/torvalds/linux/blob/3cee6079f62f4d3a37d9dda2e0851677e08028ff/security/apparmor/domain.c#L912-L926

Since a lot of sandboxing options force this enabled, most of them will fail. Would it be possible to somehow make a service transition AppArmor profile and then enable `no_new_privs`, rather than the other way around?
