### ISSUE TITLE
Incorrect device numbers resolved for IOWriteIOPSMax= option with LVM + dm-crypt

### ISSUE THREAD

**Issue by mk-fg** [systemd/systemd#14271]
**systemd version the issue has been seen with**
systemd-244

**Used distribution**
Arch Linux with 4.19 LTS kernel and `systemd.unified_cgroup_hierarchy` on cmdline.

**Expected behaviour you didn't see**

`IOWriteIOPSMax=/dev/disk/by-label/home 10` resource limit results in setting `wiops=10` for that device major:minor numbers.

I.e. if /dev/disk/by-label/home has 253:14 according to "ls -lH", then that's what will end up in io.max for cgroup where that line was specified, if "io" controller is available.

This is not what happens.

**Unexpected behaviour you saw**

major:minor numbers for related but different device end up being written to io.max file by systemd.

```
# systemctl cat test.slice
[Slice]
IOWriteIOPSMax=/dev/disk/by-label/home 10

# cat /sys/fs/cgroup/test.slice/io.max
253:2 rbps=max wbps=max riops=max wiops=10

# ls -lH /dev/disk/by-label/home
brw-rw---- 1 root disk 253, 14 Dec  7 06:03 /dev/disk/by-label/home

# lsblk
sdb                                               8:16   0 465.8G  0 disk
├─sdb3                                            8:19   0 270.1G  0 part
...
│ ├─base-home                                   253:2    0    70G  0 lvm
│ │ └─luks-f8a1c1fd-eb16-43a0-a036-78ba6535eaa3 253:14   0    70G  0 crypt /home
...
```

This is a problem, because unlike 253:14 dm-crypt device node, underlying 253:2 mapping does not get any writes according to io.stat, so setting such limits via systemd does not work at all.

Writing correct device numbers with same limits line to io.max via "echo" manually works and enforces such limits.

**Steps to reproduce the problem**

- Create /etc/systemd/system/test.slice with any LVM + dm-crypt mapping referenced there in any way (tried with /dev/mapper/* or /dev/disk/* symlinks, as well as /dev/dm-* nodes directly):

    ```
    [Slice]
    IOWriteIOPSMax=/dev/disk/by-label/home 10
    ```

- Start the slice unit: `systemctl start test.slice`

- Check io.max value for created cgroup: `cat /sys/fs/cgroup$(systemctl -q show -p ControlGroup --value test.slice)/io.max`

- Check same device major:minor numbers via ls: `ls -lH /dev/disk/by-label/home`

**Note**

Not sure if maybe it can be considered a kernel bug that writes to dm-crypt device do not get counted towards underlying lvm mapping, but arguably systemd seem to be doing something too clever and unnecessary here, with no opt-out option for user as far as I know.

One workaround I can think of, that'd also respect systemd's exclusive use of /sys/fs/cgroup, would be to write a script that'd find and template major:minor numbers into a unit file and do daemon-reload, to bypass incorrect detection of these in systemd.
That'd have to be run on every boot and seem to be quite an ugly hack.

**Comment by mk-fg** [comment]
> One workaround I can think of ... and template major:minor numbers into a unit file and do daemon-reload, to bypass incorrect detection of these in systemd.

Correction:
This won't work either, as systemd doesn't seem to allow specifying raw major:minor numbers in such options in any way.

So afaict there's no clean workaround for this, can only tweak io.max outside of systemd and hope that it won't reset or revert these back, unfortunately.

**Comment by poettering** [comment]
So the thing is that we need to set these limits on block devices that actually have an IO elavator associated with them. Partition block devices do not but their containing devices do. Hence we do some minimal traversal of devices to find the containing device. This might need better documentation.

Now you appear to use LVM. For that we dont do the full traversal because volumes might span multiple devices. So you end up with an unenforcable policy the way you are doing it...

**Comment by mk-fg** [comment]
Ah, fair enough, oh well.
Would be nice if docs also pointed to some rationale for this limitation, if it's spelled out somewhere, since as these limits seem to work when set manually, it looks strangely unnecessary, without digging into commits and code that implements it, at least.
