### ISSUE TITLE
When ran as regular user, systemctl status systemd-udevd shows an incorrect warning

### ISSUE THREAD

**Issue by ht990332** [systemd/systemd#14281]
when ran as regular use, systemctl status systemd-udevd shows an incorrect warning.

> 
>  systemctl status systemd-udevd
> ● systemd-udevd.service - udev Kernel Device Manager
>      Loaded: loaded (/usr/lib/systemd/system/systemd-udevd.service; static; vendor >
>      Active: active (running) since Sat 2019-12-07 23:29:43 EET; 19min ago
> TriggeredBy: ● systemd-udevd-kernel.socket
>              ● systemd-udevd-control.socket
>        Docs: man:systemd-udevd.service(8)
>              man:udev(7)
>    Main PID: 513 (systemd-udevd)
>      Status: "Processing with 24 children at max"
>       Tasks: 1
>      Memory: 42.9M
>      CGroup: /system.slice/systemd-udevd.service
>              └─513 /usr/lib/systemd/systemd-udevd
> 
> Warning: Journal has been rotated since unit was started. Log output is incomplete

This is incorrect. The journal was not rotated. I simply ran the command as regular user without running su first.

**Comment by poettering** [comment]
So if you run the same command as root when you see this, doesit show log output then without claiming output was incomplete?

**Comment by poettering** [comment]
(also, please always fill in the supplied form, we ask for that for a reason)

**Comment by hussamT** [comment]
Sorry for not following the form. I must have been in a hurry
As root

```
Loaded: loaded (/usr/lib/systemd/system/systemd-udevd.service; static; vendor preset: disabled)
     Active: active (running) since Fri 2019-12-13 12:51:53 EET; 1h 34min ago
TriggeredBy: ● systemd-udevd-kernel.socket
             ● systemd-udevd-control.socket
       Docs: man:systemd-udevd.service(8)
             man:udev(7)
   Main PID: 474 (systemd-udevd)
     Status: "Processing with 24 children at max"
      Tasks: 1
     Memory: 43.2M
     CGroup: /system.slice/systemd-udevd.service
             └─474 /usr/lib/systemd/systemd-udevd

Dec 13 12:51:54 hades mtp-probe[504]: bus: 1, device: 5 was not an MTP device
Dec 13 12:51:54 hades mtp-probe[506]: checking bus 1, device 2: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
Dec 13 12:51:54 hades mtp-probe[506]: bus: 1, device: 2 was not an MTP device
Dec 13 12:51:54 hades systemd-udevd[484]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 13 12:51:55 hades systemd-udevd[482]: Using default interface naming scheme 'v243'.
Dec 13 12:51:55 hades systemd-udevd[482]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 13 12:51:55 hades systemd-udevd[492]: Using default interface naming scheme 'v243'.
Dec 13 12:51:55 hades systemd-udevd[492]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 13 12:51:56 hades systemd-udevd[483]: controlC0: Process '/usr/bin/alsactl restore 0' failed with exit code 99.
Dec 13 12:51:56 hades systemd-udevd[485]: controlC1: Process '/usr/bin/alsactl restore 1' failed with exit code 99.
lines 2-24/24 (END)

```

as regular user:
```

systemctl status systemd-udevd
● systemd-udevd.service - udev Kernel Device Manager
     Loaded: loaded (/usr/lib/systemd/system/systemd-udevd.service; static; vendor >
     Active: active (running) since Fri 2019-12-13 12:51:53 EET; 1h 34min ago
TriggeredBy: ● systemd-udevd-kernel.socket
             ● systemd-udevd-control.socket
       Docs: man:systemd-udevd.service(8)
             man:udev(7)
   Main PID: 474 (systemd-udevd)
     Status: "Processing with 24 children at max"
      Tasks: 1
     Memory: 43.2M
     CGroup: /system.slice/systemd-udevd.service
             └─474 /usr/lib/systemd/systemd-udevd

Warning: Journal has been rotated since unit was started. Log output is incomplete >

```

**Comment by anitazha** [comment]
I'm under the impression this is normal behavior. Since `systemd-udevd` is a system service, the journal logs shown in the `systemctl status` output are not normally readable to non-root users (unless they were given access to read system journals).

**Comment by hussamT** [comment]
@anitazha , the issue here is the incorrect warning message.
"Warning: Journal has been rotated since unit was started. Log output is incomplete".
The journal was not rotated since the last boot.
