### ISSUE TITLE
calling SetBrightness with --expect-reply=no does not change the brightness

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#14288]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 when calling ` busctl  --expect-reply=no call org.freedesktop.login1 /org/freedesktop/login1/session/self org.freedesktop.login1.Session SetBrightness ssu "backlight" "intel_backlight" 700` I expect the brightness to change.

**Unexpected behaviour you saw**
 > Brightness didn't change

**Steps to reproduce the problem**
Run the command above.

I double checked that the same command without --expect-reply works correctly. I also did a quick `busctl monitor` to check what was going on, but all messages are exchanged as expected.

systemd-logind calls GetConnectionUnixProcessID and gets an error, but this is "expected"

Using --expect-reply is explicitely mentionned as the correct way to do things in https://github.com/systemd/systemd/commit/b3be8c46af32b1135b0e118415eb2060bd69ae1a so I expect logind to deal with that error...

**Comment by poettering** [comment]
Hmmm. I figure the problem is not so much to set the no-reply-expected flag but to disconnect immediately after issuing the request. Not sure we can fix that. Might be something document somewhere and accept.

**Comment by boucman** [comment]
maybe change the --expect-reply to accept a delay...

busctl --expect-reply=100ms would set the no-reply flag and wait for a reply for 100ms and terminate (without an error) if there is no such reply

**Comment by poettering** [comment]
that exists, it's called "--timeout=". i.e. drop the --expect-reply= and say "--timeout="

**Comment by boucman** [comment]
indeed that works... kinda not what I would have expected, but that's good enough
