### ISSUE TITLE
nspawn: can't set network namspece path in OCI spec

### ISSUE THREAD

**Issue by zhsj** [systemd/systemd#14289]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Debian/testing

**Expected behaviour you didn't see**
 > ...

**Unexpected behaviour you saw**
 > systemd-nspawn failed to launch

```
$ sudo systemd-nspawn --oci-bundle=test                                             
--network-namespace-path= cannot be combined with other network options.
```

If I repeat `--network-namespace-path=` in command, it won't complain.

```
sudo systemd-nspawn --oci-bundle=test --network-namespace-path=/proc/36932/ns/net
```

**Steps to reproduce the problem**

Create an OCI bundle and spec json, put `path` in `namespace` section, like
```
        "namespaces": [
            {
                "type": "network",
                "path": "/proc/36932/ns/net"
            }
        ]
```

**Comment by poettering** [comment]
Hmm, I think I would prefer if we'd simply allow combination of --private-network and -network-namespace-path= instead. (not combination of the latter and other options, but just of these two). Any chance you can rework the patch accordingly?

**Comment by poettering** [comment]
Urks that comment should of course have ended up on #14290...
