### ISSUE TITLE
LinkLocalAddressing results in additional IP address, and networkd denies knowledge of it

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#14285]
**systemd version the issue has been seen with**
> systemd 244

**Used distribution**
 > Debian testing x86_64

**Unexpected behaviour you saw**
 > The option `LinkLocalAddressing` assigns an additional ip address to the link,
without any kind of feedback. It will even claim `we don't remember`.

Please make this somewhat more transparent, I miss-understood the option, but it should not be that hard to trace the origin of a setting.

**Steps to reproduce the problem**

Configure an interface like this:
```
[Match]
Name=eno1

[Network]
LinkLocalAddressing=ipv4
IPv6AcceptRA=no
Address=192.168.0.11/24
Gateway=192.168.0.1
DNS=8.8.8.8
DNS=8.8.4.4
```

restart systemd-networkd (twice if the configuration is new).
you will end up with a `169.254.x.x` IP address on the link,
and networkd denies any knowledge:

```
** systemd-networkd[4141]: eno1: Kernel removed an address we don't remember: 169.254.125.141/16 (valid forever), ignoring.
```

**Comment by yuwata** [comment]
I think the warning is harmless. Maybe we should lower the log level. @ssahani WDYT?
