### ISSUE TITLE
PrivateUsers=0 isn't handled as --private-users=0 is

### ISSUE THREAD

**Issue by poige** [systemd/systemd#14291]
**systemd version the issue has been seen with**
> 237

— I'd also add into your questionary template a snippet to run, like: `systemctl --version`

> > **NOTE:** Do not submit bug reports about anything but the two most recently released systemd versions upstream!
For older version please use distribution trackers (see https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#filing-issues).

— how about adding to the questionary a brief info how to find out what those two most recent releases are?

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > `docker run` works inside the nspawn

**Unexpected behaviour you saw**
 >
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/docker/44c0df0967faf0aeda548c2a1a20d5bb77e7414a9e80dbb9acd884ad828037f4: read-only file system\"": unknown.
```

**Steps to reproduce the problem**

Try using `PrivateUsers=0` in nspawn-config file. To get it working, omit it there and over-ride `systemd-nspawn@…` with `ExecStart=` that uses `--private-users=0`  explicitly.

**Comment by poettering** [comment]
This behaviour is explicitly documented in the man page:

https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#-U

**Comment by poige** [comment]
As far as I remember there was no `-U` in custom `ExecStart=` still it failed to work unless `--private-users=0` was given.
