### ISSUE TITLE
sd-umount: Failed to unmount /oldroot: Device or resource busy

### ISSUE THREAD

**Issue by dkadioglu** [systemd/systemd#14298]
**systemd version the issue has been seen with**
> since 243

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > silent shutdown without errors (as it was the case until 242)

**Unexpected behaviour you saw**
 > error messages during shutdown:
sd-umount[1334]: Failed to unmount /oldroot: Device or resource busy
shutdown[1]: Failed to finalize file systems, ignoring.

**Steps to reproduce the problem**
happens on every shutdown

I already tried to figure out some details regarding the shutdown process (following https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1): https://pastebin.com/raw/Ws6RRmNM
As far as I can see, there are no errors regarding unmounting filesystems.

Is there anything else I can do to find out the reason for these error messages?

**Comment by poettering** [comment]
what is /oldroot though? That looks like some left-over mount point from your distro's initrd?

Figure out what that is and what keeps it busy (`fuser -vm /oldroot` before shutting down might help).

Either way, this looks like something to ask your distro for help about first, and let the maintainers of it elevate the issue to us if there's really an issue with systemd. From the looks of it, this is some initrd issue downstream, not a systemd issue upstream. Hope that makes sense.

**Comment by vith** [comment]
https://bugs.archlinux.org/task/63697 is the downstream issue for Arch Linux

here, https://github.com/systemd/systemd/issues/14981 is apparently related
