### ISSUE TITLE
Route MTUs for DHCP

### ISSUE THREAD

**Issue by sargun** [systemd/systemd#14302]
**Is your feature request related to a problem? Please describe.**
I would like a way to configure route MTUs versus link MTUs for DHCP.

**Describe the solution you'd like**
I would like the DHCP option to have a `[UseMTU]` flag, which can be used to configure systemd to have MTUs on the routes, versus on the link itself. This allows ingress traffic at the size of the link MTU, but the TCP MSS, and egress traffic will never exceed the MTU as suggested by DHCP.

**Comment by ssahani** [comment]
Can you paste a Wireshark dump how that  looks like ?

**Comment by sargun** [comment]
@ssahani So, if you set the link MTU, it makes it so that ingress packets bigger than that will be dropped. On the other hand, if you set the route MTU(s), then it will allow for ingress packets which are smaller than or equal to the link MTU. But, the kernel will not advertise an MSS greater than the route MTU.

This is useful for transitioning systems from small frames to jumbo frames. First, you upgrade your route MTUs, and then you upgrade your link MTUs.

**Comment by ssahani** [comment]
Route MTU the currently supported by the static configs not the DHCP. we can add that.

**Comment by ssahani** [comment]
@sargun PTAL https://github.com/systemd/systemd/issues/14302
