### ISSUE TITLE
nspawn does not create `/lib64 → /usr/lib64` symlink on s390 and aarch64

### ISSUE THREAD

**Issue by larskarlitski** [systemd/systemd#14311]
**systemd version the issue has been seen with**

239-19.el8 on s390. The problem is still there [upstream](https://github.com/systemd/systemd/blob/master/src/shared/base-filesystem.c#L41).

**Expected behaviour you didn't see**

Running systemd-nspawn with a s390 RHEL image doesn't work, because nspawn doesn't create the `lib64` symlink. The linker there is `/lib/ld64.so.1`, which is a symlink to `/lib64/ld64.so.1`.

It happens to work on aarch64, because the linker there is a relative path: `/lib/ld-linux-aarch64.so.1 -> ../lib64/ld-2.30.so`

**Comment by gicmo** [comment]
Small reproducer:

On a S390x machine:
```
mkdir -p /tmp/container
mount --bind /usr /tmp/container/usr

# systemd-nspawn -D /tmp/container
Spawning container bla on /tmp/container.
Press ^] three times within 1s to kill container.
execv(/bin/bash, /bin/sh) failed: No such file or directory
Container bla failed with error code 1.
```

**Comment by gicmo** [comment]
Same is also true for ppc64le (`Linux ibm-p9z-21-lp20.fs.lab.eng.bos.redhat.com 4.18.0-161.el8.ppc64le #1 SMP Fri Dec 6 14:47:06 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux`):

```
findmnt:
/tmp/container/usr                  /dev/mapper/rhel_ibm--p9z--21--lp20-root[/usr]

systemd-nspawn -D container/
Spawning container container on /tmp/container.
Press ^] three times within 1s to kill container.
execv(/bin/bash, /bin/sh) failed: No such file or directory
Container container failed with error code 1.
```
Here: `[Requesting program interpreter: /lib64/ld64.so.2]`

**Comment by poettering** [comment]
Here's the list of dirs and symlinks we create automatically:

https://github.com/systemd/systemd/blob/master/src/shared/base-filesystem.c#L30

I don't know what the dynamic loader on those archs is called. Any chance you can check that and prep a quick PR?

**Comment by larskarlitski** [comment]
> I don't know what the dynamic loader on those archs is called. Any chance you can check that and prep a quick PR?

A patch wouldn't need to addaa list of dynamic loaders, just the `/lib64 → /usr/lib64` link on 64 bit architectures. Maybe it's enough to drop the `#if defined(__i386__) || defined(__x86_64__)`? Does systemd support any architectures which are not 64 bits?

**Comment by boucman** [comment]
ARM 32 at least...

**Comment by poettering** [comment]
@larskarlitski it's not sufficient to just slightly expand the ifdeffery. We create these links only when the ld.so binary is in those dirs, and that might be placed in two different dirs... So you need to specify the name of the ld.so binary in the fourth column (for x86-64 it's `ld-linux-x86-64.so.2`), and the source dir to link from in the third (for x86-64 there are two candidates for that: `usr/lib/x86_64-linux-gnu` (for debian style multiarch) and `usr/lib64` (for redhat style simple scheme).

It's fine if your patch doesn't cover the debian case for now, they can add it in if they run into this. But you still need to supply the ld.so binary name to look for and the source dir to link from that is used on fedora/rhel.

(Background: distros set all this stuff up slightly differently, and there might even be distros that don't do the "64" suffix in /usr at all — i.e. are pure 64bit without legacy — and just have the x86-64 stuff in /usr/lib-<arch> directly. Hence we must search for the right place at multiple locations.)

**Comment by poettering** [comment]
@gicmo @larskarlitski ping?
