### ISSUE TITLE
systemctl suspend spins up sleeping disks

### ISSUE THREAD

**Issue by ossilator** [systemd/systemd#14310]
**systemd version the issue has been seen with**
243

**Used distribution**
debian unstable

**Unexpected behaviour you saw**
after the X server suspends (monitor goes blank), instead of completing suspension right away, the system powers up the sleeping harddrives. _then_ it suspends.

**Steps to reproduce the problem**
send all hdds to sleep via hdparm -y. then issue `systemctl suspend`.

my hdds are configured via hdparm -S and -y to sleep most of the time, as the system lives off an ssd. the pointless wakeups add ~5 seconds delay to the suspension, and shorten the disks' life.

i didn't observe this behavior with pm-utils' suspend, even while i was already using systemd.

the journal contains messages of this sort:
```
kernel: Filesystems sync: 0.009 seconds
...
kernel: sd 1:0:0:0: [sdb] Synchronizing SCSI cache
kernel: sd 1:0:0:0: [sdb] Stopping disk
```
which might be related, but probably aren't (the timestamps are all identical and incorrectly post-wakeup, so this is done very late by the kernel itself, and i think i saw this in pm-utils times as well).
there are no other disk-related log entries, and i don't know where to start looking.

**Comment by poettering** [comment]
systemd does not resume any disks. we really just echo stuff to the relevant files in /sys, and that's it.

Maybe some drop-in in /usr/lib/systemd/system-sleep/ does?

Are you sure the kernel doesn't do this on its own? try by echoing the right stuff into the sys files on the shell...

**Comment by ossilator** [comment]
hmm, indeed, `echo mem > /sys/power/state` does the same. i guess i upgraded the kernel around the same time i switched away from pm-utils (the latter was indirectly motivated by something breaking due to an upgrade, so it's plausible more stuff changed at that time).
will google some more and add a comment for posterity if i find something.
