### ISSUE TITLE
Modify behavior of "Unmanaged" attribute

### ISSUE THREAD

**Issue by Howitzer105mm** [systemd/systemd#14316]
**Is your feature request related to a problem? Please describe.**
I am contributing a modification to the OpenBMC network behavior.  The Redfish and IPMI actions for taking an ethernet interface up/down pass their request to the phosphor-network daemon, which in turn writes the systemd /etc/systemd/network/00-bmc-eth(x).network file. The systemd-networkd is then restarted to collect the new state changes.
The goal is to allow Redfish/IPMI to perform the equivalent of a "ip link eth0 down" or "up", and make the change persist between BMC reboots.

**Describe the solution you'd like**
I'm looking for a way for a systemctl restart of the systemd-networkd process that takes the active interface down that does not require also sending an ioctl command taking the interface down.

**Describe alternatives you've considered**
Currently, in order to get the "down" behavior a change has been submitted to send the eth(x) an IFF_UP/~IFF_UP ioctl command, and write "Unmanaged=yes" to the ".network" file. The ioctl takes the interface down, and the "Unmanaged" setting makes the interface stay down in the event of a BMC reboot.

**Comment by yuwata** [comment]
Related to #9956.

**Comment by Howitzer105mm** [comment]
It is hard to tell if that thread solves my issue or not. It seems like a complicated solution.
I'm not looking for networkd to sync with "ip tools" or ifconfig or xyz's alteration of the IFF_UP flag.  I want a way to tell networkd that I don't want the link to have IFF_UP set.  The Unmanaged=yes flag does not do this.
If I use "ip link set down dev eth0", and the use "ip addr" the **<BROADCAST,MULTICAST,UP,LOWER_UP>** content changes to **<BROADCAST,MULTICAST>**. This indicates the NIC port is not accepting any network traffic. The NIC doesn't even have a ipv4 link local IP assigned.  There's no way for traffic to be passed.
Intel servers have three NIC's.  There are customers who wish to use one, two, or all three ports.  Some want to disable the extra HW to avoid an incorrect port from being used/misused.

For my purposes a new [Network] entry "InterfaceEnabled=<bool>" seems to be all that would be necessary.  Leave the config file alone. I find the OpenBMC behavior of IFF_DOWN deleting valid configuration data a surprising event.  If a valid static address set is written to the config file using "ip link set down dev x" followed by "ip link set up dev x" (or a networkctl equiv) should result in the NIC going "dark", and then returning to a functioning state with the same parameters that were active before being told to go "down".

I'm not asking for "ip link" to be honored.  I'm asking for a config file element that tells networkd the NIC should be !IFF_UP.  If networkctl is the systemd networkd way of modifying the config file for this to happen, that seems like a workable solution.

I've looked through the networkd.conf content, and have not found such a config file element.

**Comment by yuwata** [comment]
I guess PR #16228 achieves what you want. Please try v248 or newer. Closing. If the PR does not solve your issue, please request to reopen this.
