### ISSUE TITLE
systemd kills user's scopes/sessions before shutdown service

### ISSUE THREAD

**Issue by lari-arjun** [systemd/systemd#14318]
I am designing a stop service which has to be run before the kill of user's scope / session .
As the reboot or shutdown are being initiated the systemd kill all the users which are in user's.slice
before the script ran so the script is of no use if the user session are killed first then the stop.service
stop.service

[Unit]
Description=Service to auto stop the EBS application
DefaultDependencies=no
Before=shutdown.target
RefuseManualStart=true

[Service]
Type=oneshot
ExecStart=/startdb/stop/stop.sh

[Install]
WantedBy=shutdown.target reboot.target
~~~

**Comment by boucman** [comment]
This is a issue tracker, not a support forum, those questions are better asked on the mailing list

That being said, what you need to do is to do a normal service 
empty ExecStart
After=user.slice
ExecStop=your script
WantedBy=user.slice

and that should do the trick

**Comment by lari-arjun** [comment]
Thankyou for your response https://github.com/systemd/systemd/issues/14318#issuecomment-564885213

but the issue is when we initiate init 6 and shutdown it will kill all the user processes running before that script

**Comment by boucman** [comment]
init 6 ??

And I still think I solve your problem.
 by setting After=user.slice, I guarantee that the unit will be /stopped before/ user.slice (ordering dependencies create the inverted order for shutdown)

**Comment by lari-arjun** [comment]
I have done the changes in the current stop service but it is not waiting for the user session which are in users.slice, it abruptly kill the user session

├─1 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
├─user.slice
│ └─user-228069.slice
│   └─session-2.scope
│     ├─2426 sshd: user1 [priv]
│     ├─2430 sshd: user2@pts/0
│     ├─2431 bash
│     ├─2575 systemd-cgls
│     └─2576 less

**Comment by boucman** [comment]
let's move to the mailing list, this is not the right place to do a proper debugging session

**Comment by poettering** [comment]
Sorry, but this is not a support forum, and the issue submission form should have made that very clear. Moreover even if it was, at the very least, specify the systemd version and distro you are using.

**Comment by lari-arjun** [comment]
Can someone share the list of mailing where i can post my query ?

**Comment by poettering** [comment]
@lari-arjun just click on the provided link when filing an issue. it will lead you to this:

https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#contributing
