### ISSUE TITLE
network-generator: Fails to parse ip address if client_hostname is missing

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#14319]
**systemd version the issue has been seen with**
> 2.44

**Used distribution**
 > None/Buildroot

**Expected behaviour you didn't see**
 > systemd-network-generator.service parsing the kernel commandline

**Unexpected behaviour you saw**
 > systemd-network-generator.service failing with Invalid argument

**Steps to reproduce the problem**
Boot a kernel with
```
root=/dev/nfs nfsroot=10.99.37.240:/srv/netroot,v3,tcp ip=10.99.37.44::10.99.10.1:255.255.0.0::enp3s0:off
```
This is a valid commandline for the kernel and common initrd's, so it would be expected that it is understood. (See: https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt)

What happens is this:
```
Dec 11 17:38:35 buildroot systemd-network-generator[695]: Failed to parse kernel command line: Invalid argument
Dec 11 17:38:35 buildroot systemd[1]: systemd-network-generator.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 17:38:35 buildroot systemd[1]: systemd-network-generator.service: Failed with result 'exit-code'.
Dec 11 17:38:35 buildroot systemd[1]: Failed to start Generate network units from Kernel command line.
```

Unless the user has configured the interface in the real root filesystem to match the kernel parameters, networkd will sever the NFS connection.

**Comment by nolange** [comment]
A similar problem will arise if gateway-ip is missing, as it would be on isolated networks.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #14321. If possible, please test the PR.

**Comment by nolange** [comment]
Will try to find time to test it tomorrow, thanks. Can you fix a potentially missing gateway-ip too?

**Comment by yuwata** [comment]
> Can you fix a potentially missing gateway-ip too?

I cannot reproduce the issue. Could you provide an example?

**Comment by nolange** [comment]
Yeah, my bad. Wasn't looking at the code but the expressions on line 21 and 22. Might fix that instead 😉

**Comment by nolange** [comment]
Tested PR, works for me. Thanks.
