### ISSUE TITLE
systemd-nspawn and sh: can't access tty; job control turned off

### ISSUE THREAD

**Issue by iby** [systemd/systemd#1431]
Trying to launch alpine container on CoreOS via toolbox and getting `sh: can't access tty; job control turned off` warning. I've read about it in BusyBox [FAQ](http://www.busybox.net/FAQ.html#job_control), which didn't work for me, and tried [this](http://superuser.com/a/418557/384955), also without any luck. 

This works without any issues nor tweaks with docker. Is there some parameter that should be passed to nspawn like --interactive with docker? Or is this something completely different?

**Comment by poettering** [comment]
Which systemd version is this? This works fine here.

What are you running inside the container precisely? just a shell as PID 1?

Does this work with bash?

**Comment by iby** [comment]
I use CoreOS [766.4](https://coreos.com/releases/#766.4.0), systemd version 222. Is that the right way to get it?

``` sh
$ systemctl --version
systemd 222
-PAM +AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

I'm trying to use my [docker image](https://github.com/ianbytchek/docker-coreos-ansible-toolbox) that's based on Alpine Linux. From what I see [here](https://github.com/coreos/toolbox/blob/bc6a8c4754c14e66c26fa21a48134a90a0592e9d/toolbox#L31-L38), it gets launched with nspawn like this:

``` sh
sudo systemd-nspawn \
    --directory="${machinepath}" \
    --capability=all \
    --share-system \
    --bind=/:/media/root \
    --bind=/usr:/media/root/usr \
    --bind=/run:/media/root/run \
    --user="${TOOLBOX_USER}" "$@"
```

I pass only `--quiet` option to suppress the noise. This happens without specifying any command to the container or when specifying `sh`. If I run Python, for example, it doesn't complain and works perfectly.

``` sh
$ toolbox --quiet
-sh: can't access tty; job control turned off
ip-10-1-1-254:~# 
```

Bash also doesn't work smoothly.

``` sh
$ toolbox --quiet
-bash: cannot set terminal process group (-1): Not a tty
-bash: no job control in this shell
ip-10-1-1-254:~# 
```

I did have some luck with passing `--quiet sh -c 'exec sh </dev/console >/dev/console 2>&1'`, but didn't find a way how to amend my image to make this a default command (the one that nspawn calls automatically or one configured to be the default command in Alpine). Besides, this doesn't seem to load ash profile, or something wrong happens with it.

``` sh
$ toolbox --quiet sh -c 'exec sh </dev/console >/dev/console 2>&1'
/ #
```

**Comment by poettering** [comment]
First, please retry with something more recent. Upstream issues should only be reported against the two most recent versions of systemd. Otherwise the right place to file a bug is downstream.

Also, if this involves some random docker images, then I am not sure I can help you. Please reduce this to a minimal test case, such as showing me that a normal fedora cloud image has the same issues, but I am not going to install coreos and then some docker image to test this. Sorry.

Maybe @alban or so can help you? Or alban, you know somebody who can help you?

**Comment by iby** [comment]
No problems, I should have tried this with the latest release. In fact, I just did with 225 and it gives me the same message. I understand your "feelings" towards random docker images, but this is [alpine](https://github.com/gliderlabs/docker-alpine) / [busybox](https://github.com/progrium/busybox) that's by far not the least thing in docker context. I've also tried this with ubuntu and fedora, both work fine.

I'll ask alpine folks what's going on, but I'd really appreciate if there are any ideas why this might be happening and how this can be cured. After all this works with docker and busybox has this at the top of the faq… The problem might get kicked around from place to place.

**Comment by johannbg** [comment]
This is just misconfiguration inittab in busybox which triggers this and has nothing to do with systemd.

Try echo ‘console::respawn:/bin/getty 38400 /dev/console’ > /path/to/busybox/etc/inittab

Or if you want you could run busybox natively with nspawsn based on some docker image something like this should work ( then you can just extend it as you need/want )...

cd /var/lib/machines/
pip install git+https://github.com/larsks/undocker/
docker pull busybox
docker save busybox | undocker -o busybox
echo ‘console::respawn:/bin/getty 38400 /dev/console’ > busybox/etc/inittab
systemd-nspawn -D busybox /bin/sh

**Comment by iby** [comment]
Thanks for input, that didn't help unfortunately. Tried pure busybox, nspawn says `Directory /var/lib/toolbox/core-busybox-latest lacks the binary to execute or doesn't look like a binary tree. Refusing.` I sticked with alpine for time sake.

``` sh
$ docker run -ti ianbytchek/alpine cat /etc/inittab
# /etc/inittab

::sysinit:/sbin/rc sysinit
::wait:/sbin/rc default

# Set up a couple of getty's
tty1::respawn:/sbin/getty 38400 tty1
tty2::respawn:/sbin/getty 38400 tty2
tty3::respawn:/sbin/getty 38400 tty3
tty4::respawn:/sbin/getty 38400 tty4
tty5::respawn:/sbin/getty 38400 tty5
tty6::respawn:/sbin/getty 38400 tty6

# Put a getty on the serial port
#ttyS0::respawn:/sbin/getty -L ttyS0 115200 vt100

# Stuff to do for the 3-finger salute
::ctrlaltdel:/sbin/reboot

# Stuff to do before rebooting
::shutdown:/sbin/rc shutdown

console::respawn:/sbin/getty 38400 /dev/console
```

I don't have easy python access on this machine. Using the CoreOS native way to undocker.

``` sh
DOCKER_IMAGE=ianbytchek/alpine
USER=root
DIRECTORY="/var/lib/toolbox"

machinename=$(echo "${USER}-${DOCKER_IMAGE}" | sed -r 's/[^a-zA-Z0-9_.-]/-/g')
machinepath="${DIRECTORY}/${machinename}"
osrelease="${machinepath}/etc/os-release"

sudo mkdir -p "${machinepath}"
sudo chown ${USER}: "${machinepath}"

docker pull "${DOCKER_IMAGE}"
docker run --name=${machinename} "${DOCKER_IMAGE}" /bin/true
docker export ${machinename} | sudo tar -x -C "${machinepath}" -f -
docker rm ${machinename}
sudo touch ${osrelease}

sudo systemd-nspawn --directory="${machinepath}" --user="${USER}" sh
```

And getting the same `sh: can't access tty; job control turned off` message.

``` sh
Spawning container root-ianbytchek-alpine on /var/lib/toolbox/root-ianbytchek-alpine.
Press ^] three times within 1s to kill container.
Timezone UTC does not exist in container, not updating container timezone.
sh: can't access tty; job control turned off
/ # 
```

**Comment by johannbg** [comment]
See http://www.busybox.net/FAQ.html#job_control

**Comment by iby** [comment]
This is on the second line of my first post.

**Comment by zsoltm** [comment]
It looks like Alpine lacks some tty initialisation stuff, but how about this workaround until then:

```
core@nasedli ~ $ toolbox getty -nl /bin/sh 0 /dev/console
Spawning container core-alpine-3.3 on /var/lib/toolbox/core-alpine-3.3.
Press ^] three times within 1s to kill container.
Timezone UTC does not exist in container, not updating container timezone.

/ # sleep 5s
^Z[1]+  Stopped                    sleep 5s
/ # 
```

**Comment by ganguin** [comment]
FTR same issue as #8577 and #8704, opening /dev/tty returns `ENXIO`, calling `setsid -c -w /bin/sh` workarounds this 3 issues. (nspawn calls `setsid()` but not `ioctl(STDIN_FILENO, TIOCSCTTY, 1)` as `setsid -c` does)

However, regarding posix, opening /dev/tty should not fail. The right solution is probably what @poettering suggest in #8577: allocate /dev/console as a pty instead of mounting it from the outside.

Or could the `ioctl(STDIN_FILENO, TIOCSCTTY, 1)` be done in the nspawn code?
