### ISSUE TITLE
networkctl: dhcp subcommand

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14334]
**Is your feature request related to a problem? Please describe.**

As part of a large set of integration tests, I set up a virtual network using systemd-nspawn, systemd-run and the iproute2 commands. The containers run a DHCP server which the integration tests sometimes use to get an IP to connect to that specific server. To do the DHCP request, I currently use dhclient or dhcpcd, which both either never exit or fork into the background (depending on the options, both undesirable). 

**Describe the solution you'd like**

Ideally, I'd be able to use `networkctl dhcp interface` to have systemd do a DHCP request, configure the interface with the resulting IP address and lifetime and exit.

**Describe alternatives you've considered**

I considered adding a network file that matches based on a `-dhcp` suffix but that approach requires encoding all configuration information in the network interface name so networkd picks up the right network file (which doesn't really scale due to the Linux interface name size limit). It's also a lot more implicit to have dynamically created interfaces in the tests automatically configured by systemd-networkd compared to the explicit configuration that would be provided if `networkctl dhcp` was added.

I'm definitely not advocating networkctl should do everything iproute2 already does. It's just that iproute2 does not do DHCP and it would be nice to be able to use networkctl (or more generally, systemd's DHCP code) to augment the lack of DHCP in iproute2.

`dhclient` and `dhcpcd` work, but they are slow and do not seem to provide options to exit immediately after configuring the interface which requires me to do extra process management to make sure they are cleaned up correctly. Additionally, `dhcpcd` does not work in a container by default as it tries to write to `/proc`. It would be great to have `networkctl` as an alternative here.

I'd be willing to look into implementing this but I'm well aware that this might be considered out-of-scope for networkctl so I'd like confirmation on whether something like this would even be accepted before doing any implementation work.

**Comment by yuwata** [comment]
Is it not enough for you that `networkctl renew eth0`? If not, could you elaborate more what `networkctl dhcp` does?

**Comment by DaanDeMeyer** [comment]
`renew` only reconfigures interfaces managed by networkd that have a corresponding network file with the DCHP option enabled (at least that's what the docs seem to imply). I want to be able to do `networkctl dhcp <my-interface>` on an interface I just created with iproute2 to have networkctl perform a DHCP request, wait for a response, apply the response data to the interface and exit.

It doesn't necessarily have to be in `networkctl`, I really just want access to networkd's DHCP code client from the command line without requiring systemd to manage the interface. All the current solutions (NetworkManager, dhcpcd, dhclient, systemd-networkd) continue to manage the interface after doing the DHCP request. I want nothing more than: 

1. Do DHCP request
2. Wait for DHCP response
3. Configure interface with response (ip, lifetime, ...).
4. exit

**Comment by yuwata** [comment]
So, if I understand the request correctly, it can be achieved by the following steps:
1. create the corresponding .network file with `DHCP=yes`.
2. `networkctl reload`
3. create interface by ip command
4. `systemd-networkd-wait-online -i <interface>`

**Comment by DaanDeMeyer** [comment]
That works, but has the following disadvantages:

- networkd will be managing the interface and doing renewals which I would prefer to avoid.
- It's not immediately clear from the test code that the created interface will have its DHCP management done by systemd-networkd.
- There's no way to release the DHCP address manually when it is no longer needed (aside from restarting networkd each time).
- I have to manage files in /etc/systemd/network when doing tests which requires extra cleanup and so forth.
- Not all interfaces require dhcp so I have to name interfaces that require dhcp differently so only those are matched by networkd.

Compare this with:

- `networkctl dhcp request <interface>`
- Do stuff with interface
- `networkctl dhcp release <interface>`

Which would be a lot simpler imo. Other options such as renew could be added as well. The tool could be named systemd-dhcp as well and be completely independent from networkctl. I don't think it would necessarily be a lot of code as all the required code should already be in systemd. It would just parse some arguments, do the DHCP operation requested by the user and exit when its done.

I think systemd has a very simple and fast DHCP implementation, it's just unfortunate that it's not easily accessible for use in one-off stuff like tests.

If the DHCP stuff was available in libsystemd I'd implement systemd-dhcp outside of systemd but that would require exposing a DHCP API in libsystemd which seems like a much bigger change compared to adding a little command line tool.

**Comment by DaanDeMeyer** [comment]
I was hoping to add a little command line tool which would basically do the same as the steps you listed (except creating the interface) so I could do `networkctl dhcp <interface>` or `systemd-dhcp <interface>`. The one difference would be that it wouldn't do anything anymore with the interface after exiting (no renewals, no releasing, no forking to the background, ...).

I suppose I could implement it completely outside of systemd, but that would mean implementing DHCP myself which feels wasteful when there's a perfectly fine implementation of DHCP in systemd.

**Comment by DaanDeMeyer** [comment]
My use case is probably too specific for something to be included inside systemd. It's probably better to implement it outside of systemd.

**Comment by yuwata** [comment]
Sorry, but I think so.

**Comment by ssahani** [comment]
Well these features available in proprietary software. It's a common use case .

**Comment by DaanDeMeyer** [comment]
Having the libsystemd DHCP library publicly available would make implementing these tools outside systemd a lot easier. Was it ever considered exporting more of systemd's internal API's in libsystemd?

**Comment by ssahani** [comment]
Yeah I see what you saying https://github.com/systemd/systemd/issues/13164 .But it's not really scope with networkd . May be https://github.com/vmware/network-config-manager will help you.
