### ISSUE TITLE
systemd (please provide solution

### ISSUE THREAD

**Issue by ravikiran300** [systemd/systemd#14332]
1)while running systemd command iam getting error
Trying to run as user instance,but the system has not been booted with systemd

2)systemctl --user --system
Failed to parse reply: failed to execute program org.freedesktop.systemd1:success
NOTE:this error comes while running any command

3)
systemctl
failed to list units:failed to execute program org.freedesktop.systemd1:success

iam getting this errors and not able boot with systemd and no process related to systemd is running
please i invoked init=/lib/system/systemd at proc/cmdline not working

system version is 232 i cant use above and below version of systemd because of dependencies

4)systemd --user --systemd
cannot determine cgroup we are running in:no medium found
detected architecture x86-84
failed to execute manger object:no medium found

**Comment by yuwata** [comment]
I guess dbus is not running.

Anyway, this is not a support page, and v232 is too old here. Please use the mailing list instead.
