### ISSUE TITLE
Wireguard netdev not created, 'operation not supported' when using in-kernel wg (DKMS fine)

### ISSUE THREAD

**Issue by OJFord** [systemd/systemd#14343]
**systemd version the issue has been seen with**
> systemd 244 (244-1-arch)

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > wg0: netdev ready

**Unexpected behaviour you saw**
 > wg0: netdev could not be created: Operation not supported

**Steps to reproduce the problem**

1. `pacman -S wireguard-arch` (the in-kernel version of wireguard)
1.  Add configuration files
1. `systemctl restart systemd-networkd`

Whereas then:

1. `pacman -Rus wireguard-arch; pacman -S wireguard-dkms; echo 'wireguard' > /etc/modules-load.d/wireguard.conf` (the DKMS version of wireguard)
1. Same conf
1. `systemctl restart systemd-networkd`

works as expected.

**Comment by neVERberleRfellerER** [comment]
It works for me. Could be version mismatch. Show
`uname -r`
and
`pacman -Qs linux | grep "local/linux "`
.

**Comment by xcffl** [comment]
Same here.
````
❯ uname -a    
Linux xcffl-pc 5.5.9-2-MANJARO #1 SMP PREEMPT Sun Mar 15 10:32:03 UTC 2020 x86_64 GNU/Linux

❯ pacman -Qs linux | grep "local/linux"  
local/linux-api-headers 5.4.17-1
local/linux-firmware 20200316.r1600.8eb0b28-1
local/linux-latest-headers 5.5-1
local/linux55 5.5.9-2
local/linux55-headers 5.5.9-2
local/linux55-nvidia-440xx 440.64-4 (linux55-extramodules)
````

**Comment by yuwata** [comment]
If wg-tools has the same issue, then it is not related to systemd-networkd.

Anyway, let's close this issue, as no response from the original reporter.
