### ISSUE TITLE
Timeout at shutdown when mounting samba share with cifs and WLan

### ISSUE THREAD

**Issue by PhilipMay** [systemd/systemd#1435]
Hello,
I am mounting a samba share with cifs (NetworkManager and WLan) and when I shutdown the computer I have a timeout (the shutdown hangs for 2 or 3 minutes).

Here is my fstab line:
//192.168.1.30/may /media/nasmay01may cifs _netdev,credentials=/etc/nasmay01-automountuser.credentials,noauto,x-systemd.automount,uid=root,gid=users,dir_mode=0770,file_mode=0660 0 0

I am using an up to date (1st Okt. 2015) arch linux with systemd 226. I am using NetworkManager and I am online via wlan.

Here is the output of "journalctl -b -1" after the reboot: http://eniak.info/static/2015-10-01-bootproblem-01.txt

What I tried in the past to solve the problem or to find a workaround (everything without success):
- add x-systemd.requires=network-online.target as parameter
- add x-systemd.requires=network.target as parameter
- switched from NetworkManager to WPA_supplicant with systemd.networkd and systemd.resolved

Strange thing is: When I do not use wlan with NetworkManager and use lan with
"systemctl start dhcpcd@<lan-device>.service" I do not get a timeout and everything is fine.

Even when I use NetworkManager with lan instead of wlan it works without a timeout. See "journalctl -b -1" after the reboot with lan: http://eniak.info/static/2015-10-01-boot-ok-lan-01.txt

Please tell me how I can provide more information to solve this issue.

Thanks.

Edit: Added info about NetworkManager and lan instead of wlan.

**Comment by arvidjaar** [comment]
It looks like D-Bus is stopped very early which in turn causes wpa_supplicant and NetworkManager to abort. For wired interface it does not really matter (you still have it up) but it apparently kills wireless. Could you provide `systemctl show dbus.service`?

**Comment by PhilipMay** [comment]
Ok thanks.
Here is the output of systemctl show dbus.service:

Type=simple
Restart=no
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
WatchdogUSec=0
WatchdogTimestamp=Do 2015-10-01 16:09:31 CEST
WatchdogTimestampMonotonic=17850736
StartLimitInterval=10000000
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=421
ControlPID=0
FileDescriptorStoreMax=0
StatusErrno=0
Result=success
ExecMainStartTimestamp=Do 2015-10-01 16:09:31 CEST
ExecMainStartTimestampMonotonic=17850693
ExecMainExitTimestampMonotonic=0
ExecMainPID=421
ExecMainCode=0
ExecMainStatus=0
ExecStart={ path=/usr/bin/dbus-daemon ; argv[]=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation ; ignore_errors=no ; start_time=[Do 2015-10-01 16:09:31 CEST] ; stop_time=[n/a] ; pid=421 ; code=(null) ; status=0/0 }
ExecReload={ path=/usr/bin/dbus-send ; argv[]=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
ControlGroup=/system.slice/dbus.service
MemoryCurrent=18446744073709551615
CPUUsageNSec=18446744073709551615
Delegate=no
CPUAccounting=no
CPUShares=18446744073709551615
StartupCPUShares=18446744073709551615
CPUQuotaPerSecUSec=infinity
BlockIOAccounting=no
BlockIOWeight=18446744073709551615
StartupBlockIOWeight=18446744073709551615
MemoryAccounting=no
MemoryLimit=18446744073709551615
DevicePolicy=auto
UMask=0022
LimitCPU=18446744073709551615
LimitFSIZE=18446744073709551615
LimitDATA=18446744073709551615
LimitSTACK=18446744073709551615
LimitCORE=18446744073709551615
LimitRSS=18446744073709551615
LimitNOFILE=4096
LimitAS=18446744073709551615
LimitNPROC=30736
LimitMEMLOCK=65536
LimitLOCKS=18446744073709551615
LimitSIGPENDING=30736
LimitMSGQUEUE=819200
LimitNICE=0
LimitRTPRIO=0
LimitRTTIME=18446744073709551615
OOMScoreAdjust=-900
Nice=0
IOScheduling=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SecureBits=0
CapabilityBoundingSet=18446744073709551615
MountFlags=0
PrivateTmp=no
PrivateNetwork=no
PrivateDevices=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
RuntimeDirectoryMode=0755
KillMode=control-group
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=dbus.service
Names=dbus.service
Requires=dbus.socket basic.target
Wants=system.slice
WantedBy=multi-user.target
Conflicts=shutdown.target
Before=shutdown.target multi-user.target systemd-networkd.service
After=system.slice dbus.socket systemd-journald.socket basic.target
TriggeredBy=dbus.socket
Documentation=man:dbus-daemon(1)
Description=D-Bus System Message Bus
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/usr/lib/systemd/system/dbus.service
UnitFileState=static
UnitFilePreset=disabled
InactiveExitTimestamp=Do 2015-10-01 16:09:31 CEST
InactiveExitTimestampMonotonic=17850737
ActiveEnterTimestamp=Do 2015-10-01 16:09:31 CEST
ActiveEnterTimestampMonotonic=17850737
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
IgnoreOnSnapshot=no
NeedDaemonReload=no
JobTimeoutUSec=0
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Do 2015-10-01 16:09:31 CEST
ConditionTimestampMonotonic=17850177
AssertTimestamp=Do 2015-10-01 16:09:31 CEST
AssertTimestampMonotonic=17850178
Transient=no

**Comment by poettering** [comment]
I figure NM should order itself explicitly after dbus, if it requires it to shut down cleanly...

**Comment by martinpitt** [comment]
NM itself is fine, but this smells like the same old "dbus dies too early for wpasupplicant" issue again, so wpasupplicant needs an `After=dbus.service`. See https://bugs.freedesktop.org/show_bug.cgi?id=89847 for some historic discussion.

**Comment by PhilipMay** [comment]
I added After=dbus.service to NetworkManager and wpa_supplicant. Didnt change anything. See the new log here: http://eniak.info/static/2015-10-01-bootproblem-03.txt

**Comment by PhilipMay** [comment]
Hello,
I finaly found the solution. Thanks so much for pointing me into the right direction. I had to do this:

$ cat /etc/systemd/system/wpa_supplicant.service.d/override.conf 
[Unit]
After=dbus.service
Before=network.target
Wants=network.target

Remark: Before=network.target and Wants=network.target is already added in wpa_supplicant Version 2.5. But Arch Linux is using version 2.3 at the moment (1st Okt. 2015).
I will write a bug report for wpa_supp.

**Comment by martinpitt** [comment]
Awesome, thanks Philip! Indeed `Before=network.target` sounds right, as on shutdown we shouldn't tear it down when network using services are still up.

**Comment by mbiebl** [comment]
Looking at
http://w1.fi/cgit/hostap/tree/wpa_supplicant/systemd/wpa_supplicant.service.in
, someone should probably poke wpasupplicant upstream to add a
After=dbus.service

2015-10-01 18:27 GMT+02:00 Martin Pitt notifications@github.com:

> Closed #1435 https://github.com/systemd/systemd/issues/1435.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/systemd/systemd/issues/1435#event-424420304.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by PhilipMay** [comment]
I have written a bug report mail to the wpa_supplicant developer (j@w1.fi). They do not have a bug tracking tool.

**Comment by marcosfrm** [comment]
`After=dbus.service` is still needed in `wpa_supplicant.service`, right? Time to ping wpa_supplicant folks again.

**Comment by marcosfrm** [comment]
I was having the same problem with NetworkManager. By default, when we connect to wifi using nm-applet, connection is saved with `connection.permissions` set to current user. At user logout, NM disconnects (before system shutdown). Solution is configure the connection as "global", not restricted to any user:

```
$ nmcli connection modify <ssid> connection.permissions ""
```

Anyway, shall the lack of `After=dbus.service` in `wpa_supplicant.service` be reported?

`wpa_supplicant.service` has `Before=network.target`. It is network daemon responsibility also order itself before `network.target` and if it needs to talk to wpa_supplicant on shutdown have proper `After=dbus.service`. Makes sense?

**Comment by skontar** [comment]
Hi all. 

I have the exact same issue on Fedora 31. However, all of `After=dbus.service`, `Before=network.target`, `Wants=network.target` are present in `wpa_supplicant.service`. I am unsure how to debug the problem. Only thing which worked for me was a workaround by @marcosfrm changing the connection permissions.

Thanks for any pointers.

**Comment by marcosfrm** [comment]
@skontar 

https://bugzilla.gnome.org/show_bug.cgi?id=788253

**Comment by rpgdev** [comment]
> @skontar
> 
> https://bugzilla.gnome.org/show_bug.cgi?id=788253

>the connection is restricted to a user, via something removes the connection, and NM brings it down. when that user logs out, NM brings down the connection. "permissions" is the "All users may connect to this network" option in nm-applet. If you want the connection to survive after logging out the user, don't set connection.permissions.

Indeed this fixes it. Thanks!
