### ISSUE TITLE
udevd link MACAddressPolicy=random fails for multiple links

### ISSUE THREAD

**Issue by iangehc** [systemd/systemd#14355]
Custom ARM Yocto-based distribution.

We have four links configured to use MACAddressPolicy=random.

Expect unique MAC address per link.

However, sometimes two or more links get the same MAC address.

The UDEV rules get processed before kernel entropy is ready.  ARM platform, so fallback to rand().  This bug occurs because udevd **forks** workers, but they share the **same** random seed.
(Found by inspecting master 3771024c24f8f9f7c28bbb61fdc21637975b1320.)

One solution would be to:
* make initialize_srand() always initialize the seed,
* have pseudo_random_bytes() test srand_called before calling initialize_srand()
* call initialize_srand() from udevd.c

(Note that there are calls to initialize_srand() in src/udev/cdrom_id/cdrom_id.c and src/udev/scsi_id/scsi_serial.c which look like cruft.)

**Comment by yuwata** [comment]
Not sure, does PR #14356 help you?

**Comment by poettering** [comment]
hmm, i think we should use genuine randomness for MACs, i.e. require the entropy. Otherwise collisions are just too likely...

**Comment by iangehc** [comment]
Thanks @yuwata but as noted in the PR #14356 review, the problem is after fork.

**Comment by keszybz** [comment]
> hmm, i think we should use genuine randomness for MACs, i.e. require the entropy.

That's tough too. We'd need to block, potentially for a long time.

@iangehc how important is true randomness for you, compared to just having the addresses different from each other?

**Comment by iangehc** [comment]
We only need the MAC addresses to be _different_.

**Comment by keszybz** [comment]
One option would be to add After=systemd-random-seed.service to systemd-udev.service. This is rather heavy-handed (and might cause other issues). What's worse, this will only work in the main system, and links are usually created in the initramfs. So I don't think we have a good answer right now, except to provide randomness early in the boot.

**Comment by poettering** [comment]
Well, the MAC addresses are inherently visible outside. If they have no entropy then collisions are just too likely, and we shouldn't allow that...

**Comment by poettering** [comment]
(or in other words: this PR @yuwata prepared is definitely more correct, but it just means the local MAC collisions are less likely. However remote MAC collisions on the local subnet are still too likely I think, but given the nature of MACs we really should care and make them as unlikely to collide as we can, and that means actually requiring entropy for them)

**Comment by poettering** [comment]
I prepped #15856 now, which switches this over to use genuine randomnes (possibly sources from RDRAND).

This means MACs are generated the exact same way we generate UUIDs. Since we nowadays generate UUIDs for every single invocation of a service I think this should be an OK fix, since it won't really drive the requirements on entropy up.
