### ISSUE TITLE
systemd-nspawn ignores bind mounts specified in .nspawn file

### ISSUE THREAD

**Issue by blablatros** [systemd/systemd#14372]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-nspawn should --bind mount directories specified in the command line in addition to the directories already specified in the `.nspawn` file

**Unexpected behaviour you saw**
 > systemd-nspawn ignores bind mounts specified in `.nspawn` file when additional --bind directories are specified in the command line

**Steps to reproduce the problem**

*Contents of /etc/systemd/nspawn/test-machine.nspawn*
```
[Exec]
PrivateUsers=false

[Files]
Bind=/var/cache/pacman/pkg
```
When running the container with `sudo systemd-nspawn --machine=test-machine` the bind mount work as expected.

When running the container with `sudo systemd-nspawn --machine=test-machine --bind=/home/blablatros/test/` the bind mounts specified in the `.nspawn` file are ignored.

**Comment by poettering** [comment]
if you specify settings on the cmdline they count and the matching settings in the nspawn file are ignored. we do not merge individual settings, we take each setting wholly from one or the other source but not mreged.

I am not sure this should be changed really...

**Comment by poettering** [comment]
A request to merge individual settings has been posted before in #5959, closing this one as duplicate hence.
