### ISSUE TITLE
Enabling LLDP on a CoreOS node

### ISSUE THREAD

**Issue by mazad01** [systemd/systemd#1437]
Hi, I'm trying to enable LLDP on a Solarflare NIC interface on a CoreOS host. 
My network file is as follows:

```
core@host ~ $ cat /etc/systemd/network/ens1f0.network                       
 [Match]
Name= ens1f0

[Network]
Address=*
LLDP=yes

[Route]
Gateway=*
Destination=*
```

I also checked to see if LLDP packets were being sent on the switch level, and it was not. Any suggestions?

cc: @greenpau

**Comment by zdzichu** [comment]
networkd's LLDP is receive only.

**Comment by greenpau** [comment]
@zdzichu, which command could I use to check what is being received by the host?

The switch the host is connected to sends LLDP packets:

```
Capturing on 'ens1f0'
  1   0.000000 f4:cf:e2:fc:5c:9a -> 01:80:c2:00:00:0e LLDP 314 Chassis Id = f4:cf:e2:fc:5c:9a Port Id = Ethernet1/19 TTL = 120
1   2  30.009666 f4:cf:e2:fc:5c:9a -> 01:80:c2:00:00:0e LLDP 314 Chassis Id = f4:cf:e2:fc:5c:9a Port Id = Ethernet1/19 TTL = 120
2   3  60.019671 f4:cf:e2:fc:5c:9a -> 01:80:c2:00:00:0e LLDP 314 Chassis Id = f4:cf:e2:fc:5c:9a Port Id = Ethernet1/19 TTL = 120
```

**Comment by zdzichu** [comment]
`networkctl lldp`

**Comment by greenpau** [comment]
@zdzichu, THANK YOU! I was looking for that command to no avail. It does not pop up on Google's first page :smile:

**Comment by poettering** [comment]
This is not a support forum. Please send requests for help to the systemd mailing list, not the github issue tracker. Thanks.
