### ISSUE TITLE
specify .mount target with new x-systemd mount property, consider x-systemd.target

### ISSUE THREAD

**Issue by aerusso** [systemd/systemd#14380]
**Is your feature request related to a problem? Please describe.**
In some cases, it may be useful to not have a `.mount` `Want=`ed by any target, or perhaps to have something besides `local-fs.target` `Want=` the `.mount file`. See zfsonlinux/zfs#9649 for a situation where something morally like `encrypted-fs@username.target` should `Want=` a collection of `.mount` files. I personally also have desired having a some filesystems that are not critical to the boot process get mounted later in the boot process, so as to not slow down early boot.

**Describe the solution you'd like**
Have `systemd-fstab-generator` recognize a new `x-systemd.target` property that would, by default, equal `local-fs.target`. If it was set to the special case of `none`, then the created `.mount` file will not be `Want=`ed by any target (or, at least the generator will not create any such link). If it has any other value, say `x-systemd.target=example.target`, then the generator will create a `Want=` dependency from that target on the new `.mount` unit.

**Describe alternatives you've considered**
In the aforementioned issue report, we have considered a global switch to disable systemd integration with the filesystems in question. We've also considered a simpler switch that can only disable the `WantedBy=local-fs.target` relation that is created.  Perhaps a better name is `x-systemd.Wanted By=`? **Guidance on the name is especially important to us.**

**Additional side comment:**
We are planning on supporting some (or perhaps all) of the `x-systemd` mount options in ZFS. There is a question of where to put these items in the namespace, and it would be ideal if we could get agreement from the folks here at systemd that (a) we should have these mount options, and (b) if should use the systemd namespace. See, e.g., https://github.com/zfsonlinux/zfs/pull/9649#issuecomment-563089176

At this point, I think we (at ZFS on Linux) would simply be happy with a statement that such a feature would be accepted. Then we could move forward with an implementation of it (starting with our own `zfs-mount-generator`).

**Comment by poettering** [comment]
x-systemd.wanted-by= sounds good to me, if you want to work on that.
