### ISSUE TITLE
systemd-journald must allow specific messages to be forwarded to syslog without being written to journal DB

### ISSUE THREAD

**Issue by gleventhal** [systemd/systemd#14387]
**Is your feature request related to a problem? Please describe.**
Yes, this is a problem.  A proxying service should always give the option of selective transparency.  systemd-journald is intrusive here, because it's acting as a proxy that also tries to serve the purpose of the service it is proxying (syslog).  I would be OK with the journal doing that if it gave me an easy way to selectively choose messages to forward to syslog without also being written to the journal DB.

I need to send certain messages off to a central syslog service and cannot keep them locally due to security reasons.  My syslog daemon makes this simple, but the journal has already chosen to persist these messages for me.  I do want to persist all the other messages, but these specific messages, I want to forward to the central syslog without keeping any trace of them on the box.  I dont want them viewable with journalctl, even by root, but I want every other message to be viewable locally.   

**Describe the solution you'd like**
Allow a way to configure certain messages to be forwarded directly to the syslog daemon based on tags, regex, syslog priority / facility, anything.

**Describe alternatives you've considered**
Ive considered letting syslog own /dev/log and not using the systemd-journal service because it's making this so difficult.  It would be so much more powerful if there were easy ways to filter things.  The syslog daemon has a much more expressive configuration syntax, so if I am forced to choose only one, it wins.

**Comment by poettering** [comment]
If you want to use syslog then do so, turn off storage in journald, and journald will forward everything to syslog via ForwardToSyslog=, including the data it receives via its native protocol, the stuff it receives via stdout/stderr logging of systemd services and so on.

Us Storage=none in journald.conf to turn off local storage. You can then process anything you want with syslog and journald just passes data along. You will generally lose early boot logging that way though since most syslogs are not capabale of running that early.

**Comment by gleventhal** [comment]
@poettering I already know everything you've said.  I am specifically asking for the ability to selectively not process *some* messages through the journal, but to store everything else in the journal database.  I'd rather not use Storage=none if I can avoid it and it seems like a trivial operation to just filter on syslog priority and conditionally  immediately forward to the syslog socket interface.

**Comment by anitazha** [comment]
Your request is similar to the ask in #6432. But even though the issue is still open, the current stance is that there will not be journal filtering at collection time.
