### ISSUE TITLE
Separate /var partition, a stop job is running for var.mount during boot several times that fails

### ISSUE THREAD

**Issue by zboszor** [systemd/systemd#14389]
**systemd version the issue has been seen with**
> 241 as used in Yocto 2.7, 243, 243.4, 243.4 + revert of 5db454b + cherry-picked 030f457 as suggested in https://github.com/systemd/systemd/issues/14128#issuecomment-558817893

**Used distribution**
 > Yocto 2.7 based custom distro

**Expected behaviour you didn't see**
 > /var left alone after mounted from fstab, all services should start correctly

**Unexpected behaviour you saw**
 > After /var was mounted from fstab, "A stop job is running for var.mount" + "Failed unmounting /var" (because it's busy) showed up several times in the log. Possibly as a side effect, connman.service didn't start. When testing on a disk with no separate /var, this doesn't occur, connman.service started properly.

**Steps to reproduce the problem**

**Comment by zboszor** [comment]
Our previous version of our custom OS based on Yocto 2.5 with systemd 237, the issue didn't occur with a separate /var. It is a regression for us.

**Comment by poettering** [comment]
This is not a useful bug report. Please provide debug logs and so on of the boot process, otherwise there's exactly nothing we can do

**Comment by zboszor** [comment]
Besides "journalctl -xb", what kind of debug logs do you need?

**Comment by poettering** [comment]
see: 
https://freedesktop.org/wiki/Software/systemd/Debugging/#index1h1

i.e. turn on debug logging as documented on the kernel command line

**Comment by zboszor** [comment]
[journal-multi-user.txt](https://github.com/systemd/systemd/files/3983460/journal-multi-user.txt)
This OS usually boots into X with a single frontend app, there I can get to the terminal.
But to limit the amount of logs, I set the multi-user.target as default. Then I had to turn on debug shell to get a shell at all because the usual ttys did not show a login prompt.
Attached journalctl -xb from this state, with "quiet rhgb" removed.
I also found this line in the log:
`Dec 19 11:56:49 pos systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided
`
How can I debug which services are in conflict?

**Comment by zboszor** [comment]
[journal-single.txt](https://github.com/systemd/systemd/files/3983508/journal-single.txt)
This is the same, booting into single mode. The "Failed unmounting /var" messages are also there.
/etc/fstab looks like this:
```
UUID=b2cccbac-2717-4fcb-ae65-15189e087778 /          auto       relatime   1  1
UUID=5b4b16a2-9b38-4618-8846-8ecc2747b013 /boot      auto       relatime   1  1
UUID=e8282db7-dd6d-4231-b2b1-49887648480c /var       auto       relatime    1  1
UUID=f278659a-627d-4367-8c12-9600b7f66cdc /mnt/backup auto      relatime    1  1
UUID=78715f88-794f-4a93-831e-b05742311ac8 swap       swap       defaults   0  0
proc                 /proc                proc       defaults              0  0
devpts               /dev/pts             devpts     mode=0620,gid=5       0  0
usbdevfs             /proc/bus/usb        usbdevfs   noauto                0  0
tmpfs                /run                 tmpfs      mode=0755,nodev,nosuid,strictatime 0  0
tmpfs                /var/volatile        tmpfs      defaults              0  0
tmpfs                /var/tmp             tmpfs      defaults              0  0
```

**Comment by poettering** [comment]
please provide the log output with debug logging on. please read the linked wiki page i linked early how to enable debug logging.

**Comment by zboszor** [comment]
I am sorry, I couldn't read properly. Here the debugging-enabled logs, one for booting into single mode, and one for booting into multi-user.target that never finishes, the tty logins won't show up.
[journal-multi-user2.txt](https://github.com/systemd/systemd/files/3984256/journal-multi-user2.txt)
[journal-single2.txt](https://github.com/systemd/systemd/files/3984257/journal-single2.txt)

**Comment by poettering** [comment]
it gets interesting here:

```
Dec 19 15:13:37 pos systemd[1]: var.mount: Directory /var to mount over is not empty, mounting anyway.
Dec 19 15:13:37 pos systemd[1]: Mounting /var...
Dec 19 15:13:37 pos systemd[1]: Started udev Kernel Device Manager.
Dec 19 15:13:37 pos sicom-sysinit-pre[547]: Removed /etc/lighttpd.d/https.conf symlink (/etc/lighttpd.d/server.pem doesn't exist)
Dec 19 15:13:37 pos systemd[554]: iptables.service: Executable /usr/sbin/iptables-extension.sh missing, skipping: No such file or directory
Dec 19 15:13:37 pos systemd[1]: Started udev Coldplug all Devices.
Dec 19 15:13:37 pos systemd[1]: Started iptables.
Dec 19 15:13:37 pos kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
Dec 19 15:13:37 pos kernel: ext4 filesystem being mounted at /boot supports timestamps until 2038 (0x7fffffff)
Dec 19 15:13:37 pos systemd[1]: Mounted /boot.
Dec 19 15:13:37 pos systemd[1]: Reloading.
Dec 19 15:13:37 pos kernel: EXT4-fs (sda5): mounted filesystem with ordered data mode. Opts: (null)
Dec 19 15:13:37 pos kernel: EXT4-fs (sda6): mounted filesystem with ordered data mode. Opts: (null)
Dec 19 15:13:38 pos systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file accordingly.
Dec 19 15:13:38 pos systemd[1]: /usr/lib/systemd/system/php-fpm73.service:9: PIDFile= references a path below legacy directory /var/run/, updating /var/run/php-fpm73.pid → /run/php-fpm73.pid; please update the unit file accordingly.
Dec 19 15:13:38 pos systemd[1]: /usr/lib/systemd/system/openvpn@.service:9: PIDFile= references a path below legacy directory /var/run/, updating /var/run/openvpn/server.pid → /run/openvpn/server.pid; please update the unit file accordingly.
Dec 19 15:13:38 pos systemd[1]: /usr/lib/systemd/system/lighttpd.service:7: PIDFile= references a path below legacy directory /var/run/, updating /var/run/lighttpd.pid → /run/lighttpd.pid; please update the unit file accordingly.
Dec 19 15:13:38 pos systemd[1]: /usr/lib/systemd/system/org.cups.cupsd.socket:6: ListenStream= references a path below legacy directory /var/run/, updating /var/run/cups/cups.sock → /run/cups/cups.sock; please update the unit file accordingly.
Dec 19 15:13:38 pos systemd[1]: Started Setup hardware state.
Dec 19 15:13:38 pos systemd[1]: mnt-backup.mount: Mount process finished, but there is no mount.
Dec 19 15:13:38 pos systemd[1]: mnt-backup.mount: Failed with result 'protocol'.
Dec 19 15:13:38 pos systemd[1]: Unmounted /mnt/backup.
Dec 19 15:13:38 pos systemd[1]: var.mount: Mount process finished, but there is no mount.
Dec 19 15:13:38 pos systemd[1]: var.mount: Failed with result 'protocol'.
Dec 19 15:13:38 pos systemd[1]: Unmounted /var.
Dec 19 15:13:38 pos systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided
Dec 19 15:13:38 pos systemd[1]: Unmounting /boot...
Dec 19 15:13:38 pos systemd[1]: Starting ip6tables...
```

somehow debug logging went away during the initrd transition... I wonder if the initrd you passes state over correctly... it looks ike it doesn't, hence the debug logging gets lost.

PID 1 is reloaded after the transition, which looks wrong too. 

and for some reason systemd believes /var was not actually mounted properly after mount exited. Maybe your job "Setup hardware state" play mount games with /var? for example unmounts it or so?

either way, there are numerous issues in your setup. For example your fstab lists a number of lines it really shouldn't list (such as /proc and /run and so on). /var mount points are not empty? I am not sure where to start with this, but first figure out why the debug logging gets lost during the initrd transition... and why there's a reload after the transition.

**Comment by zboszor** [comment]
> somehow debug logging went away during the initrd transition... I wonder if the initrd you passes state over correctly... it looks ike it doesn't, hence the debug logging gets lost.

initrd is dracut GIT that will be v50. 

> PID 1 is reloaded after the transition, which looks wrong too.
> 
> and for some reason systemd believes /var was not actually mounted properly after mount exited. Maybe your job "Setup hardware state" play mount games with /var? for example unmounts it or so?

Nope, it only reads and writes files in /etc.

> either way, there are numerous issues in your setup. For example your fstab lists a number of lines it really shouldn't list (such as /proc and /run and so on).

OK, I can take them out.

> /var mount points are not empty? I am not sure where to start with this, but first figure out why the debug logging gets lost during the initrd transition... and why there's a reload after the transition.

/var is not empty because it was not the first boot. /var was empty on the first boot, the rootfs was freshly formatted. Files in /var on the rootfs appeared after systemd unmounted/remounted /var and something started in between.

**Comment by poettering** [comment]
anyway, please start with figuring out where the debug log level went after the transition, and figure out who reloads PID 1 after the transition again.

**Comment by zboszor** [comment]
I looked into it. The script behind that "Setup hardware state" service was doing systemctl enable/disable for a service that comes later in the boot process. I guess it's not a legal operation now, but it was working (tolerated?) before.

When removing the systemctl enable/disable commands from that script, the system magically started working even with /var on the separate partition. Well, on the second boot, anyway. At the first boot connman still didn't start properly but I blame the Yocto first boot machinery for that. But there are no umount attempts anymore and there are no "mount point is not empty" reports in syslog either in subsequent reboots.

I hope creating a file for ConditionPathExists= dynamically from services in sysinit.target for later service units will still work.

Anyway, thanks for pointing me to the right direction.

**Comment by poettering** [comment]
It's the /var directory that is going to be overmounted that is not empty. And that almost certainly indicates there's a bug. i.e. not the fs you mount onto /var but the directory on the root fs that is called /var that is then obstructed by the /var mount.

**Comment by zboszor** [comment]
As I wrote, when taking out the "systemctl enable/disable" commands out of the script that is run in sysinit.target, umount /var doesn't happen anymore. I confirmed it on a freshly formatted disk.Rebooted several times, then powered the machine off and inspected the disk on a different machine. The /var directory was still empty on the root filesystem. So having the separate /var partition works now. Is is legal to run systemctl enable/disable by services?

**Comment by boucman** [comment]
yes... everything is a service at some point, so when you run systemctl from a shell, you are running it from a service if you go up the call tree.

However it probably doesn't do what you want it to do. It will add the service to the boot sequence, but that will only work for the next boot. not for the boot in progress.

To say it differently, it's allowed but if you do it it is almost certainly a bug in your script. There are very few cases where you should do i.

**Comment by zboszor** [comment]
This case was cargo culted from a time when ConditionalXXX settings were not invented yet in systemd. The enabling condition was also a little more complicated than what can be expressed by the current ones. But we actually forgot about it being in the script because it was working for such a long time. We started around systemd 216-217 and this script worked up to 237, then suddenly didn't in 241 and 243.x.

**Comment by poettering** [comment]
Is there still something to discuss ehre? Can we close this?

**Comment by zboszor** [comment]
I would like to know one last small detail: at what point can any service issue a "systemctl enable/disable" command and not disrupt the boot process? Is it only when reaching default.target or somewhat earlier? It's a purely theoretical question now but this was what caused our boot issues with /var on a separate partition, i.e. a service running before sysinit.target did this and causes this kind of buggy behaviour.

**Comment by poettering** [comment]
in theory this should work safely anytime with current systemd versions. Still not recommended to do this though in regular, clean code paths, since it's a really heavy operation, and untis that are enabled during boot-time might or might not be included in one of the initial transactions...

Anyway, I guess we can close the issue now.
