### ISSUE TITLE
Unable to set time with AmbientCapabilities=CAP_SYS_TIME

### ISSUE THREAD

**Issue by ac-frg** [systemd/systemd#14393]
systemd version the issue has been seen with

    systemd 244

Used distribution

    Yocto

Unexpected behaviour you saw

    Unable to set time with AmbientCapabilities=CAP_SYS_TIME

Steps to reproduce the problem

Service:

...
[Service]
AmbientCapabilities=CAP_SYS_TIME
Type=simple
ExecStart=/usr/bin/timedatectl set-time "2012-04-19 16:45:05"
User=testuser
...

Output:
Dec 19 07:45:27 801F123DCE1E timedatectl[1360]: Failed to set time: Access denied

**Comment by anitazha** [comment]
I think this might require a dbus call to get a pidfd to fix properly. Right now `timedatectl` makes a dbus call to `timedated` which does the authorization checks. But since there isn't a race free way to get the capabilities (because it has to read from `/proc/<pid>`) `timedated` doesn't check the capabilities at all.

**Comment by ac-frg** [comment]
I can confirm that the same problem occusr with the date and hwclock command.

**Comment by poettering** [comment]
@anitazha's analysis is correct, we can't safely check the caps on the client side via dbus, hence we don't. If you want less privileged clients to change the time via timedated, you need to write some policykit rule I figure, that matches in user/group memberships, as those can be acquired safely.

Anyway, this isn't really actionable to us I fear, the kernel is too limited to allows us to fix this. if the kernel had SCM_PASSCAPS or so for implicitly attaching cap information to AF_UNIX datagrams like it supports SCM_PASSCREDS, we'd love to support that, but other than that we really cannot fix this. Sorry.
