### ISSUE TITLE
Please exclude ID_FS_* from IMPORT{parent} rule in 60-persistent-storage.rules

### ISSUE THREAD

**Issue by scdbackup** [systemd/systemd#14408]
Hi,

the ID_* properties import rule in rules.d/60-persistent-storage.rules makes
problems with bootable ISO 9660 filesystems which contain a partition table
for the case that they are presented to the boot firmware on a USB stick.
To be still bootable from DVD, these filesystems have a ISO 9660 superblock
for mounting by the parent device.

The problematic rule lets partitions with no recognizable filesystem inherit
the filesystem properties of the parent device. Consequentially they race with
the parent for becoming link target in /dev/disk/by-label. They seem to always
win the race and then mislead users of /dev/disk/by-label.

This importing of ID_FS_* properties from the parent device is not a bigger
problem only because in most cases a partitioned disk has no filesystem which
could be mounted by the parent device file.

-------------------------------------------------------------------------

Please consider to replace in rules.d/60-persistent-storage.rules

    # for partitions import parent information
    ENV{DEVTYPE}=="partition", IMPORT{parent}="ID_*"

by

    # for partitions import parent ID_* information, except ID_FS_*
    ENV{DEVTYPE}=="partition", IMPORT{parent}="ID_[!F]*", IMPORT{parent}="ID_F[!S]*", IMPORT{parent}="ID_FS[!_]*"

-------------------------------------------------------------------------

There are two frequent reasons for having partitions with no recognizable
filesystem in the partition table of an USB stick with bootable ISO:

- grub-mkrescue for EFI creates a GPT partition table where two empty partitions shield those parts of the ISO filesystem which are not covered by the EFI partition or the HFS+ partition.

- After dd'ing a hybrid ISO image onto the USB stick, it is usual to create a partition for a rw-filesystem. While it has no filesystem, udev attributes the ISO Volume Id to it.

The current situation caused the decision to fix it by suppressing the ID_FS_*
properties of ISO 9660 parent devices in the output of libblkid:

https://github.com/karelzak/util-linux/commit/7ef86a08914427d6486734614d7d3bbed1f108fe
https://github.com/karelzak/util-linux/pull/913/commits/fc84bc0a463480ffb17a39b5375463b7f07d14ce
https://github.com/karelzak/util-linux/pull/913

7ef86a0 was too aggressive. After fc84bc0 libblkid suppresses the ID_FS_*
properties of the parent device only if there is a partition of which the
start coincides with the parent device.

In the wide spectrum of bootable hybrid ISOs, the ISO 9660 filesystem may
or may not appear as mountable by a partition.
If it appears, the partition start LBA may coincide with the parent device
(i.e. be 0) or may differ from it by 64 or much more blocks (512 bytes per
block). Filesystem equality despite non-zero LBA is achieved by having two
superblocks and directory trees.

So the new behavior of libblkid does not solve the problem of inappropriate
filesystem property import for

- ISOs from grub-mkrescue, which have no mountable ISO partition. E.g. Guix.

- ISOs with xorriso -partition_offset 16. E.g. Knoppix 8.6.

- SuSE ISOs made by KIWI where the ISO partition comes after the EFI partition.

To my opinion, this problematic and still not fully effective manipulation
of liblkid's output would not be necessary, if the udev rules would avoid
to import ID_FS_* from the parent device.
I hope to convince the libblkid developers of revoking the suppression if i
can convince you of changing the import rule.

My name is Thomas Schmitt. I am the developer of xorriso, which helps its
users to create the ISOs which then trigger the problems. Most of the created
partition layouts are not my invention, though, but rather come from boot
software developers like H. Peter Anvin, Matthew J. Garrett, Vladimir
Serbinenko.

Have a nice day :)

Thomas

**Comment by karelzak** [comment]
Thomas is right, ID_FD_* variables describe device content (yes, including LABEL and UUID). I do not understand why it makes sense to copy this description from the whole-disk (parent) device. The current 
```
ENV{DEVTYPE}=="partition", IMPORT{parent}="ID_*"
```
is just a blind shot  and we do not see more problems because partition specific blkid call (usually) overwrites it.

**Comment by poettering** [comment]
uh, I am pretty sure there's tons of sw that assumes that ID_VENDOR and ID_MODEL and such is available on all block devices (i.e. partitions and so on) that a disk synthesizes. Suppressing that sounds incompatible to me, and actually even wrong. I don't think it's wrong to assume that ID_VENDOR/ID_MODEL and similar properties are available on each partition. People write udev rules that mount a partition of a specific disk onto some mount point and for that match vendor/model, and that's totally the OK thing to do.

**Comment by poettering** [comment]
Didn't we have the same discussion before btw?

**Comment by poettering** [comment]
What I don't get? Why does this matter at all? I mean, these hybrid ISOs are all fucked up in one way or another. Who wants to mount them via /dev/disk/by-label/ links anyway? i.e their purpose is not to be stably mounted but by be just fucked up enough to boot on a variety of weird systems. I mean isn't this a mostly theoretical problem?

**Comment by scdbackup** [comment]
Hi,

my proposed rule shall only exclude ID_FS_*, which Karel deems to be the
domain of libblkid, if i understand him right.

The logic is that the description

"those ID_* which are not ID_FS_*"

is equivalent to

"those ID_* which are not ID_F*,
plus those which are ID_F* but not ID_FS*,
plus those which are ID_FS* but not ID_FS_*"

because

- any ID_FS_* gets rejected by all of my three IMPORT patterns,

- any other ID_* passes them, because it must differ at least by one of the excluded letter positions.

I test it on a Debian which is so old that i don't dare to tell.
On /dev/sdd there is a grub-mkrescue ISO with not mountable partitions:

    $ lsblk -o NAME,SIZE,FSTYPE,LABEL /dev/sdd
    NAME    SIZE FSTYPE  LABEL
    sdd     1.9G iso9660 ABCIMAGE
    |-sdd1  136K         
    |-sdd2  2.8M vfat    
    |-sdd3 11.8M hfsplus ISOIMAGE
    |-sdd4  300K         
    `-sdd5  1.9G      

My proposed rules cause:

    $ udevadm info /dev/sdd1 | fgrep ID_VENDOR
    E: ID_VENDOR=INTENSO
    E: ID_VENDOR_ENC=INTENSO\x20
    E: ID_VENDOR_ID=090c
    $ udevadm info /dev/sdd1 | fgrep ID_FS_
    $

With the original rule i get:

    $ udevadm info /dev/sdd1 | fgrep ID_VENDOR
    E: ID_VENDOR=INTENSO
    E: ID_VENDOR_ENC=INTENSO\x20
    E: ID_VENDOR_ID=090c
    $ udevadm info /dev/sdd1 | fgrep ID_F
    E: ID_FS_BOOT_SYSTEM_ID=EL\x20TORITO\x20SPECIFICATION
    E: ID_FS_LABEL=ABCIMAGE
    E: ID_FS_LABEL_ENC=ABCIMAGE
    E: ID_FS_TYPE=iso9660
    E: ID_FS_USAGE=filesystem
    E: ID_FS_UUID=2016-02-06-11-47-47-00
    E: ID_FS_UUID_ENC=2016-02-06-11-47-47-00
    $

I.e. there are no ID_F* properties in my olde rules, by which i could test
more sharply.
Do you have proposal how to mock-up a more challenging test ?

Have a nice day :)

Thomas

**Comment by scdbackup** [comment]
Hi,

> isn't this a mostly theoretical problem?

It is problem enough to cause libblkid cripple its perception of device
content. 
As happy user of lsblk i now fear problems with legacy scripts.

The reason-to-be for hybrid ISOs is that they free the distro installer
people from complaints from users who already mess up their USB stick for 
installation. ISO is read-only even on USB stick.

There are the Live ISOs which are supposed to get an additional partition
with rw-filesystem for persistent storage. So they are not that short-lived
on their storage device.

Please consider:

- Which ID_FS_* property is worth to be imported from the parent ?

- Does my proposed rule block any ID_* else but ID_FS_* ?

Have a nice day :)

Thomas

**Comment by poettering** [comment]
hmm, maybe it's ok to exclude ID_FS_*, but it sounds so weird having a blacklist from a whitelist

**Comment by scdbackup** [comment]
Hi,

> it sounds so weird having a blacklist from a whitelist

Regard ID_* as namespace and the IMPORTs as picking stuff from this space.
Then it looks more plausible. :))

After all, seen as blacklist my IMPORTs would have a strange form.
I already pondered how to encode a list of ID_XYZ* exclusion patterns this 
way. It should be possible, but a general encoder would be an interesting 
piece of software with tree and leafs and bundling optimizations.

Btw, is there some policy for new ID_* names in the official udev rules ?
Who can introduce such names and what naming rules apply ?

I found nothing during my web searches in the last days.

Have a nice day :)

Thomas

**Comment by scdbackup** [comment]
Hi,

while tinkering on a quite human friendly algorithm for producing patterns
from a multi-item blacklist, i noticed that my proposal excludes short
variable names on the way to ID_FS_* : ID_, ID_F and ID_FS.
(glob cannot say "i want no F" without saying "i want some character".)

I don't think that they are worth to be imported from parent. But if they
would be, then they would need to get their own IMPORT statements:

    ..., IMPORT{parent}="ID_", IMPORT{parent}="ID_F", IMPORT{parent}="ID_FS",

So my proposal is really not a blacklist but a cheap workaround for the lack
of a real whitelist. The justification is that udev will then stop lying
about partition content, not that this is an extensible mechanism.

Have a nice day :)

Thomas

**Comment by dsd** [comment]
> What I don't get? Why does this matter at all? I mean, these hybrid ISOs are all fucked up in one way or another.

Weirdness of hybrid ISOs aside, it also affects "normal" ISOs with partition tables.

For example with an ISO created as follows:
```
# truncate -s 2M fatfs.img
# mkfs.vfat -n isoesp fatfs.img
# xorriso -as mkisofs -volid myiso -o test.iso --append_partition 2 0xef fatfs.img /tmp/foo/
```
(where /tmp/foo contains whatever to be included in the iso, can be empty)

Now flash it to USB and check by-label results:
```
# dd if=test.iso of=/dev/sda
# ls -l /dev/disk/by-label/
lrwxrwxrwx 1 root root 15 Dec 25 14:48 fedora -> ../../nvme0n1p3
lrwxrwxrwx 1 root root 10 Dec 25 16:05 isoesp -> ../../sda2
lrwxrwxrwx 1 root root 10 Dec 25 16:05 myiso -> ../../sda1
```

So far so good.

Now add a new partition (but don't format it).

```
# echo "type=1" | sfdisk -a /dev/sda
```

This got added as sda3. And the udev property inheritence under discussion now updates the myiso symlink:
```
# ls -l /dev/disk/by-label/myiso 
lrwxrwxrwx 1 root root 10 Dec 25 16:08 /dev/disk/by-label/myiso -> ../../sda3
```

The myiso symlink now points at the new/empty/unusable partition, instead of the ISO filesystem. That seems wrong.

**Comment by scdbackup** [comment]
Hi,

Daniel Drake wrote:
> The myiso symlink now points at the new/empty/unusable partition, instead of
> the ISO filesystem. That seems wrong.

Yes. As bloated, unstylish, and strategically questionable my proposal is,
it corrects the presentation of not mountable partitions with a mountable
filesystem on the parent device. Not only in the case of ISO 9660.

I am meanwhile testing this rule:

    # for partitions import parent ID_* information, except ID_FS_*
    ENV{DEVTYPE}=="partition", \
      IMPORT{parent}="ID_[!F]*", IMPORT{parent}="ID_", \
      IMPORT{parent}="ID_F[!S]*", IMPORT{parent}="ID_F", \
      IMPORT{parent}="ID_FS[!_]*", IMPORT{parent}="ID_FS"

with this additional rule to verify the exactness of the exclusion:

    # Test mock-up for IMPORT filter without ID_FS_*
    KERNEL=="sdd", \
      ENV{ID_}="id_", ENV{ID_F}="id_f", ENV{ID_FS}="id_fs", \
      ENV{ID_FS_}="id_fs_", ENV{ID_FX_}="id_fx_", ENV{ID_FX_XYZ}="id_fx_xyz" 

The effect with an empty partition /dev/sdd5 is

    $ sudo udevadm info /dev/sdd5 | grep '^E: ID_='
    E: ID_=id_
    $ sudo udevadm info /dev/sdd5 | grep '^E: ID_F'
    E: ID_F=id_f
    E: ID_FS=id_fs
    E: ID_FX_=id_fx_
    E: ID_FX_XYZ=id_fx_xyz
    $

So among my dummy variables, only ID_FS_ is excluded, as the comment of my
proposal promises.
The real ID_FS_* variables are excluded from import too.
As far as i can see, all other real ID_* variables come into effect. Some
get overridden by partition examination. Some stay as with the parent device.

Have a nice day :)

Thomas

**Comment by poettering** [comment]
please submit any patch as PR, not as issue. otherwise we can't merge it.

**Comment by scdbackup** [comment]
Hi,

> please submit any patch as PR, not as issue. otherwise we can't merge it.

If i shall do this, then i could need help due to lack of any GitHub knowledge
and rather poor git capabilities in general.
Is there a chance for me to plead incompetence and get a pull request created
by one of the participants here as an act of mercy ?

The payload of the pull request would be

    -# for partitions import parent information
    -ENV{DEVTYPE}=="partition", IMPORT{parent}="ID_*"
    +# for partitions import parent ID_* information, except ID_FS_*
    +ENV{DEVTYPE}=="partition", \
    +  IMPORT{parent}="ID_[!F]*", IMPORT{parent}="ID_", \
    +  IMPORT{parent}="ID_F[!S]*", IMPORT{parent}="ID_F", \
    +  IMPORT{parent}="ID_FS[!_]*", IMPORT{parent}="ID_FS"

GitHub Help urges me to install GitHub Desktop. I would rather try to use
git commands from my cheat sheet for a trained monkey.
But do i have permission to push a new branch ?

Have a nice day :)

Thomas

**Comment by dsd** [comment]
You can fork systemd into your own github user account, push your changes there, and then open a pull request up to the main systemd repository.

However, I'd be happy to take care of this for you if you prefer, once I am back at work on Monday.

**Comment by scdbackup** [comment]
Hi,

> However, I'd be happy to take care of this for you if you prefer, 
> once I am back at work on Monday.

That would be great. Up to now i have used this GitHub account only for 
discussions.

Have a nice day :)

Thomas
