### ISSUE TITLE
systemd.mount: create directories for noauto mounts

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#14418]
**Is your feature request related to a problem? Please describe.**
I added a .mount file for the '/media' directory as tmpfs, this raised some problems with directories that were created and persisted though reboots.
I am using systemd 244 on Debian testing x86_64, relevant software is udisks2, Nautilus and the Gnome desktop (really dont know all involved software)

Relevant parts are the new media.mount file:
```
[Unit]
Description=Mount point for removable media (/media)
Documentation=man:hier(7)
Documentation=https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html
ConditionPathIsSymbolicLink=!/media
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target

[Mount]
What=tmpfs
Where=/media
Type=tmpfs

[Install]
WantedBy=local-fs.target
```

And some entries in fstab:
```
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
//192.168.0.2/public /media/WDCloud  cifs user=none,password=none,rw,users,uid=1000,vers=3,noauto 0 0
```

1. WDCloud cant be mounted anymore without creating the /media/WDCloud directory first
2.  /media/cdrom0 cant be mounted manually, but inserting a cdrom will automatically create the directory (udev?).

**Describe the solution you'd like**
Naturally I would like to be able to mount the WDCloud share/Cdrom for all users as before - Nautilus shows the share and you can click it.

Some option to create the directories before (the otherwise then failing) mount would seem logical.
For the cdrom0, maybe there is a better option like configuring udev to make the symlink as default cdrom, dont know. At any rate you will lose shared access if the device is then mounted below /media/<user>.

**Describe alternatives you've considered**
Well, adding tmpfiles.d entries would make everything work as before. Ideally all software would be able to deal with dynamic mount, but I think systemd would be a natural fit to bridge the time.

Also ultimatively removing the cdrom0 entry from fstab seems to be a good idea, but that might possibly break some apps.

**Comment by poettering** [comment]
Hmm, you want that /bin/mount creates those mount point dirs before mounting something there? there's the X-mount.mkdir= mount option for that (google for it, or see the mount man page), but systemd has nothing to do with that. 

Closing as unrelated to systemd.

**Comment by nolange** [comment]
Tried out `X-mount.mkdir`, doesnt work as non-root. I accept that this aint systemd business.

**Comment by poettering** [comment]
Hmm. Sounds like oversight in util-linux, i.e. something @karelzak would probably fix for you. Could you file an issue against util-linux please?

**Comment by karelzak** [comment]
The final util-linux v2.35 will address this issue.

**Comment by nolange** [comment]
@karelzak, thanks for the support.

But I believe ideally the **udisks2** daemon would handle creating directories + user-mounts (since thats its purpose). eg. if a user cant mkdir /media/cdrom then your fix wont help AFAIK.

**Comment by karelzak** [comment]
> @karelzak, thanks for the support.
> 
> But I believe ideally the **udisks2** daemon would handle creating directories + user-mounts (since thats its purpose). eg. if a user cant mkdir /media/cdrom then your fix wont help AFAIK.

Sure, a user needs access rights to create the directory (for example $HOME/mnt is fine). mount(8) is too low-level to maintain and evaluate any additional user permissions.
