### ISSUE TITLE
unmountable loop devices fail shutdown

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#14410]
Observe:
```
set -x
set -e
loopdev=$(losetup -f)
loop=$(basename $loopdev)
snap=/tmp/sample.squashfs
if [ ! -f $snap ]
then
    mksquashfs /dev/null $snap
fi

# setup loop
# mount
# umount
# detach loop
losetup --show $loopdev $snap
cat /sys/block/$loop/loop/backing_file
cat /sys/block/$loop/loop/autoclear
mount $loopdev /mnt
umount /mnt
cat /sys/block/$loop/loop/backing_file
cat /sys/block/$loop/loop/autoclear
losetup -d $loopdev
cat /sys/block/$loop/loop/backing_file || :
cat /sys/block/$loop/loop/autoclear || :

# setup loop
# mount
# detach loop
# observe change in autoclear
# unmount
# obsever autoclear working
losetup --show $loopdev $snap
cat /sys/block/$loop/loop/backing_file
cat /sys/block/$loop/loop/autoclear
mount $loopdev /mnt
losetup -d $loopdev
cat /sys/block/$loop/loop/backing_file
cat /sys/block/$loop/loop/autoclear
umount $loopdev || :
cat /sys/block/$loop/loop/backing_file || :
cat /sys/block/$loop/loop/autoclear || :
```

In the first case backing_file is set to the squashfs we created & autoclear is zero throughout.

In the second case, refcount on the loop device is up (due to live mount). And the clr_fd ioctl on the loop device will succeed, however it will not clear the backing_file and only set the autoclear flag.

Note one can continiously call clr_fd ioctl when it is in such state. As kernel does not care.

Produced output
```
+ set -e
+ losetup -f
+ loopdev=/dev/loop9
+ basename /dev/loop9
+ loop=loop9
+ snap=/tmp/sample.squashfs
+ [ ! -f /tmp/sample.squashfs ]
+ losetup --show /dev/loop9 /tmp/sample.squashfs
/dev/loop9
+ cat /sys/block/loop9/loop/backing_file
/tmp/sample.squashfs
+ cat /sys/block/loop9/loop/autoclear
0
+ mount /dev/loop9 /mnt
+ umount /mnt
+ cat /sys/block/loop9/loop/backing_file
/tmp/sample.squashfs
+ cat /sys/block/loop9/loop/autoclear
0
+ losetup -d /dev/loop9
+ cat /sys/block/loop9/loop/backing_file
cat: /sys/block/loop9/loop/backing_file: No such file or directory
+ :
+ cat /sys/block/loop9/loop/autoclear
cat: /sys/block/loop9/loop/autoclear: No such file or directory
+ :
+ losetup --show /dev/loop9 /tmp/sample.squashfs
/dev/loop9
+ cat /sys/block/loop9/loop/backing_file
/tmp/sample.squashfs
+ cat /sys/block/loop9/loop/autoclear
0
+ mount /dev/loop9 /mnt
+ losetup -d /dev/loop9
+ losetup -d /dev/loop9
+ losetup -d /dev/loop9
+ cat /sys/block/loop9/loop/backing_file
/tmp/sample.squashfs
+ cat /sys/block/loop9/loop/autoclear
1
+ umount /dev/loop9
+ cat /sys/block/loop9/loop/backing_file
cat: /sys/block/loop9/loop/backing_file: No such file or directory
+ :
+ cat /sys/block/loop9/loop/autoclear
cat: /sys/block/loop9/loop/autoclear: No such file or directory
+ :
```

This breaks systemd-shutdown, as it calls ioctl, sees that it succeeds and proceeds to try the shutdown loop again, even though nothing has actually changed. See how one can call losetup -d multiple times, and backing_file is still there!

Relevant systemd-shutdown code is at https://github.com/systemd/systemd/blob/b895fa08e6809ab54e20888f7d01ae848272e981/src/shutdown/umount.c#L326

Relevant linux code is at https://github.com/torvalds/linux/blob/7e0165b2f1a912a06e381e91f0f4e495f4ac3736/drivers/block/loop.c#L1208
(some of it was slightly refactor elsewhere in prior kernel versions)

We have a couple of options out of this:
* Do not attempt iocl on the autoclear devices, as they shouldn't be there in the first place (autocleared), or they have high ref count, meaning calling iocl on them will succeed without actually doing anything. This is proposed in https://github.com/systemd/systemd/pull/14386

* Patch kernel, such that it returns an error if refcount is high, and autoclear is already on, meaning that repeated calls to this iocl fail when indeed it does nothing.

Something like
```
diff --git a/drivers/block/loop.c b/drivers/block/loop.c
index bdf18e73c1df..186ae9e08fcd 100644
--- a/drivers/block/loop.c
+++ b/drivers/block/loop.c
@@ -1070,8 +1070,15 @@ static int loop_clr_fd(struct loop_device *lo)
         * failing tests because blkid via udev races with a losetup
         * <dev>/do something like mkfs/losetup -d <dev> causing the losetup -d
         * command to fail with EBUSY.
+        *
+        * And only do this once, if auto-teardown is already on, someone
+        * is making this call in a loop, raise an error to make them
+        * stop. For example, systemd-shutdown, when / is a loopmount that
+        * fails to unmount (refcnt > 1)
         */
        if (atomic_read(&lo->lo_refcnt) > 1) {
+               if (lo->lo_flags && LO_FLAGS_AUTOCLEAR)
+                       return -EINVAL;
                lo->lo_flags |= LO_FLAGS_AUTOCLEAR;
                mutex_unlock(&lo->lo_ctl_mutex);
                return 0;
```

* Read the autoclear & backingfile syfs files before and after. If the autoclear flag has changed, kernel did something. If the autoclear flag did not change, and backing_file is still there it means ioctl did nothing and we should return error. I'm preparing such patch. This way we don't need to guess around what kernel is doing.

**Comment by poettering** [comment]
Thanks for tracking this down. I think it's nicer if we treat such autoclear loopbacks that are still busy actually as busy. I put together another commit to #14409 that does just that: after LOOP_CLR_FD succeeded we check if the device is actually still attached, and if it is we propagate EBUSY. 

And quite frankly the kernel behaviour here is super weird. THey should at least document this...

**Comment by poettering** [comment]
Would be great if you could give #14409 a whirl to see if it fixes this for you?
