### ISSUE TITLE
Systemd 219: infinite umount after failed in "shutdown -r" until timeout

### ISSUE THREAD

**Issue by mwang911** [systemd/systemd#14428]
![11](https://user-images.githubusercontent.com/15031375/71408227-632c4c80-2678-11ea-94b9-bf74616b35f5.jpg)
**systemd version the issue has been seen with**
> ...

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

**Comment by poettering** [comment]
Sorry, but we only cover issues in the two most recently released upstream systemd versions in this bug tracker. For everything else, please contact your downstream distribution. 219 is waaaaay older than the two most recent upstream version of systemd.
