### ISSUE TITLE
systemctl status has cgroup capitalized as CGroup

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#14429]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > cgroup is written as lower case

**Unexpected behaviour you saw**
 > Written as CGroup

Recently when I was writing Arch Wiki page on cgroups and the inconsistent spelling of the name cgroup was brought up. In most of [kernel](https://www.kernel.org/doc/Documentation/cgroup-v2.txt) and systemd documentation the cgroup is written in lower case. One noteable difference is **systemctl status** command that writes it as CGroup. Not sure if it worth fixing but I can submit a pull request if you want.

**Comment by poettering** [comment]
hmm, but we uppercase all field names... i.e. ti would have to be "Cgroup" then, which looks worse than "CGroup" by a lot... Not sure this is worth "fixing"?

**Comment by igo95862** [comment]
_systemd-cgls_ and  _systemd-cgtop_ has it written as **Control Group**

**Comment by Filip-jpg** [comment]
SUP

**Comment by poettering** [comment]
well, "systemctl status" has a more compact output, i.e. it's all aligned around the colons of the fields, and there's just not enough room to spell out "Control Group". We'd probably have to re-align the table then and make all fields more wide.
