### ISSUE TITLE
Drop-in precedence is not adhered to when using type.d drop-ins

### ISSUE THREAD

**Issue by GothAck** [systemd/systemd#14439]
**systemd version the issue has been seen with**
systemd 244 git checkout

**Used distribution**
Ubuntu eoan 

**Expected behaviour you didn't see**
 /etc/systemd/system/service.d/test.conf would get overridden by /etc/systemd/system/systemd-.service.d/test.conf

**Unexpected behaviour you saw**
 /etc/systemd/system/service.d/test.conf  always takes prescience, it cannot be overridden by more sepcific drop-ins 

**Steps to reproduce the problem**
Added a test case in commit https://github.com/GothAck/systemd/commit/eb9fdb498a1fa82942b7eb56565ecc003235abbf

**Comment by GothAck** [comment]
PR #14440  against tag v244

**Comment by GothAck** [comment]
PR #14441 against master

**Comment by poettering** [comment]
Ah, eh, #14441 is merged already, let's close this hence!
