### ISSUE TITLE
systemd-cgroup v2 controller doesn't work on user-units/scopes in unified mode.

### ISSUE THREAD

**Issue by Ozymandias42** [systemd/systemd#14433]
**systemd version the issue has been seen with**
> ...
systemd 243 (+suse.225.gdbb1d4734d)
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > …
openSUSE Tumbleweed

**Expected behaviour you didn't see**
 > …
Process in user-level scope-unit being killed by OOM-killer upon doing 
`systemctl --user set-property flatpak-arbitrary.flatpak.app "MemoryMax=4K"`
when using unified hierachy with both cgroup1 and cgroup2 as apparent via absence of `systemd.unified_cgroup_hierarchy`  kernelflag and absence of `systemd.legacy_systemd_cgroup_controller` kernelflag.
`mount | grep cgroup` shows both cgroup and cgroup2 under /sys/fs/cgroup
According to documentation here: 
https://manpages.debian.org/testing/systemd/systemd.1.en.html
the systemd-controller should use cgroups2 in this case, meaning unprivileged use of cgroups via user-owned scopes or services should work.

**Unexpected behaviour you saw**
 > …
the set resource restrictions are ignored. Nothing happens.

**Steps to reproduce the problem**
make sure `mount | grep cgroup` yields both cgroup entries and one cgroup2 entry under /sys/fs/cgroup
start a user-owned service or scope, for example a flatpak app.
apply resource restrictions to it to make it be killed by OOM-killer via `systemctl --user set-property name-of-scope-or-service MemoryMax=4K`

anti-check: boot with `systemd.unified_cgroup_hierarchy=true`  to enforce exclusive use of cgroup v2 and repeat. process should now get killed as expected.

**Comment by poettering** [comment]
If the "hybrid" hierarchy is used (i.e. both cgroupv1 and cgroupv2 mounted) then cgroupv2 is only used for tracking PIDs, it has no controllers associated those are left in cgroupv1 land and thus are not delegated to unpriv processes). If you want delegation to unpriv users use exclusive cgroupsv2 mode (unified), do not use hybrid mode.

In fact, don't use hybrid mode at all anymore, it's a dead end, and was a bad idea to have added in the first place.

**Comment by Ozymandias42** [comment]
Thanks. 
That clears that up then. cgroupv2 it is then. Let's hope LXC moves to that soon too.

**Comment by poettering** [comment]
iirc LXC already supports that too. right @brauner?

**Comment by brauner** [comment]
> iirc LXC already supports that too. right @brauner?

It does, yes!
