### ISSUE TITLE
resolved has no way to disable DNSSEC capability learning checks

### ISSUE THREAD

**Issue by Avamander** [systemd/systemd#14435]
**systemd version the issue has been seen with**
> exists the very least since 233 and up to at least 243, see https://github.com/systemd/systemd/issues/6490

**Used distribution**
> I currently use Ubuntu 19.10 but also affects Fedora, Arch and other distros

**Expected behaviour you didn't see**
>  Capabilities being detected correctly and DNSSEC keeps working. Also having an option to disable incorrect capability learning for an extended period of time

**Unexpected behaviour you saw**
> Having DNSSEC enabled makes incorrect feature learning especially painful because then resolved totally stops working. For some reason resolved sees fit claiming a upstream server doesn't support a required feature but it seems to be often just plain incorrect and causes nearly permanent resolving failure.

**Steps to reproduce the problem**
> Just configure the resolver to have DNSSEC enabled and it'll stop resolving and not recover, resetting capabilities works for only a short time. Having a switch/configuration option for this would be optimal.

**Comment by Avamander** [comment]
Also opened on Ubuntu issue tracker: https://bugs.launchpad.net/systemd/+bug/1857639

**Comment by Avamander** [comment]
Also related: https://github.com/systemd/systemd/issues/9384

**Comment by poettering** [comment]
Closed by #18624
