### ISSUE TITLE
systemctl list command for showing all units under <service>@.service 

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#14436]
**Is your feature request related to a problem? Please describe.**
I have different `wg-quick@.service` files like:

```
wg-quick@germany.service
wg-quick@singapore.service
wg-quick@tokyo.service
...
```

Is there any way to show all of these files via one:
`systemctl list wg-quick@.service` command?

**Describe the solution you'd like**
I would like to have a command like `systemctl list` that shows all instances of a `wg-quick@.service` template.

**Describe alternatives you've considered**

Not sure how to accomplish this, because there is no `wg-quick@germany` file in the filesyste,.. I would need to trigger the systemd dbus API somehow (I guess).

**Comment by keszybz** [comment]
There is no way to show "all" instances, because new ones can be created at any time, and old ones are not stored anywhere, except for logs. To show the ones that are currently loaded (active or failed), a glob can be used:
```console
$ systemctl list-units 'wg-quick@*'
```
