### ISSUE TITLE
kdbus causes some problem to pulseaudio

### ISSUE THREAD

**Issue by lb90** [systemd/systemd#1444]
Hello, I'm running an updated installation of Arch Linux and I've installed kdbus from the AUR. kernel is version 4.2. There is a problem: when I play music with vlc I hear a little skipping/glitch every minute or so. After that systemctl -b displays this:

ott 02 11:13:03 hp pulseaudio[746]: E: [alsa-sink-92HD81B1X5 Analog] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
ott 02 11:13:03 hp pulseaudio[746]: E: [alsa-sink-92HD81B1X5 Analog] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_hda_intel'. Please report this issue to the ALSA developers.
ott 02 11:13:03 hp pulseaudio[746]: E: [alsa-sink-92HD81B1X5 Analog] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
ott 02 11:14:24 hp gnome-session[681]: [00007f6b0c002c58] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer
ott 02 11:14:25 hp gnome-session[681]: [00007f6b0c002c58] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer

But it happens only if using kdbus, if I boot with kdbus disabled everything operates correctly!

uname -a: Linux hp 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux

**Comment by lb90** [comment]
this is a known bug affecting pulseaudio on intel hda devices, see here: https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/996906

the glitch in sound can appear after some minutes and even after hours, it's very very unfrequent. The first time I heard it I had just installed kdbus kernel module, and that led me to believe it could be related in some way to the dbus compatibility layer! That's not the case, so I close the issue. Sorry

**Comment by dvdhrm** [comment]
Thanks for the followup!
