### ISSUE TITLE
/etc/modprobe.d install option broken - cgroup: fork rejected by pids controller in /system.slice/systemd-modules-load.service

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#14459]
**systemd version the issue has been seen with**

241

**Used distribution**

Debian buster.

**Expected behaviour you didn't see**

Kernel module correctly load.

**Unexpected behaviour you saw**

Kernel module not load.

**Steps to reproduce the problem**

Install [tirdad](https://github.com/Whonix/tirdad) (probably also any other kernel module).

file `/etc/modprobe.d/30_tirdad.conf`

    install tirdad /usr/lib/tirdad/loader

(modprobe.d supports `install modulename command...` to run arbitrary command as per its [man page](https://linux.die.net/man/5/modprobe.d).

file `/usr/lib/modules-load.d/30_tirdad.conf`

    tirdad

Module won't load at boot.

    sudo systemctl restart systemd-modules-load

> Jan 01 08:36:17 host systemd[1]: Stopped Load Kernel Modules.
> Jan 01 08:36:17 host systemd[1]: Stopping Load Kernel Modules...
> Jan 01 08:36:17 host systemd[1]: Starting Load Kernel Modules...
> Jan 01 08:36:36 host systemd-modules-load[7529]: /usr/lib/tirdad/loader: fork: retry: Resource temporarily unavailable
> Jan 01 08:36:36 host kernel: cgroup: fork rejected by pids controller in /system.slice/systemd-modules-load.service
> Jan 01 08:36:37 host systemd-modules-load[7529]: /usr/lib/tirdad/loader: fork: retry: Resource temporarily unavailable
> Jan 01 08:36:39 host systemd-modules-load[7529]: sh: 1: Cannot fork
> Jan 01 08:36:39 host systemd-modules-load[7529]: modprobe: ERROR: ../libkmod/libkmod-module.c:979 command_do() Error running install command for tirdad
> Jan 01 08:36:39 host systemd-modules-load[7529]: modprobe: ERROR: could not insert 'tirdad': Unknown symbol in module, or unknown parameter (see dmesg)
> Jan 01 08:36:39 host systemd-modules-load[7529]: modprobe: ERROR: ../libkmod/libkmod-module.c:979 command_do() Error running install command for tirdad
> Jan 01 08:36:39 host systemd-modules-load[7529]: Inserted module 'tirdad'
> Jan 01 08:36:39 host systemd[1]: Started Load Kernel Modules.

    cat /lib/systemd/system/systemd-modules-load.service

```
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Load Kernel Modules
Documentation=man:systemd-modules-load.service(8) man:modules-load.d(5)
DefaultDependencies=no
Conflicts=shutdown.target
Before=sysinit.target shutdown.target
ConditionCapability=CAP_SYS_MODULE
ConditionDirectoryNotEmpty=|/lib/modules-load.d
ConditionDirectoryNotEmpty=|/usr/lib/modules-load.d
ConditionDirectoryNotEmpty=|/usr/local/lib/modules-load.d
ConditionDirectoryNotEmpty=|/etc/modules-load.d
ConditionDirectoryNotEmpty=|/run/modules-load.d
ConditionKernelCommandLine=|modules-load
ConditionKernelCommandLine=|rd.modules-load

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/lib/systemd/systemd-modules-load
TimeoutSec=90s
```

**Comment by topimiettinen** [comment]
> Jan 01 08:36:36 host systemd-modules-load[7529]: /usr/lib/tirdad/loader: fork: retry: Resource temporarily unavailable
Jan 01 08:36:36 host kernel: cgroup: fork rejected by pids controller in /system.slice/systemd-modules-load.service

This means that `fork(2)` fails due to cgroup restrictions. Are you sure there are no `TasksMax` or `LimitNPROC` lines somewhere? Please post result of `systemctl cat systemd-modules-load.service`.

**Comment by adrelanos** [comment]
sudo systemctl cat systemd-modules-load.service --no-pager

```
# /lib/systemd/system/systemd-modules-load.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Load Kernel Modules
Documentation=man:systemd-modules-load.service(8) man:modules-load.d(5)
DefaultDependencies=no
Conflicts=shutdown.target
Before=sysinit.target shutdown.target
ConditionCapability=CAP_SYS_MODULE
ConditionDirectoryNotEmpty=|/lib/modules-load.d
ConditionDirectoryNotEmpty=|/usr/lib/modules-load.d
ConditionDirectoryNotEmpty=|/usr/local/lib/modules-load.d
ConditionDirectoryNotEmpty=|/etc/modules-load.d
ConditionDirectoryNotEmpty=|/run/modules-load.d
ConditionKernelCommandLine=|modules-load
ConditionKernelCommandLine=|rd.modules-load

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/lib/systemd/systemd-modules-load
TimeoutSec=90s
```

**Comment by poettering** [comment]
That suggests that something being forked off via the kmod loading created tons of processes so that the per-service tasks limit we set is hit?

Note that it is generally a bad idea using "install" in modprobe.d. Don't. Find a better way. A kernel module loader is not a scripting engine...

anyway, if fork() fails, then the limit is hit. find out why. i.e. start with "systemctl show -p TasksMax systemd-modules-load.service" to see the limit in effect. Figure out what other stuff forks stuff off your module loader scripts?

**Comment by poettering** [comment]
Let's close due to lack of response.
