### ISSUE TITLE
Some doubts about commit eef85c4a3f8054d29383a176f6cebd1ef3a15b9a (“core: track why unit dependencies came to be”)

### ISSUE THREAD

**Issue by taskset** [systemd/systemd#14453]
The unit_add_siblings_to_cgroup_realize_queue() has the following comments:

/* This adds the siblings of the specified unit and the
 * siblings of all parent units to the cgroup queue. (But
 * neither the specified unit itself nor the parents.) */

But commit eef85c4a3f8054d29383a176f6cebd1ef3a15b9a (“core: track why unit dependencies came to be”) introduces such a modification:

https://github.com/systemd/systemd/commit/eef85c4a3f8054d29383a176f6cebd1ef3a15b9a#diff-934893719bf9881c440da8cf911341ccL1579

`@@ -1575,8 +1576,9 @@ static void unit_add_siblings_to_cgroup_realize_queue(Unit *u) {`
`         while ((slice = UNIT_DEREF(u->slice))) {`
`                 Iterator i;`
 `                Unit *m;`
`+                void *v;`

`-                SET_FOREACH(m, slice->dependencies[UNIT_BEFORE], i) {`
`+                HASHMAP_FOREACH_KEY(v, m, u->dependencies[UNIT_BEFORE], i) {`
`                         if (m == u)`
`                                 continue;`

This patch changes slice->dependencies  dependencies to u->dependencies, which creates fewer cgroups.
We don't know if such a change is appropriate?

**Comment by w-simon** [comment]
@poettering    Would you please have a look, thank you.

**Comment by poettering** [comment]
@w-simon you are right. Fix prepared in #14534.
