### ISSUE TITLE
resolved: reload /etc/hosts also when inode nr changes (to support nixos where mtime is fixed to 1)

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#14456]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > NixOS Unstable

I'm using a setup of systemd-nspawn containers with private network adresses, and sniproxy on the host to act as a reverse proxy in front of those containers.
I'd like to refer to the names of those containers instead of hard-coding ip adresses in configuration files.

sniproxy doesn't use `getaddrinfo(3)` to do resolving, but instead will do DNS requests on its own. I pointed it to resolved's stub resolver at `127.0.0.53`, which it can dig for `<containername>` records.

I did a renumbering of IPs. Both `machinectl list` and `getent hosts <containername>`  showed the new adress(es), but resolved kept delivering the old DNS records over the stub interface (due to caching?).

Can resolved be a bit smarter, and maybe not cache records provided via "local" nss databases?

**Comment by poettering** [comment]
What is .containers? who defines that? Can you elaborate?

**Comment by flokli** [comment]
Ah, ignore the `.containers` - that's an entry added to `/etc/hosts` by some other tooling - I assumed it was some `nss-mymachines` magic.

However, as `/etc/hosts` entries get populated via nss too, I assume the issue is the same.

**Comment by poettering** [comment]
hmm, this is weird, before eahc lookup we check the mtime of /etc/hosts and reread if it changed? does the mtime change when your entry is changed and still we don't reread?

**Comment by flokli** [comment]
On NixOS, `/etc/hosts` is a symlink to `/etc/static/hosts`, and `/etc/static` is a symlink to a directory somewhere in the nix-store, with timestamps set to `Jan  1  1970` - so checking mtime on `/etc/static/hosts` won't work (it would currently work if checking of the symlink itself, but I wouldn't count on that)

Does this mean the resolved stub is reimplementing parts of `nss_files`, and not using nss at all by itself? (so doesn't know about `nss-mymachines`)?

**Comment by poettering** [comment]
resolved is a provider of NSS not a consumer. And yes, if you query resolved then it checks /etc/hosts, but it will not consult arbitrary other NSS modules.

**Comment by poettering** [comment]
hmm, when you update the file you at least will replace the inode, right? so if we track the inode nr we should be fine?

**Comment by flokli** [comment]
Once realized, files in the nix store are immutable. This means, if I want to update my `/etc/hosts`, I build a new `hosts` file which will be in another place in the nix store. The `hosts` file will still stick around on that nix store path, and eventually get garbage-collected.

`/etc/hosts` is a symlink to `/etc/static/hosts`
`/etc/static` is a symlink to `/nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-etc/etc`

When the system switches to a new configuration, the `/etc/static` symlink is what will changed (and have a new inode number) - see https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/etc/setup-etc.pl#L23.

`/nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-etc/etc/hosts` and `/nix/store/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-etc/etc/hosts` will have different inode numbers, but you'd need to traverse the symlink chain every time to see that it points to a new location.
