### ISSUE TITLE
systemd-fsckd tries to check *mounted* filesystems by default

### ISSUE THREAD

**Issue by joshudson** [systemd/systemd#14452]
If somebody left a filesystem mounted read-write when exiting emergency mode, don't try to check it. That way lies data corruption.

I caught systemd-fsckd doing this because e2fsck complained. Don't do it.

**Comment by poettering** [comment]
there's no systemd-fsckd? what is this about?

Traditionally on Linux the root fs is fsck'ed while mounted. Only with systemd we introduced for the first time that the root fs is checked from the initrd before we mounted it instead of from the host after doing so. That is, as long as there's an initrd at all. If there is not we continue to do the fsck after the transition, but only if the rootfs is actually read-only, see systemd-fsck-root.service about that, specifically the line ConditionPathIsReadWrite=!/ which conditions this check on / being mounted read-only.

hence, I am pretty sure we do everything correctly here. There's no fsckd service though, which leaves me a bit confused about your question?

Linux has no API to check if a file system is currently mounted. (i mean, one could parse /proc/self/mountinfo, but that sucks hard since it cannot cover btrfs or even other fs namespaces), hence implementing an additional safety check before we invoke the util-linux fsck tool isn't really doable afaics...

But what is this precisely about, can you elaborate?

**Comment by marcosfrm** [comment]
Debian (or Ubuntu?) specific stuff maybe?

https://salsa.debian.org/systemd-team/systemd/blob/debian/master/debian/patches/debian/fsckd-daemon-for-inter-fsckd-communication.patch

**Comment by poettering** [comment]
hmm, that's downstream stuff and it only shows progress bars? @joshudson so what's this about?

**Comment by joshudson** [comment]
You're right, the way to check if something is mounted sucks. The way I normally do it is parse /proc/mounts and hope nobody made an alias device.

I had to use fsck.mode=force to get it to reproduce on the very next
boot. Otherwise, it reproduces sporadically. I don't want to
deliberately crash the system badly enough to get it to really need to
fsck the next boot.

Reduced logs:

Dec 31 08:42:05 nova kernel: Command line: BOOT_IMAGE=Lin ro
root=/dev/mapper/isw_cfbejbfeib_Volume11 video=960x540 fsck.mode=force
Dec 31 08:42:05 nova kernel: Kernel command line: BOOT_IMAGE=Lin ro
root=/dev/mapper/isw_cfbejbfeib_Volume11 video=960x540 fsck.mode=force
Dec 31 08:42:05 nova kernel: Adding 33554428k swap on
/dev/mapper/isw_cfbejbfeib_Volume12.  Priority:-2 extents:1
across:33554428k FS
Dec 31 08:42:08 nova systemd[1]: Condition check resulted in
/dev/mapper/isw_cfbejbfeib_Volume12 being skipped.
Dec 31 08:42:08 nova dmraid-activate[579]: ERROR: Cannot retrieve RAID
set information for isw_cfbejbfeib_Volume1
Dec 31 08:42:08 nova dmraid-activate[572]: ERROR: Cannot retrieve RAID
set information for isw_cfbejbfeib_Volume1
Dec 31 08:42:09 nova systemd[1]: Condition check resulted in
/dev/mapper/isw_cfbejbfeib_Volume13 being skipped.
Dec 31 08:42:09 nova systemd[1]: Starting File System Check on
/dev/mapper/isw_cfbejbfeib_Volume13...
Dec 31 08:42:09 nova systemd[1]: Started File System Check on
/dev/mapper/isw_cfbejbfeib_Volume13.
Dec 31 08:42:15 nova systemd[1]: Condition check resulted in
/dev/mapper/isw_cfbejbfeib_Volume14 being skipped.
Dec 31 08:42:15 nova systemd[1]: Starting File System Check on
/dev/mapper/isw_cfbejbfeib_Volume14...
Dec 31 08:42:15 nova systemd[1]: Started File System Check on
/dev/mapper/isw_cfbejbfeib_Volume14.

e2fsck complains on the console about Volume14 being mounted, but
there's no trace in the logs.

Note that I have to mount everything in /sbin/init before handing off
to systemd because otherwise it waits for the raid controller
containing / to come up so it can mount it read-write (makes no
sense--/ is already up by definition).

**Comment by joshudson** [comment]
Got a complete log of it trying to check mounted filesystems w/o force fsck. Note that the log still doesn't show they're mounted, but they _are mounted_.
[systemd3.log](https://github.com/systemd/systemd/files/4018033/systemd3.log)

**Comment by mbiebl** [comment]
If you mount your partitions manually via a custom script before you exec init, I would make sure that you set passno to 0 in /etc/fstab.
This way systemd-fsck@.service won't be run for those partitions.

**Comment by joshudson** [comment]
@mbiebl : The custom script runs `fsck -AMsp`, but I think this is more fundamental. systemd should be trying to do the equivalent of `fsck -M` and just skip mounted filesystems.

**Comment by marcosfrm** [comment]
`fsck` uses libmount `mnt_table_find_source()` (then `mnt_table_find_srcpath()`), which has some glue for Btrfs detection.

**Comment by mbiebl** [comment]
> @mbiebl : The custom script runs `fsck -AMsp`, but I think this is more fundamental. systemd should be trying to do the equivalent of `fsck -M` and just skip mounted filesystems.

`systemd-fsck` is just a very thin wrapper around `fsck` and passes `-M` to fsck.
https://github.com/systemd/systemd/blob/master/src/fsck/fsck.c#L384

Are you saying this is not working?

**Comment by joshudson** [comment]
I observed it not working. Easy to verify. Boot fsck.mode=force init=/bin/sh mount a filesystem and do exec /sbin/init. Nothing appears in the logs but there is spam on the console about checking mounted filesystems. I tried fsck -M directly as well and that works correctly.

**Comment by poettering** [comment]
Maybe a race? it's not helping if fsck -M checks /proc/self/mountinfo, if the device is already in the progress of being mounted then. i.e. "-M" is not atomic in its behaviour, it's a one time check in fsck made under no lock taken, and the kernel doesn't do a reverse check at all...

-M is a nice helper for serialized cases without namespacing and such. it's not going to protect you in the general case.

**Comment by mbiebl** [comment]
I can't reproduce the issue, fwiw.
@joshudson  if you run `SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-fsck /dev/mapper/XXX`, what do you get?

**Comment by mbiebl** [comment]
The output of `systemctl status systemd-fsck@....service` whould be helpful as well.

**Comment by joshudson** [comment]
I can't eliminate the possibility of a race condition, but I suspect
rather we need an `else` for `!root_directory`.

Requested infos:

root@nova:~# SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-fsck
/dev/mapper/isw_cfbejbfeib_Volume14
Found container virtualization none.
Successfully forked off '(fsck)' as PID 1929.
fsck succeeded.
root@nova:~# SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-fsck
/dev/mapper/isw_cfbejbfeib_Volume11
Found container virtualization none.
Successfully forked off '(fsck)' as PID 1933.
fsck succeeded.
root@nova:~# systemctl status systemd-fsck@isw_cfbejfbeib_Volume14
* systemd-fsck@isw_cfbejfbeib_Volume14.service - File System Check on
/isw_cfbejfbeib_Volume14
   Loaded: loaded (/lib/systemd/system/systemd-fsck@.service; static;
vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-fsck@.service(8)
root@nova:~# systemctl status systemd-fsck@isw_cfbejfbeib_Volume11
* systemd-fsck@isw_cfbejfbeib_Volume11.service - File System Check on
/isw_cfbejfbeib_Volume11
   Loaded: loaded (/lib/systemd/system/systemd-fsck@.service; static;
vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-fsck@.service(8)

I think I need to run it with the force option, which I don't seem to
be able to do from the command line.

**Comment by joshudson** [comment]
It's the race condition. I eliminated everything else by jamming logging into `/sbin/fsck`.

**Comment by poettering** [comment]
OK, this is unfixable then for us, if it's the race. Let's close.
