### ISSUE TITLE
Make creation of persistant services in one command line like with systemd-run possible

### ISSUE THREAD

**Issue by Eucyon** [systemd/systemd#14458]
**Describe the solution you'd like**
With systemd-run, one can create simple services and their timers in just one command line, which is easier than creating unit files and starting or enabling them, especially for one-timers. But they don't survive the next boot, they are transient.

Please enable this feature for persistant units which do survive the next boot.

Related to #13485, #14245, #14251.

**Comment by doverride** [comment]
```
for i in $(systemd-run $@ 2>&1 | awk -F": " '{ print $2 }')
do
   cat /run/systemd/transient/$i > /etc/systemd/system/$i
done
```

**Comment by poettering** [comment]
Duplicate of #13485
