### ISSUE TITLE
predictables ifnames are racy on bnxt_en ethernet kernel driver

### ISSUE THREAD

**Issue by RajeshRavi-brcm** [systemd/systemd#14464]
**systemd version the issue has been seen with**
> systemd 243 (243+)

**Used distribution**
 > Yocto poky 3.0

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 >after rmmod ;modprobe; modprobe of bnxt_en network driver, interface (re)naming is inconsistent and differs in last part(port name)
Often, /sys/class/net/<iface>/phys_port_name entry is not populated yet, by the time dev_pci_slot() function [src/udev/udev-builtin-net_id.c] reads it.

Following  patch works around (solves) the issue:

diff --git a/src/udev/udev-builtin-net_id.c b/src/udev/udev-builtin-net_id.c
index b82fd88497..0d1dc6d662 100644
— a/src/udev/udev-builtin-net_id.c
+++ b/src/udev/udev-builtin-net_id.c
@@ -257,6 +257,7 @@ static int dev_pci_slot(sd_device *dev, struct netnames *names) {
struct dirent *dent;
int r;

+ usleep(50000);
r = sd_device_get_sysname(names->pcidev, &sysname);
if (r < 0)
return r;

**Steps to reproduce the problem**
rmmod bnxt_en;modprobe bnxt_en; ifconfig -a

**Comment by poettering** [comment]
this is a bug in that driver, no? right, @gregkh, the "phys_port_name" should appear at the time the device shows up and not later, no?

**Comment by RajeshRavi-brcm** [comment]
I think phys_port_name_show() [kernel/net/core/net-sysfs.c] populates by obtaining portname from
individual driver via .ndo_get_phys_port_name() member of net_device_ops.

Following is the code snippet which implements the function:

[Ref: kernel/drivers/net/ethernet/broadcom/bnxt/bnxt.c]

.ndo_get_phys_port_name = bnxt_get_phys_port_name

static int bnxt_get_phys_port_name(struct net_device *dev, char *buf,
                                    size_t len)
 {
         struct bnxt *bp = netdev_priv(dev);
         int rc;
 
         /* The PF and it's VF-reps only support the switchdev framework */
         if (!BNXT_PF(bp))
                 return -EOPNOTSUPP;
 
         rc = snprintf(buf, len, "p%d", bp->pf.port_id);
 
         if (rc >= len)
                 return -EOPNOTSUPP;
         return 0;
 }

**Comment by gregkh** [comment]
On Thu, Jan 02, 2020 at 06:33:03AM -0800, Lennart Poettering wrote:
> this is a bug in that driver, no? right, @gregkh, the "phys_port_name" should appear at the time the device shows up and not later, no?

Yes, it "should".

**Comment by poettering** [comment]
OK, let's consider this a kernel issue then. Please report to the bnxt driver maintainers, so that they make sure the sysfs attribute is available at the moment the netlink message announcing the device is sent from the kernel. Otherwise this will always be racy. Thank you!

**Comment by RajeshRavi-brcm** [comment]
Thanks Lennart @poettering  and @gregkh   for prompt response.
