### ISSUE TITLE
logind does not give me access to my backlight device

### ISSUE THREAD

**Issue by majewsky** [systemd/systemd#14463]
My understanding is that systemd-logind should give me write access to my backlight device in sysfs so that, as the user sitting in front of the machine, I can set brightness by writing into sysfs without needing sudo. This is not working on my system.

Here is what is working:

1. udev correctly applies `/lib/udev/rules.d/71-seat.rules` (which ships with systemd) and marks the backlight device as belonging to a seat:
   ```
   $ udevadm info /sys/class/backlight/amdgpu_bl0 | grep TAGS
   E: TAGS=:systemd:seat:
   ```
2. logind correctly associates the backlight device with seat0 (the only seat on my notebook):
   ```
   $ loginctl seat-status seat0 | grep backlight
                     ├─/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/backlight/amdgpu_bl0
                     │ backlight:amdgpu_bl0
   ```
3. logind correctly associates my desktop session (the only session running right now) with that seat and considers it active:
   ```
   $ loginctl session-status 1 | grep 'Seat\|State' | grep -v grep
               Seat: seat0; vc2
              State: active
   ```

At this point, I'm out of ideas and don't know what else to check. Any pointers would be appreciated. If you need any additional information, I'll be happy to supply it.

The following software is involved:
* The OS is Arch Linux with all updates as of 2020-01-01.
* systemd and udev are version 244.1.
* The display manager is sddm 0.18.1.
* The Wayland compositor is sway 1.2.

**Comment by poettering** [comment]
so what happens if you issue commands like these:

```sh
$ busctl call org.freedesktop.login1 /org/freedesktop/login1/session/auto org.freedesktop.login1.Session SetBrightness "ssu" "backlight" "amdgpu_bl0" 4711
```

(with 4711 replaced by some appropriate value for your backlight device?)

**Comment by majewsky** [comment]
That works.

**Comment by poettering** [comment]
So? What doesn't work then?

**Comment by poettering** [comment]
What's the full  output of loginctl session-status btw?

**Comment by majewsky** [comment]
```
$  loginctl session-status
1 - stefan (1001)
           Since: Thu 2020-01-02 11:44:46 CET; 1h 9min ago
          Leader: 1081 (sddm-helper)
            Seat: seat0; vc2
             TTY: tty2
         Service: sddm-autologin; type wayland; class user
           State: active
            Unit: session-1.scope
                  ├─1081 /usr/lib/sddm/sddm-helper --socket /tmp/sddm-autha635d3bb-4de8-4457-9a0a-e05e23901616 --id 1 --start sway --user stefan --autologin
                  ├─1094 /usr/bin/kwalletd5 --pam-login 7 3
                  ├─1095 sway
                  ├─1315 Xwayland :1 -rootless -terminate -listen 15 -listen 17 -wm 58
                  ├─1836 i3status-rs /home/stefan/.config/i3status-rust.toml
                  ├─2532 swaybg -o * -i /home/stefan/Wallpapers/c3d2-v2-1920x1080.png -m fill
                  ├─2534 swaybar -b bar-0
                  ├─2537 i3status-rs /home/stefan/.config/i3status-rust.toml
                  ├─2715 /usr/lib/firefox/firefox
                  ├─2878 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 7142 -prefMapSize 244775 -parentBuildID 20191202234414 -greomni /usr/lib/firefox/omni.ja -ap>
                  ├─4663 /usr/lib/firefox/firefox -contentproc -childID 15 -isForBrowser -prefsLen 7925 -prefMapSize 244775 -parentBuildID 20191202234414 -greomni /usr/lib/firefox/omni.ja -a>
                  ├─4952 /usr/lib/firefox/firefox -contentproc -childID 17 -isForBrowser -prefsLen 7925 -prefMapSize 244775 -parentBuildID 20191202234414 -greomni /usr/lib/firefox/omni.ja -a>
                  ├─5114 /usr/lib/firefox/firefox -contentproc -childID 19 -isForBrowser -prefsLen 7925 -prefMapSize 244775 -parentBuildID 20191202234414 -greomni /usr/lib/firefox/omni.ja -a>
                  ├─5214 konsole
                  ├─5231 /bin/zsh
                  ├─5247 loginctl session-status
                  └─5248 less -R
```

> What doesn't work then?

As I said, my understanding is that I should have write access to the device in sysfs. The GUI application that I'm using to control the backlight ([i3status-rust](https://github.com/greshake/i3status-rust)) also assumes that this is possible (see [this documentation section](https://github.com/greshake/i3status-rust/blob/master/blocks.md#setting-brightness-with-the-mouse-wheel)). If this is not a behavior provided by logind by default, then I'd like to know if there is a way to enable such behavior. I've tried to set permissions on the device in sysfs using the udev rule suggested by the documentation section linked above:
```udev
ACTION=="add", SUBSYSTEM=="backlight", GROUP="video", MODE="0664"
```
But that does not have any effect (`ls` shows `root:root` for all relevant files in sysfs), leading me to believe that it is overridden later (e.g. by logind when the session starts).

**Comment by poettering** [comment]
> > 
> 
> As I said, my understanding is that I should have write access to the device in sysfs.

Ah no, you do not get that. We don't do access management on the device node, that's not safe, as we can never take that away. It's the D-Bus interface or nothing. it checks if you belong to a session on a seat the backlight device you pick belongs to and then does policykit. Raw sysfs access does not provide that.

Sorry. If you want direct access then logind won't do that for you, and that's not going to change.

The udev line you posted applies perms to a device node, not to sysfs files. udev is not for managing syfs access anyway, things are not designed for that.

Sorry, but this is out of focus for logind and unsafe, and thus unsupported. Closing.

**Comment by majewsky** [comment]
OK, thanks for explaining. I'll follow up with the i3status-rust team to see if they can use the DBus interface when available.

**Comment by boucman** [comment]
@majewsky I patched py3status to support that, if you want inspiration... see https://github.com/ultrabug/py3status/pull/1870
