### ISSUE TITLE
system-wide OnFailure

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14462]
**Is your feature request related to a problem? Please describe.**
Currently, there is no system-wide OnFailure option. We do have OnFailure per unit but that is definitely not adequate.

As a result, people have tried to fake-implement such a feature by using timers, log parsers and all sorts of hacks. These are partially effective and not very efficient (polling for logs, re-running over a timer thus delaying an error report due to the timer waiting to timeout, so on and so forth).

Others just manually edit individual unit files and add OnFailure by hand or by script.

Essentially, we are missing a system-wide OnFailure that executes when systemd enters a degraded state and reports that XYZ service (or unit, or whatever) entered a non-active state.

**Describe the solution you'd like**
Implement an OnFailure option in system.conf that covers everything.

Once systemd goes into degraded state due to a service failure, the OnFailure executes and performs an action, like sending an email, or syslog/journal entry, or instant message alert.

**Describe alternatives you've considered**
A cron job that executes once per minute, which runs "systemctl status" and checks:
- the "State:" output for a result not matching "running"
- the "Failed:" output for a result not matching "0 units"

The cron job by default sends an email when the output of the script is not empty, thus any reports are sent to the admin without any further setup.

Thank you.

**Comment by poettering** [comment]
I am pretty sure it's not a good idea to use this, but you can do so nowadays, since v244 via dropins into <unit-type>.d/ directories. See NEWS.
