### ISSUE TITLE
Please provide a ConditionCPUID or similar

### ISSUE THREAD

**Issue by joshtriplett** [systemd/systemd#14479]
I'd love to have a Condition that would allow only running a unit if the CPU does (or doesn't) have a specific capability. For instance, I'd like to conditionally disable systemd-random-seed.service if and only if running on a CPU with rdrand. (That would make it easier to improve boot performance without having to create a specialized disk image.)

**Comment by GiedriusS** [comment]
Should be included in v248. I think we can close this fixed.
