### ISSUE TITLE
Since 25de7aa7 TEST octal mask acts as exact match not a mask

### ISSUE THREAD

**Issue by kergon** [systemd/systemd#14473]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Fedora Rawhide

**Expected behaviour you didn't see**
 > Prior to 25de7aa7 "udev: modernize udev-rules.c" TEST{octal_mask}== behaved as a partial mask
  match = ((statbuf.st_mode & cur->key.mode) > 0);

**Unexpected behaviour you saw**
 > Afterwards it became 
  match = (((statbuf.st_mode ^ mode) & 07777) == 0);

This appears to have broken a udev rules file of mine which tested for executable permission using {111}.

I can't find documentation relating to this change - was it an accident and please could it be reverted?  Or even better I suppose, extend (and document) the syntax to support different types of masking.

**Steps to reproduce the problem**

**Comment by yuwata** [comment]
Thank you for the report. PR #14503 should fix the issue. If possible, please test the PR.
