### ISSUE TITLE
Allow logind session type to change

### ISSUE THREAD

**Issue by mmonaco** [systemd/systemd#14489]
There is at least one workflow where a session's type might change. I login (usually tty1) using `agetty` -> `login` -> `pam_systemd.so`. So the session type is `Type=tty` and `XDG_SESSION_TYPE=tty`.

I then set `XDG_SESSION_TYPE=wayland` and start a Wayland compositor (although starting X here would be similar). But I have no way of changing the session type in `logind`. There are projects in the wild which look at `XDG_SESSION_TYPE` for wayland vs x11; I'm not sure about `org.freedesktop.login1` or `sd_session_get_type(3)`.

Is it reasonable to want a way to change this in `logind`? Something like `loginctl update-session Type=wayland`.

**Comment by poettering** [comment]
Your wayland compositor should just allocate a new session. Only then we can be sure things are cleared up properly when it exits again.

**Comment by mmonaco** [comment]
Maybe, but doesn't that imply a separate login? I don't think most (any)? x window managers / wayland compositors do this.

> **CreateSession()** and **ReleaseSession()** may be used to open or close login sessions. These calls should never be invoked directly by clients. Creating/closing sessions is exclusively the job of PAM and its pam_systemd module.

I think it's fine if the conclusion is something like "the usecase is valid but not worth the implementation work on logind so just use a display manager or live with the inconsistency"

**Comment by boucman** [comment]
basically this is the "startx" use-case. startx is used directly from an already existing session.

@mmonaco summary is good : how do we handle session-type changes from the shell, and is it worth doing ?

I'm pretty sure most WM would be OK to invoke some sort of dbus/cli/other command to tell logind that the session is changin/stacking a new session-type, but direction is needed...

**Comment by poettering** [comment]
The assumption in logind is that display managers are used, such as gdm. "Upgrading" of sessions is never what logind was designed for, it's not a concept that exists in logind. Thus startx was always only half-way supported: if you want idle mgmt you couldn't use startx.

But this "sway" thing, how does it get access to its DRM and input devices? Through logind? If so it really should have figured out that registering a session means being privileged.

**Comment by poettering** [comment]
(the problem with changing session types temporarily is that there needs to be some robustness to automatically change it back when "startx" dies, so that the session doesn't stay in manual idle-detection mode and thus stuck in idle or in non-idle mode for ever, and insteads reverts to tty atime watching again)

**Comment by progandy** [comment]
> But this "sway" thing, how does it get access to its DRM and input devices? Through logind? If so it really should have figured out that registering a session means being privileged.

As far as I know, sway calls ```TakeControl``` for the session. Since the shell doesn't try to do that, the attempt succeeds and sway becomes the session controller. 

Now that I think about it, that may be a somewhat sane way to "upgrade" a session. It could be set when a controller takes over and is reset when control is released.

Personally, I am perfectly fine with using an ncurses-like display manager like ```ly```, though.

**Comment by poettering** [comment]
hmm, yeah, that might make sense: as long as control is taken for a session we could bump the session type to graphical somehow, and revert to the original afterwards. Happy to review a patch for that ;-)

**Comment by boucman** [comment]
pinging @ddevault just in case... so he is aware that sway and idle are being discussed here...

**Comment by electrickite** [comment]
@poettering  I'm considering taking a stab at this one. I can see a couple of approaches:

  1. Add an argument to TakeControl that allows the caller to set the session type. This seems cleanest to me, but would alter the method signature and break backwards compatibility.
  2. Add another D-Bus method to Session, something like UpgradeType, that would both take control of the session and change the type. This would not break compatibility, but clutters the API.

Do either of those seem reasonable or is there a better way to approach this?

**Comment by electrickite** [comment]
PR #14925 would add a SetType method that requires control of the session. I believe that would resolve this issue.
