### ISSUE TITLE
resolvectl query / systemd-resolved errors on emoji IDN/punycode (sub)domains

### ISSUE THREAD

**Issue by raspi** [systemd/systemd#14483]
**systemd version the issue has been seen with**
> 242.153-2

**Used distribution**
 > Manjaro

**Expected behaviour you didn't see**
 > DNS record succesfully queried and resolved

**Unexpected behaviour you saw**
 > Error

**Steps to reproduce the problem**
1. `resolvectl query "xn--s28h.raspi.fi"` or `systemd-resolve "xn--s28h.raspi.fi"`
1. `xn--s28h.raspi.fi: resolve call failed: Invalid argument`

or:
1. Try to go to https://😎.raspi.fi/

I can go to https://😎.raspi.fi/ with my phone but on GNU/Linux `systemd-resolve` doesn't resolve. See also: https://en.wikipedia.org/wiki/Emoji_domain

**Comment by yuwata** [comment]
https://gitlab.com/libidn/libidn2/issues/25
