### ISSUE TITLE
Cannot attach to tmux after closing ssh session

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14497]
**systemd version the issue has been seen with**

```
$ systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Used distribution**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic
```

**Expected behaviour you didn't see**

Able to reconnect to tmux after closing ssh session.

**Unexpected behaviour you saw**

When reconnecting to my server, `tmux attach` doesn't work.

```
$ tmux attach
no sessions
```

**Steps to reproduce the problem**

```bash
$ ssh server
# on server
$ tmux
# Detatch from tmux
# Hit `Control-b` and then `:` and enter
: detach
# Now back on server
$ exit
# Back on client
$ ssh server
# Back on server
$ tmux attach
no sessions
```

**What was tried**

_rebooting after every step and retesting did **not** help_

Set KillUserProcesses=no
```
$ grep Kill /etc/systemd/logind.conf
KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
```

Enable lingering on the user from root
```
$ sudo loginctl enable-linger ubuntu
```

Enable lingering without root
```
$ loginctl enable-linger
```

After relogging and checking the user session, the test still failed
```
$ loginctl show-user ubuntu
UID=1000
GID=1000
Name=ubuntu
Timestamp=Mon 2020-01-06 19:23:32 CET
TimestampMonotonic=1655270008590
RuntimePath=/run/user/1000
Service=user@1000.service
Slice=user-1000.slice
Display=1127
State=active
Sessions=1127
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
Linger=yes
```

-- no reboots from this point forward---

```
$ systemd-run --scope --user --uid ubuntu --gid ubuntu tmux
Job for run-r172e61e2d88947799ce7fdfb879449bd.scope failed.
See "systemctl status run-r172e61e2d88947799ce7fdfb879449bd.scope" and "journalctl -xe" for details.
$ $ journalctl -xe | tail -n 12
Jan 06 20:32:04 server polkitd(authority=local)[1057]: Registered Authentication Agent for unix-process:8312:165938186 (system bus name :1.628 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jan 06 20:32:04 server systemd[17230]: run-r172e61e2d88947799ce7fdfb879449bd.scope: Failed to add PIDs to scope's control group: Permission denied
Jan 06 20:32:04 server systemd[17230]: run-r172e61e2d88947799ce7fdfb879449bd.scope: Failed with result 'resources'.
Jan 06 20:32:04 server polkitd(authority=local)[1057]: Unregistered Authentication Agent for unix-process:8312:165938186 (system bus name :1.628, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 06 20:32:04 server systemd[17230]: Failed to start /usr/bin/tmux.
-- Subject: Unit UNIT has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit UNIT has failed.
-- 
-- The result is RESULT.
```

Same result for `systemd-run --scope --user tmux`.

Another without `--scope`
```
$ systemd-run --user tmux
Running as unit: run-r6d5fcc15f8254ac2b0a8e0bad5c71475.service
$ journalctl -xe | tail -n 4
Jan 06 20:35:40 server polkitd(authority=local)[1057]: Unregistered Authentication Agent for unix-process:9543:165959789 (system bus name :1.629, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 06 20:35:40 server tmux[9548]: open terminal failed: not a terminal
Jan 06 20:35:40 server systemd[17230]: run-r6d5fcc15f8254ac2b0a8e0bad5c71475.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 20:35:40 server systemd[17230]: run-r6d5fcc15f8254ac2b0a8e0bad5c71475.service: Failed with result 'exit-code'.
```

With `--pty` since it couldn't find a terminal

```
$ systemd-run --pty --user tmux
Failed to create bus connection: No such file or directory
```

Trying with sudo doesn't help either.

```
$ sudo systemd-run --scope --user --uid ubuntu --gid ubuntu tmux
Failed to create bus connection: No such file or directory
```

No, I'm not running the graphical target, since this is a server (used to be a desktop, but it serves another function now).

```
$ systemctl get-default 
multi-user.target
```

**Hail maries**

 - nohup
 - [daemonize](https://linux.die.net/man/1/daemonize)

Running anything with those, disconnecting and reconnecting doesn't work.

------------------------------

Should more information be required, I'd be happy to provide it. I just want to be able to run **anything** for longer than a session :cry: 

I had to resort to running things in `cron` since it's easier than writing a whole new user service.

**Comment by poettering** [comment]
As the submission form should have made sufficiently clear: we only track issues in the two most recently systemd versions here. For everything older: ping downstream.

Sorry. But this stuff has changed quite a bit since then. Please retry with something newer or ping downstream. Thank you for understanding.

(We try to make this very clear when submitting an issue to keep frustartion low, btw)

**Comment by LoveIsGrief** [comment]
@poettering How to find out which versions are the 2 last ones? https://freedesktop.org/wiki/Software/systemd/ doesn't mention it and I'm not sure where to look. The tags?  
It'd be great if the issue template contained instructions or links on how to find them.

**Comment by mrc0mmand** [comment]
@LoveIsGrief you can find them under the 'Releases' section: https://github.com/systemd/systemd/releases

Also, the *Download* link on the freedesktop wiki points to *Releases* as well.

**Comment by sneakin** [comment]
Having this issue with 246. Gentoo is refusing to update atm, so may not get a 248 report as my session keeps getting killed trying to appease emerge.
