### ISSUE TITLE
systemd-boot ignores VERSION from osrel of unifed images

### ISSUE THREAD

**Issue by Prototik** [systemd/systemd#14493]
See the following snippet:

https://github.com/systemd/systemd/blob/14b6e6b6f31afdec9a4e8f322226def30815e8fe/src/boot/efi/boot.c#L1961-L1971

It reads `VERSION_ID` both times, but writes it to different variables. Actually the second branch is dead code and it should check for `VERSION` field of osrel.

**Comment by poettering** [comment]
Fix waiting in #14506
