### ISSUE TITLE
systemd-run: imply DynamicUser when using --uid

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14507]
**Is your feature request related to a problem? Please describe.**

I'm in a situation where I start a systemd-nspawn container and mount some directories from the current user into it. I then want to run commands as the same user in the container. Currently, I create the user manually in the container but systemd-run creating the user dynamically when passing `--uid` would be much simpler. This can be done by setting the `DynamicUser` property but implying `DynamicUser` when `--uid` is used would be less verbose.

**Describe the solution you'd like**

Have systemd-run's  `--uid` option imply `-p DynamicUser=yes`.

**Describe alternatives you've considered**

The alternative is specifying `-p DynamicUser=yes` manually which is more verbose.

**Comment by DaanDeMeyer** [comment]
Looking back, this doesn't seem like a very good idea.
