### ISSUE TITLE
systemd-udevd: 100% CPU usage when the RUN program closes fds

### ISSUE THREAD

**Issue by liskin** [systemd/systemd#14514]
**systemd version the issue has been seen with**
> 244

**Used distribution**
> Debian testing

**Expected behaviour you didn't see**
> no systemd-udevd at the top of top(1)

**Unexpected behaviour you saw**
> systemd-udevd consuming a lot of CPU when processing certain rules (more on that later)

**Steps to reproduce the problem**

The smallest reproducer I managed to get is this one:

1. `ACTION=="change", SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", RUN+="/bin/sh -c 'exec >/dev/null 2>/dev/null; exec sleep 10'"`
2. `udevadm trigger /sys/bus/usb/devices/usb1`
3. now systemd-udevd eats one CPU for 10 seconds

stracing it shows that it's stuck in a loop doing `epoll_wait(15, [{EPOLLHUP, {u32=…, u64=…}}, {EPOLLHUP, {u32=…, u64=…}}], 5, 0) = 2`, which suggests that the problem is that closed file descriptors are not being removed from epoll.

A workaround is to surround the RUN with an additional /bin/sh -c '…' which keeps the fds open (but beware that if /bin/sh is bash, it will automatically perform an exec if there's just one command).

**Comment by poettering** [comment]
My educated guess is that 9f537ae3100f8372579daea53c24fff917cc3257 already fixes that. You are not running a version with that commit included, are you?

**Comment by yuwata** [comment]
I cannot reproduce the issue with the current git master, and it is reproducible by reverting 9f537ae3100f8372579daea53c24fff917cc3257. Hence, this is already fixed.

**Comment by yuwata** [comment]
@keszybz Any chance to backport 9f537ae3100f8372579daea53c24fff917cc3257 to the stable repo?

**Comment by liskin** [comment]
Thank you guys and sorry for the noise. I'll try to grab a fresh build and reproduce in a VM next time. :-)
