### ISSUE TITLE
systemd leaks a unix domain socket file handle to kmod

### ISSUE THREAD

**Issue by etbe** [systemd/systemd#1451]
The following lines from the output of dmesg on a SE Linux system show that systemd (init_t) is leaking socket file handle 7748 when spawning kmod.  It should either close the file handle before calling exec() or set FD_CLOEXEC.

In this case it's a minor bug but in other situations such bugs can have security implications 
so this should be fixed. This occurs in version 215 and version 226.

I can give you root access to a virtual machine demonstrating this problem if it's of use to you.

[    2.809497] audit: type=1400 audit(1443503644.476:4): avc:  denied  { read 
write } for  pid=151 comm="kmod" path="socket:[7748]" dev="sockfs" ino=7748 
scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:init_t:s0 
tclass=unix_stream_socket permissive=0
[    2.809564] audit: type=1400 audit(1443503644.476:4): avc:  denied  { read 
write } for  pid=151 comm="kmod" path="socket:[7748]" dev="sockfs" ino=7748 
scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:init_t:s0 
tclass=unix_stream_socket permissive=0

Here's the Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800417

**Comment by poettering** [comment]
Which invocation of kmod is that? Which service? Is that from `kmod-static-nodes.service`? That's the only place where we invoke the kmod binary from upstream. Or is this an invocation added downstream?

Note that we pass an AF_UNIX/SOCK_STREAM socket as stdout/stderr/stdin to invoked processes. Maybe that's the one?

**Comment by poettering** [comment]
I am pretty sure this is the stdin/stdout/stderr socket. Will close hence. If it turns out not to be that socket, feel free to reopen.
