### ISSUE TITLE
systemd-networkd-wait-online: Wait for specific operational state

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14529]
**Is your feature request related to a problem? Please describe.**

I'm currently using systemd-networkd-wait-online in some testing scripts to wait until network interfaces come online and it's been working extremely well. Unfortunately, I sometimes have to do the reverse as well (wait for network interfaces to go down). With systemd-networkd-wait-online's current interface, that's not possible since the specified operational state is always a minimum level.

**Describe the solution you'd like**

Add an option to have systemd-networkd-wait-online treat operational states as fixed states instead of minimum states. that way I can specify the exact operational state I expect the network interface to be in which allows me to wait for that specific state, disregarding all higher states. This would also improve the tests that wait until an interface is online since we'd notice if an operational state changes to a higher level than the accepted one.

There's also the option to implement this differently by adding some prefix characters to operational states that cause them to be treated differently. For example, prefixing an operational state with '!' could cause it to be treated as a fixed operational state and prefixing with '$' could be used to treat an operational state to be treated as a maximum operational state. This might be too much flexibility though.

**Describe alternatives you've considered**

The alternative is a rather ugly shell command that repeats the check using iproute with sleep inbetween to wait until the interface goes down.

I can implement this if it is accepted, one point of discussion would be the name of the option. `--fixed-operstate` would work but maybe we can come up with a better name.

**Comment by yuwata** [comment]
How about `-i INTERFACE[:MIN_STATE[:MAX_STATE]]`?

**Comment by DaanDeMeyer** [comment]
That seems better than the prefix approach as it's more in line with the rest of systemd's options that tend to use ':' as well and doesn't require adding a new option, only extending the current ones in a completely backwards-compatible way.
