### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [systemd/systemd#14531]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:

* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:

* For github and gitlab hosted projects, Weblate open pull request. For other git hosting, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by keszybz** [comment]
Hi,
sorry for the slow reply.

>     * [mandatory] which branch is your development branch?

`master`

>     * [mandatory] have you merged latest translation from Zanata and locked the project?

No. I looked at https://fedora.zanata.org/dashboard/projects?dswid=2687 but I wasn't able to figure out if any translations is there to be merged. It says  "4 months ago Last translated by Andika Triwidada" but I don't know how to see any details. But I don't think there's been any recent activity. The last translation to mention zanata was submitted in 2018 (9e97a15b5d66797c6d3f523ea40ac00c7e816e93). So I think it's safe to assume that there are no outstanding translations there.
 
>     * [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]

We usually just made the po-file update as part of updating the translation. This makes sense for us because .pot changes much more often than the individual translation files, so we get relatively little "noise" in the git log from translations this way.

>     * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

LGPL-2.1+

>     * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
> 
>     * [optional] do you need us to activate any specific checks? (this is a setting per component [3])
> 
>     * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No need, I think.

Let us know if we need to take some action right now.

**Comment by Jibec** [comment]
Thanks for your answer.

Action needed: push your pot file in your repository.

> We usually just made the po-file update as part of updating the translation. This makes sense for us because .pot changes much more often than the individual translation files, so we get relatively little "noise" in the git log from translations this way.

It is easier for translator community to let Weblate handle pot updates.

* Translators can get a notification when new strings are available.
* Translation progress in translation platform is made accurate
* it allows translators to add a new language in Weblate (reducing complexity to contribute)

Weblate will open a Pull Request and reuse it as long as it is open.
I will configure a git-squash per author, reducing the number of update commits.
I can also configure weblate to strip line numbers in po files, to reduce even more diff sizes in updates.
Also, Weblate can take care of updating your LINGUAS file when a new language is added.

In a regular pace, assuming you'll merge translation for each release, you'll get one Weblate commit for po updates, and one commit per translation.

First pull request will be big as it will update all po files and eventually strip line numbers if you wish to do so.

Weblate will have its own repository with po files inside, if you do changes on po file, you'll have git conflicts.
You normally won't have to do this has anyone can upload it to Weblate.
