### ISSUE TITLE
udev: create disk/by-id/ symlinks for nvme devices

### ISSUE THREAD

**Issue by Bronek** [systemd/systemd#1453]
I need NVMe device symlink under `disk/by-id/` , but there does not seem to be matching rule in `60-persistent-storage.rules`, thus no symlinks are created (under systemd 226). I found there was some discussion on the subject at http://lists.freedesktop.org/archives/systemd-devel/2015-May/031967.html , but it does not seem to have led anywhere. What are the current plans for this functionality?

Is systemd going to use Per's utility `nvme_id` (as proposed in above link), or is this code going to be built-in (given the right patch), or are we just going to get by using `disk/by-id/nvme-$env{ID_SCSI_SERIAL}` or alternatively `disk/by-id/nvme-$ENV{ID_MODEL}_$ENV{ID_SCSI_SERIAL}`, or no support for the time being ?

FWIW I'd be happy to help testing necessary patches, or even give it a try writing one.

**Comment by poettering** [comment]
I think consensus was that the kernel should fix it's APIs to expose the necessary bits via sysfs attributes, so that no "nvme_id" tool is necessary, and also no SCSI is involved. If the nvme stuff would expose identity information as normal sysfs attributes we could just add a generic udev rule and be done with it. 

Or in other words, this needs to be fixed in the kernel.

@kaysievers, please comment!

**Comment by Bronek** [comment]
FWIW, serial number of my nvme device is available under /sys/devices:

```
root@gdansk /sys/devices # find /sys/devices -name nvme0n1
/sys/devices/pci0000:80/0000:80:03.0/0000:83:00.0/block/nvme0n1
root@gdansk /sys/devices # lspci -v -s 0000:83:00.0 | grep "Device Serial Number"
        Capabilities: [270] Device Serial Number 55-cd-2e-40-4b-e0-42-7d
```

I guess that does not help much?

**Comment by kaysievers** [comment]
MMC calls similar attributes in sysfs "name" and "serial".

The NVMe spec calls the values Serial Number (SN), EEE OUI Identifier
(IEEE), Model Number (MN), Firmware Revision (FR). Something like
"serial", "vendor", "model", "revision" sounds fine, but in the end
the attribute name does not really matter, as long as it does not
clash with attribute names used by the block subsystem.

**Comment by poettering** [comment]
Anyway, closing, as this really needs to be fixed in the kernel.

**Comment by keithbusch** [comment]
Just FYI, kernel 4.5 added uuid attributes to the sysfs block path for nvme drives.

**Comment by jejb** [comment]
Just a note that this still fails, even with 4.5-rc1: systemd-udev doesn't see the serial attribute.  These are the rules I added to persistent-storage to get it to show up

```
# nvme
SUBSYSTEMS=="nvme", ATTRS{serial}=="?*", PROGRAM="/usr/bin/echo $attr{serial}", ENV{ID_SERIAL}="%c"
KERNEL=="nvme[0-9]*", ENV{DEVTYPE}=="disk", ENV{ID_SERIAL}=="?*", SYMLINK+="disk/by-id/nvme-$env{ID_SERIAL}"
KERNEL=="nvme[0-9]*", ENV{DEVTYPE}=="partition", ENV{ID_SERIAL}=="?*", SYMLINK+="disk/by-id/nvme-$env{ID_SERIAL}-part%n"
```

**Comment by jejb** [comment]
Hm, apparently github is a bit useless for cut and paste.  anyway +keithbusch: the reason for the echo is to strip the leading whitespace in the attribute.   Should this attribute have leading whitespace?

**Comment by keithbusch** [comment]
Thanks for providing a rule.

The attribute should not have a leading white space. I don't know where that is coming from, but will fix it as soon as I can to it.

**Comment by kabbey** [comment]
Would this rule work on Centos 7.1?

Is there an alternate file for the nvme rule?  
The rule file state it will be over written on update.  Do we need to write again after each update?

I'd like to use the persistent path for zfs on linux.

**Comment by poettering** [comment]
@jejb btw, please file a PR if you want those rules shipped along the usual udev rules. Thanks

**Comment by poettering** [comment]
(involving "echo" in the rules looks wrong though)
