### ISSUE TITLE
Give comprehensive names to start / stop jobs

### ISSUE THREAD

**Issue by Markus-N** [systemd/systemd#14544]
**The problem**
I'm regularly encountering "A stop job is running for Session 1 of user markus" during shutdown. And I'm not the only one: There are lots of people asking what to do about it on LinuxQuestions, AskUbuntu, SuperUser, reddit, ...
Rarely, there is also a message "A start job is running ..." during boot.

**The solution I'd like**
I think it would be helpful to have a more complete message on the console when this happens, e.g. type and name of the unit the job tries to start or stop, or ( if the job is not unit related ) the name of the process to kill, the filesystem to umount, ...

**Alternatives (I don't like)**
One could argue "it's all in the journal", but searching for the cause in the journal is cumbersome and sometimes even impossible without deeper knowledge. You can't find anything if you don't know what to look for. And why make it complicated when it can be easy ?

**Comment by Werkov** [comment]
> e.g. type and name of the unit the job tries to start or stop

The message already says it, it's *stop*  job of "Session 1 of user markus" (description of the unit). Would it really be more useful to the user w/out deeper knowledge if the message was: "A stop job is running for session-3.scope"?
There are no unitless jobs. What would you propose, @Markus-N?

**Comment by Markus-N** [comment]
In my particular case, it was x11vnc that could not be closed because it was still busy, i.e. a client was still connected. It took me a whole lot of time to figure that out. So a "comprehensive name" would be something that contains "x11vnc". That's what I meant with "the process to kill".
You say "Session 1" is technically correct. Does that mean that x11vnc is kind of wrapped by the DE session and systemd cannot figure out the process name ? At least, X11 was not showing anymore when the "stop job" message appeared on the local screen and so I thought it would be an individual process to kill.

About "unitless jobs":
Probably I got things wrong. One example for what I understand as "unitless jobs" are mount points that are specified in /etc/fstab but have no unit files (somewhere I've read that you could replace fstab with .mount unit files). Maybe, systemd implicitly creates units for those internally. But from my user perspective, a unit that has no unit file is not a unit I can handle and therefore it's start/stop jobs _appear_ unitless to me.

**Comment by yennor** [comment]
I've got the same problem. I was bothered by one of those stob jobs for years.
The reason was not easy to find in the journal since there is no mentioning of stop job at all. I only found out what to look for since some (a lot) of people asked exactly the same in some forums. In my case it was keepassxc.
So showing a message and explaining which process is the reason, would help a lot.
Additionally it would be great to have shown something like "to abort waiting press a".
Usually you just don't want to wait those 90 seconds.

**Comment by keszybz** [comment]
The message you're seeing ( "Session 1 of user markus") is very generic, and systemd doesn't really know what the scope is for. Earlier, it was told by some other service (most likely either the display manager or sshd) to open a session and put some PIDs in it.

But I think we *could* try to improve the UX here. A few ideas:
- if there's just a few processes left in the scope, systemd could include their comms in the message printed to screen:
    "A stop job is running for Session 1 of user markus (3 processes remaining: keepassxc, x11vnc, foobar).
- when a delay like this happens, log more information to the journal. The user could then use this to figure out what is causing the problem. In fact, I think we should always log an informative line the first time we show the "cylon eye prompt" with the reason for it. Right now a delay is very prominently shown in the console messages, but there is very little information in the journal.

**Comment by Markus-N** [comment]
@yennor 
I like your idea "to abort waiting press a" very much.

**Comment by dtardon** [comment]
I think https://github.com/systemd/systemd/commit/3889fc6fc347f0e12070f7b873d065508c8df816 fulfills this request, doesn't it?

**Comment by Markus-N** [comment]
I cannot test it because my test case appears to be gone. Currently, x11vnc closes normally on shutdown even when there is still a client connected.

**Comment by keszybz** [comment]
Yes, this RFE has been implemented.
