### ISSUE TITLE
machinectl bind: Failed to mount: Invalid argument

### ISSUE THREAD

**Issue by lotan** [systemd/systemd#14559]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > machinectl bind should mount bind a host path

**Unexpected behaviour you saw**
 > machinectl bind results in error "Failed to mount: Invalid argument"

**Steps to reproduce the problem**
Use machinectl bind in the documented way, observe error message.

Looking at the source code, I saw that a dbus interface is used.
Using that dbus interface using dbus-send, resulted in the same error.

Previous systemd versions worked with the same call. However, I don't use machinectl bind very often, so I can't pinpoint the exact version change in which the functionality stopped working.

Additional information: My container has CAP_SYS_ADMIN.

**Comment by poettering** [comment]
What's the precise "systemd-nspawn" command line used for your container? And what is the .nspawn file for it (if there is one)?

**Comment by lotan** [comment]
`/usr/bin/systemd-nspawn --quiet --keep-unit --boot --network-macvlan=enp4s0.1 --machine=%i --capability=CAP_NET_RAW --capability=CAP_NET_ADMIN --capability=CAP_SYS_ADMIN --bind=/var/cache/pacman/pkg --bind=/tmp/.X11-unix --bind=/var/lib/machines/persistent:/mnt/persistent --ephemeral`

There's no .nspawn file for this container.

Testing the issue, I tried with a non-ephemeral container as well: The same issue happened.
