### ISSUE TITLE
Unequal framing of text in important authentication dialog

### ISSUE THREAD

**Issue by enkore** [systemd/systemd#1455]
When systemctl prompts for authentication (this happens for example if one wants to suspend a machine remotely with active sessions) the following text shows up:

```
$ systemctl suspend
==== AUTHENTICATING FOR org.freedesktop.login1.suspend ===
Authentication is required for suspending the system.
Authenticating as: <redacted>
Password:
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
```

Note that on the left side there are four equal signs (====), but on the right only three (===) are printed. I can't seem to find where this output is actually generated (and `====` etc. is not part of the source code, it is only mentioned in the man pages), so I can't prepare a patch for this formatting anomaly.

**Comment by poettering** [comment]
That's implemented in PolicyKit's `pkttyagent` tool, and not in systemd.

**Comment by enkore** [comment]
Fixed in polkit ( https://bugs.freedesktop.org/show_bug.cgi?id=92276 )
