### ISSUE TITLE
Handle masked .mount units more gracefully.

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#14550]
**systemd version the issue has been seen with**

v244

**Used distribution**
 
Debian sid
See relevant downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948710
and the discussion at 
https://lists.freedesktop.org/archives/systemd-devel/2020-January/043922.html https://lists.freedesktop.org/archives/systemd-devel/2020-January/043924.html

gparted masks .mount units during runtime to prevent automounting.
With recent versions of systemd, this now triggers a failure for every service that has a dependency on `_.mount` (basically everything).

While masking .mount units is a bad idea, systemd should handle this case more gracefully.

**Comment by poettering** [comment]
Fix waiting in #14596.
