### ISSUE TITLE
KillMode=mixed can leave left over processes when used with ExecStopPost

### ISSUE THREAD

**Issue by c-ryan747** [systemd/systemd#14566]
**systemd version the issue has been seen with**
v243

**Used distribution**
centos

**Expected behaviour you didn't see**
The [documentation](https://www.freedesktop.org/software/systemd/man/systemd.kill.html) for `KillMode=mixed` says that:
   >If set to mixed, the SIGTERM signal (see below) is sent to the main process while the subsequent SIGKILL signal (see below) is sent to all remaining processes of the unit's control group.
...
If processes still remain after the main process of a unit has exited or the delay configured via the TimeoutStopSec= has passed, the termination request is repeated with the SIGKILL signal or the signal specified via FinalKillSignal= (unless this is disabled via the SendSIGKILL= option). See kill(2) for more information.

This implies that with `KillMode=mixed` once the main process has died or timed out, any remaining processes in the cgroup will be killed with `SIGKILL`.

**Unexpected behaviour you saw**
`KillMode=mixed` works as expected except when both:
- The service has some `ExecStopPost` commands set
- The main process exits within the timeout

In this case the remaining processes in the cgroup never get killed, causing them to leak beyond the end of the service.

If either of the above conditions aren't met then systemd exhibits the right behaviour and the unit ends with no processes left in the cgroup.

**Steps to reproduce the problem**
`/etc/systemd/system/test.service`
```
[Install]
WantedBy=multi-user.target

[Service]
ExecStart=/usr/local/bin/python3 /tmp/test.py
ExecStopPost=/bin/true

KillMode=mixed
```
`/tmp/test.py`
```
import asyncio
import signal
import time
import os


async def main():
    proc = await asyncio.create_subprocess_shell('sleep 200')
    await proc.communicate()


def exit_after_sleep(signum, frame):
    time.sleep(3)
    os._exit(0)

signal.signal(signal.SIGTERM, exit_after_sleep)


asyncio.run(main())
```
Output
```
$ sudo systemctl start test.service
$ sudo systemctl status test.service
● test.service
   Loaded: loaded (/etc/systemd/system/test.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-01-14 03:23:23 PST; 2s ago
 Main PID: 1796133 (python3)
       IO: 0B read, 0B written
    Tasks: 2
   Memory: 15.1M
      CPU: 86ms
   CGroup: /system.slice/test.service
           ├─1796133 /usr/local/bin/python3 /tmp/test.py
           └─1796237 sleep 200

Jan 14 03:23:23 devvm5241.lla1.facebook.com systemd[1]: Started test.service.
$ sudo systemctl stop test.service
$ ps -p 1796237
    PID TTY          TIME CMD
1796237 ?        00:00:00 sleep
```

**Potential fix**
Looking through the code I think it's a problem with`service_sigchld_event`. When the service is in state `SERVICE_STOP_SIGTERM` it should call something like:
```
service_enter_signal(s, SERVICE_FINAL_SIGTERM, SERVICE_SUCCESS)
``` 
rather than
```
service_enter_stop_post(s, f);
```
https://github.com/systemd/systemd/blob/master/src/core/service.c#L3485

**Comment by michelbitar-99** [comment]
I observed the following as well with KillMode=control-group in systemd 229

- SIGTERM is sent to all processes
- SIGKILL is only sent to parent process
