### ISSUE TITLE
StandardInput=file: doesn't work

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#14560]
**systemd version the issue has been seen with**
```
systemd 244 (244-3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
Debian Sid

**Expected behaviour you didn't see**
`StandardInput=file:…` does what it says on the tin.

**Unexpected behaviour you saw**
When `StandardInput=file:…` is used, the service fails on startup with `code=exited, status=1/FAILURE`, and no other message. That's it. It doesn't seem to matter what other options are used. It looks like the `ExecStart` process is not even spawned.

**Steps to reproduce the problem**

`test-standardinput-file.service`:
```
[Service]
StandardInput=file:/etc/hostname
ExecStart=/bin/cat
```

```
# systemctl start test-standardinput-file.service
# systemctl status test-standardinput-file.service
● test-standardinput-file.service
     Loaded: loaded (/etc/systemd/system/test-standardinput-file.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-01-13 19:05:40 GMT; 4s ago
    Process: 145622 ExecStart=/bin/cat (code=exited, status=1/FAILURE)
   Main PID: 145622 (code=exited, status=1/FAILURE)

Jan 13 19:05:40 systemd[1]: Started test-standardinput-file.service.
Jan 13 19:05:40 systemd[1]: test-standardinput-file.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 19:05:40 systemd[1]: test-standardinput-file.service: Failed with result 'exit-code'.
```

**Comment by anitazha** [comment]
Is your `StandardOutput=` set to inherit when you use `StandardInput=file:<some path>`? It seems to change to `inherit` when I use your example. Adding `StandardOutput=tty` (as an example) appears to do what you expect. I would need to look harder to see if this is intentional and update documentation or code.

**Comment by dechamps** [comment]
@anitazha Good catch.

Without `StandardInput=`:

```
# systemctl show test-standardinput-file.service | grep Standard
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
```

With `StandardInput=file:/etc/hostname`:

```
# systemctl show test-standardinput-file.service | grep Standard
StandardInput=file
StandardInputData=
StandardOutput=inherit
StandardError=inherit
```

If I counteract this phenomenon by explicitly adding `StandardOutput=journal` to the unit file, it works! So I guess we have a workaround at least.

Unless I missed it, that behaviour is not mentioned in the documentation. This `StandardOutput=inherit` implicit change looks like a bug.

**Comment by poettering** [comment]
yeah, this looks like a bug

**Comment by poettering** [comment]
Fix pending in #14595

**Comment by cpuguy83** [comment]
Sorry to resurrect this old thread, details on this is hard to come by and figured I'd try pinging here before code spelunking in an unfamiliar codebase.

For me systemd is refusing to even set the property for me when using "file:<path>" in a transient service.
Is this expected?

**Comment by anitazha** [comment]
@cpuguy83 could you open a new issue with the systemd version and a repro? It should work afaik
