### ISSUE TITLE
[Question] How to know systemd user session already started?

### ISSUE THREAD

**Issue by kevinhwang91** [systemd/systemd#14568]
[cmus](https://github.com/cmus/cmus) using `sd_bus_process` to process mpris request in the loop UI thread, this is the snippet code:
```c
void mpris_process(void)
{
    if (bus) {
        while (sd_bus_process(bus, NULL) > 0)
        ;
    }
}
```
 I run cmus in tmux server and logout(Switch xserver because of using eGPU) and then cmus 
occupy 100% CPU. I find out `sd_bus_process` return -ECONNRESET when I logout and then hang the UI because of invoking `sd_bus_process` again in loop UI thread.

Maybe I could uninstall mpris bus service according to the last return code -ECONNRESET and reinstall the service again. But I don't know when the user login and when to notify cmus to initiate mpris again in the loop UI thread.

Can someone help me?

**Comment by poettering** [comment]
This is not a support forum, but a bug and issue tracker. If you need support, please contact the systemd mailing list or other forums more appropriate to your project or distro instead.

To keep frustration low we actually try to make this very clear in the issue submission form.
