### ISSUE TITLE
Journald messages being displayed out of order

### ISSUE THREAD

**Issue by volfco** [systemd/systemd#14574]
**systemd version the issue has been seen with**
> systemd 244 (244.1-1-arch)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 Running the script in the service file below in a bash shell, I expect the following output:
```
stdout
stderr
stdout again
```

**Unexpected behaviour you saw**
Viewing the journald output using `journalctl -e -u script`, I get the following output. 
 ```
Jan 14 18:45:39 blackwolf python2[553748]: stderr
Jan 14 18:45:49 blackwolf python2[553748]: stdout
Jan 14 18:45:49 blackwolf python2[553748]: stdout again
```
The messages are out of order. stderr shows up first.

**Steps to reproduce the problem**
Run the following service file and watch script output.
```
[Unit]
Description=Script
After=network.target

[Service]
ExecStart=/usr/bin/python -c "import time; import sys; time.sleep(1); print 'stdout'; time.sleep(2); print >> sys.stderr, 'stderr'; print 'stdout again'; time.sleep(30)"
Restart=always

[Install]
WantedBy=multi-user.target
```
Switching the command to `/usr/bin/python2 /usr/local/sbin/script.py` has no affect.

**Comment by vcaputo** [comment]
stderr is unbuffered while stdout is line-buffered, which is probably why you're seeing all the stdout prints in aggregate after stderr.

**Comment by volfco** [comment]
Yup @vcaputo. Running python with `-u` fixes it.
