### ISSUE TITLE
When /var/run -> ../run unneccessary pid updates and warnings

### ISSUE THREAD

**Issue by keithy** [systemd/systemd#14572]
v243.5-1.fc31

/usr/lib/systemd/system/sssd.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/sssd.pid → /run/sssd.pid; please update the unit file accordingly.

**Steps to reproduce the problem**

This occurs when using Fedora CoreOS because /var/run is symbolically linked to /run

**Comment by dustymabe** [comment]
hey @keithy - I think this is systemd just telling us that `sssd.service` needs to update `PIDFile=/var/run/sssd.pid` to `PIDFile=/run/sssd.pid`. i.e. not a bug but we maybe need to update: `@pidpath@` somehow in https://pagure.io/SSSD/sssd/blob/master/f/src/sysv/systemd/sssd.service.in

**Comment by poettering** [comment]
Everybody creates such a symlink. We require that from all systems running systemd. Please ask the sssd maintainers to update their unit file.
