### ISSUE TITLE
RFE: designate a namespace for module loading 

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#14576]
**Is your feature request related to a problem? Please describe.**
I'm using `RootImage/RootDirectory=` feature extensively. Almost all services run inside a minimal, custom file system dedicated to each service. However, the construction of file systems is affected by loading of kernel modules and firmware. The kernel seems to perform loads using the mount namespace of the process which triggers the load, so the file systems for the services must contain the needed files as well as tools for module loading (`/sbin/modprobe`). The files bind the file system to kernel version(s) supported and also increase the size of the file system. Space saving is obviously not a priority of this setup, but the module sets are quite big (even when dropping most of the modules) and this is also multiplied by the number of kernels supported.

**Describe the solution you'd like**
Allow designating one mount namespace (or more conveniently, a service) for module and firmware loading. This would need some changes to kernel. For example, a new file could be added to `/proc/sys/kernel/usermodehelper/` to specify the mount namespace used by the kernel for module loading (something similar for firmware). Very likely this would have to be filled in and kept updated by the service manager, which knows the namespaces well as they are created by it.

This way only the dedicated service (for example `udevd`) would need to have a file system containing modules, firmware and tools, while all others would be kept free of such stuff and the kernel version dependencies.

**Describe alternatives you've considered**
- `udevd` might be a candidate for handling also module and firmware load requests by extending the protocol between `udevd` and kernel.
- `systemd-modules-load` could be promoted from one-shot module loader to a module loading server (or new service without changing `systemd-modules-load`). Needs a new protocol.
- kernel support but no involvement from systemd: make a small tool launched by `ExecStartPost=`  which tells kernel that this mount NS is the chosen one. On service restarts, the time window of when the information would not be correct would be longer than with PID1 involvement.
- make a simple replacement for `/sbin/modprobe`, which forwards module load requests outside of the namespace. No changes would be needed to kernel or systemd but this would not work for firmware and the kernel would not enforce the use of the namespace.
- load a predetermined set of modules at once by `systemd-modules-load`. Inflexible, does not work for firmware (some of them seem to be loaded only later when the device is used) or for hardware plugged in later.
- just bind mount `/lib/modules/` where needed: PID1 file system would have to contain all modules, which are not needed otherwise. Would make some modules available to services which have no legitimate need for them, defeating the minimalist goal.

**Comment by boucman** [comment]
how do you load your modules ? is it through udev/hotplug or do you call "modprobe" directly ?

From my understanding of on-demand loading, I don't see how it could be happening in anything but the namespace in which udev is loaded, so I assume you are calling modprobe directly...

if that's the case, it makes sense that you need all those tools in your namespace. if that's not the case there is something fishy going on and we probably need more info on what you are doing...

**Comment by topimiettinen** [comment]
`udevd` loads most modules, I've made sure that `systemd-modules-load` is actually not needed to be run. Indeed it would make most sense if `udevd` or at least its mount namespace would always be used and the tools may as well be there (but they shouldn't need to be anywhere else).

However, module loading is triggered later by for example UFW (Uncomplicated Firewall) by using xtables, or `systemd-cryptsetup` for crypto and algorithm modules. I don't think these are loaded explicitly with `modprobe`. For one my network cards, the firmware gets loaded when `udevd` loads the driver but for the other, it's only loaded when `systemd-networkd` starts setting up the interface. Then I think some modules were requested in PID1 mount namespace (not same as `udevd`), but currently I've put the modules in more places than earlier when I was fighting with this problem.

**Comment by topimiettinen** [comment]
I replicated the setup so that modules, firmware and modprobe are only in `udevd` NS. Here are some kernel logs from the resulting failures:

HD Audio driver is loaded by `udevd` but it can't find a codec:
`kernel: hdaudio hdaudioC0D0: Unable to bind the codec`
Same for iwlwifi:
`kernel: iwlwifi 0000:3b:00.0: firmware: failed to load iwlwifi-7260-17.ucode (-2)`
This cryptic message tells that some Bluetooth crypto module failed to load:
`kernel: alg: ecdh: test failed on vector 2, err=-14`
Also BT firmware:
`kernel: bluetooth hci0: firmware: failed to load intel/ibt-hw-37.7.bseq (-2)`
This is the cryptsetup thing I mentioned, but it may actually as well be DM or LVM:  
`kernel: device-mapper: table: 254:40: crypt: unknown target type`
Related message (strange blank between "on" and "failed"):
`systemd-cryptsetup[693]: device-mapper: reload ioctl on   failed: Invalid argument`

This could be also related if something related to efivars module (which was loaded by udevd) didn't load:
```
systemd-udevd[456]: efivars.0: Running built-in command "kmod load platform:efivars"
systemd-udevd[456]: Inserted module 'efivars'
systemd-remount-fs[702]: /bin/mount for /sys/firmware/efi/efivars exited with exit status 32.
```

**Comment by topimiettinen** [comment]
UFW failure:
`ufw-init[723]: iptables/1.8.3 Failed to initialize nft: Protocol not supported`

I just noticed that UFW is actually OK if the module stuff is not present there but exist in PID1 namespace (similar boot but file system for PID1 contains the full OS).

**Comment by topimiettinen** [comment]
I made a small program, which takes place of `modprobe`, to show the mount namespace and indeed all invocations were from PID1 namespace. This makes life a bit easier, maybe proxying `modprobe` just for PID1 is the easiest solution.

```
#include <stdio.h>
#include <string.h>
#include <syslog.h>
#include <unistd.h>

int main(int argc, char *argv[], char *envp[]) {
        char ns_name[30];

        memset(ns_name, '\0', sizeof(ns_name));
        readlink("/proc/self/ns/mnt", ns_name, sizeof(ns_name));
        openlog("modprobe", LOG_CONS | LOG_PERROR | LOG_PID, LOG_DAEMON);
        syslog(LOG_ERR, "modprobe %s from %s", argv[1], ns_name);
        closelog();
        execve("/sbin/modprobe.real", argv, envp);
}
```

**Comment by topimiettinen** [comment]
I tossed the firmware files around, but there the problem remains, the files are loaded from various mount namespaces (PID1, udevd, systemd-networkd). For the firmware file issue, kernel change seems to be the only option as no user space loader is involved.

**Comment by topimiettinen** [comment]
Maybe a more preferable way would be that like modules, firmware files are also loaded with PID1's namespace (actually seems to be `kthreadd` for modules). This would not allow isolating all module / firmware handling to one dedicated namespace though.

**Comment by topimiettinen** [comment]
Patch sent to lkml: https://lkml.org/lkml/2020/1/17/755

**Comment by topimiettinen** [comment]
In [gregkh/driver-core-next](https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core.git/commit/?h=driver-core-next&id=901cff7cb96140a658a848a568b606ba764239bc).

**Comment by topimiettinen** [comment]
In [5.6-rc1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=901cff7cb96140a658a848a568b606ba764239bc).

**Comment by poettering** [comment]
OK, so I guess we can close this here then? There's nothing left to do on systemd's side, is there?

**Comment by topimiettinen** [comment]
Probably not. I'm not sure it's reasonable to implement the dedicated name space stuff, it's probably a bit too fragile.
