### ISSUE TITLE
Journal doesn't respect SystemMaxUse option

### ISSUE THREAD

**Issue by ac-frg** [systemd/systemd#14583]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > Yocto

**Unexpected behaviour you saw**
 > Journal doesn't respect SystemMaxUse option

**Steps to reproduce the problem**
Journald.conf:

[Journal]
Storage=persistent
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
#RateLimitBurst=10000
SystemMaxUse=128M
#SystemKeepFree=
#SystemMaxFileSize=
#SystemMaxFiles=100
RuntimeMaxUse=64M
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
#LineMax=48K
#ReadKMsg=yes

Info from Journal:

Jan 16 06:43:16 801F123DCE1E systemd-journald[278]: Journal started
Jan 16 06:43:16 801F123DCE1E systemd-journald[278]: Runtime journal (/run/log/journal/92ba909ee37f42988c5d91a5c9d74d4c) is 8.0M, max 64.0M, 56.0M free.
Jan 16 06:43:17 801F123DCE1E systemd-journald[278]: Time spent on flushing to /var is 1.192126s for 299 entries.
Jan 16 06:43:17 801F123DCE1E systemd-journald[278]: System journal (/var/log/journal/92ba909ee37f42988c5d91a5c9d74d4c) is 16.0M, max 128.0M, 111.9M free.
Jan 16 06:43:19 801F123DCE1E systemd-journald[278]: Missed 8 kernel messages
Jan 16 06:43:24 801F123DCE1E systemd-journald[278]: Missed 10 kernel messages

Journal files:
root@801F123DCE1E:~# du -h /var/log/journal/
17M     /var/log/journal/f656a1831b1e4954b0f7816ef01eeb9f
8.1M    /var/log/journal/55f7e3342a5442fa812a9a14b4f5c43a
8.1M    /var/log/journal/e88b8d3928ab4df197a4a21782b1894c
17M     /var/log/journal/5d309abe97534769888af39a853ef9ed
8.1M    /var/log/journal/cc1ec3a1f4424d6daac56175ad2a3635
17M     /var/log/journal/23c35ca4722f4ca88d21bd90dae03351
17M     /var/log/journal/6ed2021a3aa242b4bf906443a0e01934
17M     /var/log/journal/053395f30de646d59d222997f3618100
17M     /var/log/journal/92ba909ee37f42988c5d91a5c9d74d4c
25M     /var/log/journal/69063d7eae214bc9b9359cb310b4f376
17M     /var/log/journal/24b637f7c9ef40f9ac98d2bd97c08554
8.1M    /var/log/journal/f42bf4c14c7e42f59031a7f488b71f48
169M    /var/log/journal/

**Comment by poettering** [comment]
You apparently have an unstable machine ID? /etc/machine-id is supposed to be stable, and journald uses it to name the journal directories below /var/log/journal. If you keep chaning the machine ID then of course journald will create different directories all the time but never manage the old ones for you.

On stateless systems it's fine if /etc/machine-id is not table and determined randomly at boot, we explicitly support that. But stateless then also means that /var needs to be flushed out during each boot too. We do not support a mode where /etc/machine-id is dynamic but /var is stable.

Closing.
