### ISSUE TITLE
Will AddressSanitizer be added in meson_options.txt?

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#14606]
It might be useful to have AddressSanitizer.

**Comment by poettering** [comment]
Why thought? We have https://systemd.io/TESTING_WITH_SANITIZERS already, which explains all this well enough, and it's easy enough to enable this, even without explicit meson options. Isn't this enough?

**Comment by mrc0mmand** [comment]
Actually, meson already supports sanitizers, see https://mesonbuild.com/Builtin-options.html#base-options, option `b_sanitize`, so I'm not sure what's the RFE part here. It's also describe in detail in the document @poettering linked.

**Comment by fayeinseu** [comment]
> Why thought? We have https://systemd.io/TESTING_WITH_SANITIZERS already, which explains all this well enough, and it's easy enough to enable this, even without explicit meson options. Isn't this enough?

thanks，I've tried to add option Dsanitize in meson_options.txt, however I don't know about  https://systemd.io/TESTING_WITH_SANITIZERS before, I will try it.
