### ISSUE TITLE
growfs does not handle case when online resizing requires filesystem to be mounted as read-write

### ISSUE THREAD

**Issue by zOrg1331** [systemd/systemd#14603]
**systemd version the issue has been seen with**
244 (probably, does not depend on version)

**Used distribution**
ALT Linux (http://www.altlinux.org)

**Expected behaviour you didn't see**
Resizing the requested filesystem when `x-systemd.growfs` option is specified in `/etc/fstab` and all conditions are met.

**Unexpected behaviour you saw**
Root filesystem (ext4) was requested to be resized, `/etc/fstab` line:
```
UUID=e98df2d1-5b88-4a41-8da5-d90df8a47e92       /       ext4    x-systemd.growfs        1 1
```
Underlying partition had enough space for resizing fs. However, during resize attempt the following error was recorded in journal:
```
systemd-growfs[840]: Failed to resize "/" to 1894400 blocks (ext4): Read-only file system
```
The following manual operations in single-user mode demonstrate the requirement of having rootfs mounted as read-write:
```
bash-4.4# mount | grep mmc
/dev/mmcblk0p1 on / type ext4 (ro,relatime,data=ordered)
bash-4.4# /sbin/resize2fs /dev/mmcblk0p1 
resize2fs 1.44.6 (5-Mar-2019)
Filesystem at /dev/mmcblk0p1 is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1
/sbin/resize2fs: Read-only file system While checking for on-line resizing support
bash-4.4# mount -o remount,rw /
bash-4.4# /sbin/resize2fs /dev/mmcblk0p1 
resize2fs 1.44.6 (5-Mar-2019)
Filesystem at /dev/mmcblk0p1 is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1
The filesystem on /dev/mmcblk0p1 is now 1894400 (4k) blocks long.
```

**Steps to reproduce the problem**
Request root filesystem to be expanded. The issue will be triggered if growfs service will be called on read-only mounted filesystem when online resizing happens (on mounted filesystem).

**Comment by poettering** [comment]
Hmm, resizing a file system requires writing to it, isn't that obvious? 

I mean, we could of course, mount the fs writable, then do the resize, then mount it read-only again, but that's racy and would mean apps could write to the fs too in the time window where things are writable...

**Comment by kkm000** [comment]
A missing ordering dependency. I am rolling out cloud VMs, and they always resize their boot disks, as the archetype it starts with is quite small. For a couple years this has been an obligatory drop-in:
```conf
# /etc/systemd/system/systemd-remount-fs.service.d/override.conf
#
# Workaround for a systemd bug #TBD: remount-fs and growfs@ race
# so that the latter may fail because the / is still readonly.
# This ensures the remount happens first.
[Unit]
Before=systemd-growfs@-.service
```
@poettering, sorry, I should have reported it long ago, but it kinda slipped off my radar. At least, I can put this issue id in place of that '#TBD' placeholder. :)

@zOrg1331, I'd appreciate if you test this in your setup. This will provide additional evidence we are really seeing the same problem. Thanks.

**Comment by poettering** [comment]
@kkm000 could you have a look at #14618? That should fix the issue

**Comment by kkm000** [comment]
@poettering, thanks, looks like it should.
