### ISSUE TITLE
RFE: support ConditionHardwareVirtualization=boolean

### ISSUE THREAD

**Issue by mrinaldhillon** [systemd/systemd#14602]
Services running inside container should be able to identify base host virtualization. What do you think?

**Comment by poettering** [comment]
Uh, I am not convinced that this either can work semantically nor technically, since the host virtualization is in many cases hidden from containers. This could never work reliable and for all VM types...

**Comment by mrinaldhillon** [comment]
@poettering we can come up with a semantically correct directive , how about ConditionHardwareVirtualization=boolean ?

Could you please give an example of when it is technically not possible to use systemd-detect-virt --vm in container? Also it can be well documented caveat of the directive as part of Container Interface.

**Comment by poettering** [comment]
We need access to /proc/xen, /sys/class/dmi/id/*, /proc/device-tree, /sys/hypervisor/*, /proc/sysinfo, /proc/cpuinfo at least for the VM detection. It's not clear which container managers make those available, and which do not. For nspawn at least /sys/hypervisor is missing (the rest is read-only in nspawn, but readable, which is what we need).

hence, I am not sure we should make this available if we cannot make it work everywhere, and not even on our own container mgr

**Comment by boucman** [comment]
a bit of a naive question, but why do you need that ? in what use-case does a container need the underlying tech of the underlying virtualisation solution ?

**Comment by mrinaldhillon** [comment]
I agree with Lennart's concern. However any code that depends on systemd to detect hardware virtualization cannot be reliably containerized at the moment. By using ConditionVirtualization=|\?!\?vm flag or systemd-detect-virt --vm application shows clear intent to identify hardware virtualization and expects atleast true/vm_other or false. This flag is useless inside container. Also systemd-detect-virt --vm cannot be relied upon.

IMHO the behaviour should be identical in all cases. ConditionVirtualization=|\?!\?vm should at-least attempt to identify hardware virt. Moreover ContainerInterface should document proc/sysfs requirements to allow systemd (and other code) to identify hardware virtualization.
