### ISSUE TITLE
restorecon has no effect in systemd-nspawn -D because /sys/fs/selinux is ro

### ISSUE THREAD

**Issue by hkoba** [systemd/systemd#14601]
Recently I found systemd-nspawn is very useful to prepare chroot-ed system image spaces. Since it does most of /dev,/sys and /proc jobs nicely for me, my cloud image build script becomes much simpler than before. Thank you for your great efforts.

Unfortunately, I also found getenforce returns `Disabled` in nspawn-ed space. This caused `dnf update systemd` to label `/usr/lib/systemd/systemd` as lib_t instead of init_exec_t and the resulting system image becomes unusable state (no one can login;-). And even worse, 
restorecon doesn't work because getenforce is disabled.

Although it can be solved manually by remounting selinuxfs as rw, doing it for every systemd-nspawn invocations make my image build script complex again.

Version: systemd-241-12.git323cdf4.fc30.x86_64
Distribution: fedora30
Kernel: 5.4.7-100.fc30.x86_64

**Describe the solution you'd like**
So, I want to see future systemd-nspawn to have an option to mount selinuxfs as rw.

**Describe alternatives you've considered**
Alternatively, how about adding a note about how to enable selinux in nspawn to the manual page of systemd-nspawn?

```
mount -o remount,rw /sys/fs/selinux
```

Thank you!

**Comment by keszybz** [comment]
Does making /sys/fs/selinux rw grant privileges that affect the host selinux configuration (I assume yes). In that case telling people how to mount it rw does not sound like a good idea.

**Comment by hkoba** [comment]
Hi! Thank you for your quick reply!

I can understand your concerns about affecting the host selinux configuration.
That is why I requested having **an option** to mount /sys/fs/selinux rw.

I tested `setsebool` affects the host selinux config or not. It does. Here is the result:
```
Z-chtholly(pts/5)% getsebool httpd_can_network_connect_db
httpd_can_network_connect_db --> off
Z-chtholly(pts/5)% sudo systemd-nspawn -D /mnt/disk
Spawning container disk on /mnt/disk.
Press ^] three times within 1s to kill container.
[root@disk ~]# getenforce 
Disabled
[root@disk ~]# mount -o remount,rw /sys/fs/selinux
[root@disk ~]# getenforce
Enforcing
[root@disk ~]# getsebool httpd_can_network_connect_db
httpd_can_network_connect_db --> off
[root@disk ~]# setsebool httpd_can_network_connect_db on
[root@disk ~]# getsebool httpd_can_network_connect_db
httpd_can_network_connect_db --> on
[root@disk ~]# logout
Container disk exited successfully.
Z-chtholly(pts/5)% getsebool httpd_can_network_connect_db
httpd_can_network_connect_db --> on
Z-chtholly(pts/5)% 
```

So I don't want to change current behavior of systemd-nspawn. Instead, I wish if I could choose mounting /sys/fs/selinux as rw by giving a runtime option to systemd-nspawn.

--------

By the way, with reading some SELinux codes, I found libselinux explicitly requires writable selinuxfs. I'm not sure why, but it seems to me libselinux is intentionally designed to do nothing if selinuxfs is mounted read-only. Following is my observations:

`getenforce` command just calls `is_selinux_enabled()`

https://github.com/SELinuxProject/selinux/blob/5bbe32a7e585dcd403739ea55a2fb25cbd184383/libselinux/utils/getenforce.c

```c
	rc = is_selinux_enabled();
	if (rc < 0) {
		fputs("getenforce:  is_selinux_enabled() failed", stderr);
		return 2;
	}
	if (rc == 1) {
		rc = security_getenforce();
		if (rc < 0) {
			fputs("getenforce:  getenforce() failed", stderr);
			return 2;
		}

		if (rc)
			puts("Enforcing");
		else
			puts("Permissive");
	} else {
		puts("Disabled");
	}

```

`is_selinux_enabled()` examins 2 variables `selinux_mnt && has_selinux_config`.
https://github.com/SELinuxProject/selinux/blob/5bbe32a7e585dcd403739ea55a2fb25cbd184383/libselinux/src/enabled.c#L11-L20

```c
int is_selinux_enabled(void)
{
	/* init_selinuxmnt() gets called before this function. We
 	 * will assume that if a selinux file system is mounted, then
 	 * selinux is enabled. */
#ifdef ANDROID
	return (selinux_mnt ? 1 : 0);
#else
	return (selinux_mnt && has_selinux_config);
#endif
}
```

These variables are initialized from`init_lib`.
https://github.com/SELinuxProject/selinux/blob/5bbe32a7e585dcd403739ea55a2fb25cbd184383/libselinux/src/init.c#L150-L158

`has_selinux_config` is defined by `access()`
```c
static void init_lib(void) __attribute__ ((constructor));
static void init_lib(void)
{
	selinux_page_size = sysconf(_SC_PAGE_SIZE);
	init_selinuxmnt();
#ifndef ANDROID
	has_selinux_config = (access(SELINUXCONFIG, F_OK) == 0);
#endif
}
```

`selinux_mnt` is defined only if selinux is mounted as `!ST_RDONLY`.

https://github.com/SELinuxProject/selinux/blob/5bbe32a7e585dcd403739ea55a2fb25cbd184383/libselinux/src/init.c#L32-L54

```c
		if ((uint32_t)sfbuf.f_type == (uint32_t)SELINUX_MAGIC) {
			struct statvfs vfsbuf;
			rc = statvfs(mnt, &vfsbuf);
			if (rc == 0) {
				if (!(vfsbuf.f_flag & ST_RDONLY)) {
					set_selinuxmnt(mnt);
				}
				return 0;
			}
		}
```

**Comment by poettering** [comment]
Uh, SELinux is not virtualized, containers cannot load their own policy or have their own label database, and hence really shouldn't ba able to make changes to labels either.

Marking the dir r/o is considered the API to telll the code inside the container that selinux is not really available in the container and should not be actively managed by the code inside the container.

We can lift this restriction as soon as SELinux becomes virtualized for containers. Then nspawn could enable it inside the containers too, and the container could load its own policy and then apply labels as it sees fit.

**Comment by doverride** [comment]
This might help?

https://lore.kernel.org/selinux/20190912133007.27545-1-jlebon@redhat.com/T/#u

and this maybe?

https://bugzilla.redhat.com/show_bug.cgi?id=1758597

**Comment by hkoba** [comment]
Hi, poettering! Thank you for your comment about this feature request, and also, thank you for your long term efforts to build systemd. I love Systemd because it modernized Linux's userland quite a lot.

I agree with your decision to keep /sys/fs/selinux ro until SELinux becomes capable of virtualization. I feel even current systemd-nspawn is useful enough than bare chroot + manual procfs,sysfs,devfs, etc... mounting. But I can understand and respect your goal to provide better virtualization with systemd-nspawn.

**Comment by DemiMarie** [comment]
For image building, you can pass `setfiles` an explicit path to the policy.  It will then set the extended attributes directly.

**Comment by hkoba** [comment]
Hi DemiMarie!

Thank you for your advice to use `setfiles`. After some googling, I found this mailing list archive: https://selinux.tycho.nsa.narkive.com/lVbPWZGP/how-do-you-relabel-all-selinux-file-contexts-of-an-offline-system-s-file-system

It seems a good workaround for my use case. Thank you!

**Comment by DemiMarie** [comment]
You’re welcome!
