### ISSUE TITLE
systemd-networkd fails to decode DHCP SendOption with a null character (\00)

### ISSUE THREAD

**Issue by dontomage** [systemd/systemd#14609]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 >My ISP waits for a DHCP AUTH string starting with \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0d followed by a credential. Putting the following line in my 10-wan.network file should allow the string to be sent:
SendOption=90:string:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential

>Using tcpdump, I should see this message in the DHCP packet :
`AUTH Option 90, length 31: 0.0.0.0.0.0.0.0.0.0.0.26.9.0.0.5.88.1.3.65.1.12.114.101.100.101.110.116.105.97.108`

**Unexpected behaviour you saw**
 > The message does not appear in the packet sent and the following errors are found in journalctl:

```
/etc/systemd/network/10-wan.network:11: Failed to decode DHCPv4 option data, ignoring assignment: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential
/etc/systemd/network/10-wan.network:11: Failed to store DHCPv4 option 'x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential', ignoring assignment: Invalid argument
```
>Removing all the `\00` characters works. This null character seems to be the problem.

**Steps to reproduce the problem**
On any interface in DHCP (eg. wan), use the option SendOption in the DHCP block:
```
[DHCPv4]
SendOption=90:string:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential
```
On the same interface, listen to udp packets with `tcpdump -i wan -v udp`
Restart systemd-networkd with `systemctl restart systemd-networkd`

**Comment by Toniob** [comment]
Hi,
I've got the same issue here (Orange ISP in France). The string is parsed going through the cunescape function. And this function doesn't allow NUL character
  https://github.com/systemd/systemd/blob/05332e243cfcea70f900a741b917d04291a1f9e0/src/basic/escape.c#L173
That's why decoding fails.

**Comment by ssahani** [comment]
> Hi,
> I've got the same issue here (Orange ISP in France). The string is parsed going through the cunescape function. And this function doesn't allow NUL character
> 
> https://github.com/systemd/systemd/blob/05332e243cfcea70f900a741b917d04291a1f9e0/src/basic/escape.c#L173
> 
> 
> That's why decoding fails.

hmmm should we drop that line or do a bool @yuwata ?

**Comment by yuwata** [comment]
Could you test #14675?

**Comment by dontomage** [comment]
I've tested, it's working. Thanks !
