### ISSUE TITLE
dhcpcd: can dhclient take over dhcpclient function from kernel after system boot

### ISSUE THREAD

**Issue by YanfeiXu** [systemd/systemd#14610]
I use kernel with CONFIG_IP_PNP_DHCP when rootfs is nfs.  But kernel seems can't renew the lease, so DHCP server will reclaim the IP. 
Can run DHCP client after nfs mount by systemd for renewing lease function? I have found some service file in yocto that don't run dhclient if rootfs is nfs. 

If you need any file or log ,please let me know. Thanks!

**Comment by yuwata** [comment]
This is not a support forum, please use our mailing list (or dhclient's support forum if you use dhclient).

One point. If you use systemd-networkd, then KeepConfiguration=dhcp may help you. But if you use dhclient, then we cannot help you...
