### ISSUE TITLE
scoket activation: Unreclaimable slab (cred_jar) grows continuously 

### ISSUE THREAD

**Issue by nunojpg** [systemd/systemd#14639]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Container Linux by CoreOS stable (2303.3.0)

**Unexpected behaviour you saw**
 > Unreclaimable slab (cred_jar) grows continuously 

In CoreOS sshd is socket activated. When I have the port exposed to the internet and get a substantial amount of connection attempts my RAM gets exhausted. I've been observing this since ever (about 1 year).

echo 2 > /proc/sys/vm/drop_caches does not release any memory.

I expect that after the socket activation terminates the connection/process, no unreclaimable slab is left behind. I would appreciate help to track it down even if there is a chance that this will be a kernel bug instead.

**Comment by poettering** [comment]
we only track issues in the two most current systemd versions here. 241 is too old, sorry. Older bugs like that should be reported downstream. (the submission form should have made that clear, to keep frustration low)

But in general: this looks like a kernel/distro bug to me, unless you see that systemd's own resource usage grows? i.e. do the fds in /proc/1/fd grow without bound for example? or its RSS?

Anyway, let's close this here for now. Please cntact your downstream distro first, and let them escalate this here if they are sure it's a systemd issue. Thank you!

**Comment by nunojpg** [comment]
Thanks Lennart.

> But in general: this looks like a kernel/distro bug to me, unless you see that systemd's own resource usage grows? i.e. do the fds in /proc/1/fd grow without bound for example? or its RSS?

The number of /proc/1/fd does not increase over time.
The only observation I currently have is unreclaimable slab (cred_jar) growing.

Since you mention RSS, how should I check that?

I would like to collect as much information as possible before either trying to update systemd or reporting to Linux.
