### ISSUE TITLE
Boot lockup  when NTP is disabled

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#14648]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > buildroot

**Expected behaviour you didn't see**
 > Boot should properly finish

**Unexpected behaviour you saw**
 > The initial boot transaction never finishes, `systemctl status` stays in the starting state

**Steps to reproduce the problem**
* start with a fresh systemd installation
* run `timedatectl set-ntp false`
* reboot

Since systemd v243, all units provided by systemd are enabled by default (unless a preset file changes that). As a consequence, systemd-time-wait.service is enabled and is started at boot time.

Because there is no NTP, the service nerver finishes. Because that service has a timeout set to infinite, the service never finishes and the initial bootup is never concluded.

Note that we do reach default.target so the bug is not as serious as it seems, but numerous boot-related (like systemd-analyze critical-chain) are broken.

There are various ways to fix this, but I'm not sure what the proper approch would be. maybe put a timeout and let time-sync.target fail ?

**Comment by boucman** [comment]
Thinking about it some more, the proper fix might be to not start time-sync.target at all and have it be an "on demand" target. i.e it is started when someone Wants it.

This way unless a service explicitely asks to be after time-sync.target, it is not started.

The infinite timeout is also questionnable. I believe it's here to deal with the very long delays for ntp synchronisation via drift, but in that case it might be better to  have a timeout and extend it when drifting is taking place (assuming this can be detected... i'm not sure it's possible)

**Comment by keszybz** [comment]
I agree we should just disable the target. See the linked PR.

> The infinite timeout is also questionnable

Yes, it is. But what should we use? NTP syncrhonization can take a very long time. If somebody can specify what is a good limit which would be enough for "sane" NTP settings, we should change to that (+ a little bit).

**Comment by boucman** [comment]
my original idea was to have a reasonable timeout and have time-wait.service use EXTEND_TIMEOUT_USEC= when it detects that there is some drift correction going on.

but as I said, i'm not sure this is actually detectable...

**Comment by keszybz** [comment]
> my original idea was to have a reasonable timeout and have time-wait.service use EXTEND_TIMEOUT_USEC= when it detects that there is some drift correction going on.

I think this would be nice.
