### ISSUE TITLE
Timer runs on every boot

### ISSUE THREAD

**Issue by Louis9902** [systemd/systemd#14642]
**systemd version the issue has been seen with**
> systemd 243 (v243.5-1.fc31)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > fedora 31

**Expected behaviour you didn't see**
**Unexpected behaviour you saw**
 > **TLDR:** Timer runs on every boot even though it is not supposed to.
 > I created a timer and a unit file like these:

```
[Unit]
Description=Example timer which is used for debugging
Requires=example.service

[Timer]
OnCalendar=*-*-* 15:05:00
RandomizedDelaySec=2m
Persistent=true

[Install]
WantedBy=timers.target
```

```
[Unit]
Description=An example service to debug some functionality

[Service]
User=louis
ExecStart=bash -c "/usr/bin/date >> /home/louis/service_results"
```
> This is just an example, but when I enable the timer and it runs the service does its thing, no problem here. But after the reboot the service is executed again even though the timer is not elapsed.
> This happens with the user session as well as with the system session of systemd.

**Steps to reproduce the problem**
1. Install the service files, maybe adjust the paths and the time.
2. Enable the timer and let it run once...
3. Look at the file an remember the last time.
4. Rebbot and look at the file again.

**Comment by arvidjaar** [comment]
Not a bug.

> `Requires=example.service`

This causes `example.service` to be started every time `timer` unit is started.

**Comment by mbiebl** [comment]
Right, since example.timer is started via timers.target during boot, example.service will be started as well due to `Requires=example.service`. Just drop that line and it should work.

**Comment by Louis9902** [comment]
Oh okay thanks, then I misunderstood the documentation.
