### ISSUE TITLE
bootctl - problems with EFI loader.conf parsing 

### ISSUE THREAD

**Issue by JiriPodhorny** [systemd/systemd#14657]
**systemd version the issue has been seen with**
> systemd-boot 244.1-1-arch

**Used distribution**
 > Arch Linux (5.4.14)

**Expected behaviour you didn't see**
 > My loader.conf file:

`default arch`
`timeout 2`
`random-seed-mode always`

**Unexpected behaviour you saw**
 > "bootctl" command produce report with first line:

`/boot/loader/loader.conf:4: Unknown line "random-seed-mode", ignoring.`

**Steps to reproduce the problem**
> use loader.conf with any random-seed-mode option
run bootctl

**Problems found:**

File: systemd-master/src/shared/bootspec.c
Function: boot_loader_read_conf
Line: 232
Problem: missing '**else if (streq(field, "random-seed-mode")** ...'

File: systemd-master/src/boot/efi/boot.c
Function: print_status
Lines: 407,410
Problem:  text "random-seed-**node**" should be "random-seed-**mode**"

**Comment by yuwata** [comment]
Fix is waiting in #14667.
