### ISSUE TITLE
hwdb: Lenovo Ideapad 710S-13IKB touchpad

### ISSUE THREAD

**Issue by lucazade** [systemd/systemd#14668]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Manjaro

**Unexpected behaviour you saw**
 The Y-axis resolution for the Lenovo Ideapad 710S-13IKB 13" touchpad is far too low, which is confirmed by udev reporting the size as 102x28 mm, while the real size is 104x70.
(similar to bug #4027)

Even if I apply a new hwdb rule created with touchpad-edge-detector the vertical movement is still really short.

**Steps to reproduce the problem**
Output of touchpad-edge-detector 104x70 /dev/input/event15:
```
Touchpad AlpsPS/2 ALPS GlidePoint on /dev/input/event15
Move one finger around the touchpad to detect the actual edges
Kernel says:    x [0..4095], y [0..2047]
Touchpad sends: x [132..3954], y [110..1961] /^C

Touchpad size as listed by the kernel: 102x28mm
User-specified touchpad size: 104x70mm
Calculated ranges: 3822/1851

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:AlpsPS/2 ALPS GlidePoint:dmi:bvnLENOVO:bvr3HCN12S2:bd10/07/2016:svnLENOVO:pn80VQ:pvrLenovoideapad710S-13IKB:rvnLENOVO:rnLenovoideapad710S-13IKB:rvrSDK0J40709WIN:cvnLENOVO:ct10:cvrLenovoideapad710S-13IKB:*
 EVDEV_ABS_00=132:3954:37
 EVDEV_ABS_01=110:1961:26
 EVDEV_ABS_35=132:3954:37
 EVDEV_ABS_36=110:1961:26

```

Output of udevadm info /dev/input/event15 after new rule:
```
P: /devices/platform/i8042/serio1/input/input7/event15
N: input/event15
L: 0
S: input/by-path/platform-i8042-serio-1-event-mouse
E: DEVPATH=/devices/platform/i8042/serio1/input/input7/event15
E: DEVNAME=/dev/input/event15
E: MAJOR=13
E: MINOR=79
E: SUBSYSTEM=input
E: USEC_INITIALIZED=3425541
E: EVDEV_ABS_00=132:3954:37
E: EVDEV_ABS_01=110:1961:26
E: EVDEV_ABS_35=132:3954:37
E: EVDEV_ABS_36=110:1961:26
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_WIDTH_MM=102
E: ID_INPUT_HEIGHT_MM=28
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-1
E: ID_PATH_TAG=platform-i8042-serio-1
E: ID_INPUT_TOUCHPAD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/2/8:isa0060/serio1
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-1-event-mouse
```

**Comment by whot** [comment]
I take it you restarted your session/rebooted after the hwdb entry was applied? That entry looks correct to me, so I'd say submit a PR for it, let's close it for systemd and open a bug in libinput if the pointer movement is an issue after that.

**Comment by lucazade** [comment]
Yes, I have restarted session/pc but pointer movement is still too short.
I'm going to open a libinput bug then.
Just one thing...what is a PR??

**Comment by whot** [comment]
PR == pull request, MR is merge request. Github uses the former, gitlab - which e.g. libinput uses - the latter, but it's effectively the same process for both. you'll find plenty of documentation and tutorials on how to do it online, in better format than a comment posted here :)

**Comment by poettering** [comment]
Let's close this. Please submit any new data as pull request, as mentioned, we'll then review/merge it. Thank you!
