### ISSUE TITLE
networkd: options for checksum offloading?

### ISSUE THREAD

**Issue by lheckemann** [systemd/systemd#14661]
**Is your feature request related to a problem? Please describe.**
One of my machines has a buggy network chip or driver, and will stop responding to various types of network traffic after a few hours or days of uptime – unless TX checksum offloading is disabled (`ethtool --offload eth0 tx off`). I'd like to be able to configure this with networkd.

**Describe the solution you'd like**
Addition of a `[Link]` section option for checksum offloading.

**Describe alternatives you've considered**
- Creating a service which runs ethtool to apply the setting (currently using this). It seems like something that networkd should be able to do though.

**Comment by yuwata** [comment]
If possible, please test #14676.
