### ISSUE TITLE
Create isolated bridge with traffic conlrol

### ISSUE THREAD

**Issue by ne-vlezay80** [systemd/systemd#14671]
Haw to create isolation bridge with systemd-networkd?

**Comment by zamshe21** [comment]
interface in clear linux
/etc/systemd/network.br0.netdev
[NetDev]
Name=br0
Kind=bridge

/etc/systemd/network/br0.network
[Match]
Name=br0

[Network]
Address=10.0.0.3/16
Gateway=10.0.0.1
DNS=10.0.0.1

**Comment by yuwata** [comment]
Sorry, this is not a support forum. Please use our mailing list instead.
