### ISSUE TITLE
core: top-level drop-in service.d wrong precedence

### ISSUE THREAD

**Issue by tchernomax** [systemd/systemd#14680]
**systemd version the issue has been seen with**

```
systemd 244 (244.1-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**

Archlinux

**Expected behaviour you didn't see**

Considering:
```
max@mde-oxalide % tail -n+1 failure-notify-send@.service failure-notify-send@.service.d/default.conf service.d/default.conf
==> failure-notify-send@.service <==
[Unit]
OnFailure=
…
[Service]
…

==> failure-notify-send@.service.d/default.conf <==
[Unit]
OnFailure=

==> service.d/default.conf <==
[Unit]
OnFailure=failure-notify-send@%N.service
```

As `man systemd.unit` indicate:

> Configurations in type.d/ have the lowest precedence compared to settings in the name specific override directories. So the contents of foo-.service.d/10-override.conf would override service.d/10-override.conf.

I expect that `failure-notify-send@.service.d/default.conf` should override `service.d/default.conf`.

```
max@mde-oxalide % systemctl --user show -p OnFailure failure-notify-send@toto.service
OnFailure=
```

**Unexpected behaviour you saw**

`service.d/default.conf` override `failure-notify-send@.service.d/default.conf`:

```
max@mde-oxalide % systemctl --user show -p OnFailure failure-notify-send@toto.service
OnFailure=failure-notify-send@failure-notify-send@toto.service
```

```
max@mde-oxalide % systemctl --user cat failure-notify-send@.service
# /home/max/.config/systemd/user/failure-notify-send@.service
…
# /home/max/.config/systemd/user/service.d/default.conf
…
```

**Steps to reproduce the problem**

```
mkdir ~/.config/systemd/user/
cd ~/.config/systemd/user/
mkdir service.d
mkdir toto@.service.d
cat > toto@.service <<END
[Unit]
[Service]
ExecStart=/usr/bin/sleep 600
END
cat > service.d/default.conf <<END
[Unit]
OnFailure=toto@%N.service
END
cat > toto@.service.d/default.conf <<END
[Unit]
OnFailure=
END
```

Then:

```
systemctl --user show -p OnFailure toto@titi.service
```

**Notes**

I tried with `toto@.service.d/override.conf` instead of `toto@.service.d/default.conf`.
But then both settings are mixed (And there is no way to reset the `OnFailure` list).

I also tried `toto@.service.d/default.conf` symlinked to /dev/null… without success.

**Comment by anitazha** [comment]
https://github.com/systemd/systemd/pull/14441 should fix this but it was merged just a bit after the version you're using. Sorry :(
