### ISSUE TITLE
Delete or Modify Specific Lines Based on Filters?

### ISSUE THREAD

**Issue by randoogle** [systemd/systemd#14709]
I recently found that a specific application has been logging my passwords to my user.journal logs for months.
As it is I'm left with the option of completely deleting all my logs, but it would sure be nice to be able to delete or replace (obfuscate) certain lines, so that I can still preserve my other logs.

**Comment by keszybz** [comment]
You can just rewrite the journal, grepping out the bad lines.
```bash
journalctl -o export --grep 'match-lines-without-password' | /usr/lib/systemd/systemd-journal-remote -o /tmp/dir/new.journal -
```
where 'match-lines-without-password' should be a pattern to filter-out the lines with the password. If the line from the logs if fixed, this could be something like `^[^T][^h][^e][^ ][^u][^s][^e][^r][^ ][^l][^o][^g][^g][^e][^d][^ ][^i][^n][^ ][^u][^s][^i][^n][^g][^ ][^p][^a][^s][^s][^w][^o][^r][^d]`. If we have negative matches, something much easier could be used, but we this should do in a pinch.

Afterwards, simply remove old journal files and move in the new ones.
