### ISSUE TITLE
[systemd-homed] Immutable home directory

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#14702]
Firstly - sorry for my poor English.
Idea was started by this thread: https://forums.opensuse.org/showthread.php/536699-IDEA-Simple-but-powerful-security-system .
The main problem is: how to make user home secure? First revision is to create two user UID instead of only one and create two home directory. One will be only-read and second read-write. Next task is to create special daemon, which applications could talk to change one's settings in first directory. Of course, application should been integrated to read settings and write it to first.

But the idea goes further and now I think:
1. We still need two directories
2. Some directories/files in user home will be temporary changeable - when application decided (for example) to write into ~/.mozilla/firefox/... , systemd will check there exist changes in ~/.mozilla/firefox/.. , and if user decided to logout, systemd asks user to keep it
3. (Maybe) add action to show differences between previous and current state of unchangeable directories

This ideas could be implemented by some Onion/Layered filesystem

**Comment by nintyfan** [comment]
I will try to create some solution in nearest future. I will use fuse fs + dbus daemon. Fuse fs will use dbus api to talk with daemon, daemon will open file and send fd to fuse fs (python script). Problem is everything should be multi thread and we should deny access by default after some time period.

**Comment by poettering** [comment]
I am not convinced this is really something we should do in systemd-homed. i.e. homed is not suppsoed to force user apps into new APIs: the idea is that once logged in we offer a real UNIX home directory, nothing else. Hence, I your idea might have some merit, but I really think that systemd-homed is not the best place for it.

Sorry if that's disappointing!
