### ISSUE TITLE
Add defaults.conf file to override defaults

### ISSUE THREAD

**Issue by melbahja** [systemd/systemd#14713]
**Is your feature request related to a problem? Please describe.**
I want to change default values for some security options to be applied to all services

**Describe the solution you'd like**
For example create a file `/etc/systemd/defaults.conf`, options in this file will change defaults systemd options values, this file will be empty by default on systemd to avoid breaking something.
example if the file contents is:
```
PrivateDevices=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
```
systemd will use this options as defaults, and if `defaults.conf` has options in it add a message for the admin in logs for example, or in status command.

**Describe alternatives you've considered**
...

Thanks.

**Comment by anitazha** [comment]
It's not exactly the same as what you're suggesting but in 244 there is support for top-level drop-ins that apply across all units of the specified type. It would have a similar effect as an overridden "default" value. You can read about it at https://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by melbahja** [comment]
This is just an idea I thought about to solve my issue, I will try this after I update my systemd to 244.
Thanks

**Comment by keszybz** [comment]
Yep, the default drop-ins do pretty much what was requested.
