### ISSUE TITLE
environment.d man page seems to imply that it might affect login shells

### ISSUE THREAD

**Issue by ChaiTRex** [systemd/systemd#14714]
**systemd version the issue has been seen with**
> Master branch here

**Used distribution**
 > All (concerns man page at https://github.com/systemd/systemd/blob/master/man/environment.d.xml)

**Expected behaviour you didn't see**
 > `man environment.d` expresses clearly enough that environment variables set in `/etc/environment.d` won't be set for end-user shells.

**Unexpected behaviour you saw**
 > `man environment.d` starts with the misleading:

 >> The environment.d directories contain a list of "global" environment variable assignments for the user environment.  systemd-environment-d-generator(8) parses them and updates the environment exported by the systemd user instance to the services it starts.

The first sentence has the misleading "the user environment", which could, to a newcomer, easily mean the environment variables end users see in shells. The second sentence doesn't dispel that false conclusion from the first. For all I know, not knowing how systemd works, one of the services it starts goes on to provide the variables to end user shells.

**Steps to reproduce the problem**

0. Run `man environment.d` as someone new to systemd.
0. Be misled.

Please incorporate something like the fairly clear correction in #12938 into that man page.

**Comment by aungxilwin7** [comment]
![FB_IMG_1566539633312](https://user-images.githubusercontent.com/61482157/75475293-efcfef80-59c6-11ea-8745-a3896b03cf96.jpg)

**Comment by aungxilwin7** [comment]
#14714

**Comment by aungxilwin7** [comment]
@aungxilwin7

**Comment by aungxilwin7** [comment]
#14814

**Comment by aungxilwin7** [comment]
* Item 1
* Item 2
  * Item 2a
  * Item 2b

**Comment by aungxilwin7** [comment]
- [ ] `**1.**` ### **__**

**Comment by jdebp** [comment]
The explanation of how GNOME Terminal works, now given in the manual, is false.  GNOME Terminal does not work that way, and environment variables set by the systemd per-user service manager will not be seen in shells spawned by GNOME Terminal.

* https://unix.stackexchange.com/a/407863/5132

**Comment by keszybz** [comment]
I can't read 8 paragraphs of dense text with historical references. If you can succinctly state what is wrong with the description after  3ea2b11, I'll be happy to fix it.
