### ISSUE TITLE
"systemctl show": serialization of "EnvironmentFile" is not re-usable ("EnvironmentFiles")

### ISSUE THREAD

**Issue by sumpfralle** [systemd/systemd#14723]
**systemd version the issue has been seen with**
244

**Used distribution**
Debian testing (to be *bullseye*)

**Expected behaviour you didn't see**
```shell
$ environmentfile_property=$(systemctl show ssh | grep "^EnvironmentFile" | head -1)
$ echo "$environmentfile_property"
EnvironmentFile=-/etc/default/ssh
$ systemd-run --quiet --collect --pipe --property "$environmentfile_property" -- /bin/echo foo
foo
$ echo $?
0
```

**Unexpected behaviour you saw**
```shell
$ environmentfile_property=$(systemctl show ssh | grep "^EnvironmentFile" | head -1)
$ echo "$environmentfile_property"
EnvironmentFiles=/etc/default/ssh (ignore_errors=yes)
$ systemd-run --quiet --collect --pipe --property "$environmentfile_property" -- /bin/echo foo
Unknown assignment: EnvironmentFiles=/etc/default/ssh (ignore_errors=yes)
$ echo $?
1
```

**Steps to reproduce the problem**
```shell
$ systemctl edit --user --runtime --force --full foo
# type into spawned editor:
[Service]
EnvironmentFile=-/etc/default/foo
$ systemctl show --user --runtime foo | grep ^Env
EnvironmentFiles=/etc/default/foo (ignore_errors=yes)
```

**Use case (short description)**
The output of `systemctl show` in general is usable as an input for creating new service files or as parameters for `systemd-run`. There is only one exception I am aware of: `EnvironmentFile`. This property is printed in a non-parseable format (e.g. `EnvironmentFiles=/etc/default/foo (ignore_errors=yes)` instead of `EnvironmentFile=-/etc/default/foo`). This forces consumers of `systemctl show` to write custom translations.

Instead `systemd show` should use an output format that can be uses as an input for other systemd components without understanding the details of specific directives.

**Use case (long description)**
[munin](http://munin-monitoring.org) (a monitoring software) ships a tool `munin-run` that is supposed to execute plugins in the same environment, that is provided by the daemon `munin-node`. This worked well, as long as `munin-node` was started by a sysv-init scripts (i.e. without any hardening flags like `ProtectHome`). With the advent of hardening flags defined via systemd units, it is necessary for `munin-run` to simulate these restrictions as closely as possible. Thus `munin-run` recently started to use `systemctl show munin-node` for collecting all properties of the `munin-node` service. A selected set of properties is handed over to a `systemd-run` execution. This should ensure an environment that is very close to real environment used by the proper `munin-node` service.

**Comment by Salamandar** [comment]
This issue is marked as closed, but it is still present. Would it be possible to reopen the issue ? (Reproduced with v252 on Debian and 257 on Manjaro)
