### ISSUE TITLE
systemctl --host=... status foo.service breaks terminal without dbus

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#14729]
**systemd version the issue has been seen with**

v244

Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905024

When invoking:

```
  # systemctl --host=... status ssh.service
```
then the terminal kind of breaks, if dbus isn't present at the remote host.
For example if `PermitRootLogin yes` is set in sshd_config
and trying to connect to the local system *without* dbus being
present I get:

  root@debian-sid01:~# systemctl --host=$(hostname) status ssh.service
  root@debian-sid01's password:
  root@debian-sid01:~# root@debian-sid01:~#·root@debian-sid01:~#·root@debian-sid01:~#·root@debian-sid01:~#·

So whenever pressing the <enter> key the prompt gets worse (and only
a `reset` fixes that). :) As soon as dbus is present/available it
works as intended though.

This is quite irritating, not even getting an error/warning message.

I get the following error messages on the remote host:

```
Feb 01 05:02:56 debian systemd-stdio-bridge[548]: Failed to start bus client: No such file or directory
Feb 01 05:02:56 debian sshd[547]: Received disconnect from 192.168.122.1 port 35596:11: disconnected by user
```

The systemctl man page, specifically the --host parameter should probably be updated, saying that this feature requires dbus on the remote host.

systemctl on the local host should also deal with this more gracefully and not mess up the terminal and ideally provide a proper error message.

**Comment by yuwata** [comment]
The same happens when `machinectl --host root@localhost`. And setting `--no-pager` works fine. Maybe, we should update `pager_close()` or so.
