### ISSUE TITLE
RFE: systemd-resolved allow whitelisting domains for mDNS scope

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#14735]
I am using systemd-resolved as a system mdns resolver/responder and it works well. However, using mDNS scope has some unintended side effect for me that could probably be improved.

For example:

```
$ time ping -4 -c1 google.com
PING google.com (216.239.32.117) 56(84) bytes of data.
[...]
ping -4 -c1 google.com  0.00s user 0.00s system 0% cpu 10.005 total
```

It takes 10 seconds for a `ping google.com` to respond :/. It's kind of obvious in retrospect, but the delay here isn't the google.com lookup – that's served by DNS – but the _reverse_ name lookup ping does. I have mDNS scope enabled for this link:

```
$ resolvectl status wlp2s0
Link 3 (wlp2s0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6 mDNS/IPv4 mDNS/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: yes
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 10.1.0.253
         DNS Servers: 10.1.0.253
          DNS Domain: home
```

It doesn't find a PTR in DNS, so resolved continues with mDNS. It obviously doesn't find an answer, but does delay the lookup for ~7-10 seconds. Here's a log of sd-resolved's attempts to answer 117.32.239.216.in-addr.arpa IN PTR:

<details>
<summary>systemd-resolved log</summary>

```
Jan 31 12:48:50 systemd-resolved[82082]: Looking up RR for 117.32.239.216.in-addr.arpa IN PTR.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 46310 for <117.32.239.216.in-addr.arpa IN PTR> scope dns on */*.
Jan 31 12:48:50 systemd-resolved[82082]: Using feature level UDP+EDNS0 for transaction 46310.
Jan 31 12:48:50 systemd-resolved[82082]: Using DNS server 1.1.1.1 for transaction 46310.
Jan 31 12:48:50 systemd-resolved[82082]: Sending query packet with id 46310.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 35435 for <117.32.239.216.in-addr.arpa IN PTR> scope dns on wlp2s0/*.
Jan 31 12:48:50 systemd-resolved[82082]: Using feature level UDP+EDNS0 for transaction 35435.
Jan 31 12:48:50 systemd-resolved[82082]: Using DNS server 10.1.0.253 for transaction 35435.
Jan 31 12:48:50 systemd-resolved[82082]: Sending query packet with id 35435.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 38738 for <117.32.239.216.in-addr.arpa IN PTR> scope llmnr on wlp2s0/INET.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 44396 for <117.32.239.216.in-addr.arpa IN PTR> scope mdns on wlp2s0/INET.
Jan 31 12:48:50 systemd-resolved[82082]: Processing incoming packet on transaction 35435 (rcode=NXDOMAIN).
Jan 31 12:48:50 systemd-resolved[82082]: Added NXDOMAIN cache entry for 117.32.239.216.in-addr.arpa IN ANY 9s
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 35435 for <117.32.239.216.in-addr.arpa IN PTR> on scope dns on wlp2s0/* now complete with <rcode-failure> from network (unsigned).
Jan 31 12:48:50 systemd-resolved[82082]: Processing incoming packet on transaction 46310 (rcode=NXDOMAIN).
Jan 31 12:48:50 systemd-resolved[82082]: Added NXDOMAIN cache entry for 117.32.239.216.in-addr.arpa IN ANY 60s
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 46310 for <117.32.239.216.in-addr.arpa IN PTR> on scope dns on */* now complete with <rcode-failure> from network (unsigned).
Jan 31 12:48:50 systemd-resolved[82082]: Timeout reached on transaction 38738.
Jan 31 12:48:50 systemd-resolved[82082]: Retrying transaction 38738.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 38738 for <117.32.239.216.in-addr.arpa IN PTR> scope llmnr on wlp2s0/INET.
Jan 31 12:48:50 systemd-resolved[82082]: Timeout reached on transaction 44396.
Jan 31 12:48:50 systemd-resolved[82082]: Retrying transaction 44396.
Jan 31 12:48:50 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 44396 for <117.32.239.216.in-addr.arpa IN PTR> scope mdns on wlp2s0/INET.
Jan 31 12:48:50 systemd-resolved[82082]: Transaction 38738 for <117.32.239.216.in-addr.arpa IN PTR> on scope llmnr on wlp2s0/INET now complete with <not-found> from none (unsigned).
Jan 31 12:48:51 systemd-resolved[82082]: Timeout reached on transaction 44396.
Jan 31 12:48:51 systemd-resolved[82082]: Retrying transaction 44396.
Jan 31 12:48:51 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:51 systemd-resolved[82082]: Transaction 44396 for <117.32.239.216.in-addr.arpa IN PTR> scope mdns on wlp2s0/INET.
Jan 31 12:48:53 systemd-resolved[82082]: Timeout reached on transaction 44396.
Jan 31 12:48:53 systemd-resolved[82082]: Retrying transaction 44396.
Jan 31 12:48:53 systemd-resolved[82082]: Cache miss for 117.32.239.216.in-addr.arpa IN PTR
Jan 31 12:48:53 systemd-resolved[82082]: Transaction 44396 for <117.32.239.216.in-addr.arpa IN PTR> scope mdns on wlp2s0/INET.
Jan 31 12:48:57 systemd-resolved[82082]: Timeout reached on transaction 44396.
Jan 31 12:48:57 systemd-resolved[82082]: Retrying transaction 44396.
Jan 31 12:48:57 systemd-resolved[82082]: Transaction 44396 for <117.32.239.216.in-addr.arpa IN PTR> on scope mdns on wlp2s0/INET now complete with <attempts-max-reached> from none (unsigned).
Jan 31 12:48:57 systemd-resolved[82082]: Freeing transaction 46310.
Jan 31 12:48:57 systemd-resolved[82082]: Freeing transaction 35435.
Jan 31 12:48:57 systemd-resolved[82082]: Freeing transaction 38738.
Jan 31 12:48:57 systemd-resolved[82082]: Freeing transaction 44396.
```
</details>

The failure isn't cached either, so subsequent ping attempts take just as long.

Now most the time there is a PTR record in DNS so this doesn't always happen, but it happens often enough. I know I can just `-n` but the point is the behavior is inconvenient for more than just `ping`. The real "issue" is that I don't think I ever want to forward non-local .in-addr.arpa. to mDNS scope, but as far as I know there is no way to configure sd-resolved for that.

**Describe the solution you'd like**
nss-mdns handles this in mdns_minimal for example, which only queries .local on mDNS but passes on other TLDs. I think that's a much more useful setup for the casual user and it would be nice if resolved could do the same.

It would be best I think if there was a way to configure a whitelist of domains for the mDNS scope on a link. I could be a plain and simple whitelist, or maybe something like `MulticastDomains=local ~mylocal` in parallel to `Domains=`. So in that case it could have multicast search domains and multicast route-only domains, except in this case they're exclusive to mDNS scope.

There is already some similar logic in resolved-dns-scope.c from 1750854 that special cases local and local reverse mapping domains to _prefer_ mDNS scope. With this proposal the user-configurable `MulticastDomains=` (for which the local and local reverse mapping domains would be a very sensible default value) would keep the default behavior for those domains, and mDNS scope would not be considered for all other domains. So in parallel to `Domains=`, in this case I guess a value of `MulticastDomains=~.` would be equivalent to the current behavior, and a value of `MuticastDomains=local` would add local as a search domain but queries formed by concatenating a local suffix would only be fulfilled by mDNS (unless local is also a `Domains` search domain). Does that make sense? I suppose some similar logic would probably be needed for LLMNR in this case, but I know very little about LLMNR so forgive me for not expanding there.

Regarding adding scope specific search lists, [RFC 6762](https://tools.ietf.org/html/rfc6762#section-3) has this to say about .local as a search domain:
> It is unimportant whether a name ending with ".local." occurred because the user explicitly typed in a fully qualified domain name ending in ".local.", or because the user entered an unqualified domain name and the host software appended the suffix ".local." because that suffix appears in the user's search list.  The ".local." suffix could appear in the search list because the user manually configured it, or because it was received via DHCP [RFC2132] or via any other mechanism for configuring the DNS search list.  In this respect the ".local." suffix is treated no differently from any other.

But if I'm reading resolved-dns-scope.c correctly, configuring local as a search domain currently does have the effect of permitting local to be resolved via DNS. The RFC allows us to resolve .local however we like in addition to mDNS, but I think with this proposal `MulticastDomains=local` comes closer to the RFCs meaning in that local could be placed on a search list without changing the behavior of name resolution for .local names. If that matters.

Thanks for reading my long post. Let me know what you think.

**Describe alternatives you've considered**
Disable mDNS scope or use an alternative mDNS resolver.

**Comment by kmarty** [comment]
Totally agree.
It took me several hours to find why it criples resolving and creates delays.
Even “stub-resolv.conf” and “nss-resolve” is useless, it corrupts mdns (it somehow precedes mdns queries, tries to resolve using dns and return as non-existing names).
As it is now, it is better for me to completely avoid systemd-resolved for anything than creating  /run/systemd/resolve/resolv.conf and for working mdns, even for basics, run avahi-daemon with “nss-mdns”.
