### ISSUE TITLE
MACAddressPolicy=persistent doesn't work with VFs in virtual machines

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#14744]
**Steps to reproduce**

On a KVM installation build out multiple VMs and assign an SRIOV VF to each newly created VM.
Ensure the iavf driver is installed inside the VM and bound to the VF passed through to the VM.
Note the MAC addresses assigned to each VM's SRIOV VF.

**Actual results**

All VMs are created with an identical MAC address assigned to the VF. 

**Expected results**

All SRIOV VFs have a unique MAC address assigned.

**Additional info**

Originally implemented in https://github.com/systemd/systemd/commit/16b9b87aeee9353b5b8dae6089a69752422a5b09

**Comment by yuwata** [comment]
I guess each VM has the same /etc/machine-id. The MAC address is generated from the machine-id. So, if you share the machine-id, then the generated MAC addresses are equivalent.

**Comment by jsynacek** [comment]
Also see original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1751174

**Comment by jsynacek** [comment]
> I guess each VM has the same /etc/machine-id. The MAC address is generated from the machine-id. So, if VMs share the machine-id, then the generated MAC addresses are equivalent.

So my guess is that the logic should be extended to also consider any virtual functions that might be present.

**Comment by yuwata** [comment]
But changing the logic causes MAC address change... It is not acceptable I think.
We already depend on the fact that machine-id is unique at many places. I think it is documented somewhere.

**Comment by yuwata** [comment]
The original issue is already closed. Let's also close this.
