### ISSUE TITLE
systemd-tmpfiles fails without mounted /proc

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#14745]
**systemd version the issue has been seen with**

v244.1

We recently enabled persistent journal in Debian.
For that we run in postinst
```
mkdir -p /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
```
This fails in a chroot though:
```
[/usr/lib/tmpfiles.d/systemd-tmp.conf:11] Failed to replace specifiers: /tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/systemd-tmp.conf:12] Failed to replace specifiers: /tmp/systemd-private-%b-*/tmp
[/usr/lib/tmpfiles.d/systemd-tmp.conf:13] Failed to replace specifiers: /var/tmp/systemd-private-%b-*
[/usr/lib/tmpfiles.d/systemd-tmp.conf:14] Failed to replace specifiers: /var/tmp/systemd-private-%b-*/tmp
[/usr/lib/tmpfiles.d/systemd-tmp.conf:22] Failed to replace specifiers: /var/lib/systemd/coredump/.#core*.%b*
ACL operation on "/var/log/journal" failed: No such file or directory
ACL operation on "/var/log/journal" failed: No such file or directory
Failed to re-open '/var/log/journal': No such file or directory
fchmod() of /var/log/journal failed: No such file or directory
```

The error message is misleading. /var/log/journal does exist and what is failing instead is that  chown_one() requires a mounted /proc
```
getxattr("/proc/self/fd/4", "system.posix_acl_access", 0x7ffc2fdcc8c0, 132) = -1 ENOENT (No such file or directory)
writev(2, [{iov_base="ACL operation on \"/var/log/journ"..., iov_len=69}, {iov_base="\n", iov_len=1}], 2ACL operation on "/var/log/journal" failed: No such file or directory
```

**Comment by mbiebl** [comment]
Aside from improving the error message, would it possible to handle this situation more gracefully?
I don't mean silently skipping applying of ACLs, which wouldn't be great either.
But maybe it's possible to not require a mounted proc for systemd-tmpfiles?

**Comment by fsateler** [comment]
AFAICT, proc is only used for removexattr. Could it be replaced with fremovexattr?

**Comment by poettering** [comment]
hmm, is there really a need to do anything about this? /proc is API, if you don#t mount it everything fails, that not new. I am not sure it's too much to expect that /proc is pre-mounted, everyone knows that...

tmpfiles works fine in a chroot, however people need to prepare the chroot to have proc mounted... that's not specific to this tool, that's universially true...

**Comment by poettering** [comment]
See #15564. It doesn't add an explicit error message, but it avoids the confusing ENOENT in these cases. 

Still: if you set up a borked chroot env like this, it's your own fault if cryptic stuff fails, and I think we can live with that. Don't set up stuff like this if you are not prepared for cryptic errors.

I mean, it's good to know we don't segfault or so in this case...

**Comment by mikhailnov** [comment]
Oh, "Failed to replace specifiers" means that /proc is needed? That is definitely VERY measleading, it makes think that there is a syntax error.

**Comment by poettering** [comment]
btw, we use /proc for a lot more than the ACL stuff, i.e. after following symlink chains via O_PATH fds we need to convert the fds back to something real, for which we use /proc/self/fd/.

That's at least the acl stuff, the xattr stuff, the chattr stuff, anything of the recursive stuff, the AF_UNIX collision checks, the protected hardlinks detection logic, the btrfs subvol stuff, the adjusting of access modes.

We also use /proc to resolve %b, to ensure the stuff we create has the right selinux label, or to fix such labels.

Or in othe words: there's only a tiny subset of operations where we do not require /proc.

It's simply illusionary for a non-trivial program on Linux to operate without /proc, and I doubt it's worth making any effort to have fallbacks for any of this.

I think the only fair solution here is to add a check early on that ensures people don't accidentally run into this. i.e. a helpful check that just says "I am sorry, but you need to mount /proc/. If you operate on a OS tree, consider using --image= or --root=." is the best way.

**Comment by mikhailnov** [comment]
10.02.2021 19:04, Lennart Poettering пишет:
> I think the only fair solution here is to add a check early on that ensures people don't accidentally run into this. i.e. a helpful check that just says "I am sorry, but you need to mount /proc/. If you operate on a OS tree, consider using --image= or --root=." is the best way.
+1
