### ISSUE TITLE
restarting networkd returns too soon

### ISSUE THREAD

**Issue by plmuon** [systemd/systemd#14748]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > fedora & arch

**Expected behaviour you didn't see**
 > after modifying a file in /etc/systemd/network and restarting system-networkd, the new config is active

**Unexpected behaviour you saw**
 > it takes a few milliseconds before it is active

**Steps to reproduce the problem**
Note: not sure whether this should be consdiered a bug or a feature request.
I need some way to modify systemd-networkd config and be sure that the change is effective before going on.

For an interface, modify the MTU from 2000 to 1900 (just an example) in the config file.
Then:

$ systemctl restart systemd-networkd; ip a show eno1
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2000 qdisc fq_codel state UP group default qlen 1000
    link/ether 54:bf:64:6a:59:10 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::56bf:64ff:fe6a:5910/64 scope link 
       valid_lft forever preferred_lft forever

A fraction of a second later:
$ ip a show eno1
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1900 qdisc fq_codel state UP group default qlen 1000
    link/ether 54:bf:64:6a:59:10 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::56bf:64ff:fe6a:5910/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by yuwata** [comment]
I guess `systemd-networkd-wait-online` may help you.

**Comment by yuwata** [comment]
And the behavior is intended. Sorry. Closing.

**Comment by floppym** [comment]
> I need some way to modify systemd-networkd config and be sure that the change is effective before going on.

Maybe waiting for `networkctl reconfigure eno1` would do the trick?

**Comment by plmuon** [comment]
Thanks floppym. Doesn't work alas, and neither does systemd-networkd-wait-online because we can have various operational states and don't care. We have systems with many interfaces, we just need to know when the reconfiguation of MTU or other settings is effective, no matter what the network state is.

For the time being, we'll just pause after restarting systemd-networkd.

**Comment by yuwata** [comment]
`wait-online` has `-i` option to chose which interface to be configured. Still I believe `wait-online` can help you, rather than `sleep`.

**Comment by plmuon** [comment]
I tried the various options of /usr/lib/systemd/systemd-networkd-wait-online (interactively calling it directly after systemctl restart systemd-networkd), but the problem was that we don't have a carrier always. I know the use case is obscure, I think I'll change my code to poll on the client side until we observe the change directly. Thanks for your suggestions and help.
