### ISSUE TITLE
systemd-tmpfiles --create failes with smt disabled

### ISSUE THREAD

**Issue by EDEADLINK** [systemd/systemd#14753]
**systemd version the issue has been seen with**
> v244
I have not seen it before, possible regression

**Used distribution**
 > Linux Arch 5.4.15-arch1-1

**Unexpected behaviour you saw**
 > running systemd-tmpfiles --create 
fails with:
```
Failed to write file "/sys/devices/system/cpu/cpufreq/policy6/energy_performance_preference": Invalid argument
Failed to write file "/sys/devices/system/cpu/cpufreq/policy4/energy_performance_preference": Invalid argument
Failed to write file "/sys/devices/system/cpu/cpufreq/policy7/energy_performance_preference": Invalid argument
Failed to write file "/sys/devices/system/cpu/cpufreq/policy5/energy_performance_preference": Invalid argument
```
I have a 4 core 8 thread cpu and boot with nosmt and thus use only 4 threads. While the files exist when smt is disabled trying to read one of those files fails with "No such device or address" see:
```
cat: /sys/devices/system/cpu/cpufreq/policy7/energy_performance_preference: No such device or address
```
I do not understand is why modifying energy_performance_preference is necessary in the first place but systemd-tmpfiles should not fail to create tmpfiles because of it, right?

**Steps to reproduce the problem**
1. boot with kernel with the parameter nosmt. Or disable smt through /sys/devices/system/cpu/smt/control. Using a kernel with CONFIG_HOTPLUG_SMT=y on a machine with SMT.
2. run /usr/bin/systemd-tmpfiles --create

**Workaround**
Enabling smt before running systemd-tmpfiles --create fixes the issue.

**Comment by yuwata** [comment]
Could you check which .conf file provide the setting? We do not provide such setting...

**Comment by DeadLink404** [comment]
Woops.
It appears /etc/tmpfiles.d/energy_performance_preference.conf
is the issue but it isn't owned by any package so the culprit is probably me.

It contains:
```
w /sys/devices/system/cpu/cpufreq/policy?/energy_performance_preference - - - - power
```
Is it possible to make this work with smt on or off or should I just delete this?

**Comment by yuwata** [comment]
Instead of using systemd-tmpfiles, you should use udev .rules file for such a purpose, I think.

Anyway, here is not a support forum. Please use our mailing list. Sorry.
