### ISSUE TITLE
Udev cannot send udp networkpaket

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14756]
I have a problem with a udev rule. I use Raspbian Buster with Kernel 4.19.93-v7+ #1290. At first, if i execute the script manually it works. The udev rule also execute the script, but abort when to send a upd paket. (I will send a upd paket to localhost which a other programm register) Here is the working Script with debugging-Code:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

# Import der 
notwendigen Bibliotheken
import os
import sys
import getpass
import socket

f = open('/home/pi/scripts/keypad/client.txt','a')
f.write('Starting Script from Udev-Rule as user: ')
f.write(str(getpass.getuser()))
#f.write('\n')
f.close()

try:
    # Serververbindung öffnen, an Port binden und auf Lauschen stellen
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.sendto('1', ('127.0.0.1', 50000))
except:
    f=open('/home/pi/scripts/keypad/client.txt','a')
    f.write('\n')
    f.write(str(sys.exc_info()[0]))
    f.write(str(sys.exc_info()[1]))
    f.write(str(sys.exc_info()[2]))
    f.write('\n')
    f.close()

f = open('/home/pi/scripts/keypad/client.txt','a')
f.write('End of Script from Udev-Rule\n')
f.write('\n')
f.write('\n')
f.close()
```

If i but my device in the Rasbperry, the script will be excecuted and abort. Here you cann see what i am logging:

```
Starting Script from Udev-Rule as user: root
<class 'socket.error'>
[Errno 1] Operation not permitted
<traceback object at 0x76c36260>
End of Script from Udev-Rule
```

If i do this manually the script works perfect. I also tried to replace the code with a simply bash command "echo "1" | nc -w1 -u 127.0.0.1 50000" . But the result is the same. Manually works if udev execute its not working.

Has anyone an idea?

PS: If I use the Image from Homepage (September 2019) it works.

**Comment by yuwata** [comment]
I guess `RestrictAddressFamilies=` does not contain `AF_INET` and `AF_INET6`.

Please provide the result of `systemctl cat systemd-udevd.service`.

**Comment by Blackbox-git** [comment]
Thx for your Reply. Here is the output of the command.

What do I have to change to allow the sending of upd networkpakets? 

Do I have to change anything else at the point IPAddressDeny?

Are there any security gaps if i do this?


```[Unit]
Description=udev Kernel Device Manager
Documentation=man:systemd-udevd.service(8) man:udev(7)
DefaultDependencies=no
After=systemd-sysusers.service systemd-hwdb-update.service
Before=sysinit.target
ConditionPathIsReadWrite=/sys

[Service]
Type=notify
OOMScoreAdjust=-1000
Sockets=systemd-udevd-control.socket systemd-udevd-kernel.socket
Restart=always
RestartSec=0
ExecStart=/lib/systemd/systemd-udevd
KillMode=mixed
WatchdogSec=3min
TasksMax=infinity
PrivateMounts=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6
SystemCallArchitectures=native
LockPersonality=yes
IPAddressDeny=any
```

**Comment by yuwata** [comment]
Ah, I forgot `IPAddressDeby=`. Please try to disable the setting, by creating the following drop-in:
```
# /etc/systemd/system/systemd-udevd.service.d/override.conf
[Service]
IPAddressDeny=
```
For the security risk by disabling the setting, please read the man page systemd.resource-control(5).

**Comment by yuwata** [comment]
By the way, here is not a support forum, but a issue or RFE trucker. Please use our mailing list instead, sorry. This is not a bug.

**Comment by Blackbox-git** [comment]
I was not familiar with the settings in Systemd. So I thought it was a bug. Thanks for the help.

どうも 有難う 御座います

**Comment by yuwata** [comment]
どういたしまして。

**Comment by mbiebl** [comment]
This is more or less a duplicate of #7074 so you might find the referenced commit 695fe4078f0df6564a1be1c4a6a9e8a640d23b67 interesting
