### ISSUE TITLE
Systemd-resolved not starting

### ISSUE THREAD

**Issue by xeruf** [systemd/systemd#14766]
**systemd version the issue has been seen with**
> systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

I know this version is older, but I am not sure whether this is related to the version and where eactly to report this, because neither the Debian nor the Ubuntu bug reporting tools are available on my system.

**Used distribution**
 > KDE Neon

**Expected behaviour you didn't see**
 > I can access the internet normally

**Unexpected behaviour you saw**

When opening my browser, I got a `DNS_PROBE_FINISHED_BAD_CONFIG` error.
`ping example.com` 
```
ping: example.com: Temporary failure in name resolution
```

`journalctl -u systemd-resolved -f `
```
-- Logs begin at Thu 2019-06-27 13:49:00 CEST. --
Feb 04 11:45:49 pavilion-neon systemd[1]: Stopped Network Name Resolution.
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Failed to run 'start' task: No such file or directory
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Failed with result 'resources'.
Feb 04 11:45:49 pavilion-neon systemd[1]: Failed to start Network Name Resolution.
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Service has no hold-off time, scheduling restart.
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
Feb 04 11:45:49 pavilion-neon systemd[1]: Stopped Network Name Resolution.
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Start request repeated too quickly.
Feb 04 11:45:49 pavilion-neon systemd[1]: systemd-resolved.service: Failed with result 'resources'.
Feb 04 11:45:49 pavilion-neon systemd[1]: Failed to start Network Name Resolution.
```

`systemctl start systemd-resolved`
```
Job for systemd-resolved.service failed because of unavailable resources or another system error.
See "systemctl status systemd-resolved.service" and "journalctl -xe" for details.
```
`/lib/systemd/systemd-resolved`
```
Could not create runtime directory: No such file or directory
```
`sudo /lib/systemd/systemd-resolved` works and outputs this:
```
Positive Trust Anchors:
. IN DS 19036 8 2 49aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb5
. IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Using system hostname 'pavilion-neon'.
```
but after that it only puts the stub `nameserver 127.0.0.53` into my `/etc/resolv.conf`, which results in a `DNS_PROBE_FINISHED_BAD_CONFIG` as well.

There is enough free disk space
For now the only way for me to connect to the internet that works is to add `nameserver 1.1.1.1` manually to /etc/resolv.conf.

**Comment by Xerus2000** [comment]
This was somehow magically solved by removing the `resolvconf` package as mentioned here :sweat:  https://askubuntu.com/a/1164602/678543
