### ISSUE TITLE
network: Should we introduce .tc-qdisc file like .netdev?

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#14763]
We have already so many settings in `[TrafficControlQueueingDiscipline]` section, and it will be increased for a while. And each setting has verry long name which is almost redundant. 
So, Should we introduce .tc file like .netdev? I propose the following syntax:
```
# 10-netem.tc
[Match]
Name=eth0

[QueueingDiscipline]
Parent=root
Handle=ffff
Kind=netem

[NetworkEmulator]
DelaySec=1ms
DelayJitterSec=0.5ms
PacketLimit=1000
LossRate=1%
DuplicateRate=2%
```
In the previous release, we only have netem support if I remember correctly. So, I think we can change the setting now, and keeping backward compatibility is easy.
@ssahani and @keszybz WDYT?

**Comment by yuwata** [comment]
If we decided we should do so, then this must be done before v245.

**Comment by yuwata** [comment]
If I get positive comments about this, I will prepare a PR for this soon.

**Comment by yuwata** [comment]
Or, more simply, instead of introducing .tc file, how about to introduce sections named by their kind:
```
# 10-eth0.network
[Match]
Name=eth0

[NetworkEmulator]
Parent=root
Handle=ffff
DelaySec=1ms
DelayJitterSec=0.5ms
PacketLimit=1000
LossRate=1%
DuplicateRate=2%
```

**Comment by keszybz** [comment]
> Or, more simply, instead of introducing .tc file, how about to introduce sections named by their kind:

That looks much nicer to me. Introducing anther file type is a very "costly" operation, since knowledge about it must be added in many many places and tools. I think the named sections look very readable.

**Comment by ssahani** [comment]
I like it.

**Comment by yuwata** [comment]
@keszybz and @ssahani Thank you for the comments. I will prep a PR soon.
