### ISSUE TITLE
`test-network/test_altname` fails in the sanitizers job

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#14764]
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > Arch Linux (CentOS CI)

This is just a tracking issue, as @yuwata already knows about this (see https://github.com/systemd/systemd/pull/14758#issuecomment-581744046)

```
======================================================================
ERROR: test_altname (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 501, in test_altname
    self.wait_online(['dummy98:degraded'])
  File "test/test-network/systemd-networkd-tests.py", line 448, in wait_online
    check_output(*args, env=env)
  File "test/test-network/systemd-networkd-tests.py", line 47, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/build/build/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']' returned non-zero exit status 1.
```

Other known occurrences:
 - https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/3770/artifact//systemd-centos-ci/index.html
 - https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/3769/artifact//systemd-centos-ci/index.html
 - https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/3768/artifact//systemd-centos-ci/index.html
 - etc.

**Comment by yuwata** [comment]
@mrc0mmand Could you give me the version of kernel and iproute2?

**Comment by mrc0mmand** [comment]
```
linux 5.5.1.arch1-1
iproute2 5.5.0-1
```

(taken from https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/3768/artifact//systemd-centos-ci/artifacts_all/artifacts_nOcHOo/vagrant-logs.Kbb/vagrant-arch-sanitizers-gcc-installed-pkgs.txt)

**Comment by yuwata** [comment]
Thanks!

**Comment by yuwata** [comment]
@mrc0mmand I guess that `udevd` in the test environment is old (not built from the PR). Is it true?

Is it possible to get full journal log when running the networkd tests?

**Comment by mrc0mmand** [comment]
> @mrc0mmand I guess that `udevd` in the test environment is old (not built from the PR). Is it true?

That's possible, since we don't install any compiled binaries, as they're all built with sanitizers, which may compromise system stability

> Is it possible to get full journal log when running the networkd tests?

https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/3768/artifact//systemd-centos-ci/artifacts_all/artifacts_nOcHOo/vagrant-logs.Kbb/vagrant-arch-sanitizers-gcc-testsuite.3c3/journalctl-testsuite_PASS.log

**Comment by yuwata** [comment]
Bingo!
```
Feb 04 06:32:07 arch.localdomain systemd-udevd[347]: /run/systemd/network/12-dummy.link:5: Unknown key name 'AlternativeName' in section 'Link', ignoring.
```

**Comment by mrc0mmand** [comment]
Hm, I see. What would be the best solution here? We can't install just `systemd-udevd`, as we'd be mixing insturmented & uninstrumented code (and code from different systemd versions). Also, installing the entire systemd build is also out of the question, as any PID1 reload/reexec could crash the SUT.
