### ISSUE TITLE
flag `-n` conflicts with `--since` in journalctl

### ISSUE THREAD

**Issue by yifan-gu** [systemd/systemd#1477]
I found that `journalctl -n` shows the **n most recent** logs, while `journalctl -n --since=xx` shows the **n oldest** logs. 
For example:

``` shell
$ sudo journalctl -m _HOSTNAME=rkt-a5a9c273-0ba1-47e2-b12c-7fc4accd790d -n 10 --since=2015-10-06 --output cat
Runtime journal is using 8.0M (max allowed 383.7M, trying to leave 575.6M free of 3.7G available → curren
Permanent journal is using 8.0M (max allowed 4.0G, trying to leave 4.0G free of 172.1G available → curren
Time spent on flushing to /var is 788us for 2 entries.
Journal started
hello 0
hello 1
hello 2
hello 3
hello 4
hello 5
lines 1-10/10 (END)
```

``` shell
$ sudo journalctl -m _HOSTNAME=rkt-a5a9c273-0ba1-47e2-b12c-7fc4accd790d -n 10 --output cat
hello 856
hello 857
hello 858
hello 859
hello 860
hello 861
hello 862
hello 863
hello 864
Journal stopped
```

systemd version 219.

``` shell
$ journalctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

Not sure if that's fixed in the master, if so I will close the issue :)

/cc @alban @jonboulle @iaguis

**Comment by iaguis** [comment]
FWIW this happens on systemd v226 too.

**Comment by dongsupark** [comment]
Isn't `journalctl -n 10 -r --since=xx` probably what you actually want to do?
I agree that it's confusing, but it looks like users are expected to explicitly give an `-r` option to print out the most recent logs. It's just like the case of `journalctl -n 10 -r --until=xx`.

**Comment by yifan-gu** [comment]
> Isn't journalctl -n 10 -r --since=xx probably what you actually want to do?
> I agree that it's confusing, but it looks like users are expected to explicitly give an -r option to print out the most recent logs. It's just like the case of journalctl -n 10 -r --until=xx.

I don't understand what's the reason for changing the behavior of `-n` when `--since` is applied? And I can't find related docs to notice users about this.

**Comment by YHNdnzj** [comment]
Fixed by https://github.com/systemd/systemd/pull/26669.
