### ISSUE TITLE
Configure Flow Control in .link

### ISSUE THREAD

**Issue by LemonIceScream** [systemd/systemd#14770]
**Is your feature request related to a problem? Please describe.**
I am unable to configure flow control parameters on an interface using networkd.

I am using networkd to configure a Mellanox switch whose hardware is configured by [switchdev](https://github.com/mellanox/mlxsw/wiki), a kernel module. These switches are big on zero packet loss / lossless Ethernet and is achieved by relying on flow control. Any network OS built on top of Mellanox and switchdev should take flow control into consideration and not leave it to defaults.

Since networkd doesn't offer this functionality I have to fallback to calling `ethtool --pause` manually via a NixOS activiation script.

**Describe the solution you'd like**
I believe networkd is a more suitable place to put the configuration and would like to see flow control configure options in .link files that calls `ethtool --pause` for me.

Example systemd.link options:
```
FlowControl=
Takes a value of "both" to enable flow control for both receive and transmit, "rx" for receive only, "tx" for transmit only, or "off" to disable flow control entirely. When unset the kernel's default will be used.
```

Or:
```
FlowControlRx=, FlowControlTx=
Takes a boolean. If set to yes enables flow control for the specified direction: receive or transmit. When unset the kernel's default will be used.
```

**Describe alternatives you've considered**
As a temporary workaround I am using an activation script that just sets the desired values on each interface. This occurs every time I switch configuration or at boot. I have also considered udev rules. However:

1) I'd rather networkd exclusively configure all interfaces.
2) It's hard to find related information about flow control since it's in a lot of network debug messages.
3) While flow control is generally considered an afterthought along the lines of "don't use it", it's important consideration for use-case.

**Comment by ssahani** [comment]
Sure rfc

**Comment by yuwata** [comment]
If you'd like, please test #14821.

**Comment by LemonIceScream** [comment]
That was an impressive turnaround -- thank you.

I haven't been able to test this in my environment. I'm running NixOS where everything needs to be installed to a path under /nix/store. They've [forked systemd](https://github.com/NixOS/systemd/tree/nixos.v243.4) likely to keep track of Nix-specific patches but they're only at v243. I can get the patches to apply with `-F 3` but it doesn't compile. I've tried compiling from the systemd repository instead but this tries to write to paths not under /nix/store so it fails.

So I don't have a way to test this in my set up. Sorry!

**Comment by software011** [comment]
Hola comparto en este hilo, lo siguiente [https://sites.google.com/aprendizajesignificativo.org/dibujo-g/p%C3%A1gina-principal](url) , que los dirige a un articulo de asesoramiento e informacion para las personas amantes del dibujo y no tienen claro que desean estudiar en la universidad.

**Comment by kevin839** [comment]
Tal vez has escuchado la marca de ropa Chanel, pero detrás de esto hay una historia de una mujer que es muy importante en el mundo del Diseño de modas. 

https://sites.google.com/aprendizajesignificativo.org/modas/p%C3%A1gina-principal
