### ISSUE TITLE
homed: change the term "home" for "user space" in 12 labels

### ISSUE THREAD

**Issue by dmedri** [systemd/systemd#14789]
homed introduced new labels and almost all of these use the term "home".

e.g.
"Create a home"
"Resize a home"

While the term has a fundamental/historical role in Unix Oses, it's a bit ambigous, especially when translated in different languages. The term "user space" could be a solution, maintaining the HOME concept as is.

The resulting 12 labels:

"Create a user space"
"Remove a user space"
"Check credentials of a user space"
"Update a user space"
"Resize a user space"
"Change password of a user space"
"Authentication is required for creating a user space."
"Authentication is required for removing a user space."
"Authentication is required for checking credentials against a user space."
"Authentication is required for updating a user space."
"Authentication is required for resizing a user space."
"Authentication is required for changing the password of a user space."

Option: a "(home)" reference nearby, eg. "Create a user space (home)".

**Comment by keszybz** [comment]
"user space" is also very easy to confuse with a "user namespace". Maybe "user home space"?

**Comment by cdown** [comment]
"user space" also has a very well defined meaning, meaning "userspace code" :-)

I agree with @keszybz's suggestion.

**Comment by yuwata** [comment]
Still I have not followed what homed is in detail. But what is the difference between 'home space' and 'home directory'?

**Comment by keszybz** [comment]
The issue is that it's not necessarily an actual directory. It can also be a loopback file or a separate partition. Calling it a home *directory* would be misleading.

**Comment by yuwata** [comment]
I see. Thanks.

**Comment by boucman** [comment]
"home area" ? 
it carries the keyword "home" that is well known and it also carries the idea of "some space of some sort" without using a word like directory

**Comment by dmedri** [comment]
@cdown @keszybz "in user space" could be a strictly developer concept IMHO.

What about  "a user space (home)"?

**Comment by yuwata** [comment]
+1 for 'home area'.

**Comment by anitazha** [comment]
Also +1 for "home area".
It's a bit more concise than "user home space". And "area" is a bit less used in this domain so we can define it however we want.

**Comment by dmedri** [comment]
"home area" has the same initial problem. Please, reread this thread.

Using "in user space (home)" could be translated in:

italian: "nello spazio utente (home)"
spanish: "en el espacio del usuario (home)"
...and so on.

+3

**Comment by boucman** [comment]
user-space is really a term we can't use. it has too much meaning attached to it. especially for a software like systemd that deals a lot with the userspace/kernelspace frontier.

It's impossible to account for every language around so we need to provide a term as clear as possible in english and hope that translators are creative when they translate.

Using a new term means that translator will stop and think on it, creating a new term in the target language

Using a term with a meaning attached (like user-space) will actually do more bad than good since translator will use the accepted translation for the user-space concept, which is not what we want.

I still think home area is better than user-space

**Comment by matthewwardrop** [comment]
My 2c: As an outside observer and user, "user filesystem" seems intuitive to me.

**Comment by poettering** [comment]
> The issue is that it's not necessarily an actual directory. It can also be a loopback file or a separate partition. Calling it a home directory would be misleading.

Inside of these loopback filesystems there's always a directory and from the logged in user's PoV that's the primary concept visible. So i think directory is not that bad, but then again it appears to me people want to get away from the "directory" terminology in general in favour of "folder" or so. Hence maybe "home folder" would work? "home space" sounds ok to me too.

**Comment by poettering** [comment]
Home area is also fine by me.
