### ISSUE TITLE
Support the trivial link equalizer (teql) scheduler

### ISSUE THREAD

**Issue by tomhughes** [systemd/systemd#14792]
**Is your feature request related to a problem? Please describe.**

I use the trivial link equalizer scheduler to load balance traffic over two interfaces and this is the last thing that I have to use ppp up/down scripts for and as `systemd-networkd` is now busy gaining support for configuring traffic schedulers it would be nice if it could take care of this.

**Describe the solution you'd like**

I would like to be able to configure an interface to use the `teql` scheduler in a `.network` unit file - to have it do the equivalent of:

```
tc qdisc add dev <interface> root teql<N>
```

when an interface appears, for a specified value of `N`.

**Describe alternatives you've considered**

Currently I use a pppd pre-up script to run the above command.

**Comment by yuwata** [comment]
How to introduce teql<N> rather than teql0? `modprobe sch_teql` always creates `teql0`.

**Comment by tomhughes** [comment]
Yes that's the only tricky bit - you have to have already loaded the module... You can also create an alias in modprobe.d like this:

```
alias sch_teql* sch_teql
```

and then it will load automatically, though only `teql0` will be available the `max_equalizers` module parameter is set.
