### ISSUE TITLE
Broken build (undefined reference to `pthread_sigmask')

### ISSUE THREAD

**Issue by Werkov** [systemd/systemd#14793]
**systemd version the issue has been seen with**
> v245-rc1

**Used distribution**
> openSUSE Leap 15.1
> rpm -q meson glibc gcc ninja
> meson-0.46.0-lp151.4.1.noarch
> glibc-2.26-lp151.18.7.x86_64
> gcc-7-lp151.3.5.x86_64
> ninja-1.8.2-lp151.2.5.x86_64

**Expected behaviour you didn't see**
Succesfull build from sources.

**Unexpected behaviour you saw**
```
FAILED: test-dlopen
ccache cc  -o test-dlopen 'test-dlopen@exe/src_test_test-dlopen.c.o' 'test-dlopen@exe/src_libsystemd_disable-mempool.c.o' -Wl,--no-undefined -Wl,--as-nee
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: src/basic/libbasic.a(signal-util.c.o): in function `signal_is_blocked':
/projects/systemd-dev-group-slice/build/../src/basic/signal-util.c:295: undefined reference to `pthread_sigmask'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: src/basic/libbasic.a(random-util.c.o): in function `initialize_srand':
/projects/systemd-dev-group-slice/build/../src/basic/random-util.c:321: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
[72/902] Compiling C object 'systemd@exe/src_core_main.c.o'.
ninja: build stopped: subcommand failed.
```

```
FAILED: test-bus-error
ccache cc  -o test-bus-error 'test-bus-error@exe/src_libsystemd_sd-bus_test-bus-error.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -fs
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: src/basic/libbasic.a(signal-util.c.o): undefined reference to symbol 'pthread_si
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Steps to reproduce the problem**
Build with tests.

**Workaround**
I can work this around by [adding direct reference to libpthread](https://github.com/Werkov/systemd/commit/d224dcb3f976a7e91f58bb87691ecf7d0b3dc270) but I assume proper fix would be better dependency added to `libbasic`, however, it's beyond my meson skill. (Also, I didn't check whether the functions are really used in the resulting binaries, so it may be just too eager linker reporting.)

**Comment by keszybz** [comment]
You have a very old meson, can you try with a newer one? Also, please post the full configuration line and the actual non-truncated cc call.

**Comment by Werkov** [comment]
So it's indeed a likely meson bug. I can build successfully after upgrading to meson-0.53.1-160.d_t_b.1.noarch. Closing as resolved.

(Didn't notice the cropped paste, sorry about that.)
