### ISSUE TITLE
systemd 245-rc1 reports "Repartition Root Disk" failure

### ISSUE THREAD

**Issue by FireBurn** [systemd/systemd#14804]
**systemd version the issue has been seen with**
> 245-rc1

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

Feb 06 10:58:00 axion systemd[1]: systemd-repart.service: Main process exited, code=exited, status=1/FAILURE
Feb 06 10:58:00 axion systemd[1]: systemd-repart.service: Failed with result 'exit-code'.
Feb 06 10:58:00 axion systemd[1]: Failed to start Repartition Root Disk.
[journalctl.zip](https://github.com/systemd/systemd/files/4164706/journalctl.zip)

This is an auto started new service, I'm not sure if it should be a concern or not
**Steps to reproduce the problem**

**Comment by yuwata** [comment]
Could you provide the debugging log of the service?

**Comment by FireBurn** [comment]
How do I do that sorry?

**Comment by yuwata** [comment]
Please create the following drop-in file:
```
# /etc/systemd/system/systemd-repart.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by yuwata** [comment]
Do you use initrd which contains systemd-repart.service? If so, which directory is used to mount '/'? Currently, systemd-repart assumes '/sysroot' is used.

**Comment by FireBurn** [comment]
I don't use an initrd

I don't think adding that file gave any extra info
[journalctl.zip](https://github.com/systemd/systemd/files/4164885/journalctl.zip)

**Comment by FireBurn** [comment]
I use a small self contained kernel which is booted directly from efi (efi-stub)

My kernel config is here:

https://github.com/FireBurn/KernelStuff/blob/master/dot_config_adg5f

**Comment by yuwata** [comment]
Please provide
- kernel command line
- /proc/mounts
- fdisk -l

**Comment by FireBurn** [comment]
`Kernel command line: root=/dev/nvme0n1p2 rootfstype=ext4 libahci.ignore_sss=1 init=/usr/lib/systemd/systemd systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all psmouse.synaptics_intertouch=1 mitigations=off mds=off pti=off spectre_v2=off l1tf=off nospec_store_bypass_disable printk.devkmsg=on`

```
/dev/root / ext4 rw,noatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=16369776k,nr_inodes=4092444,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=52 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
none /var/tmp/portage tmpfs rw,noatime,size=24557908k 0 0
/dev/nvme0n1p1 /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/nvme0n1p3 /home ext4 rw,noatime,stripe=32750 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=3274384k,mode=700,uid=1000,gid=100 0 0
```

```
Disk /dev/nvme0n1: 953.89 GiB, 1024209543168 bytes, 2000409264 sectors
Disk model: PM951 NVMe SAMSUNG 1024GB
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 99412A57-A6DA-C148-A57C-8CBBD791F78F

Device            Start        End    Sectors   Size Type
/dev/nvme0n1p1     2048     104447     102400    50M EFI System
/dev/nvme0n1p2   104448   97761279   97656832  46.6G Linux filesystem
/dev/nvme0n1p3 97761280 2000408575 1902647296 907.3G Linux filesystem
```

**Comment by yuwata** [comment]
One curious thing in the log is that systemd-repart.service is started twice... Why?

**Comment by yuwata** [comment]
Please provide
- `systemd-analyze dump`

**Comment by poettering** [comment]
Systemd-repart is supposed to be started in the initrd when possible, but we also invoke it after the initrd transition to cover for initrds that do not like systemd.

I figure we need to fix repart to exit quickly when no drop-ins are defined, before looking for the block device to operate on and opening it and probing it. Right now its done the other way round. Should be an easy fix (but I am on parental leave, unlikely finding the chance to address this myself, sorry!)

**Comment by yuwata** [comment]
@FireBurn I hope #14807 fixes the issue. Could you test the patch?

@poettering Thank you for the hint.

**Comment by FireBurn** [comment]
That seems to have done the trick

I'm still seeing messages such as:

```
Feb 06 16:08:35 axion systemd[1]: Couldn't move remaining userspace processes, ignoring: Input/output error
Feb 06 16:08:35 axion systemd[1]: local-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
Feb 06 16:08:35 axion systemd[1]: initrd-root-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
Feb 06 16:08:35 axion systemd[1]: initrd.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
Feb 06 16:08:35 axion systemd[1]: initrd-root-device.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
Feb 06 16:08:35 axion systemd[1]: initrd-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
```

I'm not sure if that's related though, attaching the full boot log
[journalctl.zip](https://github.com/systemd/systemd/files/4166263/journalctl.zip)

**Comment by yuwata** [comment]
> Couldn't move remaining userspace processes, ignoring: Input/output error

#14682.

> local-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).

#14787.

**Comment by FireBurn** [comment]
Thanks, I'll wait for those to appear in Linus's tree and rc2
