### ISSUE TITLE
Power management problems since kernel 5.5.2

### ISSUE THREAD

**Issue by rado84-github** [systemd/systemd#14810]
**systemd version the issue has been seen with**
> 244.1-1

**Used distribution**
 > Arch Linux with Cinnamon 4.4.8

**Expected behaviour you didn't see**
 > Instant system startup and sleep upon pressing the corresponding button

**Unexpected behaviour you saw**
 > The whole system hangs up for a few seconds at startup (incl. reboot) and also hangs up for a few seconds after pressing the sleep button (which in my case I've set it to be Pause/Break).

**Steps to reproduce the problem**
1. Install kernel 5.5.2.
2. Set a key to suspend the system to ram.
3. Press that key to put the system to sleep.
4. It will wait a few seconds and then goes to sleep.
In the older versions of the kernel it was enough to gently touch the sleep button and it would go to sleep instantly, whereas now I have to either wait for these seconds to pass or to hold the key pressed for 4-5 seconds, release it and then press it again for the system to sleep.

The following steps are for reboot and I believe they're part of the same problem.
5. From using the system (it doesn't matter if any programs are running) either open terminal and type reboot or use the GUI menus to reboot the system.
6. About 10 seconds will pass before the system actually reboots.
7. Upon startup after displaying the startup events, the white underscore cursor remains on screen for at least 20 seconds and just when you think to reboot and restore from backup, the system suddenly starts up.

According to several sources, Arch wiki included, that's a power management problem with systemd. I tried editing several different config files of systemd, including logind.conf which contained timeout settings but nothing changed.
None of this was happening with systemd and kernel 5.5.1 or lower, so it must be some kind of incompatibility between the two.

**Comment by poettering** [comment]
This sounds like a kernel issue to me. What makea you think this has anything to do with systemd?

**Comment by IvoAndonov** [comment]
> This sounds like a kernel issue to me. What makea you think this has anything to do with systemd?

Arch wiki says so.

**Comment by poettering** [comment]
where does it do so?

**Comment by poettering** [comment]
Let's close this here. Please bring this up with the Arch maintainers. If they see that this is a indeed a systemd problem they'll escalate it back here. I hope that makes sense.

**Comment by IvoAndonov** [comment]
> Let's close this here. Please bring this up with the Arch maintainers. If they see that this is a indeed a systemd problem they'll escalate it back here. I hope that makes sense.

You were right it was a kernel problem, not systemd. I just lost the link to this post and couldn't reply to it until I received an e-mail for the issue being closed.
When kernel 5.6 arrived the problem was gone. Sorry I bothered you with this.
