### ISSUE TITLE
systemd service for libmicrohttpd not working

### ISSUE THREAD

**Issue by Pradeep-raj544** [systemd/systemd#14842]
I created systemd service for sample code of libmicrohttpd ,if I am running this manually its working fine (able to open sample webpage) if I run through systemd service, it's running but webpage not loading(i.e refused to connect), gave permission 777 to the file my systemd service,

[Unit]
Description=lib micro service
After=network.target
[Service]
Type=simple
ExecStart =/root/mylibmicrohttpd 
ExecStop =/root/mylibmicrohttpd
Restart=on-failure
Restart=always
RestartSec=30
[Install]
WantedBy=multi-user.target ```

kindly suggest any working systemd service,

**Comment by boucman** [comment]
This is an issue tracker, not a support forum. Please direct your questions to the systemd mailing list

When you ask your question, could you please also attach the output of "systemctl status <your service>" while it's running but not working ?

thx
