### ISSUE TITLE
loginctl list-sessions and sessions with state closing

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14850]
Ubuntu 18.04 with virtualmin/webmin.

**Is your feature request related to a problem? Please describe.**
When executing loginctl list-sessions, I see accumulated sessions that never disappear with active=yes and state=closing. Even a session that started with ssh remains there forever.

When running systemd-cgls, I see

> ├─user.slice
> │ ├─user-1000.slice
> │ │ └─session-2752200.scope
> │ │   ├─2815 sshd: domain [priv]
> │ │   ├─2830 sshd: domain@pts/0
> │ │   ├─2831 -bash
> │ │   ├─2843 sudo systemd-cgls
> │ │   ├─2844 systemd-cgls
> │ │   └─2845 systemd-cgls
> │ └─user-0.slice
> │   └─user@0.service
> │     ├─gpg-agent.service
> │     │ └─588 /usr/bin/gpg-agent --supervised
> │     └─init.scope
> │       ├─16706 /lib/systemd/systemd --user
> │       └─16707 (sd-pam)

2752200 = current session of SSH, the other session that is still in the list, does not show here. 

> loginctl show-session 2752200
> Id=2752200
> User=1000
> Name=domain
> Timestamp=Mon 2020-02-10 18:27:50 UTC
> TimestampMonotonic=259687025313
> VTNr=0
> Remote=yes
> RemoteHost=87.71.133.205
> Service=sshd
> Scope=session-2752200.scope
> Leader=2815
> Audit=2752200
> Type=tty
> Class=user
> Active=yes
> State=active
> IdleHint=no
> IdleSinceHint=0
> IdleSinceHintMonotonic=0
> LockedHint=no

> 
> loginctl show-session 2751449
> Id=2751449
> User=1000
> Name=domain
> Timestamp=Mon 2020-02-10 18:09:34 UTC
> TimestampMonotonic=258591093717
> VTNr=0
> Remote=yes
> RemoteHost=87.71.133.205
> Service=sshd
> Scope=session-2751449.scope
> Leader=765
> Audit=2751449
> Type=tty
> Class=user
> Active=yes
> State=opening
> IdleHint=no
> IdleSinceHint=0
> IdleSinceHintMonotonic=0
> LockedHint=no

**Describe the solution you'd like**
Not sure if the problem is with systemd but it looks like something is still running/executing but systemd does not show it.

**Comment by poettering** [comment]
please report to your downstream distro. ubuntu 18.04 is too old for this bug tracker. We only accept issues reproducible on the two most recent upstream systemd versions here. Thank you for understanding.

The submission form should have made that very clear btw to keep frustration at a minimum.

**Comment by sebma** [comment]
@poettering Hi,
I have a similar problem on Ubuntu 20.04.2 LTS : 
```bash
$ loginctl list-sessions 
SESSION  UID USER      SEAT  TTY
    105 1001 sebastien seat0    
     99 1001 sebastien seat0    

2 sessions listed.
$ loginctl -n 15 session-status 99 
99 - sebastien (1001)
           Since: Sat 2021-08-07 15:52:39 CEST; 22min ago
          Leader: 119723
            Seat: seat0; vc1
         Display: :0
         Service: sddm; type x11; class user
         Desktop: KDE
           State: closing
            Unit: session-99.scope
                  ├─120287 /usr/bin/baloo_file
                  ├─120342 /usr/libexec/at-spi-bus-launcher --launch-immediately
                  ├─120349 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
                  ├─120407 /usr/libexec/geoclue-2.0/demos/agent
                  ├─120439 /usr/bin/zeitgeist-datahub
                  └─122590 /usr/libexec/at-spi2-registryd --use-gnome-session

Aug 07 15:52:39 michel-K72Jr systemd[1]: Started Session 99 of user sebastien.
Aug 07 15:52:40 michel-K72Jr sddm-helper[119790]: pam_kwallet5: final socket path: /run/user/1001/kwallet5.socket
Aug 07 15:52:40 michel-K72Jr sddm-helper[119795]: Adding cookie to "/home/sebastien/.Xauthority"
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: Checking for pam module
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: Got pam-login param
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: Waiting for hash on 7-
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: waitingForEnvironment on: 3
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: client connected
Aug 07 15:53:09 michel-K72Jr sddm[119792]: kwalletd5: client disconnected
Aug 07 15:53:09 michel-K72Jr sddm-helper[119723]: [PAM] Closing session
Aug 07 15:53:09 michel-K72Jr sddm-helper[119723]: pam_unix(sddm:session): session closed for user sebastien
Aug 07 15:53:09 michel-K72Jr sddm-helper[119723]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_close_session
Aug 07 15:53:09 michel-K72Jr sddm-helper[119723]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Aug 07 15:53:09 michel-K72Jr sddm-helper[119723]: [PAM] Ended.
```

Can you please reopen this issue ?
