### ISSUE TITLE
configure-printer coredumps on me... 

### ISSUE THREAD

**Issue by evertvorster** [systemd/systemd#14855]
Feb 11 11:38:07 Vorster.Home systemd-coredump[686]: Process 552 (udev-configure-) of user 0 dumped core.
                                                    
                                                    Stack trace of thread 552:
                                                    #0  0x00007f95aaa89f25 raise (libc.so.6 + 0x3bf25)
                                                    #1  0x00007f95aaa73897 abort (libc.so.6 + 0x25897)
                                                    #2  0x00007f95aaacd258 __libc_message (libc.so.6 + 0x7f258)
                                                    #3  0x00007f95aaad477a malloc_printerr (libc.so.6 + 0x8677a)
                                                    #4  0x00007f95aaad614c _int_free (libc.so.6 + 0x8814c)
                                                    #5  0x00005622a86ebccd n/a (udev-configure-printer + 0x3ccd)
                                                    #6  0x00005622a86eca58 n/a (udev-configure-printer + 0x4a58)
                                                    #7  0x00005622a86ea10a n/a (udev-configure-printer + 0x210a)
                                                    #8  0x00007f95aaa75153 __libc_start_main (libc.so.6 + 0x27153)
                                                    #9  0x00005622a86ea3ee n/a (udev-configure-printer + 0x23ee)

**Comment by evertvorster** [comment]
Feb 11 11:38:07 Vorster.Home systemd-coredump[686]: Process 552 (udev-configure-) of user 0 dumped core.
                                                    
                                                    Stack trace of thread 552:
                                                    #0  0x00007f95aaa89f25 raise (libc.so.6 + 0x3bf25)
                                                    #1  0x00007f95aaa73897 abort (libc.so.6 + 0x25897)
                                                    #2  0x00007f95aaacd258 __libc_message (libc.so.6 + 0x7f258)
                                                    #3  0x00007f95aaad477a malloc_printerr (libc.so.6 + 0x8677a)
                                                    #4  0x00007f95aaad614c _int_free (libc.so.6 + 0x8814c)
                                                    #5  0x00005622a86ebccd n/a (udev-configure-printer + 0x3ccd)
                                                    #6  0x00005622a86eca58 n/a (udev-configure-printer + 0x4a58)
                                                    #7  0x00005622a86ea10a n/a (udev-configure-printer + 0x210a)
                                                    #8  0x00007f95aaa75153 __libc_start_main (libc.so.6 + 0x27153)
                                                    #9  0x00005622a86ea3ee n/a (udev-configure-printer + 0x23ee)

**Comment by evertvorster** [comment]
Printer works fine, though... this coredump just looks ugly in the logs

**Comment by mbiebl** [comment]
Please report this issue/crash against system-config-printer. systemd-coredump is just the messenger here.
