### ISSUE TITLE
userdbctl: Assertion 'iterator' failed

### ISSUE THREAD

**Issue by embe** [systemd/systemd#14868]
**systemd version the issue has been seen with**
> 245-rc1 (also happens with `userdbctl` from current git (1d6cfd25a2))

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
> No assertion failure

**Unexpected behaviour you saw**
 > ```
 > $ userdbctl -N
 > Assertion 'iterator' failed at src/shared/userdb.c:718, function userdb_iterator_get(). Aborting.
 > zsh: abort (core dumped)  userdbctl -N
 > ```

**Steps to reproduce the problem**
Run `userdbctl -N`.

**Comment by yuwata** [comment]
Fix is waiting in #14944. If you are interested in, please test the PR.
