### ISSUE TITLE
How to serialize on a service unit template?

### ISSUE THREAD

**Issue by zboszor** [systemd/systemd#14866]
Not an actual bug report, just a question.

Does After= and Before= work with non-instantiated template names?
I.e. if I have a service template for which there can be an unknown number of instances, can a service use this below to run after all of the instances?
```
After=template@.service
```
The feature (or the lack of it) is not spelled out in the documentation.

**Comment by boucman** [comment]
please use the mailing list for questions

That being said... here is the current state of affairs
* you can use After=template@.service, but only in another service and it will create the dependency betweent instances of the same name.
* There is no way to do the "any instance" logic from the unit side, but you can add the reverse ordering dependency in the template itself. that would have the same effect...

**Comment by anitazha** [comment]
Closing as it's a mailing list question
