### ISSUE TITLE
Several tests related to unlinkable temporary files seem to fail when shiftfs is used

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#14861]
Trying to run the unit tests on Travis CI on arm64/s390x/ppc64le @mrc0mmand discovered a few issues (mentioned in https://github.com/systemd/systemd/pull/13785#issuecomment-583859992) reproducible with shiftfs only. I'm not sure whether it's a bug in systemd or in shiftfs (or somewhere in between) but I'll leave it here so that it would be possible to refer to it in commit messages.

I'll go ahead and add the "lxc" label because it appears shiftfs is used in LXD containers on Travis CI by default.

Here's how it goes sideways in `test-xattr-util`:
```sh
openat(AT_FDCWD, "/tmp", O_RDWR|O_EXCL|O_TMPFILE, 0600) = -1 EOPNOTSUPP (Operation not supported)
umask(077)                              = 022
getpid()                                = 29361
openat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 3</tmp/systemd-tmp-7950fL>
umask(022)                              = 077
unlinkat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", 0) = 0
statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
fsetxattr(3</tmp/systemd-tmp-7950fL (deleted)>, "user.crtime_usec", "\200\307.0\243e\5", 8, 0) = 0
statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
writev(2<pipe:[241902836]>, [{iov_base="Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.", iov_len=118}, {iov_base="\n", iov_len=1}], 2Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.
) = 119
```

cc @brauner

**Comment by brauner** [comment]
See https://github.com/systemd/systemd/pull/13785#issuecomment-585148492. :)

**Comment by evverx** [comment]
Thank you!

It's not our bug, then :-) Let's wait for Travis to roll the fix out. @mrc0mmand in the meantime, to keep the ball rolling we can mount tmpfs onto /tmp and /var/tmp. I ran
```sh
unshare -m bash -x -c "
mount -t tmpfs tmpfs /tmp/
mount -t tmpfs tmpfs /var/tmp/

meson --werror \
      --optimization=0 \
      --buildtype=debug \
      -Dc_args='-fno-omit-frame-pointer -ftrapv' \
      -Dtests=unsafe \
      -Dsplit-usr=true \
      -Dman=true \
      build
ninja -v -C build
meson test -C build --print-errorlogs --timeout-multiplier=4"
```

**Comment by mrc0mmand** [comment]
Thanks a lot for getting down this rabbit hole!

>in the meantime, to keep the ball rolling we can mount tmpfs onto /tmp and /var/tmp. 

Will do!

**Comment by evverx** [comment]
As far as I can tell, it was reported somewhere else and should be addressed in https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1872757. Closing. @brauner thank you!
