### ISSUE TITLE
sd_bus async method call results in "The maximum number of pending replies per connection has been reached" error

### ISSUE THREAD

**Issue by wrobell** [systemd/systemd#14869]
I have an issue with long running processes, which, after few weeks, results in `The maximum number of pending replies per connection has been reached` error. The processes read data from Bluetooth devices, the devices can be unreliable and after few weeks my software crashes with the error. This applies to multiple systemd versions.

The scenario below tries to replicate the issue. Tested with systemd 244 on ArchLinux distro (as recent as 2020-02-12).

1. Compile the source files for `bad-server` and `bad-client` (see below).
2. Change `max_replies_per_connection` to 128 in `/usr/share/dbus-1/session.conf` to speed-up the process.
3. Start `bad-server`, it will receive a call but will hang for very long time to simulate an unreliable device.
4. Start `bad-client`.
5. After few minutes, the `bad-client` shall report the error.

I would expect no error

- while async call timeout in the client is quite tight (5ms), this should be not a problem for a modern laptop
- the client unrefs sd_bus message and slot after each call 
- the client triggers about 100 asynchronous calls per second, one every 10ms, so there is plenty of time for D-Bus to cleanup messages and slots (I would assume)
- increasing max number of replies per connection will only help to delay the issue, but will not solve it

Seems like a bug, but maybe I am making some error here?

Source for `bad-server.c`
```
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <systemd/sd-bus.h>
#include <unistd.h>

int method(sd_bus_message *msg, void *user_data, sd_bus_error *error) {
    printf("method waiting\n");
    sleep(3600);
    printf("method done\n");
    return sd_bus_reply_method_return(msg, NULL);
}

static const sd_bus_vtable vtable[] = {
        SD_BUS_VTABLE_START(0),
        SD_BUS_METHOD("Method", "", "", method, 0),
        SD_BUS_VTABLE_END
};

int main(int argc, char *argv[]) {
    sd_bus_slot *slot = NULL;
    sd_bus *bus = NULL;
    int r;

    sd_bus_open_user(&bus);
    sd_bus_add_object_vtable(
        bus,
        &slot,
        "/org/test/Bad",
        "org.test.Bad",
        vtable,
        NULL
    );
    sd_bus_request_name(bus, "org.test.Bad", 0);

    while (1) {
        r = 1;
        while (r > 0)
            r = sd_bus_process(bus, NULL);

        sd_bus_wait(bus, -1);
    }
} 
```

Source for `bad-client.c`
```
#include <stdio.h>
#include <unistd.h>
#include <systemd/sd-bus.h>

int task_cb_read(sd_bus_message *msg, void *user_data, sd_bus_error *ret_error) {
    const sd_bus_error *error = sd_bus_message_get_error(msg);

    printf("call returned\n");

    if (error != NULL)
        printf("error: %s\n", error->message);
}


void main() {
    int r;
    sd_bus_slot *slot;
    sd_bus *bus;
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_message *msg;

    r = sd_bus_open_user(&bus);

    while (1) {
        sd_bus_message_new_method_call(
            bus,
            &msg,
            "org.test.Bad",
            "/org/test/Bad",
            "org.test.Bad",
            "Method"
        );
        sd_bus_call_async(bus, &slot, msg, task_cb_read, NULL, 5000);

        r = 1;
        while (r > 0)
            r = sd_bus_process(bus, NULL);

        sd_bus_message_unref(msg);
        sd_bus_slot_unref(slot);

        usleep(10000);
    }
}

```

**Comment by wrobell** [comment]
Another version of `bad-client` below - uses `sd_bus_wait` instead of `usleep`.

What I am looking for is a way to cancel asynchronous call.

Unfortunately `sd_bus_call_async` is missing its man page (BTW. link to its man page at https://www.freedesktop.org/software/systemd/man/sd_bus_slot_set_userdata.html leads to 404).

"Internet" claims I should be able to cancel the call by unreferencing slot (i.e. see approved answer here https://stackoverflow.com/questions/43414858/what-is-a-slot-in-sd-bus-c-language). If that's the case, then there seems to be a bug?

Also, DBus API shows that it is possible to cancel a pending call with `dbus_pending_call_cancel` (https://dbus.freedesktop.org/doc/api/html/group__DBusPendingCall.html).

```
#include <stdio.h>
#include <unistd.h>
#include <systemd/sd-bus.h>

int task_cb_read(sd_bus_message *msg, void *user_data, sd_bus_error *ret_error) {
    const sd_bus_error *error = sd_bus_message_get_error(msg);
    
    printf("call returned\n");
    
    if (error != NULL)
        printf("error: %s\n", error->message);
    return 1;
}
        
void main() {
    int r;
    sd_bus *bus;
    sd_bus_message *msg;
    r = sd_bus_open_user(&bus);
    
    while (1) { 
        sd_bus_slot *slot;
        sd_bus_message_new_method_call(
            bus,
            &msg,
            "org.test.Bad",
            "/org/test/Bad",
            "org.test.Bad",
            "Method"
        );
        sd_bus_call_async(bus, &slot, msg, task_cb_read, NULL, 0);
    
        sd_bus_wait(bus, 10000);

        r = 1;
        while (r > 0)
            r = sd_bus_process(bus, NULL);
        
        sd_bus_message_unref(msg);
        sd_bus_slot_unref(slot);
    }   
} 
```

**Comment by poettering** [comment]
This is not a support forum but a bug and issue tracker. Please contact the mailing list about question how to use sd-bus. (you are basically leaking bus slots)

**Comment by poettering** [comment]
(to keep frustration low the submission form tries to make very clear that this is about bugs and rfes, not about support questions)

**Comment by wrobell** [comment]
Thanks for the pointers. Simple "not a bug" would more than enough. I understand your frustration, but please keep in mind it is sometimes hard to determine scope of the problem for a function having broken or no documentation.
