### ISSUE TITLE
exporting bash functions as env vars are not compatible with systemctl's `--import-environment` operation

### ISSUE THREAD

**Issue by ZaWertun** [systemd/systemd#14878]
**systemd version the issue has been seen with**
systemd 243 (v243.6-1.fc31)

**Used distribution**
Fedora 31, x86_64

**Expected behaviour you didn't see**
Command `systemctl --user import-environment` wouldn't fail after installing package `Lmod` on the Fedora.

**Unexpected behaviour you saw**
Env variables exported by `Lmod` package causing GUI apps artefacts when GUI applications is started with dbus-launch command.
Example of env variables exported when Lmod package is installed:
```
BASH_FUNC_ml%%=() {  eval $($LMOD_DIR/ml_cmd "$@")
}
BASH_FUNC_module%%=() {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
```

**Steps to reproduce the problem**
1. Install `Lmod` package;
2. Logout from KDE;
3. Login back to the KDE;
4. Launch any KDE application via krunner or with dbus-launch, for example Dolphin or Spectacle.
5. That application will lose user configured GUI theme.

Running command `systemctl --user import-environment` gives this error:
```
$ systemctl --user import-environment
Failed to import environment: Invalid environment assignments
```

Error will disappear If I delete env variables `BASH_FUNC_module%%` & `BASH_FUNC_ml%%` before running `systemctl`:
```
$ env -u 'BASH_FUNC_module%%' -u 'BASH_FUNC_ml%%' systemctl --user import-environment
$
```

See related bug in the Redhat bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754395

**Comment by poettering** [comment]
These looknlike very strange variables to export, in particular as they might confuse other shells. I am not convinced that systemd should br a vehicle to set these. What's the rationale behind them?

**Comment by poettering** [comment]
It might be worth changing "import-environment" to warn and ignore such weird assignments instead of failing though...

**Comment by ZaWertun** [comment]
> These looknlike very strange variables to export, in particular as they might confuse other shells. I am not convinced that systemd should br a vehicle to set these. What's the rationale behind them?

It's `Environment Modules provide a convenient way to dynamically change the users’ environment through modulefiles`.
Don’t know why this is needed, but package `Lmod` installed as dependency of `mp` (An open-source library for mathematical programming).
And in Fedora `mp` is intermediate dependency for a wide list of packages (like `digikam` or `blender`).

> It might be worth changing "import-environment" to warn and ignore such weird assignments instead of failing though...

It will be very nice!

Also today I found other package from the standard Fedora repos that will export those weird variables - it's `environment-modules` (https://apps.fedoraproject.org/packages/environment-modules).
Variables exported by this package:
```
BASH_FUNC_switchml%%=() {  typeset swfound=1;
 if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
 typeset swname='main';
 if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
 typeset swfound=0;
 unset MODULES_USE_COMPAT_VERSION;
 fi;
 else
 typeset swname='compatibility';
 if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
 typeset swfound=0;
 MODULES_USE_COMPAT_VERSION=1;
 export MODULES_USE_COMPAT_VERSION;
 fi;
 fi;
 if [ $swfound -eq 0 ]; then
 echo "Switching to Modules $swname version";
 source /usr/share/Modules/init/bash;
 else
 echo "Cannot switch to Modules $swname version, command not found";
 return 1;
 fi
}
BASH_FUNC_module%%=() {  _module_raw "$@" 2>&1
}
BASH_FUNC_scl%%=() {  if [ "$1" = "load" -o "$1" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
BASH_FUNC__module_raw%%=() {  unset _mlshdbg;
 if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '1' ]; then
 case "$-" in
 *v*x*)
 set +vx;
 _mlshdbg='vx'
 ;;
 *v*)
 set +v;
 _mlshdbg='v'
 ;;
 *x*)
 set +x;
 _mlshdbg='x'
 ;;
 *)
 _mlshdbg=''
 ;;
 esac;
 fi;
 unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "`eval 'echo ${'$_mlv'+x}'`" ]; then
 _mlre="${_mlre:-}${_mlv}_modquar='`eval 'echo ${'$_mlv'}'`' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='`eval 'echo ${'$_mlrv':-}'`' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 eval `eval ${_mlre}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '"$@"'`;
 else
 eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 if [ -n "${_mlshdbg:-}" ]; then
 set -$_mlshdbg;
 fi;
 unset _mlshdbg;
 return $_mlstatus
}
```

**Comment by pizzadude** [comment]
I hope this gets fixed in future. :)

**Comment by xdelaruelle** [comment]
All the `BASH_FUNC_*` variables you see are exported Bash shell functions:

```console
$ foo() { echo foo; }
$ export -f foo
$ env | grep foo
BASH_FUNC_foo%%=() {  echo foo
```

So basically the situation you encounter with either Lmod or Modules installed will be encountered anytime a shell function is found exported on Bash shell session.

Exporting shell function enables to pass it to sub-shell execution:

```console
$ foo() { echo foo; }
$ export -f foo
$ bar() { echo bar; }
$ bash
$ foo
foo
$ bar
bash: bar: command not found...
```

**Comment by ZaWertun** [comment]
> All the `BASH_FUNC_*` variables you see are exported Bash shell functions:
> 
> ```
> $ foo() { echo foo; }
> $ export -f foo
> $ env | grep foo
> BASH_FUNC_foo%%=() {  echo foo
> ```
> 
> So basically the situation you encounter with either Lmod or Modules installed will be encountered anytime a shell function is found exported on Bash shell session.
> 
> Exporting shell function enables to pass it to sub-shell execution:
> 
> ```
> $ foo() { echo foo; }
> $ export -f foo
> $ bar() { echo bar; }
> $ bash
> $ foo
> foo
> $ bar
> bash: bar: command not found...
> ```

I just don't understand you.
Such variables breakes things for me even when I'm using __fish__ as my login shell.
Really I don't care why are these variables are needed.

Variables with non valid names must just be skipped.

**Comment by xdelaruelle** [comment]
I just point out that such variables are legitimate in a Bash environment and simply removing them may solve this issue but it may create other issues. But maybe not, depending on where such `systemctl --user import-environment` command is expected to run. So developers should look at that taking this knowledge into account.

**Comment by ZaWertun** [comment]
I got it. Thanks for explanation :)

**Comment by poettering** [comment]
quite frankly, I don#t know what Lmod does, but why does it export these variables?

**Comment by xdelaruelle** [comment]
It exports a shell function to get this function defined in sub-shell. And when you export a function in bash you get such variable defined in the environment.

**Comment by poettering** [comment]
> It exports a shell function to get this function defined in sub-shell. And when you export a function in bash you get such variable defined in the environment.

Well, but it does so much more than exporting it to the subshell: every process will inherit that, not just bash... Isn't the clean approach here to make those subshells source these functions in themselves from somewhere, so that only bash gets it? i.e. propagating bash functions by env vars down the tree and into systemd --user sounds like a pretty poor way of doing these things to me...

**Comment by xdelaruelle** [comment]
What is needed for these tools is to get the shell functions, that are set in `/etc/profile.d/*.sh` scripts, defined in the terminal the user launches once the user is connected to its graphical desktop session.

For instance, he/she:
* connects to the GNOME environment
* then starts `gnome-terminal`
* then types the function name in this terminal (`module` in the present case)
* shell should find the function defined.

**Comment by piotr-dobrogost** [comment]
Related issue #4446
