### ISSUE TITLE
Allow adding further prefixes for units and generator search paths

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#14881]
Many GNOME developers use e.g. jhbuild or similar to create a development environment. For this to work, usually the appropriate environment variables are updated, so that the executables and libraries from the development environment are preferred over the system installed versions.

We can't really install our systemd units into a global directory, and actually also just install them into the same prefix. To make the login work, what we have right now is a script that copies the units into the users runtime directory.

This works pretty well, but we will also need to run generators in the future. We could run those manually but I fear we might end up with odd situations where a system version of the generator is run later on or similar.

This should be solvable if we could re-exec systemd with the additional search paths or maybe even runtime configure these paths. Basically, I am looking at modifying the `UnitPath` property and also adding the generator path.

I think it is fair to assume that we basically have a fresh user login and that we are early in the login process (i.e. session leader wrapper script that sets up the virtual environment).

**Comment by benzea** [comment]
Thinking about it, the cleanest way would probably to have a systemd binary inside the virtual environment. And then provide a way to re-exec into that binary rather than the original one, maybe similar to how root switching works.

**Comment by benzea** [comment]
An alternate solution might be to add a drop-in for user@X.service and rely on us having a separate test user and knowing its UID. There we could execute a separate binary or solve it by allowing to modify the prefix using some other method.

As for the setting the relevant environment variables. jhbuild could install a user-environment-generator to solve that part; with that the user would "magically" run inside the virtual environment.

**Comment by benzea** [comment]
Hmm, ok, further discussions … seems like we can just run a nested `systemd --user` in principle. Which might be an interesting approach to solve all this in a way that requires no systemd changes whatsoever.

**Comment by benzea** [comment]
So, my current thought is, that systemd should be enhanced to allow further extending the generator (and unit) paths through environment variables.

i.e. we currently already have `XDG_DATA_DIRS` which is already quite nice for unit dirs. But the XDG specification does not cover the lib dirs (which makes sense), and this is where many of the units and all the generators live. So having a further environment variable for this, would permit us to overlay the virtual environment using a simple script.

Maybe `SYSTEMD_LIB_DIRS` would work.

**Comment by poettering** [comment]
systemd already looks in XDG_DATA_HOME for unit files too. what else do you need?

**Comment by benzea** [comment]
Well, we did merge #14893 which resolves this issue. Closing because of that.

`XDG_DATA_HOME` does not help for generators.
