### ISSUE TITLE
Make nonunmountable_path configurable

### ISSUE THREAD

**Issue by danbst** [systemd/systemd#14884]
**Is your feature request related to a problem? Please describe.**
`nonunmountable_path` currently looks like:
```
static bool nonunmountable_path(const char *path) {
        return path_equal(path, "/")
#if ! HAVE_SPLIT_USR
                || path_equal(path, "/usr")
#endif
                || path_startswith(path, "/run/initramfs");
}
```

The reasoning is described in comment later:
```
                /* Skip / and /usr since we cannot unmount that anyway, since we are running from it. They
                 * have already been remounted ro. */
```

This assumption fails for NixOS, as we run `systemd` from `/nix/store`, not from `/usr`. So this is kind request to ...

**Describe the solution you'd like**
... allow configure directories where `systemd` is located. And thus, don't try to umount those directories.

**Describe alternatives you've considered**
We are patching `systemd` right now, but systemd refactorings often invalidate our patches.
https://github.com/NixOS/systemd/commit/33f458625f2a9d201263bd1b81b1c56f4a077e80

**Comment by flokli** [comment]
As elaborated in https://github.com/flokli/nixpkgs/commit/8006b5b988c0440c4dcbedb057cabd7ff8d9f14d, this might be fixable by simply adding entries with the `x-initrd` to our `/etc/fstab` - but we need to test it.

I'd propose to focus discussion inside https://github.com/NixOS/nixpkgs/issues/80038, no reason to bother upstream with this too much.

**Comment by danbst** [comment]
@flokli ok, though looking at their code I don't see they use `x-initrd` flag in during umount. Our issue with umount is during shutdown.

**Comment by flokli** [comment]
I meant the special handling for lines with a "x-initrd.mount`` in the `mount_is_extrinsic()` method at 
https://github.com/systemd/systemd/blob/c315b79fb43a4d921a533ba0c2cb303324887993/src/core/mount.c#L426-L430

**Comment by poettering** [comment]
yeah x-initrd.mount is doing what you are asking for. if it doesn't file a bug about that please. let's close the issue here for now.
