### ISSUE TITLE
/usr/lib/systemd/system/systemd-ask-password-console.service:12: Executable "systemd-tty-ask-password-agent" not found in  path "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14889]
**systemd version the issue has been seen with**
> 245 rc1

**Used distribution**
 > Fedora Rawhide

**Expected behaviour you didn't see**
 > 

**Unexpected behaviour you saw**
[  +0.001745] systemd[1]: Couldn't move remaining userspace processes, ignoring: Input/output error
[  +0.101932] systemd[1]: initrd.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
[  +0.011801] systemd[1]: /usr/lib/systemd/system/systemd-ask-password-console.service:12: Executable "systemd-tty-ask-password-agent" not found in
 path "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
[  +0.000006] systemd[1]: systemd-ask-password-console.service: Unit configuration has fatal error, unit will not be started.
[  +0.004748] systemd[1]: local-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
[  +0.008420] systemd[1]: initrd-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
[  +0.000262] systemd[1]: initrd-root-device.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).
[  +0.000430] systemd[1]: initrd-root-fs.target: Requested dependency OnFailure=emergency.target ignored (target units cannot fail).```
```

**Steps to reproduce the problem**
update

**Comment by doverride** [comment]
This applies to all references to systemd-ask-password in the various related service units

**Comment by doverride** [comment]
Actually looks like a fedora specifc packaging issue. seems the command isnt installed at all

**Comment by doverride** [comment]
actually dracut issue but ok
