### ISSUE TITLE
Multiple template instance variables

### ISSUE THREAD

**Issue by chiraag-nataraj** [systemd/systemd#14895]
**Describe the solution you'd like**
As it stands right now, templates can only provide one argument (accessible by `%i`). It would be nice to be able to provide multiple arguments to instantiate a template as an alternative to `EnvironmentFile`. The parameters could be accessible as some sort of array (and presumably there'd be some sort of maximum parameter limit).

**Describe alternatives you've considered**
`EnvironmentFile` works.

Here's an example. I want to use `sshfs` with several instance-specific options. It's not easy to derive all options from one parameter, so instead, I do something like this:

* `~/.config/sshfs/sshfs.config` contains several environment variables pertaining to global `sshfs` configuration (location of identity files and such)
* `~/.config/sshfs/<x>.sshfs` contains environment variables related to host `<x>` (such as hostname, mount location, etc).
* `~/.config/systemd/user/sshfs@.service` loads `~/.config/sshfs/sshfs.config` for the global options, loads the relevant config file from `~/.config/sshfs` for the specified instance, and then runs `ExecStart` with the specified parameters. Both `~/.config/sshfs/sshfs.config` and `~/.config/sshfs/%i.sshfs` are loaded as `EnvironmentFile` arguments. Being able to provide multiple template instance variables would be helpful in this kind of scenario.

**Comment by keszybz** [comment]
This has come up before, and we decided not to allow multiple instances. If necessary, it is possible to encode multiple fields into one value in a unit-specific fashion, or use the instance as a key into some external storage, for example a directory on disk. Sorry.

**Comment by eMPee584** [comment]
so f.e., for multiple matrix synapse workers, instead of having a `matrix-synapse-worker-@.service` base unit that can be symlinked to `matrix-synapse-worker-federation_reader@8088.service` and make use of `%j` and `%i`, this should best be solved with a shell command? :
```
# matrix-synapse-worker@federation_reader:8088.service => %i=federation_reader:8088
ExecStart=/bin/sh -c "WORKER=%i; WORKER=$${WORKER%%:*}; \
                       exec /usr/bin/docker exec \
                       --user={{ matrix_user_uid }}:{{ matrix_user_gid }} \
                       matrix-synapse \
                       python -m synapse.app.$${WORKER} -c /data/homeserver.yaml -c /data/worker.%i.yaml"
```

**Comment by fxfactorial** [comment]
> This has come up before, and we decided not to allow multiple instances. If necessary, it is possible to encode multiple fields into one value in a unit-specific fashion, or use the instance as a key into some external storage, for example a directory on disk. Sorry.

So users have asked multiple times and the response is nah - go against the users direct feedback

**Comment by eMPee584** [comment]
> we decided not to allow multiple instances
… Mind explaining the reasoning behind this?
