### ISSUE TITLE
systemd-makefs: can't make filesystem

### ISSUE THREAD

**Issue by killermoehre** [systemd/systemd#14905]
**systemd version the issue has been seen with**
> systemd 243 (v243.7-1.fc31)

**Used distribution**
 > Fedora 31

**Expected behaviour you didn't see**
 > On the device `/dev/sdb` is an `ext4` filesystem created.

**Unexpected behaviour you saw**
 > No filesystem is created, but `mke2fs` returns `1` with following error message:
> ```Shell
> $ sudo /usr/lib/systemd/systemd-makefs ext4 /dev/sdb
> mke2fs 1.45.5 (07-Jan-2020)
> The file  does not exist and no size was specified.
> /sbin/mkfs.ext4 failed with exit status 1.
> ```
> 
> Check out the double space between `file` and `does`

**Steps to reproduce the problem**

In `/etc/fstab` add following line

```
/dev/sdb /builddir ext4 defaults,noauto,x-systemd.automount,x-systemd.makefs,x-systemd.growfs 0 0
```

Attach a (virtual) disk as `/dev/sdb` and access `/builddir`. It will fail.

**Comment by yuwata** [comment]
Should be fixed by #14873.
