### ISSUE TITLE
udevadm trigger --type=devices --action=add pollutes kernel log

### ISSUE THREAD

**Issue by ErwanAliasr1** [systemd/systemd#14906]
**Version**
Seen on systemd 219-67 but still exist in master

**Used distribution**
Centos

**Expected behaviour you didn't see**
Running /usr/bin/udevadm trigger --type=devices --action=add pollutes the kernel logs.
On a Dual AMD-7702, this commands prints 256 times "kvm: disabled by bios" 
An "add" event to /sys/devices/system/cpu/cpu<x>/uevent will print this message.
As my system has CPU 256 threads, this prints 256 times that line in the logs.
That clearly pollutes the logs.

**Unexpected behaviour you saw**
I would expect /usr/bin/udevadm trigger to only perform the "add" on a single cpu thread, not on all of them.

**Steps to reproduce the problem**
Run "/usr/bin/udevadm trigger --type=devices --action=add" on a system where the virtualization extensions are off, you'll get one line per cpu thread existing on the system.

**Comment by boucman** [comment]
Is that still the case in latest release of systemd ?

**Comment by ErwanAliasr1** [comment]
Just tried master and it's fixed yes.

**Comment by ErwanAliasr1** [comment]
I have no idea what release fixed it then :/

**Comment by ErwanAliasr1** [comment]
At least I built up to v239 and it worked nice. Earlier version didn't built and I don't want to enter this painful build process with all possible combiniations of deps.

**Comment by yuwata** [comment]
Closing then.

**Comment by ErwanAliasr1** [comment]
Got a patch merged into the kernel to reduce the noise when hit by this issue:  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ef935c25fd648a17c27af5d1738b1884f78c5b75

**Comment by superm1** [comment]
With kernel 5.18.0 and systemd 249.11 (Packaged as part of Ubuntu 22.04; distro package version 249.11-0ubuntu3.1), I'm still seeing this issue happening.
I actually sent up a patch to change it to `pr_err_once` and was pointed at this bug report.
I can readily reproduce the problem with `udevadm trigger --type=devices --action=add`.
