### ISSUE TITLE
Support journal-upload HTTPS without key and certificate

### ISSUE THREAD

**Issue by megastef** [systemd/systemd#14919]
**Is your feature request related to a problem? Please describe.**

We like to upload journald-logs to SaaS HTTPS receiver without the need to create client certificates. 
All https uploads fail with this setting: 

```
[Upload]
URL=https://logsene-journald-receiver.sematext.com:443/LOGS_TOKEN
#ServerKeyFile=/etc/ssl/private/journal-upload.pem
#ServerCertificateFile=/etc/ssl/certs/journal-upload.pem
TrustedCertificateFile=/etc/ssl/certs/ca-certificates.crt
```

Error: 
```
failed: error reading X.509 key or certificate file
```

Setting no `ServerCertificateFile`  and `ServerKeyFile` file, the default value is used, but those files don't exist. 
https://github.com/systemd/systemd/blob/5ee69e144e57edd328abf85ef8790ed52217b930/src/journal-remote/journal-upload.c#L36-L37

journal-upload loads keyfile and certificate always for `https` URLs
See: https://github.com/systemd/systemd/blob/5ee69e144e57edd328abf85ef8790ed52217b930/src/journal-remote/journal-upload.c#L243-L250

**Describe the solution you'd like**

Change the condidtion in line 243: https://github.com/systemd/systemd/blob/5ee69e144e57edd328abf85ef8790ed52217b930/src/journal-remote/journal-upload.c#L243

```
if (arg_key || startswith(u->url, "https://")) {
...
```
to
```
if (arg_key) { 
...

// or when arg_key AND https URL is used

if (arg_key && startswith(u->url, "https://")) {
...

```

So keys are only loaded if the user has specified the keys - and not for every HTTPS URL. 

**Describe alternatives you've considered**
An alternative would be a setting to allow simple https uploads. 
In our case, we use a generated token in the URL.

**Comment by megastef** [comment]
@poettering would it help if we provide a pull-request `systemd-journal-upload`?

**Comment by anitazha** [comment]
@megastef PRs are always appreciated and considered if there's a feature you'd like to have.
