### ISSUE TITLE
Shutdown/Reboot hang on "Detaching DM devices"

### ISSUE THREAD

**Issue by aaronovz1** [systemd/systemd#14920]
**systemd version the issue has been seen with**
> 243.2

**Used distribution**
 > Yocto Zeus 3.0.1

**Expected behaviour you didn't see**
 > System shuts down/reboots completely

**Unexpected behaviour you saw**
 > System hangs at "Detaching DM devices" when shutting down or rebooting.
Tried the following:
 - debug-shell is not accepting user input, making it very hard to debug the issue.
 - Enable ShutdownWatchdogSec and RebootWatchdogSec with kernel module softdog. Watchdog doesn't seem to work.
 - Set reboot.target JobTimeoutSec to a short value. Does not make a difference.

**Steps to reproduce the problem**
CTRL+ALT+DEL

Can anyone suggest anything else I can do debug this? It doesn't happen on every reboot/shutdown, but it does happen on most of them.

**Comment by aaronovz1** [comment]
Anyone have some suggestions?

**Comment by brianjmurrell** [comment]
Similarly, we frequently see:

```
[  386.681152] systemd-shutdown[1]: All filesystems unmounted.
[  386.687344] systemd-shutdown[1]: Deactivating swaps.
[  386.692808] systemd-shutdown[1]: All swaps deactivated.
[  386.698506] systemd-shutdown[1]: Detaching loop devices.
[  386.704380] systemd-shutdown[1]: All loop devices detached.
```
and the reboot hangs there.

Typically on a successful reboot, after the above comes:

```
[ 1221.760256] systemd-shutdown[1]: Detaching DM devices.
[ 1221.765447] systemd-shutdown[1]: All DM devices detached.
[ 1221.772818] systemd-shutdown[1]: Syncing filesystems and block devices.
[ 1221.779509] systemd-shutdown[1]: Rebooting.
```

**Comment by poettering** [comment]
Do you actually have any DM devices?

This smells like a kernel lockup to me, i.e. nothing systemd could do anything about? have you turned on full debug logging?

**Comment by poettering** [comment]
(in particular that softdog doesn't work makes this smell like a kernel problem)

**Comment by aaronovz1** [comment]
What is a DM device and how would I check if the system has any? Also note that kernel version did not change when systemd version was updated.

**Comment by poettering** [comment]
DM devices are LVM, cryptsetup, some forms of RAID

**Comment by aaronovz1** [comment]
Ok. The system has none of those. Is that something that should be disabled somewhere to stop it even doing that step on shutdown?

**Comment by poettering** [comment]
no, there's not.

So this is on some embedded device I presume? my educated guess is that this is between the kernel and the hw, systemd is just the last thing you see on screen, that's all...

**Comment by aaronovz1** [comment]
Yep, embedded device running Yocto. Interesting the HW and kernel stayed the same but upgrading Yocto branch, updated many other packages plus systemd. Some combination of packages has now caused this lock up.

**Comment by poettering** [comment]
is this still relevant? can we close this?

**Comment by aaronovz1** [comment]
It's probably relevant but was not able to root cause the issue and added a HW watchdog to workaround hang on shutdown. I am not sure if the problem exists in newer versions of systemd/yocto. You can close if you like.

**Comment by poettering** [comment]
Ok, let's close then. If you manage to find something in the end, please report back!

**Comment by suniljamadar** [comment]
kk
