### ISSUE TITLE
nss-resolve returns UNAVAIL for LLMNR resolution failures

### ISSUE THREAD

**Issue by Hello71** [systemd/systemd#14922]
If LLMNR is enabled, as I believe is the default, systemd-resolved returns org.freedesktop.DBus.Error.Timeout: All attempts to contact name servers or networks failed. This causes nss-resolve to return UNAVAIL instead of NOTFOUND, causing a delay in lookup. This is especially bad with the recommended NSS resolve + dns fallback, because then at least three resolutions will be performed: resolve, DNS AAAA, DNS A, which will all time out. On my system, this causes the time for failed resolutions to increase from 1.5-2 seconds to 12 seconds.

Similar to #4157, but LLMNR instead of DNSSEC.

**Comment by Gigadoc2** [comment]
Hmm, maybe I am missing something here, but if you can't resolve a name on LLMNR, wouldn't you want to retry with regular DNS?

I realize that LLMNR only checks single-label names, but those are also often used with local DNS?

**Comment by Hello71** [comment]
nss-resolve already does that.

**Comment by Hello71** [comment]
furthermore, UNAVAIL is clearly not correct.

**Comment by Gigadoc2** [comment]
> nss-resolve already does that.

You are right, I realize my error there...

> furthermore, UNAVAIL is clearly not correct.

Not too sure about that, given that with LLMNR (and mDNS) you can never be sure that there is no such host, you only know that you can't find it right now. For example, I believe mDNS is specified to never return NXDOMAIN, and resolved does not cache negative results for either LLMNR or mDNS and has them time out with the stub listener as well (which I believe is on purpose?).
Nevertheless, you have a valid point there that it needlessly tries resolving the name twice in the global DNS, once with `resolve` and once with `dns`.
