### ISSUE TITLE
libudev is not requirend by systemd anymore?

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#14937]
I just realized that my embedded system has no use of libudev, and that my debian system likely would not need it either (it depends on the library, but doesn't need any symbols from it as far as I can tell)

If you look for ex. at the symbols from libsystemd-shared, it lists libudev as dependency, but all symbols are defined in the library (show an address).
```bash
nm -D  /usr/lib/systemd/libsystemd-shared-244.so | grep udev
```

Time to stop linkin libudev to libsystemd-shared?

**Comment by yuwata** [comment]
Yeah, libudev is not used anymore.

**Comment by nolange** [comment]
I thought libsystemd-shared was linked to udev, turns out it leaks in transitively from libdevmapper.
shouldnt have used `ldd` to check.

Invalid issue then
