### ISSUE TITLE
machinectl shell does not load environment variables from user instance

### ISSUE THREAD

**Issue by Gigadoc2** [systemd/systemd#14939]
**systemd version the issue has been seen with**
> systemd 244 (244.3-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

I have briefly looked through the NEWS and commit history, and found no commits pertaining to this since 244.

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > When obtaining a new shell as a non-root user with `machinectl shell user@`, the shell imports the environment of the systemd user instance.

**Unexpected behaviour you saw**
 > When obtaining a new shell as a non-root user with `machinectl shell user@`, the shell is started with a mostly empty environment.

**Steps to reproduce the problem**
```
$ systemctl --user set-environment FOO=bar
$ machinectl shell $USER@
Connected to the local host. Press ^] three times within 1s to exit session.
$ echo $FOO

```

**Notes**
Now I am not sure whether this is a bug or intended design.
On one hand, `man:environment.d(5)` clearly states that the environment is exported to the services the systemd _user instance_ starts, while `machinectl shell` has the _system instance_ create a new session. Also, `machinectl shell` has the explicit purpose of getting a clean environment.

On the other hand, `environment.d` seems also to be meant for customizing user session environment, as GNOME defines it to be the place for customizing environment variables in a Wayland session and GDM imports them for user sessions. If I understand correctly, `environment.d` even began because GDM wanted a place to load variables from somewhere without running login shells (https://github.com/systemd/systemd/pull/3904). In that thread it was also planned to have `login` load the variables, though that has not happened so far.

So, whether this is or is not a bug seems to depend on the scope of both `environment.d` and `machinectl shell`:
 * Is `environment.d` meant to be general configuration for user sessions and services, or only graphical sessions and services, or really only services?
 * Is `machinectl shell` supposed to result in a "full session" like when logging in via `login` or GDM, or is it something more limited?

**Comment by poettering** [comment]
environment.d is not applied to sessions, only to stuff invoked from the systemd --user instance. There's no concept of importing that back into login shells. GNOME imports things the other way, but I am not sure any such blanket importing makes sense. 

If you want to set an env var for a login shell just put it in ~/.profile? i.e. the environment.d is for a world where that s not read because there is no ~/.profile read because there is no shell.

**Comment by Gigadoc2** [comment]
GNOME starts its processes partially as systemd --user services, partially as scopes, depending on whether there is a native .service file already or not (especially for .desktop apps there is not). So I think for GNOME in particular the blanket import does make sense, as it keeps the launch environment for systemd native and .desktop apps somewhat consistent.

However, this is not done by the GNOME session, but by GDM, even for non-GNOME desktops, and that is probably where the confusion starts: I see now that environment.d variables are not meant to unconditionally apply to all user sessions, but as long as you use GDM they kind of do (and then there is also the talk in https://github.com/systemd/systemd/pull/3904).

But I wonder if it really should not blanket apply to all sessions: Most of the variables set for non-shell sessions and systemd --user services also apply to shell sessions. If .profile only applies to shell sessions and environment.d only to everything else, users and developers/distributors need to keep environment.d and /etc/profile in sync; flatpak for example already ships both an user-environment-generator and an /etc/profile.d drop-in doing the same thing.
Adding to that confusion is that some display managers (like apparently SDDM) do _neither_ use environment.d nor invoke a login shell, and there is no way at all to set environment variables (maybe desirable for the far future, but problematic right now). So I wonder whether there shouldn't be a standard to set environment variables for both shell and non-shell sessions (and systemd --user services, as they are part of non-shell sessions), and if there should, why not take the environment generators as is?

But my original question has been answered (it is intentional), and the general question about the future scope of environment.d (and environment generators in general) is probably to vague for an issue like this. I will close this and take the discussion to the mailing list.
