### ISSUE TITLE
networkd: manually specified Gateway added to main route table instead of VRF's

### ISSUE THREAD

**Issue by mizvekov** [systemd/systemd#14940]
Seen on systemd v244.3 on debian testing:

When an interface is configured for VRF, any manually added gateways are added to the main routing table, instead of VRF's routing table. This otherwise works fine when using DHCP for example.

```
[Network]
VRF=test
Address=192.168.2.2/24
Gateway=192.168.2.1
```
```
# ip route show vrf test
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.2
192.168.3.0/24 dev eth1 proto kernel scope link src 192.168.3.1
```
```
# ip route show
default via 192.168.2.1 dev eth0 proto static
```

**Comment by yuwata** [comment]
Could you show the relevant .network and .netdev files?

**Comment by mizvekov** [comment]
> 
> 
> Could you show the relevant .network and .netdev files?

test.netdev:
```
[NetDev]
Name=test
Kind=vrf

[VRF]
Table=651732
```

test.network:
```
[Match]
Name=test
```
eth0.network:
```
[Match]
MACAddress=06:00:00:00:00:00

[Network]
VRF=test
Address=192.168.2.2/24
Gateway=192.168.2.1
```

**Comment by yuwata** [comment]
#14941 should fixes the issue. If you are interested in, please test the PR.
