### ISSUE TITLE
Inform the user of errors when using `udevadm info [-e]`

### ISSUE THREAD

**Issue by Swaagie** [systemd/systemd#14959]
**Is your feature request related to a problem? Please describe.**
Running `udevadm info -e` does not output errors if the system contains devices that are only readable by a certain user (read: root). `udevadm` does not output any of the `EACCES` errors. Example output when a single device (`uevent`) had 'incorrect' permissions:

```
> ls -la /sys/devices/platform/soc/soc:firmware/soc:firmware:expgpio/
total 0
drwxr-xr-x 5 root root    0 Feb 27 13:51 .
drwxr-xr-x 6 root root    0 Feb 27 13:49 ..
lrwxrwxrwx 1 root root    0 Feb 27 13:51 driver -> ../../../../../bus/platform/drivers/raspberrypi-exp-gpio
-rw-r--r-- 1 root root 4096 Feb 27 13:51 driver_override
drwxr-xr-x 3 root root    0 Feb 27 13:51 gpio
drwxr-xr-x 3 root gpio    0 Feb 27 01:28 gpiochip1
-r--r--r-- 1 root root 4096 Feb 27 13:51 modalias
lrwxrwxrwx 1 root root    0 Feb 27 13:51 of_node -> ../../../../../firmware/devicetree/base/soc/firmware/expgpio
drwxr-xr-x 2 root root    0 Feb 27 13:51 power
lrwxrwxrwx 1 root root    0 Feb 27 13:51 subsystem -> ../../../../../bus/platform
-rw-r----- 1 root root 4096 Feb 27 13:51 uevent

> $ udevadm info -e
> $ 
```

**Describe the solution you'd like**
Output the `EACCES` errors to `stdout` or `stderr` so its clear to the user or a consuming higher level language module that some of the devices are unreadable. Similar to how `find` outputs `find: ‘/proc/14/fdinfo’: Permission denied`

**Describe alternatives you've considered**
Make the CLI tool more resillient to erros while listing all devices. Skip the unreadable device and allow it to continue reading to return an incomplete list. I consider this suboptimal as its technically not the complete set of devices which could lead to bad assumptions in consumption libraries or frameworks.

**Comment by yuwata** [comment]
If possible, please test PR #14960.
