### ISSUE TITLE
REST API via HTTP

### ISSUE THREAD

**Issue by cypa** [systemd/systemd#14974]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with ISPmanager, VestaCP, webmin etc. - many management web-panels are disaster and badly constructed, lack any sensible architecture.  

**Describe the solution you'd like**
Simple and consistent http interface to rule my linux server.

**Describe alternatives you've considered**
I've found a few experimental projects like https://github.com/ogarcia/sysdweb, none of them are mature or thoroughly elaborated.

**Comment by q2dg** [comment]
What you need is https://cockpit-project.org
You're in the wrong place, let's close this

**Comment by cypa** [comment]
that's nice, but they invented another new protocol in the cockpit - I'm not sure about it's security and possible vulnerabilities
I'd like simple robust thing tightly integrated into systemd

**Comment by ssahani** [comment]
May be you try with https://github.com/RestGW/api-routerd

**Comment by keszybz** [comment]
Yeah, this is out of scope here. Systemd provides dbus and varlink interfaces, rest is out of scope.

**Comment by TriMoon** [comment]
> that's nice, but they invented another new protocol in the cockpit - I'm not sure about it's security and possible vulnerabilities
> I'd like simple robust thing tightly integrated into systemd

Opening another door as default is not a feature that general systems need.
If the administrator needs a web interface then he can use https://cockpit-project.org/ as mentioned...
