### ISSUE TITLE
Maybe RootImage= should add a dependency to systemd-udevd.service

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#14972]
**systemd version the issue has been seen with**
> master / 244.3-1

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Successful boot

**Unexpected behaviour you saw**
 
I have an experimental setup where most services use a custom built `RootImage` (or `RootDirectory`). This works well with initramfs created by Debian mkinitramfs tool, but when trying Dracut, starting of several services hang before they reach execve(). The problem seems to be that the `RootImage` is probed for partitions and this wants to [talk to udevd](https://github.com/systemd/systemd/blob/e6e81ec0a56861b905db975fc32c83e2f2faca7d/src/shared/dissect-image.c#L188). With mkinitramfs initramfs, for some reason udevd is always available, but with Dracut initramfs, udevd has not been restarted at this point. Then there seems to be a dependency issue where udevd can't be started until later (why? udevd does not depend on anything?), so there's a deadlock. Perhaps with Dracut the dependencies are managed much more flexibly with systemd in initramfs, compared to a shell script which has quite rigid ordering.

It's not clear what are the failing units, at least systemd-remount-fs (RootImage) and systemd-udev-trigger (tried both RootDirectory and RootImage) seem to have this problem.

I tried to avoid this by introducing a new drop-in for all units with RootImages which have `DefaultDependencies=no`, containing
```
[Unit]
Wants=systemd-udevd.service
After=systemd-udevd.service
Requires=systemd-udevd.service
```
but this causes dependency loops.

I also modified PID1 so that DISSECT_IMAGE_NO_UDEV is always enabled, but that didn't seem to change anything.

This is what strace from debug shell shows for a failing process (systemd-remount-fs but this is still systemd in control before execve()):

```
openat(AT_FDCWD, "/run/udev/data/b7:0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
epoll_create1(EPOLL_CLOEXEC)            = 3
access("/run/udev/control", F_OK)       = 0
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, NETLINK_KOBJECT_UEVENT) = 4
setsockopt(4, SOL_SOCKET, SO_ATTACH_FILTER, {len=8, filter=0x7ffe064bae60}, 16) = 0
setsockopt(4, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
bind(4, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000002}, 12) = 0
getsockname(4, {sa_family=AF_NETLINK, nl_pid=836, nl_groups=0x000002}, [12]) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=2163346048, u64=94839336209024}}) = 0
openat(AT_FDCWD, "/run/udev/data/b7:0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
epoll_wait(3, 
```

Sorry for being vague but the problem isn't very clear to me either yet. Journald is also not running at this point. It's not clear if this is a bug, perhaps the setup is too experimental and unsupported. Maybe this already provokes some thoughts on the dependencies for `RootImages`.

**Steps to reproduce the problem**

Nothing simple yet.

**Comment by topimiettinen** [comment]
Regarding the dependencies: systemd-udevd.service has line `After: systemd-sysusers.service systemd-hwdb-update.service` and systemd-tmpfiles-setup-dev.service has `Before: systemd-udevd.service`. There is also an implied dependency for kmod-static-nodes.service due to systemd-tmpfiles-setup-dev.service. I'm not sure about systemd-remount-root.service and various LVM services (probably because rootfs uses LVM). After changing these to use a `RootDirectory` instead of `RootImage`, and adding a dependency to systemd-udevd.service for rest, my system finally boots with initrd made with dracut without assistance.

The boot problem is a bit nasty as it can't be broken by restarting services with systemctl. By killing processes by hand, the service gets considered failed and then it can be restarted manually, once the system gets to the point where systemd-udevd is also available.

I think the same situation could be reached on shutdown, if you have a service using `RootImage` that is started after systemd-udevd is killed.

The problem can be reproduced by stopping udevd and its control sockets, running `udevadm info --cleanup-db` and then trying to restart a service with a `RootImage`.

So, how to fix this? My images only contain a squashfs filesystem without partitions, so for this specific case it would probably be enough to fix dissect_image() or its call site at setup_namespace() to handle this situation without help from udevd. This would not help in the more general case, where there actually could be a partition table. I don't like the idea of automatic dependency, perhaps there are other solutions. Also it would be nice to use `RootImage` for those early services which now use `RootDirectory`, even for systemd-udevd.

**Comment by poettering** [comment]
hmm, yeah, i guess we should add that implicit dep
