### ISSUE TITLE
networkd: vxlan netdev set physdev

### ISSUE THREAD

**Issue by rcgoodfellow** [systemd/systemd#14975]
Is there a way to set the physdev of a vxlan netdev? I've not been able to find any documentation or examples of this. This would correspond to the `dev` argument in 

```
ip link add vxlan47 type vxlan id 47 dev eth2
```

Thanks

**Comment by ssahani** [comment]
Please see https://www.freedesktop.org/software/systemd/man/systemd.network.html#VXLAN=

**Comment by rcgoodfellow** [comment]
Thanks!
