### ISSUE TITLE
Multi address network config after resume from sleep is missing IP's.

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#14987]
**systemd version the issue has been seen with**
> 242-7ubuntu3.7

**Used distribution**
 > Kubuntu 19.10 with it's PPA
<details>
<summary>neofetch output</summary>

```console
> neofetch --stdout
OS: Ubuntu 19.10 x86_64 
Model: Manual build Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2017-08-10 AMI Ver:3801 
Kernel: 5.3.0-40-generic 
Uptime: 1 day, 2 hours, 2 mins 
Packages: 2797 (dpkg), 9 (snap) 
Shell: zsh 5.7.1 
Resolution: 1680x1050 @ 59.88Hz, 2560x1080 @ 60.00Hz 
DE: KDE 
WM: KWin 
Theme: Breeze [KDE], Adapta-Nokto [GTK2], Default [GTK3] 
Icons: breeze [KDE], breeze [GTK2/3] 
Terminal: vscode 
Font: [KDE], Noto Sans, 10 [GTK2/3] 
Locale: en_US.UTF-8 
Memory: 7470MiB / 32026MiB (23%) [37m[---============[37m] 
CPU: Intel i7-5820K (12) @ 4.0GHz [46.0°C] 
GPU: NVIDIA GeForce GTX 1080 Ti 
GPU Driver: NVIDIA 430.50 
CPU Usage: 4% 
Disk (/): 18G / 146G (13%) 
Disk (home): 27G / 63G (45%) 
Disk (efi): 89M / 511M (18%) 
Disk (efi-other): 5.4M / 549M (1%) 
Disk (Data): 551G / 3.5T (17%) 
```
</details>

**Expected behaviour you didn't see**
 > All assigned addresses should be correctly configured as before system went to sleep.

**Unexpected behaviour you saw**
 > Only first address is assigned.

**Steps to reproduce the problem**
<details>
<summary>File: /etc/systemd/network/<b>10-mb-eth0.link</b></summary>

```ini
[Match]
MACAddress=<MAC hidden for privacy>

[Link]
Description=Onboard ethernet port
Name=dmz0
# Unknown lvalue 'AlternativeName' in section 'Link'
# AlternativeName=utp
# AlternativeName=eth0
MTUBytes=1500
# BitsPerSecond=1G
AutoNegotiation=yes
WakeOnLan=magic
# See: lshw -C network
Advertise=1000baset-full
Advertise=100baset-full
# Advertise=100baset-half
# Advertise=10baset-full
# Advertise=10baset-half
```
</details>
<details>
<summary>File: /etc/systemd/network/<b>10-mb-eth0.network</b></summary>

```ini
[Match]
MACAddress=<MAC hidden for privacy>

[Link]
ARP=yes
Multicast=yes
AllMulticast=true
RequiredForOnline=yes

[Network]
Description=Onboard ethernet port
MulticastDNS=true
# DHCPServer=yes
LinkLocalAddressing=yes
IPv4LLRoute=true
LLMNR=yes
MulticastDNS=yes
DNSSEC=allow-downgrade
DNSSECNegativeTrustAnchors=lan
LLDP=true
# EmitLLDP=true
DNS=::1
DNS=127.0.0.1
Domains=lan
Domains=dev.lan
…
Domains=~.
DNSDefaultRoute=true
# NTP=
IPForward=yes
IPv6PrivacyExtensions=kernel
IPv6AcceptRA=true
# IPv6DuplicateAddressDetection=0
# ConfigureWithoutCarrier=true
# IgnoreCarrierLoss=true
# DefaultRouteOnDevice=yes

[Address]
Address=192.168.0.2/16
Broadcast=192.168.0.255

[Address]
Address=192.168.1.254/24
Broadcast=192.168.1.255

[Address]
Address=<IP6 hidden for privacy>
HomeAddress=yes
DuplicateAddressDetection=no
# AutoJoin=yes

[Address]
Address=<IP6 hidden for privacy>
# PreferredLifetime=0
HomeAddress=yes
DuplicateAddressDetection=no
# AutoJoin=yes

[Route]
Gateway=192.168.0.1
GatewayOnLink=true
# Was 3
Metric=1

[IPv6AcceptRA]
UseDNS=no
UseDomains=no
UseAutonomousPrefix=no
UseOnLinkPrefix=no
```
</details>
<details>
<summary><b>Dir listing:</b> /lib/systemd/system-sleep</summary>

```console
> ls -lah
total 48K
drwxrwxr-x+ 2 root root 4.0K Feb 29 18:33 .
drwxr-xr-x  8 root root  12K Feb 19 09:32 ..
-rwxr-xr-x  1 root root   92 Aug 21  2019 00-hdparm
-rwxrwxr-x+ 1 root root  156 Feb 29 18:35 10-systemd-networkd
-rwxrwxr-x+ 1 root root  134 Feb 29 14:40 40-tor
-rwxrwxr-x+ 1 root root  126 Feb 29 15:25 41-bind9
-rwxrwxr-x+ 1 root root  160 Feb 29 15:01 50-systemd-resolved
-rwxr-xr-x  1 root root  219 Feb 17 14:29 50-unattended-upgrades
-rwxrwxr-x+ 1 root root  144 Feb 29 15:23 98-NetworkManager
-rwxrwxr-x+ 1 root root  421 Feb 29 17:05 99-fixEntries
```
</details>
<details>
<summary>File: /lib/systemd/system-sleep/<b>10-systemd-networkd</b></summary>

```sh
#!/bin/sh
set -e

case "$1" in
  # pre)
  #   /bin/systemctl stop systemd-networkd
  #   ;;
  post)
    /bin/systemctl restart systemd-networkd
    ;;
esac
```
</details>

Bugy behavior is triggered with these steps:
1. Use the `10-mb-eth0.link` and `10-mb-eth0.network` files from above.
   - (edit to your needs, i have hidden some data)
2. Boot your PC or restart `systemd-networkd`
3. Check that all IP's are available on the device: `ip addr show dmz0`
   - Shows 6 IP's in total on my system
4. Manually put the system into sleep with your preferred option to do so.
5. Resume the system from sleep.
6. Check that all IP's are available on the device: `ip addr show dmz0`, **you will miss some**.

To correct it:
1. Place the `10-systemd-networkd` file from above in it's directory.
   - I have some more in that directory that stop/restart some other services also as can be seen in the directory listing, but they are not needed to reproduce this bug...
2. Repeat steps 2-5 from above.
3. This time all IP's are available on the device: `ip addr show dmz0`

**Comment by ssahani** [comment]
Hmm it seems a puzzle to me . Should I close my laptop lid 4/5 times or Pause fedora running VMware fusion on MAC  and resume . Can you paste some debug logs here. 

 The log can be generated by creating e.g. the following drop-in config:

```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by TriMoon** [comment]
@ssahani hi sorry i saw your post last night just before i went to bed so i could not reply.

BTW: is there any other place we can put those sleep scripts instead of `/lib/systemd/system-sleep` because it is not documented.

I will try in a few minutes and give the info you asked for, after removing the scripts from `/lib/systemd/system-sleep` for a clean log.

/please hold on wait...

**Comment by yuwata** [comment]
I guess, a workaround for this issue is setting `IgnoreCarrierLoss=yes` in `[Network]` section.

**Comment by yuwata** [comment]
Are there any chance to test with the current git master, v245-rc1 or rc2?

**Comment by TriMoon** [comment]
> Are there any chance to test with the current git master, v245-rc1 or rc2?

no sorry unfortunately.

> I guess, a workaround for this issue is setting `IgnoreCarrierLoss=yes` in `[Network]` section.

That is not an option because i need feedback in that case under normal operation...
My current workaround are the files under `/lib/systemd/system-sleep` i posted in OP...

**Comment by yuwata** [comment]
> > Are there any chance to test with the current git master, v245-rc1 or rc2?
> 
> no sorry unfortunately.

Sad news.

> > I guess, a workaround for this issue is setting `IgnoreCarrierLoss=yes` in `[Network]` section.
> 
> That is not an option because i need feedback in that case under normal operation...
> My current workaround are the files under `/lib/systemd/system-sleep` i posted in OP...

Yeah, I forgot your workaround. Thank you for the feedback.

**Comment by TriMoon** [comment]
PS: Are we able to put the files under `/etc/systemd/system-sleep` instead of `/lib/systemd/system-sleep`? Because i could not find any documentation that allows it...

**Comment by yuwata** [comment]
As documented in systemd-suspend.service(8), /etc/systemd/system-sleep seems not supported yet.

**Comment by TriMoon** [comment]
Then that's another inconsistency that needs fixed :wink: 
Thanks so far and hope this bug gets fixed and distributed to debian/ubuntu package repos soon :+1:

**Comment by yuwata** [comment]
> Then that's another inconsistency that needs fixed 

Filed as #15000.

**Comment by TriMoon** [comment]
because you made https://github.com/systemd/systemd/issues/15000 a dupe of  https://github.com/systemd/systemd/issues/4927  i thought i better mention it here also for cross-linking :wink:
