### ISSUE TITLE
If binfmts with the 'F' flag are registered through systemd-binfmt, the root filesystem fails to unmount during shutdown

### ISSUE THREAD

**Issue by joanbm** [systemd/systemd#14981]
**systemd version the issue has been seen with**
systemd 244.3 ([Arch package](https://www.archlinux.org/packages/core/x86_64/systemd/))

**Used distribution**
Arch Linux, updated as of 2020-02-29 (reproduced in a new VM)

I have also been able to reproduce the issue with a clean install of Ubuntu 19.10 Server.

**Expected behaviour you didn't see**

Independently of the binfmts that have been registered (through systemd-binfmt), the system should be able to shut down cleanly, including unmounting the root filesystem correctly.

**Unexpected behaviour you saw**

Depending of the binfmts registered through systemd-binfmt (see steps and further information below), it's possible that during shutdown/reboot/kexec, unmounting the root filesystem fails. In this case, a series of messages like this is printed to the console when shutting down:

    sd-umount[1334]: Failed to unmount /oldroot: Device or resource busy
    shutdown[1]: Failed to finalize file systems, ignoring.

Similar messages have already been reported sometimes (see [1], [2]), and can have multiple causes. This report presents a way to reproduce one of them which appears to be due to the behaviour of systemd.

**Steps to reproduce the problem**

It is enough to create a file in /lib/binfmt.d/TestFormat.conf with the following content:

     :TestFormat:M::XX::/usr/bin/true:F

After this, make sure the format is registered by systemd-binfmt (in both Arch and Ubuntu 19.10, this is done automatically on the next reboot).

After this format has been registered, during every subsequent shutdown/reboot/kexec, the mentioned error message is printed to the kernel's console, implying that the root filesystem can not be unmounted correctly. (If you can't see it, try booting with the `debug` kernel parameter and/or setting a sensible value in `/proc/sys/kernel/printk_delay`, since the message appears very late during shutdown).

The `F` flag in the last field of the registered binfmt is necessary for the problem to trigger. The meaning of the `F` flag is explained here: https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html and seems to imply that it keeps a reference to the interpreter binary, so that's likely the file that's still open during shutdown and causes the unmount to fail. This flag is often useful for e.g. QEMU static binaries.

As explained in [3], when the systemd-binfmt service, which originally registered the format, is stopped, the format is not de-registered. Unmounting the `binfmt_misc` filesystem from `/proc/sys/fs/binfmt_misc/` does also not de-register the formats (I believe this is expected behaviour). During systemd's shutdown process, the binfmts are not de-registered along other mounts, loopbacks, swaps, etc.. This, along with the behaviour of the `F` flag which seems to keep a file reference to the interpreter, seems to be the cause of the root filesystem unmount to fail.

Either making systemd-binfmt de-register the formats when stopped (as in [3]), or making the shutdown process de-register the binfmts as part of the other cleanup steps, would be enough to get the root filesystem to unmount cleanly.

**Links**

[1]: [Arch Linux FS#63697 - systemd 243.0-1 poweroff/reboot umount errors ](https://bugs.archlinux.org/task/63697)
[2]: [systemd issue #14298 -  sd-umount: Failed to unmount /oldroot: Device or resource busy](https://github.com/systemd/systemd/issues/14298)
[3]: [systemd issue #13129 - "systemctl stop systemd-binfmt" should remove the registered entries?](https://github.com/systemd/systemd/issues/13129)

**Comment by marscher** [comment]
Back in the old days we would have "solved" this by a lazy umount. But I guess nowadays we pretend to be more clever about things.

As mentioned in [1], this could be triggered by any misbehaving service/process still holding a file handle. Probably this is why one should kill processes (gently) prior trying to unmount filesystems...

I'm currently suffering from this bug, but in combination with LVM caching. The failure to umount the root filesystem culminate in a failure to properly detach the DM devices. This marks the cache dirty after the reboot resulting in copying over all cached pages (for the whole FS) again. My SSD would die soon, if I would reboot too often.

This is printed to console before reboot:
```
  sd-unmou[1158]: Failed to unmount /oldroot/sys: Device or resource busy
  shutdown[1]: Could not detach DM /dev/dm-4: Device or resource busy
  shutdown[1]: Could not detach DM /dev/dm-3: Device or resource busy
  shutdown[1]: Could not detach DM /dev/dm-2: Device or resource busy
  shutdown[1]: Could not detach DM /dev/dm-1: Device or resource busy
  shutdown[1]: Failed to finalize  filesystems, DM devices, ignoring
```

The last message is particularly funny, it risks data corruption just for the sake of an instant reboot. Why the heck is it ignored? This should only be the case if the admin is willing to take the risk of data loss/corruption by putting a sanity flag.

So actually this is just a symptom of a faulty design decision (not gently killing procs, not forcefully closing handles before umount).

I would love to be corrected (if possible) about my strong opinion :+1:

**Comment by marscher** [comment]
most likely related: https://github.com/systemd/systemd/issues/15004

**Comment by poettering** [comment]
Ah, christ. What a weird interface...

**Comment by poettering** [comment]
Fix waiting in #15566

**Comment by joanbm** [comment]
Just as a quick heads up, I can confirm the patch (applied over v245.5) fixes the problem for me. Thanks!

**Comment by joe733** [comment]
Hi, I'm getting the same message:
```
sd-umount[1675]: Failed to unmount /oldroot: Device or resource busy
sd-umount[1676]: Failed to unmount /oldroot: Device or resource busy
shutdown[1]: Failed to finalize file systems, ignoring.
```

on
```
➜ yay -Qi systemd           
Name            : systemd
Version         : 249.5-1
Description     : system and service manager
Architecture    : x86_64
URL             : https://www.github.com/systemd/systemd
Licenses        : GPL2  LGPL2.1
Groups          : None
Provides        : nss-myhostname  systemd-tools=249.5  udev=249.5
Depends On      : acl  libacl.so=1-64  bash  cryptsetup  libcryptsetup.so=12-64  dbus  iptables  kbd  kmod  libkmod.so=2-64
                  hwids  libcap  libcap.so=2-64  libgcrypt  libxcrypt  libcrypt.so=2-64  systemd-libs  libidn2  lz4  pam  libelf
                  libseccomp  libseccomp.so=2-64  util-linux  libblkid.so=1-64  libmount.so=1-64  xz  pcre2  audit
                  libaudit.so=1-64  libp11-kit  libp11-kit.so=0-64  openssl
Optional Deps   : libmicrohttpd: remote journald capabilities
                  quota-tools: kernel-level quota management
                  systemd-sysvcompat: symlink package to provide sysvinit binaries [installed]
                  polkit: allow administration as unprivileged user [installed]
                  curl: machinectl pull-tar and pull-raw [installed]
                  libfido2: unlocking LUKS2 volumes with FIDO2 token
                  tpm2-tss: unlocking LUKS2 volumes with TPM2
Required By     : accountsservice  android-udev  base  bluez-utils  bolt  colord  cups  cups-filters  gdm  gnome-bluetooth
                  gnome-desktop  gnome-disk-utility  gnome-logs  gnome-remote-desktop  gnome-session  gnome-settings-daemon
                  gnome-system-monitor  libcolord  libgdm  libgudev  libinput  libpulse  libwacom  media-player-info  mkinitcpio
                  pcsclite  phodav  plymouth-git  polkit  rtkit  systemd-sysvcompat  upower  vte3  xdg-user-dirs
Optional For    : None
Conflicts With  : nss-myhostname  systemd-tools  udev
Replaces        : nss-myhostname  systemd-tools  udev
Installed Size  : 25.80 MiB
Packager        : Christian Hesse <arch@eworm.de>
Build Date      : Wed 13 Oct 2021 03:05:21 AM IST
Install Date    : Fri 15 Oct 2021 03:02:42 PM IST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature
```

how do I debug to resolve this?

**Comment by joanbm** [comment]
@joe733 This problem has many causes, see [Arch Linux FS#63697](https://bugs.archlinux.org/task/63697). I don't know any painless way to debug it, but try to boot your system with as little services as possible until it no longer reproduces then start adding services until you find the culprit.
