### ISSUE TITLE
Better support for UseRoutes in DHCP4

### ISSUE THREAD

**Issue by sunil-mukundan** [systemd/systemd#14982]
**Is your feature request related to a problem? Please describe.**
we want to disable requesting `rfc3442-classless-static-routes` and we are doing that by setting `UseRoutes` to `False`. This works as expected and the DHCP server does not send the classless routes, but this results in the DHCP server sending back a default gateway (via the `router` option) which does not get installed (maybe this is actually a bug because technically the UseRoutes flag should only ignore the static routes and not the default gateway)

**Describe the solution you'd like**
Have the ability to control the installation of static routes (via `rfc3442-classless-static-routes`) and the ability to control the installation of default gateway with two different flags `UseRoutes` and `UseRouter`

**Describe alternatives you've considered**
N.A

**Comment by ssahani** [comment]
>This works as expected and the DHCP server does not send the classless routes, but this results in the DHCP server sending back a default gateway (via the router option) which does not get installed (maybe this is actually a bug because technically the UseRoutes flag should only ignore the static routes and not the default gateway)

RFC 3442 DHCP Client Behavior:
  If the DHCP server returns both a Classless Static Routes option and                                                                             a Router option, the DHCP client MUST ignore the Router option.

**Comment by sunil-mukundan** [comment]
> > This works as expected and the DHCP server does not send the classless routes, but this results in the DHCP server sending back a default gateway (via the router option) which does not get installed (maybe this is actually a bug because technically the UseRoutes flag should only ignore the static routes and not the default gateway)
> 
> RFC 3442 DHCP Client Behavior:
> If the DHCP server returns both a Classless Static Routes option and a Router option, the DHCP client MUST ignore the Router option.

@ssahani i agree

What i was asking is this
I use `UseRoutes=False` so the DHCP request itself does not request for Classless Static Routes option. As a result, the DHCP server will only respond with a Router option. In this case since we are using the `UseRoutes=False` option, `link_set_dhcp_routes` bails out right at the top of the function without even installing the `gateway` that comes in via the router option

**Comment by ssahani** [comment]
Hmm I see what you saying . Please test https://github.com/systemd/systemd/pull/14983 with `_dhcp` in https://www.freedesktop.org/software/systemd/man/systemd.network.html#Gateway=2

I have not tested it.

**Comment by sunilfff** [comment]
@ssahani thanks . Will check

**Comment by sunil-mukundan** [comment]
@ssahani thanks . Will check

**Comment by sunil-mukundan** [comment]
@ssahani we verified this issue in our setup. thanks for the help.
