### ISSUE TITLE
time-sync.target is not triggered after successful time synchronization

### ISSUE THREAD

**Issue by lewisdiamond** [systemd/systemd#14994]
**systemd version the issue has been seen with**
> systemd 244 (244.3-1-arch)

**Used distribution**
 > Archlinux arm

**Expected behaviour you didn't see**
 > After time synchronization, time-sync.target should be active

**Unexpected behaviour you saw**
 > After time synchronization, time-sync.target is inactive (dead)

**Steps to reproduce the problem**
Unfortunately, other than rebooting the raspberry pi until it fails to activate, I don't currently have better repro steps.

More information:
```
systemctl status time-sync.target

* time-sync.target - System Time Synchronized
     Loaded: loaded (/usr/lib/systemd/system/time-sync.target; static; vendor preset: disabled)
     Active: inactive (dead)
       Docs: man:systemd.special(7)

Mar 02 11:27:23 HOSTNAME systemd[1]: time-sync.target: Merged time-sync.target/start into installed job time-sync.target/start as 11
Mar 02 11:28:26 HOSTNAME systemd[1]: time-sync.target: Merged time-sync.target/start into installed job time-sync.target/start as 11
```
```
systemctl status systemd-timesyncd.service

* systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-03-02 11:27:24 EST; 32min ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 8821 (systemd-timesyn)
     Status: "Initial synchronization to time server 205.206.70.7:123 (0.arch.pool.ntp.org)."
      Tasks: 2 (limit: 2204)
     Memory: 1.0M
     CGroup: /system.slice/systemd-timesyncd.service
             `-8821 /usr/lib/systemd/systemd-timesyncd

Mar 02 11:42:55 HOSTNAME systemd[1]: systemd-timesyncd.service: Got notification message from PID 8821 (WATCHDOG=1)
Mar 02 11:44:55 HOSTNAME systemd[1]: systemd-timesyncd.service: Got notification message from PID 8821 (WATCHDOG=1)
```
```
ls -alh /run/systemd/timesync/synchronized

-rw-r--r-- 1 systemd-timesync systemd-timesync 0 Mar  2 11:43 /run/systemd/timesync/synchronized
```

**Comment by keszybz** [comment]
Please the full boot log (with systemd.log-level=debug is possible), and also `systemctl status time-set.target`.

**Comment by lewisdiamond** [comment]
Here is the status of `time-set.target`
```
     Loaded: loaded (/usr/lib/systemd/system/time-set.target; static; vendor preset: disabled)
     Active: active since Thu 2020-02-13 15:07:08 EST; 2 weeks 4 days ago
       Docs: man:systemd.special(7)
```
As for the boot log, I'll do my best to repro it on a dev device.

**Comment by lewisdiamond** [comment]
[bootlog.txt](https://github.com/systemd/systemd/files/4281998/bootlog.txt)

**Comment by keszybz** [comment]
This might be fixed by 097537f07a. Please test v245-rc2.

**Comment by poettering** [comment]
time-sync.target is a passive unit, it's only pulled in by stuff that wants it. Are you sure any of your services pull it in? i.e. we minimize synchronization points, and if noone wants to wait for the time being sync'ed we don't bother inserting the unit into the boot process and having an extra sync point.

**Comment by poettering** [comment]
see systemd.special(7) man page for details about the target, that explains this.

**Comment by lewisdiamond** [comment]
Can't reproduce in 245
