### ISSUE TITLE
please extend udev hwdb list to cover Olimex Teres-I DIY laptop kit

### ISSUE THREAD

**Issue by jonassmedegaard** [systemd/systemd#15003]
Please include the following to file `/lib/udev/hwdb.d/60-keyboard.hwdb` to have working media keys for the Olimex Teres-I DIY laptop kit:
```
###########################################################
# Olimex
###########################################################

# Teres-I
evdev:input:b0003v15BAp003C*
 KEYBOARD_KEY_70066=sleep                               # Fn+F1
 KEYBOARD_KEY_700f6=wlan                                # Fn+F2
 KEYBOARD_KEY_700c7=f21                                 # Fn+F3 touchpad toggle
 KEYBOARD_KEY_7006f=brightnessdown                      # Fn+F7
 KEYBOARD_KEY_70070=brightnessup                        # Fn+F8
 KEYBOARD_KEY_7006e=switchvideomode                     # Fn+F9
```

**Comment by boucman** [comment]
Could you please submit as a pull-request instead of an issue ?
It's way easier for the systemd team to review/merge that way...

**Comment by jonassmedegaard** [comment]
Sorry, I understand how that is more convenient but I am not comfortable pushing code patches to Github due to their terms of use.

I can offer to setup a fork of this git somewhere else, for you to cherry-pick from - but I suspect that would not really be any easier for you than to just pick the change from here.
