### ISSUE TITLE
journalctl -u sshd No entry found

### ISSUE THREAD

**Issue by ketonik** [systemd/systemd#15015]
**systemd version the issue has been seen with**
> ...
`244`

**Used distribution**
 > …
`Clear Linux 32510`
**Expected behaviour you didn't see**
 > …
`printed log sshd entries`
**Unexpected behaviour you saw**
 > …
`No entry found`
**Steps to reproduce the problem**
`journalctl -u sshd`
`journalctl -u sshd.service`

Discovered printed message can be achieve by
`journalctl _COMM=sshd`

But why make this change? Now, years of command line example tutorials, cheat sheets etc on the www will be invalid redundant without explanation causing confusion and costing people time figuring out how to get sshd log entries with joournalctl

Second, `COMM` is illogical, sshd is not a `command` but a  UNIT, a binary , an executable.
`journalctl _COMM=sshd` in its entirety IS a command, not sshd.

Please revert back to sensible behaviour:
`journalctl -u sshd`

**Comment by keszybz** [comment]
I have no idea why you're not seeing the messages with `journalctl -u`. The results depend on the unit configuration and maybe clear linux has made some modifications to change unit names. No changes in this area have been made upstream (and `journalctl -u sshd` certainly works here with git master). Seems to be a downstream issue, please file a report against your distro.

**Comment by ahkok** [comment]
We start sshd.socket. Not sshd.service. Instantiated units like sshd@.service's output end up in the journal, but not in `-u sshd`.

```
$ journalctl -a |grep sshd|wc -l
29
$ journalctl -a -u sshd |grep sshd |wc -l
0
```

**Comment by ahkok** [comment]
As I mentioned, this totally worked before. We don't have any patches to the journal to filter out things like this. We do carry some patches, but nothing touching the journal this way.

**Comment by ahkok** [comment]
@keszybz your thoughts? I assume you're using `sshd.service` and overlooked that we're using the `socket` unit instead.

**Comment by ahkok** [comment]
Looks like my suspicion is correct:

```
 journalctl -u sshd@blablabla.service -o verbose
-- Logs begin at Fri 2020-02-28 21:51:03 PST, end at Wed 2020-03-04 10:24:57 PST. --

    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd

    _COMM=systemd
    _EXE=/usr/lib/systemd/systemd
    _CMDLINE=/usr/lib/systemd/systemd --system --deserialize 56
    _CAP_EFFECTIVE=3fffffffff
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice

    PRIORITY=6
    CODE_FILE=src/core/unit.c
    CODE_LINE=5750
    CODE_FUNC=unit_log_success

    UNIT=sshd@blablabla.service
    MESSAGE=sshd@blablabla.service: Succeeded.
    _SOURCE_REALTIME_TIMESTAMP=1583229921682586
```

I'm digging through our patches, again, but, fairly sure I'll come up empty.

**Comment by ahkok** [comment]
Cannot reproduce this as far as 2+ years back. My memory must be playing tricks on me. Sorry for thrashing everyone's time here.

**Comment by pythonwood** [comment]
It happend to me and find this. ubuntu 22.04. 

`journalctl -u sshd -f ` NOT OK
`journalctl -a |grep sshd` OK
`journalctl _COMM=sshd` OK
