### ISSUE TITLE
nspawn: rootfs in oci bundle not resilved

### ISSUE THREAD

**Issue by RoadRunnr** [systemd/systemd#15018]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Ubuntu 19.10

**Expected behaviour you didn't see**

nspawn find rootfs relative to bundle

**Unexpected behaviour you saw**

```
systemd-nspawn --oci-bundle=./bundles/upf/
Failed to resolve path rootfs: No such file or directory
```

config.json:

```
        "root": {
                "path": "rootfs"
        },
```

bundle content:

```
# ls -l bundles/upf/
total 1136
drwxr-xr-x  3 root root    4096 Mar  4 16:23 blobs
-rw-r--r--  1 root root    3500 Mar  4 16:26 config.json
-rw-r--r--  1 root root     286 Mar  4 16:23 index.json
-rw-r--r--  1 root root      31 Mar  4 16:23 oci-layout
drwxr-xr-x 22 root root    4096 Jan  1  1970 rootfs
-rw-r--r--  1 root root 1134976 Mar  4 16:23 sha256_e44044477c4a3775e1f79cf5e1832f271f57713cd43eeae5e8b051d27a8ef07e.mtree
-rw-r--r--  1 root root     393 Mar  4 16:23 umoci.json
```

**Steps to reproduce the problem**

create OCI bundle with relative path to rootfs

** Explanation **

OCI specification says:

> On POSIX platforms, path is either an absolute path or a relative path to the bundle. For example, with a bundle at /to/bundle and a root filesystem at /to/bundle/rootfs, the path value can be either /to/bundle/rootfs or rootfs. The value SHOULD be the conventional rootfs.

So, nspawn should try locate the rootfs relative to the config.json, what it does it tries to find the rootfs in the current working directory.

**Comment by poettering** [comment]
I am pretty sure this was fixed already with #14689. Please try that. And if it doesn't work report back and we can reopen this.
