### ISSUE TITLE
systemd-firstboot accepts no input

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#15011]
**systemd version the issue has been seen with**
> 244.3-1

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
I expect that systemd-firstboot would do something after I press "any" key.

**Unexpected behaviour you saw**
When I boot into systemd-firstboot I get stucked in the welcome screen and the system doesn't accept input.
...
-- Press any key to proceed --

**Steps to reproduce the problem**

Use mkosi to reproduce this issue:

==> minimal.default <==
```
[Distribution]
Distribution=arch

[Output]
Format=raw_gpt
Bootable=yes
Firstboot=yes
Output=minimal.img
```

==> minimal.postinst <==
```
#!/bin/bash

cat > /etc/systemd/system/systemd-firstboot.service << EOF
[Unit]
Description=First Boot Wizard
Documentation=man:systemd-firstboot(1)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-remount-fs.service
Before=systemd-sysusers.service sysinit.target shutdown.target
ConditionPathIsReadWrite=/etc
ConditionFirstBoot=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemd-firstboot --prompt --setup-machine-id
StandardOutput=tty
StandardInput=tty
StandardError=tty

[Install]
WantedBy=sysinit.target
EOF

systemctl enable systemd-firstboot.service

```

Then boot the image via qemu: 
`qemu-system-x86_64 -m 512 -smp 2 -bios /usr/share/ovmf/x64/OVMF_CODE.fd -drive format=raw,file=minimal.img -serial stdio -show-cursor`

**Note: You need this patch for mkosi: https://github.com/systemd/mkosi/pull/385**

**Comment by shibumi** [comment]
Ok,
I had a proper look on `systemd-firstboot` in systemd 244.3 and I came to the conclusion that it's systematically broken.

Here are just a few other bugs I've found in less than 5min playing around with it:

When Invoking `systemd-firstboot --prompt-locale` or `systemd-firstboot --prompt-keymap` or `systemd-firstboot --prompt-timezone` I get the following error:

`systemd-firstboot: unrecognized option`

When I do `systemd-firstboot --prompt-hostname` I get no prompt or anything at all. The process just exits with status code 0. Same for `systemd-firstboot --prompt-root-password`.

When I call `systemd-firstboot --prompt` it doesn't ask for all options (as stated in the help message)..

I am not sure if this is related to the fact that i have tested it on a system that has booted already.
But I guess that the `--prompt-*` options should at least work?!

**Comment by shibumi** [comment]
Note: This problem persists in systemd-245.

**Comment by poettering** [comment]
Note that systemd-firstboot will only prompt you about stuff that is not initialized yet. i.e. if from a running system that has a hostname set you do `systemd-firstboot --prompt-hostname`, then nothing happens because there already has been a hostname set. See the man page about this: "If a setting is already initialized, it will not be overwritten and the user will not be prompted for the setting."

The idea is that OS vendors can initialize /etc as much or as little as they want, systemd-firstboot will initialize what's missing on first boot. i.e. that way you can provision a timezone and firstboot won't ask about it, but you will still be queried about your root pw.

systemd-firstboot needs no special setup, it's automatically invoked when /etc is empty and will query you for stuff not filled in, hence not sure why you create the service file for it?

if the tool doesn't react to your keypresses, maybe its colliding with something else on your console tht also reads from it?

It should generally just work and require not manual set up, as long as /etc/machine-id is missing.

**Comment by shibumi** [comment]
So the solution would be to empty /etc/, is this correct? Wouldn't I remove other important configurations like /etc/ssh/sshd_config with this approach? Do you have a list of files that needs to be removed for a full initialization? For hostname it will be `/etc/hostname`, I guess.

Interesting, if there is no service needed then this wiki article is absolutely wrong and should be changed: https://wiki.archlinux.org/index.php/Systemd-firstboot

**Comment by poettering** [comment]
the man page says explicitly which switch initializes which file, have a look. If you delete all mentioned files it should prompt you for all of them again.

**Comment by poettering** [comment]
If you drop your own service file you added, and boot with a missing /etc/machine-id and a few of the files mentioned removed, does it work then?

**Comment by shibumi** [comment]
Thanks for your feedback, I will have a look on it asap.
Do I even need my own service file? You said, it's not needed and systemd-firstboot should just start.

**Comment by poettering** [comment]
you don't need it. the idea really is to work fully automatically with the existing service: if we detect a first boot (which is defined as /etc/machine-id not existing), we'll ask for all settings for which the respective config file in /etc is also not existing. This means people can easily provision every single setting.

**Comment by shibumi** [comment]
Ok, I have the following in my mkosi.postinst file now:

```
#!/bin/bash

# clean locale
rm /etc/locale.cconf
# clean timezone
rm /etc/localtime
# clean keymap
rm /etc/vconsole.conf
# clean hostname
rm /etc/hostname
# clean shadow file
rm /etc/shadow
```

I hope this is all what is needed for a full systemd-firstboot.
mkosi is running now, I will update this comment when it works/not works.

**Comment by shibumi** [comment]
Ok I don't know if this is a QEMU thing, but the problem persists. I can't insert any key, because systemd-firstboot ignores all input or another application is grabbing it or this is a QEMU bug. Even `sendkey` via QEMU monitor fails.

But I can confirm that systemd-firstboot boots up without the service file.

My mkosi files are looking like this:
```
[Distribution]
Distribution=arch

[Output]
Format=raw_gpt
Bootable=yes
Firstboot=yes
Output=minimal.img
```

```
#!/bin/bash

# clean locale
rm /etc/locale.cconf
# clean timezone
rm /etc/localtime
# clean keymap
rm /etc/vconsole.conf
# clean hostname
rm /etc/hostname
# clean shadow file
rm /etc/shadow
```

`sudo mkosi --default minimal/minimal.default --postinst minimal/minimal.postinst --root-size=2G --force`

(note: you need my mkosi firstboot patch).

my Qemu line is this one:
`qemu-system-x86_64 -m 512 -smp 2 -bios /usr/share/ovmf/x64/OVMF_CODE.fd -drive format=raw,file=minimal.img -serial stdio -show-cursor`

**Comment by shibumi** [comment]
Update: 

`minimal.default`:
```ini
[Distribution]
Distribution=arch

[Output]
Format=raw_gpt
Bootable=yes
Output=minimal.img
```

`minimal.postinst`:
```shell
#!/bin/bash

cat > /etc/systemd/system/systemd-firstboot.service << EOF
[Unit]
Description=First Boot Wizard
Documentation=man:systemd-firstboot(1)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-remount-fs.service
Before=systemd-sysusers.service sysinit.target shutdown.target
ConditionPathIsReadWrite=/etc
ConditionFirstBoot=yes

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemd-firstboot --prompt --setup-machine-id
StandardOutput=tty
StandardInput=tty
StandardError=tty

[Install]
WantedBy=sysinit.target
EOF

systemctl enable systemd-firstboot.service
# clean locale
rm /etc/locale.cconf
# clean timezone
rm /etc/localtime
# clean keymap
rm /etc/vconsole.conf
# clean hostname
rm /etc/hostname
# clean shadow file
rm /etc/shadow
# delete machine-id
rm /etc/machine-id
```

Running:

1. `sudo mkosi --default minimal/minimal.default --postinst minimal/minimal.postinst --root-size=2G --force`
2. `qemu-system-x86_64 -m 512 -smp 2 -bios /usr/share/ovmf/x64/OVMF_CODE.fd -drive format=raw,file=minimal.img`

Still, no systemd-firstboot :(

if I use `sudo mkosi --default minimal/minimal.default --postinst minimal/minimal.postinst --root-size=2G --force --remove-files '/etc/*'`

systemd will hang at "starting graphical.target" and do nothing... same happens when I delete whole /etc/* via postinst script.

What am I missing here?

**Comment by shibumi** [comment]
This is not an issue anymore. systemd-firstboot works fine now.
