### ISSUE TITLE
networkd: Emit link local as DNS in DHCPServer

### ISSUE THREAD

**Issue by TheoGoudout** [systemd/systemd#15026]
I would like to setup a network interface as

```
[Match]
Type=wlan
Name=wlan0

[Network]
Description=Main LAN interface
Address=0.0.0.0/24
Address=::/64
DHCPServer=yes

[DHCPServer]
PoolOffset=10
PoolSize=40
DefaultLeaseTimeSec=600
MaxLeaseTimeSec=7200
EmitDNS=yes
DNS=_link_local
```

But when using `Address=0.0.0.0/24` I have no way to specify link local as a DNS server. Something similar exists in `[IPv6PrefixDelegation]`.

For now, the only workaround (AFAICT) is to specify explicitly the address range to use.

**Comment by yuwata** [comment]
`_link_local` sounds IPv4LL. So, maybe `_self` is better?
