### ISSUE TITLE
sshd.socket stops after daemon-reload

### ISSUE THREAD

**Issue by vlsunil** [systemd/systemd#15037]
**systemd version the issue has been seen with**
> ...237

**Used distribution**
 > …Yocto

**Expected behaviour you didn't see**
 > …sshd.socket unit should not stop just because of daemon-reload. For headless servers, it is a problem if we can't connect using ssh. 

**Unexpected behaviour you saw**
 > …sshd.socket stops working after daemon-reload. But it happens only first time after the boot. Once sshd.socket is restarted, the next daemon-reload doesn't cause sshd.unit to stop. 
Below messages are seen.
sshd.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.

I have not changes any unit files manually. 

**Steps to reproduce the problem**
I am using yocto distribution and it is easily reproducible. Let me know what data I can gather.

**Comment by QuantumLove** [comment]
I am experiencing the same, how did you solve it?

**Comment by vlsunil** [comment]
@QuantumLove  : Sorry, I moved out of that project. Please open the issue if you are seeing the issue.
