### ISSUE TITLE
Every boot has a 91 second "Wait until kernel time synchronized" timer

### ISSUE THREAD

**Issue by gavinhoward** [systemd/systemd#15031]
**systemd version the issue has been seen with**
```
244
```

**Used distribution**
 EndeavourOS, fully updated.

**Expected behaviour you didn't see**
 Quick boot (about 30 seconds).

**Unexpected behaviour you saw**
 91 seconds with the same message:

```
[***   ] Start job for wait until kernel time synchronized 1m 31s/no limit
```

Note: the timer changes, and the three asterisks move back and forth, but the message may not be exact.

It always quits at exactly 1m 31s.

This is not a slow network problem because it only happens on my desktop; my laptop, on the same network, boots fine. It doesn't have an Nvidia card (see below).

**Steps to reproduce the problem**
Install EndeavourOS, including with Nvidia drivers (I can't reproduce the problem without them), and reboot.

**Comment by refi64** [comment]
This is most likely an issue with the NVIDIA driver and the kernel or
something else that is also Endeavor OS-specific, see:
https://forum.endeavouros.com/t/wait-until-kernel-time-synchronized/3524/10

**Comment by gavinhoward** [comment]
Thank you for that link; I didn't find it when trying to search the EndeavourOS forums.

For those coming here from Google, it seems this command does the trick:

```
systemctl disable systemd-time-wait-sync
```
