### ISSUE TITLE
Not getting new values for property along with PropertiesChanged signal

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#1503]
I am writing a monitoring application to start, stop and monitor service state.

I am looking for way to know when service stopped or failed so that i can take some action in my monitoring app.

I am listening to PropertiesChanged signal and query ActiveState. This does not work always.
Some times, unit is unloaded before I query the ActiveState. What is the solution for this 
Do we get new values of property along with PropertiesChanged signal in new version of systemd?
if yes in which version this feature was added ?
What is the best way  to achieve my requirement ?

**Comment by poettering** [comment]
THis is not a support forum but a bug tracker. Please send questions like yours to the systemd mailing list instead. Thanks!
