### ISSUE TITLE
homed: if fallocate() is not supported (zfs, reiserfs etc.) fall back to plain ftruncate()

### ISSUE THREAD

**Issue by sandhoners123** [systemd/systemd#15059]
**systemd version the issue has been seen with**
> ... 245

**Used distribution**
 > … Arch Linux (with Root on ZFS)

**Expected behaviour you didn't see**
 > …
When using homectl, it should create my home and not give “failed to set extended attributes operation not supported” in systemd journal. Or it should say that systemd-homed is not supported on ZFS
**Unexpected behaviour you saw**
 > …
Homectl gives an error: Unable to create home
failed to set extended attributes operation not supported in journal
**Steps to reproduce the problem**
1. Try to create a home in any root-on-zfs distro 
2. It will fail with this error in journal

**Comment by sandhoners123** [comment]
`sudo homectl create ShadowsightWC`
`Please enter new password for user ShadowsightWC: ********`              
`Please enter new password for user ShadowsightWC (repeat): (press TAB for no ech********`
`Failed to create user home: Failed to execute operation: Operation not supported`
And in the logs

● systemd-homed.service - Home Manager
     Loaded: loaded (/usr/lib/systemd/system/systemd-homed.service; static; vendor preset: disabled)
     Active: active (running) since Tue 2020-03-17 11:04:29 IST; 3 days ago
       Docs: man:systemd-homed.service(8)
   Main PID: 1695 (systemd-homed)
     Status: "Processing requests..."
      Tasks: 1 (limit: 3791)
     Memory: 2.4M
     CGroup: /system.slice/systemd-homed.service
             └─1695 /usr/lib/systemd/systemd-homed

Mar 17 11:04:27 Rootspring systemd[1]: Starting Home Manager...
Mar 17 11:04:28 Rootspring systemd-homed[1695]: Successfully loaded private key pair.
Mar 17 11:04:29 Rootspring systemd[1]: Started Home Manager.
Mar 21 10:23:01 Rootspring systemd-homed[1695]: ShadowsightWC: changing state absent → creating
Mar 21 10:23:01 Rootspring systemd-homework[169991]: Sizing home to 85% of available disk space, which is 679.6G.
Mar 21 10:23:01 Rootspring systemd-homework[169991]: Failed to set file attributes on /home/.#homeworkShadowsightWC.home9166ea4e3c9758d9, ignoring: Operation not supported
Mar 21 10:23:01 Rootspring systemd-homework[169991]: Failed to truncate home image /home/.#homeworkShadowsightWC.home9166ea4e3c9758d9: Operation not supported
Mar 21 10:23:01 Rootspring systemd-homed[1695]: Operation on ShadowsightWC failed: Operation not supported

**Comment by poettering** [comment]
hmm ZFS doesn't support fallocate()? hmpf... that's quite a limitation...

I guess we can automatically fallback to ftruncate if fallocate doesn't work. 

In the meantime if you pass `--luks-discard=yes` things should work for you. Can you try?

**Comment by sandhoners123** [comment]
Yes, passing luks-discard=yes works, however, it is still not a permanent fix (hopefully will be fixed with v246). 
Also, it is not just ZFS. IIRC, ReiserFS also does not support fallocate, so this should also fix ReiserFS in homed

**Comment by poettering** [comment]
Fix waiting in #15297.
