### ISSUE TITLE
libmount support required but libraries

### ISSUE THREAD

**Issue by kennedy-han** [systemd/systemd#1506]
when run `./configure`

its show me

```
checking for XKBCOMMON... no
checking for BLKID... no
checking for MOUNT... no
configure: error: *** libmount support required but libraries not found
```

I use ubuntu 14.04 LTS x64

**Comment by martinpitt** [comment]
Ubuntu 14.04's util-linux is too old for systemd 227, which requires util-linux 2.27. If you want, you can use https://launchpad.net/~pitti/+archive/ubuntu/systemd-semaphore to get util-linux 2.27 for Ubuntu 14.04 (but I don't give support for this at all! This PPA just exists just for running distcheck for upstream integration testing).

**Comment by kennedy-han** [comment]
thanks, I install from tarbal the util-linux 2.27 and it's worked.
