### ISSUE TITLE
Add a service condition for $XDG_SESSION_TYPE

### ISSUE THREAD

**Issue by emersion** [systemd/systemd#15067]
**Is your feature request related to a problem? Please describe.**

Some services may only support one session type, e.g. Wayland and not X11.

See https://github.com/emersion/mako/pull/240#issuecomment-597122444

**Describe the solution you'd like**

```
WantedBy=graphical-session.target
ConditionSessionType=wayland
```

Makes it so the service is only started in a Wayland session.

**Describe alternatives you've considered**

```
WantedBy=graphical-session.target
ConditionPathExists=${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
```

(Doesn't work because systemd doesn't expand env variables in conditions.)

**Comment by WhyNotHugo** [comment]
Note: This applies to user units, not system units.

**Comment by refi64** [comment]
You could always do something like `ConditionPathExistsGlob=%t/wayland-*` or `ExecCondition=bash -c '[[ "$XDG_SESSION_TYPE" == "wayland"]]`.

**Comment by emersion** [comment]
Ah, I completely missed `ExecCondition`. This will probably do, can you try @WhyNotHugo?

**Comment by WhyNotHugo** [comment]
This works as expected (note that exit code must be -1):
```
ExecCondition=sh -c '[[ "$XDG_SESSION_TYPE" == "wayland" ]] || exit -1'
```

A condition failure marked the service as `failed` (without this line, running outside of wayland merely marked it as `exited`).

**Comment by emersion** [comment]
I think we should just exit with 1 to skip the unit outside of Wayland sessions. We don't want to fail the unit, we want to potentially allow another systemd unit to be started (e.g. dunst on X11).

Closing this issue, let's continue the discussion on the mako PR.
