### ISSUE TITLE
[Arch Linux | systemd 245-1 & 245-2 | ZFS on root] System no longer boots - "Caught <ABRT>, dumped core as pid / Freezing execution"

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#15070]
**systemd version the issue has been seen with**
> 245-1-arch & 245-2-arch

**Used distribution**
 > Arch Linux

I'm using Arch Linux with ZFS on root and native ZFS encryption.

Since I updated `systemd`, `systemd-libs` and `systemd-sysvcompat` from 244.3-1 to 245-1 or 245-2, my system no longer boots.

After I enter my pool passphrase, I'm getting the following errors:

```
Starting version 245-2-arch
Enter passphrase for 'zroot/encr':
no pools available to import
[    36.211510] systemd[1]: Caught <ABRT>, dumped core as pid 093.
[    36.211542] systemd[1]: Freezing execution.
```

And the boot process stops there.

Downgrading `systemd`, `systemd-libs` and `systemd-sysvcompat` to 244.3-1 solves the issue.

**Comment by jh10001** [comment]
Same issue without ZFS.

**Comment by floppym** [comment]
I think you're going to have to provide some additional info.

Maybe start with the output of `coredumpctl info`, and maybe some relevant output from `coredumpctl debug` if you know how to operate gdb.

**Comment by vtnpp** [comment]
> I think you're going to have to provide some additional info.
> 
> Maybe start with the output of `coredumpctl info`, and maybe some relevant output from `coredumpctl debug` if you know how to operate gdb.

Not sure when I'm supposed to run these commands? Since my system won't boot with 245-1-arch or 245-2-arch, I downgraded to 244.3-1.

Both `coredumpctl info` and `coredumpctl debug` give me no output at all.

**Comment by StefRe** [comment]
Same issue here after update to 245-2 with `ext4` and no encryption. Had to downgrad to 244.3-1 to be able to boot again. No core dumps available (according to `coredumpctl list`) although it said `dumped core as pid xxx` before halting.

**Comment by floppym** [comment]
Oh, right. If systemd can't mount the root filesystem, it will also be unable to save the coredump info in the journal.

The core dump is probably output somewhere in the temporary rootfs that is set up for initramfs execution. Getting at it will probably be tricky.

**Comment by jh10001** [comment]
Maybe this? I'm not sure.
```
Process 5145 (systemd) of user 0 dumped core.
                
                Stack trace of thread 5145:
                #0  0x00007f8b9fc810bb kill (libc.so.6 + 0x3c0bb)
                #1  0x000056169f7ffdbe n/a (systemd + 0xe2dbe)
                #2  0x00007f8b9fc80d70 __restore_rt (libc.so.6 + 0x3bd70)
                #3  0x00007f8b9fc80ce5 raise (libc.so.6 + 0x3bce5)
                #4  0x00007f8b9fc6a857 abort (libc.so.6 + 0x25857)
                #5  0x00007f8b9fa32069 n/a (libsystemd-shared-245.so + 0x4f069)
                #6  0x00007f8b9fadfc72 path_startswith (libsystemd-shared-245.so + 0xfcc72)
                #7  0x00007f8b9fadff61 path_startswith_strv (libsystemd-shared-245.so + 0xfcf61)
                #8  0x00007f8b9fae015d is_device_path (libsystemd-shared-245.so + 0xfd15d)
                #9  0x000056169f761847 n/a (systemd + 0x44847)
                #10 0x000056169f7c86f0 n/a (systemd + 0xab6f0)
                #11 0x000056169f755fe0 n/a (systemd + 0x38fe0)
                #12 0x000056169f757272 n/a (systemd + 0x3a272)
                #13 0x000056169f76673d n/a (systemd + 0x4973d)
                #14 0x000056169f768c81 n/a (systemd + 0x4bc81)
                #15 0x000056169f7696ff n/a (systemd + 0x4c6ff)
                #16 0x000056169f7ca1f5 n/a (systemd + 0xad1f5)
                #17 0x000056169f7caf06 n/a (systemd + 0xadf06)
                #18 0x000056169f7500cb n/a (systemd + 0x330cb)
                #19 0x00007f8b9fc6c023 __libc_start_main (libc.so.6 + 0x27023)
                #20 0x000056169f75149e n/a (systemd + 0x3449e)
```

**Comment by vtnpp** [comment]
> Maybe this? I'm not sure.
> 
> ```
> Process 5145 (systemd) of user 0 dumped core.
>                 
>                 Stack trace of thread 5145:
>                 #0  0x00007f8b9fc810bb kill (libc.so.6 + 0x3c0bb)
>                 #1  0x000056169f7ffdbe n/a (systemd + 0xe2dbe)
>                 #2  0x00007f8b9fc80d70 __restore_rt (libc.so.6 + 0x3bd70)
>                 #3  0x00007f8b9fc80ce5 raise (libc.so.6 + 0x3bce5)
>                 #4  0x00007f8b9fc6a857 abort (libc.so.6 + 0x25857)
>                 #5  0x00007f8b9fa32069 n/a (libsystemd-shared-245.so + 0x4f069)
>                 #6  0x00007f8b9fadfc72 path_startswith (libsystemd-shared-245.so + 0xfcc72)
>                 #7  0x00007f8b9fadff61 path_startswith_strv (libsystemd-shared-245.so + 0xfcf61)
>                 #8  0x00007f8b9fae015d is_device_path (libsystemd-shared-245.so + 0xfd15d)
>                 #9  0x000056169f761847 n/a (systemd + 0x44847)
>                 #10 0x000056169f7c86f0 n/a (systemd + 0xab6f0)
>                 #11 0x000056169f755fe0 n/a (systemd + 0x38fe0)
>                 #12 0x000056169f757272 n/a (systemd + 0x3a272)
>                 #13 0x000056169f76673d n/a (systemd + 0x4973d)
>                 #14 0x000056169f768c81 n/a (systemd + 0x4bc81)
>                 #15 0x000056169f7696ff n/a (systemd + 0x4c6ff)
>                 #16 0x000056169f7ca1f5 n/a (systemd + 0xad1f5)
>                 #17 0x000056169f7caf06 n/a (systemd + 0xadf06)
>                 #18 0x000056169f7500cb n/a (systemd + 0x330cb)
>                 #19 0x00007f8b9fc6c023 __libc_start_main (libc.so.6 + 0x27023)
>                 #20 0x000056169f75149e n/a (systemd + 0x3449e)
> ```

Providing that this output could somehow help debugging the issue (confirmation needed), could you please detail how you managed to get it, considering `systemd` cannot mount the root filesystem?

@StefRe @jh10001 I guess you guys are also using Arch?

**Comment by StefRe** [comment]
> @StefRe @jh10001 I guess you guys are also using Arch?

@vtnpp: Yes (ArchLabs to be precise).

**Comment by tonkapango** [comment]
also observe same error on boot, after updating to 245.2-2,.

**Comment by vcaputo** [comment]
Ok, I haven't reproduced this or done anything beyond some rudimentary deductive reasoning based on the above stack traces, so take this with a grain of salt.

We're fortunate to have relatively few call sites for is_device_path():
```
src/basic/path-util.c:bool is_device_path(const char *path) {
src/basic/path-util.h:bool is_device_path(const char *path);
src/basic/unit-name.c:        if (is_device_path(name)) {
src/core/mount.c:        if (!is_device_path(p->what))
src/core/swap.c:        if (is_device_path(p->what)) {
src/core/unit.c:        if (!is_device_path(what))
src/fstab-generator/fstab-generator.c:                if (is_device_path(what) && path_is_read_only_fs("/sys") > 0) {
src/fstab-generator/fstab-generator.c:        if (is_device_path(what)) {
src/fstab-generator/fstab-generator.c:                         is_device_path(what) ? 1 : 0, /* passno */
src/fstab-generator/fstab-generator.c:                         is_device_path(what) ? 1 : 0, /* passno */
src/mount/mount-tool.c:        if (arg_bind_device && is_device_path(arg_mount_what)) {
src/mount/mount-tool.c:        if (!is_device_path(arg_mount_what))
src/shared/dissect-image.c:        if (is_device_path(image)) {
src/shared/generator.c:        if (!is_device_path(what)) {
src/shared/generator.c:        if (!is_device_path(node)) {
src/shared/generator.c:        if (!is_device_path(node))
src/shared/generator.c:        if (!is_device_path(node))
src/shared/generator.c:        if (!is_device_path(node))
```

Pruning the obviously irrelevant results leaves us with these:
```
src/basic/unit-name.c:        if (is_device_path(name)) {
src/core/mount.c:        if (!is_device_path(p->what))
src/core/swap.c:        if (is_device_path(p->what)) {
src/core/unit.c:        if (!is_device_path(what))
```

If we assume that what's going on is an assert() in path_startswith_str() under is_device_path() meaning it got passed a NULL path, let's look at the four call sites to see which could do that:

src/basic/unit-name.c: explicitly checks isempty(name) prior to is_device_path(), nope.

src/core/mount.c: explicitly checks if !p->what prior to is_device_path(), nope.

src/core/swap.c: checks if !p but doesn't check if !p->what which gets supplied to is_device_path(), looks plausible.  p comes from swap_get_parameters(), can swap_get_parameters() return a NULL p->what?  Maybe, I didn't exhaustively untangle that particular knot.

src/core/unit.c: explicitly checks isempty(what) before passing to is_device_path(), nope.

So, at this point, the prime suspect is src/core/swap.c:swap_add_device_dependencies()

Now looking at the diffs between v244..v245 for src/core/swap.c we find:

```
commit 61f9cf4e4c488adf47419a4a81a315196fc01d43
Author: Lennart Poettering <lennart@poettering.net>
Date:   Tue Jan 21 18:16:05 2020 +0100

    swap: generate automatic dependencies also for /proc/swaps devices
    
    This catches up with the logic we do for mounts: we create deps based on
    /proc/swaps now too, with the right flags set.

diff --git a/src/core/swap.c b/src/core/swap.c
index 473b3483ae..4155112f41 100644
--- a/src/core/swap.c
+++ b/src/core/swap.c
@@ -184,21 +184,39 @@ static int swap_arm_timer(Swap *s, usec_t usec) {
         return 0;
 }
 
+static SwapParameters* swap_get_parameters(Swap *s) {
+        assert(s);
+
+        if (s->from_proc_swaps)
+                return &s->parameters_proc_swaps;
+
+        if (s->from_fragment)
+                return &s->parameters_fragment;
+
+        return NULL;
+}
+
 static int swap_add_device_dependencies(Swap *s) {
+        UnitDependencyMask mask;
+        SwapParameters *p;
+
         assert(s);
 
         if (!s->what)
                 return 0;
 
-        if (!s->from_fragment)
+        p = swap_get_parameters(s);
+        if (!p)
                 return 0;
 
-        if (is_device_path(s->what))
-                return unit_add_node_dependency(UNIT(s), s->what, UNIT_BINDS_TO, UNIT_DEPENDENCY_FILE);
+        mask = s->from_proc_swaps ? UNIT_DEPENDENCY_PROC_SWAP : UNIT_DEPENDENCY_FILE;
+
+        if (is_device_path(p->what))
+                return unit_add_node_dependency(UNIT(s), p->what, UNIT_BINDS_TO, mask);
 
-        /* File based swap devices need to be ordered after systemd-remount-fs.service,
-         * since they might need a writable file system. */
-        return unit_add_dependency_by_name(UNIT(s), UNIT_AFTER, SPECIAL_REMOUNT_FS_SERVICE, true, UNIT_DEPENDENCY_FILE);
+        /* File based swap devices need to be ordered after systemd-remount-fs.service, since they might need
+         * a writable file system. */
+        return unit_add_dependency_by_name(UNIT(s), UNIT_AFTER, SPECIAL_REMOUNT_FS_SERVICE, true, mask);
 }
 
 static int swap_add_default_dependencies(Swap *s) {

```

Note how that commit switches from passing s->what to p->what to is_device_path()?  And nothing is checking for !p->what?  My guess is this commit is responsible for the regression.

@jh10001 @vtnpp Care to retry v245 with 61f9cf4e4c4 reverted?

Or, you could just add an `|| !p->what` to the `if (!p)` check following `swap_get_parameters(s)` in `src/core/swap.c:swap_add_device_dependencies()` so it returns 0 when p->what is NULL.

**Comment by vtnpp** [comment]
> @jh10001 @vtnpp Care to retry v245 with 61f9cf4 reverted?

No problem but.. I've never done that before, I'm just a random end user. Could you please elaborate on how should I proceed?

My guess would be:

1. Clone the repository
2. Revert 61f9cf4 (or change what you suggest in `src/core/swap.c`)
3. Recompile `systemd` and create an Arch package but what about `systemd-libs` and `systemd-sysvcompat`?

Maybe @jh10001 @tonkapango @StefRe are more knowledgeable than I am about all of that and can try individually.

Thanks.

**Comment by jh10001** [comment]
> 
> 
> Ok, I haven't reproduced this or done anything beyond some rudimentary deductive reasoning based on the above stack traces, so take this with a grain of salt.
> 
> We're fortunate to have relatively few call sites for is_device_path():
> 
> ```
> src/basic/path-util.c:bool is_device_path(const char *path) {
> src/basic/path-util.h:bool is_device_path(const char *path);
> src/basic/unit-name.c:        if (is_device_path(name)) {
> src/core/mount.c:        if (!is_device_path(p->what))
> src/core/swap.c:        if (is_device_path(p->what)) {
> src/core/unit.c:        if (!is_device_path(what))
> src/fstab-generator/fstab-generator.c:                if (is_device_path(what) && path_is_read_only_fs("/sys") > 0) {
> src/fstab-generator/fstab-generator.c:        if (is_device_path(what)) {
> src/fstab-generator/fstab-generator.c:                         is_device_path(what) ? 1 : 0, /* passno */
> src/fstab-generator/fstab-generator.c:                         is_device_path(what) ? 1 : 0, /* passno */
> src/mount/mount-tool.c:        if (arg_bind_device && is_device_path(arg_mount_what)) {
> src/mount/mount-tool.c:        if (!is_device_path(arg_mount_what))
> src/shared/dissect-image.c:        if (is_device_path(image)) {
> src/shared/generator.c:        if (!is_device_path(what)) {
> src/shared/generator.c:        if (!is_device_path(node)) {
> src/shared/generator.c:        if (!is_device_path(node))
> src/shared/generator.c:        if (!is_device_path(node))
> src/shared/generator.c:        if (!is_device_path(node))
> ```
> 
> Pruning the obviously irrelevant results leaves us with these:
> 
> ```
> src/basic/unit-name.c:        if (is_device_path(name)) {
> src/core/mount.c:        if (!is_device_path(p->what))
> src/core/swap.c:        if (is_device_path(p->what)) {
> src/core/unit.c:        if (!is_device_path(what))
> ```
> 
> If we assume that what's going on is an assert() in path_startswith_str() under is_device_path() meaning it got passed a NULL path, let's look at the four call sites to see which could do that:
> 
> src/basic/unit-name.c: explicitly checks isempty(name) prior to is_device_path(), nope.
> 
> src/core/mount.c: explicitly checks if !p->what prior to is_device_path(), nope.
> 
> src/core/swap.c: checks if !p but doesn't check if !p->what which gets supplied to is_device_path(), looks plausible. p comes from swap_get_parameters(), can swap_get_parameters() return a NULL p->what? Maybe, I didn't exhaustively untangle that particular knot.
> 
> src/core/unit.c: explicitly checks isempty(what) before passing to is_device_path(), nope.
> 
> So, at this point, the prime suspect is src/core/swap.c:swap_add_device_dependencies()
> 
> Now looking at the diffs between v244..v245 for src/core/swap.c we find:
> 
> ```
> commit 61f9cf4e4c488adf47419a4a81a315196fc01d43
> Author: Lennart Poettering <lennart@poettering.net>
> Date:   Tue Jan 21 18:16:05 2020 +0100
> 
>     swap: generate automatic dependencies also for /proc/swaps devices
>     
>     This catches up with the logic we do for mounts: we create deps based on
>     /proc/swaps now too, with the right flags set.
> 
> diff --git a/src/core/swap.c b/src/core/swap.c
> index 473b3483ae..4155112f41 100644
> --- a/src/core/swap.c
> +++ b/src/core/swap.c
> @@ -184,21 +184,39 @@ static int swap_arm_timer(Swap *s, usec_t usec) {
>          return 0;
>  }
>  
> +static SwapParameters* swap_get_parameters(Swap *s) {
> +        assert(s);
> +
> +        if (s->from_proc_swaps)
> +                return &s->parameters_proc_swaps;
> +
> +        if (s->from_fragment)
> +                return &s->parameters_fragment;
> +
> +        return NULL;
> +}
> +
>  static int swap_add_device_dependencies(Swap *s) {
> +        UnitDependencyMask mask;
> +        SwapParameters *p;
> +
>          assert(s);
>  
>          if (!s->what)
>                  return 0;
>  
> -        if (!s->from_fragment)
> +        p = swap_get_parameters(s);
> +        if (!p)
>                  return 0;
>  
> -        if (is_device_path(s->what))
> -                return unit_add_node_dependency(UNIT(s), s->what, UNIT_BINDS_TO, UNIT_DEPENDENCY_FILE);
> +        mask = s->from_proc_swaps ? UNIT_DEPENDENCY_PROC_SWAP : UNIT_DEPENDENCY_FILE;
> +
> +        if (is_device_path(p->what))
> +                return unit_add_node_dependency(UNIT(s), p->what, UNIT_BINDS_TO, mask);
>  
> -        /* File based swap devices need to be ordered after systemd-remount-fs.service,
> -         * since they might need a writable file system. */
> -        return unit_add_dependency_by_name(UNIT(s), UNIT_AFTER, SPECIAL_REMOUNT_FS_SERVICE, true, UNIT_DEPENDENCY_FILE);
> +        /* File based swap devices need to be ordered after systemd-remount-fs.service, since they might need
> +         * a writable file system. */
> +        return unit_add_dependency_by_name(UNIT(s), UNIT_AFTER, SPECIAL_REMOUNT_FS_SERVICE, true, mask);
>  }
>  
>  static int swap_add_default_dependencies(Swap *s) {
> ```
> 
> Note how that commit switches from passing s->what to p->what to is_device_path()? And nothing is checking for !p->what? My guess is this commit is responsible for the regression.
> 
> @jh10001 @vtnpp Care to retry v245 with [61f9cf4](https://github.com/systemd/systemd/commit/61f9cf4e4c488adf47419a4a81a315196fc01d43) reverted?
> 
> Or, you could just add an `|| !p->what` to the `if (!p)` check following `swap_get_parameters(s)` in `src/core/swap.c:swap_add_device_dependencies()` so it returns 0 when p->what is NULL.


Add `|| !p->what` solved.

I checked the configuration of the swap partition in fstab and found problem. But swap partition was mount correctly in the system so I didn't notice it.
Use an incorrect swap partition in fstab may reproduce this.

**Comment by vtnpp** [comment]
I've just updated the following packages:

- `systemd-libs` (244.3-1 -> 245.3-1)
- `systemd` (244.3-1 -> 245.3-1)
- `systemd-sysvcompat` (244.3-1 -> 245.3-1)

and can confirm the problem is solved.
