### ISSUE TITLE
[227 regression] user systemd instances try to unmount system mounts on boot

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1507]
https://bugs.debian.org/801361 reported that 227 introduced a regression with the user systemd instances: They now try to unmount system mounts at startup:

```
systemd[1653]: Reached target Default.
systemd[1653]: boot.mount: Mount process exited, code=exited status=1
systemd[1653]: Failed unmounting /boot.
systemd[1653]: run-user-1000.mount: Mount process exited, code=exited status=1
systemd[1653]: Failed unmounting /run/user/1000.
systemd[1653]: dev-dm\x2d2.swap: Unit entered failed state.
systemd[1653]: sys-kernel-debug.mount: Mount process exited, code=exited status=1
systemd[1653]: Failed unmounting /sys/kernel/debug.
[...]
umount[1657]: umount: /boot: umount failed: Operation not permitted
umount[1658]: umount: /run/user/1000: umount failed: Operation not permitted
swapoff[1659]: swapoff: Not superuser.
```

This is mostly cosmetical for non-root logins, but it was reported that for root logins this actually does unmount stuff.

Investigation is ongoing.

**Comment by martinpitt** [comment]
I amended our "boot-smoke" test to check for this/catch this: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=2e4ab375bfe . Unfortunately this doesn't happen in the minimal VMs that I usually test systemd in (not even with lightdm and network-manager installed), only in a full desktop VM; the latter has autologin enabled, I figure that's the important difference. But at least I have a way to reproduce this automatically now.

**Comment by martinpitt** [comment]
Bisected to https://github.com/systemd/systemd/commit/8c8da0e, from the rather large patch series in PR #1408. It reverts cleanly on top of 207 (and master). Admittedly I don't understand this at all yet, but I figure this should be very simple to reproduce on a desktop system.

**Comment by poettering** [comment]
Any chance you can let this systemd --user instance run with SYSTEMD_LOG_LEVEL=debug? (edit the user@.service for that) and then paste the output here?

**Comment by poettering** [comment]
Also, an output of "systemd-analyze --user dump" of the affected system would be useful

**Comment by martinpitt** [comment]
Sure, no problem.
- user@1000.service journal with debug: http://paste.ubuntu.com/12724199/
- `systemd-analyze --user dump`: http://paste.ubuntu.com/12724206/

**Comment by poettering** [comment]
OK, I think I know what's going on. Prepping a fix now.

**Comment by poettering** [comment]
So I figure the issues is related to the fact that we "isolate" default.target and you have no user services around, hence everything is shut down, that is not immediately part of default.target itself. Normally, if you have at least one user service this would mean that at least -.slice is pulled in by it. Since you have none, we decide that -.slice is unnecessary, and try to pull it down. Now, since -.slice is now Required= by all .mounts (since that's the slice the /bin/mount processes run it), this means that the .mount units are pulled down too, and BOOM!

Fix is easy: just make sure that -.slice is ignored by isolate requests.

**Comment by poettering** [comment]
@martinpitt could you check if #1516 fixes your problem? If so, please press the green button on it....

**Comment by martinpitt** [comment]
Thanks @poettering! Verified that this works, and the other changes look straightforward.
