### ISSUE TITLE
systemd-nspawn --image hangs in an unshared network namespace

### ISSUE THREAD

**Issue by ondrejbudai** [systemd/systemd#15079]
**systemd version the issue has been seen with**
> 241-245, **not seen** in 239

**Used distribution**
 > fedora 30-32 and ubuntu 19.10, **not seen** in fedora 29

**Expected behaviour you didn't see**
 > systemd-nspawn doesn't start a container in image mode when running in an unshared network namespace

**Unexpected behaviour you saw**
 > systemd-nspawn just hangs and does nothing with no output

**Steps to reproduce the problem**
```
wget https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz
unxz Fedora-Cloud-Base-31-1.9.x86_64.raw.xz
sudo unshare -n systemd-nspawn --boot --register=no -M fedora-cloud --image Fedora-Cloud-Base-31-1.9.x86_64.raw
```

**My observations**

:heavy_check_mark: Without unsharing it just works:
```
sudo systemd-nspawn --boot --register=no -M fedora-cloud --image Fedora-Cloud-Base-31-1.9.x86_64.raw
```

:heavy_check_mark: With strace **and** unsharing it also *magically* works (possibly a heisenbug?)
```
sudo unshare -n strace systemd-nspawn --boot --register=no -M fedora-cloud --image Fedora-Cloud-Base-31-1.9.x86_64.raw 2>/dev/null
```

:x: When I try to unshare the network using `unshare(2)` and then spawn `systemd-nspawn` using `exec(3)`, `nspawn` hangs.

:heavy_check_mark: When I mount the image and run `systemd-nspawn` with `--directory` argument, it works alright:
```
mkdir /tmp/fedora-image
sudo mount -o loop,offset=1048576 ./Fedora-Cloud-Base-31-1.9.x86_64.raw /tmp/fedora-image
sudo unshare -n systemd-nspawn --boot --register=no -M fedora-cloud --directory /tmp/fedora-image/
```

**Comment by yuwata** [comment]
What does the 'hang' mean here? Does SYSTEMD_LOG_LEVEL=debug show something?

**Comment by ondrejbudai** [comment]
'hang' means that the command is running indefinitely without any output.

With SYSTEMD_LOG_LEVEL=debug I got this output:
```
Setting RLIMIT_CPU to infinity.
Setting RLIMIT_FSIZE to infinity.
Setting RLIMIT_DATA to infinity.
Setting RLIMIT_STACK to 8388608:infinity.
Setting RLIMIT_CORE to 0:infinity.
Setting RLIMIT_RSS to infinity.
Setting RLIMIT_NPROC to 63372.
Setting RLIMIT_NOFILE to 1024:4096.
Setting RLIMIT_MEMLOCK to 65536.
Setting RLIMIT_AS to infinity.
Setting RLIMIT_LOCKS to infinity.
Setting RLIMIT_SIGPENDING to 63372.
Setting RLIMIT_MSGQUEUE to 819200.
Setting RLIMIT_NICE to 0.
Setting RLIMIT_RTPRIO to 0.
Setting RLIMIT_RTTIME to infinity.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Waiting for device (parent + 1 partitions) to appear...
```

**Comment by ondrejbudai** [comment]
I used bisect and this commit (https://github.com/systemd/systemd/commit/a8040b6d0ad43e5cb7168fd3b739c8c68aaa61b1) introduced this issue

**Comment by ondrejbudai** [comment]
I investigated some more. The commit mentioned above added call to `device_wait_for_initialization`. This function calls `sd_device_get_is_initialized` to check if the device is initialized. If it is not, it creates a `device_monitor` which is then used to wait for the initialization.

The `device_monitor` works in this way: It opens a `NETLINK` socket and listens to udev messages (multicast group 2). However, as we are in our own namespace, we don't get messages from this multicast group. Therefore, the function `device_wait_for_initialization` just waits for the message indefinitely.

I'm not sure about a solution to this issue. I don't know if it's possible to somehow listen to udev messages in a different network namespace. A dirty solution is to poll `sd_device_get_is_initialized` function which works in a namespaced environment just OK.

cc @keszybz

**Comment by yuwata** [comment]
@ondrejbudai Why do not you use `--private-network` option? I think `nspawn` is not designed to work with `unshare`.

**Comment by ondrejbudai** [comment]
Our usecase in [osbuild-composer](https://github.com/osbuild/osbuild-composer) is to test whether an image boots. We do that by enabling ssh server in the image and trying to connect to it. To ensure we don't collide with other processes we unshare a process, which 1) spawns the container with `systemd-nspawn` and 2) tries to connect to the container using ssh.

**Comment by yuwata** [comment]
Still not sure about the use case. But I think `--private-network` (or maybe `--network-namespace-path=`) option help you in that case. No? If no, why?

**Comment by teg** [comment]
@yuwata `--private-network` does not work in this case, as we want to share the network namespace between nspawn and another process (running the tests). `--network-namespace-path=` looks like it should work. The nice thing is that `--network-namespace-path=' was introduced before the change in behaviour, so on a given systemd version either `--network-namespace-path=` works or it is not necessary.

Downside is that we can't have one code-path that works on all systemd releases, and we need to support both old and new, but I guess that can't be helped.

**Comment by poettering** [comment]
I figure we somehow need to create the netlink socket in the root namespace. yuck.

**Comment by poettering** [comment]
So, I don't think we can reasonably fix this. AF_NETLINK (and thus udev notifications) is part of what a netns is, and if you run nspawn inside its own netns, then you basically declare you want AF_NETLINK disconnected. But we need AF_NETLINK to wait for udev.

Yes, it sucks that AF_NETLINK (and AF_UNIX for the matter) are affected by netns, but it is the way it is...

So, I don't think we can reasonably fix this for you. What we can do however, is at least fail cleanly instead of hanging silently. I'll prep a patch for that.

(And yeah, the proper fix is probably: just don't do what you are trying to do... sorry!)

**Comment by ondrejbudai** [comment]
`--network-namespace-path=` works for us, so that's great. Failing cleanly would be indeed amazing, thanks!
