### ISSUE TITLE
New systemctl list-units table format breaks zsh completions

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#15077]
```
$ systemctl --version
systemd 245 (245-2-arch)
```

It appears that the output format of `systemctl --no-pager --no-legend --full list-units` has changed in v245 and some zsh completions are broken as a result.

The format has changed from,

v244:
```
$ systemctl --no-pager --no-legend --full list-unit-files
my-unit.service loaded active running [...]
[...]
```

v245:
```
$ systemctl --no-pager --no-legend --full list-unit-files
  my-unit.service loaded active running [...]
[...]
```

(notice the leading spaces)

The zsh completions for systemctl use one of those magical zsh parameter expansion parsers to get an array of active units,

https://github.com/systemd/systemd/blob/0335d110afc08baf47d76b7011ce02510dfdd524/shell-completion/zsh/_systemctl.in#L200

which is tripped up by the leading spaces, resulting in an always empty list of active units.

Steps to reproduce:
1. Use zsh
2. `systemctl stop <TAB>`

Expected: autocomplete list of active unit names
Actual: nothing

I'm guessing that the change in format is unintentional (perhaps from de9a8fe18e?), but if not the zsh completions could be updated to compensate. Please advise.

**Comment by mrc0mmand** [comment]
Ah, I see. The `--no-legend` switch in `systemctl list-units` originally hid the first column as well (which shows a circle glyph on failed/non-existent/etc. units), but that got lost during conversion to the `format-table.[ch]` stuff.

The same stuff applies to `machinectl list` as well.

**Comment by RPigott** [comment]
Thanks @mrc0mmand for the quick fix!

**Comment by joukewitteveen** [comment]
Should it be documented that the the bullets are hidden with `--no-legend` too? Currently this behavior is only documented for `--plain`:
> --plain
>    When used with list-dependencies, list-units or list-machines, the output is printed as a list instead of a tree, and the bullet circles are omitted.

Is there any other than historical reasons for hiding the bullet circle with `--no-legend`?
