### ISSUE TITLE
LVM LVs are not started correctly if cached LV is distributed on different encrypted disks

### ISSUE THREAD

**Issue by freaknils** [systemd/systemd#15087]
**systemd version the issue has been seen with**
244.3

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
My disk setup is like this:
```
+---------------------------------------------------------------------------------------+
| lvhome_cachepool    | [SWAP]              | /                   | /home               |
| on md127            | on md127            | on md127            | on md128            |
|---------------------------------------------------------------------------------------|
|                                   LVM Volume group                                    |
|                                         VGmain                                        |
|-------------------------------------------|-------------------------------------------|
|                 RAID 1                    |                 RAID 1                    |
|               /dev/md127                  |               /dev/md128                  |
--------------------------------------------|--------------------------------------------
| LUKS2 encrypted ssd | LUKS2 encrypted ssd | LUKS2 encrypted hdd | LUKS2 encrypted hdd |
|     /dev/sda        |     /dev/sdb        |     /dev/sdc        |     /dev/sdd        | 
+-------------------------------------------|-------------------------------------------+
```
Mdadm assembling, decrypting, lvm activation, mouting should work fine.

**Unexpected behaviour you saw**
Mdadm is working fine. Both encrypted devices are decrypted well, after that, the lvms are not started properly. Root device and swap are working fine, but /home is not started automaticly.

If if do a `lvchange -ay VGmain/lvhome` in recovery console the LV is activated and after Ctrl.+R the system is booting fine.

**Steps to reproduce the problem**
Se above

**Comment by poettering** [comment]
I am sorry, but we cannot help with RAID/LVM. Please contact your distro first or the RAID/LVM people, but systemd has no understanding of that stuff itself, and we as its maintainers cannot really help either. Sorry.

Please contact the storage maintainers. Thank you for understanding.
