### ISSUE TITLE
systemd-homed cannot be disabled

### ISSUE THREAD

**Issue by maklor78** [systemd/systemd#15083]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > arch linux

**Expected behaviour you didn't see**
 > "systemctl disable systemd-homed.service" should disable the homed service after reboot
 > Optional services like homed should be disabled by default as most users do not have a use case for it

**Unexpected behaviour you saw**
 > Systemd-homed.serviceit is enabled by default and cannot be disabled

**Steps to reproduce the problem**
Install systemd on arch linux

"systemctl systemd-homed" shows the service is active and running even after "systemctl disable systemd-homed.service" and reboot

The only way to disable the service that I found was to mask it
systemctl mask systemd-homed.service

**Comment by jneen** [comment]
I'm also having this issue. My fresh install won't boot because systemd-homed is trying to access my encrypted partition before it can be mounted on login.

I'm happy to set up homed if that's the preferred method, but so far I've found no guide for that, and the tools have only given me cryptic error messages. This should be disabled by default until it is stable and has suitable documentation.

**Comment by refi64** [comment]
If you aren't actively using it, it shouldn't cause anything.

**Comment by MountainX** [comment]
> If you aren't actively using it, it shouldn't cause anything.

My system shows it consuming 1.5M RAM, even when not being used.

**Comment by maklor78** [comment]
> If you aren't actively using it, it shouldn't cause anything.

This is incorrect.

Not only could this argument be used to run hundreds of services notbody needs and uses.
But most noteably is the fact that any unrequired service running increases not only the attack surfae of a systems but also the number of things that can go wrong in general.

Systemd has a great responsibility as it is used on billions of systems.
There should be very good reasoning before enableing some service by default.

homed is a nice feature which I am currently testing myself.
But this feature has no business on the hundreds of servers and many other clients I am running.
Homed will be completely useless for 99.9% of all systemd users and even those who will use it, first have to set it up before it can be used. 

systemd-homed should be disbaled by default and only be enabled by those few who have an actual use case for it.

And 1.5 MB Ram use plus a few seconds of cpu time add up to a lot of energie wasted as well.
