### ISSUE TITLE
systemd-userdbd.service loaded failed failed User Database Manager

### ISSUE THREAD

**Issue by MountainX** [systemd/systemd#15085]
**systemd version the issue has been seen with**
> systemd 245-2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > 0 units failed

**Unexpected behaviour you saw**
 >  UNIT                    LOAD   ACTIVE SUB    DESCRIPTION                 
> ● systemd-userdbd.service loaded failed failed User Database Manager       
> ● systemd-userdbd.socket  loaded failed failed User Database Manager Socket
> 
> Mar 11 13:00:13 sshd[355]: pam_systemd(sshd:session): Failed to get user record: Input/output error
> Mar 11 13:00:13 systemd[1]: Failed to start User Database Manager.

**Steps to reproduce the problem**
I updated systemd on 15 identical systems today. On about half of them, I get the above error on most reboots. However, not every system gives the error on every boot. It appears slightly random. These 15 systems are VPS at different high-quality hosting providers. 

It can be resolved with `systemctl restart systemd-userdbd`.

**Comment by maklor78** [comment]
The systemd-userdbd service should also be disabled by default.
there is no usecase for most users and it runied my day as well.
(Not to mention the energie wasted having services  running on millions of systems even though 99.9% wont need it)

Please be more careful and make it an active choice what services to enable

**Comment by StepDub** [comment]
Can confirm. Using Manjaro cinnamon testing (also systemd 245.2). systemd-userdbd.service fails to start during boot most times but not always.

`
Mar 21 11:51:33 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:33 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:33 systemd[1]: Starting User Database Manager...
Mar 21 11:51:34 systemd[1]: Started User Database Manager.
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:34 systemd[1]: Starting User Database Manager...
Mar 21 11:51:34 systemd[1]: Started User Database Manager.
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:34 systemd[1]: Starting User Database Manager...
Mar 21 11:51:34 systemd[1]: Started User Database Manager.
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:34 systemd[1]: Starting User Database Manager...
Mar 21 11:51:34 systemd[1]: Started User Database Manager.
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:34 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:35 systemd[1]: Starting User Database Manager...
Mar 21 11:51:35 systemd[1]: Started User Database Manager.
Mar 21 11:51:35 systemd[1]: systemd-userdbd.service: Main process exited, code=killed, status=10/USR1
Mar 21 11:51:35 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:35 systemd[1]: systemd-userdbd.service: Start request repeated too quickly.
Mar 21 11:51:35 systemd[1]: systemd-userdbd.service: Failed with result 'signal'.
Mar 21 11:51:35 systemd[1]: Failed to start User Database Manager.
Mar 21 11:51:35 systemd[1]: systemd-userdbd.socket: Failed with result 'service-start-limit-hit'.
`

**Comment by poettering** [comment]
Ouch!

**Comment by poettering** [comment]
Fix waiting in #15268
