### ISSUE TITLE
systemd should pass bus/vendor/model/version information to udev rules for emulated devices

### ISSUE THREAD

**Issue by Xyene** [systemd/systemd#15092]
Hi,

I'm filing this issue as part of something that came up while debugging [this](https://gitlab.freedesktop.org/xorg/xserver/issues/995) sway/`Xwayland` bug that stumped us for a few days, and that I believe originated in `systemd`. That page has a bit more context, if necessary.

**Brief background:** a straightforward way to debug software for input devices you don't own is to obtain `evemu-describe` output, and then use `evemu-device` to emulate it on your machine.

My Huion 420 drawing tablet pad has [this `evemu` description](https://gist.github.com/Xyene/d0530a96730695291a6becbb7481cfb4), which also describes the device bus, vendor, model, and version:

```
I: 0003 256c 006e 0111
```

(Bus `003` = USB, Huion = `256c`, model = `006e`, version = `0111`.)

Tablets in particular really need `libwacom` `udev` rules to execute, so that the `ID_INPUT_TABLET_PAD` flag is correctly set. On my machine, `/usr/lib/udev/rules.d/65-libwacom.rules` contains:

```
# Huion H610 Pro
ENV{ID_BUS}=="usb", ENV{ID_VENDOR_ID}=="256c", ENV{ID_MODEL_ID}=="006e",  ENV{ID_INPUT}="1", ENV{ID_INPUT_JOYSTICK}="", ENV{ID_INPUT_TABLET}="1"
ATTRS{name}=="* Pad", ENV{ID_BUS}=="usb", ENV{ID_VENDOR_ID}=="256c", ENV{ID_MODEL_ID}=="006e",  ENV{ID_INPUT_TABLET_PAD}="1"
```

If `ID_INPUT_TABLET_PAD` is incorrectly set for an emulated pad device, then some issues may be unreproducible since they don't hit the same code paths.

**The issue:** currently, `systemd` does not set `ID_BUS`, `ID_VENDOR_ID`, `ID_MODEL_ID`, or `ID_REVISION` for anything but devices physically connected via USB, even when this information should be available. This caused a lot of confusion when debugging the previously linked issue, since the emulated device was not being marked as a tablet pad (`systemd` instead seems to mark it as `ID_INPUT_TABLET`, which is not the same thing).

I believe something like the following patch should work:

```diff
diff --git a/src/udev/udev-builtin-input_id.c b/src/udev/udev-builtin-input_id.c
index 9ff2b02..3faf81b 100644
--- a/src/udev/udev-builtin-input_id.c
+++ b/src/udev/udev-builtin-input_id.c
@@ -264,6 +264,16 @@ static bool test_pointers(sd_device *dev,
         if (is_tablet)
                 udev_builtin_add_property(dev, test, "ID_INPUT_TABLET", "1");
 
+        const char *v;
+        if (sd_device_get_sysattr_value(dev, "id/bustype", &v) >= 0)
+                udev_builtin_add_property(dev, test, "ID_BUS", v);
+        if (sd_device_get_sysattr_value(dev, "id/vendor", &v) >= 0)
+                udev_builtin_add_property(dev, test, "ID_VENDOR_ID", v);
+        if (sd_device_get_sysattr_value(dev, "id/product", &v) >= 0)
+                udev_builtin_add_property(dev, test, "ID_MODEL_ID", v);
+        if (sd_device_get_sysattr_value(dev, "id/version", &v) >= 0)
+                udev_builtin_add_property(dev, test, "ID_REVISION", v);
+
         return is_tablet || is_mouse || is_touchpad || is_touchscreen || is_joystick || is_pointing_stick;
 }
```

If this seems like something that should be sent in as a PR, I'd be happy to do so. It seems reasonable to me that this data should be provided to `udev` rules since it _is_ present, but I might be missing something. Once we figured out what was wrong, [the workaround](https://gitlab.freedesktop.org/xorg/xserver/issues/995#note_433228) was simple enough, but the current behaviour feels very unintuitive.

**Comment by yuwata** [comment]
Please submit as a PR. Then discuss the issue on that page.

**Comment by Xyene** [comment]
Done, it seems to fail `bionic-i386` CI, but from reading the logs it's not clear to me whether this is a spurious failure or caused by my PR (some other PRs seem to be failing in the same place).

**Comment by whot** [comment]
FTR, this use-case should be fixed with https://github.com/linuxwacom/libwacom/pull/233. While the systemd fix may still be worthwhile, at least this use-case no longer needs it. I'll comment on the MR separately.
