### ISSUE TITLE
Systemd fstat call broken/ kernel verison requirement false

### ISSUE THREAD

**Issue by D3faultPassw0rd** [systemd/systemd#15096]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Debian Bullseye with Linux kernel 3.4.0

**Expected behaviour you didn't see**
 > Basically anything in systemd to work

**Unexpected behaviour you saw**
 > Any systemd function that uses chase_symlinks fails at fstat system call (Bad file descriptor)
 > When booting with systemd I get this:
[    5.465203] systemd[1]: Failed to determine whether /sys is a mount point: Bad file descriptor
[    5.474926] systemd[1]: Failed to determine whether /proc is a mount point: Bad file descriptor
[    5.484674] systemd[1]: Failed to determine whether /dev is a mount point: Bad file descriptor
[    5.507533] systemd[1]: Freezing execution.

**Steps to reproduce the problem**
 > Use Systemd with Linux kernel older than 3.6
 > This probably wont get "fixed" But rather the kernel requirement should be raised. Since the issue itself is in the Linux open and fstat system calls. When opening file with O_PATH flag the fstat will work only on kernel newer than 3.6 [Source](http://man7.org/linux/man-pages/man2/open.2.html)

**Comment by yuwata** [comment]
kernel version 3.4.0. Oh, that's too old for the latest systemd. Sorry. Please see the README file:
https://github.com/systemd/systemd/blob/1f58feec7360b39be5ba37470da8f9e3c0862ae9/README#L36-L37
