### ISSUE TITLE
systemd-fsck-root: Endlessly fails with f2fs, likely needs some filesystem specific magic

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#15106]
**systemd version the issue has been seen with**
> systemd 245 (245)
> -PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ +LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=unified
>
> fsck.f2fs 1.13.0 (2019-09-24)

the root filesystem is f2fs, mounted read-only from the initrd.
Systemd will endlessly reboot the system as the fsck attempt fails.

The systemd-fsck tool will end up calling fsck.f2fs with the parameter below,
and will fail as this device is mounted (tries to open it in exclusive mode).

```
$ fsck.f2fs -a /dev/mmcblk0p5; echo $?  
Info: Fix the reported corruption.
Info: Mounted device!
Info: Check FS only on RO mounted device
	Error: Failed to open the device!
255
```

A workaround would be to force or skip the check

```
fsck.f2fs -a -f /dev/mmcblk0p5; echo $?   
Info: Fix the reported corruption.
.....
Done: 0.232165 secs
0
```

I know that the blame could be distributed amongst fsck, fsck.f2fs and systemd,
but since those are separate tools there will likely be the need for some fs specific logic/options.
As it is now, its rather critical bug to me if changing the fs hoses the system.

Some other weird thing is, that deleting the fsck.f2fs tool will allow the system to boot, alteast in a logical sense a missing tool should be atleast as bad as the tool not checking the fs. But that is "no care"

**Comment by poettering** [comment]
this looks like a bug in fsck.f2fs, it's not implementing the fsck protocol correctly. Please report the issue there.
