### ISSUE TITLE
Enable unit template without executing systemctl

### ISSUE THREAD

**Issue by abitrolly** [systemd/systemd#15110]
For an image for a headless ARM system I need it to start WiFi on `wlan0` interface when it boots. I found that I need to enable the `/usr/lib/systemd/system/wpa_supplicant@.service` but the system is headless and I can not login into without WiFi to run `systemctl enable`. What are actions can I take to enable the following unit template from `/usr/lib/systemd/system/wpa_supplicant@.service` without running `systemctl`?

```
[Unit]
Description=WPA supplicant daemon (interface-specific version)
Requires=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target

# NetworkManager users will probably want the dbus version instead.

[Service]
Type=simple
ExecStart=/usr/bin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -i%I

[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service
```

I searched the wiki but couldn't find anything - https://www.google.com/search?sitesearch=https%3A%2F%2Fwww.freedesktop.org%2Fwiki%2F&q=enable+unit+template+without+systemctl

**Comment by floppym** [comment]
This is an issue tracker, not a support forum. You can send your question to the systemd-devel mailing list if you are unable to find help elsewhere.

**Comment by abitrolly** [comment]
@floppym this is a request to document `systemd` behaviour, and an issue with search on https://systemd.io/ domain.

Going through the cycle of subscribing, sending the message, filtering mailbox until the answer is sent, and then unsubscribing is not very user friendly. Support forums are much easier in this respect and that's another issue.

**Comment by TriMoon** [comment]
@abitrolly 
`wpa_supplicant@.service` is a template, and you are not  (should not be) able to enable templates on their own...
You can only enable instances that inherit settings from the template...
You can however use the [DefaultInstance=](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#DefaultInstance=) keyword in the template file itself...

**Comment by boucman** [comment]
and all that is documented in man:systemd.unit.

**Comment by abitrolly** [comment]
> You can however use the DefaultInstance= keyword in the template file itself or in a drop-in file for the template...

Not sure what that means.

> Instead of using systemctl enable you can also manually create the necessary symbolic links that are created by using that command...

@TriMoon this is what I had in mind. But is it just a symbolic link? I need to pass the `wlan0` param to it somehow. Tried to inspect changes inside LXD container, but there is no such file there. Not sure why.

**Comment by floppym** [comment]
If you run `systemctl enable wpa_supplicant@wlan0.service`, it will tell you exactly what it is doing. You could easily replicate the same step(s) without calling systemctl.

Also, the actions of `systemctl enable` are explained thoroughly in the `systemctl(1)` man page.

**Comment by TriMoon** [comment]
@abitrolly i suggest you read-up more on how/what/etc systemd is and how to use it, because we have answered enough with info already available in the documentation.
No one will provide an online course for you personally :wink:

**Comment by abitrolly** [comment]
Thanks for the pointers. I read the links, and if I understood what I read correctly, the symlink to all places in `[Install]` section should be enough. In my case the symlink should be located under `/etc/systemd/system/multi-user.target.wants`.
```
[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service
```
I created it as following, where `$MOUNT` is the current mount point for SD image (which is `/run/media/root/ROOT`.
```
ln -s \
  /usr/lib/systemd/system/wpa_supplicant@.service \
  "$MOUNT/etc/systemd/system/multi-user.target.wants/wpa_supplicant-wlan0.conf"
```
Now that I looks at this, maybe the extension `wpa_supplicant-wlan0.conf` is wrong and it should be `wpa_supplicant-wlan0.service`?

I still don't know if it works. The device is not responding to pings by `hostname`, and its IP is unknown. I am trying to figure out how to `enable` some other service like `mdns` to understand that the device is online.

**Comment by boucman** [comment]
The name of the file in the .wants directory must be the same as the file pointed to with the instance name added. you can't nae it .conf

**Comment by abitrolly** [comment]
@boucman thanks. I will try it next time I get to the device. It would be much easier to debug if the nework was already there.

**Comment by poettering** [comment]
This is a bug and RFE tracker, not a support forum. Use the mailing list for support questions. Thank you for understanding.

To keep frustration low the submission form is supposed to make it very clear that this is not the place to ask support questions and where to ask them instead.

**Comment by abitrolly** [comment]
@poettering why redirect users to mailing list instead of documentation? If there is no documentation o this topic, then mailing list won't help either, because this is a documentation request.

**Comment by boucman** [comment]
it's documented in man:systemd.unit
