### ISSUE TITLE
X11/Wayland specific user targets

### ISSUE THREAD

**Issue by xdbob** [systemd/systemd#15112]
**Is your feature request related to a problem? Please describe.**
I am working on wayland specific user services and I didn't find satisfying ways to differentiate X11/Wayland at the user service level (see https://github.com/emersion/mako/pull/240).

**Describe the solution you'd like**
I wish that systemd provides targets to make this easier by providing new user targets (`{x11,wayland}{,-pre}-session.target`, see https://github.com/xdbob/sway-services/blob/master/systemd/wayland-session.target)

**Describe alternatives you've considered**
I have considered using `ExecCondition` but I would like to have a meaningful way to express it

PS: I am willing to implement it and give a PR if you agree with the concept

**Comment by poettering** [comment]
I guess we can close this, given that #15180 has been closed now.
