### ISSUE TITLE
UseRoutes=no is no longer working as before (because of #14983)

### ISSUE THREAD

**Issue by davdiv** [systemd/systemd#15117]
**systemd version the issue has been seen with**
> systemd 245 (245-3-arch)

**Used distribution**
> Arch Linux

**Expected behaviour you didn't see**
> I was expecting UseRoutes=no in [DHCPv4] in a `.network` file to prevent all routes, including the default one, from being added. It was working correctly until #14983 broke this expected behaviour.

**Unexpected behaviour you saw**
> Now, the default gateway is added.
> The changed behavior seems to come from #14983, which is described as a simple bug fix but it is in fact a non-backward compatible change. It broke my network configuration!

@ssahani and @yuwata do you think you could either revert the change or at least make the configuration possible with a `UseGateway=` parameter?

Thank you very much for all the work you do for the community!

**Comment by yuwata** [comment]
@ssahani I will work on this. Or are you already working on this?

**Comment by ssahani** [comment]
> @ssahani I will work on this. Or are you already working on this?

No I am not . Please go ahead . Thanks I am working on some networkctl tunnel display now.

**Comment by yuwata** [comment]
Fix is waiting in #15136. If possible, please test the PR. Thank you.

**Comment by davdiv** [comment]
@yuwata Thank you for answering and working on a fix so quickly!
I don't know how to test the fix before it is integrated in my distribution (Arch Linux).
I think your fix is working anyway.
Thank you again for all the great work you do!
