### ISSUE TITLE
fscrypt suspend support for homed

### ISSUE THREAD

**Issue by NeoTheFox** [systemd/systemd#15113]
Right now it's only possible to use `suspend` option of `pam_systemd_home.so` if luks storage is used

According to the [kernel docs](https://www.kernel.org/doc/html/latest/filesystems/fscrypt.html) fscrypt supports this functionality via `FS_IOC_REMOVE_ENCRYPTION_KEY` ioctl.

**Comment by poettering** [comment]
As I understand using that ioctl will just lock the files again, and not actually suspend access again. I.e. after calling that any access attempts will result in failure, but what they should result in is hanging access. In particular as I understand it it's supposed to be called when all files on the encrypted dir are closed, but that's not what suspending means, we after all want to keep the session running with all fds open, but just freeze things temporarily.

What am I missing?

**Comment by poettering** [comment]
Actually let's close this. I am pretty sure the available APIs are not suitable for temporarily suspending access in a "freezing" fashion, and thus not suitable for what we want to do here.

I'd be happy if I was wrong, but afaics i am not. If you figure out more, please let me know, we can reopen the issue.
