### ISSUE TITLE
Feature Request: Allow "listen-only" mode for socket can interfaces

### ISSUE THREAD

**Issue by trabant-asb** [systemd/systemd#15129]
The support for CAN (Controller Area Network) devices was added to systemd in 2018 (as per #9185). Currently, there are several supported options like CAN.BitRate, CAN.SamplePoint, CAN.RestartSec, however the "listen-only" mode is not yet implemented. 

Listen-only is important to sniff on CAN networks without letting the other bus members know that a third party device is even attached, as it would be with a simple ACK message sent from that device.

Unfortunately, I'm not deep enough in that code for that I could do the required code changes on my own.

**Comment by yuwata** [comment]
Please test #15133 if possible. Thank you.
