### ISSUE TITLE
homectl support for additional or arbitrary mount options

### ISSUE THREAD

**Issue by cmurf** [systemd/systemd#15120]
**Is your feature request related to a problem? Please describe.**
There are a number of use case specific mount options: e.g. on Btrfs, supporting various compression algorithms and levels, autodefrag, flushoncommit, ssd_spread for USB flash, user_subvol_rm_allowed. Possible other file systems have use case specific options as well.
, 
**Describe the solution you'd like**
I think a facility to set arbitrary mount options, set by create and update subcommands, and stored in the homed metadata, and applied every time the volume is activated.

**Describe alternatives you've considered**
The user could manually `-o remount,compress=zstd:1` but as this is an optimization, it's suboptimal to have to do it manually. Plausibly the desktop environment could do this; or maybe systemd supports a user specific generator that could do the remount. Still another option would be supporting /etc/fstab, if the homed UUID is specified in fstab then honor the listed mount options there.

**Comment by poettering** [comment]
i guess we could add a record to the json user record, with extra mount options

**Comment by poettering** [comment]
i figure user_subvol_rm_allowed should actually be the default for btrfs mounts homed does
