### ISSUE TITLE
[RFI] Document the key used to show menu at boot

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#15125]
**Is your feature request related to a problem? Please describe.**
It is so frustrating to not be able to find an answer to the question "How do i show the boot menu of `systemd-boot` at boot time when timeout=0"
I had to dig into [the source-code to find it](https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L748)...

**Describe the solution you'd like**
It should **at least** be documented under `KEY BINDINGS` of `systemd-boot(7)` that pressing <kbd>F1</kbd> will show the boot-menu when it is not shown by default at boot.

**Describe alternatives you've considered**
If this key, which worked for me, is not the right one please document THAT instead.

**Comment by poettering** [comment]
actually, pretty much any key works. Not just F1. But you are right, this deserves some documentaiton.

**Comment by TriMoon** [comment]
> actually, pretty much any key works. Not just F1. But you are right, this deserves some documentaiton.

Thanks for doing that :+1: , but...
Why isn't the <kbd>F1</kbd> key documented while it's used in [the source](https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L753)?
