### ISSUE TITLE
LLDP=false should be the default for bond interfaces

### ISSUE THREAD

**Issue by rfc1036** [systemd/systemd#15146]
**systemd version the issue has been seen with**
241

**Used distribution**
Debian

**Expected behaviour you didn't see**
LLDP should not be active by default on bonding interfaces because it makes no sense: LLDP is a link layer protocol and is only meaningful for physical interface.
This probably should apply also to bridge interfaces.

**Unexpected behaviour you saw**
`networkctl lldp` shows received LLDP data for the bond0 interface.

**Steps to reproduce the problem**
Configure a `Kind=bond` interface, configure `EmitLLDP=true` on the underlying physical interface(s).

**Comment by poettering** [comment]
fix waiting in #15565
