### ISSUE TITLE
zsh completion fails after "systemctl stop"

### ISSUE THREAD

**Issue by hexchain** [systemd/systemd#15161]
**Edit:** This issue has already been reported and fixed in #15077. See the following comment for another one.

**systemd version the issue has been seen with**
 > 245

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > zsh shows completions correctly.

**Unexpected behaviour you saw**
 > zsh inserts `●.service`.

**Steps to reproduce the problem**
1. Save the following file as `zshrc-test`:
   ```
   HISTFILE=/dev/null
   autoload -Uz compinit
   compinit
   ```
2. Run zsh with `zsh -d -f` (without loading rc files) and then `source zshrc-test`
3. Enter `systemctl stop `
4. Press TAB multiple times.

**Comment by hexchain** [comment]
Another fail:
Enter `systemctl disable d` and press TAB multiple times. Zsh complains:
```
_systemctl_unit_state: bad set of key/value pairs for associative array
```

**Comment by hexchain** [comment]
I've probably found the cause to the first failure: I have a failed unit and it has a "●" symbol before its name in `systemctl list-units`.

**Comment by joukewitteveen** [comment]
I haven't looked into this issue specifically, but given its relation to #15077, it may be fixed by #15458.

**Comment by hexchain** [comment]
> I haven't looked into this issue specifically, but given its relation to #15077, it may be fixed by #15458.

Yes, the original one is fixed by #15458, but the other one still remains.

**Comment by joukewitteveen** [comment]
Too bad.
Note that #15458 was *not* the (original) change that fixed #15077. With #15458, the `systemctl` interface was cleaned up slightly and the shell-completions were updated.

**Comment by hexchain** [comment]
With the current git master:

```
% local -A us
% us=($(./systemctl --full --no-pager --no-legend --plain list-unit-files "c*" ))
zsh: bad set of key/value pairs for associative array
% ./systemctl --full --no-pager --no-legend --plain list-unit-files "c*"
clevis-luks-askpass.path                disabled disabled
caddy.service                           disabled disabled
canberra-system-bootup.service          disabled disabled
canberra-system-shutdown-reboot.service disabled disabled
canberra-system-shutdown.service        disabled disabled
clean-mount-point@.service              static   disabled
clevis-luks-askpass.service             static   disabled
colord.service                          static   disabled
conntrackd.service                      disabled disabled
console-getty.service                   disabled disabled
container-getty@.service                static   disabled
cpupower.service                        disabled disabled
create_ap.service                       disabled disabled
cups-browsed.service                    disabled disabled
cryptsetup-pre.target                   static   disabled
cryptsetup.target                       static   disabled
ctrl-alt-del.target                     disabled disabled
% us=($(./systemctl --full --no-pager --no-legend --plain list-unit-files "f*" ))
% ./systemctl --full --no-pager --no-legend --plain list-unit-files "f*"
fancontrol.service            disabled disabled
firewalld.service             enabled  disabled
flatpak-system-helper.service static   disabled
fstrim.service                static   disabled
fwupd-offline-update.service  static   disabled
fwupd-refresh.service         static   disabled
fwupd.service                 static   disabled
final.target                  static   disabled
fstrim.timer                  enabled  disabled
fwupd-refresh.timer           disabled disabled
% typeset -p us
typeset -A us=( [disabled]=disabled [enabled]=disabled [fancontrol.service]=disabled [flatpak-system-helper.service]=static [fstrim.timer]=enabled [fwupd-offline-update.service]=static [fwupd.service]=static [static]=disabled )
```

**Comment by joukewitteveen** [comment]
I'm no zsh guru, but there's a lot more processing going on in the zsh completion file (e.g. `all_unit_files=( ${${(f)"$(__systemctl list-unit-files "$PREFIX*" )"}%% *} )`), which leads me to believe that the output you are showing is not indicative of any bug. Unless of course `systemctl disable d<TAB>` yields an error. That could be a bug in the completion file.

**Comment by joukewitteveen** [comment]
Digging a little deeper, I think I have found the issue.

In b01c1f305c044a381ad110709a62507d74bf6d86 a third column was introduced in the output of `systemctl list-unit-files`. This trips up [line 224 of the completion script](https://github.com/systemd/systemd/blob/v245/shell-completion/zsh/_systemctl.in#L224). The solution is probably to simply drop the shortest suffix matching `' *'`. In other words, adding `% *` somewhere on that line of the completion script. My knowledge of zsh is insufficient to know for sure how this should be done exactly, but I guess this should be pretty easy for anyone with a working knowledge of zsh.

**Comment by hexchain** [comment]
> The solution is probably to simply drop the shortest suffix matching `' *'`.

I don't think so. The output of `systemctl` is directly fed to the associative array in line 224, so I guess some kind of filter must be in place to drop the third column before feeding the values into the array.

**Comment by joukewitteveen** [comment]
> some kind of filter must be in place to drop the third column

Wouldn't dropping the shortest suffix matching ` *` achieve just that? Except for some trailing spaces on the second column that remain, but likely get trimmed by word-splitting.

**Comment by hexchain** [comment]
> > some kind of filter must be in place to drop the third column
> 
> Wouldn't dropping the shortest suffix matching ` *` achieve just that? Except for some trailing spaces on the second column that remain, but likely get trimmed by word-splitting.

Yes, sorry, you are right. I've played with it a bit more and this is what I have for now:

```
% systemctl --full --no-pager --no-legend --plain list-unit-files "e*"
e2scrub@.service      static   disabled
e2scrub_all.service   static   disabled
e2scrub_fail@.service static   disabled
e2scrub_reap.service  disabled disabled
ebtables.service      disabled disabled
emergency.service     static   disabled
emergency.target      static   disabled
exit.target           disabled disabled
e2scrub_all.timer     disabled disabled
% declare -A test=( ${(s. .)${(f)"$(systemctl --full --no-pager --no-legend --plain list-unit-files "e*")"}% *} ); typeset -p test
typeset -A test=( [e2scrub@.service]=static [e2scrub_all.service]=static [e2scrub_all.timer]=disabled [e2scrub_fail@.service]=static [e2scrub_reap.service]=disabled [ebtables.service]=disabled [emergency.service]=static [emergency.target]=static [exit.target]=disabled )
```

**Comment by joukewitteveen** [comment]
Looks alright to me (but again: I'm not too familiar with the zsh syntax).
If you're confident regarding the solution, please file a pull request!

**Comment by hexchain** [comment]
Okay this is getting more interesting. `systemctl` sometimes spits out lines ending with spaces:

```
% systemctl --full --no-pager --no-legend --plain list-unit-files "getty*"
getty@.service   indirect enabled
getty-pre.target static   disabled
getty.target     static   disabled
% declare -a test=( ${(f)"$(systemctl --full --no-pager --no-legend --plain list-unit-files "getty*")"} ); typeset -p test
typeset -a test=( 'getty@.service   indirect enabled ' 'getty-pre.target static   disabled' 'getty.target     static   disabled' )
```
There is an extra space at the end of the `getty@.service` line, and that breaks `% *`.
