### ISSUE TITLE
Support shell script for StandardOutput/StandardError parameters

### ISSUE THREAD

**Issue by ccasallas** [systemd/systemd#15164]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support shell script for **StandardOutput** and **StandardError** parameters. Some times is required a new log file in each reboot of a service. Enable shell script allow to define file names dynamically. For example, appending the current date:
StandardOutput=file:/home/log/$(date +%Y-%m-%d_%H-%M-%S)-output.log

**Describe alternatives you've considered**
No one.

**Comment by cdown** [comment]
I think it's very unlikely we'd add unfettered access to the shell through an interface like this: it's clunky and doesn't give any opportunity for error handling. However, if you have a specific dynamic case that might be generally applicable, there may be the possibility of having a format applied. We'd need to see the use case being widely applicable enough, though.

**Comment by poettering** [comment]
I am not seeing the point of this. If you want a shell variable expansion and pipelines then use a shell. I am very strongly opposed in reinventing a shell in systemd. bash and friends are fine, if what you want is a shell. Sorry.

**Comment by ccasallas** [comment]
Hi @cdown and @poettering 

Thanks for your time and your viewpoints. Maybe you can guide me how I can do  with systemd at this moment to create a new standard output file in each new service execution. From my knowledge I thought that using shell script was a valid option, maybe there is a better way to do it on systemd.

My current solution is this:

[Unit]
Description=My java app
After=syslog.target
[Service]
User=ubuntu
Type=simple
ExecStart=/bin/sh -c 'exec /usr/bin/java -jar /home/myApp.jar 2> /home/$$(date +%%Y-%%m-%%d_%%H-%%M-%%S)-my-app-error.log > /home/$$(date +%%Y-%%m-%%d_%%H-%%M-%%S)-my-app.log'
SuccessExitStatus=143
[Install]
WantedBy=multi-user.target

**Comment by poettering** [comment]
The solution you came up with looks great, if it works, and this is what you want.
