### ISSUE TITLE
systemctl --user import-environment fails 

### ISSUE THREAD

**Issue by gnzlbg** [systemd/systemd#15179]
On my system when I type:

> $ systemctl --user import-environment
> Failed to import environment: Invalid environment assignments

I would have liked to either fix a bug on a configuration file on my side, or maybe open a more useful bug report here with an actual reproducer. Unfortunately, I don't know which line in the **hundreds** of configuration files in my system is causing the problem.

I've set `LogLevel=debug`, and I have inspected `journalctl`, without any luck. I've also been trying to find a way to diagnose this problem for 2 hours now without any luck, so there are IMO multiple bugs here:

* the error message hints that a parser failed parsing a file somewhere, so I'd expect a file name, line number, and column is displayed (or if it is parsing something that's not a file, maybe a dump somewhere of what was parsed succesfully and what failed), and the reason why parsing actually failed. That would have allowed me to either fix my issue, or fill a more informative bug.
* the debug logs do not contain any meaningful information about parsing filing at all
* the documentation doesn't really explain how to debug these kind of issues - while there are some pages about how to debug systemctl, I think I've exhausted all resources I tried to find. While I've definitely have missed some resources, I tried the best I could.

**Comment by arvidjaar** [comment]
> the error message hints that a parser failed parsing a file somewhere

`import-environment` does not parse any file as should be clear from manual page. It sends to `systemd` full current environment as inherited by `systemctl`. 

The reason for these errors are

- "invalid" variable name (hint - do you have any exported function?)
- value is not UTF-8
- value contains TAB or LF character (which is yet another reason to reject exported functions)
- value too large (SC_ARG_MAX)

You should be able to check it yourself. If nothing stands out, attach output of `env`.

Printing more meaningful information is not exactly trivial as function that checks for valid assignment does not really return **which** assignment was invalid.

**Comment by gnzlbg** [comment]
I've executed `env` in my current shell, the output is here: https://gist.github.com/gnzlbg/3027279324c120aa4f47207e958669fc

**Comment by arvidjaar** [comment]
You have exported functions which `systemd` does not accept.

**Comment by gnzlbg** [comment]
So how do I fix that? Or does that mean that `systemd --user import-environment` is not intended to be used from, e.g., a `bash` shell that contains imported functions ?
