### ISSUE TITLE
Please remove hard-coded "net.core.default_qdisc = fq_codel"

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#15183]
**Is your feature request related to a problem? Please describe.**
> I didn't compile fq_codel module, so
```
# Fair Queue CoDel packet scheduler to fight bufferbloat
net.core.default_qdisc = fq_codel

```
> throws an error message.

**Describe the solution you'd like**
> Make it configurable.

**Describe alternatives you've considered**

**Comment by zdzichu** [comment]
It is configurable. Copy `50-default.conf` to `/etc/sysctl.d/` and remove fq_codel line.
Files in `/etc` override files in `/usr`.

**Comment by poettering** [comment]
hmm, maybe we should make this build-time configurable (i.e. a meson flag), since it's configurable in kernel building too.

**Comment by dtaht** [comment]
I'm always kind of curious as to why people wouldn't build fq_codel, sch_fq, and cake.....

**Comment by flokli** [comment]
Aren't these sysctl files "suggestions" meant to be "considered" by downstream packagers as it fits?

If you're building your own kernel lacking features the distro kernel ships, I'd propose just overriding it, but I'm not sure if adding knobs for everything in the build system is desirable.

**Comment by Thaodan** [comment]
Can this be closed after https://github.com/systemd/systemd/commit/fa98c99ea7f7c5bec3962fa52f4d3496a9777024?

**Comment by dtaht** [comment]
I guess I'm confused. For the last 8 years or so, the vast majority of systemd distros ended up with fq_codel as the default qdisc via this method. Really happy about that, it's been sitting there subtly doing it's job (primarily the fq portion) for billions of containers in particular.  Otherwise the qdisc default has to be set explicitly in the kernel, or by the distro, and in many cases, defaults still to pfifo_fast. So I'd kind of consider it a regression if all of a sudden everybody went back to pfifo_fast.

https://en.wikipedia.org/wiki/FQ-CoDel

**Comment by flokli** [comment]
https://github.com/systemd/systemd/commit/fa98c99ea7f7c5bec3962fa52f4d3496a9777024 prefixed the sysctl line with a `-`, which will only silence the warning if net.core.default_qdisc cannot be set.

From `sysctl.d (5)`:

```
       Any access permission errors and attempts to write variables not present on the local system are logged at debug level and do not cause the service to fail. Other
       types of errors when setting variables are logged with higher priority and cause the service to return failure at the end (after processing other variables). As
       an exception, if a variable assignment is prefixed with a single "-" character, failure to set the variable for any reason will be logged at debug level and will
       not cause the service to fail.
```

Systemd still tries to set it (assuming distros ship that sysctl files), but doesn't fail anymore the whole service if it can't (for example when the running kernel is compiled without fq_codel support).

**Comment by dtaht** [comment]
OK, thx, that's a relief.

**Comment by ivanbaldo** [comment]
Shouldn't this issue be closed now?

**Comment by yuwata** [comment]
Yeah, at least, the original issue was already fixed.
