### ISSUE TITLE
systemctl cat does not work in chroot

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [systemd/systemd#15182]
**systemd version the issue has been seen with**
```
systemctl --version
systemd 244 (244.3-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

see:
https://github.com/random-archer/mkinitcpio-systemd-tool/issues/32#issuecomment-602026850
```
I guess systemctl cat <unit> is not allowed to be run in a chroot. That's pretty meh...
```

**Comment by boucman** [comment]
I am not sure what you mean, you probably need to provide a bit more details

IIUC you mean that if you run "systemctl cat <unit>" within a chroot, you expect to see the content of the corresponding unit outside the chroot ?

If that's what you want, then... no systemctl can't do that, and that's the whole point of a chroot. that has nothing to do with systemctl

when you are inside a chroot, you can't see files outside the chroot.

if your bug is something else, then please explain a bit more...

**Comment by Andrei-Pozolotin** [comment]
I mean, when running in chroot, while trying to merge override with base service unit
`systemctl cat` reports:

1. plain invocation:
```
Running in chroot, ignoring request: cat
```

2. invocation with `SYSTEMD_IGNORE_CHROOT=1`
```
Failed to connect to bus: No data available
```

**Comment by boucman** [comment]
do you run systemd in your chroot ?

**Comment by Andrei-Pozolotin** [comment]
no, full systemd init pid 0 context is not started

**Comment by boucman** [comment]
then if there is no systemd, systemctl can't ask systemd about stuff, which is the error you are reporting.

**Comment by Andrei-Pozolotin** [comment]
then perhaps there should be a `systemd-cat` incarnation capable of working "off-line"?

**Comment by Andrei-Pozolotin** [comment]
and then the message `Running in chroot, ignoring request: cat` 
makes one think "it almost works" :-)

**Comment by boucman** [comment]
well, it makes me think "devs are aware of that case and explicitely  tell you it won't work"

you could try with $SYSTEMCTL_INSTALL_CLIENT_SIDE=1
( see https://github.com/systemd/systemd/blob/master/docs/ENVIRONMENT.md )

**Comment by Andrei-Pozolotin** [comment]
> well, it makes me think "devs are aware of that case and explicitely tell you it won't work"

no, my interpretation is much more hopeful ;-)

so, basically, no dice? will never be fixed?

**Comment by boucman** [comment]
it's not a bug. you are not supposed to access the unit files from within a chroot,

**Comment by Andrei-Pozolotin** [comment]
ok, cool. thank you for clarification

**Comment by moooofly** [comment]
> no, full systemd init pid 0 context is not started

Should it be "PID 1"?
