### ISSUE TITLE
Script 50-systemd-user.sh running after service has been started

### ISSUE THREAD

**Issue by davidmogar** [systemd/systemd#15184]
**systemd version the issue has been seen with**
> 245-3

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > DISPLAY variable defined for user services

**Unexpected behaviour you saw**
 > DISPLAY variable is not defined

**Steps to reproduce the problem**
The service I'm using is the following one:
```
[Unit]
Description=Simple X Hotkey Daemon
After=graphical.target

[Service]
ExecStart=/usr/bin/sxhkd -c %h/.config/sxhkd/sxhkdrc

[Install]
WantedBy=default.target
```
When I log in through lightdm, the service is started but fails as it cannot find the display. If I restart the service, it works. It seems like a race condition between my service and the execution of `50-systemd-user.sh`.

**Comment by oakszyjrnrdy** [comment]
I still came with this bug on Arch. Have you figured it out?
