### ISSUE TITLE
networkd - interferes with /etc/sysctl.conf - AGAIN - accept_ra

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#1519]
systemd 227

systemd-networkd now - again - interferes with settings from /etc/sysctl.conf.  And, just to make things interesting, the result is unpredictable, depending upon whether systemd-sysctl.service runs before or after systemd-networkd.  And then, 1) there is no warning, and 2) there is no understandable documentation.

Lennart, I've read your opinion on this issue of networkd interfering with sysctl, and I will continue to disagree.  I'm going to try very hard to avoid ranting or swearing in capital letters.

1) This needs to be documented properly.  There needs to be a BIG FAT WARNING that says "Systemd 227 WILL BREAK your current sysctl settings!"

2) This needs to be documented properly.  The current man page description is meaningless.
"IPv6AcceptRouterAdvertisements= This is enabled if local forwarding is disabled. Disabled if local forwarding is enabled. Takes a boolean. Defaults to  unset."  As you know, there are _three_ states to "net.ipv6.conf.<interface>.accept_ra", "0", "1", and "2".  Three states do not make a "boolean", so the description is immediately confusing.  And the sentence "This is enabled if..." suggests that the setting itself is automatic and changes nothing, which makes no sense.

I would encourage you to, at least, simply use the wording from the git commit, which makes somewhat more sense:
"Set accept_ra to "2" if enabled in config.  This causes the kernel to accept router advertisments even if ip forwarding is enabled for this interface."

3) I will say again - and again and again - that these sort of "interferences" should default to NOT BREAKING an existing sysctl configuration.  There is already an "IPForward=kernel" setting.  It is at first counterintuitive that, having set this, it does not also disable "IPv6AcceptRouterAdvertisements= ".  So now, there needs to be an "IPv6AcceptRouterAdvertisements=kernel" setting.  Really, there needs to be a "DoNotTouchSysctl=" setting.  Either way, there should be a _consistent_ approach to disabling sysctl overrides.

4)  There should NOT be a race condition between systemd-sysctl.service and systemd-networkd.  In other words, the result of setting - or not setting - sysctl.conf or "IPv6AcceptRouterAdvertisements=" should not produce unpredictable results.

**Comment by thx1111** [comment]
BTW, the immediate work-around for the race condition would be to require that _both_ any sysctl.conf and any .network file have the same accept_ra setting, so that whichever "wins", the result will be the same.

**Comment by thx1111** [comment]
Losing accept_ra=2 with forwarding will make the ipv6 network unreachable on that interface because, without the router advertisement, there is no prefix for the kernel to derive an address or a prefix route.

**Comment by poettering** [comment]
The documentation has been improved with #1544.

**Comment by falconindy** [comment]
Why do we keep replacing perfectly good knobs provided by the kernel with new knobs providing different defaults (and new surprising behavior)? Shouldn't we have learned from what happened with ip forwarding? Improving the documentation is nice, but silent breakage isn't something that's easily discoverable...

**Comment by marineam** [comment]
Documentation is insufficient for incompatible changes. Similar to IPFoward the best option is probably going to be `IPv6AcceptRouterAdvertisements=kernel` and even if systemd keeps `false` as the default CoreOS is going to need to carry a patch switching the default from `false` to `kernel` like we do for IPForward.

**Comment by marineam** [comment]
On the up side, IPv6 deployment remains poor enough that rolling it out as-is would break fewer systems than IPForward would have. :P

**Comment by tribals** [comment]
I don't have the time to figure out all that intrinsic of "it will be enabled if either this or that". The proper solution is `systemctl disable --now systemd-networkd; systemctl mask systemd-networkd`. Nothing new, actually - that people continue arguing they're programmers, but they aren't.
