### ISSUE TITLE
systemd-fstab-generator does not recognise davfs entries in fstab as network mounts

### ISSUE THREAD

**Issue by pelzvieh** [systemd/systemd#15198]
**systemd version the issue has been seen with**
> 244.3-1

**Used distribution**
 > Debian bullseye

**Expected behaviour you didn't see**
 > adding davfs mounts with option auto,nofail,... to /etc/fstab mounts these volumes on system startup.
 > I believe that davfs is by its nature a network fs type and such entries in fstab should be generated with network dependency without adding explicitly the _netdev option.

**Unexpected behaviour you saw**
 > The davfs volume is not mounted because the mount is attempted when the network is not yet set up.
 > systemd-fstab-generator generates mount units in /run/systemd/generator with local-fs dependency instead of network dependency. This is the expected behaviour for local volumes in fstab, i.e. the generator treats davfs as local fs type.

**Steps to reproduce the problem**
Create an entry in /etc/fstab to a davfs resource, similar to:
`https://some.host.example/nextcloud/remote.php/webdav/somepath/ /var/lib/somepackage/somedir davfs auto,nodev,noexec,nosuid,grpid,user,uid=somesystemuser,nofail,conf=/var/lib/somesystemuser/.davfs2/davfs2.conf 0 0`
Correct behaviour can be enforced by adding _netdev to the options part.

**Comment by allen2424** [comment]
I meet the same issues, the fstab option _netdev is not working for the davfs items, the davfs is not mount after system startup.

**Comment by allen2424** [comment]
> 

pi@raspberrypi:~ $ mount.davfs -V
davfs2 1.5.5  <http://savannah.nongnu.org/projects/davfs2>

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
