### ISSUE TITLE
systemd-resolved: Bad Global DNS Servers + Bad orders

### ISSUE THREAD

**Issue by moocan** [systemd/systemd#15202]
Hello,

Computers are connected to an internal network `10.31.0.0` which is using an `internal DNS server 10.31.0.254`.
DNS Server forward DNS queries to another `internal DNS 10.30.0.253` through a Netgear Firewall using `10.30.0.254`.
`Internal DNS Server 10.30.0.253` forward queries when necessary to Internet Router `192.168.100.254` using `192.168.100.253`.

`10.31.0.xxx <->  10.31.0.254 -| DNS |- 10.30.0.254 <-> 10.30.0.253 -| DNS/Firewall |- 192.168.100.253 <-> 192.168.100.254 -> Internet`

`systemd-resolved` reports in Global DNS Server these servers: 
```
10.30.0.253
192.168.100.254
10.31.0.254
```

Local DNS server 10.31.0.254 appear always in last position.

```
Global
         DNS Servers: 10.30.0.253
                      192.168.100.254
                      10.31.0.254
          DNS Domain: mydom.int
                      ~.
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 23 (enp1s0.3100)
      Current Scopes: LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp2s0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (enp1s0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 10.31.0.254
                      fd01:2d94:a73::1
          DNS Domain: mydom.int
```

Only one network connection is active on `10.31.0.0` network.
We are using `NetworkManager`.
DNS Server 10.31.0.254 and Domain search is fully attributed with DHCP.

Why `DNS Servers 10.30.0.253 and 192.168.100.254` are reported ? and discovered ?
These DNS Servers are not specified or hardcoded in any config files.
Even when stopping NetworkManager service these servers are reported.
No Ethernet connection are reporting these DNS Servers.
The only one which is specified is `10.31.0.254` which is in last position.

`Domains` value is specified in `/etc/systemd/resolved.conf` (Domains=mydom.int)
But local DNS names queries are sent to `10.30.0.253 and 192.168.100.254` which can't resolve local names

To force querying the good DNS Server `10.31.0.254` we added this in a config file` /etc/systemd/resolved.conf.d/dns_servers.conf`
```
[Resolve]
DNS=10.31.0.254
Domains=~.
```

Now this DNS Server appear in first place.
But due to mobility when connecting laptop on other networks, `systemd-resolved` is always trying to query `10.31.0.254` as primary DNS.

So how to purge Global DNS Servers list ?
How to prevent systemd-resolved to "discover" DNS servers other than these specified by the DHCP or configured in NetworkManager ?
We tried to manually edit /run/systemd/resolve/resolv.conf (I know ... Do not edit.) but even without any ethernet connection and restarting systemd-resolved service these DNS Servers are always reported and again available in `/run/systemd/resolve/resolv.conf`

The only laptops that work as intended `systemd-resolved` has been disabled and replaced by other mecanisms.
Is there any way to do it using `systemd-resolved` ?

Kind Regards

**systemd version the issue has been seen with**
> ... 237

**Used distribution**
 > … Ubuntu 18.04 LTS

**Expected behaviour you didn't see**
 > … Only DNS Servers from DHCP
or those configured in NetworkManager.

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

**Comment by poettering** [comment]
Sorry, but v237 is waaay to old. We only track issues in the two most recent systemd versions here, and this is clarified in the submission form, in order to keep frustration low.

Please reproduce your issue with current systemd, there have been a ton of fixes going in resolved since 237...

For everything older than 244 please ping your distro regarding bugs.

Sorry!
