### ISSUE TITLE
make error /bin/bash: -o: command not found

### ISSUE THREAD

**Issue by kennedy-han** [systemd/systemd#1521]
The last N rows output

```
  CC       src/dbus1-generator/dbus1-generator.o
  CCLD     systemd-dbus1-generator
  CC       src/udev/ata_id/ata_id.o
  CCLD     ata_id
  CC       src/udev/cdrom_id/cdrom_id.o
  CCLD     cdrom_id
  CC       src/udev/collect/collect.o
  CCLD     collect
  CC       src/udev/scsi_id/scsi_id.o
  CC       src/udev/scsi_id/scsi_serial.o
  CCLD     scsi_id
  CC       src/udev/v4l_id/v4l_id.o
  CCLD     v4l_id
  CC       src/udev/mtd_probe/mtd_probe.o
  CC       src/udev/mtd_probe/probe_smartmedia.o
  CCLD     mtd_probe
  GEN      man/custom-entities.ent
  GEN      man/custom-entities.ent
  XSLT     man/bootup.7
/bin/bash: -o: command not found
make[2]: *** [man/bootup.7] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by kennedy-han** [comment]
I run `/bin/bash -o` and it exist

**Comment by keszybz** [comment]
Please paste the output from from 'make V=1'.

**Comment by kennedy-han** [comment]
https://gist.github.com/kennedy-han/5e833e1374b45a068566

**Comment by fsateler** [comment]
@keszybz the errors are at the end of the raw log (the link shows a truncated file, you need to click through to the full file).

```
o man/bootup.7 --nonet --xinclude --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 --stringparam systemd.version 227 --path './man:./man' ./man/custom-man.xsl man/bootup.xml
/bin/bash: o: command not found
```

and so on for all manpages.

**Comment by keszybz** [comment]
That's really strange. Can you show how you run configure and what's the output?

**Comment by floppym** [comment]
Might also want to check the environment for variables containing wierd values.

**Comment by kennedy-han** [comment]
I run `./configure --prefix=/usr/local &> conf.log`

and there is the conf.log file:

https://gist.github.com/kennedy-han/686794e6833fc38a9403

**Comment by floppym** [comment]
```
checking for xsltproc... no
```

So you are building with man pages enabled but do not have xsltproc installed. configure.ac should probably be updated to throw an error under this condition.

**Comment by kennedy-han** [comment]
yeah

:+1: 

I run 
`sudo apt-get install xsltproc`
`sudo apt-get install docbook-xsl`

and it's worked

thanks
