### ISSUE TITLE
sd-pam in /proc/<pid>/stat

### ISSUE THREAD

**Issue by icegood** [systemd/systemd#15216]
Here is an output of sd-pam process statistiscs right from
/proc/<pid>/stat/ file:

2246 ((sd-pam)) S 2245 2245 2245 0 -1 1077936448 48 0 0 0 0 0 0 0 20 0 1 0 1971 172810240 821 18446744073709551615 94266113667072 94266114572037 140724155513776 0 0 0 0 4096 0 1 0 0 17 6 0 0 0 0 0 94266114906480 94266115166360 94266128642048 139824204562432 139824204562441 140724155518766 140724155518957 0

It is not expected for name to be in double parentheses, which confuses at least htop

**Comment by anitazha** [comment]
Should this be an issue filed to `htop` instead? Systemd names some of it's forked processes with parentheses, causing them to appear with double parentheses in `/proc/$PID/stat`. But AFAIK that is acceptable and should be handled accordingly by applications reading it.

**Comment by keszybz** [comment]
What do you mean by "confuses htop"? htop seems to display such processes just fine here.
Anyway, let's close this, since putting process names in parens is a well  established pattern.
