### ISSUE TITLE
CAN-FD networking support in networkd

### ISSUE THREAD

**Issue by rpls** [systemd/systemd#15219]
**Is your feature request related to a problem? Please describe.**
PR #9185 added support for CAN type network devices. Adding support for CAN-FD, an extended version of the standard, shoud be fairly easy. The CAN-FD standard introduces a second bitrate, which is used by the network during the "data" phase of a CAN frame. Furthermore, the maximum MTU is raised considerably from 8 to 64 bytes. Support for CAN-FD is present in the linux mainline for some time, devices and drivers exist as well.

**Describe the solution you'd like**
The easist solution would be to simply extend the configuration to allow a specification of the bitrate for the data bitrate. Example config file:
```
[Match]
Name=*can*

[CAN]
BitRate=500000
SamplePoint=80%
DataBitRate=2000000
DataSamplePoint=80%
FDMode=yes
```
The `FDMode` could also be implicitly turned on, as soon as `DataBitRate` has a non-zero value. However, a "non-ISO" mode should also be supported, so the `FDMode` could be be some form of ternary switch between `(no|yes|noniso)`. One even easier cop-out could also be to simply not support the "non-ISO" variant. I'm not even sure if there are real world use cases for it. The feature, however, is present in the kernel (and some drivers).

I already made a patch for the CAN code of networkd, if anyone is interested. But I have no idea how I could extend the configuration file parser. The code, however, could work (unless I grossly misunderstood some things, e.g. how a `FDMode` flag would be parsed). The `linux/can/netlink.h` header included in the systemd sources already has the necessary flags etc. to support CAN-FD, so its just a matter of appending another attribute and setting a flag.

```C
diff --git a/src/network/networkd-can.c b/src/network/networkd-can.c
index 18533843e3..54785dcf8e 100644
--- a/src/network/networkd-can.c
+++ b/src/network/networkd-can.c
@@ -119,6 +119,36 @@ static int link_set_can(Link *link) {
                         return log_link_error_errno(link, r, "Could not append IFLA_CAN_BITTIMING attribute: %m");
         }
 
+        if (link->network->can_data_bitrate > 0 || link->network->can_data_sample_point > 0) {
+                struct can_bittiming bt = {
+                        .bitrate = link->network->can_data_bitrate,
+                        .sample_point = link->network->can_data_sample_point,
+                };
+
+                if (link->network->can_data_bitrate > UINT32_MAX) {
+                        log_link_error(link, "data bitrate (%" PRIu64 ") too big.", link->network->can_data_bitrate);
+                        return -ERANGE;
+                }
+
+                log_link_debug(link, "Setting data bitrate = %d bit/s", bt.bitrate);
+                if (link->network->can_data_sample_point > 0)
+                        log_link_debug(link, "Setting data sample point = %d.%d%%", bt.sample_point / 10, bt.sample_point % 10);
+                else
+                        log_link_debug(link, "Using default data sample point");
+
+                r = sd_netlink_message_append_data(m, IFLA_CAN_DATA_BITTIMING, &bt, sizeof(bt));
+                if (r < 0)
+                        return log_link_error_errno(link, r, "Could not append IFLA_CAN_DATA_BITTIMING attribute: %m");
+        }
+
+        cm.mask |= CAN_CTRLMODE_FD;
+        SET_FLAG(cm.flags, CAN_CTRLMODE_FD, link->network->can_fd_mode > 0);
+        log_link_debug(link, "%sabling FD mode", link->network->can_data_bitrate > 0 ? "En" : "Dis");
+
+        cm.mask |= CAN_CTRLMODE_FD_NON_ISO;
+        SET_FLAG(cm.flags, CAN_CTRLMODE_FD_NON_ISO, link->network->can_fd_mode > 1);
+        log_link_debug(link, "%sabling FD non-ISO mode", link->network->can_fd_mode > 1 ? "En" : "Dis");
+
         if (link->network->can_restart_us > 0) {
                 char time_string[FORMAT_TIMESPAN_MAX];
                 uint64_t restart_ms;
diff --git a/src/network/networkd-network.h b/src/network/networkd-network.h
index f747ccaf10..171b922375 100644
--- a/src/network/networkd-network.h
+++ b/src/network/networkd-network.h
@@ -205,6 +205,11 @@ struct Network {
         int can_termination;
         int can_listen_only;
 
+        /* CAN-FD support */
+        uint64_t can_data_bitrate;
+        unsigned can_data_sample_point;
+        int can_fd_mode;
+
         AddressFamily ip_forward;
         bool ip_masquerade;

```

**Describe alternatives you've considered**
Another, more detailed option would be to also support a more detailed configuration, which allows a fine grained control over bitrate calculation. A CAN(-FD) bitrate setting actually consists of the settings TQ (time-quanta in nanoseconds), PROP-SEG (technically only part of CAN-FD), PHASE1-SEG, PHASE2-SEG and SJW. Each of the SEG segments and SJW are multipliers for TQ. The actual bitrate is equal to `1s / TQ*(1 + PROP + PHASE1 + PHASE2)`, the SJW is the synchronization jump width. The sample point is simply the ratio `(1 + PROP + PHASE1)/(1 + PROP + PHASE1 + PHASE2)`. If one wants to support a more fine grained variant, the configuration format has to be extended quite a bit. Maybe with some fancy parsed format? But that's probably outside of the scope of this feature request.

```
[Match]
Name=*can*

[CAN]
BitTiming=tq:prop:seg1:seg2 # Each an integer
DataBitTiming=tq:prop:seg1:seg2
FDMode=yes
```

**Comment by ssahani** [comment]
Please submit as a PR.

**Comment by rpls** [comment]
Is there any documentation on how I would go about extending the parsers? Because otherwise it would be an incomplete PR.

**Comment by rpls** [comment]
From what I gather, I have to extend the gperf files?

**Comment by ssahani** [comment]
yes it's very strate forward. Please see how other CAN variables are defined and do the same.
