### ISSUE TITLE
Support for MUD URL DHCP client option

### ISSUE THREAD

**Issue by elear** [systemd/systemd#15223]
**Is your feature request related to a problem? Please describe.**

RFC 8520 provides a means for IoT devices to express network resource requirements. We're using it for various purposes.  Both DHCP and LLDP provide a way to emit a "MUD URL".    it's an important option to support because net admins are being hit by quite a lot of new devices that they have no idea how to protect (from).

**Describe the solution you'd like**

At first glance, this looks like a pretty straightforward addition to systemd.network.xml, networkd_ipv4.c, networkd-network-gperf.gperf, netword-network.h, and rinse and repeat for IPv6.  I'm basing this on @ssahani's commit 53d3494e62e07eba183a4f9f77fbc4d4223e1f97  #5134 for other options.

**Describe alternatives you've considered**

ISC's code has a pretty elegant way of doing this, and lldpd just takes it as a byte string based on an IANA code point.  The code is also present in dhcpcd.

**Comment by ssahani** [comment]
@elear please test with https://github.com/systemd/systemd/pull/15229

**Comment by ssahani** [comment]
@elear  I have also implemented the LLDP part https://github.com/systemd/systemd/pull/15234

**Comment by elear** [comment]
I have tested this code and found no issues.

**Comment by poettering** [comment]
I guess we can close this now that the DHCP and LLDP code for this has been merged.
