### ISSUE TITLE
systemd 245 fails to complete boot sequence with kernels 3.xx

### ISSUE THREAD

**Issue by Mal36** [systemd/systemd#15225]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 >Arch Linux

**Expected behaviour you didn't see**
 > Normal boot into login prompt.

**Unexpected behaviour you saw**
 >A series of systemd failures -  Failed to apply ambient capabilities (before UID change): Invalid argument

**Steps to reproduce the problem**
 Boot a 3.xx kernel with systemd 245

**Comment by Mal36** [comment]
I have two systems (both archlinux) running 3.xx kernels. One is an armv7 machine running 3.5.7.
The other is an x86_84 machine running 3.16.75. The rest of both systems is up-to-date Arch Linux.
Both booted normally with systemd 244 and earlier.
From any version of 245 I get the same initial failure as per the log. Thereafter, it is obvious 
carnage as the initial vital systemd components have failed to start.
The 3.16.75 machine has two kernels installed and starts normally if I boot its 5.x kernel. 

Log

[   11.566696] systemd[1]: Mounting POSIX Message Queue File System...
[   11.583212] systemd[106]: dev-mqueue.mount: Failed to apply ambient capabilities (before UID change): Invalid argument
[   11.611878] systemd[1]: Mounting Kernel Debug File System...
[   11.629291] systemd[107]: sys-kernel-debug.mount: Failed to apply ambient capabilities (before UID change): Invalid argument
[   11.666579] systemd[1]: Condition check resulted in Kernel Trace File System being skipped.
[   11.704044] systemd[1]: Mounting Temporary Directory (/tmp)...
[   11.752642] systemd[111]: tmp.mount: Failed to apply ambient capabilities (before UID change): Invalid argument
[   11.797738] systemd[1]: Starting Create list of static device nodes for the current kernel...
[   11.818124] systemd[112]: kmod-static-nodes.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   11.873084] systemd[114]: modprobe@drm.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   11.892379] systemd[1]: Starting Load Kernel Module drm...
[   11.984511] systemd[1]: Starting RPC Bind...
[   12.021318] systemd[117]: rpcbind.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.059754] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[   12.095021] systemd[1]: Starting Journal Service...
[   12.133023] systemd[119]: systemd-journald.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.177274] systemd[1]: Starting Load Kernel Modules...
[   12.212546] systemd[120]: systemd-modules-load.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.255344] systemd[1]: Starting Remount Root and Kernel File Systems...
[   12.294120] systemd[122]: systemd-remount-fs.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.337228] systemd[1]: Starting Repartition Root Disk...
[   12.382557] systemd[124]: systemd-repart.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.425724] systemd[1]: Starting udev Coldplug all Devices...
[   12.472625] systemd[126]: systemd-udev-trigger.service: Failed to apply ambient capabilities (before UID change): Invalid argument
[   12.540599] systemd[1]: dev-mqueue.mount: Mount process exited, code=exited, status=218/CAPABILITIES
[   12.588840] systemd[1]: dev-mqueue.mount: Failed with result 'exit-code'.
[   12.619931] systemd[1]: Failed to mount POSIX Message Queue File System.
[   12.655238] systemd[1]: sys-kernel-debug.mount: Mount process exited, code=exited, status=218/CAPABILITIES
[   12.673745] systemd[1]: sys-kernel-debug.mount: Failed with result 'exit-code'.
[   12.690625] systemd[1]: Failed to mount Kernel Debug File System.

**Comment by Mal36** [comment]
I performed a further confirmatory test today.
1 ) I installed a fresh Arch Linux system on an x86_64 virtual machine and updated it. It was now running kernel 5.5.11-arch-1 and systemd 245.2-2. This booted normally.
2) I then installed kernel linux-lts316 from the Arch AUR (3.16.75). Booted this and got exactly the same errors as above from systemd  ie  Failed to apply ambient capabilities (before UID change): Invalid argument.

**Comment by keszybz** [comment]
We have "Linux kernel >= 3.13" in requirements in README, so the older kernel is out-of-scope.
The newer one — we need to figure out what changed. If it is not too cumbersome, I'd prefer to restore support. If too cumbersome — we'll bump the minimum version required, sorry.
But obviously the first step is to figure out the exact reason.

**Comment by Mal36** [comment]
Thanks for the quick response. I'm not really worried by the armv7 machine running 3.5.7 - I can freeze the software on it if necessary and its main use to me here was just to confirm to myself that there was a more general problem and just a problem with a my x86_64 3.16 machine. I'm somewhat surprised that no-one else has hit this problem as 3.16 is still an official LTS kernel. Anyway, I hope support can be re-instated - and look forward with interest to whatever results.

**Comment by floppym** [comment]
A quick grep of of the commit log turns up 82d832b435a0ae799011aeec75584af8188fb8db and 943800f4e7728feb2416dd57b8c296614497b94f as a likely candidates. Those were merged in https://github.com/systemd/systemd/pull/14133.

Maybe try reverting those commits to see if that makes it work on the 3.16 kernel.

Otherwise, you could try bisecting between v244 and v245.

**Comment by keur** [comment]
After a quick glance, I assume the problem is using `PR_CAP_AMBIENT`. It has relatively recent kernel requirements `4.3`. This flag was used prior to the PR, but https://github.com/systemd/systemd/pull/14133 may have created a path that you are hitting. Well check this evening after work.

**Comment by keur** [comment]
Yeah, so I'm pretty sure that is the problem. It compiles fine with those flags because they are defined in https://github.com/systemd/systemd/blob/v245/src/basic/missing_prctl.h for older kernels. My guess is we just need an #ifdef based on kernel version before doing the `prctl`s.

**Comment by keszybz** [comment]
> #ifdef based on kernel version before doing the `prctl`s.

That won't really work, since people often compile on a different kernel then the runtime one. Would it be possible to assume that the flag is unknown to the kernel if we get some error?

**Comment by keur** [comment]
> > #ifdef based on kernel version before doing the `prctl`s.
> 
> That won't really work, since people often compile on a different kernel then the runtime one. Would it be possible to assume that the flag is unknown to the kernel if we get some error?

Based on the above log, it's probably `EINVAL`. Specifically this line:

> [ 12.133023] systemd[119]: systemd-journald.service: Failed to apply ambient capabilities (before UID change): Invalid argument

**Comment by floppym** [comment]
We have a `ambient_capabilities_supported()` helper function, I guess it just isn't used for this case?

https://github.com/systemd/systemd/blob/v245/src/basic/capability-util.c#L359

**Comment by floppym** [comment]
Looks like `ambient_capabilities_supported` is called from `exec_child` to set `needs_ambient_hack`.

https://github.com/systemd/systemd/blob/v245/src/core/execute.c#L3428

This is later checked before calling `capability_ambient_set_apply`.

https://github.com/systemd/systemd/blob/v245/src/core/execute.c#L3701

**Comment by keur** [comment]
Okay, so my suspicion is that https://github.com/systemd/systemd/pull/14133 caused this by calling `capability_ambient_set_apply()` even when nothing was passed to `context->capability_ambient_set`, because that patch makes the function also drop ambient capabilities that may have been inherited unknowingly. Users on 3.x.x kernels previously would likely never set an ambient set, so `prctl` would not be called with the new flag.

Can someone with a 3.x.x kernel handy apply this diff (branched off `v245` tag)? 

```
diff --git a/src/basic/capability-util.c b/src/basic/capability-util.c
index 93237646cc..caffda62af 100644
--- a/src/basic/capability-util.c
+++ b/src/basic/capability-util.c
@@ -107,6 +107,10 @@ int capability_ambient_set_apply(uint64_t set, bool also_inherit) {
         unsigned long i;
         int r;
 
+        /* Check that we can use PR_CAP_AMBIENT or quit early. */
+        if (!ambient_capabilities_supported())
+                return 0;
+
         /* Add the capabilities to the ambient set. */
 
         if (also_inherit) {

```

**Comment by moonman** [comment]
> 
> 
> Okay, so my suspicion is that #14133 caused this by calling `capability_ambient_set_apply()` even when nothing was passed to `context->capability_ambient_set`, because that patch makes the function also drop ambient capabilities that may have been inherited unknowingly.
> 
> Can someone with a 3.x.x kernel handy try this diff (on the `v245` tag)?
> 
> ```
> diff --git a/src/basic/capability-util.c b/src/basic/capability-util.c
> index 93237646cc..caffda62af 100644
> --- a/src/basic/capability-util.c
> +++ b/src/basic/capability-util.c
> @@ -107,6 +107,10 @@ int capability_ambient_set_apply(uint64_t set, bool also_inherit) {
>          unsigned long i;
>          int r;
>  
> +        /* Check that we can use PR_CAP_AMBIENT or quit early. */
> +        if (!ambient_capabilities_supported())
> +                return 0;
> +
>          /* Add the capabilities to the ambient set. */
>  
>          if (also_inherit) {
> ```
Tested on Cubox-i with 3.14.79 and it boots up.

**Comment by Mal36** [comment]
For what it's worth, I've downloaded the Arch Linux package build stuff for systemd and built their 245.2-2 package. Running on my test x86_64 virtual machine with the Arch 3.16.75 kernel it failed as expected with the ambient capabilities problem. I then rebuilt it, with the capability-util.c patch as above and reran with 3.16.75. This booted up normally with no errors.
