### ISSUE TITLE
Improve Manual Page for moving home dirs between different systems

### ISSUE THREAD

**Issue by smartshogu** [systemd/systemd#15235]
**Is your feature request related to a problem? Please describe.**
My goal was to have one user with an encrypted home drive on different computers. Therefore I created the user with homectl as described in the manual with the options `--storage=luks` and `--image-path=/dev/disk/by-id/usb...`. After changing the PAM module ([Arch-Wiki](https://wiki.archlinux.org/index.php/Systemd-homed#Enabling_PAM_modules)) I was able to log in on the original computer and use all features of homed. With regard to the manual page 

> In this mode home directories and all data they include are nicely migratable between machines, simply by plugging the USB stick into different systems at different times.

was my expectation that a (nearly) simple change of the USB stick into another computer would lead to the same behaviour. But the following message appears

> systemd-homed[511]: User record archie.identity is not signed at all, ignoring.
> systemd-homed[511]: Failed to query quota on /home/, ignoring.
> systemd-homed[511]: Discovered new home for user archie through image /dev/disk/by-uuid/090fd8bd-5fe4-45b1-861b-56815d26c0ac.

There is an example in the manual page of how authentication can be done using YubiKey. However, there is no description of what the necessary measures are for switching between different computers. 

**Describe the solution you'd like**
However, extending the examples to include this circumstance would be very helpful for less experienced users.

**Describe alternatives you've considered**
If someone could give me a hint or link to the solution of the problem that would be super great.

**Comment by poettering** [comment]
See #15714.
