### ISSUE TITLE
Inconsistent behaviour between `systemctl poweroff` and `poweroff` (symlink to systemctl)

### ISSUE THREAD

**Issue by Ongy** [systemd/systemd#15239]
**systemd version the issue has been seen with**
> systemd 232, but verified via current code 

**Used distribution**
 > N/A (proprietary linux based OS)

**Expected behaviour you didn't see**
 > Calling the `poweroff` symlink should wait for systemd shutdown inhibitor delays to finish

**Unexpected behaviour you saw**
 > Calling `poweroff` shuts down immediatly

**Steps to reproduce the problem**
As root:
```
systemd-inhibit --what=shutdown --mode=delay /bin/bash
poweroff 
```
Commands can be in different shells.

NOTE: The behaviour is different with the `systemctl poweroff` special target handling.

**The promised pointers to code, which I think allow to report for old version :)**
The `systemctl poweroff` code ends up in logind via https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl.c#L3701 (unless called with force)
While the `poweroff` code ends up in logind only if `uid != 0` via this check https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl.c#L9355

We currently work aorund that, by replacing the symlinks with the equivalent of `systemctl ARGV[0] $@` but that isn't 100% drop in replacement, as the compat behaviour isn't invoked.

**Comment by keszybz** [comment]
I didn't look at the details here, but a general comment: `poweroff` is trying to emulate the pre-systemd interface, while `systemctl poweroff` doesn't have this limitation. There is no expectation that they'll do the same thing.

**Comment by poettering** [comment]
i guess we should document this behaviour
