### ISSUE TITLE
[Q]: Is there a way to create the bonding interface early during boot when it's managed by systemd/networkd?

### ISSUE THREAD

**Issue by morfikov** [systemd/systemd#15258]
I have a firewall script and this kind of scripts should be started with `Before=network-pre.target` in order to set firewall rules before the network related services start. But what about the bonding interface that is managed by systemd/networkd? In this case the bonding interface is created via the `systemd-networkd`  service, which has `After=network-pre.target` . My firewall (which is based on `nftables`) uses the `netdev` table, which requires specifying an interface (in this case `bond0`). Without the interface, the script is unable to add rules to the `netdev` table. 

How to make the two things work? Is there any way for systemd/networkd to create the bonding interface a little bit earlier? When I was using `ifupdown`, there was no such issue since the bonding interface was already there. And the problem I'm facing now is because of the `bonding.max_bonds=0` kernel parameter.

```
# systemd --version
systemd 245 (245.2-1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

# uname -a
Linux morfikownia 5.5.13-amd64 #52 SMP PREEMPT Wed Mar 25 17:16:39 CET 2020 x86_64 GNU/Linux
```

**Comment by zdzichu** [comment]
I guess you can create interface in initramfs (see http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html and search for `bond=`). networkd, when started, should take over the interface.

**Comment by morfikov** [comment]
I don't use `dracut` , but I was able to create the bond0 interface in initramfs/initrd using the regular `ip` command (not the one from busybox). Networkd picks up the interface:

`systemd-networkd[2714]: bond0: netdev exists, using existing without changing its parameters`

But that setup is weird... First you have to add `bonding.max_bonds=0` to the kernel command line because systemd wants it. Then you have to create and configure the bond0 interface manually in the initramfs/initrd phase so systemd/networkd can pick it up later and use when system boots...

**Comment by poettering** [comment]
THis is a bug and feature tracker, not a support forum. use the mailing list if you have support questions. Thank you for understanding.

(To keep frustration low the submission form should actually have made this very clear)
