### ISSUE TITLE
exit.target should not alias to ctrl-alt-del.target

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#1525]
I enabled  the exit.target with `systemctl --user/--global` (confirmed that a user ctrl-alt-del.target symlink is created) and mask/delete the system ctrl-alt-del.target. However it doesn't seem to do anything when I press Ctrl+Alt+Del in console or in X.

Also starting exit.target basically just kills the user systemd instance, which only leaves the login in a weird state and does not seem to be something one would like to do with ctrl-alt-del anyway.

So I guess the [Install] section is simply inappropriate and should be removed?

**Comment by poettering** [comment]
Yeah, I figure we should remove the install section from that file.
