### ISSUE TITLE
Some questions about using the new time zone list.

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#15250]
systemd version the issue has been seen with
systemd243

Time zone list has been changed from zone.tab to zone1970.tab.https://github.com/systemd/systemd/commit/ba32084f08d4dcf11430816d53f467837c8d01a5
Time zone information originally in zone.tab does not exist in zone1970.tab, such as Europe/Jersey.I wonder if the missing of some areas or city in zone1970.tab is a problem?

**Comment by poettering** [comment]
I don't think this should be a problem, after all we use this only to display a list of available options, if you pick Europe/Jersey explicitly then things continue to work as before. i.e. we do not validate with the list, we just use it for enumeration. And I think there's value in keeping this list minimal, i.e. not have too many redundant names for the same timezone. 

Or to say this differently: let's just wait if people can actually point us to a case where a timezone they need does not appear the list, and it isn't just an alias of another one. (In which case this would appear more to be a bug in tzinfo than in systemd though)...

Hope that makes sense.
