### ISSUE TITLE
libmount utab mount options get lost when we switch root, and thus x-initrd.mount vanishes during initrd transitions

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#15266]
x-initrd.mount (for instance) is used for setting mounts up in initrd. This "application" option is recorded in "utab" so applications (such as systemd) can figure out later which application options have been used for a given mount.

However	in initrd, mount points described in fstab are usually mounted under /sysroot, therefore mount paths in utab are usually prefixed with "/sysroot". A typical entry in utab looks like:

`SRC=/dev/vdb1 TARGET=/sysroot/mnt ROOT=/ OPTS=x-initrd.mount,_netdev`

The problem appears after swithing to the main system: PID1 tries to retrieve the mount options (via mnt_fs_get_options()) for /mnt (not /sysroot/mnt) but nothing is found since the relevant entry has `TARGET=/sysroot/mnt`.

The previous example is based on x-initrd.mount but the issue can also happen with any other x-* options.

**Comment by poettering** [comment]
Hmm, I wonder what the right approach here... somehow libmount needs to either convert utab or better automatically handle this better.

Maybe the correct approach would be if libmount only ever uses the numeric mount ID (rather than the mount point path) for identifying mounts? that way things should remain robust regardless how many times we switch root.

@karelzak any chance you could rework libmount like that? i.e. replace the utab key with the numeric mount ID?

**Comment by karelzak** [comment]
I'll try it. @poettering suggested to use  /proc/self/fdinfo/<mountpoint-fd> to get the ID -- it seems elegant way how to bypass the current mount(2) stupidity (it does not provide any feedback after success). In the future with the new mount API we can get the ID from fsmount() FD.

**Comment by karelzak** [comment]
@poettering has suggested mount ID to join utab and mountinfo. The question is how usable mount ID is as it seems kernel is cycling the IDs ;-(

Is there any possibility to detect that the current root is in /sysroot directory? If yes, we can improve the way how libmount search in the utab.

**Comment by fbuihuu** [comment]
@poettering in the meantime maybe we could workaround this issue with something like https://github.com/fbuihuu/systemd/commit/303c959147e07b2b3865228dda73e62033983450 ?

**Comment by fbuihuu** [comment]
> @poettering in the meantime maybe we could workaround this issue with something like [fbuihuu@303c959](https://github.com/fbuihuu/systemd/commit/303c959147e07b2b3865228dda73e62033983450) ?

Ah but wait, I initially thought that the prob was the lack of notification to libmount when we're switching root but apparently `mnt_update_set_fs(upd, MS_MOVE, NULL, fs)` is not doing the right thing: it only updates the entry in utab for the specified path but doesn't consider the submounts at all.

@karelzak could you confirm ?

**Comment by fbuihuu** [comment]
@karelzak this basic patch seems to do the trick: https://gist.github.com/fbuihuu/186769abcd852f24bc20ef8c38cf026b. However this is probably not enough because utab doesn't seem to store canonicalized paths and the patch assumes that it does.

**Comment by karelzak** [comment]
@poettering yes, mnt_update_set_fs( MS_MOVE ) is designed to update the specified target (one emtry) and nothing else.

**Comment by karelzak** [comment]
> @karelzak this basic patch seems to do the trick: https://gist.github.com/fbuihuu/186769abcd852f24bc20ef8c38cf026b. However this is probably not enough because utab doesn't seem to store canonicalized paths and the patch assumes that it does.

mount/umount cannonicalizes all paths (in mnt_context_prepare_target() it calls mnt_resolve_path()), this is probably no problem

I guess your improvement for MS_MOVE makes sense, can you create regular PR for util-linux with it?

**Comment by fbuihuu** [comment]
> mount/umount cannonicalizes all paths (in mnt_context_prepare_target() it calls mnt_resolve_path()), this is probably no problem

The problem here is that PID1 doesn't rely on neither mount(8) (the binary) nor `mnt_context_mount()` in order to move `/sysroot` to `/`. Instead it does its own calls to `mount(2)` which by pass libmount completely and therefore makes `/run/mount/utab` outdated.

That's the reason why I proposed in https://github.com/fbuihuu/systemd/commit/303c959147e07b2b3865228dda73e62033983450 to notify libmount once the switch root happened. But this is done by calling `mnt_update_set_fs()` and `mnt_update_table()` and none of these functions seems to canonicalize the paths. 

Maybe I'm missing something in this code, could you check it please ?

> I guess your improvement for MS_MOVE makes sense, can you create regular PR for util-linux with it?

Ok I will. If you don't mind I'll open a bug before.

**Comment by fbuihuu** [comment]
> I guess your improvement for MS_MOVE makes sense, can you create regular PR for util-linux with it?

@karelzak. PR submitted: https://github.com/util-linux/util-linux/pull/1660

**Comment by fbuihuu** [comment]
@poettering I've prepared a patch to make PID1 inform libmount about initrd transition: https://github.com/systemd/systemd/pull/23168. PTAL

**Comment by poettering** [comment]
At this point this is mostly a tracking issue for https://github.com/util-linux/util-linux/issues/1765

i.e. this will eventually be fixed in util-linux, no need to fix this on systemd's side.
