### ISSUE TITLE
network: tc: add sch_ets qdisc

### ISSUE THREAD

**Issue by k0ste** [systemd/systemd#15264]
In Linux 5.6 https://github.com/torvalds/linux/commit/dcc68b4d8084e1ac9af0d4022d6b1aff6a139a33  sch_ets was added - [802.1Qaz – Enhanced Transmission Selection](https://1.ieee802.org/dcb/802-1qaz/).

**Comment by k0ste** [comment]
@yuwata

**Comment by ssahani** [comment]
```tc qdisc add dev eth0 root handle 1: ets bands 8 priomap 7 6 5 4 3
       2 1 0
Unknown qdisc "ets", hence option "bands" is unparsable
cd: too many arguments

Apparently this example not working http://man7.org/linux/man-pages/man8/tc-ets.8.html
@k0ste do you have a working example on `tc`
```

**Comment by k0ste** [comment]
@ssahani, I was try with Linux 5.6.2 and iproute 5.6.

![image](https://user-images.githubusercontent.com/7759548/78633618-41c03b00-78cc-11ea-9a18-b02651c3cf89.png)

**Comment by yuwata** [comment]
Now I am working on this.
