### ISSUE TITLE
Homectl list does not refresh with udev events if home area not already registered

### ISSUE THREAD

**Issue by matthewwardrop** [systemd/systemd#15287]
**systemd version the issue has been seen with**
> 245.2-2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Home areas on external usb drives should appear "immediately" as "unfixated" in the output of `homectl list`.

**Unexpected behaviour you saw**
 > Home areas on external usb drives do not appear in the `homectl list` output until `systemd-homed` is restarted.

**Steps to reproduce the problem**
1. Create external home area (I have been using LUKS encrypted partitions if that makes a difference)
2. Unregister home area on the same machine, or try it on a properly provisioned second machine, and observe that hotplugged home areas do not appear until homed is restarted.

**Comment by poettering** [comment]
Fix pending in #15931
