### ISSUE TITLE
Add support to remove DefaultPVID in network-files

### ISSUE THREAD

**Issue by prauscher** [systemd/systemd#15291]
**Is your feature request related to a problem? Please describe.**
When realizing a VM-Host, which would have a bridge shared with the VMs and a physical interface, but the VM-Host should not be reachable on this bridge for security reasons, systemd-networkd can only add new VIDs to a bridge, never remove the DefaultPVID. The problem occurs when trying to use systemd-networkd to achieve https://vincent.bernat.ch/en/blog/2017-linux-bridge-isolation

**Describe the solution you'd like**
BridgeVLAN-Blocks in network-files should include an option to remove VIDs from the port. That would allow to create a bridge with `DefaultPVID=1` and removing the VID 1 only from this bridge-port, just like `bridge vlan del vid 1 dev br0 self` would do.

**Describe alternatives you've considered**
You could set `DefaultPVID=none` and configure all networks which should be part of the bridge manually. This however is errorprone and at least does not work properly for tun-devices created by libvirt (vnet*).

**Comment by prauscher** [comment]
Just in case: I'm running systemd 241 on Debian, but I could not find any hint for such option using google and the manpages explicitly for newer versions.

**Comment by prauscher** [comment]
PS: This issue is somewhat related to #5716, as the solution described in #5716 only works in this specific scenario, this approach would have been an alternative solution to #5716.

**Comment by sr105-tm** [comment]
Instead of forcing the config to detail all VLANs that should be removed, perhaps systemd could remove any vlans not part of the current configuration. I have a similar issue. I start up with DefaultPVID=0. I then need to be able to change VLAN membership at runtime. I would expect restarting networkd to do this, but it only ADDs new VLANs without removing old VLANs no longer part of the current configuration. If this should be a separate issue, I'll create a new issue, but it seems the same to me.

```
root@tspv1rb:~# bridge vlan
port	vlan ids
modem	 1 PVID Egress Untagged
	 3893

enet2-data	 3893 PVID Egress Untagged

enet1-mgmt	 1 PVID Egress Untagged

br0	 1 PVID Egress Untagged

root@tspv1rb:~# cd /etc/systemd/network
# 
# Change 3893 to 3897
# 
root@tspv1rb:/etc/systemd/network# vi modem.network 
root@tspv1rb:/etc/systemd/network# systemctl restart systemd-networkd
root@tspv1rb:/etc/systemd/network# bridge vlan
port	vlan ids
modem	 1 PVID Egress Untagged
	 3893                                                    #  I expected this VLAN to be removed by systemd
	 3897

enet2-data	 3893 PVID Egress Untagged

enet1-mgmt	 1 PVID Egress Untagged

br0	 1 PVID Egress Untagged

```

**Comment by yuwata** [comment]
Waiting in #29987.
