### ISSUE TITLE
writing entprypoint log when starting systemd in docker

### ISSUE THREAD

**Issue by rightblank** [systemd/systemd#15296]
**systemd version the issue has been seen with**
> root@40dc0dfb3034:/# systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > **container**
root@40dc0dfb3034:/# uname -a
Linux 40dc0dfb3034 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**host**
~# uname -a
Linux eldamar 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > the entrypoint shell script could write the log to **docker logs**

**Unexpected behaviour you saw**
 > the output of docker logs contains the systemd log
~# docker logs 40d
> Welcome to Ubuntu 18.04.4 LTS!
>
>[  OK  ] Created slice User and Session Slice.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Set up automount Arbitrary Executab…rmats File System Automount Point.
[  OK  ] Reached target Remote File Systems.

**Steps to reproduce the problem**
> 
- Prepare the files before build the image.
```
~# cat Dockerfile
FROM ubuntu:18.04
RUN apt update -y && apt install -y systemd && \
    apt clean && apt autoremove
ADD entry.sh /root
ENTRYPOINT [ "/sbin/init" ]
CMD [ "/root/entry.sh" ]

~# cat entry.sh
#!/bin/bash
echo "Something"
# do the job
echo "done"
```
- build the image
```
chmod +x entry.sh
docker build . -t ubuntu:systemd
```
- run the container and check the logs
```
docker run -td --privileged ubuntu:systemd
40dc0dfb303441a961f68d6c7908ce9f6f0ad269ba8a7111a3c887f96fd113f7
~# docker logs 40d

Welcome to Ubuntu 18.04.4 LTS!
...
```

**Comment by poettering** [comment]
i am sorry, what is this issue about? what do you want us to do?

**Comment by rightblank** [comment]
I wanted the entrypoint.sh script of the docker container can `echo` logs to console so that `docker logs` command can show the output of the `echo`. Later I found that it would be better to convert the entrypoint.sh into a systemd service, in this case `echo "XXXX" > /dev/console` would get the result I want, that is `XXXX` shows up in `docker logs`'s output.
