### ISSUE TITLE
IPv6 and RouteMetric

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#15295]
**systemd version the issue has been seen with**
> systemd 245 (245.3-2-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > Routing table entry with only the correct RouteMetric set

**Unexpected behaviour you saw**
 > Dupplicated routing table entry once with metric 1024 and once with the provided one.

**Steps to reproduce the problem**
Use a network unit like:
```
[Match]
Name=wlp2s0

[Network]
DHCPServer=no
DHCP=yes
DNSOverTLS=opportunistic
DNSSEC=allow-downgrade
DNS=2606:4700:4700::1111 2001:4860:4860::8888 1.1.1.1 8.8.8.8
DNSDefaultRoute=yes
IPv6AcceptRA=yes
IPv6DuplicateAddressDetection=1
IPv6PrivacyExtensions=kernel
LLMNR=no
MulticastDNS=no

[DHCP]
Anonymize=yes
UseDNS=no
UseDomains=route
UseHostname=no
RouteMetric=2000
```
Than the routing table looks like:
```
Destination                    Next Hop                   Flag Met Ref Use If
::/0                           fe80::feec:daff:fe1c:76b2  UGe  1024 6     0 enp0s25
::/0                           fe80::feec:daff:fe1c:76b2  UGe  1024 5     0 wlp2s0
::/0                           fe80::feec:daff:fe1c:76b2  UGe  2000 1     0 wlp2s0
```
obviously the 2nd line should not be present.

Note: The documentation at https://www.freedesktop.org/software/systemd/man/systemd.network.html also only lists the option `RouteMetric` for the section `DHCPv4` instead of also for `DHCP`.

**Comment by yuwata** [comment]
If possible, could you test #15996?
