### ISSUE TITLE
IPv6 SLAAC address lifetimes not reset on RA when other static addresses are defined.

### ISSUE THREAD

**Issue by mmonaco** [systemd/systemd#15303]
v245.3 on Archlinux

The hosts on my network have an interface configuration such as:
```
[Network]
DHCP=no
Address=fd00::42/56
Address=192.168.0.42/24
IPv6Token=::42
IPv6PrivacyExtensions=yes
IPv6AcceptRA=yes

[Route]
Gateway=fd00::1
Metric=16

[Route]
Gateway=192.168.0.1
Metric=16
```

This results in addresses such as:
```
    inet  192.168.0.42/24 brd 192.168.0.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 2601:XXXX::YYYY/64 scope global temporary dynamic
       valid_lft 850sec preferred_lft 850sec
    inet6 2601:XXXX::27/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 850sec preferred_lft 850sec
    inet6 fd00::42/56 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ZZZZ/64 scope link
       valid_lft forever preferred_lft forever
```

With some attempt at redacting my info, `XXXX` is in my ISPs public range, `YYYY` is a random temp address, and `ZZZZ` is the link-local address based on my MAC. (Aside: TBH I'm not sure why I'm not getting a temp address for the static `fd00` range too).

When new RAs are received (every minute or so) I expect the `valid_lft` and `preferred_lft` to be reset back to the values in the RA (I've  played with 1h, 2h, 6h, etc). This does not happen though and the lifetimes drop down to 0 leaving the interface without any public IPv6 addresses until a restart of `systemd-networkd`. Temporarily commenting out the static v6 address works around the problem.

**Comment by mmonaco** [comment]
https://tools.ietf.org/html/rfc4862#section-5.5.3 item `e)` is where this is defined.

**Comment by ssahani** [comment]
> https://tools.ietf.org/html/rfc4862#section-5.5.3 item `e)` is where this is defined.

That's implemented here https://github.com/systemd/systemd/blob/master/src/network/networkd-ndisc.c#L393

**Comment by mmonaco** [comment]
My internal fd00::/56 network was sending RA's with /64. I believe this was causing `networkd` to choke and the interface went into the failed state. So the lifetimes issue was just a symptom.

Note that my OpenWRT routers handle this fine. The static address is a /56 while slaac and temp addresses are all /64.

I don't have a good reason to use /56 though so I switched in the meantime. I'll close for now....

**Comment by mmonaco** [comment]
Hrm, I'll dig a little more but one static+slaac issue I'm seeing now is that the lifetime of the static address is being dropped from forever to the RA's lifetime.
