### ISSUE TITLE
resolved: reverse IPv6 lookups with DNSSEC validation are slow

### ISSUE THREAD

**Issue by huupoke** [systemd/systemd#15317]
**systemd version the issue has been seen with**
> 245.4-1

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > The lookup takes short time

**Unexpected behaviour you saw**
 > The lookup takes very long time

**Steps to reproduce the problem**
```
$ systemd-resolve 2606:4700:4700::1001
2606:4700:4700::1001: one.one.one.one          -- link: eno1

-- Information acquired via protocol DNS in 8.2949s.
-- Data is authenticated: no

$ systemd-resolve 1.0.0.1
1.0.0.1: one.one.one.one                       -- link: eno1

-- Information acquired via protocol DNS in 1.1647s.
-- Data is authenticated: no

$ systemd-resolve 2600:1417:3f:2af::b33
2600:1417:3f:2af::b33: g2600-1417-003f-02af-0000-0000-0000-0b33.deploy.static.akamaitechnologies.com -- link: eno1

-- Information acquired via protocol DNS in 1min 41.0551s.
-- Data is authenticated: no

$ systemd-resolve 23.15.104.32
23.15.104.32: a23-15-104-32.deploy.static.akamaitechnologies.com -- link: eno1

-- Information acquired via protocol DNS in 1.3804s.
-- Data is authenticated: no

```

I'm running in stub resolver mode.
My custom config at `/etc/systemd/resolved.conf.d/custom.conf`:
```
[Resolve]
DNS=1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
Domains=~.
DNSSEC=true
DNSOverTLS=yes
```

**Comment by poettering** [comment]
Lemme guess, if you turn off DNSSEC all is quick?

Most likely there's ome DNS server in the mix which takes us too long to fully probe and validate all records in the chain with...

**Comment by huupoke12** [comment]
Yes, it's much quicker after disabling DNSSEC.

**Comment by keszybz** [comment]
I don't think there's anything to fix. We cache everything that should be cached and if there's a slow upstream server there isn't much we can do. Any stub resolver will have the same issue…
