### ISSUE TITLE
start with java -jar  killed by systemd,Manual startup is ok. 

### ISSUE THREAD

**Issue by superfenv** [systemd/systemd#15322]
linux : contos 7.2
java: open-jdk-1.8.0

command :  /opt/rocketmq/rocketmq_exporter/start.sh
 java -jar $base_dir/rocketmq_exporter/rocketmq-exporter-0.0.1-SNAPSHOT.jar   > /dev/null 2>&1

systemd unit:

[Unit]
Description=Rocketmq exporter
After=network.target

[Service]
User=prometheus

Type=forking
ExecStart=/opt/rocketmq/rocketmq_exporter/start.sh -d /opt/rocketmq -p 9121 -l 9876 -i rocketmq_kafka-sit-az1-1 -n sit_rocketmq_common -t '"env=sit","name=rocketmq","category=middleware","alias=sit_rocketmq_common"' -s http://192.168.64.xxx:8500/v1/agent/service
ExecStop=/opt/rocketmq/rocketmq_exporter/stop.sh  -p 9121 -l 9876 -i rocketmq_kafka-sit-az1-1 -s http://192.168.64.xxx:8500/v1/agent/service
SuccessExitStatus=1 143
MemoryLimit=200M
PrivateTmp=true

[Install]
WantedBy=multi-user.target

errors:

+ java -jar /opt/rocketmq/rocketmq_exporter/rocketmq-exporter-0.0.1-SNAPSHOT.jar
start.sh[3675]: /opt/rocketmq/rocketmq_exporter/start.sh: line 41:  3692 Killed                  java -jar $base_dir/rocketmq_exporter/rocketmq-exporter-0.0.1-xxx.jar

**Comment by poettering** [comment]
This is not a support forum, but a bug and feature track The submission form should have made that clear, to keep frustration at a minimum. Please contact the appropriate support forum for your project or distro instead. 

Thank you for understanding,
