### ISSUE TITLE
systemd-backlight@backlight:acpi_video0.service No such device

### ISSUE THREAD

**Issue by davispuh** [systemd/systemd#15329]
**systemd version the issue has been seen with**
245

**Used distribution**
ArchLinux

**Expected behaviour you didn't see**
To not have this service

**Unexpected behaviour you saw**
Service tries to start

On my Lenovo ThinkPad E585 there is no such `acpi_video0` but only `amdgpu_bl0`
```
$ ls -l /sys/class/backlight/
total 0
lrwxrwxrwx 1 root root 0 apr  3 23:46 amdgpu_bl0 -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.0/backlight/amdgpu_bl0/
```
So why there is such service?

Journal shows:
```
apr 03 23:46:06 localhost systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:acpi_video0...
apr 03 23:46:06 localhost systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
apr 03 23:46:06 localhost systemd-backlight[748]: Failed to get backlight or LED device 'backlight:acpi_video0': No such device
apr 03 23:46:06 localhost systemd[1]: systemd-backlight@backlight:acpi_video0.service: Main process exited, code=exited, status>
apr 03 23:46:06 localhost systemd[1]: systemd-backlight@backlight:acpi_video0.service: Failed with result 'exit-code'.
apr 03 23:46:06 localhost systemd[1]: Failed to start Load/Save Screen Backlight Brightness of backlight:acpi_video0.
apr 03 23:46:06 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-backlight@backli>
apr 03 23:46:06 localhost systemd[1]: Started Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
apr 03 23:46:06 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-backlight@backli>
```

**Comment by poettering** [comment]
My educated guess: the ACPI device shows up early and then disappears again when your graphics driver is loaded. Turn on debug logging (debug on the kernel cmdline) and check the boot logs...

I am not entirely sure what the canonical solution to this issue is, but iirc this is something the kernel acpi/laptop driver people care about and will fix fo you.

**Comment by poettering** [comment]
Anyway, let's close this here, I don#t think we can do anything about this here. We can only act on what the kernel tells us. And if the kernel create a device first and then quickly removes it again, we will have trouble accessing it, since this is all asynchronous. 

Please contact your driver maintainers upstream, maybe they can do something about this so that the device doesn't appear just in order to immediatelly disappear again.

Hope this makes sense

**Comment by greenfoo** [comment]
Hi. Looking at the kernel logs confirms your theory: it first creates a device ("acpi_video0") which is then removed to insert a new one on its place ("amdgpu_bl0").

**However**, it looks like "systemd" receives the three events (1. "acpi_video0 is created"; 2. "acpi_video0 is removed"; 3. "amdgpu_bl0 is created") as can be seen on the next lines extracted (in order) from journactl:
```
Apr 26 14:03:45 x395 systemd[1]: sys-devices-pci0000:00-0000:00:08.1-0000:05:00.0-backlight-acpi_video0.device: Changed dead -> plugged
Apr 26 14:03:45 x395 systemd[1]: sys-devices-pci0000:00-0000:00:08.1-0000:05:00.0-backlight-acpi_video0.device: Changed plugged -> dead
Apr 26 14:03:45 x395 systemd[1]: sys-devices-pci0000:00-0000:00:08.1-0000:05:00.0-backlight-amdgpu_bl0.device: Changed dead -> plugged
Apr 26 14:03:45 x395 systemd[1]: systemd-backlight@backlight:acpi_video0.service: Changed dead -> start
Apr 26 14:03:45 x395 systemd[1]: systemd-backlight@backlight:amdgpu_bl0.service: Changed dead -> start
Apr 26 14:03:45 x395 systemd[1]: systemd-backlight@backlight:acpi_video0.service: Changed start -> failed
Apr 26 14:03:45 x395 systemd[1]: systemd-backlight@backlight:amdgpu_bl0.service: Changed start -> exited
```
So... even if systemd *knows* that "acpi_video0" was "unplugged", it still tries to start the associated service later, which then obviously fails when it cannot find the device.

Again, I know nothing about how systemd works but, would it make sense to hook the "unplugged" event to a function that uninstalls/destroys the service before it is started? (I guess there could still be race conditions, but at least the probability of a faulty service would be minimized, right?)

**Comment by davispuh** [comment]
By the way I submitted it here https://bugzilla.kernel.org/show_bug.cgi?id=207197

**Comment by michal-grabarczyk** [comment]
I support @davispuh that when there is an event of unregistering a device (acpi_video0) that is obtained by systemd - systemd could still not trigger the `systemd-backlight@backlight:acpi_video0.service` that is doomed to fail

**Comment by filip-hejsek** [comment]
I have tried to solve this problem by masking `systemd-backlight@backlight:acpi_video0.service`, and for some reason it makes `systemd-backlight@backlight:amdgpu_bl0.service` fail. To make it worse, it fails only when the `debug` kernel option is not enabled. Does anyone have any idea why this could happen?
