### ISSUE TITLE
networkd: IPv6: Add option to unconditionally send IA_PD even when upstream RA does not contain M or O flags

### ISSUE THREAD

**Issue by pbasista** [systemd/systemd#15339]
**Is your feature request related to a problem? Please describe.**

*systemd 245 (245.4-2-arch)*:
When an upstream router sends an IPv6 [RA](https://tools.ietf.org/html/rfc4861#section-4.2) that does not include any flag (i.e. no M flag and no O flag), then networkd does not send any [IA_PD](https://tools.ietf.org/html/rfc3633#section-6) requests. However, the upstream router may support prefix delegation despite the fact that its RA messages do not include any flags.

It is perhaps non-intuitive, but it seems to be compliant with section [4.2](https://tools.ietf.org/html/rfc7084#section-4.2) of RFC 7084. In particular:

>    WPD-4:  By default, the IPv6 CE router MUST initiate DHCPv6 prefix
           delegation when either the M or O flags are set to 1 in a
           received Router Advertisement (RA) message.  Behavior of the
           CE router to use DHCPv6 prefix delegation when the CE router
           has not received any RA or received an RA with the M and the
           O bits set to zero is out of scope for this document.

The last part says that the behavior to use DHCPv6 prefix delegation when RA contains no flags or when it has not been received is out of scope of this document. If I understand correctly, it means that sending an IA_PD in such a case is allowed. However, networkd would not do it unless RA is present and contains the M flag or unless it does not contain the M flag but contains the O flag and the `ForceDHCPv6PDOtherInformation` option is true.

**Describe the solution you'd like**

I think that it would make sense for systemd to have an option to unconditionally send the IA_PD messages even when there are no flags in the RA and also when there is no RA.

The reason is that otherwise the prefix delegation via networkd could not work at all in networks whose routers either do not send RA or send them without any flags. From what I have read, such a network configuration seems to be valid.

**Describe alternatives you've considered**

An alternative is to use a different software for prefix delegation in such a case. `dhcpcd`, for instance, can send IA_PD even when there is no RA.

**Comment by ssahani** [comment]
```
[DHCPv6]
WithoutRA=
```

**Comment by pbasista** [comment]
In addition, it seems to me that requesting a non-temporary address ([IA_NA](https://tools.ietf.org/html/rfc8415#section-21.4)) via DHCPv6 should also be possible even without router advertisements.

**Comment by ssahani** [comment]
There's nothing to prohibit DHCPv6 to run always; it is just that it SHOULD be run if M or O bits are set.  So we need to add an another option .

**Comment by ssahani** [comment]
Here is it . https://github.com/systemd/systemd/pull/15363
