### ISSUE TITLE
Improve Manual Page for pam_systemd_home to better explain usage of the `suspend=` parameter

### ISSUE THREAD

**Issue by julie-is-late** [systemd/systemd#15343]
**Is your feature request related to a problem? Please describe.**
Recently went through the effort to convert my full disk encrypted setup to a luks2 file loopback based systemd-homed user. After reading through the [pam_systemd_home man page](https://www.freedesktop.org/software/systemd/man/pam_systemd_home.html), as well as following the recommendations from the [arch wiki page](https://wiki.archlinux.org/index.php/Systemd-homed), I ended up with a modified pam config that looks like: 

/etc/pam.d/nss-auth:
-------------
```
#%PAM-1.0

auth      sufficient  pam_unix.so try_first_pass nullok
auth      sufficient  pam_systemd_home.so
auth      required    pam_deny.so

account   sufficient  pam_unix.so
account   sufficient  pam_systemd_home.so
account   required    pam_deny.so

password  sufficient  pam_unix.so try_first_pass nullok sha512 shadow
password  sufficient  pam_systemd_home.so
password  required    pam_deny.so
```
/etc/pam.d/system-auth:
-------------
```
#%PAM-1.0

auth      substack  nss-auth
auth      optional  pam_permit.so
auth      required  pam_env.so

account   substack  nss-auth
account   optional  pam_permit.so
account   required  pam_time.so

password  substack  nss-auth
password  optional  pam_permit.so

session   required  pam_limits.so
session   optional  pam_systemd_home.so
session   required  pam_unix.so
session   optional  pam_permit.so
```

However despite now allowing logins, I was still a little surprised to find that upon `systemctl suspend` and resume, even before re authenticating my user's homedir was not locked and was accessible via a second user despite numerous mentions that it was supported for luks2 backed storage. 

**Describe the solution you'd like**

Regardless, after reading up more on pam_systemd_home.so's `suspend=` parameter I am still confused about the usage of it. Is it ready for actual use? Will it require unlocking from a separate console or will I be able re-authenticate with the GDM lock screen? Just seems like there could be a little more info on the usage of both this option and the pam module as a whole.

**Comment by poettering** [comment]
I extended the documentation on this a bit in #15373. ptal. hope this clears up things enough?

**Comment by pltrz** [comment]
> I extended the documentation on this a bit in #15373. ptal. hope this clears up things enough?

thanks so much! this affects me as well, so I will give it a try
