### ISSUE TITLE
former patch to 60-keyboard.hwdb breaks keyboard

### ISSUE THREAD

**Issue by chri2** [systemd/systemd#15360]
**actual systemd since pull request #11516 **

**Used distribution**
PureOS Amber (based on Debian Buster)

**Expected behaviour you didn't see**
Pressing the  `<>|`-key on Librem13v4 with german keyboard should yield keycode 94.

**Unexpected behaviour you saw**
Instead pressing  `<>|`-key produces keycode 51.

**Steps to reproduce the problem**
Added a description with steps to reproduce to pull request #11516.

A Librem13v4 with german keyboard is needed to reproduce.

**Comment by poettering** [comment]
So the en and the de kbd are not distuingishable for us, are they?

We can drop the patch, but I doubt anyone will be helped by that?

what else can we do?

**Comment by chri2** [comment]
To make sure the de and en keyboards cannot be distinguished we'd need the data of someone using a Librem13v4 with en keyboard and maybe creativity to distinguish in a different way than using the data of evemu-describe.

To drop the patch would be the technically right way from my point of view: The keyboard problem is a firmware problem of the en keyboard and should be fixed at the root cause. A workaround for that problem is known (and found its way in good intentions into systemd).

To fix a broken keyboard type with a software workaround and thereby break working keyboards seems to be wrong.

But I agree: The best possible solution in systemd would be to have a workaround that only affects the keyboards that need the patch.

The only enhancement so far I could think about is to implement something that can take in account the chosen keyboard config: if the user chose an english keyboard layout there is a strong probability that the keyboard is an english keyboard. But this is not really cool, since there might be users with a german keyboard switching to english layout for some reason.

I'd say we'd need to fix the problem of the en keyboard in a workaround during setup that lets the users decide whether they'd need the workaround or not including explanation to make them aware of the possibly arising problems. But that would be outside systemd I guess.

**Comment by agx** [comment]
related issue on the pureos tracker: https://tracker.pureos.net/T888

**Comment by poettering** [comment]
can you prepare a pr dropping the entry again?

**Comment by chri2** [comment]
I'll try...

**Comment by poettering** [comment]
Any update?

**Comment by chri2** [comment]
Sorry, lost my reminder somewhere. Will do.

**Comment by chri2** [comment]
https://github.com/systemd/systemd/pull/18552

**Comment by poettering** [comment]
#18552 was merged, closing.
