### ISSUE TITLE
All non-seat0 input devices leak into VT if no display server on seat0

### ISSUE THREAD

**Issue by n3rdopolis** [systemd/systemd#15387]
**systemd version the issue has been seen with**
> 241 (with Debian Buster)

**Operating System**
 > Debian Buster

**Unexpected behaviour you saw**
 > When there is a display server running on one seat, and a console session active on seat0, upon entering keyboard input into the keyboard attached to the non-seat0 seat, all keyboard input appears on the TTY as well.

I am not sure if there is an interface for the kernel to exclude certain keyboards from the VTs or not

**Steps to reproduce the problem**
- You need two have two seats capable of running display servers. Which means two video cards. (Real hardware I use DisplayLink v2 devices) Thankfully QEMU can emulate this pretty well, if it's newish, and has SDL compiled in. (I did have to build my own QEMU, but I am stuck on Ubuntu 18.04 as my main box)

- I observe this on QEMU _and_ real hardware. This is not a problem with QEMU.
The problem resides with when there is no display server running on seat0, the console gets input from all keyboards, regardless of their seat assignments.

1. Start up the instance of QEMU, attaching video cards, and setting up the QEMU seat devices like this. This gives you two seats.
qemu-system-x86_64 -smp 2 -m 1024 -cdrom ~/SomeLiveDistro.iso -vga virtio -enable-kvm -display sdl -device pci-bridge-seat,chassis_nr=2,id=head.2 -device virtio-gpu-pci,bus=head.2,addr=02.0,id=video.2 -device virtio-keyboard-pci,bus=head.2,display=video.2 -device virtio-tablet-pci,bus=head.2,display=video.2`

With QEMU's multiseat support, Keyboard and mouse input in the first window go to seat0, and keyboard and mouse window in the second window go to the second seat. If _both_ seats have display servers running on them, you can verify that this works correctly, 

2. Once booted, you can get  `weston` to start on the second seat of the VM like this:
`systemd-run -p User=$LOGNAME -p WorkingDirectory=~ --setenv=XDG_SEAT=seat-pci-pci-0000_00_04_0 -p PAMName=login weston`
and then you can open up a weston-terminal

3. Switch to a TTY, and then activate the window for the second seat and start typing in the weston-terminal. Observe the same keystrokes appearing in the TTY as a part of seat0 .

4. Activate the window for seat0 and start typing in the TTY. Observe that the text input there does not appear in the weston-terminal running in the non-seat0 seat.

**Comment by poettering** [comment]
hmm i wonder what the proper protocol is to keep the devices away from the kernel input processing. @dvdhrm you are well versed in this stuff, any idea?

maybe weston is simply not calling the right ioctls to continously detach the input devices from the kernel's own processing?

**Comment by n3rdopolis** [comment]
I found that something like `evtest --grab /dev/input/eventX` can keep the input away from the TTY, but _everything else_ as well, as it calls EVIOCGRAB .

So if Weston was to hypothetically call EVIOCGRAB I assume there would probably be a need to make sure Weston (and other display servers) correctly releases the grab during a session switch, and if for some reason the server hangs before it does, that that could be a problem probably...  

(and that could break other things that do custom things with input that I can't think of right now)

Correct me if I am wrong here, because I very well could be...

I threw a printk in kbd_connect and kbd_disconnect in drivers/tty/vt/keyboard.c to see what happens, and it seems it doesn't get called during TTY switch, only when it actually finds new hardware, so it would be my guess that the VT console gets keyboard input all the time, I guess only ignoring it in KD_GRAPHICS. 
And none of the other IOCTLs in drivers/input/evdev.c look relevant to me. Maybe something has to be added to the kernel. IDK.

**Comment by dvdhrm** [comment]
Yeah, I don't think the kernel has any filter there. Easiest way around is to not run any gettys. Just disable the autogetty feature in logind, for instance.

**Comment by jdebp** [comment]
Aren't you using `KDSKBMUTE` yet?  Arthur Taylor mentioned it in 2013.  See https://unix.stackexchange.com/a/178807/5132 .

**Comment by n3rdopolis** [comment]
looks like `KDSKBMUTE` is for the /dev/ttyX devices, and not /dev/input/eventX devices.

Which isn't really what to look for in a multiseat config. You have two video cards, running a separate display server each, and the input devices are grouped per-seat.

Problem is, if your main device on seat0 is showing a TTY console, the kernel mode TTY console isn't obeying seats. `KDSKBMUTE` would only be for if a display server is active on seat0.
(where now you can have a display server active on another seat, but the kernel mode VT is active)

**Comment by n3rdopolis** [comment]
It would be my assumption from here a report in bugzilla.kernel.org is needed? Obviously I am not sure the best way to handle it. ...or maybe the TTY subsystem needs to be tweaked so that `EVIOCREVOKE` also  works for it too? IDK

**Comment by n3rdopolis** [comment]
For documentation purposes, I opened up https://bugzilla.kernel.org/show_bug.cgi?id=208239 but forgot to report it back here

**Comment by n3rdopolis** [comment]
This is probably unfixable in the kernel or systemd unless VTs are disabled
