### ISSUE TITLE
systemd-sysv-install does not trigger for service aliases

### ISSUE THREAD

**Issue by ottok** [systemd/systemd#15394]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Debian unstable

## Problem

Currently in https://github.com/systemd/systemd/blob/4c39820562e562b98c2fd269ad3a4f84949d6059/src/systemctl/systemctl.c#L6680 we check if there is a sysvinit service with the identical name when a service is enabled or disabled, and the state is synced to sysvinit.

Example:
```
# systemctl enable mysql  
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mysql
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service -> /lib/systemd/system/mariadb.service.

--> both init and systemd service files active

# systemctl disable mysql
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable mysql
Removed /etc/systemd/system/multi-user.target.wants/mariadb.service.

--> neither init nor systemd service files active
```

This is sensible. If a sysadmin disabled mysqld on their system in systemd, they don't want it to be started on next boot via the init script (which will run due to backwards compatibility setups in most distros).

The problem is stars then the service is disabled using an alias, that does not have a direct match in sysvinit files:

```
# systemctl enable mariadb
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service -> /lib/systemd/system/mariadb.service.

# systemctl disable mariadb
Removed /etc/systemd/system/multi-user.target.wants/mariadb.service.

--> systemd-sysv-install does not trigger for service aliases
--> on next reboot /etc/rc.* will run /etc/init.d/mysql which is not intended
```

MariaDB is used as an example here because it has systemd service aliases to support being invoked by as both mariadb or mysql for backwards compatibility reasons.

This also applies for other software. For example `openssh-server` installs sysvinit file `/etc/ini.d/ssh` on Debian and has systemd service file `ssh.service` and alias `sshd.service`. If `systemctl disable sshd` is run, on next reboot SSH from the init file will still run.

## Suggested fix

Expand the comparison that currently looks if there is a /etc/init.d/X where X=systemd service main file name to also check if if there are /etc/init.d/Y or /etc/init.d/Z if Y and Z and systemd service aliases for the service.

**Comment by poettering** [comment]
i am sorry, but no. aliases are a systemd concept, they don't exist on sysvinit. And no, we are not adding new concepts to our compat for sysvinit scripts. we support that as close to the original behaviour as we can, and since sysv didn't know aliases it won't either for us.

if you want aliases, then ship a proper unit file for your service. It's 2020 today.

I am sorry, but we are not going to polish sysvinit support with new features anymore.

I hope this is understandable.

**Comment by ottok** [comment]
> if you want aliases, then ship a proper unit file for your service. It's 2020 today.

I don't understand this remark. I wonder if you read the bug report properly?

We do ship a proper unit file and we do want and we do use aliases, but since `systemd disable X` will not in all cases disable the service and described above, we might need to stop using aliases in the systemd service file.

You don't need to introduce any concepts to sysvinit, you (or somebody else can send a patch if you leave this issue in open state) just needs to apply a bugfix to that the code in https://github.com/systemd/systemd/blob/4c39820562e562b98c2fd269ad3a4f84949d6059/src/systemctl/systemctl.c#L6678 does what the code comment says is should do, in all situations.

**Comment by mbiebl** [comment]
For clarification: What the mariadb package does is:
- Ship a native service file named mariadb.service
- Ship a SysV init script named /etc/init.d/mysql
- Ship a symlink /lib/systemd/systemd/mysql.service → mariadb.service

**Comment by mbiebl** [comment]
Actually, you don't use a static symlink but `Alias=`, right?


> This also applies for other software. For example `openssh-server` installs sysvinit file `/etc/ini.d/ssh` on Debian and has systemd service file `ssh.service` and alias `sshd.service`. If `systemctl disable sshd` is run, on next reboot SSH from the init file will still run.

I can't reproduce that. if I run `systemctl disable sshd`, ssh is not started on boot.

**Comment by ottok** [comment]
I can be reproduced with ssh:
```
root@551698a3c40e:/test# systemctl disable sshd
Removed /etc/systemd/system/multi-user.target.wants/ssh.service.
Removed /etc/systemd/system/sshd.service.

root@551698a3c40e:/test# find /etc/rc* -ls | grep ssh
    13347      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc2.d/S01ssh -> ../init.d/ssh
    13348      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc3.d/S01ssh -> ../init.d/ssh
    13349      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc4.d/S01ssh -> ../init.d/ssh
    13350      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc5.d/S01ssh -> ../init.d/ssh

--> S* links means ssh will still keep starting

root@551698a3c40e:/test# systemctl disable ssh 
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable ssh

root@551698a3c40e:/test# find /etc/rc* -ls | grep ssh
    13347      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc2.d/K01ssh -> ../init.d/ssh
    13348      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc3.d/K01ssh -> ../init.d/ssh
    13349      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc4.d/K01ssh -> ../init.d/ssh
    13350      4 lrwxrwxrwx   1 root     root           13 Apr 10 13:55 /etc/rc5.d/K01ssh -> ../init.d/ssh

--> K* links means that now ssh is really disabled.
```

**Comment by ottok** [comment]
Enabling with alias does however not work is 'ssh' has not been enabled first:
```
root@551698a3c40e:/test# systemctl enable sshd
Failed to enable unit: Unit file sshd.service does not exist.

root@551698a3c40e:/test# systemctl enable ssh 
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
Created symlink /etc/systemd/system/sshd.service -> /lib/systemd/system/ssh.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ssh.service -> /lib/systemd/system/ssh.service.

root@551698a3c40e:/test# systemctl disable sshd
Removed /etc/systemd/system/sshd.service.
Removed /etc/systemd/system/multi-user.target.wants/ssh.service.
```

**Comment by ottok** [comment]
Enabling of `ssh` is idempotent and can be run as many times, but alias `sshd`  will complain:
```
root@551698a3c40e:/test# systemctl enable ssh 
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
root@551698a3c40e:/test# systemctl enable ssh
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
root@551698a3c40e:/test# systemctl enable sshd
Failed to enable unit: Too many levels of symbolic links
root@551698a3c40e:/test# find /etc/systemd /lib/systemd -ls | grep ssh
    13364      4 lrwxrwxrwx   1 root     root           31 Apr 10 14:00 /etc/systemd/system/sshd.service -> /lib/systemd/system/ssh.service
    13366      4 lrwxrwxrwx   1 root     root           31 Apr 10 14:00 /etc/systemd/system/multi-user.target.wants/ssh.service -> /lib/systemd/system/ssh.service
    13067      4 -rw-r--r--   1 root     root          184 Feb 26 10:55 /lib/systemd/system/rescue-ssh.target
    13068      4 -rw-r--r--   1 root     root          538 Feb 26 10:55 /lib/systemd/system/ssh.service
    13069      4 -rw-r--r--   1 root     root          216 Feb 26 10:55 /lib/systemd/system/ssh.socket
    13070      4 -rw-r--r--   1 root     root          289 Feb 26 10:55 /lib/systemd/system/ssh@.service
```

This is however side-tracking the original issue: systemd-sysv-install should trigger for aliases as well.

**Comment by mbiebl** [comment]
> --> S* links means ssh will still keep starting

No, as there is a native service file which is disabled it overrides the enabled state of the sysv init script.

**Comment by mbiebl** [comment]
> root@551698a3c40e:/test# systemctl enable sshd
> Failed to enable unit: Unit file sshd.service does not exist.

Whis would require parsing all .unit files for `Alias=` lines. This idea was rejected in the past (and ist not SysV specific)

**Comment by ottok** [comment]
> No, as there is a native service file which is disabled it overrides the enabled state of the sysv init script.

What code does this?
Is it https://sources.debian.org/src/systemd/245.4-2/debian/extra/init-functions.d/40-systemd/ ? I don't see any section that checks for native service files like this.

**Comment by mbiebl** [comment]
If you have a native service file and a sysv init script of the same name, only the enabled state of the native service file counts.

**Comment by mbiebl** [comment]
> Is it https://sources.debian.org/src/systemd/245.4-2/debian/extra/init-functions.d/40-systemd/ ? I don't see any section that checks for native service files like this.

fwiw, I'm inclined to rework and simplify this script and only forward update-rc.d calls if there is no native .service file.  Synchronizing the state between SysV and systemd native services can lead to confusion (as this bugreport shows).
