### ISSUE TITLE
systemd-detect-virt doesn't always identify docker environments

### ISSUE THREAD

**Issue by mika** [systemd/systemd#15393]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > `systemd-detect-virt` doesn't detect docker when running from inside docker without container being booted/running via systemd

**Unexpected behaviour you saw**
 > `systemd-detect-virt` reports `none` when running inside docker without e.g. `/run/systemd/container` being present

**Steps to reproduce the problem**

```
% docker run --rm -i -t debian:unstable bash
root@d187f93409f2:/# systemd-detect-virt   
none
root@d187f93409f2:/# systemd-detect-virt --container
none
```

It looks like some folks are "manually" setting up `/run/systemd/container` so systemd-detect-virt does its job for detecting docker, but this isn't necessarily true and reliable.

One approach would be to check for presence of file `/.dockerenv` file (see e.g. https://github.com/moby/moby/blob/v1.9.1/daemon/execdriver/lxc/init.go#L111 + https://github.com/moby/moby/blob/b3e9f7b13b0f0c414fa6253e1f17a86b2cff68b5/daemon/initlayer/setup_unix.go)?

**Comment by fishilico** [comment]
Hello, I also hit this bug, for example when running jobs in Arch Linux or Fedora containers:
```console
$ docker run --rm -ti archlinux bash
[root@9df2a5ebee5b /]# systemd-detect-virt --container
none
```

```console
$ docker run --rm -ti fedora:34 bash
[root@5f111469aed7 /]# dnf install -y systemd
...
[root@5f111469aed7 /]# systemd-detect-virt --container
none
```

What would be the proper way to detect that a shell script is running from a container, as `systemd-detect-virt --container` does not work? (My use-case is in https://github.com/archlinuxhardened/selinux/blob/3c62c277a473e8bcf3ad29f95cbfbc0f05200295/build_and_install_all.sh#L64-L70)
