### ISSUE TITLE
Support rotation on Thinkpad Yoga S1

### ISSUE THREAD

**Issue by michamos** [systemd/systemd#1539]
Hi,

I have unmapped keys being triggered on rotation of the laptop & folding of my Thinkpad Yoga S1 Laptop.
`dmesg` output on rotation & folding:

```
atkbd serio0: Unknown key pressed (translated set 2, code 0xd8 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.
```

on rotating back & unfolding:

```
atkbd serio0: Unknown key released (translated set 2, code 0xd8 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known.
```

I tried to adapt @martinpitt's patch for #1440 to my case with modalias

```
dmi:bvnLENOVO:bvrGQET46WW(1.26):bd07/29/2015:svnLENOVO:pn20CD0038MB:pvrThinkPadS1Yoga:rvnLENOVO:rn20CD0038MB:rvrSDK0E50510Pro:cvnLENOVO:ct10:cvrNotAvailable:
```

by adding

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPadS1Yoga*
 KEYBOARD_KEY_d8=direction
 KEYBOARD_KEY_d9=direction
```

to a file in `/etc/udev/hwdb.d/`.
After `udevadm hwdb --update` and reboot, the new keys seem to be picked up, given that `udevadm info --path /sys/devices/platform/i8042/serio0/input/input0/event0` outputs 

```
P: /devices/platform/i8042/serio0/input/input0/event0
N: input/event0
S: input/by-path/platform-i8042-serio-0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/platform/i8042/serio0/input/input0/event0
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_SERIAL=noserial
E: KEYBOARD_KEY_d8=direction
E: KEYBOARD_KEY_d9=direction
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: USEC_INITIALIZED=1713040
E: XKBLAYOUT=be
E: XKBMODEL=pc105
```

However, I still get the 'Unknown key pressed' messages in `dmesg`, so I must be missing something...

I am running Debian unstable, with kernel 4.2.0 and systemd 227.

**Comment by poettering** [comment]
@martinpitt any idea?

**Comment by martinpitt** [comment]
@michamos: Indeed we should generalize the match to also apply to your model then. However, let's first find out what's wrong here. Your local `.hwdb` and the udevadm output look good, so can you please run (as root)

```
strace -fvvs1024 -o /tmp/trace udevadm test-builtin keyboard /devices/platform/i8042/serio0/input/input0/event0
```

copy&paste the output here, and pastebin (or put somewhere else) `/tmp/trace`? Thanks!

**Comment by michamos** [comment]
Output:

```
calling: test-builtin
=== trie on-disk ===
tool version:          227
file size:         6861615 bytes
header size             80 bytes
strings            1722575 bytes
nodes              5138960 bytes
Load module index
timestamp of '/etc/systemd/network' changed
timestamp of '/lib/systemd/network' changed
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /lib/systemd/network/90-mac-for-usb.link
Created link configuration context.
Unknown key identifier 'direction'
Unknown key identifier 'direction'
Unload module index
Unloaded link configuration context.
```

[strace result](https://gist.github.com/michamos/a88d8a1cd193a9f25095)

**Comment by martinpitt** [comment]
> Unknown key identifier 'direction'

Aha! It seems your systemd package was built against an older kernel then? `/usr/include/linux/input.h` should contain

```
#define KEY_ROTATE_DISPLAY………………153……………/* Display orientation for e.g. tablets */
#define KEY_DIRECTION……………………………KEY_ROTATE_DISPLAY
```

which defines the key code. Apparently your kernel doesn't yet?

**Comment by martinpitt** [comment]
Ah, nevermind! It seems our parser doesn't get along with the aliased name. Please change your `.hwdb` file to

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPadS1Yoga*
 KEYBOARD_KEY_d8=rotate_display
 KEYBOARD_KEY_d9=rotate_display
```

Then it should work. Thanks!

**Comment by poettering** [comment]
@martinpitt i figure a patch that makes the alias work would be easy...

**Comment by martinpitt** [comment]
PR #1558 generalizes the match for the Yoga and fixes parsing of aliases. I tested this on my ThinkPad (I dont' have a screen rotation key, but I assigned that key to the mute key).

**Comment by michamos** [comment]
Indeed, with `rotate_display` it works now.
It even works too well in fact, since after a system update [iio-sensor-proxy](https://github.com/hadess/iio-sensor-proxy) started working too. It turns out that rotation events are exposed through the iio bus as well as through keys, leading to the screen rotating twice. I suppose this should be fixed by `iio-sensor-proxy` though rather than not mapping the keys. Any thoughts @hadess?

**Comment by hadess** [comment]
You should leave those keys alone. The Yoga's firmware sends key events whenever it's being folded or unfolded. But those aren't a "screen rotation" button. They're there to tell the OS that the laptop's folding status changed, like a poor man's lid switch.

I would assign it (edit: it, the keycode generating the event that leads to a kernel warning) to a key that doesn't emit any event, and have the laptop automatically rotate based on the accelerometer data instead.

**Comment by keszybz** [comment]
Would iio-sensor-proxy work if we assigned

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPadS1Yoga*
  KEYBOARD_KEY_d8=reserved
  KEYBOARD_KEY_d9=reserved
```

?

**Comment by michamos** [comment]
> The Yoga's firmware sends key events whenever it's being folded or unfolded.

Actually, it sends those key events also when rotating, causing the over-rotation when using iio-sensor-proxy.

> Would iio-sensor-proxy work if we assigned
> 
> ```
> evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPadS1Yoga*
>   KEYBOARD_KEY_d8=reserved
>   KEYBOARD_KEY_d9=reserved
> ```
> 
> ?

I just tried, it does.

EDIT: Warnings about unknown key presses are back though when using `reserved`

**Comment by martinpitt** [comment]
Yes, we already have cases where we disable a key by assigning it to "reserved". I guess I interpreted the issue description as actual keys. I know other ThinkPad laptops which actually have a "rotate screen" button, where this needs to be mapped. I'll adjust my PR then. Now that I re-read issue #1440 it seems like that is the same case.

**Comment by martinpitt** [comment]
> EDIT: Warnings about unknown key presses are back though when using reserved

Ah, then there's no point adding/maintaining a keymap for this. Instead I'll drop the keymap from #1440 again too. Thanks @hadess for the explanation!
