### ISSUE TITLE
systemd-run with --pty shows no output

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#15395]
systemd version is 245.4-2-arch. Details are here: https://github.com/actionless/pikaur/issues/469.

**Comment by ikrivosheev** [comment]
I think, need to remove `--pty` from command.

**Comment by poettering** [comment]
This is not a useful bug report.

Please fill in the form that is provided when filing an issue. The form exists for a reason...

Please provide a minimal reproducer, i.e. a minimal command line we can run to see what the issue is supposed to be.

**Comment by M4tT3d** [comment]
It stucks in terminal
`systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/snapd makepkg --force`

**Comment by NikitaPuzyryov** [comment]
Hereʼs basic repro  `systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes sh -c 'while true; do echo test; done'`

**Comment by poettering** [comment]
Fix waiting in #15545
