### ISSUE TITLE
networkd: VXLAN netdev does not assign group address

### ISSUE THREAD

**Issue by fooker** [systemd/systemd#15391]
**systemd version the issue has been seen with**
systemd 243 (v243.8-1.fc31)

**Used distribution**
Fedora 31 (Server Edition)

**Expected behaviour you didn't see**
After creating a VXLAN netdev with a `Group` multicast address, the group address should be shown in `ip -d link show NETDEV` and `networkctl show NETDEV`.

**Unexpected behaviour you saw**
The group address is not assigned to the interface. No error is shown in debug log.

**Steps to reproduce the problem**
Create a VXLAN netdev (and a simple network) unit containing the following:
```
[NetDev]
Kind=vxlan
Name=myvx

[VXLAN]
VNI=1
Group=ff02::42:1
DestinationPort=8472
```
After restarting `systemd-networkd` the VXLAN device is created, but the group address is not assigned. Use  `ip -d link show myvx` and `networkctl show myvx` to verify.

In contrast, creating the device using iproute2 (`ip -6 link add name myvx type vxlan id 1 dev enp8s0 dstport 8472 group ff02::42:1`) will assign the group address and it will show up in both commands.

The logs don't show any error or warning.

**Comment by ssahani** [comment]
Fix is https://github.com/systemd/systemd/pull/15397
