### ISSUE TITLE
nspawn: clarify that VirtualEthernetExtra= doesn't configure any bridging

### ISSUE THREAD

**Issue by heini** [systemd/systemd#15402]
When adding an extra veth interface to an already running system container which has a working "host0" veth interface connected to a bridge on the host, the additional interface is not brought up.

**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Extra interfaces should be brought up just like host0

**Unexpected behaviour you saw**
 > Extra interfaces are not getting configured

**Steps to reproduce the problem**
1. Take a container with working veth networking in bridge mode
2. Add another veth interface using `VirtualEthernetExtra=vb-somename.2:host1`
3. Add a host1.network file for simple DHCP configuration to /etc/systemd/network/ and restart the container

Here's what the `ip`command shows on both the host and the container:
```
34: vb-somename@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
    link/ether 0a:43:21:04:d6:f7 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::843:21ff:fe04:d6f7/64 scope link 
       valid_lft forever preferred_lft forever
35: vb-somename.2@if3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 62:9c:65:e2:a4:3c brd ff:ff:ff:ff:ff:ff link-netnsid 0
```
```
2: host0@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 06:e3:54:3f:e6:27 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.103/24 brd 192.168.1.255 scope global host0
       valid_lft forever preferred_lft forever
    inet6 2a00:6020:15d0:ae00:4e3:54ff:fe3f:e627/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 3583sec preferred_lft 2233sec
    inet6 fe80::4e3:54ff:fe3f:e627/64 scope link 
       valid_lft forever preferred_lft forever
3: host1@if35: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 0a:05:b5:53:b1:26 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```
Looking at nspawn.c (lines 4444-4477), it seems that the first interface is added to the bridge, but the extra ones are not.

**Comment by poettering** [comment]
I am sorry, but what's the precise issue? see the man page:

```
       --network-veth-extra=
           Adds an additional virtual Ethernet link between host and container. Takes a colon-separated pair of host interface name and container interface name. The latter may be omitted in which case the container and host sides
           will be assigned the same name. This switch is independent of --network-veth, and — in contrast — may be used multiple times, and allows configuration of the network interface names. Note that --network-bridge= has no
           effect on interfaces created with --network-veth-extra=.
```

I am not sure I grok what you are saying, but aren't you just expecting behaviour that is explicitly documented as not happening in the last sentence of this man page text?

What am I missing?

Conceptually, --network-bridge= is supposed to be just a simple shortcut for a common case, and for any more complex setups, you better use a couple .network drop-ins plus --network-veth-extra= for as many ifaces as you need. If you do it like that you have the full power of setting things up any way you like. 

Hence, if you are looking for "--network-bridge-extra=" or so, i.e. the ability to add more veth tunnels but all connected to the same bridge: this is clearly out of focuse here, just use .network files for that.

Or what am I missing?

**Comment by heini** [comment]
Ah, OK. I was looking up systemd.nspawn(5), which doesn't say anything about not adding the extra interface to the bridge.
So, if I understand this right, I'd need to add the extra interface to the bridge and bring it up explicitely, most likely every time the container starts? How would I use .network files for this?

**Comment by poettering** [comment]
Write a .network file that matches against the veth host side and uses Bridge= to add it to the bridge as it pops up. THere's plenty of documentation around for that.

Anyway, I guess we can update the documentation of the .nspawn files a bit regarding this. turning this into a documentation bug hence.

**Comment by heini** [comment]
Thanks a lot. Could you also think about considering this a feature request to enhance `VirtualEthernetExtra=` so that it accepts an optional bridge (like: host-if:container-if[:bridge])? Would make the above far more simple, IMHO...

**Comment by poettering** [comment]
THere's already #11087 which asks for what you are asking for, no?

**Comment by poettering** [comment]
THere's already #11087 which asks for what you are asking for, no?

**Comment by heini** [comment]
Seems so, yes.
