### ISSUE TITLE
systemd-networkd Failed to start network service

### ISSUE THREAD

**Issue by tricky-mind** [systemd/systemd#15410]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 >Linux From Scratch (Kali Linux as Host)

when the system is booted the network service is not starting. I checked with all the drivers.

this is what i get when i run **systemctl status systemd-networkd.service**

![Screenshot_2020-04-12_03-16-54](https://user-images.githubusercontent.com/52381720/79063267-9964fa80-7c6e-11ea-880d-b6aeb0ab3daf.png)
![Screenshot_2020-04-12_03-17-37](https://user-images.githubusercontent.com/52381720/79063268-9d911800-7c6e-11ea-8510-e2cddb6d3750.png)

**Unexpected behaviour you saw**
 >not only this all the services related to the network also fails

**Comment by mbiebl** [comment]
Please provide the output of
`systemctl cat systemd-networkd.service`

**Comment by tricky-mind** [comment]
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Network Service
Documentation=man:systemd-networkd.service(8)
ConditionCapability=CAP_NET_ADMIN
DefaultDependencies=no
# systemd-udevd.service can be dropped once tuntap is moved to netlink
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Conflicts=shutdown.target
Wants=network.target

[Service]
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
DeviceAllow=char-* rw
ExecStart=!!/lib/systemd/systemd-networkd
WorkingDirectory=/lib/systemd/
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectKernelModules=yes
ProtectSystem=strict
Restart=on-failure
RestartSec=0
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6 AF_PACKET
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RuntimeDirectory=systemd/netif
RuntimeDirectoryPreserve=yes
SystemCallArchitectures=native
SystemCallErrorNumber=EPERM
SystemCallFilter=@system-service
Type=notify
User=systemd-network
WatchdogSec=3min

[Install]
WantedBy=multi-user.target
Also=systemd-networkd.socket
Alias=dbus-org.freedesktop.network1.service

# We want to enable systemd-networkd-wait-online.service whenever this service
# is enabled. systemd-networkd-wait-online.service has
# WantedBy=network-online.target, so enabling it only has an effect if
# network-online.target itself is enabled or pulled in by some other unit.
Also=systemd-networkd-wait-online.service

**Comment by tricky-mind** [comment]
```
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Network Service
Documentation=man:systemd-networkd.service(8)
ConditionCapability=CAP_NET_ADMIN
DefaultDependencies=no
# systemd-udevd.service can be dropped once tuntap is moved to netlink
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Conflicts=shutdown.target
Wants=network.target

[Service]
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
DeviceAllow=char-* rw
ExecStart=!!/lib/systemd/systemd-networkd
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectKernelModules=yes
ProtectSystem=strict
Restart=on-failure
RestartSec=0
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6 AF_PACKET
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RuntimeDirectory=systemd/netif
RuntimeDirectoryPreserve=yes
SystemCallArchitectures=native
SystemCallErrorNumber=EPERM
SystemCallFilter=@system-service
Type=notify
User=systemd-network
WatchdogSec=3min

[Install]
WantedBy=multi-user.target
Also=systemd-networkd.socket
Alias=dbus-org.freedesktop.network1.service

# We want to enable systemd-networkd-wait-online.service whenever this service
# is enabled. systemd-networkd-wait-online.service has
# WantedBy=network-online.target, so enabling it only has an effect if
# network-online.target itself is enabled or pulled in by some other unit.
Also=systemd-networkd-wait-online.service

```

**Comment by ssahani** [comment]
It seems networkd is crashing. A bt is useful here. Please do bt full.

**Comment by tricky-mind** [comment]
is there any way to fix it other than disabling systemd-networkd service

**Comment by mbiebl** [comment]
That doesn't look like the systemctl cat output, E.g. the override.conf is missing.

**Comment by ssahani** [comment]
The log can be generated by creating e.g. the following drop-in config:

```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by tricky-mind** [comment]
> The log can be generated by creating e.g. the following drop-in config:
> 
> ```
> # /etc/systemd/system/systemd-networkd.service.d/override.conf
> [Service]
> Environment=SYSTEMD_LOG_LEVEL=debug
> ```

The log gives same error as in the screenshot.nothing else

**Comment by ssahani** [comment]
I am sorry. Not sure how to proceed without the logs.

**Comment by tricky-mind** [comment]
> I am sorry. Not sure how to proceed without the logs.

i'm sorry that the logs are in this way because i cant move the log file to my host system

Page 1
![p1](https://user-images.githubusercontent.com/52381720/79069382-bf54c400-7c9b-11ea-82e5-6c96aa45a4f8.png)
![p2](https://user-images.githubusercontent.com/52381720/79069383-c380e180-7c9b-11ea-8933-d820ec75c725.png)

page 2

![p3](https://user-images.githubusercontent.com/52381720/79069386-cb408600-7c9b-11ea-9f5d-886877ea3e20.png)
![p4](https://user-images.githubusercontent.com/52381720/79069387-cd0a4980-7c9b-11ea-8a4b-7f22940e22bf.png)

page 3
![p5](https://user-images.githubusercontent.com/52381720/79069389-d4315780-7c9b-11ea-8b02-dd2b249284fb.png)
![p6](https://user-images.githubusercontent.com/52381720/79069390-d5628480-7c9b-11ea-951e-55b08e6facde.png)

**Comment by ssahani** [comment]
it seems some kind of dir permission issue to me from `status=200/CHDIR`. @poettering ?

**Comment by tricky-mind** [comment]
which directory should i need to check. I'm very much confused

**Comment by poettering** [comment]
what's the access mode + ownership of your root directory?

if chdir() fails, then this means something is wrong with that. Consider doing an `strace -f -s 500 -p 1 -o log` one one tty, while you type `systemctl start systemd-networkd` on another. This should write a syslog trace of what PID 1 and any forked off child does to the file `log`, and then you should be able to see whether chdir("/") fails...

Do you use any weird MAC? SELinux or so?

**Comment by tricky-mind** [comment]
Thank you very much @poettering. i figured it out it was just the permission issue of root folder.now the service is working fine.thankyou
