### ISSUE TITLE
Please add a .clang-format file

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#15415]
I am contributing to various projects, and the differing Coding styles
are a big timesink for making code "fitting". I guess some of your time is wasted as well by pointing out violations.

So I would ask you to "invest" in a best-fit .clang-format, even if its not a 100% fit its a good starting point. 
In case you don't know, `git clang-format [--diff]` will apply/show corrections only on changed lines (possible to integrate this into CI)

**Comment by poettering** [comment]
See: #11811

**Comment by keszybz** [comment]
This is never going to happen until clang-format gets much much smarter. There were attempts previously, but we have lots of formatting rules to make the code readable in different contexts. Automatic formatting is generally not flexible enough to support this.

I'll close this issue to avoid false hope.

**Comment by nolange** [comment]
Thing is, that I will still use clang-format or equivalents for systemd, even if this is not deemed sufficient its better than having nothing.
So just throw it under `tools/` with some notes that this is no substitute to reading an adhering to the style guide.

**Comment by keszybz** [comment]
Indeed, we should probably do that.

**Comment by nolange** [comment]
Thanks for making this happen.

It seems though, that the backslashes are messing up the `ForEachMacros`.
Thats what I get after a `clang-format --style=file --dump-config`:
(which I would recommend before committing this)

```
ForEachMacros:
  - BITMAP_FOREACH
  - CMSG_FOREACH
  - _DNS_ANSWER_FOREACH
  - DNS_ANSWER_FOREACH
  - '\
  _DNS_ANSWER_FOREACH_FLAGS'
  - DNS_ANSWER_FOREACH_FLAGS
  - _DNS_ANSWER_FOREACH_FULL
  - '\
  DNS_ANSWER_FOREACH_FULL'
```
