### ISSUE TITLE
Domain resolves to 192.0.2.1

### ISSUE THREAD

**Issue by johnbester** [systemd/systemd#15420]
**systemd version the issue has been seen with**
systemd 237

**Used distribution**
Ubuntu Mate 18.04 i386
Ubuntu 18.04 x64

**Expected behaviour you didn't see**
domains should resolve to the same IP that the DNS servers resolve to

**Unexpected behaviour you saw**
Some domains intermittently resolved to 192.0.2.1

**Steps to reproduce the problem**
This is difficult. Yesterday I did a clean install of Ubuntu Mate 18.04.4 1386 and apt update failed after first reboot because of this problem. Today I did a clean install of the same ISO to a VirtualBox VM and I did not have any problems.

I performed a lot of cli commands to show as best I could what happens. Please read through the attached pdf to get the details.

[dns-problem.pdf](https://github.com/systemd/systemd/files/4469226/dns-problem.pdf)

**Comment by poettering** [comment]
uh this is seriously weird. (submitting a PDF is a bit weird, btw)

What is the contents of /etc/hosts on that system?

Any chance you can reproduce this on the affected system and set SYSTEMD_LOG_LEVEL=debug as env var for the systemd-resolved service? i.e. run `systemctl edit systemd-resolved`, then write into the editor:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

and issue `systemctl restart systemd-resolved`. That will then make sure resolved starts logging about every request it gets, and how it resolves it. It would be very interesting to get the relevant output for such a bad lookup on that machine.

**Comment by poettering** [comment]
Closing due to lack of response.

**Comment by johnbester** [comment]
My apologies. I remember writing a response, but I never checked the actual bug report to see if my response was listed.

I might have since figured out what caused the problem, so I was able to fix the issue. But in figuring out the problem I might have stumbled on a security issue which is not a bug per se, or I might have interpreted my findings incorrectly. However, it might be worth looking in to. The only problem I have is that I cannot describe the issue without outright saying how it may be
misused, and since this bug report is open to the public to view I would rather communicate that information via email to a recipient that can decide what to do with it before making it public (if need be).

**Comment by poettering** [comment]
Please report security issues like described here: https://systemd.io/SECURITY

Thank you!

**Comment by keszybz** [comment]
systemd-resolved does not do any kind of server discovery — it just uses whatever it configured, explicitly or from other services. We can't diagnose this based only on nslookup and ping entries. This is especially true for Ubuntu, which uses a unique setup and a very old version of systemd, which we don't support upstream anymore.

You need to figure out how the additional name server gets inserted into your configuration. Since you're using NM, I'd start by checking if NM isn't picking it up and passing to resolved. (And please don't post PDFs — plaintext FTW!)

**Comment by kht-pavel** [comment]
> **systemd version the issue has been seen with** systemd 237
> 
> **Used distribution** Ubuntu Mate 18.04 i386 Ubuntu 18.04 x64
> 
> **Expected behaviour you didn't see** domains should resolve to the same IP that the DNS servers resolve to
> 
> **Unexpected behaviour you saw** Some domains intermittently resolved to 192.0.2.1
> 
> **Steps to reproduce the problem** This is difficult. Yesterday I did a clean install of Ubuntu Mate 18.04.4 1386 and apt update failed after first reboot because of this problem. Today I did a clean install of the same ISO to a VirtualBox VM and I did not have any problems.
> 
> I performed a lot of cli commands to show as best I could what happens. Please read through the attached pdf to get the details.
> 
> [dns-problem.pdf](https://github.com/systemd/systemd/files/4469226/dns-problem.pdf)



> My apologies. I remember writing a response, but I never checked the actual bug report to see if my response was listed.
> 
> I might have since figured out what caused the problem, so I was able to fix the issue. But in figuring out the problem I might have stumbled on a security issue which is not a bug per se, or I might have interpreted my findings incorrectly. However, it might be worth looking in to. The only problem I have is that I cannot describe the issue without outright saying how it may be misused, and since this bug report is open to the public to view I would rather communicate that information via email to a recipient that can decide what to do with it before making it public (if need be).

Hello
I have similar problem on ubuntu server 20.04
could u write me what caused it directly to email?
github@i776781i.beget.tech
