### ISSUE TITLE
systemctl: failed to open /run/systemd/ask-password/block/136:2

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#1543]
When calling `systemctl <privileged command>` as a non-privileged user (using polkit), systemctl complains:

```
Failed to open /run/systemd/ask-password-block/136:2: No such file or directory
```

However, after authenticating with polkit, the command to completes successfully.

Distro: Arch Linux
systemd version: 227

**Comment by ghost** [comment]
Noticed similar, only in my case it returned "Permission denied" instead of "no such file or directory"

**Comment by poettering** [comment]
This is mostly cosmetic. We should just downgrade the message
