### ISSUE TITLE
Some of the manager settings require daemon-reexec rather than daemon-reload

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#15453]
When changing some settings in system.conf, `daemon-reload` is usually enough for the new values to be taken into account.

But there are a couple of settings such as `WatchdogRuntime=`, which are basically the settings affecting the manager itself rather than the units, that require a full daemon reexecution.

I opened this report because it's not really clear to me whether we should fix the documentation or we should try to make `daemon-reload` work with the manager settings (or some of them).

**Comment by poettering** [comment]
hmm, i figure we should determine what to do for each setting individually. My guess is that WatchdogRuntime= specifically should definitely be fixed to be updated on daemon reload.

**Comment by fbuihuu** [comment]
@poettering what about https://github.com/systemd/systemd/pull/15535 ?
