### ISSUE TITLE
networkd:  addr_gen_mode overwriten by networkd

### ISSUE THREAD

**Issue by AvailCat** [systemd/systemd#15465]
**systemd version the issue has been seen with**
> 245 (latest) on ArchLinux and 241 on Debian

**Used distribution**
 > ArchLinux and Debian

**Expected behaviour you didn't see**
>  Set `net.ipv6.conf.all.addr_gen_mode = 3` in `/etc/sysctl.d/99-sysctl.conf` should  keep ip address generate with a new random token at every reboot or restart, and stable-privacy applied to the address with flag mngtmpaddr

**Unexpected behaviour you saw**
 > It was overwritten to 0 by systemd-networkd, and no stable-privacy flag for the address with flag mngtmpaddr

**Steps to reproduce the problem**
1. Keep systemd-networkd stopped, disabled
2.  Append those line after your sysctl file, either new file in sysctl.d or sysctl.conf should be okay
```
net.ipv6.conf.all.addr_gen_mode = 3
net.ipv6.conf.all.use_tempaddr = 2
```
3. Reboot, don't apply with sysctl -p
4. Check with `sysctl -a | grep gen_mode`, all value was set to 3
5. Use this network configure:
```
[Match]
Name=eth0

[Network]
DHCP=yes
IPv6PrivacyExtensions=kernel
# 👆 I don't know is this required but with or without this will got same result
```
6. Start systemd-networkd
7. Repeat step 4, but you will see the value of eth0 changed to 0

The excepted behaviour section was what i see with Wicked (openSUSE) or just `ip link set eth0 up`

**Comment by ssahani** [comment]
Allow to configure addr_gen_mode  https://github.com/systemd/systemd/pull/15167
