### ISSUE TITLE
networkd: DHCPv6 Send extra options

### ISSUE THREAD

**Issue by jblankfeld** [systemd/systemd#15471]
**Is your feature request related to a problem? Please describe.**
I would like to replace my router ipv6 configuration deamons (dibbler, radvd) with systemd-networkd.
My ISP enforces the presence of specific DHCPv6 options (11 authentication, 15 user class, 16 vendor class) during SOLICIT and REQUEST messages. These option codes also must be passed in the "Option Request Option" field (6). It would be very appreciated if networkd could allow that sort of override, in the same fashion than previously done for DHCPv4.

**Describe the solution you'd like**
Implement SendOption= and RequestOption= configuration in [DHCPv6] section

**Comment by ssahani** [comment]
@jblankfeld is anything need to be implemented ?

**Comment by jblankfeld** [comment]
Hi,
I think that these pull requests, along with https://github.com/systemd/systemd/pull/15494 and https://github.com/systemd/systemd/commit/e7d5fe17db9d046b364f933c4dcdd145f47b024a should cover all I need.
Thanks a lot. :+1:
