### ISSUE TITLE
Systemd should allow user services run before the system goes into a suspend state via a sleep.target or the like

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#15477]
**Is your feature request related to a problem? Please describe.**

I need to have systemd in **user mode** run a target script before the system is suspended.  The `sleep.target` does not seem to work in user mode.

Here is a use case: the expected behavior of systemd in **user mode** is to pass 3 different augments to a target script under 4 different circumstances:

1. Pass "start" as the first token when the service is started
2. Pass "stop" when the service is stopped
3. Pass "resync" once per hour
4. Pass "resync" if the system is suspended

* To do 1 and 2 I have [psd.service](https://github.com/graysky2/profile-sync-daemon/blob/df8e8e9a97c48e27b4b2b813e08f121a49ed8f7d/init/psd.service)
*  To do 3 I created a separate service/timer and joined them to the first one [psd-resync.timer](https://github.com/graysky2/profile-sync-daemon/blob/75363da43fe2767deec908861efd1f1ae1529f3f/init/psd-resync.timer) and [psd-resync.service](https://github.com/graysky2/profile-sync-daemon/blob/f72a82896e0b82b40a9ad7623a6e48e40de18217/init/psd-resync.service)

These do not cover #4.  I tried adding the `sleep.target` to `psd-resync.service` but it is not honored when the system is suspended.  I believe these targets do not work in user mode.

**Describe the solution you'd like**
Systemd should allow user services run before the system goes to sleep via a `sleep.target` or the like

**Describe alternatives you've considered**
* One solution could be to use a systemd sleep hook but that requires a system unit and in my case, that would mix a system unit with a user unit which is complex and just seems wrong.
* Another solution could be to have the bash script some how [listen to dbus](https://unix.stackexchange.com/questions/149959/how-to-run-systemd-user-service-to-trigger-on-sleep-aka-suspend-hibernate) and execute a function when dbus tells it that the system is going to suspend.  I'm thinking that could be useful if I could also employ a `systemd-inhibit` command that could be cleared after the script's function I want to call on suspend completes.

Both of those seems needlessly complex.

**Comment by poettering** [comment]
THis is unsafe, we cannot allow clients to synchronously delay sleeping. There's a concept of suspend inhibitors though, which can be acquired with a time limit (or by authenticating via pk first), but running unprivileged user scripts synchronously before going to sleep is something we simply cannot support in general, since it's a security problem.

if you use inhibitor locks then everything should be fine. And yeah, I am sorry they require you to talk to dbus, but it's the way it is...

**Comment by poettering** [comment]
Let's close this. I am pretty sure we cannot and shouldn't do this, for the aforementioned security implications. use inhibitor locks, that's what they are for, and hey have timeouts.
