### ISSUE TITLE
Can systemd.network assign two LinkLocalAddressing addresses

### ISSUE THREAD

**Issue by aletheia7** [systemd/systemd#1547]
I have two processes that bind to the same port on the same machine. I use LinkLocalAddressing in the the systemd.network file. I use a bridge device (br0). How can I get the bridge to have two zeroconf 169.254.*.* addresses? Multiple [Network] sections do not work and LinkLocalAddressing is not used in the [Address] section.
#### br0.network

``` sh
[Match]
Name = br0

[Network]
LinkLocalAddressing = ipv4
NTP = ntp1.local
LLMNR = false
# vim: ft=sh
```
#### br0.netdev

``` sh
[NetDev]
Kind = bridge
Name = br0

# vim: ft=sh
```
### cards.network

``` sh
[Match]
Name = e*

[Network]
Bridge = br0

# vim: ft=sh
```

**Comment by poettering** [comment]
Please not that this is not a support forum, please send help requests like this one to systemd-devel, rathern than post them as issue. Only report bugs here, please. Closing, as misfiled.
