### ISSUE TITLE
networkd: DHCPv4 send user_class and extra options in request

### ISSUE THREAD

**Issue by jblankfeld** [systemd/systemd#15470]
**Is your feature request related to a problem? Please describe.**
My ISP mandates DHCP options 90 authentication, user class and vendor class to be sent in the DHCP Request.
Although it is possible to send these options in DHCP Discover using the appropriate [DHCPv4] options, only vendor class is sent during Request. This causes my ISP not to offer me a lease.

**Describe the solution you'd like**
I would like DHCPv4 options user class and extra generic options to be appended in the DHCP Request message and not only DHCP Discover.

This behavior would be consistent with dhclient and busybox udhcpc that I tested successfully against that ISP.

**Comment by ssahani** [comment]
User class , requested options and Send generic options already implemented. 

https://www.freedesktop.org/software/systemd/man/systemd.network.html#UserClass=
https://www.freedesktop.org/software/systemd/man/systemd.network.html#RequestOptions=
https://www.freedesktop.org/software/systemd/man/systemd.network.html#SendOption=

**Comment by jblankfeld** [comment]
Yes, I tried to debug this and https://github.com/systemd/systemd/blob/5099fd44ca56f4be22191dafb16b967045bfbb90/src/libsystemd-network/sd-dhcp-client.c#L921 (discover) shows user class, vendor class and generic options are all appended but https://github.com/systemd/systemd/blob/5099fd44ca56f4be22191dafb16b967045bfbb90/src/libsystemd-network/sd-dhcp-client.c#L1049 (request) shows that vendor class is appended but not user class and generic options.

**Comment by ssahani** [comment]
yes please test with https://github.com/systemd/systemd/pull/15488

**Comment by jblankfeld** [comment]
This is perfect :+1: Thank you

**Comment by dollar349** [comment]
if I set `RequestOptions` in my network file.
for example
```
[DHCPv4]
RequestOptions=125
```
And restart `systemd-networkd`, how to get this option's return value?

**Comment by yuwata** [comment]
@dollar349 Usually most provided values by server for options in `RequestOptions=` are simply ignored by networkd. Maybe, we need to provide a way to dump dhcp leases in `networkctl` with json format or so. Could you open a new page for the RFE with a concrete usecase?

**Comment by elshyam** [comment]
How could we save return value for `RequestOptions`, is there any specified location/file where is it saved?
I see my dhcp server send Requested Option but `systemd-networkd` is not saving. I am running `systemd-networkd` version 246.2, please let me know

Thanks in advance.

**Comment by yuwata** [comment]
@elshyam Unfortunately, currently systemd doesn't provide a way users to read/parse requested options.

**Comment by srd424** [comment]
See #16785 - could we not just write it to somewhere under `/run/systemd`? Then an inotify watch or something could be set up on it...
