### ISSUE TITLE
colored journalctl output hard or impossible to read

### ISSUE THREAD

**Issue by olafhering** [systemd/systemd#15498]
**systemd version the issue has been seen with**
> 245
(but in fact, this happens since months or even years)

**Used distribution**
 > Tumbleweed

**Expected behaviour you didn't see**
 > A plain `journalctl -b` should use just three colors: the default terminal background color for "no text", the default terminal foreground color for "text", and the color red (or whever stands obviously out based on the background color) for error message. 

**Unexpected behaviour you saw**
 > there is a rainbow of colors used for all sorts of various subsystems. As a result a number of them are just not readable, depending on the background color. One must pipe to `less` or take additional actions to disable colors. As a result, errors do not stand out anymore.

**Steps to reproduce the problem**
Run `journalctl -b`, expect errors to be easily identify.
![Bildschirmfoto_2020-04-20_17-52-20](https://user-images.githubusercontent.com/942324/79773064-77c7db00-8320-11ea-8c17-41138ba3cfa7.png)

**Comment by poettering** [comment]
Please use SYSTEMD_COLORS=0 to turn off coloring on your system. It's impossible to pick colors that work on all backgrounds. We only try to cover the common backgrounds, i.e. white and black. If we want to support grey or yellow backgrounds we can only lose, as this basically means using no color at all.

Sorry, but I think the benefit of greying out debug messages is major and it's still very well visible for most users, given they use black or white as bg. The few people who pick something else are out in the cold, but I think the benefit for the many wins over the problems here with the few. I am sorry, but this yellow tone you picked is definitely not a particular common background.

Sorry, but I hope this is understandable.

**Comment by olafhering** [comment]
White as background is hardly a usable and healthy environment. Neither is black. But sure, ppl never get out of their tiny `cmd.exe` world...

**Comment by oliverpool** [comment]
Since https://github.com/systemd/systemd/pull/17702 has been merged (released in version 248), you can use set the `SYSTEMD_COLORS` environement variable to `16` to accommodate your palette.

> Various tools now accept SYSTEMD_COLORS=16|256 to configure what colours are used in output.

**Comment by miccoli** [comment]
> Please use SYSTEMD_COLORS=0 to turn off coloring on your system. It's impossible to pick colors that work on all backgrounds. We only try to cover the common backgrounds, i.e. white and black. If we want to support grey or yellow backgrounds we can only lose, as this basically means using no color at all.

Sorry for the added noise on this old issue. I understand that the systemd color scheme is hardcoded... but I think that having a configurable color scheme would be more inclusive towards the large Linux community.

**Comment by oliverpool** [comment]
@miccoli see my comment above. You can use `SYSTEMD_COLORS=16` to use the colors of your terminal (since version 248).

**Comment by miccoli** [comment]
@oliverpool I read with attention the whole thread, and arrived here after searching the internet on this problem. I'm well aware that `SYSTEMD_COLORS=16` is a great improvement with respect to legibility and usefulness, but IMHO it is not a substitute for a custom color scheme.

- `SYSTEMD_COLORS=16` disables automatic color selection, so you cannot pipe the output:
    ```
   $ SYSTEMD_COLORS=16 journalctl -e -o json | jq .
    parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 25
    ```
    This prevents setting `export SYSTEMD_COLORS=16` once for all, because then you have to remeber to unset it before piping.
- Of course I'm responsible for choosing a legible 8+8 base ansi color palette, but there is no guarantee that what “yellow” means for systemd is tha same for all other programs... or to be more explicit, I'm stuck with the cognitive choices of systemd, and I have to adapt all other programs (which may have a configurable color scheme) to follow that same choices.

So the only safe setting is `export SYSTEMD_COLORS=0` for now.

I gave a quick view at #17702, and I understand the complexity of the status quo: I do not feel bad if implementing a customizable color scheme is deemed unfeasable. Thanks again for your prompt reply.

**Comment by poettering** [comment]
Sorry, we are not going to add fully configurable coloring to systemd. Hard no. If you don't like the colors of your terminal, then fix that, but don#t make that a systemd problem. We are not in the theming business.

> * `SYSTEMD_COLORS=16` disables automatic color selection, so you cannot pipe the output:

This is a valid point. Happy to take a patch that adds `SYSTEMD_COLORS=auto-16` or so that forces 16 color mode, but keeps the pipe detection logic in place. Or file an RFE for that.
