### ISSUE TITLE
A process move from system.slice  to user.slice when sytemctl daemon-reload

### ISSUE THREAD

**Issue by JackFangXN** [systemd/systemd#15496]
**systemd version the issue has been seen with**
> systemd245

**Used distribution**
 >i start a process by shell, and put this process in system.slice, but after "systemctl daemon-reload", this process is back to user.slice. i hope all resource manager is controlled by system.slice. 
**Expected behaviour you didn't see**
 >The process 2822476 still is in system.slice/system-fsa.slice

**Unexpected behaviour you saw**
 > The process 2822476 is back to user.slice/user-0.slice/session-32.scope

**Steps to reproduce the problem**
1、sleep 1000 &
![image](https://user-images.githubusercontent.com/53254947/79760007-0143d100-8352-11ea-81de-83c1a399471e.png)
   2、echo 2822476 > /sys/fs/cgroup/memory/system.slice/system-fsa.slice/tasks
        cat /sys/fs/cgroup/memory/system.slice/system-fsa.slice/tasks
![image](https://user-images.githubusercontent.com/53254947/79760105-29333480-8352-11ea-804a-507512a2622b.png)
   3、cat /proc/2822476/cgroup
![image](https://user-images.githubusercontent.com/53254947/79760415-98108d80-8352-11ea-90a1-5666fe49d5cd.png)
   4、systemctl daemon-reload
         cat /sys/fs/cgroup/memory/system.slice/system-fsa.slice/tasks
         cat /proc/2822476/cgroup
![image](https://user-images.githubusercontent.com/53254947/79760415-98108d80-8352-11ea-90a1-5666fe49d5cd.png)

**Comment by JackFangXN** [comment]
How do i should to avoid ？

**Comment by boucman** [comment]
The short answer is "don't do that"
More precisely, systemd is the one handling cgroup and other processes (including you, the admin) shouldn't change processes between cgroup directly.

If you want to do something like that you should : 
* Start the process in its own service (using systemd-run is the common way to do that
* put it in another slice, either directly at startup using systemd-run --property Slice= or after the fact using systemctl set-property <the service> Slice=

**Comment by JackFangXN** [comment]
i can understand, but the same operation is ok in systemd 219，i am sure this commit cause https://github.com/systemd/systemd/commit/58d83430e1276fe8d1224c2b5f76e756d143a375,
 there are many the same actions in lower version OS. I need to spend a lot of energy to adapt, which is obviously unscientific. The higher systemd version should keep backward compatibility or support the ablity to config, the user can decide open or not.

**Comment by JackFangXN** [comment]
could you help me to add this config or  other better way.

**Comment by poettering** [comment]
on systemd systems it's systemd that manages the cgroup tree. You can have your own subtree if you want, see https://systemd.io/CGROUP_DELEGATION/

**Comment by poettering** [comment]
anyway, let's close this, it's clearly documented that you void your warranty if you manipulate the cgroup tree yourself.

**Comment by JackFangXN** [comment]
ok，tks.
