### ISSUE TITLE
Fix Chromebook accelerometer not having correct orrientation

### ISSUE THREAD

**Issue by MadMcCrow** [systemd/systemd#15513]
**Is your feature request related to a problem? Please describe.**
 The accelerometer sensor for the samsung chromebook pro reports inverted position that causes inverted screen rotation, forcing user to disable the auto rotate feature on their devices. 

**Describe the solution you'd like**
Adding a new rule in 60-sensor.hwdb 
```
sensor:modalias:platform:cros-ec-accel:dmi:*:svnGoogle:pnCaroline*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
```
fixes the issue for this specific computer without (hopefully) affecting other devices

**Describe alternatives you've considered**
adding the rule with both spelling of Google (ie. `svnGOOGLE` and `svnGoogle`), might help users of other boards

**Comment by poettering** [comment]
please submit as PR, so that we can merge this patch and attribute it correctly to you.

/cc @hadess
