### ISSUE TITLE
nspawn: Impossible to override --network-veth with VirtualEthernet=no

### ISSUE THREAD

**Issue by pocek** [systemd/systemd#1554]
`--network-veth` command line argument of `systemd-nspawn` implies `--private-network`, so if we have:

```
ExecStart=@bindir@/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth --settings=override --machine=%I
```

and try to override it:

```
# cat /etc/systemd/nspawn/foo.nspawn 
[Network]
VirtualEthernet=no
```

it doesn't work, because the implied `--private-network` is not reset nor read from .nspawn file.

```
[Network]
VirtualEthernet=no
Private=no
```

doesn't work either - private network is left enabled. AFAICS, the same stands for other network related options.

systemd v226.

**Comment by fsateler** [comment]
I can reproduce this with 227.

**Comment by Ferdi265** [comment]
Ran into this bug on systemd 239.

`VirtualEthernet=no` or `Private=no` don't have an effect on the created container
