### ISSUE TITLE
nspawn-v227: cannot mount /sys with private users but without private net

### ISSUE THREAD

**Issue by alban** [systemd/systemd#1555]
systemd 227

```
# systemd-nspawn --private-users=10000:65536
[pid   390] mount(NULL, "/proc/sys", NULL, MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND, NULL) = 0
[pid   390] mkdir("/sys/full", 0755)    = 0
[pid   390] mount("sysfs", "/sys/full", "sysfs", MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL <unfinished ...>
[pid   388] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid   390] <... mount resumed> )       = -1 EPERM (Operation not permitted)
```

But it works fine if I add `--private-net`

```
# systemd-nspawn --private-users=10000:65536 --private-net
```

I suspect the difference with `--private-net` comes from the following test in the kernel:

> [linux/fs/sysfs/mount.c#L33](https://github.com/torvalds/linux/blob/master/fs/sysfs/mount.c#L33)
> 
> ```
>     if (!(flags & MS_KERNMOUNT)) {
>         if (!kobj_ns_current_may_mount(KOBJ_NS_TYPE_NET))
>             return ERR_PTR(-EPERM);
>     }
> ```

I am not sure why this issue was not seen before systemd-v227. It is probably because of the new way /sys is mounted in nspawn containers: https://github.com/systemd/systemd/commit/d8fc6a000fe21b0c1ba27fbfed8b42d00b349a4b

Tested on Linux v4.1 and Linux 4.3.0-rc4+. There was a fair amount of changes in the Linux kernel about sysfs and procfs mounts due to options nosuid,nodev,noexec. So I don't know if it is reproducible on all Linux versions or only the ones I tested.

**Comment by poettering** [comment]
Ah, jeezuz.. i figure we can fix the stuff to mount the host sysfs in the !netns case... the kernel is such a pile of hacks regarding all the namespacing...

my proposal would be to mount /sys from the host in the !netns case and then skip the /sys-as-tmpfs thing from inside the container if we find that /sys is already an fs which reports the SYSFS magic as type... that way i figure your rkt bug will fix itself magically, too...

happy to take a patch for that...

**Comment by alban** [comment]
/cc @iaguis 

Not directly related, but an interesting read about mounting things in user namespace: http://lwn.net/Articles/652468/. It mentions that it's possible to mount sysfs in a user namespace but it does not mention the restriction with the netns.

**Comment by alban** [comment]
I also tested on `v4.1-rc1` and it is reproducible, so it is not caused by [1b852bceb0d1 ("mnt: Refactor the logic for mounting sysfs and proc in a user namespace")](https://github.com/torvalds/linux/commit/1b852bceb0d111e510d1a15826ecc4a19358d512) because that commit is after.

**Comment by dongsupark** [comment]
I've been also curious about why sysfs_mount() has such a limitation. I think it was initially introduced either with ("userns: Restrict when proc and sysfs can be mounted") https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=87a8ebd637dafc255070f503909a053cf0d98d3f or with ("sysfs: Restrict mounting sysfs") https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=7dc5dbc879bd0779924b5132a48b731a0bc04a1e . That's either 3.9 or 3.12, way back from 2013. Though I'd need to dig into discussions in the past to be able to know what was the motivation.
