### ISSUE TITLE
Issue rebooting from ofline-update

### ISSUE THREAD

**Issue by JH-Dak** [systemd/systemd#15567]
I have a strange issue running offline-updates on systemd (241-7~deb10u3 on Debian 10.3).  According to the document, you should reboot after your script completes.  The service file runs the installer script with ExecStart and then has "ExecStartPost=/bin/systemctl reboot".  The installer works and the system reboots, but according to the logs, the systemctrl reboot command fails with this:

... systemctl[3678]: Failed to connect to bus: No such file or directory

Which causes the offline-update process to fail with this:

… systemd[1]: offline-update.service: Control process exited, code=killed, status=15/TERM
… systemd[1]: offline-update.service: Failed with result 'signal'.
… systemd[1]: Stopped Updates the operating system whilst offline.
… systemd[1]: offline-update.service: Triggering OnFailure= dependencies.
… systemd[1]: Requested transaction contradicts existing jobs: Transaction for rescue.target/start is destructive (systemd-reboot.service has 'start' job queued, but 'stop' is included in transaction).
… systemd[1]: offline-update.service: Failed to enqueue OnFailure= job, ignoring: Transaction for rescue.target/start is destructive (systemd-reboot.service has 'start' job queued, but 'stop' is included in transaction).

This all happens after the update has successfully completed, so even though it says it is failing, the failure is during the reboot call, so everything is actually fine.

When I added a systemctl status before the reboot (and a few echo commands around these, just to confirm exactly what was failing), the status command worked just fine but the reboot resulted in the same errors as above.

Am I doing something wrong or is this a possible bug?  What is the proper way to reboot after an offline-update?

**Comment by poettering** [comment]
please provide the precise service definition

**Comment by JH-Dak** [comment]
[Unit]
Description=Updates the operating system whilst offline
OnFailure=rescue.target
Requires=-.mount
After=-.mount
#Requires=network-online.target
#After=network-online.target

[Service]
StandardOutput=journal
StandardError=journal

Type=oneshot

ExecStart=/usr/sbin/fwinstall systemd-do-upgrade
ExecStartPost=/bin/systemctl reboot

**Comment by poettering** [comment]
hmm, is dbus not installed on that system or so? please provide full logs of such a reboot cycle

**Comment by JH-Dak** [comment]
Here is a more simplified .service file with .txt appended so i could attach it (it only removes /system-update) and the resulting journalctl dump (the error is on line 775)

[kaylor-offline-update.service.txt](https://github.com/systemd/systemd/files/4588135/kaylor-offline-update.service.txt)
[dump_03_just_remove_symlink.txt](https://github.com/systemd/systemd/files/4588136/dump_03_just_remove_symlink.txt)

**Comment by poettering** [comment]
For some reason your system enters rescue mode from teh offline update system. Figure out why that is. Will close now as this is a local misconfiguration. For those please contact the systemd mailing list, as this doesn't look like an upstream bug, but mostly like a support issue. Also, this issue is three years old now, so I figure no longer relevant anyway.

Closing.
