### ISSUE TITLE
Problema con OCREND y HTTPS

### ISSUE THREAD

**Issue by manu-89** [systemd/systemd#15576]
Buenas! Estoy con una página desarrollada con el framework OCREND y tengo 2 problemas:

1.- Al acceder a la web con https presenta falla de contenido mixto al invocar los css y js, pero los tengo con URLs relativas, por lo que el error es extraño.

2.- El htaccess está configurado para forzar https y redirección 301 pero no hace nada, lo tengo en la carpeta public_html y el servidor sí tiene las directivas activadas para leerlo.

Esta es la página: https://cotizarobra.com

¿Qué puedo hacer para que siempre dirja las visitas a https y no haya contenido mixto?

Gracias de antemano por su atención.

**Comment by poettering** [comment]
por favor solo haga preguntas aquí en inglés.  su problema no parece tener nada que ver con systemd.  por favor contacte al fabricante de su producto.  gracias por tu comprensión
