### ISSUE TITLE
machinectl pull-raw requires btrfs

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#1559]
18:37 < grift> ]# machinectl pull-raw --verify=no
http://ftp.halifax.rwth-aachen.de/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.raw.xz
18:37 < grift> Failed transfer image: /var/lib/machines is not a btrfs file system. Operation is not supported on legacy file systems.

It fails pretty much immediately. it seems to get attribute of the filesystem mounted on /var/lib/machines and i suppose it uses that info to determine that its not what it wants:

Oct 13 17:41:27 d30 audit[11155]: AVC avc:  denied  { getattr } for  pid=11155 comm="systemd-importd" name="/" dev="dm-6" ino=2 scontext=sys.id:sys.role:sd_importd.subj:s0 tcontext=sys.id:sys.role:fs.fs:s0 tclass=filesystem permissive=1

**Comment by poettering** [comment]
Yeah, i figure import and export should work fine without btrfs really
