### ISSUE TITLE
fido2 support for systemd-homed unlocking?

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#15591]
**Is your feature request related to a problem? Please describe.**
PKCS11 support for hardware tokens is not universally available; whilst FIDO2 is quickly emerging as a modern 'alternative' for public key cryptography through hardware tokens or TPMs. 
https://fidoalliance.org/fido2/

OpenSSH recently also adadopted it for authentication: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f

**Describe the solution you'd like**
We could base support on the https://github.com/shimunn/fido2luks library though maybe something directly in systemd would work as well.

**Describe alternatives you've considered**
None at this point

**Comment by poettering** [comment]
See #15442

**Comment by arianvp** [comment]
Oh wow I spoke too soon.  Github Search only showed issues, not PRs. grrr.  Thanks for the link
