### ISSUE TITLE
MOUSE_WHEEL_CLICK_ANGLE has no effect on trackball

### ISSUE THREAD

**Issue by spydon** [systemd/systemd#15597]
**systemd version the issue has been seen with**
> systemd 245 (245.5-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > arch linux

**Expected behaviour you didn't see**
 > Scroll speed of trackball should change after config change

**Unexpected behaviour you saw**
 > Scroll speed did not change

**Steps to reproduce the problem**
Add
```
# Kensington SlimBlade Trackball
mouse:usb:v047dp2041:name:Kensington Slimblade Trackball:
 MOUSE_WHEEL_CLICK_ANGLE=60
 ID_INPUT_TRACKBALL=1
```
to /usr/lib/udev/hwdb.d/70-mouse.hwdb or a local file.
Run:
`# udevadm hwdb --update && udevadm trigger /dev/input/event24`
(or whatever your correct event id is)
I can see that the values have updated correctly with:
`# udevadm info /dev/input/event24`
Output:

> : /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:047D:2041.006C/input/input155/event24
> N: input/event24
> L: 0
> S: input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-mouse
> S: input/by-id/usb-047d_Kensington_Slimblade_Trackball-event-mouse
> E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/0003:047D:2041.006C/input/input155/event24
> E: DEVNAME=/dev/input/event24
> E: MAJOR=13
> E: MINOR=88
> E: SUBSYSTEM=input
> E: USEC_INITIALIZED=290110531801
> E: ID_INPUT=1
> E: ID_INPUT_MOUSE=1
> E: ID_VENDOR=047d
> E: ID_VENDOR_ENC=047d
> E: ID_VENDOR_ID=047d
> E: ID_MODEL=Kensington_Slimblade_Trackball
> E: ID_MODEL_ENC=Kensington\x20Slimblade\x20Trackball
> E: ID_MODEL_ID=2041
> E: ID_REVISION=0110
> E: ID_SERIAL=047d_Kensington_Slimblade_Trackball
> E: ID_TYPE=hid
> E: ID_BUS=usb
> E: ID_USB_INTERFACES=:030102:
> E: ID_USB_INTERFACE_NUM=00
> E: ID_USB_DRIVER=usbhid
> E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
> E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
> E: ID_INPUT_TRACKBALL=1
> E: **MOUSE_WHEEL_CLICK_ANGLE=10**
> E: LIBINPUT_DEVICE_GROUP=3/47d/2041:usb-0000:00:14.0-2
> E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-mouse /dev/input/by-id/usb-047d_Kensington_Slimblade_Trackball-event-mouse

But there is no change to the scroll speed however I change the value.

#10459 might be related.

**Comment by spydon** [comment]
Labels hwdb and udev should be added.

**Comment by poettering** [comment]
well, we just store stuff in the udev db here, what happens with that data is up to the higher levels of the stack, i.e. libinput or so. this means this issue should be posted against libinput really. @whot can you help @spydon?

**Comment by spydon** [comment]
Alright, thanks. I'll post an issue towards libinput instead.
I added the hwdb entry in #15687 anyways since I already wrote it.
