### ISSUE TITLE
HELP log to syslog

### ISSUE THREAD

**Issue by nicola-lunghi** [systemd/systemd#15609]
Hi,
I have a service (ofono) that prints errors both on syslog and stderr like this

```
#include <syslog.h>

    int option = LOG_NDELAY | LOG_PID | LOG_PERROR;
    openlog("test_log", option, LOG_DAEMON);
    syslog(LOG_INFO, "A different kind of Hello world ... ");

```

and the [Service] section for this service is this

```
[Service]
Type=dbus
BusName=org.ofono
ExecStart=/usr/sbin/ofonod -n
StandardError=null
```
According to the commit message they put the  StandardError=null to avoid to have double logs in /var/log/syslog -> as systemd forward his logs to console as well

Now the problem with this is that I cannot get the logs using systemd journalctl as systemd effectively has no logs for it

How can I fix this? there's a way for systemd to get the logs from /var/log/syslog?
Thanks

**Comment by mbiebl** [comment]
Hi,
this is the systemd bug tracker, not a support forum. Please use the mailing list instead.
