### ISSUE TITLE
build failure with latest glibc head (IPPROTO_MAX is >8 bits)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#15604]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > build complete

**Unexpected behaviour you saw**
 > build failure:
In file included from ../systemd-245/src/basic/macro.h:4,
                 from ../systemd-245/src/basic/alloc-util.h:9,
                 from ../systemd-245/src/shared/conf-parser.h:10,
                 from ../systemd-245/src/network/netdev/fou-tunnel.c:8:
../systemd-245/src/network/netdev/fou-tunnel.c: In function 'config_parse_ip_protocol':
../systemd-245/src/basic/macro.h:380:9: error: static assertion failed: "IPPROTO_MAX-1 <= UINT8_MAX"
  380 |         static_assert(expr, #expr)
      |         ^~~~~~~~~~~~~
../systemd-245/src/network/netdev/fou-tunnel.c:161:9: note: in expansion of macro 'assert_cc'
  161 |         assert_cc(IPPROTO_MAX-1 <= UINT8_MAX);
      |         ^~~~~~~~~

**Steps to reproduce the problem**
build systemd against installed glibc development version, with commit f9ac84f92f151e07586c55e14ed628d493a5929d (Add IPPROTO_ETHERNET and IPPROTO_MPTCP from Linux 5.6 to netinet/in.h.)  applied.

**Comment by keszybz** [comment]
Fixed already on master and in v245.5 in stable: https://github.com/systemd/systemd-stable/commit/c5e346905952fef0f163d91522dd43333f1f219d.
