### ISSUE TITLE
sd-boot: automatically load all drivers in some drop-in dir in the ESP.

### ISSUE THREAD

**Issue by robert-scheck** [systemd/systemd#15617]
I would like to see a reference implementation of an UEFI system driver for a Extended Boot Loader Partition with an ext4 filesystem for systemd-boot as mentioned in https://github.com/systemd/systemd/pull/11701#issuecomment-463997319 – as this would avoid kernel and initramfs on the ESP.

**Comment by poettering** [comment]
There's: https://efi.akeo.ie/

Is that what you are looking after?

(There's one thing we should add to sd-boot: a drop-in dir in the ESP somewhere, where we load everything from. i.e. a place you can drop file system drivers like that, so that they are automatically loaded before we do anything else)

**Comment by robert-scheck** [comment]
> There's: https://efi.akeo.ie/
> 
> Is that what you are looking after?

Yes, thank you. It might be worth to mention this somewhere in the systemd-boot documentation as example.

> (There's one thing we should add to sd-boot: a drop-in dir in the ESP somewhere, where we load everything from. i.e. a place you can drop file system drivers like that, so that they are automatically loaded before we do anything else)

Yes…any chance for an implementation? Because as of writing, I'm not sure how to practically load the UEFI filesystem drivers without manual intervention (via EFI shell) before running systemd-boot, but this might be caused by my lack of UEFI experience.

**Comment by arvidjaar** [comment]
@robert-scheck 

> I'm not sure how to practically load the UEFI filesystem drivers without manual intervention (via EFI shell) before running systemd-boot

Theoretically UEFI standard defines variables `DriverXXXX` and `DriverOrder` which parallel `BootXXXX` and `BootOrder`. Firmware boot manager is required to process all `DriverXXXX` options included in `DriverOrder` before processing any of `BootXXXX` options.

Whether this is actually implemented by vendors is subject to testing.

**Comment by robert-scheck** [comment]
> Whether this is actually implemented by vendors is subject to testing.

Thus I would highly prefer the systemd-boot change for a specified drop-in directory as @poettering suggested.

**Comment by nolange** [comment]
> There's: https://efi.akeo.ie/
> 
> Is that what you are looking after?

Damn, Amiga Filesystem drivers for EFI! That would've been my next rfe for systemd 😂

**Comment by poettering** [comment]
supporting such a drop-in dir that works without mucking with EFI vars would make a ton of sense. I figure the patch would be quite simple even. i.e. just enumerate the dir and do what the EFI shell's "load" command does, i.e. this:

https://github.com/tianocore/edk2/blob/master/ShellPkg/Library/UefiShellLevel2CommandsLib/Load.c

**Comment by AdrianVovk** [comment]
Is there anything we can do to bump this? It would solve a lot of OSTree-related bootloader issues (OSTree really doesn't like operating directly on the ESP)

**Comment by sbpetrack** [comment]
Please PLEASE help a newbie who has been tearing my hair out over this issue for days now. For the time being, until such a directory is implemented, i have the following problem ( and i apologize in advance for describing the issue in the technical equivalent of baby-talk; it's just that I'm the technical equivalent of a baby:)):

I use sd-boot -- loader.conf and an "entries" directory. Both the Physical machine and the virtual one present the systemd boot menu, but only the physical machine maps
