### ISSUE TITLE
Cannot run systemctl disable --now on a template unit

### ISSUE THREAD

**Issue by ondrejbudai** [systemd/systemd#15620]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
 > `systemctl disable --now osbuild-worker@.service` disables and stops all services spawned from a template unit.

**Unexpected behaviour you saw**
 > When I run `systemctl disable --now osbuild-worker@.service`, I got:
 > `Failed to stop osbuild-worker@.service: Unit name osbuild-worker@.service is missing the instance name.
See system logs and 'systemctl status osbuild-worker@.service' for details`
 >
 > I tried running `systemctl disable --now "osbuild-worker@*.service"` and got:
 > `Glob pattern passed to enable, but globs are not supported for this.
Invalid unit name "osbuild-worker@*.service" escaped as "osbuild-worker@\x2a.service".`

**Steps to reproduce the problem**

1) Create a template unit:
```
$ cat /usr/lib/systemd/system/osbuild-worker@.service
[Unit]
Description=OSBuild Composer Worker (%i)
Requires=osbuild-composer.socket

[Service]
Type=simple
ExecStart=/usr/libexec/osbuild-composer/osbuild-worker
```

2) Try disabling it and stopping in one step:
```
systemctl disable --now osbuild-worker@.service
```

I originally discovered this issue when trying to get the `systemd_preun` RPM macro to get working with a template unit. The `systemd_preun` macro uses `systemctl disable --now` which makes it unusable for a template unit.

The workaround I found is to use `systemctl disable` and `systemctl stop` separately like this:
```
systemctl --no-reload disable osbuild-worker@.service
systemctl stop "osbuild-worker@*.service"
```

This issue was originally reported in https://github.com/systemd/systemd/issues/9862 but imho it got accidentally closed.

**Comment by AlexAegis** [comment]
Just to let everyone know, this issue is still around in version 250

**Comment by ferdnyc** [comment]
@scheuref 

`systemctl disable unit@.service` actually _works_ — it's only when the `--now` is added in, that it produces an error. (In either case, it _does_ also disable  all instances of `unit@*.service`, although it doesn't mass _stop_ them even if `--now` is present on the command.)

It's the mass-`stop`, more than the mass-`disable`, functionality that's really the problem. Mass-disabling instantiated templates works fine with `unit@.service`, at least in systemd 253.4:

```console
$ sudo systemctl enable --now akmods@6.2.15-300.fc38.x86_64.service
Created symlink /etc/systemd/system/multi-user.target.wants/akmods@6.2.15-300.fc38.x86_64.service → /usr/lib/systemd/system/akmods@.service.

$ sudo systemctl list-units akmods@\*.service                      
  UNIT                                  LOAD   ACTIVE SUB    DESCRIPTION       >
  akmods@6.2.15-300.fc38.x86_64.service loaded active exited Builds and install>

$ sudo systemctl disable akmods@.service
Removed "/etc/systemd/system/multi-user.target.wants/akmods@6.2.15-300.fc38.x86_64.service".

$ sudo systemctl list-units akmods@\*.service                      
  UNIT                                  LOAD   ACTIVE SUB    DESCRIPTION       >
  akmods@6.2.15-300.fc38.x86_64.service loaded active exited Builds and install>

$ sudo systemctl stop akmods@6.2.15-300.fc38.x86_64.service

$ sudo systemctl list-units akmods@\*.service              
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed. Pass --all to see loaded but inactive units, too.

$ sudo systemctl enable --now akmods@6.2.15-300.fc38.x86_64.service
Created symlink /etc/systemd/system/multi-user.target.wants/akmods@6.2.15-300.fc38.x86_64.service → /usr/lib/systemd/system/akmods@.service.

$ sudo systemctl disable --now akmods@.service
Removed "/etc/systemd/system/multi-user.target.wants/akmods@6.2.15-300.fc38.x86_64.service".
Failed to stop akmods@.service: Unit name akmods@.service is missing the instance name.
See system logs and 'systemctl status akmods@.service' for details.

$ sudo systemctl list-units akmods@\*.service                      
  UNIT                                  LOAD   ACTIVE SUB    DESCRIPTION       >
  akmods@6.2.15-300.fc38.x86_64.service loaded active exited Builds and install>
```

**Comment by ferdnyc** [comment]
This is also unfortunate, because `/usr/lib/systemd/systemd-update-helper` attempts to call `systemctl disable --now` on its arguments whenever its `remove-system-units` subcommand is used. Which means that `/usr/lib/systemd/systemd-update-helper remove-system-units akmods@.service` will return an error, and fail to stop any instantiated units of the template (though it will disable them).

**Comment by GrabbenD** [comment]
Isn't there a better way of disabling services with **wildcard** in 2024?

* `--all` doesn't work for `mask`/`unmask` 
   ```bash
   $ systemctl disable --all 'getty@tty*.service'
   Glob pattern passed to enable, but globs are not supported for this.
   ```

* `--all` wont work for `disable`/`enable` unless `--now` is specified

* Currently this is the only workaround that I've come across:
   ```shell
   $ cd /etc/systemd/system/getty.target.wants && \
     systemctl mask getty@tty*.service
   ```

* _(Sequences are another alternative in this instance. However, wildcards would be cleaner)_
   ```shell
   $ systemctl mask getty@tty{1..9}.service
   ```

**Comment by ferdnyc** [comment]
@GrabbenD You're commenting on a closed issue about something that was already fixed. If you think there are issues with how `--all` is handled, I'd suggest opening a new issue documenting the problems. Commenting here is basically just shouting into the void.
