### ISSUE TITLE
Change Ubuntu CI testing repo to use github instead of salsa.debian.org

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#15625]
**Is your feature request related to a problem? Please describe.**
Problem: the Ubuntu CI tests get their Debian packaging from the systemd repository hosted on salsa.debian.org.

One problem with that is changes to the Debian part of the Ubuntu CI testing have, in the past, been slow to update, due to the repository also being used for normal Debian systemd pacakges.  However, this is better now as a dedicated 'ubuntu-ci' branch has been created that allows updates without affecting the Debian systemd packaging.  However, changes still require someone with commit access to the Debian systemd repository.

Another problem is that the entire Debian git server has gone down today, due to infrastructure problems.  While I think this is rare, and understandable (hardware issues happen), it still adds a point of failure to the Ubuntu CI process.

**Describe the solution you'd like**
While I think it is important for the Ubuntu CI to use a Debian packaging repository that is kept up to date with the main Debian repo, I don't think there is any specific reason that each Ubuntu CI test needs to use the Debian git repo; it probably would be better to create a new dedicated repo or branch just for Ubuntu CI packaging/testing code.  This would be similar to the dedicated systemd-centos-ci repo.

At first I think it just could be a clone of the current Debian 'ubuntu-ci' branch, but having it under upstream systemd control would allow any of the upstream systemd maintainers to modify it as needed.

**Describe alternatives you've considered**
There is no serious problem with the status quo - continuing to use the Debian git repo for the packaging and test code used during Ubuntu CI tests.  However, I think changing the Ubuntu CI tests to use a repo on github under the systemd team's control provides significant advantages.  The main downside that I can see is the github repo will need to be kept up to date with the Debian repo.

**Comment by ddstreet** [comment]
@mbiebl particularly interested in your opinion on this, from the Debian perspective.  I think it would probably make sense to continue keep the Debian ubuntu-ci branch, and just periodically sync/rebase the github-hosted repo, and/or sync between the repos.

@mrc0mmand @evverx @keszybz also interested in your thoughts?

**Comment by mbiebl** [comment]
I guess the problem then is, who would keep the dedicated repo on github updated? If there is someone who is dedicated to do that (longterm), then this would be great.
Obviously, the disconnect between the real Debian package shouldn't be to big

**Comment by ddstreet** [comment]
> I guess the problem then is, who would keep the dedicated repo on github updated? If there is someone who is dedicated to do that (longterm), then this would be great.
> Obviously, the disconnect between the real Debian package shouldn't be to big

yep exactly; it really depends on if the systemd team here would prefer to be able to directly modify the repo, or if it's easier for them to just continue asking me or you to make any changes needed in the repo on salsa.

**Comment by mbiebl** [comment]
Let me add here, that this someone is not going to be me.
What I'm happy to do is give someone besides us (Ubuntu/Debian) access to the Debian repo on salsa to be able to directly commit changes to the ubuntu-ci branch.
That ubuntu-ci branch is actually already showing this problem. It's not automatically updated, so needs manual work now and then. On the other hand, it provides the benefits you outline: you can commit changes which don't (negatively) affect Debian or Ubuntu, so you can add more *experimental* stuff.

**Comment by mbiebl** [comment]
@ddstreet What's your plan here? Who should keep this packaging branch/repo on github up-to-date and how close should it monitor the changes from the "real" Debian packaging?

**Comment by mbiebl** [comment]
Or put it differently:I'm not following the upstream CI too closely, so I'm interested where the current setup has produced problems. Maybe it helps to identify specific issues, to see where we can improve without creating additional work.

**Comment by mrc0mmand** [comment]
> 
> One problem with that is changes to the Debian part of the Ubuntu CI testing have, in the past, been slow to update, due to the repository also being used for normal Debian systemd pacakges. However, this is better now as a dedicated 'ubuntu-ci' branch has been created that allows updates without affecting the Debian systemd packaging. However, changes still require someone with commit access to the Debian systemd repository.

From the *convenience* side a separate GH repository would be an improvement, however, it would further support the *disconnect* between the `ubuntu-ci` branch and the *master* one. So, if you could provide commit access to one or two more people from the upstream to the `ubuntu-ci` branch in the Debian repository, that should, hopefully, be enough to make the changes propagate much faster (basically what @mbiebl proposed).

> 
> Another problem is that the entire Debian git server has gone down today, due to infrastructure problems. While I think this is rare, and understandable (hardware issues happen), it still adds a point of failure to the Ubuntu CI process.

I wouldn't include that into the *decision criteria*, as CentOS CI had the same issues in the recent weeks due to several GitHub outages. So, as you said, these issues are rare and understandable.

**Comment by mbiebl** [comment]
Sorry for the confusion: in my previous replies I meant `upstream-ci`, *not* `ubuntu-ci`
https://salsa.debian.org/systemd-team/systemd/-/tree/upstream-ci

**Comment by ddstreet** [comment]
> @ddstreet What's your plan/idea here? Who should keep this packaging branch/repo on github up-to-date and how close should it monitor the changes from the "real" Debian packaging?

No plan, I just thought it would be worth getting opinions on if upstream should be able to respond more quickly to Ubuntu CI failures or needed changes.  Personally I'm happy with how things are setup now, but I also don't get to focus as much time as I'd like on issues with the ci.

**Comment by ddstreet** [comment]
Ok as I only wanted to bring this up as an option to gather opinions (I should have probably used the mailing list ;-), I'll close this.

**Comment by evverx** [comment]
@ddstreet I'm just spitballing but I think by analogy with Travis CI and Semaphore CI it would be great if we could control what happens on Ubuntu CI by editing a config of some kind kept in the systemd repo. "debian/extra/checkout-upstream" could parse it and pass whatever is set there on. For example, [to install `libzstd-dev` and `zstd`](https://github.com/systemd/systemd/pull/15422#issuecomment-620287078) it would be possible to add something like `build-dependencies: libzstd-dev zstd` right in that PR to the config without bothering anybody.
