### ISSUE TITLE
Not going to servers mentioned at FallbackNTP for systemd-timesynd.service

### ISSUE THREAD

**Issue by alpana17** [systemd/systemd#15644]
I am working on Flatcar OS
My configuration for /etc/systemd/timesyncd.conf is:
[Time]
NTP=169.254.169.123
FallbackNTP=0.flatcar.pool.ntp.org
#RootDistanceMaxSec=5
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048

Here is debug log snapshot:
![image](https://user-images.githubusercontent.com/8611615/80704754-c6d0f580-8b02-11ea-86b3-72936edc2897.png)

My question is:
When it is not able to connect with 169.254.169.123, why is it not going to 0.flatcar.pool.ntp.org??

**Comment by poettering** [comment]
The FallbackNTP= setting (like the FallbackDNS= setting in resolved.conf) configures the servers to use when no other servers can be determined. If there are other servers (like the ones you defined via NTP=) declared then they are ignored.

If you want fallback from one NTP server to another when the first one doesn#t respond then just list them space separated in NTP=. In that case timesyncd will try the first listed one, and then the second and so on. Once it finds one that works it sticks to it.

**Comment by rnestler** [comment]
I also found this confusing from the naming. Especially, since I can't control the `LinkNTPServers` so NTP was broken in a network where the advertised/detected NTP server on the link didn't work.
