### ISSUE TITLE
DBus introspection should support argument names

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1564]
It would be nice if the interfaces were a bit more self-documenting. The current numbered arguments don't make a good impression.

I suppose introspection could even contain [gtk-doc-style comments](http://dbus.freedesktop.org/doc/dbus-api-design.html#documentation) and [annotations](http://dbus.freedesktop.org/doc/dbus-api-design.html#annotations) (such as `org.freedesktop.DBus.Deprecated`)—but this would also create overhead when the introspection data is parsed by clients.

**Comment by poettering** [comment]
dbus interfaces are explicitly not documentation, and i doubt it should carry that.

That said, I am open to allowing people to embed this info, but I couldn't come up with a nice way to do that with the way vtables are currently put together with macros.

Also, I really don't like dbus introspection argument names as they only cover the top-level list of arguments, but a soon as you have any non-trivial arguments is useless as it cannot carry any information about anything inside of structures/array/dictionaries/...

**Comment by poettering** [comment]
Also see #2230

**Comment by poettering** [comment]
Fix pending in #11357
