### ISSUE TITLE
console=ttyS0 causes boot to hang on machines without serial ports

### ISSUE THREAD

**Issue by trapperhoney** [systemd/systemd#15656]
**systemd version the issue has been seen with**
> 245.4-4ubuntu3

**Used distribution**
 > Ubuntu 20.04

**Expected behaviour you didn't see**
 > Successful boot (possibly with failed units)

**Unexpected behaviour you saw**
 > Boot hangs when kernel boot arguments include a serial console, but no serial ports exist.

**Steps to reproduce the problem**
I noticed this problem when upgrading from Ubuntu 19.10 to 20.04 (systemd 242-7ubuntu3.7 to 245.4-4ubuntu3).  The grub configuration on my laptop accidentally contained a line copied from a server to enable serial console output at boot.  Specifically, the options "console=tty0 console=ttyS0,115200n8".  With this additional ttyS0 option, systemd hangs (spinning the CPU) very early in the boot process (my laptop does not have any serial ports, but these options work just fine on a machine that does).  This did not happen in the earlier version and the option was silently ignored.

I was also able to reproduce this issue in QEMU by using the "-serial none" command line flag.

Kernel boot seems to work without issue, and I get to the lines
```
Run /init as init process
systemd-udev[1314]: Starting version 245.4-4ubuntu3
```
After a couple seconds, the CPU fan spins up and the boot process appears to hang.  Eventually a few other kernel messages pop up about initializing the random number generator and high precision event timers, but the boot sequence seems to hang forever.

"systemd.unit=rescue.target" does not work either.  So whichever target is causing this issue is very early in the boot process.

**Comment by poettering** [comment]
any idea what pid 1 s supposed to be spinning on? what does strace say?

I mean, serial output in the kernel is frickin weird. It's synchronous since kernel people want to log to the serial port from interrupt context and such. So I am not surprised things are really weird if you have a serial port that doesn't actually exist....

**Comment by trapperhoney** [comment]
I don't have the exact debugging information you asked for, but I did a bit more poking and have a couple more observations.

First, order of the 'console' boot parameters matters.  The last option is apparently the 'primary' terminal that gets input/output before all of the additional ttys are setup.  This bug only appears to trigger when serial is the primary (eg, the last console argument).  When serial is the non-primary console, the system still comes up.

Next, in order to try to get ptrace output, I tried using init=/bin/bash.  This also does not seem to be early enough in the boot process to prevent the problem.  The kernel's <init_task> seems to do some things before actually running the ultimate pid 1 init process.  In particular, it looks like a shell script runs that among other things seems to start the systemd-udev process.  I think this process might be the one causing the problem.

I was able to attach gdb to the kernel running in qemu under two situations, both with the init=/bash/bin parameter.  One setup puts the consoles in the 'bad' order such that the boot process hangs and one in the 'good' order such that I actually make it to the bash prompt.

Looking at the kernel process list in these two situations there is an interesting observation.  In the 'bad' hung case, the <init_task> kernel thread has spawned 'sh' as pid 1 (not bash), which ultimately spawns systemd-udev, which in turn seems to be hung calling 'loadkeys'

Comparing that to the process list for the 'good' version which does make it to a prompt, the kernel <init_task> has spawned bash as pid 1 and systemd-udev is not in the list (either because it exited or never started in the first place).

So it seems that systemd-udev hanging on loadkeys is the thing that's actually the problem here (I guess I can believe that this wouldn't work if the primary terminal isn't responding? And perhaps whatever calls loadkeys from systemd-udev is the new behavior here).

I don't understand at all, though, how systemd-udev seems to be starting before the 'real' init process of the system.  Does the kernel's init bootstrapping allow for multiple init phases?

(Here are the full process lists in the two states for completeness)
[bash-bad.txt](https://github.com/systemd/systemd/files/4575764/bash-bad.txt)
[bash-good.txt](https://github.com/systemd/systemd/files/4575765/bash-good.txt)

**Comment by poettering** [comment]
Ubuntu uses its own initrd that does not include systemd. They build their own init system with shell scripts. Questionnable idea if you ask me, but that's just me...

Either way, I doubt there's anything we can do here. It appears systemd is not involved here. It's between Ubuntu's initrd, bash, the kernel and loadkeys, neither of which are part of systemd. Hence I think we should close this here...

Bring this up with the ubuntu devs, if this is before systemd becomes PID 1 they really need to maintain this themselves. 

Hope that makes sense.
