### ISSUE TITLE
Reduce output of list-timers

### ISSUE THREAD

**Issue by mb720** [systemd/systemd#15650]
Hi and thanks for systemd!

When calling `systemctl list-timers`, I wish I could limit the output to certain columns. For example, I might be interested only in the values of columns `NEXT` and `UNIT`.

My first hunch was to try `cut` and `awk` but I couldn't find a reliable delimiter between the columns to separate them.

Then, I was hoping to configure the output format of `list-timers`, like it's possible with [`--output`](https://www.freedesktop.org/software/systemd/man/systemctl.html#-o) for journal entries. But this didn't seem to affect the output:

    systemctl list-timers --output=cat

Is there a way to reduce the number of columns shown in `systemctl list-timers`? Maybe using a flag similar to [`--property`](https://www.freedesktop.org/software/systemd/man/systemctl.html#-p) or by making the output machine-readable, then piping it to `awk`.

Thanks for your time!

**Comment by mrc0mmand** [comment]
As for the machine-readability - since https://github.com/systemd/systemd/pull/15701 you can use the json* output modifiers[0] to achieve that:

```
$ systemctl --output=json-pretty list-timers
[
        {
                "next" : 1589485390891904,
                "left" : 1589485390891904,
                "last" : 1589481783203015,
                "passed" : 1589481783203015,
                "unit" : "dnf-makecache.timer",
                "activates" : "dnf-makecache.service"
        },
        {
                "next" : 1589493600000000,
                "left" : 1589493600000000,
                "last" : 1589447147449642,
                "passed" : 1589447147449642,
                "unit" : "mlocate-updatedb.timer",
                "activates" : "mlocate-updatedb.service"
        },
        {
                "next" : 1589493600000000,
                "left" : 1589493600000000,
                "last" : 1589447147388611,
                "passed" : 1589447147388611,
                "unit" : "unbound-anchor.timer",
                "activates" : "unbound-anchor.service"
        },
        {
                "next" : 1589493674578675,
                "left" : 1589493674578675,
                "last" : 1589366318576908,
                "passed" : 1589366318576908,
                "unit" : "systemd-tmpfiles-clean.timer",
                "activates" : "systemd-tmpfiles-clean.service"
        },
        {
                "next" : 1589752800000000,
                "left" : 1589752800000000,
                "last" : 1589148061166495,
                "passed" : 1589148061166495,
                "unit" : "fstrim.timer",
                "activates" : "fstrim.service"
        }
]
```

[0] https://www.freedesktop.org/software/systemd/man/journalctl.html#%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20json%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20

**Comment by poettering** [comment]
Let's close this. I think the JSON stuff is the way to go, and jq a better tool for filtering output then what we could ever add to our native, human readable tabular output. Closing.
