### ISSUE TITLE
Homed - Opt Out

### ISSUE THREAD

**Issue by 4nanook** [systemd/systemd#15658]
I hope that when you implement systemd homed that you allow those of us in server environments who do not wish to participate an easy means to opt out and continue to use our existing functionality.  I have a network that is not homogeneous consisting of Linux and non-Linux machines using NIS for authentication and NFS for home directories and I do not want to have to stay with old Linux, switch to a non systemd version etc, because of your ongoing desire to take over Linux.

**Comment by refi64** [comment]
It's already implemented, and from what I can tell, being mandatory was
never a design goal...

**Comment by keszybz** [comment]
It's fully opt in: you have to create the user using homectl as an administrator.

**Comment by 4nanook** [comment]
Ok, thank you very much.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
Thank you very much.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
