### ISSUE TITLE
Logitech Ultrathin Touch Mouse reports as keyboard to upower

### ISSUE THREAD

**Issue by ralphm** [systemd/systemd#15657]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Ubuntu 20.04

**Expected behaviour you didn't see**
 > Showing up as a mouse with power supply

**Unexpected behaviour you saw**
 > Showing up as a keyboard with power supply

I originally filed an [issue against upower](https://gitlab.freedesktop.org/upower/upower/issues/97) for this. The problem is that this device reports two input devices (in this order): "Ultrathin Touch Mouse Keyboard" (`ID_INPUT_KEYBOARD==1`) and "Ultrathin Touch Mouse" (`ID_INPUT_MOUSE==1`). When upower detects the power supply it looks for the first sibling input device, and if it reports as `ID_INPUT_MOUSE`, it marks the device as a mouse, otherwise it falls back to keyboard.

It was suggested that could be addressed through hwdb. However, it appears that the existing rules for input devices consider the event devices, not the parent input devices. Additionally, according to the available properties shown by `udevadm info` the only difference between the two input devices is the name, and I couldn't find a way to match by vendor and product ids. The following custom udev rule fixes the problem:

```
ACTION=="add|change", SUBSYSTEM=="input", KERNEL=="input*", ATTR{name}=="Ultrathin Touch Mouse Keyboard", ENV{ID_INPUT_MOUSE}="1"
```

**Comment by poettering** [comment]
I figure a new entry for your device here needs to be added:

https://github.com/systemd/systemd/blob/master/hwdb.d/60-input-id.hwdb

i.e. figure out the right modalias string for your device (via `cat /sys/class/input/input$XYZ/modalias`), then prepare a PR that sets ID_INPUT_MOUSE via a hwdb entry in that file matching the modalias you found.

**Comment by poettering** [comment]
(since we lack the hw in question we really need a PR for this, otherwise we cannot fix this. The linked hwdb file has some hints that should help you how to get started with this)

**Comment by hadess** [comment]
Would be great if you could test this: https://github.com/systemd/systemd/pull/15711

**Comment by ralphm** [comment]
As mentioned on #15711, that PR fixes the problem.
