### ISSUE TITLE
If Match is invalid in a .network file, networkd will apply the configuration to all interfaces

### ISSUE THREAD

**Issue by jimfunk** [systemd/systemd#15665]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > openSUSE Tumbleweed

**Expected behaviour you didn't see**
 > configuration not applied to any interface

**Unexpected behaviour you saw**
 > configuration applied to all interfaces found on the system

**Steps to reproduce the problem**

Create a .network file with the following contents (assuming a bridge named "br0" is present):

  [Match]
  Name=this-name-exceeds-ifnamsiz

  [Network]
  Bridge=br0

Restart systemd-networkd.

All interfaces found on the system will have their master set to br0.

**Comment by keszybz** [comment]
We discussed this a number of times in the past, e.g. #12098, and finally a warning was added in 84ea567eb4326eb970a33188649fde6bea2a0d4e. We've had the warning for more than a year now, and three releases. I think we should turn the warning into a hard error now (and not apply such .link/.network files to anything).

**Comment by poettering** [comment]
At the very least we should refuse matching any .network file to a device if it has at least one non-commented line in [Match] but no valid one.

**Comment by yuwata** [comment]
dade7349174765a702ab5cb9e27608ca966c3673 resolves this. Closing.

**Comment by keszybz** [comment]
Oh, indeed.
