### ISSUE TITLE
networkd inside of containers cannot do Driver= matches in .network files, since udev doesn't run in containers

### ISSUE THREAD

**Issue by seirl** [systemd/systemd#15678]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**

When running a container with --network-veth, the host should have an interface `ve-` up and running, thanks to `/usr/lib/systemd/network/80-container-ve.network`. When using `--network-zone`, it should have a `vb-` interface up and running.

Networkctl should show: `ve-... ether    routable    configured` (and `vz-... bridge    routable    configured` when using a network zone)

**Unexpected behaviour you saw**

Networkctl shows: `ve-... ether   off         unmanaged ` (and `vb-... bridge off unmanaged` when using a network zone).

 The host does get an interface, but it is not matched by systemd-networkd and does not get an IP attributed. Removing `Driver=veth` from `/usr/lib/systemd/network/80-container-ve.network` fixes the issue (and `Driver=bridge` from `/usr/lib/systemd/network/80-container-vb.network` when using a network zone).

**Steps to reproduce the problem**

This happens for some reason in nested containers and in virtual machines. When the `ve-` interface is brought up, it doesn't have a `Driver` field (doesn't show any `Driver` field when running `networkctl status ve-...`). The Driver=veth / Driver=bridge condition isn't matched, and the interface doesn't get an IP attributed.

However, when doing `ethtool -i ve-...` I see the following entry: `driver: veth` (`driver: bridge` when using it on a `vb-...` interface), so there is a problem between ethtool and systemd-networkd.

**Comment by poettering** [comment]
I don't get it? You claim `/usr/lib/systemd/network/80-container-ve.network` had `Driver=bridge` set. But it does not, not in the upstream version:

https://github.com/systemd/systemd/blob/master/network/80-container-ve.network#L16

Hence, what's going on?

**Comment by seirl** [comment]
Sorry, I mixed up two different behaviors I'm observing. The first is for `Driver=veth` when using `--network-veth`, the second is for `Driver=bridge` when using `--network-zone`. I cleared things up in the OP.

Basically, when running a systemd-nspawn container inside a container or a VM, there appears to be no driver seen either for `vb-` or `ve-` interfaces

**Comment by poettering** [comment]
we determine the driver of a network device from udev. There's no udev in containers however, hence we simply don't know the driver and can't match against that. 

Not sure what we can do about that.

**Comment by seirl** [comment]
Maybe just remove the `Driver=` filter from the upstream files, or would that be too much of a breaking change?

I'm thinking having both the match on `Name=v{e,b}-*` *and* the low priority should make the matching conservative enough.

**Comment by poettering** [comment]
We could probably read the driver via the ethtool ioctls instead of udev, and things would just work. i really hope the strings reported via both mechanisms are the same though...

**Comment by yuwata** [comment]
If possible, please test PR #16054. Thank you.
