### ISSUE TITLE
FR: Add plugin/module support to homed

### ISSUE THREAD

**Issue by aveao** [systemd/systemd#15671]
**Is your feature request related to a problem? Please describe.**

systemd-homed has some shortcomings, such as the fact that the backends for auth, remote etc need to be supported by systemd itself.

One issue I can think of is the lack of any remotes other than CIFS, however, I do acknowledge that it is unviable to support every single protocol (filesystems and authentication methods) out there, and that's specifically the issue at hand.

**Describe the solution you'd like**

systemd-homed, from what I've seen, aims to simplify and unify some of the changes people often do in PAM, and provide further portability options.

I think that the proper way of implementing all these protocols etc would be to allow some sort of modules to be added to systemd-homed by the user (user as in people who aren't systemd devs), similar to how PAM supports modules.

This way, changes like #15442 could simply be modules for homed.

I'm not sure how this would be tackled from a technical standpoint as I haven't familiarized myself with the systemd-homed codebase. However, this could be done either in the form of scripts, .service-like configuration files (optionally with access to credentials, preferably configurable) or binary modules (likely undesirable).

I can see potential portability concerns, however the alternative of PRing features into systemd would also have the same problems if the portee is running an older systemd.

**Describe alternatives you've considered**

Without support for modules, there's 2 potential alternatives:

- Not using homed, just using PAM
- PRing everything needed into homed

**Comment by poettering** [comment]
The idea of homed is to define a clear way how we set up things, i.e. provide only a limited set of options that make sense and are thought from start to end. Any plug-in interface is philosophically a contradiction to that, as it means you have the same random combination explosion as you had before.

I explicitly don't think FIDO2 should be an afterthought, i.e. an add-on module, a plugin you install. Instead it should be at the core of what we do and how we do stuff these days. 2FA needs to be a built-in default, not  little tested add-on.

homed is not a universal solution, it doesn't aspire to be the exclusive way you manage your home directories. It's supposed to be *one* way, and can live side by side with other approaches, such as NIS, LDAP, winbind or whatnot. And it's great that way. 

Hence, if the choices homed makes for you are not what you want, then build your own solution, let it live side-by-side with homed, it's explicitly supported that way.

Also note homed just implements the userdb API for its users, and logind consumes the userdb API to implement resource mgmt and stuff. If you want your own way to manage users then i recommend to implement the userdb API, it's a simple and a nice add-on for other solutions that manage users, to improve integration with systemd. userdb is documented in a lot of detail here: https://systemd.io/USER_GROUP_API/. 

To say this explicitly: if you are looking for a way to integrate your own user mgmt with systemd, then userdb is the API of choice, it's the API we define for that purpose. Maybe that API you are looking for. Consider homed just one "plug-in" for that API, and build your own if homed is not suitable for you.

Or in other words: most of what homed does is opened up to other packages as well, to reach the same level of integration, via the PAM APIs, the NSS APIs and the userdb APIs. consider homed one implementation of such a solution, implementing all three APIs, but if the offer is not interesting to you then pick another, which can also implement them.

Note that specifically for FIDO2, integration on the level of PAM isn't really a good option. We want to derive crypto keys directly from the device which we can use for the LUKS encryption. i.e. want to do things securely and not just superficially authenticate the user record, but actually securely lock the disk encryption to the FIDO2 device. That makes it much more important for homed to just be the glue between fido2 and luks and not stick PAM or something like that in between.

Anyway, I think there's a misunderstanding what homed is supposed to be. Unlikey for example logind, which manages *all* logins on a system, and thus *is* a universal login manager, homed only strives to manage a subset of users, for those users where that makes sense and thus *is* *not* a universal account manager, but a very specific one, among multiple others.

I hope the above makes sense. Let's close this hence here.
