### ISSUE TITLE
mount point does not umuont when remvoe a disk on v245

### ISSUE THREAD

**Issue by hejiwen** [systemd/systemd#15686]
In Fedora32， systemd version is 245.4-1.fc32

when I remove a disk with 'echo 1 > /sys/block/sdb/device/delete'，the /proc/self/mountinfo still has mount info about this disk，as follows:
/dev/sdb  /mnt  type xfs  (rw,nouuid,nodev,noexec,relatime,seclable)

when I insert this disk with ' echo "- - -" > /sys/class/scsi_host/host2/scan' again， The drive has became sdc.
![systemd_20200504153928](https://user-images.githubusercontent.com/19829014/80945132-b203a300-8e1d-11ea-9eee-38aac2356039.png)

I expected： when remove a disk， the mount point will umount cleanly， when insert again，the drive is still the same drive symbol before remove.

**Comment by poettering** [comment]
you need to add x-systemd.device-bound to your mount options if you want systemd to unmount the thing on unplug. See systemd.mount(5) man page for details.

**Comment by hejiwen** [comment]
Thanks for you comment.
I add a mont point in /etc/fstab with option  x-systemd.device-bound as follows:
UUID=ca7be1f6-dc3c-4865-8d61-c137945a2bf8 /mnt                    xfs     defaults,x-systemd.device-bound 0 0
then exec mount -a,  'echo 1 > /sys/block/sdk1/device/delete',  the mount point hasn‘t removed. 

the mountinfo as follows :
/dev/sdk1 on /mnt type xfs (rw,relatime,attr2,inode64,noquota)

Is there something wrong？
