### ISSUE TITLE
mount point does not umuont when remvoe a disk 

### ISSUE THREAD

**Issue by hejiwen** [systemd/systemd#15680]
In CentOS7.4， systemd version is  219-57.el7.x86_64。

when I remove a disk with 'echo 1  > /sys/block/sdx/device/delete'，the /proc/self/mountinfo still has mount info about this disk，as follows：
1102 62 8:193 / /mnt  rw,noatime shared:1011 - xfs /dev/sdx1 rw,nouuid,attr2,inode64,noquota

when I insert this disk with ' echo "- - -" > 
/sys/devices/pci0000:5d/0000:5d:00.0/0000:5e:00.0/host0/scsi_host/host0/scan
' again， The drive has became sdy.

I expected： when  remove a disk， the mount point will umount cleanly， when  insert again，the drive is still the same drive symbol before remove.

**Comment by poettering** [comment]
As the submission form makes very clear we only track issues in the two most recent upstream versions of systemd here. That's currently v244 and v245. Your version v219 is waaaay to old for that. Please contact your distro instead for help for older versions.

Thank you for understanding!
