### ISSUE TITLE
Bump C language standard to C11?

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#15693]
Thinking about adding some improvements, and C11 would have some nice stuff like atomics and memory barriers that could help implementing simple refcounters.
There are multiple places in `basic/macro.h` testing for C11 that could be simplified as well if this is the baseline.

Compilers supporting C11 appeared recently enough I hope, only if someone wants compatibility with an MS compiler this could be an issue ;)

**Comment by poettering** [comment]
we already use some newer C11 constructs and add minimal compat for older compilers. for example `thread_local` is emulated for older compilers, and our `_noreturn_` can map to either C11 or the gcc extension depending on compuler.

I figure bumping the minimum compiler would be fine as soon as every big distro shipped at least one stable distro version with C11 supported. Are we there yet?

The atomic/memory barrier stuff is not super important for us so far, we only have very little threaded code right now (and we try to avoid it). what precisely do you have in mind where you want to use it?

**Comment by nolange** [comment]
Lazy initialization for one, like this : https://godbolt.org/z/_jdS_K
Simple thread-safe counters aswell. And you could drop all `volatile` from your code, which really is just fitting for HW accesses (naturally it was necessary before the language got atomics)

Note that this ain't introducing threaded-code, but makes code robust for that use.
C11 is supported with gcc-5, timeframe 2012, would be surprised if you find any big linux distro not supporting it

**Comment by Conan-Kudo** [comment]
If we want to go down extreme roads here, even RHEL 6 and SLE 11 have GCC 5 or newer available to build systemd if someone were crazy enough to try. At this point in time, virtually all Linux distributions shipping systemd have a C11-compatible compiler in their latest release.

* Fedora 32: GCC 10
* RHEL 8: GCC 8
* SLE/openSUSE Leap 15: GCC 7
* Ubuntu 20.04: GCC 9
* Debian 10: GCC 8
* Mageia 7: GCC 8
* OpenMandriva Lx 4.1: Clang 9

**Comment by keszybz** [comment]
So it seems there's no reason not to bump it. But we shouldn't just bump it in isolation, but only do it when a change that requires it is introduced.

**Comment by nolange** [comment]
Seems like a chicken egg problem, no one will pick stuff from C11 if the project hasn't adapted it, and nothing **requires** C11. Substitutes like `volatile` instead of `atomic` kinda work by accident.

**Comment by Conan-Kudo** [comment]
Crack the egg and reveal the chicken inside then 😄

**Comment by vcaputo** [comment]
If you've identified places in the codebase that clearly benefit from C11 features, create a PR utilizing them profitably and bumping the compiler flag.

I don't think there's a genuine chicken-egg problem here.

**Comment by poettering** [comment]
yupp, just prep a PR that converts stuff where it would be better to use atomic stuff, add a commit msg that explains the why and we'll review and merge it.

**Comment by keszybz** [comment]
Anyway, let's close this. The consensus is that C11 is a good thing, so a PR which bumps the minimal version *and* makes use of the new features would be very welcome. No need to keep the issue open though.
