### ISSUE TITLE
Incorrect 60-evdev.hwdb entry for T490 trackpad

### ISSUE THREAD

**Issue by ianhi** [systemd/systemd#15694]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > PopOS 20.04

The current entry for the T490 trackpad:

https://github.com/systemd/systemd/blob/b642dfcdc225ee913c0624b23ba3a539ddaf25ce/hwdb.d/60-evdev.hwdb#L524-L529

Was introduced on the basis of a touchpad-edge-detector report from https://gitlab.freedesktop.org/libinput/libinput/issues/402. However, the incorrect touchpad dimensions (78x108 mm) were used with `touchpad-edge-detect`. I measured and found the correct dimensions to be 100x68 mm which is the same as in this [article](https://www.notebookcheck.net/Lenovo-ThinkPad-T490-i7-MX250-Low-Power-FHD-Laptop-Review.421150.0.html) and a later [post](https://gitlab.freedesktop.org/libinput/libinput/issues/402#note_388169) in the same libinput issue. 

This swap of the x and y dimensions results in much faster movement in y than in x. I ran `touchpad-edge-detect 100x68 /dev/input/event5` giving:

```
User-specified touchpad size: 100x68mm
Calculated ranges: 4412/3533

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:SynPS/2 Synaptics TouchPad:dmi:bvnLENOVO:bvrN2IET80W(1.58):bd11/26/2019:svnLENOVO:pn20N2CTO1WW:pvrThinkPadT490:rvnLENOVO:rn20N2CTO1WW:rvrSDK0J40709WIN:cvnLENOVO:ct10:cvrNone:*
 EVDEV_ABS_00=1266:5678:44
 EVDEV_ABS_01=1161:4694:52
 EVDEV_ABS_35=1266:5678:44
 EVDEV_ABS_36=1161:4694:52
```
Changing these values in `/lib/udev/hwdb.d/60-evdev.hwdb` fixed the faster movement in y than in x for me.

Per the gitlab issue cc @whot

**Comment by JohnPucciarelli** [comment]
Thanks for fixing this!
