### ISSUE TITLE
Systemd-homed authentication / PAM settings to use for lightdm

### ISSUE THREAD

**Issue by shadowrylander** [systemd/systemd#15696]
Hello!

Sorry if this isn't the right place to ask, but searching for the solution on Google yielded no tangible results, so I thought I could ask at the source.

I am using the `lightdm display manager`, with the [Aether Theme](https://github.com/NoiSek/Aether), on EndeavorOS / Arch Linux, with the PAM configurations laid out in the Arch Wiki, regarding `nss-auth` and `system-auth`. The service is enabled, as mentioned in the Wiki, though I thought it was a static unit, and I created two LUKS users (non-usb) with `homectl`, providing the `UID` for one of them and not the other, as well as their groups. I can activate them by way of the command line from the default user, created using the os installer, but cannot log in via `lightdm`.

I have seen reports of being able to log in via `GDM`, and was therefore wondering whether only `GDM` supports `homed` users at the moment, if it's something about my PAM configuration, if it's maybe my `lightdm` theme, or something else entirely.

Thank you kindly for the help!

**Comment by vcaputo** [comment]
As you suspected, this isn't the right place to ask, it's not a support forum.

Try asking on the systemd-devel mailing list [0], #systemd on freenode, or whatever support channels your distro provides.

Thanks for understanding!

[0] https://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by shadowrylander** [comment]
Fair enough! Thanks for the pointer!
