### ISSUE TITLE
Denial of write access to /tmp when SMACK is enabled

### ISSUE THREAD

**Issue by again4you** [systemd/systemd#1571]
Denial of write access to /tmp occurs when SMACK is enabled. This is mainly because /tmp is labelled as '_'. In order to resolve this issue, 'smackfsroot=*' option should be specified in tmp.mount file when SMACK is enabled since many non-root processes use /tmp for temporary usage.

**Comment by kaysievers** [comment]
https://github.com/systemd/systemd/pull/1572 is reverted now. This needs a different fix.

**Comment by poettering** [comment]
Yeah, the patch wasn't right, makes sense to revert this. Not sure though how the right fix should look like...

Maybe add a new SmackFileSystemRoot= setting to .mount units, and then set that. This would simply append the "smackfsroot=" option to the mount option string if smack is compiled in and enabled during runtime. This way we'd only have it in the option string, when it's really supported.

Does this make sense, @again4you?

**Comment by again4you** [comment]
@poettering, I agreed with your idea. It supports both smack-enabled and smack-disabled kernel. 
I will submit the patch in this way.
