### ISSUE TITLE
IMPORT{cmdline} is slow

### ISSUE THREAD

**Issue by thesourcehim** [systemd/systemd#15739]
**systemd version the issue has been seen with**
> systemd-245.4-1.fc32.x86_64

**Used distribution**
 > Fedora 32 x86_64

**Expected behaviour you didn't see**
 > The system should boot normally

**Unexpected behaviour you saw**
 > After upgrade to Fedora 32 from 31 I started to face very long boots. Examining the problem closer revealed that for some reason udev rules that contain IMPORT{cmdline} take more time to process than usual. Removing 3 unneeded files made system to boot much faster:
[61-gdm.rules.txt](https://github.com/systemd/systemd/files/4591309/61-gdm.rules.txt)
[64-md-raid-assembly.rules.txt](https://github.com/systemd/systemd/files/4591310/64-md-raid-assembly.rules.txt)
[65-md-incremental.rules.txt](https://github.com/systemd/systemd/files/4591311/65-md-incremental.rules.txt)
There was no such problem in version 243.8 in Fedora 31.
My hardware:
ASUS N56VB laptop
CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
HDD: Samsung SSD 860 EVO 2TB
RAM: 16 GB
There are complaints about this problem on fedora forums from person with similar hardware, so it might be hardware specific. Booting kernels left from Fedora 31 does not help.

**Steps to reproduce the problem**

**Comment by arianvp** [comment]
I think this is the same issue as https://github.com/systemd/systemd/issues/14828 (which should probably be re-opened)

**Comment by thesourcehim** [comment]
I'm not sure if I tested correctly but here's what I did:
1. Created system image using 'mkosi -f -p libzstd.x86_64 -p mdadm -p gdm --password test'
2. Booted the image using 'systemd-nspawn -bi image.raw'
Everything booted fast, so maybe it's fixed on master, though I'm not sure if testing using systemd-nspawn is the correct way in this case.
Btw, add libzstd package for your fedora mkosi build script, the image can not boot without it.

**Comment by arianvp** [comment]
`nspawn` will not exercise the code-paths that made this slow I think.  the slowness was caused by rate-limiting efivarfs access; which isnt mounted in containers

**Comment by thesourcehim** [comment]
Can the image be written to flash drive and booted from it?

**Comment by thesourcehim** [comment]
Ok, I generated new image to include all fedora udev rules that has IMPORT{cmdline}:
mkosi -f -p libzstd.x86_64 -p mdadm -p gdm -p device-mapper-multipath -p kpartx -p biosdevname --password test

I wrote the image to flash drive and booted from it. The boot process until login takes about 30 seconds from flash drive (vs several minutes from SSD with systemd version provided by fedora 32)

**Comment by poettering** [comment]
Fix waiting in #15870.
