### ISSUE TITLE
Failed to fix up PID1 environment

### ISSUE THREAD

**Issue by openmindead** [systemd/systemd#15730]
**systemd version the issue has been seen with**
> 245.r819 onward

**Used distribution**
 > Manjaro

**Expected behaviour you didn't see**
 > Normal boot when SecureBoot is enabled.

**Unexpected behaviour you saw**
 > When SecureBoot is ON, there's the following error:
```
Failed to fix up PID 1 environment: No such file or directory.
Freezing execution.
```
![IMG_20200430_201218](https://user-images.githubusercontent.com/36324977/81197594-d28d5200-9003-11ea-9686-d47bfa6ad3d3.jpg)

**Steps to reproduce the problem**
I observe this since https://github.com/systemd/systemd/pull/15640, which was meant to be a fix for https://github.com/systemd/systemd/issues/14864, but unfortunately it caused a disruptive side-effect described above.
Sadly I couldn't find anything in the journal.

**Comment by openmindead** [comment]
There's a screenshot with a bit more details but that's all:
![IMG_20200512_212229](https://user-images.githubusercontent.com/36324977/81687117-37312c80-949c-11ea-872d-2c14e050ed2f.jpg)

**Comment by keszybz** [comment]
What's up with github? It sees the link in the commit, and in the PR it highlights "fix", but there's no link from 'linked pulled requests' above.

**Comment by keszybz** [comment]
@openmindead I'd appreciate a confirmation that #15868 works for you.

**Comment by openmindead** [comment]
> @openmindead I'd appreciate a confirmation that #15868 works for you.

Yes it works!
Dzięki za poprawkę!
