### ISSUE TITLE
IdleAction=lock Not working in Debian and ubuntu

### ISSUE THREAD

**Issue by polampalliarchana** [systemd/systemd#15738]
systemd -241
debian-buster
linux-4.19.0-5-amd64

i have one security requirement is system should get lock  when it is idle for 5min.so i have configured /etc/systemd/logind.conf file with
IdleAction=lock
IdleActionSec=5min

and i left my system idle for more than 20 min,but system  is not getting locked,lock action is not working.
I need this requirement urgently ,How can i slove this problem,

Regards
Archana 

**systemd version the issue has been seen with**
> ...systemd - 241

**Used distribution**
 > …Debian and Ubuntu

**Expected behaviour you didn't see**
 > …System should get lock if it is idle for more than 5min

**Unexpected behaviour you saw**
 > …system is not locking

**Steps to reproduce the problem**
1.open /etc/systemd/logind.conf fileand enable  IdleAction and IdleActionSec .
change idleaction=ignore to idleAction=lock
$vim /etc/systemd/logind.conf
IdleAction=lock
IdleActionSec=5min
2.Restart systemd-logind service
$systemctl restart systemd-logind.service
3.left sysem idle for 5min or 10min and observe
It should get lock,but not locking

**Comment by mbiebl** [comment]
You asked the same question on the mailing list [1], where @poettering told you, that this is basically an issue of the desktop environment being hooked up properly to logind.

I'm not sure what you expect from reposting this question via the bug tracker and I'm inclined to closed this bug report.

[1] https://lists.freedesktop.org/archives/systemd-devel/2020-May/044495.html

**Comment by polampalliarchana** [comment]
he just told 'Not all DEs support the looking logic and simply ignore' i
want to to which  DEs doesn't support . and he asked me what is  my desktop
environment ,  i am using gnome DE.i want to know gnome DE does support
locking logic.why are hesitating to answer my question.i have asked few
more question  i think you have already seen that ,

please tell me does this IdleAction=lock work in Gnome DE

Regards
Archana

**Comment by mbiebl** [comment]
But this a bug tracker, not a support forum.

**Comment by polampalliarchana** [comment]
Ok thank you,

**Comment by poettering** [comment]
let's close this here, and leave the thread on the ML.
