### ISSUE TITLE
RestrictAddressFamilies should support "no address families"

### ISSUE THREAD

**Issue by mrmonday** [systemd/systemd#15753]
[RestrictAddressFamilies](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RestrictAddressFamilies=) currently supports:

 * Whitelisting address families eg. `RestrictAddressFamilies=AF_INET` for "only `AF_INET`"
 * Blocklisting address families eg. `RestrictAddressFamilies=~AF_INET` for "everything but `AF_INET`"
 * Allowing all address families eg. `RestrictAddressFamilies=`

Without listing every single address family, it is not possible to explicitly say "block all address families".

I would suggest `RestrictAddressFamilies=yes` for this, to be consistent with other options.

I believe this can currently be worked around by `SystemCallFilter=~socket`, but it would be nice to support this separately.

**Comment by daoo** [comment]
Does whitelisting and then blacklisting the same address family provide a workaround for blacklisting all families? Example:
```
RestrictAddressFamilies=AF_UNIX
RestrictAddressFamilies=~AF_UNIX
```
When I tried it at least `systemd-analyze security` reports all families as blocked:
```
> systemd-analyze security example | grep RestrictAddressFamilies
✓ RestrictAddressFamilies=~AF_(INET|INET6)                    Service cannot allocate Internet sockets
✓ RestrictAddressFamilies=~…                                  Service cannot allocate exotic sockets
✓ RestrictAddressFamilies=~AF_PACKET                          Service cannot allocate packet sockets
✓ RestrictAddressFamilies=~AF_NETLINK                         Service cannot allocate netlink sockets
✓ RestrictAddressFamilies=~AF_UNIX                            Service cannot allocate local sockets
```

**Comment by Hendrikto** [comment]
Any update on this? I would be willing to implement this.

**Comment by yuwata** [comment]
Waiting in #19340.
