### ISSUE TITLE
RFE: we should move the `systemctl reboot` positional argument into a switch `--reboot-arg=`

### ISSUE THREAD

**Issue by Trumeet** [systemd/systemd#15773]
**Is your feature request related to a problem? Please describe.**
I'm using systemd to manage services on both my servers and desktops. Although I used systemd for quiet a long time, I still often confused (mistyped) the command `systemctl restart` and `systemctl reboot`, and this happened lots of times on my server when **I just wanted to restart a service but I accidentally restarted the whole machine**, which is really distracting. 

**Describe the solution you'd like**
My modest solution is, to prompt for error if the arguments for `systemctl reboot` is incorrect. This will definitely help me when I mistyped the command. For example:
```
$ systemctl reboot systemd-networkd
Unrecognized argument: systemd-networkd
```

**Describe alternatives you've considered**
Either the command `reboot` or `restart` could also be renamed to avoid confusion, but it has greater impacts on users comparing to an error prompt. 

I'm looking for this feature and your replies. Thanks.

**Comment by poettering** [comment]
The argument to "systemctl reboot" is passed to the kernel reboot() syscall, where it is passed to the firmware to pick specific modes of rebooting. We can't validate it sensibly, it's a free-form string for us, that only the firmware can understand.

Looking back, given that this is quite an exotic feature (only use on some archs) I figure we should have hidden it in some command line switch `--reboot-arg=` or so to `systemctl reboot`, but that would be quite a compatibility break now. And I am not sure it's worth breaking this.

This is documented in the systemctl man page btw...

**Comment by Trumeet** [comment]
Thanks for your reply! I had just heard that as well, so it may not be the best solution... Maybe we could add an interactive warning if user is rebooting from shell... Anyways, thanks for your support!

**Comment by keszybz** [comment]
I think adding `systemctl reboot --reboot-arg=` and deprecating the version with a positional argument and warning about it would be OK. Then at some point we can either remove support for it or only make it opt-in.

I guess it depends on the ratio between the number of people who are confused by this and the number of people who are using `reboot` with an argument.

**Comment by poettering** [comment]
sounds ok by me. happy to review a PR for that ;-)

**Comment by layderv** [comment]
I've pushed a commit to fix this issue. Is this what you had in mind? https://github.com/systemd/systemd/pull/15958
I looked at the code and documentation to make this change. If it's not correct, can you point me to the right direction?

**Comment by layderv** [comment]
We can close this or we can leave it open to force the use of `--reboot-argument`. In how many versions should I make that change?

**Comment by keszybz** [comment]
Let's close this. I'd wait at least a year before removing the old syntax.

**Comment by KexyBiscuit** [comment]
@keszybz it has been nearly three years, should we remove the old syntax now? :-)
