### ISSUE TITLE
Can't display anymore memory usage with `systemctl status service`

### ISSUE THREAD

**Issue by AlphaJack** [systemd/systemd#15772]
This problem occurs with every service, it worked fine until the last updates. I've already tried setting `DefaultMemoryAccounting=yes` in /etc/systemd/system.conf and then running `sudo systemctl daemon-reexec`, but it doesn't work, unlike uncommenting other settings like `DefaultCPUAccounting=yes` which show changes.

**systemd version the issue has been seen with**
>  245.5-2

**Used distribution**
 > Arch Linux ARM

**Expected behaviour you didn't see**
> Memory information
```
* ddclient.service - Dynamic DNS Update Client
     Loaded: loaded (/usr/lib/systemd/system/ddclient.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-05-05 11:07:40 CEST; 5 days ago
   Main PID: 473 (ddclient - slee)
      Tasks: 1 (limit: 2172)
     Memory: 2.5M
     CGroup: /system.slice/ddclient.service
             `-473 ddclient - sleeping for 3290 seconds
```

**Unexpected behaviour you saw**
> No memory information
```
* ddclient.service - Dynamic DNS Update Client
     Loaded: loaded (/usr/lib/systemd/system/ddclient.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-05-05 11:07:40 CEST; 5 days ago
   Main PID: 473 (ddclient - slee)
      Tasks: 1 (limit: 2172)
     CGroup: /system.slice/ddclient.service
             `-473 ddclient - sleeping for 3290 seconds
```

**Steps to reproduce the problem**
`systemctl status service`

**Comment by poettering** [comment]
What does "systemctl show" show for this unit? in particular for the MemoryAccounting property?

**Comment by AlphaJack** [comment]
<details> 
<summary>systemctl show ddclient</summary>
<pre>Type=forking
Restart=no
PIDFile=/run/ddclient.pid
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
TimeoutAbortUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=473
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
ReloadResult=success
CleanResult=success
UID=[not set]
GID=[not set]
NRestarts=0
OOMPolicy=stop
ExecMainStartTimestamp=Tue 2020-05-05 11:07:40 CEST
ExecMainStartTimestampMonotonic=59761566
ExecMainExitTimestampMonotonic=0
ExecMainPID=473
ExecMainCode=0
ExecMainStatus=0
ExecStart={ path=/usr/bin/ddclient ; argv[]=/usr/bin/ddclient ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartEx={ path=/usr/bin/ddclient ; argv[]=/usr/bin/ddclient ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
ControlGroup=/system.slice/ddclient.service
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
EffectiveCPUs=
EffectiveMemoryNodes=
TasksCurrent=1
IPIngressBytes=[no data]
IPIngressPackets=[no data]
IPEgressBytes=[no data]
IPEgressPackets=[no data]
IOReadBytes=18446744073709551615
IOReadOperations=18446744073709551615
IOWriteBytes=18446744073709551615
IOWriteOperations=18446744073709551615
Delegate=no
CPUAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
CPUQuotaPeriodUSec=infinity
AllowedCPUs=
AllowedMemoryNodes=
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=yes
DefaultMemoryLow=0
DefaultMemoryMin=0
MemoryMin=0
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=2172
IPAccounting=no
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=infinity
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=524288
LimitNOFILESoft=1024
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=7241
LimitNPROCSoft=7241
LimitMEMLOCK=65536
LimitMEMLOCKSoft=65536
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=7241
LimitSIGPENDINGSoft=7241
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
OOMScoreAdjust=0
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
CPUAffinity=
CPUAffinityFromNUMA=no
NUMAPolicy=n/a
NUMAMask=
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
LogRateLimitIntervalUSec=0
LogRateLimitBurst=0
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read
AmbientCapabilities=
DynamicUser=no
RemoveIPC=no
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectClock=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectKernelLogs=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
PrivateMounts=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
LockPersonality=no
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=0755
ConfigurationDirectoryMode=0755
TimeoutCleanUSec=infinity
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
MountAPIVFS=no
KeyringMode=private
ProtectHostname=no
KillMode=control-group
KillSignal=15
RestartKillSignal=15
FinalKillSignal=9
SendSIGKILL=yes
SendSIGHUP=no
WatchdogSignal=6
Id=ddclient.service
Names=ddclient.service
Requires=system.slice sysinit.target
WantedBy=multi-user.target
Conflicts=shutdown.target
Before=multi-user.target shutdown.target
After=systemd-journald.socket sysinit.target system.slice basic.target network.target
Description=Dynamic DNS Update Client
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/usr/lib/systemd/system/ddclient.service
UnitFileState=enabled
UnitFilePreset=disabled
StateChangeTimestamp=Tue 2020-05-05 11:07:40 CEST
StateChangeTimestampMonotonic=59761740
InactiveExitTimestamp=Tue 2020-05-05 11:06:34 CEST
InactiveExitTimestampMonotonic=52940565
ActiveEnterTimestamp=Tue 2020-05-05 11:07:40 CEST
ActiveEnterTimestampMonotonic=59761740
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Tue 2020-05-05 11:06:34 CEST
ConditionTimestampMonotonic=52928450
AssertTimestamp=Tue 2020-05-05 11:06:34 CEST
AssertTimestampMonotonic=52928456
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=d9f90546b24f4c06aad9f020243c9ea6
CollectMode=inactive
</pre>
</details>

**Comment by poettering** [comment]
so, that looks pretty ok. please acquire an "strace" log when doing "systemctl status" on the service. i.e. in one terminal do: `strace -p1 -s 500 -o log". Then in another terminal issue the "systemctl status" command, and then hit C-c in the first terminal. Please attach resulting log file `log` here.

Is there anything in the logs?

If you turn on debug logging right before starting that service, is there anything interesting in the logs then? (`systemd-analyze log-level debug`)

**Comment by AlphaJack** [comment]
I would also like to point out that another computer with Manjaro x64 and `systemd` 245.5-2 correctly returns the memory usage. In this computer `/etc/systemd/system.conf` file the "#DefaultMemoryAccounting=yes" is commented.

[log.txt](https://github.com/systemd/systemd/files/4621182/log.txt)

The memory usage is not specific for `ddclient`, every service doesn't display it.

**Comment by poettering** [comment]
This line is interesting:

```
read(31, "9:devices:/init.scope\n8:perf_event:/\n7:net_cls,net_prio:/\n6:cpuset:/\n5:cpu,cpuacct:/\n4:blkio:/\n3:pids:/init.scope\n2:freezer:/\n1:name=systemd:/init.scope\n0::/init.scope\n", 1024) = 168
```

i.e. it's the list of cgroup controllers your kernel supports: devices, perf_event, net_cls, net_prio, cpuset, cpu, cpuacct, blkio, pids, freezer. And that's it. no "memory".

Hence, this feature appears to be turned off in your kernel. Please contact your distro for help about this, i.e. why they turned off the memory cgroup controller in the kernel.

**Comment by AlphaJack** [comment]
Thank you, then it's probably due to the recent switch from linux-rasperrypi 4.19 to version 5.4.

**Comment by AlphaJack** [comment]
Fixed by adding 
```
cgroup_enable=memory cgroup_memory=1
``` 
to `/boot/cmdline.txt`

**Comment by hobbes1069** [comment]
Just found this after struggling with a RPi chromium Kiosk w/ heavy JS and a slow memory leak. Any fix coming to Raspbian?

**Comment by mbiebl** [comment]
> Just found this after struggling with a RPi chromium Kiosk w/ heavy JS and a slow memory leak. Any fix coming to Raspbian?

you might ask the raspbian maintainers about this.
