### ISSUE TITLE
Possible race condition when service restarts itself through systemd

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#15775]
**systemd version the issue has been seen with**
> 241

I would like to try a new systemd version to eliminate that the bug might have been fixed upstream. Do you remember fixing something around this problem recently?

**Used distribution**
 > Raspberry Pi Debian

**Expected behaviour you didn't see**
 > I am debugging an application which tries to update itself. Application restarts itself through "systemctl restart" but the new application never starts. Before executing systemctl, application renames its file and download file. Once this is over, it calls "systemctl restart" synchronously and then exits the program. 

I have seen few times that the old application shuts itself down but the new one never starts. I can see on the logs that right after my service says good bye, systemd prints "Successful" message for the service but the new one is not there.

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

**Comment by poettering** [comment]
I don't get it? a service issues a synchronous restart on itself? that's gonna deadlock? i don't get it?

**Comment by utezduyar** [comment]
It seems like it is NOT sync. It is golang that I had to look at the API. 

```go
log.Infof("Trigger manager to restart new instance")
cmd := exec.Command("/bin/systemctl", "restart", "sitecontroller")
err = cmd.Start() // This is a background job.
log.Infof("Closing old instance, letting service manager start new instance")
logger.Close()
os.Exit(0)
```

And the logs are:

```
systemd[1]: sitecontroller.service: Succeeded.
sitecontroller_linux_arm7[306]: 2020-05-08 06:24:43.717378177 +0000 UTC INFO sitecontroller/autoupdates/autoupdate(426): Closing old instance, letting service manager start new instance
sitecontroller_linux_arm7[306]: 2020-05-08 06:24:43.70559438 +0000 UTC INFO sitecontroller/autoupdates/autoupdate(418): Trigger manager to restart new instance
```

I assumed systemd[1]'s message "Succeeded" was for restarting but maybe not.

Can it be that systemd never receives the "restart" job? 

What would be a better way of self updating? The old program `exec` ing the new one? Old one exiting and letting system restart the new one due to Restart=always? 

Thank you for your answer.

**Comment by poettering** [comment]
invoking `systemctl` without `--no-block` means you start systemctl that synchronously waits for the job to complete. But restarting a service means stopping then starting a service. So this systemctl invocation will necessarily be aborted midway since for the restart job to complete it needs to be stopped itself. Use `--no-block` to enqueue a restart if that's everything you want.

I can't tell you what went through and what didn't. consider turning on debug logs and see what actually happens, i.e. what request is received by pid 1 and what it does. i.e run "systemd-analyze log-level debug" before you do things.

**Comment by utezduyar** [comment]
Seems like "--no-block" needs to be combined with synchronous execution. I will try it. Closing the bug report since it is most likely due to our implementation. If I stumble on the problem, i will post a new bug report with systemd logs.
