### ISSUE TITLE
Provide ability to configure systemd to not listen to audit messages

### ISSUE THREAD

**Issue by nickbroon** [systemd/systemd#15777]
**Is your feature request related to a problem? Please describe.**
#959 was fixed (via #15444) so systemd could be configured to not unconditionally enable the generation audit messages on startup. But it still unconditionally listens for audit messages. Which means that if some other software is being used to enable/collect audit messages, systemd will also receive and log them, which may not be desired.

**Describe the solution you'd like**
An ability to configure systemd not to listen to audit messages.

**Describe alternatives you've considered**
If I mask `systemd-journald-audit.socket` I see the following warnings in the journal:
```
Dec 02 17:03:43 vm-1 systemd[1]: systemd-journald-audit.socket: Cannot add dependency job, ignoring: Unit systemd-journald-audit.socket is masked.
Dec 02 17:03:45 vm-1 systemd[1]: systemd-journald-audit.socket: Cannot add dependency job, ignoring: Unit systemd-journald-audit.socket is masked.
Dec 02 17:03:45 vm-1 systemd[1]: systemd-journald-audit.socket: Cannot add dependency job, ignoring: Unit systemd-journald-audit.socket is masked.
Dec 02 17:03:45 vm-1 systemd[1]: systemd-journald-audit.socket: Cannot add dependency job, ignoring: Unit systemd-journald-audit.socket is masked.
```
Can these be safely ignored?

**Comment by poettering** [comment]
yes, they can be safely ignored.

**Comment by nickbroon** [comment]
Links:
Patch SUSE use to disable audit completely: https://github.com/openSUSE/systemd/commit/14771d697a159f46ecc723d41b113437a046a6f6
Debian PR proposing the same: https://salsa.debian.org/systemd-team/systemd/-/merge_requests/86
Patch RHEL previously used to also disable audit: https://github.com/lnykryn/systemd-rhel/commit/5dee07f71ccaf8eacd115e01e665c645f7c3a75d

All just completely disable audit support. Making it a configurable option would probably be preferable to allow system builders to choose.

**Comment by poettering** [comment]
hmm, i guess this would be ok to do.

But could you please make three additions:

1. update the man page of journald, add a quick sentence somewhere where we say we read from audit, indicating that this depends on whether `systemd-journald-audit.socket` is enabled.

2. Also in the man page of journald.conf, near Audit= explanation say it only has an effect if the socket unit is enabled.

3. if journald initializes, I think it would be good to output a quick informational string saying whether audit logging is on or not.

**Comment by floion** [comment]
Hi @poettering , quick questions here. What will systemd typically log to journald if auditing is enabled in the kernel?

**Comment by floion** [comment]
The reason I am asking is that from what I can tell, journald would log the messages defined in rules of other auditing tools, such as for example when defining a rule with `auditctl` then journald would also log those messages filtered by the auditctl rule, but also additionally, if no rule is set with auditctl then journald would still log some audit messages every 60 seconds or so, thus filling up the journal with logs that may not be desired.
