### ISSUE TITLE
networkd: wireguard ListenPort not set without configured WireGuardPeer-s

### ISSUE THREAD

**Issue by yaneti** [systemd/systemd#15786]
**systemd version the issue has been seen with**
systemd-245.4-1.fc32.x86_64

**Expected behaviour you didn't see**
When there are no configured WireGuardPeers, the ListenPort directive is not applied to the interface

As to why one might want to do that. Its plausible that peer configuration is dynamic and managed outside networkd, but the port should still be static

**Comment by conqp** [comment]
I just stumbled over this issue as well [1].
As a workaround I added a dummy peer with just a public key specified and destroyed the corresponding private key.
However, this feels like a dirty hack and I'd also appreciate native support of WG interfaces without initially configured peers.

[1] https://bbs.archlinux.org/viewtopic.php?id=256047

**Comment by yuwata** [comment]
Fix is waiting in #16029. If possible, please test the PR.
