### ISSUE TITLE
when I add a user named user1,journal will record user1's log to  user-1000.journal ,then delete user1 and add user2, user2 can read user1's journal?

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#15802]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 >243

**Expected behaviour you didn't see**
 > user-1000.journal will be vaccummed after user2 logins.

**Unexpected behaviour you saw**
 >user2‘s journal appends user1’s log

**Steps to reproduce the problem**
add a user named user1,journal will record user1's log to user-1000.journal ,then delete user1 and add user2, user2 can read user1's journal.

**Comment by poettering** [comment]
yes, on traditional unix you cannot safely return UIDs to the system, they can be reused and any files owned or accessible to those users are up for grabs for any new user with the recycled UID.

**Comment by mbiebl** [comment]
@fayeinseu which tool did you use to delete `user1`? Maybe that tool can be taught to delete user journals (some tools already provide the option to delete the home directory when deleting a user)

**Comment by poettering** [comment]
Yeah, I would agree here, this is generally a problem with anything that maintains resources on behalf of the user. Like for example per-user cronjobs, which aren't cleaned up either automatically when a user is deleted, but require some extra hook-up in deluser. 

I don't think there's anything actionable here... let's close this.

**Comment by fayeinseu** [comment]
userdel. @mbiebl

**Comment by fayeinseu** [comment]
Thanks！I agree with you.
