### ISSUE TITLE
systemd: systemd --user and AmbientCapabilities throw EPERM

### ISSUE THREAD

**Issue by nhooyr** [systemd/systemd#15811]
**systemd version the issue has been seen with**
systemd 241 (241)

**Used distribution**
 Debian 10

**Expected behaviour you didn't see**
The service starts as expected

**Unexpected behaviour you saw**
 Starting the service throws (in my case named code-server):
```
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: Starting test...
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[12402]: test.service: Failed to apply ambient capabilities (before UID change): Operation not permitted
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[12402]: test.service: Failed at step CAPABILITIES spawning /bin/true: Operation not permitted
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: test.service: Main process exited, code=exited, status=218/CAPABILITIES
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: test.service: Failed with result 'exit-code'.
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: Failed to start test.
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: test.service: Service RestartSec=100ms expired, scheduling restart.
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: test.service: Scheduled restart job, restart counter is at 4.
May 14 09:21:44 xayah.us-central1-a.c.nhooyr-coder.internal systemd[750]: Stopped test.
```

**Steps to reproduce the problem**
```
[Unit]
Description=test
After=network.target

[Service]
Type=exec
ExecStart=/bin/true
Restart=always
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

Add the above as a systemd user service and then start it.

**Comment by poettering** [comment]
The issue submission form makes very clear that this is a bug tracker only for the two most recent upstream versions for systemd. For everything else, please talk to your downstream.

241 is too old. we are at v244 + v245 these days.

There has been plenty of work going into the caps/ambient code, hence please reopen if reproducible on current systemd.

**Comment by nhooyr** [comment]
Thanks for the quick reply. Sorry about, should have read the template more thoroughly.

**Comment by akostadinov** [comment]
I observe this with `systemd-255.10-3.fc40.x86_64`, I see now latest version is 256 so I guess that counts.
