### ISSUE TITLE
systemd-nspawn incorrectly parsed mountpoints when SELinux options -L or -Z containing commas

### ISSUE THREAD

**Issue by amessina** [systemd/systemd#15822]
**systemd version the issue has been seen with**
> systemd 245 (v245.4-1.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Fedora 32 x86_64

**Expected behaviour you didn't see**
 > systemd-nspawn handles SELinux labels with commas

**Unexpected behaviour you saw**
 > The comma seems to be parsed as a separate mountpoint option rather than one string to be set as something like `"mode=1777,uid=277413888,gid=277413888,context="system_u:object_r:systemd_nspawn_file_t:s0:c77,c78""`

> SYSTEMD_LOG_LEVEL=debug /usr/bin/systemd-nspawn --boot --link-journal=try-guest --settings=override --machine=fedora -L system_u:object_r:systemd_nspawn_file_t:s0:c77,c78 -Z system_u:system_r:systemd_nspawn_t:s0:c77,c78
Setting RLIMIT_CPU to infinity.
Setting RLIMIT_FSIZE to infinity.
Setting RLIMIT_DATA to infinity.
Setting RLIMIT_STACK to 8388608:infinity.
Setting RLIMIT_CORE to 0:infinity.
Setting RLIMIT_RSS to infinity.
Setting RLIMIT_NPROC to 127864.
Setting RLIMIT_NOFILE to 1024:4096.
Setting RLIMIT_MEMLOCK to 65536.
Setting RLIMIT_AS to infinity.
Setting RLIMIT_LOCKS to infinity.
Setting RLIMIT_SIGPENDING to 127864.
Setting RLIMIT_MSGQUEUE to 819200.
Setting RLIMIT_NICE to 0.
Setting RLIMIT_RTPRIO to 0.
Setting RLIMIT_RTTIME to infinity.
Settings are trusted: yes
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Spawning container fedora on /var/lib/machines/fedora.
Press ^] three times within 1s to kill container.
Outer child is initializing.
Mounting / (MS_REC|MS_SLAVE "")...
Selected user namespace base 277413888 and range 65536.
Bind-mounting /var/lib/machines/fedora on /var/lib/machines/fedora (MS_BIND|MS_REC "")...
Found libsystemd shared at "/var/lib/machines/fedora/lib/systemd/libsystemd-shared-245.so", version 245 (OK).
Using unified hierarchy for container.
Mounting /var/lib/machines/fedora (MS_REC|MS_SHARED "")...
Root directory of image is already owned by the right UID/GID range, skipping recursive chown operation.
Mounting tmpfs on /var/lib/machines/fedora/tmp (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777,uid=277413888,gid=277413888,context=system_u:object_r:systemd_nspawn_file_t:s0:c77,c78")...
Failed to mount tmpfs (type tmpfs) on /var/lib/machines/fedora/tmp (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777,uid=277413888,gid=277413888,context=system_u:object_r:systemd_nspawn_file_t:s0:c77,c78"): Invalid argument
(sd-namespace) failed with exit status 1.

**Steps to reproduce the problem**
```
SYSTEMD_LOG_LEVEL=debug /usr/bin/systemd-nspawn --boot --link-journal=try-guest --settings=override --machine=fedora -L system_u:object_r:systemd_nspawn_file_t:s0:c77,c78 -Z system_u:system_r:systemd_nspawn_t:s0:c77,c78
```

The same occurs when using these options in a systemd-nspawn@.service unit.  Replacing the `,` with `.` works, but creates inclusive SELinux category ranges, rather than groups, reducing the number of SELinux separated containers that can be run.

It should also be noted that using `.` in the command line or nspawn template unit file results in the following (mounted with commas) in the machine:
```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,context="system_u:object_r:systemd_nspawn_file_t:s0:c77,c78",uid=277413888,gid=277413888)
```

**Comment by cgzones** [comment]
Maybe [`extract_first_word`](https://github.com/systemd/systemd/blob/a51a3247e5bb36e375eb750b78fabcdff8601378/src/shared/mount-util.c#L624) shouldn't be called with option `EXTRACT_UNQUOTE` to allow quoted mount arguments, see **mount**(8) option `context=`
