### ISSUE TITLE
ACPI reports lid state, but systemd/logind isn't detecting it

### ISSUE THREAD

**Issue by JamesSwift** [systemd/systemd#15832]
**systemd version the issue has been seen with**

    systemd 245 (245.4-4ubuntu3pop0~1588265185~20.04~3ec71c3) +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Pop 20.04

**Expected behaviour you didn't see**
 > Closing the laptop lid didn't trigger the sleep action. I have checked that it is enabled in gnome.

**Unexpected behaviour you saw**
`/proc/acpi/button/lid/LID0/state` shows the correct lid state. 
If I use `acpi_listen` however, I get the following unusual output, which may be why systemd isn't properly detecting the action.

```
676AA15E-6A47- 000000bc 00000000
676AA15E-6A47- 000000bc 00000000
```

**Steps to reproduce the problem**
Close the lid. Screen remains on.

**Notes**
I am using an `acer switch 11v sw5-173` detachable laptop/tablet. I am happy to provide any other logs to help diagnose, please just ask.

**Comment by poettering** [comment]
So, systemd-logind watches the state of any SW_LID switch on any input device. it does not watch acpi directly, but only through the input device the acpi subsystem exposes. Check if that reports things properly.

Also, logind exposes the state of the lid switch as it detected it itself as dbus property. you can query it like this:

```
busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager LidClosed
```

It might be worth checking out if that property follows the state of the lid correctly.

logind requires drivers to work correctly. if they don't, please report this to the driver maintainers instead.

**Comment by poettering** [comment]
also, note that desktop apps/environments can install "inhibitors" to block handling of such input events or the operations resulting from them. Maybe yours does? Use "systemd-inhibit --list" for a list of active inhibitors

**Comment by JamesSwift** [comment]
Thanks for your quick reply! So I tested whether logind gets the state correct but it doesn't. I tested like so:
```
james@poper:~$ busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager LidClosed
b false
james@poper:~$ #Hit enter then immediately close the lid
james@poper:~$ sleep 3 && busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager LidClosed
b false
```
Forgive my ignorance, but is this a problem with the driver or systemd. If the driver, please would you be able to point me roughly towards the relevant place to try and fix it/file a bug?

**Comment by JamesSwift** [comment]
I don't think gnome is inhibiting the lid switch, but I'll let you judge for yourself :-)

[inhibit-list.log](https://github.com/systemd/systemd/files/4645305/inhibit-list.log)

**Comment by poettering** [comment]
yeah, looks like your firmware/acpi driver doesn't work. Consider asking your distro for help, or the people who work on the laptop driver support for your laptop. Maybe these people can help you:

https://github.com/jfrimmel/Acer-Switch-Battery-Module

Or try a firmware update.

But let's close this here, driver issues are nothing we can do anything about from the systemd side. Sorry.
