### ISSUE TITLE
Unable to execute fail2ban-client after fail2ban.service

### ISSUE THREAD

**Issue by Zhaoxun** [systemd/systemd#15831]
**systemd version the issue has been seen with**
> 219

**Used distribution**
 > CentOS 7.6

**Expected behaviour you didn't see**
 >the execution of `fail2ban-client status sshd` after the service fail2ban started

**Unexpected behaviour you saw**
 > `Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?`

**Steps to reproduce the problem**
firstly, make a small script that writes down fail2ban JAIL sshd status and mark a time stamp:

/root/fail2banstat.sh
```
#!/bin/bash
fail2ban-client status sshd > /root/fail2ban.status
date >> /root/fail2ban.status
```
change `chmod +x /root/fail2banstat.sh`

Then write a service file in 

/usr/lib/systemd/system/autoinit.sh
```
[Unit]
After=fail2ban.service
Description=stamp fail2ban status

[Service]
Type=notify
ExecStart=/root/fail2banstat.sh
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
If I start the service manually, it will print out the correct result in /root/fail2ban.status, but if enable the service and restart, an error will occur telling that fail2ban is unavailable and fail2ban-client... command yielded no result but to flush the text file fail2ban.status, leaving only the time in it.
systemd report not able to use fail2ban:
```
systemctl status -l autoinit
● autoinit.service - stamp fail2ban status
   Loaded: loaded (/usr/lib/systemd/system/autoinit.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sat 2020-05-16 11:51:32 CST; 1min 52s ago
  Process: 1047 ExecStart=/root/fail2banstat.sh (code=exited, status=0/SUCCESS)
 Main PID: 1047 (code=exited, status=0/SUCCESS)

May 16 11:51:32 10-24-11-67 systemd[1]: Starting stamp fail2ban status...
May 16 11:51:32 10-24-11-67 fail2banstat.sh[1047]: 2020-05-16 11:51:32,982 fail2ban                [1050]: ERROR   Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
May 16 11:51:32 10-24-11-67 systemd[1]: Started stamp fail2ban status.
```

**Comment by poettering** [comment]
The submission form tries to make clear that this is an issue tracker only for the two most recent systemd upstream versions, which is 244 and 245 currently. 219 is waaaay to old for that. For old stuff like that, plese contact your downstream distro instead.
