### ISSUE TITLE
User timers with WantedBy=multi-user.target are inactive after reboot.

### ISSUE THREAD

**Issue by nils-werner** [systemd/systemd#15846]
**systemd version the issue has been seen with**

> ```
> systemd 245 (245.5-2-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
> ```

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > User timers with WantedBy=multi-user.target should be active after reboot.

**Unexpected behaviour you saw**
 > User timers with WantedBy=multi-user.target are inactive after reboot.

**Steps to reproduce the problem**

Create a service and a timer:

```
# /usr/lib/systemd/system/true.service
[Unit]
Description=Test service

[Service]
ExecStart=/usr/bin/true
```

and

```
# /usr/lib/systemd/system/true.timer
[Unit]
Description=Test timer

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=multi-user.target
```

and also create links to make them available as user services and timers:

```
sudo ln -s '../system/true.timer' /usr/lib/systemd/user/true.timer
sudo ln -s '../system/true.service' /usr/lib/systemd/user/true.service
```

Enable both the system timer and the user timer

```
sudo systemctl enable --now true.timer
systemctl --user enable --now true.timer
```

Both timers are running:

```
sudo systemctl status true.timer
systemctl --user status true.timer
```

yields

```
● true.timer - Test timer
     Loaded: loaded (/usr/lib/systemd/system/true.timer; enabled; vendor preset: disabled)
     Active: active (waiting) since Tue 2020-05-19 15:05:32 CEST; 6s ago
     Trigger: Wed 2020-05-20 00:00:00 CEST; 8h left
     Triggers: ● true.service

● true.timer - Test timer
     Loaded: loaded (/usr/lib/systemd/system/true.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Tue 2020-05-19 15:05:32 CEST; 50s ago
     Trigger: Wed 2020-05-20 00:00:00 CEST; 8h left
     Triggers: ● true.service
```

And reboot. After the reboot, only the system timer is still active:

```
sudo systemctl status true.timer                                                                                                                            
systemctl --user status true.timer
```

yields

```
● true.timer - Test timer
     Loaded: loaded (/usr/lib/systemd/system/true.timer; enabled; vendor preset: disabled)
     Active: active (waiting) since Tue 2020-05-19 14:53:50 CEST; 3min 22s ago
     Trigger: Wed 2020-05-20 00:00:00 CEST; 9h left
     Triggers: ● true.service

● true.timer - Test timer
     Loaded: loaded (/usr/lib/systemd/system/true.timer; enabled; vendor preset: enabled)
     Active: inactive (dead)
     Trigger: n/a
     Triggers: ● true.service
```

If I change

```
[Install]
WantedBy=multi-user.target
```

to

```
[Install]
WantedBy=timers.target
```

the user timer is active after reboot.

Is it by design that system timers can use `WantedBy=multi-user.target` but user timers must use `WantedBy=timers.target`, otherwise they silently fail?

**Comment by nils-werner** [comment]
I have changed the setup to use copies of the system and timer files

```
sudo rm /usr/lib/systemd/user/true.timer
sudo rm /usr/lib/systemd/user/true.service
sudo cp /usr/lib/systemd/system/true.timer /usr/lib/systemd/user/true.timer
sudo cp /usr/lib/systemd/system/true.service /usr/lib/systemd/user/true.service
```

but the problem remains.

**Comment by poettering** [comment]
multi-user.target is a target that is only defined for the system instance of systemd. It doesn't exist for the user instance, and hence if you hook yourself into that it has no effect.

Timers are supposed to be hooked into timers.target, and that's a target defined both for systemd --user and systemd --system.

See the systemd.special(7) man page for details about the units defined in either context.

In general we allow hooking into any unit you like via WantedBy=, even non-existing ones, following a lose-coupling logic: a unit X shipped in package X.rpm might want to hook itself into a package Y if Y.rpm is installed, but if not not do anything.

**Comment by nils-werner** [comment]
Ah that makes sense, thanks.

So basically [this system timer which I took inspiration from](https://git.archlinux.org/svntogit/packages.git/tree/trunk/btrfs-scrub@.timer?h=packages/btrfs-progs#n11) is technically wrong, too?

And regarding linking service files from system to user, is this an OK thing to do?

**Comment by keszybz** [comment]
> And regarding linking service files from system to user, is this an OK thing to do?

Theoretically yes, but please don't. Such a unit file would be treated as a linked unit file (in the sense of `systemctl link`). systemd and systemctl should treat it correctly. But users are very much likely to be confused by this.

> So basically [this system timer which I took inspiration from](https://git.archlinux.org/svntogit/packages.git/tree/trunk/btrfs-scrub@.timer?h=packages/btrfs-progs#n11) is technically wrong, too?

Dunno, it looks like a system timer? I don't see anything wrong with it.

Anyway, it seems everything is working as expected here, let's close.
