### ISSUE TITLE
systemd-repart asserts when Label=something is used in .conf file

### ISSUE THREAD

**Issue by hunger** [systemd/systemd#15841]
**systemd version 245**

**Used distribution: Arch Linux**

Setting a Label in a configuration file seems to trigger an assertion in `systemd-repart`.

**Expected behaviour you didn't see**

systemd-repart does whatever it is supposed to do:-)

**Unexpected behaviour you saw**

The following output is produced:
```
Assertion '!p->new_label' failed at src/partition/repart.c:2213, function context_acquire_partition_uuids_and_labels(). Aborting.
Aborted (core dumped)
```

**Steps to reproduce the problem**

Created `/usr/lib/repart.d/30-btrfs.conf` with the following contents:
```
[Partition]
Type=linux-generic
Label=fs_btrfs
```
Then run `systemd-repart --dry-run=yes --empty=require /dev/vda` (in Qemu with an empty disk, no GPT yet).

**Comment by poettering** [comment]
Fix waiting in #15844
