### ISSUE TITLE
Freezing units vs jobs

### ISSUE THREAD

**Issue by Werkov** [systemd/systemd#15849]
**systemd version the issue has been seen with**
> 9e12d5bf6368de78243a8de11d7739d2c89c1378

**Used distribution**
 > openSUSE Tumbleweed

**Expected behaviour you didn't see**
 > Starting a unit under frozen slice or stopping an indirectly frozen unit is rejected on the job level.

**Unexpected behaviour you saw**
 > Attempt to spawn starting/control process in a frozen cgroup leading to various timeouts and confusing reported states (new unit unfrozen, old unit failed (frozen)).

**Steps to reproduce the problem**
```
systemd-run --slice=frozen.slice cmd
systemctl stop unit-frozen-by-ancestor.slice
```

Cc: @msekletar

**Comment by poettering** [comment]
yes, i think we should make sure that unit_start() returns some recognizable error if it is invoked on a unit that resides in a frozen slice, maybe EHWPOISON. This should then be propagated into a new job failure code, i.e. JOB_FROZEN or so, similar to how we do it with JOB_UNSUPPORTED or JOB_ASSERT.
