### ISSUE TITLE
udev rule matching arbitrary uevent parameter

### ISSUE THREAD

**Issue by osresearch** [systemd/systemd#15855]
**Is your feature request related to a problem? Please describe.**
I'd like to register a udev rule that matches when a dmverity block device has detected a merkle tree hash failure.  `udevadm monitor` shows the uevent including the `DM_VERITY_ERR_BLOCK_NR` attribute:

```
KERNEL[3859.338338] change   /devices/virtual/block/dm-7 (block)
ACTION=change
DEVPATH=/devices/virtual/block/dm-7
SUBSYSTEM=block
DM_VERITY_ERR_BLOCK_NR=0,4241
DEVNAME=/dev/dm-7
DEVTYPE=disk
SEQNUM=8693
MAJOR=253
MINOR=7
```

I tried adding a udev rule that matched on `ATTRS{DM_VERITY_ERR_BLOCK_NR}`, but the rule never fired when my test created deliberate file system errors:

```
KERNEL=="dm-[0-9]*", ACTION=="change", SUBSYSTEM=="block", ATTRS{DM_VERITY_ERR_BLOCK_NR}!="", RUN+="/usr/sbin/dmverity-log-error"
```

**Describe the solution you'd like**
`ATTRS{}` to match the parameters in the event.

**Describe alternatives you've considered**
I wrote a small program that creates a raw netlink socket of type `NETLINK_KOBJECT_UEVENT` and parses the uevent strings, which might end up being necessary anyway to avoid `EIO` errors if the root filesystem corruption happens to hit `/etc/udev/` or the program to do the reporting.

**Comment by poettering** [comment]
ATTRS{} is for checking attribute files in sysfs.

YOu want to check env vars, i.e. ENV{DM_VERITY_ERR_BLOCK_NR}=="…"

**Comment by poettering** [comment]
(And note that this is not a support forum but a bug and feature request tracker. Please use the systemd mailing list for support questions like this one)

**Comment by osresearch** [comment]
`ENV{DM_VERITY_ERR_BLOCK_NR}!=""` works.  Thanks for the suggestion - the `man udev` docs weren't clear what was in `ENV` versus `ATTR`.
