### ISSUE TITLE
nspawn: fails when using --private-users and the rootfs group is not mapped

### ISSUE THREAD

**Issue by iaguis** [systemd/systemd#1585]
If I start a container with `--private-users` whose rootfs has the mode 750 and is owned by a group that's not mapped, nspawn fails:

```
> ls -lnd ~/temp/test-userns
drwxr-x--- 12 10000 1001 4096 Oct 16 11:27 /home/iaguis/temp/test-userns
> sudo ./systemd-nspawn --private-net --private-users=10000:65536 -D ~/temp/test-userns/ /bin/busybox sh
Spawning container test-userns on /home/iaguis/temp/test-userns.
Press ^] three times within 1s to kill container.
Child died too early.
Using user namespaces with base 10000 and range 65536.
Timezone Europe/Madrid does not exist in container, not updating container timezone.
Failed to detect whether /proc is a mount point: Permission denied
```

I checked the code and at first I thought the problem was that [we mount `/proc` before we become the new root](https://github.com/systemd/systemd/blob/8ee07361d0065a2d4ab9c4bf6aeb0893b05b2b6c/src/nspawn/nspawn.c#L2453) so we're `nobody:nogroup` at that point and since the rootfs has mode 750 we get the `Permission denied` message.

However, if the group is mapped, everything works fine:

```
> sudo chown 10000:11111 ~/temp/test-userns
> ls -lnd ~/temp/test-userns
drwxr-x--- 12 10000 11111 4096 Oct 16 11:27 /home/iaguis/temp/test-userns
> sudo ./systemd-nspawn --private-net --private-users=10000:65536 -D ~/temp/test-userns/ /bin/busybox sh
Spawning container test-userns on /home/iaguis/temp/test-userns.
Press ^] three times within 1s to kill container.
Using user namespaces with base 10000 and range 65536.
Timezone Europe/Madrid does not exist in container, not updating container timezone.
sh: can't access tty; job control turned off
/ #
```

I'm confused now, any ideas?

**Comment by poettering** [comment]
What does an strace -f say? What syscall really fails like this?

**Comment by iaguis** [comment]
With a non-mapped group:

```
[pid  3164] lstat("/proc",  <unfinished ...>
[pid  3161] setsockopt(9, SOL_SOCKET, SO_RCVBUFFORCE, [8388608], 4 <unfinished ...>
[pid  3164] <... lstat resumed> 0x7ffc65ad8b30) = -1 EACCES (Permission denied)
```

With a mapped group:

```
[pid  3117] lstat("/proc",  <unfinished ...>
[pid  3114] <... getsockopt resumed> [212992], [4]) = 0
[pid  3117] <... lstat resumed> {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
...
```

**Comment by poettering** [comment]
My guess is that this is actually caused by the issue indicated here:

https://lwn.net/Articles/626665/

(i.e. groups can be used to take privs away on UNIX, hence an unmapped group might result in EPERM)

And as such is hardly anything we could fix in systemd/nspawn. or did I musinderstand this?

**Comment by poettering** [comment]
Closing this, due to lack of response, and under the assumption that I guess right.
