### ISSUE TITLE
Systemd-boot: missing documentation for the option "options" in loader.conf(5)

### ISSUE THREAD

**Issue by MrM40** [systemd/systemd#15863]
I cannot find any documentation for the option "options" in the .conf file.
Been looking in loader.conf(5), freedesktop.org and systemd.io.
Am I missing something?

**Comment by poettering** [comment]
There is no such option called "options". That's why it is not documented. What makes you think there was such an option?

**Comment by MrM40** [comment]
This is a copy of my current systemd-boot .conf file:

     title      "SRV1_Debian 10 (Burster)"
     linux      "/EFI/kernels/SRV02_Debian10(Burster)/vmlinuz-4.19.0-8-amd64"
     initrd     "/EFI/kernels/SRV02_Debian10(Burster)/initrd.img-4.19.0-8-amd64"
     options    root=UUID=a4474847-222f-48af-bd29-078737c03d31 intel_iommu=on

Am I wrong calling the option "options" an option, haha, if you can follow me ;-)

**Comment by poettering** [comment]
that's not loader.conf. That's boot loader spec type #1 snippets. See https://systemd.io/BOOT_LOADER_SPECIFICATION/
