### ISSUE TITLE
RFE: common interface to expose host's os-release to container-like runtimes

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#15878]
Creating an RFE as requested based on the following mail thread:

https://lists.freedesktop.org/archives/systemd-devel/2020-April/044378.html

>We find ourselves in a situation where application running
containerized (specifically as portable services, although this issue
is general) need to either find information about the host, or alter
their behaviour depending on the host's flavour.
At the same time, applications also need to find information about the
guest's OS, so simply bind mounting /etc/os-release from the host is
not enough. We need both.

Proposed solutions:

- mount/copy the host's os-release in a specific path
  - Flatpak exposes files from the host under /run/host, so following that model it would look like /run/host/usr/lib/os-release
  - nspawn exposes mounts from the host in /run/systemd/nspawn/incoming, so following that model it would look like /run/systemd/nspawn/incoming/usr/lib/os-release
- have the runtime manager parse the *_ID keys from the host's os-release and make them available as environment variables to the guest, and have this as part of the container interface

**Comment by bluca** [comment]
Flatpak implementation: https://github.com/flatpak/flatpak/pull/3640

**Comment by bluca** [comment]
In https://github.com/systemd/systemd/pull/15891 the design veered toward having the runtime set an environment variable for each key in the host's os-release, prefixed by service_host_ for lightweight-container-like runtimes (portabled, flatpak, nspawn with start_pid1/2) and container_host_ for vm-like runtimes (nspawn with a full image boot, lxd)

**Comment by alexlarsson** [comment]
For flatpak, I want to go with the /run/host model, because a filesystem option like that is much more robust. For example, env-vars are often cleared or changed when children are spawned, which would lose this information. Also, having the sandbox tool parse a file unnecessarily means its more risky, and less flexible (i.e. harder to extend).
