### ISSUE TITLE
journalctl should be able to parse its own timestamps

### ISSUE THREAD

**Issue by grahamc** [systemd/systemd#15899]
journalctl's output emits timestamps journalctl can't parse as an argument to `--since`:

```
$ journalctl -e
May 24 01:55:58 ceres ...

$ journalctl --since "May 24 01:53:48"
Failed to parse timestamp: May 24 01:53:48
```

Ideally, by default, whatever format is printed by default should be a valid argument to `--since`, like:

```
$ journalctl --since "May 24 01:53:48"
May 24 01:55:58 ceres ...
```

or changing the log format to be compatible.

**Comment by mrc0mmand** [comment]
There's `journalctl -o short-full`, which works just as the default output format (`short`), but prints timestamps in `--since/--until` friendly name, see [journalctl(1)](https://www.freedesktop.org/software/systemd/man/journalctl.html#-o):

```
-o, --output=

    Controls the formatting of the journal entries that are shown. Takes one of the following options:

    short
        is the default and generates an output that is mostly identical to the formatting of classic
        syslog files, showing one line per journal entry.

    short-full
        is very similar, but shows timestamps in the format the --since= and --until= options accept.
        Unlike the timestamp information shown in short output mode this mode includes weekday, year
        and timezone information in the output, and is locale-independent.
```

**Comment by poettering** [comment]
The regular syslog output format we use (called "short") we inherited pretty much from syslog. It's has a less than ideal way to encode dates, i.e. lacking timezone info and stuff. I figure we could add the minimal bits necessary to make this work somewhat reasonably, but of course in an ideal world, we wouldn't even use that time format but something less ambiguous...

**Comment by hyperfekt** [comment]
journalctl already accepts times without a timezone and interprets it as (I'm guessing) the current one. Is there a reason this cannot be done for timestamps that look the same but additionally include a date, too?

**Comment by poettering** [comment]
it's not just the timezone thing, it's also that the syslog formatting is locale dependent, i.e. month names change... it's just nasty... 

but sure, we can make this work based on locally set tz and locally. happy to review a patch.
