### ISSUE TITLE
timesyncd monitoring

### ISSUE THREAD

**Issue by sts** [systemd/systemd#1589]
We are currently testing timesyncd as NTP client on our machines. One thing I noticed is that timedatectl doesn't provide any output about offsets and jitter, how I was used to when using ntpd. It provides us with a way to write monitoring scripts for time drift in our network.

```
ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*1.2.3.4  213.136.0.252    2 u  486 1024  377    0.287   -1.760   0.491
+2.3.4.5 193.239.220.29   2 u  441 1024  377    0.872   -3.321   1.094
```

Is there any hidden functionality, which isn't mentioned in the manpage yet, which we could make use of or can you plan a feature for that?

**Comment by poettering** [comment]
We generate some output on LOG_DEBUG level. But I figure we could expose this on the bus, too. Happy to take a patcj.

**Comment by ghost** [comment]
IMHO commit 7b5b3fc3 should be reverted. The INFO logging level was sufficient for that one line. Making it log_debug() it is now logged at the same level as log_debug() at line 632 above that, which only repeats that info but much more verbose.

So in other words, log_debug() for that verbose status log, and log_info() for occasional one-liner about delay, drift, offset, ...

Having offset logged like it was before is a great way to track precision and wasn't chatty at all, it logs once or twice PER HOUR, at least looking at our Debian Jessie logs, systemd 219.
