### ISSUE TITLE
Possible addition: Passing environment variables to systemd as PID1?

### ISSUE THREAD

**Issue by alexyuriev** [systemd/systemd#15895]
It is currently not possible to pass environment variables to systemd when it is running as PID1. While it is not an issue in a main system, should systemd be a PID1 in a container it complicated things. 

Should we consider having a flag that would allow systemd to receive a list of environment variables to preserve from whatever spawned the container?

**Comment by poettering** [comment]
systemd accepts env vars just fine. Just set them and pass them to PID 1. systemd-nspawn exposes `--setenv=` to set them to systemd if it runs as PID1 inside the container.

You can propagate them from the service manager to specific services using the `PassEnvironment=` setting in unit files.

Hence I think everything you are asking for is already there, no? Closing hence.

**Comment by alexyuriev** [comment]
@poettering  I see the behavior you are describing when using bash as the init. However when the systemd is being used as the PID1 this is what happens with systemd 241 ( Debian 10 )

` systemd-nspawn --hostname=`hostname` -D k-agent-0.04 -b --bind-ro=/tmp/k-agent-ssh/:/root/.ssh:norbind --setenv=TESTVAR=test`

`Debian GNU/Linux 10 pmaster1 console

pmaster1 login: root
Password: 
Last login: Wed Jun 17 20:08:47 EDT 2020 on console
Linux pmaster1 5.5.0 #11 SMP PREEMPT Sun Apr 19 08:17:52 EDT 2020 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@pmaster1:~# printenv
SHELL=/bin/bash
PWD=/root
LOGNAME=root
HOME=/root
LANG=C.UTF-8
INVOCATION_ID=bc0dd4f38366460a811073848e18ecfd
TERM=xterm
USER=root
SHLVL=1
JOURNAL_STREAM=9:5245096
HUSHLOGIN=FALSE
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAIL=/var/mail/root
_=/usr/bin/printenv
`
TESTVAR environment variable is missing.

Based on what I'm reading in systemd.exec PassEnvironment needs to be used to tell systemd running as PID1 to whitelist additional environment variables but systemd-nspawn does not support it. 

Am I missing something obvious?
