### ISSUE TITLE
systemd-cgtop CPU usage

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#159]
The percentage value of cpu usage of systemd-cgtop is %100 x number of cores system has. This is not so easy to understand when you are using the program. You need to know how many cores your system has. I don't think this is how it is in "top". 

We should either scale the number down so we don't exceed %100 or indicate somewhere how many cores this system has with max possible %.

**Comment by poettering** [comment]
I am pretty sure we should follow the same logic that top has in place there...

Anyone can check what happens in top if I have a process with multiple trheads attached to multiple CPUs all eating full CPU?

**Comment by utezduyar** [comment]
I checked it on busybox top. I have 4 cores on my target and I have started 2 dd processes. Result is:

```
Mem: 36880K used, 174360K free, 4392K shrd, 0K buff, 17692K cached
CPU: 11.6% usr 38.7% sys  0.0% nic 49.6% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 0.77 0.20 0.10 4/63 470
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  469   381 root     R     2700  1.2   2 24.9 dd if /dev/zero of /dev/null
  470   381 root     R     2696  1.2   1 24.9 dd if /dev/zero of /dev/null
  414     1 root     S     7884  3.7   0  0.1 sshd: root@pts/1
  468   416 root     R     2876  1.3   3  0.1 top
    7     2 root     SW       0  0.0   0  0.0 [rcu_sched]
  165     2 root     SW       0  0.0   3  0.0 [kworker/3:2]
```

**Comment by keszybz** [comment]
On Fri, Jun 12, 2015 at 05:38:38AM -0700, Umut Tezduyar Lindskog wrote:

> I checked it on busybox top. I have 4 cores on my target and I have started 2 dd processes. Result is:
> 
> ```
> Mem: 36880K used, 174360K free, 4392K shrd, 0K buff, 17692K cached
> CPU: 11.6% usr 38.7% sys  0.0% nic 49.6% idle  0.0% io  0.0% irq  0.0% sirq
> Load average: 0.77 0.20 0.10 4/63 470
>   PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
>   469   381 root     R     2700  1.2   2 24.9 dd if /dev/zero of /dev/null
>   470   381 root     R     2696  1.2   1 24.9 dd if /dev/zero of /dev/null
>   414     1 root     S     7884  3.7   0  0.1 sshd: root@pts/1
>   468   416 root     R     2876  1.3   3  0.1 top
>     7     2 root     SW       0  0.0   0  0.0 [rcu_sched]
>   165     2 root     SW       0  0.0   3  0.0 [kworker/3:2]
> ```
> 
> It seems that busybox top behaves differently than "normal" top:

top - 08:56:00 up 142 days, 14:15, 10 users,  load average: 1.58, 0.61, 0.39
Tasks: 406 total,   3 running, 401 sleeping,   0 stopped,   2 zombie
%Cpu(s):  2.4 us, 15.9 sy,  0.0 ni, 81.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  32903980 total, 29911368 used,  2992612 free,  1585120 buffers
KiB Swap: 25067516 total,  1749064 used, 23318452 free, 18932660 cached

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30429 zbyszek   20   0  107924   1828   1736 R 100.0  0.0   1:07.31 dd
30435 zbyszek   20   0  107924   1828   1736 R 100.0  0.0   1:06.51 dd
 7332 zbyszek   20   0 11.673g 936760  17032 S 815.2  2.8   1:08.88 java  

(This is on a 12 core machine).

As you can see, each dd if shown as using 100%, and a hungry java
process is shown using 815% cpu. OTOH, both tops show the total in the
header as used / total available, so a fully loaded machine will show
100%.

**Comment by poettering** [comment]
I am pretty sure we should follow "normal" top here, hence there's nothing to change in cgtop, is there?

**Comment by utezduyar** [comment]
Ok, is this the summary?
**"normal" top displays both per CPU % (next to process) and per system CPU (in the header) scaled to %100.**
**busybox top only displays per system CPU % (next to process) scaled to %100.**
**systemd-cgtop only displays per system CPU % (next to process), not scaled to %100.**

I still think we should indicate what the max %100 can be on systemd-cgtop. A non tech savvy person will have no idea how to find the number of cores etc.

**Comment by keszybz** [comment]
On Sun, Jun 14, 2015 at 11:03:22PM -0700, Umut Tezduyar Lindskog wrote:

> Ok, is this the summary?
> **"normal" top displays both per CPU % (next to process) and per system CPU (in the header) scaled to %100.**
> When it shows e.g. 400%, I wouldn't call this "per CPU". I'd rather call
> this total usage by this process in units of cpus.
> 
> **busybox top only displays per system CPU % (next to process) scaled to %100.**
> I displays the same thing as "normal" top, only scaled differently.
> 
> **systemd-cgtop only displays per system CPU % (next to process), not scaled to %100.**
> It displays the same thing as "normal" top, but only the first part.
> 
> I still think we should indicate what the max %100 can be on systemd-cgtop. A non tech savvy person will have no idea how to find the number of cores etc. 

Can't we just describe this in the man page?

Zbyszek

**Comment by poettering** [comment]
Yeah, as much as I understood this appears to be a documentation issue primarily...

**Comment by poettering** [comment]
#221 was merged, I guess this can be closed now.

**Comment by seidler2547** [comment]
What is described here as "normal" top CPU usage display is actually called "Irix mode" in top and can be toggled with "I" (Shift+i). So in a world where more options are better, systemd-cgtop would be able to toggle between Irix and non-Irix mode.

**Comment by poettering** [comment]
I am pretty sure I have no interest in dumping computer history such as "Irix" on people... Sorry...
