### ISSUE TITLE
machined: log when we enable btrfs quota use, and add way to turn it off

### ISSUE THREAD

**Issue by tolga9009** [systemd/systemd#15903]
**systemd version the issue has been seen with**
> 245.5-2-arch

**Used distribution**
 > Arch Linux, Kernel 5.4.41-1-lts, btrfs-progs v5.6.1

**Expected behaviour you didn't see**
 > N/A

**Unexpected behaviour you saw**
 `machinectl pull-tar` quietly enables BTRFS quota, system-wide. There is no output indicating it. For my servers this is very critical, as I'm using snapper configured to maintain a total of around ~20 snapshots. BTRFS quota sometimes cripples performance up to a point, where I have to physically shutdown the servers, as SSH doesn't respond anymore due to 100% CPU load.

I wasn't aware `machinectl pull-tar` was enabling BTRFS quota system-wide just until now, since no documentation, man-page or console output indicates this. I stumbled upon it randomly, after wondering, why `list-images` suddenly listed subvolume sizes after using `pull-tar` operation.

For a feature, which is listed for causing performance issues in several Wikis ([[1]](https://btrfs.wiki.kernel.org/index.php/Quota_support#Known_issues),[[2]](https://wiki.debian.org/Btrfs#Warnings),[[3]](https://wiki.archlinux.org/index.php/Btrfs#Quota)), I think it would be necessary to atleast inform the user or better, add a flag to make it user-controllable (e.g. `machinectl pull-tar [...] --no-quota`).

**Steps to reproduce the problem**
1. `btrfs quota disable /`
2. `machinectl pull-tar http://example.com/image.tar.gz`
3. BTRFS quota is enabled.

Logs:
1. `machinectl pull-tar`, cleaned up [pull-tar_clean.log](https://github.com/systemd/systemd/files/4673849/pull-tar_clean.log)
2. `machinectl pull-tar`, full, URLs changed for privacy [pull-tar.log](https://github.com/systemd/systemd/files/4673848/pull-tar.log)
3. `btrfs subvolume list /` [btrfs-subvolumes.log](https://github.com/systemd/systemd/files/4673847/btrfs-subvolumes.log)
4. `btrfs filesystem usage /`[btrfs-fs.log](https://github.com/systemd/systemd/files/4673845/btrfs-fs.log)

**Comment by Edu4rdSHL** [comment]
This feature hasn't been implemented yet, right? Because the solution described in the documentation doesn't work.

```
 $ systemctl cat systemd-importd.service 

# /usr/lib/systemd/system/systemd-importd.service
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Virtual Machine and Container Download Service
Documentation=man:systemd-importd.service(8)
Documentation=man:org.freedesktop.import1(5)

[Service]
ExecStart=/usr/lib/systemd/systemd-importd
BusName=org.freedesktop.import1
KillMode=mixed
CapabilityBoundingSet=CAP_CHOWN CAP_FOWNER CAP_FSETID CAP_MKNOD CAP_SETFCAP CAP_SYS_ADMIN CAP_SETPCAP CAP_DAC_OVERRIDE CAP_LINUX_IMMUTABLE
NoNewPrivileges=yes
MemoryDenyWriteExecute=yes
ProtectHostname=yes
RestrictRealtime=yes
RestrictNamespaces=net
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallFilter=@system-service @mount
SystemCallErrorNumber=EPERM
SystemCallArchitectures=native
LockPersonality=yes
WatchdogSec=3min

# /etc/systemd/system/systemd-importd.service.d/override.conf
[Service]
Environment=SYSTEMD_IMPORT_BTRFS_QUOTA=false
```

As you can see, the override file contains `Environment=SYSTEMD_IMPORT_BTRFS_QUOTA=false`, however, quota is still enabled on disk.

**Comment by cmurf** [comment]
> This feature hasn't been implemented yet, right? Because the solution described in the documentation doesn't work.

```
$ env | grep SYS
SYSTEMD_IMPORT_BTRFS_QUOTA=0
SYSTEMD_EXEC_PID=2352
$ sudo machinectl pull-tar https://kojipkgs.fedoraproject.org//packages/Fedora-Container-Base/35/20220127.0/images/Fedora-Container-Base-35-20220127.0.x86_64.tar.xz F35CB20220127
...
[snip]
Failed to retrieve SHA256 checksum, cannot verify. (Try --verify=no?)
Exiting.
$ sudo btrfs qgroup show /
qgroupid         rfer         excl 
--------         ----         ---- 
0/5          16.00KiB     16.00KiB 
0/264         4.00GiB      4.00GiB 
0/271         2.44GiB    961.82MiB 
... [snip]
```

So yeah looks like it's not wired up still.

systemd-249.9-1.fc35.x86_64
