### ISSUE TITLE
UBSan seems to be complaining about a float-cast-overflow in json_variant_has_type

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#15907]
```sh
$ printf '[7E73]' >crash

$ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1 ./out/fuzz-json ./crash

INFO: Seed: 3046474721
INFO: Loaded 2 modules   (136687 inline 8-bit counters): 136668 [0x7f6fca188930, 0x7f6fca1a9f0c), 19 [0x575d60, 0x575d73),
INFO: Loaded 2 PC tables (136687 PCs): 136668 [0x7f6fca1a9f10,0x7f6fca3bfcd0), 19 [0x54fcd0,0x54fe00),
./out/fuzz-json: Running 1 inputs 1 time(s) each.
Running: ./crash
../src/shared/json.c:1144:38: runtime error: 7e+73 is outside the range of representable values of type 'long'
    #0 0x7f6fc97e12ef in json_variant_has_type /home/vagrant/systemd/build/../src/shared/json.c:1144:38
    #1 0x7f6fc97d8dc5 in json_variant_is_normalized /home/vagrant/systemd/build/../src/shared/json.c:4282:41
    #2 0x7f6fc97d7506 in json_variant_new_array /home/vagrant/systemd/build/../src/shared/json.c:543:22
    #3 0x7f6fc97f15ca in json_parse_internal /home/vagrant/systemd/build/../src/shared/json.c:2980:29
    #4 0x7f6fc97f5b6f in json_parse_file_at /home/vagrant/systemd/build/../src/shared/json.c:3188:16
    #5 0x536d8b in json_parse_file /home/vagrant/systemd/build/../src/shared/json.h:205:16
    #6 0x536914 in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/fuzz/fuzz-json.c:21:13
    #7 0x441958 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-json+0x441958)
    #8 0x426a75 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-json+0x426a75)
    #9 0x42f9b9 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/systemd/out/fuzz-json+0x42f9b9)
    #10 0x41fa16 in main (/home/vagrant/systemd/out/fuzz-json+0x41fa16)
    #11 0x7f6fc8c1b1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #12 0x41fa6d in _start (/home/vagrant/systemd/out/fuzz-json+0x41fa6d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/shared/json.c:1144:38 in
```

As far as I can see, it seems to be intentional so it would probably make sense to turn this check off there with [`__attribute__((no_sanitize("float-cast-overflow")))`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-undefined).

**Comment by evverx** [comment]
To judge from https://travis-ci.org/github/systemd/systemd It seems to be another UBSan check gcc interprets differently. @jakubjelinek I wonder why gcc wouldn't complain about it?

**Comment by evverx** [comment]
Never mind. I passed `-fsanitize=float-cast-overflow -fno-sanitize-recover=float-cast-overflow` to `gcc` explicitly and the fuzz target failed as expected. It appears float-cast-overflow is just off by default (that is it isn't turned on by `-fsanitize=undefined`).

**Comment by jakubjelinek** [comment]
Sure, because it is not undefined behavior, see https://gcc.gnu.org/legacy-ml/gcc-patches/2014-05/msg01006.html for details.

**Comment by poettering** [comment]
> As far as I can see, it seems to be intentional so it would probably make sense to turn this check off there with [`__attribute__((no_sanitize("float-cast-overflow")))`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-undefined).

Hmm, we already use `#pragma GCC diagnostic ignored "-Wfloat-equal"` to turn off gcc's warning on this. Would be great if ubsan would just honour that too...

**Comment by poettering** [comment]
Does #15914 fix this?
