### ISSUE TITLE
CLI tools do not log to the console when executed as a child process

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#15902]
**systemd version the issue has been seen with**
> v245

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-tmpfiles logs to the console when executed as a child process

**Unexpected behaviour you saw**
 > systemd-tmpfiles logs to the journal when executed as a child process

**Steps to reproduce the problem**

Run systemd-tmpfiles as a child process (e.g. via Python's `subprocess.run`)

I spent (wasted?) a lot of time debugging a pacman hook failure that was failing with not logging output because systemd-tmpfiles decides to log directly to the journal if the stderr fd is not a tty. systemd-tmpfiles calls `log_setup_service` which sets the log target to `AUTO`. Subsequently, when `log_open` is called, the `isatty` check fails and systemd-tmpfiles prefers all the other logging options above logging to the console. 

I think this behaviour is perfectly acceptable for actual services but for stuff that is also meant to be run as a CLI tool, maybe we should prefer logging to the console even if it isn't a tty to avoid weird behaviour when running these command line tools as child processes of another process for example a package manager such as pacman.

**Comment by poettering** [comment]
hmm, so actually, we check that stderr is a tty or not, since typically when you invoke something in a subprocess you'd leave stderr the way it is. i mean, that's at least what you'd do in a shell script for example, where unless you explicitly redirect stderr it is just inherited and thus still connected to a tty...

isn't this most something we should just document clearly?

**Comment by keszybz** [comment]
> since typically when you invoke something in a subprocess you'd leave stderr the way it is

Not really. You do that only if you can't do better. When shelling out under python, people nowadays use subprocess.run(capture_output=True), and then you can print the stdout or stderr streams only when an error occurs.

> for stuff that is also meant to be run as a CLI tool, maybe we should prefer logging to the console even if it isn't a tty to avoid weird behaviour when running these command line tools as child processes of another process for example a package manager such as pacman

Yeah, I think we should do this.
