### ISSUE TITLE
systemd-bus-proxyd crashes when user runs an application under fakeroot

### ISSUE THREAD

**Issue by KenMilmore** [systemd/systemd#1591]
Running an application under fakeroot which attempts to make use of the user bus, causes systemd-bus-proxyd to crash on my system.

I am running Arch Linux with stock kernel 4.2.3, systemd 227, kdbus (git 245fe9) and Xfce desktop environment.

Running e.g. "fakeroot mousepad" causes the user instance of systemd-bus-proxyd to die immediately, blowing away most of the processes in the desktop session.  Journalctl shows the following messages:

systemd-bus-proxyd[769]: Failed to start bus client: Connection reset by peer
systemd-bus-proxyd[769]: Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/util.c:318, function safe_close(). Aborting.

I first encountered this problem when building the Arch AUR package tango-icon-theme:  I think the rsvg-convert utility may be using dbus from within the fakeroot environment.

**Comment by poettering** [comment]
Thre's a fix in #1595 for this.

**Comment by KenMilmore** [comment]
Thanks for responding!
Having patched my systemd 227 with the above fix(commit 1a37c97), I can confirm that the bus proxy no longer falls over when I run things under fakeroot.
I do see a lot of repetitions of "systemd-bus-proxyd[...]: Failed to start bus client: Connection reset by peer" in the journal, but I guess that may be expected under the circumstances?
