### ISSUE TITLE
systemd hangs on shutdown/restart waiting on autofs CIFS unmount

### ISSUE THREAD

**Issue by geckolinux** [systemd/systemd#15913]
Hi, running openSUSE Tumbleweed with systemd 245.

I use autofs to mount two CIFS shares on a local NAS. This causes systemd to hang for 3 minutes on every shutdown while waiting for autofs to unmount the shares. I even set `timeout = 5` in `/etc/autofs.conf`, but it doesn't help.

There was apparently a similar issue in the past when NFS shares were automounted, but this was supposedly [fixed](https://bugs.archlinux.org/task/40200).
I confirm on Tumbleweed that the supplied autofs.service contains these lines:

```````````
After=network.target ypbind.service sssd.service network-online.target remote-fs.target rpc-statd.service rpcbind.service
Wants=network-online.target rpc-statd.service rpcbind.service
```````````

Other relevant reports and supposed fixes:
- https://bugs.freedesktop.org/show_bug.cgi?id=59152
- https://cgit.freedesktop.org/systemd/systemd/commit/?id=7700945
- https://bugs.archlinux.org/task/35671
- https://bbs.archlinux.org/viewtopic.php?id=162236

**Comment by poettering** [comment]
So, have any logs? screenshots? i.e. something that actually could tell us what is delaying things? otherwise we really cannot help you...

**Comment by poettering** [comment]
what do you use to configure your network? does it properly order itself before network-online.target and network.target?

**Comment by geckolinux** [comment]
[enabled-units.txt](https://github.com/systemd/systemd/files/4677972/enabled-units.txt)

[critical-chain.txt](https://github.com/systemd/systemd/files/4677974/critical-chain.txt)

[journalctl.txt](https://github.com/systemd/systemd/files/4677975/journalctl.txt)

![IMG_20200525_103621](https://user-images.githubusercontent.com/2692138/82827807-5d2fd700-9e75-11ea-90a1-a87cc8da0063.jpg)

![IMG_20200524_203132](https://user-images.githubusercontent.com/2692138/82827819-60c35e00-9e75-11ea-9a37-c87ec9198420.jpg)

**Comment by geckolinux** [comment]
[enabled-units.txt](https://github.com/systemd/systemd/files/4678060/enabled-units.txt)

[critical-chain.txt](https://github.com/systemd/systemd/files/4678061/critical-chain.txt)

[journalctl.txt](https://github.com/systemd/systemd/files/4678062/journalctl.txt)

![IMG_20200524_203132](https://user-images.githubusercontent.com/2692138/82829416-d0871800-9e78-11ea-83a7-99aee9d0c6b0.jpg)

![IMG_20200525_105927](https://user-images.githubusercontent.com/2692138/82829433-d977e980-9e78-11ea-987d-be6f74bfaded.jpg)

**Comment by geckolinux** [comment]
For some reason the `\\192.198.1.6 Cancelling wait for...` thing started working after about ten seconds.  Much better than 3 minutes, but still clunky.

**Comment by poettering** [comment]
So what's the problem here? is the server simply not responding? Is your network shut down before the file system is unmounted?

As I asked before, which network management implementation are you using? networkd?

**Comment by geckolinux** [comment]
Since systemd doesn't save shutdown logs I have no idea what it's doing apart from the stuff on the tty in my screenshot.

And from the attached files you can see that I am using NetworkManager.

**Comment by poettering** [comment]
systemd saves shutdown logs just fine. Maybe your distro is not turning persistant logging on though?

Quite frankly, please ping your distro maintainers first, they should probably help you first, and then propagate this here. This is alsmost certainly an integration problem, and unlikely an upstream problem. i.e. what matters is whatever network management solution they have implemented it is ordered before remote-fs.target, so that at shutdown the mounts are detached first and the network pulled down after that.

@fbuihuu iirc you are a suse guy, can you help @geckolinux?

**Comment by fbuihuu** [comment]
Persistent logging is turned on by default on TW. But to look at the shudown part in the logs you need to reboot and then look at the previous boot with something like `journalctl -b -1`... 

Also what happens if you umount the CIFS shares manually with `systemctl stop mnt-openmediavault-home.mount` ? Does it hang too ?

**Comment by marcosfrm** [comment]
> And from the attached files you can see that I am using NetworkManager.

If on wifi, take a look:

https://github.com/systemd/systemd/issues/1435#issuecomment-332795236

**Comment by geckolinux** [comment]
@marcosfrm Hmm, that appears to be the issue. I am indeed on WiFI, sorry I didn't mention that before. So I made the connection global and it seems to shut down immediately now.

So I gather it was technically hanging because it was waiting on wpa_supplicant or dbus? Shouldn't systemd be able to force the WiFI connection to drop?

**Comment by marcosfrm** [comment]
It is NetworkManager job. systemd just tells it to stop and nothing else.

**Comment by poettering** [comment]
> So I gather it was technically hanging because it was waiting on wpa_supplicant or dbus? Shouldn't systemd be able to force the WiFI connection to drop?

Nah, if you manage your wifi with NM you manage it with NM, we won't interfere with that.

Let's close this, this is apparently a misconfiguration...
