### ISSUE TITLE
System hangs after reaching target *Reboot*

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#15919]
Using systemd 242, trying to reboot a server, which was in an error state, where writes were not completed, rebooting the system did not work.

```
# more /proc/1909/stack
[<0>] call_rwsem_down_write_failed+0x13/0x20
[<0>] nfsd_lookup_dentry+0x9e/0x3a0 [nfsd]
[<0>] nfsd_lookup+0x7f/0x130 [nfsd]
[<0>] nfsd4_proc_compound+0x3ed/0x700 [nfsd]
[<0>] nfsd_dispatch+0xf5/0x230 [nfsd]
[<0>] svc_process_common+0x4e3/0x730 [sunrpc]
[<0>] svc_process+0xe0/0xf0 [sunrpc]
[<0>] nfsd+0xe3/0x150 [nfsd]
[<0>] kthread+0x113/0x130
[<0>] ret_from_fork+0x22/0x40
[<0>] 0xffffffffffffffff
# more /proc/2028/stack
[<0>] rescuer_thread+0x2d7/0x320
[<0>] kthread+0x113/0x130
[<0>] ret_from_fork+0x22/0x40
[<0>] 0xffffffffffffffff
```

So the system was rebooted using `systemctl reboot`, but it did not complete.

![phaedra_down](https://user-images.githubusercontent.com/9318792/82882673-aea59800-9f41-11ea-82b1-477c9262fbd8.png)

Plugging in a USB KVM console was still possible, so Linux seems to have still worked.

As this only seems to happen in strange error conditions from Linux, is there a way, without having the systemd debug shell running by default, to get more output? Could systemd increase the error level after reaching the reboot target for example? As the journal has already stopped, that wouldn’t pollute the logs either, would it?

**Comment by arvidjaar** [comment]
> Could systemd increase the error level after reaching the reboot target for example?

Actually current systemd does force logging to console in systemd-shutdown. If you get no further output it implies systemd-shutdown was not executed or somehow hung even before first log outupt.

**Comment by poettering** [comment]
Maybe your printk is simply too low to see something interesting? We bump it now since 827156b33098cebcfb78e8afd17970c446394665. Are you after that commit?

What happens if you turn on debug logging when booting Linux? i.e. "debug" on the kernel cmdline option. Then reproduce the issue?

**Comment by poettering** [comment]
Closing due to lack of response.
