### ISSUE TITLE
RFE: journalctl: output format compatible with audit tools (ausearch)

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#15921]
**Is your feature request related to a problem? Please describe.**
Currently auditd stores separate logs in `/var/log/audit`. I'd like to discontinue using auditd for logging (but not for other audit control) and use only systemd-journald logs also for `ausearch` etc. `ausearch` is able to read logs also from standard input. The output format of `journalctl` is quite similar to format of `/var/log/audit/audit.log`, but `ausearch` does not understand it.

**Describe the solution you'd like**
Add new `audit` format for `journalctl` which can be directly read by audit tools, for example: `journalctl -b --output=audit | ausearch`.

So, this record from `journalctl --output=short-unix`
```
1590476099.070000 loora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

should be printed when `--output=audit` is specified in the format in `/var/log/audit/audit.log`:
```
type=SERVICE_START msg=audit(1590476099.070:34): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Describe alternatives you've considered**
1. Postprocess journalctl output to match audit.log (no changes required to journalctl or audit tools):
```
# journalctl -b _TRANSPORT=audit --output=short-unix | awk '{ print "type="$4" msg=audit("$1") " $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17 }' | ausearch -r
----
type=SERVICE_START msg=audit(1590476099.070000) pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' 
```

2. Enhance audit tools to understand some existing journalctl output format (for example syslog/short-unix or JSON). This could be useful even when not using journald. @stevegrubb?

3. Perhaps (some) search options of `ausearch` could be easily implemented also in `journalctl`. But format compatibility between journalctl and audit tools would still be needed in order to use the other audit tools like `audit2allow` to process SELinux AVC denials. Reimplementing `audit2allow` by `journalctl` does not seem to make sense.

**Comment by layderv** [comment]
If the maintainers agree with your proposed solution, I can take a look at this

**Comment by topimiettinen** [comment]
I implemented the feature, only to discover that `audit2allow` actually can read `journalctl` format directly and it can also parse user journals (like logs from Xorg which include SELinux AVC denials, when Xorg is enabled as object manager). So the audit output format is a bit useless. It could still be used to search logs with `ausearch`.

Is there interest for the feature otherwise? @layderv?

**Comment by layderv** [comment]
No particular other use cases for me @topimiettinen

**Comment by topimiettinen** [comment]
OK, let's close this then.
