### ISSUE TITLE
Linux: Fedora on VirtualBox, shutdown error: ScheduleShutdown

### ISSUE THREAD

**Issue by Leady12** [systemd/systemd#1592]
Hi there. 
Ive got a problem. Im working on Fedora by VitualBox and after I use shutdown -r time command I get error "Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown:Access denied" then system reboot. I saw  the topic with the same problem but it'is closed and I dont understand how can I fix it. Im new in it and I dont get most of things. Can someone explain step by step how exactly the fixing looks like?

**Comment by poettering** [comment]
Well, you get this if you lack the privileges to schedule a shutdown, but do have the priviliges to shutdown the system immediately. We fall back from scheduled shutdowns to immediate shutdowns if the privs for the former a lacking. Maybe we shouldn't do that though but fail with an error and do not fall back.

If you issue your command as root then scheduled shutdowns should work, no?

**Comment by Leady12** [comment]
I forgot to inform that I type it after I authenticate as root. When I try to do it as normal user it asks me for a root password.

**Comment by poettering** [comment]
do you have selinux enabled or so?

if you do, can you turn it off? does the issue go away then?

**Comment by alxpl** [comment]
Yes, SELinux plays a part in this:
https://bugzilla.redhat.com/show_bug.cgi?id=1276424

The bug is present in 222 but not in 219, if it's of any help.

**Comment by poettering** [comment]
OK, seems to be a problem in the selinux policy then. Since the policy is maintained in Fedora's selinux packages and not in systemd, closing this.
