### ISSUE TITLE
Add priority for DHCP lease requests

### ISSUE THREAD

**Issue by ijustlovemath** [systemd/systemd#15933]
**Is your feature request related to a problem? Please describe.**
I've been battling systemd-networkd for the last few hours trying to reliably get a DHCP lease after a reboot. I have a working configuration, eg
```
# /etc/systemd/network/25-wireless.network
[Match]
Name=wl*

[Network]
DHCP=ipv4
```

The line in the systemd journal indicating success is `May 26 15:20:54 x220 systemd-networkd[1892]: wlp3s0: DHCPv4 address 192.168.1.107/24 via 192.168.1.254`

This is triggered by an event that's handled by `dhcp4_handler` in `src/network/networkd-dhcp4.c`, specifically `dhcp_lease_ip_change`.

Right now the system just silently connects to the access point and seemingly does nothing before randomly being assigned an IP by the DHCP client. This can be quite frustrating because this silence feels like you've messed up the configuration, and documentation on this particular feature and its behavior is sparse.

**Describe the solution you'd like**
https://github.com/systemd/systemd/blob/1283366a90e8aa8713af449a0e3a0096c90648e3/src/network/networkd-dhcp4.c

It would be great if the polling infrastructure which fires this event could be configured, as right now it seems to take 40 seconds to 5 minutes to be assigned an IP, which really seems like a long time for getting a DHCP lease.

Not sure how this fits (or doesn't fit) into systemd's philosophy, but a command-line tool ala `resolvectl` which could craft and dispatch UDP messages for use by the following handler: https://github.com/systemd/systemd/blob/929d07ddcbbb50576ea8dc4a2295573b6d0ee3ee/src/libsystemd-network/sd-dhcp-client.c#L1677

would be a good start; that way we as users could force a reboot of the DHCP lease.

**Describe alternatives you've considered**
Switching back to equally problematic alternatives like dhcpcd, dhclient etc.

**Comment by poettering** [comment]
I am sorry, I really don't get what you are asking for? Can you elaborate?

**Comment by ijustlovemath** [comment]
Sure, thanks for taking the time! The main problem is that `systemd-networkd` takes too much time to get an IP when the built-in DHCP client is enabled. Additionally, it doesn't add very much to the system journal, so the user is left in the dark as to *why* the DHCP lease is taking so long to obtain.

The code links I gave are where it looks like we obtain the DHCP lease; it seems like the daemon only attempts to obtain a lease when it receives an appropriately formatted `DHCPMessage` over its UDP port; I'm proposing that if the timing cannot be adjusted, a new command line utility be added to retry DHCP lease renewal.

**Comment by poettering** [comment]
> Sure, thanks for taking the time! The main problem is that `systemd-networkd` takes too much time to get an IP when the built-in DHCP client is enabled.

Hmm, it should normally be pretty much instant.

> Additionally, it doesn't add very much to the system journal, so the user is left in the dark as to _why_ the DHCP lease is taking so long to obtain.

Turn on debug logging. `systemctl edit systemd-networkd`, then write: 

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

and save/exit. Then do "systemctl restart systemd-networkd". It will then output full debug output, and tell you what it is doing and waiting for.

**Comment by ijustlovemath** [comment]
It seems to be working now with the only change being the higher level of debug logging. Going to close this issue for now, thanks for weighing in!
