### ISSUE TITLE
dhcp server concepts need to be cleaned up

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#15943]
We can't really release before the DHCP server info exposure is cleaned up.

i.e. The SIP stuff is sometimes called SIP in .network files and sometimes SIPServer. THere's only an EmitXYZ= setting for someof the server types, and everything uses individual structure fields instead of arrays indexed by the server type. This needs to be cleaned up, since it leaks into various apis.

**Comment by yuwata** [comment]
@poettering #15967 was merged. So, should this be closed?

**Comment by poettering** [comment]
No, not yet. We need to clean up things like `sd_network_link_get_sip()` vs. `sd_network_link_get_sip_servers()` in sd-network.h still. i.e. only sd-dhcp got cleaned up so far, but what networkd then does with all this needs more love and be straightened out. It leaks into configuration file formats and such nad we should get this right before release
