### ISSUE TITLE
systemd-time-wait-sync hangs during boot and doesn't detect that /run/systemd/timesync/synchronized exists

### ISSUE THREAD

**Issue by gourvy** [systemd/systemd#15947]
**systemd version the issue has been seen with**
> v245.5 and v244.3 - not in 241

**Used distribution**
 > Custom distribution created with yocto - dunfell

**Expected behaviour you didn't see**
 > During some boots, systemd-time-wait-sync doesn't detect time synchronization with adjtimex. The problem has been solved with /run/systemd/timesync/synchronized (see https://github.com/systemd/systemd/issues/8683). So, with the presence of /run/systemd/timesync/synchronized systemd-time-wait-sync should have exited

**Unexpected behaviour you saw**
 > systemd-time-wait-sync hangs but /run/systemd/timesync/synchronized exists. No error log from this service, only some "adjtime state 5 status 40 time ..."

**Steps to reproduce the problem**
> mask the ntp client service, reboot, create the file "synchronized" and check the status of systemd-time-wait-sync
`systemctl mask systemd-timesyncd; reboot`
`mkdir /run/systemd/timesync; touch /run/systemd/timesync/synchronized; systemctl status systemd-time-wait-sync`
If systemd-time-wait-sync is still running, the problem is there. If it's exited, there's no problem. In my case it always fail.

Strange behaviour: if I restart manually the service systemd-time-wait-sync, the service notice /run/systemd/timesync/synchronized and exit properly. So, it seems that the problem appears only during boot time. Also, I didn't encountered the problem with systemd v241 (the build was slightly different, made from yocto - warrior).

**Comment by livelace** [comment]
Caught the same problem with 244.3. I use only systemd-timesyncd + systemd-time-wait-sync, there are no other time services.

**Comment by zeisss** [comment]
We are seeing the same thing on AWS after updating from Ubuntu 19.10 (systemd 242) to Ubuntu 20.04 LTS (systemd 245).

**Comment by spaetz** [comment]
I know nothing about systemd internals, but could it be that this file is now located at /run/systemd/timesync/synchronized ?
See commit https://github.com/pabigot/systemd/commit/e4c603518ba844e1fdee87160ec7511d9e2ef922 (referred from issue #8683)

**Comment by tmm1** [comment]
This bug is resolved in v246. Specifically this is a regression in https://github.com/systemd/systemd/commit/27c3112dcbd1b5f171c36c32550d9c6331375b0b which was fixed in https://github.com/systemd/systemd/commit/f6f4f5fe5395a57f10dd446c7266c53f0673eaac

**Comment by poettering** [comment]
Closing as per @tmm1's comment.
