### ISSUE TITLE
Flushing /dev/kmsg... takes 75 ms on systemd with SSD

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#15966]
$ systemd --version
    systemd 245 (245.5-3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

On Debian Sid/unstable trying to decrease the long systemd-journald start-up time, adding `debug` to the Linux kernel command line shows that flushing `/dev/kmsg` takes a noticeable amount of time. This is a Dell Latitude E7250 with an SSD (AHCI), but I could reproduce this on NVMe systems too.

    [    6.217060] systemd-journald[280]: Flushing /dev/kmsg...
    [    6.292206] systemd-journald[280]: systemd-journald running as PID 280 for the system.

75 ms is over ten percent of the start-up time here.

Setting `ReadKMsg=no` in `/etc/systemd/journald.conf` indeed gets rid of this.

Being ignorant, I’d thought reading in a few hundred lines of text wouldn’t take that long. It’d be great if the code could be optimized, or if not possible, reading in `/dev/kmsg` is moved out the startup path.

### With `ReadKMsg=yes` ###

```
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.7.0-rc5-amd64 root=UUID=aa6034bb-8cc1-4111-a0a7-9b3f5e13e281 ro quiet noisapnp initcall_debug log_buf_len=8M random.trust_cpu=on cryptomgr.notests i915.fastboot=0 systemd.verity=0 acpi_pm_good debug
[    0.026304] Kernel command line: BOOT_IMAGE=/vmlinuz-5.7.0-rc5-amd64 root=UUID=aa6034bb-8cc1-4111-a0a7-9b3f5e13e281 ro quiet noisapnp initcall_debug log_buf_len=8M random.trust_cpu=on cryptomgr.notests i915.fastboot=0 systemd.verity=0 acpi_pm_good debug
[    0.561649] systemd-udevd[122]: Starting version 245.5-3
[…]
[    6.206835] systemd-journald[280]: Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
[    6.208098] systemd-journald[280]: Journal effective settings seal=no compress=yes compress_threshold_bytes=512B
[    6.208883] systemd-journald[280]: Fixed min_use=16.0M max_use=159.5M max_size=19.9M min_size=512.0K keep_free=79.7M n_max_files=100
[    6.210637] systemd-journald[280]: Reserving 36316 entries in hash table.
[    6.211876] systemd-journald[280]: Vacuuming...
[    6.212880] systemd-journald[280]: Vacuuming done, freed 0B of archived journals from /run/log/journal/88c996ae63fc4f929b2dad45836260f4.
[    6.217060] systemd-journald[280]: Flushing /dev/kmsg...
[    6.292206] systemd-journald[280]: systemd-journald running as PID 280 for the system.
[    6.293588] systemd-journald[280]: Sent READY=1 notification.
[    6.293691] systemd-journald[280]: Sent WATCHDOG=1 notification.
```

### With `ReadKMsg=no` ###

```
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.7.0-rc5-amd64 root=UUID=aa6034bb-8cc1-4111-a0a7-9b3f5e13e281 ro quiet noisapnp initcall_debug log_b
uf_len=8M random.trust_cpu=on cryptomgr.notests i915.fastboot=0 systemd.verity=0 acpi_pm_good debug
[    0.000000] Kernel command line: BOOT_IMAGE=/vmlinuz-5.7.0-rc5-amd64 root=UUID=aa6034bb-8cc1-4111-a0a7-9b3f5e13e281 ro quiet noisapnp initcall_debu
g log_buf_len=8M random.trust_cpu=on cryptomgr.notests i915.fastboot=0 systemd.verity=0 acpi_pm_good debug
[    0.474876] systemd-udevd[122]: Starting version 245.5-3
[…]
[    8.365307] systemd-journald[292]: Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
[    8.366348] systemd-journald[292]: Journal effective settings seal=no compress=yes compress_threshold_bytes=512B
[    8.366946] systemd-journald[292]: Fixed min_use=16.0M max_use=159.5M max_size=19.9M min_size=512.0K keep_free=79.7M n_max_files=100
[    8.368561] systemd-journald[292]: Reserving 36316 entries in hash table.
[    8.369382] systemd-journald[292]: Vacuuming...
[    8.369966] systemd-journald[292]: Vacuuming done, freed 0B of archived journals from /run/log/journal/88c996ae63fc4f929b2dad45836260f4.
[    8.370576] systemd-journald[292]: systemd-journald running as PID 292 for the system.
[    8.371298] systemd-journald[292]: Sent READY=1 notification.
[    8.371918] systemd-journald[292]: Sent WATCHDOG=1 notification.

**Comment by Malvineous** [comment]
If you use `dmesg` to retrieve the messages, is it any faster?  Just thinking that if `dmesg` takes the same amount of time, the delay is probably in the kernel rather than in systemd-journald.

**Comment by poettering** [comment]
i wouldn't be surprised if this is a bit slow: for log entries that have device info attached we'll check the udev db, and that could be quite a bit. We could certainly improve that, and cache a few things. In fact there's already #8361 filed about this, hence closing as duplicate.

**Comment by paulmenzel** [comment]
If it’s known to be slow, shouldn’t it taken out of the boot path?

Would an option be accept to only read in `/dev/kmsg` once the system is considered booted?

**Comment by poettering** [comment]
> If it’s known to be slow, shouldn’t it taken out of the boot path?

Why? We aim for correctness, being comprehensive and debuggable. Just being quick is a secondary goal only.

> Would an option be accept to only read in `/dev/kmsg` once the system is considered booted?

We care about global ordering to the level this is possible, i.e. we want that earlier messages are appear earlier in the log stream. If you do things async then you'll interleave earlier kmsg data with later regular log data, and global ordering will be interfered with.

I am pretty sure caching of udev props is the way to go. We have such caching for process metadata already. it can be used as blueprint for doing the same kind of caching for devices too. Would be delighted to review a patch.
