### ISSUE TITLE
journalctl -r -n flags incorrectly processed

### ISSUE THREAD

**Issue by ceecko** [systemd/systemd#1596]
I'm running version `208` - unfortunately I can't install the latest version but the issues seems to be present in the `master` as well as of writing.

```
journalctl --version
systemd 208
+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ
```

Consider the following log entries:

```
2015-01-01 log1
2015-02-02 log2
2015-03-03 log3
2015-04-04 log4
```

Issuing `journalctl -n 2` properly shows this:

```
2015-03-03 log3
2015-04-04 log4
```

However issuing `journalctl -r -n 2` shows this:

```
2015-02-02 log2
2015-01-01 log1
```

This is because in [journalctl.c](https://github.com/systemd/systemd/blob/e88a5a5bde28c55da86ec5ea33fd9b88f4f5878a/src/journal/journalctl.c) line 2087 skips journal by `arg_lines` but doesn't take into account `arg_reverse`. Consequently on line 2153 the journal is read from `arg_lines` backwards which ultimately skips first `arg_lines` lines.

The expected output of `journalctl -r -n 2` is:

```
2015-04-04 log4
2015-03-03 log3
```

**Comment by fwjavox** [comment]
This still applies to version `239`. A workaround is to specify the cursor of the point where you want to start reading.

**Comment by timo-schluessler** [comment]
I can confirm this bug.
It is fixed by first checking for arg_reverse and then for arg_lines. The following patch fixes this.

[fix-nr-of-lines-when-reversing.diff.gz](https://github.com/systemd/systemd/files/3406035/fix-nr-of-lines-when-reversing.diff.gz)

**Comment by dtardon** [comment]
@timo-schluessler Could you submit your patch as a pull request?

**Comment by timo-schluessler** [comment]
Sorry for my late reply. Please find the pull request at https://github.com/systemd/systemd/pull/14552.
