### ISSUE TITLE
$path is different

### ISSUE THREAD

**Issue by alicera** [systemd/systemd#15970]
I use the  " echo $PATH " in the terminal
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

but  I set the service to run shell script and the shell script use the  " echo $PATH "
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

why  $path is different
it will cause some command not found

**Comment by poettering** [comment]
systemd sets a default path set at build time for all userspace processes it spawns. Login shells can set their own $PATH of course, if they like, but this only applies to the specific shell instance, not the system services or any other processes. It's how UNIX works: environment variables are inherited down the process tree, but do not propagate upwards or sidewards

**Comment by alicera** [comment]
how can I  improve the situation?

node install command 
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source ~/.nvm/nvm.sh # . ~/.nvm/nvm.sh
nvm install v12.13.0
nvm use v12.13.0`

I install the node and command the "which node"  in the host terminal 
it will print the "/home/lvy/.nvm/versions/node/v12.13.0/bin/node "

but I use the *.service to command the "which node" 
it will print the "/usr/bin/node "

I expect the "/home/lvy/.nvm/versions/node/v12.13.0/bin/node "
