### ISSUE TITLE
Cache not found records

### ISSUE THREAD

**Issue by Trolldemorted** [systemd/systemd#15983]
**Is your feature request related to a problem? Please describe.**
I forgot to add an AAAA record to a wildcard domain. Client software now asks resolved for the IP (unfortunately A and AAAA), and resolved responds the former from the cache and the latter after asking the upstream (opendns) every time.

I noticed this at some point and created the AAAA record, but now the opendns caches remember that the AAAA record does not exist, and thus don't ask the authoritative nameserver.

If resolved would cache that the AAAA does not exist, I would not be bombarding opendns with thousands of requests per minute.

**Describe the solution you'd like**
Resolved should cache all results, not only the successful ones.

**Comment by ldruschk** [comment]
What does your resolved configuration look like? Usually resolved should cache negative responses unless configured otherwise: https://www.freedesktop.org/software/systemd/man/resolved.conf.html#Cache=

**Comment by Trolldemorted** [comment]
```
alice@enoVM:~$ cat /etc/systemd/resolved.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#DNSOverTLS=no
#Cache=yes
#DNSStubListener=yes
#ReadEtcHosts=yes
```

Since the default is yes, it should work in theory?

**Comment by Trolldemorted** [comment]
Since we assume this is a TTL issue I am closing this issue for now. Sorry for bothering you!
