### ISSUE TITLE
Pulling a public docker image fails

### ISSUE THREAD

**Issue by inducer** [systemd/systemd#1599]
Doing this:

```
machinectl pull-dkr --verify=no inducer/relate-runpy-i386 --dkr-index-url=https://index.docker.io/
```

says this:

```
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'inducer/relate-runpy-i386' with reference 'latest', saving as 'relate-runpy-i386'.
Download of https://index.docker.io/v1/repositories/inducer/relate-runpy-i386/images complete.
Index lookup succeeded, directed to registry registry-1.docker.io.
Downloading 1.4K for https://auth.docker.io/v2/token/?scope=repository:inducer/relate-runpy-i386:pull&service=registry.docker.io.
Download of https://auth.docker.io/v2/token/?scope=repository:inducer/relate-runpy-i386:pull&service=registry.docker.io complete.
Downloading 25.5K for https://registry-1.docker.io/v2/inducer/relate-runpy-i386/manifests/latest.
Got 61% of https://registry-1.docker.io/v2/inducer/relate-runpy-i386/manifests/latest. 943ms left at 10.4K/s.
Download of https://registry-1.docker.io/v2/inducer/relate-runpy-i386/manifests/latest complete.
Invalid JSON Manifest
Exiting.
```

Visiting https://registry-1.docker.io/v2/inducer/relate-runpy-i386/manifests/latest in a browser gives this:

```
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"repository","Name":"inducer/relate-runpy-i386","Action":"pull"}]}]}
```

although I'm not sure whether `importd` (?) sends cookies or something that would lead to a different response. At any rate, the image is public, but I can't pull it.

**Comment by inducer** [comment]
Forgot to say

```
$ machinectl --version
systemd 227
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

(installed from Debian's `systemd-container` 227-2.)

**Comment by runcom** [comment]
in order to pull from the docker hub (which runs registry v2), even if the image is public, you need to send the Bearer token in an `Authorization` header (after you get it from the token service, which machinectl I can see is doing)
the issue here may seem to lie in the fact the Bearer token is somehow invalid or something wrong is happening in the response of the pull manifest request (probably the latter)

**Comment by vito** [comment]
I've noticed pulling fail after working fine for a while (~5mins). In my case it was a `401` status code error, but maybe it depends on the code path (i.e. maybe this one tries to unmarshal the JSON before checking the status code).

Perhaps it acquires a token at the start but the duration of the token is short enough to expire while pulling?

**Comment by poettering** [comment]
We decided to drop dkr support form importd, see #2133. closing.
