### ISSUE TITLE
Support %f specifier in DeviceAllow option

### ISSUE THREAD

**Issue by askask** [systemd/systemd#1602]
I have a service file like this

```
[Unit]
Description=Device driver for %f
After=%i.device
BindsTo=%i.device

[Service]
ExecStart=/usr/local/bin/rb %f
DevicePolicy=strict
DeviceAllow=%f rw
…
```

which produces the following output from systemd (version 227)

```
Okt 18 13:23:08 hostname systemd[1]: [/etc/systemd/system/rb@.service:16] Invalid device node path '%f'. Ignoring.
```

The service file is for a device driver (which gets started by udev SYSTEMD_WANTS) that should only have access to the device for which it was started, so it would be nice if systemd could support expansion of %f here.

**Comment by poettering** [comment]
Seems reasonable enough to add support for specifier expansion support to DeviceAllow=.
