### ISSUE TITLE
API(sd_journal_next)stops offering next line when timejump backwards, so /var/log/message stops logging

### ISSUE THREAD

**Issue by Zoe-Lyu** [systemd/systemd#16037]
Using CentOS7 with systemd-219 + rsyslog 8.2004.

This is very similar to another BUG, which can reproduce the problem in a similar way. The link is as follows.：
As I can see, rsyslog has fixed code problems on the imjournal side, and systemd has previously fixed an issue related to time-jumping. However, the time-judgment problem in the API (sd_journal_next) still seems to exist and is abnormal after timejump backwards. It seems that this will cause imjournal to fail to get to the next log, and /var/log/message stops the record.

By the way, there will be systemd@***.journal~ file appears, the “~” is a bit strange.

**Comment by poettering** [comment]
We only track issues in the two most recent systemd versions here, and the submission form should have made that very clear, to minimize frustration. Current version is 244 and 245. For everything older (and rsyslog is waaay too old) please contact your downstream.
