### ISSUE TITLE
systemd-journald doesn't respect configuration file

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#16034]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > Persistent journal enabled by selecting `Storage=persistent` in `/etc/systemd/journald.conf`

**Unexpected behaviour you saw**
 > The journal is not persistent across boots.

    $ ls -al /var/log/journal/   # There should be another directory here
    total 20
    drwxr-sr-x+ 3 root systemd-journal        4096 Dec 20 09:08 .
    drwxr-xr-x  9 root root                   4096 Jun  1 00:00 ..
    drwxr-sr-x+ 2 root systemd-journal-remote 4096 Dec 20 09:08 remote
    # This should say something about /var/log/journal/:
    $ sudo systemctl status systemd-journald.service
    ● systemd-journald.service - Journal Service
         Loaded: loaded (/etc/systemd/system/systemd-journald.service; static; vendor preset: disabled)
         Active: active (running) since Mon 2020-06-01 09:59:29 PDT; 9min ago
    TriggeredBy: ● systemd-journald-audit.socket
                 ● systemd-journald.socket
                 ● systemd-journald-dev-log.socket
           Docs: man:systemd-journald.service(8)

       Main PID: 297 (systemd-journal)
         Status: "Processing requests..."
          Tasks: 1 (limit: 6646)
         Memory: 7.7M
         CGroup: /system.slice/systemd-journald.service
                 └─297 /usr/lib/systemd/systemd-journald

    Jun 01 09:59:29 myserver systemd-journald[297]: Journal started
    Jun 01 09:59:29 myserver systemd-journald[297]: Runtime Journal (/run/log/journal/5f415173375c4f44842cefa3f72db2e3) is 3.7M, max 30.0M, 26.2M free.
    Jun 01 09:59:29 myserver systemd-journald[297]: Runtime Journal (/run/log/journal/5f415173375c4f44842cefa3f72db2e3) is 3.7M, max 30.0M, 26.2M free.
    Warning: journal has been rotated since unit was started, output may be incomplete.

**Comment by poettering** [comment]
Did systemd-journald-flush get started? What actually *is* your journald.conf?

**Comment by archenemies** [comment]
My apologies! The Storage parameter was being overridden by another file in '/etc/systemd/journald.conf.d/`.
