### ISSUE TITLE
Dependencies on generated units do not work properly

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#16038]
If a unit (such as a swap unit) is generated, `Requires=` and `After=` dependencies on it do not seem to work properly.

**Comment by poettering** [comment]
hmm? can you give an example what doesn't "work properly"? This is an extremely vague bug report...

**Comment by DemiMarie** [comment]
@poettering If I have `Requires=dev-mapper-swap.swap` in a unit file, and `/dev/mapper/swap` doesn’t exist at boot, the unit won’t be started, even though `dev-mapper-swap.swap` is started later.

**Comment by poettering** [comment]
please provide logs of a boot like this (ideally with systemd in debug mode, i.e. `systemd.log_level=debug` on kernel cmdline) , otherwise there's little we can do.

my educated guess: some ordering loop, and systemd fixed it up by dropping some job. it will report this in the logs.

**Comment by poettering** [comment]
Closing due to lack of response
