### ISSUE TITLE
Systemd crashes Gnome Shell when launching terminal without kdbus=0 set on boot

### ISSUE THREAD

**Issue by Nikki1993** [systemd/systemd#1604]
Oct 18 11:09:05 arch_dellxps systemd[3781]: Starting DBUS1: org.gnome.Terminal...
Oct 18 11:09:05 arch_dellxps systemd[3781]: Started DBUS1: org.gnome.Terminal.
Oct 18 11:09:05 arch_dellxps systemd-bus-proxyd[3811]: Failed to start bus client: Connection reset by peer
Oct 18 11:09:05 arch_dellxps systemd-bus-proxyd[3811]: Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/util.c:318, function safe_close(). Aborting.

Gnome Shell crashes and displays Oops, something went wrong. Arch with Gnome Shell 3.18

So far happens when running linux-zen but doesn't on mainline linux for some reason. However, putting kdbus=0 on boot fixes it for zen.

**Comment by Nikki1993** [comment]
Here is the conversation from linux-zen github https://github.com/zen-kernel/zen-kernel/issues/35

**Comment by heftig** [comment]
FTR, downstream bug: https://github.com/zen-kernel/zen-kernel/issues/35
Logs: https://drive.google.com/file/d/0BzuUKFr0QgadQktVODZWckNqX2c/view?usp=sharing

**Comment by mbiebl** [comment]
@Nikki1993 it is systemd, not SystemD

**Comment by Nikki1993** [comment]
My bad :P I knew that!

**Comment by poettering** [comment]
Duplicate of #1591 which was just fixed via #1595. Closing.
