### ISSUE TITLE
implement DNS-SD subtypes in systemd-resolved

### ISSUE THREAD

**Issue by Kxuan** [systemd/systemd#16069]
**Is your feature request related to a problem? Please describe.**
The [DNS-SD RFC](https://tools.ietf.org/html/rfc6763#section-7.1) use subtype to represent a more detail protocol of primary protocols.
But systemd-resolved is not support the subtypes currently.

**Describe the solution you'd like**

Add a new config field named `Subtype` in `*.dnssd`. When the user specify one or more `Subtype`, systemd-resolved should response to corresponding subtype query request.

**Comment by poettering** [comment]
Closed by #30500
