### ISSUE TITLE
systemd-user-runtime-dir creates /run/user/uid/inaccessible with the wrong SELinux context

### ISSUE THREAD

**Issue by bauen1** [systemd/systemd#16066]
**systemd version the issue has been seen with**
> sysadmin@selinux-pr-test1:~$ systemctl --version
> systemd 245 (245.5-3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > debian unstable

**Expected behaviour you didn't see**
```
sysadmin@selinux-pr-test1:~$ ls -AlZd /run/user/1000/inaccessible
d---------. 3 sysadmin sysadmin staff_u:object_r:user_runtime_t:SystemLow 60 Jun  4 16:49 /run/user/1000/inaccessible
```

**Unexpected behaviour you saw**
```
sysadmin@selinux-pr-test1:~$ ls -AlZd /run/user/1000/inaccessible
d---------. 3 sysadmin sysadmin system_u:object_r:user_runtime_t:SystemLow 60 Jun  4 16:49 /run/user/1000/inaccessible
```

**Steps to reproduce the problem**
1. Install debian minimal
2. Install refpolicy from git
3. Logout / Login
4. Observe the context of `/run/user/uid/inaccessible` it should match the user part of `id -Z`

It is also important to note that the context of `/run/user/1000/` is set correctly.

This might be caused by using `mkdir` instead of `mkdir_label` at https://github.com/systemd/systemd/blob/222633b646eb8b728e066bbc0bfb865eb8907566/src/shared/dev-setup.c#L99
But I'm no expert of the codebase.

**Comment by topimiettinen** [comment]
Confirmed, but since the directory should be inaccessible, a label belonging to the user would actually make the item slightly more accessible. Would this change be desirable?

Perhaps instead the refpolicy should have a new type `inaccessible_t` for use with inaccessible nodes. This type would have no TE rules allowing any access, except for PID1/`init_t` to create them.

**Comment by bauen1** [comment]
> Confirmed, but since the directory should be inaccessible, a label belonging to the user would actually make the item slightly more accessible. Would this change be desirable?

I'd argue that for the sake of consistency it should.
In my humble opinion access to this directory should be done using type enforcement.
At least in refpolicy `system_u` also isn't ubac separated for practical reasons, so something running as `user_u:user_r:mydomain_t` can access a directory labeled `system_u:object_r:file_type_t` as long as an appropriate TE rule is in place.

> Perhaps instead the refpolicy should have a new type `inaccessible_t` for use with inaccessible nodes. This type would have no TE rules allowing any access, except for PID1/`init_t` to create them.

I agree, I'm already working on adding such a type to refpolicy.

**Comment by topimiettinen** [comment]
Great! In addition to `/run/user/*/inaccessible/*`, there's `/run/systemd/inaccessible/*`. Maybe systemd should just bind mount `/run/systemd/inaccessible` as `/run/user/*/inaccessible`. Then inaccessible items would need to be created only once by PID1 and `systemd-user-runtime-dir` would need fewer capabilities.

**Comment by bauen1** [comment]
With a bind mount `/run/user/*/inaccessible/*` would still be labeled `system_u:*`.
The additional capabilities are only `mknod`.
Under SELinux I believe `systemd-user-runtime-dir` can be further confined to only `create` / `setattr` on the block device / character files under `/run/user/*/inaccessible/*`

**Comment by topimiettinen** [comment]
Maybe bind mounting is not any better.

About the context, should we wait for the updated refpolicy and use the new inaccessible type or is there a need to fix this earlier? I suppose the fix should amount to what you already found out (replace mkdir() with mkdir_label()).

**Comment by bauen1** [comment]
It doesn't change anything in practice, apart from being consistent, so there shouldn't be a need to wait for refpolicy to update.

Looking at the code, I would also guess that `mknod` or `makedev` would have to be replace with the appropriate selinux aware function.
https://github.com/systemd/systemd/blob/222633b646eb8b728e066bbc0bfb865eb8907566/src/shared/dev-setup.c#L101

**Comment by topimiettinen** [comment]
I meant waiting for the `inaccessible_t` to be implemented and released by refpolicy, probably also wait for distros to catch up with updated version. For the `system_u` -> `user_u` change there would be no need to wait if the policy is already in shape. But shouldn't it also need fixing too, where else than [userdomain policy](https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/system/userdomain.fc) would the new label come from for `mk*_label()`?

**Comment by bauen1** [comment]
There should be no need to hardcode `inaccssible_t` (which will probably have a slightly different name).
Using `mkdir_label`  will eventually lookup the context for `/run/user/uid/inaccessible` here:
https://github.com/systemd/systemd/blob/2df0df56dddc758607ea503006db0997d8e0aec0/src/basic/selinux-util.c#L396-L400
If no context is found, nothing will happen, this is the current behavior.
Once the policy has a file context for `/run/user/uid/inaccessible` the context will be set correctly, no matter the name.

Test program to confirm this:
```C
/* gcc systemd-selinux-test.c -lselinux -o systemd-selinux-test */
#include <selinux/selinux.h>
#include <selinux/label.h>

#include <stdlib.h>
#include <errno.h>
#include <stdio.h>

static struct selabel_handle *hnd = NULL;

int main(void) {
    hnd = selabel_open(SELABEL_CTX_FILE, NULL, 0);
    if (hnd == NULL) {
        perror("selabel_open");
        return EXIT_FAILURE;
    }

    char *filecon = NULL;
    int r = selabel_lookup_raw(hnd, &filecon, "/run/user/1000/inaccessible", 0);
    if (r < 0) {
        if (errno == ENOENT) {
            /* current behaviour */
            printf("no entry, skipping!\n");
        } else {
            perror("selabel_lookup_raw");
        }
    } else {
        /* correctly set the context on file creation */
        freecon(filecon);
    }
}
```

**Comment by bauen1** [comment]
@doverride has discovered that the change in #16118 has lead to a regression in 246-rc1
Because `systemd-user-runtime-dirs` runs before `systemd --user` it creates `/run/user/$UID/systemd/inaccessible` and `/run/user/$UID/systemd` with the wrong SELinux context.
Once `systemd --user` runs it can't access `/run/user/$UID/systemd` due to the wrong label.
