### ISSUE TITLE
Suggestions for logind to think I'm "docked"?

### ISSUE THREAD

**Issue by hahuang65** [systemd/systemd#16077]
I'm stuck in this situation where I can't figure out how to do what I want with `logind`'s `LidSwitch` options.

I have a laptop where I'd like it to behave like a regular laptop when it's connected to power or when I'm using it on it's own unplugged. However, when I'm connected to power AND a single monitor, I'd like it not to suspend when I close the lid (and the monitor is off, because I share the monitor with 2 other computers)

Currently what happens is, if I'm using this laptop, then switch my monitors input, this laptop goes to sleep, and when I want to come back to it, I need to flip open the lid, and press a button to wake it, and sometimes even restart my Bluetooth services for my keyboard and mouse to work. This gets old pretty fast. I'd like it simply not to sleep if it's plugged into power and it's got a monitor attached (even if it's not on the current input, not sure if this is even possible).

The `HandleLidSwitchDocked` only applies when a computer is `Docked` or when there are more than 1 monitor. I don't seem to satisfy either situation.

I'm wondering if there are any suggestions for me?

**Comment by arvidjaar** [comment]
> The `HandleLidSwitchDocked` only applies when a computer is Docked or when there are more than 1 monitor. I don't seem to satisfy either situation.

It applies when logind detects at least one external monitor. What systemd version do you have? What is content of /sys/class/drm/?

**Comment by hahuang65** [comment]
```
$ systemctl --version
systemd 245 (245.6-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

```
$ ls -1 /sys/class/drm
card0
card0-DP-1
card0-DP-2
card0-eDP-1
renderD128
version
```

**Comment by arvidjaar** [comment]
How exactly you "switch monitors output"? Do you connect external monitor and then close lid? Please show `grep . /sys/class/drm/*/{enabled,status}` after external monitor is connected but before lid is closed.

**Comment by hahuang65** [comment]
Most of the time, I have the laptop lid already closed, and I switch the input of the monitor to HDMI 1, which is what the laptop is connected to. However, usually I have to  open the lid of the laptop and press a button to wake it up, which is a little annoying.

Here is the info you asked for:

```
$ grep . /sys/class/drm/*/{enabled,status}
/sys/class/drm/card0-DP-1/enabled:enabled
/sys/class/drm/card0-DP-2/enabled:disabled
/sys/class/drm/card0-eDP-1/enabled:disabled
/sys/class/drm/card0-DP-1/status:connected
/sys/class/drm/card0-DP-2/status:disconnected
/sys/class/drm/card0-eDP-1/status:connected
```
Turns out, its the same whether the lid is closed or not when I'm running it.

**Comment by arvidjaar** [comment]
> ```
>/sys/class/drm/card0-DP-1/enabled:enabled
>/sys/class/drm/card0-DP-1/status:connected
>```

Well, this is external monitor enabled and connected. It should trigger `HandleLidSwitchDocked` action. Next step I guess is to enable logind debug log level, try lid close and upload resulting logs.

**Comment by arvidjaar** [comment]
> I have the laptop lid already closed, and I switch the input of the monitor to HDMI 1

Sorry, this is confusing. If you close lid without having any external monitor it is expected that logind initiates `HandleLidSwitch` and not `HandleLidSwitchDocked` action. Also your output shows no HDMI at all. If you mean you disconnect DP-1, again - you lose external monitor in this case so logind behavior is expected.

I guess you will need to describe in more details starting from the beginning what you do, at which point in time you connect external monitor, to which output you connect it, when you close lid etc.

**Comment by hahuang65** [comment]
Sorry for the confusion. Here is my use-case, and keep in mind, maybe I'm completely using these settings wrong and my use-case isn't even supported.

I have a single monitor with 3 computers attached to it. For simplicity's sake, let's just assume it's 2, my Macbook and my Arch Laptop.

My Arch Laptop is connected via DisplayPort on the laptop side, to HDMI1 on the monitor side.
The Macbook is connected via DisplayPort on the laptop side, to HDMI2 on the monitor side.

When I switch my monitors input from HDMI1 to HDMI2, the Arch laptop will go to sleep, I'm guessing because the lid is closed, I'm not entirely sure. Sometimes it stays awake for a little bit, and sometimes it stays awake for a LOOONG time. I'm not really sure.

In any case, when I switch back from HDMI2 to HDMI1, I frequently need to open the lid for the Arch laptop and press a key or two to wake it up, and often have to manually restart `bluetoothd` in order for my keyboard to work again.

I was HOPING that the `HandleLidSwitchDocked` could help me keep the laptop on indefinitely while it's plugged into power and the monitor (even if the monitor isn't actively displaying that laptop).

**Comment by arvidjaar** [comment]
That is rather different problem from what you described initially, is not it?

> When I switch my monitors input from HDMI1 to HDMI2, the Arch laptop will go to sleep, I'm guessing because the lid is closed, I'm not entirely sure.

That's correct. logind installs handler that checks lid state on every even loop. As your external monitor is disconnected and lid is closed, system is no more considered docked.

> Sometimes it stays awake for a little bit, and sometimes it stays awake for a LOOONG time.

Yes, that is certainly not nice and inconsistent. That is real bug here.

> I was HOPING that the HandleLidSwitchDocked could help me keep the laptop on indefinitely while it's plugged into power and the monitor (even if the monitor isn't actively displaying that laptop).

What makes you believe monitor remains plugged in? Disable lid close action entirely and provide the same grep output after monitor was switched to another input while lid is closed. You likely need to either type in blindly (prepare command line and just hit RETURN) or use network logon.

**Comment by hahuang65** [comment]
No, I don't think the monitor remains "plugged in" after I switch it's input. Do you have any suggestions on how I might be able to keep my laptop from sleeping without changing how it should behave when it's not physically attached to a monitor?

**Comment by arvidjaar** [comment]
You can manually inhibit suspend before you are going to switch off monitor. See `man systemd-inhibit`.

**Comment by poettering** [comment]
systemd operates on what the kernel exports there in sysfs.

When you switch inputs on your display, what happens to those sysfs enabled/connected files?

**Comment by poettering** [comment]
Closing due to lack of response
