### ISSUE TITLE
systemd-boot: Support TCG/OPAL pre-boot authentication

### ISSUE THREAD

**Issue by tadfisher** [systemd/systemd#16089]
**Is your feature request related to a problem? Please describe.**
Users of self-encrypting disks (e.g. TGC OPAL) have to rely on vendor-provided or janky open-source pre-boot authentication images to unlock disks before loading an EFI boot loader from the ESP. 

These know nothing about systemd-boot or the Boot Loader Specification, thus their integration amounts to soft-rebooting the system to run through the EFI boot process with the disk unlocked. 

In addition, the open-source options (such as [sedutil's PBA](https://github.com/Drive-Trust-Alliance/sedutil)) boot a Linux kernel and userland to unlock the drive with a utility program, which is somewhat overkill.

**Describe the solution you'd like**
`bootctl` is an ideal tool to install and manage a pre-boot authenticator for self-encrypting drives, because of its integration with `systemd-boot` and existing implementation in Linux distributions.

I can imagine two implementation options:

1. bootctl installs a small EFI image (the PBA) into the shadow MBR. This image contains the (encrypted) key hash, prompts the user for a passphrase if needed, and unlocks the drive containing the real systemd-boot EFI image. It can then "chainload" systemd-boot using the EDK's `LoadImage` or similar.
2. systemd-boot itself could handle PBA duties: bootctl installs a copy of the systemd-boot EFI image to the shadow MBR, and systemd-boot performs drive unlocking as above prior to loading the boot menu entries and booting the system.

The advantage of (1) is that systemd-boot itself would not need to be modified, and the PBA image could possibly chainload into alternative bootloaders.

The advantage of (2) is the reuse of systemd-boot's EFI stub and better integration with its UI.

**Describe alternatives you've considered**
I have considered creating a PBA image using an EFISTUB kernel and Plymouth for a graphical prompt.

I have also considered implementing (1), but I'm still learning how to do this.

**Comment by UtilFunction** [comment]
Any updates on this one?

**Comment by savely-krasovsky** [comment]
@poettering I would highlight that PBA is the only they to encrypt both Windows and Linux in dual boot setups. Because as far as I know Windows cannot reuse SID/Admin1 password to create own Locking Ranges after setting up them in Linux using `cryptsetup`.

There were [attempts](https://github.com/necauqua/opal-uefi-greeter) to create small unlocker, but `systemd-boot` still seems to be the ideal candidate.

I understand that probably this is quite niche case.
