### ISSUE TITLE
Add URL to bug report template to current issue numbers upstream

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#16083]
In this bug form one sees

> **NOTE:** Do not submit bug reports about anything but the two most recently released systemd versions upstream!

Please add a link to help the user find what those version numbers are. They are not seen anywhere on https://github.com/systemd/systemd/ etc.

**Comment by dnicolodi** [comment]
https://github.com/systemd/systemd/releases

**Comment by jidanni** [comment]
Good. So it should say:
> NOTE: Do not submit bug reports about anything but the two most https://github.com/systemd/systemd/releases !

**Comment by jidanni** [comment]
(Plus "upstream" wasn't valid, as we are already reading this upstream.)

**Comment by poettering** [comment]
Fix waiting in #16102
