### ISSUE TITLE
logged module loading error at bootup

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#161]
This should be suppressed. It happens inside the initrd and on the real system:
  Jun 11 11:17:24 ank systemd[1]: Failed to insert module 'kdbus'

**Comment by poettering** [comment]
Hmm, the new log_full() in kmod-setup.c line really should show the actual error happening there.

@kaysievers we now log this always, except that we do so on LOG_DEBUG only for some modules. Did you see this when you turned on debug logging? Or durin normal operation?

**Comment by kaysievers** [comment]
I have no specific debug setting, I would know of. It is 'make install' from -git and no options or config.

**Comment by poettering** [comment]
@kaysievers I have now pushed d814f9904bb9705070dde8458464b8afe6cfbb22, can you rerun things like that, what's the precise message you see then?

**Comment by kaysievers** [comment]
Jun 11 12:44:16 ank systemd[1]: Failed to insert module 'kdbus': Function not implemented

**Comment by poettering** [comment]
@kaysievers can you recheck now?
