### ISSUE TITLE
journald missed standardoutput logs

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#16103]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 >243

**Expected behaviour you didn't see**
 > Jun 09 04:27:42 localhost.localdomain test_journal[3845]: Hi
    Jun 09 04:27:42 localhost.localdomain test_journal[3845]: Hi
    Jun 09 04:27:42 localhost.localdomain test_journal[3845]: Hi

**Unexpected behaviour you saw**
 >Jun 09 04:27:42 localhost.localdomain test_journal[3845]: Hi 

**Steps to reproduce the problem**
systemctl restart journal-test-printf.service
> the test.service is:
[Unit]
Description=journal test printf
After=syslog.target

[Service]
ExecStart=/usr/sbin/test_journal
KillMode=process
StandardOutput=journal
[Install]
WantedBy=multi-user.target

test_journal.cpp is shown as below:
#include <iostream>
using namespace std;
int main()
{
    for(int i=0;i<3;i++){
    char *p="Hi";
    printf("%s", p);
    fflush(stdout);
    printf("\n");
    }
    return 0;
}

**Comment by mrc0mmand** [comment]
I think this might be the same issue as https://github.com/systemd/systemd/issues/14898 fixed by https://github.com/systemd/systemd/pull/14913 - could you try your reproducer with v245?

**Comment by fayeinseu** [comment]
Yes,thank you for your advice, it is fixed after this patch https://github.com/systemd/systemd/pull/14913/commits/8d2e97f1e84dfa38139c2a09ac8256f67c9ac5c8
