### ISSUE TITLE
systemd.volatile without initrd

### ISSUE THREAD

**Issue by robimarko** [systemd/systemd#16107]
**Is your feature request related to a problem? Please describe.**
Hi, I have an ARM embedded board that is using systemd.
We are now trying to implement a RO SquashFS rootfs with a UBIFS RW overlay
using OverlayFS.
Since its run on NAND, we are using UBI for this.
It has 3 volumes, kernel, rootfs for the squashfs and rootfs_data that should hold the RW UBIFS overlay.
It seems that systemd does not have support for that, but I see that it supports
using tmpfs overlay in systemd.volatile, but that works only in initrd which we don't
have.

**Describe the solution you'd like**
It would be great to extend the systemd.volatile to work outside of initrd and to support
other FS like UBIFS etc.

**Describe alternatives you've considered**
Adding a system service that will start as soon as possible, but this is too late actually.
So, I doubt that there is a userspace solution for this issue

Any pointers on the best approach to extending systemd.volatile or a different solution
are welcome.

Regards
Robert

**Comment by poettering** [comment]
THis is reason to add an initrd, no?

**Comment by robimarko** [comment]
Well, in embedded it's really not that easy.
Adding initrd would require additional storage space, add further complication to the build and boot processes, and also would increase the maintenance on the software stack.

So, its gotta be an initrd-less solution.

Thanks for the suggestion anyway

**Comment by poettering** [comment]
It kinda sucks rearranging the root dir like that afte rthe fact. initrds exist precisely in order to prepare the rootfs. Trying to work around that just creates complexity for little win. At least traditionally initrd based boots were a lot faster than those without anyway, since the kernel wouldn't insert a synthetic "wait for all devices" delay into the boot process in that case.

**Comment by robimarko** [comment]
> Same boat here. You can do an initrd below 100KB (quite simple if all kernel modules are static) and you already have a partition for the kernel. If it does nothing but mounting a handful filesystems you likely won't need to touch it often.
> 
> If you think that's bad for maintainance and a complicated boot process, then please try doing that after you have processes running on your lower filesystem. Or updating the rootfs when running.

If it could only be 100k then that's a viable option, unfortunately I have no idea how I would generate such a small initrd.

I currently have a plan to do it before systemd starts, so if that fails I might have to go the initrd way.

I have had the pleasure to invent a way of updating a running UBIFS rootfs on a embedded device so I know what pain it is.

**Comment by jktjkt** [comment]
Just to share my two cents, on our embedded devices we have a custom shell script as an init which launches systemd. Our requirements were:

- a read-only rootfs,
- a persistent partition for some data (`/cfg`)
- writable `/etc` backed by an overlay filesystem (transient writes)
- using RAUC for system updates.

```sh
#!/bin/sh

echo "Preparing /etc overlay"
/bin/mount -t tmpfs tmpfs /.ov -o mode=0700
/bin/mkdir /.ov/etc-u
/bin/mkdir /.ov/etc-w
/bin/mount overlay -t overlay /etc -olowerdir=/etc,upperdir=/.ov/etc-u,workdir=/.ov/etc-w

/bin/mount -t proc proc /proc -o rw,nosuid,nodev,noexec,relatime
if grep -q rauc.slot=A /proc/cmdline; then
  RAUC_SLOT_NO=0
  RAUC_SLOT_NAME=A
elif grep -q rauc.slot=B /proc/cmdline; then
  RAUC_SLOT_NO=1
  RAUC_SLOT_NAME=B
else
  echo "Cannot determine active RAUC rootfs slot"
  #exit 1
fi
/bin/umount /proc
echo "RAUC: active slot ${RAUC_SLOT_NAME}"

# sed magic:
# 1) use `sed -n` so that we only print what's explicitly printed
# 2) anchor the search between the "[slot.cfg.$RAUC_SLOT_NO]" and any other section
# 3) look for a line beginning with "device="
# 4) take stuff which is behind the "="
# 5) print it
DEVICE=$(sed -n "/\[slot\.cfg\.${RAUC_SLOT_NO}\]/,/\[.*\]/{/^device=/s/\(.*\)=\(.*\)/\\2/p}" /etc/rauc/system.conf)

if [ x$DEVICE = x ]; then
  echo "Cannot determine device for /cfg from RAUC"
  #exit 1
fi

if [ ! -b $DEVICE ]; then
  echo "Device ${DEVICE} is not a block device"
  #exit 1
fi

echo "Mounting /cfg"
/bin/mount ${DEVICE} /cfg -t auto -o relatime,nosuid,nodev

if [ -d /cfg/etc ]; then
  echo "Restoring /etc from /cfg"
  /bin/cp -a /cfg/etc/* /etc/
fi

if [ -f /cfg/random-seed/random-seed ]; then
  cat /cfg/random-seed/random-seed | /sbin/czechlight-random-seed
fi

exec /sbin/init
```

As you can see, our board has no hwrng, and this was before kernel decided to not block at boot anymore. In fact, the [rng seeding is where we got this advice to run something prior to systemd](https://github.com/systemd/systemd/pull/10621#issuecomment-470476931).

**Comment by robimarko** [comment]
Thanks, I also started on that route of having a shell script that is called as init instead of systemd.
Then it would call other packages to do all of the heavy lifting in creating an RW overlay etc, and then it simply exec /sbin/init so systemd would start as normal.

It just turns out that mounting and pivoting stuff is not as easy as I hoped

**Comment by nolange** [comment]
> Thanks, I also started on that route of having a shell script that is called as init instead of systemd.
> Then it would call other packages to do all of the heavy lifting in creating an RW overlay etc, and then it simply exec /sbin/init so systemd would start as normal.

Just take this one step further and put that script and the tools it needs in an initrd.
I'd start with [alpine mkinitfs](https://github.com/alpinelinux/mkinitfs/blob/master/initramfs-init.in) and drop everything that you don't need.
Look at a busybox, built statically with musl for the shell + tools you need.

**Comment by robimarko** [comment]
In the end, I was able to write a C program with no external dependencies that does the job.
Thankfully sys calls and POSIX covers all that I need so binary size is really small.
Its called as init then it will mount procfs, sysfs, tmpfs, find the UBI volume, mount it and then use OverlayFS to have an RW root.

The program will then simply execv the /sbin/init and systemd will run fine.

This way there is no shell script of anything external in form of libraries needed.

This will also make updating a bit easier to do with volume updates instead of ubiformat.

Thanks for your suggestions.
