### ISSUE TITLE
SyncIntervalSec not working

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#16100]
**systemd version the issue has been seen with**
> 237 and other

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > the SyncIntervalSec paramether if config file must be delay in writing logs in /var/log/syslog or journalctl.

**Unexpected behaviour you saw**
 > writing logs simultaneously in /var/log/syslog or journactl -f

**Steps to reproduce the problem**

Hello
According to the freedesktop website, the "SyncIntervalSec" paramether in config file must put delay in writing logs in /var/log/syslog or journalctl. So I am setting 1m or 5m for this parameter and then runing flowing command :

```
# systemctl restart systemd-journald.service
# systemctl daemon-reload
# echo my_test_msg | systemd-cat
```

and in the new window : 

```
journalctl -f
```

So it's expected to see "my_test_msg" with delay in to the log (/var/log/syslog or journalctl command) but it logs simultaneously

Im confused. Please help

```
journalctl --version
system 237
```

**Comment by vcaputo** [comment]
The definition of syncing in this context is consistent with the rest of *nix, see resources like the fsync(2) and sync(2) man pages for some background.

Writes to the journal are buffered in memory transparently by the kernel, but made available to readers immediately.

The sync interval controls how often those kernel buffers are synchronized to the backing store, not how long to delay propagating the writes to any readers.  It's more related to making data durable in the face of system crashes/abrupt power loss.

**Comment by poettering** [comment]
Yupp @vcaputo is right. We pretty much expose only the Linux sync() call with some magic around it. It's how that call works.

Closing hence.
