### ISSUE TITLE
systemd-networkd coredump twice with different backtraces

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#16116]
**systemd version the issue has been seen with**
> ...
systemd-239

systemd-networkd has been core dumping twice after reboot. I have two coredump files in two different machines with the same version of systemd after reboot. Maybe this problem has been fixed before, but I am not familiar with the code of systemd-networkd and it's hard to reproduce the coredump.  I hope you may give me some suggestions to solve this problem. Thanks!

One of the backtrace is below:

(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000ffff8ece54ec in __GI_abort () at abort.c:79
#2  0x0000ffff8ed1f838 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0xffff8ede55b8 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x0000ffff8ed26124 in malloc_printerr (str=str@entry=0xffff8ede1028 "free(): invalid pointer") at malloc.c:5389
#4  0x0000ffff8ed27a40 in _int_free (av=0xffff8ee31a40 <main_arena>, p=0xaaaad5b88ee8, have_lock=0) at malloc.c:4172
#5  0x0000aaaab56b6e40 in routing_policy_rule_free (rule=0xaaaad5bcf8b0) at ../src/network/networkd-routing-policy-rule.c:52
#6  0x0000aaaab56aa840 in manager_rtnl_process_rule (rtnl=<optimized out>, message=<optimized out>, userdata=0xaaaad5b84c20) at ../src/network/networkd-manager.c:862
#7  0x0000ffff8efdfd10 in process_match (m=0xaaaad5be4470, rtnl=0xaaaad5b84ea0) at ../src/libsystemd/sd-netlink/sd-netlink.c:367
#8  process_running (ret=0x0, rtnl=0xaaaad5b84ea0) at ../src/libsystemd/sd-netlink/sd-netlink.c:397
#9  sd_netlink_process (rtnl=0xaaaad5b84ea0, ret=ret@entry=0x0) at ../src/libsystemd/sd-netlink/sd-netlink.c:430
#10 0x0000ffff8efdffc8 in io_callback (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>) at ../src/libsystemd/sd-netlink/sd-netlink.c:722
#11 0x0000ffff8efed8dc in source_dispatch (s=s@entry=0xaaaad5b850e0) at ../src/libsystemd/sd-event/sd-event.c:3183
#12 0x0000ffff8efef60c in sd_event_dispatch (e=e@entry=0xaaaad5b82bd0) at ../src/libsystemd/sd-event/sd-event.c:3596
#13 0x0000ffff8efef890 in sd_event_run (e=e@entry=0xaaaad5b82bd0, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3653
#14 0x0000ffff8efefaec in sd_event_loop (e=0xaaaad5b82bd0) at ../src/libsystemd/sd-event/sd-event.c:3675
#15 0x0000aaaab56a7dd4 in main (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:140

Another  backtrace is below:

(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000ffffb5d974ec in __GI_abort () at abort.c:79
#2  0x0000ffffb5dd1838 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0xffffb5e975b8 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x0000ffffb5dd8124 in malloc_printerr (str=str@entry=0xffffb5e93028 "free(): invalid pointer") at malloc.c:5389
#4  0x0000ffffb5dd9a40 in _int_free (av=0xffffb5ee3a40 <main_arena>, p=0xaaaadda44078, have_lock=0) at malloc.c:4172
#5  0x0000aaaab23dce40 in routing_policy_rule_free (rule=0xaaaadda2ac10) at ../src/network/networkd-routing-policy-rule.c:52
#6  0x0000aaaab23d2084 in manager_free (m=0xaaaadda22a00) at ../src/network/networkd-manager.c:1468
#7  0x0000aaaab23cd834 in manager_freep (p=0xfffff2488328) at ../src/network/networkd-manager.h:104
#8  main (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:14

Here is the routing_policy_rule_free()
![image](https://user-images.githubusercontent.com/56221695/84152617-7f417000-aa97-11ea-8421-0a43c201236c.png)

Here is the “rule” shown with gdb.
![image](https://user-images.githubusercontent.com/56221695/84152741-9da76b80-aa97-11ea-9fe0-986212f7b810.png)

coredump is generated during reboot
![image](https://user-images.githubusercontent.com/56221695/84157812-bdda2900-aa9d-11ea-934b-925da5fa1f80.png)

**Comment by poettering** [comment]
Sorry, but we only track issues with the two most recently released systemd versions here. That's 244 and 245 right now, and 239 is waay to old. 

networkd received many fixes like this in the recent past, hence I am pretty sure this is already fixed. Hence I will close this now. If you manage to reproduce the issue on something more recent, please reopen/report back. 

Sorry.

(The submission form should have made this very clear actually, to keep frustration at a minimum.)
