### ISSUE TITLE
autosuspend udev rules should not be udev rules, but hwdb lookups

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#16119]
We should never match huge amounts  of vids/pids in udev rules. The database imported from chromiumos (see PR #13515) should be converted to a hwdb file, not a rules file.

/cc @keszybz @superm1 @jwrdegoede

**Comment by poettering** [comment]
I guess fixing this is not too hard, I started playing around with this:

https://paste.centos.org/view/ae7a14ba

I don't have any relevant hw though. Anyone wants to pick this up?

**Comment by poettering** [comment]
I pushed my work I already pasted above into this branch:

https://github.com/poettering/systemd/commits/auto-suspend-hwdb

in case I can interest anyone in cleaning this up?

**Comment by mrhpearson** [comment]
Hi - I can definitely give this a go. Thanks for looking into this
Mark

**Comment by poettering** [comment]
hmm, yeah, my experiment might generate misformed files, it was a quick excercise only. The correct format is documented in hwdb(7) man page.

Also @keszybz already added some comments about where my script is broked in the branch I linked.

**Comment by keszybz** [comment]
Oh, I missed the latest comments here. I started working on this yesterday. I'll push what I have to a branch.

> Also @keszybz already added some comments about where my script is broked in the branch I linked.

I didn't want to imply it was borked. Only that would be prettier in a more modern style.

@mrhpearson I think we'll need to apply your patch as in F32, and this rewrite will only apply to systemd-246+ and F33+.
