### ISSUE TITLE
OOMScoreAdjust for systemd-service-units inside containers

### ISSUE THREAD

**Issue by maxmeyer** [systemd/systemd#1611]
Running services like `dbus` or `postgresql` via systemd _within_ containers fails with error status `206/OOM_ADJUST`. Service-units of both applications contain the setting `OOMScoreAdjust` within their `service.unit`\- at least on CentOS and Arch Linux. After deleting that configuration option, the services can be started without any problem. But changing `service.units` requires manual interaction. With the hype/rise of container solutions a more "automatic" solution would be great - at least for those using systemd inside a container.

```
docker
 |
 - container
    |
    - systemd
       |
       - postgres
       |
       - dbus
```

Suggestion (either or):
1. If `virtualization=container` ignore setting `OOMScoreAdjust`
2. If `virtualization=container` ignore setting `OOMScoreAdjust` and output warning
3. Add option to ignore settings if ConditionVirtualization=container|kvm|... maybe something like `ConditionIgnoreOption="ConditionVirtualization=kvm,OOMScoreAdjust,..."`

Thanks a lot.

**Comment by poettering** [comment]
THis has long been fixed in systemd. Please upgrade the systemd version in your container.

**Comment by maxmeyer** [comment]
Mmmhh... In which version? I'm using CentOS 7.1 with systemd 208 (default) I think.

**Comment by maxmeyer** [comment]
Maybe this affect RHEL as well? I'm not sure if customers are allowed to upgrade systemd without losing support.

**Comment by maxmeyer** [comment]
Sorry I just checked your bug tracker on github. I forgot that you switched to github "recently".

**Comment by poettering** [comment]
@maxmeyer a lot newer than 208. But dunno if RHEL backported the stuff. Please ask RHEL support for help.

note that we track only issues with the most recent systemd versions upstream. For everything in stabilized, distro versions please ask the vendors for help.

**Comment by ghost** [comment]
Ok. Thanks a lot. Just ask to give support some more information like a commit or at least a version.

**Comment by ghost** [comment]
But anyway, I think for now I can live with running `sed` over problematic service files. 

And if someone stumbles across this issue, here's my `Dockerfile` for building a centos image https://github.com/fedux-org/centos/tree/master/files/latest and here https://hub.docker.com/r/feduxorg/centos/~/dockerfile/
