### ISSUE TITLE
how can I use the host env variable in *.service 

### ISSUE THREAD

**Issue by alicera** [systemd/systemd#16126]
I want to create a new *.service and set the "WorkingDirectory" to $PWD
but *.service cant accept the method, it has to set actually location
how can I do to set the $PWD
 
and the content is 

> `

[Unit]
Description= Application Service

[Service]
Type=simple
RemainAfterExit=yes
WorkingDirectory=$PWD

ExecStart=run code
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target`

``

**Comment by poettering** [comment]
This is not a support forum, as the submission form really should have made clear. Please post only bug reports an feature requests here. Thank you.

Contact the systemd mailing list for support questions
