### ISSUE TITLE
What if I don't use systemd to manage pam session?

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#16125]
I encountered a problem days ago. Each time I used sudo, there would be about 25s delay. I can't reproduce the problem now, but I managed to find this might be reletad to pam_systemd.so. 
In /etc/pam.d/system-auth, I found this line:
`-session     optional      pam_systemd.so`
Even if this line is deleted, everything seems to work fine.
I am not sure if there are any bad effect if I don't use systemd to manage pam session. And by including pam certification, what benefits can we get.
Thanks!

**Comment by poettering** [comment]
This is not a support forum, as the submission form really should have made clear. Please post only bug reports an feature requests here. Thank you.

Contact the systemd mailing list for support questions
