### ISSUE TITLE
bootctl: can't install/update with encrypted /boot

### ISSUE THREAD

**Issue by jrobsonchase** [systemd/systemd#16151]
**systemd version the issue has been seen with**
`systemd 245 (245.6-4-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid`

**Used distribution**
Arch

**Expected behaviour you didn't see**
 `bootctl install` and `bootctl update` should install/update the bootloader respectively.

**Unexpected behaviour you saw**
Without arguments:
```
# bootctl update
Failed to probe partition scheme of "/dev/block/254:3": Input/output error
```

With boot/esp path arguments:
```
# bootctl --boot-path=/boot --esp-path=/efi update
Failed to probe partition scheme of "/dev/block/254:3": Input/output error
```

With boot path == esp path:
```
# bootctl --boot-path=/efi --esp-path=/efi update
File system "/dev/block/259:1" has wrong type for extended boot loader partition.
```

Printing the boot/esp paths:
```
# bootctl -x
Failed to probe partition scheme of "/dev/block/254:3": Input/output error
# bootctl -p
/efi
Failed to probe partition scheme of "/dev/block/254:3": Input/output error
```

**Steps to reproduce the problem**
My partition layout looks like this:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         1050623   512.0 MiB   EF00  EFI system partition
   2         1050624         2099199   512.0 MiB   8309  Linux LUKS
   3         2099200      1046480895   498.0 GiB   8309  Linux LUKS
```

Partition 1 is mounted at `/efi`, partition 2 is an encrypted ext4 partition mounted at `/boot`, and partition 3 is an encrypted lvm PV that holds my `/` and `/home` partitions.

My `esp` contains:

```
.
├── EFI
│   ├── arch
│   │   ├── linux-fallback-signed.efi
│   │   └── linux-signed.efi # unified kernel/cmdline/initramfs
│   ├── boot
│   │   └── bootx64.efi # manually installed systemd-boot
│   └── systemd
│       └── systemd-bootx64.efi # manually installed systemd-boot
└── loader
    ├── entries
    │   └── arch.conf
    └── loader.conf
```

I boot a unified kernel/cmdline/initramfs EFI image via the systemd `linxux64.efi.stub` bundled by [sbupdate](https://github.com/andreyv/sbupdate). As far as I know, neither the boot process nor the systemd-boot installation process should need to touch `/boot` - everything lives in my `esp`

**Comment by poettering** [comment]
So what kind of device is /dev/block/254:3?

I guess we need some more defensive handling if /boot is not a regular partition, and then ignore the directory entirely.

**Comment by jrobsonchase** [comment]
It's the `cryptsetup luksOpen`ed `/dev/mapper` device.

Oddly, it's now working for me. It's possible that I might have been in some weird state between an update and a reboot at the original time of writing.

**Comment by poettering** [comment]
OK, let's close it then?

**Comment by jrobsonchase** [comment]
Fine with me ¯\\\_(ツ)\_/¯

**Comment by o0-o** [comment]
I am experiencing this issue while attempting to install Arch. Same as @jrobsonchase I have a luks/ext4 `/boot`. `bootctl install` fails if `/boot` is mounted. If I unmount it, the command succeeds, as does a subsequent `bootctl update`. Interestingly, `/` is also on luks/ext4, so the issue appears to depend on `/boot` being a mountpoint, not limited to luks.

Please let me know if you prefer I create a new issue as opposed to reviving this one.

```
[root@archiso /]# lsblk -o NAME,TYPE,MOUNTPOINT
NAME                             TYPE  MOUNTPOINT
loop0                            loop
sr0                              rom
vda                              disk
├─vda1                           part  /efi
├─vda2                           part
│ └─md127                        raid1
│   └─boot_luks                  crypt /boot
└─vda3                           part
  └─md126                        raid1
    └─root_luks                  crypt
      ├─root_vg-root_lv          lvm   /
      ├─root_vg-var_lv           lvm   /var
      ├─root_vg-var_log_lv       lvm   /var/log
      ├─root_vg-var_log_audit_lv lvm   /var/log/audit
      └─root_vg-swap_lv          lvm   [SWAP]
vdb                              disk
├─vdb1                           part
├─vdb2                           part
│ └─md127                        raid1
│   └─boot_luks                  crypt /boot
└─vdb3                           part
  └─md126                        raid1
    └─root_luks                  crypt
      ├─root_vg-root_lv          lvm   /
      ├─root_vg-var_lv           lvm   /var
      ├─root_vg-var_log_lv       lvm   /var/log
      ├─root_vg-var_log_audit_lv lvm   /var/log/audit
      └─root_vg-swap_lv          lvm   [SWAP]
vdc                              disk
└─home_luks                      crypt
  └─home_vg-home_lv              lvm   /home
[root@archiso /]# bootctl install
Failed to probe partition scheme of "/dev/block/251:0": Input/output error
[root@archiso /]# umount /boot
[root@archiso /]# bootctl install
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/BOOT/BOOTX64.EFI".
Random seed file /efi/loader/random-seed successfully written (512 bytes).
Not installing system token, since we are running in a virtualized environment.
Created EFI boot entry "Linux Boot Manager".
[root@archiso /]# bootctl update
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/BOOT/BOOTX64.EFI".
[root@archiso /]# mount /dev/mapper/boot_luks /boot
[root@archiso /]# bootctl update
Failed to probe partition scheme of "/dev/block/251:0": Input/output error
```

**Comment by tz4678** [comment]
I have same problem, but boot partition is not luks-encrypted:

```bash
~ 
➜ sudo blkid /dev/nvme0n1p1
/dev/nvme0n1p1: UUID="<UUID>" TYPE="crypto_LUKS" PARTUUID="<UUID>"

~ 
➜ sudo blkid /dev/nvme0n1p2
/dev/nvme0n1p2: UUID="<UUID>" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="<UUID>"

~ 
➜ sudo blkid /dev/nvme0n1p3
/dev/nvme0n1p3: UUID="<UUID>" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="ESP" PARTUUID="<UUID>"
```

**Comment by dev-uhuru** [comment]
Hello,

I have the same error message thrown by systemd-logind on a clean Fedora install which appeared after I encrypted /boot (LUKS/ext4) with grub2 as bootloader:

Failed to probe partition scheme of "/dev/block/253:1": Input/output error

Hope this helps
