### ISSUE TITLE
reboot --force does not actually reboot immediately

### ISSUE THREAD

**Issue by audunmg** [systemd/systemd#16167]
**systemd version the issue has been seen with**
> 245.5-3

**Used distribution**
 > Debian sid

**Expected behaviour you didn't see**
 > Actual reboot

**Unexpected behaviour you saw**
 > System freezing

**Steps to reproduce the problem**
run `reboot --force`

**Comment by poettering** [comment]
"reboot --force" just means we call the kernel's reboot() syscall, nothing else. If that freezes it's a bug in the kernel or firmware. There's nothing systemd can do about that. Please report to your kernel maintainers.

Sorry!

**Comment by boucman** [comment]
wouldn't that be reboot -f -f ?
man page is not very clear...

**Comment by audunmg** [comment]
I should elaborate.

reboot -f does not reboot, nor does it freeze the system.
It is still responsive as if nothing happened except the terminal doing the reboot -f is frozen.
So no reboot() system call is called, something else happens.

For future reference, `echo b > /proc/sysrq-trigger` works as a workaround and instantly reboots the system.
