### ISSUE TITLE
Non-nl80211 WiFi adapter is not being brought up by systemd-networkd

### ISSUE THREAD

**Issue by szpajder** [systemd/systemd#16160]
**systemd version the issue has been seen with**
245

**Used distribution**
Arch Linux ARM

**Expected behaviour you didn't see**
wlan interface is brought up on system startup, just like it worked prior to upgrade from v243 to v245

**Unexpected behaviour you saw**
The interface is not brought up. `networkctl status wlan0` shows the following:

```
 3: wlan0
             Link File: /usr/lib/systemd/network/99-default.link
          Network File: n/a
                  Type: wlan
                 State: carrier (failed)
                  Path: platform-3f980000.usb-usb-0:1.3:1.0
                Driver: r8188eu
                Vendor: Realtek Semiconductor Corp.
                 Model: RTL8188EUS 802.11n Wireless Network Adapter
            HW Address: f8:1a:67:0a:4a:16 (TP-LINK TECHNOLOGIES CO.,LTD.)
                   MTU: 1500 (min: 68, max: 1500)
  Queue Length (Tx/Rx): 4/4
               Address: fe80::fa1a:67ff:fe0a:4a16
```

Due to the `failed` state, systemd-networkd does not start DHCP nor assign static IP address (whichever I configure). Also note that `Network File` shows `n/a`, however `/etc/systemd/network/wlan0.network` exists and is correct.

**Steps to reproduce the problem**

The contents of `/etc/systemd/network/wlan0.network` is pretty straightforward:

```
[Match]
Name=wlan0

[Network]
DHCP=yes
```

`wpa_supplicant@wlan0` service is enabled and running. Due to the fact that r8188eu driver does not support nl80211, I run it with `-Dnl80211,wext` option. It works fine - association with the AP succeeds.

Some logs:

```
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: Successfully initialized wpa_supplicant
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: nl80211: Driver does not support authentication/association or connect commands
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: rfkill: Cannot get wiphy information
(...)
Jun 12 12:44:54 rasp04 systemd-networkd[285]: wlan0: Flags change: +UP
Jun 12 12:44:54 rasp04 systemd-networkd[285]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=16 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jun 12 12:44:54 rasp04 systemd-networkd[285]: wlan0: Link UP
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: ioctl[SIOCSIWAP]: Operation not permitted
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
Jun 12 12:44:54 rasp04 wpa_supplicant[332]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
Jun 12 12:44:56 rasp04 wpa_supplicant[332]: wlan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='***' freq=2452 MHz)
Jun 12 12:44:56 rasp04 wpa_supplicant[332]: Failed to add supported operating classes IE
Jun 12 12:44:56 rasp04 wpa_supplicant[332]: wlan0: Association request to the driver failed
Jun 12 12:44:56 rasp04 wpa_supplicant[332]: wlan0: Associated with xx:xx:xx:xx:xx:xx
Jun 12 12:44:56 rasp04 systemd-networkd[285]: wlan0: Flags change: +LOWER_UP
Jun 12 12:44:56 rasp04 systemd-networkd[285]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=17 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jun 12 12:44:56 rasp04 systemd-networkd[285]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jun 12 12:44:57 rasp04 wpa_supplicant[332]: wlan0: WPA: Key negotiation completed with xx:xx:xx:xx:xx:xx [PTK=CCMP GTK=CCMP]
Jun 12 12:44:57 rasp04 wpa_supplicant[332]: wlan0: CTRL-EVENT-CONNECTED - Connection to xx:xx:xx:xx:xx:xx completed [id=0 id_str=]
Jun 12 12:44:57 rasp04 systemd-networkd[285]: wlan0: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: boot, type: unicast
Jun 12 12:44:57 rasp04 systemd-networkd[285]: wlan0: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
Jun 12 12:44:57 rasp04 systemd-networkd[285]: wlan0: Flags change: +RUNNING
Jun 12 12:44:57 rasp04 systemd-networkd[285]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jun 12 12:44:57 rasp04 systemd-networkd[285]: wlan0: Gained carrier
Jun 12 12:44:57 rasp04 systemd-networkd[285]: Failed to request information about wifi interface 3: No such device
Jun 12 12:44:57 rasp04 systemd-networkd[285]: Could not process link message, ignoring: No such device
```

In the end, the link layer is up and running:

```
root@rasp04:~ # iwconfig wlan0
wlan0     IEEE 802.11bgn  ESSID:"***"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.452 GHz  Access Point: xx:xx:xx:xx:xx:xx
          Bit Rate:72.2 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****   Security mode:open
          Power Management:off
          Link Quality=99/100  Signal level=65/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

but no IP addresses get assigned to the interface:

```
root@rasp04:~ # ip a s dev wlan0
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f8:1a:67:0a:4a:16 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fa1a:67ff:fe0a:4a16/64 scope link
       valid_lft forever preferred_lft forever
```

and `networkctl status wlan0` shows `State: carrier (failed)` as above.

However if I run `networkctl reload` at this point, the interface comes up successfully:

```
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: found matching network '/etc/systemd/network/wlan0.network'
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: Re-configuring with /etc/systemd/network/wlan0.network
Jun 12 12:45:49 rasp04 systemd-networkd[285]: Setting '/proc/sys/net/ipv6/conf/wlan0/disable_ipv6' to '0'
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: IPv6 successfully enabled
Jun 12 12:45:49 rasp04 systemd-networkd[285]: Setting '/proc/sys/net/ipv6/conf/wlan0/proxy_ndp' to '0'
Jun 12 12:45:49 rasp04 systemd-networkd[285]: Setting '/proc/sys/net/ipv6/conf/wlan0/use_tempaddr' to '0'
Jun 12 12:45:49 rasp04 systemd-networkd[285]: Setting '/proc/sys/net/ipv6/conf/wlan0/accept_ra' to '0'
Jun 12 12:45:49 rasp04 systemd-networkd[285]: LLDP: Started LLDP client
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: Started LLDP.
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: Setting address genmode for link
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: Setting address genmode done.
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: Acquiring DHCPv4 lease
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): STARTED on ifindex 3
Jun 12 12:45:49 rasp04 systemd-networkd[285]: wlan0: State changed: initialized -> configuring
Jun 12 12:45:49 rasp04 systemd-networkd[285]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_33 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=25 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): DISCOVER
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): OFFER
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): REQUEST (requesting)
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): ACK
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): lease expires in 23h 59min 58s
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): T2 expires in 20h 59min 58s
Jun 12 12:45:49 rasp04 systemd-networkd[285]: DHCP CLIENT (0x531c638d): T1 expires in 11h 59min 58s

root@rasp04:~ # networkctl status wlan0
* 3: wlan0
             Link File: /usr/lib/systemd/network/99-default.link
          Network File: /etc/systemd/network/wlan0.network
                  Type: wlan
                 State: routable (configuring)
                  Path: platform-3f980000.usb-usb-0:1.3:1.0
                Driver: r8188eu
                Vendor: Realtek Semiconductor Corp.
                 Model: RTL8188EUS 802.11n Wireless Network Adapter
            HW Address: f8:1a:67:0a:4a:16 (TP-LINK TECHNOLOGIES CO.,LTD.)
                   MTU: 1500 (min: 68, max: 1500)
  Queue Length (Tx/Rx): 4/4
               Address: 192.168.1.94
               Gateway: 192.168.1.4 (Intel Corporation)
```

I see that the `Failed to request information about wifi interface` error message comes from a recently introduced code in `shared/wifi-util.c`. This code seems to rely heavily on nl80211 interface, so I guess it can't work with drivers that only support wext?

AFAIK wext is considered obsolete and probably won't be implemented here in systemd-networkd, however is there any workaround for such adapters?

Nevertheless, inability to read some non-essential wifi-related info from the driver (like SSID, etc) should not be considered fatal, I think. After a reload systemd-networkd is able to work fine without this information after all. Too bad it requires manual intervention, and a local access to the box on every reboot.

**Comment by mbiebl** [comment]
> AFAIK wext is considered obsolete and probably won't be implemented here in systemd-networkd, however is there any workaround for such adapters?

I wonder if you could run  `wpa_cli -a` to automatically trigger the `networkctl reload` when `CONNECTED`

**Comment by szpajder** [comment]
@mbiebl thanks for suggestion. I didn't know about `-a` option.

It kinda works,but the reliability is so-so. Starting wpa_cli right away after wpa_supplicant (using `Wants=` and `Before=` in wpa_supplicant's drop-in) usually fails, because wpa_supplicant's socket is not there yet at this time. I added a sleep for a second before starting wpa_cli - now it's better. It seems to work directly after a reboot, but things like `systemctl restart wpa_supplicant@wlan0` or `systemctl restart systemd-networkd` cause loss of connectivity in most cases. In the first case the interface state usually gets stuck in `degraded (failed)` state (which is quite unexpected, because wpa_supplicant reports `CONNECTED` event and wpa_cli reloads systemd-networkd, but due to degraded state it does not even attempt to configure the interface any further. I don't yet fully understand what's going on here). And in the second case (ie. after restarting systemd-networkd) the reload obviously won't happen because for wpa_supplicant nothing has changed, so no event gets emitted.

But it's better than nothing, so thanks anyway.

**Comment by poettering** [comment]
Hmm, I am pretty sure we should explicitly not support WEXT, since it's obsolete. However, we probably should support the iface to the level where it is like any other iface

**Comment by yuwata** [comment]
@szpajder If possible, could you test PR #16200? I do not have any WiFi adapter which does not support nl80211. So, the PR is not tested.

**Comment by szpajder** [comment]
Apologize for delayed response.

Just tested in under Arch Linux ARM. Works great, no workarounds needed. @yuwata thanks a lot for the fix :)

**Comment by yuwata** [comment]
Thank you for testing!

**Comment by Juweii** [comment]
Is it possible to backport the fix also to the raspbian buster (systemd/stable,now 241-7~deb10u5+rpi1 armhf)?
The current version has the same problem, all USB wifi devices are not getting handled by systemd (failed):

3 is the build-in, 6 & 7 are the USB devices.
```
  3 wlan0           wlan               degraded    unmanaged
  [...]
  6 wlan1           wlan               carrier     failed
  7 wlan2           wlan               carrier     failed
```
My workaround is to dhclient the failed wlan interfaces manually right after the boot process, but this is considered as a bug and should be fixed. :)

This worked before the upgrade to 241-7~deb10u5, so it seems the unfixed changes got backported to this version...


Or is there a way to upgrade on raspbian buster to the most current version without using the official repo?

**Comment by Juweii** [comment]
Nevermind, it just works again after i have upgraded the latest rpi-eeprom and rpi.gpio-common packages just by now.
Don't know why, since its changelogs doesn't show anything related, but after reboot the usb wifi sticks are handled by systemd again.
