### ISSUE TITLE
persistent ramdisk

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#16171]
**Is your feature request related to a problem? Please describe.**

Ramdisks / tmpfs are great because these are super fast. Ideal for cache. However, a server reboot leads to loosing the cache.

File storage is great because persistent after reboot.

I would like to combine the best of both worlds.

**Describe the solution you'd like**

Persistent ramdisk.

**Describe alternatives you've considered**

There are a lot attempts on persistent ramdisks but none of the projects I found seems to be either still maintained / stable enough for use in production / available from distribution package sources.

* https://github.com/patrikx3/ramdisk
* https://wiki.debian.org/SSDOptimization#Persistent_RAMDISK
* https://thelinuxexperiment.com/persistent-ramdisk-on-debain-ubuntu/
* https://github.com/graysky2/anything-sync-daemon
* https://github.com/wor/goanysync
* https://web.archive.org/web/20191005110948/https://blog.jmdawson.co.uk/persistent-ramdisk-on-debain-ubuntu/
* https://gitlab.com/jamesdawson1995/persist
* https://github.com/graysky2/profile-sync-daemon
* https://wiki.archlinux.org/index.php/Profile-sync-daemon

There are a lot corner cases such as incomplete snapshot / failed restoration. The one where I am confident that a persistent ramdisk could be implemented is systemd.

**Comment by poettering** [comment]
What's this precisely supposed to be? tmpfs means data is lost when you turn off the system. What is a "persistent" ramdisk supposed to be? I don't get it?

I mean, do you want to continously mirror the tmpfs on some persistent disk? that sounds racy? or do you want to do that only on shutdown? but that means you lose all data if you shut down the machine at the wrong time?

I also see no reason why a tmpfs should be much faster than an fs where every file is in the cache and you turn off any form of sync'ing.

I fail to see the point I must say?

**Comment by adrelanos** [comment]
> What's this precisely supposed to be?

> tmpfs means data is lost when you turn off the system.

> What is a "persistent" ramdisk supposed to be?

Fast as a ramdisk but can be restored after reboot.

> I mean, do you want to continously mirror the tmpfs on some persistent disk?

> that sounds racy?

Yes, certainly not trivial to get right. Perhaps possible will correct lockfile mechanisms during synchronization and restore. Hence, asking you. :)

> or do you want to do that only on shutdown?

The synchronization timer should probably be configurable. Either only on shutdown or every x minutes.

> but that means you lose all data if you shut down the machine at the wrong time?

Yes, a setting only sync on shutdown and powerloss would leave to a full data loss. That would be non-ideal - cache would then have to be restructured from scratch. But if that happens only every few years, we'd still enjoy mostly persistent ramdisk most of the time.

> I also see no reason why a tmpfs should be much faster than an fs where every file is in the cache and you turn off any form of sync'ing.

Folder location of /var/ramdisk would be different from /var/ramdisk-backup. /var/ramdisk would always be fast and restored on reboot. /var/ramdisk-backup

Why would every file be in cache? Example:

    vmtouch /var/www/

>  Resident Pages: [...] 31.0%

It takes a while until all files are cached by kernel (speak: slower for first visitors after reboot). File needs to be requested "a few times" before the kernel considers it "hot" and caches it if I am not mistaken. However, I don't think kernel caching mechanism is a full replacement for ramdisks?

Also advantage of ramdisk is that ramdisk contents can change rapidly (writing is super fast and doesn't wear SSD). Kinda huge writeback buffer. Sync to disk could be every 10-60 minutes and therefore save disk io cycles.

> I fail to see the point I must say?

Only for my request or all alternative projects that I listed above? Perhaps these projects explain the point better than I did. They're all besides the point if I am missing something?

**Comment by poettering** [comment]
> It takes a while until all files are cached by kernel (speak: slower for first visitors after reboot). File needs to be requested "a few times" before the kernel considers it "hot" and caches it if I am not mistaken. However, I don't think kernel caching mechanism is a full replacement for ramdisks?

No, once a file is in RAM it is in RAM. The buffer cache takes up every byte of memory not used elsewhere and stuff is removed from the buffer cache only if there's pressure because something else needs RAM.

If you constantly sync stuff to disk in the bg, you just increase the writeback delay, that's what it comes down to. You can probably tweak a regular file system for that too if you like. i.e. mount options such as commit=,barrier=0 for ext4 come to mind, turn off the journalling and so on.

Either way I doubt this is something we should have in systemd. If what you are asking for cannot be done already with ext4 or a similar fs in equally performant way at the compromise of loss of data integrity guarantees the same as what you propose, then it should be implemented in ext4...

**Comment by adrelanos** [comment]
Thank you for your feedback!

**Comment by poettering** [comment]
Anyway, let's close this here. I don't think systemd is the right fit for this, and I think you can do that with ext4 better already, by using the right params.
