### ISSUE TITLE
how change coredump directory in system-coredump

### ISSUE THREAD

**Issue by smaysam** [systemd/systemd#16177]
Is it possible to change the default path (/var/lib/systemd/coredump/) for creating coredump file ?

I change path in  /proc/sys/kernel/core_pattern but coredump not created !

**Comment by mrc0mmand** [comment]
You can use bind mounts to achieve it, but there's no support for it in systemd.

Please see https://github.com/systemd/systemd/pull/16078 for more information.

**Comment by smaysam** [comment]
tnx a lot
