### ISSUE TITLE
Fails to start services on NixOS with binutils-2.34

### ISSUE THREAD

**Issue by luc65r** [systemd/systemd#16174]
**systemd version the issue has been seen with**
> 245.5 and 245.6

**Used distribution**
 > NixOS

**Expected behaviour you didn't see**
 > systemd-journald.service and systemd-udevd.service start successfully.

**Unexpected behaviour you saw**
 > Jobs for systemd-journald.service and systemd-udevd.service fail with code 127.
`Unexpected job result, assuming server side newer than us: failed`

**Steps to reproduce the problem**
- Build a system against the staging branch of NixOS with [this PR](https://github.com/NixOS/nixpkgs/pull/89793).
- Switch to the system.

The PR mostly bumped `gcc` from 9 to 10 and `binutils` from 2.31.1 to 2.34. The problem seems to be related to `binutils`, as it has the same behavior compiled with gcc9 and with gcc10.

**Comment by mrc0mmand** [comment]
Do you have a journal from the machine? Since one of our CIs is running on Arch with gcc 10.1 and binutils 2.34 (and is running without mentioned issues) I suspect the issue is not in systemd.

**Comment by luc65r** [comment]
> Do you have a journal from the machine?

What are you talking about? `dmesg`?

The thing is that I can launch `systemd-journald` and `systemd-udevd` manually, but I can't launch the `.service` with `systemctl`.
The `.service` files seem right, as they are identical to a machine with binutils-2.31.1, except from the paths (because of Nix) which all point to the right place too.

**Comment by mrc0mmand** [comment]
> > Do you have a journal from the machine?
> 
> What are you talking about? `dmesg`?
> 

I somehow managed to ignore the fact that you can't run `systemd-journald` in the first place, so I journal won't help much there.

> The thing is that I can launch `systemd-journald` and `systemd-udevd` manually, but I can't launch the `.service` with `systemctl`.
> The `.service` files seem right, as they are identical to a machine with binutils-2.31.1, except from the paths (because of Nix) which all point to the right place too.

In that case could you try running the `systemctl` command with debug log level? Like:

```
# SYSTEMD_LOG_LEVEL=debug systemctl start systemd-journald.service
```

Also, strace-ing `systemctl` and PID 1 with `-s 500` during the start operation might be useful as well.

**Comment by luc65r** [comment]
[`SYSTEMD_LOG_LEVEL=debug systemctl start systemd-journald.service`](https://termbin.com/tg90)
[`strace -s 500 -p 1 systemctl start systemd-journald.service`](https://termbin.com/1guz)

Executing `/nix/store/.../systemd-journald` or `systemd-run /nix/store/.../systemd-journald` work just fine.

**Comment by luc65r** [comment]
[Here](https://termbin.com/z1hom) is what is in the journal after executing `systemctl start systemd-udevd.service`

**Comment by mrc0mmand** [comment]
Thank you. According to the logs this looks like an issue with `libgcrypt:

```
Jun 14 15:47:14 nixos systemd-udevd[1357]: /nix/store/q3mgcgvas6fzsfq4209amh8kr84nl1k1-systemd-245.6/lib/systemd/systemd-udevd: error while loading shared libraries: libgcrypt.so.20: cannot enable executable stack as shared object requires: Operation not permitted
Jun 14 15:47:14 nixos systemd[1]: systemd-udevd.service: Main process exited, code=exited, status=127/n/a
```

**Comment by luc65r** [comment]
Thanks a lot, I will try `execstack` on it, hopefully it will work!

**Comment by luc65r** [comment]
It worked! Thank you!

**Comment by mrc0mmand** [comment]
@luc65r just to make the reason clear - the executable stack is incompatible with `MemoryDenyWriteExecute=yes` used by `systemd-journald.service`, `systemd-udevd.service`, etc. (https://github.com/systemd/systemd/issues/3814 is a similar issue). It's also weird that you encountered the issue in the first place, since the [last NixOS libgcrypt build I could find](https://hydra.nixos.org/build/121351494#tabs-summary) seems to be compiled with `--noexecstack`.
