### ISSUE TITLE
systemd-udevd[423]: vethUVP58D: Failed to get link config: No such device

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#16175]
**systemd version the issue has been seen with**

v245.6

**Used distribution**

Raspbian

After upgrading from v241 to 245 I see the following veth related error in the journal:
```
Jun 14 00:49:45 raspberrypi systemd-udevd[423]: vethUVP58D: Failed to get link config: No such device
```

For a bit of context, `journalctl -b | grep veth` yields
```
Jun 14 00:49:45 raspberrypi kernel: br0: port 2(vethSWE1WI) entered blocking state
Jun 14 00:49:45 raspberrypi kernel: br0: port 2(vethSWE1WI) entered disabled state
Jun 14 00:49:45 raspberrypi kernel: device vethSWE1WI entered promiscuous mode
Jun 14 00:49:45 raspberrypi kernel: IPv6: ADDRCONF(NETDEV_UP): vethSWE1WI: link is not ready
Jun 14 00:49:45 raspberrypi systemd-networkd[133]: vethSWE1WI: Link UP
Jun 14 00:49:45 raspberrypi kernel: eth0: renamed from vethUVP58D
Jun 14 00:49:45 raspberrypi kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethSWE1WI: link becomes ready
Jun 14 00:49:45 raspberrypi kernel: br0: port 2(vethSWE1WI) entered blocking state
Jun 14 00:49:45 raspberrypi kernel: br0: port 2(vethSWE1WI) entered forwarding state
Jun 14 00:49:45 raspberrypi systemd-networkd[133]: vethSWE1WI: Gained carrier
Jun 14 00:49:45 raspberrypi systemd-udevd[423]: vethUVP58D: Failed to get link config: No such device
Jun 14 00:49:46 raspberrypi systemd-networkd[133]: vethSWE1WI: Gained IPv6LL
```

Since this is a new error, is this something to worry about?

**Comment by h3d0** [comment]
Confirmed on

Linux:

```
uname -a
Linux n552vw 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
started 1-2 daya ago after update to v245:

```
systemd --version
systemd 245 (245.4-4ubuntu3.1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```
journal:

```
journalctl -b -p 0..3
Jun 16 08:39:13 n552vw systemd-udevd[17919]: veth0305b6c: Failed to get link config: No such device
Jun 16 08:44:18 n552vw systemd-udevd[22031]: veth46b0a67: Failed to get link config: No such device
Jun 16 08:48:21 n552vw systemd-udevd[25109]: veth6edc8d5: Failed to get link config: No such device
Jun 16 08:49:22 n552vw systemd-udevd[25741]: veth4de86a9: Failed to get link config: No such device
Jun 16 08:50:23 n552vw systemd-udevd[26537]: vethfba2c7c: Failed to get link config: No such device
Jun 16 08:54:27 n552vw systemd-udevd[29673]: veth6fd5d47: Failed to get link config: No such device
Jun 16 08:55:28 n552vw systemd-udevd[30282]: veth49f0d20: Failed to get link config: No such device
Jun 16 09:00:32 n552vw systemd-udevd[34200]: vethf1f9303: Failed to get link config: No such device
Jun 16 09:02:34 n552vw systemd-udevd[35798]: vethe24bd1a: Failed to get link config: No such device
Jun 16 09:05:37 n552vw systemd-udevd[38399]: veth2b2bef6: Failed to get link config: No such device
Jun 16 09:14:45 n552vw systemd-udevd[45383]: veth2fea856: Failed to get link config: No such device
Jun 16 09:15:46 n552vw systemd-udevd[46122]: veth13a9e91: Failed to get link config: No such device
```

**Comment by poettering** [comment]
hmm, so this is a veth tunnel that gets created under the name "eht0" and then renamed to "vethUVP58D" and that races against udevd?

Any chance you can strace that, to see what precisely fails with ENODEV?

Alternatively bisect it to see where this begins?

Is this reproducible on git master?

link_config_get() only has three calls that could fail that way, and I don't see why any of those three should really care about the device already being renamed.

**Comment by mbiebl** [comment]
Unfortunately, git bisect is not an option for me. Compiling systemd on my old pi takes almost 24h.

**Comment by mbiebl** [comment]
> hmm, so this is a veth tunnel that gets created under the name "eht0" and then renamed to "vethUVP58D" and that races against udevd?

Isn't this udev itself renaming the device?

**Comment by poettering** [comment]
the code you are seeing the log message from is the one that later renames the device. So no, it's something else, i.e. probably the tool that registers that veth? (not sure why it doesn#t create it under the right names right-away, though)

**Comment by mbiebl** [comment]
I wonder if #15691 is somehow related (I'm not using iwd though).

**Comment by mbiebl** [comment]
@h3d0 Are you using lxc/lxd as well?
The `veth` devices is created by lxc whenever I start an lxc container.
I've setup a bridge devices via networkd 
```
# cat /etc/systemd/network/br0.network 
[Match]
Name=br0

[Network]
Address=192.168.XXX.XXX/24
```
and my lxc container contains
```
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = br0
```

**Comment by poettering** [comment]
strace?

**Comment by HontoNoRoger** [comment]
I see the same issues on our servers.
Using Ubuntu server 20.04 which automatically comes with LXD 4.0.
I'm not using LXD containers so I suspect some automated routine on every boot.

**Comment by poettering** [comment]
@mbiebl hmm, this is with lxc? please mention things like that in the original bug report!

my guess: lxc creates a veth pair under random names, then moves one into the container, and renames it "eth0" there? @mbiebl @stgraber?

if so, it migh tjust be that things are run async here. i.e. the device under the random name shows up, udev picks it up does its thing, but in the middle of it the iface is already moved over, and it gets ENODEV.

we might want to just downgrade the message to debug here, and say "device vanished while we were processing it or so.

**Comment by brauner** [comment]
On Fri, Feb 12, 2021 at 09:49:34AM -0800, Lennart Poettering wrote:
> @mbiebl hmm, this is with lxc? please mention things like that in the original bug report!
> 
> my guess: lxc creates a veth pair under random names, then moves one into the container, and renames it "eth0" there? @mbiebl @stgraber? @brauner?

Moving the devices into a container is one scenario where udev has
correct permissions on the device while not being allowed access to
others (on purpose).
But I've also encountered the problem because I'm investigating a new
feature for udev.

> 
> if so, it migh tjust be that things are run async here. i.e. the device under the random name shows up, udev picks it up does its thing, but in the middle of it the iface is already moved over, and it gets ENODEV.

The EROFS early exit is a great compromise because it allows us to
simply tell udev to not even bother with devices but it would be great
for testing and development if only sys being ro would cause a bailout,
not permission errors.

**Comment by brauner** [comment]
Sorry, need to read that again. I was replying to a different mail in my mind. Sorry for that. :)

**Comment by brauner** [comment]
> @mbiebl hmm, this is with lxc? please mention things like that in the original bug report!
> 
> my guess: lxc creates a veth pair under random names, then moves one into the container, and renames it "eth0" there? @mbiebl @stgraber? @brauner?
> 
> if so, it migh tjust be that things are run async here. i.e. the device under the random name shows up, udev picks it up does its thing, but in the middle of it the iface is already moved over, and it gets ENODEV.
> 
> we might want to just downgrade the message to debug here, and say "device vanished while we were processing it or so.

I think that makes sense. Yes, we do create the device in the host namespace and then move it to the container and rename it to the user intended name. I once made it so that no rename was necessary but that introduced another netlink can of worms.

**Comment by brauner** [comment]
If you can wait for a few days until later next week I can bisect.

**Comment by poettering** [comment]
prepped a fix in #18569 that downgrades the warnings to debug on ENODEV

**Comment by teresaejunior** [comment]
I'm having a similar issue with Cloudflare's WARP: `CloudflareWARP: Failed to get link config: No such device`. From what I could gather from this conversation, this is not really systemd's fault (https://github.com/systemd/systemd/pull/18569 deals with logging), and so I cannot fix by trying to upgrade systemd on my Ubuntu LTS. Can someone please confirm?

**Comment by Deepak275** [comment]
@poettering  can you please tell me what will be the fix of it ?  my systems version . do I have to upgrade/downgrade  it ?

> systemd 245 (245.4-4ubuntu3.13)
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
