### ISSUE TITLE
systemd-tmpfiles will resolve specifiers (machine-id, etc) from host, not from target --root

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#16183]
This is a follow-up to #14806, systemd-tmpfiles learned to use {passwd,group} databases from the root systemd, but will still use the host /etc/machine-id, /etc/os-release and so on.

Ideally it will pick such configuration files only from the target rootfs, while not handling entries containing non-resolvable specifiers (boot, user id, etc..).
Any entry with questionable specifiers should be rather leftout than containing information from the running host.

the architecture could probably be added per environment or switch.

**Comment by poettering** [comment]
(No need to file an issue if you intend to file a PR. Just post the PR right away, that's enough for us)

**Comment by nolange** [comment]
> (No need to file an issue if you intend to file a PR. Just post the PR right away, that's enough for us)

Did not know I'd do a PR shortly, kids stayed at a friends yesterday ;)
