### ISSUE TITLE
systemctl cannot start nginx when access_log path is set to use /tmp/nginx/

### ISSUE THREAD

**Issue by billchen8888** [systemd/systemd#16184]
**systemd version the issue has been seen with**
> 219

**Used distribution**
 > Centos 8; amazonlinux 2

**Expected behaviour you didn't see**
 > systemctl start nginx

**Unexpected behaviour you saw**
 > systemctl doesn't start nginx  when the nginx access_log is set to /tmp/nginx/access.log

**Steps to reproduce the problem**
1) yum install nginx
2) edit the /etc/nginx/nginx.conf, change the line
access_log /var/log/nginx/access.log main;
to:
access_log  /tmp/nginx/access.log main;
3) mkdir /tmp/nginx; chown nginx:root /tmp/nginx;
4) systemctl start nginx
5)  Now we will see the error in the syslog.    But we can directly run  /usr/sbin/nginx; then the nginx is running fine  and the log file /tmp/nginx/access.log is created. This makes me believe the systemctl does some other checkup, but I don't know what it is.  Please note:  if the configuration line is set to:   access_log  /tmp/access.log main;   systemctl start nginx  works.

**Comment by mrc0mmand** [comment]
The nginx service[0] in RHEL 8 uses `PrivateTmp=true` [directive](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=) so it doesn't see the `/tmp/nginx` directory you just created. You could either add a service dropin with `ExecStartPre=` which will do the log directory setup or drop `PrivateTmp=true` to make this work.


[0]
```
# /usr/lib/systemd/system/nginx.service
[Unit]
Description=The nginx HTTP and reverse proxy server
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
# Nginx will fail to start if /run/nginx.pid already exists but has the wrong
# SELinux context. This might happen when running `nginx -t` from the cmdline.
# https://bugzilla.redhat.com/show_bug.cgi?id=1268621
ExecStartPre=/usr/bin/rm -f /run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
KillSignal=SIGQUIT
TimeoutStopSec=5
KillMode=mixed
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

**Comment by billchen8888** [comment]
@mrc0mmand 

Thanks for the explanation!
