### ISSUE TITLE
test-date fails, if system time is after 2070-01-01

### ISSUE THREAD

**Issue by MofX** [systemd/systemd#16181]
The test `test_should_fail("-100y");` of test-date fails, if the system time is after 2070-01-01.
This is of course expected, because 2070-01-01 - 100 years is still a valid date.

I guess this should just be removed entirely.

This was found on an embedded system, that has no RTC and the bios/firmware reports 2070-01-01 on bootup every time.

**Comment by boucman** [comment]
that's a weird hardware.... and sounds like a bug (01/01/1970) 

but good catch
