### ISSUE TITLE
Breaking change in sd_bus_message_new() in v245.6

### ISSUE THREAD

**Issue by sangelovic** [systemd/systemd#16193]
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > `sd_bus_message_new()` should be able to create and return a D-Bus message of type `_SD_BUS_MESSAGE_TYPE_INVALID`. This expected behavior is exhibited by all other sd-bus versions until 245.6. But 245.6 changed this behavior in a backwards-incompatible way.

**Unexpected behaviour you saw**
 > `sd_bus_message_new()` invoked with `_SD_BUS_MESSAGE_TYPE_INVALID` fails, returns invalid value error. This breaks `sdbus-c++` library, since one of its core concepts is based on plain sd-bus messages used only for storing/reading serialized data.

**Steps to reproduce the problem**
> Just call `sd_bus_message_new()` with `_SD_BUS_MESSAGE_TYPE_INVALID` type.

Suspicious commit that brought this change: a2dd99

**Comment by sangelovic** [comment]
The bug was filed based on Lennart's proposal here: https://lists.freedesktop.org/archives/systemd-devel/2020-June/044723.html

**Comment by poettering** [comment]
Offending commit is:

https://github.com/systemd/systemd/commit/a2dd991d0fde59dc0574bd4d0c1438f01dc0b8ff

**Comment by keszybz** [comment]
@sangelovic I would love to see the sdbus-c++ testsuite executed as part of our CI (e.g. with the latest stable release of sdbus-c++). But when I run the testsuite locally, it fails (some activation errors and such, i.e. it seems to be about lack of fallback on lack of permissions). Maybe someone from your side who knows your test suite could open a PR against systemd to do that?

**Comment by sangelovic** [comment]
@keszybz sdbus-c++ unit tests shall run OK, but integration tests need to have the `org.sdbuscpp.integrationtests.conf` file (versioned just next to test sources, in `tests/integrationtests/files/` directory) copied into `/etc/dbus-1/system.d/` before running them... and that should be all. Would you still like to give it a second chance and add the CI job yourself, or shall I look into that (I guess it would take much longer to me since I'm not familiar with systemd CI, and honestly I don't have much spare time for that...)?

**Comment by sangelovic** [comment]
The latest stable sdbus-c++ version is [v0.8.2](https://github.com/Kistler-Group/sdbus-cpp/releases/tag/v0.8.2)
