### ISSUE TITLE
fsck.xfs doesn't exist, not checking file system.

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#16201]
I am using Manjaro testing with systemd 245.6-4-manjaro and kernel 5.7.2 / 5.4.46.
I have the following filesystems:
```
Filesystem                                Type            Size  Used Avail Use% Mounted on
/dev/nvme0n1p1                            vfat            511M  4.1M  507M   1% /boot/efi
/dev/nvme0n1p2                            xfs              59G   44G   15G  75% /
...
```
all the rest is on zfs.

I changed my initcpio hook to use systemd instead of udev:

`HOOKS=(base systemd autodetect modconf block keyboard keymap filesystems)`

and I created new initramfs with `mkinitcpio -P
`
Now I see the following error message in the journal:

`systemd-fsck[375]: nvme0n1p2: fsck.xfs doesn't exist, not checking file system.`

While the efi partition is checked just fine:

```
systemd-fsck[1505]: fsck.fat 4.1 (2017-01-24)
systemd-fsck[1505]: /dev/nvme0n1p1: 11 files, 1025/130812 clusters
```

This does not make sense in two ways:

1) `fsck.xfs` does exist. It is in the same directory as fsck.fat. Although I can not find any fsck.* in the initramfs.
2) the `fsck.xfs` script is doing nothing anyways because xfs automatically checks the fs during mount. `xfs_repair` is needed if an fs is broken.

From my point of view systemd should stop trying to exceute  `fsck.xfs` because it is useless and/or it should use `xfs_repair` instead.

**Comment by marcosfrm** [comment]
Arch's mkinitcpio has the `fsck` hook. I think you need it.

**Comment by mabod** [comment]
no. I dont think so.
(1) I had the fsck hook enabled before. The fsck hook actually executes an fsck.xfs for / on every boot. Which makes no sense for xfs because fsck.xfs is basically exiting without doing anything. 
(2) I do not believe that the systemd hook has a dependency on the fsck hook. In fact I believe the systemd hook makes the fsck hook obsolete.

**Comment by marcosfrm** [comment]
Well, some hook needs to copy the `fsck.*` binaries to the initramfs, no?

`systemd-fsck` will just fork/exec the `fsck.xxx` tool for the fs being checked.

Recent `fsck.xfs` now calls `xfs_repair` when `-f` is passed. The `fsck` hook probably needs updating to add  `xfs_repair` to the initramfs.

**Comment by mabod** [comment]
I understand your point, but if the systemd hook depends on the fsck scripts, then it should take care about it by itself. It should be independent.

**Comment by marcosfrm** [comment]
Hence report the issue to mkinitcpio devs.

**Comment by poettering** [comment]
Nah, we just invoke `fsck.<fstype>`, and it's the job of the file system devs to provide some sensible executable under that name. It's how this works on Linux. If this doesn't work correctly for XFS, then XFS needs to fix that.

That said, it appears to me your initrd tool is simply not packing the xfs fsck tool into the initrd. If that's what you want, then bring this up with your initrd maintainers.

Either way, there's nothing to fix in systemd here, we do not have fs-specific code for this in systemd and don't intend to change that. It's up to the xfs devs to implement the `fsck.<fstype>` API if they wants things to be compatible with util-linux and how this is done.

**Comment by asmallpileofash** [comment]
Hey, sorry if posting on isn't allowed, but  you just need to install the xfsprogs package on arch linux to solve the issue
:)
