### ISSUE TITLE
systemd-run --shell: Failed to set up standard input

### ISSUE THREAD

**Issue by lotan** [systemd/systemd#16204]
**systemd version the issue has been seen with**
245.6

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
```$ systemd-run --shell --machine=test```
Shell should open up in Container test. 
Until recently that worked every time.

**Unexpected behaviour you saw**
```
$ systemd-run --shell --machine=test
Running as unit: run-u119.service
Press ^] three times within 1s to disconnect TTY.
Finished with result: success
```
But it reverts back into the host shell.

The log in the container shows:
```
Jun 17 19:39:24 test systemd[1]: Starting /bin/bash...
Jun 17 19:39:24 test systemd[17724]: run-u114.service: Failed to set up standard input: No such file or directory
Jun 17 19:39:24 test systemd[17724]: run-u114.service: Failed at step STDIN spawning /bin/bash: No such file or directory
Jun 17 19:39:24 test systemd[1]: run-u114.service: Main process exited, code=exited, status=208/STDIN
Jun 17 19:39:24 test systemd[1]: run-u114.service: Failed with result 'exit-code'.
Jun 17 19:39:24 test systemd[1]: Failed to start /bin/bash.
Jun 17 19:39:26 test systemd[1]: Starting /bin/bash...
Jun 17 19:39:26 test systemd[1]: Started /bin/bash.
```
**Steps to reproduce the problem**
```$ systemd-run --shell --machine=test```

Sometimes the shell does open up in the container.

**Comment by lotan** [comment]
I managed to narrow down, when the problem started by manually bisecting the versions in Arch Linux:
The problematic change must have been introduced between v245.6-1 and v245.6-2.
According to the package description that meant a change from tag a520e63382396661d79f630b2babe717a85b1209 and a47534aa62edfddb2df86e2d0c208979f24dc8c2 plus one additional backport: 2b6df46d21abe8a8b7481e420588a9a129699cf9 (https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/systemd&id=e51eabda046e72816fdf0774c7de7adbd93fc645)

Unfortunately, I had a look at the changes between those two tags and there are many :(

**Comment by poettering** [comment]
Does your version already include 2b5f708985a0d175f86a57d4e8e2c8eccfb73bd6?

If not, is it fixed if you move to at least that version of systemd-run?

**Comment by lotan** [comment]
No it didn't.

But adding that commit fixed the issue.
Looking forward to the next release including that commit.
Thank you!
