### ISSUE TITLE
journalctl -export format error 

### ISSUE THREAD

**Issue by r10r** [systemd/systemd#16202]
**systemd version the issue has been seen with**
> systemd 245 (245.6-1)

**Used distribution**
 > debian bullseye/sid

**Expected behaviour you didn't see**
 > Exactly one double newline at the end for journal entry https://www.freedesktop.org/wiki/Software/systemd/export/

**Unexpected behaviour you saw**
 > A double newline before the end of a single journal entry.

**Steps to reproduce the problem**

```
ruben@nas:~$ journalctl  --no-pager -o export -n 1 -q
__CURSOR=s=f5edef76263d4773a34aa394faa1badc;i=17623;b=c77cddb06b0340ee9ccfdc3db56bd4e7;m=2a80142358;t=5a8457dd99b34;x=289ac07c2d98ea45
__REALTIME_TIMESTAMP=1592391301176116
__MONOTONIC_TIMESTAMP=182537429848
_BOOT_ID=c77cddb06b0340ee9ccfdc3db56bd4e7
_UID=0
_GID=0
_CAP_EFFECTIVE=3fffffffff
_SELINUX_CONTEXT

unconfined

_MACHINE_ID=1953ab44d65e401dabb882d9329b7095
_HOSTNAME=nas
PRIORITY=6
_TRANSPORT=syslog
SYSLOG_FACILITY=10
SYSLOG_IDENTIFIER=CRON
_COMM=cron
_EXE=/usr/sbin/cron
_CMDLINE=/usr/sbin/CRON -f
_AUDIT_LOGINUID=0
_SYSTEMD_CGROUP=/system.slice/cron.service
_SYSTEMD_UNIT=cron.service
_SYSTEMD_SLICE=system.slice
_SYSTEMD_INVOCATION_ID=579acfdd843a48a9be6dc097f4071bd3
MESSAGE=pam_unix(cron:session): session closed for user root
SYSLOG_PID=350359
SYSLOG_TIMESTAMP=Jun 17 12:55:01 
_PID=350359
_AUDIT_SESSION=527
_SOURCE_REALTIME_TIMESTAMP=1592391301175759

```

**Comment by vuzdemav** [comment]
On the documentation page you linked to, look at the example of a message with a binary field. If the binary field has two newlines in a row then so will the export output.

**Comment by r10r** [comment]
Chris, thanks for the response. I definitely scanned the documentation page to quickly ...
The example message on the documentation page the field '_SELINUX_CONTEXT' does not contain a binary value - this on tricked me. 
Are you aware of any existing ragel machine definition for the export format ?
