### ISSUE TITLE
journalctl: make "--user --unit" works as "--user-unit"

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#1621]
Currently if I run `journalctl --user --unit $SOME_UNIT` I will just get "No entries". Although there is the "--user-unit" option, it seems a bit dumb to me that "--user --unit" doesn't do the same thing. Would it be possible/nice to add a switch or something to "--unit" so that when "--user" is used, it matches "_SYSTEMD_USER_UNIT=" and "_UID=" instead of "_SYSTEMD_UNIT=UNIT"?

**Comment by poettering** [comment]
Yeah, probably makes sense.

**Comment by oconnor663** [comment]
Is there any particular reason `--unit` doesn't match both `_SYSTEMD_UNIT` and `_SYSTEMD_USER_UNIT`? It took me a while to figure out why my logs weren't showing up >.<

**Comment by poettering** [comment]
@oconnor663 well, most sys admins might be quite confused if "journalctl -u httpd" also gives them the output of any user service by the same name, just because a user decided to name a service that way.

**Comment by oconnor663** [comment]
Hmm, I wonder if there's an easy way to prevent other new users from making my mistake. Maybe add an explicit mention in the `--unit` documentation that it ignores user-level services, so that users don't have to keep reading to `--user-unit` to find that out? Anyway, I'll stop hijacking this issue :)

**Comment by markstos** [comment]
Thanks for this fix! I'm using 229 and only today discovered that --user --unit did not mean --user-unit like I thought. I look forward now to v230.

**Comment by LeGEC** [comment]
Hello

Can someone please indicate in what version this feature has been released ?

From what I see on our systems : we are running systemd v232 on debian/stretch systems, and "journalctl --user --unit blah" does not output the same thing as "journalctl --user-unit blah"

**Comment by keszybz** [comment]
@LeGEC this might be something to report in your distro. Upstream the code was merged to systemd-v230.

**Comment by audetto** [comment]
Same thing still happens on v241 on Raspberry Pi OS

```
pi@raspberrypi:~/projects/gym $ journalctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

pi@raspberrypi:~/projects/gym $ journalctl --user --unit booking
No journal files were found.
-- No entries --

pi@raspberrypi:~/projects/gym $ journalctl --user-unit booking
-- Logs begin at Sun 2021-05-02 11:07:00 BST, end at Sun 2021-05-16 09:42:19 BST. --
May 15 11:59:45 raspberrypi systemd[818]: Started Booking System.
May 15 11:59:45 raspberrypi schedule.sh[13264]: 2021-05-15 11:59:45,506 13270 INFO Connect
...
```

**Comment by keszybz** [comment]
@audetto We only track the latest two releases in this bug tracker (i.e. >= 246 right now).

**Comment by andrewchen5678** [comment]
still an issue on 252, encountered an error on a podman user unit while checking `systemctl --user status podname.service` and suggested me to run `journalctl --user -xeu podname.service` to find the log, but running `journalctl --user -xeu podname.service` gives me nothing while `journalctl --user-unit podname.service` does show the log.
