### ISSUE TITLE
Different device name for wifi depending on the driver

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#16214]
A user is installing Ubuntu, during installation they download and install better dkms drivers for their wifi. At this point they loose wifi connectivity and have to reset up the wifi.

From the dmesg log that was automatically collected I can see

```
[ 129.282522] brcmsmac bcma0:1 wlp2s0b1: renamed from wlan0
[ 491.516220] wl 0000:02:00.0 wlp2s0: renamed from wlan0
```

It seems like with one driver `wlan0` gets renamed to `wlp2s0b1`, and when the switch to a different driver happens `wlp2s0` is used instead.

I am not sure what `b1` stands for, or where i came from. Is there potentially an issue with `net_id` builtin? or for example is there something broken with one or the other driver, such that they both generate `...b1` or both generate `...s0` names?

Or is above working as expected, and such is life?

**Comment by arvidjaar** [comment]
> I am not sure what `b1` stands for

According to https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html it is "Broadcom bus (BCMA) core number". So yes, it works as expected. I do not know if devices with more than one bus actually exist, nor how they are named using non-BCMA aware driver like wl.

**Comment by xnox** [comment]
> > I am not sure what `b1` stands for
> 
> According to https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html it is "Broadcom bus (BCMA) core number". So yes, it works as expected. I do not know if devices with more than one bus actually exist, nor how they are named using non-BCMA aware driver like wl.

Thank you! Somehow I went reading code and didn't find that.
