### ISSUE TITLE
ConditionPathIsDirectoryNotEmpty ignored

### ISSUE THREAD

**Issue by jamescassell** [systemd/systemd#16220]
**systemd version the issue has been seen with**
> systemd-245.4-1.fc32.x86_64

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
 > `ConditionPathIsDirectoryNotEmpty` honored

**Unexpected behaviour you saw**
 > `ConditionPathIsDirectoryNotEmpty` completely ignored

**Steps to reproduce the problem**
set `ConditionPathIsDirectoryNotEmpty` to any value. restart the service to see if the condition triggered.  Modify the value to include a `!` to see if the condition triggered.  Observe that service starts regardless of the actual status of the Directory being Empty, or the inverted status of the condition.

**Comment by jamescassell** [comment]
Originally found on RHEL 8, reproduced on Fedora 32.

**Comment by boucman** [comment]
There is no such thing as ConditionPathIsDirectoryNotEmpty... what are you trying to do ? is that a feature request ?

**Comment by mrc0mmand** [comment]
As @boucman said, there's no such thing as `ConditionPathIsDirectoryNotEmpty=`, but there is `ConditionDirectoryNotEmpty=`.

In that case I gave it a try on RHEL 8.2 (systemd-239-33.el8.x86_64) and it seems to be working as expected:

```
#  mkdir -p /var/testdir
# systemd-run --unit test-empty -p ConditionDirectoryNotEmpty=/var/testdir /bin/sleep infinity
# systemctl is-active test-empty
inactive
# systemd-run --unit test-empty -p 'ConditionDirectoryNotEmpty=!/var/testdir' /bin/sleep infinity
Running as unit: test-empty.service
# systemctl is-active test-empty
active
```

**Comment by jamescassell** [comment]
Obviously I was up to late... surprised it didn't error out in me.

**Comment by mrc0mmand** [comment]
@jamescassell in case of a standard unit file you should see a warning in the journal if systemd encounters an invalid directive:

```
# rpm -q systemd
systemd-239-31.el8_2.2.x86_64
# cat > /etc/systemd/system/test.service << EOF
[Unit]
ConditionPathIsDirectoryNotEmpty=/var/testdir
[Service]
ExecStart=/bin/sleep infinity
EOF
# systemctl daemon-reload
# systemctl cat test.service
# /etc/systemd/system/test.service
[Unit]
ConditionPathIsDirectoryNotEmpty=/var/testdir
[Service]
ExecStart=/bin/sleep infinity

# systemctl status -l test.service
● test.service
   Loaded: loaded (/etc/systemd/system/test.service; static; vendor preset: disabled)
   Active: inactive (dead)

Jun 19 09:44:18 XXX.redhat.com systemd[1]: /etc/systemd/system/test.service:2: Unknown lvalue 'ConditionPathIsDirectoryNotEmpty' in section 'Unit'
