### ISSUE TITLE
Add .zst support to machinectl export-tar & import-tar

### ISSUE THREAD

**Issue by Isopod** [systemd/systemd#16222]
Zstandard (.zst) is a relatively new compression method with a compression ratio comparable to Gzip but significantly faster compression and decompression. It is already supported by GNU Tar and BsdTar/Libarchive, among others, and is seeing increasing adoption, for example Arch Linux switched all of its packages from .xz to .zst earlier this year.

At the moment, `machinectl export-tar` and `machine-ctl import-tar` are hard-coded to only understand .gz, .xz and .bz2:

>        export-tar NAME [FILE], export-raw NAME [FILE]
>            Exports a TAR or RAW container or VM image and stores it in the
>            specified file. The first parameter should be a VM or container
>            image name. The second parameter should be a file path the TAR or
>            RAW image is written to. If the path ends in ".gz", the file is
>            compressed with gzip, if it ends in ".xz", with xz, and if it ends
>            in ".bz2", with bzip2. If the path ends in neither, the file is
>            left uncompressed. [...]

I've tried  running `export-tar mymachine mymachine.tar.zst` anyway, but as the man page states, this resulted in an uncompressed file.

It would be nice if you could add Zstandard support to machinectl.

**Comment by tpgxyz** [comment]
Would be nice also to add zstd support to mkosi

**Comment by poettering** [comment]
Duplicate of #9105
