### ISSUE TITLE
homed with NFS and remote user

### ISSUE THREAD

**Issue by sequencer** [systemd/systemd#16230]
**Is your feature request related to a problem? Please describe.**
Systemd-homed formulates a good home directory management tool, however there is a common issue that home directory lays on the NFS(or some remote filesystem) which is required to be mount on demand, and user is managed by LDAP and use NIS to provide a unified user database management.
I hope systemd-homed can also kill these legacy softwares and provide userdb to external servers.

**Describe the solution you'd like**
Export userdbctl with a socket interface, homed and userdb can retrieve user data there,
add NFS backend to homed. 

**Describe alternatives you've considered**
Or if we still keep LDAP and let LDAP create a VarLink to support systemd users?

**Comment by poettering** [comment]
homedis an alternative to manage users via ldap/nis. It's a more decentralized scheme that works without a single central directory. If you have LDAP/NIS set up, use sssd or anything else to manage those home directories. homed is really not for that.

A subset of the functionality that is now available (resource mgmt and so on) can be be populated via LDAP too, if sssd and such would implement this:

https://systemd.io/USER_GROUP_API

That way you can make logind honour the data provided via LDAP for resource mgmt and such.

homed doesn't care where the home directories it manages are located. If /home is on NFS it can even mount homes from there. That should already just work.

**Comment by poettering** [comment]
Anyway, I don#t think there's anything actionable here for us. Closing hence.
