### ISSUE TITLE
Waiting for wpa_supplicant (or re-running dhcp) on wired network

### ISSUE THREAD

**Issue by k0stjap** [systemd/systemd#16234]
My office desktop system - running gentoo in the "systemd" profile - is attached to the (wired) ethernet where dhcp leases provide for different networks, depending on whether 802.1x authentication is completed or not. I need to use the network requiring the 802.1x authentication, and use wpa_supplicant in the "wired" mode. wpa_supplicant per se works fine - but systemd-networkd initiates dhcp and usually obtains the lease before wpa_supplicant completes, stranding me in the wrong network.

I could not find any way to either tell networkd to configure the interface but wait with dhcp until wpa_supplicant completes, or, in a pinch, a way to force automatic reconfiguration of networkd service when wpa_supplicant is done.

Specifically, I could not solve the problem using the Before=/After= constraints as networkd actually does two things: configures the interface (which I need to be done before wpa_supplicant can run in the "wired" mode) and runs dhcp (which I need to be bone after wpa_supplicant).

**Comment by ssahani** [comment]
I think `BlackList=` would work . DHCP offers from servers in the list are rejected
```
[DHCPv4]
BlackList = 
```

**Comment by k0stjap** [comment]
Dear 'ssahani',

.. thanks, that actually seems to work too! I actually overlooked the option (by looking at the older version of the documentation ;-()

'BlackList' option does not seem to support the CIDR notation, compared to dhcpd, IIRC. At very least I tried "BlackList=10.114.64.0/20" and I got barked at ("DHCP black listed ip address is invalid, ignoring assignment"), while "BlackList=10.114.79.254" worked fine. This is rather important as the sysadmins can re-locate the dhcp server, of course, without letting me know..

Besides the CIDR notation, having a "white list" would be more appropriate in my case - as I need to use a specific network.

Cheers,

**Comment by ssahani** [comment]
We can do whitelist.  CIDR is more like a FW job we should not do it.

**Comment by ssahani** [comment]
Can you test this https://github.com/systemd/systemd/issues/16234 ?

**Comment by k0stjap** [comment]
.. FYI, a status update: I built systemd with your commit used as a patch applied to the gentoo's version of systemd-244 (gentoo-244.3), updated the config, and rebooted the system - and the result so far is that I cannot reach it over the internet anymore ;-) I shall have the opportunity to visit the office tomorrow, and I'll post more details.

What's a "FW job" such that "we should not do it"?

Cheers,

**Comment by k0stjap** [comment]
unfortunately, white-listing the server address - the one from the 'SERVER_ADDRESS' entry in the lease file, i.e. adding

[DHCPv4]
BlackList=10.114.79.254
#WhiteList=193.10.64.241

where the lease file from a previous run (without white-listing) contained:

SERVER_ADDRESS=193.10.64.241

made systemd-networkd unable to take a lease.

I feel I should emphasize that I applied your patch to my gentoo's "sys-apps/systemd-244.3", not your [git development] head. Because of that, the patch also had two rejects - but purely syntactic, I believe.
