### ISSUE TITLE
journalctl: use log prio coloring also for "-o cat" output mode

### ISSUE THREAD

**Issue by sergey-safarov** [systemd/systemd#16232]
**Is your feature request related to a problem? Please describe.**
I looking daemons logs via command like
```sh
journalctl --no-hostname -flu ${daemon_name}
```
I use this only to get colored (using message loglevel) daemon output.
And here I process name and message timestamp is not use full.

**Describe the solution you'd like**
Could you add also options
`--no-exec-name`
`--no-timestamp`

**Describe alternatives you've considered**
None

**Comment by sergey-safarov** [comment]
I want output format like `--output=cat`. But the `cat` format does not display colored output.

**Comment by poettering** [comment]
Adding color output to --output=cat makes more sense to me...

**Comment by vtronko** [comment]
What if pipe reader (or anything that reads the output from `journalctl --output=cat ...`) doesn't expect the ANSI codes? Separate option looks more sound.

**Comment by sergey-safarov** [comment]
How about automatic output device capabilities determination?

As example
On CentOS when you grep file search and output to the terminal, then you have `red` highlighted matched string.
When you make the same grep search to file, then you will get strings without any coloring.

**Comment by vtronko** [comment]
@sergey-safarov unless you want to forward colored output to file and store it as is.

**Comment by sergey-safarov** [comment]
Think about this not widely used case.
When I want to save the colored output, then I use:
1) output logs to the terminal;
2) copy colored output as HTML, modern Linux terminal support this feature;
3) paster colored text to Libreoffice;
4) save the text as HTML;
5) send colored logfile to devs.

**Comment by sergey-safarov** [comment]
> unless you want to forward colored output to file and store it as is.

How about `--output=html` for this case and save the output to file?

**Comment by poettering** [comment]
> What if pipe reader (or anything that reads the output from `journalctl --output=cat ...`) doesn't expect the ANSI codes? Separate option looks more sound.

All our color logic is automatically turned off if output is to a non-TTY, unless you force it on via the SYSTEMD_COLOR env var (which you can also use to force it off). This means, when you redirect to pipe of file colors is automatically off,  but when you invoke a tool interactively it's on. It's generally how this works on Linux, not just in systemd but many other tools too.

**Comment by dustymabe** [comment]
> All our color logic is automatically turned off if output is to a non-TTY, unless you force it on via the SYSTEMD_COLOR env var

slight correction for anyone reading this.. It's `SYSTEMD_COLORS` with an `S`.
