### ISSUE TITLE
systemd-repart: Fails to partition qemu-nbd device

### ISSUE THREAD

**Issue by hunger** [systemd/systemd#16242]
**systemd version: built from master branch**
**Used distribution: Arch Linux**

**Expected behaviour you didn't see**

Systemd-repart can partition a NBD device.

**Unexpected behaviour you saw**

Systemd-repart fails to partition a NBD device with the following error message:
`Failed to discard entire block device: Input/output error.`

**Steps to reproduce the problem**

Install `qemu` so that `qemu-img` and `qemu-nbd` are both available on your system.

```
qemu-img create -f qcow2 /tmp/image.img 5G
qemu-nbd --connect=/dev/nbd0 /tmp/image.img
systemd-repart --definitions=/some/dir/with/definition --empty=force --dry-run=yes /dev/nbd0
```

The format passed to `qemu-img` does not seem to matter: `raw` will also fail, but `losetup` can then be used in conjunction with `systemd-repart` to partition the image file:

```
qemu-img create -f raw /tmp/image.img 5G
losetup -f -P /tmp/image.img
losetup -l | grep /tmp/image.img
systemd-repart --definitions=/some/dir/with/definition --empty=force --dry-run=yes /dev/loopX
```

Unfortunately `losetup` does not work with qcow2 files:-/

`gdisk` can be used to create a GPT partition table on the `/dev/nbd0` device just fine, but systemd-repart will continue to fail even with a valid GPT on the device.

**Comment by hunger** [comment]
`systemd-repart` sucessfully repartititons the qemu-nbd device if I remove the `return` from the line reporting the "Failed to discard entire block device:" error.

I am not sure this is the right thing to do, but then if the discard is not working, that is not a reason to fail the partitioning, is it?

**Comment by poettering** [comment]
hmm, seems the nbd device returns EIO instead of EOPNOTSUPP/ENOTTY/ENOSYS when we issue the discard ioctl on it. We currently check for the latter and ignore it assuming the device can't do discard. But EIO we treat as serious error. We should probably whitelist EIO the same way then.

(might make sense to fix nbd instead though, to generate EOPNOTSUPP instead, like all other block devices that lack spport for it)

**Comment by WGH-** [comment]
I don't have `systemd-repart` installed, but discard itself seems to work fine for me:

```
$ qemu-img create -f qcow2 /tmp/image.img 2M
$ sudo qemu-nbd --connect=/dev/nbd0 /tmp/image.img
$ sudo strace blkdiscard /dev/nbd0
(skip)
openat(AT_FDCWD, "/dev/nbd0", O_WRONLY) = 3
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(0x2b, 0), ...}) = 0
ioctl(3, BLKGETSIZE64, [2097152])       = 0
ioctl(3, BLKSSZGET, [512])              = 0
ioctl(3, BLKDISCARD, [0, 2097152])      = 0
close(3)                                = 0
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by poettering** [comment]
@WGH- if I try this with bkdiscard I also get EIO:

```
openat(AT_FDCWD, "/dev/nbd0", O_WRONLY) = 3
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(0x2b, 0), ...}) = 0
ioctl(3, BLKGETSIZE64, [5368709120])    = 0
ioctl(3, BLKSSZGET, [512])              = 0
ioctl(3, BLKDISCARD, [0, 5368709120])   = -1 EIO (Input/output error)
openat(AT_FDCWD, "/usr/share/locale/C.UTF-8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C.utf8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "blkdiscard: ", 12blkdiscard: )            = 12
write(2, "/dev/nbd0: BLKDISCARD ioctl fail"..., 34/dev/nbd0: BLKDISCARD ioctl failed) = 34
openat(AT_FDCWD, "/usr/share/locale/C.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/C/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ": Input/output error\n", 21: Input/output error
)  = 21
dup(1)                                  = 4
close(4)                                = 0
dup(2)                                  = 4
close(4)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by poettering** [comment]
And in kernel logs I see:

```
Jun 23 17:16:11 iota kernel: block nbd0: Other side returned error (5)
Jun 23 17:16:11 iota kernel: blk_update_request: I/O error, dev nbd0, sector 0 op 0x3:(DISCARD) flags 0x4000 phys_seg 1 prio class 0
```

**Comment by poettering** [comment]
Ah, interesting, it appears to work when using "2M" as image size. Doesn't work when using "5G". @WGH- can you verify?

Smell like a bug in qemu-nbd...

**Comment by poettering** [comment]
I am not sure we should do anything about this. This really looks like a bug in qemu-nbd to me. The nbd device even announces it can deal with 2T discards:

```
cat /sys/block/nbd0/queue/discard_max_bytes
2199023255040
```

Except that it apparently can't actually deal with that...

@hunger please report a bug against qemu-nbd instead. As a local work-around consider using `systemd-repart --discard=no`, which will skip the discarding step.

**Comment by WGH-** [comment]
Huh, I guess I was wrong when I tried to use the smaller image. With large image, it doesn't work for me, either.

**Comment by poettering** [comment]
urks, qemu tracks bugs in launchpad... Not sure I want an account on that...

**Comment by hunger** [comment]
Yeap, I can confirm that this is probably a bug in qemu-nbd.

Now I need to decide whether I want to live with --discard=no or bother to report something in launchpad:-)

**Comment by hunger** [comment]
I reported this issue to qemu:

https://bugs.launchpad.net/qemu/+bug/1884831

**Comment by ebblake** [comment]
This is not a bug in qemu-nbd, but in the kernel nbd.ko.  It appears that the kernel module is reporting a 32-bit value of -1 as the max_discard_size, which is then being scaled up by the sector size of 512 when reported through sysfs.  But the NBD protocol itself is limited to 32-bits (there are plans to add an optional 64-bit extension to the protocol, but that has not landed yet), so the REAL maximum discard size cannot exceed ROUND_DOWN(INT32_MAX, sector_size).

**Comment by ebblake** [comment]
Never mind, it IS a bug in qemu rather than the kernel; nbd-client did not have the same problem (the kernel is fragmenting the requests below 4G after all, but qemu-nbd is choking on requests larger than 2G).

**Comment by poettering** [comment]
@ebblake thank you for reporting back! much appreciated!
