### ISSUE TITLE
systemd-cryptsetup is so slow when opening an encrypted container

### ISSUE THREAD

**Issue by morfikov** [systemd/systemd#1624]
I just wanted to check whether systemd is able to unlock my laptop using just one password, and actually it is. But I've noticed something that could be wrong.

I have several LUKS devices, and I was using the scripts `cryptdisks_start` and `cryptdisks_stop` (from the `cryptsetup` package)  in order to have just one password to open all the containers before. This solution was working well for some time.

I removed all my services that had something to do with mounting, and I configured everything via `/etc/crypttab` and `/etc/fstab` files.

The boot process seems to be really slow, for instance (with `systemd-cryptsetup`):

```
      8.778s systemd-cryptsetup@grafi.service
      8.545s systemd-cryptsetup@kabi.service
```

versus:

```
      4.641s systemd-cryptsetup@grafi.service
      4.540s systemd-cryptsetup@kabi.service
```

The files now don't differ much. Actually the only difference is in `ExecStart` and `ExecStop`. In the case of the scripts it is:

```
ExecStart=/usr/sbin/cryptdisks_start %i
ExecStop=/usr/sbin/cryptdisks_stop %i
```

And the files from the generator have: 

```
ExecStart=/lib/systemd/systemd-cryptsetup attach 'grafi' '/dev/disk/by-uuid/d314ed20-ffaf-4a18-98a7-91538e79d981' 'none' 'luks'
ExecStop=/lib/systemd/systemd-cryptsetup detach 'grafi'
```

I have no idea why the `systemd-cryptsetup` is so slow, but when I use it, most of the other services also get some delay. It's about 1-2 secs.

I don't know whether it's a normal thing because I've never used it before.

**Comment by arvidjaar** [comment]
Do you observe the same difference in startup time if you start them manually after boot?

**Comment by poettering** [comment]
do you have multiple LUKS devices with different passphrases?

**Comment by morfikov** [comment]
@poettering 
I have multiple LUKS devices with usually 2 key slots active. One is just a normal password, and it's the same in the case of all of the devices. The other key slot was created from the `dmsetup table --showkeys` -- the long hash. By using `keyscript=/lib/cryptsetup/scripts/decrypt_derived` in the `/etc/crypttab` file, I was able to use the long hash as a password in order to open the derived containers, and it also is the same in this case -- I was planning to use only the long hash and delete the normal password in the future, but for now it's a backup password. When I unlock my system, I use the backup password, and not the hash.

Maybe it's because of the two key slots? Because the time is twice longer compared to the script.

@arvidjaar 
I didn't try to mount them in that way when I had switched to the systemd tool. I will check that if the above thought is wrong.

**Comment by morfikov** [comment]
It looks like that both mechanisms (debian script and systemd) do the same thing, more or less. I mean, they take the password and go through the keyslots. If the first doesn't match, then the second keyslot is used, and so on. I just tested it with two containers. One of them stores the password in the first keyslot, the other in the third keyslot. Under the "password" I mean the one which should open the container using the auto-open feature. Both containers have 3 slots used. See the result:

```
# systemd-analyze blame
         10.234s systemd-cryptsetup@kabi.service
         2.693s systemd-cryptsetup@grafi.service
```

I tested this also with the debian script, and the result is the same, I mean, if the 128-char hash is in the first keyslot, then it takes ~2.5 secs to open the container. When it's in the 3rd, it takes ~10 secs.

@poettering 
Is there a possibility to add an option that would set which keyslot should be used when systemd have to open the LUKS containers automatically, so the mechanism won't go through all the keyslots? For now, the solution is to use only one keyslot, or place the password in the first one in order to reduce the time needed to open the containers.

**Comment by medhefgo** [comment]
A simple "man crypttab" would've told you there is.

**Comment by morfikov** [comment]
I've missed that option. I just tested it, and it looks it works as expected. The whole `ExecStart` line looks like this:

```
ExecStart=/lib/systemd/systemd-cryptsetup attach 'kabi' '/dev/disk/by-uuid/f3c10054-0583-4e10-937b-dcdc9a05a25c' 'none' 'luks,key-slot=0'
```
