### ISSUE TITLE
Broken link to "collision attacks" in RANDOM_SEEDS.md

### ISSUE THREAD

**Issue by mwleeds** [systemd/systemd#16245]
In `docs/RANDOM_SEEDS.md` there is the following link which doesn't work: https://rt.perl.org/Public/Bug/Display.html?CSRF_Token=165691af9ddaa95f653402f1b68de728

Perl bugs have been migrated to GitHub; maybe [this is the one](https://github.com/Perl/perl5/issues/14583) that was intended to be the link target?

**Comment by keszybz** [comment]
The original link has no bug number so it could have never worked. Dunno, https://github.com/Perl/perl5/issues/14583 has a lot of discussion, but it'd be nice to link to some writeup that's easier to consume.

**Comment by poettering** [comment]
Hmm the original paper that made the PERL issue public was this:

https://www.cs.auckland.ac.nz/~mcw/Teaching/refs/misc/denial-of-service.pdf

Maybe we should just link that.

That github but is not the one, no. Kinda sucks that the Perl link vanished
