### ISSUE TITLE
systemd-nspawn: memory accounting inside a container

### ISSUE THREAD

**Issue by TCB13** [systemd/systemd#16259]
**systemd version the issue has been seen with**

systemd 241 (241)

**Used distribution**

Debian GNU/Linux 10 (buster)

**Expected behaviour you didn't see**

Services / units / processes running inside containers should be able to use MemoryAccounting features.

**Unexpected behaviour you saw**

Can't get Memory information for anything running inside a container:

```
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-06-24 01:38:55 CEST; 11min ago
     Docs: man:sshd(8)
           man:sshd_config(5)
  Process: 39 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
 Main PID: 46
   CGroup: /system.slice/ssh.service
           └─46 /usr/sbin/sshd -D
```

**Steps to reproduce the problem**

1. Enable MemoryAccounting for all units in your host machine:

```
root@debian:~# cat /etc/systemd/system.conf | grep Memory
DefaultMemoryAccounting=yes
```

1. Create a new Debian container as follows
`````
debootstrap --include=ssh,locales,dbus,net-tools,vim,htop,gnupg2,curl,sudo,systemd --arch=amd64 buster my-
container
`````
2. Setup the container
`````
systemd-nspawn -M my-container --network-veth -a
root@my-container:~# passwd
root@my-container:~# rm /etc/securetty
root@my-container:~# systemctl enable systemd-networkd.service
root@my-container:~# cat /etc/systemd/system.conf | grep Memory
DefaultMemoryAccounting=yes
root@my-container:~# reboot
```
#
`````
3. Start the container 
`````
systemctl start systemd-nspawn@my-container
`````
4. Fetch systemctl status for any service inside the container. Memory information won't show up in the container, but everything works for the host:

```
root@debian:~# systemctl -M my-container status ssh
● ssh.service - OpenBSD Secure Shell server
   (...)
 Main PID: 46
   CGroup: /system.slice/ssh.service
           └─46 /usr/sbin/sshd -D

root@debian:~# systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
 (...)
 Main PID: 460 (sshd)
    Tasks: 1 (limit: 4558)
   Memory: 9.0M
   CGroup: /system.slice/ssh.service
           └─460 /usr/sbin/sshd -D
```

Thank you.

**Comment by poettering** [comment]
are you using cgroupv2? 

delegation of cgroup controllers to less privileged clients is not safe on cgroupv1, hence nspawn won't do it. If you use cgroupv2 it is safe and done and should just work.

**Comment by poettering** [comment]
We only track issues with the two most recent upstream systemd versions here. 241 is too old. For everything older, please contact downstream.

To keep frustration low the issue submission form tries to make this very very clear btw.
