### ISSUE TITLE
systemd-boot: Improve support for one-off boots from removable disks (e.g. flash drives)

### ISSUE THREAD

**Issue by michael-schaller** [systemd/systemd#16255]
**Is your feature request related to a problem? Please describe.**
We are interested in using `systemd-boot` on flash drives for our custom installer but we are concerned about these points:
* systemd-boot can't be configured so that it is independent of EFI variables.
* systemd-boot can't be configured to always show its menu without timeout.

**Describe the solution you'd like**
* The `timeout` config option could be changed so that a certain value (maybe `-1`) means that there is no timeout and that the menu has to be shown as the user has to select a menu entry.
* The `no-variables` option could be added to `loader.conf`. If set to true systemd-boot wouldn't read or write EFI variables similar to `bootctl --no-variables`.

**Describe alternatives you've considered**
* Currently we use `grub-mkstandalone` but we don't like its complexity and the many [patches Debian adds](https://sources.debian.org/patches/grub2/2.04-8/) on top of the upstream GRUB source.
* We've considered switching to `syslinux` but would actually prefer to move to `systemd-boot`.

**Additional notes**
Please let us know if you would accept patches for this feature request.

**Comment by poettering** [comment]
systemd-boot doesn't write persistent efi variables, unless told explicitly so (i.e by user interaction for example). The backing persistent memory is not necessarily of a quality we want to waste write cycles on, hence there's actually zero persisent variables we write during regular boot. We do read data from there though.  I am not sure what the problem with that is supposed to be. These variables are defined by sd-boot, and are hence not set except if the user explicitly did so, but in that case there's nothing wrong to consume them.

**Comment by poettering** [comment]
The title of this issueis kinda misleading, sd-boot supports removable disks just fine of course... it doesn't support infinite timeouts though.

**Comment by michael-schaller** [comment]
Our concern with `systemd-boot` reading/writing EFI variables is that variables like `LoaderConfigTimeout`, `LoaderConfigTimeoutOneShot`, `LoaderEntryDefault` and `LoaderEntryOneShot` should only apply to regular boots like for instance day to day booting of a Debian/Fedora/... installation.

Booting an installer from a flash drive isn't a regular boot though and hence should be independent of any config on the machine and we consider these EFI variables (if present) such config. This makes the `systemd-boot` behavior machine-specific (which is intentional for regular day to day boots) but this isn't desired for booting an installer, particularly as it makes it harder to document the installer workflow. For an installer we would really prefer if there would be an option in `loader.conf` with which we can ignore all machine-specific config so that we only rely on the config on the flash drive. 

I've also reworded the title. Hopefully this makes it less misleading.

**Comment by michael-schaller** [comment]
Lennart, would this feature request be acceptable? If not please let us know and we'll migrate to `syslinux` instead of `systemd-boot`.

**Comment by poettering** [comment]
send a patch, sure! both requests sound acceptable as long as it opt-in

**Comment by michael-schaller** [comment]
Cool and thanks! I think I'll start with the infinite timeout first...

**Comment by michael-schaller** [comment]
Looking at the current `timeout` implementation I have concerns introducing `-1` as infinite timeout.
* The `-`/`T` key press UX would IMHO be a bit weird as decreasing `0` (`Menu disabled`) to `-1` (`Menu always shown`) is probably unexpected.
* A timeout of `-1` is technically already used to unset the EFI variable:
  https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L788-L796

The easiest solution would probably be to choose a max timeout after which the timeout is disabled/infinite, maybe something `> 30`. This would also work with the current UX as then increasing with `+`/`t` past `30` could display `Menu always shown`.

Alternatively I could add `no_autoselect` to the config and disable the timeout in case there are no auto-selectable entries. That would also work for us but would probably be harder to document.

Lennart, what do you think? What would be your preference?

**Comment by michael-schaller** [comment]
Sorry for the silence on this issue. This was buried in my inbox and there was more important work to do...

So this bug and the discussion in the pull request went into a direction that would have made `sd-boot` a lot more complicated and I don't feel like this is the correct direction as I have doubts that this is beneficial for `sd-boot`. In the meanwhile a colleague of mine went ahead and did an internal fork of `sd-boot` that just doesn't read the persistent EFI variables. That was a direction I wanted to avoid but alas what's done is done and I think I should leave it to said colleague to work on a way to upstream his patch in a meaningful way...

So I'm closing this issue in favor of a future issue for whenever that colleague decides to upstream his patch.
