### ISSUE TITLE
Cannot umount /oldroot

### ISSUE THREAD

**Issue by wq-h** [systemd/systemd#16252]
Kernel version
```shell
# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```
systemd version the issue has been seen with
```shell
# systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
![image](https://user-images.githubusercontent.com/38638778/85399939-348d2100-b58a-11ea-9385-5ea576945596.png)

**Comment by poettering** [comment]
This is the upstream bugtracker. As the submission form should make very clear this is only for the two most recent upstream systemd versions, which is 244 and 245, which is *way* newer than 219. For everything older, please contact your downstream distro. Thank you for understanding.
