### ISSUE TITLE
hwdb: HP Elitebook 1040 G6 keyboard

### ISSUE THREAD

**Issue by surhudm** [systemd/systemd#16280]
**systemd version the issue has been seen with**
> systemd 245 (v245.6-2.fc32)

**Used distribution**
 > Fedora Core 32

**Expected behaviour you didn't see**
 > The keyboard's brightness control buttons should control brightness, the Mic mute button should mute the microphone and light up its led, the Monitor button and Call receive and Call end buttons should be assignable to certain actions.

**Unexpected behaviour you saw**
 > The keyboard brightness buttons do not change the brightness, the mic mute button does not mute the microphone or light up its led, the monitor button, call receive and call end buttons do not work either.

**Steps to reproduce the problem**
1) Install Fedora core 32 on HP Elitebook 1040 G6.
2) Press any of the brightness, mic mute, monitor or call receive or call end buttons. Nothing happens.

My diagnostic using evtest for the keycodes emitted by the keyboard on pressing these buttons and a possible solution for mic mute (although not perfect can be found [here](https://gist.github.com/surhudm/fd85edc531cdc41ca9ccda3b418e2a90) ). 

In this solution I managed to map the mic mute button using a new hwdb, but it maps the brightness keys to mic mute as well. This does not fix the micmute led though. 

I was also able to assign the Call Recv and Call End buttons to function as the brightness keys using acpid. Of course this is not ideal, but I hope I can get this resolved in the proper way.

**Comment by poettering** [comment]
Please submit the hwdb mapping as proper PR. We lack the hw in question and cannot test this for you hence rely on a ready patch submitted as PR in order to fix this.

**Comment by surhudm** [comment]
@poettering I can submit the half baked hwdb mapping as PR, but I will need help in fine tuning it. The keyboard emits multiple scan codes when a single key is pressed. Can such situations be handled through hwdb files? I started looking into this only after facing this issue. Some pointers regarding this would be helpful, and then I can submit as PR.

**Comment by poettering** [comment]
You can always suppress scancodes by mapping them to "unknown". It could also be that your key simply never generates a release event, in whih case you can use `!`. 

Consult the comments here: 

https://github.com/systemd/systemd/blob/master/hwdb.d/60-keyboard.hwdb

And see the existing entries.

**Comment by surhudm** [comment]
@poettering Submitted as PR #16419
