### ISSUE TITLE
Boot from virtio-fs

### ISSUE THREAD

**Issue by peterjohanson** [systemd/systemd#16288]
I'm not sure if it is a dracut or systemd issue ...
Virtio-fs is a new filesystem which allows to share a host directory with a virtual machine. It is also possible to boot from it. However, up to now I only could get it working without using an initrd/systemd.
When using dracut, which uses systemd, I get dropped to an emergency shell. When I press ctrl+D or enter my root password and exit the shell it continues to boot succesfully, so it works to some extend. Also the virtiofs module is loaded.
I use direct kernel boot (kernel 5.8-rc1) + a dracut initrd and "root=/dev/root rootfstype=virtiofs" on the kernel commandline.
The error I get is:
"Timed out waiting for device /dev/root"
"Dependency failed for initrd root device"
...
"dracut-initqueue - starting timeout scripts"|
"Starting Dracut Emergency Shell"

There is no /dev/root in the initrd since systemd (I guess) mounts devtmpfs in the /dev folder.
OS is Fedora 32.
For setting up virtiofs I used:
https://libvirt.org/kbase/virtiofs.html
You need a recent libvirt, qemu and kernel to make it work.

Documentation here: https://virtio-fs.gitlab.io/howto-boot.html
is a bit outdated (you can't use a tag to boot, but need to use /dev/root)

Any ideas how to get this working?
I know it is fairly new. Or is there some way to make systemd ignore the error and just continue to boot as an intermediate solution?

**Comment by poettering** [comment]
What is /dev/root supposed to be? That's not a real device, is it? 

I don't know virtio-fs, maybe contact that project for help? Or at least dracut?

**Comment by poettering** [comment]
The second link you posted suggstes to use root=none? Where does the /dev/root thing come from?

I really have no idea about all of this, but I think you should start with reading the docs you linked yourself, and inquiring with the virtio-fs and dracut projects...

Generally, this is not a support forum, but a bug and RFE tracker. This appears to be a support question for some other software. Hence, please contact that project for support, but let's not track this as a bug... Closing.

**Comment by keszybz** [comment]
virtiofs should be supported natively in systemd. We should figure out why it doesn't work.

**Comment by keszybz** [comment]
So… after some experimentation, it turns out that there's no bug in systemd.

The documentation under https://virtio-fs.gitlab.io/howto-boot.html is misleading and incomplete. But https://wiki.archlinux.org/title/QEMU#Host_file_sharing_with_virtiofsd is decent. Following those instructions I get a normal boot with mkosi-initrd (i.e. a pure systemd-based initrd):
```console
$ sudo mkosi -E KERNEL_VERSION=6.0.9-300.fc37.x86_64 build
$ sudo /usr/libexec/virtiofsd --socket-path=/tmp/vhostqemu -o source=$PWD/mkosi.output/fedora\~37/image -o cache=always
$ sudo chown $USER /tmp/vhostqemu
$ qemu-kvm -m 4G -object memory-backend-memfd,id=mem,size=4G,share=on -numa node,memdev=mem -kernel /lib/modules/6.0.9-300.fc37.x86_64/vmlinuz -initrd $PWD/mkosi.output/fedora~37/initrd.cpio.zstd -append "rootfstype=virtiofs root=myfs rw console=ttyS0 console=tty0" -serial stdio -chardev socket,id=char0,path=/tmp/vhostqemu -device vhost-user-fs-pci,chardev=char0,tag=myfs

[root@fedora ~]# findmnt /
TARGET SOURCE FSTYPE   OPTIONS
/      myfs   virtiofs rw,relatime
```

The docs are generally very incomplete, but the missing bits are on the side of qemu and virtiofsd… I don't see anything missing on our side, things seem to "just work".

When testing with libvirt, I can just add a virtiofs mount point and it's correctly exposed in the guest. Using that as root should also work.

--

I also tried to boot with dracut. This doesn't work out of the box:
```console
...
$ qemu-kvm -m 4G -object memory-backend-memfd,id=mem,size=4G,share=on -numa node,memdev=mem -kernel /lib/modules/6.0.9-300.fc37.x86_64/vmlinuz -initrd /boot/initramfs-6.0.9-300.fc37.x86_64.img -append "rootfstype=virtiofs root=myfs rw console=ttyS0 console=tty0" -serial stdio -chardev socket,id=char0,path=/tmp/vhostqemu -device vhost-user-fs-pci,chardev=char0,tag=myfs

[    1.953415] dracut: FATAL: Don't know how to handle 'root=myfs'
[    1.954002] dracut: Refusing to continue
```
But dracut has its own virtiofs module, and probably it'll work with that module enabled. I'm too lazy to check ;)
