### ISSUE TITLE
systemctl --host

### ISSUE THREAD

**Issue by milenBG** [systemd/systemd#16284]
Hello,

I used to check status of systemd units on remote PC with systemctl -H command.
After update to last version it doesn't work any more and returns exit code 1

systemctl --version
systemd 245 (245.6-8-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Comment by poettering** [comment]
Not a useful bug report. Please fill in the supplied issue submission form in full, provide console/log output and such.
