### ISSUE TITLE
systemd failed to load Swap File

### ISSUE THREAD

**Issue by pheiduck** [systemd/systemd#16289]
**systemd version the issue has been seen with**
>  systemd 245.6-8

**Used distribution**
 > Manjaro testing branch

**Expected behaviour you didn't see**
 > ...

**Unexpected behaviour you saw**
![grafik](https://user-images.githubusercontent.com/47042125/85846531-40edc580-b7a6-11ea-9d73-347bdd79a4db.png)

 > -- Logs begin at Wed 2020-06-24 22:51:32 CEST, end at Thu 2020-06-25 10:32:36 CEST. --
Jun 25 10:20:55 Workstation systemd[1]: /run/systemd/system/var-lib-systemd\x2dswap-swapfc-1.swap:11: Sorry, swap priorities smaller than -1 may only be assigned by the kernel itself, ignoring: -2
Jun 25 10:20:56 Workstation systemd[1]: Failed to activate swap Swap File.

**Steps to reproduce the problem**
Configure SwapFile (with btrfs)
https://wiki.manjaro.org/index.php?title=Swap#Swapfiles_on_BTRFS
https://wiki.manjaro.org/index.php?title=Swap#Automated_Swap_Management_with_systemd-swap
zswap_enabled=0
zram_enabled=0
swapfc_enabled=1
#swapfc_priority=100

Note:
swapfc_priority=100 didn't fix this.

**Comment by poettering** [comment]
I don't know what `systemd-swap` is. Despite its name it's not a systemd thing. That project should probably not use the "systemd-" prefix in its name...

Anyway, please contact the developers of the `systemd-swap` project, I don't know what they are doing, but it appears systemd itself is not the thing responsible for the negative swap priority configured.

Closing here.
