### ISSUE TITLE
Failed unmounting /home on shutdown

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#16291]
**systemd version the issue has been seen with**
> 245.6-8

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > /home partition should be umounted by systemd before power off

**Unexpected behaviour you saw**
 > Systemd reported that it could not umount /home and powered down the system

**Steps to reproduce the problem**
1) Log into DE (xfce4 in this case)
2) Initiate a reboot or shutdown

**Details**

I am seeing a warning indicting, "Failed unmounting /home" just before my system goes down.  It is consistently happening on every shutdown inspecting the journal.  I am unsure what is causing it and why systemd isn't pausing to wait for whatever it is to stop.

[Link](https://gist.github.com/graysky2/320fad79c56970d0066c6c3767992210) to complete journalctl when shutdown is initiated.

Relevant pieces of journalctl showing the error:
```
...
Jun 24 22:20:13 ease systemd[1]: Stopped Initialize hardware monitoring sensors.
Jun 24 22:20:13 ease systemd[1]: session-1.scope: Succeeded.
Jun 24 22:20:13 ease systemd[1]: Stopped Session 1 of user facade.
Jun 24 22:20:13 ease systemd[1]: Unmounting /home...
Jun 24 22:20:13 ease systemd[1]: Stopping Login Service...
Jun 24 22:20:13 ease systemd[1]: Stopping User Manager for UID 1000...
Jun 24 22:20:13 ease systemd-logind[568]: Removed session 1.
Jun 24 22:20:13 ease systemd[609]: Stopped target Main User Target.
Jun 24 22:20:13 ease systemd[609]: Stopping Accessibility services bus...
Jun 24 22:20:13 ease umount[1094954]: umount: /home: target is busy.
Jun 24 22:20:13 ease gvfsd[745]: A connection to the bus can't be made
Jun 24 22:20:13 ease systemd[609]: Stopping D-Bus User Message Bus...
Jun 24 22:20:13 ease gpg-agent[217307]: SIGTERM received - shutting down ...
Jun 24 22:20:13 ease gvfsd[215849]: A connection to the bus can't be made
Jun 24 22:20:13 ease systemd[609]: Stopping GnuPG cryptographic agent and passphrase cache...
Jun 24 22:20:13 ease systemd[609]: Stopping Virtual filesystem service - Apple File Conduit monitor...
Jun 24 22:20:13 ease systemd[609]: Stopping Virtual filesystem service...
Jun 24 22:20:13 ease systemd[609]: Stopping Virtual filesystem service - digital camera monitor...
Jun 24 22:20:13 ease systemd[609]: Stopping Virtual filesystem metadata service...
Jun 24 22:20:13 ease systemd[609]: Stopping Virtual filesystem service - disk device monitor...
Jun 24 22:20:13 ease systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
Jun 24 22:20:13 ease systemd[1]: Failed unmounting /home.
```

I am allowing systemd to manage mounts, `/etc/fstab`:
```
tmpfs /scratch  tmpfs size=29G,nodev,lazytime  0 0

LABEL=boot             /boot         ext4  defaults  0 1
LABEL=home             /home         ext4  noauto,x-systemd.automount  0 2
LABEL=lxc              /var/lib/lxc  ext4  noauto,x-systemd.automount  0 2
LABEL=incoming         /incoming     f2fs  noauto,x-systemd.automount,nodiscard  0 0
/dev/mapper/data-crypt /mnt/data     ext4  noauto,x-systemd.automount  0 0
```

Note - I do not see this problem if:
* Logged in as root/no graphical = clean reboot
* Logged in as user/no graphical = clean reboot
* Logged in as user --> `startxfce4` (no dm) = bad reboot
* Logged in as user via lxdm = bad reboot
* Logged in as user via sddm = bad reboot

Speculation is that something in xfce4 is causing the problem but I do not understand why systemd doesn't wait a timeout period to allow whatever it is to finish.

**Comment by graysky2** [comment]
Removing `/home/` from the control of x-systemd.automount fixes this issue, ie:
```
% grep home /etc/fstab 
LABEL=home             /home         ext4  defaults  0 2
```

Something within systemd is likely the culprit.

**Comment by poettering** [comment]
well, when we shutdown we'll try to stop as much as we can as quickly as we can. The only restrictions to this are the unit ordering dependencies. Now, if you have /home as autofs, then this means "mount this lazily, i.e. don#t wait for it at boot", i.e. establish them as late as possible. But this also then means (because ordering in systemd is symmetric: the shutdown order of two units is always the inverse of the startup order of them): stop them as early as possible. And this is were things go bad: if we stop them right away, they might still be busy, and that's what you see here...

We can probably add an explicit dep to systemd-logind.service or so that orders it *after* home.mount. During boot this doesn#t have too much effect: as long as the automount is never triggered, the mount won't be included in the initial ordering and thus the ordering doesn't matter. But at shutdown it does matter: if home.mount is up by then we'll stop it only after getting rid of systemd-logind.

It's slightly ugly however, since /home is the likely place for home directories but isn#t stritctly the only place where they could be placed.

**Comment by RokeJulianLockhart** [comment]
I see the same, using `systemd-256.12-1.fc41.x86_64` (on `cpe:/o:fedoraproject:fedora:41`):

1.	#### `journalctl`

	1.	~~~sh
		#!/usr/bin/env sh
		journalctl -b $boot_entry -e
		~~~

	1.	<blockquote>

		~~~log
		Apr 03 16:23:30 Beedell.RokeJulianLockhart.desktop.SSV2AY systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
		Apr 03 16:23:30 Beedell.RokeJulianLockhart.desktop.SSV2AY systemd[1]: Failed unmounting home.mount - /home.
		Apr 03 16:23:30 Beedell.RokeJulianLockhart.desktop.SSV2AY systemd[1]: run-media-RokeJulianLockhart-\x40\x7b_Name_\x3d_Data_\x3b\x20_Identifier_\x3d_S11VZD_\x7d\x23.dir.mount: Mount process exited, code=exited, status=32/n/a
		Apr 03 16:23:30 Beedell.RokeJulianLockhart.desktop.SSV2AY systemd[1]: Failed unmounting run-media-RokeJulianLockhart-\x40\x7b_Name_\x3d_Data_\x3b\x20_Identifier_\x3d_S11VZD_\x7d\x23.dir.mount - /run/media/RokeJulianLockhart/@{_Name_=_Data_; _Identifier_=_S11VZD_}#.dir.
		~~~

		</blockquote>

1.	#### `fstab`

	<details>

	1.	~~~sh
		#!/usr/bin/env sh
		cat /etc/fstab
		~~~

	1.	<blockquote>

		~~~sh
		#
		# /etc/fstab
		# Created by anaconda on Sun Mar  9 10:52:04 2025
		#
		# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
		# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
		#
		# After editing this file, run 'systemctl daemon-reload' to update systemd
		# units generated from this file.
		#
		UUID=e70e2a08-dcc9-4696-9a41-1b34ee1b4b94 /                       btrfs   subvol=root,compress=zstd:1 0 0
		UUID=7faeafbb-6206-458a-a6d4-36de13a6f8fd /boot                   ext4    defaults        1 2
		UUID=8C16-B16E          /boot/efi               vfat    umask=0077,shortname=winnt 0 2
		UUID=e70e2a08-dcc9-4696-9a41-1b34ee1b4b94 /home                   btrfs   subvol=home,compress=zstd:1 0 0
		~~~

		</blockquote>

	</details>
