### ISSUE TITLE
support controlling NIC device NamePolicy via kernel arguments

### ISSUE THREAD

**Issue by dustymabe** [systemd/systemd#16296]
**Is your feature request related to a problem? Please describe.**

No problem.

It would be nice to be able to control my NIC naming via a karg. 

**Describe the solution you'd like**

I can already disable predictable names via `net.ifnames` and I can already control the naming scheme via `net.naming-scheme`. It would be nice to be able to control the `NamePolicy` as defined in `/usr/lib/systemd/network/99-default.link` via a karg as well.

An example here would be useful. I run Fedora CoreOS. Fedora CoreOS starts as a disk image and configuration gets applied via Ignition on first boot. If I would like to change my `NamePolicy` to `mac` such that my interfaces are named like `enx123456789abc` then I have to boot the image, write a file into `/etc/systemd/network/99-default.link` and reboot. It would be more convenient if I could control this from the start with a karg.

Maybe this was considered before and decided against for good reason.

**Describe alternatives you've considered**

The alternative is what we have today :)

**Comment by poettering** [comment]
what's "kargs"? a kernel command line argument?

**Comment by dustymabe** [comment]
> what's "kargs"? a kernel command line argument?

Yes, kernel arguments. Sorry for not making that clear.
