### ISSUE TITLE
RFE: log when we receive an additional DNS server from NetworkManager, to make things easier to debug

### ISSUE THREAD

**Issue by tudorapo** [systemd/systemd#16298]
**systemd version the issue has been seen with**

$ systemctl --version
systemd 245 (245.4-4ubuntu3.1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Expected behaviour you didn't see**
 DNS server list remains the one received from DHCP

**Unexpected behaviour you saw**
```
 Link 2 (enp11s0)
      Current Scopes: DNS                     
DefaultRoute setting: yes                     
       LLMNR setting: yes                     
MulticastDNS setting: no                      
  DNSOverTLS setting: no                      
      DNSSEC setting: no                      
    DNSSEC supported: no                      
  Current DNS Server: fe80::bad8:12ff:fe66:b1b
         DNS Servers: 192.168.2.1             
                      fe80::bad8:12ff:fe66:b1b
          DNS Domain: ~.                      
                      tomka.heji              
                      lan
```

**Steps to reproduce the problem**
- Switch on computer
- Wait some time (maybe a hour?)

Hi,

The "fe80::bad8:12ff:fe66:b1b" was not configured by me and as it's not using information from the real dns, it is unable to resolve the local names provided by 192.168.2.1.

If this is a feature, what it's name, how to disable it, and why is it enabled by default?

If this is a bug, then please see the details above.

Thanks,

tg

**Comment by tudorapo** [comment]
[resolved.log](https://github.com/systemd/systemd/files/4841206/resolved.log)

[resolved.status.txt](https://github.com/systemd/systemd/files/4841207/resolved.status.txt)

Some logs, containing nothing useful.
[someconfs.txt](https://github.com/systemd/systemd/files/4841208/someconfs.txt)
resolved.conf and networkd.conf, containing linkclocaldressing which I thought was the source of this fake dns.

**Comment by poettering** [comment]
Maybe it's a DNS server configured via IPv6 RA?

**Comment by tudorapo** [comment]
1. how could I check that?
2. As far as I know my home network has no RA configured. 
3. fe80:: seems to be the 169.154 of the ipv6 world, so it's an address on the local host, it would be interesting for an RA to share addresses from this domain.

**Comment by poettering** [comment]
What networking implementation do you use? networkd? NetworkManager?

**Comment by tudorapo** [comment]
I think ubuntu uses networmanager, and after I disabled the systemd-resolved service I had to wrestle NetworkManager down from using 127.0.0.53 as a dns server.

**Comment by tudorapo** [comment]
Also if it was not clear: after boot the dns server list shows what I expect, my only dns server. After a while the fake one appears but as it's not logged anywhere (unlike the dhcp acquired one) I can't tell when it appears exactly.

**Comment by poettering** [comment]
maybe turn on debug logging in "systemd-resolved". It will then show you whenever some D-Bus peer registers a new DNS server. I'd still bet it's some IPv6 RA that NM picks up and tells resolved about.

Might also use Wireshark to look for that.

**Comment by tudorapo** [comment]
Hi,

Here it is the debug log, the bad8 dns appeared 20 minutes or so after boot. I can't find where it appears exactly.

[resolved.debug.log](https://github.com/systemd/systemd/files/4851044/resolved.debug.log)

**Comment by tudorapo** [comment]
Hmmm it happens around the time when this happens with network manager:
jún 30 12:03:26 capali NetworkManager[2160]: <info>  [1593511406.7216] dhcp6 (enp11s0): activation: beginning transaction (timeout in 45 seconds)
jún 30 12:04:11 capali NetworkManager[2160]: <warn>  [1593511451.5793] dhcp6 (enp11s0): request timed out
jún 30 12:04:11 capali NetworkManager[2160]: <info>  [1593511451.5794] dhcp6 (enp11s0): state changed unknown -> timeout
[nm.log](https://github.com/systemd/systemd/files/4851080/nm.log)

**Comment by tudorapo** [comment]
I would like to point out that this dns object appears without resolved acknowledging or logging about it. I think this is a bug in itself. Should I open a separate report or wait until we find out what's happening?

**Comment by tudorapo** [comment]
My apologies, there _was_ a RA, which was eliminated and the core issue is now seems to be fixed. 

Now about the logging of dns server acquirements.

**Comment by poettering** [comment]
i turned this into an RFE bug now, asking for explicit non-debug logging when a new DNS server is added from NM or other D-Bus clients

**Comment by tudorapo** [comment]
Thanks.
