### ISSUE TITLE
RFE: bump rlimit_memlock for services

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#16300]
**systemd version the issue has been seen with**
>systemd 243 (v243-4.gitef67743.fc31)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 >Fedora release 31 (Thirty One)

**Expected behaviour you didn't see**
 > run 'ulimit -l', the result is 65536KB (64M).

**Unexpected behaviour you saw**
 > run 'ulimit -l', the result is 64KB.

**Steps to reproduce the problem**
>Just run 'ulimit -l'

I'm not sure if this is a bug. But since this commit https://github.com/systemd/systemd/pull/13012/commits/e4e81c37aeccb200fa4efd29b2c895bb8ff36f82, the default rlimit_memlock (64K) was saved in arg_default_rlimit[RLIMIT_MEMLOCK], and this value was used **after** bumping rlimit_memlock. This results in the rlimit_memlock be 64K, not 64M (the value systemd tries to bump to).

**Comment by fbuihuu** [comment]
Before commit e4e81c37aeccb200fa4efd29b2c895bb8ff36f82 (not sure where this commit ID comes from because it's not part of the systemd git repo but github manages to show it...) the rlimit memlock default value was explicitly set to 64K (original value inherited from the kernel), see https://github.com/systemd/systemd/commit/e4e81c37aeccb200fa4efd29b2c895bb8ff36f82#diff-108b33cf1bd0765d116dd401376ca356L1212.

But this default value was "lost" as soon as systemd was reloaded, that's what the commit you pointed fixed.

@poettering not sure what the desired behavior is, should services inherit their default value from systemd (bumped one) or from the kernel ?

**Comment by keszybz** [comment]
e4e81c3 is called a9fd4cd1206832a61aaf61fff583bb133e6cb965 really.

For services we have DefaultLimitMEMLOCK=. By default it isn't set, so we get the kernel default. And this seems to be 64kb. So I don't think we have an error here. Instead, the kernel default is not very useful. I'll retitle accordingly.

**Comment by Geass-LL** [comment]
Yes, I have tried to change DefaultLimitMEMLOCK=64M in system.conf, and the MemLock changed to 64M indeed. But, I don't think this is the right way. The bump_rlimit_memlock function in src/core/main.c still doesn't take effect.

**Comment by keszybz** [comment]
What do you by "doesn't take effect"? Please paste `grep locked /proc/1/limits`.

**Comment by Geass-LL** [comment]
[root@localhost ~]# grep locked /proc/1/limits
Max locked memory         67108864             67108864             bytes

**Comment by poettering** [comment]
So the intended behaviour was that we set RLIMIT_MEMLOCK for PID 1 but not for anything forked off. i.e. child processes should get the original kernel setting. 

This is different from RLIMIT_NOFILE, where the hard limit is something we bump for everyone, not just for PID 1.

**Comment by poettering** [comment]
So, taking everything into consideration I think there's no acual bug here, sorry for the confusion. Everything works as expected now.

**Comment by keszybz** [comment]
But do you agree that we should bump it? I think something like 4MB would be reasonable as a default for services.

**Comment by poettering** [comment]
No idea what would be a better default. Given this is RAM we talk about here, it might make sense to make it a function based on physical_memory()?

Do we actually have requests to pick larger defaults? (Is this one?)

**Comment by poettering** [comment]
@Geass-LL are you asking that we globally bump the limit? see earlier question?

**Comment by Geass-LL** [comment]
> @Geass-LL are you asking that we globally bump the limit? see earlier question?

Thanks for the replies. Yes, bumpping the limit to 16M or something would be better.
But I still think there is something wroing. I have also run `grep locked /proc/1/limits` in CentOS8 (systemd-239), the value is also 67108864. However, in systemd-239, the bumped value is 16M.

**Comment by poettering** [comment]
> But I still think there is something wroing. I have also run `grep locked /proc/1/limits` in CentOS8 (systemd-239), the value is also 67108864. However, in systemd-239, the bumped value is 16M.

This is intended. In newer systemd versions we'll bump the limit for PID 1 itself, but carefully make sure to reset it to the original settings whenever we fork something off. Thus /proc/1/limits should always show the *high* value now, even if children that are forked off will have set it low as before.

**Comment by poettering** [comment]
BTW, kernel 5.16 changed the default to 8M. I'll post a PR shortly that makes systemd do the same (which is only relevant on old kernels and for nspawn)
