### ISSUE TITLE
fdstore access from outside of a specific service

### ISSUE THREAD

**Issue by giuseppe** [systemd/systemd#16318]
**Is your feature request related to a problem? Please describe.**

Podman needs to run rootless containers in the same user+mount namespaces.  Running all the containers in the same user namespace, instead of creating a new userns per container, is necessary in order to join namespaces created for other containers. e.g. Podman needs to join the same mount namespace in order to access existing mounts.

Since an unprivileged user is not able to pin an existing namespace to the file system (lack of `CAP_SYS_ADMIN` in the initial userns), Podman uses a "pause" process with the sole responsibility of keeping these two namespaces alive.

**Describe the solution you'd like**

I'd like to have a way to store the fds for these namespaces inside the user instance of systemd, so there is no need of running the "pause" process.  Ideally it would be possible to store/fetch/remove these fds using the d-bus API with ("name", FD).  The API should allow a way to specify whether the fd must be replaced if already existing, or return an error if a FD with the same name is already present in the store.

**Describe alternatives you've considered**

Running another process to keep these namespaces alive.

**Comment by poettering** [comment]
Did you see `FileDescriptorStoreMax=` and the `sd_pid_notify_with_fds()` APIs? What's missing for you there?

**Comment by giuseppe** [comment]
if I understand it correctly, `FileDescriptorStoreMax=` can be used only for services managed by systemd.  Can an interactive process be able to use these FDs?

**Comment by poettering** [comment]
This is only available to services run by systemd, as the lifecycle of those fds is bound to the service, i.e. the fds are closed the instant the service is stopped and no further jobs are queued for the service. 

Note that "run as systemd service" and "interactivity" are not contradictory. see "systemd-run -t" for example, which allows you to interactively invoke something as a systemd service, i.e. with full tty hookup and everything.

I am not convinced we should allow arbitrary processes pass fds to PID1, the lifecycle of that (given that fds come at a price) is just too vague, we need automatic clean-up when clients go, but this is nothing I can see how it could work if we'd allow arbitrary clients to upload stuff.

That said, #16332 is asking for a way to upload fds into the fdstore of other services. Maybe that might be something that could work: if we'd allow that (and the reverse, of requesting the fds of arbitrary services), and you define an empty service (i.e. without any ExecXYZ= line), then you could use it as a somewhat reasonable fd store, that is automatically cleaned up on shutdown, and is active as long as the stub service is up. And while it is up it wouldn't even cost anything besides some minimal memory in PID 1, as it wouldn't have to have any processes associated.

**Comment by rhatdan** [comment]
Since we would want the FD to last for the length of the user session,then would that work. Basically want this just for user sessions, I believe.

**Comment by poettering** [comment]
#27135 should address your usecase. It doesn't really implement what you are asking, but something similar: it allows you to have a socket activated service that runs only on demand and when a request comes in, but has access to the same set of fds each time.

Hence you could implement a tiny daemon that is socket activated, and when a specific request comes in allocates a userns, returns that to the client and uploads it to the fdstore and exits. Next time it is activated it will get the userns fd back from the fdstore, and would pass that to the client.

This way systemd would maintain the fd for you, you'd not to have to run a process all the time, only on demand.

I'll mark this RFE issue as implemented by that PR, even though it doesn't give you 1:1 what you are asking for.
