### ISSUE TITLE
networkd: DNS= should accept hostname for certificate validation in DoT

### ISSUE THREAD

**Issue by worldowner** [systemd/systemd#16327]
Currently I use .network file:

```
[Match]
Name=eno1

[Network]
DHCP=yes
LLMNR=no
MulticastDNS=no
DNS=IP_OF_DNS_SERVER_MANAGED_BY_ME

[DHCPv4]
UseDNS=false
```
I have configured ```DNSOverTLS=yes``` in resolved.conf.
DNS address set in .network file is propagated to resolved but name resolution doesn't work. I think that this is because dns's certificate doesn't contain IP address (it is Let's Encrypt certificate which doesn't issue certificates for IP).
Resolved allows for ```DNS=ip#hostname``` which makes name resolution working but also sets my DNS server as global DNS so queries that sould be sent do VPN-provided dns servers are sent to my server it in parallel which may be undesirable for privacy (not my case as I self-host my DNS) and performance reasons.

For consistency and to fix such scenario I think that DNS= in .network file should also accept ip#hostname format and propagate it to resolved. In result DNSOverTLS would work without setting self-hosted DNS server as Global.

**Comment by yuwata** [comment]
relevant comment: https://github.com/systemd/systemd/pull/14210#issuecomment-561565580

**Comment by yuwata** [comment]
I am now working on this.

@poettering How the port number should be configured through `DNS=`? Please provide the format.
