### ISSUE TITLE
Support delegating hugetlb (cgroup v2)

### ISSUE THREAD

**Issue by AkihiroSuda** [systemd/systemd#16325]
**Is your feature request related to a problem? Please describe.**
Please support delegating hugetlb controller to non-root users.
Expected to be used by rootless containers including Docker/Podman and Kubernetes.

**Describe the solution you'd like**

Support delegating hugetlb as follows:
```console
$  mkdir -p /etc/systemd/system/user@.service.d
$  cat > /etc/systemd/system/user@.service.d/delegate.conf << EOF
[Service]
Delegate=cpu cpuset hugetlb io memory pids
EOF
$  systemctl daemon-reload
```

Currently the hugetlb delegation is just ignored: `/etc/systemd/system/user@.service.d/delegate.conf:2: Invalid controller name 'hugetlb', ignoring`.

**Describe alternatives you've considered**
None

**Comment by AkihiroSuda** [comment]
cc @giuseppe @rhatdan

**Comment by giuseppe** [comment]
dup of https://github.com/systemd/systemd/issues/14662 ?
