### ISSUE TITLE
Failure in pam_systemd for non-local users

### ISSUE THREAD

**Issue by tkoeller-max** [systemd/systemd#16329]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Fedora 32

**Problem description**
 I am running a Fedora 32 (x86_64) system with Gnome desktop. My PAM stack contains the pam_systemd module in the session initialization part. I cannot start a Gnome session because pam-systemd fails like this:

`Jun 24 22:49:03 sarkovy gdm-password][8319]: pam_systemd(gdm-password:session): Failed to get user record: Input/output error`

The failure results in no systemd user instance being created, and hence no dbus.service to be started, which finally causes the session setup to be aborted. The problem only shows for non-local users that are authenticated via sssd and pam_sss. Local users are not affected.

Also see [this fedora bugzilla entry](https://bugzilla.redhat.com/show_bug.cgi?id=1836616).

**Comment by poettering** [comment]
if you run "userdbctl user <xyz>" on that offending user, what happens?

**Comment by tkoeller-max** [comment]
[root@sarkovy ~]# userdbctl user thomas
Failed to find user thomas: Input/output error
[root@sarkovy ~]# su thomas
[thomas@sarkovy root]$ id
uid=10000(thomas) gid=10000(domainusers) groups=10000(domainusers),0(root),10(wheel),18(dialout),39(video),190(systemd-journal),954(toranon),962(davfs2),987(wireshark),10001(family),10002(parents) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[

**Comment by poettering** [comment]
If you add debug logging to that:

`SYSTEMD_LOG_LEVEL=debug userdbctl user thomas`

what does that print?

**Comment by tkoeller-max** [comment]
[root@sarkovy ~]# SYSTEMD_LOG_LEVEL=debug userdbctl user thomas
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.Multiplexer: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"userName":"thomas","service":"io.systemd.Multiplexer"}}
/run/systemd/userdb/io.systemd.Multiplexer: varlink: changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Multiplexer: New incoming message: {"error":"io.systemd.System","parameters":{"errno":22}}
/run/systemd/userdb/io.systemd.Multiplexer: varlink: changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.System
/run/systemd/userdb/io.systemd.Multiplexer: varlink: changing state processing-reply → idle-client
Failed to find user thomas: Input/output error

**Comment by poettering** [comment]
hmm, if you stop "systemd-userdb.service and issue the same command again, what do you see then?

It appears the NSS module of your user provider returns some weird unexpected error

Anything possibly related in the system logs?

**Comment by tkoeller-max** [comment]
> hmm, if you stop "systemd-userdb.service and issue the same command again, what do you see then?
> 
> It appears the NSS module of your user provider returns some weird unexpected error
> 
> Anything possibly related in the system logs?

Assuming that systemd-userdb.service is a typo, and that you actually mean systemdbd.service, this is the result:

```[root@sarkovy ~]# systemctl stop systemd-userdbd.service systemd-userdbd.socket
[root@sarkovy ~]# systemctl stop systemd-userdbd.service systemd-userdbd.socket
[root@sarkovy ~]# SYSTEMD_LOG_LEVEL=debug userdbctl user thomas
Unable to connect to /run/systemd/userdb/io.systemd.Multiplexer: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.Home: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"userName":"thomas","service":"io.systemd.Home"}}
/run/systemd/userdb/io.systemd.Home: varlink: changing state idle-client → awaiting-reply
Unable to connect to /run/systemd/userdb/io.systemd.NameServiceSwitch: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"userName":"thomas","service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.Home: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Home: varlink: changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Home: varlink: changing state processing-reply → idle-client
Failed to do shadow lookup for user thomas, ignoring: No such process
   User name: thomas
 Disposition: regular
    Login OK: yes
 Password OK: yes
         UID: 10000
Unable to connect to /run/systemd/userdb/io.systemd.Multiplexer: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.Home: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":10000,"service":"io.systemd.Home"}}
/run/systemd/userdb/io.systemd.Home: varlink: changing state idle-client → awaiting-reply
Unable to connect to /run/systemd/userdb/io.systemd.NameServiceSwitch: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":10000,"service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Home: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Home: varlink: changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Home: varlink: changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state processing-reply → idle-client
Failed to do shadow lookup for group domainusers, ignoring: No such process
         GID: 10000 (domainusers)
Unable to connect to /run/systemd/userdb/io.systemd.Multiplexer: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.Home: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"userName":"thomas","service":"io.systemd.Home"},"more":true}
/run/systemd/userdb/io.systemd.Home: varlink: changing state idle-client → awaiting-reply-more
Unable to connect to /run/systemd/userdb/io.systemd.NameServiceSwitch: Connection refused
n/a: varlink: setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"userName":"thomas","service":"io.systemd.DynamicUser"},"more":true}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state idle-client → awaiting-reply-more
 Aux. Groups: root
              wheel
              video
              dialout
              systemd-journal
              wireshark
              davfs2
              toranon
/run/systemd/userdb/io.systemd.Home: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Home: varlink: changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Home: varlink: changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: varlink: changing state processing-reply → idle-client
   Real Name: Thomas Köller

   Directory: /home/thomas
     Storage: classic
       Shell: /bin/bash
   Passwords: none
```

The logs do not contain anything that seems relevant, in paticular, the only log entries pertaining to systemd-userdbd.{service,socket} are start/stop messages for those units.

**Comment by tkoeller-max** [comment]
In an attempt to gain more insight into the nature of the problem, I attached strace to the running systemd-userdbd process and executed 'userdbctl user thomas'. This is what I got (slightly edited in order to not expose my root password):
[userdbd.trace.txt](https://github.com/systemd/systemd/files/5003699/userdbd.trace.txt). It seems to me that the only data source that is consulted is /etc/shadow. This perfectly matches the observation that  user name lookup works for local users, but not for those from ldap:

```
[thomas@sarkovy ~]$ userdbctl user thomas
Failed to find user thomas: Input/output error
[thomas@sarkovy ~]$ userdbctl user testuser
   User name: testuser
 Disposition: regular
 Last Passw.: Fri 2020-06-26 02:00:00 CEST
    Login OK: yes
 Password OK: yes
         UID: 10005
         GID: 10000 (domainusers)
   Directory: /home/testuser
     Storage: classic
       Shell: /bin/bash
 Passwd Chg.: max 273y 9month 1w 4d 19h 30min/warn 1w
Pas. Ch. Now: no
   Passwords: none
     Service: io.systemd.NameServiceSwitch
Warning: lacking rights to acquire privileged fields of user record of 'testuser', output incomplete.
```

**Comment by poettering** [comment]
I wonder if #16668 is related to this?

**Comment by poettering** [comment]
is this reproducible on 246?

**Comment by poettering** [comment]
Hmm, I'd curious to know the full struct passwd and struct spwd for the offending user records?

**Comment by tkoeller-max** [comment]
> I wonder if #16668 is related to this?

Maybe. The record returned by LDAP looks like this:
```
[root@sarkovy thomas]# ldapsearch '(uid=thomas)'
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
# extended LDIF
#
# LDAPv3
# base <dc=koeller,dc=dyndns,dc=org> (default) with scope subtree
# filter: (uid=thomas)
# requesting: ALL
#

# thomas, people, koeller.dyndns.org
dn: uid=thomas,ou=people,dc=koeller,dc=dyndns,dc=org
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
uid: thomas
uidNumber: 10000
gidNumber: 10000
homeDirectory: /home/thomas
loginShell: /bin/bash
mail: thomas@koeller.dyndns.org
mail: thomas.koeller@baslerweb.com
cn:: VGhvbWFzIEvDtmxsZXI=
sn:: S8O2bGxlcg==
displayName:: VGhvbWFzIEvDtmxsZXI=

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

Note that the displayName, cn, and sn attributes are base-64 encoded. LDAP does this whenever a string contains non-ascii characters. I found that only entries with this property seem to be affected. There are other entries present in LDAP, for which these attributes contain plain ascii strings; these are processed correctly by userdbd, as it seems.

**Comment by tkoeller-max** [comment]
And this is what getent returns:
```
[root@sarkovy thomas]# getent passwd thomas
thomas:*:10000:10000:Thomas Köller:/home/thomas:/bin/bash
```

**Comment by tkoeller-max** [comment]
Without apparent reason, the problem disappeared. My system is still running systemd v245, so the fix is most likely a side effect of updating some other package. Anyway, I'm glad it's working again.

**Comment by poettering** [comment]
did you run this in a non-utf8 locale btw? i.e. the non-ascii chars, are they utf8 all the way?

**Comment by poettering** [comment]
I wonder if 5cd12abaa0c0f3a06c9ff2048941fbe6e8b3577e got backported and fixed it for you.

**Comment by tkoeller-max** [comment]
> I wonder if [5cd12ab](https://github.com/systemd/systemd/commit/5cd12abaa0c0f3a06c9ff2048941fbe6e8b3577e) got backported and fixed it for you.

I don't think so. My update history shows that systemd was last updated on 2020-08-06 and, as can be seen above, the problem was still present on 2020-08-08. That transaction also installed a new kernel, and is always reboot if this happend.

**Comment by tkoeller-max** [comment]
> did you run this in a non-utf8 locale btw? i.e. the non-ascii chars, are they utf8 all the way?

No, I am using utf8 throughout.

**Comment by poettering** [comment]
> > did you run this in a non-utf8 locale btw? i.e. the non-ascii chars, are they utf8 all the way?
> 
> No, I am using utf8 throughout.

hmm, but ldap, what does that use? utf8 too? it predates universal acceptance of utf8, no?

**Comment by tkoeller-max** [comment]
Well, as I wrote [here](https://github.com/systemd/systemd/issues/16329#issuecomment-670221701), ldap accepts utf8 strings, but internally stores them base64-encoded.

**Comment by i-garrison** [comment]
> Without apparent reason, the problem disappeared. My system is still running systemd v245, so the fix is most likely a side effect of updating some other package. Anyway, I'm glad it's working again.

One of Gentoo users reported very similar issue where `userdbctl user username` fails but works if any of `--no-varlink` or `--no-dropin` is provided. After user performed systemd first boot stuff by hand, `userdbctl user username` started to work as expected. Could this be related?

**Comment by Blackburn29** [comment]
> > Without apparent reason, the problem disappeared. My system is still running systemd v245, so the fix is most likely a side effect of updating some other package. Anyway, I'm glad it's working again.
> 
> One of Gentoo users reported very similar issue where `userdbctl user username` fails but works if any of `--no-varlink` or `--no-dropin` is provided. After user performed systemd first boot stuff by hand, `userdbctl user username` started to work as expected. Could this be related?

I can confirm after setting up a fresh gentoo install with systemd that running the firstboot/preset commands fixes this issue
