### ISSUE TITLE
A unit with unsatisfied condition should not stop a conflicting unit

### ISSUE THREAD

**Issue by luizluca** [systemd/systemd#16330]
**systemd version the issue has been seen with**
> systemd 245

**Used distribution**
 > OpenSUSE Tumbleweed

**Expected behaviour you didn't see**
 > A unit conditions should be satisfied before systemd stops its conflicting units

**Unexpected behaviour you saw**
 > A unit without a satisfied condition stops a running conflicting unit and it is immediately skipped because its condition check fails. The result is that both units are now down.

**Steps to reproduce the problem**

```
a.socket:
[Unit]
Before=b.socket
Conflicts=b.socket
ConditionPathExists=!/etc/passwd

[Socket]
ListenStream=6666
Accept=yes

[Install]
WantedBy=sockets.target
```

```
b.socket:
[Unit]

[Socket]
ListenStream=6666
Accept=yes

[Install]
WantedBy=sockets.target
```

```
systemctl start b.socket; systemctl status a.socket b.socket; systemctl start a.socket; systemctl status a.socket b.socket
```

Both sockets are down after this sequence.

My workaround was to use a ExecStartPre stopping a.socket when b.socket is started. However, this is simply a parallel manual dependency system, instead of using the native one.

**Comment by poettering** [comment]
Nah, this is simply not what conditions are. Conditions do not affect the job queue, they just cause services to ultimately be skipped. And that's explicitly documented. see systemd.unit(5) man page.

If you want to implement a logic that either a or b are added to the initial transition, use generators. see systemd.generator(7) man page.
