### ISSUE TITLE
don't set system time to systemd build time in pid1

### ISSUE THREAD

**Issue by gzjsgdsb** [systemd/systemd#16334]
**Is your feature request related to a problem? Please describe.**
Set a next best time when the device is missing time #10195
In some situations,user want to set the system time to older time like 2000/1/1,they will disable timesyncd service first ,but if the systemd is builded in 2009/1/1,user can't do this ,because pid1 systemd  will set the system time to systemd build time automatically,some times user don't know what happend

**Describe the solution you'd like**
if we disable timesyncd service,maybe we want to control the system time self,so don't set system time to systemd build time in pid1。
otherwise,user will not disable timesyncd,the time will set to systemd build in rtc lackless system by timesyncd

**Describe alternatives you've considered**
may be if the rtc device is exist,we don't set time to systemd build time in systemd,otherwise we do it

**Comment by poettering** [comment]
use `systemd.clock_usec=` to set the clock to arbitrary times at boot, so that the compiled-in epoch has no effect.

**Comment by gzjsgdsb** [comment]
thank you for replay,myy be arg_clock_usec have not initialized;

**Comment by gzjsgdsb** [comment]
> use the kernel command line option `systemd.clock_usec=` to set the clock to arbitrary times at boot, so that the compiled-in epoch has no effect.

thank you for replay,may be arg_clock_usec have not initialized;
