### ISSUE TITLE
systemd check failed in docker

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#16335]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > fedora32

**Expected behaviour you didn't see**
 > rpmbuild -ba systemd.spec successful

**Unexpected behaviour you saw**
 > check failed 

**Steps to reproduce the problem**
rpmbuild -ba systemd.spec in docker
![image](https://user-images.githubusercontent.com/38710185/86310546-f1e5db80-bc50-11ea-9d8c-2cee1bcc2cce.png)

**Comment by syyhao1994** [comment]
248/501 udev-test                               FAIL    30.84 s (exit status 1)
--- stderr ---
umount: test/tmpfs: no mount point specified.
/run/udev/rules.d/udev-test.rules:1 Unknown user 'bad', ignoring
/run/udev/rules.d/udev-test.rules:1 Unknown group 'name', ignoring
/run/udev/rules.d/udev-test.rules:1 Unknown user 'bad', ignoring
/run/udev/rules.d/udev-test.rules:1 Unknown group 'name', ignoring
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
sda: Failed to rename '/dev/..tmp-b8:0' to '/dev/.': Device or resource busy
tty0: Conflicting device node '/dev/tty0' found, link to '/dev/tty0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
ttyACM0: Conflicting device node '/dev/ttyACM0' found, link to '/dev/ttyACM0' will not be created.
/run/udev/rules.d/udev-test.rules:1 Invalid value for OPTIONS key, ignoring: 'last_rule'
/run/udev/rules.d/udev-test.rules:1 Invalid value for OPTIONS key, ignoring: 'last_rule'
/run/udev/rules.d/udev-test.rules:2 Unknown group 'not-ok', ignoring
/run/udev/rules.d/udev-test.rules:2 Unknown group 'not-ok', ignoring
/run/udev/rules.d/udev-test.rules:3 Unknown group 'not-ok', ignoring
/run/udev/rules.d/udev-test.rules:3 Unknown group 'not-ok', ignoring
/run/udev/rules.d/udev-test.rules:1: GOTO="does-not-exist" has no matching label, ignoring
/run/udev/rules.d/udev-test.rules:1: The line takes no effect any more, dropping
/run/udev/rules.d/udev-test.rules:1: GOTO="does-not-exist" has no matching label, ignoring
/run/udev/rules.d/udev-test.rules:1: The line takes no effect any more, dropping
/run/udev/rules.d/udev-test.rules:1 Invalid operator for KERNEL.
/run/udev/rules.d/udev-test.rules:1 Invalid operator for KERNEL.
/run/udev/rules.d/udev-test.rules:3 Invalid key/value pair, ignoring.
/run/udev/rules.d/udev-test.rules:3 Invalid key/value pair, ignoring.
sda: /run/udev/rules.d/udev-test.rules:2 Failed to parse mode '0400letsdoabuffferoverflow0123456789012345789012345678901234567890', ignoring: Invalid argument
sda: /run/udev/rules.d/udev-test.rules:2 Failed to parse mode '0400letsdoabuffferoverflow0123456789012345789012345678901234567890', ignoring: Invalid argument
/run/udev/rules.d/udev-test.rules:10001: Line is too long, ignored
/run/udev/rules.d/udev-test.rules:10001: Line is too long, ignored

290/501 test-condition                          FAIL     0.99 s (killed by signal 6 SIGABRT)
--- stderr ---
Found container virtualization none.
Assertion 'r >= 0' failed at src/test/test-condition.c:216, function test_condition_test_host(). Aborting.

308/501 test-fs-util                            FAIL     0.56 s (killed by signal 6 SIGABRT)
--- stderr ---
/* test_chase_symlinks */
Assertion 'r == -ENOTDIR' failed at src/test/test-fs-util.c:214, function test_chase_symlinks(). Aborting.


338/501 test-seccomp                            FAIL     1.75 s (killed by signal 6 SIGABRT)
/* test_restrict_realtime */
Assertion 'sched_setscheduler(0, SCHED_FIFO, &(struct sched_param) { .sched_priority = 1 }) >= 0' failed at src/test/test-seccomp.c:438, function test_restrict_realtime(). Aborting.
realtimeseccomp terminated by signal ABRT.
Assertion 'wait_for_terminate_and_check("realtimeseccomp", pid, WAIT_LOG) == EXIT_SUCCESS' failed at src/test/test-seccomp.c:458, function test_restrict_realtime(). Aborting.

377/501 test-strv                               FAIL     0.66 s (killed by signal 6 SIGABRT)
/* test_specifier_printf */
Assertion 'r >= 0' failed at src/test/test-strv.c:37, function test_specifier_printf(). Aborting.

380/501 test-execute                            FAIL    11.55 s (killed by signal 6 SIGABRT)
--- stderr ---
Found container virtualization none.
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/docker/d65077d6bf04fd14b097963e9cb5d33a74933b46f61e22e984a419e29267d3f1/docker/d65077d6bf04fd14b097963e9cb5d33a74933b46f61e22e984a419e29267d3f1/abb7291768889aa0.
Not running with unified cgroups, BPF firewalling is not supported.
Not running with unified cgroups, BPF device control is not supported.
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: yes
Controller 'io' supported: no
Controller 'blkio' supported: yes
Controller 'memory' supported: yes
Controller 'devices' supported: yes
Controller 'pids' supported: yes
Controller 'bpf-firewall' supported: no
Controller 'bpf-devices' supported: no
...
Failed to connect to nscd socket: No such file or directory
Failed to connect to nscd socket: No such file or directory
/root/rpmbuild/BUILD/systemd-243/test/test-execute/exec-specifier.service:28: Failed to resolve unit specifiers in test %m = $$(cat /etc/machine-id): No such file or directory
exec-specifier.service: Unit configuration has fatal error, unit will not be started.
exec-specifier.service: Failed to load configuration: Exec format error
Unit exec-specifier.service has a bad unit file setting.
Assertion 'manager_load_startable_unit_or_warn(m, unit_name, NULL, &unit) >= 0' failed at src/test/test-execute.c:204, function test(). Aborting.

392/501 test-id128                              FAIL     0.53 s (killed by signal 6 SIGABRT)
--- stderr ---
Assertion 'r >= 0' failed at src/test/test-id128.c:147, function main(). Aborting.

442/501 test-dhcp-client                        FAIL     2.87 s (killed by signal 6 SIGABRT)
--- stderr ---
Found container virtualization none.
Assertion 'client' failed at src/libsystemd-network/sd-dhcp-client.c:173, function sd_dhcp_client_set_request_option(). Ignoring.
Assertion 'client' failed at src/libsystemd-network/sd-dhcp-client.c:206, function sd_dhcp_client_set_request_address(). Ignoring.
Assertion 'client' failed at src/libsystemd-network/sd-dhcp-client.c:219, function sd_dhcp_client_set_ifindex(). Ignoring.
Assertion 'ifindex > 0' failed at src/libsystemd-network/sd-dhcp-client.c:221, function sd_dhcp_client_set_ifindex(). Ignoring.
Assertion 'ifindex > 0' failed at src/libsystemd-network/sd-dhcp-client.c:221, function sd_dhcp_client_set_ifindex(). Ignoring.
Assertion 'ifindex > 0' failed at src/libsystemd-network/sd-dhcp-client.c:221, function sd_dhcp_client_set_ifindex(). Ignoring.
DHCP CLIENT (0x0): FREE
DHCP CLIENT (0x0): FREE
DHCP CLIENT (0xa9cec30e): STARTED on ifindex 42
DHCP CLIENT (0xa9cec30e): STOPPED
DHCP CLIENT (0x0): FREE
DHCP CLIENT (0x2d58cdcc): STARTED on ifindex 42
Code should not be reached 'Test case should have completed in 2 seconds' at src/libsystemd-network/test-dhcp-client.c:35, function test_dhcp_hangcheck(). Aborting.

447/501 test-dhcp6-client                       FAIL     0.52 s (killed by signal 6 SIGABRT)
--- stderr ---
Found container virtualization none.
/* test_client_basic */
Assertion 'ifindex >= -1' failed at src/libsystemd-network/sd-dhcp6-client.c:133, function sd_dhcp6_client_set_ifindex(). Ignoring.
/* test_option */
/* test_option_status */
DHCPv6 CLIENT: IA status 1
/* test_advertise_option */
DHCPv6 CLIENT: Using deprecated SNTP information
/* test_client_solicit */
Assertion 'sd_dhcp6_client_start(client) >= 0' failed at src/libsystemd-network/test-dhcp6-client.c:924, function test_client_solicit(). Aborting.

**Comment by syyhao1994** [comment]
I found that the /etc/machin-id is missed in docker，but after i reinstall systemd in docker， there is still a failure, 

338/501 test-seccomp                            FAIL     1.65 s (killed by signal 6 SIGABRT)
--- stderr ---
Found container virtualization none.
/* test_seccomp_arch_to_string */
/* test_architecture_table */
seccomp-arch: native → 0x0 → native
seccomp-arch: x86 → 0x40000003 → x86
seccomp-arch: x86-64 → 0xc000003e → x86-64
seccomp-arch: x32 → 0x4000003e → x32
seccomp-arch: arm → 0x40000028 → arm
seccomp-arch: arm64 → 0xc00000b7 → arm64
seccomp-arch: mips → 0x8 → mips
seccomp-arch: mips64 → 0x80000008 → mips64
seccomp-arch: mips64-n32 → 0xa0000008 → mips64-n32
seccomp-arch: mips-le → 0x40000008 → mips-le
seccomp-arch: mips64-le → 0xc0000008 → mips64-le
seccomp-arch: mips64-le-n32 → 0xe0000008 → mips64-le-n32
seccomp-arch: ppc → 0x14 → ppc
seccomp-arch: ppc64 → 0x80000015 → ppc64
seccomp-arch: ppc64-le → 0xc0000015 → ppc64-le
seccomp-arch: s390 → 0x16 → s390
seccomp-arch: s390x → 0x80000016 → s390x
...
Failed to add rule for system call signalfd() / -10173, ignoring: Numerical argument out of domain
Failed to add rule for system call sigpending() / -10056, ignoring: Numerical argument out of domain
Failed to add rule for system call sigprocmask() / -10057, ignoring: Numerical argument out of domain
Failed to add rule for system call sigsuspend() / -10059, ignoring: Numerical argument out of domain
Failed to add rule for system call sync_file_range2() / -10089, ignoring: Numerical argument out of domain
Failed to add rule for system call alarm() / -10148, ignoring: Numerical argument out of domain
Failed to add rule for system call fadvise64_64() / -10007, ignoring: Numerical argument out of domain
Failed to add rule for system call oldolduname() / -10036, ignoring: Numerical argument out of domain
Failed to add rule for system call olduname() / -10038, ignoring: Numerical argument out of domain
Failed to add rule for system call readdir() / -10041, ignoring: Numerical argument out of domain
Failed to add rule for system call sendfile64() / -10043, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsgid32() / -10044, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsuid32() / -10045, ignoring: Numerical argument out of domain
...
/* test_restrict_realtime */
Assertion 'sched_setscheduler(0, SCHED_FIFO, &(struct sched_param) { .sched_priority = 1 }) >= 0' failed at src/test/test-seccomp.c:438, function test_restrict_realtime(). Aborting.
realtimeseccomp terminated by signal ABRT.
Assertion 'wait_for_terminate_and_check("realtimeseccomp", pid, WAIT_LOG) == EXIT_SUCCESS' failed at src/test/test-seccomp.c:458, function test_restrict_realtime(). Aborting.

**Comment by poettering** [comment]
Docker doesn't play nice and sets up a broken environment for systemd code to run in. If you want to run systemd code in docker, make sure to follow the Container Interface: https://systemd.io/CONTAINER_INTERFACE/

if you implement those rules it should work, but otherwise Docker just sets up a borked environment that systemd cannot run in. sorry.
