### ISSUE TITLE
tmpfiles' 'R' and 'r' should support age field

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#1633]
I think it currently is _not_ possible to simply remove a directory after a delay without creating it if doesn't exist. According to comment in the source, 'R' does not honour 'x' excludes either.

**Comment by poettering** [comment]
Hmm, but what's that really supposed to mean? Aging so far is supposed to clean up stuff _inside_ of directories, but not the directories themselves. Are you suggesting that in the case of r/R it would clean-up the directory itself?

**Comment by keszybz** [comment]
Yes, also the directory. Also, both 'd' and 'D' would create the directory. I don't want that.

**Comment by paulraines68** [comment]
Am I missing something, or how else is someone supposed do something like 
"Delete all files matching /tmp/tmp*.nii if older than 1 day" but with 

r /tmp/tmp*.nii - - - 1d

which right now deletes them no matter what the age.  This seems like a common critical function systemd should be able to do if it is replacing tmpwatch

At the very least I think systemd should default to generating an error on the above config instead of just deleting whatever the age.

**Comment by poettering** [comment]
> Am I missing something, or how else is someone supposed do something like
> "Delete all files matching /tmp/tmp*.nii if older than 1 day" but with
> 
> r /tmp/tmp*.nii - - - 1d
> 
> which right now deletes them no matter what the age. This seems like a common critical function systemd should be able to do if it is replacing tmpwatch

"r" has an effect during boot only, the aging logic is independent of that, and is the only thing that is done repeatedly during runtime. Hence, what this issue requests is that you can combine both: remove the ting during boot, and during when old also during runtime.

**Comment by paulraines68** [comment]
Well, "r!" then would signify only at boot then but for backward compatibility maybe one could have if no age is given at all, "r!" is assumed.  You would need to explicitly give "0" for age to have it remove the files anytime they are found during runtime

**Comment by thkoch2001** [comment]
This has also been asked for here:
https://unix.stackexchange.com/questions/500197/using-systemd-tmpfiles-to-remove-a-file-pattern-by-age

Seeing also other features requested for tmpfiles (e.g. [1](https://github.com/systemd/systemd/issues/24736), [2](https://github.com/systemd/systemd/issues/23965), [3](https://github.com/systemd/systemd/issues/21402), [4](https://github.com/systemd/systemd/issues/24788)), I believe that one would quickly end up in feature-creeping tmpfiles towards a configuration management tool. Which indicates to me, that tmpfiles itself might probably better be replaced by proper configuration management tool.
