### ISSUE TITLE
systemd-networkd does not appear to reset the valid/preferred lifetime of delegated IPv6 prefixes when doing a DHCPv6 RENEW, leading to loss of IPv6 connectivity

### ISSUE THREAD

**Issue by mamarley** [systemd/systemd#16356]
**systemd version the issue has been seen with**
> git HEAD

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > Valid and preferred lifetimes for IPv6 delegated prefixes as announced in RAs should be reset after a DHCPv6 RENEW renews the lease.

**Unexpected behaviour you saw**
 > The lifetimes continue decrementing towards 0, causing loss of IPv6 connectivity for devices behind the router when 0 is reached.

**Steps to reproduce the problem**
1. Set up systemd-networkd to do DHCPv6 PD and delegate the prefixes to one or more interfaces.
2. Watch as the valid and preferred lifetimes for the delegated prefixes as shown by "rdisc6" continue to decrement toward 0 even after the DHCPv6 client renews the lease.
3. Watch as IPv6 connectivity stops working when the lifetimes reach 0.

**Comment by mamarley** [comment]
After more testing and research, it seems this issue is in git HEAD, not 245 as I previously wrote, and is actually caused by https://github.com/systemd/systemd/commit/02e9e34bd9a8a252610e181533e477ec10733e27.

**Comment by mamarley** [comment]
Specifically, it appears that the call to dhcp6_link_has_dhcpv6_prefix() on line 315 of src/network/networkd-dhcp6.c is returning true when the interface in question already has a prefix assigned, which is causing the prefix to never be reassigned and updated (line 334).  I don't understand this code well enough to be able to tell why this changed in https://github.com/systemd/systemd/commit/02e9e34bd9a8a252610e181533e477ec10733e27 though, so I can't propose a fix.

**Comment by ssahani** [comment]
Ohh it's a serous bz

**Comment by mamarley** [comment]
For what it is worth, I did a build with that "if (dhcp6_link_has_dhcpv6_prefix(link))" commented out and that returns it to previous (correct) behavior.

**Comment by yuwata** [comment]
@mamarley Your investigation sounds correct for me. See #16380.

**Comment by mamarley** [comment]
With the patch it works correctly now, thanks!
