### ISSUE TITLE
scope rmdir cgroup path return EBUSY cause session remain

### ISSUE THREAD

**Issue by JackFangXN** [systemd/systemd#16350]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 >

Sftp transfers a large number of files. After running for a period of time, you will find that many sessions remain in the system(/sys/fs/cgroup/systemd, /sys/fs/cgroup/memory).

**Expected behaviour you didn't see**
 > …
stop transfer file and no session remain.

**Unexpected behaviour you saw**
many sessions remain, this session cat tasks is 0.
![image](https://user-images.githubusercontent.com/53254947/86460489-10d09480-bd5b-11ea-85d2-573820881e86.png)

 > …

**Steps to reproduce the problem**

**Comment by JackFangXN** [comment]
stop to transfer files and will close session.  all cgroup processes have been killed.
when session**.scope state is dead, will call unit_prune_cgroup to clear cgroups.
Call rmdir to clear the cgroup path maybe return EBUSY, result in the cgroup of
 sessions remain.
unit_prune_cgroup->cg_trim_everywhere
![image](https://user-images.githubusercontent.com/53254947/86461223-3d38e080-bd5c-11ea-8af9-c0b6033c31df.png)

**Comment by JackFangXN** [comment]
https://github.com/systemd/systemd/pull/16349 , this pr can fix it, maybe not best.

**Comment by Werkov** [comment]
@JackFangXN The sessions are opened on the server side of the SFTP connection? How do the transfers and sessions terminate? (Do you have syslog with debug level systemd/logind messages?)

**Comment by JackFangXN** [comment]
session-6248.scope is remain, the log is below. We can find "Removed session 6248" in the log, but session-6248.scope always 
exist.
![image](https://user-images.githubusercontent.com/53254947/88030332-ae0a3600-cb6d-11ea-9c0f-81e2f97d23f7.png)

![image](https://user-images.githubusercontent.com/53254947/88030447-d1cd7c00-cb6d-11ea-99df-54b9e55c3b97.png)
![image](https://user-images.githubusercontent.com/53254947/88030488-e1e55b80-cb6d-11ea-8ec4-b49c376eced2.png)
![image](https://user-images.githubusercontent.com/53254947/88030534-ef024a80-cb6d-11ea-9073-9c0c1ac8ca1c.png)

**Comment by Werkov** [comment]
Thanks for the logs. The relevant message is
> systemd[1]: session-6248.scope: Succeeded
It's called from `scope_enter_dead()` and that's when cgroup would be removed (i.e. after empty notification, the session scope is only abandoned, not stopped explicitly).
What is `TimeoutStopUSec=` of the offending scopes (`systemctl show -p TimeoutStopUSec foo.scope`)?

**Comment by JackFangXN** [comment]
TimeoutStopUSec is default time 90s.
![image](https://user-images.githubusercontent.com/53254947/88494830-45e2a680-cfea-11ea-9026-abdd1912cde8.png)

**Comment by JackFangXN** [comment]
@Werkov

**Comment by anitazha** [comment]
I'm running cgroup2 and another cause for EBUSY I ran into from strace-ing was due to sub-cgroups under the session scope owned by root. So I had a cgroup, e.g. `/sys/fs/cgroup/user.slice/user-1000.slice/test.scope` and no processes were in it. But under `test.scope` there was also e.g. `/sys/fs/cgroup/user.slice/user-1000.slice/test.scope/payload/init.scope`, where `/.../test.scope/payload/` and `/.../tests.scope/payload/init.scope` were made through sudo. The systemd user manager owns `test.scope` so it tries to `rmdir()` starting with `/.../tests.scope/payload/init.scope`, but fails because its parent directory is owned by root.

It's bit specific (I'm filing an issue for my problem) but could you possibly be getting EBUSY due to lack of permission deleting sub-cgroups in your session scopes?

**Comment by Werkov** [comment]
Good point about the subgroups (although unless `Delegate=` is set, creating subdirs violates [systemd assumptions](https://systemd.io/CGROUP_DELEGATION)). I also noticed in the original comment that this pertains to legacy hierarchy setup.

@JackFangXN I'd like to ask for the following information:
- Enable debug logging in systemd. Can you please provide such debug logs capturing termination of session with a leaked directory?
- Are there any subdirs created in your scope cgroups?
- What kernel version do you run on? (To rule out some erroneous notifications.)

Thanks.

**Comment by poettering** [comment]
@JackFangXN is that on cgroupsv1 or cgroupvs2?

**Comment by poettering** [comment]
Closing due to lack of response.
