### ISSUE TITLE
armhf container cannot be started on amd64 host

### ISSUE THREAD

**Issue by emojifreak** [systemd/systemd#16359]
**systemd version the issue has been seen with**
245.6

**Used distribution**
Debian 11 Bullseye on amd64 with qemu-user-static 5.0.
Downstream report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964289
I am told there that
> I'm not sure if this is supported and supposed to work

If this is an unsupported feature, please close this.

**Expected behaviour you didn't see**
 systemd-nspawn -M armhf-bullseye -b starts the container

**Unexpected behaviour you saw**
 
```
# systemd-nspawn -D /var/lib/machines/armhf-bullseye   -b
Spawning container armhf-bullseye on /var/lib/machines/armhf-bullseye.
Press ^] three times within 1s to kill container.
systemd 245.6-1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Detected virtualization systemd-nspawn.
Detected architecture arm.

Welcome to Debian GNU/Linux bullseye/sid!

Set hostname to <armhf-bullseye>.
Failed to enqueue loopback interface start request: Operation not supported
Caught <SEGV>, core dump failed (child 3, code=killed, status=11/SEGV).
Exiting PID 1...
Container armhf-bullseye failed with error code 255.
```

**Steps to reproduce the problem**

```
# mmdebstrap --components="main contrib non-free" --architectures=armhf --variant=important bullseye /var/lib/machines/armhf-bullseye
# systemd-nspawn -D /var/lib/machines/armhf-bullseye   -b
```

Note that 
* `systemd-nspawn -D /var/lib/machines/armhf-bullseye   -a` works fine.
* The same symptom is observed when container's distribution is Debian Buster (stable) armhf.
* When the container's distribution is Debian Buster **MIPS 32-bit big endian**, then systemd-nspawn -b **DOES WORK**. The container was made with `mmdebstrap --architectures=mips`.

**Comment by poettering** [comment]
Please report this to qemu, there's nothing actionable to us here. We neither interpret nor synthesize the ARM machine code here, that's between qemu and gcc/your distro. Please contact them.

Sorry!

**Comment by emojifreak** [comment]
Thank you! I will do that.

**Comment by emojifreak** [comment]
This issue was reported to QEMU at https://bugs.launchpad.net/qemu/+bug/1886811 and confirmed.
