### ISSUE TITLE
RemainAfterElapse=no in timer has no effect at all

### ISSUE THREAD

**Issue by braindevices** [systemd/systemd#16378]
**systemd version the issue has been seen with**
> systemd 243 (v243.8-1.fc31)

**Used distribution**
 > with RemainAfterElapse=no,  the timer is supposed to be inactive after target time reached. But it does not.

**Expected behaviour you didn't see**
 > the timer should be inactive after 5 sec.

**Unexpected behaviour you saw**
 > the timer is active after 28mins.

**Steps to reproduce the problem**

my.timer:
```
[Timer]
AccuracySec=1
OnActiveSec=5
Unit=my.target
RemainAfterElapse=no
```
```
$ systemctl status my.timer
● my.timer
   Loaded: loaded (/etc/systemd/system/my.timer; static; vendor preset: disabled)
   Active: active (running) since Mon 2020-07-06 21:50:33 CEST; 28min ago
  Trigger: n/a
```

**Comment by poettering** [comment]
(or in other words: once you issue `systemctl stop my.target` in your example the timer unit should unload instantly, doesn't it?)
