### ISSUE TITLE
change Storage=persistent to Storage=volatile， /var/log/journal remains.

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#16384]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > the journal files dir will change from /var to /run.

**Unexpected behaviour you saw**
 >/var/log/journal remains.

**Steps to reproduce the problem**
change Storage=persistent to Storage=volatile, then run "systemctl restart systemd-journald"

**Comment by poettering** [comment]
Yeah, we don't remove stuff just because you change configuration.

Might be something to document explicitly, but it appears to me the current behaviour makes a ton of sense and should stay that way.

**Comment by fayeinseu** [comment]
Thanks for your answer. document is a good way.
