### ISSUE TITLE
problem when entering multi-user.target and then back to graphical.target

### ISSUE THREAD

**Issue by vifm9** [systemd/systemd#16393]
the first one is that the device is administratively down. so the command 
nmcli device connect <device> must be used to bring up the device

the second problem is that operations like reboot need sudo access now.

is there a way to make the transition between the states as if i were directly logged in to graphical.target?

**Comment by poettering** [comment]
This does not look like a systemd upstream issue. Please contact your downstream distribution first, they will escalate this to us, if they are sufficiently sure that this is a systemd issue.
