### ISSUE TITLE
systemd should remount the fs R/O if it cannot be umounted on reboot

### ISSUE THREAD

**Issue by soig** [systemd/systemd#16397]
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > Mageia Linux

**Expected behaviour you didn't see**
 > No fsck on reboot

**Unexpected behaviour you saw**
 > The /home FS is not properly umounted on reboot (due to screen(1) leftover?), which causes a fsck on startup

**Steps to reproduce the problem**
Reboot my personal system.

I don't reboot it often, maybe once every 2 months, but everytime, at startup, a slow fsck is started on it.
As a bonus, the automatic fsck.ext4 usually fails (for bogus reason such as having to say yes for shrinking directories.
Last occurrence was this morning, I only see a message looking like "…is still in use" flashing at screen before reboot completed

I don't know why it fails to umount (maybe because I always have a remote screen(1) session, but systemd could prevent the fsck by remounting the system as read-only (a little bit like magic sysrq alt-print-U)

Or it could try to kill any leftover processes.

My FS layout has nothing exotic IMHO:
* / as ext4
* /home as ext4 (this is the one which is always fscked on reboot)
* 2 other ext4 fs in /media/big{,2}
* swap as file on /media/big2/swap.img (so dep on /media/big2 but that's orthogonal to /home fsck issue)

**Comment by poettering** [comment]
We already do that, but for many file systems that's not sufficient to make them clean.

See this:

https://github.com/systemd/systemd/blob/master/src/shutdown/umount.c#L505
