### ISSUE TITLE
systemd: logind parameters "IdleAction=Lock" is not working

### ISSUE THREAD

**Issue by venkata-pyla** [systemd/systemd#16391]
**systemd version the issue has been seen with**
> Version: 241-7

**Used distribution**
 >Debian 10.4 Desktop

**Expected behaviour you didn't see**
> In logind.conf `IdleAction=Lock` should send `Lock` event when system is Idle

**Unexpected behaviour you saw**
 >Not received any `Lock` event After the above configuration and restart of system, 

**Steps to reproduce the problem**
* Disable other Auto Lock features in desktop environment.
* Set 'Blank screen' timeout to 5min
* Configured the logind for recieving the `Lock` event action after reaching system Idle.
logind.conf
```
[Login]
IdleAction=lock
IdleActionSec=1min
```
* Restart the system and waited using a sample application which is registered for dbus event "Lock"
* waited for more than 10min after system lid is off, not received any "Lock" event, and when i saw the status logs the idle action was initiating but no dbus event generated
```
========================================================================================
● systemd-logind.service - Login Service
   Loaded: loaded (/lib/systemd/system/systemd-logind.service; static; vendor
preset: enabled)
   Active: active (running) since Tue 2020-06-16 19:48:42 IST; 2 days ago
     Docs: man:systemd-logind.service(8)
           man:logind.conf(5)
           https://www.freedesktop.org/wiki/Software/systemd/logind
           https://www.freedesktop.org/wiki/Software/systemd/multiseat
 Main PID: 634 (systemd-logind)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 2.6M
   CGroup: /system.slice/systemd-logind.service
           └─634 /lib/systemd/systemd-logind

Jun 19 18:09:08 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:10:38 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:12:08 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:13:38 debian systemd-logind[634]: System idle. Taking action.
Jun 19 18:15:08 debian systemd-logind[634]: System idle. Taking action.
========================================================================================
```
With curiosity i have checked the source code and after applying the below change i could see the `Lock` event is generating and  my sample application could recieve it.

```diff
diff --git a/src/login/logind.c b/src/login/logind.c
index 95ec0a57c6..ea505ceed8 100644
--- a/src/login/logind.c
+++ b/src/login/logind.c
@@ -1019,7 +1019,7 @@ static int manager_dispatch_idle_action(sd_event_source
*s, uint64_t t, void *us
                     (m->idle_action_not_before_usec <= 0 || n >=
m->idle_action_not_before_usec + m->idle_action_usec)) {
                         log_info("System idle. Taking action.");

-                        manager_handle_action(m, 0, m->idle_action, false,
false);
+                        manager_handle_action(m, 0, m->idle_action, false,
true);
                         m->idle_action_not_before_usec = n;
                 }
```
Is there any specific reason blocking the "Lock" action in the [source code](https://github.com/systemd/systemd/blob/d7b34e384108ff431401d942ec0daaf156ec27c1/src/login/logind-action.c#L94)?

can we apply the above change to the master branch?

Thanks,
venkata.

**Comment by venkata-pyla** [comment]
Hi,

can i know the feedback for this issue.

Thanks,
venkata.

**Comment by poettering** [comment]
please submit your patch as a PR, we'll review it then like we usually do with proposed code changes.

**Comment by OJFord** [comment]
I'm a little unclear about the status here - `IdleAction=lock` doesn't seem to be working (locking) for me, is it expected to be working at all?
