### ISSUE TITLE
systemd-boot strange behavior & not working anymore.

### ISSUE THREAD

**Issue by bionade24** [systemd/systemd#16408]
**Arch Linux, systemd  245.6-7  and systemd-245.5-2 (downgraded)**
> ...

**Used distribution, used Laptop**
 > …Arch Linux, Dell Precision 7540

**Expected behaviour you didn't see**
 > … System boots

**Unexpected behaviour you saw**
 > … Systemd-boot hangs (Like if initrd path is wrong.)

Original entry:
```
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options root=UUID=88dbf04d-9daa-40b2-8b83-870eb2f24d56 nvidia-drm.modeset=1 i915.enable_dpcd_backlight=1
```
Didn't work, it was suggested to remove the `/` or use `\`
Removing `/`: Didn't work
Substitute `/` with `\`: Worked for one boot, now doesn't work either.
Entry from last try:
```
title Arch Linux
linux vmlinuz-linux
initrd intel-ucode.img
initrd initramfs-linux.img
options root=UUID=88dbf04d-9daa-40b2-8b83-870eb2f24d56 nvidia-drm.modeset=1 i915.enable_dpcd_backlight=1
```
Fallback-entry from last try:
```
title Arch Linux (fallback)
linux \vmlinuz-linux
initrd \intel-ucode.img
initrd \initramfs-linux-fallback.img
options root=UUID=88dbf04d-9daa-40b2-8b83-870eb2f24d56 nvidia-drm.modeset=1 i915.enable_dpcd_backlight=1
```
loader.conf
```
default arch.conf
console-mode 1
editor yes
auto-firmware 1
auto-entries 1
```
Also tried to downgrade systemd to 245.5, ran `bootctl install` and `bootctl update` again, but didn't work, too.

**Comment by medhefgo** [comment]
Changing / to \ is done automatically as can be verified by editing the cmdline at boot time. Are there any error messages? What kernel version? What versions were last well known?

Things to try:
 - downgrade kernel
 - boot without intel-ucode
 - reset efi
 - boot with earlyprintk cmd option

**Comment by poettering** [comment]
What's the error you see?

Are kernel and initrd actually in the root of the ESP?

**Comment by bionade24** [comment]
It's cause by [intel-ucode firmware](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/34) and has nothing to do with systemd-boot. Closing it now.
