### ISSUE TITLE
Delayed hibernation fails with "There's already a shutdown or sleep operation in progress"

### ISSUE THREAD

**Issue by gamanakis** [systemd/systemd#1640]
Delayed hibernation on archlinux (i.e. suspend and then wakeup via rtc in order to hibernate) under gnome fails with

```
● suspend-to-hibernate.service - Delayed hibernation trigger
   Loaded: loaded (/etc/systemd/system/suspend-to-hibernate.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://bbs.archlinux.org/viewtopic.php?pid=1420279#p1420279
           https://wiki.archlinux.org/index.php/Power_management

Oct 21 18:53:18 scythe-thinkpad systemd[1]: Starting Delayed hibernation trigger...
Oct 21 18:53:18 scythe-thinkpad sh[1646]: alarm set for 1445446458
Oct 21 18:54:19 scythe-thinkpad systemd[1]: Started Delayed hibernation trigger.
Oct 21 18:54:19 scythe-thinkpad systemd[1]: suspend-to-hibernate.service: Unit not needed anymore. Stopping.
Oct 21 18:54:19 scythe-thinkpad systemd[1]: Stopping Delayed hibernation trigger...
Oct 21 18:54:19 scythe-thinkpad sh[1748]: hibernate triggered
Oct 21 18:54:19 scythe-thinkpad sh[1748]: Failed to hibernate system via logind: There's already a shutdown or sleep operation in progress
Oct 21 18:54:19 scythe-thinkpad systemd[1]: Stopped Delayed hibernation trigger.
```

Culprit after a git bisect seems to be commit 7f96539d45028650f2ba9452095473a9c455d84b
 systemctl: when a shutdown is scheduled, always go via logind

**Comment by poettering** [comment]
"delayed hibernation" is not a systemd feature. Please report this to the folks who wrote this.

Not saying there wasn't a bug logind here, but this looks like an issue in some package first, as unspecific as the report is. Feel free to reopen if there's actual indication on a specific bug in logind.

**Comment by nmaggioni** [comment]
A solution to this can be found here: https://bbs.archlinux.org/viewtopic.php?id=204346
Scripts placed in `/usr/lib/systemd/system-sleep` are still affected, though!
