### ISSUE TITLE
Add support to set io.cost.qos and io.cost.model

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#16403]
**Is your feature request related to a problem? Please describe.**
For features such as `IOWeight` the cost model needs to be set on the root node of the cgroup hierarchy. It would be good if systemd had an easy way to set this for a selection of devices.

As an initial implementation, one would not even need to be able to set the more specific attributes. Just being able to set `io.cost.qos` the enabled flag for a specific device (e.g. containing `/`) would be a good start.

**Describe the solution you'd like**

I suspect this would work with a new `IODeviceCost` key in `/etc/systemd/system.conf`.

**Describe alternatives you've considered**

One could also implicitly add entries to `io.cost.qos` if there is a unit that sets IODeviceWeight for example.

**Comment by anitazha** [comment]
Assigned this to myself for now but I'm onboarding a new hire and I'm planning to have them implement as part of their ramp up.

**Comment by benzea** [comment]
> Regarding alteratives -- @benzea have you considered setting the IO cost parameters through udev rules? 

I had not really considered that. At the time, it seemed logically to me for systemd to enable the feature (i.e. it is managing cgroupfs, so it might as well set this).

No strong opinion. I don't even expect that it is interesting for admins to tweak the option, i.e. we may be able to just enable it by default.

**Comment by Werkov** [comment]
The hwdb integration sounds interesting. IIUC hwdb files would contain the HW specific config values [1] and a generic udev rule would apply them (there's slight difference that those aren't applied directly to sysfs nodes but to the root of unified cgroup hierarchy).

It sounds appealing to me to expose just the simple on-off (more like off-user-auto) switch via systemd attributes and hide the complexities of attributes tuning into the hwdb. Here I'm assuming these attributes are really HW- and not workload specific hence don't need frequent admin tweaking.

WDYT @alexlzhu?

[1] modalias-specific

**Comment by cmurf** [comment]
I'm sorta expecting hwdb contains raw values (include a range, e.g. HDDs have different throughput depending on the location of the rw head), nothing workload specific. Anything workload specific would be dealt with by cgroup organization strategies. The hard work comes from the middle gray area processes, to what degree they need IO guarantees before it causes peripheral effects on other services in ways that aren't always obvious.

**Comment by benzea** [comment]
> Here I'm assuming these attributes are really HW- and not workload specific hence don't need frequent admin tweaking.

I can't find the mails about that right now. IIRC, it was basically the raw read/write values, to avoid filling the disk buffers with too many requests. And using distributed measurements is generally good enough.
