### ISSUE TITLE
Resolved: set up a complement default routing domain

### ISSUE THREAD

**Issue by DamienRobert** [systemd/systemd#16412]
When we configure a specific domain on an interface A

    Domains=~foo

Then `systemd-resolve` will only query the DNS servers from interface A for `.foo` domains.
If we want to also query other domains on interface A, we may set

    Domains=~foo ~.

But in this case the (generic) DNS lookups won't be done on other interfaces anymore.

I need a way to specify that `.foo` domains should be looked-up on A, while other domains should be looked-up on all interfaces in parallel, including A. Something like

    Domains=~foo ~~.

to specify that the `.` lookups are not exclusive to A?

**Comment by poettering** [comment]
This is a misunderstanding. Just don't add the `~.` in the first place.

systemd will route queries for all domains for which no interface has a Domains= set to all interfaces at once, i.e. you get the behaviour you are looking for anyway.

Domains= doesn't mean that *only* the listed domains go onto that interface. It just means that these domains *definitely* go there, but everything else could go there too if there's no better place.
