### ISSUE TITLE
[CI] [integration test suite] cannot do any dm-verity operations in test/TEST-XX, qemu blocks forever

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#16414]
Paging CI/integration suite experts @mrc0mmand @msekletar @evverx @keszybz
I've added a few verity-related features, but the only integration test I could add was a very simple dissect:

https://github.com/systemd/systemd/blob/master/test/TEST-50-DISSECT/test.sh
https://github.com/systemd/systemd/blob/master/test/units/testsuite-50.sh

Any operation that involve opening a verity device in the kernel hang forever in the test image under qemu. This is not even related to functionality added to systemd itself, even a simple ```veritysetup open``` just hangs.

I tried to tweak the image (even included ALL the kernel modules I have on my host os, just in case something was missing) and the qemu invocation to no avail.
There's nothing useful in the kernel log, and this is what the veritysetup verbose debug shows:

```
# cryptsetup 2.3.3 processing "veritysetup -v --debug open tmp.2jxQRL.raw img tmp.2jxQRL.fooverity 49241091586abe0277"
# Running command open.
# Allocating context for crypt device tmp.2jxQRL.fooverity.
# Trying to open and read device tmp.2jxQRL.fooverity with direct-io.
# Trying to open device tmp.2jxQRL.fooverity without direct-io.
# Initialising device-mapper backend library.
# Setting ciphertext data device to tmp.2jxQRL.raw.
# Trying to open and read device tmp.2jxQRL.raw with direct-io.
# Trying to open device tmp.2jxQRL.raw without direct-io.
# Trying to load VERITY crypt type from device tmp.2jxQRL.fooverity.
# Crypto backend (OpenSSL 1.1.1d  10 Sep 2019) initialized in cryptsetup library version 2.3.3.
# Detected kernel Linux 5.6.0-0.bpo.2-amd64 x86_64.
# Reading VERITY header of size 512 on device tmp.2jxQRL.fooverity, offset 0.
# Activating volume img by signed key.
# dm version   [ opencount flush ]   [16384] (*1)
# dm versions   [ opencount flush ]   [16384] (*1)
# Detected dm-ioctl version 4.42.0.
# Detected dm-verity version 1.6.0.
# Device-mapper backend running with UDEV support enabled.
# dm status img  [ opencount noflush ]   [16384] (*1)
# Trying to activate VERITY device img using hash sha256.
# Allocating a free loop device.
# Trying to open device /dev/loop4 without direct-io.
# Allocating a free loop device.
# Trying to open device /dev/loop5 without direct-io.
# Calculated device size is 8 sectors (RW), offset 0.
# DM-UUID is CRYPT-VERITY-3f04afbf324b4bebb60948a5edd42158-img
# Udev cookie 0xd4d1aba (semid 1) created
# Udev cookie 0xd4d1aba (semid 1) incremented to 1
# Udev cookie 0xd4d1aba (semid 1) incremented to 2
# Udev cookie 0xd4d1aba (semid 1) assigned to CREATE task(0) with flags DISABLE_LIBRARY_FALLBACK         (0x20)
# dm create img CRYPT-VERITY-3f04afbf324b4bebb60948a5edd42158-img [ opencount flush ]   [16384] (*1)
# dm reload img  [ opencount flush readonly securedata ]   [16384] (*1)
# dm resume img  [ opencount flush readonly securedata ]   [16384] (*1)
# img: Stacking NODE_ADD (254,1) 0:6 0660 [trust_udev]
# img: Stacking NODE_READ_AHEAD 256 (flags=1)
# Udev cookie 0xd4d1aba (semid 1) decremented to 1
# Udev cookie 0xd4d1aba (semid 1) waiting for zero
```

The image is built from my host machine, where everything works just fine. So I would have expected the exact same thing booted in qemu to also work. On other images, not created by this test suite, verity works just fine.

Does anybody have any clue what is going on?

As an added bonus, the interactive run in qemu is horrendously slow. The terminal freezes every few seconds for minutes at a time. It's barely usable. The qemu monitor shows kvm is enabled, and -cpu host is used as expected, and the amount of memory/cores do not make any difference. Cross-architecture emulated VMs are faster than this, on the same machine. Images not built by this CI system again have no problem whatsoever.

Any help would be greatly appreciated - I'd really like to add full coverage for these features.

It seems to me, given the image build is designed to mirror the host system, there's something going wrong or missing from the image. But can't really figure it out.

**Comment by mrc0mmand** [comment]
After a bit of playing around and googling the only thing you need is this patch:

```diff
diff --git a/test/TEST-50-DISSECT/test.sh b/test/TEST-50-DISSECT/test.sh
index cfe97aaa2d..8aef105c05 100755
--- a/test/TEST-50-DISSECT/test.sh
+++ b/test/TEST-50-DISSECT/test.sh
@@ -25,6 +25,7 @@ test_create_image() {
         instmods loop =block
         instmods squashfs =squashfs
         instmods dm_verity =md
+        install_dmevent
         generate_module_dependencies
         inst_binary mksquashfs
         inst_binary veritysetup
```

which installs the necessary `/usr/lib/udev/rules.d/95-dm-notify.rules` rule file. With this `veritysetup open` works as expected in the CI image:
```
# cryptsetup 2.3.0 processing "veritysetup -v --debug open tmp.qvOwSD.raw img tmp.qvOwSD.fooverity 04b0eed17ccbfcbb9c7b71397f4436f7c658166db7a3db71bcad0a40bd0cfb8"
# Running command open.
# Allocating context for crypt device tmp.qvOwSD.fooverity.
# Trying to open and read device tmp.qvOwSD.fooverity with direct-io.
# Trying to open device tmp.qvOwSD.fooverity without direct-io.
# Initialising device-mapper backend library.
# Setting ciphertext data device to tmp.qvOwSD.raw.
# Trying to open and read device tmp.qvOwSD.raw with direct-io.
# Trying to open device tmp.qvOwSD.raw without direct-io.
# Trying to load VERITY crypt type from device tmp.qvOwSD.fooverity.
# Crypto backend (OpenSSL 1.1.1g FIPS  21 Apr 2020) initialized in cryptsetup library version 2.3.0.
# Detected kernel Linux 5.6.13-200.fc31.x86_64 x86_64.
# Reading VERITY header of size 512 on device tmp.qvOwSD.fooverity, offset 0.
Invalid root hash string specified.
# Releasing crypt device tmp.qvOwSD.fooverity context.
# Releasing device-mapper backend.
# Closing read only fd for tmp.qvOwSD.fooverity.
Command failed with code -1 (wrong or missing parameters).
04b0eed17ccbfcbb9c7b71397f4436f7c658166db7a3db71bcad0a40bd0cfb8vOwSD.fooverity 60
# cryptsetup 2.3.0 processing "veritysetup -v --debug open tmp.qvOwSD.raw img tmp.qvOwSD.fooverity 604b0eed17ccbfcbb9c7b71397f4436f7c658166db7a3db71bcad0a40bd0cfb8"
# Running command open.
# Allocating context for crypt device tmp.qvOwSD.fooverity.
# Trying to open and read device tmp.qvOwSD.fooverity with direct-io.
# Trying to open device tmp.qvOwSD.fooverity without direct-io.
# Initialising device-mapper backend library.
# Setting ciphertext data device to tmp.qvOwSD.raw.
# Trying to open and read device tmp.qvOwSD.raw with direct-io.
# Trying to open device tmp.qvOwSD.raw without direct-io.
# Trying to load VERITY crypt type from device tmp.qvOwSD.fooverity.
# Crypto backend (OpenSSL 1.1.1g FIPS  21 Apr 2020) initialized in cryptsetup library version 2.3.0.
# Detected kernel Linux 5.6.13-200.fc31.x86_64 x86_64.
# Reading VERITY header of size 512 on device tmp.qvOwSD.fooverity, offset 0.
# Activating volume img by signed key.
# dm version   [ opencount flush ]   [16384] (*1)
# dm versions   [ opencount flush ]   [16384] (*1)
# Detected dm-ioctl version 4.42.0.
# Device-mapper backend running with UDEV support enabled.
# dm status img  [ opencount noflush ]   [16384] (*1)
# Trying to activate VERITY device img using hash sha256.
# Allocating a free loop device.
# Trying to open device /dev/loop0 without direct-io.
# Allocating a free loop device.
# Trying to open device /dev/loop1 without direct-io.
# Calculated device size is 8 sectors (RW), offset 0.
# dm target-version verity  [ opencount flush ]   [16384] (*1)
# dm versions   [ opencount flush ]   [16384] (*1)
# Detected dm-verity version 1.6.0.
# DM-UUID is CRYPT-VERITY-ee1ae2b7d55f419a80e8d14089e6654b-img
# Udev cookie 0xd4df136 (semid 0) created
# Udev cookie 0xd4df136 (semid 0) incremented to 1
# Udev cookie 0xd4df136 (semid 0) incremented to 2
# Udev cookie 0xd4df136 (semid 0) assigned to CREATE task(0) with flags DISABLE_LIBRARY_FALLBACK         (0x20)
# dm create img CRYPT-VERITY-ee1ae2b7d55f419a80e8d14089e6654b-img [ opencount flush ]   [16384] (*1)
# dm reload   (253:0) [ opencount flush readonly securedata ]   [16384] (*1)
# dm resume img  [ opencount flush readonly securedata ]   [16384] (*1)
# img: Stacking NODE_ADD (253,0) 0:6 0660 [trust_udev]
# img: Stacking NODE_READ_AHEAD 256 (flags=1)
# Udev cookie 0xd4df136 (semid 0) decremented to 1
# Udev cookie 0xd4df136 (semid 0) waiting for zero
# Udev cookie 0xd4df136 (semid 0) destroyed
# img: Skipping NODE_ADD (253,0) 0:6 0660 [trust_udev]
# img: Processing NODE_READ_AHEAD 256 (flags=1)
# img (253:0): read ahead is 256
# img: retaining kernel read ahead of 256 (requested 256)
# dm status img  [ opencount noflush ]   [16384] (*1)
# Verity volume img status is V.
# Releasing crypt device tmp.qvOwSD.fooverity context.
# Releasing device-mapper backend.
# Closed loop /dev/loop1 (tmp.qvOwSD.raw).
# Closing read only fd for tmp.qvOwSD.fooverity.
# Closed loop /dev/loop0 (tmp.qvOwSD.fooverity).
Command successful.
```

The credit goes to @xnox and his [bug](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1749432) which looked suspiciously similar.

**Comment by bluca** [comment]
Yay, it works! Thank you so much! I had _completely_ missed that. I'll work on adding more tests.

Any chance you'd also know why these images are extremely slow in qemu?

**Comment by mrc0mmand** [comment]
> Yay, it works! Thank you so much! I had _completely_ missed that. I'll work on adding more tests.
> 
> Any chance you'd also know why these images are extremely slow in qemu?

Hm, I haven't experienced any unusual slow downs so far, but I played around with `veritysetup open` only, which took around a second to complete. Also, the system as a whole was as responsive as the underlying machine. However, if you have any particular scenario where you keep experiencing such slow downs, I'll gladly take a look.

**Comment by bluca** [comment]
> > Yay, it works! Thank you so much! I had _completely_ missed that. I'll work on adding more tests.
> > Any chance you'd also know why these images are extremely slow in qemu?
> 
> Hm, I haven't experienced any unusual slow downs so far, but I played around with `veritysetup open` only, which took around a second to complete. Also, the system as a whole was as responsive as the underlying machine. However, if you have any particular scenario where you keep experiencing such slow downs, I'll gladly take a look.

In particular I experience constant console lock ups. The terminal becomes unresponsive for seconds or minutes at a time, on random intervals. Doesn't matter which operation it is doing, or if it's idle.
When the terminal is working, then commands don't take long.

The baseline is Debian 10 + kernel from buster-backports, so that's qemu 3.1 and kernel 5.6.

**Comment by xnox** [comment]
I don't know how veritysetup works, but does it require high-memory pressure to unlock? In a similar way to how default configuration of LUKS2 tries to use argon2i with high memory settings? Maybe for test-suite, it can be tweaked to use all the smaller things, to reduce performance impact during test?

**Comment by bluca** [comment]
> I don't know how veritysetup works, but does it require high-memory pressure to unlock? In a similar way to how default configuration of LUKS2 tries to use argon2i with high memory settings? Maybe for test-suite, it can be tweaked to use all the smaller things, to reduce performance impact during test?

This is not related to verity - even without any verity operations, I have the same amount of terminal lockups.

**Comment by mrc0mmand** [comment]
> > > Yay, it works! Thank you so much! I had _completely_ missed that. I'll work on adding more tests.
> > > Any chance you'd also know why these images are extremely slow in qemu?
> > 
> > 
> > Hm, I haven't experienced any unusual slow downs so far, but I played around with `veritysetup open` only, which took around a second to complete. Also, the system as a whole was as responsive as the underlying machine. However, if you have any particular scenario where you keep experiencing such slow downs, I'll gladly take a look.
> 
> In particular I experience constant console lock ups. The terminal becomes unresponsive for seconds or minutes at a time, on random intervals. Doesn't matter which operation it is doing, or if it's idle.
> When the terminal is working, then commands don't take long.
> 
> The baseline is Debian 10 + kernel from buster-backports, so that's qemu 3.1 and kernel 5.6.

That's weird. I spun up  a Debian 10 VM, installed kernel & QEMU from buster-backports, but the test VM still runs smoothly as expected (both QEMU and KVM). I'm not sure what's going on in here.

```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# uname -a
Linux debian10.localdomain 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux
# qemu-system-x86_64 --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u5)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
```

**Comment by bluca** [comment]
> > > > Yay, it works! Thank you so much! I had _completely_ missed that. I'll work on adding more tests.
> > > > Any chance you'd also know why these images are extremely slow in qemu?
> > > 
> > > 
> > > Hm, I haven't experienced any unusual slow downs so far, but I played around with `veritysetup open` only, which took around a second to complete. Also, the system as a whole was as responsive as the underlying machine. However, if you have any particular scenario where you keep experiencing such slow downs, I'll gladly take a look.
> > 
> > 
> > In particular I experience constant console lock ups. The terminal becomes unresponsive for seconds or minutes at a time, on random intervals. Doesn't matter which operation it is doing, or if it's idle.
> > When the terminal is working, then commands don't take long.
> > The baseline is Debian 10 + kernel from buster-backports, so that's qemu 3.1 and kernel 5.6.
> 
> That's weird. I spun up a Debian 10 VM, installed kernel & QEMU from buster-backports, but the test VM still runs smoothly as expected (both QEMU and KVM). I'm not sure what's going on in here.
> 
> ```
> # cat /etc/os-release 
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> # uname -a
> Linux debian10.localdomain 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux
> # qemu-system-x86_64 --version
> QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u5)
> Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
> ```

Thanks for testing - at this point I'll go on and blame it on gremlins infesting my laptop :-)
I can live with it, most of the times I can run interactively with the nspawn-based image which works just fine
