### ISSUE TITLE
systemd randomly shuts down service

### ISSUE THREAD

**Issue by alexradu04** [systemd/systemd#16410]
I am hosting a twitch chatbot (node js application) on a Ubuntu Server. I created a service file and made it run 24/7. 
```
[Unit]
Description=twitch bot xd
After=network.target

[Service]
WorkingDirectory=/root/tsubot/
Environment=NODE_PORT=3001
Type=simple
User=root
ExecStart=/usr/bin/node /root/tsubot/index.js
Restart=on-abnormal
RestartSec=3

[Install]
WantedBy=multi-user.target
```

It has been running for the past 3 days, but now all of a sudden, it died without throwing any error message.
```
● tsubot.service - twitch bot xd
   Loaded: loaded (/lib/systemd/system/tsubot.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2020-07-08 02:23:00 EDT; 13h ago
  Process: 2057 ExecStart=/usr/bin/node /root/tsubot/index.js (code=exited, status=0/SUCCESS)
 Main PID: 2057 (code=exited, status=0/SUCCESS)
```

**Comment by boucman** [comment]
your javascript terminated normally (exited with code 0). looking at your unit, systemd did not restart it because it only restarts on abnormal termination

the error is probably in your script. 
`journalctl -u tsubot` might have some usefull logs for you, but apart from that it's probably standard node.js debug...

**Comment by poettering** [comment]
This looks like a clean exit of your service (i.e. exit status 0), i.e. nothing systemd was responsible for. You script just decides to exit. To trick this down, please contact the author of that script.

Closing here, as this is apparently not a systemd issue.
