### ISSUE TITLE
Error in journalctl man page, example section

### ISSUE THREAD

**Issue by pghpete** [systemd/systemd#16425]
**systemd version the issue has been seen with**
> 245.6-2.fc32

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
 > Example section in the journalctl man page has a minor error, and suggests a chapter of a man page that doesn't exist.

man journalctl (example section) contains...
_(see systemd.journal-fields(**5**) for an explanation of those patterns)._

and instead should point to...
_(see systemd.journal-fields(**7**) for an explanation of those patterns)._
...as referenced in several other locations within the journalctl man page.  The proper man page is here... /usr/share/man/man7/systemd.journal-fields.7.gz

**Unexpected behaviour you saw**
 > man journalctl (example section) contains...
_(see systemd.journal-fields(**5**) for an explanation of those patterns)._

**Steps to reproduce the problem**
>man journalctl
(using vi)
<esc>
/see systemd.journal-fields(5)
This will bring you to the incorrect line that should properly point to systemd.journal-fields(7)

**Comment by keszybz** [comment]
Fixed in #16427.
