### ISSUE TITLE
BLS: extend the boot loader spesification to include a drop in drivers directory.

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#16433]
Presumably the BLS needs to be extended to include drivers prior to any efi loading driver work is done in sd-boot and related tools ( something like bootctl install being extended to create the driver directory and install efi driver to it etc. ) basically the systemd ecosystem itself.

The most logical and most self explanatory directory structure to me is.. 

The parent efi drivers directory 
$BOOT\drivers 
and since the EFI drivers come in two variants 
$BOOT\drivers\boot for the boot drivers 
and $BOOT\drivers\runtime for the runtime drivers.

But others might want to add $ARCH somehow in the mix and even keep just a single drivers directory.

Once this has been discussed/hashed out a pull request can be made against the BLS itself so thoughts comments flames etc.

**Comment by poettering** [comment]
I think adding something like this makes sense, but for sd-boot not for the spec. If other boot loaders access their stuff with their own file systems they shouldn't have to load file systems.


The feature request for sd-boot is already filed in #15617. Closing hence.
