### ISSUE TITLE
How can I checking the service status with my own script

### ISSUE THREAD

**Issue by vincup** [systemd/systemd#1643]
As we know, in old sysV, when we can write a script to check the status of service.
But in SystemD, in my mind, systemctl tool check the status of service by checking the status of the Main PID which systemD manages after the service started by systemd.

And in my application, the service process will restart with a fixed epoch, or I can manually restart it with some script like in sysV, so when the restart operation is done out of control of systemd, I cannot get the right status of my service.

Is their any way to : 
1. providing a script to systemd, so when run 'systemctl status myservice', systemd will return the out of the provided script;
2. or is their any mechanism that I can notify systemd that my main process id has changed since I configured the PIDFile in unit file.

Thanks!  Hope some one can help me figure it out.

**Comment by rumpelsepp** [comment]
First, this seems to be a support question. This is a bugtracker, please post on the mailing list for that stuff. :)

For your question; what about these `systemctl` commands?
- `is-active`: Check whether units are active
- `is-enabled`: Check whether unit files are enabled
- `is-failed`: Check whether units are failed

**Comment by poettering** [comment]
This is not a support forum. Please use the systemd ML for questions like yours.
