### ISSUE TITLE
Cleanup error message in CentOS package creates a false positive in an environment check

### ISSUE THREAD

**Issue by synergiator** [systemd/systemd#16442]
**systemd version the issue has been seen with**
> systemd-239-18

**Used distribution**
 > Centos 8.1

**Expected behaviour you didn't see**
 > No error message

**Unexpected behaviour you saw**
 > Warning message in this ```yum -y update``` output block:
```

Cleanup          : systemd-pam-239-18.el8_1.5.x86_64                  128/177 
Running scriptlet: systemd-239-18.el8_1.5.x86_64                      129/177 
Cleanup          : systemd-239-18.el8_1.5.x86_64                      129/177 
warning: file /var/log/README: remove failed: No such file or directory

```

**Steps to reproduce the problem**

* Install CentOS 8.1
* Run ```yum -y update```

See also this log: here you can see this message line.
https://repo1.dsop.io/dsop/anchore/engine/engine/-/commit/9f918327b22d7925b8658d26af2b385790fd7243

**Comment by keszybz** [comment]
This sounds like a packaging problem in CentOS. Nothing we can solve upstream. Please report in CentOS.
