### ISSUE TITLE
[RFE] Extend "inhibit" interface to optionally apply to privileged/system services too

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#16454]
**Is your feature request related to a problem? Please describe.**
On an unmanned system with multiple privileged applications performing operations like firmware upgrades for different components followed by reboots to apply them, we need a centralized way to inhibit shutdown/reboot so that concurrent updates of different components don't interrupt each other and brick the hardware.

**Describe the solution you'd like**
logind already offers an "Inhibit" interface ( https://www.freedesktop.org/wiki/Software/systemd/inhibit/ ) but it seems limited to stopping actions requested via the logind interface itself and only by unprivileged processes (eg: shutdown button on a GUI). It would be very useful if this was extended to (optionally) cover any request. Blocking privileged components would be the core feature request, and covering requests outwith logind (eg: activate reboot.target) a bonus.

At the moment it seems it doesn't:

```
root@localhost:~# systemd-run systemd-inhibit --what=shutdown --who=test --why=test --mode=block sleep 120
Running as unit: run-r31c12a3d309b476bb66e4132bcc7df54.service
root@localhost:~# systemd-inhibit --list --no-pager
WHO  UID USER PID COMM            WHAT     WHY  MODE 
test 0   root 375 systemd-inhibit shutdown test block

1 inhibitors listed.
root@localhost:~# systemd-run busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager PowerOff b false
Running as unit: run-r4bad103a670e4275857ccb735be9fcee.service
root@localhost:~# 
root@localhost:~# [  OK  ] Stopped /usr/bin/busctl call org.freedesktop.…n1 org.freedesktop.login1.Manager PowerOff b false.
         Stopping Session c1 of user root.
[  OK  ] Removed slice system-modprobe.slice.
[  OK  ] Stopped target Host and Network Name Lookups.
```

**Describe alternatives you've considered**
We have a custom synchronization mechanism, which can only be opt-in, so it is fragile. The risk of an interrupted FW update causing the hardware to require manual intervention to fix it is too high.

**References to similar issues/pull requests**
https://github.com/systemd/systemd/issues/949
https://github.com/systemd/systemd/pull/950
https://github.com/systemd/systemd/pull/951
https://github.com/systemd/systemd/issues/2680
https://github.com/systemd/systemd/issues/6644
https://github.com/systemd/systemd/pull/9356
https://github.com/systemd/systemd/pull/16215
https://github.com/systemd/systemd/pull/17110

**Comment by coling** [comment]
Just FYI a recent post on the mailing list titled "Shutdown order in systemd" indirectly asked about something where fuller inhibitor protection would be useful.

They ultimately found this project: https://github.com/ryran/reboot-guard which may be worth looking at (at least to see if all it's functionality could be baked into systemd directly).

**Comment by bluca** [comment]
> Just FYI a recent post on the mailing list titled "Shutdown order in systemd" indirectly asked about something where fuller inhibitor protection would be useful.
> 
> They ultimately found this project: https://github.com/ryran/reboot-guard which may be worth looking at (at least to see if all it's functionality could be baked into systemd directly).

Thanks, I'm aware of that project - it's a clever of units options, but to be honest it feels a bit hacky :-) Also, it stops manually activating units, but it doesn't do anything for the DBUS-driven API.
