### ISSUE TITLE
The variables defined in ~/.config/environment.d/somefile.conf are not available as expected

### ISSUE THREAD

**Issue by kwaun** [systemd/systemd#16469]
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Declare my environment variable.

**Unexpected behaviour you saw**
 > My environment variable has no content.

**Steps to reproduce the problem**
```
$ cat << EOF > ~/.config/environment.d/myvars.conf
TEST=MyTestingVariable
EOF
$
```
(reboot system and login)
```
$ echo $TEST

$ 
```
But this command shows the variable!
```
$ systemctl --user show-environment
[...]
SHELL=/bin/bash
TEST=MyTestingVariable
CSF_LANGUAGE=us
[...]
$ 
```
Not sure if this is a bug actually or maybe the expected behaviour.

**Comment by poettering** [comment]
environment.d is a thing that systemd processes and sets for its services. it has no effect on your shell. See the "Applicability" section of the environment.d man page.

Closing, since this is a misunderstanding.
