### ISSUE TITLE
nspawn: os-release stuff bugs

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#16484]
PR #15891 was merged a bit too quickly. os-release should be a read-only bind mount, but it's writable. To make a r/o bind mount each mount needs to be listed twice, once to create the bind mount, and once to make it read-only. Kernel API is like this.

That's the biggie, I added a few more minor notes to the original PR.

**Comment by bluca** [comment]
Sorry about that, I saw that the mounts were done with MS_RDONLY and I thought that was enough - I'll follow up with another PR with the fix for that and the other comments this morning

**Comment by bluca** [comment]
PR open, with a test case to cover this as well: https://github.com/systemd/systemd/pull/16485
