### ISSUE TITLE
CapabilityBoundingSet=~CAP_RAWIO simply don't work

### ISSUE THREAD

**Issue by thelounge-zz** [systemd/systemd#16489]
https://bugzilla.redhat.com/show_bug.cgi?id=1857783
systemd-243.8-1.fc31.x86_64

"cap_sys_rawio" is still part of CapabilityBoundingSet

[root@asterisk:~]$ systemd-analyze security iaxmodem.service | grep RAWIO
✗ CapabilityBoundingSet=~CAP_RAWIO  Service has raw I/O access  0.2

[root@asterisk:~]$ cat /etc/systemd/system/iaxmodem.service | grep CapabilityBoundingSet
CapabilityBoundingSet=~CAP_NET_ADMIN CAP_SYSLOG CAP_SYS_ADMIN CAP_SYS_BOOT CAP_SYS_MODULE CAP_SYS_PTRACE CAP_SYS_TIME CAP_RAWIO

[root@asterisk:~]$ systemctl show iaxmodem.service | grep CapabilityBoundingSet | grep -i raw
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_rawio cap_sys_chroot cap_sys_pacct cap_sys_nice cap_sys_resource cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_wake_alarm cap_block_suspend cap_audit_read

**Comment by anitazha** [comment]
Looks like a typo in analyze-security. It should say `CapabilityBoundingSet=~CAP_SYS_RAWIO`. I'll put up a PR shortly.

**Comment by thelounge-zz** [comment]
well, normally "systemctl daemon-reload" warns in case of whatever nonsense, not in that case :-)
