### ISSUE TITLE
systemd-logind fails to recover after running a large number of concurrent tasks

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#16487]
**systemd version the issue has been seen with**
> systemd 243 (v243-18.h35.eulerosv2r9)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

**Used distribution**
 > …

**Expected behaviour you didn't see**
>When running a large number (800 jobs per minute) of cron jobs, and restarting some services concurrently, after one or two hours, systemd-logind reports the following error, and cannot start.
>
> systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
>
>This error is normal, because at this time, dbus resource is always not available. However, After stopping these tasks, systemd-logind should be able to recover without reboot.

**Unexpected behaviour you saw**
 >systemd-logind fails to recover, and reports the following error:
>[root@localhost ~]# systemctl restart systemd-logind
>Failed to restart systemd-logind.service: Unit systemd-logind.service failed to load properly: Transport endpoint is not connected.

**Steps to reproduce the problem**
>Hard to reproduce. Run hundreds of cron jobs and keep restarting services, reload daemon at the same time for more than an hour, then Stop them. See if systemd-logind can be restarted.

**Comment by Geass-LL** [comment]
journalctl -u systemd-logind:


[root@localhost ~]# journalctl -u systemd-logind
-- Logs begin at Thu 2020-07-16 16:46:05 CST, end at Thu 2020-07-16 20:09:21 CST. --
Jul 16 17:01:11 localhost.localdomain systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Jul 16 17:01:37 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:02:24 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:02:48 localhost.localdomain systemd[1]: systemd-logind.service: State 'stop-sigterm' timed out. Killing.
Jul 16 17:02:48 localhost.localdomain systemd[1]: systemd-logind.service: Killing process 1472 (systemd-logind) with signal SIGKILL.
Jul 16 17:02:50 localhost.localdomain systemd[1]: systemd-logind.service: Main process exited, code=killed, status=9/KILL
Jul 16 17:02:50 localhost.localdomain systemd[1]: systemd-logind.service: Failed with result 'timeout'.
Jul 16 17:02:52 localhost.localdomain systemd[1]: systemd-logind.service: Failed to schedule restart job: Unit systemd-logind.service failed to load properly: Transport endpoint is not connected.
Jul 16 17:02:52 localhost.localdomain systemd[1]: systemd-logind.service: Failed with result 'timeout'.
Jul 16 17:03:18 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:04:08 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:05:05 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:05:55 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:06:42 localhost.localdomain systemd[1]: systemd-logind.service: Cannot watch bus name org.freedesktop.login1: Transport endpoint is not connected
Jul 16 17:08:01 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:02 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:03 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:08:04 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:09:01 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:09:01 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.
Jul 16 17:09:01 localhost.localdomain systemd[1]: systemd-logind.service: Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.

**Comment by Geass-LL** [comment]
This PR may help to fix the bug. Please take a look.
[https://github.com/systemd/systemd/pull/16488](https://github.com/systemd/systemd/pull/16488)

**Comment by poettering** [comment]
It appears dbus simply refuses connections. At that point there's nothing we can do, we need it for communication. Check what is up with dbus, and raise its connection/queue limits?

**Comment by Geass-LL** [comment]
Yes, dbus refuses the connections when concurrent tasks are running. After stopping these tasks, dbus recovered, and systemd-logind should be able to recover too without reboot. But it didn't. 
I found this may be related to the UNIT->load_state of systemd-logind, which is UNIT_ERROR at this point. When I restart systemd-logind, this UNIT_ERROR unit is got from manager and leads to the failure of starting.

**Comment by poettering** [comment]
so, i figure the issue is like this: as part of loading the unit, we will start watching the bus name, to figure out the current state of the unit. This fails in your case, and we consider the unit having failed to load. If the unit is in that state we'll not allow it to be started again. The fix is easy though: "systemctl daemon-reload" should fix things again, as we'll reload the unit then, and if dbus works then everything should be jolly again.

**Comment by poettering** [comment]
> Service 'systemd-logind.service' will be restarted to activate the service. The current service state is 15.

I presume that's a log message you added?

**Comment by poettering** [comment]
Anyway, can you check if "systemctl daemon-reload" suffices? Is this still reproducible?
