### ISSUE TITLE
systemd-hwdb missing entry for Weida Hi-Tech CoolTouch System Touchscreen ID 2575:c300

### ISSUE THREAD

**Issue by globeone** [systemd/systemd#16495]
**systemd version the issue has been seen with**
> systemd --version
systemd 245 (245.4-4ubuntu3.1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

Peformed a 
sudo systemd-hwdb update
to no avail

**Used distribution**
 > …Ubuntu 20.04 LTS

**Expected behaviour you didn't see**
 > … 
lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f2:b651 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 2575:c300 **Weida Hi-Tech CoolTouch System Touchscreen**
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 13d3:3533 IMC Networks Bluetooth Radio 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Unexpected behaviour you saw**
 > …
lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f2:b651 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 2575:c300  
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 13d3:3533 IMC Networks Bluetooth Radio 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Steps to reproduce the problem**
Open a terminal
Type the command sudo lsusb

**Extended output that may help with creating the entry**
sudo lsusb -v shows:
Bus 001 Device 004: ID 2575:c300  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x2575 
  idProduct          0xc300 
  bcdDevice           31.00
  iManufacturer           1 Weida Hi-Tech
  iProduct                2 CoolTouch® System
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          3 CoolTouch® System 10x
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              4 CoolTouch® USB Interface 2
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     735
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

**Screenshot with proof**
![2020-07-16_CoolTouchMissing](https://user-images.githubusercontent.com/10052587/87715685-0330fb00-c7ae-11ea-8e66-9006e4cc703b.png)

**Comment by globeone** [comment]
The machine is a Shuttle POS P511 All-In-One which has been certified to work with Linux. The touchscreen works out of the box with no issues, the touchscreen is already in the Linux kernel. It's just missing from the lsusb output so I can't tell easily if something ever goes wrong with it.

The manufacturer of the touchscreen is Weida Hightech of Taiwan.

Thanks for updating the entry in hwdb.bin

**Comment by poettering** [comment]
please submit the entry to the USB ID database here:

http://www.linux-usb.org/usb-ids.html

We regularly import our hwdb data from there.
