### ISSUE TITLE
systemd-timesyncd: poll interval should not increase during network failures

### ISSUE THREAD

**Issue by vinc17fr** [systemd/systemd#16492]
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > Debian/unstable

**Expected behaviour you didn't see**
 > Synchronized machine.

**Unexpected behaviour you saw**
 > I got a 5-second delta compared to several other machines (giving a consistent time). Even though the network connection was intermittently very slow, the synchronization seemed to have stopped entirely.

**Steps to reproduce the problem**
I'm not sure how to reproduce the above problem, but when I tried, I noticed something unexpected: the poll interval as shown by `timedatectl timesync-status` increased during a lack of Internet connection, so that temporary connection issues would make synchronization less likely to have a chance to work. Before giving the steps to reproduce the problem, I'm going to give output from various commands I ran after noticing the 5-second delta (in case there would be some additional useful information).
```
zira:~> timedatectl timesync-status
       Server: (null) (3.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 2
    Reference: 596DFB17
    Precision: 1us (-24)
Root distance: 40.580ms (max: 5s)
       Offset: -1.087495s
        Delay: 2.156880s
       Jitter: 2.300948s
 Packet count: 620

zira:~> timedatectl show-timesync
FallbackNTPServers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
ServerName=3.debian.pool.ntp.org
RootDistanceMaxUSec=5s
PollIntervalMinUSec=32s
PollIntervalMaxUSec=34min 8s
PollIntervalUSec=34min 8s
NTPMessage={ Leap=0, Version=4, Mode=4, Stratum=2, Precision=-24, RootDelay=30.776ms, RootDispersion=25.192ms, Reference=596DFB17, OriginateTimestamp=Mon 2020-07-06 20:06:14 CEST, ReceiveTimestamp=Mon 2020-07-06 20:06:14 CEST, TransmitTimestamp=Mon 2020-07-06 20:06:14 CEST, DestinationTimestamp=Mon 2020-07-06 20:06:16 CEST, Ignored=yes PacketCount=620, Jitter=2.300948s }
Frequency=32768000

zira:~> systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2020-07-04 00:39:52 CEST; 3 days ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 684 (systemd-timesyn)
     Status: "Idle."
      Tasks: 2 (limit: 19071)
     Memory: 2.8M
     CGroup: /system.slice/systemd-timesyncd.service
             └─684 /lib/systemd/systemd-timesyncd

Jul 05 23:40:38 zira systemd-timesyncd[684]: Timed out waiting for reply from 37.187.174.185:123 (1.debian.pool.ntp.org).
Jul 05 23:40:51 zira systemd-timesyncd[684]: Initial synchronization to time server 185.51.192.34:123 (2.debian.pool.ntp.org).
Jul 06 10:50:50 zira systemd-timesyncd[684]: Initial synchronization to time server 51.15.191.239:123 (0.debian.pool.ntp.org).
Jul 06 12:30:47 zira systemd-timesyncd[684]: Initial synchronization to time server 4.53.160.75:123 (0.debian.pool.ntp.org).
Jul 06 13:50:59 zira systemd-timesyncd[684]: Initial synchronization to time server 91.206.16.3:123 (0.debian.pool.ntp.org).
Jul 06 14:08:11 zira systemd-timesyncd[684]: Initial synchronization to time server 162.159.200.1:123 (0.debian.pool.ntp.org).
Jul 06 17:32:15 zira systemd-timesyncd[684]: Initial synchronization to time server 193.70.90.148:123 (0.debian.pool.ntp.org).
Jul 06 19:53:13 zira systemd-timesyncd[684]: Initial synchronization to time server 94.130.184.193:123 (0.debian.pool.ntp.org).
Jul 06 19:57:43 zira systemd-timesyncd[684]: Timed out waiting for reply from 94.130.184.193:123 (0.debian.pool.ntp.org).
Jul 06 19:57:44 zira systemd-timesyncd[684]: Initial synchronization to time server 91.207.136.55:123 (0.debian.pool.ntp.org).
```

Now, to reproduce the issue about the poll intervals:

1. Disconnect the machine (I plugged out the Ethernet cable).
2. Connect to a wifi hotspot of a phone while the mobile data are disabled.
3. Run `timedatectl timesync-status` periodically.

From what I could see, `timedatectl` switched to the fallback NTP servers (the same as above), and it tried the one after the other, apparently with cached IP addresses. For 2.debian.pool.ntp.org, I could see that it tried at least 3 IP addresses. After some time, it ended up with `(null) (3.debian.pool.ntp.org)`, as I saw above.

Here's what I got:
```
zira:~> timedatectl timesync-status
       Server: 62.210.244.146 (2.debian.pool.ntp.org)
Poll interval: 2min 8s (min: 32s; max 34min 8s)
[...]

zira:~> timedatectl timesync-status
       Server: (null) (3.debian.pool.ntp.org)
Poll interval: 4min 16s (min: 32s; max 34min 8s)
[...]

zira:~> timedatectl timesync-status
       Server: (null) (3.debian.pool.ntp.org)
Poll interval: 8min 32s (min: 32s; max 34min 8s)
[...]

Then I reenabled the mobile data on the phone, and after some time, I got:

zira:~> timedatectl timesync-status
       Server: 37.187.122.11 (0.debian.pool.ntp.org)
Poll interval: 17min 4s (min: 32s; max 34min 8s)
[...]
```

The fact that the poll interval increases even when there are connection issues makes synchronization less likely to have a chance to work. When I had the issue several days ago (see above), it was 34min 8s, i.e. the maximum in its default configuration. So I don't think that this is the expected behavior: the poll interval should remain low until the synchronization is effective. I suppose that a workaround would be to change the `PollIntervalMaxSec` value, but this would affect the normal usage.

I hope I guessed it right, as the lack of documentation and log messages in case of failures does not help.

**Comment by vinc17fr** [comment]
BTW, the bug I had reported in the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964444

**Comment by yuwata** [comment]
Note that the logic was once dropped by 665c6a9eab46b0b253af6566ca9fc70c866b3fcd and reverted by ab4df227d466e881e4279821b5fc1563f0e7e933.

**Comment by vinc17fr** [comment]
#16494 has no effect: I get
```
zira:~> timedatectl timesync-status
       Server: n/a (3.debian.pool.ntp.org)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
```
and have to wait for 34 minutes.

**Comment by vinc17fr** [comment]
If only the retry times have been changed, I don't think that this will fix the issue, which was: When the maximum was reached, it would not decrease to the minimum in case of network failure. This can be a problem for laptops in particular, as they may be connected for a long period (so that the maximum can be reached), but they may also have later intermittent connections (so that the maximum could prevent time synchronization).

**Comment by vinc17fr** [comment]
But this means that the machine can remain unsynchronized for half an hour (typically after a sleep/resume), possibly more, say if one connects for 5 minutes a few times per day.

**Comment by keszybz** [comment]
The maximum time is now 6 minutes. In the unlikely case that the machine is always conntected for exactly 359 s, it will indeed might not synchronize.

**Comment by vinc17fr** [comment]
That's better. But IMHO, it would make sense to trigger synchronization as soon as one connects to the network.

**Comment by keszybz** [comment]
> it would make sense to trigger synchronization as soon as one connects to the network.

That would be nice but it's a much more complicated issue. There is not single "connected to the network" state. Instead, for example timesyncd could integrate with networkd and watch for an event where networkd thinks it has achieved connectivity. That wouldn't be bad, but it's not trivial to implement.

**Comment by vinc17fr** [comment]
As a simple workaround, I have now written a script `/etc/network/if-up.d/timesyncd` to restart the systemd-timesyncd service when a connection is up:
```
#!/bin/sh

[ "$IFACE" != "lo" ] || exit 0
[ -d /run/systemd/system ] || exit 0
[ -x /lib/systemd/systemd-timesyncd ] || exit 0

cmd="systemctl try-restart systemd-timesyncd.service"
[ -x /usr/bin/logger ] && /usr/bin/logger -t "${0#/etc/network/}" "$cmd"
$cmd || true
```
I don't know whether there is any drawback, but this seems to be a working solution as this forces a synchronization.
