### ISSUE TITLE
NIC alternative names can block naming policy from being applied

### ISSUE THREAD

**Issue by bjencks** [systemd/systemd#16500]
**systemd version the issue has been seen with**
> v245

**Used distribution**
 > Fedora coreos

**Expected behaviour you didn't see**
 > I want to apply path naming to what's currently eno1.
 > I made /etc/systemd/network/foo.link matching the interface, with NamePolicy=path.
 > I expect to see the interface named `enp1s0f0` after boot.

**Unexpected behaviour you saw**
 > Initrd applies the default `onboard` naming policy, renaming it to `eno1`, then adds `enp1s0f0` as an alternative name.
 > Later, after switching to real root, it attempts to apply the new link settings, but can't rename `eno1` to `enp1s0f0` because the name is taken by its own alternative name.
 > `systemd-udevd[623]: eno1: Failed to rename network interface 3 from 'eno1' to 'enp1s0f0': File exists`

**Steps to reproduce the problem**
Create /etc/systemd/network/foo.link with appropriate Match section for eno1.
```
[Match]
Driver=i40e ixgbe

[Link]
NamePolicy=path
```

**Comment by yuwata** [comment]
Ouch! I will work on this.

**Comment by yuwata** [comment]
Fix is waiting in #16501.
