### ISSUE TITLE
Failed to exec "systemctl --host user@host:port status"

### ISSUE THREAD

**Issue by halexan** [systemd/systemd#16509]
**systemd version the issue has been seen with**
> 237 (on Ubuntu 18.04)

**Expected behaviour you didn't see**
 > I should see status on the remote host.

**Unexpected behaviour you saw**
 > I see an error: "ssh: Could not resolve hostname host:port: Name or service not known". But on ubuntu20.04 with systemd[245], this error does not exsit.

**Steps to reproduce the problem**
> Just exec "systemctl --host user@host:port status" on ubuntu 18.04 with systemd[237].

**Comment by boucman** [comment]
237 is too old for upstream...

can you reproduce with the newest version ?
if not, please open an Ubuntu bug, not upstream...
