### ISSUE TITLE
systemd fails to unplug USB devices when using SYSTEMD_USER_WANTS with udev

### ISSUE THREAD

**Issue by swestlake** [systemd/systemd#16510]
Linux system is Debian 10 64-bit
Systemd version is 245.6-1

The service is to be run when the user is already logged into his Desktop and he wishes to attach his phone usb plug.

When a desktop user plugs in their phone, udev/systemd dynamically generates a .device, and then my_scrcpy.service gets automatically loaded/executed. I mention ".device" because it appears systemd is not handling the dynamic generated .device unit correctly- the user unplugs the usb cord but systemd will still list it as plugged.
(
"#systemctl list-units --type=devic
sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d6-1\x2d6.4.device loaded active plugged SAMSUNG_Android "
)

Two configuration files are used for binding the unit service to the udev usb event.
/etc/udev/rules.d/99-my_scrcpy.rules
and
/etc/systemd/user/my_scrcpy.service

file: /etc/udev/rules.d/99-my_scrcpy.rules
`ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="4ee7", ENV{DEVTYPE}=="usb_device", TAG+="systemd", ENV{SYSTEMD_USER_WANTS}+="my_scrcpy.service"
`

file: /etc/systemd/user/my_scrcpy.service

> [Unit]
> Description=Start scrcpy when correct usb device is plugged
> 
> [Service]
> Type=simple
> ExecStart=/usr/local/bin/scrcpy
> TimeoutStartSec=15
> 
> [Install]
> WantedBy=default.target
> 
> 

and then as root user 
 `#udevadm control --reload-rules`

followed by (on the Desktop as normal user)
`$systemctl --user --daemon-reload`

The scrcpy binary executes when I plug in my phone but when I try to replug the usb cord, the unit fails to reload.

Workaround: "$ systemctl --user daemon-reload" always works but only for the next replug -- this is a awkward and of course not ideal but for some reason it works even though it solves the problem temporarily.

`journalctl --user -xe -u my_scrcpy.service` always shows succesfully completed whether I close the scrcpy-window or just unplug the phone's usb cable. Despite this, there are no new journal entries again unless I perform "systemctl --user daemon-reload" and then replug the phone again. This is odd since there is no editing of system units being performed anywhere.

some extra output if this may help,
```
journalctl --user -xe -u my_scrcpy.service
 -- Logs begin at Sat 2020-07-18 00:22:14 EDT, end at Sat 2020-07-18 00:49:51 EDT. --
 Jul 18 00:49:36 debian64bit.localdomain systemd[1960]: Starting Start scrcpy when correct usb device is plugged...
 -- Subject: A start job for unit UNIT has begun execution
 -- Defined-By: systemd
 -- Support: https://www.debian.org/support
 -- 
 -- A start job for unit UNIT has begun execution.
 -- 
 -- The job identifier is 220.
 Jul 18 00:49:39 debian64bit.localdomain systemd[1960]: Started Start scrcpy when correct usb device is plugged.
 -- Subject: A start job for unit UNIT has finished successfully
 -- Defined-By: systemd
 -- Support: https://www.debian.org/support
 -- 
 -- A start job for unit UNIT has finished successfully.
 -- 
 -- The job identifier is 220.
 Jul 18 00:49:39 debian64bit.localdomain scrcpy[67925]: INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
 Jul 18 00:49:39 debian64bit.localdomain scrcpy[67929]: * daemon not running; starting now at tcp:5037
 Jul 18 00:49:42 debian64bit.localdomain scrcpy[67929]: * daemon started successfully
 Jul 18 00:49:42 debian64bit.localdomain scrcpy[67929]: [100%] /data/local/tmp/scrcpy-server.jar
 Jul 18 00:49:42 debian64bit.localdomain scrcpy[67929]: /usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 3.9 MB/s (33142 bytes in 0.008s)
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67951]: [server] INFO: Device: samsung SM-A520W (Android 9)
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: OpenGL shaders: ENABLED
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: Created renderer: opengl
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: Renderer: opengl
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: OpenGL version: 3.0 Mesa 18.3.6
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: Trilinear filtering enabled
 Jul 18 00:49:43 debian64bit.localdomain scrcpy[67925]: INFO: Initial texture: 1080x1920
 Jul 18 00:49:48 debian64bit.localdomain systemd[1960]: my_scrcpy.service: Succeeded.
 -- Subject: Unit succeeded
 -- Defined-By: systemd
 -- Support: https://www.debian.org/support
 -- 
 -- The unit UNIT has successfully entered the 'dead' state.
```

the following shows systemd is able to print out a .device entry even though the plug is disconnected from the phone device -- hopefully I am interpreting this information correctly. I believe there is a bug with this output so I am adding this over here. If I am wrong please correct me, and I will see about adding something with ACTION=="remove", but from what I read I don't think SYSTEMD_USER_WANTS does support deactivation (and only activation). If I don't need an action-remove rule, then I suppose there must be a bug occurring with systemd's handling of dynamically generating the usb device unit.

I don't think the following should show when I have the phone disconnected, 
```
#systemctl list-units --type=device
sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d6-1\x2d6.4.device loaded active plugged SAMSUNG_Android
```

maybe this is a separate bug, but I think it is connected to faulty behaviour with SYSTEMD_USER_WANTS so that is why I have added it.

please take a look
thanks

**Comment by poettering** [comment]
Is the udev/sysfs device still around when this happens?

i.e. does `/sys/devices/pci0000:00-0000:00:14.0-usb1-1:6-1:6.4` exist, i.e. the sysfs path matching the .device unit?

**Comment by poettering** [comment]
Closing due to lack of response.
