### ISSUE TITLE
systemctl try-xyz should suppress error messages about masked units

### ISSUE THREAD

**Issue by thelounge-zz** [systemd/systemd#16521]
> Failed to try-restart clamav-freshclam.service: Unit clamav-freshclam.service is masked.: 1 Times(s)
    > Failed to try-restart clamd@scan.service: Unit clamd@scan.service is masked.: 1 Times(s)

these warnings appearing also in logwatch make no sense
the whole point of try-restart/condrestart is "restart if it is running"
if it is masked it is not running so dear systemctl shut up :-)

on highly customized systems and by the fact that a lot of stuff is started compüared to 5 years ago more and more needs to be masked and more and more has condrestarts here and there

**Comment by poettering** [comment]
Hmm, you are probably right, we should suppress the error message in the try-xyz cases

**Comment by thelounge-zz** [comment]
and the non-zero exit code is a problem at it's own

Aug  3 00:35:34 testserver logrotate[141596]: Failed to try-restart clamav-freshclam.service: Unit clamav-freshclam.service is masked.
Aug  3 00:35:34 testserver systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Aug  3 00:35:34 testserver systemd[1]: logrotate.service: Failed with result 'exit-code'.
Aug  3 00:35:34 testserver systemd[1]: Failed to start Rotate log files.
Aug  3 00:35:34 testserver logrotate[141596]: error: error running non-shared postrotate script for /var/log/freshclam.log of '/var/log/freshclam.log '
