### ISSUE TITLE
tmpfiles.d(5) file subvolume semantics should work under ZFS

### ISSUE THREAD

**Issue by strugee** [systemd/systemd#16553]
**Is your feature request related to a problem? Please describe.**

Not really a specific problem, just fleshing out a feature.

**Describe the solution you'd like**

`tmpfiles.d` configuration files should understand when the system is on a ZFS filesystem, and take the appropriate action when types like `v`, `q` and `Q` are specified. Specifically, ZFS datasets can be created and configured instead of subvolumes.

**Describe alternatives you've considered**

Do nothing and WONTFIX this because ZFS is an out-of-tree DKMS module everywhere except Ubuntu so you're more on your own. This seems perfectly reasonable to me; I have no pressing need for this feature and am filing this mostly because I think it just makes sense as an integration point.

I don't really know the btrfs quota system _or_ the ZFS quota system, as I have no use for either. So I don't really know how much they differ, or if they differ too much to make the semantics here reasonable. If the latter ends up being true, however, that might be another compelling reason to drop this proposal.

Or, if they're too different, we could also add ZFS variants for these (`vz`, `qz` and `Qz` maybe - the implication that they're like the originals, but for ZFS?) to make it easier to document the differences, since the relevant types wouldn't be littered with hard-to-parse "Under btrfs it does xyz, but under ZFS it does abc instead" type sentences. This feels ugly though because what if you're a vendor writing a file for `/usr/lib/tmpfiles.d`, you understand that there's a difference depending on the root fs, and you're fine with either? So I don't really like this idea.

**Comment by poettering** [comment]
We are not too keen to support subsystems like zfs that are license-wise controversial and have no prospect of being merged upstream because of that any time soon.

Please work with zfs upstreams to resolve the license mess, and we certainly can support it as nicely as we support btrfs right now, but until then I don't thin we should add code to systemd. 

Sorry.

**Comment by DemiMarie** [comment]
@poettering The license mess isn’t the fault of OpenZFS, but of Oracle, and even they might be bound by various legal agreements of their own.  So working with OpenZFS won’t really help.  Furthermore, OpenZFS is *heavily* used in production.

Would you accept a patch if one was submitted?

**Comment by poettering** [comment]
@DemiMarie here's my suggestion: can't OpenZFS implement the same ioctls as btrfs? I mean, that happens all the time, for example the file clone ioctls that btrfs came up with are nowadays implemented by xfs and other file systems too. And the other way round too.

if openzfs would implement a relevant subset of the btrfs ioctls then things might just magically start working without any explicit support for zfs on our side. And things would not just work with systemd but other projects using these ioctls too.

(so, strictly speaking we'd have to lose systemd a bit for that, for a number of things we actually do verify the statfs magic to be btrfs before we do certain things)

**Comment by poettering** [comment]
Let's close this here, I am really sure this should be considered a zfs issue, if they implement the btrfs ioctl then things should pretty much just work, with systemd and other tools too.
