### ISSUE TITLE
Clarify whether enhancement requests should be filed on GitHub given systemd version <= $CURRENT - 2

### ISSUE THREAD

**Issue by strugee** [systemd/systemd#16550]
[CONTRIBUTING.md](https://github.com/systemd/systemd/blob/82ff544160aa2aa04cdd5c3f158135f7d61b8542/docs/CONTRIBUTING.md) specifies pretty clearly that systemd bugs belong in distribution bug trackers if the user is not on one of the two most recently released upstream systemd versions. Also, the issue template for bugs contains a comment stating the same.

However, CONTRIBUTING.md doesn't really address whether enhancement requests are allowed to be filed on GitHub if the systemd version is too old. This seems reasonable to allow as long as the submitter checks for open and closed duplicate issues, since I'm guessing most enhancements will have gotten an issue at some point? If not you could tell submitters to check open and closed PRs, too.

**Comment by strugee** [comment]
If it'll save y'all some time I'd be happy to prepare a patch if someone comments here and clarifies the policy.

**Comment by keszybz** [comment]
Yeah, this also applies to RFEs. The general idea is that we don't want to deal with the old versions upstream.  The reporter would have to verify that the code hasn't changed, which is not always trivial, and in general it's easier to ask people to just check with one of the latest versions.

> I'm guessing most enhancements will have gotten an issue at some point? 

Not really. Issues are used for communication with users and other developers, and plenty of features are implemented without any prior discussion. 

It'd be great if you can prepare a patch that'd just say that the limits apply to both types of issues.

**Comment by strugee** [comment]
Ack, sorry this dropped off my radar :(

Glad it got fixed.
