### ISSUE TITLE
How to add .mount units for ordering

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#16554]
Hello,

I experimented with some services that eg. copy over content of `/var` to a new tmpfs and then bind/move this back to `/var`.
What I would need is a way to order other mounts like `/var/tmp` automatically after this service.
What I did so far is using an "order-only" mount unit, given that there are mandatory options I did my best to create a "no-op".

So the (re-)quest would be about the optimal solution, and whether you might consider some clean official way to do such a thing, like a special flag or `Type=service-dependency` setting that skips the mount call and maybe logs an error if there is not a `BindsTo` dependency.

The service that actually does the work is ordered `After=local-fs-pre.target`, as stuff like fsck should happen before. So for this and other reasons its not an option to use `Before=local-fs-pre.target`.

```ini
[Unit]
Description=variable storage (/var)
Documentation=man:file-hierarchy(7)
ConditionPathIsSymbolicLink=!/var
ConditionPathIsReadWrite=!/var
After=rootfs-copymount-var.service
BindsTo=rootfs-copymount-var.service

[Mount]
What=dummy
Where=/var
Options=remount
```

**Comment by poettering** [comment]
can't you just use systemd.volatile=yes on the kernel cmdline?

**Comment by poettering** [comment]
But in general, this is a bug and feature request tracker, not a support forum. THe submission form should have made that very clear, to keep frustration at a minimum. For support questions/howtos please contact the systemd ml instead.
