### ISSUE TITLE
Mount/Device dependencies sometimes not updated

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#1656]
Situation:
- I have a fstab entry mounting `/dev/disk/by-uuid/QWERTY` on `/mnt/backup`. The device resolves to `/dev/sdb1` and is currently mounted.
- Due to a flaky USB port, the disk previously at `/dev/sdb` gets disconnected and almost immediately reconnected. The kernel assigns it `/dev/sdc` for some reason (maybe because it hasn't finished cleaning up /dev/sdb yet?)
- The device `/dev/disk/by-uuid/QWERTY` now resolves to `/dev/sdc1` – both according to filesystem and even `systemctl show /dev/disk/by-uuid/QWERTY` (which shows "active (plugged), tracking /sys/…/sdc/sdc1").
- However, I _still can't_ mount it on `/mnt/backup` because systemd still secretly thinks that `mnt-backup.mount` depends on `dev-sdb1.device` (confirmed by `systemctl list-dependencies`), resulting in "Unit is bound to inactive unit dev-sdb1.device. Stopping, too." messages.

Running a `systemctl daemon-reload` helps, but I would think that's something that should be updated automatically?

systemd 227.r252.gd3aacce

**Comment by intelfx** [comment]
Confirming on v228, affected too.

**Comment by keszybz** [comment]
Probably related to #1741.

**Comment by poettering** [comment]
This should be fixed since eef85c4a3f8054d29383a176f6cebd1ef3a15b9a and related commits, i.e. v236. Closing.
