### ISSUE TITLE
 No space left on device ext4 machines.raw after resize and set-limit

### ISSUE THREAD

**Issue by oxwivi** [systemd/systemd#16565]
**systemd version the issue has been seen with**
 > ```
 > $ systemctl --version 
 > systemd 245 (245.4-4ubuntu3.1)
 > +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
 > ```

**Used distribution**
 > KDE neon/Ubuntu 20.04

**Expected behaviour you didn't see**
 > Successful execution of `machinectl import-raw`.

**Unexpected behaviour you saw**
 > ```
 > $ sudo machinectl import-raw ~/Downloads/ERPNext-Production/ERPNext-Production-20200707063143.raw
 > Enqueued transfer job 1. Press C-c to continue download in background.
 > Importing '/home/virtoki/Downloads/ERPNext-Production/ERPNext-Production-20200707063143.raw', saving as 'ERPNext-Production-20200707063143'.
 > Imported 0%.
 > Failed to decode and write: No space left on device
 > Exiting.
 > ```
**Steps to reproduce the problem**
 - import anything over the default `machine.raw` limit
 
**Workarounds from online that has been tried**
```
$ sudo umount /var/lib/machines ; sudo qemu-img resize -f raw /var/lib/machines.raw +100G ; sudo systemctl restart /var/lib/machines
Image resized.
$ sudo qemu-img info /var/lib/machines.raw
image: /var/lib/machines.raw
file format: raw
virtual size: 116 GiB (125078339584 bytes)
disk size: 484 MiB
$ qemu-img info /home/virtoki/Downloads/ERPNext-Production/ERPNext-Production-20200707063143.raw
image: /home/virtoki/Downloads/ERPNext-Production/ERPNext-Production-20200707063143.raw
file format: raw
virtual size: 39.1 GiB (41943040000 bytes)
disk size: 5.2 GiB
```
Exact same output as noted under _unexpected behaviour_ after verifying `machines.raw` has been resized and `ERPNext-Production-20200707063143.raw` is within in the limits.
```
$ sudo machinectl set-limit 100G
```
Same output again as noted above.

**Comment by poettering** [comment]
machines.raw support has long been dropped. Let's close this here, as this is not going to come back.
