### ISSUE TITLE
Systemd-login issue: boot hanging with blinking underscore until I switch to another tty and switch back

### ISSUE THREAD

**Issue by Dmarc** [systemd/systemd#16577]
**systemd version the issue has been seen with**
> 245.6-8 (but it may happened with previous versions as well, I did not reboot for nearly two months)

**Used distribution**
 > Arch linux with kernel 5.7.10 and gnome shell 3.36

**Expected behaviour you didn't see**
 > It should boot on gdm login interface

**Unexpected behaviour you saw**
 > systemd starts then it stucks on a black screen with a blinking underscore. I waited for 10 minutes but still hanging. I found a workaround: I switch to another tty (alt+F2),  **without loging**,  and then switch back to the initial one (alt+F1), and the booting process then keeps going, and gdm login interface appears as normal.
In the log file I found this suspect warning:
gnome-session-binary[444]: Unrecoverable failure in required component org.gnome.Shell.desktop

**Steps to reproduce the problem**
Just boot with the same configuration I guess...

**Comment by poettering** [comment]
This doesn't really sound like a systemd bug but one in gdm or so. Can you report this to your downstream distro first? If they find this to actually be systemd faults, they'll escalate it back to us, but given the error you indicated this doesn't appear to be systemd's issue...
