### ISSUE TITLE
False statement in documentation that  GPT is mandatory on EFI systems

### ISSUE THREAD

**Issue by DavidWHodgins** [systemd/systemd#16570]
I noticed that https://systemd.io/DISCOVERABLE_PARTITIONS/ has the statement
"The GUID Partition Table (GPT) is mandatory on EFI systems."
The statement is false. My EFI system works using MBR partitioned disk drives. Some faulty EFI
firmware may only be able to boot from GPT partitioned drives, but that is the fault of the firmware
developers, not the EFI specification.

Compliant EFI systems can use either MBR or GPT partitioned hard drives.

That sentence should be deleted from the documentation, or reworded to indicate that use of GPT
partition tables is optional, and that if used allows the use of discoverable partitions.

**Comment by mPiotrek** [comment]
Oh, someone reported this before me : )

The sentence could just state that the GPT support is mandatory – since the whole point of this specification is to include additional information when **possible**.
