### ISSUE TITLE
after "systemctl daemon-reload" most service infos are lost

### ISSUE THREAD

**Issue by thelounge-zz** [systemd/systemd#16572]
it's not nice to lose all state informations just because you edited a unit and the same applies also without edit and only daemon-reload......

systemd-243.8-1.fc31.x86_64
---------------------------------------------------

[root@srv-rhsoft:~]$ systemctl status network-up.service
● network-up.service - Network
   Loaded: loaded (/etc/systemd/system/network-up.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2020-07-23 23:47:40 CEST; 1h 11min ago
  Process: 1045 ExecStart=/usr/sbin/ipset -file /etc/sysconfig/ipset restore (code=exited, status=0/SUCCESS)
  Process: 1097 ExecStart=/usr/sbin/iptables-nft-restore /etc/sysconfig/iptables (code=exited, status=0/SUCCESS)
  Process: 1169 ExecStart=/usr/sbin/ip link add name br-wan type bridge (code=exited, status=0/SUCCESS)
  Process: 1171 ExecStart=/usr/sbin/ip link set dev wan master br-wan multicast off allmulticast off up (code=exited, status=0/SUCCESS)
  Process: 1190 ExecStart=/usr/sbin/ip link set dev vmnet1 master br-wan multicast off allmulticast off up (code=exited, status=0/SUCCESS)
  Process: 1191 ExecStart=/usr/sbin/ip addr flush vmnet1 (code=exited, status=0/SUCCESS)
  Process: 1192 ExecStart=/usr/bin/systemctl start vpn.service (code=exited, status=0/SUCCESS)
  Process: 1220 ExecStart=/usr/sbin/ip link add name br-lan type bridge (code=exited, status=0/SUCCESS)
  Process: 1221 ExecStart=/usr/sbin/ip link set dev br-lan up (code=exited, status=0/SUCCESS)
  Process: 1223 ExecStart=/usr/sbin/ip a add 192.168.2.2/255.255.255.0 broadcast 192.168.2.255 dev br-lan (code=exited, status=0/SUCCESS)
  Process: 1225 ExecStart=/usr/sbin/ip link set dev lan-spare1 master br-lan up (code=exited, status=0/SUCCESS)
  Process: 1228 ExecStart=/usr/sbin/ip link set dev lan-spare2 master br-lan up (code=exited, status=0/SUCCESS)
  Process: 1229 ExecStart=/usr/sbin/ip link set dev lan-tv master br-lan up (code=exited, status=0/SUCCESS)
  Process: 1231 ExecStart=/usr/sbin/ip link set dev poe-spare master br-lan up (code=exited, status=0/SUCCESS)
  Process: 1233 ExecStart=/usr/sbin/ip link set dev poe-phone master br-lan multicast off allmulticast off up (code=exited, status=0/SUCCESS)
  Process: 1235 ExecStart=/usr/sbin/ip link add name br-guest type bridge (code=exited, status=0/SUCCESS)
  Process: 1236 ExecStart=/usr/sbin/ip link set dev br-guest multicast off allmulticast off up (code=exited, status=0/SUCCESS)
  Process: 1238 ExecStart=/usr/sbin/ip a add 192.168.10.1/255.255.255.0 broadcast 192.168.10.255 dev br-guest (code=exited, status=0/SUCCESS)
  Process: 1239 ExecStart=/usr/sbin/ip link set dev lan-guest master br-guest multicast off allmulticast off up (code=exited, status=0/SUCCESS)
  Process: 1240 ExecStart=/usr/sbin/ip route add 172.17.0.0/24 via 192.168.196.5 dev vmnet8 (code=exited, status=0/SUCCESS)
  Process: 1241 ExecStart=/usr/bin/systemctl start network-wan-dhcp.service (code=exited, status=0/SUCCESS)
  Process: 1280 ExecStart=/usr/sbin/sysctl -q --load=/etc/sysctl*.conf (code=exited, status=0/SUCCESS)
  Process: 1281 ExecStart=/usr/sbin/tc qdisc add dev wan root handle 1 hfsc default 1 (code=exited, status=0/SUCCESS)
  Process: 1284 ExecStart=/usr/sbin/tc class add dev wan parent 1: classid 1:1 hfsc sc rate 54Mbit ul rate 54Mbit (code=exited, status=0/SUCCESS)
  Process: 1285 ExecStart=/usr/sbin/tc qdisc add dev wan parent 1:1 handle 11: fq_codel (code=exited, status=0/SUCCESS)
 Main PID: 1285 (code=exited, status=0/SUCCESS)
      CPU: 755ms

Jul 23 23:47:31 srv-rhsoft.rhsoft.net systemd[1]: Starting Network...
Jul 23 23:47:40 srv-rhsoft.rhsoft.net systemd[1]: Started Network.
Warning: The unit file, source configuration file or drop-ins of network-up.service changed on disk. Run 'systemctl daemon-reload' to reload units.

---------------------------------------------------

[root@srv-rhsoft:~]$ systemctl daemon-reload

---------------------------------------------------

[root@srv-rhsoft:~]$ systemctl status network-up.service
● network-up.service - Network
   Loaded: loaded (/etc/systemd/system/network-up.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2020-07-23 23:47:40 CEST; 1h 11min ago
 Main PID: 1285 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 512)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/network-up.service

Jul 23 23:47:31 srv-rhsoft.rhsoft.net systemd[1]: Starting Network...
Jul 23 23:47:40 srv-rhsoft.rhsoft.net systemd[1]: Started Network.

---------------------------------------------------

**Comment by poettering** [comment]
I am pretty sure this has been fixed in 244 or 245. Please upgrade or report back if this is reproducible even in 245.

**Comment by poettering** [comment]
(i.e. it's this commit I figure: 334c0979f37adab7cf6df01cff1ee818bf72d7b2)
