### ISSUE TITLE
possible systemd.volatile=overlay causing initrd-switch-root to fail

### ISSUE THREAD

**Issue by skinkie** [systemd/systemd#16580]
**systemd version the issue has been seen with**
> 245.6-8-arch

**Used distribution**
 > ArchLinux ARM (RPi4) 

**Expected behaviour you didn't see**
 > I am trying to integrate the systemd.volalite=overlay feature inside an image, to prevent writes to a microSD card without too much integration. I have noticed that having this option enabled a significant number of boots fail on initrd-switch-root, including the warning that the root account is locked. Removing the option seem to consistently boot the system. When the system would boot (after the Enter key, it tries again a few tems) I did not see a volatile filesystem. For example changes to /boot are applied. In one test I actually did see volatile behavior: a touched file was not preserved during reboot.

**Unexpected behaviour you saw**
 > The system would most of the time (80%) hang at initrd-switch-root.

![photo5825764529185863160](https://user-images.githubusercontent.com/502394/88441078-3f98d280-ce10-11ea-8518-aff306eefec6.jpg)

**Steps to reproduce the problem**
My system uses F2FS as root filesystem and vfat as /boot. A stock ArchLinux Arm image should be extended with f2fs-tools and dosfstools. Within mkinitcpio.conf change on the HOOKS line the hook "udev" for "systemd" as documented on the ArchLinux wiki. Update the image with mkinitcpio. Update /boot/cmdline.txt with the systemd.volalite=overlay option. In addition reading some advices the paths to the partition for root have already been update to the /dev/disk/by-id/... opposed to /dev/mmcblk0p2.

In addition I have noticed that the regular boot time with File System Check is about 30s for the partition (30GB).

```
-- The job identifier is 36.
Jun 24 14:37:43 archlinux systemd[1]: Starting Switch Root...
-- Subject: A start job for unit initrd-switch-root.service has begun execution
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit initrd-switch-root.service has begun execution.
-- 
-- The job identifier is 37.
Jun 24 14:37:44 archlinux systemctl[178]: Failed to switch root: Failed to determine whether root path '/sysroot' contains an OS tree: No such file or directory
Jun 24 14:37:44 archlinux systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStart= process belonging to unit initrd-switch-root.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Jun 24 14:37:44 archlinux systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit initrd-switch-root.service has entered the 'failed' state with result 'exit-code'.
Jun 24 14:37:44 archlinux systemd[1]: Failed to start Switch Root.
-- Subject: A start job for unit initrd-switch-root.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit initrd-switch-root.service has finished with a failure.
-- 
-- The job identifier is 37 and the job result is failed.
Jun 24 14:37:44 archlinux systemd[1]: Startup finished in 6.969s (kernel) + 0 (initrd) + 1.081s (userspace) = 8.050s.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- All system services necessary queued for starting at boot have been
-- started. Note that this does not mean that the machine is now idle as services
-- might still be busy with completing start-up.
-- 
-- Kernel start-up required 6969039 microseconds.
-- 
-- Initial RAM disk start-up required 0 microseconds.
-- 
-- Userspace start-up required 1081068 microseconds.
Jun 24 14:37:44 archlinux systemd[1]: initrd-switch-root.service: Triggering OnFailure= dependencies.
Jun 24 14:37:44 archlinux systemd[1]: Started Emergency Shell.
-- Subject: A start job for unit emergency.service has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit emergency.service has finished successfully.
-- 
-- The job identifier is 68.
Jun 24 14:37:44 archlinux systemd[1]: Reached target Emergency Mode.
-- Subject: A start job for unit emergency.target has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit emergency.target has finished successfully.
-- 
-- The job identifier is 67.
Jun 24 14:37:44 archlinux systemd[180]: emergency.service: Executable /bin/plymouth missing, skipping: No such file or directory
-- Subject: Process /bin/plymouth could not be executed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /bin/plymouth could not be executed and failed.
-- 
-- The error number returned by this process is ERRNO.
```

**Comment by poettering** [comment]
please boot with debug logging on and provide logs from such a failed boot then (without -x)

https://freedesktop.org/wiki/Software/systemd/Debugging/

**Comment by skinkie** [comment]
Thanks for your personal reply @poettering  If the visuals are not sufficient I'll attempt a console cable over GPIO approach. I do not see these logs in journalctl.

![photo5841305219806377129](https://user-images.githubusercontent.com/502394/88819194-f5bd3d00-d1bf-11ea-9eb2-59a28de0ea90.jpg)

![photo5841305219806377130](https://user-images.githubusercontent.com/502394/88819211-fa81f100-d1bf-11ea-8c72-a7f9290d8065.jpg)

![photo5841305219806377127](https://user-images.githubusercontent.com/502394/88819217-fe157800-d1bf-11ea-9684-56346e84e532.jpg)

**Comment by poettering** [comment]
no these screenshots do not suffice. we need the logs immediately before what you can see on them...

**Comment by skinkie** [comment]
@poettering it took some more effort to convince to get the debug output to the serial port. Otherwise it would only end up on the framebuffer (tty1) device, and not on the serial port. Attached is the serial debugging log.
[capturefile.txt.gz](https://github.com/systemd/systemd/files/4997282/capturefile.txt.gz)

**Comment by poettering** [comment]
First of all, systemd can only be installed in /usr/, and /, i.e. not in /usr/local. it's simply not supported to use a different prefix. systemd is not an app you install, but the heart of the OS userspace, it has some special requirements there.

**Comment by poettering** [comment]
so systemd-volatile-root isn't available at all on your system:

```
systemd-volatile-root.service: Failed to load configuration: No such file or directory
```

Your initrd has no os-release file either.

There's somethign wrong with your initrd. I doubt this is fault of systemd...

**Comment by skinkie** [comment]
@poettering This is a stock installation of ArchLinux (ARM). When the systemd hook is added to the mkinitcpio configuration the system boots, without any issues. If you would like to see that happening, I'm happy to provide a log file for that too. The volatile switch-root issue is something that in 80% of the cases occurs, hence the system gives the "Switch Root"-error, with some pervasive pressing the Enter key it can after 1-5 times boot into the system.

This is the contents of the initramfs contents; I concur /etc/os-release and systemd-volatile-root.service are missing. If the best thing is to open an issue at the ArchLinux bugtracker, I am happy to do so.
[initramfs-linux.txt](https://github.com/systemd/systemd/files/4999908/initramfs-linux.txt)

**Comment by poettering** [comment]
If stock archlinux initrd installs systemd into /usr/local then this sounds like something to report to arch, yes.

Our README even explicitly documents this: `Note that the build prefix for systemd must be /usr.`

Anyway, let's close this here, please follow up with the Arch maintainers. If there's something wrong with systemd after all I am sure they'll escalate this back to us. Hope that makes sense.

**Comment by skinkie** [comment]
> If stock archlinux initrd installs systemd into /usr/local then this sounds like something to report to arch, yes.

As you can observe from the file list, this is not the case. But your other two comments are still valid.

> Anyway, let's close this here, please follow up with the Arch maintainers. If there's something wrong with systemd after all I am sure they'll escalate this back to us. Hope that makes sense.

For future reference and SEO: https://bugs.archlinux.org/task/67439
