### ISSUE TITLE
machinectl pull-tar fails with "broken pipe" for tarballs with trailing garbage

### ISSUE THREAD

**Issue by marcecj** [systemd/systemd#16605]
**systemd version the issue has been seen with**
> 244.3 (Gentoo)
> 245.6 (openSUSE TW)

**Used distribution**
 > Gentoo
 > openSUSE TW

**Expected behaviour you didn't see**
 > machinectl pull-tar --verify=no http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz succeeds

**Unexpected behaviour you saw**
 > machinectl pull-tar --verify=no http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz fails with a broken pipe (see below)

**Steps to reproduce the problem**
The following is from my Gentoo desktop, but I got the same error on my openSUSE TW laptop:
```
% machinectl pull-tar --verify=no http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz -
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz', saving as 'stage3-amd64-systemd-20200722T214503Z'.
Downloading 230.1M for http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz.
Downloading 355B for http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.nspawn.
HTTP request to http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.nspawn failed with code 404.
Settings file could not be retrieved, proceeding without.
Got 1% of http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz. 2min 50s left at 1.3M/s.
[...]
Got 97% of http://distfiles.gentoo.org/releases/amd64/autobuilds/20200722T214503Z/stage3-amd64-systemd-20200722T214503Z.tar.xz. 1s left at 4.3M/s.
Failed to write file: Datenübergabe unterbrochen (broken pipe)
Failed to retrieve image file. (Wrong URL?)
Exiting.
```
The problem also happens with `systemd-import` on the downloaded and uncompressed file:
```
# LANG=C /lib/systemd/systemd-import tar /home/marcec/tmp/stage3-amd64-systemd-20200722T214503Z.tar test
Importing '/home/marcec/tmp/stage3-amd64-systemd-20200722T214503Z.tar', saving as 'test'.
Imported 0%.
[...]
Imported 99%.
Failed to decode and write: Broken pipe
Exiting.
```
What works is unpacking the tarball and using `import-fs`:
```
% sudo machinectl import-fs ~/tmp/gentoo_test/ test
Passwort: 
Enqueued transfer job 1. Press C-c to continue download in background.
Importing '/home/marcec/tmp/gentoo_test', saving as 'test'.
(Note, file list shown below is incomplete, and is intended as sporadic progress report only.)
Copying tree, currently at 'usr/bin/symcryptrun' (@115.8K)...
[...]
Copying tree, currently at 'sbin/losetup' (@111.0K)...
Exiting.
```
After that I finally have an image:
```
# machinectl list-images -a
NAME  TYPE      RO  USAGE CREATED                      MODIFIED
.host subvolume no  10.3G Tue 2019-04-23 18:17:31 CEST n/a     
test  subvolume no 525.2M Tue 2020-07-28 18:31:50 CEST n/a     

2 images listed.
```

**Comment by poettering** [comment]
Hmm, the link is gone unfortunately. Do you by any chance have a link that works right now that works?

**Comment by poettering** [comment]
Where by "working" I mean, reproduces the issue this bug report is about, i.e. results in EPIPE rather than 404

**Comment by poettering** [comment]
Ah, `https://gentoo.osuosl.org/releases/amd64/autobuilds/20200826T214504Z/stage3-amd64-systemd-20200826T214504Z.tar.xz` appears to be a URL that exposes this and currently works.

**Comment by poettering** [comment]
Hmm, how are these images generated? Is it possible that the tar archive contains trailing garbage? the tar tool simply closes the stream at the end of things, but there's more data to write to it, at which point we'll EPIPE.

**Comment by poettering** [comment]
So, yeah, it appears these archives contain garbage at the end.  If you untar this with `--ignore-zeros` on the regular tar command line it notices this and fails, too.

Not sure what the best strategy here is. We can simply ignore trailing garbage too. Like "tar" invoked on the file would. Or we can just add a better log message explaining the situation. Either way, the Gentoo folks probably have some bug in their image generation logic.

**Comment by poettering** [comment]
I prepped #16930 now which makes tar generate a somewhat usable error for borked tar files like this. Please contact the gentoo people to fix their archives though.

(I think it's better to refuse such bad archives than to silently ignore the trailing garbage, since we are operating on signed, verified cleanly built images here, and not physical tape drive archives where size information is not really available. Better detect corrupt data than to silently eat it up here)

**Comment by marcecj** [comment]
> I prepped #16930 now which makes tar generate a somewhat usable error for borked tar files like this. Please contact the gentoo people to fix their archives though.

I didn't even think to check the tarballs, I will definitely ask about that.  In any case, thanks for making this easier to debug in the future!

**Comment by floppym** [comment]
Gentoo [bug report](https://bugs.gentoo.org/787194), for reference.
