### ISSUE TITLE
network: rename settings about DHCPv6 prefix delegation

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#16602]
Currently, we have three settings to configure DHCPv6 prefix delegation.
```
[Network]
IPv6PDSubnetId=
[DHCPv6]
AssignAcquiredDelegatedPrefixAddress=
AssignAcquiredDelegatedPrefixToken=
```
I think we should introduce a new section and rename the settings like follows:
```
[DHCPv6PrefixDelegation]
SubnetID=
Assign=
Token=
```
@poettering, @keszybz, @ssahani, @andir and @mamarley. WDYT?

Note that all the above settings are introduced after v245. So, if they should be renamed, that should be done before v246 release.

**Comment by mamarley** [comment]
Sounds logical to me.  I thought it was kind of silly to be putting a [DHCPv6] section in the configuration files for the LAN interfaces on my router.

**Comment by yuwata** [comment]
From https://github.com/systemd/systemd/pull/16585#issuecomment-665343528
> I wonder if it might be a good idea to have the new configuration section name more explicitly reflect that it handles the receiving end of prefix delegation (versus the existing [IPv6PrefixDelegation] section that handles the "sending" end).

Any suggestions?

**Comment by andir** [comment]
I think your proposal is good. It was source of many confusions in the past
and having used some of the new options throughout the last months I can
see how the proposed renaming is helping. :+1:.

**Comment by mamarley** [comment]
> 
> Any suggestions?

I thought about it for a while and I couldn't come up with anything that didn't sound awkward.  What you called it is better than anything I could come up with.  Sorry for the bother.
