### ISSUE TITLE
Socket Activated Containers: stop idle containers

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#16637]
http://0pointer.de/blog/projects/socket-activated-containers.html mentioned future improvements to socket activated containers would include shutting down idle containers. Unless my google skills failed me, this never seems to have been added. Are there any major blockers preventing implementing this?

I'm in a scenario (https://github.com/systemd/mkosi/pull/482) where it would be great if systemd could shut down a container when the last SSH connection is terminated. 

cc @poettering

**Comment by poettering** [comment]
well, the question is: what *is* an idle container? i.e. how would you define that?

on desktops we have logind to detect idle and then suspend/shutdown. I wonder what that means for socket services though...

I mean, exiting on idle is easy to implement. But figuring out what precisely idle means is much harder...

**Comment by DaanDeMeyer** [comment]
Hmm you're right, maybe it would have to be user defined? E.g when the last instance of this service exits, shut down the container.

Maybe we don't even need to add anything for that. I guess a service that shuts down the container with After=sshd@.service could work here.

I'm not sure if this will work out of the box with the container socket activation mechanism though. I'll try it out and report back.

**Comment by DaanDeMeyer** [comment]
Solved, see https://lists.freedesktop.org/archives/systemd-devel/2020-August/045077.html

The basic idea to shutdown the system after at least one service of a set of services has started and all of those services have exited is to have each of these services pull in a poweroff-when-unneeded service that has StopWhenUnneeded in its unit file and runs systemctl poweroff on exit.
