### ISSUE TITLE
LogNamespace for user units

### ISSUE THREAD

**Issue by aerusso** [systemd/systemd#16638]
**systemd version the issue has been seen with**
> 245.7

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
> User unit file executed, with output redirected per LogNamespace

**Unexpected behaviour you saw**
 > User unit file failed with `.service: Failed to connect stdout to the journal socket, ignoring: Connection refused` and then `.service: Failed to set up mount namespacing: Operation not supported`

**Steps to reproduce the problem**
1. Create a user unit with `LogNamespace` set to something.
2. Make sure that `systemd-journalctld@something.service` is loaded and running.
3. Start the user unit.

**Comment**

I can't seem to find any documentation if this is supported.  If it's not, we should add documentation clarifying that.  If it is, either I'm really botching something, or we should improve the experience for doing this.  It's worth noting that I have not restarted my machine since setting the `LogNamespace` options up.  I'll also add that for system units, the namespace is working perfectly fine (and I'm particularly thrilled about it, thanks!)

**Comment by poettering** [comment]
We unfortunately cannot implement this. LogNamespace= requires mount namespaces, so that we can redefine where /dev/log points to for services, but mount namespaces are only available to privileged processes. 

#16680 documents this properly.
