### ISSUE TITLE
InitialCongestionWindow and InitialAdvertisedReceiveWindow are multipliers for MSS

### ISSUE THREAD

**Issue by ryancdotorg** [systemd/systemd#16643]
**systemd version the issue has been seen with**
> v246

**remainder of template irrelevant, as this is a documentation bug**

The man page for systemd.network describes the value for `InitialCongestionWindow` and `
`InitialAdvertisedReceiveWindow` as

>  Takes a size in bytes between 1 and 4294967295 (2^32 - 1). The usual suffixes K, M, G are supported and are understood to the base of 1024.

This is not accurate.

A correct description of the value, from the `iproute2` documentation:

> Actual window size is this value multiplied by the MSS (``Maximal Segment Size'') for same connection.

Since MSS may be affected by various conditions on a per connection basis, it is not possible to compute a value to use for the route from a number of bytes.

As such:

*  Support for K/M/G suffixes should be removed.

* Documentation should be updated with wording similar to that used by `iproute2`

**Comment by yuwata** [comment]
Thanks, we will mention that.

> Support for K/M/G suffixes should be removed

But we cannot do so for backward compatibility.

**Comment by ryancdotorg** [comment]
Values using even a K are so as to cause pathological network stack behavior. What benefit would there be to honor them rather than ignore (as a non-fatal error)?

The default value is 10, and 100 is considered remarkably large.

I found a research paper from last year talking about what values are in production use: https://arxiv.org/pdf/1902.08937.pdf

**Comment by yuwata** [comment]
Even so, we should keep the backward compatibility. We can also set meaninglessly large value without suffix, e.g., 10000000. So, dropping to support suffix does not solve any issues.

**Comment by ryancdotorg** [comment]
How about rephrasing the docs as:

InitialCongestionWindow=

>  The TCP initial congestion window is used during the start of a TCP connection. During the start of a TCP session, when a client requests a resource, the server's initial congestion window determines how many packets will be sent during the initial burst of data without waiting for acknowledgement. Takes a number between 1 and 4294967295 (2^32 - 1). Note that 100 is considered an extremely large value for this option. The K, M, and G suffixes are supported for backwards compatibility but should not be used. When unset, the kernel's default (typically 10) will be used.

and similar language for InitialAdvertisedReceiveWindow?

**Comment by yuwata** [comment]
@ryancdotorg Sorry for late response. And thank you for the suggestion. Fix is waiting in #17087.
