### ISSUE TITLE
document clearer that socket passing protocol guarantees no fd order whatsoever

### ISSUE THREAD

**Issue by mildred** [systemd/systemd#16647]
**systemd version the issue has been seen with**
> systemd 241 (241)
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > debian 10 buster

**Expected behaviour you didn't see**
 > When starting a service that depends on two socket units, the file descriptors should be passed in a stable order

**Unexpected behaviour you saw**
 > When starting a service that depends on two socket units, the file descriptor order is not constant

**Steps to reproduce the problem**

socket unit `nimnews.socket`:
```
[Unit]
Description=NimNews NNTP and NNTPS socket

[Socket]
ListenStream=[::]:119
ListenStream=[::]:563
BindIPv6Only=both

[Install]
WantedBy=multi-user.target
```
socket unit `nimnews-lmtp.socket`:
```
# /etc/systemd/system/nimnews-lmtp.socket
[Unit]
Description=NimNews NNTP and NNTPS socket

[Socket]
ListenStream=/run/nimnews-lmtp.socket
Service=nimnews.service

[Install]
WantedBy=multi-user.target
```

Service `nimnews.service` (actually any daemon that keeps running should demonstrate the issue, just `lsof -p PID` and see the socket order):
```
[Unit]
Description=NimNews server
After=network.target
Requires=nimnews.socket nimnews-lmtp.socket
After=nimnews.socket nimnews-lmtp.socket

[Service]
Sockets=nimnews-lmtp.socket
Sockets=nimnews.socket
ExecStart=/usr/local/bin/nimnews \
  --port sd=0 --tls-port sd=1 \
  --db /var/lib/nimnews.sqlite \
  --fqdn perrin.mildred.fr \
  --cert /etc/letsencrypt/live/perrin.mildred.fr/fullchain.pem \
  --skey /etc/letsencrypt/live/perrin.mildred.fr/privkey.pem \
  --lmtp-socket sd=2 \
  --smtp localhost --smtp-port 587 \
  --log --smtp-debug
```

No matter what order I have the sockets in `Socket=` directive, the file descriptor order is not stable.

**Comment by arvidjaar** [comment]
According to `sd_listen_fds(3)`

> If multiple socket units activate the same service, the order of the file descriptors passed to its main process is undefined. 

You may consider using `sd_listen_fds_with_names` to identify them.

P.S. granted, here we have usual systemd lack of clarity. Does "activate the same service" refer to "systemd receives concurrent connection requests on multiple sockets" or "there are multiple socket units that define the same `Service=`"?

**Comment by mildred** [comment]
Thank you, it was not documented in `systemd.socket` and `systemd.service` so I didn't see it. That solves the problem. Unless there is atechnical limitation, that'd still be nice to have always the same order but that's not as important. Also, the documentation could be clarified.

As the use case is handled by `sd_listen_fds_with_names` feel free to close the issue if you think there is nothing to do on this.

Thank you for the answer.

**Comment by poettering** [comment]
I am not convinced we should define a strict order here. fds can come from many sources, not just socket activation but also the fdstore, and i have no clue how we'd define a clear, systematic order there.

I think we should just document clearly that no order is guaranteed whatsoever, and people should search by fd type or by name.

i.e. sd_is_socket() and so on is the way to go, always has been...

Turning this into a documentation issue hence. Hope that makes sense?
