### ISSUE TITLE
Could not set hostname: Permission denied

### ISSUE THREAD

**Issue by kaizen1** [systemd/systemd#16656]
systemd 245 (245.4-4ubuntu3.2)
OS: Ubuntu 20.04 minimal Google Cloud image

**Expected behaviour you didn't see**
 > I would expect systemd-networkd to set the hostname

**Unexpected behaviour you saw**
 > hostname could not be set due to permission error. 

**Steps to reproduce the problem**
Reboot the VM 
Run sudo systemctl status systemd-networkd

Get: 

● systemd-networkd.service - Network Service
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-08-03 17:25:10 UTC; 5min ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 606 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 2010)
     Memory: 1.4M
     CGroup: /system.slice/systemd-networkd.service
             └─606 /lib/systemd/systemd-networkd

systemd[1]: Starting Network Service...
systemd-networkd[606]: Enumeration completed
systemd[1]: Started Network Service.
systemd-networkd[606]: ens4: DHCPv4 address 10.142.0.11/32 via 10.142.0.1
systemd-networkd[606]: Could not set hostname: Permission denied

**Comment by yuwata** [comment]
Is `systemd-hostnamed` installed? `networkd` itself does not set hostname, but set it through `hostnamed`.

**Comment by yuwata** [comment]
Maybe related to #13501.

**Comment by kaizen1** [comment]
● systemd-hostnamed.service - Hostname Service
     Loaded: loaded (/lib/systemd/system/systemd-hostnamed.service; static; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:systemd-hostnamed.service(8)
             man:hostname(5)
             man:machine-info(5)
             https://www.freedesktop.org/wiki/Software/systemd/hostnamed

Aug 05 12:23:57 vm1 systemd[1]: Starting Hostname Service...
Aug 05 12:23:57 vm1 systemd[1]: Started Hostname Service.
Aug 05 12:24:27 vm1 systemd[1]: systemd-hostnamed.service: Succeeded.
Aug 05 12:28:09 vm1 systemd[1]: Starting Hostname Service...
Aug 05 12:28:09 vm1 systemd[1]: Started Hostname Service.
Aug 05 12:28:42 vm1 systemd[1]: systemd-hostnamed.service: Succeeded.

**Comment by yuwata** [comment]
> `libpolkit-gobject-1-0`

Is this only installed package related to `polkit`? I do not know the exact name of `polkit` package in Ubuntu. But `libpolkit-gobject-1-0` seems not sufficient. Please install `polkit`.

**Comment by yuwata** [comment]
Ah, maybe `policykit`.
https://packages.ubuntu.com/focal/policykit-1

**Comment by kaizen1** [comment]
sudo apt install policykit-1
No more permissions error from: sudo systemctl status systemd-networkd
Thank you @yuwata !
どうもどうも！

**Comment by yuwata** [comment]
どういたしまして。
