### ISSUE TITLE
Export "Memory modules" information

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#16651]
The "About" dialogue in GNOME currently shows the amount of memory actually visible by the OS, along with hardware information, such as the CPU and Graphics used. On a lot of systems with integrated video cards, the OS visible RAM doesn't match "hardware" RAM.

On x86, the DMI information contains useful data:
```
Handle 0x003C, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x003B
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 8 GB
        Form Factor: DIMM
        Set: None
        Locator: ChannelA-DIMM0
        Bank Locator: BANK 0
        Type: DDR4
        Type Detail: Synchronous
        Speed: 2667 MT/s
        Manufacturer: Samsung
        Serial Number: 416433E9
        Asset Tag: 9876543210
        Part Number: M378A1K43CB2-CTD    
        Rank: 1
        Configured Memory Speed: 2400 MT/s
        Minimum Voltage: 1.2 V
        Maximum Voltage: 1.2 V
        Configured Voltage: 1.2 V
<etc>
```

For each slot, having the amount, the form-factor, the type (DDRX) and the speed of the RAM could allow showing something like `24GiB 2600Mt/s DDR4 DIMM`, instead of `23.4GiB`, or could show the separate memory modules graphically, along with the free space if any (look for `about this mac` images, you can see the textual representation used in newer versions, and the graphical info used in older versions).

That information is available in `/sys/firmware/dmi/entries/17-*` on x86 Linux systems, but we don't have good "devices" in udev to attach this information to without encoding it somehow. I also don't know whether `hostnamectl` would be a good place to export this information (probably not).

**Comment by hadess** [comment]
One option might be to have a `dmi-memory` similar to the `dmi-id` code in the kernel. We'd have a virtual device that handles all the memory modules and attributes we could parse through. Or devices for each slot.

**Comment by hadess** [comment]
Example UIs:
![image](https://user-images.githubusercontent.com/769861/89187884-29bca780-d59e-11ea-8305-b75babcb5985.png)
![image](https://user-images.githubusercontent.com/769861/89187895-2e815b80-d59e-11ea-8f59-ebc05bb7f884.png)
![image](https://user-images.githubusercontent.com/769861/89188044-65577180-d59e-11ea-9622-48e45b9dcfd6.png)

**Comment by keszybz** [comment]
> One option might be to have a `dmi-memory` similar to the `dmi-id` code in the kernel. We'd have a virtual device that handles all the memory modules and attributes we could parse through. Or devices for each slot.

Hmm, do we need to involve the kernel in this at all? The information printed by `dmidecode` requires privileges, but apart from that we could do that purely in user space.  Maybe we could define a "virtual device" purely in udev, so that it would be possible to use udevadm and the sd-device library calls to query this device, and let the userspace query this information however it wants to?

**Comment by hadess** [comment]
> Hmm, do we need to involve the kernel in this at all? The information printed by `dmidecode` requires privileges, but apart from that we could do that purely in user space.

It would stop needing stuff that pokes at hardware directly, or needing root.

> Maybe we could define a "virtual device" purely in udev, so that it would be possible to use udevadm and the sd-device library calls to query this device, and let the userspace query this information however it wants to?

Do you have an example of how that virtual device would be implemented?

**Comment by keszybz** [comment]
> It would stop needing stuff that pokes at hardware directly, or needing root.

Yes, exactly. Access to udev database is unprivileged.

> Do you have an example of how that virtual device would be implemented?

No, I think udev doesn't do anything like this currently. Essentially, instead of creating a device in response to a kernel uevent, we would create a fake device statically.

**Comment by poettering** [comment]
we could have a little builtin helper a la usb_id/input_id/pci_id or so. Called "dmi_id", and it would run on the DMI virtual device, would parse out a few things and attach them as udev properties onto the DMI virtual device. Then, GNOME could simply query those properties off the device, entirely unprivileged.

**Comment by hadess** [comment]
> we could have a little builtin helper a la usb_id/input_id/pci_id or so. Called "dmi_id", and it would run on the DMI virtual device, would parse out a few things and attach them as udev properties onto the DMI virtual device. Then, GNOME could simply query those properties off the device, entirely unprivileged.

The problem is that the existing `DMI virtual device` in the kernel is a virtual device for DMI **IDs**. The dmi-sysfs entries (or a container for those) aren't presented as udev devices, which would have made creating a udev helper a no-brainer.

**Comment by poettering** [comment]
Not sure I follow? I'd just attach this to `/sys/class/dmi/id/`, which is a device. Of course, internally, we'd parse the data from `/sys/firmware/dmi/tables/DMI` but that shouldn't really matter.

The device `sys/class/dmi/id/` was named "id" just because we had no better name (yours truly wrote the kernel patch adding that, actually), and we didn't want to call it `dmi` since then it would be a device `dmi` of the class `dmi` which is a bit confusing. But I see no reason not to attach other info to it as well...

**Comment by hadess** [comment]
Then I'll look at going with that then, thanks.

**Comment by hadess** [comment]
I just need to finish selecting which attributes are important, and do a final cleanup pass before trying to integrate it:
https://github.com/hadess/udev-memory-devices
