### ISSUE TITLE
securebits can't be set

### ISSUE THREAD

**Issue by wusto** [systemd/systemd#16666]
**systemd version the issue has been seen with**
> 243 (but the affected code hasn't changed since then)

**Used distribution**
 > yocto

**Expected behaviour you didn't see**
 > securebits shall be set e.g. when setting SecureBits=noroot-locked in the service file and the service is running as non-root user.
 > However the securebit can be set if an Ambient capability is defined in the service file

**Unexpected behaviour you saw**
 > service startup fails

**Steps to reproduce the problem**
> Add SecureBits=noroot-locked to an service file which is not setting AmbientCapabilities and which is running as non-root user.

**Investigation results**
- the capability CAP_SETPCAP is needed to set securebits
- the effective and permitted set are cleared during setresuid (in enforce_user())
- securebits are set after setresuid, but CAP_SETPCAP is cleared from the effective set -> Failure

If an arbitrary capability is set:
- This changes the behavior of enforce_user. The securebit keep-caps is set in enforce_user. Thus the effective and the permitted set are not cleared during the following setresuid and the other securebits can be set afterwards.

**Remark**
- I already have prepared a patch, which I am willing to submit, if the intended behavior is to set securebits without changing ambient capabilities.
- The code section in exec_child is not in the best shape and needs most probably rework. 
  - uid_is_valid is invoked up to 10x (in exec_child and in invoked functions).
  - Documentation is misleading/outdated (patch available)
  - code with no impact is in place (e.g. set keep-caps after setresuid) (patch available)

**Comment by poettering** [comment]
Please submit your patches as PR, we'll then review them there.

uid_is_valid() is trivial, gcc/lto should optimize it away...
