### ISSUE TITLE
LDAP users with gecos field cause userdbd to fail with "Input/output error"

### ISSUE THREAD

**Issue by BtbN** [systemd/systemd#16668]
**systemd version the issue has been seen with**
> 245.5

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > "userdbctl user XYZ" actually showing info about the user.

**Unexpected behaviour you saw**
 > "Failed to find user XYZ: Input/output error"

**Steps to reproduce the problem**

This only happens for users that are brought into the system via ldap in nsswitch.conf. Using nss-pam-ldapd.
Additionally, it only happens for some of them. After some testing around, I realized that those users with no gecos field work properly, and get their user session started on login.
For users which do have a gecos field set, it fails with above message, both via userdbctl and on pam_systemd for session creation.

Querying information via getend and logging in as those users works otherwise perfectly fine.

"getent passwd XYZ" reports:
`XYZ:x:10003:10003:Account added via adduser.sh by root on Wed Jun 28 13 43 29 CEST 2017:/home/XYZ:/bin/bash`

For user ABC, which does not have a gecos field, getent output looks like this:
`ABC:x:10000:10000:ABC:/home/ABC:/bin/bash`

To confirm, I plain removed the gecos field from one of the users. And it immediately started working as expected.

Update: The script that generates that gecos field puts the time in in the form of "13:43:29", and it's those additional ":" that trip it up. Removing just those ":" fixed it.
For getent, something, somewhere seems to just filter out those extra ":", but not so in userdbd.

**Comment by poettering** [comment]
hmm, those gecos fields are definitely invalid, i.e. you cannot have ":" in them, since that's what /etc/passwd uses as separators... You cannot have newlines in them either...

I figure we can try to handle this more gracefully, and try to mangle invalid chars, but the data in your userdatabase is definitely fishy here...

**Comment by BtbN** [comment]
Yeah, I already fixed all the gecos fields, the primary issue is the poor Error-Message in this case.
Replacing the ":" while logging a warning would be even nicer.

**Comment by poettering** [comment]
Fix waiting in #166682
