### ISSUE TITLE
org.freedesktop.systemd1 crash with error "Failed to get properties: Connection timed out" by running systemctl commands; and notify socket failure with error  "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by ygangch** [systemd/systemd#16670]
**systemd version the issue has been seen with**
> Version 245.5+

**Used distribution**
 >yocto

**Expected behaviour you didn't see**
 >get/set DBus property should work.

**Unexpected behaviour you saw**
 >systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Connection refused  
systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected 

root@obmc:/# busctl tree org.freedesktop.systemd1
systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Failed to introspect object / of service org.freedesktop.systemd1: Connection timed out
No objects discovered.
root@obmc:/# systemctl status bmcweb
Failed to get properties: Connection timed out
set/get DBus property failure

**Steps to reproduce the problem**
1. power on -> 2. system bring up 3. -> system is up and wait for tens seconds 4. -> cold reset --> cycling from step 2 to Step 4 for about 279 cycles then runs into issue.
According to our test, it's only reproduced by Version 245, not reproduced before Version 245.

**Comment by poettering** [comment]
Please provide debug logs when this happens. Otherwise there's little we can do. i.e. set 'systemd.log_level=debug` on kernel cmdline, then reproduce the issue and attach logs here.

**Comment by ygangch** [comment]
By debugging, the following error is output by checking return "l" value after socket send(l = send(s->notify_fd, p, strlen(p), MSG_DONTWAIT); ) to local rootfs socket file "/run/systemd/notify", which is failed in journald-server.c(dispatch_notify_event()) of systemd: 

systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Connection refused
systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected

**Comment by ygangch** [comment]
more error information:

busctl:
org.freedesktop.systemd1                            - -               -               (activatable) -                                                                     -       -
compare to good results:
busctl:
org.freedesktop.systemd1                           1 systemd         root            :1.2          init.scope                                                             -       -



1.busctl command works fine,
root@intel-obmc:~# busctl introspect  xyz.openbmc_project.CPUSensor /xyz/openbmc_project/sensors/temperature/Die_CPU1 xyz.openbmc_project.Sensor.Value

NAME                             TYPE      SIGNATURE RESULT/VALUE FLAGS

.MaxValue                        property  d         127          emits-change

.MinValue                        property  d         -128         emits-change

.Value                           property  d         26.922       emits-change writable

2. D-Bus property works fine.
3. all related systemd1 run into issue:
systemctl status bmcweb
Failed to get properties: Connection timed out
 busctl set-property org.freedesktop.systemd1 \
>   /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel s "debug"
Failed to set property LogLevel on interface org.freedesktop.systemd1.Manager: Connection timed out
root@intel-obmc:~# busctl get-property org.freedesktop.systemd1 \
>  /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel
[219168.221615] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Failed to get property LogLevel on interface org.freedesktop.systemd1.Manager: Connection timed out

Error info:
[   82.922116] lm75 6-004f: hwmon7: sensor 'tmp75'
[   82.926870] i2c i2c-6: new_device: Instantiated device tmp75 at 0x4f
[   82.990687] i2c i2c-7: new_device: Instantiated device eeprom at 0x51
[   86.136713] i2c i2c-7: new_device: Instantiated device pmbus at 0x59
[  107.136458] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Connection refused
[  198.869083] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[  288.443123] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[  378.293351] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[  467.133757] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[  557.399559] systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected

and it's similar issue with "systemd-journald fails to connect to notify socket with SELinux and dracut #16714"

**Comment by ygangch** [comment]
the following error would be disappear after run "/lib/systemd/systemd-journald &"
"systemd-journald[138]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected"

But systemd1 & systemctl command failure(such as "systemctl status org.freedesktop.systemd1", etc..) can't be recovery by "kill -9 1" or "systemctl daemon-reexec"(No output message after running "systemctl daemon-reexec").

root@intel-obmc:~# systemctl status org.freedesktop.systemd1

Failed to get properties: Connection timed out

root@intel-obmc:~# busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel

Failed to get property LogLevel on interface org.freedesktop.systemd1.Manager: Connection timed out

**Comment by ygangch** [comment]
root@intel-obmc:/tmp# systemctl status sshd
Failed to get properties: Connection timed out
root@intel-obmc:/tmp# systemctl cat sshd
Failed to get LoadState: Connection timed out
root@intel-obmc:/tmp# systemctl
Failed to list units: Connection timed out
something like the old issue described in  "https://github.com/systemd/systemd/issues/4444"

**Comment by ygangch** [comment]
it can't recovery by "systemctl daemon-reload", "systemctl daemon-reexec  " or  "kill 1", need to reboot the system to recovery it.

**Comment by ygangch** [comment]
it caused by services dependency, network service is started late so some notify socket were missed to handle.

**Comment by rocketraman** [comment]
I had the same problem today after a kernel oops. Even `reboot` doesn't work:
> Failed to reboot system via logind: Connection timed out

The only way to reboot as far as I could tell was to use magic sysrq.

**Comment by Heavygrass** [comment]
Having this same issue with systemd 255.
Neither "systemctl daemon-reexec " nor "kill 1" works.

org.freedesktop.systemd1 is inactive.

```
systemctl status org.freedesktop.systemd1

Failed to get properties: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeo

busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel
Failed to get property LogLevel on interface org.freedesktop.systemd1.Manager: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
```

**Comment by 10dcar** [comment]
> Having this same issue with systemd 255. Neither "systemctl daemon-reexec " nor "kill 1" works.
> 
> org.freedesktop.systemd1 is inactive.
> 
> ```
> systemctl status org.freedesktop.systemd1
> 
> Failed to get properties: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeo
> 
> busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel
> Failed to get property LogLevel on interface org.freedesktop.systemd1.Manager: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
> ```

me too
