### ISSUE TITLE
About the mechanism of using the customized globle DNS Server and the specific dns settings on the interfaces. 

### ISSUE THREAD

**Issue by hongyi-zhao** [systemd/systemd#16693]
Hi,

On Ubuntu 20.04, I set the customized global dns server by the following file:

```
$ cat /etc/systemd/resolved.conf.d/dns_servers.conf 
# https://wiki.archlinux.org/index.php/Systemd-resolved
# Use the new setting:
#sudo systemctl restart systemd-resolved
# Test it:
#resolvectl status
# or
#systemd-resolve --status
[Resolve]
DNS=127.0.0.1 
Domains=~.
```

And at the same time, the specific interfaces will obtain the default dns servers via dhcp. See the following for mor info:

```
$ resolvectl status | egrep -i 'dns server|link|global'
Global
  Current DNS Server: 127.0.0.1           
         DNS Servers: 127.0.0.1           
Link 3 (enp5s0)
  Current DNS Server: 192.168.1.1
         DNS Servers: 192.168.1.1
Link 2 (enp4s0)
```

Does this mean the mechanism of systemd-resolved for my case is as following:

1. If 127.0.0.1 is alive, it will be used for all interfaces.
2. If 127.0.0.1 is dead/unavailable, 192.168.1.1 will be used for `Link 3`
3. If 127.0.0.1 is unavailable at the beginning  when connecting to it and then after a while it becomes alive, then it will be resued for the  `Link 3`.

Am I right?

Regards
HY

**Comment by poettering** [comment]
This is not a support forum. The issue submission form should have made that very clear in order to keep frustration at a minimum. Please use the mailing list instead if you have a support question. Thank you for understanding.
