### ISSUE TITLE
systemd-networkd doesn't establish connection after resume from suspend at v246

### ISSUE THREAD

**Issue by ynakao** [systemd/systemd#16696]
**systemd version the issue has been seen with**
> v246

**Used distribution**
 > Arch Linux 5.7.12-arch1-1

**Expected behaviour you didn't see**
 > Establish wireless connection with my acccess point after resume from suspend.

**Unexpected behaviour you saw**
 > Failed to connect with my AP saying `No static address is stored.`

**Steps to reproduce the problem**

I'm using systemd-networkd and iwd for wireless settings.

1. At first boot, internet connection works fine.

2. Execute `$ systemctl suspend`, and open the laptop lid to resume from suspend.

3. systemd-networkd doesn't establish the connection.

After resume from suspend, manually restarting `systemd-networkd.servise` makes internet connection work again.

And systemd-networkd works properly by downgrading systemd to the previous version `$ sudo pacman -U /var/cache/pacman/pkg/systemd-245.7-1-x86_64.pkg.tar.zst`.

---

journalctl log `$ journalctl -u systemd-networkd`
```
# Boot

Aug 08 09:24:26 hostname systemd[1]: Starting Network Service...
Aug 08 09:24:27 hostname systemd-networkd[1020]: Enumeration completed
Aug 08 09:24:27 hostname systemd-networkd[1020]: wlan0: Could not find device, waiting for device initialization: No such device
Aug 08 09:24:27 hostname systemd-networkd[1020]: enp0s25: Interface name change detected, enp0s25 has been renamed to eth0
Aug 08 09:24:27 hostname systemd[1]: Started Network Service.
Aug 08 09:24:27 hostname systemd-networkd[1020]: eth0: Interface name change detected, eth0 has been renamed to enp0s25
Aug 08 09:24:27 hostname systemd-networkd[1020]: wlan0: Link DOWN
Aug 08 09:24:27 hostname systemd-networkd[1020]: wlan0: Link UP
Aug 08 09:24:27 hostname systemd-networkd[1020]: enp0s25: Link UP
Aug 08 09:24:30 hostname systemd-networkd[1020]: wlan0: Gained carrier
Aug 08 09:24:30 hostname systemd-networkd[1020]: wlan0: Connected WiFi access point: $MySSID ($MyMACAddress)

# Resume from suspend

Aug 08 09:25:44 hostname systemd-networkd[1020]: wlan0: Lost carrier
Aug 08 09:25:45 hostname systemd-networkd[1020]: wlan0: Gained carrier
Aug 08 09:25:45 hostname systemd-networkd[1020]: wlan0: Reset carrier
Aug 08 09:25:45 hostname systemd-networkd[1020]: lo: Reset carrier
Aug 08 09:25:45 hostname systemd-networkd[1020]: wlan0: No static address is stored.
Aug 08 09:25:45 hostname systemd-networkd[1020]: wlan0: Failed

# Restart systemd-networkd.service

Aug 08 09:26:02 hostname systemd[1]: Stopping Network Service...
Aug 08 09:26:02 hostname systemd[1]: systemd-networkd.service: Succeeded.
Aug 08 09:26:02 hostname systemd[1]: Stopped Network Service.
Aug 08 09:26:02 hostname systemd[1]: Starting Network Service...
Aug 08 09:26:02 hostname systemd-networkd[2130]: Enumeration completed
Aug 08 09:26:02 hostname systemd-networkd[2130]: wlan0: Connected WiFi access point: $MySSID ($MyMACAddress)
Aug 08 09:26:02 hostname systemd[1]: Started Network Service.
```

/etc/systemd/network/25-wireless.network
```
[Match]
Name=wlan0

[Network]
Address=192.168.179.4/24
Gateway=192.168.179.1
DNS=192.168.179.1
```

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #16697. If possible, please test the PR.

**Comment by ynakao** [comment]
Sorry for the late reply. I finally managed to build the patched one.
I confirm patched systemd can establish the connection even after resume from suspend.
I appreciate your work.

**Comment by yuwata** [comment]
@ynakao Thank you for your help to test the PR.
