### ISSUE TITLE
machinectl/nspawn/login session cleanup failed from systemd-239-18 to 239-29 (Update CentOS 8.1 to 8.2)

### ISSUE THREAD

**Issue by gcoretech** [systemd/systemd#16694]
**systemd version the issue has been seen with**
> still present in v246

**Used distribution**
 > Centos 8.1/8.2

**Expected behaviour you didn't see**
 > before this patch machinectl stop container was quick

**Unexpected behaviour you saw**
 > shutdown takes 120 seconds until a (non-existent) user service is killed by systemd after timeout
 > user@0.service: Processes still around after final SIGKILL. Entering failed mode
 > user@0.service: Failed with result 'timeout'.

**Steps to reproduce the problem**

Start a CentOS 8.2 nspawn container from /var/lib/machines/ve2006

  CentOS has been installed with:
  yum --installroot=/var/lib/machines/ve2006 --releasever=8 install systemd centos-release ...

Steps to Reproduce:
1. [root@server1.lan ~]# machinectl start ve2006
2. [root@server1.lan ~]# machinectl shell ve2006
3. [root@ve2006.lan ~]# logout
4. [root@server1.lan ~]# machinectl stop ve2006

Actual results:
Shutdown takes 120 seconds (machinectl list shows ve2006 still running)

[  *** ] A stop job is running for User Manager for UID 0 (1min 43s / 1min 43s)

(from journalctl -M ve2006 -f):
systemd[1]: user@0.service: Processes still around after final SIGKILL. Entering failed mode.
systemd[1]: user@0.service: Failed with result 'timeout'.
systemd[1]: Stopped User Manager for UID 0.
systemd[1]: user-runtime-dir@0.service: Unit not needed anymore. Stopping.
systemd[1]: Removed slice User Slice of UID 0.

Also see https://bugzilla.redhat.com/show_bug.cgi?id=1866888

This has been introduced with systemd-239-29.el8.src.rpm on CentOS 8.2

**Solution**

I've narrowed it down to Patch0233: 0233-core-only-watch-processes-when-it-s-really-necessary.patch
which is the following: https://github.com/systemd/systemd/commit/846a07b50594e763c2ed57855a6bf97d42cfa32a

machinectl shutdown works as expected after recompiling systemd-239-29.el8.src.rpm with patch 0233 disabled

**Comment by poettering** [comment]
hmpf. this bug tracker is exlusively about issues in curretn upstream systemd versions, i.e. 245 and 246 at the moment. Can you reproduce this with those two versions?

**Comment by gcoretech** [comment]
I had checked that patch was still unchanged in master and thus reported it, seems that was not enough.
I copied the systemd 239 rpm spec file, removed all patches and compiled a new set with systemd 246.
machinectl shutdown does not hang anymore, so it seems to be a problem specific to redhat versions.
