### ISSUE TITLE
sytemd-journald config silently falls back to default config with inline comment in config file

### ISSUE THREAD

**Issue by onjen** [systemd/systemd#16710]
**systemd version the issue has been seen with**
245.6-2

**Used distribution**
debian testing

**Expected behaviour you didn't see**
An error when loading a config file with inline comment.

**Unexpected behaviour you saw**
Config was not loaded but no error was thrown. It just silently fall back to the default config.

**Steps to reproduce the problem**
Edit and entry `/etc/systemd/journald.conf` for example `SystemMaxUse=6G` restart systemd-journald. Everything is fine. 
`journalctl -u systemd-journald` shows the new value has been loaded successfully.
`systemd-journald[3020]: System Journal (/var/log/journal/650aa7e3d265476b8579154406431ac8) is 272.0M, max 6.0G, 5.7G free.`

But now add an inline comment in that line, for example `SystemMaxUse=6G # foo`, restart systemd-journald. No error is thrown while trying to load the config, but the value silently went back to 4G from the default config. `journalctl -u systemd-journald` shows `systemd-journald[3727]: System Journal (/var/log/journal/650aa7e3d265476b8579154406431ac8) is 272.0M, max 4.0G, 3.7G free.` I would have expected at least a warning in the log, that the line is ignored.

**Comment by poettering** [comment]
Can you check if logs about this appear in dmesg?

Note that journald is a weird thing, it cannot log like a regular program to the journal, because it *is* the journal. In particular during initialisation, where it has no log files open it cannot log to the journal hence. What it does instead is write to kmsg. Eventually it should pick things up there again, though, as kmsg data is eventually flushed to the journal too.

**Comment by onjen** [comment]
Sure, I checked dmesg as well, but nothing there is no error shown when trying to load the config file. Just the default of 4GB is applied again.
```
[Wed Aug 12 19:50:07 2020] systemd[1]: Stopping Journal Service...
[Wed Aug 12 19:50:07 2020] systemd[1]: systemd-journald.service: Succeeded.
[Wed Aug 12 19:50:07 2020] systemd[1]: Stopped Journal Service.
[Wed Aug 12 19:50:07 2020] systemd[1]: Starting Journal Service...
[Wed Aug 12 19:50:08 2020] systemd[1]: Started Journal Service.
[Wed Aug 12 19:50:31 2020] systemd[1]: Stopping Journal Service...
[Wed Aug 12 19:50:31 2020] systemd[1]: systemd-journald.service: Succeeded.
[Wed Aug 12 19:50:31 2020] systemd[1]: Stopped Journal Service.
[Wed Aug 12 19:50:31 2020] systemd[1]: Starting Journal Service...
[Wed Aug 12 19:50:31 2020] systemd[1]: Started Journal Service.
```
I also checked version 246-2 and it shows the same behavior.

**Comment by poettering** [comment]
anything in dmesg?

journald itself doesn't really log to the journal, but to kmsg, to avoid loops

**Comment by onjen** [comment]
With systemd 247.3 there is an entry in dmesg

`[  149.146654] systemd-journald[4867]: /etc/systemd/journald.conf:22: Failed to parse size value, ignoring: 6G #foo`
