### ISSUE TITLE
User unit(service) is stopped("Succeeded") when there's no session left while lingering is enabled

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#16717]
**systemd version the issue has been seen with**

systemd 246 (246.1-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > User units should stay running even when all sessions are terminated when the user has lingering enabled

**Unexpected behaviour you saw**
 > Although the user unit (pulseaudio.service in my case) start and stay running after boot, if I for example remote in via ssh and then disconnect (if I have more than one connection/session then when *all* are disconnected/terminated), the unit is stopped (with the log message "Succeeded", if it matters).

**Steps to reproduce the problem**
1. loginctl enable-linger $NON_ROOT
2. reboot
3. log in as root to monitor/check stuff with e.g. loginctl user-status $NON_ROOT: it is lingering, the user unit is started and running
4. log in as $NON_ROOT (ssh, I supposed it's the same case with tty)
5. log out / terminate all $NON_ROOT sessions
6. confirm the user unit is stopped in the root session

**Comment by poettering** [comment]
I am sorry, I don't get it. What do you mean by "user unit"? The system unit called `user@$USERNAME.service` or a unit that runs in user context, i.e. is run by the service manager that is encapsulated in the system unit `user@$USERNAME.service`?

pulseaudio exits on idle on its own behalf whenever it wants btw. if that's the issue you are having?

**Comment by tomty89** [comment]
> I am sorry, I don't get it. What do you mean by "user unit"? The system unit called `user@$USERNAME.service` or a unit that runs in user context, i.e. is run by the service manager that is encapsulated in the system unit `user@$USERNAME.service`?

The latter. Sorry. I always thought "user units" specifically refers to the units run in user context.

> 
> pulseaudio exits on idle on its own behalf whenever it wants btw. if that's the issue you are having?

Nope. I'm sure it's gone when and only when all sessions of a user are gone. (The only exception is the "first time" -- apparently when a user enter linger state "from scratch", a session will be spawned but gone more or less right away -- judging by the session number.) Apparently `--daemonize=no` makes it stick around.

I can work around the issue with this (a system service):
```
[Unit]
Description=Linger Lock For %I

[Service]
ExecStart=/usr/bin/machinectl shell --uid=%i

[Install]
WantedBy=multi-user.target
```
Or this (a user service):
```
[Unit]
Description=loopback ssh to keep at least one session

[Service]
ExecStart=/usr/bin/ssh -tt %u@127.0.0.1

[Install]
WantedBy=default.target
```

**Comment by poettering** [comment]
i don#t get wht this issue is supposed to be about? PA decides to exit on is own accord, we cannot do anything about it. If you don't want that beaviour, turn it off in PA.

I really don#t grok this bug report? what is systemd supposed to do that it doesn't do?

**Comment by tomty89** [comment]
Is it that hard to understand? Isn't lingering supposed to keep user-context services rolling? And now the behavior is, while it does make the services start and keep it running after boot, BUT that behavior ONLY lasts before a user *logged in and logged out* (i.e. when no session is *left* -- more specifically *after* one/some was/were spawned -- hence *logged in and logged out*).

No offense but have you even read what I wrote? Or is there some misunderstanding on my side? (e.g. PA decides to exit when it notices all sessions are *gone*? as it doesn't exit until, again, one/some was/were spawned *and then* all gone)

This is NOT about PA exiting after all its sinks are idled/suspended for a certain time. NOT. NOT. NOT. No offense but if you ever glimpsed what I wrote above you should have realized that.

**Comment by poettering** [comment]
lingering is supposed to keep the per-user service manager up. What happens inside the service manage is up to the service manager and its services.

I still don#t get what you are trying to say. Are you saying that the system service called `user@tomty89.service` exits when the user `tomty89` logs out even though lingerig is turned on for `tomty89`?

**Comment by tomty89** [comment]
Muh, I wasn't aware of this silly "smart" override: https://github.com/pulseaudio/pulseaudio/commit/de705a0eeaa27a8ac1abdc2625e639340323595a

And then:
https://github.com/pulseaudio/pulseaudio/blob/v13.99.1/src/pulsecore/core.c#L64
https://github.com/pulseaudio/pulseaudio/blob/v13.99.1/src/pulsecore/core.c#L136
https://github.com/pulseaudio/pulseaudio/blob/v13.99.1/src/pulsecore/core.c#L162
https://github.com/pulseaudio/pulseaudio/blob/v13.99.1/src/daemon/main.c#L1036
https://github.com/pulseaudio/pulseaudio/blob/v13.99.1/src/daemon/main.c#L1051

Then exit-idle-time looks disabled / ignored at first but is / will be enabled / (partially) used. Wonderful. (`daemonize` wasn't actually relevant -- probably some interaction/intervention made it seemed otherwise)

Sorry for the false alarm. Should have tested with something else first before filing.

**Comment by tomty89** [comment]
Btw, where is the linger setting stored?

**Comment by poettering** [comment]
`/var/lib/systemd/linger/`
