### ISSUE TITLE
How to handle path unit behaviour change to PathExists from edge to level triggered?

### ISSUE THREAD

**Issue by egtvedt** [systemd/systemd#16713]
Hello,

After commit 708961c7011b7578d3e6e10ca463d15edb62b5c1 ('core/path: recheck path specs when triggered unit changes state'), the behaviour for path unit files with PathExists changed. Although I understand the motivation behind the change, I have experienced that a feature now has gone.

I have several services that I want to start once a file appears on the system, and I only want these services to run once (1 execution) when the marker file appears. The service does not remove the marker file, and the service is a oneshot. Hence once it exists, it is after upgrading to v246 immediately running again.

What is the recommended best practice now to implement a service that should run once depending on a file?

The ConditionPathExists does not solve the case, as it is a one time check, and the service will fail as the marker file is not present at that time.

Or should there be an additional feature to path units, being able to single trigger? Something ala

PathExists=[SOME SYMBOL]/path/to/file_or_directory

Where SOME SYMBOL could be !, |, =, etc?

**Comment by arvidjaar** [comment]
> What is the recommended best practice now to implement a service that should run once depending on a file?

Make it `RemainAfterExit=true`? Path is checked when service changes state, as long as your service remains active it won't be started again.

**Comment by egtvedt** [comment]
@arvidjaar thank you for the hint, tested and this works well. One could argue the oneshot should have been a RemainAfterExit=true service anyway. So, still able to setup all services as before, no need for additional arguments I can think of.
