### ISSUE TITLE
systemd-journald fails to connect to notify socket with SELinux and dracut

### ISSUE THREAD

**Issue by KrissN** [systemd/systemd#16714]
**systemd version the issue has been seen with**
> 245 (both in initrd and rootfs)

**Used distribution**
 > Gentoo

**Expected behaviour you didn't see**
 > System starts normally and a login prompt appears

**Unexpected behaviour you saw**
 > System does not start and hangs indefinitely trying to start the `systemd-journald` and `systemd-udevd`

**Steps to reproduce the problem**

1. Install Gentoo with SELinux and systemd
2. Install latest upstream SELinux reference policy
3. Build initramfs using dracut
4. Try to start the system SELinux in enforcing mode

The problem I'm observing is related to the systemd notify socket. When starting `systemd-journald` it will fail and complain that it is unable to connect to the notify socket:

> systemd-journald[698]: Failed to connect to notify socket: Permission denied

This is because the socket is incorrectly labelled:

> audit: type=1400 audit(1597230143.334:32): avc:  denied  { sendto } for  pid=698 comm="systemd-journal" path="/run/systemd/notify" scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket

The actual label is `system_u:system_r:kernel_t:s0`, while it should be `system_u:object_r:init_runtime_t:s0`. Note that this is not a SELinux policy problem, as it contains a proper file context entry for this file. This is also confirmed by the fact that the system starts with a workaround applied, as explained further in the report.

After investigating this I have found, that the mislabelling is due to the fact, that the socket is created by the `systemd` instance running in the initrd. At the time of its execution the SELinux policy is not loaded, hence the right label is not known. At this stage it doesn't matter anyway, as no policy is enforced.

When the system switches execution to the main systemd from the target root filesystem, the notify socket is closed, but not removed from `/run/systemd`.

Once the main systemd starts all the services, `systemd-journald` is started. It tries to connect to the notify socket seeing that it exists, but unfortunately it fails due to permission violation and exits, causing an avalanche effect on the system start-up.

To prove my theory I have performed an experiment, which involved running the main systemd through a wrapper script, which removes `/run/systemd/notify` and executes systemd. With this script included in the boot chain the system started fine in SELinux enforcing mode.

So now comes the question where the true problem is and where to fix it. The was I see it, we could:

1. Clean-up `/run/systemd/notify` (and possibly other files) before handing over control to the main systemd.
2. Force a relabel of `/run/systemd/notify` (and possibly others) once the SELinux policy is loaded.
3. Allow `sd_notify` to ignore permission violation errors when trying to open the notify socket.

Personally I'd opt for option 1, but since I'm aware, that systemd is a complex machinery and simple questions may not necessary have simple answers, I've taken the liberty to open this bugreport to hear your opinion and work on a proper fix.

**Comment by poettering** [comment]
We already relabel `/dev/`, `/dev/shm/`, `/run/` recursively after loading the policy. See `src/core/mount-setup.c`, the beginning of `mount_setup()`.

**Comment by KrissN** [comment]
> We already relabel `/dev/`, `/dev/shm/`, `/run/` recursively after loading the policy. See `src/core/mount-setup.c`, the beginning of `mount_setup()`.

Yes, I remember that - I've actually put my dirty fingers in that code some time ago.

I'll add some verbose messages there to check if we don't have any hidden problems in that code.

**Comment by KrissN** [comment]
So, the realabelling code works, but there is interesting stuff. `mount_setup` is relabelling `/run/systemd/notify` from `system_u:object_r:tmpfs_t:s0` to `system_u:object_r:init_runtime_t:s0`, which is the correct target label for this socket.

However the SELinux deny errors mention the context `system_u:system_r:kernel_t:s0`. Is there some namespace weirdness going on here?

**Comment by poettering** [comment]
so my educated guess is this: in order not to lose notify msgs from services that finish asynchronously during the initrd→host transition we leave the sd_notify listening socket open and just pass it over from pid 1 in the initrd to the pid 1 of the host. since the fd remains opened I guess the original label applies, not the one from the host.

not sure what fedora does here, maybe they just accept that the original label applies and allow that.

**Comment by KrissN** [comment]
Yes I think it starts to make sense now. It may be that they have just added a bunch of `kernel_dgram_send()` for each of the affected domains and called it a day.

I think, that you may be right, that the socket label is set once the socket is created and bound and from that point on relabelling the directory entry has no effect.

I have looked around the kernel and I didn't find a way to relabel an already open socket, so unless systemd could affort to reopen this socket in order to set a proper context on it, it looks like it we will have to live with `kernel_dgram_send()`.

**Comment by poettering** [comment]
@KrissN it might be possible to relabel it via the /proc/self/fd/X pseudo symlink that refers to the inode behind the open socket.

**Comment by KrissN** [comment]
Nope, that doesn't work and after browsing through the kernel code I haven't had high hopes about this method to be successful.

The way the kernel works currently is that it actually completely ignores the label on the filesystem, which points to the UNIX socket. When the socket is created, the kernel initializes the security context of the socket handle to the context of the process that created it. As said before - there is no way to alter that during the lifetime of this kernel object - there is simply no code in the kernel that allows to do this.

This means that a UNIX socket has actually two levels of security labelling:

1. Directory entry level (`sock_file` class)
2. Socket object level (`unix_dgram_socket` class)

Based on the above I think that from a security PoV giving all security domains, who wish to use `Type=Notify` access to send datagrams to kernel sockets is not a problem, as proper access to the socket will be additionally guarded at the directory entry level. It's only a bit unfortunate, that it has to be worked around this way, but I guess unless a proper API is added at the kernel level there is no better choice.

**Comment by DemiMarie** [comment]
Another approach is to keep the old socket open, but atomically rename the new socket on top of it.  No messages would be lost.

**Comment by poettering** [comment]
I understand that this can be closed hence, any further fix needs to take place in the kernel. Closing hence

(If I  misunderstood, speak up and we can reopen)

**Comment by DemiMarie** [comment]
Would the solution I mentioned earlier work?

**Comment by poettering** [comment]
Sorry, didnt see that comment. 

Not sure if that could work if people called connect() on their client socket since that probably pins the old socket and wont get updated by the one behind the new inode.

**Comment by poettering** [comment]
> Not sure if that could work if people called connect() on their client socket since that probably pins the old socket and wont get updated by the one behind the new inode.

If it does work (though I don't expect it to) and this helps, please send a PR, we'll certainly merge it if good. (but for all selinux stuff we need contributed patches, we are not selinux gurus enough to do this work ourselves)

**Comment by Eng-Fouad** [comment]
This worked for me:

> semanage permissive -a systemd_notify_t
