### ISSUE TITLE
Only syntax verify - don't actually try to run 

### ISSUE THREAD

**Issue by fxfactorial** [systemd/systemd#16730]
I found `systemd-analyze verify`  which is great but it actually tries running the file. 

that's too much - I only need it to validate that the .service file is syntactically correct, not whether it can run or not, somewhat similar to this issue

https://github.com/systemd/systemd/issues/15342

**Comment by poettering** [comment]
it does not try to run the unit file. it only validates what it is spelled out in it. See docs.

**Comment by fxfactorial** [comment]
Okay I would appreciate it if you didn't close issues before at least 1 round trip with OP, could give the benefit of doubt to issue opener that I did look at docs. 

```
> systemd-analyze verify hyegar.service 
/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file accordingly.
/lib/systemd/system/docker.socket:6: ListenStream= references a path below legacy directory /var/run/, updating /var/run/docker.sock → /run/docker.sock; please update the unit file accordingly.
Failed to bind to varlink socket: Address already in use
Failed to set up Varlink server, ignoring: Address already in use
snap-gtk\x2dcommon\x2dthemes-1506.mount: Unit is bound to inactive unit dev-loop15.device. Stopping, too.
snap-snap\x2dstore-415.mount: Unit is bound to inactive unit dev-loop13.device. Stopping, too.
snap-telegram\x2ddesktop-2064.mount: Unit is bound to inactive unit dev-loop9.device. Stopping, too.
snap-gnome\x2d3\x2d34\x2d1804-33.mount: Unit is bound to inactive unit dev-loop17.device. Stopping, too.
snap-gtk\x2dcommon\x2dthemes-1502.mount: Unit is bound to inactive unit dev-loop7.device. Stopping, too.
snap-core20-634.mount: Unit is bound to inactive unit dev-loop5.device. Stopping, too.
snap-gnome\x2d3\x2d26\x2d1604-100.mount: Unit is bound to inactive unit dev-loop4.device. Stopping, too.
snap-snap\x2dstore-467.mount: Unit is bound to inactive unit dev-loop14.device. Stopping, too.
snap-solium-555.mount: Unit is bound to inactive unit dev-loop18.device. Stopping, too.
snap-telegram\x2ddesktop-1708.mount: Unit is bound to inactive unit dev-loop11.device. Stopping, too.
hyegar.service: Command /root/shard-3-worker/harmony is not executable: Permission denied
(ERROR)-(Exit Code 1)-(General error)
```

Here it is running code and tried to run the binary - I don't need that at all, just needed a syntax check.

**Comment by poettering** [comment]
What is it precisely running? I don't see what you mean? It just tells you that `access("/root/shard-3-worker/harmony", X_OK)` failed.

What makes you think anything was executed here?

**Comment by poettering** [comment]
The man page explicitly says: "The following errors are currently detected: … · commands listed in ExecStart= and similar which are not found in the system or not executable."

we event document what we do...

**Comment by fxfactorial** [comment]
okay - thank you for the reply - I concede, you're right.
