### ISSUE TITLE
Systemd-udevd: worker processing is taking a long time / killed.

### ISSUE THREAD

**Issue by hercc82** [systemd/systemd#16746]
**systemd version the issue has been seen with**
245.5-r1 (from gentoo repository)

**Used distribution**
gentoo amd64, kernel 5.4.58-gentoo

**Expected behaviour you didn't see**

**Unexpected behaviour you saw**
systemd-udevd[2311]: sfX: Worker [3783] processing SEQNUM=3192 is taking a long time
systemd-udevd[2311]: sfX: Worker [3783] processing SEQNUM=3192 killed

Usb stops working. See steps to reproduce for details.

**Steps to reproduce the problem**

Gentoo 1:
Udev 245.5-r1
Kernel 5.4.48

Gentoo 2:
Udev 238
Kernel 4.9.95

Please notice both Gentoo installations run on the same hardware machine.

Gentoo 1:
1. Insert the usb pendrive into the slot.
2. Wait until it is detected (observation with the help of dmesg -w).
3. Take out the usb pendrive from the slot.
4. Repeat steps 1-3 x times. I have tried with multiple pendrives.
5. Usb pendrive cannot be detected any more. Amperage is 0 (measured with a logilink measuring device). Dmesg shows the following issue:
systemd-udevd[2311]: sfX: Worker [3783] processing SEQNUM=3192 is taking a long time
systemd-udevd[2311]: sfX: Worker [3783] processing SEQNUM=3192 killed
Putting it in and taking it out again doesn't help. At least a couple of slots stop working at once. Probably all from a particular controller. 

I can reproduce it pretty quickly. It takes about 1-5 minutes to reproduce. I can't link the problem to a specific pendrive. I think any might cause it.

Gentoo 2:
The problem described in Gentoo 1 cannot be reproduced. I have tried over half an hour and I wasn't able to hang usb. Dmesg kept showing me the connection and disconnection and the pendrive was powered all the time. 

I also described the problem on the gentoo forum. https://forums.gentoo.org/viewtopic-t-1117598.html

If you need additional information and logs, please write me what exactly and how to create them. My knowledge of linux is limited. I'm also not sure if the problem lies with kernel or udev. If you help me figure this out, it'll be fine.

Thx.

**Comment by poettering** [comment]
So what is that worker 3783 actually doing? what does "ps xawuf" show in relation to that process and its children?

Most likely you just have a udev rule installed by some package that runs some binary that is excessively slow. Can't tell you what that is... ps likely gives you a hint.

**Comment by poettering** [comment]
is this a systemd system? or some other init system? you only say something about udev, not systemd.

If it's not systemd then please contact your downstream distro for help.

**Comment by hercc82** [comment]
> So what is that worker 3783 actually doing? what does "ps xawuf" show in relation to that process and its children?

ps after reboot without a connected flashdrive
https://pastebin.com/fbbcmw2L

ps after connecting a flashdrive and after worker message (systemd-udevd[2313]: sdf: Worker [3969] processing SEQNUM=3264 is taking a long time)
https://pastebin.com/TM1wt6Qv

ps after processing killed and flashdrive still connected (systemd-udevd[2313]: sdf: Worker [3969] processing SEQNUM=3264 killed)
https://pastebin.com/kAES5uQr

ps after removing flashdrive:
https://pastebin.com/twSkKjen

root      3969  0.0  0.0  13976  5144 ?        D    17:08   0:00  \_ /lib/systemd/systemd-udevd

 D    uninterruptible sleep (usually IO) - Is that something I should be worried about?


> is this a systemd system? or some other init system? you only say something about udev, not systemd.
> 
> If it's not systemd then please contact your downstream distro for help.

I use the default gentoo init system. It is open-rc. sys-apps/systemd is not installed on my system. However, sys-fs/udev is. I assumed that the systemd community is responsible for the udev package and if I have any problems with it, I can turn here.

**Comment by poettering** [comment]
This is not a systemd system. Please bring this up with the gentoo people. This is a systemd bug tracker. 

> I use the default gentoo init system. It is open-rc. sys-apps/systemd is not installed on my system. However, sys-fs/udev is. I assumed that the systemd community is responsible for the udev package and if I have any problems with it, I can turn here.

Well, we semi-support udev outside of systemd, but for stuff like this please ask the gentoo people for help. running udev without systemd is legacy stuff. If downstreams use things that way they really should help you first, and if they find something report it back to us, but we cannot possibly help you with such obsolete stuff upstream as we don#t run this our own. support for non-systemd udev relies on contributions from downstream, and that's about it.

Hence, please talk to the gentoo people, they'll let us know if there's an actual problem upstream.

But again, udev tells you that some worker hangs. figure our why. try to get a backtrace of the offending worker. my guess: driver issue or weird rule installed.

Anyway, closing here. Please take this up to gentoo first, and let them escalate this back if there's actually something to fix in systemd upstream.
