### ISSUE TITLE
 top shows that the systemd-logind and dbus-daemon processes occupy nearly 100% of the CPU resources

### ISSUE THREAD

**Issue by xufuhai** [systemd/systemd#16743]
**systemd version the issue has been seen with**
>
219.42.el7_4.4 

**Used distribution**
 > centos 7.4

**Expected behaviour you didn't see**
 > system-logind and dbus should not occupy one cpu nearly 100% and there should be no watchdog behavior in system-logind（log as "systemd-logind.service watchdog timeout (limit 1min)!" ）

**Unexpected behaviour you saw**
 > huge closing sessions almost 30w+ appeared in the /run/systemd/sessions directory

**Steps to reproduce the problem**
the issue machines have the huge multi-sessions connections from remote login via ssh and crond tasks in localhost with 5min cycles. and I could not find the stable approach to reproduce the issue until now:( 

I searched the issue with google and centos bugzilla, then found that the issue is a know issue as below link:

https://bugs.centos.org/view.php?id=14278

the issue has been resolved and needs to update the systemd version to solve the issue, but I could not update the systemd to the newest version because the fixup patches not related to the issue are so much, must consider compatibility and  avoid bringing new issue for centos 7.4. 
We have so much online machine using systemd 219.42.el7_4.4, update to newest is difficult for us.

The best way for us is to backport the fixup patches to the 219.42.el7_4.4, So my question is could you please help me: 

**_1. provide us the fixup patches only for solving the above issue, we can backport the patches to our issue version?
2. provide us the stable approach to reproduce this issue?_** 

btw, we think the issue is not same with https://github.com/systemd/systemd/issues/1961
we had checked the above patches which have been merged into 219.42.el7_4.4 version

Thanks for taking the time～

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.

**Comment by xufuhai** [comment]
hi poettering, 
I had found four maybe fixup patches as below which almost have relationship with the issue.
Could you please help me make sure whether these patches are valid to the issue?) 
if these are right, we will backport to our systemd/dbus version.
thx!

systemd：
- core: use an AF_UNIX/SOCK_DGRAM socket for cgroup agent notification (d8fdc62037b5) 
dbus：
- Only read one message at a time if there are fds pending (892f084eeda0)
- bus: Fix timeout restarts (529600397bca)
- DBusMainLoop: ensure all required timeouts are restarted (446b0d9ac75a)
