### ISSUE TITLE
Don't make zstd the default journal compression (yet)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#16749]
In v246, journald gained support for zstd compression.
If systemd is compiled with zstd support, new journal log files will default to use zstd.
While having support for zstd is nice, I think, systemd should continue to use lz4 as default compression for a while, until all major distros ship a new enough version of systemd with zstd support.
Otherwise you might end up generating journal files which can't be read from other distros, live cds etc.

**Comment by mbiebl** [comment]
Otherwise, users will just see an error message like that
```
Journal file /var/log/journal/64f9b494837d480e9ecd81ea0cef1551/system@5cd966d8e5d24653b114e239c300135e-00000000000e3792-0005ac0f7ccf0a84.journal uses an unsupported feature, ignoring file.
```
without really knowing, why journalctl refuses to open that journal file.

**Comment by poettering** [comment]
Nah. This is misleading.

We updated the format for other reasons (hardening, see NEWS file). We then made the zstd change at the same time in order not to have more boundaries where we make new files incompatible.

While the value of zstd over lz4 might be minimal, the hardening stuff matters, and hence I think we should stay with it.

**Comment by poettering** [comment]
the unsupported feature you see in that log msg is likely the hardening, not the zstd thing

**Comment by mbiebl** [comment]
urgh, this is unfortunate. Can I change journald to support reading those new type journal file while still producing files that are compatible with pre v246 systemd versions?

**Comment by mbiebl** [comment]
If I'm reading the NEWS entry correctly, SYSTEMD_JOURNAL_KEYED_HASH=false only affects the hardening, not the default compression

**Comment by poettering** [comment]
journald always uses the "best"/"newest" compression algorithm when writing journal files, while it is able to read files of all supported algorithms.

There's currently no knob to write files with an "older" compression algorithm while being able to read the new files.

The hardening is a good thing, I would not turn that off..

**Comment by mbiebl** [comment]
Ok, I'll patch that downstream then.
It is not uncommon that users run a combination of different Debian versions, say a Debian buster base system and bullseye containers. Not being able to read the journal files is not a good user experience.

**Comment by mbiebl** [comment]
I have something like this in mind:
```
Index: systemd-246.1/src/journal/journal-file.c
===================================================================
--- systemd-246.1.orig/src/journal/journal-file.c	2020-08-16 21:36:36.000000000 +0200
+++ systemd-246.1/src/journal/journal-file.c	2020-08-17 14:17:32.758779884 +0200
@@ -3375,10 +3375,10 @@
                 .prot = prot_from_flags(flags),
                 .writable = (flags & O_ACCMODE) != O_RDONLY,
 
-#if HAVE_ZSTD
-                .compress_zstd = compress,
-#elif HAVE_LZ4
+#if HAVE_LZ4
                 .compress_lz4 = compress,
+#elif HAVE_ZSTD
+                .compress_zstd = compress,
 #elif HAVE_XZ
                 .compress_xz = compress,
 #endif
@@ -3396,7 +3396,7 @@
         if (r < 0) {
                 if (r != -ENXIO)
                         log_debug_errno(r, "Failed to parse $SYSTEMD_JOURNAL_KEYED_HASH environment variable, ignoring.");
-                f->keyed_hash = true;
+                f->keyed_hash = false;
         } else
                 f->keyed_hash = r;
 
```

**Comment by keszybz** [comment]
Changing the default compression is OK. I think it'd be reasonable to patch out meson setup to let the default configuration be selected at configuration time. Defaulting to keyed_hash=false is not good though.

**Comment by mbiebl** [comment]
This will be temporary, for one release cycle, to make the upgrade smoother.

**Comment by poettering** [comment]
As I understand we can close this now? Debian solved this downstream? For the security reasons I don#t think we should go back to the old format upstream.

Closing. (Or did I miss something? If so, please report back)
