### ISSUE TITLE
systemd-machine-id-setup: running debootstrap inside KVM creates identical /etc/machine-id

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#16758]
I have a test VM based on QEMU/KVM.
Inside that VM, I ran `debootstrap` to create a couple of test containers/chroots.
While doing that, I noticed, that all chroots had the same `/etc/machine-id`.
debootstrap does properly mount /sys and /proc inside the chroot during the setup and because of that I see the following when systemd is installed:
```
Initializing machine ID from KVM UUID.
```
The end result is, that all chroots have an identical `/etc/machine-id`

**Comment by mbiebl** [comment]
`systemd-machine-id-setup` should not use `/sys/class/dmi/id/product_uuid` when run inside a chroot/container.

**Comment by poettering** [comment]
we only read that file when we run in kvm and not in a container. see:

https://github.com/systemd/systemd/blob/master/src/core/machine-id-setup.c#L47

**Comment by mbiebl** [comment]
Since /sys is bind-mounted, systemd-machine-id-setup thinks it runs directly in KVM. There is probably a `running_in_chroot()` missing.
