### ISSUE TITLE
Allow passing raw udev PROGRAM results to SYSTEMD_WANTS

### ISSUE THREAD

**Issue by JakubVanek** [systemd/systemd#16760]
**Is your feature request related to a problem? Please describe.**
This is a continuation of https://github.com/systemd/systemd/issues/16735. The core of the problem is that when using a systemd-encoded string containing a backslash (e.g. `ev3-ports@ev3\x2dports:in4.service`) in the unit name, `SYSTEMD_WANTS` from udev rightly requires doubling of the backslash. However, it is not possible to double the backslash from inside PROGRAM, as the non-last backslash is [always](https://github.com/systemd/systemd/blob/bfeb370abcd9a5468ef565a32189d5593a40ce19/src/udev/udev-rules.c#L1686) removed in `util_replace_chars()`. For example, it turns `ev3-ports@ev3\\x2dports:in4.service` into `ev3-ports@ev3_\x2dports:in4.service` (at least in v241, but I think that `master` should behave identically).

Interestingly, in v241 using `OPTIONS+="string_escape=none"` should prevent the double backslash from being removed, but I couldn't reproduce that on Debian Buster.

**Describe the solution you'd like**
I think that introducing a new option like `program_result_escape=none` would be an ideal solution.

**Describe alternatives you've considered**
There is the possibility of relying on https://github.com/systemd/systemd/commit/dcebc9bae4dcc3e844f01558c6127fc0d8745c8e as an alternative to filling the instance name manually. This may not work in all situations though.

**Comment by keszybz** [comment]
The original rule was
```
SUBSYSTEMS=="lego", ENV{DEVTYPE}=="ev3-uart-host", ACTION=="add", TAG+="systemd", \
    PROGRAM="/bin/systemd-escape $env{LEGO_ADDRESS}" \
    ENV{SYSTEMD_WANTS}="ev3-uart@$result.service", \
    ENV{SYSTEMD_ALIAS}="/sys/subsystem/lego/devices/ev3_uart_host_$env{LEGO_ADDRESS}"
```
What about adding a new way to access the result, e.g. $env{RESULT} that would be always escaped?

**Comment by yuwata** [comment]
Now I am very confused. Why not to simply assign like `ENV{SYSTEMD_WANTS}="ev3-uart@$env{LEGO_ADDRESS}.service"`?

**Comment by keszybz** [comment]
Righto, that's much better than my suggestion.

**Comment by yuwata** [comment]
Closing. If the suggestion above does not work, then feel free to request to reopen this page.

**Comment by CarloWood** [comment]
@JakubVanek Excellent work! I was under the impression that it was preferred to keep the weird behavior of SYSTEMD_WANTS to demand escaping backslashes, but it is definitely more clean if things are simply the same on the commandline, when using SYSTEMD_WANTS, as well as for the output of PROGRAM and IMPORT: just leave single backslashes alone everywhere. It would be perfectly acceptable to only leave "\x[0-9][0-9]" alone, but it seems confusing to do so.

PS I just tried hard to find anything with Google that refers to / documents the use of SYSTEMD_WANTS, and the only things I can find are either posts from more than 9 years ago, people not using `@`, or people using it to pass `%k`, `%p`, `$name` or `$devnode`. I can't find ANYONE talking about having to escape backslashes or doing anything special. So, I'm inclined to think that fixing the bug won't have a large impact on current configurations.

**Comment by CarloWood** [comment]
@JakubVanek Perhaps it is not necessary to add the `program_result_escape=none` option? I assume that the purpose of filtering the output of PROGRAM is to make sure that the result is not an illegal string, as in: it must be a legal systemd-escaped string. That functionality is best kept and won't get in the way once SYSTEMD_WANTS accepts legal systemd-escaped strings again (aka, `foo\x2dbar`, instead of `foo\\x2dbar`). Before I said that only accepting backslashes if they are part of "\x[0-9][0-9]" would be confusing, but really it isn't: if backslashes in systemd escaped strings only can occur in that form, then the PROGRAM filter probably should replace anything else with an underscore.

**Comment by JakubVanek** [comment]
Thank you!

> I was under the impression that it was preferred to keep the weird behavior of SYSTEMD_WANTS to demand escaping backslashes

This was indeed the initial consensus in https://github.com/systemd/systemd/issues/16735 . However, I think that the fact that systemd in the past used not to escape the backslashes is a compelling reason to change the behaviour back to something compatible.

> PS I just tried hard to find anything with Google that refers to / documents the use of SYSTEMD_WANTS, and the only things I can find are either posts from more than 9 years ago, people not using @, or people using it to pass %k, %p, $name or $devnode. I can't find ANYONE talking about having to escape backslashes or doing anything special. So, I'm inclined to think that fixing the bug won't have a large impact on current configurations.

This sounds good. I now also tried to do a quick GitHub code search (https://github.com/search?q=PROGRAM+SYSTEMD_WANTS+%40+path%3A*.rules&type=code) and it seems that the remaining people are still relying on `PROGRAM` + `systemd-escape` the way it worked in systemd <=v232.

> Perhaps it is not necessary to add the program_result_escape=none option?

I agree; I was just somewhat curious about how difficult would it be to add that too.

> I assume that the purpose of filtering the output of PROGRAM is to make sure that the result is not an illegal string, as in: it must be a legal systemd-escaped string.

I think it's that and also a bit of security (in the history, the relevant function used to be called `replace_untrusted_chars`, [ref](https://github.com/systemd/systemd/blame/c2666405031cfda5720ddb9ecd88c1b476babc2a/udev_rules.c#L779C26-L779C26)).

Agreed with the rest.
