### ISSUE TITLE
Minor issue regarding https://github.com/systemd/systemd/blob/master/man/systemd.service.xml

### ISSUE THREAD

**Issue by ZjYwMj** [systemd/systemd#16775]
This is a minor bug regarding [master/man/systemd.service.xml](https://github.com/systemd/systemd/blob/master/man/systemd.service.xml). I don't know if the problem is with the source xml file, or with the tools that renders it. I can see it at 2 different places, though it could be that one of the two uses tools that are also used by the other.
line 220 of the xml source reads:
`<option>main</option>.</para></listitem>`
Note the period, which is supposed to be a full stop to mark an end of sentence.
1. I can not see that period at https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options. Manually searching for the word forcibly in the link helps.
2. Traditional man tools renders it in the wrong way. For example, it is translated to 
```
\fBnone\fR, it will be forcibly set to
\fBmain\fR
.RE
\&.
```
Here, `\&.` should probably be before `.RE`, and this is not enough for correct rendering. 
```

**Comment by poettering** [comment]
Already fixed by 6b49257f6b92c1bcdf02ca0e896009da36ed9bb0
