### ISSUE TITLE
Support OnFailure= for targets

### ISSUE THREAD

**Issue by geissonator** [systemd/systemd#16778]
**Is your feature request related to a problem? Please describe.**
https://github.com/systemd/systemd/issues/14142 has some background on this.

Basically, this feature used to work with older versions of systemd, but was explicitly disabled within more recent systemd releases.

The basic use case we have over in OpenBMC is we have two targets which encapsulate the services needed to boot a server. There's the first target, which does everything needed to apply power to the server, then another target which depends on this power on target which has all the services needed to start the host firmware (i.e. BIOS/UEFI/KVM/OS). 

There can be quite a few services required for these targets as these are large enterprise class servers that need a lot of different levers pulled to boot. 

We had a nice simple design, utilizing OnFailure= within these targets to ensure a recovery target was started if any of the Required services within the targets failed. For example, if the target responsible for powering on the chassis fails, start the power off target to ensure the system gets back in a known state. Without this support, we now have two issues:
- We don't recover on target failures
- We actually keep trying to boot even if the server fails to power on (the dependency of the boot target on the power on target does not seem to be affected by the first target failing)

**Describe the solution you'd like**
I'd like to see the pass/fail state of the target be a && operation of all the statuses of the services of which it requires and for the OnFailure to work within systemd targets.

**Describe alternatives you've considered**
It seems like the only other approach is to have each individual service within the targets have a OnFailure= within them. This seems redundant and error prone given our design of allowing different vendors to plug and play their own services into these targets.

**Comment by keszybz** [comment]
This is already true (again) since 94d1ddbd7cd15b1073757eb5ae0645c83f0b414c.
