### ISSUE TITLE
RFE: x-systemd.not-device-bound

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#16801]
**Is your feature request related to a problem? Please describe.**

I have some multi-device Btrfs filesystems, which are mounted from fstab. The filesystems use Btrfs profiles which can tolerate a device being removed (e.g. for replacement with a larger one).

So upon removing a disk, the filesystem could remain mounted (possibly in degraded state) from the remaining disks – but systemd automatically unmounts the filesystem anyway, because it's a fstab entry and therefore device-bound. Then I have to manually mount it again. (Then it gets unmounted again, I run `systemctl daemon-reload`, and _then_ I can manually mount it again.)

This is probably not solvable using just systemd dependencies, since they're "requires all" and not "requires at least one of".

**Describe the solution you'd like**

As "x-systemd.device-bound" is currently implied for fstab entries, I would like to use the opposite option and explicitly mark certain fstab mountpoints as _not_ device-bound.

**Describe alternatives you've considered**

There have been several other issues about this, but none of them resulted in any practical change.

**Comment by poettering** [comment]
we could certainy beef up `x-systemd.device-bound` to take a parameter: `=auto` would be equivalent to the current behaviour. `=yes` would mean we'd force device bound logic, like what currently happens when you specify it, and `=no` would be what you are asking for.
