### ISSUE TITLE
systemctl is not working with chroot

### ISSUE THREAD

**Issue by adityat3** [systemd/systemd#16802]
Inside an embedded linux box, systemd version the issue has been seen with 243

tmp_dir=$(mktemp -d)
mkdir $tmp_dir/upper
mkdir $tmp_dir/work
mkdir $tmp_dir/merged
mount -t overlay overlay -olowerdir=/,upperdir=$tmp_dir/upper,workdir=$tmp_dir/work $tmp_dir/merged/
mount --bind /run/ $tmp_dir/merged/run/
mount --bind /proc/ $tmp_dir/merged/proc/
mount --bind /dev/ $tmp_dir/merged/dev
mount --bind /sys/ $tmp_dir/merged/sys
mount --bind /var/data/ $tmp_dir/merged/var/data/
mount --bind /var/opt/ $tmp_dir/merged/var/opt/
mount --bind /var/sys/ $tmp_dir/merged/var/sys/
mount --bind /var/run/ $tmp_dir/merged/var/run/
mount --bind /dsp/ $tmp_dir/merged/dsp
mount --bind /firmware/ $tmp_dir/merged/firmware/
mount --bind /opt/ $tmp_dir/merged/opt/
chroot $tmp_dir/merged/ /bin/sh -c "systemctl"

The last command should list all the UNITs with chroot

But it gives below stdout:
systemctl: 
systemctl: Running in chroot, ignoring request.

Same behavior observed for 
chroot $tmp_dir/merged/ /bin/sh -c "systemctl --state=running"
Expected: should list all running units with chroot
Actual:
systemctl: 
systemctl: Running in chroot, ignoring request.

**Comment by poettering** [comment]
This is on purpose: chroot environments are typically used in "offline" mode, i.e. they cannot run systemd inside them, as they have no concept of PID 1. Hence systemctl automatically supprresses any comunication with PID 1 when run in a chroot.

See https://systemd.io/ENVIRONMENT/ for details on how you can override this logic.

In general: if you want to run a bootable chroot environment, then better use containers, i.e. systemd-nspawn is dead-easy to use like that.
