### ISSUE TITLE
systemd-homed keeps corrupting gnome-keyring

### ISSUE THREAD

**Issue by rautesamtr** [systemd/systemd#16814]
**systemd version the issue has been seen with**
246.2-2

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
Have a working gnome-keyring when using systemd-homed

**Unexpected behaviour you saw**
Randomly the gnome login keyring seems to be corrupting. This is noticeable when chromium keeps asking to reenter the keyring password and trying to change the password of the login keyring keeps rejecting the correct password. Deleting the login keyring and letting it get recreated fixes the issue temporarily.

**Steps to reproduce the problem**
Use systemd-homed on Arch Linux with Gnome and Gnome keyring. Sadly i can't yet determine when the corruption or why it happens since it seems randomly and i only notice the corruption on a reboot.
I use systemd-homed with btrfs subvolume as storage. At least one other person seems to have the same problem. 
* https://www.reddit.com/r/archlinux/comments/i05el0/policykit_systemdhomed_not_playing_nicely_together/g24d9fs?utm_source=share&utm_medium=web2x&context=3
* https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/59

**Comment by jekanev** [comment]
Same problem gnome-keyring login keyring corrupted cant unlock old password not work.

**Comment by poettering** [comment]
gnome keyring seems to be "corrupting"? what does that mean? Are you talking about on-disk corruption? Can you elaborate?

**Comment by rautesamtr** [comment]
The login keyring is the one that get's automatically unlocked on login if it has the same password as your login. Chromium uses the login keyring for its password manager. So being asked continually for the password for the keyring without it properly unlocking suggest it is corrupted. It also isn't possible to unlock or change the password within seahorse since the login keyring isn't accepting the proper password.

It probably is a file corruption since the keyring resides in `~/.local/share/keyrings`. And only deleting `login.keyring` and `user.keystore` in said folder fixes the problem since they get recreated on login.

Is systemd-homed interacting in any way directly with the keyring?

Strange enough i had the issue on three different machines running arch with systemd-homed, two migrated home folders and one freshly created. All use subvolume as storage mechanism. I have to admit, that the corruption hasn't occurred anymore since opening this ticket. Maybe it was fixed with 246.3? Not sure if i should close this ticket for now or not, since there are other people reporting the same issue.

**Comment by poettering** [comment]
Still wondering: what do you mean by "corrupting"?

**Comment by viggy96** [comment]
This could be related, I've noticed that every time I accidentally enter my password incorrectly on the login screen, once I do finally login, a GNOME keyring dialog comes up to ask for my password. The keyring password seems to always be changed to the typo'd password. I fix this by "changing" the keyring password back to the correct password.

**Comment by poettering** [comment]
Still wondering, what "corrupting" is supposed to mean? That the cached pw is forgotten? Or something worse? I can't do anything about this if it's not clear what the issue is supposed to be...

**Comment by viggy96** [comment]
@poettering Have you been unable to replicate the issue?

**Comment by poettering** [comment]
My daily work user account is managed by homed, and I use GNOME (on Fedora), and evertyhing works fine here.

I am still puzzled what "corrupting" is supposed to mean. Unless someone can answer that there's little we can do. "corrupting" is not a proper description of what happens here. Please explain exactly what the issue is, and what "corrupting" is supposed to mean here?

**Comment by viggy96** [comment]
I guess I can't speak for the OP, but I think that somehow the login keyring password is getting corrupted somehow, or otherwise is being changed somehow such that it is changed randomly without the user expressly deciding to change said password.

**Comment by poettering** [comment]
hmm, what? you are telling me that homed changes the gnome keyring password for you? that's highly unlikely...

I am sorry, but I am inclined to close this issue, since I really don't grok what the issue is supposed to be here, what "corrupting" is supposed to mean

**Comment by viggy96** [comment]
@poettering With some further trying out of stuff, I don't think that its systemd-homed that's the issue. It seems to be more a gnome keyring daemon issue. If I attempt login with an incorrect password, then the correct one, I get popups from gnome-keyring asking for the password. I just hit escape on this dialog. On restarting the machine, and logging in with the correct password the first time, I don't get any dialogs from gnome-keyring.

@rautesamtr @jekanev I suggest that this issue be pursued here instead: https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/59

**Comment by rautesamtr** [comment]
@viggy96 seems you are right, i can reliably reproduce your issue. Closing this one for now.

@poettering sorry for using the therm corruption, i rather reused it after finding posts suggesting the keyring is corrupt if it didn't unlock with the correct password. it looks like in this case it really is a pam issue.

**Comment by cruegge** [comment]
Sorry to revive this, but I've encountered a similar issue (cruegge/pam-gnupg#24) in pam-gnupg, a pam module to unlock gpg-agent similar to what gnome-keyring does, and I think I know what causes it.

The thing is that if the first password is incorrect, pam-systemd-homed [produces another prompt](https://github.com/systemd/systemd/blob/07ccf434e77b17b20d773ce8b2637083cd4fdafc/src/home/pam_systemd_home.c#L310) to get it, but then does not set the `PAM_AUTHTOK` item, which is what both pam-gnupg and gnome-keyring use to unlock their respective keyrings. Therefore, they still get the mistyped password.

Moreover, I think – although I haven't tested it, so this is a bit speculative – gnome-keyring then notices that the password does not unlock the keyring, asks for the correct one and then, assuming the password has changed, set the keyring's password to the assumed-to-be-new mistyped one, thereby “corrupting” it.

Is there a specific reason not to set `PAM_AUTHTOK`, or would it be feasible to add that?
