### ISSUE TITLE
Error blanking a disk with dd

### ISSUE THREAD

**Issue by jonshouse1** [systemd/systemd#16830]
Trying to blank an old laptop disk via a USB adapter got some weird error.

Linux  Mint 20 XFCE

Kernel
Linux jonspc 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 /lib/systemd/systemd --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

Did this
dd if=/dev/urandom of=/dev/sdc bs=8192

I have no idea what the following gobshite means, but I assume some sort of disk error. In the good old days I would have got some sort of meaningful error instead a hung dd and this in the log:

Error was "task systemd-udevd:476 blocked for more than 120 seconds.", here in context.

If something has gone wrong with the disk write then I would expect and error to say so, if nothing has gone wrong then I would expect no messages at all.

 dmesg -T
`[Tue Aug 25 00:52:31 2020] scsi 5:0:0:0: Direct-Access     FUJITSU  MHD2032AT             PQ: 0 ANSI: 5
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: Attached scsi generic sg3 type 0
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] 6354432 512-byte logical blocks: (3.25 GB/3.03 GiB)
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] Write Protect is off
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] Mode Sense: 28 00 00 00
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] No Caching mode page found
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] Assuming drive cache: write through
[Tue Aug 25 00:52:31 2020]  sdc: sdc1
[Tue Aug 25 00:52:31 2020] sd 5:0:0:0: [sdc] Attached SCSI disk
[Tue Aug 25 01:01:01 2020] INFO: task systemd-udevd:476 blocked for more than 120 seconds.
[Tue Aug 25 01:01:01 2020]       Tainted: G           OE     5.4.0-42-generic #46-Ubuntu
[Tue Aug 25 01:01:01 2020] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[Tue Aug 25 01:01:01 2020] systemd-udevd   D    0   476      1 0x00000320
[Tue Aug 25 01:01:01 2020] Call Trace:
[Tue Aug 25 01:01:01 2020]  __schedule+0x2e3/0x740
[Tue Aug 25 01:01:01 2020]  schedule+0x42/0xb0
[Tue Aug 25 01:01:01 2020]  schedule_preempt_disabled+0xe/0x10
[Tue Aug 25 01:01:01 2020]  __mutex_lock.isra.0+0x182/0x4f0
[Tue Aug 25 01:01:01 2020]  ? exact_lock+0x11/0x20
[Tue Aug 25 01:01:01 2020]  __mutex_lock_slowpath+0x13/0x20
[Tue Aug 25 01:01:01 2020]  mutex_lock+0x2e/0x40
[Tue Aug 25 01:01:01 2020]  __blkdev_get+0x78/0x550
[Tue Aug 25 01:01:01 2020]  blkdev_get+0x3d/0x140
[Tue Aug 25 01:01:01 2020]  ? blkdev_get_by_dev+0x50/0x50
[Tue Aug 25 01:01:01 2020]  blkdev_open+0x8f/0xa0
[Tue Aug 25 01:01:01 2020]  do_dentry_open+0x143/0x3a0
[Tue Aug 25 01:01:01 2020]  vfs_open+0x2d/0x30
[Tue Aug 25 01:01:01 2020]  do_last+0x194/0x900
[Tue Aug 25 01:01:01 2020]  path_openat+0x8d/0x290
[Tue Aug 25 01:01:01 2020]  do_filp_open+0x91/0x100
[Tue Aug 25 01:01:01 2020]  ? __alloc_fd+0x46/0x150
[Tue Aug 25 01:01:01 2020]  do_sys_open+0x17e/0x290
[Tue Aug 25 01:01:01 2020]  __x64_sys_openat+0x20/0x30
[Tue Aug 25 01:01:01 2020]  do_syscall_64+0x57/0x190
[Tue Aug 25 01:01:01 2020]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[Tue Aug 25 01:01:01 2020] RIP: 0033:0x7f8e0fa54d1b
[Tue Aug 25 01:01:01 2020] Code: Bad RIP value.
[Tue Aug 25 01:01:01 2020] RSP: 002b:00007ffe1583b060 EFLAGS: 00000246 ORIG_RAX: 0000000000000101
[Tue Aug 25 01:01:01 2020] RAX: ffffffffffffffda RBX: 00007ffe1583b170 RCX: 00007f8e0fa54d1b
[Tue Aug 25 01:01:01 2020] RDX: 00000000000a0800 RSI: 000056182f35c900 RDI: 00000000ffffff9c
[Tue Aug 25 01:01:01 2020] RBP: 000056182f35c900 R08: 000056182e3eb0c0 R09: 0000000000000000
[Tue Aug 25 01:01:01 2020] R10: 0000000000000000 R11: 0000000000000246 R12: 00000000000a0800
[Tue Aug 25 01:01:01 2020] R13: 000056182f38d130 R14: 00007ffe1583b138 R15: ffffffff00000001

`

**Comment by poettering** [comment]
the kernel dump indicates a kernel program. Please report to your distro's kernel maintainers.
