### ISSUE TITLE
ignoreroutes=true still sets default gateway

### ISSUE THREAD

**Issue by Hr46ph** [systemd/systemd#16839]
I saw this:
https://github.com/systemd/systemd/issues/2282

Unless there is an issue with my config (complete paste of every file below), it looks like the bug has been reintroduced somehow.

**systemd version the issue has been seen with**
systemd 246.2-2
systemd-libs 246.2-2
systemd-sysvcompat 246.2-2

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
When using the option IgnoreRoutes=True (or on if that matters) below [DHCP] in the .network file, I expect the default route pushed by DHCP to be ignored.

**Unexpected behaviour you saw**
When using the option IgnoreRoutes=True I do not expect the default route pushed by DHCP to be set.

**Steps to reproduce the problem**
File: eno1.network
```
[Match]
Name=eno1

[Network]
MACVLAN=untagged
VLAN=vlan50
VLAN=vlan60
```
File: mcvlan50.netdev
```
[NetDev]
Name=mcvlan50
Kind=macvlan

[MACVLAN]
Mode=bridge
```
File: mcvlan50.network
```
[Match]
Name=mcvlan50

[Network]
MACAddress=a2:88:fa:b6:a2:0e
IPForward=yes
DHCP=ipv4

[DHCP]
UseRoutes=false
```
File: untagged.netdev
```
[NetDev]
Name=untagged
Kind=macvlan

[MACVLAN]
Mode=bridge
```
File: untagged.network
```
[Match]
Name=untagged
MACAddress=ea:f0:bc:62:c9:69

[Network]
IPForward=yes
DHCP=ipv4
```
File: vlan50.netdev
```
[NetDev]
Name=vlan50
Kind=vlan

[VLAN]
Id=50
```
File: vlan50.network
```
[Match]
Name=vlan50

[Network]
MACVLAN=mcvlan50
```
File: vlan60.netdev
```
[NetDev]
Name=vlan60
Kind=vlan

[VLAN]
Id=60
```

**Comment by yuwata** [comment]
We introduced `UseGateway=` since v246. Please use that option.

**Comment by Hr46ph** [comment]
Thanks, still one simple question though, using `UseGateway=false` without `UseRoutes=false` still sets a default gateway. When using both on false, the gateway is no longer set. Is that expected behavior?

**Comment by yuwata** [comment]
Hmm, that's strange. If `UseGateway=` is explicitly specified, then the setting should be always honored. If `UseGateway=` is not specified, then the value `UseRoutes=` is used to determine whether gateway will be configured or not. So, If you just set `UseRoutes=no`, then both routes and gateway are not configured.

**Comment by Hr46ph** [comment]
I will retest it to make sure it works as intended, I think I might have confused `IgnoreRoutes` with `UseRoutes` (I made this mistake in my original post too, `IgnoreRoutes` in the description but `UseRoutes` in the code).
