### ISSUE TITLE
systemd-tty-ask-password-agent --list behaves wrong

### ISSUE THREAD

**Issue by TheBigLee** [systemd/systemd#16836]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Ubuntu 20.04 LTS

**Expected behaviour you didn't see**
 > When executing the command `systemd-tty-ask-password-agent --list`, the command **should** show a list of pending password requests and exit.

**Unexpected behaviour you saw**
 > When executing the command `systemd-tty-ask-password-agent --list`, the command **is** continously processing pending password requests and never exists (like the `--watch` parameter.

**Steps to reproduce the problem**
Simply running the command `systemd-tty-ask-password-agent --list` should return a empty list and exit and not "watch" the process and never terminate.

I suspect that the issue is in this line: https://github.com/systemd/systemd/blob/master/src/tty-ask-password-agent/tty-ask-password-agent.c#L716 and should probably also include the `ACTION_LIST` 
Something like this probably: 
`return process_and_watch_password_files(arg_action != ACTION_QUERY || arg_action != ACTION_LIST);`

I'm not a C programmer and didn't study the code of that program in detail. So it's possible that the issue lies somewhere else.

**Comment by poettering** [comment]
you are absolutely right about where the issue is!
