### ISSUE TITLE
Unclear documentation for systemd.exec

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#16845]
**Is your feature request related to a problem? Please describe.**
The systemd.exec unit options `WorkingDirectory` and `RootDirectory` specify filesystem paths.  It is unclear from the documentation if this adds the systemd.unit directive `RequiresMountsFor` as a dependency.

**Describe the solution you'd like**
Can the documentation for `systemd.exec` be altered to explicitly state if it adds `RequiresMountsFor` as a dependency or if the owner of the unit file is expected to add it manually.

**Describe alternatives you've considered**
This is really just ensuring the documentation is precise on this point.  It is possible for reasonable folks to assume either condition.

**Comment by poettering** [comment]
It's pretty clear about this already. Here's the documentation on WorkingDirectory=:

> Note that setting this parameter might result in additional dependencies to be added to the unit (see above).

And if you look a few lines above you'll find this:

> IMPLICIT DEPENDENCIES
> A few execution parameters result in additional, automatic dependencies to be added:
>
>  Units with WorkingDirectory=, RootDirectory=, RootImage=, RuntimeDirectory=, StateDirectory=, CacheDirectory=, LogsDirectory= or ConfigurationDirectory= set automatically gain dependencies of type Requires= and After= on all mount units required to access the specified paths. This is equivalent to having them listed explicitly in RequiresMountsFor=.

And for RootDirectory= you find the same hint.

So I'd say this is pretty clear and hard to misunderstand no?

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Implicit%20Dependencies
