### ISSUE TITLE
Failed unmounting /home. systemd-homed

### ISSUE THREAD

**Issue by jekanev** [systemd/systemd#16842]
**systemd version the issue has been seen with**
systemd 246.2-2

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
unmount /home

**Unexpected behaviour you saw**
when home folder mount point on different partition i get error log message on shutdown. Failed unmounting /home.
same if i try --image-path=/mypath/path different partitioni
if home folder on same partition with root no error.
also if i use user with regular home folder shutdown goes without error.

**Steps to reproduce the problem**
reboot shutdown with systemd-homed user folder.

<pre>
<code>
Aug 26 12:13:09 robot systemd[1]: Stopped target Local File Systems.
Aug 26 12:13:09 robot systemd[1]: Unmounting /boot/efi...
Aug 26 12:13:09 robot systemd[1]: Unmounting /home/spik...
Aug 26 12:13:09 robot systemd[1]: Unmounting /media/disk_A_3...
Aug 26 12:13:09 robot systemd[1]: Unmounting /media/ext4_E...
Aug 26 12:13:09 robot systemd[1]: Unmounting /ramdisk...
Aug 26 12:13:09 robot systemd[1]: Unmounting /run/shm...
Aug 26 12:13:09 robot systemd[1]: Unmounting /tmp...
Aug 26 12:13:09 robot systemd[1]: Unmounting /var/cache/pacman/custom...
Aug 26 12:13:09 robot systemd[1]: Unmounting /var/tmp...
Aug 26 12:13:09 robot systemd[1]: boot-efi.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /boot/efi.
Aug 26 12:13:09 robot systemd[1]: ramdisk.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /ramdisk.
Aug 26 12:13:09 robot systemd[1]: run-shm.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /run/shm.
Aug 26 12:13:09 robot systemd[1]: tmp.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /tmp.
Aug 26 12:13:09 robot systemd[1]: var-cache-pacman-custom.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /var/cache/pacman/custom.
Aug 26 12:13:09 robot systemd[1]: var-tmp.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /var/tmp.
Aug 26 12:13:09 robot systemd[1]: Stopped target Swap.
Aug 26 12:13:09 robot systemd[1]: Unmounting /media/disk_D...
Aug 26 12:13:09 robot systemd[1]: systemd-fsck@dev-disk-by\x2duuid-507D\x2d632A.service: Succeeded.
Aug 26 12:13:09 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-fsck@dev-disk-by\x2duuid-507D\x2d632A comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:09 robot systemd[1]: Stopped File System Check on /dev/disk/by-uuid/507D-632A.
Aug 26 12:13:09 robot systemd[1]: media-disk_A_3.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /media/disk_A_3.
Aug 26 12:13:09 robot systemd[1]: systemd-fsck@dev-disk-by\x2duuid-fdb1e73f\x2d6407\x2d4fea\x2d8512\x2d29727c1c9f6b.service: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Stopped File System Check on /dev/disk/by-uuid/fdb1e73f-6407-4fea-8512-29727c1c9f6b.
Aug 26 12:13:09 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-fsck@dev-disk-by\x2duuid-fdb1e73f\x2d6407\x2d4fea\x2d8512\x2d29727c1c9f6b comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:09 robot systemd[1]: media-disk_D.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /media/disk_D.
Aug 26 12:13:09 robot systemd[1]: home-spik.mount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unmounted /home/spik.
Aug 26 12:13:09 robot systemd[1]: Unmounting /home...
Aug 26 12:13:09 robot umount[1670]: umount: /home: target is busy.
Aug 26 12:13:09 robot systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
Aug 26 12:13:09 robot systemd[1]: Failed unmounting /home.
Aug 26 12:13:09 robot systemd[1]: home.automount: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Unset automount home.automount.
Aug 26 12:13:09 robot systemd[1]: systemd-fsck@dev-disk-by\x2duuid-5efd5569\x2da376\x2d4f7c\x2d997c\x2de29f58c35d49.service: Succeeded.
Aug 26 12:13:09 robot systemd[1]: Stopped File System Check on /dev/disk/by-uuid/5efd5569-a376-4f7c-997c-e29f58c35d49.
Aug 26 12:13:09 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-fsck@dev-disk-by\x2duuid-5efd5569\x2da376\x2d4f7c\x2d997c\x2de29f58c35d49 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:09 robot systemd[1]: home.mount: Failed with result 'exit-code'.
Aug 26 12:13:10 robot systemd[1]: media-ext4_E.mount: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Unmounted /media/ext4_E.
Aug 26 12:13:10 robot systemd[1]: Reached target Unmount All Filesystems.
Aug 26 12:13:10 robot systemd[1]: systemd-fsck@dev-disk-by\x2duuid-973ce4ae\x2d0f0b\x2d4157\x2d9ede\x2d874775f449b9.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Stopped File System Check on /dev/disk/by-uuid/973ce4ae-0f0b-4157-9ede-874775f449b9.
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-fsck@dev-disk-by\x2duuid-973ce4ae\x2d0f0b\x2d4157\x2d9ede\x2d874775f449b9 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: Removed slice system-systemd\x2dfsck.slice.
Aug 26 12:13:10 robot systemd[1]: Stopped target Local File Systems (Pre).
Aug 26 12:13:10 robot systemd[1]: Stopping Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
Aug 26 12:13:10 robot systemd[1]: systemd-remount-fs.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Stopped Remount Root and Kernel File Systems.
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: systemd-tmpfiles-setup-dev.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Stopped Create Static Device Nodes in /dev.
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: lvm2-monitor.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=lvm2-monitor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: Stopping LVM2 metadata daemon...
Aug 26 12:13:10 robot systemd[1]: lvm2-lvmetad.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Stopped LVM2 metadata daemon.
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=lvm2-lvmetad comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: Reached target Shutdown.
Aug 26 12:13:10 robot systemd[1]: Reached target Final Step.
Aug 26 12:13:10 robot systemd[1]: lvm2-lvmetad.socket: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Closed LVM2 metadata daemon socket.
Aug 26 12:13:10 robot systemd[1]: systemd-reboot.service: Succeeded.
Aug 26 12:13:10 robot systemd[1]: Finished Reboot.
Aug 26 12:13:10 robot audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-reboot comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-reboot comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 26 12:13:10 robot systemd[1]: Reached target Reboot.
Aug 26 12:13:10 robot systemd[1]: Shutting down.
Aug 26 12:13:10 robot audit: BPF prog-id=6 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=5 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=12 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=11 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=8 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=7 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=4 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=3 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=10 op=UNLOAD
Aug 26 12:13:10 robot audit: BPF prog-id=9 op=UNLOAD
Aug 26 12:13:10 robot systemd[1]: Hardware watchdog 'SP5100 TCO timer', version 0
Aug 26 12:13:10 robot systemd[1]: Set hardware watchdog to 10min.
Aug 26 12:13:10 robot kernel: watchdog: watchdog0: watchdog did not stop!
Aug 26 12:13:10 robot systemd-shutdown[1]: Syncing filesystems and block devices.
Aug 26 12:13:10 robot systemd-shutdown[1]: Sending SIGTERM to remaining processes...
</code>
</pre>

**Comment by poettering** [comment]
what does "homectl inspect -j" of your user output? can you paste that somewhere?

**Comment by jekanev** [comment]
> what does "homectl inspect -j" of your user output? can you paste that somewhere?
i change homectl kill process to true and wrote script which logout then run homectl deactivate with shutdown, this give no errors.
my homectl  inspect -j below.
<pre>
<code>{
{
        "binding" : {
                "da027a8473f94ea1b803959c8e1e62d1" : {
                        "fileSystemType" : "ext4",
                        "fileSystemUuid" : "e77b8558-7046-41f4-b6df-8d8bf5de6fca",
                        "gid" : 1000,
                        "homeDirectory" : "/home/spik",
                        "imagePath" : "/home/spik.home",
                        "luksCipher" : "aes",
                        "luksCipherMode" : "xts-plain64",
                        "luksUuid" : "fb410d0e-1f89-4579-8120-fb537a467019",
                        "luksVolumeKeySize" : 32,
                        "partitionUuid" : "4a24d252-d47b-4002-96ff-6d4b14564f6f",
                        "storage" : "luks",
                        "uid" : 1000
                }
        },
        "disposition" : "regular",
        "killProcesses" : true,
        "lastChangeUSec" : 1598532867371314,
        "lastPasswordChangeUSec" : 1598372836061069,
        "luksOfflineDiscard" : true,
        "memberOf" : [
                "audio",
                "input",
                "kvm",
                "libvirt",
                "spik",
                "storage",
                "users",
                "video",
                "wheel"
        ],
        "perMachine" : [
                {
                        "matchMachineId" : "da027a8473f94ea1b803959c8e1e62d1"
                }
        ],
        "privileged" : {
                "hashedPassword" : [
                        ""
                ]
        },
        "shell" : "/usr/bin/zsh",
        "signature" : [
                {
                        "data" : "",
                        "key" : "-----BEGIN PUBLIC KEY-----\"
                }
        ],
        "stopDelayUSec" : 0,
        "uid" : 1000,
        "userName" : "spik",
        "status" : {
                "da027a8473f94ea1b803959c8e1e62d1" : {
                        "badAuthenticationCounter" : 34,
                        "lastBadAuthenticationUSec" : 1598678269969796,
                        "rateLimitBeginUSec" : 1598678564545846,
                        "rateLimitCount" : 1,
                        "goodAuthenticationCounter" : 190,
                        "lastGoodAuthenticationUSec" : 1598678565492470,
                        "state" : "active",
                        "service" : "io.systemd.Home",
                        "diskSize" : 45231341568,
                        "diskUsage" : 14587146240,
                        "diskFree" : 30644195328,
                        "diskCeiling" : 62171750400,
                        "diskFloor" : 14587146240,
                        "signedLocally" : true
                }
        }


</code>
</pre>

**Comment by zachsmith** [comment]
I'm using Gnome on Arch and /home is a Btrfs subvolume. 

I have the same issue when issuing a shutdown or reboot from within a Gnome session. I noticed that if I logout of my user account in Gnome and then login as root via a console I can see that /home/zach is still mounted for a few seconds. If I wait for it to be unmounted and then reboot I do not see the `Failed to unmount /home` error.

`$ homectl inspect -j`

```json
{
        "binding" : {
                "2d5d5e5896d843619c2be183b6c018d3" : {
                        "fileSystemType" : "ext4",
                        "fileSystemUuid" : "226c5b83-19a8-49ed-a19a-48d2b8dadcae",
                        "gid" : 1000,
                        "homeDirectory" : "/home/zach",
                        "imagePath" : "/home/zach.home",
                        "luksCipher" : "aes",
                        "luksCipherMode" : "xts-plain64",
                        "luksUuid" : "fa777976-1680-4be9-9459-2bad4246047e",
                        "luksVolumeKeySize" : 32,
                        "partitionUuid" : "204c540f-d601-4193-b38b-de9aae8fcbb6",
                        "storage" : "luks",
                        "uid" : 1000
                }
        },
        "disposition" : "regular",
        "lastChangeUSec" : 1600007386067334,
        "lastPasswordChangeUSec" : 1600006206401479,
        "luksDiscard" : true,
        "memberOf" : [
                "libvirtd",
                "wheel"
        ],
        "perMachine" : [
                {
                        "matchMachineId" : "2d5d5e5896d843619c2be183b6c018d3",
                        "storage" : "luks"
                }
        ],
        "privileged" : {
                "hashedPassword" : [
                        "$y$j9T$8yTDUnBlvX6zaC/0G476L0$CH56IOjR6Cj6RTCSXjMbNFVM4ZR.p4NxPC7nxDif6bC"
                ]
        },
        "realName" : "Zachary Smith",
        "shell" : "/bin/zsh",
        "signature" : [
                {
                        "data" : "EmCrq0uwxDHaWd4Pg0MT94T0EnOWUsayGQXr1RKngzUzOyMV5rX+tuz60J4EkHIBbmnByzi1/CFRt1yTKETDBA==",
                        "key" : "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAMv32XVD5XOCkV/RESfjdR2qrTrE3KIacTO8hBWyRAeQ=\n-----END PUBLIC KEY-----\n"
                }
        ],
        "uid" : 1000,
        "userName" : "zach",
        "status" : {
                "2d5d5e5896d843619c2be183b6c018d3" : {
                        "badAuthenticationCounter" : 19,
                        "lastBadAuthenticationUSec" : 1600397037814878,
                        "rateLimitBeginUSec" : 1600435444316802,
                        "rateLimitCount" : 1,
                        "goodAuthenticationCounter" : 163,
                        "lastGoodAuthenticationUSec" : 1600435445324893,
                        "state" : "active",
                        "service" : "io.systemd.Home",
                        "diskSize" : 349321137152,
                        "diskUsage" : 55675719680,
                        "diskFree" : 293628399616,
                        "diskCeiling" : 407081033728,
                        "diskFloor" : 55675719680,
                        "signedLocally" : true
                }
        }
}
```

**Comment by poettering** [comment]
Any chance you can check if #17100 improves things for you?

**Comment by poettering** [comment]
Hmm, we shouldn't close this yet. #17100 probably doesn't fix things entirely.

**Comment by zachsmith** [comment]
> Any chance you can check if #17100 improves things for you?

Sorry for the late reply - just got around to this. It looks like the original commit you'd intended to be a fix (https://github.com/systemd/systemd/pull/17100/commits/9796a9fbad5bae4d66bb40d848f6245d1ee327d8) was cherry-picked into `system-stable` and Arch picked that up so I tested with the systemd-stable v246.6 package and unfortunately I am still seeing the issue with `/home` failing to unmount. If I should test with the full branch you'd linked I can do that as well but at a glance none of the other commits seemed related.

**Comment by poettering** [comment]
#17113 should fully fix the issue.
