### ISSUE TITLE
Enhancement: please enhance kernel to automatically select IO elevator based on type of disk

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#1684]
Moving this here upstream since this needs some formal response from most likely @kaysievers  ( Kay was cc on the upstream kernel discussion that took place in 2012 ) and the kernel community thinks this should be handled by udev ( I personally dont see how the intent is to implement this effectively in the kernel or udev or elsewhere for that matter + ) . 

Relevant comment from Justin
"Vivek did lob the patch that would do this upstream, but it only acts based on SATA vs not. Upstream pretty much agreed that it should be based on the type of device vs how it is connected (rotational vs ssd, etc). Upstream also agreed that this was something that udev should handle, and not the kernel.  I am going to reassign this to systemd and see if there is something they can do here.

The discussion upstream can be seen found here:
https://lkml.org/lkml/2012/4/10/198"

Downstream report
https://bugzilla.redhat.com/show_bug.cgi?id=1175275

**Comment by johannbg** [comment]
Apparently reporters cant label themselves here on github which is something that should perhaps be looked at.

**Comment by poettering** [comment]
Where precisely is where upstream said that this should happen in udev?

But quite frankly, I don't see what the benefit is of doing this in userspace: reading one sysfs attribute and writing it back immediately sounds pretty pointless... the kernel should really pick such basic defaults automatically...

**Comment by poettering** [comment]
But anyway, I'll leave this for @kaysievers to decide.

**Comment by johannbg** [comment]
"This sort of thing should be done with a udev rule. It should not be too
hard to match for the most popular arrays, catching the majority of the
setups by default."

https://lkml.org/lkml/2012/4/10/370

**Comment by poettering** [comment]
That talks about RAID and stuff... RAID is clearly out-of-focus for udev/systemd. If it's just about that, please file a bug against mdadm or so, so that they can ship a rule, but this would have no place in systemd upstream. Or what is this about?

**Comment by johannbg** [comment]
@poettering  Perhaps you should just pick up your phone and call your coworkers and ask them for clarification I have better things to do than playing the middle man for you and other Red Hat employees because you cant respond to the downstream bug report.

**Comment by kaysievers** [comment]
This has no place in udev, as mentioned many times.
