### ISSUE TITLE
no IPIP-tunnel created whatever I do in .netdev file

### ISSUE THREAD

**Issue by cypa** [systemd/systemd#16852]
**systemd version the issue has been seen with**
>  ~|systemctl --version
systemd 245 (245.7-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Archlinux stable

**Expected behaviour you didn't see**
 > create network interface m66 as ipip-mode tunnel 

**Unexpected behaviour you saw**
> no interface created

**Steps to reproduce the problem**

~|cat /etc/systemd/network/25-ipip.netdev 
[NetDev]
Name=m66
Kind=ipip
MTUBytes=1480 

[Tunnel]
Local=5.172.19.48
Remote=5.79.136.222
TTL=64
~|cat /etc/systemd/network/25-ipip.network
[Match]
Name=m66

[Network]
Address=10.1.1.1/24
~|doas systemctl restart systemd-networkd
~|networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP      
  1 lo     loopback carrier     unmanaged  
  2 wlp1s0 wlan     routable    configured 
  3 br0    bridge   no-carrier  configuring

no tunnel interfaces created, while with command 
`doas ip tunnel add m66 mode ipip local 5.172.19.48 remote 5.79.136.222`
the tunnel interface was created successfully

debug log of systemd-networkd shows only one line on ipip:
авг 26 20:41:32 avs.mobile.cypa systemd-networkd[2921]: m66: loaded ipip

**Comment by yuwata** [comment]
Please set `Independent=yes` in `[Tunnel]` section, or assign `m66` tunnel to other interface by setting `Tunnel=m66` in a corresponding .network file.
