### ISSUE TITLE
systemd-resolved: Failed at step NAMESPACE spawning Read-only file system

### ISSUE THREAD

**Issue by seregaizsbera** [systemd/systemd#16868]
systemd-resolved failed to start
on fast hardware.

After migration to more powerful hardware systemd-resolved fails to start with onward error.

systemd-resolved.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-resolved: Read-only file system

I managed to find a workaround by adding an option RestartUSec=5s

**Comment by seregaizsbera** [comment]
Linux 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by seregaizsbera** [comment]
CentOS Linux release 8.2.2004 (Core)

**Comment by seregaizsbera** [comment]
systemd-239-31.el8_2.2.x86_64

**Comment by seregaizsbera** [comment]
$ systemd-resolve --version
systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31

**Comment by yuwata** [comment]
Sorry, v239 is too old here. Please contact to your downstream.
