### ISSUE TITLE
Extremely slow boot and constant CPU utilization

### ISSUE THREAD

**Issue by Staudey** [systemd/systemd#16878]
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Solus Budgie (kernel 5.6.19), Unstable repository activated

**Expected behaviour you didn't see**
 > Same boot times and CPU utilization as with version 245

**Unexpected behaviour you saw**
 > Boot is significantly longer (i.e. several times longer) than with systemd 245, and one of my cores is constantly 50 - 100% in use due to systemd processes.
> Regarding the boot: `systemd-analyze blame` (which itself takes incredibly long to process now) always shows one service with a start time of ~25 seconds now, but it's not always the same one. For the last two boots it was "vboxdrv.service" resp. "accounts-daemon.service". Here is a journalctl log of my last boot: https://hastebin.com/bujomehayo.coffeescript
> Regarding CPU utilization: my System monitor shows a `systemd` process and `dbus-daemon` taking up at least 50% of my CPU and then `systemd-logind` another 4%, constantly. `sudo journalctl -f` doesn't show any errors or warnings.

**Steps to reproduce the problem**

1. Use Solus with the unstable repository activated
2. Do a full update, which includes systemd 246.2
3. Reboot and observe the long boot time
4. Log in and open System Monitor to observe the high CPU utilization

Note that it doesn't happen to other Solus users I have talked to, so it must be something specific to my kind of setup. Not sure what, unfortunately.

I have built and installed systemd 246.3 to see if it fixes this problem, but it has the same issues

**System Information:**
```
System:    Host: solus-pc Kernel: 5.6.19-158.current x86_64 bits: 64 Desktop: Budgie 10.5.1 Distro: Solus 4.1 
Machine:   Type: Desktop Mobo: MEDION model: MS-7797 v: 1.1 serial: <superuser/root required> BIOS: American Megatrends 
           v: M7797W08.209 date: 09/20/2012 
CPU:       Topology: Quad Core model: Intel Core i5-3350P bits: 64 type: MCP L2 cache: 6144 KiB 
           Speed: 3218 MHz min/max: 1600/3300 MHz Core speeds (MHz): 1: 3112 2: 3104 3: 3107 4: 3112 
Graphics:  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 450.66 
           Display: x11 server: X.Org 1.20.8 driver: nvidia resolution: 1920x1080 
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 450.66 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel 
           Device-2: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel 
           Device-3: JMTek LLC. USB PnP Audio Device type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.6.19-158.current 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: d4:3d:7e:2e:66:8e 
           Device-2: Realtek RTL8188CUS 802.11n WLAN Adapter type: USB driver: rtl8192cu 
           IF: wlp0s26u1u1 state: down mac: 80:1f:02:81:9a:41 
Drives:    Local Storage: total: 931.51 GiB used: 405.17 GiB (43.5%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB 
Partition: ID-1: / size: 452.99 GiB used: 405.17 GiB (89.4%) fs: ext4 dev: /dev/sda4 
Swap:      ID-1: swap-1 type: partition size: 3.72 GiB used: 0 KiB (0.0%) dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 51.0 C mobo: N/A gpu: nvidia temp: 36 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:      Processes: 270 Uptime: 30m Memory: 7.78 GiB used: 2.41 GiB (31.0%) Shell: zsh inxi: 3.1.03
```

**Comment by keszybz** [comment]
Could you test if #16885 helps?

**Comment by Staudey** [comment]
> Could you test if #16885 helps?

Just recompiled the Solus package with that patch set and it indeed fixes both issues for me. Thank you!
