### ISSUE TITLE
timedate1 get-property NTP gets stuck if time changed to the past

### ISSUE THREAD

**Issue by marusak** [systemd/systemd#16883]
**systemd version the issue has been seen with**
systemd-246.1

**Used distribution**
Fedora 33

**Expected behaviour you didn't see**
`busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP` should always reply and not timeout.

**Unexpected behaviour you saw**
`busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP` gets stuck under specific circumstances. 

**Steps to reproduce the problem**
Note: It is rather racy therefore I call `get-property` 5 times in a row. It gets stuck at one point, ^C is the best option. The provided script reproduces it 100% of time for me on cleanly booted fedora-33 VM.

The issue has 3 steps:
1. Set time to the past. If setting it to the future it works. (Try changing `2020-01-24` to `2020-10-24` in the script). This requires NTP to be turned off, thus the command before `set-time`.
2. Turn the NTP back up
3. Now turn the NTP back off again. At this point `get-property` gets stuck and never replies. It times out.

```
$ cat script_past.sh 
busctl call org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 SetNTP bb false true

busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP

timedatectl set-time '2020-01-24 08:03:00'

busctl call org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 SetNTP bb true true

busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP

busctl call org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 SetNTP bb false true

busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP

busctl call org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 SetNTP bb true true

busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP

$ ./script_past.sh 
b false
b false
b false
b false
b false
b true
b true
b true
b true
b true
Failed to get property NTP on interface org.freedesktop.timedate1: Connection timed out
^C
```

**Comment by poettering** [comment]
hmm, when it gets stuck, what does "systemctl list-jobs" say?

ARe you actually using systemd-timedated? Or that weird python script fedora replaces it with?

Which NTP client is this? systemd-timesyncd? Or chrony? If you use systemd-timesyncd, does this become stable?

**Comment by marusak** [comment]
> hmm, when it gets stuck, what does "systemctl list-jobs" say?

That is stuck as well.

> ARe you actually using systemd-timedated? Or that weird python script fedora replaces it with?

:man_shrugging: How can I check that? This is just default fedora 33.

> Which NTP client is this? systemd-timesyncd? Or chrony? 

chrony

> If you use systemd-timesyncd, does this become stable?

Does not seem so, still the same issue.

**Comment by poettering** [comment]
So that sounds as if your dbus is simply down?

mabye you just hit dbus' per-user limits?

Anything in the logs from dbus-daemon or dbus-broker?

**Comment by keszybz** [comment]
> Or that weird python script fedora replaces it with?

Hmm, what script?

**Comment by poettering** [comment]
the fedora chrony people had timedatedx or so? which was a reimplementation of the whole thing?

**Comment by keszybz** [comment]
Fedora had timedatex that had the functionality removed from timedated, but we merged that functionality back a while ago and timedatex is long gone.

**Comment by poettering** [comment]
Anyway, if "systemctl list-jobs" is hanging too, this suggests something is wrong with dbus. Anything in the logs?

**Comment by marusak** [comment]
attaching output from `journalctl -f` while running the script. Notice the last line, thats from the stuck command.

[log.txt](https://github.com/systemd/systemd/files/5162390/log.txt)

**Comment by poettering** [comment]
my educated guess is that someone calculates timeouts based on CLOCK_REALTIME instead of CLOCK_MONOTONIC.

What dbus daemon do you use? dbus-daemon? dbus-broker?

Does dbus-broker hang? what is the gdb stack trace of the dbus daemon when the issue happens?

**Comment by marusak** [comment]
I am not able to reproduce this anymore. I was (and am) using dbus-broker.
Closing as I cannot provide more info anymore.
