### ISSUE TITLE
[NIT] Coredump filename mistakenly has granularity change done twice

### ISSUE THREAD

**Issue by Kellel** [systemd/systemd#16919]
**systemd version the issue has been seen with**
Master branch in github. Currently b51952910443303cb3f9fd037865470e402003ad

**Used distribution**
Debian buster

**Expected behaviour you didn't see**
Expected to see 6 zeros on the trailing end of generated coredump filenames

Something like the following:
`/var/lib/systemd/coredump/core.sleep.1000.1f8ff1efb5ad4603a2041a7e4c6155ac.1969435.1598914313000000.zst`

**Unexpected behaviour you saw**
Saw 12 zeros on the trailing end of the generated coredump filenames

Example generated on my machine:
`/var/lib/systemd/coredump/core.sleep.1000.1f8ff1efb5ad4603a2041a7e4c6155ac.1969435.1598914313000000000000.zst`

**Steps to reproduce the problem**
Generate any coredump on a machine with External storage configured

**Relevant parts of the source code**
In `gather_pid_metadata_from_argv` https://github.com/systemd/systemd/blob/master/src/coredump/coredump.c#L1038-L1043 there is a comment about padding the timestamp field such that the granularity is changed from 1s to 1µs. At this point 6 zeros are appended to the end of the timestamp.

Later when writing to external storage the `make_filename` function is called. It then _ALSO_ does the same conversion https://github.com/systemd/systemd/blob/master/src/coredump/coredump.c#L314 appending another 6 zeros. 

This results in having 12 zeros on the end of every coredump file written to disk.

My guess is that this is a super low priority bug, but a colleague asked me why all the zeros where there and this seemed wrong.

**Comment by poettering** [comment]
indeed!

**Comment by poettering** [comment]
Thanks for tracking this down. Fix pending in #16931
