### ISSUE TITLE
LogRateLimitIntervalSec or LogRateLimitIntervalUSec

### ISSUE THREAD

**Issue by Furgas** [systemd/systemd#16921]
I'm trying to use per-service LogRateLimitIntervalSec but it doesn't seem to work for me.
I started digging, and noticed that in `src/core/dbus-execute.c` there is `LogRateLimitIntervalUSec` option (notice the "U"), while in the rest of the code and documentation files it is called `LogRateLimitIntervalSec` (without the "U"). Could it be a reason?

**Comment by yuwata** [comment]
Please see https://github.com/systemd/systemd/pull/16875.

If you want set in a unit file, then please use `LogRateLimitIntervalSec`. If you want to control that e.g. by `systemctl set-property`, then please use `LogRateLimitIntervalUSec`.
