### ISSUE TITLE
networkd - sd_dhcp_clients not keeping lease over system recycles

### ISSUE THREAD

**Issue by cherusk** [systemd/systemd#16924]
**systemd version the issue has been seen with**
v245
Should be from v241, when that changes came in [1].

**Expected behaviour you didn't see**
dhcp client keeping leases applied to interfaces in case configured accordingly with networkd. Expected to be working network configuration example:

> [Match]
> Name=some_iface
> 
> [Network]
> DHCP=ipv4
> KeepConfiguration=dhcp
> IgnoreCarrierLoss=yes
> 
> [DHCPv4]
> SendRelease=no

**Unexpected behaviour you saw**
Even ignoring carrier loss and forbidding a DHCP release being sent to the server are not preventing leases being lost.

**Steps to reproduce the problem**

Setup two nodes. One for acting as sd_client, using networkd for clienting, other as dhcp server. Stop dhcp daemon on the server and reboot the sd_client. The sd_client will loose the lease.

** Ref **
[1] https://github.com/systemd/systemd/pull/16920

[2] https://github.com/systemd/systemd/issues/10820

**Comment by cherusk** [comment]
I'm keen to patch it myself, could benefit from collaborators though:
Please see initial  steps [²]

**Comment by poettering** [comment]
what is a "system recycle"? a reboot?

Are you saying that a locally acquired DHCP lease is lost during reboot? We do not make leases persistent, so this is expected. What makes you think otherwise?

**Comment by cherusk** [comment]
> what is a "system recycle"? a reboot?
Yes, kept wording more abstract, as I wanted to catch shutdown/startup a reboot or other forms of cycles as suspension e.g. in one phrasing. :)
 
> Are you saying that a locally acquired DHCP lease is lost during reboot?
Correct. That I don't want, or only want it optionally.

> We do not make leases persistent, so this is expected. What makes you think otherwise?

Please refer to https://github.com/systemd/systemd/issues/10820 as referred to above, once networkd did retain leases active on the interafaces. It's true, the leases are retained volatily `/run` and always have been, but until more recent versions, the sd_dhcp_clients had not been stopped which led to the effect that the links remained configured with a lease those attained before a system recycle happening.

Moreover,  **KeepConfiguration=dhcp** is misleading or of limited value to any serious infrastructure setup to my mind if not kept in the scenarious I'm describing.

**Comment by yuwata** [comment]
Still I do not understand your issue. Could you show the commands and their expected results one by one?

**Comment by cherusk** [comment]
@yuwata Pardon should I have fallen short in conveying. Let me kindly provide a sample sequence:

We're are on a simplistic link layer network, both systems **dhcp-server-vm** and **sd-client-vm** are seeing each other on link layer.

```
# Let's start on the server side. Provided all is configured well to work as minimal dhcpd.
[root@dhcp-server-vm ~]# systemctl start dhcpd

# ---

[root@dhcp-server-vm ~]# systemctl status dhcpd 
● dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; disabled; vendor pres>
   Active: active (running) since Thu 2020-09-03 04:34:35 UTC; 1min 44s ago
     Docs: man:dhcpd(8)
           man:dhcpd.conf(5)
 Main PID: 2330 (dhcpd)
   Status: "Dispatching packets..."
    Tasks: 1 (limit: 2354)
   Memory: 4.7M
   CGroup: /system.slice/dhcpd.service
           └─2330 /usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -grou>

Sep 03 04:34:35 dhcp-server-vm dhcpd[2330]: Wrote 7 leases to leases file.
Sep 03 04:34:35 dhcp-server-vm dhcpd[2330]: Listening on LPF/eth0/52:54:00:33:8>
Sep 03 04:34:35 dhcp-server-vm dhcpd[2330]: Sending on   LPF/eth0/52:54:00:33:8>
Sep 03 04:34:35 dhcp-server-vm dhcpd[2330]: Sending on   Socket/fallback/fallba>
Sep 03 04:34:35 dhcp-server-vm dhcpd[2330]: Server starting service.
Sep 03 04:34:35 dhcp-server-vm systemd[1]: Started DHCPv4 Server Daemon.
Sep 03 04:35:14 dhcp-server-vm dhcpd[2330]: DHCPDISCOVER from 52:54:00:bb:ac:63>
Sep 03 04:35:15 dhcp-server-vm dhcpd[2330]: DHCPOFFER on 10.0.2.18 to 52:54:00:>
Sep 03 04:35:15 dhcp-server-vm dhcpd[2330]: DHCPREQUEST for 10.0.2.18 (10.0.2.6>

# ---
# On client siede, let's assume we hold that lease then.

[root@sd-client-vm ~]# ip a | grep -A 10 eth
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:bb:ac:63 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 10.0.2.18/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever

# ---
# Now let's stop the dhcpd serving leases

[root@dhcp-server-vm ~]# systemctl stop dhcpd 
[root@dhcp-server-vm ~]# systemctl status dhcpd 
● dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; disabled; vendor pres>
   Active: inactive (dead)
     Docs: man:dhcpd(8)
           man:dhcpd.conf(5)

Sep 03 04:37:11 dhcp-server-vm dhcpd[2330]: reuse_lease: lease age 116 (secs) u>
Sep 03 04:37:11 dhcp-server-vm dhcpd[2330]: DHCPDISCOVER from 52:54:00:bb:ac:63>
Sep 03 04:37:12 dhcp-server-vm dhcpd[2330]: DHCPOFFER on 10.0.2.18 to 52:54:00:>

# ---
# and reboot the sd networkd client vehicle

[root@sd-client-vm ~]# reboot
         Stopping Session 1 of user root.
[  OK  ] Removed slice system-modprobe.slice.
[  OK  ] Removed slice system-sshd\x2dkeygen.slice.
[  OK  ] Stopped target Cloud-init target.
[  OK  ] Stopped target Multi-User System.
[  OK  ] Stopped target Login Prompts.
[  OK  ] Stopped target Timers.
[...]

# ---

# when the sd_client is coming up again, I'd like to keep it's lease when providing configuration as stated in report, but
# it will preen and drop its leases during recycle as follows in recent version

[root@sd-client-vm ~]# ip a | grep -A 10 eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:bb:ac:63 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet6 fe80::5054:ff:febb:ac63/64 scope link 
       valid_lft forever preferred_lft forever

# ---

[root@sd-client-vm ~]# networkctl list
IDX LINK TYPE     OPERATIONAL SETUP      
  1 lo   loopback carrier     unmanaged  
  2 eth0 ether    degraded    configuring

2 links listed.
# ---

[root@sd-client-vm ~]# networkctl status eth0
● 2: eth0                                                                      >
                     Link File: /usr/lib/systemd/network/99-default.link       >
                  Network File: /etc/systemd/network/01_ether_link_dhcp.network>
                          Type: ether                                          >
                         State: degraded (configuring)
             Alternative Names: enp0s3                                         >
                                ens3                                           >
                          Path: pci-0000:00:03.0                               >
                        Driver: virtio_net                                     >
                        Vendor: Red Hat, Inc.                                  >
                         Model: Virtio network device                          >
                    HW Address: 52:54:00:bb:ac:63                              >
                           MTU: 1500 (min: 68, max: 65535)                     >
                         QDisc: fq_codel                                       >
  IPv6 Address Generation Mode: eui64                                          >
          Queue Length (Tx/Rx): 1/1                                            >
              Auto negotiation: no                                             >
                         Speed: n/a                                            >
                       Address: fe80::5054:ff:febb:ac63                        >
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab1179d8e01841640a730000    >

Sep 03 04:39:52 sd-client-vm systemd-networkd[635]: eth0: IPv6 successfully ena>
Sep 03 04:39:52 sd-client-vm systemd-networkd[635]: eth0: Link UP

```

Hope it's clear now.

Further, please also see my PR [1] as referrenced above.

[¹] https://github.com/systemd/systemd/pull/16920

**Comment by cherusk** [comment]
@ssahani 

> When the system reboots you saying `networkd` dhcp client does not talk to DHCP server to acquire them again. The DHCP server has the leases . So when the client starts again it should get these leases from the server as it remembers them. There is no need for the clients to make persistent are not valid .

No, I have not said that. I'm only saying the sd_client does currently not persist the lease and reload it after coming up during boot, in case that has been configured. The sd_dhcp_client for sure will attempt to get a fresh lease in some back-off manner, which is fine and in case the DHCPD infrastructure is up is the desired path. Yet, if a lease has been stored that has still a valid life time, and the sd_dhcp_client has not sent a release before going done, there is DHCP protocol nothing wrong in reapplying that lease in case no DHCPD is reachable when the system is coming up. The latter is what I'm seeking for with my changes.

**Comment by yuwata** [comment]
When system is rebooted, there is no guarantee that the interface is still connected to the same network. E.g., you worked at your office with a laptop, and once shutdown the machine, then go to a cafe and connect to a WiFi spot there. In such a case, we should not use the lease obtained at the office. In general, we need to drop old lease and acquire new lease on reboot.

I do not find any strong use case to introduce a new option or extend `KeepConfiguration=` to store lease on persistent storage...

**Comment by cherusk** [comment]
@yuwata 

> When system is rebooted, there is no guarantee that the interface is still connected to the same network. E.g., you worked at your office with a laptop, and once shutdown the machine, then go to a cafe and connect to a WiFi spot there. In such a case, we should not use the lease obtained at the office. In general, we need to drop old lease and acquire new lease on reboot.

That's a fair point, that's why I'm proposing to yield the behaviour I'm proposing only when it has been explicitly configured as suggested in the report by an engineer who knows what he/she is doing. I'm not proposing to make the suggested additional flow the default flow, clearly not.

> I do not find any strong use case to introduce a new option or extend `KeepConfiguration=` to store lease on persistent storage...

It's because you're not thinking from the infrastructure perspective. systemd is a desktop system management component as much as it is for the infrastructure side, probably even more. Right @poettering?  And on infrastructure side there are outages, incidents and so on, harsh times. And if someone decides to use DHCP as addressing bootstraping delivery channel, then what I'm proposing is a valid stabilizing approach to come up with a higher degree of resiliency  for a standardized, well defined and known backend setup of machines.

One could state now to make the DHCP server side more resilient and only concentrate on that, but not every infrastructure holding entity can afford that. Even a highly availabe DHCP server setup is fallible either. Rendering all addresing static with help of centralized automation is not for everyone either.

Further, if you looked at the isc equivalent components, like **dhclient**, it also allows you to opt into keeping the lease or not. Only **ifupdown**, one of the most widespread or prominent management layers around it, established that notion of leases only being held when the system is up. As said once more, what I'm proposing is not breaking the DHCP protocol in any regards.

**Comment by ssahani** [comment]
What happens when you shutdown. After some days you switch on ? In the meantime if server asks all clients to release the leases ? This looks wrong to me.

**Comment by cherusk** [comment]
> What happens when you shutdown. After some days you switch on ? In the meantime if server asks all clients to release the leases ? This looks wrong to me.

That highly depends on the DHCP infra setup.

Hm. First, the lease can still have a lifetime, can't it. Hence, the client could do a lease validation on that. Further, the client when it's coming up shall always try to reattain a lease. Only when it cannot, apply the existing lease. And for the corner case you're mentioning, there's duplicate detection on several layers throughtout the network stack, even for DHCP itself. Please revise the RFCs.

Nigh, the scenario you're providing is again if you're not in charge of both, the client and server side of DHCP.

**Comment by ssahani** [comment]
>Hm. First, the lease can still have a lifetime, can't it. Hence, the client could do a lease validation on that. Further, the client when it's coming up shall always try to reattain a lease. Only when it cannot, apply the existing lease.

The leases can be for days depending on the configuration. How is it know these lease are valid in first place if reconfigure happens . It needs to validate the leases from the server even if they valid via request .

**Comment by cherusk** [comment]
> The leases can be for days depending on the configuration. How is it know these lease are valid in first place if reconfigure happens . It needs to validate the leases from the server even if they valid via request .

Well, but normally, if the setup is centrally controlled, one chooses a client identifier, either clietn-uuid or the mac, which should be uniquely mapped to an IP. What you're describing here again is some highly mobile, rather desktopish setup.

Even networkd sports already a dhcp duplicate detection, please see. :grin: 

> DuplicateAddressDetection=
> Takes one of "ipv4", "ipv6", "both", "none". When "ipv4", performs IPv4 Duplicate Address Detection. 
>
> See https://www.freedesktop.org/software/systemd/man/systemd.network.html

That logic could be leveraged also for further lease validation, no?

Nigh, as indicated, find your constraints as highly hypothetical, since one wouldn't configure the DHCP daemon side in the way you're argumenting here in an infrastructural centralized adressing distribution.

Once more, I'm agreeing, the functionality is for specific setups, but there of invaluable benefit.

**Comment by Karlson2k** [comment]
I also make sense to preserve assigned IP (if not expired) for sleep-wakeup cycle.

**Comment by cherusk** [comment]
I've devised in improvised fashion a custom client based on systemd service means and the isc-dhclient(man 8 dhclient)[1]:

```
[Unit]
Description=Genesis Cloud Custom DHCP client
After=systemd-networkd.service
Before=multi-user.target
Wants=systemd-networkd.service

[Service]
ExecStart=+/var/lib/custom_dhclient/start.sh ${__interface}
ExecStop=+/var/lib/custom_dhclient/stop.sh ${__interface}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=sys-subsystem-net-devices-${__interface}.device
```

With **/var/lib/custom_dhclient/start.sh**:
```
#!/usr/bin/env bash

set -eEux

# external params
__interface="${1}"

__pid_file="/run/gc_dhc_${__interface}.pid"
__lease_file="/var/lib/gc_dhclient/leases/${__interface}.leases"

/sbin/dhclient  -4 -v -i -I -d \
               -pf "${__pid_file}" \
               --timeout 5 \
               -lf "${__lease_file}" -df "${__lease_file}" "${__interface}"
```

And with **/var/lib/custom_dhclient/stop.sh**:
```
#!/usr/bin/env bash

set -eEux

# external params
__interface="${1}"

__pid_file="/run/gc_dhc_${__interface}.pid"

/sbin/dhclient -x -pf "${__pid_file}"
```

Further, please find excerpts from [1]:

>  In order to keep track of leases across system reboots and server restarts, dhclient keeps a list of leases it has been assigned in the dhclient.leases file. On startup, after reading the dhclient.conf file, dhclient reads the dhclient.leases file to refresh its memory about what leases it has been assigned. 

>  Old leases are kept around in case the DHCP server is unavailable when dhclient is first invoked (generally during the initial system boot process). In that event, old leases from the dhclient.leases file which have not yet expired are tested, and if they are determined to be valid, they are used until either they expire or the DHCP server becomes available. 

Therefore, is the ISC conventions authoritative enough to bestow the sd_dhcp_client with similar functionality?

[1] https://manpages.debian.org/jessie/isc-dhcp-client/dhclient.8.en.html

**Comment by dutchalthoff** [comment]
Here is an example use-case where we encounter this issue.
When systems restart they can (and do) boot quicker than the DHCP servers. If leases are released when the systems shut down they can (and do) come up missing the IPs, hostnames, routes, DNS configs, etc. all which are configured via DHCP. In the case of larger data center operations with central config management the leases can be indefinite and may only change on command or when a new image is booted. 
This is obviously not your average user DHCP use-case scenario, but is a good and valid use of DHCP for operating at scale.

There are ways for operators to work around such issues but these hacks cascade into more issues with system.d functions we expect and depend on. For example, DNS breaks and we have to shoe string more hacks together to fix it.

We are hoping that adding this option upstream will not only make our lives easier but also help other data center operators that are moving away from static configurations to more modern operating paradigms.

Let us know what we can do to help move this forward. We are committed to solving this.

**Comment by cherusk** [comment]
Let's IPv6 take care of that conundrum eventually. ;)
