### ISSUE TITLE
hwdb: keyboard: Scancodes for (Ortek) Adesso AKB-805MAC

### ISSUE THREAD

**Issue by gwhitney** [systemd/systemd#16937]
**Is your feature request related to a problem? Please describe.**
I connected an Adesso AKB-805MAC keyboard (http://adesso.com/productmanuals/UserGuide_AKB-805MAC.pdf) to my OpenSUSE Tumbleweed machine and the row of "internet" buttons along the top were mostly dead.

**Describe the solution you'd like**
I wanted them to work as labeled, so using evtest I looked up and reassigned the relevant scancodes. The resulting `/etc/udev/hwdb.d` section I now have working is below, along with an attachment of the output of `udevadm info /dev/input/event25` as requested in `60-keyboard.hwdb`.

**Describe alternatives you've considered**
I filed this as an issue, rather than going ahead and submitting a pull request, simply because of the age of the keyboard: if you go to the last page of the user guide linked above, you'll see that the keyboard was released ca. 2003. So I wasn't at all sure that you'd want its scan codes cluttering the systemd distribution. Maybe `60-keyboard.hwdb` should refer to some online database of additional scancodes kept somewhere, rather than putting all scancodes into the source distribution? Anyhow, if on the other hand you'd like this submitted as a pull request, please just let me know -- I'd be happy to prepare one.

Thanks for the comments in `60-keyboard.hwdb` making it so easy to get an old keyboard running!

My `70-keyboard.hwdb`:
```
# Adesso AKB-805MAC (manufactured by Ortek)
evdev:input:b0003v05A4p9735*
 KEYBOARD_KEY_c0015=back
 KEYBOARD_KEY_c0012=forward
 KEYBOARD_KEY_c000c=stop
 KEYBOARD_KEY_c0018=refresh
 KEYBOARD_KEY_c00b9=search
 KEYBOARD_KEY_c0006=bookmarks
 KEYBOARD_KEY_c00a8=homepage
 KEYBOARD_KEY_c0010=mute
 KEYBOARD_KEY_c0011=volumedown
 KEYBOARD_KEY_c0014=volumeup
 KEYBOARD_KEY_c000e=close
 KEYBOARD_KEY_c00a7=print
 KEYBOARD_KEY_c0013=documents
 KEYBOARD_KEY_c000d=find
 KEYBOARD_KEY_c000f=mail
 KEYBOARD_KEY_c000a=calc
 KEYBOARD_KEY_c000b=sleep
 KEYBOARD_KEY_c0007=previoussong
 KEYBOARD_KEY_c0008=playpause
 KEYBOARD_KEY_c0009=nextsong
 KEYBOARD_KEY_c00b2=stopcd
 KEYBOARD_KEY_c0016=prog1
 KEYBOARD_KEY_c00bb=prog2
 KEYBOARD_KEY_c00b8=prog3
```
[udevadm_info.txt](https://github.com/systemd/systemd/files/5159062/udevadm_info.txt)

**Comment by poettering** [comment]
hwdb exists only for the purpose of providing device metadata like this, and it doesn't really matter if it's a kbd from today or 17y ago. If it still works, then by all means, please send this as PR and we'll merge it.

I mean, it's a USB keyboard, it's not even that exotic. should work fine with today's systems, afaics hence please send a PR
