### ISSUE TITLE
Colorize "enabled" in `systemctl status ...`

### ISSUE THREAD

**Issue by al-caveman** [systemd/systemd#16932]
**Is your feature request related to a problem? Please describe.**
Reducing reading time of output of `systemctl status ...`.

**Describe the solution you'd like**
`systemctl statatus ...` already colotizes "active (running)" into bold green.  it would be nice if "enabled" is also colorized.  If not in bold green, then maybe in just bold white.

Likewise, colorize the `disabled`s into some gray color.

This way, when we want to check if service is enabled, our eyes can only scan for colorized texts, such as bold green or bold white.  This is more convenient than scanning for word `enabled` specially that there is 2 `enabled` (one for service and one for vendor preset).

**Comment by amarjargal** [comment]
I see that this issue is quite old but by running systemctl status in current version, I see that it is not solved. Can I work on it if it's still relevant?

**Comment by medhefgo** [comment]
Of course you can.
