### ISSUE TITLE
v246 fails udev-test, test-cap-list, test-seccomp, test-execute, test-bus-track (ppc32, Big Endian)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [systemd/systemd#16942]
I noticed some test failures _(killed by signal 6 SIGABRT)_ with Gentoos systemd v245.5, v245.7 and v246 on my PowerMac G4. Earlier versions are probably affected too. Building v246 from git and running the testsuite reveals the same failures + 2 more. For details please have a look at the attached testlog.txt.

**systemd version the issue has been seen with**
v246

**Used distribution**
Gentoo
(This is Gentoo downstream bug [738456](https://bugs.gentoo.org/738456)).

**Unexpected behaviour you saw**
235/500 udev-test                                 FAIL           36.36s (exit status 1)
321/500 test-cap-list                             FAIL           0.44s (killed by signal 6 SIGABRT)
331/500 test-seccomp                              FAIL           1.48s (killed by signal 6 SIGABRT)
377/500 test-execute                              FAIL           9.30s (killed by signal 6 SIGABRT)
421/500 test-bus-track                            FAIL           0.45s (killed by signal 6 SIGABRT)

**Steps to reproduce the problem**
```
git clone https://github.com/systemd/systemd
cd systemd/ && git checkout v246
mkdir build && meson build/
ninja -j3 -C build/
cd build/ && ninja -j3 test
```

Some data about the machine:
```
System:    Kernel: 5.9.0-rc3-PowerMacG4 ppc bits: 32 Console: tty 2 
           Distro: Gentoo Base System release 2.7 
Machine:   Type: PowerPC Device System: PowerMac3 6 details: PowerMac3 6 rev: 3.3 (pvr 8001 0303) 
CPU:       Info: Dual Core 7455 altivec supported [MCP] speed: 1417 MHz 
Graphics:  Device-1: AMD RV350 [Radeon 9550/9600/X1050 Series] driver: radeon v: kernel 
           Display: server: X.org 1.20.8 driver: ati,radeon unloaded: fbdev,modesetting tty: 104x53 
Network:   Device-1: Broadcom and subsidiaries BCM4306 802.11b/g Wireless LAN driver: b43-pci-bridge 
           Device-2: Apple UniNorth 2 GMAC driver: gem 
           Device-3: gmac driver: gem 
```

[testlog.txt](https://github.com/systemd/systemd/files/5165365/testlog.txt)

**Comment by poettering** [comment]
any chance you can bisect this?

**Comment by keszybz** [comment]
```
321/500 test-cap-list                             FAIL           0.44s (killed by signal 6 SIGABRT)

--- command ---
21:51:55 PATH='/root/build/systemd/build:/sbin:/bin:/usr/sbin:/usr/bin' SYSTEMD_KBD_MODEL_MAP='/root/build/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/build/systemd/src/locale/language-fallback-map' /root/build/systemd/build/test-cap-list
--- stderr ---
Assertion 'streq(t1, t)' failed at src/test/test-cap-list.c:61, function test_capability_set_one(). Aborting.
```

This suggests some major fuckup with out handling of capabilities. But looking at the code, I don't see anything obvious. It should be fairly easy to diagnose with `gdb`.

**Comment by keszybz** [comment]
test-seccomp:
```
/* test_protect_sysctl */
Assertion 'errno == EFAULT' failed at src/test/test-seccomp.c:316, function test_protect_sysctl(). Aborting.
sysctlseccomp terminated by signal ABRT.
Assertion 'wait_for_terminate_and_check("sysctlseccomp", pid, WAIT_LOG) == EXIT_SUCCESS' failed at src/test/test-seccomp.c:329, function test_protect_sysctl(). Aborting.
```

udev-test:
```
TEST 64: textual user/group id
device '/devices/pci0000:00/0000:00:1f.2/host0/target0:0:0/0:0:0:0/block/sda' expecting node/link 'node'
  expected permissions are: root:mail:0660
  created permissions are : 0:0:0600
permissions: error
add:         ok
remove:      ok
```

**Comment by keszybz** [comment]
OK, that last one seems easy:
```
Argument "mail" isn't numeric in numeric ne (!=) at /root/build/systemd/test/udev-test.pl line 1630.
/run/udev/rules.d/udev-test.rules:1 Unknown group 'mail', ignoring
```
We're relying on `mail` group to be defined, and we shouldn't.

**Comment by ernsteiswuerfel** [comment]
> any chance you can bisect this?

I can try. Which version would be a good starting point? Is it possible to run single tests instead of the whole testsuite?

**Comment by poettering** [comment]
to run just test-bus-track, go to the build tree and type `meson test test-bug-track`.

i have no idea which version to try best as a start, maybe 244 given that is the last release before the ones you tested?

**Comment by ernsteiswuerfel** [comment]
Interesting, running the v246 testsuite now only following tests are failing:
235/500 udev-test                                 FAIL           33.72s (exit status 1)
377/500 test-execute                              FAIL           9.01s (killed by signal 6 SIGABRT)
421/500 test-bus-track                            FAIL           0.40s (killed by signal 6 SIGABRT)

In the meantime I had a few system updates. I ran the testsuite a 2nd time to be sure, results were the same.
[testlog.txt](https://github.com/systemd/systemd/files/5180189/testlog.txt)

Will try to bisect these failing tests now.

**Comment by ernsteiswuerfel** [comment]
Did not get very far in finding a working version for the bisect:

v244 same 3 testfailures
v243 same 3 testfailures
v242 same 3 testfailures
v241 build failure ([557/1699] Linking target libnss_myhostname.so.2 - FAILED: libnss_myhostname.so.2)
v240 build failure ([557/1699] Linking target libnss_myhostname.so.2 - FAILED: libnss_myhostname.so.2)
v239 build failure (meson_options.txt:49:0: ERROR: Option name debug is reserved.)
v238 build failure (meson_options.txt:49:0: ERROR: Option name debug is reserved.)
v237 build failure (meson_options.txt:49:0: ERROR: Option name debug is reserved.)

**Comment by keszybz** [comment]
It doesn't make to bissect in that case (v242 is far enough to know that this isn't a recent regression). Try gdb as suggested in https://github.com/systemd/systemd/issues/16942#issuecomment-687113759.

**Comment by poettering** [comment]
hmm, i am a bit surprised that this shows up now, i assumed that be ppc32 was actually build/check tested regularly on debian. right @mbiebl?

**Comment by mbiebl** [comment]
ppc32 is not (build-)tested on Debian (anymore). 
https://buildd.debian.org/status/package.php?p=systemd shows the list of architectures we currently build systemd for.
This includes ppc64 and ppc64el (but not ppc/powerpc)

I think after Debian 9 (stretch) ppc was removed from debian ports.

**Comment by mbiebl** [comment]
Oh my, I must be blind, sorry. powerpc is still built
https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=powerpc&ver=246.4-1&stamp=1599066691&raw=0

**Comment by mbiebl** [comment]
autopkgtest is only run for amd64 and arm64 atm though (and ppc64el semi regularly). So it depends on whether how udev-test etc are run (apparently not via meson test)

**Comment by poettering** [comment]
> Oh my, I must be blind, sorry. powerpc is still built
> https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=powerpc&ver=246.4-1&stamp=1599066691&raw=0

hmm, test-cap-list, test-seccomp pass on debian's infrastructure apparently. udev-test, test-bus-track and test-execute are skipped (presumably since debian build infra runs unpriv)...

do gentoo build systems build packages as root?

does gentoo enable libseccomp and debian disable it, or vice versa?

**Comment by mbiebl** [comment]
> hmm, test-cap-list, test-seccomp pass on debian's infrastructure apparently. udev-test, test-bus-track and test-execute are skipped (presumably since debian build infra runs unpriv)...

Correct, the build (and meson test) run as non-root user in Debian




> does gentoo enable libseccomp and debian disable it, or vice versa?

libseccomp support is enabled for the following architectures in Debian
https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/control#L48

libseccomp-dev (>= 2.3.1) [amd64 arm64 armel armhf i386 mips mipsel mips64 mips64el x32 powerpc ppc64 ppc64el s390x],

**Comment by floppym** [comment]
> do gentoo build systems build packages as root?

Based on the build log, the "userpriv" feature was enabled, which means the tests were running as the "portage" user (uid 250).

> does gentoo enable libseccomp and debian disable it, or vice versa?

From the build log, libseccomp was enabled.

```
Message: systemd 245
         split /usr:                        true
         split bin-sbin:                    true
         prefix directory:                  /usr
         rootprefix directory:              /
         sysconf directory:                 /etc
         include directory:                 /usr/include
         lib directory:                     /usr/lib
         rootlib directory:                 /usr/lib
         SysV init scripts:                 /etc/init.d
         SysV rc?.d directories:            /etc/rc.d
         PAM modules directory:             /lib/security
         PAM configuration directory:       /etc/pam.d
         RPM macros directory:              /usr/lib/rpm/macros.d
         modprobe.d directory:              /lib/modprobe.d
         D-Bus policy directory:            /usr/share/dbus-1/system.d
         D-Bus session directory:           /usr/share/dbus-1/services
         D-Bus system directory:            /usr/share/dbus-1/system-services
         bash completions directory:        /usr/share/bash-completion/completions
         zsh completions directory:         /usr/share/zsh/site-functions
         extra start script:                /etc/rc.local
         debug shell:                       /bin/sh @ /dev/tty9
         TTY GID:                           5
         users GID:                         -
         maximum system UID:                999
         maximum system GID:                999
         minimum dynamic UID:               61184
         maximum dynamic UID:               65519
         minimum container UID base:        524288
         maximum container UID base:        1878982656
         /dev/kvm access mode:              0666
         render group access mode:          0666
         certificate root directory:        /etc/ssl
         support URL:                       https://gentoo.org/support/
         nobody user name:                  nobody
         nobody group name:                 nobody
         fallback hostname:                 localhost
         symbolic gateway hostnames:        _gateway
         default DNSSEC mode:               allow-downgrade
         default DNS-over-TLS mode:         no
         default cgroup hierarchy:          unified
         default net.naming-scheme setting: latest
         default KillUserProcesses setting: false
         default locale:                    C.UTF-8
         default user $PATH:                (same as system services)
         systemd service watchdog:          3min
         default DNS servers:               1.1.1.1
                                            8.8.8.8
                                            1.0.0.1
                                            8.8.4.4
                                            2606:4700:4700::1111
                                            2001:4860:4860::8888
                                            2606:4700:4700::1001
                                            2001:4860:4860::8844
         default NTP servers:               0.gentoo.pool.ntp.org
                                            1.gentoo.pool.ntp.org
                                            2.gentoo.pool.ntp.org
                                            3.gentoo.pool.ntp.org
         time epoch:                        1587127032 (2020-04-17T12:37:12+00:00)
         static libsystemd:                 true
         static libudev:                    true
         efi arch:                          ppc
         
         enabled features: PAM, libfdisk, IMA, SECCOMP, SMACK, lz4, ACL, gcrypt, gnutls, openssl, libidn2, elfutils, binfmt, vconsole, quotacheck, tmpfiles, environment.d, sysusers, firstboot, randomseed, backlight, rfkill, logind, machined, portabled, userdb, hostnamed, timedated, timesyncd, localed, networkd, resolve, coredump, pstore, polkit, efi, kmod, pcre2, blkid, dbus, glib, nss-myhostname, nss-mymachines, nss-resolve, nss-systemd, hwdb, tpm, man pages, man page indices, SysV compat, utmp, ldconfig, hibernate, adm group, wheel group, gshadow, link-udev-shared, link-systemctl-shared, link-networkd-shared, link-timesyncd-shared
         
         disabled features: libcryptsetup, pwquality, p11kit, AUDIT, AppArmor, SELinux, zlib, xz, bzip2, qrencode, microhttpd, libcurl, idn, libidn, libiptc, repart, homed, importd, DNS-over-TLS(gnutls), DNS-over-TLS(openssl), legacy pkla, gnu-efi, xkbcommon, html pages, debug hashmap, debug mmap cache, debug siphash, valgrind, trace logging

```

**Comment by ernsteiswuerfel** [comment]
> This suggests some major fuckup with out handling of capabilities. But looking at the code, I don't see anything obvious. It should be fairly easy to diagnose with `gdb`.

_421/500 test-bus-track FAIL 0.40s (killed by signal 6 SIGABRT)_
```
# PATH='/root/build/systemd/build:/sbin:/bin:/usr/sbin:/usr/bin' SYSTEMD_KBD_MODEL_MAP='/root/build/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/build/systemd/src/locale/language-fallback-map' gdb /root/build/systemd/build/test-bus-track

[...]
Reading symbols from /root/build/systemd/build/test-bus-track...
(gdb) run
Starting program: /root/build/systemd/build/test-bus-track 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Assertion 'r >= 0' failed at src/libsystemd/sd-bus/test-bus-track.c:83, function main(). Aborting.

Program received signal SIGABRT, Aborted.
0x00257c40 in __libc_signal_restore_set (set=0xbfffecd8) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
86	  INTERNAL_SYSCALL_CALL (rt_sigprocmask, err, SIG_SETMASK, set, NULL,
```

_377/500 test-execute FAIL 9.01s (killed by signal 6 SIGABRT)_
```
 # PATH='/root/build/systemd/build:/sbin:/bin:/usr/sbin:/usr/bin' SYSTEMD_KBD_MODEL_MAP='/root/build/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/build/systemd/src/locale/language-fallback-map' gdb /root/build/systemd/build/test-bus-track

Reading symbols from /root/build/systemd/build/test-bus-track...
(gdb) run
# PATH='/root/build/systemd/build:/sbin:/bin:/usr/sbin:/usr/bin' SYSTEMD_KBD_MODEL_MAP='/root/build/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/build/systemd/src/locale/language-fallback-map' gdb /root/build/systemd/build/test-execute

[...]
exec-dynamicuser-fixeduser-adm.service: Executing: /bin/sh -x -c 'test "$(id -nG)" = "adm" && test "$(id -ng)" = "adm" && test "$(id -nu)" = "adm"'
++ id -nG
+ test 'adm sys disk' = adm
Received SIGCHLD from PID 1619 (sh).
Child 1619 (sh) died (code=exited, status=1/FAILURE)
exec-dynamicuser-fixeduser-adm.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
exec-dynamicuser-fixeduser-adm.service: Child 1619 belongs to exec-dynamicuser-fixeduser-adm.service.
exec-dynamicuser-fixeduser-adm.service: Main process exited, code=exited, status=1/FAILURE
exec-dynamicuser-fixeduser-adm.service: Failed with result 'exit-code'.
exec-dynamicuser-fixeduser-adm.service: Service will not restart (restart setting)
exec-dynamicuser-fixeduser-adm.service: Changed start -> failed
exec-dynamicuser-fixeduser-adm.service: Unit entered failed state.
Spawning thread to nuke /tmp/systemd-private-bd3f7593f8e64bcfbb592dace7b7975e-exec-dynamicuser-fixeduser-adm.service-P3F4VW
[New Thread 0xb6bff3a0 (LWP 1621)]
Spawning thread to nuke /var/tmp/systemd-private-bd3f7593f8e64bcfbb592dace7b7975e-exec-dynamicuser-fixeduser-adm.service-FomS2W
[New Thread 0xb75ba3a0 (LWP 1622)]
[Thread 0xb6bff3a0 (LWP 1621) exited]
UID 3 is no longer referenced, cleaning up its IPC.
GID 4 is no longer referenced, cleaning up its IPC.[Thread 0xb75ba3a0 (LWP 1622) exited]

Failed to connect to nscd socket: No such file or directory
Failed to connect to nscd socket: No such file or directory
	PID: 1619
	Start Timestamp: Fri 2020-09-11 00:53:35 CEST
	Exit Timestamp: Fri 2020-09-11 00:53:35 CEST
	Exit Code: exited
	Exit Status: 1
test_exec_dynamicuser: exec-dynamicuser-fixeduser-adm.service: exit status 1, expected 0

Thread 1 "test-execute" received signal SIGABRT, Aborted.
0xb7a74c40 in __libc_signal_restore_set (set=0xbfffec18) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
86	  INTERNAL_SYSCALL_CALL (rt_sigprocmask, err, SIG_SETMASK, set, NULL,
```

**Comment by poettering** [comment]
test-bus-track tries to connect to the system or user bus, if it finds one. If that fails because none is running it skips the test. Here we suceed to connect initially, but we then fail when executing the first operation on it. This means dbus is running but then refuses to talk to us. Question is why. Anything in the logs of the dbus daemon?

**Comment by ernsteiswuerfel** [comment]
This is the output of `journalctl -xe` while running the tests and output gathered via `dbus-monitor --system` while running the tests.
[journalctl.log](https://github.com/systemd/systemd/files/5264247/journalctl.log)
[dbus.log](https://github.com/systemd/systemd/files/5264250/dbus.log)

**Comment by poettering** [comment]
If you run only test-bus-track from the build tree, what happens in the dbus logs? 

is this dbus-daemon or dbus-broker?

if you turn on debug logging in dbus-daemon/broker, do you see something then?

**Comment by ernsteiswuerfel** [comment]
Gentoo is running dbus-daemon by default as it seems.

Please find the log attached when test-bus-track is run only. But how would I get debug logging in dbus? 

Dbus was built with following (default) settings:
`/var/tmp/portage/sys-apps/dbus-1.12.18/work/dbus-1.12.18/configure --prefix=/usr --build=powerpc-unknown-linux-gnu --host=powerpc-unknown-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/dbus-1.12.18 --htmldir=/usr/share/doc/dbus-1.12.18/html --with-sysroot=/ --libdir=/usr/lib --localstatedir=/var --enable-static --disable-verbose-mode --disable-asserts --disable-checks --disable-selinux --disable-libaudit --disable-apparmor --enable-inotify --disable-kqueue --disable-elogind --enable-systemd --enable-user-session --disable-embedded-tests --disable-modular-tests --disable-stats --with-session-socket-dir=/tmp --with-system-pid-file=/run/dbus.pid --with-system-socket=/run/dbus/system_bus_socket --with-systemdsystemunitdir=/lib/systemd/system --with-dbus-user=messagebus --with-x --enable-xml-docs --disable-doxygen-docs`
[dbus_test-bus-track.log](https://github.com/systemd/systemd/files/5279469/dbus_test-bus-track.log)

**Comment by poettering** [comment]
see dbus-daemon(1) man page, part about "DEBUGGING"

**Comment by poettering** [comment]
if the tests are skipped, and you boot a machine from the results, do things work then? in particular, does all the dbus stuff work?

**Comment by ernsteiswuerfel** [comment]
Sorry for the long delay, I was rather busy last weeks! I will check out how to work with this dbus debugging stuff next week.

During regular desktop usage the G4 shows no systemd or dbus glitches I would notice, despite these tests failing. This was for v245 and v246 as v247 is not available on Gentoo yet.

**Comment by poettering** [comment]
I'll unpin this now. Given this is so far Gentoo specific and only with exotic arch I don't think we need to keep this pinned. Happy to merge a fix, but I figure the work for that must be done by someone who possesses such hw. Hope that makes sense.

**Comment by ernsteiswuerfel** [comment]
Finally I foud some time and re-tested after a hint on IRC #gentoo-powerpc. Turned out that I needed to turn off Gentoo FEATURES _pid-sandbox ipc-sandbox_, where _ipc-sandbox_ is turned on by default.

247_rc2 passes tests after that.
[testlog.txt](https://github.com/systemd/systemd/files/5567815/testlog.txt)
