### ISSUE TITLE
Enhancement: Add label directive to unit files

### ISSUE THREAD

**Issue by 0asys** [systemd/systemd#1694]
I appreciate a direcitve Label in unit files to mark some units togheter and filtering it.

eg. all services running by a company

> [Unit]
> Description=Service for Company Nagios
> Label=mycompanyservice
> 
> [Unit]
> Description=Service for Company Postfix
> Label=mycompanyservice

ex. systemctl list-units mycompanyservice should show/filter all Units labeled with the pattern.
I didn't found any other existing alternative or working possibility in the documentation.

**Comment by poettering** [comment]
Why not just give all units of one customer the same name prefix? i.e. give customer "foo" units foo-nagios.service, foo-mysql.service, foo-postifx.service?

Or, even better, make this all instances of templates:

nagios@foo.service, mysql@foo.service, postfix@foo.service, all for the same customer "foo".

I am not convinced we should anything beyond that I must say, as it's too opaque...

**Comment by johannbg** [comment]
You would actually create customer isolated container and allocate system resources ( cpu/memory/network/storage ) to it. 

The only thing systemd lacks in this regard to be "business completed" is built in metric collection and reporting which should not be that difficult to implement although I'm not sure if power conception per container can be collected.
