### ISSUE TITLE
.network drop-in does not override nameservers but always appends

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#16959]
**systemd version the issue has been seen with**
> systemd 245 (245.6-117-g5dd8a7b+)

**Used distribution**
 > Flatcar Container Linux by Kinvolk alpha (2605.1.0)

**Expected behaviour you didn't see**
 When setting the following in a drop-in:
```
[Network]
DNS=
DNS=<actual server>
```
I'd expect it to override the previous list of DNS servers. 

**Unexpected behaviour you saw**
It appends to the list of DNS servers.  

**Steps to reproduce the problem**

I have a network unit which is shipped by the cloud OS image:
```
# /etc/systemd/05-bond0.network
[Match]
Name=bond0
[Network]
DNS=8.8.8.8
DNS=8.8.4.4
[Address]
Address=147.75.100.101
[Route]
Destination=0.0.0.0/0
Gateway=147.75.100.100
[Address]
Address=2604::1380::2000:abcd::3
[Route]
Destination=::/0
Gateway=2604::1380::2000:abcd::2
```

And I override it with a drop-in:
```
# /etc/systemd/network/05-bond0.network.d/00-dns.conf
[Network]
DNS=
DNS=2001:4860:4860::8888
DNS=2001:4860:4860::8844
```

I get the following `/etc/resolv.conf`
```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 147.75.207.207
nameserver 147.75.207.208
nameserver 2001:4860:4860::8888
# Too many DNS servers configured, the following entries may be ignored.
nameserver 2001:4860:4860::8844
```

Whilst I expected:

```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```

**Comment by yuwata** [comment]
This is already fixed by d96edb2c6e7014e93e6713c79a698c91463c8929 which is included in v246.

@keszybz WDYT about to backport the commit to v245-stable?

**Comment by keszybz** [comment]
> This is already fixed by [d96edb2](https://github.com/systemd/systemd/commit/d96edb2c6e7014e93e6713c79a698c91463c8929) which is included in v246.

Hmm, d96edb2c6e7014e93e6713c79a698c91463c8929 is about log levels, are you sure that's the right commit?

**Comment by yuwata** [comment]
Yeah, I should split the commit. But it also fixes this. Please see the change in `config_parse_dns()`.

**Comment by arianvp** [comment]
A backport would be very appreciated.

Do we backport the entire commit or just the snippet that fixes this bug?

**Comment by keszybz** [comment]
https://github.com/systemd/systemd-stable/commit/25f1b107cd4ea5b00c919e6fe1cc68d119be2e1e

**Comment by yuwata** [comment]
Thank you!
