### ISSUE TITLE
Please document how to change the default umask for `systemd --user` with a per-user configuration file

### ISSUE THREAD

**Issue by rrthomas** [systemd/systemd#16963]
**systemd version the issue has been seen with**
> 245.4

**Used distribution**
 > Ubuntu 20.04

See issue #6077, which has now been fixed (thanks to all who were involved).

`systemd.exec(5)` says:

> Hence changing the default value of a user instance, either via UMask= or via a PAM module, will affect the user instance itself and all user units started by the user instance unless a user unit has specified its own UMask=.

However, I cannot discover how to change "the default value of a user instance" using a file in the user's home directory. Apologies if I have overlooked something, but over an hour of reading the systemd man pages, and searching online, and reading past issues and forum threads has failed to give me a working method. I can use PAM (specifically `pam_umask`) fine, but I would rather have this configuration in the user's home directory, to avoid the necessity to need root privileges (for example, to edit a system-level systemd configuration file, or to edit `/etc/login.defs` on my Ubuntu machine, or, the best option I have found so far, to run `chfn -o`, which again needs root).

If it is possible to achieve this, then it would be great to document the method in `systemd.exec(5)`.

**Comment by poettering** [comment]
systemd does not offer an option for unpriv users to change the account-wide umask themselves.

You can either use pam_umask for this, but for that check the documentation of pam_umask itself.

Or if you use systemd-homed or some other user mgmt framework that implements https://systemd.io/USER_GROUP_API you can encode the umask for an account in the user record itself. But that typically requires admin privs too to modify.

We should probably add a reference to the latter to the doc you linked, but other than that we cannot really help you: there's no unpriv way that would allow users to change their own umask for the whole account. Sorry.

**Comment by rrthomas** [comment]
Thanks for the explanation, @poettering. The one thing I'm still unclear on is what the documentation is referring to in the section I quoted, that is:

> …changing the default value of a user instance…via UMask=

Even if that were via a system file, it would be good to know about!

**Comment by poettering** [comment]
The `user@.service` templated system service is instantiated for each user. It's a system service like any other, hence you can extend it via drop-ins, and thus configure UMask= for it, like for any other system service. e.g.

```
mkdir -p /etc/systemd/system/user@1000.service.d
cat >  /etc/systemd/system/user@1000.service.d/umask.conf<<EOF
[Service]
UMask=0007
EOF
systemctl daemon-reload
```

**Comment by rrthomas** [comment]
Thanks again, all is clear now. So, that service is a system service and hence can't be changed by the user.

**Comment by poettering** [comment]
> Thanks again, all is clear now. So, that service is a system service and hence can't be changed by the user.

Correct
