### ISSUE TITLE
remove SmackFileSystemRootLabel= again

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#1696]
As it turns out, we might not actually need it. If so, let's kill it before the next release.

**Comment by poettering** [comment]
Also see:

https://github.com/systemd/systemd/pull/1664#issuecomment-151507778

and

http://lists.freedesktop.org/archives/systemd-devel/2015-October/034743.html

**Comment by karelzak** [comment]
@again4you please, try it without systemd -- it means manually mount(8) on command line. Now libmount supports:

   smackfsdef=, smackfsfloor=, smackfshat=, smackfsroot= and  smackfstransmute=

mount options and /sys/fs/smackfs is used to detect if smack is enabled. You need util-linux compiled --with-smack. You can use

   LIBMOUNT_DEBUG=all  mount /tmp ....

or strace to see what mount(8) does with your mount options. Thanks.

**Comment by poettering** [comment]
@again4you ping?

**Comment by poettering** [comment]
@again4you could you please comment? Otherwise we'll remove the option again for the upcoming release.

**Comment by poettering** [comment]
OK, I figure we should remove the option, as it apparently is unnecessary and done by mount anyway, implicitly, and @again4you has not responded so far.

**Comment by poettering** [comment]
OK, I prepped a patch that removes it again in #1864.
