### ISSUE TITLE
When shutting down, reset_arguments() will overwrite configured ShutdownWatchdogSec

### ISSUE THREAD

**Issue by egtvedt** [systemd/systemd#16991]
**systemd version the issue has been seen with**
> v245, but AFAICT from code also present in v246 and HEAD.

**Used distribution**
 > Embedded

**Expected behaviour you didn't see**
 > Respect the ShutdownWatchdogSec value in system.conf.

**Unexpected behaviour you saw**
 > ShutdownWatchdogSec reset to default value.

**Steps to reproduce the problem**
In src/core/main.c (HEAD) line 2871 there is a call to reset_arguments(), this will reset ShutdownWatchdogSec to default value unconditionally. I would assume this is not the intended logic with regards to ShutdownWatchdogSec ?

**Comment by poettering** [comment]
Yeah, this looks broken. @keszybz you changed that last, what was the intention here?
