### ISSUE TITLE
homed: Unable to use sudo in the terminal, but pkexec works just fine

### ISSUE THREAD

**Issue by viggy96** [systemd/systemd#17014]
**systemd version the issue has been seen with**
> 246.4

**Used distribution**
 > Manjaro

**Expected behaviour you didn't see**
 > sudo accepts password and runs specified command

**Unexpected behaviour you saw**
 > sudo doesn't accept password, instead saying "Sorry, try again."

**Steps to reproduce the problem**
1. Create a user using homectl. 
2. Try using sudo in the terminal. 
Note: I have seen this behavior with both a LUKS backed user, and now a fscrypt backed user. 

For example:
`sudo su` does not work
however,
`pkexec su` does work

**Comment by poettering** [comment]
Hmm, what? what is "sudo su" supposed to mean? you become super user and then you become super user again?

So what actually fails? the "sudo"? or the "su"?

What's in the logs?

does your pam stack for sudo contain pam_systemd_home properly?

**Comment by viggy96** [comment]
@poettering I think I got it now, I didn't see that I needed to add pam_systemd_home to a pam config in any of the guides that I followed to start using systemd-homed. 

Does this look good for /etc/pam.d/sudo?
"sudo" now works, but I want to make sure I didn't miss anything. I only added the "pam_systemd_home.so" line.
```
#%PAM-1.0

auth required pam_env.so
auth sufficient pam_fprintd.so
auth sufficient pam_unix.so try_first_pass likeauth nullok
auth sufficient pam_systemd_home.so
auth required pam_deny.so
auth		include		system-auth
account		include		system-auth
session		include		system-auth
```

**Comment by poettering** [comment]
That looks roughly OK, see man page of pam_systemd_home + pam_systemd.

Anyway, I guess we can close this now, given this has been resolved.
