### ISSUE TITLE
systemd build fails on reiser4 4.0.2

### ISSUE THREAD

**Issue by Metztli** [systemd/systemd#17013]
[Metztli Reiser4](https://sourceforge.net/projects/metztli-reiser4/) hack based on Debian Buster 10.5 for AMD64.
I am utilizing the current [Debian packaging for systemd 246.4-1](https://packages.debian.org/sid/systemd) to create backport package but systemd from git build stops during tests
390/562 test-acl-util                           FAIL     0.12 s (killed by signal 6 SIGABRT)
...
437/562 test-path                               FAIL    30.69 s (exit status 1)
...
458/562 test-journal                            TIMEOUT 30.53 s

Bypassing those tests in systemd/src/test/meson.build then build stops at

test-journal-interleaving.c

Reiser4, currently, does not support ACLs, I have seen that message frequently in dmesg output. Notwithstanding, if I omit those tests above, the systemd build completes but the system is unusable as disk dependency fail issues are introduced.

Attached is the last fragment of the initial build attempt. uname -a
Linux tezcatlipoca 5.7.0-3+reiser4.0.2-amd64 #1 SMP Debian 5.7.19-1+reiser4.0.2 (2020-09-03) x86_64 GNU/Linux

[systemd-build-fail.txt](https://github.com/systemd/systemd/files/5204625/systemd-build-fail.txt)

**Comment by poettering** [comment]
Hmm, not sure it is wise to use an fs that can't do ACLs for /tmp. But i guess we could change that.

If have no idea about the other issues. What makes you think systemd is at fault?

**Comment by Metztli** [comment]
> What makes you think systemd is at fault?

I am having issues with the Debian official systemd package, thus it is the first time I attempt a newer systemd build.

I tried the build on a relatively clean reiser4 sfrn 4.0.2 installation --after the initial build failed similarly in my usual development reiser4 environment. I have installed all dependencies as listed in debian/control file. Yet in both environments the build fails during those tests. I could not go any further without anyone potentially offering some insight.

I just filed the issue in case someone could accommodate reiser4 peculiarities as I do not think anyone is building systemd in a reiser4 file system environment. I might try to build on [Reiser5](https://sourceforge.net/projects/debian-reiser4/files/) later and see if I have better luck.

Best Professional Regard.

**Comment by Metztli** [comment]
@poettering, thank you for your fix #17032. It fixed the failing test(s) issue.

Best Professional Regards.

**Comment by Metztli** [comment]
Probably I spoke too soon. Although @poettering's fix made the test-acl-util be skipped, there are three(3) test-journal-xy.c files which produce a TIMEOUT of approximately 30-31 s and thus these are considered as failed:
test-journal                            TIMEOUT 30.32 s
...
463/562 test-journal-stream                     TIMEOUT 30.17 s
...
468/562 test-journal-interleaving               TIMEOUT 31.02 s

I am unaware of how that threshold is arrived at to be considered a failure.

Initially I thought the headers for these files were on Debian side. Notwithstanding, upon reviewing src/test, src/journal/, src/basic, etc., listings, I can see that all those *.c and *.h files are provided as part of systemd.

Furthermore, I can also read there are some adjustments for btrfs in the code. I believe it is probably the case that test-journal.c, test-journal-stream.c,  test-journal-interleaving,c, as well as some of the headers they invoke, i.e., 
journal-authenticate.h
journal-file.h
journal-vacuum.h
journal-internal.h
may not be compliant with Reiser4 Software Format Release Number (SFRN) 4.0.2, where the builds were attempted.

I reopened this issue but there may be no inclination by systemd developers and/or volunteers to fix it and thus I understand that the issue may be closed again.

[test-journal-x-fail.txt](https://github.com/systemd/systemd/files/5212173/test-journal-x-fail.txt)

Thank you, anyway.

**Comment by poettering** [comment]
hmm, so this leaves the timeout things unsolved, iiuc?

maybe reiser4 is just terribly slow for this access pattern? i.e. do the tests progress? or just hang? do they finish eventually if you prolong the test timeouts (i.e. use meson's `-t` switch for multiplying the test timeouts).

Either way: if the test sjust become awfully slow or hang entirely on reiser4 this appears to be an issue in reiser4 mostly and would need to be fixed there.

**Comment by Metztli** [comment]
> hmm, so this leaves the timeout things unsolved, iiuc?

Not at all, @poettering. Your commit to skip test-acl-util proved to be the solution.
> 
> maybe reiser4 is just terribly slow for this access pattern? i.e. do the tests progress? or just hang? do they finish eventually if you prolong the test timeouts (i.e. use meson's `-t` switch for multiplying the test timeouts).

Fact is my local reiser4 environment is an ageing Intel -based platform. Although I still build reiser4 kernels and related utilities, for whatever reason my attempts to build systemd choked it.

> 
> Either way: if the test sjust become awfully slow or hang entirely on reiser4 this appears to be an issue in reiser4 mostly and would need to be fixed there.

I spinned out a reiser4 instance customized for Google Compute Engine (GCE) and the systemd build took approximately seven(7) minutes to complete within the Debian packaging framework.
 If interested in further details: https://metztli.blog/amatl/reiser-nahui/systemd .

I really appreciate your actionable commit, @poettering. Thank you.

Best Professional Regards.
