### ISSUE TITLE
A more reliable way to manage the backlight restoring

### ISSUE THREAD

**Issue by Digitalone1** [systemd/systemd#17011]
Reopening #16630.

I though someone at kernel side patched the issue of backlight not restoring on amdgpu cards.

5.8.6 [changelog](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.6) reported the change commit:

> commit 54dc92e1900895401135ffbc95586dae30309a14
> Author: Alexander Monakov <amonakov@ispras.ru>
> Date:   Tue Aug 4 23:13:13 2020 +0300
> 
>     drm/amd/display: use correct scale for actual_brightness
>     
>     commit 69d9f4278d0f9d24607645f10e5ac5c59c77a4ac upstream.
>     
>     Documentation for sysfs backlight level interface requires that
>     values in both 'brightness' and 'actual_brightness' files are
>     interpreted to be in range from 0 to the value given in the
>     'max_brightness' file.
>     
>     With amdgpu, max_brightness gives 255, and values written by the user
>     into 'brightness' are internally rescaled to a wider range. However,
>     reading from 'actual_brightness' gives the raw register value without
>     inverse rescaling. This causes issues for various userspace tools such
>     as PowerTop and systemd that expect the value to be in the correct
>     range.
>     
>     Introduce a helper to retrieve internal backlight range. Use it to
>     reimplement 'convert_brightness' as 'convert_brightness_from_user' and
>     introduce 'convert_brightness_to_user'.

I had the kernel and systemd package blacklisted. Half an hour ago I updated both, but brightness keeps not restoring at boot.

I don't understand. Is systemd method not good at it or the kernel patch did nothing?

**systemd version the issue has been seen with**
> 246.4-1

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Brightness restoring at startup

**Unexpected behaviour you saw**
 > Brightness is not restored at the startup

**Comment by yuwata** [comment]
Please show actual_brightness, brightness, max_brightness of the device. Also, show saved brightness in /var/lib/systemd/backlight.

Also, do you have any relevant log message in journal?

**Comment by Digitalone1** [comment]
If you don't tell me where to pick them, I can't show you nothing.

Saved values are:
`/var/lib/systemd/backlight/backlight:amdgpu_bl0` > 249 0
`/var/lib/systemd/backlight/pci-0000:00:01.0:backlight:radeon_bl0` > 108
`/var/lib/systemd/backlight/backlight:amdgpu_bl0` > 116

I don't have nothing in the journal at the moment because I disabled systemd to use brillo to restore the backlight.

It's a shame that an app not maintained anymore is working while systemd is failing in this simple task.

**Comment by yuwata** [comment]
> If you don't tell me where to pick them, I can't show you nothing.

You can find the relevant backlight device at /sys/class/backlight.

> I don't have nothing in the journal at the moment because I disabled systemd backlight restoring service to use brillo to restore the brightness at the boot (obviously I enabled it when I had the previous working version).

Hmm? You enabled brillo? systemd-backlight@.service is automatically started by udev rule. Maybe, systemd-backlight and brillo may conflict each other. Please try again without brillo.

**Comment by Digitalone1** [comment]
`/sys/class/backlight/amdgpu_bl0/actual_brightness` > 249
`/sys/class/backlight/amdgpu_bl0/brightness` > 108
`/sys/class/backlight/amdgpu_bl0/max_brightness` > 255

> Hmm? You enabled brillo? systemd-backlight@.service is automatically started by udev rule. Maybe, systemd-backlight and brillo may conflict each other. Please try again without brillo.

I didn't have brillo enabled before the update. With the update, the backlight restoring by systemd is not working, so I disabled it and enabled brillo which is the only option I have now.

**Comment by yuwata** [comment]
Please disable brillo, and try to use systemd-backlight@.service. Otherwise, we have no way to help your issue.

Or, if you really do not want to use systemd-backlight@.service, then please report the issue to brillo or kernel support forum. We do not manage brillo.

**Comment by Digitalone1** [comment]
Disabled brillo.
Reenabled systemd backlight service.

Restarted and the brightness is at the max. Reduced it because it's too bright. Restarted another time and it's at the max again.

```
systemctl status systemd-backlight@backlight:amdgpu_bl0.service 
 
● systemd-backlight@backlight:amdgpu_bl0.service - Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0
     Loaded: loaded (/usr/lib/systemd/system/systemd-backlight@.service; static)
     Active: active (exited) since Fri 2020-09-11 07:56:27 CEST; 6min ago
       Docs: man:systemd-backlight@.service(8)
    Process: 290 ExecStart=/usr/lib/systemd/systemd-backlight load backlight:amdgpu_bl0 (code=exited, status=0/SUCCESS)
   Main PID: 290 (code=exited, status=0/SUCCESS)

set 11 07:56:27 hp255g5arch systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
set 11 07:56:27 hp255g5arch systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```

No errors from the service. Nothing relevant from the journal except the 2 lines already shown above.

Disabled systemd backlight service.
Reenabled brillo, restarted the system and the backlight is restored properly at the boot.

**Comment by yuwata** [comment]
Thanks. Could you enable to generate debugging logs, and try one more time? The debugging log can be generated by creating the following drop-in config:
```
# /etc/systemd/system/systemd-backlight@.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by Digitalone1** [comment]
These were the values with systemd backlight service enabled (and brillo disabled):

`/var/lib/systemd/backlight/pci-0000:00:01.0:backlight:amdgpu_bl0` > 249 0
`/var/lib/systemd/backlight/pci-0000:00:01.0:backlight:radeon_bl0` > 108
`/var/lib/systemd/backlight/backlight:amdgpu_bl0` > 116

`/sys/class/backlight/amdgpu_bl0/actual_brightness` > 249
`/sys/class/backlight/amdgpu_bl0/brightness` > 249
`/sys/class/backlight/amdgpu_bl0/max_brightness` > 255

For reference:
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tree/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c?id=69d9f4278d0f9d24607645f10e5ac5c59c77a4ac
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/commit/?id=69d9f4278d0f9d24607645f10e5ac5c59c77a4ac

Seeing the code, the values are rescaled, but I don't know which variable is affected. It seems only `brightness`. Anyway `actual_brightness` seems to be stuck at 249.

Can you please tell me why you are picking `actual_brightness`? Can you pick `brightness` for amdgpu and give and end to this issue? Thanks.

**Comment by Digitalone1** [comment]
> Thanks. Could you enable to generate debugging logs, and try one more time? The debugging log can be generated by creating the following drop-in config:
> 
> ```
> # /etc/systemd/system/systemd-backlight@.service.d/override.conf
> [Service]
> Environment=SYSTEMD_LOG_LEVEL=debug
> ```

Not now. Don't have time for this, sorry.

**Comment by Digitalone1** [comment]
Thanks for your work @yuwata @poettering
