### ISSUE TITLE
systemd-cryptsetup: parse cipher names with embedded comma

### ISSUE THREAD

**Issue by nebulakl** [systemd/systemd#17035]
**systemd version the issue has been seen with**
> 246.4-1-arch

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Encrypted device gets decrypted without error.

**Unexpected behaviour you saw**
 > `systemd-cryptsetup.service` complains 

```
systemd[1]: Starting Cryptography Setup for foo...
systemd-cryptsetup[346]: Encountered unknown /etc/crypttab option 'aes-adiantum-plain64', ignoring.
systemd-cryptsetup[346]: Set cipher xchacha12, mode plain, key size 256 bits for device /dev/disk/by-id/xxx.
systemd-cryptsetup[346]: device-mapper: reload ioctl on   failed: No such file or directory
systemd-cryptsetup[346]: Failed to activate with key file '/path/to/decryptionkey'. (Key file missing?)
systemd-cryptsetup[346]: Loading of cryptographic parameters failed: Invalid argument
systemd[1]: systemd-cryptsetup@foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-cryptsetup@foo.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Cryptography Setup for foo.
```

**Steps to reproduce the problem**

1. Write something similar to the following in `/etc/crypttab`

```
foo /dev/bar /path/to/decryptionkey cipher=xchacha12,aes-adiantum-plain64,plain
```
2. Reboot

**Comment by poettering** [comment]
hmm? "aes-adiantum-plain64" is no a recognized crypttab option, what makes you think it was?

**Comment by nebulakl** [comment]
Adiantum cipher is called `xchacha12,aes-adiantum-plain64` or `xchacha20,aes-adiantum-plain64` and there is a comma in between.

I can run `cryptsetup` like this to decrypt the drive
```bash
cryptsetup --cipher=xchacha12,aes-adiantum-plain64 --key-file=/keyfile open --type plain /dev/encrypteddrive fancyname
```
but I don't know how to translate that to `crypttab`, because the comma in the cipher name seems to break `systemd-cryptsetup-generator`

**Comment by poettering** [comment]
hmm, we'll have to add some form of escaping, if "," now has two meanings. Stupid choice of characters by the kernel there... :-(

i.e. `cipher=xchacha12\,aes-adiantum-plain64,plain` or so would have to be the string to use, so that the first comma is escaped and thus not interpreted by systemd-cryptsetup.
