### ISSUE TITLE
systemd-boot incorrect error message

### ISSUE THREAD

**Issue by damianatorrpm** [systemd/systemd#17036]
Product: systemd-boot v246.1-1.fc33

When an entry.conf is correct and associated kernel / initrd / efi files are found
the entry is shown in sd-boot menu.

When the ***file** is present but invalid (0 bytes - nautilus managed to not copy it correctly)
the error message upon loading that entry is that the kernel can not be found.

It really should say the kernel file is bad, but not that it was not found.

EDIT: file = kernel file

**Comment by poettering** [comment]
What's the precise error you are seeing? We do not generate an error like that ourselves.

**Comment by damianatorrpm** [comment]
> What's the precise error you are seeing? We do not generate an error like that ourselves.

Error loading \ostree\fedora-longHash\kernel-version not found.

**Comment by poettering** [comment]
"\ostree" is really a path in the ESP? Are you sure?

The error message you see is printed here:
https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L2249

We simply display the error code he firmware reported to us. Hence, either your fimrware is simply returning bogus errors, in which case we can do little about it, or your kernel is not actually installed at the referenced path in the ESP. Is it?

**Comment by damianatorrpm** [comment]
> "\ostree" is really a path in the ESP? Are you sure?
> 
Yes, certain the root of the fat formatted efi partion has a folder named /ostree.

> The error message you see is printed here:
> https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L2249
> 
> We simply display the error code he firmware reported to us. Hence, either your fimrware is simply returning bogus errors, in which case we can do little about it, or your kernel is not actually installed at the referenced path in the ESP. Is it?
Like in the original bug description, it exists but is a bad file due to nautilus copying not correctly.
It should report bad file, not file not found.

**If** the efi firmware is what's reports this I understand, this can not be changed (**close**).

**Comment by keszybz** [comment]
It doesn't seem to be a problem with our code.
