### ISSUE TITLE
Allow to execute user service into dedicated namespace if pam_namespace enabled

### ISSUE THREAD

**Issue by bobsaintcool** [systemd/systemd#17043]
**Is your feature request related to a problem? Please describe.**
When enabling [pam_namespace(8)](https://www.man7.org/linux/man-pages/man8/pam_namespace.8.html) on my system I've hard time to make a use of user services started by systemd.

As `systemd --user` start service into a different mount namespace that the one the user is. 

Let's say that my `/etc/security/namespace.conf` is as the following:

```
HOME    $HOME/$USER.inst/     user
```

On the root mount namespace I'll have something like this:

```
# find /proc/1/root/home/
/proc/1/root/home/
/proc/1/root/home/user
/proc/1/root/home/user/.bash_profile
/proc/1/root/home/user/.cache
/proc/1/root/home/user/.cache/vim
/proc/1/root/home/user/user.inst
/proc/1/root/home/user/user.inst/user
/proc/1/root/home/user/user.inst/user/in_ns
/proc/1/root/home/user/user.inst/user/.bash_profile
/proc/1/root/home/user/user.inst/user/.cache
/proc/1/root/home/user/user.inst/user/.cache/vim
/proc/1/root/home/user/user.inst/user/.ssh
/proc/1/root/home/user/user.inst/user/.ssh/config
/proc/1/root/home/user/user.inst/user/.bash_history
/proc/1/root/home/user/user.inst/user/.bash_logout
/proc/1/root/home/user/user.inst/user/.lesshst
/proc/1/root/home/user/user.inst/user/.bashrc
/proc/1/root/home/user/.bash_history
/proc/1/root/home/user/.bash_logout
/proc/1/root/home/user/not_in_ns
/proc/1/root/home/user/.bashrc
```

If I'm looking what are the mntns setup if got two different (4026531840) for `systemd --user` and (4026532360) for the shell I
ran:

```
$ ps -u "$(id -u)" -o pid,user,mntns,command --sort mntns
PID USER          MNTNS COMMAND
442 user     4026531840 /usr/lib/systemd/systemd --user
480 user     4026532360 -bash
532 user     4026532360 ps -u 1000 -o pid,user,mntns,command --sort mntns
```

4026531840 seems to be the initial mnt namespace:

```
# ls -l /proc/1/ns/mnt
lrwxrwxrwx 1 root root 0 Sep 13 16:23 /proc/1/ns/mnt -> 'mnt:[4026531840]'
```

Thus, if I'm starting a user service it is executed within the initial mount namespace:

  - The service cannot use the data that the user see easily
  - The user cannot see the data generated by the service
  - The data generated by the service are not protected by the namespace

**Describe the solution you'd like**

I will imagine a way (if possible) to execute user service within the polyinstantiated namespace instead of the initial namespace. That way it will be able to use and generate data usable for the sandboxed user.

I'm not sure if its something that can be done or if I just miss something in this particular setup.

**Describe alternatives you've considered**

I've considered adding something like `session required pam_namespace.so` into `/etc/pam.d/systemd-user` which seems used by `user@.service` but I'm not sure I'm not mess up doing so.

**Comment by poettering** [comment]
This sounds like a limitation of pam_namespace.so, unrelated to systemd.

I.e. both user@.service and the regular login sessions go through PAM. If pam_namespace cannot reuse mount namespaces for all of them, that's something to fix there. 

systemd doesn't do anything special here, we go through PAM for all sessions and for user@.service. If pam_namespace would know how to reuse mount namespaces between all concurrent PAM sessions you'd get what you ask for but if it does not support that there's nothing we can do, sorry.

Please file a RFE bug against https://github.com/linux-pam/linux-pam/issues — maybe they'll add that for you, but from systemd's side there's nothing we can do about that othewise.

Hope this makes sense. Closing.

**Comment by bobsaintcool** [comment]
Thanks for the clarification!

**Comment by keszybz** [comment]
I'm looking into this because of downstream bug in RHEL.

> I.e. both [user@.service](mailto:user@.service) and the regular login sessions go through PAM. If pam_namespace cannot reuse mount namespaces for all of them, that's something to fix there.

Yes.

> I've considered adding something like `session required pam_namespace.so` into `/etc/pam.d/systemd-user` which seems used by `user@.service`

Yes, we should do this, because it is required to get pam_namespace to work correctly with `user@.service`. We have a line like this downstream in Fedora. I'll submit a patch to move it upstream.

**Comment by bobsaintcool** [comment]
This is cool, thanks having double look at it.

At the time I've followed suggestion and created an issue on linux-pam (and also lost a bit track of it :(). The answer I got seems to match mostly what your commit is about. 
You can see it there https://github.com/linux-pam/linux-pam/issues/268
