### ISSUE TITLE
systemctl mask should create dirs

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1706]
`mask` fails if the unit directory (e.g. `~/.config/systemd/user`) is missing. It should create the directory, like `enable` does.

**Comment by poettering** [comment]
Ah, interesting. In my working copy of #1515 I actually made pretty much the same change. Since that rework is mostly done now but a massive refactoring, I'd rather merge that instead of dealing with the rebase afterwards... I hope that's OK?

**Comment by heftig** [comment]
Sure; do what you think is best.

**Comment by poettering** [comment]
I posted my rework now as force push on #1515. it includes a change similar to what you wanted to make. Hence closing this one. Thanks!
