### ISSUE TITLE
User units not activated on login with encrypted home directory

### ISSUE THREAD

**Issue by OJFord** [systemd/systemd#17089]
**systemd version the issue has been seen with**
> systemd 246 (246.4-1-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > `loaded` & `active` in `systemctl --user status <unit>`
 > user units listed `systemctl --user status` cgroup tree 
 > manual `systemctl --user start <unit>` unnecessary

**Unexpected behaviour you saw**
 > `loaded` & `inactive (dead)` in `systemctl --user status <unit>`
 > only units listed in `systemctl --user status` from outside home directory (`init.scope`, `at-spi-dbus-bus.service`, and `dbus.service`)
 > manual `systemctl --user start <unit>` necessary, and does work. Units automatically triggered later (`pulseaudio.*`) also work.

```
$ systemctl --user status default.target
● default.target - Main User Target
     Loaded: loaded (/usr/lib/systemd/user/default.target; static)
     Active: active since Thu 2020-09-17 09:14:46 BST; 1h 14min ago
       Docs: man:systemd.special(7)

Sep 17 09:14:46 desk systemd[455]: Reached target Main User Target.
```

**Steps to reproduce the problem**

Initially I used `pam_mount.so` _last_ in `auth` & `session` sections of `/etc/pam.d/system-login`, [as recommended by the wiki of my encrypted filesystem, gocryptfs](https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount).

I was suspicious that this position after `-session pam_systemd.so` was the issue, and noticed that it differed from the [advice in Arch wiki](https://wiki.archlinux.org/index.php/Pam_mount), so I switched to that, but it had no effect (on systemd user unit startup).

Units that are `WantedBy=default.target` are then created inside the home directory (that will only exist after pam_mount runs on login), such as this one provided by `clipmenu` (which I've linked to from my `XDG_CONFIG_HOME` for convenience, but among similar ones I've written there and couldn't so reasonably leave outside my home directory):
```ini
[Unit]
Description=Clipmenu daemon

[Service]
ExecStart=/usr/bin/clipmenud
Restart=always
RestartSec=500ms
Environment=DISPLAY=:0

MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=
RestrictRealtime=yes

[Install]
WantedBy=default.target
```

`systemctl --user enable <unit>` to create symlink in `$HOME/.config/systemd/user/default.target.wants/<unit>`, where `$HOME` is the decrypted-on-login directory, and `$HOME/.config` is `$XDG_CONFIG_HOME`.

**Comment by poettering** [comment]
This really doesn't look like a systemd issue. We don#t do anything special regarding encrypted file systems. If this doesn't work for you, please talk to your distro or the maintainers of the package that does the encrypted fs stuff. Most likely the module is just missing from the "systemd-user" PAM stack or so.
