### ISSUE TITLE
Lost Before=local-fs.target on crypttab mounts after upgrading from v245 to v246

### ISSUE THREAD

**Issue by egtvedt** [systemd/systemd#17095]
**systemd version the issue has been seen with**
> v246

**Used distribution**
 > Embedded Linux

**Expected behaviour you didn't see**
 > Still have Before=local-fs.target in our crypttab .mount unit file.

**Unexpected behaviour you saw**
 > Before=local-fs.target is now gone.

**Steps to reproduce the problem**
I suspect this is related to some of these commits:
https://github.com/systemd/systemd/commit/83cdc870949823b5b9fa04dd76e952d42faab0b1
https://github.com/systemd/systemd/commit/b3d7aef525dc1620a7948ffdbf3f36bfa3d5b5e8
https://github.com/systemd/systemd/commit/045c5faf5a3ef51cd39f738694e06c11a73f54b7

Is the change intentional? This causes issues since our crypttab mounts might be unmounted very early during shutdown.

What is the suggested work flow now?

**Comment by egtvedt** [comment]
Is the recommended practice now to add `x-systemd.before=local-fs.target` in fstab?

**Comment by poettering** [comment]
"crypttab .mount file"? What do you mean by that? systemd-cryptsetup-generator does no generate .mount unit files from /etc/crypttab. I am puzzled?

**Comment by egtvedt** [comment]
I agree, my original post is very confusing. I have only myself to blame. The /etc/crypttab works as expected, the device mappers are setup as expected.

However, I noticed that the mount points defined in /etc/fstab no longer had Before=local-fs.target, but I suspect that is also a fault on my side. The mount point I originally referred to had option nofail, and I discovered that we in the past had patched src/fstab-generator/fstab-generator.c to always add Before=, even if nofail option was set.

However, the src/fstab-generator/fstab-generator.c code has changed significant between v245 and v246, causing our local patch to no longer apply, causing this issue to pop up on our end.

AFAIK the preferred solution for nofail mount points is to add the `x-systemd.before=local-fs.target` option?

Sorry for causing noise.

**Comment by poettering** [comment]
Yes, x-systemd.before= certainly works.

Let's close this then.

**Comment by jarda-wien** [comment]
I was just hunting why we don't get the Before=local-fs.target on our system and stumbled upon this. While I am ok with the resolution, I really think that the [relevant manpage](https://github.com/systemd/systemd/blob/master/man/systemd.special.xml#L424) should be more specific about this.
Happy to create a PR, but I am not sure if `nofail` is the only flag which will disable the automatic Before=local-fs.target relation.
