### ISSUE TITLE
Systemd timeout when cups-browsed.service is stopping

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#17105]
**systemd version the issue has been seen with**
> 246.4-1

**Used distribution**
> Manjaro Linux

**Expected behaviour you didn't see**
 > no error timeout before systemd[1]: Stopped Make remote CUPS printers available locally

**Unexpected behaviour you saw**
 > systemd[1]: cups-browsed.service: Failed with result 'timeout'.

**Steps to reproduce the problem**
> systemctl stop cups-browsed

**Comment by poettering** [comment]
Please contact the maintainers of said service `cups-browsed`, systemd is just the messenger that that service failed to shut down in time.
