### ISSUE TITLE
Top-level drop-in is ignored if a unit-specific drop-in is found

### ISSUE THREAD

**Issue by amo13** [systemd/systemd#17107]
**systemd version the issue has been seen with**
> 246.5-1

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > `systemctl cat myunit` shows the directives of the unit file itself and the directives in `myunit.service.d/override.conf`, but not the directives in `service.d/override.conf`, even if the directive in `service.d/override.conf` is not mentioned in the first two files. I expected to see `OnFailure=failure-notification@%n` from the top-level drop-in when calling `systemctl cat myunit` but I don't.

> The mention of top-level drop-ins in the systemd manual states, to my understanding, that the service file itself, its drop-in and the top-level drop-in should all be merged by systemd to a unit config with respect to the defined precedence:

>        Units also support a top-level drop-in with type.d/, where type may
>        be e.g.  "service" or "socket", that allows altering or adding to the
>        settings of all corresponding unit files on the system. The
>        formatting and precedence of applying drop-in configurations follow
>        what is defined above. Configurations in type.d/ have the lowest
>        precedence compared to settings in the name specific override
>        directories. So the contents of foo-.service.d/10-override.conf would
>        override service.d/10-override.conf.

**Unexpected behaviour you saw**
 > My journal during boot time is full of statements like these ones:
 > `systemd[1]: /etc/systemd/system/service.d/override.conf:2: Failed to add dependency on failure-notification@failure-notification@failure-notification@failure-notification@failure-notification@systemd-remount-fs.service, ignoring: Invalid argument`

**Steps to reproduce the problem**
 > Add a top-level drop-in `/etc/systemd/system/service.d/override.conf`a
 > ```
 > [Unit]
 > OnFailure=failure-notification@%n
 > ```
 > Do a `systemctl daemon-reload` (or reboot) and check out `systemctl cat myunit` for a service unit with an existing drop-in `myunit.service.d/override.conf`.

**Comment by poettering** [comment]
All the files in the drop-in dirs are merged, as per docs. Files of the same name override each other, so that the "most specific" drop-in wins. But it's the whole files that override each other. If you don't want that use files of different names in drop-in dirs. 

I guess we could reword this in the docs to make this even clearer.

**Comment by amo13** [comment]
Awesome, thanks for making this clear!
Now, I actually understand why the example top-level override file is called `10-override.conf` in the docs...

**Comment by amo13** [comment]
Any idea why I could be getting this weird flood of systemd messages about my top-level override file?

`systemd[1]: /etc/systemd/system/service.d/override.conf:2: Failed to add dependency on failure-notification@failure-notification@failure-notification@failure-notification@failure-notification@systemd-remount-fs.service, ignoring: Invalid argument`

They did not vanish from renaming `override.conf` to `toplevel-override.conf`.

**Comment by ckotte** [comment]
@amo13 Could you get rid of those errors? There are thousands of services created because of the template unit file in ```OnFailure``` in the top-level override.

Looks like you have the same issue.. This is an example on my system:

```
systemctl show systemd-notify@
zsh: do you wish to see all 1200 possibilities (1550 lines)? 
```
```
...
systemd-notify@systemd-notify@systemd-notify@systemd-journal-flush.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-logind.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machined.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machine-id-commit.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-modules-load.service.service.service.service
...
```

**Comment by amo13** [comment]
I think I got rid of it by removing the Before= and After= statements in some of my units. I originally wanted to have my gotify server (responsible for delivering messages about failed units) start before most of the other units (nginx, mariadb, redis, ...), but it would not work. Removing the After= and Before= statements also made these weird messages go away.
I don't remember if I actually had hundreds of units created (did not check or look for them), but I always had lots of messages like in my last post in my journal.
