### ISSUE TITLE
Strange failures of oneshot/remainafterexit=true

### ISSUE THREAD

**Issue by alexyuriev** [systemd/systemd#17104]
I have a question about an odd behavior of systemd version 241 from debain 10.

This is a unit file. 

```
[Unit]
Description=Loads saved iptables configuration on boot
Before=network.target

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/usr/sbin/zcm-load-iptables

[Install]
WantedBy=multi-user.target
```

Under certain circumstances the unit is showing as inactive/dead.

```root@sentinel-1:/etc/systemd/system# systemctl status iptables_on_boot.service
● iptables_on_boot.service - Loads saved iptables configuration on boot
   Loaded: loaded (/etc/systemd/system/iptables_on_boot.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sat 2020-09-19 02:59:00 UTC; 3min 52s ago
 Main PID: 284 (code=exited, status=0/SUCCESS)

Sep 19 02:59:00 sentinel-1 systemd[1]: Starting Loads saved iptables configuration on boot...
Sep 19 02:59:00 sentinel-1 iptables[289]: File /etc/iptables.rules does not exit. Not activating
Sep 19 02:59:00 sentinel-1 zcm-load-iptables[284]: <13>Sep 19 02:59:00 iptables: File /etc/
Sep 19 02:59:00 sentinel-1 systemd[1]: iptables_on_boot.service: Succeeded.
Sep 19 02:59:00 sentinel-1 systemd[1]: Started Loads saved iptables configuration on boot.
```

During those times the ExecStart line from show iptables_on_boot.service looks like this:

```
ExecStart={ path=/usr/sbin/zcm-load-iptables ; argv[]=/usr/sbin/zcm-load-iptables ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
```

which is clearly an indicator of a problem as when it works correctly this is how it looks like:

```
ExecStart={ path=/usr/sbin/zcm-load-iptables ; argv[]=/usr/sbin/zcm-load-iptables ; ignore_errors=no ; start_time=[Sat 2020-09-19 03:26:26 UTC] ; stop_time=[Sat 2020-09-19 03:26:26 UTC] ; pid=305 ; code=exited ; status=0 }
```

Any thoughts?

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by alexyuriev** [comment]
@poettering How on earth the same unit behaving differently *sometimes* on the same system is not a potential bug?!

**Comment by poettering** [comment]
most likely something stopped the service. figuring that out is a support job really, not a bug. it might be escalated eventually to a bug, but from all i am seeing it's quite a stretch to assume a bug here... i.e. contact a support forum first, and post as bug only if it's sufficiently clear it's not operating correctly, i.e. it stopped things without request or reason.

btw, as the 241 is waaay too old to be tracked here too, the submission form should have made that very clear. So even if it actually was somewaht clear thtat this is a bug it still would not be the right place to post unless verified it happens on the current upstream verisions. For stuff older than that your downstream distro will take your request. 

But again, this smells like some mistake in use, not a bug in systemd proper, hence contact a support forum first.
