### ISSUE TITLE
systemd-coredump Failed to get COMM: No such process

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#17119]
systemd version the issue has been seen with
246

Recently i encountered a problem. I wrote a simple program, the content is listed as below which would coredump.

#include<stdio.h>
int main()
{
        int *ptr = NULL;
        *ptr = 0;
        return 0;
}

When i execute this program on x86, a coredump file was generated under /var/lib/systemd/coredump/.
But when i execute this program on arm, I got the error of 
"systemd-coredump[5548]: Failed to get COMM: No such process"
I add some log info to judge the reason.

Sep 22 17:13:43 testname audit[5547]: ANOM_ABEND auid=0 uid=0 gid=0 ses=9 pid=5547 comm="test" exe="/opt/test" sig=11 res=1
Sep 22 17:13:43 testname systemd-coredump[5548]: 11111111111into process_kernel
Sep 22 17:13:43 testname systemd-coredump[5548]: 2222222222222PID to pass 5547.
Sep 22 17:13:43 testname systemd-coredump[5548]: 4444444444 print p /proc/5547/comm.
Sep 22 17:13:43 testname systemd-coredump[5548]: Failed to get COMM: No such process

And when i used gdb to execute the program step by step, problem was no longer exist, everything was ok, there was coredump file under /var/lib/systemd/coredump/.

I think the problem may be cause the process of the program above is exist too fast for systemd to get the command info throgh function get_process_comm, so i got the failure of  "Failed to get COMM: No such process". Maybe systemd-coredump should let the program not exit from very beginning?

It seems we got the metadata get from argv[], but when we try to retrieve the rest metadata from runtime,  r = gather_pid_metadata(iovw, &context) get the result of -3, it means that the core dump process has already exit.
        /* Collect all process metadata from argv[] by making sure to skip the
         * '--backtrace' option */
        r = gather_pid_metadata_from_argv(iovw, &context, argc - 2, argv + 2);
        if (r < 0)
                goto finish;

        /* Collect the rest of the process metadata retrieved from the runtime */
        r = gather_pid_metadata(iovw, &context);
        if (r < 0)
                goto finish;

**Comment by syyhao1994** [comment]
![image](https://user-images.githubusercontent.com/38710185/93982135-71e49300-fdb3-11ea-879b-905b0d9d8c1d.png)
I add a sleep in systemd-coredump.
When i executed core dump program on x86, the program will not exit util the core dump file generated.
But on aarch64 the program exit directly without waiting for systemd-coredump.

**Comment by syyhao1994** [comment]
It seems to be influeced by the configuration of kernel. The page size on aarch64 is 64K, but it is 4K on x86.

**Comment by poettering** [comment]
This looks like a kernel bug. Processes being dumped are expected to stay around in /proc until they are processed (i.e. userspace closes the pipe it receives the coredump on). If this is different on arm then this is really a kernel compat break on that. Can you report this to the arm kernel maintainers?

This is even documented:

https://man7.org/linux/man-pages/man5/core.5.html

See the part about core_pipe_limit.

We need the process to stick around so that we can collect all kind of metadata really.

I don't think this is something to fix for us. It's really wrong behaviour of the kernel on that arch, contradicting docs and I am pretty sure that should be corrected to behave like on x86

let's close this here, as this doesn't look like anything to change in systemd. Even if we wanted to i doubt we could fix anything here: collecting metadata after the process is already entirely dead is not possible.

hope this makes sense.

**Comment by syyhao1994** [comment]
> This looks like a kernel bug. Processes being dumped are expected to stay around in /proc until they are processed (i.e. userspace closes the pipe it receives the coredump on). If this is different on arm then this is really a kernel compat break on that. Can you report this to the arm kernel maintainers?
> 
> This is even documented:
> 
> https://man7.org/linux/man-pages/man5/core.5.html
> 
> See the part about core_pipe_limit.
> 
> We need the process to stick around so that we can collect all kind of metadata really.
> 
> I don't think this is something to fix for us. It's really wrong behaviour of the kernel on that arch, contradicting docs and I am pretty sure that should be corrected to behave like on x86
> 
> let's close this here, as this doesn't look like anything to change in systemd. Even if we wanted to i doubt we could fix anything here: collecting metadata after the process is already entirely dead is not possible.
> 
> hope this makes sense.

I figured out the reason why there are no coredump files on machines of 64K pagesize through systemd-coredump eventually. Actually there is no difference on X86 or arm. It is because that the pipe size is not the same on different pagesize(the pipe size of 4K is 65536 bytes and the size of 64K is 1048576K, you can got this from the /proc/sys/fs/pipe-max-size) . The coredump file generated through the program i mentioned before is only 970k dumped by kernel. The pipe size of 4K page size is smaller than 970k, so the kernel could wait systemd-coredump for reading full data from pipe. But 970k is less than the pipe size of 64K page size machine, so the kernel write the dumped data into pipe one time and kill the coredump process without waiting for systemd-coredump. So this problem is no longer exist when the dumped file is larger than 1M. The dumped file of the  program i listed below is 1.2M, the problem is no longer exist.
#include<stdio.h>
#include<unistd.h>
#include<fcntl.h>
#include<stdlib.h>
#include<errno.h>
#include<signal.h>
#include<string.h>
int main()
{
  char *ptr = (char *)malloc(64 * 512);
  memset(ptr, 0, 64 * 512);
  char *ptr1 = NULL;
  *ptr1 = 1;
  return 0;
}

I have also tried the earlier systemd version such as systemd v239 on 64k pagesize machine. This problem seems don't exist. The kernel didn't wait for systemd-coredump.As the result systemd-coredumped could not get the COMM as well ,but the coredump file could generated as normal. 
The commits listed as below make the difference, i think maybe there is a way to solve this problem in systemd?
https://github.com/systemd/systemd/commit/47cf786c0a13fccd777c334bed4b1e7b02f18d42#diff-50317a194e91003ebac9d57280bceec6
https://github.com/systemd/systemd/commit/f46c706bdd4316ae8ed6baf7a8c382b90b84f648#diff-50317a194e91003ebac9d57280bceec6
Oct 10 11:15:53 localhost.localdomain [19007]: [ls /var/lib/systemd/coredump/] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:20 localhost.localdomain [19187]: [rm -rf /var/lib/systemd/coredump/*] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:21 localhost.localdomain [19227]: [ls] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:25 localhost.localdomain [19261]: [ls /var/lib/systemd/coredump/] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:31 localhost.localdomain [19310]: [rpm -qa systemd] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:43 localhost.localdomain [19409]: [cat /proc/sys/kernel/core_pattern] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:16:57 localhost.localdomain [19512]: [./test] return code=[139], execute failed by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:17:07 localhost.localdomain systemd-coredump[19498]: **Failed to get COMM, falling back to the command line: No such process**
Oct 10 11:17:07 localhost.localdomain systemd-coredump[19498]: **Failed to get EXE, ignoring: No such process**
Oct 10 11:17:07 localhost.localdomain systemd[1]: **Started Process Core Dump (PID 19498/UID 0).**
Oct 10 11:17:08 localhost.localdomain systemd-coredump[19566]: Process 19497 (test) of user 0 dumped core.

                                                               Stack trace of thread 19497:
                                                               #0  0x00000000004005e4 n/a (/home/test)
                                                               #1  0x0000fffd04370be0 __libc_start_main (libc.so.6)
                                                               #2  0x0000000000400514 n/a (/home/test)
                                                               #3  0x0000000000400514 n/a (/home/test)
Oct 10 11:18:10 localhost.localdomain [19963]: [ls /var/lib/systemd/coredump/] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:19:11 localhost.localdomain [20338]: [getconf PAGESIZE] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:19:17 localhost.localdomain [20389]: [./test1] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
Oct 10 11:19:42 localhost.localdomain [20597]: [cat /proc/sys/fs/pipe-max-size] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.90.94)]
