### ISSUE TITLE
Provide a way to block use of RDRAND

### ISSUE THREAD

**Issue by khuey** [systemd/systemd#17112]
This originated in mozilla/rr#2694.

_rr_ is a userspace record-and-replay debugger that does not (and can not, for obvious reasons) support replaying the results of an RDRAND instruction. _rr_ uses Linux kernel and hardware support to trap and emulate CPUID instructions where possible, but this support is not available on older kernels, non-Intel hardware, or in certain virtualized environments. When we cannot trap CPUID and lie about the presence of RDRAND, we use software configuration where available, such as for OpenSSL and Qt[0].

In the original issue, a program from our test suite makes a libc call that ultimately hits libnss_systemd and the RDRAND-using code. _rr_ is unable to trap CPUID on that system (because it has an AMD processor and that isn't supported there) so systemd uses the available hardware support and generates a random value, which _rr_ will never be able to successfully replay. If systemd had an environment variable that could disable RDRAND like OpenSSL and Qt do, we could set that in the environment and tell libnss_systemd not to use RDRAND when running under rr.

`git annotate` leads me to believe that CCing @poettering would be a good idea.

[0] https://github.com/mozilla/rr/blob/a4f96c01be873c804eeef8acc0bb7ec2eee3b7a2/src/RecordSession.cc#L2204

**Comment by poettering** [comment]
what are the env vars named qt/openssl use? generically? if so we can just reuse them.

anyway, makes sense, PR would be very welcome

**Comment by poettering** [comment]
hmm, looking at the link you provided the env vars are not generically named. hence maybe add this as SYSTEMD_RDRAND=0|1

**Comment by khuey** [comment]
Yes unfortunately nobody agreed on something generic to call it. How about `SYSTEMD_DISABLE_RDRAND` (then a simple `getenv_bool(..) > 0` will be enough to tell us to skip rdrand)? If that sounds good to you I'll send a PR.

**Comment by keszybz** [comment]
`SYSTEMD_RDRAND=0|1` is better. `SYSTEMD_DISABLE_RDRAND` assumes that we'll only ever want to disable rdrand, which is true now, but might not be true in the future. And "negative" options are generally inferior. It's also longer.
