### ISSUE TITLE
[Documentation] To add the info about first-seen release version in directives description

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#1712]
Subj.

E.g.:

```
Name
bla-bla-bla

Synopsis

bla-bla-bla.service
bla-bla-bla.socket

Released in: systemd XXX

Description
...
```

or, if directive/tool was deleted:

```
Name
bla-bla-bla

Synopsis

bla-bla-bla.service
bla-bla-bla.socket

Released in: systemd XXX
Deleted in: systemd YYY

Description
...
```

or, if directive/tool was replaced by another directive/tool:

```
Name
bla-bla-bla

Synopsis

bla-bla-bla.service
bla-bla-bla.socket

Released in: systemd XXX
Replaced by: new-pretty-good directive/tool in systemd release: YYY

Description
...
```

or, if directive/tool was modified\upgraded:

```
Name
bla-bla-bla

Synopsis

bla-bla-bla.service
bla-bla-bla.socket

Released in: systemd XXX
Modified/Upgraded in: systemd YYY

Description
...
```

I suppose it will make searching much more easy in way of "Does my systemd version have directive/tool A/B/C/.../Z?" without re-reading all systemd release-notes.

**Comment by poettering** [comment]
This has been requested before, but we always said no to this so far. I can see why this could be useful, but in general this is a lot of work to get done, and also adds a lot of noise to the man pages, in particular as the effect of setting changes or is extended over time.

Instead we usually recommend that people simply use the man pages of the version they care about.

Sorry, but I don't see a nice way how to integrate this information without keeping the man pages minimal and noise-free. Also we don't really have the manpower to track this information down now. Sorry.

**Comment by MikhailKasimov** [comment]
Ok. :(

**Comment by keszybz** [comment]
We already have some of this kind of information for the C API. But I think we could add it also for configuration directives without too much noise. For me, Python docs are the gold standard of how to do this; see e.g. https://docs.python.org/dev/library/tempfile.html:

```
        New in version 3.2
```

This doesn't introduce too much noise, but would helps a lot when trying to write units which will work for more than the latest version of systemd. One recent example: I replaced OnFailure=reboot.target with FailureAction=reboot in dnf-plugin-system-upgrade, without realizing that F21 does not have FailureAction=. It is possible to extract this information from NEWS, but it requires much more dedication. Having it prominently displayed would reduce errors like that.

To implement this, we could simply require new additions to man pages to have an extra <para>Added in version ...</para>.

**Comment by poettering** [comment]
I am still not convinced that carrying this in the man page is the right thing to do. Sorry.
