### ISSUE TITLE
logind's `BootLoaderEntries` property cannot be retrieved

### ISSUE THREAD

**Issue by aburch** [systemd/systemd#17122]
**systemd version the issue has been seen with**
246.6-1 (Debian)

**Used distribution**
Debian testing/unstable

**Expected behaviour you didn't see**
The `BootLoaderEntries` property should be retrievable.

**Unexpected behaviour you saw**
```
$ busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager BootLoaderEntries
Failed to get property BootLoaderEntries on interface org.freedesktop.login1.Manager: Input/output error
```

The journal contains the following error message from logind:
```
Failed to probe partition scheme of "/dev/block/9:0": Input/output error
```
where `/dev/block/9:0` is `md0` which is a raid1 containing the `/boot` filesystem directly (no partition table).
`lsblk` shows:
```
├─sda2             8:2    0   244M  0 part  
│ └─md0            9:0    0 243.8M  0 raid1 /boot
[...]
├─sdb2             8:18   0   244M  0 part  
│ └─md0            9:0    0 243.8M  0 raid1 /boot
```

I found this when investigating why I encountered #17121.

**Comment by chpio** [comment]
@aburch have you got updates working with your setup? Im getting the same error with `bootctl --path=/boot update`. `--graceful` ("Don't fail when the ESP cannot be found or EFI variables cannot be written") doesn't change a thing.

I installed it "normally" then added the md raid1.

```
NAME        MAJ:MIN RM    SIZE RO TYPE  MOUNTPOINT
nvme1n1     259:0    0  931,5G  0 disk  
├─nvme1n1p1 259:5    0      1G  0 part  
│ └─md127     9:127  0 1023,9M  0 raid1 /boot
[...]
nvme0n1     259:1    0  931,5G  0 disk  
├─nvme0n1p1 259:2    0      1G  0 part  
│ └─md127     9:127  0 1023,9M  0 raid1 /boot
[...]
```

https://lists.freedesktop.org/archives/systemd-devel/2017-December/039962.html
