### ISSUE TITLE
udev: /sys/class/net/<ib>/mode expects newline

### ISSUE THREAD

**Issue by afq984** [systemd/systemd#17131]
**systemd version the issue has been seen with**

<details><summary>systemd 246 (246.2-1-arch)</summary>
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
</details>

**Used distribution**
Arch Linux

**Steps to reproduce the problem**
```
$ cat /etc/udev/rules.d/2-ipoib.rules
ACTION=="add", KERNEL=="ib*", SUBSYSTEM=="net", ATTR{mode}="connected"
$ udevadm test /sys/class/net/ibp3s0/
...
ibp3s0: /etc/udev/rules.d/2-ipoib.rules:1 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/net/ibp3s0/mode}, ignoring: Invalid argument
...
```

**Notes**

```
# echo connected > /sys/class/net/ibp3s0/mode
# echo -n connected > /sys/class/net/ibp3s0/mode
bash: echo: write error: Invalid argument
```

* https://github.com/systemd/systemd/pull/13987
* https://github.com/systemd/systemd/issues/13985
* https://github.com/torvalds/linux/blob/v5.8/drivers/infiniband/ulp/ipoib/ipoib_main.c#L511

**Comment by yuwata** [comment]
How about to use `ATTR{mode}="connected\n"`?

**Comment by afq984** [comment]
I'd be happy with that.
But if someone uses `"\n"` to express "backslash n" their configuration would need to change.
I thought of `$byte{10}` `%b{10}` to reuse existing escape characters, though, it looks kind of scary...

**Comment by yuwata** [comment]
I guess the current udevd code already supports to put a line break with `\n`. Also, putting with a backslash and 'n' is also supported by `\\n`. Though, I have not test it. I think it is not necessary to change udevd code to 'fix' this issue.

**Comment by afq984** [comment]
I haven't look into the code, but strace says it writes a backslash now
```
# strace udevadm test /sys/class/net/ibp3s0/
...
openat(AT_FDCWD, "/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/net/ibp3s0/mode", O_WRONLY|O_NOC
TTY|O_CLOEXEC) = 4
fcntl(4, F_GETFL)                       = 0x8001 (flags O_WRONLY|O_LARGEFILE)
write(4, "connected\\n", 11)            = -1 EINVAL (Invalid argument)
...
```

**Comment by yuwata** [comment]
With `\n`?

**Comment by afq984** [comment]
Yeah, 
```
# cat /etc/udev/rules.d/2-ipoib.rules
ACTION=="add", KERNEL=="ib*", SUBSYSTEM=="net", ATTR{mode}="connected\n"
```

**Comment by yuwata** [comment]
Ugh, yeah, my previous comment is completely wrong....

So, currently, we have no way to include a line break in a value. Maybe, we need to introduce a way to support escaped characters, e.g., `ATTR{mode}=e"connected\n"`

**Comment by afq984** [comment]
I'll send a PR for this soon

**Comment by poettering** [comment]
Hmm,  @yuwata i wonder if maybe this is a regression... i.e. i wonder if we used to implicitly append the \n back in the days, but we accidentally changed that?

**Comment by afq984** [comment]
@poettering I've tested selected versions of systemd from v187 to v246, and it seems that only v243 append the `\n` (fixed by #13987). v187 is from 2012 so I think it's safe to say udev doesn't append `\n` for a long time.

<details><summary>Test details</summary>

udev in qemu running historic Arch Linux ISO releases

Test line: `ACTION=="add", KERNEL=="lo", SUBSYSTEM=="net", ATTR{mtu}="65537"`
Results:

| archiso version | systemd version | strace output |
| -- | -- | -- |
 | ARCH_201208 | systemd 187 | `write(4, "65537", 5)` | 
 | ARCH_201209 | systemd 189 | `write(4, "65537", 5)` | 
 | ARCH_201210 | systemd 194 | `write(4, "65537", 5)` | 
 | ARCH_201211 | systemd 195 | `write(4, "65537", 5)` | 
 | ARCH_201212 | systemd 196 | `write(5, "65537", 5)` | 
 | ARCH_201301 | systemd 196 | `write(5, "65537", 5)` | 
 | ARCH_201302 | systemd 197 | `write(5, "65537", 5)` | 
 | ARCH_201303 | systemd 197 | `write(5, "65537", 5)` | 
 | ARCH_201310 | systemd 207 | `write(5, "65537", 5)` | 
 | ARCH_201311 | systemd 208 | `write(5, "65537", 5)` | 
 | ARCH_201312 | systemd 208 | `write(5, "65537", 5)` | 
 | ARCH_201401 | systemd 208 | `write(5, "65537", 5)` | 
 | ARCH_201402 | systemd 208 | `write(5, "65537", 5)` | 
 | ARCH_201403 | systemd 208 | `write(5, "65537", 5)` | 
 | ARCH_201404 | systemd 212 | `write(5, "65537", 5)` | 
 | ARCH_201405 | systemd 212 | `write(5, "65537", 5)` | 
 | ARCH_201406 | systemd 212 | `write(5, "65537", 5)` | 
 | ARCH_201407 | systemd 214 | `write(5, "65537", 5)` | 
 | ARCH_201408 | systemd 215 | `write(5, "65537", 5)` | 
 | ARCH_201409 | systemd 216 | `write(5, "65537", 5)` | 
 | ARCH_201410 | systemd 216 | `write(5, "65537", 5)` | 
 | ARCH_201411 | systemd 216 | `write(5, "65537", 5)` | 
 | ARCH_201412 | systemd 217 | `write(5, "65537", 5)` | 
 | ARCH_201501 | systemd 218 | `write(5, "65537", 5)` | 
 | ARCH_201502 | systemd 218 | `write(5, "65537", 5)` | 
 | ARCH_201503 | systemd 218 | `write(5, "65537", 5)` | 
 | ARCH_201504 | systemd 218 | `write(5, "65537", 5)` | 
 | ARCH_201505 | systemd 219 | `write(5, "65537", 5)` | 
 | ARCH_201506 | systemd 219 | `write(5, "65537", 5)` | 
 | ARCH_201507 | systemd 221 | `write(4, "65537", 5)` | 
 | ARCH_201508 | systemd 223 | `write(4, "65537", 5)` | 
 | ARCH_201509 | systemd 224 | `write(4, "65537", 5)` | 
 | ARCH_201510 | systemd 226 | `write(4, "65537", 5)` | 
 | ARCH_201511 | systemd 227 | `write(4, "65537", 5)` | 
 | ARCH_201512 | systemd 228 | `write(4, "65537", 5)` | 
 | ARCH_201601 | systemd 228 | `write(4, "65537", 5)` | 
 | ARCH_201602 | systemd 228 | `write(4, "65537", 5)` | 
 | ARCH_201603 | systemd 229 | `write(4, "65537", 5)` | 
 | ARCH_201604 | systemd 229 | `write(4, "65537", 5)` | 
 | ARCH_201605 | systemd 229 | `write(4, "65537", 5)` | 
 | ARCH_201606 | systemd 229 | `write(4, "65537", 5)` | 
 | ARCH_201607 | systemd 230 | `write(4, "65537", 5)` | 
 | ARCH_201608 | systemd 231 | `write(4, "65537", 5)` | 
 | ARCH_201609 | systemd 231 | `write(4, "65537", 5)` | 
 | ARCH_201610 | systemd 231 | `write(4, "65537", 5)` | 
 | ARCH_201611 | systemd 231 | `write(4, "65537", 5)` | 
 | ARCH_201612 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201701 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201702 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201703 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201704 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201705 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201706 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201707 | systemd 232 | `write(4, "65537", 5)` | 
 | ARCH_201708 | systemd 234 | `write(4, "65537", 5)` | 
 | ARCH_201709 | systemd 234 | `write(4, "65537", 5)` | 
 | ARCH_201710 | systemd 234 | `write(4, "65537", 5)` | 
 | ARCH_201711 | systemd 235 | `write(4, "65537", 5)` | 
 | ARCH_201712 | systemd 235 | `write(4, "65537", 5)` | 
 | ARCH_201801 | systemd 236 | `write(4, "65537", 5)` | 
 | ARCH_201802 | systemd 236 | `write(4, "65537", 5)` | 
 | ARCH_201803 | systemd 237 | `write(4, "65537", 5)` | 
 | ARCH_201804 | systemd 238 | `write(4, "65537", 5)` | 
 | ARCH_201805 | systemd 238 | `write(4, "65537", 5)` | 
 | ARCH_201806 | systemd 238 | `write(4, "65537", 5)` | 
 | ARCH_201807 | systemd 238 | `write(4, "65537", 5)` | 
 | ARCH_201808 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201809 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201810 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201811 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201812 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201901 | systemd 239 | `write(4, "65537", 5)` | 
 | ARCH_201902 | systemd 240 | `write(4, "65537", 5)` | 
 | ARCH_201903 | systemd 241 (241.7-2-arch) | `write(4, "65537", 5)` | 
 | ARCH_201904 | systemd 241 (241.67-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_201905 | systemd 242 (242.19-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_201906 | systemd 242 (242.29-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_201907 | systemd 242 (242.32-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_201908 | systemd 242 (242.84-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_201909 | systemd 242 (242.84-2-arch) | `write(4, "65537", 5)` | 
 | ARCH_201910 | **systemd 243 (243.51-1-arch)** | `write(4, "65537\n", 6)` | 
 | ARCH_201911 | systemd 243 (243.78-1-arch) | `write(4, "65537\n", 6)` | 
 | ARCH_201912 | **systemd 243 (243.162-2-arch)** | `write(4, "65537", 5)` | 
 | ARCH_202001 | systemd 244 (244.1-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_202002 | systemd 244 (244.1-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_202003 | systemd 244 (244.3-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_202004 | systemd 245 (245.3-2-arch) | `write(4, "65537", 5)` | 
 | ARCH_202005 | systemd 245 (245.5-2-arch) | `write(4, "65537", 5)` | 
 | ARCH_202006 | systemd 245 (245.5-2-arch) | `write(4, "65537", 5)` | 
 | ARCH_202007 | systemd 245 (245.6-8-arch) | `write(4, "65537", 5)` | 
 | ARCH_202008 | systemd 245 (245.7-1-arch) | `write(4, "65537", 5)` | 
 | ARCH_202009 | systemd 246 (246.3-1-arch) | `write(4, "65537", 5)` | 

</details>

Strangely though, Gentoo's wiki suggests [using udev rules to change IPoIB transport modes](https://wiki.gentoo.org/wiki/InfiniBand#Performance_tuning), but it almost never worked.

**Comment by poettering** [comment]
Ah, excellent, thanks for going the extra mile and testing that. Much appreciated.

PR would be very welcome. And please include a man fix that tells the next one running into this how to correctly embedd newlines.

**Comment by poettering** [comment]
(it's kinda sad btw that some kernel drivers do it like one way, and the others the other way... ideally they'd all accept both with and without trailing newline... in a perfect world someone would just fix the kernel drivers for this)
