### ISSUE TITLE
/oldroot is not unmounted

### ISSUE THREAD

**Issue by rahulaggarwal965** [systemd/systemd#17133]
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Arch Linux (Kernel 5.4.66-1-lts)

**Expected behaviour you didn't see**
 > Clean shutdown 

**Unexpected behaviour you saw**
 ```
sd-umoun[1218]: Failed to unmount /oldroot: Device or resource busy
sd-umoun[1219]: Failed to unmount /oldroot/sys: Device or resource busy
shutdown[1] Failed to finalize file systems, ignoring.
```

**Steps to reproduce the problem**
This happens when nvidia drivers are loaded and then the machine is shutdown or rebooted. It happens every time.

I realize that this has been talked about before downstream as well as with binfmts here, but I am unsure how I would debug this problem. It looked like there were some updates that were supposed to solve this, but I have not been able to fix it.

I did try booting with systemd debug kernel params and using the debug.sh script in system-shutdown but oldroot was not referenced in that file ever.

**Comment by poettering** [comment]
/oldroot is where the initrd is moved during the initrd-to-host transition. If that cannot be unmounted then something from the initrd is probably runnig the whole time and keeps things pinned. Normally, /oldroot should already be gone by the time the main PID 1 takes over during boot, i.e. much much earlier than during shutdown.

This is something to report to your initrd implementation first, as systemd is just the messenger, i reports that it cannot unmount things when it tries to, but the reason it cannot do that is that something keeps thigs pinned from it.

Hence, please contact the archlinux initrd maintainers about this. If there's an issue in systemd here after all they'll escalate this back to us. But let's close this here. Hope that makes sense.
