### ISSUE TITLE
systemd-nspawn: Some SELinux questions / issues

### ISSUE THREAD

**Issue by resdigita** [systemd/systemd#17140]
I want to use systend-nspawn as OS type container on a Fedora 32 server. 

But currently I only managed to do this if I run the host system in SELinux permissive mode.

What I have done:

- New installation of Fedora 32, SELinux enforcing by default

- Installation of package systemd-container, Version 245.7

- Installation of a container directory via

  `dnf --releasever=32      --best         --setopt=install_weak_deps=False        --installroot=/var/lib/machines/test/   
       install dhcp-client dnf fedora-release glibc glibc-langpack-en glibc-langpack-de  iproute iputils less passwd  
       sudo systemd vim-minimal`

- **Set a root password** in the container:
`systemd-nspawn -D /var/lib/machines/test02  passwd`
**Result: failed**

  > passwd: Authentication token manipulation error
  > Container test failed with error code 1.
 
   Only **solution** found so far: 
Temporarily switch to _permissive_ mode (not fine, but I could live with that)

- Starting the container, SELinux enforcing, via
  > systemd-nspawn -U -b -D /var/lib/machines/test 

  **Result: fine, but not a permanent operation mode**
   Container startet, I could login. 

- Starting the **container as a service**, SELinus still enforcing, via
  > systemctl  start  systemd-nspawn@test 
  > systemctl  status  systemd-nspawn@test 

  **Result: failed**
  > … 
  > Process: 2327 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot 
  >               --link-journal=try-guest --network-veth -U –settings=override  
  >               --machine=test (code=exited, status=1/FAILURE)
  > …
  > Status: "Terminating…"
  > Error: 13 (Keine Berechtigung) ((i.e. no permission))
  > … 
  > Failed to register machine: Access denied
  > Parent died too early
 
  **Solutions** found so far:
  
  a) SELinux permanently in permissive mode
  b) Remove the --keep-unit parameter (OK I hope)
    > systemctl  edit  systemd-nspawn@test01
    > 	[Service]
    > 	ExecStart=
    > 	ExecStart=/usr/bin/systemd-nspawn --quiet --boot   --link-journal=try-guest --network-veth -U –settings=override   --machine=test
 

- Opening of a terminal with machinectl, Linux enforcing

  **Result: failed**

  > machinectl  list
  > MACHINE CLASS     SERVICE        OS VERSION ADDRESSES
  > test.   container systemd-nspawn -  -       - 
  > machinectl  login test
  > Failed to get login PTY: Access denied 

   Only **solution** found so far: 
Permanently switch to _permissive_ mode (not acceptable)

**My questions:**
- Did I miss something in the documentation?
- Is there a workaround to use machinectl login also in enforcing mode?

**Comment by poettering** [comment]
hmpf, these things should in theory just work. but we are not selinux pros, we rely on patch submissions for selinux to keep working.

@cgzones maybe something you have a clue about this?

my educated guess: the selinux policy needs some updates

**Comment by cgzones** [comment]
With version `systemd 246 (246.6-1)` on Debian sid I do not notice any failures.

Are there any related SELinux denials (`ausearch -m avc,user_avc` / `journalctl --grep avc`)?
Maybe retry with dontaudit rules disabled (`semodule -DB` (`semodule -B` to re-enable dontaudit rules)).

**Comment by resdigita** [comment]
> With version systemd 246 (246.6-1) on Debian sid I do not notice any failures.

I'm not sure and by far not an expert, but doesn't use Debian apparmor instead of selinux? 

> Are there any related SELinux denials (ausearch -m avc,user_avc / journalctl --grep avc)?
> Maybe retry with dontaudit rules disabled (semodule -DB (semodule -B to re-enable dontaudit rules)).

Unfortunately, I don't know anything about these things and don't know what I've to do. I've searched the internet and found in various documentations, the file /var/log/audit/audit.log contains information about the causes of the blockade by selinux. I hope it is helpful here, too, and provides the informations you are looking for:

If I start my standard installation with standard systemd configuration **with --keep-unit** included in **permissive** mode I get in audit.log:

```
type=SERVICE_START msg=audit(1600934206.427:1907): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@dm-mod comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
type=SERVICE_STOP msg=audit(1600934206.427:1908): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@dm-mod comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
type=UNKNOWN[1334] msg=audit(1600934206.431:1909): prog-id=323 op=LOAD
type=AVC msg=audit(1600934206.828:1910): avc:  denied  { search } for  pid=1048 comm="systemd-machine" name="11173" dev="proc" ino=272323 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=1
type=AVC msg=audit(1600934206.828:1911): avc:  denied  { read } for  pid=1048 comm="systemd-machine" name="cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1912): avc:  denied  { open } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1913): avc:  denied  { getattr } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1914): avc:  denied  { ioctl } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 ioctlcmd=0x5401 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=SERVICE_START msg=audit(1600934206.890:1915): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-nspawn@test04 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"

```

If I try the same in **enforcing** mode I get in audit.log

```
type=MAC_STATUS msg=audit(1600934515.057:1918): enforcing=1 old_enforcing=0 auid=0 ses=38 enabled=1 old-enabled=1 lsm=selinux res=1AUID="root"
type=SERVICE_START msg=audit(1600934585.870:1919): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@dm-mod comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
type=SERVICE_STOP msg=audit(1600934585.871:1920): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=modprobe@dm-mod comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
type=UNKNOWN[1334] msg=audit(1600934585.876:1921): prog-id=324 op=LOAD
type=AVC msg=audit(1600934585.915:1922): avc:  denied  { search } for  pid=1048 comm="systemd-machine" name="11246" dev="proc" ino=277012 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=0
type=SERVICE_START msg=audit(1600934585.933:1923): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-nspawn@test04 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'UID="root" AUID="unset"
type=UNKNOWN[1334] msg=audit(1600934585.961:1924): prog-id=324 op=UNLOAD
type=SERVICE_START msg=audit(1600934593.192:1925): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf-makecache comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
type=SERVICE_STOP msg=audit(1600934593.192:1926): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf-makecache comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
```

If I  try to login into a running container  using **machinectl** in **permissive** mode I get

```
type=AVC msg=audit(1600935435.897:1930): avc:  denied  { search } for  pid=1048 comm="systemd-machine" name="6131" dev="proc" ino=186887 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=1
type=AVC msg=audit(1600935435.898:1931): avc:  denied  { read } for  pid=1048 comm="systemd-machine" name="mnt" dev="proc" ino=191818 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1600935435.898:1932): avc:  denied  { sys_ptrace } for  pid=1048 comm="systemd-machine" capability=19  scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:systemd_machined_t:s0 tclass=cap_userns permissive=1
type=AVC msg=audit(1600935435.898:1933): avc:  denied  { read } for  pid=1048 comm="systemd-machine" scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600935435.899:1934): avc:  denied  { sys_admin } for  pid=11297 comm="(sd-openptns)" capability=21  scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:systemd_machined_t:s0 tclass=cap_userns permissive=1
type=AVC msg=audit(1600935435.899:1935): avc:  denied  { setgid } for  pid=11297 comm="(sd-openptns)" capability=6  scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:systemd_machined_t:s0 tclass=cap_userns permissive=1
type=AVC msg=audit(1600935435.899:1936): avc:  denied  { setuid } for  pid=11297 comm="(sd-openptns)" capability=7  scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:systemd_machined_t:s0 tclass=cap_userns permissive=1
type=AVC msg=audit(1600935435.900:1937): avc:  denied  { read } for  pid=11298 comm="(sd-openpt)" name="ptmx" dev="tmpfs" ino=183578 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1600935435.900:1938): avc:  denied  { open } for  pid=11298 comm="(sd-openpt)" path="/dev/pts/ptmx" dev="devpts" ino=2 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:devpts_t:s0 tclass=chr_file permissive=1
type=AVC msg=audit(1600935435.904:1939): avc:  denied  { read } for  pid=11300 comm="(sd-buscntr)" name="run" dev="dm-10" ino=12585120 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1600935435.904:1940): avc:  denied  { write } for  pid=11300 comm="(sd-buscntr)" name="system_bus_socket" dev="tmpfs" ino=193432 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=sock_file permissive=1
type=AVC msg=audit(1600935435.904:1941): avc:  denied  { connectto } for  pid=11300 comm="(sd-buscntr)" path="/run/dbus/system_bus_socket" scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=1
type=AVC msg=audit(1600935435.908:1942): avc:  denied  { read write } for  pid=783 comm="dbus-broker" path="/dev/pts/ptmx" dev="devpts" ino=2 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:devpts_t:s0 tclass=chr_file permissive=1
```

If I do the same in **enforcing** mode I just get
```
type=AVC msg=audit(1600936185.945:1999): avc:  denied  { search } for  pid=1048 comm="systemd-machine" name="11417" dev="proc" ino=280789 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=0

```

I hope it helps

**Comment by cgzones** [comment]
> I'm not sure and by far not an expert, but doesn't use Debian apparmor instead of selinux?

Yes, Debian uses apparmor by default, but I was referring to no failures on Debian with SELinux in enforced mode.

> type=AVC msg=audit(1600934206.828:1910): avc:  denied  { search } for  pid=1048 comm="systemd-machine" name="11173" dev="proc" ino=272323 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=1
type=AVC msg=audit(1600934206.828:1911): avc:  denied  { read } for  pid=1048 comm="systemd-machine" name="cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1912): avc:  denied  { open } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1913): avc:  denied  { getattr } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
type=AVC msg=audit(1600934206.828:1914): avc:  denied  { ioctl } for  pid=1048 comm="systemd-machine" path="/proc/11173/cgroup" dev="proc" ino=275274 ioctlcmd=0x5401 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1

systemd-machined wants to read the cgroup of the process 11173, which is probably systemd-nspawn.

All in all, the failures seem to result by your policy not allowing the required accesses.

You should consult the maintainer of the SELinux policy, in your case probably the Fedora selinux-policy package maintainers.

**Comment by resdigita** [comment]
> Yes, Debian uses apparmor by default, but I was referring to no failures on Debian with SELinux in enforced mode.

Oh thanks, I didn't know that selinux is even an option in Debian. Good to know.

> You should consult the maintainer of the SELinux policy, in your case probably the Fedora selinux-policy package maintainer

I'm wondering which component I'm submitting a bug report for: systemd-container, selinux-policy or selinux-policy-targeted? Who assigns the selinux labels and permissions to the files of a package, the systemd-container packager or is this done centrally by selinux-policy packagers? And who can make a change that fixes the problem? It suppose, selinux-policy it the best target?

**Comment by resdigita** [comment]
Just another question: I'm, wondering about the --keep-unit parameter as a default value in the Fedora package. As I read the documentation this parameter is for a special use case. My use case is a standard one, to expose the host as little as possible and to containerise long-running publicly accessible processes such as Jenkins and web servers. 

Could removing this parameter for my use case cause any drawbacks or negative side effects?

**Comment by poettering** [comment]
--keep-unit means you run your container in the cgroup you are invoked in. This is the right choice if you invoke your systemd-nspawn command from an ExecStart= line of a systemd service. If you invoke the tool from the shell don't use that though as shell sessions do not have delegation on for their cgroups.

Either way the setting should be irrelevant to any selinux questions.

**Comment by resdigita** [comment]
Thanks for the info

> Either way the setting should be irrelevant to any selinux questions.

Unfortunately, the parameter causes an selinux denial during container startup using `systemctl start systemd-nspawn@<name>` at the moment. In order tobe able to successfully start the containers automatically at boot time, I need to temporarily remove the parameter from the startup configuration to run the server in enforcing mode - until the issue is resolved.

But if this leads to unreliable behaviour of the containers, I have to either run the server in permissive mode or I have to do without nspawn containerisation for the time being.

So my question is, due to the _architecture_ of systemd, can a container started by `systemctl start systemd-nspawn@<name>` run as reliable without a --keep-unit in the start configuration or are constructional errors to be expected? Or in other words, is it a "malpractice"/ carelessness to start a container as a service without this parameter?

**Comment by poettering** [comment]
if you drop --keep-unit you'll always have two units: the systemd-nspawn@.service one will just container nspawn itself, while the container payload will be in a separate scope. which shoud just work, but is ugly, and a terrible work-around for a selinux policy bug.

Anyway, please report to fedora bugzilla against the selinux policy package (probably selinux-policy-targeted, they will reassign if not), it's a downstream thing. selinux policy is managed centrally, we do not write it, the selinux people do (and we lack expertise for that really).

Anyway, closing
