### ISSUE TITLE
machinectl import-fs mishandles ACLs

### ISSUE THREAD

**Issue by alajovic** [systemd/systemd#17178]
**systemd version the issue has been seen with**
> 245.7

**Used distribution**
 > Gentoo Linux

**Expected behaviour you didn't see**
 > I imported a root filesystem of a container with `machinectl import-fs`. I expected the system to be imported exactly as-is, including file ownership, permissions, and ACLs.

**Unexpected behaviour you saw**
 > While file ownership and permissions seemed to have been preserved, the import procedure discarded all ACLs. Since the system in the container depended on certain ACLs, it was not fully functional when I booted it with nspawn.

**Steps to reproduce the problem**

Create an example filesystem:
```
# mkdir testfs
# cd testfs
# touch foo bar baz
# ls -lh
total 0
-rw-r--r-- 1 root root 0 Sep 27 17:30 bar
-rw-r--r-- 1 root root 0 Sep 27 17:30 baz
-rw-r--r-- 1 root root 0 Sep 27 17:30 foo
```

Set an ACL on one of the files, and verify that it has actually been set:
```
# setfacl -m u:daemon:rw foo

# ls -lh
total 0
-rw-r--r--  1 root root 0 Sep 27 17:30 bar
-rw-r--r--  1 root root 0 Sep 27 17:30 baz
-rw-rw-r--+ 1 root root 0 Sep 27 17:30 foo

# getfacl foo
# file: foo
# owner: root
# group: root
user::rw-
user:daemon:rw-
group::r--
mask::rw-
other::r--
```

Import the tree with machinectl:
```
# machinectl import-fs . testmachine
Enqueued transfer job 1. Press C-c to continue download in background.
Importing '/root/testfs', saving as 'testmachine'.
Exiting.
```

List the contents of the imported machine. The ACL on the file `foo` has vanished, and the file's permissions have been set to `-rw-rw-r--` instead.
```
# ls -lh /var/lib/machines/testmachine/
total 0
-rw-r--r-- 1 root root 0 Sep 27 17:30 bar
-rw-r--r-- 1 root root 0 Sep 27 17:30 baz
-rw-rw-r-- 1 root root 0 Sep 27 17:30 foo

# getfacl /var/lib/machines/testmachine/foo
getfacl: Removing leading '/' from absolute path names
# file: var/lib/machines/testmachine/foo
# owner: root
# group: root
user::rw-
group::rw-
other::r--
```

**Comment by poettering** [comment]
are the source and target fs the same type? i.e. both ext4 or so?

**Comment by alajovic** [comment]
Yes, in my case, both the source and the destination were on the same btrfs filesystem.

**Comment by alajovic** [comment]
Just checked with systemd 246.6 on Arch Linux and ext4 filesystem, result is the same.

**Comment by alajovic** [comment]
@poettering, any more input needed on this? The needs-reporter-feedback label is still active, so I don't know whether I gave sufficient feedback or not.

I have also looked at the source code in the meantime, and it seems that ACLs are just plainly ignored when importing. That is, no attempt is made to copy them at all.

**Comment by poettering** [comment]
ACLs are stored in xattrs and those we copy. i.e. the `system.posix_acl_access` xattr should be copied over. Apparently that doesn't work however maybe we need to copy acls differently.

**Comment by alajovic** [comment]
I wasn't aware that ACLs were implemented in terms of xattrs, but it makes sense now that you mention it. Thanks. I dug further, and found this in the xattr copy loop in copy_xattr().

```
if (!startswith(p, "user."))
        continue;
```
(`p` is the name of the xattr being copied). ACLs, I now see, are stored under the xattr `system.posix_acl_access`, and since this name does not begin with `user.`, the attribute gets ignored.

**Comment by alajovic** [comment]
@poettering, the attribute filter was introduced in commit e6bd041c97 (almost six years ago) in which copying of xattrs was implemented. You are written down as the author of the commit, so do you perhaps remember why this filter was necessary?

**Comment by alajovic** [comment]
Coming back to this after a while, I see that the behavior is still the same. In my opinion, copying only xattrs from the `user` namespace (i.e., those that begin with `user.`) is clearly incorrect, as it omits ACLs (which are in the `system` namespace, i.e., names start with `system.`). ACLs are needed for proper functioning of imported systems, so they should not be discarded by `machinectl import-fs`.

Unless someone provides a good argument for doing otherwise, I'll go ahead and propose a pull request that removes the xattr filter from `copy_xattr()`.
