### ISSUE TITLE
man: systemd-tmpfiles typo:  systemd-tmpfiles-cleanup.service → systemd-tmpfiles-clean.service

### ISSUE THREAD

**Issue by gitterman** [systemd/systemd#17171]
This is a multi item enhancement request.
systemd-tmpfiles is a very complex service and it is has flaws which affect many users as can be seen by a wealth of posts on the subject in various forums.
What is definitely missing is the option to ignore certain timestamps.
Especially the option to ignore access time on specific files or directories is missing.
If the age parameter is set and some process does an inventory on files in e.g. /tmp, thus accessing its contents, then files cannot get cleaned by tmpfiles.d rules.
This is definitely a gap.
Also, there is no size option on directories containing tmpfiles, which can lead to file system overflow.

On the other hand the default to clean tmpfiles unconditionally at boot is way too harsh.
A default should always be conservative and don't do things if they are not necessary.
I.e. if tmpfiles are not using too much size or if files are not older than a couple of days there is no real need to do something.
Thus,  the default should use an age specifier e.g. 5 days.

The man page of tmpfiles.d mentiones a  systemd-tmpfiles-cleanup.service.
This service does not exist, but there is a  systemd-tmpfiles-clean.service.

The man page of tmpfiles.d and systemd-tmpfiles are missing a clear description why and how e.g. /tmp gets cleaned by default on every boot and an example how to change this.

**Comment by poettering** [comment]
My assumption here is that you are talking about the "file aging" logic of systemd-tmpfiles?

The no-atime checking has been requested in #17002 already.

> If the age parameter is set and some process does an inventory on files in e.g. /tmp, thus accessing its contents, then files cannot get cleaned by tmpfiles.d rules.

Well, /tmp has terrible semantics, admittedly. Don't place your data there, if you are can#t deal with these terrible semantics, but systemd-tmpfiles won't fix them for you, the "file aging" logic it implements just makes one facet a bit less terrible: the directories get cleaned up now every now and then.

If you are asking for quota on /tmp, then by all means use that, but systemd-tmpfiles is not a tool for implementing quota.

> On the other hand the default to clean tmpfiles unconditionally at boot is way too harsh.

We don't do that. Maybe your /tmp is a tmpfs? It's what we recommend, but not require. It means the files stored there are backed by RAM+swap not a persistent fs, and things are flushed out during boot. But given the accepted semantics of /tmp that shouldn't matter, as it is the place to store temporary data. If you store data you want to keep there, then you are misuing it.

If your /tmp is tmpfs, it comes with quota already built in, you can adjust the size= mount option in /etc/fstab for it, to put a size limit ont it of your choice.

> The man page of tmpfiles.d mentiones a systemd-tmpfiles-cleanup.service.
> This service does not exist, but there is a systemd-tmpfiles-clean.service.

Indeed! Will file fix shortly. Thanks!



> The man page of tmpfiles.d and systemd-tmpfiles are missing a clear description why and how e.g. /tmp gets cleaned by default on every boot and an example how to change this.

As mentioned, we actually don't do that, systemd-tmpfiles doesn't and has no influence on it. It sounds as if your /tmp is a tmpfs, and thus flushed out.

In general, it appears to me you are using /tmp for stuff it shouldn't be used for. The semantics of /tmp/ are terrible, admittedly, but if you assume it is for storing data persistently, then you are mistaken, sorry. At the very least use /var/tmp for that (which can take much larger data, and is not backed by tmpfs, and thus will survive reboots), but it appears me you actually want to use your home directory $HOME instead, which can be used to store data persistently, without automatic time-based clean-up.

**Comment by gitterman** [comment]
Thanks for the clarification.
I stumbled upon the /tmp issue on the latest RaspberryOS.
/tmp is a regular dir under '/' there, but it gets unconditionally cleaned on every boot.
I saw that when my system crashed and I wanted to check the possible cause.
Sometimes files in /tmp give a hint on that.
If systemd-tmpfiles isn't responsible for it I have no clue what does the cleanup of /tmp at boot.

With respect to the cleanup by age I think I am not safe if I use /var/tmp or any other dir because systemd-tmpfiles will not clean any files in any dir if the age specifier is set and the file access time gets updated.
I think I will need to do my own housekeeping on temporary directories as well as on log files.

**Comment by poettering** [comment]
> If systemd-tmpfiles isn't responsible for it I have no clue what does the cleanup of /tmp at boot.

It might be that your OS is changing our upstream defaults to make it do that. But from upstream we don't do that.

**Comment by poettering** [comment]
The relevant upstream file (`/usr/lib/tmpfiles.d/tmp.conf`) looks like this:

```
…
q /tmp 1777 root root 10d
q /var/tmp 1777 root root 30d
…
```

This just creates the dirs, and ages out files after 10d/30d. Maybe your distro changes the "q" to something else.

**Comment by poettering** [comment]
I changed this to a doc issue now, since from the four things (atime, delete-on-boot, quota, man page typo) only the latter remains. The others are not responsibility of our upstream systemd-tmpfiles or already have an issue filed.

**Comment by mbiebl** [comment]
> > If systemd-tmpfiles isn't responsible for it I have no clue what does the cleanup of /tmp at boot.
> 
> It might be that your OS is changing our upstream defaults to make it do that. But from upstream we don't do that.

I assume RaspberryOS is based on Raspbian and thus ultimately Debian.
So this might indeed be the case, if they use the package from Debian.
See https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/patches/debian/Bring-tmpfiles.d-tmp.conf-in-line-with-Debian-defaul.patch

Regards

**Comment by gitterman** [comment]
I created an empty /etc/tmpfiles.d/tmp.conf and then /tmp files don't get cleaned.
Thus, you are right., the raspberry OS seems to have the changed defaults.

**Comment by poettering** [comment]
> So this might indeed be the case, if they use the package from Debian.
> See https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/patches/debian/Bring-tmpfiles.d-tmp.conf-in-line-with-Debian-defaul.patch

Hmm, Debian doesn't clean up /tmp and /var/tmp at all, still? So if they run full your system is basically hosed?

**Comment by mbiebl** [comment]
no, there is no peridioc/automatic cleanup of /var/tmp and /tmp. /tmp is only cleaned up during boot.

**Comment by mbiebl** [comment]
A periodic cleanup of /tmp and /var/tmp does not really guard you against your system running full (one process running amok can do that within a short period of time). For that you'd need quotas.

**Comment by poettering** [comment]
> A periodic cleanup of /tmp and /var/tmp does not really guard you against your system running full (one process running amok can do that within a short period of time). For that you'd need quotas.

Sure, /tmp sucks in its semantics, people shouldn't use it. But just letting it fill up (regardless if with quota boundary or fs size boundary) is a bad idea, no? We cannot properly fix /tmp, but there really should be a away it is kept under control so that eventually the system can recover even if it fills up temporarily.

Quota alone is not going to deliver this for you: it must be quota in combination with automatic clean-up, so that the filling up won't be propagated out of /tmp and the filling up has a chance of being cleaned up eventually...
