### ISSUE TITLE
[pam] computer takes long time to boot/allow ssh login

### ISSUE THREAD

**Issue by gearhead** [systemd/systemd#17179]
**systemd version the issue has been seen with**
>  246.6-1-arch

**Used distribution**
 > Arch Arm RaspberryPi armv6, armv7, aarch64 kernel 5.4.65

**Expected behaviour you didn't see**
 > full startup in a reasonable time. 

**Unexpected behaviour you saw**
 > hanging on boot. Inability to ssh in to cli. Required multiple attempts simultaneously until one window actually responded from teh password request. I could ge a login:, but after I typed in the password, it would hang.

**Steps to reproduce the problem**
Install Arch Linux on any RPi, enable sshd, reboot and attempt to ssh into the Rpi. 

My workaround was to build the previous shipping version of pam/pambase for arch. When installed this 'seems' to fix it. The version of pam/pambase on arch arm is currently is pam-1.4.0-3  pambase-20200721.1-2, I installed  pam-1.3.1-2 pambase-20190105.1-2 and get normal login response and boot times.

**Comment by gearhead** [comment]
The 'workaround' just broke with another update. as of yesterday afternoon (2020/09/27), when I try to install the older pam and pambase, the passwords become invalid and I cannot log in at all. The problem does not appear to affect current 64 bit OSes that I run (aarch64, x86_64), but is present on both armv6h and armv7h running on a raspberrypi.

**Comment by poettering** [comment]
This doesn't really look like it has much to do with systemd. Please contact your downstream distro (i.e. the Arch community) first, they'll help you and escalate this back to us in the (unlikely) case this is actually a systemd issue.

Thank you for understanding.
