### ISSUE TITLE
Use the tool of wakeonlan to send MagicPacket wake system which is sleeped by use the command of sytemctl suspend.Nothing happens in the system.

### ISSUE THREAD

**Issue by zhongjianwen** [systemd/systemd#17182]
I'm always frustrated when use the tool of wakeonlan to send MagicPacket wake system which is sleeped by use the command of sytemctl suspend,because nothing happens in the system.

Use the tool of pm-suspend to replace sytemctl suspend, System can wake up by wakeonlan to send MagicPacket.

After I use pm-suspend, use sytemctl suspend again to take effect. But after system reboot, first use sytemctl suspend will not take effect.

**Comment by poettering** [comment]
what does "pm-suspend" differently than what we do? we just echo one of "mem", "standby", "freeze" into /sys/power/state, until one works. There's nothing much else we do.

pm-suspend is a shell script, but what does it actually do for you differently?

**Comment by poettering** [comment]
If you play around with the sleep states in /etc/systemd/sleep.conf, can you make it work then?

If the default state selection doesn't work this indicates an issue with your system/firmware i guess. Not sure what we can do about that...

**Comment by poettering** [comment]
Let's close this, due to lack of response
