### ISSUE TITLE
use FIDO2 credential to sign the UserRecord, making home directories truly portable

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#17183]
**Is your feature request related to a problem? Please describe.**
Having to copy over `/var/lib/systemd/home/local.private` between my devices is cumbersome; especially if I already have a perfectly capable FIDO2 device for storing private key credentials.  It might not even be possible ; say my  root partition disk fails completely, I don't have backups, but I do have a backup of my home directory.

**Describe the solution you'd like**

Currently we're using the FIDO2 credential _just_ for the `hmac-secret`; but when we create the credential; it will also generate an associated public-private keypair, that signs the `clientdata_hash` using the private key when making assertions,  and returns that field in the assertion as the `signature`. We currently simply discard that. But if we don't do that, I think we can  build a pretty awesome feature!

Instead of setting `clientdata_hash` to all zeroes as we currently do
https://github.com/systemd/systemd/blob/feee7f62889fe2e936e7cca8f194ec44e0d4f4d8/src/home/homework-fido2.c#L79

we could set `clientdata_hash` to the hash of our `UserRecord` fields 
and store the `signature` field returned by 
https://github.com/systemd/systemd/blob/feee7f62889fe2e936e7cca8f194ec44e0d4f4d8/src/home/homework-fido2.c#L96

The signature format that FIDO2 produces is the same as systemd uses, and can be consumed with `EVP_DigestVerify`

When creating a home directory and user, should also store the associated public key generated by
https://github.com/systemd/systemd/blob/feee7f62889fe2e936e7cca8f194ec44e0d4f4d8/src/home/homectl-fido2.c#L264
 in the `UserRecord`

`libfido2` already comes with the functions to convert a FIDO2 public key into the format that systemd currently uses (`EVP_PKEY`)

https://github.com/Yubico/libfido2/blob/58c553e6110811212edec8cf8141b2e595b26073/src/fido/eddsa.h#L27

This is rather elegant, as it means we can move around our identity on our yubikey, and don't require copying files between hosts in order to modify `UserRecord`s.  It makes your portable home diretory _truly_ portable.

**Describe alternatives you've considered**
None

**Comment by poettering** [comment]
Hmm, you don't actually have to copy local.private at all — as long as you are OK with the user records being immutable on the specific system. local.private needs to be copied only if you want to be able to make changes to the user record, so that we can re-sign the record afterwards.

You always need to copy local.public however, since without that we won#t even allow logging in.

I can see that it's a certain kind of sexy if we'd make use of the private key stored on the FIDO2 token, but this would only make it unnecessary to copy local.private, you'd still have to copy local.public. But if you copy one manually, is it really that much better to not need to copy the other too? I mean, the mess of having to invoke "scp" or so remains, it's just one file less...

Or what am I missing?

**Comment by arianvp** [comment]
> Or what am I missing?

The public key is part of the `Credential` that `fido_dev_make_cred` returns. We can store a 
`Map<CredentialId,PublicKey>` in the `UserRecord`

We then pass `fido_dev_get_assert` the list of `CredentialIds`s and it will tell us which `CredentialId` was used in the response. We can then use that to look up the corresponding `publicKey` from the user record,  and use that to verify the `signature` that `fido_dev_get_assert` returned

**Comment by poettering** [comment]
I think there's a misunderstanding: homed uses /var/lib/systemd/home/*.public as sort of keychain that contains all keys that can be used for signing user records that may log in locally. It's access control if you so will: unless the public key used for signing your user record is known locally we will not allow logging in. i.e. we explicitly do not allow arbitrary users to log in onto arbitrary machines. There needs to be a step in place where foreign previously unsees users are somehow marked OK.

Thus having a user account on a stick + a matching fido2 token is not enough for what we want to do. Random users which posses both should still not be allowed access locally...

**Comment by poettering** [comment]
(something we want to do eventually is that if you plug in a random usb stick with a user on it locally and it's not signed by a locally known key, that via policykit and root-level auth we optionally add the signing key to the local keychain to allow future log-ins by all users signed with that key without further ado. i.e. gdm would pop up a dialog "hey, you plugged in a user `foo`, do you want allow logging in with it on this machine, if so, provide both `foo`'s password and root's password" — but for that fido2 is not needed...)

**Comment by arianvp** [comment]
Hmm; I gave your message some thought. And in that case I indeed do not see the added benefit of this. For that usecase having the private key on a hardware device might even be a hindrance...

**Comment by poettering** [comment]
ok, let's close this then!
