### ISSUE TITLE
seccomp-util: Missing arch specific syscalls

### ISSUE THREAD

**Issue by FlyGoat** [systemd/systemd#17197]
**Expected behaviour you didn't see**
 Start a systemd-nspawn container, run NodeJS inside it.

**Unexpected behaviour you saw**
 NodeJS crahsed with:
```
# Fatal error in , line 0
# Failed to flush the instruction cache from 0xafde048040 with size 12
```

**Reasoning**
NodeJS uses v8 JIT engine, which relies on `NR_cacheflush` syscall to synchonize I-Cache and D-Cache.
However, it is not known to seccomp-util, so it will be banned by the seccomp with `-EPERM`.

Also there is a report[1] that a similiar issue happens on AArch64 system when runing legacy Arm binary inside the container.

[1]: https://blog.canvon.de/posts/arm_legacy_system_alongside_arm64_replacement/

**Comment by keszybz** [comment]
The bug template is very verbose about this... what systemd version are you speaking about?

**Comment by poettering** [comment]
seems 246 lacks the line for it in `@default`. i'll prep a PR

**Comment by FlyGoat** [comment]
> seems 246 lacks the line for it in `@default`. i'll prep a PR

```
#define __ARM_NR_BASE			(__NR_SYSCALL_BASE+0x0f0000)
#define __ARM_NR_breakpoint		(__ARM_NR_BASE+1)
#define __ARM_NR_cacheflush		(__ARM_NR_BASE+2)
#define __ARM_NR_usr26			(__ARM_NR_BASE+3)
#define __ARM_NR_usr32			(__ARM_NR_BASE+4)
#define __ARM_NR_set_tls		(__ARM_NR_BASE+5)
```

What about those for Arm?

**Comment by poettering** [comment]
I don't know what they do. Should they be in the default set or so?

(set_tls is already in the `@default` set btw, and)

**Comment by FlyGoat** [comment]
> 
> 
> I don't know what they do. Should they be in the default set or so?
> 
> (set_tls is already in the `@default` set btw, and)

`usr26` and `usr32` are used to switch between different execution modes for a thread and I guess they should also be a part of `@default`.

`breakpoint` should be a part of `@debug`.

Thanks~

**Comment by keszybz** [comment]
Hmm, I'm not sure about usr26 and usr32. They appear in kernel sources but only as the number defines.

From http://51.15.138.76/patch/19182/:
> Having a wrapper for usr26 and usr32 is almost certainly not useful, especially if we are contemplating removing support for
ARMv4 (because these syscalls don't work on v4T or anything newer). 

Since this hasn't come up before, maybe they aren't needed at all, or should be added to `@obsolete`?

**Comment by poettering** [comment]
I'd probably just close this, until someone who runs into this or cares about arm reports this to us. For `cacheflush()` we know it's apparently use, so adding htat was obvious, but for the other ones I'd really just wait it out.

**Comment by keszybz** [comment]
Yeah, I agree.

**Comment by srd424** [comment]
FWIW, I've been chasing a problem with Java crashing randomly when nested in docker/podman containers inside nspawn containers (probably best not to ask why I'm doing this.) Turns out adding cacheflush solves the problem. I haven't tested Java directly in nspawn containers, I would expect the same issue but then I'm surprised nobody has hit this before.

**Comment by srd424** [comment]
Trivial test case if anyone needs it - for some reason arm doesn't have `asm/cachectl.h` ..
```
#include <unistd.h>
#include <sys/syscall.h>   /* For SYS_xxx definitions */
#include <stdio.h>

void main()
{
        char foo[10];

        if(syscall(__ARM_NR_cacheflush, &foo[0], &foo[10], 0))
                perror("cacheflush: ");
        else
                printf("ok.\n");
}
```
