### ISSUE TITLE
In contrast to StartUnit() the StartTransientUnit() D-Bus call doesn't pass unit name metadata to PolicyKit authorization request

### ISSUE THREAD

**Issue by nlzv** [systemd/systemd#17224]
systemd-245.8-2.fc32.x86_64
polkit-0.116-7.fc32.x86_64

Fedora core 32 64 bit

```
systemd-run --scope -u isc_cache ccontrol start 201722B865D3
```
purpose not root user might able to start transient unit

```
cat /etc/polkit-1/rules.d/10-isc-cache.rules
polkit.addRule(function(action, subject) {
 if (action.id == "org.freedesktop.systemd1.manage-units" ) {
   polkit.log("action lookup unit=" + action.lookup("unit") );
   // !!! system-run  action.lookup("unit") undefined
   if ( action.lookup("unit") == "isc_cache.scope" && subject.isInGroup("cachemgr") ) {
     return polkit.Result.YES;
   }
  // ok systemctl start|stop isccache@<instance> for /etc/systemd/system/isccache@.service
  // purpose not root might start isc cache service if user memeber of cachemgr group
   if ( RegExp("isccache@[A-Za-z0-9_-]+.service").test(action.lookup("unit")) && subject.isInGroup("cachemgr") ) {
     return polkit.Result.YES;
   }

 }
});
```

as test code instead 
ccontrol start 201722B865D3
might be simple code

```
#include <unistd.h>
int main(int argc , char * argv [] ) {
  for(;;)
   sleep(1);
}
```
Terminate it sending SIGTERM signal.

as I understand
StartTransientUnit doesn send appropriate details when it calls CheckAuthorization.

If it is required I might add dbus-monitor --system log excerpt related to issue.

**Comment by nlzv** [comment]
There is stuff to reproduce problem.
Though it seems idea of problem should be enough.

testecho.c

#include <unistd.h>
#include <stdio.h>
int main(int argc , char * argv [] ) {
 printf("%s",arv[1]);
}

gcc -g testecho.c -o testecho

example of service file
testecho@.service
[Unit]
Description='test echo'

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=testecho start %i
ExecStop=true

[Install]
WantedBy=multi-user.target


suppose user testecho in group testecho.

cat /etc/polkit-1/rules.d/10-testecho.rules
polkit.addRule(function(action, subject) {
if (action.id == "org.freedesktop.systemd1.manage-units" ) {
polkit.log("action lookup unit=" + action.lookup("unit") );
// !!! system-run action.lookup("unit") undefined
if ( action.lookup("unit") == "testechorun.scope" && subject.isInGroup("testecho") ) {
return polkit.Result.YES;
}
// ok systemctl start|stop isccache@ for /etc/systemd/system/isccache@.service
// purpose not root might start isc cache service if user memeber of cachemgr group
if ( RegExp("testecho@[A-Za-z0-9_-]+.service").test(action.lookup("unit")) && subject.isInGroup("testecho") ) {
return polkit.Result.YES;
}

}
});

if user testecho does
systemctl start testecho@aaa
then it is ok
but if run
systemd-run --scope -u techoechorun testecho aaa
then it fails.

problem is that for case 
systemctl start testecho@aaa
polkit jscript has  action.lookup("unit") expected value
but for case
systemd-run --scope -u techoechorun testecho aaa
action.lookup("unit") is undefined.

Here is dbus-monitor details (but for my primary sample)

systemctl start isccache@201722B865D3

method call time=1601558502.288699 sender=:1.359 -> destination=org.freedesktop.systemd1 serial=3 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=StartUnit
   string "isccache@201722B865D3.service"
   string "replace"
method call time=1601558502.288930 sender=:1.103 -> destination=org.freedesktop.DBus serial=9024 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionCredentials
   string ":1.359"
method return time=1601558502.288976 sender=org.freedesktop.DBus -> destination=:1.103 serial=4294967295 reply_serial=9024
   array [
      dict entry(
         string "UnixUserID"
         variant             uint32 1000
      )
      dict entry(
         string "ProcessID"
         variant             uint32 39708
      )
      dict entry(
         string "UnixGroupIDs"
         variant             array [
               uint32 966
               uint32 974
               uint32 1000
               uint32 1092
               uint32 1093
               uint32 1196
               uint32 1197
               uint32 1197
            ]
      )
      dict entry(
         string "LinuxSecurityLabel"
         variant             array of bytes "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023" + \0
      )
   ]


method call time=1601558502.290447 sender=:1.103 -> destination=org.freedesktop.PolicyKit1 serial=9026 path=/org/freedesktop/PolicyKit1/Authority; interface=org.freedesktop.PolicyKit1.Authority; member=CheckAuthorization
   struct {
      string "system-bus-name"
      array [
         dict entry(
            string "name"
            variant                string ":1.359"
         )
      ]
   }
   string "org.freedesktop.systemd1.manage-units"
   array [
      dict entry(
         string "unit"
         string "isccache@201722B865D3.service"
      )
      dict entry(
         string "verb"
         string "start"
      )
      dict entry(
         string "polkit.message"
         string "Authentication is required to start '$(unit)'."
      )
      dict entry(
         string "polkit.gettext_domain"
         string "systemd"
      )
   ]
   uint32 1
   string ""

systemdrun

dbus-monitor --system

method call time=1601546678.753990 sender=:1.261 -> destination=org.freedesktop.systemd1 serial=3 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=StartTransientUnit
   string "isc_cache.scope"
   string "fail"
   array [
      struct {
         string "Description"
         variant             string "/usr/bin/ccontrol start 201722B865D3"
      }
      struct {
         string "PIDs"
         variant             array [
               uint32 34367
            ]
      }
   ]
   array [
   ]
method call time=1601546678.754254 sender=:1.103 -> destination=org.freedesktop.DBus serial=7990 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionCredentials
   string ":1.261"
method return time=1601546678.754282 sender=org.freedesktop.DBus -> destination=:1.103 serial=4294967295 reply_serial=7990
   array [
      dict entry(
         string "UnixUserID"
         variant             uint32 1000
      )
      dict entry(
         string "ProcessID"
         variant             uint32 34367
      )
      dict entry(
         string "UnixGroupIDs"
         variant             array [
               uint32 966
               uint32 974
               uint32 1000
               uint32 1092
               uint32 1093
               uint32 1196
               uint32 1197
               uint32 1197
            ]
      )
      dict entry(
         string "LinuxSecurityLabel"
         variant             array of bytes "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023" + \0
      )
   ]
method call time=1601546678.754939 sender=:1.103 -> destination=org.freedesktop.PolicyKit1 serial=7992 path=/org/freedesktop/PolicyKit1/Authority; interface=org.freedesktop.PolicyKit1.Authority; member=CheckAuthorization
   struct {
      string "system-bus-name"
      array [
         dict entry(
            string "name"
            variant                string ":1.261"
         )
      ]
   }
   string "org.freedesktop.systemd1.manage-units"
   array [
# here is missed unitnane
#   dict entry(
#        string "unit"
#        string UnitNmae
#      )
   ]
   uint32 1
   string ""
method return time=1601546678.755381 sender=:1.10 -> destination=:1.48 serial=1804 reply_serial=165

**Comment by nlzv** [comment]
_In contrast to StartUnit() the StartTransientUnit() D-Bus call doesn't pass unit name metadata to PolicyKit authorization _request.__
This is core of the issue. Why? There is reason for this or just one is missed to do?
man systemd-run
_If a command is run as transient service unit, it will be started and managed by the service manager like any other service ...
 If a command is run as transient scope unit, it will be executed by systemd-run itself as parent process and will thus inherit the execution environment of the
 caller. **However, the processes of the command are managed by the service manager similar to normal services**, and will show up in the output of systemctl
 list-units. Execution in this case is synchronous, and will return only when the command finishes. This mode is enabled via the --scope switch (see below)._

**Comment by xrchz** [comment]
What is needed to progress this?
