### ISSUE TITLE
Show hostnames with machinectl list

### ISSUE THREAD

**Issue by gcoretech** [systemd/systemd#17220]
I intend to replace openvz with nspawn containers using --network-veth. My first guess was to use hostnames as container (machine) names. Then I read about the 15 character limit of network interface names and that these are named after the containers' names. So I decided to use generic names like ve2001, ve2002, ... but with every container it gets harder to remember its hostname. 

It would be really helpful if the hostname could also be shown when calling machinctl list:

```
[root@test2 ~]# LD_PRELOAD=./libsystemd-shared-246.so ./machinectl list
MACHINE CLASS     SERVICE        OS VERSION HOSTNAME         ADDRESSES                                                                      
ve2001  container systemd-nspawn -  -       test2.server.lan 10.47.14.65
ve2002  container systemd-nspawn -  -       mail.server.lan  123.124.125.64                                        
ve2003  container systemd-nspawn -  -       web.server.lan   2a01::66
 ```

Therefore I created a small patch that adds a hostname column to machinectl list.
I hope someone could have a look as I'm not a C-programmer:

[systemd-master-246-hostname-patch.txt](https://github.com/systemd/systemd/files/5311549/systemd-master-246-hostname-patch.txt)

Best regards
Gerald

**Comment by poettering** [comment]
recent kernels have the "alternative names" concept which doesn't suffer by the short length limitation. We support this pretty pervasively in all our tools now. nspawn for example sets the altnames stuff to the unabbreviated network names. See this:

```
$ ip link
…
6: ve-thisisav9XJt@if2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether e6:e1:86:67:72:74 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    altname ve-thisisaverylongname
…
```

**Comment by poettering** [comment]
Please submit the patch as PR
