### ISSUE TITLE
`Gateway=_dhcp` causes [Route] section ignored

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#17249]
**systemd version the issue has been seen with**
 > 246.6

**Used distribution**
 > Archlinux

**Linux kernel version used** (`uname -a`)
 > 5.8.13

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > .network configured route is added

**Unexpected behaviour you saw**
 > error: `Route section without Gateway=, Destination=, Source=, or PreferredSource= field configured. Ignoring [Route] section from line xxx.`

**Steps to reproduce the problem**
 > `/etc/systemd/network/wired.network`
```
[Match]
Name=eth*

[Network]
DHCP=ipv4
LinkLocalAddressing=no
LLMNR=false

[DHCPv4]
UseDomains=true

[Route]
FastOpenNoCookie=true
Gateway=_dhcp
InitialAdvertisedReceiveWindow=88
InitialCongestionWindow=88
QuickAck=true
```

**Comment by yuwata** [comment]
Thank you for the report.

One workaround for this issue is once set `Gateway=0.0.0.0` and then `Gateway=_dhcp`.
```
[Route]
FastOpenNoCookie=true
Gateway=0.0.0.0
Gateway=_dhcp
InitialAdvertisedReceiveWindow=88
InitialCongestionWindow=88
QuickAck=true
```
