### ISSUE TITLE
homectl resize fails after trying to resize too small

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#17241]
I'm playing around with systemd-homed. For actual portability, it's quite important to be able to shrink a .home file to the size that it actually needs, otherwise one would copy endless Gigabytes of empty data around. This generally seems to work, but it seems homed's state gets slightly corrupted after trying to resize to a size smaller than what's actually needed.

**systemd version the issue has been seen with**
 > systemd-246.4-2.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > Linux donald 5.8.12-300.fc33.x86_64 #1 SMP Mon Sep 28 14:04:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Steps to reproduce the problem**
 
1. `homectl create -P --disk-size=500M test`
2. Log in as test (`su - test`)
3. Create a 400 MB file in test's home dir: `yes | dd bs=1M count=400 iflag=fullblock of=blob`
4. Now most of tests's home dir is used:
```
$ df -h ~
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/home-test  445M  403M   39M  92% /var/home/test
```
5. Log out
6. Try to resize it: `homectl resize test 400M`. This exectedly fails (but see below)
7. Validate that test user is still working: `homectl inspect test` still shows `Disk Size: 500.0M`, and you can log in and `df` output is unchanged.
8. Increase the size of test's home dir: `homectl resize test 600M`

**Unexpected behaviour you saw**
- Step 6 fails with a relatively confusing error message:

        Operation on home test failed: Failed to execute operation: Protocol error

- Step 8 fails with `Operation on home test failed: Access denied` (huh? -- yes, it did *not* ask me for the password..)

- Step 8 increased the disk image size, and shows too much usage:
```
# ls -lh /home/test.home 
-rw-------. 1 root root 600M  4. Okt 12:06 /home/test.home
# homectl inspect test | grep Disk
   Disk Size: 600.0M
  Disk Usage: 561.6M (= 93.7%)
   Disk Free: 38.3M (= 6.3%)
```

  ... but did not grow the filesystem:
```
$ df -h ~
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/home-test  445M  403M   39M  92% /var/home/test
```

**Expected behaviour you didn't see**
- Step 6: More  useful error message, and keep internal state consistent
- Step 8: Resizing to a larger size should work, and increase both the LUKS image and the ext4 fs inside.

**Comment by martinpitt** [comment]
After step  8, when I run `homectl resize test 600M` a second time, it does ask me for the password, and does not fail. It keeps increasing the image file, but never grows the file system.

**Comment by martinpitt** [comment]
This happens even without trying to shrink to a too small size:
```
# homectl create -P --disk-size=500M test
🔐 Please enter new password for user test: ******                  
🔐 Please enter new password for user test (repeat): ******                  
Specified password does not pass quality checks (Password too weak: The password is shorter than 8 characters), proceeding anyway.
[root@donald ~]# homectl resize test 600M
🔐 Please enter password for user test: ******                  
Operation on home test failed: Access denied
```

**Comment by poettering** [comment]
is this ext4 inside? or btrfs?

My educated guess is that this is already (partially?) fixed by c9ef77ec5ff5e7e283181e9dcfb93acfb0656ae6. I figure your version doesn't include that yet?

**Comment by shalzz** [comment]
Hi,

I just hit this issue as well and found out that if you have `ext4` as the underlying filesystem then you have to enable online discards for resize to work and the loop device to have the right size by running `homectl update --luks-discard=on $USER`
so that you have this in homectl inspect: `LUKS Discard: online=yes offline=yes`

Not sure if this is the best fix, but I see the latest version of systemd defaults to using btrfs for the underlying filesystem maybe since it has better online resizing? If btrfs is indeed the better option in the context of homed with the `luks` storage option, does it make sense to migrate from `ext4` to `btrfs` for the luks device.

**Comment by martinpitt** [comment]
@poettering : Sorry, I completely missed your reply... indeed Fedora 33 still has 246.6 which doesn't have commit c9ef77e yet. I applied this locally. The weird "protocol error" from step 6 is still identical. But the main issue (step 8) works correctly now. Thanks!
