### ISSUE TITLE
Wipe RAM to defeat Cold Boot Attacks

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#17242]
**Is your feature request related to a problem? Please describe.**

* https://www.youtube.com/watch?v=JDaicPIgn9U
* https://en.wikipedia.org/wiki/Cold_boot_attack
* https://blog.f-secure.com/cold-boot-attacks/
* https://www.usenix.org/legacy/event/sec08/tech/full_papers/halderman/halderman.pdf

**Describe the solution you'd like**
Emergency RAM wipe program which wipes all RAM once run. Such as program could be run when a panic key was pressed or through udev device removal rules.

Wipe RAM at end of shutdown procedure.

**Comment by poettering** [comment]
Uh, we can't do that from userspace, we don't even et access to that. This is something that needs to be implemented in the kernel, for example with a magic sysrq thing.

I think this feature requests has merits, but it really needs to be filed against the kernel as a feature request, systemd is not the right place where we could implement that. 

Closing this here hence, I hope that makes sense?

**Comment by adrelanos** [comment]
Makes sense. Thank you for your consideration!
