### ISSUE TITLE
systemd-nspawn JIT (JRE,Mono and Box86) segfault on clear cache system call

### ISSUE THREAD

**Issue by abn0mad** [systemd/systemd#17244]
**systemd version the issue has been seen with**
 >246.6 (Debian Buster Backports) - down to 241

**Used distribution**
 > Debian Buster

**Linux kernel version used** (`uname -a`)
 > 5.4.65

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Fully functional systemd-nspawn containers

**Unexpected behaviour you saw**
 > Immediate segfaulting of software that includes a JIT (ie. Java Runtime Environment, Mono, Box86)

**Steps to reproduce the problem**
 > Run a Debian or Raspbian ARMHF container on an AARCH64 kernel and Debian host operating system

Issue was discovered when trying to run Box86 on an ARM64 / AARCH64 Debian Buster host with a systemd-nspawn ARMHF Debian Buster container. After spending quite some time [debugging the error messages](https://github.com/ptitSeb/box86/issues/216) under guidance of [Box86' creator ptitSeb](https://github.com/ptitSeb) - he requested that I test other JIT enabled software on the container after discovering that the reason behind the Box86 segfaults was the "clear cache" system call on a 32-bit systemd-nspawn container. 

It turned out that no JIT enabled software of any kind would run on this configuration (64-bit host, 32-bit guest) as the error messages in the link above demonstrate. 

I then tested the JRE as well as Mono on a 64-bit container on the same system and found no issues.

Running JIT enabled software in a 32-bit chroot on the same system is also without any issues - meaning the problem must be in systemd-nspawns handling of system calls when the host is aarch64 and the guest container is armhf.

There are a number of traces to be found in the link above as well as on the [Pyra Forum](https://www.pyra-handheld.com/boards/threads/box86-linux-userspace-x86-emulator.83577/page-20) (pages 20 through 22) which is where the debugging attempts started.

I have tested the issue on systemd 241.7 (Debian Stable) as well as systemd 246.6 (Buster-Backports) - and the results are the same.

**Comment by keszybz** [comment]
Please verify that 8e24b1d23f5fa711bfdfd38bcfef525de04cd3c1 fixes the issue.
I'll include that commit in various -stable branches.

**Comment by abn0mad** [comment]
[This (8e24b1d)](https://github.com/systemd/systemd/commit/8e24b1d23f5fa711bfdfd38bcfef525de04cd3c1) indeed fixes the issue. Fantastic work - thank you very very much :)
