### ISSUE TITLE
networkd: Support `via` in BridgeFDB

### ISSUE THREAD

**Issue by zhaofengli** [systemd/systemd#17247]
**Is your feature request related to a problem? Please describe.**
In the context of VXLAN interfaces, I cannot specify the outgoing interface for FDB entries (akin to `bridge fdb add via DEV`), which makes it hard to use IPv6 link-local addresses for VXLAN.

**Describe the solution you'd like**
Add a parameter named `Via` or `Interface` to `[BridgeFDB]` section.

**Describe alternatives you've considered**
It's possible to run the `bridge fdb add` commands manually by creating a unit that depends on the netdev, or not use link-local addresses. Neither solution fully addresses my use-case in a clean way.

**Comment by LittleFox94** [comment]
This seems to be done with af99cdf4d493c2e97bc789e22336c377dad1c6e9, as I noticed while starting to try to add it x)
