### ISSUE TITLE
regression in enumerator match_property OR semantic

### ISSUE THREAD

**Issue by HiassofT** [systemd/systemd#17259]
`udevadm trigger` manpage mentions that specifying multiple property matches results in an OR semantic.
> -p, --property-match=PROPERTY=VALUE
> ... When this option is specified more than once, then each matching result is ORed

Although not explicitly documented in the manpages the same was true for eg `udev_enumerate_add_match_property`.

systemd 245 and earlier allowed specifying the same property name multiple times with different values. 

This no longer works with systemd 246, specifying the same property name more than once results in an error (EEXIST).

**systemd version the issue has been seen with**
 >systemd 246

also current master 1b97c5cba58fdd1138e7622d7edef9a48309b0e2 shows that issue

**Used distribution**
 > LibreELEC

**Linux kernel version used** (`uname -a`)
 >5.9.0-rc7

**CPU architecture issue was seen on**
 > ARM

**Expected behaviour you didn't see**

Property matching should provide OR semantic, eg when using the following command to match both disks and partitions with systemd 245:
```
# udevadm trigger -v -n -y 'sd*' -p DEVTYPE=disk -p DEVTYPE=partition
/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/host0/target0:0:0/0:0:0:/block/sda
/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/host0/target0:0:0/0:0:0:/block/sda/sda1
```

**Unexpected behaviour you saw**
Property matching fails if the same property name is specified more than once
```
# udevadm trigger -v -n -y 'sd*' -p DEVTYPE=disk -p DEVTYPE=partition
Failed to add property match 'DEVTYPE=partition': File exists
```

**Steps to reproduce the problem**
Either use the udevadm trigger command as above (a simple `udevadm trigger -p FOO=bar -p FOO=baz` will do) or call `udev_enumerate_add_match_property` or `sd_device_enumerator_add_match_property` another time with the same property name.

**Further information**
git bisect led to commit eb1c1dc029c91750e6255c3fd844b4f4bf238fab as the first bad commit which was added via #15635

**Comment by yuwata** [comment]
@HiassofT Thank you for the detailed report. Fix is waiting in #17267.
