### ISSUE TITLE
LimitNOFILE property on the systemd-nspawn@.service unit does not affect ressource limitations of containers

### ISSUE THREAD

**Issue by mercora** [systemd/systemd#17263]
**systemd version the issue has been seen with**
> systemd 246 (246.6-1-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
> ArchLinux

**Linux kernel version used** (`uname -srvmo`)
> Linux 5.8.8-arch1-1 #1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000 x86_64 GNU/Linux

**CPU architecture used by user-space the issue was seen on**
> x86_64

**Expected behaviour you didn't see**
 > Attaching `LimitNOFILE=infinity` to the `systemd-nspawn@.service` unit would affect the applied resource limitations of the container for which it has been configured. That is, i expect the configured value for that property to be the upper bound of what it can be set to inside the container if the nspawn configuration allows for this by setting `Capability=CAP_SYS_RESOURCE` while `PrivateUsers=pick` is present too. Further i expect the root user inside the container to be able to raise the value up to the configured upper bound even if it has been set to a lower value inside the container before.

**Unexpected behaviour you saw**
 > The same apparently arbitrarily chosen limitation is applied regardless of the value that property is set to. Furthermore the limit can only be risen if it was not set lower before. That is, i can set this particular setting **up to 4096** but if set to a lower value this becomes the new upper-bound. So in this regard it behaves for root inside the container just like for any other user on the host.

**Steps to reproduce the problem**
```
# /etc/systemd/system/systemd-nspawn@share.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Container %i
Documentation=man:systemd-nspawn(1)
Wants=modprobe@tun.service modprobe@loop.service modprobe@dm-mod.service
PartOf=machines.target
Before=machines.target
After=network.target systemd-resolved.service modprobe@tun.service modprobe@loop.service modprobe@dm-mod.service
RequiresMountsFor=/var/lib/machines/%i

[Service]
# Make sure the DeviceAllow= lines below can properly resolve the 'block-loop' expression (and others)
ExecStart=systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=%i
KillMode=mixed
Type=notify
RestartForceExitStatus=133
SuccessExitStatus=133
Slice=machine.slice
Delegate=yes
TasksMax=16384
WatchdogSec=3min

# Enforce a strict device policy, similar to the one nspawn configures when it
# allocates its own scope unit. Make sure to keep these policies in sync if you
# change them!
DevicePolicy=closed
DeviceAllow=/dev/net/tun rwm
DeviceAllow=char-pts rw

# nspawn itself needs access to /dev/loop-control and /dev/loop, to implement
# the --image= option. Add these here, too.
DeviceAllow=/dev/loop-control rw
DeviceAllow=block-loop rw
DeviceAllow=block-blkext rw

# nspawn can set up LUKS encrypted loopback files, in which case it needs
# access to /dev/mapper/control and the block devices /dev/mapper/*.
DeviceAllow=/dev/mapper/control rw
DeviceAllow=block-device-mapper rw

[Install]
WantedBy=machines.target
```
```
# /etc/systemd/system/systemd-nspawn@share.service.d/ulimit.conf
[Service]
LimitNOFILE=infinity
```
```
# /etc/systemd/nspawn/share.nspawn
[Network]
MACVLAN=LAN

[Exec]
PrivateUsers=yes
Capability=CAP_SYS_RESOURCE
```
``` 
[root@share ~]# ulimit -n
1024
[root@share ~]# ulimit -n 4097
bash: ulimit: open files: cannot modify limit: Operation not permitted
[root@share ~]# ulimit -n 4096
[root@share ~]# ulimit -n 
4096
[root@share ~]# ulimit -n 4095
[root@share ~]# ulimit -n 
4095
[root@share ~]# ulimit -n 4096
bash: ulimit: open files: cannot modify limit: Operation not permitted
[root@share ~]# ulimit -n 4094
[root@share ~]# ulimit -n 
4094
```
```
[root@share ~]# cat /proc/1/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             63921                63921                processes 
Max open files            4096                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63921                63921                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us
```

**Comment by poettering** [comment]
systemd-nspawn initializes the rlimits of the payload to match those the kernel passes to host PID 1, to minimize differences between a container and a real system. The rlimits you specify hence for nspawn are applied to nspawn itself, but have no effect onto its payload. You can tweak the payload's rlimits with the --rlimit= nspawn cmdline option, or with the matching LimitXYZ= setting in the matching .nspawn file.

**Comment by mercora** [comment]
> systemd-nspawn initializes the rlimits of the payload to match those the kernel passes to host PID 1, to minimize differences between a container and a real system.

well that makes a lot of sense now.

>You can tweak the payload's rlimits with the --rlimit= nspawn cmdline option, or with the matching LimitXYZ= setting in the matching .nspawn file.

Sorry for the noise, i must have scrolled through this like 10 times and still missed it. I guess the ability to rise the limit again after it has been lowered is not expected to work either then? At least i am not concerned about this anymore.

**Comment by poettering** [comment]
> I guess the ability to rise the limit again after it has been lowered is not expected to work either then? At least i am not concerned about this anymore.

hmm? inside the container you should be able to do everything you can do outside regarding rlimits if userns is used, iirc.

**Comment by mercora** [comment]
once the limit has been set this becomes the upper-bound for everything forked afterwards regardless if i am root or not. It is somewhat annoying as it means if another user, lets say root, has a higher limit i can not switch to it. i.e. sudo won't work. I would have guessed this is likely because the kernel won't differentiate between a regular user and the mapped root user of the container.
