### ISSUE TITLE
nss-systemd appears to hang during boot-timed mounts of NFS file systems

### ISSUE THREAD

**Issue by Rudd-O** [systemd/systemd#17260]
**systemd version the issue has been seen with**

systemd-245.8-2.fc32.x86_64

**Used distribution**

Fedora 32.

**Linux kernel version used** (`uname -a`)

Linux roxanne.dragonfear 5.8.12-200.fc32.x86_64 #1 SMP Mon Sep 28 12:17:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**

x86_64

**Expected behaviour you didn't see**

Mounts are fast during boot.

**Unexpected behaviour you saw**

Mounts hang for two minutes each.

**Steps to reproduce the problem**

1. Setup a `_netdev,sec=krb5p` NFS mount on a client system.
2. Ensure the default `/etc/nsswitch.conf` has `sss files systemd` in the `group` and `passwd` config entries.
2. Ensure the default `/etc/idmapd.conf` has `Nobody-User` and `Nobody-Group` set to `nfsnobody`.
2. Reboot system.
3. Witness mount hang for ~2 minutes (eventually failing), and opening SSH logins to the machine become extremely slow.

Switching idmapd.conf to user Nobody User / Group `nobody` makes the slowness go away.

Switching nsswitch.conf to use exclusively `files` lookup for `group` and `passwd` contents makes the slowness go away.

There appears to be some sort of contention in the name<->ID resolution of users during boot while NFS file systems are mounting.  When the offending NSS component is removed from the system configuration, the problem goes away.  When the ID mapper is configured to use a system user rather than an intrinsic-to-userdbd user, the problem goes away.

Downstream report is here: https://bugzilla.redhat.com/show_bug.cgi?id=1885652

**Comment by Rudd-O** [comment]
This is a bit urgent for me and other NFS client users to get fixed, because basic system functionality depends on the NSS switch actually having `systemd` listed (several systemd units require `DynamicUser=yes`).

**Comment by poettering** [comment]
Looking at the upstream issue, it appears you have /var/shared as remote mount and then inside that an automount?

That creates a dep cycle. fix that first.

The automount is currently pulled in by "local-fs.target", i.e. early, but it can only be activated when /var/shared is fulfilled, which requires NM online stuff, which is late stuff. So you have an ordering cycle there.

And for any idmap things, please ping the nfs people first, I doubt systemd is involved. We only synthesize the "nobody" user if it is missing in /etc/passwd  but it typically is not.

**Comment by Rudd-O** [comment]
> Looking at the upstream issue, it appears you have /var/shared as remote mount and then inside that an automount?

Nope.  The mount table looks like this:

```
penny.dragonfear:/srv/shared /var/shared nfs4 _netdev,sec=krb5p 0 0
penny.dragonfear:/srv/shared/Seedbox		/var/shared/Seedbox	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Incoming		/var/shared/Incoming	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment		/var/shared/Entertainment	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Jokes		/var/shared/Entertainment/Jokes	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Movies		/var/shared/Entertainment/Movies	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/TV		/var/shared/Entertainment/TV	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Music		/var/shared/Entertainment/Music	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Miro		/var/shared/Entertainment/Miro	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Albums		/var/shared/Albums	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Knowledge		/var/shared/Knowledge	nfs4	_netdev,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Software		/var/shared/Software	nfs4	_netdev,sec=krb5p	0 0
```

It used to look like this:

```
penny.dragonfear:/srv/shared /var/shared nfs4 _netdev,x-systemd.automount,sec=krb5p 0 0
penny.dragonfear:/srv/shared/Seedbox		/var/shared/Seedbox	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Incoming		/var/shared/Incoming	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment		/var/shared/Entertainment	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Jokes		/var/shared/Entertainment/Jokes	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Movies		/var/shared/Entertainment/Movies	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/TV		/var/shared/Entertainment/TV	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Music		/var/shared/Entertainment/Music	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Entertainment/Miro		/var/shared/Entertainment/Miro	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Albums		/var/shared/Albums	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Knowledge		/var/shared/Knowledge	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
penny.dragonfear:/srv/shared/Software		/var/shared/Software	nfs4	_netdev,x-systemd.automount,sec=krb5p	0 0
```

In either case the problem exists.  In the latter case (what used to be the former config) the NFS mount just hangs the system later when the file systems are attempted to be accessed.  In the former case it just hangs during boot (~2 minutes per file system, roughly, while booting).

**Comment by Rudd-O** [comment]
@poettering would you mind routing me to the NFS folks?

I honestly do think this is a systemd-related issue, since `nss_systemd` causes the hang when it's involved and the hang is not there when it's not involved.

**Comment by poettering** [comment]
Please provide a gdb backtrace of the hanging process, so that we can see what is blocking there.

**Comment by Rudd-O** [comment]
The machine this was happening on is currently down.  Since updating to Fedora 33 that has not been an issue.
