### ISSUE TITLE
extend discoverable partition spec with LVM

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#1727]
The specification for auto-discovering partitions is an excellent idea:
http://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/

Unfortunately it's incompatible with LVM. Would be great to extend it so root, swap and home partitions which are part of LVM setup could be automatically discovered as well.

This is especially handy with the projects like https://github.com/tasleson/lvm-dubstep which allows to interface to LVM via dbus which will be available to systemd early at boot thanks to kdbus.

**Comment by poettering** [comment]
LVM is nothing we support in systemd directly, it's an add-on package, and as such there's no point in automatically discovering anything on it automatically. If the LVM folks want to do that, they can do that, but that has no place in the core OS.

Please talk to the LVM folks, they can do that in an LVM-specific spec. There's no need to define this in any generic spec.
