### ISSUE TITLE
Add missing desktop entry keys to XDG autostart generator

### ISSUE THREAD

**Issue by rydalt** [systemd/systemd#17276]
**Is your feature request related to a problem? Please describe.**
Currently whenever I login I get a spew of log spam related to .desktop files and unknown keys from auto-start applications. Notably Path, MimeType, StartupWMClass, and URL are considered unknown keys, however each are standard keys per the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.0.html#recognized-keys) and are not listed in [`xdg-autostart-service.c`](https://github.com/systemd/systemd/blob/5177cb0a9add4ae568cff6e6f7c2b3c77760c343/src/xdg-autostart-generator/xdg-autostart-service.c#L321) with the rest of the standard keys.

Here's an anonymized example from my logs:
```
MON DD HH:MM:SS hostname systemd[pid]: $HOME/.config/autostart/org.qbittorrent.qBittorrent.desktop:7: Unknown key name 'MimeType' in section 'Desktop Entry', ignoring.
MON DD HH:MM:SS hostname systemd[pid]: $HOME/.config/autostart/org.qbittorrent.qBittorrent.desktop:12: Unknown key name 'StartupWMClass' in section 'Desktop Entry', ignoring
MON DD HH:MM:SS hostname systemd[pid]: $HOME/.config/autostart/discord.desktop:10: Unknown key name 'Path' in section 'Desktop Entry', ignoring.
```

I don't have an example of the URL key being logged as unknown, but it appears to be missing in the code related to auto starting applications.

**Describe the solution you'd like**
Ideally each missing key would be added and would not be logged every time I login as a direct result.

**Describe alternatives you've considered**
I suppose they could just not be added and I can live with 5-8 lines of unnecessary log spam.

**Comment by mbiebl** [comment]
Maybe those log messages could be downgraded to debug (at least some of them).
Slightly related is this downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968116

**Comment by sysrabbit** [comment]
Looking at that, I agree that most of the messages should be downgraded from info to debug, they don't seem to be of much use except to someone debugging a desktop entry that's not starting correctly.

I still feel the four desktop entry keys I mentioned should probably be added to the array of desktop entries I mentioned earlier as they are part of the official desktop entry standard and not really unknown.

**Comment by poettering** [comment]
Yeah, we should downgade the messages at least for standard defined, but ignored keys.

/cc @benzea
