### ISSUE TITLE
$SYSTEMD_RELAX_ESP_CHECKS env var should also relax backing block device checks

### ISSUE THREAD

**Issue by andrejpodzimek** [systemd/systemd#17298]
This report is based on [this discussion](https://github.com/systemd/systemd/issues/12468#issuecomment-698692508).

**systemd version the issue has been seen with**
 > `246.6-1`

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)
 > `5.8.14-arch1-1-zen2`

**CPU architecture issue was seen on**
 > AMD Ryzen 9 3950X

**Expected behaviour you didn't see**
 > Partition type checks should be bypassed and bootloader files updated (based on environment variables documented [here](https://systemd.io/ENVIRONMENT/)).

**Unexpected behaviour you saw**
 > ```
 > Failed to probe partition scheme of "/dev/block/9:127": Input/output error
 > ```
 > [Here's a full `strace -f`](https://github.com/systemd/systemd/files/5358160/strace.txt) from `bootctl update`.

**Steps to reproduce the problem**
 > 0. Configure `/boot` as a legacy (metadata-free) RAID 1 device (over 2 USB flashdisks in this case):
 >     ```ini
 >     [Unit]
 >     Description=UEFI partition replication RAID
 >     Before=boot-efi.mount
 >
 >     [Service]
 >     Type=oneshot
 >     RemainAfterExit=yes
 >     ExecStart=mdadm --build efi --level=raid1 --raid-devices=2 /dev/disk/by-id/usb-Samsung_Flash_Drive_0374718070015469-0:0-part1 /dev/disk/by-id/usb-Samsung_Flash_Drive_0362920010004877-0:0-part1
 >     ExecStop=mdadm --stop /dev/md/efi
 >
 >     [Install]
 >     RequiredBy=dev-md-efi.device
 >     RequiredBy=boot-efi.mount
 >     ```
 > 1. Now with this^^^, try to install and/or update the bootloader:
 >     ```shell
 >     export SYSTEMD_RELAX_ESP_CHECKS=1
 >     export SYSTEMD_ESP_PATH=/boot
 >     bootctl update  # Bam. This fails.
 >     ```
 > I tried to set `--path`, `--esp-path` and `--boot-path`, but it had no effect on the outcome.

**Comment by poettering** [comment]
SYSTEMD_RELAX_ESP_CHECKS currently only relaxes checks on the used fs, and whether we run in a container mgr. It does not relax checks on used backing device

**Comment by andrejpodzimek** [comment]
A quick workaround could be a low-level tool that just copies the bootloader files, but doesn't check anything. Actually, if all the necessary files are already installed with the package somewhere outside `/boot`, then it would be just a few `cp` commands.

The only use-case that matters here is to have the bootloader automatically updated after systemd updates (which is not strictly necessary, but definitely advisable, I guess).

**Comment by aep** [comment]
> The only use-case that matters here is to have the bootloader automatically updated after systemd updates (which is not strictly necessary, but definitely advisable, I guess).

i usually just rsync /boot. Mirroring the ESP should be fine, but i'd much prefer if bootctl update would just support multiple ESP.

**Comment by gregory-lee-bartholomew** [comment]
> i usually just rsync /boot. Mirroring the ESP should be fine, but i'd much prefer if bootctl update would just support multiple ESP.

I'd like to second the above request. But if people want to go the rsync route, I have some custom scripts <a href="https://github.com/gregory-lee-bartholomew/bootsync">here</a> that automate the process that I'd be willing to work with someone on integrating into systemd.

**Comment by MartinX3** [comment]
In my usecase the ESP partition isn't mirrored.
But my xbootldr partition is mirrored by mdadm raid.
Of course with metadata 1.0 to put them at the end of the disk.

It would be useful if it works since the ESP could get modified by the UEFI, but the xbootldr won't.
So mirroring the xbootldr partition should be secure.

**Comment by poettering** [comment]
XBOOTLDR can't be mirrored either. sd-boot will write to it for doing boot counts.

Seriously forget about RAID for ESP or XBOOTLDR...

**Comment by poettering** [comment]
This has long been fixed, $SYSTEMD_RELAX_ESP_CHECKS nowadays also controls block device checks.

Closing
