### ISSUE TITLE
no hibernate functions after adding swapfile with existing swap partition

### ISSUE THREAD

**Issue by howdev** [systemd/systemd#17299]
systemd 245 

**Used distribution**
Mint 20

**Linux kernel version used**
 5.4.0-48

**CPU architecture issue was seen on**
64bit

**Expected behaviour you didn't see**
hibernate function shows in shutdown menu even when swapfile is added with existing swap partition

**Unexpected behaviour you saw**
 No hibernate function in shutdown menu when swapfile is added by swapon in addition to existing swap partition. When swapoff the swapfile, hibernate appears again in the shutdown menu.
This wasn't a problem when I was using Mint 19.3 with same swapfile and same swap partition. Mint 19.3 uses systemd 237

**Steps to reproduce the problem**
1. With existing swap partition
2. Enable hibernate which is disable by default using com.ubuntu.enable-hibernate.pkla in /etc/polkit-1/localauthority/50-local.d, hibernate shows in shutdown menu
3. create swapfile, swapon swapfile.
4. hibernate disappeared in shutdown menu

**Comment by poettering** [comment]
Please report what /proc/swaps contains. Also, what does "busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanHibernate" report?

**Comment by howdev** [comment]
@poettering strange. I followed your instructions. proc/swap reports my swap partition,  busctl reports yes canhibernate with swapfile on and off, also restarted systemctl to make sure. And hibernate shows in the menu. I don't know what happened

**Comment by poettering** [comment]
Ok. So i guess we can close this here then? Maybe you ui iust didnt refresh the bus property before showing its menu...

**Comment by howdev** [comment]
@poettering ok can close. thanks.
