### ISSUE TITLE
systemd-udevd:auto modify a new bridge  mac

### ISSUE THREAD

**Issue by zhangzhibo** [systemd/systemd#17303]
**systemd version the issue has been seen with**
 > # /usr/lib/systemd/systemd-udevd --version
v245.6-2.fc32

**Used distribution**
 ># cat /etc/redhat-release
Fedora release 32 (Thirty Two)

**Linux kernel version used** (`uname -a`)
 ># uname -a
Linux 5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 >all

**Expected behaviour you didn't see**
 >the command "brctl addbr br4;" will not change the mac of br4
**Unexpected behaviour you saw**
 > #brctl addbr br4
systemd-udevd 2177291 [003] 1898708.404165: probe:br_set_mac_address: (ffffffffc145b8d0)
        ffffffffc145b8d1 br_set_mac_address+0x1 (/lib/modules/5.7.9-100.fc31.x86_64/kernel/net/bridge/bridge.ko.xz)
        ffffffff928b038b dev_set_mac_address+0x9b ([kernel.kallsyms])
        ffffffff928c88af do_setlink+0x1cf ([kernel.kallsyms])
        ffffffff928c9555 rtnl_setlink+0xe5 ([kernel.kallsyms])
        ffffffff928c75bc rtnetlink_rcv_msg+0x28c ([kernel.kallsyms])
        ffffffff9291fd09 netlink_rcv_skb+0x49 ([kernel.kallsyms])
        ffffffff9291f4fd netlink_unicast+0x16d ([kernel.kallsyms])
        ffffffff9291f7d3 netlink_sendmsg+0x233 ([kernel.kallsyms])
        ffffffff9289157e sock_sendmsg+0x5e ([kernel.kallsyms])
        ffffffff928934fe __sys_sendto+0xee ([kernel.kallsyms])
        ffffffff92893595 __x64_sys_sendto+0x25 ([kernel.kallsyms])
        ffffffff920052eb do_syscall_64+0x5b ([kernel.kallsyms])
        ffffffff92c0008c entry_SYSCALL_64_after_hwframe+0x44 ([kernel.kallsyms])
            7f60e4073cda __libc_sendto+0x1a (/usr/lib64/libc-2.30.so)

**Steps to reproduce the problem**
 > #brctl addbr br4;ifconfig br4;brctl delbr br4;brctl addbr br4;ifconfig br4;
you will see the macs of br4 are same.

**Comment by yuwata** [comment]
Hmm? I cannot reproduce this issue.
```
$ sudo brctl addbr br4
$ sudo ip link show dev br4
6: br4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 16:d1:b2:ae:05:f4 brd ff:ff:ff:ff:ff:ff
$ sudo ip link del br4
$ sudo brctl addbr br4
$ sudo ip link show dev br4
7: br4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 16:d1:b2:ae:05:f4 brd ff:ff:ff:ff:ff:ff
$ sudo ip link del br4
```

Could you show the result of `udevadm test /sys/class/net/br4`?
Also, could you show relevant parts of debugging logs of systemd-udevd?

**Comment by zhangzhibo** [comment]
1、The result of udevadm test /sys/class/net/br4 :
[root@localhost ~]# udevadm test /sys/class/net/br4/
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
Reading rules file: /usr/lib/udev/rules.d/10-dm.rules
Reading rules file: /usr/lib/udev/rules.d/13-dm-disk.rules
Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
Reading rules file: /usr/lib/udev/rules.d/60-autosuspend-chromiumos.rules
Reading rules file: /usr/lib/udev/rules.d/60-block.rules
Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
Reading rules file: /usr/lib/udev/rules.d/60-fido-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /usr/lib/udev/rules.d/60-rfkill.rules
Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
Reading rules file: /usr/lib/udev/rules.d/61-autosuspend-manual.rules
Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /usr/lib/udev/rules.d/90-vconsole.rules
Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
Reading rules file: /usr/lib/udev/rules.d/96-e2scrub.rules
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
DEVPATH=/devices/virtual/net/br4
DEVTYPE=bridge
INTERFACE=br4
IFINDEX=13
ACTION=add
SUBSYSTEM=net
ID_NET_DRIVER=bridge
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
TAGS=:systemd:
SYSTEMD_ALIAS=/sys/subsystem/net/devices/br4
USEC_INITIALIZED=357733474031
run: '/usr/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/br4 --prefix=/net/ipv4/neigh/br4 --prefix=/net/ipv6/conf/br4 --prefix=/net/ipv6/neigh/br4'
Unload module index
Unloaded link configuration context.
[root@localhost ~]#
2、You have already reproduced this issue successfully:
 The mac of br4 is "16:d1:b2:ae:05:f4",  is static and is not random!

**Comment by zhangzhibo** [comment]
1、The result of udevadm test /sys/class/net/br4 :
[root@localhost ~]# udevadm test /sys/class/net/br4/
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
Reading rules file: /usr/lib/udev/rules.d/10-dm.rules
Reading rules file: /usr/lib/udev/rules.d/13-dm-disk.rules
Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
Reading rules file: /usr/lib/udev/rules.d/60-autosuspend-chromiumos.rules
Reading rules file: /usr/lib/udev/rules.d/60-block.rules
Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
Reading rules file: /usr/lib/udev/rules.d/60-fido-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /usr/lib/udev/rules.d/60-rfkill.rules
Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
Reading rules file: /usr/lib/udev/rules.d/61-autosuspend-manual.rules
Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /usr/lib/udev/rules.d/90-vconsole.rules
Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
Reading rules file: /usr/lib/udev/rules.d/96-e2scrub.rules
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
DEVPATH=/devices/virtual/net/br4
DEVTYPE=bridge
INTERFACE=br4
IFINDEX=13
ACTION=add
SUBSYSTEM=net
ID_NET_DRIVER=bridge
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
TAGS=:systemd:
SYSTEMD_ALIAS=/sys/subsystem/net/devices/br4
USEC_INITIALIZED=357733474031
run: '/usr/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/br4 --prefix=/net/ipv4/neigh/br4 --prefix=/net/ipv6/conf/br4 --prefix=/net/ipv6/neigh/br4'
Unload module index
Unloaded link configuration context.
[root@localhost ~]#
2、You have already reproduced this issue successfully:
The mac of br4 is "16:d1:b2:ae:05:f4", is static and is not random! It is changed from random to static by systemd-udev.

**Comment by zhangzhibo** [comment]
1、The result of udevadm test /sys/class/net/br4 :
[root@localhost ~]# udevadm test /sys/class/net/br4/
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Load module index
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
Reading rules file: /usr/lib/udev/rules.d/10-dm.rules
Reading rules file: /usr/lib/udev/rules.d/13-dm-disk.rules
Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
Reading rules file: /usr/lib/udev/rules.d/60-autosuspend-chromiumos.rules
Reading rules file: /usr/lib/udev/rules.d/60-block.rules
Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
Reading rules file: /usr/lib/udev/rules.d/60-fido-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /usr/lib/udev/rules.d/60-rfkill.rules
Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
Reading rules file: /usr/lib/udev/rules.d/61-autosuspend-manual.rules
Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /usr/lib/udev/rules.d/90-vconsole.rules
Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
Reading rules file: /usr/lib/udev/rules.d/96-e2scrub.rules
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
DEVPATH=/devices/virtual/net/br4
DEVTYPE=bridge
INTERFACE=br4
IFINDEX=13
ACTION=add
SUBSYSTEM=net
ID_NET_DRIVER=bridge
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
TAGS=:systemd:
SYSTEMD_ALIAS=/sys/subsystem/net/devices/br4
USEC_INITIALIZED=357733474031
run: '/usr/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/br4 --prefix=/net/ipv4/neigh/br4 --prefix=/net/ipv6/conf/br4 --prefix=/net/ipv6/neigh/br4'
Unload module index
Unloaded link configuration context.
[root@localhost ~]#
2、You have already reproduced this issue successfully:
The mac of br4 is "16:d1:b2:ae:05:f4", is static and is not random! It is changed from random to static by systemd-udevd to call br_set_mac_address.

**Comment by yuwata** [comment]
> You have already reproduced this issue successfully

Oh, sorry, I misunderstand your first comment.

How about to create the following .link file?
```
# 90-bridge.link
[Match]
Type=bridge

[Link]
MACAddressPolicy=random
```

**Comment by zhangzhibo** [comment]
Thank you!
