### ISSUE TITLE
systemd-networkd: Can't enable WakeOnLan with systemd.link

### ISSUE THREAD

**Issue by mikkeloscar** [systemd/systemd#1730]
I'm trying to enable WakeOnLan using systemd-networkd with a `.link` file. This is my configuration which should be enough as far as I understand from the docs.

```
$ cat /etc/systemd/network/wired.network 
[Match]
Name=en*

[Network]
DHCP=ipv4
$ cat /etc/systemd/network/wired.link 
[Link]
WakeOnLan=magic
```

However WakeOnLan doesn't get enabled and there are no errors/information regarding this in the journal.

I can enable WakeOnLan with no problem using:

```
# ethtool -s enp9s0 wol g
```

systemd-version: 227
OS: ArchLinux

**Comment by mikkeloscar** [comment]
I had a dig in the code (first time looking at systemd source mind you) and I think the issue is related to the config logic.

First the link files are loaded here and added to a list: https://github.com/systemd/systemd/blob/master/src/udev/net/link-config.c#L174-L188

`/usr/lib/systemd/network/99-default.link` will be added to the front of the list since it is loaded and prepended last.

Later when the link config for a specific device is looked up it will always find the config defined in `/usr/lib/systemd/network/99-default.link` because it matches all devices and is the first in the list. Thus whatever configuration defined in `/etc/systemd/network/*.link` will never get used.
https://github.com/systemd/systemd/blob/master/src/udev/net/link-config.c#L253-L295

So unless I'm misunderstanding how this is supposed to work, then the solution must be to merge the configs of all link-files which match a specific device and then return that complete link config.

I'm not completely sure how it should be done, but I guess it should be done as part of the lookup in: https://github.com/systemd/systemd/blob/master/src/udev/net/link-config.c#L245

**Comment by poettering** [comment]
Oh, I see your issue now:

networkd/udev only apply the first matching file, where "first" is the lexicographically first one. Which means if you have the default file "99-default.link" which applies to all links and one called "wired.link" then "99-default.link" will always win.

You are expected to prefix your .link file name with a number to indicate the order of preference you want your stuff applied. For example "50-wired.link" would be a better name.

See docs about this.

**Comment by mikkeloscar** [comment]
Ok, then I completely misunderstood how it works. After rereading systemd.link I see that it is in fact described like you describe it.

Thanks a lot for your help!

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
So then what exactly was your solution to your problem?
