### ISSUE TITLE
systemd --user runs in init_t SELinux context

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#1731]
Hi,

ATM, systemd --user process runs as init_t which can be a problem as all the processes started by it will be mislabelled.

systemd --user process should run in the user domain of the user (or one derivated from the user domain)

Example:

```
$ systemd-run --user sleep 100 ; ps uaxZ|grep sleep
system_u:system_r:initrc_t:s0   bigon     5634  0.0  0.0   5800   680 ?        Ss   18:35   0:00 /bin/sleep 100
```

Edit: This is the case with both the Fedora policy and the refpolicy

**Comment by poettering** [comment]
Already fixed via #1338.
