### ISSUE TITLE
Running systemd inside unprivileged docker container.

### ISSUE THREAD

**Issue by rightblank** [systemd/systemd#17320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Systemd is really cool and amazing, but for now it can only start inside a privileged container which might have security risks,   could this great community make the systemd even more cool by running it inside a unprivileged container? 

**Describe alternatives you've considered**

**Comment by poettering** [comment]
systemd should just work in any container mgr that implements this:

https://systemd.io/CONTAINER_INTERFACE

It works fine with and without userns out of the box, this requires not changes.
