### ISSUE TITLE
networkd: DHCP on InfiniBand(IPoIB) interface does not work

### ISSUE THREAD

**Issue by BtbN** [systemd/systemd#17322]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)
 > 5.4.70

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**

I was expecting networkd with DHCP=yes on an IB interface to successfully request an IP from a DHCP Server.
The DHCP server (Mellanox-Patched ISC DHCPd) is working fine for PXE boot and via dhclient.

**Unexpected behaviour you saw**

The DHCP server never sees any kind of request from the machine running the networkd DHCP client.
Additionally, when enabling debug logging in networkd, I can see it starting the "DHCP CLIENT", but after that it only ever logs about IPv6 RA. No sign of it actually sending any DHCP request(s).

**Steps to reproduce the problem**

Run networkd on any machine with an IPoIB interface, with the most basic DHCP=yes networkd config for the respective interface.
The used IB card is a ConnectX-4 VPI running with the in-kernel mlx5 driver with IPoIB enhancements enabled in my case.

**Comment by ssahani** [comment]
We don't have this interface. Can you please capture packets on that interface with networkd debug logs.

**Comment by BtbN** [comment]
tcpdump does not show any (IPv4) traffic on the interface on port 67 or 68 whatsoever. (Or on any port really)
Log of networkd: https://gist.github.com/BtbN/4cfbab09113c95aba8fcbc9f29ad4bb8

**Comment by ssahani** [comment]
Thank for the logs
```
Oct 12 21:24:10 node01 systemd-networkd[5436]: ibp1s0: Acquiring DHCPv4 lease
Oct 12 21:24:10 node01 systemd-networkd[5436]: DHCP CLIENT (0x983477a3): STARTED on ifindex 4
```

right no packets (not even discoverer)  can be seen .  Not sure why packets are not passing throw.  Does even any ipv4 packets passed via this interface

**Comment by BtbN** [comment]
No, if I run an unconditional tcpdump alongside a networkd restart, all it shows are IPv6 RA things. Nothing IPv4.

**Comment by ssahani** [comment]
What I want to say is, we need to figure why no IPv4 packets not going via this interface. If no IPv4 packets throw then we can't talk to server and no IPv4 DHCP address. I think this is not about networkd rather why IPv4 traffic not going throw.

**Comment by ssahani** [comment]
Well I am asking about just any IPv4 traffic. Can you capture any ?

**Comment by BtbN** [comment]
If I manually assign an IPv4 address to the interface it works fine and the traffic does show up in tcpdump.
However networkds DHCP client does not send any IPv4 traffic on the interface at all, and also does not log about trying to.
Not sure what to do about that.
The .network file is quite literally just

```
[Match]
Name=ibp1s0

[Network]
DHCP=ipv4
```

Here's a tcpdump capture of dhclient (With above Mellanox patch applied) grabbing an address:

<details>

```
23:52:51.975378 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request, length 300, htype 32, hlen 8, xid 0xdd1a8918, Flags [Broadcast]
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Discover
            Parameter-Request Option 55, length 8:
              Subnet-Mask, BR, Time-Zone, Default-Gateway
              Domain-Name, Domain-Name-Server, Hostname, NTP
            Client-ID Option 61, length 9: hardware-type 32, e0:07:1b:ff:ff:79:d0:84
23:52:51.975850 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 349)
    10.110.10.251.67 > 255.255.255.255.68: BOOTP/DHCP, Reply, length 321, htype 32, hlen 8, xid 0xdd1a8918, Flags [Broadcast]
          Your-IP 10.110.10.1
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Offer
            Server-ID Option 54, length 4: 10.110.10.251
            Lease-Time Option 51, length 4: 3600
            Subnet-Mask Option 1, length 4: 255.255.255.0
            BR Option 28, length 4: 10.110.10.255
            Default-Gateway Option 3, length 4: 10.110.10.250
            Domain-Name Option 15, length 27: "cluster.klima.uni-bremen.de"
            Domain-Name-Server Option 6, length 8: 10.110.10.250,10.110.10.249
            Hostname Option 12, length 6: "node01"
23:52:51.975930 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request, length 300, htype 32, hlen 8, xid 0xdd1a8918, Flags [Broadcast]
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Request
            Server-ID Option 54, length 4: 10.110.10.251
            Requested-IP Option 50, length 4: 10.110.10.1
            Parameter-Request Option 55, length 8:
              Subnet-Mask, BR, Time-Zone, Default-Gateway
              Domain-Name, Domain-Name-Server, Hostname, NTP
            Client-ID Option 61, length 9: hardware-type 32, e0:07:1b:ff:ff:79:d0:84
23:52:51.976091 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 349)
    10.110.10.251.67 > 255.255.255.255.68: BOOTP/DHCP, Reply, length 321, htype 32, hlen 8, xid 0xdd1a8918, Flags [Broadcast]
          Your-IP 10.110.10.1
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: ACK
            Server-ID Option 54, length 4: 10.110.10.251
            Lease-Time Option 51, length 4: 3600
            Subnet-Mask Option 1, length 4: 255.255.255.0
            BR Option 28, length 4: 10.110.10.255
            Default-Gateway Option 3, length 4: 10.110.10.250
            Domain-Name Option 15, length 27: "cluster.klima.uni-bremen.de"
            Domain-Name-Server Option 6, length 8: 10.110.10.250,10.110.10.249
            Hostname Option 12, length 6: "node01"

```

</details>

**Comment by mercora** [comment]
i don't know anything about InfiniBand, but does broadcasting actually work? if not i think it wont work using a standard DHCP client. i.e. the client would need to know where to send packets to instead of a broadcast address...

**Comment by BtbN** [comment]
It works, yes.
See what needs changed in dhclient for it to work: https://src.fedoraproject.org/rpms/dhcp/blob/master/f/0014-IPoIB-support-660681.patch

The primary two change to the client are `ip->client->config->bootp_broadcast_always = 1;` and enforcing a client-id to be set, for the lack of a MAC-Address on those broadcasts.

Both of these things are already present in networkd, so there must be some other issue somewhere, that prevents networkd from operating properly.

**Comment by BtbN** [comment]
I traced this down a bit more by adding debug prints into the code.
In sd-dhcp-client.c, it calls client_send_discover, which then calls dhcp_client_send_raw.
dhcp_client_send_raw returns -22, which means EINVAL.
Which originates from sendto() in dhcp_network_send_raw_socket() in dhcp-network.c.

Did not get to investigate why exactly it fails to send.
