### ISSUE TITLE
systemd-cgtop --raw --cpu=time should show time in microseconds to ease consumption by scripts

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#17325]
**Is your feature request related to a problem? Please describe.**
I am using `systemd-cgtop --raw` because it's supposed to be easy to parse using tools like `awk` to feed cgroup metrics to Prometheus using https://github.com/ncabatoff/script-exporter. However, because the time format that is used for showing `CPU Time` is in human-readable format that has an arbitrary amount of spaces even _if_ `--raw` is applied (e.g. `15h 27min 45.420584s`) it's hard to programatically parse the output of `systemd-cgtop --raw`

**Describe the solution you'd like**
`--raw` also causes the CPU Time column to show raw numbers just like the bytes columns. I suggest the amount of microseconds.

**Describe alternatives you've considered**
I tried parsing the result using `systemd-analyze timespan` but it was hard to do because the CPU Time format's amount of spaces depends on whether `hours` `minutes` or `seconds` are needed to display it.   e.g. you have all these different formats in one that I need to handle
```
14h 34min 25.390000s
1min 35.382358s
1.274791s
1.798ms
381us
```
And it's hard to figure out e.g. in awk how many spaces you should consume for parsing the time apriori. It's not clear where the column boundaries are of the fields.

Another alternative would be to write a little C program `systemd-cg-metrics` that shows the `cgtop` values in prometheus metrics format (https://prometheus.io/docs/instrumenting/writing_exporters/). I don't know if this is a feature that systemd would consider merging though.    For a simple prototype it could just print to `stdout` and use https://github.com/ncabatoff/script-exporter; but given we already depend on `libmicrohttpd` we could perhaps expose a `/metrics` HTTP endpoint serving prometheus metrics directly by making a little `systemd-prometheus-metrics` daemon

**Comment by poettering** [comment]
makes sense. Happy to merge a patch that tweaks this
