### ISSUE TITLE
Can't list more than ~3k coredumps?

### ISSUE THREAD

**Issue by davispuh** [systemd/systemd#1733]
It seems coredumpctl doesn't show new coredumps for me anymore.

```
$ coredumpctl -1
TIME                            PID   UID   GID SIG PRESENT EXE
C  2015-10-29 19:03:47 EET    2204  1000  1000   6 * /mnt/Android/prebuilts/misc/linux-x86/flex/flex-2.5.39
```

but I've many more recent coredumps

```
$ ls -lat /var/lib/systemd/coredump
total 901392
drwxr-xr-x  1 root root    37046 okt 31 00:34 ./
-rw-r-----+ 1 root root  5744668 okt 31 00:34 core.kded5.1000.eae52be87aee4548aa2b961409342351.10574.1446244455000000.lz4
-rw-r-----+ 1 root root  3790812 okt 31 00:34 core.akonadi_notes_a.1000.eae52be87aee4548aa2b961409342351.11855.1446244455000000.lz4
-rw-r-----+ 1 root root  3812293 okt 31 00:34 core.akonadi_sendlat.1000.eae52be87aee4548aa2b961409342351.11881.1446244455000000.lz4
-rw-r-----+ 1 root root  1182355 okt 31 00:34 core.klauncher.1000.eae52be87aee4548aa2b961409342351.12660.1446244456000000.lz4
[...]
```

```
$ coredumpctl list --no-pager | wc -l
2949
```

also I'm trying to preserve all logs/coredumps and never delete them, but I'm not sure if I've gotten settings right

`/etc/systemd/coredump.conf`

```
[Coredump]
Storage=external
#Compress=yes
ProcessSizeMax=4G
ExternalSizeMax=4G
JournalSizeMax=100M
MaxUse=0
KeepFree=0
```

`/etc/systemd/journald.conf`

```
[Journal]
Storage=persistent
SystemMaxUse=0
SystemKeepFree=0
SystemMaxFileSize=0
SystemMaxFiles=0
RuntimeMaxUse=0
RuntimeKeepFree=0
MaxRetentionSec=0
MaxFileSec=0
```

**Comment by davispuh** [comment]
I just compiled systemd from git master, rebooted and now I see latest ones, but there's less entries...

```
$ coredumpctl list --no-pager | wc -l
2020
```

**Comment by poettering** [comment]
well, coredumpctl is basically just a frontend for the journal, and follows reference to coredump files from the journal. Hence: only what is in the journal it will find.

You should see the same coredumps if you use:

```
journalctl MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1
```

Do you see the same coredumps there?

Also note that access to the journal file matters, i.e. if you run this as unpriviliged user membership of the `systemd-journal` group matters... Or are you running this as root?

**Comment by davispuh** [comment]
They are in journal, there are entries like

```
systemd-coredump[20723]: Process 19444 (X) of user 1000 dumped core
```

and those files are on filesystem in that folder only coredump didn't showed them.

Yeah with that I do see them now, but now I see all dumps anyway because when I rebuilt and reinstalled systemd it overwrote my previous config and so it deleted old logs. Now that I've less I can't reproduce it anymore. I'll see when I'll reach 3k coredumps again.

I'm part of `wheel` group and tried with `sudo` but there wasn't any difference. I think I did checked with root too and it was same.

**Comment by poettering** [comment]
I am sorry, but I cannot parse what you wrote above:

> and those files are on filesystem in that folder only coredump didn't showed them.

What's that supposed to mean? Can you elaborate?

Note that coredumpctl shows you all coredumps listed in the journal, but allows you to run gdb only on those where the actual binary coredump is still around. However, journal files and coredump files are subject to different clean-up schemes. Hence it might very well happen that you have binary coredump files around where the journal data for is already cleared. In that case "coredumpctl" won't show anything about htis.

**Comment by davispuh** [comment]
I meant, I had coredumps in `/var/lib/systemd/coredump` but they didn't showed up with coredumpctl. Those coredumps are very new and coredumpctl showed older ones but not these new ones. Also they clearly are in journal because now they show up with coredumpctl, but didn't before.

**Comment by davispuh** [comment]
Seems it's something related to my settings in `journald.conf`, now again I don't see latest dumps with `coredumpctl` but I do see them with `journalctl MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1`

**Comment by poettering** [comment]
hmm, coredumpctl showing less data than journalctl is weird indeed... Maybe you are running them with different privileges? i.e. one as root and the other as normal user?

If you run coredumpctl with SYSTEMD_LOG_LEVEL=debug set it will output the precise matches it applies to the journal to look for the coredumps. Could you try that, and use those matches on journalctl? It should output the very same data then (well, as long as they run with the same privs).

**Comment by davispuh** [comment]
> Maybe you are running them with different privileges? i.e. one as root and the other as normal user?

nope, both times with same user and tried running as root too, but same result.

Anyway I found out what's wrong, by default open file descriptor count (ulimit -n) on Arch Linux is only 1024 which isn't enough. After increasing this limit I see all coredumps.

```
$ coredumpctl list --no-pager | wc -l
19
$ ulimit -n 10000
$ coredumpctl list --no-pager | wc -l
630
```

if I set `SYSTEMD_LOG_LEVEL=debug` can see that in log

```
File /var/log/journal/873a5f55f2aa4b33b2568baca40e6a91/user-1000@4fe9906248af45e09f1cca2e3033e527-000000000006795d-0005344f52e64c70.journal added.
Failed to open journal file /var/log/journal/873a5f55f2aa4b33b2568baca40e6a91/user-1002@c671a2c7d1d940df8a030d83a58cd166-0000000000067dc1-00053450039087d9.journal: Too many open files
Failed to open journal file /var/log/journal/873a5f55f2aa4b33b2568baca40e6a91/user-1001@f0ac4c406b1141c1a9e01b3733e58bdf-0000000000065b24-00053439ed3b2f49.journal: Too many open files
```

I think this is bug, does it really needs to keep them all open...

**Comment by keszybz** [comment]
There's a couple of issues here.

First, not coredumpctl specific, is whether we need to keep so many files open. There are cases where we *need* to keep a large number of journals open (e.g. we have 10k users, and each one has their own journal file, and we are merging them). But it's much more common to just have many archived journals. They are consecutive in time, and I really don't think we need to keep them all open. This seems to be a bug / inefficiency in sd-journal.

Second, `coredumpctl` does not seem to report this issue properly. `journalctl` does better:
```bash
$ ulimit -n 10
$ journalctl MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1
An error was encountered while opening journal file or directory /var/log/journal/9b47c1a5b339412887a197b7654673a7/user-1000@b7f953f7c4d6460fae41d3ff2e4c7537-000000000003d4ee-000540af21f59097.journal, ignoring file: Too many open files
-- No entries --
$ coredumpctl 
No coredumps found.
```

At least making `coredumpctl` report the error would make it easy to diagnose the issue.
