### ISSUE TITLE
Need support : VxLAN creation with systemd-networkd

### ISSUE THREAD

**Issue by christian-vdz** [systemd/systemd#17335]
**systemd version the issue has been seen with**
systemd 246 (246.6-1~bpo10+1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
Debian buster

**Linux kernel version used** (`uname -a`)
4.19.0-11-amd64

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
 VxLAN interface created as configured

**Unexpected behaviour you saw**
 No VxLAN interface created

**Steps to reproduce the problem**
My config files :
/etc/systemd/network/11-br100.netdev
[NetDev]
Name=br100
Kind=bridge

/etc/systemd/network/11-br100.network
[Match]
Name=br100

/etc/systemd/network/11-vxlan100.netdev
[NetDev]
Name=vxlan100
Kind=vxlan

[VXLAN]
VNI=100
Local=10.0.0.1
Remote=10.0.0.2
DestinationPort=10100

/etc/systemd/network/11-vxlan100.network
[Match]
Name=vxlan100

[Network]
Bridge=br100
VXLAN=vxlan100

journalctl -b -u systemd-networkd says : "systemd-networkd[1867]: vxlan100: loaded vxlan" but no vxlan interface is created

networkctl :
IDX LINK  TYPE      OPERATIONAL SETUP
  1 lo    loopback  carrier     unmanaged
  2 ens18 ether     routable    unmanaged
  3 br100 bridge    no-carrier  configuring

**Comment by yuwata** [comment]
Why do you set `VXLAN=vxlan100` in 11-vxlan100.network?

There are two ways vxlan100 to be created:
1. set `Independent=yes` in 11-vxlan100.netdev
2. set `VXLAN=vxlan100` in a .network file which matches an interface NOT vxlan100.

BTW, here is not a support forum, but a bug or feature request tracker. Sorry. Closing.

**Comment by yuwata** [comment]
If you find any bug or issue on vxlan or anything, feel free to request reopening this page or create another page.
