### ISSUE TITLE
Zero size core dumps

### ISSUE THREAD

**Issue by vsotog** [systemd/systemd#17348]
Hi!

I have an issue when generating core dumps with systemd-coredump. I'll write the info below.

## Setup
Ubuntu 20.04, systemd-coredump (apport has been uninstalled)

```
$ coredumpctl --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

```
$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64023
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 64023
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I have a CIFS mounted under `/var/lib/systemd/coredump` and everything seems to be working fine, core dumps are generated with the proper information. 

**Parameters used to mount the CIFS**
```
-o vers=3.0,username=username,password=password,dir_mode=0777,file_mode=0777,serverino,mfsymlinks,sfu
```

## Issue
The problem I am having, might just be a configuration error on my side, is that when I try to change the `kernel.core_pattern`, the core dumps have a size of zero. 

**Things I've tried to change the kernel.core_pattern**
```
#Echoing the new pattern to /etc/sysctl.conf
echo "kernel.core_pattern=/var/lib/systemd/coredump/%h-%e-%t.%p" >> /etc/sysctl.conf

#Using "sysctl -w" and reloading conf with "sysctl -p"
sudo sysctl -w kernel.core_pattern=/var/lib/systemd/coredump/%h-core-%e-%t.%p
```

However, if I try to change the `kernel.core_pattern` to a local path, e.g. `/etc/coredump` (not the mounted CIFS) the files are generated OK. 

Let me know if you need more info. Thanks!

**Comment by poettering** [comment]
if you set the core pattern to some fs path manually, then you bypass systemd-coredump. The core_pattern needs to be set to the pipe path it is by default set to to work properly.

How is this a systemd issue hence? You turn off systemd-coredump basically and then file a bug why systemd doesn't work? What am I missing?

**Comment by vsotog** [comment]
Sorry about that, as I mentioned I wasn't sure if it was only a configuration error on my side, I'll close the ticket. 

What do you mean with "The core_pattern needs to be set to the pipe path it is by default set to to work properly."?
That might fix the issue I'm having

**Comment by poettering** [comment]
Closing hence.

**Comment by poettering** [comment]
(note that ubuntu afair uses apport instead of systemd-coredump. not idea what is necessary to make systemd-coredump work on ubuntu, but the ubuntu folks should know)

**Comment by vsotog** [comment]
Thanks!
