### ISSUE TITLE
networkd: Cannot disable RAs when IPv6 prefix delegation is enabled

### ISSUE THREAD

**Issue by klada** [systemd/systemd#17353]
**Is your feature request related to a problem? Please describe.**

systemd-networkd is able to assign an IPv6 address/prefix it receives from an upstream interface via DHCPv6-PD to local interfaces. Right now systemd-networkd handles that case through this configuration:

```
[Network] 
IPv6PrefixDelegation=dhcpv6

[DHCPv6PrefixDelegation] 
Assign=yes
```

The issue with this is that systemd-networkd assumes that it should always announce the delegated prefix through a RA on that interface. However there are environments where the announcement of the prefix is unwanted. These include environments where other tools, such as radvd or dnsmasq are used to announce the prefix – both tools provide many more options (which are out of the scope of networkd).

The current behavior kind of violates the usage patterns for many scenarios, where systemd-networkd is used for managing interface addresses, but not for providing services such as DHCP or RA.

**Describe the solution you'd like**

There should be an option for disabling RA sending for delegated prefixes. Possible config:

```
[DHCPv6PrefixDelegation] 
Assign=yes
Annouce=no    # should default to "yes" in order to keep compatibility with existing setups
```

**Describe alternatives you've considered**

There are no alternatives other than disabling systemd-networkd completely and configuring interfaces in the old-fashioned way (which is super annoying in environments with DHCPv6-PD).

**Comment by bartelsielski** [comment]
Does the interface get an address assigned when you set the following?
```
[Network] 
IPv6PrefixDelegation=no

[DHCPv6PrefixDelegation] 
Assign=yes
```

According to the man pages (in the [Network] section):
```
IPv6PrefixDelegation=
    Whether to enable or disable Router Advertisement sending on a link. ...
```

**Comment by klada** [comment]
> Does the interface get an address assigned when you set the following?

No, this does not work. And according to the man pages the `[DHCPv6PrefixDelegation]` section with `Assign=yes` is only relevant if `IPv6PrefixDelegation` is enabled.
