### ISSUE TITLE
MemoryDenyWriteExecute causes Branch Target Identification (BTI) enabled services to abort (aarch64)

### ISSUE THREAD

**Issue by jlinton** [systemd/systemd#17368]
**systemd version the issue has been seen with**
 > systemd-246.6-3.fc33.aarch64

**Used distribution**
 > fedora 33

**Linux kernel version used** (`uname -a`)
 > 5.9

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > services running

**Unexpected behaviour you saw**
 > services with MemoryDenyWriteExecute fail to start

**Steps to reproduce the problem**
 > Install an aarch64 disto with BTI enabled (fedora 33) on an arm v8.5+ machine or emulator (arm AEM model, or qemu)
Note that certain services are unable to start, and that there are messages in the log file "mprotect failed to turn on BTI". 

This is caused by systemd+secomp filtering PROT_EXEC calls when MemoryDenyWriteExecute is enabled. Glibc uses mprotect PROT_EXEC|PROT_BTI to turn on the arm v8.5 Branch Target Identification, which is a security feature intended to mitigate ROP attacks.

There is a fedora bug report here: https://bugzilla.redhat.com/show_bug.cgi?id=1888842 along with a glibc patch to bypass BTI.

**Comment by topimiettinen** [comment]
I agree with @keszybz's analysis, allowing this would weaken MWDX and from seccomp it's not possible to determine the original PROT flags. Couldn't the dynamic loader avoid `mprotect()` entirely by `mmap()`ing the program segments with BTI directly with correct PROT flags, including `PROT_BTI`? The problem seems to be that PROT flags are not set up correctly at the first place but need to be fixed later with `mprotect()`.

**Comment by topimiettinen** [comment]
I'd move the PROT_BTI check in dynamic loader [here](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c;h=f3201e7c14424a736da9d4b8fbff247664010076;hb=HEAD#l1180), something like
```
	  if (ph->p_flags & PF_X)
	    c->prot |= PROT_EXEC;
+	  arch_prot_flags(c);  
#endif
```
where arch_prot_flags() would be something like
```
void arch_prot_flags(struct loadcmd *c) {
  if (GLRO(dl_aarch64_cpu_features).bti && l->l_mach.bti)
	c->prot |= PROT_BTI;
}
```
I think then the flags for `mmap()` would not need any fixing.

**Comment by poettering** [comment]
I geuss this was fixed now in glibc, as the linked bz ticket says.

https://sourceware.org/pipermail/libc-alpha/2020-November/119305.html

I guess we can close this here then.

**Comment by fweimer-rh** [comment]
I believe there has been an issue with kernel interop: 

> So I think decoupling the two makes sense but the patch is no longer as simple as the ELF loader now needs to parse the main executable. If that's doable and the code looks sane, I'd go with it. Otherwise, we scrap the idea of the kernel setting PROT_BTI on the main executable.

https://lore.kernel.org/linux-arm-kernel/20210208184902.GC12694@gaia/#t

**Comment by jlinton** [comment]
Right, none of this is fixed yet, although IMHO this is less a systemd problem than a glibc+kernel one at the moment, although it keeps systemd from booting the system.
