### ISSUE TITLE
tmpfiles: Returns failure on NFS mounted filesystem from server not supporting ACLs

### ISSUE THREAD

**Issue by pcoultha** [systemd/systemd#17379]
**systemd version the issue has been seen with**
246

**Used distribution**
Debian stable -> testing upgrade
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972135

**Linux kernel version used** (`uname -a`)
Tested/observed on both:
* 4.19.0-6-arm64 #1 SMP Debian 4.19.67-2
* 5.8.0-3-arm64 #1 SMP Debian 5.8.14-1

NFS server kernel:
*  4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1

**CPU architecture issue was seen on**
arm64

** Background **
systemd-tmpfiles has code to suppress errors and indicate success when ACLs cannot be applied due to a lack of filesystem ACL support. In the case of an NFSv3 mounted root filesystem where the client has not specified the "noacl" mount option, but the backing server filesystem lacks ACL support, the behavior of various syscalls is not fully accounted for by this error handling code.

Therefore...

**Expected behaviour you didn't see**

When run on an NFS-mounted root filesystem (with neither "noacl" nor "acl" mount options specified) where the server filesystem does not support ACLs. I expected:
`systemd-tmpfiles --create --prefix /var/log/journal`
to still exit indicating success (after possibly warning about the lack of ACL support).

This _is_ the behavior I see with a local ext4 "noacl" filesystem or with the same NFS filesystem mounted "noacl" on the client.

**Unexpected behaviour you saw**
In this configuration, systemd-tmpfiles exits with error code 73, after displaying an error:
`Setting access ACL "u::rwx,g::r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal failed: Operation not supported`

**Steps to reproduce the problem**
1. On the NFS server, mount a filesystem without ACL support (like ext4 mounted -o "noacl"). Install a root file system for a root-on-nfs client on this filesystem. Export the filesystem via NFSv3.
1. On the NFS client, mount the remote filesystem without specifying the "noacl" mount option.
1. `mkdir -p /var/log/journal`
1. `systemd-tmpfiles --create --prefix /var/log/journal`
 
**Technical Details**
This issue occurs because in this configuration, the client kernel returns ENODATA when getting the ACL (getxattr(...)), but EOPNOTSUPP when setting the ACL (setxattr(...)). In other configurations (local ext4 filesystem mounted "noacl" or NFS client using "noacl" mount option), the Kernel returns EOPNOTSUPP in both cases. This means that systemd-tmpfiles encounters the EOPNOTSUPP a bit later in the code flow in this specific configuration and treats it as an actual error.

See attached strace logs: 
* [strace-failure.txt](https://github.com/systemd/systemd/files/5397881/strace-failure.txt)
* [strace-success.txt](https://github.com/systemd/systemd/files/5397882/strace-success.txt)

In the "success" log, the "noacl" mount option was added on the NFS client.

**Code Details**
Changing the existing check for -EOPNOTSUPP to check for both positive/negative values, and moving it a bit earlier in the code flow fixes this issue for me (but keeps the user-visible error message):
https://github.com/systemd/systemd/blob/90616bb962703d9d0d61e1988b302f2dae013cb5/src/tmpfiles/tmpfiles.c#L1149-L1168

If it is desirable to also suppress the error message in this case, a check for `errno == EOPNOTSUPP` could be added here:
https://github.com/systemd/systemd/blob/cea0e4e281c413ab69da15873c2d3dd7cc89e38c/src/tmpfiles/tmpfiles.c#L1106-L1115

I'd be happy to submit a pull request including either/both of these changes for consideration.

**Comment by poettering** [comment]
Sure, please prep a patch and submit as PR.

(Note that we typically now use the macro ERRNO_IS_NOT_SUPPORTED() as a more generic EOPNOTSUPP check. It also checks a couple of other typically seen error codes for the "not supported" case. I think instead of checking EOPNOTSTUPP explicitly here, we probably should use the new macro instead)
