### ISSUE TITLE
No router advertisements sent out over wireguard link

### ISSUE THREAD

**Issue by bartelsielski** [systemd/systemd#17380]
**systemd version the issue has been seen with**
246

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
Linux 5.9.1-arch1-1

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Client autoconfiguring ipv6 addresses by using router advertisements sent out over wireguard link by the server.

**Unexpected behaviour you saw**
Router advertisements were not sent.

**Steps to reproduce the problem**
Setup the following configuration:

### Server configuration:
`/etc/systemd/network/20-wg0.netdev`:
```
[NetDev]
Name=wg0
Kind=wireguard

[WireGuard]
PrivateKey=server_private_key
ListenPort=12345

[WireGuardPeer]
PublicKey=client_public_key
AllowedIPs=::/0
```

`/etc/systemd/network/20-wg0.network`:
```
[Match]
Name=wg0

[Link]
Multicast=yes

[Network]
Address=fd00:1234:5678:9abc::1/64
IPv6PrefixDelegation=static

[Address]
Address=fe80::1234:5678:9abc:def0/64
Scope=link

[IPv6PrefixDelegation]
RouterLifetimeSec=0
DNS=fd00:1234:5678:9abc::1
Domains=example.com
DNSLifetimeSec=1800

[IPv6Prefix]
Prefix=fd00:1234:5678:9abc::/64
```

### Client configuration:
`/etc/systemd/network/20-wg0.netdev`
```
[NetDev]
Name=wg0
Kind=wireguard

[WireGuard]
PrivateKey=client_private_key

[WireGuardPeer]
PublicKey=server_public_key
AllowedIPs=::/0
Endpoint=wireguard.example.com:12345
```

`/etc/systemd/network/20-wg0.network`
```
[Match]
Name=wg0
Type=wireguard

[Link]
Multicast=yes

[Network]
IPv6Token=static:::0fed:cba9:8765:4321
IPv6AcceptRA=yes

[Address]
Address=fe80::0fed:cba9:8765:4321/64
Scope=link

[IPv6AcceptRA]
UseDomains=route
```

**Comment by yuwata** [comment]
Hmm, at least currently, IPv6 RA is supported only when the interface has an IPv6 link local address, and wireguard interfaces seem not to support IPv6 LL address. Do you mean we should support to send RA even if a link does not have an IPv6LL address?

**Comment by bartelsielski** [comment]
@yuwata 

> Do you mean we should support to send RA even if a link does not have an IPv6LL address?

No, this is required by [RFC4861](https://tools.ietf.org/html/rfc4861#section-3.2).

>  wireguard interfaces seem not to support IPv6 LL address.

There is nothing which blocks link local addresses from working in the wireguard protocol. It's just that a LL address cannot be automatically generated because the link does not have a mac address. As you can see in the configuration I included in the issue description, I've manually added a link local address to both wireguard peers and I can ping between the 2 devices using these LL addresses.

**Comment by mercora** [comment]
wireguard does not support anything but unicast routing

**Comment by bartelsielski** [comment]
@mercora 
> wireguard does not support anything but unicast routing

Multicast works perfectly fine when the wireguard setup is a point-to-point link because there multicast and unicast are effectively the same. This only requires that the `AllowedIPs` are configured correctly and the multicast flag is set on the interface (which it isn't by default).

If you read [this message](https://lists.zx2c4.com/pipermail/wireguard/2020-September/005825.html) posted to the wireguard mailing list, you can see that the poster has gotten mDNS working over a point-to-point wireguard connection.

**Comment by mercora** [comment]
it is not the same, this is just using multicast addresses using unicast routing. if its a point-to-point link (i.e a single remote endpoint on the interface) it could indeed work but note that only a single endpoint can be configured with a specific AllowedIPs. So you would configure the radv reciever to be the destination for the multicast address used for this. This does not imply multicast "works perfectly" in any way whatsoever. If you read closely the message you've just linked you see that he had trouble configuring "overlapping ranges" which would be a requirement for proper multicast support. To make it work he patched wireguard to intercept specific (multicast) packets and send them out to all connected endpoints (effectively making multicast kinda working) bypassing...

**Comment by bartelsielski** [comment]
@mercora The "overlapping ranges" issue is only relevant when a wireguard node has multiple peers. The configuration I included in the issue description is a point-to-point link. This requires no hacking on the wireguard kernel code to make it work.

**Comment by bartelsielski** [comment]
I've gotten router advertisements to work over a wireguard point-to-point link using radvd on the server side and dhcpcd on the client side. The configuration is included below.

### Server configuration:

`/etc/systemd/network/20-wg0.netdev`:
```
[NetDev]
Name=wg0
Kind=wireguard

[WireGuard]
PrivateKey=server_private_key
ListenPort=12345

[WireGuardPeer]
PublicKey=client_public_key
AllowedIPs=::/0
```

`/etc/systemd/network/20-wg0.network`:
```
[Match]
Name=wg0

[Link]
Multicast=yes

[Network]
Address=fd00:1234:5678:9abc::1/64

[Address]
Address=fe80::1234:5678:9abc:def0/64
Scope=link
```

`radvd.conf`:
```
interface wg0 {
  AdvSendAdvert on;
  AdvDefaultLifetime 0;
  prefix fd00:1234:5678:9abc::/64 {};
  RDNSS fd00:1234:5678:9abc::1 {};
  DNSSL example.com {};
};
```

### Client configuration:
`/etc/systemd/network/20-wg0.netdev`:
```
[NetDev]
Name=wg0
Kind=wireguard

[WireGuard]
PrivateKey=client_private_key

[WireGuardPeer]
PublicKey=server_public_key
AllowedIPs=::/0
Endpoint=wireguard.example.com:12345
```

`/etc/systemd/network/20-wg0.network`:
```
[Match]
Name=wg0
Type=wireguard

[Link]
Multicast=yes

[Address]
Address=fe80::0fed:cba9:8765:4321/64
Scope=link
```

Run `dhcpcd -6 wg0`

**Comment by mercora** [comment]
does it use the same destination address as networkd? i would guess you have a route for that subnet pointing to the wiregurad interface... i.e. all traffic destined fd00:1234:5678:9abc::/64 hits the wireguard interface which in turn forwards the traffic accordingly. My guess is networkd is not using a subnet specific destination address. thus no route points to your wireguard interface and in turn nothing reaches the client.  but as i said i am just guessing here.

**Comment by bartelsielski** [comment]
I've had a quick look at the code for router advertisments and immediatly found: `radv_configure` which has a guard clause calling `link_ipv6ll_enabled` (via `link_radv_enabled`).

This is some of the code for `link_ipv6ll_enabled`:
```c
bool link_ipv6ll_enabled(Link *link) {
        ...
        if (STRPTR_IN_SET(link->kind, "vrf", "wireguard", "ipip", "gre", "sit", "vti", "nlmon"))
                return false;
        ...
}
```

So systemd-networkd hardcodes that wireguard interfaces do not have an IPv6 link local address. Which is simply an incorrect assumption.

**Comment by yuwata** [comment]
Fix is waiting in #21692.

**Comment by zx2c4** [comment]
Please revert this. WireGuard does not work with LLv6 by design.

**Comment by iam-TJ** [comment]
[RFC4291 "IP Version 6 Addressing Architecture" section 2.1 "Addressing Model"](https://datatracker.ietf.org/doc/html/rfc4291#section-2.1):

"All interfaces are required to have at least one Link-Local unicast address (see Section 2.8 for additional required addresses). "

**Comment by zx2c4** [comment]
I'm aware of that text. It doesn't change the fact that this isn't how WireGuard works.

**Comment by zx2c4** [comment]
This still needs to be reverted.

**Comment by moshevds** [comment]
@zx2c4 Can you give some explanation about **why** this needs to be reverted?

It seems like you are confirming that wireguard is strictly speaking not compliant with v6 of the internet protocol, but at the same time saying that this systemd feature should be reverted because it is strictly speaking not compliant with the wireguard protocol?

(I'm currently evaluating VPN options, and RAs happen to be one of my requirements. I'm open to suggestions that my network topology is wrong, and you seem to be of that opinion. For that reason, I'm interested in the why of it.)

**Comment by awlx** [comment]
As a Wireguard interface is a routed interfaces and thus has no link-layer, in my opinion a `fe80` doesn't make any sense as the scope would only be the interface and nothing further.

Just like `loopback` is handled in Linux which also has no `fe80` assigned.
```
lo               UNKNOWN        127.0.0.1/8 ::1/128 
```

I think adding a `fe80` actually violates the IPv6 RFC as `fe80` is scope link and shouldn't be routed. But Wireguard is crypto **routing**.

So I agree with @zx2c4 that this should be reverted.

**Comment by eqvinox** [comment]
> As a Wireguard interface is a routed interfaces

There is no such thing as a "routed interface", neither in Linux nor in the IPv6 RFCs. All¹ IPv6 interfaces require a link-local address. As a matter of fact, the absence of LL addresses makes Wireguard incapable of running standard IPv6 routing protocols.

[¹] If you really want to go into the "weeds" on this, technically there isn't even an exception for loopback on this, and some BSDs do in fact configure a `fe80::` address for loopback. Linux does not. This is of "academical" interest only though.

> WireGuard does not work with LLv6 by design.

That is a Wireguard bug and should be fixed in Wireguard. Looking at the other comments here it seems to already work on PtP links, which is a good start.

**Comment by donaldsharp** [comment]
The problem with just `ignoring` the RFC here is that anything that programs against the v6 RFC and expects the LL address to be present is just not going to work!  It's an odd stance to take, imo, effectively shutting off v6 usage for your end users.
