### ISSUE TITLE
can't start ovs through systemctl start ovs

### ISSUE THREAD

**Issue by WSEmma** [systemd/systemd#17408]
**systemd version the issue has been seen with**
 >systemd 237

**Used distribution**
 > Ubuntu 18.04.5 LTS \n \l

**Linux kernel version used** (`uname -a`)
 >Linux ubuntu 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 >X86_64

**Expected behaviour you didn't see**
 >systemctl start ovs   failed.It seems that ovs service is not registered inside systemed

**Comment by poettering** [comment]
You apparently have no service "ovs" installed?

This is not a systemd problem. Please ask your downstream distribution (Ubuntu) for help about this, i.e. how to install packages.
