### ISSUE TITLE
transient hostname received from dhcp server (option 12) is not set for longer period. goes away after a minute or two

### ISSUE THREAD

**Issue by elschman** [systemd/systemd#17402]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.2)

**Used distribution**
 > ubuntu 20.04
**Linux kernel version used** (`uname -a`)
 > Linux dev75523 5.4.0-1026-kvm #27-Ubuntu SMP Wed Sep 30 23:41:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > the hostname is set as transient and stable as long the dhcp session is valid

**Unexpected behaviour you saw**
 > the transient hostname goes away after a minute or two

**Steps to reproduce the problem**
 > set option 12 on dhcp server for the dhcp entry to set a hostname via dhcp. reboot the host and check via hostnamectl.

**Comment by poettering** [comment]
Closing due to lack of response
