### ISSUE TITLE
 Support DNSSEC in every build, make it clear validation is toggled only

### ISSUE THREAD

**Issue by pemensik** [systemd/systemd#17419]
**Is your feature request related to a problem? Please describe.**
Include security-aware resolver support in all builds. That means [RFC 4035, paragraph 3.2](https://tools.ietf.org/html/rfc4035#section-3.2).

**Describe the solution you'd like**
Enable DO on all ougoing queries, regardless what were requested by user. If forwarder could deliver DO types, pass them to clients with RFC 4035 support. Allow only disabling [paragraph 4.2](https://tools.ietf.org/html/rfc4035#section-4.2) validation by a local or build-time policy.

**Describe alternatives you've considered**
Tried in request #17226, but that was closed after just minor fix on documentation was implemented.

**Comment by keszybz** [comment]
Let's not multiply tickets. The discussion can continue in #17226.

**Comment by pemensik** [comment]
I haven't noticed any discussion attempts from your side unfortunately.
