### ISSUE TITLE
resolved: Include support for EDNS0 (RFC 2671)

### ISSUE THREAD

**Issue by pemensik** [systemd/systemd#17420]
**Is your feature request related to a problem? Please describe.**
[EDNS0](https://tools.ietf.org/html/rfc2671) allows extension of DNS message size and some later extensions. It is 20 years old and still not supported by the most recent systemd-resolved.

**Describe the solution you'd like**
``dig localhost | grep OPT`` to be non-empty.

**Describe alternatives you've considered**
Because it can do DNSSEC support on outgoing queries, it has to support it already. Please pass it also to clients indicating its support.

**Comment by poettering** [comment]
```
$ dig localhost @127.0.0.53

; <<>> DiG 9.11.23-RedHat-9.11.23-1.fc32 <<>> localhost @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36158
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;localhost.			IN	A

;; ANSWER SECTION:
localhost.		0	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Do Okt 22 16:34:46 CEST 2020
;; MSG SIZE  rcvd: 54
```

Are you sure you are using systemd-resolved?

**Comment by pemensik** [comment]
Oh, you are right. I were playing with mikrotik forwarder and it remained in resolv.conf after some testing.

```
$ dig localhost @127.0.0.53 | grep OPT
;; OPT PSEUDOSECTION:
```

``systemd-246.6-3.fc34.x86_64``

**Comment by pemensik** [comment]
It were on  ``/run/systemd/resolve/resolv.conf``, which does not point to systemd itself.
