### ISSUE TITLE
ExecStopPost fails on a socket-activated service with Accept=true where the service shuts down the socket

### ISSUE THREAD

**Issue by ihenry1** [systemd/systemd#1742]
An ExecStopPost= line in a socket-activated service with Accept=true fails when the process started in ExecStart= shuts down the socket. I first had this problem when trying to add an ExecStopPost= to `vsftpd@.service` with a .service.d/*.conf file, the output and service files below are for a simplified test case.

Journal output:

```
Nov 01 12:04:13 desktop-arch systemd[1]: Started Accept=true ExecStopPost service ([::1]:51802).
Nov 01 12:04:13 desktop-arch systemd[1]: test-socket-execstoppost@1-::1:12345-::1:51802.service: Failed to run 'stop-post' task: Transport endpoint is not connected
Nov 01 12:04:13 desktop-arch systemd[1]: test-socket-execstoppost@1-::1:12345-::1:51802.service: Unit entered failed state.
Nov 01 12:04:13 desktop-arch systemd[1]: test-socket-execstoppost@1-::1:12345-::1:51802.service: Failed with result 'resources'.
```

/etc/systemd/system/test-socket-execstoppost.socket

```
[Unit]
Description=Accept=true ExecStopPost socket

[Socket]
Accept=true
ListenStream=[::1]:12345

[Install]
WantedBy=sockets.target
```

/etc/systemd/system/test-socket-execstoppost@.service

```
[Unit]
Description=Accept=true ExecStopPost service

[Service]
ExecStart=/usr/bin/python2 -c 'import socket; s = socket.fromfd(0, socket.AF_INET6, socket.SOCK_STREAM); s.shutdown(socket.SHUT_RDWR)'
ExecStopPost=/bin/true
StandardInput=socket
```

Using strace I see that the ENOTCONN comes from systemd trying to call getpeername on the shut down socket.

Distribution: Arch Linux
systemd version: 227-1

**Comment by evverx** [comment]
Fix: #4108
