### ISSUE TITLE
Add preset-all option to run generators, similar to systemd-analyze

### ISSUE THREAD

**Issue by charles-dyfis-net** [systemd/systemd#17432]
When building a system image in a chroot without systemd _actually running_, it's often helpful to run `systemctl preset-all` such that the image has services that are expected to be enabled already running without the necessity of having an empty `/etc` to trigger this operation on-boot in the guest.

However, if a system image contains generators that would modify dependency order, this operation does not reflect them, and thus can enable services that shouldn't be enabled, or fail to enable services that _should_ be enabled.

Just as `systemd-analyze` has a `--generators=true` option to run generators against a temporary directory as a destination and take those into account, `systemctl preset-all` would benefit from an equivalent option.

**Comment by poettering** [comment]
I don#t understand what you are saying? generators only generate transient units, i.e. units in /run? You want to run the offline aheadof time? That makes no sense to me? I don't grok this at all?

preset-all doesn't take generator output into account, so why would one run generators before them?

**Comment by charles-dyfis-net** [comment]
> preset-all doesn't take generator output into account, so why would one run generators before them?

Context for this ticket: I have a generator which removes systemd-timesyncd from sysinit.target (creating a `/run/systemd/...` version of `systemd-timesyncd.service` to shadow the "real" file by filtering the unwanted dependency out of the original), as I'm making changes to systemd-timesyncd's configuration based on information which is only known later in the boot process.

The use of a generator is the approach I landed on for a few reasons: I can't just include a filtered version in my own codebase on account of the service file itself being under GPLv2; and overlay files, as far as I can tell, aren't capable of _removing_ dependency relationships.

My experience is that if-and-only-if I manually run this generator (with its output going to the same `/run/...` location as usual) before `systemctl preset-all`, this prevents a `sysinit.target.wants/systemd-timesyncd.service` link from being created by `preset-all` in `/etc`. Needing to do that manually is unfortunate, though -- it means needing to create and then clean up `/run` contents, hence this ticket.

**Comment by poettering** [comment]
I don't get it? What's the usecase precisely? I am not sure I grok why you want to remove systemd-timesyncd? If you want to manage its enable/disable state programmatically, then manage that via a generator, and don't enable it via a preset. It's just strange to enable something just to disable it dynamically again. Do it the other way round: leave it off, and only enable it dynamically via generator if you need it?

But I really don't get the usecase. I think it would be best to start from the beginning: what precisely are you trying to do? please keep it brief and concise, but start from the goal, not from the mechanisms you chose to implement it with currently

**Comment by charles-dyfis-net** [comment]
> Do it the other way round: leave it off, and only enable it dynamically via generator if you need it?

That... would work. Mind, the intent is to _always_ enable it, but as part of `multi-user.target` instead of `sysinit.target`. But that can certainly be done at runtime; the point of building presets into the image is to prevent failure cases from leaving no services running, but we're accessible enough for administrative use &c. without NTP.

Would you want to close this ticket absent an alternative use case?

**Comment by poettering** [comment]
(btw, there's somewhere an issue open for allowing cancelling of deps via masking symlinks. i.e. that a symlink created with "ln -s /dev/null /etc/systemd/system/foobar.service.wants/quux.service allows cancelling out a Wants= dep from foobar.service to quux.service. But so far this hasn't materialized. I figure that would also be an option for you, if it ever gets implemented)

Anyway, let's close as there's apparently an OK solution found already now.
