### ISSUE TITLE
Add configurability to keep network in operational down state on startup

### ISSUE THREAD

**Issue by mercora** [systemd/systemd#17437]
In order to bring up network interfaces only when they are needed i would like networkd to keep networks in operational off state when configured for this. Currently i need to issue `networkctl down interface-name` every time networkd starts.

I suggest to make a setting available to tell networkd to keep the device in operational off state on startup and only start configuring the network once  `networkctl up interface-name` has been issued. Additionally the operational state of the network might be held across reload operations like it already does.

Alternatively it is probably possible to do this by making the link unavailable to networkd somehow at startup and when not desired anymore but i don't know how i would do that. Bringing it down via some custom systemd.service might work too but will likely leave the network at an operational state other then off for a brief period of time which is not desired.

**Comment by poettering** [comment]
I figure #16228 implements what you are asking for?

**Comment by mercora** [comment]
yes that is pretty much what i was hoping for :)

**Comment by poettering** [comment]
(no need to close this issue just yet, after all #16228 isn't merged yet. but i guess it doesn't matter now)
