### ISSUE TITLE
journalctl returns success/zero-exit code even without any matches

### ISSUE THREAD

**Issue by lukastribus** [systemd/systemd#17442]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.2)

**Used distribution**
 > Ubuntu 20.04 LTS

**Linux kernel version used** (`uname -a`)
 > Linux ubuntu20 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > journalctl should return a non-zero exit code (failure), when no log messages have matched the query.

**Unexpected behaviour you saw**
 > journalctl returns zero exit-code (success), even when no message matched the filters. Only when using regular expression (-g <expression>) a non-zero exit-code is returned on failure.

**Steps to reproduce the problem**

* issue a journalctl query that will not return any results, check exit-code
* issue a journalctl query by using regex (-g), that will not return any results, check exit-code

```
lukas@ubuntu20:~$ journalctl --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
lukas@ubuntu20:~$
lukas@ubuntu20:~$ journalctl MESSAGE="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
-- Logs begin at Sat 2020-08-15 13:57:48 CEST, end at Sat 2020-10-24 16:21:53 CEST. --
-- No entries --
lukas@ubuntu20:~$ echo $?
0
lukas@ubuntu20:~$
lukas@ubuntu20:~$
lukas@ubuntu20:~$
lukas@ubuntu20:~$ journalctl -g "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
-- Logs begin at Sat 2020-08-15 13:57:48 CEST, end at Sat 2020-10-24 16:21:53 CEST. --
-- Reboot --
-- Reboot --
-- Reboot --
-- Reboot --
-- No entries --
lukas@ubuntu20:~$ echo $?
1
lukas@ubuntu20:~$

```

Same on 246 / Ubuntu 20.10:

```
root@ubuntu:~# uname -a
Linux ubuntu 5.8.0-25-generic #26-Ubuntu SMP Thu Oct 15 10:30:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# journalctl --version
systemd 246 (246.6-1ubuntu1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
root@ubuntu:~#
root@ubuntu:~# journalctl MESSAGE="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
-- Logs begin at Sat 2020-10-24 14:44:11 UTC, end at Sat 2020-10-24 14:49:59 UTC. --
-- No entries --
root@ubuntu:~# echo $?
0
root@ubuntu:~#
root@ubuntu:~# journalctl -g "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
-- Logs begin at Sat 2020-10-24 14:44:11 UTC, end at Sat 2020-10-24 14:49:59 UTC. --
-- No entries --
root@ubuntu:~# echo $?
1
root@ubuntu:~#
root@ubuntu:~# journalctl -u sablabsldlalsdlasd
-- Logs begin at Sat 2020-10-24 14:44:11 UTC, end at Sat 2020-10-24 14:50:56 UTC. --
-- No entries --
root@ubuntu:~# echo $?
0
root@ubuntu:~#
```

**Comment by keszybz** [comment]
It is not an error to have no logs... If we were designing things from scratch, maybe we could do something different. But the current interface has been like this for the last 9 years, and we can't change this without breaking backwards compatibility. If we changed the return code this would likely break many many scripts. So sorry, it's too late too change this.

**Comment by lukastribus** [comment]
> It is not an error to have no logs..

The use-case is to execute other things down the line, based on whether or not something has been found in the logs.

`journalctl MESSAGE="AAAAAAAAAAAAAA" && echo "Oh no, the thing happened again"`

If it works for regex but not for other things, someone somewhere along the line agreed that this would be a god thing. `it's not an error to have no logs` is pretty weak argument.

The primary use-case for journalctl is to show logs. Therefor exit-code should be strongly depend on that.

`diff` returns 1 if the files are different, `cmp` same, just as `grep` also changes exit code based on whether or not it matches something.

I agree with your point about backwards compatibility, but there are things that can be done about. Like only changing the behavior if a new flag is used.

**Comment by keszybz** [comment]
`--grep` was added much later, and it was reasonable to use a different convention.

>  Like only changing the behavior if a new flag is used.

You can use `--grep=.` as the flag that will change the return code.
```console
$ journalctl -b MESSAGE="AAAAAAAAAAAAAA" --quiet; echo $?
0
$ journalctl -b MESSAGE="AAAAAAAAAAAAAA" --quiet --grep=.; echo $?
1
```

**Comment by lukastribus** [comment]
I didn't think of that, yes, that's better than a pipe.

Thanks
