### ISSUE TITLE
systemd in container in cgroupv2 environment

### ISSUE THREAD

**Issue by luodw** [systemd/systemd#17447]
Recently, I test containerd in cgroupv2 environment, this is my physical machine env: kernal 5.4 + cgroupv2 + systemd 241. And in container, systemd is in version 230

When I run command `ctr run -t --rm  --mount type=tmpfs,src=/run,dst=/run --mount type=tmpfs,src=/run/lock,dst=/run/lock --mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,options=rbind:ro  --env container=containerd  <containerid> <image> /lib/systemd/systemd`， it will failed as follow
![image](https://user-images.githubusercontent.com/14847074/97147706-e2ad0f80-17a4-11eb-95c5-d14e23b52923.png)

But if /sys/fs/cgroup change to rw mount, it will be ok. So in cgroupv2 env, /sys/fs/cgroup must be mounted  as rw? But it's not safe to mount /sys/fs/cgroup as rw?

**Comment by poettering** [comment]
We document our requirements on cgroupsfs here:

https://systemd.io/CONTAINER_INTERFACE/

Also, this is not a support forum, please contact the systemd ML or so for help you have support questions like this.

**Comment by luodw** [comment]
ok, thanks

**Comment by luodw** [comment]
@poettering hi, whether systemd support not create cgroup hierarchy in container in cgroupv2 env? I do not find any information about this, thanks.
