### ISSUE TITLE
homed: if user logs out but some (privileged?) process keeps $HOME busy and pinned, retry every now and then to unmount to clean things up.

### ISSUE THREAD

**Issue by damianatorrpm** [systemd/systemd#17445]
systemd-246.6-3.fc34.x86_64

The following behavior strikes me as very odd:
I have two terminals in Terminal1 I am logged in as root.
in Terminal2 am logged in as tux.

I created via homectl a new user test  --storage=luks
I log in as UserY in Terminal2 via ` su - test `
I cd in Terminal1(root) to` /home/test` 
I log out of Terminal2 via 'exit'
In Terminal1(root) I cd out of /home/test

A few moments later I see that the luks-volume is still mounted
and root can still cd into it and create files which are visible the next time 'test' logs in.

Is this by design?

**Comment by poettering** [comment]
if you "cd" into it, you keep it busy.

What does "homectl" report? What does "loginctl" report? Do you have "lingering" for the user enabled? Anything still running that keeps the home dir pinned, for example PulseAudio, gpg-agent or so? What does "ps xauwf" say?

**Comment by damianatorrpm** [comment]
>loginctl - nothing regarding that user
>homectl - yes it reports that session as active!

I verified the same behavior a few times and it seems if root is in the home directory 
at the time the user exits, even if root closes his session the users session will stay active indefinitely,
(I can't see any processes belonging to that user), unless --kill-processes=true is set in the users config.

If root never cd's into that directory it becomes 'inactive' cleanly.

I haven't done loginctl enable-linger (unless that's default on Fedora for users).

**Comment by poettering** [comment]
yeah, a process with a working directory in the user's home keeps the user's fs busy. 

I fgure we could install a timer though, and retry every now and then. won#t be instant then, but simple and robust.

the kernel simply doesn#t allow unmounting file systems that are pinned by a process through the working directory logic. We could of course kill the offending processes, but that sounds like a bad idea, in particular as the process pinning the fs is likely more privileged

**Comment by poettering** [comment]
I turned this into an RFE bug now, suggesting we try to unmount every now and then again if we see things are busy.

**Comment by damianatorrpm** [comment]
Just as an idea, but you will probably know better if possible etc.
The e.g timer runs whenever a user exits a shell,
checks if the user has other shells open,
closes if no shell opens affecting that user.

Thanks for your attention and support.

**Comment by poettering** [comment]
we already unmount the home directory once the user's last session ends. But if some other non-session process keeps the home directory open/pinned for some reason (like in your case that root process having it as its working directory) this won't work. Currently we leave the home directory mounted then, and don't try again. This RFE issue is now about retrying this a couple of times while offline, until it works.
