### ISSUE TITLE
Forking Is Broken

### ISSUE THREAD

**Issue by diabl0w** [systemd/systemd#17458]
**systemd version the issue has been seen with**
 > 246.6-1 on arch linux

**Used distribution**
 > arch linux

**Linux kernel version used** (`uname -a`)
 > 5.8.14

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > systemd suspend.service with **type=forking** and running **i3-lock --no-fork**
should fork the i3 lock command and then suspend instead of waiting for i3lock to complete

**Unexpected behaviour you saw**

 > when closing the laptop lid or any other way of invoking suspend, if I wait a few seconds and then wake, the lockscreen is there waiting for me and so:
>  as soon as i unlock, it allows the i3-lock to finish, therefore allowing systemd service to finish (because its waiting instead of properly forking) and the laptop immediately suspends after the unlock. 

>If instead of waking after a few seconds, and I just let the laptop suspend, then later upon waking the systemd service will have an error that it timed out (because it didn't properly fork and instead waited for i3-lock --no-fork which never completed)

**Steps to reproduce the problem**
 suspend@.service:
> [Unit]
> Description=User suspend actions
> Before=sleep.target
> [Service]
> User=%I
> Type=forking
> Environment=DISPLAY=:0
> ExecStart=/bin/i3lock -n
> ExecStartPost=/usr/bin/sleep 2
> [Install]
> WantedBy=sleep.target

**Comment by diabl0w** [comment]
well, changing the type to "simple" fixes this issue... this doesn't make sense to me logically though. Why would type=forking wait for a process to complete while type=simple not wait for the process to complete?

**Comment by keszybz** [comment]
Feel free to peruse the documentation (https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) at any time.

**Comment by boucman** [comment]
a bit more explanation: 
Type= tells systemd how the process will behave, and systemd reacts accordingly.

Type=forking: the process will fork, so systemd waits for the forking to happen and  for the parent to finish
Type=simple: the process will not fork, so systemd considers it ready right away and does not wait for it to exit before moving on.

**Comment by diabl0w** [comment]
> a bit more explanation:
> Type= tells systemd how the process will behave, and systemd reacts accordingly.
> 
> Type=forking: the process will fork, so systemd waits for the forking to happen and for the parent to finish
> Type=simple: the process will not fork, so systemd considers it ready right away and does not wait for it to exit before moving on.

Thanks for the explanation, that was clearer than the documentation. Sorry for wasting your time
