### ISSUE TITLE
 A possible memory leak occurs in systemd

### ISSUE THREAD

**Issue by Carol-code2222** [systemd/systemd#17450]
**systemd version the issue has been seen with**

systemd-239

**Used distribution**
 > systemd-239-13.el8.x86_64

**Linux kernel version used** (`uname -a`)
 > 
4.18.0-80.el8.x86_64 

**Unexpected behaviour you saw**
 > When the “systemctl daemon-reload“ command is executed repeatedly, the RES of pid 1 keeps increasing，the memory is increased by 6 MB in 3 hours.
After “systemctl daemon-reload“ is stopped, the memory is not released

![image](https://user-images.githubusercontent.com/31803337/97181807-a85c6600-17d6-11eb-9c7f-1fdaf335de0a.png)

**Steps to reproduce the problem**
 >  Run the "systemctl daemon-reload" command repeatedly.
#!/bin/bash
while true;
do
        systemctl daemon-reload;
        sleep 1
done

**Comment by keszybz** [comment]
Sorry, we only fix upstream bugs in the latest two versions of systemd. 239 is ancient for us. Please take it up with your distro if necessary.
