### ISSUE TITLE
Cannot activate VT without CAP_SYS_ADMIN when polkit is disabled (prevents running weston as non-root user)

### ISSUE THREAD

**Issue by JPEWdev** [systemd/systemd#17473]
**systemd version the issue has been seen with**
 > 245 and later (also reproduced on latest master)

**Used distribution**
 > Custom Embedded Distribution on Raspberry Pi 4

**Linux kernel version used** (`uname -a`)
 > 5.4.72

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Since 4acf0cfd2f92edb94ad48d04f1ce6c9ab4e19d55, it is no longer possible for a process without `CAP_SYS_ADMIN` to activate a virtual terminal when polkit support is disabled.

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > Build without polkit support and attempt to activate launch weston as  non-root user. See: https://gitlab.freedesktop.org/wayland/weston/-/issues/428

**Comment by poettering** [comment]
Install PK if you want unpriv users to chvt?

**Comment by JPEWdev** [comment]
If it is avoidable, I'd rather not pull in polkit into an embedded device; it's a pretty heavy dependency.

Also, I think there is some precedence here: IIUC 19bb87fbfac8df67c0c8ff4714382a88733c61a2 changed the default polkit policy so that unprivileged users can chvt from a service for pretty much the same reason (running a wayland compositor from a user service). I'm wondering if we can restore that to be the default behaivor when polkit support is not enabled.

**Comment by JPEWdev** [comment]
Any update on this? It's preventing us from updating to newer versions of systemd in our embedded devices.

**Comment by mikkorapeli** [comment]
Reviewed the patch and it looks good. I would also like to have it applied to systemd to avoid carrying the patch in downstream distros for embedded devices. systemd dependency to polkit should be configurable. As is obvious to everyone, polkit depends on full javascript engine mozjs which has a huge impact on rootfs size and boot times for anything which depends on them, like weston in this case.

**Comment by debrouxl** [comment]
I would be interested in a version of systemd where this issue is fixed, by the pull request or an equivalent patch :)
