### ISSUE TITLE
Condition on systemd version to ease API breaking upgrades

### ISSUE THREAD

**Issue by raggi** [systemd/systemd#17481]
**Is your feature request related to a problem? Please describe.**

I have configured a system that is performing ipv6 prefix delegation using systemd-networkd v246. The setup for this had a number of challenges, leading to various bug fixes and changes coming in the 247 series (yay!). Unfortunately these changes delete current configuration API (boo!), and replace it with new API (yay?). I'm happy to move to the new API, but on a system with rolling updates, it's a high cost of ownership for me to have to track the systemd release process and distro release process for timing.

**Describe the solution you'd like**

As I already know what the new configuration should be, I would like to be able to type that in to my system now, with a condition such that it will take effect only once the system upgrades to the new version. I see kernel version conditions in the documentation, but I do not see a systemd version I can apply conditions to.

**Describe alternatives you've considered**

I think the behavior of the system is such that I could include both configurations now, and live with errors in the logs, however, I need to monitor for errors in the logs and alert on them because other parameters may change during rolling updates that I need to be aware of, so such a solution is noisy without a bunch more effort.

I can also disable rolling upgrades, but that arguably increases my cost of ownership, and may push me toward more calcified solutions over time.

Thank you for this software. It's in general working great for me, and a pleasure to configure.

**Comment by poettering** [comment]
> Unfortunately these changes delete current configuration API (boo!), and replace it with new API (yay?)

Hmm? They do? I thought we kept compat for all options?

What you you mean by "configuration API"? you mean the configuration file settings? What precisely?

We try hard to maintain compat, and usually are pretty good at that. Are you saying we fucked something up there?

I'd rather fix the incompatibilities than add work arounds for them

**Comment by poettering** [comment]
I presume you are talking about systemd-networkd here?

**Comment by raggi** [comment]
Yes, systemd-networkd.

I am currently using:

```
[Network]
IPv6PrefixDelegation=dhcpv6
```

This appears to have been replaced by:

```
[Network]
DHCPv6PrefixDelegation=yes
```

**Comment by poettering** [comment]
IPv6PrefixDelegation= is still understood.

When we rename stuff we leave the old stuff around for compat reasons.

**Comment by raggi** [comment]
I see, thank you.

Is there somewhere I can read about this, are these deprecated options ever removed, if so on what schedule?
