### ISSUE TITLE
Shouldn't all systemd tool man pages enumerate relevant environment variables?

### ISSUE THREAD

**Issue by vcaputo** [systemd/systemd#17484]
Something like `SYSTEMD_LOG_LEVEL=debug` affects `systemctl`, yet the systemctl(1) man page makes zero mention of `SYSTEMD_LOG_LEVEL` or its effects.

Is it really appropriate to only mention these variables in the systemd(1) man page?  It implies that these variables only affect PID1, and it's unlikely anyone reading the systemctl(1) man page would go looking at systemd(1) for more potentially relevant variables - especially considering systemctl(1) explicitly enumerates environment variables in its own `ENVIRONMENT` section, without mentioning systemd(1)'s `ENVIRONMENT` section may contain variables also affecting systemctl's execution .

I think we should either refer the reader to systemd(1) for more variables from all the man pages in their respective `ENVIRONMENT` sections, or explicitly duplicate the documentation for relevant variables in every man page.

**Comment by keszybz** [comment]
Yeah, we should do something similar to `man/less-variables.xml` and include it in various places.

**Comment by vcaputo** [comment]
Nice!
