### ISSUE TITLE
systemd automatically umounts manual mounts for failed mount unit

### ISSUE THREAD

**Issue by leiyu-bytedance** [systemd/systemd#17487]
**systemd 241/232 and probably earlier**
**[Update]**: This issue occurs on **systemd 246** as well

This is a very similar bug as https://github.com/systemd/systemd/issues/1741
The difference is that the issue in #1741 is for the mount units that has **`LABEL`** in `/etc/fstab`, but this issue applies for other cases, e.g. UUID.

In short, as long as a mount unit is in the failed state, systemd will automatically un-mount it once the mount-point is mounted by other devices.

The below steps are tested on Debian 9 and Debian 10, most likely it is reproduced on other distros.

**Steps to reproduce the problem**
```bash
### Precondition: In a virtual machine, attach and format /dev/vdb1 as ext4
# /sbin/blkid /dev/vdb1 # Check the UUID
/dev/vdb1: UUID="89b89119-b1eb-4807-afc0-058d7dc7912c" TYPE="ext4" PARTUUID="7c14697e-01"

# Append the device into /etc/fstab
# tail -n1 /etc/fstab
UUID=89b89119-b1eb-4807-afc0-058d7dc7912c /mnt/test ext4 defaults 0 0

# systemctl daemon-reload # Make sure systemd loads the mnt-test.mount unit

# mount /mnt/test # Mount the device

# mount |grep test # Verify it's mounted correctly
/dev/vdb1 on /mnt/test type ext4 (rw,relatime)

# umount /mnt/test # un-mouint it

# yes | /sbin/mkfs.ext4 /dev/vdb1 # Re-format the partition

# /sbin/blkid /dev/vdb1 # Verify the UUID is changed
/dev/vdb1: UUID="210abcaf-4c5f-45ab-83b5-1e7b6142f2bf" TYPE="ext4" PARTUUID="7c14697e-01"

# systemctl restart mnt-test.mount  # Or systemctl daemon-reload 
# Verify the unit fails as below, either failed directly, or failed after timeout
    mnt-test.mount: Job mnt-test.mount/start failed with result 'dependency'.

# mount /dev/vdb1 /mnt/test # Try to mount it
# Verify the unit fails and journal log says:
    kernel: EXT4-fs (vdb1): mounted filesystem with ordered data mode. Opts: (null)
    systemd[1]: mnt-test.mount: Unit is bound to inactive unit dev-disk-by\x2duuid-89b89119\x2db1eb\x2d4807\x2dafc0\x2d058d7dc7912c.device. Stopping, too.
    systemd[1]: Unmounting /mnt/test...
    systemd[2567]: mnt-test.mount: Succeeded.
    systemd[1]: mnt-test.mount: Succeeded.
    systemd[1]: Unmounted /mnt/test.
```

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.

**Comment by leiyu-bytedance** [comment]
I just upgraded to systemd-246 on Debian 10 (buster-backports) and confirm that the same issue occurs on systemd 246 as well.

@poettering Could you re-open this issue? I could add the above information in the issue's description as well.
