### ISSUE TITLE
Recent hwdb match cleanups adding ":*" break many matches

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#17499]
**systemd version the issue has been seen with**
master

I already added a few comments about this to the commit causing the issue commit c0443b97b71d5f70a0622061f589307bec5502c6.

To be sure this gets fixed I'm also filing this issue. As explained in more details in the comments added to the commit, this commit at least breaks hwdb matches for all entries in hwdb.d/60-autosuspend.hwdb and for all evdev:input: style entries in hwdb.d/60-keyboard.hwdb.

I believe that the best solution is to revert commit c0443b97b71d5f70a0622061f589307bec5502c6

**Comment by poettering** [comment]
Hmm, so I figure the commit is wrong for input-style modalias, but the fixes for the DMI ones should be OK, right?

**Comment by jwrdegoede** [comment]
Yes for DMI modalias matches it should be fine. DMI modalias-es end in `:cvrFOO:` there are some instances in commit c0443b97b71d5f70a062 changing those to:  `:cvrFOO:*` but I assume that this being shell-glob style matching that the `*` will also match 0 chars and then this should be fine.

Note that it is not just the `input:b####v####p####*` input-modalias matches which are being broken it is also usb modalias in `usb:v####p####*` style which are being broken and I did not check any others.

Still keeping the DMI modalias changes (and only those) should be fine.
