### ISSUE TITLE
systemd-nspawn: opt-out from seccomp to improve container startup latency

### ISSUE THREAD

**Issue by jkartseva** [systemd/systemd#17504]
Container startup latency can be critical for some realtime applications. Having seccomp library linked makes even the simplest payload, e.g. `true` run hundreds of milliseconds.

In the test set up `Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz` x  1 CPU core x Fedora 31 x `5.3.7-301.fc31.x86_64` kernel.

```
for i in $(seq 0 4); do echo "-$(date +%s%N)+$(sudo build/systemd-nspawn -D / --volatile=yes --register=no --keep-unit -q "true" && date +%s%N)" | bc; done
110676429
119882807
124630593
111842131
113331488
```

`perf` shows seccomp among top CPU consumers:
```
    20.47%  systemd-nspawn  libseccomp.so.2.5.0       [.] 0x0000000000009680
     7.44%  systemd-nspawn  libseccomp.so.2.5.0       [.] 0x0000000000009684
     6.98%  systemd-nspawn  libc-2.30.so              [.] __strcmp_avx2
     6.05%  systemd-nspawn  libseccomp.so.2.5.0       [.] 0x0000000000010cf8
     3.72%  systemd-nspawn  libc-2.30.so              [.] _int_free
     2.33%  systemd-nspawn  libc-2.30.so              [.] malloc
     1.86%  systemd-nspawn  libseccomp.so.2.5.0       [.] 0x0000000000009697
     1.40%  systemd-nspawn  [kernel.kallsyms]         [k] copy_mount_options
```
 Same set up but with seccomp disabled, latency drops down to tens of milliseconds:
```
yum remove libseccomp-devel
# Rebuild systemd-nspawn
for i in $(seq 0 4); do echo "-$(date +%s%N)+$(sudo build/systemd-nspawn -D / --volatile=yes --register=no --keep-unit -q "true" && date +%s%N)" | bc; done
71652078
77380866
70011649
66086714
75647526
```
`perf`:
```
     7.69%  systemd-nspawn  [kernel.kallsyms]         [k] copy_mount_options
     5.13%  systemd-nspawn  [kernel.kallsyms]         [k] _raw_spin_unlock_irqrestore
     5.13%  systemd-nspawn  [kernel.kallsyms]         [k] copy_page_regs
     5.13%  systemd-nspawn  [kernel.kallsyms]         [k] memcg_kmem_get_cache
     2.56%  systemd-nspawn  [kernel.kallsyms]         [k] __d_lookup
     2.56%  systemd-nspawn  [kernel.kallsyms]         [k] __insert_inode_hash
     2.56%  systemd-nspawn  [kernel.kallsyms]         [k] __mod_node_page_state
```

The solution would be to make seccomp opt-out. Currently it is enabled if `HAVE_SECCOMP` macro if set (which is decided in compile time) and if runtime dependencies are satisfied.
Make it possible to disable seccomp for nspawn container even if runtime dependencies are satisfied, e.g. by having an option in `.nspawn` config and making [seccomp](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn-settings.h#L221) setting conditional.

**Comment by poettering** [comment]
There has been a request to be able to turn off seccomp logic for other reasons already.

**Comment by deliciouslytyped** [comment]
@poettering just checking, since I'm not intimately familiar with a lot of systemd things: I vaguely recall from an unrelated debugging attempt that systemd does some kind of RPC stuff all over the place, so will setting this env var on a command that is run do the thing a user expects? I.e. disable seccomp on only that nspawn container and such?
