### ISSUE TITLE
possible integer overflow in journal/sd-journal.c: real_journal_next_skip

### ISSUE THREAD

**Issue by ente76** [systemd/systemd#17502]
**systemd version the issue has been seen with**
 > git HEAD

**Used distribution**
 > N/A

**Linux kernel version used** (`uname -a`)
 > N/A

**CPU architecture issue was seen on**
 > N/A

**Expected behaviour you didn't see**
 > N/A

**Unexpected behaviour you saw**
 > integer overflow if API function sd_journal_next_skip is called with a skip parameter at value 9,223,372,036,854,775,808 or higher if the journal is large enough to support such . Line 808 will run into an integer overflow. The return value of your functions is defined to be positive on success and negative on error. With the integer overflow one may receive a negative value on a successful operation.

**Steps to reproduce the problem**
 > call function sd_journal_next_skip with a skip parameter at value 9,223,372,036,854,775,808 on a very large journal. I could not test it - my journal is too small and I am not bored enough to artificially blow up my journal to the required extend.

**Comment by yuwata** [comment]
Fix is waiting in #17550.
