### ISSUE TITLE
resolved: reload dnssd units?

### ISSUE THREAD

**Issue by tmm1** [systemd/systemd#17503]
**Is your feature request related to a problem? Please describe.**

I would like to add/remove dnssd files from `/run/systemd/dnssd` and have resolved pick up the changes without a restart

**Describe the solution you'd like**

Ideally the daemon can inotify watch for changes, but a signal to tell it to reload dnssd configuration would also be enough.

Is there a free signal available? Does it make sense to overload SIGUSR1/2 to add this behavior?

Or would it be better to use inotify?

Another possibility is to add a method to the dbus api

I am happy to put together a PR here but am looking for some guidance on what approach to use.

cc @rojkov

**Comment by elyscape** [comment]
Relatedly, it would be nice if the D-Bus API supported updating services.

**Comment by eworm-de** [comment]
A vote from me... This would be nice to have. Restarting the service to make it reread dnssd units is really ugly.

**Comment by travisghansen** [comment]
Yeah, took me a bit to discover this wasn't happening automatically. Looking forward to a proper solution!

**Comment by travisghansen** [comment]
@yuwata can we get a short description of the implementation? Do we need to invoke a command or was a fs listener implemented?

Thanks!

**Comment by yuwata** [comment]
@travisghansen Please use `systemctl reload systemd-resolved.service` to reload config.
