### ISSUE TITLE
systemd-networkd: Intermittent failure to bring up network on Raspberry Pi 4

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#17509]
**systemd version the issue has been seen with**
 > systemd 246 (246.6-1.1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch ARM aarch64 

**Linux kernel version used** (`uname -a`)
 > uname -a
Linux workbench64 5.9.2-1-ARCH #1 SMP Thu Oct 29 07:17:39 EDT 2020 aarch64 GNU/Linux

**CPU architecture issue was seen on**
 > Raspberry Pi 4

**Expected behaviour you didn't see**
 > systemd-networkd should consistently bring up the wired network on boot.

**Unexpected behaviour you saw**
 > systemd-networkd fails to consistently bring up the wired network on boot.

**Steps to reproduce the problem**
 > Boot the system with the following `/etc/systemd/network/eth.network`
```
[Match]
Name=eth*

[Network]
DHCP=yes
DNSSEC=no
```

The bug manifests itself intermittently.  Some boots are fine, others are not.  When booted into a state when the bug is experienced, systemd-networkd reports:
```
# systemctl status systemd-networkd
● systemd-networkd.service - Network Service
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2020-10-03 14:13:07 EDT; 4 weeks 1 days ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 307 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 4443)
     Memory: 2.4M
     CGroup: /system.slice/systemd-networkd.service
             └─307 /usr/lib/systemd/systemd-networkd

Oct 03 14:13:06 workbench64 systemd[1]: Starting Network Service...
Oct 03 14:13:07 workbench64 systemd-networkd[307]: Enumeration completed
Oct 03 14:13:07 workbench64 systemd-networkd[307]: eth0: IPv6 successfully enabled
Oct 03 14:13:07 workbench64 systemd-networkd[307]: eth0: Could not bring up interface: No such device
Oct 03 14:13:07 workbench64 systemd[1]: Started Network Service.
```

Yet, eth0 is clearly present:
```
% ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
```

It is possible to manually restart systemd-networkd when the machine is in this state.  Doing so allows systemd-networkd to bring up the interface as expected.  This is problematic since many users run these boxes in headless configurations.

**Additional data**
* [dmesg](https://gist.github.com/graysky2/6b68cf3baed4987c6206cf23c72a15e3)
* [journalctl  -b](https://gist.github.com/graysky2/1045d8308982263e0755754dc3c043f4)

**Comment by poettering** [comment]
```
…
[  +0.006384] bcmgenet fd580000.ethernet eth0: failed to connect to PHY
…
```

That's from your dmesg. Contact driver people. If your driver can't talk to the PHY, something is fucked looong before this reaches userspace.

**Comment by graysky2** [comment]
Thanks, Lennart.  Perhaps releated (although slightly different): https://github.com/raspberrypi/linux/issues/3108

**Comment by aguegu** [comment]
For those who run into the same problem. check here:

https://archlinuxarm.org/forum/viewtopic.php?f=67&t=14806#p64938
https://github.com/raspberrypi/linux/issues/3108#issuecomment-723550749
