### ISSUE TITLE
Configuration option to limit the number of coredumps per daemon

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [systemd/systemd#17515]
**Is your feature request related to a problem? Please describe.**
An user configurable option to control the amount of core dumps preserved per daemon in the storage.

**Describe the solution you'd like**
Currently, we have only size based limit on the core dump storage, but we don't have any count based coredump file limit.  Hence we prefer to have a configuration to limit the total number of coredump and another configuration to limit the number of core dumps per daemon.

**Describe alternatives you've considered**
Having a Cron script to monitor and remove the older core dumps when the total and per daemon limit is reached.

**Comment by poettering** [comment]
I don't get this? "coredumps per process"? every process can coredump at most once. Hence limit on coredumps per process is either 0 or 1, anyway?

What are you precisely asking for? Do you mean *per user*?

**Comment by Dinesh-Ramakrishnan** [comment]
Sorry, I meant the coredump limit per daemon.
For example, If the systemd-journald daemon is crashing multiple times, we have multiple core.systemd-journal....xz  files.  We would like to limit such coredumps.
