### ISSUE TITLE
repart: support verity root devices

### ISSUE THREAD

**Issue by dm0-** [systemd/systemd#17519]
**Is your feature request related to a problem? Please describe.**
My root file system is on verity, which causes the `systemd-repart` service to fail to find the GPT disk (with v246).

**Describe the solution you'd like**
While root-on-verity can have odd/complex backing devices, I think it is reasonable to support the basic case when the verity backing device is a regular GPT partition.  (Most other systemd tools support GPT layouts for a root partition and a verity hash partition, so it makes sense for repart to understand this as well.)  A simple solution could be to check if the verity data device (fifth item in the device mapper table) is a GPT partition, and proceed as if that was the root device, or fail otherwise.

**Describe alternatives you've considered**
I slapped together a generator as a workaround until I can look into a proper implementation:
```bash
#!/bin/bash -eu
table=( $(dmsetup table "$(findmnt --noheadings --output=source --raw /)") )
[[ ${table[2]} == verity ]] || exit 0  # not verity root
test -e "/sys/dev/block/${table[4]}/partition" || exit 0  # not partitioned
part=$(sed -n s,^DEVNAME=,/dev/,p "/sys/dev/block/${table[4]}/uevent")
dev=/dev/$(lsblk --nodeps --noheadings --output=PKNAME "$part")
test -b "$dev" || exit 0  # failed to find the partition's parent device
unit=$(systemd-escape --path "$dev").device
mkdir -p /run/systemd/system/systemd-repart.service.d
echo > /run/systemd/system/systemd-repart.service.d/verity.conf "\
# Specify the backing disk of the verity root device.
[Unit]
After=$unit
Wants=$unit
[Service]
ExecStart=
ExecStart=/usr/bin/systemd-repart --dry-run=no $dev"
```

**Comment by poettering** [comment]
hmm, so I understand you are saying that repart is not able to detect the backing root device for you? what is the error you see?

There's actually code in place to deal with verity root devices. Only works if verity data and actual fs are both on the same backing block device though. 

Can you describe precisely what error you see, and how your devices are stacked? Which fs you use? which systemd version? which distro version? what kind of disk label?

**Comment by dm0-** [comment]
I believe the specific error from systemd-repart was `Failed to determine backing device ...` in the journal, but I can verify later today.  I will need to generate a new image to make it fail again.

For the other info, my current setup appends verity hashes to the file system, so they're both actually on the same partition on a regular GPT-formatted disk (i.e. the table uses the same device for both partitions and specifies the hash device offset).  I've used both squashfs and EROFS for the root file system with verity.  It's systemd v246.  My current focus is using Gentoo as the distro to generate minimal self-formatting chromebook images, but I can try other distros later today when I verify the error message.

**Comment by poettering** [comment]
hmm, i tested the code only against verity images that using two distinct partitions for payload and verity info. maybe there's some problem with handling the case with the same backing partition block device.

Hmm, how is the precise layout of devices done in this case? i.e. the offset to the verity data, how is that configured? is there maybe some other DM target plugged in between? how does the slaves/ dir for the resulting attached block device look like?

**Comment by dm0-** [comment]
I built some test images yesterday, and I think I see what's happening now.  It seems that the issue was actually being fixed by the unit ordering from my generator (which I just added randomly) rather than specifying the device.  The chromebook still fails with the error `Failed to determine the backing device of /dev/mmcblk0: No such file or directory` if I remove the ordering, but test VMs succeed with the same verity setup and no generator.  The service succeeded on the chromebook when I restarted it later via a debug shell, which seems to confirm a timing problem.

Sorry for my confusion here.  My initial testing of repart.d succeeded in mutable VMs, but when I built a chromebook image with verity and got a `Failed to determine backing device` failure (and skimmed `repart.c` and saw no references to verity), I assumed verity was the problem rather than it being a hardware difference.  Then my attempt at a workaround fixed it for an unrelated reason.

To answer your other questions, the offset is configured in the table given to either `dm-mod.create` on the kernel command-line or `dmsetup create --concise` (if I have a busybox initramfs configured), e.g. `root,,,ro,0 675128 verity 1 PARTUUID=dbe189fd-a174-4bf2-a519-b404e7ac6d3e PARTUUID=dbe189fd-a174-4bf2-a519-b404e7ac6d3e 4096 4096 84391 84392 sha256 bfd6ca6546457c1be5b58901eb7a5224e300481d726db8b04efe2e6f3675b198 dea3b9e4e5b27d3d25c55031f8b29ab6d9fde924e5acffdc5d8043d9cbc96b02 2 root_hash_sig_key_desc verity:root`.  The offset itself is just the size of the filesystem since the verity hash block was directly appended.  There is no other device mapper usage; if I use `dm-mod.create` with no initramfs, I'll also have `root=/dev/dm-0` so there are no intermediate devices.  (I don't think my chromebook supports loading an initrd, so I have to build an initramfs into the kernel to handle userspace stuff like adding the roothash signature to the keyring.  Since that's annoying, sometimes I build a kernel with no initramfs and boot without the optional signature.)  The `/sys/block/dm-0/slaves` directory contains only a symlink `mmcblk0p2` to `../../../../platform/ff0c0000.mmc/mmc_host/mmc0/mmc0:1234/block/mmcblk0/mmcblk0p2`.

So I think this can be closed for now.  Maybe I'll eventually be able to put more time into this and come up with a proper fix for the device ordering.

**Comment by dm0-** [comment]
Just noting that I've since tried it on a different VM configuration using virtio, and it failed with `Failed to determine backing device of /: No such file or directory` again.  As with the chromebook, it worked when `systemd-repart.service` was started at a later time in boot.

So it looks like this isn't specific to one type of hardware.  It succeeded in a VM when the root device was `/dev/sda`, and it failed when the root device was `/dev/mmcblk0` and `/dev/vda`.
