### ISSUE TITLE
PulseSecure VPN does not work with systemd-resolved

### ISSUE THREAD

**Issue by anatol** [systemd/systemd#17512]
**systemd version the issue has been seen with**
246.6 at Arch Linux

**Used distribution**
Arch Linux, up-to-date

**Linux kernel version used** (`uname -a`)
5.9.3-arch1-1

**CPU architecture issue was seen on**
x86_64

My company recently moved to PulseSecure VPN. It provides proprietary closed-source client that sets up a VPN connection. Some people use this tool at Fedora with `NetworkManager` and say the tools works fine.

I am trying to use it at Arch with `systemd-network` and `systemd-resolved`. The tool seems sets up a VPN connection. But it does not configure DNS routing correctly. So I have to configure DNS manually like this:

```
$ cat /etc/systemd/resolved.conf.d/mycompany.conf   
[Resolve]
DNS=162.200.100.12
Domains=mycompany.corp mycompany.com net.mycompany.net local.mycompany.com mycompany.biz
LLMNR=no
```
and then `sudo systemctl restart systemd-resolved.service`. i.e. the DNS configuration and service restart has to be done manually. I would love to find a better automatic way to configure DNS at the VPN connection event.

Taking into account that some folks were able to make it working with `NetworkManager` flawlessly I believe that `pulsesecure` UI tool tries to send this DNS information to the system but `systemd-resolved` does not receive this information for some reason. I am looking for a way to make `systemd-resolved` with `pulseUI` without manual intervention.

I am eager to provide you as much debug information as possible but I do not know where to start debugging this issue.

**Comment by poettering** [comment]
there's no standardized logic on Linux how connection handlers can propagate DNS server info into the system. Some distros know the "resolvconf" tool, and systemd actually provides command line compat with that, when you invoke "resolvectl" via such an alias. 

I am not sure what "pulsevpn" does to propagate DNs info into NM? Maybe it calls its D-Bus interfaces directly? We have similar interfaces. systemd's "resolvectl" provides a command line interface to that (and the "resolvconf" alias interface it provides, does too). You need to figure out what this pulsevpn thing actually precisely does with the DNS info...

If pulsevpn talks to NM: NM can propagate info on to resolved. Check NM docs how that is configured.

**Comment by poettering** [comment]
#17678 now contains detailed info how to hook up VPNs with resolved. I think this is all we can do from our side: document exactly what to do.

**Comment by Spikhalskiy** [comment]
PulseSecure 22.7 works correctly with systemd-resolved and doesn't just overwrite `/etc/resolv.conf` anymore like 22.5 and below were doing.
