### ISSUE TITLE
TEST-56-OOMD consistently fails on kernel 5.9.x

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#17533]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.3-arch1-1

**CPU architecture issue was seen on**
 > x86_64

In my still ongoing efforts to get kernel > 5.7.12 to CentOS CI I stumbled upon an issue with the `TEST-56-OOMD`, which started failing consistently since kernel 5.9.x (I'm not not sure about the exact version). Given the results it looks like the `testsuite-56-testbloat.service` is not killed when it supposed to be:

```
[ 3959.326758] testsuite-56.sh[26]: + sleep 15
[ 3970.562761] testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3970.562761] testsuite-56-slowgrowth.sh[35]: mem usage 20434944
[ 3974.328470] testsuite-56.sh[190]: ++ date -u +%s
[ 3974.341013] testsuite-56.sh[26]: + [[ 1604606526 -le 1604606525 ]]
[ 3974.341013] testsuite-56.sh[26]: + systemctl status testsuite-56-testbloat.service
[ 3974.346018] testsuite-56.sh[191]: ● testsuite-56-testbloat.service - Create a lot of memory pressure
[ 3974.346018] testsuite-56.sh[191]:      Loaded: loaded (/usr/lib/systemd/tests/testdata/units/testsuite-56-testbloat.service; static)
[ 3974.346018] testsuite-56.sh[191]:      Active: active (running) since Thu 2020-11-05 19:57:05 UTC; 5min ago
[ 3974.346018] testsuite-56.sh[191]:    Main PID: 35 (bash)
[ 3974.346018] testsuite-56.sh[191]:       Tasks: 2 (limit: 9509)
[ 3974.346018] testsuite-56.sh[191]:      Memory: 2.0M (high: 2.0M)
[ 3974.346018] testsuite-56.sh[191]:         CPU: 4min 52.791s
[ 3974.346018] testsuite-56.sh[191]:      CGroup: /testsuite.slice/testsuite-56.slice/testsuite-56-workload.slice/testsuite-56-testbloat.service
[ 3974.346018] testsuite-56.sh[191]:              ├─ 35 bash /usr/lib/systemd/tests/testdata/units/testsuite-56-slowgrowth.sh
[ 3974.346018] testsuite-56.sh[191]:              └─188 bash /usr/lib/systemd/tests/testdata/units/testsuite-56-slowgrowth.sh
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:03 systemd-testsuite testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:03 systemd-testsuite testsuite-56-slowgrowth.sh[35]: mem usage 19918848
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:18 systemd-testsuite testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:18 systemd-testsuite testsuite-56-slowgrowth.sh[35]: mem usage 20402176
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:32 systemd-testsuite testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:32 systemd-testsuite testsuite-56-slowgrowth.sh[35]: mem usage 20525056
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:47 systemd-testsuite testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:01:47 systemd-testsuite testsuite-56-slowgrowth.sh[35]: mem usage 20611072
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:02:02 systemd-testsuite testsuite-56-slowgrowth.sh[35]: target 107880448
[ 3974.346018] testsuite-56.sh[191]: Nov 05 20:02:02 systemd-testsuite testsuite-56-slowgrowth.sh[35]: mem usage 20434944
[ 3974.347597] testsuite-56.sh[26]: + exit 42
[ 3974.357340] sh[192]: + systemctl poweroff --no-block
[ 3974.366263] systemd-logind[23]: System is powering down.
[ 3974.672101] systemd-journald[16]: Journal stopped
```

It doesn't appear to be a flake, since it happened in every test run in the last ~two weeks.

Full journal: [system.journal.tar.gz](https://github.com/systemd/systemd/files/5501357/system.journal.tar.gz)
Console log: [TEST-56-OOMD_console_log.log](https://github.com/systemd/systemd/files/5501358/TEST-56-OOMD_console_log.log)

/cc @anitazha

**Comment by mrc0mmand** [comment]
Quick udpate: I had to disable this test in the Arch part of CentOS CI, so I could finally bump kernel to 5.9.x.

Also, the QEMU part of this test is skipped by default, as the test requires swap, but the VM created by the test's setup script doesn't have any - that shouldn't be hard to fix.

**Comment by anitazha** [comment]
https://github.com/torvalds/linux/commit/e22c6ed90aa91abc08f107344428ebb8c2629e98 removed the "feature" where memory limits counted towards pressure (unless it results in direct reclaim). I was using that to generate fake pressure in the test so... I guess I need to generate some real pressure or lower the threshold

**Comment by anitazha** [comment]
Also I think it's okay to not set up swap for the QEMU portion; I'm going to update oomd so that swap is not a hard requirement and it would be good to test that killing generally works without swap.
