### ISSUE TITLE
systemd-nspawn --bind-ro option results in empty file remaining in used filesystem root after exiting container

### ISSUE THREAD

**Issue by Downloading69** [systemd/systemd#17536]
**systemd version the issue has been seen with**
 > systemd 246

**Used distribution**
 > Manjaro

**Linux kernel version used** (`uname -a`)
 > 5.9.3-1-MANJARO

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > sudo systemd-nspawn --bind-ro=/usr/bin/binary -D directory/
When exiting this container, an empty file remains at directory/usr/bin/binary

**Unexpected behaviour you saw**
 > When exiting the container, no remains of the --bind-ro files should be left in the filesystem directory/

**Steps to reproduce the problem**
 > 
1. Spawn container
`sudo systemd-nspawn --bind-ro=/usr/bin/binary -D directory/`
2. Exit container
3. Check directory/:
```
ls -al directory/usr/bin/binary
-rw-r--r-- 1 root root 0 Nov  6 14:59 directory/usr/bin/binary --> **_empty file that should not be there after exiting container_**
```

**Comment by poettering** [comment]
Hmm, I figure we should document the behaviour the way it is, to make this clear. We cannot really safely provide what you are asking for: containers can be aborted anytime by the kernel, for example when PID 1 of the container is killed. In that case the mount namespace of the container is destroyed automatically by the kenel, and that's a good thing. But if so, we have no time to unlink any inodes we used for mount points.

i.e. such clean-ups could never be robust, and I am not convinced we really should do them then. Having the kernel be able to destroy a running container safely is an inherently good thing and requiring userspace cleanup of the image itself is not a good thing. or to say this differently: a container image should stay in order even when things are aborted suddenly. But if we are supposed to clean-up an image after use, then things wouldn't be robust towards that anymore.

The fact that nspawn can create the inode to mount over for you is mostly a convenience thing, it should not be considered a replacement for "overlaying" file systems, i.e. magically making additional files appear inside some other dir. For that the `--overlayfs=`option is almost definitely the better choice.

Anyway, let's turn this into a documentation issue: the docs for `--bind=` should say that we create missing inodes to mount over as convenience feature, but they are not removed again.

**Comment by Downloading69** [comment]
Alright, this makes sense now! Thanks man!
