### ISSUE TITLE
Possbile division by 0 in bus-message.c

### ISSUE THREAD

**Issue by qarmin** [systemd/systemd#17541]
sz is integer, and in else branch(`sz >= 0`) it may have 0 value which will cause division by 0
https://github.com/systemd/systemd/blob/1008f5b069d574ce1ebe18572fda30ac964ba147/src/libsystemd/sd-bus/bus-message.c#L3189-L3209

**Comment by keszybz** [comment]
I'm not sure if this can be hit in practice, but the code does look a bit sloppy. Please submit as PR>

**Comment by yuwata** [comment]
#17549.
