### ISSUE TITLE
Possible usage null pointer in load-fragment.c

### ISSUE THREAD

**Issue by qarmin** [systemd/systemd#17543]
`dot` may be null according to 2 null check, but still is used `dot - i` 

https://github.com/systemd/systemd/blob/a149d4a95eabe39f36e913f0a0ad9c84007b4e4f/src/core/load-fragment.c#L5666-L5670

**Comment by keszybz** [comment]
Please submit as PR.

**Comment by yuwata** [comment]
#17549.
