### ISSUE TITLE
Sd-bus documentation. sd_bus_call man page RETURN VALUE section does NOT mention big difference between sd_bus_call and sd_bus_call_async return

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#17556]
If you look at [the `sd_bus_call` implementation](https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/libsystemd/sd-bus/sd-bus.c#L2299) you can see that it returns from  `sd_bus_error_set_errno` which sets that returns corresponding errno mapped in [`bus-common-errors.c`](https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/libsystemd/sd-bus/bus-common-errors.c#L10).

Example, if you call an Unknown Method the `sd_bus_call`  will return -EBADR. [Man page for `sd_bus_call`](https://github.com/systemd/systemd/blob/df80c98cdece42c6b49f4c9adc45017b0b0582c6/man/sd_bus_call.xml#L99) has only mentions of EINVAL, ECHILD, ENOTCONN, ECONNRESET, ... and no EBADR. There is no mention of this in DESCRIPTION section as well.

[`sd-bus-errors` man page](https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/man/sd-bus-errors.xml#L101) has no information about that as well.

`sd_bus_call_async` only returns  the error local to the function itself and the RETURN VALUE section is correct in this context.

**Comment by igo95862** [comment]
I wonder if there is room for `sd_bus_call2` which has consistent behavior with `sd_bus_call_async`

**Comment by yuwata** [comment]
sd_bus_call(3) states
> If ret_error is not NULL and sd_bus_call() fails (either because of an internal error or because it received a D-Bus error reply), ret_error is initialized to an instance of sd_bus_error describing the error.

Also,
> Returned errors may indicate the following problems:

and the page does not say that no other values are returned from the function.

Maybe, we should mention that the return value may be mapped from bus error name in the `RETURN VALUE` section.

**Comment by igo95862** [comment]
> sd_bus_call(3) states
> 
> > If ret_error is not NULL and sd_bus_call() fails (either because of an internal error or because it received a D-Bus error reply), ret_error is initialized to an instance of sd_bus_error describing the error.

This talks about `ret_error` parameter of the function not return value of the function. Unless you mean that `ret_error` should be checked before checking return value of the `sd_bus_call`. The man page does not say that.

> > Returned errors may indicate the following problems:
> 
> and the page does not say that no other values are returned from the function.

Every page has that.
