### ISSUE TITLE
In socket.c there is no check against OOM after memory allocation

### ISSUE THREAD

**Issue by mehoffer** [systemd/systemd#17552]
As can be seen below there is no check if OOM occurs after memory allocation by `path_make_absolute`

https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/core/socket.c#L1712-L1714

and if OOM happened we would end up with bare assert in function `usbffs_address_create`

https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/core/socket.c#L1219-L1223

Just info as not sure about possibility of hitting OOM here.

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #17554.
