### ISSUE TITLE
/dev/usb/lp1 path is used for usb printers even if only one USB printer is connected

### ISSUE THREAD

**Issue by Potomac** [systemd/systemd#1756]
I use archlinux 64 bits,

since a recent upgrade of systemd ( probably systemd 227 ) I notice a change about the USB printer management in udev,

I have an usb printer canon LBP3000, with the previous versions of systemd it was the path "/dev/usb/lp0" who was used with my canon LBP3000,

but with systemd 227 the path is different, it's "/dev/usb/lp1", this change triggers a problem with my cups configuration for LBP3000, because cups will try to use "/dev/usb/lp0", but this path doesn't exist since systemd 227, the solution for me is to type this commande in order to change the cups configuration : 
ccpdadmin -p LBP3000 -o /dev/usb/lp1

I want to know why systemd 227 uses the path "/dev/usb/lp1" instead of "/dev/usb/lp0" even when only one printer is used ? ( I don't have a second USB printer )

is this change ( lp1 instead of lp0 ) is intentional, or is it a bug ?

**Comment by gregkh** [comment]
This sounds like a kernel issue, are you sure you don't have another printer recognized by the usb subsystem now?

**Comment by Potomac** [comment]
I use kernel 4.2.5,

I don't have another printer, and the usb subsystem doesn't show a second printer, in /dev/usb I see only 2 files : hiddev0 and lp1

$ lsusb
Bus 004 Device 005: ID 04a9:266a Canon, Inc. CAPT Device
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 002: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 0463:ffff MGE UPS Systems UPS
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

# lpinfo -v

network lpd
network https
network ipps
network ipp
network http
direct ccp
network socket
network smb
direct usb://Canon/LBP3000?serial=0000A1551Krc

**Comment by gregkh** [comment]
What does the kernel log show?  Did the device disconnect itself and then add itself back?

Did you change kernel versions when you noticed this change or only just changed systemd?

**Comment by Potomac** [comment]
in dmesg I see no problems, usb printer add itself when I connect the printer, and when I disconnect the printer the lp1 file is removed from /dev/usb,

but I made progress, I found that if I disconnect my battery backup device (MGE UPS PROTECTION CENTER 645 ) by removing the USB cable then the bug is gone, the path "/dev/usb/lp0" is used for my USB printer,

and if I reconnect my battery backup device ( usb cable ) then the bug is back, "/dev/usb/lp1" will be used for my USB printer,

I tried to downgrade kernel, systemd packages to the previous versions ( 227 --> 224,  kernel 4.2.5 --> 4.1.4 ) : this weird bug is still here,

I didn't notice this bug because my battery backup device was not plug to my PC ( usb cable ), but some days ago I have plugged my battery backup device to my PC and that's why I notice now this weird bug, I don't know if systemd is guilty or if it's a kernel bug

**Comment by gregkh** [comment]
systemd has nothing to do with this, I suggest sending your kernel log messages to the linux-usb@vger.kernel.org mailing list and the usb kernel developers there can help you out.  Odds are, your ups device has a usb to parallel port device in it, which causes the device ordering to be different.  I'd recommend using some sort of persistent name for your printer instead of relying on "lp0" to be stable (hint, it isn't going to be).  Perhaps make a rule based on the serial number of your printer?

**Comment by Potomac** [comment]
yes the solution is to create an udev rule like this : 
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04a9", ATTRS{idProduct}=="266a", ATTRS{serial}=="0000A1551Krc", SYMLINK+="usb/lbp3000"

this rule will create a symbolic link "/dev/usb/lbp3000", 

then I will setup my cups configuration like this : 

ccpdadmin -p LBP3000 -o /dev/usb/lbp3000
