### ISSUE TITLE
MOUNT_MOUNTING_DONE triggers assert in mount_start, core generated.

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#17570]
**systemd version the issue has been seen with**
 > systemd-246

**Used distribution**
 > ...

**Linux kernel version used** (`uname -a`)
 > …

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > No core generated.

**Unexpected behaviour you saw**
 > Core generated in mount_start().

**Steps to reproduce the problem**
 >  Executing `udevadm trigger -c remove` and `udevadm trigger -c add` in an infinite loop.

**Comment by Geass-LL** [comment]
(gdb) bt
#0  0x0000ffffb4eea508 in kill () from /lib64/libc.so.6
#1  0x0000aaaab0c685bc in crash (sig=6) at ../src/core/main.c:185
#2  <signal handler called>
#3  0x0000ffffb4eea200 in raise () from /lib64/libc.so.6
#4  0x0000ffffb4eeb5ac in abort () from /lib64/libc.so.6
#5  0x0000ffffb5330e60 in log_assert_failed_realm (realm=realm@entry=LOG_REALM_SYSTEMD, text=text@entry=0xaaaab0d39a88 "IN_SET(m->state, MOUNT_DEAD, MOUNT_FAILED)",
    file=file@entry=0xaaaab0d39770 "../src/core/mount.c", line=line@entry=1065, func=func@entry=0xaaaab0d38eb0 <__PRETTY_FUNCTION__.19539> "mount_start") at ../src/basic/log.c:806
#6  0x0000aaaab0cfe61c in mount_start (u=0xaaaae38c1ff0) at ../src/core/mount.c:1065
#7  0x0000aaaab0cd0d24 in unit_start (u=u@entry=0xaaaae38c1ff0) at ../src/core/unit.c:1831
#8  0x0000aaaab0c87e34 in job_perform_on_unit (j=0xffffed6fe5e8, j@entry=0xffffed6fe618) at ../src/core/job.c:533
#9  0x0000aaaab0c8ae80 in job_run_and_invalidate (j=<optimized out>) at ../src/core/job.c:597
#10 0x0000aaaab0ca1ec0 in manager_dispatch_run_queue (source=<optimized out>, userdata=0xaaaae37eca20) at ../src/core/manager.c:2058
#11 0x0000ffffb53b8060 in source_dispatch (s=s@entry=0xaaaae37e5b40) at ../src/libsystemd/sd-event/sd-event.c:3227
#12 0x0000ffffb53b9ea4 in sd_event_dispatch (e=e@entry=0xaaaae37e5860) at ../src/libsystemd/sd-event/sd-event.c:3602
#13 0x0000ffffb53ba128 in sd_event_run (e=0xaaaae37e5860, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3659
#14 0x0000aaaab0ca771c in manager_loop (m=0xaaaae37eca20) at ../src/core/manager.c:2828
#15 0x0000aaaab0c6472c in invoke_main_loop (ret_error_message=0xffffed6fe8b0, ret_switch_root_init=<synthetic pointer>, ret_switch_root_dir=<synthetic pointer>, ret_fds=0xffffed6fe8c0,
    ret_shutdown_verb=<synthetic pointer>, ret_retval=<synthetic pointer>, ret_reexecute=<synthetic pointer>, m=0xaaaae37eca20) at ../src/core/main.c:1653
#16 main (argc=5, argv=0xffffed6feb28) at ../src/core/main.c:2440
(gdb) f 6
#6  0x0000aaaab0cfe61c in mount_start (u=0xaaaae38c1ff0) at ../src/core/mount.c:1065
1065            assert(IN_SET(m->state, MOUNT_DEAD, MOUNT_FAILED));
(gdb) info locals
m = 0xaaaae38c1ff0
r = <optimized out>
__PRETTY_FUNCTION__ = "mount_start"
(gdb) p m->meta->id
$3 = 0xaaaae38c02f0 "boot.mount"
(gdb) p m->state
$4 = MOUNT_MOUNTING_DONE
