### ISSUE TITLE
systemd-inhibitor in mode delay doesn't delay suspend

### ISSUE THREAD

**Issue by theGeekyLad** [systemd/systemd#17579]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Arch Linux 

**Linux kernel version used** (`uname -a`)
 > 5.9.6-arch1-1

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > The system was not supposed to suspend for a delay of 60s in `logind.conf`. 

**Unexpected behaviour you saw**
 > The system suspended.

**Steps to reproduce the problem**
> - Edit `/etc/systemd/logind.conf` and set `InhibitDelayMaxSec=60` for a 60s delay
> - Run a sleep inhibitor in delay mode as `sudo systemd-inhibit --mode=delay --what=sleep sleep 2m`
> - Open another terminal and run `systemctl suspend`

**Comment by poettering** [comment]
did you run "systemctl suspend" as root?

**Comment by poettering** [comment]
Closing due to lack of response
