### ISSUE TITLE
systemd-resolved updates resolv.conf every time an IPv6 RA with RDNSS is received, even if the nameservers are unchanged

### ISSUE THREAD

**Issue by andatche** [systemd/systemd#17577]
**systemd version the issue has been seen with**

> 246.6-2

**Used distribution**

> Debian 11 Bullseye

**Linux kernel version used** (`uname -a`)

> Linux unida 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux

**CPU architecture issue was seen on**

> amd64

**Unexpected behaviour you saw**

systemd-resolved rewrites `/run/systemd/resolve/resolv.conf` every time an IPv6 RA containing the RDNSS option is received, even if the nameservers are unchanged from the previous configuration.

This causes other process which watch `resolv.conf` (e.g. dnsmasq for CNI/podman or libvirt) to  reload their configuration unnecessarily, spamming the journal.

```
Nov 11 22:08:23 unida dnsmasq[1131]: reading /etc/resolv.conf
Nov 11 22:08:23 unida dnsmasq[1131]: using only locally-known addresses for domain dns.podman
Nov 11 22:08:23 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:08:23 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:08:23 unida dnsmasq[1131]: reading /etc/resolv.conf
Nov 11 22:08:23 unida dnsmasq[1131]: using only locally-known addresses for domain dns.podman
Nov 11 22:08:23 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:08:23 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:16:29 unida dnsmasq[1131]: reading /etc/resolv.conf
Nov 11 22:16:29 unida dnsmasq[1131]: using only locally-known addresses for domain dns.podman
Nov 11 22:16:29 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:16:29 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:16:29 unida dnsmasq[1131]: reading /etc/resolv.conf
Nov 11 22:16:29 unida dnsmasq[1131]: using only locally-known addresses for domain dns.podman
Nov 11 22:16:29 unida dnsmasq[1131]: using nameserver <snip>#53
Nov 11 22:16:29 unida dnsmasq[1131]: using nameserver <snip>#53
```

**Steps to reproduce the problem**

Define a network unit with with `IPv6AcceptRA=yes` configured on an interface connected to a network segment with a router which issues IPv6 RAs with the RDNSS option set.

```
[Match]
Name=eno1

[Network]
IPv6AcceptRA=yes

[IPv6AcceptRA]
UseDNS=yes
```

**Comment by yuwata** [comment]
Fix in resolved side is proposed in #17535. I will work on networkd side after v247 is released.

**Comment by samy-mahmoudi** [comment]
Hi all,

It seems this issue is not fully resolved. Please see https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1891215/comments/4 for more information.

**Comment by yuwata** [comment]
@samy-mahmoudi This issue is fixed in v248. Here is the upstream bug tracker, so backporting the patches to v245 is out of scope. Please contact the downstream.

**Comment by samy-mahmoudi** [comment]
> @samy-mahmoudi This issue is fixed in v248. Here is the upstream bug tracker, so backporting the patches to v245 is out of scope.

I was indeed under the assumption that we were running a version of systemd that included the relevant fixes. Thanks for pointing this out.

> Please contact the downstream.

Done.
