### ISSUE TITLE
sd_bus. Message refrence count between sd_bus_call_async callback and sd_bus_process.

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#17571]
Calling sd_bus_process with second parameter as sd_bus_message** will
put a new message in to that pointer. The man page says that the caller
should unref it ,however, I found out that if you do that it will get
garbage collected before a callback registed with sd_bus_call_async
will get a chance to access it.

Even passing NULL to the second parameter will corrupt callbacks.

Is this documentation issue? Is it correct to refernce the new message
with sd_bus_process and when not touch its refrence count until the
callback has a chance to access it? Does the callback get a new
reference so it should unrefrence it twice?

Tested on version: systemd 246 (246.6-1-arch)

**Comment by igo95862** [comment]
After a bit of testing I found out that callbacks are called from the `sd_bus_process`.

This means it is possible to use `NULL` as a second parameter to `sd_bus_process` but you need to increase the message reference inside callback.

**Comment by poettering** [comment]
I am not sure I grok what you are saying. Can you provide a minimal example C code that is supposed to reproduce the problem?

I am a bit puzzled about this bug report. There is no "garbage collection" in place, we just to simple ref counting.

Are you aware that the message objects passed to message handlers  remain under ownership of the calling code, you are supposed to inc the ref counter if you want to keep a copy. sd_bus_process() otoh returns a message whose ref count is already increased by one, for you, so you own the ref.

**Comment by igo95862** [comment]
> Are you aware that the message objects passed to message handlers remain under ownership of the calling code, you are supposed to inc the ref counter if you want to keep a copy.

This should be added to the man pages. (at least to `sd_bus_call_async')  I had to figure out that on my own.

**Comment by igo95862** [comment]
The initial bug report is confusing because I was confused about internal structure of sd_bus. I did not realize that sd_bus_process dispatches to the callbacks. So somehow not un-referencing in sd_bus_process made the reply messages not lose the message. 


[Reference counting is called a form of garbage collection by wikipedia](https://en.wikipedia.org/wiki/Reference_counting#Garbage_collection)


Now I need to figure out why cancelling callbacks by un-referencing slots seems to leak memory.

**Comment by igo95862** [comment]
I found a paragraph in sd_bus_match_signal_async which is similar. Made a pull request with a fix to man page.
