### ISSUE TITLE
Triggering udev rules based on module loading is racy

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#17586]
When the kernel loads a module it first sends an uevent to udev and then initializes the module. This means that udev can start processing the module uevent before the module is fully initialized.

We happen to mount configfs by listening such uevents and for some reasons it has only started failing with v246:

> [   25.022146] localhost systemd[1]: sys-module-configfs.device: Changed dead -> plugged
> [   25.022219] localhost systemd[1]: sys-kernel-config.mount: Trying to	enqueue job sys-kernel-config.mount/start/fail
> [   25.022251] localhost systemd[1]: Added job sys-kernel-config.mount/start to transaction.
> [...]
> [   25.022533] localhost systemd[1]: sys-kernel-config.mount: Enqueued job sys-kernel-config.mount/start as 562
> [   25.022579] localhost systemd[1]: sys-kernel-config.mount: ConditionPathExists=/sys/kernel/config failed

As you can see, udev and systemd processed the uevent before the kernel finished to initialize the module (configfs).

**Comment by poettering** [comment]
Sounds unfixable unless the kernel gets fixed to tell userspace when modules finished loading, rather than started loading

**Comment by nmorey** [comment]
This has been done this way in the kernel since 2.6 so it won't be necessary that easy to get a fix everywhere.
It is not clear yet if there is a reason for the uevent to be triggered this early.

Also, there is a way to check if the module is actually fully loaded.
Each module has a /sys/module/<mod>/initstate  entry that contains the module state.
It should be "coming" when the module is still under init and "live" once it is fully operational.

**Comment by poettering** [comment]
So what we probably can do is add After=modprobe@configfs.service to the mount unit. This means we'l issue "modprobe" on the kmod once the modprobe is announced to be loaded. Sounds pointless, but given that modprobe only returns after the initialization of the module is complete should fix the issue at hand.

@fbuihuu if you change the .mount unit that way, does that fix things for you?

**Comment by fbuihuu** [comment]
We also need to add `Wants=modprobe@configfs.service` to the mount unit, don't we ?

There are various ways to load the module, modprobe@configfs.service is only one of them.

**Comment by poettering** [comment]
yeah, that's what I meant: After=+Wants=

**Comment by fbuihuu** [comment]
@poettering it seems to do the trick.

**Comment by fbuihuu** [comment]
Hmm wait, actually it doesn't work because modprobe@.service has: `ConditionPathExists=!/sys/module/%I`.

But /sys/module/configfs is created by the kernel before the module is init() is called therefore modprobe@.service can't be used as a synchronization point unless this condition is removed.

Given that we should be sure that a module is fully loaded after `modprobe@.service`, the condition should be removed, no ?

**Comment by poettering** [comment]
yeah i guess
