### ISSUE TITLE
Add knob for vm.swappiness to systemd.resource-control

### ISSUE THREAD

**Issue by Flowdalic** [systemd/systemd#17598]
I wan to set the swappiness for slices via systemd. Currently this appears to be not possible, only for services via something like

```
[Service]
ExecStartPre=/bin/bash -c "/bin/echo 10 > /sys/fs/cgroup/memory/user.slice/memory.swappiness"
```

I would be great if there was a systemd resource control setting, which would allow to specify the swappiness on Units, e.g.

```
[Unit]
Swappiness=10
```

This would users relief from resorting to workarounds like the one described in https://github.com/systemd/systemd/issues/9276#issuecomment-442514543

**Comment by poettering** [comment]
`swapiness` is a cgroupvs1 feature, and it has no counterpart on cgroupsv2. (the new latency stuff is maybe a better replacement though).

At this point we are not going to add new features for cgroupsv1 features, sorry. And the latency stuff is already exposed for cgroupsv2. 

Hope that makes some sense, closing. Sorry!

**Comment by zouppen** [comment]
What is the *new latency stuff* you are referring to, @poettering? Some keyword easier to google would be nice :-)

**Comment by Flowdalic** [comment]
My best guess would be [cgroup v2 io interface files](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#io-interface-files) configuring the swap device. But that appears rather cumbersome, for example as there could be multiple swap device (or even swap files).
