### ISSUE TITLE
Allow fuse in systemd-nspawn containers

### ISSUE THREAD

**Issue by paravoid** [systemd/systemd#17607]
@poettering, in https://github.com/systemd/systemd/issues/2178#issuecomment-165753697 (Dec 2015) wrote:
> fuse is currently not supported in nspawn containers, because the kernel interfaces aren't compatible with namespaces/containers. Or at least they weren't the last time I looked, and leaked information from inside the container to the host. If that changed now we can certainly open that up, too.

and in https://github.com/systemd/systemd/issues/7669#issuecomment-352388204 (Dec 2017) also wrote:
> Well, I'd love to just make fuse available by default, but iirc fuse is still not properly set up for usage in containers, i.e. just making the fuse node available is not safe, as it leaks access on host-side mounts or so, I don't remember the details about that.
> 
> If that changes we should just make FUSE available by default. Until then: you can hack around this already if you are willing to ignore the security implications around this. Just use "--bind=/dev/fuse" on the nspawn cmdline, it knows how to deal with device nodes these days.

Evidently, this has actually changed :) Linux https://github.com/torvalds/linux/commit/da315f6e03988a7127680bbc26e1028991b899b8 (v4.18-rc1); excerpt from the commit message:
> "The most interesting part of this update is user namespace support, mostly done by Eric Biederman. This enables safe unprivileged fuse mounts within a user namespace.

Given `@mount` is already part of the seccomp allow list for nspawn, and even `/sys/fs/fuse/` is exposed, I _think_ that, effectively, this should do it (completely untested):
```diff
diff --git a/src/nspawn/nspawn.c b/src/nspawn/nspawn.c
index 0842731c18..20e34ab9a6 100644
--- a/src/nspawn/nspawn.c
+++ b/src/nspawn/nspawn.c
@@ -2122,6 +2122,7 @@ static int copy_devnodes(const char *dest) {
                 "random\0"
                 "urandom\0"
                 "tty\0"
+                "fuse\0"
                 "net/tun\0";
 
         _cleanup_umask_ mode_t u;
```

#2178 (sshfs) and #6553 (glusterfs) have some real-world use cases. I'm interested in fuse-overlayfs (for podman) myself.

**Comment by Korynkai** [comment]
> Given `@mount` is already part of the seccomp allow list for nspawn, and even `/sys/fs/fuse/` is exposed, I _think_ that, effectively, this should do it (completely untested):
> 
> ```diff
> diff --git a/src/nspawn/nspawn.c b/src/nspawn/nspawn.c
> index 0842731c18..20e34ab9a6 100644
> --- a/src/nspawn/nspawn.c
> +++ b/src/nspawn/nspawn.c
> @@ -2122,6 +2122,7 @@ static int copy_devnodes(const char *dest) {
>                  "random\0"
>                  "urandom\0"
>                  "tty\0"
> +                "fuse\0"
>                  "net/tun\0";
>  
>          _cleanup_umask_ mode_t u;
> ```
@paravoid Uhhh.... And wow does it work....

This one-line, eight-character simple patch is exactly what I needed, even without being tested. Thank you! (Well, err, I guess I just tested it)

Technically our usage case makes significant use of nspawn and we've been having difficulties with everything from filesystem binds with `PrivateUsers=pick`, to any type of remote filesystem. We technically wanted to use GlusterFS for our scenario, but considering it relies on FUSE, this was a significant issue. Now we're able to use GlusterFS without difficulty.

I am curious as to whether any issues (security or otherwise) will occur with this patch, but I am hopeful considering at least we have it working and no longer need to rely on unnecessarily redundant information anymore.

If I come across any issues regarding this patch, I will post another comment. The only one I can think of currently would be where the userspace FUSE tools are not present on the container or host system and the device itself would be unnecessary in that case.  I do hope, however, that the systemd developers (presumably in combination with the kernel developers) inevitably decide upon a preferred solution, but, well, "this'll work for now!" :wink:

**Comment by Korynkai** [comment]
> Given `@mount` is already part of the seccomp allow list for nspawn, and even `/sys/fs/fuse/` is exposed, I _think_ that, effectively, this should do it (completely untested):
> 
> ```diff
> diff --git a/src/nspawn/nspawn.c b/src/nspawn/nspawn.c
> index 0842731c18..20e34ab9a6 100644
> --- a/src/nspawn/nspawn.c
> +++ b/src/nspawn/nspawn.c
> @@ -2122,6 +2122,7 @@ static int copy_devnodes(const char *dest) {
>                  "random\0"
>                  "urandom\0"
>                  "tty\0"
> +                "fuse\0"
>                  "net/tun\0";
>  
>          _cleanup_umask_ mode_t u;
> ```
@paravoid Uhhh.... And wow does it work....

This one-line, eight-character simple patch is exactly what we needed, even without being tested. Thank you! (Well, err, I guess we just tested it)

Technically our usage case makes significant use of nspawn and we've been having difficulties with everything from filesystem binds when our usage case involves `PrivateUsers=pick`, to any type of remote filesystem. We technically wanted to use GlusterFS for our scenario, but considering it relies on FUSE, this was a significant issue. Now we're able to use GlusterFS without difficulty.

I am curious as to whether any issues (security or otherwise) will occur with this patch, but we're hopeful considering at least we have it working and no longer need to rely on unnecessarily redundant data consuming large amounts of disk space anymore.

If we come across any issues regarding this patch, I will post another comment. The only one I can think of currently would be where the userspace FUSE tools are not present on the container or host system and the device itself would be unnecessary in that case.  I do hope, however, that the systemd developers (presumably in combination with the kernel developers) inevitably decide upon a preferred solution, but, well, this should work for now in our systems! Thanks again!

**Comment by paravoid** [comment]
> This one-line, eight-character simple patch is exactly what we needed, even without being tested. Thank you! (Well, err, I guess we just tested it)

Thank you for testing this and reporting back!

> I am curious as to whether any issues (security or otherwise) will occur with this patch, but we're hopeful considering at least we have it working and no longer need to rely on unnecessarily redundant data consuming large amounts of disk space anymore.

The most obvious one is that older kernels (for mainline that's <= 4.17), there was no namespace support for fuse, and this has no version check, which I believe would create an insecure confiugration. In another issue @poettering expressed his preference for guarding a similar feature behind a kernel feature flag, rather than a version check (to account for backports etc.), but I'm not sure what we could check here to conditionally enable this support.

**Comment by poettering** [comment]
If there's no sane way to check for the feature explicitly I figure we could query the fuse minor version  FUSE_KERNEL_MINOR_VERSION) from the device and base things on that.

**Comment by poettering** [comment]
(i.e. the point i am making, if we have to do a version check, then it should be a runtime hceck against the fuse version, and not the kernel. i.e. the more focussed and dynamic the better, since people backport features all the time to older kernels)

Anyway, happy to review/merge a patch for this.

**Comment by iam-TJ** [comment]
I'm investigating how to complete this issue. Apparently it "only" needs a run-time version check on the fuse version, but I've not been able to figure out how that should be done.

   1. link and call into libfuse
   2. direct open of /dev/fuse with a FUSE_INIT check  (out.major > 7 || (out.major == 7 && out.minor >=27))
   3. some other?

Guidance please!

**Comment by paravoid** [comment]
FWIW, I'm not interested in this myself anymore. But as far as I know, the bug still stands.

My personal opinion is that the most reasonable path forward would be for KERNEL_BASELINE_VERSION to be higher than the current one (4.15, 6½ years old at this point), and avoid a runtime check altogether. Perhaps setting the baseline to LTS kernels would be reasonable, which would conveniently place the current minimum at 4.19 ;)

**Comment by LukeShu** [comment]
> I'm investigating how to complete this issue. Apparently it "only" needs a run-time version check on the fuse version, but I've not been able to figure out how that should be done.
> 
> 1. link and call into libfuse
> 
>  2. direct open of /dev/fuse with a FUSE_INIT check  (out.major > 7 || (out.major == 7 && out.minor >=27))
> 
> 3. some other?
> 
> 
> Guidance please!

A demonstration libc-only program that gets the FUSE version:

```c
#define _GNU_SOURCE     /* for asprintf(3gnu) */
#include <errno.h>      /* for errno */
#include <error.h>      /* for error(3gnu) */
#include <fcntl.h>      /* for open(2) and associated flags */
#include <inttypes.h>   /* for uin32_t, PRIu32 */
#include <stdio.h>      /* for printf(3), dprintf(3), asprintf(3gnu) */
#include <stdlib.h>     /* for malloc(3), mkdtemp(3), EXIT_SUCCESS, EXIT_FAILURE */
#include <unistd.h>     /* for read(2), write(2), close(2), getuid(3), getgid(3) */
#include <sys/mount.h>  /* for mount(2), umount(2) */
#include <sched.h>      /* for unshare(2) and associated flags */
#include <string.h>     /* for strdup(3) */
#include <linux/fuse.h> /* for FUSE_INIT, FUSE_MIN_READ_BUFFER, struct fuse_in_header */

/* These 2 strings can be arbitrary values; they are purely cosmetic.  Actually,
 * mount_subtyp being defined at all is optional.  */
#define mount_src "fuse-version"
#define mount_subtyp "fuse-version"

#ifdef mount_subtyp
#  define mount_typ "fuse." mount_subtyp
#else
#  define mount_typ "fuse"
#endif

int main() {
	int fd;
	ssize_t n;
	char *opts;
	char *mount_dst;
	uid_t uid;
	gid_t gid;
	union {
		char unstructured[FUSE_MIN_READ_BUFFER];
		struct {
			struct fuse_in_header header;
			/* Don't use <linux/fuse.h>:`struct fuse_init_in`
			 * because a newer fuse.h might give us a bigger struct
			 * than what an older kernel actually gives us, and that
			 * would break our short-read checks.  */
			struct {
				uint32_t major;
				uint32_t minor;
			} body;
		} structured;
	} req;

	/* Run in a new mount namespace.
	 *
	 * This is important because (1) it allows unprivileged users to sniff
	 * the FUSE version, which is important because systemd-nspawn has an
	 * unprivileged mode; and (2) it prevents against a dangling mount if
	 * for some reason we bail/get-killed before calling unmount().  */

	uid = getuid();
	gid = getgid();
	if (unshare(CLONE_NEWNS|CLONE_NEWUSER) < 0)
		error(EXIT_FAILURE, errno, "unshare");

	fd = open("/proc/self/uid_map", O_WRONLY);
	if (fd < 0)
		error(EXIT_FAILURE, errno, "open /proc/self/uid_map");
	if (dprintf(fd, "0 %d 1", (int)uid) < 0)
		error(EXIT_FAILURE, errno, "write /proc/self/uid_map");
	if (close(fd) < 0)
		error(EXIT_FAILURE, errno, "close /proc/self/uid_map");

	fd = open("/proc/self/setgroups", O_WRONLY);
	if (fd < 0)
		error(EXIT_FAILURE, errno, "open /proc/self/setgroups");
	if (dprintf(fd, "deny") < 0)
		error(EXIT_FAILURE, errno, "write /proc/self/setgroups");
	if (close(fd) < 0)
		error(EXIT_FAILURE, errno, "close /proc/self/setgroups");

	fd = open("/proc/self/gid_map", O_WRONLY);
	if (fd < 0)
		error(EXIT_FAILURE, errno, "open /proc/self/gid_map");
	if (dprintf(fd, "0 %d 1", (int)gid) < 0)
		error(EXIT_FAILURE, errno, "write /proc/self/gid_map");
	if (close(fd) < 0)
		error(EXIT_FAILURE, errno, "close /proc/self/gid_map");

	/* Get a FUSE handle.  */

	fd = open("/dev/fuse", O_RDWR);
	if (fd < 0)
		error(EXIT_FAILURE, errno, "open /dev/fuse");

	mount_dst = mkdtemp(strdup("/tmp/mountpoint.XXXXXX"));
	if (mount_dst == NULL)
		error(EXIT_FAILURE, errno, "mkdtemp");
	if (asprintf(&opts, "fd=%i,rootmode=40000,user_id=0,group_id=0", fd) < 0)
		error(EXIT_FAILURE, errno, "asprintf");
	if (mount(mount_src, mount_dst, mount_typ, 0, opts) < 0)
		error(EXIT_FAILURE, errno, "mount");
	free(opts);

	/* Read version information from the FUSE handle.  */

	n = read(fd, &req.unstructured, sizeof req);
	if (n < 0)
		error(EXIT_FAILURE, errno, "read /dev/fuse");
	if (n < sizeof req.structured.header)
		error(EXIT_FAILURE, 0, "read /dev/fuse: Short read");
	if (req.structured.header.opcode != FUSE_INIT)
		error(EXIT_FAILURE, 0, "expected opcode=%d (FUSE_INIT), got opcode=%"PRIu32,
		      FUSE_INIT, req.structured.header.opcode);
	if (n < sizeof req.structured)
		error(EXIT_FAILURE, 0, "read /dev/fuse: Short read");
	if (req.structured.header.len < sizeof req.structured.body)
		error(EXIT_FAILURE, 0, "FUSE_INIT request body is too small (%"PRIu32" bytes) to store version information (%zu bytes)",
		      req.structured.header.len, sizeof req.structured.body);

	/* Close the FUSE handle.  */

	if (umount(mount_dst) < 0)
		error(EXIT_FAILURE, 0, "umount %s", mount_dst);
	if (rmdir(mount_dst) < 0)
		error(EXIT_FAILURE, 0, "rmdir %s", mount_dst);
	free(mount_dst);
	if (close(fd) < 0)
		error(EXIT_FAILURE, 0, "close /dev/fuse");

	/* Print and return.  */

	printf("kernel fuse version is %"PRIu32".%"PRIu32"\n",
	       req.structured.body.major, req.structured.body.minor);
	return EXIT_SUCCESS;
}
```

**Comment by LukeShu** [comment]
I've prepared a patch that adds the FUSE version check to `nspawn.c`, but I've discovered that @paravoid's patch no longer works with kernel 6.7.4 (I verified this with systemd c61f46fe3142e8b2fee48c845339bd82e29df085, so as to determine that it's a kernel change that broke the patch, not an nspawn change; I had to cherry-pick c29537f39e4f413a6cbfe9669fa121bdd6d8b36f and 7c5b9952c4f6e2b72f90edbe439982528b7cf223 to get it to compile).

**Comment by LukeShu** [comment]
> I verified this with systemd [c61f46f](https://github.com/systemd/systemd/commit/c61f46fe3142e8b2fee48c845339bd82e29df085), so as to determine that it's a kernel change that broke the patch, not an nspawn change

I should have said that I verified with *nspawn* c61f46f; I did not install an older pid1 or anything.

And as for what's different: BPF. It's `BPF_CGROUP_RUN_PROG_DEVICE_CGROUP(type, major, minor, access);` that's rejecting the `open()`.

I suspect it's the `sd_devices` BPF prog that's rejecting it, but I'll check that tomorrow.
