### ISSUE TITLE
sd_bus_add_object_vtable man page formatting errors

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#17610]
![Screenshot from 2020-11-14 21-43-17](https://user-images.githubusercontent.com/8576552/99154685-94a37180-26a9-11eb-9333-23df12163377.png)

Broken formating at the end of **SD_BUS_METHOD_WITH_ARGS_OFFSET**

![Screenshot from 2020-11-14 21-37-48](https://user-images.githubusercontent.com/8576552/99154737-e1874800-26a9-11eb-9345-ae5003f165af.png)

Extra `>` at the start of **SD_BUS_SIGNAL_WITH_ARGS**

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #17612.
