### ISSUE TITLE
udevd net_id builtin does not identify platform eth on Raspberry Pi 4b

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#17625]
```
udevadm info /sys/class/net/eth0
P: /devices/platform/scb/fd580000.ethernet/net/eth0
L: 0
E: DEVPATH=/devices/platform/scb/fd580000.ethernet/net/eth0
E: INTERFACE=eth0
E: IFINDEX=2
E: SUBSYSTEM=net
E: USEC_INITIALIZED=2468495
E: ID_MM_CANDIDATE=1
E: ID_NET_NAMING_SCHEME=v245
E: ID_NET_NAME_MAC=enxdca63237faa6
E: ID_OUI_FROM_DATABASE=Raspberry Pi Trading Ltd
E: ID_PATH=platform-fd580000.ethernet
E: ID_PATH_TAG=platform-fd580000_ethernet
E: ID_NET_DRIVER=bcmgenet
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth0
E: TAGS=:systemd:
```

Looking at names_platform, the syspath for the device neither matches _PLATFORM_PATTERN4 nor _PLATFORM_PATTERN3.

It would be nice if `/sys/devices/platform/scb/fd580000.ethernet/net/eth0` was recognized and something sensible got constructed out of it.

**Comment by poettering** [comment]
Requires patch by someone who has one of these devices, and cares

**Comment by xnox** [comment]
> Requires patch by someone who has one of these devices, and cares

I have trivial access to all of those devices rpi2, 3[ab+], 4[all the ram sizes], keyboard, etc.

However, I have no clue what to name them, or what the device path means =))))))

"/devices/platform/scb/fd580000.ethernet/net/eth0"

I think it means simple command bus (aka I2C) with lots of things attached to it, one of them is fd580000.ethernet and i'm not sure what those numbers mean.

the dtb for it, just specifies that there is genet node, and that it's well ethernet with a phy.

I'll try to dissamble the compiled dtb, to see if those numbers come from the dtb or some such.

I guess my question is what the naming scheme should be for these.

**Comment by yuwata** [comment]
Maybe, PR #24265 helps you?

**Comment by jcamposeco** [comment]
> Maybe, PR #24265 helps you?

Looks like that is what I was looking for, I will take a look, thanks

**Comment by yuwata** [comment]
@xnox and @jcamposeco Now PR #24265 is in a good shape. Could you test the PR?
