### ISSUE TITLE
Sad DNS: switch default value of DNSSEC option to ‘allow-downgrade’

### ISSUE THREAD

**Issue by djasa** [systemd/systemd#17624]
**systemd version the issue has been seen with**
 > systemd-246.6-3.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > Linux djasa-p1g2-sb.of.brq.spice-qe.redhat.com 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > DNSSEC is enabled and used by default

**Unexpected behaviour you saw**
 > DNSSEC disabled by default leaves users vulnerable to [Sad DNS attack](https://www.cs.ucr.edu/~zhiyunq/SADDNS.html)

**Steps to reproduce the problem**
 > run systemd-resolved in default settings

Filing as a bug as the vulnerability to attack is pretty obvious. In ideal world, we should switch to `DNSSEC=yes` right away but the compatibility problems may be too large so I'm proposing `DNSSEC=allow-downgrade` as saner default.

**Comment by djasa** [comment]
[Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1898137). According to [Fedora wiki](https://fedoraproject.org/wiki/Changes/systemd-resolved), the unsafe default is in their packaging so I'm self-closing this bug.

**Comment by poettering** [comment]
It's the default upstream already. Fedora turns it off though, and I think for good reasons, it's too flakey to do this against arbitrary DNS servers by default, this doesn#t work for many border gateway routers.

Kernel addressed part of the problem already btw, by randomizing the ICMP answer limiting
