### ISSUE TITLE
journalctl missing log between the system@suffix.journal

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#17623]
Please get the details in the issue. I am tring very hard to figure out the reason, but i still can't explain the reason.
cc @poettering @georgmu @keszybz @yuwata
https://github.com/systemd/systemd/issues/17540

**Comment by yuwata** [comment]
Sorry for that we have not responded in the original issue yet. But please do not open such an issue...

**Comment by syyhao1994** [comment]
> Sorry for that we have not responded in the original issue yet. But please do not open such an issue...

Sorry for that, i got it.
