### ISSUE TITLE
Memory leak when running systemctl daemon-reload

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#17632]
**systemd version the issue has been seen with**
 > systemd 245 (v245.4-1.fc32)

**Used distribution**
 > Fedora 32

**Linux kernel version used** (`uname -a`)
 > 5.6.6-300.fc32

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > The RSS PID1 used stays unchanged.

**Unexpected behaviour you saw**
 > The RSS PID1 used increased from 17184 to 21468 in about 11 hour.

**Steps to reproduce the problem**
 > Running systemctl daemon-reload in a while loop.   
```shell
while true; do
        systemctl daemon-reload;
done
```

**Comment by poettering** [comment]
systemd tracks a lot of state. vom 17K to 21K after 11h system uptime doesn't sound so bad. What means you think the memory is leaked?

Note that we maintain allocation caches for hash tables and such, which we don't return to the OS, but reuse.

Checking RSS is not a suitable tool to detect leaks. Use a tool like valgrind or so for that.

Let's close this, as the wrong tools were used, and there's no indication there's actually a problem. Please file a new issue if you can show the memory is actually leaked with a more suitable tool

(Not saying there wasn't a leak, just saying that the tool you used is not suitable for determining that)

**Comment by Geass-LL** [comment]
But if you stop systemd-logind, and retest. The RSS stays unchanged, which is weird。

**Comment by Geass-LL** [comment]
And, does systemd have some limits to RSS PID1 used?  RSS may be more than 600M after 2 months at this speed.
