### ISSUE TITLE
man pages: NUL-terminated vs NULL-terminated

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#17648]
I noticed that the man pages are inconsistent in how they call NULL terminated strings. Sometimes in the same sentence.

```
All functions that take a char*** parameter will store the answer there as an address of
an array of strings. Each individual string is NUL-terminated, and the array is
NULL-terminated as a whole. It will be valid as long as c remains valid, and should not
be freed or modified by the caller.
```

I think it should be NULL-terminated in all cases as the macro name is NULL.  '\0' character is sometimes called NUL but thats not a standard unlike NULL which is a part of standard.

**Comment by igo95862** [comment]
Wikipedia call such strings as null terminated with two L https://en.wikipedia.org/wiki/Null-terminated_string

**Comment by keszybz** [comment]
The single-byte was was traditionally called "NUL" in ASCII charts. That's what we use. And NULL is for the (multi-byte) pointer.
