### ISSUE TITLE
systemd-backlight@backlight:amdgpu_bl0.service cant restore backlight, when using "quiet" kernel command option

### ISSUE THREAD

**Issue by fabiscafe** [systemd/systemd#17645]
**systemd version the issue has been seen with**
 > systemd 246 (246.6-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux frigg 5.9.8-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 10 Nov 2020 22:44:06 +0000 x86_64 GNU/Linux
 > Linux frigg 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > backlight restore working

**Unexpected behaviour you saw**
 > ```Failed to start Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.```

**Steps to reproduce the problem**
 > 1. add "quiet"  to your kernel commmand line
 > 2. reboot 

Journal with quiet:
```
journalctl -b -1 -u systemd-backlight@backlight:amdgpu_bl0.service
-- Logs begin at Thu 2020-09-17 08:15:00 CEST, end at Tue 2020-11-17 14:19:18 CET. --
Nov 17 14:15:15 frigg systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
Nov 17 14:15:15 frigg systemd-backlight[325]: amdgpu_bl0: Failed to write system 'brightness' attribute: No such device or address
Nov 17 14:15:15 frigg systemd[1]: systemd-backlight@backlight:amdgpu_bl0.service: Main process exited, code=exited, status=1/FAILURE
Nov 17 14:15:15 frigg systemd[1]: systemd-backlight@backlight:amdgpu_bl0.service: Failed with result 'exit-code'.
Nov 17 14:15:15 frigg systemd[1]: Failed to start Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```

Right after login, I can do: `systemctl start systemd-backlight@backlight:amdgpu_bl0.service` and backlight got restored successfully

journal without quiet:
```
journalctl -b -u systemd-backlight@backlight:amdgpu_bl0.service
-- Logs begin at Thu 2020-09-17 08:15:00 CEST, end at Tue 2020-11-17 14:23:50 CET. --
Nov 17 14:15:57 frigg systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
Nov 17 14:15:57 frigg systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```
----------------------------------------------

**Upstream Bug** link: https://bugzilla.kernel.org/show_bug.cgi?id=210263 (with workaround)

**Comment by poettering** [comment]
sounds like a driver bug. i.e. if the "brightness" sysfs attribute of the amdgpu driver returns ENXIO you get what you see.

Please ping amdgpu maintainers about this, i.e. why the advertise a brightness device that returns ENXIO.

**Comment by poettering** [comment]
Anyway, let's close this here. I doubt there's anything for us to fix here. If the driver people say otherwise, please report back and we can reopen, but from all i can see it's a driver problem if they advertise a brightness device that results in ENXIO
