### ISSUE TITLE
Pull USB autosuspend rules from fprintd

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#17663]
In fprintd, we have two  sources for USB autosuspend rules:
 * USB IDs mapping the drivers
 * A wiki page of unsupported devices: https://gitlab.freedesktop.org/libfprint/wiki/-/wikis/Unsupported-Devices (which I now intend to pull regularly)
 * A short hardcoded list of exclusions (a keyboard that lags otherwise)

The device are also tagged with the libfprint driver, but we don't really need that at all. With all the unsupported devices, this results in ~250 rules currently (two per device).

We really should turn this into a hwdb. But that made me wonder if we should/could pull the device list into systemd and avoid shipping it in libfprint altogether.

**Comment by poettering** [comment]
Yes, sounds like a job for hwdb. And yes, I think autosuspend stuff is best shipped with systemd itself.

Would love to review/merge a patch for that.

Option 1: libfprint continues to main the original sources, and we pull them from there and process them, covnerting them to hwdb files. We do that from various sources already, such as the PCI or USB ID database, or the chromeos autosuspend database. This would then be one more.

Option 2: the db is moved altogether into our tree, and maintained in systemd form now on.

Either of that would be fine with us.
