### ISSUE TITLE
Unable to disable `systemd-modules-load.service`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#17689]
With Debian Bullseye/testing and systemd 246.6-2, I am unable to disable the service unit *systemd-modules-load*, not required on my system.

    $ sudo systemctl disable systemd-modules-load.service
    $ echo $?
    0

It’s still hooked up, though.

    $ ls -l /lib/systemd/system/sysinit.target.wants/systemd-modules-load.service
    lrwxrwxrwx 1 root root 31 19. Nov 22:35 /lib/systemd/system/sysinit.target.wants/systemd-modules-load.service -> ../systemd-modules-load.service

**Comment by floppym** [comment]
This service isn't supposed to be disabled by the user. It doesn't do anything if unless configured via modules-load.d.

If you really don't want it to run, mask it instead.
```
systemctl mask systemd-modules-load.service
```

**Comment by paulmenzel** [comment]
> This service isn't supposed to be disabled by the user.

How should the user now that? It’d be great, if `systemctl` would gave corresponding feedback, and not return with success.

> It doesn't do anything unless configured via modules-load.d.

It clutters the logs, and despite not much, it still consumes tiny resources, which is bad if `/etc/modules-load.d` is not used on quite a few systems. So it should be possible to easily disable that service unit.

> If you really don't want it to run, mask it instead.
> 
> ```
> systemctl mask systemd-modules-load.service
> ```

Yeah, that is one way. I removed the symbolic link `/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service` instead.

**Comment by floppym** [comment]
> I removed the symbolic link /lib/systemd/system/sysinit.target.wants/systemd-modules-load.service instead.

That symlink will be restored whenever you upgrade/reinstall systemd.

**Comment by yuwata** [comment]
Yes, please use `systemctl mask` if you really want to disable the service.

**Comment by paulmenzel** [comment]
It is a bug, when `systemctl` returns success, but did not do anything.. Please re-open.

**Comment by yuwata** [comment]
OK. Let's document the behavior explicitly. #17695.
