### ISSUE TITLE
Improve user experience with Systemctl unit command argument order

### ISSUE THREAD

**Issue by mtovmassian** [systemd/systemd#17696]
When I manage a service I regularly run these two commands to refresh the instance and immediately verify its behavior:
` systemctl restart my-service`
` systemctl status my-service`

The _systemctl_ command line syntax, where the unit command precedes the service name, is not convenient for this workflow. I wish I could retrieve the first command I typed, and simply edit it by deleting/replacing the last argument. But here I have to navigate through the command line by hitting Ctrl-b until I reached the command unit argument before deleting/replacing it.

What if we have  a flag, _--flip_, that allows to flip the unit command argument with the service name argument?

` systemctl --flip my-service restart`
` systemctl --flip my-service status`

**Comment by poettering** [comment]
I am sorry, but no. Redundancy like this is detrimental to user experience. We want simple, uniform interfaces and not interfaces that can be used in one way, but also in the reverse.

Most shells (like bash) know keycombos like Alt-B for skipping backwords over a word, and Alt-Backspace for removing the previous word. This means if you have the following like:

```
systemctl restart my-service
```

Then it suffices to hit `<Alt-B> <Alt-Backspace> <s> <t> <a> <t> <u> <s>` to get to:

```
systemctl status my-service
```

That's 5 keys less than typing in the command with an extra `--flip ` in the command line, and then hitting `<Alt-Backspace> <s> <t> <a> <t> <u> <s>`. Also, it has the very nice property that it doesn't require to think about the `--flip` already when you type in the command first.

Hence, sorry, but I am not convinced this is a good idea. Using shell keyboard shortcuts properly sound like the much better, much more powerful and generic option here. Adding redundant features to the command line can only be the very last resort to achieve things.

Hope that makes some sense, even if disappointing. Sorry!

**Comment by mtovmassian** [comment]
Ok make sense. I can understand that it would deteriorate the interface consistency just for a little bit of comfort.
Thanks for the `<Alt-b>` tip.
