### ISSUE TITLE
systemd-tmpfiles prints weird errors when setting file attributes that conflict

### ISSUE THREAD

**Issue by brainpower** [systemd/systemd#17690]
**systemd version the issue has been seen with**
 > Arch Linux's  246.6-1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.9-arch1-1

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > systemd-tmpfiles not printing any errors

**Unexpected behaviour you saw**
 > systemd-tempfiles prints the following errors:
```
(2/3) Creating temporary files...
Cannot set file attribute for '/var/log/journal', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
Cannot set file attribute for '/var/log/journal/1cd5XXXXXXXXXXXXXXXX32420fa', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
Cannot set file attribute for '/var/log/journal/remote', value=0x00800000, mask=0x00800000, ignoring: Invalid argument
```

My investigation showed that these errors are only printed when compression was enabled on the directories systemd-tmpfiles tries to set the `+C` attribute on. Running `chattr -c` on the directories listed in the error messages fixed the errors.
It seems to me that **compression** and **no CoW** cannot be enabled together on **btrfs**.

Maybe this can be fixed by also disabling compression in [master/tmpfiles.d/journal-nocow.conf](https://github.com/systemd/systemd/blob/master/tmpfiles.d/journal-nocow.conf), if thats possible, sensible and does not hurt on other filesystems?

The other issue here is, maybe the error messages could be improved? It took me some googling to get to the root of the issue...

**Steps to reproduce the problem**
 > Enable compression on a btrfs filesystem before systemd-tmpfiles creates `/var/log/journal`

EDIT: It seems this only happens if the attributes are used via `chattr +c` or `btrfs property set ./dir compression lzo`, but not when using the mount option `compress=`.
Sounds like there could be a btrfs bug at play here, too, but I dont think thats the case since `btrfs(5)` states for the `nodatacow` mount option: ` Nodatacow implies nodatasum, and disables compression.`

also, showing that `+c` and `+C` seem to conflict:
```console
% mkdir dir                                             
% lsattr                                                
-------------------- ./dir
% chattr +C dir                                         
% lsattr                                                
---------------C---- ./dir
% chattr +c dir                                         
chattr: Invalid argument while setting flags on dir
% lsattr                                                
---------------C---- ./dir
% chattr -C dir                                         
% chattr +c dir                                         
% lsattr                                                
--------c----------- ./dir
% chattr +C dir                                         
chattr: Invalid argument while setting flags on dir
% lsattr                                                
--------c----------- ./dir
```

**Comment by yuwata** [comment]
Fix is waiting in #17693.
