### ISSUE TITLE
systemd-hostnamed fails to start with read-only file system (but read-writable `/run`)

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#17701]
With Debian bullseye/testing, `systemd-hostnamed` fails to start if the file system is read-only.

```
$ systemd --version
systemd 246 (246.6-2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
$ systemctl status systemd-hostnamed.service
● systemd-hostnamed.service - Hostname Service
     Loaded: loaded (/lib/systemd/system/systemd-hostnamed.service; static)
     Active: failed (Result: exit-code) since Mon 2020-11-23 15:33:30 CET; 1min 23s ago
       Docs: man:systemd-hostnamed.service(8)
             man:hostname(5)
             man:machine-info(5)
             https://www.freedesktop.org/wiki/Software/systemd/hostnamed
    Process: 490 ExecStart=/lib/systemd/systemd-hostnamed (code=exited, status=226/NAMESPACE)
   Main PID: 490 (code=exited, status=226/NAMESPACE)

Nov 23 15:33:30 gepard systemd[1]: Starting Hostname Service...
Nov 23 15:33:30 gepard systemd[490]: systemd-hostnamed.service: Failed to set up mount namespacing: /run/systemd/unit-root/dev: Read-only file system
Nov 23 15:33:30 gepard systemd[490]: systemd-hostnamed.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-hostnamed: Read-only file system
Nov 23 15:33:30 gepard systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=226/NAMESPACE
Nov 23 15:33:30 gepard systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
Nov 23 15:33:30 gepard systemd[1]: Failed to start Hostname Service.
```

Should `systemd-hostnamed` be able to support read-only file systems?

**Comment by poettering** [comment]
/run is read-only for you system wide? That's not supported. Sorry.

**Comment by paulmenzel** [comment]
Do you know who sets `/run` up? Is `/run` set up by `systemd-tmpfiles-setup`? I couldn’t find an entry only for `/run` in `/usr/lib/tmpfiles.d/systemd.conf`.

**Comment by mbiebl** [comment]
Am Mo., 23. Nov. 2020 um 18:49 Uhr schrieb Paul Menzel <
notifications@github.com>:

> Do you know who sets /run up? Is /run set up by systemd-tmpfiles-setup? I
> couldn’t find an entry only for /run in /usr/lib/tmpfiles.d/systemd.conf.
>

https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L84

**Comment by poettering** [comment]
/run is consider an "API VFS", i.e. it's not user managed, but is "just there", like /sys/ or /proc/. There's no special need to set it up and it comes with closely defined semantics.

**Comment by paulmenzel** [comment]
Sorry, I should have checked, if `/run` is writable right away. And it is:

    $ findmnt /
    TARGET SOURCE         FSTYPE OPTIONS
    /      /dev/nvme0n1p2 ext4   ro,relatime
    $ findmnt /run
    TARGET SOURCE FSTYPE OPTIONS
    /run   tmpfs  tmpfs  rw,nosuid,nodev,noexec,relatime,size=3280868k,mode=755

Just to make sure it’s not an ordering problem, restarting the service `systemd-hostnamed` still fails.

    $ sudo systemctl restart systemd-hostnamed.service
    Job for systemd-hostnamed.service failed because the control process exited with error code.
    See "systemctl status systemd-hostnamed.service" and "journalctl -xe" for details.

Permissions:

    $ ls -ld /run/systemd/unit-root
    drwx------ 2 root root 40 24. Nov 09:06 /run/systemd/unit-root
    $ sudo ls -l /run/systemd/unit-root
    insgesamt 0

At least I can write to the directory. (But probably I misunderstand the error.)

    $ sudo touch /run/systemd/unit-root/test
    $ sudo ls -l /run/systemd/unit-root/test
    -rw-r--r-- 1 root root 0 24. Nov 09:16 /run/systemd/unit-root/test

**Comment by poettering** [comment]
Consider doing "strace -y -s 500 -p 1 -f -o /tmp/strace.log" right before starting hostnamed with "systemctl start systemd-hostnamed.service".

Then terminate the strace, and paste the generated log file somewhere.

This should say more clearly on which precise operation EROFS is seen.

**Comment by paulmenzel** [comment]
Thank you for guiding me. Here it is: [strace.log](https://github.com/systemd/systemd/files/5591628/strace.log).

**Comment by paulmenzel** [comment]
It seems to want to write to `/tmp`, which is directly on `/` and indeed read-only.

    mkdir("/tmp/systemd-private-03d8c18d870f4524a6dc0593cb13b124-systemd-hostnamed.service-KuEeJf", 0700) = -1 EROFS (Das Dateisystem ist nur lesbar

**Comment by mbiebl** [comment]
`/tmp` needs to be writeable. If you want to make `/` ro, then you could use a tmpfs on `/tmp`

**Comment by paulmenzel** [comment]
Can the requirement of `/tmp/` having to be writable be formulated as a condition in the service unit?

**Comment by poettering** [comment]
Conditions bypass unnecessary stuff. If hostnamed is requested we should not bypass it, but the client should either get its request through or things should fail.

Anyway, /tmp needs to be writable, otherwise things using it will fail. Same for /var: stuff that needs to write to /var needs it writable.

Closing.

**Comment by paulmenzel** [comment]
For systemd-hostnamed should this be:

a) documented, and
b) be checked in code?

**Comment by paulmenzel** [comment]
Reading more about boot options, I wonder, if this is also a problem with `systemd.volatile=true`.

**Comment by poettering** [comment]
We don't document requirements like this for individual daemons, writable /tmp is an implicit provided functionality of the OS. Daemons running after initial boot completed (i.e. "regular" services) may assume that /tmp is writable, and `systemd-hostnamed` is a regular service like that.

Semantics of /tmp and /var/tmp are explained here: 

https://systemd.io/TEMPORARY_DIRECTORIES/

First sentence already says they are "world-writable", which means more generally: writable.

**Comment by aep** [comment]
> a) documented, and

did you end up documenting it? currently try-and-erroring my way to systemd in read-only root
