### ISSUE TITLE
Missing entry in 60-evdev.hwdb for Lenovo Thinkpad Carbon X1 Extreme Gen 1/2/3

### ISSUE THREAD

**Issue by law** [systemd/systemd#17716]
**systemd version the issue has been seen with**
 > 245.4-4ubuntu3.3 

**Used distribution**
 > Ubuntu Desktop 20.04

**Linux kernel version used** (`uname -a`)
 > Linux carbon 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

There are no entries for the new Lenovo Thinkpad X1 Carbon Extremes, Gen 1, 2, or 3, causing some confusion with libinput when the touchpad gets initialized at the (incorrect) size of 70mm x 50mm - see https://gitlab.freedesktop.org/libinput/libinput/-/issues/541 for details.

Per the instructions in the file, I have measured my touchpad size (100mm x 69mm) and run it through `touchpad-edge-detect 100x69 /dev/input/event5` with the following results: 

```
# Lenovo Thinkpad Carbon X1 Extreme Gen 3
evdev:name:SynPS/2 Synaptics TouchPad:dmi:bvnLENOVO:bvrN2VET23W(1.08):bd10/05/2020:svnLENOVO:pn20TKCTO1WW:pvrThinkPadX1ExtremeGen3:rvnLENOVO:rn20TKCTO1WW:rvrSDK0R32862WIN:cvnLENOVO:ct10:cvrNone:*
 EVDEV_ABS_00=1354:5678:43
 EVDEV_ABS_01=1169:4695:51
 EVDEV_ABS_35=1354:5678:43
 EVDEV_ABS_36=1169:4695:51
```

I am creating this bug report so the above data may be included in future versions of systemd, hopefully saving folks the trouble I went through getting my touchpad working.

**Comment by whot** [comment]
Can you submit this as a PR please so the CI runs on it and we can merge it. Plus you get all the fame from having a patch in :)

Best to shorten the match line to 
```
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnLENOVO*pvrThinkPadX1ExtremeGen3*
```

**Comment by keszybz** [comment]
Let's keep the issue open until this gets fixed though.

**Comment by law** [comment]
PR is live: https://github.com/systemd/systemd/pull/17733
