### ISSUE TITLE
[homed] support F2FS encryption

### ISSUE THREAD

**Issue by FedericoCeratto** [systemd/systemd#17713]
F2FS is becoming widespread on smartphones and tablets and distributions like Debian/Mobian are starting to target them.
It supports per-directory encryption and compression.

homed could support encryption and hopefully scrub keys/passwords on suspend.

**Comment by igo95862** [comment]
Isn't it already supported: https://wiki.archlinux.org/index.php/Systemd-homed#fscrypt_directory

**Comment by FedericoCeratto** [comment]
There is no clear mention of it in https://github.com/systemd/systemd/blob/master/docs/HOME_DIRECTORY.md#storage-mechanism-fscrypt-directories but hopefully fscrypt should work - thanks.

**Comment by poettering** [comment]
I have no experience with f2fs. If it works already I guess we can close this? Can you check, given you appear to play around with file systems of that type?

**Comment by igo95862** [comment]
> There is no clear mention of it in https://github.com/systemd/systemd/blob/master/docs/HOME_DIRECTORY.md#storage-mechanism-fscrypt-directories but hopefully fscrypt should work - thanks.

fscrypt is just a linux subsystem that certain filesystems support. Right now (2020-11-26) only ext4, f2fs and ubifs supports it. Maybe there is room to add a list of filesystem that support fscrypt to systemd-homed documentation or just put an information that you should check the list of filesystems supporting fscrypt.

**Comment by igo95862** [comment]
@FedericoCeratto Do you think adding more documentation to what exactly fscrypt is and what filesystems support it will solve this issue?

**Comment by poettering** [comment]
So, what his this about now? is there anything that doesnt work already, @FedericoCeratto? is thus just a request to list f2fs directly  in the man page? I am not sure i want to do that, unless someone actually tests it. Hence, you appear to have such file systems, can you verify and report back, please?

If not I think we should just close the issue, and wait until someone reports it doesn't work, or reports they have tested it and it does work, and we should list it in the docs

**Comment by FedericoCeratto** [comment]
Will do

**Comment by poettering** [comment]
Ok, let#s close this. if f2fs supports fscrypt this should just work. If this doesn't work, please report a bug.
