### ISSUE TITLE
.path units with PathChanged= should recognize atomic symlink replacement, but doesn't

### ISSUE THREAD

**Issue by Bilge** [systemd/systemd#17727]
**Is your feature request related to a problem? Please describe.**
I want to monitor atomic deployments with a path unit. An atomic deployment looks like this:

```sh
ln -nsf new-release release
mv -T release current
```

This replaces the existing symlink `current` with the new symlink `release` pointing to `new-release` (instead of whatever the old release was).

**Describe the solution you'd like**
>my.path
```ini
[Path]
PathMoved=/var/www/my-site/current
```

**Describe alternatives you've considered**
I have tried `PathChanged` and `PathModified`, neither of which detect the symlink replacement.

**Comment by poettering** [comment]
hmm, PathChanged= really should just work for this.

**Comment by keszybz** [comment]
Let's move this down. If we have a patch soon, we can always merge it. But I don't think we need to block on this.

**Comment by tjohanssonn** [comment]
+1 Also stumbled upon this, been trying both `PathChanged` and `PathModified`. Only difference is that I am doing this from a python script with pathlib's `Path.replace()`.

**Comment by nomeata** [comment]
Maybe I am doing something wrong, but (using systemd 254.6, which should have the fix from #19726) it seems it does not seem to work here. This is my setup:
```
# cat /etc/systemd/system/loogle-watcher.path
[Unit]

[Path]
PathChanged=/home/loogle/deploy/live

# cat /etc/systemd/system/loogle-watcher.service
[Unit]
Description=Loogle file watcher

[Service]
Environment="TZDIR=/nix/store/4dbixfbbm2vl5jsl7xr7pbp71amf4x9r-tzdata-2023c/share/zoneinfo"
ExecStart=systemctl restart loogle.service
Type=oneshot
```

The symlink `/home/loogle/deploy/live` was just replaced:
```
# ls -l /home/loogle/deploy/live
lrwxrwxrwx 1 loogle users 32 Jan 25 08:13 /home/loogle/deploy/live -> deploy-2024-01-25T08:05:39+00:00
```
but didn’t trigger the `.path`
```
# systemctl status loogle-watcher.path
● loogle-watcher.path
     Loaded: loaded (/etc/systemd/system/loogle-watcher.path; enabled; preset: enabled)
     Active: active (waiting) since Thu 2024-01-25 00:41:47 UTC; 7h ago
   Triggers: ● loogle-watcher.service

Jan 25 00:41:47 loogle systemd[1]: Started loogle-watcher.path.
```

I’m using this idiom for an atomic swap:
```
ln -s "$workdir" tmp
mv -T tmp live
```

**Comment by martyone** [comment]
Same here. Workaround: `touch --reference path/to/symlink path/to/symlink` after replacing the symlink.

**Comment by dinvlad** [comment]
I'd add that paths, whether with or without symlinks, aren't detecting changes to files for me..
