### ISSUE TITLE
systemctl list-dependencies should use a different shape for non-up dependencies (UX)

### ISSUE THREAD

**Issue by Jiehong** [systemd/systemd#17728]
`systemctl list-dependencies` displays the list of dependencies, with white or green circles next to them to indicate if they are up or not.

Ex:

![image](https://user-images.githubusercontent.com/1061229/100255467-d05cf780-2f43-11eb-812d-b3247ba26b15.png)

However, when colours cannot be displayed (or be correctly seen by users with colour blindness), the status is unclear.

Copy/past of the content of the screenshot:

```
➤ systemctl list-dependencies dbus.service
dbus.service
● ├─dbus.socket
● ├─system.slice
● └─sysinit.target
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─haveged.service
●   ├─kmod-static-nodes.service
●   ├─ldconfig.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─sys-kernel-tracing.mount
```

In UI/UX, it is always recommended to indicate something with both a colour and a shape, to avoid this kind of issues.

I propose to display a different glyph for dependencies that are not up, for example the [black square](https://unicode-table.com/en/25A0/): `■`.

**Systemd version**
 > 246.

**Used distribution**
 > Archlinux

**Linux kernel version used** (`uname -a`)
 > Linux archlinux 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Dependencies that aren't up should use a different glyph.

**Unexpected behaviour you saw**
 > Dependencies are displayed with the same glyph, irrespective their status.

**Steps to reproduce the problem**
 > Run `systemctl list-dependencies dbus.service`.

**Comment by q2dg** [comment]
Moreover, it could be great if this color/shape agreement was documented somewhere. Thanks!

**Comment by Jiehong** [comment]
Closing, with a PR that improved things a lot on that front (with documentation). See https://github.com/systemd/systemd/commit/9ae5fed64ec1647d1c8a8e21528c1d2f08b3ebac.
