### ISSUE TITLE
Limit* should take human-readable inputs

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#1772]
I'd be nice to be able to say LimitAS=16G instead of LimitAS=16106127360

**Comment by poettering** [comment]
I figure much of this is alraedy implemented with #1794 now (which adds K, G, M style parsing for byte-based limits). #1835 adds support for better parsing time-based limits by adding "s", "ms", "h", "min"-style units. With both merged I figure this RFE is fully implemented.
