### ISSUE TITLE
systemd incorrectly reports unit file has "changed on disk" when override.conf is present

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#17730]
Verified with 246.6 and 247-rc2

Originally filed as downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975289

This reproduces the issue with 246.6-2~bpo10+1:

1) Create a normal unit file /etc/systemd/system/test-start.service with 
contents
```
[Unit]
Description=Test start

[Service]
Type=oneshot
ExecStart=/usr/bin/mailx -s "message from test-start.service" root < /dev/null
```
2) Create an instantiated unit file 
/etc/systemd/system/test-warning@.service with contents
```
[Unit]
Description=test warning

[Service]
Type=oneshot
ExecStart=/usr/bin/mailx -s "service %i at %H has failed" root < /dev/null
```
3) Create a system wide drop-in 
/etc/systemd/system/service.d/test-warning.conf with contents
```
[Unit]
OnFailure=test-warning@%p.service
```
4) Create drop-in /etc/systemd/system/test-start.service.d/override.conf 
(by executing "systemctl edit test-start") with contents
```
[Service]
ExecStartPost=/usr/bin/mailx -s "message from override.conf" root < /dev/null
```
5) systemctl daemon-reload

6) systemctl status test-start

7) goto 5

The "Run 'systemctl daemon-reload' to reload units." warning persists as 
long as /etc/systemd/system/test-start.service.d/override.conf is newer 
than /etc/systemd/system/service.d/test-warning.conf and can be cleared by:

touch /etc/systemd/system/service.d/test-warning.conf
systemctl daemon-reload

**Comment by arnested** [comment]
I can confirm this on 246.6:
```console
$ systemctl --version
systemd 246 (246.6-1ubuntu1.1pop0~1612220693~20.10~224c77d)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

This is my test case:
```console
$ sudo systemctl cat test-17730.service
# /etc/systemd/system/test-17730.service
[Unit]
Description=Test service

[Service]
Type=oneshot
ExecStart=/bin/echo "message from test service"

# /etc/systemd/system/test-17730.service.d/override.conf
[Service]
ExecStart=
ExecStart=/bin/echo "message from test service override"

# /etc/systemd/system/test-17730.service.d/override2.conf
[Service]
ExecStart=
ExecStart=/bin/echo "message from test service override 2"
```
After creating the files and doing a daemon-reload everything looks fine.

Then I make the timestamp of the first override file newer than that of the second:
```console
sudo touch /etc/systemd/system/test-17730.service.d/override.conf
```

Now I get the warning that the source configuration files have changed on disk. Even after I do a daemon-reload:
```console
$ sudo systemctl status test-17730.service 
Warning: The unit file, source configuration file or drop-ins of test-17730.service changed on disk. Run 'system...
● test-17730.service - Test service
     Loaded: loaded (/etc/systemd/system/test-17730.service; static)
    Drop-In: /etc/systemd/system/test-17730.service.d
             └─override.conf, override2.conf
     Active: inactive (dead)

[... log lines]
arne@skovsnegl:~$ sudo systemctl daemon-reload 
arne@skovsnegl:~$ sudo systemctl status test-17730.service 
Warning: The unit file, source configuration file or drop-ins of test-17730.service changed on disk. Run 'system...
● test-17730.service - Test service
     Loaded: loaded (/etc/systemd/system/test-17730.service; static)
    Drop-In: /etc/systemd/system/test-17730.service.d
             └─override.conf, override2.conf
     Active: inactive (dead)

[... log lines]
```

To get rid of the warning I can update the timestamp of the second override file by touching it. I don't need a daemon-reload for the warning to disappear:
```console
$ sudo touch /etc/systemd/system/test-17730.service.d/override2.conf
$ sudo systemctl status test-17730.service 
● test-17730.service - Test service
     Loaded: loaded (/etc/systemd/system/test-17730.service; static)
    Drop-In: /etc/systemd/system/test-17730.service.d
             └─override.conf, override2.conf
     Active: inactive (dead)

[... log lines]
```

Having just one override file and touching the main unit file to be newer than the override file does not result in a warning.

**Comment by luitzifa** [comment]
Got the same problem. Touched my drop-in files in alphabetical order and it was gone. Thanks @arnested
