### ISSUE TITLE
org.freedesktop.timedate1.SetNTP is not atomic, prevents other calls

### ISSUE THREAD

**Issue by davidedmundson** [systemd/systemd#17739]
**systemd version the issue has been seen with**
 > …

246

**Used distribution**
 > …
Any

**Linux kernel version used** (`uname -a`)
 > …
5.9.2-arch1-1, but it will affect an

**CPU architecture issue was seen on**
 > …
x86_64, but it will affect any

**Expected behaviour you didn't see**
 >
We call SetNtp() wait for it to finish, Call SetTime. Expectation is this succeeds correctly,

**Unexpected behaviour you saw**
 We call SetNtp() wait for it to finish, Call SetTime. 

"Failed to set current time "org.freedesktop.timedate1.AutomaticTimeSyncEnabled" "Previous request is not finished, refusing."

> Steps to reproduce:

One needs a binary that calls SetNtp() SetTime() consecutively, which is a sensible pattern for a GUI with an apply button.

Raised as downstream bug(https://bugs.kde.org/show_bug.cgi?id=429112) 

> Code wise the issue is:

set_ntp does starts an async call and then returns success from the setNTP method
https://github.com/systemd/systemd/blob/a2e926a135e0a88e5df3731e7fd682aba789cce9/src/timedate/timedated.c#L969

ntp property doesn't change until the "Job removed" signal comes in from systemd, via: match_job_removed
https://github.com/systemd/systemd/blob/a2e926a135e0a88e5df3731e7fd682aba789cce9/src/timedate/timedated.c#L462

The set_time method fails if an existing job is still running:
https://github.com/systemd/systemd/blob/a2e926a135e0a88e5df3731e7fd682aba789cce9/src/timedate/timedated.c#L812

General convention is that DBus methods only return when the property is actually updated.

Creating the call and then watching the property instead of the method returning will probably work as a downstream workaround, but it's messy as I can't correctly detect failures.

Alternatively returning the path to the systemd job in setNTP would work allow a much cleaner downstream patch.

**Comment by sl1pkn07** [comment]
any notice of this?

2023 and still is a reproducible issue

greetings

**Comment by zvova7890** [comment]
Any comment?

**Comment by yuwata** [comment]
I will take a look.
