### ISSUE TITLE
bootctl --boot-path=/ should be permitted, currently is refused

### ISSUE THREAD

**Issue by robert-scheck** [systemd/systemd#17746]
**Is your feature request related to a problem? Please describe.**

1. `/dev/vda1`, ESP with FAT32, mounted to `/boot/efi`
2. `/dev/vda2`, XBOOTLDR with ext4, mounted to `/`
3. UEFI shell can access ext4 filesystems due to EfiFs being loaded:
```
$ efibootmgr -v -r
DriverOrder: 0000
Driver0000* ext4	HD(1,GPT,8a1f0559-5c12-4ee7-b4fc-77b6bb505a73,0x800,0x12c000)/File(\EFI\drivers\ext2.efi)
$ 
```
4. On `/dev/vda2`, there are `/boot/vmlinuz-<…>`, `/boot/loader/entries/<…>.conf` etc.
5. Trying to use `/boot` (being not an own partition, but part of `/`) is disliked by `bootctl`:
```
$ bootctl install --boot-path=/boot --esp-path /boot/efi
Directory "/boot" is not the root of the file system.
$ 
```
6. Finally, trying to be very clever doesn't help either, because:
```
$ bootctl install --boot-path=/ --esp-path /boot/efi
Directory "/" is not the root of the file system.
```

**Describe the solution you'd like**
`bootctl` also should support non-root of the filesystem for `--boot-path`, or at least have an exception to only whitelist `/boot` for non-root of the filesystem.

**Describe alternatives you've considered**
As of writing it seems to be needed by `bootctl` to have three partitions:
1. `/`
2. `/boot` as XBOOTLDR
3. `/boot/efi` as ESP

GRUB2 supports the desired two partition situation with non-root of the filesystem (yes, GRUB2 doesn't do XBOOTLDR), but it's more about the two partition rather three partition difference here.

**Comment by poettering** [comment]
Hmm, you want the root partition and the xbootldr partition to be the same? interesting idea. 

Note that for sd-boot to find its stuff you have to place the /loader/ dir in the root of xbootldr fs, hence if you want to have xbootldr and the root fs the same partition you need a /loader/ dir in the root fs (and maybe make /boot a symlink to /)

THe check for root of the fs works by comparing the backing st_dev stat field of the specified xbootldr path with the st_dev field of its parent dir. if you pass the root dir as path, the parent of root is root again (yeah, unix thinks that's smart that way), which means st_dev will match, and bootctl thus thinks you are not at the top of the fs.

I figure we have to special case the root dir when specified as --boot-path=, to also recognize it as top of an fs. happy to review/merge a patch for that

**Comment by robert-scheck** [comment]
> I figure we have to special case the root dir when specified as --boot-path=, to also recognize it as top of an fs. happy to review/merge a patch for that

I wonder how bad it actually would be to also check `/boot/loader/` either before or after `/loader/` on XBOOTLDR only?

**Comment by poettering** [comment]
It sounds more like what you actually want is tag the root fs as root fs, but have sd-boot look on the rootfs too, so that it looks in:

1. The /loader/ dir of the ESP
2. The /loader/ dir of XBOOTLDR
3. The /boot/loader/ dir of the root fs

or to say this differently: you merge the rootfs and the xbootldr partition into one. If you do that, i'd say it's still more a root fs than a xbootldr fs though.

Right?

**Comment by robert-scheck** [comment]
Right, I tried to avoid a separate `/boot` partition by labeling the rootfs as xbootldr.

**Comment by scratchmex** [comment]
How do you use XBOOTLDR with ext4 as the root / partition when the [bootloader spec](https://systemd.io/BOOT_LOADER_SPECIFICATION/) says that it should be fat32? I want to do the same as you and when running the command in `systemd 250 (v250.8-1.fc36)` I get
```console
# bootctl install --boot-path=/ --esp-path /efi
File system "/dev/block/259:10" has wrong type for extended boot loader partition.
```

```console
# lsblk -f
NAME        FSTYPE   FSVER         LABEL   UUID   FSAVAIL FSUSE% MOUNTPOINTS
nvme0n1                                                                                                        
├─nvme0n1p1 vfat     FAT32         ESP     X       615.6M     5% /efi
├─nvme0n1p2                                                                                                     
├─nvme0n1p3 ntfs                   OS      X                                   
├─nvme0n1p5 ext4     1.0                   X        31.5G    15% /
├─nvme0n1p6 ext4     1.0                   X        47.4G    34% /home

# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
nvme0n1     259:0    0 931.5G  0 disk 
├─nvme0n1p1 259:2    0   650M  0 part /efi
├─nvme0n1p2 259:6    0   128M  0 part 
├─nvme0n1p3 259:9    0   796G  0 part 
├─nvme0n1p5 259:10   0  40.5G  0 part /
├─nvme0n1p6 259:11   0  79.5G  0 part /home
```
