### ISSUE TITLE
[Feature request - released tarballs/zip files] Consider offering versioned tarball releases at github

### ISSUE THREAD

**Issue by rubyFeedback** [systemd/systemd#17747]
Hello,

If you go there:

    https://github.com/systemd/systemd/releases

You see the two downloads such as:

  https://github.com/systemd/systemd/archive/v247.tar.gz

This one is already versioned, e. g. at 247.

I would like to propose to also make available "fully" versioned
tarball releases, such as this one here:

    https://github.com/lxqt/qterminal/releases/download/0.16.0/qterminal-0.16.0.tar.xz

If you wget it and extract it, you get the extracted directory called "qterminal-0.16.0".

Reasoning for this proposal:

Actually this is a bit selfish, since I have written some ruby-code over the years where
I manage downloads like this. For these scripts it is simpler to assume that the 
tarballs follow some "rule", e. g. "program-name" on the left hand side, then "program
version" on the right hand side (and yes, there are lots of special cases these scripts
have to cover, since there is no real consistent scheme in use; people use all sorts of
strange setups, but most follow the program-name + program-version approach).

So via a versioned tarball, this simplifies the scripts a little bit.

I am not sure if that use case seems relevant to the project here, but I wanted to 
describe the genuine use case, as trivial as it is.

If I use the above .tar.gz for systemd, which I assume is autogenerated, the
extracted directory is systemd-247/. It is not a big deal, my ruby scripts already
handle that (a simple way is to, after extraction, get a listing of directories and
compare which one is new, for example), so strictly speaking this is not really
necessary (for me). I just would prefer if a versioned tarball would be considered
too. (I am not sure how this is done in a github-based project, but I assume it
must be possible somehow, as other projects do so too; not sure how they
do it, because many projects don't offer versioned tarballs whereas others
do.)

At any rate please feel free to close this issue here at any moment in time for
any reason.

PS: I actually only care about .tar.* releases; .zip I normally only use on 
windows, but most of the time I am on linux, and even on windows I can
now use WSL so wget works too + tar.

**Comment by yuwata** [comment]
Please use https://github.com/systemd/systemd/archive/v247/systemd-247.tar.gz

**Comment by yuwata** [comment]
You can also download in zip format with https://github.com/systemd/systemd/archive/v247/systemd-247.zip
