### ISSUE TITLE
Document Systemd Journald Protocol

### ISSUE THREAD

**Issue by sargun** [systemd/systemd#17748]
**Is your feature request related to a problem? Please describe.**
sd_journal_print and co that are provided by the libsystemd library are required to do structured logging from arbitrary applications. I need to be able to log structured data in an efficient manner to systemd without the usage of native (linked-in) bindings. For example, Erlang has native unix socket support (https://erldocs.com/current/erts/socket.html?i=66), but calling FFIs can be quite a task (specifically around NIFs). In addition other languages like nodejs don't have a good way to write stable libraries across versions.

**Describe the solution you'd like**
I would like formal documentation of how the systemd journald protocol works, and how to log to it from my application. Specifically, I can open a DGRAM socket to `/run/systemd/journal/socket`, and I'd like to know how to log to it. 

**Describe alternatives you've considered**
I've considered using `systemd-journal-remote`, but unfortunately it doesn't have all the same features as writing to the socket directly, and it involves extra levels of indirection, and complexity.

**Comment by bluca** [comment]
Have you read this https://systemd.io/JOURNAL_FILE_FORMAT/ ?

**Comment by sargun** [comment]
It doesn't seem like this is the format that's used to write entries to the journald socket, but the journald file itself instead.

**Comment by topimiettinen** [comment]
There's also [Wireshark dissector for journald](https://gitlab.com/wireshark/wireshark/-/blob/master/epan/dissectors/packet-systemd-journal.c), but it also seems to be for the file format.

**Comment by poettering** [comment]
So, the protocol is stable and we do support alternative implementations of it. However it is indeed currently undocumented. Documenting it shouldn't be hard, it's a pretty simple protocol. It's just that somebody needs to sit down and do it.
