### ISSUE TITLE
Document that [Install] in drop-ins is not respected

### ISSUE THREAD

**Issue by pengwyn** [systemd/systemd#1774]
Hi,

I have recently tried to add a modified install option to a system unit file, by making a drop-in override through the command `systemctl edit blah.service`. In particular I replaced a `WantedBy=` option by putting into the file:

```
[Install]
WantedBy=
WantedBy=network-online.target
```

However, this wasn't respected, and when I ran `systemctl enable blah.service` it seemed to use the `WantedBy` option of the default unit file (set to `multi-user.target`) because it created symlinks into the direction `multi-user.target.wants` instead of `network-online.target.wants`. To properly replace the option I had to make a full replacement through the command `systemctl edit --full blah.service`.

Is this behaviour intended? There doesn't seem to be an explicit mention of this in the documentation. There is a mention that

> "... dependencies (After=, etc.) cannot be reset to an empty list... you have to override the entire 
> unit."

however this doesn't seem to be the present behaviour either. If this were the case, then I would have two symlinks in both `network-online.target.wants` and `multi-user.target.wants`.

If this behaviour is intended, then perhaps a mention of it could be made in the documentation as well as a warning given when `systemctl edit blah.service` finishes copying a drop-in override with an [Install] section.

I'm using release 227 of systemd in an archlinux install.

Thanks

**Comment by poettering** [comment]
Well, this has been requested before, but generally, install info is something that is provided by the unit file vendor in the unit files. drop-ins and symlinks in /etc are user extensions however. "systemctl enable" is for applying that install info to /etc. It would be contradictory to use user configuration to create user configuration though. Hence we do not respect install info in drop-ins.

So, this is really expected behaviour. But I figure it's undocumented expected behaviour. I'll hence turn this into a documentation bug about that.

**Comment by pengwyn** [comment]
Sounds good to me. I figured that the drop-ins are a bit of a post-install configuration. However, from a pure systemctl edit perspective, it is a bit confusing that running the command with and without "--full" produces different behaviour.

Does "systemctl edit" currently do any sanity checks of the content of the overrides? I had a quick look at the source and it doesn't appear to. Would it be a good idea if I put in a feature request for sanity checks?

**Comment by poettering** [comment]
Yeah, might make sense to add such a feature. And yeah, I agree that it is non-obvious that "systemctl edit --full" accepts [Install] and "systemctl edit" does not... Humpf...

Anyway, please file an RFE bug regarding asking "systemctl edit" to verify unit files after editing them.

**Comment by pengwyn** [comment]
Done! I might try implementing it myself sometime soon.

**Comment by pengwyn** [comment]
This may not need to be an issue soon depending on the outcome from discussions in #2270. Just referencing that here in case of confusion later.
