### ISSUE TITLE
Create own memory cgroup  

### ISSUE THREAD

**Issue by Zqiang1211** [systemd/systemd#17749]
**Is your feature request related to a problem? Please describe.**
 
When test memcg with LTP,  the testcase  the test sample performs the following steps:
1. mkdir /dev/memcg
2. mount -t cgroup -o memory memcg /dev/memcg
3. echo 0 > /dev/memcg/memory.use_hierarchy

when exec step3  will appear "echo: write error: Device or resource busy" .
this error occurs because there are "system.slice" and "user.slice" subdirectories
in the /dev/memcg. 

**Describe the solution you'd like**
I want to create own memory cgroup, not affected by systemd.
 or rather  not include "system.slice" and "user.slice" subdirectories in /dev/memcg

**Describe alternatives you've considered**

**Comment by poettering** [comment]
On systemd systems the top-level hierarchy is owned and managed by systemd. if you want to manage your own cgroups, then request a delegated subtree. See:

https://systemd.io/CGROUP_DELEGATION

**Comment by Zqiang1211** [comment]
I tried to create own cgroup with the following command
systemd-run --unit=test.service --slice=test -p "Delegate=memory" top

I find "system.slice" and "user.slice" not exist in "/sys/fs/cgroup/memory/test.slice".
but  because in "/sys/fs/cgroup/memory" dir  the "memory.use_hierarchy == 1"
so in “test.slice” dir  exec "echo 0 > memory.use_hierarchy" will failed.

 Is there any way I can make my own cgroup detach from memory subtree ?

**Comment by poettering** [comment]
I can't parse this, sorry. Note that this is a not a support forum, but a bug tracker. If you need support, and have questions about systemd, contact the systemd-devel mailing list or a similar forum, but please do not use this bug tracker, where support questions are just noise. Thank you for understanding.
