### ISSUE TITLE
systemd-boot doesn't load entries from XBOOTLDR

### ISSUE THREAD

**Issue by robert-scheck** [systemd/systemd#17756]
**systemd version the issue has been seen with**
 246.6-1 (built myself, a rebuild from the Fedora SRPM)

**Used distribution**
 CentOS 8 (but also Fedora 32)

**Linux kernel version used** (`uname -a`)
 4.18.0-193.el8.x86_64, but doesn't really matter for this issue.

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
`systemd-bootx64.efi` does not load anything from XBOOTLDR.

**Unexpected behaviour you saw**
`systemd-bootx64.efi` only handles ESP.

I have two different entries for systemd-boot (different entries/labels to see the difference on boot-time between ESP and XBOOTLDR), and I only see the entry/label from ESP. If I delete the stuff on ESP, I only can reboot into the firmware setup. I never see the entry/label from XBOOTLDR.

**Steps to reproduce the problem**
```
$ lsblk -p /dev/vda -o NAME,PARTTYPE,MOUNTPOINT,FSTYPE
NAME        PARTTYPE                             MOUNTPOINT FSTYPE
/dev/vda                                                    
├─/dev/vda1 c12a7328-f81f-11d2-ba4b-00a0c93ec93b /boot/efi  vfat
├─/dev/vda2 bc13c2ff-59e6-4262-a352-b275fd6f7172 /boot      ext4
├─/dev/vda3 0fc63daf-8483-4772-8e79-3d69d8477de4 /          ext4
└─/dev/vda4 0657fd6d-a4ab-43c4-84e5-0933c84b4f4f [SWAP]     swap
$ 
```

```
$ find /boot
/boot
/boot/vmlinuz-4.18.0-193.el8.x86_64
/boot/config-4.18.0-193.el8.x86_64
/boot/initramfs-4.18.0-193.el8.x86_64.img
/boot/System.map-4.18.0-193.el8.x86_64
/boot/lost+found
/boot/loader
/boot/loader/entries
/boot/loader/entries/a80f77d954ed4d04af4924f7920145db-4.18.0-193.el8.x86_64.conf
/boot/efi
/boot/efi/EFI
/boot/efi/EFI/BOOT
/boot/efi/EFI/BOOT/BOOTX64.EFI
/boot/efi/EFI/systemd
/boot/efi/EFI/systemd/systemd-bootx64.efi
/boot/efi/EFI/efifs
/boot/efi/EFI/efifs/ext2.efi
/boot/efi/loader
/boot/efi/loader/entries
/boot/efi/loader/entries/a80f77d954ed4d04af4924f7920145db-4.18.0-193.el8.x86_64-test.conf
/boot/efi/loader/loader.conf
/boot/efi/loader/random-seed
/boot/efi/shellx64.efi
/boot/efi/vmlinuz-4.18.0-193.el8.x86_64
/boot/efi/initramfs-4.18.0-193.el8.x86_64.img
/boot/EFI
/boot/EFI/Linux
/boot/.vmlinuz-4.18.0-193.el8.x86_64.hmac
/boot/a80f77d954ed4d04af4924f7920145db
$ 

$ efibootmgr -v -r
DriverOrder: 0000
Driver0000* ext4	HD(1,GPT,85481640-57aa-4d36-9bd3-d31f4276dab1,0x800,0x12c000)/File(\EFI\efifs\ext2.efi)
$ 
```

The EfiFs driver is working fine, I can see the content of XBOOTLDR e.g. with UEFI shell (or inside the OMVF KVM UEFI firmware itself).

```
System:
     Firmware: UEFI 2.60 (EDK II 1.00)
  Secure Boot: disabled
   Setup Mode: setup
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot v246.6-1.el8
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Boot loader sets ESP partition information
          ESP: /dev/disk/by-partuuid/85481640-57aa-4d36-9bd3-d31f4276dab1
         File: └─/EFI/systemd/systemd-bootx64.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot/efi (/dev/disk/by-partuuid/85481640-57aa-4d36-9bd3-d31f4276dab1)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot v246.6-1.el8)
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot v246.6-1.el8)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0006
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/85481640-57aa-4d36-9bd3-d31f4276dab1
         File: └─/EFI/systemd/systemd-bootx64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/8c37fb1c-d003-48bd-a415-527eef335553)

[…]
```

**Comment by poettering** [comment]
hmm, your xbootldr partition is ext4? how is sd-boot supposed to be able to access that? you have an ext2 driver in the ESP i understand, but that would have to be loaded before sd-boot does its thing, but nothing is, or what am i missing?

We definitely should define some dir in the ESP where sd-boot will iterate through and load everything in there as driver. That way you could drop in your ext2 driver in that dir and that would be sufficient for sd-boot to load it and for what you want to work. I'd be happy to review/merge a patch for that!

Or what am I missing?

**Comment by robert-scheck** [comment]
My UEFI firmware is [EDK II](https://src.fedoraproject.org/rpms/edk2) inside a KVM virtual machine. That one offers to load an UEFI driver before the UEFI application (see `efibootmgr -v -r`), at least I have to assume this, because if I boot into the "UEFI Shell" (discovered by `systemd-bootx64.efi`, "UEFI Shell" was copied beforehand from `/usr/share/edk2/ovmf/Shell.efi` onto the ESP), I can – using the "UEFI Shell" – access my ext4 XBOOTLDR partition. If I remove the UEFI driver however, reboot, and try to repeat it, I can *not* access my ext4 XBOOTLDR partition from the "UEFI Shell" anymore. Thus my conclusion is that the UEFI driver must be already loaded before the `systemd-bootx64.efi`.

**Comment by asgeir** [comment]
This could be related to an issue I'm having on an ECS LIVA Q which has a Device Node Path, for the on-board eMMC, without a Messaging Device Path node.

`PciRoot(0)/Pci(0x1C,0x0)/Ctrl(0)/HD(1,GPT,461A5D9B-A120-4DDa-9FE6-E19D8ED3D52A)`

This fails the check in https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L2065 which I've been able to work around using the following patch (made against version 246.5, but the same idea applies to master)

```
diff -urN a/src/boot/efi/boot.c b/src/boot/efi/boot.c
--- a/src/boot/efi/boot.c       2020-09-12 12:16:33.000000000 +0000
+++ b/src/boot/efi/boot.c       2020-12-16 10:35:02.935396984 +0000
@@ -2037,6 +2037,11 @@
         return parent;
 }
 
+static BOOLEAN is_controller(EFI_DEVICE_PATH *node)
+{
+        return (DevicePathType(node) == HARDWARE_DEVICE_PATH) && (DevicePathSubType(node) == HW_CONTROLLER_DP);
+}
+
 static VOID config_load_xbootldr(
                 Config *config,
                 EFI_HANDLE *device) {
@@ -2062,7 +2067,7 @@
 
                 /* First, Let's look for the SCSI/SATA/USB/… device path node, i.e. one above the media
                  * devices */
-                if (DevicePathType(node) != MESSAGING_DEVICE_PATH)
+                if ((DevicePathType(node) != MESSAGING_DEVICE_PATH) && !is_controller(node))
                         continue;
 
                 /* Determine the device path one level up */
```

**Comment by robert-scheck** [comment]
Unfortunately, @asgeir's patch did not change the behaviour here, but I noticed a difference where I'm not sure if it's relevant:

```
$ efibootmgr -v
[…]
Boot0005* grubx64.efi	PciRoot(0x0)/Pci(0x2,0x3)/Pci(0x0,0x0)/HD(1,GPT,85481640-57aa-4d36-9bd3-d31f4276dab1,0x800,0x12c000)/File(\EFI\centos\grubx64.efi)
Boot0006* Linux Boot Manager	HD(1,GPT,85481640-57aa-4d36-9bd3-d31f4276dab1,0x800,0x12c000)/File(\EFI\systemd\systemd-bootx64.efi)
```

**Comment by asgeir** [comment]
If `PciRoot(0x0)/Pci(0x2,0x3)/Pci(0x0,0x0)/HD(1,GPT,85481640-57aa-4d36-9bd3-d31f4276dab1,0x800,0x12c000)` is how UEFI sees the device path (I verified by running UEFI Shell) it will trigger the same behavior as I saw. `config_load_xbootldr` assumes that a Messaging Device Path Node exists, and it looks for that to discover the parent device node for the partition.

**Comment by robert-scheck** [comment]
I'm not an UEFI expert, can I somehow verify your findings myself? Or can I somehow trick systemd-boot into some debug messages? Or can I somehow patch it to provide such details?

**Comment by robert-scheck** [comment]
So, that's how the mapping table looks for me:

![image](https://user-images.githubusercontent.com/10982488/102474081-7e962180-4058-11eb-86e7-78be14aa55ad.png)

**Comment by asgeir** [comment]
Going by the partition GUID your ESP seems to be FS1 in this screenshot. It is indeed missing a Messaging Device Path node so XBOOTLDR will not be discovered.

You could try the following, untested, patch. But it might enter an infinite loop if it can't open a block device for `PciRoot(0x0)/Pci(0x2,0x3)/Pci(0x0,0x0)`

```
diff -urN a/src/boot/efi/boot.c b/src/boot/efi/boot.c
--- a/src/boot/efi/boot.c       2020-09-12 12:16:33.000000000 +0000
+++ b/src/boot/efi/boot.c       2020-12-17 10:03:29.752026860 +0000
@@ -2041,7 +2041,7 @@
                 Config *config,
                 EFI_HANDLE *device) {
 
-        EFI_DEVICE_PATH *partition_path, *node, *disk_path, *copy;
+        EFI_DEVICE_PATH *partition_path, *node, *prev, *disk_path, *copy;
         UINT32 found_partition_number = (UINT32) -1;
         UINT64 found_partition_start = (UINT64) -1;
         UINT64 found_partition_size = (UINT64) -1;
@@ -2054,7 +2054,7 @@
         if (!partition_path)
                 return;
 
-        for (node = partition_path; !IsDevicePathEnd(node); node = NextDevicePathNode(node)) {
+        for (prev = partition_path, node = partition_path; !IsDevicePathEnd(node); prev = node, node = NextDevicePathNode(node)) {
                 EFI_HANDLE disk_handle;
                 EFI_BLOCK_IO *block_io;
                 EFI_DEVICE_PATH *p;
@@ -2062,7 +2062,10 @@
 
                 /* First, Let's look for the SCSI/SATA/USB/… device path node, i.e. one above the media
                  * devices */
-                if (DevicePathType(node) != MESSAGING_DEVICE_PATH)
+                if ((DevicePathType(node) == MEDIA_DEVICE_PATH) &&
+                    (DevicePathSubType(node) == MEDIA_HARDDRIVE_DP)) {
+                        node = prev;
+                } else if (DevicePathType(node) != MESSAGING_DEVICE_PATH)
                         continue;
 
                 /* Determine the device path one level up */
```

**Comment by robert-scheck** [comment]
* If XBOOTLDR is vfat, your [second patch](https://github.com/systemd/systemd/issues/17756#issuecomment-747347604) works for me :)
   * UEFI shell is able to successfully read my ext4 XBOOTLDR, if `Driver0000` is set, but systemd-boot is somehow not.
 * Your [first patch](https://github.com/systemd/systemd/issues/17756#issuecomment-746083687) does not work for me, independent whether XBOOTLDR is vfat or ext4 (`Driver0000` is set)

If I'm now not completely mistaken, there are two different issues:

  1. EDK II (UEFI firmware) is missing a Messaging Device Path node, which is not (yet?) being worked around by systemd-boot  
     → @asgeir, do you see a chance to get your [second patch](https://github.com/systemd/systemd/issues/17756#issuecomment-747347604) into a PR that @poettering could review for merging?
  2. systemd-boot behaves differently than UEFI shell, if `Driver0000` is set (this was the original reason for opening this issue)

**Comment by asgeir** [comment]
Before my patch could be submitted the infinite loop issue would have to be fixed, and I don't know enough about UEFI to know if this approach of just selecting whatever comes before the HD node will work in general.

**Comment by robert-scheck** [comment]
> Before my patch could be submitted the infinite loop issue would have to be fixed, and I don't know enough about UEFI to know if this approach of just selecting whatever comes before the HD node will work in general.

Maybe @poettering could help here?

**Comment by robert-scheck** [comment]
@poettering, do you see a chance to optimize the patch from @asgeir to make systemd-boot at least usable for KVM guests having UEFI OVMF firmware (which about every Linux distribution has)?

**Comment by poettering** [comment]
I am a bit surprised that this should be necessary, given that I tested things with the OVMF/EDK stuff myself (though only with vfat as xbootldr partition)

**Comment by poettering** [comment]
we have to work with the firmware that we got, so yes, we should merge a work around for this. But please submit as PR. And please find a better way that mucking with the iterator so weirdly...

And it should come with with a comment that explains in-situ what the work-around works around

**Comment by robert-scheck** [comment]
> I am a bit surprised that this should be necessary, given that I tested things with the OVMF/EDK stuff myself (though only with vfat as xbootldr partition)

Not sure if it makes a difference, I'm using the Q35 chipset in KVM, thus e.g. `-machine pc-q35-rhel7.6.0` (as e.g. shipped with RHV 4.x).

**Comment by medhefgo** [comment]
Can't say I can reproduce this myself with qemu. What qemu args are used to launch the VM?

**Comment by robert-scheck** [comment]
> Can't say I can reproduce this myself with qemu. What qemu args are used to launch the VM?

In case it's still relevant:

```
/usr/libexec/qemu-kvm -name guest=systemd-boot,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-systemd-boot/master-key.aes -machine pc-q35-rhel7.6.0,accel=kvm,usb=off,smm=on,dump-guest-core=off -cpu Skylake-Client-IBRS,ss=on,vmx=on,hypervisor=on,tsc_adjust=on,clflushopt=on,md-clear=on,stibp=on,ssbd=on,pdpe1gb=on,ibpb=on -global driver=cfi.pflash01,property=secure,value=on -drive file=/usr/share/OVMF/OVMF_CODE.secboot.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/var/lib/libvirt/qemu/nvram/systemd-boot_VARS.fd,if=pflash,format=raw,unit=1 -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid f9eaa6bf-d306-4e22-8bb9-c6e9a42a6fed -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=26,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1 -boot strict=on -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-pci-bridge,id=pci.3,bus=pci.1,addr=0x0 -device pcie-root-port,port=0x12,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x2 -device pcie-root-port,port=0x13,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x3 -device pcie-root-port,port=0x14,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x4 -device pcie-root-port,port=0x15,chassis=7,id=pci.7,bus=pcie.0,addr=0x2.0x5 -device pcie-root-port,port=0x16,chassis=8,id=pci.8,bus=pcie.0,addr=0x2.0x6 -device ich9-usb-ehci1,id=usb,bus=pcie.0,addr=0x1d.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pcie.0,multifunction=on,addr=0x1d -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pcie.0,addr=0x1d.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pcie.0,addr=0x1d.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.4,addr=0x0 -drive file=/var/lib/libvirt/images/systemd-boot.img,format=raw,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,scsi=off,bus=pci.5,addr=0x0,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -drive file=/var/lib/libvirt/images/centos.iso,format=raw,if=none,id=drive-sata0-0-0,media=cdrom,readonly=on -device ide-cd,bus=ide.0,drive=drive-sata0-0-0,id=sata0-0-0 -netdev tap,fd=28,id=hostnet0,vhost=on,vhostfd=29 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:1b:02:3c,bus=pci.2,addr=0x0 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 127.0.0.1:0 -device VGA,id=video0,vgamem_mb=16,bus=pcie.0,addr=0x1 -device virtio-balloon-pci,id=balloon0,bus=pci.6,addr=0x0 -object rng-random,id=objrng0,filename=/dev/urandom -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.7,addr=0x0 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```

That's purely what `virt-manager` created.

**Comment by s3rgeym** [comment]
FISRT CHECK FLAGS:

```bash
parted /dev/sda p
# set extended boot flag for partition for /boot mountpoint
parted /dev/sda set <PART-NUMBER> bls_boot
```

YOU SHOULD ADD SYSTEMD DRIVERS FOR FILESYSTEM:

```bash
pacman -Syu
# efi drivers for most common filesystems
pacman -S efifs
# driver for ext4, ext3 and ext2
pacman -Qlq efifs | grep 'ext.*x64'
mkdir /efi/EFI/systemd/drivers
cp $(pacman -Qlq efifs | grep 'ext.*x64') /efi/EFI/systemd/drivers/
```
