### ISSUE TITLE
Systemd recursively chowns RuntimeDirectory and all of it's contents on service reload

### ISSUE THREAD

**Issue by uvNikita** [systemd/systemd#17752]
**systemd version the issue has been seen with**
246

**Used distribution**
Fedora, NixOs

**Linux kernel version used** (`uname -a`)
Linux localhost.localdomain 5.9.10-200.fc33.x86_64

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Folders specified in `RuntimeDirectory` and all of their contents retain their ownership after reloading the service.

**Unexpected behaviour you saw**
Folders specified in `RuntimeDirectory` and all of their contents are chowned back to root user after reloading the service.

**Steps to reproduce the problem**
Create the following service `/etc/systemd/system/test.service`:

```
[Service]
ExecStart=/bin/bash -c 'while true; do echo 'running'; sleep 5; done'
ExecStartPost=/bin/bash -c 'touch /run/test/inner/file'
ExecStartPost=/bin/bash -c 'chown -R 999:999 /run/test/inner'
ExecReload=/bin/bash -c 'echo reloading'
RuntimeDirectory=test
RuntimeDirectory=test/inner

```

```bash
$ systemctl start test.service
$ ls -la /run/test/inner/
total 0
drwxr-xr-x 2  999 999 60 Nov 27 14:46 .
drwxr-xr-x 3 root root  60 Nov 27 14:46 ..
-rw-r--r-- 1  999 999  0 Nov 27 14:46 file

$ systemctl reload test.service
$ ls -la /run/test/inner/
total 0
drwxr-xr-x 2 root root 60 Nov 27 14:44 .
drwxr-xr-x 3 root root 60 Nov 27 14:44 ..
-rw-r--r-- 1 root root  0 Nov 27 14:44 file
```

I'm not 100% sure if this is a bug, so feel free to close the issue if it's intended behavior.

**Comment by uvNikita** [comment]
Currently I can use `TemporaryFileSystem=/run/test/inner` to achieve similar result without ownership changes on service reload.

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=

> Except in case of ConfigurationDirectory=, the innermost specified directories will be owned by the user and group specified in User= and Group=. If the specified directories already exist and their owning user or group do not match the configured ones, all files and directories below the specified directories as well as the directories themselves will have their file ownership recursively changed to match what is configured.

**Comment by uvNikita** [comment]
@bluca thanks for pointing it out!

Closing, sorry for the noise.
