### ISSUE TITLE
systemd-detect-virt detects nested UML inside KVM incorrectly

### ISSUE THREAD

**Issue by obbardc** [systemd/systemd#17754]
**systemd version the issue has been seen with**
 > 241 (and latest master)

**Used distribution**
 > Debian Sid

**Linux kernel version used** (`uname -a`)
 > Linux obbardc-laptop 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > When running UML inside KVM (i.e a AWS machine), `systemd-detect-virt` should report that it is running as uml

**Unexpected behaviour you saw**
 > When running UML inside KVM (i.e a AWS machine), `systemd-detect-virt` reports running using kvm rather than uml :-(

**Steps to reproduce the problem**
 > Running a UML system inside a KVM host, then run `systemd-detect-virt`

Running UML locally, with no KVM everything is nice:
```
SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Found container virtualization none.
No virtualization found in DMI
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen does not exist
This platform does not support /proc/device-tree
UML virtualization found in /proc/cpuinfo
Found VM virtualization uml
uml
```

Running UML inside a KVM machine:
```
Found container virtualization none.
No virtualization found in DMI
Virtualization found, CPUID=KVMKVMKVM
Found VM virtualization kvm
kvm
```

i'm pretty sure this is because uml passes through the CPUID virtualisation bits from the host.
Question I have is, does the bug lie in systemd or uml, I can prepare a patch for either?

**Comment by poettering** [comment]
probably something to fix in our codebase, we should check for uml first and check cpuid only after that.
