### ISSUE TITLE
Add vlan protocol type in networkd

### ISSUE THREAD

**Issue by walbit-de** [systemd/systemd#17777]
Hello, I have made a change with which it is possible to tell systemd-networkd the protocol for VLAN adapters.
The Linux kernel uses the VLAN protocol 802.1q as standard, but also supports 802.1ad. With this change you can select the desired protocol in the config section ([Vlan] Protocol = 802.1..).
I need rights to create a feature branch and a pull request.
[vlan.txt](https://github.com/systemd/systemd/files/5615086/vlan.txt)

**Comment by yuwata** [comment]
The attached patch looks incomplete, but anyway, please submit it as a PR. Then, we can review it easily.

**Comment by walbit-de** [comment]
Thanks for your answer. What do you mean with incomplete.
I don't have the permissions to create pull requests..

**Comment by keszybz** [comment]
@walbit-de no special permissions are required. See https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github for a detailed tutorial.

**Comment by walbit-de** [comment]
Thanks for the link! I got it.
