### ISSUE TITLE
RFE: Capability for system-wide user mount/automount units (allow symlinking?)

### ISSUE THREAD

**Issue by scruloose** [systemd/systemd#17789]
**Is your feature request related to a problem? Please describe.**
I use systemd user mount/automount pairs to provide on-demand mounting of sshfs shares. (Each user connects with their own key so the remote NAS server can enforce correct access controls.) When a single user has a mount unit in `~.config/systemd/user/`, it's easy to satisfy the requirement that the unit file name match the absolute path to the mountpoint. But if you want to set this up for all users (ie in `/etc/systemd/user/path-to-foo.mount`), that requirement is in direct conflict with the necessity for each user to have their own mountpoint. As far as I can tell, this makes it simply impossible to define a working system-wide user mount unit. According to the mount and automount units' man pages, neither of those unit types can be templated, so that avenue to incorporate the individual username into the filenames of an instantiated mount/automount pair is not available. Likewise symlinking.

**Describe the solution you'd like**
I would like systemd's facility to define a system-wide user unit in one place for all users to include mount and automount units. I would guess that allowing symlinking to mount and automount units would be the easiest and cleanest solution. Then no matter what the unit files in `/etc/systemd/user` are named, when a user enables the automounnt or starts the mount *via their own symlinks*, the file name requirements could be enforced on the symlinks — eg `~/config/systemd/user/home-username-mountpoint.mount → /etc/systemd/user/remotehostname.mount`. This would make it easy to set up per-user mountpoints under `/mnt` or in their home dirs or wherever, with one point of configuration, while preserving the "unit file name must correspond to the absolute path to the mountpoint" validation.

**Describe alternatives you've considered**
Interpreting variables or specifiers in the unit file name would do it. Dropping the requirement for mount and automount unit files to be named for the absolute path to the mountpoint would do it, though I assume that requirement is there for a reason. I *think* allowing templating of mount and automount units could do it, eg a template unit file `/etc/systemd/unit/mnt@.mount`  containing `Where=/mnt/%i`, then instantiated with `systemctl enable mnt@$USER-mountpoint.mount`, though the unchanging template prefix would be a limitation.

As far as I know, the only option as things stand is to duplicate the mount and automount unit files, putting a copy in every user's `~/config/systemd/user` directory. Using specifiers, I don't have to change the *contents* of those files for every user, but each pair's filenames have to be different for each user. And, of course, any future changes to the mount/automount configuration has to be applied to every user's copy.

**Comment by poettering** [comment]
automount units are a privileged facility, they are not available to regular users.

It appears to me that the better approach to what you are trying to do is write a generator that generates the right .mount unit from the user's identity and ssh creds. See https://www.freedesktop.org/software/systemd/man/systemd.generator.html for details.

**Comment by scruloose** [comment]
Ah, I see. 

Thanks for the pointer. I'll look into the generator approach.
