### ISSUE TITLE
kmod-static-nodes.service: Making gutenprint the default printer driver

### ISSUE THREAD

**Issue by es20490446e** [systemd/systemd#17786]
I don't know if this is the right place to report this. This should be concerning the software in charge of selecting the printer drivers, and kmod-static-nodes seems to be the one on my system.

I'm using Manjaro with systemd 246.6. [system-config-printer ](https://github.com/OpenPrinting/system-config-printer/issues/188)is usually who performs the following actions, but it isn't installed on my system. So my guess is that now is done by systemd.

---

It seems that many printers don't support printing on glossy paper except if they are using gutenprint. For example, see here.

That is because the black ink isn't really designed to print on that type of paper, so what gutenprint or drivers on Windows do is printing black as a light grey. Otherwise the ink never dries out.

The thing is that without gutenprint CUPS doesn't seem capable of doing that, at least for many printers. So my suggestion is simple, that when you connect a new printer to the system, if gutenprint is available, it is selected as the default driver instead of the raw printer drivers.

**Comment by mbiebl** [comment]
I don't see the relation between kmod-static-nodes and the default printer driver (the later ist something cups specific).
Please elaborate.

**Comment by poettering** [comment]
This is not the right place. Please talk to your downstream distro.

systemd has no relation to printer drivers, this is entirely the wrong place to report this. Sorry.
