### ISSUE TITLE
Stopping user mount unit (FUSE) fails

### ISSUE THREAD

**Issue by vojta001** [systemd/systemd#17788]
**systemd version the issue has been seen with**
 > systemd 246 (246)

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)
 > 5.4.77

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Unmounting the FUSE FS

**Unexpected behaviour you saw**
 > Failure and `umount: /path: must be superuser to unmount.` printed in logs

**Steps to reproduce the problem**
 > Create a user mount unit e. g.
> ```
> [Install]
> WantedBy=graphical-session.target
>
> [Mount]
> Options=resolve-symlinks
> Type=fuse.bindfs
> What=/foo/bar
> Where=/path
>
> [Unit]
> After=graphical-session-pre.target
> Description=FooBar
> PartOf=graphical-session.target
> ```
>
> Start it. It will start just fine with recent enough util-linux (#13741). Then stop it. It will fail.

**Comment by yuwata** [comment]
Hmm, this issue seems a util-linux's bug or limitation. We invoke `umount` with `-c` option. But, for fuse mounts, unmounting with `-c` causes the failure:
```
$ mount -t fuse.sshfs localhost:/tmp ~/aaa
$ umount -c /home/watanabe/aaa
umount: /home/watanabe/aaa: must be superuser to unmount.
$ echo $?
32
$ umount /home/watanabe/aaa
$ echo $?
0
```

cc @karelzak?

**Comment by yuwata** [comment]
Oh, it seems already fixed in util-linux with https://github.com/karelzak/util-linux/commit/77a37084898d6df73783a53135a26b4c8b99bf15.

**Comment by poettering** [comment]
OK, let's close this here, then. @vojta001 please follow up with @karelzak over at util-linux if there's more to fix. THis doesn't look like something to fix in systemd here.

**Comment by vojta001** [comment]
Thank you both for your advice. I'll wait for the next util-linux release and let you know if it doesn't help.

**Comment by vojta001** [comment]
I can confirm with systemd 247 and util-linux 2.36.1, it works without problems.

Thanks to everyone involved
