### ISSUE TITLE
sd_notify_barrier() breaks notify; possible denial-of-service attacks

### ISSUE THREAD

**Issue by ensc** [systemd/systemd#17795]
Using `systemd-notify --ready` puts systemd in a state where it does not receive notify messages anymore.  Problem can be reproduced by

```
NOTIFY_SOCKET=/run/systemd/notify systemd-notify --ready
NOTIFY_SOCKET=/run/systemd/notify systemd-notify --ready
```

where second command hangs and systemd stops to receive further notifies. 

Problem happens because  the `recvmsg()` gets the `MSG_CTRUNC` flag set:

```
10199 sendmsg(3, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/notify"}, msg_namelen=22, msg_iov=[{iov_base="READY=1\nMAINPID=10198", iov_len=21}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=10198, uid=0, gid=0}}], msg_controllen=32, msg_flags=0}, MSG_NOSIGNAL) = 21
1     recvmsg(32, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="READY=1\nMAINPID=10198", iov_len=4096}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=10198, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_CMSG_CLOEXEC}, MSG_TRUNC|MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 21

10199 sendmsg(5, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/notify"}, msg_namelen=22, msg_iov=[{iov_base="BARRIER=1", iov_len=9}],               msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[4]}],                            msg_controllen=24, msg_flags=0}, MSG_NOSIGNAL) = 9
1     recvmsg(32, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="BARRIER=1",              iov_len=4096}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=10199, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_CTRUNC|MSG_CMSG_CLOEXEC}, MSG_TRUNC|MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 9
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1903106 for more extensive logs

Beside the problem `MSG_CTRUNC` problem, further processing is disabled because the fd is `EPOLL_CTL_DEL`.  This seems to open ways for denial-of-service attacks where a user sends messages with large payloads.

**systemd version the issue has been seen with**
 > systemd-246.6-3.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > 5.9.10-200.fc33.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > - systemd works with sd_notify_barrier()
 > - systemd does not stop receiving valid messages after invalid ones

**Unexpected behaviour you saw**
 > systemd stops to receive notification after sd_notify_barrier() has been used
 > systemd  does not handle `BARRIER=1` messages

**Steps to reproduce the problem**
 > 1. run `NOTIFY_SOCKET=/run/systemd/notify systemd-notify --ready`
 > 2. run `NOTIFY_SOCKET=/run/systemd/notify systemd-notify --ready` a second time

**Comment by ensc** [comment]
The `MSG_CTRUNC` flag is caused by SELinux 

```
type=AVC msg=audit(1606850930.657:1138): avc:  denied  { write } for  pid=1 comm="systemd" path="pipe:[657841]" dev="pipefs" ino=657841 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=fifo_file permissive=0
```

But systemd should ignore such conditions instead of disabling notify completely.

**Comment by poettering** [comment]
I tried to reproduce to no success and I am not sure I grok this. 

If we see MSG_CTRUNC here we are apparently miscalculating the control buffer size, but how can that happen? what kind of aux data is attached to those messages we apparently aren't expecting? You are suggesting this has something to do with selinux? But what is selinux attaching there? Your strace shows nothing being actually attached, maybe selinux is just broken in the kernel to set this flag? why would there be more data attached when selinux is on then otherwise?

**Comment by poettering** [comment]
There's a fix waiting in #18314 now, which makes systemd handle this gracefully. But i still wonder why selinux even wants to insert control data into the datagrams. Something seems to be off with selinux there. 

I am not an selinux guy myself though, someone who cares about selinux should try to figure out what is precisely going on there.

**Comment by bluca** [comment]
> I tried to reproduce to no success and I am not sure I grok this.
> 
> If we see MSG_CTRUNC here we are apparently miscalculating the control buffer size, but how can that happen? what kind of aux data is attached to those messages we apparently aren't expecting? You are suggesting this has something to do with selinux? But what is selinux attaching there? Your strace shows nothing being actually attached, maybe selinux is just broken in the kernel to set this flag? why would there be more data attached when selinux is on then otherwise?

@pebenito this looks like something we should care about, given a non-functioning notify socket would be, uh, _problematic_. Any idea what could be happening?

**Comment by pebenito** [comment]
I don't see how this is related to SELInux. The referenced denial message from SELinux is systemd attempting to write to an unnamed pipe. Is it fixed if this access is allowed or SELinux is permissive/disabled?

**Comment by ensc** [comment]
SELinux removes the FDs (when prohibited; see https://bugzilla.redhat.com/show_bug.cgi?id=1903106#c4) and sets `MSG_CTRUNC`

**Comment by pebenito** [comment]
I can't follow your logic about the denial causing the `MSG_CTRUNC` to be set. Your strace output in the bug doesn't to show what fd 32 is, but `recvmsg()` is clearly a socket function, and the SELinux denial has `tclass=fifo_file`, which is a pipe. It would seem that the denial is either a red herring or a separate problem to the `-EXFULL`.

If you need to allow the access that is denied, then this likely means that when systemd tries to use the pipe fd that systemd-notify passes over the notify socket, it gets denied, and that's where things go wrong.

**Comment by poettering** [comment]
> I can't follow your logic about the denial causing the `MSG_CTRUNC` to be set. Your strace output in the bug doesn't to show what fd 32 is, but `recvmsg()` is clearly a socket function, and the SELinux denial has `tclass=fifo_file`, which is a pipe. It would seem that the denial is either a red herring or a separate problem to the `-EXFULL`.

the fd that sd_notify_barrier() sends via the AF_UNIX socket is a pipe. i.e. there are two fds involved here: the transport fd and the parcel fd. The parcel fd is a pipe and sent over the transport fd which is an AF_UNIX/SOCK_DGRAM socket.

**Comment by poettering** [comment]
i think @ensc's analysis makes sense. the strace he posted shows tht a BARRIER=1 message was delivered to PID 1, which is supposed to carry a pipe fd, but the strace shows that it arrived without one.

If you ask me it's a really poor choice of selinux to suppress the fd and set MSG_CTRUNC. The usual logic of programs seeing MSG_CTRUNC is to enlarge the control buffer and try again. If programs do that in this case they'll busy loop however. I think it would make more sense for selinux to prohibit the full datagram if it wants to disallow passing of some fd over. It's a really bad idea to muck with the integrity of the messages sent over.

what does selinux actually do if i send three fds over, and the middle one is disallowed by policy? does it pass the other two over, and the array becomes one item shorter? that's just evil.

**Comment by poettering** [comment]
anyway, i would claim that the bug is a bug in selinux or at least a misfeature/misdesign. They should fix that, and make sure MSG_CTRUNC is clear indication for clients that enlarging the buffer would work.

in the meantime systemd will now ignore such messages that are corrupted by selinux, given that #18314 has been merged.

**Comment by pebenito** [comment]
Looking through the kernel some more, I determined what is happening. It is not SELinux corruption. This is the kernel socket code response to the SELinux denial. On receive, it iterates over the fds in the message to add them to the receiving process. For each, there is an LSM check. If that fails on any of the fds, then it breaks out of the loop. This is not SELinux specific; any LSM could deny this access and induce this behavior. If you object to this behavior then you will need to talk to the kernel networking people.

This is the most relevant part of the kernel code: https://elixir.bootlin.com/linux/latest/source/net/core/scm.c#L309 .  You can see at the bottom of the function where `MSG_CTRUNC` can be set if not everything is received. receive_fd_user() has the LSM check (a few calls deeper).

In the context of this issue, SELinux checks if the receiver can access the object that the fd points at, and denies the access to the one pipe, so you get the `MSG_CTRUNC`. This is why the denial is on the pipe, not the socket. The only thing for the SELinux people to do is to allow the access in the policy so this function can work correctly.

**Comment by bluca** [comment]
Thanks Chris, this is super helpful!

**Comment by poettering** [comment]
> Looking through the kernel some more, I determined what is happening. It is not SELinux corruption. This is the kernel socket code response to the SELinux denial. On receive, it iterates over the fds in the message to add them to the receiving process. For each, there is an LSM check. If that fails on any of the fds, then it breaks out of the loop. This is not SELinux specific; any LSM could deny this access and induce this behavior. If you object to this behavior then you will need to talk to the kernel networking people.

Dunno, selinux is the primary user of the LSM logic. Sure, not the only one, but I bet this was added for selinux in the first place, probably even by selinux people, and not by networking people.

I mean, I personally don't even have selinux enabled, I won't follow up on this. I just think that the behaviour with selinux enabled here (regardess if it's selinux own codebase or lsm in general at fault here) is really broken: it breaks with assumptions userspace makes, and will likely break not just here but at other places too. 

At the very least, this should documented. The man page expressly currently says:

> MSG_CTRUNC
>              indicates that some control data was discarded due to lack of space in the buffer for ancillary data.

which is apparently wrong. it might also indicate that stuff was dropped due to security policy.

(But quite frankly, just documenting this is chickening out, since it just means userspace could never generically do a control datat sizing loop properly: i.e. if userspace sees MSG_CTRUNC there's no sane strategy how to handle that: it could be that increasing the buffer might help, it could mean tht it doesn't. if one tries anyway one will enter an endless loop... that's just a really broken interface)
