### ISSUE TITLE
Prevent frequent updates of the /run/systemd/resolve/resolv.conf file

### ISSUE THREAD

**Issue by taskset** [systemd/systemd#17796]
The application on one of our servers may create more than 100 eth ports (these eth ports do not have ip address and dns), but we have observed that the /run/systemd/resolve/resolv.conf file has been updated more than 100 times.

We use the following audit rules to monitor:
```
# auditctl -w /run/systemd/resolve -p wx  -k XXX
```

Then the following information is frequently printed in the log:
```
type=SYSCALL msg=audit(1606839337.454:9553): arch=c000003e syscall=82 success=yes exit=0 a0=5594771cb030 a1=55947674e240 a2=0 a3=55947674dcff items=5 ppid=1 pid=96504 auid=4294967295 uid=193 gid=193 euid=193 suid=193 fsuid=193 egid=193 sgid=193 fsgid=193 tty=(none) ses=4294967295 comm="systemd-resolve" exe="/usr/lib/systemd/systemd-resolved" key="XXX"
…
type=SYSCALL msg=audit(1606839358.792:9556): arch=c000003e syscall=82 success=yes exit=0 a0=55947713e050 a1=55947674e240 a2=0 a3=55947674dcff items=5 ppid=1 pid=96504 auid=4294967295 uid=193 gid=193 euid=193 suid=193 fsuid=193 egid=193 sgid=193 fsgid=193 tty=(none) ses=4294967295 comm="systemd-resolve" exe="/usr/lib/systemd/systemd-resolved" key="XXX"
…
```

```
#define __NR_rename 82

# cat /var/log/audit/audit.log | grep XX | grep  'syscall=82' | wc -l
155
```

In fact, the content of the /run/systemd/resolve/resolv.conf file is the same, but it has been unconditionally updated 155 times.

**Comment by floppym** [comment]
What problem does this cause?

**Comment by w-simon** [comment]
> What problem does this cause?

hi, we have observed at least the following two problems:
1. systemd-resolved occupies 100% cpu.
2. If another program is doing bind mount /etc/resolv.conf file at the same time, it may fail.

**Comment by mk-pmb** [comment]
Useless writes may cause
* less useful file modified date,
* additional noise in inotify,
* additional network traffic on network-backed storage,
* excessive wear on some kinds of storage media,
* waste of paper trail in very paranoid setups ;-)
* probably other problems.

**Comment by poettering** [comment]
Duplicate of #17577

**Comment by floppym** [comment]
> Useless writes may cause
> 
> * additional network traffic on network-backed storage,
> * excessive wear on some kinds of storage media,

These don't apply to files in /run, which is always a tmpfs and lives in memory.
