### ISSUE TITLE
assigning IP address sometimes fails with Cannot assign requested address

### ISSUE THREAD

**Issue by agners** [systemd/systemd#1784]
Using systemd-networkd to configure a RNDIS network interface (using the USB Gadget ConfigFS) seems to expose a race condition. The network configuration looks rather simple:

```
[Match]
Name=usb0

[Network]
Address=192.168.11.1/24
DHCPServer=yes
```

During boot a systemd service configures the USB Gadget device. In the bad case, the log output looks like this:

```
# journalctl -b 0 | grep -e networkd -e usb0
Nov 05 02:44:48 host-imx6 systemd[1]: Listening on networkd rtnetlink socket.
Nov 05 02:44:48 host-imx6 systemd[1]: Starting networkd rtnetlink socket.
Nov 05 02:44:54 host-imx6 systemd-networkd[482]: Enumeration completed
Nov 05 02:44:54 host-imx6 kernel: usb0: HOST MAC ce:06:c6:f8:eb:a7
Nov 05 02:44:54 host-imx6 systemd-networkd[482]: usb0            : usb0            : could not bring up interface: Cannot assign requested address
Nov 05 02:44:54 host-imx6 systemd-networkd[482]: usb0            : link configured
Nov 05 02:44:54 host-imx6 kernel: usb0: MAC d2:33:9e:fe:bf:3e
```

The interface seems to have a IP address assigned, but it is down.

```
# ip addr show dev usb0
4: usb0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d2:33:9e:fe:bf:3e brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.1/24 brd 192.168.11.255 scope global usb0
       valid_lft forever preferred_lft forever
```

In the working case (DHCP works and Link is up):

```
# journalctl -b 0 | grep -e networkd -e usb0
Nov 05 02:54:57 host-imx6 systemd[1]: Listening on networkd rtnetlink socket.
Nov 05 02:54:57 host-imx6 systemd[1]: Starting networkd rtnetlink socket.
Nov 05 02:55:00 host-imx6 systemd-networkd[482]: Enumeration completed
Nov 05 02:55:01 host-imx6 kernel: usb0: HOST MAC 46:bc:c8:96:ad:49
Nov 05 02:55:01 host-imx6 kernel: usb0: MAC 82:03:74:c4:29:5f
Nov 05 02:55:01 host-imx6 kernel: IPv6: ADDRCONF(NETDEV_UP): usb0: link is not ready
Nov 05 02:55:01 host-imx6 avahi-daemon[438]: Joining mDNS multicast group on interface usb0.IPv4 with address 192.168.11.1.
Nov 05 02:55:01 host-imx6 avahi-daemon[438]: New relevant interface usb0.IPv4 for mDNS.
Nov 05 02:55:01 host-imx6 avahi-daemon[438]: Registering new address record for 192.168.11.1 on usb0.IPv4.
Nov 05 02:55:01 host-imx6 systemd-networkd[482]: usb0            : usb0            : could not bring up interface: Invalid argument
Nov 05 02:55:01 host-imx6 systemd-networkd[482]: usb0            : link configured
Nov 05 02:55:01 host-imx6 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
Nov 05 02:55:01 host-imx6 systemd-networkd[482]: usb0            : gained carrier
Nov 05 02:55:03 host-imx6 avahi-daemon[438]: Registering new address record for fe80::214:2dff:feff:ffff on usb0.*.
```

In both cases networkd claims that it could not bring up the interface, but with different reasons ("Invalid argument" vs "Cannot assign requested address"). It seems that  in the working case the two kernel messages reporting the assigned MAC addresses

Note that this is on a ARM based embedded device with a dual-core CPU. The serial console is on which imposes some delays between kernel log messages...

**Comment by vaijab** [comment]
I think I am hitting the same issue here.

I have an EC2 (CoreOS) instances with systemd version 255. I attach network interfaces after instances finished booting, but some of them fail to bring up eth1 with the above error messages.

Some instances happily bring up eth1 and get an IP from DHCP, so it seems that there is some sort of race.

**Comment by yuwata** [comment]
@vaijab Is `systemd-udevd` running in the system?

> I have an EC2 (CoreOS) instances with systemd version 255.

v255 is not released yet :-p

**Comment by vaijab** [comment]
> Is `systemd-udevd` running in the system?

@yuwata I no longer have access to the system. Sorry, I cannot help with this issue.

**Comment by yuwata** [comment]
@agners Is this issue still reproducible on your systems? If so, please provide the debugging logs of udevd and networkd.

@vaijab No problem. Sorry for late to tackling this issue.

**Comment by yuwata** [comment]
Let's close this. If you still have similar problems, then please file as a new issue with debugging logs.
