### ISSUE TITLE
journalctl -D does not show entries from some .journal files in the directory

### ISSUE THREAD

**Issue by Jcpetrucci** [systemd/systemd#17841]
It seems that after I upgraded from CentOS 7.8 (systemd-219-73.el7_8.9.x86_64) to 7.9 (systemd-219-78.el7_9.2.x86_64), this issue began.  

I use systemd-journal-upload on my clients and systemd-journal-remote on a central journal server.  When I want to review logs from all clients, I use `journalctl -D /var/log/journal/remote`.  I expect this command to show journal entries from all remote clients.  After updating, only _some_ remote clients' output appears.

By comparing `ls -l /var/log/journal/remote/` against the files "added" in the following command, I can see that all of the expected files are supposedly being included in the journalctl query:

```
$ sudo SYSTEMD_LOG_LEVEL=debug journalctl -D /var/log/journal/remote
Considering root directory '/var/log/journal/remote'.
Root directory /var/log/journal/remote added.
File /var/log/journal/remote/remote-10.0.0.1.journal added.
File /var/log/journal/remote/remote-10.0.0.2.journal added.
File /var/log/journal/remote/remote-10.0.0.3.journal added.
File /var/log/journal/remote/remote-10.0.0.4.journal added.
....
```

If I generate journal entries on 10.0.0.1 or 10.0.0.3, for example by running `echo test | systemd-cat`, I do not see those entries using `journalctl -D /var/log/journal/remote`.  However, if I **directly** inspect the journal file such as `journalctl --file=/var/log/journal/remote/remote-10.0.0.1.journal` though, I see the entries just fine.

Version information:
$ journalctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

$ yum list installed | grep systemd
systemd.x86_64                  219-78.el7_9.2            
 
$ head -1 /etc/*release
==> /etc/centos-release <==
CentOS Linux release 7.9.2009 (Core)

**Comment by vcaputo** [comment]
Considering how old v219 is, I don't think you'll be getting any help here as it's not a support forum.

Either reproduce the problem with a current version, or contact an actual support provider for your distro.

**Comment by poettering** [comment]
Please read the submision form, it should have made very clear that this is an upstream bug and issue tracker for recent *upstream* versions, 219 is waaaaay too old. Please contact your downstream distro about that.

**Comment by jakob-tsd** [comment]
I hit the same issue on:

```
Debian Buster, systemd 241-7~deb10u6
```
But I'm happy to report that things seem to work ok on:
```
Debian Bullseye, systemd 247.3-1
```

For fellow Debian Buster users who are not ready do upgrade I suggest to install systemd 247 from buster-backports:
https://packages.debian.org/search?keywords=systemd&searchon=names&suite=all&section=all
