### ISSUE TITLE
systemd-resolved (v245) not accepting DNS-Server with Port

### ISSUE THREAD

**Issue by f0o** [systemd/systemd#17858]
According to the Docs (https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNS=) this should be supported, however when trying it on v245 it just fails with `Invalid argument`.

full config:
```
[Resolve]
DNS=127.0.0.1:5053
Domains=~custom.local
Cache=no
```

**systemd version the issue has been seen with**
 > systemd 245 (237-12140-g29cb7c4+)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

**Used distribution**
 > Flatcar Linux

**Linux kernel version used** (`uname -a`)
 > 5.4.77-flatcar

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > systemd-resolved to accept a DNS Server with Port

**Unexpected behaviour you saw**
 > Failed to add DNS server address '127.0.0.1:5053', ignoring: Invalid argument

**Steps to reproduce the problem**
 > Add DNS=127.0.0.1:5053 to /etc/systemd/resolved.conf

**Comment by f0o** [comment]
I maybe have found the issue, https://archive.is/DLEiN#selection-161.0-185.125 (assuming this snapshot is accurate) indicates that 245 does not support Ports yet. Is this accurate?

**Comment by bluca** [comment]
> I maybe have found the issue, https://archive.is/DLEiN#selection-161.0-185.125 (assuming this snapshot is accurate) indicates that 245 does not support Ports yet. Is this accurate?

That's correct, it was added in 246:

https://github.com/systemd/systemd/blob/v246/NEWS#L285

**Comment by bluca** [comment]
Closing - please reopen if you find any issue with this feature in v246. Thanks!
