### ISSUE TITLE
Anyone else noticed something related to systemd seeming to be interfering it or preventing Xfce desktop from functioning correctly? (in particular, settings not being saved across reboots)

### ISSUE THREAD

**Issue by DwarfFighterCleric** [systemd/systemd#17867]
I don't know if this is something that only affects Xfce (tested latest Manjaro, MX Linux and Xubuntu after hardware upgrade)  
Desktop settings and general system settings (keyboard layout, mouse settings, keyboard hotkeys, panel settings, Thunar settings even, etc etc) are not being saved and restored as intended across reboots. Some of these (like mouse settings) seem to not survive even a logout/login cycle.  
It's a bit more detailed here:  
https://forum.xfce.org/viewtopic.php?pid=60770#p60770  
When I logout, Ctrl Alt F2 TTY, manually rename ~/.config/xfce4/ and log back in, I see that the /.config/xfce4/ directory gets repopulated, but not with the directory xfconf, there's no xfconf directory there.  
Which leads me to believe that these values are being read from somewhere else, or possibly from a memory address, and not from disk, as they are intended to be at each and every login event (That directory holds the individual XML files responsible for all settings, except for Thunar settings)  
In the past, on Xubuntu 16.04 to be more precise (I think it already used systemd back then, didn't it? was it a different systemd? more stripped down maybe? not-so-ingrained into the system yet? can anyone offer input on the historical aspect of this?) On 16.04, none of this was an issue. I would have boot scripts for different live-sessions, I would simply replace (overwrite) the XML files inside of /.config/xfce4/xfconf/ and the new settings would be applied immediately (you can see terminal colors changing while the script is still running) Some settings required a simple logout/login to be applied. Simple and easy. That seems to be not possible anymore.  
Might as well be a Xfce bug, but there's high probability of systemd making things extra-difficult and putting roadblocks in the way (as we've seen in recent history countless times)

**Comment by poettering** [comment]
This does not at all look like it has anything to do with systemd. Please contact your downstream distro for help first, they will escalate things to us if there's anything, but what you describe seems entirely removed from what systemd does. Closing.

**Comment by DwarfFighterCleric** [comment]
Indeed.  
This is a not a bug report or anything. It's just a question so hopefully if anyone out there seems it, catch their eye, and they experienced similar issues, they will be able to share a bit of their experiences, and hopefully provide workarounds for it. Also is more convenient since most people have an account here but not on each individual forums out there, makes it easier to login and write down here.

**Comment by vcaputo** [comment]
This is not a support forum, please stop treating it as one.
