### ISSUE TITLE
User service failed to start with PrivateUsers=yes and ProtectControlGroups=yes

### ISSUE THREAD

**Issue by duament** [systemd/systemd#17860]
**systemd version the issue has been seen with**
 > 247.1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux arch-PC 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Service starts successfully.

**Unexpected behaviour you saw**
 > Service failed to start.
 > Logs:
 >```
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Successfully forked off '(sd-userns)' as PID 31611.
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: (sd-userns) succeeded.
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Bind-mounting / on /run/systemd/unit-root (MS_BIND|MS_REC "")...
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Applying namespace mount on /run/systemd/unit-root/dev
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Applying namespace mount on /run/systemd/unit-root/proc
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to umount /run/systemd/unit-root/proc, ignoring: Invalid argument
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to umount /run/systemd/unit-root/proc/sys/fs/binfmt_misc, ignoring: Invalid argument
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Mounting proc (proc) on /run/systemd/unit-root/proc (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: Failed to mount proc (type proc) on /run/systemd/unit-root/proc (MS_NOSUID|MS_NODEV|MS_NOEXEC ""): Operation not permitted
 > Dec 05 18:49:09 arch-PC ssh-agent[31610]: ssh-agent.service: Failed to set up mount namespacing: /run/systemd/unit-root/proc: Operation not permitted
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Changed failed -> running
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Job 31 ssh-agent.service/start finished, result=done
 > Dec 05 18:49:09 arch-PC systemd[31489]: Started SSH key agent.
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=10 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/ssh_2dagent_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31610]: Skipping PR_SET_MM, as we don't have privileges.
 > Dec 05 18:49:09 arch-PC systemd[31610]: ssh-agent.service: Failed at step NAMESPACE spawning /usr/bin/ssh-agent: Operation not permitted
 > Dec 05 18:49:09 arch-PC systemd[31489]: Received SIGCHLD from PID 31610 ((sh-agent)).
 > Dec 05 18:49:09 arch-PC systemd[31489]: Child 31610 ((sh-agent)) died (code=exited, status=226/NAMESPACE)
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Child 31610 belongs to ssh-agent.service.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Main process exited, code=exited, status=226/NAMESPACE
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Failed with result 'exit-code'.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Service will not restart (restart setting)
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Changed running -> failed
 > Dec 05 18:49:09 arch-PC systemd[31489]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Unit entered failed state.
 > Dec 05 18:49:09 arch-PC systemd[31489]: ssh-agent.service: Consumed 1ms CPU time.
 >```

**Steps to reproduce the problem**
 > 1. Create a user service file ~/.config/systemd/user/ssh-agent.service
 >```
 >[Unit]
 >Description=SSH key agent
 >
 >[Service]
 >Type=simple
 >Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
 >ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK
 >
 >PrivateUsers=yes
 >ProtectControlGroups=yes
 >
 >[Install]
 >WantedBy=default.target
 >```
 >2. Run `systemctl --user daemon-reload` and `systemctl --user start ssh-agent.service`

These 2 settings works fine in systemd 246.6.

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectControlGroups=

> This option is only available for system services and is not supported for services running in per-user instances of the service manager.

IIRC this has always been the case?

**Comment by duament** [comment]
As https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing said, it should work in conjunction with PrivateUsers=true. Actually it works fine until I upgrade systemd to 247.1.

**Comment by bluca** [comment]
> As https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing said, it should work in conjunction with PrivateUsers=true. Actually it works fine until I upgrade systemd to 247.1.

Ah yes you are indeed right, forgot that on Debian user ns are runtime disable by default.

**Comment by yuwata** [comment]
I've created #17872, but not tested it yet.

**Comment by duament** [comment]
Applied #17872 to 247.1. It fixed the issue for me.

**Comment by yuwata** [comment]
Thank you for testing the PR. Let's wait for a review.
