### ISSUE TITLE
Slow shutdown with systemd >= 247

### ISSUE THREAD

**Issue by flaphoschi** [systemd/systemd#17861]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Archlinux
 > Using GNOME and NetworkManager without `wait-online` and `dispatcher`. For WiFi encryption `iwd` is in use instead of `wpa_supplicant`. To increase random number generation either `rngd-tools` or `haveged`.

**Linux kernel version used** (`uname -a`)
 > Linux cupcake 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64 (Intel SandyBridg i7-2640M CPU)

**Expected behaviour you didn't see**
 > Computer should shutdown quickly i.e. less than five seconds.

**Unexpected behaviour you saw**
 > Not 100% reproduceable, about in one of five shutdowns or reboots *user@1000.service* seems to timeout during shutdown after 120 seconds.

**Steps to reproduce the problem**
 > 1.) boot computer
 > 2.) login into graphic environment // seems to make the issue much more likely
 > 3.) systemctl reboot
 > 4.) if (reboot_is_quick) { jump to 1; } // should be slow in one of five
 > 5.) be patient :slightly_smiling_face: 

If the shutdown is slow you will probably see only a blinking cursor. I've managed to see sometimes the message `systemd-shutdown[1]: Waiting for process: dbus-daemon, systemd, rngd, gpg-agent` when I press Ctrl+Alt+Del, Esc, Ctrl+c or shortly the power button. I've seen here various processes, systemd is obviously always included.

[slow_shutdown_cutout.txt](https://github.com/systemd/systemd/files/5646936/slow_shutdown_cutout.txt)
Please see line 514 - 515.

Thank you
Stay confident!

**Comment by andreaskem** [comment]
Sounds similar to [this ](https://gitlab.gnome.org/GNOME/gnome-session/-/issues/74)bug, supposedly fixed by [this ](https://gitlab.gnome.org/GNOME/gnome-session/-/commit/9de6e40f12e8878f524f8d429d85724c156a0517)commit.

**Comment by flaphoschi** [comment]
Thank you Andreas! That explains why I had no issues with pure TTY sessions. I've search everywhere for combinations of the words "systemd, hang, slow" but not "delay" :yum:
