### ISSUE TITLE
SYSTEMD_NSPAWN_TMPFS_TMP seems to be ignored by machinectl wrapper

### ISSUE THREAD

**Issue by Phyks** [systemd/systemd#17863]
Hi,

**systemd version the issue has been seen with**
 > systemd 246 (246.6-1-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS
> +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)
 > Linux Phyks-laptop 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Following https://github.com/systemd/systemd/pull/10294 and the description in https://github.com/poettering/systemd/blob/master/docs/ENVIRONMENT.md, I was expecting setting `SYSTEMD_NSPAWN_TMPFS_TMP` environment variable value to `0` would prevent the container from having a force-mounted `/tmp` as `tmpfs`. This does work with `systemd-nspawn` command, but not when spawning the machine through the `machinectl` wrapper.

**Unexpected behaviour you saw**
> `SYSTEMD_NSPAWN_TMPFS_TMP=0 machinectl start ubuntu-20.04` gives the same result as `machinectl start ubuntu-lineage-20.04` (`/tmp` mounted as `tmpfs`)

**Steps to reproduce the problem**
 
```
cd /var/lib/machines
debootstrap --include=systemd-container --components=main,universe focal ubuntu-20.04 http://archive.ubuntu.com/ubuntu/
SYSTEMD_NSPAWN_TMPFS_TMP=0 machinectl start ubuntu-20.04
```
and look at the `/tmp` mount.

Note that using `SYSTEMD_NSPAWN_TMPFS_TMP=0 systemd-nspawn -b -D ./ubuntu-20.04/` does prevent the `/tmp` to be force-mounted as `tmpfs`.

Thanks!

**Comment by bluca** [comment]
The document lists that env var under the systemd-nspawn tool. It is parsed and interpreted by the systemd-nspawn command line utility, and it's specific to it, like other env vars. machinectl doesn't support those, as it simply asks systemd to start a templated nspawn unit, it does not run nspawn directly.

But you should be able to add it by creating a drop-in /etc/systemd/system/systemd-nspawn@ubuntu-20.04.service.d/no-tmp.conf :

```
[Service]
Environment=SYSTEMD_NSPAWN_TMPFS_TMP=0
```

Would that work for your use case?

**Comment by Phyks** [comment]
Indeed, going through a `systemd-nspawn` unit would work for my use case. I still find it confusing for the user that `machinectl` would not pass along those environment variables.

Feel free to close if this issue is expected.

**Comment by bluca** [comment]
> Indeed, going through a `systemd-nspawn` unit would work for my use case. I still find it confusing for the user that `machinectl` would not pass along those environment variables.
> 
> Feel free to close if this issue is expected.

Well, it's expected in the sense that nobody (afaik) has required non-default nspawn options to be used via machinectl so far. It's a simple wrapper, and it's easy to add drop-ins as explained above or just use nspawn directly. But in principle the tool itself could be changed to accept --set-env for the ```start``` verb as well, and create drop-ins automatically. If that is something you'd have a real use case for, please feel free to rename this issue to an RFE. And even better, to send a PR :-)

**Comment by Phyks** [comment]
I actually am very new to nspawn and machinectl, and came across them from the Arch wiki: https://wiki.archlinux.org/index.php/Systemd-nspawn. machinectl options differ subtly from default values for the `systemd-nspawn` CLI, and it appears to me at first read as the best way to start containers through a service-like interface (start / stop / enable). I must confess I completely missed the `systemd-nspawn@.service` option.

This one and the drop-in provided above works perfectly fine for my use case, so I'm definitely fine with leaving as is. I'm closing this one and the documentation above should be enough for most users to find a solution through a search engine :)

Thanks!
