### ISSUE TITLE
read-only-filesystem warnings when booting

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#17862]
**systemd version the issue has been seen with**
 > master

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)
 > 5.9.11

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > No warnings

**Unexpected behaviour you saw**
 > Warnings when booting the container image with mkosi

**Steps to reproduce the problem**
 > mkosi --default .mkosi/mkosi.fedora boot

```
daan@archlinux ~/p/systemd (master)> sudo mkosi --default .mkosi/mkosi.fedora boot
‣ Processing default...
Spawning container image on /home/daan/projects/systemd/image.raw.
Press ^] three times within 1s to kill container.
systemd 247 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 33 (Thirty Three)!

Queued start job for default target Graphical Interface.
-.slice: Failed to migrate controller cgroups from , ignoring: Read-only file system
system.slice: Failed to delete controller cgroups /system.slice, ignoring: Read-only file system
[  OK  ] Created slice system-getty.slice.
[  OK  ] Created slice system-modprobe.slice.
user.slice: Failed to delete controller cgroups /user.slice, ignoring: Read-only file system
[  OK  ] Created slice User and Session Slice.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Reached target Slices.
[  OK  ] Reached target Swap.
[  OK  ] Listening on Process Core Dump Socket.
[  OK  ] Listening on initctl Compatibility Named Pipe.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket.
[  OK  ] Listening on User Database Manager Socket.
dev-hugepages.mount: Failed to delete controller cgroups /dev-hugepages.mount, ignoring: Read-only file system
         Mounting Huge Pages File System...
sys-fs-fuse-connections.mount: Failed to delete controller cgroups /sys-fs-fuse-connections.mount, ignoring: Read-only file system
         Mounting FUSE Control File System...
         Starting Journal Service...
         Starting Remount Root and Kernel File Systems...
system.slice: Failed to delete controller cgroups /system.slice, ignoring: Read-only file system

```

**Comment by DaanDeMeyer** [comment]
Bisected to 7b63961415920b30a4e9f6d4c87bda20a1d8ec67

**Comment by DaanDeMeyer** [comment]
This isn't limited to just systemd-nspawn. I see similar messages in my boot logs:

```
Dec 04 19:35:36 archlinux systemd[928]: -.slice: Failed to migrate controller cgroups from /user.slice/user-976.slice/user@976.service, ignoring: Permission denied
```

**Comment by Werkov** [comment]
Ad `systemd-nspawn` case: I see that controller hierarchies are mounted as read-only into the container. Therefore no resource control is possible in such environments. The cgroup [creation error is swallowed](//github.com/systemd/systemd/blob/v247/src/shared/cgroup-setup.c#L610) and there is eventually a [debug message when writing the value](https://github.com/systemd/systemd/blob/v247/src/core/cgroup.c#L81) and we get [ENOENT](https://github.com/systemd/systemd/blob/v247/src/core/cgroup.c#L38). So in this case the warning is benign (to the extent as other cgroup errors are treated) and its level could be relaxed.

Ad the host case, this is more interesting. What cgroup setup does your host use (hybrid/legacy)? Do you apply any additional cgroup settings to `user@976.service` (share `systemctl cat user@976.service` if you can)? Thanks.

**Comment by DaanDeMeyer** [comment]
user@976.service:

```
# /usr/lib/systemd/system/user@.service
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=User Manager for UID %i
Documentation=man:user@.service(5)
After=systemd-user-sessions.service user-runtime-dir@%i.service dbus.service
Requires=user-runtime-dir@%i.service
IgnoreOnIsolate=yes

[Service]
User=%i
PAMName=systemd-user
Type=notify
ExecStart=/usr/lib/systemd/systemd --user
Slice=user-%i.slice
KillMode=mixed
Delegate=pids memory
TasksMax=infinity
TimeoutStopSec=120s
KeyringMode=inherit
```

UID 976 on my system belongs to the sddm user. sddm is KDE's display manager.

**Comment by DaanDeMeyer** [comment]
Arch bug [report](https://bugs.archlinux.org/task/68832?string=cgroup&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=) that also reports the "Permission Denied" warnings:

**Comment by DaanDeMeyer** [comment]
Reopening because there's still the host issue

**Comment by bluca** [comment]
On the host, is this specific to that particular user unit? Or is it a random occurrence?

**Comment by DaanDeMeyer** [comment]
It's that particular one. I think it has something to do with systemd --user.

**Comment by bluca** [comment]
But does it happen with other user units within the same systemd --user instance? Just the first? Or is it specific to settings in that unit?

**Comment by DaanDeMeyer** [comment]
I've only seen a warning for that specific user unit instance. (I'm not sure how many others there, I guess there's another one for my own user (uid 1000)).
