### ISSUE TITLE
unwanted device link for nondev filesystems

### ISSUE THREAD

**Issue by karelzak** [systemd/systemd#1788]
Based on https://bugzilla.redhat.com/show_bug.cgi?id=1226528

If you mount (for example) ramfs and you specify some dummy source string prefixed by /dev, for example:

   #  mount -t ramfs /dev/something /foo/bar

then systemd immediately umount the filesystem with message "Unit is bound to inactive unit...".

The problem is probably src/core/mount.c:mount_add_device_links() where systemd tries to interpret the dummy mount-source string as a real device. If you change the mount command to:

   #  mount -t ramfs something /foo/bar

than all works as expected.

I see two possible solution:
1/ ignore the problem and describe somewhere in docs that for nondev filesystem is necessary to use dummy strings without "/dev" prefix.

2/ improve mount_add_device_links() to not create dependence on devices for nondev (pseudo) filesystems. For example libmount provides mnt_fstype_is_pseudofs()
https://github.com/karelzak/util-linux/blob/master/libmount/src/utils.c#L245 and we use it to ignore source paths in mount(8).

**Comment by poettering** [comment]
Hmm, isn't this kinda a "feature", not a bug? i.e. by specifying a device there, you made the mount be bound to that?

**Comment by karelzak** [comment]
Well, mount source is whatever, kernel is pretty promiscuous about it. The string is interpreted by FS driver (so the string could be ignored, something maybe generated on the fly or whatever). 

See the current situation:
1/ user mount something manually on command line, mount(8) success, kernel is happy
2/ we read from /proc/self/mountinfo info about the mountpoint
3/ we incorrectly interpret mountinfo as "device is missing" and call umount()

We should be more smart and follow kernel, if kernel is happy with the mountpoint then we should be also happy and don't call umount().

**Comment by grawity** [comment]
Well the auto-unmount feature was added to handle devices that disappear, like unplugged USB sticks. But it _is_ quite annoying the way it's implemented right now (via BindsTo) – it breaks regular device mounts in emergency mode as well…

Maybe it would be possible to add the BindsTo dep only when the device _exists_ at mount time? That way auto-unmount would still happen for devices which _disappear_.

**Comment by basic6** [comment]
Could this be related to https://bugzilla.redhat.com/show_bug.cgi?id=1214069 ?

That bug is about BTRFS, which couldn't be mounted occasionally (some time later it didn't work at all anymore). This made using this system impossible until it was revealed that removing the mount entry from /etc/fstab solves it. Error message also mentions `Unit data.mount is bound to inactive unit`.

_If_ this is the right bug - this kind of behavior is extremely annoying. Nothing should be unmounted automatically without an option to disable this. Or maybe there's an option that I have overlooked?

**Comment by keszybz** [comment]
I cannot reproduce this with systemd-229, #2017 probably did the trick.
