### ISSUE TITLE
Allow creating unreachable/blackhole RoutingPolicyRule

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#17890]
**Is your feature request related to a problem? Please describe.**
I have set up a WireGuard tunnel using a netdev and now I want to use policy-based routing to route all traffic from certain source network through the WireGuard tunnel. My uplink only has IPv4, so my host will also get an IPv6 address from this prefix and route its own IPv6 traffic via the tunnel. But normal v4 traffic should not go via the tunnel.

Normally I would add rules like this:

```
0:	from all lookup local
1000:	from all fwmark 0xca6c lookup main
2000:	from all fwmark 0xca6c unreachable
3000:	from 2a0f:4ac0:acab::/48 lookup 1234
32766:	from all lookup main
```

(and the same for IPv4 with the corresponding source prefix)

systemd-networkd has the `[RoutingPolicyRule]` section, but it can not create an `unreachable` rule or in fact any other than `lookup XYZ` (there's also `blackhole` for example).

**Describe the solution you'd like**

I would like to get a new field in the `[RoutingPolicyRule]` section that allows me to create rules with different types:

```
Type=blackhole
```

or

```
Type=unreachable
```

**Describe alternatives you've considered**

I really think systemd-networkd should be able to add this kind of rule, but in this case it would probably be possible to add another table which contains an unreachable default-route (which systemd-networkd already supports).

**Related**
https://github.com/systemd/systemd/issues/967
https://github.com/systemd/systemd/issues/797

**Comment by ssahani** [comment]
How you set this in ```ip rule```  ?

**Comment by petabyteboy** [comment]
For example:

```
[pbb@amalthea:~]$ sudo ip rule add fwmark 51820 unreachable prio 3000

[pbb@amalthea:~]$ ip rule
0:	from all lookup local
3000:	from all fwmark 0xca6c unreachable
32766:	from all lookup main
32767:	from all lookup default

[pbb@amalthea:~]$
```
