### ISSUE TITLE
udev can't start @.service

### ISSUE THREAD

**Issue by alex19EP** [systemd/systemd#17893]
**systemd version the issue has been seen with**
 > … 247.1

**Used distribution**
 > … arch

**Linux kernel version used** (`uname -a`)
 > …Linux alex-pc 5.9.12-arch1-1 GNU/Linux

**CPU architecture issue was seen on**
 > …amd64

**Expected behaviour you didn't see**
 > …when [90-brltty-device.rules.txt](https://github.com/systemd/systemd/files/5656206/90-brltty-device.rules.txt) triggers [brltty@.service.txt](https://github.com/systemd/systemd/files/5656211/brltty%40.service.txt) a [systemd-wrapper.txt](https://github.com/systemd/systemd/files/5656219/systemd-wrapper.txt) should be started. and will run until device hasn't been unplugged. 
systemd v 246 can do that without any problem.

**Unexpected behaviour you saw**
 > …service starts and after 1.5 secondes is stopped.

**Comment by yuwata** [comment]
- Please generate the debugging logs of systemd-udevd by creating the following drop-in file:
```
# /etc/systemd/system/systemd-udevd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
and then provide the relevant log of udevd.
- Please provide the journal log of the service.
- Please provide the result of `udevadm info` for the relevant device.

**Comment by yuwata** [comment]
I guess `bind/unbind` event is triggered after `add` event.

**Comment by alex19EP** [comment]
> I guess `bind/unbind` event is triggered after `add` event.

yes. should we somehow react on it?

> Please generate the debugging logs of systemd-udevd by creating the following drop-in file

when udev debug is enabled something strange happens.: first started service wouldn't stop, even on device disconnect. on second connection service starts and stops as before.

In fact, it seems that we have solved the problem. we have created a [brltty-device@.service.txt](https://github.com/systemd/systemd/files/5660587/brltty-device%40.service.txt) that depends on the device and requires our service. now hour udev rule wants that service. and all working well.

it is still not clear to me why it worked before, but now such changes are needed.
it would also be nice to make sure we are actually doing the right thing. from an upstream point of view.

**Comment by alex19EP** [comment]
>>I guess bind/unbind event is triggered after add event.

>yes. should we somehow react on it?

it turned out that we really did not handle udev events correctly.
when we changed `ACTION=="add", GOTO="brltty_systemd_add"` to:
`ACTION!="remove", GOTO="brltty_systemd_add"` all got back to normal.
