### ISSUE TITLE
Computer Hung by Attempt to Turn-on Non-Existence KBD Light

### ISSUE THREAD

**Issue by Oeconomist** [systemd/systemd#1792]
This is [Bug 1253523](https://bugzilla.redhat.com/show_bug.cgi?id=1253523) at bugzilla.redhat.com. 

On a Dell Inspiron Mini 1012, and presumably on other machines, systemd attempts to turn-on a non-existence keyboard backlight.  This completely hangs the computer during boot-up. 

 [Iván Jiménez pinned-down what was happening](https://bugzilla.redhat.com/show_bug.cgi?id=1253523#c12), and provided a work-around using 

```
systemctl mask systemd-backlight@leds\:dell\:\:kbd_backlight.service
```

He notes that the problem is associated with the presence of a file 

```
/var/lib/systemd/backlight/platform-dell-laptop:leds:dell::kbd_backlight
```

which he conjectures is created by 

```
systemd-backlight@.service
```

**Comment by poettering** [comment]
Well, userspace should not be able to make the system freeze like this. If it can do that, that's a kernel bug, and in this case a bug in the dell laptop driver, apparently. Could you please file a bug against that driver in the kernel bugzilla, and explain the situation there? Thanks!

**Comment by Oeconomist** [comment]
A bug report has been filed as [Kernel Bug 107651](https://bugzilla.kernel.org/show_bug.cgi?id=107651).
