### ISSUE TITLE
Mouse and keyboard don't initialize on Wayland session when "ckb-next" package is installed

### ISSUE THREAD

**Issue by dron1885** [systemd/systemd#17922]
**systemd version the issue has been seen with**
 > 247 and 247.1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux Arch 5.9.13-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 08 Dec 2020 12:10:52 +0000 x86_64 GNU/Linux

But bug persist Linux-lts 5.4.82-1

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > After logging into the Wayland session mouse and keyboard are responsive and working.

**Unexpected behaviour you saw**
 > Mouse and keyboard initialized fine. Both works under X11 display manager and session. As soon as I login into the Wayland session (tested with Sway and Weston) both the mouth and keyboard are unresponsive and don't show in inputs. Wi-Fi dongle kb+m combo still works.

**Steps to reproduce the problem**
 > Update systemd, systemd-libs, systemd-sysvcompat from version 246. Login into the Wayland session.
Kb and Mouse in question are Corsair Gaming K70 LUX RGB and Corsair Gaming HARPOON RGB Mouse.

**Comment by mbiebl** [comment]
Are you by any chance using ckb-next?
This sounds a lot like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976366#58 / https://github.com/ckb-next/ckb-next/issues/671

**Comment by dron1885** [comment]
@mbiebl yes, I'm using it, and the bug is exactly what I have.
But I didn't think that the ckb-next broke input as it had no updates since late October.
Is there any "digging" I can do? Because bug seems related to systemd.

**Comment by poettering** [comment]
This is garbage:

https://github.com/ckb-next/ckb-next/blob/master/linux/udev/99-ckb-next-daemon.rules

if you remove (move it away) that udev rules files, does it work then?

**Comment by dron1885** [comment]
@poettering nope. As soon as I start ckb-next-daemon, I losing mouse and kb.
It seems the bug is fixed in ckb-next master, but it's a coincidental fix.

**Comment by poettering** [comment]
What makes you think systemd is doing anything wrong?

If you drop that "ckb-next" package as a whole, do things work then?

**Comment by duck-rh** [comment]
ckb-next's udev config is broken but it's not needed to use the device and fixing it or removing it does not help.

I can confirm downgrading systemd to 246 (and this only) fixes the issue.

As for ckb-next in master the only related changes seem to be filtering keys according to the device type. That might be better like this but that does not explain why this would be needed to work with systemd 247.

That does not mean systemd is doing anything wrong but I think that's worth investigating.

**Comment by poettering** [comment]
by all means, please investigate. I doubt anyone from upstream would bother with that though, given it appears hw specific and the software involved is kinda fishy if i look at it superficially. I am tempted to just close this, unless anyone with the hw and the sw wants to track this down further and report back here?

**Comment by boucman** [comment]
maybe bissect between 246 and 247, so we have an idea what change caused this ?

**Comment by aragon999** [comment]
Not sure if this is related but we found a bug which was kind of similar, and happens if too many keys for device were enabled.
This only happens in systemd 247 and is not present in systemd 246.

For more information see this issue/comment: https://github.com/PixlOne/logiops/issues/166#issuecomment-744595620

**Comment by mbiebl** [comment]
Can anyone affected by this run a `git bisect`?

**Comment by aragon999** [comment]
If this is related to the linked issue I have the following test code (with systemd 246 both `test_input` calls work, in systemd 247 only the latter):

```main.cpp
#include <iostream>
#include <string.h>

extern "C"
{
#include <libevdev/libevdev.h>
#include <libevdev/libevdev-uinput.h>
}

void test_input(int register_keys_upto)
{
    int err;
    struct libevdev *dev;
    struct libevdev_uinput *uidev;

    dev = libevdev_new();
    libevdev_set_name(dev, "virtual keyboard");

    std::cout << "Created new keyboard with " << register_keys_upto << " enabled events and name: " << libevdev_get_name(dev) << std::endl;

    libevdev_enable_event_type(dev, EV_KEY);
    for (uint i = 0; i < register_keys_upto; i++) {
        libevdev_enable_event_code(dev, EV_KEY, i, NULL);
    }

    err = libevdev_uinput_create_from_device(dev,
            LIBEVDEV_UINPUT_OPEN_MANAGED,
            &uidev);

    if (err != 0) {
        std::cerr << "error rc: << " -err << strerror(-err) << std::endl;
    }

    // Wait to display the char
    getchar();

    std::cout << "Sending key a" << std::endl;

    libevdev_uinput_write_event(uidev, EV_KEY, KEY_A, 1);
    libevdev_uinput_write_event(uidev, EV_SYN, SYN_REPORT, 0);
    libevdev_uinput_write_event(uidev, EV_KEY, KEY_A, 0);
    libevdev_uinput_write_event(uidev, EV_SYN, SYN_REPORT, 0);

    // Wait to display the char
    getchar();

    std::cout << "Finished sending keys: " << libevdev_get_name(dev) << std::endl;

    libevdev_uinput_destroy(uidev);
}

int main() {
    std::cout << "Start test" << std::endl;

    test_input(KEY_CNT);
    test_input(128);
    std::cout << "Finished test" << std::endl;

    return 0;
}
```

`g++ -levdev test-input.cpp  -I/usr/include/libevdev-1.0 -o test-input` (you will need `libevdev`).

I can try to setup the systemd compilation for my machine later (never compiled systemd from source) and after that try to run a `git bisect`.

**Comment by poettering** [comment]
Let's close this as this is apparently fixed in ckb-next from master. While systemd did change udev logic a bit in an incompatible way (which we widely announced, there was even an LWN article about this), we cannot undo this. Let's hence close this.

(Also see #18119)
