### ISSUE TITLE
systemd-networkd assertion failed and lost internet connection after resume from suspend

### ISSUE THREAD

**Issue by ynakao** [systemd/systemd#17920]
At first I thought this issue was related to #17803, but even after Arch maintainer [backported](https://github.com/archlinux/svntogit-packages/commit/bb0ca6bd29043205c5bdfbe7b449be04d608e373#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) the patches to the systemd package, the issue still remains. So I guess this is another issue.

**systemd version the issue has been seen with**
 > 247.1-3 Arch Linux build

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.13-arch1-1
 
**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Reconnect to my acccess point after resume from suspend.

**Unexpected behaviour you saw**
 > systemd-networkd doesn't reconnect to my AP automatically after resume from suspend.

**Steps to reproduce the problem**

I'm using systemd-networkd and iwd for wireless settings.

1. At first boot, internet connection works fine.

2. Execute `$ systemctl suspend`, and open the laptop lid to resume from suspend.

3. After repeating resume from suspend two or three times (mostly two times in my case), systemd-networkd raises assertion error, but still reconnects to the network correctly at this point.

```
Assertion 'IN_SET(link->state, LINK_STATE_CONFIGURING, LINK_STATE_FAILED, LINK_STATE_LINGER)' failed at src/network/networkd-address.c:934, function address_handler(). Aborting.
```

4. After another repeating resume from suspend two or three times (mostly one or two times in my case), systemd-networkd doesn't establish the connection.

- Manually restarting `systemd-networkd.servise` or `iwd.service` makes internet connection work again.

- systemd-networkd works properly by downgrading systemd to the previous version.

```
$ sudo pacman -U /var/cache/pacman/pkg/systemd-246.6-1-x86_64.pkg.tar.zst
```

---

- journalctl log 

`$ journalctl -u systemd-networkd`

Blank lines represent suspend and resume process.

```
-- Boot 72014ee554c6448684a463eb9ac1a5f3 --
Dec 10 11:54:51 hostname systemd[1]: Starting Network Service...
Dec 10 11:54:51 hostname systemd-networkd[899]: Enumeration completed
Dec 10 11:54:51 hostname systemd-networkd[899]: enp0s25: Interface name change detected, enp0s25 has been renamed to eth0.
Dec 10 11:54:51 hostname systemd[1]: Started Network Service.
Dec 10 11:54:51 hostname systemd-networkd[899]: eth0: Interface name change detected, eth0 has been renamed to enp0s25.
Dec 10 11:54:51 hostname systemd-networkd[899]: wlan0: Could not find device, waiting for device initialization: No such device
Dec 10 11:54:51 hostname systemd-networkd[899]: wlan0: Link DOWN
Dec 10 11:54:51 hostname systemd-networkd[899]: wlan0: Link UP
Dec 10 11:54:51 hostname systemd-networkd[899]: enp0s25: Link UP
Dec 10 11:54:54 hostname systemd-networkd[899]: wlan0: Gained carrier
Dec 10 11:54:54 hostname systemd-networkd[899]: wlan0: Connected WiFi access point: $My_SSID ($SSID_MAC_Address)

Dec 10 11:56:48 hostname systemd-networkd[899]: wlan0: Lost carrier
Dec 10 11:56:48 hostname systemd-networkd[899]: wlan0: Gained carrier
Dec 10 11:56:49 hostname systemd-networkd[899]: wlan0: Reset carrier
Dec 10 11:56:49 hostname systemd-networkd[899]: lo: Reset carrier

Dec 10 11:59:39 hostname systemd-networkd[899]: wlan0: Lost carrier
Dec 10 11:59:39 hostname systemd-networkd[899]: Assertion 'IN_SET(link->state, LINK_STATE_CONFIGURING, LINK_STATE_FAILED, LINK_STATE_LINGER)' failed at src/network/networkd-address.c:934, function address_handler(). Aborting.
Dec 10 11:59:40 hostname systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=6/ABRT
Dec 10 11:59:40 hostname systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 10 11:59:40 hostname systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 1.
Dec 10 11:59:40 hostname systemd[1]: Stopped Network Service.
Dec 10 11:59:40 hostname systemd[1]: Starting Network Service...
Dec 10 11:59:40 hostname systemd-networkd[2118]: Enumeration completed
Dec 10 11:59:40 hostname systemd-networkd[2118]: wlan0: Lost carrier
Dec 10 11:59:40 hostname systemd[1]: Started Network Service.
Dec 10 11:59:40 hostname systemd-networkd[2118]: wlan0: Gained carrier
Dec 10 11:59:40 hostname systemd-networkd[2118]: wlan0: Connected WiFi access point: $My_SSID ($SSID_MAC_Address)

Dec 10 12:01:11 hostname systemd-networkd[2118]: wlan0: Lost carrier
Dec 10 12:01:11 hostname systemd-networkd[2118]: wlan0: Address ready callback is not set.
Dec 10 12:01:11 hostname systemd-networkd[2118]: wlan0: Failed
Dec 10 12:01:11 hostname systemd-networkd[2118]: wlan0: Gained carrier
Dec 10 12:01:12 hostname systemd-networkd[2118]: lo: Reset carrier
Dec 10 12:01:12 hostname systemd-networkd[2118]: wlan0: Reset carrier

// after this, systemd-networkd lost the connection.
```

- configuration file

/etc/systemd/network/25-wireless.network

```
[Match]
Name=wlan0

[Network]
Address=192.168.179.4/24
Gateway=192.168.179.1
DNS=192.168.179.1
```

**Comment by yuwata** [comment]
@ynakao Thank you for the report. I've created #17921. It should fixes the assertion.

Though, currently I have no idea about the following error...
> `wlan0: Address ready callback is not set.`

Could you test #17921? Thank you.

**Comment by ynakao** [comment]
Hmm... the issue still remains, if I compiled systemd correctly with the patch.
The exact behavior described above happens even after installing the patched one.

This is systemd-networkd.service log enabled with `SYSTEMD_LOG_LEVEL=debug`.
https://gist.github.com/ynakao/504286daa0844a57c39fc5d3f8d5e385

**Comment by ynakao** [comment]
Oh, sorry I placed the patch file in the build directory, but forgot to apply it.
Wait for minutes to recompile.

**Comment by ynakao** [comment]
I'm really sorry for bothering you.
After installing the patched systemd, assertion error disappeared, but the internet connection issue still remains saying `wlan0: Address ready callback is not set.`.

New systemd-networkd.service log is here.
https://gist.github.com/ynakao/917d3ce4fcfd80dda30f5acb4634dc05

**Comment by yuwata** [comment]
@ynakao Thanks. The PR is updated. Could you retest it?

**Comment by ynakao** [comment]
systemd with the latest patch works properly!
I appreciate your work.
