### ISSUE TITLE
systemd-coredump 246 hang shutdown (randomly)

### ISSUE THREAD

**Issue by 82ghost82** [systemd/systemd#17937]
**systemd version the issue has been seen with**
systemd 246

**Used distribution**
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"

**System**
System:

Kernel: 5.4.80-2-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0

Console: tty 1 Distro: Manjaro Linux

Machine:

Type: Server Mobo: ASUSTeK model: Z9PE-D8 WS v: 1.0x serial:

UEFI: American Megatrends v: 5802 date: 06/10/2015

CPU:

Info: 2x 8-Core model: 06/2d bits: 64 type: MCP SMP arch: Sandy Bridge

rev: 5 L2 cache: 40.0 MiB

flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 99763

Speed: 1204 MHz min/max: 1200/3800 MHz Core speeds (MHz): 1: 1207 2: 1205

3: 1204 4: 1204 5: 1204 6: 1204 7: 1204 8: 1204 9: 1204 10: 1204 11: 1204

12: 1260 13: 1214 14: 1204 15: 1204 16: 1205

Graphics:

Device-1: NVIDIA GF108GL [Quadro 600] driver: nouveau v: kernel

bus ID: 03:00.0

Device-2: NVIDIA GK110B [GeForce GTX TITAN Black] driver: vfio-pci v: 0.2

bus ID: 83:00.0

Display: server: No display server data found. Headless machine?

tty: 80x24

Message: Unable to show advanced data. Required tool glxinfo missing.

Audio:

Device-1: Intel C600/X79 series High Definition Audio vendor: ASUSTeK

driver: vfio-pci v: 0.2 bus ID: 00:1b.0

Device-2: NVIDIA GF108 High Definition Audio driver: snd_hda_intel

v: kernel bus ID: 03:00.1

Device-3: NVIDIA GK110 High Definition Audio driver: vfio-pci v: 0.2

bus ID: 83:00.1

Sound Server: ALSA v: k5.4.80-2-MANJARO

Network:

Device-1: Intel 82574L Gigabit Network vendor: ASUSTeK driver: e1000e

v: 3.2.6-k port: 8000 bus ID: 06:00.0

IF: enp6s0 state: down mac:

Device-2: Intel 82574L Gigabit Network vendor: ASUSTeK driver: e1000e

v: 3.2.6-k port: 7000 bus ID: 07:00.0

IF: enp7s0 state: up speed: 100 Mbps duplex: full mac:

IF-ID-1: br0 state: up speed: N/A duplex: N/A mac:

IF-ID-2: br1 state: up speed: N/A duplex: N/A mac:

IF-ID-3: vnet0 state: unknown speed: 10 Mbps duplex: full mac:

IF-ID-4: vnet1 state: unknown speed: 10 Mbps duplex: full mac:

Drives:

Local Storage: total: 8.19 TiB used: 3.36 TiB (41.0%)

ID-1: /dev/sda vendor: SanDisk model: SDSSDP256G size: 238.47 GiB

ID-2: /dev/sdb vendor: Crucial model: CT500MX500SSD1 size: 465.76 GiB

ID-3: /dev/sdc vendor: Western Digital model: WD20EZRX-00DC0B0

size: 1.82 TiB

ID-4: /dev/sdd vendor: Western Digital model: WD60EZRX-00MVLB1

size: 5.46 TiB

ID-5: /dev/sde vendor: Hitachi model: HTS542525K9SA00 size: 232.89 GiB

Partition:

ID-1: / size: 227.74 GiB used: 3.50 GiB (1.5%) fs: ext4 dev: /dev/sde2

Swap:

Alert: No Swap data was found.

Sensors:

System Temperatures: cpu: 29.0 C mobo: N/A gpu: nouveau temp: 48.0 C

Fan Speeds (RPM): N/A gpu: nouveau fan: 2820

Info:

Processes: 292 Uptime: 7m Memory: 62.92 GiB used: 32.76 GiB (52.1%)

Init: systemd Compilers: gcc: N/A Packages: 422 Shell: Bash v: 5.0.18

inxi: 3.1.08

**Linux kernel version used** (`uname -a`)
Linux tower 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux

**CPU architecture issue was seen on**
2x Intel xeon e5-2687w (v1) - Sandy Bridge

**Expected behaviour you didn't see**
workstation always shutdown when command `shutdown -h now` is issued

**Unexpected behaviour you saw**
workstation hangs randomly on shutdown (>50%) when command `shutdown -h now` is issued.
It is the same as 
https://github.com/systemd/systemd/issues/2691
Also, the same fix works in my case (at least in the last 2 days the shutdown was ok with the fix).
Fix:
https://github.com/systemd/systemd/issues/2691#issuecomment-203534354

**Steps to reproduce the problem**
I don't know how to reproduce 100% the issue.
I use manjaro architect (only cli) with qemu/kvm to host a mac os vm automatically booted.
Sometimes (>50%) the systems hangs on "reboot: power down"; waiting (> 20 minutes) doesn't help, the workstation doesn't shutdown without the fix.
A log is attached: log is created on next boot after a forced shutdown (long press of mechanical button).
`journalctl -b -1 -n250`

As you can see I have these lines, which pointed me in the link I posted above (very old! 2016)
`dic 09 17:58:20 tower systemd[1]: Requested transaction contradicts existing jobs: Transaction for systemd-coredump@0-1660-0.service/start is destructive (umount.target has 'start' job queued, but 'stop' is included in transaction).
dic 09 17:58:20 tower systemd[1]: systemd-coredump.socket: Failed to queue service startup job (Maybe the service file is missing or not a non-template unit?): Transaction for systemd-coredump@0-1660-0.service/start is destructive (umount.target has 'start' job queued, >
dic 09 17:58:20 tower systemd[1]: systemd-coredump.socket: Failed with result 'resources'.`

[log.txt](https://github.com/systemd/systemd/files/5677872/log.txt)

**Comment by 82ghost82** [comment]
Nope, the fix doesn't fix...
After 2 days another hang..
There's no more the systemd-coredump lines, because it's disabled now, but something is still broken..
So now, not sure at all, maybe related to systemd-networkd?
New log attached.
[new-log.txt](https://github.com/systemd/systemd/files/5679255/new-log.txt)

**Comment by 82ghost82** [comment]
I'm closing this, since it seems not related to systemd: I tried the Artix systemd free distribution and I have exactly the same issue of random hangs on shutdown/poweroff.
If, however, someone with more experience could contact me on how to debug this issue, since it seems kernel related, it would be good.

Thanks and sorry

**Comment by sverdlin** [comment]
Hello @82ghost82!
Would you like to test #19350, maybe it will fix the issue you've reported?
