### ISSUE TITLE
udev TAGS= prop must be prefixed and suffixed by ":"

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#17930]
#17871 dropped the ":" prefix and suffix on the TAGS= property, which will cause breakage and should be reverted.

**Comment by poettering** [comment]
See https://github.com/systemd/systemd/pull/17871#issuecomment-742533435 for a longer discussion of the issue

**Comment by yuwata** [comment]
Thank you for pointing out this. Fix is waiting in #17933.
