### ISSUE TITLE
machinectl 'failed to set up default quota hierarchy' on first run

### ISSUE THREAD

**Issue by oxwivi** [systemd/systemd#17946]
**systemd version the issue has been seen with**
 > systemd 246 (v246.6-3.fc33)

**Used distribution**
 > Fedora 33 (Workstation Edition)

**Linux kernel version used** (`uname -a`)
 > 5.8.15-301.fc33.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Successfully import rootfs tar

**Unexpected behaviour you saw**
 > `Failed to set up default quota hierarchy for /var/lib/machines/.#tarb8eee0a181a5ed97: Permission denied`

**Steps to reproduce the problem**
 > 1. Install Fedora 33
 > 2. `machinectl import` root tarball of your choice

This occurred on a fresh install of a Fedora 33 Workstation install. After installation, I've tried both `import-tar` and `import-rootfs` but it complains about, presumably, Btrfs quota. Of course that's not the case since the first command I've ran since user setup is the import commands.

```
$ sudo machinectl pull-tar https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.tar.gz --verify=no
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.tar.gz', saving as 'openwrt-19.07.5-x86-64-generic-rootfs'.
Downloading 169B for https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.nspawn.
HTTP request to https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.nspawn failed with code 404.
Settings file could not be retrieved, proceeding without.
Downloading 3.6M for https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.tar.gz.
Failed to set up default quota hierarchy for /var/lib/machines/.#tarb8eee0a181a5ed97: Permission denied
tar: /var/lib/machines/.#tarb8eee0a181a5ed97: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
Failed to write file: Broken pipe
Failed to retrieve image file. (Wrong URL?)
Got 1% of https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-19.07.5-x86-64-generic-rootfs.tar.gz.
Exiting.
```

**Comment by poettering** [comment]
is this with selinux on?

if you turn off selinux, does it work then?

anything in the logs?

is this on /var being btrfs?

do you have btrfs quota enabled on /var?

**Comment by poettering** [comment]
Closing due to lack of response.

**Comment by ctsk** [comment]
Hey :)

I encountered this issue today. I'm running Fedora 38 - after disabling selinux via `setenforce Permissive` the error did no longer occur.
