### ISSUE TITLE
Feature: noexec (or mount flag) controls 

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#17942]
**Is your feature request related to a problem? Please describe.**
With #17940 the default mount flags for `/dev` would change to allow executable files. To allow hardening the system with strict W^X file system policies for services, it should be possible to change the default on a case by case basis. Today, typically services don't need exec access to `/dev` at all, but this may change if Intel SGX gains acceptance.

**Describe the solution you'd like**
The mount flags for a path should be changeable for individual services with new directives like:
- `NoExecPaths=/dev` (matches `ReadOnlyPaths=`, `InaccessiblePaths=`)
- `MountOptions=/dev:rw,noexec,dev,nosuid` (generic mount option directive)
- `ProtectDev=yes` (higher level control but specific to `/dev`, could include other features in the future)
- `RestrictSGX=yes` (very specific to SGX)
- `RestrictEnclaves=yes` (less specific to SGX)

**Comment by topimiettinen** [comment]
One more idea:
- `FileSystemDenyWriteExecute=yes` (like `MemoryDenyWriteExecute=yes`)

The idea would be that for W&X paths, either write access or execute access would be removed, according to heuristics. It's not so clear what those could be though.

With `NoExecPaths=` and the reverse directive `ExecPaths=`, allow-listing of all executable content could be implemented:
```
[Service]
NoExecPaths=/
ExecPaths=/usr/sbin/daemon /lib64/ld-linux-x86-64.so.2 /usr/lib 
```
This would not be possible with `MountOptions=` without considering the possible mount options for each file system.

@poettering @keszybz any preference? Most of the possible options are not mutually exclusive, so more than one could be implemented.

**Comment by poettering** [comment]
Every new option we add comes at a price: the burden to maintain it. In particular stuff that is opt-in comes at a very high price. 

I am not sure MS_NOEXEC on /dev/ is really worth the effort and burden. I mean, I am all for locking things down, if we can do it without compromising too hard. But I am not sure that it's really worth locking this down, it doesn't really substantially reduce attack surface afaics, but it's very nichey.

**Comment by topimiettinen** [comment]
I agree that only MS_NOEXEC for only `/dev` would indeed be too nichey (something like `NoExecDev=yes`) and that's why I'm proposing more generic or higher level controls.

I think `NoExecPaths=` (complemented with `ExecPaths=`) would be the most generally useful of the list of ideas above. Controlling execute permissions across all file systems with allow-listing would be very powerful. For example, it could mean that a compromised service would not be able to execute a shell, if that was not explicitly allowed. The execute permissions for writable locations may also be easily controlled with allow-listing mode.

We've also discussed about something like `MountOptions=` before, but I think for this case it would not be the best tool.
