### ISSUE TITLE
[systemd-networkd][bug] With "AddPrefixRoute=false" Default Routes via "Gateway=" Or "[Route]" Are Not Created

### ISSUE THREAD

**Issue by maddes-b** [systemd/systemd#17949]
**systemd version the issue has been seen with**
 > systemd 246 (246.6-1ubuntu1)
 > +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu Server 20.10

**Linux kernel version used** (`uname -a`)
 > Linux test 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > amd64, Proxmox/qemu VM

**Expected behaviour you didn't see**
 > Default routes specified in .network files are created by systemd
```
# ip -4 route | sort
10.0.0.0/8 dev ens18 proto static src 10.1.2.3 metric 100
default via 10.99.99.99 dev ens18 proto static src 10.1.2.3 metric 100
```

**Unexpected behaviour you saw**
 > No default routes were generated
```
# ip -4 route | sort
10.0.0.0/8 dev ens18 proto static src 10.1.2.3 metric 100
```

**Steps to reproduce the problem**
 > Reason for bug is `AddPrefixRoute=false`.
 > Doesn't matter if only `Gateway=` is used under `[Network]` or `[Route]`, or if `Destination=0.0.0.0/0` is defined.
 > Also it doesn't matter if a route table is specified or not, or anything else.

Example:
```
[Match]
Name=ens18

[Link]
RequiredForOnline=yes

[Network]
ConfigureWithoutCarrier=false
IgnoreCarrierLoss=false
DHCP=no
IPForward=yes
LinkLocalAddressing=ipv6
IPv6AcceptRA=yes
IPv6PrivacyExtensions=yes

[Address]
Address=10.1.2.3/8
AddPrefixRoute=false

[Route]
Destination=10.0.0.0/8
PreferredSource=10.1.2.3
Metric=100
## Fix for issue: define correct scope
Scope=link

[Route]
Gateway=10.99.99.99
PreferredSource=10.1.2.3
Metric=100

[Address]
Address=fd7a:1::1:2:3/64
```
The second `[Route]` with the default gateway does not get setup, while the first is setup just fine. Their order does not change this behaviour.
```
# ip -4 route | sort
10.0.0.0/8 dev ens18 proto static src 10.1.2.3 metric 100
```

**Comment by arvidjaar** [comment]
With `AddPrefixRoute=false` kernel does not know how to reach your gateway `10.99.99.99`, so result is expected. Setting `GatewayOnLink=true` may help.

**Comment by maddes-b** [comment]
> 
> 
> With `AddPrefixRoute=false` kernel does not know how to reach your gateway `10.99.99.99`, so result is expected. Setting `GatewayOnLink=true` may help.

Sorry, the example is just an extract, so maybe misleading. Of course in my definition there's another route for 10.0.0.0/8. I will add this to my example.

The issue is really that the route does not get setup by systemd, which is independent of that it will work.

Still I will try if "GatewayOnLink=" may help.

**Comment by arvidjaar** [comment]
> Of course in my definition there's another route for 10.0.0.0/8. I will add this to my example.
> Or am I missing here something?

You need to tell kernel it is on-link route (`Scope=link`), otherwise it _still_ does not know how to reach your gateway ...

```
default via 10.99.99.99 dev eth0 proto static src 10.1.2.3 linkdown 
10.0.0.0/8 dev eth0 proto static scope link src 10.1.2.3 linkdown 

[Route]
Destination=10.0.0.0/8
PreferredSource=10.1.2.3
Scope=link
```

**Comment by yuwata** [comment]
It sounds not a networkd issue, but a user's misconfiguration (or a kernel limitation).
