### ISSUE TITLE
logind: documentation should be clear that linux >= 4.17 is required

### ISSUE THREAD

**Issue by larathbone** [systemd/systemd#17956]
In order for hibernation to work with a swapfile in particlar, logind requires /sys/power/resume_offset to exist. This file only appeared as of linux kernel 4.17. As i was running 4.14 on an older machine, I did not realize this was an issue until I got an opaque "no such file or directory" error message. Poking around the source code, I saw that logind was looking for /sys/power/resume_offset, which only came into being as of kernel 4.17.

This isn't a big deal I guess, but it might make sense to bump the kernel version requirements, if logind is going to be looking for features that were only added post-4.4, and silently failing when not found.

**Comment by yuwata** [comment]
Could you show the relevant debugging logs of logind?

**Comment by larathbone** [comment]
I'm actually running elogind on Slackware Current - 243.7, forked from systemd 243.

I didn't run it with debugging enabled, sorry. I've now upgraded my kernel. If I get a sec I'll try on the old kernel with debugging enabled.

Here are the errors in syslog:

Dec 13 15:30:30 darkstar kernel: [  149.005441] elogind-daemon[1397]: Failed to prepare for hibernation: No such file or directory
Dec 13 15:30:30 darkstar kernel: [  149.005445] elogind-daemon[1397]: Error during inhibitor-delayed operation (already returned success to client): No such file or directory

looks like `configure_hibernation` function in src/sleep/sleep.c looks for /sys/power/resume_offset which only exists >= linux 4.17.

**Comment by yuwata** [comment]
Unfortunately, v243 is too old here, and your issue seems to be already fixed by 7bdf56a28ae5ba3c2ae404932062dbf240ddc511. Closing.

If you still observe similar issue in systemd-logind of the recent release, then feel free to request to reopen this.

**Comment by larathbone** [comment]
> If you still observe similar issue in systemd-logind of the recent release, then feel free to request to reopen this.

will do - thanks!
