### ISSUE TITLE
nspawn --private-users-chown causes /run/systemd/netif/ to become unwritable by the host networkd

### ISSUE THREAD

**Issue by juliacartwright** [systemd/systemd#17961]
**systemd version the issue has been seen with**
 > systemd 247 (247.1-3-arch)
> +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux kryptos 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
I've been experimenting with some newly created containers managed with `systemd-nspawnd@.service`, and noticed that when these new containers were booted for the first time, I was seeing these errors very frequently (~every second) in the journal:

 > Dec 13 22:38:49 kryptos systemd-networkd[243]: vb-eso: Failed to save link data to /run/systemd/netif/links/7: Permission denied
> Dec 13 22:38:49 kryptos systemd-networkd[243]: enp0s4: Failed to save LLDP data to /run/systemd/netif/lldp/2: Permission denied
> Dec 13 22:38:49 kryptos systemd-networkd[243]: enp0s4: Failed to save link data to /run/systemd/netif/links/2: Permission denied
> Dec 13 22:38:49 kryptos systemd-networkd[243]: vz-cont: Failed to save link data to /run/systemd/netif/links/8: Permission denied

Perplexed, I rebooted the host.  After a fresh reboot of the host, booting up the guest caused no issues.  At this point I was suspecting `--private-users-chown`, which is the assumed default when managed via `systemd-nspawn@.service` or `machinectl`.

**Steps to reproduce the problem**
 Inspect `/run/systemd/netif` prior to the first nspawn boot of a guest.

> [root@kryptos machines]# ls -al /run/systemd/netif/**
>-rw-r--r-- 1 systemd-network systemd-network 145 Dec 13 23:19 /run/systemd/netif/state
>
>/run/systemd/netif/leases:
>total 4
>drwxr-xr-x 2 systemd-network systemd-network  60 Dec 13 23:19 .
>drwxr-xr-x 5 systemd-network systemd-network 120 Dec 13 23:19 ..
>-rw-r--r-- 1 systemd-network systemd-network 303 Dec 13 23:19 2
>
>/run/systemd/netif/links:
>total 8
>drwxr-xr-x 2 systemd-network systemd-network  80 Dec 13 23:19 .
>drwxr-xr-x 5 systemd-network systemd-network 120 Dec 13 23:19 ..
>-rw-r--r-- 1 systemd-network systemd-network 119 Dec 13 21:49 1
>-rw-r--r-- 1 systemd-network systemd-network 664 Dec 13 23:19 2
>
>/run/systemd/netif/lldp:
>total 4
>drwxr-xr-x 2 systemd-network systemd-network  60 Dec 13 23:19 .
>drwxr-xr-x 5 systemd-network systemd-network 120 Dec 13 23:19 ..
>-rw-r--r-- 1 systemd-network systemd-network 298 Dec 13 23:19 2

Create a new container to play with, then boot it using `machinectl`:
> mkdir /var/lib/containers/test
> pacstrap -c /var/lib/containers/test
> machinectl start test

Inspect `/run/systemd/netif` again (from the host):
> [root@kryptos machines]# ls -al /run/systemd/netif/**
> -rw-r--r-- 1 systemd-network systemd-network 145 Dec 13 23:20 /run/systemd/netif/state
>
>/run/systemd/netif/leases:
>total 4
>drwxr-xr-x 2             **981**             **981**  60 Dec 13 23:20 .
>drwxr-xr-x 5             **981**             **981** 120 Dec 13 23:20 ..
>-rw-r--r-- 1 systemd-network systemd-network 303 Dec 13 23:20 2
>
>/run/systemd/netif/links:
>total 8
>drwxr-xr-x 2             **981**             **981**  80 Dec 13 23:20 .
>drwxr-xr-x 5             **981**             **981** 120 Dec 13 23:20 ..
>-rw-r--r-- 1 systemd-network systemd-network 119 Dec 13 21:49 1
>-rw-r--r-- 1 systemd-network systemd-network 664 Dec 13 23:20 2
>
>/run/systemd/netif/lldp:
>total 4
>drwxr-xr-x 2             **981**             **981**  60 Dec 13 23:20 .
>drwxr-xr-x 5             **981**             **981** 120 Dec 13 23:20 ..
>-rw-r--r-- 1 systemd-network systemd-network 298 Dec 13 23:20 2

Note how the owner/group of `/run/systemd/netif`, `/run/systemd/netif/leases`, `/run/systemd/netif/links`, and `/run/systemd/netif/lldp` have been changed to **981**.

Also, note the aforementioned spam in the journal.

**Workaround**
As a workaround, I've found that running `chown -R systemd-network:systemd-network /run/systemd/netif` from the host appears to fix things up.

**Comment by yuwata** [comment]
Does it work correctly with v246?

**Comment by juliacartwright** [comment]
Unfortunately I don't have that information, as I just started experimenting when running v247.  And: this system isn't in the place right now to try an older systemd.  Maybe if I can figure out systemds build system + mkosi I can give it a test under kvm.

**Comment by poettering** [comment]
This is really werid.

What's the precise nspawn cmdline/.nspawn file you use? Anything that is not default?

**Comment by juliacartwright** [comment]
With the container I first saw this issue with, I was using the following `.nspawn`:

>[Network]
>Zone=cont
>Port=tcp:2222:22

However, I was able to reproduce this without this `.nspawn` at all, completely with the defaults, strictly following the reproduction steps above.

**Comment by juliacartwright** [comment]
Update: some further testing has shown that this issue occurs not when the container is booted, but when `pacstrap` is executed, which means to me that this is either a `pacman` bug (something about running the `.install` scripts outside of the specified root?) or a bug in Arch's `systemd` packaging.  Still investigating.

**Comment by juliacartwright** [comment]
Update to the update: `pacstrap`, when constructing the environment, bind mounts the host's `/run` read-write.  After the install, `systemd-sysusers` is executed, which allocates the new uid/gid in the guest (in my example case, uid/gid **981** are allocated in the guest for `systemd-network`).  After the installation transaction, an installed `systemd-tmpfiles` hook is invoked, which then sets permissions on `/run/systemd/netif` using the _guest_ allocated uid/gids.  This is what causes issues on the host.

Turns out, this issue has already been identified and filed to the `arch-install-scripts` package as [FS#61808](https://bugs.archlinux.org/task/61808).

At this point, this issue should be closed.  Thanks!
