### ISSUE TITLE
#17957 looks strange to me (core/namespace: ignore ENOENT for /proc/sys/kernel/domainname and hostname)

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#17979]
Just a tracker bug, to make sure this is not forgotten. See my comments on #17957.

**Comment by yuwata** [comment]
> I am puzzled by this. How can it be that these files are missing? they are kernel API, so they can#t be missing?
> 
> This smells a lot like taping over some other problems? What am I not getting?

Yeah, the commit 0ebc9f23faf5586f8a9250c3be08773eb3f8d2da can be reverted.

The commit 61f8a7bd3e20222617fc59f398071daf2af86f96 (#17872) had an issue (fix is waiting in #17977). @veecue tested the commit on lxc environment, then as you can see in https://pastebin.com/C99BLSUS, /proc is not mounted but setup_namespace() succeeds. So, /proc/sys/kernel/domainname and hostname do not exist.
With the fix #17977, /proc is always mounted, or `setup_namespace()` fails earlier. So, it is not necessary to set `.ignore = true` anymore.

**Comment by yuwata** [comment]
The revert commit is added to #17977.
