### ISSUE TITLE
Systemd-resolved (MDNS) – "AA" (Authoritative Answer) Bit is not set in MDNS response messages 

### ISSUE THREAD

**Issue by jonas1811** [systemd/systemd#17972]
Hi, 

We just switched from using avahi to systemd's implementation of MDNS-SD in our embedded devices. 
Our device is not discovered anymore due to AA bit not set in the MDNS response messages. 

I didn't see any code in systemd-resolved which would set the AA bit.
I have patched the code (in a dirty way) to set the AA bit and verified that this resolves our issue.

From RFC 6762, chapter 18.4: 
    "In response messages for Multicast domains, **the Authoritative Answer bit MUST be set to one**" 

The issue is seen on a recent NXP board based on linux-imx-5.4.24 and systemd 243.2 
But also in the latest mainline code of systemd I didn’t find any code related to setting the AA bit. 
It should be a quite simple fix, I just didn’t find the "right" place to set the bit. 

Regards 
Jonas

**Comment by pemensik** [comment]
It should set aa bit also for any names it provides locally via stub, not only mdns. It does not provide aa bit even for localhost or _gateway. Even on current main branch.

```
$ dig @127.0.0.53 _gateway

; <<>> DiG 9.16.11-RedHat-9.16.11-2.fc32 <<>> @127.0.0.53 _gateway
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44765
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_gateway.			IN	A

;; ANSWER SECTION:
_gateway.		0	IN	A	192.168.88.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Čt úno 11 13:30:04 CET 2021
;; MSG SIZE  rcvd: 53
```
