### ISSUE TITLE
Unicast DNS for corp.local fails with "No appropriate name servers or networks for name found"

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#17970]
My employer uses several Active Directory domains. One of which is called `corp.local`.

This conflicts with the use of `local.` for link-local networking.

However, this domain was created long before RFC 6762 came about. I believe Microsoft used to actually recommend AD domains be created underneath `local.`!

So in practice, `systemd-resolved` has to deal with this.

Now the funny thing is that until about 30 minutes ago, I had no trouble resolving names underneath `corp.local` with `systemd-resolved`. But from examining `dpkg.log`, I can see that I upgraded systemd from 446 -> 447 on Thursday, and according to the journal, `systemd-resolved` didn't get restarted until just now. So it looks like this is a change in behaviour caused by this update.

If I bypass `systemd-resolved` and go straight to my DHCP-provided DNS server, I'm able to resolve stuff under `corp.local` just fine. So at most, this appears to be a problem with my own system.

I do recall the change in 088648d081e9bc27f53c6471b91109569b29322f - might that have unintentionally caused this behaviour change? I know it's only supposed to be related to LLMNR, but there's nothing else in the changelog between 246 and 247...

I also found the following comment in `resolved-dns-scope.c`, at the end of the code that handles `DNS_PROTOCOL_DNS`:

```
/* Exclude link-local IP ranges */
if (dns_name_endswith(domain, "254.169.in-addr.arpa") == 0 &&                                              
    dns_name_endswith(domain, "8.e.f.ip6.arpa") == 0 &&                                                    
    dns_name_endswith(domain, "9.e.f.ip6.arpa") == 0 &&                                                    
    dns_name_endswith(domain, "a.e.f.ip6.arpa") == 0 &&                                                    
    dns_name_endswith(domain, "b.e.f.ip6.arpa") == 0 &&                                                    
    /* If networks use .local in their private setups, they are supposed to also add .local to their search
     * domains, which we already checked above. Otherwise, we consider .local specific to mDNS and won't   
     * send such queries ordinary DNS servers. */
    dns_name_endswith(domain, "local") == 0)                                                               
        return DNS_SCOPE_MAYBE;                                                                            
```

This dates back to 2015, so it's not a recent change. But I did a little experiment and explicitly added `local` to the list of domains for my network interface, and it caused `resolved` to resume handling queries for `corp.local`.

But... I really don't think you can expect every network operator to add `local` to the domain search list that their DHCP server hands out. So I'm hoping that this behaviour change was unintentional and can be reverted.

**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)
 > `Linux myhost.corp.example.com 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > `x86_64`

**Expected behaviour you didn't see**
 ```
$ dig +short corp.local
192.0.2.1
192.0.2.2
```

**Unexpected behaviour you saw**
 ```
$ dig corp.local

; <<>> DiG 9.16.8-Debian <<>> +multi corp.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 46119
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;corp.local.		IN A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Dec 14 13:14:30 GMT 2020
;; MSG SIZE  rcvd: 39
```

**Steps to reproduce the problem**
> Try to use `resolved` in a Windows world ;)

**Comment by poettering** [comment]
Please see documentation. This is explicitly documented:

>        •   Other multi-label names are routed to all local interfaces that have a DNS server configured, plus the globally configured DNS servers if there are any. Note that by default, lookups for domains with the ".local" suffix
>           are not routed to DNS servers, unless the domain is specified explicitly as routing or search domain for the DNS server and interface. This means that on networks where the ".local" domain is defined in a site-specific DNS
>           server, explicit search or routing domains need to be configured to make lookups within this DNS domain work. Note that these days, it's generally recommended to avoid defining ".local" in a DNS server, as RFC6762[2]
 >          reserves this domain for exclusive MulticastDNS use.

See systemd-resolved(8) for further info.

Not sure why this ever worked for you, it was not supposed to. Maybe your DHCP server started advertising different search domains? Or your network management solution stopped propagating it or so?

Either way, let's close this, as the current behaviour is clearly documented I think (including ways out of it), and using .local for unicast DNS against current RFCs.
