### ISSUE TITLE
Systemd-resolved (MDNS) – queries with "QU" bit are dropped. Bit is wrongly interpreted as cache-flush bit. 

### ISSUE THREAD

**Issue by jonas1811** [systemd/systemd#17973]
Hi,

We just switched from using avahi to systemd's implementation of MDNS-SD in our embedded devices.
The device does not reply anymore to MDNS queries which have the "QU" bit set. 

Systemd-resolved drops the QU question because it wronlgy interprets the bit as a "cache-flush" bit:
The "QU" bit is the top bit in the class field of a DNS question, whereas the "cache-flush" bit is the top bit in the class field of a DNS response. 
The implementation in` /src/resolve/resolved-dns-packet.c:dns_packet_read_key()` called by `dns_packet_extract_question()` does not distinguish this and thus the DNS question is dropped with  
```
    if (cache_flush) 
       return -EBADMSG; 
```
       
Commenting out the above return statement solves the issue in the sense that a multicast response is send. 
However, ideally a unicast-response should be send. 

From RFC 6762, chapter 5.4: 
"To avoid large floods of potentially unnecessary responses in these cases, Multicast DNS defines the top bit in the class field of a DNS question as the unicast-response bit. When this bit is set in a question, it indicates that the querier is willing to accept unicast replies in response to this specific query, as well as the usual multicast responses. These questions requesting unicast responses are referred to as "QU" questions, to distinguish them from the more usual questions requesting multicast responses ("QM" questions). A Multicast DNS querier sending its initial batch of questions immediately on wake from sleep or interface activation SHOULD set the unicast-response bit in those questions." 

The issue is seen on a recent NXP board based on linux-imx-5.4.24 and systemd 243.2 
I still see the bug in the latest mainline source code of systemd. 

Regards
Jonas

**Comment by jonas1811** [comment]
Hi @bugaevc ,
i see you have been working on this few weeks back.
Did a fix already make it into the main branch?
Thanks for your help!

**Comment by bugaevc** [comment]
Hi :slightly_smiling_face:

My fix, which is in PR https://github.com/systemd/systemd/pull/18701, was to be merged after the [248 release](https://github.com/systemd/systemd/releases/tag/v248). Apparently the maintainers haven't gotten to testing/merging it yet.
