### ISSUE TITLE
networkd: An option to set VLAN egress QoS maps in netdev files

### ISSUE THREAD

**Issue by jess-sch** [systemd/systemd#17989]
**Is your feature request related to a problem? Please describe.**
My VDSL ISP (NetCologne) requires me to set the default egress QoS to 6 on the voice VLAN. This can be done by manually by running `ip link set voice type vlan egress 0:6` (or using a oneshot service), though the DHCP configuration in the network file does not work this way (because the DHCP request is sent before the mapping is applied).

**Describe the solution you'd like**
netdev files should have some sort of setting in their `[VLAN]` sections to pass an egress QoS mapping. This might be called `EgressQoSMap` and be a space-separated list of `from:to` mappings, similarly to the syntax used by iproute2.

**Describe alternatives you've considered**
Alternatively, systemd-networkd could allow (oneshot) services to require to be run `Before=` .network files are handled, but `After=` .netdev files are handled.

**Comment by longhuaizhang991108** [comment]
I set up 80-80 vlan.netdev under /etc/systemd/network in ubuntu20.04, add EgressQOSMaps=4-0 to the file, and check the vlan configuration under /pro/net/vlan. EGRESS priority mappings: Have any of these leaders any idea why this is?

**Comment by longhuaizhang991108** [comment]
The following files are written in systemd/network
/systemd/network：
80-80vlan.netdev
[Match]
Virtualization=no
[NetDev]
Name=eno1.202
Kind=vlan
[VLAN]
Id=202
Protocol=802.1q
ReorderHeader=yes
IngressQOSMaps=0-0
EgressQOSMaps=4-0

85-vlan.network
[Match]
Name=eno1.202
[Network]
Address=10.202.0.1/16
[DHCPv4]
SocketPriority=4
