### ISSUE TITLE
Controlling randomization of MAC Addresses related to P2P-device type

### ISSUE THREAD

**Issue by Ircama** [systemd/systemd#17980]
Which is the appropriate method to control MAC Addresses managed by the cfg80211 subsystem for devices of type `NL80211_IFTYPE_P2P_DEVICE`, like a device of type *P2P-device* (Unnamed/*non-netdev* interface), so that *systemd.udev*/*systemd.link* (or other methods) can be used (e.g., with `MACAddressPolicy=persistent`) to keep the MAC address unaltered on any subsequent interface creation, with only the first creation performed with randomization?

Specifically, I am referring to the way *wpa_supplicant* currently uses [`nl80211_create_iface_once()`](https://w1.fi/cgit/hostap/tree/src/drivers/driver_nl80211.c#n5188): the creation of a new interface of type `NL80211_IFTYPE_P2P_DEVICE` generates random MAC addresses, unless the code is modified (e.g, by adding `NL80211_ATTR_MAC`/`NL80211_ATTR_MAC_MASK`, so that a fixed address is defined).

I think that MAC randomization is internal default behavior of the cfg80211 device driver and that udev at the moment has no control of unnamed/non-netdev interfaces.

The question is related to the need to appropriately configure the system to support Wi-Fi Direct (P2P) persistent groups also after restarting *wpa_supplicant*, without changing *wpa_supplicant* code. In fact, in my case, a persistent P2P-GO group works correctly while *wpa_supplicant* is running. After restarting it, the saved persistent group in the peer device becomes no more usable for fast reconnection: only a new persistent group can be established, usable until *wpa_supplicant* is subsequently restarted. The expected behavior is that a fast reconnection to the previously saved group is possible also after restarting *wpa_supplicant*. This problem happens because each time *wpa_supplicant* creates a *P2P-device* type interface, it randomly creates a MAC address and this breaks the persistent P2P Group reuse.

If there is no possibility to control the MAC address randomization process of *non-netdev* devices, a change in *wpa_supplicant* has to be made to appropriately manage this use case. Just for testing, I in fact verified that, by adding the following code before [`ret = send_and_recv_msgs(drv, msg, handler, arg, NULL, NULL);`](https://w1.fi/cgit/hostap/tree/src/drivers/driver_nl80211.c#n5229) of `nl80211_create_iface_once()` in *hostap/src/drivers/driver_nl80211.c* (with hardwired MAC in my example, just for testing), *wpa_supplicant* performs as expected also after a restart.

```
    if (iftype == NL80211_IFTYPE_P2P_DEVICE) {
        u8 mac_addr[ETH_ALEN];
        if (hwaddr_aton2("dc:a6:32:01:02:03", mac_addr))
            if(nla_put(msg, NL80211_ATTR_MAC, ETH_ALEN, mac_addr))
                goto fail;
    }
```

Anyway, before considering a solution within *wpa_supplicant*, I would ask whether there are methods with *systemd*, or new developments can be planned (e.g., with udev) to externally define a *P2P-device* MAC address.

Ref. https://github.com/systemd/systemd/issues/13642 and https://github.com/raspberrypi/firmware/issues/1510.

**Comment by yuwata** [comment]
I am not familiar with the device type. Could you show how to test it? Is it possible test on e.g. normal laptop?

Also, could you show the results of `networkctl status INTERFACE` and `udevadm info /sys/class/net/INTERFACE`?

BTW, disabling `MACAddressPolicy=` does work for the device? If it works and is an expected way, then we can provide, say, 98-nl80211-p2p-default.link.

**Comment by Ircama** [comment]
> I am not familiar with the device type. Could you show how to test it? Is it possible test on e.g. normal laptop?

*wpa_supplicant* correctly processes persistent groups when the created *P2P-device* interface always gets the same address at process restart. I am performing the tests on a Raspberry Pi running *Rasperry Pi OS "buster"*, Debian-based. To test, I kill the process and restart it, then I issue `iw dev`:

```
phy#0
        Unnamed/non-netdev interface
                wdev 0x70
                addr dc:02:03:04:05:06
                type P2P-device
                txpower 31.00 dBm
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr dc:a6:32:00:9a:f5
                ssid TIM-86817771
                type managed
                channel 100 (5500 MHz), width: 40 MHz, center1: 5510 MHz
                txpower 31.00 dBm
```

In the shown case, I forced the address `dc:02:03:04:05:06` by modifying the code as noted. With unmodified *wpa_supplicant*, the `addr` field of the `Unnamed/non-netdev interface` gets random values (e.g., de:03:42:78:6a:d7 in my last test). Simply use an official *wpa_supplicant* version and check that field each time the process is restarted.

---------------

> Also, could you show the results of `networkctl status INTERFACE` and `udevadm info /sys/class/net/INTERFACE`?

As this *P2P-device* type interface is unnamed, I am not able to use `networkctl status INTERFACE` over this interface. If I run `networkctl -a status`, its output does not report that interface (maybe because Unnamed/non-netdev):

```
● 1: lo
       Link File: n/a
    Network File: n/a
            Type: loopback
           State: carrier (unmanaged)
         Address: 127.0.0.1
                  ::1

● 2: eth0
       Link File: n/a
    Network File: n/a
            Type: ether
           State: routable (unmanaged)
            Path: platform-fd580000.ethernet
          Driver: bcmgenet
      HW Address: dc:a6:32:00:9a:f4
         Address: 192.168.1.45
                  fe80::21df:adac:9424:c09c
         Gateway: 192.168.1.1 (Technicolor)

● 3: wlan0
       Link File: n/a
    Network File: n/a
            Type: wlan
           State: routable (unmanaged)
            Path: platform-fe300000.mmcnr
          Driver: brcmfmac
      HW Address: dc:a6:32:00:9a:f5
         Address: 192.168.1.24
                  fe80::3c1d:2ab8:167b:77b
         Gateway: 192.168.1.1 (Technicolor)
```

Also, if I issue `ls -l /sys/class/net`, I do not get a link to this interface:

```
total 0
lrwxrwxrwx 1 root root 0 Dec 15 09:29 eth0 -> ../../devices/platform/scb/fd580000.ethernet/net/eth0
lrwxrwxrwx 1 root root 0 Dec 15 09:29 lo -> ../../devices/virtual/net/lo
lrwxrwxrwx 1 root root 0 Dec 14 12:15 wlan0 -> ../../devices/platform/soc/fe300000.mmcnr/mmc_host/mmc1/mmc1:0001/mmc1:0001:1/net/wlan0
```

Besides, `ls -l /sys/devices/virtual/net` only reports the loopback:

```
total 0
drwxr-xr-x 5 root root 0 Dec 15 09:29 lo
```

-------------

> BTW, disabling *MACAddressPolicy=* does work for the device? If it works and is an expected way, then we can provide, say, 98-nl80211-p2p-default.link.

Before opening this issue, I have tried to use */etc/systemd/network/12-p2p-wlan0.link* without success: I am not able to select *[Match]* attributes because names (also *wdev*) are dynamically generated (any advice is useful here); anyway, in the [Link] section, *MACAddress* and *MACAddressPolicy* do not seem to have any effect on that interface. Is it because, being Unnamed/non-netdev, it is not managed by udev? In such case I think that that *wpa_supplicant* should be the only possible controller of that resource.

I suspect *wpa_supplicant* shall be the only valid controller of the P2P-device interface it creates, because this interface can get random addresses when no persistent group is configured, while it shall reuse the same address when e.g. a section like the following appears in the configuration file (e.g., */etc/wpa_supplicant/wpa_supplicant.conf*), maybe allowing to reuse the reported *bssid* (this is the way persistent groups are defined in *wpa_supplicant.conf*):

```
network={
        ssid="My-persistent-group"
        bssid=de:03:42:78:6a:d7
        psk="mypassword"
        proto=RSN
        key_mgmt=WPA-PSK
        pairwise=CCMP
        auth_alg=OPEN
        mode=3
        disabled=2
}
```

**Comment by Ircama** [comment]
The MAC address that needs to be reused is related to a P2P-device which is an unnamed/non-netdev interface, that is not controlled by *systemd/udev*. To check this, after appropriately configuring *wpa_supplicant.conf*, I have run the following:

```
systemctl stop dhcpcd # this stops wpa_supplicant
udevadm monitor --environment kernel & # monitor udev events
systemctl start dhcpcd # restarts wpa_supplicant
fg # use control-C to stop udevadm
```

No information is reported by the monitor on the P2P-device, even if it is created by *wpa_supplicant*.

I am closing this issue as it is not applicable to *udev*.

Additional information to address the mentioned *wpa_supplicant* issue is in https://github.com/raspberrypi/firmware/issues/1510#issuecomment-774749551.
