### ISSUE TITLE
Too many open files - with 100+ nspawn containers started.

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#17992]
**systemd version the issue has been seen with**
systemd 246 (v246.6-3.fc33)

**Used distribution**
Fedora 33

**Linux kernel version used** (`uname -a`)
Linux r2.d250.hu 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Services starting normally.

**Unexpected behaviour you saw**
Services failing randomly.

**Steps to reproduce the problem**
- Create over 100 containers

Some configs: 

```
/etc/security/limits.d/srvctl-limits.conf
*         hard    nofile      1048576
*         soft    nofile      1048576
root      hard    nofile      1048576
root      soft    nofile      1048576
*         hard    memlock      unlimited
*         soft    memlock      unlimited

/etc/sysctl.d/srvctl-sysctl.conf
fs.file-max = 4194304
fs.inotify.max_queued_events = 2097152
fs.inotify.max_user_instances = 2097152
fs.inotify.max_user_watches = 2097152

kernel.pid_max=4194304

## use minimum of swap
vm.swappiness = 1
```

```
Uptime:  10:07:12 up 34 days,  6:49,  2 users,  load average: 0,31, 0,43, 0,59

vmstat -s
    131715440 K total memory
     57702684 K used memory
     56870620 K active memory
     35503640 K inactive memory
      7852692 K free memory
         4576 K buffer memory
     66155484 K swap cache
      8388600 K total swap
        28416 K used swap
      8360184 K free swap
    147736936 non-nice user cpu ticks
      6280624 nice user cpu ticks
     78387756 system cpu ticks
   9079872132 idle cpu ticks
       110135 IO-wait cpu ticks
     30849202 IRQ cpu ticks
     22905444 softirq cpu ticks
            0 stolen cpu ticks
   3988689611 pages paged in
   2573594609 pages paged out
          921 pages swapped in
        24209 pages swapped out
   1809105290 interrupts
   3573512951 CPU context switches
   1605147435 boot time
     20099083 forks

```

I don't think I had these problems before, but it might be that I see this now since reached 100+ containers.
The error messages have various forms of `Too many open files`
`Failed to allocate directory watch: Too many open files`

The error message makes some services fail, then some containers or the host reboot helps temporarly. ..

I could not pinpoint yet which resource is running out.

Could anyone shed light on how to debug this further?

**Comment by LaKing** [comment]
lsof line count on the host: 3586494 
sum of lsof line count of all containers: 3589670

**Comment by poettering** [comment]
> Failed to allocate directory watch: Too many open files

That suggests it's actually about inotify watches . Maybe you have something that watches stuf recursively (which costs a ton of inotify watches, and is generally a poor idea), and eats them all up? There's nothing much systemd can do about that. You can just bump the inotify watch limits on the host drastically. If you do, does this go away?

**Comment by LaKing** [comment]
There is no code in my hand that does recursive watches. Most containers run wordpress instances, some nodejs, etc. generic webserver. ...

```
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: systemd v246.6-3.fc33 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Detected virtualization systemd-nspawn.
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Detected architecture x86-64.
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: 
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Welcome to Fedora 33 (Thirty Three)!
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: 
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Set hostname to <carco.one>.
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Failed to create control group inotify object: Too many open files
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Failed to allocate manager object: Too many open files
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: [!!!!!!] Failed to allocate manager object.
dec 21 12:43:57 r2.d250.hu systemd-nspawn[1799762]: Exiting PID 1...
```

I didn't set the inotify limits higher yet, so I can track a bit more incidence of the problem.

Is there a configuration option to apply limits on the containers and set the limits on the host so that we can run a number of containers safely? The goal would be that containers never take down services on the host. 
Would be setting limits for syctl and security limits effective on containers?

**Comment by LaKing** [comment]
I found a good [post on stackexchange](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached)

It looks like my settings in `/etc/sysctl.d/srvctl-sysctl.conf` is not effective. 
```
[root@r2 sysctl.d]# cat /proc/sys/fs/inotify/max_user_watches
524288
```
I've set manually ...
```
[root@r2 sysctl.d]# sysctl fs.inotify.max_user_watches=2097152
fs.inotify.max_user_watches = 2097152
```
Ok, now it seems to report the new value.
```
[root@r2 ~]# cat /proc/sys/fs/inotify/max_user_watches
2097152
```
Not sure if this method with testing of tail is accurate but `tail -f /var/log/boot.log-20200212` ends with...
```
tail: inotify cannot be used, reverting to polling: Too many open files
``` 
And indeed several services report `Failed to allocate directory watch: Too many open files` 
So I went ahead, and increased further.
```
[root@r2 ~]# sysctl fs.inotify.max_user_watches=4194304
fs.inotify.max_user_watches = 4194304
```
Now neither the tail command, nor the services report too many open files. This might be a coincidence, or might be an indication for succes. Will check again to make sure it's a success.

The question what remains is, what a safe value would be and how to set it permanently ... and how to prevent containers from excessive usage of that resource. ...

**Comment by poettering** [comment]
Can you check with `SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-sysctl` whether the setting is properly written to your sysctl?

**Comment by LaKing** [comment]
@poettering good point, ... seems they were not, .... 

Thanks,...

**Comment by poettering** [comment]
what was the reason they weren't?

**Comment by LaKing** [comment]
@poettering There were two files in `/etc/sysctl.d`, a symlink to `/etc/sysctl.conf` and my own `srvctl-sysctl.conf`.
While trying to figure out the problem I've set `inotify.max_user_watches` in both files, so when I set my sysctl later on, the symlink named `99-sysctl.conf` was overriding it. The command you wrote nicely indicated this, so this minor configuration issue is resolved, my bad. ...

The bigger-better-moreimportant question would be still a sort of managment of that resource on containers and host. As far as I understand this parameter reseves memory on the host. However, if containers can exhaust that resource, and there is no way to limit this on containers, then a single container can render the host unstable, by using up inotify watches, which leads to randomly failing host services.

Another theroetic question is what safe value should be set. I guess the higher the better, but since memory is scarce, ...
4194304 per 100 containers - assuming some sort of avarage load ... ?

**Comment by LaKing** [comment]
Unfortunatley, the problem reappeard. :(

New containers wont start.
```
systemd-nspawn[3375089]: Failed to create control group inotify object: Too many open files
systemd-nspawn[3375089]: Failed to allocate manager object: Too many open files
systemd-nspawn[3375089]: [!!!!!!] Failed to allocate manager object.
```

The tail command suggest ionotify failure.
```
tail: inotify cannot be used, reverting to polling: Too many open files
```

Max watches is increased and the setting is active:
```
[root@r2 ~]# cat /proc/sys/fs/inotify/max_user_watches
4194304
```
```
[root@r2 ~]# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-sysctl
Parsing /usr/lib/sysctl.d/10-default-yama-scope.conf
Parsing /usr/lib/sysctl.d/50-coredump.conf
Parsing /usr/lib/sysctl.d/50-default.conf
Parsing /usr/lib/sysctl.d/50-libkcapi-optmem_max.conf
Parsing /usr/lib/sysctl.d/50-pid-max.conf
Parsing /etc/sysctl.d/srvctl-sysctl.conf
Setting 'kernel/yama/ptrace_scope' to '0'.
Setting 'kernel/core_pattern' to '|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h'.
Setting 'kernel/core_pipe_limit' to '16'.
Setting 'fs/suid_dumpable' to '2'.
Setting 'kernel/sysrq' to '16'.
Setting 'kernel/core_uses_pid' to '1'.
[...]
Setting 'fs/file-max' to '4194304'.
Setting 'fs/inotify/max_queued_events' to '2097152'.
Setting 'fs/inotify/max_user_instances' to '2097152'.
Setting 'fs/inotify/max_user_watches' to '4194304'.
Setting 'vm/swappiness' to '1'.

```

So, really drastically incremented limits now.
```
[root@r2 sysctl.d]# cat srvctl-sysctl.conf 
## srvctl3 containerfarm

fs.file-max = 16777216
fs.inotify.max_queued_events = 8388608
fs.inotify.max_user_instances = 8388608
fs.inotify.max_user_watches = 16777216

kernel.pid_max=16777216

## use minimum of swap
vm.swappiness = 1
```

Let's see if that helps ...

**Comment by hinell** [comment]
@LaKing 
On my machine the output of `sysctl --all` : 
```
...
fs.file-max = 9223372036854775807
...
```

**Comment by dajianderichang** [comment]
> Did that get resolve? I'm experiencing the same issue with KiND, when deploy a multi-node cluster on a same host.

there have a script, the auth very niubi: https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers
it's view a user current use how much instance, a  process watch how much file.

**Comment by peterwaller-arm** [comment]
I've just hit this on a shared machine running systemd inside docker containers. I was able to workaround it by increasing user.max_inotify_instances.

I am running the containers using `docker run --rm ...` so that the container should be gone, but I suspect something must be leaking handles somewhere such that the container is not actually gone.
