### ISSUE TITLE
Please guarantee that VPN will be up before ANY network access occurs

### ISSUE THREAD

**Issue by BillDietrich** [systemd/systemd#17993]
**Is your feature request related to a problem? Please describe.**
In my Kubuntu 20.10 system, and others, if I have set VPN to start automatically: I get notified first that Ethernet is up, then a second or two later, that VPN is up.

This make me wonder if there is any guarantee that VPN will be up before ANY network access takes place.  Since I specified "automatic connection to VPN", obviously I want every single access to occur through the VPN.

**Describe the solution you'd like**
Provide some kind of policy statement that:
If system is set to have "automatic connection to VPN", every single non-localhost network access will occur through the VPN, at system boot time, login time, if VPN server goes down, anything.  Every access must go through VPN, or fail.

Then, if needed, change software to implement that policy.

**Describe alternatives you've considered**
The work could be pushed down to the distro or user level, forcing them to modify systemd units or write iptables rules.  This would result in huge duplication of effort, and probably security holes.  Best if the work is done in the base systemd units.

Thanks.

**Comment by poettering** [comment]
Hmm, systemd is not the place that deals with VPNs. I presume Kubuntu uses NetworkManager that does that. Please contact the NetworkManager community about that (and maybe Kubuntu), but from systemd's side there's nothing we can do about how NM sets up networking, and in which order and what it does to the rest of the system while it does that.

Hope that makes sense.

**Comment by BillDietrich** [comment]
Okay, thanks, filed https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/610
