### ISSUE TITLE
networkd: IPv6PrivacyExtensions=kernel doesn't honor kernel setting

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#18003]
**systemd version the issue has been seen with**
 > 247, 247.1

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)
 > Linux 5.4.83

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > networkd honors the `net.ipv6.conf.$interface.use_tempaddr` sysctl values set when `IPv6PrivacyExtensions=kernel` is set

**Unexpected behaviour you saw**
 > `net.ipv6.conf.$interface.use_tempaddr` is `-1`, no IPv6 private IP addresses are assigned, traffic goes out with the EUI-64 address

**Steps to reproduce the problem**
 > Configure your interface with `IPv6PrivacyExtensions=kernel`, set the `net.ipv6.conf.$interface.use_tempaddr` sysctl to 2`, plug it into a network with IPv6 router advertisements

[Bisecting](https://github.com/NixOS/nixpkgs/issues/106858#issuecomment-745992338) showed this seems to have been introduced by https://github.com/systemd/systemd/commit/5e0534f1c13cd50ec2b143a8b18156cd37e502f7, which was part of https://github.com/systemd/systemd/pull/17240. More details are in https://github.com/NixOS/nixpkgs/issues/106858#issuecomment-745992338.

**Comment by WhoNeedszZz** [comment]
Considering this has to do with privacy why has this not been patched yet?
