### ISSUE TITLE
Systemd is not using environment from /etc/profile.d on CentOS 7

### ISSUE THREAD

**Issue by noloader** [systemd/systemd#18028]
**systemd version the issue has been seen with**
 > systemctl --version
 > systemd 219
 > +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Used distribution**
 > CentOS 7
 > lsb_release -a
 > LSB Version:    :core-4.1-amd64:core-4.1-noarch
 > Distributor ID: CentOS
 > Description:    CentOS Linux release 7.9.2009 (Core)
 > Release:        7.9.2009
 > Codename:       Core

**Linux kernel version used** (`uname -a`)
 > uname -a
> Linux ftpit 2.6.32-042stab120.6 #1 SMP Thu Oct 27 16:59:03 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Systemd to use the environment setup in `/etc/profile.d`

**Unexpected behaviour you saw**
 >  Systemd using some random environment

**Steps to reproduce the problem**
 > 1. Install Red Hat's Software Collections (SCL)
 > 2. Enable SCL's Python, PHP and Apache in `/etc/profile.d`
 > 3. Schedule a Systemd service that uses Python

> Here's what we are seeing in our backup job, which runs `duplicity`. `duplicity` is a python-based script:
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: Traceback (most recent call last):
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: File "/opt/rh/python27/root/usr/bin/duplicity", line 1636, in <module>
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: util.release_lockfile()
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: File "/usr/lib64/python2.7/site-packages/duplicity/util.py", line 161, in release_lockfile
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: if globals.lockfile and globals.lockfile.is_locked():
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: AttributeError: '_FcntlLock' object has no attribute 'is_locked'
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: duplicity failed with error 0
> Dec 19 16:34:22 ftpit systemd[1]: bitvise-backup.service: main process exited, code=exited, status=1/FAILURE
> Dec 19 16:34:22 ftpit bitvise-backup[26980]: bitvise-backup encountered an error

We did not make any changes to the environment or Systemd. The gear in `/opt/rh/python27/root/usr/bin` should **NOT** be using Python from `/usr/lib64/python2.7`. The environment appears broken under Systemd.

Here's how to enable the updated components from SCL:

```bash
# cat /etc/profile.d/enable-scl-python27.sh
#!/usr/bin/env bash
source scl_source enable python27

# cat /etc/profile.d/enable-scl-php73.sh
#!/usr/bin/env bash
source scl_source enable rh-php73

# cat /etc/profile.d/enable-scl-httpd24.sh
#!/usr/bin/env bash
source scl_source enable httpd24
```

Here's a typical output from an updated command:

```bash
# command -v python
/opt/rh/python27/root/usr/bin/python

# python --version
Python 2.7.18
```

**Comment by arvidjaar** [comment]
> Expected behaviour you didn't see
> Systemd to use the environment setup in /etc/profile.d

Why do you expect this behavior? `systemd` is not shell and never interpreted any shell startup script.

**Comment by poettering** [comment]
/etc/profile.d is the profile script for shells. systemd is not a shell.

Also, the submission form should have made very clear that only issues with current systemd versions are to be reported here. For everything older, contact your downstream distro vendor.

**Comment by noloader** [comment]
> Why do you expect this behavior? systemd is not shell and never interpreted any shell startup script.

I expect Systemd to follow conventions on CentOS. Red Hat developed the procedures. It is the official procedure.

> Also, the submission form should have made very clear that only issues with current systemd versions are to be reported here.

It is current for CentOS 7.

**Comment by poettering** [comment]
> It is current for CentOS 7. There is nothing newer available.

Great, but then contact CentOS for help. This is the *upstream* bug tracker. Current upstream versions this bug tracker is about are v246 + v247

**Comment by poettering** [comment]
> I expect Systemd to follow conventions on CentOS. Red Hat developed the procedures. It is the official procedure. Blowing out the platform's environment is not acceptable, and it breaks other software.

This is bogus. Systemd is not a shell interpretor. Never was. 

If "Software Collections" is saying otherwise, please file a bug against that.
