### ISSUE TITLE
systemd 247 is stuck on a stop job running for user manager at shutdown

### ISSUE THREAD

**Issue by Digitalone1** [systemd/systemd#18023]
**systemd version the issue has been seen with**
 > 247.2.1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.12

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Shutdown properly

**Unexpected behaviour you saw**
 > I see `Unmounted /run/user/1002/gvfs` message, then `A stop job is running for User Manager` that waits 2 minutes before shutdown.

**Steps to reproduce the problem**
 > Restart or shutdown with systemd 247. It's not happening with version 246.

**Comment by XueqiangDong** [comment]
got the same on archlinux version
5.4.84-1-lts
both shutdown/reboot

**Comment by boucman** [comment]
This means that your user session is not ending properly. i.e you have a user software that systemd asked to stop but didn't stop

systemd waits a reasonable time then kills the user process

you need to figure out what is not terminating properly, but that's not a systemd bug. systemd is just the messenger.

**Comment by Digitalone1** [comment]
> you need to figure out what is not terminating properly, but that's not a systemd bug. systemd is just the messenger.

I think it's a systemd bug because it always happens with version > 246

Never happened before.

**Comment by poettering** [comment]
See:  https://github.com/systemd/systemd/issues/12262#issuecomment-747040852
