### ISSUE TITLE
udevadm control --exit does not work

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#1802]
Really easy to reproduce:

```
[root@notas ~]# systemctl --version 
systemd 227
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
[root@notas ~]# systemctl is-active systemd-udevd
active
[root@notas ~]# udevadm control --exit
calling: control
[root@notas ~]# systemctl is-active systemd-udevd
active
```

**Comment by lnykryn** [comment]
Maybe we should deprecate it or at least print a warning message?

**Comment by arvidjaar** [comment]
Service has Restart=always. What systemctl status systemd-udevd says - was it stopped and then started?

**Comment by lnykryn** [comment]
Yep, it has different PID.

**Comment by poettering** [comment]
Well, we nominally still support udev outside of systemd, where the call is still used...

Yeah, we should probably at least document that it is pointless to use in the man page.
