### ISSUE TITLE
file:ABS_FILE_PATH for *Default* StandardOutput and *Default* StandardError

### ISSUE THREAD

**Issue by icegood** [systemd/systemd#18034]
**Is your feature request related to a problem? Please describe.**
The problem is to be able to log issues like #17133 correctly instead of an a-few-seconds message on the screen.

It is well documented that each unit could have StandardOutput and/or StandardError to be 
file:ABS_FILE_PATH
in particular in mine **man systemd.exec:**

_StandardOutput=
           Controls where file descriptor 1 (stdout) of the executed processes is connected to. Takes one of inherit, null, tty, journal, kmsg, journal+console, kmsg+console, file:path, append:path,
           socket or fd:name_
          
However, it doesn't relate to the appropriate default values mentioned in another part of my **man systemd** (are very close to appropriate kernel arguments):

_systemd.default_standard_output=, systemd.default_standard_error=
           Controls default standard output and error output for services and sockets. That is, controls the default for StandardOutput= and StandardError= (see systemd.exec(5) for details). Takes one
           of inherit, null, tty, journal, journal+console, kmsg, kmsg+console. If the argument is omitted systemd.default-standard-output= defaults to journal and systemd.default-standard-error= to
           inherit._

**Describe the solution you'd like**
By given solution, I want to prolong the lifetime of logging in a given files whenever it is possible and therefore be able to 
obtain logs for further analysis 

**Describe alternatives you've considered**
Be able to quickly read and remember all output at the unmount stages like in #17133.

**Comment by poettering** [comment]
I am sorry what?

Everything systemd logs also goes to kmsg and the journal. Always. From initrd on. The console is only an addition target, not the only target of the status/log data.
