### ISSUE TITLE
ResolveUnicastSingleLabel=yes does not resolve NFQDNs with non-search domains

### ISSUE THREAD

**Issue by bluppfisk** [systemd/systemd#18036]
**systemd version the issue has been seen with**
 > 246 (ubuntu 20.10)

**Used distribution**
 > Ubuntu

**Linux kernel version used** (`uname -a`)
 > 5.10

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > ResolveUnicastSingleLabel=yes resolutions also resolving my single-labels when the domain is set to be non-search (~) 

e.g.:

```bash
resolvectl query test
```

> test: 10.28.0.20                             -- link: wg0
> 
> -- Information acquired via protocol DNS in 15.2ms.
> -- Data is authenticated: no

**Unexpected behaviour you saw**

Even with a search-domain, systemd-resolved returns an answer for a composed FQDN (with appended search domain) rather than trying the NFQDN (**Non-Fully-Qualified Domain Name**) first. Only a search domain _AND_ the option `search=no` properly resolve a NFQDN.

**Steps to reproduce the problem**

I set up a single Wireguard tunnel to my corporate network (with domain **example.net**) whose DNS server at **10.28.0.1** can resolve the NFQDN **test** into an IP address **10.28.0.20**.

1. With non-search domain we get no results:

```bash
resolvectl dns wg0 10.28.0.1
resolvectl domain wg0 ~example.net
resolvectl query test
```

> test: resolve call failed: 'test' not  found

2. Setting it to a search-domain simply qualifies the NFQDN into a FQDN by appending .example.net, which relies on the server doing DNS forwarding of test.example.net to **10.28.0.20**. That's not what we want:

```bash
resolvectl domain wg0 example.net
resolvectl query test
```

> test: 10.28.0.20                             -- link: wg0
>         (test.example.net)
> 
> -- Information acquired via protocol DNS in 15.7ms.
> -- Data is authenticated: no
> 

3. When I specifically tell `resolvectl` to not search (but still use the search domain), we get the desired result:

```bash
resolvectl query --search=no test
```

> test: 10.28.0.20                             -- link: wg0
> 
> -- Information acquired via protocol DNS in 15.2ms.
> -- Data is authenticated: no

To me it seems that `ResolveUnicastSingleLabel=yes` is not working with a non-search domain.

## Config:

```bash
resolvectl
```

```
> Global
>        LLMNR setting: no
> MulticastDNS setting: no
>   DNSOverTLS setting: no
>       DNSSEC setting: no
>     DNSSEC supported: no
> 
> Link 2 (wlp0s20f3)
>       Current Scopes: DNS        
> DefaultRoute setting: yes        
>        LLMNR setting: yes        
> MulticastDNS setting: no         
>   DNSOverTLS setting: no         
>       DNSSEC setting: no         
>     DNSSEC supported: no         
>   Current DNS Server: 192.168.1.1
>          DNS Servers: 192.168.1.1
>           DNS Domain: ~.         
>                       home       
> 
> Link 3 (wg0)
>       Current Scopes: DNS       
> DefaultRoute setting: yes       
>        LLMNR setting: resolve   
> MulticastDNS setting: no        
>   DNSOverTLS setting: no        
>       DNSSEC setting: no        
>     DNSSEC supported: no        
>          DNS Servers: 10.28.0.1 
>           DNS Domain: example.net
```

**Comment by poettering** [comment]
Hmm, I am sorry I don't get what the problem is supposed to be? nfqdn? whaa?

Please provide the info requested into the bug submission form, i.e. say exactly what lookup result you expected that you didn't get. I cannot parse what you wrote above?

What is the configuration you actually have in place, i..e. what is the full "resolvectl status" output?

**Comment by bluppfisk** [comment]
@poettering fair enough, I seem to have cut some corners. With NFQDN I meant non-fully qualified domain name, i.e. a single-label hostname (in this case `test`).

I've added the relevant bit of the `resolvectl status` command, and updated the bug as requested.

**Comment by poettering** [comment]
Your wifi interface has `~.` has routing domain, i.e. it preferably wants all traffic, and that includes "test". Drop that. For further details see this:

https://systemd.io/RESOLVED-VPNS/

**Comment by bluppfisk** [comment]
Thanks for looking into this.

Dropping it does not work - single-labels are still not resolved through the wg0 link. It does if I assign `~.` to wg0, but of course I don't want those domain names to be resolved through the company VPN wg0.

I've read the text (I had already) but I can't find how I would have single labels resolved by my company VPN (this might sound contra-intuitive, but in this case my company has made a number of single-label hostnames available through the VPN and it would be preferable to use them).
