### ISSUE TITLE
touchpad device information for Lenovo(IBM) SK-8845

### ISSUE THREAD

**Issue by zhangjiakouzf** [systemd/systemd#18049]
hello, my usb keyboard SK-8845's touchpad wasn't working well with fedora32, and i made a litte change following the instruction in /usr/lib/udev/hwdb.d/70-touchpad.hwdb

-------------------------------------------------------------------------------------------------------

[admin@localhost ~]$ cat /etc/udev/hwdb.d/71-touchpad-local.hwdb 
\# Lenovo UltraNav SK-8845 (USB keyboard)
touchpad:usb:v06cb*
 ID_INPUT_TOUCHPAD_INTEGRATION=external

-------------------------------------------------------------------------------------------------------------------------------

[admin@localhost hwdb.d]$ udevadm info /dev/input/event13
P: /devices/pci0000:00/0000:00:1b.0/sound/card0/input24/event13
N: input/event13
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1b.0/sound/card0/input24/event13
E: DEVNAME=/dev/input/event13
E: MAJOR=13
E: MINOR=77
E: SUBSYSTEM=input
E: USEC_INITIALIZED=9336862
E: ID_INPUT=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=pci-0000:00:1b.0
E: ID_PATH_TAG=pci-0000_00_1b_0
E: LIBINPUT_DEVICE_GROUP=0/0/0:ALSA
E: TAGS=:power-switch:

-----------------------------------------------------------------------------------------------------------

BTW. the configuration of this usb keyboard's trackpoint(stick) has already existed in "70-pointingstick.hwdb", but there isn't the configuration for touchpad

**Comment by poettering** [comment]
please submit this patch as PR! Then we can merge it and correctly attribute it to you

**Comment by poettering** [comment]
Let's close this. We'd still like this to be added, but since we can't test this ourselves since we lack the hw, please submit a ready-made PR, which we can then merge and properly attribute to you. Thank you.
