### ISSUE TITLE
sd_notify and sd_journal_* not working inside chroot

### ISSUE THREAD

**Issue by skwiffhub** [systemd/systemd#18051]
**systemd version the issue has been seen with**
 > ```
 > $ sudo systemctl --version
> systemd 246 (v246.7-2.fc33)
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
> ```

**Used distribution**
> ```
> $ sudo cat /etc/os-release | head -2
> NAME=Fedora
> VERSION="33.20201221.0 (Silverblue)"
> ```

**Linux kernel version used** (`uname -a`)
> ```
> $ sudo uname -a
> Linux xxx 5.9.14-200.fc33.x86_64 #1 SMP Fri Dec 11 14:30:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```

**CPU architecture issue was seen on**
> ```
> $ cat /proc/cpuinfo | head -5
> processor	: 0
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 63
> model name	: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
> ```

**Expected behaviour you didn't see**
 > When configuring a `RootDirectory` for the `Type=notify` service, I was expecting notifications and journal logging to work properly.

**Unexpected behaviour you saw**
 > The service just hangs when started via `systemctl start` (no shell prompt comes back). `systemd` never seems to receive the `READY` notification via `sd_notify()` and no journal logs appear.

**Steps to reproduce the problem**
 > Compile the following code (name the file `test_sd_wdog.c`):
```c
/*
 * Compile with:
 *   gcc -o test_sd_wdog test_sd_wdog.c -lsystemd
 */

#include <stdio.h>
#include <systemd/sd-daemon.h>
#include <systemd/sd-journal.h>
#include <inttypes.h>
#include <sys/types.h>
#include <unistd.h>

int main( int argc, char **argv )
{
    uint64_t watchdogNotifyIntervalUsec = 0;
    int watchdogEnabled = sd_watchdog_enabled(0, &watchdogNotifyIntervalUsec);

    sd_notifyf(0, "READY=1\n"
               "STATUS=Processing requests?\n"
               "MAINPID=%lu",
               (unsigned long) getpid());
    sd_journal_print( LOG_INFO, "READY sent from PID %lu", (unsigned long) getpid() );
    
    while ( 1 ) { 
        sd_notify( 0, "WATCHDOG=1" );
        sd_journal_print( LOG_INFO, "notified watchdog from PID %lu", (unsigned long) getpid() );
        sd_journal_send("MESSAGE=Test message: Warning...", "SD_JOURNAL_TEST=SEND", "PRIORITY=%i", LOG_WARNING, NULL);
        sleep( 3 );
    }
}
```
> Use the following `systemd` service file and copy `test_sd_wdog` to the chroot dir `/tmp/test_chroot` along with all necessary libraries (see below): 
```systemd
# /etc/systemd/system/testwd.service
[Unit]
Description=simple watchdog test

[Service]
Type=notify
NotifyAccess=all
StandardOutput=journal
TimeoutStartSec=300
RootDirectory=/tmp/test_chroot
RootDirectoryStartOnly=yes
ExecStart=/test_sd_wdog
Restart=on-failure
WatchdogSec=10s

[Install]
WantedBy=multi-user.target
```
> I tested this outside of a chroot jail and it worked fine. Watchdog gets properly reset and the journal logs appear.
>
> Here are the libs and binaries I copied into the chroot jail:
```sh
$ ls -R test_chroot/
test_chroot/:
bin  lib64  test_sd_wdog  usr

test_chroot/bin:
bash  ldd  ls

test_chroot/lib64:
ld-linux-x86-64.so.2  libattr.so.1  libbz2.so.1  libcap.so.2  libc.so.6  libdl.so.2  libdw.so.1  libelf.so.1  libgcc_s.so.1  libgcrypt.so.20  libgpg-error.so.0  liblz4.so.1  liblzma.so.5  libm.so.6  libpcre2-8.so.0  libpcre.so.1  libpthread.so.0  libresolv.so.2  librt.so.1  libselinux.so.1  libsystemd.so.0  libtinfo.so.6  libzstd.so.1

test_chroot/usr:
bin

test_chroot/usr/bin:
bash
```

**Comment by skwiffhub** [comment]
Seems like #3544 is similar and, based on the text in that issue, was never completely resolved. That issue also references #5446.

**Comment by skwiffhub** [comment]
Found what appears to be a work-around. Adding both `/var/run/systemd` and `/run/systemd` as `BindPaths` in the chroot seems to get `sd_notify()` going:

```
[Service]
...
BindPaths=/var/run/systemd
BindPaths=/run/systemd
...
```

**Comment by poettering** [comment]
In the portable service security logic we explicitly bind mount relevant sockets:

https://github.com/systemd/systemd/blob/master/src/portable/profile/default/service.conf

The question of course is whether we should maybe mount $NOTIFY_SOCKET implicitly in case RootDirectory=/RootImage= and NotifyAccess= are used in the same unit.

For the journal/logging case i don't think any automatism makes sense though, it's something we should document though.

**Comment by skwiffhub** [comment]
@poettering wrote:

> In the portable service security logic we explicitly bind mount relevant sockets:
> 
> https://github.com/systemd/systemd/blob/master/src/portable/profile/default/service.conf
> 
> The question of course is whether we should maybe mount $NOTIFY_SOCKET implicitly in case RootDirectory=/RootImage= and NotifyAccess= are used in the same unit.
> 
> For the journal/logging case i don't think any automatism makes sense though, it's something we should document though.

FWIW, I initially attempted bind mounting just `/var/run/systemd/notify` and that didn't help ... neither did `/var/run/systemd`. So, it seems like we need a larger complement of systemd sockets & resources to get the notifications and journaling to work.

**Comment by poettering** [comment]
`/var/run/` is a legacy alias for `/run/`. Nothing connects there. If you bind that then you basically tell systemd to create a dir inside the root namespace that nothing every connects to.

Seriously, forget about `/var/run/`, that's 10y out-of-date, everything is `/run` these days.

**Comment by skwiffhub** [comment]
Yes, `/var/run` is just a sym link to `/run`, which makes me now wonder why just `/var/run/systemd` didn't work in the first place. In any case, I'll just ignore `/var/run` and stick with the `/run` bind mount.

**Comment by skwiffhub** [comment]
> we'll follow symlinks when establishing these mounts, but my guess is that /var/run/ didn't exist in your root image, in which case we'll create it for you, but as a dir, not as a symlink, and then the bind will be established, but be useless, since at wrong place

Yes that's correct: `/var/run` was not defined as a symlink. Makes sense now.
