### ISSUE TITLE
Issues in udev man pages

### ISSUE THREAD

**Issue by hmartink** [systemd/systemd#18050]
Dear udev maintainer,
the manpage-l10n project maintains a large number of translations of
man pages both from a large variety of sources (including udev) as
well for a large variety of target languages.

During their work translators notice different possible issues in the
original (english) man pages. Sometimes this is a straightforward
typo, sometimes a hard to read sentence, sometimes this is a
convention not held up and sometimes we simply do not understand the
original.

We use several distributions as sources and update regularly (at
least every 2 month). This means we are fairly recent (some
distributions like archlinux also update frequently) but might miss
the latest upstream version once in a while, so the error might be
already fixed. We apologize and ask you to close the issue immediately
if this should be the case, but given the huge volume of projects and
the very limited number of volunteers we are not able to double check
each and every issue.

Secondly we translators see the manpages in the neutral po format,
i.e. converted and harmonized, but not the original source (be it man,
groff, xml or other). So we cannot provide a true patch (where
possible), but only an approximation which you need to convert into
your source format.

Finally the issues I'm reporting have accumulated over time and are
not always discovered by me, so sometimes my description of the
problem my be a bit limited - do not hesitate to ask so we can clarify
them.

I'm now reporting the errors for your project. If future reports
should use another channel, please let me know.

Man page: udev.7
Issue: character followed by a backslash → backslash followed by a character

"Values are written as double quoted strings, such as (\"string\")\\&. To "
"include a quotation mark (\") in the value, precede it by a backslash (\\e"
"\")\\&. Any other occurrences of a character followed by a backslash are not "
"further unescaped\\&. That is, \"\\et\\en\" is treated as four characters: "
"backslash, lowercase t, backslash, lowercase n\\&."
--
Man page: udev.7
Issue: a single list → share a common list?

"Specify a program to be executed after processing of all the rules for the "
"event\\&. With \"+=\", this invocation is added to the list, and with \"=\" "
"or \":=\", it replaces any previous contents of the list\\&. Please note "
"that both \"program\" and \"builtin\" types described below use a single "
"list, so clearing the list with \":=\" and \"=\" affects both types\\&."

**Comment by bluca** [comment]
Thanks for the report - any chance you could please send a PR with the fixes?

**Comment by hmartink** [comment]
Hello Bluca,
no, this is not possible. Manpages-l10n supports more than 100 upstreams and each and everyone is organized differently. Please also read my introductory text.

Thanks for taking care of udev.
