### ISSUE TITLE
ARP=False disables IPv6 Neighbor Discovery (networkd)

### ISSUE THREAD

**Issue by SRv6d** [systemd/systemd#18063]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 20.04.1 LTS

**Linux kernel version used** (`uname -a`)
 > 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > The `ARP` setting should only toggle ARP, not IPv6 NDP. Although both protocols have similar objectives they are inherently different. 

**Unexpected behaviour you saw**
 > IPv6 neighbor discovery is disabled when the `ARP=` [Link] section option is set to false. ARP and IPv6 NDP are inherently different.

**Steps to reproduce the problem**
 > Create a .network configuration with the following [Link] section:
```
[Link]
ARP=False
```

**Comment by yuwata** [comment]
Sorry for late response. 

> IPv6 neighbor discovery is disabled

Could you elaborate more? What command or property did you check?

**Comment by SRv6d** [comment]
> Sorry for late response.  

Likewise. 
I investigated a bit and it seems like networkd simply sets the `IFF_NOARP` interface flag and the Kernel doesn't properly differentiate between ARP and IPv6 Neighbor Discovery Protocol, even though they are entirely different, which means that this is a Linux and not a networkd issue.

**Comment by andrewbaxter** [comment]
Could this be documented? I just got bit by this, `ARP=no` is the last place I would have expected to find the issue.

The documentation fairly explicitly says this is ARP only right now and there's precedent to documenting interaction with the kernel in other options.

**Comment by yuwata** [comment]
-> #34221

**Comment by andrewbaxter** [comment]
Ah thanks! Sorry, I should have made a new issue.
