### ISSUE TITLE
udev: uaccess is set before ID_SMARTCARD_READER

### ISSUE THREAD

**Issue by vpelletier** [systemd/systemd#18079]
**Is your feature request related to a problem? Please describe.**

I have a usb smartcard reader which properly exposes the CCID standard class, but it is not getting the `uaccess` tag, preventing access from scdaemon, gnupg, etc.

udev ships with `70-uaccess.rules`, which adds the `uaccess` tag to deices which match `ENV{ID_SMARTCARD_READER}=="?*"`. It also ships with `99-systemd.rules`, which sets `ENV{ID_SMARTCARD_READER}="1"` to devices which match `ENV{ID_USB_INTERFACES}=="*:0b????:*"` (`0x0b` being the CCID standard class). But because 99 > 70, the `uaccess` tag is not set as `ID_SMARTCARD_READER` is not set yet at that point.

**Describe the solution you'd like**

On a high level, anything setting the `uaccess` tag based on interface would be fine.

On a low level, I guess the `ENV{ID_SMARTCARD_READER}="1"` rule will probably need to be moved from 99-systemd.rules to some less-than-70 rule. But I am not familiar at all with the rules on what levels are supposed to be used, and of the possible consequences on compatibility.

**Describe alternatives you've considered**

I have duplicated the rule from `99-systemd.rules` verbatim to a custom `/etc/udev/rules.d/60-CCID.rules` and it fixes the access for me:

```
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ENV{ID_USB_INTERFACES}=="*:0b????:*", ENV{ID_SMARTCARD_READER}="1"
```

But I believe more would benefit from an upstream fix.

Also reported as [Debian bug #978011](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978011).

**Comment by bluca** [comment]
> On a low level, I guess the ENV{ID_SMARTCARD_READER}="1" rule will probably need to be moved from 99-systemd.rules to some less-than-70 rule. But I am not familiar at all with the rules on what levels are supposed to be used, and of the possible consequences on compatibility.

This sounds fine, and if not people familiar with it will be more likely to comment on a PR. Could you please verify the fix works for you and open a PR?

**Comment by vpelletier** [comment]
@bluca Done: #18816 . Tested by commenting out my local fix & the line being deleted, copying the new rule file in /lib/udev/rules, plugging in a card reader and running `gpg --edit-card` from a regular user.
