### ISSUE TITLE
RFE: support for long unit names

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#18077]
**Is your feature request related to a problem? Please describe.**
systemd currently has a hard limit of 255 bytes for the length of a unit name.  This causes problems such as #17684.

**Describe the solution you'd like**
Longer unit names are supported.  This can be done by hashing them before converting them to a filename.

**Describe alternatives you've considered**
Long mount point paths could be handled differently.  For instance, they could be symlinked to somewhere under `/run`.

**Comment by poettering** [comment]
Unsetting milestone again. I think #17684 + #16161 should be enough to have on the milestone.
