### ISSUE TITLE
Looping over joysticks looking for joystick like properties should OR hint results together

### ISSUE THREAD

**Issue by rfechney** [systemd/systemd#18070]
I'm debugging some issues I'm having with a set of Thrustmaster Pendular rudders as an input device, and I was looking at how udev gets it's initial guess as to what an input is.  From what I can see here, we check for joystick like properties and we intend to set the flag has_joystick_axes_or_buttons to true if anything like that is found.  However, I am of the understanding that using = would always set the value to whatever was last tried, rather than using |= which would discover if any test is true.

The following lines are involved.

https://github.com/systemd/systemd/blob/227acf0009bde2cd7f8bc371615b05e84137847d/src/udev/udev-builtin-input_id.c#L214
https://github.com/systemd/systemd/blob/227acf0009bde2cd7f8bc371615b05e84137847d/src/udev/udev-builtin-input_id.c#L216
https://github.com/systemd/systemd/blob/227acf0009bde2cd7f8bc371615b05e84137847d/src/udev/udev-builtin-input_id.c#L218
https://github.com/systemd/systemd/blob/227acf0009bde2cd7f8bc371615b05e84137847d/src/udev/udev-builtin-input_id.c#L221

**Comment by andreaskem** [comment]
The lines you mention are preceded by loops containing the condition `!has_joystick_axes_or_buttons` so no other check should occur at all after the flag is set to true.

**Comment by rfechney** [comment]
Ah, you are correct.  This ticket can be closed.
