### ISSUE TITLE
Unit files under `/run` labeled incorrectly

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#18076]
**systemd version the issue has been seen with**
 > systemd 246

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > 5.4.83

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd creates unit files under `/run` with an appropriate SELinux context, such as `systemd_runtime_unit_file_t`.  That is what is specified by `/etc/selinux/targeted/contexts/systemd_contexts`.

**Unexpected behaviour you saw**
 > systemd transient unit files are created with context `user_tmp_t`, `init_var_run_t`, or other incorrect types.

**Steps to reproduce the problem**
 > run a session as a confined user (`staff_t`) and observe that D-Bus activation fails

**Comment by poettering** [comment]
For selinux fixes we rely on patch submission, as we do not have enough selinux expertise to implement these things on our own.

**Comment by DemiMarie** [comment]
The appropriate context can be obtained from `selinux_systemd_contexts_path`.  I will see if there are higher-level APIs to use.

Would it be possible for `systemd-tmpfiles` to create these directories?

**Comment by DemiMarie** [comment]
This can be fixed by using the `Z /run - - - -` in a `tmpfiles.d` entry.

**Comment by floppym** [comment]
Could you provide some examples of unit files (path + content) that get mislabeled? That should give a clue as to what part of the systemd code base is creating them.

**Comment by DemiMarie** [comment]
`/run/systemd/{generator.{early,late},transient}`

**Comment by floppym** [comment]
For the generator units, I guess you would probably want to hook into [generator_open_unit_file](https://github.com/systemd/systemd/blob/v247/src/shared/generator.c#L25).

For the transient units, probably [unit_make_transient](https://github.com/systemd/systemd/blob/v247/src/core/unit.c#L4928).

**Comment by floppym** [comment]
As for what to change, I guess you would want to call [label_fix](https://github.com/systemd/systemd/blob/v247/src/basic/label.h#L13).

**Comment by poettering** [comment]
tmpfiles.d/ is dispatched once, during late boot. The label should be applied for all transient units created the moment they are created, during early boot, and during rutime. Hence tmpfiles.d/ is not really an option.

**Comment by DemiMarie** [comment]
> As for what to change, I guess you would want to call [label_fix](https://github.com/systemd/systemd/blob/v247/src/basic/label.h#L13).

Should systemd do that for every file that it creates?

**Comment by DemiMarie** [comment]
Fixed in or before Fedora 35, closing.
