### ISSUE TITLE
RTC configured in localtime, but should treat RTC as UTC

### ISSUE THREAD

**Issue by cmurf** [systemd/systemd#18083]
**systemd version the issue has been seen with**
 > systemd-247.1-3.fc34.x86_64

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)
 > 5.10.0-0.rc6.20201204git34816d20f173.92.fc34.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 >           RTC in local TZ: no

**Unexpected behaviour you saw**
 >           RTC in local TZ: yes                        

**Steps to reproduce the problem**
 > Boot a USB stick made from Fedora-Workstation-Live-x86_64-Rawhide-20201215.n.0.iso, or Fedora-Workstation-Live-x86_64-Rawhide-20201225.n.0.iso

Problem doesn't happen with systemd-246.7-2.fc33.x86_64 when using the same kernel as the USB stick.  Two systems tested are EFI 1.10 (ancient EFI) and UEFI 2.40. The problem doesn't happen with the same kernel, but with 

CONFIG_RTC_HCTOSYS=y
CONFIG_RTC_HCTOSYS_DEVICE="rtc0"

kernel sets system clock to the corrent UTC time based on RTC
```
Dec 26 00:15:58 fedora kernel: PM: RTC time: 05:15:51, date: 2020-12-26
...
Dec 26 00:15:58 fedora kernel: rtc_cmos 00:03: setting system clock to 2020-12-26T05:15:57 UTC (1608959757)
```

Time as reported by journalctl is the correct local/EST time until journald restarts:
```
Dec 26 00:16:03 fedora systemd-journald[243]: Journal stopped
Dec 26 05:16:21 fedora kernel: kauditd_printk_skb: 51 callbacks suppressed
```

This is suspicious. I'm not sure why it thinks it's configured in localtime. This message only appears when booting systemd-247, it doesn't appear when booting systemd-246.
```
Dec 26 05:16:21 fedora systemd[1]: RTC configured in localtime, applying delta of -300 minutes to system time.
```

**Comment by cmurf** [comment]
This was the first indication of a problem.
```
# timedatectl
               Local time: Sat 2020-12-26 05:22:09 EST
           Universal time: Sat 2020-12-26 10:22:09 UTC
                 RTC time: Sat 2020-12-26 05:22:09    
                Time zone: US/Eastern (EST, -0500)    
System clock synchronized: no                         
              NTP service: active                     
          RTC in local TZ: yes                        

Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
[root@localhost-live chris]# 
```

This RTC time is the correct UTC time.

The system doesn't have internet access when booted from the USB stick. Whereas the systemd-246 systems do have internet access.

**Comment by cmurf** [comment]
Reproduces with qemu-kvm as well. With or without internet access; however with internet access...

```
$ timedatectl
               Local time: Sat 2020-12-26 02:03:36 EST
           Universal time: Sat 2020-12-26 07:03:36 UTC
                 RTC time: Sat 2020-12-26 07:03:36    
                Time zone: US/Eastern (EST, -0500)    
System clock synchronized: yes                        
              NTP service: active                     
          RTC in local TZ: yes                        

Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
```

What? UTC and RTC are the same, local time is different. So why does it claim RTC in local TZ = yes?

**Comment by cmurf** [comment]
OK this is not a new problem, I'm seeing it with Fedora-Workstation-Live-x86_64-33-1.2.iso which has systemd-246.6-3.fc33.x86_64. Seems to be unique to live boots? Weird.

**Comment by cmurf** [comment]
Looks like this is intentional. I found 7948c4dfbe and see that Live media have 
```
# cat /etc/adjtime 
0.0 0 0.0
0
LOCAL
```
That's probably what's resulting in the 'RTC configured in localtime' message. Maybe it's intended to be friendly for the Windows dual boot case, but it's kindof an odd duck in every other case.

**Comment by poettering** [comment]
systemd can't know whether the RTC is in local timezone or not, unless you tell it so. for a livecd it's probably wise to assume it's in local time, because Windows, so I think fedora is doing it right.

Hence, I don't think we can do anything about this, sorry. :-(
