### ISSUE TITLE
network.online not reliable

### ISSUE THREAD

**Issue by troelsarvin** [systemd/systemd#18086]
**systemd version the issue has been seen with**
246.7

**Used distribution**
Fedora 33

**Linux kernel version used** (`uname -a`)
5.9.15-200.fc33.x86_64

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
The samba service was expected to be running without special configuration steps (see workarounds below).

**Unexpected behaviour you saw**
The samba-service had failed starting. It seems to me it's because the samba unit waits for network-online.target, but network-online.target prematurely reports the network to be online.

**Steps to reproduce the problem**
I think the system has to be dual-stacked, i.e. have a configured IPv4 and IPv6 address.
Apart from that: Install Samba from Fedora 33, and set it to be enabled. After boot:

```$ systemctl status samba
● samba.service - Samba AD Daemon
     Loaded: loaded (/usr/lib/systemd/system/samba.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sat 2020-12-26 16:50:48 CET; 5min ago
...
```

I've found two work-arounds:

Adding a file like this e.g. as /etc/sysctl.d/99-nonlocal_bind.conf:
`net.ipv4.ip_nonlocal_bind = 1
net.ipv6.ip_nonlocal_bind = 1`

Or add a delay to the samba unit using `systemctl edit samba`:
`[Service]
ExecStartPre=/bin/sleep 30`

**Comment by troelsarvin** [comment]
[journalctl_nonworking_samba.txt](https://github.com/systemd/systemd/files/5743344/journalctl_nonworking_samba.txt)

[journalctl_nonworking_samba_debug.txt](https://github.com/systemd/systemd/files/5743345/journalctl_nonworking_samba_debug.txt)

[journalctl_working_samba.txt](https://github.com/systemd/systemd/files/5743346/journalctl_working_samba.txt)

[status-network-online.target.txt](https://github.com/systemd/systemd/files/5743349/status-network-online.target.txt)

[status-samba.service.txt](https://github.com/systemd/systemd/files/5743350/status-samba.service.txt)

[systemctl_cat_samba.txt](https://github.com/systemd/systemd/files/5743351/systemctl_cat_samba.txt)

**Comment by bluca** [comment]
network-online.target is only a synchronization point, the network manager of choice needs to implement the blocking functionality. What manager are you using? networkd? network-manager? What does this show:

```
systemctl list-dependencies --after network-online.target
```

**Comment by poettering** [comment]
network-online.target is a placeholder that your network management solution has to fill with logic to be useful. Hence if that doesn't work, please work with the folks maintaining your network management solution. I figure that's NetworkManager, given you are using fedora 33 and that comes with that, and you are not saying you switched away from the default. Hence, please work with the Fedora/NetworkManager communities on this, they'll help you.

**Comment by troelsarvin** [comment]
OK, reported to NetworkManager: [https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/617](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/617)
