### ISSUE TITLE
RFE: JSON output option for bootctl

### ISSUE THREAD

**Issue by Batcastle** [systemd/systemd#18094]
**Is your feature request related to a problem? Please describe.**
Currently, it takes seemingly unnecessary parsing to get the output of `bootctl list` in a machine-readable format.

**Describe the solution you'd like**
Having a JSON option, or proper YAML formatting (The current output is already very close to YAML formatting, but not close enough to be parse correctly.), would make it very easy for any third-party developer to use a standard lib to parse the output, in order to provide information to the user about their system, or inform a decision on what to do in a program.

**Describe alternatives you've considered**
Manually fixing the current output in each application is a viable option. If we go for YAML, we just need to change the number of leading spaces on each line so that each line's description lines up, instead of the value for each line lining up. Like so:

Instead of this:
```
Boot Loader Entries:
        title: Reboot Into Firmware Interface
           id: auto-reboot-to-firmware-setup
       source: /sys/firmware/efi/efivars/LoaderEntries-****
```
We would have this:
```yaml
Boot Loader Entries:
       title: "Reboot Into Firmware Interface"
       id: "auto-reboot-to-firmware-setup"
       source: "/sys/firmware/efi/efivars/LoaderEntries-****"
```
As you can see, the only real difference is line indentation. This, however, requires unnecessary preprocessing that can can be avoided by formatting the output as YAML in the first place.
<br/><br/>
YAML can be achieved without even adding a new flag, and it will maintain the same level of readability for users. JSON would likely require a new flag due to it's reduced readability for average users, despite being (arguably) easier to parse and generate. An example of the above `bootctl list` output, in JSON output:

```json
{
    "Boot Loader Entries": [
        {
            "title": "Reboot Into Firmware Interface",
            "id": "auto-reboot-to-firmware-setup",
            "source": "/sys/firmware/efi/efivars/LoaderEntries-****",
            "default": false
        }
    ]
}
```

Is something like this possible? Thanks!!!

**Comment by poettering** [comment]
yaml is such a broken language. json is fine though. we can add that.

**Comment by Batcastle** [comment]
I can get behind that. I preferred JSON anyways. I just looked mostly at YAML cause I figured it would be the least work to add with the current output format.

**Comment by Batcastle** [comment]
Hey. Just wondering where this feature is at? 

I understand it's probably low on the priority list. Just curious if it is already being worked on, just isn't committed yet, or if doing it myself (if I can figure it out XD) and making a PR would be a quicker way of getting it included in the next release.

Thanks!

**Comment by poettering** [comment]
Noone I am aware of is working on this. Happy to review/merge patches for that.

To generate JSON output we typically use the APIs from src/shared/json.h, or in case the stuff is in tabular format via the json output option of src/shared/format-table.h. There are plenty examples in the codebase for using either.
