### ISSUE TITLE
daemon-reexec coredump

### ISSUE THREAD

**Issue by gaoyi1988** [systemd/systemd#18099]
**systemd version the issue has been seen with**
 > 239

**Linux kernel version used** (`uname -a`)
 > 4.19

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > daemon-reexec success

**Unexpected behaviour you saw**
 > daemon-reexec dumped, and pid 1 is Freezing.

**Steps to reproduce the problem**
 I can't reproduce the problem. 
From the **core file**, I find the error is the follow:
The func **load_fragment_gperf_lookup** has a **static const** variable -- **wordlist**, and it's values are wrong. Like below: 
```
(gdb) x/20gx 0xaaaad4e5ac80
0xaaaad4e5ac80 <wordlist.19693+6112>:   0x0000aaaad4e05d68      0x0000aaaad4d6d4d8
0xaaaad4e5ac90 <wordlist.19693+6128>:   0x0000000000000000      0x0000000000000000
0xaaaad4e5aca0 <wordlist.19693+6144>:   0x0000000000000000      0x0000000000000000
0xaaaad4e5acb0 <wordlist.19693+6160>:   0x0000000000000000      0x0000000000000000
0xaaaad4e5acc0 <wordlist.19693+6176>:   0x0000000004f88131      0x0000000000000000
0xaaaad4e5acd0 <wordlist.19693+6192>:   0x226c1bf60beee7e2      0x0000000000000000
0xaaaad4e5ace0 <wordlist.19693+6208>:   0x0000aaaad4e05d80      0x0000aaaad4d78ce0
0xaaaad4e5acf0 <wordlist.19693+6224>:   0x0000000000000000      0x0000000000000000
0xaaaad4e5ad00 <wordlist.19693+6240>:   0x0000000049c6405b      0x263375c400000000
0xaaaad4e5ad10 <wordlist.19693+6256>:   0x000000002e040da8      0x0000000000000000
(gdb) p (char *)0x0000aaaad4e05d68
$4 = 0xaaaad4e05d68 "Unit.Description"
(gdb) p (void *)0x0000aaaad4d6d4d8
$5 = (void *) 0xaaaad4d6d4d8 <config_parse_unit_string_printf>
(gdb)
```
According to the code "{"Unit.Description",                config_parse_unit_string_printf,    0,                             offsetof(Unit, description)},", the correct value in addr 0xaaaad4e5ac98 is "232". So, when parsing the Description of a Unit，it will write the rvalue to u->manager, and causes the coredump.

From the log, before coredump, it executed Reloading two times, and executing "restart kdump.service" at that time.
```
Dec  5 15:55:29 localhost systemd[1]: Reloading.
Dec  5 15:55:30 localhost systemd[1]: Reloading.
Dec  5 15:55:30 localhost systemd[1]: Stopping Crash recovery kernel arming...
Dec  5 15:55:30 localhost kdumpctl[82125]: kexec: unloaded kdump kernel
Dec  5 15:55:30 localhost kdumpctl[82125]: Stopping kdump: [OK]
Dec  5 15:55:30 localhost systemd[1]: Stopped Crash recovery kernel arming.
Dec  5 15:55:30 localhost systemd[1]: Starting Crash recovery kernel arming...
Dec  5 15:55:31 localhost kdumpctl[82187]: Kbox memory 0x6f000000-0x1000000: [OK]
Dec  5 15:55:33 localhost kdumpctl[82187]: kexec: loaded kdump kernel
Dec  5 15:55:33 localhost kdumpctl[82187]: Starting kdump: [OK]
Dec  5 15:55:33 localhost systemd[1]: Started Crash recovery kernel arming.
Dec  5 15:55:33 localhost dbus-daemon[10785]: [system] Activating service name='org.fedoraproject.Setroubleshootd' requested by ':1.6' (uid=0 pid=10674 comm="/usr/sbin/sedispatch " label="system_u:system_r:auditd_t:s0") (using servicehelper)
Dec  5 15:55:34 localhost systemd[1]: Reexecuting.
Dec  5 15:55:34 localhost kernel: [81843.801608] systemd: 31 output lines suppressed due to ratelimiting
Dec  5 15:55:34 localhost systemd[1]: [81843.825722] systemd 239 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Dec  5 15:55:34 localhost systemd[1]: [81843.826919] Detected architecture arm64.
Dec  5 15:55:34 localhost dbus-daemon[10785]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Dec  5 15:55:34 localhost systemd[1]: [81844.087996] Caught <SEGV>, dumped core as pid 86546.
Dec  5 15:55:34 localhost systemd[1]: [81844.088156] Freezing execution.
```
I find the PR https://github.com/systemd/systemd/pull/11121, is the problem related to is?

**Comment by gaoyi1988** [comment]
(gdb) bt
#0  0x0000ffffa40d0508 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x0000aaaad4d4758c in crash (sig=11) at ../src/core/main.c:184
#2  <signal handler called>
#3  hash_key (h=<optimized out>) at ../src/basic/hashmap.c:330
#4  base_bucket_hash (h=h@entry=0x7661532f64616f4c, p=p@entry=0xaaaae902f660) at ../src/basic/hashmap.c:338
#5  0x0000ffffa450d3fc in internal_hashmap_get (h=0x7661532f64616f4c, key=0xaaaae902f660) at ../src/basic/hashmap.c:1339
#6  0x0000aaaad4d826b4 in manager_load_unit_prepare (m=m@entry=0xaaaae9076b20, name=0xaaaae902f660 "sys-devices-virtual-misc-rfkill.device", path=path@entry=0x0, e=e@entry=0x0,
    _ret=_ret@entry=0xfffff5096960) at ../src/core/manager.c:1883
#7  0x0000aaaad4d82838 in manager_load_unit (m=0xaaaae9076b20, name=<optimized out>, path=path@entry=0x0, e=e@entry=0x0, _ret=0xfffff5096960, _ret@entry=0xfffff50969a0) at ../src/core/manager.c:1928
#8  0x0000aaaad4dad714 in unit_add_dependency_by_name (u=u@entry=0xaaaae9089910, d=d@entry=UNIT_REQUIRES, name=<optimized out>, path=path@entry=0x0, add_reference=add_reference@entry=true,
    mask=mask@entry=UNIT_DEPENDENCY_FILE) at ../src/core/unit.c:2933
#9  0x0000aaaad4d6d0e4 in config_parse_unit_deps (unit=0xaaaae9006bd0 "\210$\255", <incomplete sequence \373\252\252>, filename=0xaaaae90482b0 "/usr/lib/systemd/system/systemd-rfkill.socket",
    line=0, section=<optimized out>, section_line=<optimized out>, lvalue=<optimized out>, ltype=0, rvalue=0xaaaae9083678 "sys-devices-virtual-misc-rfkill.device", data=<optimized out>,
    userdata=<optimized out>) at ../src/core/load-fragment.c:140
#10 0x0000ffffa44b3430 in next_assignment (userdata=0xaaaae9089910, flags=CONFIG_PARSE_ALLOW_INCLUDE, rvalue=0xaaaae904f7a0 "systemd-rfkill.socket", lvalue=0xaaaae9083670 "BindsTo", section_line=10,
    section=0xaaaae9024cb0 "Unit", table=0xaaaad4e8d000 <kill@got.plt>, lookup=0xffffa44b28b0 <config_item_perf_lookup>, line=14,
    filename=0xaaaae90482b0 "/usr/lib/systemd/system/systemd-rfkill.socket", unit=0xaaaae904f7a0 "systemd-rfkill.socket") at ../src/shared/conf-parser.c:138
#11 parse_line (unit=0xaaaae904f7a0 "systemd-rfkill.socket", unit@entry=0x8 <error: Cannot access memory at address 0x8>,
    filename=filename@entry=0xaaaae90482b0 "/usr/lib/systemd/system/systemd-rfkill.socket", line=line@entry=14, sections=sections@entry=0x1 <error: Cannot access memory at address 0x1>,
    lookup=lookup@entry=0xffffa44b28b0 <config_item_perf_lookup>, table=0xaaaad4e8d000 <kill@got.plt>, table@entry=0x2, flags=flags@entry=CONFIG_PARSE_ALLOW_INCLUDE,
    section=section@entry=0xaaaad4e8d000 <kill@got.plt>, section_line=<optimized out>, section_line@entry=0xfffff5096c6c, section_ignored=0xfffff5096bcb, section_ignored@entry=0xaaaae9089910,
    l=<optimized out>, userdata=0xaaaae9089910, userdata@entry=0xaaaad4e8d000 <kill@got.plt>) at ../src/shared/conf-parser.c:263
#12 0x0000ffffa44b2c50 in config_parse (unit=0x8 <error: Cannot access memory at address 0x8>, filename=0xaaaae90482b0 "/usr/lib/systemd/system/systemd-rfkill.socket", f=0xaaaae9006bd0,
    sections=0x1 <error: Cannot access memory at address 0x1>, lookup=0xffffa44b28b0 <config_item_perf_lookup>, table=0x2, flags=flags@entry=CONFIG_PARSE_ALLOW_INCLUDE,
    userdata=0xaaaad4e8d000 <kill@got.plt>, userdata@entry=0xaaaae9089910) at ../src/shared/conf-parser.c:380
#13 0x0000aaaad4d75650 in load_from_path (u=u@entry=0xaaaae9089910, path=0xaaaae904f7a0 "systemd-rfkill.socket") at ../src/core/load-fragment.c:4466
#14 0x0000aaaad4d7bab8 in unit_load_fragment (u=u@entry=0xaaaae9089910) at ../src/core/load-fragment.c:4503
#15 0x0000aaaad4dac188 in unit_load_fragment_and_dropin (u=u@entry=0xaaaae9089910) at ../src/core/unit.c:1291
#16 0x0000aaaad4da03fc in socket_load (u=0xaaaae9089910) at ../src/core/socket.c:524
#17 0x0000aaaad4dada4c in unit_load (u=0xaaaae9089910) at ../src/core/unit.c:1481
#18 0x0000aaaad4d82238 in manager_dispatch_load_queue (m=0xaaaae8fff310) at ../src/core/manager.c:1836
#19 0x0000aaaad4d82848 in manager_load_unit (m=0xaaaae8fff310, name=<optimized out>, path=path@entry=0x0, e=e@entry=0x0, _ret=0xfffff5097020, _ret@entry=0xfffff5097060) at ../src/core/manager.c:1932
#20 0x0000aaaad4dad714 in unit_add_dependency_by_name (u=u@entry=0xaaaae90894d0, d=d@entry=UNIT_WANTS, name=<optimized out>, path=path@entry=0x0, add_reference=add_reference@entry=true,
    mask=mask@entry=UNIT_DEPENDENCY_UDEV) at ../src/core/unit.c:2933
#21 0x0000aaaad4dd5d64 in device_add_udev_wants (dev=0xaaaae9020310, u=0xaaaae90894d0) at ../src/core/device.c:390
#22 device_setup_unit (m=m@entry=0xaaaae8fff310, dev=dev@entry=0xaaaae9020310, path=path@entry=0xaaaae9071850 "/sys/devices/virtual/misc/rfkill", main=main@entry=true) at ../src/core/device.c:541
#23 0x0000aaaad4dd6610 in device_process_new (m=m@entry=0xaaaae8fff310, dev=dev@entry=0xaaaae9020310) at ../src/core/device.c:574
#24 0x0000aaaad4dd7e20 in device_enumerate (m=0xaaaae8fff310) at ../src/core/device.c:878
#25 0x0000aaaad4d824c4 in manager_enumerate (m=0xaaaae8fff310) at ../src/core/manager.c:1352
#26 0x0000aaaad4d87a30 in manager_startup (m=0xaaaae8fff310, serialization=0xaaaae8eff350, fds=0xaaaae8ffd158) at ../src/core/manager.c:1579
#27 0x0000aaaad4d4305c in main (argc=4, argv=0xfffff50976b8) at ../src/core/main.c:2408

**Comment by bluca** [comment]
v239 is really old. Can you reproduce the problem with a recent release?

**Comment by gaoyi1988** [comment]
My distribution is fedora 29. But now I can't reproduce the problem whether in v239 or in v246.

**Comment by bluca** [comment]
Fedora 29 was EOL more than a year ago. If the issue can't be reproduced on a supported distro, with a more recent version, I'm afraid there's little we can do, sorry.
You might want to attach the coredump file, for future reference, just in case.

**Comment by poettering** [comment]
Let's close this, 239 is just too old. To keep frustration low the submission form tries to make very clear, that we only cover issues in the two most recent *upstream* versions here. For everything else, contact your downstream distros. Closing.
