### ISSUE TITLE
systemctl show-environment should not show environment variables of root when run by a non-root user

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#18098]
**systemd version the issue has been seen with**

`241`

**Used distribution**

Debian `buster`

**Linux kernel version used** (`uname -a`)

**CPU architecture issue was seen on**

**Expected behaviour you didn't see**

`systemctl show-environment` should not show environment variables of `root` when run by a non-root user.

**Unexpected behaviour you saw**

`systemctl show-environment` shows environment variables of root when run by a non-root user.

Running `systemctl show-environment` should require root/sudo.

Environment variables set for `root` are none of the business of non-root users. Although (probably) bad practice, environment variables might contain sensitive information such as passwords or other information leaks useful for a non-root attacker attempting to compromise root.

This may be more so the case when using `systemctl import-environment`.

**Steps to reproduce the problem**

Run `systemctl show-environment` as user.

**Comment by poettering** [comment]
I am not sure what you mean by "environment variables of root"?

"systemctl show-environment" shows the default env block passed to system services.

"systemctl show-environment --user" shows the default env block passed to user services, when run under the respective user. If the user is "root", will show the environment passed to the root user's per-user services.

System service parameters, including the default env block are publically accessible info. This is explicitly documented btw, see the Environment= docs.

It requires manual, systemd-specific work to upload env vars into systemd's default env block. People shouldn't place secret info there. There are better approaches available, for example the credentials subsystem. Given this is all documented explicitly, and the concept was introduced by us (there was simply no default env block that is passed to all system services in sysvinit times) and never changed I don't think we need to change anything here.
