### ISSUE TITLE
Update the [Install] section when daemon-reload.

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#18096]
**Is your feature request related to a problem? Please describe.**
1. create `test.service`, and enable it `systemctl enable test`.
```shell
[Unit]
Description=TEST

[Service]
ExecStart=/usr/bin/true
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
```
2. copy `test.service` to `test1.service`, add `Also=test1.service` in `test.service`, do not `systemctl enable test.service` to leave `test1.service` disabled.
3. `systemctl daemon-reload`; `systemctl status test1`

**Describe the solution you'd like**
As `test.service` is enabled, the `test1.service` should also be enabled.

**Describe alternatives you've considered**
`test1.service` is disabled.

**Comment by keszybz** [comment]
This is a misunderstanding of what [Install] is for. The manager does not load or use the [Install] section in normal operation, so any information present in [Install] is irrelevant to daemon-reload. The [Install] section is read at the moment when systemctl enable is called. You can update the state to match the new contents of [Install] by calling `systemctl reenable`.
