### ISSUE TITLE
Systemd inside docker running forking services : Refusing to accept PID 

### ISSUE THREAD

**Issue by junaid-ebrahim** [systemd/systemd#18091]
I'm using 
	Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
	systemd 239 (239-41.el8_3)

Basically I am trying to run certain forking services in docker that run fine on native linux, however on docker they fail with  
"Refusing to accept PID outside of service control group, acquired through unsafe symlink chain: /run/<piddirectory>/<pidfile>"

I am using the oci-systemd-hook to ensure all cgroups dirs are mounted correctly. And they all look to be correct, container is also run as privileged

I am also running a non-docker (native centos 8) version of systemd to compare the issue to confirm that it is docker related(and not dac permission related). 
The  forking services work fine in native linux and I confirmed that their configs are identical. Both native and docker machines are running systemd version - systemd 239 (239-41.el8_3)

Docker daemon on host is running with "exec-opts": ["native.cgroupdriver=systemd"] (Not sure if this helps)

(WORKING NATIVE INVESTIGATION)
Chronyd is one of the services I have problems with , it works on the native centos 8 , and here are my investigations on the "working native machine"

		When getting the service unit info using : 
		cat /proc/(chronyd pid)/cgroup 

		I get the following (partial extract of output)
		1:name=systemd:/system.slice/chronyd.service

		systemctl status chronyd (partial extract of output below)
		CGroup: /system.slice/chronyd.service
		
		So I assume that this works because systemd would see that this is in the same control group

(BROKEN DOCKER INVESTIGATION)
On docker I cannot run the service because I get the error 
		chronyd.service: Refusing to accept PID outside of service control group, acquired through unsafe symlink chain: /run/chrony/chronyd.pid
		The pid file is not a sym link but the /run/chrony/ directory and chronyd.pid are owned by the non privileged user chrony (dac permissions are exactly as working native linux above )
		To work around the issue  I simply set the /run/chrony directory  and chrony.pid file owner to root. When this service runs I see the following 

		cat /proc/(chronyd pid)/cgroup (partial extract of output below)
		1:name=systemd:/system.slice/docker-e1ef2ab2e21f3ae5dc7297d07485b79201af37aed2afcf571f578a19040e1413.scope/system.slice/docker-e1ef2ab2e21f3ae5dc7297d07485b79201af37aed2afcf571f578a19040e1413.scope/system.slice/chronyd.service

		systemctl status chronyd  (partial extract of output below)

		CGroup: /system.slice/docker-e1ef2ab2e21f3ae5dc7297d07485b79201af37aed2afcf571f578a19040e1413.scope/system.slice/chronyd.service
		
Could the issue of systemd seeing the PID outside of service control group be due to the fact that the /proc/(chronyd pid)/cgroup file shows a duplicate system.slice text ?
NB: I'm not saying that this is a systemd issue, I don't know enough of systemd or linux to say that it is , I just thought that it might be, or systemd could be maybe output more detail e.g. the control group name

**Comment by poettering** [comment]
I don't know docker, but the cgroup hierarchy you have set up there is totally wrong. Please work with Docker to follow the basic rules for cooperation in the cgroup hierarchy (i.e. the delegation mode), as documented in all detail here:

https://systemd.io/CGROUP_DELEGATION

This is not crazy stuff the systemd people came up with, but how the kernel cgroups maintainer has designed this stuff.

For further details how container managers need to set up stuff for systemd to just work:

https://systemd.io/CONTAINER_INTERFACE

To my knowledge other container managers with less hostile upstreams all follow these rules. Maybe switch to podman or so?

Anyway, we cannot fix docker. Hence closing.

Closing.
