### ISSUE TITLE
sd-bus should prefer DBUS_{SYSTEM,SESSION}_BUS_ADDRESS

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1810]
These variables are supposed to be authoritative. sd-bus should attempt the addresses contained within before falling back to the default system or user bus.

**Comment by poettering** [comment]
Hmm, but that's precisely what we do?

https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/sd-bus.c#L1247
https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/sd-bus.c#L1201

We always honour those env vars first, before looking for something else. Are you saying this does not work for you?

**Comment by heftig** [comment]
Hm, you're right. I could have sworn I saw some code that preferred at least the kernel bus before checking the environment.
