### ISSUE TITLE
Mounting the delegated payload cgroup subtree as default in nspawn container

### ISSUE THREAD

**Issue by zepag** [systemd/systemd#18104]
**Is your feature request related to a problem? Please describe.**
When trying to use something that fiddles with cgroups inside of an nspawn container, there are often shortcomings due to the (otherwise acceptably false) assumption that the target software (e.g. Docker, Kubernetes, runc, podman, buildah ...) can write in e.g. the system.slice directly, or at least in a dedicated slice at the root of the cgroup hierarchy.
In an nspawn container, the delegated hierarchy where everything should/must/can be written is under: `/sys/fs/cgroup/machine.slice/machine-<containerid>.scope/payload/ ` which makes perfect sense and goes in the direction of better isolation.
Though sadly seldom are the software taking that into account or make it discoverable or even possible to parameterize, which makes running them in nspawn a pain, or just having to wait for many software to work around their shortcomings for a use-case that is (sadly) not really in their target... :p

**Describe the solution you'd like**
I'm probably missing the reason why it's necessary, though why is the full cgroup hierarchy visible to the container?
It would be a lot more transparent and backward-compatible if there was a way for the `/sys/fs/cgroup/machine.slice/machine-<containerid>.scope/payload/` from the host hierarchy to be visible as `/sys/fs/cgroup/` in the nspawn container.
This would allow for a transparent behaviour of software inside the container, regardless of whether they do things properly or not, or where coded with the systemd/nspawn scenario in mind, as long as they only write and can only write to their own dedicated sub-tree of the cgroup hierarchy.

**Describe alternatives you've considered**
Having all the other software fixed for the shortcomings... quite unlikely.

**Comment by bluca** [comment]
IIRC things might break badly if /sys/fs/cgroup does not match /proc/self/cgroup. Have you tried the setup you suggested?

**Comment by zepag** [comment]
Not really, I'm trying to understand the exact limitations and whereabouts.
I wouldn't know how to force that though. Any lead on a way to test such a setup?

**Comment by zepag** [comment]
Though I see what you imply @bluca : you in fact gave the resolution to my "I'm probably missing the reason why it's necessary" ;) 

It's because the /proc/self/cgroup has to match /sys/fs/cgroup.
Therefore (complete newbie question on the topic) couldn't both be remapped to the delegated ../payload/ subtree in a nspawn container?

**Comment by zepag** [comment]
The user experience can be weird though (and therefore inconsistent).

systemd-cgls will in fact only show you the subtree of the current Control group, though the whole tree is accessible in read-only mode.

It looks like a sandbox, though does permeate information about the host and any other nspawn containers in /sys/fs/cgroup.

Or am I missing anything?

**Comment by zepag** [comment]
Maybe this is related to my specific setup (though I've tested multiple variants to no avail yet) but everytime it seems the whole tree is visible.

I had the feeling that the CLONE_NEWCGROUP clone flag for clone() and unshare() where destined to achieve that.
Is there a specific reason why systemd-nspawn is (apparently) not doing that?

**Comment by zepag** [comment]
Well in fact... self-closing this issue.
Apparently after many fiddlings on my side, I had SYSTEMD_NSPAWN_USE_CGNS=0 set...
🤦 
@bluca sorry for bothering.
