### ISSUE TITLE
journald not strictly respecting SystemMaxUse=100M

### ISSUE THREAD

**Issue by rckoepke** [systemd/systemd#18103]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > AWS EC2 Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-0a91cd140a1fc148a (64-bit x86)

**Linux kernel version used** (`uname -a`)
 > Linux ip-172-31-39-196 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > 64-bit x86

**Expected behaviour you didn't see**
 > Expected journald to respect `SystemMaxUse=100M`
 ```sh
 sudo journalctl --disk-usage
 ```
Result: ```Archived and active journals take up 100.0M in the file system.```

**Unexpected behaviour you saw**
 >
 ```sh
 sudo journalctl --disk-usage
 ```
Result: ```Archived and active journals take up 130.4M in the file system.```

**Steps to reproduce the problem**
 > Start with fresh AWS EC2 Ubuntu Install:
```sh
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=100M/g' /etc/systemd/journald.conf 
sudo sed -i 's/#SystemMaxFileSize=/SystemMaxFileSize=100M/g' /etc/systemd/journald.conf
sudo sed -i 's/#SplitMode=uid/SplitMode=none/g' /etc/systemd/journald.conf
sudo rm -rf /var/log/journal
sudo mkdir /var/log/journal
sudo systemctl restart systemd-journald.service
systemd-cat head -c 10G /dev/urandom 
systemd-cat head -c 50G /dev/urandom 
***Repeat previous two commands with varying sizes (100M, 5G, 600M...) between 3-30 times**
sudo journalctl --disk-usage
```

**Comment by bluca** [comment]
This is explained in the manpage:

> Also note that only archived files are deleted to reduce the space occupied by journal files. This means that, in effect, there might still be more space used than SystemMaxUse= or RuntimeMaxUse= limit after a vacuuming operation is complete.

https://www.freedesktop.org/software/systemd/man/journald.conf.html#SystemMaxUse=

You can reduce the size of individual journal files to decrease the delta, at the cost of more processing.

**Comment by poettering** [comment]
Yupp, let's close this. This is documented, and I see no nice way to address it beyond that that wouldn#t come with major shortcomings.
