### ISSUE TITLE
System unbootable with btrfs compression level in fstab

### ISSUE THREAD

**Issue by 9ary** [systemd/systemd#18114]
**systemd version the issue has been seen with**
 247.2

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)
 5.9.14-arch1-1

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
 System boots and mount options are set correctly.

**Unexpected behaviour you saw**
Much of my system breaks as soon as I write the problematic change to fstab, and doesn't boot after a reset.

**Steps to reproduce the problem**
Have a btrfs entry in fstab (mounted on /), my mount options are `rw,noatime,ssd_spread,space_cache,compress-force=zstd:2`. `rw,noatime,ssd_spread,space_cache,compress-force=zstd` works as expected, setting the compression level through rootflags on the kernel command line also works just fine. The mount command also has no problem with these options on a booted system. I haven't tried this on a filesystem that isn't / yet.

A user in #btrfs on freenode couldn't reproduce this problem (but they didn't try it for /), so it might be a regression?
> `<Zygo> my systemd 241 test VM isn't doing anything like this on 5.10`

I'll be able to do more testing on another system tomorrow.

**Comment by bluca** [comment]
What's the content of the generated mount unit? -.mount in /run/systemd

**Comment by 9ary** [comment]
`/run/systemd/generator/-.mount` exists on a working system but there's pretty much nothing in /run/systemd after the breakage happens. I'll try again later.

**Comment by bluca** [comment]
you can do a daemon-reload on a working system after editing fstab, you'll see it immediately

**Comment by 9ary** [comment]
Yeah, as I wrote in the first post, my system enters a very broken state as soon as I save fstab with my changes, and pretty much everything is gone from /run/system (except ask-password I think).

**Comment by bluca** [comment]
Mmmh seems to work fine in a Debian unstable image running in qemu

```
root@localhost:~# mount | grep btrfs
/dev/vda2 on / type btrfs (rw,noatime,compress-force=zstd:2,ssd_spread,space_cache,subvolid=5,subvol=/)
```

**Comment by 9ary** [comment]
This is really strange, I can't reproduce on my desktop either, which is running the same software.

**Comment by 9ary** [comment]
So in the end it turned out that I had installed a script to manage NFS mounts and completely forgot about it. Since I had no use for it anyway, I've removed the script and my laptop no longer has problems with this. I'm not sure what the script actually did, but I suppose the colon threw it off.
