### ISSUE TITLE
logind: nonfunctional input after launching graphical environment after commit 643bb9240

### ISSUE THREAD

**Issue by ajakk** [systemd/systemd#18119]
**systemd version the issue has been seen with**

Any time after commit 643bb9240832c238a28cb36efc9d1a6c8d7e6ea0.

```systemd $ git tag --contains 643bb9240832c238a28cb36efc9d1a6c8d7e6ea0
v247
v247-rc1
v247-rc2
```

**Used distribution**

Gentoo

**Linux kernel version used** (`uname -a`)

Experienced on 5.4, 5.9, and 5.10.

**CPU architecture issue was seen on**

amd64

**Expected behaviour you didn't see**

Functional keyboard and mouse

**Unexpected behaviour you saw**

Nonfunctional keyboard and mouse

**Steps to reproduce the problem**

Launching any graphical environment (tested Sway and i3) results in my keyboard and mouse not working. Patching systemd with a revert commit of 643bb9240832c238a28cb36efc9d1a6c8d7e6ea0 fixes my issue.

**Comment by bluca** [comment]
Sounds like some problems in the udev rules - can you provide the relevant ones that you have on your system?

**Comment by ajakk** [comment]
Unfortunately I can't say I know what I'm looking for here, but I can say I've not modified the default rules installed by various packages on Gentoo and that all of the files in `/lib/udev/rules.d` are owned by an installed package.

```
/lib/udev/rules.d $ grep -Eil '(input|keyboard|mouse)' *.rules
50-udev-default.rules
60-evdev.rules
60-game-input.rules
60-input-id.rules
60-persistent-input.rules
60-sensor.rules
70-joystick.rules
70-mouse.rules
70-power-switch.rules
70-touchpad.rules
70-uaccess.rules
71-seat.rules
77-mm-usb-device-blacklist.rules
80-libinput-device-groups.rules
80-stelladaptor-joystick.rules
90-libinput-fuzz-override.rules
95-upower-csr.rules
97-hid2hci.rules
99-ckb-next-daemon.rules
99-systemd.rules
```

And then here's the content of those in a Gist: https://gist.github.com/ajakk/00217f315f1c0e1b86a8644d3b96746b

**Comment by poettering** [comment]
If you remove that "ckb-next" thing, do things work then?

**Comment by ajakk** [comment]
Removing that package appears to have fixed it, thank you!

**Comment by bluca** [comment]
@ajakk please report the issue to your distribution, as these rules probably need an update (see changelog for v247)
