### ISSUE TITLE
network: RoutingPolicyRule does not accept Table=main

### ISSUE THREAD

**Issue by sbraz** [systemd/systemd#18121]
Hi,
I noticed that `Table=main` does not work in routing policies although the manual mentions it. It would be great if this could be fixed.

A nice improvement (separate issue needed?) would be to accept the names of non-reserved tables.

**systemd version the issue has been seen with**
247

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
`5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
amd64

**Expected behaviour you didn't see**
`systemd.network`'s manual mentions that the `Table` option accepts values such as `main`:
> Takes one of "default", "main", and "local", or a number between 1 and 4294967295.

**Unexpected behaviour you saw**
However, when I use `main` or `default`, I see the following error: `Failed to parse RPDB rule table, ignoring: main`.

**Steps to reproduce the problem**
* Create a `.network` file with a policy rule that contains `Table=main` or `Table=default`
```ini
[RoutingPolicyRule]
FirewallMark=100
Table=main
```
* Run `networkctl reload`

**Comment by bluca** [comment]
That was never supported, I think 41b90a1eb5cb87beab4603b52adbce36b723a6d6 updated the wrong Table section of the manpage (it implemented it for the Route section but updated the RoutingPolicyRule section). That said, should be trivial to add and would make sense to be consistent.

**Comment by sbraz** [comment]
Hi @bluca, thanks for the explanation. And what about non-reserved table names? Would it be difficult to support them?

**Comment by bluca** [comment]
Yeah that would require more changes, as those are just shortcuts
