### ISSUE TITLE
RFE: allow multiple args to udevadm info

### ISSUE THREAD

**Issue by vinc17fr** [systemd/systemd#1813]
/lib/udev/hwdb.d/60-keyboard.hwdb (version 227) contains:

```
# If your changes are generally applicable, preferably send them as a pull
# request to
#   https://github.com/systemd/systemd
# or create a bug report on https://github.com/systemd/systemd/issues and
# include your new rules, a description of the device, and the output of
#   udevadm info /dev/input/eventXX
# (or /dev/input/event*).
```

But `udevadm info` takes only one file argument, so that `/dev/input/event*` is incorrect.

**Comment by mbiebl** [comment]
@keszybz do you want to keep this bug report open to implement the functionality as you suggested in #2222 or should we close it? If the former, we should retitle the bug an probably label it RFE

**Comment by vinc17fr** [comment]
In any case, the wildcard is handled by the shell to give multiple arguments, so that the command never sees a "wildcard argument".

**Comment by vinc17fr** [comment]
In any case, the wildcard is handled by the shell to give multiple arguments, so that the command never sees a "wildcard argument".
