### ISSUE TITLE
'systemctl is-enabled' returns incorrect exit code for 'alias' output

### ISSUE THREAD

**Issue by SunilMohanAdapa** [systemd/systemd#18134]
**systemd version the issue has been seen with**
 > 247
 > systemd 247 (247.1-3+deb11u1)
 > +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian Testing (Bullseye)

**Linux kernel version used** (`uname -a`)
 > Linux mybox 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The [documentation](https://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20UNIT%E2%80%A6) claims that when 'systemctl is-enabled' is run on an alias (in my case created with Alias= in [Install] section), then exit code of the command will be '0'.

**Unexpected behaviour you saw**
 >Exit code is '1'.

**Steps to reproduce the problem**
 > In Debian Testing
 > \# apt install bind9
 > \# cat /lib/systemd/system/named.service
 > ...
 > [Install]
 > WantedBy=multi-user.target
 > Alias=bind9.service
 > \# systemctl enable named.service
 > Synchronizing state of named.service with SysV service script with /lib/systemd/systemd-sysv-install.
 > Executing: /lib/systemd/systemd-sysv-install enable named
 > Created symlink /etc/systemd/system/bind9.service → /lib/systemd/system/named.service.
 > Created symlink /etc/systemd/system/multi-user.target.wants/named.service → /lib/systemd/system/named.service.
 > \# systemctl is-enabled named.service ; echo $?
 > enabled
 > 0
 > \# systemctl is-enabled bind9.service ; echo $?
 > alias
 > 1

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/15692 introduced the check for "alias" to return true in systemctl, but only in "local" mode (eg, offline, on a separate root, etc). Likely not intentional, will fix it.

```
$ SYSTEMCTL_INSTALL_CLIENT_SIDE=1 systemctl is-enabled test2.service; echo $?
alias
0
```
