### ISSUE TITLE
pam_systemd(sshd:session): Failed to create session: Connection timed out

### ISSUE THREAD

**Issue by Jsfastsa** [systemd/systemd#18143]
**systemd version the issue has been seen with**
 > …systemd 246

**Used distribution**
 > …fedora

**Linux kernel version used** (`uname -a`)
 > …

**CPU architecture issue was seen on**
 > …x86

**Expected behaviour you didn't see**
 > … login without timeout

**Unexpected behaviour you saw**
 > …login timeout for two minutes for user test.
https://github.com/systemd/systemd/pull/14077/commits/13f691ea09dfc891f03068abc51afa580f91296d
You may get timeout in /var/log/secure or journal

Jan  5 20:20:42 localhost systemd[484762]: pam_unix(systemd-user:session): session opened for user test by (uid=0)
Jan  5 20:20:42 localhost systemd[484790]: pam_unix(systemd-user:session): session closed for user test
Jan  5 20:22:41 localhost sshd[484239]: pam_systemd(sshd:session): Failed to create session: Connection timed out
Jan  5 20:22:41 localhost sshd[484239]: pam_unix(sshd:session): session opened for user test by (uid=0)
Jan  5 20:22:58 localhost sshd[484239]: pam_unix(sshd:session): session closed for user test
Jan  5 20:23:05 localhost systemd[498543]: pam_unix(systemd-user:session): session opened for user test by (uid=0)
Jan  5 20:23:05 localhost sshd[498117]: pam_unix(sshd:session): session opened for user test by (uid=0)
Jan  5 20:23:07 localhost sshd[498117]: pam_unix(sshd:session): session closed for user test
Jan  5 20:23:12 localhost systemd[499208]: pam_unix(systemd-user:session): session opened for user test by (uid=0)
Jan  5 20:23:12 localhost systemd[499231]: pam_unix(systemd-user:session): session closed for user test
Jan  5 20:25:12 localhost sshd[498944]: pam_systemd(sshd:session): Failed to create session: Connection timed out
Jan  5 20:25:12 localhost sshd[498944]: pam_unix(sshd:session): session opened for user test by (uid=0)
Jan  5 20:25:51 localhost sshd[498944]: pam_unix(sshd:session): session closed for user test

**Steps to reproduce the problem**
 > …
This is related to the high frequency of command "systemctl daemon-reload".
[root@localhost ~]# cat test.sh
```
#!/bin/bash
while true
do
#    start/revise/stop service
      systemctl daemon-reload
done
```

1、sh test.sh &
2、ssh test@ip
3、login may occasionally time out.

**Comment by boucman** [comment]
why do you loop-reload systemd ??? that can't be good...

**Comment by jackma-sudo** [comment]
> why do you loop-reload systemd ??? that can't be good...

Maybe you're right, daemon-reload probably shouldn't be executed so frequently. But there's no manual that says I shouldn't do this. And this is only a reproducing step to this occasional problem . The actual use is not in a loop, but there are a large number of ”daemon-reload“.

**Comment by boucman** [comment]
Ok, maybe this should work, it's hard to tell out o the box, but from my experience "a large number of daemon-reload" usually means a problem in your services. 

There are very good reasons why systemd does not automatically reload services when they are modified (even if systemd already detects it) Daemon reload should really be a manual-only action...

Services are not meant to be edited frequently (heck, on most systems, they should be read-only) and this usually mean a misunderstanding/bad design somewhere else.

There might be a bug here, but I would seriously advice redoing whatever does the daemon-reload. If you are not sure how to do whatever requires those daemons-reloads, fell free to ask questions on the systemd mailing-list. that's where support questions go.

**Comment by poettering** [comment]
my educated guess: dbus is simply overloaded and doesn't respond?

**Comment by jackma-sudo** [comment]
> my educated guess: dbus is simply overloaded and doesn't respond?

but actually I can run "systemctl start/status/stop" without timeout during user test login timeout, dbus may not be overloaded?

**Comment by jackma-sudo** [comment]
Hmm... I think it's easy to reproduce this. And is it reasonable that the login with timeout 120s during high frequency use of “daemon-reload”？

**Comment by boucman** [comment]
as I said.i'm not sure "high frequencey daemon-reload" is reasonable... I'd really like to understand why you are doing that.

**Comment by jackma-sudo** [comment]
This issue can be solved by https://github.com/systemd/systemd/commit/428a9f6f1d0396b9eacde2b38d667cbe3f15eb55
https://github.com/systemd/systemd/commit/e9eec8b5d2c106c5dd51382a155e6045c7c17c1a
. Thanks a lot. @poettering @boucman

**Comment by poettering** [comment]
OK, let's close then.
