### ISSUE TITLE
systemd-resolved: limiting search domains to single label queries is restrictive

### ISSUE THREAD

**Issue by fbellet** [systemd/systemd#18147]
**systemd version the issue has been seen with**
 > systemd-246.7-2.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > 5.9.16-200.fc33.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > I expected the search domains to be applied to all  queries, not just single label queries. For example when domain is "corp.example." I would like to resolve "box.subdomain" as "box.subdomain.corp.example." and "box.othersubdomain" as "box.othersubdomain.corp.example.".  IMO the search domain should be always added except when the query is fully-qualified already, ie with a final dot.

**Unexpected behaviour you saw**
 > The behaviour of function ``dns_scope_name_wants_search_domain()`` seems to prevent such use case. 

**Steps to reproduce the problem**
 > …

**Comment by poettering** [comment]
This is security issue. If we'd do that, then "google.com" can be redirected to arbitrary domains, and that's generally not desirable.

We don't support this for a reason, and this is unlikely to change. This is documented in detail:

https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Compatibility%20with%20the%20traditional%20glibc%20stub%20resolver

Sorry, but this is something that is not going to change.
