### ISSUE TITLE
systemd-tmpfiles blocks indefinitely during boot when using systemd.volatile=overlay

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#18140]
**systemd version the issue has been seen with**
 > v247.2

**Used distribution**
 > Arch (VM) + Ubuntu Focal / Arch (host)

**Linux kernel version used** (`uname -a`)
 > 5.10.4

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > mkosi VM booted

**Unexpected behaviour you saw**
 > mkosi VM boot sequence blocked at 

`[    **] A start job is running for Create V…d Directories (4min 3s / no limit)`

**Steps to reproduce the problem**
 > 

mkosi config:

```
[Distribution]
Distribution=arch

[Host]
QemuHeadless=yes

[Output]
Format=gpt_ext4
WithUnifiedKernelImages=no
# Boot with systemd.volatile=overlay so squashfs images can write to the filesystem
KernelCommandLine=systemd.volatile=overlay
```

Then run `sudo mkosi qemu`

Interesting is that this only seems to happen in mkosi CI when using ext4 or xfs. When using btrfs, the VM boots as expected.

**Comment by poettering** [comment]
hmm, wha? on what precisely does it block? can you generate a backtrace of it when it hangs?

smells a lot like an overlayfs kernel bug.

**Comment by DaanDeMeyer** [comment]
I'm trying to get a backtrace but `kill -6 <pid>` from a debug shell doesn't give a coredump and `eu-stack -p <pid>` doesn't give me a backtrace either.

**Comment by Andrei-Pozolotin** [comment]
also tracking with kernel:
https://bugzilla.kernel.org/show_bug.cgi?id=211193
