### ISSUE TITLE
ProtectClock=yes blocks mount() system call for block device nodes

### ISSUE THREAD

**Issue by cgwalters** [systemd/systemd#18142]
**systemd version the issue has been seen with**
 > systemd-246.7-1.fc33.x86_64 and libseccomp-2.5.0-3.fc33.x86_64

**Used distribution**
 > Fedora CoreOS

**Linux kernel version used** (`uname -a`)
 > `Linux cosa-devsh 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

Having `ProtectClock=yes` seems to strangely deny use of `mount()`:

```
$ systemd-run -Pq -p ProtectClock=yes -p MountFlags=slave mount /dev/disk/by-label/EFI-SYSTEM /boot/efi/
mount: /boot/efi: permission denied.
$
```

Yet this works:

```
$ systemd-run -Pq -p MountFlags=slave mount /dev/disk/by-label/EFI-SYSTEM /boot/efi/
$
```

This came up in https://github.com/coreos/bootupd/pull/127/

I skimmed the relevant code and didn't see why this would be the case.

**Comment by poettering** [comment]
selinux?
