### ISSUE TITLE
su -c script ppoll blocking does not return

### ISSUE THREAD

**Issue by xufuhai** [systemd/systemd#18158]
**systemd version the issue has been seen with**
 > 219.42.el7_4.4

**Used distribution**
 > centos 7.4

**Linux kernel version used** (`uname -a`)
 > 3.10/4.18

**CPU architecture issue was seen on**
 > intel/amd

**Expected behaviour you didn't see**
 > su -c cd /home/sfop/paas-pcs-agent; bash bin/control.sh status - root script exits normally

**Unexpected behaviour you saw**
 > su -c cd /home/sfop/paas-pcs-agent; bash bin/control.sh status - root still hung ,not returns

**Steps to reproduce the problem**
 > have no clear approach to reproduce the issue

the issue by detailed:
Recently, I encountered a very strange problem. The script we deployed online was hung frequently and did not return like below image:
![image](https://user-images.githubusercontent.com/18589955/103899121-e22fde00-5130-11eb-8ab2-21e90e5dee46.png)
Use the pstack tool to view the call stack, it is blocked in ppoll and does not return
![image](https://user-images.githubusercontent.com/18589955/103899263-186d5d80-5131-11eb-878f-2bee533941cd.png)
Looking through the corresponding systemd code, I found the following code questions:
src/libsystemd/sd-bus/sd-bus.c:
![image](https://user-images.githubusercontent.com/18589955/103899418-54082780-5131-11eb-82dd-bbfbfdc8622d.png)
![image](https://user-images.githubusercontent.com/18589955/103899825-ec9ea780-5131-11eb-9e1c-378c1d8ecfd1.png)
![image](https://user-images.githubusercontent.com/18589955/103899875-04762b80-5132-11eb-913e-5f957f67e35c.png)
Since I don’t have a stable means to reproduce, but there are tens of thousands of machines on the line that the script does not return. The most likely cause of the blocking is that ppoll uses a synchronous blocking method to wait for the wake-up. , I checked the latest systemd mainline code and found that there seems to be no obvious code logic to solve this problem
![image](https://user-images.githubusercontent.com/18589955/103900365-af86e500-5132-11eb-8707-f3bb89d15cbc.png)
Corresponding to journalctl when there is a problem
![image](https://user-images.githubusercontent.com/18589955/103900518-d9d8a280-5132-11eb-9b06-d4ccda0e9625.png)
Can you help explain why poll waiting in BUS_OPENING state adopts blocking mode, and can it be optimized by timeout? And is there a solution to this problem? Thanks a lot

**Comment by bluca** [comment]
Have you raised this issue with the CentOS 7 package maintainers, or alternatively can it be reproduced on v247/v246? v219 is very old

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
