### ISSUE TITLE
Logitech MX Keys Wireless Keyboard identifies as Mouse 

### ISSUE THREAD

**Issue by yuriloliveira** [systemd/systemd#18161]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Ubuntu 24.04.1 LTS

**Linux kernel version used** (`uname -a`)
 > 5.4.0-59-generic

**Expected behaviour you didn't see**
 > Logitech MX Keys Wireless Keyboard being identified as Keyboard.

**Unexpected behaviour you saw**
 > Logitech MX Keys Wireless Keyboard being identified as Mouse

**Steps to reproduce the problem**
 > A Logitech MX Keys Wireless Keyboard

**Evidence**
The command *upower --dump* outputs as follows:
![image](https://user-images.githubusercontent.com/30935962/103952867-e1db1700-511f-11eb-8b29-063626fd0c53.png)

**Comment by yuriloliveira** [comment]
I've created PR #18162 to solve the issue. Tested with local */etc/udev/hwdb.d/61-input-id-local.hwdb* file.

**Comment by bluca** [comment]
Fixed by https://github.com/systemd/systemd/pull/18156
