### ISSUE TITLE
RFE: Possibility of using `--no-canonicalize` in mount units to prevent `What=` from being converted to absolute paths

### ISSUE THREAD

**Issue by chenxiaolong** [systemd/systemd#18188]
**Is your feature request related to a problem? Please describe.**

util-linux's `mount` calls `realpath()` on the [source argument of the mount by default](https://github.com/karelzak/util-linux/blob/1b39cd7f63b0beb1519a76f5104843c93809cf94/sys-utils/mount.c#L417-L419). This is problematic when the source should not be interpreted as a path, but is also a valid path. For example, by default, a zfs dataset of the name `pool/test` is mounted at `/pool/test`.

With a mount unit like:

```
[Mount]
Where=pool/test
What=/pool/test
Type=zfs
```

systemd will call the `mount` command with `mount pool/test /pool/test -t zfs`, but `mount` will call `mount.zfs` with `mount.zfs /pool/test /pool/test` (note the leading slash). `mount`'s `--no-canonicalize` argument prevents this behavior.

**Describe the solution you'd like**/**Describe alternatives you've considered**

I see two possible solutions for this:

* Update systemd to pass `--no-canonicalize` by default. I don't see anything in systemd's documentation that describes the canonicalization behavior, but at the same time, I'm not sure if folks depend on it.
* Add a new parameter to mount units that allows canonicalization to be disabled.

I'd like to get an opinion from the systemd maintainers to see if either of these would be viable solutions. I'd be happy to do the actual implementation and submit a PR.

**Comment by poettering** [comment]
hmm, @karelzak can you comment on this? why is the source mangled at all? i mean, for stuff such s procfs, sysfs, nfs overlayfs canonicalizing the souce path doesn't make much sense anyway, so how does mount figure out when to do this, and why does it do that for zfs?

**Comment by poettering** [comment]
and of course: i have the suspicion we should not have this as option at all, but simply unconditionally disable canonicalization, both on source and on dest... i mean, systemd expects that if it invokes /bin/mount for some path /foo/bar, that it is actually /foo/bar/ that shows up mounted in /proc/self/mountinfo after all, and not something canonicalized. i.e. systemd expects to deal in canonicalized mounts anyway, hence I figure the right approach would be to pass this switch always...

@karelzak the mount man page uses quite strong wording recommending against use of this switch. Can you elaborate?

**Comment by karelzak** [comment]
This is also reported for util-linux https://github.com/karelzak/util-linux/issues/1231. I think you can close this systemd issue as this is something we need to resolve in ZFS and util-linux upstreams. I'll very probably add an exception for ZFS.

@poettering we use canonicalization for more than 10 years, and yes, net filesystems and pseudo filesystems are excluded from this behavior. Unfortunately, ZFS doesn't fall under any of the existing exceptions.

The reason why we use canonicalization is (I think) obvious -- we want to control what we have in /proc/self/mountinfo and it's better to keep it in our hands and assume that all we write/read from kernel is canonical than introduce any unnecessary variability there.

The option --no-cannonicalize has been introduced for 3rd party script/applications (fuse in this case). The strong wording on the man page is to avoid that ordinary user will use it without an idea about the impact of the option. I guess we really don't want /root/../dev/symlink junk in mountinfo. The option is designed for users who understand it.

The option has also an impact on tags (LABEL=) evaluation. If you want to use it by default then you need to be sure that all (source and target) you specify on mount(8) command line is directly usable by mount(2) syscall and it's fine to have it in  mountinfo. 

I don't think we need to change anything on the current systemd behavior as there is nothing to fix, and it works as expected for all time ;-) The issue with ZFS is something we need to fix independently on systemd.

**Comment by poettering** [comment]
OK! Thanks for the feedback.

Let's close this then. Any further discssion on that util-linux bug please!
