### ISSUE TITLE
sd-bus: Can't asynchronously answer properties Get call?

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#18193]
If you look here the properties always expects the get and set call to immediately to put data in to the message.

https://github.com/systemd/systemd/blob/222466954659b33034dc87c2bb0c3db059bc110c/src/libsystemd/sd-bus/bus-objects.c#L618

Unlike methods, returning positive integer from message does not make the message async.

Is this a bug or designed on purpose?

**Comment by yuwata** [comment]
Hm? Sorry, I cannot catch what you want to say. Could you elaborate more?

**Comment by igo95862** [comment]
From man page:
> Note that you can return a positive integer from a callback without
>  immediately sending a reply. This informs sd-bus this callback will
>  take responsibility for replying to the request without forcing the
>  callback to produce a reply immediately. This allows a callback to
>  perform any number of asynchronous operations required to construct a
>  reply. However, if producing a reply takes too long, the method call
>  will time out at the caller.

This does not work for properties callbacks.

**Comment by igo95862** [comment]
I think there is a one line fix to this.
