### ISSUE TITLE
Systemd-networkd: allow `ManageTemporaryAddress` in `[DHCPv6PrefixDelegation]`

### ISSUE THREAD

**Issue by gdonval** [systemd/systemd#18208]
**Is your feature request related to a problem? Please describe.**

 > I'm always frustrated when I have to manually create a static address (in `[Address]`) when I already get a prefix from `[DHCPv6PrefixDelegation]`. 

**Describe the solution you'd like**

 > Being able to specify `ManageTemporaryAddress` in `[DHCPv6PrefixDelegation]` directly.
 > `Token` does not change its meaning: the assigned address is just added to the system with the `mngtmpaddr` flag.

**Describe alternatives you've considered**

> Using static addresses. All other alternatives I thought of are not neat (systemd unit file to scan `ip -6 a s` then construct and add new address with the right prefix).

**Comment by yuwata** [comment]
Implemented by #18227.
