### ISSUE TITLE
Systemd-networkd apparently can't perform stand-alone DHCPv6-PD requests

### ISSUE THREAD

**Issue by gdonval** [systemd/systemd#18203]
**systemd version the issue has been seen with**
> systemd 247 (247.2-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Archlinux 

**Linux kernel version used** (`uname -a`)
 > Linux <..> 5.10.5-arch1-1 #1 SMP PREEMPT Thu, 07 Jan 2021 09:50:43 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > Intel(R) Atom(TM) CPU  C2350  @ 1.74GHz

**Expected behaviour you didn't see**
 > Request prefix delegation without allocating an IPv6.

**Unexpected behaviour you saw**
 > DHCPv6 is *required* to obtain a lease and a /56 prefix to delegate (DHCPv6-PD).
 > But when used, a default address, [prefix]::1/128, is systematically allocated on the requesting network interface with no apparent way to disable assignment. I tried `Assign=no` everywhere permitted.
 > If DHCPv6 client is not activated, no lease is acquired and DHCPv6-PD is not triggered at all.

**Steps to reproduce the problem**

> /etc/systemd/networkd/10-wan.network

```
[Match]
# Actually the name of the specific wan interface like `enp0s20`
Name=e*
 
[Network]
DHCP=ipv6
IPv6AcceptRA=yes
Address=<fixed IPv4 address>
Address=[prefix]:1:2:3:4/128
DHCPv6PrefixDelegation=yes

[Route]
Gateway=<fixed IPv4 gateway>
GatewayOnlink=yes

[DHCP]
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=<duid>

[IPv6AcceptRA]
UseOnLinkPrefix=no
UseAutonomousPrefix=no
# Pretty sure the DHCPv6 server is not 100% compliant:
#    either have to uncomment the next line:
#DHCPv6Client=always
#    or have to set `WithoutRA` in `[DHCPv6]`

[DHCPv6]
RapidCommit=no
ForceDHCPv6PDOtherInformation=yes
PrefixDelegationHint=[prefix]::/56
WithoutRA=solicit
```
> Activate the link and a default IPv6 address ([prefix]::1/128) should be allocated on the `e*` interface.

**Notes of importance**

 > Without `WithoutRA=solicit` or `DHCPv6Client=always`, prefix delegation does not work at all (I can provide an example of configuration for a dummy interface to see this).

 > When the address is allocated, this is what I see in the journal (debug mode):

```raw
Jan 11 13:54:07 <..> systemd-networkd[411]: DHCPv6 CLIENT: Timeout T1
Jan 11 13:54:07 <..> systemd-networkd[411]: DHCPv6 CLIENT: Sent RENEW
Jan 11 13:54:07 <..> systemd-networkd[411]: DHCPv6 CLIENT: Next retransmission in 9s
Jan 11 13:54:07 <..> systemd-networkd[411]: DHCPv6 CLIENT: T1 expires in 2h 42min 31s
Jan 11 13:54:07 <..> systemd-networkd[411]: DHCPv6 CLIENT: T2 expires in 1d 23h 16min 36s
Jan 11 13:54:07 <..> systemd-networkd[411]: enp0s20: DHCPv6 address [prefix]::1/128 timeout preferred 54000 valid 86400
Jan 11 13:54:07 <..> systemd-networkd[411]: enp0s20: Updating address: [prefix]::1
Jan 11 13:54:07 <..> systemd-networkd[411]: enp0s20: Configuring route: dst: [prefix]::/56, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: 0, type: unreachable
Jan 11 13:54:07 <..> systemd-networkd[411]: enp0s20: Assigning up to 256 prefixes from [prefix]::/56
```

 > My provider does not say anything about an address being pushed, quite the contrary, [this](https://documentation.online.net/en/dedicated-server/network/ipv6/prefix#how_to_configure_the_dhcpv6_client) is their documentation and they explicitly advise to set an address manually (and indeed `dhclient` does not auto-allocate an address).

**Comment by yuwata** [comment]
I created #18205.

**Comment by seblu** [comment]
I tested the patch with systemd v248 and the address is not assigned. :+1: 
But still, systemd-networkd can't perform **stand-alone** requests, obtain a lease, and let another process or even itself assign subnet statically to an interface.

For example, when a provider distribute a PD lease of subnet `2021::/56`, we cannot assign an address of the pool statically 
This require either, a dummy interface (resulting in one interface for IPv4 and one for IPv6), or use dhclient to only manage the PD lease and let networkd assignt the address statically instead of a network file like this:

```ini
[Match]
Name=eth0

[Network]
Address=1.2.3.4/24
Address=2021::1:2:3:4/64
Gateway=1.2.3.1
DHCP=ipv6

[DHCPv4]
# Used by DHCPv6 but not allowed in DHCPv6
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=****

[DHCPv6]
UseAddress=false
WithoutRA=solicit
```

Is this need a separate RFE ?

**Comment by yuwata** [comment]
Could you open a new rfe page? Otherwise, we can easily forget your request.

By the way, have you tried to use `Assign=` setting in [DHCPv6PrefixDelegation] section?
