### ISSUE TITLE
systemd-cryptsetup-generator creates units with TimeoutSec=0, causing them to fail

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#18224]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > Linux work 5.4.88-1.qubes.x86_64 \#1 SMP Mon Jan 11 05:03:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemd-cryptsetup-generator` generates units with a reasonable timeout, or with timeouts disabled

**Unexpected behaviour you saw**
 >  `systemd-cryptsetup-generator` generates units with a zero timeout

**Steps to reproduce the problem**
 > Create an encrypted swap partition in `/etc/crypttab`

**Comment by poettering** [comment]
Can you elaborate? Which units have TimeoutSec= precisely? and how do they fail?

**Comment by DemiMarie** [comment]
Here is `/run/systemd/generator/systemd-cryptsetup@swap.service`:

    # Automatically generated by systemd-cryptsetup-generator
    
    [Unit]
    Description=Cryptography Setup for %I
    Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
    SourcePath=/etc/crypttab
    DefaultDependencies=no
    IgnoreOnIsolate=true
    After=cryptsetup-pre.target
    Before=blockdev@dev-mapper-%i.target
    Wants=blockdev@dev-mapper-%i.target
    Conflicts=umount.target
    Before=cryptsetup.target
    After=systemd-random-seed.service
    BindsTo=dev-xvdc1.device
    After=dev-xvdc1.device
    Before=umount.target
    
    [Service]
    Type=oneshot
    RemainAfterExit=yes
    TimeoutSec=0
    KeyringMode=shared
    OOMScoreAdjust=500
    ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'swap' '/dev/xvdc1' '/dev/urandom' 'swap,cipher=aes-xts-plain64,discard,size=512'
    ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'swap'
    ExecStartPost=/usr/lib/systemd/systemd-makefs swap '/dev/mapper/swap'

Intermittently, this unit times out, causing my QubesOS VMs to occasionally fail to start.

**Comment by DemiMarie** [comment]
@poettering do you need more information?

**Comment by poettering** [comment]
So this is just a misunderstanding. Setting these time-outs to zero turns them off. We nowadays suggest that people spell this out as "TimeoutSec=infinity" though. Will post PR shortly that does so.

But anyway, we turn off time-outs where because cryptsetup is possibly interactive (i.e. asks user for a pw), and hence a time-out doesn't really make sense.
