### ISSUE TITLE
nss-mymachines not working inside of a container

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#18229]
**systemd version the issue has been seen with**
 > systemd-246.7-2.fc33.x86_64

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)
 > Linux $HOSTNAME 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > inter-container DNS lookup works

**Unexpected behaviour you saw**
 > unresolved DNS names between containers

**Steps to reproduce the problem**

  - Insert `mymachines` into `/etc/nsswitch.conf`'s `hosts` line in a container
  - Run a container with `systemd-nspawn -M target -D … --boot` (I used a `fedora:33` container mounted via `buildah`)
  - Run a container with `systemd-nspawn -M source -D … --boot`
  - Inside a `machinectl shell source`: `getent ahosts target` returns nothing (it works on the host)

Mounting a container:

  - `buildah mount $( buildah from fedora:33 )` will output the path to give to `-D`. Can be repeated for distinct root directories.

**Comment by mathstuf** [comment]
Hmm, I do see it working for one pair of containers…I'll have to investigate what the difference might be.

**Comment by mathstuf** [comment]
It seems that there is one container that all can reach…but no other combination seems to work? I don't know what is different about the one container that can be resolved.

**Comment by poettering** [comment]
Hmm, wa? nss-mymachines allows the host to resolve its container names, not the containers to resolve each other names...

If you want that I'd suggest running resolved in them, turning on llmnr, which should make this just work if you put them on the same link.

Anyway, I think this is mostly a misunderstanding. I figure we can improve docs though, making this clear more explicity. Hence turning this into a documentation issue

**Comment by mathstuf** [comment]
I wonder if the one that does resolve is finding it through the global name that does exist for it.

> If you want that I'd suggest running resolved in them, turning on llmnr, which should make this just work if you put them on the same link.

I am running resolved inside. I'll check out llmnr. Is using the same `Zone=` setting the same link? Or is some other setting needed for that?

**Comment by mathstuf** [comment]
Though the default does seem to be `true`. I guess they're not on the same link then.
