### ISSUE TITLE
Make Handle Lid events "edge triggered"

### ISSUE THREAD

**Issue by gene-vigelis** [systemd/systemd#18240]
The current HandleLid series of events prevent me from having a systemd trigger wake my laptop to perform backups when the lid is closed which is 100% of the time in the middle of the night.

Have the HandleLid logic only trigger when the lid switch changes from Open -> Close or Close -> Open (i.e. Edge Triggered)

I can find no alternative, every attempt to wake the laptop with the lid closed puts it immediately back to sleep. Disabling the Lid switch is no a desirable option as multiple people who are not tech savy use this laptop and cannot be counted on to manually initiate a sleep cycle.

**Comment by poettering** [comment]
You can specify a long `HoldoffTimeoutSec=` time and then use the `systemd-inhibit` tool to take an inhibitor lock for the lid switch as long as your backup script runs. That way we'll still suspend once the lid is closed, but with the specified latency in which you cn start your script. if you didn't do that in the available time we'll go back to sleep, which is good and makes this robust. But if your script started and acquired the inhibitor the system will stay up until you end the inhibitor lock.
