### ISSUE TITLE
udev: Processing firmware loading events can be too late

### ISSUE THREAD

**Issue by izh1979** [systemd/systemd#18259]
Prior to https://github.com/systemd/systemd/commit/be2ea723b1d023b3d385d3b791ee4607cbfb20ca there was udev's "firmware" built-in command which is dropped now. But it seems that it is not currently possible to implement firmware loading by using udev rules, because the firmware loading events could be too late in some situations.
E.g. when some device needs both kernel module loading and firmare loading, the order of the events executions could be important. I.e. first you need to load the firmware to bring up some HW part, then load the module that will communicate to the hardware. And currently it could be that the firmware loading event will be processed after the module loading. So module will wait for a device until some timeout, then print error and terminate, then the firmware loading event will be processed, but there is no more firmware special file in /sys/.
Ealier there was an exception for firmware handling events allowing them to skip dependencies and be executed earlier:
https://github.com/systemd/systemd/commit/be2ea723b1d023b3d385d3b791ee4607cbfb20ca#diff-000342aa23dfb7299537dded24bb982625fdb7bc62f94be779c94041e49e1e5aL542
Should we bring this back?

**Comment by izh1979** [comment]
So there could be currently following sequence of events:
1) udev sees new device and schedules firmware loading event
2) then udev loads kernel module which initializes the hardware and waits for the firmware to be loaded(which can't be loaded because of the dependency)
3) nothing happened within a minute, the kernel module complains about failing to load the firmware and exits (the firmware loading directory is removed from /sys)
4) firmware loading event is fired, the script tries to load the firmware, but the proper directory is alredy removed from /sys

**Comment by poettering** [comment]
We don#t support user-space firmware loading anyore. The kernel does that on its own these days.

**Comment by izh1979** [comment]
Then why don't udev simply drops firmware events? Because currently they are can still be used in udev rules, but they are broken.

**Comment by izh1979** [comment]
I suggested not to bring back the full support of the firmware loading, but simply firing them earlier as it was before the removal commit.

**Comment by poettering** [comment]
Please read the documentation, i.e. README, where we ask people to turn it off in the kernel.

**Comment by poettering** [comment]
I am sorry, we are not going to polish a feature we don't support anymore.

**Comment by izh1979** [comment]
Well, in the world of mobile devices where e.g. Android firmware can be placed in some non-standard folders you have either to patch the kernel or to use some helper.

**Comment by poettering** [comment]
symlinks?

**Comment by izh1979** [comment]
Yes. It is one possible way (if the kernel follows them -- need to check). Another way is to alter the kernel list of directories where it looks for the firmware.
