### ISSUE TITLE
networkd: Destination with single IP address should not add IPv6 prefix route

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#18278]
**systemd version the issue has been seen with**
 > systemd 247 (247.2-1-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.7.12-arch1-1 and 5.6.12-arch1-1

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > I expected the IPv6 routes to behave the same way as for IPv4. Specifying a single IP as the `Destination=` address did not add a subnet route for IPv4 (correct) but it did add a subnet route for IPv6 (incorrect).

**Unexpected behaviour you saw**
 > A `/64` route was added for an IPv6 point-to-point link when a single destination/peer IP was specified.  This prefix route should not have been added.
 > I tried setting `AddPrefixRoute=false` in the `[Address]` section but the prefix route was still added.  I also tried specifying `Peer=` in the `[Address]` section but this appeared to be ignored.

**Steps to reproduce the problem**
```
# Config for second network interface (not the primary one)
[Route]
Scope=link
Destination=192.168.0.10/32

[Route]
Scope=link
Destination=fd01::1:2:3:4/128
```
After applying, there is no network route for IPv4 which is expected and correct:
```
$ ip route
192.168.0.10 dev eth1 proto static scope link
# Nothing for 192.168.0.0/24 dev eth1
```
However for IPv6, a route for the network is added, despite the destination being a single IPv6 address:
```
$ ip -6 route
fd01::1:2:3:4 dev eth1 proto static metric 1024 pref medium
fd01::/64 dev eth1 proto kernel metric 256 pref medium   # Should not be added
```
I cannot find a way to get a route added for a single destination IPv6 address without having the `/64` route added as well.

**Comment by yuwata** [comment]
Hmm? I cannot reproduce the issue, Could you show the full .network file?

**Comment by yuwata** [comment]
I tested with the following.
```
[Match]
Name=dummy98

[Address]
Address=fd01::1:2:3:5/64
AddPrefixRoute=false

[Route]
Destination=fd01::1:2:3:4/128
```
```
$ ip -6 address show dev dummy98
31: dummy98: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    inet6 fd01::1:2:3:5/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
$ ip -6 route show dev dummy98
fd01::1:2:3:4 proto static metric 1024 pref medium
fe80::/64 proto kernel metric 256 pref medium
```

**Comment by yuwata** [comment]
(Note, `Scope=` for IPv6 route is ignored.)

**Comment by Malvineous** [comment]
I tried `AddPrefixRoute=no` but it still adds the prefix route.

This is the full `.network` file.  I've tried it with the exact IPv6 addresses below and confirmed I get the unwanted prefix route:
```
[Match]
Name=eth1

[Network]
Address=fd01::1:2:3:4/64
DefaultRouteOnDevice=false
AddPrefixRoute=no

[Route]
Scope=link
PreferredSource=192.168.0.2
Destination=192.168.0.10/32

[Route]
Scope=link
PreferredSource=fd01::1:2:3:4
Destination=fd01::5:6:7:8/128
```
```
[Match]
Name=eth0

[Network]
Address=fd01::1:2:3:4/64
Address=192.168.0.2/16
Gateway=192.168.0.1
```
```
$ ip -6 route | grep fd01
fd01::5:6:7:8 dev eth1 proto static src fd01::1:2:3:4 metric 1024 pref medium
fd01::/64 dev eth1 proto kernel metric 256 pref medium    # Unwanted
fd01::/64 dev eth0 proto kernel metric 256 pref medium    # Correct
```
I tried commenting that whole IPv4 `[Route]` section out and I still get it, so perhaps it's related to having addresses within the same IPv6 prefix across two interfaces?  (My intention is to use `eth0` for all traffic on fd01::/64, but then use `eth1` for just a single IP address within that prefix, so that one IP goes via a much faster direct network link between the two machines.)

Thanks for the tip about `Scope` I will remove that if it is not used.

**Comment by yuwata** [comment]
Oh, `AddPrefixRoute=` must be in `[Address]` section. So, you should use something like the following:
```
[Match]
Name=eth1

[Network]
DefaultRouteOnDevice=false

[Address]
Address=fd01::1:2:3:4/64
AddPrefixRoute=no

[Route]
Scope=link
PreferredSource=192.168.0.2
Destination=192.168.0.10/32

[Route]
PreferredSource=fd01::1:2:3:4
Destination=fd01::5:6:7:8/128
```

**Comment by Malvineous** [comment]
Ohhh, that's all it was!  I thought I double-checked where `AddPrefixRoute` goes but apparently I only scrolled up in the man page far enough to see that it goes under `Address=`, silly me.

I have moved it (and `Address=` as suggested) to the `[Address]` section and I confirm it now works as expected, no extra IPv6 prefix gets added.

Sorry about that, and many thanks for your help!

**Comment by yuwata** [comment]
Nope, I am happy to hear that.
