### ISSUE TITLE
test-parse-util fails on 32 bit - safe_atou does not ERANGE on negative numbers

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1829]
on i386 (32 bit x86), this test fails:

```
$ ./test-parse-util 
Assertion 'parse_range("111--123", &lower, &upper) == -ERANGE' failed at src/test/test-parse-util.c:258, function test_parse_range(). Aborting.
```

Stepping through with gdb shows that the "-123" is not handled correctly in `safe_atou`:

```
303    int safe_atou(const char *s, unsigned *ret_u) {
[...]
311         l = strtoul(s, &x, 0);
(gdb) p s
$8 = 0x5658928f "-123"
(gdb) n
313         if (!x || x == s || *x || errno)
(gdb) p x
$9 = 0x56589293 ""
(gdb) p l
$10 = 4294967173
(gdb) p errno
$11 = 0
```

Thus this expects an `ERANGE` from `strtoul()`, but that instead converts it to a positive number. But this actually appears correct: the manpage says:

>  "The  strtoul() function returns either the result of the conversion or, if there was a leading minus sign, the negation of the result of the conversion represented as an unsigned value, unless the original (nonnegated)  value  would  overflow;  in  the  latter  case,  strtoul() returns ULONG_MAX and sets errno to ERANGE."

So it would seem we need to check for a leading minus sign ourselves?

**Comment by martinpitt** [comment]
Ah, it's not due to `strtoul()` not returning `ERANGE`, sorry; I didn't read into the code far enough. On x86_64, we get `l == 18446744073709551493`, which fails that `(unsigned long) (unsigned)` conversion as `(unsigned) l == 4294967173`.

But on 32 bit `strtoul()` already just returns a 32 bit unsigned, i. e. `l == 4294967173`, so a further (attempted) "truncation" to `(unsigned)` does not actually change its value.

Is `safe_atou()` actually supposed to fail with `ERANGE` on negative numbers? Then the `(unsigned long) (unsigned)` double-casting won't work. Or is it just supposed to fail on too large numbers? Then the test needs to be adjusted as -123 is way too small to trigger an overflow.

**Comment by martinpitt** [comment]
If we want an ERANGE for negative numbers: glibc really doesn't make that easy :-( We'd either need to skip space and check for a leading minus ourselves, or parse it twice with e. g. `strtoll` and check if that's negative (but we couldn't use that in `safe_atollu()`).

However, if we want ERANGE for negative numbers, then this isn't consistently implemented anyway: `safe_atollu()` and `safe_atod`() implement no such check.

So once we made up our mind about how the `*u()` functions should handle negative numbers, we can then go ahead and fix them to be consistent, and also add some tests for negative numbers to `test-parse-util.c`.

**Comment by poettering** [comment]
I prepped a fix for this in #1835, please have a look.

**Comment by martinpitt** [comment]
Confirmed, working fine on 32 bits now. Thanks!

**Comment by martinpitt** [comment]
I created PR #1844 for adding some more test cases around this.
