### ISSUE TITLE
resolved crashes in dns_transaction_process_reply

### ISSUE THREAD

**Issue by bugaevc** [systemd/systemd#18295]
**systemd version the issue has been seen with**
246
```
$ /usr/lib/systemd/systemd-resolved --version
systemd 246 (v246.7-2.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Used distribution**
Fedora 33

**Linux kernel version used**
5.10.7

**CPU architecture issue was seen on**
x86_64

systemd-resolved has segfaulted several times in a row with this backtrace:
```
(gdb) bt
#0  0x00007f589a460f47 in hashmap_iterate_entry (i=0x7ffd765d4000, h=0x706f746b73656465) at ../src/basic/hashmap.c:703
#1  _hashmap_iterate (h=0x706f746b73656465, i=i@entry=0x7ffd765d4000, value=value@entry=0x7ffd765d3ff8, key=key@entry=0x0) at ../src/basic/hashmap.c:712
#2  0x00007f589a46101b in set_iterate (s=<optimized out>, i=i@entry=0x7ffd765d4000, value=value@entry=0x7ffd765d3ff8) at ../src/basic/hashmap.c:733
#3  0x000055b98577980f in dns_query_candidate_go (c=c@entry=0x55b986261490) at ../src/resolve/resolved-dns-query.c:139
#4  0x000055b985779720 in dns_query_candidate_notify (c=0x55b986261490) at ../src/resolve/resolved-dns-query.c:271
#5  0x000055b98577de28 in dns_transaction_complete (t=0x55b98624b8e0, state=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:350
#6  0x000055b98577fefb in dns_transaction_process_reply (t=0x55b98624b8e0, p=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:1171
#7  0x000055b985780d41 in on_dns_packet (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x55b98624b8e0) at ../src/resolve/resolved-dns-transaction.c:1223
#8  0x00007f589a509217 in source_dispatch (s=s@entry=0x55b98626fbb0) at ../src/libsystemd/sd-event/sd-event.c:3181
#9  0x00007f589a5094fd in sd_event_dispatch (e=0x55b9862621e0) at ../src/libsystemd/sd-event/sd-event.c:3620
#10 0x00007f589a50a7c8 in sd_event_run (e=e@entry=0x55b9862621e0, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3678
#11 0x00007f589a50a9ef in sd_event_loop (e=0x55b9862621e0) at ../src/libsystemd/sd-event/sd-event.c:3700
#12 0x000055b98576bc14 in run (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:92
#13 0x000055b98576060a in main (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:99
```

<details>
<summary><code>bt full</code>, though it doesn't look very useful</summary>
<pre><code>(gdb) bt full
#0  0x00007f589a460f47 in hashmap_iterate_entry (i=0x7ffd765d4000, h=0x706f746b73656465) at ../src/basic/hashmap.c:703
No locals.
#1  _hashmap_iterate (h=0x706f746b73656465, i=i@entry=0x7ffd765d4000, value=value@entry=0x7ffd765d3ff8, key=key@entry=0x0) at ../src/basic/hashmap.c:712
        e = &lt;optimized out&gt;
        data = &lt;optimized out&gt;
        idx = &lt;optimized out&gt;
#2  0x00007f589a46101b in set_iterate (s=&lt;optimized out&gt;, i=i@entry=0x7ffd765d4000, value=value@entry=0x7ffd765d3ff8) at ../src/basic/hashmap.c:733
No locals.
#3  0x000055b98577980f in dns_query_candidate_go (c=c@entry=0x55b986261490) at ../src/resolve/resolved-dns-query.c:139
        t = 0x55b98626e520
        i = {idx = 4294967295, next_key = 0x0}
        r = &lt;optimized out&gt;
        n = 1
        __PRETTY_FUNCTION__ = "dns_query_candidate_go"
#4  0x000055b985779720 in dns_query_candidate_notify (c=0x55b986261490) at ../src/resolve/resolved-dns-query.c:271
        state = &lt;optimized out&gt;
        r = 1
        __PRETTY_FUNCTION__ = "dns_query_candidate_notify"
        __func__ = "dns_query_candidate_notify"
#5  0x000055b98577de28 in dns_transaction_complete (t=0x55b98624b8e0, state=&lt;optimized out&gt;) at ../src/resolve/resolved-dns-transaction.c:350
        c = 0x55b986261490
        z = &lt;optimized out&gt;
        d = &lt;optimized out&gt;
        st = 0x55b9857ab331 "rcode-failure"
        key_str = "\000z\346\231X\177\000\000\200\000\000\000\000\000\000\000\340@]v\375\177\000\000\000\000\000\000X\177\000\000\000\000\000\000\000\000\000\000\060A]v\375\177\000\000\360@]v\375\177\000\000\000\000\000\000\000\000\000\000\350@]v\375\177\000\000\340\270$\206\271U\000\000\000\000\000\000\000\000\000\000\332\026&gt;\232X\177\000\000[\317΅\271U\000\000\373Yх\271U\000\000\000et\000tdec\000aptop\000\000\260\260΅\271U\000\000\377\213x\205\271U\000\000\260\377\360\205\271U\000\000\000\376\206g\327Ka\323XA]v\375\177\000\000\340\270$\206\271U\000\000\250\251&\206\271U\000\000\220A]v\375\177\000\000\210A]v\375\177\000\000\000\000\000\000\000\000\000\000"...
        __PRETTY_FUNCTION__ = "dns_transaction_complete"
        __func__ = "dns_transaction_complete"
        _found = &lt;optimized out&gt;
        __assert_in_set = {&lt;optimized out&gt;, &lt;optimized out&gt;, &lt;optimized out&gt;}
#6  0x000055b98577fefb in dns_transaction_process_reply (t=0x55b98624b8e0, p=&lt;optimized out&gt;) at ../src/resolve/resolved-dns-transaction.c:1171
        ts = 152168533048
        r = 0
        __PRETTY_FUNCTION__ = "dns_transaction_process_reply"
        __func__ = "dns_transaction_process_reply"
#7  0x000055b985780d41 in on_dns_packet (s=&lt;optimized out&gt;, fd=&lt;optimized out&gt;, revents=&lt;optimized out&gt;, userdata=0x55b98624b8e0) at ../src/resolve/resolved-dns-transaction.c:1223
        p = 0x55b98626a900
        t = 0x55b98624b8e0
        r = &lt;optimized out&gt;
        __PRETTY_FUNCTION__ = "on_dns_packet"
        __func__ = "on_dns_packet"
#8  0x00007f589a509217 in source_dispatch (s=s@entry=0x55b98626fbb0) at ../src/libsystemd/sd-event/sd-event.c:3181
        saved_type = SOURCE_IO
        r = &lt;optimized out&gt;
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#9  0x00007f589a5094fd in sd_event_dispatch (e=0x55b9862621e0) at ../src/libsystemd/sd-event/sd-event.c:3620
        ref = 0x55b9862621e0
        p = 0x55b98626fbb0
        r = &lt;optimized out&gt;
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#10 0x00007f589a50a7c8 in sd_event_run (e=e@entry=0x55b9862621e0, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3678
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_run"
#11 0x00007f589a50a9ef in sd_event_loop (e=0x55b9862621e0) at ../src/libsystemd/sd-event/sd-event.c:3700
        ref = &lt;optimized out&gt;
        r = &lt;optimized out&gt;
        __PRETTY_FUNCTION__ = "sd_event_loop"
#12 0x000055b98576bc14 in run (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at ../src/resolve/resolved.c:92
        m = &lt;optimized out&gt;
        notify_stop = 0x55b9857a4668 "STOPPING=1\nSTATUS=Shutting down..."
        r = 0
        __func__ = "run"
        __PRETTY_FUNCTION__ = "run"
#13 0x000055b98576060a in main (argc=&lt;optimized out&gt;, argv=&lt;optimized out&gt;) at ../src/resolve/resolved.c:99
        r = &lt;optimized out&gt;
</details>

**Comment by keszybz** [comment]
Please test #18290. This appears to be the same as #16168.
