### ISSUE TITLE
RFE: make "coredumpctl info" show COREDUMP_HOSTNAME= log field if different from HOSTNAME=, to improve friendliness towards UTS containers

### ISSUE THREAD

**Issue by rampxxxx** [systemd/systemd#18321]
**systemd version the issue has been seen with**
 > 246.9-1.1

**Used distribution**
 > openSuse Tumbleweed

**Linux kernel version used** (`uname -a`)
 > `4.12.14-lp151.33.gf0f1262-default`

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > With just a core_pattern like this `/tmp/core.%e.%p.%h` and a crash inside a docker the core generated has this name  `/tmp/core.processd.2044.docker1`

**Unexpected behaviour you saw**
 > "coredumpctl info"  show info with lines like this "Hostname: localhost.localdomain" which is the hostname not the docker name

**Steps to reproduce the problem**
 > Install systemd-coredump , docker , ... run a crashable binary from inside the docker

**Comment by poettering** [comment]
I don't follow?

Is this is a complaint that coredump collection running on the host includes the hostname of the host in the coredump metadata, and you'd rather have it collect the hostname of the container? Or are you saying the opposite?

I have no idea what a "docker name" is. systemd has no relationship to docker.

**Comment by rampxxxx** [comment]
I'd rather that `systemd-coredump`collect ,what I think is , the proper hostname . 
If the crash happens in the host then the hostname, if the crash is inside the docker container then the name of the container .
But always the output of `uname -n` (run inside host or inside container) as happens when the system is configured without `systemd-coredump` and just with `echo "/tmp/core.%e.%p.%h > /proc/sys/kernel/core_pattern`  .

What I think is that systemd-coredump makes some conversion/validation with the `%h` parameter because I've created a bash script that just print all received parameters:
```
echo "|/tmp/dump_parms.sh %P %u %g %s %t %c %h " > /proc/sys/kernel/core_pattern
```

And the output of that script is 
```
23745 0 0 6 1611134578 18446744073709551615 localhost.localdomain
24474 0 0 6 1611134603 18446744073709551615 dock1
29432 0 0 6 1611134779 18446744073709551615 dock1
30117 0 0 6 1611134803 18446744073709551615 localhost.localdomain
30372 0 0 6 1611134812 18446744073709551615 dock1

```
So when a crash happens inside the host the %h parameter is `localhost.localdomain`and when a crash happens inside a docker container the %h parameter is `dock1`.

But when the systemd-coredump is configured ' coredumpctl' always print `localhost.localdomain` in the `Hostname` row.

**Comment by poettering** [comment]
so systemd-coredump runs on the host, and when it logs about the crashes it does so from the host hence the hostname of the host shows up in the logs. That said, the hostname inside the container is also collected in the COREDUMP_HOSTNAME= property. we could probably show that too in coredumpctl if it is different from the host the coredump collector runs on.
