### ISSUE TITLE
IPv6 Proxy NDP addresses are being lost from interfaces after networkd adds them

### ISSUE THREAD

**Issue by kpfleming** [systemd/systemd#18378]
**systemd version the issue has been seen with**
 > Debian 247.2-5 package

**Used distribution**
 > Debian testing (Bullseye)

**Linux kernel version used** (`uname -a`)

 > `Linux net20 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Five configured IPv6 Proxy NDP addresses for eno1 do not appear in 'ip neigh show proxy'

**Steps to reproduce the problem**
 > 

1. Configure eno1 as follows:

```
[Match]
Name=eno1

[Network]
IPv6ProxyNDPAddress=2607:5300:203:5215:5::1
IPv6ProxyNDPAddress=2607:5300:203:5215:4::1
IPv6ProxyNDPAddress=2607:5300:203:5215:3::1
IPv6ProxyNDPAddress=2607:5300:203:5215:1::1
IPv6AcceptRA=no
DHCP=ipv4
IPForward=yes
IPv6ProxyNDPAddress=2607:5300:203:5215:2::1
Address=66.70.129.136/32
Address=66.70.129.142/32
Address=66.70.129.143/32

[DHCP]
UseDNS=no

[Address]
Address=2607:5300:203:5215::1/64

[Route]
Destination=2607:5300:203:52ff:ff:ff:ff:ff

[Route]
Gateway=2607:5300:203:52ff:ff:ff:ff:ff
Destination=::/0
```

2. Boot system
3. Run 'ip neigh show proxy' to see that the proxy addresses were not added, then add them manually to ensure that they can be added successfully

```
root@net20:~# ip neigh show proxy
2607:5300:203:5215::1 dev ve-mail20  proxy
2607:5300:203:5215::1 dev ve-diw20  proxy
root@net20:~# ip neigh add proxy 2607:5300:203:5215:4::1 dev eno1
root@net20:~# ip neigh add proxy 2607:5300:203:5215:1::1 dev eno1
root@net20:~# ip neigh add proxy 2607:5300:203:5215:2::1 dev eno1
root@net20:~# ip neigh add proxy 2607:5300:203:5215:3::1 dev eno1
root@net20:~# ip neigh add proxy 2607:5300:203:5215:5::1 dev eno1
root@net20:~# ip neigh show proxy
2607:5300:203:5215:5::1 dev eno1  proxy
2607:5300:203:5215:3::1 dev eno1  proxy
2607:5300:203:5215:2::1 dev eno1  proxy
2607:5300:203:5215:1::1 dev eno1  proxy
2607:5300:203:5215:4::1 dev eno1  proxy
2607:5300:203:5215::1 dev ve-mail20  proxy
2607:5300:203:5215::1 dev ve-diw20  proxy
```

DEBUG log of systemd-networkd is here: https://gist.github.com/kpfleming/4b6c721edaf9d2ff4a24dadbb002fb0c#file-systemd-networkd-log

I can't see any indication in the log that there were errors encountered while attempting to add the addresses to the interface.

This system was recently upgraded from Debian Buster (systemd 241) to Debian Bullseye (systemd 247) and this problem did not occur prior to the upgrade, so at this point I can only surmise that something changed between 241 and 247 to cause this problem. I understand that's a wide range of versions and will attempt to build systemd from source with some additional debug logging to see if I can figure out what is happening.

**Comment by yuwata** [comment]
I cannot reproduce the issue. See #18380. The newly added test passes on my local machine.

**Comment by kpfleming** [comment]
Thanks for that, I'll continue working on my custom build to see if I can figure out what is triggering the issue.

**Comment by kpfleming** [comment]
OK, added a log entry for each attempt to add an IPv6 Proxy NDP address, and sure enough... networkd is adding them, and not getting any error response. However, the addresses are *not* present in the 'ip neigh show proxy' output, so somehow they are being lost after the successful additions.

Updated log is here (new log entries are prefixed with KPF): https://gist.github.com/kpfleming/4b6c721edaf9d2ff4a24dadbb002fb0c#file-systemd-networkd-2-log

I can only assume that some kernel events on these links are occurring after the addresses are added, and the kernel is removing them, and then networkd doesn't know that it needs to re-add them after that event occurs.

**Comment by kpfleming** [comment]
Looking over the log, there is a 'carrier loss' event on eno1 which appears to be correlated with the DHCPv4 client doing something to the link; when carrier returns on the link, networkd re-applies the static addresses and routes, but doesn't re-apply the proxy NDP addresses.

**Comment by kpfleming** [comment]
For what it's worth, I seem to be seeing the same behavior on veth devices created by systemd-nspawn when I launch containers (there are five in the log I linked). Sometimes the proxy address added by the nspawn startup process just disappears from the host end of the veth link pair.

**Comment by kpfleming** [comment]
I have tried setting the NUD_PERMANENT flag on the neighbor addresses, and also delaying the addition of the addresses by moving the function call into the "configure_continue" function in networkd-link.c, but neither were effective.

**Comment by kpfleming** [comment]
Continuing the investigation, I've posted to the netdev mailing list to find out which interface events might be responsible for the proxy addresses being removed inside the kernel.

**Comment by kpfleming** [comment]
I didn't get any responses from the netdev mailing list, so I added some hacky code into networkd to dump the list of Proxy NDP addresses attached to a link every time `link_clean` is called (hoping that I would catch every significant link event that way). It seems to have worked, here's a log for a veth pair created by systemd-nspawn which is configured to have one Proxy NDP address on it:

```
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: New device has no master, continuing without
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Flags change: +MULTICAST +BROADCAST
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Link 6 added
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: udev initialized link
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: State changed: pending -> initialized
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Saved original MTU: 1500
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Link state is up-to-date
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: found matching network '/etc/systemd/network/mail20.network'
Feb 03 06:53:47 net20 systemd-networkd[2608]: Setting '/proc/sys/net/ipv6/conf/ve-mail20/disable_ipv6' to '0'
Feb 03 06:53:47 net20 systemd-networkd[2608]: Setting '/proc/sys/net/ipv6/conf/ve-mail20/use_tempaddr' to '0'
Feb 03 06:53:47 net20 systemd-networkd[2608]: Setting '/proc/sys/net/ipv6/conf/ve-mail20/accept_ra' to '0'
Feb 03 06:53:47 net20 systemd-networkd[2608]: Setting '/proc/sys/net/ipv6/conf/ve-mail20/proxy_ndp' to '1'
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Setting nomaster
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Setting address genmode for link
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Failed to read sysctl property stable_secret: Input/output error
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Setting nomaster done.
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Setting address genmode done.
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: State changed: initialized -> configuring
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Bringing link up
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: IPv6 Proxy NDP Address: 2607:5300:203:5215::1
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Flags change: +UP +RUNNING
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Link UP
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Started LLDP.
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
Feb 03 06:53:47 net20 systemd-networkd[2608]: ve-mail20: IPv6 Proxy NDP Address: 2607:5300:203:5215::1
Feb 03 06:53:48 net20 systemd-networkd[2608]: ve-mail20: Flags change: -RUNNING
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: boot, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Flags change: +LOWER_UP +RUNNING
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Gained carrier
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): static addresses are not configured.
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): static addresses are not configured.
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Configuring route: dst: 66.70.129.137/32, src: n/a, gw: n/a, prefsrc: n/a, scope: link, table: main, proto: static, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Configuring route: dst: 2607:5300:203:5215:1::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Setting routes
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Received remembered route: dst: 66.70.129.137/32, src: n/a, gw: n/a, prefsrc: n/a, scope: link, table: main, proto: static, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Received remembered route: dst: 2607:5300:203:5215:1::1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: Routes set
Feb 03 06:54:00 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): IPv6LL is not configured.
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Remembering foreign address: fe80::5458:16ff:fed0:d50f/64 (valid forever)
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): IPv6LL is not configured.
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Gained IPv6LL
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): dynamic addresses or routes are not configured.
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Discovering IPv6 routers
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Remembering route: dst: fe80::5458:16ff:fed0:d50f/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
Feb 03 06:54:02 net20 systemd-networkd[2608]: ve-mail20: Remembering route: dst: fe80::/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: anycast
Feb 03 06:54:14 net20 systemd-networkd[2608]: ve-mail20: NDisc handler get timeout event
Feb 03 06:54:14 net20 systemd-networkd[2608]: ve-mail20: link_check_ready(): dhcp4:no dhcp6_addresses:no dhcp_routes:no dhcp_pd_addresses:no dhcp_pd_routes:no ndisc_addresses:yes ndisc_routes:yes
Feb 03 06:54:14 net20 systemd-networkd[2608]: ve-mail20: State changed: configuring -> configured
Feb 03 06:54:14 net20 systemd-networkd[2608]: ve-mail20: Dumping IPv6 Proxy NDP addresses
```

At 06:53:47 the interface has been fully configured and the proxy address is present. One second later the RUNNING flag on the interface is unset, and twelve seconds after that the LOWER_UP and RUNNING flags are set. After that point there are three more events which cause the addresses to be dumped, and in each case the address is gone.

I suspect this means that inside the kernel, when the RUNNING flag on an interface is unset, any proxy NDP addresses configured on that interface are removed. I'm not familiar enough with the networking code in the kernel to track down the exact location where this is happening, but it at least seems logical, and networkd appears to be doing some reconfiguration already when RUNNING is set on the interface again, so re-adding the proxy addresses at that point might be the right thing to do.

**Comment by kpfleming** [comment]
In case you are interested in seeing the address-dumping code, it's [here](https://github.com/kpfleming/systemd/blob/be68a4fec625d90c9ae9bfeddd08ebef965e00a0/src/network/networkd-ipv6-proxy-ndp.c#L15).
