### ISSUE TITLE
Improve systemd-nspawn performance

### ISSUE THREAD

**Issue by badrelmers** [systemd/systemd#18370]
**Is your feature request related to a problem? Please describe.**
CPU tasks take twice of the time it takes in docker, podman or qemu

**Describe the solution you'd like**
 I like the simplicity of nspawn so I hope we can achieve the same benchmark results as with docker, podman or qemu

**Describe alternatives you've considered**
 I made the following tests in docker , podman and qemu, and all of them are as quick as the baremetal machine:
first I disabled all the spectre/miltdown mitigations in the host kernel (and the qemu guest kernel in the case of qemu benchmark) using:
```bash
GRUB_CMDLINE_LINUX_DEFAULT=noibrs noibpb nopti nospectre_v2 nospectre_v1 l1tf=off nospec_store_bypass_disable no_stf_barrier mds=off tsx=on tsx_async_abort=off mitigations=off spectre_v2_user=off spec_store_bypass_disable=off nx_huge_pages=off kvm.nx_huge_pages=off kvm-intel.vmentry_l1d_flush=never srbds=off
```

then I used this benchmark test:
```bash
git clone https://github.com/tsuna/contextswitch
cd contextswitch
time make
```

I tested nspawn with super full privileges:
```bash
export SYSTEMD_NSPAWN_USE_CGNS=0
systemd-nspawn  --keep-unit --register=no --boot --capability=all --private-users=false --system-call-filter="@default @aio @basic-io @chown @clock @cpu-emulation @debug @file-system @io-event @ipc @keyring @memlock @module @mount @network-io @obsolete @privileged @process @raw-io @reboot @resources @setuid @signal @swap @sync @system-service @timer" --bind=/sys/fs/cgroup  --machine=testtt -D busterdir
```

 I tested podman with privileges too:
```bash
podman run --rm -it --privileged debian:10 bash
```

I tested docker with privileges too:
```bash
docker run --rm -it  --privileged  debian:10 bash
```

I tested qemu with:
```bash
qemu-system-x86_64 -name buster20210121210102 -m 2G -enable-kvm -cpu host -smp cores=4,threads=2,sockets=1 -object iothread,id=myio1 -device virtio-blk-pci,drive=mydisk0,iothread=myio1 -drive file=buster20210121210102.qcow2,if=none,id=mydisk0,format=qcow2,aio=native,cache=none
```

and here are the results:
```bash
# baremetal
real    0m12.998s

# nspawn
real    0m30.777s  <==== :(

# docker
real    0m15.127s

#podman
real    0m15.207s

# qemu without mitigations
real    0m15.979s
```

______________________________________________________
here is the full benchmark results:
```bash
# model name : Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
# 1 physical CPUs, 4 cores/CPU, 2 hardware threads/core = 8 hw threads total

# baremetal
-- No CPU affinity --
10000000 system calls in 448036009ns (44.8ns/syscall)
2000000 process context switches in 2005671664ns (1002.8ns/ctxsw)
2000000  thread context switches in 1986152606ns (993.1ns/ctxsw)
2000000  thread context switches in 174970680ns (87.5ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 413985383ns (41.4ns/syscall)
2000000 process context switches in 1863340451ns (931.7ns/ctxsw)
2000000  thread context switches in 1570550960ns (785.3ns/ctxsw)
2000000  thread context switches in 238062519ns (119.0ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 415118251ns (41.5ns/syscall)
2000000 process context switches in 1888062497ns (944.0ns/ctxsw)
2000000  thread context switches in 2043713610ns (1021.9ns/ctxsw)
2000000  thread context switches in 126207872ns (63.1ns/ctxsw)

real    0m12.998s
user    0m1.577s
sys     0m17.197s

__________________
# nspawn
-- No CPU affinity --
10000000 system calls in 3743325001ns (374.3ns/syscall)
2000000 process context switches in 3059850829ns (1529.9ns/ctxsw)
2000000  thread context switches in 2824211608ns (1412.1ns/ctxsw)
2000000  thread context switches in 331626517ns (165.8ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 3745385500ns (374.5ns/syscall)
2000000 process context switches in 3558904538ns (1779.5ns/ctxsw)
2000000  thread context switches in 3262669478ns (1631.3ns/ctxsw)
2000000  thread context switches in 438412824ns (219.2ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 3740509086ns (374.1ns/syscall)
2000000 process context switches in 3034727941ns (1517.4ns/ctxsw)
2000000  thread context switches in 2654637032ns (1327.3ns/ctxsw)
2000000  thread context switches in 332498452ns (166.2ns/ctxsw)

real    0m30.777s
user    0m1.302s
sys     0m38.252s

__________________
# docker
-- No CPU affinity --
10000000 system calls in 422997844ns (42.3ns/syscall)
2000000 process context switches in 2371566620ns (1185.8ns/ctxsw)
2000000  thread context switches in 2312299087ns (1156.1ns/ctxsw)
2000000  thread context switches in 151385343ns (75.7ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 418894209ns (41.9ns/syscall)
2000000 process context switches in 2007747079ns (1003.9ns/ctxsw)
2000000  thread context switches in 1774258687ns (887.1ns/ctxsw)
2000000  thread context switches in 237541191ns (118.8ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 417941741ns (41.8ns/syscall)
2000000 process context switches in 2333469063ns (1166.7ns/ctxsw)
2000000  thread context switches in 2342962835ns (1171.5ns/ctxsw)
2000000  thread context switches in 170803179ns (85.4ns/ctxsw)

real    0m15.127s
user    0m1.714s
sys     0m20.372s

__________________
# podman 
-- No CPU affinity --
10000000 system calls in 422140813ns (42.2ns/syscall)
2000000 process context switches in 2327258389ns (1163.6ns/ctxsw)
2000000  thread context switches in 2303935623ns (1152.0ns/ctxsw)
2000000  thread context switches in 173876523ns (86.9ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 414733022ns (41.5ns/syscall)
2000000 process context switches in 2056974355ns (1028.5ns/ctxsw)
2000000  thread context switches in 1764302475ns (882.2ns/ctxsw)
2000000  thread context switches in 238696271ns (119.3ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 414162948ns (41.4ns/syscall)
2000000 process context switches in 2357517631ns (1178.8ns/ctxsw)
2000000  thread context switches in 2341193272ns (1170.6ns/ctxsw)
2000000  thread context switches in 127445572ns (63.7ns/ctxsw)

real    0m15.207s
user    0m1.686s
sys     0m20.453s

__________________
# qemu
-- No CPU affinity --
10000000 system calls in 416050123ns (41.6ns/syscall)
2000000 process context switches in 2622501273ns (1311.3ns/ctxsw)
2000000  thread context switches in 2943208360ns (1471.6ns/ctxsw)
2000000  thread context switches in 75041713ns (37.5ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 410593796ns (41.1ns/syscall)
2000000 process context switches in 1746922645ns (873.5ns/ctxsw)
2000000  thread context switches in 1468297976ns (734.1ns/ctxsw)
2000000  thread context switches in 250822044ns (125.4ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 411155731ns (41.1ns/syscall)
2000000 process context switches in 2626956804ns (1313.5ns/ctxsw)
2000000  thread context switches in 2887268012ns (1443.6ns/ctxsw)
2000000  thread context switches in 75958384ns (38.0ns/ctxsw)

real    0m15.979s
user    0m3.079s
sys     0m22.188s

```

**Comment by refi64** [comment]
You're running nspawn with --boot so it's starting up its own systemd instance, and I'd be willing to bet you're including that time in your benchmark.

Container solutions generally don't incur any tangible extra CPU overhead, so differences you see are either going to be due to different base images or the generally small differences in startup time.

**Comment by badrelmers** [comment]
I was not testing the boot time and i'm not interested in that, did you see
the link posted? it is a benchmark done on a booted container;
nspawn is even slower than qemu!!
and tests was done on the same OS , for example for qemu and nspawn I used
debootstrap to create the base image with the same version.
thank you

**Comment by boucman** [comment]
would --notify-ready=no help in your case ? that's not exactly what notify ready is meant for, so I'm not sure it will make a difference, but give it a try...

**Comment by boucman** [comment]
and you use --boot on the systemd-nspawn command line... so you are testing the boot time. arn't you ?
I'm confused.

**Comment by badrelmers** [comment]
@boucman I tested with `--notify-ready=no`, but nothing changed.
I m not testing the boot time but the time it takes the benchmark of `context switch`. I boot because I need a `system container` with systemd (as with qemu), not an `application container` .

**Comment by gregkh** [comment]
Do not disable spectre mitigations in your host kernel, unless you _really_ know what you are doing.

That should not matter in your benchmarks, please leave those alone and try again.

And are you sure the context switch benchmark actually tests something worth testing, and does so correctly?

**Comment by gregkh** [comment]
The best way to benchmark this is to run `perf` to see what is happening differently.

**Comment by gregkh** [comment]
and, that benchmark looks really "fishy" to try to measure a context switch, that's not how to do it and the kernel developer community has already pointed this out in the past.

Please run a real benchmark that reflects your workload as that is the only way to properly measure this type of thing.

**Comment by gregkh** [comment]
If you are curious as to why that benchmark is not measuring the correct thing, see this response: https://www.realworldtech.com/forum/?threadid=189711&curpostid=189752

**Comment by badrelmers** [comment]
@gregkh thank you very much for the link, it seems that context switch is useless for testing.

I did a test with `perf` but `nspawn` is showing low performance again (with about 20000000 syscall ops/s bellow podman and docker!)

## **benchmark method:**
```bash
echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
apt update && apt-get -y -t buster-backports install linux-perf
perf_5.9 bench syscall all
```
## **create  a base image to use with nspawn and podman:**
```bash
debootstrap buster ./bbuster
```

## run the containers with:
**nspawn with --boot:**
```bash
export SYSTEMD_NSPAWN_USE_CGNS=0
systemd-nspawn  --keep-unit --register=no --boot --capability=all --private-users=false --system-call-filter="@default @aio @basic-io @chown @clock @cpu-emulation @debug @file-system @io-event @ipc @keyring @memlock @module @mount @network-io @obsolete @privileged @process @raw-io @reboot @resources @setuid @signal @swap @sync @system-service @timer" --bind=/sys/fs/cgroup  --machine=testtt -D ./bbusterboot
```
**nspawn without --boot**
```bash
systemd-nspawn  -D ./bbuster 
```
**podman**
```bash
#here I m using the same folder (base image) that I used with nspawn
podman create -it --privileged=true --systemd=always --rootfs  --name bbuster ./bbuster /sbin/init
podman start bbuster
podman exec -it bbuster bash
```
**docker**
```bash
docker run --rm -it  --privileged  debian:10 bash
```
**qemu**
```bash
qemu-system-x86_64 -m 2G -enable-kvm -cpu host -smp 8 -drive file=unstable20210121210102.qcow2,if=none,id=mydisk0,format=qcow2,aio=native,cache=none 
```

## **the results:**
|  |  ops/sec |
| --------------- | --------------- |
| baremetal | 24815373 |
| nspawn  --boot | 3167938 |
| nspawn  | 3122724 |
| podman --rootfs | 23906858 |
| docker | 23084878 |
| qemu | 2960285 |

can you shed some light on this results please?

**Comment by gregkh** [comment]
And where does `perf` say the extra time is being taken up when you compare the different runs?

**Comment by badrelmers** [comment]
@gregkh
the numbers in the table above are from `perf` output:
```bash
# perf_5.9 bench syscall all
   Running syscall/basic benchmark...
   Executed 10000000 getppid() calls
      Total time: 0.421 [sec]

        0.042171 usecs/op
        23712921 ops/sec    <=====
```
I did not understand what you mean by `the extra time` in your question. the numbers as you see here are calculated by perf, and after it makes 10000000 syscall it does calculate the time spent 
I hope that you clarify your question if I did not answer it properly

**Comment by gregkh** [comment]
I mean to look at the output of running perf when you run these tests and then using the output to see where time is being spent.  `perf record` is probably what you want to do here.

**Comment by poettering** [comment]
we probably install more seccomp filters than the others. which on current systemd versions you can set the SYSTEMD_SECCOMP=0 env var to turn them off. (ce8f6d478e3f6c6a313fb19615aa5029bb18f86d)

**Comment by badrelmers** [comment]
@gregkh thank you so much, it was solved, `nspawn` now is as quick as the baremetal host, `podman` and `docker`. I had only to use a `systemd v247+` and `SYSTEMD_SECCOMP`.
____________________________________________________________
# Details
I will describe the steps so new comers may benefit of this.

I used `perf record` as you told me:
```bash
# in the host do (this is necesary to see the dbg symbols from /proc/kallsyms)
export SYSTEMD_NSPAWN_API_VFS_WRITABLE=yes
# in the container
perf_5.9 record -a -g perf_5.9 bench syscall all
perf_5.9 report -n
````

the result:

![image](https://user-images.githubusercontent.com/40046489/106050079-276b7e00-60e7-11eb-96b4-cc994ed60cdd.png)

it seems that most time is spent in **___bpf_prog_run** 

so I did the [following](https://prototype-kernel.readthedocs.io/en/latest/bpf/troubleshooting.html) in the host
```bash
sysctl net/core/bpf_jit_enable=1
```

then the results were better and nspawn now improved from **3M ops/s** to **9M ops/s**.

but now a new function seems to spend a lot of time too: **__seccomp_filter**

![image](https://user-images.githubusercontent.com/40046489/106050863-f5a6e700-60e7-11eb-8faa-1fe7ec1191eb.png)

so I attempted to use the following as they told me in the [mail ](https://lists.freedesktop.org/archives/systemd-devel/2021-January/045890.html) list:
```bash
export SYSTEMD_SECCOMP=0
```

but it did not work, because this is a new variable added I think in systemd `v247`, but I was using systemd `v241 `of debian buster. So I installed `v247 `using the `debian backport`, and the problem was solved, now `nspawn ` is so quick as the baremetal host , doing **24669247 ops/sec**

**NB:**
if I use `SYSTEMD_SECCOMP=0` then I do not need to use `sysctl net/core/bpf_jit_enable=1`, I do not know why , it seems that disabling `seccomp` solves the problem of performance permanently

now even the `context switch` benchmark is as quick as the baremetal host:
```bash
model name : Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
1 physical CPUs, 4 cores/CPU, 2 hardware threads/core = 8 hw threads total
-- No CPU affinity --
10000000 system calls in 416906873ns (41.7ns/syscall)
2000000 process context switches in 2550940018ns (1275.5ns/ctxsw)
2000000  thread context switches in 2430690945ns (1215.3ns/ctxsw)
2000000  thread context switches in 174068483ns (87.0ns/ctxsw)
-- With CPU affinity --
10000000 system calls in 408690806ns (40.9ns/syscall)
2000000 process context switches in 2214310153ns (1107.2ns/ctxsw)
2000000  thread context switches in 1963588117ns (981.8ns/ctxsw)
2000000  thread context switches in 238885089ns (119.4ns/ctxsw)
-- With CPU affinity to CPU 0 --
10000000 system calls in 408912460ns (40.9ns/syscall)
2000000 process context switches in 2579114722ns (1289.6ns/ctxsw)
2000000  thread context switches in 2391113524ns (1195.6ns/ctxsw)
2000000  thread context switches in 170056463ns (85.0ns/ctxsw)

real    0m15.996s
user    0m1.600s
sys     0m21.688s
```

NB:
`sysbench`, `stress-ng`, `7z` and `geekbench`, they all have shown me that `nspawn` is as quick as the baremetal, `docker` `podman` and `qemu`, without using anything of this configs, so i don't think they are as reliable as `perf`. (I will not post the results of those apps to make this comment shorter)
_______________________________________________________
# Summary
To gain max performance with nspawn do:
```bash
debootstrap buster ./bbusterboot
#make sure you have systemd v247, so if you are using buster then let s add backport repository to the source list and install the new systemd
echo 'deb http://deb.debian.org/debian buster-backports main' >> ./bbusterboot/etc/apt/sources.list
# boot nspawn and do
apt update
apt-get install -t buster-backport systemd
# it is better to reboot here
```

```bash
#improve nspawn from 3M to 15M ops/s (this is relative to your computer) 
export SYSTEMD_SECCOMP=0
systemd-nspawn --capability=all --private-users=false -D ./bbusterboot --boot
```

if you want more performance, then add this to `/etc/default/grub` in the host:
but it is a **_dangerous_** step, as `gregkh` said, if you run a browser without ad's blocker or you run an untrusted code, then you should not do it; and even with an ad blocker it is not secure at all, because a lot of ad blockers are in fact some type of trojans, and a lot of known ad blockers was sold to companies doing bad things... so think twice before adding this to the grub.
```bash
# improve nspawn from 15M to 24M ops/s
GRUB_CMDLINE_LINUX_DEFAULT="noibrs noibpb nopti nospectre_v2 nospectre_v1 l1tf=off nospec_store_bypass_disable no_stf_barrier mds=off tsx=on tsx_async_abort=off mitigations=off spectre_v2_user=off spec_store_bypass_disable=off nx_huge_pages=off kvm.nx_huge_pages=off kvm-intel.vmentry_l1d_flush=never srbds=off"
````

**NB:**
Sometimes if I use nspawn without --boot then I use --boot again, then I cannot login with root. (I had read before a comment by `poettering` himself saying that it is a useless security method which should be removed...); so this is safe and will solve this problem:
```bash
echo "pts/0" >> ./bbusterboot/etc/securetty
```
that' s all.

Thank you very very much for all your help Sirs.

**Comment by poettering** [comment]
BTW, this bug/feature tracker is about upstream issues only, i.e. issues seen in the two most current systemd releases. The bug submission form tries to make that very clear to keep frustration low. v241 is super old, any issues regarding that should only be reported downstream, so that we can maximize the signal/noise ratio here, and don't get drowned in bug reports about long long addressed issues. Thank you for understanding.

Closing.

**Comment by yayoi-k** [comment]
@badrelmers How do you get "`export SYSTEMD_SECCOMP=0`" to take effect?  I've entered it on the host and restarted nspawn containers with machinectl however it seems seccomp filters as still applying:

~# grep -i seccomp /proc/5164/status
Seccomp:        2
Seccomp_filters:        30`
