### ISSUE TITLE
SetLocalRTC does not set system time if local_rtc is unchanged

### ISSUE THREAD

**Issue by hellow554** [systemd/systemd#18391]
Reading the dbus interface description of [`SetLocalRTC`](https://www.freedesktop.org/software/systemd/man/org.freedesktop.timedate1.html) it seems to me, that I can sync the system clock to the RTC clock, when I set the second argument (`fix_system`) to true and leave the rest to false.

I have a usecase, where we have a high resolution external RTC that I want my systime to sync with with the timedate1 dbus api.

But, according to https://github.com/systemd/systemd/blob/9a4fce2efc4f74aa69117f43aa9a6ce499f9a099/src/timedate/timedated.c#L728-L729 the function will early return, if the local_rtc field is unchanged.

Either this behavoir should be document or (better) it shouldn't be intercept it in any way, else I have no way to sync the system time to the RTC with timedated.

**Comment by yuwata** [comment]
Fix is waiting in #18771.
