### ISSUE TITLE
systemd-resolved 246 fails to resolve LAN names

### ISSUE THREAD

**Issue by TheHans255** [systemd/systemd#18398]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Pop_OS! 20.10

**Linux kernel version used** (`uname -a`)

 > `Linux my-machine 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > I expect to be able to resolve hostnames of the other devices on my LAN network for applications such as SSH. Other, non-Linux devices on my network are capable of doing this.

**Unexpected behaviour you saw**
 > When I attempt to resolve names on my Pop_OS! devices, I get the error "Temporary failure in name resolution". `nslookup my-other-machine` provides the following output:
> ```
> Server:		127.0.0.53
> Address:	127.0.0.53#53
> 
> ** server can't find my-other-machine: SERVFAIL
> ```
>
> Weirder still is that I can reverse lookup the expected IP address and get the name just fine (e.g. `nslookup 192.168.1.125`), get name resolution for my own machine (`nslookup my-machine`) and of course get name resolution to the Internet (`nslookup www.example.com`). I can even get expected DNS lookup if I query my router's DNS directly (e.g. `nslookup my-other-machine 192.168.1.1`).

**Steps to reproduce the problem**
 > 1. Have local network with at least two named devices, one of which on `systemd` 246 and `systemd-resolved` set up.
 > 2. On the device with `systemd` 246, nslookup the other device, or do another operation that requires name resolution.

**Comment by grawity** [comment]
Do you use a local domain for those hostnames (as in DHCP domain-search parameter), or do they just exist as single-label names in DNS?

**Comment by TheHans255** [comment]
> Do you use a local domain for those hostnames (as in DHCP domain-search parameter), or do they just exist as single-label names in DNS?

These are single-label names.

**Comment by pemensik** [comment]
Single-label names are resolved only by multicast local-network resolver protocol, as is llmnr or mdns. That is by decision of systemd maintainers. I think they have added some resolved.conf(8) option to allow resolving it via DNS protocol.

**Comment by TheHans255** [comment]
> Single-label names are resolved only by multicast local-network resolver protocol, as is llmnr or mdns. That is by decision of systemd maintainers. I think they have added some resolved.conf(8) option to allow resolving it via DNS protocol.

OK, that seems to have done the trick - in both of my Linux machines, both LLMNR and mDNS were off on the global context. I turned on LLMNR on both of them and now they can talk to each other by name! (Why the network settings in Gnome doesn't seem to have an option for this is beyond me...)

**Comment by pemensik** [comment]
mDNS is off by default maybe to let avahi-daemon serve it instead. It can do more features than systemd-resolved. It might help you to set common domain for your lan machines and use search <domain> to use it without writing the suffix every time.

**Comment by poettering** [comment]
Let's close this. This is a design decision for security, and is amply documented in the man page. And I don#t think we should change this.

**Comment by fermulator** [comment]
It's really a big failure of the systemd default configuration #13763.

**Comment by pemensik** [comment]
Security? What security? Do you expect multicast-only protocol resolution is more secure than unicast-only resolution to servers provided by the network? Especially if you push for DNS over TLS support, then *security* argument seems very wrong. It might be related to privacy, as it prevents leakage of single-names resolution to DNS. But if you trust your DNS on a trusted network, it would not be usually a problem. Non-working resolution of selected kinds of names is a problem on the other hand.
