### ISSUE TITLE
`machinectl import-fs ...` enques the job, but doesn't actually do anything

### ISSUE THREAD

**Issue by kcwitt** [systemd/systemd#18404]
**systemd version the issue has been seen with**
 > systemd v246.7-2.fc33 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)

**Used distribution**
 > Fedora 33 with btrfs filesystem

**Linux kernel version used** (`uname -a`)

 > `Linux localhost 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `machinectl import-fs ./fedora-33` does not import the directory into /var/lib/machines

**Unexpected behaviour you saw**
 > command output is "Enqueued transfer job 1. Press C-c to continue download in background.", but no files are transferred
> `machinectl list-transfers` output is "No Transfers."
> `machinectl list-images` output is "No Images."

**Steps to reproduce the problem**
> run the following in fedora
```shell
mkdir ./fedora-33
dnf install --releasever 33 --installroot "$(pwd)/fedora-33" systemd passwd dnf fedora-release
machinectl import-fs "$(pwd)/fedora-33"
```

**Comment by kcwitt** [comment]
Apparently this is a selinux policy issue because it works after `setenforce 0`.

So should it be reported here (ie. who supplies the policy for this? systemd or fedora?)?

Is it possible to at least include in systemd an error message for this case since the transfer failed? Currently there is no feedback that the transfer failed.

**Comment by poettering** [comment]
the selinux policy is maintained by the selinux maintainers of fedora, systemd has nothing to do with that.

is there anything in the logs about this? my educated guess is that the selinux already prohibits the log output prpoagation between the worker process that does the import and importd, that#s why you see nothing.

**Comment by kcwitt** [comment]
@poettering thanks for the feedback. I could not find anything in the logs. I will try and followup with the fedora selinux folks.
