### ISSUE TITLE
str_verscmp() or strverscmp() do not work with RC version

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#18403]
I had sd-boot with from `247~rc2`. When I tried to upgrade sd-boot with `247.2-2`, it cannot, as `strverscmp()` in `bootctl` wrongly detects that newer version is already installed.
Replacing with `str_verscmp()` does not help. See tests added in #18402.

Should we improve `str_verscmp()` to make it handle RC version gracefully?

**Comment by keszybz** [comment]
I think we have to. It should understand `~` and `^`: those symbols are used in rpm and deb versions.

**Comment by yuwata** [comment]
https://github.com/rpm-software-management/rpm/blob/ef3ea9c69b7e5eddc9ad22c1832773e12bba1cb3/rpmio/rpmvercmp.c
