### ISSUE TITLE
suppress end of line whitespace in table output

### ISSUE THREAD

**Issue by jaalto** [systemd/systemd#18415]
C.f https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980820

Please clean up the output of all systemd commands by removing extra
whitespaces at EOL ::

    $ timedatectl status | cat -vTE

                   Local time: Sat 2021-01-30 17:46:26 EET $
               Universal time: Sat 2021-01-30 15:46:26 UTC $
                     RTC time: Sat 2021-01-30 15:46:26     $
                    Time zone: Europe/Helsinki (EET, +0200)$
    System clock synchronized: yes                         $
                  NTP service: active                      $
              RTC in local TZ: no                          $

Debian policy shows ::

    systemd:
      Installed: 247.2-5

NOTE: The output was clean in previous versions ::

    $ timedatectl status | cat -vTE
          Local time: Sat 2021-01-30 17:46:21 EET$
      Universal time: Sat 2021-01-30 15:46:21 UTC$
            RTC time: Sat 2021-01-30 15:46:21$
           Time zone: Europe/Helsinki (EET, +0200)$
     Network time on: yes$
    NTP synchronized: yes$
     RTC in local TZ: no$

Debian policy shows ::

    systemd:
      Installed: 232-8

**Comment by poettering** [comment]
and how is this a problem?

**Comment by yuwata** [comment]
Fix is waiting in #18430.

**Comment by poettering** [comment]
btw, neither this bug report nor the upstream bug report contains any info why the existing behaviour should be considered a problem?

**Comment by jaalto** [comment]
"Why is this a problem?"

First of all, it's a standard de facto practise the EOL of the output is not cluttered with whitespace. This is how all Linux programs work by default. It's called "quality".

This behavior was   not present in previous versions of systemd commands
