### ISSUE TITLE
RFE: maybe also ship default, commented config files in /usr/, for admins to consult for systems that come up with empty /etc

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#18420]
I'm currently cleaning up the systemd implementation in dracut and splitting systemd into seperated modules, bringing in dbus-broker and some other stuff trying to get dracut back on track into the 21 century and *only* provide files that are used by modules in the initramfs to keep it as small as possible. 

As I have been doing so I have been noticing some random missing files which presumably is something that was forgotten ( yet at the same time looks intentional ) which makes it difficult to reflect in the module and presumably breaks Factory Reset, Stateless System, Reproducible Systems and Verifiable Systems concepts. 

To give latest an example of this I'm currently working on the systemd-coredump module for dracut and that module should...

Create the /var/lib/systemd/coredump
install /usr/lib/systemd/coredump.conf ( currently missing )
install /usr/lib/systemd/coredump.conf.d/* ( vendor overrite snippet)
install /usr/lib/sysctl.d/50-coredump.conf 
install /usr/lib/systemd/systemd-coredump
install /usr/lib/systemd/system/systemd-coredump.socket
install /usr/lib/systemd/system/systemd-coredump@.service
install /usr/lib/systemd/system/sockets.target.wants/systemd-coredump.socket

And for local user/adminstration configuration ( hostonly in dracut ) 
install /etc/systemd/coredump.conf ( administrators override, currently provide )
install /etc/systemd/coredump.conf.d/coredump.conf ( administrator snippets override)
install /etc/sysctl.d/50-coredump.conf ( adminstrator override )
install /etc/systemd/system/systemd-coredump.socket  ( administrators override )
install /etc/systemd/system/systemd-coredump.socket.d/*conf  ( administrators snippet(s) override )
install /etc/systemd/system/systemd-coredump@.service ( administrators override )
install /etc/systemd/system/systemd-coredump@.service.d/*.conf ( administrators snippet(s) override )
install /etc/systemd/system/sockets.target.wants/systemd-coredump.socket ( administrators override )
install /etc/systemd/system/sockets.target.wants/systemd-coredump.socket.d/*.conf ( administrators snippet(s) override )

Looking at the man page for coredump.conf 
"The default configuration is defined during compilation, so a configuration file is only needed when it is necessary to deviate from those defaults. By default, the configuration file in /etc/systemd/ contains commented out entries showing the defaults as a guide to the administrator. This file can be edited to create local overrides."

I argue that this is outright wrong approach since it breaks "Stateless System" and the correct approach for the coredump.conf file should always be created under /usr/lib/systemd followed by it being copied and or symlinked to /etc/systemd/coredump.conf if required which instead supports Factory Reset, Stateless System, Reproducible Systems, Verifiable Systems.

**Comment by poettering** [comment]
not sure i follow?

the default config files we drop in /etc are entirely redundant: all lines in them are commented, they only serve is helpful hint to the admin. if you delete them all the system will boot up exact the same way. 

We generally strive to require zero configuration, i.e. always have sane built-in defaults.

So I really don't get what this is about? why would shipping helpful, fully commented config files that have zero effect but contain comments useful to the admin stateless systems and stuff?

**Comment by johannbg** [comment]
"We require zero configuration, i.e. always have sane built-in defaults." 
Which is pretty sane approach and I'm not arguing against that. 
What I'm arguing for is that these sane build-in default should always exist as files ( with explanatory comments but not the default options commented out ) under /usr/lib/systemd and then either be copied or symbolic linked to /etc ( which also makes it consistent /etc/systemd implementation with type units that reside under /usr/lib/systemd ).

Which file is the administrator supposed to read if /etc does not exist, the non existent upstream/vendor file?

**Comment by poettering** [comment]
so far the idea was that you have two kind of systems:

1. "tinker" systems, where a local admin or config mgmt mucks with /etc/ manually or in a scripted fashion. In this case it makes sense to ave the default files there with comments, so that the admin and scripts can look at them, mangle them, process them.
2. "cattle" systems, which have no local admin and run with minimal config only. On systems like this you come up with empty /etc and /var, and no admin would every log in and try to analyze stuff. 

For case 1 we install the files in /etc, for case 2 we make sure that all our stuff can operate fine with /etc entirely empty, and no configuration files around.

You appear to be looking something in between: i.e. where you still have the config files around to consult, but they aren't in /etc. i.e. a "cattle" system you can still "tinker" with. This has been out of focus so far.

**Comment by johannbg** [comment]
Owners of system will always want to tinker with them regardless if's considered cattle or something else anyway the only thing you can reliably ensure that exist in all existing use cases that I'm aware of is /usr so it makes only sense that it is considered the source of truth for the rest of the filesystem so to speak, thus things should only be placed,installed,copied,moved or linked from there to other places on the filesystem ( or not ) depending on the use case right.

**Comment by johannbg** [comment]
systemctl edit could be extended to cover .conf files as in "systemctl edit systemd.conf" and eople/administrator directed to use that as the "go to" tool for editing type units, mounts and configuration and other thing that administrators are expect to be editing in the systemd ecosystem at the same time as the file get moved under /usr path

**Comment by johannbg** [comment]
@poettering on closer examination as far as I can tell this just a simply matter of altogether stop placing files under /etc and start placing them under /usr/share/factory/etc instead and use tmpfiles with L and C to link/copy those files to /etc/systemd instead. 

Extending systemctl edit to cover  basically any file that an administrator/use is expected to edit within systemd is another scope.
