### ISSUE TITLE
networkd: NextHop should not require Gateway= directive

### ISSUE THREAD

**Issue by zhangyoufu** [systemd/systemd#18446]
The `[NextHop]` Section of systemd.network configuration requires a `Gateway=` directive.

Point-to-point link may not have a gateway address and assumes the peer on the other end is the gateway.

`Gateway=` directive should not be mandatory. And a `Family=` directive would be required when `Gateway=` is missing.

**Comment by yuwata** [comment]
I've created #18447. If possible and you want, please test the PR. Thank you.

**Comment by zhangyoufu** [comment]
Is there any way to specify nhid for [Route] without using MultiPath?

**Comment by yuwata** [comment]
> Is there any way to specify nhid for [Route] without using MultiPath?

That is another RFE. I will try to add that. Could you suggest the format? What do you think about the following?
```
[NextHop]
Id=3
Gateway=...

[Route]
NextHopId=3
...
```

**Comment by zhangyoufu** [comment]
LGTM

I think it would be nice to have aliases(identifiers) for nhid. I didn’t find such functionality in iproute2. I have no idea if networkd should implement this kind of mapping. If both nhid and alias can be used by any chance, then `NextHop=` would be better than `NextHopId=`.

**Comment by yuwata** [comment]
Aliases?? Sorry could you elaborate more?

**Comment by yuwata** [comment]
`NextHopId=` support is also added in #18447.

**Comment by zhangyoufu** [comment]
> Aliases?? Sorry could you elaborate more?

Since #18256, I can use name instead of number to reference a route table in [Route] section. It would be nice to have similar feature for NextHop. (This RFE can be done in a separate PR.)

For example
```
[NextHop]
Id=1
Name=gateway-1
Gateway=192.168.0.1

[NextHop]
Id=2
Name=gateway-2
Gateway=192.168.0.2

[Route]
Table=table-1
Destination=192.0.2.0/24
NextHop=gateway-1

[Route]
Table=table-2
Destination=198.51.100.0/24
NextHop=gateway-2
```
`NextHop=` directive accept both numeric ids and defined names.
