### ISSUE TITLE
Misleading statement in the man page of logind.conf

### ISSUE THREAD

**Issue by piotr-dobrogost** [systemd/systemd#18458]
In the man page for logind.conf one reads the following

> The main configuration file is read before any of the configuration directories, and has the lowest precedence; entries in a file in any configuration directory override entries in the single configuration file.

and then later on this

> Files in /etc/ are reserved for the local administrator, who may use this logic to override the configuration files installed by vendor packages.

These statements seem to be contradictory as written as far as `/etc/systemd/logind.conf` is concerned; this file is inside `/etc/` but it can not be used to override vendor configuration according to the first statement. The latter statement should instead be
> Files in /etc/systemd/logind.conf.d/ ...

systemd 246 (v246.7-2.fc33)

**Comment by dev-harsh1998** [comment]
This should be done
