### ISSUE TITLE
systemd-boot cmdline single

### ISSUE THREAD

**Issue by Kunzol** [systemd/systemd#18456]
**systemd version the issue has been seen with**
 > seen in 241-7, but the code says the problem is in newer versions, too

**Used distribution**
 > Debian 10 Buster

**Linux kernel version used** (`uname -a`)
 > `Linux debianhost 5.4.94-050494-generic #202101301330 SMP Sat Jan 30 13:34:41 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > I think that the script "src/kernel-install/90-loaderentry.install" does not handle the special case if booted with
option "single".

**Unexpected behaviour you saw**
 > System boots to recovery (aka single user mode) all the time.

**Steps to reproduce the problem**
 > On bootup in the systemd-boot menu, edit the line and add "single", to get into the recovery (aka single
user mode).
> In recovery you just say "exit" or press ctrl-D. This will boot the system in normal mode (usually multi-user).
> BUT, in "/proc/cmdline" there is still the option "single" at the end of the line.
> Now install a kernel update or do "update-initramfs", which will update the "systemd-boot" loader-entries by running the
> kernel-install scripts including "90-loaderentry.install".
> The updated loader-entry will have the entry "single" under "options".
> On next reboot, the system will again go to recovery.
> At the end, you will never get rid of the option "single".
> The only way out is to create "/etc/kernel/cmdline" without the "single" in the line.
> I saw this in Debian 10 (buster), but did not see a change in the source of newer versions.

**Comment by poettering** [comment]
We can't possibly fix this: apparently "single" was a one-time thing for you, but it might not be for others. /proc/cmdline can't inform us about your intention with this.

generally, generating the kernel cmdline from /proc/cmdline is  a fallback only, and works for simple cases but not the general case. The correct place to configure your kernel cmdline is /etc/kernel/cmdline, there's no way around that...

**Comment by Kunzol** [comment]
I came to this because I thought about having a "rescue" menu entry in systemd-boot like with grub.
But the "framework" of systemd-boot is not (yet) as advanced as grub in this respect.

Using the systemd-boot editor to modify the boot process should always be a one-time thing. 
But I don't see a possibility to put the information about this editing somewhere, where it can be read after boot.

On the other side your argument about creating /etc/kernel/cmdline is valid, too. In grub it is the same (debian: /etc/default/grub), where the configuration is expected. Maybe /etc/kernel/cmdline should be created directly on first start of kernel-install. 

Thanks for the discussion.

**Comment by poettering** [comment]
Also see #18406
