### ISSUE TITLE
indefinite wait on boot when missing a Btrfs member device

### ISSUE THREAD

**Issue by cmurf** [systemd/systemd#18466]
systemd-247.2-3.fc34 (but has behaved this way for a long time)

Simple case of 2-device btrfs raid1, where one device is missing. The result is an indefinite wait during boot:

`[***   ] A start job is running for /dev/disk/by-uuid/cf9c9518-45d4-43d6-8a0a-294994c383fa (55min 40s / no limit)`

[btrfsbootfailjournal.txt](https://github.com/systemd/systemd/files/5923638/btrfsbootfailjournal.txt)

What should happen eventually is drop to a dracut shell. I think 2 minutes is reasonable.

**Comment by poettering** [comment]
Is this on encrypted media?

**Comment by poettering** [comment]
please provide the contents of /run/systemd/generator*/ when this happens. also please provide your fstab, and "systemd-analyze dump" output

**Comment by poettering** [comment]
(I think we are disabling timeouts for the root disk, since being dropped into a dracut prompt isn't much better than just waiting until the device shows up. but not sure, what we did there. @keszybz do you remember this?

**Comment by poettering** [comment]
Ah, right, dracut is responsible for this. Pretty sure dracut shouldn't do that though, but systemd's fstab generator...

https://github.com/dracutdevs/dracut/blob/master/modules.d/98dracut-systemd/rootfs-generator.sh#L12

Closing this here.
