### ISSUE TITLE
TEST-55-OOMD fails sporadically due to non-existent dbus service

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#18469]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

Several of the recent runs failed because of missing `dbus-org.freedesktop.oom1.service` in `TEST-56-OOMD`:

```
[   14.628829] kernel: audit: type=1130 audit(1612431027.616:98): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-56-testbloat comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   14.511995] testsuite-56.sh[232]: + grep /testsuite-56-workload.slice
[   14.515917] testsuite-56.sh[231]: + oomctl
[   14.595242] dbus-daemon[222]: [system] Activating via systemd: service name='org.freedesktop.oom1' unit='dbus-org.freedesktop.oom1.service' requested by ':1.2' (uid=0 pid=231 comm="oomctl ")
[   14.915309] dbus-daemon[222]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.oom1.service': Unit dbus-org.freedesktop.oom1.service not found.
[   14.915457] testsuite-56.sh[231]: Failed to dump context: Unit dbus-org.freedesktop.oom1.service not found.
```

Logs:
 * console: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/2521/artifact//systemd-centos-ci/artifacts_LhSnWH/vagrant-logs.gib/vagrant-arch-testsuite.PMn/TEST-56-OOMD_FAIL.log
 * journal: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/2521/artifact//systemd-centos-ci/artifacts_LhSnWH/vagrant-logs.gib/vagrant-arch-testsuite.PMn/TEST-56-OOMD/system.journal

I'm not quite sure what exactly is going wrong, but it's kind of weird that meson doesn't create the `dbus-*.service` symlink for the oomd service like it does for other services, e.g.:

logind:
```
...
Installing /build/src/login/org.freedesktop.login1.conf to /var/tmp/systemd-test-TEST-01-BASIC/root/usr/share/dbus-1/system.d
Installing /build/src/login/org.freedesktop.login1.service to /var/tmp/systemd-test-TEST-01-BASIC/root/usr/share/dbus-1/system-services
Installing /build/src/login/org.freedesktop.login1.policy to /var/tmp/systemd-test-TEST-01-BASIC/root/usr/share/polkit-1/actions
'/var/tmp/systemd-test-TEST-01-BASIC/root/usr/lib/systemd/system/dbus-org.freedesktop.login1.service' -> 'systemd-logind.service'
...
```

oomd:
```
Installing /build/src/oom/org.freedesktop.oom1.conf to /var/tmp/systemd-test-TEST-01-BASIC/root/usr/share/dbus-1/system.d
Installing /build/src/oom/org.freedesktop.oom1.service to /var/tmp/systemd-test-TEST-01-BASIC/root/usr/share/dbus-1/system-services
```

(taken from the image setup task: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/2521/artifact//systemd-centos-ci/artifacts_LhSnWH/vagrant-logs.gib/vagrant-arch-testsuite.PMn/setup-the-base-image_PASS.log)

but maybe that's how it's supposed to be :shrug: 

/cc @anitazha

**Comment by mrc0mmand** [comment]
@anitazha hey! Any update on this? It keeps happening and I'm not sure how serious the issue actually is.

Attaching logs from a recent fail, since the original links are now 404.
 * journal: [system.journal.tar.gz](https://github.com/systemd/systemd/files/6288284/system.journal.tar.gz)
 * console log: 
[TEST-55-OOMD_2_FAIL.log](https://github.com/systemd/systemd/files/6288287/TEST-55-OOMD_2_FAIL.log)

**Comment by anitazha** [comment]
Sorry for the delay @mrc0mmand. The PR I linked should fix the missing service problem.
