### ISSUE TITLE
Link specific DNS server is written to Global and does not get flushed on a network change

### ISSUE THREAD

**Issue by AndrewLipscomb** [systemd/systemd#18475]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > arch

**Linux kernel version used** (`uname -a`)

 > `5.10.7-arch1-1`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > Global DNS value to not change after DHCP Wifi network change. Using `networkd` and `resolved` alone with no other network management tooling. 

**Unexpected behaviour you saw**
 > The global DNS changes to match the DHCP-provided DNS from the previous network - then does not unset when the wifi changes. The global DNS will stay in use even though the local server it points to is unavailable
> As far as I can tell - Global DNS should only be getting changed from the user or configuration files - not on a network switch. 

**Steps to reproduce the problem**
 > Unsure as yet - still attempting to get a replicable-on-demand case. When I do have the case occur - restarting `systemd-resolved` returns DNS to the correct state. Replicating the same breaking interaction after that point does not cause an issue - so this may be racy or only occur after a longer period of running. 

Unsure as to whether this is `networkd` or `resolved` at fault - some guidance or documentation on how to make their interactions more visible would be appreciated. 

Relevant `.network` file for the radio involved
```
# /etc/systemd/network/20-wlan0.network 
[Match]
Name=wlan0

[Network]
DHCP=yes

[DHCP]
RouteMetric=4096
```

I am using `iwd` for the wifi link management

Relevant config for `resolved`.
```
[Resolve]
DNSSEC=false
```

`networkd` is all configuration defaults

**Comment by yuwata** [comment]
Please provide the result of `resolvectl`.

**Comment by poettering** [comment]
Closing due to lack of response.
