### ISSUE TITLE
dbus doesn't work if systemd was compiled with clang

### ISSUE THREAD

**Issue by protonesso** [systemd/systemd#18474]
**systemd version the issue has been seen with**
 > 247.3

**Used distribution**
 > Ataraxia (in nspawn container on Fedora and virtual machine)

**Linux kernel version used** (`uname -a`)

 > `Linux misaka 5.10.13-ataraxia #2 SMP PREEMPT Thu Feb 4 10:21:15 JST 2021 x86_64 GNU/Linux`

**Expected behaviour you didn't see**
 > Working dbus services like login1, home1, locale1

**Steps to reproduce the problem**
 > Recompile latest stable systemd (in my case it's 247.3) with LLVM/clang 11.0.1 (including compiler-rt, libunwind, libc++)

Logs:
 Cmdline: https://termbin.com/2blif
 Journal: https://termbin.com/24lj
 Analyze dump: https://termbin.com/uc7b
 Systemd test: https://termbin.com/hcua

**Comment by protonesso** [comment]
I can provide img file with automatic gpt discovery for nspawn if need, including strace and LLDB

**Comment by poettering** [comment]
i don't follow? what makes you think dbus doesn't work?

never heard that distro, have you pinged them?

**Comment by poettering** [comment]
the logs you show that logind worked great and acquired its bus name

**Comment by protonesso** [comment]
> never heard that distro, have you pinged them?

This is my playground, don't worry

**Comment by protonesso** [comment]
> the logs you show that logind worked great and acquired its bus name

it doesn't want to start and always tries to respawn

**Comment by protonesso** [comment]
![image](https://user-images.githubusercontent.com/47295761/106942067-0cdc7900-6767-11eb-9da1-43792a9f89c1.png)

**Comment by protonesso** [comment]
![image](https://user-images.githubusercontent.com/47295761/106944890-7d38c980-676a-11eb-8539-96cf51dc1743.png)

**Comment by protonesso** [comment]
UPDATE: if running service on my own then it works, but for some reason dbus can't activate it with systemd

**Comment by yuwata** [comment]
Please provide the journal logs when you invoke `hostnamectl`.

**Comment by protonesso** [comment]
```
Feb 04 19:45:20 misaka dbus-daemon[343]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.7' (uid=0 pid=359 comm="hostnamectl " label="kernel")
Feb 04 19:45:45 misaka dbus-daemon[343]: [system] Failed to activate service 'org.freedesktop.hostname1': timed out (service_start_timeout=25000ms)
```

**Comment by protonesso** [comment]
ok folks ive compiled systemd without optimizations, i will tell cflags which are dangerous for it

**Comment by protonesso** [comment]
clang is very weird compiler, I had `-Os` in CFLAGS and it caused the issue!
