### ISSUE TITLE
Allow to reload systemd-logind configuration

### ISSUE THREAD

**Issue by benjarobin** [systemd/systemd#18484]
**Is your feature request related to a problem? Please describe.**
After updating `/etc/systemd/logind.conf` there is no easy way to ask logind to reload the configuration.

**Describe the solution you'd like**
Is there a reason to not have `ExecReload=/bin/kill -HUP $MAINPID` in the service file?
This way the configuration can be easily reloaded by just executing `systemctl reload systemd-logind.service`

**Describe alternatives you've considered**
 - Sending SIGHUP manually to logind PID
 - Rebooting

**Comment by poettering** [comment]
You should be able to restart it...

**Comment by benjarobin** [comment]
I am using KDE+sddm, and personally I can restart systemd-logind without any problem.
This is a problem that was reported by another user. When restarting systemd-logind.service X is stopped.
But I can reproduce the problem in the following condition: Launch Xorg using startx, and restart systemd-logind from an xterm

Here the end of Xorg log:
```
[   558.069] (EE) 
Fatal server error:
[   558.070] (EE) systemd-logind disappeared (stopped/restarted?)
[   558.070] (EE) 
[   558.070] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[   558.070] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[   558.070] (EE) 
[   560.651] (EE) systemd-logind: ReleaseControl failed: You are not in control of this session
[   560.651] (EE) Server terminated with error (1). Closing log file.
```

**Comment by keszybz** [comment]
Restarting systemd-logind doesn't work properly. I was working on a patch last year, but didn't finish it (https://github.com/systemd/systemd/pull/17558). I hope to return to it soon.

**Comment by ChenQi1989** [comment]
@poettering There's a regression in this solution: https://github.com/systemd/systemd/issues/28016
This regression is not specific to logind, but to all notify-reload services that connect to dbus, e.g., systemd-networkd.
I'm not very familiar with the codes. Do you have some advice how to fix this issue?
