### ISSUE TITLE
When seat1 logout seat0 also get loged out with it.

### ISSUE THREAD

**Issue by devbapidey** [systemd/systemd#18491]
I found this bug with Debian testing. More info https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981867

**Comment by poettering** [comment]
[Canned reply follows] When submitting a GitHub issue, please fill in the submission form you find in the issue creation page, i.e. provide the requested details, such as distribution and systemd versions. We ask you these details to keep frustration at a minimum, both for us, and for you. If you don't provide this information it makes things needlessly difficult to help you.

Also, please keep in mind: this is a bug and feature request tracker only. If you have a support question, i.e. wonder how to use a feature, or can't figure out how to do something best, please use a different forum, such as the systemd mailing list. Also, do not file bug reports unless you can reproduce the issue with one of the two most recently released *upstream* version of systemd. For everything older, please contact your downstream distribution instead.

Thank you for understanding!

**Comment by devbapidey** [comment]
@poettering Nice Try.
I am currently using systemd v246.6 so I can clearly report here. I may not notice but that is what said from debian side. Before closing the issue did your read the link I provide?

As for your info
ubuntu 20.10
systemd 246.6
gnome 3.38.3
nvidia-driver-460

I hope that's all version info you need and do read the link I provided.

**Comment by poettering** [comment]
is thta the closed source nvidia driver?

as that driver doesn't use the driver model it's not supported for multi-seat. sorry!

**Comment by devbapidey** [comment]
ya! it's closed source. But open source also has same problem as I said previously.

**Comment by poettering** [comment]
I am not even sure what the bug is supposed to be. Please file a proper bug report, as requested, filling in the requested form and providing the requested data, explaining exactly what the issue is, and how we can reproduce it. And no closed source nvidia driver in the mix please.

Linking up bug reports between bug trackers is great, but just filing a bug here with nothing but a link to the debian bts is not a great idea, and we'll close that. We are not going to wade through other bug trackers to figure out the data we need.

**Comment by devbapidey** [comment]
Did you know multiseat?

**Comment by poettering** [comment]
I wrote the original multiseat support for systemd. Anyway, this is not a chat service. Let's end this here Please file a proper issue, if there's something left to fix.

**Comment by devbapidey** [comment]
Should I put a video demonstration for you? You are so hurry for closing the issue.

**Comment by poettering** [comment]
nope, i don't care for videos. I care for well-formed, comprehensive bug reports. Can't be that hard.

**Comment by devbapidey** [comment]
Well I did it. I think you are not reading. Can you say what or which part you don't understand?

**Comment by mrc0mmand** [comment]
> Well I did it. I think you are not reading. Can you say what or which part you don't understand?

No, you didn't. The original [issue template](https://github.com/systemd/systemd/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md) you completely skipped over serves the purpose of having all issues in somewhat consistent format with all important bits of information at one place, without the need to follow links to other discussions and parse the information there. So, please, fill in the issue template with the requested details, so we have something actionable here.

**Comment by devbapidey** [comment]
OK! I will fill it.
'is thta the closed source nvidia driver?' :- You misspelled that spelling. Did you notice that. It explained you are too hurry to not listen.

**Comment by devbapidey** [comment]
> is thta the closed source nvidia driver?
> 
> as that driver doesn't use the driver model it's not supported for multi-seat. sorry!

That one

**Comment by poettering** [comment]
@devbapidey you are not helping your case.

**Comment by devbapidey** [comment]
**systemd version the issue has been seen with**
 > …





**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…` 

Linux Vostro-3668 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > …
Intel CPU amd64 ( I know why intel also called amd )

**Expected behaviour you didn't see**
 > … When seat1 logout, just logout seat1. Why forcing to get log-out others seat.

**Unexpected behaviour you saw**
 > … Just logout who wants not the whole system.

**Steps to reproduce the problem**
 > … Just logout the seat1

**Comment by devbapidey** [comment]
> @devbapidey you are not helping your case.

Seems angry.

**Comment by devbapidey** [comment]
https://gitlab.gnome.org/GNOME/gdm/-/issues/721#note_1252332 it's a gdm problem @poettering
