### ISSUE TITLE
Missing builds

### ISSUE THREAD

**Issue by Neustradamus** [systemd/systemd#18497]
I think there is a problem, there are missing builds, we can see at this time 247.3 but not in:
- https://github.com/systemd/systemd/releases
- https://github.com/systemd/systemd/tags

Sources:
- https://packages.debian.org/sid/systemd
- https://archlinux.org/packages/core/x86_64/systemd/
- https://src.fedoraproject.org/rpms/systemd
- ...

Thanks in advance.

**Comment by boucman** [comment]
These are not systemd release, but systemd-stable releses.

These are tracked in a separate repository, see
https://github.com/systemd/systemd-stable
