### ISSUE TITLE
systemd-networkd assigning broadcast address to WireGuard interfaces

### ISSUE THREAD

**Issue by fl4co** [systemd/systemd#18492]
`systemd-networkd` supports adding WireGuard interfaces and assigning IP addresses to them. That's very nice.
However, when assigning an IP address to the interface, a broadcast address is added too, as showed by the `ip addr` command. This happens if, for example, a /24 subnet mask is specified, which is useful because the kernel will add a routing table for the subnet. Anyway, it's my understanding that WireGuard doesn't support broadcasting.

When using `wg-quick` provided by wireguard-tools a broadcast address is in fact not added to the interface. Would it be possible to make `systemd-networkd` not assign a broadcast address to WireGuard interfaces too?

I'm submitting this issue as a feature request and not as a bug because nothing is actually broken and it's only an "aesthetic" request. I understand if this is not high priority but would it be nice if it was fixed nonetheless.

**Comment by zhangyoufu** [comment]
You can configure your WireGuard interface with `/32` address, and a separate `[Route]` section for your subnet (omit `Gateway=`).

There is actually no subnet for L3 VPN like WireGuard. WireGuard simply looks up the allowed IPs to determine which peer should the packet be forwarded to.

**Comment by fl4co** [comment]
> You can configure your WireGuard interface with `/32` address, and a separate `[Route]` section for your subnet (omit `Gateway=`).
> 
> There is actually no subnet for WireGuard. WireGuard simply looks up the allowed IPs to determine which peer should the
> packet be forwarded to.

True, but it's just so much simpler to have a single auto-added route, especially if you plan to add and remove additional peers later. Otherwise you have to continually tweak your routes. Adding a /24 "subnet" makes the kernel five a single route that will work for all future peers.

**Comment by yuwata** [comment]
Maybe, we should extend the setting `Broadcast=no|auto|xxx.yyy.zzz.uuu`. Then, `Broadcast=no` solves your issue.
