### ISSUE TITLE
localectl, loginctl (sd-bus?) memory leak

### ISSUE THREAD

**Issue by crrodriguez** [systemd/systemd#185]
localectl
   System Locale: n/a

```
   VC Keymap: es
  X11 Layout: es
   X11 Model: pc105
 X11 Options: terminate:ctrl_alt_bksp
```
# 

==90==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 36 byte(s) in 4 object(s) allocated from:
    0 0x7f899be1b93f in strdup (/usr/lib64/libasan.so.2+0x6293f)
    1 0x555f493890c8 in free_and_strdup src/basic/util.c:5417
    2 0x555f4933605c in map_basic src/shared/bus-util.c:974
    3 0x555f493367c4 in bus_message_map_all_properties src/shared/bus-util.c:1084
    4 0x555f49336eca in bus_map_all_properties src/shared/bus-util.c:1171
    5 0x555f4932e07b in show_status src/locale/localectl.c:169
    6 0x555f493306a8 in localectl_main src/locale/localectl.c:657
    7 0x555f49330853 in main src/locale/localectl.c:678
    8 0x7f899b1ea8c4 in __libc_start_main (/lib64/libc.so.6+0x208c4)

SUMMARY: AddressSanitizer: 36 byte(s) leaked in 4 allocation(s).

A similar leak is also triggered with loginctl seat-status
# 

==83==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f6de112a93f in strdup (/usr/lib64/libasan.so.2+0x6293f)
    #1 0x559b8a00c356 in free_and_strdup src/basic/util.c:5417
    #2 0x559b89fa77d1 in map_basic src/shared/bus-util.c:974
    #3 0x559b89fa7f39 in bus_message_map_all_properties src/shared/bus-util.c:1084
    #4 0x559b89fa863f in bus_map_all_properties src/shared/bus-util.c:1171
    #5 0x559b89f92a0a in print_seat_status_info src/login/loginctl.c:614
    #6 0x559b89f93c6f in show_seat src/login/loginctl.c:810
    #7 0x559b8a010b2c in dispatch_verb src/basic/verbs.c:81
    #8 0x559b89f967a9 in loginctl_main src/login/loginctl.c:1358
    #9 0x559b89f9696c in main src/login/loginctl.c:1381
    #10 0x7f6ddffec8c4 in __libc_start_main (/lib64/libc.so.6+0x208c4)

I didn't spot anything wrong with the tools', I suspect the leak is in sd-bus library. it might be worth to take a look.

**Comment by teg** [comment]
This was fixed by #196.
