### ISSUE TITLE
Hangs during boot (arm64)

### ISSUE THREAD

**Issue by ab491** [systemd/systemd#18519]
**systemd version the issue has been seen with**
243
(dbus - 1.12.16)

**Used distribution**
Yocto (zeus)

**Linux kernel version used** (`uname -a`)

`Linux s32g274aevb 4.19.59-rt24+ged566620fe59 #1 SMP PREEMPT Thu Feb 4 16:00:50 UTC 2021 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
ARM64

**Unexpected behaviour you saw**
System hangs for 30 seconds during boot, but not always (~in 90% cases). 
1. The hang my occur 1-3 times during boot in different stages
2. In all of cases I see a delay (in logs) between forking (into  the child process) and die confirmation:

```
Dec 15 15:00:35 s32g274aevb systemd[1]: phc2sys.service: About to execute: /bin/sleep 1
Dec 15 15:00:35 s32g274aevb systemd[1]: phc2sys.service: Forked /bin/sleep as 162
Dec 15 15:00:35 s32g274aevb systemd[1]: phc2sys.service: Changed dead -> start-pre
...........
............
Dec 15 15:01:06 s32g274aevb systemd[1]: Child 162 (sleep) died (code=exited, status=0/SUCCESS)

```

(It's example with "sleep 1", but it also happens with another programs: mount, ip, udev, systemd-random-seed,...)

3. During this delay (15:00:35-15:01:06) the entire system (kernel, shells,...) works normally. I wrote a script ("top > log.txt" in cycle each second), CPU mostly is idle... 

```
Tue Dec 15 15:00:47 UTC 2020
Mem: 176580K used, 3327068K free, 8216K shrd, 2416K buff, 23440K cached
CPU:   4% usr   4% sys   0% nic  90% idle   0% io   0% irq   0% sirq
Load average: 0.46 0.10 0.03 1/87 156
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
   99     1 root     S     5916   0%   5% @lib/systemd/systemd-bootchart -r
  100     1 root     S    21464   1%   0% /lib/systemd/systemd-journald
    1     0 root     S    11392   0%   0% {systemd} /sbin/init
   97     1 messageb S     4392   0%   0% /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  113    98 root     S     3724   0%   0% /usr/bin/dbus-monitor --system --profile
   98     1 root     S     3500   0%   0% {print_top.sh} /bin/sh /usr/sbin/print_top.sh
  156    98 root     R     3208   0%   0% top -b -n 1
   61     2 root     IW       0   0%   0% [kworker/3:1-eve]
  101     1 root     Z        0   0%   0% [systemd-modules]
   11     2 root     SW       0   0%   0% [rcuc/0]
  103     1 root     Z        0   0%   0% [udevadm] 
..........

Tue Dec 15 15:00:48 UTC 2020
Mem: 177324K used, 3326324K free, 8216K shrd, 2416K buff, 23452K cached
CPU:   2% usr   0% sys   0% nic  97% idle   0% io   0% irq   0% sirq
Load average: 0.46 0.10 0.03 1/87 160
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
   99     1 root     S     6208   0%   2% @lib/systemd/systemd-bootchart -r
   26     2 root     SW       0   0%   1% [rcuc/2]
  100     1 root     S    21464   1%   0% /lib/systemd/systemd-journald
    1     0 root     S    11392   0%   0% {systemd} /sbin/init
   97     1 messageb S     4392   0%   0% /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  113    98 root     S     3724   0%   0% /usr/bin/dbus-monitor --system --profile
   98     1 root     S     3500   0%   0% {print_top.sh} /bin/sh /usr/sbin/print_top.sh
  160    98 root     R     3208   0%   0% top -b -n 1
   61     2 root     IW       0   0%   0% [kworker/3:1-mm_]
  101     1 root     Z        0   0%   0% [systemd-modules]
   11     2 root     SW       0   0%   0% [rcuc/0]
  103     1 root     Z        0   0%   0% [udevadm]
   20     2 root     SW       0   0%   0% [rcuc/1]
   74     2 root     IW<      0   0%   0% [kworker/2:1H-kb]
   12     2 root     IW       0   0%   0% [rcu_preempt]
```

4. I tried to run systemctl list-jobs in parallel with top - it hangs... until 15:01:36

5. Sometimes I see in log next message (but seems it's not related to root cause. System hangs with and without such notification):
```
Dec 15 15:01:36 s32g274aevb dbus-daemon[157]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30015ms)
```

Some information is attached:

journalctl --no-pager >/var/log.txt 
systemd-analyze --no-pager dump >/var/dump.txt 
systemd-analyze plot >/var/bootup.svg
.config (kernel)
log (serial console)

[bootup.svg.zip](https://github.com/systemd/systemd/files/5951885/bootup.svg.zip)

[dump.txt](https://github.com/systemd/systemd/files/5951871/dump.txt)
[log.txt](https://github.com/systemd/systemd/files/5951872/log.txt)

![bootup](https://user-images.githubusercontent.com/78802655/107375858-7f43b500-6ae9-11eb-8df8-27cc0d8c1906.jpg)
[kernel_config.txt](https://github.com/systemd/systemd/files/5951892/kernel_config.txt)

[log_serial.txt](https://github.com/systemd/systemd/files/5951922/log_serial.txt)

**Comment by poettering** [comment]
pid1 connecting to dbus-daemon seems to time out. Try to track that down. Get a backtrace on PID 1 when it hangs on the bus connection.

but this is not the right place for this. Please contact your downstream distro. we only track issues in the two most recent systemd upstream versions here, and the submission form should have made that very clear to keep frustration at a minimum. Closing hence, since 243 is really really old.

Before continuing, try to check things with a current systemd version.

**Comment by ab491** [comment]
Hello,
I updated systemd (to 246:)
```
root@s32g274aevb:~# systemctl --version
systemd 246 (246.9+)
+PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -ZSTD -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid

```
dbus also updated (to 1.12.20)
```
root@s32g274aevb:~# dbus-daemon --version
D-Bus Message Bus Daemon 1.12.20

```

kernel is the same (4.19)
```
Auto Linux BSP 1.0 (zeus) s32g274aevb (Linux 4.19.59-rt24+ged566620fe59 #1 SMP PREEMPT Thu Feb 4 16:00:50 UTC 2021) arm64
Startup finished in 2.147s (kernel) + 1min 4.652s (userspace) = 1min 6.799s multi-user.target reached after 1min 4.577s in userspace
```

**systemd still hangs 0-3 times (for 30 seconds) during boot.** 
updated logs:
[bootup.svg.zip](https://github.com/systemd/systemd/files/5988991/bootup.svg.zip)
[dump.txt](https://github.com/systemd/systemd/files/5988993/dump.txt)
[log.txt](https://github.com/systemd/systemd/files/5988994/log.txt)
[serial_tty.log](https://github.com/systemd/systemd/files/5988995/serial_tty.log)


I also debugged the previous version of systemd (243). 

It hangs in 2 functions (in systemd[1]):
manager_dispatch_run_queue
manager_dispatch_sigchld

But not always, and not clear why. 
Any hints are highly appreciated.

thnx.

**Comment by poettering** [comment]
> manager_dispatch_run_queue
> manager_dispatch_sigchld

provide a proper backtrace maybe. gdb bt with debug symbols.

last thing in the log shows some clock jump think. maybe if you turn off that PTP service it goes away?

**Comment by ab491** [comment]
_>>provide a proper backtrace maybe. gdb bt with debug symbols._
could you point me some manual how to correctly start systemd under gdb? 
I can put "gdb /lib/system/systemd" into /sbin/init, and (probably) gdb will start.. but systemd will have PID != 1.. not sure if it's correct for boot debugging.

_>>last thing in the log shows some clock jump think. maybe if you turn off that PTP service it goes away?_
It does not helps. Hang occures before ptp-service activation

**Comment by jetm** [comment]
@ab491 I am getting the same problem with a similar SW/HW setup. Did you manage not to get any more hangs with Yocto (zeus)?

**Comment by ab491** [comment]
hi @jetm, it was a problem with serial driver in BSP. After update it does not hangs anymore (zeus, kernel 4.19, systemd 243)

**Comment by ab491** [comment]
@jetm No, I did not upgrade kernel. 
I only update the serial driver. 
from:
https://source.codeaurora.org/external/autobsps32/linux/commit/drivers/tty/serial/fsl_linflexuart.c?h=alb/master&id=0a6875f43b6ea2222b31acb9a1885d85a6d011b8
to:
https://source.codeaurora.org/external/autobsps32/linux/commit/drivers/tty/serial/fsl_linflexuart.c?h=alb/master&id=400ae66ea0e7d85a653f495c5869c0ec58e141ba

**Comment by jetm** [comment]
@ab491 Thank you!
