### ISSUE TITLE
udev: watch handle may be deleted by other devices

### ISSUE THREAD

**Issue by gaoyi1988** [systemd/systemd#18525]
**systemd version the issue has been seen with**
 > 247

**Expected behaviour you didn't see**
 > Each disk or lvm device has a watch handle symlink in /run/udev/watch

**Unexpected behaviour you saw**
 > Some devices have no watch handle

**Steps to reproduce the problem**
 > The follow scripts can reproduce the problem
```
watch_org=$(ls -l /run/udev/watch | wc -l)

while true
do
        systemctl restart systemd-udevd
        sleep 3

        udevadm trigger
        udevadm settle
        watch_current=$(ls -l /run/udev/watch | wc -l)
        if [ $watch_org != $watch_current ]; then
                break
        fi
done
```

**Comment by gaoyi1988** [comment]
This is because it restore the watch handles in "systemctl restart systemd-udevd", but it not update the new info into db. And the problem is occured like follow(dx means device x, wdx -> dy means there has a symlink x->dy, dbx: y means device x's recorded watch handle is y in db):
1. wd4->d1(db1: 4) wd5->d2(db2: 5) wd6->d3(db3: 6)
2. After "systemctl restart systemd-udevd", the infos may like this:
    wd1->d1(db1: 4) wd2->d2(db2: 5) wd3->d3(db3: 6)
3. Trigger change event for d2, the infos will change to this:
    wd1->d1(db1: 4) wd4->d2(db2: 4) wd3->d3(db3: 6)
4. Trigger change event for d1, the problem will occur:
    "change event for d1" calls udev_watch_end to delete wd4, but at this time, wd4 is for d2.

PR https://github.com/systemd/systemd/pull/18524 can solve this problem.

**Comment by gaoyi1988** [comment]
https://github.com/systemd/systemd/pull/18524

**Comment by gaoyi1988** [comment]
Or update infos to db.

https://github.com/systemd/systemd/pull/18526

**Comment by gaoyi1988** [comment]
@yuwata @poettering How about this issue? Is the solution gave in PR https://github.com/systemd/systemd/pull/18524 ok? Or we must find another solution?

**Comment by gaoyi1988** [comment]
@yuwata

**Comment by gaoyi1988** [comment]
@yuwata 
What else can I do about this issue?
I think https://github.com/systemd/systemd/pull/18524 is a better solution. The symlink in /run/udev/watch can save watch infos. So I think there's no need to write watch infos to db. And watch infos saved in two places may casue inconsistency.

Based on PR https://github.com/systemd/systemd/pull/18524, watch infos in db seems no use, if the PR is ok, I can cleanup related codes.

**Comment by yuwata** [comment]
Sorry for late review. I will take a look.
