### ISSUE TITLE
When seat1 logout seat0 also get loged out with it.

### ISSUE THREAD

**Issue by devbapidey** [systemd/systemd#18533]
**systemd version the issue has been seen with**
 > … 246.6

**Used distribution**
 > … Ubuntu 20.04

**Linux kernel version used** (`uname -a`)

 > `…` Linux Vostro-3668 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > … amd64

**Expected behaviour you didn't see**
 > … logout only user who try to get logout. Not entire system

**Unexpected behaviour you saw**
 > … Whole system get logout when user1 logout

**Steps to reproduce the problem**
 > … create 2 seat with intel and nvidia setup -> install ubuntu 20.10 -> sudo apt update; sudo apt upgrade; sudo apt install nvidia-driver-610 or nothing (tested both)  -> create 2 seat with loginctl and attach 2 monitor  -> reboot -> login both -> then logout the user who useing nvidia.

**Comment by poettering** [comment]
Please provide relevant logs when this happens. ideally with debug logging turned on for systemd-logind. i.e. `systemctl edit systemd-logind` then add:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

then restart logind (or better reboot, i think some display servers have probs with logind being restarted)

**Comment by devbapidey** [comment]
should I provide journalctl details?

**Comment by poettering** [comment]
yes, pleas provide relevant logs

**Comment by devbapidey** [comment]
[logind-problem.txt](https://github.com/systemd/systemd/files/5958404/logind-problem.txt)
I hope it helps.

**Comment by devbapidey** [comment]
[logoutproblem.txt](https://github.com/systemd/systemd/files/5958464/logoutproblem.txt)

**Comment by poettering** [comment]
those logs only show one session terminating, for a user "kiran". 

Please provide the logs around the time the issue actually happens.

Your gnome-shell shows all kinds of javascript stacktraces to bad memory accesses. My educated guess is that gnome-shell has some memory corruption and then dies of that. It's probably best to track that down first.

**Comment by poettering** [comment]
That second log also only shows one user being used.

**Comment by devbapidey** [comment]
[loginctl-error-again.txt](https://github.com/systemd/systemd/files/5958512/loginctl-error-again.txt)
Hi I don't know how to give you the relevent logs. Please assist me on that.
Yes I only have 2 seats.
Here again I put some logs.

**Comment by poettering** [comment]
In those logs too only a single user "kiran" is mentioned.

You are aware that parallel logins on multiple graphical seats by the same user are not supported: gdm should refuse that. the per-user service manager is strictly per user, and hence doesn't allow mutiple graphical logins of the same user.

If you experience this with two sessions of two distinct users then the logs you pasted don't show that. Please provide more useful logs hence.

**Comment by devbapidey** [comment]
[loginctl-problem.txt](https://github.com/systemd/systemd/files/5958605/loginctl-problem.txt)

**Comment by devbapidey** [comment]
[loginctl-problem1.txt](https://github.com/systemd/systemd/files/5958709/loginctl-problem1.txt)

**Comment by poettering** [comment]
this only shows logind logs, and it just says that the users logged out, nothing more. My guess: your gnome-shell is aborting. please provide complete logs around the time this happens.

**Comment by devbapidey** [comment]
Ya, that also my guess. I see a gnome-session-binary error, it's in /var/crash should I provide it.

**Comment by poettering** [comment]
i do't know what /var/crash/ is.  But no, this is not the place to discuss GNOME crashes. Please contact your distro about this, or the GNOME upsream people.

Let's close this here, this really doesn't look like a systemd issue to me, but in GNOME.

**Comment by devbapidey** [comment]
Well of course, please review this log to make sure about it. I am not a expert in this, but you are, so maybe you can assist on this way.
[session-problem.txt](https://github.com/systemd/systemd/files/5973346/session-problem.txt)

**Comment by devbapidey** [comment]
Feb 10 19:24:25 bapi-Vostro-3668 gdm-Xorg-:0[712]: (EE) systemd-logind: failed to get session: PID 712 does not belong to any known session -- what it mean?

**Comment by devbapidey** [comment]
https://github.com/systemd/systemd/issues/18533

**Comment by devbapidey** [comment]
https://gitlab.gnome.org/GNOME/gdm/-/issues/675
