### ISSUE TITLE
Unit deps with escaping broken

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1856]
systemd does not boot properly since 3d793d2905 (bisected), as it cannot find the devices for the mount units. Reverting this commit restores proper behavior.

It appears the new code swallows all backslashes, so `by\x2dpartlabel` is loaded as `byx2dpartlabel`.

**Comment by filbranden** [comment]
Fixed by #1854.

**Comment by heftig** [comment]
Right, thanks.
