### ISSUE TITLE
In the Requirements section in the README, it should be written that CONFIG_NET is required only for Unix Sockets

### ISSUE THREAD

**Issue by heretoenhance** [systemd/systemd#18597]
**Is your feature request related to a problem? Please describe.**
I wanted to build a kernel with no network capabilities but saw that CONFIG_NET was required by systemd and thought it was not possible. But the only thing required is Unix Sockets.

**Describe the solution you'd like**

In the README file, REQUIREMENTS section, Kernel Config options section, add between parentheses after CONFIG_NET that the only flag required from that section is the Unix Sockets one.
I can make a PR if you want me to.

**The systemd version you checked that didn't have the feature you are asking for**

247.3

**Comment by bluca** [comment]
> I can make a PR if you want me to.

Yes, please

**Comment by heretoenhance** [comment]
Done: #18600
