### ISSUE TITLE
systemd-boot ignores stubs without VERSION_ID

### ISSUE THREAD

**Issue by Gigadoc2** [systemd/systemd#186]
systemd-boot displays only efi stubs containing a VERSION_ID field in their embedded os-release file, yet VERSION_ID is listed as an optional field in the manpage of os-release.

**Comment by kaysievers** [comment]
Yeah, sounds like VERSION_ID should not be optional. ID + VERSION_ID seems to the only sensible way to compose a machine-readable identifier.

**Comment by Gigadoc2** [comment]
But then what about rolling release distributions? They don't have a sensible value for this field.

Would it be prolematic to omit VERSION_ID if it is not set?

**Comment by kaysievers** [comment]
Well, even a rolling release would ideally carry some identifier in the os-release file. Be it from the repo package database at that time, or at least the date+time of the update.

At the moment, I'm personally not convinced that we should support omitting it, it needs more discussion.

**Comment by poettering** [comment]
I wonder if the code should use BUILD_ID if VERSION_ID is missing?
