### ISSUE TITLE
networkd regression: interfaces don't get DHCPv6 addresses any more

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#1866]
Today my "networkd" tests started failing again. IPv4 is fine, but IPv6 does not seem to get IP addresses from DHCP any more:

```
======================================================================
FAIL: test_coldplug_dhcp_ip6 (__main__.TestNetworkd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.3VEbpQ/build.CyP/systemd-227+upstream20151112/debian/tests/networkd", line 155, in test_coldplug_dhcp_ip6
    self.do_test(coldplug=True, ipv6=True)
  File "/tmp/adt-run.3VEbpQ/build.CyP/systemd-227+upstream20151112/debian/tests/networkd", line 101, in do_test
    self.assertRegex(out, b'inet6 2600::.* scope global .*dynamic')
AssertionError: Regex didn't match: b'inet6 2600::.* scope global .*dynamic' not found in b'6: test_eth42@router_eth42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000\n    inet6 fe80::b85e:66ff:feec:20bf/64 scope link \n       valid_lft forever preferred_lft forever\n'
```

(Same issue for the hotplug test). Yesterday's tests were still fine, so this is presumably commit 3b015d40c19d or something similar. I'll bisect and investigate further, and will come up with an easier reproducer.

For now this is to raise the "hold your horses on 228" flag to avoid releasing with a last-minute regression.

**Comment by martinpitt** [comment]
Reproducer:
- Create a veth pair `en0` (client side) vs. `router` (router side) and up the router:
  
  ```
  ip link add name en0 type veth peer name router
  ip a add 2600::1/64 dev router
  ip link set router up
  ```
- Start a DHCP server on the "router": This will run in the foreground for easy logging, so keep this in a separate shell/ssh:
  
  ```
  dnsmasq --log-queries --log-facility=- --conf-file=/dev/null --dhcp-leasefile=/tmp/leases \
  --bind-interfaces --interface=router --except-interface=lo  \
  --enable-ra --dhcp-range=2600::10,2600::20
  ```
- Configure client side with networkd and start it:
  
  ```
  cat <<EOF > /etc/systemd/network/en0.network 
  [Match]
  Name=en0
  [Network]
  DHCP=yes
  EOF
  
  systemctl start systemd-networkd
  ```

We expect this:

```
# ip a show dev en0
4: en0@router: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 2a:56:02:1b:c2:98 brd ff:ff:ff:ff:ff:ff
    inet6 2600::1c/64 scope global noprefixroute dynamic 
       valid_lft 3452sec preferred_lft 3452sec
    inet6 fe80::2856:2ff:fe1b:c298/64 scope link 
       valid_lft forever preferred_lft forever
```

Which works fine with 227 and upstream master until yesterday, but with today's version we instead get:

```
6: en0@router: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether be:7f:28:ae:91:46 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::bc7f:28ff:feae:9146/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

I. e. no address has been acquired, and nothing is logged in dnsmasq.

**Comment by martinpitt** [comment]
Indeed reverting commit 3b015d4, copying the updated `./systemd-networkd` into the VM, and restarting networkd makes this work again.

**Comment by thparamboll** [comment]
No idea if this helps but I have this patch locally for the new ndisc code:
https://paste.gnome.org/pmy0ezrcc
It is about nd_ra_flags_reserved and  ND_RA_FLAG_PREF which is also changed in 3b015d4 so maybe related.

**Comment by teg** [comment]
@thparamboll that should be unrelated (getting the wrong pref should not matter much, unless you have several routers on your link of course you might end up using the wrong one as your default). I'll make a patch for your issue in a separate PR so we can get that fixed before the release too though.

**Comment by teg** [comment]
@martinpitt I was not able to reproduce this for some reason (i'm using nspawn, with networkd from git on the inside, dnsmasq on the outside and the setup you outlined....). But could it be that PR #1882 fixes this?

**Comment by martinpitt** [comment]
Indeed the IPv6 tests succeed again with current master, and I can reproduce the error again with reverting commit a56a2048f9592, so I that did it, thanks!

Annoyingly, the IPv4 ones are now failing, `systemd-networkd-wait-online` is timing out. There's just no pleasing these friggin' tests!

I'll investigate more and file a separate issue about that.

**Comment by martinpitt** [comment]
> with networkd from git on the inside

Note that I didn't get that either with just copying systemd-networkd, I had to install the entire systemd package(s).

**Comment by martinpitt** [comment]
Sorry, it's still there, it just happens much less often. I still need to apply http://paste.ubuntu.com/13248170/ to make DHCPv6  work reliably. This doesn't fix the hanging/failing IPv4 tests yet (networkctl stays at `routable (configuring)` and never goes to `(configured)`

**Comment by martinpitt** [comment]
I tried this in nspawn with `--private-network` so that I can actually use the "ip" command. With the packages from current git master installed, running http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/networkd reproduces the bug still.

The only distro specific bit there is the path to s-n-wait-online, where you'd need to add a `/usr/` in front; otherwise this should just run as-is. (Note: run it under `LANG=C.UTF-8` as containers commonly don't have actual locales configured; you'll get `UnicodeDecodeError`s under `C`):

```
 while LANG=C.UTF-8 ./networkd TestNetworkd.test_hotplug_dhcp_ip6; do sleep 2; done
```

Just takes one or two iterations here.

**Comment by teg** [comment]
Thanks! I can reproduce with that test just fine, I'll get both issues fixed.

**Comment by martinpitt** [comment]
Oh, nice! Perhaps it's time to clean them up a bit for upstream and put them into git. Most of our downstream tests are rather distro specific, but the networkd and logind ones seem fairly generic.

BTW, off for the weekend now, I can continue investigating this on Monday.

**Comment by martinpitt** [comment]
For the records, PR #1932 fixes the DHCPv4 regression.

**Comment by martinpitt** [comment]
228 happened, so dropped release-critical and moved over to 229.

**Comment by martinpitt** [comment]
Worked around by commit 64feec9238f16a065548ba9eec0aa2ece0a41ff8, so closing for now. Thanks!
