### ISSUE TITLE
github actions bot labeler malfunctioning

### ISSUE THREAD

**Issue by vcaputo** [systemd/systemd#18671]
Commit https://github.com/systemd/systemd/commit/292420ce4b2ecac521d9016ed2ad99dabd8e5049 introduced .github/labeler.yml to automatically add labels to PRs, which is useful.

When these PRs receive forced pushes updating their commits, the labels are unhelpfully getting removed.  I haven't attempted to understand *why* that happens, but it's creating work for us undoing the removals if we want the labels to persist.

Maybe the cause is the forced push doesn't change anything in the directories mapping to the label getting removed, and the bot doesn't know to leave the labels be when that occurs, instead always synchronizing the set of labels to what the latest changset intersects.  I don't know, that's just gross speculation.

@jameerpathan111 do you have any idea why this is happening, and how to fix it?

Example: https://github.com/systemd/systemd/pull/18013

Note the github-actions bot removed the journal label after the force-push, 29 days later I restored the label.

If we can't address this I'm in favor of disabling the labeler.

**Comment by poettering** [comment]
yeah. it is fine if the labeler was purely additive, but removing labels is evil.

**Comment by jameerpathan111** [comment]
@vcaputo @poettering `sync-labels: false` (which is false by default) is not working. There is an open [PR](https://github.com/actions/labeler/pull/113) on [actions/labeler](https://github.com/actions/labeler/) to fix this issue. 
Found workaround for it as well, we need to add option `sync-labels: ""` in `.github/workflows/labeler.yml`

**Comment by vcaputo** [comment]
https://github.com/systemd/systemd/pull/18674 was merged so let's close this
