### ISSUE TITLE
Recent python commits break builds on old distros like Debian 9

### ISSUE THREAD

**Issue by vcaputo** [systemd/systemd#18708]
I often perform quick build tests on a Debian 9 system whenever I'm developing systemd patches, up until the following two commits this was relatively pain-free:
7857b6e8383f5debab9544ef3abb15a27830fafa
b0a336a66929ed2a146888178157bf1af5c8598c

It was only a matter of tweaking the minimum mount utils version in meson.build, the old python version was not a problem for running meson+ninja to at least run a quick compile test of changes.

I don't know if anyone cares enough about preserving this capability, but from where I'm sitting those small, seemingly cosmetic "modernizations" don't seem worthwhile.  I mostly just wanted to lodge a complaint and bring up that this is annoying someone who regularly contributes patches voluntarily.

**Comment by keszybz** [comment]
Sorry, I'm not a debian person. I don't know what version of Python Debian 9 has. In the commit I wrote that meson itself requires python3.6. Is that not the case for you?

**Comment by mbiebl** [comment]
https://tracker.debian.org/pkg/python3-defaults -> Debian 9 is oldstable, so it has python 3.5
