### ISSUE TITLE
DISCOVERABLE_PARTITIONS: Table hard to read

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#18706]
The left column in the table of the [The Discoverable Partitions Specification][1] is centered vertically, making it hard to map to the right side, as there is no big space between rows. It’d be great if the cell text would start at cell top.

[1]: https://systemd.io/DISCOVERABLE_PARTITIONS/

**Comment by keszybz** [comment]
Hmm, my patch doesn't seem to have worked. Not sure why.

**Comment by keszybz** [comment]
OK, it worked now. Apparently there's some cache. I think it looks much better ;)
