### ISSUE TITLE
Should not destroy application created cgroups

### ISSUE THREAD

**Issue by psz2036** [systemd/systemd#1872]
```
Systemd should not destroy application created cgroups. When commands
  systemctl daemon-reload
  systemctl start [anything]
are run, all cgroup tasks files are emptied. The above commands happen
regularly: on my Debian machine, daemon-reload seems to happen within
some "apt-get dist-upgrade" sequences, and "start anacron" happens
nightly. (Other systemd commands may also affect.)

To reproduce on a freshly-installed Debian (jessie) machine:
 - Run command
     dpkg-reconfigure libpam-runtime
   and de-select the
     [] Register user sessions in the systemd control group hierarchy
   option; then reboot.
 - Log in to the machine; probably not via GDM3 as that might not work
   at all; not via getty as then the issue will not show(?!!); but log
   in via XDM, or via telnetd or sshd.
 - Become root (log in as such, or use su).
 - As root, do commands:
     # Set things up
     mkdir /sys/fs/cgroup/cpu/mytest
     echo $$ > /sys/fs/cgroup/cpu/mytest/tasks
     # Check it is there
     grep . /sys/fs/cgroup/cpu/mytest/tasks
     # Do the systemd thing
     systemctl daemon-reload
     systemctl start anacron
     # See it gone
     grep . /sys/fs/cgroup/cpu/mytest/tasks

The step of configuring libpam-runtime causes pam_systemd.so to be
removed from /etc/pam.d/common-session. Noting that cron and sudo use
common-session-noninteractive that does not contain it anyway, or that
an sshd login with keys may bypass PAM, the issue may also occur on a
fully default Debian machine.

I propose the attached patch to avoid the issue. This patch works well
for me.

Maybe see also
  http://bugs.debian.org/803013

Cheers, Paul

Paul Szabo   psz@maths.usyd.edu.au   http://www.maths.usyd.edu.au/u/psz/
School of Mathematics and Statistics   University of Sydney    Australia
```

[psz-diff.txt](https://github.com/systemd/systemd/files/33455/psz-diff.txt)

**Comment by poettering** [comment]
Sorry, but systemd implements a single-writer cgroup logic (as requested by the kernel maintainers), and hence takes possesion of the whole tree. If you want your own cgroup tree to manage, use the "Delegate=yes" feature in a service or scope, but otherwise systemd is in exclusive control. 

Sorry, but multiple access to the cgroup tree is simply not supported.

**Comment by psz2036** [comment]
I see, not supported... fine. (NOT!)
If only the code would contain, besides assert(pto) and similar,
some assert(*pto) or assert(strlen(pto)) lines...

**Comment by martinpitt** [comment]
This sounds a bit similar to  http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/patches/cgroup-don-t-trim-cgroup-trees-created-by-someone-el.patch which is supposed to guard against that. This was proposed upstream for a while but rejected for a similar reason.

However, we currently only test it against empty cgroups: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/boot-and-services#n352 so I guess this needs to be extended.

**Comment by psz2036** [comment]
Seeing how my patch only handles the empty string, a case that should
never happen, it and similar checks should be adopted for robustness,
quite independently whether it has any obvious or demonstrable benefit.
And it does have a benefit!

Someone might track down why systemd passes an empty string around...
but sanity checks are useful anyway.

**Comment by alexbrand** [comment]
Is this related to https://bugzilla.redhat.com/show_bug.cgi?id=1139223?

@poettering Can you expand on the single-writer cgroup logic? I believe I am running into the bug linked above and want to better understand what is going on. Specifically, I am seeing tasks files of cgroup hierarchies outside systemd being emptied after some event that I haven't pinned down yet.

**Comment by psz2036** [comment]
I cannot tell whether this is related to redhat bug 1139223 as I have
Debian machines, no RedHat. But: you _should_ try my one-line patch...
and/or also look for further comments in Debian bug 803013 (both those
mentioned in my initial post of this thread).

**Comment by poettering** [comment]
See https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/

**Comment by alexbrand** [comment]
Thanks @poettering . So I assume PID 1 goes over the cgroup tree and migrates any process that is outside of systemd's cgroup tree into it? How does it choose the destination cgroup?

I have also noticed that processes started with `cgexec` will sometimes not be included in the specified cgroup. That is, the tasks file remains empty (or is emptied?) after starting a process with `cgexec`. This is also under circumstances that are not entirely clear to me.

**Comment by poettering** [comment]
@alexbrand well, systemd maintains a structure of the system in the name=systemd hierarchy, and whenever a service changes state, or a service property changes state we might bring the other hierarchies into sync with the name=systemd hierarchy again.

cgexec is generally not compatible with systemd. Don't mix it. The only place where 3rd party software may make changes to the hierarchy is in their own subtrees (i.e. in services and scopes where Delegate=yes is set) or in hierachies systemd doesn't manage at all. It's also somewhat OK to write to attributes in cgroups systemd manages, if systemd doesn't expose a knob for them yet. It's also fully Ok to read attributes from cgroups systemd manages any time.

**Comment by alexbrand** [comment]
@poettering Thanks. Is it expected for `cgexec` to fail silently and start the process without placing it in the specified cgroup? Or what exactly is happening in that case? Is there any log file where I could trace any of this?

**Comment by poettering** [comment]
@alexbrand i have no idea of cgexec really, I can't answer that.

You can turn on debug logging in systemd, it it provides you with more information, but the lowest level cgoup operations are not logged about then either.

**Comment by alexbrand** [comment]
@poettering I have isolated the issue with cgexec. It seems like there is some delta in the way systemd handles cgroups when the process is started from a `user.slice` vs a `system.slice`. I hope this is as an area where you can shed some light.

I am able to reproduce consistently using the following script:

```
#!/bin/bash

if [ ! -e /sys/fs/cgroup/cpu/test ]; then
  mkdir  /sys/fs/cgroup/cpu/test
fi

echo "Pre system.slice"
cgexec --sticky -g cpu:/test su cgtest -c "sleep 3" &
sleep 0.5

# PIDs show up in the tasks file as expected
cat /sys/fs/cgroup/cpu/test/tasks 

echo $$ > /sys/fs/cgroup/systemd/system.slice/tasks
sleep 3

echo "Post system.slice"
cgexec --sticky -g cpu:/test su cgtest -c "sleep 3" &
sleep 0.5

# PIDs do not show up in the task file
cat /sys/fs/cgroup/cpu/test/tasks
```

**Comment by poettering** [comment]
"cpu" is a cgroup controller managed by systemd. You may create subgroups in it only if you create your own service or scope unit with Delegate=yes set.

Or in other words: what you are doing is not supported. Sorry.

**Comment by alexbrand** [comment]
Gotcha. That makes sense!

I am wondering though why it works in the "Pre system.slice" section, but it doesn't after moving to "system.slice". Does the user.slice has delegation enabled by default, or something like that?
