### ISSUE TITLE
Small language ambiguity in systemd.unit manual

### ISSUE THREAD

**Issue by maoif** [systemd/systemd#18725]
In the manual for _systemd.unit_, in the second paragraph under section **Conditions and Asserts**, we have "...which causes the condition becomes a triggering condition.", which perhaps should to corrected to "...which causes the condition _to become_ a triggering condition."

And in the next sentence, "If at least one triggering condition is defined for a unit, then the unit will be executed if at least one of the triggering conditions apply and all of the non-triggering conditions..." all of the non-triggering conditions what?? Please consider elaborating this.

systemd version 247.3-1

**Comment by poettering** [comment]
I hope #18735 improves this for you?
