### ISSUE TITLE
Unified Kernel Images (EFI-STUB) crash when chain-loaded by FreeBSD loader

### ISSUE THREAD

**Issue by schreiberstein** [systemd/systemd#18733]
## AFFECTED COMPONENT
systemd-247/src/boot/efi/stub.c	(systemd EFI STUB used for unified kernel images)

## PROBLEM
A unified kernel image built with systemd's EFI STUB is currently **(systemd v247, FreeBSD 13 BETA3)** unable to be chainloaded by FreeBSD's native bootloader "loader".

## TARGET SYSTEM
I have confirmed this on a VMware virtual machine's UEFI environment.

## STEPS TO REPRODUCE

1. Prepare artifacts by running [reproduce_artifacts.sh] on a recent GNU/Linux machine (depends on bash, zstd, base64, gzip, objcopy, sha1sum)
2. Download latest FreeBSD 13 disc1 iso image (tested with BETA3)
3. Install FreeBSD 13 via UEFI mode (select "Guided ZFS" and "GPT" and enable SSH)
4. Boot into system
5. Copy both [unified-upstream.efi] and [unified-patched.efi] artifacts to the FreeBSD's [/boot/] folder via SSH
6. Reboot the machine
7. At loader prompt, press [3] to drop into loader shell
8. Execute the previously generated upstream unified kernel image by entering [chain /boot/unified-upstream.efi]
(Alternatively, one may extract the attached [freebsd13-boot.tar.gz] file and place its content onto a FAT32 partition, place the artifacts in the /boot folder, boot off it and follow the instructions starting from step 7.

The attached Bash script [reproduce_artifacts.sh] can be used to generate two different unified kernel images consisting of the Debian GNU/Linux installer kernel and ramdisk, one using the upstream stub and one using the patched stub that utilized the workaround described below. ([unified-upstream.efi] and [unified-patched.efi])
(The patched stub variant is stored in the shell file via base64 encoding.)

## EXPECTED BEHAVIOR
Unified kernel image with embedded Debian GNU/Linux installer starts properly.

## OBSERVED BEHAVIOR
After the loading process of the EFI binary completes, the system hangs completely.

## WORKAROUND
According to FreeBSD's manpage regarding UEFI, it is noted as caveat that "EFI environment variables are not supported by loader(8) or the kernel."
Source: https://www.freebsd.org/cgi/man.cgi?query=uefi&sektion=8&manpath=FreeBSD+13.0-current
This lead me to believe that the problem could be circumvented by removing practically all lines from systemd's [stub.c] that had to do with reading or setting EFI environment variables.
The attached patch [systemd-v247-efi-stub-freebsd-loader-workaround.patch] radically removes all the potentially offending lines, adds two convenient debug messages and finally allowed me to successfully chain-load unified kernel images via FreeBSD's loader. [unified-patched.efi]
This radical approach is obviously not acceptable to be incorporated into the upstream stub, given that there are significantly more users interested in proper EFI variables than in booting via the FreeBSD loader.

## APPLICATION (OFF-TOPIC)
I am developing a GNU/Linux based embedded system that consists of a single, self-contained (e.g. 500+ MB SquashFS ramdisk), highly compressed unified UEFI amd64 kernel image binary.
The embedded system utilizes its own storage / auto-provisioning software which relies heavily on OpenZFS.
Since OpenZFS is a first-class citizen in the FreeBSD world and other third-party bootloaders (GRUB, rEFInd, ...) appear to offer only limited ZFS support (+ problematic GPLv3 licensing), transplanting FreeBSD's bootloader and using it to chain-load unified kernel images seems like a reasonable and maintainable choice.
This approach enables the user to place unified kernel images on a (perhaps RAID-enabled) ZFS pool dataset and have them chain-loaded.
Compared to storing them directly on the FAT32 ESP partition, this ensures the integrity of the images in case of a sudden loss of power (e.g. during a software update), avoids tricky MDRAID/LVM based configurations and also removes the need to manually sync ESP partition content on multiple drives when RAID is not used.
I have not been able to find resources about people attempting to use FreeBSD's loader to conveniently and reliably boot their OpenZFS-based GNU/Linux machines, but I personally think it would be a great alternative compared to what is available right now.

## QUESTION
Since I have no experience in debugging UEFI execution yet, I would like to kindly ask if systemd upstream could make provisions to ensure that (perhaps less spec-conforming(?)) boot environments such as FreeBSD's loader are capable of booting unified kernel images.

Note: I have described this issue in such detail so that I could point the fine folks over at FreeBSD to this in case this is actually a bug on their side.

**Thank you very much.**

**Cheers,**
**schreiberstein**

## ATTACHMENTS

[patch_and_script.tar.gz](https://github.com/systemd/systemd/files/6023017/patch_and_script.tar.gz)
[freebsd13-boot.tar.gz](https://github.com/systemd/systemd/files/6023020/freebsd13-boot.tar.gz)

## SCREENSHOTS

**UPSTREAM EFI STUB:**
![SCREEN-UPSTREAM](https://user-images.githubusercontent.com/2147331/108729701-16b5f880-752b-11eb-8be7-8c1cb97acdee.PNG)

**PATCHED EFI STUB: (proceeds to boot kernel successfully)**
![SCREEN-PATCHED](https://user-images.githubusercontent.com/2147331/108729689-14539e80-752b-11eb-9af6-9812b997c599.PNG)

**Comment by poettering** [comment]
uh, what does freebsd actually load there? does it invoke the EFI binary as EFI binary? or does it invoke the kernel via the linux boot protocol?

our stub is only useful when invoked as EFI binary, since it's the EFI stub after all..

**Comment by schreiberstein** [comment]
> uh, what does freebsd actually load there? does it invoke the EFI binary as EFI binary? or does it invoke the kernel via the linux boot protocol?
> 
> our stub is only useful when invoked as EFI binary, since it's the EFI stub after all..

As far as I can see, it is loading the EFI binary. I can use the same command (chain) to load a regular EFI binary like shell.efi.

**Comment by poettering** [comment]
hmm, those message are supposed to come from our stub? not in our upstream version?

**Comment by poettering** [comment]
oh, you added them, i see

**Comment by poettering** [comment]
if you first load the efi shell and then the kernel binary, does it work then?

**Comment by poettering** [comment]
but quite frankly, i have no idea what freebsd does differently there, and why it wouldn't invoke our EFI binary...

**Comment by poettering** [comment]
might be something to contact the freebsd people over...

**Comment by schreiberstein** [comment]
> if you first load the efi shell and then the kernel binary, does it work then?

Sadly, this is impossible.
The FreeBSD loader does not seem to access ZFS via an integrated firmware driver, but rather does it internally.
When I drop into a UEFI shell, I can only see the regular, firmware supported filesystems (FS0:, the esp partition).

**Comment by schreiberstein** [comment]
> but quite frankly, i have no idea what freebsd does differently there, and why it wouldn't invoke our EFI binary...

Some of the EFI variable calls in the middle of the stub.c file seem to cause / reveal the problem.
Once they are deleted, the loader can chain-load the stub just fine and the kernel is usable. (See my patch in the ZIP)

**Comment by poettering** [comment]
> When I drop into a UEFI shell, I can only see the regular, firmware supported filesystems (FS0:, the esp partition).

Copy the EFI kernel into the ESP for testing purposes then?

**Comment by poettering** [comment]
> Some of the EFI variable calls in the middle of the stub.c file seem to cause / reveal the problem.
> Once they are deleted, the loader can chain-load the stub just fine and the kernel is usable. (See my patch in the .tar.gz)

Can you figure out which ones precisely?

Is this in SecureBoot mode? Or is SB disabled?

**Comment by schreiberstein** [comment]
> > When I drop into a UEFI shell, I can only see the regular, firmware supported filesystems (FS0:, the esp partition).
> 
> Copy the EFI kernel into the ESP for testing purposes then?

Yes, I have tested that. This works.
It only occurs when the unified-upstream.efi file is loaded directly by the FreeBSD loader.
The patched variant works in both environments, UEFI shell and FreeBSD loader.

Secureboot is disabled.

**Comment by poettering** [comment]
if none work: that's a pretty broken uefi environment. I don't think we can support that, sorry. EFI variables are pretty much the only thing that the stub writes. If you don't have those the stub is entirely pointless...

**Comment by poettering** [comment]
Seriously, this looks like something the freebsd people need to fix. if they break access to EFI variables for chain loaded EFI binaries, things are really broken, that's waaaay to integral to how EFI works, we can't work around that.

given that freebsd is open source, the same way as we are, and the bug is apparently pretty clearly in their camp not ours this looks like something they need to fix, not we work around (which we can't even if we wanted to). Please contact the freebsd people

**Comment by schreiberstein** [comment]
> Seriously, this looks like something the freebsd people need to fix. if they break access to EFI variables for chain loaded EFI binaries, things are really broken, that's waaaay to integral to how EFI works, we can't work around that.
> 
> given that freebsd is open source, the same way as we are, and the bug is apparently pretty clearly in their camp not ours this looks like something they need to fix, not we work around (which we can't even if we wanted to). Please contact the freebsd people

Alright. Thank you very much for your comment. I appreciate it.
I will contact them. I guess this problem could just be solved magically over some time as they implement proper EFI variable handling in their FreeBSD loader.

**Have a great day / night!**
**schreiberstein**

**Comment by poettering** [comment]
the comment on their man page looks weird. I think it's more about support for those variables in their own code... They say they are "environment variables", which they aren't really...

I'd still be curious if any variable access hangs, or just some

**Comment by schreiberstein** [comment]
> the comment on their man page looks weird. I think it's more about support for those variables in their own code... They say they are "environment variables", which they aren't really...
> 
> I'd still be curious if any variable access hangs, or just some

Do you have a better / more efficient idea than doing it manually like this? :
I could compile the stub several times, each time commenting out one more call to see WHEN it starts working again.

**Comment by schreiberstein** [comment]
And if this is the preferred method, can I speed up systemd compile time by just building THIS particular target? (the stub, that is) Sadly, I have been unable to find a way to exclude all the other targets from compilation. Excuse me in case this is a newbie question.

**Comment by poettering** [comment]
> > 
> 
> Do you have a better / more efficient idea than doing it manually like this? :
> I could compile the stub several times, each time commenting out one more call to see WHEN it starts working again.

Yeah, try bisection. It's what I'd do…

**Comment by schreiberstein** [comment]
> > And if this is the preferred method, can I speed up systemd compile time by just building THIS particular target? (the stub, that is) Sadly, I have been unable to find a way to exclude all the other targets from compilation. Excuse me in case this is a newbie question.
> 
> hmm? ninja will just rebuild what you change, and not rebuild what you don't.

I have a build system (like ArchLinux‘ makepkg) for said embedded system which extracts the systemd tree anew every time and I thought that I could make a shortcut and only compile the stub. You are right though. If the source directory remains the same, it will only compile changes. I can do it outside this build system for testing purposes.

**Comment by schreiberstein** [comment]
For sake of completeness, I include a reference to the FreeBSD Bugzilla report I made: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253770

**Comment by bsdimp** [comment]
FreeBSD does implement proper EFI variable handling. Any statements to the contrary are not correct. If there's something specific that's not implemented correctly, I'd love to hear about it.

Where did you find the statement that they weren't supported? I implemented that years ago and thought I'd removed all them.

We load an EFI binary and then execute it when chain booting. At that point, we're out of the picture entirely and the binary should be able to do whatever it does normally. I'm having trouble parsing out where it goes south, however, in this discussion. Can someone draw my attention to where that is?

**Comment by schreiberstein** [comment]
> FreeBSD does implement proper EFI variable handling. Any statements to the contrary are not correct. If there's something specific that's not implemented correctly, I'd love to hear about it.
> 
> Where did you find the statement that they weren't supported? I implemented that years ago and thought I'd removed all them.
> 
> We load an EFI binary and then execute it when chain booting. At that point, we're out of the picture entirely and the binary should be able to do whatever it does normally. I'm having trouble parsing out where it goes south, however, in this discussion. Can someone draw my attention to where that is?

Thank you for your quick response, Mr. Losh.
It is very good you removed the outdated caveat note, as you mentioned on the FreeBSD bugzilla thread. I am quite relieved that FreeBSD's loader does in fact support EFI variables, as that should come in handy for my project soon as well. Looking at the loader source code, I was confused because there clearly was some EFI variable handling going on, but I thought the manual took precedence.

I expect to narrow down the offending call / section in the systemd EFI stub code tomorrow by going through each of the ~5 efivar_get_raw calls or other parts that I purged in my temporary workaround. By then, there should be a clearer picture of what exactly goes wrong.

**Comment by bsdimp** [comment]
> I expect to narrow down the offending call / section in the systemd EFI stub code tomorrow by going through each of the ~5 efivar_get_raw calls or other parts that I purged in my temporary workaround. By then, there should be a clearer picture of what exactly goes wrong.

Great! I'm happy to help in any way I can. Please do keep me in the loop.

**Comment by schreiberstein** [comment]
**Quick info: I bisected the stub.c and can confirm that the "LoaderImageIdentifier" section is affected.**
**If only this part is commented out, the stub can be chainloaded by the FreeBSD loader without any problems.**

  94         /* if LoaderImageIdentifier is not set, assume the image with this stub was loaded directly from UEFI */
  95         /* if (efivar_get_raw(&loader_guid, L"LoaderImageIdentifier", NULL, NULL) != EFI_SUCCESS) { */
  96         /*         _cleanup_freepool_ CHAR16 *s; */
  97 
  98         /*         s = DevicePathToStr(loaded_image->FilePath); */
  99         /*         efivar_set(L"LoaderImageIdentifier", s, FALSE); */
 100         /* } */

**Comment by schreiberstein** [comment]
From my point of understanding, there would be two possible solutions for this:

**A) Extend FreeBSD's loader to set the variable read by loaded_image->FilePath**
**B) Extend systemd's stub to feature a NULL check for loaded_image->FilePath and to set a placeholder value if it is NULL**

Is that correct?
If so, what would be the preferred solution?

Cheers,
schreiberstein

**Comment by poettering** [comment]
So it appears FreeBSD doesn't set FilePath, probably because it doesn't implement a proper UEFI fs driver, and hence it can't. I think what they are doing is questionnable at least, given that the spec doesn't say the field may be NULL. But then again, they also don't say explicitly that it can't be NULL. Either way, we should probably handle this gracefully.

**Comment by poettering** [comment]
Fix in #18760. PTAL.

(I think FreeBSD should set FilePath though. I think our earlier interpretation ofthe spec that FilePath is not NULL isn't actually wrong, and FreeBSD should fill something in there. I figure they don't because they don't implement a proper fs driver, but they should then place something else there)

**Comment by schreiberstein** [comment]
> Fix in #18760. PTAL.
> 
> (I think FreeBSD should set FilePath though. I think our earlier interpretation ofthe spec that FilePath is not NULL isn't actually wrong, and FreeBSD should fill something in there. I figure they don't because they don't implement a proper fs driver, but they should then place something else there)

**Thank you very much, Mr. Poettering!**
Great to see this issue resolved in upstream **so** quickly.

I will proceed and update my bug report over at FreeBSD's bugzilla accordingly to keep this in sync, even though I suppose @bsdimp is receiving messages from this thread here as well.

Have a great day!

**Cheers,**
**schreiberstein**
