### ISSUE TITLE
systemd-networkd loops in gaining/losing carrier with dhcp-provided mtu for some nics

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#18738]
**systemd version the issue has been seen with**
 > latest git

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > interface configured for DHCPv4 with server-provided MTU comes up successfully

**Unexpected behaviour you saw**
 > interface remains in loop toggling between carrier up/down, constantly setting the mtu to dhcp-provided mtu and original mtu

**Steps to reproduce the problem**
 > This requires a nic that drops carrier when setting its mtu; the e1000e driver/hw is one such nic.
> 1) create a VM and configure to use e1000e emulation for its interface
> 2) connect that VM to a network that provides DHCPv4
> 3) configure the DHCPv4 server to provide a non-standard (i.e. not 1500) mtu
> 4) start up the test VM and check systemd-networkd logs
> 5) the logs will show systemd-networkd cycling endlessly between carrier up and down
> As this is a timing issue, it's possible the interface will eventually successfully come up.

When the problem is reproduced, systemd-networkd will show logs similar to:

> Feb 22 15:18:58 lp1881207-upstream systemd-networkd[992]: ens8: Gained carrier
> Feb 22 15:18:58 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv4 address 1.2.3.133/24 via 1.2.3.1
> Feb 22 15:18:59 lp1881207-upstream systemd-networkd[992]: ens8: Lost carrier
> Feb 22 15:18:59 lp1881207-upstream systemd-networkd[992]: ens8: DHCP lease lost
> Feb 22 15:18:59 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv6 lease lost
> Feb 22 15:19:01 lp1881207-upstream systemd-networkd[992]: ens8: Gained carrier
> Feb 22 15:19:01 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv4 address 1.2.3.133/24 via 1.2.3.1
> Feb 22 15:19:02 lp1881207-upstream systemd-networkd[992]: ens8: Lost carrier
> Feb 22 15:19:02 lp1881207-upstream systemd-networkd[992]: ens8: DHCP lease lost
> Feb 22 15:19:02 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv6 lease lost
> Feb 22 15:19:04 lp1881207-upstream systemd-networkd[992]: ens8: Gained carrier
> Feb 22 15:19:04 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv4 address 1.2.3.133/24 via 1.2.3.1
> Feb 22 15:19:05 lp1881207-upstream systemd-networkd[992]: ens8: Lost carrier
> Feb 22 15:19:05 lp1881207-upstream systemd-networkd[992]: ens8: DHCP lease lost
> Feb 22 15:19:05 lp1881207-upstream systemd-networkd[992]: ens8: DHCPv6 lease lost
> 

This is not a new problem, and the code does currently work around this by setting link->setting_mtu flag while the mtu netlink request is pending; however as soon as the kernel sends the netlink response, systemd-networkd clears the link->setting_mtu flag.

When using ip monitor to see the timing, it looks like the kernel first reports the MTU change, and then less than 1ms later the kernel reports the carrier loss. I'm not sure if this ordering (mtu change first, then carrier loss) is new behavior from the kernel, or if it's always been this way.

> root@lp1881207-upstream:~# ip -4 l show dev ens8 ; ip -4 -t monitor l dev ens8
> 3: ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
>     link/ether 52:54:00:15:2c:8a brd ff:ff:ff:ff:ff:ff
> Timestamp: Mon Feb 22 19:57:54 2021 1749 usec
> [LINK]3: ens8: <BROADCAST,MULTICAST,UP> mtu 9000 qdisc fq_codel state UP group default 
>     link/ether 52:54:00:15:2c:8a brd ff:ff:ff:ff:ff:ff
> Timestamp: Mon Feb 22 19:57:54 2021 3852 usec
> [LINK]3: ens8: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc fq_codel state DOWN group default 
>     link/ether 52:54:00:15:2c:8a brd ff:ff:ff:ff:ff:ff
> Timestamp: Mon Feb 22 19:57:56 2021 226630 usec
> [LINK]3: ens8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UP group default 
>     link/ether 52:54:00:15:2c:8a brd ff:ff:ff:ff:ff:ff
> 

After that monitor was started, I changed the mtu to 9000, and the ordering of the netlink events shows the mtu is set first, then the carrier is dropped.

**Comment by yuwata** [comment]
Hmm, we have fixed that about two years ago....

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/pull/9832#issuecomment-412430383

**Comment by yuwata** [comment]
@ddstreet Could you test #18746?

**Comment by ddstreet** [comment]
This does stop the up/down 'flapping', but it leaves the interface configured with the original mtu, not the mtu provided by the dhcp server.
