### ISSUE TITLE
systemd-udevd is not properly stopped if there is an aliased service

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1873]
In Debian, for historical reason, we ship a symlink 

```
# ls -la /lib/systemd/system/udev.service 
lrwxrwxrwx 1 root root 21 Nov 12 23:14 /lib/systemd/system/udev.service -> systemd-udevd.service
```

During the upgrade process, we mask udevd, so it is not started by the socket.
The sequence of events is

```
systemctl mask --runtime systemd-udevd
systemctl mask --runtime udev
sleep 1
systemctl unmask --runtime systemd-udevd
systemctl unmask --runtime udev
systemctl restart systemd-udevd
```

After that, I would expect only a single instance of systemd-udevd is running. But on each new restart an new systemd-udevd process is spawned.

To reproduce the issue, create the udev.service as above, then run the aforementioned commands.
This will result in something like this, 

```
 systemctl status systemd-udevd
● systemd-udevd.service - udev Kernel Device Manager
   Loaded: loaded (/lib/systemd/system/systemd-udevd.service; static; vendor preset: enabled)
   Active: active (running) since Fr 2015-11-13 02:49:04 CET; 1s ago
     Docs: man:systemd-udevd.service(8)
           man:udev(7)
 Main PID: 4866 (systemd-udevd)
   Status: "Processing..."
   CGroup: /system.slice/systemd-udevd.service
           ├─4424 /lib/systemd/systemd-udevd
           ├─4479 /lib/systemd/systemd-udevd
           ├─4530 /lib/systemd/systemd-udevd
           ├─4684 /lib/systemd/systemd-udevd
           ├─4771 /lib/systemd/systemd-udevd
           └─4866 /lib/systemd/systemd-udevd
```

This is a regression in git master and doesn't happen with v227.

Maybe something to look into before releasing v228.

**Comment by mbiebl** [comment]
Removing the regression tag, seems I can reproduce that with v227 as well

**Comment by poettering** [comment]
when activating a unit systemd won't crawl over entire /etc and check if the unit is masked under any of the symlinks possibly pointing to it, and it really shouldn't.

Or are you saying that the a mask by the name used for activation is ignored?

(Note that the right way to disable activation is to stop the the activating socket units. Doing this via masking is just wrong, as this implies multiple reload events)

**Comment by mbiebl** [comment]
@poettering well, the point is, that the masks have been removed again, before the restart is executed. So a restart should work fine at this point.
Somehow systemd get's in a confused state though.
I just broke it down to a minimal test case so you can reproduce the issue.

**Comment by keszybz** [comment]
I tested this now, and the issue appears to be fixed. (I'd guess that the symlink handling rework e8630e6952 might help, but it could be something earlier.) Please reopen if you can still reproduce.
