### ISSUE TITLE
networkd: make it easier to set associated interface IP to the local endpoint address of the tunnel

### ISSUE THREAD

**Issue by Tosainu** [systemd/systemd#18732]
**Is your feature request related to a problem? Please describe.**

My ISP supports DS-Lite for IPv4-over-IPv6 tunnel. To use it on my Linux-based router, I made the following systemd-networkd configuration files.

- `/etc/systemd/network/20-wan.network`
    ```ini
    [Match]
    Name=enp2s0f0

    [Network]
    IPv6AcceptRA=true
    Tunnel=dslite
    ```
- `/etc/systemd/network/30-dslite.netdev`
    ```ini
    [NetDev]
    Name=dslite
    Kind=ip6tnl

    [Tunnel]
    Mode=ipip6
    Local=<WAN (enp2s0f0) IP address configured by SLAAC>
    Remote=<DS-Lite server (AFTR, Address Family Transition Router) address>
    ```
- `/etc/systemd/network/30-dslite.network`
    ```ini
    [Match]
    Name=dslite

    [Route]
    Destination=0.0.0.0/0
    ```

It works fine but configuration files are confusing. The `Local=` field in the `.netdev` file requires the IP address configured by SLAAC.

**Describe the solution you'd like**

Introducing another special value to the `Local=` field to set the address of the associated interface automatically may be helpful in this case.

**The systemd version you checked that didn't have the feature you are asking for**

247.3

**Comment by lheckemann** [comment]
In my use case, the address I need used as the local address is assigned by `DHCPPrefixDelegation=true`. The PR fixing this doesn't provide a way to achieve that, right?

**Comment by lheckemann** [comment]
Opened #38211 to address my issue
