### ISSUE TITLE
systemd-nspawn loads OCI bundle rootfs relative to working directory insted of relative to OCI bundle

### ISSUE THREAD

**Issue by aylen384** [systemd/systemd#18758]
**systemd version the issue has been seen with**
 > 246.10

**Used distribution**
 > openSUSE Tumbleweed and SUSE Linux Enterprise Server 15 SP3

**Linux kernel version used** (`uname -a`)
 > `Linux athene 5.10.12-1-default #1 SMP Sat Jan 30 19:15:49 UTC 2021 (a3c8888) x86_64 x86_64 x86_64 GNU/Linux
`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemd-nspawn` loads the rootfs from the OCI bundle per as per [spec](https://github.com/opencontainers/runtime-spec/blob/master/config.md#root) relatively to the OCI bundle as configured in `config.json`.

**Unexpected behaviour you saw**
 > `systemd-nspawn` tries to load the OCI bundle root filesystem with the path configured in `config.json` but relative to the current working directory while the spec says: "_On POSIX platforms, path is either an absolute path or a relative path to the bundle._"

**Steps to reproduce the problem**
 > 
```sh
# create the OCI bundle
skopeo copy docker://busybox oci:busybox-oci/
oci-image-tool create --ref platform.os=linux ./busybox-oci/ /tmp/testbundle3/
# edit /tmp/testbundle3/ and set "args" to ["sh", "-c", "echo Hello World!"]
```
```
athene:~ # l /tmp/testbundle3/
insgesamt 4
drwxr-x---  3 dheidler users   80 23. Feb 13:23 ./
drwxrwxrwt 28 root     root  1040 23. Feb 13:15 ../
-rw-r--r--  1 dheidler users  239 23. Feb 10:44 config.json
drwxr-x--- 13 dheidler users  280 23. Feb 10:44 rootfs/
athene:~ # cat /tmp/testbundle3/config.json 
{"ociVersion":"1.0.0","process":{"terminal":true,"user":{"uid":0,"gid":0},"args":["sh", "-c", "echo Hello World!"],"env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"cwd":"/"},"root":{"path":"rootfs"},"linux":{}}
```

```sh
# failed attempt with PWD=/root/ 
athene:~ # systemd-nspawn --oci-bundle=/tmp/testbundle3 
Failed to resolve path rootfs: No such file or directory
```

```sh
# successfull attempt with PWD=/tmp/testbundle3
athene:~ # cd /tmp/testbundle3/
athene:/tmp/testbundle3 # systemd-nspawn --oci-bundle=/tmp/testbundle3 
Spawning container rootfs on /tmp/testbundle3/rootfs.
Press ^] three times within 1s to kill container.
Hello World!
Container rootfs exited successfully.
athene:/tmp/testbundle3 # 
```

Downstream bug report: https://bugzilla.suse.com/show_bug.cgi?id=1182598

**Comment by poettering** [comment]
Already fixed by 089cd8b34b5732e57321c92c16382dc8366faa42
