### ISSUE TITLE
kernel-install is now installed in /usr/share/systemd

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#18754]
Version: 248~rc1

Trying to build the latest rc, I noticed that `kernel-install` is now installed as `/usr/share/systemd/kernel-install`
```
$ meson --version
0.56.2
```
This is probably a result of 5ffa2eaa541b718122a3422e911ef95f4c9981d7

**Comment by mbiebl** [comment]
I assume the default  for `install_data` is datadir and not bindir.

**Comment by yuwata** [comment]
Fix is waiting in #18755.
