### ISSUE TITLE
systemd-boot: Add option to change menu timeout in bootctl

### ISSUE THREAD

**Issue by der-eismann** [systemd/systemd#18766]
**Is your feature request related to a problem? Please describe.**
It seems I accidentally increased the timeout in the boot menu to 301 seconds, I probably pressed `t` too much while booting or something similar. Now there is no (easy) way to remove this from a running system, working with `efivar` for a beginner is tricky since it's exporting hex code.

**Describe the solution you'd like**
Show the timeout in `bootctl status` and make it possible to change it since systemd-boot already has access to efi vars. Something like
```
$ bootctl status
...
Current Boot Loader:
      Product: systemd-boot v246.6-3.fc33
      Boot menu timeout: 30 seconds
...

$ bootctl set-timeout 5
```

**Describe alternatives you've considered**
None

**The systemd version you checked that didn't have the feature you are asking for**
v246.6

**Comment by vbortnikov** [comment]
I have another problem.
Probably, after an update, my systemd-boot 247.3-1-arch does not recognize the "timeout" at all.
Bootctl reports error:
"/boot/loader/entries/arch.conf:2: Unknown line "timeout", ignoring."
The line number is always added by one (in this case "timeout" was placed in the first line)
The default value is used when booting.
It was a working configuration.

**Comment by poettering** [comment]
@vbortnikov please do not hijack existing bug reports with unrelated questions. That just generates noise, and is considered very unfriendly by the people who look after the bug trackers.
