### ISSUE TITLE
networkd-test.py fails when run under LXC

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#18795]
Version: 248~rc2
OS: Debian Sid

Runnning the networkd-test.py test inside an LXC container fails with 248~rc2. It  works when run with qemu.
Downgrading to v247 fixes the issue (thus marked as regression).
So I ran a git bisect, which points at ddc155b2fd7807cda088c437dc836eebbcf79cea as the first faulty commit.

Full log from the test run is attached:
[log.txt](https://github.com/systemd/systemd/files/6041704/log.txt)

@topimiettinen , @brauner any ideas?

Do we have a CI which runs the test suite under  LXC? If not, would it be a good idea to do so?

**Comment by mbiebl** [comment]
I reverted ddc155b2fd7807cda088c437dc836eebbcf79cea on top of 248~rc2 and the test suite passed.

**Comment by bluca** [comment]
semaphore-ci runs under LXC: https://github.com/systemd/systemd/blob/main/.semaphore/semaphore-runner.sh

Can you see any obvious differences in options/settings used?

**Comment by bluca** [comment]
The bisected commit is strange - as far as I can see, it's default to off and shouldn't have any effect, so can't tell what the issue is on first pass

**Comment by mbiebl** [comment]
Yeah, I'm puzzled by the commit as well.
Semaphore-ci runs lxc inside docker?

**Comment by mbiebl** [comment]
findmnt dump from inside the lxc container when running the test
```
TARGET                               SOURCE               FSTYPE    OPTIONS
/                                    /dev/sda6[/var/lib/lxc/autopkgtest-lxc-lncvfx/rootfs]
│                                                         ext4      rw,relatime,errors=remount-ro
├─/run                               tmpfs                tmpfs     rw,nosuid,nodev,size=3254948k,nr_inodes=819200,mode=755
│ ├─/run/lock                        tmpfs                tmpfs     rw,nosuid,nodev,noexec,relatime,size=5120k
│ ├─/run/user/0                      tmpfs                tmpfs     rw,nosuid,nodev,relatime,size=1627472k,nr_inodes=406868,mode=700
│ └─/run/systemd/netif               none                 tmpfs     rw,relatime
├─/dev                               none                 tmpfs     rw,relatime,size=492k,mode=755
│ ├─/dev/pts                         devpts               devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/ptmx                        devpts[/ptmx]        devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/tty1                        devpts[/0]           devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/tty2                        devpts[/1]           devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/tty3                        devpts[/2]           devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/tty4                        devpts[/3]           devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666,max=1024
│ ├─/dev/shm                         tmpfs                tmpfs     rw,nosuid,nodev
│ ├─/dev/hugepages                   hugetlbfs            hugetlbfs rw,relatime,pagesize=2M
│ ├─/dev/mqueue                      mqueue               mqueue    rw,nosuid,nodev,noexec,relatime
│ ├─/dev/console                     devpts[/4]           devpts    rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ ├─/dev/.lxc/proc                   proc                 proc      rw,relatime
│ └─/dev/.lxc/sys                    sys                  sysfs     rw,relatime
├─/proc                              proc                 proc      rw,nosuid,nodev,noexec,relatime
│ ├─/proc/sys                        proc[/sys]           proc      ro,nosuid,nodev,noexec,relatime
│ │ └─/proc/sys/kernel/random/boot_id
│ │                                  none[/.lxc-boot-id]  tmpfs     ro,nosuid,nodev,noexec,relatime,size=492k,mode=755
│ └─/proc/sysrq-trigger              proc[/sysrq-trigger] proc      ro,nosuid,nodev,noexec,relatime
├─/sys                               sysfs                sysfs     rw,nosuid,nodev,noexec,relatime
│ └─/sys                             sysfs                sysfs     ro,nosuid,nodev,noexec,relatime
│   ├─/sys/devices/virtual/net       sysfs                sysfs     rw,relatime
│   │ └─/sys/devices/virtual/net     sysfs[/devices/virtual/net]
│   │                                                     sysfs     rw,nosuid,nodev,noexec,relatime
│   ├─/sys/fs/fuse/connections       fusectl              fusectl   rw,nosuid,nodev,noexec,relatime
│   └─/sys/fs/cgroup                 cgroup               cgroup2   rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot
├─/tmp/autopkgtest-lxc.wgo04b54      tmpfs[/autopkgtest-lxc.wgo04b54]
│                                                         tmpfs     rw,nosuid,nodev,relatime
└─/etc/systemd/network               none                 tmpfs     rw,relatime
```

**Comment by mbiebl** [comment]
```
$ lxc-checkconfig 
LXC version 4.0.6
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.10.0-3-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 


Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup namespace: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

**Comment by topimiettinen** [comment]
Very strange. ddc155b should not do anything if `ExecPaths=` or `NoExecPaths=` aren't used and they shouldn't be in case of network tests. In the logs it seems that all network operations fail. Also the file system permissions in the LXC seem correct.

**Comment by topimiettinen** [comment]
@mbiebl can you test if changing
``` 
        return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, SYSFS, PROCFS);
```
to 
```
        return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE);
```
here
https://github.com/systemd/systemd/blob/7ed72cfac7ff282c12c22adcd87b46bb61f37435/src/core/namespace.c#L275
would help?

Maybe even INACCESSIBLE could be removed to be sure.

**Comment by mbiebl** [comment]
> @mbiebl can you test if changing
> 
> ```
>         return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, SYSFS, PROCFS);
> ```
> 
> to
> 
> ```
>         return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE);
> ```

This helps. Thanks

**Comment by bluca** [comment]
I'll go on and open a PR to get Michael unblocked, then we can try and figure out why it's happening

**Comment by mbiebl** [comment]
@bluca It's not time critical. The v248 upload is planned go to experimental (I guess v248 for bullseye will be too late, given that we are already in soft freeze).

**Comment by mbiebl** [comment]
Which means, if it takes a bit to fix this properly, so be it.

**Comment by mbiebl** [comment]
I'm still puzzled why semaphore-ci didn't catch this. This is weird.

**Comment by bluca** [comment]
It's good to fix the immediate regression IMHO, noexec wasn't enabled for sysfs/procfs in 247 so we are not losing anything. I don't know why semaphore-ci didn't trigger this either. Different kernel versions?

**Comment by mbiebl** [comment]
> It's good to fix the immediate regression IMHO, noexec wasn't enabled for sysfs/procfs in 247 so we are not losing anything.

Fair enough. @topimiettinen are you ok if this change is applied or was this supposed to be used only for debugging?

**Comment by mbiebl** [comment]
> Different kernel versions?

I'm using 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux

**Comment by bluca** [comment]
it looks like semaphore is running on Ubuntu Bionic, so maybe difference in kernel/LXC could account for this

**Comment by topimiettinen** [comment]
@mbiebl It's the proper fix. For some reason, LXC doesn't like noexec /proc and /sys, but that shouldn't be done anyway without explicit `NoExecPaths=`.

**Comment by brauner** [comment]
I can't make out what fails here looking at the logs. LXC doesn't care whether proc or sys are mounted with noexec or not. As you can see from the ouput you posted @mbiebl both proc and sys are mounted with noexec.

One thing to note is that `noexec` along with `rdonly` and a few others fall into the "locked flags" category, i.e. when the container tries to mount instances of an already visible fs (e.g. proc and sys) or remounts instances of a locked mount it needs to make sure to retain those flags. If not, the remount will fail. But there's another fresh proc instance that should prevent this problem as can be seen in the mount output.

So my guess is AppArmor, i.e. does `dmesg` show anything interesting?

**Comment by mbiebl** [comment]
@brauner I booted the host system with `apparmor=0`, but this didn't help unfortunately.
I don't see anything interesting in dmesg or the jouranal which looks remotely related.

**Comment by brauner** [comment]
Can you spot what exactly is failing? It feels like that a mount or remount of `proc` or `sys` by one of the tests might do the trick.

**Comment by brauner** [comment]
I.e. can you tell me how the test fails?

**Comment by mbiebl** [comment]
> Can you spot what exactly is failing?

Any hints how I can find out?

**Comment by brauner** [comment]
> > Can you spot what exactly is failing?
> 
> Any hints how I can find out?

If you know the test that fails then I'd suggest to strace it with `strace -f` and append the output here.

**Comment by topimiettinen** [comment]
Just an idea: @mbiebl could you check which one, `/proc` or `/sys`, is the problem by retrying the tests with:
```
return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, PROCFS);
```
and
```
return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, SYSFS);
```

**Comment by mbiebl** [comment]
> Just an idea: @mbiebl could you check which one, `/proc` or `/sys`, is the problem by retrying the tests with:
> 
> ```
> return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, PROCFS);
> ```

All tests pass successfully

Ran 34 tests in 134.213s

OK (skipped=2)


> ```
> return p->noexec || IN_SET(p->mode, NOEXEC, INACCESSIBLE, SYSFS);
> ```

All tests fail

Ran 34 tests in 354.946s

FAILED (failures=8, errors=23, skipped=2)

**Comment by mbiebl** [comment]
> If you know the test that fails then I'd suggest to strace it with `strace -f` and append the output here.

I ran one of the following command: `./test/networkd-test.py MatchClientTest`
[strace.txt](https://github.com/systemd/systemd/files/6071345/strace.txt)

**Comment by topimiettinen** [comment]
This command `execve("/usr/sbin/ip", ["ip", "link", "add", "name", "test_veth", "addr", "00:01:02:03:98:99", "type", "veth", "peer", "name", "test_peer", "addr", "00:01:02:03:98:99"], 0x12ee8a0 /* 10 vars */)` fails:
```
[pid  2921] 19:50:02.237781 sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=124, type=RTM_NEWLINK, flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_EXCL|NLM_F_CREATE, seq=1614714603, pid=0}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_NETROM, ifi_index=0, ifi_flags=0, ifi_change=0}, [{{nla_len=10, nla_type=IFLA_ADDRESS}, 00:01:02:03:98:99}, {{nla_len=14, nla_type=IFLA_IFNAME}, "test_veth"}, {{nla_len=64, nla_type=IFLA_LINKINFO}, [{{nla_len=8, nla_type=IFLA_INFO_KIND}, "veth"...}, {{nla_len=52, nla_type=IFLA_INFO_DATA}, "\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0a\x00\x01\x00\x00\x01\x02\x03\x98\x99\x00\x00"...}]}]}, iov_len=124}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 124
[pid  2921] 19:50:02.237944 recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=NULL, iov_len=0}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_TRUNC}, MSG_PEEK|MSG_TRUNC) = 144
[pid  2921] 19:50:02.238068 recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=144, type=NLMSG_ERROR, flags=0, seq=1614714603, pid=2921}, {error=-EEXIST, msg={{len=124, type=RTM_NEWLINK, flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_EXCL|NLM_F_CREATE, seq=1614714603, pid=0}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_NETROM, ifi_index=0, ifi_flags=0, ifi_change=0}, [{{nla_len=10, nla_type=IFLA_ADDRESS}, 00:01:02:03:98:99}, {{nla_len=14, nla_type=IFLA_IFNAME}, "test_veth"}, {{nla_len=64, nla_type=IFLA_LINKINFO}, [{{nla_len=8, nla_type=IFLA_INFO_KIND}, "veth"...}, {{nla_len=52, nla_type=IFLA_INFO_DATA}, "\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0a\x00\x01\x00\x00\x01\x02\x03\x98\x99\x00\x00"...}]}]}}}, iov_len=32768}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 144
[pid  2921] 19:50:02.238229 write(2, "RTNETLINK answers: File exists\n", 31RTNETLINK answers: File exists
) = 31
[pid  2921] 19:50:02.238347 exit_group(2) = ?
```
But the command doesn't access `/sys` at all. Earlier, `networkctl` (`[pid  2915] 19:50:02.031788 execve("/usr/bin/networkctl", ["networkctl", "--no-legend"], 0x12ee8a0 /* 10 vars */ <unfinished ...>`) checks the devices in `/sys` via `/sys/class/net/test_veth/../../devices/virtual/net/test_veth`.

In the `findmnt` there's indeed a new mount for `/sys/devices/virtual/net` which is probably remounted from the fresh `/sys` instance. Could it be that the fresh `/sys` and the `/sys` instance mounted with `noexec` become disconnected and somehow unsynchronized, and this doesn't happen without `noexec`?

**Comment by mbiebl** [comment]
```
[pid  2914] 19:49:56.808313 openat(AT_FDCWD, "/proc/sys/kernel/random/boot_id", O_RDONLY|O_NOCTTY|O_CLOEXEC) = 10
[pid  2914] 19:49:56.808389 read(10, "e487d3b2-359d-4409-8f40-c8f9c453"..., 38) = 37
[pid  2914] 19:49:56.808439 read(10, "", 1) = 0
[pid  2914] 19:49:56.808490 close(10)   = 0
[pid  2914] 19:49:56.808540 timerfd_settime(6, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=6848, tv_nsec=965083000}}, NULL) = 0
[pid  2914] 19:49:56.808614 epoll_wait(4, [{EPOLLIN, {u32=1255430776, u64=93936485161592}}], 12, -1) = 1
[pid  2914] 19:50:02.014026 read(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  2914] 19:50:02.014246 gettid()    = 2914
[pid  2914] 19:50:02.014658 gettid()    = 2914
[pid  2914] 19:50:02.015067 sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="PRIORITY=3\nSYSLOG_FACILITY=3\nTID"..., iov_len=161}, {iov_base="MESSAGE=", iov_len=8}, {iov_base="Event loop failed: Connection ti"..., iov_len=39}, {iov_base="\n", iov_len=1}], msg_iovlen=4, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 209
```
Not sure if this is relevant
