### ISSUE TITLE
StopWhenUnneeded doesn't stop when referencing unit removes dependency

### ISSUE THREAD

**Issue by phemmer** [systemd/systemd#18792]
**systemd version the issue has been seen with**
> systemd-246.7-2.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)

 > `5.10.14-200.fc33.x86_64`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Editing a unit and removing a `Wants=` on another unit which has `StopWhenUnneeded=true` should cause the other unit to stop.

**Unexpected behaviour you saw**
 > Other unit did not stop

**Steps to reproduce the problem**
```
$ systemctl cat test.target
# /etc/systemd/system/test.target
[Unit]
Wants=test.service

$ systemctl cat test.service
# /etc/systemd/system/test.service
[Unit]
StopWhenUnneeded=true

[Service]
ExecStart=/bin/sleep inf

$ systemctl start test.target

$ systemctl status test.service | grep Active
     Active: active (running) since Thu 2021-02-25 00:39:05 EST; 33s ago

$ systemctl list-dependencies --reverse test.service
test.service
● └─test.target

$ sed -i /Wants/d /etc/systemd/system/test.target

$ systemctl daemon-reload

$ systemctl status test.service | grep Active   
     Active: active (running) since Thu 2021-02-25 00:39:05 EST; 2min 4s ago

$ systemctl list-dependencies --reverse test.service
test.service

$ systemctl stop test.target

$ systemctl status test.service | grep Active      
     Active: active (running) since Thu 2021-02-25 00:39:05 EST; 3min 3s ago
```

After the `daemon-reload`, `test.service` should have stopped as it was no longer needed. It even stays running when `test.target` is stopped.

**Comment by poettering** [comment]
I am pretty sure this has been fixed by 156ba52b43f4ce795fbc1662f85e2fb4a45dd00a and 99e9af257a1a3afbb661a0991bf4464285bc8009

(the first when the dep is changed without reloading, the latter when the dep is changed while reloading).

Closing.
