### ISSUE TITLE
broken systemctl status output

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#18814]
Version: 248-rc2
OS: Debian sid

Running `systemctl status` on the console, I get broken output. See attached screenshot. This is a regression to v247, so marking accordingly.

![Screenshot_debian10_2021-02-26_20:55:33](https://user-images.githubusercontent.com/3609611/109348797-4a6b8800-7875-11eb-942e-01d7d190c43a.png)

**Comment by poettering** [comment]
See NEWS file, comment about "less".

**Comment by mbiebl** [comment]
Hm, the latest version at http://www.greenwoodsoftware.com/less/ is 563 and the comment says/said:

```
-        /* Unfortunately 'less' doesn't support links like this yet 😭, hence let's disable this as long as there's a
-         * pager in effect. Let's drop this check as soon as less got fixed a and enough time passed so that it's safe
-         * to assume that a link-enabled 'less' version has hit most installations. *
```
"enough time passed to assume a link-enabled 'less' has hit most installation"
I'd say this is not the case (yet)

**Comment by poettering** [comment]
Can't you just add a "Conflicts: less < 563" to the .debs? Or can you patch it out in Debian? I kinda would prefer if we could leave this in, it's just sooo useful

**Comment by mbiebl** [comment]
The latest available version is 551, so a Conflicts would not help.

**Comment by poettering** [comment]
you mean, latest available in debian?

**Comment by mbiebl** [comment]
Please check the less upstream homepage. 551 is the latest stable release. All others are beta releases (they don't even compile here).
So yeah, I think it's premature to depend on less > 563

**Comment by mbiebl** [comment]
I will patch this out downstream

**Comment by rbalint** [comment]
> Please check the less upstream homepage. 551 is the latest stable release. All others are beta releases (they don't even compile here).
> So yeah, I think it's premature to depend on less > 563

As I read www.greenwoodsoftware.com/less/ 563 had been released on 2020-10-21, but both Debian and Ubuntu are frozen thus it is not a good time to upgrade less.

**Comment by mbiebl** [comment]
Looks like the less homepage has been updated in the mean time. Back in march, it didn't list 563

**Comment by jameshilliard** [comment]
Added an option to disable this feature in #20196, useful when using older versions of less or alternate stripped down versions of less that don't hyperlinks such as busybox less.
