### ISSUE TITLE
Drop-in override of erroneous/outdated .service unit file cannot silence warning

### ISSUE THREAD

**Issue by fabricemarie** [systemd/systemd#18839]
Using systemd-246 on Fedora 33

freshclam RPM ships with an outdated `clamav-freshclam.service` unit file that generate warnings when doing reload-daemon

```
/usr/lib/systemd/system/clamav-freshclam.service:11: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```

So I created an drop-in override file to try to silence the warning by myself:

```
# cat /etc/systemd/system/clamav-freshclam.service.d/override.conf
[Service]
StandardOutput=journal
```

I reload systemd and the warning appears again.

And I also confirmed that the override drop-in file was indeed loaded:

```
# systemctl status clamav-freshclam
● clamav-freshclam.service - ClamAV virus database updater
     Loaded: loaded (/usr/lib/systemd/system/clamav-freshclam.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/clamav-freshclam.service.d
             └─override.conf
```

It would be great if systemd could postpone checks for warning conditions until after the drop-in file overrides the settings

This would make it semantically more correct I believe (and avoid surprises).
Additionally, we wouldn't have to wait for distro packagers (Fedora) or actual software developers (ClamAV) to fix this kind of issue.

**Comment by poettering** [comment]
Hmpf, I am not convinced. Parsing warnings are parsing warnings, I don't thin we should hide them.

Drop-ins are not supposed to be a mechanism for suppressing parsing issues, but a tool for extending/overrding settings. I'd really not mix up the two concepts.

The idea of these warnings in the first place is put gentle pressure on the unit file maintainers to fix their units properly. I.e. it's actually part of our approach that people are sufficiently annoyed by these warnings to go to the maintainers and ask them to fix the unit files.

**Comment by keszybz** [comment]
Yeah, I agree. Drop-ins are not a mechanism to fix syntax issues. If you need to do that, override the main file itself. If `/etc/system/clamav-freshclam.service` is present, we will not look at `/usr/lib/systemd/system/clamav-freshclam.service` at all.

There's also a question of complexity: we would need to somehow read everything into memory, generating and gathering warnings and errors as we go along, and then emit them or not. The complexity of this would be enormous.
