### ISSUE TITLE
systemd-sysv-generator should read limits.conf

### ISSUE THREAD

**Issue by Tatikoma** [systemd/systemd#1884]
Hey, We migrate our servers from Debian 7 to Debian 8. Systemd uses "systemd-sysv-generator" for packages that haven't own .service-file ( for example pgbouncer or rabbitmq-server). But systemd-sysv-generator sets only minimal config and ignores settings at limits.conf, For example NOFILE=1024:4096.

Right behavior of systemd-sysv-generator is: 
1. Define user that start process
2. Find all limits and that this user has at limit.conf ( with NOFILE)
3. Write limits to .service-file

**Comment by poettering** [comment]
limits.conf is the configuration file for pam_limits, which is a PAM module and applied to user logins, and nothing else. System services are not logins, and hence limits.conf is really nothing that should apply.

Sorry, but reading PAM-private configuration from a systemd generator is simply wrong.

If you want to adjust a resource limit for a service, consider creating a file /etc/systemd/system/fooobar.service.d/override.conf, and then use:

```
[Service]
LimitNOFILE=4711
```

in it. The "systemctl edit" command will even help you with this.

But really, PAM-private config and systemd service config are independent and should be independent.

Sorry.

**Comment by Tatikoma** [comment]
If i create /etc/systemd/system/fooobar.service.d/override.conf, then it's file 'll not be referenced to package. It's not good.

systemd-sysv-generator should provide compatability to old init script. Correct way to change limits with init-script is edit limits.conf. If systemd-sysv-generator provides comptability then it should read limits.conf, even in the case if its PAM-private configuration file.

Thank you anyway.

**Comment by poettering** [comment]
"referenced to the package"? Not sure what that is supposed to mean?

There's no compatibility to maintain here, limits.conf always was the PAM config file, nothing else. You are asking for behaviour that was never implemented on sysv either.
