### ISSUE TITLE
timedatectl listing NTP service as inactive if systemd-timesyncd is not running

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#18854]
Using Debian sid/unstable with

```
$ systemctl --version
systemd 247 (247.3-1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

if systemd-timesyncd is not running, the NTP service is shown as inactive.

```
$ sudo systemctl start systemd-timesyncd
$ timedatectl
               Local time: Wed 2021-03-03 09:07:17 CET
           Universal time: Wed 2021-03-03 08:07:17 UTC
                 RTC time: Wed 2021-03-03 08:07:17
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
$ sudo systemctl start systemd-timesyncd.service 
$ timedatectl
               Local time: Wed 2021-03-03 09:07:29 CET
           Universal time: Wed 2021-03-03 08:07:29 UTC
                 RTC time: Wed 2021-03-03 08:07:29
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

It’d be great, if it could be marked as *unknown* (systemd-timesyncd not running or D-Bus interface not available) could be used instead of *inactive*.

**Comment by poettering** [comment]
I don't follow? NTP *is* inactive in that case? What do you mean? I don't get what you are saying?

**Comment by paulmenzel** [comment]
Sorry, indeed. `ntpd` is running on the machine, and, therefore, I would have thought, that it would be `NTP: active`.

**Comment by poettering** [comment]
That's a packaging shortcoming. Please ask your distro's ntpd maintainers to drop-in a file as documented in systemd-timedated(8) man page, at the bottom, so that timedatectl will know it exists.

Most distros actually get this right today I think.

Closing, since this is a distro issue.

**Comment by mbiebl** [comment]
@paulmenzel my recommendation would be to use chrony instead of ntp
