### ISSUE TITLE
Router Advertisement based routes ignore local interface MTU

### ISSUE THREAD

**Issue by kuba-moo** [systemd/systemd#18868]
```
# systemctl --version
systemd 245 (v245.8-2.fc32)

# cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

# uname -r
5.10.18-100.fc32.x86_64
```

Working on a network where routers are configured to carry jumbo frames, but some hosts are configured with link MTU of 1500 we see systemd ignore the local MTU and insert routes into the kernel with the MTU from RA. This breaks the connectivity to the parts of the network which are not running with jumbo MTU.

Steps to repro:
1. Find a network with RAs which include MTU
2. Set local link MTU lower than MTU in the RAs
3. Test the routes added from RA: 
```
# ip -6 route get $address
[...] dev enp1s0 proto static src [...] metric 1024 mtu 6000 pref medium
```
The MTU from RA will be listed in the result, even tho in the example the link was at 1500 MTU.

**Comment by yuwata** [comment]
> ```
> # ip -6 route get $address
> [...] dev enp1s0 proto static src [...] metric 1024 mtu 6000 pref medium
> ```

First of all, is this route really configured by `networkd`? Why `proto static`?? Why `src` address is set??

We set route MTU only for default gateway or routes configured with `Gateway=_ipv6ra`.

Could you show the relevant .network file and debugging logs of `networkd`?

**Comment by kuba-moo** [comment]
Ah boo me, I tried to fake the output because I already fixed the machine, but other than the proto it's the same thing:
```
[test addr] from :: via [gw addr] dev enp1s0 proto ra src [...] metric 1024 mtu 6000 pref medium
```

The config is:
```
[Match]
MACAddress=[...]

[Network]
Address=[...]
Gateway=[gw addr]
Domains=[...]
DNS=[...]
```
Nothing in `networkd.config`.

How do I get debugging logs?

**Comment by kuba-moo** [comment]
BTW I'm pretty sure it's `systemd-network` adding the bad route, because:
```
# bpftrace -e 'kprobe:ip_fib_metrics_init { if (arg2) { printf("%s: %r\n", comm, buf(arg1, arg2)); } }' 
Attaching 1 probe...
systemd-network: \x08\x00\x02\x00p\x17\x00\x00
```
If you can read raw netlink it's the RTA_METRICS nest and it contains 2 (MTU) and value 6000 :)

**Comment by yuwata** [comment]
> How do I get debugging logs?

Debugging logs can be generated by creating the following drop-in:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
I recommend to use `sudo systemctl edit systemd-networkd.service` for creating the above drop-in.

**Comment by kuba-moo** [comment]
Here are the logs: https://pastebin.com/v731yEGV

**Comment by bartelsielski** [comment]
> we see systemd ignore the local MTU and insert routes into the kernel with the MTU from RA.

I would say that this is the correct behavior. This is what [rfc4861#section-4.6.4](https://tools.ietf.org/html/rfc4861#section-4.6.4) says regarding the MTU option in RAs:

> The MTU option is used in Router Advertisement messages to ensure that all nodes on a link use the same MTU value in those cases where the link MTU is not well known.
>
> ...
> 
> In configurations in which heterogeneous technologies are bridged together, the maximum supported MTU may differ from one segment to another.  If the bridges do not generate ICMP Packet Too Big messages, communicating nodes will be unable to use Path MTU to dynamically determine the appropriate MTU on a per-neighbor basis.  In such cases, routers can be configured to use the MTU option to specify the maximum MTU value that is supported by all segments.

If it is known which devices should use jumbo frames and which shouldn't, why not configure all of them manually and disable the MTU option in the RAs?

**Comment by anitazha** [comment]
@yuwata I've been discussing this issue with kuba-moo offline and I'm wondering if maybe a knob would be appropriate here (or would a patch be accepted for this)? To at least follow the Linux kernel behavior in this case. Quoting him:
> kernel will make sure it doesn't install a route based on RA with MTU higher than the device MTU, because that'll obviously lead to drops

**Comment by yuwata** [comment]
See #20489.
