### ISSUE TITLE
Portable Services: `portablectl attach --now` doesn't start `.timer` units

### ISSUE THREAD

**Issue by exFalso** [systemd/systemd#18888]
**systemd version the issue has been seen with**
```
systemd 246 (246.6-1ubuntu1)
```

**Used distribution**
Ubuntu 18.04

**Linux kernel version used** (`uname -a`)
```
$ uname -a
Linux XXX 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
After attaching an image with a `.timer` with a corresponding `.service` using `portablectl attach --now`, the service was started once, but the timer wasn't

**Comment by bluca** [comment]
This was fixed by https://github.com/systemd/systemd/commit/e26fe5f91158a0d9133e61347650dfb73aadd6bb via https://github.com/systemd/systemd/pull/18440 and will be included in v248 - should probably backport a smaller fix to systemd-stable
