### ISSUE TITLE
Hundreds of weird systemd-sysv-convert warnings

### ISSUE THREAD

**Issue by Cris70** [systemd/systemd#18898]
**systemd version the issue has been seen with**
 > 246.10

**Used distribution**
 > openSuse Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux polarisuse 5.10.16-1-default #1 SMP Sat Feb 13 16:20:19 UTC 2021 (11381f3) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > AMD64

**Expected behaviour you didn't see**
 > N/A

**Unexpected behaviour you saw**
 > during update (zypper dup) I get hundreds of warning messages like these:
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          
systemd-sysv-convert: warning, /usr/lib/systemd/system/--global.service not found, skipping                                                                                          

**Steps to reproduce the problem**
 > simply issue the `zypper dup` command

**Additional program output to the terminal or log subsystem illustrating the issue**
> See https://gist.github.com/Cris70/fb42961ecd185aadabae1817ca426b40

**Comment by keszybz** [comment]
Looks like an error in the distro packaging scriptlets.

**Comment by poettering** [comment]
Yeah, that script is a Suse thing. Please contact suse for help on this.

See:
https://build.opensuse.org/package/view_file/Base:System/systemd/systemd-sysv-convert
