### ISSUE TITLE
systemd options used to mount a samba share on boot are not allowing to mount share manually after boot

### ISSUE THREAD

**Issue by ed-torvalds** [systemd/systemd#1891]
I am using following lines in `/etc/fstab` file to mount a samba shared folder on boot:

> //192.168.2.3/Seagates /home/edward/samba/raspberry cifs user,noauto,x-systemd.automount,x-systemd.device-timeout=10s,nofail,uid=1000,gid=1000,credentials=/home/edward/.smbcredentials,iocharset=utf8,sec=ntlm 0 0

Note, I am using `noauto,x-systemd.automount,x-systemd.device-timeout=10s` without which mounting does not happen during boot.

Sometimes the computer that shares folder is turned off. When that computer is turned on later, I mount the folder manually by clicking the folder icon in nautilus. With above lines in `/etc/fstab` file, on manual mounting I get this error: [screenshot on imgur](http://i.imgur.com/HVranvJ.png) which is `mount error(22): Invalid arguments`.

from `journalctl`:

> Nov 14 00:33:30 flippingbits systemd[1]: home-edward-samba-raspberry.mount: Unit entered failed state.
> Nov 14 00:33:33 flippingbits kernel: CIFS: Unknown mount option "x-systemd.automount"

**I mean the same option that helps mounting on boot gives error while mouting after boot**
The manual mounting happens **by non-root user** if I remove `systemd` specific options: `noauto,x-systemd.automount,x-systemd.device-timeout=10s` or by removing `user` option which prevents me from mounting saying that only `root` users can mount.

System details:
1. systemd 225
2. Ubuntu 15.10
3. samba --version 4.1.17-Ubuntu
4. [Output](http://sprunge.us/LXHQ) of `systemd-analyze blame` on my computer
5. [Output](http://sprunge.us/EOLZ) of `systemctl status smbd.service`
6. [Output](http://sprunge.us/PYaK) of `systemctl status nmbd.service`

(please tell me if you need more information on this)

**Comment by arvidjaar** [comment]
>  I mount the folder manually

How exactly? mount from util-linux should ignore options that start with x- since at least version 2.21.

**Comment by ed-torvalds** [comment]
@arvidjaar There is an icon named 'raspberry', the name of computer that shares the folder, in nautilus. I click on that to mount it 'manually'. I am sure util-linux is not ignoring the options starting with `x-` you should see the log I gave `Nov 14 00:33:33 flippingbits kernel: CIFS: Unknown mount option "x-systemd.automount"`

**Comment by poettering** [comment]
First of all, x-systemd.device-timeout= only has an effect on mounts that are backed by block devices, and SMB mounts are not.

Other than that: nautilus mounts devices via udisks, and udisks calls util-linux /bin/mount, which in turn invokes the CIFS mount tools, systemd isn't involved in any of that. 

Hence, please file a bug against util-linux or udisks. Normally, /bin/mount should be stripping all options starting with "x-" away. If it doesn't do that in your case, and they get passed to the CIFS mount tool, then this is either indication for a bug in util-linux or that your util-linux is too old. Which util-linux version do you have? @karelzak might have more to say about that.

Either way, closing this here, as systemd is not really involved in all of this... Please report to util-linux/udisks maintainer, and maybe include a reference to this original bug.
