### ISSUE TITLE
Upgrade to systemd v248 RC2 on Fedora34 switches default-hierarchy to unified but doesn't cleanup hybrid setup

### ISSUE THREAD

**Issue by PavelSosin-320** [systemd/systemd#18912]
**systemd version the issue has been seen with**
systemctl --version
systemd 248 (v248~rc2-1.fc34)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
 > …

**Used distribution**

**Operating System: Fedora 34 (Container Image Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:34**
          **Kernel: Linux 5.4.91-microsoft-standard-WSL2
    **Architecture: x86-64**
 **

**Expected behaviour you didn't see**
 > After installation or upgrade to the recent systemd version the old hybrid cgroup setup is cleaned up to avoid misleading of Podman, Docker, etc. inline with systemd.io recommendations and systemctl version output.

**Unexpected behaviour you saw**
 > The hybrid cgroup setup containing both /sys/fs/cgroup/unified and /sys/fs/cgroup/systemd…
The Podman is misleading and use cgroup V1 API instead of V2

**Steps to reproduce the problem**
 > …
I use Fedora 34 container image 
1. Windows 10 WSL2 -> ....
2. Import Fedora34 container image as WSL distro
3. Install genie systemd to get systemd workig
4. Upgrade systemd to the latest version
4. Install Podman 3.0
5. Check Podman info for the root user - The correct combination of cgroup manager and cgroup API is shown
6. logon as rootless user and run Podman info > cgroup V2 is not recognized and Podmans falls back to the cgroupfs cgroup manager.

**Additional program output to the terminal or log subsystem illustrating the issue**

ls /sys/fs/cgroup/
blkio  cpu,cpuacct  cpuset   freezer  memory   net_cls,net_prio  perf_event  rdma     **unified**
cpu    cpuacct      devices  hugetlb  net_cls  net_prio          pids        **systemd**

journal for the last boot contains 
![image](https://user-images.githubusercontent.com/54495912/110238600-254cd880-7f4b-11eb-9af4-1f3dac75a270.png)

But there is no systemd-compat and log messages found.

```text
…
```

**Comment by poettering** [comment]
Apparently you booted in hybrid mode. If you want cgroupv2 mode, then don't do that. Boot with `systemd.unified_cgroup_hierarchy=1` on the kernel command line to get cgroupsv2 mode.

You cannot switch during runtime, you need to reboot to switch between cgroupsv1, hybrid and cgroupsv2 mode, and the way to choose that is via the kernel cmdline.

Closing, since this doesn't appear to be a bug, but a misunderstanding how to select the hierarchy. In general, please contact the mailing list first for support questiosn like this. thank you
