### ISSUE TITLE
SystemCallFilter doesn't override errno

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#18916]
**systemd version the issue has been seen with**
247.3-1

**Used distribution**
Debian Unstable

**Linux kernel version used** (`uname -a`)
`5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux`

**Expected behaviour you didn't see**

The documentation of [`SystemCallFilter`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SystemCallFilter=) states:

> Deny-listed system calls and system call groups may optionally be suffixed with a colon (":") and "errno" error number (between 0 and 4095) or errno name such as EPERM, EACCES or EUCLEAN (see errno(3) for a full list). This value will be returned when a deny-listed system call is triggered, instead of terminating the processes immediately.

This only seems to work on the first directive in which the call is denied; any further overrides will be unable to change the error number.

**Steps to reproduce the problem**

```
[Service]
ExecStart=/bin/uname
SystemCallErrorNumber=EUCLEAN
SystemCallFilter=@system-service
SystemCallFilter=~uname:EBADF
```

When attempting to run this service, the `uname` error (as reported in the journal) is "Structure needs cleaning", i.e. `EUCLEAN`. I would have expected to see `EBADF` instead.

As far as I can tell this makes it impossible to customize errno on a per-system-call basis when using an allow-list approach.

**Comment by yuwata** [comment]
Fix is waiting in #18921.
