### ISSUE TITLE
systemd-detect-virt does not recognize AWS arm64 instance types as virtualized

### ISSUE THREAD

**Issue by nmeyerhans** [systemd/systemd#18929]
**systemd version the issue has been seen with**
 > 247.3

**Used distribution**
 > Debian, Amazon Linux 2

**Linux kernel version used** (`uname -a`)

 > `5.10.0-3-cloud-arm64` (Debian)

**CPU architecture issue was seen on**
 > arm64

**Expected behaviour you didn't see**
 > Expected KVM-based arm64 instances to be detected as virtualized.

**Unexpected behaviour you saw**
 > systemd-detect-virt reports "none"

**Steps to reproduce the problem**
 > Launch an arm64 instance (Any that doesn't end in .metal, e.g. m6g.large) on Amazon EC2. Log in and run `systemd-detect-virt`

**Additional program output to the terminal or log subsystem illustrating the issue**

On current-generation (i.e. Nitro-based) x86_64 instances, we see KVM virtualization properly detected:
```
admin@ip-10-0-0-10:~$ ec2-metadata --instance-type
instance-type: t3.medium
admin@ip-10-0-0-10:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.998
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        1 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht sy
                                 scall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmu
                                 lqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hy
                                 pervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
                                  mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 x
                                 saves ida arat pku ospke
admin@ip-10-0-0-10:~$ SYSTEMD_LOG_LEVEL=debug systemd-detect-virt 
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
No virtualization found in DMI
UML virtualization not found in /proc/cpuinfo.
Virtualization found, CPUID=KVMKVMKVM
Found VM virtualization kvm
kvm
```
On Nitro based arm64 instance types, also based on KVM, we see the following:
```
admin@ip-10-0-0-17:~$ ec2-metadata --instance-type
instance-type: m6g.large
admin@ip-10-0-0-17:~$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           1
Model name:                      Neoverse-N1
Stepping:                        r3p1
BogoMIPS:                        243.75
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
admin@ip-10-0-0-17:~$ SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
No virtualization found in DMI
UML virtualization not found in /proc/cpuinfo.
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen does not exist
/proc/device-tree: No such file or directory
This platform does not support /proc/sysinfo
Found VM virtualization none
none
```

**Comment by nmeyerhans** [comment]
The kernel exposes a number of details via DMI that can help to provide some hints:
```
$ cat /sys/class/dmi/id/sys_vendor 
Amazon EC2
```
However, looking exclusively at DMI also means taking care to exclude bare-metal instances, which would present a DMI product_name field containing the string `.metal`:
```
$ cat /sys/class/dmi/id/product_name 
m6g.metal
```

Since there's no arm64 equivalent of [cpuid](https://www.kernel.org/doc/html/latest/virt/kvm/cpuid.html), which is used on x86_64, this approach may be the most practical.

**Comment by poettering** [comment]
well, but we are not so much interested in wether this is aws or not, we care if it is kvm or not...

**Comment by poettering** [comment]
also, this requires a contributed patch, since we have no access to such machines

**Comment by nmeyerhans** [comment]
> well, but we are not so much interested in wether this is aws or not, we care if it is kvm or not...

Agreed, but what other options to we have? On x86_64, we detect KVM primarily through the CPUID instruction, but arm64 has no such equivalent. I don't believe that the kernel exposes anything indicating KVM via sysfs. In fact, I'm not sure that the kernel itself currently has a mechanism for detecting the presence of a hypervisor on arm64.  All of that is done via CPUID in kernel space as well.

> also, this requires a contributed patch, since we have no access to such machines

That's fine, I can help to prepare a patch when we decide on the right approach.

**Comment by poettering** [comment]
We also use DMI data:

https://github.com/systemd/systemd/blob/main/src/basic/virt.c#L137

**Comment by nmeyerhans** [comment]
Yes, but the kernel doesn't expose any DMI data in sysfs that indicates the generic presence of a KVM hypervisor. Everything currently visible from the kernel is vendor specific.

At least on the Amazon EC2 instances, there's a bit set in SMBIOS that indicates that the machine is a VM. The [dmidecode](https://nongnu.org/dmidecode/) tool is able to properly identify EC2 instances as VMs using this mechanism. The drawback with that approach is that we need to parse the SMBIOS information tables ourself, but I do believe QEMU will also set that bit. See section 7.1.2.2 of the [smbios](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf) spec for details on that.

We may also be able to get details from ACPI, but this again will involve some low-level inspection of the ACPI tables. The information we need isn't exported by the kernel in an easily consumable way.

**Comment by poettering** [comment]
So, you are basically saying that there's really no way to detect that AWS implements this with KVM? Hmmm... :-(

We have some code parsing SMBIOS already in `src/udev/dmi_memory_id/dmi_memory_id.c` we could probably generalize that a bit and reuse it here. 

Checking for the SMBIOS 7.1.2.2 flag is something we should certainly do I think. I mean, I very much appreciate a mechanism that works generically like this I must say.

(We also prase some ACPI tables ourselves, for getting boottime performance info for example. I am totally fine if we have some parsing for that in place).

But neither SMBIOS nor ACPI provides us with a way to detect that this is KVM, right?

Or is AWS-flavoured KVM already far away from vanilla KVM that we should consider AWS a VM product of its own right and accept our fate on this?

**Comment by poettering** [comment]
Also see #17315 btw

**Comment by nmeyerhans** [comment]
Thank you for the pointer to the pull request. I was only looking through open issues and missed an existing PR.  I've left a comment on that, as it's not complete as implemented.

Let me summarize the current state, at least as it is on VMs that I can access right, and I will make a proposal that hopefully will address both issues.

I'll start with QEMU, ignoring anything to do with AWS:

**QEMU emulated (x86_64)**

    root@debian:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    Virtualization QEMU found in DMI (/sys/class/dmi/id/sys_vendor)
    UML virtualization not found in /proc/cpuinfo.
    Virtualization found, CPUID=TCGTCGTCGTCG
    Found VM virtualization qemu
    qemu

**QEMU on KVM (x86_64)**

    root@debian:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    Virtualization QEMU found in DMI (/sys/class/dmi/id/sys_vendor)
    UML virtualization not found in /proc/cpuinfo.
    Virtualization found, CPUID=KVMKVMKVM
    Found VM virtualization kvm
    kvm

With arm64 (aarch64) we have:

**QEMU emulated (arm64)**

    root@debian:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    Virtualization QEMU Virtual Machine found in DMI (/sys/class/dmi/id/product_name)
    UML virtualization not found in /proc/cpuinfo.
    No virtualization found in CPUID
    Found VM virtualization qemu
    qemu

**QEMU on KVM (arm64)**

    root@debian:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    Virtualization KVM Virtual Machine found in DMI (/sys/class/dmi/id/product_name)
    UML virtualization not found in /proc/cpuinfo.
    No virtualization found in CPUID
    Found VM virtualization kvm
    kvm

The only hint we use is /sys/class/dmi/id/product_name, which contains the string "KVM Virtual Machine".  However, that string actually comes from QEMU, not directly from KVM itself. (see https://github.com/qemu/qemu/blob/821e7ed167f11f482d2d1a8eaf114a667295a581/hw/arm/virt.c#L1506)

On Amazon EC2 today we have the following:

**EC2 Nitro (kvm) x86_64**

    root@ip-172-31-81-203:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    No virtualization found in DMI
    Virtualization found, CPUID=KVMKVMKVM
    Found VM virtualization kvm
    kvm

So we see here that virtualization is detected entirely based on CPUID; there is nothing in DMI (at least where we're looking) that indicates virtualization.

**EC2 Nitro (kvm) arm64**

    root@ip-10-0-0-158:~# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
    Found container virtualization none.
    No virtualization found in DMI
    UML virtualization not found in /proc/cpuinfo.
    No virtualization found in CPUID
    Virtualization XEN not found, /proc/xen does not exist
    /proc/device-tree: No such file or directory
    This platform does not support /proc/sysinfo
    Found VM virtualization none
    none

And here, since there is not CPUID on arm64, and as with x86_64 we don't interpret anything in DMI as indicating a hypervisor, we fail to detect virtualization.

So, to answer your questions:

> So, you are basically saying that there's really no way to detect that AWS implements this with KVM? Hmmm... :-(

The only DMI hints that work today on arm64 come from QEMU, not directly KVM, so it's not surprising that they don't work in AWS where QEMU is not used.

> But neither SMBIOS nor ACPI provides us with a way to detect that this is KVM, right?

That's right. They will tell us if the system is a VM, which is helpful for distinguishing between AWS VMs and bare-metal instances as they otherwise look pretty similar in terms of the DMI information that the kernel exposes, but they won't tell us about the underlying technology.  The alternative is to look in /sys/class/dmi/id/product_name for the string ".metal" when running on AWS and treat that as an indicator that virtualization is not present.  But that's obviously somewhat brittle.

> Or is AWS-flavoured KVM already far away from vanilla KVM that we should consider AWS a VM product of its own right and accept our fate on this?

It's all standard KVM, but as I mentioned above most of the relevant information comes from the VMM on top of KVM, not from KVM itself.  AWS is definitely different from QEMU, so it'd be reasonable to detect it as something distinct there.  Is there a use case for being able to detect an AWS hypervisor specifically?  I could certainly envision ConditionVirtualization=amazon-ec2 being useful to activate specific unit files based on whether they're running on an EC2 instance.  On the other hand, you might soon find people asking for more and more cloud services to be identified specifically, and that way lies madness.  Since AWS x86_64 instances are currently already detected as kvm, I think it makes sense to remain consistent and identify AWS arm64 instances the same.

Since we're already recognizing QEMU as a vendor, based on "Virtualization QEMU found in DMI (/sys/class/dmi/id/sys\_vendor)" from systemd-detect-virt, I think it's reasonable to similarly recognize other vendor-specific values in sys_vendor, so that would be Amazon EC2 in this case.  So I think we should do the following, in pseudocode:

    if sys_vendor contains "Amazon EC2":
        if SMBIOS indicates virtualization:
            return "kvm"
        else
            return "none"

This will properly detect AWS x86_64 instances as well as arm64 instances without depending on the x86\_64 CPUID instruction, and will properly classify non-virtualized AWS instances.  Amazon's Xen instances don't need special handling since they're x86\_64 only and already properly identified as xen.

**Comment by nmeyerhans** [comment]
I'm looking in to putting together a pull request for this. Decoding a bunch of binary-packed datastructures from firmware memory to get one bit worth of data seems like overkill on its own, so, as you indicated previously, having some more general DMI/SMBIOS parsing code makes some sense.  There are three ways to approach this, and I'd like some feedback before I pick one:

1. We could incorporate (much of) the content of [dmidecode.c](http://git.savannah.nongnu.org/cgit/dmidecode.git/tree/dmidecode.c) from the [dmitools](http://savannah.nongnu.org/projects/dmidecode/) project (GPLv2).
2. We could link against the [libsmbios](https://github.com/dell/libsmbios/) library published by Dell (GPLv2 or [OSL v2.1](https://opensource.org/licenses/OSL-2.1) dual license).
3. We could do a from scratch implementation of SMBIOS parser/decoder logic. It's not particularly complicated, but it is rather tedious code. And it'll end up looking an awful lot like `dmidecode.c` when it's done.

Thoughts or preferences?

**Comment by poettering** [comment]
So hmm, I wasn't aware that AWS uses KVM without QEMU. Is vmm they use proprietary aws stuff? or is it open soruce and people could run that outside of aws too?

I figure it would make sense to declare (and document) that what we report as "kvm" actually means "kvm+qemu", and then treat the aws thing as a totally different thing.

**Comment by nmeyerhans** [comment]
> So hmm, I wasn't aware that AWS uses KVM without QEMU. Is vmm they use proprietary aws stuff? or is it open soruce and people could run that outside of aws too?

The [Nitro Hypervisor](https://aws.amazon.com/ec2/nitro/) is custom to Amazon EC2 and will only be encountered within that service. (BTW, I work for AWS; sorry for not being clear about that up front.)

> I figure it would make sense to declare (and document) that what we report as "kvm" actually means "kvm+qemu", and then treat the aws thing as a totally different thing.

I think that's reasonable. It's the approach that @bjacquin implemented in #17315, which looks pretty good to me. The only issue with that PR in my view is that it doesn't distinguish between virtual and physical arm64 instances, and would incorrectly identify physical systems as being virtualized. To correct that, unfortunately, requires parsing raw DMI data that's not exposed by the kernel via `/sys/class/dmi/id`.

**Comment by ozbenh** [comment]
Should we fix the kernel ?

**Comment by nmeyerhans** [comment]
> Should we fix the kernel ?

Actually, I the kernel does expose the data we need via the `/sys/firmware/dmi/entries/` interface. It's still packed binary, rather than the convenient string interfaces in `/sys/devices/virtual/dmi/`, but it's easy to get at. So I don't think we need to change the kernel, import `dmidecode.c` or link against additional libraries. I'll post a patch in the next couple days.

**Comment by ozbenh** [comment]
/sys/firmware/dmi/entries/  is only present if dmi-sysfs.ko is loaded which doesn't seem to be automatic on my laptop at least.  It's also root restricted. There might be additional restrictions (lockdown ?), I need to look at the code, but I still think it would be better to augment /sys/device/virtual/dmi to expose the parsed information
