### ISSUE TITLE
Better error message on systemctl enable  for Aliases which already exist as real files.

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1892]
The recent rework of how Aliases are handled did break systemctl enable.

E.g. our ssh.service has 

```
[Install]
WantedBy=multi-user.target
Alias=sshd.service
```

this will now result in 

```
# systemctl enable ssh.service
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ssh
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
Failed to execute operation: Invalid argument
# echo $?
1
```

The WantedBy= symlink is created, the Alias= not and systemd chokes on that.

@martinpitt I'm surprised our integration tests didn't catch that, unit-config was supposed to detect this breakage. Something to look into.

**Comment by mbiebl** [comment]
I suspect this is caused by https://github.com/systemd/systemd/pull/1515 but didn't further investigate yet.

**Comment by poettering** [comment]
Any chance you can isolate a minimal test case, that does not involve sysv fallback code or anything like that (as your example apparently does)?

**Comment by mbiebl** [comment]
@poettering ok, this is apparently a typical point of pebkac.
For some reason on my laptop running git master, I had /etc/systemd/system/sshd.service as real file (it was a copy of /lib/systemd/system/ssh.service).
So creating the Alias=sshd.service simply failed.

This is not really a regression. This already failed with older versions. In the test-VM with v227 I simply didn't have /etc/systemd/system/sshd.service as real file :-/

I guess if the error message would have been clearer, I wouldn't have misinterpreted the issue.

**Comment by mbiebl** [comment]
@poettering to reproduce the problem, you can do the following:

```
systemctl disable sshd.service
cp  /usr/lib/systemd/system/sshd.service /etc/systemd/system/ssh.service
echo "Alias=ssh.service" >> /usr/lib/systemd/system/sshd.service
systemctl enable sshd.service
```
