### ISSUE TITLE
RFE: option to set HOME to /

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#18948]
**Is your feature request related to a problem? Please describe.**

Some customers were running code in a container as the nobody user with a systemd service and expected the $HOME environment variable to be set to "/". However it's not. There's a comment in the code that says $HOME and $SHELL are not set if they're "not particularly enlightening". https://github.com/systemd/systemd/blob/e5f8ce13bbaf0d8b9ff597692c67fba0e38b4200/src/core/execute.c#L943-L944

**Describe the solution you'd like**

Maybe a way to assign a default value to an environment variable if it isn't set (this could be useful if combined with inherited environment variables?).
Or maybe a property that will allow setting $HOME and $SHELL to whatever is in /etc/passwd even if it's / and /bin/nologin.
Do any of these sound acceptable?

**Describe alternatives you've considered**
 
We plan to eventually migrate off nobody as the default but due to the size of the fleet it will take... a while. We could set it manually with Environment=HOME=/ but since systemd is doing the home look up already (and takes into account any namespacing?) it didn't make sense to do it outside of the unit. In both cases there are users other than nobody that have HOME=/ and they may expect HOME and SHELL to default to something as well (like how login defaults HOME to / and SHELL to /bin/sh).

**The systemd version you checked that didn't have the feature you are asking for**

latest (248-rc2)

**Comment by poettering** [comment]
Hmm, this sounds like something one can easily do manually via `Environment=HOME=/`

we never set $HOME in this case, so I am not sure how people would assume we did?

$HOME generally is a weird concept for system services, hence we generally try to avoid it, unless there's actually real data set.

**Comment by anitazha** [comment]
Sorry I should have mentioned that the customers were migrating from a different init to systemd.

Previously their commands were run with something like `setpriv --reuid nobody --reset-env <command>` or `su -s /bin/sh -c <command> nobody` which both set HOME=/ and now the command is moved to a systemd service (e.g. with User=nobody ExecStart=<command>)

Systemd should probably continue to omit HOME=/, but maybe there can be an option to default it to something if it's omitted?

**Comment by anitazha** [comment]
Closing this since we'll be resolving this internally. We've agreed that HOME=/ is not very useful
