### ISSUE TITLE
resolved: issue with polkit-1 and capabilities

### ISSUE THREAD

**Issue by kayrus** [systemd/systemd#18956]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.4)

**Used distribution**
 > ubuntu focal

**Linux kernel version used** (`uname -a`)

 > `5.4.0-66-generic`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > resolved should grant DNS changes if a client has `CAP_NET_ADMIN` capability

**Unexpected behaviour you saw**
 > resolved keeps asking for a password even when a client has `CAP_NET_ADMIN` capability

**Steps to reproduce the problem**

```
$ sudo setcap cap_net_admin+ep /usr/bin/resolvectl
$ resolvectl dns eth0 8.8.8.8 # asks for a password
```

see also https://github.com/systemd/systemd/pull/13457#issuecomment-795722551

**Comment by poettering** [comment]
we can't safely determine a client's caps on Linux AF_UNIX currently. It's simply not implemented what you are looking for, because we cannot. What made you think it was?

**Comment by kayrus** [comment]
Another bizarre behavior is that sequence of user commands require typing the password multiple times :\
```
$ systemd-resolve --set-domain=local --interface eth0
# password prompt
$ systemd-resolve --set-dns=192.168.0.1 --interface eth0
# password prompt
```
shall I create a new issue or is it something that can be configured?

**Comment by kayrus** [comment]
I found a workaround for password prompts. I took NetworkManager's `/var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla` config as an example. If default Ubuntu allows me to modify DNS addresses via NetworkManager polkit rules, then it should be possible for `systemd-resolve`.
I created a `/var/lib/polkit-1/localauthority/50-local.d/org.freedesktop.resolve1.pkla` file with a content below and now if my user has a `sudo` or `netdev` group, the pasword is not asked:
```ini
[Adding or changing system-wide resolved]
Identity=unix-group:netdev;unix-group:sudo
Action=org.freedesktop.resolve1.*
ResultAny=no
ResultInactive=no
ResultActive=yes
```

**Comment by kayrus** [comment]
I'll close this issue for now. However I'd like to get references to discussions regarding inability of detecting capabilities via AF_UNIX, while sockets can detect user ID and group.
