### ISSUE TITLE
fstab generated Requires= dependency on mount is missing escaping

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#18952]
**systemd version the issue has been seen with**
systemd 247.3 (though it's present in latest main)

**Expected behaviour you didn't see**
 Example contents of /etc/fstab:
```
LABEL=/mnt/d0   /mnt/d0         rtxfs x-systemd.requires=/dev/disk/by-partlabel/\\x2fmnt\\x2fd0 0 2
```
On v246 this correctly generates Requires= dependencies for /mnt/d0 that looks like:
```
Requires="dev-disk-by\\x2dpartlabel-\\x5cx2fmnt\\x5cx2fd0.device"
```

**Unexpected behaviour you saw**
On v247 the example incorrectly generates:
```
Requires="dev-disk-by\\x2dpartlabel-x2fmntx2fd0.device"
```

I've bisected this to 0645b83a40d1c782f173c4d8440ab2fc82a75006. cc @keszybz in case you have a quick fix. I can look at it tomorrow since it's bedtime here.

**Comment by keszybz** [comment]
Duh, I made a deep dive down into the parsing code, and it was mind numbing.
But it turns out that the bug report is buggy too: v246 does **not** behave like this:

```console
$ git describe
v246
$ cat fstab
LABEL=/mnt/d0   /mnt/d0         rtxfs x-systemd.requires=/dev/disk/by-partlabel/\\x2fmnt\\x2fd0 0 2
$ rm -rf /tmp/y && mkdir /tmp/y && SYSTEMD_FSTAB=fstab build/systemd-fstab-generator /tmp/{y,y,y}
$ grep Requires tmp/y/mnt-d0.mount
Requires=dev-disk-by\x2dpartlabel-\x5cx2fmnt\x5cx2fd0.device
```

I'll file a PR to restore the same behaviour.
I'm not sure if we ever didn't do escaping. Right now getmntent() returns the unescaped string already.

**Comment by anitazha** [comment]
Oh geez I'm so sorry the `Requires=` lines  I pasted were from `systemctl show -p Requires`. The actual file difference is as you described

v246 (good)
`Requires=dev-disk-by\x2dpartlabel-\x5cx2fmnt\x5cx2fd5.device`

v247+ (bad)
`Requires=dev-disk-by\x2dpartlabel-x2fmntx2fd5.device`

**Comment by keszybz** [comment]
Oh, OK. I got so caught up in the tests that I didn't see that the bug is actually not fixed ;(

PTAL now.
