### ISSUE TITLE
Journald parsing errors for namespaces get lost

### ISSUE THREAD

**Issue by amarao** [systemd/systemd#18951]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Ubuntu 20.10

**Linux kernel version used** (`uname -a`)
 > `Linux XPS13 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > If there is an additional namespace configuration for journald, and there is a typo in this config, error message about this typo get lost and is invisible to administrator.

**Unexpected behaviour you saw**
 > `journalctl -u systemd-journald@namespace.service` shows no errors if there is a typo in namespace configuration.

**Steps to reproduce the problem**
Create a namespace configuration:
```
echo -e '[Journal]\nStorage=moon\n' > /etc/systemd/journald@myspace.conf
systemctl start systemd-journald@myspace.conf
systemctl status systemd-journald@myspace.conf
```
Strace on journald shows there is an error message to stderr:
```
writev(2, [{iov_base="/etc/systemd/journald@myspace.co"..., iov_len=85}, {iov_base="\n", iov_len=1}], 2/etc/systemd/journald@myspace.conf:2: Failed to parse storage setting, ignoring: moon
) = 86
```
But this message is nowhere in the system journals. There is no way for operator to see if there is an error in configuration for journald or not.

**Comment by poettering** [comment]
Hmm, question is where to make namespaced journald log. Could be kmsg like the primary journald, or we could chain it to the main journald...

**Comment by amarao** [comment]
Fo my case (I have a separate  journal for very talkative application suite) I changed both  `StandadOutput` and `StandardError` to `journal` and they works very nicely. There was a clean nice error message in `systemctl status systemd-journald@myapp` and it looked consistent with other system services. I vow for `journal`.
