### ISSUE TITLE
machinectl bind: machinectl bind: Failed to mount: Invalid argument 

### ISSUE THREAD

**Issue by lotan** [systemd/systemd#18964]
**systemd version the issue has been seen with**
 > 247.3-1

**Used distribution**
  > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.11.2-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > machinectl bind should mount bind a host path

**Unexpected behaviour you saw**
 > machinectl bind results in error "Failed to bind mount: Failed to mount: No such file or directory"

**Steps to reproduce the problem**
 > Use machinectl bind in the documented way:
 > ```$ sudo machinectl bind --mkdir mycont /mnt/a /mnt/a```
 > Observe error message.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
-
```
Additional information: My container has CAP_SYS_ADMIN.

**Comment by poettering** [comment]
does the container use userns?

any chance you can test this with a 248 rc release?

**Comment by lotan** [comment]
In systemd-git 248.rc4.r21.ge39288193f this issue doesn't show anymore.
I'll just wait for release 248.
Thank you!
