### ISSUE TITLE
PID 1 heap corruption crash

### ISSUE THREAD

**Issue by bugaevc** [systemd/systemd#18970]
**systemd version the issue has been seen with**
 > v248~rc2

**Used distribution**
 > Fedora 34 (Workstation Edition Prerelease)

**Linux kernel version used** (`uname -a`)

 > `Linux badwolf 5.11.5-300.fc34.x86_64 #1 SMP Tue Mar 9 18:42:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

I'm not sure how to reproduce or diagnose it. But what happened was, during `dnf update`, at about the time DNF was updating the systemd package, PID 1 crashed with a heap corruption error:

```
(gdb) bt
#0  0x00007f60ec94958b in kill () from /lib64/libc.so.6
#1  0x000055da9b19ab68 in crash (sig=6) at ../src/core/main.c:256
#2  <signal handler called>
#3  0x00007f60ec949292 in raise () from /lib64/libc.so.6
#4  0x00007f60ec9328a4 in abort () from /lib64/libc.so.6
#5  0x00007f60ec98bcd7 in __libc_message () from /lib64/libc.so.6
#6  0x00007f60ec99394c in malloc_printerr () from /lib64/libc.so.6
#7  0x00007f60ec99482c in unlink_chunk.constprop () from /lib64/libc.so.6
#8  0x00007f60ec99509b in _int_free () from /lib64/libc.so.6
#9  0x00007f60ec998a48 in free () from /lib64/libc.so.6
#10 0x00007f60ecbbfb5d in closef.lto_priv () from /lib64/libselinux.so.1
#11 0x00007f60ecbc43cd in selabel_close () from /lib64/libselinux.so.1
#12 0x00007f60ecd8f199 in mac_selinux_finish () at ../src/basic/selinux-util.c:206
#13 0x000055da9b197655 in main (argc=5, argv=0x7ffebc1e6e48) at ../src/core/main.c:2913
```

There wasn't anything interesting around that in the journal. (I can't attach it here because I was not smart enough to `journalctl --sync` before force rebooting, oh well)

**Comment by keszybz** [comment]
This is already fixed by 39ad3f1c09.
