### ISSUE TITLE
Virtual wlan interface

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#18977]
Im trying to add a virtual wlan interface but im unable to do it or to find a description how to do it.
Should be equivalent to
```
iw dev wlan0 interface add wlan0_sta type managed addr 12:34:56:78:ab:cd
```
Is it possible using systemd-networkd?

**Comment by yuwata** [comment]
Currently not. Interesting.

**Comment by yuwata** [comment]
Waiting in #22502.
