### ISSUE TITLE
Incorrect Damned Lies configuration

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#18981]
Current configuration of the systemd project in GNOME [Damned Lies](https://l10n.gnome.org) still seems to point to a `master` branch instead of the correct `main` one. I am aware that there is now a Weblate primarily used, however I think that this should be fixed as well.

**Comment by poettering** [comment]
hmm, wa? I am the maintainer? tbh i couldn't tell you what damned lies was 5min ago? am I supposed to have set that up?

**Comment by poettering** [comment]
Hmm, i don't think i created this, i think someone else did, and I don't think i have an account there. might be something to ping the GNOME community about

**Comment by mrc0mmand** [comment]
Appears to be resolved: https://l10n.gnome.org/module/systemd/, closing.
