### ISSUE TITLE
smartd not issueing a standby request on my wd hard disk.

### ISSUE THREAD

**Issue by devbapidey** [systemd/systemd#18980]
**systemd version the issue has been seen with**
 > … 246.6-1ubuntu1.1

**Used distribution**
 > … Ubuntu 20.10

**Linux kernel version used** (`uname -a`)

 > `…` 5.8.0-44-generic x86_64

**CPU architecture issue was seen on**
 > … 64bit pentiam g4560

**Expected behaviour you didn't see**
 > … standby my second disk in 10min

**Unexpected behaviour you saw**
 > … Hard disk spinning forever

**Steps to reproduce the problem**
 > … I create a multi-seat setup using nvidia card by loginctl. Since then I see this issue. Issue is also occurs while all other users logged out.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
I have very low experience on debugging so help me out on that.

**Comment by poettering** [comment]
systemd is not smartd. Please contact the smartd community for help for questions about smartd.
