### ISSUE TITLE
Auto-generated dependent units aren't activated after reloading daemon if the target unit is started

### ISSUE THREAD

**Issue by ivanov17** [systemd/systemd#18983]
Hello. It's not a bug report, but I need advice about rightly using systemd in my case.

I have a task for executing scripts in a hierarchically organized directory. Scripts must start as the system boots up, also the script must be executed if it was changed or if it was added to the directory. 

```
/srv/project
├── abc
│   └── script.sh
├── def
│   └── script.sh
└── xyz
    └── script.sh
```

I thought it's a suitable case to try to implement it with systemd.

Because the hierarchy of the directory does not suppose to be changed, I use templates for service and path units. Path units monitor changes in script files and activate service units, which execute scripts if the triggering condition applies.

Also, I want to be able to add subdirectories to the directory, to which scripts can be added any time, so I don't know those names in advance. Therefore, I use a generator that reads the directory and creates symlinks like `project@xyz.path` and `project@xyz.service` in `project.target.wants/`.

Since the generator is executed at system boot, it creates symlinks only for subdirectories that already exist. If I'm adding a new subdirectory contains the script, the generator knows nothing about it. It seems that the only option is reloading of systemd daemon when a subdirectory is added.

Therefore, I use another path unit for monitoring changes in the directory. It activates a service unit, which reloads systemd daemon. Maybe automatically reload of the daemon is not a pretty good solution, but it works: if I add a new subdirectory, new symlinks will be added to `project.target.wants/`.

But there is another problem: new path units wouldn't be activated if `project.target` already started. It means that nothing monitors changes and new scripts aren't executed. If I restart `project.target`, all scripts in the directory are executed. But I need to execute only the new script that was just added to the directory.

I tried to use my configuration with *systemd 234* on *OpenSUSE 15.2* and with *systemd 246* on *Fedora 33*. I got the same results on both. 

Now I need advice. Probably, I made a mistake in the configuration. Or my issue should be solved differently. Finally, maybe I should solve it using other tools, without systemd at all. I've never used systemd for such things, so I'm not sure that I'm doing right.

Anyway, I want to thank the developers for the great tool which we have.

Below are my configuration files.

```
# /etc/systemd/system/project@.path
[Unit]
Description=detect changes in %i script
PartOf=project.target
ReloadPropagatedFrom=project.target

[Path]
PathChanged=/srv/project/%i/script.sh
Unit=project@%i.service
```

```
# /etc/systemd/system/project@.service
[Unit]
Description=run %i script
PartOf=project.target
ReloadPropagatedFrom=project.target
ConditionPathExists=|/srv/project/%i/script.sh

[Service]
Type=oneshot
WorkingDirectory=/srv/project/%i
ExecStart=/bin/bash script.sh
```

```
# /etc/systemd/system/project.target
[Unit]
Description=project target
Wants=project-reload.path

[Install]
WantedBy=default.target
```

```
# /etc/systemd/system/project-reload.path
[Unit]
Description=detect changes in directory

[Path]
PathChanged=/srv/project
Unit=project-reload.service
```

```
# /etc/systemd/system/project-reload.service
[Unit]
Description=reload systemd daemon

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl daemon-reload
```

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
