### ISSUE TITLE
DHCPv6 DUID options are under DHCPv4 section

### ISSUE THREAD

**Issue by seblu** [systemd/systemd#18996]
**systemd version the issue has been seen with**
 > $ systemctl --version
systemd 247 (247.3-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux hostname 5.11.0-seblu #1 SMP PREEMPT Tue Feb 16 15:56:00 CET 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
The DHCPv6 DUID related configurations settings in the `[DHCPv6]` section.

Network providers sometime require a custom DUID to obtain a lease. The DHCPv6 client use  `ClientIdentifier`, `DUIDType` and `DUIDRawData` to compute the DUID to send to the DHCPv6 server. This use to be in `[DHCP]` section, but with the split into `[DHCPv4]` and `[DHCPv6]` parameters, the `.network` files should look like this:
```ini
[Network]
DHCP=ipv6

[DHCPv6]
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=35:36:37:38:39:40:41:42
WithoutRA=solicit
```

**Unexpected behaviour you saw**

The previous `.network` configuration produce *Unknown key name* messages.
```
# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd
sd-device-monitor: No permission to stat PID1's netns, unable to determine if we are in host netns: Permission denied
Bus bus-api-network: changing state UNSET → OPENING
sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Bus bus-api-network: changing state OPENING → AUTHENTICATING
Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
timestamp of '/etc/systemd/network' changed
/etc/systemd/network/ilovelennart.network:20: Unknown key name 'ClientIdentifier' in section 'DHCPv6', ignoring.
/etc/systemd/network/ilovelennart.network:21: Unknown key name 'DUIDType' in section 'DHCPv6', ignoring.
/etc/systemd/network/ilovelennart.network:23: Unknown key name 'DUIDRawData' in section 'DHCPv6', ignoring.
```

And the working configuration use `[DHCPv4]` in order to configure DHCPv6 clients.

```ini
[Network]
DHCP=ipv6

[DHCPv4]
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=35:36:37:38:39:40:41:42

[DHCPv6]
WithoutRA=solicit
```

**Comment by yuwata** [comment]
Ouch, indeed...
