### ISSUE TITLE
systemd-analyze security does not consider TemporaryFileSystem=/

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#19000]
**systemd version the issue has been seen with**
247.3-1

**Used distribution**
Debian Unstable

**Linux kernel version used** (`uname -a`)
`5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux`

**Expected behaviour you didn't see**

The following configuration:

```
TemporaryFileSystem=/:ro
BindReadOnlyPaths=/bin /lib /lib64 /proc
```

Is even more locked down than `ProtectSystem=strict` because the service won't be able to access any unmentioned top-level directories - not even read-only.

`systemd-analyze security` doesn't seem to understand this and does not even award the `ProtectSystem=` points:

```
✗ ProtectSystem=    Service has full access to the OS file hierarchy
```

**Comment by poettering** [comment]
Duplicate of #15771
