### ISSUE TITLE
syslog facility of stream logs lost after restarting systemd-journald

### ISSUE THREAD

**Issue by fancy-rabbit** [systemd/systemd#19019]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > debian buster with buster-backports repo

**Linux kernel version used** (`uname -a`)

 > `5.4.56`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > after restarting systemd-journald, the _TRANSPORT=stdout logs will be transfered to syslog with correct facility and priority

**Unexpected behaviour you saw**
 > after systemd-journald was restarted, the _TRANSPORT=stdout logs lost the LOG_DAEMON facility and inherits the default LOG_USER

**Steps to reproduce the problem**
 > pdns-recursor write to stdout normally with --disable-syslog and the syslog facility is LOG_DAEMON
after restarting systemd-journald, the syslog facility changed to LOG_USER.
specifying different destination in rsyslog can be used to easily identify this (e.g. daemon.log vs user.log)

 > it seems that the call of log_level_from_string() in stdout_stream_load() (which restores the params of the streams from the state_file) cannot convert the PRIORITY=30 (30: LOG_DAEMON | LOG_INFO) in the state file under /run/systemd/journal/streams into correct priority value, 
https://github.com/systemd/systemd/blob/efd3be9de1dc07ec743912f3c166bbf17dbb20f5/src/journal/journald-stream.c#L753
i.e., log_level_from_string("30") returns -1.

**Additional program output to the terminal or log subsystem illustrating the issue**

The content of pdns-recursor.service: (which produces the logs)
```
# /lib/systemd/system/pdns-recursor.service
[Unit]
Description=PowerDNS Recursor
Documentation=man:pdns_recursor(1) man:rec_control(1)
Documentation=https://doc.powerdns.com
Wants=network-online.target nss-lookup.target
Before=nss-lookup.target
After=network-online.target

[Service]
ExecStart=/usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no
User=pdns
Group=pdns
Type=notify
Restart=on-failure
StartLimitInterval=0
RuntimeDirectory=pdns-recursor

# Tuning
LimitNOFILE=16384

# Sandboxing
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_CHOWN
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_CHOWN
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
ProtectControlGroups=true
ProtectHome=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectSystem=full
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictRealtime=true
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
```

The Content of the corresponding state_file in /run/journald/streams:
```
# This is private data. Do not parse
PRIORITY=30
LEVEL_PREFIX=1
FORWARD_TO_SYSLOG=0
FORWARD_TO_KMSG=0
FORWARD_TO_CONSOLE=0
STREAM_ID=e309365cafe04e4da8f88fa530104448
IDENTIFIER=pdns_recursor
```

**Comment by poettering** [comment]
Any chance you can give #19022 a quick test?

**Comment by fancy-rabbit** [comment]
@poettering https://github.com/systemd/systemd/pull/19022 works as expected in this scenario. Thanks.
will this be merged into 248?
