### ISSUE TITLE
Escape speical characters inside Environment file

### ISSUE THREAD

**Issue by GreatBahram** [systemd/systemd#19014]
Hello there,

I have a environment file inside `/etc/systemd/system/myservice.service.d/auth.conf ` that contains the following data:
```shell
Environment="MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(uid=%s)"
```

when Systemd loads this file, it will somehow replace the `%s` with `/bin/bash` and I couldn't find a logical way to stop it. I want to have `%s`. I tried `\%`, `\\%`, `\%\s`, .... .

Any suggestion?

**Comment by smod** [comment]
Hello,

According to [documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) it should be `%%s`, same format as `printf`.

**Comment by poettering** [comment]
Please always consult the documentation first

**Comment by GreatBahram** [comment]
Thanks!
