### ISSUE TITLE
Allow controlling of prefix route metric in [address] and [dhcp*]

### ISSUE THREAD

**Issue by msoltyspl** [systemd/systemd#19028]
**Is your feature request related to a problem? Please describe.**

There is no easy way to control the metric of prefix routes defined via [address] or [dhcp*] sections

**Describe the solution you'd like**

Similarly to how we can define metric in [Route] section, it would be nice to be able to do that at [address]/[[dhcp*] level, so the equivalent of the following is possible in systemd:

`ip ad add 192.168.50.50/24 dev eno1 metric 123`

which normally results with a prefix route being added with required metric:

```
ip ro sh
192.168.50.0/24 dev eno1 proto kernel scope link src 192.168.50.50 metric 123
```

In context of dhcp, the already present RouteMetric option could be taken into account, as it currently isn't, for example:

```
default via 10.13.36.1 dev eno1 proto dhcp src 10.13.37.254 metric 200 
10.13.36.0/23 dev eno1 proto kernel scope link src 10.13.37.254 
10.13.36.1 dev eno1 proto dhcp scope link src 10.13.37.254 metric 200 
```

Note missing metric on prefix route. This is generated by the following .network file config:

```
[DHCP]
UseDNS=true
UseDomains=true
UseRoutes=true
RouteMetric=200
```

**Describe alternatives you've considered**

The only workaround is to block automatic prefix route creation, and create it independently via [route] section, but that's messy. The dhcp case seems impossible to control.

**The systemd version you checked that didn't have the feature you are asking for**

systemd 247 (247.4-2-arch), also current origin/master as of writing of this RFE.

**Comment by yuwata** [comment]
Waiting in #19344.
