### ISSUE TITLE
Tunnel interfaces are tied to the physical ones, breaks multi-homed systems  

### ISSUE THREAD

**Issue by afpd** [systemd/systemd#19033]
Consider the system with two Ethernet interfaces, eno1 and eno2 with dynamic routing to lo (BGP for example).
Since system is multi-homed there is service IP assigned to a lo  - 10.7.2.8/32.
Goal is to have a gre tunnel to that system. 
I've tried 
```
# 30-gre-to-pl.netdev
[NetDev]
Name=gre-pl
Kind=gre
MTUBytes=1480

[Tunnel]
Remote=10.15.14.222
Local=10.7.2.8
```
```
# 30-gre-to-pl.network 
[Match]
Name=gre-pl

[Network]
Address=10.4.3.2/30
```
Then system-networkd expect that tunnel is managed by other interface, for example eno1
```
# 20-eno1.network
[Match]
Name=eno1

[Network]
Address=192.168.14.164/29
Tunnel=gre-pl
```
Problem with that approach is that one wold get gre-pl@eno1 interface which is tied to eno1, and if interface eno1 goes down, gre tunnel is no longer usable.

However, manually created gre tunnel get @NONE binding:
```
# ip tunnel add  jjj mode gre remote 10.15.14.222 local 10.7.2.8
# ip link ls jjj
8: jjj@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> 
and such tunnel performs as expected in multi-homed environment independently if one on the eno1 or eno2 interfaces are going down.
```
Solution would be to have an ability to bring up virtual interfaces without the binding to the existing ones. 
Gre is to demonstrate the valid use case, same problem may arise with other virtual interfaces.
I didn't find a way to bring a virtual interface regardless of the physical ones.

**Comment by yuwata** [comment]
Please try to use `Independent=yes` in your .netdev file. See systemd.netdev(5) man page. Closing. If it does not work, feel free to request reopen this page.
