### ISSUE TITLE
Predictable network interface name fails and udev events messed up

### ISSUE THREAD

**Issue by aleksander0m** [systemd/systemd#19038]
Issue found in **Arch Linux** running with systemd **247.3-1**.

When a Netgear AC340U USB modem is plugged in the host (a WWAN module that exposes a MBIM cdc-wdm/net port pair), the predictable interface name udev rules try to rename the exposed `wwan0` interface as `wwp0s20f0u8u3c2i12`, but that seems to be failing, and the net interface is kept with the original name:

```
$ ip addr
28: wwan0: <BROADCAST,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 36:d2:e2:d4:a3:87 brd ff:ff:ff:ff:ff:ff
```

What do these renaming rules when the target network interface name is longer than `IFNAMSIZ-1`?

Is that possibly the reason why the interface rename fails? (as `wwp0s20f0u8u3c2i12` is 18 chars long, greater than `IFNAMSIZ-1=15`)

The outcome of the failure is a bit bad as it leads to several inconsistent states:

- One of the udev "add" events reported, the one containing all applied udev tags, is for the `wwp0s20f0u8u3c2i12` name, even if the interface doesn't end up renamed. This confuses a lot applications relying on this event, like `ModemManager`, which ends up failing because the network interface doesn't exist (and no "remove" event was emitted for it)

- In addition to that, the non-renamed `wwan0` interface is left without any common udev tag applied, so not even restarting `ModemManager` would help to use the modem (i.e. even if the userspace app finds the net interface without a udev event, the interface still lacks the necessary udev tags to be usable, like `ID_MM_CANDIDATE`).

```
$ sudo udevadm info -p /sys/class/net/wwan0 
P: /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/net/wwan0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/net/wwan0
E: DEVTYPE=wwan
E: INTERFACE=wwan0
E: IFINDEX=28
E: SUBSYSTEM=net
E: ID_RENAMING=1
```

There is no issue observed as soon as predictable interface names is disabled with `ln -s /dev/null /etc/systemd/network/99-default.link`.

This AC340U is a bit peculiar, not sure if related to the issue itself or not. This device boots initially with vid:pid 0x1199:0x0fff exposing a cdc-wdm+net; and as soon as it boots, it reboots itself into vid:pid 0x1199:0x9051 exposing a cdc-wdm+net plus a disk. The dmesg output shows this re-enumeration done:  [ac340u-dmesg.txt](https://github.com/systemd/systemd/files/6164820/ac340u-dmesg.txt)

Once it's booted on the 2nd final composition, it looks like this:
```
T:  Bus=01 Lev=02 Prnt=04 Port=02 Cnt=01 Dev#= 32 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  2
P:  Vendor=1199 ProdID=9051 Rev=00.06
S:  Manufacturer=Sierra Wireless, Incorporated
S:  Product=AirCard 340U
S:  SerialNumber=013323002267632
C:  #Ifs= 3 Cfg#= 2 Atr=80 MxPwr=500mA
I:  If#=0xc Alt= 0 #EPs= 1 Cls=02(commc) Sub=0e Prot=00 Driver=cdc_mbim
I:  If#=0xd Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=02 Driver=cdc_mbim
I:  If#=0x9 Alt= 0 #EPs= 2 Cls=08(stor.) Sub=06 Prot=50 Driver=usb-storage
```

The attached `udevadm monitor` output shows the detailed info of all events emitted: 
[ac340u-udevadm-monitor.txt](https://github.com/systemd/systemd/files/6164848/ac340u-udevadm-monitor.txt)

Filtering out the events that ModemManager monitors, e.g. just those for the usbmisc and net subsystems, we can see the mixup easily; again this includes also the USB re-enumeration done by the device itself:

```
UDEV  [261376.540600] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/usbmisc/cdc-wdm0 (usbmisc)
UDEV  [261376.544660] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/net/wwp0s20f0u8u3c2i12 (net)
UDEV  [261378.942142] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/net/wwan0 (net)
UDEV  [261378.980199] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/usbmisc/cdc-wdm0 (usbmisc)

// These previous events are the initial enumeration; we get an add event for wwp0s20f0u8u3c2i12 but the interface isn't really renamed, and we get a remove event for wwan0 instead.

UDEV  [261379.594987] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/usbmisc/cdc-wdm0 (usbmisc)
UDEV  [261379.597120] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.3/1-8.3:2.12/net/wwp0s20f0u8u3c2i12 (net)

// And these two previous events are the ones during the re-enumeration, again we get an add event for wwp0s20f0u8u3c2i12 and again the interface is really wwan0 still
```

**Comment by poettering** [comment]
> What do these renaming rules when the target network interface name is longer than `IFNAMSIZ-1`?

We won't apply it as ifname if the name is too long. On newer kernels we might apply it as "altname" however.

I am a bit puzzled by this: a name that is longer than IFNAMSIZ-1 shouldn't even be something we can give the kernel?

**Comment by aleksander0m** [comment]
> 
> >    What do these renaming rules when the target network interface name is longer than IFNAMSIZ-1?
> 
> We won't apply it as ifname if the name is too long. On newer kernels we might apply it as "altname" however.
> 
> I am a bit puzzled by this: a name that is longer than IFNAMSIZ-1 shouldn't even be something we can give the kernel?

Oh, if the new name is not even attempted to be changed, then the problem is not that the predictable name setting fails; that should not be even attempted.

The only problem then is the wrong udev "add" event emitted with the new never-applied name (and the lack of the "add" event for the old kept name). Given that is udev the one doing the interface rename and the emission of the add event, I guess there may be some issue in between that wrongly assumes the interface renaming will be done before it's truly done? Or something like that?

**Comment by aleksander0m** [comment]
> On newer kernels we might apply it as "altname" however.

This is with kernel 5.11.5-arch1-1. We wouldn't expect to have udev "add" events for the altnames, though, right?

**Comment by aleksander0m** [comment]
> Fix is waiting in #19047. @aleksander0m If possible, could you test the PR?

Lovely, thanks! will test it right away

**Comment by aleksander0m** [comment]
@yuwata it worked! the name is kept as wwan0 in all udev events now. I applied your patch on top of 248rc4, and this is the result of the events ModemManager is interested in:
```
UDEV  [580.052329] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/usbmisc/cdc-wdm0 (usbmisc)
UDEV  [580.064963] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/net/wwan0 (net)
UDEV  [582.740283] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/net/wwan0 (net)
UDEV  [582.759532] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/usbmisc/cdc-wdm0 (usbmisc)
UDEV  [583.209662] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/usbmisc/cdc-wdm0 (usbmisc)
UDEV  [583.222548] add      /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2:2.12/net/wwan0 (net)
```

The full udevadm monitor log is here: 
[20210318 - ac340u - probing fixed.txt](https://github.com/systemd/systemd/files/6167536/20210318.-.ac340u.-.probing.fixed.txt)

**Comment by yuwata** [comment]
@aleksander0m Thank you!
