### ISSUE TITLE
udevd: some uevents are not be processed

### ISSUE THREAD

**Issue by gaoyi1988** [systemd/systemd#19039]
**systemd version the issue has been seen with**
 > 247

**Expected behaviour you didn't see**
 > The uevent is correctly processed.

**Unexpected behaviour you saw**
 > The uevent is not processed.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
[root@localhost eth104]# cat ly-162438--162635 | grep eth104
Mar 16 16:25:49 host-192-168-2-5 systemd-udevd[3494148]: eth104: Device (SEQNUM=3177426, ACTION=add) is queued
Mar 16 16:25:51 host-192-168-2-5 systemd-udevd[3494148]: eth104: sd-device-monitor: Passed 206 byte to netlink monitor
```
PID 3494148 is the main process and there is no child process in log.

**Comment by gaoyi1988** [comment]
By analyzing the code, I think eca195ec23fb4ed3ece26b55f85c5eefa662e967 introduces a problem.

event_source_disable called in event_queue_start can just prevent received kill_workers_event later.
If we received uevent and kill_workers_event both, uevent may not be processed.

**Comment by yuwata** [comment]
Are there any relevant log messages from udev main process?

**Comment by yuwata** [comment]
> event_source_disable called in event_queue_start can just prevent received kill_workers_event later.
If we received uevent and kill_workers_event both, uevent may not be processed.

Hmm. `kill_workers_event` is a timer event source, it does not receive anything.

If a uevent comes first, then `kill_workers_event` is disabled by `on_uevent()` -> `event_queue_start()` -> `event_source_disable()`.
If `kill_workers_event` timer is triggered first, then a later uevent will spawn a worker by `on_uevent()` -> `event_queue_start()` -> `event_run()` -> `worker_spawn()`.

I think it is skeptical that workers are killed by `kill_workers_event` timer in your issue. `manager_kill_workers()` is called in various places. Did you really see `"Cleanup idle workers"` in debug log?

**Comment by gaoyi1988** [comment]
@yuwata 
Sorry, There is no problem in kill_workers_event. The real problem is in event_queue_start https://github.com/systemd/systemd/blob/main/src/udev/udevd.c#L924.

When rules are changed, manager_reload will be called, and kill the workers.

The problem may happened like follow:
> 1. Reveived uevent1: event_queue_start()-> event_run()->device_monitor_send_device()
> 2. Reveived uevent2:  event_queue_start()-> manager_reload() -> manager_kill_workers()
> 3. child is received uevent1 and SIGTERM, and exit.

So uevent1 will not be processed.

The log has the “timestamp changed” content.
```
Mar 16 16:25:51 host-192-168-2-5 systemd-udevd[3494148]: eth104: sd-device-monitor: Passed 206 byte to netlink monitor
Mar 16 16:25:51 host-192-168-2-5 systemd-udevd[3494148]: timestamp of '/etc/udev/rules.d' changed
```

**Comment by gaoyi1988** [comment]
@yuwata 
I have verify https://github.com/systemd/systemd/pull/19051 can solve this problem.
