### ISSUE TITLE
resolved (with caching enabled) returns IPv6 IP for e.g. retrace.fedoraproject.org despite lack of global IPv6 connectivity

### ISSUE THREAD

**Issue by AdamWill** [systemd/systemd#19049]
This is kind of a follow-on to https://github.com/systemd/systemd/issues/18972 , but @mcatanzaro suggested it should be a new issue as it does not appear to be caused by the stub resolver.

With the `systemd-248~rc2-8.fc34.x86_64` build that backports the latest fix for that bug and has caching enabled, I cannot reach `retrace.fedoraproject.org`. See the output of various commands @mcatanzaro suggested:

    [adamw@xps13k ~]$ ping -v retrace.fedoraproject.org
    ping: connect: Network is unreachable
    [adamw@xps13k ~]$ resolvectl query retrace.fedoraproject.org
    retrace.fedoraproject.org: 2620:52:3:1:dead:beef:cafe:c005 -- link: wlp58s0
                               (retrace03.rdu-cc.fedoraproject.org)

    -- Information acquired via protocol DNS in 2.3ms.
    -- Data is authenticated: no; Data was acquired via local or encrypted transport: no
    -- Data from: cache
    [adamw@xps13k ~]$ dig @127.0.0.53 retrace.fedoraproject.org

    ; <<>> DiG 9.16.11-RedHat-9.16.11-5.fc34 <<>> @127.0.0.53 retrace.fedoraproject.org
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47990
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 65494
    ;; QUESTION SECTION:
    ;retrace.fedoraproject.org.	IN	A

    ;; ANSWER SECTION:
    retrace.fedoraproject.org. 53	IN	CNAME	retrace03.rdu-cc.fedoraproject.org.
    retrace03.rdu-cc.fedoraproject.org. 6953 IN A	8.43.85.61

    ;; AUTHORITY SECTION:
    retrace03.rdu-cc.fedoraproject.org. 53 IN AAAA	2620:52:3:1:dead:beef:cafe:c005

    ;; Query time: 0 msec
    ;; SERVER: 127.0.0.53#53(127.0.0.53)
    ;; WHEN: Thu Mar 18 13:32:35 PDT 2021
    ;; MSG SIZE  rcvd: 129

    [adamw@xps13k ~]$ dig @1.1.1.1 retrace.fedoraproject.org

    ; <<>> DiG 9.16.11-RedHat-9.16.11-5.fc34 <<>> @1.1.1.1 retrace.fedoraproject.org
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5324
    ;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;retrace.fedoraproject.org.	IN	A

    ;; ANSWER SECTION:
    retrace.fedoraproject.org. 300	IN	CNAME	retrace03.rdu-cc.fedoraproject.org.
    retrace03.rdu-cc.fedoraproject.org. 86400 IN A	8.43.85.61

    ;; Query time: 715 msec
    ;; SERVER: 1.1.1.1#53(1.1.1.1)
    ;; WHEN: Thu Mar 18 13:32:43 PDT 2021
    ;; MSG SIZE  rcvd: 101

With the `-8` build - whose only difference to `-7` is that caching is disabled - things work OK. This is on a system with no global IPv6 connectivity.

I don't think this is the same as #16913 because I don't think the record has the same attributes described there. `retrace.fedoraproject.org` is a CNAME for `retrace03.rdu-cc.fedoraproject.org.` in both the A and AAAA responses.

**Comment by nanonyme** [comment]
I managed some level of reproduction with RC4 but I'm not sure if this is 1:1 same case as this involved stub resolver. Basically
```
resolvectl flush-caches
dig AAAA retrace.fedoraproject.org
ping retrace.fedoraproject.org
```
systemd-resolved will in this case deal out only the AAAA record it got from earlier query and not fetch any A records so. The incriminating fact here is that if you do in this scenario
```
dig A retrace.fedoraproject.org
ping retrace.fedoraproject.org
```
then dig will give expect output *but* ping will still fail since varlink interface keeps dealing out the AAAA only response.

**Comment by nanonyme** [comment]
If on the other hand I do this with IPv6 only having link-local support (now with again having varlink socket)
```
resolvectl query retrace.fedoraproject.org
resolvectl query retrace.fedoraproject.org
```
then ping works but first resolvectl query gives both AAAA and A records whereas second only gives A record! So even when in this case caching seems to work, cached result is different than original uncached result.

**Comment by nanonyme** [comment]
*But* just as counter-example:
```
resolvectl flush-caches
resolvectl query www.youtube.com
resolvectl query www.youtube.com
```
here first query gives all responses whereas latter gives only AAAA.

**Comment by nanonyme** [comment]
@poettering so seems all in all it's possible to get cache go into a bad state through multiple different methods, sometimes with A records only, sometimes with AAAA records only. Things only seem to work consistently with cache on in a system that has both IPv4 and IPv6 support (then cache will just be silently broken with no user-visible impact).

**Comment by nanonyme** [comment]
Looks possibly related to https://github.com/systemd/systemd/issues/19003

**Comment by bugaevc** [comment]
> Looks possibly related to #19003 

I don't think it is. #19003 is about mDNS being split between IPv4 and IPv6 scopes, which regular DNS is not.

**Comment by nanonyme** [comment]
Both of these seem to be about systemd-resolved trying to be overly smart and returning partial response.

**Comment by yuwata** [comment]
I am not sure it is a right way, but PR #19064 fixes the issue for me. I tested the reproducer in https://github.com/systemd/systemd/issues/19049#issuecomment-803085600.

**Comment by poettering** [comment]
@AdamWill @nanonyme any chance you can test #19079? I am pretty sure that's your fix, but I only gave it light testing so far myself

**Comment by nanonyme** [comment]
@yuwata any chance making a test build with these patches included and cache enabled? (but with automatic promotion to stable disabled) Would be easier to test.

**Comment by yuwata** [comment]
@nanonyme 
rawhide: https://koji.fedoraproject.org/koji/buildinfo?buildID=1726679
f34: https://koji.fedoraproject.org/koji/buildinfo?buildID=1726681

**Comment by AdamWill** [comment]
@yuwata can you create an update for F34 also? Thanks.

**Comment by yuwata** [comment]
Hmm, I cannot push update... What I missed? Only builder (in this case @keszybz) can push update?
```
$ fedpkg update
Password: 
Could not execute update: Could not generate update request: Authentication failed
A copy of the filled in template is saved as bodhi.template.last
```

**Comment by AdamWill** [comment]
huh, not sure. You can try through the web UI? I could do it, but if I create the update, I can't leave karma for it.

**Comment by yuwata** [comment]
Oh. Done. https://bodhi.fedoraproject.org/updates/FEDORA-2021-ea92e5703f

**Comment by nanonyme** [comment]
Okay, this fixes the two resovectl query cases. This does *not* the case where stub resolver is used to pre-fill cache. It's a different bug though than @AdamWill's clearly. Should I create yet another case for that?

**Comment by mcatanzaro** [comment]
> Should I create yet another case for that?

Yes please.

**Comment by nanonyme** [comment]
Okay. Created https://github.com/systemd/systemd/issues/19095 as follow-up. I can't tell if that's a regression anymore but there's some cases still that might end up broken because of that.
