### ISSUE TITLE
'systemd-run --slice-inherit' missing bash/zsh completion

### ISSUE THREAD

**Issue by mcatanzaro** [systemd/systemd#19044]
systemd-248rc2

Minor wart: systemd-run has shell completion for `--slice` but is missing autocompletion for `--slice-inherit` which seems to have been forgotten in https://github.com/systemd/systemd/commit/2c7039b3169d736a98ca1cb1e03129f12c2ab6ed.

**Comment by yuwata** [comment]
Fix is waiting in #19057. If possible, please test the PR, especially, if you use zsh. I am not familiar with zsh.
