### ISSUE TITLE
Applications/services crash recovery

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#19061]
**Is your feature request related to a problem? Please describe.**
It is not related to any problem. It is about not restarting app from start, so user must provide some steps again.

**Describe the solution you'd like**
Kernel supports checkpoint/restore from some time. I think about provide daemon, which monitor for app crash and do checkpoint in that moment for application request that. It is necessary to support for restore mechanism from this app. For example app must support argument of ident/path for file of checkpoint. App does not load full memory, because it will provide to next crash case, but loads some information, like opened tabs/files. Of course, app will also show error message and maybe sent info to developers.

**Describe alternatives you've considered**
Nothing.

**The systemd version you checked that didn't have the feature you are asking for**

** Also **
I am not too good developer/app designer, so I am not known it is easy to implement and for usage by app developer. In my mind, it's better than save app state each time. If my idea was realized, then app must only provide save state on exit and recovery procedure. The idea makes user happier, because in some cases he/she ever would not known that app crash.

**Comment by poettering** [comment]
Desktops used to provide state saving/restoring infra for decades, but they were left unused and eventually they all stripped them to my knowledge.

I am pretty sure this is something to better bring up with GNOME or so, i.e. the folks who provide the destop app execution environment. I doubt doing something like this in systemd is useful for user-facing apps..

Sorry!
