### ISSUE TITLE
Debian armhf(armv7l): Assertion '(unsigned long) safe_personality(current) == current' failed at src/test/test-seccomp.c:837

### ISSUE THREAD

**Issue by emojifreak** [systemd/systemd#19060]
**systemd version the issue has been seen with**
 
Debian package 247.3-3.

**Used distribution**
Debian 11 Bullseye (testing) as of 19 March 2021.
Downstream bug report at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982929
@mbiebl requested me to bring that to the upstream.

**Linux kernel version used** (`uname -a`)
autopkgtest qemu testbed for armhf.

**CPU architecture issue was seen on**
qemu-system-arm

**Expected behaviour you didn't see**
autopkgtest of Debian systemd passes.

**Unexpected behaviour you saw**
`root-unittest` and `upstream` tests fail by
root-unittests-stderr:28315:Assertion '(unsigned long) safe_personality(current) == current' failed at src/test/test-seccomp.c:837, function test_lock_personality(). Aborting.
upstream-stdout:4788:Assertion '(unsigned long) safe_personality(current) == current' failed at src/test/test-seccomp.c:837, function test_lock_personality(). Aborting.

**Steps to reproduce the problem**
One needs to install the very latest version of autopkgtest that supports armhf (armv7l) qemu testbed.
On Debian bullseye host with any (incl. amd64) CPU architecture:

```
#!/bin/sh
if [ ! -d autopkgtest ]; then
   git clone https://salsa.debian.org/ci-team/autopkgtest.git
fi

if [ ! -r /var/tmp/autopkgtest-sid-armhf.qcow2 ]; then
  sudo ./autopkgtest/tools/autopkgtest-build-qemu --arch=armhf --boot=efi sid /var/tmp/autopkgtest-sid-armhf.qcow2
fi
./autopkgtest/runner/autopkgtest --timeout-factor=3 -B -u user -o /var/tmp/log-systemd systemd -- qemu --dpkg-architecture=armhf --boot=efi --ram-size=3072 --timeout-reboot=300 --show-boot /var/tmp/autopkgtest-sid-armhf.qcow2
cat /var/tmp/log-systemd/summary
```

**Additional program output to the terminal or log subsystem illustrating the issue**

**Comment by poettering** [comment]
hmm, armhf is 32bit arm in LE for both kernel and userpace? Does seccomp even exist for that arch?

Most likely, unless a patch is provided this won't be fixed. We don't have this arch around.

**Comment by poettering** [comment]
Hmm, or is `qemu-system-arm` the weird thing where qemu translates code in userspace, i.e. not full-system virtualization, but just of isolated processes? I mean, that's hardly surprising to fail then. seccomp cannot possibly work in such an environment: it runs as arch X, would thus install filters for arch X and then the filters are suppsoed to enforced in syscalls of arch Y.

Quite frankly, if you do such userpace virtualization, then you get to keep the pieces, it's just a mess. If there's any chance you to get this working, please work with the qemu and libseccomp people. But I think we should close this here. This is not actionable to us, we just consume the library and the kernel interface, and if qemu doesn't translate things correctly (which I think it has every right to), then we can't do anything about it.

**Comment by bluca** [comment]
> Hmm, or is qemu-system-arm the weird thing where qemu translates code in userspace, i.e. not full-system virtualization, but just of isolated processes? 

I think you are referring to qemu-user-static? If that's the case that's different, qemu-system-arm is a full VM environment, the repro steps include the image build (autopkgtest-build-qemu)

**Comment by emojifreak** [comment]
Yes, qemu-system-arm is a full VM environment, and systemd should behave in the same way as it does on a barebone armv7l hardware. For support of seccomp in Debian armhf, I am unsure. @mbiebl could you comment on the seccomp status in Debian armhf??

**Comment by bluca** [comment]
Did a quick check under the same qemu+image and gdb, and `safe_personality` returns `8650752` while `current` is `0`

https://github.com/systemd/systemd/blob/main/src/test/test-seccomp.c#L895

To reproduce this under gdb, build the image with the `autopkgtest-build-qemu` command mentioned in the report, and then run the vm:

```
# in the vm
su
echo 'deb http://deb.debian.org/debian-debug sid-debug main' >> /etc/apt/sources.list
apt update
apt install --yes systemd-tests gdb systemd-tests-dbgsym systemd-dbgsym libc6-dbg
gdb /usr/lib/systemd/tests/test-seccomp
```
