### ISSUE TITLE
Key shortcut to run KMS-based process monitor

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#19062]
**Is your feature request related to a problem? Please describe.**
Sometimes entire session hangs, so there is no simple way to kill trouble process.

**Describe the solution you'd like**
User should press keyboard shortcut for current vt or ctrl+alt+backspace twice, so registered app was ran with reowned privileges to current screen for this app. Application should provide list of process, way to kill each, kill entire session or restart system. This should be KMS app. This app should have higher priority/lower nice level or similar technique to give it maximum performance. 

**Describe alternatives you've considered**
Nothing.

**Comment by poettering** [comment]
I am sorry, but we are not in the business of UIs. This certainly would be useful to have, but I am pretty sure that's out of focus for us and would be better placed in GNOME, maybe as part of the gdm project or so.

Hope that makese sense?
