### ISSUE TITLE
RoutesToDNS causes broken route if DNS server is not in same network

### ISSUE THREAD

**Issue by fxri** [systemd/systemd#19077]
**systemd version the issue has been seen with**
v246.10

**Used distribution**
Self-compiled

**Expected behaviour you didn't see**
 `RoutesToDNS=yes` autogenerates a route to the DNS server. Taking into account that the server is not in the same network the route incorporates that the server must be reached through the gateway that was also given by the DHCP server.

**Unexpected behaviour you saw**
 The route to the DNS server is set up, but without specifying the gateway and local route scope. As the DNS server is not reachable without going through the gateway, DNS resolution fails afterwards.

**Steps to reproduce the problem**
 - Setup a DHCP server that passes along a gateway IP and also a DNS server outside of the current subnet
 - - e.g.`dnsmasq --dhcp-option=3,192.168.188.1 --dhcp-option=6,8.8.8.8 --dhcp-range=192.168.188.201, 192.168.188.210,2h`
 - (On another device) Enable DHCP for systemd-networkd and also set RoutesToDNS=yes in the DHCPv4 section:
 ```text
[Match]
Name=lan0

[Network]
DHCP=ipv4

[DHCPv4]
RoutesToDNS=yes
```
 - Reload systemd-networkd
 - Try resolving a DNS name: `nslookup google.com`

**Additional program output to the terminal or log subsystem illustrating the issue**
Output of `ip route` in error case. Note how the DNS server route doesn't mention the gateway:
```text
# ip route
default via 192.168.188.1 dev lan0 proto dhcp src 192.168.188.208 metric 1024 
8.8.8.8 dev lan0 proto dhcp scope link src 192.168.188.208 metric 1024 
192.168.188.0/24 dev lan0 proto kernel scope link src 192.168.188.208 
192.168.188.1 dev lan0 proto dhcp scope link src 192.168.188.208 metric 1024
```
Debug output of systemd-networkd:
```text
Mar 22 14:48:11 dummydev systemd-networkd[351]: lan0: DHCP: No routes received from DHCP server: No data available
Mar 22 14:48:11 dummydev systemd-networkd[351]: lan0: Configuring route: dst: 192.168.188.1/32, src: n/a, gw: n/a, prefsrc: 192.168.188.208, scope: link, table:
 main, proto: dhcp, type: unicast
Mar 22 14:48:11 dummydev systemd-networkd[351]: lan0: Configuring route: dst: n/a, src: n/a, gw: 192.168.188.1, prefsrc: 192.168.188.208, scope: global, table: 
main, proto: dhcp, type: unicast
Mar 22 14:48:11 dummydev systemd-networkd[351]: lan0: Configuring route: dst: 8.8.8.8/32, src: n/a, gw: n/a, prefsrc: 192.168.188.208, scope: link, table: main,
 proto: dhcp, type: unicast
```

**Comment by yuwata** [comment]
Fix is waiting in #19286.
