### ISSUE TITLE
systemd-detect-virt --container doesn't detect docker env

### ISSUE THREAD

**Issue by psaini79** [systemd/systemd#19072]
**systemd version the issue has been seen with**

rpm -qa | grep systemd
systemd-libs-219-78.0.3.el7_9.3.x86_64
systemd-219-78.0.3.el7_9.3.x86_64
systemd-sysv-219-78.0.3.el7_9.3.x86_64

**Linux kernel version used** (`uname -a`)
 `5.4.17-2036.102.0.2.el7uek.x86_64`

**Expected behaviour you didn't see**
The command `systemd-detect-virt --container ` must return container or docker.

**Unexpected behaviour you saw**
It returns "None"

**Steps to reproduce the problem**
 systemd-detect-virt --container
none

**Comment by bugaevc** [comment]
This has been fixed in https://github.com/systemd/systemd/pull/17902
