### ISSUE TITLE
Caching partial queries (only A or AAAA) done by stub resolver prevent fetching full result

### ISSUE THREAD

**Issue by nanonyme** [systemd/systemd#19095]
**systemd version the issue has been seen with**
 > systemd-248~rc4-3.fc34.x86_64

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `Linux neutronitykki 5.11.7-300.fc34.x86_64 #1 SMP Wed Mar 17 18:43:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Queries done through stub resolver break subsequent queries by nss-resolve

**Unexpected behaviour you saw**
 > Partial query (eg AAAA) done through stub prevent getting full result until cache expires.

**Steps to reproduce the problem**
> resolvectl query retrace.fedoraproject.org 
> resolvectl flush-caches
> dig AAAA retrace.fedoraproject.org
> resolvectl query retrace.fedoraproject.org

**Additional program output to the terminal or log subsystem illustrating the issue**
First resolvectl query in repro steps gives full response, second only AAAA response.

**Comment by yuwata** [comment]
Hmm? I cannot reproduce this...
```
$ resolvectl flush-caches 
$ dig AAAA retrace.fedoraproject.org

; <<>> DiG 9.11.28-RedHat-9.11.28-1.fc33 <<>> AAAA retrace.fedoraproject.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23528
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;retrace.fedoraproject.org.	IN	AAAA

;; ANSWER SECTION:
retrace.fedoraproject.org. 299	IN	CNAME	retrace03.rdu-cc.fedoraproject.org.
retrace03.rdu-cc.fedoraproject.org. 21599 IN AAAA 2620:52:3:1:dead:beef:cafe:c005

;; Query time: 1199 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Mar 24 01:16:44 JST 2021
;; MSG SIZE  rcvd: 113

$ resolvectl query retrace.fedoraproject.org
retrace.fedoraproject.org: 8.43.85.61          -- link: wlp59s0
                           2620:52:3:1:dead:beef:cafe:c005 -- link: wlp59s0
                           (retrace03.rdu-cc.fedoraproject.org)

-- Information acquired via protocol DNS in 2.2776s.
-- Data is authenticated: no
```

**Comment by nanonyme** [comment]
Wait, this no longer reproduces for me either. I'm quite sure it reproduced for me earlier today. Closing as invalid.
