### ISSUE TITLE
Service does not join mount namespace

### ISSUE THREAD

**Issue by Melab** [systemd/systemd#19136]
This issue is happening with systemd 245 on Ubuntu 20.04 with Linux 5.8.0-48-generic.

I have written a script that sets up an alternate mount namespace to run various services in. Services do not join its mount namespace when `JoinsNamespaceOf=` is specified.

I wrote two service files that replicate the problem.

`loop1.service`:

     [Unit]
    Description=Loop 1
    
    [Service]
    ExecStart=/bin/bash -c "while true; do :; done"
    PrivateTmp=true

`loop2.service`:

    [Unit]
    Description=Loop 2
    Requires=loop1.service
    JoinsNamespaceOf=loop1.service
    
    [Service]
    ExecStart=/bin/bash -c "while true; do :; done"

Both services run in different mount namespaces when they should be running in the same mount namespace.

**Comment by poettering** [comment]
What makes you think this would run thing in the same mount namespace?

Please always consult the man page, before filing an issue here. i.e. https://www.freedesktop.org/software/systemd/man/systemd.unit.html#JoinsNamespaceOf= – it's only about network namepaces and PrivateTmp=, nothing else.

#11699 asks for a concept of joining mount namespaces already, in case you are asking for that. Let's hence close this issue.

**Comment by Melab** [comment]
@poettering How can they have the same `/tmp` filesystem but be in different mount namespaces?

**Comment by poettering** [comment]
Each service get its own namespace, and then we bind mount the same dirs to /tmp and /var/tmp inside both.
