### ISSUE TITLE
The Dirty Detection chapter in JOURNAL_FILE_FORMAT.md maybe wrong

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#19145]
**systemd version the issue has been seen with**
 > master

**Expected behaviour you didn't see**
 > 
Maybe it should be **STATE_ONLINE** instead of **STATE_OFFLINE** when we should  immediately rotate the file

**Unexpected behaviour you saw**
 > 
```
If a writer is asked to write to a file that is not in
STATE_OFFLINE it should immediately rotate the file and start a new one,
without changing the file.
```

**Comment by vcaputo** [comment]
No, it's describing that a writer requires an offline journal to be writable.

An already-online journal cannot be written to, because it must be assumed to be dirty/inconsistent, because it's been left online.

Perhaps the text could be restructured for clarity, but it is not incorrect as-is.

**Comment by keszybz** [comment]
Yeah, I think the text is OK after the revert.
