### ISSUE TITLE
Missing documentation for Following property

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#1914]
I can't find any doc on this property:

```
% git grep Following docs man
man/systemd-journal-gatewayd.service.xml:    <para>Following parameters can be used as part of the URL:</para>
```

All I have been able to find is on the [D-Bus API docs](http://www.freedesktop.org/wiki/Software/systemd/dbus/#properties), which is not very clear either.

**Comment by arvidjaar** [comment]
Well, Following is not user-settable and I am not sure we have manual page for such properties. It is used to group all device aliases and points to "primary" device unit that systemd is using to track device state (usually corresponds to sysfs path).

**Comment by fsateler** [comment]
I'd argue that as long as it is user-readable it should be documented. Also, explaining the relationship between different names of the same device would independently be useful (why are there multiple device units? can they be used interchangeably?).

BTW, your description doesn't explain why devices aren't simply aliased to each other.
