### ISSUE TITLE
timesyncd may try to sync when system is not really online

### ISSUE THREAD

**Issue by sipraga** [systemd/systemd#19143]
I originally [posted about this on the systemd-devel mailing](https://lists.freedesktop.org/archives/systemd-devel/2021-March/046239.html) list hoping to get some feedback on this problem. Below is more or less a repost, in the hopes of catching some more attention. In the absence of any other opinions, I will prepare a PR according to suggestion (2) below.

Thanks in advance!

**Is your feature request related to a problem? Please describe.**
systemd-timesyncd listens for changes in network state and will start a timesync when it determines that the system is online. It does this via `network_is_online()`, which just queries the global carrier and address state advertised by systemd-networkd.

systemd-networkd determines the global carrier and address state by simply iterating through all links and taking the maximum of the link carrier and address states.

However, a routable link does not necessarily mean that the system is online. One example is with wireless access point interfaces: an AP is set up with hostapd and networkd configures a static IP address on that interface, making it routable. By the above, this causes timesyncd to attempt a timesync that is doomed to fail.

We are having trouble with this logic because we start hitting timesyncd's internal rate limiter. After a non-AP interface gets an IP and we are truly "online", timesyncd will try to start a timesync, but may defer it for up to 30 seconds due to rate limiting.

Ideally, timesyncd should be able to distinguish between the two cases such that it can ignore the state of the AP interface and avoid spurious timesync attempts.

**Describe the solution you'd like**
Here are some proposals:

1. Add a new `[Link]` option `NotForOnline=` (or similar) to systemd.networkd(5) to indicate that this link being routable does not 
imply that the system is online. This could also implicitly set `RequiredForOnline=no` if desired. Then parse the option in `network_is_online()` to exclude certain links.

2. Add a new `[Link]` option `IgnoreLinkState=` (or similar) to systemd.network(5) to indicate to systemd-networkd that this link's 
carrier and address state should not be factored into the calculation of global carrier and address state.

3. Same as (1) above, but rather than adding a new option, just parse `RequiredForOnline=`.

**Describe alternatives you've considered**
Our current workaround is to restart systemd-timesyncd to force an immediate timesync, but this is an awful hack. Another workaround is to put systemd-timesyncd after `network-online.target`.

**The systemd version you checked that didn't have the feature you are asking for**
v246. I believe the problem is also present in the main branch as of writing.

**Comment by poettering** [comment]
well, there are a myriad of reasons why connectivity might not be there. i mean, there's a long chain of routers usually towards reaching the internet, and any of those can fail. We use the carrier check as a reason to recheck, and we'll alwas retry after a while. 30s shouldn't be that bad...

I mean, we can certainly polish things further, but it's not really a bug here...

Wouldn't it suffice to make network_is_online() honour RequiredForOnline=? i.e. why another option?

**Comment by sipraga** [comment]
Sure, I also think it's reasonable to just honour RequiredForOnline= in network_is_online().

Here's a quick attempt at doing that: https://github.com/sipraga/systemd/commit/cce3dd298266d39d615db3ba2ba7a95995390d80

I haven't made a PR because it still requires an update to the documentation for RequiredForOnline=, and I haven't tested it just yet. But does it seem like a reasonable approach?

**Comment by poettering** [comment]
This should probably be implemented networkd-side, not client-side
