### ISSUE TITLE
Versioned man pages on website

### ISSUE THREAD

**Issue by koernepr** [systemd/systemd#19141]
**Is your feature request related to a problem? Please describe.**
Rendered man pages are available at [freedesktop.org](https://www.freedesktop.org/software/systemd/man/), but only for one version. Based on their version number, they are for the in-development release.

**Describe the solution you'd like**
It would be helpful to have the rendered man pages for (non-ancient) stable releases available online at an official location:

Reasons:
- Not all systems provide the man pages; they are missing e.g. on embedded systems or other reduced installations.
- Man pages available on the web can be used as an easily-accessible citation reference.

**Describe alternatives you've considered**
You can of course use the DocBook sources, but these are neither good to read, nor to search due to the XML tags.

**The systemd version you checked that didn't have the feature you are asking for**
N/A

**Comment by poettering** [comment]
We aren't web people. I doubt this will happen, it's a lot of effort for little gain in a territory we are not that at home in... And doesn't https://manpages.debian.org/ and similar already provide something like this, hence why should we?

**Comment by bluca** [comment]
More than storing old manpages, it would be great if we could annotate options with the version they were first introduced. I often have to `git blame` to find out, and I know others do too. It's quite a bit chunk of work though...

**Comment by koernepr** [comment]
I'm not talking about anything fancy; it would be sufficient to generate HTML files like [these](https://www.freedesktop.org/software/systemd/man/) for maybe the ten most recent releases and put them in sub directories named after the respective version. Then, ideally also generate an index page, but this wouldn't even be strictly necessary if it's too much effort and the chosen URLs are straightforward.

It's true that e.g. Debian also hosts man pages, but these are only for the few versions packaged by Debian.

@bluca Yes, that would also be quite helpful; a simpler alternative might be to generate a separate table of directives vs. versions or annotate the directives man page only. That's for a separate ticket though IMHO :slightly_smiling_face:
