### ISSUE TITLE
Christmas wishes

### ISSUE THREAD

**Issue by tele1** [systemd/systemd#19151]
All the best and a lot of time to refine the project.

Things I would see better.
Last time I tried copy iptables.service from Arch Linux.

1. In my opinion, misunderstanding of how services work or pushing the power of options.
 Code for systemd:
```
 [Unit]
Description=IPv4 Packet Filtering Framework
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/usr/bin/iptables-restore /etc/iptables/iptables.rules
ExecReload=/usr/bin/iptables-restore /etc/iptables/iptables.rules
ExecStop=/usr/lib/systemd/scripts/iptables-flush
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Part code for init
```
case "$1" in
start|restart|reload|force-reload)
	load_rules
	;;
save)
	save_rules
	;;
stop)
	# Why? because if stop is used, the firewall gets flushed for a variable
	# amount of time during package upgrades, leaving the machine vulnerable
	# It's also not always desirable to flush during purge
	echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
	;;
flush)
	flush_rules
	;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac
```

1.1  Flush command resets the firewall settings.
So this should be firewall job and not system service.
But this and other options are not necessarily pushed into the service.
But it looks like trying to combine all the iptables commands into one .
It would make more sense if this service were just to turn the firewall on and off.
If you build something similar upgrade app and leave services.

**Edited:**
I will try to explain otherwise.
This service is considered to be a service for loading and cleaning iptables rules.
But its main task is to restore settings at system startup. That is all and nothing else.

1.2 If you need more options like in init. Init have advantage.
You can create own options, but systemctl have own options
`systemctl --help | grep UNIT`

1.3  " **iptables-restore** " command is specific.  Loads settings from file and exits.
So it only works for a moment but systemctl show that this app running, but this is not true.
So I can not use **ExecStop** to kill a process which isn't exist. 
Other services like ssh server, rsync server still running.
I can remove line **ExecStop=...** from own service but after reboot I see from systemctl again.
I can not put this command to cron because because this command for security reasons must be run before internet can be started.
So it must be started in a specific order like the service although it is not running permanently.

I hope that reflections will help to create something better.

**Comment by keszybz** [comment]
Hi @tele1. The right place to discuss iptables configuration scripts is with the iptables project... Systemd is not providing or developing this file. That said, at this point in time, iptables is being slowly removed, so you might want to look at nftables instead.
