### ISSUE TITLE
Support for DHCP option 212 (sixrd)

### ISSUE THREAD

**Issue by samip5** [systemd/systemd#19152]
**Is your feature request related to a problem? Please describe.**
It's related to the fact that when ISP gives the 6RD details though DHCPv4 and the border gateway may change without a notice.

**Describe the solution you'd like**
I would want it to automatically be configured or the details should be outputted to log or have a scriptable way to generate the config from those details.

**Describe alternatives you've considered**
I have tried NetworkManager, but it also does not have support for it.

**The systemd version you checked that didn't have the feature you are asking for**
247.2-r4 on Gentoo

RFC link: https://tools.ietf.org/html/rfc5969#section-7.1.1

**Comment by yuwata** [comment]
@samip5 I've tried to implement 6rd support in PR #21625. If possible, could you test the PR? Thank you.

**Comment by samip5** [comment]
> 

I'm not exactly sure as to how I should go about building systemd with the PR changes?

**Comment by DaanDeMeyer** [comment]
See https://github.com/systemd/systemd/blob/main/docs/HACKING.md for instructions on how to build systemd.

**Comment by yuwata** [comment]
@samip5 Sorry for missed your question. Please try with the instruction shown by @DaanDeMeyer. If you have any trouble on testing the PR, feel free to ask that.

**Comment by samip5** [comment]
@yuwata Could you please tell me all the patches I need and which order they need to applied?
Currently patching fails due to the PR being split into smaller ones I belive.

Trying to patch using the PR (#21625) results in failures.

Paste: https://dpaste.com/CGRGHMZUE

**Comment by samip5** [comment]
Got that built, but will be able to properly test by the latest on December 24th.

**Comment by yuwata** [comment]
@samip5 The PR is merged, and will be included in v250-rc1. If you find any issues, please open a new issue page. Thank you.

**Comment by samip5** [comment]
Verified that it works properly. Thank you. @yuwata
