### ISSUE TITLE
journalctl -F shows the same values multiple times

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#19172]
I think this doesn't make any sense... We should return just a list of unique items.

```console
$ journalctl -F _TRANSPORT|sort|uniq -c|sort -g
     17 driver
     39 audit
     39 kernel
     67 stdout
     70 syslog
     95 journal
```

systemd 248-106-g3e23a7b

**Comment by vcaputo** [comment]
That looks like a bug to me, the code makes an effort to not return duplicates from multiple journals @ https://github.com/systemd/systemd/blob/v248/src/libsystemd/sd-journal/sd-journal.c#L2967

afraid I don't have time to dig deeper into this anytime soon
