### ISSUE TITLE
nspawn: private users + bind mount rw results to ro in fact

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#19195]
Hello

I create a directory:
`mkdir -p /run/coturn-container/certbot-logs`

Then run a container from squashfs image and want to make a bind mount of an empty directory from read-only image to a writable directory on host:

```
systemd-nspawn \
<...>
--bind=/run/coturn-container/certbot-logs:/var/log/letsencrypt \
--private-users=1100000 \
--boot
```

The container boots. But that directory is not writable:
From inside container:
```
[root@coturn1 ~]# touch /var/log/letsencrypt/t2
touch: cannot touch '/var/log/letsencrypt/t2': Permission denied
[root@coturn1 ~]# mount | grep /var/log/letsencrypt
tmpfs on /var/log/letsencrypt type tmpfs (rw,nosuid,nodev,size=1100476k,nr_inodes=819200,mode=755)
```

From the host I can create a file in that directory and it is readable from the container.
Yes, as according to docs, 0:0 from host is mapped to nobody in the container.
But why can't the root user inside the container read and write into it?

**Comment by poettering** [comment]
if you make the host dir owned by the root user of the container then everything should just work, no?

userns just works the way userns works: root in the container cannot modify stuff owned by non-mapped users...

**Comment by poettering** [comment]
I figure once we start supporting linux 5.12 per-mount userid mappings we can support this safely without requiring you to chown() the files you bind mount like that.

The mess around bind mounts in userns envs is documented in the man page btw.

**Comment by mikhailnov** [comment]
> if you make the host dir owned by the root user of the container then everything should just work, no?

Yes, it works, thanks!

**Comment by mikhailnov** [comment]
> The mess around bind mounts in userns envs is documented in the man page btw.

Probably not clearly enough...
