### ISSUE TITLE
RFE: accept alternative separator for PCR lists

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#19205]
**Is your feature request related to a problem? Please describe.**

The systemd-cryptsetup `tpm2-pcrs=` option accepts a comma-separated list. The problem is, options _themselves_ are a comma-separated list. This makes putting commas in the value slightly annoying, and escaping varies from place to place, especially when the crypttab-generator is involved. Do you use one backslash, or two, or three, or do you need hex escapes?

For example, in the kernel command line, `rd.luks.options=system=discard,tpm2-pcrs=0\,4\,7` appears to be right.

But in /etc/crypttab, `discard,tpm2-pcrs=0\x2c4\x2c7` is the only option I've managed to work out.

**Describe the solution you'd like**

Accept e.g. dots or colons or semicolons as alternative separators (`tpm2-pcrs=0:4:7`) maybe?

Even better, not require tpm2-pcrs to be specified at all and just directly use what's already stored in the luks token? (I expected that to already be the case, but from reading the source code it very much looks like it always tries to unseal against pcr7 by default...)

**Describe alternatives you've considered**

From source it _seems_ like repeating the option for each single PCR would work, but that's also undocumented and a bit cumbersome.

**The systemd version you checked that didn't have the feature you are asking for**

v248

**Comment by poettering** [comment]
Yeah, makes sense.

**Comment by poettering** [comment]
you need to specify the TPM2 PCRs in crypttab only if you don't use LUKS2 with the data properly available in JSON. See docs.
