### ISSUE TITLE
Enabling getty@..service leads to /dev permission changed to 0620

### ISSUE THREAD

**Issue by bjacquin** [systemd/systemd#19213]
**systemd version the issue has been seen with**
 > `systemd 247 (247) +PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL -XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid`

**Used distribution**
 > Gentoo Linux

**Linux kernel version used** (`uname -a`)
 > `Linux intel-g6pa105007m7 5.11.11-stable #1 SMP 2021-04-06T01:51:21+01:00 x86_64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz GenuineIntel GNU/Linux`

**CPU architecture issue was seen on**
 > `x86_64`

**Expected behaviour you didn't see**
 > When service `getty@..service` is enabled and started, a few second later `/dev` permission are changed from `0755` to `0620` while the following errors are printed out in the logs:

```
# systemctl enable getty@..service
Created symlink /etc/systemd/system/getty.target.wants/getty@..service → /lib/systemd/system/getty@.service.
# systemctl start getty@..service

# journalctl
...
Apr 06 02:23:18 intel-g6pa105007m7 agetty[354]: /dev/.: cannot open as standard input: Is a directory
Apr 06 02:23:18 intel-g6pa105007m7 systemd[1]: getty@..service: About to execute /sbin/agetty -o '-p -- \u' --noclear . $TERM
Apr 06 02:23:18 intel-g6pa105007m7 systemd[1]: getty@..service: Forked /sbin/agetty as 354
Apr 06 02:23:18 intel-g6pa105007m7 systemd[354]: getty@..service: Executing: /sbin/agetty -o '-p -- \u' --noclear . vt220
Apr 06 02:23:28 intel-g6pa105007m7 systemd[1]: Received SIGCHLD from PID 354 (agetty).
Apr 06 02:23:28 intel-g6pa105007m7 systemd[1]: Child 354 (agetty) died (code=exited, status=1/FAILURE)

# stat /dev
  File: /dev
  Size: 13320     	Blocks: 0          IO Block: 4096   directory
Device: 5h/5d	Inode: 1           Links: 14
Access: (0620/drw--w----)  Uid: (    0/    root)   Gid: (    5/     tty)
Access: 2021-04-06 02:19:05.026000000 +0100
Modify: 2021-04-06 02:19:08.725999919 +0100
Change: 2021-04-06 02:23:28.478982876 +0100
 Birth: -
```

This leads for example to /dev/null not being available for regular user then after and so all sort of unexpected behaviour. While I understand `getty@..service` is a typo here, should we expect systemd to not catch the error earlier and prevent this from happening overall ?

**Unexpected behaviour you saw**
 > See above

**Steps to reproduce the problem**
 > See above

**Additional program output to the terminal or log subsystem illustrating the issue**
 > See above

**Comment by bjacquin** [comment]
Please note this is not a bug in util-linux, but instead it seems this is due to `TTYReset=yes` set in `/lib/systemd/system/getty@.service` which lead to `vt_restore()` changing the permission and owner without sanity check

**Comment by poettering** [comment]
Hmm, so of course enabling the unit like that is a bug in itself. But you are right, we should handle this more gracefully, and refuse things if the TTY path is not actually a tty.
