### ISSUE TITLE
Handle PKCS#11 URI with dots

### ISSUE THREAD

**Issue by livelace** [systemd/systemd#19224]
Hi. I use [Rutoken ECP](https://www.rutoken.ru/products/all/rutoken-ecp/) for security purpose. 

This token has PKCS11 URI with dot:

```
pkcs11:model=Rutoken%20ECP;manufacturer=Aktiv%20Co.;serial=3xxxxxxb;token=livelace
```

Quick [RFC](https://tools.ietf.org/html/rfc7512) reading didn't make it more clear (for me) - permitted dots or not.

The problem can be easily fixed with patch:

```
--- src/shared/pkcs11-util.c    2021-04-06 20:06:51.675353783 +0300
+++ src/shared/pkcs11-util.c.new        2021-04-06 21:38:42.459441816 +0300
@@ -31,7 +31,7 @@
         if (isempty(p))
                 return false;
 
-        if (!in_charset(p, ALPHANUMERICAL "-_?;&%="))
+        if (!in_charset(p, ALPHANUMERICAL ".-_?;&%="))
                 return false;
 
         return true;
```

It seems not a big deal to add dots in the list of permitted characters ?

v248

**Comment by poettering** [comment]
Please submit as PR, so that we can properly attribute the patch to you

**Comment by poettering** [comment]
The RFC says that manufacturer= may contain ".", as that's one of the "unreserved" chars, as per RFC 3986.

The RFC allows a bunch of other char, too such as "~" and "/",` we probably should allowlist them too.

**Comment by livelace** [comment]
It looks like CI is broken.

https://github.com/systemd/systemd/pull/19280
