### ISSUE TITLE
systemd-networkd : Option 42 to fetch the NTP server

### ISSUE THREAD

**Issue by Jyothi-K** [systemd/systemd#19230]
Hello Team,

I have a requirement on fetching the NTP server address from DHCP option 42 as a DHCP client . I am using systemd for this and my configuration file looks like this

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6

[DHCP]
ClientIdentifier=mac
RouteMetric=50
UseMTU=true
UseNTP=true

Please let me know if this is the right option and if yes how to use the response of this to fetch the NTP server address.

Any hints would be more useful for me

**Comment by yuwata** [comment]
You can see the NTP server addresses in `networkctl status INTERFACE`. Or do you want e.g. dbus API to get NTP server addresses?

**Comment by yuwata** [comment]
Maybe related to #16785.

**Comment by FedericoVaga** [comment]
Hello, connected to this issue. I would like to use `systemd-networkd`+ `chrony`.  `chrony` provides a `dhclient` hook to handle the DHCP option 42 to update the list on NTP servers. However, `systemd-networkd` does not use `dhclient` but its own internal DHCP client. So, how can I trigger a script to handle option 42? This is handled if I use `systemd-timesyncd`, but I do need to use `chrony`. So, how to have the same behavior  as with `dhclient` (hooks)?

**Comment by yuwata** [comment]
Now `networkctl --json=pretty status INTERFACE` can show NTP addresses gracefully in JSON format. I hope that it is enough for the original request.

@FedericoVaga Please try to monitor `AdministrativeState` DBus property for the interface you use. Then, when the property change is detected, try to parse the output of `networkctl status INTERFACE`.

Closing.

**Comment by PercevalSA** [comment]
@FedericoVaga I have the exact same problem. How did you solve your issue?

**Comment by FedericoVaga** [comment]
> @FedericoVaga I have the exact same problem. How did you solve your issue?

I bit of a hack. I've created a new systemd service running after `network-online.target` and `chronyd.service` that executes the following script:

```
for server in $(networkctl status | grep NTP -A 1 | grep -o -E "([0-9]{1,3}.?){4}"):
do
    chronyc -n -m "add server $server iburst" && (echo $server > /run/chrony/added_server)
done
```

But then I moved to a fixed configuration, which is anyway a good solution for the context where this is running.
