### ISSUE TITLE
RFE: resolvectl should warn or refuse operation when called from a netns different from resolved's

### ISSUE THREAD

**Issue by stu-gott** [systemd/systemd#19236]
**systemd version the issue has been seen with**
systemd-246.13-1.fc33.x86_64

**Used distribution**
 Fedora 33

**Linux kernel version used** (`uname -a`)
`5.11.11-200.fc33.x86_64`

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
 I would expect that I can use resolvectl inside a network namespace independently of other namespaces.

**Unexpected behaviour you saw**
 Managing a network interface with resolvectl inside a network namespace makes changes to the root namespace and vice versa.

**Steps to reproduce the problem**
Use podman to create a container (easy way to create a usable network namespace):

# sudo podman run -it --rm --privileged -v /var/run/dbus:/var/run/dbus fedora
# resolvconf -a eth0

Then paste some garbage data in. I used this:
search example.com
nameserver 127.0.0.1

Inside the container, "resolvectl status" reflects this:

Link 3 (eth0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 127.0.0.1
          DNS Domain: example.com

Now back in the root namespace, "resolvectl status" says this.

Link 3 (enp0s31f6)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 127.0.0.1                                                   
    DNS Domain: example.com 

Now let's revert. In the root namespace:
# sudo resolvectl revert enp0s31f6

And now in the container, resolvectl status output:

Link 3 (eth0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

The two namespaces clearly interact. It appears to me that the link is that these two unrelated interfaces had the same number associated with them. In this case "Link 3". This has a profound effect inside the namespace. In short, per-link DNS resolution is broken. This would have been useful, e.g. for setting up a VPN.

**Comment by poettering** [comment]
no, resolved runs on the host namespace, and takes your requests from dbus/varlink/nss or the stub and sends it upstream, returning universal truths. If you want an isolated instance with a different configuration you need to run resolved inside your own namespace.

**Comment by stu-gott** [comment]
This seems like a really strange/artificial limitation. It's perfectly valid to run a process in a network namespace without running in a container. Yes it's a bit of a corner case, but there's no way to run two separate resolved's like that--they share a mount namespace.

If resolved can/should only track state in one namespace I still think there's a fundamental issue here. Information that applied to one namespace was presented as ground truth for all namespaces.

At the very least, requests from processes running in a different network namespaces than the daemon runs in need to be refused. Though I think there are better overall solutions than that.

**Comment by stu-gott** [comment]
> note that this was _never_ supported, even before resolved, because if you run something inside a netns without anything else you'd always share the common /etc/resolv.conf...
> 

Well? Your statement is absolutely correct, but there usually is something else in play. I don't know how all the moving parts work, I think maybe iproute or NetworkManager takes care of this detail for me, but creating this file:

/etc/netns/test/resolv.conf

Does automatically bindmount over /etc/resolv.conf when switching to a network namespace named "test". Which in essence does allow for separate control of DNS resolution. Well it would, except that /etc/resolv.conf is no longer the source of ground truth in a resolved world.

As far as what needs to be done, I have no idea. Totally agree that pid lookup needs to be avoided at all costs. Blocking cross-namespace queries with a helpful message would be a good place to start. At least it would save debugging time for anybody who trips over this.

**Comment by poettering** [comment]
> > 
> 
> Well? Your statement is absolutely correct, but there usually is something else in play. I don't know how all the moving parts work, I think maybe iproute or NetworkManager takes care of this detail for me, but creating this file:
> 
> /etc/netns/test/resolv.conf

Well, but that means you are *not* employing just netns but also mount file systems. because apparently you are living in your own mount namespace too now, since otherwise this would affect everyone else too.

So you have a mount *and* a network namespace. This comes awfully close to being its own container already.
