### ISSUE TITLE
Timing of persistent and delayed services

### ISSUE THREAD

**Issue by Sadi58** [systemd/systemd#19244]
**systemd version the issue has been seen with**
 > 245.4-4ubuntu3.6

**Used distribution**
 > KDE neon

**Linux kernel version used** (`uname -a`)
 > 5.4.0-70

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > When user sets up several persistent timers to start at 10:05, 10:10 and 10:15, systemd should start them with a 5 minute interval even when the computer has been start at 11:00.

**Unexpected behaviour you saw**
 > At the moment systemd seems to disregard the timing details and try to start all such persistent and delayed timers at the time of user login, which causes conflicts between some scripts, ending up some commands failing to be executed.

**Steps to reproduce the problem**
 > 1. Create 3 user scripts (for example, all writing to a log file the starting time, actions taken, and the time finished), services and timers (persistent and set to start at different times such as 10:05, 10:10 and 10:15), and enable them.
 > 2. Start the computer some time after these systemd user services have been set to start.
 > 3. Check out the user systemd log file, which will show 3 scripts have been started more or less at the same time, and their entries are all mixed up.

**Comment by poettering** [comment]
Uh, I am not convinced this is really desirable. What do you do if the time differences are larger, i.e. multiple hours? And if I have five unrelated timers why would i even want that at all? 

It appears to me you should find a different solution for what you are doing. For example, start the first timer as usual via timers.target, but start the second timer unit from the first service, and the third timer from the second service. That way you can be sure that the timers only become pending once your earlier jobs are finished.

You could also use Type=oneshot service and then simply order the services via After=.

Either way, this looks more like a support issue. For things like that please contact the systemd mailing list or another forum. Hope that makes sense.
