### ISSUE TITLE
RFE: add ability to add "sbat" metadata to sd-boot and EFI stub builds

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#19247]
The new shim 15.4 that are getting signed by everyone requires sbat sections to be present in the EFI applications that it loads.

The specification is here https://github.com/rhboot/shim/blob/main/SBAT.md

The idea is that all EFI apps have sbat sections, and that one can sign an authorized variable that can revoke a generation of similar products. I.e. "revoke all grubs of generation 2 or lower from everybody" or "revoke grubs from vendor X that derived from vendor Y" because of some bugs that only affects certain vendors but not others.

This means that systemd-boot$arch.efi should have .efi section, but probably also kernel.efi (type 2 from the Boot Loader Specification).

Example .sbat sections for vendor Ubuntu are:

```
shim, fb, mm:
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.ubuntu,1,Ubuntu,shim,15.4-0ubuntu1,https://www.ubuntu.com/

grub:
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.ubuntu,1,Ubuntu,grub2,2.04-1ubuntu45,https://www.ubuntu.com/

fwupd:
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.8,https://github.com/fwupd/fwupd
fwupd.ubuntu,1,Ubuntu,fwupd,1.5.8-0ubuntu1,https://launchpad.net/ubuntu/+source/fwupd
```

It would be nice if systemd would define sbat.csv, ship it in /usr/lib/systemd/boot/efi/ (for people to add it to kernel.efi) and also add it to the systemd-bootx64.efi.

I would like to propose the following SBAT

```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
systemd,1,systemd,systemd,248,https://github.com/systemd/systemd
systemd.ubuntu,1,Ubuntu,systemd,248-1ubuntu17,https://launchpad.net/ubuntu/+source/systemd
```

First line is required, as that defined all of sbats of everything.
Second line describes systemd upstream itself, thus i.e. it should have systemd upstream release version number.
Third line is customized by vendor with vendor name, vendor-patch-version, vendor-url.

fwupdate already did all that in meson, so we might be able to copy the same option names from there, see https://github.com/fwupd/fwupd/blob/master/meson_options.txt#L50

Also Boot Loader Specification should be updated to include .sbat such that shim can load kernel.efi directly without grub/systemd-boot in between, as it has been possible to date.

**Comment by poettering** [comment]
What a needlessly weird format...

Not using shim myself, this probably needs a contributed patch

**Comment by xnox** [comment]
> What a needlessly weird format...
> 
> Not using shim myself, this probably needs a contributed patch

wait till you see the custom aarch64 linker scripts to do all that.
