### ISSUE TITLE
TEST-50-DISSECT: misleading /etc/os-release check

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#19242]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > CentOS 8

During my attempts to migrate the CentOS CI's CentOS 7 job to CentOS 8 I've been battling with `TEST-50-DISSECT` which keeps failing *mysteriously*, even though everything seems to be in order. After some debugging the issue lies in this particular line:

https://github.com/systemd/systemd/blob/71d1e58309bb70bb2a014f33c5f9503dcbed020c/test/units/testsuite-50.sh#L35

This uses the `/etc/os-release` as a list of fixed-string patterns to match against the `systemd-dissect`'s output. However, `grep` happily returns 0 when at least one of the patterns match. This, combined with the `os-release`'s format, which uses quoted string in _some cases_, whereas `systemd-dissect` uses unquoted strings in all cases, makes the test fail even though it shouldn't.

CentOS 8:
```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

# systemd-dissect root/usr/share/minimal_0.raw 
      Name: minimal_0.raw
      Size: 2.6M

OS Release: NAME=CentOS Linux
            VERSION=8
            ID=centos
            ID_LIKE=rhel fedora
            VERSION_ID=8
            PLATFORM_ID=platform:el8
            PRETTY_NAME=CentOS Linux 8
            ANSI_COLOR=0;31
            CPE_NAME=cpe:/o:centos:centos:8
            HOME_URL=https://centos.org/
            BUG_REPORT_URL=https://bugs.centos.org/
            CENTOS_MANTISBT_PROJECT=CentOS-8
            CENTOS_MANTISBT_PROJECT_VERSION=8
            MARKER=1

RW DESIGNATOR PARTITION UUID PARTITION LABEL FSTYPE   ARCHITECTURE VERITY                           NODE PARTNO
ro root       -              -               squashfs -            external root/usr/share/minimal_0.raw -     

# systemd-dissect root/usr/share/minimal_0.raw | grep -F -f root/etc/os-release || echo "<no match>"
<no match>
```

In this case all strings in `/etc/os-release` are quoted, so there's no match with the dissected-image's output.

Fedora 33:
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

# systemd-dissect /tmp/tmp.zfwT9M/minimal_0.raw | grep -F -f /etc/os-release
 OS Release: NAME=Fedora
             ID=fedora
             VERSION_ID=33
             PRETTY_NAME=Fedora 33 (Thirty Three)
             LOGO=fedora-logo-icon
             REDHAT_BUGZILLA_PRODUCT_VERSION=33
             REDHAT_SUPPORT_PRODUCT_VERSION=33
```

In this case the grep matches the unquoted fields (and `PRETTY_NAME`, because it's matched by `NAME=Fedora`).

I suspect the image check will need to use a slightly different approach to avoid this.

/cc @bluca

**Comment by bluca** [comment]
This quoting/unquoting business is unfortunate - I thought at least the ID_ fields were always unquoted. Instead of grep -f, is there some awk magic we can use that would make more sense?

**Comment by mrc0mmand** [comment]
> This quoting/unquoting business is unfortunate - I thought at least the ID_ fields were always unquoted. Instead of grep -f, is there some awk magic we can use that would make more sense?

What about a *simple* `sed` magic?

```
# systemd-dissect root/usr/share/minimal_0.raw | grep -F -f <(sed 's/"//g' root/etc/os-release)
OS Release: NAME=CentOS Linux
            VERSION=8
            ID=centos
            ID_LIKE=rhel fedora
            VERSION_ID=8
            PLATFORM_ID=platform:el8
            PRETTY_NAME=CentOS Linux 8
            ANSI_COLOR=0;31
            CPE_NAME=cpe:/o:centos:centos:8
            HOME_URL=https://centos.org/
            BUG_REPORT_URL=https://bugs.centos.org/
            CENTOS_MANTISBT_PROJECT=CentOS-8
            CENTOS_MANTISBT_PROJECT_VERSION=8
```

i.e. just strip the double quotes from the `os-release` file at *runtime*. Not sure if there are any legitimate use cases of double quotes inside the quoted strings, but I hope they aren't :-)

**Comment by bluca** [comment]
Thanks for the suggestion, can you let me know if https://github.com/systemd/systemd/pull/19249 fixes the issue?
