### ISSUE TITLE
resolved: make clear that global search domains apply to global DNS servers, and per-interface search domains to per-interface DNS servers

### ISSUE THREAD

**Issue by sbogomolov** [systemd/systemd#19257]
**systemd version the issue has been seen with**
 > systemd 248 (v248-2.fc34)

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `Linux fedora 5.11.11-300.fc34.x86_64 #1 SMP Tue Mar 30 16:37:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
I expect the global search domain be applied to `nas` and tried on all interfaces. `host`, `nslookup` and `ping` should all work.
```sh
$ ping nas
PING nas.lan (192.168.10.20) 56(84) bytes of data.
64 bytes from nas.lan (192.168.10.20): icmp_seq=1 ttl=64 time=0.150 ms
64 bytes from nas.lan (192.168.10.20): icmp_seq=2 ttl=64 time=0.842 ms

$ host nas
nas.lan has address 192.168.10.20

$ nslookup nas
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	nas.lan
Address: 192.168.10.20
```

**Unexpected behaviour you saw**
Global search domain is not applied with `ping`, but works with `host` and `nslookup`
```sh
$ ping nas
ping: nas: Name or service not known

$ host nas
nas.lan has address 192.168.10.20

$ nslookup nas
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	nas.lan
Address: 192.168.10.20
```

**Steps to reproduce the problem**
1. Set the global search domain in `/etc/systemd/resolved.conf` and restart `systemd-resolved`:
```sh
$ grep Domains /etc/systemd/resolved.conf 
Domains=lan

$ sudo systemctl restart systemd-resolved

$ resolvectl 
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub
      DNS Domain: lan

Link 2 (enp39s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp38s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.10.1
       DNS Servers: 192.168.10.1

Link 4 (wlo1)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```
2. Try to ping without the domain and with the domain specified (only the latter works):
```sh
$ ping nas
ping: nas: Name or service not known

$ ping nas.lan
PING nas.lan (192.168.10.20) 56(84) bytes of data.
64 bytes from nas.lan (192.168.10.20): icmp_seq=1 ttl=64 time=0.185 ms
64 bytes from nas.lan (192.168.10.20): icmp_seq=2 ttl=64 time=0.173 ms
```
3. Remove global search domain, restart `systemd-resolved` and set the search domain for the interface:
```sh
$ grep Domains /etc/systemd/resolved.conf
#Domains=

$ sudo resolvectl domain enp38s0 lan

$ resolvectl 
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp39s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp38s0)
Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.10.1
    DNS Domain: lan

Link 4 (wlo1)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```
4. Try to ping without the domain and with the domain specified (works both ways):
```sh
$ ping nas
PING nas.lan (192.168.10.20) 56(84) bytes of data.
64 bytes from nas.lan (192.168.10.20): icmp_seq=1 ttl=64 time=0.149 ms
64 bytes from nas.lan (192.168.10.20): icmp_seq=2 ttl=64 time=0.162 ms

$ ping nas.lan
PING nas.lan (192.168.10.20) 56(84) bytes of data.
64 bytes from nas.lan (192.168.10.20): icmp_seq=1 ttl=64 time=0.412 ms
64 bytes from nas.lan (192.168.10.20): icmp_seq=2 ttl=64 time=0.185 ms
```

**Comment by poettering** [comment]
Search domains are specific to the scope they are defined on, and are used for the DNS servers you configure on that scope. i.e. the global search domains apply to the global DNS servers. and the per-interface search domains to the per-interface DNS servers.

i.e. always configure the search domains at the same place you configure the DNS servers, they always belong together.

This should be made clearer in the docs.

**Comment by sbogomolov** [comment]
Thanks for clarifying that. What made it unclear in the first place is this bit [here](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html):
```
When global search domains are defined, such look-ups are routed to all interfaces, suffixed by each of the global search domains in turn.
```
Maybe it makes sense to mention there that even though it is routed to all interfaces, it still uses Global DNS servers.
