### ISSUE TITLE
no early login for root with pam_nologin

### ISSUE THREAD

**Issue by mphilipps** [systemd/systemd#19264]
**systemd version the issue has been seen with**
 > tested with 241, checked files for 247

**Used distribution**
 > Debian Buster

**Expected behaviour you didn't see**
 > root should be able to login befor **systemd-user-sessions** runs

**Unexpected behaviour you saw**
 > root login is delayed until **systemd-user-sessions** runs.

**Steps to reproduce the problem**
 * create oneshot service with a sleep 30 and Before=systemd-user-sessions to slow down the boot
 * reboot
 * try to ssh login as a non-root user -> /run/nologin gets printed and the connection closed 
 * try to ssh login as root -> login is delayed by 30 seconds, /run/nologin gets printed (why?), shell gets launched

**Additional program output to the terminal or log subsystem illustrating the issue**

man systemd-user-sessions.service

```
NAME
       systemd-user-sessions.service, systemd-user-sessions - Permit user logins after boot, prohibit user logins at shutdown

SYNOPSIS
       systemd-user-sessions.service

       /lib/systemd/systemd-user-sessions

DESCRIPTION
       systemd-user-sessions.service is a service that controls user logins through pam_nologin(8). After basic system initialization is complete, it
       removes /run/nologin, thus permitting logins. Before system shutdown, it creates /run/nologin, thus prohibiting further logins.
```

This implies root should be able to login befor systemd-user-sessions runs.

Suspected culprint:

# /usr/lib/systemd/system/user@.service

```
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=User Manager for UID %i
Documentation=man:user@.service(5)
After=systemd-user-sessions.service user-runtime-dir@%i.service dbus.service
Requires=user-runtime-dir@%i.service
IgnoreOnIsolate=yes

[Service]
User=%i
PAMName=systemd-user
Type=notify
ExecStart=-/lib/systemd/systemd --user
Slice=user-%i.slice
KillMode=mixed
Delegate=pids memory
TasksMax=infinity
TimeoutStopSec=120s
```

The systemd user session for root shouldn't depend on systemd-user-sessions.service. Root should be able to login before regular users can to fix possible issues that may have occurred during boot.

E:

/usr/lib/tmpfiles.d/systemd-nologin.conf
 ```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5), systemd-user-session.service(5) and pam_nologin(8).
# This file has special suffix so it is not run by mistake.

F! /run/nologin 0644 - - - "System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)."

```

**Comment by poettering** [comment]
the idea is that during early boot logind isn't around hence pam_systemd won't talk to it, and thus the whole user@0.service service not be startd, and systemd-user-session.service is not started.

During late boot logind is up, and pam_systemd hence will talk to it, and this means user@0.service will be started.

If you don't want user@0.service, that#s fine, simply mask it, it should just work then.

You appear to be interested in a case where sshd and logind is up, but systemd-user-session.service can still take a while? we do cover that in a reasonable way I think: we wait for it, and give eventually up.

Hence, I am not sure there's anything to fix here?

**Comment by poettering** [comment]
Or to say this differently: we can't really know via black magic if it's worth waiting for systemd-user-session.service. Hence we use the fact that `systemd-logind.service` is connectible as indicator whether to wait and time-out everything. Once that service is reached we decide: it's worth waiting until the timeout is reached. Before that we decide: nope, just bypass everything, allow log-ins immediately.

I am tempted to close this, because I think the current behaviour makes a ton of sense.

**Comment by mphilipps** [comment]
My situation is that I have several sftp users that have bindfs (fuse) mounts within their home directory. I want to ensure that these mounts are ready before the user is allowed to login, because if they don't they may create files in the empty directories which in turn prevent the mount from succeeding. 
I thought the solution here would be to create drop dropin that establishes a dependency between the mounts and `systemd-user-sessions.service`and mounts.  

However if the bindfs mounts or the cifs mount they depend on fail I want to be able to login in as root and examine/fix the issue. I thought pam_nologin would be my best option to prevent logins from unprivileged users during that period of the boot process.  

If this is not the case, what is your suggestion? Ensuring mounts are ready for the users using them shouldn't be that uncommon.
