### ISSUE TITLE
Make the resolvconf command behave the same as old behaviour with stub-resolv.conf

### ISSUE THREAD

**Issue by smekkley** [systemd/systemd#19283]
Strongswan, a VPN client probably runs something like `resolvconf -a enp0s8 <<< "nameserver 8.8.8.8"` when it gets configured to use remote dns server.  
  
The problem is that with systemd resolver(127.0.0.53), it adds the entry after the original address, so name won't get resolved using the address which causes some wait time until systemd-resolved decides to use the newly added dns server as the current one.  Also this failover doesn't happen if it's reachable to the original dns server.
   
Can we maybe patch it in away the it behaves the same like /etc/resolve.conf, as in when resolvconf is run, it sets the dns server as the current one immediately? Or would it be against the intention of the designed behaviour?

**Comment by poettering** [comment]
Please, fill out the bug submission form, thank you. And quite frankly, I don't grok much of what you say. Please provide "resolvectl status" output, and say which resolvconf implementaiton you use and so on. Otherwise this is really not actioble at all, because wildly underspecified.

**Comment by smekkley** [comment]
Sorry.  Here is the output from Fedora 33 (systemd 246)

Before
````
Link 9 (enp0s20f0u2)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 8.8.8.8
         DNS Servers: 8.8.8.8
```  

After strongswan has run. (It's trying to set 10.100.10.53 but the current doesn't change, if I block the access to 8.8.8.8, it switches in time.)
```
Link 9 (enp0s20f0u2)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 8.8.8.8
         DNS Servers: 10.100.10.53
                      8.8.8.8
```

**Comment by poettering** [comment]
where does your /usr/bin/resolvconf symlink point? 

it appears strongswan configures two DNS servers, not just one. i.e. 8.8.8.8 is among them, so if that DNS server shall not be used, why does it configure it?

**Comment by smekkley** [comment]
8.8.8.8 is the one I get from the local dhcp server(systemd-networkd dhcp client), and it seems to stay.   
strongswan only serves a single dns server.
```
/usr/sbin/resolvconf -> ../bin/resolvectl
```
 
I can reproduce it by running `resolvconf -a enp0s20f0u2 <<< "nameserver 10.10.100.53"`

The main difference from classic /etc/resolve.conf is that the new entry doesn't come to the first. The issue doesn't happen.  
  
But from your response, maybe this isn't designed behaviour, let me try with other non-fedora setup.

**Comment by poettering** [comment]
Closing, since this appears to be a local issue.
