### ISSUE TITLE
systemd target regex

### ISSUE THREAD

**Issue by PatHoo** [systemd/systemd#19293]
**Is your feature request related to a problem? Please describe.**
I have this service file: `test@.service`
```
[Unit]
Description=test
PartOf=test.target

[Service]
Environment=PORT="$((100 + %i))"
ExecStart=/bin/bash -c '/bin/echo ${PORT} > /tmp/test-%i.log'

[Install]
WantedBy=multi-user.target
```
and the target file: `test.target`
```
[Unit]
Description=test
#Requires=test@[0-2].service
#Requires=test@{0..2}.service
Requires=test@0.service test@1.service test@2.service

[Install]
WantedBy=multi-user.target
```
How can I do if I want something like this: `#Requires=test@[0-2].service` or `#Requires=test@{0..2}.service`, so I don't need to write `Requires=test@0.service test@1.service test@2.service`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by poettering** [comment]
This doesn't work. I mean, what would you expect Requires=test@.*.target would do? i.e. a regex matching an unbounded number of strings? Should we pull in an unbounded number of units.

The thing is: we already went quite far with turning unit files into a templating language. I'd rather have less than more of that. Adding more and more string resolution logic to it makes it harder and harder for other programs to generate/parse our files, and I really don't like that. These files should be simple and declarative, but if you add wildcards and stuff to it, it becomes really hard to deduce what that even means.

Hence, I am against this. I sympathize with your use case, but I'd claim this is better solved with a script that instantiates a bunch of .requires/ symlinks for you then with a language extension that can explode regex expressions.

i.e. if you want a scripting/macro language use one there's nothing wrong with that. i.e. you could either generate the unit files with a macro or scrpt language or the symlinks to it. But i don't think systemd should take responsibility for it, we could never be as good as a proper scripting language.

I hope this makes a bit of sense, even if disappointing.

**Comment by PatHoo** [comment]
OK, got it.
