### ISSUE TITLE
systemd-nspawn --ephemeral creates problematic nested subvolume making container non-deletable

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#193]
When using systemd-nspawn --ephemeral, the temporary subvolume will contain a nested subvolume for var/lib/machines; which makes the temporary subvolume non-deletable:

```
Container stuff terminated by signal KILL.
Cannot remove subvolume '/var/lib/machines/.#stuff7ebdaddeb5da4865', ignoring: Directory not empty
```

This can be fixed by executing `btrfs subvolume delete /var/lib/machines` from within the container, or `btrfs subvolume delete /var/lib/machines/#stuff7ebdaddeb5da4865/var/lib/machines` from the host before exiting the container.

Removing the subvolume from the original template won't work (nspawn will recreate it anyway), the only work-around is to create a normal directory in the template; so the container won't copy/create the subvolume

**Comment by dvdhrm** [comment]
We support recursive subvolume removal, and nspawn actually tries to do this. Which systemd version do you use? Does this still happen with -git?

**Comment by SjonHortensius** [comment]
You're right; I should have mentioned that. This is with systemd-219; should that feature be available?

**Comment by poettering** [comment]
Recursive snapshotting and removal is a v220 feature. Please upgrade
