### ISSUE TITLE
udev: slash in nvme model attribute leads to directories in /dev/disk/by-id

### ISSUE THREAD

**Issue by mwhudson** [systemd/systemd#19309]
**systemd version the issue has been seen with**
 
Not actually sure, but afaict basically any version since by-id links for nvme devices was added in a5110c90303cf455db5062faef34d5724d12e2e9 up until git master will do this.

**Used distribution**

Ubuntu 20.04.

**Linux kernel version used** (`uname -a`)

5.4.0

**CPU architecture issue was seen on**
 
amd64

**Expected behaviour you didn't see**

Symlinks directly in /dev/disk/by-id

**Unexpected behaviour you saw**

As seen in https://discourse.maas.io/t/unable-to-deploy-valueerror-failed-to-find-storage-volume-id-nvme0n1/4442, a / in the model reported by a nvme device leads to a directory in /dev/disk/by-id.

**Steps to reproduce the problem**

 1. Find a NVMe device with a / in it's reported model name (this is the hard part)
 2. boot a system with it in
 3. find /dev/disk/by-id -type d

Maybe this is something that we need to cope with but it was certainly unexpected for me. I also can't see how to fix this by changing the udev rule, all I can think of is some variant of the "$attr{file}" syntax that indicates that escaping should be done, or that the kernel be changed to escape this value.

**Comment by yuwata** [comment]
@mwhudson Does the PR #19312 solve your issue?

**Comment by mwhudson** [comment]
Thanks for the super quick PR which does help (I commented on the PR too)

After finding this, I wondered about whether I could set model to say "../../../etc/shadow" and cause arbitrary files to be overwritten but this doesn't work because path_make_relative (called by node_symlink) rejects such paths. This feel a touch accidental for something that's a potential security issue, so I wonder if it's worth having the handler for SYMLINK+= explicitly reject paths with /../ in or something?
