### ISSUE TITLE
cannot see cursor while editing boot line via "e"

### ISSUE THREAD

**Issue by crysman** [systemd/systemd#19301]
**Issue/Bug Description:**
cannot see cursor while editing boot line via "e" :(

**Steps to reproduce (if you know):**
reboot, press "e" to edit boot parameters, move cursor by left and right arrows - cursor cannot be seen

**Expected behavior:**
cursor functional

**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
❱ apt policy systemd
systemd:
  Installed: 246.6-1ubuntu1.3pop0~1617377719~20.10~ce920ac
  Candidate: 246.6-1ubuntu1.3pop0~1617377719~20.10~ce920ac
  Version table:
 *** 246.6-1ubuntu1.3pop0~1617377719~20.10~ce920ac 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     246.6-1ubuntu1.3 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     246.6-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
```

**Other Notes:**

1. editing the line without cursor is a real pain :(
2. originally posted here https://github.com/isantop/kernelstub/issues/31

**Comment by poettering** [comment]
what is this about? are you talking about the boot loader "sd-boot"?

**Comment by poettering** [comment]
note that we rely on the firmware's console support. If it doesn't show a cursor, not sure we can do much about it.

**Comment by crysman** [comment]
@poettering _POP OS_ seems to be using  `systemd` and `kernelstub`
if it's firmware console, that's bad news, they do not tend to cooperate much on FOSS stuff :( Thanks for reply, anyways!
PS: Using `ACER SPIN 5` laptop.

**Comment by crysman** [comment]
OK, I've commented on this here on ACER forum
https://community.acer.com/en/discussion/636073/spin-5-sp513-54n-efi-bios-boot-cursor-cannot-be-seen/p1?new=1

**Comment by crysman** [comment]
asked here on ACER forum https://community.acer.com/en/discussion/636073/spin-5-sp513-54n-efi-bios-boot-cursor-cannot-be-seen/p1?new=1
