### ISSUE TITLE
Wrong PID passed to systemd-coredump for process in different PID namespace

### ISSUE THREAD

**Issue by antrik** [systemd/systemd#1930]
The default /usr/lib/sysctl.d/50-coredump.conf shipped with systemd sets the core dump command to '/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e', where %p is the "PID of dumped process, as seen in the PID namespace in which the process resides" (according to http://man7.org/linux/man-pages/man5/core.5.html ) -- so when a process dumps core inside a container, systemd-coredump (running in the global PID namespace) gets the wrong PID, and thus fetches meta data (command name etc.) from the wrong process. (See https://github.com/coreos/bugs/issues/172 and https://groups.google.com/forum/#!topic/coreos-user/l00MNe6fOHM )

This can be avoided by using %P ("PID of dumped process, as seen in the initial PID namespace (since Linux 3.12)") instead of %p.

Is there any reason for not using %P in the default config shipped with systemd?

**Comment by poettering** [comment]
No, really, sounds like something to fix.

**Comment by poettering** [comment]
will prep a fix

**Comment by poettering** [comment]
Of course, apparently there's not "%U" to match the same namespacing logic for the userns stuff... Meh.
