### ISSUE TITLE
machinectl is closing root-shell immediately

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#1933]
Hello,
when I want to open a root-shell via `machinectl shell` on the localhost the shell is closed immediately:

```
==== AUTHENTICATING FOR org.freedesktop.machine1.host-shell ===
Authentication is required to acquire a shell on the local host.
Authenticating as: root
Password: 
==== AUTHENTICATION COMPLETE ===
Connected to the local host. Press ^] three times within 1s to exit session.

Connection to the local host terminated.
```

I am running:

GNU/Linux 4.2.5-1-ARCH
systemd 227
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN

my standard shell for root is zsh.. maybe thats the problem. I know that normally I should just jump into bash via machinectl.

**Comment by poettering** [comment]
Fixed in the upcoming 228.
