### ISSUE TITLE
Inaccurate description of cgroup controllers required by systemd-oomd.service

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#19331]
The man page for [`systemd-oom.service`](https://www.freedesktop.org/software/systemd/man/systemd-oomd.service.html#Setup%20Information) states:

> ## Setup Information
> The system must be running systemd with a full unified cgroup hierarchy for the expected cgroups-v2 features. Furthermore, resource accounting must be turned on for all units monitored by **systemd-oomd**. The easiest way to turn on resource accounting is by ensuring the values for `DefaultCPUAccounting`, `DefaultIOAccounting`, `DefaultMemoryAccounting`, and `DefaultTasksAccounting` are set to true in [systemd-system.conf(5)](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html).

Reading the oomd code, only the memory controller seems to be used, meaning no setup is needed as `DefaultMemoryAccounting` defaults to yes. There is a chance that I missed something in the code, but if the memory controller truly is the only required cgroup controller, perhaps the sentence should be rephrased to make it clear that no additional setup is needed.

**Comment by anitazha** [comment]
You're right systemd-oomd only uses the memory controller based properties so only `DefaultMemoryAccounting` is needed. Happy to take a patch or I can put one up today.

**Comment by klausenbusk** [comment]
> I can put one up today.

Fine by me
