### ISSUE TITLE
TEST-56-EXIT-TYPE is strangely flaky

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#19345]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > CentOS 8, Arch Linux

As already discussed in https://github.com/systemd/systemd/pull/19248#discussion_r609993606, TEST-56 became flaky and the fails point to a potential issue:

Related test code:
https://github.com/systemd/systemd/blob/6604fb0207ee10e8dc05d67f6fe45de0b193b5c4/test/units/testsuite-56.sh#L80-L92

Journal from a failing test run:
```
[ 1620.848148] testsuite-56.sh[26]: + cat
[ 1620.849079] testsuite-56.sh[26]: + chmod +x /tmp/test56-exit-cgroup-unclean.sh
[ 1620.849996] testsuite-56.sh[26]: + systemd-run --wait --unit=eight -p ExitType=cgroup /tmp/test56-exit-cgroup-unclean.sh
...
[ 1620.858801] testsuite-56.sh[90]: Running as unit: eight.service
...
[ 1620.860920] test56-exit-cgroup-unclean.sh[92]: + sleep 1
[ 1620.868374] systemd[1]: eight.service: Passing 0 fds to service
[ 1620.868418] systemd[1]: eight.service: About to execute /tmp/test56-exit-cgroup-unclean.sh
[ 1620.868466] systemd[1]: eight.service: Forked /tmp/test56-exit-cgroup-unclean.sh as 91
[ 1620.868617] systemd[1]: eight.service: Changed dead -> running
[ 1620.868661] systemd[1]: eight.service: Job 514 eight.service/start finished, result=done
[ 1620.868705] systemd[1]: Started /tmp/test56-exit-cgroup-unclean.sh.
...
[ 1620.869420] systemd[1]: Received SIGCHLD from PID 91 (bash).
[ 1620.869463] systemd[1]: Child 91 (bash) died (code=exited, status=0/SUCCESS)
[ 1620.869504] systemd[1]: eight.service: Child 91 belongs to eight.service.
[ 1621.862168] test56-exit-cgroup-unclean.sh[92]: + exit 255
[ 1621.862504] systemd[1]: systemd-journald.service: Received EPOLLHUP on stored fd 37 (stored), closing.
[ 1621.862795] systemd[1]: eight.service: Control group is empty.
[ 1621.862857] systemd[1]: eight.service: Deactivated successfully.
[ 1621.862908] systemd[1]: eight.service: Service will not restart (restart setting)
[ 1621.862965] systemd[1]: eight.service: Changed running -> dead
[ 1621.863053] systemd[1]: eight.service: Consumed 4ms CPU time.
[ 1621.863229] systemd[1]: Received SIGCHLD from PID 92 (bash).
[ 1621.863295] systemd[1]: Child 92 (bash) died (code=exited, status=255/EXCEPTION)
[ 1621.863341] systemd[1]: system.slice: Child 92 belongs to system.slice.
[ 1621.865025] testsuite-56.sh[90]: Finished with result: success
[ 1621.865025] testsuite-56.sh[90]: Service runtime: 1.004s
[ 1621.865025] testsuite-56.sh[90]: CPU time consumed: 4ms
[ 1621.865579] systemd[1]: eight.service: Collecting.
[ 1621.865727] testsuite-56.sh[26]: + echo 'unexpected success'
[ 1621.865727] testsuite-56.sh[26]: unexpected success
[ 1621.865987] testsuite-56.sh[26]: + exit 1
[ 1621.866092] systemd[1]: Received SIGCHLD from PID 26 (bash).
[ 1621.866148] systemd[1]: Child 26 (bash) died (code=exited, status=1/FAILURE)
[ 1621.866196] systemd[1]: testsuite-56.service: Child 26 belongs to testsuite-56.service.
[ 1621.866255] systemd[1]: testsuite-56.service: Main process exited, code=exited, status=1/FAILURE
[ 1621.866383] systemd[1]: testsuite-56.service: Failed with result 'exit-code'.
```
Full journal: [system.journal.tar.gz](https://github.com/systemd/systemd/files/6329941/system.journal.tar.gz)

The service exited with EC 255, however systemd-run reports 'success' :thinking:.

/cc @keszybz @bluca

**Comment by keszybz** [comment]
So... was this caused by https://github.com/systemd/systemd/pull/19365/commits/291c5857c73bb907cd0fb1b843964198a9c4211b?

**Comment by bluca** [comment]
Unfortunately I don't think so, that was added less than a day ago via https://github.com/systemd/systemd/commit/5a3b86404a65d1f47da2d387fd84cebd1b3418a2 but the flakiness began last week

**Comment by unusual-thoughts** [comment]
Looks like a race condition in the implementation of `ExitType=cgroup`.

Somehow the cgroup empty notification arrives before the signal notification, hence why there is no `eight.service: Last process exited ...` line

It is then hitting one of the cases in
https://github.com/systemd/systemd/blob/main/src/core/service.c#L3262-L3266

Adding checks for `s->exit_type == SERVICE_EXIT_MAIN` in most (all ?) of these cases should fix the flakyness.
I'm also wondering why https://github.com/systemd/systemd/blob/main/src/core/service.c#L3294-L3296 doesn't have the `main_pid_good(s) == 0 && control_pid_good(s) == 0` check ?

This class of bug (inexact exit result) looks like it could still happen with `ExitType=main` when the main PID is unknown.
