### ISSUE TITLE
resolvconf-compat splits interface names at dots

### ISSUE THREAD

**Issue by jkhsjdhjs** [systemd/systemd#19357]
**systemd version the issue has been seen with**
 > 248

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux benziuminator 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `resolvconf -a client.wg0` tries to use the interface `client.wg0`

**Unexpected behaviour you saw**
 > `resolvconf -a client.wg0` tries to use the interface `client`

**Steps to reproduce the problem**
 > run `resolvconf -a` for an interface containing a dot

**Additional information**
> I experienced this issue when using `wg-quick` to create a wireguard connection:
```
# wg-quick up client.wg0.conf
[#] ip link add client.wg0 type wireguard
[#] wg setconf client.wg0 /dev/fd/63
[#] ip -4 address add 172.18.30.2/24 dev client.wg0
[#] ip link set mtu 1420 up dev client.wg0
[#] resolvconf -a client.wg0 -m 0 -x
Failed to resolve interface "client": No such device
[#] ip link delete dev client.wg0
```

**Comment by poettering** [comment]
it's how "resolvconf" is designed to work unfortunately. We didn#t define the interface. See:

https://manpages.ubuntu.com/manpages/trusty/man8/resolvconf.8.html

Don't use dots in interface names if you intend to use resolvconf. Sorry.

**Comment by jkhsjdhjs** [comment]
Ah, I understand. Thanks for the info!
