### ISSUE TITLE
[networkd] please log obtained prefix

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#19354]
Hi,

after obtaining an IPv6 assignment from the DHCPv6 server, networkd logs the received address:

    Apr 19 15:17:59 prom systemd-networkd[34240]: unt381: DHCPv6 address 2001:16b8:30d4:fa00:840f:33ff:fe68:445f/128 timeout preferred 3600 valid 7200

This is nice.

If a prefix is delegated from the server (IA_PD), the received prefix should be logged as well.

Greetings
Marc

**Comment by yuwata** [comment]
Sure. Waiting in #19362.
