### ISSUE TITLE
Unlocking with FIDO2 (yubikey) fails with hmac in second slot on key

### ISSUE THREAD

**Issue by takooakes** [systemd/systemd#19367]
**systemd version the issue has been seen with**
> 248

**Used distribution**
> Arch Linux with systemd 248-5

**Linux kernel version used** (`uname -a`)
> Linux hades 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
> LUKS partition should unlock with fido2 key

**Unexpected behaviour you saw**
> Failed to activate with FIDO2 decrypted key. (Key incorrect?)

**Steps to reproduce the problem**
> Setup HMAC challenge on slot 2 of yubikey
> Use cryptenroll to add fido2 key to LUKS partition
> Attempt to unlock the partition

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
> $ systemd-cryptenroll --fido2-device=auto /dev/vg0/cryptswap
> 🔐 Please enter current passphrase for disk /dev/vg0/cryptswap: *********               
> Initializing FIDO2 credential on security token.
> 👆 (Hint: This might require verification of user presence on security token.)
> 🔐 Please enter security token PIN: ********                
> Generating secret key on FIDO2 security token.
> 👆 In order to allow secret key generation, please verify presence on security token.
> New FIDO2 token enrolled as key slot 3.
> $  /usr/lib/systemd/systemd-cryptsetup attach resumeSwap /dev/vg0/cryptswap - fido2-device=auto
> Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/vg0/cryptswap.
> Automatically discovered security FIDO2 token unlocks volume.
> Asking FIDO2 token for authentication.
> Security token requires user presence.
> Failed to activate with FIDO2 decrypted key. (Key incorrect?)

**Comment by bluca** [comment]
Can you please try https://github.com/systemd/systemd/pull/19298 and see if it solves the problem?

**Comment by takooakes** [comment]
Yes #19298 does indeed fix the problem.
