### ISSUE TITLE
regression:  systemd-gpt-auto-generator[pid]: Failed to dissect: Connection timed out

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#19377]
**systemd version the issue has been seen with**
master @ https://github.com/systemd/systemd/commit/5efbd0bf897a990ebe43d7dc69141d87c404ac9a

**Used distribution**
own project

**Linux kernel version used** (`uname -a`)
5.11.15

**CPU architecture issue was seen on**
x64

**Expected behaviour you didn't see**
systemd-gpt-autogenerator does not fail, smooth boot

**Unexpected behaviour you saw**
systemd-gpt-autogenerator fails, boot is delayed at least a minute, however somehow journal does not reflect the delay
```
Apr 21 02:02:34 asusb450eg systemd[1]: Inserted module 'autofs4'
Apr 21 02:02:34 asusb450eg systemd[1]: systemd 248-428-g5efbd0b+ running in system mode. (+PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Apr 21 02:02:34 asusb450eg systemd[1]: Detected architecture x86-64.
Apr 21 02:02:34 asusb450eg systemd-gpt-auto-generator[219]: Failed to dissect: Connection timed out
Apr 21 02:02:34 asusb450eg systemd[209]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
```

**Steps to reproduce the problem**
boot a UEFI/GPT system

**Additional program output to the terminal or log subsystem illustrating the issue**
running ` /usr/lib/systemd/system-generators/systemd-gpt-auto-generator` from console after the system has booted succeeds (exit 0),

**Comment by poettering** [comment]
is this reproducible on more current git?

**Comment by asavah** [comment]
> is this reproducible on more current git?

Sorry for the delay, wasn't able to do a fresh build due to time constraints.
Yes, the error is still there, nothing has changed.

```
Apr 29 04:27:59 asusb450eg systemd[1]: systemd 248-606-gbf8a5f6+ running in system mode. (+PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Apr 29 04:27:59 asusb450eg systemd[1]: Detected architecture x86-64.

-- system stalls for at least 1 minute at this point, journal does not reflect this delay --

Apr 29 04:27:59 asusb450eg systemd-gpt-auto-generator[219]: Failed to dissect: Connection timed out
Apr 29 04:27:59 asusb450eg systemd[208]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
```

**Comment by poettering** [comment]
Any chance you can bisect this?

This is on a regular host system? No werid virtualization/containerization or so in the mix?

**Comment by poettering** [comment]
hmm, so my educated guess is that you either have no initrd or no initrd with systemd/udev in it, is that right?

**Comment by poettering** [comment]
I am pretty sure #19777 will fix the issue for you

**Comment by asavah** [comment]
@poettering If memory serves the issue started with https://github.com/systemd/systemd/pull/19368 .
Yes the system has no initrd/initramfs at all.

Will build with the PR you mentioned and report back here.

**Comment by asavah** [comment]
#19368 indeed fixes the issue.
System boots instantly, thank you.
