### ISSUE TITLE
systemd uses stale fstab

### ISSUE THREAD

**Issue by frankheckenbach** [systemd/systemd#1938]
Observed with systemd version 215-17+deb8u2 (Debian jessie)

The following happened to me, as far as I can recollect after the fact:
- While booting I had an entry in /etc/fstab like
  `/dev/sdc1 /mnt ... noauto`
- Later, I changed the entry to "/dev/sdb1 ..." and mounted it manually.
- Later again, I plugged in a completely unrelated disk, which was detected as /dev/sdc, and partitioned it (I did not mount anything).
- Suddenly I found /mnt unmounted.
- This was mostly reproducible (i.e. mount /mnt; partition /dev/sdc, /mnt is umounted).
- The only hint I found was this small entry in syslog:
  `Sep 14 12:40:25 base systemd[1]: Unit mnt.mount entered failed state.`
- To get details, I did:

```
  systemctl status mnt.mount
  * mnt.mount - /mnt
    Loaded: loaded (/etc/fstab)
    Active: failed (Result: exit-code) since Mon 2015-09-14 12:42:08 CEST; 636ms ago
     Where: /mnt
      What: /dev/sdc1
      Docs: man:fstab(5)
            man:systemd-fstab-generator(8)
   Process: 2186 ExecUnmount=/bin/umount -n /mnt (code=exited, status=0/SUCCESS)

   Sep 14 12:42:08 pax systemd[1]: Unit mnt.mount entered failed state.
```
- So there's the error here: It thinks /mnt had mounted /dev/sdc1 rather than /dev/sdb1 (which it really did, and which mount confirmed -- and it couldn't possibly have been /dev/sdc1 anyway, since I'd just been creating the partition).
- The only connection to /dev/sdc1 I could remember was the old entry in /etc/fstab. I verified that I had really changed it, so something was obviously using stale information.
- Remembering what little I know about systemd, I did "systemctl daemon-reload", and indeed this seemed to fix the problem.

I claim this is a bug because what I did had nothing to do with systemd (from a user's perspective).

It's OK when systemd requires a reload when one edits systemd's configuration. It might be acceptable when editing e.g. legacy scripts under /etc/init.d for which systemd claims to be a replacement.

But it's not OK to require extra steps when just using plain old Unix commands and configuration (/etc/fstab, mount, creating partitions).

If systemd must interfere with mounts at all, it must do so transparently, i.e. in this case, catch changes to /etc/fstab by itself or recheck it automatically when acting on it, because /etc/fstab is not systemd's own configuration, and it's not up to systemd to determine how it's to be used.

**Comment by arvidjaar** [comment]
Current systemd is 227 and there were changes in this area. Can you reproduce the problem with current version?

**Comment by frankheckenbach** [comment]
I tried with the current version in stretch (227-2) and I could not reproduce the problem like above. I hope it's really fixed, and not just circumstances changes slightly; i.e. doesn't systemd require manual reloading of fstab anymore?

**Comment by codywohlers** [comment]
I'm having this issue with `229-4ubuntu19` (on KDE neon)

When I plug in my USB drive:
syslog:
```
Aug 30 07:18:36 macbook systemd[1]: Mounting /media/user/usbdrive...
Aug 30 07:18:36 macbook mount[14059]: mount: wrong fs type, bad option, bad superblock on /dev/sdb2,
Aug 30 07:18:36 macbook mount[14059]:        missing codepage or helper program, or other error
Aug 30 07:18:36 macbook mount[14059]:        In some cases useful info is found in syslog - try
Aug 30 07:18:36 macbook mount[14059]:        dmesg | tail or so.
Aug 30 07:18:36 macbook systemd[1]: media-user-usbdrive.mount: Mount process exited, code=exited status=32
Aug 30 07:18:36 macbook systemd[1]: Failed to mount /media/user/usbdrive.
Aug 30 07:18:36 macbook systemd[1]: media-user-usbdrive.mount: Unit entered failed state.
Aug 30 07:18:36 macbook kernel: [39731.386234] EXT4-fs (sdb2): Unrecognized mount option "nobootwait" or missing value
```

I used to have a line in fstab with the incorrect `nobootwait` option but I removed the whole line, rebooted the machine and when I plug in the drive, systemd tries to mount it again with the old fstab options.  (It doesn't try to mount the other partitions on the drive which never had an fstab entry)
