### ISSUE TITLE
Reattach make system unbootable.

### ISSUE THREAD

**Issue by devbapidey** [systemd/systemd#19404]
**systemd version the issue has been seen with**
 > … 246.6-1ubuntu1.3

**Used distribution**
 > … ubuntu 20.10

**Linux kernel version used** (`uname -a`)

 > `…` Linux 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > … amd64 with Intel Pentium g4560

**Describe Problem**
> ... I have 2 gpu(igpu+nvidia gt1030) with 2 seat via loginctl. When I attach drm 1 to seat0 for and reboot. Both screen black. Note here seat0 is vga and seat1 is hdmi. When I disconnect hdmi with pc system boot successful.

**Expected behaviour you didn't see**
 > … 

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > … make a seat and attach keyboard mouse sound and drm. reboot. > now reattach drm with seat0. reboot > blackout. click power button. > remove hdmi cable. click power button. Ok. > reattach drm to seat1. poweroff. > attach hdmi cable. click power button.> All ok.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
This doesn't sound like a systemd issue, but a driver one. Please contact your downstream distro for help first, they'll propagate this to us if there's really a systemd issue here.
