### ISSUE TITLE
udev assigns the same ID_PATH for different usb devices (Built-in USB camera and External USB 3.0 camera via USB-C port)

### ISSUE THREAD

**Issue by williamiced** [systemd/systemd#19406]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `Linux localhost 5.4.113-14419-g47d1a7be3a65 #1 SMP PREEMPT Thu Apr 22 12:49:28 CST 2021 x86_64 Intel(R) Core(TM) i5-7Y57 CPU @ 1.20GHz GenuineIntel GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > The same ID_PATH are given for built-in USB camera and the external USB 3.0 camera (Connected via USB-C port) while they are both connected.

**Steps to reproduce the problem**
 > I observed the issue on a Google Pixelbook using the USB-C port on the right side.

Built-in Camera:
```
$ udevadm info --query=all /dev/video0
...
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/video4linux/video0
...
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
```

External Camera:
```
$ udevadm info --query=all /dev/video2
...
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/video4linux/video2
...
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
```

There is a similar issue which is filed a few years ago:
https://github.com/systemd/systemd/issues/10683

Here are some extra outputs which are asked to provide in that issue:
[Output of $ lspci -nnv](https://gist.github.com/williamiced/4a3f3f3b9a3a79a5f49d36313b3aacc3)
[Output of $ lsusb -v](https://gist.github.com/williamiced/097334b4f61e5ceb5713dbde99225b8f)
[Output of $ udevadm info --export-db](https://gist.github.com/williamiced/1d2a0d4e55990a1e972b2875475ecf8e)
[Output of $ ls -lR /sys](https://gist.github.com/williamiced/7b9e7c1b081bdf894fc20a461f4996cd)

Please let me know if you need any more information.
Thanks for helping.

**Comment by yuwata** [comment]
@arvidjaar Hi! You commented in #21620 that the bus number is not stable, so should not be used in ID_PATH. But then, that introduces this conflict. Do you have any idea?

**Comment by arvidjaar** [comment]
@yuwata 

Yes, this is xHCI interface which registers two USB root hubs (and creates two separate USB buses) for USB 2.0 and USB 3.0. The only heuristic I see in sysfs is USB version:

```
$ grep . /sys/devices/pci0000\:00/0000\:00\:14.0/usb?/pro*
/sys/devices/pci0000:00/0000:00:14.0/usb2/product:xHCI Host Controller
/sys/devices/pci0000:00/0000:00:14.0/usb3/product:xHCI Host Controller
$ grep . /sys/devices/pci0000\:00/0000\:00\:14.0/usb?/idP*
/sys/devices/pci0000:00/0000:00:14.0/usb2/idProduct:0002
/sys/devices/pci0000:00/0000:00:14.0/usb3/idProduct:0003
$ 
```

Driver registers USB 2.0 first and USB 3.0 second. So we _could_ check if product is xHCI and assign **relative** bus number (e.g. 0 for USB 2.0 and 1 for USB 3.0) depending on idProduct. But this information is not available for USB device itself, it is necessary to go up to HCI itself. We get HCI node after `skip_subsystem(parent, "usb")`.

It is still wrong to take bus number verbatim. And I think this should be discussed with kernel USB maintainers how to identify this case.

Note that also `ID_PATH` for HCI nodes themselves is identical - you get `ID_PATH=pci-0000:00:14.0` for both usb2 and usb3. Whether this is a problem I do not know.

Actually adding explicit HCI node handling this could be `ID_PATH=pci-0000:00:14.0-usb-0` or `ID_PATH=pci-0000:00:14.0-usb-1` for HCI itself and then adding USB connection path to it for connected devices.

**Comment by ribalda** [comment]
Couldn't we append the value of `bDeviceProtocol`. It should be 1 for usb2 and 3 for usb3. Something like:

- `pci-0000:00:14.0-usbv1-0:2:1.0`
- `pci-0000:00:14.0-usbv3-0:2:1.0`

**Comment by ribalda** [comment]
ping?
