### ISSUE TITLE
systemctl preset-all fails completely on any error and even on missing Also= unit

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#19407]
```
[user@rosa2019 ~]$ cat /lib/systemd/system/sysstat.service
<...>
[Unit]
Description=Resets System Activity Logs

[Service]
Type=oneshot
RemainAfterExit=yes
User=root
ExecStart=/usr/lib64/sa/sa1 --boot

[Install]
WantedBy=multi-user.target
Also=sysstat-collect.timer
Also=sysstat-summary.timer
```

sysstat-collect.timer and sysstat-summary.timer do not exist. But `systemctl preset-all` fails because of this:
```
[user@rosa2019 ~]$ sudo systemctl preset-all --preset-mode=enable-only
Failed to preset all units: Unit file sysstat-collect.timer does not exist.
[user@rosa2019 ~]$ echo $?
1
```

Other units have not been enabled even if they are OK (and remember https://github.com/systemd/systemd/issues/12345, e.g. getty@tty1.service was not enabled in my case).

Problem in the sysstat package will be fixed, but I did not expect preset-all to fail in such way even because of a unit which is not listed explicitly in presets, it matches only "disable *" glob.

**Comment by poettering** [comment]
Yeah, we probably should continue in a case like this
