### ISSUE TITLE
RFE: (Documentation) alias in template, seems that WantedBy=/Alias= can't be used together

### ISSUE THREAD

**Issue by moocan** [systemd/systemd#19409]
**Is your feature request related to a problem? Please describe.**
Two `Alias=` directive or `WantedBy=` and `Alias=` directive in `[Install]` section of a template service unit lead to have a non working alias with "Loaded: error (Reason: Unit alias to load properly: File Exists)"  while alias symlink are created when unit is enabled (and not removed when disabled).
This behavior is not encountered in standard service unit.

Standard Service

> /etc/systemd/system/foo.service
> [Unit]
> Description=foo
> [Service]
> ExecStart=/bin/echo "start"
> Type=idle
> [Install]
> WantedBy=getty.target
> Alias=bar.service
> 
> systemctl enable foo.service
> Created symlink /etc/systemd/system/bar.service ->  /etc/systemd/system/foo.service
> Created symlink /etc/systemd/system/getty.target.wants/foo.service ->  /etc/systemd/system/foo.service
> 
> systemctl start bar.service = OK
> systemctl stop bar.service = OK
> systemctl status bar.service
> foo.service - foo
> Loaded: loaded (/etc/systemd/system/foo.service; enabled; vendor preset: enabled)

Template Service

> /etc/systemd/system/foo@.service
> [Unit]
> Description=foo %i
> [Service]
> ExecStart=/bin/echo "start"
> TTYPath=/dev/%i
> Type=idle
> [Install]
> WantedBy=getty.target
> Alias=bar@.service
> DefaultInstance=tty12
> 
> systemctl enable foo@tty12.service
> Created symlink /etc/systemd/system/bar@tty12.service ->  /etc/systemd/system/foo@.service
> Created symlink /etc/systemd/system/getty.target.wants/foo@tty12.service ->  /etc/systemd/system/foo@.service
> 
> systemctl start bar@tty12.service = KO
> Failed to start bar@tty12.service: Unit bar@tty12.service failed to load properly: File Exists.
> See system logs and systemctl status bar@tty12.service for details
> 
> systemctl status bar@tty12.service
> Loaded: error (Reason: Unit bar@tty12.service to load properly: File Exists)
> 
> systemctl start foo@tty12.service = OK

Same behavior using in [Install] section:

> Alias=getty.target.wants/foo@%i.service
> Alias=bar@.service

> Alias=getty.target.wants/foo@.service
>systemd[1]: Invalid unit foo@tty12.service symlink getty.target.wants/foo@.service

**Describe the solution you'd like**
Please provide more details in documentation about alias with template unit.
Found only some information in this report #13990

**Describe alternatives you've considered**
No more aliases in templates

**The systemd version you checked that didn't have the feature you are asking for**
Current system: systemd 245
Tested with in a vm with systemd 248

Regards

**Comment by poettering** [comment]
smells like a bug. /cc @keszybz
