### ISSUE TITLE
Cannot enable service@instance file outside of /etc/systemd/system/

### ISSUE THREAD

**Issue by Simonesien** [systemd/systemd#19414]
**systemd version the issue has been seen with**
 ```
pi@minepi:~/minecraft-server $ sudo systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Linux kernel version used**
 ```
Linux minepi 5.10.17-v7l+ 1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
```
(Raspberry OS on Raspberry Pi 4)

**My personal Explanation**

If there is not a file named actually like "/home/pi/minecraft-server/minecraft@test.service", systemd doesn´t search in /home/pi/minecraft-server/ for minecraft@.service, but in /etc/systemd/system/. 

**The Error**
```
pi@minepi:~/minecraft-server $ sudo systemctl enable /home/pi/minecraft-server/minecraft@test.service
Failed to enable unit: Unit file /home/pi/minecraft-server/minecraft@test.service does not exist.
```

**Additional Information**
```
pi@minepi:~/minecraft-server $ ls -al
total 16
drwxr-xr-x  2 pi pi 4096 Apr 24 09:19 .
drwxr-xr-x 20 pi pi 4096 Apr 24 09:19 ..
-rwxr-xr-x  1 pi pi 3982 Apr 24 09:19 mc
-rw-r--r--  1 pi pi  471 Apr 24 09:18 minecraft@.service
pi@minepi:~/minecraft-server $ cat minecraft@.service 
[Unit]
Description=Minecraft Server
Wants=network.target
After=network.target

[Service]
Type=forking
User=pi
Group=pi
KillMode=none

PrivateDevices=no
NoNewPrivileges=yes
ReadWritePaths=/home/pi/minecraft-server
WorkingDirectory=/home/pi/minecraft-server
ExecStart=/home/pi/minecraft-server/mc %i start
ExecReload=/home/pi/minecraft-server/mc %i restart
ExecStop=/home/pi/minecraft-server/mc %i stop
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
```

**Comment by zdzichu** [comment]
You **must** put unit files in the paths specifed in `systemd.unit` man page (https://www.freedesktop.org/software/systemd/man/systemd.unit.html)
Using other paths is not supported and won't work.

**Comment by Simonesien** [comment]
Ok, and can you please add that systemd is also looking for the service file with an empty instance in the directory in which the file is located? I think it would be very helpful to a lot of people.

**Comment by poettering** [comment]
I am not convinced that makes sense. We have a search path, drop your stuff there. If you want to place stuff elsewhere, symlink it in there, but I am pretty sure we shouldn't go on a wild adventure ride and then pick up further dirs to enumerate stuff in as we go from these symlinks. That'd be really weird.

I think the documentation clearly says which search paths we look in, and tht's pretty simple and straightforward. Any magic logic of also picking up more stuff along the way makes things a bit too magic for my test.

Or in other words: just symlink the template unit into the earch path too.

Hope that makes some sense, even if disappointing. Sorry!
