### ISSUE TITLE
Endless "Not all MD devices stopped, 1 left" errors on shutdown on old kernels (< 4.4)

### ISSUE THREAD

**Issue by vl-80** [systemd/systemd#19418]
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux 4.4.264-gentoo`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Clean reboot

**Unexpected behaviour you saw**
 > Endless "Not all MD devices stopped, 1 left" messages on the screen (waited longer than 5 minutes)

**Steps to reproduce the problem**
 > Issue the `reboot` command on a system with active raid devices (md)

**Additional program output to the terminal or log subsystem illustrating the issue**

```
[  371.737980] systemd-shutdown[1]: Not all MD devices stopped, 1 left.
[  371.738108] systemd-shutdown[1]: Stopping MD devices.
[  371.738543] systemd-shutdown[1]: Stopping MD /dev/md0 (9:0).
[  371.844840] md: md0 stopped.
[  371.844927] systemd-shutdown[1]: Not all MD devices stopped, 1 left.
[  371.845054] systemd-shutdown[1]: Stopping MD devices.
[  371.845497] systemd-shutdown[1]: Stopping MD /dev/md0 (9:0).
[  371.948992] md: md0 stopped.
[  371.949076] systemd-shutdown[1]: Not all MD devices stopped, 1 left.
[  371.949203] systemd-shutdown[1]: Stopping MD devices.
[  371.949641] systemd-shutdown[1]: Stopping MD /dev/md0 (9:0).
[  372.003904] md: md0 stopped.
[  372.003988] systemd-shutdown[1]: Not all MD devices stopped, 1 left.
[  372.004115] systemd-shutdown[1]: Stopping MD devices.
[  372.004559] systemd-shutdown[1]: Stopping MD /dev/md0 (9:0).
[  372.057953] md: md0 stopped.

These messages continue to appear on the console endlessly
```

**My own thoughts on the issue**

If I understand correctly, following is happening when Systemd is shutting down:
https://github.com/systemd/systemd/blob/be8fc0ef2ed702ee95c06075025f36b9f2a4f93d/src/shutdown/shutdown.c#L458-L468

`md_detach_all()` calls `md_list_get():`

https://github.com/systemd/systemd/blob/be8fc0ef2ed702ee95c06075025f36b9f2a4f93d/src/shutdown/umount.c#L826-L838

`md_list_get()` ends up scanning `/sys/class/block` and returns a list of `md*` entries.

Then, `md_points_list_detach()` calls `delete_md()`:

https://github.com/systemd/systemd/blob/bd6ea22920d83c61220d09fa3b4ae449216b9fdb/src/shutdown/umount.c#L726-L742

which successfully shuts down the array, as seen in the console output (`md: md0 stopped.`):

https://github.com/systemd/systemd/blob/bd6ea22920d83c61220d09fa3b4ae449216b9fdb/src/shutdown/umount.c#L477-L495

and because it succeeds, the `*changed` is set to `true`:

https://github.com/systemd/systemd/blob/bd6ea22920d83c61220d09fa3b4ae449216b9fdb/src/shutdown/umount.c#L733-L740

which gives `main()` a reason to continue trying endlessly:

https://github.com/systemd/systemd/blob/bd6ea22920d83c61220d09fa3b4ae449216b9fdb/src/shutdown/shutdown.c#L499-L509

**Possible cause**

I think the issue is specific to kernel versions < `4.6`. Per this [commit](https://github.com/torvalds/linux/commit/399146b80ed6fb9f1ebe5a07234f00dff446d2b4) kernels prior to `4.6` are generating a "change" udev event when md devices are stopped which causes the md device entry to reappear in the sysfs.

Systemd in turn will continue seeing this entry on every iteration of the main() in `shutdown.c` and will keep trying to shut it down even though it was already shut down.

Per [kernel.org](https://www.kernel.org/category/releases.html) kernel 4.4 is currently supported as LTS.

**Comment by poettering** [comment]
Why is this a systemd issue? Isn't this an isue with your old kernel? Why not backport the fix there?

**Comment by vl-80** [comment]
I do not want to insist that systemd needs to fix it. I decided to inform the community of this non-optimal behavior, because kernel 4.4 is going to be officially supported for another 10 months and people experiencing same problem might find this information useful.

**Comment by dimitry-ishenko** [comment]
> Why is this a systemd issue? Isn't this an isue with your old kernel? Why not backport the fix there?

That may break other non-systemd systems

**Comment by poettering** [comment]
> That may break other non-systemd systems

Well, on non-systemd systems break with newer kernels than 4.4, than thta's really not systemd's fault.

Either way, if you want to see this addressed, consider proposing a patch, otherwise I doubt anyone will look into this, given this such an old kernel (5y!)

**Comment by dimitry-ishenko** [comment]
> > That may break other non-systemd systems
> 
> Well, on non-systemd systems break with newer kernels than 4.4, than thta's really not systemd's fault.
> 
> Either way, if you want to see this addressed, consider proposing a patch, otherwise I doubt anyone will look into this, given this such an old kernel (5y!)

@poettering thank you, that seems reasonable. @vl-80 are you up to doing that?

**Comment by cjschroeder** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1970610

**Comment by vl-80** [comment]
The kernel version `4.4` has reached the EOL.
