### ISSUE TITLE
hostnamectl: cannot set transient hostname

### ISSUE THREAD

**Issue by programmer04** [systemd/systemd#19413]
**systemd version the issue has been seen with**
 > v248 and current main branch (works ok for v247 and previous)

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)

 > `Linux test2 5.8.15-301.fc33.x86_64 #1 SMP Thu Oct 15 16:58:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > It is possible to set transient hostname.

**Unexpected behaviour you saw**
 > Could not get property: Unknown interface org.freedesktop.hostname1 or property HostnameSource.

**Steps to reproduce the problem**
 > hostnamectl set-hostname test4 --transient

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.319 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.DBus.Properties member=Get cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Got message type=error sender=:1.317 destination=:1.319 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.UnknownProperty error-message=Unknown interface org.freedesktop.hostname1 or property HostnameSource.
Could not get property: Unknown interface org.freedesktop.hostname1 or property HostnameSource.
Bus n/a: changing state RUNNING → CLOSED
```
In logs from `journald` nothing appears when a version with the bug. When version without the bug is used below message is presented
```
Apr 23 18:18:16 test2 systemd-hostnamed[34505]: Changed hostname to 'test4'
```

**Comment by poettering** [comment]
this suggests you are running an old hostnamed with a new hostnamectl? did you reboot after upgrading systemd to v248? how did you install v248? manually compiled? maybe your version and fedora's got mixed up somehiw?

**Comment by programmer04** [comment]
I mismatched versions, everything works ok. Thanks!
