### ISSUE TITLE
journalctl: filter by hostname

### ISSUE THREAD

**Issue by sergey-safarov** [systemd/systemd#19427]
**Is your feature request related to a problem? Please describe.**
I use `systemd-journal-remote.service` to as logger from different servers.
in my config defined `SplitMode=none` and `--output=/var/log/journal/remote/remote.journal`
I want check log messages on given hostname.
Now, `journalctl` outputs server hostname but does not provide the ability to filter by this key.

**Describe the solution you'd like**
I prefer to use `hostname` key to filter messages.
```
journalctl  --file=remote.journal --follow --hostname=ip-100-86-41-76.ec2.internal
```

**The systemd version you checked that didn't have the feature you are asking for**
Checked man page from current master 2b4d791e41734e506e06f7906b174b51dfb0827c

**Comment by mrc0mmand** [comment]
Would using the `_HOSTNAME=` field work for you? E.g.:

```
$ journalctl  --file=remote.journal --follow _HOSTNAME=ip-100-86-41-76.ec2.internal
```

**Comment by sergey-safarov** [comment]
Yes, this allows the filter of log messages by hostname.
Could be updated journalctl man page to reflect ability to use `_HOSTNAME` as filter.

**Comment by sergey-safarov** [comment]
Looks a lot of info about message filtering may be added from this page
http://0pointer.net/blog/projects/journalctl.html

**Comment by mrc0mmand** [comment]
The `_HOSTNAME=` field along with other filterable fields is documented in the [systemd.journal-fields man page](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Trusted%20Journal%20Fields) (also referenced from the `journalctl` man page).

**Comment by sergey-safarov** [comment]
thanks, @mrc0mmand for clarification.
