### ISSUE TITLE
Add support for SyncJumpWidth to the CAN Network configuration

### ISSUE THREAD

**Issue by cwoodall** [systemd/systemd#19424]
**Is your feature request related to a problem? Please describe.**

I have a can device [PCAN-miniPCIE FD](https://www.peak-system.com/PCAN-miniPCIe-FD.464.0.html?&L=1 
) which for my network requires the SyncJumpWidth to be configured properly (based on the base clock frequency the default calculated by socketcan is too small of a time slice). At present I cannot configure the sync jump width automatically at bringup using a networkd file, and the can bus is flakey as a result.

The following documentation indicates the available settings in systemd.network: https://man7.org/linux/man-pages/man5/systemd.network.5.html#%5BCAN%5D_SECTION_OPTIONS

**Describe the solution you'd like**

- Adding an additional configuration option for `SyncJumpWidth` to the configuration file format. Add TQ, Seg1, Seg2, and PropSeg as well. 
- For my application setting the SamplePoint and allowing the calculation to be automatic and then setting just the SJW manually is acceptable. However, setting all manually would be acceptable (and more correct).

**Describe alternatives you've considered**

**The systemd version you checked that didn't have the feature you are asking for**

`systemd 245 (245.4-4ubuntu3.4)`
I also looked through the master branch for `SyncJumpWidth`, `sync jump width` and `sjw`.

I looked at this issue, but it did not seem like it made the bit timing configuration directly accessible. https://github.com/systemd/systemd/issues/15219

**Comment by poettering** [comment]
> The following documentation indicates the available settings in systemd.network: https://man7.org/linux/man-pages/man5/systemd.network.5.html#%5BCAN%5D_SECTION_OPTIONS
> 
> ****

The upstream version of the man page (i.e. usually a newer one) is available here btw:

https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BCAN%5D%20Section%20Options

**Comment by poettering** [comment]
best way to get this implemented is by providing a patch btw.

**Comment by cwoodall** [comment]
@poettering yep! I was planning on providing a patch I just wanted to get the issue reported for my own records.

i worked around for now by falling back to ifupdown for can devices... but I feel all configuration options should be made available through this interface (over time)

**Comment by yuwata** [comment]
Waiting in #20442. If possible, please test the PR.
