### ISSUE TITLE
systemd-shutdown[1] : Waiting for process: crond ---- System take too long to shutdown/reboot

### ISSUE THREAD

**Issue by devbapidey** [systemd/systemd#19430]
**systemd version the issue has been seen with**
 > … 247.3-3ubuntu3

**Used distribution**
 > … ubuntu 21.04

**Linux kernel version used** (`uname -a`)

 > `…` Linux 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > … amd64

**Expected behaviour you didn't see**
 > … Computer should shutdown in few seconds usually.

**Unexpected behaviour you saw**
 > … Computer takes too long to shut down.

**Steps to reproduce the problem**
 > … 
![IMG_20210426_232114](https://user-images.githubusercontent.com/33697097/116185183-bae03980-a73e-11eb-9c6a-6a4360c03ad1.jpg)

Update - I am useing nvidia driver(non-free) + nvidia-cuda-toolkit with nvidia-prime. This is only happen when I select nvidia on demand is active. When Intel / Nvidia performance mode selected system reboot/shutdown as usual.
![nvidia prime](https://user-images.githubusercontent.com/33697097/116191332-bec58900-a749-11eb-9fb0-bea42f34ef6a.png)

 

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
Seems cron is hanging for you. Which doesn't have much to do with systemd, it's just the messenger here. Also, if this is triggered by nvidia closed source stuff it's probably caused by that.

Either way, please contact your downstream distro first about this, i.e. the nvidia driver maintainers or the cron maintainers.
