### ISSUE TITLE
Missing / (commit cd0d230e7bf87f979722de7e364619dfa71bd6a2)

### ISSUE THREAD

**Issue by chprecision** [systemd/systemd#19456]
OS: Fedora34 (systemd version 248-2)

After upgrading to fedora34, system is unable to boot with "file not found" error. This is due to the fact that grub2 tries to load an image ($root)boot/xxx/5.11.15-300.fc34.c86_64/linux instead of ($root)/boot/xxx/5.11.15-300.fc34.c86_64/linux (note the slash between $root and boot)

After some investigation, it seems that the script 90-loaderentry.install script is generating the following entry:
#cat /boot/loader/entry/xxx-5.11.15-300.fc34.x86_64.conf
title      Fedora 34 (Thirty Four)
version    5.11.15-300.fc34.x86_64
machine-id xxx
options    root=UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx ro rhgb quiet
linux      boot/xxx/5.11.15-300.fc34.x86_64/linux
initrd     boot/xxx/5.11.15-300.fc34.x86_64/initrd
<-- end cat
Some 90-loaderentry.install script values
ENTRY_DIR_ABS=/boot/xxx/5.11.15-300.fc34.x86_64
MACHINE_ID=xxx
KERNEL_VERSION=5.11.15-300.fc34.x86_64
BOOT_ROOT=/boot
BOOT_MNT=/
ENTRY_DIR=boot/xxx/5.11.15-300.fc34.x86_64  <- missing leading slash

Previous working entry had the following content:
#cat /boot/loader/entry/xxx-5.8.18-100.fc31.x86_64.conf
title      Fedora 31 (Thirty One)
version    5.8.18-100.fc31.x86_64
machine-id xxx
options root=UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx ro rhgb quiet 
linux      /boot/xxx/5.8.18-100.fc31.x86_64/linux
initrd     /boot/xxx/5.8.18-100.fc31.x86_64/initrd

Commit cd0d230e7bf87f979722de7e364619dfa71bd6a2 removes a redundant leading /, but it seems wrong in my case. So maybe should be reverted.

**Comment by yuwata** [comment]
Fix is waiting in #19457. @chprecision Could you test the PR?

**Comment by chprecision** [comment]
Fix #19457 is working in my case.

**Comment by yuwata** [comment]
@chprecision Thank you!
