### ISSUE TITLE
Restrict static IP access when DHCP is enabled

### ISSUE THREAD

**Issue by rakesh1225** [systemd/systemd#19469]
I am using an embedded board with customized linux on it configured with both DHCP(client) and fallback static IP via Systemd service. 
We are handling all the worst case scenarios.
 1) Need to restrict the board to be accessed with only DHCP IP once DHCP IP is set automatically. It should not be accessed by the static IP at this time.
 2) When the DHCP IP is not assigned then the board should be accessed with the static IP automatically.
Scenario 2 is working already. Not sure for the Scenarion1 configuration

What could be the configuration for Scenario 1 to work?

We are allowed to configure DHCP client only. DHCP client config used :

[Link]
 RequiredForOnline=no

[Network] 
DHCP=ipv4
LinkLocalAddressing=ipv6 
Address=xxx.xxx.x.x/xx
 DNS=xxx.xxx.x.xxx

[DHCP] 
ClientIdentifier=mac
 RouteMetric=50 
UseMTU=true

[Route] 
Gateway=xxx.xxx.x.xxx 
Destination=x.x.x.x/x 
Metric=60

**Comment by yuwata** [comment]
Hmm... For that purpose, maybe link local address should be used?

Or, the device may possibly connect two networks, one has DHCP server, and the other has no DHCP server?

Could you elaborate more why such fallback mechanism is required??

**Comment by poettering** [comment]
hmm, so you want to have policy between the static IP address and the DHCP address? i.e. disable one if the other becomes available? revert back to the the one if the other's lease ends?

That'd be a new feature, there's no policy logic in place like that right now.

**Comment by rakesh1225** [comment]
@yuwata the board(DHCP client) is connected to router(may have DHCP server). It is on single network.
By any chance if the DHCP server is down then we can access the board using static IP. This is the reason.

@poettering  If not directly using configuration, is there any other work-around can we try for Scenario 1?

**Comment by poettering** [comment]
it does sound you want ipv4ll for this scenario though.

**Comment by rakesh1225** [comment]
@poettering @yuwata    can you confirm if this is the way you are suggesting

[Link]
RequiredForOnline=no

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv4
Address=xxx.xxx.x.x/xx
DNS=xxx.xxx.x.xxx

[DHCP]
ClientIdentifier=mac
RouteMetric=50
UseMTU=true

[Route]
Gateway=xxx.xxx.x.xxx
Destination=x.x.x.x/x
Metric=60

**Comment by yuwata** [comment]
The `Address=` line is dangerous, as it may conflicts with an address provided by the DHCP server to a host. The IPv4 link-local address should not conflicts with the pool of DHCP addresses. I suggests that you should simply drop the `Address=` line.

**Comment by rakesh1225** [comment]
Our intention is to maintain a fallback static IP also which can be used when DHCP is down.
If I remove this line it may effect the static IP right?

**Comment by yuwata** [comment]
I do not suggest such network configuration, but if you really want to configure a secondary address for that purpose, then, use the following.
```
[Address]
Address=xxx.xxx.xxx.xxx/yy
PreferredLifetime=0
```
And then migrate the secondary address when the host detects that the DHCP server is down.
But we do not (and will not, I guess) support the automatic migration feature for such configuration.
Please write your own script or something to do that.

Closing.
