### ISSUE TITLE
dhcp client behavior when one or more parameters are changed during renewal

### ISSUE THREAD

**Issue by prkatti1** [systemd/systemd#19461]
**systemd version the issue has been seen with**
 > systemd 247 (247.3+)

When we change one or more parameter on dhcp server during lease renewal, dhcp-client is getting updated with new values that are sent by DHCP server.

Like: When we just modify router value on dhcp server, dhcp client is updated with new router that is sent by dhcp server during lease renewal and erasing old value.
 
I also think that this is a correct behavior, however RFC 2131 does not say anything specific to router.

Need an expert openion/comment on this.

**Comment by yuwata** [comment]
networkd already evaluates router option on every renewal. Doesn't it work for you? Could you provide relevant debugging logs of networkd?

**Comment by prkatti1** [comment]
Hi @yuwata, yep it is picking new router value on every renewal and updated with new router.
Just wanted clarification, is that the correct behavior?
RFC 2131 does not say anything on dhcp-client behavior with respect to router change during lease renewal.

**Comment by yuwata** [comment]
> Hi @yuwata, yep it is picking new router value on every renewal and updated with new router.

@prkatti1 Ah, sorry, I misunderstood your point. And I am happy to hear that the DHCP client works as expected.

> Just wanted clarification on client behavior.
> RFC 2131 does not say anything on dhcp-client behavior with respect to router change during lease renewal.

Unfortunately, I am not sure... But the current behavior should be at least reasonable for many usecases, no?

Let's close this at least tentatively. If you or someone find that the current behavior is not compliant to RFC(s), then please request to reopen this.
