### ISSUE TITLE
 Can't use lxcfs with systemd-nspawn

### ISSUE THREAD

**Issue by brunorf** [systemd/systemd#19466]
```
Operating system: Ubuntu 20.10
Systemd 245 (245.4-4ubuntu3.4)
lxcfs 4.0.3
```

I don't know if this is the correct place for asking help, but I'm trying to use lxcfs with systemd-nspawn and for some reason this is not working, although it works well with lxc/lxd.

When systemd-nspawn container starts, it immediately stops and prints out:
```
$ sudo systemd-nspawn -b -D focal -M test-container --bind=/var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo --bind=/var/lib/lxcfs/proc/diskstats:/proc/diskstats --bind=/var/lib/lxcfs/proc/loadavg:/proc/loadavg --bind=/var/lib/lxcfs/proc/meminfo:/proc/meminfo --bind=/var/lib/lxcfs/proc/stat:/proc/stat --bind=/var/lib/lxcfs/proc/swaps:/proc/swaps --bind=/var/lib/lxcfs/proc/uptime:/proc/uptime
Spawning container test-container on /reserva/systemd-containers/focal.
Press ^] three times within 1s to kill container.
Failed to stat /var/lib/lxcfs/proc/diskstats: No such file or directory
Child died too early.
```

But lxcfs is mounted and working correctly with lxd:
```
$ mount | grep lxcfs
lxcfs on /var/lib/lxcfs type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)

$ ls -l /var/lib/lxcfs/proc/
total 0
-r--r--r-- 1 root root 0 mar  2 08:16 cpuinfo
-r--r--r-- 1 root root 0 mar  2 08:16 diskstats
-r--r--r-- 1 root root 0 mar  2 08:16 loadavg
-r--r--r-- 1 root root 0 mar  2 08:16 meminfo
-r--r--r-- 1 root root 0 mar  2 08:16 stat
-r--r--r-- 1 root root 0 mar  2 08:16 swaps
-r--r--r-- 1 root root 0 mar  2 08:16 uptime

$ ls -l /var/lib/lxcfs/proc/diskstats 
-r--r--r-- 1 root root 0 mar  2 08:10 /var/lib/lxcfs/proc/diskstats
```

If I try to remove diskstats bind-mount it complains about another bind-mount:
```
$ sudo systemd-nspawn -b -D focal -M test-container --bind=/var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo --bind=/var/lib/lxcfs/proc/loadavg:/proc/loadavg --bind=/var/lib/lxcfs/proc/meminfo:/proc/meminfo --bind=/var/lib/lxcfs/proc/stat:/proc/stat --bind=/var/lib/lxcfs/proc/swaps:/proc/swaps --bind=/var/lib/lxcfs/proc/uptime:/proc/uptime
Spawning container test-container on /reserva/systemd-containers/focal.
Press ^] three times within 1s to kill container.
Failed to stat /var/lib/lxcfs/proc/loadavg: No such file or directory
Child died too early.
```

**Comment by poettering** [comment]
uh, i am not sure this is actionable for us. is lxcfs supposed to work for other container manager? i have no idea what it precisely does, and you kinda lost me at "fuse".

if you want this to work, for whatever this does, please work with the lxcfs community, i am pretty sure noone here is going to invest any time in this

**Comment by brunorf** [comment]
Thanks for the help.
Apparently it should work, as it's only a fuse filesystem based on cgroups which masks some real /proc pseudo-files (cpuinfo, diskstats, meminfo, stats, swaps  and uptime) with the purpose of container looks more like a VM. For example, uptime will record the creation time of container cgroup instead of host uptime.

If I bind-mount this pseudo-files in somewhere else it works. The problem is only happens when I try to mount on the required location. Moreover, if I mount, let's say, uptime on /uptime and check contents, it contains exactly what is supposed to.

Honestly I don't know if this is the right place for asking help (and for that, I apologize) , but apparently this has something to do with systemd-nspawn when I try to bind mount over container /proc pseudo-files

**Comment by poettering** [comment]
I am tempted to close this. I don't think anyone here will help you with this. if you want this to work you'd have to look into this yourself. We don't work on LXC, and the LXC people probably don't care about nspawn either. Hence I doubt anyone will do anything about this.

**Comment by mikhailnov** [comment]
+1 for this, I also wanted to use lxcfs with nspawn because nspawn itself cannot limit memory available to the container.

**Comment by poettering** [comment]
> +1 for this, I also wanted to use lxcfs with nspawn because nspawn itself cannot limit memory available to the container.

it can do that. use --property=MemoryMax=…

**Comment by poettering** [comment]
Let's close this, this is really not in focus for us, the kernel and nspawn should set /proc/ and /sys/ and cgroupfs up as needed, and if there's something to fix then we should do that in nspawn.
