### ISSUE TITLE
Flush LinkLocal IP when DHCP IP is assigned

### ISSUE THREAD

**Issue by lorenzo-arena** [systemd/systemd#19460]
**Is your feature request related to a problem? Please describe.**
When configuring an interface like:

```
[Match]
Name=br0

[Network]
BindCarrier=eth0
DHCP=yes
LinkLocalAddressing=yes
```

if the interface is brought up without a DHCP server online, it correctly gets a LinkLocal IP (i.e. 169.254.x.x). As soon as a DHCP server is online, it also gets an IP from the server, but it doesn't flush the old LinkLocal IP.

**Describe the solution you'd like**
I'd like systemd-networkd to release the old LinkLocalIP.

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 244 (244.5+)`

**Comment by yuwata** [comment]
Already implemented. See 8ccae2dd2d68f715d4c962ee4bab4827b4500540.
