### ISSUE TITLE
systemd-cryptsetup RFE: use security hardware as 2FA

### ISSUE THREAD

**Issue by michel-slm** [systemd/systemd#19473]
**Is your feature request related to a problem? Please describe.**
For laptops with a secure hardware token (e.g. Yubikey) permanently attached, unlocking LUKS2 volume with the token is potentially less safe than using a passphrase, as arguably both can be stolen / accessed without authorization.

**Describe the solution you'd like**
It would be great if the hardware token can be used as a second factor, in addition to still requiring the user's passphrase

**Describe alternatives you've considered**
N/A

**The systemd version you checked that didn't have the feature you are asking for**
v248

**Comment by poettering** [comment]
Configure a PIN on the device and we'll prompt you for it. What more do you need?

(PIN means any type of pw actually, even text based. security tokens just call it a PIn even though it isn't one)

**Comment by poettering** [comment]
Let's close this. I am not sure what else you need beyond the PIN on the security token, for 2FA.
