### ISSUE TITLE
"No swap partitions or files matching resume config were found in /proc/swaps."

### ISSUE THREAD

**Issue by DankRank** [systemd/systemd#19486]
**systemd version the issue has been seen with**
 > systemd 248 (248-5-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux ruby 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Hibernation

**Unexpected behaviour you saw**
 > `Failed to hibernate system via logind: Not enough swap space for hibernation`

**Steps to reproduce the problem**
 > 1) Setup a system with two swap partitions with different priorities
 > 2) The swap with lower priority has to come second in /proc/swaps
 > 3) Set `resume=` kernel parameter to the swap with lower priority.
 > 4) run `sudo systemctl hibernate`

**Additional program output to the terminal or log subsystem illustrating the issue**
All relevant info
```text
$ cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-linux root=UUID=4790f24a-690e-4e3c-baaf-c3baa7cbde77 rw quiet resume=UUID=b8cb26d5-809d-4a4c-95fd-f4b5e81752cc
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           974Mi        92Mi       391Mi       1.0Mi       490Mi       741Mi
Swap:          8.5Gi          0B       8.5Gi
$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
/dev/sdc2                               partition       524284          0               -2
/dev/sdc4                               partition       8388604         0               -3
$ lsblk -o +UUID | grep SWAP
├─sdc2   8:34   0   512M  0 part [SWAP]     d0a7688a-f252-43da-9c15-8b6a0b0e3216
└─sdc4   8:36   0     8G  0 part [SWAP]     b8cb26d5-809d-4a4c-95fd-f4b5e81752cc
$ cat /sys/power/resume
8:36
$ cat /sys/power/resume_offset
0
$ sudo systemctl hibernate
Failed to hibernate system via logind: Not enough swap space for hibernation
```
systemd-logind debug log:
```text
Apr 30 07:26:39 ruby systemd-logind[1090]: Got message type=method_call sender=:1.28 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=HibernateWithFlags cookie=3 reply_cookie=0 signature=t error-name=n/a error-message=n/a
Apr 30 07:26:39 ruby systemd-logind[1090]: Sleep mode "disk" is supported by the kernel.
Apr 30 07:26:39 ruby systemd-logind[1090]: Disk sleep mode "platform" is supported by the kernel.
Apr 30 07:26:39 ruby systemd-logind[1090]: /dev/sdc2: is a candidate device.
Apr 30 07:26:39 ruby systemd-logind[1090]: /dev/sdc4: ignoring device with lower priority
Apr 30 07:26:39 ruby systemd-logind[1090]: No swap partitions or files matching resume config were found in /proc/swaps.
Apr 30 07:26:39 ruby systemd-logind[1090]: Sent message type=error sender=n/a destination=:1.28 path=n/a interface=n/a member=n/a cookie=15 reply_cookie=3 signature=s error-name=org.freedesktop.login1.SleepVerbNotSupported error-message=Not enough swap space for hibernation
Apr 30 07:26:39 ruby systemd-logind[1090]: Failed to process message type=method_call sender=:1.28 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=HibernateWithFlags cookie=3 reply_cookie=0 signature=t error-name=n/a error-message=n/a: Not enough swap space for hibernation
```

## In-depth investigation
First of all, triggering hibernation manually with `echo disk | sudo tee /sys/power/state` works.
I tried to hibernate with `SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1` and got this
```text
Apr 30 17:55:48 ruby systemd-sleep[1545]: Failed to find location to hibernate to: Function not implemented
```
Regardless of whether the memory check is bypassed, the issue stems from the same place: `find_hibernate_location` in `src/shared/sleep-config.c`. 

The function is supposed to find the swap entry that's going to be used for hibernation. If `/sys/power/resume` is set, it looks for a matching swap entry and returns 1. Otherwise it finds the swap with highest priority (or largest amount of usable space, if priorities are equal) and returns 0, which tells systemd-sleep to write that swap to `/sys/power/resume`. The problem is that it kinda does both of these cases at the same time.

Here it discards sdc4, because the previously found sdc2 has higher priority
https://github.com/systemd/systemd/blob/88c2c8a0ba13de31061a22a352410c18ffacab9a/src/shared/sleep-config.c#L391-L401
This is the part which checks that an entry matches /sys/power/resume. It's never reached by sdc4.
https://github.com/systemd/systemd/blob/88c2c8a0ba13de31061a22a352410c18ffacab9a/src/shared/sleep-config.c#L421-L426
And here it errors out because it couldn't find the resume entry.
https://github.com/systemd/systemd/blob/88c2c8a0ba13de31061a22a352410c18ffacab9a/src/shared/sleep-config.c#L436-L439

So to fix this, I think it would suffice to put the priority check and the usable space check behind a `sys_resume == 0` condition.

P.S. yes, I'm aware that my swap setup is moronic.

**Comment by poettering** [comment]
Best way to get this addressed would be to provide a patch!
