### ISSUE TITLE
sysv-generator-test.py fails if run as root

### ISSUE THREAD

**Issue by dvdhrm** [systemd/systemd#195]
Currently, running the test-suite as root fails on `python2 ./test/sysv-generator-test.py`. If run as user it works fine.

As my python knowledge is pretty limited, I'd prefer if someone of the authors (@martinpitt ?) could have a look. Maybe a simple `if geteuid() == 0: return 72` is enough.

**Comment by martinpitt** [comment]
Confirmed. The reason is that running the tests as root will cause the generator's output to go into the journal instead of stdout/stderr, so the test gets an empty stderr.

**Comment by martinpitt** [comment]
Trivial fix, pushed directly: https://github.com/systemd/systemd/commit/6b7d32add4733a83f86e18bb86f914037a6688b7

**Comment by dvdhrm** [comment]
Much appreciated, thanks!
