### ISSUE TITLE
Question: howto set systemd.log_target, systemd.log_level when invoked via docker?

### ISSUE THREAD

**Issue by dothebart** [systemd/systemd#19504]
I'm trying to set up a docker image using systemd like documented here:

https://github.com/docker-library/docs/tree/master/centos#dockerfile-for-systemd-base-image

I have the issue that on some machines systemd will not create the dbus-unix-domain-socket for systemctl. I see this output on a broken machine:
```
Set hostname to <cf2f71b8125c>.
Initializing machine ID from random generator.
Couldn't move remaining userspace processes, ignoring: Input/output error
Failed to determine supported controllers: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```
I've searched the systemd source, and wasn't able to identify which files are broken here by these error messages, hence I'm hoping to see more when turning on debug logging?

The original issue is here:
https://github.com/docker-library/docs/issues/1936

**Comment by poettering** [comment]
Please ask the maintainers of "docker-library" for more information on Docker. This is really the wrong thing, we have no clue about docker.

We document our expectations on the container manager here:

https://systemd.io/CONTAINER_INTERFACE/

**Comment by dothebart** [comment]
but whats `systemd.log_target` from the point of systemd? https://fedoraproject.org/wiki/How_to_debug_Systemd_problems ? is it an environment variable? which way is it passed in? the CONTAINER_INTERFACE page doesn't list anything for this. 

Could the error message be improved? Like containing the actual filename?

**Comment by poettering** [comment]
It's a kernel cmdline parameter. If you run things in a container (whcih systemd detects via the $container env var on PID 1) then it will use argv[] of PID 1 instead.

That crappy docs you linked don't suggest setting $container at all, it appears the people who wrote that didn't bother to consult the documentation we explicitly provide for this.

Please start with our docs I linked, it states explicitly that $container should be set. My educated guess is that a good part of the mess already goes away then. My recommendaiton would be: read the rest too and adjust the image accordingly.

It would all be so easy of Docker would just set that env var out of the box, like everyone else does, but they live in this fantasy world where they believe they can still set the rules and don't need to make themselves recognizable.
