### ISSUE TITLE
Help: "cpuset" Python utility no longer words with recent systemd version

### ISSUE THREAD

**Issue by Hubro** [systemd/systemd#19518]
The only way I can find to shield CPU cores for realtime applications is the Python utility "cpuset". Since a recent systemd update, that utility no longer works. Any action results in the same error:

```
~ 
➜ sudo cset shield --reset
mount: /cpusets: none already mounted on /sys/fs/bpf.
cset: **> mount of cpuset filesystem failed, do you have permission?
```

This broke for me when updating from `systemd 247.4-2` to `systemd 248-5`.

See the related bug report here: https://github.com/lpechacek/cpuset/issues/40

If the cpuset Python utility can no longer be used for shielding CPU cores, how can it be done? I have tried an failed to find any documentation on doing this with systemd.

---

(By "shielding CPU cores" I mean moving all other processes away from those cores and only allowing a certain process to run on them. In my case it's a high performance virtual machine. Without shielding the relevant cores, I experience stutters and performance issues.)

**Comment by behrmann** [comment]
That's not a systemd specific problem. Arch has switched their default hierarchy from [hybrid](https://github.com/archlinux/svntogit-packages/blob/8a4be64d166704be7db6a0cddba6e3aee93a51c8/repos/core-x86_64/PKGBUILD#L134) to [unified](https://github.com/archlinux/svntogit-packages/blob/packages/systemd/trunk/PKGBUILD#L126). 

If you need a quick fix, I think booting with `systemd.unified_cgroup_hierarchy=0` should do it, but even Debian has switched their default hierarchy to cgroups v2 for Bullseye. cgrous v1 is flawed and at some point no users of it will remain. 

For a long-term fix, not knowing what it is you're running, have a look at `man systemd.resource-control`, specifically at `AllowedCPUs=`

**Comment by keszybz** [comment]
https://github.com/lpechacek/cpuset/issues/40 seems more appropriate to track this.
