### ISSUE TITLE
Show status if a unit fails to reload successfully

### ISSUE THREAD

**Issue by mikehearn** [systemd/systemd#19522]
I usually use a command like this to reload e.g. web servers:

`systemctl reload nginx || systemctl status nginx`

That's because if the server fails to reload due to a config error of some sort, the reload command won't tell me what the issue is. That's a pity. It'd be better if `systemd reload` automatically showed the log lines emitted by the unit if reload fails, to save a bit of typing.

**Comment by poettering** [comment]
Pretty much a duplicate of #1287 (which so far covers only start + stop, but if we add that we'd add it for reload too of course)
