### ISSUE TITLE
DynamicUser creates users with no home directory in the nss db?

### ISSUE THREAD

**Issue by mikehearn** [systemd/systemd#19537]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.6)

I admit this is one version outside the "two major last versions" policy, unfortunately I'm not sure how to get a system with the very latest systemd without building my own distro. Is there a VM or docker image I can use to test against a recent build of systemd?

**Used distribution**
 > Ubuntu 20.04

**Linux kernel version used** (`uname -a`)
 > `5.4.0-72-generic`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > nss db should have a home dir for dynamic users = StateDirectory

**Unexpected behaviour you saw**
 > it's actually set to /

**Steps to reproduce the problem**
 > Install Java then run `systemd-run -p DynamicUser=1 -p StateDirectory=xyz -p Environment=HOME=/var/lib/xyz -p WorkingDirectory=/var/lib/xyz -t /usr/bin/java -XshowSettings:properties --version | grep user.home`

This Java system property is calculated here using getpwuid:

https://github.com/openjdk/jdk/blob/bebfae48e3f1643f2456d680d170dcc22f7231bf/src/java.base/unix/native/libjava/java_props_md.c#L482

Because Java apps use this instead of $HOME, it means trying to sandbox Java servers that want to store data to their home directory will fail when they try to write to / instead.

**Comment by poettering** [comment]
and where should that home dir point to? we have none, hence we set the root fs, as we have to specify something.

the concept of a "home directory" for system users is a bit weird, no?

isn't this something to fix in java? i.e. at the very least make it honour $HOME like everything else?

**Comment by mikehearn** [comment]
The state directory seems as good a choice as any. It's semantically the "home" in the sense that it's persistent and where a server is meant to store its primary data files. 

Is there some specific guidance somewhere that getpwuid isn't meant to be used and $HOME is canonical? I guess it could be treated as a Java bug, but I wouldn't want to assert that getpwuid shouldn't be used unless the man pages actually said so. I don't see any mention of that field being deprecated, so there doesn't seem to be a strong case for calling this a Java bug.

**Comment by poettering** [comment]
Well, there's https://man7.org/linux/man-pages/man7/environ.7.html.

On UNIX nothing of this is of course standardized. Everyone does what they think makes sense. It usually is a good idea to look at what GLib does however. And that's this:

https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-home-dir

Qt does the same:

https://doc.qt.io/qt-6/qstandardpaths.html

systemd does the same too.

In bash if you use "~" you get put into $HOME as well. Typing "cd" without argument gets you there too. 

Hence I figure this is a de-facto standard, which is as good as it usually gets on Linux. It's really universal. It's irritating that java doesn't do that.

I don't think there's the need to deprecate the field. I am just saying that for *system* users (as opposed to regular users) it doesn't make too much sense to have one. And it's weird for Java that today probably is more often called outside of regular user context and much more inside of a system user context they require it to be set. And it's even weirder that they hard rely on it, and don't even bother with $HOME.

So, my suggestion: file a bug/PR against java, asking them to honour $HOME like everyone else, and only fallback to the getpwuid() thing if $HOME isn't set.

**Comment by mikehearn** [comment]
BTW the relevant OpenJDK bug already exists for a decade:

https://bugs.openjdk.java.net/browse/JDK-7069190

It died with a comment from some engineer who seems to have been over-thinking this somewhat and scared of security issues, then I guess it got triaged into low priority and never re-visited. Unfortunately the OpenJDK bug tracker is not open. The best I can do is file a deliberate dupe via their "webbug group" and hope it kicks someone into action, but that won't do anything for all the old JVMs out there, which will still be ignoring HOME.

**Comment by poettering** [comment]
POSIX defines $HOME btw:

https://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap08.html

**Comment by mikehearn** [comment]
Right - I agree with you actually, I just think that fixing Java _and_ systemd is the best outcome here. Even if Java is fixed soon (and I might take a crack at a patch just to get familiar with their patch submission process), modern Javas are unfortunately not so backwards compatible anymore meaning many apps will be stuck on 8 or 11 for many years even as the OS is upgraded around them. They have an easy workaround, but ultimately some fraction of people who try to combine Java with DynamicUser will end up on a pilgrimage to this issue to discover why it doesn't work. That's a pity, and an avoidable one. There are already too many things in computers that break due to obscure semantic disagreements buried in some bug tracker somewhere.

**Comment by martin-vitek** [comment]
The same problem is with ssh - it is searching `.ssh/` in home directory using `getpwuid`.

We are using [JupyterHub](https://jupyter.org/). It is a web application where user authenticates by OAuth2, and based on that, a dynamic user is created for him. This is working very well, and it is very convenient. The user can run python scripts, persistently store data, but he cannot simply use ssh for access to git repository.

**Comment by behrmann** [comment]
As said in jupyterhub/systemdspawner#92, I'm not sold that `DynamicUser=` is the right hammer for that particular nail. I also agree with @poettering that `HOME` should be honoured, which is what most parties do, and that the whole thing is not very well-defined and that there is not really an obvious choice of what it should be (looking at various `/etc/passwd` entries).

That being said I think the SSH example has merit, since having some service run with `DynamicUser=` being able to to receive SSH connections is something that can reasonably be expected. Also, SSH can't really grab into the environment of some running service to extract the `HOME` (well, it *could*, but that's not really a reasonable thing to do) and while this might very well be something that OpenSSH should fix, setting *some* directory as home in NSS (other than `/`) might make sense in systemd as well.

Looking at different passwd entries, I agree that one could point at either state directory, runtime directory or configuration directory as possible values. I guess state directory would be least surprising for most users, but I any of the three can be argued convincingly. Maybe a new setting `DynamicUserHome=` with settings `root` (the default and current behaviour), `statedirectory`, `configurationdirectory` and `runtimedirectory` could be added to address this.

**Comment by domenkozar** [comment]
Is there way to tell nss-systemd to respond with a specific home directory when using DynamicUser=1?

Software like OpenSSH has an issue opened for 12 years and it doesn't look like it will get fixed.

**Comment by AndrewKvalheim** [comment]
Also ran into this after expecting to be able to run OpenSSH client as a DynamicUser. I was able to work around it with e.g.:

```bash
ssh -o IdentityFile="$HOME/.ssh/id_ed25519" \
    -o UserKnownHostsFile="$HOME/.ssh/known_hosts"
```

but a `DynamicUserHome=` would be more helpful.

**Comment by mikehearn** [comment]
BTW, Java was fixed in v19 to use $HOME when NSS returns null or a single character result.

**Comment by poettering** [comment]
OK, so if Java addressed this, then I guess we can close this here.
