### ISSUE TITLE
[networkd] enabling IPForward makes networkd ignore DHCPv6 lease

### ISSUE THREAD

**Issue by Iced-Sun** [systemd/systemd#1954]
With

```
[Network]
DHCP=yes
```

networkd can get both IPv6 and IPv6 DHCP address. However, once IPForward is enabled (through `IPForword=yes/ipv6/ipv4`, or `IPForword=kernel` with `/proc/sys/net/ipv4/ip_forward==1`), networkd will just ignore DHCPv6 leases.

Thanks.

**Comment by Iced-Sun** [comment]
OK, it seems I need set `accept_ra` to 2 if I want both forwarding and DHCPv6.

`IPv6AcceptRouterAdvertisements` won't do that for me, right?

**Comment by teg** [comment]
Some of this logic recently changed. Are you using the most recent release? IPv6AcceptRouterAdvertisements=yes should do the trick.

**Comment by Iced-Sun** [comment]
I'm currently using v227. I'll try v228.

**Comment by Iced-Sun** [comment]
`IPv6AcceptRouterAdvertisements=yes` in systemd 228 solves the problem. Thanks.
