### ISSUE TITLE
timedatectl set-timezone set the wrong time zone if Etc is used.

### ISSUE THREAD

**Issue by guadl** [systemd/systemd#19557]
**systemd version the issue has been seen with**
 > 237, 245, 247

**Used distribution**
 > Ubuntu 18.04, Manjaro 

**Linux kernel version used** (`uname -a`)

 > 5.4.0-72-generic, 5.10.34-1

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > If i set timezone with 'timedatectl set-timezone Etc/GMT+5' it results in 'Local time: Mo 2021-05-10 04:01:54 -05'. At each time zone the sign is reversed.

**Steps to reproduce the problem**
 > 'timedatectl set-timezone Etc/GMT+5'
View 'timedatectl' and see the Local time or Time zone

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
Sorry, but this not a systemd issue. It's reproducible without it easily:

```
TZ=':Etc/GMT+5' date 
```

See:

https://en.wikipedia.org/wiki/Tz_database#Area
