### ISSUE TITLE
user@.service TasksMax

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1955]
Right now it defaults to `TasksMax=512`. Since it is within an user slice (which has `TasksMax=4096`), shouldn't it have `TasksMax=infinity`?

**Comment by ohsix** [comment]
do you have any information on what distros set RLIMIT_NPROC to? i don't think it was unlimited, but it was probably high

(i don't, sorry)

**Comment by heftig** [comment]
Arch has it at 63575, which seems like a default value.

**Comment by poettering** [comment]
I was wondering about that, too, I must admit. I figure we should reset the setting for user systemd services to infinity indeed. WOuld be delighted to take a patch for this.

**Comment by cdauth** [comment]
As discovered in [Arch Linux bug 47787](https://bugs.archlinux.org/task/47787#comment143204), this issue is also affecting programs started from the terminal when running Gnome, as the terminal is started as a sub-process of dbus and is thus part of `user@.service`.
