### ISSUE TITLE
TEST-10-ISSUE-2467 is flaky

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#19563]
Version: 248.1

I've updated the Debian packaging to v248.2 and noticed that the "upstream" autopkgtest does not pass reliably.
I have two tests which are flaky and fail randomly: TEST-10-ISSUE-2467 and TEST-29-PORTABLE (see #19564).

TEST-10-ISSUE-2467 fails about 1 out of 3.
In 248.1-1 I switched to the upstream runner, which afair now runs more tests under nspawn instead of qemu, to speed things up. This might be a contribution factor, as I didn't see those failure with the old, Debian based upstream runner.

See https://salsa.debian.org/systemd-team/systemd/-/commit/de959cc3eaba39805699dc9384d5f499e8dddb10 and https://salsa.debian.org/systemd-team/systemd/-/commits/debian/experimental/

A full log is attached, an excerpt follows:
```
Container root has been shut down.
Spawning getter /bin/journalctl -o export -D /var/tmp/systemd-test.Wa03WM/root/var/log/journal/e12d2c5797c64db4a4379f1ab5a1f1c9...
Finishing after writing 1510 entries
---- /var/tmp/systemd-test.Wa03WM/root/var/log/journal/e12d2c5797c64db4a4379f1ab5a1f1c9 ----
-- Journal begins at Mon 2021-05-10 13:09:04 UTC, ends at Mon 2021-05-10 13:09:04 UTC. --
[  447.280528] systemd[1]: test10.socket: Trigger limit hit, refusing further activation.
[  447.280596] systemd[1]: test10.socket: Failed with result 'trigger-limit-hit'.
[  447.282712] systemd[1]: testsuite-10.service: Failed with result 'exit-code'.
[  447.282968] systemd[1]: Failed to start TEST-10-ISSUE-2467.
[  447.383860] systemd[1]: systemd-update-utmp-runlevel.service: Main process exited, code=killed, status=15/TERM
[  447.383946] systemd[1]: systemd-update-utmp-runlevel.service: Failed with result 'signal'.
-rw-r----- 1 root root 8388608 May 10 13:09 /tmp/autopkgtest.7EwKBD/upstream-artifacts/TEST-10-ISSUE-2467.journal
nspawn-root test failed
make: *** [Makefile:2: run] Error 1
+ make -C TEST-11-ISSUE-3166 setup run
```
[log.txt](https://github.com/systemd/systemd/files/6452494/log.txt)

**Comment by mbiebl** [comment]
I ran the test a 1000 times, it failed in 189 of them. The system I was running it on was not under any particular load.

**Comment by mbiebl** [comment]
Should we disable the test until a proper solution is found?

**Comment by bluca** [comment]
it's been working fine upstream though, can't remember seeing that failing recently

**Comment by mbiebl** [comment]
Well, not if you disable tracing, which I think we shouldn't apply as a bandaid to make this test work.
At least here (in Debian) for a regular build without tracing enabled, this test fails (reliably).

**Comment by bluca** [comment]
Yeah now I remember, something very weird is going on with socat that nobody can explain - let's use the existing ticket which has all the info please, to avoid duplicating everything
