### ISSUE TITLE
Failed to fully start up daemon: Permission denied, Failed with result 'protocol'.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#19565]
**systemd version the issue has been seen with**
 > systemd-239-41.el8_3.2.x86_64

**Used distribution**
 > CentOS Linux release 8.3.2011

**Linux kernel version used** (`uname -a`)
 > `Linux server 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > cron jobs should work

**Unexpected behaviour you saw**
 > some cron jobs fail, while others work. Those that work produce various errors, pasted at the bottom of this issue.

**Steps to reproduce the problem**
 > I am not sure how to reproduce this issue. I have 10 CentOS servers, 5 of them exhibit this issue for no apparent reason, all 10 servers are identical (run CentOS 8.3 and have been setup with the same Ansible playbook, they all run the same matomo PHP script as a cron job). All servers have SELinux enabled in enforcing mode, but there are no AVC errors.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Apr 23 21:05:01 server.tld systemd[201370]: pam_unix(systemd-user:session): session opened for user myuser by (uid=0)
Apr 23 21:05:01 server.tld systemd[201370]: Failed to fully start up daemon: Permission denied
Apr 23 21:05:01 server.tld systemd[201372]: pam_unix(systemd-user:session): session closed for user myuser
Apr 23 21:05:01 server.tld systemd[1]: user@1000.service: Failed with result 'protocol'.
Apr 23 21:05:01 server.tld systemd[1]: Failed to start User Manager for UID 1000.
Apr 23 21:05:01 server.tld crond[201367]: pam_systemd(crond:session): Failed to create session: Start job for unit user@1000.service failed with 'failed'
Apr 23 21:05:01 server.tld CROND[201379]: (myuser) CMD (/usr/bin/php -f /home/myuser/public_html/matomo/console core:archive --url=https://www.myuser.tld/matomo/ > /dev/null)
Apr 23 21:05:01 server.tld systemd[903]: run-user-1000.mount: Succeeded.
```

Thank you.

**Comment by Bill-ColeUS** [comment]
Redhat has no idea, they suggested to ask here.

So thanks for nothing, great support!

:roll_eyes:

**Comment by vcaputo** [comment]
> So thanks for nothing, great support!

Please accept this 1000% refund.
