### ISSUE TITLE
RFE: make systemd.directives html pages jump to the anchor in the target

### ISSUE THREAD

**Issue by ohsix** [systemd/systemd#1956]
currently when you click on a link from http://www.freedesktop.org/software/systemd/man/systemd.directives.html

say, the first one, Accept=, it currently goes to http://www.freedesktop.org/software/systemd/man/systemd.socket.html

it would be useful if it went to http://www.freedesktop.org/software/systemd/man/systemd.socket.html#Accept=

(i don't know dockbook nor if that is easy)

**Comment by poettering** [comment]
@keszybz  is our XML guru! Any idea if we can get that done?

**Comment by keszybz** [comment]
I'm pretty sure that nobody really understands that stuff :)

But in this case it seems fairly easy to get 90% of the problem done. Maybe @cmacq2 has some better idea.
