### ISSUE TITLE
TEST-29-PORTABLE is flaky

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#19564]
Version: 248.1

I've updated the Debian packaging to v248.2 and noticed that the "upstream" autopkgtest does not pass reliably.
I have two tests which are flaky and fail randomly: TEST-10-ISSUE-2467 (see #19563) and TEST-29-PORTABLE. 

TEST-29-PORTABLE fails about 1 out of 5.
In 248.1-1 I switched to the upstream runner, which afair now runs more tests under nspawn instead of qemu, to speed things up. This might be a contribution factor, as I didn't see those failure with the old, Debian based upstream runner.

A full log is attached, an excerpt follows:
```
[   59.201795] reboot: Power down
Spawning getter /bin/journalctl -o export -D /var/tmp/systemd-test.bOTOCF/root/var/log/journal/c435290885d24823ba68d29e517634f0...
Finishing after writing 4902 entries
---- /var/tmp/systemd-test.bOTOCF/root/var/log/journal/c435290885d24823ba68d29e517634f0 ----
-- Journal begins at Mon 2021-05-10 11:35:58 UTC, ends at Mon 2021-05-10 11:36:36 UTC. --
[    1.856402] kernel: acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[   10.823616] kernel: blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[   13.480131] kernel: ext4 filesystem being mounted at /root supports timestamps until 2038 (0x7fffffff)
[   14.776919] systemd[1]: Failed to find module 'autofs4'
[   28.436389] kernel: blk_update_request: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[   47.990040] systemd[236]: device-mapper: create ioctl on 978711fc108a67d3a47a702058073a4cf4eb195341440efc8861cb32c47cee1a-verity CRYPT-VERITY-fee1de6663094bb083a09b38bc1a8146-978711fc108a67d3a47a702058073a4cf4eb195341440efc8861cb32c47cee1a-verity failed: Device or resource busy
[   48.122700] systemd[236]: Failed to wait for device to be initialized: Connection timed out
[   48.519987] kernel: device-mapper: ioctl: remove_all left 1 open device(s)
[   48.653464] kernel: /dev/mapper/978711fc108a67d3a47a702058073a4cf4eb195341440efc8861cb32c47cee1a-verity: Can't open blockdev
[   49.666165] systemd[237]: Device 978711fc108a67d3a47a702058073a4cf4eb195341440efc8861cb32c47cee1a-verity is not active.
[   49.705351] systemd[237]: app0.service: Failed to set up mount namespacing: No such file or directory
[   49.706522] systemd[237]: app0.service: Failed at step NAMESPACE spawning cat: No such file or directory
[   49.822483] systemd[1]: app0.service: Failed with result 'exit-code'.
[   49.839056] systemd[1]: Failed to start app0.service.
[   50.152609] portablectl[207]: Job for app0.service failed because the control process exited with error code.
[   50.160342] portablectl[207]: See "systemctl status app0.service" and "journalctl -xeu app0.service" for details.
[   53.918637] systemd[1]: testsuite-29.service: Failed with result 'exit-code'.
[   53.951266] systemd[1]: Failed to start TEST-29-PORTABLE.
[   57.751326] systemd[1]: systemd-portabled.service: Failed with result 'exit-code'.
-rw-r----- 1 root root 16777216 May 10 11:36 /tmp/autopkgtest.Znbfmk/upstream-artifacts/TEST-29-PORTABLE.journal
QEMU test failed
make: *** [Makefile:2: run] Error 1
make: Leaving directory '/tmp/autopkgtest.Znbfmk/build.YNt/src/test/TEST-29-PORTABLE'
--x-- Result of TEST-29-PORTABLE: 2 --x--
```

[log.txt](https://github.com/systemd/systemd/files/6452519/log.txt)

**Comment by bluca** [comment]
I'm pretty sure this is a duplicate of https://github.com/systemd/systemd/issues/17469 - the issue is the same, uevents are unreliable on loaded systems

**Comment by bluca** [comment]
> In 248.1-1 I switched to the upstream runner, which afair now runs more tests under nspawn instead of qemu, to speed things up. This might be a contribution factor, as I didn't see those failure with the old, Debian based upstream runner.

This test does not run under nspawn, as it needs loopdev and more

**Comment by mbiebl** [comment]
It's nested qemu though.

**Comment by bluca** [comment]
yeah nested qemu is slow enough to make this issue appear quite often, unfortunately. There's a patch series proposed for the kernel that would fix it:

https://lore.kernel.org/linux-block/20210315200242.67355-1-mcroce@linux.microsoft.com/T/#m67c8c7f25e6a5cc9b5c1b343697218a46c65de83

There have also been several attempts to mitigate it on our side, so far unsuccessfully, unfortunately.

**Comment by mbiebl** [comment]
> > In 248.1-1 I switched to the upstream runner, which afair now runs more tests under nspawn instead of qemu, to speed things up. This might be a contribution factor, as I didn't see those failure with the old, Debian based upstream runner.
> 
> This test does not run under nspawn, as it needs loopdev and more

Right, thanks. The above comment was misleading anyway, as TEST-29-PORTABLE appears to be new in v248.
Sorry for the confusion.

**Comment by mbiebl** [comment]
Ok, thanks for the pointers. While I haven't run into failures of TEST-50-DISSECT myself, it indeed looks like a duplicate issue.
So closing this one accordingly.
