### ISSUE TITLE
networkctl reload + networkctl reconfigure doesn't always pick up changes to overrides

### ISSUE THREAD

**Issue by wak-google** [systemd/systemd#19576]
**systemd version the issue has been seen with**
 > 247.4

**Used distribution**
 > openembedded

**Linux kernel version used** (`uname -a`)

 > 5.10.35

**CPU architecture issue was seen on**
 > arm

**Expected behaviour you didn't see**
 > New addresses don't get configured on the interfaces after changing a drop-in file in `/run/systemd/network`, running `networkctl reload` and `networkctl reconfigure <intf>`. I added a single valid Address=<addr> to the [Network] section of the file. If I restart systemd-networkd entirely the change gets applied as expected.

**Unexpected behaviour you saw**
 > If I add an invalid address along with my valid address, `networkctl reload` + `networkctl reconfigure <intf>` works to pick up the valid address.

**Comment by wak-google** [comment]
I was wrong about the invalid address part, it looks like adding an invalid address or changing the file doesn't do anything interesting. It's worth noting that the parser is definitely running over the file after `networkctl reload` as the error messages for invalid configuration options do change appropriately.

**Comment by wak-google** [comment]
@yuwata

**Comment by yuwata** [comment]
This should be already fixed by da46a1bc3cd28ac36114002c216196dae004b05c (v248). Closing.
If the issue still exists in v248 or newer, please request to reopen this page.
