### ISSUE TITLE
sshd

### ISSUE THREAD

**Issue by jackiesparks** [systemd/systemd#19587]
Well when it recieves exit code or the -t faiks upon cert finding and loading it doesnt stop the daemon and issue a dmesg log.

**systemd version the issue has been seen with**
 > …

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by yuwata** [comment]
Please fill information in the form, and provides any relevant logs. Otherwise, there is nothing we can do.
