### ISSUE TITLE
Failed to build systemd.directives.xml

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#19601]
You can see the following failure in packit, e.g. https://copr-be.cloud.fedoraproject.org/results/packit/systemd-systemd-19592/fedora-rawhide-i386/02184619-systemd/builder-live.log.gz
```
[2045/2048] /builddir/build/BUILD/systemd-248/tools/make-directive-index.py man/systemd.directives.xml ../man/directives-template.xml (...snip)
FAILED: man/systemd.directives.xml
(snip)
Traceback (most recent call last):
  File "/builddir/build/BUILD/systemd-248/tools/make-directive-index.py", line 194, in <module>
    main(*sys.argv[1:])
  File "/builddir/build/BUILD/systemd-248/tools/make-directive-index.py", line 190, in main
    xml = make_page(template_path, xml_files)
  File "/builddir/build/BUILD/systemd-248/tools/make-directive-index.py", line 186, in make_page
    return _make_page(template, directive_groups, formatting)
  File "/builddir/build/BUILD/systemd-248/tools/make-directive-index.py", line 162, in _make_page
    _make_section(template, name, directives, formatting)
  File "/builddir/build/BUILD/systemd-248/tools/make-directive-index.py", line 122, in _make_section
    display = tree.fromstring(formatting[varname])
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 27
ninja: build stopped: subcommand failed.
```
Not sure, but I guess this is introduced by #19589. cc @keszybz.

**Comment by asavah** [comment]
I've stumbled into this issue yesterday too.
It happens with libxml2 (lxml uses it) 2.9.12 , with 2.9.10 everything is ok.
I've checked several times by swapping libxml2.so.2 symlink destination in a controlled prefix.

With https://github.com/systemd/systemd/pull/19589 reverted building with any of 2.9.10 or 2.9.12 present everything is ok.
I haven't had time to find the root cause so I didn't report it.
My current theory is that there are some subtle differences which make regexes in https://github.com/systemd/systemd/blob/main/tools/make-directive-index.py#L15 fail.

**Comment by keszybz** [comment]
It fails on i386, but not on amd64, fairly consistently. Looks like it might be some bug in libxml2.

**Comment by asavah** [comment]
It fails on amd64 for me.

**Comment by yuwata** [comment]
@asavah could you provide the build log?

**Comment by asavah** [comment]
@yuwata Will do in around a hour, I already have some extra info I got why trying to debug this yesterday but it's on a machine that's currently off and far way, will reproduce and provide the logs.

**Comment by keszybz** [comment]
```python
from lxml import etree as tree

def xml_print(xml):
    return tree.tostring(xml, pretty_print=True, encoding='utf-8')

page = 'man/systemd.socket.xml'
t = tree.parse(page)

name = t.find('.//variablelist/varlistentry/term/varname')
print(f'TEXT: {name.text}')
print(f'NAME: {xml_print(name)[:200]}')
```

This is my reproducer. It prints
```
TEXT: ListenStream=
NAME: b'<varname>ListenStream=</varname>\n'
```
or
```
TEXT: ListenStream=
NAME: b'<varname>ListenStream=</varname></term>\n        <term><varname>ListenDatagram=</varname></term>\n        <term><varname>ListenSequentialPacket=</varname></term>\n        <listitem><para>Specifies an add'
```

The `\n` in the first variant is expected: it's the tail element that contains trailing whitespace after an element. But the output in the second variant seems wrong.

**Comment by asavah** [comment]
@yuwata 

Full configure/build log https://pastebin.com/uuk1GUUu

Quick and dirty patch for  make-directive-index.py to provide some info:
```
diff --git a/tools/make-directive-index.py b/tools/make-directive-index.py
index 6aaad6700c..223f35b373 100755
--- a/tools/make-directive-index.py
+++ b/tools/make-directive-index.py
@@ -119,6 +119,13 @@ def _make_section(template, name, directives, formatting):
     for varname, manpages in sorted(directives.items()):
         entry = tree.SubElement(varlist, 'varlistentry')
         term = tree.SubElement(entry, 'term')
+
+        print('--------------------------------------------------------------------')
+        print(varname)
+        print()
+        print(formatting[varname])
+        print('--------------------------------------------------------------------')
+
         display = tree.fromstring(formatting[varname])
         term.append(display)
 
```

For simplicity tried manually building directives with just one xml like so:
`asavah@kross-1910:~/kross/tmp/asusb450eg/systemd$ /home/asavah/kross/src/systemd/tools/make-directive-index.py man/systemd.directives.xml ../../../src/systemd/man/directives-template.xml ../../../src/systemd/man/sd-event.xml`

Output: https://pastebin.com/VhpHWvCa

Resymlinked libxml to 2.9.10:
```
asavah@kross-1910:~/kross/host/lib$ ln -sf libxml2.so.2.9.10 libxml2.so.2
asavah@kross-1910:~/kross/host/lib$ ln -sf libxml2.so.2.9.10 libxml2.so
```

Another try but with 2.9.10 which succeds: https://pastebin.com/MWxqU6TS

As you can see in my quick and dirty debug there is something very wrong with xml parsing,
with 2.9.10 the script does the righh thing:
```
CLOCK_BOOTIME

b'<constant xmlns:xi="http://www.w3.org/2001/XInclude">CLOCK_BOOTIME</constant>\n'
```

While with 2.9.12 it dumps the whole chunk:
```
CLOCK_BOOTIME

b'<constant xmlns:xi="http://www.w3.org/2001/XInclude">CLOCK_BOOTIME</constant><constant>CLOCK_REALTIME_ALARM</constant><constant>CLOCK_BOOTTIME_ALARM</constant>
<lots of stuff snipped>
```

At this point I'm not sure whether it's libxml2 bug/breaking change or something else.

**Comment by keszybz** [comment]
OK, so it seems that we're getting consistent results. libxml2-2.9.12 was emitted in Fedora as a security update. Hopefully this will get resolved quickly, but we probably need some workaround until that happens.
