### ISSUE TITLE
RFE: credentials loaded with LoadCredential should be available to ExecStartPre too

### ISSUE THREAD

**Issue by happysalada** [systemd/systemd#19604]
This is just asking precision around the LoadCredential doc.

I couldn't understand how to actually use the feature.

The way i understood it was:
In order to pass an environment variable SECRET_KEY_BASE to a service
- add a `LoadCredential=secret_key_base:/run/secrets/unionBlue.secret_key_base`. 
- then add an environment variable `SECRET_KEY_BASE=$CREDENTIALS_DIRECTORY/secret_key_base`;
I made sure that the `/run/secrets/unionBlue.secret_key_base` file (just a text file) is owned by the same user running the service.
However upon starting the service I run into the following errors
```
72670]: union-blue.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/credentials/union-blue.service: No such file or directory
72670]: union-blue.service: Failed at step NAMESPACE spawning /nix/store/sxpb7vbxx1kwprnhsvr2cn7l0vssl9r2-union-0.0.1/bin/union: No such file or directory
```

I'm not sure what I missed.
I'm happy to test any suggestions and propose an amendment to the documentation.

**Comment by happysalada** [comment]
Thanks a lot for helping with this!

SECRET_KEY_BASE is a literal secret.

To give you a little more context. I would like to manage everything with git. So for secrets I use something like age that does encryption with ssh keys. The idea being that when I deploy something will decrypt the file at a special location owned by root. That decrypted location is `/run/secrets/unionBlue.secret_key_base`. At that location, I have a decrypted file containing a string of characters that corresponds to the secret.

That said, I'm open to using this in a different way. Ideally though I can pass files to LoadCredentials. However in the end, my service needs some environment variables to be literal secrets. There are several of those. Currently I'm using EnvironmentFile (using the encryption/decryption process I'm talking about in the previous step).

Let me know if you need any more information.

**Comment by mjlbach** [comment]
I'm also running into this issue trying to share a file (not a literal secret).

```
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/home (rw-implicit) is duplicate.
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/root (rw-implicit) is duplicate.
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/run/user (rw-implicit) is duplicate.
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/home (read-only) is made redundant by /run/systemd/unit-root/ (read-only)
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/root (read-only) is made redundant by /run/systemd/unit-root/ (read-only)
May 15 12:17:47 nixos-desktop systemd[3320593]: /run/systemd/unit-root/run/user (read-only) is made redundant by /run/systemd/unit-root/ (read-only)
May 15 12:17:47 nixos-desktop systemd[3320593]: Bind-mounting / on /run/systemd/unit-root (MS_BIND|MS_REC "")...
May 15 12:17:47 nixos-desktop systemd[3320593]: Applying namespace mount on /run/systemd/unit-root/
May 15 12:17:47 nixos-desktop systemd[3320593]: Applying namespace mount on /run/systemd/unit-root/dev
May 15 12:17:47 nixos-desktop systemd[3320593]: Applying namespace mount on /run/systemd/unit-root/proc
May 15 12:17:47 nixos-desktop systemd[3320593]: Applying namespace mount on /run/systemd/unit-root/run/credentials
May 15 12:17:47 nixos-desktop systemd[3320593]: Mounting tmpfs (tmpfs) on /run/systemd/unit-root/run/credentials (MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_STRICTATIME "mode=0755,size=4m,nr_inodes=1k")...
May 15 12:17:47 nixos-desktop systemd[3320593]: Applying namespace mount on /run/systemd/unit-root/run/credentials/dendrite.service
May 15 12:17:47 nixos-desktop systemd[3320593]: Failed to follow symlinks on /run/credentials/dendrite.service: No such file or directory
May 15 12:17:47 nixos-desktop systemd[3320593]: dendrite.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/credentials/dendrite.service: No such file or directory
May 15 12:17:47 nixos-desktop systemd[3320593]: dendrite.service: Failed at step NAMESPACE spawning /nix/store/dyikz835agazxvxm9fj7xqlsz0k34iwj-coreutils-8.32/bin/cp: No such file or directory
May 15 12:17:47 nixos-desktop systemd[1]: dendrite.service: Child 3320593 belongs to dendrite.service.
```

The exact service config I'm using is:

```
[Unit]
After=network.target
Description=Dendrite Matrix homeserver

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/7dz31dq4n1r0wqq3r28r7975cql68n8w-glibc-locales-2.32-40/lib/locale/locale-archive"
Environment="PATH=/nix/store/dyikz835agazxvxm9fj7xqlsz0k34iwj-coreutils-8.32/bin:/nix/store/2nx0mmb4k7z9i5ii4fw9jxwm9afh5wyl-findutils-4.7.0/bin:/nix/store/fxy5ficr8paan2yxrh45d9j17ryy2z2y-gnugrep-3.6/bin:/nix/store/9fbkl74hnskvmlkbx2cyy88q04nx12vp-gnused-4.8/bin:/nix/store/bmvjq883zj2vxgynl8p47za39lrg0ypi-systemd-247.6/bin:/nix/store/dyikz835agazxvxm9fj7xqlsz0k34iwj-coreutils-8.32/sbin:/nix/store/2nx0mmb4k7z9i5ii4fw9jxwm9afh5wyl-findutils-4.7.0/sbin:/nix/store/fxy5ficr8paan2yxrh45d9j17ryy2z2y-gnugrep-3.6/sbin:/nix/store/9fbkl74hnskvmlkbx2cyy88q04nx12vp-gnused-4.8/sbin:/nix/store/bmvjq883zj2vxgynl8p47za39lrg0ypi-systemd-247.6/sbin"
Environment="TZDIR=/nix/store/qqlfpa7hsgvpaj1nmg2d6qlxdh8s2vsv-tzdata-2020f/share/zoneinfo"



DynamicUser=true
ExecReload=/nix/store/dyikz835agazxvxm9fj7xqlsz0k34iwj-coreutils-8.32/bin/kill -HUP $MAINPID
ExecStart=/nix/store/ydh46v17fipa1q9s0my9w8dfdx35sh2x-matrix-dendrite-0.3.11/bin/dendrite-monolith-server --config $CREDENTIALS_DIRECTORY/dendrite.yaml --http-bind-address :8008
ExecStartPre=/nix/store/dyikz835agazxvxm9fj7xqlsz0k34iwj-coreutils-8.32/bin/cp /nix/store/njqqj4nygg4nq70g7pfa5l7zi9nxqyhs-dendrite.yaml /run/dendrite/dendrite.yaml

LoadCredential=matrix_key.pem:/home/mjlbach/matrix_key.pem
Restart=on-failure
RuntimeDirectory=dendrite
RuntimeDirectoryMode=0700
StateDirectory=dendrite
Type=simple
WorkingDirectory=/var/lib/dendrite
```

Sorry for the nix stuff, but that is also my usecase.

**Comment by poettering** [comment]
> SECRET_KEY_BASE is a literal secret.

the credentials logic doesn't support passing secrets down via env vars, because that's not a safe thing since env vars are by default inherited down the tree, even when there are privilege transitions.

@happysalada can you please provide the most minimal unit that shows your issue? 

if you run 'systemd-run -p LoadCredential=foo:/etc/shadow -t /bin/bash' on the cmdline, and then type `cat $CREDENTIALS_PATH/foo` in the shell that opens then, does that work?

If you run this on 248, does it work then?

**Comment by happysalada** [comment]
Here are the results
```
echo $CREDENTIALS_PATH


[root@hetzner-AX41-UEFI-ZFS-NVME:/]# cat $CREDENTIALS_PATH/foo
cat: /foo: No such file or directory
```

the CREDENTIAL_PATHS env var appears to be not set.
but the service says it's running
```
Running as unit: run-u921297.service
Press ^] three times within 1s to disconnect TTY.
```

248 should come out on NixOS in a few days, I can test again then.

**Comment by poettering** [comment]
> When using LoadCredential. Does it mean that the service will have access to the $CREDENTIALS_PATH and it should try to read files from that path?

Yes. Isn't the documentation explicit enough about this, it even provides example command lines? https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LoadCredential=ID:PATH

If the aforementioned cmdline doesn't work, then I am puzzled. Might be something weird with what nixos does with the paths?

Can you reproduce the issue on a more regular distro?

Can you ping the nixos people about this?

**Comment by dotlambda** [comment]
> If the aforementioned cmdline doesn't work, then I am puzzled.

It does work if you use `$CREDENTIALS_DIRECTORY`:
```
# systemd-run -p LoadCredential=foo:/etc/shadow -t $(which bash)
Running as unit: run-u139.service
Press ^] three times within 1s to disconnect TTY.

# cat $CREDENTIALS_DIRECTORY/foo
nixbld4:!:1::::::
messagebus:!:1::::::
systemd-network:!:1::::::
nixbld7:!:1::::::
nixbld9:!:1::::::
nobody:!:1::::::
nixbld1:!:1::::::
...
```

**Comment by poettering** [comment]
oops, sorry, i meant DIRECTORY of course, not PATH. Sorry for the confusion.

**Comment by poettering** [comment]
So is all cleared up now? or any questions left? can we close this?

**Comment by dotlambda** [comment]
Sadly, the issue is still there. I was able to boil it down to the following unit file:
```
[Unit]

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/77iwp66553657gnsmbx66y4gbpsmvpih-glibc-locales-2.32-46/lib/locale/>
Environment="PATH=/nix/store/0vkw1m51q34dr64z5i87dy99an4hfmyg-coreutils-8.32/bin:/nix/store/j1pkn9109012w>
Environment="TZDIR=/nix/store/bjxkrk1pd65z5gz5y62jyqdsjkicvvck-tzdata-2020f/share/zoneinfo"



DynamicUser=true
ExecStart=/nix/store/0vkw1m51q34dr64z5i87dy99an4hfmyg-coreutils-8.32/bin/cat ${CREDENTIALS_DIRECTORY}/foo
ExecStartPre=/nix/store/0vkw1m51q34dr64z5i87dy99an4hfmyg-coreutils-8.32/bin/ls
LoadCredential=foo:/etc/shadow
RuntimeDirectory=test
```
In particular, it doesn't occur if I remove `DynamicUser`, `RuntimeDirectoryMode`, or `ExecStartPre`.
Btw, the Nix stuff shouldn't matter, just replace `/nix/store/*` with `/usr/bin`.

<details>
<summary>Using [nixos-shell](https://github.com/Mic92/nixos-shell), you can try the following `vm.nix`</summary>

```
{ pkgs, ... }:

{
  nixos-shell.mounts = {
    mountHome = false;
    mountNixProfile = false;
  };

  systemd.services.test = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      DynamicUser = true;
      RuntimeDirectory = "test";
      LoadCredential = "foo:/etc/shadow";
      ExecStartPre = "${pkgs.coreutils}/bin/ls";
      ExecStart = "${pkgs.coreutils}/bin/cat \${CREDENTIALS_DIRECTORY}/foo";
    };
  };
}
```
</details>

**Comment by arianvp** [comment]
The same issue reproduces on Ubuntu 21.04  (Systemd 247):

```
[Service]
DynamicUser=true
ExecStart=/usr/bin/cat ${CREDENTIALS_DIRECTORY}/foo
ExecStartPre=/usr/bin/ls
LoadCredential=foo:/etc/passwd
RuntimeDirectory=test
```

```
May 26 21:25:38 vultr.guest systemd[1]: Starting test.service...
░░ Subject: A start job for unit test.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit test.service has begun execution.
░░ 
░░ The job identifier is 1364.
May 26 21:25:38 vultr.guest systemd[2360]: test.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/credentials/test.service: No such file or directory
May 26 21:25:38 vultr.guest systemd[2360]: test.service: Failed at step NAMESPACE spawning /usr/bin/ls: No such file or directory
░░ Subject: Process /usr/bin/ls could not be executed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The process /usr/bin/ls could not be executed and failed.
░░ 
░░ The error number returned by this process is ERRNO.
May 26 21:25:38 vultr.guest systemd[1]: test.service: Control process exited, code=exited, status=226/NAMESPACE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit test.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 226.
May 26 21:25:38 vultr.guest systemd[1]: test.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit test.service has entered the 'failed' state with result 'exit-code'.
May 26 21:25:38 vultr.guest systemd[1]: Failed to start test.service.
░░ Subject: A start job for unit test.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit test.service has finished with a failure.
```

**Comment by dotlambda** [comment]
I can't reproduce on Arch Linux using systemd 248. I hope to be able to confirm that 248 also fixes it on NixOS soon.

**Comment by happysalada** [comment]
> > When using LoadCredential. Does it mean that the service will have access to the $CREDENTIALS_PATH and it should try to read files from that path?
> 
> Yes. Isn't the documentation explicit enough about this, it even provides example command lines? https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LoadCredential=ID:PATH
> 
> If the aforementioned cmdline doesn't work, then I am puzzled. Might be something weird with what nixos does with the paths?
> 
> Can you reproduce the issue on a more regular distro?
> 
> Can you ping the nixos people about this?

I guess if I can suggest an improvement to the documentation. It would be to cover a couple of typical use cases. For example, passing a certfile, should be fairly straightforward.
However how would it work to pass a database user password for example. Should the consuming application have a flag that can read a file rather than just read an environment variable? Should you have the credential file just be like an EnvironmentFile with Key=Value then sourced from inside the consuming app?

**Comment by happysalada** [comment]
Would the recommended way to use it be like
`env DB_PASSWORD=$(<"$CREDENTIALS_DIRECTORY/db_password") my_webservice_start_script`
and then adding something like
`LoadCredentials=db_password:/run/secrets/my_secret_file`

passing the secret to credentials then back as an environment variable feels a little weird, is that the right way ?

**Comment by boucman** [comment]
well. env variables are not safe... anybody can read them from /proc IIUC
so if you have to save your password in an env variable there is no point in keeping it secret and you could just use Environment= no ?

(or to put it differently: yes. if you want to pass a password to an application, the application needs to read it from a file. Most other common ways are not safe)

**Comment by poettering** [comment]
> well. env variables are not safe... anybody can read them from /proc IIUC

It's not that bad, you need privs or be same user to do so. But they still suck, since they are agressively inherited down the process tree and once inherited no further access restrictions are made. It's a shitty way to pass secret data.

But yeah, we are not going to support passing creds via env vars, it's just a terrible way. If you need it you can easily glue it in however: wrap your program in a shell script that does:

```
#!/bin/sh

read -r FOOBAR < "$CREDENTIALS_DIRECTORY/foobar"

exec /path/to/real/program
```

But again, I'd really advise that programs are fixed to allow taking secrets via regular files though.

**Comment by happysalada** [comment]
Thank you both for the explanation, anything secret needs to be passed via a file! And that file will be passed as a credentials.
Everything is clear and makes sense!

**Comment by happysalada** [comment]
Actually one more question.
What are the recommendations for the credential original files, in terms of ownerhip, rights, and location?

If I understand correctly, the recommendation for running a systemd service is to do it with DynamicUser when possible, if not then do it with a SystemUser. There should be one user per service that need to be run.

Should the owner of that original credential file be the one who runs the service? If yes, then the file can be read just like env vars can be accessed? Perhaps the location of the file is another factor that makes it harder.
Regarding this, what is the recommended location for those original credential file?

When I say original, I mean the location that you pass to load credential.

**Comment by flokli** [comment]
@happysalada The original files can just be chmod `0600` (or `0400` even) and owned by `root:root` - the passed file in `$CREDENTIALS_DIRECTORY` will be readable by whatever `User` the unit runs as:

Original file:
```shell
root@tp:~|⇒  ls -la /run/secrets                    
total 4
drwx------  2 root root  60 Jun 10 14:14 .
drwxr-xr-x 31 root root 820 Jun 10 14:13 ..
-rw-------  1 root root   4 Jun 10 14:14 foo
```

Passed credential:
```shell
root@tp:~|⇒  systemd-run -p Type=oneshot -p DynamicUser=yes -p User=test -p LoadCredential=foo:/run/secrets/foo -t /bin/sh
Running as unit: run-u720.service
Press ^] three times within 1s to disconnect TTY.
sh-4.4$ /run/current-system/sw/bin/id
uid=63378(test) gid=63378(test) groups=63378(test)
sh-4.4$ /run/current-system/sw/bin/ls -la $CREDENTIALS_DIRECTORY
total 4
dr-x------ 2 test root  0 Jun 10 15:04 .
drwxr-xr-x 3 root root 60 Jun 10 15:04 ..
-r-------- 1 test root  4 Jun 10 15:04 foo
sh-4.4$ exit

**Comment by flokli** [comment]
I think the main confusion here is that it's not possible to use `$CREDENTIALS_DIRECTORY` from the unit file itself (in an `Environment=…` line, or `ExecStartPre` line).

It works fine if used inside the process specified via `ExecStart[Pre]`. This means wrapper scripts such as https://github.com/systemd/systemd/issues/19604#issuecomment-852964641 needs to be used, if services can't read secret files from a path that's to be assembled at runtime with an environment variable.

**Comment by dotlambda** [comment]
> it's not possible to use `$CREDENTIALS_DIRECTORY` from the unit file itself (in an `Environment=…` line, or `ExecStartPre` line).

That's simply untrue:
```
# systemd-run -p LoadCredential=foo:/etc/shadow -t /run/current-system/sw/bin/cat '${CREDENTIALS_DIRECTORY}/foo'
Running as unit: run-u35.service
Press ^] three times within 1s to disconnect TTY.
lightdm:!:1::::::
nixbld11:!:1::::::
nixbld6:!:1::::::
nixbld7:!:1::::::
...
```

**Comment by flokli** [comment]
Ah, I finally figured out what's the problem:

Reproducer:
```
systemd-run -p LoadCredential=foo:/etc/shadow -p DynamicUser=yes -p RuntimeDirectory=test -p ExecStartPre='/run/current-system/sw/bin/id' -t /run/current-system/sw/bin/cat '${CREDENTIALS_DIRECTORY}/foo'
Running as unit: run-u819.service
Press ^] three times within 1s to disconnect TTY.
(immediately goes back to prompt)
```

log:
```Jun 10 17:24:34 tp systemd[1]: Starting /run/current-system/sw/bin/cat ${CREDENTIALS_DIRECTORY}/foo...
Jun 10 17:24:34 tp systemd[266593]: run-u819.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/credentials/run-u819.service: No such file or directory
Jun 10 17:24:34 tp systemd[266593]: run-u819.service: Failed at step NAMESPACE spawning /run/current-system/sw/bin/id: No such file or directory
Jun 10 17:24:34 tp systemd[1]: run-u819.service: Control process exited, code=exited, status=226/NAMESPACE
Jun 10 17:24:34 tp systemd[1]: run-u819.service: Failed with result 'exit-code'.
Jun 10 17:24:34 tp systemd[1]: Failed to start /run/current-system/sw/bin/cat ${CREDENTIALS_DIRECTORY}/foo.
```

As soon as I don't set the `ExecStartPre=` line, the service succeeds running and dumps my `/etc/shadow`.

But having a `ExecStartPre`, and `LoadCredential` property messes things up.

**Comment by dotlambda** [comment]
@flokli ... and that's exactly what I said in https://github.com/systemd/systemd/issues/19604#issuecomment-849053534.

**Comment by poettering** [comment]
So what is this issue about now? Just a request for more docs? Or is there an actual bug to fix here?

**Comment by happysalada** [comment]
Thank you for coming back on this.
NixOS hasn't made the transition to 248 yet, so this can't be tested fully.
I would suggest some improvements to the documentation, but the first step is to make sure how it works.
You can close this issue for now if you feel more comfortable, and it can be re-opened when we have managed to test further and gathered more info.

**Comment by ju1m** [comment]
Hi there,
Couple of remarks I have after struggling to use `LoadCredential=` in `NixOS`:
1. I assumed that `LoadCredential=` would also be available to `ExecStartPre=` but it is apparently not the case, and in fact the [current doc](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Credentials) does only say: `a credential may be read from within a ExecStart= command line`. If that is indeed the expected behavior it would be great to stress it the documentation. However IMHO **accessing credentials is also useful in `ExecStartPre=`** to configure services unable to read credentials from standalone files. Eg. `sourcehut` services can only read their credentials inlined in their `config.ini` file. Hence an `ExecStartPre=` has to substitute paths in that file with their content, and it would be great if that `ExecStartPre=` were able to get those files from `LoadCredential=`, instead of resorting to a `+` prefix and `RootDirectoryStartOnly=true`.
2. Minor gotcha, **`$CREDENTIALS_DIRECTORY` must indeed actually be used with `${}`** (as in `${CREDENTIALS_DIRECTORY}/mycred` from the doc example) when part of a word, since contrary to `bash`, a `/` is not a separator for variable names. This behavior is [specified here](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines).
3. I did not expect `NixOS` to lag that much behind `systemd`, [NixOS/master is still at v247.6](https://github.com/NixOS/nixpkgs/blob/62ca1cc769207f3d64baad30cf73eacdddbfc4be/pkgs/os-specific/linux/systemd/default.nix#L116) whereas upstream `systemd` is at `v249` since July, to the point that **the fix from January for https://github.com/systemd/systemd/issues/18116 is still not included in latest downstream**, leading at least @dotlambda, @flokli and I rediscovering it independently, respectively in May, June and August. I don't know why it happened, but very surprising for me, it unfortunately took me some time to realise that it was not me misconfiguring `systemd` or misusing `LoadCredential=`, but that my `systemd` was not actually fixed.
4. Not a big deal but being able to use the slash (`/`) character in `LoadCredential=`'s `ID` would smooth the configuration of passing credentials from `password-store`.

Thanks for working on `systemd` and this issue amongst others :)

**Comment by happysalada** [comment]
Nixos unstable channel now has systemd 249.4 !

I made the same mistake thinking that the credential would be available in ExecStartPre. I solved it by supplying a script to the exec start. Just to give a bit more context on this issue. A lot of packaged software (all that I have seen so far) do not support reading secrets from files. So what we do in nixos is try to patchup the configuration in the ExecStartPre phase, so that secrets are not in environment variables.

I used the $CREDENTIALS_DIRECTORY in a bash script on exec start, so I did not run into the problem you mentioned above with `/` not acting as a separator. For me patching a configuration file required a script.

I think this issue can be closed. If other people have time, would be happy to have confirmation.

**Comment by flokli** [comment]
As @ju1m mentioned, if credentials not being available in `ExecStartPre=` is intended, the docs should probably make this more clear. Or if it's not intended (as them being available in `ExecStartPre=` is very useful too), this should be turned into a feature request.

**Comment by tv42** [comment]
Since it really wasn't clear until I read through this issue:

If you see error

`Failed to set up mount namespacing: /run/systemd/unit-root/run/credentials/NAMEOFUNIT.service: No such file or directory`

and are

- running systemd v247 or so (e.g. in Debian 11 bullseye)
- your unit file has all of `DynamicUser=yes`, `LoadCredential=`, and `ExecStartPre=`

That means you've hit the previously mentioned https://github.com/systemd/systemd/issues/18116 & https://github.com/systemd/systemd/pull/18308 bug, and there is no fix provided/backported for it.

Guess I won't be using DynamicUser yet, then.

**Comment by tv42** [comment]
I ran into another case where I could really have used credentials in `ExecStartPre`. And the fact that nothing says that *isn't* possible confused me again.

**Comment by happysalada** [comment]
Just curious what your case was ?
inside ExecStart you can use a script with loadcredentials there. So you can do what you need to do before starting inside the script.

**Comment by tv42** [comment]
> Just curious what your case was ?

I have a service that changes its userid and I tried to chown the secrets to be readable by the final userid, without resorting to shell script kludges.

**Comment by kwohlfahrt** [comment]
> I ran into another case where I could really have used credentials in ExecStartPre. And the fact that nothing says that isn't possible confused me again.

+1, I had this issue as well. Specifically, I have a script that converts configuration from a custom format into the format that is expected by the service. As part of this conversion, it effectively `#include`s credentials into the final config, and having `LoadCredentials` available would let me use `DynamicUser = true` for this service.

> inside ExecStart you can use a script with loadcredentials there

Sure, but by that logic we don't need `ExecStartPre` at all ;). Since this configuration-munging script doesn't start the service, it a) makes semantic sense to be in a pre-start section, and b) `ExecStop` scripts don't need to run.

FWIW, the following patch lets my service run successfully, _but I don't know what the security model of `LoadCredentials` is, so there could be serious vulnerabilities_.

```
diff --git a/src/core/service.c b/src/core/service.c
index 49579f7998..7587e0046f 100644
--- a/src/core/service.c
+++ b/src/core/service.c
@@ -2222,7 +2222,7 @@ static void service_enter_start_pre(Service *s) {
                 r = service_spawn(s,
                                   s->control_command,
                                   s->timeout_start_usec,
-                                  EXEC_APPLY_SANDBOXING|EXEC_APPLY_CHROOT|EXEC_IS_CONTROL|EXEC_APPLY_TTY_STDIN,
+                                  EXEC_APPLY_SANDBOXING|EXEC_APPLY_CHROOT|EXEC_IS_CONTROL|EXEC_APPLY_TTY_STDIN|EXEC_WRITE_CREDENTIALS,
                                   &s->control_pid);
                 if (r < 0)
                         goto fail;

```

**Comment by flokli** [comment]
I still think not having those credentials available in `ExecStartPre` is a bug / incomplete implementation. There's a lot of valid reasons for having credentials available in `ExecStartPre` (to assemble config files containing these secrets for example), and I don't see why it should (only) behave the way it does now.

@poettering, WDYT?

**Comment by bjornfor** [comment]
@poettering: Any chance we can get your comment on whether `credentials loaded with LoadCredential should be available to ExecStartPre too`?

(I spent an evening pulling my hair out not understanding why it didn't work to read the credential in `ExecStartPre`... I'm happy I found this issue :-) )

**Comment by flokli** [comment]
https://github.com/systemd/systemd/pull/24734 now adds support use `LoadCredentials` from `ExecStartPre=`.
