### ISSUE TITLE
New sgx group seems overly generic and prone to collision

### ISSUE THREAD

**Issue by guillemj** [systemd/systemd#19610]
The new `sgx` group introduced in #18944 seems overly generic an prone to collisions with actual non-system user/group names (say out of initials). Could this be renamed to use the common pattern that prefixes system user/group names with «_» to «_sgx» so properly namespace it?

**Comment by keszybz** [comment]
We discussed this a few times… Some systems (in particular Debian) have the convention to use `_` for system users and groups, but it's not widely supported by other distros. For better or worse, "common" groups use non-namespaced names and this is the pattern we're following here. Perhaps more importantly, this patch in systemd replaces existing code in other projects, which already recommended and widely used the `sgx` name. We want to allow seamless upgrades on systems that were already set up with those existing conventions so changing the name would be problematic.

**Comment by guillemj** [comment]
The difference with most other user and groups names defined by systemd is that they are fairly scoped, having user/groups named like `audio`, `video`, `input`, seem pretty safe namespace-wise. `lp` is a bit problematic, but that's a historical name anyway, `kvm` is unfortunate but that ship has already sailed, but given that `sgx` is a new name it could start using a new and safer convention instead of making the problem worse. Of course the compat issues with existing systems using that name seem problematic, but stomping on that global namespace for the foreseeable future seems worse to me.

But I suppose this is not going to be changed anyway, which seems rather meh. :/

**Comment by poettering** [comment]
@guillemj did you run into the collision IRL? or is this mostly a theoretic concern?

I mean, it does suck on UNIX that there's no namespacing whatsoever for user and group names. It's hard to introduce it now, after the horse already left the barn. 

To me "sgx" sounded cryptic enough to make it not an obvious name clash candidate, but of course, it's there's always a risk involved...

**Comment by guillemj** [comment]
At an early stage aren't all namespacing issues theoretical, until they are too late? :)

Barring any lack of native namespacing support, the convention of «_»-prefix is the best we have right now, and not starting to use it even for newly introduced names seems like a disservice. Also the BSDs have all (AFAICS) switched most of their user/groups (to a greater or lesser extent) to use such convention, even though their global management might make this easier, but still with good coordination that could be accomplished too on */Linux I think. But we can already start someplace.

**Comment by keszybz** [comment]
Yeah, but this is not a "newly introduced name". We're just incorporating an already existing name. So yeah, let's do that the next time when we have a chance.

**Comment by poettering** [comment]
the underscore thing is that documented for any distro as suggeted naming policy? a quick google didn't reveal anything to me in that area. i.e. politically it's probably easier to convince people of something already established somewhere then to be the ones who introduce the concept?

**Comment by rbalint** [comment]
It is not emphasized and mentions usernames only, but I think in spirit it covers group names as well: https://www.debian.org/doc/debian-policy/ch-opersys.html#introduction
The preliminary discussion of this policy change: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949390 .
I share the concerns about new names conflicting with local names existing on systems and using `_` prefix for new ones in systemd would be very welcome. Also I'd like to suggest using vendor-independent new names, like `_enclave` in case other vendors roll their own variants.

**Comment by poettering** [comment]
@rbalint there was a discussion about using a generic group name for both AMD SEV and intel sgx, but the apis are simply too different conceptually and philosophically to subsume them under one group.
