### ISSUE TITLE
IPv6LinkLocalAddressGenerationMode=stable-privacy needs a stable_secret set by sysctl

### ISSUE THREAD

**Issue by ei-ke** [systemd/systemd#19622]
**systemd version the issue has been seen with**
 248

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)

 `Linux silence 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 x64

**Expected behaviour you didn't see**
<s> I set up stable-privacy via sysctl and made a permanent sysctl.d configuration and expected it to be honored also after a reboot. The network inteface is configured for systemd-networkd but had not included the `IPv6LinkLocalAddressGenerationMode=` parameter so it should have fallen back to the kernel settings.</s> _Edit: Obsolete, see 2nd comment._
Vice versa I expected `IPv6LinkLocalAddressGenerationMode=stable-privacy` to work on it's own, but it seems to need the `stable_secret` one can set via sysctl.

**Unexpected behaviour you saw**
<s>Seems to be overwritten by systemd after a reboot and the interface was back to a normal EUI-64 address.</s> _Edit: Obsolete, see 2nd comment._ Further after setting the interface configuration to `IPv6LinkLocalAddressGenerationMode=stable-privacy` and removing the settings I did via sysctl it is not generating a stable-privacy address after a reboot.

**Steps to reproduce the problem**
<s>Generate a `stable_secret` and save it to a sysctl.d configuration and set `addr_gen_mode` to 2:
```
sysctl net.ipv6.conf.eno1.addr_gen_mode=3
sysctl net.ipv6.conf.eno1.stable_secret
```
Outputs e.g. `9676:70db:3cc3:fd9f:27e2:90db:ea4e:0ee9`
Configuration for sysctl.d:
```
# Enable IPv6 stable-privacy mode for eno1
net.ipv6.conf.eno1.stable_secret = 9676:70db:3cc3:fd9f:27e2:90db:ea4e:0ee9
net.ipv6.conf.eno1.addr_gen_mode = 2
```
Reboot -> No stable-privacy address
Remove the configuration from above,</s> _Edit: Obsolete, see 2nd comment._ add `IPv6LinkLocalAddressGenerationMode=stable-privacy` to the interface configuration and reboot -> No stable-privacy address
Set a `stable_secret` and set the link down and up:
```
sysctl net.ipv6.conf.eno1.stable_secret=9676:70db:3cc3:fd9f:27e2:90db:ea4e:0ee9
ip link set eno1 down
ip link set eno1 up
```
-> There is your stable-privacy address

The fact that the `stable_secret` needs to be set might just be an documentation issue, but ignoring the kernel defaults seems like a bug.
This bug is related to #15465.

**Comment by ei-ke** [comment]
**systemd version the issue has been seen with**
 247






**Used distribution**
Ubuntu Server 21.04
**Linux kernel version used** (`uname -a`)

 `Linux syss-test 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 x64 (virtualized)

I tried to reproduce what happened on my Arch Linux system on a fresh Ubuntu system but could not reproduce that the permanent settings done via sysctl are overwritten by systemd after a reboot.
What I could reproduce is that `IPv6LinkLocalAddressGenerationMode=stable-privacy` needs to have a `stable_secret` set via sysctl - otherwise no stable-privacy address is generated and used.

**Comment by poettering** [comment]
I guess we should make that configurable maybe, and by default if unspecified hash it out of the machine-id in combination with the iface name or so.

**Comment by ei-ke** [comment]
Sounds reasonable. Maybe it would be the best to `net.ipv6.conf.if_name.addr_gen_mode=3` for getting a secret. But I have nearly no programming knowledge and don't know if it's more complicated to rely on the kernels logic or writing your own one.
Thanks for considering making it configurable.
