### ISSUE TITLE
Option to restrict the access/activation times for a service/socket

### ISSUE THREAD

**Issue by rugk** [systemd/systemd#19620]
**Is your feature request related to a problem? Please describe.**
I have a service/socket that should only be reachable at a certain time.

What I want is to implement a basic access restriction by time. I.e. I want to limit the time a day the socket/service can be activated/reached from the outside, so it's only available at certain times a day, e.g.

**Describe the solution you'd like**
The `[Socket]` config could have an entry `AccessTimes=`, which makes sure the socket is only accessible at a certain time 

**Describe alternatives you've considered**

*Alternative software:*
To compare this, the little oldish tool `xinetdx`, which can do the same i.e. listen on a socket and start a process (server) on demand [has an option](https://www-uxsup.csx.cam.ac.uk/pub/doc/redhat/redhat8/rhl-rg-en-8.0/s1-tcpwrappers-xinetd.html) called `access_times`, which can be used to specify when a service should be available. 
But using this as another tool (/dependency) is not a thing I'd like. I'd aim for an integrated way into systemd.

I've asked [how to do this on Unix Stackexchange](https://unix.stackexchange.com/q/649704/146739), but nobody came up with an idea to do it in systemd, so I guess it's not implemented/really possible. (Feel free to answer there, if you know a clever way.)

The only other suggestion was adjusting firewall rules, but not all firewall clients support that (firewalld) or you have to resort to some 

**The systemd version you checked that didn't have the feature you are asking for**

Don't really know, but [from that man page](https://manpages.debian.org/experimental/systemd/systemd.socket.5.en.html) at least v248.2-1.

**Comment by boucman** [comment]
hmm, I don't think this should be wired into the Socket... it's more like a sort of "reverse timer" i.e a timer that would stop the unit if it's running.

I'm not sure exactly how the syntax would be but I really like how systemd separates "triggering the unit" from the "how the unit works" in different units. I think it's good to keep that.


You could do this with a timer that starts the unit at the start of the period and a second timer (+a simple service) that would stop your unit. You could also use RuntimeMaxSec to limit the duration until systemd stops your unit (but the unit might end up in the failed state in that case)

Anyway, those are all workarounds. it would be nice to have timers that could do something else than start their target (stop, restart, reload)

**Comment by poettering** [comment]
This sounds awfully specific to me? Why not have two timers that start/stop the socket unit at the right times? unlike xinetd we give you control about the time when a socket shell be connnectible. i.e. a socket is listening when you issue "systemctl start foobar.socket" and stops listening once you issue "systemctl stop foobar.socket". Thus if you schedule these two commands via timer units you should have all you need?

**Comment by poettering** [comment]
Let's close this. I don't think we need any specific new concept for sockets here, timer unit should totally suffice.
