### ISSUE TITLE
`ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#19625]
On an Asus F2A85-M PRO running Debian sid/unstable with systemd 247 (247.3-5), systemd-udevd logs the messages below.

```
$ journalctl -o short-precise -u systemd-udevd.service -b
-- Journal begins at Mon 2021-05-10 15:48:05 CEST, ends at Sun 2021-05-16 11:39:40 CEST. --
May 16 11:39:03.094695 kodi systemd[1]: Started Rule-based Manager for Device Events and Files.
May 16 11:39:03.608824 kodi systemd-udevd[181]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 16 11:39:04.016808 kodi systemd-udevd[182]: Using default interface naming scheme 'v247'.
May 16 11:39:04.034608 kodi systemd-udevd[182]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 16 11:39:04.176704 kodi systemd-udevd[151]: Using default interface naming scheme 'v247'.
May 16 11:39:04.180926 kodi systemd-udevd[151]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
```

Is this a Linux kernel driver problem?

Edit:

From the output [`journalctl -o short-precise -b`](https://github.com/systemd/systemd/files/6520249/journal-o-short-precise-b.txt), the first udev message appears before the Linux driver is loaded.

```
[…]
May 21 06:31:32.712612 kodi systemd-udevd[163]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
[…]
May 21 06:31:32.796376 kodi kernel: hub 10-0:1.0: USB hub found
May 21 06:31:32.796701 kodi kernel: r8169 0000:04:00.0 eth0: RTL8168f/8111f, 08:60:6e:74:7a:51, XID 480, IRQ 34
May 21 06:31:32.797079 kodi kernel: r8169 0000:04:00.0 eth0: jumbo features [frames: 9194 bytes, tx checksumming: ko]
```

**Comment by poettering** [comment]
Do you have any .link files in place that configure speed/duplex or so?

**Comment by paulmenzel** [comment]
No, it’s a default installation with only `/etc/systemd/network/50-default.network` created for the network device.

**Comment by yuwata** [comment]
Fix is waiting in #19681.

**Comment by paulmenzel** [comment]
(I updated my issue description.)

**Comment by paulmenzel** [comment]
@yuwata, thank you for looking into this. Reading the merge/pull request description and commit messages, I unfortunately do not understand the actual problem. Downgrading the log level sounds to me only hiding a general problem.

Why does systemd-udev do anything with autonegotiation, when no network device is set up yet? (If that is the actual problem.)

**Comment by yuwata** [comment]
@paulepanter Sorry, maybe the title of #19681 was misleading. The main commit to fix this issue is the 4th commit in the PR.

**Comment by yuwata** [comment]
> Why does systemd-udev do anything with autonegotiation, when no network device is set up yet? (If that is the actual problem.)

That is for `lo`. It can (and should?) be available before any other interfaces.

Hmm, maybe we should do nothing for `lo`.

**Comment by paulmenzel** [comment]
> > Why does systemd-udev do anything with autonegotiation, when no network device is set up yet? (If that is the actual problem.)
> 
> That is for `lo`. It can (and should?) be available before any other interfaces.

Indeed. Thank you for the clarification.

> Hmm, maybe we should do nothing for `lo`.

I do not know much about it, but your suggestion sounds reasonable.

    $ sudo ethtool lo
    Settings for lo:
   	Link detected: yes
