### ISSUE TITLE
systemd-stable-248.3/src/libsystemd/sd-journal/lookup3.c:966: why write into array then not use it ?

### ISSUE THREAD

**Issue by dcb314** [systemd/systemd#19634]
systemd-stable-248.3/src/libsystemd/sd-journal/lookup3.c:966:40: style: Variable 'state[i]' is assigned a value that is never used. [unreadVariable]

Source code is

  for (i=0; i<HASHSTATE; ++i) state[i] = 1;
  printf("These should all be different\n");
  for (i=0, h=0; i<8; ++i)
  {
    h = hashlittle(buf, 0, h);
    printf("%2ld  0-byte strings, hash is  %.8x\n", i, h);
  }
}

**Comment by poettering** [comment]
We copy that file mostly 1:1 from http://www.burtleburtle.net/bob/c/lookup3.c, i.e. this is the Jenkins hash reference implementation.

The issue you found is in the test code though, which we don't make use of.

I doubt that the author of the jenkins hash still intends to update his upstream version, but the right approach would be to ping him. For us I doubt we need to do anything, as we don't use the test code and we are interested in copying the file as untouched is we can get away with.

**Comment by poettering** [comment]
See this for more details on this code:

https://en.wikipedia.org/wiki/Jenkins_hash_function
