### ISSUE TITLE
RFE: rlimit "fallback

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#19643]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by poettering** [comment]
Hmm?

**Comment by anitazha** [comment]
Somehow Chrome submitted before I was done. Correct issue at https://github.com/systemd/systemd/issues/19645
