### ISSUE TITLE
Resolve: retry dbus reads when one returns EINTR

### ISSUE THREAD

**Issue by mkaito** [systemd/systemd#1965]
Attached: strace of a call to `cabal update` [strace2.txt](https://github.com/systemd/systemd/files/39621/strace2.txt).

See the SIGVTALRM that aborts lookup.

**Comment by geekosaur** [comment]
Expanding a bit on this (I helped diagnose this issue):
The Haskell runtime uses a SIGVTALRM timer tick, defaulting to every 0.01s. In this case, it is interrupting the libnss_resolve dbus transaction, which is not being resumed after the resulting EINTR. The result is a hostname lookup failure, which goes away if the runtime's SIGVTALRM tick is disabled or if glibc's nss resolver module is used instead.

**Comment by poettering** [comment]
Humpf, that appears a very weird way to do things. I am pretty sure nss-resolve can't be the only thing that doesn't like when its operations are cancelled via EINTR and unexpected times...

**Comment by poettering** [comment]
(But anyway, this should definitely be fixed in nss-resolve, as nss modules really need to be prepared to run in any kind of process)

**Comment by geekosaur** [comment]
I helped someone else track down a similar problem a week before that; again it was dbus not wrapping its reads. I believe they forwarded upstream a list of syscalls they'd run into that needed to check for EINTR. It's actually a fairly common failing.

**Comment by gdamjan** [comment]
biboumi (a jabber <-> irc gateway) also fails with nss_resolve

**Comment by poettering** [comment]
So, I though about this for a while, an I am pretty sure our NSS lookup should actually exit if we get EINTR because the user pressed C-c and we got a SIGINT. Hence, I think the right approach here is to block the signals temporarily rather than restart the poll() syscall immediately unconditionally.

Now, the question is which signals to block, and which ones not to block. My guess is that we should only block a select few, where we know that processes use them for internal purposes. Specifically, I figure the following ones are the ones to block:

SIGALRM, SIGVTALRM, SIGPIPE, SIGCHLD, SIGTSTP, SIGIO, SIGHUP, SIGUSR1, SIGUSR2, SIGPROF, SIGURG, SIGWINCH

**Comment by poettering** [comment]
@gdamjan what precisely fails for that irc gateway? can you elaborate?

**Comment by poettering** [comment]
There's a fix now waiting in #2445.

**Comment by gdamjan** [comment]
@poettering strace and ltrace didn't help me (too little, or too much info) but it seems to be using c-ares. In strace I can see it opening /etc/hosts and then it logs 'resolution failed' nothing much inbetween. sorry couldn't help more. I'll check with your fixes later.

**Comment by poettering** [comment]
@gdamjan well, but c-ares is speaking DNS directly on the wire afaik. It does not involve NSS and hence nss-resolve at all....

**Comment by gdamjan** [comment]
@poettering I'm not sure how this works in biboumi/c-ares. maybe it checks for the string "dns" in nss_switch??? seems to be non-issue wrt nss-resolve, I'll take it upstream. 

Just for reference, if people stumble upon this issue after switching to nss-resolve exclusively:

```
hosts: files dns resolve mymachines myhostname # works
hosts: files resolve dns mymachines myhostname # works
hosts: files resolve mymachines myhostname # doesn't work
```

ps. I confirm that this branch fixes the cabal issue.

**Comment by gdamjan** [comment]
right https://github.com/c-ares/c-ares/blob/master/ares_init.c#L1288 :/

**Comment by gdamjan** [comment]
c-ares 1.11 now handles 'resolve' in nsswitch too

https://raw.githubusercontent.com/c-ares/c-ares/cares-1_11_0/RELEASE-NOTES
 o Use "resolve" as synonym of "dns" in nsswitch.conf
