### ISSUE TITLE
Allow searching the entire journal (across all _BOOT_ID's) when "-k" argument is given

### ISSUE THREAD

**Issue by mailinglists35** [systemd/systemd#19677]
**Is your feature request related to a problem? Please describe.**

I need to examine kernel logs from a specific date, but in order to do that, first I must find what _BOOT_ID contains that date. asking for a specific date that is earlier than current boot without explicitly adding the corresponding boot id shows no logs, but only the header `-- Logs begin at [...], end at [...]`

**Describe the solution you'd like**

`--boot` only allows picking one _BOOT_ID. it would very useful to me to allow to specify also boot id ranges or word "all", meaning to examine all _BOOT_ID's

**Describe alternatives you've considered**

the alternative is to first iterate all _BOOT_ID's then make calculations to find out what _BOOT_ID contains the requested date 

**The systemd version you checked that didn't have the feature you are asking for**

v248

**Comment by poettering** [comment]
I am sorry, I don't follow?

```
journalctl --since=… --until=…
```

is how you search by calendar time. Why do you care about the boot id for that?

**Comment by mailinglists35** [comment]
that is exactly how I searched, but it returns zero results until I actually fit in the correct boot id, unless the date I am searching is in the current boot id

**Comment by mrc0mmand** [comment]
Could you give an example? Because `--since/--until` seems to work as expected on my side without any boot id shenanigans

```
$ ~/repos/systemd/build/journalctl --version
systemd 248 (248-1083-gf144f6f)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

$ journalctl --no-hostname -b | head -n2
-- Logs begin at Tue 2019-10-01 17:07:12 CEST, end at Thu 2021-05-20 18:06:56 CEST. --
Apr 19 11:06:20 kernel: Linux version 5.11.14-200.fc33.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9), GNU ld version 2.35-18.fc33) #1 SMP Wed Apr 14 15:25:53 UTC 2021

$ journalctl --no-hostname --since "2020-11-06" | head -n2
-- Logs begin at Tue 2019-10-01 17:07:12 CEST, end at Thu 2021-05-20 18:06:56 CEST. --
Nov 06 00:00:39 pulseaudio[20243]: E: [alsa-source-USB Audio] module-echo-cancel.c: Doing resync

$ journalctl --no-hostname --since "2020-12-24 19:27:47" | head -n2
-- Logs begin at Tue 2019-10-01 17:07:12 CEST, end at Thu 2021-05-20 18:06:56 CEST. --
Dec 24 19:28:55 NetworkManager[1285]: <info>  [1608834535.4443] dhcp4 (enp34s0): option dhcp_lease_time      => '600'
```

**Comment by mailinglists35** [comment]
> If you're including `-k`/`--dmesg`, `journalctl` implicitly adds `-b`, maybe that's what's happening?
> 
> I'm not aware of anything else that would add a `_BOOT_ID` match behind the scenes when using `--since` and/or `--until`.
> 
> @mailinglists35 could you paste the `journalctl` command you're executing verbatim?

thank you! I did not realize that. yes I was using `-k` as I was searching for kernel messages

````
# journalctl --since 2021-05-15 --until 2021-05-17 -k
-- Logs begin at Fri 2020-09-18 09:15:03 EEST, end at Thu 2021-05-20 21:18:00 EEST. --
````
removing `-k` shows all messages

**Comment by medhefgo** [comment]
Note that `-k` is just a shorthand for a `_TRANSPORT=kernel` match. So you can use that with `--since` and `--until` to do what you want.

Though, I think it makes sense to forego implying `-b` if `--since` or `--until` is provided....

**Comment by vcaputo** [comment]
I'd support suppressing the implicit `-b` if combined with `--since` and/or `--until`.

**Comment by poettering** [comment]
Hmm, I'd consider "-k" a useful shortcut only, which combines a bunch of thing into one. if you don't want some of those things, don't use the shortcut, use the long form... `journalctl _TRANSPORT=kernel --since= … --until=…` should be all you need.

**Comment by poettering** [comment]
I'd consider this a documentaiton isue. i.e. maybe we should extend the documentation of the -k switch with a sentence like: "If you want to kernel logs from other boots than the current, use `journalctl _TRANSPORT=kernel`"

**Comment by medhefgo** [comment]
`-k` is originally just a dmesg replacement. And as such it makes sense for it to default to current boot. But there is nothing that fundamentally speaks against widening the search if explicitly asked to. Especially when doing so is the first thing that comes to mind and most natural thing to do. Forcing people to rtfm here seems excessive to me.

**Comment by poettering** [comment]
but --since= doesn't "widen" the search, it reduces it. not following?

**Comment by medhefgo** [comment]
Well, it would widen it if it removed the implied -b. I guess I failed to see how --since/--until could be used to reduce -k output, if, say, the current boot has been running for days.

Though, it could display a helpful message if -k and --since/--until has no messages to show that they probably wanted to use _TRANSPORT=kernel instead. And maybe it makes sense to have a boot-range option for -b in general too.

**Comment by medhefgo** [comment]
One could also argue that people consider -k to mean "show me kernel messages". The fact that it implies -b is just for convenience since it's the most likely think people want (when not giving any extra args). But you could certainly have it not added if --since/--until is given considering the most likely intention of someone using those is to observe much older logs. And in the unlikely scenario where -k + --since/--until would show logs not from current boot, they would surely immediately resort to adding -b themselves.

**Comment by mailinglists35** [comment]
man page says that `-k` "Show only kernel messages. This implies -b and adds the match "_TRANSPORT=kernel"."

it does not explicitly says it's a 1:1 dmesg equivalent, but notes that implies `-b`. 

when scripting I would probably be satisfied with `journalctl --since [...] --until [...] _TRANSPORT=kernel`, however on interactive command line I would never use _TRANSPORT because it implies unconfort to hold shift key to get the underscore (`<>?:"{}|` and are much easier to type, but underscore is farther and I must make unconfortable fionger effort to reach it while holding shift), even if further on after typing TR bash completion would take over (I'd have to keep holding shift to get the capitals T and R, which are even farther than minus/underscore key)

Practical alternative would be to use only date filtering then grep the output for " kernel:", but since I'm already into the habit of filtering the kernel messages by adding `-k`, it would make more sense and be more useful if along with `-k` I would be able to add `-b all`

**Comment by mrc0mmand** [comment]
> Practical alternative would be to use only date filtering then grep the output for " kernel:", but since I'm already into the habit of filtering the kernel messages by adding `-k`, it would make more sense and be more useful if along with `-k` I would be able to add `-b all`

Actually, journalctl understands `-b all`, so you can definitely do that (TIL):

```
$ journalctl -k --until 2020-09-09 
-- Logs begin at Tue 2019-10-01 17:07:12 CEST, end at Fri 2021-05-21 20:27:44 CEST. --
-- No entries --

$ journalctl -k --until 2020-09-09 -b all                                                                              
-- Logs begin at Tue 2019-10-01 17:07:12 CEST, end at Fri 2021-05-21 20:27:44 CEST. --                                                                                                                                                         
Oct 01 17:07:12 localhost.localdomain kernel: Linux version 5.3.1-300.fc31.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)) #1 SMP Tue Sep 24 21:00:05 UTC 2019
```

See: https://github.com/systemd/systemd/blob/05576809194754989f88f83c7104341c35944546/src/journal/journalctl.c#L275-L278

So I guess this makes #19692 somewhat redundant, maybe a man page note would be nice.

**Comment by mailinglists35** [comment]
apparently I was reading the manual page from a release older than v242, where `-b all` was implemented. sorry for trouble caused!
