### ISSUE TITLE
systemctl isolate causes forced logout

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1969]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805442

Say you are logged in to the console, "systemctl isolate multi-user.target" will kick you out of your session and you are back to the login prompt. This should not happen, since getty@.service has IgnoreOnIsolate=yes.

This is a regression that afaics was introduced in v227 by commit 8c8da0e0cb498245c765732cf9caa081a70c560f.

v228 had a followup fix in 417800228f69db9ff37f4193d11508757dd09308 but that is unfortunately not sufficient. So both v227 and v228 show this behaviour.

**Comment by intelfx** [comment]
Probably all slices should be `IgnoreOnIsolate=true`?..

/me is affected too.

**Comment by intelfx** [comment]
@poettering? would it be correct to ignore all slices on isolate? they are second to actual units, after all. We could also make them stopped-when-unneeded.

**Comment by bitstreamout** [comment]
Same reports here  http://bugzilla.opensuse.org/show_bug.cgi?id=966535 ...
As a simple test do login remote or local and do  `init 3' or even`init 5' at runlevel 5 or
   systemctl isolate graphical.target
or
  systemctl default
and all sessions become logout
