### ISSUE TITLE
CanGraphical is false on nvidia-340xx and kernel-5.11

### ISSUE THREAD

**Issue by wojnilowicz** [systemd/systemd#19698]
**systemd version the issue has been seen with**
 > 248.3

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `5.11.21-300.fc34.x86_64`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > true

**Unexpected behaviour you saw**
 > false

**Steps to reproduce the problem**
 > qdbus --system org.freedesktop.login1 /org/freedesktop/login1/seat/seat0 org.freedesktop.DBus.Properties.Get org.freedesktop.login1.Seat CanGraphical

**Additional program output to the terminal or log subsystem illustrating the issue**
SDDM will not show the display manager if "CanGraphical" is false. Overriding it shows the display manager.

lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation G96CM [GeForce 9600M GT] (rev a1)

in Xorg.0.log I have following line when I'm on kernel 5.10
"xfree86: Adding drm device (/dev/dri/card0)"
and "/dev/dri/card0" exists in fact, but when I'm on kernel 5.11 I don't have this line, and 
/dev/dri/card0 doesn't exist.

How can I debug it further?

```text
…
```

**Comment by poettering** [comment]
if the drm device doesn't exist, this looks like a driver problem, unrelated to systemd. We just pick up the DRM devices the kernel provides us with.

Please contact your distro for help.

**Comment by wojnilowicz** [comment]
> if the drm device doesn't exist, this looks like a driver problem, unrelated to systemd. We just pick up the DRM devices the kernel provides us with.
> 
> Please contact your distro for help.

Yes, the driver was the problem for the drm device and needed to be patched, but I think that setting CanGraphical to "false" when there is no drm device is also not right because if I hardcode it to true in sddm then everything graphical starts working. Thanks for looking into this matter.

**Comment by poettering** [comment]
well, CanGraphical= literally means: there's a graphics device for this seat. But as you say, there isn't. If you driver has a fallback and also can work without kernel graphics driver then that's great, but htat's not detectable by us.
