### ISSUE TITLE
Implement termination of the current session/user/seat using loginctl

### ISSUE THREAD

**Issue by rgeorgiev583** [systemd/systemd#19711]
**Is your feature request related to a problem? Please describe.**
It is convenient to be able to easily logout from the current session (i.e. terminate it) using the command line in a DE-invariant way.  However, this is currently a bit tedious to achieve using `loginctl` because one has to do the following:
1. check the ID of the current session using `loginctl list-sessions`;
2. run the `loginctl terminate-session ID` command to actually terminate the session.

**Describe the solution you'd like**
I want the `loginctl terminate-session` command, when invoked without any positional arguments, to simply terminate the current session.  This kind of behavior can similarly be implemented for `loginctl kill-session`, `loginctl terminate-user`, `loginctl kill-user` and `loginctl terminate-seat`.

**Describe alternatives you've considered**
It would be nice to implement a command-line flag (e.g. `-f`) for approval of this behavior because an unaware user might expect that `loginctl terminate-session` will simply print the usage of the command, so they'd run it carelessly and lose their entire session.  Without the `-f` flag, the command should output a confirmation message and ask to user to rerun the command with `-f` if they really want to terminate the session.

To be honest, I'm not convinced that this flag would really be beneficial.  It just crossed my mind as a possibility.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 248

**Comment by poettering** [comment]
this already exists. just pass the empty string as argument. i.e.:

```
loginctl terminate-session ""
```

Works for all relevant verbs.

I guess we should actually document that though.
