### ISSUE TITLE
Please apply acl also to /var/log/journal

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1971]
systemd.conf currently only set's up ACLs for subdirectories of /var/log/journal.

It would be good, if the ACL was also applied directly to /var/log/journal, (as we do for the file ownership/permissions).
This way, newly created subdirectories would directly inherit the correct ACL without requiring a reboot (or restart of systemd-tmpfiles for that matter). I'm thinking of systemd-journal-remote for example, which creates /var/log/journal/remote.

Afaics, Fedora already does it this way:

```
# getfacl /var/log/journal/
getfacl: Entferne führende '/' von absoluten Pfadnamen
# file: var/log/journal/
# owner: root
# group: systemd-journal
# flags: -s-
user::rwx
group::r-x
group:adm:r-x
group:wheel:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:adm:r-x
default:group:wheel:r-x
default:mask::r-x
default:other::r-x
```

Would make sense to apply that directly upstream.

@keszybz that's probably for you.

**Comment by mbiebl** [comment]
The systemd-journald man page contains

```
By default, the journal stores log data in /run/log/journal/. Since /run/ is volatile, log data is lost at reboot. To make the data persistent, it is
sufficient to create /var/log/journal/ where systemd-journald will then store the data:

           mkdir -p /var/log/journal
           systemd-tmpfiles --create --prefix /var/log/journal
```

Adding the ACL setup to systemd.conf would make sure we apply the distro default ACL as well.

**Comment by evverx** [comment]
> The systemd-journald man page contains

See https://github.com/systemd/systemd/issues/1397

**Comment by poettering** [comment]
Makes sense!

(Always happy to take a patch for these things!)

**Comment by keszybz** [comment]
Should be fixed now.
