### ISSUE TITLE
Support SendRelease for DHCPv6

### ISSUE THREAD

**Issue by tie** [systemd/systemd#19728]
**Is your feature request related to a problem? Please describe.**

Looking through the code, I can’t find where DHCPv6 client releases acquired IPv6 addresses on shutdown. That’s seems to be an issue on my network since apparently DHCP server does not assign new address until the existing lease expires.

**Describe the solution you'd like**

I want DHCPv6 client to release IP address on shutdown.

```ini
[DHCPv6]
SendRelease = true # default
```

**Describe alternatives you've considered**

Persist leases on reboot, see https://github.com/systemd/systemd/issues/16924

**The systemd version you checked that didn't have the feature you are asking for**

[systemd 247.6 from nixos-unstable](https://github.com/NixOS/nixpkgs/blob/ea7d4aa9b8225abd6147339f0d56675d6f1f0fd1/pkgs/os-specific/linux/systemd/default.nix)

**Comment by yuwata** [comment]
Closed by #26043.
