### ISSUE TITLE
networkd: Could not set NDisc route: Connection timed out

### ISSUE THREAD

**Issue by margau** [systemd/systemd#19738]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-5~bpo10+1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
> From buster-backports

**Used distribution**
> Debian Buster  (10)

**Linux kernel version used** (`uname -a`)
 > `Linux gw1 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > (re)-configure the interface using IPv6 RA and DHCP without failing, install route in table 1000, update route in table 1000

**Unexpected behaviour you saw**
 > failing to reconfigure the interface after some time, state changed to routable (failed)

**Steps to reproduce the problem**
 > Configure the system as stated below, provide a public ipv6 prefix via RA

**Additional program output to the terminal or log subsystem illustrating the issue**

An Interface is configured with the following network configuration:
```
[Match]
Name=ens18

[Network]
IPv6AcceptRA=true
DHCP=ipv4

[Route]
Table=1000
Destination=0.0.0.0/0
Gateway=_dhcp4

[Route]
Table=1000
Gateway=_ipv6ra
```

Another, manual IP rule command redirects some traffic to table 1000. At first, everything runs fine.
After a certain time (preferably around 00:30:00, maybe correlating to a new prefix rollout), at least once a day, the following failure happens, ens18 goes to state  `routable (failed)`.

```text
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Configuring route: dst: n/a, src: n/a, gw: fe80::[...], prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Configuring route: dst: n/a, src: n/a, gw: fe80::[...], prefsrc: n/a, scope: global, table: 1000, proto: ra, type: unicast
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Configuring route: dst: 2003::[...]/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Updating address: 2003:c6:[..]
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Setting SLAAC addresses.
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: Setting NDisc routes.
May 26 12:44:17 gw1 systemd-networkd[42935]: ens18: State changed: configured -> configuring
May 26 12:44:42 gw1 systemd-networkd[42935]: ens18: Could not set NDisc route: Connection timed out
May 26 12:44:42 gw1 systemd-networkd[42935]: ens18: Failed
May 26 12:44:42 gw1 systemd-networkd[42935]: ens18: State changed: configuring -> failed
```

The IPv4 route is still present. The IPv6 default route vanishes, both in table 1000 and in the default table.
The IPv6 address on ens18 is still present, as well as the on-link (/64) route. There is no kernel output in dmesg.

Restarting systemd-networkd fixes the issue until next iteration.

On the systems also the "bird" routing daemon injects some routes, but not in table 1000.

radvdump output:
```test
interface ens18
{
	AdvSendAdvert on;
	# Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
	AdvManagedFlag off;
	AdvOtherConfigFlag off;
	AdvReachableTime 0;
	AdvRetransTimer 0;
	AdvCurHopLimit 64;
	AdvDefaultLifetime 180;
	AdvHomeAgentFlag off;
	AdvDefaultPreference medium;
	AdvSourceLLAddress on;

	prefix 2003:c6:[..]::/64
	{
		AdvValidLifetime 2592000;
		AdvPreferredLifetime 604800;
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr off;
	}; # End of prefix definition

}; # End of interface definition
```

**Comment by yuwata** [comment]
Maybe, disabling `bird` fixes the issue?

**Comment by yuwata** [comment]
Or, #18545 fixes the issue? The PR is backported in v247.4.

**Comment by margau** [comment]
With stopped bird, the configuration is stable for > 12h, will continue to Monitor the Situation for another 12h. As bird normally Imports a IPv6 fulltable, it seems that this could definitively be related.

As the newer systemd Version is not directly available in Debian at the moment, it may Takes some time to try this out. If possible, I'll provide Feedback.

**Comment by margau** [comment]
Another Update: It is running stable over long time (~24h), until bird is started. Some minutes after bird installed its routes, the issue appears again. 
Unfortunately, I was not yet able to replace systemd with a newer version due to packaging and dependency issues on the semi-productive system.

**Comment by yuwata** [comment]
I guess setting `ManageForeignRoutes=no` in networkd.conf should resolve the issue. Closing.

If the setting does not resolve the issue, then feel free to request to reopen this page.
