### ISSUE TITLE
Suggested commands should include --user flag if the systemctl call includes it

### ISSUE THREAD

**Issue by mineo** [systemd/systemd#1973]
Same setup as in #1972, the output of `systemctl --user start hello` is

```
Job for hello.service failed because a configured resource limit was exceeded. See "systemctl status hello.service" and "journalctl -xe" for details.
```

The suggested call to `systemctl status` isn't really useful because the system service manager doesn't know about the user unit.

**Comment by poettering** [comment]
This has been fixed comprehensively with 4524439edb7d6050ba8a7779cdb7305e6ceb621c and some other commits.
