### ISSUE TITLE
nspawn Fedora 33 -> 34 container

### ISSUE THREAD

**Issue by ipcloud** [systemd/systemd#19740]
**systemd version the issue has been seen with**
 > systemctl --version
systemd 239 (239-41.el8_3.2)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

**Used distribution**
 > CentOS 8 (nspawn 'container' was Fedora 33 (upgrading to F34))

**Linux kernel version used** (`uname -a`)
==>  `4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
**CPU architecture issue was seen on**
 >x86_64

**Expected behaviour you didn't see**
 > In the container I  ran the command `dnf system-upgrade download --releasever=34`
 Expected to have the machine upgrade from F33 to F34

**Unexpected behaviour you saw**
 > Post the process the instruction (next step) was to run `dnf system-upgrade reboot`
And the machine did the upgrades but 
  would not complete the boot --> Failed to create /init.scope control group: Operation not permitted

**Steps to reproduce the problem**
 > Create an F33 nspawn container then run `dnf system-upgrade download --releasever=34`

The machine started to reboot and process the upgrade than no action after the following 
message:

Welcome to Fedora 34 (Thirty Four)!

Failed to create /init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Container tennessine failed with error code 255.

 After a bit of digging into this I see one main item that had me pause and start this report to you all.

 The permissions have been changed.  An example (I can provide one other if it helps) where files where root:root
they now show on the host as 659750912:659750912 
 ) Not sure what changed the permissions.  Other containers are not showing that issue and boot/run as expected
 on the same host as the noted 'container' with the issue.
 
 Is it possible to update the machine so that any 659750912:659750912 gets set back to root:root?
  Could be a script with some shell work 

but before I attempt that I am asking the question here

_What is the suggested best approach to get the container back up & running?_

 I figure there are a lot of details.  I can provide more information.  I wanted to get this started.  Let me know what
other details are helpful.

 I appreciate all your work and have used systemd-nspawn in many cases and hope there is a means 
to recover (beyond myself doing a complete rebuild).  

Your feedback is appreciated -- thanks

**Comment by ipcloud** [comment]
Could it be the systemd version "in" the 'container'? 
--> systemd-nspawn -bD /var/lib/machines/tennessine 
Spawning container tennessine on /home/machines/tennessine.
Press ^] three times within 1s to kill container.
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 34 (Thirty Four)!

Failed to create /init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Container tennessine failed with error code 255.

**Comment by poettering** [comment]
Have you previously run the container with "-U" mode? Maybe via `systemd-nspawn@.service`? See docs of that.

**Comment by ipcloud** [comment]
I had not.  
     I have run with the command = `systemd-nspawn -bD /var/lib/machines/tennessine` 
 
The .service file, the major way the container is run, is (very basic, the --network switch is in use):
[Unit]
Description=nspawn tennessine
[Service]
ExecStart=/usr/bin/systemd-nspawn -bD /var/lib/machines/tennessine --network-macvlan=enp2s0 --machine=tennessine
KillMode=mixed
Type=notify
RestartForceExitStatus=133
SuccessExitStatus=133
[Install]
WantedBy=multi-user.target

  I will follow the details you noted and learn some more details.

 The `dnf system-upgrade download --releasever=34` in that name space started the upgrade to Fedora 34.
  Then the `dnf system-upgrade reboot` rebooted the container and I could see the upgrade progress. 
 Though the container will not start. 

 Could it be the newer version of the systemd ("systemd v248.3-1.fc34 ") running in the container? 
 Are there configuration changes that could be made to it that could be made to progress in getting the machine to run?

 Thanks for your time.

**Comment by poettering** [comment]
Well, the 659750912:659750912 stuff suggests you did run things with -U or --private-user-chown in some form.

Consider running `systemd-nspawn --private-users=0 --private-users-chown …` once, to re-chown things to be ownd by host UID range again.

**Comment by ipcloud** [comment]
Could it be that the upgrade (dnf system-upgrade reboot) in the container does something to modify
the ownership?

   `systemd-nspawn --private-users=0 --private-users-chown -bD /var/lib/machines/tennessine`

==>
Spawning container tennessine on /home/machines/tennessine.
Press ^] three times within 1s to kill container.
Selected user namespace base 0 and range 65536.
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 34 (Thirty Four)!

Failed to create /init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Container tennessine failed with error code 255.

**Comment by poettering** [comment]
are you in cgroupv1 or cgroupv2 mode on the host?

**Comment by ipcloud** [comment]
cgroupv2

IF these steps I followed (below) are correct:
`
mkdir /mnt/c2
mount -t cgroup2 none /mnt/c2
ls -l  /mnt/c2
`
==>
total 0
-r--r--r-- 1 root root 0 May 27 09:22 cgroup.controllers
-rw-r--r-- 1 root root 0 May 27 09:22 cgroup.max.depth
-rw-r--r-- 1 root root 0 May 27 09:22 cgroup.max.descendants
-rw-r--r-- 1 root root 0 May 27 09:22 cgroup.procs
-r--r--r-- 1 root root 0 May 27 09:22 cgroup.stat
-rw-r--r-- 1 root root 0 May 27 09:22 cgroup.subtree_control
-rw-r--r-- 1 root root 0 May 27 09:22 cgroup.threads
-rw-r--r-- 1 root root 0 May 27 09:22 cpu.pressure
-rw-r--r-- 1 root root 0 May 27 09:22 io.pressure
-rw-r--r-- 1 root root 0 May 27 09:22 memory.pressure

# also
 `grep cgroup /proc/filesystems`
==>
nodev   cgroup
nodev   cgroup2


uname -r
4.18.0-240.22.1.el8_3.x86_64

**Comment by poettering** [comment]
What fs is mounted to /sys/fs/cgroup/? If it's tmpfs the system is running in cgroupv1 mode. If it's cgroup2 it's in cgroupv2 mode.

**Comment by ipcloud** [comment]
Thanks for the targeted details.

 Seems I was wrong.

==> tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)

So, I appreciate the help and all the work/efforts that go into the development and support...
 I am trying to figure out IF it is of value to pursue this and use up more valuable time/efforts
 OR IF doing a rebuild/replacement for the container is the wiser course of action. 
 
 I think it would be instructive to resolve but if the cost is too great --- let me know.

What is next?  How/What  can I do?

**Comment by ipcloud** [comment]
Could it be the systemd version "in" the 'container'? 
--> systemd-nspawn -bD /var/lib/machines/tennessine 
Spawning container tennessine on /home/machines/tennessine.
Press ^] three times within 1s to kill container.
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 34 (Thirty Four)!

Failed to create /init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Container tennessine failed with error code 255.

**Comment by ipcloud** [comment]
Thanks for the targeted details.

cgroupv1 does that  indicate there is not a means to repair?

**Comment by ipcloud** [comment]
What is next? How/What can I do?
  Is doing a rebuild/replacement for the container is the wiser course of action?
