### ISSUE TITLE
 HTTPS to the journal-gateway

### ISSUE THREAD

**Issue by Gittum** [systemd/systemd#19757]
When try to connect from a browser via HTTPS to the journal-gateway the browser shows a error message (In case of Firefox: PR_END_OF_FILE_ERROR) and in the journal of the host I found: 
microhttpd: Received malformed line (no colon). Closing connection.
microhttpd: Error processing request (HTTP response code is 400 ... Your HTTP request was syntactically incorrect) Closing connection.

A request via HTTP instead of HTTPS is without problems.

**systemd version the issue has been seen with**
> systemd 234

**Used distribution**
> openSUSE Leap 15.2

**Linux kernel version used** (`uname -a`)
 > `Linux 5.3.18-lp152.75-default #1 SMP Wed May 5 09:22:56 UTC 2021 (16c42c8) x86_64 x86_64 x86_64 GNU/Linux

**Comment by poettering** [comment]
did you configure an ssl cert for it?

Did you read the man page?

https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html

As documented, the service only speaks plain HTTP unless you configure a certificate in which case it can do https for you.

**Comment by poettering** [comment]
Closing, since I presume no certificate was configured. Moreover, this is a bug tracker only, for the two most recently released upstream systemd versions and the submission form tried to make this very clear to keep frustration at a minimum. 234 is *way* too old.
