### ISSUE TITLE
Incomplete --user service logging (no unit information in journal)

### ISSUE THREAD

**Issue by ecki** [systemd/systemd#19751]
**systemd version the issue has been seen with**
 > 245 (245.4-4ubuntu3)

**Used distribution**
 > Ubuntu 20.04 LTS

**Linux kernel version used** (`uname -a`)
 > `5.4.0-26-generic #30-ubuntu SMP`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**

When using system services the systemctl status command prints out most of the unit related log messages as well as stdout of the ExecStart= script (StandardOutput=journal) is used.

When using --user service the same behavior should happen. But it does not.

For a user with id < 1000 it does not print any messages when querying the status as this user (thats presumeable caused by the system redirect for those messages)

For a user with id > 1000 it does print the unit related messages but not stdout. But stdout is printed with journalctl --user.

The following example for a system service looks good:

```bash
root> systemctl daemon-reload
root> systemctl restart systest
root> systemctl status systest -n 100
● systest.service - TESTSERVICE2 (systest.service user root )
     Loaded: loaded (/etc/systemd/system/systest.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-27 23:03:09 CEST; 19s ago
   Main PID: 37127 (systest.sh)
      Tasks: 2 (limit: 2241)
     Memory: 788.0K
     CGroup: /system.slice/systest.service
             ├─37127 /bin/bash /root/systest.sh
             └─37130 sleep 50

Mai 27 23:03:09 ubunutu2004 systemd[1]: Started systest.service.
Mai 27 23:03:09 ubunutu2004 systest.sh[37128]: INVOCATION_ID=fca6b70072844a6caf00810964367e59
...
Mai 27 23:03:09 ubunutu2004 systest.sh[37128]: _=/usr/bin/env

root> journalctl _PID=37128 -n 1 -o json_pretty
{
	"_MACHINE_ID" : "880038e304264fe9b7fd7feee325c684",
	"_GID" : "0",
	"_SYSTEMD_UNIT" : "systest.service",
	"_SYSTEMD_INVOCATION_ID" : "fca6b70072844a6caf00810964367e59",
	"_UID" : "0",
	"_TRANSPORT" : "stdout",
	"_SELINUX_CONTEXT" : "unconfined\n",
	"_COMM" : "env",
	"_BOOT_ID" : "0a0b9642b957409bb51b738b875f4bf9",
	"SYSLOG_IDENTIFIER" : "systest.sh",
	"_HOSTNAME" : "ubunutu2004",
	"_STREAM_ID" : "c5e1b060f8c74606aa597142f34b2ecc",
	"_CAP_EFFECTIVE" : "3fffffffff",
	"__REALTIME_TIMESTAMP" : "1622149389500600",
	"MESSAGE" : "_=/usr/bin/env",
	"SYSLOG_FACILITY" : "3",
	"_PID" : "37128",
	"__MONOTONIC_TIMESTAMP" : "8756552426",
	"PRIORITY" : "6"
}
```

Note that the entries for the stdout messages contain an invocation id as well as _SYSTEMD_UNIT which allows them to be aggregated to the actual service. They showed up un systemctl status just fine. I can also find them by _SYSTEMD_INVOCATION_ID.

**Unexpected behaviour you saw**

For a user called app (uid=1001) it is still logged, but not correlated:

```bash
app> systemctl --user daemon-reload
app> systemctl --user restart apptest
app> systemctl --user status apptest
● apptest.service - TESTSERVICE2 (apptest.service user app )
     Loaded: loaded (/home/app/.config/systemd/user/apptest.service; disabled; vendor preset: enabled)
     Active: inactive (dead)

Mai 27 22:51:00 ubunutu2004 systemd[35541]: Started TESTSERVICE2 (apptest.service user app ).
Mai 27 22:51:50 ubunutu2004 systemd[35541]: apptest.service: Succeeded.

app> journalctl --user 
-- Logs begin at Thu 2021-05-27 22:21:26 CEST, end at Thu 2021-05-27 22:53:14 CEST. --
Mai 27 22:51:00 ubunutu2004 apptest.sh[36683]: INVOCATION_ID=18f27acc384c45f7aeaee61a27c1631b
...
Mai 27 22:51:00 ubunutu2004 apptest.sh[36683]: _=/usr/bin/env
Mai 27 22:51:50 ubunutu2004 systemd[35541]: apptest.service: Succeeded.

app> journalctl --user _PID=36683 -n 1  -o json-pretty
{
	"_STREAM_ID" : "a90670d8da1a4e7c9a58d6ae207604f0",
	"SYSLOG_IDENTIFIER" : "apptest.sh",
	"PRIORITY" : "6",
	"_GID" : "1001",
	"_TRANSPORT" : "stdout",
	"__REALTIME_TIMESTAMP" : "1622148660308861",
	"_BOOT_ID" : "0a0b9642b957409bb51b738b875f4bf9",
	"_HOSTNAME" : "ubunutu2004",
	"MESSAGE" : "_=/usr/bin/env",
	"_PID" : "36683",
	"__MONOTONIC_TIMESTAMP" : "8027360687",
	"SYSLOG_FACILITY" : "3",
	"_UID" : "1001",
	"_MACHINE_ID" : "880038e304264fe9b7fd7feee325c684"
}
```

It does not show up in the status output, it does not reference the USER_SYSTEMD_UNIT and it does not list a USER_INNVOCATIONID in the stdout logs. (it also misses STREAMID and SELINUX details?) 

----

The scripts systest.sh and apptest.sh have the following simple content:

```bash
#!/bin/bash
env
sleep 50
```

the /etc/systemd/system/systest.service:

```text
[Unit]
Description=TESTSERVICE (%n user %u)

[Service]
ExecStart=/root/systest.sh
StandardOutput=journal
User=root
```

the /home/app/.config/systemd/user/apptest.service:

```text
[Unit}
Description=TESTSERVICE2 (%n user %u)
AssertUser=app

[Install]
WantedBy=default.target

[Service]
ExecStart=/home/app/apptest.sh
StandardOutput=journal
#user=app - does not work /GROUP problem?!
```

**Comment by poettering** [comment]
Does this work if you "set" or "export" instead of "env" to print the env vars?

I figure this is simply a race with short-lived processes: if a process logs and immediately exits by the time journald tries to collect the log metadata the process is gone from /proc, hence we can't associate the metadata to it. 

This is not fixable without kernel improvements.

**Comment by ecki** [comment]
Yes you are right, the transient nature of env was the problem here. I tried it again with a shell-builtin "echo" and it worked (since the shell process did stick around longer). 

Strange enough I had the problem with an actual longer running forked application. But since I cannot reproduce it right now I will close this.

For completeness attached are 2 messages from the same test.sh script, one caused by an echo the other by "env" child. 

I wonder if in this case where there is no process thombstone hanging around to reflect from it, if somehow the info about the (still existing) parent could be reported. After all some info (SYSLOG_IDENTIFIER=test.sh) seems to be persisting. It also looks like the streamID is correct.

```json
journalctl -g 05d -o json-pretty
{
        "_CMDLINE" : "/bin/sh /root/test.sh",
        "_CAP_EFFECTIVE" : "0",
        "_SYSTEMD_UNIT" : "user@1000.service",
        "_SYSTEMD_USER_UNIT" : "apptest.service",
        "PRIORITY" : "6",
        "_STREAM_ID" : "13088612409e4fe7af5ad030643297c1",
        "_PID" : "637",
        "_BOOT_ID" : "5e9d6d438935496fb11b23ac1a023199",
        "_HOSTNAME" : "localhost",
        "__CURSOR" : "s=0b5798a4a200410cb333e37898c10e8b;i=2b7f;b=5e9d6d438935496fb11b23ac1a023199;m=7c6ef7551;t=5c3a608266d57;x=a18783775802a53e",
        "__REALTIME_TIMESTAMP" : "1622492752276823",
        "_SYSTEMD_CGROUP" : "/user.slice/user-1000.slice/user@1000.service/apptest.service",
        "SYSLOG_IDENTIFIER" : "test.sh",
        "_COMM" : "test.sh",
        "_SYSTEMD_INVOCATION_ID" : "05dbeb98082e4cb1bb39996382c332cc",
        "_UID" : "1000",
        "_SYSTEMD_OWNER_UID" : "1000",
        "_TRANSPORT" : "stdout",
        "SYSLOG_FACILITY" : "3",
        "_SELINUX_CONTEXT" : "unconfined\n",
        "_GID" : "100",
        "MESSAGE" : "Hello from /root/test.sh 05dbeb98082e4cb1bb39996382c332cc",
        "_EXE" : "/usr/bin/bash",
        "_MACHINE_ID" : "19a92bf4a1c949bfba9fc16830b42637",
        "_SYSTEMD_SLICE" : "user-1000.slice",
        "_SYSTEMD_USER_SLICE" : "-.slice",
        "__MONOTONIC_TIMESTAMP" : "33402352977"
}
{
        "__CURSOR" : "s=0b5798a4a200410cb333e37898c10e8b;i=2b82;b=5e9d6d438935496fb11b23ac1a023199;m=7c6ef7f87;t=5c3a60826778d;x=2d4e27eefa96007f",
        "_STREAM_ID" : "13088612409e4fe7af5ad030643297c1",
        "_MACHINE_ID" : "19a92bf4a1c949bfba9fc16830b42637",
        "SYSLOG_FACILITY" : "3",
        "PRIORITY" : "6",
        "_TRANSPORT" : "stdout",
        "MESSAGE" : "INVOCATION_ID=05dbeb98082e4cb1bb39996382c332cc",
        "_GID" : "100",
        "_COMM" : "env",
        "__MONOTONIC_TIMESTAMP" : "33402355591",
        "_BOOT_ID" : "5e9d6d438935496fb11b23ac1a023199",
        "_HOSTNAME" : "localhost",
        "__REALTIME_TIMESTAMP" : "1622492752279437",
        "_PID" : "638",
        "SYSLOG_IDENTIFIER" : "test.sh",
        "_UID" : "1000"
```

as reported before, the messages are not showing up (not correlated): 

```text
o apptest.service - apptest
     Loaded: loaded (/home/ecki/.config/systemd/user/apptest.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Mon 2021-05-31 22:26:42 CEST; 12min ago
    Process: 637 ExecStart=/root/test.sh (code=exited, status=0/SUCCESS)
   Main PID: 637 (code=exited, status=0/SUCCESS)

May 31 22:25:52 localhost systemd[1393]: Starting apptest...
May 31 22:25:52 localhost systemd[1393]: Started apptest.
May 31 22:25:52 localhost test.sh[637]: Hello from /root/test.sh 05dbeb98082e4cb1bb39996382c332cc
May 31 22:26:42 localhost systemd[1393]: apptest.service: Succeeded.
```

```bash
#!/bin/sh
echo "Hello from $0 $INVOCATION_ID"
env
sleep 50
exit 0
```

MAybe it would be at least possible to associate the stream id somehow with the unit start? This was the first systemd message for this:

```json
{
        "SYSLOG_IDENTIFIER" : "systemd",
        "CODE_FILE" : "src/core/job.c",
        "_CMDLINE" : "/usr/lib/systemd/systemd --user",
        "_PID" : "1393",
        "_CAP_EFFECTIVE" : "0",
        "MESSAGE_ID" : "7d4958e842da4a758f6c1cdc7b36dcc5",
        "_BOOT_ID" : "5e9d6d438935496fb11b23ac1a023199",
        "CODE_LINE" : "592",
        "_TRANSPORT" : "journal",
        "_COMM" : "systemd",
        "_SYSTEMD_OWNER_UID" : "1000",
        "_SYSTEMD_USER_UNIT" : "init.scope",
        "CODE_FUNC" : "job_log_begin_status_message",
        "_SELINUX_CONTEXT" : "unconfined\n",
        "_GID" : "100",
        "PRIORITY" : "6",
        "SYSLOG_FACILITY" : "3",
        "_HOSTNAME" : "localhost",
        "JOB_ID" : "34",
        "_SYSTEMD_UNIT" : "user@1000.service",
        "_SOURCE_REALTIME_TIMESTAMP" : "1622492752268679",
        "_SYSTEMD_USER_SLICE" : "-.slice",
        "__MONOTONIC_TIMESTAMP" : "33402344994",
        "JOB_TYPE" : "start",
        "USER_INVOCATION_ID" : "05dbeb98082e4cb1bb39996382c332cc",
        "__CURSOR" : "s=0b5798a4a200410cb333e37898c10e8b;i=2b7d;b=5e9d6d438935496fb11b23ac1a023199;m=7c6ef5622;t=5c3a608264e28;x=1eda1f4e0dccc543",
        "_UID" : "1000",
        "_SYSTEMD_CGROUP" : "/user.slice/user-1000.slice/user@1000.service/init.scope",
        "_MACHINE_ID" : "19a92bf4a1c949bfba9fc16830b42637",
        "_EXE" : "/usr/lib/systemd/systemd",
        "_SYSTEMD_SLICE" : "user-1000.slice",
        "__REALTIME_TIMESTAMP" : "1622492752268840",
        "MESSAGE" : "Starting apptest...",
        "USER_UNIT" : "apptest.service"
}
```

**Comment by ecki** [comment]
BTW: just for completeness, it does work for a system service, echo and env messages show up properly. Is this due to another type of slice or different child reaping?

```text
ÔùÅ systest.service - apptest
     Loaded: loaded (/etc/systemd/system/systest.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Mon 2021-05-31 22:49:12 CEST; 44s ago
    Process: 8331 ExecStart=/root/test.sh (code=exited, status=0/SUCCESS)
   Main PID: 8331 (code=exited, status=0/SUCCESS)

May 31 22:48:21 localhost systemd[1]: Starting apptest...
May 31 22:48:21 localhost systemd[1]: Started apptest.
May 31 22:48:21 localhost test.sh[8331]: Hello from /root/test.sh d4708414876f4a58939718400548b2ed
May 31 22:48:21 localhost test.sh[8332]: LANG=en_US.UTF-8
May 31 22:48:21 localhost test.sh[8332]: INVOCATION_ID=d4708414876f4a58939718400548b2ed
May 31 22:48:21 localhost test.sh[8332]: USER=ecki
May 31 22:48:21 localhost test.sh[8332]: PWD=/
May 31 22:48:21 localhost test.sh[8332]: HOME=/home/ecki
May 31 22:48:21 localhost test.sh[8332]: JOURNAL_STREAM=9:1112535
May 31 22:48:21 localhost test.sh[8332]: SHELL=/bin/bash
May 31 22:48:21 localhost test.sh[8332]: SHLVL=1
May 31 22:48:21 localhost test.sh[8332]: LOGNAME=ecki
May 31 22:48:21 localhost test.sh[8332]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
May 31 22:48:21 localhost test.sh[8332]: _=/usr/bin/env
May 31 22:49:12 localhost systemd[1]: systest.service: Succeeded.
```

**Comment by ncfavier** [comment]
> I figure this is simply a race with short-lived processes: if a process logs and immediately exits by the time journald tries to collect the log metadata the process is gone from /proc, hence we can't associate the metadata to it.

I don't understand this: if I want to capture the output of a process, I redirect stdout to a pipe, fork, exec, and the process writes to the pipe. Why isn't systemd doing this? What is stdout connected to, for processes run by systemd? Why do we need `/proc` at all?

**Comment by ncfavier** [comment]
Also, I can't seem to reproduce this issue with system services. Is this specific to user units?

**Comment by ecki** [comment]
Yes, i can only reproduce it with —user services.

The journald is capturing the pipe just as you have described, but in order to look up Meta-Data of the originator, it has to see the running process. If the process is gone and the data is only buffered in the pipe it will journal the output, it just is not tagging it correctly. Not sure why System mode services do not have this problem.


--
http://bernd.eckenfels.net
________________________________
Von: Naïm Favier ***@***.***>
Gesendet: Wednesday, June 16, 2021 11:17:33 PM
An: systemd/systemd ***@***.***>
Cc: Bernd ***@***.***>; State change ***@***.***>
Betreff: Re: [systemd/systemd] Incomplete --user service logging (no unit information in journal) (#19751)


Also, I can't seem to reproduce this issue with system services. Is this specific to user units?

**Comment by ncfavier** [comment]
I guess what I wonder specifically is why use a single pipe for the entire journald, rather than one pipe per unit/cgroup?

**Comment by ecki** [comment]
I guess it is already one pipe per forked process, otherwise it can’t inherit it from the Systemd instance. In case of the „env“ command that pipe fd is cloned with the transient child.. it should still know that the pipe is for a unit. But don’t know haven’t looked at the systemd code too close.

 I do try to stay away from user services they seem to have some quirks, but this specific one might  not be a kernel limitation (only).


--
http://bernd.eckenfels.net
________________________________
Von: Naïm Favier ***@***.***>
Gesendet: Thursday, June 17, 2021 2:54:04 AM
An: systemd/systemd ***@***.***>
Cc: Bernd ***@***.***>; State change ***@***.***>
Betreff: Re: [systemd/systemd] Incomplete --user service logging (no unit information in journal) (#19751)


I guess what I wonder specifically is why use a single pipe for the entire journald, rather than one pipe per unit/cgroup?
