### ISSUE TITLE
systemd-backlight[584]: Failed to get backlight or LED device 'backlight:acpi_video0': No suc

### ISSUE THREAD

**Issue by tivrfoa** [systemd/systemd#19770]
$ systemctl --version
systemd 245 (245.4-4ubuntu3.6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Linux kernel version used** (`uname -a`)
```
Linux lesco-Lenovo-IdeaPad-S145-15API 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**

AMD® Ryzen 5 3500u with radeon vega mobile gfx × 8 

**Expected behaviour you didn't see**

Brightness should not change.

**Unexpected behaviour you saw**
 
Screen gets darker.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: Created slice system-systemd\x2dbacklight.slice.
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:acpi_video0...
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd-backlight[584]: Failed to get backlight or LED device 'backlight:acpi_video0': No suc>
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: systemd-backlight@backlight:acpi_video0.service: Main process exited, code=exited>
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: systemd-backlight@backlight:acpi_video0.service: Failed with result 'exit-code'.
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: Failed to start Load/Save Screen Backlight Brightness of backlight:acpi_video0.
jun 01 07:09:03 lesco-Lenovo-IdeaPad-S145-15API systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```

**Comment by tivrfoa** [comment]
Hi folks,

The brightness of my laptop goes to minimum when I boot it.
The brightness changes when this error happens.
I am able to change the brightness after the boot.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by yuwata** [comment]
Should be duplicate of #16600, #16718, and #17826.
