### ISSUE TITLE
user journal files have weird group x bit set (mode 650)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1977]
Looking at /var/log/journal, it looks like journald creates the user journal files with the group x bit set:

```
-rw-r-----+ 1 root systemd-journal 8388608 Nov 21 03:08 system.journal
-rw-r-x---+ 1 root systemd-journal 8388608 Nov 21 02:47 user-1000.journal
-rw-r-x---+ 1 root systemd-journal 8388608 Nov 21 02:42 user-65534.journal
```

That seems odd. For the the system.journal, not such x bit is set.

**Comment by poettering** [comment]
How do the ACLs for these files look like?

**Comment by mbiebl** [comment]
```
getfacl: Removing leading '/' from absolute path names
# file: var/log/journal/567a68a5c2672114bcf5192d00000008/user-1000.journal
# owner: root
# group: systemd-journal
user::rw-
user:michael:r--
group::r-x
group:adm:r-x
mask::r-x
other::---
```

**Comment by keszybz** [comment]
Gee, github has so many shiny buttons. If only the search box would autocomplete on labels ;)

**Comment by keszybz** [comment]
Hm, seems to be a problem with our acl setting functions.

I added some tests in keszybz/systemd@233e4ffc331185b7dc4d633d6ae120b6b2d1a43e and journald seems to be doing everything all right.
