### ISSUE TITLE
udev: the broken symlink left in system

### ISSUE THREAD

**Issue by gaoyi1988** [systemd/systemd#19788]
**systemd version the issue has been seen with**
 > 247

**Expected behaviour you didn't see**
 > There is no broken symlink in /dev

**Unexpected behaviour you saw**
 > There are some broken symlinks in /dev

**Steps to reproduce the problem**
 > 1. iscsiadm -m node -p 127.0.0.1 -l   (there are 100 disks in system)
 > 2. parted -s -l &  (can trigger the change uevent)
 > 3. iscsiadm -m node -p 127.0.0.1 -u &

**Additional program output to the terminal or log subsystem illustrating the issue**

There is no sdf1 in system，but has the symlink as follow:
```
[root@localhost by-id]# ll /dev/disk/by-id
lrwxrwxrwx. 1 root root  9 Jun  1 21:02 scsi-36001405aa0fe76b38fc4a84b921a13f3 -> ../../sdf1
lrwxrwxrwx. 1 root root  9 Jun  1 21:02 wwn-0x6001405aa0fe76b38fc4a84b921a13f3 -> ../../sdf1
…
```

From the logs, I think this is because there is no device when handling the change or remove uevent. 
```
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Processing device (SEQNUM=86248, ACTION=change)
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: sd-device: Failed to read uevent file '/sys/devices/platform/host1/session655/target1:0:0/1:0:0:3/block/sdf/sdf1/uevent': No such device
May 31 15:54:52 localhost.localdomain systemd-udevd[574]: sdf1: Device (SEQNUM=86259, ACTION=remove) is queued
May 31 15:54:52 localhost.localdomain systemd-udevd[574]: sdf1: SEQNUM=86259 blocked by SEQNUM=86248
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: /usr/lib/udev/rules.d/60-persistent-storage.rules:95 Importing properties from results of builtin command 'blkid'
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Failed to open block device /dev/sdf1: No such file or directory
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: /usr/lib/udev/rules.d/60-persistent-storage.rules:95 Failed to run builtin 'blkid': No such file or directory
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Handling device node '/dev/sdf1', devnum=b8:81
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Preserve already existing symlink '/dev/block/8:81' to '../sdf1'
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: sd-device: Created db file '/run/udev/data/b8:81' for '/devices/platform/host1/session655/target1:0:0/1:0:0:3/block/sdf/sdf1'
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Adding watch on '/dev/sdf1'
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Failed to add device '/dev/sdf1' to watch: No such file or directory
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: sd-device: Created db file '/run/udev/data/b8:81' for '/devices/platform/host1/session655/target1:0:0/1:0:0:3/block/sdf/sdf1'
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Device (SEQNUM=86248, ACTION=change) processed
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: sd-device-monitor: Passed 324 byte to netlink monitor
May 31 15:54:52 localhost.localdomain systemd-udevd[574]: sdf1: Device (SEQNUM=86259, ACTION=remove) ready for processing
May 31 15:54:52 localhost.localdomain systemd-udevd[574]: sdf1: sd-device-monitor: Passed 267 byte to netlink monitor
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Processing device (SEQNUM=86259, ACTION=remove)
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: Device (SEQNUM=86259, ACTION=remove) processed
May 31 15:54:52 localhost.localdomain systemd-udevd[25748]: sdf1: sd-device-monitor: Passed 311 byte to netlink monitor
```

Are there any methods that can delete the broken symlinks.

**Comment by yuwata** [comment]
@gaoyi1988 Is it reproducible with the current git HEAD?

**Comment by yuwata** [comment]
Could you also show the result of `udevadm monitor -k -p -s block` or relevant command?

**Comment by poettering** [comment]
so, when this happens what does "udevadm info /dev/sd1" report?

**Comment by yuwata** [comment]
@gaoyi1988 Are there any broken symbolic links in /dev/block (or /dev/char)?

**Comment by yuwata** [comment]
Hmm,,, very strange. From 60-persistent-storage.rules, each device symlink to a partition has suffix `-part%n`, e.g.
```
# by-id (World Wide Name)
ENV{DEVTYPE}=="disk", ENV{ID_WWN_WITH_EXTENSION}=="?*", SYMLINK+="disk/by-id/wwn-$env{ID_WWN_WITH_EXTENSION}"
ENV{DEVTYPE}=="partition", ENV{ID_WWN_WITH_EXTENSION}=="?*", SYMLINK+="disk/by-id/wwn-$env{ID_WWN_WITH_EXTENSION}-part%n"
```

**Comment by yuwata** [comment]
Also, the timestamp shown in the result of `ll /dev/disk/by-id` is newer than the date shown in the log...

Could you test the following?
1. logout iscsi session and remove the device
2. remove the broken symlinks
3. also remove /run/udev/links/\x2fdisk\x2fby-id\x2fscsi-36001405aa0fe76b38fc4a84b921a13f3 and /run/udev/links/\x2fdisk\x2fby-id\x2fwwn-0x6001405aa0fe76b38fc4a84b921a13f3
4. login iscsi session and create the device
5. `udevadm info /dev/sdf1`, check symlinks in /dev/disk/by-id and files in /run/udev/links
6. trigger change uevent by parted
7. again `udevadm info /dev/sdf1`, check symlinks in /dev/disk/by-id and files in /run/udev/links
8. logout iscsi session and remove the device
9. again `udevadm info /dev/sdf1`, check symlinks in /dev/disk/by-id and files in /run/udev/links
10. `journalctl --no-hostname -u systemd-udevd.service` and provide the relevant logs (all of ADD, CHANGE, and REMOVE events for the device)

**Comment by gaoyi1988** [comment]
> so, when this happens what does "udevadm info /dev/sd1" report?

When the problem happened, there is no /dev/sdf1 in the system

**Comment by gaoyi1988** [comment]
> @gaoyi1988 Are there any broken symbolic links in /dev/block (or /dev/char)?

No

**Comment by gaoyi1988** [comment]
> Hmm,,, very strange. From 60-persistent-storage.rules, each device symlink to a partition has suffix `-part%n`, e.g.
> 
> ```
> # by-id (World Wide Name)
> ENV{DEVTYPE}=="disk", ENV{ID_WWN_WITH_EXTENSION}=="?*", SYMLINK+="disk/by-id/wwn-$env{ID_WWN_WITH_EXTENSION}"
> ENV{DEVTYPE}=="partition", ENV{ID_WWN_WITH_EXTENSION}=="?*", SYMLINK+="disk/by-id/wwn-$env{ID_WWN_WITH_EXTENSION}-part%n"
> ```
Actually, my original environment with broken symbolic links /dev/sdf1 has been rebooted. And I reproduced the problem as above, and the broken symbolic links is /dev/sde. But I add a lot of logs and so the logs are messy. So the symbolic links above is   /dev/sde, 
For /dev/sdf1, the broken symbolic links are these two, too, with part.

**Comment by poettering** [comment]
again, how does "udevadm info /dev/sdf1" (or whatever the block device name is at the moment) looks like when the device vanished but the symlinks are still there?

**Comment by gaoyi1988** [comment]
> again, how does "udevadm info /dev/sdf1" (or whatever the block device name is at the moment) looks like when the device vanished but the symlinks are still there?
```
[root@localhost by-id]# ll /dev/disk/by-id/
lrwxrwxrwx. 1 root root  9 Jun  3 16:05 scsi-36001405aa0fe76b38fc4a84b921a13f3 -> ../../sde
lrwxrwxrwx. 1 root root  9 Jun  3 16:05 wwn-0x6001405aa0fe76b38fc4a84b921a13f3 -> ../../sde
[root@localhost by-id]# udevadm info /dev/sde
Successfully loaded SELinux database in 5.202ms, size on heap is 729K.
Unknown device "/dev/sde": No such file or directory
```

**Comment by gaoyi1988** [comment]
/run/udev/links also have  these two:
```
[root@localhost links]# ls *001405aa0fe76b38fc4a84b921a13f3*
'\x2fdisk\x2fby-id\x2fscsi-36001405aa0fe76b38fc4a84b921a13f3':
b8:64

'\x2fdisk\x2fby-id\x2fwwn-0x6001405aa0fe76b38fc4a84b921a13f3':
b8:64
[root@localhost links]# pwd
/run/udev/links
[root@localhost links]#
```

**Comment by gaoyi1988** [comment]
By adding logs, the problem seems to be occured as follow (change uevent):
1. worker_device_monitor_handler() -> worker_process_device() -> udev_event_execute_rules() -> device_clone_with_db() -> device_read_db() -> device_read_db_internal() -> device_get_id_filename()
Because of no device, device_get_id_filename() failed, and print "Failed to read uevent file...". So nothing was read from the database.
2. udev_event_execute_rules() -> update_devnode() -> udev_node_update_old_links()
Nothing will be removed.

**Comment by yuwata** [comment]
```
sdf1: sd-device: Failed to read uevent file '/sys/devices/platform/host1/session655/target1:0:0/1:0:0:3/block/sdf/sdf1/uevent': No such device
```
Hmm? Did you modify udev-event.c? Why is the failure not propagated? If you change some code in systemd, then please clarify the change at first.

BTW, I hope #19815 fixes this issue.
