### ISSUE TITLE
/sys/firmware/efi/efivars should be mounted by default even if we diable efi

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#19787]
**systemd version the issue has been seen with**
 > ALL

**Used distribution**
 > fedora 34

**Expected behaviour you didn't see**
 > 1. I build the systemd with configuration Defi=false Dgnu-efi=false cause i want to get a simplify systemd.
2. I want to use some tools as efibootmgr. It should be supported.

**Unexpected behaviour you saw**
 > 
```
# efibootmgr
EFI variables are not suported on this system.
```
I figured out it was caused by the code listed below
```
#if ENABLE_EFI
        { "efivarfs",    "/sys/firmware/efi/efivars", "efivarfs",   NULL,                                      MS_NOSUID|MS_NOEXEC|MS_NODEV,
          is_efi_boot,   MNT_NONE                   },
#endif
```

I think we should delete the macro here. Even if we don enable efi feature in systemd, but there are maybe some other tools that can be used to manager efi.

**Steps to reproduce the problem**
 > Use the systemd without EFI enabled.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
This sounds really wrong to me. if people turn something off we should not turn it back on behind their back. I don't undestand what this is supposed to fix? Why don't you turn EFI on if you want EFI?

**Comment by syyhao1994** [comment]
> fix? Why don't you turn EFI on if you want EFI?

I use grub2 for EFI boot on arm and legacy boot on x86. So i need /sys/firmware/efi/efivars to be mounted by default. 
I disable systemd-boot just for getting a simplify systemd. I am not mean to disable EFI.
And if we really dont use EFI(maybe we use legacy), mount /sys/firmware/efi/efivars does nothing actually. So i think it is suitable to try to mount efivars by default.

**Comment by poettering** [comment]
mounting efivarfs triggers SMM code on most firmwares and people hence in some environments want to disable it. See #19509 for example.

sd-boot and EFI support in systemd are two distinct things. If you build systemd without gnu-efi but with EFI on you'll get a systemd version that does mounts efivarfs for you but we won't build sd-boot for you. If all you want is no sd-boot support, then thta' the way to go.

Sorry, but if people turn off EFI that should mean no EFI.

You can also do what #19509 does, and supply your own mount units. I don#t think that makes much sense for the general case though.

**Comment by yuwata** [comment]
@syyhao1994 You should just disable `gnu-efi`, instead of EFI support (`efi`). `meson configure -Dgnu-efi=false`. Closing.
