### ISSUE TITLE
systemd segfault in timer_enter_waiting while masking a unit

### ISSUE THREAD

**Issue by sitsofe** [systemd/systemd#1981]
Description of problem:
While trying to mask a timer file that in turn has a subunit override systemd segfaulted.

Version-Release number of selected component (if applicable):
Fedora 23
systemd-222-8.fc23.x86_64

How reproducible:
Reproducible every time.

Steps to Reproduce:
1. Run

```
rm /etc/systemd/system/dnf-makecache.timer.d/override.conf
systemctl unmask dnf-makecache.timer
reboot
```

.
2. When the system is back up and running log in and run
`systemctl edit dnf-makecache.timer`
and put the following lines:

```
[Timer]
OnBootSec=10s
OnUnitInactiveSec=1h
```

and then save and quit your editor.
3. Run
`systemctl mask dnf-makecache.timer`
.

Actual results:
The following is printed:

```
Broadcast message from systemd-journald@<hostname> (Sat 2015-10-10 15:31:20 UTC):

systemd[1]: Caught <SEGV>, dumped core as pid 819.


Broadcast message from systemd-journald@<hostname> (Sat 2015-10-10 15:31:20 UTC):

systemd[1]: Freezing execution.
```

and it is no longer possible to start/stop systemd units or change runlevels/reboot cleanly.

Expected results:
dnf-makecache.timer unit to be masked out?

Additional info:
Using
`echo "/tmp/core" > /proc/sys/kernel/core_pattern`
before step 3 allows a core dump to be produced. Looking at the backtrace in the coredump shows the following:

```
#0  0x00007f433b062d07 in kill () from /lib64/libc.so.6
#1  0x0000563ce32c04dd in crash.lto_priv ()
#2  <signal handler called>
#3  0x0000563ce337240c in timer_enter_waiting ()
#4  0x0000563ce3372d7d in timer_enter_waiting_coldplug ()
#5  0x0000563ce3386226 in manager_coldplug.lto_priv ()
#6  0x0000563ce32b8ef4 in manager_reload ()
#7  0x0000563ce32bb819 in main ()
```

dmesg also contains the following:

```
[   49.866897] systemd[1]: segfault at 1d0 ip 0000556629ef640c sp 00007ffffa39f700 error 4 in systemd[556629e1b000+14a000]
[   49.882635] systemd-coredum[820]: segfault at 0 ip 0000561607fb4361 sp 00007ffe6effbc90 error 6 in systemd-coredump[561607fa6000+18000]
```

Originally filed on https://bugzilla.redhat.com/show_bug.cgi?id=1270524 against systemd-219-24.fc22.x86_64 in Fedora 22.

**Comment by sitsofe** [comment]
Reproduced with systemd-228-3.fc24.x86_64 , backtrace with debug symbols below:

```
Thread 1 (LWP 1027):
#0  0x00007efe19f6e8d7 in kill () at ../sysdeps/unix/syscall-template.S:84
#1  0x000055611abae831 in crash.lto_priv.245 (sig=11) at src/core/main.c:195
#2  <signal handler called>
#3  timer_enter_waiting (t=0x55611bb41500, initial=initial@entry=false) at src/core/timer.c:411
#4  0x000055611abb8237 in timer_coldplug.lto_priv.474 (u=<optimized out>) at src/core/timer.c:285
#5  0x000055611ac157c6 in unit_coldplug (u=0x55611bb41500) at src/core/unit.c:2896
#6  0x000055611ac226b4 in manager_coldplug.lto_priv.987 (m=0x55611bb07150) at src/core/manager.c:1035
#7  0x000055611ab48ff7 in manager_reload (m=0x55611bb07150) at src/core/manager.c:2577
#8  0x000055611ab4cdd5 in main (argc=5, argv=<optimized out>) at src/core/main.c:1802

(gdb) print (&t->meta)->dependencies[UNIT_TRIGGERS]
$8 = (Set *) 0x0
```

**Comment by sitsofe** [comment]
Is the coredump handler also crashing?

**Comment by evverx** [comment]
I can confirm this.

Script to reproduce:

``` sh
cat <<'EOL' >/lib/systemd/system/my.service
[Service]
Type=oneshot
ExecStart=/bin/echo Timer runs me
EOL

cat <<'EOL' >/lib/systemd/system/my.timer
[Timer]
OnBootSec=10s
OnUnitInactiveSec=1h
EOL

systemctl unmask my.timer

systemctl start my.timer

mkdir -p /etc/systemd/system/my.timer.d/
cat <<'EOL' >/etc/systemd/system/my.timer.d/override.conf
[Timer]
OnBootSec=10s
OnUnitInactiveSec=1h
EOL

systemctl daemon-reload

systemctl mask my.timer
```

**Comment by evverx** [comment]
I don't have a fix.
But I wrote a [test](https://github.com/evverx/systemd/commit/fb2a28a21147dd35d341c610c56ef410978b3f24).
So, ping me. I can reproduce this segfault very fast:)

**Comment by poettering** [comment]
Fix waiting in PR #2576.

**Comment by evverx** [comment]
Works fine!

**Comment by keszybz** [comment]
What about a pull request with the test?

**Comment by evverx** [comment]
Makes sense. I'll prep a PR.

**Comment by evverx** [comment]
Done: https://github.com/systemd/systemd/pull/2579
