### ISSUE TITLE
Add 60-sensor.hwdb ACCEL_MOUNT_MATRIX for Cube i7 Book

### ISSUE THREAD

**Issue by Dziban-dev** [systemd/systemd#19829]
Hi I own a cube i7 book and i noticed the screen rotation when in portrait mode was fliped so I made this changes to the 60-sensor.hwdb and it all works correctly now, i noticed there is no profile for that specific device lister on systemd's 60-sensor.hwdb.
so here it is:

```
sensor:modalias:acpi:KIOX000A*:dmi:*:svnCube*:pni16-L:*
  ACCEL_MOUNT_MATRIX=0,0,1;0,1,0;1,0,0
```

**Comment by Dziban-dev** [comment]
related to this but i don't know if is an issue with systemd, now that the screen rotation displays correctly on portraitmode, the wacom pen is inverted when portrait mode, if i go down with the pen the cursor goes up and so on, however left and right works just fine. Don't know if I need to open and issue for that

**Comment by Dziban-dev** [comment]
here is the info for the build in wacom device:

```
I: Bus=0018 Vendor=056a Product=0104 Version=0100
N: Name="Wacom HID 104 Pen"
P: Phys=i2c-WCOM4002:01
S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-WCOM4002:01/0018:056A:0104.0003/input/input11
U: Uniq=
H: Handlers=mouse1 event10 
B: PROP=2
B: EV=b
B: KEY=1e03 0 0 0 0 0
B: ABS=1000003
```

**Comment by poettering** [comment]
Please submit your patch as PR, then the change will be properly attributed to you and everything

**Comment by poettering** [comment]
Let's close this here. Since we lack this hardware we can't test this and rely on ready-made submissions for this hence.

Hence, please submit as PR after testing, so that we cna just merge it, and properly attribute it to you.
