### ISSUE TITLE
sd_notify( 0, "WATCHDOG=1" ) causes intermittent Assertion 'close_nointr(fd) != -EBADF' failed at ../src/basic/fd-util.c:81, function safe_close(). Aborting.

### ISSUE THREAD

**Issue by theDogOfPavlov** [systemd/systemd#19834]
**systemd version the issue has been seen with**
 systemd 237

**Used distribution**
Ubuntu Bionic

**Linux kernel version used** 
Linux asparagus 5.4.0-1048-aws #50~18.04.1-Ubuntu SMP Tue May 4 17:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
Intel

**Expected behaviour you didn't see**
No assertion. ;)

**Unexpected behaviour you saw**
Intermittently (once every few days or so) the service will fail with the above error, and then the watchdog will restart it.

**Steps to reproduce the problem**

**Additional program output to the terminal or log subsystem illustrating the issue**

```[Unit]
Description=asparagus
After=mysql.service
StartLimitIntervalSec=60s

[Service]
Type=notify
NotifyAccess=main
User=asparagus
ExecStart=/opt/asparagus/asparagus
TimeoutSec=130s
WatchdogSec=60s
Restart=on-failure
RestartSec=20s
StartLimitBurst=2

[Install]
WantedBy=multi-user.target
```

**Comment by poettering** [comment]
This is almost certainly a bug in your program "asparagus", which presumably closes the file descriptor that sd_notify() internally uses to communicate with PID1. it really shouldn't do that, closing other code's file descriptors is not OK.

(Also, systemd v237 is *way* too old for an issue to be filed upstream, and the submission form should have made that very clear, to keep frustration at a minimum. For everything older ping your distribution)

**Comment by theDogOfPavlov** [comment]
Thanks for the quick response: noted on the version, but my code definitely doesn't close file descriptors that don't belong to it. It has been working without issue for months without change, and has suddenly started throwing these errors. Checking the ubuntu changelog, there were multiple changes pushed to systemd in May. I'll follow it up with them!
