### ISSUE TITLE
User Manager for UID service fails to start with access denied for display manager user

### ISSUE THREAD

**Issue by tSte** [systemd/systemd#19859]
**systemd version the issue has been seen with**
 > systemd 248.3-2

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)

 > `5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x64 i7-1185G7

**Expected behaviour you didn't see**
 > After installing and running display manager (tested with SDDM and LigthDM), systemd will load and start `User Manager for UID 967` (`/usr/lib/systemd/system/user@.service`). I'd expect this service not to fail.

**Unexpected behaviour you saw**
 > The service failed with `pam_access(systemd-user:account): access denied for user 'sddm' from 'systemd-user'`

**Steps to reproduce the problem**
 > Install display manager (SDDM or LightDM) and start display manager service (or `systemctl enable` it and reboot). In my case:
```
sudo pacman -S sddm
sudo systemctl start sddm.service
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```systemctl status user@967.service 
× user@967.service - User Manager for UID 967
     Loaded: loaded (/usr/lib/systemd/system/user@.service; static)
     Active: failed (Result: exit-code) since Wed 2021-06-09 09:18:39 CEST; 2min 30s ago
       Docs: man:user@.service(5)
    Process: 1068 ExecStart=/usr/lib/systemd/systemd --user (code=exited, status=224/PAM)
   Main PID: 1068 (code=exited, status=224/PAM)
        CPU: 9ms

Jun 09 09:18:39 tyy systemd[1]: Starting User Manager for UID 967...
Jun 09 09:18:39 tyy systemd[1068]: pam_access(systemd-user:account): access denied for user `sddm' from `systemd-user'
Jun 09 09:18:39 tyy systemd[1068]: pam_systemd_home(systemd-user:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Jun 09 09:18:39 tyy systemd[1068]: PAM failed: Permission denied
Jun 09 09:18:39 tyy systemd[1068]: user@967.service: Failed to set up PAM session: Operation not permitted
Jun 09 09:18:39 tyy systemd[1068]: user@967.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted
Jun 09 09:18:39 tyy systemd[1]: user@967.service: Main process exited, code=exited, status=224/PAM
Jun 09 09:18:39 tyy systemd[1]: user@967.service: Failed with result 'exit-code'.
Jun 09 09:18:39 tyy systemd[1]: Failed to start User Manager for UID 967.
```

**Comment by poettering** [comment]
A PAM module called "pam_access" prohibits access apparently. Not sure why that even is in your PAM stack. But it's certainly not systemd's fault, but maybe put there by distro or admin?
