### ISSUE TITLE
systemd.network(5) is missing L2TP

### ISSUE THREAD

**Issue by dasJ** [systemd/systemd#19869]
**Is your feature request related to a problem? Please describe.**

I'm trying to configure L2TP with networkd.
I have a problem with the lack of documentation for a related option.

**Describe the solution you'd like**

Documentation for `L2TP=` in the `[Network]` section.

**Describe alternatives you've considered**

Read the source code myself.
I found the option via a [blog post](https://tsia.me/systemd-networkd_L2TP/) and was able to confirm its existence in the [parser test](https://github.com/yuwata/systemd/blob/main/test/fuzz/fuzz-network-parser/directives.network#L221).

**The systemd version you checked that didn't have the feature you are asking for**

main branch as of writing

cc @ajs124 @yuwata

**Comment by yuwata** [comment]
Fix is waiting in #19871.
