### ISSUE TITLE
logind: trigger service if button is held

### ISSUE THREAD

**Issue by robimarko** [systemd/systemd#19880]
**Is your feature request related to a problem? Please describe.**
Currently, logind has no support for triggering a systemd service when a button is held.
It can trigger shutdown/reboot etc upon a button press, but that is triggered as soon as
the input event is broadcast.

**Describe the solution you'd like**
I would like to have a trigger or something that allows a systemd service to be started if for
example reset button is held for 5s or so.
This would allow using the same(Usually the only) button to trigger a factory reset on the device
instead of only rebooting.
This is a common feature in systems using OpenWrt and similar distributions.

**Describe alternatives you've considered**
No possible alternatives as pressing the button causes instant reboot.

**The systemd version you checked that didn't have the feature you are asking for**
v248

**Comment by robimarko** [comment]
@yegor-alexeyev Any ideas?

**Comment by yegor-alexeyev** [comment]
Want to link a related issue here for reference:
https://github.com/systemd/systemd/issues/16400

**Comment by yegor-alexeyev** [comment]
I think logind receives enough information for the implementation of this. 
button_dispatch should be receiving both KEY_RESTART pressed and KEY_RESTART released events. All that is needed then is to keep some timer which wil measure the key press duration and fire the appropriate action depending on the duration. 
The only drawback I see is a slight change of behaviour, the KEY_RESTART will be handled on button releasing, and not on button pressing as it is now. But this is inevitable.


I will prepare the PR for this.

**Comment by robimarko** [comment]
Great to hear that.
I don't think that triggering on release will change the behaviour noticeably for a simple reboot.

**Comment by yegor-alexeyev** [comment]
Created PR https://github.com/systemd/systemd/pull/19917
This one just supports handling of reboot key longpress. It does not introduce the ability to launch a systemd service in response to the button event.
