### ISSUE TITLE
How to fix a bad boot ID in the journal?

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#19887]
I am runnign EndeavourOS with systemd  248.3-2-arch. Today my PC was frozemn and I had to reboot why the REISUB mechanismn. After that I can not see old boot logs with journalctl -b -1 for example:

```
9# journalctl -b -1
Data from the specified boot (-1) is not available: No data available
```

But the logs are still there. I can scroll through them with just the journactl command. When I do `journalctl --list-boots` I see a list of 265 boot logs without any error message.

But `export SYSTEMD_LOG_LEVEL=debug` reveals the following:

```
21# journalctl -b -6
[...]
Encountered invalid entry while bisecting, cutting algorithm short. (1)
Attempt to move to uninitialized object: 9519184
Encountered invalid entry while bisecting, cutting algorithm short. (1)
Whoopsie! We found a boot ID but can't read its last entry.
Data from the specified boot (-6) is not available: No data available
Root directory /run/log/journal removed.
Directory /var/log/journal/4bd88beaa35549b5922de02c8064cbf1 removed.
Root directory /var/log/journal removed.
mmap cache statistics: 6916 context cache hit, 1392 window list hit, 540 miss
```

How can I fix this: `We found a boot ID but can't read its last entry.` ?

**Comment by poettering** [comment]
Hmm, we should handle issues like this automatically, you shouldn't notice anything bad from these corruptions

Any chance you can provide me with the set of journal files that caused this where i can reproduce this? (no need to attach here though, just send me by email).

**Comment by mabod** [comment]
Unfortunately this is not possible. I vacuumed the journal and my backup did not run befor I did that.

From the report I posted in the EndeavourOS forum:

```
Jun 10 12:05:00 rakete kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to process the buffer list -19!
Jun 10 12:05:01 rakete crond[13330]: pam_unix(crond:session): session opened for user matthias(uid=1000) by (uid=0)
-- Boot 00000000000000000000000000000000 --
-- Boot 09d9dc88ec4a42cfb4abfb9563fc87a8 --
Jun 10 12:12:01 rakete kernel: Linux version 5.12.9-zen1-1-zen (linux-zen@archlinux) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 Z>
Jun 10 12:12:01 rakete kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-linux-zen root=UUID=0a765f87-6eca-4e05-bd1a-36ac4ba3fb8f rw audit=0 >
```
I created this log with just "journalctl" which was working all the time. It is just the "-b -1" option which fails. It seems to me it is stumbling over a boot ID with all zeros.

**Comment by poettering** [comment]
This is unfortunately not actionable for us. If this is ever reproducible, please provide us with the offending journal file, and we'll certainly fix it.

let's close this, as we can't really know wat precisely went wrong here.

**Comment by DaanDeMeyer** [comment]
Some fixes landed recently that might address this issue as well. I'd build the latest journalctl from main to see if you still have the issue. If that doesn't fix it, please provide a journal file as @poettering suggested.
