### ISSUE TITLE
RFE: Add OnWatchdogFailure= dependency type

### ISSUE THREAD

**Issue by pdmorrow** [systemd/systemd#19885]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to start some other service if systemd detects a service has not sent it's "WATCHDOG=1" message to systemd. This other service could be used to notify some other part of the system that a particular service wasn't able to pat the watchdog for whatever reason.

If a service has an OnFailure= dependency list and a OnWatchdogFailure= list then the OnWatchdogFailure dependencies would be run only if there was a watchdog failure. In all other failure cases the regular OnFailure dependency list would be run.

**Describe the solution you'd like**

A new OnWatchdogFailure= dependency type which causes services specified to be run if the service which defines the list fails due to watchdog expiry.

**Describe alternatives you've considered**

I wondered about making use of the existing OnFailure= mechanism and then checking the services Result property for value "watchdog". This might be possible with templates and some other hoop jumping, thus the RFE for a clear mechanism for starting some service(s) on watchdog expiry.

**The systemd version you checked that didn't have the feature you are asking for**

249.

**Comment by poettering** [comment]
So, we could add a concept that for OnFailure= and OnSuccess= we expose the service metainfo as env vars to the activated services. i.e. whenever we spawn a service we check the reverse deps OnFailureOf= and OnSuccessOf= it might have. If there's exactly one then we'd pick up up relevant props of the listed service and expose it as env vars in our service i.e. we'd basically take the env vars $EXIT_CODE=/$EXIT_STATUS=/$SERVICE_RESULT= that we currently set for ExecStop= of a service, and also set them for  any monitor service, maybe prefixed with MONITOR_ or so. Maybe also add MONITOR_UNIT= and MONITOR_INVOCATION_ID= as additional env vars describing the service OnFailureOf= and OnSuccessOf= point to.

**Comment by poettering** [comment]
Not a fan of OnWatchdogFailure=, it's a bit too specific to my test. I don't think we should permit an inflation of deps like this for every single case of failure tere might be. However, the simple approach i suggested should be equally good, no?

**Comment by pdmorrow** [comment]
Yep, agreed. I like the more general approach here.

**Comment by pdmorrow** [comment]
Yep, agreed. I like the more general approach here.
