### ISSUE TITLE
systemd-networkd: MultiPathRoute:  Nexthop device index does not match RTA_OIF

### ISSUE THREAD

**Issue by 3nprob** [systemd/systemd#19890]
**systemd version the issue has been seen with**
 > 247.3-5

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)
 > `Linux foo 5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
  > `amd64`

**Expected behaviour you didn't see**
Attempting to add a MultipathRoute as default gateway. Manually adding the route using `ip route` works fine:
```
# ip route add default nexthop via 192.168.1.3 weight 10 nexthop via 192.168.1.2 weight 50
```
However, attempting to add the same route using `systemd-networkd` fails.

**Unexpected behaviour you saw**
Given the following:

```
# /etc/systemd/network/eth0.network
[Match]
Name=eth0

[Network]
IPForward=true
Address=192.168.1.1/24
Domains=lan

[Route]
MultiPathRoute=192.168.1.3 10
MultiPathRoute=192.168.1.2 50
GatewayOnlink=no # or yes

# Either of these:
Destination=0.0.0.0/0
PreferredSource=192.168.1.1

```

Gives error message:

```
eth0: Could not set route: Nexthop device index does not match RTA_OIF. Invalid argument
eth0: Failed
```

**Steps to reproduce the problem**

Add the above file. Restart `systemd-networkd`.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
eth0: Could not set route: Nexthop device index does not match RTA_OIF. Invalid argument
eth0: Failed
```

**Comment by yuwata** [comment]
Thank you for the report.

Workaround for this issue is adding interface name in `MultiPathRoute=`:
```
MultiPathRoute=192.168.1.3@eth0 10
```

**Comment by 3nprob** [comment]
Thanks for the workaround and fast resolution!
