### ISSUE TITLE
Add L4 protocol filtering for SocketBind{Allow|Deny}=

### ISSUE THREAD

**Issue by jkartseva** [systemd/systemd#19891]
**Is your feature request related to a problem? Please describe.**
`SocketBind{Allow|Deny}=` unit properties already support filtering by address family, port or port range.
Filtering by L4 protocol, e.g. TCP, UDP, DCCP prevents services from using illegitimate L4 protocol.
This addresses feature request by @topimiettinen https://github.com/systemd/systemd/pull/17655#issuecomment-800001162

This should be merged before [v249](https://github.com/systemd/systemd/milestones/v249) is finalized: dbus API ought to stay immutable across releases.
The implementation is halfway done at the moment of filing the issue.

**Comment by keszybz** [comment]
I think it's fine to do this change up until the final release, we don't have to keep the dbus api stable before then.

Currently the filters are described as `"a(iqq)"`. I guess something like `"a(iiqq)"` will be appropriate. If we don't manage to get the implementation done quickly enough, I think we should merge a simple patch which adds the additional param, but requires it to be 0 on input, and always outputs 0 in output. We can then add other values in a backwards-compatible fashion.

**Comment by wat-ze-hex** [comment]
@keszybz 

#19942 adds a stub ip protocol parameter to dbus methods, w/o implementation yet. Should be an easy review.
Implementation doesn't block the release and will follow.
