### ISSUE TITLE
Signal info always TERM

### ISSUE THREAD

**Issue by Pablohn26** [systemd/systemd#199]
I have created a dummy service that create a sleep process at start and kill the sleep process with several signals when you type systemctl stop sleep.service.

I have tried with signal 9 (SIGKILL), signal 23 (SIGSTOP) and signal 18 (SIGTSTP) and when I type systemctl status sleep.service it always says the signal was TERM (from SIGTERM, I suppose). My signal reference is http://man7.org/linux/man-pages/man7/signal.7.html

Here aretwo examples of the problem: 
- http://pastebin.centos.org/28616/
- http://pastebin.centos.org/28621/

**Comment by poettering** [comment]
Well, systemd assumes that ExecStop= is synchronous: it not only asks the service for shutdown, but also waits for it to exit. If systemd sees a process of the daemon around after ExecStop= exits, it will kill it anyway.

Placing an invocation of /usr/bin/kill in ExecStop= is hence generally not a good idea.

Also, note that systemd always sends SIGCONT after each SIGTERM when shutting down a service, to ensure that paused processes can be terminated too.

**Comment by mbiebl** [comment]
I think it would be a great idea to put this information into the man page
Am 14.06.2015 23:34 schrieb "Lennart Poettering" notifications@github.com:

**Comment by poettering** [comment]
@mbiebl done so now in cceb20c75ca4eb14cb72866e9490691b543f0dd6 and e8c53936316288ea3b33b5997b175862f0efef92

**Comment by mbiebl** [comment]
2015-06-15 12:07 GMT+02:00 Lennart Poettering notifications@github.com:

> @mbiebl https://github.com/mbiebl done so now in cceb20c
> https://github.com/systemd/systemd/commit/cceb20c75ca4eb14cb72866e9490691b543f0dd6
> and e8c5393
> https://github.com/systemd/systemd/commit/e8c53936316288ea3b33b5997b175862f0efef92
> 
> Thanks Lennart.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?
