### ISSUE TITLE
Cannot add gateway as device to routing table

### ISSUE THREAD

**Issue by bnicolae** [systemd/systemd#19911]
**Is your feature request related to a problem? Please describe.**

Cannot add gateway as device to specified routing table. This is needed to redirect all traffic via Wireguard when the gateway IP is not known (i.e., need a way to define a separate table that handles the non-watermarked packets in which the default route is set to device instead of IP).

**Describe the solution you'd like**

The [Route] section should allow gateways to be added as devices, not only IPs. For example:
```
DefaultRouteOnDevice=true
Table=1000
```

This would be equivalent to: 
`ip route add default dev wg0 table 1000`

**Describe alternatives you've considered**

I've considered starting wg-quick@wg0 after systemd-networkd initializes my interfaces. This works great, except that a network reconfiguration clears the routing tables and leaves WireGuard in a stale state (a manual restart is needed to fix it).

The [Network] section has a "DefaultRouteOnDevice=" setting that binds the default route to a device, but it does not allow to put the corresponding rule in a separate table.

**The systemd version you checked that didn't have the feature you are asking for**
248

**Comment by yuwata** [comment]
`DefaultRouteOnDevice=yes` is an alias of 
```
[Route]
Gateway=0.0.0.0
```
So, a workaround for your issue is
```
[Route]
Gateway=0.0.0.0
Table=1000
```

**Comment by bnicolae** [comment]
Thanks, this works. The documentation should be updated to mention this.

**Comment by yuwata** [comment]
The man page update is waiting in #19933.
