### ISSUE TITLE
Socket activation using SELinuxContextFromNet requires service use socket

### ISSUE THREAD

**Issue by tedx** [systemd/systemd#19918]
systemd-219-78.el7_9.3

RHEL 7.9

3.10.0-1160.21..1

x86_64

In order for the SELinuxContestFromNet socket option to work one or more of the associated service files
StandardInput/StandardOutput/StandardError options must be set to socket.

From execute.c:
      if (context->std_input == EXEC_INPUT_SOCKET ||
            context->std_output == EXEC_OUTPUT_SOCKET ||
            context->std_error == EXEC_OUTPUT_SOCKET) {

                if (params->n_fds != 1) {
                        log_unit_error(params->unit_id, "Got more than
one socket.");
                        return -EINVAL;
                }

                socket_fd = params->fds[0];
        } else {
                socket_fd = -1;
                fds = params->fds;
                n_fds = params->n_fds;
        }

When socket_fd is -1 the SELinux context is not computed. 

If this would also work when using a single fd that would be helpful.

**Comment by poettering** [comment]
Yes, this makes sense, we should make this work.

**Comment by msekletar** [comment]
@tedx please see my PR #20063. Testing would be very much appreciated!

**Comment by poettering** [comment]
patch looks good, but can you augment the man page about this? it should make clear that this only work if a single socket is passed to a service. i.e. maybe:

"This option has no effect when more than one socket is passed to the activated service." to the  SELinuxContextFromNet= part of systemd.socket should suffice

**Comment by poettering** [comment]
oops that comment should have been on the PR, not here.
