### ISSUE TITLE
Kernel 4.19 won*t boot with systemd v248, but boots fine with v247

### ISSUE THREAD

**Issue by hphilm** [systemd/systemd#19926]
**systemd version the issue has been seen with**
 > systemd 248.3-2

**Used distribution**
 > Manjaro 21.0.7

**Linux kernel version used** (`uname -a`)

 > `4.19.194-1-MANJARO`

**CPU architecture issue was seen on**
 > Ryzen 2 (x64)

**Expected behaviour you didn't see**
 > Boot the system with 4.19 kernel

**Unexpected behaviour you saw**
 > System compains about udev and haveged systemd services not able to run. Only a reboot of the system is possible. Note: 4.14 and other kernels boot fine.

**Steps to reproduce the problem**
 > Get the latest [Manjaro 21.0.7 ISO](manjaro.org/download/), install it as Kernel 5.10 series boots with 248. Install the package **linux419** via `sudo mhwd-kernel -i linux419`. Try to boot the system with that 4.19 kernel.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Jun 14 20:40:33 development systemd[1]: systemd-udevd.service: Failed with result 'exit-code'.
Jun 14 20:40:33 development systemd[1]: Failed to start Rule-based Manager for Device Events and Files.
Jun 14 20:40:33 development systemd[1]: systemd-udevd.service: Scheduled restart job, restart counter is at 2.
Jun 14 20:40:33 development systemd[1]: Stopped Rule-based Manager for Device Events and Files.
Jun 14 20:40:33 development systemd[1]: Starting Rule-based Manager for Device Events and Files...
Jun 14 20:40:33 development systemd[392]: systemd-udevd.service: Failed to set up mount namespacing: /run/systemd/unit-root/proc/sys/kernel/hostname: Device or resource busy
Jun 14 20:40:33 development systemd[392]: systemd-udevd.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-udevd: Device or resource busy
Jun 14 20:40:33 development systemd[1]: systemd-udevd.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 14 20:40:33 development systemd[1]: systemd-udevd.service: Failed with result 'exit-code'.
Jun 14 20:40:33 development systemd[1]: Failed to start Rule-based Manager for Device Events and Files.
Jun 14 20:40:33 development systemd[1]: systemd-udevd.service: Scheduled restart job, restart counter is at 3.
....
Jun 14 20:40:34 development systemd[1]: haveged.service: Scheduled restart job, restart counter is at 1.
Jun 14 20:40:34 development systemd[1]: Stopped Entropy Daemon based on the HAVEGE algorithm.
Jun 14 20:40:34 development systemd[1]: Started Entropy Daemon based on the HAVEGE algorithm.
Jun 14 20:40:34 development systemd[403]: haveged.service: Failed to set up mount namespacing: /run/systemd/unit-root/dev: Invalid argument
Jun 14 20:40:34 development systemd[403]: haveged.service: Failed at step NAMESPACE spawning /usr/bin/haveged: Invalid argument
Jun 14 20:40:34 development systemd[1]: haveged.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 14 20:40:34 development systemd[1]: haveged.service: Failed with result 'exit-code'.
```

**Comment by mrc0mmand** [comment]
A "full" log when trying to restart systemd-udevd from a rescue shell for completeness:

```
[  539.705373] systemd[1]: systemd-udevd.service: Converting job systemd-udevd.service/restart -> systemd-udevd.service/start
[  539.705399] systemd[1]: systemd-udevd.service: Consumed 2ms CPU time.
[  539.705421] systemd[1]: systemd-udevd.service: ConditionPathIsReadWrite=/sys succeeded.
[  539.705968] systemd[1]: systemd-udevd.service: Failed to remove oomd_avoid flag on control group /system.slice/systemd-udevd.service, ignoring: Operation not supported
[  539.706049] systemd[1]: systemd-udevd.service: Failed to remove oomd_omit flag on control group /system.slice/systemd-udevd.service, ignoring: Operation not supported
[  539.706086] systemd[1]: systemd-udevd.service: Passing 2 fds to service
[  539.706110] systemd[1]: systemd-udevd.service: About to execute /usr/lib/systemd/systemd-udevd
[  539.706185] systemd[1]: systemd-udevd.service: Forked /usr/lib/systemd/systemd-udevd as 315
[  539.706358] systemd[1]: systemd-udevd.service: Changed dead -> start
[  539.706409] systemd[1]: Starting Rule-based Manager for Device Events and Files...
[  539.707535] systemd[1]: systemd-journald.service: Got notification message from PID 250 (FDSTORE=1)
[  539.707579] systemd[1]: systemd-journald.service: Added fd 42 (n/a) to fd store.
[  539.707603] systemd[315]: Bind-mounting / on /run/systemd/unit-root (MS_BIND|MS_REC "")...
[  539.707757] systemd[315]: Applying namespace mount on /run/systemd/unit-root/proc/sys/kernel/domainname
[  539.707785] systemd[315]: Bind-mounting /run/systemd/unit-root/proc/sys/kernel/domainname on /run/systemd/unit-root/proc/sys/kernel/domainname (MS_BIND|MS_REC "")...
[  539.707808] systemd[315]: Successfully mounted /run/systemd/unit-root/proc/sys/kernel/domainname to /run/systemd/unit-root/proc/sys/kernel/domainname
[  539.707831] systemd[315]: Applying namespace mount on /run/systemd/unit-root/proc/sys/kernel/hostname
[  539.707856] systemd[315]: Bind-mounting /run/systemd/unit-root/proc/sys/kernel/hostname on /run/systemd/unit-root/proc/sys/kernel/hostname (MS_BIND|MS_REC "")...
[  539.707880] systemd[315]: Successfully mounted /run/systemd/unit-root/proc/sys/kernel/hostname to /run/systemd/unit-root/proc/sys/kernel/hostname
[  539.707902] systemd[315]: Applying namespace mount on /run/systemd/unit-root/run/credentials
[  539.707922] systemd[315]: Bind-mounting /run/systemd/inaccessible/dir on /run/systemd/unit-root/run/credentials (MS_BIND|MS_REC "")...
[  539.707943] systemd[315]: Successfully mounted /run/systemd/inaccessible/dir to /run/systemd/unit-root/run/credentials
[  539.707967] systemd[315]: Applying namespace mount on /run/systemd/unit-root/run/systemd/incoming
[  539.707988] systemd[315]: Followed source symlinks /run/systemd/propagate/systemd-udevd.service → /run/systemd/propagate/systemd-udevd.service.
[  539.708020] systemd[315]: Bind-mounting /run/systemd/propagate/systemd-udevd.service on /run/systemd/unit-root/run/systemd/incoming (MS_BIND "")...
[  539.708047] systemd[315]: Successfully mounted /run/systemd/propagate/systemd-udevd.service to /run/systemd/unit-root/run/systemd/incoming
[  539.708071] systemd[315]: Remounted /run/systemd/unit-root/proc/sys/kernel/domainname.
[  539.708095] systemd[315]: Failed to re-mount '/run/systemd/unit-root/proc/sys/kernel/hostname' and its submounts: Device or resource busy
[  539.708117] systemd[315]: systemd-udevd.service: Failed to set up mount namespacing: /run/systemd/unit-root/proc/sys/kernel/hostname: Device or resource busy
[  539.708143] systemd[315]: systemd-udevd.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-udevd: Device or resource busy
[  539.742883] systemd[1]: Received SIGCHLD from PID 315 ((md-udevd)).
[  539.742975] systemd[1]: Child 315 ((md-udevd)) died (code=exited, status=226/NAMESPACE)
[  539.743042] systemd[1]: systemd-udevd.service: Child 315 belongs to systemd-udevd.service.
[  539.743079] systemd[1]: systemd-udevd.service: Main process exited, code=exited, status=226/NAMESPACE
[  539.743116] systemd[1]: systemd-udevd.service: Failed with result 'exit-code'.
[  539.743153] systemd[1]: systemd-udevd.service: Service will restart (restart setting)
[  539.743182] systemd[1]: systemd-udevd.service: Changed start -> failed
[  539.743221] systemd[1]: systemd-udevd.service: Job 140 systemd-udevd.service/start finished, result=failed
[  539.743262] systemd[1]: Failed to start Rule-based Manager for Device Events and Files.
```

**Comment by mrc0mmand** [comment]
The whole `/proc` fs seems to be in some *weird* state:

![image](https://user-images.githubusercontent.com/679338/121958344-df7e8800-cd63-11eb-975f-18ba39a9b134.png)

**Comment by philmmanjaro** [comment]
Some also report that 4.9 kernel series won't boot. However 4.4 does. This is really weird. What do those kernel series missing ...

**Comment by mrc0mmand** [comment]
With v248 GA (938bdfc0fa737d86eb3ecc70506e11e5f740e0dc) it boots fine. I'll try to bisect this if it find anything useful.

**Comment by mrc0mmand** [comment]
Bisect show that the problematic commit is 5c5753b - after reverting this commit the machine boots fine once again.

/cc @poettering

**Comment by poettering** [comment]
So, this is an old kernel. does it work with a more recent kernel version? my guess is that this is the mount table brokeness on old kernels, that newer libmount worked around. i.e. /proc/self/mountinfo on old kernels showed partially old data and partially new data, and confused the heck out of everyone.

at  least that's my guess that this is the issue here.

please ping your kernel maintainers, update the kernel, or backport relevant patches. Or at least update libmount to something new.

**Comment by poettering** [comment]
The "mount -l" screenshot really suggets this is about mount table corruption, i.e. "proc on 20" with mount options "(rw,25)", what is that even supposed to mean?

**Comment by philmmanjaro** [comment]
The thing is: 4.14 is fine, 4.19 not. For now I reverted the following commits on my end to get 4.19 booting again:

  3e4099b090301707ed55d56e7ea6a91bf3910b48
  f67154881de61d436bd95312bd015314f613c922
  c2e7941d914968d15bfc2ced889f9e76ae875f2a
  bad107f1518452c725f0142bb223f77acf1a62b5
  c2c331056a7c331a5478124b3cd6a34c9f539839

I assume since 4.14 boots, some patches are missing for 4.19 to make this work ...

**Comment by mrc0mmand** [comment]
> So, this is an old kernel. does it work with a more recent kernel version? my guess is that this is the mount table brokeness on old kernels, that newer libmount worked around. i.e. /proc/self/mountinfo on old kernels showed partially old data and partially new data, and confused the heck out of everyone.
> 
> at least that's my guess that this is the issue here.
> 
> please ping your kernel maintainers, update the kernel, or backport relevant patches. Or at least update libmount to something new.

Unfortunately, even with the latest util-linux master (and thus the latest libmount) the issue still persists.

**Comment by philmmanjaro** [comment]
@mrc0mmand I assume some is missing in the 4.19 kernel series to make this work. We should ping @gregkh and Sasha Levin on this one.

**Comment by poettering** [comment]
> I assume since 4.14 boots, some patches are missing for 4.19 to make this work ...

What is with newer, less archaic kernels?

**Comment by poettering** [comment]
anyway, let's drop this from our milestone. given that the "mount" output you posted shows complete rubbish I doubt systemd is involved here, but just suffer by the same kernel problem that "mount" suffers by.

**Comment by gregkh** [comment]
What specific 4.19.y release is having problems here?  Did older ones work?  Any chance you can use `git bisect` on the kernel to see where the offending commit showed up?

**Comment by philmmanjaro** [comment]
Well, we have to see if any 4.19 kernel works with **systemd** 248.2 to have a clue. Latest 4.14 and 4.4 for example works just fine. I'll try some and let you guys know.

**Comment by gregkh** [comment]
4.19 is based on a tree from 2018, why not just use a newer kernel release?

**Comment by moson-mo** [comment]
@philmmanjaro
You have some patch in your 4.19 manjaro-build that seems to cause the trouble with systemd: "proc_mounts.patch"
When I remove the patch and build the kernel I can boot just fine...

**Comment by philmmanjaro** [comment]
Hmm. Have to check that. So with 4.19.0 it booted, also the 4.19.133. I had found a 4.19.175 which didn't boot. @moson-mo so if that is the case with the patch on our end, sorry for the noise. Let me check that [patch](https://gitlab.manjaro.org/packages/core/linux419/-/blob/master/proc_mounts.patch).

**Comment by philmmanjaro** [comment]
@moson-mo seems to be that patch, as 4.19.133-1 didn't had it. It was added with 4.19.133-2. Have to see why we had that patch anyway ...

**Comment by philmmanjaro** [comment]
So it seems it was a patch of Aufs4, which got somehow added during updating on our end. This is what the patch does:

- proc_mounts.patch
  When there are many mountpoints and many mount(2)/umount(2) are
  running, then /proc/mounts may not show the all mountpoints.  This
  patch makes /proc/mounts always show the full mountpoints list.
  If you don't want to apply this patch and meet such problem, then you
  need to increase the value of 'ProcMounts_Times' make-variable in
  aufs-util.git as a second best solution.

**Comment by philmmanjaro** [comment]
So I think we can close this one then. I was able to boot with the latest 248.3 Systemd and the kernel:

```
   [phil@development Schreibtisch]$ uname -a
   Linux development 4.19.194-2-MANJARO #1 SMP Tue Jun 15 17:28:21 UTC 2021 x86_64 GNU/Linux
   [phil@development Schreibtisch]$ pacman -Q systemd
   systemd 248.3-4
```
