### ISSUE TITLE
upstream-ci: Entry 'sockets.target.wants' in /etc/systemd/system (32387) has an incorrect filetype (was 2, should be 1).

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#19952]
Version: 249-rc1

After updating systemd from v248 to v249-rc1, I pretty reliably get this error message when trying to run the upstream ci via autopkgtest:

```
 Loading, please wait...
Starting version 249~rc1-1
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
Begin: Will now check root file system ... fsck from util-linux 2.36.1
[/sbin/fsck.ext4 (1) -- /dev/sda1] fsck.ext4 -a -C0 /dev/sda1 
systemd contains a file system with errors, check forced.
Entry 'sockets.target.wants' in /etc/systemd/system (32387) has an incorrect filetype (was 2, should be 1).


systemd: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
	(i.e., without -a or -p options)
fsck exited with status code 4
done.
Failure: File system check of the root filesystem failed
The root filesystem on /dev/sda1 requires a manual fsck


BusyBox v1.30.1 (Debian 1:1.30.1-6+b2) built-in shell (ash)
Enter 'help' for a list of built-in commands.
```

A full test log of `autopkgtest --test-name=upstream` is attached.
The tests are run via qemu (5.2) on Debian sid with kernel 5.10.40

[log.txt](https://github.com/systemd/systemd/files/6664778/log.txt)

I haven't really investigated this yet. But since this error happens reproducibly, I thought it's best to file it here.

Might be worth adding this to the v249 milestone.

**Comment by mbiebl** [comment]
The error messages are slightly different each time but they all look like some FS corruption.

**Comment by mbiebl** [comment]
Hm, this might be due to a missing dosfstools. Will further investigate.

**Comment by bluca** [comment]
dosfstools? Do we use vfat anywhere in the test suite?

**Comment by mbiebl** [comment]
```
$ grep mkfs.vfat test/ -R
test/test-efi-create-disk.sh:mkfs.vfat -F32 "${LOOP}p1"
test/test-functions:    dracut_install /sbin/mkfs.vfat
```

**Comment by bluca** [comment]
ah for EFI, of course

**Comment by mbiebl** [comment]
I'm curious, why this didn't fail on the Ubuntu CI. Do they have dosfstools pre-installed?

**Comment by bluca** [comment]
I'm not sure - this is the diff between the upstream-ci and debian/experimental branches on salsa:

```
--- a/debian/tests/control
+++ b/debian/tests/control
@@ -115,7 +115,6 @@ Restrictions: needs-root, isolation-container, breaks-testbed
 
 Tests: upstream
 Depends: @,
-  attr,
   tree,
   perl,
   xz-utils,
@@ -141,7 +140,7 @@ Depends: @,
   libc6-dev | libc-dev,
   make,
   quota,
-  fdisk,
+  fdisk | util-linux (<< 2.29.2-3~),
   netcat-openbsd,
   socat,
   busybox-static,
@@ -150,6 +149,7 @@ Depends: @,
   zstd,
   squashfs-tools,
   vim-tiny,
+  attr,
 Restrictions: needs-root, allow-stderr, isolation-machine
 
 Tests: boot-smoke
@@ -180,7 +180,7 @@ Depends: libsystemd-dev,
   systemd-container,
   systemd-coredump,
   systemd-sysv,
-  fdisk,
+  fdisk | util-linux (<< 2.29.2-3~),
   netcat-openbsd,
   busybox-static,
   plymouth,
```

**Comment by mbiebl** [comment]
ah, I think it is because `ubuntu-standard` depends on it.

**Comment by bluca** [comment]
is the issue fixed after installing it?

**Comment by mbiebl** [comment]
Yeah, I don't see any fs related errors anymore. Closing

**Comment by bluca** [comment]
Added as a dependency in the upstream-ci branch so that it's documented: https://salsa.debian.org/systemd-team/systemd/-/commit/292b70acaaed99abe1282c473c931e80ada06508

**Comment by mbiebl** [comment]
@bluca, @ddstreet I just made an upload of 249-rc1 to experimental

I think I've cherry-picked everything that is relevant from the `upstream-ci` branch and rebased the `upstream-ci` branch on top of `debian/experimental` as the upstream-ci branch was getting out-of-sync a little. I've force-pushed the changes, so you'll need to update your local copies before you make any changes to `upstream-ci`.

We now have a much smaller diff again, which is nice (basically only the enabling of log-trace).

Please be aware, that rebasing on top of `debian/experimental` also means, that now `unified` is the new default hierarchy, just in case there are some (new) CI failures.
