### ISSUE TITLE
systemd-nspawn failed to mount tmpfs

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#19976]
**systemd version the issue has been seen with**
 > 249 rc1

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > 5.12.12-300.fc34.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > a running nspawn container

**Unexpected behaviour you saw**
 > 
```
Jun 20 10:31:01 brutus systemd[1]: Failed to start Container mycontainer.
Jun 20 10:31:01 brutus systemd[1]: systemd-nspawn@mycontainer.service: Failed with result 'exit-code'.
Jun 20 10:31:01 brutus systemd[1]: systemd-nspawn@mycontainer.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 10:31:01 brutus systemd-nspawn[3786]: Failed to mount tmpfs (type tmpfs) on /var/lib/machines/mycontainer/tmp (2|4|(1<<24) "mode=1777,size=10%,nr_inodes=400k,uid=496107520,gid=496107520,context=,sys.id:sys.role:systemd.nspawn.container.fs:s0,"): Invalid argument
Jun 20 10:31:01 brutus systemd[1]: Starting Container mycontainer..
```
**Steps to reproduce the problem**
 > The "unexpected behavior i saw above" say's enough

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by doverride** [comment]
In case you don't see it: You wrapped the `context=` argument with `,`

wrong: context=,sys.id:sys.role:systemd.nspawn.container.fs:s0, 
right: context=sys.id:sys.role:systemd.nspawn.container.fs:s0

**Comment by mrc0mmand** [comment]
Looks like this might be caused by cfea7618f28562c053a1ee194108feaa502081ff, /cc @yuwata.

**Comment by yuwata** [comment]
@doverride Thank you for the report! @mrc0mmand Thank you for finding the commit which introduce this issue.

Fix is waiting in #19977. PTAL.

**Comment by bluca** [comment]
I guess we missed it cause we don't have CI jobs with SELinux?

**Comment by mrc0mmand** [comment]
> I guess we missed it cause we don't have CI jobs with SELinux?

We sort of have a daily [Fedora Rawhide SELinux/systemd run](https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-rawhide-selinux/), but it's pretty barebones, so far. I'll try to extend it to cover this scenario as well (among others).
