### ISSUE TITLE
Best way to handle update of existing template instances' definition after updating template definition? 

### ISSUE THREAD

**Issue by czardien** [systemd/systemd#19974]
Hi,

Sorry for the blank issue, this is more of a question I guess and I couldn't find anything close to this in the existing issues, and I went over the docs without being able to find anything relevant.

We define a template: `template@.service` as:

```
[Unit]
Description=template

[Service]
Type=oneshot
RemainAfterExit=False
ExecStart=bash -c "echo Hi %i"
```

...and we start manually an instance as:

```
sudo systemctl start template@instance.service
```

... which works as expected. Later on we edit the `template@.service` definition by adding an `ExecStartPost=` directive: 

```
[Unit]
Description=template

[Service]
Type=oneshot
RemainAfterExit=False
ExecStart=bash -c 'echo Hi %i'
ExecStartPost=bash -c 'echo Goodbye %i'
```

... before running: `systemctl daemon-reload`. When we take a look at the previous instance definition we still see:

```
$ systemctl cat template@instance.service
[Unit]
Description=template

[Service]
Type=oneshot
RemainAfterExit=False
ExecStart=bash -c "echo Hi %i"
```

... and when we run it with: `systemctl run template@instance.service`, we don't get the newly defined template's `ExecStartPost=` called, which is in line with the instance's definition.

From the docs I assume this is expected, as an existing file for this instantiated service exists:

> As mentioned above, a unit may be instantiated from a template file. This allows creation of multiple units from a single configuration file. If systemd looks for a unit configuration file, it will first search for the literal unit name in the file system. If that yields no success and the unit name contains an "@" character, systemd will look for a unit template that shares the same name but with the instance string (i.e. the part between the "@" character and the suffix) removed. Example: if a service getty@tty3.service is requested and no file by that name is found, systemd will look for getty@.service and instantiate a service from that configuration file if it is found.

Is there any way to reflect newly defined template files' definitions onto already launched instance files, aside from calling `systemctl daemon-reload`? 

Is the option of deleting any existing instances for that template after editing it the solution here? Is there a nice CLI way to do so ?

Thank you

Edit: Made the quote from freedesktop prettier

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
