### ISSUE TITLE
bash completions fails with unbound variables when set -u is in effect

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#19987]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-5)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Debian sid

When `set -u` is in effect (which should be perfectly valid), systemd’s bash completion functions fail at least when completing e.g.
```
$ systemctl sta<TAB>
-bash: verb: unbound variable
```
The same at least with all other actions of systemctl, but it could be easily that there are much more variables which are used in an unbound manner.

I think a fix should be rather easy, e.g. when using `${verb}` use `${verb-}` instead which will cause an unset variable `verb` to be expanded to the empty string.

But of course, there might be many more variables which are used in that fashion.

IMO it would make sense to fix any expansions of unbound variables, e.g. `bash-completions` considers such cases a bug: https://github.com/scop/bash-completion/issues/44#issuecomment-632513173

Cheers,
Chris.

**Comment by bluca** [comment]
Is there a way to programmatically check for these errors? If so, we can add it to the CI - right now I've manually tested the verb completions, but if there's no tests it will regress at some point

**Comment by calestyo** [comment]
I personally wouldn't know any. Even if one had a static syntax checker or so (which I don't think exists for bash - or at least I wouldn't have heard about it) it could still give false positives, like when the usage of an unset variable is protected by an outer conditional.
