### ISSUE TITLE
systemd merges deps of mount unit files and /proc/self/mountinfo, leading to surprising results: systemd automatically unmounts manually mounted filesystems [Take #2]

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#19983]
PR https://github.com/systemd/systemd/pull/19322 is supposed to fix issue https://github.com/systemd/systemd/issues/9869 but AFAICS it's not the case.

IIUC StopPropagatedFrom= is supposed to address the aforementioned issue but I fail to see how exactly: as long as the dependency on the wrong device is still included in the mount dependencies, the problem isn't solved.

The fact that the dependency on the device is now edge-triggered doesn't help, it just moves the problem when the wrong device (the one PID1 initially tracked when the generated mount unit was loaded) is being stopped now.

**Comment by fbuihuu** [comment]
Since issue https://github.com/systemd/systemd/issues/9869 had label `v249`, I also put the same label on this issue since both issue are identical.

**Comment by poettering** [comment]
I can't pare this. Please describe remaining problem precisely and provide a reproducer.

**Comment by fbuihuu** [comment]
Let's say that fstab has an entry for device `dev-A` which should be mounted on path  /my/mount/unit.

The user unmounts `dev-A` and manually mounts device `dev-B` on /my/mount/unit.

At that point `my-mount-unit.mount` has dependencies on 2 different devices: `dev-A` and `dev-B`.

If for any reason `dev-A` is unplugged,  `my-mount-unit.mount` will be stopped and thus `dev-B` will be incorrectly unmounted.

So as long as `my-mount-unit.mount` will keep a dependency on `dev-A`, the problem remains, no ?

**Comment by fbuihuu** [comment]
Here's a test case:

```
# systemctl --version
systemd 248 (248-1661-ge4948b0)

# tail -n1 /etc/fstab
/dev/mapper/vdb /mnt  ext4 defaults 1 2

# cat /etc/crypttab
vdb  UUID=289d7e97-deac-4769-bb7f-991e4c66814a none discard
vdc  UUID=ffda7bac-7437-46d6-a01a-512930f64041 none discard

# systemctl status mnt.mount 
● mnt.mount - /mnt
     Loaded: loaded (/etc/fstab; generated)
     Active: active (mounted) since Mon 2021-06-21 14:47:48 CEST; 3min 10s ago
      Where: /mnt
       What: /dev/mapper/vdb
      [...]

# umount /mnt 
# mount /dev/mapper/vdc /mnt/
# systemctl status mnt.mount 
● mnt.mount - /mnt
     Loaded: loaded (/etc/fstab; generated)
     Active: active (mounted) since Mon 2021-06-21 14:51:40 CEST; 4s ago
      Where: /mnt
       What: /dev/mapper/vdc
      [...]

# systemctl stop systemd-cryptsetup@vdb.service 
# systemctl status mnt.mount 
○ mnt.mount - /mnt
     Loaded: loaded (/etc/fstab; generated)
     Active: inactive (dead) since Mon 2021-06-21 14:53:02 CEST; 2s ago
      Where: /mnt
       What: /dev/mapper/vdb
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
        CPU: 3ms

Jun 21 14:53:02 vm-tumbleweed systemd[1]: Unmounting /mnt...
Jun 21 14:53:02 vm-tumbleweed systemd[1]: mnt.mount: Deactivated successfully.
Jun 21 14:53:02 vm-tumbleweed systemd[1]: Unmounted /mnt.

```

**Comment by fbuihuu** [comment]
@poettering ping.

**Comment by frittentheke** [comment]
I believe this issue here goes back to the issue https://github.com/systemd/systemd/issues/1741 (and fixing it would likely close this old and heatedly discussed bug :see_no_evil: ).

See my post to the ML about it: https://lists.freedesktop.org/archives/systemd-devel/2021-July/046671.html

**Comment by yuwata** [comment]
@fbuihuu Could you test and review #23367?
