### ISSUE TITLE
tests: testing of locale-gen autorun is disabled due to bionic-ppc64el issues

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#19993]
testing for localed auto-runs of locale-gen is disabled because on bionic-ppc64el it fails:

```
autopkgtest [20:46:01]: test localed-locale: [-----------------------
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
locale 'de_DE.UTF-8' not available
de_DE.UTF-8 UTF-8
locale 'de_DE.UTF-8' not available
de_DE.UTF-8 UTF-8
FAIL: expected: '0' actual: '1'
```

Discussion is ongoing to figure out what the problem is on ppc64el:
https://salsa.debian.org/systemd-team/systemd/-/merge_requests/116#note_245439

Keeping this open so that we don't forget to revert this:

https://salsa.debian.org/systemd-team/systemd/-/commit/c7ac8ffa830b0b672396a8be65390a5e981fc8eb

**Comment by mbiebl** [comment]
For the curious, this turned out to be an issue in gzip:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890279 which makes localedef fail when run in systemd-localed context with MemoryDenyWriteExecute=yes

**Comment by bluca** [comment]
A new version of gzip was added by @ddstreet on the systemd-ci ppa, so I have re-enabled the test
