### ISSUE TITLE
systemd doesn't start units in the default target

### ISSUE THREAD

**Issue by Pesa** [systemd/systemd#20003]
**systemd version the issue has been seen with**
 > v248.3

`systemctl --version`
 > systemd 248 (248)
+PAM -AUDIT -SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 +LZ4 +XZ -ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid

**Used distribution**
 > Gentoo Linux

**Linux kernel version used** (`uname -a`)

 > `Linux gentoo-amd64-dev 5.7.14-gentoo #2 SMP Thu Aug 13 02:17:28 CEST 2020 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux`

**Expected behaviour you didn't see**
 > systemd boots normally into `multi-user.target` (the default target on this system) and starts all the units pulled in by that target. This was working fine before I upgraded to v248.3 (from v247.2).

**Unexpected behaviour you saw**
 > systemd claims it reached `multi-user.target` but doesn't actually start any units in that target. Units in `basic.target` and all previous targets are started correctly.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
$ systemctl get-default
multi-user.target

$ ls -l /etc/systemd/system/default.target
lrwxrwxrwx 1 root root 37 Apr 29 05:46 /etc/systemd/system/default.target -> /lib/systemd/system/multi-user.target

$ journalctl ...
...
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Finished Flush Journal to Persistent Storage.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Finished Create Static Device Nodes in /dev.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Local File Systems (Pre).
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Local File Systems.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Rebuild Dynamic Linker Cache being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Starting Create Volatile Files and Directories...
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Rule-based Manager for Device Events and Files being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Finished Create Volatile Files and Directories.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Rebuild Journal Catalog being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Condition check resulted in Update is Completed being skipped.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Starting Update UTMP about System Boot/Shutdown...
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Finished Update UTMP about System Boot/Shutdown.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target System Initialization.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Started Daily man-db regeneration.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Started Daily Cleanup of Temporary Directories.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Timers.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Listening on D-Bus System Message Bus Socket.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Listening on OpenSSH Server Socket.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Listening on UUID daemon activation socket.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Sockets.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Basic System.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: System is tainted: cgroupsv1
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Reached target Multi-User System.
Jun 23 09:26:57 gentoo-amd64-dev systemd[1]: Startup finished in 106ms.

$ systemctl list-jobs
No jobs running.

$ systemctl status
● gentoo-amd64-dev
    State: running
     Jobs: 0 queued
   Failed: 0 units
```

Note: The above output is with the hybrid cgroup hierarchy. I've also tried with the unified hierarchy and got the same result.

If I manually run `systemctl isolate multi-user.target` then all the enabled units are started as expected.

**Comment by Pesa** [comment]
The symptoms look very similar to #13609

**Comment by poettering** [comment]
@Pesa, does #20004 fix the issue for you?

**Comment by Pesa** [comment]
No. I've tried with 249-rc2 but unfortunately it does not solve the problem.

**Comment by keszybz** [comment]
Please provide the full debug log from boot (`systemd.log-level=debug` on the kernel command line). We now log about what unit files are loaded quite extensively, this should help debug the issue.

**Comment by Pesa** [comment]
This is a `systemd-nspawn` container. What's the equivalent of that? Should I pass `-E SYSTEMD_LOG_LEVEL=debug` to `systemd-nspawn`?

**Comment by poettering** [comment]
just pass it on the nspawn cmdline, it's consdered the kernel command line for the init system in the nspawn container

**Comment by andir** [comment]
I believe I am seeing the same / a very similar error while working on the NixOS upgrade to v249.

In our case I see several units (even outside of the `multi-user.target`) not being attempted. Including the `getty@tty0.service`. When putting a unit into the `local-fs.target` that calls `systemctl start mutli-user.target` after a couple of seconds  

After a couple of hours of staring at VM & nspawn output I am not entirely sure why the units in the `multi-user.target` are never started.

Below is a gist with a boot log of an nspawn container that is supposed to start NGINX as part of `multi-user.target`. The system boot up and sits there but hasn't really tried to spawn any of the services that are part of the target. I also included a list of the wanted units and a copy of the NGINX unit but neither look out of the ordinary from my perspective.
https://gist.github.com/andir/ba4eea5a69c6ad80b19a40a3e1f42f61


Unfortunately we are still have to apply a couple of patches for systemd to work on NixOS. Most (if not all) are related to path handling (e.g. no /bin, /usr etc..). I can see why this puts us into a situation where we are on our own so I don't have hard feelings if you can't help.  That being said the patches that I am currently applying can be found here: https://github.com/andir/nixpkgs/tree/systemdv249/pkgs/os-specific/linux/systemd

**Comment by keszybz** [comment]
My guess would be that `default.target` does is not the same as `multi-user.target`:
```
unit_file_build_name_map: linked unit file: /etc/systemd/system/default.target → /nix/store/9vb2q104s578yikz46jkkd5sjdlqkgb7-system-units/multi-user.target
```
What does `systemctl show -p Wants,Requires multi-user.target default.target` say?

--

It would be nice to log all the aliases of default target in `Activating default unit: default.target`.

**Comment by andir** [comment]
I think you are right.

```
$ systemctl show -p Wants,Requires multi-user.target default.target
Requires=basic.target
Wants=swap.target getty.target backdoor.service nss-lookup.target network-online.target systemd-ask-password-wall.path machines.target network-setup.service local-fs.target systemd-user-sessions.service reload-systemd-vconsole-setup.service dhcpcd.service remote-fs.target systemd-tmpfiles-setup-dev.service resolvconf.service systemd-modules-load.service nss-user-lookup.target systemd-logind.service systemd-sysctl.service
Requires=basic.target
Wants=
```

You might be right about them being two distinct target even thought they are all symlinked to the same file.. This used to work until v248/v249 (coming from v247). I noticed that systemd now doesn't follow all the symlinks anymore when looking at `systemctl status <unit>` whereas previously it would always list the final path (after following all(?) symlinks).

**Comment by keszybz** [comment]
Yes, as soon as the symlink chain leaves one of the unit directories, we stop following. Any names of symlinks within the search paths become aliases, and the last name within the search directories becomes the unit name name. This changed in the rework that was done to clarify/fix how we handle aliases. I wasn't aware of the NixOS case at all — indeed this changes how units are interpreted. But in most other cases it makes things work better, because we finally have a consistent story about what unit symlinks mean. 

Just change `/etc/systemd/system/default.target → /nix/store/9vb2q104s578yikz46jkkd5sjdlqkgb7-system-units/multi-user.target` to be a symlink to `multi-user.target`.

**Comment by andir** [comment]
> Yes, as soon as the symlink chain leaves one of the unit directories, we stop following. Any names of symlinks within the search paths become aliases, and the last name within the search directories becomes the unit name name. This changed in the rework that was done to clarify/fix how we handle aliases. I wasn't aware of the NixOS case at all — indeed this changes how units are interpreted. But in most other cases it makes things work better, because we finally have a consistent story about what unit symlinks mean.
> 
> Just change `/etc/systemd/system/default.target → /nix/store/9vb2q104s578yikz46jkkd5sjdlqkgb7-system-units/multi-user.target` to be a symlink to `multi-user.target`.

Looking closer into this that is actually the case in our default configuration. The problem could be related to `/etc/systemd/system` already being a symlink? We symlink the current set of active units there after building that paths.

If we look at another example within an nspawn container:

```
$ readlink -f /etc/systemd/system
/nix/store/sd7rn0v8sx5f82kw827v5dlzjdhnmfzg-system-units/
$ ls -la /nix/store/sd7rn0v8sx5f82kw827v5dlzjdhnmfzg-system-units/default.target
lrwxrwxrwx 21 root root 17 Jan  1  1970 /nix/store/sd7rn0v8sx5f82kw827v5dlzjdhnmfzg-system-units/default.target -> multi-user.target
```

Yet we see the following when booting the container with the log level set to debug:
```
unit_file_build_name_map: linked unit file: /etc/systemd/system/default.target → /nix/store/sd7rn0v8sx5f82kw827v5dlzjdhnmfzg-system-units/multi-user.target
```

With `systemctl show -p Wants,Requires multi-user.target default.target` we have seen that the two targets are apparently not the same, correct? Yet when I inject a unit into the boot process that sleeps for a while and then lists the dependencies of the multi-user.target and tells me what the default target is I get this:

```
[   19.761553] foobarbazfoobarbaz-start[654]: + /nix/store/xpk8wddr1hbpkhkdd68lhpr6baadx27k-systemd-249.3/bin/systemctl list-jobs
[   19.820539] foobarbazfoobarbaz-start[676]: No jobs running.
[   19.823739] foobarbazfoobarbaz-start[654]: + /nix/store/xpk8wddr1hbpkhkdd68lhpr6baadx27k-systemd-249.3/bin/systemctl list-dependencies multi-user.target
[   20.345597] foobarbazfoobarbaz-start[677]: multi-user.target
[   20.346020] foobarbazfoobarbaz-start[677]: ○ ├─backdoor.service
[   20.346436] foobarbazfoobarbaz-start[677]: ○ ├─dhcpcd.service
[   20.346847] foobarbazfoobarbaz-start[677]: ○ ├─network-setup.service
[   20.347276] foobarbazfoobarbaz-start[677]: ○ ├─reload-systemd-vconsole-setup.service
[   20.347956] foobarbazfoobarbaz-start[677]: ○ ├─resolvconf.service
[   20.349719] foobarbazfoobarbaz-start[677]: ○ ├─systemd-ask-password-wall.path
[   20.350583] foobarbazfoobarbaz-start[677]: ○ ├─systemd-logind.service
[   20.352271] foobarbazfoobarbaz-start[677]: ● ├─systemd-modules-load.service
[   20.354028] foobarbazfoobarbaz-start[677]: ● ├─systemd-sysctl.service
[   20.355113] foobarbazfoobarbaz-start[677]: ○ ├─systemd-tmpfiles-setup-dev.service
[   20.356182] foobarbazfoobarbaz-start[677]: ○ ├─systemd-user-sessions.service
[   20.357068] foobarbazfoobarbaz-start[677]: ● ├─basic.target
[   20.357705] foobarbazfoobarbaz-start[677]: ● │ ├─-.mount
[   20.358299] foobarbazfoobarbaz-start[677]: ● │ ├─audit.service
[   20.358968] foobarbazfoobarbaz-start[677]: ○ │ ├─tmp.mount
[   20.359599] foobarbazfoobarbaz-start[677]: ● │ ├─paths.target
[   20.360284] foobarbazfoobarbaz-start[677]: ● │ ├─slices.target
[   20.360929] foobarbazfoobarbaz-start[677]: ● │ │ ├─-.slice
[   20.361606] foobarbazfoobarbaz-start[677]: ● │ │ └─system.slice
[   20.362291] foobarbazfoobarbaz-start[677]: ● │ ├─sockets.target
[   20.362865] foobarbazfoobarbaz-start[677]: ● │ │ ├─nix-daemon.socket
[   20.363616] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-coredump.socket
[   20.364245] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journald-audit.socket
[   20.364962] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journald-dev-log.socket
[   20.365780] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journald.socket
[   20.366526] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-udevd-control.socket
[   20.367278] foobarbazfoobarbaz-start[677]: ● │ │ └─systemd-udevd-kernel.socket
[   20.368005] foobarbazfoobarbaz-start[677]: ● │ ├─sysinit.target
[   20.369622] foobarbazfoobarbaz-start[677]: ● │ │ ├─dev-hugepages.mount
[   20.377144] foobarbazfoobarbaz-start[677]: ● │ │ ├─dev-mqueue.mount
[   20.377664] foobarbazfoobarbaz-start[677]: ● │ │ ├─firewall.service
[   20.378135] foobarbazfoobarbaz-start[677]: ● │ │ ├─kmod-static-nodes.service
[   20.378614] foobarbazfoobarbaz-start[677]: ● │ │ ├─sys-fs-fuse-connections.mount
[   20.379144] foobarbazfoobarbaz-start[677]: ● │ │ ├─sys-kernel-config.mount
[   20.379616] foobarbazfoobarbaz-start[677]: ● │ │ ├─sys-kernel-debug.mount
[   20.380102] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-ask-password-console.path
[   20.380618] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journal-catalog-update.service
[   20.381226] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journal-flush.service
[   20.385971] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-journald.service
[   20.386519] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-modules-load.service
[   20.387035] foobarbazfoobarbaz-start[677]: ○ │ │ ├─systemd-pstore.service
[   20.387501] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-random-seed.service
[   20.388002] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-sysctl.service
[   20.388476] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-tmpfiles-setup.service
[   20.389045] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-udev-trigger.service
[   20.389535] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-udevd.service
[   20.392753] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-update-done.service
[   20.393255] foobarbazfoobarbaz-start[677]: ● │ │ ├─systemd-update-utmp.service
[   20.393759] foobarbazfoobarbaz-start[677]: ● │ │ ├─cryptsetup.target
[   20.394217] foobarbazfoobarbaz-start[677]: ● │ │ ├─local-fs.target
[   20.394738] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─-.mount
[   20.395169] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─foobarbazfoobarbaz.service
[   20.395923] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─nix-.ro\x2dstore.mount
[   20.396863] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─nix-.rw\x2dstore.mount
[   20.397738] foobarbazfoobarbaz-start[677]: ○ │ │ │ ├─systemd-fsck-root.service
[   20.398401] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─systemd-remount-fs.service
[   20.402395] foobarbazfoobarbaz-start[677]: ● │ │ │ ├─tmp-shared.mount
[   20.403356] foobarbazfoobarbaz-start[677]: ● │ │ │ └─tmp-xchg.mount
[   20.404002] foobarbazfoobarbaz-start[677]: ● │ │ ├─swap.target
[   20.404774] foobarbazfoobarbaz-start[677]: ● │ │ └─veritysetup.target
[   20.405514] foobarbazfoobarbaz-start[677]: ● │ └─timers.target
[   20.406307] foobarbazfoobarbaz-start[677]: ● │   └─systemd-tmpfiles-clean.timer
[   20.407024] foobarbazfoobarbaz-start[677]: ○ ├─getty.target
[   20.407629] foobarbazfoobarbaz-start[677]: ○ │ ├─getty@tty1.service
[   20.408386] foobarbazfoobarbaz-start[677]: ○ │ ├─serial-getty@hvc0.service
[   20.409323] foobarbazfoobarbaz-start[677]: ○ │ └─serial-getty@ttyS0.service
[   20.409895] foobarbazfoobarbaz-start[677]: ● ├─local-fs.target
[   20.410302] foobarbazfoobarbaz-start[677]: ● │ ├─-.mount
[   20.410732] foobarbazfoobarbaz-start[677]: ● │ ├─foobarbazfoobarbaz.service
[   20.411207] foobarbazfoobarbaz-start[677]: ● │ ├─nix-.ro\x2dstore.mount
[   20.411678] foobarbazfoobarbaz-start[677]: ● │ ├─nix-.rw\x2dstore.mount
[   20.412135] foobarbazfoobarbaz-start[677]: ○ │ ├─systemd-fsck-root.service
[   20.412596] foobarbazfoobarbaz-start[677]: ● │ ├─systemd-remount-fs.service
[   20.413084] foobarbazfoobarbaz-start[677]: ● │ ├─tmp-shared.mount
[   20.413503] foobarbazfoobarbaz-start[677]: ● │ └─tmp-xchg.mount
[   20.413933] foobarbazfoobarbaz-start[677]: ○ ├─machines.target
[   20.414359] foobarbazfoobarbaz-start[677]: ○ ├─network-online.target
[   20.414802] foobarbazfoobarbaz-start[677]: ○ │ └─dhcpcd.service
[   20.415223] foobarbazfoobarbaz-start[677]: ○ ├─nss-lookup.target
[   20.415647] foobarbazfoobarbaz-start[677]: ○ │ └─nscd.service
[   20.416069] foobarbazfoobarbaz-start[677]: ○ ├─nss-user-lookup.target
[   20.416499] foobarbazfoobarbaz-start[677]: ○ │ └─nscd.service
[   20.416921] foobarbazfoobarbaz-start[677]: ○ ├─remote-fs.target
[   20.417331] foobarbazfoobarbaz-start[677]: ● └─swap.target
[   20.417754] foobarbazfoobarbaz-start[654]: + /nix/store/xpk8wddr1hbpkhkdd68lhpr6baadx27k-systemd-249.3/bin/systemctl get-default
[   20.418481] foobarbazfoobarbaz-start[678]: multi-user.target
```

So apparently the default target is really `multi-user.target` and not the default.target that we have seen before?

**Comment by poettering** [comment]
@Pesa is this still an issue? If so, can you provide the requested logs? Otherwise I guess we should close the issue...

**Comment by poettering** [comment]
@Pesa do you have any weird symlink setup for the dirs in question?

**Comment by Pesa** [comment]
Yes this is still an issue with v249.4.

I don't know what exactly you mean by "weird symlink"? `/lib` is a symlink to `/lib64` on my system, but I don't think that's weird?

```
$ ls -l /etc/systemd/system/default.target
lrwxrwxrwx 1 root root 37 Apr 29 05:46 /etc/systemd/system/default.target -> /lib/systemd/system/multi-user.target
$ realpath /lib/systemd/system/multi-user.target
/lib64/systemd/system/multi-user.target
```

```
$ systemctl show -p Wants,Requires multi-user.target default.target
Requires=basic.target
Wants=systemd-networkd.service systemd-update-utmp-runlevel.service dbus.service remote-fs.target systemd-ask-password-wall.path systemd-logind.service machines.target systemd-user-sessions.service getty.target

Requires=basic.target
Wants=
```

I'll post the debug logs tomorrow.

**Comment by poettering** [comment]
/lib is a symlink to /lib64? on which planet does that make any sense? In that case #20479 is almost certainly your fix.

**Comment by poettering** [comment]
Ah, I see now that this is Gentoo. Yeah, gentoo is super confused regarding /usr merge and multi-arch.
