### ISSUE TITLE
standalone sysusers binary depends on libcrypt

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#20006]
While testing `-Dstandalone-binaries=true`, I noticed that `systemd-sysusers.standalone` has a dependency on libcrypt:

```
$ objdump -x systemd-sysusers.standalone | grep NEEDED
  NEEDED               libcrypt.so.1
  NEEDED               libselinux.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

This dependency appears to be superfluous from a cursory glance.

**Comment by poettering** [comment]
We support hashing passwords and writing them into shadow for you. For that we call `crypt_r` which is from libcrypt/libxcrypt.

libcrypt is part of glibc, are you saying that it is not installed anyway on debian?

(note that libcrypt != libcrypto. The former is a password hashing lib that is part of glibc, the latter is openssl)

**Comment by mbiebl** [comment]
Ah, so it is `hash_password()` which is pulling in this dependency?
When searching for "crypt" in sysusers.c I saw bits about decrypted_image which was ifdeffed out on standalone binaries, which probably led me to believe the dependency was not necessary.

libcrypt in Debian is no longer provided by glibc directly anymore afaics. The libcrypt1 binary package is built from libxcrypt. It is installed by default. https://tracker.debian.org/pkg/libxcrypt

**Comment by mbiebl** [comment]
Closing as per @poettering 's explanation
