### ISSUE TITLE
Managed netns 

### ISSUE THREAD

**Issue by j16sdiz** [systemd/systemd#2000]
I am trying to run a service in separate netns, use the same host filesystem.
nspawn does not supporting running in `/`.

What I want is running a service with totally different ip routing / addressing. 
Seems setting up netns manually is the only current option, right?
Is nspawn / networkd going to support configs like this?

**Comment by richardmaw-codethink** [comment]
If you don't want to have a separate root, then http://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateNetwork= may be of more use, depending on whether you need your service to then be able to connect out.

Have you tried http://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--share-system ?

**Comment by poettering** [comment]
This is not a support forum, but a bug and issue tracker. Please send questions like yours to the mailing list.

@richardmaw-codethink please don't respond to such misfiled support requests, I'd like to avoid that this becomes acceptable, and people spam the bug tracker with such support requests.

**Comment by j16sdiz** [comment]
@poettering , fyi i have asked on irc and they directed me here.

**Comment by poettering** [comment]
@j16sdiz yeah, sorry for the confusion, probably somebody misdirected you there. Generally, support questions are fine on IRC (for quick reactions, if you are lucky), or the ML (for the rest), but the bug tracker is really just a bug tracker.
