### ISSUE TITLE
Mount encrypted swap partitions with the correct partition type

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#20019]
**Is your feature request related to a problem? Please describe.**

I'm trying to move to a setup where I have no more hardcoded partition names into my `cmdline`.

This aligns very well with the [Discoverable Partitions Specification](https://systemd.io/DISCOVERABLE_PARTITIONS/), and by simply following it, I'm 90% there.

For most of the auto-discovered partitions, if the partition is LUKS encrypted, `systemd-gpt-auto-generator(8)` will handle unlocking them and accessing the volume inside of it.

However, for a `swap` partition, even if the partition type is set to `0657fd6d-a4ab-43c4-84e5-0933c84b4f4f` (the appropriate type), the partition is not unlocked:

```
# systemctl status dev-nvme0n1p3.swap
× dev-nvme0n1p3.swap - Swap Partition
     Loaded: loaded (/run/systemd/generator.late/dev-nvme0n1p3.swap; generated)
     Active: failed (Result: exit-code) since Thu 2021-06-24 17:25:36 CEST; 2h 42min ago
       What: /dev/nvme0n1p3
       Docs: man:systemd-gpt-auto-generator(8)
        CPU: 1ms

Jun 24 17:25:36 victory swapon[370]: swapon: /dev/nvme0n1p3: read swap header failed
Jun 24 17:25:36 victory systemd[1]: dev-nvme0n1p3.swap: Swap process exited, code=exited, status=255/EXCEPTION
Jun 24 17:25:36 victory systemd[1]: dev-nvme0n1p3.swap: Failed with result 'exit-code'.
Jun 24 17:25:36 victory systemd[1]: Failed to activate swap Swap Partition.
```

It would seem that this specific partition type (and only this one) won't de-crypt the partition.

**Describe the solution you'd like**

Partition should be unlocked with LUKS much the same was as other partitions (e.g.: `/` or `/usr`).

**Describe alternatives you've considered**

Using an unencrypted partition is a huge leak: the system will leave all kinds of sensitive material when powered off When suspending-to-disk, the entire RAM is copied into it.

Hardcoding the UUID into the `cmdline` defeats the purpose of the Discoverable Partitions Specification.

**The systemd version you checked that didn't have the feature you are asking for**

`systemd 248 (248.3-2-arch)`

**Comment by poettering** [comment]
Yeah, automatically doing cryptsetup for encrypted swap is missing in gpt-auto. It's not difficult to do, it's just that noone spent the time on it so far.

**Comment by WhyNotHugo** [comment]
I assumed it would not be very difficult too. I looked into `gpt-auto-generator.c` and `generator.c`, but it seems to be a bit beyond me.

I can't quite figure out what determines if partitions (e.g.: `/usr`) are LUKS encrypted or not. I may just have to leave it in the hands of those more adept at C :sweat_smile:

**Comment by WhyNotHugo** [comment]
My workarounds for this have been flaky, so I'm wanting to give this another shot.

I'm thinking that in `gpt-auto-generator.c`, function `add_swap()` would need to:

- Read the partition, and check if there's a LUKS header.
- If the partition is missing, return non-zero.
- If there is a LUKS header, create two units:
  -  `systemd-cryptsetup@swap.service` that basically does `/usr/lib/systemd/systemd-cryptsetup attach 'swap' '/dev/disk/by-uuid/UUID_OF_PARTITION' '' ''`. I guess using `add_cryptsetup` does all the hard lifting here.
  - `sway.swap` that's basically a `systemd.swap(5)` unit with `What=/dev/mapper/swap`.
- If there's no LUKS header, do the same that's done right now.

Does that sound like an approach that would be acceptable?

Is there some existing function that would do the "check if this looks like a LUKS partition" part?

**Comment by cmurf** [comment]
> I can't quite figure out what determines if partitions (e.g.: `/usr`) are LUKS encrypted or not.

libblkid shows the magic of a LUKS partition is `crypto_LUKS`
