### ISSUE TITLE
nspawn does not support container directories that are symlinks with -M

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2001]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805785

machinectl start #containername# fails when /var/lib/machines/#containername#
is symbolic link to other folder

```
systemd[1]: Starting Container jee...
systemd-nspawn[2798]: Failed to open root file system: Too many levels of
symbolic links
systemd[1]: systemd-nspawn@jee.service: Main process exited, code=exited,
status=1/FAILURE
systemd[1]: Failed to start Container jee.
systemd[1]: systemd-nspawn@jee.service: Unit entered failed state.
systemd[1]: systemd-nspawn@jee.service: Failed with result 'exit-code'.
```

```
ls -la /var/lib/machines
drwx------  2 root root 4096 Ноя 22 14:55 .
drwxr-xr-x 77 root root 4096 Ноя 22 14:06 ..
lrwxrwxrwx  1 root root   26 Ноя 22 14:24 jee ->
/home/#my_home_folder#/containers/jee
```

**Comment by crequill** [comment]
Same problem here with systemd 228
For me it's not a RFE, it's a BUG: this was working with systemd 218

**Comment by juhokuu** [comment]
Yes, it did indeed work in previous versions. I was relying on this behaviour on a couple of servers and it's also something that is outlined in the `machinectl` man page under _Files and directories_:

> Machine images are preferably stored in /var/lib/machines/, but are also searched for in /usr/local/lib/machines/ and /usr/lib/machines/. For compatibility reasons, the directory /var/lib/container/ is searched, too. Note that images stored below /usr are always considered read-only. **It is possible to symlink machines images from other directories into /var/lib/machines/ to make them available for control with machinectl.**

**Comment by teburd** [comment]
I just ran in to this myself after reading the man page on how I could do exactly what apparently does not work

**Comment by Ram-Z** [comment]
Same issue. It seems unrelated to `-M`.

```
17:55 ramsi@fractal
❱❱ sudo mkdir container
17:55 ramsi@fractal
❱❱ sudo pacstrap -cd container systemd
[...]
❱❱ sudo systemd-nspawn -b -D container                                                                                                                          ~
Spawning container container on /home/ramsi/container.
Press ^] three times within 1s to kill container.
systemd 228 running in system mode. (+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Chakra!

Set hostname to <localhost>.
display-manager.service: Cannot add dependency job, ignoring: Unit display-manager.service failed to load: No such file or directory.
[...]
Chakra 4.5.0-1-CHAKRA (console)
localhost login: ^]^]^]

17:58 ramsi@fractal
1❱❱ ln -s container symlink                                                                                                                                     ~
17:58 ramsi@fractal
❱❱ sudo systemd-nspawn -b -D symlink                                                                                                                            ~
Spawning container symlink on /home/ramsi/symlink.
Press ^] three times within 1s to kill container.
Failed to open root file system: Too many levels of symbolic links
```

**Comment by greg-hydrogen** [comment]
agreed... this is a regression from previous versions, is there any way we can get the RFE tag removed and the BUG tag added, or do we need to create a new issue?

**Comment by gnyers** [comment]
a possible workaround for anyone interested:  bind mounting the target directory seems to work:
`mount --bind /containerstore /var/lib/machines/`
