### ISSUE TITLE
Udev rule with ATTRS{inquiry}=="*" not applied although the attr exists (v248 regression)

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#20025]
**systemd version the issue has been seen with**
 > v248

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux susetest 5.12.10-5-default #1 SMP Fri Jun 11 05:05:06 UTC 2021 (b92eaf7) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
**Unexpected behaviour you saw**

openQA noticed that with systemd v248, `/dev/sr0` in QEMU got a new device link which wasn't there with systemd v246: `/dev/disk/by-id/scsi-SQEMU_QEMU_CD-ROM_cd0`. With v246, only `/dev/disk/by-id/scsi-0QEMU_QEMU_CD-ROM_cd0` appears. By looking at the udev log, it was discovered that the difference is caused by the way a rule from `sg3_utils` is executed:

https://github.com/hreinecke/sg3_utils/blob/627b12990c899934dfb34bedd349408884d8f61b/scripts/55-scsi-sg3_id.rules#L53-L55

```
SUBSYSTEMS=="scsi", ATTRS{inquiry}=="*", KERNELS=="[0-9]*:*[0-9]", \
  ENV{.SYSFS_PATH}="$sys/class/scsi_device/$id/device"
ENV{.SYSFS_PATH}=="", GOTO="sg_inquiry"
```

With systemd < 248, `ATTRS{inquiry}=="*"` is true thus the action is executed and the `GOTO` not taken.
With systemd 248, `ATTRS{inquiry}=="*"` is false and the `GOTO` is taken.

I guess this condition is there to check for existence of the attribute.

The `inquiry` attribute has embedded `00` bytes:

```
susetest:~ # hexdump -C /sys/devices/pci0000:00/0000:00:0b.0/host8/target8:0:0/8:0:0:0/inquiry
00000000  05 80 05 12 1f 00 00 12  51 45 4d 55 20 20 20 20  |........QEMU    |
00000010  51 45 4d 55 20 43 44 2d  52 4f 4d 20 20 20 20 20  |QEMU CD-ROM     |
00000020  32 2e 35 2b                                       |2.5+|
00000024
```

This behaviour change was caused by (mostly harmless looking) 2a394d0bf2f0afd8b9ed5faeb33f23459e3c6504, because it stopped passing `&size` to `read_full_virtual_file`, which makes it return `EBADMSG` when the read data contains `00`.

If this is the expected behaviour, is there a better way to check for existence of an attribute?

(CC @fbuihuu)

**Comment by yuwata** [comment]
Fix is waiting in #20039.
