### ISSUE TITLE
Incorrect documentation regarding DynamicUser and StateDirectory

### ISSUE THREAD

**Issue by dgcampea** [systemd/systemd#20037]
Under `man systemd.exec` regarding `RuntimeDirectory=` (or https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=)

> If DynamicUser= is used in conjunction with StateDirectory=, the logic for CacheDirectory= and LogsDirectory= is slightly altered: the directories are created below /var/lib/private,
           /var/cache/private and /var/log/private, respectively, which are host directories made inaccessible to unprivileged users, which ensures that access to these directories cannot be gained
           through dynamic user ID recycling. Symbolic links are created to hide this difference in behaviour. Both from perspective of the host and from inside the unit, the relevant directories hence
           always appear directly below /var/lib, /var/cache and /var/log.

When `DynamicUser=` is used, _CacheDirectory, StateDirectory_ and _LogsDirectory_ are created under `/var/*/private` irrespective of `StateDirectory=` usage.
Earlier commits https://github.com/systemd/systemd/commit/fdfcb946315a119c5201f1223a8c983e2df3c25c and https://github.com/systemd/systemd/commit/e9dd6984076389e8cfa15b72bc62187544e49b61 suggest some misinterpretation might have occured when they got reworded.

**Comment by bluca** [comment]
Can you send a PR to reword it?
