### ISSUE TITLE
multiseat support on the same graphics card

### ISSUE THREAD

**Issue by sbourdeauducq** [systemd/systemd#20040]
**Is your feature request related to a problem? Please describe.**
Easy multiseat setup with systemd is very nice, but one major limitation is requiring one physical graphics card per seat. Modern cards commonly have 3 or 4 video outputs, but only one can be used in multiseat setups currently. And, besides the obvious graphics card and PCIe slot cost aspect, the reality of most computer hardware is that having niche configurations (such as installing multiple GPUs) tickles BIOS/hardware bugs. For example, the built-in Ethernet on the ASUS Pro-WS-X570-ACE motherboard can break down when two GPUs are installed. So for small setups (<= 4 seats) it would be good to avoid having more than one graphics card.

**Describe the solution you'd like**
``loginctl`` should be able to accept a graphics output specification (e.g. ``/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1``) instead of a graphics card specification (e.g. ``/sys/devices/pci0000:00/0000:00:02.0/drm/card0``).

**Describe alternatives you've considered**
https://help.ubuntu.com/community/MultiseatOneCard which is convoluted, and Xephyr is old and probably has performance issues.

**The systemd version you checked that didn't have the feature you are asking for**
247

**Comment by poettering** [comment]
humm, this is an access control issue. I doubt the kernel exposes separate device nodes with different sets of access permissions for the different output ports. hence there is simply no infrastructure for this in the kernel to my knowledge, and we can't make up what isn't there from userspace.

**Comment by poettering** [comment]
or to say this differently: if the kernel driver maintainers add infra to expose separate device nodes for the different ports with proper access control, and isolated access to graphics memory we can certainly add support for that to logind as well. But without that t would be a security nightmare.

I'll close this. Please work with the kernel DRM people to add support for this in the kernel drivers, and then we can look into supporting this from userspace too.

**Comment by tleydxdy** [comment]
Is it possible to implement this for two users that are mutually trusting? (e.g. they both have sudo rights/in video group/or whatever other means of signaling nessesary). if the users could access the video device regardless of multiseat then the security is no longer an concern.
