### ISSUE TITLE
split up systemd/sysusers.d/systemd.conf.in

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#20044]
Hey there.

This is because of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990349 .

Right now, Debian creates the various systemd-* users in the maintainer scripts from the respective packages (e.g. systemd, systemd-timesyncd and so on)... (but this might change as Michael Biebl indicated in the bug above).

However, it ships `systemd/sysusers.d/systemd.conf` in the systemd (main) package, so effectively, even if systemd-timesyncd isn't installed, the user still gets created for no reason.
Same with systemd-coredump.

In the above ticket I've asked whether they could simply split up `systemd/sysusers.d/systemd.conf` and ship each part in the respective package, not knowing that this is actually based on this upstream file (`systemd/sysusers.d/systemd.conf.in`).

So Michael asked in the bug, that I might ask systemd upstream, whether they see a point in this and could split up the file, so it would be easier for distros to pick that up.

Thanks,
Chris.

**Comment by keszybz** [comment]
The effect of creating the user when not needed is really tiny. But I agree that it's more elegant to have the user declared in the package that uses it. At least in Fedora this will result in virtual `Provides:user(foo)` to be attached to the right package (while right now it is attached to the main package that provides the sysusers.d file). So… please submit a PR.

**Comment by calestyo** [comment]
I could of course make a PR, but how far would you want to have it split up? Really one for each user... or should there be some set of "core" users which are always there?

**Comment by keszybz** [comment]
Each of the optional blocks in `systemd.conf.in` should get its own file.

**Comment by calestyo** [comment]
I made a PR, but please double-check it thoroughly, especially what I've edited in the `meson.build` since I don't really have that much idea of it.

Also not that I've left in the stuff like `{% if ENABLE_OOMD %}` in the respective `systemd-*.conf.in`, but maybe these don't make sense anymore, when there the file is only included by the build system, when that feature is enabled.
Just ask if I should revise the PR accordingly.

Also, I did tidy up some white space.

**Comment by mbiebl** [comment]
> Also not that I've left in the stuff like `{% if ENABLE_OOMD %}` in the respective `systemd-*.conf.in`, but maybe these don't make sense anymore, when there the file is only included by the build system, when that feature is enabled.
> Just ask if I should revise the PR accordingly.

Right, those conditions can be dropped completely from the .in files. They basically moved into the meson.build file.
