### ISSUE TITLE
Pretty hostname specifier

### ISSUE THREAD

**Issue by petrkutalek** [systemd/systemd#20054]
**Is your feature request related to a problem? Please describe.**
It is not related to any problem, just nice-to-have feature request.

**Describe the solution you'd like**
Systemd offers [`%H` and `%l` specifiers](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) for hostname and short hostname. It would be useful to also offer a specifier for the `Pretty hostname` (like the entry in `hostnamectl`). The rationale is to offer a nice host name to systemd service units (e.g. `ExecStart=/usr/bin/player --name "Audioplayer @ %█"` could pass "Audioplayer @ Petr's Laptop").

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 248 (248.3-2-arch)`

**Comment by poettering** [comment]
makes sense i guess
