### ISSUE TITLE
Empty Nspawn Container Settings File does not default to private network

### ISSUE THREAD

**Issue by gitmalet** [systemd/systemd#20055]
**systemd version the issue has been seen with**
248

**Used distribution**
Arch

**Linux kernel version used** (`uname -a`)

`Linux archlinux 5.12.13-arch1-2 #1 SMP PREEMPT Fri, 25 Jun 2021 22:56:51 +0000 x86_64 GNU/Linux`
and
`Linux machine 5.12.12-hardened1-1-hardened #1 SMP PREEMPT Fri, 18 Jun 2021 23:00:50 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
After creating an Arch Linux nspawn container `test` and creating an empty container settings file `test.nspawn` in `/etc/systemd/nspawn`, the `machinectl` commands starts the container with the same options as it would without a container settings file (`test.nspawn`)   

**Unexpected behaviour you saw**
systemd-networkd inside the container fails with error `ConditionCapability=CAP_NET_ADMIN was not met` when starting the container with an empty `test.nspawn`.
Adding either `Private=yes` or `VirtualEthernet=yes` inside the `[Network]` section of `test.nspawn` resolves the issue

**Steps to reproduce the problem**

* Create a new container with mkosi as `mkosi -o /var/lib/machines/test -t directory`
* Start the container with `machinectl start test`
* Try to reach something in the internet from inside the container
* Stop the container with `machinectl stop test`
* Create an empty file with `touch /etc/systemd/nspawn/test.nspawn`
* Start the container again with `machinectl start test`
* Observer that networkd inside the container failed with `systemctl status --machine=status systemd-networkd`

**Comment by poettering** [comment]
So this is caused by the `--network-veth` option passed to systemd-nspawn when started via the `systemd-nspawn@.service`. 

But there's something wrong here, if the network is not configured in the .nspawn file its existance should not have any effect on the networking
