### ISSUE TITLE
RFE: teach "systemd-analyze verify" --override-name= to override unit name a unit file is loaded as, ignoring the actual name on disk

### ISSUE THREAD

**Issue by dnmvisser** [systemd/systemd#20061]
**systemd version the issue has been seen with**
 
```sh
systemd 246 (246.6-1ubuntu1.4)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
 
Ubuntu 20.10

**Linux kernel version used** (`uname -a`)
```
Linux groovy 5.8.0-59-generic #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**
 ```
x86_64
```

**Expected behaviour you didn't see**

As expected, `systemd-analyze verify <filename>` will verify the systemd unit:

```
vagrant@groovy:~$ cp /etc/systemd/system/syslog.service ~
vagrant@groovy:~$ systemd-analyze verify syslog.service 
/lib/systemd/system/plymouth-start.service:17: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
/lib/systemd/system/dbus.service:12: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
snap-lxd-20806.mount: Unit is bound to inactive unit dev-loop1.device. Stopping, too.
snap-snapd-12159.mount: Unit is bound to inactive unit dev-loop2.device. Stopping, too.
vagrant@groovy:~$ echo $?
0
```

**Unexpected behaviour you saw**

When trying to verify the same file, but with a different name, the verify step fails:

```
vagrant@groovy:~$ cp /etc/systemd/system/syslog.service source
vagrant@groovy:~$ systemd-analyze verify source
/lib/systemd/system/plymouth-start.service:17: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
/lib/systemd/system/dbus.service:12: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
snap-snapd-12159.mount: Unit is bound to inactive unit dev-loop2.device. Stopping, too.
Failed to prepare filename source: Invalid argument
vagrant@groovy:~$ echo $?
1
```

**Steps to reproduce the problem**

See above.

This issue is problematic when deploying systemd unit files using the ansible `template` module. This has a validate option that would be useful with `systemd-analyze verify`: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-validate

But the temp file used by ansible is not the one of the final template, instead it will be `source` in a temp directory.

Ideally `systemd-analyze verify` should not care about the file name it's verifying.

**Comment by mrc0mmand** [comment]
I'm not sure if this is (easily) achievable, since `systemd-analyze` needs the "correct" extension to determine the unit's type (service, mount, network, etc.), so it can check if the specified directives are valid for the given unit type. It also checks if the unit name itself is a valid name for systemd, which is a yet another benefit.

**Comment by keszybz** [comment]
I guess it would make *some* sense, for example when you have a build system and you want to call the service file something different, like `systemd-service.ini` and rename it to `<name>.service` during installation.

**Comment by poettering** [comment]
we also use the unit file name to resolve specifiers with i.e. `%f`, `%n` and so on. If we don't have the name for the unit we can't really load unit files hence.

But we could certainly add --override-name= or so as a new switch that allows specifiying the name to load the file under regarldes off its actual name.
