### ISSUE TITLE
udev: Rule for UBI in 60-persistent-storage.rules can't work

### ISSUE THREAD

**Issue by xyzzy42** [systemd/systemd#20071]
**systemd version the issue has been seen with**
 > v248

**Expected behaviour you didn't see**
 > Symlink to /dev/ubiX_Y is created by udev

**Unexpected behaviour you saw**
 > No symlink

**Steps to reproduce the problem**
 > Attach UBI partition with volumes

The issue is that virtually all of 60-persistent-storage.rules is skipped for non-block devices.  The UBI volume isn't a block device, so the rule for it is skipped.  If we look at the lines in question:
```
SUBSYSTEM!="block", GOTO="persistent_storage_end"
SUBSYSTEM=="ubi", KERNEL=="ubi*_*", ATTRS{mtd_num}=="*", SYMLINK+="ubi_mtd%s{mtd_num}_%s{name}"
LABEL="persistent_storage_end"
```
Obviously `SUBSYSTEM` can not be both `block` and `ubi` at the same time.  It looks like this bug has been present since the introduction of this rule.

The link `disk/by-uuid/<ubifs-uuid>`, which the existing rules would create, via blkid and ID_FS_UUID_ENC, is also missing for this same reason.

The link name, e.g. `/dev/ubi_mtd2_rootfs`, does not resemble other storage symlinks.  As the rule has never worked, likely no one depends on this name, and it could be changed to something more in line with other symlinks.

As UBI and MTD are both uncommon on non-embedded systems and somewhat unusual, I will describe some basics here:

> UBI creates a UBI device from an MTD device.  A UBI device will have multiple volumes in it.  They have both a volume number, which is usually sequentially assigned starting at 0, but can be anything, and a volume name.  Both must be unique for that UBI device.  The MTD device the UBI device is created in has a number assigned by the kernel and also usually a name.  The number must be unique but not the name.  Typically, a flash single storage device is split into partitions via the OF device tree passed to the kernel, and this is where the name and number of the MTD device(s) are created.  I.e., each MTD device is in fact a partition, with a partition label, of a larger device.  MTD does not create a "whole device" node as is usually done for partitioned block devices.
> 
> The UBI device also has a number, usually dynamically allocated but it can be specified, when UBI is attached to to the MTD device.  This UBI device number doesn't really correspond to real hardware and is more like a loop device number.
> 
> A UBI volume often, but not always, contains a ubifs filesystem.  In this case there is a UUID for the filesystem, but no additional label beyond the volume name.

Supposed we have `/dev/mtd1`, named `"ubiflash"`, which as been attached to UBI to make device `/dev/ubi0`, which has a volume `/dev/ubi0_2` named `"rootfs"`.

Links to /dev/ubi0_2 could be created as:

1. `disk/by-id/ubi-mtd1-rootfs`
2. `disk/by-id/ubi-0-rootfs`
3. `disk/by-id/ubi-mtd1-volume2`
4. `disk/by-id/ubi-0-volume2`
5. `disk/by-id/ubi-ubiflash-rootfs`
6. `disk/by-id/ubi-ubiflash-volume2`

Choices 1-4 result in unique names.  For 5 and 6, there could be a collision with multiple mtd partitions named `ubiflash` (which would be a foolish configuration to have created).  The UBI device number, used in 2 & 4 is IMHO not very useful as a symlink, as it's chosen at attach time like a loop device and 4 adds nothing that isn't already in `/dev/ubi0_2`.

One could also make the link `disk/by-partlabel/ubiflash` -> `/dev/mtd1`. I don't see a good reason to exclude mtd partitions with names from by-partlabel symlinks, but that's a different issue.

**Comment by poettering** [comment]
/cc @mgrzeschik 

maybe we should revert that PR #6750 entirely for now

**Comment by poettering** [comment]
Filed a revert in #20095 now.

**Comment by xyzzy42** [comment]
The by-uuid link is also missing.
