### ISSUE TITLE
test-time-util fails on CentOS CI after #20066

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#20089]
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/1649/artifact//systemd-centos-ci/artifacts_rGw9Uv/testsuite-logs-upstream.E9x/ninja-test_FAIL.log

cc @ddstreet.

**Comment by keszybz** [comment]
The test passes on Fedora because there is /usr/share/zoneinfo/Factory. https://en.wikipedia.org/wiki/List_of_tz_database_time_zones also lists it. I think we could consider this a packaging bug… The test checks consistency of external data, and there isn't much we can do about it.

**Comment by mrc0mmand** [comment]
Interesting, `Factory` was dropped from the `tzdata` package in Fedora/RHEL in 2012 - https://src.fedoraproject.org/rpms/tzdata/blob/rawhide/f/tzdata.spec#_585 and re-added back in Fedora in https://src.fedoraproject.org/rpms/tzdata/blob/rawhide/f/tzdata.spec#_221. The second commit (https://src.fedoraproject.org/rpms/tzdata/c/92f74b8c8a4466565dcdd554adeaeaf80091ab9a) is however didn't make it into RHEL/CentOS 8.

**Comment by keszybz** [comment]
Gotta love those commit messages that that explain anything.

**Comment by poettering** [comment]
now where is this country called "Factory"? Or is it a continent?
