### ISSUE TITLE
QMI LTE modem MAC address configuration race

### ISSUE THREAD

**Issue by tambry** [systemd/systemd#20090]
**Versions tested**
* 247.3-5 (Debian)
* 249~rc2-1 (Debian)

**Distribution**
Debian Unstable/Experimental

**Kernel**
`Linux [redacted] 5.10.0-8-amd64 #1 SMP Debian 5.10.46-1 (2021-06-24) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
amd64

**Expected behaviour you didn't see**
systemd always successfully performs DHCP on my QMI LTE modem's raw IP interface.

**Unexpected behaviour you saw**
About 50% of the time systemd fails to perform DHCP on the modem's interface due to the MAC address being empty.

**Steps to reproduce the problem**
Quectel EG25-G with firmware EG25GGBR07A08M2G.

Network file:
```
[Match]
Name=wwan0

[Network]
DHCP=yes
LLDP=no
```

(see #10881 for `LLDP=no`)

**Additional information**
It seems that the configuration only succeeds if systemd is fast enough and the device is not fully configured or something. Adding more networking files for LAN, etc. helps to ensure a higher failure rate.

`cat /sys/class/net/wwan0/addr_len` is `0` regardless of successful configuration or not.

**Logs**
[247 bad.log](https://github.com/systemd/systemd/files/6746066/bad.log)
[247 good.log](https://github.com/systemd/systemd/files/6746065/good.log)

**Comment by tambry** [comment]
I compiled trunk 58551e6ebc465227d0add8c714f9f38213b6878a and it seemed to work. Then again it might be coincidence since this is racy. Will bisect.

**Comment by tambry** [comment]
Right, I compiled systemd 247 with the more or less correct Debian options with a few adjustments to reduce compile times:
```
meson configure build/ \
	--prefix=/usr/local \
	-Db_lto=true \
	-Db_pie=true \
	-Dmode=release \
	-Drootlibdir=/usr/local/lib/x86_64-linux-gnu \
	-Dsplit-usr=true \
	-Dversion-tag="custom" \
	-Dquotaon-path=/sbin/quotaon \
	-Dquotacheck-path=/sbin/quotacheck \
	-Dkmod-path=/bin/kmod \
	-Dkexec-path=/sbin/kexec \
	-Dsulogin-path=/sbin/sulogin \
	-Dmount-path=/bin/mount \
	-Dumount-path=/bin/umount \
	-Dloadkeys-path=/bin/loadkeys \
	-Dsetfont-path=/bin/setfont \
	-Dnologin-path=/usr/sbin/nologin \
	-Dtelinit-path=/lib/sysvinit/telinit \
	-Dsysvinit-path=/etc/init.d \
	-Dsysvrcnd-path=/etc \
	-Dlocalegen-path=/usr/sbin/locale-gen \
	-Ddebug-shell=/bin/bash \
	-Dzshcompletiondir=/usr/local/share/zsh/vendor-completions \
	-Ddbuspolicydir=/usr/local/share/dbus-1/system.d/ \
	-Ddefault-kill-user-processes=false \
	-Ddefault-hierarchy=unified \
	-Ddefault-dnssec=no \
	-Dpamconfdir=no \
	-Dpamlibdir=/lib/x86_64-linux-gnu/security \
	-Drpmmacrosdir=no \
	-Dqrencode=false \
	-Dvconsole=false \
	-Dfirstboot=false \
	-Dxkbcommon=false \
	-Dwheel-group=false \
	-Drepart=false \
	-Duserdb=false \
	-Dhomed=false \
	-Dlibfido2=false \
	-Dfdisk=false \
	-Dpwquality=false \
	-Dp11kit=false \
	-Dtpm2=false \
	-Doomd=false \
	-Dsysext=true \
	-Dnscd=true \
	-Dntp-servers="0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org" \
	-Ddns-servers='' \
	-Dlink-udev-shared=false \
	-Dsystem-uid-max=999 \
	-Dsystem-gid-max=999 \
	-Dnobody-user=nobody \
	-Dnobody-group=nogroup \
	-Dbump-proc-sys-fs-nr-open=false \
	-Ddev-kvm-mode=0660 \
	-Dgroup-render-mode=0660 \
	-Dselinux=true \
	-Dhwdb=true \
	-Dsysusers=true \
	-Dinstall-tests=false \
	-Defi=true \
	-Dman=false \
	-Dtranslations=false \
	-Dnss-myhostname=true \
	-Dnss-mymachines=true \
	-Dnss-resolve=true \
	-Dnss-systemd=true \
	-Dresolve=true \
	-Dlink-systemctl-shared=false \
	-Daudit=true \
	-Dlibcryptsetup=true \
	-Dcoredump=true \
	-Delfutils=true \
	-Dapparmor=true \
	-Dlibidn2=true \
	-Dlibiptc=true \
	-Dlibcurl=true \
	-Dimportd=true \
	-Dmicrohttpd=true \
	-Dgnutls=true \
	-Dpcre2=true
```

But basically I seem to be unable to reproduce with a custom-compiled distribution-identical systemd. Not much use, so closing for now.

**Comment by tambry** [comment]
The issue indeed was timing-dependent and returned since. Since systemd v250 this can however be solved by setting `ClientIdentifier=duid-only` (and `DUIDType=vendor`, i.e. the default). Credit to @ciandonovan for the solution.

**Comment by AravindGopala** [comment]
@tambry I am facing a similar issue, I do not see this resolved by setting `ClientIdentifier=duid-only` can you confirm if it is actually fixed for you?

**Comment by tambry** [comment]
@AravindGopala We eventually still encountered various issues and moved to using a static IP configuration. Long-term we're moving back to dynamic and will likely implement a daemon that will configure the interface through netlink based on the configuration information obtained with QMI.

**Comment by AravindGopala** [comment]
The issue is 100% reproducible for me if the systemd-networkd is started after  raw_ip wwan0 interface is up.

**Comment by AravindGopala** [comment]
Created this [ticket](https://github.com/systemd/systemd/issues/27219) with my analysis, please feel free to update if you find a solution, thank you
