### ISSUE TITLE
systemd-boot corrupts .cmdline if there's no .initrd in EFI Unified Kernel Image

### ISSUE THREAD

**Issue by glance-** [systemd/systemd#20096]
**systemd version the issue has been seen with**
 > 249-rc1-34-gd8301ae

**Used distribution**
 > Custom embedded stuff.

**Linux kernel version used** (`uname -a`)

 > `5.10-with-local-patches`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd-boot booting EFI Unified Kernel Image with proper command line.

**Unexpected behaviour you saw**
 > systemd-boot booting EFI Unified Kernel Image with garbage command line.

**Steps to reproduce the problem**
(maybe unneccecry step:)
Build a kernel with a compiled in initramfs, using CONFIG_INITRAMFS_SOURCE

Create a Unified Kernel Image without a .initrd section
 > objcopy \
>        --add-section .osrel=/tmp/os-rel.txt --change-section-vma .osrel=0x20000 \
>        --add-section .cmdline=/tmp/cmdline.txt --change-section-vma .cmdline=0x30000 \
>        --add-section .linux=/boot/linux-5.10 --change-section-vma .linux=0x2000000 \
>        /usr/lib/systemd/boot/efi/linuxx64.efi.stub /boot/efi/EFI/Linux/crashing-and-burning.efi

And try to boot it. The command line passed from systemd-boot to linux will contain garbage. On the other hand, if one stops at the systemd-boot menu, and clears the cmdline there and then boot, linux will get the proper cmdline.

**Additional program output to the terminal or log subsystem illustrating the issue**
This issue can be worked around by adding a empty cpio archive as .initrd section:
echo -n | cpio -o --file /tmp/empty.cpio
and adding
>         --add-section .initrd=/tmp/empty.cpio --change-section-vma .initrd=0x3000000 \
to the objcopy cmdline.

**Comment by jameshilliard** [comment]
Hmm, I wonder if this might be related to #20195.

**Comment by mxre** [comment]
Have you tried writing `if ( (UINT32)initrd_size )`  or commenting out the lines setting the initrd address in the boot stub?
 
 https://github.com/systemd/systemd/blob/66e093def81d18967c412cb578c2aeecb1c33551/src/boot/efi/linux.c#L74-L75

**Comment by glance-** [comment]
I just re-tested this, and this now works, without any changes. Just a v249-962-g3a18c0e5f2 systemd-boot was enough to get this working.

I can see that @poettering have worked on those bits recently so I'm guessing that something there fixed it.
