### ISSUE TITLE
sysusers not adding user to specified group

### ISSUE THREAD

**Issue by grawlinson** [systemd/systemd#20107]
**systemd version the issue has been seen with**
 > 248.3 (248.3-2 in Arch's core repository)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux ticktock 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
**Unexpected behaviour you saw**

> These two statements above ^^ contradict each other, so I'm just going to ignore them.

**Steps to reproduce the problem**
 > Add following to `example.conf`, then run `systemd-sysusers example.conf`:
```conf
g example
u example1 -:example
u example2 -:example
u example3 -:example
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
$ systemd-sysusers example.conf
Creating group example with gid 962.
Creating user example1 (n/a) with uid 961 and gid 962.
Creating user example2 (n/a) with uid 960 and gid 962.
Creating user example3 (n/a) with uid 959 and gid 962.

$ grep example /etc/passwd
example1:x:961:962::/:/usr/bin/nologin
example2:x:960:962::/:/usr/bin/nologin
example3:x:959:962::/:/usr/bin/nologin

$ grep example /etc/group
example:x:962:
```

I expected the `example` group in `/etc/group` to look like this: `example:x:962:example1,example2,example3` instead of the above result. I assumed that by specifying the primary group in `example.conf`, the users would automatically be added to the primary group.

To achieve my desired results, I had to adjust `example.conf` to look like this:

```conf
g example
u example1 -:example
u example2 -:example
u example3 -:example
m example1 example
m example2 example
m example3 example
```

**Comment by poettering** [comment]
/etc/group lists auxiliary group memberships only. The primary group membership is only listed in /etc/passwd. 

Thus if you want to know all users which are in group X you need to find the group X in /etc/group for the auxiliary memberships and then also look for all entries in /etc/passwd that specify X's GID as their primary group for the primary memberships.

This is how UNIX works. Sorry!

And yes, there's nothing stopping you from making a user both a primary and an auxiliary member of the same group.

Anyway, we didn't design thing that way, we just create compatible records in these two databases, hence we do what UNIX requires us.

**Comment by grawlinson** [comment]
Thanks for the explanation! Much appreciated.
