### ISSUE TITLE
/dev/vhost-net could be usable by non-root

### ISSUE THREAD

**Issue by dwmw2** [systemd/systemd#20105]
We already make /dev/net/tun accessible to all users, because you need CAP_NET_ADMIN to create an actual device anyway. But a device can be created *for* you in advance, and then you can run a VPN client as an unprivileged user. We do this for OpenConnect from NetworkManager, for example.

You can do it for virtual machines too. If the tun device is created in advance, qemu doesn't need privileges just to be able to *use* it.

We can use vhost-net for accelerating access to our tun device... but that doesn't work in these situations because it seems to be root-only, unlike /dev/net/tun. Can we make them match?

**Comment by poettering** [comment]
We can certainly open up everything where from the kernel people that's blessed as being safe and OK, i.e. where the API is designed with such security delegation in mind.

**Comment by bluca** [comment]
@dwmw2 is there kernel (or other) documentation available that describes the security model that can be used with vhost-net, if we do make it usable to other users? Is it the same (CAP_NET_ADMIN), is there a different mechanism, etc

**Comment by dwmw2** [comment]
It does not confer any permissions or privileges or give access to any resources other than the socket you bind it to. And you can't use it unless you have a suitable socket to use it *with*. Which is either an AF_PACKET socket or a tun/tap device — all of which require CAP_NET_ADMIN or to have been granted permission to a specific device explicitly.

**Comment by bluca** [comment]
Sounds good. Want to send a PR? It's just a config change in tmpfiles.d/static-nodes-permissions.conf.in

**Comment by bluca** [comment]
(it's 0666 by default, but distros change it, I guess because it's the same option that controls also /dev/kvm and /dev/vhost-vsok)

**Comment by dwmw2** [comment]
Oh, in this case it's already fixed by commit f65efddd1. I'm OK with it being in line with /dev/kvm (which is *also* OK to be usable by unprivileged users, modulo bugs). Thanks.

**Comment by bluca** [comment]
@dwmw2 should we start to ask distro maintainers to avoid overriding the default, to make them 0666? /cc @mbiebl

https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/rules#L88

**Comment by dwmw2** [comment]
Probably. I have made OpenConnect report EPERM on /dev/vhost-net as an error, not silently ignore it and do without
