### ISSUE TITLE
Chrome: "Network service crashed" with 249rc3

### ISSUE THREAD

**Issue by twwn** [systemd/systemd#20111]
**systemd version the issue has been seen with**
 > 249rc2, 249rc3

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)

 > `5.12.14-zen1-1-zen`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > Chrome works

**Unexpected behaviour you saw**
 > Tabs "freeze" instantly when browsing.

**Steps to reproduce the problem**
 > Start, try browsing any site

**Additional program output to the terminal or log subsystem illustrating the issue**

Chrome's only console output is this repeating:
```text
ERROR:network_service_instance_impl.cc(332)] Network service crashed, restarting service.
```

After downgrading to v248 Chrome (93.0.4557.4) works fine again.

**Comment by yuwata** [comment]
Please provide debugging log of networkd, otherwise there is almost nothing we can do. I hope #20108 also fixes your issue.

**Comment by nwwt** [comment]
I don't appear to have setup networkd. That is, it's not running under v248 nor v249, instead `systemctl status`'es it as _"inactive (dead)"_ under both.

The only network-related things `list-units` prints is `network.target` and `network-online.target`, neither of which seem to have issues.

(Also, Firefox shows no problems, nor have I seen any command-line utilities having trouble connecting.)

**Comment by yuwata** [comment]
Hence, there is nothing we can do. Sorry. Please contact to google.

**Comment by keszybz** [comment]
Yeah, this needs to be debugged from the Chrome side. FWIW, Chrome and Chromium both seem to work fine here with the latest systemd.

**Comment by foutrelis** [comment]
Bisects to 319a4f4bc46b230fc660321e99aaac1bc449deea. Chromium works if `systemd-resolved` is **not** running; seems related to `libnss_resolve` 🐱

**Comment by afq984** [comment]
See also https://crbug.com/1221442
