### ISSUE TITLE
sd-oomd uses excessive cpu

### ISSUE THREAD

**Issue by cmurf** [systemd/systemd#20122]
**systemd version the issue has been seen with**
 > systemd-248.3-1.fc34.x86_64

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)

 > `5.12.11-300.fc34.x86_64`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > minimal cpu usage

**Unexpected behaviour you saw**
 > top consumer of cpu, by a lot

**Steps to reproduce the problem**
 > clean install, run system at idle

**Additional program output to the terminal or log subsystem illustrating the issue**

[strace-oomd.txt](https://github.com/systemd/systemd/files/6757885/strace-oomd.txt)

[oomd-stack.txt](https://github.com/systemd/systemd/files/6757886/oomd-stack.txt)

[ps-sorttime.txt](https://github.com/systemd/systemd/files/6757887/ps-sorttime.txt)

These are the top two consumers of cpu by time on an idle system:
```
polkitd      898  0.2  0.3 3245888 41948 ?       Ssl  00:04   3:10 /usr/lib/polkit-1/polkitd --no-debug
systemd+    1074  2.5  0.0  17840  8868 ?        Ss   00:04  33:00 /usr/lib/systemd/systemd-oomd
```

**Comment by anitazha** [comment]
Oops I know what happened... cb13961ada52c1b27f6d6c2c6e37a2901f01ed30 I updated the logic to update kill candidates only when a kill is about to happen but I forgot to remove the original lines at https://github.com/systemd/systemd/blob/main/src/oom/oomd-manager.c#L427-L432 so it's still updating kill candidates regardless of whether a kill is about to happen or not. Sorry about that I'll test a PR for this when it's more sane Pacific hours and put up a fix.
