### ISSUE TITLE
systemd-sleep.conf(5) suspend-then-hibernate confusing

### ISSUE THREAD

**Issue by hmoffatt** [systemd/systemd#20125]
**systemd version the issue has been seen with**
248

**Used distribution**
Source

**Unexpected behaviour you saw**
The manual page refers to 3 settings that are referred to by 4 units, **respectively**, which doesn't make a lot of sense.

```
SuspendMode=, HibernateMode=, HybridSleepMode=

    The string to be written to /sys/power/disk by, respectively, systemd-suspend.service(8), systemd-hibernate.service(8), systemd-hybrid-sleep.service(8), or systemd-suspend-then-hibernate.service(8). 
```

And the same for the SuspendState etc.

From reading the source (src/sleep/sleep.c, src/shared/sleep-config.c) I see that the suspend-then-hibernate mode does not have configuration settings of its own but issues a suspend using the SuspendMode/SuspendState settings and then a hibernate using the HibernateMode/HibernateState settings. It would be helpful if the man page said this.

**Comment by bluca** [comment]
Can you send a PR to reword it?

**Comment by hmoffatt** [comment]
Will do!
