### ISSUE TITLE
Systems can not boot , restart and restart and restart.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#2012]
I have an pc with AMD A4 cpu with gigabyte FM2+ motherboard 

The system i tried ubuntu 15.04 , 15.10. they both include systemd as default . 

while boot system. it will restart again and again.

so i reinstall with ubuntu 14.04. they not using systemd.

the boot success and running normal.

**Comment by utezduyar** [comment]
Could you please attach some logs so we know how far do you go with the boot.

**Comment by ghost** [comment]
Currently i am not using systemd. i reload os with Ubuntu 14.04. so can not provided logs.
Before i reload os, i installed ubuntu 15.10. and i can not boot into system. so i can not got logs from system.

**Comment by ghost** [comment]
the grub menu i can see, but when we press boot, the boot menu disappear, then the system reboot. So it should be a systemd problem.

**Comment by ghost** [comment]
I am not the only one. see 

https://plus.google.com/+gregkroahhartman/posts/EivMyiW6GR1

Greg Kroah-Hartman faced similar problem like me .

**Comment by ghost** [comment]
Due to i can not provided any proof to help dig the problem out, it seems close issue better.

**Comment by zonque** [comment]
> I am not the only one. see
> 
> https://plus.google.com/+gregkroahhartman/posts/EivMyiW6GR1
> 
> Greg Kroah-Hartman faced similar problem like me .

But Greg's problem isn't related to a systemd update, so that's really a wrong lead here.

Anyway, what makes you believe this is related to systemd? Are you positive you set up you initrd correctly and didn't mess with other bootloader specific settings?

**Comment by ghost** [comment]
Because it's fresh install. and i reload ubuntu 15.10 more than three times.
The early reboot problem only can be relate grub or systemd.

**Comment by ghost** [comment]
If bios was broken, i would not be able to install ubuntu 14.04. My pc works well with ubuntu 14.04. which not using systemd

**Comment by martinpitt** [comment]
We really need a journal log or at least a screenshot with an error message (with a camera) to do anything with this. Please also note that in the boot menu you can choose to boot with upstart, that should give you a working systemd. Please also see /usr/share/doc/systemd/README.Debian.gz how to get some debug information, like the rescue shell.
