### ISSUE TITLE
RFE: skip job activation if not enough system resources (CPU/memory) are available

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#20139]
**Is your feature request related to a problem? Please describe.**
On slow/overloaded/constrained systems it is common to partition system resources (CPU/memory) so that critical tasks are guaranteed to be able to run. This is especially true when memory overcommitting (swap) is disabled. Periodic tasks (eg: timer units) need to have resources carved out too, despite only needing them seldomly.

**Describe the solution you'd like**
Linux makes pressure stall information (PSI) available (https://www.kernel.org/doc/html/latest/accounting/psi.html), which indicate the state of system resources availability within a given window of time, as an indicator of system load.
New unit directives such as `ConditionMemoryPressure=`, `ConditionCPUPressure=` could be made available, which instructs systemd to skip the activation of a unit if the required threshold is not met, for example: `ConditionMemoryPressure=70` following oomd's syntax https://www.freedesktop.org/software/systemd/man/oomd.conf.html#DefaultMemoryPressureLimit=

**Describe alternatives you've considered**
Carving out resources specifically for period tasks, which leads to under-utilization, or carefully building dependency/ordering chains between all timed units, which is unwieldy and not really possible unless a single entity provides them all.

**Comment by bluca** [comment]
Thanks to oomd's implementation, the ground work is already in place. It should be just a matter of reading PSI in a new `condition_memory_pressure()` function. I would tend to keep the configuration syntax in line with oomd's, for consistency and simplicity. An alternative would be to allow 1:1 mapping to the kernel interface (eg: `ConditionMemoryPressure=avg10<80 avg300<50`) but it seems excessively complicated.

**Comment by poettering** [comment]
is "condition" really the right concept for this? I mean, you don't want to totally skip these services, but just delay them a bit more, no?

so far our philosophy was to dump as much as we can on the CPU/IO schedulers and priorize the work via nice levels/ioprios/cpuprios and so on, and then let the kernel figure out things on its own, instead of second guessing these schedulers by monitoring them from userspace and dumping more work on them only when they don't appear overloaded. Having a scheduler in userspace that kinda works around the fact that the schedulers already implemented in the kernel apparently aren't that good at scheduling stuff sounds kinda sad no?

ignoring this issue, i wonder if this wouldn't better be implemented as part of the timer logic, or possibly in a new unit type ".idle" or so? maybe with a timer unit like this:

```
[Timer]
OnActiveSec=15min
IdleDelaySec=6h
IdleDelayCondition=avg10 < 80
```

With a timer like this we'd wait at least 15min after the unit is started and then until the load falls below 80, but 6h at maximum.

Or in other words, I'd use a concept such as RandomizedDelaySec= as model here: which adds random noise to the trigger time. With this idle concept we'd add not-quite-as-random noise to it.

**Comment by bluca** [comment]
> is "condition" really the right concept for this? I mean, you don't want to totally skip these services, but just delay them a bit more, no?
> 
> so far our philosophy was to dump as much as we can on the CPU/IO schedulers and priorize the work via nice levels/ioprios/cpuprios and so on, and then let the kernel figure out things on its own, instead of second guessing these schedulers by monitoring them from userspace and dumping more work on them only when they don't appear overloaded. Having a scheduler in userspace that kinda works around the fact that the schedulers already implemented in the kernel apparently aren't that good at scheduling stuff sounds kinda sad no?

It's the same theory behind having systemd-oomd - when things get dire, the kernel is not the best place to make a choice on what to throw under the bus and what to leave alone. Having strong hints in the unit configuration in practice just yields better results.

> ignoring this issue, i wonder if this wouldn't better be implemented as part of the timer logic, or possibly in a new unit type ".idle" or so? maybe with a timer unit like this:
> 
> ```
> [Timer]
> OnActiveSec=15min
> IdleDelaySec=6h
> IdleDelayCondition=avg10 < 80
> ```
> 
> With a timer like this we'd wait at least 15min after the unit is started and then until the load falls below 80, but 6h at maximum.
> 
> Or in other words, I'd use a concept such as RandomizedDelaySec= as model here: which adds random noise to the trigger time. With this idle concept we'd add not-quite-as-random noise to it.

So something like that was my first idea when I proposed in the chat, then it evolved into a condition. The advantage of having a condition is that it applies to all units, not just timers - think of a path-triggered service that watches for non-critical and relatively frequent disk changes, for example. Being able to codify "watch this path, but it's fine to skip a round if the system is under pressure" is something I definitely have use cases for and need to provide. Or a templated unit that get occasionally instantiated by another service.

What you say about guaranteed retries is of course true as well, it would be good to have for timers. What if we had both options?

**Comment by Werkov** [comment]
I'm not convinced this is generic enough use case to be useful in systemd (don't forget about `ExecCondition=`, why it doesn't work for you?).
- What pressure should be watched? (global, target slice, a target slice parent,...)
- What to do on kernels without PSI support? (give up or proceed regardless)
- What's actually the goal? (not stressing the system when it's struggling -- as argued above kernel scheduling should deal with that; having enough resources for timely completion of the job -- what's the point of delay?)

**Comment by bluca** [comment]
> I'm not convinced this is generic enough use case to be useful in systemd (don't forget about `ExecCondition=`, why it doesn't work for you?).
> 
> * What pressure should be watched? (global, target slice, a target slice parent,...)
> * What to do on kernels without PSI support? (give up or proceed regardless)
> * What's actually the goal? (not stressing the system when it's struggling -- as argued above kernel scheduling should deal with that; having enough resources for timely completion of the job -- what's the point of delay?)

I don't see how it is not generic enough? Memory pressure is a thing on most systems, that's why oomd was added in the first place, and it's enabled by default in Fedora, for example.

- the system-wide one (eg: proc/pressure/memory)
- same that we do for all other optional features that require kernel support, skip it
- same as oomd, in practice it's just not true, and results are and can only be suboptimal without "hints", especially for memory pressure

**Comment by Werkov** [comment]
The note about generality means that there are too many options: memory or cpu pressure was mentioned, idle condition+wait window, observed slice (I still think target slice may be a use case too) -- those would be expressed with an `ExecCondition=` (and adding further flexibility). I see that could be more troublesome to evaluate under the stressing condition than a built-in directive.

If I understand the argument with systemd-oomd similarity, you're saying that a unit that'd be a candidate for killing under given circumstances is not worth starting at all. Maybe the directive shouldn't suggest similarity with static conditions (comparing with the existing conditions) but relatedness to systemd-oomd. Extending on that, adding something like `ManagedOOMPressureFilled=` directive on a *slice* instead that would reject any starts of under given slice if pressure is too high (I'm throwing this as a brainstorm idea, I can't tell what is more practical).
