### ISSUE TITLE
systemctl start will canceled, but service start not

### ISSUE THREAD

**Issue by zhangguanzhang** [systemd/systemd#20130]
**systemd version the issue has been seen with**
```
$ systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
$ cat /etc/os-release 
PRETTY_NAME="UnionTech OS Server 20 Enterprise"
NAME="UnionTech OS Server 20 Enterprise"
VERSION_ID="20"
VERSION="20"
ID=UOS
HOME_URL="https://www.chinauos.com/"
BUG_REPORT_URL="http://bbs.chinauos.com"
VERSION_CODENAME=fou
```

**Linux kernel version used** (`uname -a`)

 > `Linux host1 4.19.0-arm64-server #3017 SMP Thu Nov 12 19:54:04 CST 2020 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 > `aarch64`

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
```
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://docs.docker.io
$ systemctl start docker
Job for docker.service canceled.
$ service docker start
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-05 14:41:30 CST; 15s ago
     Docs: http://docs.docker.io
$ systemctl cat docker
# /etc/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.io

[Service]
Environment="PATH=/data/kube/bin:/bin:/sbin:/usr/bin:/usr/sbin"
ExecStart=/data/kube/bin/dockerd 
ExecStartPost=/sbin/iptables --wait -I FORWARD -s 0.0.0.0/0 -j ACCEPT
ExecStopPost=/bin/sh -c '/sbin/iptables --wait -D FORWARD -s 0.0.0.0/0 -j ACCEPT &> /dev/null || :'
ExecStartPost=/sbin/iptables --wait -I INPUT -i cni0 -j ACCEPT
ExecStopPost=/bin/sh -c '/sbin/iptables --wait -D INPUT -i cni0 -j ACCEPT &> /dev/null || :'
ExecReload=/bin/kill -s HUP $MAINPID
Restart=on-failure
RestartSec=5
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Delegate=yes
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

I wanto know why systemctl command cannot start docker.service

**Comment by yuwata** [comment]
Sorry, this is an upstream bug tracker and v241 is too old here. Please request to reopen this page if you reproduce with a recent systemd release (currently, v247 or v248, and v249 will be hopefully released soon).

Also, if you will be able to reproduce the issue with a recent systemd, then please provide debugging logs for the issue. To generate debugging logs, e.g. please set `systemd.log-level=debug` in the kernel command line on boot.

Closing.

**Comment by zhangguanzhang** [comment]
there is some err in file: `/etc/fstab`
the system boot into the emergency mode， so the dbus cannot start. after I resolve it and reboot. all be ok
