### ISSUE TITLE
Assertion 'fd' failed at src/tmpfiles/tmpfiles.c:843, function fd_set_perms()

### ISSUE THREAD

**Issue by jclsn** [systemd/systemd#20140]
**systemd version the issue has been seen with**
 > systemd-248.3-2

**Used distribution**
 > Arch Linux

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 >  No temporary files could be created if needed by the installed package

**Unexpected behaviour you saw**
 
```
:: Running post-transaction hooks...
( 1/12) Creating system user accounts...
( 2/12) Reloading system manager configuration...
( 3/12) Creating temporary files...
Assertion 'fd' failed at src/tmpfiles/tmpfiles.c:843, function fd_set_perms(). Aborting.
/usr/share/libalpm/scripts/systemd-hook: line 28:  1617 Aborted                 (core dumped) /usr/bin/systemd-tmpfiles --create
error: command failed to execute correctly
```

**Steps to reproduce the problem**
 > Updating systemd as it will require temporary files after the installation

**Comment by floppym** [comment]
An easy way to reproduce this is to close stdin (fd 0) before calling systemd-tmpfiles.
```
# cat foo.c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char **argv)
{
        close(0);
        execlp("systemd-tmpfiles", "systemd-tmpfiles", "--create", NULL);
        perror("execlp");
        return 1;
}

# ./foo
/usr/lib/tmpfiles.d/legacy.conf:13: Duplicate line for path "/run/lock", ignoring.
Assertion 'fd' failed at src/tmpfiles/tmpfiles.c:843, function fd_set_perms(). Aborting.
Aborted (core dumped)
```

**Comment by keszybz** [comment]
Yes, but this is essentially a bug in the spawning program. As a POSIX program you can expect to have fds 0, 1, 2 initialized correctly. In our code, we obviously try not to rely on this, hence the pull request, but I expect this to cause issues in other programs started this way. (In particular, you open a file for output, and then it gets used as stdin by some child you spawn, and then you open another file for output, and it gets used as stdout by some child you spawn. With a shell, this is unlikely to lead to expected results.)

**Comment by floppym** [comment]
Right, I suspect something is weird/broken with the way @coldspark29 is updating their system, or with Arch's package manager.
