### ISSUE TITLE
remote-fs.targets should have a hard_timeout option to automatically force unmount if endpoint becomes unresponsive.

### ISSUE THREAD

**Issue by blistovmhz** [systemd/systemd#20148]
**Is your feature request related to a problem? Please describe.**
All remote-fs.targets will cause any process attempting to access the mount point, to hang indefinitely, if the mount point is not accessible. With some endpoints (ie: cifs) we can sorta hack around this by sending specific mount options to set timeouts, but not all endpoints have sufficient timeout options (and CIFS options work, annoyingly poorly). 
Example use case: I've got an sshfs mount point at ~/remotes/bob . I disconnect from the network, and type ls in ~/remotes/, and ls hangs indefinitely. We at this point cannot manually unmount bob. It seems the only recourse is either re-gain network connectivity and manually unmount bob, or reboot.

**Describe the solution you'd like**
Ideally, systemd would have an option to set a hard timeout for all mounts. EG: hard_timeout=0.5s. If a process attempts to access the mountpoint, and the mountpoint does not respond in time, systemd kills the mount entirely or at least fails gracefully so the requesting process can get on with it's day. It seems we SORT OF have this already in some edge cases, but it would be immensely valuable to be able to just force this behavior globally, to all mounts.

**Describe alternatives you've considered**
I've manually hacked solutions to this problem for 20 years (never with systemd.remote-fs.target). There aren't really any alternatives that work out of the box and can be expected to be available on all systems.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 247 (247.3-3ubuntu3.1)

**Comment by poettering** [comment]
Why should that be in systemd though? systemd has no idea what a "responsive" mount is and what not. The file system implementation otoh is likely to know this.

Have you asked the maintainers of the network file system implementation of your choice?

**Comment by blistovmhz** [comment]
I absolutely agree that's how it SHOULD be done, and I've been hoping for 20+ years that the various devs of cifs/sshfs/fuse/nfs would all have a sit down and agree on a standard, but I think we know that isn't going to happen at this point. CIFS has their few options, but they just barely work and are not terribly responsive. For some reason they force you to wait for at least a 1 second timeout minimum, and I believe 3 automatic reconnect attempts (total of 3 seconds) before gracefully giving up. In the mean time, you have 10 CIFS mounts all in the same parent directory, so you're waiting 30 seconds for mistakenly hitting ls.

Like I said, I've written (poorly) wrappers in the past to handle this issue with other various subsystems, but as they come and go, we have to rewrite them, and we're still 20 years of having no consistent method of automatically and gracefully releasing a remote mount when it's very clearly dead.

I'll admit I don't know what at this point, would be necessary to mitigate/hack around this issue these days (I don't have time anymore, for my OS and software to be any more than a tool). If this isn't something that could be accomplished via systemd, and we don't have any standard mount options for the various remote file systems, do you have any other suggestions? Just occurs to me that systemd, to me, seems best positioned to recognise when a mount has become inaccessible, given it's sorta in the middle of everything at this point.

**Comment by poettering** [comment]
I am sorry, but systemd is not the place for workarounds around misdesigns and bugs in other people's software.

**Comment by poettering** [comment]
Let's close this. Please work with the relevant network fs communities. systemd is not the place to work around limitations of such implementations. Sorry.
