### ISSUE TITLE
systemd-resolved: getaddrinfo returns different ai_canonname from nss-resolve than nss-files

### ISSUE THREAD

**Issue by tchernomax** [systemd/systemd#20158]
In other words, systemd-resolved doesn't respect the [/etc/hosts format](https://man.archlinux.org/man/hosts.5.en#DESCRIPTION).

**systemd version the issue has been seen with**
 
> systemd 248 (248.3-2-arch)
> +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**

> Archlinux

**Linux kernel version used** (`uname -a`)

> Linux mde-claranet 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**

 > x86_64

**Expected behaviour you didn't see**

Running systemd-resolved with `ReadEtcHosts=yes` (the default).
For names from `/etc/hosts` I expect it to behave like libnss_files.so, which means it should considere the [/etc/hosts formated as such](https://man.archlinux.org/man/hosts.5.en#DESCRIPTION):
```
IP_address canonical_hostname [aliases...]
```
So when [nsswitch.conf is configured to use systemd-resolved](https://www.freedesktop.org/software/systemd/man/nss-resolve.html), `getaddrinfo(alias)` should return 'canonical_hostname' as canonical hostname (ai_canonname in [getaddrinfo man page](https://man.archlinux.org/man/getaddrinfo.3#DESCRIPTION)).

```
root@fakename # grep alias /etc/hosts
127.1.1.1 canonical_hostname alias
root@fakename # grep hosts: /etc/nsswitch.conf
hosts: resolve
root@fakename # python3 -c 'import socket; print(socket.getaddrinfo("alias", 0, flags=socket.AI_CANONNAME)[0][3])'
canonical_hostname
```

**Unexpected behaviour you saw**

Currently, `getaddrinfo(alias)` returns 'alias' as canonical hostname.

```
root@fakename # python3 -c 'import socket; print(socket.getaddrinfo("alias",0, flags=socket.AI_CANONNAME)[0][3])'
alias
```

**Steps to reproduce the problem**

```
root@fakename # echo '[Resolve]' > /etc/systemd/resolved.conf
root@fakename # systemctl restart systemd-resolved.service
root@fakename # echo '127.1.1.1 canonical_name alias' >> /etc/hosts
root@fakename # sed -i 's/^hosts: .*/hosts: resolve/' /etc/nsswitch.conf
root@fakename # python3 -c 'import socket; print(socket.getaddrinfo("alias",0, flags=socket.AI_CANONNAME)[0][3])'
alias
root@fakename # sed -i 's/^hosts: .*/hosts: files resolve/' /etc/nsswitch.conf
root@fakename # python3 -c 'import socket; print(socket.getaddrinfo("alias",0, flags=socket.AI_CANONNAME)[0][3])'
canonical_hostname
```

**Comment by keszybz** [comment]
In short, when you ask for the canonical name through an alias, it returns the alias the canonical name.
I can reproduce this here.

**Comment by keszybz** [comment]
@ldv-alt you mentioned that you have some WIP?

**Comment by ldv-alt** [comment]
@keszybz I've amended the PR to explicitly mention this issue, otherwise the PR didn't show up here although the commits were.

**Comment by pemensik** [comment]
For a reproducer, this might work:

```
$ gdb --args getent ahosts localhost4

(gdb) break freeaddrinfo
(gdb) run
Starting program: /usr/bin/getent ahosts localhost4
[Thread debugging using libthread_db enabled]                                                                                    
Using host libthread_db library "/lib64/libthread_db.so.1".
127.0.0.1       STREAM localhost                                                                                                 
127.0.0.1       DGRAM  
127.0.0.1       RAW    

Breakpoint 1, __GI_freeaddrinfo (ai=ai@entry=0x55555555f070) at ../sysdeps/posix/getaddrinfo.c:2612
(gdb) p *ai
$1 = {ai_flags = 234, ai_family = 2, ai_socktype = 1, ai_protocol = 6, ai_addrlen = 16, ai_addr = 0x55555555f0a0, 
  ai_canonname = 0x55555555f050 "localhost", ai_next = 0x55555555f0c0}
```
