### ISSUE TITLE
logind fails at authenticating with -ESTALE when processing a request for hibernating and an inhibitor lock is taken by another user

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#20155]
Steps to reproduce:

Root is logged via ssh and takes a lock with:
```root@localhost # systemd-inhibit --who=root-locker --why=test --mode=block --what=sleep sleep infinity```

On a tty, a regular user is logged and can check that the lock is taken:

```
fbui@locahost # systemd-inhibit --list
WHO          UID USER PID  COMM            WHAT  WHY                           
root-locker  0   root 1558 systemd-inhibit sleep test
```
He then attempts to hibernate with the check for inhibitors disabled:

```
fbui@localhost # systemctl hibernate --check-inhibitors=no
==== AUTHENTICATING FOR org.freedesktop.login1.hibernate-multiple-sessions ====
Authentication is required to hibernate the system while other users are logged in.
Authenticating as: root
Password: 
==== AUTHENTICATION COMPLETE ====
Failed to hibernate system via logind: Stale file handle
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to start 'hibernate.target'.
Authenticating as: root
Password:
```

As this can be seen, several authentications were requested:

- one by logind for `org.freedesktop.login1.hibernate-multiple-sessions` which was successful 
- one by logind for `org.freedesktop.login1.hibernate-ignore-inhibit`  which failed with "Stale file handle"
- one by systemctl for `org.freedesktop.systemd1.manage-units` : systemctl felt back to starting `hibernate.target` directly because logind failed

For some reasons the second auth request failed with -ESTALE which is not expected.

**Comment by yuwata** [comment]
WithFlags methods were introduced by 8885fed4e3a52cf1bf105e42043203c485ed9d92 (#18316).

**Comment by fbuihuu** [comment]
Hmm, there's something fishy here, it's now reproducible with v246.

@yuwata can you reproduce the issue on your side ?

**Comment by fbuihuu** [comment]
It doesn't look specific to my system as I can reproduce the problem on f33 (v246.14-1.fc33).

**Comment by dtardon** [comment]
> @dtardon are you working on a PR? I see the commits tagged - wondering whether to keep this in the milestone or move it

I am. I just need to test the latest version and then, if it still works, I'll file a PR. But I'm not very happy about the change, as it makes the asynchronous polkit query handling in `bus-polkit.c` even more complex than it already is (esp. wrt. memory cleanup), so maybe it would be better to postpone this...

**Comment by bluca** [comment]
ok, I'll push it to v254
