### ISSUE TITLE
systemctl (>=227) fails in chroots instead of ignoring

### ISSUE THREAD

**Issue by absurd34** [systemd/systemd#2015]
Hi systemd maintainers,

since systemd 227, the behaviour of systemctl in chroot environments has changed:

<= 226: Ignored, retval 0:
 # root? systemctl restart non-existing.service
 Running in chroot, ignoring request.

> = 227: Fails, retval 6:
>  # root? systemctl restart non-existing.service
>  Failed to restart non-existing.service: Unit non-existing.service failed to load: No such file or directory.

Fwiw, In the (227 failing) case, the error of systemctl varies, depending on how your chroot is setup -- in a more sparse setup than mine, you will probably get the dbus error first; in any case however, 226 just "works fine" and ignores the call.

This does also occur an actual packages/services, which effectively breaks (Debian) package installation and removal in chroots (unless especially patched). This Debian bug report

https://bugs.debian.org/802780

has some more information about this.

So was the chroot ignore check removed intentionally, or is this just a bug?

Imho, the previous behaviour should be re-established.

Thanks!

S

**Comment by poettering** [comment]
Fix waiting in #2465.
