### ISSUE TITLE
Failed to resolve unit specifiers in %f: Invalid argument

### ISSUE THREAD

**Issue by mildred** [systemd/systemd#20150]
**systemd version the issue has been seen with**
> systemd 248 (248.3-2-arch)
> +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Manjaro Linux

**Linux kernel version used** (`uname -a`)
 > `Linux min 5.12.11-1-MANJARO-ARM #1 SMP Wed Jun 16 13:18:32 UTC 2021 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > systemd templated user unit should work or at least the error should be a little more specific

**Unexpected behaviour you saw**
 > /home/mildred/.config/systemd/user/cleanup-dir@.service:5: Failed to resolve unit specifiers in %f: Invalid argument

**Steps to reproduce the problem**

I added a user service to my installation in the form of:

```desktop
[Unit]
#Description=Cleanup %f

[Service]
ExecStart=/usr/bin/env cleanup-dir %f
```

File location: `~/.config/systemd/user/cleanup-dir@.service`

After running `systemctl --user daemon-reload` and `systemctl --user start cleanup-dir@-home-mildred-Downloads.service` I get the following error:

> `Failed to start cleanup-dir@-home-mildred-Downloads.service: Unit cleanup-dir@-home-mildred-Downloads.service has a bad unit file setting.`
> `See user logs and 'systemctl --user status cleanup-dir@-home-mildred-Downloads.service' for details.`

The status gives me the errors:

> `juil. 07 10:33:32 min systemd[3955]: /home/mildred/.config/systemd/user/cleanup-dir@.service:5: Failed to resolve unit specifiers in %f: Invalid argument`
> `juil. 07 10:33:32 min systemd[3955]: cleanup-dir@-home-mildred-Downloads.service: Unit configuration has fatal error, unit will not be started.`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
the instance part of `cleanup-dir@-home-mildred-Downloads.service` is not properly escaped according to the escaping rules. Drop the leading "-", then it should work, no?
