### ISSUE TITLE
logind: allow triggering custom service on button press/hold

### ISSUE THREAD

**Issue by robimarko** [systemd/systemd#20175]
**Is your feature request related to a problem? Please describe.**
Currently, logind has no support for triggering a systemd service when a button is presed or held.
It can only trigger one of the predefined handlers like reboot, poweroff, etc.

**Describe the solution you'd like**
I would like to have a way to trigger a systemd service instead of existing handlers.
This would allow using the same(Usually the only) button to trigger a factory reset on the device
instead of only reboot/poweroff and other predefined handlers.
This is a common feature in systems using OpenWrt and similar distributions.

**Describe alternatives you've considered**
No possible alternatives as there is a fixed number of handlers currently supported, no support
for a user systemd service to be called.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by robimarko** [comment]
@yegor-alexeyev Any ideas.

**Comment by poettering** [comment]
i wouldn#t want to open this too liberally. However, I sympathize with the factory reset case. Maybe we should add a generic factory-reset.target, that implements that. Then, teach logind to optionally enter it.

We already have some factory reset concepts in place (see repart), and I think we should hook this up with logind.

**Comment by robimarko** [comment]
I agree, but the issue is that method to do a factory reset varies on embedded devices.
Some use OverlayFS, some two rootfs-es etc, so I am not sure if a generic target could fit all of those.

**Comment by poettering** [comment]
well, we'd define factory-reset.target, and people hook into that the services of their choice. We could offer some with the repart thing, but it would be up to the local developers to add watever they need. In fact they could even plug in multiple services if they like, for example one thing that resets the OS, and another one that resets the home dirs, and so on.

**Comment by robimarko** [comment]
That sounds good to me.

**Comment by poettering** [comment]
I guess we can close this given that #20302 was merged.
