### ISSUE TITLE
`systemd-inhibit` and prologing awake state

### ISSUE THREAD

**Issue by kiminuo** [systemd/systemd#20174]
Hi team,

I have read http://manpages.ubuntu.com/manpages/focal/man1/systemd-inhibit.1.html and I still wonder what the following command exactly does: 

```bash
systemd-inhibit --what="idle:sleep" --mode=block sleep 3600
```

I understand that a computer cannot go to sleep for one hour (unless the associated process is killed). But then I'm not sure whether after that one hour period it may happen that the computer can go immediately sleep or not. Meaning, does the command above resets an idle timer or not? If not, is there a command to reset "an idle timer" (if it exists)?

Thank you!

Originally posted here: https://askubuntu.com/questions/1350674/systemd-inhibit-and-prologing-awake-state

**Comment by poettering** [comment]
Once the last idle inhibitor is gone the machine can instantly go to suspend, if the last "not idle" ping was received long enough ago. But note that not all desktops actually send that ping, but insteadl do their own idle logic.

Anyway, this is not a support forum, but a bug tracker. If you have questions, please send your query to systemd-devel or so, but let's leave this here for bugs and feature requests. Thank you for understanding.
