### ISSUE TITLE
systemctl help machines.target does not open the systemd.special(7) manpage

### ISSUE THREAD

**Issue by schuelermine** [systemd/systemd#20189]
**systemd version the issue has been seen with**
systemd 247 (`247.3-3ubuntu3.1pop1~1623176805~21.04~74cb00e`)

**Used distribution**
Pop!_OS 21.04

**Linux kernel version used** (`uname -a`)
5.11.0-7620-generic `#21~1624379747~21.04~3abeff8-Ubuntu`

**CPU architecture issue was seen on**
x86-64

**Expected behaviour you didn't see**
`systemctl help machines.target` opens the manpage `systemd.special(7)`, as happens with other units described there

**Unexpected behaviour you saw**
`systemctl` prints nothing and exits with status code 1

**Steps to reproduce the problem**
run `systemctl help machines.target`

**Additional program output to the terminal or log subsystem illustrating the issue**
nothing

**Comment by Osrepnay** [comment]
I'm on Linux 5.12.14 on Arch with systemd version 248 and could not reproduce, maybe a problem with vers 247?

**Comment by schuelermine** [comment]
possible, can’t upgrade to check
feel free to close if you believe this is resolved
