### ISSUE TITLE
Verbose systemd logs for mount succeeded 

### ISSUE THREAD

**Issue by msschl** [systemd/systemd#20184]
**systemd version the issue has been seen with**

```
systemd --version
systemd 245 (245.4-4ubuntu3.7)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Linux kernel version used** (`uname -a`)

```
uname -a
Linux lxkubenode02 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I opened this issue also on `cri-o/cri-o`, and `opencontainers/runc`. [cri-o/cri-o#5064](https://github.com/cri-o/cri-o/issues/5064), [opencontainers/runc#3083](https://github.com/opencontainers/runc/issues/3083)

**Description**

```
Jul 09 12:15:42 lxkubenode02 systemd[1]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.4po0xy.mount: Succeeded.
Jul 09 12:15:42 lxkubenode02 systemd[663855]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.4po0xy.mount: Succeeded.
Jul 09 12:15:44 lxkubenode02 systemd[1]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.u9nGFW.mount: Succeeded.
Jul 09 12:15:44 lxkubenode02 systemd[663855]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.u9nGFW.mount: Succeeded.
Jul 09 12:15:46 lxkubenode02 systemd[663855]: run-runc-ce7517c93e09e8f18ed5483cce138483781a7d8d34322bb1543c2163694772ee-runc.bjm8Fp.mount: Succeeded.
Jul 09 12:15:46 lxkubenode02 systemd[1]: run-runc-ce7517c93e09e8f18ed5483cce138483781a7d8d34322bb1543c2163694772ee-runc.bjm8Fp.mount: Succeeded.
Jul 09 12:15:49 lxkubenode02 systemd[1]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.rv3k3B.mount: Succeeded.
Jul 09 12:15:49 lxkubenode02 systemd[663855]: run-runc-b611a3bdf936d64e8983e045c27cd142949b6a54e772846f7750ca7ced35e5ea-runc.rv3k3B.mount: Succeeded.
Jul 09 12:15:52 lxkubenode02 systemd[663855]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.pnqjUW.mount: Succeeded.
Jul 09 12:15:52 lxkubenode02 systemd[1]: run-runc-bd72a510b8f38c6337dfa0298f9cc6969b355fa3da4770143244f74d46fb52f8-runc.pnqjUW.mount: Succeeded.
```

It looks like a [issue docker had once](https://github.com/docker/for-linux/issues/679), and is related to healthchecks.

**Output of `crio --version`:**

```
$ crio --version
INFO[0000] Starting CRI-O, version: 1.20.3, git: 50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d(clean)
crio version 1.20.3
Version:       1.20.3
GitCommit:     50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d
GitTreeState:  clean
BuildDate:     2021-06-03T20:25:45Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- K8s cluster deployed with kubeadm on ubuntu 20.04 vms

**Comment by msschl** [comment]
Maybe related to #6432 - Filter mechanism for logs in journald

**Comment by ziggythehamster** [comment]
> It looks like a issue docker had once, and is related to healthchecks.

It definitely has it still, but Docker decided that they can't fix this, so they closed the issue. The proposed workaround is to disable health checks, which you would never do on a production system. Apparently, the way that the container runtime starts stuff is different when using systemd for cgroups, so the messages don't appear with the same frequency there.

#6432 would certainly be a generic solution, but simply not logging anything on a mount unit would solve my complaints. Though I would bet that others would want mounts to be logged, so it would need to be configurable.

**Comment by poettering** [comment]
seems pretty broken in docker to leak all these mounts to the host.

I am not convinced we should stop logging about units starting and shutting down. That said, you can manually configure things that way if you like, since c2503e359a3a03b73acce0a92d27b1b8f54ff92c. You could use that to define a drop-in that turns it off for all those messy docker mounts.

But I think it's pretty broken that docker lets its management mounts leak into the host like that. They are doing something wrong there...

Anyway, closing.

**Comment by msschl** [comment]
Well, it's not just docker. `cri-o` has the same behaviour as well.

**Comment by ziggythehamster** [comment]
> But I think it's pretty broken that docker lets its management mounts leak into the host like that.

Docker isn’t magic; a container root or mount is a normal mount. It’s best to think about it like chroots with extra isolation, security, and tooling. They do use namespaces and cgroups to do isolation, which I believe applies to mounts as well, but that doesn’t keep systemd from seeing the mounts.

> you can manually configure things that way if you like

I’m not sure how this would be possible because it’s not possible to know the mount path ahead of time to install a drop-in. You’d need a drop-in that applied to everything under a particular subpath, and I’m not sure how someone might do that. Forgive me if this is actually possible; I know there’s a path inheritance mechanism for slices, but I don’t know if mounts do the same thing or not.

**Comment by poettering** [comment]
> Docker isn’t magic; a container root or mount is a normal mount. It’s best to think about it like chroots with extra isolation, security, and tooling. They do use namespaces and cgroups to do isolation, which I believe applies to mounts as well, but that doesn’t keep systemd from seeing the mounts.

the point of mount namespacing is that their container mounts dont become visible on the host, but are local to their container.

**Comment by poettering** [comment]
> I’m not sure how this would be possible because it’s not possible to know the mount path ahead of time to install a drop-in. You’d need a drop-in that applied to everything under a particular subpath, and I’m not sure how someone might do that. Forgive me if this is actually possible; I know there’s a path inheritance mechanism for slices, but I don’t know if mounts do the same thing or not.

Check the docs, you can install a drop-in that applies to any units that are a suffix of some prefix.
