### ISSUE TITLE
networkd: Ability to add route with Gateway=_dhcp4 without getting default route from DHCP

### ISSUE THREAD

**Issue by Jaakkonen** [systemd/systemd#20208]
**Is your feature request related to a problem? Please describe.**
The case where you have a mobile device with wlan connectivity where you want all of your traffic to go through a VPN is currently served pretty badly by systemd-networkd.
The want is to create a route from the gateway of any wlan you connect to, to the VPN endpoint and then to use another systemd unit to establish the VPN connection and default route.

Currently if `UseGateway=no` no routes referencing to gateway are added. This gets rid of the `default via @GATEWAY@ dev wlan0` route but in this case the `[Route]` with `Gateway=_dhcp4` is not added either.

The `UseRoutes=no` option does not seem to affect this.

**Describe the solution you'd like**
Ability to use `Gateway=_dhcp4` in routes without adding default route via gateway.

**Describe alternatives you've considered**
- Adding a "dummy" route with higher priority so that the default route by networkd does not allow any traffic to leak past. This is a hack and not a clean solution.
- Use another DHCP client with ability to hook into events. For example add a dummy route, wait for wlan to connect and to acquire DHCP lease, delete DHCP default route, delete dummy default route. And add the VPN default route at some point in that chain. This again is a horrible hack.

**The systemd version you checked that didn't have the feature you are asking for**
249 (Arch Linux version 249-2)

**Comment by yuwata** [comment]
If possible, please test #20209. Thank you.

**Comment by Jaakkonen** [comment]
I'll test the PR branch tomorrow (UTC time). Thank you really much for the quick PR :)

**Comment by Jaakkonen** [comment]
Works like a charm. Config:
```
[Match]
name=wlan0

[Network]
Address=DHCP
DHCP=ipv4
Xfrm=vpn0

[DHCPv4]
UseDNS=no
UseRoutes=yes
UseGateway=no

[Route]
Destination=<vpn gateway ip>/32
Gateway=_dhcp4
```

**Comment by yuwata** [comment]
Thank you for testing.
