### ISSUE TITLE
Internet is broken with DNSOverTLS enabled

### ISSUE THREAD

**Issue by MartinX3** [systemd/systemd#20211]
**systemd version the issue has been seen with**
 > 249

**Used distribution**
 > EndeavourOS / ArchLinux

**Linux kernel version used** (`uname -a`)

 > `Linux deus-ex-machina 5.12.15-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 07 Jul 2021 23:35:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > A working resolution

**Unexpected behaviour you saw**
```
resolvectl query google.com
google.com: resolve call failed: All attempts to contact name servers or networks failed
```

**Steps to reproduce the problem**
> Using a Fritz!Box as DNS Server.
Which uses 149.112.112.112 for DNS (Quad9, Supports DoT)

**Additional program output to the terminal or log subsystem illustrating the issue**

> [journalctl.log.txt.zip](https://github.com/systemd/systemd/files/6803991/journalctl.log.txt.zip)

**Comment by dnicolodi** [comment]
Does the DNS server on the Fritz!Box support DNS-over-TLS? I don't think so. Being it a completely different protocol it does not matter whether the DNS server the caching DNS server on the Fritz!Box uses supports DNS-over-TLS or not.

**Comment by MartinX3** [comment]
@dnicolodi why you don't think so?
A Fritz!Box supports DoT.

Btw I tested it with a DoT server directly as well (DNS property in the config file)

**Comment by dnicolodi** [comment]
Can you please point me to where the support for DoT in the Fritz!Box standard firmware is advertised? All I find is that the caching DNS in the Fritz!Box supports querying via DoT, not that it exposes a DoT server to the internal network.

**Comment by MartinX3** [comment]
![image](https://user-images.githubusercontent.com/4518092/125936474-be01643a-2f40-460b-959e-0b5eac37179e.png)

**Comment by bermeitinger-b** [comment]
This means that the FritzBox uses the listed servers with DoT. It does not expose a DoT interface!

Your PC -> DNS inside your own LAN -> FritzBox -> DoT over Internet

**Comment by poettering** [comment]
to my knowledge the firtzbox only supports dot between fritzbox and upstream server, but it doesn't itself speak dot towards its clients.

What precisely did you configure in resolved.conf?

What's in the logs? in partcular if you turn on debug logging?

**Comment by poettering** [comment]
Yeah, the logs you aready supplied make this very clear: any attempts to reach the fritzbox via dot fail with connection refused.

And since you don't allow any fallbcak this is doomed to fail.
