### ISSUE TITLE
[udev] identically named partitions trigger pathological performance in link_update() & link_find_prioritized()

### ISSUE THREAD

**Issue by ipilcher** [systemd/systemd#20212]
**systemd version the issue has been seen with**
> 248.3

**Used distribution**
> Fedora 34

**Linux kernel version used** (`uname -a`)
 > `Linux n5550.penurio.us 5.12.14-300.fc34.x86_64 #1 SMP Wed Jun 30 18:30:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Successful boot in a reasonable amount of time

**Unexpected behaviour you saw**
 > udev race condition(?) caused very long boot times and/or device timeouts when "large numbers" of block devices are attached.

**Steps to reproduce the problem**
 > Attempt to boot NAS with 5 data disks, each with 16 partitions installed.  (NAS boots fine when data disks are not installed.)

This is basically an upstream clone of an issue that was fixed in Red Hat Enterprise Linux 8.  Unfortunately, the Red Hat Bugzilla is not public, but you can see the pull request at https://github.com/redhat-plumbers/systemd-rhel8/pull/175.

From what I can tell, the problematic upstream commits are:
* https://github.com/systemd/systemd/commit/30f6dce62cb3a738b20253f2192270607c31b55b
* https://github.com/systemd/systemd/commit/996c83903da5bf8b371314b4207ff97afeef65a4

This is borne out by the fact that a test RPM built from https://github.com/systemd/systemd-stable/commit/a59b0a9f768f6e27b25f4f1bab6de08842e78d74 boots in the expected amount of time, and an RPM built from https://github.com/systemd/systemd-stable/commit/30f6dce62cb3a738b20253f2192270607c31b55b does not.

**Comment by ipilcher** [comment]
@msekletar - You mentioned in the RHEL bug that you have had some conversations about approaches to this issue.  Can you share those?

**Comment by ipilcher** [comment]
FYI, CPU speed definitely affects this issue (which makes sense, as it seems to be some sort of race condition).

I've been able to reproduce this issue in a VM.  The basic steps I took were:

- Create a Fedora 34 VM.
    - 4 VCPUs.  (Probably not necessary, but I configured them as 1 socket, 2 cores, 2 threads.)
    - 8 GB
    - VirtIO SCSI controller
    - SCSI disk
- Shut down the VM and use `virsh edit`, **virt-manager**, etc. to change the type of the domain from `kvm` to `qemu`.  (This simulates the effect of the slow Atom D2550 CPU in my NAS.)
- Boot the VM.  Note that, while slower, it still boots in a reasonable amount of time (<1 minute).
- Shut down the VM and add 5 "data disks," 8TB each.  (Using the default QCOW2 format, each disk will only consume about 600KB of actual disk space.)
- Boot the VM and create a 16 data partitions on each disk (see below).
- Reboot the VM.  Note that it boots very slowly, devices time out, etc.

Notes:

To create the "data disk" images (run on the hypervisor):

```
# for I in {0..4} ; do qemu-img create -f qcow2 fedora34-data${I}.qcow2 8T ; done
```

To create the partitions (run in the guest):

> (The boot drive is `sdf` in my VM; run `lsblk` to check.)

```
# for D in /dev/sd{a..e} ; do
    for I in {1..16} ; do
        sgdisk -n ${I}:0:+976752640 -t ${I}:8301 -c "${I}:RAID member" $D
    done
done
```

> (Setting the partition types is almost certainly unnecessary, but it matches what I use on my NAS.)

**Comment by yuwata** [comment]
@ipilcher Hi. Could you test and benchmark #20603?

**Comment by ipilcher** [comment]
> @ipilcher Hi. Could you test and benchmark #20603?

Looks much better.

| Disks | Named partitions per disk | Total named partitions | Calls to `link_find_prioritized()` | Loop iterations |
|-------|---------------------------|------------------------|------------------------------------|-----------------|
| 5 | 0 | 0 | 240 | 720 |
| 5 | 4 | 20 | 260 | 974 |
| 5 | 8 | 40 | 280 | 1,624 |
| 5 | 12 | 60 | 302 | 2,851 |
| 5 | 16 | 80 | 322 | 4,367 |

It does still curve up a bit a the end, so I suppose that really large numbers of "competing" devices might still be an issue, but it's a tremendous improvement over the previous situation.  (I.e. it "fixes" the issue for my configuration.)

**Comment by yuwata** [comment]
@ipilcher Thank you for the test. Wow, the improvement looks much significant than I expected! How about the time and CPU consumption?

**Comment by ipilcher** [comment]
> @ipilcher Thank you for the test. Wow, the improvement looks much significant than I expected! How about the time and CPU consumption?

I haven't testing the fix on my NAS, only in a VM.

The VM has 4 VCPUs running on a Ryzen 7 3700x.  Loading the `virtio_scsi` module with 80 identically named partitions pegs all 4 VCPUs for approximately 33 seconds.  (On my Atom D2550-powered NAS, it lasts for several minutes ... long enough for the boot to fail because devices time out.)

With the fix, loading the module in the VM causes a barely noticeable blip in the CPU usage shown in `virt-manager`.  The logs show that processing all 80 identically named partitions takes about 4 seconds (but that includes the time spent waiting for the workers to exit).

**Comment by yuwata** [comment]
Thank you!

**Comment by poettering** [comment]
> It does still curve up a bit a the end, so I suppose that really large numbers of "competing" devices might still be an issue, but it's a tremendous improvement over the previous situation. (I.e. it "fixes" the issue for my configuration.)

We could do exponential back-off, btw, to improve siutation with large numbers. i.e. prolong our sleep time in each iteration, i.e. if we notice that things are still contended after we slept a random time, then be nice and step away for a bit longer.

**Comment by mbiebl** [comment]
This issue is now hitting Debian bullseye, which uses v247.x
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993738

@yuwata @msekletar : what would you recommend here? Should I revert commits 30f6dce and 996c839?

Would a backport of #20603 to systemd-stable v247-stable be an option?

**Comment by msekletar** [comment]
@mbiebl well for RHEL-8.4 we have reverted those commits. We did this in the interim, until we figure out what followups are needed to fix this fully. Thankfully, @yuwata did fix it now.

Hence, my advice is to revert until there is a backport in stable branch. Btw, backport will require a bit of work as it doesn't apply cleanly.

**Comment by mbiebl** [comment]
That's basically why I'm asking (If a backport is planned/is an option)

**Comment by mbiebl** [comment]
@msekletar did you decide to backport all commits from #20603 or did you stick with the revert in RHEL?
