### ISSUE TITLE
Nofail option doesn't work with systemd-249

### ISSUE THREAD

**Issue by Arvamer** [systemd/systemd#20224]
**systemd version the issue has been seen with**
 
249

**Used distribution**

Archlinux

**Linux kernel version used** (`uname -a`)

 `Linux archpc 5.12.17-180-tkg-bmq #1 TKG SMP PREEMPT Wed, 14 Jul 2021 16:40:09 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 
 x86_64

**Expected behaviour you didn't see**
 
Mounts with `nofail` option shouldn't  delay boot.

**Unexpected behaviour you saw**
 
I have to wait 1 min 30 s before systemd give up mounting partition.

**Steps to reproduce the problem**
 
Unplug disc with `nofail` option and boot system.

```
# /etc/crypttab

media          UUID=c46a21c3-e8ad-4a3a-9429-86e6b7321729    /etc/luks-keys/media      nofail

# /etc/fstab

/dev/mapper/media       /media       ext4    defaults,nofail   2
 ```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
lip 14 18:28:39 archpc systemd[1]: dev-disk-by\x2duuid-c46a21c3\x2de8ad\x2d4a3a\x2d9429\x2d86e6b7321729.device: Job dev-disk-by\x2duuid-c46a21c3\x2de8ad\x2d4a3a\x2d9429\x2d86e6b7321729.device/start timed out.
lip 14 18:28:39 archpc systemd[1]: Timed out waiting for device /dev/disk/by-uuid/c46a21c3-e8ad-4a3a-9429-86e6b7321729.
lip 14 18:28:39 archpc systemd[1]: Dependency failed for Cryptography Setup for media.
lip 14 18:28:39 archpc systemd[1]: Dependency failed for /dev/mapper/media.
lip 14 18:28:39 archpc systemd[1]: Dependency failed for /media.
lip 14 18:28:39 archpc systemd[1]: media.mount: Job media.mount/start failed with result 'dependency'.
lip 14 18:28:39 archpc systemd[1]: dev-mapper-media.device: Job dev-mapper-media.device/start failed with result 'dependency'.
lip 14 18:28:39 archpc systemd[1]: systemd-cryptsetup@media.service: Job systemd-cryptsetup@media.service/start failed with result 'dependency'.
lip 14 18:28:39 archpc systemd[1]: dev-disk-by\x2duuid-c46a21c3\x2de8ad\x2d4a3a\x2d9429\x2d86e6b7321729.device: Job dev-disk-by\x2duuid-c46a21c3\x2de8ad\x2d4a3a\x2d9429\x2d86e6b7321729.device/start failed with result 'timeout'.
lip 14 18:28:39 archpc systemd[1]: Reached target Block Device Preparation for /dev/mapper/media.
lip 14 18:28:39 archpc systemd[1]: Reached target Local File Systems.
```

**Comment by Exagone313** [comment]
Just for the record, I can reproduce the issue without LUKS.

**Comment by ruuda** [comment]
I can reproduce with Arch package 249-3, and after downgrading to 248.3-2 I can no longer reproduce.

Possible suspect: fa138f5e26742f83a762b2809a1891978c6aa04a.

**Comment by poettering** [comment]
I guess we should check for nofail in that commit, too.

**Comment by ruuda** [comment]
I think this or something related to it regressed in the past ~two months (currently running `250.5-1-arch`); if I boot my laptop without any external drives attached, it waits 90 seconds before continuing to boot. But it doesn’t delay the boot if *some* drives are present.
