### ISSUE TITLE
systemd-resolved: simple DNS caching server

### ISSUE THREAD

**Issue by robimarko** [systemd/systemd#20221]
**Is your feature request related to a problem? Please describe.**
In some embedded configurations, there is sometimes a need for a very simple caching DNS server. Systemd-resolved looks like it can provide this.

**Describe the solution you'd like**
Right now  DNS stub listener is fixed to listen on 127.0.0.53. I would like to be able to set up an arbitrary network address to set up listener on.

**Describe alternatives you've considered**
An alternative would be to set up some kind of proxy to forward network DNS requests to the local stub listener. However, that would make the entire design more complex in the long run. Especially since we would like to further extend the systemd's DNS codebase since systemd already has internally already all the DNS-related code.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by dnicolodi** [comment]
Isn't the `DNSStubListenerExtra=` option enabling exactly this?

**Comment by anitazha** [comment]
Closing since `DNSStubListener=` and `DNSStubListenerExtra=` should handle this. If it doesn't please reopen.
