### ISSUE TITLE
[Feature request] #snapsafe: introduce 'snapshot' and 'resume' inhibitors

### ISSUE THREAD

**Issue by acatangiu** [systemd/systemd#20222]
**Is your feature request related to a problem? Please describe.**

This is a spin-off of https://github.com/systemd/systemd/issues/19269

In virtualized or containerized environments, applications that work with local copies or caches of world-unique data such as random values, uuids, monotonically increasing counters, cryptographic nonces, etc. can be negatively affected by VM or container snapshotting when the VM or container is either cloned or returned to an earlier point in time.

Following a VM or container snapshot, the data in the image in no longer unique, for example:
- PRNG seeds for anything using openssl
- UUIDs in random code (sid in smbd or avahi for example)
- Anything using stateful networking, connections, sessions, etc

General purpose software as well as language runtimes can handle their specific usecases if the system would provide an asynchronous interface that allows them to be notified of and do work at specific points in the snapshot lifecycle:
- `before-snapshot`/`prepare-for-snapshot`
- `post-snapshot`/`prepare-for-resume`

As described in https://github.com/systemd/systemd/issues/19269#issuecomment-822552884 this would allow the system to have four states: `running → queiscing/preparing-for-snap → quiesced/snapshotted → unquiescing/preparing-for-resume → running`.

Systemd is a great candidate to provide this foundational functionality under the "inhibitors" functionality in `systemd-login`.

**Describe the solution you'd like**

Linux kernel component to expose a u32 sysgenid counter in /sys or /proc somewhere, world-readable. This could be driven by `vmgenid`-like devices.

We could introduce a new file `/run/sysgen-id` or so that is either a symlink to the aforementioned kernel-provided file, or is managed in userspace by PID 1 (for container mgrs, where the generation should expose the snapshot logic of the container, not of the surrounding host); declare that `inotify`, `mmap`, `mtime` all work on the file as one would expect to, regardless if kernel provided or userspace provided.

This model is also backwards compatible with the kernel SysGenID patch [1]. For example, there’s a PR (https://github.com/awslabs/aws-lc/pull/179) [2] in AWS libcrypto (AWS crypto lib based on BoringSSL and OpenSSL) that makes AWS-LC #snapsafe using kernel SysGenID device. For this lib and other *SSL libs, the same patch/change will work out of the box with approach described above - only thing different would be the configurable file path: /run/sysgen-id instead of /dev/sysgenid.

Then there’s the asynchronous part the story, for those components that need to do "new-generation-id" event coordinating.
For this, we modeled and validated a solution based on `quiesce`/`snapshot` and `unquiesce`/`resume` inhibitors:

As described in https://github.com/systemd/systemd/issues/19269#issuecomment-822552884 there'd be two actions that can be inhibited: "quiesce" (create snapshot) and "unquiesce" (resume workload after loading from snapshot).

Software such as networkd/NetworkManager would install a delay inhibitor for the former, and openssl/avahi/… for the latter. Then, when the dance is started we first do the "queiscing" inhibitor dance. Then we are officially "quiesced". Then we'll do the "unquiescing" dance, and once that's achieved we are back running again.
The system would have four states: running → queiscing → quiesced → unquiescing → running

Language runtimes would install both inhibitors and offer equivalent language specific runtime interfaces/events to generic software running under said runtimes.

For example, these inhibitors can be used as a backend for [Java Coordinated Restore at Checkpoint](https://crac.github.io/jdk/jdk-crac/api/java.base/jdk/crac/package-summary.html) [3] as a possible mechanism to make Java Applications #snapsafe.

I strongly believe if we provide the above in `systemd`, we would provide a great foundational step to fuel further innovation in this space.

Would you accept the above if we were to contribute it to `systemd`?

[1] https://lkml.org/lkml/2021/3/8/677
[2] https://github.com/awslabs/aws-lc/pull/179
[3] https://crac.github.io/jdk/jdk-crac/api/java.base/jdk/crac/package-summary.html

**Describe alternatives you've considered**
- System Generation ID as systemd new DBus service https://github.com/systemd/systemd/issues/19269
- System Generation ID as a userspace systemd plugin service (standalone DBus service unit, not baked in systemd)
- System Generation ID kernel driver - https://lkml.org/lkml/2021/3/8/677

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by bluca** [comment]
Sounds like a nice and useful feature to have

**Comment by acatangiu** [comment]
Then I'll start working on a patch

**Comment by acatangiu** [comment]
I went through [systemd contribution docs](https://github.com/systemd/systemd/blob/main/docs/CONTRIBUTING.md) and found nothing related to new feature design review.

Should we first agree on a design for this feature, or is it small enough that we can directly go for a PR?

**Comment by bluca** [comment]
IMHO there was enough discussion in the other ticket, I'd suggest to just go for a PR and take it from there

**Comment by poettering** [comment]
So I think we kinda all agreed that instead of an explicit snapshot/resume inhibitor a clone should just be treated as a system suspend. Hence closing this.
