### ISSUE TITLE
systemd-fsck doesn't honor nofail

### ISSUE THREAD

**Issue by scottlamb** [systemd/systemd#20237]
**systemd version the issue has been seen with**
> `systemd 249 (249-115-g942a69e)`

To be precise, I originally observed this with my distribution package:
 > `systemd 247 (247.3-3ubuntu3.1)`

but I've tested `systemd-fsck` behavior at HEAD; it looks the same.

**Used distribution**
 > Ubuntu 21.04 (Hirsute Hippo)

**Linux kernel version used** (`uname -a`)

 > `Linux slamb-workstation 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > system performs a fsck on `nofail` filesystem but continues to boot even if it fails

This is the behavior I expected given this text in the `systemd-fsck` manpage:

```
       If a file system check fails for a service without nofail, emergency mode is activated, by isolating to
       emergency.target.
```

**Unexpected behaviour you saw**
 > system sees exit status 4 from fsck and goes into emergency mode

**Steps to reproduce the problem**
Prepare a corrupt filesystem. I did this as follows:
```
$ sudo mkfs.ext4 /dev/sdb2
...
$ sudo debugfs -w /dev/sdb2
debugfs 1.45.7 (28-Jan-2021)
debugfs:  blocks /lost+found
9236 9237 9238 9239
debugfs:  zap_block 9236
debugfs:  dirty
```

Add it to `/etc/fstab` with `nofail` and a non-zero pass:

```
/dev/sdb2        /media/bad      ext4    nofail          0        2
```

Reboot.

**Additional program output to the terminal or log subsystem illustrating the issue**

Output from the head build:
```text
[slamb@slamb-workstation ~/git/systemd]$ sudo SYSTEMD_LOG_LEVEL=debug build/systemd-fsck /dev/sdb2
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Successfully forked off '(fsck)' as PID 16476.
/dev/sdb2 contains a file system with errors, check forced.
/dev/sdb2: Directory inode 11, block #0, offset 0: directory corrupted


/dev/sdb2: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
        (i.e., without -a or -p options)
fsck failed with exit status 4.
fsck failed with exit status 4.
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Running request emergency.target/start/replace
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnitReplace cookie=1 reply_cookie=0 signature=sss error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=org.freedesktop.systemd1.NoSuchJob error-message=No job queued for unit basic.target
Bus n/a: changing state RUNNING → CLOSED
```
(My system didn't actually go into emergency mode, presumably because it's already reached the correct target? I'm not quite sure how this works.)

Output from the actual boot with Ubuntu packages:
```
Jul 16 16:46:24 slamb-workstation systemd-fsck[937]: /dev/sdb2: Directory inode 11, block #0, offset 0: directory corrupted
Jul 16 16:46:24 slamb-workstation systemd-fsck[937]: /dev/sdb2: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
Jul 16 16:46:24 slamb-workstation systemd-fsck[937]:         (i.e., without -a or -p options)
Jul 16 16:46:24 slamb-workstation systemd-fsck[932]: fsck failed with exit status 4.
Jul 16 16:46:24 slamb-workstation systemd-fsck[932]: Running request emergency.target/start/replace
Jul 16 16:46:25 slamb-workstation systemd[1]: systemd-fsck@dev-sdb2.service: Main process exited, code=exited, status=1/FAILURE
```
(and my system really did go into emergency mode)

It looks like the fstab generator saw the `nofail` attribute. I see a symlink `/run/systemd/generator/local-fs.target.wants/media-bad.mount` rather than `/run/systemd/generator/local-fs.target.requires/media-bad.mount`, and writes out `nofail` in its unit file:

```
[slamb@slamb-workstation /run/systemd/generator]$ cat media-bad.mount
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/etc/fstab
Requires=systemd-fsck@dev-sdb2.service
After=systemd-fsck@dev-sdb2.service
After=blockdev@dev-sdb2.target

[Mount]
Where=/media/bad
What=/dev/sdb2
Type=ext4
Options=nofail
```

but fsck (specifically `src/fsck/fsck.c`, `run`) doesn't know if the mount is nofail or not as far as I can tell, and decides to go to emergency mode all on its own:

```
        if ((exit_status & ~FSCK_ERROR_CORRECTED) != FSCK_SUCCESS) {
                log_error("fsck failed with exit status %i.", exit_status);

                if ((exit_status & FSCK_SYSTEM_SHOULD_REBOOT) && root_directory) {
                        /* System should be rebooted. */
                        start_target(SPECIAL_REBOOT_TARGET, "replace-irreversibly");
                        return -EINVAL;
                } else if (exit_status & (FSCK_SYSTEM_SHOULD_REBOOT | FSCK_ERRORS_LEFT_UNCORRECTED))
                        /* Some other problem */
                        start_target(SPECIAL_EMERGENCY_TARGET, "replace"); <--------- HERE
                else
                        log_warning("Ignoring error.");
        }
```

**Comment by arvidjaar** [comment]
This has always been this way from the very beginning. Description of `nofail` was added to manual page in commit a17f2dc15b84c158a13968b4dbef92ae4f45c572 (@keszybz). Sounds more like documentation issue.

**Comment by scottlamb** [comment]
From my own code archeology, I agree it's always been this way, but I would prefer the code change to match the documented behavior than the reverse. I suspect it's not possible now to guarantee that even a `noauto` mount which is wanted by some other unit later on will not cause the system to go into emergency mode due to fsck failure. (Or if it is, it'd be by forcing its fsck to be delayed enough that the `start_target` has no effect. But I want a fast boot!) So if I want to have a mount which doesn't ever take the system into emergency mode, I have to give up on using `systemd-fsck` for it entirely. Does that really make sense?

Here's my proposal. I don't know systemd that well, so please tell me if there's an obvious problem with it.

*   rather than calling `start_target(SPECIAL_EMERGENCY_TARGET, ...)` call, just fail the fsck target.
*   leave the `start_target(SPECIAL_REBOOT_TARGET, ...)` call as is.
*   make `./units/systemd-fsck-root.service.in` have `OnFailure=emergency.target` to preserve root fsck failure behavior.

then for `nofail` mounts, if fsck fails the mount unit will fail, but `local-fs.target` will still come up and it will work as documented. For other non-root mounts, if fsck fails the mount will fail, so `local-fs.target` will fail, so its `OnFailure=emergency.target` will apply. The `nofail` behavior will match the documentation and other cases will be essentially unchanged.

One detail I don't get is `replace` vs `replace-irreversibly`. Currently it seems like fsck failure uses `replace` and other mount failures use `replace-irreversibly`. I don't know why. Could this be an oversight?
