### ISSUE TITLE
Can dbus interfaces introspection XML be exported to `/usr/share/dbus-1/interfaces/`?

### ISSUE THREAD

**Issue by igo95862** [systemd/systemd#20238]
Currently the dbus interface XML is either in man pages or must be extracted during run-time.

Exporting them directly to interfaces folder will help code generators for dbus.

I have some ideas on how to export them directly from source code.

**Comment by igo95862** [comment]
> Maybe you could prep a patch? It seems all the parts are in place, it's mostly a matter of figuring out what the file layout should be and hooking up some meson targets.

Sure. I will have some time this weekend.

**Comment by igo95862** [comment]
I started here: #20294

Would you mind providing feedback?

**Comment by splatch** [comment]
@igo95862 Could you count in an extra export for `org.freedesktop.network1`? Currently I can't find anywhere a dbus descriptor of networkd.

**Comment by igo95862** [comment]
> @igo95862 Could you count in an extra export for `org.freedesktop.network1`? Currently I can't find anywhere a dbus descriptor of networkd.

Sadly it does not seem like systemd-networkd implements `--bus-introspect` so it will be much more difficult to implement export.

@keszybz any reason why systemd-networkd does not implement it? I might be able to create a Pull Request.

**Comment by keszybz** [comment]
> @keszybz any reason why systemd-networkd does not implement it? I might be able to create a Pull Request.

There were no API docs for networkd, and I only (or mostly, don't quite recall) added `--bus-introspect` to the services which had the docs to recreate them in the new style. It should be fairly easy to (and useful) to add this to systemd-networkd and provide a stub man page, even without any descriptions.

**Comment by igo95862** [comment]
So the steps would be:

1. Create stub man page that will be updated by `update-dbus-docs.py`
2. Add `--bus-introspect` to systemd-networkd

May I create the PR for this? @keszybz

**Comment by igo95862** [comment]
There was an issue that I opened about it: #20508

**Comment by yuwata** [comment]
> > So the steps would be:
> > ```
> > 1. Create stub man page that will be updated by `update-dbus-docs.py`
> > 
> > 2. Add `--bus-introspect` to systemd-networkd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > May I create the PR for this? @keszybz
> 
> A PR would be welcome.

#21436.
