### ISSUE TITLE
IPv6 addresses time out

### ISSUE THREAD

**Issue by Jookia** [systemd/systemd#20245]
**systemd version the issue has been seen with**
 > systemd 249 (249-3-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `linux titan 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > IPv6 temporary addresses to regularly renew

**Unexpected behaviour you saw**
 > IPv6 temporary addresses timeout and stay timed out

**Steps to reproduce the problem**
 > Set up networkd to use privacy extensions like so:

```[Match]
MACAddress=24:4b:fe:cd:5b:4f

[Network]
Address=192.168.27.7/24
Gateway=192.168.27.1
IPv6PrivacyExtensions=yes
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 24:4b:fe:cd:5b:4f brd ff:ff:ff:ff:ff:ff
    inet 192.168.27.7/24 brd 192.168.27.255 scope global enp4s0
       valid_lft forever preferred_lft forever
    inet6 fd8f:b57c:707a:0:cd30:14de:7a2f:96bf/64 scope global temporary dynamic 
       valid_lft 601940sec preferred_lft 83378sec
    inet6 fd8f:b57c:707a:0:264b:feff:fecd:5b4f/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2406:XXXX:XXXX:XXXX:a23d:1779:1299:6064/64 scope global temporary deprecated dynamic 
       valid_lft 1138sec preferred_lft 0sec
    inet6 2406:XXXX:XXXX:XXXX:264b:feff:fecd:5b4f/64 scope global deprecated dynamic mngtmpaddr noprefixroute 
       valid_lft 1138sec preferred_lft 0sec
    inet6 fe80::264b:feff:fecd:5b4f/64 scope link 
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:f1:68:1c brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever

PING google.com(2404:6800:4006:812::200e (2404:6800:4006:812::200e)) 56 data bytes
From fd8f:b57c:707a::1 (fd8f:b57c:707a::1) icmp_seq=1 Destination unreachable: Unknown code 5
From fd8f:b57c:707a::1 (fd8f:b57c:707a::1) icmp_seq=2 Destination unreachable: Unknown code 5
From fd8f:b57c:707a::1 (fd8f:b57c:707a::1) icmp_seq=3 Destination unreachable: Unknown code 5
```
networkd log: https://gist.github.com/Jookia/9c7182cb9308f76ef5ea5cfa2939f569

**Comment by Jookia** [comment]
I found this happens without privacy extensions too.
Windows 10 seems stable on the same network.

**Comment by yuwata** [comment]
Fix is waiting in #20246. If possible, please test the PR. Thank you.

**Comment by Jookia** [comment]
I patched my systemd version with your patch and it hasn't changed any behaviour.

**Comment by yuwata** [comment]
Hmm, could you provide debugging logs by the patched networkd?

**Comment by Jookia** [comment]
Here you go: https://gist.github.com/Jookia/45045e6fec3c7fd3aabddad761664d0a

**Comment by Jookia** [comment]
I'm willing to dump in any debug patches/tracing/etc required. I'm running an outdated OpenWrt on the router so I can do any packet sniffing there too.

**Comment by yuwata** [comment]
From the second debugging logs:
```
enp4s0: Requesting address: 2406:XXXX:XXXX:XXXX:264b:feff:fecd:5b4f/64 (valid for 26min 19s, preferred for 6min 19s), flags: manage-temporary-address,no-prefixroute
enp4s0: Configuring address: 2406:XXXX:XXXX:XXXX:264b:feff:fecd:5b4f/64 (valid for 26min 19s, preferred for 6min 19s), flags: manage-temporary-address,no-prefixroute
enp4s0: Remembering updated address: 2406:XXXX:XXXX:XXXX:264b:feff:fecd:5b4f/64 (valid for 26min 19s, preferred for 6min 19s), flags: manage-temporary-address,no-prefixroute
enp4s0: Remembering updated address: 2406:XXXX:XXXX:XXXX:b815:f60d:9273:90c7/64 (valid for 26min 19s, preferred for 6min 19s), flags: temporary
(snip)
enp4s0: Remembering updated address: 2406:XXXX:XXXX:XXXX:b815:f60d:9273:90c7/64 (valid for 20min, preferred for 0), flags: temporary,deprecated
enp4s0: Remembering updated address: 2406:XXXX:XXXX:XXXX:264b:feff:fecd:5b4f/64 (valid for 20min, preferred for 0), flags: deprecated,manage-temporary-address,no-prefixroute
```
So, it seems the reported bug is certainly fixed by #20246, and worked as expected. The reason the addresses still become deprecated is that the router does not send RA message within the preferred lifetime (6min 19sec in the above case). I guess, this is a bug or mis-configuration in the router. That is, the timespan of between each periodic RA message (4~7min) is almost equivalent to the preferred lifetime of the prefix.

Note that from [RFC 4861 section-6.3.7](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.7), once we received RA message, then we must not send Router Solicitation messages later unless some configuration is changed. So, we must not request RA message actively, and such a bug or mis-configuration cannot be handled at the host side (i.e. by networkd).

**Comment by yuwata** [comment]
Or, does v248 work fine with the same router??

**Comment by Jookia** [comment]
I can confirm this is a router bug. But systemd is trying to route my traffic through a LAN private address instead of a valid WAN address?

**Comment by Jookia** [comment]
My bad, this is the kernel doing it. It won't route outgoing traffic from deprecated addresses, but will still take incoming traffic on them. My bad.
