### ISSUE TITLE
Systemd 249 network issues after waking from sleep

### ISSUE THREAD

**Issue by oscarpax** [systemd/systemd#20244]
**systemd version the issue has been seen with**
 systemd 249  (249-3-arch)

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)
 `5.12.15-arch1-1`

**CPU architecture issue was seen on**
 amd64 

**Expected behaviour you didn't see**
 Network connection to resume and stay constant with ipv6

**Unexpected behaviour you saw**
 Frequent network connection changes with ipv6 (global) address disappearing and then reappearing. I can reproduce this problem identically with a desktop and a laptop. Rebooting fixes the problem until next sleep. Workaround is to disable systemd-networkd and systemd-resolved, and enabling NetworkManager after which network connection resumes normally even after waking from sleep.

**Steps to reproduce the problem**
 Put the computer to sleep, and then wake it up. This problem only happens after sleep.

**Additional program output to the terminal or log subsystem illustrating the issue**

**Comment by yuwata** [comment]
Could you enable to generate debugging logs of networkd and provide it? The logs can be generated by creating the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by oscarpax** [comment]
Here it is: https://gist.github.com/oscarpax/a6e0f90851f247acc55a7ec19c0ef4b9

**Comment by garw** [comment]
I see the same behavior with systemd `249.1-1` and Linux `5.13.4-arch1-1` also on Arch Linux.

The SLAAC global address is continuously being removed and added to the interface. For me it isn't 100% reproducible after every suspend to RAM cycle but it always occurs after some cycles.
Restarting systemd-networkd doesn't change the behavior. Also removing `/run/systemd/netif` doesn't change the behavior. However, after the next complete reboot, the problem is gone.

Another log to cross reference:
https://gist.github.com/garw/4542a4787d1df964ef32589d6a5cba70

**Comment by Tisalgelijk** [comment]
Can also confirm this behaviour with 249 on Arch Linux. SLAAC addresses alternate between being added and removed with every incoming RA. This only starts happening some time after booting. The resume from suspend others have reported is not directly related, just often a way to move forward in time a few hours.

This comment in issue #20050 references this behaviour: https://github.com/systemd/systemd/issues/20050#issuecomment-872967337

I would guess commit 899034ba8167bd16e802cfbea29a9ee85dee5be5 apparently did not completely fix this issue, but rather delays it until a few hours after a reboot.

**Comment by yuwata** [comment]
@oscarpax and @garw Thank you for providing the debugging logs. I hope #20374 fixes this issue. If possible, please test the PR. Thank you!

**Comment by foxxx0** [comment]
just for reference: i've been using v249 + the proposed patch since this morning including two temporary s2ram + resumes and have not had any issues yet. looks promising!

**Comment by yuwata** [comment]
@foxxx0 Thank you!

**Comment by tboedecker-godaddy** [comment]
Unfortunately, after 2 days with longer s2ram periods (8-10h) the issue now presented itself even with the patch.

It seems that on one RA the SLAAC works and the interface gets configured.
But on the next RA it will just remove the addresses again, without even configuring new ones.
So until the next RA you are left without any IPv6 address configured.
On the next RA the SLAAC works again and the IPv6 addresses are added to the interface.

Did a quick restart of `systemd-networkd.service` to enable debug logging and that didn't resolve the issue so it is not related to long-running instances of networkd.

networkd debug log: https://gist.github.com/tboedecker-godaddy/61877beab331c9d67964f9d66179577b
(I have obfuscated my IPv6 prefix to `3000:aaaa:bbbb::`)

**Comment by foxxx0** [comment]
Unfortunately, after 2 days with longer s2ram periods (8-10h) the issue now presented itself even with the patch.

It seems that on one RA the SLAAC works and the interface gets configured.
But on the next RA it will just remove the addresses again, without even configuring new ones.
So until the next RA you are left without any IPv6 address configured.
On the next RA the SLAAC works again and the IPv6 addresses are added to the interface.

Did a quick restart of `systemd-networkd.service` to enable debug logging and that didn't resolve the issue so it is not related to long-running instances of networkd.

networkd debug log: https://gist.github.com/foxxx0/ff83f6130a9c2b4c7c073a2a52076319
(I have obfuscated my IPv6 prefix to `3000:aaaa:bbbb::`)

**Comment by yuwata** [comment]
@foxxx0 From the debugging log, the first and third RA messages seem to contain autonomous prefix, but the second and fourth do not. So, the IPv6 address is once configured, but removed later. See the following:
```
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: NDISC: Invoking callback for 'router' event.
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Requesting route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Requesting route: dst: 3000:aaaa:bbbb::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Requesting address: 3000:aaaa:bbbb:0:f22f:74ff:fe16:5ade/64 (valid for 12h, preferred for 5min), flags: manage-temporary-address,no-prefixroute
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Setting SLAAC addresses.
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Setting NDisc routes.
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: link_check_ready(): dynamic addresses or routes are not configured.
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Configuring route: dst: 3000:aaaa:bbbb::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:11:31 utgard.lan systemd-networkd[2119957]: br0: Configuring address: 3000:aaaa:bbbb:0:f22f:74ff:fe16:5ade/64 (valid for 12h, preferred for 5min), flags: tentative,manage-temporary-address,no-prefixroute
(snip)
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: NDISC: Invoking callback for 'router' event.
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Requesting route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Requesting route: dst: 3000:aaaa:bbbb::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Setting NDisc routes.
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Configuring route: dst: n/a, src: n/a, gw: fe80::1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Configuring route: dst: 3000:aaaa:bbbb::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: NDisc routes set.
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Removing old NDisc information obtained from fe80::1.
Aug 06 08:12:24 utgard.lan systemd-networkd[2119957]: br0: Removing address: 3000:aaaa:bbbb:0:f22f:74ff:fe16:5ade/64 (valid for 11h 59min 59s, preferred for 4min 59s), flags: manage-temporary-address,no-prefixroute
```

Could you check that the router always send information about the autonomous prefix? If so, could you also check that this behavior can be reproducible with earlier releases, e.g. plain v249 or v248?

**Comment by foxxx0** [comment]
With systemd v248 I've had no such issues even with power-on times for over two weeks with daily suspend periods.

From my ISP I have been assigned a static `/48` prefix from which I can freely request `/64` prefixes through DHCPv6-PD.
On my router there is a simple `radvd` instance running to announce the prefixes per-VLAN and that hasn't been causing any issues since it was setup. Works perfectly fine with Windows, Android, FreeBSD and other Linux clients.

`radvd.conf` excerpt for one of the interfaces:
```
interface intern0 {
  AdvSendAdvert on;
  AdvDefaultLifetime 9000;
  MinRtrAdvInterval 10;
  MaxRtrAdvInterval 120;

  RDNSS fe80::1 {
      AdvRDNSSLifetime 240;
  };

  DNSSL lan {
      AdvDNSSLLifetime 240;
  };

  AdvRASrcAddress {
      fe80::1;
  };

  prefix ::/64 {
    AdvOnLink on;
    AdvAutonomous on;
    AdvRouterAddr on;
    AdvValidLifetime 43200;
    AdvPreferredLifetime 300;
  };
};
```

output from `radvdump` on my machine with systemd v248 now running (shouldn't change with v249 though):
```
[Aug 06 11:08:13] radvdump (233090): br0 recvmsg len=96
[Aug 06 11:08:13] radvdump (233090): receiver if_index: 2
#
# radvd configuration generated by radvdump 2.19
# based on Router Advertisement from fe80::1
# received by interface br0
#

interface br0
{
	AdvSendAdvert on;
	# Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
	AdvManagedFlag off;
	AdvOtherConfigFlag off;
	AdvReachableTime 0;
	AdvRetransTimer 0;
	AdvCurHopLimit 64;
	AdvDefaultLifetime 9000;
	AdvHomeAgentFlag off;
	AdvDefaultPreference medium;
	AdvSourceLLAddress on;

	prefix 2001:4dd0:4cc8::/64
	{
		AdvValidLifetime 43200;
		AdvPreferredLifetime 300;
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	}; # End of prefix definition


	RDNSS fe80::1
	{
		AdvRDNSSLifetime 240;
	}; # End of RDNSS definition


	DNSSL lan
	{
		AdvDNSSLLifetime 240;
	}; # End of DNSSL definition

}; # End of interface definition
```

Please let me know if you need further information.

**Comment by foxxx0** [comment]
Just as an update, I have now dumped 20 consecutive RAs from my router and all of them contain the same information, including the
```
	prefix 3000:aaaa:bbbb::/64
	{
		AdvValidLifetime 43200;
		AdvPreferredLifetime 300;
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	}; # End of prefix definition
```
block.

So the RAs should not be the issue here but rather what systemd does with them.

**Comment by yuwata** [comment]
@foxxx0 Thanks. Could you also try to apply #20389?

**Comment by foxxx0** [comment]
compiled, installed and rebooted.

will continue to observe and report back in 2-3 days if it keeps working as intended. (or earlier if it fails before that)

**Comment by yuwata** [comment]
Thank you!

**Comment by foxxx0** [comment]
Almost reached 3d uptime with multiple s2ram periods, some of them even for ~12 hours and haven't encountered this issue yet.
So I'm cautiously optimistic that the two commits have fixed this regression.

**Comment by yuwata** [comment]
Thank you for testing!
