### ISSUE TITLE
Systemd 249 breaks keyboard (keysym values)

### ISSUE THREAD

**Issue by YvanFournier** [systemd/systemd#20243]
**systemd version the issue has been seen with**
 > systemd 249 (249-3-arch)

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)

 > `5.12.15-arch1-1`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > Upgrading to systemd 249-1, 249-2, or 249-3 on x86_64 system (MSI Prestige 14 Laptop, 2019 model) breaks keyboard at lowest level:

> Key which normally returns keysym 0x3c now returns 0x2a, so I have 2 keys returning the same keysym. On my French keyboard layout, this leads to 2 keys for "*", no key for "<". As this is at the keysym level, X11, Wayland, and consoles are all affected, with no workaround except reverting to older systemd.

**Steps to reproduce the problem**
 > Test key mapped to keysym 0x3c ("<" on US or FR keyboard on MSI Prestige 14). Returns "*" (FR) or "\" (US) instead.
Reverting to systemd 248 "solves" the issue

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by bluca** [comment]
Guessing from the hardware model, this might be a regression introduced by https://github.com/systemd/systemd/pull/19325 - can you try to revert that change instead of downgrading and confirm that's indeed the case?

/cc @sainAk

**Comment by sainAk** [comment]
@YvanFournier can you send the output of `evtest` for the said key.

I think it's due to
https://github.com/systemd/systemd/blob/a2efdaac077e3aa41720636609be9ff83075bc2e/hwdb.d/60-keyboard.hwdb#L1306
Please remove this line form `/usr/lib/udev/hwdb.d/60-keyboard.hwdb` and run `systemd-hwdb update && udevadm trigger` and see if it fixes the issue.

**Comment by YvanFournier** [comment]
Thanks to all for the quick response.

@sainAk , your suggestion seems to fix the issue. 

Do you also need me to try reverting #19325 (in which case I need to setup the appropriate build), or is the feedback relative to  `/usr/lib/udev/hwdb.d/60-keyboard.hwd` sufficient to confirm the origin of the bug and fix it ?

**Comment by bluca** [comment]
Can you share the output of `evtest` as the first thing? Then we can see if we need to revert, or if it can be fixed

**Comment by sainAk** [comment]
I addded `KEYBOARD_KEY_56=backslash` definition because initially it was returning "<" and ">" on US layout instead of "\" and "|" but it seems to be working fine without the definition.
So I will create a pr to remove it.
Sorry for the trouble, I didn't took other layouts into account.

**Comment by YvanFournier** [comment]
Hello,

Pressing the `<` key (French keyboard) with the commented line in `/usr/lib/udev/hwdb.d/60-keyboard.hwd` (working version), `evtest` returns:
```
Testing ... (interrupt to exit)
Event: time 1626720022.217505, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1c
Event: time 1626720022.217505, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1626720022.217505, -------------- SYN_REPORT ------------
Event: time 1626720030.365236, type 4 (EV_MSC), code 4 (MSC_SCAN), value 56
Event: time 1626720030.365236, type 1 (EV_KEY), code 86 (KEY_102ND), value 1
Event: time 1626720030.365236, -------------- SYN_REPORT ------------
<Event: time 1626720030.431904, type 4 (EV_MSC), code 4 (MSC_SCAN), value 56
Event: time 1626720030.431904, type 1 (EV_KEY), code 86 (KEY_102ND), value 0
Event: time 1626720030.431904, -------------- SYN_REPORT ------------
Event: time 1626720036.664150, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1d
Event: time 1626720036.664150, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1626720036.664150, -------------- SYN_REPORT ------------
Event: time 1626720036.857130, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2e
Event: time 1626720036.857130, type 1 (EV_KEY), code 46 (KEY_C), value 1
Event: time 1626720036.857130, -------------- SYN_REPORT ------------
```

Uncommenting the line (buggy version), I get:
```
Testing ... (interrupt to exit)
Event: time 1626720173.406866, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1c
Event: time 1626720173.406866, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1626720173.406866, -------------- SYN_REPORT ------------
Event: time 1626720174.864513, type 4 (EV_MSC), code 4 (MSC_SCAN), value 56
Event: time 1626720174.864513, type 1 (EV_KEY), code 43 (KEY_BACKSLASH), value 1
Event: time 1626720174.864513, -------------- SYN_REPORT ------------
*Event: time 1626720174.951672, type 4 (EV_MSC), code 4 (MSC_SCAN), value 56
Event: time 1626720174.951672, type 1 (EV_KEY), code 43 (KEY_BACKSLASH), value 0
Event: time 1626720174.951672, -------------- SYN_REPORT ------------
Event: time 1626720180.119301, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1d
Event: time 1626720180.119301, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1626720180.119301, -------------- SYN_REPORT ------------
Event: time 1626720180.207030, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2e
Event: time 1626720180.207030, type 1 (EV_KEY), code 46 (KEY_C), value 1
Event: time 1626720180.207030, -------------- SYN_REPORT ------------
```

Also, when uncommenting line 1306 and running `systemd-hwdb update && udevadm trigger`, I immediately get the wrong (code 43, `KEY_BACKSLASH`) behavior, but when I comment it again, I need to reboot to get the correct (code 86, `KEY_102ND`) behavior.

**Comment by sainAk** [comment]
@YvanFournier you can remove that line.
I've created a PR to fit it, upcoming releases won't have this issue.

**Comment by YvanFournier** [comment]
Ok thanks !
