### ISSUE TITLE
rm_rf failing after ioctl(BTRFS_IOC_SNAP_DESTROY) returns EPERM

### ISSUE THREAD

**Issue by dylanmackenzie** [systemd/systemd#2025]
After an upgrade to fedora 23, systemd-tmpfiles-setup.service started failing with the following messages. I'm using btrfs as the filesystem, but I'm not terribly familiar with its inner workings.

```
Nov 24 16:05:41 neskowin systemd[1]: Starting Create Volatile Files and Directories...
Nov 24 16:05:41 neskowin systemd-tmpfiles[697]: rm_rf(/var/tmp/dnf-mackendy-h3p6rt3r/locks/714adb777d4a13156209c39afdd23433): Operation not permitted
Nov 24 16:05:42 neskowin systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 16:05:42 neskowin systemd[1]: Failed to start Create Volatile Files and Directories.
Nov 24 16:05:42 neskowin systemd[1]: systemd-tmpfiles-setup.service: Unit entered failed state.
Nov 24 16:05:42 neskowin systemd[1]: systemd-tmpfiles-setup.service: Failed with result 'exit-code'.
```

I ran `systemd-tmpfiles --remove dnf.conf` (which replicates the error) in gdb, and the problem appears to occur [here](https://github.com/systemd/systemd/blob/master/src/basic/rm-rf.c#L185). rm_rf attempts to remove the directory as a subvolume (which it is not), and this results in the call to ioctl that fails with EPERM. It looks like systemd expects this call to fail with EINVAL instead when path is not a subvolume, but I'm out of my depth here.

**Comment by poettering** [comment]
Any chance you can run the same command in "strace -s 300 ..." and paste the part around the failing syscalls here?

Not sure why this would ever return EPERM I must say...

**Comment by dylanmackenzie** [comment]
Here's everything pertaining to the locks directory. I should mention that this doesn't affect system integrity at all, it just results in noisy logs.

```
stat("/var/tmp/dnf-mackendy-h3p6rt3r/locks", {st_mode=S_IFDIR|0755, st_size=64, ...}) = 0
openat(AT_FDCWD, "/var/tmp/dnf-mackendy-h3p6rt3r/locks", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_NOFOLLOW|O_NOATIME|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFDIR|0755, st_size=64, ...}) = 0
fcntl(4, F_GETFL)                       = 0x78800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_NOFOLLOW|O_NOATIME)
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents(4, /* 3 entries */, 32768)     = 104
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
open("/var/tmp/dnf-mackendy-h3p6rt3r/locks", O_RDONLY|O_NOCTTY|O_DIRECTORY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFDIR|0755, st_size=64, ...}) = 0
ioctl(4, BTRFS_IOC_SNAP_DESTROY, 0x7ffdc8ecfc60) = -1 EPERM (Operation not permitted)
close(4)                                = 0
```

**Comment by dylanmackenzie** [comment]
Also, I just discovered `systemd-tmpfiles --remove dnf.conf` does succeed when run as root. However the directory in question and all its sub-directories are owned by my user account, and it fails on startup again once I run a dnf command as a normal user. Isn't EACCES returned for permissions problems?

**Comment by poettering** [comment]
On Thu, 26.11.15 11:19, Dylan MacKenzie (notifications@github.com) wrote:

> Also, I just discovered `systemd-tmpfiles --remove dnf.conf` does
> succeed when run as root. However the directory in question and all
> its sub-directories are owned by my user account, and it fails on
> startup again once I run a dnf command as a normal user. Isn't
> EACCES returned for permissions problems?

Hmm, do you have SELinux enabled? Does the problem go away if you
disable it?

**Comment by dylanmackenzie** [comment]
@poettering Yes I am, and booting with selinux=0 does fix the problem, but it comes back after reenabling it and relabeling. Is the problem on dnf's end? `ls -Z` on the locks directory returns

```
unconfined_u:object_r:user_tmp_t:s0 714adb777d4a13156209c39afdd23433
```

**Edit:**
If I just call `setenforce 0` and then try `systemd-tmpfiles --remove dnf.conf`, the command fails with the same error. systemd-tmpfiles-load.service only succeeds if I completely disable selinux.

**Comment by poettering** [comment]
sounds like a problem in the selinux policy. Please file a bug against the selinux policy in fedora. They should allow the BTRFS_IOC_SNAP_DESTROY ioctl to tmpfiles...
