### ISSUE TITLE
 30-systemd-environment-d-generator documentation

### ISSUE THREAD

**Issue by evelynmitchell** [systemd/systemd#20258]
**systemd version the issue has been seen with**
 > …
237
Appears in current code.

**Documentation error**
systemd-environment-d-generator.xml line 22 is:
 <refname>30-systemd-environment-d-generator</refname>
This shows up in man 8 with the 30-prefix, as well as systemd-environment-d-generator
The 30- prefix is meaningless, and so this line should be removed.

**Comment by keszybz** [comment]
The generator *is* installed as 30-systemd-environment-d-generator so the name is appropriate.

**Comment by evelynmitchell** [comment]
> The generator _is_ installed as 30-systemd-environment-d-generator so the name is appropriate.

It is unusual for the generator to be mentioned as a separate man page, which this patch is intended to fix.

See also:
90-systemd.preset
Which is also installed, but does not have a man page, and does have one for systemd.preset

man/systemd.preset.xml
`

--
6 | <refentry id="systemd.preset">
7 |  
8 | <refentryinfo>
9 | <title>systemd.preset</title>
10 | <productname>systemd</productname>
11 | </refentryinfo>
12 |  
13 | <refmeta>
14 | <refentrytitle>systemd.preset</refentrytitle>

`

This change is to bring systemd-environment-d-generator in line with that standard.

Without this fix the generated 30-systemd-environment-d-generator shows up as a man page, when it isn't distinct from systemd-environment-d-generator.

**Comment by keszybz** [comment]
That's a misunderstanding. systemd.preset.xml is for the general concept of systemd presets, similarly to systemd.unit.xml for systemd units, etc. It is not specifically related to 90-systemd.preset. OTOH, this page is for a binary which is installed literally as `30-systemd-environment-d-generator`.
