### ISSUE TITLE
crash in malloc() will cause systemd deadlock

### ISSUE THREAD

**Issue by yummypeng** [systemd/systemd#20266]
**systemd version the issue has been seen with**
 > 219
(It's a very old systemd though I think the problem still exists in upstream)

**Used distribution**
 > centos7.9

**Linux kernel version used** (`uname -a`)

 > `4.19.91 `

**Expected behaviour you didn't see**
 > systemd should not deadlock when crash

**Unexpected behaviour you saw**

We have a production environment where systemd crash on malloc, the backtrace seems like this:
![image](https://user-images.githubusercontent.com/20569488/126445605-3d43ce90-cde2-451a-a5b1-5bd2fc039a93.png)

**Steps to reproduce the problem**
 > occasionally happens

**Additional program output to the terminal or log subsystem illustrating the issue**

The deadlock happens because systemd crash in `malloc()` then in signal handler, it calls `malloc()` (`close_all_fds()`-> `opendir()`-> `__alloc_dir()`) again. `malloc()` is not a signal-safe function, maybe we should re-think the logic here.

**Comment by bluca** [comment]
As far as I can see there are no mallocs in that path when running on a modern kernel (with `close_range()`, since v5.9): https://github.com/systemd/systemd/blob/v249/src/basic/fd-util.c#L230
It's only with the manual fallback that `opendir()` is used - I think that's a fair compromise, I don't think we want to do complicated refactors for a corner case that benefits only legacy systems

**Comment by keszybz** [comment]
No, we will do close_range() without any allocations if there are no gaps. But there usually may be gaps. I think this code is unnecessarily complicated: we could just sort the existing array in place and everybody will be better off. I'll try to prep a patch like this.

**Comment by bluca** [comment]
> No, we will do close_range() without any allocations if there are no gaps. But there usually may be gaps. I think this code is unnecessarily complicated: we could just sort the existing array in place and everybody will be better off. I'll try to prep a patch like this.

In general that can happen, but not in this code path from the signal handler:

https://github.com/systemd/systemd/blob/v249/src/basic/process-util.c#L1045

```
(void) close_all_fds(NULL, 0);
```

That is guaranteed to go through the no-malloc path:

https://github.com/systemd/systemd/blob/v249/src/basic/fd-util.c#L230
