### ISSUE TITLE
systemd-resolved: ability to monitor resolver activity

### ISSUE THREAD

**Issue by yegor-alexeyev** [systemd/systemd#20264]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to monitor systemd-resolved DNS activity(dumping DNS queries and responses, in real time, with some additional info(like whether the repsonse was cached, the query originator etc). Something like logging, but with a strict output format(json, for example).

**Describe the solution you'd like**
Add "monitor" command-line option to the resolvectl utility. So that resolvectl monitor will start dumping current request and responses to the terminal in JSON format. That command-line option cat have additional switches, like resolvectl monitor --dns; that way only DNS requests will be dumped.

**Describe alternatives you've considered**
Alternatively I considered to use the approach with monitoring sdbus, but this resulted in incomplete output(stub resolver and nss_resolve apparently are not using sdbus for interfacing with resolver service).

**The systemd version you checked that didn't have the feature you are asking for**
249

**Comment by yegor-alexeyev** [comment]
@poettering ? Can you tell what do you think about it, please?

**Comment by poettering** [comment]
This was implemented a while back in fffbf1dc996691298fd5e53f15c98e7d7257235a.

Closing.
