### ISSUE TITLE
nss_myhostname: gateway is not a reserved top-level domain

### ISSUE THREAD

**Issue by fweimer** [systemd/systemd#2026]
The full list of reserved top-level domains is available here:
- http://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml

`gateway` is not among them. With the new TLD process, there is a real risk of collision. Please use `gateway.local`, a name you have registered, or reserve the name `gateway` in the IANA database mentioned above. A name such as `_gateway` which accepted by most software, but not a valid DNS domain (which can contain only decimal digits, the letters A-Z, and dots and hyphens “.-”) would be an option as well.

**Comment by poettering** [comment]
Nah, single-label names cannot be confused with top-level domains. That fact is what LLMNR is built on. In resolved we explicitly refuse to resolve single-label names directly via Unicast DNS for this reason.

Hence, we conflict only against LLMNR names there, as well as possibly configured search path logic, but in that case all bets are off anyway...

**Comment by poettering** [comment]
Closing now. Single-label names are special beast due to LLMNR and search domain logic, hence I doubt it's really appropriate to compare them against regular top-level domains.

**Comment by fweimer** [comment]
This issue prevents myhostname from being listed first in `/etc/nsswitch.conf`.  Please fix this.

**Comment by poettering** [comment]
Fixed by 5248e7e1f11aba6859de0b28f0dd3778b22842f2. Closing.
