### ISSUE TITLE
249.1 is missing?

### ISSUE THREAD

**Issue by Neustradamus** [systemd/systemd#20269]
249.1 is missing?

**Comment by mbiebl** [comment]
-> systemd-stable

**Comment by Neustradamus** [comment]
@mbiebl: Here there are tags but not the 249.1:
- https://github.com/systemd/systemd/releases
- https://github.com/systemd/systemd/tags

Other builds are here.

**Comment by mbiebl** [comment]
Right, look at systemd-stable

**Comment by Neustradamus** [comment]
249.2 is missing too.

**Comment by mrc0mmand** [comment]
> 249.2 is missing too.

https://github.com/systemd/systemd-stable/releases
