### ISSUE TITLE
[networkd] Changed Mode= in .netdev ignored on daemon restart

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#20278]
**systemd version the issue has been seen with**
 > 248, 249

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
> `Linux 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux`
> `Linux 5.13.4-arch1-1 #1 SMP PREEMPT Tue, 20 Jul 2021 16:58:51 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Updated configuration, restarted systemd-networkd, expected new configuration to be applied.

**Unexpected behaviour you saw**
 > New configuration was not applied, old configuration was left active.

**Steps to reproduce the problem**
1. Create bonded network interface, e.g. `/etc/systemd/network/example.netdev` containing:
```
[NetDev]
Name=example
Kind=bond

[Bond]
Mode=balance-rr
```
2. Run `systemctl restart systemd-networkd`
3. Run `cat /proc/net/bonding/example`
4. Observe line `Bonding Mode: load balancing (round-robin)` meaning `Mode=balance-rr` has applied
5. Edit the `.netdev` file and change to `Mode=802.3ad`
6. Run `systemctl restart systemd-networkd`
7. Run `cat /proc/net/bonding/example` again
8. Observe the `Bonding Mode` is unchanged, the old `balance-rr` value still applies.
9. Run `ip link del example` to manually remove the bond interface
10. `systemctl restart systemd-networkd`
11. `cat /proc/net/bonding/example`
12. Now the `Bonding Mode` has finally changed to `IEEE 802.3ad` as configured

It seems networkd checks whether the bond interface exists and creates it if not, but if the bond interface does exist, networkd doesn't verify that its configuration matches what's listed in the systemd config files.

**Comment by poettering** [comment]
.netdev devices are operated on if they are missing, otherwise not. 

It's like the second paragraph in the man page:

>        The main Virtual Network Device file must have the extension .netdev; other extensions are ignored. Virtual network devices are created as soon as networkd is started. If a netdev with the specified name already exists,
       networkd will use that as-is rather than create its own. Note that the settings of the pre-existing netdev will not be changed by networkd.

**Comment by Malvineous** [comment]
This seems a bit counterintuitive.  Are there other systemd configuration files that are frequently ignored by design, or is this the only one?

If networkd ignores pre-existing devices, but it created this device originally, shouldn't it then remove it upon exit?  It again seems odd that loading networkd will create a device but thereafter it will completely disown it and ignore it as if it never had anything to do with its creation.

The manpage doesn't seem to explain how to get the .netdev settings reapplied if you want this to happen.  It seems you only have two choices - either reboot the whole machine, or figure out the device-specific non-systemd command to delete the device yourself.  Neither of which seems ideal.

Wouldn't it be helpful to at least have an option like `Apply=always` you could add to the .netdev to tell systemd to always apply its settings, even if the device is pre-existing?
