### ISSUE TITLE
Requires= clarification needed

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#2028]
The man page says

> if one of the other units gets deactivated or its activation fails, this unit will be deactivated.

But that's not what I'm seeing. Instead the dependent unit is _marked_ as failed, but continues to run.

Reproducer:

```
# /home/test/.config/systemd/user/reqa.service
[Service]
Type=oneshot
ExecStart=/bin/echo reqa start
ExecStart=/bin/sleep 10
ExecStart=/bin/false
ExecStart=/bin/echo reqa done
```

```
# /home/test/.config/systemd/user/reqb.service
[Unit]
Requires=reqa.service

[Service]
Type=oneshot
ExecStart=/bin/echo reqb start
ExecStart=/bin/sleep 20
ExecStart=/bin/true
ExecStart=/bin/echo reqb done
```

```
# systemctl --user start reqb
Nov 25 07:59:23 rawhide systemd[2750]: Starting reqb.service...
Nov 25 07:59:23 rawhide systemd[2750]: Starting reqa.service...
Nov 25 07:59:23 rawhide echo[30108]: reqb start
Nov 25 07:59:23 rawhide echo[30109]: reqa start
Nov 25 07:59:33 rawhide systemd[2750]: reqa.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 07:59:33 rawhide systemd[2750]: Failed to start reqa.service.
Nov 25 07:59:33 rawhide systemd[2750]: Dependency failed for reqb.service.
Nov 25 07:59:33 rawhide systemd[2750]: reqb.service: Job reqb.service/start failed with result 'dependency'.
Nov 25 07:59:33 rawhide systemd[2750]: reqa.service: Unit entered failed state.
Nov 25 07:59:33 rawhide systemd[2750]: reqa.service: Failed with result 'exit-code'.
Nov 25 07:59:43 rawhide echo[30128]: reqb done
```

So `reqb` chugs along for another 10 s and then executes another binary after `reqa` is already marked dead.

**Comment by keszybz** [comment]
@poettering This one is for you :)

**Comment by poettering** [comment]
Well, reqb.service is missing the "After=reqa.service" line?

**Comment by keszybz** [comment]
The man page explicitly states that should be deactivated. Maybe it's a documentation issue. I can change the man page myself, but would like a clarification about the desired semantics first.

**Comment by poettering** [comment]
Well, the docs aren't very clear here. And things are a bit special for Type=oneshot services...

Both Requires= and BindsTo= when combined with After= will cause a unit to fail start-up if the dependencies fails first. Also, in both cases, when a shutdown of the dependency is requested the depending unit is also shutdown. However, the difference between the two is for "abnormal" termination of the dependency: when the dependency terminates then the depending unit is only terminated in case of BindsTo=, but not in case of Requires=.

What the man page really should be saying is is that a unit whose Requires= dependency is asked to terminate using systemd's job engine will be shutdown as well.

Does this make sense?

**Comment by bl33pbl0p** [comment]
@keszybz I think this can be closed.

Poettering's explanation is correct. The walk to fail dependencies will happen on everyone RequiredBy= the unit but this can only work if there is a job for it (hence why you must use After= to keep your job waiting until the required job completes).
