### ISSUE TITLE
systemd watchdog will kill process after S1

### ISSUE THREAD

**Issue by caoxia2008cxx** [systemd/systemd#20284]
1.config systemd-logind.service with WatchdogSec=1min
2.echo freeze > /sys/power/state
3.wait 2 min
4.wakeup system,the systemd-logind maybe killed by watchdog

because the CLOCK_MONOTONIC will increase in S1, the watchdog timer will overtime after S1
if systemd-logind scheded before systemd after S1,it will send WATCHDOG=1 to systemd,it will work normal
if systemd scheded before systemd-logind after S1,the watchdog timer will overtime and then kill systemd-logind

so the systemd-logind maybe killed after S1 by watchdog.

**Comment by poettering** [comment]
Well, we assume that clock_monotonic pauses in sleep state. If it doesnt then there's nothing we can do about it, any such sleep will be considered a long hang. I'd consider this a kernel api bug. Clock_monotonic is unlike clock_boottime the clock that pauses during system sleep. And if that rule doesnt apply anymore then a ton of things will break, not just the systemd watchdog logic.

Or to say this differently: which clock do you propose we use instead? We need one that pauses during all system sleep.

Anyway, lets close this, as this appears to be a kerenl api borkage.

**Comment by caoxia2008cxx** [comment]
> Well, we assume that clock_monotonic pauses in sleep state. If it doesnt then there's nothing we can do about it, any such sleep will be considered a long hang. I'd consider this a kernel api bug. Clock_monotonic is unlike clock_boottime the clock that pauses during system sleep. And if that rule doesnt apply anymore then a ton of things will break, not just the systemd watchdog logic.
> 
> Or to say this differently: which clock do you propose we use instead? We need one that pauses during all system sleep.
> 
> Anyway, lets close this, as this appears to be a kerenl api borkage.

can we set watchdog timer timeout in 1/4WatchdogSec,it timeout 4 times then kill the process
