### ISSUE TITLE
kmod-setup.c sould ignore ENOENT rather than ENOSYS when we fail to load a kernel module

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#203]
See #166 for details.

This issue exists merely to make sure we don't forget to fix systemd as soon as kmod has been fixed for this, too:

http://thread.gmane.org/gmane.linux.kernel.modules/1542

And we should bum the kmod dependency version then...

**Comment by lucasdemarchi** [comment]
It's now applied in upstream: https://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/commit/?id=114ec87c85c35a2bd3682f9f891e494127be6fb5

I'm treating this as a bug that should be backported. Are you sure you want to wait for the next release and bump the dependency?

**Comment by dvdhrm** [comment]
I think we should revert the old commit right away. @zonque, any objections?

**Comment by dvdhrm** [comment]
As there haven't been any objections, I now reverted the change without any version bump.
