### ISSUE TITLE
Does Systemd service have limitation w.r.t  IPC on forked process

### ISSUE THREAD

**Issue by stijueaso** [systemd/systemd#20308]
Hi,  
   I have a templated service and socket, for my program.
   thou may not be relevant here , socket is written for inetd (ie FD 0 and 1)
   the service type is put as "simple" in systemd configuration,
   the service spawns many processes in some flows ( fork + execv )  . 
   the spawned process opens , IPC connection ( normal socket to another system ), the process is killed by systemd.
   is this expected? 

   Same issue is not seen for flows where fork+  execv is not  there ( ie execv flows and one where we dont load any process)

**Comment by stijueaso** [comment]
the same behaviour is seen when  
  Type = simple , ecec , oneshot.
  
  For Type=forking , this issue is not seen.

**Comment by stijueaso** [comment]
Strace shows 

ioctl(4, FIONBIO, [0])                  = 0
write(0, "[112] [IpcIO_Recv] (2 4 0x1b335a0 4) [CRYPT]\n", 45) = 45
write(0, "[280] BIO[0x1b32770]:read(4, 5) - socket fd=4\n", 46) = 46
read(4, 0x1b60533, 5)                   = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=1, si_uid=0} ---
+++ killed by SIGTERM +++

**Comment by bluca** [comment]
Is the first process exiting after forking all the children?

**Comment by stijueaso** [comment]
> Is the first process exiting after forking all the children?

no, the process launched from service was still active.
infact it went  was capturing o/p of this process.
where it didnt get any o/p (as it was killed).

**Comment by Werkov** [comment]
I wonder -- does your socket unit specify `Accept=yes`?

**Comment by stijueaso** [comment]
> I wonder -- does your socket unit specify `Accept=yes`?
Yes it has `Accept=yes`

File looks like..
[Unit]
Description=XXXX
PartOf=my.service

[Socket]
ListenStream=<port>
Accept=yes


[Install]
WantedBy=sockets.target

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
