### ISSUE TITLE
[systemd-networkd] stateful DHCPv6 client is broken

### ISSUE THREAD

**Issue by val-kulkov** [systemd/systemd#20306]
**systemd version the issue has been seen with**
 > systemd-networkd-249.2

systemd-networkd-248-5 (the Arch-packaged version) works fine on the same host. The only difference is 'systemd', 'systemd-libs' and 'systemd-sysvcompat'.

**Used distribution**
 > Archlinux x86_64, up-to-date as of 2021-07-26

**Linux kernel version used** (`uname -a`)
 > `Linux bmtp 5.13.5-arch1-1 #1 SMP PREEMPT Sun, 25 Jul 2021 18:02:58 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64 (VM on Proxmox PVE)

**Expected behaviour you didn't see**
 > Network interfaces receive and assign stateful IPv6 addresses from the DHCP server.

**Unexpected behaviour you saw**
 > systemd-networkd solicits a lease from the DHCP server but never acquires the lease, despite the server apparently providing this information to the client (v248.5 works just fine). At the same time, gateway information is read correctly from the router advertisements and the IPv6 routing is configured correctly with the link-local address of the gateway router. A link-local IPv6 address is correctly assigned to the interface. 

With only a link-local IPv6 address configured on the client, the client machine is unreachable over IPv6 and cannot access the Internet over IPv6.

When 'A' flag is set to 'on' in router advertisements, systemd-networkd correctly sets SLAAC addresses on the client. It is only the stateful IPv6 address assignment that is broken in v249.2.

**Steps to reproduce the problem**
 > Configure DHCP server to send **'M' flag but not 'A' flag** in router advertisements. Connect the client machine to the network and observe the behaviour described above.

**Additional program output to the terminal or log subsystem illustrating the issue**

These are the relevant systemd-networkd debug log entries with v249. A SOLICIT request is retransmitted every two minutes or so and this process continues forever with no IPv6 address assignment ever happening.
```
Jul 26 16:57:52 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Sent SOLICIT
Jul 26 16:57:52 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Next retransmission in 1min 56s
Jul 26 16:59:49 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Sent SOLICIT
Jul 26 16:59:49 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Next retransmission in 1min 59s
Jul 26 17:01:49 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Sent SOLICIT
Jul 26 17:01:49 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Next retransmission in 1min 51s
Jul 26 17:03:40 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Sent SOLICIT
Jul 26 17:03:40 bmtp systemd-networkd[248]: ens18: DHCPv6 client: Next retransmission in 1min 58s
```

The DHCP server (dnsmasq 2.85-1) logs show the following every two minutes or so (the real addresses have been partially obfuscated):
```text
Jul 26 17:03:41 dnsmasq-dhcp[4888]: DHCPSOLICIT(eth3) 00:02:00:00:ab:11:ce:3c:b2:91:02:45:a7:e9                           
Jul 26 17:03:41 dnsmasq-dhcp[4888]: DHCPREPLY(eth3) fda3:deaf:deaf:43::20 00:02:00:00:ab:11:ce:3c:b2:91:02:45:a7:e9 bmtp  
Jul 26 17:03:41 dnsmasq-dhcp[4888]: DHCPREPLY(eth3) 2607:deaf:deaf:5943::20 00:02:00:00:ab:11:ce:3c:b2:91:02:45:a7:e9 bmtp
```

With v248.5, the relevant systemd-networkd debug log entries show that a successful acquisition of stateful IPv6 addresses completes almost instantaneously:
```text
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: Sent SOLICIT
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: Next retransmission in 1s
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: NTP information already provided
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: T1 expires in 5h 26min 53s
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: T2 expires in 9h 27min 40s
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: DHCPv6 address 2607:deaf:deaf:5943::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: Configuring address: 2607:deaf:deaf:5943::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: DHCPv6 address fda3:deaf:deaf:43::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: Configuring address: fda3:deaf:deaf:43::20/128 (valid for 12h, preferred for 12h)
```

The full systemd-networkd debug logs for v249.2 and v248.5 are available at https://gist.github.com/val-kulkov/92cbcecb00676f7bd6a0c8e914611dc4

Contents of /etc/systemd/network/20-wired.network:
```text
[Match]
Name = ens18

[Network]
DHCP = yes

[DHCP]
UseDomains = yes
```

**Comment by yuwata** [comment]
Hm, our testsuite does not detect the failure, and I neither reproduce the issue... If possible could you provide more detailed debug logs of dnsmasq?

**Comment by yuwata** [comment]
Also, if possible, please apply the patch in #20379 to show more logs in DHCP6 client.

**Comment by val-kulkov** [comment]
I am working on it and I am sorry for the delay. The issue appears, then disappears, and then appears again. I am trying to identify which component causes this unexpected behaviour. systemd-networkd is not the only suspect, I am also looking at dnsmasq at the OpenWrt router.

**Comment by yuwata** [comment]
From the log @val-kulkov provided (v248.5):
```
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: Sent SOLICIT
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: Next retransmission in 1s
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: NTP information already provided
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: T1 expires in 5h 26min 53s
Jul 26 17:13:30 bmtp systemd-networkd[246]: DHCPv6 CLIENT: T2 expires in 9h 27min 40s
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: DHCPv6 address 2607:deaf:deaf:5943::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: Configuring address: 2607:deaf:deaf:5943::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: DHCPv6 address fda3:deaf:deaf:43::20/128 (valid for 12h, preferred for 12h)
Jul 26 17:13:30 bmtp systemd-networkd[246]: ens18: Configuring address: fda3:deaf:deaf:43::20/128 (valid for 12h, preferred for 12h)
```
Hmm, it is strange that the valid and preferred lifetime of each address is 12h but T1 is ~5h and T2 is ~9h. We calculate T1 and T2 from the valid and preferred lifetime of addresses.

Could you also provide the config file of dnsmasq (at least relevant part of it)?

**Comment by val-kulkov** [comment]
This is the relevant part of the dnsmasq config file (autogenerated by OpenWrt):

```
dhcp-range=set:bmt,192.168.43.100,192.168.43.249,255.255.255.0,12h       
ra-param=eth3,0,7200                                                            
dhcp-range=set:bmt,::1000,::ffff,constructor:eth3,12h             
dhcp-option=bmt,option6:dns-server,[::]                           
dhcp-option=bmt,option:domain-name,biomoltech.kkf                 
dhcp-option=bmt,option:domain-search,biomoltech.kkf               
dhcp-option=bmt,option6:domain-search,biomoltech.kkf              
dhcp-option=bmt,option:ntp-server,192.168.43.1                    
dhcp-option=bmt,option6:sntp-server,[2607:deaf:deaf::5943::1]      
dhcp-option=bmt,option6:ntp-server,[2607:deaf:deaf::5943::1]       
enable-ra                                                                
quiet-ra                                                                 
```

**Comment by yuwata** [comment]
Thanks. One more question. Do you have any DHCP configs in /etc/systemd/networkd.conf or its drop-in?

**Comment by val-kulkov** [comment]
/etc/systemd/networkd.conf has not been modified since its installation. In other words, /etc/systemd/networkd.conf has no configuration settings. The drop-in contains only:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by yuwata** [comment]
Thanks. If possible, please test the current HEAD.

**Comment by val-kulkov** [comment]
The current HEAD, archlinux/svntogit-packages@c11f77d1d5, does not exhibit the problematic behaviour that continues to persist in the stable version.

The debug logs are available at https://gist.github.com/val-kulkov/d846ba7d2259af8a69329d3896f17b58

[systemd-networkd-dhcpv6-249.7-2.log](https://gist.github.com/val-kulkov/d846ba7d2259af8a69329d3896f17b58#file-systemd-networkd-dhcpv6-249-7-2-log) demonstrates systemd-networkd's inability to acquire a DHCPv6 lease. The configuration in  /etc/systemd/network/20-wired.network is the same as in the original post above.

[systemd-networkd-dhcpv6-c11f77d1d5.log](https://gist.github.com/val-kulkov/d846ba7d2259af8a69329d3896f17b58#file-systemd-networkd-dhcpv6-c11f77d1d5-log) demonstrates that a DHCPv6 lease is acquired almost instantaneously.

Should I attempt to apply the patch in #20379 to 249.7 and collect debug logs?

**Comment by yuwata** [comment]
> The current HEAD, [68ee5d7](https://github.com/systemd/systemd/commit/68ee5d774c), does not exhibit the problematic behaviour that continues to persist in v249.

Good news! And thank you for the debugging logs.

**Comment by yuwata** [comment]
Hm, client get `-EEXIST`:
> ens18: DHCPv6 client: Failed to process received reply message, ignoring: File exists

`-EEXIST` related fix after v249 I did is only e693e969614062fea1746399cf5cff4c09526c6a.
Could you try the commit (and possibly other commits required by the commit)?

**Comment by yuwata** [comment]
Ah, the `-EEXIST` is introduced by 353887831b20d0fbd500da9e9f30b048e391305f, which is included in v249 and not in v248.

**Comment by yuwata** [comment]
@val-kulkov Could you test https://github.com/systemd/systemd-stable/pull/150?

**Comment by val-kulkov** [comment]
Hi @yuwata : your patch in systemd/systemd-stable#150 worked like magic. After applying your earlier patch in #20379 and this patch, systemd/systemd-stable#150, I no longer observe the problem. The debug logs are available at https://gist.github.com/val-kulkov/0281e7c825035fde9e43f8c677673b00#file-systemd-networkd-dhcpv6-249-with-stable-p150-log

@yuwata : your response time is nothing I have ever seen before. You are my hero. Thank you.

**Comment by yuwata** [comment]
This is already fixed, and related fix is already backported. Closing.
