### ISSUE TITLE
systemd-escape not unescaping '\x2d' back to '-'

### ISSUE THREAD

**Issue by twojstaryzdomu** [systemd/systemd#20316]
**systemd version the issue has been seen with**
 > systemd 247

**Used distribution**
 > Debian, Red Hat

**Linux kernel version used** (`uname -a`)
 > `Linux host 5.10.17+ #1421 Thu May 27 13:58:02 BST 2021 armv6l GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64, armhf

**Expected behaviour you didn't see**
 > Instances of \x2d being unescaped back to '-'

**Unexpected behaviour you saw**
 > Instances of \x2d kept as x2d.

**Steps to reproduce the problem**
 > 1. Escape out a path with '-'s and record the result.
 > 2. Unescape out the result. Instances of \x2d aren't being unescaped back to '-'. See output below.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
# systemd-escape -p /dev/disk/by-partuuid/738a4d67-01
dev-disk-by\x2dpartuuid-738a4d67\x2d01
# systemd-escape -p -u dev-disk-by\x2dpartuuid-738a4d67\x2d01
/dev/disk/byx2dpartuuid/738a4d67x2d01
# systemd-escape /dev/disk/by-partuuid/738a4d67-01
-dev-disk-by\x2dpartuuid-738a4d67\x2d01
# systemd-escape -u -- -dev-disk-by\x2dpartuuid-738a4d67\x2d0
/dev/disk/byx2dpartuuid/738a4d67x2d0
# systemd-escape -p /dev/disk/by-partuuid/738a4d67-01 | xargs systemd-escape -p -u
/dev/disk/byx2dpartuuid/738a4d67x2d01
# systemd-escape /dev/disk/by-partuuid/738a4d67-01 | xargs systemd-escape -u --
/dev/disk/byx2dpartuuid/738a4d67x2d01
```

**Comment by mrc0mmand** [comment]
I suspect this is caused by `bash` processing the escape sequences first.

```
$ systemd-escape -u -- -dev-disk-by\x2dpartuuid-738a4d67\x2d0
/dev/disk/byx2dpartuuid/738a4d67x2d0

$ systemd-escape -u -- '-dev-disk-by\x2dpartuuid-738a4d67\x2d0'
/dev/disk/by-partuuid/738a4d67-0
```

Similarly with `xargs`:
```
$ systemd-escape -p /dev/disk/by-partuuid/738a4d67-01 | xargs  systemd-escape -u -p -- 
/dev/disk/byx2dpartuuid/738a4d67x2d01

$ systemd-escape -p /dev/disk/by-partuuid/738a4d67-01 | xargs -r0 systemd-escape -u -p -- 
/dev/disk/by-partuuid/738a4d67-01
```

**Comment by Hendrikto** [comment]
> I suspect this is caused by `bash` processing the escape sequences first.

Ideed, this works as expected:

```bash
❯ systemd-escape -pu $(systemd-escape -p '/dev/disk/by-partuuid/738a4d67-01')
/dev/disk/by-partuuid/738a4d67-01
```
