### ISSUE TITLE
[systemd-networkd]: Interface link shows UP even if .network file deleted

### ISSUE THREAD

**Issue by chetuneve** [systemd/systemd#20312]
**systemd version the issue has been seen with**
--> systemd 241 (241)
NetworkManager is disabled. I am using debian 10 (buster)

**Used distribution**
 > Debian 10 (buster)

**Linux kernel version used** (`uname -a`)
> Linux DEB-NUC8i3BE-G6BE01300RG2 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
> Linux RP4-2711-c03112-1xb0e6f3b8 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

**CPU architecture issue was seen on**
 > x86_64 and arm32v7

**Expected behaviour you didn't see**
 > After removing .network file there is still interface (eth0) is in UP state.

**Unexpected behaviour you saw**
 > I Removed .network file from /etc/systemd/network and after restarting systemd-networkd service, interface link (eg. eth0) should be down or should not have an IP address. but I can see that Interface is UP and it has an IP address.

**Steps to reproduce the problem**
 > Configure network interface through .network file as follows,
 ```
[Match]
Name=eth0
[Network]
DHCP=yes
```
and restart systemd-network file. then interface link (eth0) will get an IP address. After getting an IP address, remove .network file from "/etc/systemd/network/"
```
rm eth0.network
```
After removing eth0.network configuration file, restart systemd-networkd service:
```
systemctl restart systemd-networkd
```
Expected result is: There should not be an IP address for eth0 and interface link should be DOWN.

**Additional program output to the terminal or log subsystem illustrating the issue**
Output of "ip a" command:
```
root@RP4-2711-c03112-1xb0e6f3b8:/etc/systemd/network# ip a| grep eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.0.20/24 brd 192.168.0.255 scope global eth0
```
Output of "networkctl" command
```
root@RP4-2711-c03112-1xb0e6f3b8:/etc/systemd/network# networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 eth0             ether              routable    unmanaged 
  3 wlan0            wlan               routable    configured
  4 br-1e86cade5916  bridge             routable    unmanaged 
  5 br-2efd4c30845c  bridge             no-carrier  unmanaged 
  6 br-92b6847f177d  bridge             routable    unmanaged 
  8 docker0          bridge             routable    unmanaged 
 10 veth3420662      ether              degraded    unmanaged 
 12 veth55f7a50      ether              degraded    unmanaged 
 14 vetha597bc1      ether              degraded    unmanaged 
 16 vethdf9acf4      ether              degraded    unmanaged 
 18 veth7b328ba      ether              degraded    unmanaged 
 20 vethf7dd66a      ether              degraded    unmanaged 
 22 veth3acee7a      ether              degraded    unmanaged 
 24 veth5eb2e26      ether              degraded    unmanaged 
 26 vethff622a4      ether              degraded    unmanaged 
 27 vpn_5f2dd        ether              degraded    unmanaged 
 28 vpn_e7726        ether              routable    unmanaged 
 29 vpn_fd0d6        ether              routable    unmanaged 
 31 veth5317219      ether              degraded    unmanaged 
 33 veth2b3133c      ether              degraded    unmanaged 

21 links listed.
````

**Comment by Hendrikto** [comment]
As you can see from the line `2 eth0             ether              routable    unmanaged`, systemd does not manage this interface, so it is probably being brought up by something else.

**Comment by poettering** [comment]
systemd-networkd has no config for that iface anymore so it leaves the interface as it is. You can add a catchall .network file with a later name that pull down all ifaces not matched otherwise, if thats what you want.
