### ISSUE TITLE
Unable to set systemd service with realtime scheduler and priority

### ISSUE THREAD

**Issue by memetb** [systemd/systemd#20320]
> `systemd 247 (247.2-5~bpo10+1)`

**Used distribution**
 > `debian`

**Linux kernel version used** (`uname -a`)

 > `Linux controller 5.4.91-bone-rt-r43 #1buster PREEMPT_RT Sat Jan 30 03:27:21 UTC 2021 armv7l GNU/Linux`

**CPU architecture issue was seen on**
 > `ARMv7 Processor rev 2 (v7l)`
(also able to reproduce on)
 > `Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz`

**Expected behaviour you didn't see**

The description below is a minimal reproduction of a larger problem of being unable to set real-time scheduling on a systemd service file. I unfortunately do not have access to a test environment and therefore found the latest version of systemd I could find (which doesn't quite meet the 2 major revision requirement), but as far as I can tell, no issues matching `CPUSchedulingPolicy` have been filed or fixed since.

**Steps to reproduce the problem**
Please find below the minimal reproducible bug, as well as what I believe is causing the bug.

Running as root:
 > `$ systemd-run --pty --quiet --property=CPUSchedulingPolicy=rr  --property=RestrictRealtime=false --property=LimitRTPRIO=infinity /usr/bin/chrt -p 0`

correctly yields

> pid 27173's current scheduling policy: SCHED_RR
> pid 27173's current scheduling priority: 1

> `$ systemd-run --pty --quiet --property=CPUSchedulingPolicy=rr  --property=RestrictRealtime=false --property=LimitRTPRIO=infinity /usr/bin/chrt --rr 80 /usr/bin/chrt -p 0`

correctly yields

> pid 13806's current scheduling policy: SCHED_RR
> pid 13806's current scheduling priority: 80

However:
> `$ systemd-run --pty --quiet --property=CPUSchedulingPolicy=rr --property=CPUSchedulingPriority=80 --property=RestrictRealtime=false --property=LimitRTPRIO=infinity /usr/bin/chrt -p 0`

incorrectly yeilds:
> `Failed to start transient service unit: Invalid CPU scheduling priority: 80`

I believe I have isolated the bug itself [here](https://github.com/systemd/systemd/blob/80362ec56fc993d1464ae438fcfcb6f763bff1ac/src/core/dbus-execute.c#L2617).

**Additional program output to the terminal or log subsystem illustrating the issue**

Using the following short program
```C++
#include <stdio.h>
#include <sched.h>
int main(int argc, char* argv[])
{
        int scheduler = sched_getscheduler(0);
        printf("%d %d %d\n", scheduler, sched_get_priority_min(scheduler), sched_get_priority_max(scheduler));
}
```

Running as root, interactive user, I get:
> `$ ./a.out`
> `0 0 0`

(which corresponds to the "OTHER" scheduler)

> `systemd-run --pty --quiet --property=CPUSchedulingPolicy=rr --property=RestrictRealtime=false --property=LimitRTPRIO=infinity ./a.out`

correctly yields:
> `2 1 99`

and furthermore `strace`'ing the `systemd` process shows:
> `sched_get_priority_min(SCHED_RR)      = 1`
> `sched_get_priority_max(SCHED_RR)      = 99`

But when `CPUSchedulingPriority` is specified as previously mentioned, systemd fails to launch the process and I can see through `strace` that both [`sched_get_priority_min`](https://github.com/systemd/systemd/blob/80362ec56fc993d1464ae438fcfcb6f763bff1ac/src/core/dbus-execute.c#L2614) and `sched_get_priority_max` are called with `SCHED_OTHER` (0) as inputs and both result in `0` (as per interactive call to ./a.out).

This makes sense given code on line 2616 is `p < min || p > max` is always true if `min == max`.

I believe what's happening is that the SchedulingPriority is being set before the Policy.

----------

Also, for what it's worth, this is related to issue #10290 and the code introduced to fix it: https://github.com/systemd/systemd/pull/10292/commits/2926f407828988e9fbef2b3614f5ba8569f1bbfd

**Comment by poettering** [comment]
Yeah, this is broken. The validation of the range needs to take place after all props are passed.
