### ISSUE TITLE
systemctl set-property user.slice MemoryHigh= permits dangerously low values

### ISSUE THREAD

**Issue by pinkflames** [systemd/systemd#20338]
**Is your feature request related to a problem? Please describe.**
I was playing around with memory limits and on umpteenth iteration I made a typo - instead of 12G I entered 12 (yes, that's whole twelve bytes!) for MemoryHigh value - the system immediately became so slow my first thought was that it had hanged before it dawned on me what I had just done. Switching to tty still worked but only until one successfully authorizes - then user.slice kicks in and again UX becomes so slow it may as well not be running at all. Surely root is exempt from user.slice? Nope. What about rebooting in rescue mode? Since system is not broken dracut proceeds to boot into the real system and... applies the ridiculously low memory limit. I'm sure there's a kernel command line option to make it stay in the initrd but who remembers that without googling. And so we arrive at the usual Linux distro unbricking technique - a live USB, which fixes the issue so easily it feels like it never happened. Except I just spent a lot of time on resolving an issue that really should not have been possible.

**Describe the solution you'd like**
Print a huge warning and request administrator confirmation when doing something obviously dangerous - such as setting MemoryHigh or MemoryMax to unreasonably small values (perhaps less than 400M would be an acceptable threshold?).

**Describe alternatives you've considered**

1. If user interaction is not permitted, then instead of warning it should reject the command and require --force argument to make it go through
2. Put root user in its own slice - this will not save everyone since root accounts are a bit bad/evil and not always available by default but it would have worked for me
3. Have some kind of emergency button (i.e. SysRq) that can remove all limits on every cgroup
4. I did not test this, because I assumed it would be same as local root but having different slices for local and ssh users would have helped me.
5. I realized this only now but it might have been possible to disable all or at least the memory cgroup via the kernel command line.

**The systemd version you checked that didn't have the feature you are asking for**
248.6

**Comment by cdown** [comment]
There are many ways to mess up your system, and there's no way on earth we can protect you from all of them. If you want to experiment with `set-property` and are not certain about the values you're using, use `set-property --runtime` which doesn't persist anything to disk.

I strongly disagree with your assertion that this should not be possible: we don't prevent people from doing wrong things, because that would prevent them from doing smart things, as well. We're not going to turn systemd into a maze of Windows-esque yes/no dialogues.

**Comment by poettering** [comment]
I think the ability to set values this low is truly useful, for testing purposes, as it immediately triggers the memory limits then, and that's a good thing.

As long as this stuff requires privileges I think we are good. We are not in the business to prohibit privileged code all way it can shoot itself in the foot.

I'd really just close this I must say?

**Comment by cdown** [comment]
Yeah, and we actually use it as such. For example, I used very low memory.high values when implementing allocator throttling last year.

**Comment by pinkflames** [comment]
Alright, I'll try to remember to use --runtime whenever I suspect I might be doing something where a typo or another mistake could lead to a bad time.
