### ISSUE TITLE
cryptenroll: support automatic falling back from ECC to RSA keys if TPM2 chip doesn't support ECC

### ISSUE THREAD

**Issue by reynoldsbd** [systemd/systemd#20361]
I'm having some trouble enrolling my PC's TPM2 device into a LUKS2 slot. See below for error output.

There is [an error report for Clevis](https://github.com/latchset/clevis/issues/165) with an identical error message. I believe this is very similar to the issue I'm seeing with systemd:

* Like the person who reported the Clevis error, my TPM device also does not appear to support ECC.
* Like Clevis, systemd [appears to be using ECC as its default encryption algorithm](https://github.com/systemd/systemd/blob/main/src/shared/tpm2-util.c#L266).
  * Unlike Clevis, cryptenroll does not appear to support specifying any other encryption algorithms.

**systemd version the issue has been seen with**

> 249

**Used distribution**

> Arch Linux

**Linux kernel version used** (`uname -a`)

> `Linux hoth 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**

> x86_64

**Unexpected behaviour you saw**

> TPM2 enrollment fails with the following output:
>
> ```
> # systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0,7 /dev/nvme0n1p3
> 🔐 Please enter current passphrase for disk /dev/nvme0n1p3: ***
> WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000002ca) 
> Failed to generate primary key in TPM: tpm:parameter(2):the type of the value is not appropriate for the use
> ```

**Comment by poettering** [comment]
Ah, that's sad. RSA keys are sooo much slower than ECC keys for this though. But supporting them as fallback should be pretty easy.

**Comment by poettering** [comment]
(just to make this clear I am against letting the user pick the algorithm tough, this should not require user intervention, we should just try ECC and if that is not available fall back to RSA, so that things just work for everyone the best possible way.)

**Comment by poettering** [comment]
I prepped a patch for this in #20716. Would be great if you could give this a whirl. 

(Should suffice building the git tree, then invoking systemd-cryptenroll/systemd-cryptsetup from the build tree, for testing. No need to install)
