### ISSUE TITLE
networkd 249 fails to configure network interfaces with VLAN filtering

### ISSUE THREAD

**Issue by mxre** [systemd/systemd#20373]
**systemd version the issue has been seen with**
 > 249 (works with the previous version 248)

**Used distribution**
 > ArchLinux ARM

**Linux kernel version used** (`uname -a`)
 > `Linux alarm 5.11.4-1-ARCH #1 SMP Sun Mar 7 23:46:10 UTC 2021 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 >  AArch64

**Expected behaviour you didn't see**
 > networkd does not bring up the the bridged hardware interfaces

**Unexpected behaviour you saw**
 > Interface stays down

**Steps to reproduce the problem**
 >

**Additional program output to the terminal or log subsystem illustrating the issue**
```
Jul 31 04:50:00 alarm systemd-networkd[599]: lan0: Failed to set bridge configurations: Operation not supported
Jul 31 04:50:00 alarm systemd-networkd[599]: lan0: Failed
Jul 31 04:50:00 alarm systemd-networkd[599]: lan1: Failed to set bridge configurations: Operation not supported
Jul 31 04:50:00 alarm systemd-networkd[599]: lan1: Failed
```
where as on systemd-248
```
Aug 03 14:54:34 alarm systemd-networkd[599]: lan0: Could not set bridge interface: Operation not supported
Aug 03 14:54:34 alarm systemd-networkd[599]: lan1: Could not set bridge interface: Operation not supported
```
(all other log entries from networkd stayed the same)

I think networkd fails to configure VLAN hardware offload. In the past this error was simply ignored. Now networkd fails and does not bring up the interfaces (lan0 and lan1). Manually bringing them up (with `ip link set dev lan{0,1} up`) still works.

**Additional Configurations**
br0.network
```
[Match]
Name=br0

[Network]
VLAN=br0.100
VLAN=br0.600
IPForward=yes
ConfigureWithoutCarrier=yes
LLDP=yes

[Bridge]
Learning=yes
MulticastRouter=no
UseBPDU=yes

[BridgeVLAN]
VLAN=100

[BridgeVLAN]
VLAN=600
```

br0.netdev
```
[NetDev]
Name=br0
Kind=bridge

[Bridge]
MulticastQuerier=yes
MulticastSnooping=yes
Priority=10
STP=yes
ForwardDelaySec=5
MulticastIGMPVersion=2
VLANFiltering=yes
```

lan.network (for lan0 and lan1)
```
[Match]
Name=lan*

[Network]
IPForward=yes
Bridge=br0
BindCarrier=eth0
LinkLocalAddressing=no
EmitLLDP=nearest-bridge
LLDP=yes

[Link]
RequiredForOnline=no

[Bridge]
Learning=yes
MulticastRouter=query
UseBPDU=yes

[BridgeVLAN]
VLAN=100
EgressUntagged=100
PVID=100

[BridgeVLAN]
VLAN=560

[BridgeVLAN]
VLAN=600
```
(I omit the other configfiles I do not think that they are involved, as all the virtual interfaces to nspawn containers work)

**Comment by yuwata** [comment]
Could you also show config files for br0.100 and br0.600?

**Comment by yuwata** [comment]
I guess #20375 fixes your issue, but I cannot reproduce the issue, and I do not understand why kernel refuses to set bridge VLAN configs...

**Comment by mxre** [comment]
I originially left br0.100 and br0.600 out because there is not really anything special about them,...

br0.100.netdev
```
[NetDev]
Description=Management LAN
Name=br0.100
Kind=vlan

[VLAN]
Id=100
```

br0.100.network
```
[Match]
Name=br0.100

[Network]
Address=172.16.16.1/20
Address=fd6c:f52f:67bb:1::1/64
IPv6PrefixDelegation=static

[IPv6Prefix]
Prefix=fd6c:f52f:67bb:1::/64
```

br0.600.netdev
```
[NetDev]
Description=Internal LAN
Name=br0.600
Kind=vlan

[VLAN]
Id=600
```

br0.600.network
```
[Match]
Name=br0.600

[Network]
Address=172.16.0.1/20
Address=fd6c:f52f:67bb:0::1/64
IPForward=yes
ConfigureWithoutCarrier=yes
IPv6SendRA=yes
DHCPv6PrefixDelegation=yes

[IPv6SendRA]
Managed=yes
OtherInformation=yes
RouterLifetimeSec=86400
DNSLifetimeSec=86400
DNS=fd6c:f52f:67bb:0::7
Domains=lan

[IPv6Prefix]
Prefix=fd6c:f52f:67bb:0::/64

[DHCPv6PrefixDelegation]
SubnetId=auto
Announce=yes
Assign=yes
Token=::1
```

I'll look into testing #20375 it is entirely possible that this a latent bug in hardware or network driver

**Comment by mxre** [comment]
I compiled systemd-networkd from #20375 (by cloning github/yuwata:network-bridge-vlan-issue-20373); but to no avail. The problem remained.
I figured since the error message was "bridge configurations" and not "bridge VLAN configurations" which according to the string table in networkd-setlink.c meant `SET_LINK_BRIDGE` and not `SET_LINK_BRIDGE_VLAN`.
Based on the patch I tried out changing the ignore flag in `link_set_bridge_handler()` and I successfully avoided the error (or at least ignored it and thus successfully brought up the interface.)

**Comment by yuwata** [comment]
> I figured since the error message was "bridge configurations" and not "bridge VLAN configurations" which according to the string table in networkd-setlink.c meant `SET_LINK_BRIDGE` and not `SET_LINK_BRIDGE_VLAN`.

Ouch! The PR is now updated. Thank you!
