### ISSUE TITLE
shutdown does not use DefaultTimeoutStopSec value, always waits 90 seconds

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20388]
**systemd version the issue has been seen with**
 > 245.4

**Used distribution**
 > Ubuntu 20.04

**Linux kernel version used** (`uname -a`)

 > `Linux xxxxxx 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:33:50 UTC 2021 s390x s390x s390x GNU/Linux`

**CPU architecture issue was seen on**
 > s390x

**Expected behaviour you didn't see**
 > systemd-shutdown completes in DefaultTimeoutStopSec seconds

**Unexpected behaviour you saw**
 > systemd-shutdown completes in 90 seconds

**Steps to reproduce the problem**
My Linux-based appliance has a extra process that gets started before systemd is started as PID(1). This extra process handles console traffic for my appliance. This extra process also ignores SIGTERM signals, and can only be terminated by SIGKILL signal.

During shutdown, systemd sends SIGTERM, (ignored), then sends SIGKILL. Given that systemd will never be able to SIGTERM this process, I override DefaultTimeoutStopSec to shorten the shutdown time from the default of 90sec to 30sec. I use a conf file in /etc/systemd/system.conf.d to accomplish this override.

- When using Ubuntu 18.04 (systemd 237), shutdown processing would use DefaultTimeoutStopSec and only wait 30secs before sending SIGKILL.
- When using Ubuntu 20.04 (systemd 245.4), shutdown processing appears to ignore DefaultTimeoutStopSec and waits 90secs before sending SIGKILL.

It seems that somewhere between 237 and 245.4, systemd-shutdown was refactored and no longer honors DefaultTimeoutStopSec value. This presents a usability issue for my appliance (long shutdown times).
I would like for shutdown processing to use DefaultTimeoutStopSec to control the timeout as it was in 237.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
[  OK  ] Finished Reboot.
[  OK  ] Reached target Reboot.
[ 1249.550417] Terminated
[ 1249.550499] Ignoring signal     = issued by StealConsole =
[ 1259.542951] systemd-shutdown[1]: Waiting for process: StealConsole
[ 1339.687961] systemd-shutdown[1]: Could not detach DM /dev/dm-0: Device or resource busy
[ 1339.690185] systemd-shutdown[1]: Failed to finalize  DM devices, ignoring
```

**Comment by poettering** [comment]
DefaultTimeoutStopSec= only has an effect on "regular" service termination. But the timeout you see is for the second phase of shutdown, i.e. where regular service termination already has finished, and we just clean-up processes that were left-over. (i.e. the "killing spree")

It appears you actually want to  make use of this to exclude your code from this secnd phase of shutdown. See https://systemd.io/ROOT_STORAGE_DAEMONS for details.

Closing, since this seems like the much more correct approach to your problem.
