### ISSUE TITLE
resolved caching too aggressively

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#2038]
I think resolved is caching negatives a bit too aggressively and doesn't flush its cache when the network config changes.

I'm using NetworkManager with dnsmasq as its DNS driver (so `resolv.conf` ever only contains `nameserver 127.0.0.1` and various `search` domains), because this allows me to connect to an intranet using OpenVPN and have the intranet's domain names resolved using the intranet's DNS server, while leaving the default route untunneled. `resolv.conf` alone does not support setting DNS servers for specific domains.

When NM estabilishes the VPN connection (and the tun device appears), resolved does not flush its caches, so previously negative responses about the intranet's domains remain. After restarting resolved the lookups succeed.

**Comment by poettering** [comment]
So resolved maintains per-interfaces caches, which are created individually for each interface+protocol combination and removed too when the interface goes away. This doesn't apply to you though, as you don't maintain per-interface DNS config, but redirect everything globally to 127.0.0.1...

We also flush caches when the DNS server we use changes, but it never does for you, as it stays stable at 127.0.0.1...

I'd claim that dnsmasq should really return very low TTLs when serving stuff on 127.0.0.1. resolved just follows what dnsmasq suggests when caching, via the reported TTLs. However, in such a setup the double caching is pointless anyway, hence dnsmasq should return a really low TTL anyway.

I am not sure this is really something to fix in resolved...

**Comment by poettering** [comment]
Hmm, so thinking about this I think I'll make two changes:
1. When a DNS server on 127.0.0.0/8 or ::1 is configured, we will completely disable any kind of caching, under the assumption that that's done by the DNS forwarder running locally.
2. When /etc/resolv.conf is touched we'll flush all cases, even if the contents stays identical.

The first fix should make things work for you.
