### ISSUE TITLE
RFE ethtool equivalents for configuring offload parameters and coalescing

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#20392]
**Is your feature request related to a problem? Please describe.**
I'm working on porting some of our network-scripts to systemd-networkd and there were a few things that I couldn't find an equivalent for in systemd-networkd:

- [x] ~~way to change offload parameters and other features of the network device. i.e. like `ethtool -K eth0 rx-gro-hw off`. Ideally  applied before rx/tx ring parameters.~~ More features specifically rx-gro-hw
- [x] way to change coalescing settings of a network device. i.e. like `ethtool -C eth0 rx-usecs 100`
- [x] would also be nice to have a special string like "max" for all of the Rx/TxBufferSize= properties to mean "set this to the hardware supported maximum"

**Describe the solution you'd like**
~~For network features it would be pretty verbose to give every feature its own property with boolean value. Maybe one property named `Features=` where by default everything is off and if the feature is supplied (e.g. `Features=rx-gro-hw`, specified multiple times or in a space-separated list). Though one property per feature is also fine.~~ I checked again and there are features, one per feature. So I guess we just need to add more of them.

For coalesce, a `Coalesce=` property that would look something like `Coalesce=rx-usecs:100` specified multiple times  or in a space-separated list. Or I guess following the networkd trend, every setting would get its own property.

**Describe alternatives you've considered**
I can continue to make `ethtool` calls before putting down the link configurations for ring buffer parameters and applying them.

**The systemd version you checked that didn't have the feature you are asking for**
249

**Comment by yuwata** [comment]
It seems all requested features are implemented. @anitazha and @DaanDeMeyer Is it OK to close this?

**Comment by anitazha** [comment]
Yup all good here. Thanks
