### ISSUE TITLE
Unbounded number of (archived) log files generated in /var if /run is full.

### ISSUE THREAD

**Issue by iitalics** [systemd/systemd#20390]
**systemd version the issue has been seen with**
 > 248

**Used distribution**
 > `fc34`

**Linux kernel version used** (`uname -a`)
 > `Linux fedora 5.13.6-200.fc34.x86_64 #1 SMP Wed Jul 28 15:31:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**

When `Storage=volatile` is set, journald should not create any persistent logs. If for any reason persistent logs are generated, they should be subject to storage limits as if journald was not operating in volatile mode.

**Unexpected behaviour you saw**

If the `/run` directory becomes full, journald will begin generating user logs in `/var/log/journal/<machine-id>/`. When these user logs become archived, they are never cleaned up. This generates an unbounded number of log files unless they are explicitly vacuumed (e.g. `journalctl --vacuum-files 1`).

**Steps to reproduce the problem**
1. Fill `/run` directory until there is no more space left: `sudo dd if=/dev/zero of=/run/junk.bin bs=1M count=1000`
2. Ensure appropriate /var directory exists: `mkdir -p /var/log/journal/$(</etc/machine-id)`
3. Send a large number of logs to the journal as a non-root user: `su iitalics -c 'echo spam | systemd-cat'` (repeatedly)
4. Observe there are now lots of files of the form `/var/log/journal/*/user-*@*-*-*.journal`. The number of these files can exceed both `SystemMaxFiles` and `RuntimeMaxFiles` limits in journal.conf.

**Comment by poettering** [comment]
Hmm wa? when we are in volatile mode we should not log to /var, ever, regardless of what's with /run.

It's a bug if we end up writing to /var, we never should

**Comment by iitalics** [comment]
It looks like there's a couple lines (e.g. in `find_journal`) that equate `runtime_journal == NULL` with "we're not in volatile mode." But if re-opening the runtime journal fails during rotation then it will set the runtime journal to NULL, so we end up writing to /var
