### ISSUE TITLE
Missing hwdb entry for Thinkpad P14s/T14 Gen 2 touchpad

### ISSUE THREAD

**Issue by svonohr** [systemd/systemd#20394]
**systemd version the issue has been seen with**
 > 249

**Used distribution**
 > Arch Linux

The hwdb currently lists these settings for recent Thinkpad T-Models:
https://github.com/systemd/systemd/blob/e908236e054bd246f0bc764a0b1412da8172d741/hwdb.d/60-evdev.hwdb#L570-L576

I have the recent P14s Gen 2 Model which should be identical to the T14 Gen 2. It still seems to use the same touchpad as previous models. Without a hwdb entry the touchpad sensitivity is very low. I ran `touchpad-edge-detector` and got the same resolution as for the T490/T14 Gen 1. With my model added to the hwdb the touchpad works as expected with reasonable sensitivity. The P14s Gen 2 is identified by the following filter:

`evdev:name:SynPS/2 Synaptics TouchPad:dmi:*:svnLENOVO:*pvrThinkPadP14sGen2a:*`

Probably the P14s Gen 1 and T14 Gen 2 should also be added, but I cannot verify how these system identify.

**Comment by poettering** [comment]
Please submit the additional line as PR, so that it is automatically tested by CI and we can properly attribute it to you.
