### ISSUE TITLE
systemd-cryptsetup: Cannot use pkcs11-uri other than "auto"

### ISSUE THREAD

**Issue by etam** [systemd/systemd#20400]
**systemd version the issue has been seen with**
> 248

**Used distribution**
> openSUSE Tumbleweed (snapshot 20210730)

**Linux kernel version used** (`uname -a`)
 > `Linux etam-librem.lan 5.13.4-1-default #1 SMP Thu Jul 22 15:55:06 UTC 2021 (91a0cca) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Running `/usr/lib/systemd/systemd-cryptsetup attach mytest /dev/sdc1 - pkcs11-uri=${URI}`, where URI is taken from `systemd-cryptenroll --pkcs11-token-uri=list`, should use the selected device.

**Unexpected behaviour you saw**
 > The command failed with message "PKCS#11 mode selected but no key file specified, refusing."
 > See https://github.com/systemd/systemd/blob/v248/src/cryptsetup/cryptsetup.c#L881

**Steps to reproduce the problem**
 > Follow the "Example 3. Yubikey-based PKCS#11 Volume Unlocking Example" from `man crypttab`, but instead of using `pkcs11-uri=auto` use an actual URI.

**Why?**
> I don't want to use uri=auto, because I have 2 yubikeys and want to have explicitly only one of them associated with partition.

**Comment by poettering** [comment]
There are two ways to do PKCS#11 stuff with systemd-cryptsetup:

1. Automatic mode: in this mode all the metadata needed, including the encrypted key that the PKCS#11 token decrypts, is embedded in the JSON LUKS2 metadata. You pick this via pkcs11-uri=auto. 
2. Manual mode: in this mode all the metadata are specified manually, via the crypttab options string and via the keyfile column in crypttab. You pick this mode via pkcs11-uri= with any other string than "auto".

I am not sure I fully grok your problem? Your examples suddenly mention TPM2? is that a typo?

Why would you specify the pkcs11 uri in crypttab at all? it should be sufficient to specify it when enrolling?

**Comment by etam** [comment]
Sorry, I went toot fast, not reading the man pages accurately which caused me to misunderstand how "auto" works. I didn't get that, when using "auto", the uri gets stored in luks header.

And yes, the TPM2 was a typo.
