### ISSUE TITLE
support cron commands

### ISSUE THREAD

**Issue by xenoterracide** [systemd/systemd#20404]
It would be cool if there was an implementation of `crontab -l` and `crontab -e` that generated the simple timer and service files. It might allow people to give some very generic instructions that worked whether a cron was the default, or cronie.

I have 2 use cases:
1. a cli shell framework wants to do auto updates but complains that Systemd isn't cross-platform, OSX still supports cron as of 2020 according to google. Windows will always be weird. So being able to provide consistent instructions would be good
1. Timeshift only supports cron, meaning "cronie" or something also has to be installed, it's annoying, for now it's on the list of reasons I'm using snapper, but, that's not *user-friendly. Fortunately I've been doing Linux since '03, and have been and admin, and used gentoo for years, so user-friendly isn't my issue. I'm not certain if this requires additional API.

**Comment by poettering** [comment]
The semantics are sufficiently different that such a translation layer would be too skewed to make sense.

If you want cron semantics and interfaces I'd recommend just running cron on top of systemd, there's nothing wrong about that.

There are a multitude of cron implementations in the wild. I seriously doubt that cron is such useful as a "standard" as you think it is. At least cronie, dcron, vixie cron are popular, and have different feature sets. 

I know that Debian provided some package that could translate cron definitions into systemd timers via generators. I'd suggest looking into that, if you want to bridge the gap.

But other than that, I am not convinced we need to provide more glue there, definitely not now anymore, given we managed to live without for so long, and this hasn't come up that often.

Sorry if that's disappointing.
