### ISSUE TITLE
Running applications that need b-dus as a systemd service

### ISSUE THREAD

**Issue by nexcode** [systemd/systemd#20424]
The reason for creating this issue:
https://github.com/flatpak/flatpak/issues/4345#issuecomment-883522502

I need to run the application as a service, but this application needs a d-bus to work.

If I start the service as **systemctl --user** option, then everything works, but in order to manage this, I have to log in for a specific user, but this user was created only so that the application works on his behalf, and not for a login.

And to restart **--user** service, I need to use loginctl **disable-linger** and **enable-linger**.
It is very uncomfortable...

**Comment by mbiebl** [comment]
This doesn't appear to be a valid bug report bug a user support question.
Please use any of the existing channels for that.
