### ISSUE TITLE
systemd-networkd: `erspan0: Received newlink with wrong KIND erspan, expected gre`

### ISSUE THREAD

**Issue by ZeclintrYzath** [systemd/systemd#20426]
I want to use traffic mirroring from tap0 to the network card, to break up the converted
traffic issued from the server vpn.
Do you know which version of the system i should use for this?
Or are there other workarounds to support `ёrspan`?
If someone else has encountered such a problem, please leave it here
your reviews.

**Comment by yuwata** [comment]
Here is not a support forum, but the upstream bug tracker.
Please fill the template, at least, please give us the version of systemd you are using.
Also, please provide the debugging logs of networkd, and relevant .netdev, .network and .link files.
Without them, we have almost nothing to do.

Closing. If you would like, please request to reopen after the above information is provided.

**Comment by ZeclintrYzath** [comment]
I found out the version of sistemd:
`systemctl --version`
`systemd 237`
I know systemd-networkd does not support `erspan` mode right now, but:

What software could i install to make up for this deficiency, enable mirroring? 
Are there such programs? 
Or should i install systemd-networkd an older version with `erspan` support?
