### ISSUE TITLE
[networkd] Support for complete set of CAN interface options

### ISSUE THREAD

**Issue by splatch** [systemd/systemd#20435]
**Is your feature request related to a problem? Please describe.**
The SocketCAN brings multiple options which might be set. Most of drivers support only subset of them, yet option list is a bit longer than currently supported by networkd.
The `>` markers indicate options which are supported by networkd while `-` indicate an missing option or options:

```
Usage: ip link set DEVICE type can
>	[ bitrate BITRATE [ sample-point SAMPLE-POINT] ] |
-	[ tq TQ prop-seg PROP_SEG phase-seg1 PHASE-SEG1
- 	  phase-seg2 PHASE-SEG2 [ sjw SJW ] ]

>	[ dbitrate BITRATE [ dsample-point SAMPLE-POINT] ] |
-	[ dtq TQ dprop-seg PROP_SEG dphase-seg1 PHASE-SEG1
- 	  dphase-seg2 PHASE-SEG2 [ dsjw SJW ] ]

-	[ loopback { on | off } ]
>	[ listen-only { on | off } ]
>	[ triple-sampling { on | off } ]
-	[ one-shot { on | off } ]
>	[ berr-reporting { on | off } ]
>	[ fd { on | off } ]
>	[ fd-non-iso { on | off } ]
-	[ presume-ack { on | off } ]
-	[ cc-len8-dlc { on | off } ]

>	[ restart-ms TIME-MS ]
	[ restart ]

?	[ termination { 0..65535 } ]

	Where: BITRATE	:= { 1..1000000 }
		  SAMPLE-POINT	:= { 0.000..0.999 }
		  TQ		:= { NUMBER }
		  PROP-SEG	:= { 1..8 }
		  PHASE-SEG1	:= { 1..8 }
		  PHASE-SEG2	:= { 1..8 }
		  SJW		:= { 1..4 }
		  RESTART-MS	:= { 0 | NUMBER }
```

There is a `Termination` option available in networkd CAN settings which is still not documented within kernel docs. This option is however a number and not switch, please see https://github.com/torvalds/linux/commit/12a6075cabc0d9ffbc0366b44daa22f278606312. From commit you can see that termination option allows to pick a resistor of certain kind. Obviously, for most of the cases it will be 120. Since `networkd` does not know actual device (end user shall do) staying with a boolean switch will make it impossible to use termination option.
The low level options may be considered rather optional, yet loopback is something quite useful for testing usecases.

**Describe the solution you'd like**
Consistent support for socketcan interface options.

**Describe alternatives you've considered**
The alternative is to fallback to unit files and scripts which do the same. Yet then whole point of use of managed network configuration is gone.

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 248`

**Comment by yuwata** [comment]
Waiting in #20442. If possible, please test the PR.

**Comment by splatch** [comment]
@yuwata Thank you very much for prompt handling of issue. I'll have a round of testing only next week. I'll report progress then!
