### ISSUE TITLE
Add per-network-device IP forwarding option to [Network] directives

### ISSUE THREAD

**Issue by TheWug** [systemd/systemd#20441]
**Is your feature request related to a problem? Please describe.**
Currently, [Network] includes [IPForward](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPForward=) which controls the system-wide settings for net.ipv4.ip_forward and net.ipv6.conf.all.forwarding. Numerous caveats exist with this approach, including that forwarding will be enabled for all interfaces and will remain enabled even after an interface with this option is downed. Additionally, the IPMasquerade option will silently enable IPforward. My understanding is that enabling IP forwarding at the whole system level is a default-insecure pattern and should probably be removed for that reason, or at the very minimum, specified in a different manner than in any individual interface's network directives.

**Describe the solution you'd like**
The following sysctl options also impact this behavior, and they do so on a more granular level:
net.ipv4.conf.all.forwarding
net.ipv4.conf.default.forwarding
net.ipv4.conf.[iface-name].forwarding
net.ipv6.conf.default.forwarding
net.ipv6.conf.[iface-name].forwarding
It may be appropriate to control, or at least maintain awareness of, the values of these settings as they could potentially interfere with those intended by interface configuration. (e.g, consider a situation where net.ipv4.conf.default.forwarding is set, but an interface is created which does not expect to have forwarding enabled. In this situation it will inherit explicitly-enabled forwarding anyway. I don't think this is suitable default behavior, although a yes/no/kernel set of options would allow it to work this way for those who explicitly desire external configuration, while other situations can be subject to the more suitable default of 'no').

**Describe alternatives you've considered**
The only real alternative is to comb through afterwards and change the values of non-compliant sysctl options for all network interfaces. This is a tedious task, especially for environments with multiple network namespaces, for which all namespaces must be enumerated (since the sysctl settings for an interface in namespace B are masked to sysctl invocations in namespace A)

**The systemd version you checked that didn't have the feature you are asking for**
There is no per-interface setting available [in the online documentation](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPForward=) at the time of posting, and the current version of systemd is 249. Additionally, no setting appears in the manual for version 248.

**Comment by yuwata** [comment]
The kernel doc says,
```
.. note::

           It is recommended to have the same setting on all
           interfaces; mixed router/host scenarios are rather uncommon.
```
What's your usecase?

**Comment by eshattow** [comment]
Additionally from the manual page _systemd.network(5)_
> Note, unlike IPv4Forwarding=, enabling per-interface IPv6Forwarding= on two or more interfaces DOES NOT make IPv6 packets forwarded within the interfaces.
> This setting just controls the per-interface sysctl value, and the sysctl value is not directly correlated to whether packets are forwarded. To ensure IPv6
> packets forwarded, the global setting in networkd.conf(5) needs to be enabled.

What is the use of this at all if it does not do anything? Should this always be global, or tri-state?

IPv6Forwarding=yes
IPv6Forwarding=no
IPv6Forwarding=all

**Comment by yuwata** [comment]
@eshattow Global setting is in networkd.conf. Also, follow-up change is waiting in #34014.

Anyway, #31423 is merged. So the original request is addressed. Closing.
