### ISSUE TITLE
Unable to set RunTimeMaxSec for transient units started via systemd-run

### ISSUE THREAD

**Issue by ondrejv2** [systemd/systemd#20464]
**Is your feature request related to a problem? Please describe.**
I need to specify maximum runtime for a service started via systemd-run

**Describe the solution you'd like**
Implement a parameter to systemd-run which will be interpreted as RunTimeMaxSec

**Describe alternatives you've considered**
For services created via systemd-run there does not seem to be any alternative

**The systemd version you checked that didn't have the feature you are asking for**
I checked the freedesktop docs and man systemd-run on F34 and did not find a way to accomplish this

**Comment by yuwata** [comment]
Please use `-p` option:
```
systemd-run -p 'RuntimeMaxSec=1sec' sleep 5
```
Then you can find something like the following:
```
Aug 18 16:28:57 systemd[1]: Started /usr/bin/sleep 5.
Aug 18 16:28:58 systemd[1]: run-u386.service: Service reached runtime time limit. Stopping.
Aug 18 16:28:58 systemd[1]: run-u386.service: Failed with result 'timeout'.
```

**Comment by ondrejv2** [comment]
Wow, got it. I thought I can't use -p as 'RuntimeMaxSec' does not really looks like Property, but more like an option.
Thanks.
