### ISSUE TITLE
It will prompt "Failed to unmount /oldroot" when shutdown or reboot after installing finalrd

### ISSUE THREAD

**Issue by binli** [systemd/systemd#20516]
**systemd version the issue has been seen with**
 > 245.4-4ubuntu3.11

**Used distribution**
 > Ubuntu OS 20.04.2

**Linux kernel version used** (`uname -a`)

 > `5.11.0-25-generic`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > No error show up

**Unexpected behaviour you saw**
 >  sd-umoun[2406]: Failed to unmount /oldroot: Device or resource busy

**Steps to reproduce the problem**
 > Install the finalrd package and reboot, then you could find these errors on shutdown or reboot.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
 sd-umoun[2406]: Failed to unmount /oldroot: Device or resource busy
 sd-umoun[2407]: Failed to unmount /oldroot/dev/pts: Device or resource busy
 sd-umoun[2408]: Failed to unmount /oldroot/dev: Device or resource busy
 shutdown[1]: Failed to finalize  file systems, ignoring
```

**Comment by poettering** [comment]
What is "finalrd"? And if that's causing the issue, why are you not filing an issue against that?

Also, the submission form makes very clear this should only be used for issues with the two most recent systemd versions, which are 248/249 right now 245 is waaay older than that. For older stuff please contact your distro

**Comment by binli** [comment]
Thanks for your feedback.
