### ISSUE TITLE
systemd-analyze security for single undeployed unit files

### ISSUE THREAD

**Issue by mqus** [systemd/systemd#20511]
**Is your feature request related to a problem? Please describe.**
I sometimes write new unit files (mostly services) and deploy them to a different machine. I'm very happy that `systemd-analyze security` exists and would like to use it much more often but it seems like the command only works on units already installed on the system. But I would much rather avoid the additional install&remove loop to audit my unit files, especially on initial writes.

Currently, if want to run it on a local file the following happens:
```bash
$ systemd-analyze security myservice.service 
Unit myservice.service not found, cannot analyze.
```
or 
```bash
$ systemd-analyze security ./myservice.service 
Unit .-myservice.service not found, cannot analyze.
```

**Describe the solution you'd like**
Either it just works (maybe fallback on local search)
```bash
$ systemd-analyze security myservice.service 
[...the paged analysis, just like usual]
```
Or, if the above has too many issues (security, compatibility, etc):
```bash
$ systemd-analyze security --file myservice.service 
[...the paged analysis, just like usual]
```
(of course, `--file` can be anything else or even a new subcommand)

This solution could then also be used to run the command in CI pipelines or similar to check for regressions.

**Describe alternatives you've considered**
I don't know how the command works internally. Afaict this is a very static analysis that does not need much from the target system. 

But I could be very wrong. In that case I would like to know more and it would also help if there was just a subset of rules which work statically and can be tested before deploying. Even that would save much time.

**The systemd version you checked that didn't have the feature you are asking for**
```
$ systemd-analyze --version
systemd 249 (249.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

```
(Distro: archlinux)

**Comment by bluca** [comment]
It's your lucky day: https://github.com/systemd/systemd/pull/20421 was just merged which adds an --offline switch, that can be used exactly for that purpose. Will be part of v250.
