### ISSUE TITLE
systemd-journal-upload user is potentially missing systemd-journal group

### ISSUE THREAD

**Issue by DSpeichert** [systemd/systemd#2051]
systemd-journal-upload cannot upload anything unless it's given access to system journals.
Intuitively, one would expect it has access to system journals. However, this service runs as a system user of the same name and according to documentation [1]: "Unless limited by one of the options specified below, all journal entries accessible to the user the program is running as will be uploaded, and then the program will wait and send new entries as they become available."
The user systemd-journal-upload does not have access to any logs by default, even though it is automatically created.

Re-reporting upstream from https://bugs.archlinux.org/task/47161

**Comment by poettering** [comment]
Appears as if we indeed should make the systemd-journal-upload user a member of "systemd-journal" by default. Specifically, we should add a line for that to the sysuser.d/systemd-journal.conf file, and document this in README. 

@keszybz this sounds simple enough to do. Opinions?

**Comment by poettering** [comment]
Hmm, so, the "systemd-journal-upload.service" file contains `SupplementaryGroups=systemd-journal` already, which means the "systemd-journal-upload" user does not have to be member of "systemd-journal" in /etc/group. It's fully sufficient if we pass group membership to the upload service only.

Hence I see nothing to fix here, closing hence. Or did I misunderstand this issue @DSpeichert? If so, please comment + reopen.

**Comment by DSpeichert** [comment]
@poettering You are right. This SupplementaryGroups setting was already added on January 15th (3 months after I opened this issue) by @yuwata in https://github.com/systemd/systemd/commit/d70698b7e612bad2a45ad5facf9882326ab0f690, which should fix this issue. I will comment again in the unlikely case it's not fixed.
