### ISSUE TITLE
nethunter chroot; dpkg error with systemd

### ISSUE THREAD

**Issue by ind3p3nd3nt** [systemd/systemd#20539]
Preparing to unpack .../systemd_247.9-1_amd64.deb ...
mv: cannot move '/etc/pam.d/systemd-user' to '/etc/pam.d/systemd-user.dpkg-remove': No such file or directory
dpkg: error processing archive /var/cache/apt/archives/systemd_247.9-1_amd64.deb (--unpack):
 new systemd package pre-installation script subprocess returned error exit status 1
Preparing to unpack .../libsystemd0_247.9-1_amd64.deb ...
Unpacking libsystemd0:amd64 (247.9-1) over (240-6) ...
Errors were encountered while processing:
 /var/cache/apt/archives/systemd_247.9-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Used distribution**
 > https://build.nethunter.com/kalifs/kalifs-latest/

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
amd64
 > …

**Expected behaviour you didn't see**
apt would finish correctly
 > …

**Unexpected behaviour you saw**
dpkg error while doing an apt install xfce4
 > …

**Steps to reproduce the problem**
in a root I did this:
wget -O install_kali https://is.gd/kaliuniverse
chmod +x install_kali
./install_kali

then I typed in the root
remote install
(which does: nh -r apt update && nh -r apt install tightvncserver kali-defaults-desktop  kali-menu net-tools xterm lxterminal  -y;)

 > …

seems like systemd is broken in the chroot

**Comment by yuwata** [comment]
That should be a packaging issue. Please contact to your distribution. Closing.
