### ISSUE TITLE
implement some way for unprivileged users to access HID devices with sandboxed applications

### ISSUE THREAD

**Issue by Be-ing** [systemd/systemd#20533]
**Is your feature request related to a problem? Please describe.**
By default, udev prohibits unprivileged users from directly accessing HID devices, both through hidraw and directly accessing USB devices. Applications that require access to HID devices can work around this by shipping a udev rule file adding the `uaccess` tag to devices they are designed to work with. This works fine for traditional distribution packages, but there is no way for a sandboxed application to install a udev rule file to the system.

**Describe the solution you'd like**
Implement some means for applications to request access to specific HID devices without needing to install a udev rule file.

**Describe alternatives you've considered**
Tell users to manually install a udev rule file if they use a Flatpak. This is unappealing because it would lead to lots of support requests. Before Mixxx shipped a [udev rule file](https://github.com/mixxxdj/mixxx/blob/main/res/linux/mixxx-usb-uaccess.rules), we got many of these requests.

**The systemd version you checked that didn't have the feature you are asking for**
248

https://github.com/flatpak/flatpak/issues/3291
https://github.com/flatpak/xdg-desktop-portal/issues/989

**Comment by Be-ing** [comment]
> Unfortunately this is not a practical solution. This would require vendor cooperation or a source of funding to purchase every possible device anyone might want to use with Mixxx to find the PIDs, neither of which Mixxx has.

Actually, we do have the product ID of every HID device Mixxx supports recorded although Mixxx doesn't actually use that information for anything. We have the vendor and product IDs of those few old devices that Mixxx uses USB Bulk endpoints via libusb as well. So adding a list of all these devices to hwdb could work for allowing sandboxed applications to access devices Mixxx already supports. But we'd still need broad rules matching only on vendor IDs so people could add support for new devices easily.

**Comment by poettering** [comment]
> That would be nice, but that doesn't seem like a solution that would generalize well. Mixxx is not the only application affected by this, for example [Steam](https://github.com/flathub/com.valvesoftware.SteamLink#known-issues) and [web browsers accessing FIDO tokens](https://github.com/flatpak/flatpak/issues/2764) are also affected.

We cover FIDO2 natively already, they are opened up via uaccess already as mentioned. 

> Unfortunately this is not a practical solution. This would require vendor cooperation or a source of funding to purchase every possible device anyone might want to use with Mixxx to find the PIDs, neither of which Mixxx has.

Well, as with any driver support (and hwdb is pretty much that: driver support) somebody has to have a look at the respective hw before opening it up via uaccess. Blanket allowlisting whole companies is something we cannot do. Sorry. So yeah, if you want this opened up via uaccess out of the box, then that's great and we support you with that, but this must be a living hwdb then: i.e. someone needs to send as a patch adding new entries as new hw becomes available or people statr toying around with them. That's how we do it with all kinds of other hw, and is how we should do it here too. DJ/audio production hw is not that special in that regard.

**Comment by hadess** [comment]
There's a fair number of different cases to consider, and a blanket "USB devices need to be accessible by users" isn't going to be a narrow enough definition of it.

There are 2 cases that systemd could have an impact on:
- devices that only export a `hidraw` interface, and not any input devices, or anything else: the `hidraw` node should be added the `uaccess` tag (https://github.com/systemd/systemd/pull/20561 needs to show that the input layer isn't good enough to access those devices' features)
- devices without a class driver, that means no hidraw, no input device, no sound device, no video device, no network device, etc. If those are safe to be used by end-users, then you can tag them with `uaccess` (eg. https://github.com/systemd/systemd/pull/20527). If they aren't safe to be used by end-users, then we currently don't have a good solution for getting access to those.

I've commented on the PR associated with this change. Blanket opening up access to hidraw isn't feasible, as for some devices that'll be the way to access firmware updates, or other non-end-user-y activities.

**Comment by Be-ing** [comment]
> someone needs to send as a patch adding new entries as new hw becomes available or people statr toying around with them

I will document this in Mixxx's contribution guidelines for adding support for new hardware and will block merging into Mixxx until there is a pull request to add the device to hwdb in systemd.

**Comment by Be-ing** [comment]
> devices that only export a hidraw interface, and not any input devices, or anything else: the hidraw node should be added the uaccess tag

This seems like a better solution than individually listing every single device.

**Comment by Be-ing** [comment]
>  devices that only export a hidraw interface, and not any input devices, or anything else: the hidraw node should be added the uaccess tag


@poettering what do you think of this idea instead of individually listing every device?
