### ISSUE TITLE
[Feature request] Please add snapper snaphot support to systemd-boot

### ISSUE THREAD

**Issue by ShalokShalom** [systemd/systemd#2055]
I guess everybody here know snapper and the rollback feature of btrfs.

Please add the option to boot from such a snapshot, directly by systemd-boot.

There is a similar module available for GRUB2: https://hackweek.suse.com/projects/71

http://snapper.io/

**Comment by poettering** [comment]
systemd-boot has no concept of btrfs file systems, and cannot access them (it only has access to FAT file systems after all). And I am not convinced this has any place there. Sorry.

**Comment by ShalokShalom** [comment]
ok, thanks a lot. Whats the correct way for me now, in order to make it possible, please?
