### ISSUE TITLE
Problem with hwdb accel matrix for One-netbook OneMix 2s

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20550]
**Original pull request**
https://github.com/systemd/systemd/pull/20068#issue-680355660

**systemd version the issue has been seen with**
249.3-1

**Used distribution**
Arch

**Linux kernel version used** (`uname -a`)
`Linux antin-umpc 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86

**Expected behaviour you didn't see**
Rotating screen normally

**Unexpected behaviour you saw**
Screen is rotated 90 degree clockwise

**Steps to reproduce the problem**
Example rebooting machine.

**Additional program output to the terminal or log subsystem illustrating the issue**
```● iio-sensor-proxy.service - IIO Sensor Proxy service
     Loaded: loaded (/usr/lib/systemd/system/iio-sensor-proxy.service; static)
     Active: active (running) since Thu 2021-08-26 17:30:05 EEST; 1min 2s ago
   Main PID: 316 (iio-sensor-prox)
      Tasks: 3 (limit: 9414)
     Memory: 1.2M
        CPU: 89ms
     CGroup: /system.slice/iio-sensor-proxy.service
             └─316 /usr/lib/iio-sensor-proxy

elo 26 17:30:05 antin-umpc systemd[1]: Starting IIO Sensor Proxy service...
elo 26 17:30:05 antin-umpc systemd[1]: Started IIO Sensor Proxy service.
elo 26 17:30:05 antin-umpc iio-sensor-prox[316]: Could not find trigger name associated with /sys/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-BOSC0200:00/iio:device0
```

**Bad "Fix" to /usr/lib/udev/hwdb.d/60-sensor.hwdb**
```
sensor:modalias:acpi:BOSC0200*:dmi:*:svnDefaultstring:pnDefaultstring:*
 ACCEL_MOUNT_MATRIX=0, -1 0; 1, 0, 0; 0, 0, 1
```
Source: https://orumin.blogspot.com/2018/12/one-netbook-one-mix-2s.html

**Error message when using that Bad "Fix"**
```
● iio-sensor-proxy.service - IIO Sensor Proxy service
     Loaded: loaded (/usr/lib/systemd/system/iio-sensor-proxy.service; static)
     Active: active (running) since Thu 2021-08-26 17:05:38 EEST; 20min ago
   Main PID: 1959 (iio-sensor-prox)
      Tasks: 3 (limit: 9414)
     Memory: 1.3M
        CPU: 33ms
     CGroup: /system.slice/iio-sensor-proxy.service
             └─1959 /usr/lib/iio-sensor-proxy

elo 26 17:05:38 antin-umpc systemd[1]: Starting IIO Sensor Proxy service...
elo 26 17:05:38 antin-umpc systemd[1]: Started IIO Sensor Proxy service.
elo 26 17:05:38 antin-umpc iio-sensor-prox[1959]: Could not find trigger name associated with /sys/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-BOSC0200:00/iio:device0
elo 26 17:05:38 antin-umpc iio-sensor-prox[1959]: Failed to parse '0, -1 0; 1, 0, 0; 0, 0, 1' as a mount matrix
elo 26 17:05:38 antin-umpc iio-sensor-prox[1959]: Failed to parse ACCEL_MOUNT_MATRIX ('0, -1 0; 1, 0, 0; 0, 0, 1') from udev
```

I want and try to be helpful even when I don't fully understand this. Maybe some BIOS version number changed or somebody added some new accel matrix what is now in conflict or something? Maybe I did something wrong when I created accel matrix in the first place. Ask and I can post logs and other things what you need.

**Comment by jwrdegoede** [comment]
> > ```
> > sensor:modalias:acpi:BOSC0200*:dmi:*:svnDefaultstring:pnDefaultstring:*
> >  ACCEL_MOUNT_MATRIX=0, -1 0; 1, 0, 0; 0, 0, 1
> > ```
> 
> This line lacks a comma between -1 and 0.
> 
> The match is a bit too wide though. If there are laptops with mostly uninitialized strings then particular care needs to be taken to still match as much as virtually possible, to make clashes with other systems unlikely.
> 
> /cc @jwrdegoede (who likes devices like that? ;-))

Yes I just love devices with broken DMI strings.

So the right thing to do here is to use the entire `/sys/class/dmi/id/modalias` string as match, that tends to be reasonable unique even for devices with broken DMI strings.

I'll comment on #20562 about this.

**Comment by jwrdegoede** [comment]
As discussed in #20562 a kernel patch for moving the sku field to the end has been posted upstream:
https://lore.kernel.org/lkml/20210831130508.14511-1-hdegoede@redhat.com/

**Comment by jwrdegoede** [comment]
And a new systemd pull-req updating all affected dmi modalias matches in hwdb so that they work with all kernel versions is here: https://github.com/systemd/systemd/pull/20599
