### ISSUE TITLE
option _netdev not working if mount point created by mount command

### ISSUE THREAD

**Issue by zp841126** [systemd/systemd#20566]
Submission type
[ x ] Request for enhancement (RFE)
systemd version the issue has been seen with
systemd 248

Used distribution
Centos 7.6.8

In case of bug report: Expected behaviour you didn't see
We should create dependencies between mount point and network.target even if it created first time by mount command

In case of bug report: Unexpected behaviour you saw
The dependencies not created between mount point and network.target, so caused reboot hang

In case of bug report: Steps to reproduce the problem
1. Create 100 rbds quickly
2. Create filesystem on rbd
3. Mount filesystem with option "_netdev"(mount -o _netdev /dev/rbdX /mnt/rbdX)
4. Reboot

**Comment by zp841126** [comment]
I checked latest systemd code,  as my understanding, option "_netdev" not working if mount point created by call mount command.

code path: mount_setup_unit -> mount_setup_new_unit

In this code path, it not call function mount_add_default_dependencies, it means we will not create dependencies between mount and network target.

Could you confirm is it by design?

**Comment by yuwata** [comment]
Could you test #20568?

**Comment by zp841126** [comment]
Porting fix to v219, it fixed reboot hang issue. thanks  yuwata for quickly fix.
