### ISSUE TITLE
systemctl doesn´t restart but tries to stop process on its crashing

### ISSUE THREAD

**Issue by Simonesien** [systemd/systemd#20560]
**systemd version the issue has been seen with**
 > 241

**Used distribution**

 > Raspbian OS on Raspberry Pi 400

**Linux kernel version used**

 > `Linux 5.10.52-v7l+ #1441 SMP armv7l GNU/Linux`

**Expected behaviour I didn't see**
 > The Process doesn´t restart as it was killed but the restart=on-failure value was set.

**Unexpected behaviour I saw**
 > systemctl logs "Stopps" what only comes when `/home/pi/script stop` is executed. 

**The /etc/systemd/system/test.service file**
```
[Unit]
Description=Test
Wants=network.target
After=network.target

[Service]
Type=forking
User=pi
Group=pi
KillMode=none

PrivateDevices=no
NoNewPrivileges=yes
ExecStart=/home/pi/script start
ExecStop=/home/pi/script stop
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
```
**The /home/pi/script file**
```
#!/bin/bash

case "$1" in
	start)
		echo "Starts"
		tmux -L test new-session -s session -d /home/pi/script process # Starts /home/pi/script process in a own terminal (like screen)
		exit $?
		;;
	stop)
		echo "Stopps"
		touch /home/pi/tmp # Touchs /home/pi/tmp so that the process stops. 
		exit $?
		;;
	process)
		while true; do
			[ -f /home/pi/tmp ] && rm /home/pi/tmp && exit 0 # Waits for /home/pi/tmp to exist, then exits. 
		done
		;;
esac
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```
pi@minepi:~ $ pgrep tmux
pi@minepi:~ $ sudo systemctl start test.service 
pi@minepi:~ $ pgrep tmux
1238
pi@minepi:~ $ kill 1238
pi@minepi:~ $ pgrep tmux
pi@minepi:~ $ sudo systemctl status test.service 
● test.service - Test
   Loaded: loaded (/etc/systemd/system/test.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Aug 27 19:58:32 minepi systemd[1]: Starting Test...
Aug 27 19:58:32 minepi script[1235]: Starts
Aug 27 19:58:32 minepi systemd[1]: Started Test.
Aug 27 19:58:43 minepi script[1243]: Stopps
Aug 27 19:58:43 minepi systemd[1]: test.service: Succeeded.
pi@minepi:~ $ pgrep tmux
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
