### ISSUE TITLE
Third-party service files' symlinks removed with 'systemctl disable'

### ISSUE THREAD

**Issue by drws** [systemd/systemd#20569]
**systemd version the issue has been seen with**
Latest release (249.3).

**Steps to reproduce the problem**
1. Add a symlink to a service file located elsewhere into `/etc/systemd/system/`.
2. Reload deamon (service files) and enable the service.
3. Disable the service.

**Unexpected behaviour you saw**
`systemctl disable` removes **both** the target symlink (expectedly) as well as unexpectedly the service file symlink in `/etc/systemd/system/`!

**Additional program output to the terminal or log subsystem illustrating the issue**
Consider the following case in which a system service file is located somewhere in the filesystem while being symlinked into `/etc/systemd/system/`:

```
user@box:~ ln -s /usr/include/example.service /etc/systemd/system/
user@box:~ systemctl daemon-reload
user@box:~ systemctl enable example.service
Created symlink /etc/systemd/system/multi-user.target.wants/example.service -> /usr/include/example.service.
```
When such a service is enabled, the service symlink is resolved and target symlink points to the original service file location. This is arguably expected, but truly unexpected part comes upon disabling such service. `systemctl disable` removes not only target symlink(s), but the `/etc/systemd/system/example.service` symlink as well!

```
user@box:~ systemctl disable example.service
Removed /etc/systemd/system/example.service.
Removed /etc/systemd/system/multi-user.target.wants/example.service.
```

Is this an expected and documented behaviour? I don't think `systemctl` should manage willfully-configured (third-party) files, not even symlinks, without opting-in.

**Comment by mrc0mmand** [comment]
Related discussion: https://github.com/systemd/systemd/issues/3660#issuecomment-442792258

According to the `systemctl(1)` man page, this is indeed an expected behavior:

>disable UNIT…
>    Disables one or more units. This **removes all symlinks** to the unit files backing the specified units from the unit configuration directory, and hence undoes any changes made by enable or link. **Note that this removes all symlinks to matching unit files, including manually created symlinks, and not just those actually created by enable or link.** Note that while disable undoes the effect of enable, the two commands are otherwise not symmetric, as disable may remove more symlinks than a prior enable invocation of the same unit created.

Taken from: https://www.freedesktop.org/software/systemd/man/systemctl.html

**Comment by drws** [comment]
@mrc0mmand Thank you for info. Do you know any reason for such behaviour?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Thank you for info. Do you know any reason for such behaviour?

I'd say this stems from the fact that `disable` is an inverse operation to `link` as well as to `enable`:

[systemctl(1)](https://www.freedesktop.org/software/systemd/man/systemctl.html)
> link PATH…
>    Link a unit file that is not in the unit file search paths into the unit file search path. This command expects an absolute path to a unit file. **The effect of this may be undone with disable.** The effect of this command is that a unit file is made available for commands such as start, even though it is not installed directly in the unit search path. The file system where the linked unit files are located must be accessible when systemd is started (e.g. anything underneath /home/ or /var/ is not allowed, unless those directories are located on the root file system).

**Comment by drws** [comment]
Thank you for the explanation, I (obviously) still haven't managed to properly go through the documentation. I am planning to do that when the development settles down a bit more.
