### ISSUE TITLE
udevadm test-builtin net_setup_link -- Could not apply link configuration, ignoring: No such file or directory

### ISSUE THREAD

**Issue by daviessm** [systemd/systemd#20570]
**systemd version the issue has been seen with**
 > 248.6

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)
 > `5.13.13-gentoo #3 SMP Sun Aug 29 13:38:21 BST 2021 x86_64 Intel(R) Celeron(R) J4105 CPU @ 1.50GHz GenuineIntel GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Test of netdev .link file in output 

**Unexpected behaviour you saw**
 > Error message `enp3s0: Failed to get ACTION= property: No such file or directory`

**Steps to reproduce the problem**
 > `#SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/enp3s0`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          248
file size:         9135404 bytes
header size             80 bytes
strings            2305564 bytes
nodes              6829760 bytes
Load module index
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Loaded timestamp for '/etc/systemd/network'.
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /etc/systemd/network/00-enp3s0.link
Created link configuration context.
ID_NET_DRIVER=r8169
enp3s0: Device has name_assign_type=4
enp3s0: Config file /etc/systemd/network/00-enp3s0.link is applied
enp3s0: Failed to get ACTION= property: No such file or directory #<-- [1]
enp3s0: Could not apply link configuration, ignoring: No such file or directory
ID_NET_LINK_FILE=/etc/systemd/network/00-enp3s0.link
Unload module index
Unloaded link configuration context.
```

[1] This looks like it might be related to https://github.com/systemd/systemd/commit/e0e789c1e97e2cdf1cafe0c6b7d7e43fa054f151

**Comment by yuwata** [comment]
This is already fixed by #20460.
