### ISSUE TITLE
systemd-run always warns `Failed to open /dev/tty: No such device or address`

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#20576]
**systemd version the issue has been seen with**

```
$ systemctl --version
systemd 249 (249.r241.gc7cfde640d-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

ArchLinux

**Linux kernel version used** (`uname -a`)

Linux 5.13.12-arch1-1 GNU/Linux

**CPU architecture issue was seen on**

amd64

**Steps to reproduce the problem**

I've set up my compositor to run the my terminal when pressing <kbd>Super</kbd>+<kbd>Return</kbd>:

    systemd-run --user alacritty

**Expected behaviour you didn't see**

Terminal should run with no warnings.

**Unexpected behaviour you saw**

`systemd-run` prints the following warning, no matter what program I run:

    Failed to open /dev/tty: No such device or address

Nothing seems to fail though, but this quickly piles up lots of useless log entries.

**Additional program output to the terminal or log subsystem illustrating the issue**

This can be quickly reproduce by running `sway`(hint: this compositor can be nested inside another Wayland sessions), and then running:

    swaymsg exec -- systemd-run --user true

**Comment by poettering** [comment]
Smells like something wrong with your WM: it passes stdout/stderr on a tty, but not a controlling tty. This usually means the program is a bit confused about ttys (i.e. thinks its a background shell job or so)

That said, even though your tty setup looks broken we should probably handle this better and detect this case.

You can work around this by using `--no-ask-password`

**Comment by WhyNotHugo** [comment]
> Smells like something wrong with your WM: it passes stdout/stderr on a tty, but not a controlling tty. This usually means the program is a bit confused about ttys (i.e. thinks its a background shell job or so)

I'm not sure I 100% understand this. It gets passed stdout/stderr. However, it _is_ run as a background shell / job.

What I'm doing is running mapping a global keybinding to `swaymsg exec -- systemd-run --user true`. So I think it makes sense that there's not `tty` for it.

`--no-ask-password` does suppress the error message.

**Comment by poettering** [comment]
The problem is not that there was no tty for it. There *is* a TTY for it. However it's not the controlling TTY.

**Comment by WhyNotHugo** [comment]
Nice, thanks for the fix and the explanations!
