### ISSUE TITLE
nss-systemd: torsocks causes Assertion 'fclose_nointr(f) != -EBADF' failed at src/basic/fd-util.c:125, function safe_fclose()

### ISSUE THREAD

**Issue by zsugabubus** [systemd/systemd#20586]
**systemd version the issue has been seen with**
 > 249.2

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux 5.13.6-arch1-1 #1 SMP PREEMPT Thu, 29 Jul 2021 00:21:06 +0000 x86_64 GNU/Linux`

**Expected behaviour you didn't see**
 > No crash.

**Unexpected behaviour you saw**
 > Crash.

**Steps to reproduce the problem**
1. `torsocks id foo`

```
WARNING torsocks[748814]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
Assertion 'fclose_nointr(f) != -EBADF' failed at src/basic/fd-util.c:125, function safe_fclose(). Aborting.
```

```
$ torsocks -h
torsocks 2.3.0
```

**Comment by yuwata** [comment]
Please provide coredump or strace.

**Comment by zsugabubus** [comment]
<details><summary>torsocks strace -f id foo</summary>
<pre>
execve("/usr/bin/id", ["id", "foo"], 0x7fffffffc3b0 /* 51 vars */) = 0
brk(NULL)                               = 0x555555560000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fffffffc230) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, "/usr/lib/torsocks/libtorsocks.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=83832, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ffff7fc5000
mmap(NULL, 87904, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7faf000
mmap(0x7ffff7fb2000, 40960, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7ffff7fb2000
mmap(0x7ffff7fbc000, 28672, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xd000) = 0x7ffff7fbc000
mmap(0x7ffff7fc3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7ffff7fc3000
close(3)                                = 0
access("/etc/ld.so.preload", R_OK)      = 0
openat(AT_FDCWD, "/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=84448, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 84448, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ffff7f9a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`|\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 848) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0K@g7\5w\10\300\344\306B4Zp<G"..., 68, 928) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2150424, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1880536, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7dce000
mmap(0x7ffff7df4000, 1355776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7ffff7df4000
mmap(0x7ffff7f3f000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x171000) = 0x7ffff7f3f000
mmap(0x7ffff7f8b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bc000) = 0x7ffff7f8b000
mmap(0x7ffff7f91000, 33240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffff7f91000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\"\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=22704, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 24720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7dc7000
mmap(0x7ffff7dc9000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ffff7dc9000
mmap(0x7ffff7dcb000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7ffff7dcb000
mmap(0x7ffff7dcc000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7ffff7dcc000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ffff7dc4000
arch_prctl(ARCH_SET_FS, 0x7ffff7dc4740) = 0
mprotect(0x7ffff7f8b000, 12288, PROT_READ) = 0
mprotect(0x7ffff7dcc000, 4096, PROT_READ) = 0
mprotect(0x7ffff7fc3000, 4096, PROT_READ) = 0
mprotect(0x55555555e000, 4096, PROT_READ) = 0
mprotect(0x7ffff7ffb000, 8192, PROT_READ) = 0
munmap(0x7ffff7f9a000, 84448)           = 0
getuid()                                = 1000
geteuid()                               = 1000
brk(NULL)                               = 0x555555560000
brk(0x555555581000)                     = 0x555555581000
openat(AT_FDCWD, "/etc/tor/torsocks.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2087, ...}, AT_EMPTY_PATH) = 0
read(3, "# This is the configuration for "..., 4096) = 2087
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=3041456, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 3041456, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ffff7add000
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=328, ...}, 0) = 0
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=328, ...}, AT_EMPTY_PATH) = 0
read(3, "# Name Service Switch configurat"..., 4096) = 328
read(3, "", 4096)                       = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=328, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=84448, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 84448, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ffff7f9a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P5\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=51376, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 79320, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7ac9000
mmap(0x7ffff7acc000, 28672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7ffff7acc000
mmap(0x7ffff7ad3000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7ffff7ad3000
mmap(0x7ffff7ad5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb000) = 0x7ffff7ad5000
mmap(0x7ffff7ad7000, 21976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffff7ad7000
close(3)                                = 0
mprotect(0x7ffff7ad5000, 4096, PROT_READ) = 0
munmap(0x7ffff7f9a000, 84448)           = 0
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1607, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, ""..., 4096) = 1607
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=84448, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 84448, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ffff7f9a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@p\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=321712, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 326200, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7a79000
mmap(0x7ffff7a80000, 208896, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7ffff7a80000
mmap(0x7ffff7ab3000, 69632, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3a000) = 0x7ffff7ab3000
mmap(0x7ffff7ac4000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4a000) = 0x7ffff7ac4000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2207\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=39408, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 43520, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7a6e000
mmap(0x7ffff7a71000, 16384, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7ffff7a71000
mmap(0x7ffff7a75000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7ffff7a75000
mmap(0x7ffff7a77000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7ffff7a77000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libcrypt.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0  \0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=186200, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 221736, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7a37000
mmap(0x7ffff7a39000, 73728, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ffff7a39000
mmap(0x7ffff7a4b000, 102400, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7ffff7a4b000
mmap(0x7ffff7a64000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2c000) = 0x7ffff7a64000
mmap(0x7ffff7a66000, 29224, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffff7a66000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0p\7\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2986824, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 3006384, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7759000
mmap(0x7ffff77cf000, 1724416, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x76000) = 0x7ffff77cf000
mmap(0x7ffff7974000, 593920, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x21b000) = 0x7ffff7974000
mmap(0x7ffff7a05000, 188416, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2ab000) = 0x7ffff7a05000
mmap(0x7ffff7a33000, 16304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffff7a33000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libp11-kit.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\220\2\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1261136, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 1264616, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7624000
mmap(0x7ffff764d000, 647168, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7ffff764d000
mmap(0x7ffff76eb000, 368640, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc7000) = 0x7ffff76eb000
mmap(0x7ffff7745000, 81920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x120000) = 0x7ffff7745000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\200\0\0\0\0\0\0"..., 832) = 832
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 792) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\7\310\371[O2Q\320\205P!z\330\241\363\20"..., 68, 872) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=154040, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 131472, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff7603000
mprotect(0x7ffff760a000, 81920, PROT_NONE) = 0
mmap(0x7ffff760a000, 61440, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7ffff760a000
mmap(0x7ffff7619000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7ffff7619000
mmap(0x7ffff761e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7ffff761e000
mmap(0x7ffff7620000, 12688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffff7620000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libffi.so.7", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@ \0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=42960, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 46376, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ffff75f7000
mmap(0x7ffff75f9000, 24576, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ffff75f9000
mmap(0x7ffff75ff000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7ffff75ff000
mmap(0x7ffff7601000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7ffff7601000
close(3)                                = 0
mprotect(0x7ffff7601000, 4096, PROT_READ) = 0
mprotect(0x7ffff761e000, 4096, PROT_READ) = 0
mprotect(0x7ffff7745000, 40960, PROT_READ) = 0
mprotect(0x7ffff7a05000, 180224, PROT_READ) = 0
mprotect(0x7ffff7a64000, 4096, PROT_READ) = 0
mprotect(0x7ffff7a77000, 4096, PROT_READ) = 0
mprotect(0x7ffff7ac4000, 16384, PROT_READ) = 0
set_tid_address(0x7ffff7dc4a10)         = 777807
set_robust_list(0x7ffff7dc4a20, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7ffff760ab70, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7ffff7616870}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7ffff760ac10, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7ffff7616870}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7ffff7f9a000, 84448)           = 0
rt_sigprocmask(SIG_BLOCK, [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], [], 8) = 0
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
futex(0x7ffff7ac8a08, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/run/systemd/userdb/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=60, ...}, AT_EMPTY_PATH) = 0
getdents64(3, 0x5555555668b0 /* 3 entries */, 32768) = 96
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/run/systemd/userdb/io.systemd.DynamicUser"}, 45) = 0
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
epoll_create1(EPOLL_CLOEXEC)            = 5
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC|TFD_NONBLOCK) = 6
epoll_ctl(5, EPOLL_CTL_ADD, 6, {events=EPOLLIN, data={u32=1431759744, u64=93824992340864}}) = 0
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
epoll_ctl(5, EPOLL_CTL_ADD, 4, {events=0, data={u32=1431761920, u64=93824992343040}}) = 0
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
getpid()                                = 777807
write(2, "1630400378 WARNING torsocks[7778"..., 1341630400378 WARNING torsocks[777807]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:567)
) = 134
writev(2, [{iov_base="Assertion 'fclose_nointr(f) != -"..., iov_len=107}, {iov_base="\n", iov_len=1}], 2Assertion 'fclose_nointr(f) != -EBADF' failed at src/basic/fd-util.c:125, function safe_fclose(). Aborting.
) = 108
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], 8) = 0
getpid()                                = 777807
gettid()                                = 777807
tgkill(777807, 777807, SIGABRT)         = 0
rt_sigprocmask(SIG_SETMASK, [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=777807, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
</pre>
</details>

**Comment by yuwata** [comment]
with systemd-247.2-3.1.fc33.x86_64.
```
           PID: 260012 (id)
           UID: 1000 (watanabe)
           GID: 1000 (watanabe)
        Signal: 6 (ABRT)
     Timestamp: Tue 2021-08-31 18:47:36 JST (1min 8s ago)
  Command Line: id foo
    Executable: /usr/bin/id
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (watanabe)
       Boot ID: 311bd0fd555b458298ebd0924744ff69
    Machine ID: af1ad4213fa64709b7f68ade7f5c7577
      Hostname: thinkpad-x280
       Storage: /var/lib/systemd/coredump/core.id.1000.311bd0fd555b458298ebd0924744ff69.260012.1630403256000000.zst
       Message: Process 260012 (id) of user 1000 dumped core.
                
                Stack trace of thread 260012:
                #0  0x00007f6bbe7ea9e5 raise (libc.so.6 + 0x3d9e5)
                #1  0x00007f6bbe7d38a4 abort (libc.so.6 + 0x268a4)
                #2  0x00007f6bbe3ae2c7 log_assert_failed.cold (libnss_systemd.so.2 + 0x82c7)
                #3  0x00007f6bbe3dd54f safe_fclose.isra.0 (libnss_systemd.so.2 + 0x3754f)
                #4  0x00007f6bbe3c9e0c varlink_enqueue_json (libnss_systemd.so.2 + 0x23e0c)
                #5  0x00007f6bbe3d0c9d userdb_connect (libnss_systemd.so.2 + 0x2ac9d)
                #6  0x00007f6bbe3d13fe userdb_start_query.lto_priv.0 (libnss_systemd.so.2 + 0x2b3fe)
                #7  0x00007f6bbe3b46df _nss_systemd_getpwnam_r (libnss_systemd.so.2 + 0xe6df)
                #8  0x00007f6bbe879c8b getpwnam_r@@GLIBC_2.2.5 (libc.so.6 + 0xccc8b)
                #9  0x00007f6bbe87957c getpwnam (libc.so.6 + 0xcc57c)
                #10 0x0000555cfb6d25f1 parse_with_separator.constprop.0 (id + 0x45f1)
                #11 0x0000555cfb6d0e38 main (id + 0x2e38)
                #12 0x00007f6bbe7d51e2 __libc_start_main (libc.so.6 + 0x281e2)
                #13 0x0000555cfb6d12be _start (id + 0x32be)
```

**Comment by poettering** [comment]
torsocks appears to block getpid() i.e. syscall 39. That's an entirely benign syscall.

Either way, either torsocks should not allow NSS or not do weird stuff like this and block syscalls such as getpid() from NSS modules.

Nothing we could fix in systemd. Please talk to torscoks instead.

**Comment by zsugabubus** [comment]
Couldn't `getpid() = -1` case somehow be made non-fatal/non-crashing? Is it a that hard requirement?

And what is the relation between a failed `getpid()` and a crashing `safe_fclose()`? Does not it signal some kind of bug?

**Comment by poettering** [comment]
See getpid() docs: "these functions are always successful". Its stupid and against specs to prohibit that.

**Comment by poettering** [comment]
My guess is that glibc uses getpid() as part of the implementation of fclose() and this then propagates to us, and we hit the assert. Destructors must always succeed. fclose() is a destructor, and if it can fail then bad things are in play. Hence we assert on it, as it is likely a programming error somewhere.

**Comment by zeuner** [comment]
> Destructors must always succeed. fclose() is a destructor, and if it can fail then bad things are in play. Hence we assert on it, as it is likely a programming error somewhere.

For the sake of harmonizing the API with RAII-based languages, I fully agree.

However, even the latest specification IEEE Std 1003.1-2017 specifically states that `fclose` may indicate errors, including EBADF.

So, if someone can get a more RAII-compatible behaviour standardized for a future specification, that would be great. But until then, it would have advantages if systemd worked robustly on systems that adhere to the current specification.

**Comment by mnn** [comment]
Looking at torsocks git, it looks like version in main branch should pass the calls. But when I tried it (`torsocks-git` from AUR), it still crashes:

```
> torsocks id foo
Assertion 'fclose_nointr(f) != -EBADF' failed at src/basic/fd-util.c:125, function safe_fclose(). Aborting.
[1]    994508 IOT instruction (core dumped)  torsocks id foo
```

It no longer prints any warnings, so I think I have a correct version.

**Comment by keszybz** [comment]
man says:
fclose(3): 
> EBADF  The file descriptor underlying stream is not valid.
>
> The fclose() function may also fail and set errno for any of the  errors  specified for the routines close(2), write(2), or fflush(3).

close(2):
> EBADF  fd isn't a valid open file descriptor.

write(2):
> EBADF  fd is not a valid file descriptor or is not open for writing.

fflush(3):
> EBADF  stream is not an open stream, or is not open for writing.

So it's pretty clear that EBADF must not happen unless there's some programming error. We ignore other errors except EBADF in `safe_fclose()`.
