### ISSUE TITLE
IPv6 incorrectly not found on Virtuozzo containers

### ISSUE THREAD

**Issue by jorgenschaefer** [systemd/systemd#2059]
systemd [uses the presence of `/sys/module/ipv6`](https://github.com/systemd/systemd/blob/master/src/basic/socket-util.c#L442-L443) to decide whether IPv6 is supported on the current system or not. The whole `/sys/modules/` directory is unavailable on Virtuozzo containers:

```
$ ls /sys/
block/  class/  dev/  devices/  fs/  kernel/
```

This leads to the weird situation that a socket unit with `ListenStream=8080` shows `Listen: 0.0.0.0:8080` in `systemctl status` and `ListenStream=[::1]:8080` leads to an invalid argument error, even though IPv6 works perfectly fine otherwise.

Maybe `/proc/net/sockstat6` or `/proc/net/if_inet6` would be better (additional?) choices to detect IPv6 support?

**Comment by poettering** [comment]
Hmm, IIRC /proc/net/if_inet6 and suchlike are around even if ipv6 is explicitly disabled on the kernel cmdline with `ipv6.disable=1`?

I am happy to change the check, as I think hiding /sys/module is not a completely off idea... But we'd need a check that can fully replace the current check we have in place, i.e. detect both if ipv6 is disabled at compile-time and at boot-time. And iirc `test -f /proc/net/if_init6` is not good enough for that, it only checks for compile-time enablement. Any chance you can test and verify this, and if needed find some way that works reliably in all cases?

**Comment by jorgenschaefer** [comment]
On a 3.14 system with `ipv6.disable=1` and `CONFIG_IPV6=y`, I have neither `if_inet6` nor `sockstat6`:

```
$ ls /proc/net/
arp   connector  dev_mcast  fib_triestat  hidp  igmp         ip_mr_vif  mcfilter   netlink  packet     psched  raw    rt_acct   sco   sockstat      stat  udp      unix
bnep  dev        fib_trie   hci           icmp  ip_mr_cache  l2cap      netfilter  netstat  protocols  ptype   route  rt_cache  snmp  softnet_stat  tcp   udplite  wireless
```

**Comment by poettering** [comment]
OK, sounds like a suitable check then.

**Comment by poettering** [comment]
(happy to take a patch)
