### ISSUE TITLE
Allow user-specified MAC address in systemd-nspawn

### ISSUE THREAD

**Issue by kstenerud** [systemd/systemd#20607]
**Is your feature request related to a problem? Please describe.**

I've had two systemd-nspawn containers spawn with the same MAC address due to some kind of algorithm collision, and could only resolve the issue by resorting to a hack: Create a fake service that uses `ip link` to force-change the MAC address. Originally it was just this:

```
/run/current-system/sw/bin/ip link set dev eth0 address 12:34:56:78:90:00
/run/current-system/sw/bin/ip addr flush eth0
```

But that only works sometimes because even with `Before=dhcpcd.service` it still sometimes runs after, and gets a DHCP address using the systemd auto-generated MAC address. So now I've got a double-hack in place:

```
/run/current-system/sw/bin/ip link set dev eth0 address 12:34:56:78:90:00
/run/current-system/sw/bin/systemctl stop dhcpcd.service
/run/current-system/sw/bin/ip addr flush eth0
/run/current-system/sw/bin/systemctl start dhcpcd.service
```

This makes me nervous, but at least it's running consistently (for now).

A second reason is that in larger deployments, it's generally easier to move the MAC address around from say a physical machine or VM to your new container providing the same service, so that the existing infrastructure doesn't need to be updated (also it makes rollbacks MUCH easier).

**Describe the solution you'd like**

I'd like a config option to specify what MAC address to spawn the container with.

**Describe alternatives you've considered**

One could in theory use networkd to control it within the container, but that's not an option for me since NixOS doesn't have networkd integration. It also makes it harder for orchestration services to use systemd-nspawn since they now have to tinker with the internal container files rather than just deal with the hypervisor directly, and that tends to be fragile.

**The systemd version you checked that didn't have the feature you are asking for**

systemd 247 (247)

Also checked on https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html

**Comment by yuwata** [comment]
MAC address is generated from
1. host's /etc/machine-id,
2. container name,
3. interface type, and
4. index of interface when multiple interface exists.

So, why the MAC addresses in your setup conflict??

**Comment by kstenerud** [comment]
I have no idea how it happened. All I know is that it happened during a test deployment run and now everyone's paranoid about a black swan event happening in a production environment that we can't mitigate except with the above ugly hack.

No matter what magic you rely upon to generate IDs, the parts are complicated and something in the real world will eventually contrive to falsify your assumed invariants, which is precisely why users need to be able to disable it or bypass it and replace it with something suited to their environment.

Magic is bad. Magic that can't be disabled is even worse.

**Comment by kstenerud** [comment]
I can also see other problems with the MAC address generator inputs as described.

For example, suppose one of our boxes dies. No problem: just redeploy the same software configuration on a new machine. Except that the networking is now broken because while each container still has the same name, interface type and index, the host's machine-id is different. So now all the containers' MAC addresses are different. So now the DHCP server doesn't recognize them anymore, and depending on configuration they either get their request refused (network stops working), or they get assigned the wrong address (firewalls stop cooperating, other machines can't find them, etc). Determinism goes out the window because of an obscure dependency on the emergent properties of the host.

The other container managers and hypervisors (in addition to their own default internal generator) allow you to specify a custom MAC address when defining a machine. They do this because MAC addresses are used in so many different ways in the real world, and so it's critical for users to have control over how they get generated (especially when it comes to devops).

**Comment by poettering** [comment]
Happy to take a patch that checks some env var or so that allows to override the mac address to use

**Comment by kstenerud** [comment]
Actually it's worse than 46 bits since many of the "random" inputs to the generator algorithm aren't random.

You end up with the worst of all worlds: Not very random (so you can get collisions), but affected enough by your environment that migrating containers breaks things.

**Comment by poettering** [comment]
@kstenerud hmm? we hash the MAC we use from 4 values, see https://github.com/systemd/systemd/issues/20607#issuecomment-909961329 above.  /etc/machine-id is generated from the Linux RNG at first boot. It#s the random source all crypto on Linux is basically built on. If you can generate collisions from that so easily, you certainly have bigger problems. And the hash function we use is siphash, which is a cryptographic one. if you manage to trigger a collision in that you also have a major problem.

Maybe your setup is broken, and you replicate /etc/machine-id across a large number of systems or so?

**Comment by kstenerud** [comment]
Nope, machine-id is never touched. And yet we ended up with two identical MAC addresses while stress testing the deployment, which threw everyone for a loop as strange flakes started happening all over.

But the second issue is worse from a deployment perspective: If I try to rebuild the same container (same script, same settings) on a different host machine that I've spun up, it will get a different MAC address according to that algorithm. That's bad because people do this all the time when migrating services to another host (maybe the old host is overloaded, or it died). If the MAC address changes merely from moving the container to a new host, it breaks a whole slew of things.

**Comment by kstenerud** [comment]
Another thing to note:

Some organizations have a central MAC address registry, which serves two purposes:

1. No collisions are possible. Ever.
2. Services that index on MAC address directly or indirectly (DHCP, WoL, PXE, firewalls etc) can pre-register before the machine actually goes live.

Competing for adoption will be harder if you're the only one that doesn't support custom MAC addresses.

**Comment by poettering** [comment]
> Competing for adoption will be harder if you're the only one that doesn't support custom MAC addresses.

Nah, not how this works. Happy to take a patch that makes this configurable via env var, but I am pretty sure otherwise this is not going to happen anytime soon. "competition" in the container area is not really what we care about..

(And while I agree that it might be useful in some cases to pick mac adresses explicitly, I'd prefer not have this exposed as primary config concept — i.e. not via config file or cmdline param, but via env var — since conceptually I am pretty sure it should not be how containers should be used, and hence not what we push people towards.)

**Comment by jrouleau** [comment]
In my case, my service provider generates MAC addresses for IPs so I have no choice but to use the ones they provide. Not being able to declaratively define a container's MAC address means relying on runtime userspace hacks. This should be configurable by cmdline param.
