### ISSUE TITLE
Please document how to reload changes to /etc/systemd/resolved.conf

### ISSUE THREAD

**Issue by setharnold** [systemd/systemd#20604]
Hello, I looked in both `systemd-resolved.service(8)` and `resolved.conf(5)` for instructions on how to make changes to `/etc/systemd/resolved.conf` visible to the running system.

My guesses:

- `systemctl restart systemd-resolved`
- `systemctl daemon-reload`
- `systemctl daemon-reload && systemctl restart systemd-resolved`

Of course there's always the possibility that there's an inotify watch on the file, or it's re-read on every single dns lookup.

Some clear advice on what steps, if any, an admin needs to take after changing `/etc/systemd/resolved.conf` in both `systemd-resolved.service(8)` and `resolved.conf(5)` would be very welcome.

Thanks

**Comment by eworm-de** [comment]
A `systemctl restart systemd-resolved.service` does the job, touching pid 1 is not required.

But let's extend this... Any chance to make `systemd-resolved` reload its configuration without restart? It's functionality is extended, and it reads not just `resolved.conf` but also `*.dnssd` files now. Currently adding, modifying or remove a file requires a service restart, no?

**Comment by eworm-de** [comment]
Oh, #17503 is related...
