### ISSUE TITLE
List active configurations of a specific service.

### ISSUE THREAD

**Issue by krave1986** [systemd/systemd#20611]
I'm always frustrated when I want to find the exactly effective configuration of a specific service.
Take systemd-journald.service as an example.

According to the man page of journald.conf.d, there are various files reside in at least 5 different directories affect current configuration of systemd-journald.service.

It is quite hard to find what currently it is.

**Describe the solution you'd like**

`systemctl list-config systemd-journald.service` lists the current configuration.

**The systemd version you checked that didn't have the feature you are asking for**

systemd 245 (245.4-4ubuntu3.11)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Comment by yuwata** [comment]
Please try to use `systemd-analyze cat-config`.
