### ISSUE TITLE
systemctl status should not say *vendor* preset when the preset is from /etc or /run

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#2062]
"vendor preset: enabled" is fine when the preset this settings comes from is in `/usr/lib/systemd/system-preset`. But when it is in `/etc/systemd/system-preset` <strike>or `/run/systemd/system-preset`</strike>, "vendor" is wrong. Ideally, we would give the location of the preset, e.g. "vendor preset: enabled", "config preset: enabled", <strike>"runtime preset: enabled"</strike> for each of the <strike>three</strike> locations. Not sure about the exact names though. Maybe "/etc preset" <strike>and "/run preset"</strike> should be used instead.

**Comment by poettering** [comment]
We do not read /run/systemd/system-preset actually.

And I am not sure the usecase for reading /etc/systemd/system-preset is really that good... Anyway, as the current code reads it we might very well change the wording in that case...

**Comment by keszybz** [comment]
I think reading `/etc/systemd/system-preset` is important: it allows the admin to override vendor config before installing a package. (In principle they could undo the changes after installation, but preventing them from happening instead is much cleaner.)

**Comment by lucab** [comment]
For reference, we rely on `/etc/systemd/system-preset` in ContainerLinux to ship service units which are part of the distribution and disabled by default (or started in some other ways, e.g. socket activated), but can be enabled by the user when provisioning the machine.

**Comment by poettering** [comment]
Fixed in c1e0dc9c882dfae7ba4bf49c50fd253ea199e7d9
