### ISSUE TITLE
systemd-boot: Support watchdog

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#20623]
**Is your feature request related to a problem? Please describe.**
`systemd-boot` supports [Automatic Boot Assessment](https://systemd.io/AUTOMATIC_BOOT_ASSESSMENT/), but for it to automatically revert the new version can't be completely broken (kernel panic, rootfs not found, kernel bug, etc.).

**Describe the solution you'd like**
`systemd-boot` should support triggering the watchdog before handing control over to the EFI executable. This way the system can automatically revert without user interaction. 

**Describe alternatives you've considered**
A different bootloader with watchdog support, ex: [Das U-Boot](https://github.com/ARM-software/u-boot/blob/master/doc/README.watchdog).

**The systemd version you checked that didn't have the feature you are asking for**
```sh
$ systemctl --version
systemd 249 (249.3+)
-PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK -SECCOMP -GCRYPT -GNUTLS +OPENSSL
 -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC -KMOD -LIBCRYPTSETUP +L
IBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB -ZSTD -XKB
COMMON -UTMP -SYSVINIT default-hierarchy=hybrid
```

**Comment by poettering** [comment]
We set the UEFI watchdog already right before invoking the kernel:

https://github.com/systemd/systemd/blob/main/src/boot/efi/boot.c#L2535

What else do you need?

**Comment by klausenbusk** [comment]
> What else do you need?

From the [UEFI spec](https://uefi.org/sites/default/files/resources/UEFI%20Spec%202_6.pdf) (page 224):
> The watchdog timer is only used during boot services.  On successful completion of 
EFI_BOOT_SERVICES.ExitBootServices() the watchdog timer is disabled.

So if the system "crashes" between the kernel calling `ExitBootServices` and userspace being ready the system is just stuck. Ideally the watchdog timer wouldn't be disabled before userspace is ready to ping the watchdog, but I'm not sure that is easily doable?

**Comment by poettering** [comment]
ExitBootServices() is called in the kernel binary, i.e. not in sd-boot, but as last step of the EFI stub that is glued in front of the kernel image. I have no idea what one could do there at all to leave the watchdog on during ExitBootServices().

**Comment by poettering** [comment]
So I'd claim UEFI makes this impossible. Even if we'd bypass UEFI, and access the watchdog hw directly, it would reset things again. Without an extension to UEFI I doubt what you are asking for is possible. This would require an extension to the UEFI spec, to add ExitBootServicesButLeaveWatchdogOn() or something in that style...

**Comment by klausenbusk** [comment]
That is unfortunate and sadly just how it is. I will look into a different bootloader or some sort of chaining.

I assume a "stub" calling `ExitBootServices`, starting the watchdog and loading a EFI executable could work, but I assume that is out-of-scope for the systemd project, so I'm closing the issue.

Thanks for your insight :)

**Comment by poettering** [comment]
> That is unfortunate and sadly just how it is. I will look into a different bootloader or some sort of chaining.

But what different bootloader for UEFI would give you this? ExitBootServices() is hardly something you can work-around, unless you opt out of UEFI altogether.


> I assume a "stub" calling `ExitBootServices`, starting the watchdog and loading a EFI executable could work, but I assume that is out-of-scope for the systemd project, so I'm closing the issue.

Hmm, certain UEFI APIs remain accessible after ExitBootServices(). If setting the watchdog is one of them, we can certtainly add support for that to the stub we already have. but of course, this will shorten the window where the watchdog is not in effect, but not remove it.
