### ISSUE TITLE
Networkd: NIC interface swaps names on Intel Server Board S1200BT Family

### ISSUE THREAD

**Issue by Lordcorvin1** [systemd/systemd#20634]
**systemd version the issue has been seen with**
 > All of them for past 2 years at least

**Used distribution**
 > CentOS 7, Ubuntu 16.04 lts, Ubuntu 18.04 lts, CentOS 8

**CPU architecture issue was seen on**
 > e3-1230v2, x64 bit

**Expected behaviour you didn't see**
 > NIC keeping their name on reboot

**Unexpected behaviour you saw**
 > enp9s0 and eno1 swap NIC naming upon reboot. So NIC `#1` has naming of NIC `#2` and vice versa. I narrowed it down to only happen on Intel Server Board S1200BT Family, where both NICs have same model number and share the same PCIe lane.

**Steps to reproduce the problem**
 > Reboot the system with static IP set for a single NIC. ex. enp9s0, after rebooting your enp9s0 might be the NIC without ethernet cable attached.

**Workaround**
> The only workaround I found is to turn off consistent network interface device naming using Grub config to use old eth0 naming scheme `GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"`

**Comment by yuwata** [comment]
> All of them for past 2 years at least

Sorry, here is an upstream bug tracker. Please contact your downstream.

Note, not sure, but I guess this is already fixed by PR #17352.

Closing.
