### ISSUE TITLE
systemd-tmpfiles removes active socket files that have been renamed since bind()

### ISSUE THREAD

**Issue by csalinezh** [systemd/systemd#20635]
**systemd version the issue has been seen with**
 > 249.3-1-arch

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.13.12-arch1-1

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
Active UNIX sockets are left intact

**Unexpected behaviour you saw**
Active UNIX socket files that were renamed get removed by systemd-tmpfiles

**Steps to reproduce the problem**
1. Create an entry for a test directory `/sktest` in tmpfiles.d that have an age of `0` (for easier testing)
2. Create a UNIX socket, for example with Python:
```python
import socket
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.bind("/sktest/aaa")
```
3. Rename the socket file by `mv /sktest/aaa /sktest/bbb`
4. Trigger `systemd-tmpfiles --clean --prefix /sktest`

**Additional program output to the terminal or log subsystem illustrating the issue**

systemd-tmpfiles ships with [the configuration](https://github.com/systemd/systemd/blob/v249/tmpfiles.d/tmp.conf#L11) that will delete contents of /tmp if their "age" are over 10 days. To avoid breaking UNIX domain sockets that are still in use (function `unix_socket_alive`), it will extract a list of such socket paths from `/proc/net/unix` ([function `load_unix_sockets`](https://github.com/systemd/systemd/blob/v249/src/tmpfiles/tmpfiles.c#L423), feature introduced in https://github.com/systemd/systemd/commit/17b9052533551fc786f73f1a2898ac6a28fe1210).

However, the kernel only seems to record the socket path as it was passed to `bind()` (as `sun_path`). Since programs or users might rename that file later, checking kernel data alone (as of v5.13) is not enough to prevent breaking active UNIX sockets.

A notable victim of this feature is the OpenJDK HotSpot JVM: Their "Attach API" considers /tmp to be ["a global well-known location"](https://github.com/openjdk/jdk/blob/jdk-18+13/src/jdk.attach/linux/classes/sun/tools/attach/VirtualMachineImpl.java#L43) for the sockets used in this API. Once triggered, the JVM will keep listening to a UNIX socket `/tmp/.java_pidNNNN`, where the number is the PID of that particular JVM process. However for [some reasons](https://github.com/openjdk/jdk/commit/640336ebe64e38a15ba89081203921c5a5b20499), they first `bind()` to `/tmp/.java_pidNNNN.tmp`, and will remove the `.tmp` suffix after `listen()` completes. This just breaks the active socket detection of systemd-tmpfiles as explained above, and will lead to these java socket files opened more than 10 days ago being removed. Previously, the HotSpot JVM won't close that socket until it exits. Therefore, users won't be able to use the Attach API to debug a JVM again 10 days after their first try, until it is restarted.

This problem was brought up in their mailing list [in June 2019](https://mail.openjdk.java.net/pipermail/serviceability-dev/2019-June/028432.html) and later got fixed together with [JDK-8225690](https://bugs.openjdk.java.net/browse/JDK-8225690), by checking and rebinding that socket file if it vanished. This fix is present since OpenJDK 14, and got backported to OpenJDK 11 (LTS) in July 2021 (in the upcoming 11.0.13 release). Nevertheless, the majority of Java users might still be usng Java 8 or 11, and will be affected by this issue when they use such debuggers.

For the record, IBM / Eclipse OpenJ9 also places some files related to their [dynamic attach mechanism](https://www.eclipse.org/openj9/docs/attachapi/) under /tmp. However they do not appear to use domain socket for this purpose, so is out of scope of this issue.

Maybe for OpenJ9 they should ship with some tmpfiles.d configuration to exclude their directories. However, as can be seen in the case of OpenJDK, the active socket detection feature of systemd-tmpfiles is clearly broken.

**Comment by floppym** [comment]
It seems like there is no reliable way for systemd-tmpfiles to figure out if a unix socket is still being used.

As a workaround, you could install a tmpfiles.d snippet to exclude specific paths from cleanup. For example:
```
X /tmp/.java_pid*
```

**Comment by poettering** [comment]
What Java is doing here isn#t really a good idea. If they want atomic installation of unix sockets (i.e. that they appear under their final name already in listen() state), then they should implement that via symlinks, not by renaming unix sockets. Renaming unix sockets is icky, Linux doesn't track, it makes it impossible to match things up from /proc/net/unix then (and other apis) if you do that.

Hence: I'd claim that what java is doing there is simply a bad idea, they are kinda *asking* for their unix sockets to be deleted automatically.

Moreover, what java is doing there is inherently insecure because vulnerable to collision attacks. I can just take possession of all possible inodes in /tmp if i like that java might want to take (i.e. one for each possible PID, wich is usually quite a small set), and then no java program can start anymore. i.e it's a local DoS vulnerability, and not how things should be done. /tmp is a shared namespace, writable by anyone and hence not safely usable for placing guessable names there.

Hence I am tempted to just close this. There are multiple reasons why Java shouldn't do what it does, and they kinda are asking for this beaviour. If Java maintainers don't want to fix the vulnerabilities in their code, then packagers can of course include a tmpfiles.d/ drop-in that excludes the relevant inodes from clean-up. But quite frankly, that#s a bad idea, it just works around a security issue and introduces new issues (such as unbounded growrth of /tmp).

TLDR: I am tempted to just close this. I disagree that tmpfiles is broken here. It's not "fixable" to us, and what Java is doing there is just asking for this and insecure.

**Comment by csalinezh** [comment]
> I can just take possession of all possible inodes in /tmp if i like that java might want to take (i.e. one for each possible PID, wich is usually quite a small set), and then no java program can start anymore.

Actually that's not true, as this socket file is only used by their dynamic attach mechanism for debugging. It's only those debuggers that will fail.
They will also remove "stale .java_pid file" if such file exists, and have been doing so since 2013 ([JDK-7162400](https://bugs.openjdk.java.net/browse/JDK-7162400), change landed as https://github.com/openjdk/jdk/commit/221308625da2709ecc8e85b7417277ca9882acdb). Such attack won't work as long as the `java` process has the right to delete those offending files (which usually means those files are created by the same user as the one running `java`, or `java` has root permission).

However I agree with you that the behavior of java seems problematic. Maybe I should bring this up in their mailing list.

Nevertheless, shall this limitation of systemd-tmpfiles' active socket detection feature (unable to track socket file name changes) be somehow documented?

**Comment by floppym** [comment]
> Such attack won't work as long as the java process has the right to delete those offending files

It is possible that an "attack process" would be running as a different user, and thus java would be unable to remove them. /tmp has the sticky bit set, so any user can create any file so long as it does not already exist.

**Comment by poettering** [comment]
> Nevertheless, shall this limitation of systemd-tmpfiles' active socket detection feature (unable to track socket file name changes) be somehow documented?

I am not sure this is necessary, i.e. who would look there? I mean, it definitely makes sense to document noteworthy behaviour or important limitations, but does this really qualify? In all those years this hasn't come up at all, this is the first time and the offending java code does something that's really bad. i.e. should we really document that we're incompatible with buggy behaviour that almost noone ever gets into contact with?

I mean, docs are great, but I'd not put information in it that is more likely then not just noise for almost every reader.

**Comment by poettering** [comment]
So I am still tempted to just close this and let Java figure this out.

**Comment by poettering** [comment]
Let's close this. i don't think there's a way how we could fix this even if we wanted to. java needs to fix this properly on their own.
