### ISSUE TITLE
CentOs with systemd 219 failed to log/ssh/console at same time

### ISSUE THREAD

**Issue by xuzw02** [systemd/systemd#20648]
systemd-analyze --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

CentOS Version:
CentOS Linux release 7.3.1611 (Core) 
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Scenarios:
1.Couldn't log to disk
Couldn't log to disk, including systemd logging and custom logging. Looks like the logging suddely stoped with no suspicious logs.

2.ssh refused
Timed out after enter username and password.

3.console connect failed
Tried PuTTY, says Remote side unexpectedlly closed network connection.

Recovery:
Power off and on will restore everything.

Recurrence:
roughly once a week

rsyslogd version:
rsyslogd 7.4.7, compiled with:
  FEATURE_REGEXP:        Yes
  FEATURE_LARGEFILE:      No
  GSSAPI Kerberos 5 support:    Yes
  FEATURE_DEBUG (debug build, slow code):  No
  32bit Atomic operations supported:  Yes
  64bit Atomic operations supported:  Yes
  Runtime Instrumentation (slow code):  No
  uuid support:        Yes

**Comment by yuwata** [comment]
Sorry, please contact your downstream. This is an upstream bug tracker.
