### ISSUE TITLE
( cgroup / scope unit / session ) shutdown signal-propagation: hierarchy and precedence behavior documentation

### ISSUE THREAD

**Issue by gleventhal** [systemd/systemd#20642]
Version systemd-219-78.el7_9.3.x86_64

Typically, people don't define any ordering directives for scope units as they're created ad-hoc.  Upon shutdown, I'd like to know given:

```
├─1 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
├─user.slice
│ ├─user-400.slice
│ │ └─session-75.scope
│ │   ├─2428 sshd: user123 [priv] 
│ │   └─2434 sshd: user123@notty  
│ └─user-12504.slice
│   ├─service-application-generic-935003.scope
│   │ ├─12889 /path/to tools services-daemon start
│   │ └─14673 /usr/bin/python3 /usr/bin/hg serve --cmdserver chgunix --address /tmp/chg1234/server.14567 
```

If service-application-generic-935003.scope happens to have:
KillMode=none
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no

but it is a child of user.slice/, my question is whether I need to worry about any (kill) signal propagation from higher level entities like user.slice/* (which appears to have KillMode=control-group that might end up killing my service during shutdown (this is cgroups v1 API) and where is this documented?

**Comment by poettering** [comment]
Slices only kill on explicit user requests (i.e. systemctl kill), they do not terminate processes on their own based on their own state machine, as they do not directly contain any processes. If a slice goes down, the contained units are terminated first, and they are the ones which are supposed to kill their own processes first.

There are no kill settings for slices hence.

**Comment by poettering** [comment]
And also: this is a bug and RFE tracker. *Not* a support forum. Use the mailing list instead please, to keep noise levels low here. thanks.
