### ISSUE TITLE
systemd-analyze gives wrong firware time

### ISSUE THREAD

**Issue by vickyvikas7988** [systemd/systemd#20653]
Hi team,

if I reboot a bare metal machine from the OS then I get wrong time on the systemd-analyze command.

[root@test-machine~]# last reboot
 reboot   system boot  3.10.0-1160.25.1 Tue Aug 31 17:45 - 17:47  (00:02)
 reboot   system boot  3.10.0-1160.25.1 Tue Aug 31 17:23 - 17:41  (00:18)

 [root@test-mahcine ~]$ systemd-analyze
 Startup finished in 23min 12.915s (firmware) + 54.380s (loader) + 3.583s (kernel) + 13.870s (initrd) + 53.287s (userspace) = 25min 18.036s

Firmware reported wrong time if I am doing it from the OS and if I do reboot outside of console then it reports correct time.

Is it a known issue?

**Comment by poettering** [comment]
> Firmware reported wrong time if I am doing it from the OS and if I do reboot outside of console then it reports correct time.

I can't parse this. What are you trying to say here? Can you elaborate?

The data we present is only as good as what the firmware provides us with. If that data is incorrect there's nothing much we can do about it, it's a bug in your firmware.

**Comment by vickyvikas7988** [comment]
@poettering 
 I am extremely sorry for poor explanation.
 
I have a bare metal instance on a cloud.

When I try to perform a reboot from OS by running the command `reboot` systemd-analyze command shows wrong firmware time.

I did few tests and I will explain it here

1) I initiated reboot at 2021-08-31 17:41:25 from OS.

2) After the boot of OS, I was able to SSH into the vm at  2021-08-31 17:45:37.

3) If you see the time difference it took around 5 minutes to come online (SSH to the VM).
2021-08-31 17:45:37 -  2021-08-31 17:41:25  = 4 minutes and 12 seconds

But systemd-analyze reported 23min 12.915s in the firmware field but it took less than 5 mins to complete full process (stop and boot up state).

[root@test-instance ~]$ systemd-analyze
Startup finished in 23min 12.915s (firmware) + 54.380s (loader) + 3.583s (kernel) + 13.870s (initrd) + 53.287s (userspace) = 25min 18.036s  

Can i know how is firmware time calculated by systemd?


Why I try to reboot the vm from console it shows up the right time.

Please let me know if you have any queries .

**Comment by poettering** [comment]
This looks as if the firmware of your cloud instance isn't in order and it reports boot timestamps incorrectly. Please report that to your cloud vendor. i.e. software-triggered resets apparently don't reset the timestamps there.

There's nothing we can do about that from here.
