### ISSUE TITLE
systemd-cryptenroll --fido2-device=auto fails with libfido2 1.8.0

### ISSUE THREAD

**Issue by martelletto** [systemd/systemd#20664]
As reported in https://github.com/Yubico/libfido2/issues/385.

libfido2 1.8.0 saw the introduction of flock() to serialise device access, as per https://github.com/systemd/systemd/issues/19842.

The problem appears to be caused by [check_device_is_fido2_with_hmac_secret()](https://github.com/systemd/systemd/blob/main/src/shared/libfido2-util.c#L907) leaving the device open. systemd-cryptenroll proceeds to open the device a second time in [fido2_generate_hmac_hash()](https://github.com/systemd/systemd/blob/main/src/shared/libfido2-util.c#L524), leading to a deadlock.

**Comment by iAdmin-PL** [comment]
Confirmed resolved

**Comment by anatol** [comment]
Could you please bring this change to `stable`?

**Comment by anatol** [comment]
@eworm-de it worth bringing this fix to Arch package
