### ISSUE TITLE
Don't allow programs to fill up syslog disks

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#20660]
```
# ls -l /var/log/syslog*
-rw-r----- 1 root adm  50474138 09-08 02:56 /var/log/syslog
-rw-r----- 1 root adm 128216645 09-05 02:19 /var/log/syslog.1
-rw-r----- 1 root adm   6545959 08-29 17:21 /var/log/syslog.2.gz
-rw-r----- 1 root adm   2461098 08-22 12:47 /var/log/syslog.3.gz
-rw-r----- 1 root adm    113542 08-16 01:01 /var/log/syslog.4.gz
-rw-r----- 1 root adm     26718 2021-02-13  /var/log/syslog.6.gz
-rw-r----- 1 root adm     47465 2021-02-12  /var/log/syslog.7.gz
```
Without automatic limits, any program logging to syslog could easily
overflow the disks, causing the whole computer to fail.

Sure, you could say "blame it on that program".

But think of it this way: would you allow single malfunctioning
telephone to bring down the entire exchange (10000 lines)?

Therefore if a certain program writes more than e.g., 500 messages in a short
time, some limits should swing in to action.

**Comment by poettering** [comment]
systemd does not write those files. maybe your rsyslog or syslog-ng does, but systemd does not.
