### ISSUE TITLE
systemd-escape -p '' and systemd-escape -p -u '-' are not inverse.

### ISSUE THREAD

**Issue by traylenator** [systemd/systemd#20663]
**systemd version the issue has been seen with**
systemd-249.4-1.fc36.x86_64

**Used distribution**
 fedora rawhide

**Linux kernel version used** (`uname -a`)
`5.14.0-0.rc7.54.fc36.x86_64`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
`systemd-escape -p ''` and `systemd-escape -p -u '-'` are not inverse.

**Unexpected behaviour you saw**
 ```
systemd-escape -p  ''
-
```

and then trying to map back it should be ''
```
systemd-escape -p -u '-'
/
```
**Steps to reproduce the problem**
 commands as above.

Please note I have zero real-world application of this and I just happened to notice when re-implementing the algorithm in puppet language.

Maybe `systemd-escape -p  ''` should be an error as an invalid path?

**Comment by poettering** [comment]
not sure we should fail. but we probably should warn if the input is not a valid path.
