### ISSUE TITLE
Minimize side effects when running `systemd-sysctl` multiple times

### ISSUE THREAD

**Issue by gogsbread** [systemd/systemd#20677]
**Is your feature request related to a problem? Please describe.**
Currently `systemd-sysctl` binary is used in `systemd-sysctl.service` which is mostly configured as `oneshot`. There are situations where one would like to use systemd to maintain Sysctl configurations on a host, using a configuration managers such as Chef or Puppet, by apply configurations every X duration.
The problem with using `systemd-sysctl` is that it writes all the Sysctl settings, even if the values for those settings have not changed. From experience, we have observed that some Sysctl settings cause actions in the kernel upon writing(like dropping caches) which in turn cause undesired side effects.
We are proposing to upstream a patch that will perform a compare-before-write check to avoid applying Sysctl settings whose values haven't changed.

**Describe the solution you'd like**
[Draft PR](https://github.com/systemd/systemd/pull/20676)

**Describe alternatives you've considered**
 - Make this change optional by default by putting behind a command line flag?

**The systemd version you checked that didn't have the feature you are asking for**
NA

**Comment by poettering** [comment]
Closing, since #20676 got merged.
