### ISSUE TITLE
Receiving RAs appears to be broken

### ISSUE THREAD

**Issue by wak-google** [systemd/systemd#20675]
**systemd version the issue has been seen with**
 > 249.1+

**Used distribution**
 > openembedded

**Linux kernel version used** (`uname -a`)
> 5.10.62

**CPU architecture issue was seen on**
> armv7

**Expected behaviour you didn't see**
 > RAs being accepted and routes / address prefixes being used

**Unexpected behaviour you saw**
 > All of the interfaces are logging `RADV: Unexpected error receiving from ICMPv6 socket, Ignoring: Exchange full`

**Steps to reproduce the problem**
 > Start networkd on a network with something producing RAs
Log all of the traffic with tcpdump and you can see the RAs coming in but not being processed. We can see from the debug logs that networkd is slowly backing off sending RAs

**Comment by wak-google** [comment]
It's hard for me to tell exactly when this started happening, I think it had something to do with moving from kernel 5.10.40 -> 5.10.62 but I need to do some more investigation there. I'm pretty sure this was not happening when we originally moved to v249 of systemd.

**Comment by yuwata** [comment]
This should be already fixed by 9365e296fe281da45797af89a97627e872fc019d.

**Comment by wak-google** [comment]
@yuwata Should I file a bug in systemd-stable for backport? So far my rudimentary attempt at backporting causes systemd-networkd to crash in short order.

**Comment by yuwata** [comment]
Backporting PRs:
v247: https://github.com/systemd/systemd-stable/pull/121
v248: https://github.com/systemd/systemd-stable/pull/122
v249: https://github.com/systemd/systemd-stable/pull/123
