### ISSUE TITLE
Watchdog service broken for drivers without WDIOC_SETTIMEOUT support

### ISSUE THREAD

**Issue by jan-kiszka** [systemd/systemd#20683]
**systemd version the issue has been seen with**
 > 247..main

**Used distribution**
 > Debian 11

**Linux kernel version used** (`uname -a`)

 > `Linux iot2050-debian 5.14.0+ #183 SMP PREEMPT Thu Sep 9 08:26:49 CEST 2021 aarch64 GNU/Linux`
 > This is a custom kernel, but watchdog driver (rti-wdt) is upstream

**CPU architecture issue was seen on**
 > arm64

**Expected behaviour you didn't see**
 > systemd drives watchdog according to the specified RuntimeWatchdogSec period, even if (re-)setting that timeout failes with `EOPNOTSUPP`.

**Unexpected behaviour you saw**
 > Watchdog is not pinged by systemd. System resets after the programmed timeout of the watchdog, either set via `rti_wdt.hearbeat` (kernel command line) or by the bootloader that already started the watchdog.

**Steps to reproduce the problem**
 > On our device (https://github.com/siemens/meta-iot2050/), by patching an existing watchdog driver to drop `WDIOF_SETTIMEOUT`, or by faking `EOPNOTSUPP` in `update_timeout()` (`src/shared/watchdog.c`) for `WDIOC_SETTIMEOUT`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
Sep 09 09:56:27 iot2050-debian systemd[1]: Using hardware watchdog 'K3 RTI Watchdog', version 0, device /dev/watchdog
Sep 09 09:56:27 iot2050-debian systemd[1]: Failed to set timeout to 600s: Operation not supported
...
```

This used to work - more or less by chance - up to 61927b9f116bf45bfdbf19dc2981d4a4f527ae5f which now only considers the watchdog started when the timeout was successfully set. And only a started watchdog is pinged since then.

**Comment by jan-kiszka** [comment]
I'm experimenting with
```patch
diff --git a/src/shared/watchdog.c b/src/shared/watchdog.c
index 361d5837dc..9410fddf6b 100644
--- a/src/shared/watchdog.c
+++ b/src/shared/watchdog.c
@@ -32,12 +32,15 @@ static int update_timeout(void) {
                 if (ioctl(watchdog_fd, WDIOC_SETOPTIONS, &flags) < 0)
                         return log_warning_errno(errno, "Failed to disable hardware watchdog: %m");
         } else {
-                int sec, flags;
+                int sec, current_timeout, flags;
                 usec_t t;
 
+                if (ioctl(watchdog_fd, WDIOC_GETTIMEOUT, &current_timeout) < 0)
+                        current_timeout = -1;
+
                 t = DIV_ROUND_UP(watchdog_timeout, USEC_PER_SEC);
                 sec = (int) t >= INT_MAX ? INT_MAX : t; /* Saturate */
-                if (ioctl(watchdog_fd, WDIOC_SETTIMEOUT, &sec) < 0)
+                if (sec != current_timeout && ioctl(watchdog_fd, WDIOC_SETTIMEOUT, &sec) < 0)
                         return log_warning_errno(errno, "Failed to set timeout to %is: %m", sec);
 
                 log_info("Set hardware watchdog to %s.", FORMAT_TIMESPAN(sec * USEC_PER_SEC, 0));
```

That seems to work as desired so far. Didn't think about Reboot/Shutdown/Kexec settings yet. Conceptually, they should also continue to fail if the user configured a deviating timeout from the one the watchdog is tuned to.

**Comment by jan-kiszka** [comment]
FWIW, the kernel rejected a workaround: https://lore.kernel.org/lkml/4d82b8ce-bc34-e4b2-c5fe-9e883b0db59d@siemens.com (we will still carry this locally for now - easier than keeping a patched systemd for Debian)

**Comment by fbuihuu** [comment]
It may make sense to fallback to the timeout used by the device if it returns -EOPNOTSUPP with WDIOC_SETTIMEOUT in any cases. However it seems awkward to configure a (arbitrary) timeout value in system.conf to support this case (ie open the watchdog and reuse the driver value). 

Maybe we could introduce a new kernel command line option to support this specific case ?

Something like `systemd.watchdog_start[=timeout]` which would take an optional timeout parameter. The parameter would specify the desired timeout value in sec. If the parameter is not passed then it would reuse the driver value.

**Comment by fbuihuu** [comment]
Fix proposal waiting in https://github.com/systemd/systemd/pull/20787.

**Comment by poettering** [comment]
> It may make sense to fallback to the timeout used by the device if it returns -EOPNOTSUPP with WDIOC_SETTIMEOUT in any cases. However it seems awkward to configure a (arbitrary) timeout value in system.conf to support this case (ie open the watchdog and reuse the driver value).

I wouldn't see it that way: setting a timeout is "best effort" stuff, i.e. you get the timeout if we can set it, and if we don#t you dont. And even if we are able to set it then very likely you'll actually just get a timeout close to what you asked for, given hw limitations.

**Comment by poettering** [comment]
> Maybe we could introduce a new kernel command line option to support this specific case ?
> 
> Something like `systemd.watchdog_start[=timeout]` which would take an optional timeout parameter. The parameter would specify the desired timeout value in sec. If the parameter is not passed then it would reuse the driver value.

I amnot sure I follow what this has to do with drivers that lack WDIOC_SETTIMEOUT?

I mean, adding such a kernel cmdline option sounds ok, but it appears to me has little to do with wether the driver supports setting the timeout or not.
