### ISSUE TITLE
systemd freezes for minutes with around 4000 IpAddressAllow lines on a unit file

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20680]
**systemd version the issue has been seen with**
 > 248.7

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `5.13.13`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > It should perform fast on boot

**Unexpected behaviour you saw**
 >  It hangs for several minutes, doing timeouts when running multiple systemctl commands and PID 1 consuming 100% CPU.

**Steps to reproduce the problem**
 > `systemctl edit sshd`
Add:
```
[Service]
IPAccounting=yes
IPAddressDeny=any
```

Then get some IPv4/IPv6 block lists, e.g. from ipverse.net and prepend lines with `IpAddressAllow=` and append them. Save and quit. It will timeout when applying the systemctl daemon-reload. In case of a reboot it freezes for a while in the switching root step.

Tested with 280 lines, systemd-analyze blame took less than 1 second for `initrd-switch-root.service`. Tested with around 4000 lines, systemd-analyze took over 7 minutes to boot.

**Comment by yuwata** [comment]
I hope #20697 fixes your issue.

**Comment by fdelapena** [comment]
Thank you, tested the packit packages on rawhide and it works actually fast now with thousands of lines with prefixes :+1:.

> systemd 249 (v249-1.20210910081249733451.pr20697.754.g01d3167bb8.fc36)

> 1.151s initrd-switch-root.service
