### ISSUE TITLE
Systemd socket problems with MaxConnectionsPerSource when service fails

### ISSUE THREAD

**Issue by tmuncks** [systemd/systemd#20685]
**systemd version the issue has been seen with**
 > systemd-249.4-1.fc36.x86_64

**Used distribution**
 >  Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `Linux fedora 5.15.0-0.rc0.20210902git4ac6d90867a4.4.fc36.x86_64 #1 SMP Thu Sep 2 19:28:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Once a connection is dead/inactive or the service is dead/finished, the connection listed under Triggers for the socket, should be removed, and the socked should allow new connections to the socket from the same IP. `MaxConnectionsPerSource` should monitor active connections only.

**Unexpected behaviour you saw**
 > When the service called by the socket fails (e.g. because of a timeout), then connection is never freed from the `MaxConnectionsPerSource` list, and new connections are not allowed until the failed services are stopped somehow or counters cleared. systemctl daemon-reload seems to help, but not reliably. systemctl restart ttt.socket noes not appear to help.

**Steps to reproduce the problem**

Trying to be thorough here - First we need to prepare a socket and service for the test:

 > Install this file as /etc/systemd/system/ttt.socket
```
[Unit]
Description=TEST socket

[Socket]
ListenStream=7777
Accept=true
MaxConnectionsPerSource=3

[Install]
WantedBy=sockets.target
```
> Install this file as /etc/systemd/system/ttt@.service
```
[Unit]
Description=TEST

[Service]
ExecStart=-/usr/local/bin/ttt
Type=forking

User=root
Group=root

StandardInput=socket
```
> Install this file as /usr/local/bin/ttt
> (make sure the sleep number is larger than the service timeouts)

> Run: chmod +x /usr/local/bin/ttt
```
#!/bin/bash
echo TEST OUTPUT for process: $$
echo Sleeping...
sleep 120
```
> Run: systemctl daemon-reload
> Run: systemctl enable ttt.socket
> Run: systemctl start ttt.socket

Then we can run the actual test:

> Connect to the socket 4 times
> Once you see "Sleeping...", you can hit CTRL+C)
> Attempt number 4 will fail (because of `MaxConnectionPerSource=3`)
```
[root@fedora ~]# nc -v localhost 7777
Connection to localhost (::1) 7777 port [tcp/cbt] succeeded!
TEST OUTPUT for process: 9109
Sleeping...
^C
[root@fedora ~]# nc -v localhost 7777
Connection to localhost (::1) 7777 port [tcp/cbt] succeeded!
TEST OUTPUT for process: 9113
Sleeping...
^C
[root@fedora ~]# nc -v localhost 7777
Connection to localhost (::1) 7777 port [tcp/cbt] succeeded!
TEST OUTPUT for process: 9117
Sleeping...
^C
[root@fedora ~]# nc -v localhost 7777
Connection to localhost (::1) 7777 port [tcp/cbt] succeeded!

[root@fedora ~]# 
```

After a few minutes, check the status of the socket and processes:

```
[root@fedora ~]# systemctl status ttt.socket
● ttt.socket - TEST socket
     Loaded: loaded (/etc/systemd/system/ttt.socket; enabled; vendor preset: disabled)
     Active: active (listening) since Thu 2021-09-09 08:52:04 -02; 3min 47s ago
   Triggers: ● ttt@3-::1:7777-::1:49680.service
             ● ttt@4-::1:7777-::1:49682.service
             ● ttt@5-::1:7777-::1:49684.service
     Listen: [::]:7777 (Stream)
   Accepted: 6; Connected: 0;   Refused: 8
      Tasks: 0 (limit: 9159)
     Memory: 8.0K
        CPU: 26ms
     CGroup: /system.slice/ttt.socket

Sep 09 08:52:04 fedora systemd[1]: Listening on TEST socket.
Sep 09 08:52:09 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:52:15 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:52:25 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:53:56 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
[root@fedora ~]# ps aux |grep ttt
root        9156  0.0  0.0   6440  2056 pts/0    S+   08:55   0:00 grep --color=auto ttt
[root@fedora ~]# systemctl status ttt@3-::1:7777-::1:49680.service
× ttt@3-::1:7777-::1:49680.service - TEST ([::1]:49680)
     Loaded: loaded (/etc/systemd/system/ttt@.service; static)
     Active: failed (Result: timeout) since Thu 2021-09-09 08:53:52 -02; 2min 12s ago
TriggeredBy: ● ttt.socket
    Process: 9109 ExecStart=/usr/local/bin/ttt (code=killed, signal=TERM)
        CPU: 22ms

Sep 09 08:52:22 fedora systemd[1]: Starting TEST ([::1]:49680)...
Sep 09 08:53:52 fedora systemd[1]: ttt@3-::1:7777-::1:49680.service: start operation timed out. Terminating.
Sep 09 08:53:52 fedora systemd[1]: ttt@3-::1:7777-::1:49680.service: Failed with result 'timeout'.
Sep 09 08:53:52 fedora systemd[1]: Failed to start TEST ([::1]:49680).
```
The services are still listed under `Triggers` for the socket unit. The processes are no longer there, however, and the service units are listed as failed (Result: timeout).

> Now try to connect again:
```
[root@fedora ~]# nc -v localhost 7777
Connection to localhost (::1) 7777 port [tcp/cbt] succeeded!

[root@fedora ~]# systemctl status ttt.socket
● ttt.socket - TEST socket
     Loaded: loaded (/etc/systemd/system/ttt.socket; enabled; vendor preset: disabled)
     Active: active (listening) since Thu 2021-09-09 08:52:04 -02; 7min ago
   Triggers: ● ttt@3-::1:7777-::1:49680.service
             ● ttt@4-::1:7777-::1:49682.service
             ● ttt@5-::1:7777-::1:49684.service
     Listen: [::]:7777 (Stream)
   Accepted: 6; Connected: 0;   Refused: 9
      Tasks: 0 (limit: 9159)
     Memory: 8.0K
        CPU: 31ms
     CGroup: /system.slice/ttt.socket

Sep 09 08:52:04 fedora systemd[1]: Listening on TEST socket.
Sep 09 08:52:09 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:52:15 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:52:25 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:53:56 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
Sep 09 08:59:38 fedora systemd[1]: ttt.socket: Too many incoming connections (4) from source ::1, dropping connection.
```

The connection will still be rejected and a new log entry (Too many incoming connections from source) is added to the log.

**Comment by poettering** [comment]
This actually works as intended. The instances are actually in "failed" state, and those count too. The thing is that they are of Type=forking, and thus it is expected that they exit in the procss we fork off (leaving a child around) to indicate startup success. But this never happens, so this eventually times out. This time-out then puts the service into "failed" state, and failed units also count against MaxConnectionsPerSource. after all, this is about limiting resources a rogue client can pin on the host, and since we don't GC "failed" services like we GC dead services otherwise, this would pin the resources for good.

You can get rid of the failed services via `systemctl reset-failed`, which will immediately allow you to connect again.

You could CollectMode=inactive-or-failed to the service unit. This has the effect that the service will be collected (i.e. freed from memory) even on failure, and thus the count goes down immediately, even when the timeout is hit.

I'll now convert this to a documentation bug because I don't think we should change the code here. We should document this however, and point people towards CollectMode=

**Comment by tmuncks** [comment]
Thanks for a thorough response, everything makes perfect sense now. I was simply unaware that this was a GC feature and that it could be altered with CollectMode.

Thank you

Sent from mobile device, please excuse brevity.
________________________________

**Comment by poettering** [comment]
So after thinking about this I think there's still something to fix here, because MaxConnections and MaxConnectionsPerSource actually count differently currently.

The comment about CollectMode= is relevant still, and I will add relevant docs, too now.
