### ISSUE TITLE
attach stdin/stdout to a running service

### ISSUE THREAD

**Issue by alban** [systemd/systemd#2069]
Is there a way to attach stdin/stdout to a currently running service?

```
$ systemctl start myapp.service
$ systemctl attach myapp.service
```

It would be the equivalent of `docker attach`. Maybe a new option in [StandardOutput](http://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardInput=)?

```
StandardOutput=tty-allocate
TTYPath="allocate a new tty so that 'systemctl attach' can later be plugged on it"?
```

It would help for https://github.com/coreos/rkt/issues/1799.

**Comment by poettering** [comment]
There's "journalctl -u myapp.service -f", which outputs whatever that service is printing.

Just allocating a pty wouldn't suffice, something needs to process what is written to it, otherwise the daemon would eventually just stall...

How precisely is this all supposed to work?

**Comment by alban** [comment]
I don't know, I was hoping that some smart idea would emerge. I haven't thought that it would require an additional process to process the stream. Annoying.

If some utility wrapping the service is implemented to allocate a pty and process the data (like "tee(2)", forwarding both to stdout/journal and to anyone connecting to it via the "attach" command), should this be part of systemd, or an external project?

**Comment by keszybz** [comment]
I think this should be external.

See
- http://www.isi.edu/~yuri/dupx/ or
- https://github.com/jerome-pouiller/reredirect/ or
- http://pasky.or.cz/dev/retty/ or
- https://github.com/nelhage/reptyr. 

This last one seems most alive. There's even a Fedora package https://apps.fedoraproject.org/packages/reptyr.

**Comment by poettering** [comment]
Closing this, as I really see no good way to implement this.

**Comment by rhysperry111** [comment]
We've got the ability to send stdout/in/err to pipes and sockets - maybe a nice option to have systemd auto-allocate a socket/pipe which can then be attached to with `systemctl` would be nice
