### ISSUE TITLE
New drop-in change detection issue

### ISSUE THREAD

**Issue by Threadnaught** [systemd/systemd#20706]
**systemd version the issue has been seen with**
```
$ sudo systemctl --version
systemd 245 (245.4-4ubuntu3.3)
```

**Used distribution**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
**Linux kernel version used** (`uname -a`)
```
$ uname -a
Linux gv-acm-1324050001 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
**CPU architecture issue was seen on**
```
x86_64
```

**Expected behaviour you didn't see**
After adding a fresh drop-in override, `systemctl show (service) --property=NeedDaemonReload` should report `NeedDaemonReload=yes`.

**Unexpected behaviour you saw**
It reported `NeedDaemonReload=no`.

**Steps to reproduce the problem**
Here is the script which I used to demonstrate the problem (needs sudo);
```
#!/bin/bash

#Clear files from any previous runs:
rm -rf /etc/systemd/system/test-demo.service*
systemctl daemon-reload

#Add base unit file and load it:
cat <<EOF > /etc/systemd/system/test-demo.service
[Unit]
Description=Test Service
After=systend-user-sessions.service

[Service]
Type=simple
ExecStart=/usr/bin/true
EOF
systemctl daemon-reload

#Add drop-in
cat <<EOF /etc/systemd/system/test-demo.service.d/override.conf
[Service]
ExecStart=/usr/bin/false
EOF

echo "should be yes:"
systemctl show test-demo --property=NeedDaemonReload
```

**Comment by yuwata** [comment]
Sorry, here is an upstream bug tracker, and v245 is slightly old. Please contact to your downstream, or try to reproduce it with the recent release or current git master.

**Comment by Threadnaught** [comment]
@yuwata I've reproduced the issue on v247, is that recent enough?

**Comment by Threadnaught** [comment]
I tried on v247, the bug is no longer present. Thanks.
