### ISSUE TITLE
Unable to use swtpm emulator with systemd-cryptenroll

### ISSUE THREAD

**Issue by anatol** [systemd/systemd#20708]
**systemd version the issue has been seen with**
systemd 249.4-1

**Used distribution**
up-to-date Arch Linux

**Linux kernel version used** (`uname -a`)
Linux mycomp.lan 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
x86_64

I am trying to use systemd-cryptsetup+TPM2 for my tests. As my tests suppose to run at many systems (including those that do not have a TPM2 chip) I try to use a TPM2 emulator called [swtpm](https://github.com/stefanberger/swtpm). Other parts of my projects (e.g. github.com/anatol/clevis.go) are able to use swtpm successfully.

Now I am trying to use swtpm with `systemd-cryptenroll`. I am running it as `sudo  TSS2_LOG=all+ERROR,marshal+TRACE,tcti+DEBUG systemd-cryptenroll --tpm2-device=swtpm: $mydev`. Pay attention to `--tpm2-device=swtpm:` that is format expected by systemd's `tpm2_init()` function. It is able to parse the device and load `libtss2-tcti-swtpm.so.0` as expected.

Then it passes `swtpm:` string to `init()` function as `rc = info->init(tcti, &sz, device);` and it confuses TSSI library:

```
debug:tcti:src/tss2-tcti/tcti-swtpm.c:570:Tss2_Tcti_Swtpm_Init() Dup'd conf string to: 0x562f91cbc000 
debug:tcti:src/util/key-value-parse.c:85:parse_key_value_string() parsing key/value: swtpm: 
WARNING:tcti:src/util/key-value-parse.c:50:parse_key_value() key / value string is invalid 
Failed to initialize TCTI context: tcti:A parameter has a bad value
```

I tried other parameter values like `swtpm:foo=bar` and it also fails. The reason is that systemd passes `swtpm:` prefix to TSS init function and it does not sound right to me. It looks like this prefix is for systemd consumption only and should be stripped from the value before passing to TSS. I see there is `param` that contains the stripped value and it should be passed to `init()` but for some reason `device` is passed instead.

**Comment by anatol** [comment]
I made this change and it helped to run `systemd-cryptenroll` without a problem:

```patch
diff --git a/src/shared/tpm2-util.c b/src/shared/tpm2-util.c
index 793a54a449..f29686e994 100644
--- a/src/shared/tpm2-util.c
+++ b/src/shared/tpm2-util.c
@@ -184,7 +184,7 @@ static int tpm2_init(const char *device, struct tpm2_context *ret) {
                 if (!tcti)
                         return log_oom();
 
-                rc = info->init(tcti, &sz, device);
+                rc = info->init(tcti, &sz, param);
                 if (rc != TPM2_RC_SUCCESS)
                         return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE),
                                                "Failed to initialize TCTI context: %s", sym_Tss2_RC_Decode(rc));
```

**Comment by poettering** [comment]
That patch looks right. Can you submit as PR? then we can properly attribute it to you!

**Comment by anatol** [comment]
This is a straight-forward bugfix, would it be possible to cherry pick it to stable branches as well?

**Comment by yuwata** [comment]
Backporting PRs:
v248: https://github.com/systemd/systemd-stable/pull/125
v249: https://github.com/systemd/systemd-stable/pull/126

**Comment by anatol** [comment]
@eworm-de it worth bringing this fix to Arch package
