### ISSUE TITLE
systemd-networkd spins at 100% CPU when there are a lot of routes in the kernel routing table

### ISSUE THREAD

**Issue by tohojo** [systemd/systemd#20718]
**systemd version the issue has been seen with**
 > $ networkctl --version
> systemd 249 (249.4-1-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux ten64-borgen 5.13.12-1-ARCH #2 SMP Fri Aug 20 09:14:39 UTC 2021 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > systemd-networkd should run without spinning

**Unexpected behaviour you saw**
 > I'm running systemd-networkd to configure interfaces on a machine that also has a BGP session that imports the full global internet routing table:
```
# ip r show table bgp | wc -l
864190
# ip -6 r show table bgp | wc -l
137951
```
This causes systemd-networkd to spin for a long time at 100%, and strace indicates that it's reading netlink routing table messages. I **think** this happens on startup, at least everything is fine if systemd-networkd starts up before the BGP daemon (as happens during boot), but if I restart systemd-networkd I get the spinning behaviour.

**Steps to reproduce the problem**
 > Load a large routing table into the kernel, then restart systemd-networkd.

**Comment by yuwata** [comment]
Please set `ManageForeignRoutes=no` in /etc/systemd/networkd.conf.

**Comment by tohojo** [comment]
Ah, didn't realise it was **removing** those routes, I thought it was just spinning on parsing them. My bad, thanks for the pointer!
