### ISSUE TITLE
RFE: enable control of cgroup attributes at runtime

### ISSUE THREAD

**Issue by pdmorrow** [systemd/systemd#20733]
**Is your feature request related to a problem? Please describe.**

We have a system where fast re(boots) are a requirement, thus I want to be able to give all available resources to the system.slice  during boot and shutdown. However after boot (after some arbitrary target is reached) I would like to ensure processes in the system.slice cgroup only run on a subset of available CPUs (to avoid interrupting another latency sensitive application in another slice). We can use the AllowedCPUs option to pin a cgroup to a cpuset, however this requires either of:

   * AllowedCPUs is set for the system slice during boot (this slows our boot down so isn't an option).
   * A runtime drop-in is created to change AllowedCPUs at runtime. This seems like a heavy weight solution and possibly difficult to manage by another user defined service.
   * We don't set AllowedCPUs for the system.slice, rather after boot we manually twiddle the cpuset.cpus file for the system.slice. This violates the principle of a "single writer" that systemd preaches, sadly however this is the solution I am currently using.

**Describe the solution you'd like**

A less heavy weight way (as opposed to runtime drop-in creation and a daemon-reload) of changing resource configuration of a service/slice/scope. These properties are currently dbus RO, if they could be made RW then this would be a lighter weight way to change configuration. I'd be happy to work on a patch for this.

**Describe alternatives you've considered**

Copy/paste from above:

   * AllowedCPUs is set for the system slice during boot (this slows our boot down so isn't an option).
   * A runtime drop-in is created to change AllowedCPUs at runtime. This seems like a heavy weight solution and possibly difficult to manage by another user defined service.
   * We don't set AllowedCPUs for the system.slice, rather after boot we manually twiddle the cpuset.cpus file for the system.slice. This violates the principle of a "single writer" that systemd preaches, sadly however this is the solution I am currently using.

**The systemd version you checked that didn't have the feature you are asking for**

v249.

**Comment by poettering** [comment]
There's already StartupCPUWeight= vs. CPUWeight=. Maybe add StartupAllowedCPUs= vs. AllowedCPUS=, too?

**Comment by pdmorrow** [comment]
That sounds good, I'll take a look at these option. I presume the switch happens after the default target is reached?

**Comment by pdmorrow** [comment]
Posted the PR, however I just realised this helps me for the boot phase but doesn't help me for shutdown. A solution would be to add ShutdownAllowedCPUs & ShutdownAllowedMemoryNodes, which maybe would default to the same thing as the Startup versions if not set?
