### ISSUE TITLE
"table" isn't rendered on freedesktop.org/software/systemd/man

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#20747]
The man page for `systemd-cryptenroll` [contains a table with "Well-known PCR Definitions"](https://github.com/systemd/systemd/blob/679de141122ca30388bba6d132f8c0dddcdddd15/man/systemd-cryptenroll.xml#L190-L269), but it isn't rendered rendered on the [freedesktop.org man page for `systemd-cryptenroll`](https://www.freedesktop.org/software/systemd/man/systemd-cryptenroll.html).

Debian's [man page service](https://manpages.debian.org/experimental/systemd/systemd-cryptenroll.1.en.html) and Arch Linux's [man page service](https://man.archlinux.org/man/systemd-cryptenroll.1) render it correctly tho.

**Comment by bluca** [comment]
It is rendered?

![Screenshot from 2021-09-15 13-02-41](https://user-images.githubusercontent.com/782193/133430313-f4bbfb63-6318-48eb-a05e-6e9a25fd7f94.png)

**Comment by klausenbusk** [comment]
> It is rendered?

Hmm, it must has been fixed recently then. Firefox was caching the page, so I assume in the last 24-48 hours.
