### ISSUE TITLE
systemd-resolvconf shouldn't fail on "-u" switch

### ISSUE THREAD

**Issue by notorand-it** [systemd/systemd#20748]
**systemd version the issue has been seen with**
 > 249.4

**Used distribution**
 > Archlinux (current)

**Linux kernel version used** (`uname -a`)

 > `Linux Feynman 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd-resolvconf -u should do nothing and return 0

**Unexpected behaviour you saw**
 > systemd-resolvconf -u does nothing and returns 1

**Steps to reproduce the problem**
 > systemd-resolvconf -u || echo FAILED

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
n/a
```
**Extra notes**
This behavior makes some software, like VPN clients using `resolvconf`, fail on setting up the obtained DNS server IP addresses.

At least a few of those "compatibility switches" (like -u) should not fail in terms of return code != 0.
Or simply make them rerturn 0 when invoked as `resolvconf` (as opposed to `systemd-resolvconf`)
Instead a warning message could be issued on `stderr`.

I am not sure whether an invocation **including** one of those switches fails even if all other switches are workable.

**Comment by poettering** [comment]
We actually ignore some parameters, such as `-m`, but `-u` executes some operation we really can't do anything reasonably for, hence we fail right now. Is `-u` really something we should totally ignore and make a NOP? 

Can you elaborate on your case, i.e. why your VPN software calls this, and why it would be safe to entirely ignore the invocation?

**Comment by notorand-it** [comment]
Unluckily I am not the owner of that VPN application (Pritunl, actually) so I cannot provide you with technical details.
What I can tell is that I presume it is trying to update the resolver configuration file (resolv.conf) by means of the `resolvconf`tool.
I "fixed" that issue by replacing the systemd-based tool with the one which is called `core/openresolv` under Arch Linux (https://roy.marples.name/projects/openresolv).

IMHO systemd's "compatibility" implementation should not break existing code.

This is why a would say a warning message ("Not implemented, see manual") should be OK when called as `resolvconf` while a return value other than `0` seems not appropriate. If it's doing nothing, it cannot fail.

On the other hand, a failure when called as native systemd module seems to me to be quite right.
