### ISSUE TITLE
RFC: Set power/persist for USB devices

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#20754]
The USB subsystem has a feature that permits USB devices that can retain their state to remain available after a suspend/resume cycle, even if they were fully powered off in between. If `power/persist` is disabled, the USB device will behave as if it was unplugged over suspend.

This is great for e.g. USB drivers, and it is completely fine for stateless devices. However, it can create problems for state-full devices that will not retain their state through a power loss. An example of this happening is fingerprint readers.

fprintd needs to turn off `power/persist` for USB fingerprint readers to properly handle suspend/resume in cases where the HW does not fully support it. i.e. we want the device to actually disappear if it couldn't be suspended properly. Otherwise we would try to use it after resume, but things fall apart as the device is in the wrong state.

So, my question here is whether we should:
 1. Just continue setting `power/persist` at runtime in fprintd (we also set `power/wakeup` when wakeup from the device is desired)
 1. Ship another hwdb in libfprint
 2. Ship another hwdb in systemd
 3. Integrate this into the existing autosuspend hwdb. i.e. add `ID_PERSIST` or so and handle it that way.

**Comment by poettering** [comment]
this sounds awfully close to to the autosuspend stuff. Maybe close enough even t just be added to the existing autosuspend hwdb files?

**Comment by benzea** [comment]
Yup, so option 4.
