### ISSUE TITLE
Bootloader problem.

### ISSUE THREAD

**Issue by Bundy01** [systemd/systemd#20757]
**systemd version the issue has been seen with**
 > systemd 249.4-1

**Used distribution**
 >Archlinux
**Linux kernel version used** (`uname -a`)

 > `Linux desktop 5.14.3-arch1-1`

**CPU architecture issue was seen on**
 > Intel i5-10210U (8) @ 4.200GHz
**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
Hello,

I have a strange problem with systemd-boot on Arch. It became slow at startup after an installation on my new PC.
With the old one, the bootloader started at about 0.1s with a mSATA ssd. Now it starts after 3s with the samsung 970 evo plus nvme.

```
Startup finished in 3.105s (firmware) + 3.201s (loader) + 754ms (kernel) + 488ms (initrd) + 2.918s (userspace) = 10.468s 
graphical.target reached after 2.705s in userspace
```
I have tried all the options that the BIOS offers me without success. Do you have any idea of the problem?

Regards.

**Comment by medhefgo** [comment]
It's slower compared of which version of sd-boot? Have you tried latest git? It would be great if you could provide a bisect to pinpoint the culprit commit...

**Comment by Bundy01** [comment]
I'm not sure if the problem comes from this version because on the old PC I still have, I did the last update and it starts normally :/

**Comment by poettering** [comment]
This is not actionable to us, we do not possess your hw, nor do we know what software you are running, how you compiled it and such.

Thus, if you want anything to happen about this issue, then please at the very least bisect things, so that we know what commit made the change.

Otherwise I fear the only thing we can do is close the issue, because not actionable.

**Comment by Bundy01** [comment]
Sorry for the late reply.
The assembler of my laptop has flashed the uefi to embed his logo. I think it's this one that slows down the loader.

I close this issue.
