### ISSUE TITLE
Chinese  translation is imcomplete (Probably broken)

### ISSUE THREAD

**Issue by linlinger** [systemd/systemd#20760]
**systemd version the issue has been seen with**
 > 249.4

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > 5.14.3-arch1-1

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 >Shows full Chinese translation When a systemd polkit action triggered 

**Unexpected behaviour you saw**
 > In some cases the translation is not working

**Steps to reproduce the problem**
 > Create a user that can't do polkit actions passwordlessly. 
    Set system locale to zh_CN.UTF-8
    logout and login again
    Then open a terminal  type a command like timedatectl set-ntp 0 
    Finally you will see it asks you to input your password to cvontinue, but it comes with English text not Chinese

**Additional program output to the terminal or log subsystem illustrating the issue**
![图片](https://user-images.githubusercontent.com/32541118/133547994-552899d5-921a-430c-8bf2-a14792fbcf73.png)
![图片](https://user-images.githubusercontent.com/32541118/133548034-63d54693-30b7-4a06-808e-c553d1491d50.png)

```text
…
```

**Comment by yuwata** [comment]
Please submit fixes as a PR, or through weblate.

**Comment by linlinger** [comment]
Now I'm still looking for a fix for this. BTW what is weblate ?

**Comment by linlinger** [comment]
I also tried to do so using other languages like traditional Chinese and Korean. The polkit action shows all English. It seems that no translations were applied 
![图片](https://user-images.githubusercontent.com/32541118/133577680-46e6cf9f-2493-4b9b-b144-a76c288c7e11.png)
![图片](https://user-images.githubusercontent.com/32541118/133577830-8e5473df-9af5-4491-b337-1a2627202ba5.png)

**Comment by yuwata** [comment]
> Now I'm still looking for a fix for this. BTW what is weblate ?

https://translate.fedoraproject.org/projects/systemd/master/

**Comment by yuwata** [comment]
If Korean translation does not work, then the problem may not be in .po files, as all messages are already translated to Korean.

**Comment by yuwata** [comment]
Hm, zh_CN.po is also perfect. Strange.

**Comment by poettering** [comment]
Let's close this here. Please submit your translation via weblate.
