### ISSUE TITLE
Log file rotation

### ISSUE THREAD

**Issue by Arjun-DR** [systemd/systemd#20762]
Hi Team,

We are using systemd version v230. We have lot of services (around 150+) out of which 80+ services are long run services. They produce logs continuously. Currently for every 10 seconds, we run journalctl for each service and redirect the logs in another file. This results in more CPU occupancy for every 10 seconds as there are lot of IO operations involved here.

I came to know that systemd version v236 enables direct connection of the process' stdin/stdout/stderr to the file thus allowing the logs to be written in the log file by service unit itself. 

I have some queries. 
1. Do we have log file rotation support? Say, we need to rotate the log file at reaching 1 MB size for n numbers.
2. Is it possible to set the maximum size of the log file? Say, we set max size as 4 MB and upon reaching the limit, the older logs can be deleted on writing new lines and keep the same file unrotated. 

Please help. 
Thanks,
Arjun

**Comment by boucman** [comment]
why do you dump the journals in another file ? what are you trying to achieve ?

And yes, journald handles rotation and file deletion, please read the journald.conf man page

**Comment by Arjun-DR** [comment]
Because we need to have the logs in file. 

For example, we have a service A.
The logs are available in journal of A. 

We need to redirect that to a log file. So we run "journalctl -u A" and filter the output and redirect that to the log file. Since we are using systemd v230, we don't have the facility to directly write on the log file.

In systemd v236+. we can directly write to the log file from the service itself. I am just checking for the possibility of rotation of that mentioned log file in the service. Is that available?

**Comment by bluca** [comment]
No, if you create custom log files, it's up to you to manage them. If you want automated management, use the journal as defined in https://www.freedesktop.org/software/systemd/man/journald.conf.html
