### ISSUE TITLE
systemd-userdbd.service: start operation timed out. Terminating.

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#20766]
**systemd version the issue has been seen with**
 > 248

systemd-userdbd.service start failed because timeout when loggining , and login failed。After logging in several times, it succeeded.
We can't reproduce the problem. I hope the community can give some suggestions. Thank you

log ：
11:08:34 localhost.localdomain systemd[1]: Starting User Database Manager...
11:09:28 localhost.localdomain systemd[1]: Starting Cleanup of Temporary Directories...
11:09:28 localhost.localdomain systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
11:09:28 localhost.localdomain systemd[1]: Finished Cleanup of Temporary Directories.
11:10:05 localhost.localdomain systemd[1]: systemd-userdbd.service: start operation timed out. Terminating.
11:10:05 localhost.localdomain systemd[1]: systemd-userdbd.service: Failed with result 'timeout'.
11:10:05 localhost.localdomain systemd[1]: Failed to start User Database Manager.
11:10:05 localhost.localdomain systemd[1]: Starting User Database Manager...
11:11:35 localhost.localdomain systemd[1]: systemd-userdbd.service: start operation timed out. Terminating.
11:11:35 localhost.localdomain systemd[1]: systemd-userdbd.service: Failed with result 'timeout'.

**Comment by poettering** [comment]
*[Canned reply follows]*

When submitting a GitHub issue, please fill in the submission form you find in the issue creation page, i.e. provide the requested details, such as distribution and systemd versions. We ask you these details to keep frustration at a minimum, both for us, and for you. If you don't provide this information it makes things needlessly difficult to help you.

Also, please keep in mind: this is a bug and feature request tracker only. If you have a support question, i.e. wonder how to use a feature, or can't figure out how to do something best, please use a different forum, such as the systemd mailing list. Also, do not file bug reports unless you can reproduce the issue with one of the two most recently released *upstream* version of systemd. For everything older, please contact your downstream distribution instead.

Thank you for understanding!

**Comment by poettering** [comment]
Also, please provide a backtrace of the userdb process when this happens, i.e. "pstack" on the userdb main PID, then this happens.

**Comment by poettering** [comment]
Closing due to lack of response.
