### ISSUE TITLE
systemd-sleep: The hibernation fails with several swap partitions.

### ISSUE THREAD

**Issue by PavelSann** [systemd/systemd#20761]
**systemd version the issue has been seen with**
 >systemd 241

**Used distribution**
 >Debian 10 (buster)

**Linux kernel version used** (`uname -a`)
 > `Linux DELL-PC 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Right choosing location of hibernate.

**Unexpected behaviour you saw**
 > Sometimes hibernation  is failing

**Steps to reproduce the problem**
 >Create two partition of swap.
The first partition is small and have high priority(sda1).
The second partition is big and have low priority(sdb1).
```
swapoff -a
swapon /dev/sda1 --priority 100
swapon /dev/sdb1 --priority 10
swapon
NAME      TYPE       SIZE USED PRIO
/dev/sda1 partition    1G   0B  100
/dev/sdb1 partition   16G   0B   10
systemctl hibernate
Failed to hibernate system via logind: Not enough swap space for hibernation
```
But if change order, will have different happen:
```
swapoff -a
swapon /dev/sdb1 --priority 10
swapon /dev/sda1 --priority 100
swapon
NAME      TYPE       SIZE USED PRIO
/dev/sdb1 partition   16G   0B   10
/dev/sda1 partition    1G   0B  100
systemctl hibernate

```

**Description**
The unsteady behavior on choices the partition of the hibernate in the function "find_hibernate_location".

If there are several partitions of the swap in the system, and they have  different sizes and prioritys, 
the behavior of the function "find_hibernate_location" depend of an order of partition in the list "/proc/swaps".

For example, I have two partition on different disks. 
The small fast partition on the SSD disk(sda) and the big partition on the slow HDD disk(sdb).
_I want to use the fast partition to swapping and the slow partition use to hibernating._
> swapon
NAME      TYPE       SIZE USED PRIO
/dev/sdb1 partition 16,4G   0B   10
/dev/sda3 partition    4G 3,5M  100

> cat /etc/fstab
#sdb slow hdd
UUID=8ab0f291-f2aa-4542-880d-0d1d1a61ed8e none  swap    sw,pri=10                               0       0
#sda fast ssd
UUID=806ee613-d89c-40b4-a24d-40c77b4c369f none  swap    defaults,discard,sw,pri=100   0       0

If the partition "sdb1" is first in the list "/proc/swaps", hibernating is complete.
But, if the partition "sda3" is first in the list, I have error, because  partition "sda3" is small, but have high priority. 

It is happen because the function prefer a partition with highest priority and doesn't check a partition size with lower priority.

**Comment by PavelSann** [comment]
https://github.com/systemd/systemd/blob/2d253d7206e23f313520713000d3e3408e03a384/src/shared/sleep-config.c#L394

**Comment by PavelSann** [comment]
The feasible solution: skip partitions with not enough size to hibernation.
https://github.com/PavelSann/systemd/commit/d2af1a20fe897d65da4db0af5967133390d711a1

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
(I mean, for starters, 88bc86fcf895da0d51ddaf93d17b4280f4e60d74 has been merged since ancient 241)

**Comment by PavelSann** [comment]
I am sorry, thank you.
