### ISSUE TITLE
Failure to distinguish negative DNS response from error with resolved and glibc NSS

### ISSUE THREAD

**Issue by lorenz** [systemd/systemd#20786]
**systemd version the issue has been seen with**
247

**Used distribution**
custom

**Linux kernel version used** (`uname -a`)
Linux 5.10.63 with custom patches

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
System is setup with resolved, glibc and nsswitch using nss-resolve.

Calling getaddrinfo() without an active network connection (and therefore no DNS server in resolved) returns EAI_AGAIN. This would be consistent with the behavior specified in https://sourceware.org/glibc/wiki/NameResolver.

**Unexpected behaviour you saw**
Calling getaddrinfo() without an active network connection returns EAI_NONAME.

**Further information**
This is using the "standard" nsswitch setup which Fedora & co also use:
```
hosts:       files usrfiles resolve [!UNAVAIL=return] myhostname dns
```
nss-resolve asks resolved for the name:
```
{
  "method": "io.systemd.Resolve.ResolveHostname",
  "parameters": { "name": "example.com", "flags": 0 }
}
```
to which resolved correctly responds with
```json
{
  "error": "io.systemd.Resolve.NoNameServers",
  "parameters": {}
}
```
But this error is not converted into a transient error (i.e. NSS_STATUS_TRYAGAIN), but instead into NSS_STATUS_NOTFOUND. This behavior is documented at https://github.com/systemd/systemd/blob/main/src/nss-resolve/nss-resolve.c#L235.

Wireguard's userspace helper [treats getaddrinfo errors as documented](https://github.com/WireGuard/wireguard-tools/blob/master/src/config.c#L245) and never retries when receiving EAI_NONAME as that [is considered a permanent error by glibc](https://sourceware.org/glibc/wiki/NameResolver).

I'm not 100% sure who's wrong here, nss-resolve, glibc NSS (or its config) or WireGuard. WireGuard is trying to distinguish an explicit negative DNS response (i.e. an NXDOMAIN from the authoritative DNS server or a cache) from a resolution error, which makes sense considering they are different from a technical perspective.

**Comment by poettering** [comment]
I think it's our bug. Fix in #21470
