### ISSUE TITLE
RFE: add generic systemd-growfs@.service unit file template

### ISSUE THREAD

**Issue by robimarko** [systemd/systemd#20788]
**Is your feature request related to a problem? Please describe.**
It looks like systemd-growfs can be only triggered when fstab is used.
Systems that I want to use growfs on don't use fstab as there is no need
for it.

**Describe the solution you'd like**
I would like growfs to be triggerable on systems without fstab, like repart which works
fine on systems that don't use fstab.

**Describe alternatives you've considered**
Currently, I need to run a separate service that will do filesystem resizing after repart has
resized the partition automatically thanks to Discoverabla partitions specification.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by poettering** [comment]
the fstab and the gpt-auto gnerators synthesize service units for the growfs stuff, as needed. It's parameterized by multiple variables, hence it's nice to generate explicit units for this.

That said, we could probably ship a regular template unit file for this too, to make it easy to use outside of these two generators.

i.e. something like a file `systemd-growfs@.service`:

```
[Unit]
Description=Grow File System on %f
Documentation=man:systemd-growfs@.service(8)
DefaultDependencies=no
BindsTo=%i.mount
After=%i.mount
Conflicts=shutdown.target
Before=shutdown.target

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/systemd-growfs %f
TimeoutSec=0
```

Happy to take a patch that adds this to the files we install by default.

(In the meantime you can just define this unit file locally, if you like)
