### ISSUE TITLE
type=notify without NOTIFY_SOCKET

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#20796]
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type= says for

> Behavior of `notify` is similar to `exec`; however, it is expected that the service sends a notification message via sd_notify(3) or an equivalent call when it has finished starting up. systemd will proceed with starting follow-up units after this notification message has been sent. If this option is used, `NotifyAccess=` (see below) should be set to open access to the notification socket provided by systemd. If `NotifyAccess=` is missing or set to `none`, it will be forcibly set to main.

My understanding is that `type=notify` can only be used when the environment variable `NOTIFY_SOCKET` is set.  Which means, that if the variable is not set, the service is never considered started.

Please extend the documentation for type=notify to state, that it can only function, when the environment variable NOTIFY_SOCKET is set and the service silently does completes the starting, if the variable is missing.

**Comment by poettering** [comment]
We set this variable automatically. Unless you manually unset it this should not require any work. But why would you unset it?

I don't follow? I presume there's some misunderstanding here?

**Comment by dilyanpalauzov** [comment]
Where is documented, to which value `NOTIFY_SOCKET` is set?  If the .unit files sets the variable to a different value, will the new value work-as-expected-out-of-the-box.

I want to start a process from a systemd.unit file.  Once the process starts, it does chroot(2).  In the chrooted environment NOTIFY_SOCKET does not exits, as far as I have tried.  And this needs further adjustments.

**Comment by JamesXNelson** [comment]
for posterity, the linked documentation being referred to is available at https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html

Also, I looked at all the references to `NOTIFY_SOCKET` in those docs, and the explanation of where the variable comes from appears near the end, while it is referenced at length before then.  I could see how someone unfamiliar w/ how this works may have a difficult time figuring this out from the `sd_notify` docs (unless there is somewhere else I should be looking?)
