### ISSUE TITLE
What are the use cases of journalctl --flush ?

### ISSUE THREAD

**Issue by krave1986** [systemd/systemd#20794]
I have already read man page of journalctl and made some experiments with the command.
All the efforts made me more confused. So I would like to beg some help here.

My procedures:

1. create a .conf file for systemd-jounald.service and put in the following lines:
```
[Journal]
Storage=volatile
```
2. restart systemd-journald.service
```
sudo systemctl restart systemd-journald
```
3. check the status of journald and ensure it is writing log into memory
```
systemctl status systemd-journald
```
The result is like:
> Runtime Journal (/run/log/journal/...)
which informed me that .conf file worked well
4. comment out the Storage option
```
[Journal]
#Storage=volatile
```
5. restart journald
```
sudo systemctl restart systemd-journald
```
6. check status again and you will see that flush already been done
```
systemctl status systemd-journald
```
with feedback included
>  Time spent on flushing to /var/log/journal/machineID/ is 282.991ms for 1483 entries.

which means flush had been done.

Now that the operation of flush can be done automatically when you switch from `Storage=volatile` to `#Storage=volatile`, why do we still need `journalctl --flush`?

I believe there are some reasons for the existence of this switch for journalctl.

**Comment by vcaputo** [comment]
This isn't a support forum, such questions are better asked on the systemd-devel mailing list or IRC.

**Comment by krave1986** [comment]
@vcaputo Thanks. I have raised the question from mailling list.
