### ISSUE TITLE
RFE: automatically send boot messages to multiple console=

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#2079]
Hey.

(This originates from: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806793)

system is already so nice to detect when a serial console is configured and starts a getty accordingly.
What however doesn't work (out of the box) yet, is the following:

When one configures a serial console, e.g. like:
console=ttyS1,115200n8
as for remote management, one mostly wants to have everything on VGA in addition, i.e. one does:
console=ttyS1,115200n8 console=tty0
where the order of the console parameters determines what will be used for /dev/console.

When doing that, _kernel_ messages are correctly printed to both, serial console and VGA console (if that is tty0, which it typically is).
However, any init messages, like the green OKs from started services, fsck messages and so on, are just printed to the later console (i guess journald simply takes /dev/console).

Michael Biebl was so friendly to point me to journald's ForwardToConsole= but it doesn't seem to be exactly what I want as it would forward everything that gets to the journal to the console - I however want just the "boot messages" (that are not kernel messages).

Also, ideally that should again work out of the box, i.e. when someone has configured several console= it should be printed on all of them

Cheers

**Comment by poettering** [comment]
Hmm, writing to /dev/console should actually go to all consoles already. i.e. that's how /dev/console is defined really. (note that when reading on it only the first console is considered though). Are you saying this is not what you are seeing?

**Comment by calestyo** [comment]
Well it's as I've described above,... kernel messages appear on all devices given via console=, while stuff e.g. printed by systemd (I've mentioned the start/stop messages with the green OK as example) only goes to the device given for the first /dev/console.
That's what I see.

> writing to /dev/console should actually go to all consoles already

Well, Documentation/serial-console.txt says:

> You can specify multiple console= options on the kernel command line.
> Output will appear on all of them. The last device will be used when
> you open /dev/console. So, for example:
> 
> ```
>     console=ttyS1,9600 console=tty0
> ```
> 
> defines that opening /dev/console will get you the current foreground
> virtual console, and kernel messages will appear on both the VGA
> console and the 2nd serial port (ttyS1 or COM2) at 9600 baud.

I'm not sure whether that implies that anything written to it is expected to go to all devices specified in console= kernel params.

**Comment by poettering** [comment]
This works these days, see #3403

**Comment by jamespharvey20** [comment]
Can this be re-opened?

This only works if Plymouth is installed, which somehow appears to change the behavior of `/dev/console` going to all consoles.  Without Plymouth, `/dev/console` only goes to the preferred console (the one with the `C` flag in `/proc/consoles`.)

**Comment by romainreignier** [comment]
Because the `plymouth` hack only seems to work on Fedora, could someone explain how to activate it on a Debian-based distro like Ubuntu 18.04?
Thanks

**Comment by calestyo** [comment]
@poettering Lennart, could you please re-open this.

As mentioned previously, this still doesn't work as of at least systemd 247.3, just as I've described originally,... whichever `console=` comes last is the only one where systemd would print to - while the kernel itself prints correctly to both.

It may work with plymouth (haven't tested), but I don't think this is someone people would typically install in a server environment - which is however rather the major place where having multiple `console=` is relevant.

Cheers,
Chris.
