### ISSUE TITLE
systemd.directives and .index broken

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#20795]
It appears 
https://www.freedesktop.org/software/systemd/man/index.html
and
https://www.freedesktop.org/software/systemd/man/systemd.directives.html
are not properly generated atm

**Comment by mbiebl** [comment]
I'm attaching a screenshot to document the issue.
![Bildschirmfoto vom 2021-09-21 16-56-00](https://user-images.githubusercontent.com/3609611/134194887-2651b5d5-bea2-4417-b029-6927fdbe74e2.png)
![Bildschirmfoto vom 2021-09-21 16-55-26](https://user-images.githubusercontent.com/3609611/134194920-2e89f6f6-9bae-4d8e-9e7b-0d7dd9b5bd87.png)

**Comment by keszybz** [comment]
Should be fine now.
