### ISSUE TITLE
DNS over TLS: following connection to a wifi AP, internet is not available for ~30s

### ISSUE THREAD

**Issue by cmurf** [systemd/systemd#20801]
**systemd version the issue has been seen with**
 > systemd-249.4-1.fc35.x86_64

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)

 > `5.14.6-300.fc35.x86_64`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > internet access within a couple seconds of AP connection

**Unexpected behaviour you saw**
 > 30-45s delay before internet is routable following AP connection

**Steps to reproduce the problem**
 > Boot or change AP's (all AP's affected are Xfinity provided hardware and service)

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
[bug2006393-journalresolveddebug.txt](https://github.com/systemd/systemd/files/7205010/bug2006393-journalresolveddebug.txt)

Downstream bug
https://bugzilla.redhat.com/show_bug.cgi?id=2006393

**Comment by cmurf** [comment]
Creating `/etc/systemd/resolved.conf.d/50-dot.conf` with the following contents, and restarting resolved, works around the problem:

```
[Resolve]
DNSOverTLS=no
```

**Comment by poettering** [comment]
Hmm, the server you picked doesn't reply to our DNS-over-TLS requests at all, so things have to timeout. Not sure what we can do about this to speed this up. i mean falling back immediately or doing things in parallel in classic UDP mode defeats the point of DNS-over-TLS a bit, since we'd send requests in plaintext in that case..

**Comment by mcatanzaro** [comment]
> Hmm, the server you picked doesn't reply to our DNS-over-TLS requests at all, so things have to timeout. Not sure what we can do about this to speed this up. i mean falling back immediately or doing things in parallel in classic UDP mode defeats the point of DNS-over-TLS a bit, since we'd send requests in plaintext in that case..

Hm, but we're using `DNSOverTLS=opportunistic`, so why not just fall back immediately? This is best-effort protection against passive adversaries only, not protection against active attackers.

With `DNSOverTLS=yes` then it should obviously actually be secure and not fall back.

**Comment by poettering** [comment]
hmm, "immediately"? what does that even mean?

But yeah, I guess we could lower the timeout here in opportunistic mode to 3s. So the initial lookup will still be a bit slower, but not 30s.
