### ISSUE TITLE
DHCPv6 too strict when the response is missing IAID for some sections

### ISSUE THREAD

**Issue by hakman** [systemd/systemd#20803]
**systemd version the issue has been seen with**
 > systemd 248 (248.3-1ubuntu3)

**Used distribution**
 > Ubuntu 21.10 (Impish Indri)

**Linux kernel version used** (`uname -a`)
 > `Linux ip-172-31-211-65 5.11.0-1015-aws #16+21.10.1-Ubuntu SMP Mon Jul 26 13:47:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > IPv6 address acquired

**Unexpected behaviour you saw**
 > IPv6 address was not acquired due to issues parsing the DHCPv6 Advertise message:
```
systemd-networkd[19265]: DHCPv6 CLIENT: Sent SOLICIT
systemd-networkd[19265]: DHCPv6 CLIENT: Next retransmission in 29s
systemd-networkd[19265]: DHCPv6 CLIENT: ADVERTISE has wrong IAID for IA PD
systemd-networkd[19265]: DHCPv6 CLIENT: Recv ADVERTISE
```
> The DHCPv6 message is expected to have the same IAID in all the sections:
https://github.com/systemd/systemd/blob/8d71f2b3a6c9ef26a3a39fcaa4281776e9420976/src/libsystemd-network/sd-dhcp6-client.c#L1247-L1251

**Steps to reproduce the problem**
> To reproduce this problem, an AWS setup with IPv6 enabled is required.
> Create a VPC and assign an IPv6 CIDR. Assign IPv6 CIDR to a subnet and start an instance with an IPv6 address assigned.
> Once the instance is up and running, assign and IPv6 Prefix to the network interface.
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html
> The instance will fail or acquire or renew the lease for the IPv6 address.
>
> As you can see below, the main issue is the missing IAID for the IAPD section.
> I could not find any reference in the RFC about the possibility of not setting the IAID in all sections of the message, so seems to be something that AWS should fix at some point.
> That being said, the parsing of the message is also too strict. The sections with valid IAID, like the IANA should be processed and the DHCPv6 lease acquired or renewed.

**Additional program output to the terminal or log subsystem illustrating the issue**

> The DHCPv6 Advertise message as parsed with tshark:
```
> sudo tshark -V -i ens5 -d "udp.port==546:2,dhcpv6" -f "udp port 546 or udp port 547"

DHCPv6
    Message type: Advertise (2)
    Transaction ID: 0x88b74a
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115b2000709a2178c4
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5b2000709a2178c4
    Server Identifier
        Option: Server Identifier (2)
        Length: 10
        DUID: 000300010265476d3310
        DUID Type: link-layer address (3)
        Hardware type: Ethernet (1)
        Link-layer address: 02:65:47:6d:33:10
    Preference
        Option: Preference (7)
        Length: 1
        Pref-value: 255
    Identity Association for Non-temporary Address
        Option: Identity Association for Non-temporary Address (3)
        Length: 40
        IAID: ed10bdb8
        T1: 70
        T2: 112
        IA Address
            Option: IA Address (5)
            Length: 24
            IPv6 address: 2a05:d014:aa7:911:dfeb:bd5a:5115:7bef
            Preferred lifetime: 140
            Valid lifetime: 450
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 00000000
        T1: 70
        T2: 112
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 140
            Valid lifetime: 450
            Prefix length: 80
            Prefix address: 2a05:d014:aa7:911:4393::
```

**Comment by yuwata** [comment]
According to [RFC8415](https://datatracker.ietf.org/doc/html/rfc8415), IAs which do not match should be ignored, IIUC.

So, in this case, we should just ignore the IA_PD, instead of rejecting the whole message. I will prep a patch.

**Comment by hakman** [comment]
This sounds good. Thanks @yuwata.

**Comment by yuwata** [comment]
@hakman If possible, could you test #20807?

**Comment by hakman** [comment]
Thanks @yuwata. Will try to test it this week. The changes seem pretty easy to backport to the Ubuntu bundled version.

**Comment by hakman** [comment]
@yuwata I can confirm that the fix is working as expected in my test environment. Thanks again for the quick fix! :)
```
systemd-networkd[6701]: ens5: DHCPv6 address 2a05:d014:aa7:911:230e:bddc:354e:2892/128 (valid for 7min 30s, preferred for 2min 20s)
systemd-networkd[6701]: ens5: Updating address: 2a05:d014:aa7:911:230e:bddc:354e:2892/128 (valid for 7min 30s, preferred for 2min 20s)
systemd-networkd[6701]: ens5: Remembering updated address: 2a05:d014:aa7:911:230e:bddc:354e:2892/128 (valid for 7min 30s, preferred for 2min 20s)
```

**Comment by yuwata** [comment]
@hakman Thank you for testing the patch!
