### ISSUE TITLE
Documentation on cgroup delegation is misleading about scope usage

### ISSUE THREAD

**Issue by mardy** [systemd/systemd#20816]
The [documentation on cgroup delegation](https://github.com/systemd/systemd/blob/main/docs/CGROUP_DELEGATION.md) offers three possible solutions, the third one being this:

> The *i-like-continents* option. In this option you'd leave your manager daemon where it is, and would not turn on delegation on its unit. However, as first thing you register a new scope unit with systemd, and that scope unit would have `Delegate=` turned on, and then you place all your containers underneath it. From systemd's PoV there'd be two units: your manager service and the big scope that contains all your containers in one.

The way I understand this advice:
1. when your manager daemon starts, have it create a new scope unit ("*as first thing you register a new scope unit with systemd*")
2. this unit can initially be empty ("*you'd leave your manager daemon where it is*")
3. you populate this unit when you create your containers ("*then you place all your containers underneath it*")

However, this does not work: calling `StartTransientUnit` without a `PIDs` property leads to systemd complaining: "Scope has no PIDs. Refusing.". On systemd 245 the error is different (it's about not finding the unit), but it also goes away if PIDs are provided.

The observed behaviour seems consistent with a [comment from Lennart](https://github.com/systemd/systemd/issues/8645#issuecomment-378339071) in which he confirms that a scope cannot be created without any processes in it.

It would be nice if the documentation explained that a PID must be put in the scope, and give some recommendation on which one it should be (a process sleeping forever?).

**Comment by bluca** [comment]
The idea is that you create the scope on first use, no?

**Comment by mardy** [comment]
> The idea is that you create the scope on first use, no?

Maybe, but this is not what I understand by reading that paragraph. :-)

**Comment by bluca** [comment]
Fair enough - can you send a PR to reword it? The doc is at https://github.com/systemd/systemd/blob/main/docs/CGROUP_DELEGATION.md

**Comment by mardy** [comment]
Please see the linked PR and advise in case I got it all wrong :-)
