### ISSUE TITLE
feature: add service/create systemd file from command line

### ISSUE THREAD

**Issue by blinkinglight** [systemd/systemd#20815]
**Is your feature request related to a problem? Please describe.**
each time i want to add lets say "golang" service to system i need to google where and what to put

**Describe the solution you'd like**
would be nice to have command line tool for that for example: systemdaddservice /peth/to/bin or maybe flag for some questions 

**The systemd version you checked that didn't have the feature you are asking for**
systemd 245 (245.4-4ubuntu3.11)

**Comment by yuwata** [comment]
There are already two methods to add service from command line.
- `systemctl edit`
- `systemd-run`

Are they not sufficient for you? Could you elaborate more?

**Comment by blinkinglight** [comment]
"Run 'systemctl edit --force --full test.service' to create a new unit. "

ok found this, so maybe then something like --use-common-template because it creates empty file. what i want is something like this
```
[Unit]
Description = making network connection up
After = network.target

[Service]
ExecStart = /root/scripts/cleanup

[Install]
WantedBy = multi-user.target
```
by default when i starting edit file, or maybe more options to get basic file

**Comment by yuwata** [comment]
Hm, each unit type has so many options, and I do not think we can provide reasonable template...

**Comment by blinkinglight** [comment]
> Hm, each unit type has so many options, and I do not think we can provide reasonable template...

yes, i understand that. but for basic stuff to start with which is usually enough - its possible. and yes, if i need more i can read docs and add aditional stuff for it.

**Comment by blinkinglight** [comment]
another idea would be - --guide-me flag which asks what you want "which type of service?" -> 1) , 2) , 3) and you select 1 so it adds "all options in group" needed for that service. and maybe "do you need restart / start delay" - yes/no so if yes it adds several options from that group etc.
