### ISSUE TITLE
systemctl start does not respect services start order specified in .service

### ISSUE THREAD

**Issue by manusrn** [systemd/systemd#20811]
**systemd version the issue has been seen with**
 > 219

**Used distribution**
> CentOS Linux release 7.9.2009 (Core)

**Linux kernel version used** (`uname -a`)

 > `Linux 6bc41b11fbb5 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Service A set to start before service B in .services file
A.service : 
[Unit]
Description= service A
Before=B.service
[Service]
Type=notify

>B.service
[Unit]
Description= service B

>systemctl enable A.service B.service
systemctl start A.service B.service
A starts, A sleep 5s (in main.cpp) , thensend notification (call sd_notify), and then B starts

**Unexpected behaviour you saw**
 > A and B start at the same time without waiting
If the vm is rebooted, systemd starts A and B (because of the previous systemctl enable) and in that case A starts, wait 5s, send notification and then B starts. If both services are manually stopped and started (systemctl start A.service B.service , both in the same cmd) A and B start at the same time without waiting for the notification from A.

After and Before are respected when using systemctl start A.service B.service if there is Requires=A.service in B.service Unit.

**Steps to reproduce the problem**
 > Set the .services files
systemctl enable A.service B.service
systemctl start A.service B.service 

> The documentation specify that After and Before can be used without requires : 
_Before=, After=
These two settings expect a space-separated list of unit names. They may be specified more than once, in which case dependencies for all listed names are created.
Those two settings configure ordering dependencies between units. If unit foo.service contains the setting Before=bar.service and both units are being started, bar.service's start-up is delayed until foo.service has finished starting up. After= is the inverse of Before=, i.e. while Before= ensures that the configured unit is started before the listed unit begins starting up, After= ensures the opposite, that the listed unit is fully started up before the configured unit is started.
When two units with an ordering dependency between them are shut down, the inverse of the start-up order is applied. I.e. if a unit is configured with After= on another unit, the former is stopped before the latter if both are shut down. Given two units with any ordering dependency between them, if one unit is shut down and the other is started up, the shutdown is ordered before the start-up. It doesn't matter if the ordering dependency is After= or Before=, in this case. It also doesn't matter which of the two is shut down, as long as one is shut down and the other is started up; the shutdown is ordered before the start-up in all cases. If two units have no ordering dependencies between them, they are shut down or started up simultaneously, and no ordering takes place. It depends on the unit type when precisely a unit has finished starting up. Most importantly, for service units start-up is considered completed for the purpose of Before=/After= when all its configured start-up commands have been invoked and they either failed or reported start-up success. Note that this does includes ExecStartPost= (or ExecStopPost= for the shutdown case).
Note that those settings are independent of and orthogonal to the requirement dependencies as configured by Requires=, Wants=, Requisite=, or BindsTo=. It is a common pattern to include a unit name in both the After= and Wants= options, in which case the unit listed will be started before the unit that is configured with these options._

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by mrc0mmand** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

In this case, please use CentOS bug tracker, as systemd 219 is quite ancient.
