### ISSUE TITLE
libsystemd-network: inappropriate assertion in ipv4acd_on_packet() --> crash on incoming ARP packet

### ISSUE THREAD

**Issue by ceggers-arri** [systemd/systemd#20825]
**Note** 
This bug in https://github.com/systemd/systemd/blob/main/src/libsystemd-network/sd-ipv4acd.c#L412 has been identified in NetworkManager. NetworkManager uses libsystemd-network and regularly fetches the latest sources from systemd. The original bug report (and technical details) are here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/807

**systemd version the issue has been seen with**
 > 09/2015 .. latest GIT

**Used distribution**
 > NetworkManager on Yocto dunfell

**Linux kernel version used** (`uname -a`)

 > `5.10-rt <latest>`

**CPU architecture issue was seen on**
 > ARM Cortex A7

**Expected behaviour you didn't see**
 > - NetworkManager always survives IPv4LL address negotiation
 > - A software must not assert() due to incoming data which arrives at inappropriate states.

**Unexpected behaviour you saw**
 > NetworkManger dies on an assertion:

**Steps to reproduce the problem**
 > 1. Switch to IP4LL address mode and determine negotiated IP address
 > 2. Switch to manual mode
 > 3. Perform ARP flooding: `nping --arp --count 1000 --delay 100ms <negotiated IP address>`
 > 4. Switch back to IPv4LL
 > 5. Repeat steps 2 to 4 until NetworkManager aborts on the assertion above.
**Additional program output to the terminal or log subsystem illustrating the issue**

```
NetworkManager[253]: <error> [1629105229.9665] libsystemd: Code should not be reached 'Invalid state.' at ../NetworkManager-1.22.10/src/systemd/src/libsystemd-network/sd-ipv4acd.c:394, function ipv4acd_on_packet(). Aborting.
```
**Systemd commit which introduced the bug**
https://github.com/systemd/systemd/commit/25d6213b4331e9cbf355f4e851fc5b4ee2ae4c0f#diff-40da7106630f743d59d4741a7faec68404ae8dd136e36b4765f258452f67696dR379

**Proposed solution**
Silently discard ARP messages in the `default:` case of the state machine:
```
s/assert_not_reached()/break/
```

**Comment by yuwata** [comment]
Hi @ceggers-arri. Could you test #20826?

**Comment by yuwata** [comment]
@ceggers-arri The PR is already merged. If it does not fix this issue, then please request to reopen this. Thank you.
