### ISSUE TITLE
Option to add necessary Prefix to logs

### ISSUE THREAD

**Issue by Arjun-DR** [systemd/systemd#20829]
**Is your feature request related to a problem? Please describe.**
Yes, Actually we need to have logs redirected to files instead of having it in journal. So we were using journalctl to get the logs of a service, filtered it and redirected it to the respective log files of the services. This is actually not a good way. So we are trying to use "StandardOutput=append:" option to directly write the stdout/stderr to the custom log file. But when we pass through journal, we have the prefix to the log statements (timestamp, pid,..) but this direct redirection of stdout doesn't get us those prefix. Is there a way already to add those Prefix or something we can introduce?

**Describe the solution you'd like**
Expecting the way to redirect the stdout of a service to the custom log (using "append:" in StandardOutput) with the required prefix as the journal is written 

**The systemd version you checked that didn't have the feature you are asking for**
systemd v244

**Comment by poettering** [comment]
hmm? you want to bypass the journal and write directly to file, but then you want us to anyway modify the data you write while you write it?

that's a contradictory request: you don't want us to process your logs, but you also want us to process them for you? how does that make sense?

**Comment by Arjun-DR** [comment]
It's not like we want to bypass the journal. We feel difficult to take logs from journal and write it to the custom log files. There are number of logs we need to manage and it seems to run journalctl for n number of services and redirect it to log files for every few seconds. We feel this way is not good since it takes CPU. Direct write to a file seems to be a very good option for us, but I am looking for the way to add the prefix as in journal.

Any facilities to add such prefix to the stdout before writing to the log file or any other suggestions ?

**Comment by poettering** [comment]
Direct writes mean direct writes. If you want each line to be prefixed, then you don't want direct writes.

We offer no facility for something like this, and I don't hink we should. You probably can script something with awk that does this, and then wrap you rcommand in a shell pipeline to do that. 

You could also have a service that does that for you, that listens on some AF_UNIX/stream socket, and then connect your sevice here to that. if you need help on that maybe contact the systemd mailing list, as that's better suited for such support questions.

but i am very sure we shouldn#t add this to systemd itself.
