### ISSUE TITLE
resolv.conf contains servers with non-standard UDP ports, which glibc doesn't support

### ISSUE THREAD

**Issue by dkhachyan** [systemd/systemd#20836]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Fedora release 33

**Linux kernel version used** (`uname -a`)

 > `Linux master-1 5.11.15-200.fc33.x86_64 #1 SMP Fri Apr 16 13:41:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > resolve.conf generates with custom dns server port if one is set in /etc/systemd/resolved.conf.d/some_config.conf

**Unexpected behaviour you saw**
 > Custom port number is missing in resolve.conf

**Steps to reproduce the problem**
 > 
```
[Resolve]
DNS=10.0.0.1:53553
Domains=example.com
```
```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.0.0.1
search example.com
```

**Comment by poettering** [comment]
resolv.conf does not support specifying port numbers. Given the file is defined by glibc there's nothing much we can do about it.

We should probably supress the whole entry though instead one that lacks the specification of the port nr.
