### ISSUE TITLE
homectl: cannot create user's home with LUKS and pbkdf2

### ISSUE THREAD

**Issue by nl6720** [systemd/systemd#20830]
**systemd version the issue has been seen with**
 > systemd 249 (249.4-1-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux archlinux 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > No errors and successfully created user home.

**Unexpected behaviour you saw**
 > `Operation on home testuser failed: Failed to execute operation: Invalid argument`

**Steps to reproduce the problem**
 > `homectl create testuser --storage=luks --luks-pbkdf-type=pbkdf2`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
sep 24 10:50:38 systemd-homed[285]: testuser: changing state absent → creating
sep 24 10:50:38 systemd-homework[523]: Sizing home to 85% of available disk space, which is 3.5G.
sep 24 10:50:38 systemd-homework[523]: Allocating image file completed.
sep 24 10:50:38 systemd-homework[523]: Writing of partition table completed.
sep 24 10:50:38 kernel: loop: module loaded
sep 24 10:50:38 systemd-homework[523]: Setting up loopback device /dev/loop0 completed.
sep 24 10:50:38 systemd-homework[523]: PBKDF max memory or parallel threads must not be set with pbkdf2.
sep 24 10:50:38 systemd-homework[523]: Failed to format LUKS image: Invalid argument
sep 24 10:50:38 kernel: loop0: detected capacity change from 0 to 7459919
sep 24 10:50:38 systemd-homed[285]: block device /sys/devices/virtual/block/loop0 has been removed.
sep 24 10:50:38 systemd-homed[285]: Operation on testuser failed: Invalid argument
```

**Comment by poettering** [comment]
hmm, and it works if you stick to the default or explicitly select argon2?

**Comment by poettering** [comment]
does it work if you also set --luks-pbkdf-time-cost=1ms ?

**Comment by nl6720** [comment]
The defaults work. `--luks-pbkdf-type=argon2i` and `--luks-pbkdf-type=argon2id` also work.

`--luks-pbkdf-type=pbkdf2 --luks-pbkdf-time-cost=1ms` does not work. Still the same error and the same messages in journal.
