### ISSUE TITLE
handle slightly invalid LUKS JSON data more gracefully

### ISSUE THREAD

**Issue by CaseyBakey** [systemd/systemd#20847]
Hello there,

I'm using Archlinux and was able to setup secure boot with my own keys, and was using TPM to decrypt my LUKS partition (thanks to systemd-cryptenroll). Everything was working fine since few months.

However, I did update the EFI firmware of my laptop few days ago, so the TPM wasn't able to hand me the keys on the next boot (since it was linked to the PCRS 0 and 7).

I'm actually using systemd v249.4 and I'm getting an error while enrolling again (to take the new firmware fingerprint/signature into account) the TPM to decrypt my LUKS partition:

```
[user@computer]$ sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0,7 /dev/nvme0n1p3
Please enter current passphrase for disk /dev/nvme0n1p3: ******************************
Failed to determine keyslot of JSON token: Bad medium type
```

I don't know if this is a regression in systemd (because Archlinux, rolling release, etc. and I may also have updated systemd in the last few days), or in the EFI firmware since I can't downgrade my EFI firmware to the one I was previously using.

Is there any logs I can hand over to help understand/fix this issue?

**Comment by poettering** [comment]
Can you run the command with SYSTEMD_LOG_LEVEL=debug set? And paste the longer output this generates here?

Apparently you have some JSON token data enrolled in your LUKS 2 superblock that doesn't have the right JSON types?

**Comment by CaseyBakey** [comment]
Here you are:
```
[root@computer]# export SYSTEMD_LOG_LEVEL=debug
[root@computer]# systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0,7 /dev/nvme0n1p3
Allocating context for crypt device /dev/nvme0n1p3.
Trying to open and read device /dev/nvme0n1p3 with direct-io.
Initialising device-mapper backend library.
Trying to load LUKS2 crypt type from device /dev/nvme0n1p3.
Crypto backend (OpenSSL 1.1.1l  24 Aug 2021) initialized in cryptsetup library version 2.4.1.
Detected kernel Linux 5.14.7-arch1-1 x86_64.
Loading LUKS2 header (repair disabled).
Acquiring read lock for device /dev/nvme0n1p3.
Opening lock resource file /run/cryptsetup/L_259:3
Verifying lock handle for /dev/nvme0n1p3.
Device /dev/nvme0n1p3 READ lock taken.
Trying to read primary LUKS2 header at offset 0x0.
Opening locked device /dev/nvme0n1p3
Veryfing locked device handle (bdev)
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:_checksum_1_ (on-disk)
Checksum:_same_checksum_1_ (in-memory)
Trying to read secondary LUKS2 header at offset 0x4000.
Reusing open ro fd on device /dev/nvme0n1p3
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:_checksum2_ (on-disk)
Checksum:_same_checksum2_ (in-memory)
Device size 17179869184, offset 16777216.
Device /dev/nvme0n1p3 READ lock released.
PBKDF argon2id, time_ms 2000 (iterations 0), max_memory_kb 1048576, parallel_threads 4.
🔐 Please enter current passphrase for disk /dev/nvme0n1p3: ******************************
Added key to kernel keyring as 830316484.

Keyslot 0 priority 1 != 2 (required), skipped.
Trying to open LUKS2 keyslot 0.
Reading keyslot area [0x8000].
Acquiring read lock for device /dev/nvme0n1p3.
Opening lock resource file /run/cryptsetup/L_259:3
Verifying lock handle for /dev/nvme0n1p3.
Device /dev/nvme0n1p3 READ lock taken.
Reusing open ro fd on device /dev/nvme0n1p3
Device /dev/nvme0n1p3 READ lock released.
Verifying key from keyslot 0, digest 0.
TPM successfully started up.
Creating primary key on TPM.
Successfully created primary key on TPM.
Starting authentication session.
Configuring PCR policy.
Acquiring policy digest.
Session policy digest: _digest1_
Added 512 bytes of entropy to the kernel random pool.
Generating secret key data.
Creating HMAC key.
Marshalling private and public part of HMAC key.
Completed TPM2 key sealing in 1.831612s.
Requesting JSON for token 0.
Failed to determine keyslot of JSON token: Bad medium type
Releasing crypt device /dev/nvme0n1p3 context.
Releasing device-mapper backend.
Closing read only fd for /dev/nvme0n1p3.

```

**Comment by CaseyBakey** [comment]
Ok, it seems it was some TPM leftovers that prevented the command from succeeding.
I deleted the only token that was listed when checking with luksDump, and now the command doesn't output the error.
I was worried the listed token was "linked" to the keyslot (and thus me deleting my passphrase).

Here is what I've done:
```
[user@computer]$ sudo cryptsetup token remove --token-id 0 /dev/nvme0n1p3
[user@computer]$ sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0,7 /dev/nvme0n1p3
🔐 Please enter current passphrase for disk /dev/nvme0n1p3: ******************************
New TPM2 token enrolled as key slot 1.
```

I'm now going to reboot and cross my fingers.

**Comment by poettering** [comment]
OK, so I think we should handle this more gracefully and just skip over tokens we can't parse.

How did the JSON data end up in your LUKS superblock though? Which tool put them there? a systemd tool?

**Comment by poettering** [comment]
I prepped #20863 now which handles this issue more gracefully, but still warns if an invalid "keyslots" field is found.

I am still curious how this happened though, i.e. which tool actually placed the invalid entry there?

**Comment by CaseyBakey** [comment]
I guess this keyslot was put there by systemd-cryptenroll since it's the only tool I did use to enroll the TPM and the token contained the string "tpm2" in the name.

Here the steps I did to encounter that:
1) Have a properly enforced Secure Boot (my own keys are setup in the EFI/BIOS).
2) Have a LUKS2 partition (LVM inside, but I guess we don't care)
3) Enroll the TPM in the LUKS2 header with systemd-cryptenroll, while linking it to PCRS 0 (EFI firmware checksum/signature) and PCRS 7 (Secure Boot state). So the TPM while handle the key if and only if the EFI firmware is the same as when it was enrolled, and if the Secure Boot is still ON.
4) Reboot, enjoy for many months. Update Arch on daily/weekly basis. But no EFI firmware though.
5) One day got geeky, and install EFI firmware update (aka BIOS update back in the days) since security fixes.
6) Reboot, and now the TPM doesn't hand the key because PCRS 0 changed. Unlock with other keyslot (passphrase) and continue booting.
7) Once booted, try to enroll again the TPM with the same systemd-cryptenroll command (to take into account the new PCRS 0 value), get the JSON token error and go whine on systemd GitHub issue section ;)

**Comment by poettering** [comment]
Hmm, so I guess the LUKS2 superblock is gone now in its old state? Would have love to see a dump of the JSON data it included.

Was the TPM2 enrollment done with a pre-release version of systemd?

**Comment by CaseyBakey** [comment]
Yes, it's gone...

But please tell me how to do a backup of it, and I'll do it for the next EFI update.

Or I can try to downgrade EFI (it's at least possible to go to the previous version), and it will prevent the TPM to handle the keys, so I should be quite in the same situation while trying to enroll again.
