### ISSUE TITLE
Confusing wording regarding OnUnitActiveSec and OnUnitInactiveSec

### ISSUE THREAD

**Issue by guihkx** [systemd/systemd#20841]
I'm not a native English speaker, but the wording used to document both `OnUnitActiveSec` and `OnUnitInactiveSec` are very confusing to me:

```
$ man 5 systemd.timer
├───────────────────┼───────────────────────────────┤
│OnUnitActiveSec=   │ Defines a timer relative to   │
│                   │ when the unit the timer unit  │
│                   │ is activating was last        │
│                   │ activated.                    │
├───────────────────┼───────────────────────────────┤
│OnUnitInactiveSec= │ Defines a timer relative to   │
│                   │ when the unit the timer unit  │
│                   │ is activating was last        │
│                   │ deactivated.                  │
└───────────────────┴───────────────────────────────┘
```

I'm not entirely sure what those two statements are supposed to mean.

**Comment by poettering** [comment]
I am not sure how we can express this any better. Timer units activate other units based on time specifications. With the first of the two settings the timer is defines one relative to the time that other unit was last activated, and the second of the two settings defines one relative to the time that other unit was last deactivated. Is that so hard to grok?

Not sure you we can express this better, the sentences as they stand are terse, but say precisely what we mean.

It appears to me this is only hard to understand if the concept "unit" is not well understood jetzt, or activation/deactivation of units?

**Comment by guihkx** [comment]
Nah, I think I fully understand their purpose. It's just that gramatically, those descriptions are putting me off. 

>Defines a timer relative to when the unit the timer unit is activating was last activated. 

"the unit the timer unit" and " is activating was last activated" both sound just wrong to me xD

But since they seem correct, feel free to close I guess

**Comment by poettering** [comment]
better proposals for the wording here are always welcome?

**Comment by guihkx** [comment]
I got nothing. :(
