### ISSUE TITLE
Implement prefixes for SELinuxContext=

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20840]
**Is your feature request related to a problem? Please describe.**
SELinuxContext= applies to the whole unit (just like User= and Group=) but you might want to for example exempt ExecStartPre= (like PermissionsStartOnly=true use to do and now the "+" prefix does

**Describe the solution you'd like**
I guess implement something similar to the + prefix for User= and Group= but then instead for SELinuxContext=

**Describe alternatives you've considered**
I am actually working around this issue by calling the runcon command manually:

`ExecStart=/usr/bin/runcon -t myapp_t -- /usr/bin/myapp`

**The systemd version you checked that didn't have the feature you are asking for**
249

**Comment by doverride** [comment]
this is already supported ...
