### ISSUE TITLE
Systemd-boot not recognizing XBOOTLDR vfat partition.

### ISSUE THREAD

**Issue by xNicklaj** [systemd/systemd#20845]
**systemd version the issue has been seen with**
 > 249.4-1
 
**Used distribution**
 > Manjaro Pahvo

**Linux kernel version used** (`uname -a`)
 > `Linux manjaro 5.4.144-1-MANJARO #1 SMP PREEMPT Fri Sep 3 10:14:44 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > Zen 1 (x86_64)

**Expected behaviour you didn't see**
 > Systemd-boot should load entries from /boot

**Unexpected behaviour you saw**
 > Systemd-boot doesn't load entries from /boot. Only loads the entry from /efi/EFI/Microsoft

**Steps to reproduce the problem**
```
$ lsblk -p /dev/nvme0n1 -o NAME,PARTTYPE,MOUNTPOINT,FSTYPE
NAME             PARTTYPE                             MOUNTPOINT FSTYPE
/dev/nvme0n1                                                     
├─/dev/nvme0n1p1 c12a7328-f81f-11d2-ba4b-00a0c93ec93b /mnt/efi   vfat
├─/dev/nvme0n1p2 e3c9e316-0b5c-4db8-817d-f92df00215ae            
├─/dev/nvme0n1p3 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7            ntfs
├─/dev/nvme0n1p4 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7            ntfs
├─/dev/nvme0n1p5 bc13c2ff-59e6-4262-a352-b275fd6f7172            ntfs
└─/dev/nvme0n1p6 bc13c2ff-59e6-4262-a352-b275fd6f7172 /mnt/boot  vfat
```
```
$ lsblk -p /dev/sda -o NAME,PARTTYPE,MOUNTPOINT,FSTYPE
NAME        PARTTYPE                             MOUNTPOINT FSTYPE
/dev/sda                                                    
├─/dev/sda1 0fc63daf-8483-4772-8e79-3d69d8477de4 /mnt       btrfs
├─/dev/sda3 0fc63daf-8483-4772-8e79-3d69d8477de4 /mnt/home  btrfs
├─/dev/sda4 0657fd6d-a4ab-43c4-84e5-0933c84b4f4f            swap
├─/dev/sda5 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7            ntfs
└─/dev/sda6 ebd0a0a2-b9e5-4433-87c0-68b6b72699c7            ntfs
```
```
$ cat /mnt/efi/loader/loader.conf
#timeout 3
#console-mode keep
default manjarolinux5.13
```
```
**from chroot**
manjaro# tree /boot
/boot
|-- 600813afd37a42c5936d317973817022
|-- EFI
|   `-- Linux
|-- initramfs-4.14-x86_64-fallback.img
|-- initramfs-4.14-x86_64.img
|-- initramfs-5.13-x86_64-fallback.img
|-- initramfs-5.13-x86_64.img
|-- intel-ucode.img
|-- linux414-x86_64.kver
|-- linux513-x86_64.kver
|-- loader
|   |-- entries
|   |   |-- manjarolinux5.13-fallback.conf
|   |   `-- manjarolinux5.13.conf
|   |-- loader.conf
|   `-- random-seed
|-- vmlinuz-4.14-x86_64
`-- vmlinuz-5.13-x86_64

5 directories, 13 files
```
```
manjaro# bootctl list --esp-path=/efi
Boot Loader Entries:
        title: Manjaro (5.13) (manjarolinux5.13-fallback.conf)
           id: manjarolinux5.13-fallback.conf
       source: /boot/loader/entries/manjarolinux5.13-fallback.conf
      version: 5.13
        linux: /vmlinuz-5.13-x86_64
       initrd: /initramfs-5.13-x86_64-fallback.img
               /intel-ucode.img
      options: root="PARTUUID=04d91ba1-3c3f-5641-af4d-d86592f21524" rw

        title: Manjaro (5.13) (manjarolinux5.13.conf) (default)
           id: manjarolinux5.13.conf
       source: /boot/loader/entries/manjarolinux5.13.conf
      version: 5.13
        linux: /vmlinuz-5.13-x86_64
       initrd: /initramfs-5.13-x86_64.img
               /intel-ucode.img
      options: root="PARTUUID=04d91ba1-3c3f-5641-af4d-d86592f21524" rw
```

**Comment by medhefgo** [comment]
Just to make sure, is your gpt header not corrupted? `gdisk /dev/nvme0n1` and then use the `v` command to make sure.
Also, physical sector size might be the cause, can you tell me what `fdisk -l /dev/nvme0n1` shows for that too?

Note that the current main branch systemd-boot right now does not detect xbootldr partitions due to some bugs (that I caused) I intend to fix in the next couple days, but you're using the stable branch right now, so that seems odd...

**Comment by medhefgo** [comment]
Also, you have two xboot loader partitions: nvme0n1p5 (ntfs) and nvme0n1p6 (vfat). But there can only be one and the first is probably picked up first, so you'd want to change the type in fdisk.

**Comment by xNicklaj** [comment]
> Also, you have two xboot loader partitions: nvme0n1p5 (ntfs) and nvme0n1p6 (vfat). But there can only be one and the first is probably picked up first, so you'd want to change the type in fdisk.

Actually the first one `/dev/nvme0n1p5` is the Windows recovery partition that I mistakenly changed the type to. I'll edit it ASAP. I don't have access to the workstation at the moment, but in a few hours I'll post the result of the commands you asked.

**Comment by xNicklaj** [comment]
> Also, you have two xboot loader partitions: nvme0n1p5 (ntfs) and nvme0n1p6 (vfat). But there can only be one and the first is probably picked up first, so you'd want to change the type in fdisk.

Turns out that this was exactly the problem. Close the issue, or delete it if you will!

Thanks for the help!
