### ISSUE TITLE
homed: add knob for dropping caches on logout (and make it default enabled for fscrypt)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20857]
Using SystemD 249.4-1 on Linux 5.14.8-arch1-1

Created a user `$ homectl create user --storage=fscrypt --member-of=wheel`

Logged in and out (completely on all terminals, no linger in use)

Checking from another user: `ls /home/user{,.homedir}`
State seen: Directory unlocked and readable

State expected: locked
After reboot: locked as expected

`$ man pam_systemd_home` states: Automatically mount home directories managed by systemd-homed.service on login, and unmount them on logout

Doesn't keep its promise ;) Citing 0pointer: Can we do better?

Maybe related to [systemd-user doesn't properly close its PAM session](https://github.com/systemd/systemd/issues/8598)? But linked issue seems a bit dated.

**Comment by poettering** [comment]
That's how key management with fscrypt works: it's a bit nuts.

Only once you flush the buffer caches the decrypted data is removed from memory.

**Comment by JackCasual** [comment]
I hoped `pam_systemd` would save me from configuring the PAM chains by hand :)

Using only fscrypt and its usertools there's a functioning workaround by
adding to /etc/pam.d/system-login:

`session [success=1 default=ignore]  pam_succeed_if.so  service = systemd-user quiet`
`session    optional   pam_fscrypt.so       drop_caches lock_policies`

Taken from [fscrypt's issues](https://github.com/google/fscrypt/issues/77#issuecomment-360184014)

**Comment by poettering** [comment]
dropping all caches on logout sounds a bit heavy handed... but i guess we could add a knob for that...

**Comment by JackCasual** [comment]
Thanks for your consideration :)

**Comment by ebiggers** [comment]
> That's how key management with fscrypt works: it's a bit nuts.
>
> Only once you flush the buffer caches the decrypted data is removed from memory.
>
> dropping all caches on logout sounds a bit heavy handed... but i guess we could add a knob for that...

As I mentioned 2 years ago on the original systemd-homed pull request (https://github.com/systemd/systemd/pull/14096#discussion_r355036704), there is an ioctl to remove fscrypt keys.  It's unclear why systemd still isn't using it, and is instead considering implementing deprecated workarounds.

Well, as they say: you can lead a horse to water, but you can't make it drink.
