### ISSUE TITLE
Failed to determine supplementary groups: Invalid argument, UID 100201 + private users offset

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#20851]
I am running s systemd-nspawn container with `PrivateUsers=1400000`. There is a user `bigbluebutton` inside this container:

```
# id bigbluebutton
uid=100201(bigbluebutton) gid=100201(bigbluebutton) groups=100201(bigbluebutton)
```

So, it is 100201+1400000=1500201 on the host.

A unit file inside this container is the following:
```
# systemctl cat bbb-rap-starter.service
# /lib/systemd/system/bbb-rap-starter.service
[Unit]
Description=BigBlueButton recording processing starter

[Service]
Type=simple
ExecStart=/usr/local/bigbluebutton/core/scripts/rap-starter.rb
WorkingDirectory=/usr/local/bigbluebutton/core/scripts
User=bigbluebutton
Slice=bbb_record_core.slice
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
systemd can't run it with the following error:
**Failed to determine supplementary groups: Invalid argument**

The problem can be reproduced inside the container without running a systemd unit:
```
# sudo -u bigbluebutton dd
sudo: unable to change to runas gid: Invalid argument
```

/etc/nsswitch.conf inside the container:
```
passwd:		files systemd
shadow:		files systemd
group:		files systemd
```

Let's see what is 1500201 on the host (but I doubt that it makes any difference):

```
# id 1500201
uid=1500201(CPU_bbb_playback_bigbluebutton) gid=1500201(CPG_bbb_playback_bigbluebutton) группы=1500201(CPG_bbb_playback_bigbluebutton)
# grep 1500201 /etc/passwd
CPU_bbb_playback_bigbluebutton:x:1500201:1500201:Container private user, bigbluebutton user of container dumalogiya-containers-bigbluebutton-playback:/:/sbin/nologin
CPU_bbb_recs_bigbluebutton:x:486:1500201:Container private user, bigbluebutton user of container dumalogiya-containers-bigbluebutton-recordings:/:/sbin/nologin
```
So, there are 2 users with the same UID (both were created by systemd-sysusers).
I ran `userdel CPU_bbb_recs_bigbluebutton` to remove duplication and of course this did not help.

systemd is v246.13, maybe will try a newer version later.

**Comment by mikhailnov** [comment]
getgrouplist() syscall seems to fail.

`get_supplementary_groups()`  in `src/core/execute.c` calls `getgrouplist(user, gid, l_gids, sysconf(_SC_NGROUPS_MAX))`, man 3 getgrouplist (https://man7.org/linux/man-pages/man3/getgrouplist.3.html) has an example program which uses this syscall, I tested it and it works inside systemd-nspawn:

```
# ./t bigbluebutton 65536
ngroups = 1
100201 (bigbluebutton)
```

I tried `sudo -u bigbluebutton dd` (which gave error inside systemd-nspawn, see above) inside a pure chroot without private users and it worked... very interesting

I also tried a lower number of UID, changed private users offset from 1400000 to 5000, but it did not help.

**Comment by poettering** [comment]
Please run an "strace -p $PID1 -s 500 -y -f -o log" on the host right before reproducing this issue, with $PID1 replaced by the external PID of the PID 1 inside the container. Then hit C-c after the thing failed, and attach the resulting `log` file here. This might give us a hint what fails.

Moreover, please enable debug logging inside the container via "systemd-analyze log-level debug", then reproduce the issue and provide the relevant parts of the logs this resulted in here.

**Comment by poettering** [comment]
Also, please try this try this with something newer, i.e. both newer systemd inside the container and newer nspawn.

Note that we generally don't track issues in old systemd versions here. If it's not reproducible with the current newest upstream version, or one older we generally close it.

**Comment by mikhailnov** [comment]
Done, here is the log: https://clbin.com/kN3dn
`160101 setgroups(1, [100201])           = -1 EINVAL `
This does not explain anything

systemd-249-1.gitfab79a.1.x86_64 on the host, systemd-246.13-8.x86_64 inside the container

With `systemd-analyze log-level debug` inside the container:

Failed to set 'memory.limit_in_bytes' attribute on '/bbb_record_core.slice/bbb-rap-caption-inbox.service' to '-1': No such file or directory
Failed to set 'pids.max' attribute on '/bbb_record_core.slice/bbb-rap-caption-inbox.service' to '38215': No such file or directory
Failed to set invocation ID on control group /bbb_record_core.slice/bbb-rap-caption-inbox.service, ignoring: Operation not permitted
bbb-rap-caption-inbox.service: Failed to remove delegate flag on control group /bbb_record_core.slice/bbb-rap-caption-inbox.service, ignoring: Operation not permitted
bbb-rap-caption-inbox.service: Passing 0 fds to service
bbb-rap-caption-inbox.service: About to execute: /usr/local/bigbluebutton/core/scripts/rap-caption-inbox.rb
bbb-rap-caption-inbox.service: Forked /usr/local/bigbluebutton/core/scripts/rap-caption-inbox.rb as 90367 PR_SET_MM_ARG_START failed: Operation not permitted
bbb-rap-caption-inbox.service: Changed dead -> running
bbb-rap-caption-inbox.service: Job 4720886 bbb-rap-caption-inbox.service/start finished, result=done
Started BigBlueButton recording caption upload handler.
bbb-rap-caption-inbox.service: Failed to determine supplementary groups: Invalid argument
bbb-rap-caption-inbox.service: Failed at step GROUP spawning /usr/local/bigbluebutton/core/scripts/rap-caption-inbox.rb: Invalid argument
bbb-rap-caption-inbox.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
bbb-rap-caption-inbox.service: Child 90367 belongs to bbb-rap-caption-inbox.service.
bbb-rap-caption-inbox.service: Main process exited, code=exited, status=216/GROUP
bbb-rap-caption-inbox.service: Failed with result 'exit-code'

**Comment by mikhailnov** [comment]
strace sudo -u bigbluebutton echo

160101 setgroups(1, [100201])           = -1 EINVAL

**Comment by poettering** [comment]
i wonder if this is caused by `/proc/self/setgroups` being set to deny.

How do you invoke nspawn? with an empty aux group list?

**Comment by mikhailnov** [comment]
There is nothing secret in my containers, to reproduce the issue, 2 RPMs from https://disk.yandex.ru/d/SkSHx0CcHdZaqg can be installed.

dumalogiya-containers-bigbluebutton-recordings-0.1-0.git8bdb39.2-rosa2021.1.x86_64.rpm
dumalogiya-containers-bigbluebutton-recordings-sysusers-0.1-0.git8bdb39.2-rosa2021.1.x86_64.rpm

Then `systemctl daemon-reload`, `systemctl start systemd-nspawn@bigbluebutton-recordings`.
It is how I invoke nspawn.

From the host:
# cat /proc/*/setgroups | grep -v allow | wc -l
0

**Comment by mikhailnov** [comment]
After `systemctl start systemd-nspawn@bigbluebutton-recordings`, `machinectl shell bigbluebutton-recordings`, `systemctl --failed`, services bbb-rap-caption-inbox.service and bbb-rap-starter.service will be failed.

**Comment by mikhailnov** [comment]
Oh, and the following two lines  should be removed from /etc/systemd/nspawn/bigbluebutton-recordings.nspawn after installing RPMs

Bind=/srv/bigbluebutton-recordings/published:/var/bigbluebutton/published
Bind=/srv/bigbluebutton-recordings/recording/raw:/var/bigbluebutton/recording/raw

ExecStartPre from /etc/systemd/system/systemd-nspawn@bigbluebutton-recordings.service.d/override.conf should also be removed

**Comment by mikhailnov** [comment]
What is interesting, I run other containers in the same way and do not have problems with services inside them, e.g. coturn successfulyl runs from the "coturn" user inside the container, and I do not see any difference with this problematic container. The only difference is that coturn.service has both User= and Group=, but these failing service have only User=

**Comment by mikhailnov** [comment]
Addid User=bigbluebutton via a drop-in file /run/systemd/system/bbb-rap-starter.service.d/override.conf did not help

**Comment by mikhailnov** [comment]
```
# strace -f chown bigbluebutton:bigbluebutton /tmp/u
chown: changing ownership of '/tmp/u': Invalid argument
<...>
fchownat(AT_FDCWD, "/tmp/u", 100201, 100201, 0) = -1 EINVAL (Invalid argument)
```
Why does the kernel dislike 100201...

**Comment by mikhailnov** [comment]
Trying to understand which IDs kernels starts to dislike:

```bash
rm -fv /rmp/u
touch /tmp/u
for i in `seq 0 100201`; do if ! chown $i:$i /tmp/u ; then echo FAILED $i ; break; fi; done
chown: changing ownership of '/tmp/u': Invalid argument
FAILED 65536
```
65537 also does not work. So, all values above 65535 are rejected. Why can it be so?

**Comment by mikhailnov** [comment]
" This range has been chosen so that it is below the 16bit boundary (i.e. below 65535), in order to provide compatibility with container environments that assign a 64K range of UIDs to containers using user namespacing."
https://systemd.io/UIDS-GIDS/

That is probably the key to the problem.

**Comment by mikhailnov** [comment]
1215 is PID of systemd-nspawn
```
# cat /proc/1215/gid_map
         0          0 4294967295
# cat /proc/1215/uid_map
         0          0 4294967295
```
PID 1219 is its child - systemd, PID1 of the container.
```
# cat /proc/1219/gid_map
         0    1400000      65536
# cat /proc/1219/uid_map
         0    1400000      65536
```

Why is the length of the range just 65536?

**Comment by mikhailnov** [comment]
I've reread the manual systemd-nspawn(1), changed `PrivateUsers=1400000` to `PrivateUsers=1400000:200000`, and the problem has been solved. Facepalm.

Sorry for noise and thanks for help. Hope that someone may come here by googling the same problem.
Closing as not a bug.
