### ISSUE TITLE
[journalctl] Home/End button to scroll

### ISSUE THREAD

**Issue by mrx23dot** [systemd/systemd#20856]
Please add Home/End button to jump to beginning/end of journalctl log, same way page up/down works.
A lot more intuitive than shift+G.

systemd --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Comment by poettering** [comment]
We just invoke the `less` pager. It handles scroling.

Please contact your distro about that. Not us.
