### ISSUE TITLE
nspawn: not shifting UID/GID for private users offset inside /var/tmp

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#20869]
Running an nspawn container with `Bind=:/var/lib/systemd` and private users results into systemd-logind failing inside the container:
**systemd-logind.service: Failed to set up special execution directory in /var/lib: Permission denied**
It is probably because the directory inside /var/tmp, created because of an empty source inside Bind directive, is owned by 0:0, but it should have been owned by PrivateUsers offset, I think. Or maybe should not.

**Comment by poettering** [comment]
which nspawn version is this?

**Comment by poettering** [comment]
i reproduced this here with current git main. And yes, this should be owned by the containers's root, not the host's root.
