### ISSUE TITLE
[regression] corrupted escape characters in the output of systemctl status

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#20866]
After upgrading from systemd 246 to 249 + git main from today (from commit https://github.com/systemd/systemd/commit/5b32e48f6e3753600b9f6c44446b313294270f48) I see corrupted output of `systemctl status ...`, see screenshot:

![image](https://user-images.githubusercontent.com/15802528/135132004-6d19d22f-f7f0-4625-9d7f-f83aa30f1dd4.png)

The same is in two terminal emulators, xfce4-terminal and konsole and in tty, and on 2 different machines

**Comment by mrc0mmand** [comment]
What's your `less` version? This sounds like https://github.com/systemd/systemd/issues/20195#issuecomment-877772747 (and https://github.com/systemd/systemd/issues/18814).

**Comment by yuwata** [comment]
Please use newer less.

**Comment by mikhailnov** [comment]
Updating less from 563 to 590 has helped, thanks!
