### ISSUE TITLE
systemd-inhibit started from different user doesn't inhibit root

### ISSUE THREAD

**Issue by fvigotti** [systemd/systemd#20898]
**systemd version the issue has been seen with**

Linux io-VirtualBox 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
systemd --version
systemd 245 (245.4-4ubuntu3.11)

**Expected behaviour you didn't see**

io@io-VirtualBox:/root$ whoami
io
io@io-VirtualBox:/root$ systemd-inhibit --what="shutdown" cat
 ** starts waiting...

*u2 now attempt to reboot:

$ systemctl reboot  
Operation inhibited by "cat" (PID 14135 "systemd-inhibit", user io), reason is "Unknown reason".
User io is logged in on sshd.
Please retry operation after closing inhibitors and logging out other users.
Alternatively, ignore inhibitors and users with 'systemctl reboot -i'.
$ whoami
u2

*root attempt to reboot 
root
root@io-VirtualBox:~# systemctl reboot
root@io-VirtualBox:~# Shared connection to 192.168.3.105 closed.

**Unexpected behaviour you saw**
inhibit not enforced for user

**Steps to reproduce the problem**

this is tricky, because the default doc says : 
1 - `systemd-inhibit` is built to step other users than the user who run command but VERY OFTEN is used for backup/ cd burning/ other long running tasks  which may start belonging to root or the main user ( but nevertheless must keep the system to accidental reboot/sleep/... ! ) there are `systemctl reboot -i` if needed
2 - It's very, very difficult to run  `systemd-inhibit`  from a user different than root!, (sudo/sudoers will run as root ) , I've found that the only way to run this command from a user is to add a policy for the command

```
cat > /etc/polkit-1/localauthority/50-local.d/org.freedesktop.login1.inhibit-block-shutdown.pkla << POLKIT
[Allow user io to run inhibit commands]
Identity=unix-user:io
Action=org.freedesktop.login1.inhibit-block-shutdown
ResultInactive=no
ResultActive=no
ResultAny=yes
POLKIT
```

but anyway.. if something trigger a reboot as root, the inhibit doesn't work
I've also tried with mode delay 
`systemd-inhibit --what="shutdown"  --mode=delay cat`

**Comment by mrc0mmand** [comment]
This was already implemented in v248 via https://github.com/systemd/systemd/commit/4327574fc1093513badc2177f71cede2fc88c13c:

From `systemctl(5)`:
>--check-inhibitors=

>    When system shutdown or sleep state is request, this option controls how to deal with inhibitor locks. It takes one of "auto", "yes" or "no". Defaults to "auto", which will behave like "yes" for interactive invocations (i.e. from a TTY) and "no" for non-interactive invocations. "yes" will let the request respect inhibitor locks. "no" will let the request ignore inhibitor locks.

>    Applications can establish inhibitor locks to avoid that certain important operations (such as CD burning or suchlike) are interrupted by system shutdown or a sleep state. Any user may take these locks and privileged users may override these locks. If any locks are taken, shutdown and sleep state requests will normally fail (unless privileged) and a list of active locks is printed. However, if "no" is specified or "auto" is specified on a non-interactive requests, the established locks are ignored and not shown, and the operation attempted anyway, possibly requiring additional privileges. May be overridden by --force.

https://www.freedesktop.org/software/systemd/man/systemctl.html

**Comment by mrc0mmand** [comment]
Example from Fedora Rawhide (systemd-249.2-1.fc35.x86_64):

```
### An unprivileged user on a tty
$ systemd-inhibit --what=shutdown sleep infinity

### Root
# systemd-inhibit --list
WHO            UID  USER PID  COMM            WHAT     WHY                                       MODE 
NetworkManager 0    root 517  NetworkManager  sleep    NetworkManager needs to turn off networks delay
sleep infinity 1001 test 1660 systemd-inhibit shutdown Unknown reason                            block

2 inhibitors listed.
# systemctl reboot --check-inhibitors=yes
Operation inhibited by "sleep infinity" (PID 1660 "systemd-inhibit", user test), reason is "Unknown reason".
User test is logged in on tty1.
Please retry operation after closing inhibitors and logging out other users.
Alternatively, ignore inhibitors and users with 'systemctl reboot -i'.
```

**Comment by fvigotti** [comment]
about : `--check-inhibitors` I'm not sure if this is good ,
this solution reverses the responsibility, how I can be sure that a given even will make use of it ? Could be useful if the default behaviour can be configured in config files, so I know that by default the system-inhibit works if configured..

anyway... about the bug report I was in TTY, not used -i flag during reboot but system rebooted *always* when executed as root,
*given* that a special policy must be configured to allow a user to execute systemd-inhibit ,
I don't understand why the correct application behaviour MUST be that root can inhibit root, and a policy-alloed user can block root too , right now, root reboot and nothing stop him ( even without -i and even from tty ) , 

what i wanted is : ( i don;t have such modern systemd, please test yourself if you have a minute ) 


### Root
# systemd-inhibit --list
WHO            UID  USER PID  COMM            WHAT     WHY                                       MODE 
NetworkManager 0    root 517  NetworkManager  sleep    NetworkManager needs to turn off networks delay
sleep infinity 1001 test 1660 systemd-inhibit shutdown Unknown reason                            block

2 inhibitors listed.

- now press the computer shutdown button, or ask the VM provider to perform a soft reboot, or let some application trigger a reboot ( system upgrade ? ) , or simply : 
# systemctl reboot 

the system should not reboot

**Comment by ploink** [comment]
This issue has also been reported to gnome
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/591
