### ISSUE TITLE
in systemctl there must be a way to execute a safe shutdown of critical application , with dependency that wait before starting the stopping phase

### ISSUE THREAD

**Issue by fvigotti** [systemd/systemd#20899]
if service B depend on service A, 
( tried multiple service configuration , Requires, After, Wants, BindsTo,  or even running after final.target )
but anyway probably it's not a problem if my attempts.. because by specification what i mean isn't even specified in the docs, 
there is a nuance of meaning that prevents an important use of the shutdown phase, 
let me explain:
systemd DOES include tasks to be executed in order during shutdown phase..

imho that should means ( at least should comprehend the meaning) that I can fully execute tasks in order during shutdown phase..

what it really means is that :  systemd DOES include tasks to be *started* in order during shutdown phase..

because there is no way to ensure that if B depend on A which depend on Z which depend on X and so on..
unfortunately there is no way to ensure that the B.ExecStop has completed before  A.ExecStop start ( or process signaled ),  so if B should stop with a long running tasks.. at the end of this tasks it will found that A is an inconsitent state aswell as other services..

**the internet** seems to suggest that the only way is to use `systemd-inhibit` but this one seems to have confusing behaviour too ( seems not usable for root services, or even incompatible with a root user/services environment(if root initialize the shutdown, the command doesn't work )  #20898  ) 

to put it in another way there is this asymmetry in the systemctl design,
B can begin start after A is completely started, but cannot completely stop before A begin stopping,

things gets complicated when there are containerd pod A which should stop before containerd pod B but everything stop together along with containerd service so if A stop before B , and B is performing tasks that need A online it may fails ( ie: A is is a proxy for node communications while B is one of the node services which must push last state before shutdown to other nodes )

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by fvigotti** [comment]
Sorry , I didn't wanted to be overly emotional, I was trying to describe the problem and the attempted solutions that led me to the creation of the * feature request *, probably a bit of frustration emerged in the description but the goal of the post was to help development with a feature request that I thought was missing,  you pointed me to the mailing list, but I still believe that it is not a problem of my inexperience (I confirm that I'm not a systemd expert anyway) and I already have a solution for my use case, I'm using reboot-guard to do that now , 


but from the tests I carried out, it seems to me that it is not possible to be more rigorous on dependencies during the shutdown phase, and maybe a flag would be enough to activate this feature,
by rigor I mean: **if B depends on A, during the shutdown phase, B must be completely terminated (all stop steps terminated || timeout ) before starting the shutdown of A**

**Comment by poettering** [comment]
What you are looking for is of course implemented. It seems you have questions about using systemd. For those please contact the mailing list or so, but please let's keep the signal-to-noise ration high on this bug+rfe tracker. Thanks!
