### ISSUE TITLE
systemd-sysctl loads files in an unintuitive order

### ISSUE THREAD

**Issue by AlainKnaff** [systemd/systemd#20919]
The issue has been seen with systemd version 247.3-6

It has been observed on Debian 11 with kernel `Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux` running on Intel(R) Core(TM)2 Quad CPU Q6600  @ 2.40GHz

Systemd includes a sysctl program intended to load sysctl config files from /etc

**Expected behaviour you didn't see**

I'd expect files from /etc/sysctl.d to be loaded *after* those from /usr/lib/sysctl.d/
Indeed, the sysadmin's choices (in /etc) should always override the defaults from the packages (in /usr/lib)

**Unexpected behaviour you saw**

It seems that files are loaded in the alphabetical order of their base names, no matter which directory they come from.
I.e.  /usr/lib/sysctl.d/protect-links.conf would verwrite /etc/sysctl.d/allow_twrite.conf , because p > a

**Steps to reproduce the problem**

1. Put fs.protected_regular=0 into /etc/sysctl.d/allow-twrite.conf 
2. reboot.
3. Check /proc/sys/fs/protected_regular => it contains 2 (from /usr/lib/sysctl.d/protect-links.conf) rather than 0 (from  /etc/sysctl.d/allow-twrite.conf)

**Additional program output to the terminal or log subsystem illustrating the issue**

none

**Comment by poettering** [comment]
Please consult the man page, the section about "Configuration Directories and Precedence":

https://www.freedesktop.org/software/systemd/man/sysctl.d.html

The order is now what you appear to assume it is: we order by filename, without the prefix path. This a file "allow-twrite.conf" will always be read before one called "protect-links.conf", regardless in which dirs these two files are place.

It's genreally recommend to call the files NN-xyz.conf, with NN being a pair of decimals you can use for ordering, and xyz beng some name. The files we install ourselves follow that scheme.
