### ISSUE TITLE
How to specify the SecureOn password in a Link file?

### ISSUE THREAD

**Issue by rnhmjoj** [systemd/systemd#20913]
A link file allows configuring the WakeOnLan policy of network interface with the `WakeOnLan=` setting.
The manual page [systemd.link(5)](https://www.freedesktop.org/software/systemd/man/systemd.link.html) says it's also possible to enable a password with `WakeOnLan=secureon`, however it doesn't mention how to specify the password itself. How should I configure the password?

**Comment by poettering** [comment]
We currently don't support that.

**Comment by yuwata** [comment]
@rnhmjoj I introduced a new setting to set the password in #20926. But I have not tested. If possible, could you test the PR? Thank you.
