### ISSUE TITLE
How does libnss_resolve communicate with systemd-resolved

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#20925]
I want to use [nss-resolve](https://www.freedesktop.org/software/systemd/man/nss-resolve.html) in a chrooted environment.

Please extend https://www.freedesktop.org/software/systemd/man/nss-resolve.html to state, how does nss-resolve communicate with systemd-resolved.

I want to create isolated environment, with its own /etc/nsswitch.conf , which calls systemd-resolved on the host, and I want to know how the isolation shall allow the communication.

**Comment by poettering** [comment]
This is so far considered to be an implementation detail of resolved/nss-resolve.
