### ISSUE TITLE
[Outreachy fall 2021] Applicants tasks/contributions

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#20928]
# Intro

This ticket will serve as the central point tracking the contributions of perspective Outreachy (fall 2021 cohort) applicants.

For those interested, this process is described here: https://www.outreachy.org/apply/make-contributions/
The systemd project will participate for the first time this year: https://www.outreachy.org/communities/cfp/systemd/

A series of tasks will be listed here. Some of them will be "repeatable", ie: some basic tasks that every applicant can do. Some can only be done once, so they are first-come first-served. Some will be relatively quick and should be doable in a couple hours, others might take several days, and they'll be tagged as such.

Every applicant should start with the basic repeatable tasks, and complete at least two. Simply quote the task in a comment, posting proof of completion. We will "thumbs up" the comment to acknowledge completion.

After at least two of those are done and acked, then applicants should move on to the "non-repeatable" tasks. Write a comment quoting the task you selected, and if it's open-ended specify what exactly you are going to do, before you start. Those should end up with a pull request. Note that simply opening a pull request is not enough, they will be reviewed and might need follow-ups before they can be merged, so take that into account when planning for time.

Applicants should complete and wait for ack on completion at least 2 of the repeatable tasks before moving on to the short/long tasks.

@anitazha kindly volunteered to help with moderating and reviewing this process with me, so look for reviews/acks from either one of us.

# Documentation for new contributors
Contributors who are new to `systemd` are highly encouraged to start from the following documents:

- https://systemd.io/CONTRIBUTING/
- https://systemd.io/CODING_STYLE/
- https://systemd.io/HACKING/
- https://systemd.io/CODE_QUALITY/
- https://systemd.io/ARCHITECTURE/

# Repeatable tasks

- clone the project, build it, add an `Hello World from <name>!` log message to a tool of your choice from `src/`, run it and post a screenshot as proof
- clone the project, build it, pick one tool under `src/` of your choice and run it, inspect the code and in your own word write a paragraph explaining what the code (or a section of the code, some are quite large!) does - note that we don't mean just from the point of view of a user, as that's explained in the manual, but describe the actual code
- study the documentation, and write a paragraph summarizing one of the documents in your own words. Pick at least one medium/large size document, OR at least three smaller ones. For easier viewing, documents under `docs/` are rendered on https://systemd.io/ and documents under `man/` are rendered on https://www.freedesktop.org/software/systemd/man/

# Short tasks
- fix one of the issues labelled as "please-submit-as-pr" https://github.com/systemd/systemd/issues?q=is%3Aopen+is%3Aissue+label%3Aplease-submit-as-pr
- improve an existing unit test `src/test/` to increase code coverage for the basic common code - see under `src/basic/` on https://coveralls.io/github/systemd/systemd
- add a new unit test to cover the 'shared' common code - see under `src/shared/` on https://coveralls.io/github/systemd/systemd
- update outdated executables/daemons to `bus_call_method`/`bus_get_property`: https://github.com/systemd/systemd/issues/20928#issuecomment-933718629
- update outdated executables/daemons to new-style sd-bus macros: https://github.com/systemd/systemd/issues/20928#issuecomment-933733352

# Long tasks
Please note that the description might sound simple, but in reality the task might require more time than you have available. Before starting, state in a comment which issue/TODO you'd like to tackle and how much time you have available, and we'll try to advise on whether it's enough to complete it.

- fix one of the issues labelled as "RFE" https://github.com/systemd/systemd/issues?q=is%3Aopen+is%3Aissue+label%3A%22RFE+%F0%9F%8E%81%22
- fix one of the TODO items https://github.com/systemd/systemd/blob/main/TODO
- add an integration test `test/README.testsuite` for a tool/daemon that is not currently covered

**Comment by DaanDeMeyer** [comment]
Recently, we introduced a less verbose API to call D-Bus methods on systemd services from within systemd tools. This API can be found in the bus-locator.h header file. The API provides methods such as `bus_call_method` and `bus_get_property` that are shorthands for the `sd_bus_call_method` and `sd_bus_get_property` methods respectively. The only different between the `bus` functions from bus-locator.h and the `sd_bus` functions from sd-bus.h is that the `sd_bus` functions take the D-Bus destination, path and interface as separate arguments whereas the `bus` functions take a `BusLocator` object as an argument containing the D-Bus destination, path and interface as members. This ends up being a lot less verbose than using the `sd_bus` functions. There's a bunch of predefined `BusLocator` objects in bus-locator.h that can be passed to the `bus` functions as an argument.

The objective of this task is simple, look inside the codebase to find a tool that's still using the `sd_bus` functions and modify one or more of those calls to use the equivalent `bus` function from bus-locator.h instead. Also make sure the functionality is still working as before. If you don't know how to test the changes, open a PR for the changes and clearly mention that you're not sure how to test the changes and we'll make sure to help you out.

**Comment by DaanDeMeyer** [comment]
Recently, we introduced new macros for declaring D-Bus service methods in sd-bus-vtable.h. This API consists of three new macros: `SD_BUS_METHOD_WITH_ARGS`, `SD_BUS_METHOD_WITH_ARGS_OFFSET` and `SD_BUS_SIGNAL_WITH_ARGS` that replace `SD_BUS_METHOD_WITH_NAMES`, `SD_BUS_METHOD_WITH_NAMES_OFFSET` and `SD_BUS_SIGNAL_WITH_NAMES` respectively. However, many of systemd's services are still using the old macros instead of the new ones.

The objective of this task is to migrate one of systemd's D-Bus services that's still using the old macros to the new macros. Look at https://github.com/systemd/systemd/pull/15605/files to learn how to migrate from the old macros to the new macros. You can also look up the new and old macros in https://www.freedesktop.org/software/systemd/man/sd_bus_add_object_vtable.html# to read their documentation and learn more about how they work. https://www.freedesktop.org/software/systemd/man/sd_bus_message_append.html describes the D-Bus type system in more detail if you'd like to learn more.

**Comment by Redeem-Grimm-Satoshi** [comment]
@bluca Thanks.

**Comment by bluca** [comment]
yes

**Comment by bluca** [comment]
deadline for applications is past now, so closing for now.
