### ISSUE TITLE
Race in simultaneous systemd starts in docker containers results in 219/CGROUP errors

### ISSUE THREAD

**Issue by kanaka** [systemd/systemd#20939]
**systemd version the issue has been seen with**
 > systemd versions tested within the containers: 245.4, 247.3, 248.3, git 249-1195-gc82dc15 (2021-10-03)

**Used distribution**
 > Host distros tested: Ubuntu 16.04, Ubuntu 20.04, NixOS 20.09
 > Container distros tested: Ubuntu 20.04, Ubuntu 21.04, Ubuntu 21.10

**Linux kernel version used** (`uname -a`)

 > `Linux c87bc1b8115f 5.4.99 #1-NixOS SMP Wed Feb 17 09:35:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

> `Linux kanaka 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd reliably starting simultaneously in multiple docker containers

**Unexpected behaviour you saw**
 > Starting multiple docker containers simultaneously with systemd as the init process results in a race that can trigger `219/CGROUP` errors. This can happen for any 0, 1 or more units within those containers and can fail for 0, 1 or more of the containers each time they are started. Adding a sleep to each container to spread out the startup significantly reduces the likelihood.

**Steps to reproduce the problem**
 > Use docker-compose to start 10 identical containers that use systemd for the init process. On a powerful enough host system you should see a failure in at least one container on almost every startup. I have posted example files that I used to reproduce the problem and example failure output at this gist: https://gist.github.com/kanaka/2317db82e525f4d8b59834bf98ca54a5

**Additional program output to the terminal or log subsystem illustrating the issue**

> Example of status from a failing unit:

```text
● ifupdown-pre.service - Helper to synchronize boot up for ifupdown
     Loaded: loaded (/lib/systemd/system/ifupdown-pre.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-10-05 14:20:28 UTC; 41s ago
    Process: 23 ExecStart=/bin/sh -c if [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude=lo)" ] && [ -x /bin/udevadm ]; then udevadm settle; fi (code=exited, status=219/CGROUP)
   Main PID: 23 (code=exited, status=219/CGROUP)
```

> See full journalctl output at gist: https://gist.github.com/kanaka/2317db82e525f4d8b59834bf98ca54a5

**Comment by poettering** [comment]
Docker is not really interested in making cgroups work sanely in a container. Use some other container manager (nspawn, or podman if you want something you can drop-in instead of docker) and things should just work.

If you use Docker, then things are a mess, but this is not really our fault, we document precisely what needs to be done, but unlike any other container manager on the planet they refuse to implement the few things they'd need.

In a way, Docker is an upstream that really doesn't want you to run systemd as payload. 

See: #17320 #18091 …

**Comment by bluca** [comment]
For completeness, these are the documents that describe the interfaces:

https://systemd.io/CONTAINER_INTERFACE/
https://systemd.io/CGROUP_DELEGATION/
