### ISSUE TITLE
Add coredump container support

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#20944]
We should add support to propagate container coredumps into the corresponding container so they can be accessed inside that container. Currently, all coredumps from a container end up on the host system.

To implement this, we can do the following (as suggested by @poettering):

First, make sure we set some new xattr on the root of the cgroup tree. Then, join the namespaces of PID 1 in the container of the crashing process and invoke some binary there. The xattr should encode which binary to invoke (i.e basically implement a per-container core_pattern replacement). To find the correct cgroup with the xattr set, we can do the following; Determine the pid of the crashing process, follow the parent pids of this process, and iteratively check their cgroups all the way to the top. Or in other words: following the pid tree not the cgroup tree, until you find a pid which has cgroup with the right xattr set. When you find a process with a suitable cgroup/xattr, join its pidns, and from there immediately switch to all namespaces of whatever is pid 1 there and dispatch the coredump there. The xattrs could be configured using tmpfiles.d/, by adding a new specifier for the root of the cgroup tree and then adding a drop-in that writes the xattr.

**Comment by dtardon** [comment]
This is fixed by https://github.com/systemd/systemd/pull/29272, isn't it?
