### ISSUE TITLE
systemd-boot is unable to write to EFI variables

### ISSUE THREAD

**Issue by Tachi107** [systemd/systemd#20947]
**systemd version the issue has been seen with**
 > 247.9-4

**Used distribution**
 > Debian Testing (12)

**Linux kernel version used** (`uname -a`)

 > `Linux h1 5.14.0-1-amd64 #1 SMP Debian 5.14.6-2 (2021-09-19) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > systemd-boot should be able to read and set EFI variables; commands like `bootctl random-seed` should write into the proper variable. After installing systemd-boot in the ESP (`/efi`) and booting into the system, `bootctl` should report all the usual stats like firmware, features, etc.

**Unexpected behaviour you saw**
 > bootctl is unable to print any of the values under "`System:`" and "`Current Boot Loader`", and `bootctl random-seed` reports the error below.

**Steps to reproduce the problem**
 > - Buy a new PC (custom built, with an Asus ROG STRIX X470-I motherboard)
> - Update to the latest UEFI BIOS version
> - Boot into the UEFI/BIOS settings and disable CSM, fast boot and secure boot
> - Boot via a bootable USB drive and install Debian 11 **without** installing GRUB
> - Reboot into the bootable USB into rescue mode and install systemd-boot into `/efi` using an interactive shell with root mounted to the root partition of the PC
> - Reboot into the newly installed Debian system
> - Run `bootctl`
> 
> This system never saw neither GRUB nor Windows.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
root@h1:~# LC_ALL=C.UTF-8 SYSTEMD_LOG_LEVEL=debug strace -o log -s 500 -f bootctl random-seed
Found container virtualization none.
Random seed file /efi/loader/random-seed successfully written (512 bytes).
No virtualization found in DMI
UML virtualization not found in /proc/cpuinfo.
No virtualization found in CPUID
Virtualization XEN not found, /proc/xen does not exist
This platform does not support /proc/device-tree
This platform does not support /proc/sysinfo
Found VM virtualization none
Reading EFI variable /sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Failed to update mtime/atime on /sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f, ignoring: Operation not permitted
Successfully initialized system token in EFI variable with 512 bytes.
```
`log` file: https://bin.snopyta.org/?4536d20c47e03aa3#6k47T2b3jpBbgU7cwkzTpvJEno6GsHUZX5nUrM2BbCc1

```text
root@h1:~# LC_ALL=C.UTF-8 SYSTEMD_LOG_LEVEL=debug bootctl --no-pager
Found container virtualization none.
Using EFI System Partition at /efi.
Directory "/boot" is not the root of the file system.
Didn't find an XBOOTLDR partition, using the ESP as $BOOT.
Reading EFI variable /sys/firmware/efi/efivars/LoaderFirmwareType-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderFirmwareType-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderFirmwareInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderFirmwareInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
System:
     Firmware: n/a (n/a)
Reading EFI variable /sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
  Secure Boot: disabled
Reading EFI variable /sys/firmware/efi/efivars/SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
   Setup Mode: user
Reading EFI variable /sys/firmware/efi/efivars/OsIndicationsSupported-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/OsIndicationsSupported-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
 Boot into FW: not supported

Current Boot Loader:
      Product: n/a
     Features: ✗ Boot counting
               ✗ Menu timeout control
               ✗ One-shot menu timeout control
               ✗ Default entry control
               ✗ One-shot entry control
               ✗ Support for XBOOTLDR partition
               ✗ Support for passing random seed to OS
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
               ✗ Boot loader sets ESP partition information
          ESP: n/a
         File: └─n/a

Random Seed:
 Passed to OS: no
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/dfa5889e-1fb3-40e7-a11d-fa9e5d7063eb)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot 247.9-4)
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 247.9-4)

Reading EFI variable /sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
Boot Loaders Listed in EFI Variables:
Boot Loader Entries:
        $BOOT: /efi (/dev/disk/by-partuuid/dfa5889e-1fb3-40e7-a11d-fa9e5d7063eb)

Reading EFI variable /sys/firmware/efi/efivars/LoaderEntryOneShot-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderEntryOneShot-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Found default: last entry "3c394e1743524bc88301894715af92ca-5.14.0-1-amd64.conf"
Default Boot Loader Entry:
        title: Debian GNU/Linux bookworm/sid (5.14.0-1-amd64)
           id: 3c394e1743524bc88301894715af92ca-5.14.0-1-amd64.conf
       source: /efi/loader/entries/3c394e1743524bc88301894715af92ca-5.14.0-1-amd64.conf
      version: 5.14.0-1-amd64
   machine-id: 3c394e1743524bc88301894715af92ca
        linux: /3c394e1743524bc88301894715af92ca/5.14.0-1-amd64/linux
       initrd: /3c394e1743524bc88301894715af92ca/5.14.0-1-amd64/initrd.img-5.14.0-1-amd64
      options: root=UUID=cdd5c668-e0b8-4998-8f81-e6b8acaf7ae8 ro quiet
```

I know this report isn't tecnically valid since the latest released version is 249 and I'm running version 247, but to test on a newer version of systemd I would need to either compile from source or install a package from experimental, and since this is my brother's PC (doesn't know much about computers) I can't really set up a test environment. Also, I believe that this still contains useful information, and looking at the changelog it seems that systemd-boot did not recieve a lot of attention in the latest releases. If you really think that I should test this on a the latest release I can try and see what I can do (maybe something like Fedora on a USB stick).

**Comment by Tachi107** [comment]
> if you look into /sys/firmware/efi/efivars/ what do you see?

Some efivars are present, but no Loader* vars.
```text
root@h1:~# ls /sys/firmware/efi/efivars/
ConIn-8be4df61-93ca-11d2-aa0d-00e098032b8c
ConOut-8be4df61-93ca-11d2-aa0d-00e098032b8c
CurrentPolicy-77fa9abd-0359-4d32-bd60-28f4e78f784b
DeploymentModeNv-97e8965f-c761-4f48-b6e4-9ffa9cb2a2d6
Kernel_ATPSiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
Kernel_EntRevokeSiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
Kernel_RvkSiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
Kernel_SiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
Kernel_SkuSiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
Kernel_WinSiStatus-77fa9abd-0359-4d32-bd60-28f4e78f784b
StdDefaults-4599d26f-1a11-49b8-b91f-858745cff824
```

I'm quite sure sd-boot is used to boot (the installation was the same on other systems of mine, and everything works fine there).
In the "details" section there's just a picture of the sd-boot menu.

<details>

![cca6dea4-463a-47aa-b169-a86435be2a7d](https://user-images.githubusercontent.com/34214253/136249768-ab5a01ea-c496-4393-b5e8-9a7c3ed75d85.jpg)

</details>

**Comment by poettering** [comment]
Are those all efi vars? Not a single Boot* os OsIndications* efi var? that is very weird, and almost certainly broken firmware.

**Comment by poettering** [comment]
Hit the `v` key to see which version of sd-boot you are running.

**Comment by Tachi107** [comment]
`systemd-boot 247.9-4 (x64), UEFI Specification 2.70, Vendor American Megatrends 5.17�` (yes, with the replacement character at the end)

**Comment by Tachi107** [comment]
Not sure if this is useful, but I believe that the system supports TPM 2.0 (CPU is a Ryzen 3600) and it is enabled in the motherboard's settings.

**Comment by medhefgo** [comment]
That would suggest something is wrong with efivarfs...

**Comment by Tachi107** [comment]
root@h1:~# LIBEFIVAR_OPS=vars efivar --list
    efivar: error listing variables: No such file or directory

**Comment by medhefgo** [comment]
Nvm, that one is for an old efivars module that don't exist anymore.

Basically, your kernel does not show every efi var for some reason. Maybe you'll find something in the kernel logs about it. Considering that sd-boot can see and modify them, the bios seems to be working fine. You'll probably have to poke the kernel folks about it. You could also try some different kernels, maybe it's a regression.

**Comment by medhefgo** [comment]
You can't go wrong with debian bug tracker. You can also try the kernel bugzilla.

Or, if you're feeling confident you can go to the kernel people directly (CC these maintainers and the mailing list):
```
M:	Matthew Garrett <matthew.garrett@nebula.com>
M:	Jeremy Kerr <jk@ozlabs.org>
M:	Ard Biesheuvel <ardb@kernel.org>
L:	linux-efi@vger.kernel.org
```

You'll probably want to link this issue in either case.

**Comment by Tachi107** [comment]
Ok, I'll try with Debian first (no, I'm not feeling confident enough haha).
Thank you! I'll update this if needed.
