### ISSUE TITLE
Unit with hotplugged dependency can't be started

### ISSUE THREAD

**Issue by ebiggers** [systemd/systemd#2094]
I did the following:
1. Attach USB network device, creating network interface eth0
2. Start service: dhcpcd@eth0
3. Networking is functional
4. Detach USB network device, removing network interface eth0
5. Reattach USB network device, re-creating network interface eth0

After this, I expected either of the following behaviors, ideally the first one:
- The dhcpcd@eth0 service continues running and re-establishes the connection
- The dhcpcd@eth0 service ends up in a stopped or failed state and can be started again

However, the actual behavior is as follows:
- The dhcpcd@eth0 service ends up in a failed state and _cannot_ be restarted.  systemd just waits while starting the service and never actually starts the dhcpcd process.

Is this really the correct behavior?  I understand that it may be difficult to match up a unit from two different hotplug events, but I found the behavior to be very unintuitive.

**Comment by poettering** [comment]
Well, I have no idea what the dependencies of your service `dhcpcd@.service` are...

And it's completely up to dhcpc whether it will stay running when its interface is gone, hence your first suggestion how that should work isn't up to systemd at all...

If you want youe second suggestion implemented you need to add a dependency from the network device to your service, otherwise you didn't declare in anyway that you want that service started when the device appears. Use the SYSTEMD_WANTS udev prop to express that from the udev rules files. See systemd.device(5) for details.

Either way I see nothing to fix in systemd here: systemd cannot guess which behaviour you want, and accepts what dhcpcd does, and does not implicitly implement automatic restarting.

**Comment by ebiggers** [comment]
These are the dependencies in dhcpcd@.service:

```
BindsTo=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
```

Let's set aside the question of whether systemd will start the service automatically or not.  As I said, I could not restart the service after the re-hotplug.  This was true even if I ran 'systemctl start dhcpcd@eth0'; the command timed out without ever launching the binary.

I suspect that systemd is identifying the network device by sysfs path, not by network interface, and this is causing the unexpected behavior.  If the new "eth0" has a different sysfs path, then systemd doesn't match up the new device with the old one; and the service unit is still referencing the old device as a dependency, even though it's no longer "visible" in systemctl.  Do you agree with this assessment?

If the above is true, I believe this is a systemd bug because the service unit has declared a dependency on a network device name (eth0 in my case) rather than on a particular sysfs path.

**Comment by arvidjaar** [comment]
> I suspect that systemd is identifying the network device by sysfs path, not by network interface, and this
> is causing the unexpected behavior. If the new "eth0" has a different sysfs path, then systemd doesn't
> match up the new device with the old one; and the service unit is still referencing the old device as a
> dependency, even though it's no longer "visible" in systemctl. Do you agree with this assessment?

It is not something to agree or not agree. Please check `systemctl show sys-subsystem-net-devices-%i.device` before and after hotplug.

The same was reported recently for filesystems as well so you are most likely correct in your analysis.

**Comment by ebiggers** [comment]
Starting out with the device attached, I have:

```
# systemctl show sys-subsystem-net-devices-eth0.device
SysFSPath=/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2.2/2-2.2:1.0/net/eth0
Id=sys-subsystem-net-devices-eth0.device
Names=sys-subsystem-net-devices-eth0.device
BoundBy=dhcpcd@eth0.service
Before=dhcpcd@eth0.service
Description=AX88179 Gigabit Ethernet
LoadState=loaded
ActiveState=active
SubState=plugged
...
```

Detached, it becomes:

```
# systemctl show sys-subsystem-net-devices-eth0.device
SysFSPath=/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2.2/2-2.2:1.0/net/eth0
Id=sys-subsystem-net-devices-eth0.device
Names=sys-subsystem-net-devices-eth0.device
BoundBy=dhcpcd@eth0.service
Before=dhcpcd@eth0.service
Description=AX88179 Gigabit Ethernet
LoadState=loaded
ActiveState=inactive
SubState=dead
...
```

Attached using a different USB port, it becomes:

```
# systemctl show sys-subsystem-net-devices-eth0.device
SysFSPath=/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2.2/2-2.2:1.0/net/eth0
Id=sys-subsystem-net-devices-eth0.device
Names=sys-subsystem-net-devices-eth0.device
BoundBy=dhcpcd@eth0.service
Before=dhcpcd@eth0.service
Description=AX88179 Gigabit Ethernet
LoadState=loaded
ActiveState=inactive
SubState=dead
...
```

It seems to be stuck on the "old" device, even though the "new" device has the same network interface name.  At the end, the directory in SysFSPath no longer exists; the real path which actually exists is /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1.2/2-1.2:1.0/net/eth0.  Note the 2-1 instead of the 2-2.

I did not do anything with dhcpcd@eth0 during the process, although it was sitting in a failed state from earlier --- which is apparently enough to make it permanently "bound" to the old device by sysfs path.

The expected behavior, I think, is that an alias such as "eth0" be automatically updated when necessary to refer to a different physical device, as reported by the kernel.  I don't yet know enough about systemd to know whether this is difficult from a technical standpoint.
