### ISSUE TITLE
systemctl -M machine status - shows cgroups from parent

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#20958]
**systemd version the issue has been seen with**
 > 249.4-2-arch

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)
 > `5.14.6-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemctl -M container status` should show me the cgroups and processes running in the specified container

**Unexpected behaviour you saw**
 > it shows the cgroups and processes from the parent host instead

**Comment by mikhailnov** [comment]
Confirm this with systemd-249-1.gitfab79a.1.x86_64 on rosa2021.1

```diff
[root@srv1-1cloud-miran rootfs-scripts]# diff -u --color <(systemctl -M coturn status) <(systemctl status)
--- /dev/fd/63	2021-10-09 11:33:37.925155085 +0300
+++ /dev/fd/62	2021-10-09 11:33:37.925155085 +0300
@@ -1,8 +1,8 @@
-● coturn
-    State: degraded
+● srv1-1cloud-miran.infrastructure.dumalogiya.ru
+    State: running
      Jobs: 0 queued
-   Failed: 1 units
-    Since: Mon 2021-10-04 17:20:05 MSK; 4 days ago
+   Failed: 0 units
+    Since: Mon 2021-10-04 17:20:00 MSK; 4 days ago
    CGroup: /
            ├─2229697 bpfilter_umh
            ├─user.slice
```
