### ISSUE TITLE
[logind] Unhelpfull FileExist potentially returned by CreateSession

### ISSUE THREAD

**Issue by JulienPalard** [systemd/systemd#20956]
While poking a bug in an old systemd release (so I won't open an issue about it, it may have been fixed by now) I noticed a potential problem in logind source code that I can still see in the main branch:

In `logind-dbus.c`, `method_create_session` there's a call for `manager_add_session` itself calling `session_new`, itself calling `hashmap_put`. This chain cleanly return the errors to the callee, and to DBus.

But `hashmap_put` can return `EEXIST`, which translate in a FileExist error from the DBus caller point of view, which could be more explicit: issue is not that a file exists, but a key is unexpectedly present in an hashtable.

Maybe `hashmap_put` callers should check the return value against `EEXIST` and translate it to a more verbose error according to the context?

In my good old version of systemd, this translates to:

    Oct  7 14:35:12 staging sshd[13361]: pam_systemd(sshd:session): Failed to create session: File exists

in `/var/log/auth.log`.

**Comment by samuelfusato** [comment]
Hi @JulienPalard,

From a user point of view, searching a culprit file is not the right path then?

```
systemd[1]: user-runtime-dir@0.service: Succeeded.
systemd[1]: Stopped User Runtime Directory /run/user/0.
systemd[1]: Removed slice User Slice of UID 0.
sudo:   icinga : PWD=/ ; USER=root ; COMMAND=/usr/local/bin/nagios/check_sap_clients.scr
sudo: pam_systemd(sudo:session): Failed to create session: File exists   <--- here
sudo: pam_unix(sudo:session): session opened for user root by (uid=476)
sudo: pam_unix(sudo:session): session closed for user root
sudo:   icinga : PWD=/ ; USER=root ; COMMAND=/usr/local/bin/nagios/check_linux_memory.sh
systemd[1]: Created slice User Slice of UID 0.
systemd[1]: Starting User Runtime Directory /run/user/0...
```

Is there any way I can track the reason for this message?

Here is apparently the corresponding part of the code:

```
            /* We are already in a session, don't do anything */
            goto success;
        } else {
            pam_syslog(handle, LOG_ERR, "Failed to create session: %s", bus_error_message(&error, r));
            return PAM_SESSION_ERR;
        }
```

Thank you.

**Comment by JulienPalard** [comment]
> From a user point of view, searching for a culprit file is not the right path then?

No, the culpit is an entry in an hashtable. Probably triggered by this line in your case if you landed in this issue, but who knows:

https://github.com/systemd/systemd/blob/729d2df8065ac90ac606e1fff91dc2d588b2795d/src/login/logind-session.c#L81
