### ISSUE TITLE
Document $PASSWORD variable for systemd-cryptenroll

### ISSUE THREAD

**Issue by ymatsiuk** [systemd/systemd#20955]
I might be missing something out, but can't find anywhere [this](https://github.com/systemd/systemd/blob/7a6abbe93762fe23d415144ae7a040df3266bb5f/src/cryptenroll/cryptenroll.c#L422) documented.

Very useful feature for non-interactive systemd testing:
```
PASSWORD=lukspass systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7 /dev/vdb"
```

Can we rely on this functionality?

**Comment by poettering** [comment]
you may rely on it, but it's not a great feature tbh because env vars are terrible way to pass secret stuff. It's mostly a testing feature, not something to actually use

**Comment by poettering** [comment]
> Instead of $PASSWORD (which is for test purpose),is it possible for systemd-cryptenroll to support reading a passphrase from a file similar to cryptsetup using "--key-file"?

Yeah, we should add that. Please file an RFE issue requesting that.
