### ISSUE TITLE
RFE: Support reading passphrase from file when using systemd-cryptenroll

### ISSUE THREAD

**Issue by rittet** [systemd/systemd#20961]
**Is your feature request related to a problem? Please describe.**
systemd-cryptenroll does not support reading a passphrase from a file, instead it always needs to be entered manually. 

**Describe the solution you'd like**
A solution similar to `cryptsetup --key-file=` to read a passphrase  from a file.

**Describe alternatives you've considered**
Using $PASSWORD. See [#20955](https://github.com/systemd/systemd/issues/20955). (Which is not optimal).

**The systemd version you checked that didn't have the feature you are asking for**
systemd 249 (249.4-2-arch)

**Comment by j5k** [comment]
I need also something like that. At the moment I have the following workaround for silent cryptenroll:

```
/bin/expect <(cat << EOF
spawn systemd-cryptenroll ${LUKS_PARTITION} --password
expect "current passphrase" { send "${CURRENT_PWD}\r" }
expect "new passphrase" { send "${PWD1}\r" }
expect "(repeat)" { send "${PWD2}\r" }
interact
EOF
) $> /dev/null
```

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/24138
