### ISSUE TITLE
DEEPIN deepin execute systemctl start xxxxx.service No message will be returned,

### ISSUE THREAD

**Issue by pgy866** [systemd/systemd#20972]
deepin execute systemctl start xxxxx.service systemctl stop xxxxx.service
No message will be returned, a flashing cursor appears, use "sudo systemctl status xxxxx.service" to check that the service has been started or shut down correctly

deepin 执行systemctl start xxxxx.service    systemctl stop xxxxx.service
不会回显任何消息，出现一个光标闪动，用“sudo systemctl status xxxxx.service”检查其实服务已经正确的启动或关闭。

PS： Deepin 20 Community Linux version 5.13.13-amd64-desktop (root@uos-PC) (gcc (Uos 8.3.0.3-3+rebuild) 8.3.0, GNU ld (GNU Binutils for Uos) 2.31.1) #1 SMP Tue Aug 31 18:01:11 CST 2021

![截图_选择区域_20211010175035](https://user-images.githubusercontent.com/28694676/136690846-4572473e-e124-4586-aa87-d38c0ca62c92.png)
![截图_选择区域_20211010175018](https://user-images.githubusercontent.com/28694676/136690862-6598c6d1-1037-487e-9cc3-95ffe141cb94.png)

![截图_选择区域_20211010174958](https://user-images.githubusercontent.com/28694676/136690871-a4407157-6a2b-4e36-bfa2-643d57d1ae71.png)

**Comment by yuwata** [comment]
Please contact to your distro. v241 is too old here.
