### ISSUE TITLE
systemd limits maximum length of input line in unit file to 2048 bytes 

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#2099]
The problem is basically the $subject. User complains that on system with a lot of initscripts it may happen that `systemd-sysv-generator` generates unit files containing ordering dependency definitions (`After=`) with length exceeding maximum for input line in unit files.

Easiest workaround/fix is bumping `LINE_MAX`.  I guess that proper solution would be to stop using `fgets()` for line oriented input and start using `getline()`.

**Comment by msekletar** [comment]
@poettering any thoughts on this?

**Comment by ptman** [comment]
Where is this documented?
