### ISSUE TITLE
systemd-networkd fails to start before dbus.socket with selinux enabled

### ISSUE THREAD

**Issue by yaneti** [systemd/systemd#21009]
**systemd version the issue has been seen with**
 > systemd-248.7-1.fc34.x86_64

Here is a debug log of systemd-networkd trying to start and failing, when it tries to do it before the system dbus is available (/run/dbus/system_bus_socket is still not there)
```
....
Oct 14 18:19:00 kofa1 audit[599]: AVC avc:  denied  { watch } for  pid=599 comm="systemd-network" path="/" dev="dm-0" ino=2 scontext=system_u:system_r:systemd_networkd_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=0
Oct 14 18:19:00 kofa1 audit[599]: SYSCALL arch=c000003e syscall=254 success=no exit=-13 a0=e a1=7f7726cd6a3e a2=180 a3=55cf7a7bcf40 items=0 ppid=1 pid=599 auid=4294967295 uid=996 gid=992 euid=996 suid=996 fsuid=996 egid=992 sgid=992 fsgid=992 tty=(none) ses=4294967295 comm="systemd-network" exe="/usr/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)
....
Oct 14 18:19:00 kofa1 systemd-networkd[599]: SELinux enabled state cached to: enabled
Oct 14 18:19:00 kofa1 systemd-networkd[599]: sd-device-monitor: Failed to stat PID1's netns: No such file or directory
Oct 14 18:19:00 kofa1 systemd-networkd[599]: Bus bus-api-network: changing state UNSET → OPENING
Oct 14 18:19:00 kofa1 systemd-networkd[599]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Oct 14 18:19:00 kofa1 systemd-networkd[599]: Failed to add inotify watch on /: Permission denied
Oct 14 18:19:00 kofa1 systemd-networkd[599]: Bus bus-api-network: changing state OPENING → CLOSED
Oct 14 18:19:00 kofa1 systemd-networkd[599]: Failed to connect to bus: Permission denied
Oct 14 18:19:00 kofa1 systemd-networkd[599]: Could not connect to bus: Permission denied
Oct 14 18:19:00 kofa1 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 18:19:00 kofa1 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
...
```

One can workaround with  enforcing=0  or with a snippet:
```
[Unit]
After=dbus.socket
```

The logic for trying to watch for something that's probably administratively prohibited doesn't seem optimal
path="/" dev="dm-0"   is because root is on a lvm volume..

**Comment by yaneti** [comment]
> The issue seems to be an issue in watching DBus socket. Maybe, if SELinux prohibit watching DBus socket, then we should fallback to timer based retrying logic (, or any other better idea?).

The policy allows systemd_networkd_t to work the DBus socket. It doesn't allow watching random paths (/) for when the socket appears. 
Which I think is reasonable.

**Comment by doverride** [comment]
I guess this part: "we just subscribe to relevant changes to all prefix components of the path" of https://github.com/systemd/systemd/blob/v249/src/libsystemd/sd-bus/bus-socket.c#L712 can maybe be improved. Is it really necessary to "subscribe to changes to all components of the path" instead of just subscribing to something a bit more specific like the sock file itself and maybe its direct parent but not /run and /?

**Comment by doverride** [comment]
in the end though this is a SELinux policy issue regardless because even if this would be changed (preferably resolved, timsyncd and networkd shouldnt depend on DBUS at all), SELinux policy would still need to deal with compatibility.

**Comment by poettering** [comment]
i am sorry, but a policy that disallows networkd to install an inotify watch on the root fs is a broken policy.

**Comment by yaneti** [comment]
I filed the bug because I don't really agree that being allowed to watch the rootfs is really something that systemd services should die on. But hey...

https://bugzilla.redhat.com/show_bug.cgi?id=1970359
