### ISSUE TITLE
Unit dropin load order surprising

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2103]
I just found out the following:

``` shell
% systemctl cat dropin 
# /lib/systemd/system/dropin.service
[Unit]
Description=dropin

[Service]
Type=oneshot
ExecStart=/bin/true

# /lib/systemd/system/dropin.service.d/99-override.conf
[Unit]
After=network-online.target
% sudo systemctl edit --full dropin
# save with the same contents
% systemctl show -pAfter dropin
After=basic.target system.slice sysinit.target network-online.target systemd-journald.socket
```

In short, a vendor dropin is not overriden by a full admin unit. I find this very unintuitive. So, either systemd should be fixed to not load dropins from later in the search path after a unit has been found, or  this should be documented in the systemd.unit manpage. If the latter, then having `systemctl edit --full` automatically mask all dropins would be great as well.

**Comment by poettering** [comment]
drop-ins area not really supposed to be used by "vendors"... they are a way how admins/users extend their stuff... And if you do use them, then the usual logic of ordering, and masking via /dev/null is in effect...

**Comment by poettering** [comment]
But yeah, we should document that better and more clearly.

**Comment by fsateler** [comment]
I disagree that vendors would not use drop-in area. This is a very reasonable way for packages to provide default configuration for other packages. Alternatively, if drop-in area is not supposed to be used by vendors, then there should be no drop-in area in /usr. Why provide a drop-in area for vendors if vendors are not supposed to use it?

For files with only key-value pairs (like eg, journald.conf), it makes much less sense to have masking logic. They should be just merged in a reasonable order, and my claim is that having all files in /etc be parsed after files in /usr (so that they always take precedence, regardless of file name), is a more reasonable scheme than having `/etc/.../00-setting.conf` be overriden by `/usr/.../99-setting.conf`

**Comment by mbiebl** [comment]
2015-12-18 21:01 GMT+01:00 Felipe Sateler notifications@github.com:

> I disagree that vendors would not use drop-in area. This is a very
> reasonable way for packages to provide default configuration for other
> packages. Alternatively, if drop-in area is not supposed to be used by
> vendors, then there should be no drop-in area in /usr. Why provide a
> drop-in area for vendors if vendors are not supposed to use it?

I have to agree here. Having a simple way for a vendor to ship a default
configuration which differs from the upstream default by means of having a
drop-in, sounds like a very useful thing to have.

@Lennart, are you suggesting that vendors should patch the code instead?
That seems like a step backwards.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by poettering** [comment]
Hmm, OK, I think in some cases it indeed makes sense to do vendor drop-ins.

But I think in that case disabling this should really require masking, hence I still think this is a documentation issue, and we shouldn't change behaviour here...

**Comment by keszybz** [comment]
systemd.unit(5) now says:

```
   In addition to /etc/systemd/system, the drop-in ".d" directories for system
   services can be placed in /usr/lib/systemd/system or /run/systemd/system
   directories. Drop-in files in /etc take precedence over those in /run which in
   turn take precedence over those in /usr/lib. Drop-in files under any of these
   directories take precedence over unit files wherever located. (Of course, since
   /run is temporary and /usr/lib is for vendors, it is unlikely drop-ins should be
   used in either of those places.)
```

So the precedence is clear. If the text needs further tweaking, it should be done in separate PRs.
