### ISSUE TITLE
Network Service failed occasionally

### ISSUE THREAD

**Issue by Joakim-Zhang** [systemd/systemd#21048]
**systemd version the issue has been seen with**
 > v247

**Used distribution**
 > Yocto

**Linux kernel version used** (`uname -a`)

 > Linux imx8mpevk 5.15.0-rc2-lts-next+g5e80e4e777ba #1 SMP PREEMPT Tue Sep 28 10:17:35 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**CPU architecture issue was seen on**
 > arm64

**Expected behaviour you didn't see**
 > Network Service success

**Unexpected behaviour you saw**
 > Starting Network Service...
[FAILED] Failed to start Network Service.
See 'systemctl status systemd-networkd.service' for details.
[  OK  ] Stopped Network Service.
         Starting Network Service...
[FAILED] Failed to start Network Service.
See 'systemctl status systemd-networkd.service' for details.
[  OK  ] Stopped Network Service.
         Starting Network Service...
[    **] A start job is running for Network Service (5min 25s / 6min)

It will continue restart the Network Service then failed...

**Steps to reproduce the problem**
 >  tftpboot kernel then mount network rootfs, do stress test, it will show occasionally.

**Additional program output to the terminal or log subsystem illustrating the issue**

When it successed:
......
Mar 24 10:25:22 imx8mpevk systemd[409]: systemd-networkd.service: Executing: /lib/systemd/systemd-networkd
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: sd-device-monitor: Failed to stat PID1's netns: No such file or directory
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: Bus bus-api-network: changing state UNSET → OPENING
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: Bus bus-api-network: changing state OPENING → AUTHENTICATING
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Mar 24 10:25:22 imx8mpevk systemd[1]: systemd-networkd.service: Got notification message from PID 409 (WATCHDOG=1)
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: timestamp of '/etc/systemd/network' changed
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: No virtualization found in DMI
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: UML virtualization not found in /proc/cpuinfo.
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: No virtualization found in CPUID
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: Virtualization XEN not found, /proc/xen does not exist
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: No virtualization found in /proc/device-tree/*
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: This platform does not support /proc/sysinfo
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: Found VM virtualization none
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: /lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: /lib/systemd/network/80-wired.network: Conditions in the file do not match the system environment, skipping.
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: New device has no master, continuing without
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Hardware address not found for new device, continuing without
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Broadcast address not found for new device, continuing without
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Permanent MAC address not found for new device, continuing without: Operation not supported
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Flags change: +NOARP +ECHO
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Link 4 added
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: udev initialized link
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: State changed: pending -> initialized
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: can0: Saved original MTU: 16
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: New device has no master, continuing without
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: Link 3 added
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: udev initialized link
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: State changed: pending -> initialized
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth1: Saved original MTU: 1500
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: New device has no master, continuing without
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: Flags change: +MULTICAST +BROADCAST
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: Link 2 added
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: udev initialized link
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: State changed: pending -> initialized
Mar 24 10:25:22 imx8mpevk systemd-networkd[409]: eth0: Saved original MTU: 1500
......
when it failed:
......
Mar 24 10:25:22 imx8mpevk systemd[475]: systemd-networkd.service: Executing: /lib/systemd/systemd-networkd
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: sd-device-monitor: Failed to stat PID1's netns: No such file or directory
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: Bus bus-api-network: changing state UNSET → OPENING
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: Bus bus-api-network: changing state OPENING → AUTHENTICATING
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: timestamp of '/etc/systemd/network' changed
Mar 24 10:25:22 imx8mpevk systemd[1]: systemd-networkd.service: Got notification message from PID 475 (WATCHDOG=1)
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: No virtualization found in DMI
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: UML virtualization not found in /proc/cpuinfo.
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: No virtualization found in CPUID
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: Virtualization XEN not found, /proc/xen does not exist
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: No virtualization found in /proc/device-tree/*
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: This platform does not support /proc/sysinfo
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: Found VM virtualization none
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: /lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Mar 24 10:25:22 imx8mpevk systemd-networkd[475]: /lib/systemd/network/80-wired.network: Conditions in the file do not match the system environment, skipping.
Mar 24 10:26:52 imx8mpevk systemd[1]: systemd-networkd.service: start operation timed out. Terminating.
Mar 24 10:26:52 imx8mpevk systemd[1]: systemd-networkd.service: Changed start -> stop-sigterm
Mar 24 10:28:22 imx8mpevk systemd[1]: systemd-networkd.service: State 'stop-sigterm' timed out. Killing.
Mar 24 10:28:22 imx8mpevk systemd[1]: systemd-networkd.service: Killing process 475 (systemd-network) with signal SIGKILL.
Mar 24 10:28:22 imx8mpevk systemd[1]: systemd-networkd.service: Changed stop-sigterm -> stop-sigkill
Mar 24 10:29:52 imx8mpevk systemd[1]: systemd-networkd.service: Processes still around after SIGKILL. Ignoring.
Mar 24 10:29:52 imx8mpevk systemd[1]: systemd-networkd.service: Changed stop-sigkill -> final-sigterm
Mar 24 10:31:23 imx8mpevk systemd[1]: systemd-networkd.service: State 'final-sigterm' timed out. Killing.
Mar 24 10:31:23 imx8mpevk systemd[1]: systemd-networkd.service: Killing process 475 (systemd-network) with signal SIGKILL.
Mar 24 10:31:23 imx8mpevk systemd[1]: systemd-networkd.service: Changed final-sigterm -> final-sigkill
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Processes still around after final SIGKILL. Entering failed mode.
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Failed with result 'timeout'.
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Unit process 475 (systemd-network) remains running after unit stopped.
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Service will restart (restart setting)
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Changed final-sigkill -> failed
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Failed to destroy cgroup /system.slice/systemd-networkd.service, ignoring: Device or resource busy
Mar 24 10:32:53 imx8mpevk systemd[1]: systemd-networkd.service: Job 119 systemd-networkd.service/start finished, result=failed
Mar 24 10:32:53 imx8mpevk systemd[1]: Failed to start Network Service.
......

Debug found:
I tried to add some logs to debug this issue, finally I found, 
https://github.com/systemd/systemd/blob/main/src/network/networkd-manager.c#L599

it can run to sd_netlink_call() this function (I added log before this function and it print out), then it never runs into sd_netlink_call() (I added log in this function, and never print out), it's so strange.

Hi experts, do you have any suggestions? Thanks in advance!

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
