### ISSUE TITLE
Udev provides incomplete information when the wwan interface is moved in a new namespace

### ISSUE THREAD

**Issue by bogdanr** [systemd/systemd#21047]
**systemd version the issue has been seen with**
 > 248.9

**Used distribution**
 > Debian 10

**Linux kernel version used** (`uname -a`)

 > `5.10.0-0.bpo.8-amd64`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Moving the wwan interface from the default namespaces to a new namespace should allow UDEV to provide the same information to userspace, in the new namespace of course

**Unexpected behaviour you saw**
 > After the wwan interface is moved to a new namespace udev doesn't provide all the information to userspace in the new namespace

**Steps to reproduce the problem**
 >   ip netns add sim1
 >   ip link set wwan0 netns sim1
 >   ip netns exec sim1 bash
 >   udevadm info /sys/class/net/wwan0

**Additional program output to the terminal or log subsystem illustrating the issue**

udevadm info in the default namespace:
```P: /devices/pci0000:00/0000:00:15.0/usb2/2-4/2-4:1.8/net/wwp0s21u4i8
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/usb2/2-4/2-4:1.8/net/wwp0s21u4i8
E: DEVTYPE=wwan
E: INTERFACE=wwan0
E: IFINDEX=10
E: SUBSYSTEM=net
E: USEC_INITIALIZED=37010836
E: ID_NET_NAMING_SCHEME=v240
E: ID_NET_NAME_PATH=wwp0s21u4i8
E: ID_VENDOR=Sierra_Wireless__Incorporated
E: ID_VENDOR_ENC=Sierra\x20Wireless\x2c\x20Incorporated
E: ID_VENDOR_ID=1199
E: ID_MODEL=Sierra_Wireless_EM7565_Qualcomm®_Snapdragon™_X16_LTE-A
E: ID_MODEL_ENC=Sierra\x20Wireless\x20EM7565\x20Qualcomm®\x20Snapdragon™\x20X16\x20LTE-A
E: ID_MODEL_ID=9091
E: ID_REVISION=0006
E: ID_SERIAL=Sierra_Wireless__Incorporated_Sierra_Wireless_EM7565_Qualcomm®_Snapdragon™_X16_LTE-A_UF93759052021546
E: ID_SERIAL_SHORT=UF93759052021546
E: ID_TYPE=generic
E: ID_BUS=usb
E: ID_USB_INTERFACES=:ffffff:ff0000:
E: ID_USB_INTERFACE_NUM=08
E: ID_USB_DRIVER=qmi_wwan
E: ID_VENDOR_FROM_DATABASE=Sierra Wireless, Inc.
E: ID_MM_CANDIDATE=1
E: ID_PATH=pci-0000:00:15.0-usb-0:4:1.8
E: ID_PATH_TAG=pci-0000_00_15_0-usb-0_4_1_8
E: ID_NET_DRIVER=qmi_wwan
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=wwan0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/wwp0s21u4i8 /sys/subsystem/net/devices/wwp0s21u4i8
E: TAGS=:systemd:
```

udevadm info in the new namespace:
```P: /devices/pci0000:00/0000:00:15.0/usb2/2-4/2-4:1.8/net/wwp0s21u4i8
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/usb2/2-4/2-4:1.8/net/wwp0s21u4i8
E: DEVTYPE=wwan
E: INTERFACE=wwp0s21u4i8
E: IFINDEX=13
E: SUBSYSTEM=net
```

This only happens with the wwan interface, not with wired interfaces.

**Comment by yuwata** [comment]
If I remember correctly, `/sys` does not support netns, and udev cannot handle interfaces in non-main netns. 
@poettering Is it correct?

**Comment by poettering** [comment]
Yes, /sys/ is not properly virtualized for namespaces. You cannot use udev for stuff you moved out of the main namespace. Sorry.

This is a limitation of the kernel. The only way we could address that is if there was a way to properly virtualize /sys/ for other namespaces, but as long as the kernel doens't provide infra for that we cannot address that. 

If you want this to change please work with the kernel community, but others requested this before, and it was never particularly welcome an idea.

Sorry!
