### ISSUE TITLE
Req: Make advanced CAKE shaper parameters configurable (tc-cake)

### ISSUE THREAD

**Issue by tokred** [systemd/systemd#21043]
**Is your feature request related to a problem? Please describe.**
It is great that systemd can apply various traffic shapers for network devices, e.g. via `[CAKE]` section in `.network` files.

Sadly, for CAKE algorithm only the absolute rudimentary parameters `OverheadBytes` and `Bandwidth` (besides the qdisc's `Parent` and `Handle`) are exposed via `.network` files and configurable right now, and advanced features are inaccessible.

Examples of missing/unexposed config parameters are `nat`/`nonat`, `wash`/`nowash`, `split-gso`, `docsis`, `diffserv*` and various others, which make a shaper algorithm like CAKE much more tunable to individual needs.

**Describe the solution you'd like**
It would be great if either the parameters/flags provided by CAKE are added to `.network`'s `[CAKE]` section, OR if a single "generic" parameter `CakeParameters=` (e.g.) is added where such flags/parameters could be added as "free-form" concatenated string, e.g. `CakeParameters=nat nowash docsis`.

**Describe alternatives you've considered**
Not using systemd's shaper configuration but manually applying it via `tc(8)`.

**The systemd version you checked that didn't have the feature you are asking for**
v249

Respectfully tagging @yuwata as committer of tc support

**Comment by Farom** [comment]
It would be really useful if there were options for setting RTT and atm / ptm / noatm.

**Comment by yuwata** [comment]
I am working on this. WIP branch is https://github.com/yuwata/systemd/commits/network-tc-cake.

**Comment by yuwata** [comment]
Waiting in #21226.

**Comment by CallMeR** [comment]
Are the following parameters missing from the configurable parameters of cake?

- CAKE_RTT
- CAKE_ACK_FILTER

**Comment by yuwata** [comment]
> Are the following parameters missing from the configurable parameters of cake?
> 
>     * CAKE_RTT
> 
>     * CAKE_ACK_FILTER

Yeah. Opened as #25378.

**Comment by CallMeR** [comment]
> > Are the following parameters missing from the configurable parameters of cake?
> > ```
> > * CAKE_RTT
> > 
> > * CAKE_ACK_FILTER
> > ```
> 
> Yeah. Opened as #25378.

I'm curious, this function does not exist under the v252 branch of the Systemd-Stable repository, but the latest Debian12 still uses v252, so will this function be ported to v252?
