### ISSUE TITLE
RFE: add exit-on-idle to systemd-socket-proxyd

### ISSUE THREAD

**Issue by ticpu** [systemd/systemd#2106]
After experimenting with socket activation, I found out that if I use StopWhenUnneeded on the proxy, it gets killed right away.

An option could be added to the proxy so that it terminates itself after a user-defined amount of time without any connection. That way, CPU hungry process can be stopped when no one is using them, for example, VLC streaming from a camera.

**Comment by ticpu** [comment]
If anyone is interested, I can make a pull request for this. Should this be implemented as a switch in systemd-socket-proxyd?

**Comment by poettering** [comment]
Hmm, I think you are mixing up StopWhenUnneeded= and the concept of exit-on-idle. The former is purely about unit dependencies, and hence does not take into account whether there are any connections in progress or not, hence you see the effect that the unit is immediately stopped if you use this.

Exit-on-idle would mean that the daemon exits on its own when there are no more connections going on. I think that would make a ton of sense to add, hence will turn this bug into an RFE for that, under the assumption that that's what you actually are asking for.

**Comment by poettering** [comment]
systemd-socket-proxyd has been removed from the rep, closing this bug.

**Comment by fsateler** [comment]
@poettering this appears to have been closed by mistake: the bus proxy is gone, but the socket proxy is [still here](https://github.com/systemd/systemd/blob/dc3b8afb93f188f212218487ab62fd3f12a2b58f/src/socket-proxy/socket-proxyd.c).

**Comment by poettering** [comment]
oh, ouch, indeed.
