### ISSUE TITLE
merge performance & measurement patches from https://clearlinux.org

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#211]
So starting to rebase our patch series on to master, and it's not fun. A bunch of things could be upstreamed, and then I would need to care about less patches.

There is a bulk of patches that either:
- speed up execution
- allow measuring fast execution

It's small one-liner patches, which do speed-up boot. Given that we boot in sub-second time, we also had to add patches to logging/bootchart to display stuff in "ms" rather than seconds.

I will push a few small patches related to this, for a quick "yea or nay". All of them will reference this issue. If you are happy to take them, do take them. Otherwise, I will not advocate much to take them in, and will just continue maintaining them downstream.

**Comment by poettering** [comment]
I guess we can close this issue now. the referenced patches where either merged or closed, the issue hence has no purpose.

If there are more patches coming, just post them as individual PRs, no need for an issue.
