### ISSUE TITLE
Route not set for DHCPv6-PD assigned prefix with networkd

### ISSUE THREAD

**Issue by gertvdijk** [systemd/systemd#21101]
**systemd version the issue has been seen with**
 > 249.5

**Used distribution**
 > Debian Bullseye with systemd built from unstable

**Linux kernel version used** (`uname -a`)

 > `5.10.0-9-amd64` (Debian Bullseye)

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Set a route for the obtained IPv6 prefix through DHCPv6 Prefix Delegation.

**Unexpected behaviour you saw**
> An `unreachable` route is added to the kernel routing table on the `lo` interface:
> ```
> # ip -6 route
> [...]
> unreachable 2001:1c00:1234:db80::/60 dev lo proto dhcp metric 1024 pref medium
> [...]
> ```

**Steps to reproduce the problem**
ISP network setting:

```
[Network]
Description=ISP WAN interface to CPE
VLAN=wan0
LinkLocalAddressing=ipv6
LLDP=no
EmitLLDP=no
IPv6AcceptRA=yes
IPv6SendRA=no
# Enables both DHCPv4 and DHCPv6 together with the IPv6AcceptRA.DHCPv6Client setting.
DHCP=yes

[DHCPv4]
Hostname=myhostname
UseHostname=no
UseDNS=no
UseNTP=no
UseSIP=no
UseRoutes=no
UseGateway=yes

[DHCPv6]
UseHostname=no
UseDNS=no
UseNTP=no
# Without this, the modem won't reply with a IA_PD in it. Sigh.
ForceDHCPv6PDOtherInformation=yes

[IPv6AcceptRA]
UseDNS=no
DHCPv6Client=yes
```

Downstream client LAN network settings:

```
[Network]
Description=LAN for client hosts, with IPv4, IPv6-ULA and IPv6-global prefix via ISP-delegated prefix 
VLAN=clients0
LinkLocalAddressing=ipv6
LLDP=no
EmitLLDP=no
IPv6AcceptRA=no
IPv6SendRA=yes
# Announces a DHCPv6-PD prefix (DHCPv6PrefixDelegation.SubnetId) from the pool and assigns one to this network.
DHCPv6PrefixDelegation=yes

[Address]
Address=10.1.2.1/24

[IPv6SendRA]
EmitDNS=no
EmitDomains=no

[IPv6Prefix]
# Local address (ULA)
Prefix=fd58:22a0:d6b5:3200::/64

[DHCPv6PrefixDelegation]
SubnetId=0x1
```

**Additional program output to the terminal or log subsystem illustrating the issue**

Logs show that the prefix is obtained, distributed and assigned just fine:

```
systemd-networkd[1767179]: wan0: DHCP6: received PD Prefix 2001:1c00:1234:db80::/60
systemd-networkd[1767179]: clients0: DHCPv6-PD address 2001:1c00:1234:db81:36e6:d7ff:fe1b:48fe/64 (valid for 16h, preferred for 8h)
```

However, the route added on the host/router does not work (marked unreachable, on lo) and the hosts have no IPv6 connectivity.

```
# ip -6 route
[...]
unreachable 2001:1c00:1234:db80::/60 dev lo proto dhcp metric 1024 pref medium
[...]
```

Is this expected behavior?

**Comment by tokred** [comment]
I know this is a closed issue, but just for reference in case someone stumbles over the unreachable route for PD:

This is very much intentional to prevent a forwarding loop: As soon as subnets (e.g. /64) of the delegated prefix (e.g. /56) are assigned to internal networks, the more-specific route(s) take precedence. But if the unreachable route for the _entire_ delegated prefix would not be set on a Customer Edge router, packets to unreachable/unassigned subnets within the delegated prefix would be returned to the default gateway (which itself has a route to the CE router => loop). See RFC 7084, WPD-5 requirement.

**Comment by yuwata** [comment]
@tokred Thank you for the clarification.

If you still have any issues on prefix delegation. Please open a new issue.
