### ISSUE TITLE
networkd can't handle interfaces autoconfigured by the kernel (PXE boot)

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#21105]
**systemd version the issue has been seen with**
 > systemd 249 (249.5-2-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > The DNS servers supplied in DHCP response were not set up for use, so I cannot resolve private hostnames on the local network, as the local DNS servers are not consulted.

**Unexpected behaviour you saw**
 > Only fallback DNS servers were set up, such as 8.8.8.8.

**Steps to reproduce the problem**
 > Boot the kernel with autoconfiguration enabled, e.g. with the `ip=dhcp` command line parameter.

**Additional program output to the terminal or log subsystem illustrating the issue**

I am booting the machine via PXE.  It mounts its root filesystem via NFS, however in order to do this the kernel autoconfiguration feature must be used (`ip=dhcp` parameter).  This allows the kernel to query the DHCP server and configure the network interface before the root filesystem is mounted, so that it can mount it via NFS.  This part works fine.

Once the kernel has booted, I am using systemd-networkd to take over the interface, however it seems to refuse to do so.  `networkctl` just shows it as 'pending' forever:
```
# networkctl
IDX LINK   TYPE     OPERATIONAL SETUP    
  1 lo     loopback carrier     unmanaged
  2 eth0   ether    routable    pending
```
`systemd-udevd` complains that the interface is busy so it can't rename it, a problem I can live with, however neither `systemd-networkd` nor `systemd-resolved` seem to complain, but despite that, they don't set the right DNS servers.  My DHCP server shows that they aren't querying it either.
```
# journalctl -u systemd-udevd
systemd-udevd[250]: eth0: Failed to rename network interface 2 from 'eth0' to 'enp0s25': Device or resource busy
systemd-udevd[250]: eth0: Failed to process device, ignoring: Device or resource busy

# journalctl -u systemd-networkd
systemd[1]: Starting Network Configuration...
systemd-networkd[475]: eth0: Link UP
systemd-networkd[475]: eth0: Gained carrier
systemd-networkd[475]: lo: Link UP
systemd-networkd[475]: lo: Gained carrier
systemd-networkd[475]: eth0: Gained IPv6LL
systemd-networkd[475]: Enumeration completed

# journalctl -u systemd-resolved
systemd[1]: Starting Network Name Resolution...
systemd-resolved[257]: Positive Trust Anchors:
systemd-resolved[257]: . IN DS 20326 8 2 e06d44b[...]
systemd-resolved[257]: Negative trust anchors: home.arpa 10.in-addr.arpa [...]
systemd-resolved[257]: Using system hostname [...]

# resolvectl
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: uplink
  Current DNS Server: 1.1.1.1
Fallback DNS Servers: 1.1.1.1 9.9.9.10 8.8.8.8 2606:4700:4700::1111 2620:fe::10 2001:4860:4860::8888

Link 2 (eth0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```
So it seems the kernel has made the DHCP requests, but `systemd-networkd` can't find that information to use, and doesn't attempt to take over the interface and send more DHCP requests.

It makes no difference whether I have a config file or not, but I have tried this one:
```
# /etc/systemd/network/eth0.network
[Match]
Name=eth0

[Network]
DHCP=yes
DNSSEC=no
IPv6AcceptRA=true

[DHCPv4]
UseDNS=true
```
I know the config file is being read as it complained when I put a typo in it, so I'm not sure why `systemd-networkd` is not attempting to configure the interface.

**Comment by MischaBaars** [comment]
Hello,

I have a similar problem. Did you get the above working in the end?

When I boot the server (Fedora Server) that contains the nfsroot, a network connection is opened by default with ipv4.method set to auto. All DHCP settings are retrieved from a TP-Link router.

When I boot the server (Fedora Workstation) with dnsmasq enabled and with DHCP disabled on the router, and one of the nodes either with iPXE kernel line 1) or line 2), a network connection is opened by default with ipv4.method set to manual. It does retrieve the hostname and the ip address, but resolvectl status does not return a DNS server. If I put that in manually using resolvectl dns eth0 192.168.2.1, then everythings does work as it should.

Also, the networkctl executable seems to be missing on Fedora Server.

iPXE kernel line 1): kernel vmlinuz-5.18.10 console=tty1 root=/dev/nfs rw net.ifnames=0 nfsroot=192.168.2.7:/mnt/dev/e37a097c-cdde-4e70-a2ef-5c2e98b773c7 ip=on rootfstype=ext4 raid=noautodetect rootwait quiet
iPXE kernel line 2): kernel vmlinuz-5.18.10 console=tty1 root=/dev/nfs rw net.ifnames=0 nfsroot=192.168.2.7:/mnt/dev/e37a097c-cdde-4e70-a2ef-5c2e98b773c7 ip=${ip}:${dhcp-server}:${gateway}:${netmask}:${hostname}:eth0:on:${gateway}:${dhcp-server} rootfstype=ext4 raid=noautodetect rootwait quiet

Dnsmasq.conf seems to be configured correctly, all the iPXE environment variables contain the right values, but like this ofcourse one can never be sure.

journalctl output on server booting Fedora Server:

Jul 23 14:14:05 fedora systemd[1]: Starting systemd-resolved.service - Network Name Resolution...
Jul 23 14:14:06 fedora systemd-resolved[374]: Positive Trust Anchors:
Jul 23 14:14:06 fedora systemd-resolved[374]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Jul 23 14:14:06 fedora systemd-resolved[374]: Negative trust anchors: home.arpa 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Jul 23 14:14:06 fedora systemd-resolved[374]: Using system hostname 'fedora'.
Jul 23 14:14:06 fedora systemd[1]: Started systemd-resolved.service - Network Name Resolution.
Jul 23 14:14:06 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-resolved comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 23 14:14:08 fedora NetworkManager[462]: <info>  [1658578448.0497] dns-mgr[0x55ed03469250]: init: dns=systemd-resolved rc-manager=symlink, plugin=systemd-resolved
Jul 23 14:14:13 fedora systemd-resolved[374]: eth0: Bus client set default route setting: yes
Jul 23 14:14:13 fedora systemd-resolved[374]: eth0: Bus client set DNS server list to: 192.168.2.1

journalctl output on nodes booting Fedora Server:

Jul 23 14:22:48 tp11 systemd[1]: Starting systemd-resolved.service - Network Name Resolution...
Jul 23 14:22:49 tp11 systemd-resolved[362]: Positive Trust Anchors:
Jul 23 14:22:49 tp11 systemd-resolved[362]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Jul 23 14:22:49 tp11 systemd-resolved[362]: Negative trust anchors: home.arpa 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Jul 23 14:22:50 tp11 systemd-resolved[362]: Using system hostname 'tp11'.
Jul 23 14:22:50 tp11 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-resolved comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 23 14:22:50 tp11 systemd[1]: Started systemd-resolved.service - Network Name Resolution.
Jul 23 14:23:00 tp11 NetworkManager[451]: <info>  [1658578980.0304] dns-mgr[0x562590d1f250]: init: dns=systemd-resolved rc-manager=symlink, plugin=systemd-resolved

Help would be appreciated!

Thanks,
Mischa Baars.

**Comment by yuwata** [comment]
@MischaBaars Please open a new RFE page.

**Comment by MischaBaars** [comment]
No problem :)

#24095
