### ISSUE TITLE
Systemd can not autologin system user since upgrade to systemd 249

### ISSUE THREAD

**Issue by mikhailian** [systemd/systemd#21125]
**systemd version the issue has been seen with**
 >systemctl --version
systemd 249 (249.5-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)

 > ` 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd should login the user specified in 
```
# cat /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
ExecStart=/usr/bin/agetty --autologin lowry --noclear %I $TERM
Type=idle
TTYVTDisallocate=no
```

**Unexpected behaviour you saw**
 > systemd hands indefinitely in tty1

**Steps to reproduce the problem**
 > configure autologin as specified above and observe systemd hanging indefinitely in tty1.

**Additional program output to the terminal or log subsystem illustrating the issue**

journalctl shows the following entry:
```
Oct 25 22:09:48 lowry-tp login[996]: pam_systemd(login:session): Failed to get user record: Input/output error
```
```
# SYSTEMD_LOG_LEVEL=debug userdbctl user lowry
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Multiplexer: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"userName":"lowry","service":"io.systemd.Multiplexer"}}
/run/systemd/userdb/io.systemd.Multiplexer: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Multiplexer: New incoming message: {"error":"io.systemd.System","parameters":{"errno":2}}
/run/systemd/userdb/io.systemd.Multiplexer: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.System
/run/systemd/userdb/io.systemd.Multiplexer: Changing state processing-reply → idle-client
Failed to find user lowry: Input/output error
```

```
# grep lowry /etc/passwd
lowry:x:1000:985::/home/lowry:/bin/bash

```

**Comment by poettering** [comment]
This actually was fixed by e908961d2eba7adb335e7f36c37c39e2e96773d2 a long time ago.
