### ISSUE TITLE
debugging systemd user instance

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#2113]
I've got weird thing happening to my "systemd --user" - it dies:
systemctl --user status
Failed to read server status: IO error.

systemctl --user status mpd  
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1

Where can I check what "status 1" actually means?
Also, how can I isolate logs for systemd's user instance?

In journalctl output there are of course plenty of logs from systemd but how to get only logs from user instance?

I see that overall system status is degraded and "systemctl --failed" shows that it's user instance to blame. However when I inspect it with "systemctl status -l user@1000.service" the result is very brief:
...
user@1000.service: Unit entered failed state.
user@1000.service: Failed with result 'timeout'.

**Comment by zabbal** [comment]
There's one unit which fails timeout but it only has 
WantedBy=default.target
so if I interpret docs correctly its failure should not cause systemd's user instance failure.

**Comment by keszybz** [comment]
The second part of the message comes from the dbus daemon. Status 1 probably means EPERM / operation not permitted. 

> how to get only logs from user instance?

`journalctl --user`, or possibly `journalctl -b _PID=<pid-of-systemd--user>` .

If you can reproduce the issue, you can set the log level to debug (kill -SIGRTMIN+22 <pid-of-systemd--user> and then see what lands in the logs.

**Comment by poettering** [comment]
Is this still relevant? is there anything interesting in the logs @keszybz suggested to get? Otherwise we should really close this

**Comment by keszybz** [comment]
Please reopen if there's more info.
