### ISSUE TITLE
Add opt-in field indexing to journals

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#21139]
**Is your feature request related to a problem? Please describe.**

Currently, journals index every field, which means we allocate a Data object for every field and have Entry objects reference it via it's offset. This means that even for fields that don't make sense to index, we still incur a sizable overhead due to allocating a Data object for those fields. If we assume a field is unique and we never benefit from the journal's de-duplication for that field, we add 72 bytes of overhead per unique field (8 64-bit fields in Data object + 1 64-bit offset in the Entry object). This (among other things) results in journals being excessively large on disk.

**Describe the solution you'd like**

We shouldn't index every field. A great example is MESSAGE which almost always will be unique, especially when logging frameworks that don't integrate with journald are used which will include a full timestamp in the MESSAGE. Instead, I propose we add a journald configuration option that lists the fields that should be indexed. systemd can ship it's own drop-in(s) for journald's built-in and common fields (which the user can override in /etc) and other services that need specific fields indexed can ship their own drop-in to have those fields indexed as well.

Fields that are not indexed would be stored inline in the Entry object, prefixed with their size and a flags byte to store the compression flags for that field. The list of fields to index would be stored in a new object in the journal. For fields that aren't indexed, we could outright refuse to let them be used in journalctl matches or the equivalent sd-journal APIs, or fallback to the (very) slow approach of doing a linear search over all entries. An extra flag in the header could be added to allow disabling the feature altogether, which would indicate all fields should be indexed, which would enable a smooth(er) transition.

An added advantage that would come with the fewer Data objects when not every field is indexed is that the Data hash table would fill up slower which could allow journal files to grow bigger before having to rotate.

**Comment by DaanDeMeyer** [comment]
Closing this one as it's part of the wider compact mode PR already
