### ISSUE TITLE
systemd-journald refuses to shut down when under heavy load

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#21164]
If I enable the following service in a mkosi Fedora image and start the image in QEMU, when trying to shutdown the VM using `systemctl poweroff`, journald will log about not being able to connect to the stream file descriptor to the service manager and refuses to shut down, delaying the shutdown process:

mkosi.extra/etc/systemd/system/log-stuff.service:

```
[Service]
ExecStart=/usr/bin/python -c 'for c in range(1000000): print(\"%i %%d\" %% c)'
LogRateLimitIntervalSec=0
LogRateLimitBurst=0

[Install]
WantedBy=multi-user.target
```

`systemctl --root mkosi.extra enable log-stuff`

mkosi.extra/etc/systemd/journald.conf:

```
[Journal]
SystemMaxUse=1G
RateLimitIntervalSec=0
RateLimitBurst=0
```

```sh
$ mkosi -i -f qemu
...
$ systemctl poweroff
...
[    6.001446] systemd-journald[331]: Failed to send stream file descriptor to service manager: Connection refused
[    6.008643] systemd-shutdown[1]: Syncing filesystems and block devices.
[    6.021796] systemd-journald[331]: Failed to send stream file descriptor to service manager: Transport endpoint is not connected
[    6.045409] systemd-journald[331]: Failed to send stream file descriptor to service manager: Transport endpoint is not connected
[    6.053368] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
```

Happens on the main branch. Was able to reproduce on v249 release branch as well. Host system is Fedora 35.

**Comment by DaanDeMeyer** [comment]
Closing in favor of #22642 as that report is more detailed
