### ISSUE TITLE
pid1: memory not aligned enough used for reading RootImages with O_DIRECT

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#21176]
**systemd version the issue has been seen with**
 > main, bisected to e8c7c4d9d145e0ab1ca75457390fcc698c7e55af onwards

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)

 > `5.14.0-3`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Mounting a squashfs image as `RootImage=` is successful

**Unexpected behaviour you saw**
Starting a service fails:
```
Oct 29 00:08:06 systemd[15228]: systemd-networkd.service: Failed to set up mount namespacing: Invalid argument
Oct 29 00:08:06 systemd[15228]: systemd-networkd.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-networkd: Invalid argument
Oct 29 00:08:06 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=226/NAMESPACE
Oct 29 00:08:06 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Oct 29 00:08:06 systemd[1]: Failed to start Network Configuration.
Oct 29 00:08:06 systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 5.
Oct 29 00:08:06 systemd[1]: Stopped Network Configuration.
```

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

Excerpt of strace of PID1 failing when starting `systemd-networkd`:
```text
fstat(4, {st_mode=S_IFBLK|0660, st_rdev=makedev(0xfe, 0x18), ...}) = 0
ioctl(4, BLKGETSIZE64, [54525952])      = 0
openat(AT_FDCWD, "/sys/dev/block/254:24", O_RDONLY|O_CLOEXEC) = 3
openat(3, "dm/uuid", O_RDONLY|O_CLOEXEC) = 5
read(5, "LVM-Yugg1eSiCXG0Mruly3MMsgzRGcDsAw8ilggPJxLdtTuHkJAuwSaP2e151VbHpK56\n", 8191) = 69
read(5, "", 8122)                       = 0
close(5)                                = 0
close(3)                                = 0
lseek(4, 54460416, SEEK_SET)            = 54460416
read(4, 0x555f96eaa268, 64)             = -1 EINVAL (Invalid argument)
fsync(4)                                = 0
close(4)                                = 0
openat(AT_FDCWD, "/dev/kmsg", O_WRONLY|O_NOCTTY|O_CLOEXEC) = 3
clock_gettime(CLOCK_MONOTONIC, {tv_sec=36, tv_nsec=197939784}) = 0
writev(3, [{iov_base="<27>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1686]: ", iov_len=8}, {iov_base="systemd-networkd.service: Failed to set up mount namespacing: Invalid argument", iov_len=78}, {iov_base="\n", iov_len=1}], 5) = 98
```
Line
```text
read(4, 0x555f96eaa268, 64)             = -1 EINVAL (Invalid argument)
```
is the problem. Man read(2):

EINVAL fd is attached to an object which is unsuitable for reading; _or the file was opened with the O_DIRECT flag, and either the address specified in buf, the value specified in count, or the file offset is not suitably aligned._

Offset 54460416 (or 0x33f0000) is well aligned and also count 64 looks good to me, so I think the address 0x555f96eaa268 should be more strictly aligned than by 8. Sadly the manual page doesn't tell what exactly is 'suitably aligned'.

I suppose the fix is that `dissect_image()` (or something related) should use `posix_memalign()` to allocate more aligned memory for reading images opened with O_DIRECT. I couldn't locate where the read happens and e8c7c4d9d145e0ab1ca75457390fcc698c7e55af only enables O_DIRECT so it doesn't provide a clue.

The images are raw squashfs without any MBR/GPT partition tables.

**Comment by poettering** [comment]
Hmm, wait. So you are saying that libblkid fails on the block device set up this way? That would be a bug in libblkid. i.e. if we pass an `S_IFBLK` fd to libblkid and it reads data off it thta is not aligned in position and size then this would be a bug in libblkid.

(I initially thought you are saying we pass the `S_IFREG` fd that is what the loopback device is based on to libblkid where it then fails.)

**Comment by poettering** [comment]
Any chance you can upload a disk image that fails like this somewhere so that i can have a closer look?

**Comment by topimiettinen** [comment]
> Any chance you can upload a disk image that fails like this somewhere so that i can have a closer look?

@poettering I sent you a small image via email.

**Comment by topimiettinen** [comment]
In my case it's S_IFBLK:
```
openat(AT_FDCWD, "/dev/levy/acpid-all.squashfs", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_DIRECT|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(0xfe, 0xd), ...}) = 0
ioctl(3, LOOP_GET_STATUS64, 0x418be4ec0b98) = -1 ENOTTY (Inappropriate ioctl for device)
fcntl(3, F_DUPFD_CLOEXEC, 3)            = 4
ioctl(4, _IOC(_IOC_READ, 0x12, 0x80, 0x8), 0x418be4ec0890) = -1 ENOTTY (Inappropriate ioctl for device)
close(3)                                = 0
fstat(4, {st_mode=S_IFBLK|0660, st_rdev=makedev(0xfe, 0xd), ...}) = 0
[clip]
lseek(4, 12517376, SEEK_SET)            = 12517376
read(4, 0x7b91e668f1a8, 64)             = -1 EINVAL (Invalid argument)
```

**Comment by poettering** [comment]
So do I get this right: you already have a block device? I am confused? What kind of block device is this? I really don't follow anymore...

usually we operate on regular files which we turn into block devices via the loopback layer. But that's not what you are doing here, do I get this right?

**Comment by topimiettinen** [comment]
The images are stored in LVM logical volume 'levy', so the block device (for example `/dev/levy/acpid-all.squashfs`) is from device-mapper (0xfe, 0xd in the last strace).

The bug indeed doesn't seem to appear for images stored somewhere in the file system, the image doesn't seem to be probed in that case. I use that model only for a few very early services like DM and LVM, the other service images are stored in LVM.
