### ISSUE TITLE
does map blkio.bfq.weight to 1..100 meet expectations?

### ISSUE THREAD

**Issue by JetXujing** [systemd/systemd#21187]
Hi， after commit c3ba9cb8f1b3ea0211123e1ae8e00bf7494ba233, blkio.bfq.weight is mapped to 1..100, does it meet exception. CGROUP_BLKIO_WEIGHT_MAX is defined 1000 now.

**Comment by poettering** [comment]
/cc @keszybz 

Honestly, I'd just drop the whole bfq stuff. It's clearly not ready if you ask me, I am really not sure why we bother at all..

**Comment by keszybz** [comment]
> Honestly, I'd just drop the whole bfq stuff. It's clearly not ready if you ask me, I am really not sure why we bother at all..

Yeah, it would have been wise to not step into this mess in the first place. But I think it's too late now: people are using bfq, and if we rip out support, people will be unhappy. I think @yuwata's patch in #21208 is a reasonably clean solution. Let's just do that and hope that the kernel folks pull their act together.
