### ISSUE TITLE
dbus dependency in system-update

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#2119]
Since `systemd` v228 offline update (`system-update.target`) via `packagekit` fails. I have a bug report for Arch Linux:
https://bugs.archlinux.org/task/47234

Adding a `Requires=dbus.socket` for `packagekit-offline-update.service` makes this work again. I already sent a pull request:
https://github.com/hughsie/PackageKit/pull/99

As this worked before... Is this a regression in `systemd` or is it mandatory to make the unit require dbus.socket now?

**Comment by keszybz** [comment]
There's certainly no promise that dbus is running/available. Special services like offline update services should pull in their own dependencies.

Nevertheless, I'd be very suspicious of having to have dbus.socket for packagekit upgrade to work. It _should_ be able to run in a very minimalistic environment, and degrade gracefully if stuff is not available. But I don't know too much about packagekit internals, so please take this comment with a grain of salt.
