### ISSUE TITLE
Allow to prevent services from flooding the log with irrelevant messages

### ISSUE THREAD

**Issue by veita** [systemd/systemd#21192]
**Is your feature request related to a problem? Please describe.**

Currently there seems to be no way to prevent specific services from overwhelming the systemd log and displacing relevant messages from it.

E.g. we receive up to about 100 lines per second from `sshd` of the form
```
Oct 31 18:33:08 s003 sshd[3239337]: Accepted publickey for cijob from n.n.n.n port 41208 ssh2: ED25519 SHA256:...>
Oct 31 18:33:08 s003 sshd[3239337]: pam_unix(sshd:session): session opened for user cijob(uid=1127) by (uid=0)
Oct 31 18:33:08 s003 sshd[3239343]: Received disconnect from n.n.n.n port 41208:11: disconnected by user
Oct 31 18:33:08 s003 sshd[3239343]: Disconnected from user cijob n.n.n.n port 41208
Oct 31 18:33:08 s003 sshd[3239337]: pam_unix(sshd:session): session closed for user cijob
```
These messages are purely informational and not very useful in our use case.

**Describe the solution you'd like**
I would like to be able to tell systemd not to log messages from `sshd` that are not errors or warnings.

Ideally this should not affect messages about start, stop and other service control events.

**Describe alternatives you've considered**
Replacing systemd logging with a logging daemon that allows different logging configurations for different services.

**Comment by SjonHortensius** [comment]
I'd rather have the journal remain an unfiltered collection of logmessages from all daemons. For your specific issue, you should probably look into configuring the `LogLevel` in `/etc/ssh/sshd_config`

**Comment by DaanDeMeyer** [comment]
This seems to be the same request as in https://github.com/systemd/systemd/issues/6432 so I'm going to close this issue in favor of that one.
