### ISSUE TITLE
Service not auto starting when using a timer + Conflits

### ISSUE THREAD

**Issue by alvarlagerlof** [systemd/systemd#21195]
**Is your feature request related to a problem? Please describe.**
Currently, there doesn't seem to be a way to stop some services based on a trigger of a timer, while still having them automatically start on boot. I want to use this to keep some services always-running, but close them when starting a temporary very resource intensive task.

**Describe the solution you'd like**
I'd like a way to still keep the services auto starting, and only shut down when the timer triggers. Currently, the timer being active at all seems to inhibit start.

**Describe alternatives you've considered**
Running systemctl commands in ExectStartPre and ExpectStop will be my solution unless I've missed something. This is unoptimal since I will need to disabled and enable them too.

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 248 (v248.7-1.fc34)`

**Comment by poettering** [comment]
It should suffice to add Conflicts= from the "very resource intensive" service to the service you want to stop when it starts. i.e. whether that "very resource intensive" service is started via timer or something else shouldn't matter... 

Or what am I missing?

Also note #17311 is already asking for a way to stop a unit based on a timer unit elapsing.

Hence I presume we can just close this?

**Comment by alvarlagerlof** [comment]
My issue turned out to be the [Installs] section on the service with the Conflicts= I was putting multi-user.target threre making it start by itself.
