### ISSUE TITLE
journalctl: add option to show Unix time

### ISSUE THREAD

**Issue by borisovg** [systemd/systemd#2120]
Please add an option to journalctl to show timestamps in Unix time. This will be useful for correlating logs with output of dbus-monitor, for example.

**Comment by evverx** [comment]
I use [`-o json`](http://www.freedesktop.org/software/systemd/man/journalctl.html#%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20json%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20) and [`jq`](https://stedolan.github.io/jq/).
There are several fields:
- [`__REALTIME_TIMESTAMP`](http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#__REALTIME_TIMESTAMP=)
- [`_SOURCE_REALTIME_TIMESTAMP`](http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#_SOURCE_REALTIME_TIMESTAMP=)

There is an "ugly" way:

```
$ journalctl -o short-iso -q | perl -lpe 's/^(?=\d)([^ ]+)/chomp($ts=`date -d$1 +%s`);$ts/e'
```
