### ISSUE TITLE
systemctl user-requires and systemd user-dismiss

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#21205]
**Is your feature request related to a problem? Please describe.**
To stop and running service, I need to provide root password. Maybe is a way to allow certain users to type own password for selected services?

**Describe the solution you'd like**
This idea (probably) need to integrate with PolicyKit (I do not known). Add two commands to systemctl user-requires and user-dissmis. In future, maybe you could allow to start an service by providing user password for selected users with selected services. The idea is to allow user to request to request some services was running. If it is not ran, ask for root password and ran it. Also, remember which users request service to be run. To stop service, user must start systemctl user-dismiss service-name command. In next step, he/she provides own password. Systemd will remove user from list of users, who use this service. If list is empty, service will be stopped.
**Describe alternatives you've considered**
Add new systemctl commands:
1. acl allow-start [service]
2. acl allow-stop [service]
If someone type one of these systemctl commands, it must provide root password. This is system-session commands, so acl would be remember until reboot. acl allow-start allows to run service by user by providing own password. acl allow-stop is similar, but mark service to be stopped by current user (or user selected by --user=name switch).

Why these? Some system services do not need root, so there is no reason to stop/start it by root. Typing root password will degrade system security. If user is allowed to talk with docker (for example) and docker must be started on request, somebody must provide root password. Why this user must known root password?

**Comment by poettering** [comment]
I think socket activatio is a vastly safer and more secure way to run services on request only. i.e. modern services can tell systemd to bind a socket for them, and then are implicitly activated once a client connects to a socket. This is transparent to clients, and requires not manual intervention by clients.

Moreover PolicyKit allows you to define any ACLs you want already, it's the project's raison d'etre really. Please consult PK docs for details about this. You can allow any user access to any service this way, with or without re-authentication. No changes to systemd needed.

Thus, let's close this.
