### ISSUE TITLE
daemon-reload may caused unmounting  during booting the system

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#21214]
**systemd version the issue has been seen with**
 > systemd 243

**Expected behaviour you didn't see**
 > Mounted points in /etc/fstab should not be unmounted during the booting.

**Unexpected behaviour you saw**
 > Mounted points in /etc/fstab are unmounted during the booting.

**Steps to reproduce the problem**
 > Reboot the system and mask a service at very early stage of booting. The masking action will cause the daemon-reload. And the mounted point probably will be unmounted at the end stage of **manager_reload**. I think maybe caused by **manager_catchup**.

I reduce the log text into the steps listed below as the debug log is really very long.
```text
Switch root.
....
Nov 02 08:30:41  systemctl[2180]: Removed /etc/systemd/system/multi-user.target.wants/firstrun.service.
...
Nov 02 08:30:41  systemd[1]: Reloading.
...
a lot of udev actions
...
Nov 02 08:30:41  systemd[1]: Serializing systemd-state to memfd.
...
Nov 02 08:30:41  systemd[1]: Deserializing state...
...
Nov 02 08:30:41  systemd[1]: Pulling in home-fsp.mount/start from local-fs.target/start
Nov 02 08:30:41  systemd[1]: Added job home-fsp.mount/start to transaction.
...
Nov 02 08:30:41  systemd[1]: Invoking unit coldplug() handlers…
...
Nov 02 08:30:41  systemd[1]: dev-mapper-cpsVG\x2dfsp.device: Changed dead -> plugged
...
Nov 02 08:30:41  systemd[1]: Invoking unit catchup() handlers…
...
Nov 02 08:30:41  systemd[1]: dev-mapper-cpsVG\x2dfsp.device: Changed plugged -> dead(This cause the problem, as the device turned to dead.)
...
Nov 02 08:30:41  systemd[1]: dev-mapper-cpsVG\x2dfsp.device: Changed plugged -> dead...
Nov 02 08:30:41  systemd[1]: home-fsp.mount: Trying to enqueue job home-fsp.mount/stop/replace
Nov 02 08:30:41  systemd[1]: Added job home-fsp.mount/stop to transaction.
```

So i think there maybe a problem in manager_catchup at the end of manager_reload. At some case the it will turn the state of mounted points from plugged into dead. And cause the unmounting action.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
