### ISSUE TITLE
core/path: `path_spec_watch` is very slow when there's amount of disk buff/cache

### ISSUE THREAD

**Issue by slayercat** [systemd/systemd#21211]
**systemd version the issue has been seen with**
 > Found in v219.
 > But it is more likely that this problem still exists in the mainline (commit 222cd15)
 

**Used distribution**
 > `CentOS 7`

**Linux kernel version used** (`uname -a`)
 > `Linux localhost.localdomain 5.6.12-1.el7.elrepo.x86_64 #1 SMP Fri May 8 20:07:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > `systemctl daemon-reload` / `systemctl daemon-reexec` shell not took 5min and be ready quick. Also this shell not freeze the kernel untils ready.

**Unexpected behaviour you saw**
 > When there's amount of disk cache(66GiB in my case), `systemctl daemon-reload` / `systemctl daemon-reexec` will be slow (3-5min) to be ready in a high-end x86 server. 
 > `systemctl` will complains about dbus timeout. In this situation, Linux kernel will move slowly until reload is done(will freeze the terminal).
 

**Steps to reproduce the problem**
 > 1. Fills memory with disk cache (66GiB in my case)
 > 2. Use any `systemctl` operation to cause a `manager_reload`. e.g. `systemctl daemon-reload` / `systemctl enable` / `systemctl disable`
 > 3. When there's any `Unit` with `PathExists=` / `PathChanged=`. the problem reproduces.
 > 4. After use `echo 3 >/proc/sys/vm/drop_caches `, the problem will gone until disk cache grows.

**Additional program output to the terminal or log subsystem illustrating the issue**

### symptom

When there's amount of disk cache(66GiB in my case), `systemctl daemon-reload` / `systemctl daemon-reexec` will be slow (3-5min) to be ready in a high-end x86 server. 

`systemctl` will complains about dbus timeout. In this process, Linux kernel will move slowly until reload's done.

A futher dig founds that `core/path` will took a long time in loading some `Unit` having  `PathExists=` / `PathChanged=` 
(callstack `unit_coldplug` -> `path_coldplug` -> `path_spec_watch`)

### root cause
Seems calling with `inotify_add_watch` with path root (`/`) in high disk cache environ will be slow.

### suggestion
Do not call `inotify_add_watch`  with `/`

### debug process for review

I've modified the source to print some debuginfo for locate the problem. 

in `systemd version 219`, [sourcev219](https://gist.github.com/slayercat/b13e5d33fa7c31d5caed6b50836a8de6#file-path_v219-c) will produce [this log](https://gist.github.com/slayercat/b13e5d33fa7c31d5caed6b50836a8de6#file-v219_debug_path_spec_watch-log)

Have been replaced `path_spec_watch` with commit 222cd15, but the problem persists. and even worse... for it calls `inotify_add_watch` with `/` multi-times
[debug code with 222cd15](https://gist.github.com/slayercat/b13e5d33fa7c31d5caed6b50836a8de6#file-path_main-c) and produceds [log](https://gist.github.com/slayercat/b13e5d33fa7c31d5caed6b50836a8de6#file-main_debug_path_spec_watch-log)

please notify the high time delay  when calling `inotify_add_watch` with `/`.

For some reason, the `inotify_add_watch` function will took somewhile to add `/` for watch. So maybe it's fine to strip it away?

And, i'm wondering why `systemctl enable` / `systemctl disable` send daemon-reload command by default.

### workaround
1. ```echo 3 >/proc/sys/vm/drop_caches```
2. ``` systemctl --no-reload enable  `pwd`/name.service ```

### appendix

See [1] for hardware in reproduce: (be aware of *buff/cache*)
See [2] for software versions

[1] Hardwares
CPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz   *2
Memory: 754 GiB
```
top - 10:19:25 up 32 days, 35 min,  1 user,  load average: 32.46, 28.14, 30.41
Tasks: 678 total,  17 running, 336 sleeping,   0 stopped,   1 zombie
%Cpu(s): 46.3 us,  2.4 sy,  0.0 ni, 51.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 79116313+total, 38571600+free, 33622803+used, 69219120 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 43658940+avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
45110 root      20   0  521.5g   7.7g  18436 S 711.8  1.0  22:46.62 msg_processor
 6847 501       20   0   85.6g  37.5g   3.0g S 347.1  5.0   9340:48 java
45129 root      20   0 2852520 164064  12224 S 264.7  0.0  12:08.69 dataenrich
```

[2] software versions:
OS: `CentOS 7`
Kernel: `Linux localhost.localdomain 5.6.12-1.el7.elrepo.x86_64 `
Systemd version: v219 (reproduceable with `path_spec_watch` in main [commit 222cd15] )

**Comment by poettering** [comment]
I am sorry, but why would `inotify_add_watch` be slow in such a case? If it is so slow, then this would be a kernel issue, not a systemd issue.

Have you tried to reproduce this with a current systemd *and* kernel?

**Comment by poettering** [comment]
No response, and this is was done on a really old systemd. Moreover it doesn't even look like a systemd issue, but a kernel one. Hence closing.
