### ISSUE TITLE
I'm not sure if there's a state missing here. As a result, the mounted partition is unmounted.

### ISSUE THREAD

**Issue by hexiaowen** [systemd/systemd#21220]
https://github.com/systemd/systemd/blob/b2efed520b51f71484e45289f9f34b611838cd4a/src/core/device.c#L663

systemd version the issue has been seen with

`v248`

Used distribution

`openEuler 21.09`

Linux kernel version used (uname -a)

`Linux localhost.localdomain 5.10.0-5.10.0.24.oe1.x86_64 #1 SMP Wed Sep 29 19:53:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Expected behaviour you didn't see

`all mountpoints are be mounted normally when system bootup`

Unexpected behaviour you saw

`some mountpoints are be unmount when system bootup`

Steps to reproduce the problem

When the system starts, the systemctl daemon-reload is triggered.
```
Nov 02 01:50:42 localhost systemd[1]: Reloading.
Nov 02 01:50:43 localhost systemd[1]: var-log.mount: Changed dead -> mounted
```

A device is set to dead. As a result, the mounted mount is forced to stop.
```
Nov 02 01:50:43 localhost systemd[1]: dev-cpsVG-log.device: Changed plugged -> dead
Nov 02 01:50:43 localhost systemd[1]: systemd-fsck@dev-cpsVG-log.service: Trying to enqueue job systemd-fsck@dev-cpsVG-log.service/stop/replace
Nov 02 01:50:43 localhost systemd[1]: Added job systemd-fsck@dev-cpsVG-log.service/stop to transaction.
Nov 02 01:50:43 localhost systemd[1]: Pulling in var-log.mount/stop from systemd-fsck@dev-cpsVG-log.service/stop
Nov 02 01:50:43 localhost systemd[1]: Added job var-log.mount/stop to transaction.
```

The corresponding mountpoint is uninstalled.
```
Nov 02 01:50:43 localhost systemd[1]: var-log.mount: Mount process exited, code=exited, status=32/n/a
Nov 02 01:50:43 localhost systemd[1]: var-log.mount: Changed unmounting -> mounted
Nov 02 01:50:43 localhost systemd[1]: var-log.mount: Job 320 var-log.mount/stop finished, result=failed
Nov 02 01:50:43 localhost systemd[1]: Failed unmounting /var/log.
```

I'm not sure if there's a state missing here. If a device is in the PRE：DEVICE_FOUND_UDEV or NOW：DEVICE_FOUND_MOUNT state, d->state is set to DEVICE_DEAD. As a result, the mounted partition is unmounted.

**Comment by poettering** [comment]
This is with LVM? Can you reproduce the issue without? LVM makes a mess of the udev rules…

**Comment by poettering** [comment]
Also, can you reproduce this with 249?

**Comment by hexiaowen** [comment]
close , and see #12953
