### ISSUE TITLE
dbus-daemon: dbus[1252]: [system] Rejected: destination has a full message queue

### ISSUE THREAD

**Issue by csy97** [systemd/systemd#21227]
Description of problem:

A customer hits an issue where he sees his journal (and resulting rsyslog logs) flooded with "Rejected: destination has a full message queue" DBus messages.
The messages are sent by systemd, due to mount points changing (he has numerous NFS automounts), which generates "PropertiesChanged"

For some reason, systemd-logind doesn't process these messages, we can find them in "m->bus->rqueue", we reach the RQUEUE_SIZE limit, almost.
The coredump shows that systemd-logind is in its wait loop, which explains why the messages are not processed.

   var/log/messages are flooded with the below messages.
   Server started to report the below messages continuously after a system hang.

Oct 28 13:14:43 BAIOMAPC systemd-logind: Failed to start session scope session-c83791313.scope: Rejected: destination has a full message queue, 0 matched rules; type="method_call", sender=":1.3" (uid=0 pid=18177 comm="/usr/lib/systemd/systemd-logind ") interface="org.freedesktop.systemd1.Manager" member="StartTransientUnit" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="signal", sender="(unset)" ((bus)) interface="org.freedesktop.DBus" member="NameOwnerChanged" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="signal", sender="(unset)" ((bus)) interface="org.freedesktop.DBus" member="NameOwnerChanged" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (uid=0 pid=20129 comm="/usr/libexec/sysnotify --nodaemon ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="method_call", sender=":1.3" (uid=0 pid=18177 comm="/usr/lib/systemd/systemd-logind ") interface="org.freedesktop.DBus.Properties" member="Get" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="method_call", sender=":1.3" (uid=0 pid=18177 comm="/usr/lib/systemd/systemd-logind ") interface="org.freedesktop.DBus.Properties" member="Get" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
Oct 28 13:14:43 BAIOMAPC su: (to cnccq) root on none
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="signal", sender="(unset)" ((bus)) interface="org.freedesktop.DBus" member="NameOwnerChanged" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="signal", sender="(unset)" ((bus)) interface="org.freedesktop.DBus" member="NameOwnerChanged" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (uid=0 pid=20129 comm="/usr/libexec/sysnotify --nodaemon ")
Oct 28 13:14:43 BAIOMAPC dbus[18165]: [system] Rejected: destination has a full message queue, 0 matched rules; type="method_call", sender=":1.3" (uid=0 pid=18177 comm="/usr/lib/systemd/systemd-logind ") interface="org.freedesktop.systemd1.Manager" member="StartTransientUnit" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system ")

Version-Release number of selected component (if applicable):

systemd-219-67.el7_7.3

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by mrc0mmand** [comment]
Also, see:
  * https://bugzilla.redhat.com/show_bug.cgi?id=1805699
  * https://bugzilla.redhat.com/show_bug.cgi?id=1769928

which should've been, theoretically, fixed in systemd-219-78.el7,  systemd-219-73.el7_8.6, and systemd-219-67.el7_7.6
