### ISSUE TITLE
variable substitutions don't work in Environment entries

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#2123]
If I do something like

```
[Service]
Environment=FOO_PATH=/usr/local/lib/foo
Environment=PYTHONPATH=${FOO_PATH}/python
ExecStart=/usr/bin/python /usr/local/bin/foo.py -c ${FOO_PATH}/foo.conf
```

`PYTHONPATH` is not actually set correctly and my service fails to start. Doing instead

```
Environment=PYTHONPATH=/usr/local/lib/foo/python
```

works fine, which leads me to believe variables are either not supported or not processed correctly in `Environment` lines.

**Comment by davide125** [comment]
In case it matters, this is on

```
# systemctl --version
systemd 228
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by falconindy** [comment]
It's simply not supported, as mentioned by systemd.exec(5):

> Variable expansion is not performed inside the strings, however, specifier expansion is possible. The $ character has no special meaning.

**Comment by davide125** [comment]
Ah, thanks @falconindy I must have missed that in the docs. Consider this a RFE then :)

**Comment by falconindy** [comment]
I don't think there's any interest in turning systemd's unit file parser into a shell...

If you need this sort of behavior, you can wrap your ExecStart, e.g.

```
ExecStart=/usr/bin/env PYTHONPATH=${FOO_PATH}/python /usr/bin/python /usr/local/bin/foo.py -c ${FOO_PATH}/foo.conf
```

**Comment by poettering** [comment]
If you want a shell, use a shell. We don't want to be one. Sorry.

**Comment by celesteking** [comment]
This sucks. env substitution is the foundation of DRY. There's no need for shell, just $VAR substitution, that's all.
