### ISSUE TITLE
systemctl show --property=<values> do not match systemd-system.conf documentation

### ISSUE THREAD

**Issue by ptsneves** [systemd/systemd#21230]
**systemd version the issue has been seen with**
Any

**Used distribution**
Ubuntu and built from source, irrelevant

**CPU architecture issue was seen on**
Any, irrelevant

**Expected behaviour you didn't see**
 As per [systemctl manual](https://www.freedesktop.org/software/systemd/man/systemctl.html):
 >   For the manager itself, systemctl show will show all available properties. Those properties are documented in systemd-system.conf(5).

Then i see in [systemd-system.conf](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html) that there is a property called DefaultTimeoutStartSec and i expect that `systemctl show --property=DefaultTimeoutStartSec` shows the value in effect. I expect the same for all manager properties mentioned in [systemd-system.conf](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html) as per systemctl manual mentioned above.

**Unexpected behaviour you saw**
I see that `systemctl show --property=DefaultTimeoutStartSec` returns nothing nor is the property _DefaultTimeoutStartSec_  listed in `systemctl show`. Instead, i see that _DefaultTimeoutStartUSec_ is listed and shown. The same can be said about most time related properties. 

When _DefautTimeoutStartSec_ is set, for example in, _/etc/systemd/system.conf_ it gets correctly translated to the equivalent _DefautTimeoutStartUSec_. So _DefaultTimeoutStartSec_=120s will show in `systemctl show --property=DefaultTimeoutStartUSec` as 2min.

In sum: The file in [system.conf.in](https://github.com/systemd/systemd/blob/main/src/core/system.conf.in) matches the  [systemd-system.conf](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html) manual, but systemctl show --property= does not, as it should per it's own manual, thus it is a bug in my view.

**Comment by bluca** [comment]
Yes the unit directives not always match 100% with the DBUS properties, we do this intentionally, as the units are "human" readable/writable, but in general the dbus properties are for machines to consume, so for example they list the basic type (nanoseconds) even though for most cases it's not very readable, and it's easier for humans to write/read seconds. Note that "higher level" commands do pretty-print timestamps, and there are even knobs to customize that, but `show` pretty much prints what is available, so the properties names are not translated.

**Comment by ptsneves** [comment]
@bluca Fair enough. Then at least the documentation of systemctl should be updated to mention that indeed the parameters names do not match. That said it is unfortunate there is not a straight match, like explained below:

In the scenario where a system architect set out [mission specific default configurations](https://cenains.blog/2021/11/04/how-to-avoid-infinite-loops-on-crashing-systemd-units/) it is desirable that there is a way to check/test that those properties are indeed set.  systemctl's manual said there was a provided way to validate such system. Without such direct mapping an integrator must find the equivalent property to test.

In the end it does not even make much sense that the time units/scale are suffixed parts of the configuration options nor property names, because the outputs and storage can have different units. An illustrating example is one can have the system.conf option _DefaultStartLimitIntervalSec=2min_ and `systemctl show --property=DefaultStartLimitIntervalUSec` returning 120sec. Very inconsistent especially for machine usage.

To conclude, is there a way that the current promise of the manual of systemctl is honoured?

**Comment by bluca** [comment]
Feel free to send a PR to update the manpage to clarify that they might not match

**Comment by ptsneves** [comment]
I can do that, but are you able to answer the question:
> is there a way that the current promise of the manual of systemctl is honoured?

**Comment by bluca** [comment]
No, as I said there is no guaranteed 1:1 match between dbus properties and unit directives, and it's intentional - most often this is due to dbus being inflexible, so if a unit setting is expanded in a backward compatible way because the parser can be updated, the same is not true for the dbus property, as the signatures are fixed. So often there's a 1:N mapping between a unit setting and multiple dbus properties.

**Comment by bluca** [comment]
that said, systemctl does a bit of munging to print complex types, so if you feel like some of that should be improved, feel free to send a PR

**Comment by poettering** [comment]
This is *explicitly* documented already:

> Many properties shown by systemctl show map directly to configuration settings of the system and service manager and its unit files. Note that the properties shown by the command are generally more low-level, normalized versions of the original configuration settings and expose runtime state in addition to configuration. For example, properties shown for service units include the service's current main process identifier as "MainPID" (which is runtime state), and time settings are always exposed as properties ending in the "...USec" suffix even if a matching configuration options end in "...Sec", because microseconds is the normalized time unit used internally by the system and service manager.

I don't think we need more docs than that, do we? I mean, it's obvious people don't read docs, but adding more docs is not going to make it ore likely people read them...

**Comment by poettering** [comment]
That's from https://www.freedesktop.org/software/systemd/man/systemctl.html#show%20PATTERN%E2%80%A6%7CJOB%E2%80%A6 btw, i.e. the systemctl man page

**Comment by poettering** [comment]
Hence, I am tempted to just close this. Or what do you think we should add?

**Comment by ptsneves** [comment]
@poettering Fair enough, but then we have a contradiction, or at least implied one, as the following is also in the documentation of systemctl:

> For the manager itself, systemctl show will show all available properties. Those properties are documented in systemd-system.conf(5).

This is not true. systemd-system.conf does not document the properties shown by systemctl.

In my view we could clarify that "systemctl properties mostly are derived, or closely match, the options shown in systemd-system.conf". That is accurate and raises the awareness that there is not a direct equivalence.

**Comment by bluca** [comment]
That sounds about right - please go ahead and open a PR
