### ISSUE TITLE
Access to service restart functionality (SystemD) through the D-Bus for unprivileged user

### ISSUE THREAD

**Issue by gerbert** [systemd/systemd#21243]
Hi everyone!
I'm trying to restart a service managed by SystemD (e.g., dnsmasq), through a D-Bus call from Python scenario (long chain, yes). The command sent through the D-Bus to SystemD to restart the service (dnsmasq) is issued by an application, which runs as a service with unprivileged rights (user/group is not root). The Python scenario which runs as a service doesn't belong to the user/group which owns the service I'm trying to restart. The chain looks like this:

Python scenario (user/group = unprivileged) -> D-Bus command (e.g., "restart the service %name%") -> SystemD.
I always get permission denied error even though I've configured the D-Bus to allow calls to the destination/interface for specified user/group.

The question is (why I'm asking it here and not in D-Bus community)... Does SystemD allow to perform a service restart/start/stop only for the super user (i.e., root) through the D-Bus or, this can be configured (e.g., by some capability setting) and then I just need to configure D-Bus properly?

Thanks!

**Comment by mbiebl** [comment]
If you use PolicyKit > 105, you can configure it accordingly.
https://keshavarzreza.ir/create-linux-systemd-service-runable-for-non-root-users/

**Comment by gerbert** [comment]
> If you use PolicyKit > 105, you can configure it accordingly.
> https://keshavarzreza.ir/create-linux-systemd-service-runable-for-non-root-users/

The system (embedded) doesn't have user sessions and polkit at all. I was looking into polkit configuration at the very beginning. Basically I have only D-Bus and SystemD and can configure only them...

**Comment by mbiebl** [comment]
Then you are out of luck, I'd say.

**Comment by gerbert** [comment]
I expected to have some CAPs for the service which executes the command, like CAP_SYS_ADMIN or similar...

**Comment by mbiebl** [comment]
The recommendation is to use PolicyKit for such use cases. That's it raison d’être after all.
I know that PolicyKit > 105 can be a bit of a pain for embedded systems due to its mozjs dependency.
But there is https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/97 which would make it more suitable for such environments.

**Comment by gerbert** [comment]
> The recommendation is to use PolicyKit for such use cases. That's it raison d’être after all.
> I know that PolicyKit > 105 can be a bit of a pain for embedded systems due to its mozjs dependency.
> But there is https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/97 which would make it more suitable for such environments.

Thanks for your recommendation. I'll take a look into it. Maybe it'll help to solve the issue.

**Comment by mbiebl** [comment]
The Arch wiki has some useful docs as well: 
https://wiki.archlinux.org/title/Polkit#Allow_management_of_individual_systemd_units_by_regular_users

**Comment by gerbert** [comment]
Please correct me if I'm wrong, polkit requires active user session, right? Also, polkit daemon must be active? In my system polkit doesn't start at boot time, only manually. Also, as I mentioned earlier, there is no user session management (headless, or UI-less in my case).

**Comment by mbiebl** [comment]
Please follow-up on the mailing list if you have further questions.
