### ISSUE TITLE
message have Caught  <SEGV>,dumped core as pid 1473 and system is freak out

### ISSUE THREAD

**Issue by xiyou123321** [systemd/systemd#21242]
1、message have Failed to activate service 'org.freedesktop.systemd1': timed out;
2、systemd version is systemd-219-62.e17_6.3.x86_64
3、Here are some screenshots：
![图片](https://user-images.githubusercontent.com/93762788/140481951-a8bd0f3f-8680-4526-91df-a4e1c5ca4541.png)
![图片](https://user-images.githubusercontent.com/93762788/140481880-22d6eba8-a1a3-48a2-a4db-c6db87d4d273.png)

**Comment by xiyou123321** [comment]
The way to reproduce it is kill -11 1

**Comment by mrc0mmand** [comment]
1) This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. For support for older versions please contact your distribution instead - v219 is an ancient history.

2) The behavior is expected - if systemd crashes, there's not much left to do. The error messages are the result of that, since systemd no longer responds on its dbus API endpoint.

**Comment by xiyou123321** [comment]
why systemd crasher?And you konw?

**Comment by poettering** [comment]
> why systemd crasher?And you konw?

`kill -11 1` is an explicit request to make PID 1 abort with SIGSEGV, hence it aborts with SIGSEGV. If you don#t want this, don't run the command?

There are millions of ways to crash the system, systemd is not in the business in protecting you from that — as long as you are privileged you can do anything you like pretty much. If unprivileged code could do the same this would be a problem, but this is not the case here.

**Comment by xiyou123321** [comment]
>  is an explicit request to make PID 1 abort with SIGSEGV, hence it aborts with SIGSEGV. If you don#t want this, don't run the command?

No.To understand this ,don#t I use kill -11 1,it is the situation is similar of kill -11 1;

**Comment by xiyou123321** [comment]
> 
> 
>     1. This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. For support for older versions please contact your distribution instead - v219 is an ancient history.
> 
>     2. The behavior is expected - if systemd crashes, there's not much left to do. The error messages are the result of that, since systemd no longer responds on its dbus API endpoint.

V219 is not so old

**Comment by mrc0mmand** [comment]
> > ```
> > 1. This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. For support for older versions please contact your distribution instead - v219 is an ancient history.
> > 
> > 2. The behavior is expected - if systemd crashes, there's not much left to do. The error messages are the result of that, since systemd no longer responds on its dbus API endpoint.
> > ```
> 
> V219 is not so old

Uh, v219 is from 2015 (https://github.com/systemd/systemd/releases/tag/v219), so it's *quite* old. And since then, many bugs were fixed, so it's really impossible to tell if this issue is still present in the codebase. If you could reproduce it with the last two upstream releases (v248/v249), then it would be feasible to debug further).

**Comment by xiyou123321** [comment]
> 
> 
> > > ```
> > > 1. This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. For support for older versions please contact your distribution instead - v219 is an ancient history.
> > > 
> > > 2. The behavior is expected - if systemd crashes, there's not much left to do. The error messages are the result of that, since systemd no longer responds on its dbus API endpoint.
> > > ```
> > 
> > 
> > V219 is not so old
> 
> Uh, v219 is from 2015 (https://github.com/systemd/systemd/releases/tag/v219), so it's _quite_ old. And since then, many bugs were fixed, so it's really impossible to tell if this issue is still present in the codebase. If you could reproduce it with the last two upstream releases (v248/v249), then it would be feasible to debug further.

but 219 is centos latest version,i want to kuow why systemd was went wrong

**Comment by poettering** [comment]
if you encounter bugs in old systemd versions from stable distros, please contact the distros for support. They probably are missing a backport for a patch. 

Upstream we only focus on the two most recent *upstream* releases, i.e. 248 and 249 right now.
