### ISSUE TITLE
Implement support for other kinds of persistent block device naming besides `by-uuid` in `/etc/crypttab`

### ISSUE THREAD

**Issue by rgeorgiev583** [systemd/systemd#21267]
**Is your feature request related to a problem? Please describe.**
As per `crypttab(5)`, currently the only kind of persistent block device naming supported by `/etc/crypttab` (and `/etc/crypttab.initramfs`) is by UUID.  It would be useful to be able to refer to devices using the other kinds of identifiers.

Just for the sake of experiment, I tried to add an entry for an encrypted swap partition containing a `PARTLABEL` as the device ID to `/etc/crypttab.initramfs` on my machine; however, after regenerating the initramfs and rebooting, my system froze just after I entered the password to unlock my root partition.  After I changed the device ID to a UUID, my system booted without a problem and the swap device got unlocked and activated successfully.

(I'm not entirely certain that a feature request is appropriate for this.  However, the `crypttab(5)` man page states that *the second field contains a path to the underlying block device or file, or a specification of a block device via "UUID=" followed by the UUID* (there is no mention of other kinds of identifiers), so I decided that this behavior is not strictly a bug but a missing feature.)

**Describe the solution you'd like**
I want to be able to identify block devices by label, by UUID, by ID, by path, by `PARTLABEL` or by `PARTUUID`.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 249

**Comment by medhefgo** [comment]
As a workaround you can always just use `/dev/disk/by-*` directly. In fact, that's what `UUID=` translates to anway.

**Comment by poettering** [comment]
what is `/etc/crypttab.initramfs`? That's not a systemd thing.

Which distro is this? Does this distro use systemd in the initrd? I figure the answer is no, given that `/etc/crypttab.initramfs` is nothing systemd would ever read?

Everything you request should just work already if your OS uses systemd. if you use an OS that doesn't use systemd in the initrd, you are on your own I fear, we aren't involved in that, and can't fix that.

And yes, @medhefgo is right, /dev/disk/by* is the better way, and quite frankly people should really forget about the UUID=/LABEL=/PARTLABEL= mess if you ask me...

**Comment by rgeorgiev583** [comment]
@poettering I'm running Arch Linux.  `/etc/crypttab.initramfs` is used for devices which have to be unlocked by the Arch initrd (it is an alternative to specifying the devices through `rd.luks` kernel parameters).  Arch uses a custom script (`mkinitcpio`) for initrd creation which installs `/etc/crypttab.initramfs` (if it exists) into the initrd as `/etc/crypttab`.
@medhefgo thanks for the suggestion.  I totally agree with you and @poettering that this is the simpler solution to my problem.

I'm going to close this issue as I got convinced that there is no use in implementing this syntax so far.
