### ISSUE TITLE
`halt`/`poweroff`/`reboot` are not identical to `systemctl %s` with respect to non-root users

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#213]
Verbs `systemctl halt`, `systemctl poweroff` and `systemctl reboot`, if invoked under a non-root user and logind is not available, are governed by polkit action `org.freedesktop.systemd1.manage-units`. 

(For `systemctl halt` logind is obviously never available, as there's no corresponding bus method.)

However, `halt`, `poweroff` and `reboot` in the same conditions say "Must be root." and bail out. Shouldn't they be equivalent to `systemctl %s` in this regard?

**Comment by kaysievers** [comment]
They are system V compat, and should not be "smarter" than the original tools.

**Comment by intelfx** [comment]
Hm, but they already divert to logind if it's available on the bus... which itself is an enhancement over sysv semantics, IIRC.

**Comment by kaysievers** [comment]
Hmm, yeah, we did that to cover for Fedora's usermode tool (broken idea) which grants access to some tools for locally logged-in users. Not sure, what's the right answer here. @poettering?

**Comment by poettering** [comment]
We cannot make poweroff/reboot suddenly interactive when they never were before. People call these binaries from daemons and scripts and that would be quite a change of behaviour. For "systemctl poweroff" and friends this is different, because we define the API and can provide --no-ask-password to remove the interactivity (and we do). But we really shouldn't extend the old APIs with new switches or different default behaviour.

**Comment by poettering** [comment]
OK, I guess the checks in systemctl actually should be losened and also allow talking to PID1's StartUnit("reboot.target") now for unprivileged clients. After all we recently opened up StartUnit() to polkit, and hence it might be useful for unprivileged clients too. 

Of course, when we change systemctl like this I think we should only allow non-interactive polkit auth still for these tools, and leave interactive auth for systemctl poweroff and friends.

I hope that makes sense?

i have reopened the bug accordingly.

**Comment by intelfx** [comment]
At least `poweroff` and `reboot` (and `telinit`, btw) _currently_ may end up in interactive polkit auth kicking in. First two may divert to logind, and the last one is straight equivalent to `systemctl isolate`.

So — do you intend to remove existing places where interactive auth is allowed?

**Comment by poettering** [comment]
Yeah, the old tools should _never_ be interactive. If they end up being interactive now, that'd be a bug.

**Comment by intelfx** [comment]
Ok, then it's a heads-up, `poweroff` and `reboot` may become interactive in the logind path. `telinit [12345squ]` too, as it resolves directly to `start_with_fallback()` or `reload_with_fallback()`.
