### ISSUE TITLE
We can't use mac client identifier for DHCP. 

### ISSUE THREAD

**Issue by anischali** [systemd/systemd#21311]
systemd 244 (244.5+)

Distribution: homemade yocto dunfell distribution
Kernel version: linux kernel 5.4
Arch: arm

Expected behaviour:
When I put ClientIdentifier=mac, I expect to get the interface mac address in the dhcp discover packet client identifier option. but in my case I always see the iaid + duid and random client identifier with an systemd entrprise id. I get the same behavior when I put the ClientIdentifier=duid-only.

**Steps to reproduce the problem**
vi /etc/systemd/network/eth.network
[Match]
Name=eth*

[Network]
DHCP=ipv4

[DHCPv4]
UseDNS=true
UseNTP=true
UseHostname=true
UseDomains=true
UseRoutes=true
ClientIdentifier=mac

**Comment by yuwata** [comment]
Hm, systemd version you use is too old here. Could you test the issue still exists on recent release or current git HEAD?

**Comment by anischali** [comment]
Thank you very much for your quick reaction. I will test we the last commit

**Comment by anischali** [comment]
Thanck you very much, The issue is fixed in the recent code. so I will close the issue.

**Comment by anischali** [comment]
Thanck you very much, The issue is fixed in the recent code. so I will close the issue.

**Comment by yuwata** [comment]
> Thanck you very much, The issue is fixed in the recent code. so I will close the issue.

Oh, what a good news! Thank you for the confirmation.
