### ISSUE TITLE
systemd-backlight: Restore backlight after suspend

### ISSUE THREAD

**Issue by timakro** [systemd/systemd#21323]
**Is your feature request related to a problem? Please describe.**
On my laptop the backlight brightness resets to maximum when it resumes from suspend. This problem wasn't reported before so I presume on most laptops this doesn't happen?

**Describe the solution you'd like**
I suggest systemd-backlight should restore the brightness when the laptop resumes from suspend.

**Describe alternatives you've considered**
Maybe the EC firmware is responsible and it should be fixed there?

**The systemd version you checked that didn't have the feature you are asking for**

249

**Comment by poettering** [comment]
Not a systemd problem. Screen brightness should be saved/restored during suspend by the drivers, not by systemd. Please contact driver maintainers.
