### ISSUE TITLE
Dependabot is sometimes enabled on forks

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#21343]
According to https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates#enabling-version-updates-on-forks
> Version updates are not automatically enabled on forks when a dependabot.yml configuration file is present. This ensures that fork owners don't unintentionally enable version updates when they pull changes including a dependabot.yml configuration file from the original repository

but according to https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-737781797
> Dependabot version updates (setup from config file) isn't enabled by default on new forks but will be if security updates has ever been turned on and since disabled.

which means that apparently in some cases forks will receive PRs from Dependabot and the only workaround is

> The workaround for now is to delete the fork and re-create it without enabling Dependabot security updates

I don't think it affects a lot of forks but to be sure it would be great if all issues related to PRs from Dependabot could be discussed here.

To somewhat mitigate the issue the number of PRs Dependabot can create will be limited: https://github.com/systemd/systemd/pull/21342

**Comment by mrc0mmand** [comment]
Relevant upstream issues:
  * https://github.com/dependabot/dependabot-core/issues/2198
  * https://github.com/dependabot/dependabot-core/issues/2804

**Comment by eworm-de** [comment]
This one is really annoying... As the upstream issues are open for a long time already I guess this will not be fixed any time soon. 😒
So time to delete and recreate my fork?

**Comment by evverx** [comment]
> So time to delete and recreate my fork?

Unfortunately, it seems to be the only way to get rid of those PR

I'm not sure why it opened https://github.com/eworm-de/systemd/pull/4 and https://github.com/eworm-de/systemd/pull/5 though. Both those updates were blocked in https://github.com/systemd/systemd/pull/21505 and https://github.com/systemd/systemd/pull/21574.

**Comment by evverx** [comment]
I'm not sure if it helps but all those PRs are also auto-closed once forks get updated so in principle if PRs like https://github.com/eworm-de/systemd/pull/4 were blocked explicitly by using something like https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore in the systemd repository most forks updated at least once a week would never get Dependabot PRs.

**Comment by evverx** [comment]
Judging by https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/ it was fixed
