### ISSUE TITLE
implement `--output=json` for `systemctl show-environment`

### ISSUE THREAD

**Issue by jokeyrhyme** [systemd/systemd#21348]
**Is your feature request related to a problem? Please describe.**
- I'd like a consistent programmatic way to approach problems like https://github.com/systemd/systemd/issues/17340
- ultimately, I'm trying to move environment variable configuration out of my shell scripts and into systemd environment generators, however, this causes problems where not every shell is compatible with the way `systemctl show-environment` outputs values that contain spaces

**Describe the solution you'd like**
- I would like `systemctl show-environment --output=json` to output valid JSON

**Describe alternatives you've considered**
- some alternatives here: https://github.com/systemd/systemd/issues/17340
- otherwise, I suppose it's possible for me to write a program that is compatible with `systemctl show-environment`, but working JSON output from the 1st-party tooling unlocks so much potential here in a way that 3rd-party tooling will not

**The systemd version you checked that didn't have the feature you are asking for**

```
systemd 249 (249.6-3-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ
+ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by nootr** [comment]
If a maintainer approves this feature request, I'd love to implement it.

My idea (roughly) is to add a check for `--output=json*` to `src/systemctl/systemctl-set-environment.c:show_environment()` using `OUTPUT_MODE_IS_JSON` and - if true - create a `JsonVariant` object and print it using `json_variant_dump()`.
