### ISSUE TITLE
systemd-networkd cannot set hostname received from DHCP server

### ISSUE THREAD

**Issue by LubosD** [systemd/systemd#21363]
**systemd version**
 > systemd 249 (249.6-3-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.15.2-arch1-1`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > DHCP server provides a hostname and it gets set as the transient hostname on client machine.

**Unexpected behaviour you saw**
 > Nov 14 11:02:28 archlinux systemd[1]: Starting Network Configuration...
Nov 14 11:02:28 archlinux systemd-networkd[573]: eth0: Link UP
Nov 14 11:02:28 archlinux systemd-networkd[573]: eth0: Gained carrier
Nov 14 11:02:28 archlinux systemd-networkd[573]: lo: Link UP
Nov 14 11:02:28 archlinux systemd-networkd[573]: lo: Gained carrier
Nov 14 11:02:28 archlinux systemd-networkd[573]: eth0: Gained IPv6LL
Nov 14 11:02:28 archlinux systemd-networkd[573]: Enumeration completed
Nov 14 11:02:28 archlinux systemd[1]: Started Network Configuration.
Nov 14 11:02:28 archlinux systemd-networkd[573]: eth0: DHCPv4 address 10.10.10.18/24 via 10.10.10.3
Nov 14 11:02:29 archlinux systemd-networkd[573]: Could not set hostname: Interactive authentication required.

**Steps to reproduce the problem**
 > Have a DHCP server that assigns hostnames and create a file named `/etc/systemd/network/20-wired.network`:

```
[Match]
Name=eth0

[Network]
DHCP=yes
```

This issue is essentially a duplicate of #4646, but the fix done for that issue appears to have been removed since then.

Re-adding the [.rules file](https://github.com/martinpitt/systemd/blob/e8c0de91271331ddbae872de63d0a267d4f71e12/src/hostname/systemd-networkd-hostname.rules) from the original fix resolves the issue.

**Comment by yuwata** [comment]
Hm? We have https://github.com/systemd/systemd/blob/main/src/network/systemd-networkd.rules.
Is the file installed on your system?

**Comment by yuwata** [comment]
Maybe, packaging issue??

**Comment by yuwata** [comment]
Hm, the package has the rules file.
https://archlinux.org/packages/core/x86_64/systemd/

**Comment by LubosD** [comment]
Thanks for your hints, I've spotted the problem:

```
Nov 15 08:47:10 archlinux polkitd[719]: Loading rules from directory /etc/polkit-1/rules.d
Nov 15 08:47:10 archlinux polkitd[719]: Loading rules from directory /usr/share/polkit-1/rules.d
Nov 15 08:47:10 archlinux polkitd[719]: Error opening rules directory: Error opening directory “/usr/share/polkit-1/rules.d”: Permission denied (g-file-error-quark, 2)
```

And the permissions on that directory:
```
$ sudo ls -dl /usr/share/polkit-1/rules.d
drwxr-x--- 2 root video 4096 Nov 12 22:42 /usr/share/polkit-1/rules.d
```

The reason for this problem is that I used Gentoo Linux to install Arch Linux to an iSCSI disk (used for network booting), which has a different polkitd GID than Arch (so Arch sees it as group `video`). Therefore [this step](https://wiki.archlinux.org/title/Install_Arch_Linux_from_existing_Linux#Method_A:_Using_the_bootstrap_image_(recommended)) described on Wiki produces potentially incorrect results.

--> Not a systemd bug, but rather a documentation issue. I suppose `--numeric-owner` should be used there.
