### ISSUE TITLE
lack of md-raid support for /tmp mountpoint in /etc/fstab 

### ISSUE THREAD

**Issue by swestlake** [systemd/systemd#21370]
I've tried to scan through the issues archive and couldn't see anyone mentioning this other than the ability to disable tmp.mount ( #16894 )

when I perform a mask for tmp.mount to try to force the definition line of /tmp /etc/fstab... the system boots with "/" mounted as read-only.

upon further looking,  tmp.mount is a dependency of local-fs.target..
so I made a custom tmp.mount in /etc/systemd/system, and this solved the boot problem.

Apparently systemd is not honoring /tmp in /etc/fstab ...

on a more positive note,
 I noticed systemd-tmpfiles* service taking place for applying permissions for /tmp after I created and started my custom /etc/systemd/tmp.mount 

testing in a rescue target,
I can list /tmp (when not mounted) -- as having only permissions 755..

after I perform `systemctl start tmp.mount`,   /tmp is mounted and is automatically given 1777 sane permission bits due to these permissions being set somewhere in tmpfiles.d/*. This tells me tmpfiles.d is taking effect which I suppose is the whole point of making sure /tmp is working correctly for all user logins.

I don't know why I can't have /tmp working in fstab which I currently have disabled,

..though this is what I have tried previously,
(/etc/fstab)
UUID=___  /tmp  ext2 defaults  0 2
I also tried
UUID=___  /tmp  ext2 nodev  0 2
(fwiw these two examples can mount when manually typing `mount /tmp` in a rescue shell, and when / is remounted rw)

^ could it be that I need to specify x-systemd.* in order for tmp to be honored via fstab?

what are the plans regarding /tmp support in /etc/fstab ? is this a systemd design choice? bug? 

thanks

**Comment by swestlake** [comment]
adding the systemd build detail,
systemd version 247.3-6

if distribution matters, linux debian 11(latest)
thanks

**Comment by swestlake** [comment]
I should add for extra clarity what the post is about:

/tmp defined in /etc/fstab is not honored

instead what happens is /tmp becomes mounted as tmpfs rather than what is defined in /etc/fstab

**Comment by swestlake** [comment]
I did a comparison test to a vbox setup.
 /tmp in fstab passes for raw partitions.

Perhaps the reason why it is failing on the posted topic is because I am using /dev/md7  for /tmp -- which is a software md-raid1 device.

all my other mountpoints are working correctly, just not /tmp..

the UUID I am using is the one shown from "file -s /dev/md7".  All of my md-raids are defined in mdadm.conf and are never randomly assign to different /dev/md___ 

not sure what else I can add.

**Comment by poettering** [comment]
Any entry for /tmp in /etc/fstab actually takes precedence over the tmp.mount unit we ship. Don't mask anything: just define whatever you want for /tmp in /etc/fstab, it will take precedence. You#d only mask tmp.mount if you want nothing mounted there at all.

This looks more like a support issue, than a bug report (or feature request), if you have further questions, plesae contact the mailing list instead.

**Comment by poettering** [comment]
> all my other mountpoints are working correctly, just not /tmp..
> 
> the UUID I am using is the one shown from "file -s /dev/md7". All of my md-raids are defined in mdadm.conf and are never randomly assign to different /dev/md___

systemd has no explicit support for md raid. THis is up to the storage subsystems. Note that /tmp needs to be mounted *really* early, much earlier than other regular file systems. Maybe your distro's MD startup logic is not ready for that? consider asking your distro about that. Either way, systemd is not the culprit here, it might just be a flaw in your MD raid storage packages.

**Comment by swestlake** [comment]
I didn't do anything special, and reran commands again -- placing /tmp back into fstab.

it somehow is now working and I have no idea on what basis. strange.
(perhaps systemctl daemon-reload is broken?)

and I agree systemd is not the project to map raid devices --- I wonder what was causing this. I can only suspect "systemctl daemon-reload" is not doing its job correctly.

thanks for your responses, though the problem here I don't think it is distro -- I generally try to use the latest kernel that I can and try to avoid testing branches of software as part of the stable distros that I got running..

.. i realized the reportbugs for systemd are to reflect only the last 2 releases -- it was too late-- though I suppose this bug is still in the latest.

perhaps systemctl daemon-reload works better on the later releases, but that wouldn't roll out into my distribution for another while.

I think the flaw is in systemd -- though I would like systemd to continue to improve in this area of having better verbosity on the generator output regarding the "systemctl daemon-reload" command, because we users have no way to determine what it is actually performing. 

thanks

**Comment by swestlake** [comment]
systemctl cat tmp.mount --- easy enough to tell me fstab is working -- with /etc/systemd/system/tmp.mount deleted.

I don't need tech-support... there is a bug somewhere in systemd.

that's all I gotta say. :))

thanks
