### ISSUE TITLE
systemd can't create/mount runtime when using LUKS(dm-crypt)

### ISSUE THREAD

**Issue by rnz** [systemd/systemd#21375]
Have problem with LUKS (dm-crypt). After mount LUKS partition - /run/user/uid - not present and some application after login can't work (such as pulseaudio).

**systemd version the issue has been seen with**
```
systemd 248 (248.3-1ubuntu8)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Used distribution**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

**Linux kernel version used** (`uname -a`)
```Linux 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

**Expected behaviour you didn't see**
Right files in /run/user/UID/

**Unexpected behaviour you saw**
directory /run/user/UID/ not present

**Steps to reproduce the problem**
1) create LUKS partition 
2) create wrapper script for pam and make it executable:
```
# cat /usr/local/bin/cryptsetup_pam_wrapper
#!/usr/bin/env bash
IFS='' read -d '' -r stdstr < "${1:-/dev/stdin}"
CRYPT_USER="rnz"
DEVICE="/dev/disk/by-id/nvme-MODEL-part7z"
MAPPER="/dev/mapper/home-"$CRYPT_USER
if [ "$PAM_USER" == "$CRYPT_USER" ] && [ ! -e $MAPPER ]
then
   echo "$stdstr" | /usr/sbin/cryptsetup open $DEVICE home-$PAM_USER
   mount $MAPPER /home/rnz -t ext4 -o discard
fi
```
3) add wrapper to pam on auth
```
# grep cryptsetup /etc/pam.d/common-auth
auth    optional        pam_exec.so expose_authtok quiet /usr/local/bin/cryptsetup_pam_wrapper
```
4) login as user with password (password in shadow must be same as password for LUKS partition)

**Comment by poettering** [comment]
Sounds as if the PAM module pam_system.so is not in your PAM stack.

This is a PAM configuration issue, and not a systemd upstrem issue. If you have further questions please contact the systemd mailing list, where support questions are discussed.

(Or look at the logs, and make sure pam_systemd is in your PAM stack at the right places. There are plenty of docs about this, and your distro should do this for you anyway)
