### ISSUE TITLE
rtcwake for gnome-clock

### ISSUE THREAD

**Issue by axet** [systemd/systemd#21382]
**Is your feature request related to a problem? Please describe.**

Alarm Clock on linux not working in suspend mode. Linux supports for alarm clock in normal and suspend mode using rtcwake. But it does not works when system suspended by 'systemctl suspend' or lid closed.

**Describe the solution you'd like**

systemd should support gnome-clock (new API?) for alarms in suspend mode.

**Describe alternatives you've considered**

New alarms API using filesystem or dbus for alarm clocks.

**The systemd version you checked that didn't have the feature you are asking for**

249.5-2

EDIT: if alarm did't wake up user, notebook should go to suspend again. Support new API or direct Gnome Clock.

**Comment by spaetz** [comment]
To allow a user to resume a device from suspend, https://github.com/systemd/systemd/issues/17564 would probably need to be implemented, in order to be able to grant that capability to "systemd --user".

**Comment by poettering** [comment]
Closing, because #26548 was merged.
