### ISSUE TITLE
Please install dbus interface introspection xml files [RFE]

### ISSUE THREAD

**Issue by garyvdm** [systemd/systemd#21396]
It would be nice of the dbus introspection xml files for all systemd dbus services are installed to `/usr/share/dbus-1/interfaces`. I know one can pull it from the dbus server, but I find it more convenient to load it from the disk.

Thanks

**Comment by mrc0mmand** [comment]
This seems to be a duplicate of https://github.com/systemd/systemd/issues/20238.

**Comment by garyvdm** [comment]
Apologies for the duplicate
