### ISSUE TITLE
systemd-journal-upload fails and never resumes after Failed to move to next field in entry: Bad message

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#21407]
**systemd version the issue has been seen with**
 > 249.6-3

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)
 > `5.15.2-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd-journal-upload should be able to move past corrupt messages

**Unexpected behaviour you saw**
 > systemd-journal-upload failed and refused to ever continue until manual intervention. My primary issue is that the uploader should be able to skip any corrupt message. My second issue is that it actually failed on a journal-entry that seems perfectly fine. My workaround was to manually update the cursor in `/var/lib/systemd/journal-upload/state`

**Steps to reproduce the problem**
 > unknown

**Additional program output to the terminal or log subsystem illustrating the issue**

Uploader failing:
```text
systemd-journal-upload: Failed to move to next field in entry: Bad message
systemd-journal-upload: Upload to http://xxxx/upload failed: operation aborted by callback
systemd[1]: systemd-journal-upload.service: Scheduled restart job, restart counter is at 54644.
```

Content of journal showing `journalctl -c "$LAST_CURSOR" -o json -n3 |cat` (this should show the offending message, not sure why it only shows 2 lines instead of 3):
```
{"MESSAGE":"audit: type=1701 audit(1635413692.883:77691): auid=4294967295 uid=99 gid=99 ses=4294967295 pid=1879717 comm=\"php-7.3.32\" exe=\"xxx\" sig=11 res=1","__CURSOR":"s=a073513a93f74c4092fb43cdf2e627f2;i=5422e;b=0fc7f964ab7f48a2af9d7cb306804fe3;m=3356477aae0;t=5cf666c3a1365;x=e83c14b06ee24778","SYSLOG_FACILITY":"0","_HOSTNAME":"xxx","SYSLOG_IDENTIFIER":"kernel","_BOOT_ID":"0fc7f964ab7f48a2af9d7cb306804fe3","_SOURCE_MONOTONIC_TIMESTAMP":"3527832324093","PRIORITY":"5","__MONOTONIC_TIMESTAMP":"3527853714144","_MACHINE_ID":"f548e490a8794a558c2851018c04faa0","__REALTIME_TIMESTAMP":"1635413692912485","_TRANSPORT":"kernel"}
{"_PID":"1","_SOURCE_REALTIME_TIMESTAMP":"1635413724408653","_COMM":"systemd","CODE_FILE":"src/core/cgroup.c","_SYSTEMD_SLICE":"-.slice","__CURSOR":"s=a073513a93f74c4092fb43cdf2e627f2;i=5422f;b=0fc7f964ab7f48a2af9d7cb306804fe3;m=335665844aa;t=5cf666e1aad2f;x=469ce1a8b7fc2530","_HOSTNAME":"xxx","_SYSTEMD_UNIT":"init.scope","_MACHINE_ID":"f548e490a8794a558c2851018c04faa0","INVOCATION_ID":"2810c0dca3114a6f94a3cb97ca2dfb84","TID":"1","UNIT":"xxx","CODE_FUNC":"unit_check_oom","_SYSTEMD_CGROUP":"/init.scope","MESSAGE":"xxx: A process of this unit has been killed by the OOM killer.","SYSLOG_IDENTIFIER":"systemd","__MONOTONIC_TIMESTAMP":"3527885210794","_UID":"0","_TRANSPORT":"journal","_GID":"0","PRIORITY":"5","_CAP_EFFECTIVE":"1ffffffffff","_EXE":"/usr/lib/systemd/systemd","MESSAGE_ID":"fe6faa94e7774663a0da52717891d8ef","CODE_LINE":"2960","_BOOT_ID":"0fc7f964ab7f48a2af9d7cb306804fe3","_CMDLINE":"/usr/lib/systemd/systemd --system --deserialize 74","SYSLOG_FACILITY":"3","__REALTIME_TIMESTAMP":"1635413724409135"}
```

`journalctl --verify` does show some corruption due to filesystem issues so that might be the rootcause.

**Comment by DaanDeMeyer** [comment]
Could you post the output of journalctl --verify?

**Comment by SjonHortensius** [comment]
@DaanDeMeyer It shows various corruptions as already mentioned

```
3abbfe0: Invalid entry item (0/9 offset: 000000
3abbfe0: Invalid object contents: Bad message
File corruption detected at /var/log/journal/xxx/system@xxx.journal~:3abbfe0 (of 67108864 bytes, 91%)
```

I still think the uploader should be able to skip corrupt messages including this one

**Comment by DaanDeMeyer** [comment]
Could you run systemd-journal-upload with the `SYSTEMD_LOG_LEVEL=debug` environment variable set?

**Comment by SjonHortensius** [comment]
sure but there is no additional information except for all the entries that are processed fine (this is with a different cursor, but same issue):
```
...
Entry 1692623 (s=659bdd23b5d64cfd83d03ee47cc39e86;i=4911;b=16eb0f5c925149da8cdbbfd7f2ac95b0;m=189a9381163;t=5d0f0508fdb5d;x=d11a4c08bb81e3cc) has been uploaded.
Entry 1692624 (s=659bdd23b5d64cfd83d03ee47cc39e86;i=4912;b=16eb0f5c925149da8cdbbfd7f2ac95b0;m=189a9381163;t=5d0f0508fdb5d;x=3b4fd71f4d5041de) has been uploaded.
Attempt to move to object located in file header: 0
Failed to move to next field in entry: Bad message
* operation aborted by callback
* Closing connection 0
Upload to http://xxx/upload failed: operation aborted by callback
Closing journal input.
Root directory /run/log/journal removed.
Directory /var/log/journal/f548e490a8794a558c2851018c04faa0 removed.
Root directory /var/log/journal removed.
mmap cache statistics: 147470655 context cache hit, 3188601 window list hit, 457 miss
```

**Comment by DaanDeMeyer** [comment]
I think I have an idea on how we can improve this, will put up a PR.

**Comment by DaanDeMeyer** [comment]
If possible, could you test out https://github.com/systemd/systemd/pull/21420? You can either run systemd-journal-upload from the build directory or add an override for the service unit if there is one to change ExecStart= to point to the systemd-journal-upload binary in the build directory.
