### ISSUE TITLE
Scandinavian characters | No support

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#21416]
**systemd version the issue has been seen with**
 > 249.6

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)
 > `Linux fedora 5.14.17-301.fc35.x86_64 #1 SMP Mon Nov 8 13:57:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Scandinavian characters supported; 

**Unexpected behaviour you saw**
> Scandinavian characters not yet supported;  For instance _ä_ and _ö_ are respectively exhibited as "`<C3><A4>`" and "`<C3><B6>`"..

**Steps to reproduce the problem**
 > _Prerequisite_: translated expressions into **Finnish** are present on Weblate in Fedora dedicated profile for this component.

```
$ systemctl status network
* network.service - LSB: Bring up/down networking
(...)
(...) network[964]: Otetaan loopback-liit<C3><A4>nt<C3><A4> k<C3><A4>ytt<C3><B6><C3><B6>n: [ OK ]
```

**Comment by poettering** [comment]
This suggests your "less" pager isn't happy to display UTF8 chars. Please contact your distro/less maintainers. 

or maybe you have overriden the LESS/SYSTEMD_LESS env vars yourself?

either way, systemd is not causing this. (verify by passing --no-pager to the tool, to disable usage of "less")

**Comment by Ricky-Tigg** [comment]
Once the VM on QEMU was restarted the issue was no more observable.
