### ISSUE TITLE
systemd closes container /dev/console

### ISSUE THREAD

**Issue by aep** [systemd/systemd#21451]
**systemd version the issue has been seen with**
 > 249.6

**Linux kernel version used** (`uname -a`)
 > Linux d 5.15.1-1-ARCH #1 SMP Sun Nov 7 14:40:17 MST 2021 aarch64 GNU/Linux

**CPU architecture issue was seen on**
 > aarch64

**Unexpected behaviour you saw**

systemd boots fine within a container (unshare), but then after "[  OK  ] Reached target Graphical Interface." it closes /dev/console which closes the controling pty. 

    panic: read /dev/ptmx: input/output error

i'm unsure if this is intended behaviour, if yes it would be great if it was documented in
https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
specifically what kind of tty is expected in /dev/console. 
binding the host /dev/console seems to work fine, but that's of course not the intended use case with containers.

also just ignoring the EOF works, but it's unclear if this is intended

**Steps to reproduce the problem**

```
#!/bin/sh
set -ex

mkdir -p /tmp/sysd
mount none -t tmpfs /tmp/sysd
mkdir -p /tmp/sysd/root
mount --bind /  /tmp/sysd/root/ -o ro
mkdir -p /tmp/sysd/root/proc
mount none -t tmpfs /tmp/sysd/root/dev/

for i in null zero full random urandom tty ptmx
do
    touch /tmp/sysd/root/dev/$i
    mount --bind /dev/$i /tmp/sysd/root/dev/$i
done

touch /tmp/sysd/root/dev/console
mount --bind $(tty)  /tmp/sysd/root/dev/console
mount --bind /sys     /tmp/sysd/root/sys -o ro
mount --bind /proc   /tmp/sysd/root/proc -o ro

container=docker unshare --mount-proc -pf -R /tmp/sysd/root /usr/lib/systemd/systemd
```

**Comment by poettering** [comment]
Any TTY is fine. if you make it a pty just make sure you don't close the pty master while the container runs, otherwise /dev/console cannot be reopened anymore...

PID1 during runtime will close all ttys, to avoid being killed by SAK: it only opens ttys for the time it actually needs to print something. If reopening the tty then fails later that suggests a problem in your container environment.

Not sure we need to document that more, a "suitable" TTY means a working one, but a pty whose master side is closed is certainly *not* a working one...

**Comment by poettering** [comment]
(bind mounting stuff in /dev/ is typically not a good idea since container and host uids/gids might be different.)

Also, why not just use a proper container manager, such as nspawn? it handles all this stuff automatically.

**Comment by aep** [comment]
> Not sure we need to document that more, a "suitable" TTY means a working one, but a pty whose master side is closed is certainly _not_ a working one...

specifically i'm suggesting to document that the master must not be closed when the slave is closed. But you could argue this is implicit if you know that systemd behaves this way intentionally. (which i didnt know)

 > PID1 during runtime will close all ttys, to avoid being killed by SAK: it only opens ttys for the time it actually needs to print something.

thanks, this exact sentence would be helpful in the docs.
please close if you disagree its useful.

> such as nspawn?

nspawn has a different use case and lacks the features i need. I'm just migrating chroots to systemd instead of using a custom init, since systemd does generally do init better.  nspawn seems to be built around real containers, i.e. docker.

**Comment by bluca** [comment]
Can you send a PR to update the docs?

**Comment by aep** [comment]
> Can you send a PR to update the docs?

of course
