### ISSUE TITLE
sd-umount: failed to unmount /oldroot Device or resource busy

### ISSUE THREAD

**Issue by Dragon20C** [systemd/systemd#21465]
**systemd version the issue has been seen with**
 > systemD 249.6-3

**Used distribution**
 > Manjaro KDE

 > `5.15.2-2-MANJARO`
I have tried other kernels and it produces the same result

**CPU architecture issue was seen on**
 > Zen+ R5 1600 AF

**Expected behaviour you didn't see**
 > To shutdown without errors

**Unexpected behaviour you saw**
 > Error message appears at shutdown
sd-unmoun[2736] : failed to unmount /oldroot : Device or resource busy
sd-unmoun[2737] : failed to unmount /oldroot /sys: Device or resource busy
shutdown[1]: failed to finalize file system, ignoring

**Steps to reproduce the problem**
 > shutdown the system.

**Additional program output to the terminal or log subsystem illustrating the issue**

Things I have tried to resolve the issue, I have done a clean install of manjaro kde and the issue still exists, I have had others on the manjaro forum complain about the exact same issue and the pattern is, people with nvidia gpus, forum: (https://forum.manjaro.org/t/updated-system-and-now-every-shutdown-an-error-message-keeps-popping-up-error-sd-umount-failed-to-unmount-oldroot/91253)

I am throwing guesses here but I assume something to do with nvidias new driver 495.44-4, but I have tried downgrading to a older driver 470 and it produces the same issue Im not sure if systemD some how miss-configured nvidia or maybe its a completely different issue

I did a search on the issue tab and I have noticed that there is a lot of similar issues but they are closed, I dont know if that means the issue is fixed or its not systemD´s fault.
but I dont notice any posts with the latest of systemD.

![Screenshot_20211120-115710](https://user-images.githubusercontent.com/15175043/142844046-b4b73ab7-41b2-431b-927d-263faba3ba71.png)
.

**Comment by poettering** [comment]
Sorry, but systemd just reports the issue here, but is not the culprit. Something is pinning your file systems /oldroot/ until the very end. Try to figure out what that is. 

Please talk to your distro for help about this, they'll help you, as initrd handling is really a distro thing.

**Comment by Dragon20C** [comment]
@poettering sorry for bothering you, I figured out the culprit, it seems to do with the proprietary nvidia driver after changing to the open source driver the error no longer exists, so I have a question, what does this error mean exactly, if the culprit is nvidia does this mean systemD failed to stop the process, my understanding of systemD is that it starts and stops processes, so could this error suggest it couldnt stop the nvidia process, please correct me if I am wrong, thank you.

**Comment by poettering** [comment]
no idea what nvidia does, but /oldroot is presumably something from the initrd, and some driver component keeps that busy for some reason. No idea really, ask your distro/nvidia for help, i really don't know

**Comment by Paulie420** [comment]
I have the same issue today, but I have no nvidia card or drivers - I have been playing around with Plymouth (bootloader) and it showed up after that. Maybe that rings a bell, or???

**Comment by Paulie420** [comment]
I have read to add 'shutdown' to my hooks in /etc/mkinitcpio.conf file; I had recently added 'plymouth' to my HOOKS, and they currently read:
HOOKS=(base udev plymouth autodetect modconf block filesystems keyboard fsck)

Does adding 'shutdown' to the end of HOOKS and running 'mkinitcpio -p linux' seem like a way to fix this issue, or... and I barking up the wrong search-google-for-some-fix tree?

**Comment by lolcabanon** [comment]
I have the exact same error message since a couple of days.
I run Manjaro KDE with nvidia gpu.

The problem happened after my PC crashed because it was full ("0mb of space left" message showed up). I had to boot from live usb and remove some stuff, then restore a Timeshift backup to make it work like before (except this message showing now).

Also, Kodi will crash after showing the main screen for a sec since then. The log show a `SIGSEGV` error thrown by `usr/lib/libpython3.10.so.1.0`.

I don't know yet if it is related, but if anybody has anything to say about this error, I'll take it!
