### ISSUE TITLE
missing bash completion for journalctl --facility

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#21484]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000464

https://github.com/systemd/systemd/commit/196dedd50300e600a0b053af46fdcde6cb2c3034 added support for `journalctl --facility`.
bash-completion should probably be updated accordingly

**Comment by jidanni** [comment]
By the way:
Man page shows mandatory '=', but...

```
# journalctl --help|grep since
  -S --since=DATE            Show entries not older than the specified date
# journalctl --sin<TAB>
# journalctl --since [cursor]
How about:
# journalctl --since=[cursor]
```
Version: 1:2.11-5

P.S., also help the user complete "yesterday".

**Comment by keszybz** [comment]
"=" is not mandatory. I guess the completion could be fixed to insert it automatically, but shell completions are black magic that nobody wants to touch unless absolutely necessary.

**Comment by jidanni** [comment]
man and --help make "=" look mandatory,
but completions instead use " ",
causing the user to think he is about to enter an invalid command.

**Comment by keszybz** [comment]
I don't think this is much of a problem. All commonly used option parsers make "=" optional for long options, and users generally know about this.

**Comment by jidanni** [comment]
No way!
Either use what is documented,
or document what is used.
