### ISSUE TITLE
Mention GitHub somewhere on the manpage(s)

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#21490]
```
$ man systemd|col -b|grep github -ci
0
$ uname -a
Linux jidanni5 5.15.0-1-amd64 #1 SMP Debian 5.15.3-1 (2021-11-18) x86_64 GNU/Linux
```

**Comment by poettering** [comment]
Why though? 

There's a link to the homepage of system, and that links up github in many ways.

**Comment by jidanni** [comment]
Because of all the
```
$ man systemd|col -b|grep http
           https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt
           http://0pointer.de/blog/projects/systemd.html
           https://systemd.io/PORTABILITY_AND_STABILITY/
           https://systemd.io/CONTAINER_INTERFACE
           https://systemd.io/INITRD_INTERFACE/
           http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
           https://systemd.io/ENVIRONMENT
           https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html
           https://www.kernel.org/doc/Documentation/cgroup-v1/
           https://www.freedesktop.org/wiki/Software/systemd/
```
nowhere is it mentioned where to send bug reports.

These days people look for a GitHub link, so give it to them, please, with no poking around needed.

**Comment by poettering** [comment]
I am not sure the man page is the right place to tell users where to report bugs. In particular as the primary place to report them to is actually the distribution, not the upstream project. And the upstream bug tracker it is linked from the systemd homepage itself, which *is* linked from the man page.
