### ISSUE TITLE
Say "This subset of the Journal begins at..."

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#21491]
Here on the second run, the user shakes his head "those guys got the "begins" wrong!
```
# journalctl                  |head -n 2
-- Journal begins at Fri 2021-09-03 05:27:23 CST, ends at Tue 2021-11-23 21:58:15 CST. --
Sep 03 05:27:23 jidanni5 systemd[769]: mnt-usb-debs.mount: Succeeded.
# journalctl --since=yesterday|head -n 2
-- Journal begins at Fri 2021-09-03 05:27:23 CST, ends at Tue 2021-11-23 21:58:15 CST. --
Nov 22 00:00:38 jidanni5 systemd[1]: Starting Daily apt-show-versions index rebuild...

systemd 249 (249.7-1)
```
So perhaps on the second run, say instead
**This subset of the** Journal begins at **(different relevant date than first run)**

See also
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962216

Yes, we now know you originally meant "Journals are available since (first run date)",
but most users will think still using the first date even though we specified a subset
shows a sort of disjuncture between the first line and the rest.

**Comment by keszybz** [comment]
"This subset" would be even more confusing, because the reader would think that "this subset" is the subset being shown.

**Comment by mbiebl** [comment]
Yeah, I think this would be confusing as well.

The only thing I could think of to make this "clearer" is to simply drop the header "-- Journal begins" when `--since` is used

**Comment by keszybz** [comment]
Would "Journal entries **available** from … until …" be better?

**Comment by jidanni** [comment]
How about making the header an opt-in --option perhaps.
Else with just
$ journalctl
it usually is just the same as the first entry' time.

And with other slices the user doesn't need to be reminded about the maximum range available.

**Comment by keszybz** [comment]
We could have an option to not insert any lines with "--"… I'm actually surprised that we don't have one already.

**Comment by jidanni** [comment]
Well then
$ journalctl --no--lines --etc
would throw the baby (other -- lines) out with the bathwater (the confusing -- line we are discussing),
and also would necessitate
$ journalctl --boot --no--lines
to just remove the confusing line, which shouldn't be added, because it is talking about a different (complete) slice in the first place.
