### ISSUE TITLE
stub resolver does not forward query on hostname (non-FQDN?) to (link) DNS server

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#21507]
**systemd version the issue has been seen with**
 > 249.7

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux gtbook 5.15.4-arch1-1 #1 SMP PREEMPT Sun, 21 Nov 2021 21:34:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > query on hostname (which is not an "FQDN"?) like `archlinux` or `gtbook` should at least be forwarded to the link DNS servers

**Unexpected behaviour you saw**
 > such query only works if LLMNR is enabled *and working* (i.e. not blocked by firewall)

**Steps to reproduce the problem**
 ```
[tom@gtbook ~]$ resolvectl
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
Fallback DNS Servers: 1.1.1.1#cloudflare-dns.com 9.9.9.10#dns.quad9.net 8.8.8.8#dns.google 2606:4700:4700::1111#cloudflare-dns.com 2620:fe::10#dns.quad9.net
                      2001:4860:4860::8888#dns.google

Link 2 (wlan0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1
[tom@gtbook ~]$ nslookup archlinux
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find archlinux: SERVFAIL

[tom@gtbook ~]$ nslookup archlinux 192.168.1.1
Server:		192.168.1.1
Address:	192.168.1.1#53

Name:	archlinux
Address: 192.168.1.140

[tom@gtbook ~]$ 
```

<!-- ```text
…
``` -->

I found out this problem when I notice that one needs an explicit accept rule in nftables for LLMNR (or maybe multicast DNS in general) to work, apparently. It can't rely on the "established" ct state rule. Wonder if I should file a bug report to them as well...

**Comment by poettering** [comment]
We don't do this for security reasons, and this is documented in detail:

https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Compatibility%20with%20the%20traditional%20glibc%20stub%20resolver

And that also includes a note on how to disable this safety precaution.
