### ISSUE TITLE
Systemd - Template, This process can't be executed

### ISSUE THREAD

**Issue by clems09** [systemd/systemd#2151]
I,

I haved a work to do in my class with systemd templates.

I need to make a service that will erase log fill in a log directory at boot time. For exemple /var/log/squid/.

I need to erase logs of 3 differents directory. And I need one systemd file.

i have create my "rmlog@.service" file in "/etc/systemd/system".

my "rmlog@.service" look like that :

```
        [Unit]
        Description=Suppressions des fichiers contenus dans /var/log/X

        [Service]
        Type=oneshot
        ExecStart=/etc/TP/%i.sh

        [Install]
        WantedBy=default.target
```

My logs says "this process /etc/TP/%i.sh can't be executed"

Anyone can help me ?

Thanks

**Comment by sztanpet** [comment]
see the manual http://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
where it says `For each of the specified commands, the first argument must be an absolute path to an executable.`

**Comment by evverx** [comment]
@sztanpet, `/etc/TP/%i.sh` is an absolute path:)

@clems09 , see http://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines

> The command line accepts "%" specifiers as described in systemd.unit(5). Note that the first argument of the command line (i.e. the program to execute) may not include specifiers.

Try, `ExecStart=/bin/bash /etc/TP/%i.sh`

BTW: there is a mailing list: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
Ask your questions here.
But: [Before You Ask](http://www.catb.org/esr/faqs/smart-questions.html#before)

**Comment by clems09** [comment]
Thanks for your reply, 

@evverx that's work for me thanks very much !!!
