### ISSUE TITLE
systemd.exec: mounts parent directories created as root-owned with service UMask (unaccessible mountpoints)

### ISSUE THREAD

**Issue by martinetd** [systemd/systemd#21548]
**systemd version the issue has been seen with**
systemd 249.5

**Used distribution**
nixos - issue briefly discussed in https://github.com/NixOS/nixpkgs/issues/147599 where @aszlig suggested a workaround, but I think it's just a rare usecase that might be better addressed in systemd itself

**Linux kernel version used** (`uname -a`)
`Linux myhostname 5.10.79 #1-NixOS SMP Fri Nov 12 13:58:35 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
systemd creates missing parent directories for mounts such as BindPaths or BindReadOnlyPaths.
The problem arises when a service uses a restrictive UMask such as 0077 and a non-root User, such parent directories are then created as root:root (I don't believe they should be owned otherwise), but they will respect the UMask so in this case it will be 0700 and thus the bind mount itself will not be accessible.
I believe the "root" created files should use whatever umask systemd sees fit to use, not service's UMask, as it doesn't make sense to have the mount points we just created be inaccessible.

**Steps to reproduce the problem**
This can be illustrated with systemd-run. I've used a statically linked busybox to inspect the content of the chroot but /usr could have been preserved... Anyway

1/ failing example
```
# systemd-run --unit=umask-test.service -p "UMask=0077" -p "User=nobody" \
    -p "TemporaryFileSystem=/" -p "BindReadOnlyPaths=/usr/bin" -G \
    /usr/bin/sleep infinity
Running as unit: umask-test.service
# journalctl -u umask-test.service
Nov 28 09:03:37 odin systemd[1]: Started /usr/bin/sleep infinity.
Nov 28 09:03:37 odin systemd[1]: umask-test.service: Main process exited, code=exited, status=203/EXEC
Nov 28 09:03:37 odin systemd[1]: umask-test.service: Failed with result 'exit-code'.
```
2/ workaround: add these automatically created directories as TemporaryFileSystems
```
# systemd-run --unit=umask-test.service -p "UMask=0077" -p "User=nobody" \
    -p "TemporaryFileSystem=/ /usr" -p "BindReadOnlyPaths=/usr/bin" -G \
    /usr/bin/sleep infinity
Running as unit: umask-test.service
# systemctl stop umask-test.service
Nov 28 08:19:03 odin systemd[1]: Started /usr/bin/sleep infinity.
Nov 28 08:19:09 odin systemd[1]: Stopping /usr/bin/sleep infinity...
Nov 28 08:19:09 odin systemd[1]: umask-test.service: Deactivated successfully.
Nov 28 08:19:09 odin systemd[1]: Stopped /usr/bin/sleep infinity.
```
3/ inspection with busybox
```
# systemd-run --unit=umask-test.service -p "UMask=0077" -p "User=nobody" \
    -p "TemporaryFileSystem=/" -p "BindReadOnlyPaths=/usr/bin /busybox" -G \
    /busybox sleep infinity
Running as unit: umask-test.service
# nsenter -a -t "$(systemctl show --property MainPID --value umask-test.service)" \
    /busybox sh
/ # /busybox ls -l /
total 988
-rwxr-xr-x    1 0        0          1009896 Nov 27 23:01 busybox
drwx------    3 0        0               60 Nov 28 00:04 run
drwx------    3 0        0               60 Nov 28 00:04 usr
/ # exit
# systemctl stop umask-test.service
```

**Additional details**

strace of the failure does everything successfully then just can't exec the binary, which has been quite confusing to me...
```
09:16:35.566938 umask(077)              = 000
09:16:35.566981 getuid()                = 0
09:16:35.567023 getgid()                = 0
09:16:35.567064 setregid(65534, -1)     = 0
09:16:35.567118 setreuid(65534, -1)     = 0
...
09:16:35.604161 openat(AT_FDCWD, "/run/systemd/unit-root/usr/bin", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
09:16:35.604202 newfstatat(AT_FDCWD, "/run/systemd/unit-root/usr", 0x7fffa2554cf0, 0) = -1 ENOENT (No such file or directory)
09:16:35.604240 mkdir("/run", 0755)     = -1 EEXIST (File exists)
09:16:35.604276 mkdir("/run/systemd", 0755) = -1 EEXIST (File exists)
09:16:35.604324 mkdir("/run/systemd/unit-root", 0755) = -1 EEXIST (File exists)
09:16:35.604361 mkdir("/run/systemd/unit-root/usr", 0755) = 0
09:16:35.604399 newfstatat(AT_FDCWD, "/usr/bin", {st_mode=S_IFDIR|0755, st_size=16, ...}, 0) = 0
09:16:35.604438 mkdir("/run/systemd/unit-root/usr/bin", 0755) = 0
09:16:35.604477 openat(AT_FDCWD, "/run/systemd/unit-root/usr/bin", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 4
09:16:35.604514 mount("/usr/bin", "/proc/self/fd/4", NULL, MS_BIND|MS_REC, NULL) = 0
...
09:16:35.611175 execve("/usr/bin/sleep", ["/usr/bin/sleep", "infinity"], 0x55a931dc1820 /* 7 vars */) = -1 EACCES (Permission denied)
```

I believe these directories are created in `src/core/namespace.c` in the retry code (strace shows open failing once with ENOENT, creating parents and finally doing the same open+mount), so `mkdir_parents(mount_entry_path(m), 0755);`, which ultimately does this bunch of mkdir()s. mkdir() can't specifically ignore umask so it'd be a dance of resetting and restoring umask which is a bit annoying, perhaps setting umask later (just before execve) might make more sense?
In my strace I see a few other mkdirs, but nothing that seems bad if it were created with a more open umask (first number is line number in strace file for this process):
```
92:09:16:35.566938 umask(077)              = 000
108:09:16:35.567705 mkdir("/run/systemd", 0755) = -1 EEXIST (File exists)
110:09:16:35.567803 mkdir("/run/systemd/unit-root", 0700) = -1 EEXIST (File exists)
113:09:16:35.568063 mkdir("/run/systemd/propagate/umask-test.service", 0600) = -1 EEXIST (File exists)
123:09:16:35.569755 mkdir("/run/systemd/unit-root/", 0755) = -1 EEXIST (File exists)
(sidetracked note: this one is redundant with the previous that had mode 0700...)
614:09:16:35.603371 mkdir("/run", 0755)     = -1 EEXIST (File exists)
615:09:16:35.603408 mkdir("/run/systemd", 0755) = -1 EEXIST (File exists)
616:09:16:35.603447 mkdir("/run/systemd/unit-root", 0755) = -1 EEXIST (File exists)
617:09:16:35.603483 mkdir("/run/systemd/unit-root/run", 0755) = 0
618:09:16:35.603522 mkdir("/run/systemd/unit-root/run/systemd", 0755) = 0
620:09:16:35.603599 mkdir("/run/systemd/unit-root/run/systemd/incoming", 0755) = 0
637:09:16:35.604240 mkdir("/run", 0755)     = -1 EEXIST (File exists)
638:09:16:35.604276 mkdir("/run/systemd", 0755) = -1 EEXIST (File exists)
639:09:16:35.604324 mkdir("/run/systemd/unit-root", 0755) = -1 EEXIST (File exists)
640:09:16:35.604361 mkdir("/run/systemd/unit-root/usr", 0755) = 0
642:09:16:35.604438 mkdir("/run/systemd/unit-root/usr/bin", 0755) = 0
```

Anyway, I've flagged this as bug because I think directories being inaccessible is a bug, but I'm open to discussion. What do you think?

**Comment by bluca** [comment]
Can you try from latest main? There were some changes recently to restrict the effect of the umask setting when doing the setup

**Comment by martinetd** [comment]
Oh, it looks like that's exactly what I wanted.

My test environment isn't flexible enough to do a strace and check in details, but intermediate directory seems to have been created appropriately as 755:
```
drwxr-xr-x 3 0 0 60 Jan  1 00:00 nix
```
and service started successfully.

Thanks!
