### ISSUE TITLE
systemd-boot crashes at startup if a random seed exists.

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#21556]
**systemd version the issue has been seen with**

```
➜ systemctl --version
systemd 249 (249.r2481.gf5caacec1c-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

The issue seems to have been introduced somewhere in `249.r1643.g48538c19e5-1` -> `249.r2481.gf5caacec1c-1`.

**Used distribution**

ArchLinux

**Linux kernel version used** (`uname -a`)

 > `Linux victory 5.15.5-arch1-1 #1 SMP PREEMPT Thu, 25 Nov 2021 22:09:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 
amd64

**Expected behaviour you didn't see**

System boots fine

**Unexpected behaviour you saw**

Early startup crashes. Very very early.

**Steps to reproduce the problem**

Boot with systemd-boot.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd-boot assertion 'rng' failed at ..systemd/src/boot/efi/random-seed.c:130,  function mangle_random_seed(). Halting.
```

Deleting `/efi/loader/random-seed` makes the next boot continue. This file is re-created, and if I ever forget to delete it, the next startup fails.

**Comment by medhefgo** [comment]
Can you check if the PR fixes this?

**Comment by WhyNotHugo** [comment]
It works! Thanks!
