### ISSUE TITLE
Repeated journald crashes

### ISSUE THREAD

**Issue by goeranu** [systemd/systemd#2155]
During the night, the journald process crashed several times.  27 core files lay in my /var/lib/systemd/coredump now, the first one from 01:30 and the last one 08:03.

When I investigated at the end of the period, a mdraid resynchronization was also running, making I/O very sluggish.  This may or may not have been related.  It is now around 8 hours since the resync ended, and there hasn't been any further crashes.

Looking at the backtraces, many end in various file system operations, like ftruncate (e.g. pid 8974), or getdents (e.g. pid 10809).  That might indicate a connection to the slow response during the resync.  But there were also several that crashed in memset (e.g pid 610, the first crash), which would not appear to be related to a slow disk response.

There were no explanations in the journal.  That may not be surprising since it was journald itself crashing.  But I still run syslog too, and in /var/log/messages I found the pattern below repeated over and over.

This happens on a Fedora system with systemd-222-8.fc23.x86_64.

As there were different backtraces, I can't say for sure all these are because of the same problem.  But the proximity in time makes me belive there is **some** kind of connection.  I attach a tar file with all the cores, so you have whatever might be needed.

```
Dec 13 05:28:48 mimmi journal: Permanent journal is using 3.2G (max allowed 4.0G, trying to leave 4.0G free of 170.1G available → current limit 4.0G).
Dec 13 05:28:48 mimmi systemd-coredump[8970]: Detected coredump of the journal daemon itself, diverted to /var/lib/systemd/coredump/core.systemd-journal.0.352695e5a66440faad208d9f8b0c5fd3.8584.1449980924000000.xz.
Dec 13 05:28:48 mimmi journal: Journal started
Dec 13 05:28:48 mimmi systemd: systemd-journald.service: Watchdog timeout (limit 1min)!
Dec 13 05:28:48 mimmi audit: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:syslogd_t:s0 pid=8584 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" sig=6
Dec 13 05:28:48 mimmi audit: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Dec 13 05:28:48 mimmi audit: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 05:28:48 mimmi audit: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 05:28:48 mimmi audit: CONFIG_CHANGE audit_enabled=1 old=1 auid=4294967295 ses=4294967295 subj=system_u:system_r:syslogd_t:s0 res=1
Dec 13 05:28:48 mimmi audit: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=mrtg comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Dec 13 05:28:48 mimmi audit: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

[coredumps.zip](https://github.com/systemd/systemd/files/60486/coredumps.zip)

**Comment by evverx** [comment]
Looks like https://github.com/systemd/systemd/issues/1804
Fixed: https://github.com/systemd/systemd/commit/4de2402b603ea2f518f451d06f09e15aeae54fab

**Comment by evverx** [comment]
Maybe, https://github.com/systemd/systemd/commit/c2fc2c2560f0ca0fab383753c065e45d76f465e5

**Comment by goeranu** [comment]
Just so I understand what you are saying: you believe all crashes, regardless of traceback, are because of the timeout, right?

Looking further back in my logs, I see occasional occurrences of the _Watchdog timeout_ messages, almost (but not quite) always accompanied by the _Detected coredump_ message.  I take it the watchdog intentionally makes the service crash.

I've tweaked my local configuration to increase the timeout.  Thanks for the pointer!

**Comment by evverx** [comment]
> you believe all crashes, regardless of traceback, are because of the timeout, right?

Oh, sorry. Yes.

> I've tweaked my local configuration to increase the timeout. Thanks for the pointer!

I think, It's a workaround (and it works:))

BTW:
There is a PR: [journal: asyncify journal_file_close()](https://github.com/systemd/systemd/pull/2125).
But according to https://github.com/systemd/systemd/pull/2125#commitcomment-14874524

> It's really not that simple... journal_file_close() internally makes use of the "mmap cache" logic, which is not thread-safe...

**Comment by goeranu** [comment]
Got it, thanks!  (I've subscribed to the PR to see what more might happen.)

**Comment by poettering** [comment]
Yeah, looks like watchdog timeouts, i.e. as tracked before on #1804. closing.
