### ISSUE TITLE
ConditionDirectoryNotEmpty doesn't run as expected when it comes to a Non-directory file

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#21561]
**systemd version the issue has been seen with**
 > systemd-248~rc2

**Used distribution**
 > Fedora release 34 (Thirty Four)

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 >
The test.service shouldn't be started when /tmp/filename is not a dir.
[root@fedora system]# cat test.service
#/etc/systemd/system/test.service
[Unit]
Description="Test ConditionDirectoryNotEmpty"
ConditionDirectoryNotEmpty=/tmp/filename

**Unexpected behaviour you saw**
 > …
![image](https://user-images.githubusercontent.com/56221695/143883642-f137641e-dac3-40be-a257-4f9abd067fb3.png)

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by jcg190701** [comment]
https://github.com/systemd/systemd/pull/21559

**Comment by layus** [comment]
Just as a fun note, there are always people relying on the most buggy behaviors. This patch managed to break the Nix install script that uses a ListenStream located under ConditionDirectoryIsReadWrite and does not care if the directory does not exist, as systemd creates all the path components to the socket, with read-write permissions (for root). I do not think anyone on the nix side ever realized they were relying on that specific behavior. See https://github.com/NixOS/nix/issues/5909
Thanks for the fix ! the world makes a bit more sense now :-D.
