### ISSUE TITLE
networkd kills long-lived IPv6 connections

### ISSUE THREAD

**Issue by Jookia** [systemd/systemd#21593]
**systemd version the issue has been seen with**
 > master

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > Linux titan 5.15.4-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 21 Nov 2021 21:34:35 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Long-lived SSH connections stay alive

**Unexpected behaviour you saw**
 > The SSH connection stops responding

**Steps to reproduce the problem**
1. Enable temporary IPv6 addresses on an interface
2. Open an SSH connection using the temporary IPv6 (you can set the source address manually)
3. Wait until the address rotates
4. Watch as the SSH connection stops responding

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

Additional context is this is directly related to #21571

**Comment by yuwata** [comment]
Yeah... The issue is exactly caused by #21571. Unfortunately, I have no idea to fix #19838 without causing this issue right now.

This issue is more serious than #21571. So, if I cannot find any good way until v250 release, I will simply revert #21571.

**Comment by yuwata** [comment]
Note for myself: see https://github.com/systemd/systemd/pull/21571#issuecomment-982832406.

**Comment by Jookia** [comment]
I found that if you set temp_prefered_lft to 300, you can now expire temporary addresses a lot faster. regen_max_retry doesn't seem to help with this.

**Comment by yuwata** [comment]
If you set temp_prefered_lft to 300, then regen_max_retry must be enough smaller than that value, say ~30.

**Comment by Jookia** [comment]
I'm having trouble doing controlled tests to reproduce the race with a low temp_prefered_lft.
