### ISSUE TITLE
Add support for custom routing table

### ISSUE THREAD

**Issue by cdauth** [systemd/systemd#2160]
On Linux, custom routing tables can be created in addition to the main routing table. This is useful for setting up route policies, for example so that packages with a certain source IP address take a specific route.

With iproute2, custom route tables can be configured by first naming them in `/etc/iproute2/rt_tables` (for example by adding the line `200 myroute`), and then using the table name in the `table` parameter (for example `ip route add default via 192.168.0.1 table myroute` and `ip route show table myroute`).

As far as I know, systemd-networkd does not currently provide an option to configure custom routing tables. It would be nice to have something like a `Table=` options in the `[ROUTE]` section of systemd.network.

**Comment by ssahani** [comment]
The rtm_table which we need to modify is a unsigned char not a string.  ip routes reads /etc/iproute2/rt_tables and maps the number to the name here 200 as mytable.

```
[ROUTE] 
Table=200 mytable
```

I guess above would be the syntax to go for networkd.
@cdauth ?

**Comment by poettering** [comment]
Implemented by #3132.
