### ISSUE TITLE
network: is IPv4LL address stable?

### ISSUE THREAD

**Issue by rakesh1225** [systemd/systemd#21610]
I am using an embedded board with customized linux on it configured with static IP and  link local address. 
Currently we are allowing the user to configure the static IP only through HMI by editing the network service files in backend. This is working fine.

Since static IP is user configurable, we are trying to keep a fixed IP address to access the device locally. So planned to use Linklocaladdress for this.

**Required: We need the linklocal address to be same always.**
**Issue: Link local address is generated differently to the same embedded board in two scenarios:**
          1) when the board is connected to router (example LinkLocal address: 169.20.20.1)
          2) when the board is connected to the PC directly(peer to peer) (example LinkLocal address 169.204.123.34).

Network config file configuration used:

[Match]
Name=xxxx

[Link]
RequiredForOnline=no

[Network]
LinkLocalAddressing=ipv4
Address=xxxxxx/24
DNS=xxxxxxx

Please let me know if there is any option to keep the linklocaladdress same always and should not be changed automatically.

**Comment by yuwata** [comment]
The seed for generating IPv4LL is determined by the machine-ID and interface's predictable names: 
1. `ID_NET_NAME_ONBOARD` udev property, 
2. `ID_NET_NAME_SLOT` udev property, 
3. `ID_NET_NAME_PATH` udev property, 
4. `ID_NET_NAME_MAC` udev property,
5. interface name.

So, if udevd is running and the persistent names are preserved, the same IPv4LL address should we obtained, of course there is no conflict with other nodes.

So, please confirm the following:
- is systemd-udevd running on the system?
- is the machine-ID is unique?

**Comment by rakesh1225** [comment]
is systemd-udevd running on the system?
  Yes, systemd-udevd is running on the device
is the machine-ID is unique?
   Yes, Machine-ID is unique for each network port

**Comment by yuwata** [comment]
> 1) when the board is connected to router (example LinkLocal address: 169.20.20.1)
> 2) when the board is connected to the PC directly(peer to peer) (example LinkLocal address 169.204.123.34).

Hmm??? Is the address is really assigned by networkd's IPv4LL mechanism? We pick an address from 169.254.0.0/16.

**Comment by yuwata** [comment]
Please also provide the version of systemd.

**Comment by davin67** [comment]
> I am using an embedded board with customized linux on it configured with static IP and  link local address. 
> Currently we are allowing the user to configure the static IP only through HMI by editing the network service files in backend. This is working fine.
> 
> Since static IP is user configurable, we are trying to keep a fixed IP address to access the device locally. So planned to use Linklocaladdress for this.
> 
> **Required: We need the linklocal address to be same always.**
> **Issue: Link local address is generated differently to the same embedded board in two scenarios:**
>           1) when the board is connected to router (example LinkLocal address: 169.20.20.1)
>           2) when the board is connected to the PC directly(peer to peer) (example LinkLocal address 169.204.123.34).
> 
> Network config file configuration used:
> 
> [Match]
> Name=xxxx
> 
> [Link]
> RequiredForOnline=no
> 
> [Network]
> LinkLocalAddressing=ipv4
> Address=xxxxxx/24
> DNS=xxxxxxx
> 
> Please let me know if there is any option to keep the linklocaladdress same always and should not be changed automatically.
>

**Comment by yuwata** [comment]
Ah... Maybe, I completely misunderstand the original comment...

> Please let me know if there is any option to keep the linklocaladdress same always and should not be changed automatically.

So, answer is IPv4LL address should be always the same, unless it conflicts to other device's address.

Closing.
