### ISSUE TITLE
RFC: Expose a json library agnostic version of varlink

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#21645]
So I've been looking at exposing our varlink and json libraries in libsystemd so other projects can access our varlink APIs using these libraries.

I've started with the json stuff from json.h but it turns out we use quite a bit of C-isms there that make it hard to expose in libsystemd (macros, a few structs that might need versioning added, GCC statement expressions, ...). This made me consider the idea from top down again and one primary realization is that I'm really only interested in sd-varlink and not so much in sd-json. I'd construct any requests using our own internal json library and I'd convert any incoming responses to our own json library before doing anything with them.

This makes we wonder if we should couple sd-varlink tightly to systemd's own json implementation. What if we start out with exposing a json lib agnostic interface and leave the road open to plug in a fast-path using systemd's own json library in the future?

A json agnostic sd-varlink would look similar to what is in varlink.h now, except we'd accept strings (or buffer+size) containing JSON which we'd parse into JsonVariant structs with which we would call the functions that we have already in varlink.h. We'd also add one more hashmap to VarlinkServer (and accompanying functions) for registering json agnostic callbacks and we'd convert the JsonVariant to a string/buffer+size before calling those functions.

This wouldn't be the most efficient but it allows us to expose the varlink stuff separately from the json stuff and simplifies the API for everyone who brings their own JSON library and isn't looking to use systemd's json library.

If we end up with use cases where we need to squeeze out all the performance we can get, we can do the work to expose systemd's own json library properly and also expose the corresponding varlink functions which provides those users that need it with a fast path that doesn't require converting between json representations.

Thoughts?

**Comment by poettering** [comment]
varlink is a pretty trivial protocol. It's rally *extremely* easy to reimplement. Much easier than trying to wrap our C library with a non-C wrapper for some other languages. 

Hence, I think it makes sense to export our C libraries as sd-json and sd-varlink, but focus on C for that, and for other languages it would be *much* better if they'd just reimplement the protocol on top of the JSON lib most appropriate for their language.

I mean, if you don't work in C, then I think the Go, Rust, Python implementations from the upstream project might be right what you need: https://varlink.org/Language-Bindings

**Comment by DaanDeMeyer** [comment]
C++ is kinda interesting here though. We really ought to be able to use the C implementation from C++, but compound literals have different semantics in C++ (in GCC) than they do in C (See https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html), which makes me worried that the builder macros might not behave properly when used in C++.

I'll need to verify whether they'll work in C++ or not. If not we might have to ifdef them out so users don't try to use them accidentally. You're right that for other languages, it's probably better to re-implement the protocol. Let's close this issue.

**Comment by poettering** [comment]
> C++ is kinda interesting here though. We really ought to be able to use the C implementation from C++, but compound literals have different semantics in C++ (in GCC) than they do in C (See https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html), which makes me worried that the builder macros might not behave properly when used in C++.

I think sd-bus uses them too, so given that works I have the suspicion we should be fine for the stuff the json code uses, too
