### ISSUE TITLE
networkd: Please consider adding option for IPv6 preferred lifetime

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#2166]
Hi,

in IPv6, it is common that one adds one IP address per service to a host. It is also common to set the preferred lifetime of such IP addresses to 0, so that the local host doesn't use those addresses any more for outgoing connections unless the application explicitly asks for this address.

Please add an option to systemd-networkd which allows to set the preferred lifetime for an IPv6 address. The suggested name for the option would be IPv6AddressPreferredLifetime.

Greetings
Marc

**Comment by teg** [comment]
Rather than allowing the lifetime to be set arbitrarily, it would be nicer to make this a boolean meaning either "forever" or "zero". Not sure about the name though.
