### ISSUE TITLE
regression: systemd-networkd continually re-configures wlan interface which makes network unusable

### ISSUE THREAD

**Issue by LaserEyess** [systemd/systemd#21685]
**systemd version the issue has been seen with**
 > 7777024dab402b780472daf1ceb6afb3460b388d and after
> found with `git bisect -- src/network` starting from v249 to current git master

**Used distribution**
 > Arch linux (using systemd-git PKGBUILD for bisection)

**Linux kernel version used** (`uname -a`)

 > 5.15.6-arch2-1

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > working wifi

**Unexpected behaviour you saw**
 > systemd-networkd continually reconfigures the wifi device, causing it to be unusable

**Steps to reproduce the problem**
 > have systemd-networkd manage your wifi network
>  (doesn't seem to be anything else required)

**Additional program output to the terminal or log subsystem illustrating the issue**
 - This is a captured journalctl log (from HEAD) with `SYSTEMD_LOG_LEVEL=debug` for systemd-networkd: https://0x0.st/-F8O.log
 - This is kernel messages from the same log: https://0x0.st/-F8V.log
 - relevant `*.{netdev,network}` files below (I use a bonded wireless/wired interface, with iwd as my wireless management daemon)

<details>
  <summary>25-wireless.network</summary>

      ```
      [Match]
      Name=wl*
      
      [Link]
      RequiredForOnline=false
      
      [Network]
      Bond=bond1
      PrimarySlave=false
      ```
</details>

<details>
  <summary>10-bond.network</summary>
      
      ```
      [Match]
      Name=bond1
      
      [Link]
      RequiredForOnline=degraded-carrier
      
      [Network]
      DHCP=yes
      DNS=1.1.1.1
      DNSSEC=no
      DNSOverTLS=no
      
      [DHCPv4]
      UseDNS=true
      Anonymize=true
      UseDomains=true
      UseRoutes=true
      ```
</details>
<details>
  <summary>10-bond.netdev</summary>

      ```
      [NetDev]
      Name=bond1
      Kind=bond
      
      [Bond]
      Mode=active-backup
      ```
</details>

**Additional information**
My network setup is two wireless access points with the same SSID, they're in relatively close proximity to each other so they should both be visible to my wifi adapter anywhere in my home. Based on #20887 it looks like networkd is trying to do something intelligent about how it treats APs with the same SSID, but for my setup it is not working. I can reproduce this issue trivially if more information is needed.

**Comment by LaserEyess** [comment]
Setting `IgnoreCarrierLoss=10s` does not seem to fix this issue either.

**Comment by yuwata** [comment]
Thank you for the detailed report.

One question. Do you use iwd, in stead of wpa_supplicant?

**Comment by LaserEyess** [comment]
I use iwd, I have some logs from `iwmon` as well if they're relevant. My configuration is not particularly interesting:
```
[General]
#UseDefaultInterface=true
AddressRandomization=once
AddressRandomizationRange=nic

[Network]
#NameResolvingService=systemd
```
