### ISSUE TITLE
Delegation to unprivileged users doesn't work for scopes

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#21683]
**systemd version the issue has been seen with**
 > systemd-249

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)

 > `Linux localhost 5.16.0-0.rc3.24.fc36.x86_64 #1 SMP PREEMPT Mon Nov 29 13:43:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
> I would expect that bash process started by systemd-run is placed in a cgroup that can be managed by test user.

**Unexpected behaviour you saw**
> $subject, i.e. cgroup is owned by root user.

**Steps to reproduce the problem**
```bash
$ useradd test
$ systemd-run --uid=test -p Delegate=yes --scope --unit foo.scope --slice bar.slice /bin/bash
$ ls -ld /sys/fs/cgroup/bar.slice/foo.scope/
drwxr-xr-x. 2 root root 0 Dec  8 08:07 /sys/fs/cgroup/bar.slice/foo.scope/
```

**Comment by msekletar** [comment]
Although, it seems to me this is a bug it might be fairly difficult to fix because we would probably need to resolve the user at the time when we are starting scope unit. But, doing synchronous NSS lookups from PID1 might lead to deadlocks...

**Comment by bluca** [comment]
mmh but wouldn't systemd --user cover that use case? If it goes through the system manager, then it's under the system cgroup tree, no?

**Comment by bluca** [comment]
I guess your problem is sending the job to a _different_ user session?

**Comment by msekletar** [comment]
You may want to run processes under non-privileged users that are system users, i.e. they never login and never have any session nor user manager running. IOW, there are no user-sessions.

**Comment by bluca** [comment]
Sounds like ExecStartPre=! to do the setup would work? Supporting `systemd-run --machine @1000` to run from root to a different session would be something nice to support, but arbitrary uid/gid rewriting, I'm not too sure

**Comment by msekletar** [comment]
It was a mistake on my part to use normal user in the steps to reproduce. There should have been something like,

```bash
$ useradd --system test
```

**Comment by msekletar** [comment]
> Sounds like ExecStartPre=! to do the setup would work?

Well, scope units don't have unit files. I mean, sure you can workaround this just fine with service units. But that is besides the point. Question is whether it should also work for scope units?

**Comment by bluca** [comment]
I'm not sure. The `scope` unit doesn't support a `User` setting. Perhaps it could be added? Then systemd-run would just use it.

**Comment by poettering** [comment]
cgroup delegation to unpriv users for scopes simply doesn't exist so far. i.e. no User/Group= setting. Sounds like something we could add though, but it would be a new feature, not a bug.
