### ISSUE TITLE
Systemd Corruption During Distribution Update

### ISSUE THREAD

**Issue by UygarDemir** [systemd/systemd#21699]
**systemd version the issue has been seen with**
 > systemd (248.3-1ubuntu8)

**Used distribution**
 > Ubuntu 20.10

**Linux kernel version used** (`uname -a`)

 > `5.13.0-22-generic`

**CPU architecture issue was seen on**
 > AMD64

Yesterday I upgraded Ubuntu 20.04 to 20.10. I think that somehow some corruption occurred while installing systemd during the update. When I run "dpkg --audit" a long list of unconfigured packages comes up. All of these packages cannot be configured as they are systemd dependent. None of the systems like apt, dpkg are working because systemd cannot be configured. (I cannot install or update any packages on the system.)
First I tried configuring the systemd package with the command "dpkg --configure systemd". An error as below occurred:

> Ayarlanıyor: systemd (248.3-1ubuntu8) ...
> **systemd-machine-id-setup: error while loading shared libraries: libsystemd-shared-247.so: cannot open shared object file: No such file or directory**
> dpkg: systemd paketi işlenirken sorun yaşandı (--configure):
>  systemd paketi post-installation betiği kuruldu alt süreci ***127*** hatalı çıkış kodu ile sona erdi
> İşleme sırasında hatalarla karşılaşıldı:
>  systemd

I then tried to solve this by creating symlinks. It was only effective for this problem. These are the commands I used when creating the links:

> sudo ln -s /lib/systemd/libsystem-shared-248.so /lib/systemd/libsystemd-shared-247.so
> sudo ln -s /lib/systemd/libsystem-shared-248.so /usr/lib/systemd/libsystemd-shared-247.so

Now the output of the command "dpkg --configure systemd" has changed to:

> Ayarlanıyor: systemd (248.3-1ubuntu8) ...
> **systemd-machine-id-setup: symbol lookup error: systemd-machine-id-setup: undefined symbol: log_assert_failed_unreachable_realm, version SD_SHARED**
> dpkg: systemd paketi işlenirken sorun yaşandı (--configure):
>  systemd paketi post-installation betiği kuruldu alt süreci ***127*** hatalı çıkış kodu ile sona erdi
> İşleme sırasında hatalarla karşılaşıldı:
>  systemd

I've heard that others who have done the update are having this issue as well. What can I do, please help. As you know, 127 errors mean "not found". Is it possible to make the package systems work by manually adding the missing parts of the systemd package? Thanks in advance...

**Comment by keszybz** [comment]
Hi Uygar, this is a downstream packaging issue — please ask for help on the Ubuntu forums.

> Is it possible to make the package systems work by manually adding the missing parts of the systemd package?

Yes, in general you can just copy the missing library from the old package (or from the new package, not sure which one you are missing).
