### ISSUE TITLE
RequiredFamilyForOnline action for RequiredForOnline={no-carrier..dormant}

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#21706]
There are some services that bind to specific IP address when configured to do so. Then often require the IP address to be present during startup. When such address is statically configured, it's enough for the interface to be administratively up and configured, carrier is not required.

I'd like to use `RequiredFamilyForOnline=ipv4` for such services to be started just after the IP address is assigned to the interface, no matter if the interface itself is ready for traffic (in particular, I got some servers bound to link-local address, used for interconnecting virtual machines, which is set on VLAN on actual NIC and the external traffic is allowed via NAT). However, this option does nothing below "degraded" opstate.

I would except that:

0. networkctl(1) documentation be improved to describe the actual "power down/up" and "carrier" meaning in terms of background [carrier, dormant and operstate](https://unix.stackexchange.com/questions/619068/the-difference-between-ip-link-down-and-physical-link-absence) as present in `/sys/class/net/iface` as currently it is not clear whether "power down/up" means simple "administrative link down/up"  and "carrier" means actual PHY carrier present or something other.
1. if "powered up" means "ip link set dev iface up"-state:
```
RequiredForOnline=no-carrier
RequiredFamilyForOnline=ipv4
```
to wait for IP assignment, without waiting for actual PHY carrier to be present.

**Comment by yuwata** [comment]
So, do you use `ConfigureWithoutCarrier=yes` or `KeepConfiguration=`?

**Comment by g0tar** [comment]
I do (both). But according to the docs `ConfigureWithoutCarrier` is relevant only for **doing** the configuration (not the linkoperstate check after), and `KeepConfiguration` to not clear my (like: set manually?) addresses upon (re)starting interface.

I'm still struggling with documentation, some of the interactions are still a mystery to me. E.g. `RequiredForOnline=yes` meaning "network is deemed required" is useless, I got to review the sources in order to find `LINK_OPERSTATE_RANGE_DEFAULT { LINK_OPERSTATE_DEGRADED, LINK_OPERSTATE_ROUTABLE }`. And I completely do not understand what's the purpose of maximum state for this...

Only the description of ActivationPolicy distringuishes the admin and carrier state in details.

**Comment by yuwata** [comment]
I guess you have trouble with systemd-networkd-wait-online.service with `--ipv4` option. Does the PR #21756 help you? If possible, could you test the PR?

I am not always good at writing good documents. Any suggestions are welcome.

**Comment by yuwata** [comment]
Note that the half of the states are mostly equivalent to the kernel's operational state: https://www.kernel.org/doc/html/v5.12/networking/operstates.html#tlv-ifla-operstate

**Comment by g0tar** [comment]
Thank you, this seems to resolve my issue:)
