### ISSUE TITLE
Unexpected behaviour of systemd-suspend

### ISSUE THREAD

**Issue by AkshaySiramdas** [systemd/systemd#21712]
**systemctl --version**
 > `systemd 249 (249.7-2-arch)`

**Used distribution**
 > Arch Linux with DWM

 > `Linux Olympus 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > `systemd-logind` following set flags in the configuration file `/etc/systemd/logind.conf`

**Unexpected behaviour you saw**

I started encountering this issue a month ago and am struggling to find a valid solution. 

**The Problem**: Laptop suspends even when the system is not idle, i.e, playing videos, code compilation, code execution, playing games etc,. This is a new problem to me which I haven't encountered before. Previously, the system used to wait for 50 mins in idle mode then `xautolock` used to lock the system, then wait for another 10 mins before suspending. I haven't touched this configuration recently.

**Things I've tried** : My first thought was a change in the configuration file `/etc/systemd/logind.conf`, but nothing seemed off, even then I've changed few things and my current conf file is :
```
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#UserStopDelaySec=10
#HandlePowerKey=poweroff
HandleSuspendKey=ignore
#HandleHibernateKey=hibernate
HandleLidSwitch=ignore
#HandleLidSwitchExternalPower=ignore
#HandleLidSwitchDocked=ignore
#HandleRebootKey=reboot
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#RebootKeyIgnoreInhibited=no
#HoldoffTimeoutSec=30s
IdleAction=ignore
IdleActionSec=24000
#RuntimeDirectorySize=10%
#RuntimeDirectoryInodes=400k
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
```

`xautolock` options in my `xintrc` file

```
xautolock -time 50 -locker slock -killtime 10 -killer "systemctl suspend" -corners -+00 -secure
```
The current conf options in /etc/systemd/logind.conf atleast made the suspends stop while playing games but still suspended during compilations, aur builds and executions, videos etc., when no user input is there for some random time period when all the service should be doing was ignoring and `xautolock` taking over. This used to be the case before.

Few resources online have suggested to mask `sleep.target suspend.target hibernate.target hybrid-sleep.target` but I'm not sure that's a proper way to go. I'm stumped as to why the setup suddenly stopped working.

**Related Outputs**
`systemctl status systemd-logind`
```
● systemd-logind.service - User Login Management
     Loaded: loaded (/usr/lib/systemd/system/systemd-logind.service; static)
     Active: active (running) since Wed 2021-12-08 22:26:43 PST; 13h ago
       Docs: man:sd-login(3)
             man:systemd-logind.service(8)
             man:logind.conf(5)
             man:org.freedesktop.login1(5)
   Main PID: 969 (systemd-logind)
     Status: "Processing requests..."
      Tasks: 1 (limit: 18746)
     Memory: 1.9M
        CPU: 172ms
     CGroup: /system.slice/systemd-logind.service
             └─969 /usr/lib/systemd/systemd-logind
```

`journalctl -b -u systemd-suspend.service`
```
-- Journal begins at Sat 2021-01-02 19:40:41 PST, ends at Thu 2021-12-09 11:37:27 PST. --
Dec 09 00:13:42 Olympus systemd[1]: Starting System Suspend...
Dec 09 00:13:42 Olympus systemd-sleep[325884]: Entering sleep state 'suspend'...
Dec 09 08:48:53 Olympus systemd-sleep[325884]: System returned from sleep state.
Dec 09 08:48:53 Olympus systemd[1]: systemd-suspend.service: Deactivated successfully.
Dec 09 08:48:53 Olympus systemd[1]: Finished System Suspend.
Dec 09 10:29:54 Olympus systemd[1]: Starting System Suspend...
Dec 09 10:29:54 Olympus systemd-sleep[632357]: Entering sleep state 'suspend'...
Dec 09 10:30:02 Olympus systemd-sleep[632357]: System returned from sleep state.
Dec 09 10:30:02 Olympus systemd[1]: systemd-suspend.service: Deactivated successfully.
Dec 09 10:30:02 Olympus systemd[1]: Finished System Suspend.
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: Collecting.
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: Installed new job systemd-suspend.service/start as 2325
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: Passing 0 fds to service
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: About to execute /usr/lib/systemd/systemd-sleep suspend
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: Forked /usr/lib/systemd/systemd-sleep as 770347
Dec 09 11:15:07 Olympus systemd[1]: systemd-suspend.service: Changed dead -> start
Dec 09 11:15:07 Olympus systemd[1]: Starting System Suspend...
Dec 09 11:15:07 Olympus systemd[770347]: systemd-suspend.service: Executing: /usr/lib/systemd/systemd-sleep suspend
Dec 09 11:15:07 Olympus systemd-sleep[770347]: Entering sleep state 'suspend'...
Dec 09 11:15:14 Olympus systemd-sleep[770347]: System returned from sleep state.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Child 770347 belongs to systemd-suspend.service.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Main process exited, code=exited, status=0/SUCCESS (success)
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Deactivated successfully.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Service will not restart (restart setting)
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Changed start -> dead
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Job 2325 systemd-suspend.service/start finished, result=done
Dec 09 11:15:14 Olympus systemd[1]: Finished System Suspend.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Consumed 477ms CPU time.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Control group is empty.
Dec 09 11:15:14 Olympus systemd[1]: systemd-suspend.service: Collecting.
```

`journalctl -b`
Can be found [here](https://gist.github.com/AkshaySiramdas/c41282ee4772b959f152fcaa67f0e689). Please note that I have set the `log-level = debug` on Dec 9th at 11:02:40 mark and the system suspends around 11:15 mark

`loginctl`
```
SESSION  UID USER SEAT  TTY 
      1 1000 zeus seat0 tty1

1 sessions listed.
```
`loginctl show-session 1`
```
Id=1
User=1000
Name=zeus
Timestamp=Wed 2021-12-08 22:27:01 PST
TimestampMonotonic=22040371
VTNr=1
Seat=seat0
TTY=tty1
Remote=no
Service=login
Scope=session-1.scope
Leader=1221
Audit=1
Type=tty
Class=user
Active=yes
State=active
IdleHint=yes
IdleSinceHint=1639031224475034
IdleSinceHintMonotonic=0
LockedHint=no
```
`loginctl user-status`
```
zeus (1000)
           Since: Wed 2021-12-08 22:27:01 PST; 13h ago
           State: active
        Sessions: *1
          Linger: no
            Unit: user-1000.slice
```

Please let me know if any other info is needed.

**Comment by tomty89** [comment]
Have you at least tried not to start xautolock and confirm that it's actually systemd? Smells more like some regression caused by xorg-server 21.

**Comment by keszybz** [comment]
Yeah, I doubt this is our change. Nothing has changed in systemd recently in this area.

**Comment by poettering** [comment]
We rely on your DE to tell us when the session is idle. if it does that incorrectly weird things will happen. It appears to me have have automatic suspend on idle enabled but your DE doesn't properly inform us about the DE state. There's little we can do in that case.

**Comment by poettering** [comment]
Let's close this, this is a DE issue.

**Comment by ffainelli** [comment]
I do not run a desktop environment and have encountered exactly the same issue, my only modification to /etc/systemd/logind.conf is the following:

`[Login]
IdleAction=suspend
IdleActionSec=5min
`

the system will suspend if I just leave a compilation running, even if there are multiple active sessions as listed by loginctl --list-sessions.

This is seen on Ubuntu 22.04.3 LTS with:

`
ii  systemd        249.11-0ubuntu3.9 amd64        system and service manager
`
