### ISSUE TITLE
locale: possibly mistmaching defaults if locale.conf is missing

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#21723]
This is a (bugfixing) request to expose systemd `default_locale` build-config value somewhere on disk, and wire that to `/etc/locale.conf` on boot if the file is not otherwise present.

systemd has its own definition of the default locale for a system, which is set at build-time and defaults to https://github.com/systemd/systemd/blob/ea5e55b3112205194cfb6302710e989158d95b1d/meson.build#L914
Unless otherwise configured, this default is also reflected at runtime by `localectl status`.

Now, traditional Linux tools expect the system-wide locale to be configured via `/etc/locale.conf`. As the systemd [docs](https://www.freedesktop.org/software/systemd/man/locale.conf.html) mentions, this can tweaked by customization tools (like `systemd-firstboot`) but also by external installers (e.g. Anaconda does [this](https://github.com/rhinstaller/anaconda/blob/64efb290a6bea9044d0f9b977bcbc4ae6c61f0d7/pyanaconda/modules/localization/installation.py#L94-L108)).

However, if that file is not created at all, then a machine may end up with a confusing state where different part of the system disagree about the (default) locale in use. The following can be observed on a Fedora-based (CoreOS) system booted without any locale customization:
```
# stat /etc/locale.conf
stat: cannot statx '/etc/locale.conf': No such file or directory

# locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

# localectl status 
   System Locale: LANG=C.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a
```

It would be good to make sure the default locale does not end up in such split brain situation, by making systemd more proactive in claiming the default content of  `/etc/locale.conf`. To that effect, a sketch of the plan could be:
 * add a templated version of `locale.conf` and forward meson `default_locale` to it when building (what about `LC_MESSAGES`?)
 * install a copy of `locale.conf` somewhere under `/usr` (is `/usr/share/factory` supposed to cover this case?)
 * add a tmpfiles.d fragment to copy (or symlink?) the default file to `/etc/locale.conf`

**Comment by tomty89** [comment]
IMHO something similar to what's done for resolv.conf should be done.
