### ISSUE TITLE
Cross-compilation broken by #20294

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#21730]
**systemd version the issue has been seen with**
 > master

**Used distribution**
 > own project

**Linux kernel version used** (`uname -a`)

 > irrelevant

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > clean build while cross-compiling

**Unexpected behaviour you saw**
```
[1084/1086] Generating export-dbus-interfaces with a custom command
FAILED: interfaces
/home/asavah/kross/src/systemd/tools/dbus_exporter.py interfaces /home/asavah/kross/tmp/asusb450eg/systemd/systemd /home/asavah/kross/tmp/asusb450eg/systemd/systemd-resolved /home/asavah/kross/tmp/asusb450eg/systemd/systemd-logind /home/asavah/kross/tmp/asusb450eg/systemd/systemd-hostnamed /home/asavah/kross/tmp/asusb450eg/systemd/systemd-localed /home/asavah/kross/tmp/asusb450eg/systemd/systemd-timedated /home/asavah/kross/tmp/asusb450eg/systemd/systemd-machined
Traceback (most recent call last):
  File "/home/asavah/kross/src/systemd/tools/dbus_exporter.py", line 61, in <module>
    main()
  File "/home/asavah/kross/src/systemd/tools/dbus_exporter.py", line 57, in main
    iterate_executables(args.output, args.executables)
  File "/home/asavah/kross/src/systemd/tools/dbus_exporter.py", line 38, in iterate_executables
    extract_interfaces_xml(output_dir, exe)
  File "/home/asavah/kross/src/systemd/tools/dbus_exporter.py", line 9, in extract_interfaces_xml
    list_interfaces_process = run(
  File "/home/asavah/kross/host/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/asavah/kross/host/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/asavah/kross/host/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/asavah/kross/tmp/asusb450eg/systemd/systemd')
```
File /home/asavah/kross/tmp/asusb450eg/systemd/systemd exists but it is built for another architecture thus it can't be executed directly.

**Steps to reproduce the problem**
 > try cross-compiling systemd

**Additional program output to the terminal or log subsystem illustrating the issue**
caused by #20294

**Comment by asavah** [comment]
My current workaround:

```
diff --git a/meson.build b/meson.build
index daa19f0ed7..767ea73cb1 100644
--- a/meson.build
+++ b/meson.build
@@ -3837,12 +3837,14 @@ run_target(
 alias_target('update-dbus-docs', update_dbus_docs)
 alias_target('update-man-rules', update_man_rules)
 
-custom_target(
-        'export-dbus-interfaces',
-        output : 'interfaces',
-        install : dbus_interfaces_dir != 'no',
-        install_dir : dbus_interfaces_dir,
-        command : [export_dbus_interfaces_py, '@OUTPUT@', dbus_programs])
+if not meson.is_cross_build()
+        custom_target(
+                'export-dbus-interfaces',
+                output : 'interfaces',
+                install : dbus_interfaces_dir != 'no',
+                install_dir : dbus_interfaces_dir,
+                command : [export_dbus_interfaces_py, '@OUTPUT@', dbus_programs])
+ endif
 
 ############################################################
 
```

**Comment by bluca** [comment]
shouldn't this run only if the target is called manually?

**Comment by igo95862** [comment]
> shouldn't this run only if the target is called manually?

It is build by default.

There are 2 options of fixing this:

1). Disable generating D-Bus introspection XML when build is cross compile. Quick and easy but this means cross compiling is now differs from a native build. I believe distros like Debian use cross compiling so make packages for other architectures so this solution might be problematic.

2). Always build a set of native binaries that are used for D-Bus XML export but are not installed. This one is more complex but solves all the issues. (unless there are arch specific D-Bus interfaces but I don't think there are)

@asavah Did man pages properly cross compile before that? They also call the executables so they should have same issue.

**Comment by igo95862** [comment]
Actually man page builder just ignores FileNotFound https://github.com/systemd/systemd/blob/3abdd4bf2e7c6d7eef4e81b4a37fb5ebebc99ef7/tools/update-dbus-docs.py#L205 so option 2 should also fix man page compilation.

**Comment by bluca** [comment]
No, distros including Debian don't do cross builds, it's all native builds, with a few exceptions. Not worth additional complications for something like this. Can you send a PR to skip this target in cross builds?

**Comment by igo95862** [comment]
> Can you send a PR to skip this target in cross builds?

Sure
