### ISSUE TITLE
Rebooting a systemd-nspawn container with --network-veth might fail with "interface already exists"

### ISSUE THREAD

**Issue by r-darwish** [systemd/systemd#2173]
I'm booting a Debian Jessie using systemd-nspawn on Arch Linux . The container is booted with `--network-veth` and once it's up I'm provisioning it using Ansible, which causes some network traffic due to running `apt-get install`.

In some cases, typing `machinectl reboot` fails with the message `Failed to add new veth interfaces (ve-wm-debian:host0): File exists`. When this happens I immediately type `machinectl` and my machine doesn't appear. However, when I type `ip` I do see the virtual interface. I keep typing `ip` until the virtual interface disappears. Only then the machine can be booted again. 

This looks like a race condition as it only reproduces once in every few runs.

```
$ systemctl --version
systemd 228
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

$ uname -a
Linux infradev-ci-arch 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

**Comment by poettering** [comment]
Hmm, strange... not sure how this can happen. But maybe we can try to explicitly remove the veth link before rebooting nspawn.

**Comment by fossxplorer** [comment]
I see the same issue on CentOS 7.2, systemd 219:
 systemd-nspawn   --network-bridge=br0   -bD /container_raptor/c7test/ -M c7test
Spawning container c7test on /container_raptor/c7test.
Press ^] three times within 1s to kill container.
Failed to add new veth interfaces: File exists

It booted fine the first time.

root@localhost network]# systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

[root@localhost network]# uname -a
Linux localhost.localdomain 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost network]# 

EDIT: in my case the veths never disappear, so starting the containers as a service is impossible. I'm more or less dependent on this as the container startup unit files contains bind mounts, among others.
Only (very cumbersome) workaround is to start the containers using systemd-nspawn and specify a different machine name (to create a different veth on host)
I actually use nspawn in production :)

How can i manually delete the veths created?

**Comment by pdf** [comment]
This happens consistently, using a Ubuntu host here, so doesn't appear to be distro-specific.

@fossxplorer you can delete the dev using:

```
ip link del <veth-name>
```

**Comment by LaKing** [comment]
I can confirm this in systemd 222.

**Comment by Germano0** [comment]
systemd-231-10.fc25.x86_64

This is the procedure I usually use to create new containers

```
# lvcreate --name test -L 200G vg_machines
# mkfs.ext4 /dev/vg_machines/test
# mkdir /mnt/test
# mount /dev/vg_machines/test /mnt/test
# dnf --releasever=25 --installroot=/mnt/test/ install @"Fedora Server"
# semanage fcontext -a -t container_file_t "/mnt/test(/.*)?"
# restorecon -R /mnt/test/
# systemd-nspawn -D /mnt/test/ --network-bridge=virbr0 --machine=test
-bash-4.3# passwd
Changing password for user root.
passwd: all authentication tokens updated successfully.
-bash-4.3# exit
# systemd-nspawn -b -D /mnt/test/ --network-bridge=virbr0 --machine=test
```

But yesterday I made some mistakes and I met the problem this ticket:
```
# lvcreate --name test -L 200G vg_machines
# mkfs.ext4 /dev/vg_machines/test
# mkdir /mnt/test
# mount /dev/vg_machines/test /mnt/test
# dnf --releasever=25 --installroot=/mnt/test/ install @"Fedora Server"
```

Here I forgot to run the SELinux commands, and I run

`# systemd-nspawn -b -D /mnt/test/ --network-bridge=virbr0 --machine=test`

Instead of

`# systemd-nspawn -D /mnt/test/ --network-bridge=virbr0 --machine=test`

So I got stuck on container login console without being able to login (I did not set any password). So I entered into host machine and tried to poweroff the container. Here what I got

```
# machinectl poweroff test
Could not kill machine: Access denied
# machinectl stop test
Could not kill machine: Access denied
```
Then I run the SELinux commands I forgot to run before
```
# semanage fcontext -a -t container_file_t "/mnt/test(/.*)?"
# restorecon -R /mnt/test/
```
and I tried again

```
# machinectl poweroff test
Could not kill machine: Access denied
# machinectl stop test
Could not kill machine: Access denied
```

Then finally I managed to turn it off with the following command

```
# machinectl terminate lambda
# machinectl status lambda
Could not get path to machine: No machine 'lambda' known
```
Then to be able to edit container root password I run

`# systemd-nspawn -D /mnt/test/ --network-bridge=virbr0 --machine=test`

but here the error messages I got:

```
# systemd-nspawn -D /mnt/test/ --network-bridge=virbr0 --machine=test
Spawning container test on /mnt/test.
Press ^] three times within 1s to kill container.
Failed to add new veth interfaces (vb-test:host0): File exists
Parent died too early
```

```
# ip link show
(cut)
48: vb-lambda@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr0 state UP mode DEFAULT group default qlen 1000
    link/ether b2:...(cut) brd ff:ff:ff:ff:ff:ff link-netnsid 6
```

I solved with
`# ip link del vb-test`

**Comment by SjonHortensius** [comment]
I believe this is a duplicate of, or at least related to #680

**Comment by jernst** [comment]
I observed this after systems upgrade but before rebooting. Reboot fixes it.

**Comment by LaKing** [comment]
I see saw again with systemd 238
