### ISSUE TITLE
Writable /sys in containers can brick networkd

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#21744]
* systemd version the issue has been seen with: 249
* Used distribution: openSUSE Tumbleweed
* Linux kernel version used: 5.15.6
* CPU architecture issue was seen on: x86_64

Reproducer:

1. Prepare some small-scale container image of choice. Should contain systemd and should have systemd-networkd enabled for boot.
2. Add the line `sysfs /sys sysfs noauto 0 0` into the container's `/etc/fstab`.
3. Launch container, e.g. `systemd-nspawn -b -n`
4. The effect of the fstab line is that /sys is writable.
5. **Observed behavior**: networkd now believes that udevd is in charge of the host0 network interface; the interface never leaves the "pending" status:

```
01:27 testcont:/ # networkctl 
IDX LINK  TYPE     OPERATIONAL SETUP  
  1 lo    loopback carrier     pending
  2 host0 ether    off         pending

2 links listed.
```

**Expected behavior:** configure the interface.

Background:

There used to be a time when Linux systems might have a line for /sys in /etc/fstab, because some distro-specific boot scripts during the sysvinit time used fstab even for essential filesystems. I had such a system; and it was migrated through the times. When systemd came onto the scene, the rogue /sys entry in fstab did no harm. /sys was still sysfs.

Later, the host was converted to an nspawn container, i.e. retaining the /sys entry in fstab, without noticable ill effect. (I found that such fstab entry would cause /sys to be readwritable.) The last version of systemd inside the container that showed expected behavior was v234. That nspawn container was upgraded to the next distro release, featuring v246, where networkd was found to stop working when with that /sys entry. Reproduction of this behavior was then attempted with a newer systemd for the bugreport.

**Comment by yuwata** [comment]
Yeah, currently we require /sys is read-only in containers: http://systemd.io/CONTAINER_INTERFACE

Maybe, we should ignore /sys entry in fstab in containers.

**Comment by yuwata** [comment]
Fix is waiting in #21745.

**Comment by poettering** [comment]
This s by design. See container interface docs. We indicate via /sys/ being writable that udev shall be used. Dont make /sys/ writable i. A container. Its simply not supported, because running udev twice on the same sysfs is a mess. Sysfs is simy not virtualized for cotnainers.

**Comment by poettering** [comment]
Networkd not working is just one artifact of doing this. A lot of other stuff will go wrong too.
