### ISSUE TITLE
MIDI controller udev rules

### ISSUE THREAD

**Issue by jarkkojs** [systemd/systemd#21743]
Music production relies on use of USB-connected MIDI controllers. In order to provide access, software packages using them provide their ad-hoc rules or ad-hoc instructions, e.g.

- https://github.com/git-moss/DrivenByMoss/blob/master/resources/99-userusbdevices.rules (for a popular Bitwig Studio Extension on macOS, Windows and Linux).
- http://usb4java.org/faq.html.

Even on Linux, this starts to be very common use case, so I'm wondering how these rules could be upstreamed to systemd. E.g. what would be the right file to place them, and what group they should be assigned are at least things that I need some feedback.

**Comment by yuwata** [comment]
How about to add a new hwdb to set a flag, then use the flag to set access?

**Comment by Be-ing** [comment]
What's the problem here? Applications with normal user privileges already have access to ALSA MIDI devices.

**Comment by GeorgesStavracas** [comment]
I share @Be-ing's concern - MIDI devices should be automatically routed through ALSA, without any further user intervention. The ones added to hwdb are misbehaving ones that required an extra push to work properly.
