### ISSUE TITLE
Password entry times out after 1min 30sec (sd-encrypt plymouth systemd-boot) - JobRunningTimeoutUSec

### ISSUE THREAD

**Issue by bf** [systemd/systemd#21760]
**systemd version the issue has been seen with**
systemd 249.7-2
systemd-libs 249.7-2

**Used distribution**
arch linux

**Linux kernel version used** (`uname -a`)
`Linux xxx 5.15.7-hardened1-1-hardened #1 SMP PREEMPT Wed, 08 Dec 2021 21:03:34 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Password entry for disk encryption at boot does not time out. User has more than 1min 30seconds to type in password.

**Unexpected behaviour you saw**
Emergency console shows after 1min 30seconds when disk password is not typed in.

**Steps to reproduce the problem**
Install systemd-boot, plymouth. LUKS-encrypt your disk. 

**Additional program output to the terminal or log subsystem illustrating the issue**

```
$ journalctl -xb | egrep -i '(error|fail|warn)' -B 3 -A 3
Dec 13 18:49:00 archlinux systemd-modules-load[173]: Inserted module 'amdgpu'
Dec 13 18:49:00 archlinux systemd-modules-load[173]: Inserted module 'vmd'
Dec 13 18:49:00 archlinux systemd[1]: Finished Load Kernel Modules.
--
Dec 13 18:49:01 archlinux kernel: hid-generic 0003:046D:C335.0003: input,hiddev96,hidraw2: USB HID v1.11 Keyboard [Logitech Gaming Keyboard G910] on usb-0000:05:00.4-1.3.4/input1
Dec 13 18:50:28 archlinux systemd[1]: dev-vg0-root.device: Job dev-vg0-root.device/start timed out.
Dec 13 18:50:28 archlinux systemd[1]: Timed out waiting for device /dev/vg0/root.
░░ Subject: A start job for unit dev-vg0-root.device has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit dev-vg0-root.device has finished with a failure.
░░ 
░░ The job identifier is 38 and the job result is timeout.
Dec 13 18:50:28 archlinux systemd[1]: Dependency failed for File System Check on /dev/vg0/root.
░░ Subject: A start job for unit systemd-fsck-root.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit systemd-fsck-root.service has finished with a failure.
░░ 
░░ The job identifier is 39 and the job result is dependency.
Dec 13 18:50:28 archlinux systemd[1]: Dependency failed for /sysroot.
░░ Subject: A start job for unit sysroot.mount has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit sysroot.mount has finished with a failure.
░░ 
░░ The job identifier is 37 and the job result is dependency.
Dec 13 18:50:28 archlinux systemd[1]: Dependency failed for Initrd Root File System.
░░ Subject: A start job for unit initrd-root-fs.target has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit initrd-root-fs.target has finished with a failure.
░░ 
```

**It seems that `JobRunningTimeoutUSec` is set to `1min 30sec` even though `JobTimeoutUSec` is set to infinity.**

```
$ systemctl show dev-vg0-root.device
SysFSPath=/sys/devices/virtual/block/dm-2
Id=dev-vg0-root.device
Names=dev-vg0-root.device
Following=sys-devices-virtual-block-dm\x2d2.device
Description=/dev/vg0/root
LoadState=loaded
ActiveState=active
FreezerState=running
....
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=1min 30s
.....
CollectMode=inactive
```

```
$ cat /boot/loader/entries/arch-hardened.conf 
title Arch Linux
linux /vmlinuz-linux-hardened
initrd /amd-ucode.img
initrd /initramfs-linux-hardened.img

options rd.luks.name=11234-12341-1234-1234123-4123=crypt rd.luks.options=password-echo=no root=/dev/vg0/root rw nvme_core.default_ps_max_latency_us=0 quiet splash vt.global_cursor_default=0 fbcon=nodefer

$ cat /etc/mkinitcpio.conf  | grep -v "^#"
MODULES=(amdgpu vmd)

BINARIES=()

FILES=(/usr/share/fonts/TTF/DejaVuSans.ttf /usr/share/fontconfig/conf.avail/57-dejavu-sans.conf /etc/fonts/conf.d/57-dejavu-sans.conf /etc/fonts/fonts.conf /usr/lib/plymouth/label.so )

HOOKS=(base systemd sd-plymouth autodetect keyboard sd-vconsole modconf block sd-encrypt lvm2 filesystems resume fsck)
```

**Comment by Werkov** [comment]
Hi, thanks for the report.
systemd's default timeout for device activation is 90 seconds (via `JobRunningTimeoutSec=`). The rootfs device is no exception.

For instance, [dracut disables the timeout for root filesystem](https://github.com/dracutdevs/dracut/blob/2d83bce21bfc874b29c1fb99e8fabb843f038725/modules.d/98dracut-systemd/rootfs-generator.sh#L11) (regardless of encryption or other non-trivial setups). Given your distro, I assume you used `mkinitcpio`, i.e. you'd need to pass equivalent configuration into the built initrd (I'm not that familiar with `mkinitcpio`).

I'm not sure systemd can handle this in general way (i.e. via unit files shipped with systemd), it depends on the sequencing of the given initrd what is the device used for the future main root FS in there.

**Comment by bf** [comment]
To me it feels like this is a bug in the systemd component which generates the "dev-vg0-root.device" service. 

If system is waiting for user input there should not be a 90 seconds timeout.

Do you know where I can patch this?

**Comment by Werkov** [comment]
Is the password prompt a `Type=oneshot` inside a service? Then you could add `After=prompt.service` to `dev-vg0-root.device` and the 90s of running timeout would only start ticking after the prompt terminates, i.e. the semantic you likely want for this timeout.

**Comment by Werkov** [comment]
As for where to patch it, I'd start at [callers](https://github.com/systemd/systemd/blob/a5307e173bf86d695fe85b8e15e91126e8618a14/src/fstab-generator/fstab-generator.c#L749) or [callers](https://github.com/systemd/systemd/blob/a5307e173bf86d695fe85b8e15e91126e8618a14/src/gpt-auto-generator/gpt-auto-generator.c#L663) of `generator_write_initrd_root_device_deps()`. (Beware the `After=prompt.service` must be specified for the device unit, not the `initrd-root-device.target`.)

**Comment by 239** [comment]
This is especially annoying when you have to enter the long recovery keys generated by `systemd-cryptenroll --recovery-key`.
So there is no easy way to increase the timeout or disable it?

**Comment by Werkov** [comment]
@239 What do you build your initrd with? (As i wrote [above](https://github.com/systemd/systemd/issues/21760#issuecomment-1006997144) it's expected dracut unsets the timeout for the root device.)

**Comment by Winterhuman** [comment]
@239 https://wiki.archlinux.org/title/Dm-crypt/System_configuration#Timeout documents how you can change the timeout to whatever you want

**Comment by 239** [comment]
Thanks for your replies!
On Arch it was not necessary to configure anything in `mkinitcpio` since setting this parameter in my `systemd-boot` entry did it:
`options rootflags=x-systemd.device-timeout=0`
On Fedora the timeout is disabled by default, I guess due to dracut as mentioned above.
But on NixOS both options (`rd.luks.options=timeout=0 rootflags=x-systemd.device-timeout=0`) did not work. Probably because systemd in initrd is quite new and experimental there.

**Comment by Werkov** [comment]
Let me close this.
If the NixOS turns out to be systemd related, please (re)open.
