### ISSUE TITLE
[RFE] `SUPPORT_END` field for `/etc/os-release`

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#21764]
**Is your feature request related to a problem? Please describe.**
When managing multiple systems of different distributions and different versions, it is frustrating to have no neutral way to determine end of support for an OS.

**Describe the solution you'd like**
It would be helpful if `/etc/os-release` added a standardized (optional) field like `SUPPORT_END`.  Ideally supporting something like RFC3339 style dates.  From there building a vendor neutral nag tool becomes very simple.

https://www.freedesktop.org/software/systemd/man/os-release.html

**Describe alternatives you've considered**
Various OS specific tools/tricks each requiring manual tricks.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Example script using this new attribute**
Some sort of `timer` could run this script on a relevant interval.

```shell
#!/bin/sh

source /etc/os-release

if [ "x$SUPPORT_END" == "x" ]; then
        exit 0
fi

DAYS_LEFT_90=7776000
DAYS_LEFT_60=5184000
DAYS_LEFT_30=2592000
DAYS_LEFT_7=604800

EPOCH_EOL=`date -d $SUPPORT_END +%s`
EPOCH_NOW=`date +%s`

TIME_LEFT=`expr $EPOCH_EOL - $EPOCH_NOW`

PRIORITY="info"

if [ $TIME_LEFT -lt $DAYS_LEFT_7 ]; then
        PRIORITY="crit"
else if [ $TIME_LEFT -lt $DAYS_LEFT_30 ]; then
        PRIORITY="err"
else if [ $TIME_LEFT -lt $DAYS_LEFT_60 ]; then
        PRIORITY="warn"
else if [ $TIME_LEFT -lt $DAYS_LEFT_90 ]; then
        PRIORITY="notice"
fi
fi
fi
fi

echo "$PRETTY_NAME end of support is $SUPPORT_END" | systemd-cat -p $PRIORITY
```

**Comment by poettering** [comment]
A UNIX timestamp value when support ends definitely makes sense to add.

**Comment by keszybz** [comment]
I think allowing some standard human-readable format would be better. With a unix timestamp effectively the only way to consume this would be programatically, and I think people look at os-release directly quite often.

**Comment by jcpunk** [comment]
I was hopeful that RFC3339 style dates would simplify consuming this via a tool or human eyes.

**Comment by poettering** [comment]
I am not convinced RFC3339 dates are really that readable... And we don't parse them anywhere in our codebase currently.

My assumption would be that "hostnamectl" would just translate this to a nice timezoned timestamp + time left specification.

**Comment by keszybz** [comment]
We don't need a full-blown timestamp. Just YYYY-MM-DD is enough. Actually if we allow *time* so be specified, people will either use 00:00:00.0000000 or just some pseudo-random time.
