### ISSUE TITLE
bonded networking: Allow using lowest mac address as bond mac address

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#21783]
**Is your feature request related to a problem? Please describe.**
This might be a fix for https://github.com/systemd/systemd/issues/15208, or totally unrelated.

As described on https://github.com/NixOS/nixpkgs/issues/69360#issuecomment-558823357:

> systemd v242 assigns MAC addresses to bonds based on the hash of the interface name and the machine ID. [Before, the bond0 MAC was the MAC of the lowest interface](https://www.reddit.com/r/networking/comments/4w9kig/is_there_a_standard_for_lacp_bond_mac_address/d657h22/).

This causes machines on Equinix Metal to not be able to bring their bond up.

Without the bond configured, the network interfaces look like this:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
[…]
4: enp1s0f0np0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 1c:34:da:42:7d:08 brd ff:ff:ff:ff:ff:ff
5: enp1s0f1np1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 1c:34:da:42:7d:09 brd ff:ff:ff:ff:ff:ff
```

As soon as I configure the bond, even with a `.link` file with the following content…

```
[Match]
OriginalName=bond1

[Link]
MACAddressPolicy=none
```

…the bond1 interface gets assigned a hashed mac address (32:b6:ed:72:1f:5f)
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
[…]
4: enp1s0f0np0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
    link/ether 32:b6:ed:72:1f:5f brd ff:ff:ff:ff:ff:ff permaddr 1c:34:da:42:7d:08
5: enp1s0f1np1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
    link/ether 32:b6:ed:72:1f:5f brd ff:ff:ff:ff:ff:ff permaddr 1c:34:da:42:7d:09
16: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 32:b6:ed:72:1f:5f brd ff:ff:ff:ff:ff:ff
```

One way to workaround this is explicitly hardcoding the Mac Address in the bond `.netdev` file, by a snippet like this:

```
[Match]
OriginalName=bond1

[NetDev]
MACAddress=1c:34:da:42:7d:08 # lower mac
```

However, this is hacky, and only works when that mac address is known, so it's unsuitable for generic configurations (read: bootable images) that are reused across multiple machines.

**Describe the solution you'd like**
Being able to influence the mac address generation to use the old behaviour (use lower mac). If this is supposed to happen with above `MACAddressPolicy=none`, then I'd consider it a bug.

If that's expected behaviour, I'd like to see a `Bond.MACAddressPolicy`? setting in `systemd.netdev` that can be set to `lowest-mac`, to get back the old behaviour.

**Describe alternatives you've considered**
As described, hardcoding addresses, but it's not really great.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 249

cc @grahamc @bgamari @arianvp @displague

**Comment by yuwata** [comment]
`MACAddress=none` is implemented by aaa5ca57ae073bfc72bc77ca797fd23579d1e185.
