### ISSUE TITLE
Unable to use sshfs inside nspawn container

### ISSUE THREAD

**Issue by fossxplorer** [systemd/systemd#2178]
I'm unable to use sshfs from inside an nspawn container:
root# sshfs user@fromserver:/path/to/folder /path/to/mount 
fuse: device not found, try 'modprobe fuse' first
root# lsmod | grep fuse
fuse                   87741  3 

/dev/fuse does exist on the host, but not inside the container.
Is this as expected?

**Comment by zonque** [comment]
This is a problem of your local installation or sshfs, and unrelated to systemd, sorry.

**Comment by poettering** [comment]
fuse is currently not supported in nspawn containers, because the kernel interfaces aren't compatible with namespaces/containers. Or at least they weren't the last time I looked, and leaked information from inside the container to the host. If that changed now we can certainly open that up, too.

**Comment by fossxplorer** [comment]
@poettering Ok, thanks for the info. I suspected it wasn't supported atm. 
As a workaround, i use sshfs on the host and then bind mount into the container and it works fine.

**Comment by nh2** [comment]
Related: #6553

**Comment by nh2** [comment]
> Related: #6553

With what's described [there](https://github.com/systemd/systemd/issues/6553#issuecomment-350167906), I could successfully perform a fuse mount inside `systemd-nspawn`; I also tried `sshfs` and it worked.

**Comment by paravoid** [comment]
@poettering, above (Dec 2015) you wrote:
> fuse is currently not supported in nspawn containers, because the kernel interfaces aren't compatible with namespaces/containers. Or at least they weren't the last time I looked, and leaked information from inside the container to the host. If that changed now we can certainly open that up, too.

and in https://github.com/systemd/systemd/issues/7669#issuecomment-352388204 (Dec 2017) you also wrote:
> Well, I'd love to just make fuse available by default, but iirc fuse is still not properly set up for usage in containers, i.e. just making the fuse node available is not safe, as it leaks access on host-side mounts or so, I don't remember the details about that.
> 
> If that changes we should just make FUSE available by default. Until then: you can hack around this already if you are willing to ignore the security implications around this. Just use "--bind=/dev/fuse" on the nspawn cmdline, it knows how to deal with device nodes these days.

Evidently, this has actually changed :) Linux https://github.com/torvalds/linux/commit/da315f6e03988a7127680bbc26e1028991b899b8 (v4.18-rc1); excerpt from the commit message:
> "The most interesting part of this update is user namespace support, mostly done by Eric Biederman. This enables safe unprivileged fuse mounts within a user namespace.

Given `@mount` is already part of the seccomp allow list for nspawn, and even `/sys/fs/fuse/` is exposed, I _think_ that, effectively, this should do it (completely untested):
```diff
diff --git a/src/nspawn/nspawn.c b/src/nspawn/nspawn.c
index 0842731c18..20e34ab9a6 100644
--- a/src/nspawn/nspawn.c
+++ b/src/nspawn/nspawn.c
@@ -2122,6 +2122,7 @@ static int copy_devnodes(const char *dest) {
                 "random\0"
                 "urandom\0"
                 "tty\0"
+                "fuse\0"
                 "net/tun\0";
 
         _cleanup_umask_ mode_t u;
```
