### ISSUE TITLE
'systemd-hwdb update' may leak disk space via temporary files in /etc/udev

### ISSUE THREAD

**Issue by BillPlunkett** [systemd/systemd#21787]
Please see the following console output.  I've noticed some systems eventually run out of disk space, apparently due to temporary files left in /etc/udev.  My working theory is that aborted power-ups are the culprit, i.e. if power is pulled before systemd-hwdb update can complete, files are orphaned in /etc/udev.  I've been able to reproduce behavior in support of this theory by running systemd-hwdb update from the console and interrupting it a few seconds later.

root@LEA-SuperDARC(192.168.100.132):/etc/udev# systemctl --version
systemd 247 (247.6+)
-PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -ZSTD -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid

root@LEA-SuperDARC(192.168.100.132):/etc/udev# uname -a
Linux LEA-SuperDARC 5.10.21-yocto-standard #1 PREEMPT Tue Mar 9 04:04:38 UTC 2021 armv7l GNU/Linux

root@LEA-SuperDARC(192.168.100.132):/etc/udev# ls -la
drwxr-xr-x    4 root     root          4096 Dec 15 15:41 .
drwxr-xr-x   26 root     root          4096 Dec 11 00:19 ..
-r--r--r--    1 root     root      10718569 Dec 15 15:41 hwdb.bin
drwxr-xr-x    2 root     root          4096 Mar  9  2018 hwdb.d
drwxr-xr-x    2 root     root          4096 Dec 11 00:17 rules.d
-rw-r--r--    1 root     root           305 Mar  9  2018 udev.conf

root@LEA-SuperDARC(192.168.100.132):/etc/udev# systemd-hwdb update
^C

root@LEA-SuperDARC(192.168.100.132):/etc/udev# ls -la
drwxr-xr-x    4 root     root          4096 Dec 15 15:45 .
-r--r--r--    1 root     root      10718569 Dec 15 15:45 .#hwdb.bin1jpKH5  <---- orphaned file
drwxr-xr-x   26 root     root          4096 Dec 11 00:19 ..
-r--r--r--    1 root     root      10718569 Dec 15 15:41 hwdb.bin
drwxr-xr-x    2 root     root          4096 Mar  9  2018 hwdb.d
drwxr-xr-x    2 root     root          4096 Dec 11 00:17 rules.d
-rw-r--r--    1 root     root           305 Mar  9  2018 udev.conf

**Comment by poettering** [comment]
It's kinda a limitation of Linux. We would use O_TMPFILE here if we could, so that we can build the new file while it is unlinked, and then atomically link it in once we are done. But that cannot work, since we can't replace existing files that way, and hwdb.bin will almost always exist already when we run this. It's a shortcoming of Linux that O_TMPFILE and link-and-replace cannot be combined.

Because of that we create the new file under a temporary name, create it, and then rename it to the final name. That works, as rename() can replace existing files atomically...

Hence, this isn't really actionable for us, until Linux gains support for O_TMPFILE with atomic replace.

**Comment by BillPlunkett** [comment]
Seems like on startup one could check for files with names beginning with .#hwdb.bin and delete them.

**Comment by wirther** [comment]
when you execute "systemd-hwdb update" command in your machine, if you interrupt this command execute, such as ctrl+c or 
sudden power off, will produce .#hwdb.bin+suffix under /etc/udev directory.
you can delete those files when machine boot or set read only permission for linux root directory.
you can solve this problem.

**Comment by wirther** [comment]
> Seems like on startup one could check for files with names beginning with .#hwdb.bin and delete them.

yes, you are right.
