### ISSUE TITLE
RFE: turn off multipath routing on RA routes

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#21781]
systemd 249.4

I'm configuring hosts with multiple network interfaces and noticed that the routes are grouped together differently in systemd-networkd vs. network-scripts. When the routes are set up like this (multipath routes?) and the interfaces have SLAAC addresses, we fail to connect (unless explicitly pointed at one of the interfaces not using SLAAC). I think this is a difference in systemd-networkd RA vs. kernel RA. If possible, I'd like a knob or something to get the desired state below since that allows us to connect even with the existence of the interfaces with SLAAC addresses. 

Network config (same for eth2 and eth3. eth0 is also similar but has `Address=` set under `[Network]` and `*Prefix=false`):
```
[Match]
Name = eth1

[Network]
IPv4LLRoute = true
IPv6AcceptRA = true

[IPv6AcceptRA]
UseMTU = false
UseAutonomousPrefix = true
UseOnLinkPrefix = true
DHCPv6Client = false
```

`ip -6 route` snippet with the above systemd-networkd configuration:
```
default proto ra metric 1024 expires 1799sec
        nexthop via fe80::c018:50ff:fe26:d44a dev eth0 weight 1
        nexthop via fe80::c018:50ff:fe26:d44a dev eth3 weight 1
        nexthop via fe80::c018:50ff:fe26:d44a dev eth2 weight 1
        nexthop via fe80::c018:50ff:fe26:d44a dev eth1 weight 1 pref medium
```

Desired state (`ip -6 route` snippet from network-scripts config using kernel RA):
```
default via fe80::c018:50ff:fe26:d44a dev eth0 proto ra metric 1024 expires 1798sec hoplimit 127 pref medium
default via fe80::c018:50ff:fe26:d44a dev eth1 proto ra metric 1024 expires 1798sec hoplimit 127 pref medium
default via fe80::c018:50ff:fe26:d44a dev eth2 proto ra metric 1024 expires 1798sec hoplimit 127 pref medium
default via fe80::c018:50ff:fe26:d44a dev eth3 proto ra metric 1024 expires 1798sec hoplimit 127 pref medium
```

cc @yuwata

**Comment by yuwata** [comment]
Interesting. networkd requests default routes one by one, but kernel merges them into one with multipath route. I will take a look.

**Comment by yuwata** [comment]
`fib6_add_rt2node()` in net/ipv6/ip6_fib.c merges routes with the same destination and the same metric, except for the routes do not have `RTF_ADDRCONF` flag, which is set when the route is configured by kernel with RA. See `rt6_qualify_for_ecmp()` in include/net/ip6_route.h.

Question is why the network does not work when the multipath route case? Are there any other difference between networkd and kernel?

**Comment by anitazha** [comment]
> fib6_add_rt2node() in net/ipv6/ip6_fib.c merges routes with the same destination and the same metric, except for the routes do not have RTF_ADDRCONF flag, which is set when the route is configured by kernel with RA.

So kernel does not merge routes if it comes from kernel RA? But systemd-networkd does merge its own RA routes? Because in the examples I'm providing the routes that are merged come from RA and are set up by systemd-networkd.

> Question is why the network does not work when the multipath route case? Are there any other difference between networkd and kernel?

Let me provide a better example since this came up due to some special setup on our Zion hosts. The above example works for the most part but I tried to cheat by simplifying things, so apologies about that. This better reflects the set up of our hosts with SLAAC addresses:

systemd-networkd:
```
default proto ra metric 1024 expires 1798sec
        nexthop via fe80::c018:50ff:fe40:112c dev eth2 weight 1
        nexthop via fe80::c018:50ff:fe40:112c dev eth0 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth6 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth7 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth4 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth8 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth10 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth9 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth5 weight 1
        nexthop via fe80::c018:50ff:fe40:20a1 dev eth11 weight 1
        nexthop via fe80::c018:50ff:fe40:112c dev eth3 weight 1
        nexthop via fe80::c018:50ff:fe40:112c dev eth1 weight 1 pref medium
```
vs. network-scripts with kernel RA
```
default via fe80::c018:50ff:fe40:112c dev eth0 proto ra metric 1024 expires 1799sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:112c dev eth1 proto ra metric 1024 expires 1799sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:112c dev eth2 proto ra metric 1024 expires 1799sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:112c dev eth3 proto ra metric 1024 expires 1799sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth4 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth5 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth6 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth7 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth8 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth9 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium            
default via fe80::c018:50ff:fe40:20a1 dev eth10 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium           
default via fe80::c018:50ff:fe40:20a1 dev eth11 proto ra metric 1024 expires 1796sec hoplimit 127 pref medium
```

In this case eth4 - eth11 are interfaces with SLAAC addresses and are on a separate network from eth0-eth3. eth0 - eth3 are on the production network. So by design eth4 - eth11 can only ping other hosts' eth4 - eth11 on e.g. the same rack.
Here's what happens when I try to use `ip route get` on the systemd-networkd host:
```
ip -6 route get <production host IP>
<production host IP> from :: via fe80::c018:50ff:fe40:20a1 dev eth7 proto ra src <eth7 IP> metric 1024 pref medium
```
contrast this with a different host on the same rack using network-scripts:
```
ip -6 route get <production host IP>
<production host IP> from :: via fe80::c018:50ff:fe0b:b9db dev eth0 proto ra src <eth0 IP> metric 1024 hoplimit 127 pref medium
```
I'm pretty inexperienced with networking but I think ideally things should be defaulted to route through eth0-eth3 first. In our setup if we want things routed through eth4-eth11 there is special handling for that.

**Comment by yuwata** [comment]
@anitazha Sorry for late response.

So, the host is connected to two separated networks. Is it possible to add a route prefix corresponding to each network in the RA message sent by the routers?

If the routers are not under your control, please try to add the following semi-static routes?
```
[Route]
Destination=prefix_a or prefix_b
Gateway=_ipv6ra
```

Then, networkd configures routes to prefixes provided in RA messages something like the following:
```
prefix_a proto ra metric 1024 expires 1798sec
    nexthop via fe80::c018:50ff:fe40:112c dev eth0 weight 1
    nexthop via fe80::c018:50ff:fe40:112c dev eth1 weight 1
    nexthop via fe80::c018:50ff:fe40:112c dev eth2 weight 1
    nexthop via fe80::c018:50ff:fe40:112c dev eth3 weight 1
prefix_b proto ra metric 1024 expires 1798sec
    nexthop via fe80::c018:50ff:fe40:20a1 dev eth4 weight 1
    nexthop via fe80::c018:50ff:fe40:20a1 dev eth5 weight 1
    nexthop via fe80::c018:50ff:fe40:20a1 dev eth6 weight 1
    nexthop via fe80::c018:50ff:fe40:20a1 dev eth7 weight 1
```

And, if one of the network is not connected to the universe, then try to set the following to the corresponding .network files.
```
[Pv6AcceptRA]
UseGateway=no
```

**Comment by anitazha** [comment]
Thanks I'll give it a try and report back!

**Comment by yuwata** [comment]
@anitazha Ping?

**Comment by anitazha** [comment]
Sorry for the delay. When I try to suggestion to add `Destination=fe80::` to `[Route]` I get:
```
fe80:: proto ra metric 1024 expires 1799sec
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth4 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth10 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth5 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth8 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth7 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth6 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth9 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth11 weight 1 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
fe80::/64 dev eth2 proto kernel metric 256 pref medium
fe80::/64 dev eth3 proto kernel metric 256 pref medium
fe80::/64 dev eth4 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth10 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth5 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth8 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth7 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth6 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth9 proto ra metric 1024 expires 2591999sec pref medium
fe80::/64 dev eth11 proto ra metric 1024 expires 2591999sec pref medium
default proto ra metric 1024 expires 1799sec
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth4 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth10 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth5 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth8 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth7 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth6 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth9 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth11 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth2 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth1 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth3 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth0 weight 1 pref medium
```
I still run into issues when doing `ping6` and `ssh`. I guess because the default routes are still merged. And I'm not sure it's workable for us since I don't have the destination prefixes available when getting the config down.

But it inspired me to look for more options to split the routes and so I tried adding this to eth4-eth11:
```
[IPv6AcceptRA]
RouteMetric=2048
```

This splits the default route in the way I wanted:
```
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
fe80::/64 dev eth2 proto kernel metric 256 pref medium
fe80::/64 dev eth3 proto kernel metric 256 pref medium
fe80::/64 dev eth8 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth9 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth6 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth4 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth10 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth11 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth5 proto ra metric 2048 expires 2591996sec pref medium
fe80::/64 dev eth7 proto ra metric 2048 expires 2591996sec pref medium
default proto ra metric 1024 expires 1798sec
        nexthop via fe80::c018:50ff:fe53:d16e dev eth0 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth1 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth3 weight 1
        nexthop via fe80::c018:50ff:fe53:d16e dev eth2 weight 1 pref medium
default proto ra metric 2048 expires 1796sec
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth8 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth9 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth6 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth4 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth10 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth11 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth5 weight 1
        nexthop via fe80::c018:50ff:fe53:cb9b dev eth7 weight 1 pref medium
```
`ssh` and `ping6` seems to be working as expected and consistently. I'll need to follow up with the networking people and host owners to see if this is acceptable since they had reservations with multipath. But I think this is okay for now. Thanks!

**Comment by yuwata** [comment]
Ah, indeed, if the prefixes of the two or more networks are trivial and equivalent, then changing metric sounds good choice for me.

**Comment by anitazha** [comment]
Taking a while for the host owners to look at these settings. But since it's been working for some time now I'll close this and reopen if we still need to turn off merged routes.

**Comment by Gigadoc2** [comment]
Maybe it it is now time to reopen this issue: Having an (equal cost) multipath route in this scenario seems to go against [RFC4861](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.6) if I understand #33470 correctly.

So if I get this right, in the case of two (or more) equally preferred default routers, the host should prefer the router which isn't INCOMPLETE in the neighbor cache, until the advertised route expires (I am not sure what it's supposed to do when the chosen default router becomes unreachable _before_ the route expires, I might misunderstand this part).

<details>
<summary>Why ECMP might actually be OK, just not the way Linux does it</summary>

I am not sure if it is _technically wrong_ to have an ECMP route in this scenario, but it would require a routing cache instead of the flow-hash algorithm we have in Linux: Without a cache, changing the multipath default route (or going from a single nexthop to multipath as in this case) can cause Linux to select a different default router for a given destination than it used before that change, even if the previous router is still valid according to the new routing table.

The kernel actually had a routing cache, for IPv4, it was dropped in 2012 for performance reasons I believe. Considering this, it is unlikely that the kernel will gain one for IPv6 anytime soon, and so it probably makes sense to just to choose a single default router for all destinations in this case.
</details>

I think the kernel does the right thing here, and networkd should probably set the `RTF_ADDRCONF` flag to match the behavior of `accept_ra > 0`, if that flag doesn't have any negative side effects.

**Comment by LiveFreeAndRoam** [comment]
>  and networkd should probably set the RTF_ADDRCONF flag

I'm willing to try this in my IPv6 test environment, if you can tell me where in the code I should set this flag.

**Comment by LiveFreeAndRoam** [comment]
After investigating another issue (#33564), it seems the use of ECMP is breaking the scenario where we have different default routers with different router-lifetimes. I think the routers are being summarised under one `default route entry`.  When either router changes a parameter (e.g. modifies its router-lifetime), I think it is likely to impact both ECMP nexthop entries.  Is this the case? If so, then we have a problem.

From rtnetlink(7), it shows the `RTA_EXPIRE`S entry is defined on a per-route basis and it does not show up under the `RTA_MULTIPATH` entry.  So it seems there's no mechanism to independently update the expiry time for just one of the paths.

PS: I can collect more data on this to test the scenario that I'm describing.
