### ISSUE TITLE
Screen orientation is wrong with Medion Akoya E2212T-MD99720 again

### ISSUE THREAD

**Issue by Tuxman2** [systemd/systemd#21793]
**systemd version the issue has been seen with**
Systemd 249.7

**Used distribution**
 > Manjaro 21.2rc1 KDE (5.23.4 version).

**Linux kernel version used** (`uname -a`)

 > linux515 5.15.6

**CPU architecture issue was seen on**
 > Baytrail

**Expected behaviour you didn't see**
 > Detected orientation should match laptop orientation

**Unexpected behaviour you saw**
 > Orientation is incorrect (left/right swapped, normal/upside-down are all right)

**Steps to reproduce the problem**
 > Tilt the laptop.

**Additional program output to the terminal or log subsystem illustrating the issue**

The issue was here: https://github.com/systemd/systemd/issues/10991
A solution was found here and it worked before : https://github.com/systemd/systemd/pull/11786

But now it doesn't work anymore under the last Manjaro version.

I enabled the automatic rotation under KDE. I'm using Wayland rather than Xorg.

Thanks.

**Comment by jwrdegoede** [comment]
What is the output of: "cat /sys/class/dmi/id" ?

And can you please run:

udevadm info -e > db.txt

And then attach the generated db.txt here ?

**Comment by Tuxman2** [comment]
Hi,

Sorry to respond late. I no longer have this device because I replaced it with a new one. I will close this topic. Thanks for the help.
