### ISSUE TITLE
static IP is removed automatically once disconnected from network

### ISSUE THREAD

**Issue by rakesh1225** [systemd/systemd#21794]
I am using an embedded board with customized linux on it configured with static IP. network configuration is as below:

[Match]
Name=xxxxx

[Link]
RequiredForOnline=no

[Network]
LinkLocalAddressing=ipv4
Address=192.168.x.x/24
DNS=192.168.x.x

[DHCP]
ClientIdentifier=mac
RouteMetric=xx
UseMTU=true

[Route]
Gateway=192.168.x.x
Destination=x.x.x.x/x
Metric=xx

**Case  1**:
    1) Device connected to router/network
    2) set static IP as provided in above network file template to the device
    3) restart systemd-netword service
    4) Check output of command: "**ip addr**" -  It shows the static IP as provided in network config file.

**Case 2**:
    5) After all the steps executed in **Case 1**, disconnected the device from router/network.
         Now the device is connected to nothing through network
    6) Check output of command: "**ip addr**" - No static IP address is listed on ethernet port

**Case 3**:
  7) After **Case 1, Case 2**, Connected the device back to network/router
  8) Check output of command: "**ip addr**" - No static IP address is listed on ethernet port

Please let me know if any changes to be done during **Case 2** and **Case 3** to get static IP address to the device?

**Comment by yuwata** [comment]
- Please provide the version of systemd.
- What does 'Connected the device back to network/router' mean? Does it mean an ethernet cable is plugged in? Or the ethernet device itself is connected (e.g. USB-Ethernet adapter)?

**Comment by rakesh1225** [comment]
- Version: systemd 247 (247.6+)
- 'Connected the device back to network/router' means the ethernet/LAN cable is pluggedin to device.

**Comment by yuwata** [comment]
Sorry, v247 is slightly old here. Please test one of the recent releases (v249 or v250-rc1) or current git HEAD. Closing.

Feel free to request to reopen if you reproduce the issue with a recent release. In that case, please provide the debugging log of networkd. It can be generated by creating the following drop-in:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
