### ISSUE TITLE
~/.config/environment.d/*.conf don't apply,when I logout and then login

### ISSUE THREAD

**Issue by hosxy** [systemd/systemd#21821]
**systemd version the issue has been seen with**
 >  systemd 249

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux archlinux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > I write `AAA=aaa` to `~/.config/environment.d/desktop.conf`,then I logout and login,
I use `systemctl --user show-environment` to output environment variables,but I can't find the environment variable `AAA`

**Unexpected behaviour you saw**
 > Then I restart my system and login, use `systemctl --user show-environment`, I can find the environment variable `AAA`

According to manpage, `~/.config/environment.d/*.conf` use to define user service environment variables, why I need reboot my system rather than relogin to make it apply?

**Comment by tomty89** [comment]
Maybe you relogged in too soon? By default there's a 10s timeout before the user@$uid.service and so is stopped. See `UserStopDelaySec=` of logind.conf

**Comment by hosxy** [comment]
> Maybe you relogged in too soon? By default there's a 10s timeout before the user@$uid.service and so is stopped. See `UserStopDelaySec=` of logind.conf

Thank you, I wait for more than 10s, it works rightly
