### ISSUE TITLE
mark skipped tests as SKIPPED, not SUCCESS

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#21828]
Inspired by
https://github.com/systemd/systemd/pull/21797#issuecomment-996077793

I think we should mark skipped tests accordingly in the summary. Otherwise it gives the wrong impression that tests have actually successfully been run.
An example for this misconception can be found at
https://github.com/systemd/systemd/pull/21253#issuecomment-979460864

Not blaming @poettering here, but our CI infra :-)

**Comment by DaanDeMeyer** [comment]
Now that we migrated to mkosi, skipped tests are marked as skipped if they exit with 77 so let's close this. Note that this doesn't cover skipped subtests. To make that work, we need to implement the Test Anything Protocol so we can properly report subtest results to meson from the integration tests.
