### ISSUE TITLE
RFE: systemd-resolved: static dns entries

### ISSUE THREAD

**Issue by rickysarraf** [systemd/systemd#2183]
Package: systemd
Version: 228-2
Severity: normal
File: systemd-resolved

I am looking at the possibility of replacing dnsmasq with systemd-resolved.

dnsmasq works as a dns caching and dhcp server.

systemd today, with v228, can do DHCP (client/server) and dns.

> From the manpage description, it says that systemd can do a "Caching DNS stub resolver" and "LLMNR resolver and responder"

In dnsmasq, there is a provision to add IP Addr => Hostname mapping locally. And then with local dns caching server running, this all works nice and transparent to the consumers.

> From what I understand so far, systemd-resolved does not do a dns caching _server_. Nor do I see any setting to achieve the above use case, today, with systemd-resolved.

Is this something systemd can do today, or is out of scope, or I just missed something ?

-- Package-specific info:

-- System Information:
Debian Release: stretch/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable'), (101, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.3.0+ (SMP w/4 CPU cores; PREEMPT)
Locale: LANG=en_IN.utf8, LC_CTYPE=en_IN.utf8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages systemd depends on:
ii  adduser         3.113+nmu3
ii  libacl1         2.2.52-2
ii  libapparmor1    2.10-2+b1
ii  libaudit1       1:2.4.4-4
ii  libblkid1       2.27.1-1
ii  libc6           2.19-22
ii  libcap2         1:2.24-12
ii  libcap2-bin     1:2.24-12
ii  libcryptsetup4  2:1.6.6-5
ii  libgcrypt20     1.6.4-3
ii  libkmod2        21-1
ii  liblzma5        5.1.1alpha+20120614-2.1
ii  libmount1       2.27.1-1
ii  libpam0g        1.1.8-3.1
ii  libseccomp2     2.2.3-2
ii  libselinux1     2.4-3
ii  libsystemd0     228-2
ii  mount           2.27.1-1
ii  sysv-rc         2.88dsf-59.2
ii  util-linux      2.27.1-1

Versions of packages systemd recommends:
ii  dbus            1.10.4-1
ii  libpam-systemd  228-2

Versions of packages systemd suggests:
ii  systemd-container  228-2
ii  systemd-ui         3-4

Versions of packages systemd is related to:
ii  udev  228-2

-- no debconf information

**Comment by gdamjan** [comment]
what's wrong with `/etc/hosts`?

(well except there's no wildcard support in nss_files/hosts file)

**Comment by rickysarraf** [comment]
On Mon, 2015-12-21 at 10:18 -0800, Дамјан Георгиевски wrote:

> what's wrong with /etc/hosts?
> (well except there's no wildcard support in nss_files/hosts file)

There's nothing wrong with /etc/hosts and settings its priority higher
during resolve.

It had to do with some applications (Apache VirtualHosts, Drupal,
Drush) that had some issues with non-dns entries. I should have
investigated the cause then, but those were live machines and my
priority then was to get the job done.

That said, I've filed this as RFE for that reason only. I think
systemd-resolved could become a complete replacement for dnsmasq. It
already is doing dhcpd, and now the request is to extend it to dnsd
also.

## 

Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by poettering** [comment]
I am not sure I grok fully what you are requesting here? Do you want resolved to act as DNS server on port 53, serving requests for other hosts? I am pretty sure that's out-of-focus for resolved.

Or are you asking that resolved should allow resolving of additional names locally? But for that /etc/hosts should already be good enough?

**Comment by rickysarraf** [comment]
Yes. The request is to have a dnsmasq dns caching server replacement. But now I think that'd be an overkill on systemd. Hence closing it.

**Comment by alecov** [comment]
This is very useful for configuring static hosts entry per interface in a dynamic manner.

For example, when a local network is connected, I want to redirect my.dynamic.dns to a static IP address in the internal network. When I'm on the field, my.dynamic.dns should be queried for normally. It's troublesome to do this with /etc/hosts.

I would suggest to reconsider this RFE.

**Comment by ammarzuberi** [comment]
`/etc/hosts` works great as long as you don't need to do a wildcard match. It would be great if resolved had functionality similar to `/etc/hosts` but also allowed wildcard matches that resolve to static entries.

My use case: I have some IPv6-only hosts that need access to GitHub, which doesn't do IPv6. I run a GitHub proxy with a trusted CA, so I can simply override DNS in `/etc/hosts`, however, GitHub uses a bunch of subdomains within `github.com`. Today, I need to enumerate them all in the file, it would be great if I could just get resolved to respond with the correct AAAA record.
