### ISSUE TITLE
Supplementary user groups not populated to the child processes of userspace systemd

### ISSUE THREAD

**Issue by majkrzak** [systemd/systemd#21854]
**systemd version the issue has been seen with**
 > systemd 249 (249.7-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)

 > Linux gwenllech 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Additional user groups are not assigned to the processes started with `systemd --user`.

**Unexpected behaviour you saw**
 > Only main user group is reported.

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

When running a `konsole` through `krunner` (Alt+f2) on KDE plasma desktop, `id` does not return all user groups only the main one. This results in problems like, Wireshark not being able to capture, etc.

**Comment by bluca** [comment]
I don't think this can be done for the user manager? I believe you need privileges to change or add gids

**Comment by majkrzak** [comment]
@bluca maybe I didn't express myself clear enough, but if so, it is because of the template I was filling my thoughts into.

The point is that `id` called from the `console` launched via the `krunner` (which spawns process a s a child of `systemd --user`) returns: `uid=1000(majkrzak) gid=1000(majkrzak) grupy=1000(majkrzak)`. While `id` runned `konsole` launched from `plasmashell` app launcher (it is spawnik konsole as its child, systemd init is the grandparent) return `uid=1000(majkrzak) gid=1000(majkrzak) grupy=150(wireshark),985(video),987(storage),991(lp),994(input),998(wheel),1000(majkrzak)`

**Comment by bluca** [comment]
I see - I cannot reproduce that on v249, a user unit prints all the expected gids. Try running `systemd-run --user --tty id`?

**Comment by bluca** [comment]
```
$ systemd-run -t --user bash -c "id"
Running as unit: run-u637.service
Press ^] three times within 1s to disconnect TTY.
uid=1000(luca) gid=1000(luca) groups=1000(luca),4(adm),24(cdrom),25(floppy),27(sudo),30(dip),44(video),46(plugdev),103(fuse),104(scanner),107(bluetooth),109(netdev),120(kvm),121(sambashare),124(libvirt),134(wireshark),1002(steam)
$ systemd-run -t --user id
Running as unit: run-u638.service
Press ^] three times within 1s to disconnect TTY.
uid=1000(luca) gid=1000(luca) groups=1000(luca),4(adm),24(cdrom),25(floppy),27(sudo),30(dip),44(video),46(plugdev),103(fuse),104(scanner),107(bluetooth),109(netdev),120(kvm),121(sambashare),124(libvirt),134(wireshark),1002(steam)
```

**Comment by majkrzak** [comment]
in my case:
```
systemd-run -t --user id
Running as unit: run-u85.service
Press ^] three times within 1s to disconnect TTY.
uid=1000(majkrzak) gid=1000(majkrzak) grupy=1000(majkrzak)```

**Comment by bluca** [comment]
ok, I have no idea

**Comment by mrc0mmand** [comment]
Hm, interesting, I can reproduce this in my test Vagrant VM (currently with installed build from 415d7d774ab8bb46fae18dbb8aa4a69e0ad88b57):

```
$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),1001(myfancygroup),1002(foo)
$ systemd-run -t --user -- bash -c 'id'
Running as unit: run-u3.service
Press ^] three times within 1s to disconnect TTY.
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant)
$ systemctl --version
systemd 250 (250-rc2-121-g415d7d7)
+PAM +AUDIT -SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

```

**Comment by mrc0mmand** [comment]
Ah, nevermind, after rebooting the machine I get the "correct" results:

```
$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),1001(myfancygroup),1002(foo)
$ systemd-run -t --user -- bash -c 'id'
Running as unit: run-u1.service
Press ^] three times within 1s to disconnect TTY.
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),1001(myfancygroup),1002(foo)
```

**Comment by majkrzak** [comment]
I noticed this on the quite fresh installation of my Arch. On previous one there were no such issue. Both configured exactly the same, as stated in the Arch Install guide.

**Comment by tomty89** [comment]
Can't reproduce here either with a completely fresh Arch installation (sddm + plasma-desktop + konsole, and later tested with fish instead of bash as well), unless you are talking about logging out only but not rebooting after adding the user to a supplementary group (the `baloo_file` thingy prevents `user@$uid.service` from stopping after logging out).

Can you observe the same problem if you:
1. disable the display manager you are using
2. reboot
2. login on a tty
3. running `id` directly and with systemd-run

**Comment by majkrzak** [comment]
Disabling `sddm`, rebooting, logging in and running `id` results in same different results: full groups on regular run, and no groups while `systemd-run` :exploding_head:

**Comment by tomty89** [comment]
Have you taken a look at the warnings and errors (`-p 4`), if any, in the journal? (Make sure you check with and without `--user`.)

By the way, I suppose you can at least see the supp groups being shown if you run `id majkrzak` instead of just `id` with `systemd-run`, right?

**Comment by majkrzak** [comment]
`journalctl` shows mostly deprecation warnings and some svg issues from kde/plasma. Nothing relevant I think. `id majkrzak` works correctly.

I'm closing for now as I can not reproduce on the fresh VM. Issue still present on my workstation. No clue what it might be, as I did not change a singe thing regarding that.
