### ISSUE TITLE
Allow systemctl edit without tty, especially SYSTEMD_EDITOR=tee

### ISSUE THREAD

**Issue by maage** [systemd/systemd#21862]
**Is your feature request related to a problem? Please describe.**

If I want to edit unit file manually, I use "systemctl edit" as then I don't needs to create directories and run daemon-reload and avoid extra hassle.

I am frustrated that I can not use same "systemctl edit" as scriptable API to manage unit files when there is no TTY backing both STDOUT and STDERR.

I can use it as:
```
% systemctl cat --user foo.service                                               
No files found for foo.service.
% SYSTEMD_EDITOR=tee systemctl edit --user --full --force foo.service <<EOF 
[Service]
ExecStart=foo
EOF
[Service]
ExecStart=foo
% systemctl cat --user foo.service                                         
# /home/user/.config/systemd/user/foo.service
[Service]
ExecStart=foo
```
from CLI. And it works just fine.

But it does not work from scripting environments (example ansible) where there is no TTY.

Also this fails from CLI even if action is exactly the same:
```
% SYSTEMD_EDITOR=tee systemctl edit --user --full --force foo.service > /dev/null <<EOF
[Service]
ExecStart=foo
EOF
Cannot edit units if not on a tty.
```
as fails same with ```2> /dev/null``` but as there is no output obviously. Or pipe to tee too fails.

Obviously I can manage unit files manually and so on, but usually doing it is like managing unit symlinks manually instead of using systemctl (enable|disable|mask|unmask).

Feature was originally committed here:

https://github.com/systemd/systemd/blob/7d4fb3b1c5ec7a117bd5a36e4591819a64e00136/src/systemctl/systemctl.c#L6166

There is no justification why TTY is actually required.

```tee``` is just example editor here, I could use any other suitable program too, it just need to write wanted output to $1 (as bash nomenclature).

**Describe the solution you'd like**

Remove the on_tty check on sysltemctl edit:

https://github.com/systemd/systemd/blob/2ef28d054d89ee1bcdafc8000d7e6dba36d6642b/src/systemctl/systemctl-edit.c#L508

It would also help if return code would be other than 0 if new unit file Loaded as "bad-setting", but this can be done just by parsing output of:
```
% systemctl status --user foo.service --quiet --full --no-pager --lines=0 | tee
○ foo.service
     Loaded: bad-setting (Reason: Unit foo.service has a bad unit file setting.)
     Active: inactive (dead)
```
Here piping to tee is to disable on_tty checking and colouring the output.

**Describe alternatives you've considered**

There could be new option to disable all guarding (failing) on_tty, and modifying output by on_tty status.

**The systemd version you checked that didn't have the feature you are asking for**

Distro: Fedora 35
Package: systemd-249.7-2.fc35.x86_64
```
systemd 249 (v249.7-2.fc35)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by maage** [comment]
Okay, this is possible with systemd tools, "quite simply" by utilizing ```systemd-run --pty```.
Trick here is to close STDIN for systemd-run so it does not wait to close PTY's. Using $TEMPFILE gets around awkward heredoc. And bash is arranged as is to make rest be in one level of quotations, to avoid needing to quote already quoted. This is relevant as whole block needs to be run using shell.

```|sh
systemd-run --collect --pty --service-type=oneshot --setenv=SYSTEMD_EDITOR=tee --user -- \
bash -c 'f="$1"; shift; "$@" <"$f"' - "$TMPFILE" systemctl edit --force --full --user -- foo.service < /dev/null
```

**Comment by poettering** [comment]
That's really not what "systemctl edit" is for. Seems to me a nicer fix to your usecase if we had "systemctl write" or so, which can create unit files from data you pass in stdin... i.e. an explicit call makes more sense then to make an explicitly interactive operation magic in some cases.

**Comment by galets** [comment]
I really wish that was solved, one way or another. Deploying services by copying files to target machine is not a great solution.

**Comment by Gray-Stone** [comment]
I agree with the argument: 

> There is no justification why TTY is actually required.

Systemd could have been used in many places like CI pipelines that is not tty. 

Using `systemd edit` is simple and elegant, it auto generate folder and place the override file correctly.
