### ISSUE TITLE
systemd-resolved: Implement RFC 8767 for local cache

### ISSUE THREAD

**Issue by nexoscp** [systemd/systemd#21861]
[RFC 8767](https://www.rfc-editor.org/rfc/rfc8767):

> This document defines a method (serve-stale) for recursive resolvers to use stale DNS data to avoid outages when authoritative nameservers cannot be reached to refresh expired data. One of the motivations for serve-stale is to make the DNS more resilient to DoS attacks and thereby make them less attractive as an attack vector.

**Comment by nexoscp** [comment]
May be a duplicate of [Issue 21815](https://github.com/systemd/systemd/issues/21815)

**Comment by bluca** [comment]
duplicate of https://github.com/systemd/systemd/issues/21815
