### ISSUE TITLE
v250 fails to build on older kernel missing new mount api

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#21876]
**systemd version the issue has been seen with**
 > v250

**Used distribution**
 > custom

**Linux kernel version used** (`uname -a`)

 > `4.19.xx`

**Expected behaviour you didn't see**
 > systemd building

**Unexpected behaviour you saw**
 > systemd not building

**Steps to reproduce the problem**
 >  build systemd with older kernel headers

**Additional program output to the terminal or log subsystem illustrating the issue**

the build fails with mount-util.c not finding `MOUNT_ATTR_RDONLY` and other
`MOUNT_ATTR_*` defintions.

**Comment by yuwata** [comment]
Could you test PR #21879?
