### ISSUE TITLE
Namespace-confined mounts

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#21875]
As far as I can tell there's currently no way to perform [service-only mount in a clean, direct way](https://unix.stackexchange.com/questions/564237/extra-mount-points-for-systemd-service). I've found #3439 that introduced bind mounts of such kind, but this doesn't perform actual filesystem isolation.

What I intend to do is to have app-specific mountpoints to be <del>available</del>visible by default only for these apps. Those would be various databases (PostgreSQL) and *cloud-like storages that have their own backup solutions (streaming replications, *cloud-syncing etc.), so that they don't **need** to be host-visible (nor obviously in other namespaces), until requested for some maintenance. For example, I got this in my fstab:

`/dev/mapper/gamma /srv/pgsql            ext4    defaults,noatime,nodiratime,noauto      1 2`

with accompanying `/etc/systemd/system/postgresql@var-lib-pgsql.service.d`:

```
[Unit]
RequiresMountsFor=/var/lib/pgsql
```

which does the mount when service start is requested, however this is done in main tree and propagated to all the namespaces in the system (see also #21873).

Why do I seek for "hiding" this mount? Just like in the previously mentioned RFE, I want to have the system as clean as possible, with as much as can be tagged in the proper place. But why? For all the system maintenance tools, like `find` or any backup tool, even plain `tar`, to be **easier** to operate on daily basis. There are various switches and options to prevent them from traversing other filesystems or directories, but as the number of mountpoints grows and some of them should remain visible and others are not required (or even harmful, especially the *cloud storages that might be huge) this becomes tedious.

When I need to access such mount from anywhere, I could simply make the mount in current namespace, but the service keeps it's own view.

What's missing for this to work?
1. `ExecStart` is executed in separate fsns than `ExecStartPre=`, so it's not possible to simply do `mount`,
2. `RequiresMountsFor` does the mount only if not already mounted.

How would I see this solved?
Allow `PrivateMounts` to contain paths that would always be mounted in the same fsns, as `ExecStart` process, just before it, in `private` propagation mode. So my drop-in would be sth like:

```
[Unit]
PrivateMounts=/var/lib/pgsql
```

without any `MountFlags`.

**Comment by bluca** [comment]
There's already MountImages, TemporaryFileSystems, BindPaths, etc, why wouldn't any of those work?

**Comment by g0tar** [comment]
`TemporaryFileSystems` can hide directory from the service (i.e. the opposite action), unless I miss some usage pattern.
`BindPaths` makes additional viewpoint for the already-mounted resource, plausible but even if working, would be obscure.

But `MountImages` looks promising. One minor caveat is that the mount options would need to be duplicated here (not fetched from globally defined mount unit), but I can live with it. Second issue to test is pulling dependencies for the block device (LUKS activation etc.), but I see no reason why this shouldn't work. I must have missed this option as it's not obvious, that `*Images` are also plain block devices, so for now I think I'm good with this approach. Thanks for pointing me in the right direction!
