### ISSUE TITLE
crond[pid]:pam_systemd(crond:session):Failed to create session:Connection timed out

### ISSUE THREAD

**Issue by garth6666** [systemd/systemd#21885]
hello everyone
For error reporting in the title
Is this a kind of question? as follows
https://github.com/systemd/systemd/issues/2863

**Comment by garth6666** [comment]
I tracked systemd-login through the strace tool and found that the ”sendmsg” call has been blocked, no return value！as follows
sendmsg(26, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/notify"}, msg_namelen=22, msg_iov=[{iov_base="WATCHDOG=1", iov_len=10}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL)

**Comment by poettering** [comment]
Not a useful bug report. Please read the submission form properly.
