### ISSUE TITLE
227 regression: Instantiated units always get stopped during shutdown

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#2189]
In Debian we have a helper unit `ifup@.service` which gets triggered by udev when a network device appears, and then it starts the corresponding network interface if that's configured by ifupdown (i. e. not networkd). The idea is that we never want this to get stopped during shutdown, as this breaks e. g. root on NFS or on iSCSI. It's also not necessary as there already is a `networking.service` which shuts down the network interfaces (unless they are still in use in the cases mentioned).

227 introduced a regression that instantiated `foo@.service` units now always get stopped during shutdown even if they have `DefaultDependencies=no` and thus no implied `Conflicts=shutdown.service`.

This can be demonstrated in nspawn with a `/etc/systemd/system/letmelive@.service`:

```
[Unit]
Description=@@@@@@@@@@@@@@@@@@@ Let me live %i
DefaultDependencies=no

[Service]
RemainAfterExit=yes
StandardOutput=journal+console
ExecStart=/bin/true
ExecStop=/bin/echo "!!!!!!!!!!! I GOT KILLED !!!!!!!!!!!!!"
```

(The ! and @ make it much easier to recognize in the scrolled output) and `systemctl start letmelive@1.service`. https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1492546/+attachment/4536638/+files/systemd-letmelive.sh provides a fully automatic test case which takes a container root directory as the (only) argument.

Using this, I bisected  this to https://github.com/systemd/systemd/commit/8c8da0e0cb4. After that, `letmelive@1.service` has

```
Requires=system-letmelive.slice
After=systemd-journald.socket system-letmelive.slice
```

and I suppose `system-letmelive.slice` is always torn down during shutdown.

This new dependency cannot be reset using `Requires=` in the unit file, as this gets added in code.

The commit log of 8c8da0e0cb4 is not very clear to me, but I guess it fixed some real issue.

Is there any way to write instantiated units so that they don't get stopped during shutdown? (Note that this does work for "normal" units without templates, i. e. no `@`).

Or is this use case simply not supported, and we need to drop the `ExecStop=` in our `ifup@.service`? This would mean that unplugging the device  wouldn't stop and properly deconfigure an interface. Or we need to make `ExecStop=` more complicated to not actually deconfigure when the system is shutting down; both are a bit ugly.

**Comment by poettering** [comment]
I figure we should never shutdown slices at boot...

**Comment by martinpitt** [comment]
`-.slice` already has `default_dependencies == false`, but all others have it as true. I'm not sure where this is coming from as nothing in `slice.c` sets that to `true` (it's only set to false in `slice_enumerate()`).

Is there any case where a slice _should_ be stopped on shutdown? What about `user-NNNN.slice`? If there is none, `slice_add_default_dependencies()` could be eliminated completely.

**Comment by martinpitt** [comment]
I sent the linked PR for a conservative approach. This fixes the issue.

**Comment by martinpitt** [comment]
As discussed in the PR, this should instead be documented.

An appropriate place would be in the documentation of `Slice=` itself in `systemd.resource-control(5)`. Not totally easy to discover, but it's the place that documents the fact that instantiated units get their own slice. So after "Instance units are by default placed in a subslice of system.slice that is named after the template name." we could perhaps add something like

> By default these instance unit slices get stopped on shutdown; if that is not desirable, create an explicit .slice unit with DefaultDependencies=no, or put the service into Slice=system.slice."

? (Can do a PR, but discussing the wording and place is easier here than force-pushing five wording changes ☺ )

**Comment by poettering** [comment]
Maybe something like this in the docs for "Automatic Dependencies=" in systemd.service(5):

```
Note that instanced service units (i.e. services unit with an @ in their name) are by default assigned a per-template slice (see systemd.resource-control(5)), named after the template unit, which is stopped at shutdown. Also note that service units require their slice units, and hence if a slice unit is stopped all service units contained in it are stopped, too. This means if you write a template service unit that shall stay around during late shutdown, and is using DefaultDependencies=no to implement this, make sure to either define your own per-template slice unit file that also sets DefaultDEpendencies=no, or to explicitly assign your templated service unit to a different Slice that already sets this, for example Slice=systemd.slice.
```

And then a quick reference to that near Slice=:

```
Special care should be taken when relying on the default slice assignment in templated service units that have DEfaultDependencies=no set, see .... for details
```

Or somethinglike that...
