### ISSUE TITLE
systemd-notify: option to exec a command on exit

### ISSUE THREAD

**Issue by ibukanov** [systemd/systemd#21897]
**Is your feature request related to a problem? Please describe.**

systemd-notify does not work with NotifyAccess=main in an unprivileged script.

**Describe the solution you'd like**

It will be nice to have an option `--exec` to execute a process when systemd-notify exits to allow a usage like the following in a shell script:
```
exec systemd-notify --ready --exec "$0" continue_after_notify_command 
```
With this option, when the utility executes, it will have the PID of the main process and can always connect to the notify socket. Yet the script can continue after that with the same PID. Even better if systemd-notify will exec into the process on any error path and pass in an environment its error status. But it is OK to only exec on success. 

**Describe alternatives you've considered**

The obvious workaround is to use NotifyAccess=all if such loser access is OK. Another possibility is to use a scripting language that allows to call sd_notify() directly.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 249 (v249.7-2.fc35)

**Comment by poettering** [comment]
This was actually implemented by 9175338e09de56c99cebf0b9f215f3e9e0016cb9
