### ISSUE TITLE
"Failed to set hostname" if CONFIG_DEFAULT_HOSTNAME is empty

### ISSUE THREAD

**Issue by xry111** [systemd/systemd#21896]
**systemd version the issue has been seen with**
 > 250

**Used distribution**
 > Linux From Scratch

**Linux kernel version used** (`uname -a`)

 > `5.16.0-rc6+`

**CPU architecture issue was seen on**
 > mips64

**Expected behaviour you didn't see**
 > systemd should update hostname to the content of /etc/hostname

**Unexpected behaviour you saw**
 > "Failed to set hostname to \<xry111-A1901\>: No such device or address"

**Steps to reproduce the problem**
 > Build a kernel with empty CONFIG_DEFAULT_HOSTNAME, and boot it.

**Comment by xry111** [comment]
It can be workaround by setting CONFIG_DEFAULT_HOSTNAME to `(none)` (like most distros).

**Comment by zhangn1985** [comment]
same to gentoo, 

```
        assert_se(uname(&u) >= 0);


        s = u.nodename;
        if (isempty(s) ||
            (!FLAGS_SET(flags, GET_HOSTNAME_ALLOW_NONE) && streq(s, "(none)")) ||
            (!FLAGS_SET(flags, GET_HOSTNAME_ALLOW_LOCALHOST) && is_localhost(s)) ||
            (FLAGS_SET(flags, GET_HOSTNAME_SHORT) && s[0] == '.')) {
                if (!FLAGS_SET(flags, GET_HOSTNAME_FALLBACK_DEFAULT))
                        return -ENXIO;
```

when nodename is empty, GET_HOSTNAME_FALLBACK_DEFAULT is not set will return -ENIOX and refuse to set hostname.
flags is `GET_HOSTNAME_ALLOW_NONE | GET_HOSTNAME_ALLOW_LOCALHOST`
