### ISSUE TITLE
Has header "sys/capability.h" : NO   meson.build:684:8: ERROR: Problem encountered: POSIX caps headers not found

### ISSUE THREAD

**Issue by Azaretdodo** [systemd/systemd#21909]
**systemd version the issue has been seen with**
 >v250

**Used distribution**
 >Linux ubuntu-ThinkPad-X250 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Linux kernel version used** (`uname -a`)

 > Linux ubuntu-ThinkPad-X250 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 >x86_64

**Expected behaviour you didn't see**
 >I can't fully installed

**Unexpected behaviour you saw**
 > Has header "sys/capability.h" : NO 

meson.build:684:8: ERROR: Problem encountered: POSIX caps headers not found

**Steps to reproduce the problem**
 >./configure && make && make install

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
Thank you in advance to help myself fully install systemd v250,

Regards.

Dorian ROSSE.

**Comment by mrc0mmand** [comment]
You're missing dev headers of libcap (libcap-devel on Fedora, similarly for other distros).

Please, go through the requirements in the README - https://github.com/systemd/systemd/blob/main/README#L166 - to get a full list of what you need.

**Comment by mrc0mmand** [comment]
Also, since you seem to use Ubuntu, you can install most of the build requirements using `apt build-dep systemd` (assuming you have the respective `deb-src` directives in `/etc/apt/sources.list` uncommented).
