### ISSUE TITLE
meson.build:664:0: ERROR: Command "/usr/bin/sh -c echo foo,bar | /usr/local/bin/gperf -L ANSI-C" failed with status 1.

### ISSUE THREAD

**Issue by Azaretdodo** [systemd/systemd#21903]
**systemd version the issue has been seen with**
 > v250

**Used distribution**
 >Linux ubuntu-ThinkPad-X250 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Linux kernel version used** (`uname -a`)

 > Linux ubuntu-ThinkPad-X250 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 >x86_64

**Expected behaviour you didn't see**
 > a full install of systemd v250

**Unexpected behaviour you saw**
 >meson.build:664:0: ERROR: Command "/usr/bin/sh -c echo foo,bar | /usr/local/bin/gperf -L ANSI-C" failed with status 1.

**Steps to reproduce the problem**
 >./configure && make && make install

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
thank you in advance to help myself fully install systemd version 250,

Regards.

Azaretdodo.

**Comment by medhefgo** [comment]
It looks like you're using a custom built gperf. Try with the distro provided one.

**Comment by Azaretdodo** [comment]
I use gperf from "pip3 install gperf",

What gperf I must use ?

A GitHub gperf ?

Or a packaged gperf ?

Thanks you in advance for your answer,

Regards.


Dorian Rosse.
________________________________

**Comment by mrc0mmand** [comment]
> I use gperf from "pip3 install gperf", What gperf I must use ? A GitHub gperf ? Or a packaged gperf ? Thanks you in advance for your answer, Regards. Dorian Rosse.


Please use the packaged gperf from your distribution, as the `gperf` package on PyPI is something completely different than what's needed by systemd, e.g. PyPI's [gperf](https://pypi.org/project/gperf/) is *Graphing performance or system activity information* whereas the expected [gperf](https://www.gnu.org/software/gperf/) is *GNU gperf is a perfect hash function generator.*
