### ISSUE TITLE
getty: tty device name shown incorrectly on login prompt

### ISSUE THREAD

**Issue by uplighters-grays** [systemd/systemd#21919]
**systemd version the issue has been seen with**
```
systemd 250 (250-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

```
Linux arch 5.15.10-hardened1-1-hardened #1 SMP PREEMPT Fri, 17 Dec 2021 20:16:31 +0000 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Upon switching to a virtual terminal (eg. on boot or via Ctrl+Alt+F[num]), the TTY device name is shown at the login prompt

**Unexpected behaviour you saw**
 > TTY device name is not shown, instead only "-"
This is a regression introduced by b4bf9007cbee7dc0b1356897344ae2a7890df84c as part of #21171
At the same time it also seems to be intended behavior, so I am not sure what should be done. Not being able to see what TTY I switched to is mildly annoying.

**Steps to reproduce the problem**
 > Boot directly to getty

**Additional program output to the terminal or log subsystem illustrating the issue**
> N/A

**Comment by bluca** [comment]
Sounds like something that can only be fixed in agetty?

**Comment by bluca** [comment]
Unless there's some option/env var that can be passed to set the name (can't see one)

**Comment by joanbm** [comment]
agetty prints the first line from reading `/etc/issue` which in Arch Linux by default contains:
```
Arch Linux \r (\l)
```

But in agetty `\l` prints `op->tty`:
https://github.com/util-linux/util-linux/blob/1cf6e936e308166fffdc2d703c4ade2e8cbe5e51/term-utils/agetty.c#L2797

And `op->tty` is always set to whatever the received tty command line parameter is (i.e. `-` for `stdin`):
https://github.com/util-linux/util-linux/blob/1cf6e936e308166fffdc2d703c4ade2e8cbe5e51/term-utils/agetty.c#L906

So there isn't any possibility to override it, though IMO it would be a nicer fix if it's done on agetty's side either by it figuring out which TTY it is itself, or having an option to provide an alternative name.

Meanwhile if you just want to get the TTY names back for the time being, you can revert the change in https://github.com/systemd/systemd/commit/b4bf9007cbee7dc0b1356897344ae2a7890df84c by doing `systemctl edit getty@.service` and typing:

```
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -- \\u' --noclear %I $TERM
StandardInput=null
StandardOutput=journal
```

**Comment by uplighters-grays** [comment]
Closing this in favor of upstream issue https://github.com/util-linux/util-linux/issues/1546, since nothing can be done on systemd's side short of reintroducing potentially faulty behavior.
