### ISSUE TITLE
systemd-gpt-auto-generator seems to ignore TPM2 token enrolled into LUKS rootfs

### ISSUE THREAD

**Issue by swsnr** [systemd/systemd#21914]
I've got a root partition named "linux" with the appropriate partition code which contains a LUKS-encrypted filesystem with a TPM2 token enrolled:

```
$ gdisk -l /dev/nvme0n1
[...]
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         1230847   600.0 MiB   EF00  EFI System Partition
   3         3328000       488396799   231.3 GiB   8304  linux
$ systemd-cryptenroll /dev/disk/by-partlabel/linux
SLOT TYPE    
   0 tpm2
   1 password
   2 recovery
```

I have no `/etc/fstab` and no `/etc/crypttab*`.  I've got a initramfs built by dracut which includes the tpm2 modules and sets `rd.luks.options=tpm2-device=auto`:

```
kernel_cmdline="quiet systemd.unified_cgroup_hierarchy=1 lockdown=integrity rd.luks.options=tpm2-device=auto"
compress="zstd"
hostonly="yes"
hostonly_cmdline="no"
add_dracutmodules+=" tpm2-tss "
```

I'd expect to see no LUKS password prompt for the rootfs at boot, but in fact I do see one.

Am I missing something?  Or is a TPM2 token not yet supported by systemd-gpt-auto-generator?

**systemd version the issue has been seen with**
250

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
`Linux bastis-kastl 5.10.88-2-lts #1 SMP Wed, 22 Dec 2021 19:16:31 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x64_86

**Expected behaviour you didn't see**
I expect the rootfs to be decrypted automatically at boot, and have the system boot straight to GDM, without any LUKS password prompt during early boot.

The GPT generator itself works, and I've also checked that I can attach TPM2-based LUKS partitions (I've tested with a loopback device).

**Unexpected behaviour you saw**
I get a LUKS password prompt for the rootfs at boot, and I have to enter my password (from slot 1, see above) for the boot to continue; presumably the TPM2 token isn't used.

**Steps to reproduce the problem**
Create a root partition with LUKS encryption and enroll a TPM2 token to it? Not sure exactly.

I've checked `journalctl -b` but I didn't see anything suspicious:

```
Dez 27 21:01:06 bastis-kastl systemd[1]: Starting Cryptography Setup for root...
Dez 27 21:01:06 bastis-kastl kernel: random: systemd-cryptse: uninitialized urandom read (4 bytes read)
Dez 27 21:01:06 bastis-kastl systemd[1]: Started Dispatch Password Requests to Console.
Dez 27 21:01:06 bastis-kastl audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-ask-password-console comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dez 27 21:01:06 bastis-kastl systemd-tty-ask-password-agent[317]: Starting password query on /dev/tty1.
Dez 27 21:01:06 bastis-kastl kernel: fbcon: Taking over console
Dez 27 21:01:06 bastis-kastl kernel: Console: switching to colour frame buffer device 240x67
Dez 27 21:01:06 bastis-kastl kernel: input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
Dez 27 21:01:06 bastis-kastl kernel: checking generic (90000000 7e9000) vs hw (a0000000 1000000)
Dez 27 21:01:06 bastis-kastl kernel: checking generic (90000000 7e9000) vs hw (90000000 10000000)
Dez 27 21:01:06 bastis-kastl kernel: fb0: switching to inteldrmfb from EFI VGA
Dez 27 21:01:06 bastis-kastl kernel: Console: switching to colour dummy device 80x25
Dez 27 21:01:06 bastis-kastl kernel: i915 0000:00:02.0: vgaarb: deactivate vga console
Dez 27 21:01:06 bastis-kastl kernel: i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
Dez 27 21:01:06 bastis-kastl kernel: i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_04.bin (v1.4)
Dez 27 21:01:06 bastis-kastl kernel: [drm] Initialized i915 1.6.0 20200917 for 0000:00:02.0 on minor 0
Dez 27 21:01:06 bastis-kastl kernel: ACPI: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
Dez 27 21:01:06 bastis-kastl kernel: input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input6
Dez 27 21:01:06 bastis-kastl kernel: usb 1-2: new high-speed USB device number 2 using xhci_hcd
Dez 27 21:01:06 bastis-kastl kernel: fbcon: i915drmfb (fb0) is primary device
Dez 27 21:01:06 bastis-kastl kernel: usb 1-2: New USB device found, idVendor=1a40, idProduct=0101, bcdDevice= 1.11
Dez 27 21:01:06 bastis-kastl kernel: usb 1-2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
Dez 27 21:01:06 bastis-kastl kernel: usb 1-2: Product: USB 2.0 Hub
Dez 27 21:01:06 bastis-kastl kernel: hub 1-2:1.0: USB hub found
Dez 27 21:01:06 bastis-kastl kernel: hub 1-2:1.0: 4 ports detected
Dez 27 21:01:07 bastis-kastl kernel: usb 1-3: new high-speed USB device number 3 using xhci_hcd
Dez 27 21:01:07 bastis-kastl kernel: usb 1-3: New USB device found, idVendor=058f, idProduct=3822, bcdDevice=11.00
Dez 27 21:01:07 bastis-kastl kernel: usb 1-3: New USB device strings: Mfr=0, Product=2, SerialNumber=0
Dez 27 21:01:07 bastis-kastl kernel: usb 1-3: Product: HD Webcam
Dez 27 21:01:07 bastis-kastl kernel: usb 1-7: new full-speed USB device number 4 using xhci_hcd
Dez 27 21:01:07 bastis-kastl kernel: usb 1-7: New USB device found, idVendor=8087, idProduct=0025, bcdDevice= 0.02
Dez 27 21:01:07 bastis-kastl kernel: usb 1-7: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Dez 27 21:01:07 bastis-kastl kernel: Console: switching to colour frame buffer device 240x67
Dez 27 21:01:08 bastis-kastl kernel: i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
Dez 27 21:01:11 bastis-kastl kernel: random: fast init done
Dez 27 21:01:11 bastis-kastl systemd-tty-ask-password-agent[317]: Password query on /dev/tty1 finished successfully.
Dez 27 21:01:11 bastis-kastl systemd-cryptsetup[314]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/gpt-auto-root-luks.
```

**Comment by lunaryorn** [comment]
Never mind, it's a dracut issue which fails to include the systemd cryptsetup plugins: <https://github.com/dracutdevs/dracut/issues/1676>

I'm sorry for the noise; I missed the crucial two lines in the wealth of debugging output. Perhaps systemd-cryptsetup could emit a warning if `/usr/lib/cryptsetup/libcryptsetup-token-systemd-tpm2.so` is missing?  Currently it's a pretty boring log line which only appears when booting with `debug` in the kernel cmdline, and then it's easily lost among the about 13k lines of log the boot process then generates:

![grafik](https://user-images.githubusercontent.com/224922/147510108-234cf825-c571-48f1-bc34-432ac500051c.png)

A proper warning would've helped me spot this faster :slightly_smiling_face: 

In any case please do feel free to close this issue; it's not a systemd issue ultimately and it's easy to work around it with some dracut configuration.

I am sorry for the noise.
