### ISSUE TITLE
systemd-nspawn: add a flag to set working directory

### ISSUE THREAD

**Issue by cgonyeo** [systemd/systemd#2192]
It would be very convenient if nspawn had a flag to set the working directory for the binary inside the container.

Something like:

```
systemd-nspawn -D path/to/rootfs --working-dir=/app /usr/bin/bundle install
```

Would be analogous to:

```
systemd-nspawn -D path/to/rootfs /bin/sh -c 'cd /app ; bundle install'
```

Thoughts?

**Comment by poettering** [comment]
Makes sense.

**Comment by keszybz** [comment]
Option should be called `--working-directory` (no abbreviation), to match existing `--directory`. I don't think we should add a short option, unless this proves to be used often, but we should reserve `-C` for this, to match `tar` and `make`.

**Comment by cgonyeo** [comment]
`--working-directory` would be fine by me. I'm indifferent to having a short option for it.
