### ISSUE TITLE
Timesyncd.conf:  Cant override SaveIntervalSec value

### ISSUE THREAD

**Issue by mlmatlock** [systemd/systemd#21926]
**systemd version the issue has been seen with**
 >systemd 250 (250-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 >Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux Jammin1 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > Override the default 60 second time for the new SaveIntervalSec

**Unexpected behaviour you saw**
 > After daemon-reload and unit restart, this error:
```
Dec 28 10:57:35 Jammin1 systemd-timesyncd[117317]: /etc/systemd/timesyncd.conf.d/01-saveint.conf:2: Failed to parse sec value, ignoring:
```

**Steps to reproduce the problem**
 > Create an override.conf file in /etc/systemd/timesyncd.conf.d with the following:
```
[Time]
SaveintervalSec=
SaveIntervalSec=1800
```
Then daemon-reload and restart systemd-timesyncd.service.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemctl status systemd-timesyncd
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-12-28 10:57:35 EST; 12min ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 117317 (systemd-timesyn)
     Status: "Initial synchronization to time server 132.163.97.1:123 (time-a-wwv.nist.gov)."
      Tasks: 2 (limit: 38415)
     Memory: 1.4M
        CPU: 62ms
     CGroup: /system.slice/systemd-timesyncd.service
             └─117317 /usr/lib/systemd/systemd-timesyncd

Dec 28 10:57:35 Jammin1 systemd[1]: Starting Network Time Synchronization...
Dec 28 10:57:35 Jammin1 systemd-timesyncd[117317]: /etc/systemd/timesyncd.conf.d/01-saveint.conf:2: Failed to parse sec value, ignoring: 
Dec 28 10:57:35 Jammin1 systemd[1]: Started Network Time Synchronization.
Dec 28 10:57:35 Jammin1 systemd-timesyncd[117317]: Initial synchronization to time server 132.163.97.1:123 (time-a-wwv.nist.gov).
```
Relevant journal output:
```text
Dec 28 10:57:35 Jammin1 sudo[117309]:   merell : TTY=pts/0 ; PWD=/etc/systemd/timesyncd.conf.d ; USER=root ; COMMAND=/usr/bin/systemctl restart systemd-timesyncd
Dec 28 10:57:35 Jammin1 sudo[117309]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 28 10:57:35 Jammin1 systemd[1]: Stopping Network Time Synchronization...
Dec 28 10:57:35 Jammin1 systemd[1]: systemd-timesyncd.service: Deactivated successfully.
Dec 28 10:57:35 Jammin1 systemd[1]: Stopped Network Time Synchronization.
Dec 28 10:57:35 Jammin1 systemd[1]: Starting Network Time Synchronization...
Dec 28 10:57:35 Jammin1 systemd-timesyncd[117317]: /etc/systemd/timesyncd.conf.d/01-saveint.conf:2: Failed to parse sec value, ignoring: 
Dec 28 10:57:35 Jammin1 systemd[1]: Started Network Time Synchronization.
Dec 28 10:57:35 Jammin1 sudo[117309]: pam_unix(sudo:session): session closed for user root
Dec 28 10:57:35 Jammin1 systemd-timesyncd[117317]: Initial synchronization to time server 132.163.97.1:123 (time-a-wwv.nist.gov).
```
The following is not true.  Doesn't matter the value or the unit given.  Same result. 

> man timesyncd.conf:
SaveIntervalSec=
	   The interval at which the current time is periodically saved to
	   disk, in the absence of any recent synchronisation from an NTP
	   server. This is especially useful for offline systems with no local
	   RTC, as it will guarantee that the system clock remains roughly
	   monotonic across reboots.

	   Takes a time interval value. The default unit is seconds, but other
	   units may be specified, see systemd.time(5). Defaults to 60
	   seconds.

**Comment by yuwata** [comment]
It does not support an empty string. Please drop the line `SaveIntervalSec=`.

**Comment by mlmatlock** [comment]
Thanks, Yu.  That did the trick.
