### ISSUE TITLE
network: failed to set route for WireGuard interface

### ISSUE THREAD

**Issue by freswa** [systemd/systemd#21929]
Last good version: `249.7`
First bad version: `250`

I get this network error with networkd v250
```
Dec 29 15:33:10 adhiratha systemd-networkd[376]: wg3: netdev ready
Dec 29 15:33:10 adhiratha systemd-networkd[376]: wg3: Link UP
Dec 29 15:33:10 adhiratha systemd-networkd[376]: wg3: Gained carrier
Dec 29 15:33:10 adhiratha systemd-networkd[376]: wg3: Could not set route: Invalid prefix for given prefix length. Invalid argument
Dec 29 15:33:10 adhiratha systemd-networkd[376]: wg3: Failed
```

Where the `.network` file looks like:
```
[Match]
Name = wg3

[Network]
Address = 172.16.11.1/24
Address = fd00:a1f:ea75:ca75::1/64
IPForward = yes
```

**Comment by yuwata** [comment]
Could you also provide relevant .netdev files?

**Comment by freswa** [comment]
```
[NetDev]
Name = wg3
Kind = wireguard
MTUBytes = 1412

[WireGuard]
PrivateKey = <sk>
ListenPort = 51822

[WireGuardPeer]
PublicKey = <pk>
AllowedIPs = 172.16.0.0/22, 192.168.30.0/24, 172.16.43.0/24, 172.16.42.0/24, 172.16.11.10/24, 172.16.10.10/24
AllowedIPs = fd00:a1f:ea75:ca75::/64, 2a01:xxxx:xxxx:xxxx::/64, 2a01:xxxx:xxxx:xxxx::1/128, fd00:dead:beef::/64, fd00:b16b:b5::/64
```

**Comment by 1848** [comment]
Another regression, did not have time to debug yet:

```
// netdev
[NetDev]
Name = xfrm1
Kind = xfrm
MTUBytes = 1400

[Xfrm]
InterfaceId = 1
Independent = true

// network
[Match]
Name = xfrm1

[Network]
Address = SNIP/32
Xfrm = xfrm1

[Route]
Destination = SNIP/32
Scope = link

[Route]
Destination = SNIP/32
Scope = link
```

Used to work. Now I get *systemd-networkd[488]: xfrm1: Failed*

**Comment by yuwata** [comment]
@1848 It seems your issue is not relevant to this issue. Could you open a new issue page with debugging logs of networkd?

**Comment by 1848** [comment]
Well, the issue is named "networkd regression" ;) But yeah sure, will do when I find time, just wanted to give a quick notice.

**Comment by yuwata** [comment]
Fix is waiting in #21940.

**Comment by yuwata** [comment]
@1848 BTW, I guess your issue is caused by the line `Xfrm = xfrm1` in the network file, as xfrm1 itself cannot be stacked on the interface. Please try to remove the line.

**Comment by 1848** [comment]
> @1848 BTW, I guess your issue is caused by the line `Xfrm = xfrm1` in the network file, as xfrm1 itself cannot be stacked on the interface. Please try to remove the line.

Always nice to review config, I have no idea what I did there -_-
Worked fine with 249, so I guess you did a good job with input validation in 250 ;)
Thank you very much for the hint!
