### ISSUE TITLE
symlinked override.d directory is ignored

### ISSUE THREAD

**Issue by Scrumplex** [systemd/systemd#21920]
**systemd version the issue has been seen with** 
 > since 250

**Used distribution**
 > Arch Linux, systemd 250-3

**Linux kernel version used** (`uname -a`)

 > `Linux andromeda 5.15.11-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 22 Dec 2021 09:23:53 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > unit gets overriden by configuration files located in a symlinked <unit-name>.d directory

**Unexpected behaviour you saw**
 > systemd ignores the overrides, while `systemctl edit` still recognizes the override(s)

**Steps to reproduce the problem**
 > - Choose or create a service to test this with
 >   - I created this [example.service](https://github.com/systemd/systemd/files/7784200/example.service.txt) and placed it in `~/.config/systemd/user/example.service`
 > - Create a directory somewhere else. In my case I created `~/example`
 > - Place a `override.conf` in `~/example`. In my case I created this [override.conf](https://github.com/systemd/systemd/files/7784204/override.conf.txt)
 > - Create a symlink as follows: `ln -s ../../../example/ ~/.config/systemd/user/example.service.d` (points to `~/example` relative to the user units directory)
 > - Run `systemctl --user daemon-reload` and inspect the resulting unit using `systemctl --user cat example.service`
 > - No override took place
 > - But `systemctl --user edit example.service` opens our `override.conf` as expected

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
$ cat .config/systemd/user/example.service
[Unit]
Description=Example service to reproduce a bug

[Service]
ExecStart=/usr/bin/sleep 1000

[Install]
WantedBy=default.target

```
```

$ ls -laF .config/systemd/user/example.service.d
lrwxrwxrwx 1 scrumplex scrumplex 16 Dec 28 11:29 .config/systemd/user/example.service.d -> ../../../example/

```
```

$ cat example/override.conf 
[Unit]
Description=actually overridden description of example service

```
```

$ systemctl --user cat example.service
# /home/scrumplex/.config/systemd/user/example.service
[Unit]
Description=Example service to reproduce a bug

[Service]
ExecStart=/usr/bin/sleep 1000

[Install]
WantedBy=default.target

```
```

$ EDITOR=cat systemctl --user edit example.service
### Editing /home/scrumplex/.config/systemd/user/example.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Unit]
Description=actually overridden description of example service

### Lines below this comment will be discarded

### /home/scrumplex/.config/systemd/user/example.service
# [Unit]
# Description=Example service to reproduce a bug
# 
# [Service]
# ExecStart=/usr/bin/sleep 1000
# 
# [Install]
# WantedBy=default.target

```

**Comment by Scrumplex** [comment]
I should add symlinking the `override.conf` directly and creating the `example.service.d` directory, does still work as expected. So it's just symlinked unit.d directories that are treated differently.

**Comment by Scrumplex** [comment]
This is not specific to user services. I just tested the same setup with a system service and the override directory located at `/opt/example`

**Comment by bluca** [comment]
This was caused by: https://github.com/systemd/systemd/pull/20882

**Comment by yuwata** [comment]
Fix is waiting in #21925.

**Comment by Scrumplex** [comment]
Thanks @yuwata for fixing this!

**Comment by amishmm** [comment]
Just for the record, the issue was reported on mailing list too.
https://lists.freedesktop.org/archives/systemd-devel/2021-December/047243.html
