### ISSUE TITLE
intermittent failure to mount /boot on ArchARM armv6 

### ISSUE THREAD

**Issue by gearhead** [systemd/systemd#21932]
**systemd version the issue has been seen with**
 >249.7-2-arch

**Used distribution**
 >ArchArm linux-rpi-legacy armv6h

**Linux kernel version used** (`uname -a`)
 > `Linux runeall 5.10.87-1-rpi-legacy #1 Mon Dec 27 13:24:45 CST 2021 armv6l GNU/Linux`

**CPU architecture issue was seen on**
 > armv6h

**Expected behaviour you didn't see**
 > consistent booting

**Unexpected behaviour you saw**
 >intermittent failure to mount /boot from /dev/mmcblk0p1. Gets a timeout on mounting of /boot. Does not happen with faster Pis nor with armv6 Pis without onboard audio (PiZero).

**Steps to reproduce the problem**
 >Reboot the RPi B1 many times with the onboard audio enabled (dtparam=audio=on). Eventually it will fail to boot and you are presented with the option to go into emergency mode. Input the root password then mount the boot partition `mount -a` then reboot and it will cleanly reboot until it fails again. It is intermittent does not do it all the time, but requires an emergency mode mount to temporarily fix the problem. This is challenging for a device which is supposed to be headless. This bug is a recent development from early December or late November 2021. We have not seen it previously.  I do not have a debug version of the journal, yet, but will post it when it fails to boot, again. 

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Nov 30 20:17:49 runeall systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start timed out.
Nov 30 20:17:49 runeall systemd[1]: Timed out waiting for device /dev/mmcblk0p1.
Nov 30 20:17:49 runeall systemd[1]: Dependency failed for /boot.
Nov 30 20:17:49 runeall systemd[1]: Dependency failed for Local File Systems.
Nov 30 20:17:49 runeall systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
Nov 30 20:17:49 runeall systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
Nov 30 20:17:49 runeall systemd[1]: boot.mount: Job boot.mount/start failed with result 'dependency'.
Nov 30 20:17:49 runeall systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start failed with result 'timeout'.
```

**Comment by gearhead** [comment]
I tried to set systemd to debug and rebooted numerous times and the RPi B1 I have been working with now reboots cleanly every time. I tried all evening and all this morning and it reboots. I did nothing to it that I am aware of, but it failed many times previously. I have a 2 other RPi B1s one seems to reboot fine every time and another which fails more often. Neither are at this location. I will spend my time with that one that is failing to see if I can get more info as to why it is failing to mount /boot at startup. Updates when available.

**Comment by gearhead** [comment]
I was able to finally get a log with debug set. 
[journalctl_fail_2.txt](https://github.com/systemd/systemd/files/7808490/journalctl_fail_2.txt)
This is an intermittent failure. When it fails, no amount of power cycling will recover the Pi and allow it to boot. You must go to emergency mode, mount the boot partition and then reboot. Then it will continue to reboot until it doesn't, again. Repeat.  
I have another which is also failed. I will see if I can get a debug log from it as well.

**Comment by mrc0mmand** [comment]
The relevant lines from the journal seem to be:
```
Nov 30 20:16:44 runeall kernel: cam1-reg: disabling
Nov 30 20:16:44 runeall kernel: cam-dummy-reg: disabling
Nov 30 20:17:26 runeall systemd-udevd[107]: card0: Spawned process '/srv/http/command/refresh_ao' [112] is taking longer than 59s to complete
Nov 30 20:17:26 runeall systemd-udevd[110]: card1: Spawned process '/srv/http/command/refresh_ao' [113] is taking longer than 59s to complete
Nov 30 20:17:26 runeall systemd-udevd[104]: card0: Worker [107] processing SEQNUM=718 is taking a long time
Nov 30 20:17:26 runeall systemd-udevd[104]: card1: Worker [110] processing SEQNUM=721 is taking a long time
Nov 30 20:17:26 runeall systemd[1]: systemd-udevd.service: Got notification message from PID 104 (WATCHDOG=1)
Nov 30 20:17:31 runeall systemd-udevd[116]: lo: Spawned process '/srv/http/command/refresh_nics' [120] is taking longer than 59s to complete
Nov 30 20:17:31 runeall systemd-udevd[104]: lo: Worker [116] processing SEQNUM=1045 is taking a long time
Nov 30 20:17:48 runeall kernel: random: crng init done
Nov 30 20:17:48 runeall kernel: random: 7 urandom warning(s) missed due to ratelimiting
Nov 30 20:17:48 runeall systemd[1]: systemd-journald.service: Received EPOLLHUP on stored fd 50 (stored), closing.
Nov 30 20:17:48 runeall systemd[1]: Received SIGCHLD from PID 91 (systemd-random-).
Nov 30 20:17:48 runeall systemd[1]: Child 91 (systemd-random-) died (code=exited, status=0/SUCCESS)
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Child 91 belongs to systemd-random-seed.service.
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Main process exited, code=exited, status=0/SUCCESS (success)
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Changed start -> exited
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Job 45 systemd-random-seed.service/start finished, result=done
Nov 30 20:17:48 runeall systemd[1]: Finished Load/Save Random Seed.
Nov 30 20:17:48 runeall systemd[1]: systemd-random-seed.service: Control group is empty.
Nov 30 20:17:48 runeall systemd[1]: first-boot-complete.target: ConditionFirstBoot=yes failed.
Nov 30 20:17:48 runeall systemd[1]: first-boot-complete.target: Starting requested but condition failed. Not starting unit.
Nov 30 20:17:48 runeall systemd[1]: first-boot-complete.target: Job 46 first-boot-complete.target/start finished, result=done
Nov 30 20:17:48 runeall systemd[1]: Condition check resulted in First Boot Complete being skipped.
Nov 30 20:17:48 runeall systemd[1]: systemd-boot-system-token.service: starting held back, waiting for: local-fs.target
Nov 30 20:17:48 runeall systemd[1]: systemd-machine-id-commit.service: starting held back, waiting for: local-fs.target
Nov 30 20:17:49 runeall systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start timed out.
Nov 30 20:17:49 runeall systemd[1]: dev-mmcblk0p1.device: Job 39 dev-mmcblk0p1.device/start finished, result=timeout
Nov 30 20:17:49 runeall systemd[1]: Timed out waiting for device /dev/mmcblk0p1.
Nov 30 20:17:49 runeall systemd[1]: boot.mount: Job 38 boot.mount/start finished, result=dependency
Nov 30 20:17:49 runeall systemd[1]: Dependency failed for /boot.
```

Not sure what `/srv/http/command/refresh_ao'` is/does, but it seems to be the culprit why the `boot.mount` job times out.

**Comment by gearhead** [comment]
Good catch. That is a script started from udev. Will see what it takes to move this task or the start of udev to 'after' the volumes are mounted. This never shows as a problem on any other Pis only the old, slow Pi 1B and B+.
Thanks

**Comment by gearhead** [comment]
problem solved by delaying the run of that script. Would be nice if we could poll systemd to find if final target is met, i.e. graphical or multi-user, from other scripts (bash in this case). What we ended up doing is to put a soft link in the /etc/udev/rules.d/ folder to our rule and put the rule on a tmpfs so it gets loaded later in the process, but that is a hack... IMO it would be cleaner if we could poll to see if we are at our default target then run else skip.

**Comment by poettering** [comment]
Don't run long-running stuff from udev rules, that's really not what this is intended for. udev rules are supposed to be quick stuff that runs and exits in instants. If you udev rule script runs for a minute, it's *waaay* too slow.

Generally, for anything "payload", i.e. that is more than just acquiring some meta info about a device, use service activation form udev rules instead of direct script callouts. i.e. use the SYSTEMD_WANTS udev property to tell systemd to pull in a service or service instance for your device

**Comment by poettering** [comment]
Anyway, closing as this appears to be a downstream/user issue, not an upstream one.
