### ISSUE TITLE
README: CONFIG_KCMP instead of CONFIG_CHECKPOINT_RESTORE?

### ISSUE THREAD

**Issue by trentbuck** [systemd/systemd#21947]
**systemd version the issue has been seen with**
 > https://github.com/systemd/systemd/blob/v250/README#L89

**Linux kernel version used** (`uname -a`)

 > https://github.com/torvalds/linux/commit/bfe3911a91047557eb0e620f95a370aee6a248c7 (around 5.10+)

**Additional program output to the terminal or log subsystem illustrating the issue**

I just noticed there's a dedicated CONFIG_KCMP option in current kernels.
I don't have time today to prove it experimentally, but
I think where README says  "CONFIG_CHECKPOINT_RESTORE for kcmp" it can now simply say "CONFIG_KCMP".

**Comment by michaelolbrich** [comment]
`CONFIG_KCMP` was introduced with 5.12 and we support much older kernel. So the README should probably mention both.
