### ISSUE TITLE
Broken right ctrl on HP laptop

### ISSUE THREAD

**Issue by UnkwUsr** [systemd/systemd#21957]
**Expected behaviour you didn't see**
 > Pressing right ctrl key should produce ctrl keycode

**Unexpected behaviour you saw**
 > Pressing right ctrl key produces keycode for key `<`

It started after this commit: https://github.com/systemd/systemd/commit/55dad038b21ab6a91be3aba1c071f0f667844653

My laptop (HP 15s-eq0077ur) keyboard looks like this (https://120w.ru/upload/iblock/2c2/2c26a717b1638eeaf6990f558a6904e3.jpeg)

I'm not very familiar with systemd codebase, but probably selector just should be stricter. @scardracs, could you please take a look at this?

**Comment by scardracs** [comment]
Uh, seems my change had to be much more stricter

**Comment by scardracs** [comment]
@UnkwUsr could you run `sudo dmidecode | grep -A3 '^System Information'` and put the result?

**Comment by UnkwUsr** [comment]
@scardracs (that's all output)
```
System Information
        Manufacturer: HP
        Product Name: HP Laptop 15s-eq0xxx
        Version:
```

**Comment by scardracs** [comment]
Like mine...

**Comment by UnkwUsr** [comment]
Maybe that would be helpful?
```
        SKU Number: 2L2T0EA#ACB
        Family: 103C_5335KV HP Notebook
```

**Comment by scardracs** [comment]
Not really, as we have the same Product Name and 60-keyboard.conf is based on it. I'm gonna ask on IRC if there is a way to differentiate my model from others to make it more specific

**Comment by scardracs** [comment]
@bluca do you have any ideas?

**Comment by scardracs** [comment]
I hope https://github.com/systemd/systemd/pull/21958 will close it

**Comment by UnkwUsr** [comment]
Yeah, for me all works good

**Comment by scardracs** [comment]
Perfect, could You wait for merging and then close bug?
