### ISSUE TITLE
sd-boot: sbsign warns about gaps in the section table, and causing secureboot failures

### ISSUE THREAD

**Issue by NickCao** [systemd/systemd#21956]
**systemd version the issue has been seen with**
 > systemd 250 (250)
+PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)

 > `Linux local 5.15.12 #1-NixOS SMP Wed Dec 29 11:29:03 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > secureboot works after sigining `systemd-bootx64.efi` with sbsign

**Unexpected behaviour you saw**
 > sbsign signs without errors but warnings, and the resulting binary is not treated by firmware as signed.

**Steps to reproduce the problem**
 > sbsign --key db.key --cert db.crt systemd-bootx64.efi

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
warning: gap in section table:
    .text   : 0x00000400 - 0x00012c00,
    /4      : 0x00012cc0 - 0x00013ec0,
warning: gap in section table:
    /4      : 0x00012cc0 - 0x00013ec0,
    .sbat   : 0x00013e00 - 0x00014000,
warning: gap in section table:
    .sbat   : 0x00013e00 - 0x00014000,
    .osrel  : 0x00014100 - 0x00014300,
warning: gap in section table:
    .osrel  : 0x00014100 - 0x00014300,
    .sdmagic: 0x00014340 - 0x00014540,
warning: gap in section table:
    .sdmagic: 0x00014340 - 0x00014540,
    .reloc  : 0x00014600 - 0x00014800,
gaps in the section table may result in different checksums
warning: data remaining[107520 vs 123808]: gaps between PE/COFF sections?
Signing Unsigned original image
```
cc: @andir 
ref: https://github.com/NixOS/nixpkgs/pull/150491

**Comment by NickCao** [comment]
According to https://www.rodsbooks.com/efi-bootloaders/controlling-sb.html#signing, this kind of issue can be caused by an outdated version of gnu-efi, however NixOS is now on gnu-efi 3.0.11, far newer than the affected versions.
Thus I suspect changes from systemd-boot are causing the breakage, and some candidates are:
  - https://github.com/systemd/systemd/pull/21264
  - https://github.com/systemd/systemd/pull/21231

**Comment by ajakk** [comment]
Getting something somewhat similar on Gentoo, too, and downgrading to 249 fixes it ('linux' here is a dracut-produced efi with the systemd-boot efi stub):

```
# sbsign --key /etc/efi-keys/DB.key --cert /etc/efi-keys/DB.crt linux
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[57697792 vs 57711930]: gaps between PE/COFF sections?
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[57697792 vs 57711936]: gaps between PE/COFF sections?
Signing Unsigned original image
```

**Comment by Foxboron** [comment]
Can someone upload an invalid STUB? I have tried reproducing this issue and everything seems fine on my end.

**Comment by ajakk** [comment]
[linuxx64.efi.stub.gz](https://github.com/systemd/systemd/files/7823478/linuxx64.efi.stub.gz)

(gzipped thanks to GitHub file type requirements)

Grabbed this out of my Gentoo-built systemd 250, trying to sign and verify it yields:

```
# sbsign --key /etc/efi-keys/DB.key --cert /etc/efi-keys/DB.crt linuxx64.efi.stub
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[70656 vs 84794]: gaps between PE/COFF sections?
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[70656 vs 84800]: gaps between PE/COFF sections?
Signing Unsigned original image

# sbverify --cert /etc/efi-keys/DB.crt linuxx64.efi.stub
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[70656 vs 84794]: gaps between PE/COFF sections?
warning: gap in section table:
    .sbat   : 0x00011000 - 0x00011200,
    .sdmagic: 0x00011300 - 0x00011500,
gaps in the section table may result in different checksums
warning: data remaining[70656 vs 84800]: gaps between PE/COFF sections?
No signature table present
Signature verification failed
```

**Comment by Foxboron** [comment]
You are not verifying the signed binary. Please run `sbverify --cert /etc/efi-keys/DB.crt linuxx64.efi.stub.signed`

**Comment by Foxboron** [comment]
Ugh, terribly sorry for the noise. Seems like @ajakk is mixing up the STUB file with the bootloader which confused me.
