### ISSUE TITLE
homed does not map subids, causing files owned by the subids to become "nobody"

### ISSUE THREAD

**Issue by alaviss** [systemd/systemd#21952]
**systemd version the issue has been seen with**
 > systemd 250 (250)
+PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID -CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 +LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**
 > Gentoo Linux

**Linux kernel version used** (`uname -a`)
 > `Linux leorize-lnx-workstation 5.15.12-gentoo #1 SMP PREEMPT Thu Dec 30 21:06:30 CST 2021 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Files owned by subuid/subgid to be owned by the current user

**Unexpected behaviour you saw**
 > They are mapped to `nobody`, and any attempts to use the subuid feature (ie. via `podman` rootless) yields `Invalid argument` on `chown`.

**Steps to reproduce the problem**
 > Have `podman` rootless setup, then run `touch foo; podman unshare chown 0:42 foo`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
$ touch foo; podman unshare chown 0:42 foo
chown: changing ownership of 'foo': Invalid argument
```

Some details on my subid ranges:

```text
$ getsubids leorize
0: leorize 200000 65536

$ getsubids -g leorize
0: leorize 200000 65536
```

If I understand the code correctly, then `homed` does not map ranges outside of the 16-bit boundary, thus making it impossible to use the home directory as container storage.

Right now I run a version of `homed` with remapping disabled in order to keep using rootless containers.

**Comment by poettering** [comment]
So podman puts stuff owned by other users into $HOME? I mean, that might be OK as a hack, but as a regular workflow is a mess, for quota reasons and such. It really shouldn't do that.

We map the 16bit range outside of the homed range as is, so that people can unpack containers under their regular UID range. Container managers should be able to run these then in an userns environment via uidmapping things. This is what nspawn does these days, and podman should too. Actually making high UIDs hit the disk is a mess...

**Comment by mralexandernickel** [comment]
not sure if this comment is helpful, but I am using systemd-homed and podman for around a year now, and this issue came up for me between the 15th of december and the 15th of january (been on vacation so I cannot tell the exact date), so the change causing this issue (not knowing if in systemd, podman or something else) should have been rolled out (on arch linux) during that time. 

before that, everything was working like a charm.

**Comment by poettering** [comment]
Closing, as 1af53c0fa8a945616e371cb9cc75ea882874a09c was merged.

**Comment by sequencer** [comment]
I also encountered this issue today:
```
archlinux% getsubids sequencer
0: sequencer 100000 65536
archlinux% touch foo; podman unshare chown 0:42 foo
chown: changing ownership of 'foo': Invalid argument
archlinux% systemctl --version
systemd 251 (251.rc1.81.g64c843d12d-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by alaviss** [comment]
The container uid range starts at 524288 by default unless configured via `-Dcontainer-uid-base-min` to something lower. Your ids starts at 100000, which is below this range.

**Comment by pythops** [comment]
@alaviss 
I have the same issue as well. When you say:
> Right now I run a version of homed with remapping disabled in order to keep using rootless containers.

How did you do it ?

**Comment by alaviss** [comment]
With this simple patch

```diff
Disable homed UID mapping. This seems to interfere with containers.
Index: systemd-250/src/home/homework-mount.c
===================================================================
--- systemd-250.orig/src/home/homework-mount.c
+++ systemd-250/src/home/homework-mount.c
@@ -229,6 +229,9 @@ int home_shift_uid(int dir_fd, const cha
         assert(uid_is_valid(stored_uid));
         assert(uid_is_valid(exposed_uid));
 
+        /* Don't even try */
+        return 0;
+
         /* Let's try to set up a UID mapping for this directory. This is called when first creating a home
          * directory or when activating it again. We do this as optimization only, to avoid having to
          * recursively chown() things on each activation. If the kernel or file system doesn't support this
```

This should be obsolete by the time systemd 251 comes around, though.

**Comment by AkihiroSuda** [comment]
> 524288 by default

How was this decided?
`useradd` allocates subuid ranges from 100000.
