### ISSUE TITLE
user's private units won't start on a systemd-homed managed encrypted home directory

### ISSUE THREAD

**Issue by billyzs** [systemd/systemd#21963]
**systemd version the issue has been seen with**
`systemd 250 (250-4-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified`

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)

 > `…`
`Linux hayabusa 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux`

I am using systemd-homed to manage my use's home folder, and it's using fscrypt encryption. I also have a few systemd services that I want to run as user, ideally automatically after I login as the user, and the unit needs access to the home folder to read config files and mount a directory there. I've enabled linger for this user. The unit files are stored in ~/.config/systemd/user and look like the below. The same unit file was able to automatically start itself on a properly configured system that's not using systemd-homed.

[Unit]
Description=box       
AssertPathIsDirectory=/home/me/box

[Service]
Type=notify
ExecStart=/usr/bin/rclone mount \
        # some mount config omitted
       
Restart=always
RestartSec=10

[Install]
WantedBy=default.target

**Expected behaviour you didn't see**
After login, box.service automatically starts

**Unexpected behaviour you saw**
After login, I see
```
systemctl --user status box
○ box.service - box
     Loaded: loaded (/home/bzs/.config/systemd/user/box.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```
I have to manually run `systemctl --user start box` to get the service to start. 

The same unit file worked before switching this user to systemd-homed. I'm wondering if systemd-homed is interfering with the autostarting of user units here, or if I misconfigured the user units.

Happy to provide additional logs if needed. I saw that #19644 is similar but here I'm actually using systemd-homed's builtin support for fscrypt for de/encryption.

**Comment by poettering** [comment]
Please provide logs, otherwise this is not actionable

**Comment by poettering** [comment]
Closing due to lack of response.
