### ISSUE TITLE
Change in tmpfiles.d/tmp.conf causes /tmp mislabeling.

### ISSUE THREAD

**Issue by mgrepl** [systemd/systemd#2196]
In Fedora 23 we have

```
   v /tmp 1777 root root 10d
```

but we have

```
  q /tmp 1777 root root 10d
```

in rawhide as a part of "/usr/lib/tmpfiles.d/tmp.conf". 

It casuses /tmp is labeled as tmpfs_t instead of tmp_t. 

https://bugzilla.redhat.com/show_bug.cgi?id=1286964

**Comment by ghost** [comment]
I realise that it would be a major undertaking in Fedora but why not treat /tmp (and /run/user/UID) as as /dev/shm (e.g. ignore any labels under there unless undesirable, and let it default to tmpfs_t)?

Then you only have /var/tmp left as tmp_t.

I haven't encountered this issue in my policy because /tmp /dev/shm and /run/user/UID all default to "tmpfs_t". It makes my policy simpler.

I will admit though that leaving /run/user/UID type tmpfs_t in the long run may (or may not) be possible due to MLS requirements but in the current situation having /run/user/UID tmpfs_t seems to work fine here.

**Comment by ghost** [comment]
But yes eventually i suspect this should be taken care of for MLS eitherway.

So I think I agree with OP

**Comment by mgrepl** [comment]
It is a correct point  of view. We have been talking about this solution with plautrba and lvrabec. We would like to play around and have a discussion about this change with upstream. And yes we also need to take care about MLS and Common Criteria.

This is a reason why I created this issue to have a fix in systemd code.

**Comment by poettering** [comment]
Well, I don't see what precisely should have changed there in the code to cause this, and my Selinux-fu is too limited to do something about this... Kinda relying on submitter patches here...

**Comment by neel-parikh** [comment]
@mgrepl @doverride 
We have these changes in the systemd, however, we still see that /tmp is incorrectly labelled as tmpfs_t.

Can some please suggest if there are any additional changes in the SELinux policies required?

Thanks.

**Comment by doverride** [comment]
On Tue, Mar 13, 2018 at 03:01:00PM +0000, Neel Parikh wrote:
> @mgrepl @doverride 
> We have these changes in the systemd, however, we still see that /tmp is incorrectly labelled as tmpfs_t.
> 
> Can some please suggest if there are any additional changes in the SELinux policies required?

That depends on the policy obviously, and I do not know what policy you enforce.

Reference policy has a file context spec for /tmp so from that perspective Reference policy should be ok i think.

If the above applies then i suppose systemd is not resetting the context of /tmp *after* it mounted tmpfs on there

In that case either ask systemd to do a label_fix() on /tmp after it mounted tmpfs on it, or add a tmpfiles snippet that resets the label of /tmp.

I am not the right person to ask though, I accepted and use the default label of "tmpfs_t" for /tmp.

> 
> Thanks.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/2196#issuecomment-372696133

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wrabcak** [comment]
Hi @neel-parikh , 

I checked Fedora distribution is using same labeling as reference policy. I checked F27+ and there is no issue with /tmp labeled as tmpfs_t. 

What kind of system are you using?

**Comment by neel-parikh** [comment]
I'm using the latest Fedora reference policy (From Jan 2018) and my system is RedHat Linux (poky2.3).
I need /tmp labelled as tmp_t instead of tmpfs_t to support backward compatibility.

**Comment by doverride** [comment]
On Tue, Mar 13, 2018 at 08:54:37AM -0700, Neel Parikh wrote:
> I'm using the latest Fedora reference policy (From Jan 2018) and my system is RedHat Linux (poky2.3).
> I need /tmp labelled as tmp_t instead of tmpfs_t to support backward compatibility.

systemd was built with SELinux support? `systemctl --version`

> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/2196#issuecomment-372715869

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by neel-parikh** [comment]
Yes it was.
systemctl --version

systemd 232
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

**Comment by doverride** [comment]
On Tue, Mar 13, 2018 at 05:04:06PM +0000, Neel Parikh wrote:
> Yes it was.
> systemctl --version
> 
> systemd 232
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

And when you run restorecon -RvF /tmp , it resets the type to tmp_t?

If yes, then I suppose systemd didnt reset the label for some reason

In that case you could try adding a tmpfiles snippet to relabel /tmp, you can also see if it works in permissive mode

And you can see whether SELinux would allow systemd to reset:

sesearch -A -s init_t -t tmp_t -c dir -p relabelto
sesearch -A -s init_t -t tmpfs_t -c dir -p relabelfrom

> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/2196#issuecomment-372741612

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by neel-parikh** [comment]
Yes, restorecon relabels the /tmp dir to tmp_t.
I tested in permissive mode but I still get tmpfs_t label on boot.

Can you let me know what tmpfiles snippet I should add to solve this problem?

Thanks a lot for the response.

**Comment by doverride** [comment]
On Tue, Mar 13, 2018 at 05:46:01PM +0000, Neel Parikh wrote:
> Yes, restorecon relabels the /tmp dir to tmp_t.
> I tested in permissive mode but I still get tmpfs_t label on boot.
> 
> Can you let me know what tmpfiles snippet I should add to solve this problem?

something like:

echo "Z /tmp 1777 root root - -" > /etc/tmpfiles.d/mytmpfix.conf

reboot

> 
> Thanks a lot for the response.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/2196#issuecomment-372756164

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by neel-parikh** [comment]
Ok great. I'll give it a shot and see if this solves the problem.
Thanks for your help. :)
