### ISSUE TITLE
The debian systemd package seems to prevent the nss tests from being run under ASan/UBsan on GHActions

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#21975]
In https://github.com/systemd/systemd/issues/21935#issuecomment-1003214505 it was pointed out that neither `test-nss-hosts` nor `test-nss-users` is run automatically on a regular basis. To address that https://github.com/systemd/systemd/pull/21946 was opened where the tests failed under UBSan as expected. That PR was closed in favor of https://github.com/systemd/systemd/pull/21778 where the tests keep failing on Ubuntu CI/Semaphore CI because `systemd` is built with `nss` there but `libnss-*` packages aren't installed when the "unit-tests" test is run. It would be great if it was possible to either fix the debian package or skip the test upstream. Turns out all those "deny-list-ubuntu-ci " files affect the "upstream" tests only (which I already turned off in that PR).

cc @mbiebl @bluca

**Comment by bluca** [comment]
Added the libnss packages to the list in https://salsa.debian.org/systemd-team/systemd/-/commit/dc410d701dec5b526c4a349ae377254c0cef899c and restarted the test runs in https://github.com/systemd/systemd/pull/21778

**Comment by evverx** [comment]
Thanks! I'll wait for Ubuntu CI/Semaphore CI to finish there to make sure the issue is gone and then I'm going to drop the last commit (where I turned off TEST-02-UNITTESTS with deny-list-ubuntu-ci) to figure out whether the "upstream" test needs fixing too.

**Comment by evverx** [comment]
To judge from https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/s390x/s/systemd-upstream/20220103_155527_939db@/log.gz where TEST-02-UNITTESTS failed with
```
...
======== mymachines ========
Failed to load module mymachines: libnss_mymachines.so.2: cannot open shared object file: No such file or directory

...
--- test-nss-hosts begin ---
======== myhostname ========
Failed to load module myhostname: libnss_myhostname.so.2: cannot open shared object file: No such file or directory
```
the "upstream" test needs updating too.

The "unit-tests" test seems to pass now though and SemaphoreCI is green because the "upstream" test isn't run there.

**Comment by bluca** [comment]
Ok, added https://salsa.debian.org/systemd-team/systemd/-/commit/ac0c3a5506897adcbdeb89345456c0465206ee37 and restarted the s390x test run

**Comment by evverx** [comment]
Looks like it passed in https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/s390x/s/systemd-upstream/20220103_171012_3c1da@/log.gz. Thanks!

I'll force-push the PR to trigger all of them once again just to be sure.
