### ISSUE TITLE
machinectl shell seems to mess up a virtual terminal when run from x context

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#2198]
Hello.

I have the following thing to report: if you log into x, for example to gnome desktop, and start up a terminal emulator, then the bash inside is running on pts and the x server and x session runs on the vt.
In the emulator I type machinectl shell to gain root access. it is successful. I exit from the root shell, and then type ctrl+c in the graphical terminal emulator. The x server gets killed immediately, logging me out.
I have discovered that, after machinectl shell, kbd_mode command ran on the vt corresponding to the x session reports UTF-8 mode, so the keys go both to the x server and to the vt. so ctrl+c sends sigint to the x server...

**Comment by wlhlm** [comment]
This sounds like #2061

**Comment by poettering** [comment]
https://github.com/systemd/systemd/issues/2061#issuecomment-166692238 contains some notes on what might cause the issue.

**Comment by poettering** [comment]
Fix waiting in #2463.
