### ISSUE TITLE
AC power check wrong for discrete GPUs with USB-C

### ISSUE THREAD

**Issue by Sizurka** [systemd/systemd#21988]
**systemd version the issue has been seen with**
> $ systemctl --version
systemd 250 (250-4-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux kitsune.inthat.cloud 5.15.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 29 Dec 2021 12:04:52 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > Not on AC power reported for a system with only AC power (a desktop with a discrete GPU):
```
$ systemd-analyze condition ConditionACPower=yes
test.service: ConditionACPower=yes failed.
Conditions failed.
```

**Steps to reproduce the problem**
 > This is a system with a discrete GPU (AMD Radeon 6900 XT) that has a USB-C connector.  The USCI for that appears to reporting a power type of "USB" and offline (nothing connected).  Since there are no other power supplies, this is making systemd think the system is not on AC power. 

Basically: this system only has one entry in `/sys/class/power_supply/` but that entry is the power **output** from a discrete GPU (or at least it certainly can't run the system), which is reporting offline.  Since there is no other power available, the check `on_ac_power()` believes the system does not have AC power.   I believe the problem is c19a51bec40ae5e5073464e72411e7920d05d683, prior to that the check would have excluded the UCSI power.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
$ ls /sys/class/power_supply
ucsi-source-psy-0-00081
```

```
$ grep . /sys/class/power_supply/ucsi-source-psy-0-00081/*
/sys/class/power_supply/ucsi-source-psy-0-00081/current_max:0
/sys/class/power_supply/ucsi-source-psy-0-00081/current_now:0
grep: /sys/class/power_supply/ucsi-source-psy-0-00081/device: Is a directory
grep: /sys/class/power_supply/ucsi-source-psy-0-00081/hwmon6: Is a directory
/sys/class/power_supply/ucsi-source-psy-0-00081/online:0
grep: /sys/class/power_supply/ucsi-source-psy-0-00081/power: Is a directory
grep: /sys/class/power_supply/ucsi-source-psy-0-00081/subsystem: Is a directory
/sys/class/power_supply/ucsi-source-psy-0-00081/type:USB
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_NAME=ucsi-source-psy-0-00081
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_TYPE=USB
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_USB_TYPE=[C] PD PD_PPS
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_ONLINE=0
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_VOLTAGE_MIN=0
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_VOLTAGE_MAX=0
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_VOLTAGE_NOW=0
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_CURRENT_MAX=0
/sys/class/power_supply/ucsi-source-psy-0-00081/uevent:POWER_SUPPLY_CURRENT_NOW=0
/sys/class/power_supply/ucsi-source-psy-0-00081/usb_type:[C] PD PD_PPS
/sys/class/power_supply/ucsi-source-psy-0-00081/voltage_max:0
/sys/class/power_supply/ucsi-source-psy-0-00081/voltage_min:0
/sys/class/power_supply/ucsi-source-psy-0-00081/voltage_now:0
grep: /sys/class/power_supply/ucsi-source-psy-0-00081/wakeup47: Is a directory
```

**Comment by yuwata** [comment]
Could you show `/sys/class/power_supply/ucsi-source-psy-0-00081/device/typec/portX/power_role`?

**Comment by Sizurka** [comment]
```
$ grep -H . /sys/class/power_supply/ucsi-source-psy-0-00081/device/typec/port*/power_role 
/sys/class/power_supply/ucsi-source-psy-0-00081/device/typec/port0/power_role:[source]
```

**Comment by yuwata** [comment]
@Sizurka Thanks. Could you test #22006? If it does not work, then please provide the result of
```
SYSTEMD_LOG_LEVEL=debug build/systemd-ac-power
```

**Comment by Sizurka** [comment]
```
$ SYSTEMD_LOG_LEVEL=debug build/systemd-ac-power
sd-device-enumerator: Scan all dirs
sd-device-enumerator: Scanning /sys/bus
sd-device-enumerator: Scanning /sys/class
ucsi-source-psy-0-00081: USB power supply is in source mode, ignoring.
```

`build/systemd-analyze condition ConditionACPower=yes` also gives the expected result (condition passed) so that looks like a fix.  Thanks.

**Comment by yuwata** [comment]
@Sizurka Thank you!
