### ISSUE TITLE
random-seed.c should be mindful of reseeding states

### ISSUE THREAD

**Issue by zx2c4** [systemd/systemd#21983]
At boot, systemd will read the existing seed file and call `RNDADDENTROPY` on it. It will then extract a new seed and write that to disk. What happens between adding that entropy and extracting a new seed?

- Case A) If you call `RNDADDENTROPY` at `crng_init<2`, and there's enough entropy in your call, it'll switch to `crng_init==2` and reseed everything. The subsequent extraction will then be fine.
- Case B) If you call `RNDADDENTROPY` and you're already at `crng_init==2`, then it won't reseed everything. You could call `RNDRESEEDCRNG` after if you wanted it to have an immediate effect, but it's not super important, since there's already sufficient entropy from before. The subsequent extraction is fine.
- Case C) If you call `RNDADDENTROPY` at `crng_init<2`, and there's **not** enough entropy in your call, it'll just mix it into the pool, but nothing will happen immediately. The subsequent extraction will then use potentially crappy randomness.

Case C might be a bit of a problem. Stemming out of a conversation with @thejh, we were thinking:
- For newer kernels, [this pending commit](https://git.kernel.org/pub/scm/linux/kernel/git/crng/random.git/commit/?id=b1fde14b931d941abfaa91a7ac9d72b2f5c834ab) will mean that calling `RNDRESEEDCRNG` before you extract a new seed to write to disk will mostly do the rightish thing for the `crng_init<2` case.
- For older kernels, it's not a great situation, but you could at least hash together the old seed file and the new seed file before writing it out to disk.

Thoughts on this?

CC @poettering

**Comment by zx2c4** [comment]
Looking at the systemd code a bit now, following the discussion with Jann, I'm not totally sure this matters (or even that the linked pending commit is totally necessary).

- For random-seed.c's "load" mode, there's a synchronous call to `getrandom()` before writing out a new seed file to disk. That means we're in "case B" territory, and things are fine. 
- If the kernel doesn't support `getrandom()`, that pending commit doesn't help anyway. The best we can do in that case is hash it together with the old seed; that still might be a good suggestion for these cases.
- For random-seed.c's "save" mode, it may well fall back to insecure /dev/urandom if called too early, but the concern we should have here is mostly about "load" mode, right? "save" should only be called at shutdown, correct?

I'll wait for @thejh to chime in if he sees things differently.

**Comment by zx2c4** [comment]
I think, actually, https://github.com/systemd/systemd/pull/21986 is really all that's necessary to fix this up for all cases - old kernels and new.

**Comment by thejh** [comment]
I do think there's still value in `RNDRESEEDCRNG` in case B - sure, the kernel is _fairly_ sure that it has enough entropy, but there might well be some kind of embedded device where that estimate is overly optimistic because all our hardware runs off a single deterministic clock, or something along those lines.

So it probably _usually_ doesn't matter; but this would be the metaphorical suspenders juuust in case the kernel can't get enough entropy on its own and vastly overestimates how random interrupt timing and such is.
