### ISSUE TITLE
`systemd-cryptsetup`: option `keyfile-timeout=` is broken (possibly only in combination with raw device key material)

### ISSUE THREAD

**Issue by Alexander-Shukaev** [systemd/systemd#21993]
**systemd version the issue has been seen with**
 > `systemd 249 (249.7-2-arch)`

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux strix 5.15.8-arch1-1 #1 SMP PREEMPT Tue, 14 Dec 2021 12:28:02 +0000 x86_64 GNU/Linux
`

**Expected behaviour you didn't see**
 > Waiting for `/dev/disk/by-id/key-storage` should time out after `keyfile-timeout` (e.g. 5 seconds) and a fallback passphrase entry prompt should be presented.

**Unexpected behaviour you saw**
 > `/dev/disk/by-id/key-storage` received default timeout (90 seconds) instead and after it expired, the boot process is stuck forever because no fallback passphrase entry is offered.  Surfing through the web, there are examples where `keyfile-timeout` is claimed to be working as expected, all of them use true key file on some device (aka `/...:/...` or `/...:UUID=...` syntax) though.

**Steps to reproduce the problem**

Put something similar to `crypttab` for `initramfs`:

```
luks-xxx /dev/disk/by-id/luks-xxx /dev/disk/by-id/key-storage luks,header=/.../luks-xxx.header,keyfile-offset=1024,keyfile-size=1024,keyfile-timeout=5,timeout=0,password-echo=no
```

Have 2 key slots in LUKS2 header `/.../luks-xxx.header`: passphrase and key file that was written to `/dev/disk/by-id/key-storage`.  Try to boot with this setup, while `/dev/disk/by-id/key-storage` being unplugged.

**Comment by Alexander-Shukaev** [comment]
Tagging potentially related stuff: #12194, #13004, #13615.

**Comment by mrc0mmand** [comment]
Local reproducer (with `systemd 250 (250-292-g5f5131c)`):

```
# dd if=/dev/zero of=/crypt.img bs=1M count=32
# echo hello >/crypt.keyfile
# cryptsetup luksFormat --header /crypt.header --key-file /crypt.keyfile /crypt.img
## Add a passphrase to the next key slot
# cryptsetup luksAddKey --key-file /crypt.keyfile /crypt.header
<passphrase>
# echo "test /crypt.img /dev/disk/by-id/nonexistent-device luks,header=/crypt.header,keyfile-timeout=5" >/etc/crypttab
# systemctl daemon-reload

## Check if the device can be opened using just the passphrase
# cryptsetup luksOpen --header /crypt.header /crypt.img test
Enter passphrase for /crypt.img: 
# ls -l /dev/mapper/test 
lrwxrwxrwx 1 root root 7 Jan 12 17:31 /dev/mapper/test -> ../dm-0
# cryptsetup luksClose test

# timeout 20s systemctl start systemd-cryptsetup@test
# echo $?
124 (timeout)
```

As described above, the `keyfile-timeout=` is apparently applied only when the key file is defined using the *external device* syntax (`<path>:<device spec>`). When the device itself is used as a key file, the default device timeout applies.

**Comment by yan12125** [comment]
I figured out a possible way to implement this, and I hope to discuss the approach before submitting a pull request. My commit https://github.com/yan12125/systemd/commit/f3c1ff517378ebd99affe786c3a69205022f78ea involves two changes:

* Use Wants= instead of Requires= for the keyfile device if keyfile-timeout is defined. This is necessary to make cryptsetup run when the device unit fails (e.g., still not present after timeout)
* Create a drop-in file to specify the timeout

Is it a good idea?

**Comment by poettering** [comment]
sure, implementing `keyfile-timeout=` also if raw devices are specified certainly makes sense.

**Comment by poettering** [comment]
(i mean, it's already implemented for the external device syntax, so implementing it otherwise just means copying the concept for that case)

**Comment by yan12125** [comment]
Thanks! Let me check out contribution guidelines first.
