### ISSUE TITLE
systemd-logind croaks if suspend.target fails

### ISSUE THREAD

**Issue by NeKJ** [systemd/systemd#21991]
**systemd version the issue has been seen with**
 > 250

**Used distribution**
> Arch Linux

**Linux kernel version used** (`uname -a`)
> `Linux xxxx 5.10.89-1-lts #1 SMP Sun, 02 Jan 2022 19:43:44 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
> Intel x86_64

**Expected behaviour you didn't see**
System suspends and resumes

**Unexpected behaviour you saw**
System does not suspend but instead becomes frozen

**Steps to reproduce the problem**
create a symbolic link inside `/etc/systemd/system/systemd-suspend.service.requires`, that points to a file path that does not exist e.g.:
`sudo ln -s /usr/lib/systemd/system/nonexisting.service /etc/systemd/system/systemd-suspend.service.requires/nonexisting.service`
execute `sudo systemctl daemon-reload`
execute `sudo systemctl suspend`

**Additional program output to the terminal or log subsystem illustrating the issue**

In the journal log there is this relevant entry:
```
Jan 03 22:46:27 nekhome systemd-logind[4507]: Error during inhibitor-delayed operation (already returned success to client): Unit nonexisting.service not found.
```

**Comments:
I happened upon this issue when I uninstalled an nvidia proprietary driver which had some systemd services, that have a `requires=suspend.target` that the user can `enable` which run at suspend/resume targets. However, upon removing the whole driver package, the symbolic links, that were manually created by "enable"ing those services, remain in the filesystem under `/etc/systemd/system/systemd-suspend.service.requires`, which they should'nt.
After that, when systemd tries to perform a suspend, it hangs because the links are broken.

I understand that this is partly the fault of the package removal, which should clean up after itself. However, once this is done, there is no easy way to find out what the fault is, because systemd does not do any kind of check whethere there are broken links by itself, and there is not a way to list all the requires/wants dependencies in such a way that will reveal if any requires/wants dependency is broken and does not exist. So it doesn't give any help on what got wrong to the user/administrator in order to fix this.

I spend hours on this to pinpoint the issue, I couldn't find the link at all, I had to do a brute force file search. This in my opinion should be handled by systemd in a more informative way:

1. check the **complete** depedency tree for non-existent files, such as broken symb. links or files that are actually referenced but missing and **inform the user** if there are found any, where they are exactly and which unit/target/whaterver is referencing them. Maybe, even have this be done automatically at some point? Currently, there is no way to do this kind of search, AFAIK.
2. `systemd suspend`, should not hang if a dependency file does not exist or is a broken symbolic link. It should instead, just log the issue, ignore it (maybe remove it too?) and then continue on with the rest of the suspension process unaffected.

**Comment by keszybz** [comment]
A "broken" symbolic link is not the problem. Links in `.wants`/`.requires` do not have to point to a file, only the target name counts.

Essentially, you are adding a Requires=foo dependency to shutdown.target, and foo cannot be started. That's a bit unfortunate, but it fits the overall model.

The obvious fix that should be done regardless of any changes in systemd is to change those Requires dependencies to Wants. This is recommended in general, and for a unit like `systemd-suspend.service` that should never fail even more so.

**Comment by NeKJ** [comment]
OK it makes sense. However, I could not infer *why* the system has hanged without any way of recovery by reading the logs.  If `systemd-suspend` is going to hang my entire system the admin needs to know it and should be able to know exactly when and what went wrong.

The only way that I managed to fix the issue was to blindly search my  whole filesystem for the 'nvidia-suspend' file, and then found out that it was a symbolic link, which was broken. This is how I inferred that systemd is 'require'ing this unit which does no longer exists.

I am pointing out, that if I want to verify that the whole systemd dependecy tree is sane/OK and every required unit is in place I have a way to do that.

for instance I tried the following command:
`systemctl list-dependencies --all suspend.target` and the output actually listed the tourblesome `nvidia-suspend` unit which was in fact missing. However the listing didn't verify the existence of the unit files, which I think it should have, so I could immediately know that there is a "broken" dependency.

In my opinion, there should be some way of verifying the whole dependency graph of systemd, with every unit listed **and** checked if it exists, is readable and if they are syntactically correct. I think these are the most basic checks that should be mandatory, basic but very important. And if there is any issue with a unit, inform the admin with as much information as possible. For instance, if a dependent unit is missing, it should mark the target/unit as failed or broken, with red font and it should print out where this dependency is defined (e.g., a file/link exists in the xxx.requires/xxx.wants, or a  Wants=xxx line exists in the xxx2 Unit with filepath xxx/xxx/xxx)

**Comment by keszybz** [comment]
systemd-analyze verify might be what you are looking for:
```console
$ systemd-analyze verify systemd-suspend.service       
systemd-suspend.service: Failed to create systemd-suspend.service/start: Unit missing.service not found.
```

**Comment by bluca** [comment]
> A "broken" symbolic link is not the problem. Links in `.wants`/`.requires` do not have to point to a file, only the target name counts.
> 
> Essentially, you are adding a Requires=foo dependency to shutdown.target, and foo cannot be started. That's a bit unfortunate, but it fits the overall model.
> 
> The obvious fix that should be done regardless of any changes in systemd is to change those Requires dependencies to Wants. This is recommended in general, and for a unit like `systemd-suspend.service` that should never fail even more so.

Paging @aaronp24 - Aaron, any chance we could please get `nvidia-suspend.service`, `nvidia-hibernate.service` and `nvidia-resume.service` updated to use `WantedBy=` instead of `RequiredBy=` in a future nvidia-driver version?

Also it would be good to update the instructions in the README (section `21C`), after it says to enable units with `systemctl enable`, to also recommend disabling them with `systemctl disable` when the drivers are uninstalled. Thanks!

**Comment by aaronp24** [comment]
Hmm, that's an interesting problem.

Modern versions of the installer [automatically enable](https://github.com/NVIDIA/nvidia-installer/blob/f959b8b7b17c9b16bf6ef6d27c9345e3a0bdc5b0/files.c#L803) these services, so enabling them manually shouldn't be required anymore. Since the symlinks are registered in the install log, the installer will also automatically remove them as part of its uninstall process. The README [no longer recommends](https://download.nvidia.com/XFree86/Linux-x86_64/470.63.01/README/powermanagement.html#SystemdConfigur74e29) manually enabling the units:
> These files are installed and enabled by nvidia-installer automatically if systemd is detected. Installation of systemd units can be disabled by specifying the **--no-systemd** installer option.

As for `WantedBy=` vs `RequiredBy=`, I used required because when video memory preservation is enabled, failing to start `nvidia-suspend.service` (e.g. because there's not enough space on the filesystem) will result in the system failing to suspend. It sounds like we really want a `RequiredByUnlessSomeoneDeletedTheTargetUnit=` ?

**Comment by bluca** [comment]
> Hmm, that's an interesting problem.
> 
> Modern versions of the installer [automatically enable](https://github.com/NVIDIA/nvidia-installer/blob/f959b8b7b17c9b16bf6ef6d27c9345e3a0bdc5b0/files.c#L803) these services, so enabling them manually shouldn't be required anymore. Since the symlinks are registered in the install log, the installer will also automatically remove them as part of its uninstall process. The README [no longer recommends](https://download.nvidia.com/XFree86/Linux-x86_64/470.63.01/README/powermanagement.html#SystemdConfigur74e29) manually enabling the units:

@NeKJ did you install the drivers/units manually, or through a distro package? If the latter, could you please report to the distro the issue of not disabling the units before removal?

> > These files are installed and enabled by nvidia-installer automatically if systemd is detected. Installation of systemd units can be disabled by specifying the **--no-systemd** installer option.
> 
> As for `WantedBy=` vs `RequiredBy=`, I used required because when video memory preservation is enabled, failing to start `nvidia-suspend.service` (e.g. because there's not enough space on the filesystem) will result in the system failing to suspend. It sounds like we really want a `RequiredByUnlessSomeoneDeletedTheTargetUnit=` ?

According to the report here, the symptom as thing stands is that the system freezes, which is not great. In the case you mention, what happens to the system? Is suspending aborted and the system left in a usable state, or is it similarly frozen/unusable and requires powercycling?

**Comment by bluca** [comment]
If the system freezes when those fails, then the current setup is probably fine, and this should be treated as a packaging bug for the distro used by the reporter. @keszybz wdyt?

**Comment by aaronp24** [comment]
I'm curious why the system freezes. Shouldn't the failure to activate `nvidia-suspend.service` propagate back to whoever issued the request to suspend?

I just tried on my test system by making `/usr/bin/nvidia-sleep.sh` fail immediately and `systemctl suspend` just fails as expected:
```
# systemctl suspend
Jan 04 11:51:53 [...] systemd[1]: Reached target Sleep.
Jan 04 11:51:53 [...] systemd[1]: Starting NVIDIA system suspend actions...
Jan 04 11:51:53 [...] suspend[1681]: nvidia-suspend.service
Jan 04 11:51:53 [...] logger[1681]: <13>Jan  4 11:51:53 suspend: nvidia-suspend.service
Jan 04 11:51:53 [...] systemd[1]: nvidia-suspend.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 11:51:53 [...] systemd[1]: nvidia-suspend.service: Failed with result 'exit-code'.
Jan 04 11:51:53 [...] systemd[1]: Failed to start NVIDIA system suspend actions.
Jan 04 11:51:53 [...] systemd[1]: Dependency failed for System Suspend.
Jan 04 11:51:53 [...] audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=nvidia-suspend comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan 04 11:51:53 [...] systemd[1]: Dependency failed for Suspend.
Jan 04 11:51:53 [...] systemd[1]: suspend.target: Job suspend.target/start failed with result 'dependency'.
Jan 04 11:51:53 [...] systemd[1]: systemd-suspend.service: Job systemd-suspend.service/start failed with result 'dependency'.
```
If I modify the units to use `WantedBy=` rather than `RequiredBy=`, then it proceeds to kernel suspend, which fails as expected and the system immediately resumes:
```
Jan 04 11:55:24 [...] kernel: Freezing user space processes ... (elapsed 0.001 seconds) done.
Jan 04 11:55:24 [...] kernel: OOM killer disabled.
Jan 04 11:55:24 [...] kernel: Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
Jan 04 11:55:24 [...] kernel: printk: Suspending console(s) (use no_console_suspend to debug)
Jan 04 11:55:24 [...] kernel: serial 00:03: disabled
Jan 04 11:55:24 [...] kernel: e1000e: EEE TX LPI TIMER: 00000011
Jan 04 11:55:24 [...] kernel: sd 0:0:0:0: [sda] Synchronizing SCSI cache
Jan 04 11:55:24 [...] kernel: sd 0:0:0:0: [sda] Stopping disk
Jan 04 11:55:24 [...] kernel: NVRM: GPU 0000:05:00.0: PreserveVideoMemoryAllocations module parameter is set. System Power Management attempted without driver procfs suspend interface. Please refer to the 'Configuring Power Management Support' section in the driver README.
Jan 04 11:55:24 [...] kernel: PM: pci_pm_suspend(): nv_pmops_suspend+0x0/0x30 [nvidia] returns -5
Jan 04 11:55:24 [...] kernel: PM: dpm_run_callback(): pci_pm_suspend+0x0/0x160 returns -5
Jan 04 11:55:24 [...] kernel: nvidia 0000:05:00.0: PM: failed to suspend async: error -5
Jan 04 11:55:24 [...] kernel: PM: Some devices failed to suspend, or early wake event detected
Jan 04 11:55:24 [...] kernel: pci 0000:00:05.0: disabled boot interrupts on device [8086:2f28]
Jan 04 11:55:24 [...] kernel: usb usb7: root hub lost power or was reset
Jan 04 11:55:24 [...] kernel: usb usb8: root hub lost power or was reset
Jan 04 11:55:24 [...] kernel: sd 0:0:0:0: [sda] Starting disk
Jan 04 11:55:24 [...] kernel: serial 00:03: activated
Jan 04 11:55:24 [...] kernel: OOM killer enabled.
Jan 04 11:55:24 [...] kernel: Restarting tasks ... done.
Jan 04 11:55:24 [...] kernel: PM: suspend exit
Jan 04 11:55:24 [...] systemd-sleep[1868]: Failed to put system to sleep. System resumed again: Input/output error
Jan 04 11:55:24 [...] [2003]: /usr/lib/systemd/system-sleep/nvidia failed with exit status 1.
Jan 04 11:55:24 [...] systemd[1]: systemd-suspend.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 11:55:24 [...] systemd[1]: systemd-suspend.service: Failed with result 'exit-code'.
Jan 04 11:55:24 [...] systemd[1]: Failed to start System Suspend.
Jan 04 11:55:24 [...] systemd[1]: Dependency failed for Suspend.
Jan 04 11:55:24 [...] systemd[1]: suspend.target: Job suspend.target/start failed with result 'dependency'.
```
I don't think the system freezing is expected here, it's supposed to be resuming immediately.

**Comment by bluca** [comment]
interesting, which systemd version/distro are you on?

**Comment by aaronp24** [comment]
Arch Linux, systemd 250-4.

**Comment by keszybz** [comment]
In general, adding Requires on units from a different source is iffy. It makes the system more fragile. We probably should recommend Wants over Requires even more strongly than we do now.

Also, you can't really rely on all cleanup operations being done correctly when package is removed. It is just too common for package removal transactions to be interrupted, or for people to remove things by hand, including dependencies and such. So packaging should be done in a way that degrades gracefully even if some components are incomplete.

> As for `WantedBy=` vs `RequiredBy=`, I used required because when video memory preservation is enabled, failing to start `nvidia-suspend.service` (e.g. because there's not enough space on the filesystem) will result in the system failing to suspend. It sounds like we really want a `RequiredByUnlessSomeoneDeletedTheTargetUnit=` ?

Right. So this sounds like WantedBy is the appropriate choice. RequiredBy would be only appropriate if it made no sense to try suspend without `nvidia-suspend.service`, but is sounds like it's still possible that the suspend would succeed. (For example, let's say that you have a hardware failure and have replaced the nvidia card by something else… No reason to forbid suspend even if the nvidia-suspend.service/start job cannot succeed).

--

> System does not suspend but instead becomes frozen

This shouldn't happen. If some part of the suspend transaction fails, the system should just return to status quo ante.
I tried this on my system, and `systemd-logind.service` goes down, taking `gdm.service` and the graphical session with it. So we have another bug here.

**Comment by keszybz** [comment]
```
Jan 02 21:03:56 krowka systemd-logind[616]: Lid closed.
Jan 02 21:03:56 krowka systemd-logind[616]: Suspending...
Jan 03 08:58:02 krowka systemd-logind[616]: Lid opened.
Jan 03 08:58:03 krowka systemd-logind[616]: Operation 'sleep' finished.
...
Jan 04 20:59:33 krowka systemd-logind[616]: Error during inhibitor-delayed operation (already returned success to client): Unit missing.service not found.
Jan 04 20:59:36 krowka systemd[1]: systemd-logind.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 20:59:36 krowka systemd[1]: systemd-logind.service: Failed with result 'exit-code'.
Jan 04 20:59:36 krowka systemd[1]: systemd-logind.service: Consumed 12.039s CPU time.
Jan 04 20:59:36 krowka systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 1.
Jan 04 20:59:36 krowka systemd[1]: Stopped systemd-logind.service.
Jan 04 20:59:36 krowka systemd[1]: systemd-logind.service: Consumed 12.039s CPU time.
```
We log about lid events nice, and we should do the same when a user requests suspend like I did over dbus. This would make it easier to understand why things happen.

**Comment by aaronp24** [comment]
The nvidia-suspend service is written to trivially succeed if none of the NVIDIA driver stuff is loaded. So the only reason it should fail (aside from configuration issues like being uninstalled but still enabled...) is if it's actually needed and didn't work for some reason.

That said, I'll file an internal bug to make the change to `WantedBy=`. While I still disagree that that's the right dependency here, proceeding to system suspend and having it fail at a lower level is supposed to still work so the change shouldn't be a big risk.

I filed NVIDIA internal bug number 3487781 to track this change.

**Comment by keszybz** [comment]
Thanks! I'll retitle this bug to match the scope in logind.

**Comment by NeKJ** [comment]
Great work! Thanks to all for such a quick collaboration and for resolving this.

**Comment by bluca** [comment]
> Great work! Thanks to all for such a quick collaboration and for resolving this.

@NeKJ have you reported this to your distro maintainer? Package removal needs to clean up these in normal circumstances
