### ISSUE TITLE
systemd-boot boots the oldest kernel with a glob in the default version

### ISSUE THREAD

**Issue by gentoo-root** [systemd/systemd#22004]
**systemd version the issue has been seen with**

systemd 250

**Used distribution**

Gentoo

**Linux kernel version used** (`uname -a`)

`5.15.12-gentoo #1 SMP PREEMPT`

**CPU architecture issue was seen on**

`x86_64`

**Expected behaviour you didn't see**

`man 5 loader.conf` says:

```
EXAMPLE
           # /boot/efi/loader/loader.conf
           timeout 0
           default 01234567890abcdef1234567890abdf0-*
           editor no

       The menu will not be shown by default (the menu can still be shown by
       pressing and holding a key during boot). One of the entries with files
       with a name starting with "01234567890abcdef1234567890abdf0-" will be
       selected by default. If more than one entry matches, the one with the
       highest priority will be selected (generally the one with the highest
       version number). The editor will be disabled, so it is not possible to
       alter the kernel command line.
```

Starting from commit 0c674ce5f24a6e52561ec6520e43a1ca45d90f01, this statement no longer holds:

> If more than one entry matches, the one with the highest priority will be selected (generally the one with the highest version number)

**Unexpected behaviour you saw**

The oldest kernel gets selected by default when using a glob like in the example above.

**Steps to reproduce the problem**

1. Use the /boot/efi/loader/loader.conf from the example above.
2. Create two loader entries: /boot/efi/loader/entries/01234567890abcdef1234567890abdf0-5.15.11.conf and /boot/efi/loader/entries/01234567890abcdef1234567890abdf0-5.15.12.conf. Adapt the contents to your system:
```
# /boot/efi/loader/entries/01234567890abcdef1234567890abdf0-5.15.11.conf
title Gentoo Linux
version 5.15.11
machine-id 01234567890abcdef1234567890abdf0
options root=/dev/sda2 rw
linux /01234567890abcdef1234567890abdf0/5.15.11-gentoo/linux
```
```
# /boot/efi/loader/entries/01234567890abcdef1234567890abdf0-5.15.12.conf
title Gentoo Linux
version 5.15.12
machine-id 01234567890abcdef1234567890abdf0
options root=/dev/sda2 rw
linux /01234567890abcdef1234567890abdf0/5.15.12-gentoo/linux
```
3. Reboot.
4. With systemd-boot 249.6, linux 5.15.12 is booted. With systemd-boot 250, linux 5.15.11 is booted.

**Additional program output to the terminal or log subsystem illustrating the issue**

Commit 0c674ce5f24a6e52561ec6520e43a1ca45d90f01 changed the behavior by replacing the descending loop with an ascending, making globs select the oldest kernel, instead of the latest. I guess, it's enough to convert the loop in `config_entry_find()` into a descending one.

**Comment by yuwata** [comment]
Fix is waiting in #22010.
