### ISSUE TITLE
 228.2 messed with services and now the system doesn't boot automatically

### ISSUE THREAD

**Issue by gazetorio** [systemd/systemd#2201]
My sources.list updated to 228.2 and now the boot system doesn't load sddm, forcing me to start from a terminal before a warning that fsck failed to check an encrypted mapper (ctrl+d bugged the #1 ctrl+alt+f1 screen) and only then type user and password.
1.Password of encryption.
2.Ctrl+alt+f2 before it bugs
3. login on a terminal with user and pass
4. sudo service start sddm (plus privilege password typing again)
5.user and pass for the DE
6.finally login and now I can sudo service network-manager start (with privilege typing pass again) to browse a broken firefox which delays in 2-5 seconds to show context, but chromium is fine

That was all after updating systemd. Tried to reinstall to a previous version and it showed:
"dpkg: 'can't delete old '/etc/X11/xinit xinitrc.d not empty
udev wreckes systemdb (<<224-2) and it's installed
xserver-xorg-core 1.16.3-2 wrewckes systemd (<<226-4~) and it's installed

What can I do? on the freenode channel they said it's a solution rather than to wait a new version to solve it.

**Comment by zonque** [comment]
Doesn't look like an upstream issue to me. Did you report this downstream at your distribution?

**Comment by poettering** [comment]
Please report this to your distribution, thank you!
