### ISSUE TITLE
systemd unit depending on a dbus service (re)start order isn't correct when dbus service exists in multiple targets being isolated.

### ISSUE THREAD

**Issue by jlinton** [systemd/systemd#22022]
**systemd version the issue has been seen with**
 >248 (originally during F35 release cycle)

**Used distribution**
 >Fedora 35

**Linux kernel version used** (`uname -a`)

 > `5.14.10`

**CPU architecture issue was seen on**
 > arm64/amd64

**Expected behaviour you didn't see**
 > SDDM isn't started until systemd-logind is fully up

**Unexpected behaviour you saw**
 > During systemctl isolate graphical.target from multi-user.target, what appears to happen Is that all the services in multiuser are (starting) shutdown but aren't fully stopped before systemd starts to resolve dependencies for graphical.target and start services there. So in this case logind appears to be quitting but is still responding on dbus sufficiently that it appears to be up. Then sddm is started and attempts to connect to logind, but it is now not running despite having an explicit dependency. The workaround for F35 was adding a delay loop waiting a few seconds for a logind/seat to appear before automatically falling back to starting a seat. (this is all a bit fuzzy because I was going to go after the bug myself, but I've not found time in the past couple of months for it).

**Steps to reproduce the problem**
 > IIRC, it is possible to reproduce/see this behavior simply by using ps to note when systemd-logind and sddm start. Something along the lines of: systemctl disable gdm.service;systemctl enable sddm.service; then: systemctl isolate multi-user.target; systemctl isolate graphical.target. while in another window `ps aux |grep [logind|sddm]` and note that sddm is started then logind goes away and then is restarted. 

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
not following. "systemctl isolate" will shut down only units that *aren't* also dependencies of the specified target unit. Hence switch with it from multi-user.target to graphical.target shouldn't shut down logind at all, since that is required by either (already because graphical.target is a superset of multi-user.target).

Figure out whyt logind.service is shutdown if you do this. Most likely smething else fucked up its deps in some way. Turn on debug logging via "systemd-analyze log-level debug" before doing the isolation, and see the logs.

**Comment by jlinton** [comment]
Ok, let me give that a try.

**Comment by jlinton** [comment]
Ok, I'm looking at this again, and I see:

Nov 17 14:11:13 rpi4-f36 systemd[1]: systemd-logind.service: D-Bus name org.freedesktop.login1 now not owned by anyone.

which seems to be the cause of logind stopping. Which from starting at the log for the past couple hours appears to be because multi-user.target has been held back long enough that graphical.target has stopped?

I'm going to try and attach the logs/analyze dump.

**Comment by jlinton** [comment]
[debug_restart3.txt](https://github.com/systemd/systemd/files/10035745/debug_restart3.txt)
[systemd_analyze_dump.txt](https://github.com/systemd/systemd/files/10035749/systemd_analyze_dump.txt)

**Comment by piotr-dobrogost** [comment]
@poettering Could you please take a look at the logs posted by jlinton?

**Comment by poettering** [comment]
So this is actually a bug in dbus-broker. Fix is in https://github.com/bus1/dbus-broker/pull/317

**Comment by poettering** [comment]
So, actually this was fixed by #26388. Closing.
