### ISSUE TITLE
"udevadm test-builtin net_setup_link /sys/class/net/ens3" has two error messages.

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#22035]
**systemd version the issue has been seen with**
 > 
systemd-249.4-2.fc35.x86_64

**Used distribution**
 > fedora35

**Linux kernel version used** (`uname -a`)

 > Linux fedora 5.14.10-300.fc35.x86_64 #1 SMP Thu Oct 7 20:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 >  Before this PR https://github.com/systemd/systemd/pull/16968/commits/e0e789c1e97e2cdf1cafe0c6b7d7e43fa054f151
there is no error message when udevadm test-builtin net_setup_link /sys/class/net/ens3
![image](https://user-images.githubusercontent.com/56221695/148475185-24382ba6-0237-4c18-984a-70057f944b8e.png)

**Unexpected behaviour you saw**
 > But now there are two error messages here, I want to know if there is a bug here. Although the code has been refactored by https://github.com/systemd/systemd/commit/613701a4e88b3fbf9d0f7901fea62ed0016d8862 in v250. By the way, the manual about "OriginalName=" may probably be revised after https://github.com/systemd/systemd/pull/16968/commits/f57673025680fdca0c200e7ca7a37fed943d2b49 .
![image](https://user-images.githubusercontent.com/56221695/148474860-f2a0931a-c40b-4ad1-9216-c2d0a7f8d426.png)

**Steps to reproduce the problem**
 >  udevadm test-builtin net_setup_link /sys/class/net/ens3

**Comment by yuwata** [comment]
Already fixed by 7ce05a8d6631b2e99fb101bd639838c5ce8f60a7.
