### ISSUE TITLE
[Request/Future] Non-Admins who are on systems with no TTYs can't start new instances of Display Servers like Weston

### ISSUE THREAD

**Issue by n3rdopolis** [systemd/systemd#22036]
Lets say it's the future, and we have distros shipping kernels compiled without CONFIG_VT=y. And we have a user who is not an administrator, who would like to start a new instance of Weston.

Before, the user would have been able to CTRL+ALT+F2, login, and then run Weston.

If the user was a local admin, they could run the command
`systemd-run  --setenv=XDG_SEAT=$XDG_SEAT -p PAMName=user -p User=$LOGNAME "weston"`
but they are denied in doing so since they don't have admin rights.

Perhaps a property in `systemd-run` or something?

**Comment by poettering** [comment]
I am not sure I follow? Something needs to give users the privs to access the screen. Typically that's a display manager or a TTY session, that cause a logind session to be created.

Are you suggesting that unprivileged users should be able to allocate sessions without a display manager? I am not sure why that'd be desirable?

I get the sense you should be using a display manager like gdm, but then make it not manage seat0 until it gets told so via dbus. But the that'd be a thing to implement in gdm, not in systemd.

Hence, not sure what systemd is supposed to do here?

**Comment by n3rdopolis** [comment]
If making it possible to start a new logind session through a new `systemd-run` property or option, or through a custom systemd user service is not possible then I guess this should be closed.

**Comment by n3rdopolis** [comment]
OK, I tried something, I have a different plan now, and yeah, it does not involve needs for changes to systemd. Sorry about the spam
