### ISSUE TITLE
Check/Remove an obsolete Wiki link from README

### ISSUE THREAD

**Issue by peter-lyons-kehl** [systemd/systemd#22049]
https://github.com/systemd/systemd (`README.md`) reads 'Assorted, older.. in the systemd Wiki' and it links to a broken link https://www.freedesktop.org/wiki/Software/systemd.

https://www.freedesktop.org/wiki/Software mentions 'systemd' only once, and that links back to https://github.com/systemd. Hence, the above wiki either doesn't exist anymore, or is hidden/at a different url.

Please confirm if systemd wiki page still exists, and where. Either way, I'll happily provide a PR (to update the link, or to remove that doc line).

**Comment by mrc0mmand** [comment]
Looks like this was some kind of an intermittent issue, since https://www.freedesktop.org/wiki/Software/systemd/ works for me.

@peter-kehl can you confirm if this is still an issue for you?

**Comment by keszybz** [comment]
I fixed the icon on that page now…
Must have been some transient issue with the fd.o. Let's close.
