### ISSUE TITLE
lid close event will still be handled after inhibitor lock has ended

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#22052]
**systemd version the issue has been seen with**
 > 250

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux gtbook 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > lid close event is ignored if occurred during an inhibitor lock is on, i.e. it will never be handled, even after the lock has ended 

**Unexpected behaviour you saw**
 > lid close event is handled after the lock has ended

**Steps to reproduce the problem**
 > run e.g. `systemd-inhibit --what=handle-lid-switch sleep 5`, close the lid right after the command execution, wait until the lock ends(, open the lid and check log)

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Jan 08 18:10:39 gtbook sudo[79118]:      tom : TTY=pts/1 ; PWD=/home/tom ; USER=root ; COMMAND=/usr/bin/systemd-inhibit --what=handle-lid-switch sleep 5
Jan 08 18:10:39 gtbook sudo[79118]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Jan 08 18:10:41 gtbook systemd-logind[404]: Lid closed.
Jan 08 18:10:44 gtbook sudo[79118]: pam_unix(sudo:session): session closed for user root
Jan 08 18:10:44 gtbook systemd-logind[404]: Suspending...
Jan 08 18:10:44 gtbook systemd[1]: Reached target Sleep.
Jan 08 18:10:44 gtbook systemd[1]: Starting System Suspend...
Jan 08 18:10:44 gtbook systemd-sleep[79121]: Entering sleep state 'suspend'...
Jan 08 18:10:44 gtbook kernel: PM: suspend entry (deep)
Jan 08 18:10:44 gtbook kernel: Filesystems sync: 0.020 seconds
```

**Comment by poettering** [comment]
Not following? the lid input device propagates a state, not a singular event. (i.e. the input layer calls this "switch" as opposed to "key"). And we model it like that: a suspend will suspend if the lid closed, agressively – only while a lock is taken to block that we'll not do so, but once you remove it, we'll immediately suspend.

This is by design, to make things robust: the privilege to acquire an inhibitor lock gives you the privlege to keep the system running, but once you lose/give up that lock the system will move to the designed state.

Hence, this is really by design of inhibitor locks.

(this is the same for power plug state or exernal display plug state btw, if that's configured to inhibit suspending: the state matters, not the singular event)

(And yes this also means: if you manage to resume a system while the lid is switched and don#t take a lock, we'll suspend again pretty soon)

**Comment by tomty89** [comment]
So *two different modes of locks* just suddenly doesn't apply for lid switch?

I do admit that lid switch is a bit different from keypress since one can see it in a way like "closed -> kept being pressed" (not exactly sure if that's what you mean by state since you sounded more like you are not aware of block mode lock than that). I am unsure whether it has to be the way / is a more robust way to see it though.

While it can remain being a state, it doesn't necessarily prevent the action to be triggered by a state change instead of like a state monitoring / polling.

**Comment by poettering** [comment]
> So _two different modes of locks_ just suddenly doesn't apply for lid switch?

Not following? Why wouldn't they?

> I do admit that lid switch is a bit different from keypress since one can see it in a way like "closed -> kept being pressed" (not exactly sure if that's what you mean by state since you sounded more like you are not aware of block mode lock than that). I am unsure whether it has to be the way / is a more robust way to see it though.

It's not that *we* see it that way. The kernel's input layer makes that distinction: there are "keys", that know key press repetition and so on, i.e. one initial key press, possibly followed by more if key is held down, eventually followed by key release event. "Switches" are different: the are on, or off, continously, and there are no repetition events generated or anything like that. The lid switch as one of those "switches".

And this makes a ton of sense if you ask me.

**Comment by tomty89** [comment]
> Why wouldn't they?

Ugh what? That's like exactly the reason I filed this: block mode lock are showing exactly the same behavior as delay mode lock for lid switch; both types of locks only delay the suspend "command" signalled with the lid swtich during the lock is on

Or did you intend to say "Why should they?" Like "due to the nature of the switch yes they behave identically at the end"

> and there are no repetition events generated or anything like that

Doesn't that mean it should be possible to make block mode lock work expectedly for lid switch? Unless logind keeps polling of the state instead a state change.

**Comment by poettering** [comment]
> > Why wouldn't they?
> 
> Ugh what? That's like exactly the reason I filed this: block mode lock are showing exactly the same behavior as delay mode lock for lid switch; both types of locks only delay the suspend "command" signalled with the lid swtich during the lock is on

Nope. That's not the case.

Blocking locks will *stop* any operations of the selected kind to happen *while* *the* *lock* *is* *taken*.

Delaying locks will *delay* any operations of the selected kind a bit *while* *the* *lock* *is* *taken*.

While you have a blocking lock on the lid switch it will not have any effect. While you have a delay lock it will have, but you'll get some time to react to it first, but if you don't your lock will be ignored eventually.

> > and there are no repetition events generated or anything like that
> 
> Doesn't that mean it should be possible to make block mode lock work expectedly for lid switch? Unless logind keeps polling on the state instead of a state change.

As long as you maintain the block lock the lid switch won't be operated on. Once you give it up, it will be.

**Comment by tomty89** [comment]
> Blocking locks will stop any operations of the selected kind to happen while the lock is taken.

Let's clarify this first: what *exactly* do you mean by "stop" here?

> While you have a blocking lock on the lid switch it will not have any effect.

"Will not" as in the suspension will be queued/delayed (like will not "for now"), or as in lid closing actions / state changes that **occurred during the lock is on** will not ever be processed?

I'm NOT expecting the lock to make the lid switch ignored permanently (obviously that won't be a lock anymore). If you look at my attached log more carefully, I closed the lid while the lock is still on, but once the lock is gone, suspension occurs **even when I didn't open and close the lid again**.

The sudo session lines are **relevant** btw. I used sudo because the lines can indicate that the closing of the lid happened before the lock is gone.

**Comment by tomty89** [comment]
Ah never mind. Apparently the delay lock doesn't work as how I thought it does. I missed the `InhibitDelayMaxSec` part.

I guess what I'm really after is a convenient / "runtime" way to set `HandleLidSwitch=` et. al. to `ignore`, like without needing to edit a file and restart logind.

**Comment by poettering** [comment]
> > Blocking locks will stop any operations of the selected kind to happen while the lock is taken.
> 
> Let's clarify this first: what _exactly_ do you mean by "stop" here?

Stop happening? The lid state is ignored *while* the lock is taken, but not before or after.

> > While you have a blocking lock on the lid switch it will not have any effect.
> 
> "Will not" as in the suspension will be queued/delayed (like will not "for now"), or as in lid closing actions / state changes that **occurred during the lock is on** will not ever be processed?

We will not act on lid state while the lock is taken. Once you release it or before you took it we will.

> I'm NOT expecting the lock to make the lid switch ignored permanently (obviously that won't be a lock anymore). If you look at my attached log more carefully, I closed the lid while the lock is still on, but once the lock is gone, suspension occurs **even when I didn't open and close the lid again**.

Yes exactly, once the lock is release we return to normal behaviour and act on the lid state then in effect.

> The sudo session lines are **relevant** btw. I used sudo because the lines can indicate that the closing of the lid happened before the lock is gone.

Not sure I follow.
