### ISSUE TITLE
systemctl does not talk to polkit until the user has logged in once

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#22055]
**systemd version the issue has been seen with**
 > 250

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux archlinux 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemctl talks to polkit even if the user has only been lingering since the system was booted up

**Unexpected behaviour you saw**
 > systemctl fails with `Interactive authentication required` until the user "actually" (i.e. tty / ssh) logged in once (yet it doesn't matter whether a session remains existing)

**Steps to reproduce the problem**

> I have some x11vnc servers that attaches corresponding Xvfb X servers that are started with [user services et. al.](https://gist.github.com/tomty89/84f78aa6e34ed35addb029edef9793d9) They are available once the system is booted up becuase the user is set to linger. Since they do not make use of pam_systemd and so like tigervnc's vncserver, they are some sort of "session-less" environment (in addition to being "seat-less").
> 
> I don't have any real problem with them, but I notice that systemctl (without sudo) does not talk to polkit to authenticate for actions that require privilege, yet it only fails to to so until the user is logged in (once).
> 
> As I implied, it's not exactly a real problem to me since I use sudo for that anyway. However, I wonder if it hinted some potential security issue or so. Regardless, it should work anyway.
> 
> As far as I can see, even in the case in which it will fail, `systemctl` causes polkitd to be re-spawned if its service was stopped before the command. Also `udisksctl` in udisks2 works fine anyway.

**Additional program output to the terminal or log subsystem illustrating the issue**

> The following is a showcase of the weird behavior:

`(fresh boot)`
```
$ systemctl enable getty@tty6
Failed to enable unit: Interactive authentication required.

$ sudo systemctl enable getty@tty6
Created symlink /etc/systemd/system/getty.target.wants/getty@tty6.service → /usr/lib/systemd/system/getty@.service.

$ cat /etc/systemd/system/getty\@tty6.service.d/override.conf ; echo
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin tom --noclear - $TERM
Restart=no

$ grep -v '^$\|#' .bash_profile | head -n 1
[ "$XDG_VTNR" = 6 ] && exit
```
`(reboot)`
```
$ loginctl
No sessions.

$ systemctl status getty@tty6
○ getty@tty6.service - Getty on tty6
     Loaded: loaded (/usr/lib/systemd/system/getty@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/getty@tty6.service.d
             └─override.conf
     Active: inactive (dead) since Tue 2022-01-04 13:16:04 HKT; 27s ago
       Docs: man:agetty(8)
             man:systemd-getty-generator(8)
             http://0pointer.de/blog/projects/serial-console.html
    Process: 414 ExecStart=/sbin/agetty --autologin tom --noclear - $TERM (code=exited, status=0/SUCCESS)
   Main PID: 414 (code=exited, status=0/SUCCESS)
        CPU: 8ms

Jan 04 13:16:04 archlinux systemd[1]: Started Getty on tty6.
Jan 04 13:16:04 archlinux login[414]: pam_systemd_home(login:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Jan 04 13:16:04 archlinux login[414]: pam_unix(login:session): session opened for user tom(uid=1000) by (uid=0)
Jan 04 13:16:04 archlinux login[414]: pam_env(login:session): deprecated reading of user environment enabled
Jan 04 13:16:04 archlinux systemd[1]: getty@tty6.service: Deactivated successfully.

$ systemctl disable getty@tty6
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-unit-files ====
Authentication is required to manage system service or unit files.
Authenticating as: tom
Password: 
==== AUTHENTICATION COMPLETE ====
Removed /etc/systemd/system/getty.target.wants/getty@tty6.service.
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ====
Authentication is required to reload the systemd state.
Authenticating as: tom
Password: 
==== AUTHENTICATION COMPLETE ====
```

**Comment by poettering** [comment]
Hmm, you run per-user code outside of a logind user session? If so, you have no systemd instance for it, and no dbus bus instance, and no pk authentication agent will work hence. 

PK is not compatible with such setups really. (Neither is systemd really)

I don't think there's anything to fix here...

Once you have a session, then the dbus instance+systemd gets started, and you can have a PK agent hence, and all is good, but without that? doesn't really work...

**Comment by tomty89** [comment]
> or what am i missing?
lingering, maybe?

Besides, user services never runs inside a session anyway, although interactive operation might not exactly be expected from a process of one. Regardless, `udisksctl` works fine completely, and systemctl also works with the trick shown above (no session remains either)

The user manager can still be be up when there's no session remains, if that's what you mean by systemd instance (and dbus is there too).

The weird thing is, as shown in the above test, it only not work when there was never a *real* session spawned. (By real I mean, by checking the enumerated session ID, it seems that lingering from a fresh boot will cause a session to be created but also destroyed right away. I have wondered why that was necessary / how exactly it works too...

**Comment by ElijahLynn** [comment]
As an end user, I'm seeing `[system] Activation via systemd failed for unit 'Apr 05 10:12:29 archlinux sudo[6909]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.` in my logs and found this issue by trying to install the `systemd-homed` package on Arch and only found https://aur.archlinux.org/packages/systemd-homed-containers which linked to this repo as an upstream so I searched this issue queue for `"systemd-homed is not available"` and found this issue. 

I'm mainly looking to expunge this from my logs. Only reason I am posting here is because I am getting the same log message and maybe related?

**Comment by YHNdnzj** [comment]
> As an end user, I'm seeing `[system] Activation via systemd failed for unit 'Apr 05 10:12:29 archlinux sudo[6909]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.` in my logs and found this issue by trying to install the `systemd-homed` package on Arch and only found https://aur.archlinux.org/packages/systemd-homed-containers which linked to this repo as an upstream so I searched this issue queue for `"systemd-homed is not available"` and found this issue.
> 
> I'm mainly looking to expunge this from my logs. Only reason I am posting here is because I am getting the same log message and maybe related?

That's not related. If you don't need systemd-homed, please remove `pam_systemd_home.so` from your PAM stack.

Or, enable and start `systemd-homed.service`.

**Comment by poettering** [comment]
So, as I understand this is a setup where sessons are "faked" and no registered with logind. Such a scenario s not supported, because PK checks whether a user has a session before doing various interactive things. 

This is just a broken (as in: unsupported) setup. Hence closing.
