### ISSUE TITLE
System V Compatbility Shutdown/Reboot Commands Should Honor Inhibitors and Send PrepareForShutdown DBus Signal When Run As Root

### ISSUE THREAD

**Issue by JonnyWhatshisface** [systemd/systemd#22058]
**Description of Behavior**

System V compatibility shutdown/reboot/halt commands (ie via /usr/sbin/{shutdown,reboot}) do not exhibit the same behavior as a systemctl {reboot,halt} when run as root. 

Most notable is that inhibitors appear to be skipped and a PrepareForShutdown DBus signal is not emitted when immediate action via /usr/sbin/{reboot,shutdown,halt,poweroff} are executed. 

This behavior changes when using /usr/sbin/shutdown in a scheduled manner - i.e. /usr/sbin/shutdown -r +1 . In this case, delay inhibitors are honored and the DBus signal goes out, giving an inconsistent behavior in shutdown, reboot and poweroff operations between systemctl and the System V compatibility commands. 

**Example Test Case**
Install required python depedencies:

```
apt install libdbus-1-dev libglib2.0-dev python3-gi pip
pip3 install dbus-python
```

Use the following sample script:

```
#!/usr/bin/python3

import time, os, sys
import dbus
from gi.repository import GLib
from dbus.mainloop.glib import DBusGMainLoop

def handle_shutdown(*args):
    # Note: Default maximum inhibit delay time is 5 seconds.
    # This can be raised in /etc/systemd/login.conf by
    # setting InhibitDelayMaxSec .
    print("Inhibit the shutdown for 30 seconds...")
    time.sleep(30)
    print("Letting go of inhibit lock")
    os.close(inhibitor_fd)

DBusGMainLoop(set_as_default=True)
bus = dbus.SystemBus()

login = bus.get_object("org.freedesktop.login1", "/org/freedesktop/login1")
manager = dbus.Interface(login, dbus_interface='org.freedesktop.login1.Manager')
inhibitor = manager.Inhibit("shutdown", "Shutdown Handler", "Handle events on shutdown notification", "delay")

inhibitor_fd = inhibitor.take()

bus.add_signal_receiver(handle_shutdown, dbus_interface="org.freedesktop.login1.Manager", signal_name="PrepareForShutdown")

loop = GLib.MainLoop()
loop.run()

```

Run the above script. 

As root, issue a systemctl reboot command. The inhibitor is honored, the PrepareForShutdown signal is sent and the inhibitor actions the signal.

Repeat the test, this time issuing a /usr/sbin/reboot or /usr/sbin/halt command. The inhibitor will not be triggered and the system will immediately go down.

Again repeat the test, running /usr/sbin/shutdown -r +1 . After one minute, the inhibitor will be honored, the PrepareForShutdown signal is sent and the inhibitor actions the signal.

Expected behavior:

```
root@image:~# ./inhibitor.py &
[1] 64
root@image:~# systemctl reboot
Inhibit the shutdown for 30 seconds...
root@image:~# 
         Stopping Session 262 of User root...
[  OK  ] Removed slice Slice /system/getty.
[  OK  ] Removed slice Slice /system/modprobe.
[  OK  ] Stopped target Graphical Interface.
[  OK  ] Stopped target Multi-User System.
[  OK  ] Stopped target Login Prompts.
[  OK  ] Stopped target Host and Network Name Lookups.
[....]
```

**Describe the solution you'd like**
Legacy shutdown, halt and poweroff commands should be able to take advantage of the inhibitors, as well as the PepareForShutdown signal, even when run as root - as they are for systemctl reboot/halt commands. 

**Other References**
This is similar to https://github.com/systemd/systemd/issues/15239 

This looks to be due to logind_reboot() not being called in halt_main() if the reboot was executed by root.

https://github.com/systemd/systemd/blob/3989bdc1ad7cca4d75c06cdf601fea2cb37ba337/src/systemctl/systemctl-compat-halt.c#L156-L175

Bypassing the check and calling logind_reboot() yields the expected behavior. 

**The systemd version you checked that didn't have the feature you are asking for**
systemd 250 (250)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Comment by JonnyWhatshisface** [comment]
The reason for the behavior is when using systemctl to execute or schedule the reboot, it ultimately lands in start_special() which calls logind_reboot(), while using legacy commands simply sets the arg_action and lets the system drop to release_busses() . Thus, there is no check of inhibitors nor any DBus PrepareForShutdown signal when using the legacy commands.

While this looks to be by design, I don't believe utilizing the inhibitor capabilities of systemd should be limited to changing a decades long used set of commands to halt, reboot and poweroff the box.

It there is a desire to maintain a clear line between the two systems reboot behaviors, perhaps a better approach would be to introduce a configuration flag - SystemVLegacyShutdownBehavior={yes,no} - which would allow the users to choose to the current behavior of /usr/sbin/{shtdown,reboot,halt,poweroff} - to either behave in a legacy manner or to follow the systemd standard which would include honoring inhibitors and sending a PrepareForShutdown .

Would the configuration parameter fit better in logind.conf or system.conf ?

**Comment by tomty89** [comment]
Apparently not?
https://github.com/systemd/systemd/blob/04499a70fbff3f6b798028473f5c9234a53eaa2d/src/systemctl/systemctl-compat-halt.c#L147
https://github.com/systemd/systemd/blob/04499a70fbff3f6b798028473f5c9234a53eaa2d/src/systemctl/systemctl-compat-halt.c#L165

**Comment by JonnyWhatshisface** [comment]
halt_main() is only called when arg_action is ACTION_KEXEC .

**Comment by tomty89** [comment]
https://en.m.wikipedia.org/wiki/Switch_statement#Fallthrough

**Comment by JonnyWhatshisface** [comment]
Ack'd. Thank you, I actually was not aware of Fallthrough on switch statements. That means it is a bug elsewhere. 

Using legacy commands, the inhibitors are not honored and no PrepareForShutdown DBus signal is emitted. Updating issue accordingly.

**Comment by JonnyWhatshisface** [comment]
Here it is: 

https://github.com/systemd/systemd/blob/3989bdc1ad7cca4d75c06cdf601fea2cb37ba337/src/systemctl/systemctl-compat-halt.c#L156-L175

The issue is stemming from calling legacy System V commands as root.  

Calling halt_main() as root results in no call to logind_reboot() and I am suspecting somewhere down the line of this is where the PrepareForShutdown DBus signal would be emitted... 

Bypassing this check and calling logind_reboot() even when root results in the desired behavior, the shutdown delay inhibitor is honored and the PrepareForShutdown signal is emitted on the bus.

**Comment by tomty89** [comment]
It doesn't seem like inhibitor locks are supposed to have effect on root though:
https://www.freedesktop.org/wiki/Software/systemd/inhibit/

**Comment by JonnyWhatshisface** [comment]
I think that functionality should be discussed further, though today - systemctl issued halt/reboot/poweroff commands are indeed honoring them as expected. So the behavior should be the same across the two interfaces, while I believe the behavior of systemctl executed actions is the right and desired behavior. 

The inhibitors can be forcefully ignored via parameters if that is desired, so root will always be able to bypass them and reboot the box. However, there may be points in time where the desire is there to prevent the reboot even as root. Particularly in the case of highly regulated environments subject to strict auditing, and in environments of 100k+ servers where the inhibitors could also be leveraged to more effectively deliver system updates. 

I've confirmed that block inhibitors are definitely ignored by root and have zero effect, which would make sense. The delay inhibitor has the protection of InhibitDelayMaxSec and thus I believe the current behavior of systemctl honoring them is the correct and more useful approach.

**Comment by bluca** [comment]
They are with newer commands, see https://github.com/systemd/systemd/pull/18210 and https://github.com/systemd/systemd/pull/18316

**Comment by JonnyWhatshisface** [comment]
So perhaps a more appropriate patch would be to make honoring inhibitors as root an optional configurable parameter, for both systemctl and the legacy system v commands?

**Comment by bluca** [comment]
I don't think so, the legacy commands are legacy, we don't change their behaviour or it will break backward compatibility. And adding a new option is also unnecessary, if you can update your script to use a new option with the legacy command, then you can also update it to use the supported command instead.

**Comment by JonnyWhatshisface** [comment]
It's not always that simple. You're talking about needing to modify decades worth of scripts, API's, user scripts, provisioning scripts and etc in a 100k+ government regulated infrastructure, not to mention retrain every sys admin not to use "reboot" or "shutdown -r" .

That just isn't going to work. 

The code in place clearly shows that system v commands were intended to honor the inhibitors. Whether someone types "systemctl restart" or  "reboot" should be irrelevant. If the box is running systemd, then the features and functionality provided by systemd should be available even if running the old "commands." 

Otherwise, it feels like you're saying "reboot" and "shutdown" are deprecated in the eyes of systemd, despite being standardized across every unix platform.

**Comment by JonnyWhatshisface** [comment]
Additionally, what backward compatibility are you mentioning with regards to reboots? The biggest part of the system v compatibility is the init scripts and the handling of them as unit files. I'm unaware of what you mean by breaking backward compatibility by honoring inhibitors when using the legacy commands.

On that note, it's already broken by the fact that scheduled reboots (/usr/sbin/shutdown -r +1) follow the same code logic as executing it via systemctl...

**Comment by bluca** [comment]
You can't claim it both ways: either decades worth of infra scripts etc cannot be changed, and then adding a new option doesn't help since they won't be using it, or they can be changed to use a new option, which means they can also be changed to use the non-legacy commands if they want the new features.

Changing the behaviour unconditionally for legacy commands is a non-starter, as it's a backward compat breakage. If 'reboot' suddenly doesn't reboot anymore, people will get mad.

**Comment by JonnyWhatshisface** [comment]
I think either there is some confusion. 

Decades of infra scripts cannot be changed to go from calling /usr/sbin/reboot and /usr/sbin/shutdown -r now to calling systemctl restart and systemctl halt .

Changing a configuration parameter in system.conf or login.conf is easy. 

Changing the behavior to honor inhibitors won't cause the box not to reboot. As I said, a new option in system.conf or login.conf can be introduced - SystemVLegacyShutdownBehavior - which by default would keep things exactly as they are. When flipped to no, inhibitors would be honored as designed.

But again, it's already inconsistent in terms of behavior. 

Run the reproducer I have attached to the issue at the top.

**Comment by JonnyWhatshisface** [comment]
Patch in the works.

I'm hoping that the concepts I'm implementing will give comfort in ensuring the legacy behavior remains, with the option to be explicitly enabled to change the behavior. 

Patch details:

* New configuration parameter in login.conf - LegacyRootShutdown - When set to no, logind_reboot() will be called in halt_main() when executed by root. Defaults to yes, which maintains current behavior - may need a different name?

* Queries configuration parameter via dbus - if the parameter cannot be queried or dbus is not available, defaults yes (current standard legacy behavior). This looks to be an okay way to query the configuration parameter ?

* When set to no, --force will skip calling logind_reboot() and maintain current behavior

* When set to no, subsequently issuing another command with --force while already inhibited will skip the inhibitor and force the reboot

* Documentation updated accordingly

I believe this will give the most flexibility by maintaining the current functionality but giving an option to leverage inhibitors with the current legacy commands, as well as providing a failsafe to force the reboot/halt even when its already inhibited if the feature is enabled.

Note: This does not change the current behavior of blocking inhibitors which are ignored by root. This patch will aim solely to introduce new functionality when using legacy shutdown commands that must be explicitly enabled for those who wish to use it.

**Comment by lnussel** [comment]
You may want to take a look at https://github.com/systemd/systemd/pull/21838
I started to fix some of the inconsistencies but the rabbit hole is deep.

**Comment by JonnyWhatshisface** [comment]
Thanks. My patch will need to be refactored to account for the changes you've made in halt_main() , so I'll take a look and start working on that.

I'm hoping to have legal approval this upcoming week. I'm happy to help continue refactoring and cleaning up once I get through that hurdle.

**Comment by poettering** [comment]
Inhibitors do not exist on Sysv, hence the SysV compat commands don't support them. Use the new commands if you want the new stuff.

**Comment by JonnyWhatshisface** [comment]
This isn't feasible. I'm working in an infrastructure of 100k unix machines with decades worth of self-provisioning tools, updated mechanisms and self-service utilities that can't all be re-written to use "systemctl {reboot, halt}" etc. 

The inhibitors are a part of systemd in general. Using policy kit, non-root users can leverage the inhibitors. So why can't a flag be added to allow root users to leverage them?

**Comment by mbiebl** [comment]
couldn't you replace /sbin/shutdown with a shell wrapper calling `systemctl`?
That would about the same amount of work as setting a config parameter on those systems?

**Comment by JonnyWhatshisface** [comment]
No - I've had that discussion with stakeholders until we were all blue in the face. Shutdown wrappers are prohibited entirely, and that is true in most corporate environments with this size and type of regulation.

**Comment by mbiebl** [comment]
> No - I've had that discussion with stakeholders until we were all blue in the face. Shutdown wrappers are prohibited entirely, and that is true in most corporate environments with this size and type of regulation

Did they provide any solid reasoning for this?

**Comment by JonnyWhatshisface** [comment]
Because it's ugly and presents more issues than it needs to with upgrades etc. 

Why would we want to wrap the shutdown and reboot commands if we could simply flip a switch in the login.conf ? 

When you're working in environments of this size, they rely on what's in the product and what the vendor supports - as unfortunate as that may sound. Custom wrappers for /sbin/{shutdown,reboot,halt} and etc aren't anything senior managers are willing to entertain.

**Comment by lnussel** [comment]
The reason I got in touch with the shutdown logic was partially also motivated by the inhibitor inconsistency actually. My private use case is a rpi that does some regular sensor readings. The reading and processing may take a variable amount of seconds so makes sense to place an inhibitor to avoid rebooting in the middle. In that case it doesn't really matter whether eg some automatic OS update timer asks for reboot or someone logged in on the console. So IMHO it makes sense to enforce inhibitors on server side, no matter what the entry point is. As I've accidentally rebooted the machine at an inconvenient time as root I'd also argue that an interactive root should be denied unless asking for explicit override :-)

**Comment by JonnyWhatshisface** [comment]
@lnussel Thoughts on making it a configurable/optional setting? 

I don't personally feel shutdown/halt/power/reboot commands are really a component of "system v compatibility," when the biggest part of that compatibility is the ability to use traditional init scripts and the layer that converts them to unit files. My personal view is given we are using systemd, and not system v, I expect the features systemd offers to be available to me regardless of entry point for the shutdown/reboot/poweroff commands. 

However, I can see and respect the logic of those who want to preserve the expected traditional behavior - hence my thoughts that preserving the behavior as a default may be the right way to go and the ability to change that functionality via a configuration parameter gives everyone the best of both worlds. 

It's not the first time the concerns about inconsistency in behavior with regards to inhibitors when using various /sbin entry points for shutdown or reboot events has come up. 

I believe the approach I've proposed and written a patch for is a win/win for both viewpoints and introduces no risk to those who have not intentionally flipped the switch. 

Proper documentation would be the key.

**Comment by JonnyWhatshisface** [comment]
Disregard, I just saw your pull request was merged. Your merge fixed my issue.

Just one thing now: when using force, it should skip using logind_reboot and go straight to halting the system to prevent calling inhibitors.

**Comment by JonnyWhatshisface** [comment]
Issue was fixed in https://github.com/systemd/systemd/commit/adefc8789b63225662e50ceaa282f9553b5c64eb
