### ISSUE TITLE
skip TEST-02-UNITTESTS on ubuntu CIs??

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#22059]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Ubuntu/Debian

Since https://github.com/systemd/systemd/pull/22013 was merged, a couple of issues were spotted which cause the test to fail (under `autopkgtest`) and also might cause the test to give inaccurate results.

\# 1 As discussed in https://github.com/systemd/systemd/pull/22053 the test fails under `autopkgtest` (Ubuntu CI and possibly Debian soon). I'll copy my findings verbatim from the mentioned PR:

There are multiple things going "wrong":

1) `debuild` strips empty directories
2) `debuild` (or something along the way) doesn't like dangling symlinks

Now, the `install_subdir()` in meson explicitly ignores `.gitatrributes`, so the respective installed `test-fstab-generator/*.expected/*.requires/` directory ends up with only a dangling symlink. And it looks like `debuild` doesn't like dangling symlinks so it strips them as well, leading to `test-{01..11}*.expected/*.requires/` directories being empty and subsequently stripped too. All this ends up in the `systemd-tests*.deb` package, which is then used when running the integration tests.

The `systemd-tests` package then looks like this: 

```
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-01-dev-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-02-dhcp.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-03-dhcp6.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-04-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-05-nfs4.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-06-ipv4.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-07-ipv6.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-08-implicit-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-09-cifs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-10-iscsi.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-11-live.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.input
```

causing the test to fail, for obvious reasons.

So far I don't know enough about Debian packaging to propose what should be the next steps though...

\# 2 The symlinks are currently copied as files by meson

Meson already complains during `ninja install`:
```
...
Installing /home/fsumsal/repos/@systemd/systemd/test/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires/sysroot.mount to /home/fsumsal/repos/@systemd/systemd/test_install/usr/lib/syst
emd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires                                                                                                                  
Warning: trying to copy a symlink that points to a file. This will copy the file,                                                                                                                                
but this will be changed in a future version of Meson to copy the symlink as is. Please update your                                                                                                              
build definitions so that it will not break when the change happens.                                                                                                                                             
Installing /home/fsumsal/repos/@systemd/systemd/test/test-fstab-generator/test-16-tmpfs.expected/sysroot.mount to /home/fsumsal/repos/@systemd/systemd/test_install/usr/lib/systemd/tests/testdata/test-fstab-gen
erator/test-16-tmpfs.expected                                                                                                                                                                                    
Installing /home/fsumsal/repos/@systemd/systemd/test/test-fstab-generator/test-16-tmpfs.expected/initrd-root-fs.target.requires/sysroot.mount to /home/fsumsal/repos/@systemd/systemd/test_install/usr/lib/system
d/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-root-fs.target.requires                                                                                                                      
Warning: trying to copy a symlink that points to a file. This will copy the file,                                                                                                                                
but this will be changed in a future version of Meson to copy the symlink as is. Please update your                                                                                                              
build definitions so that it will not break when the change happens.                                                                                                                                             
Installing /home/fsumsal/repos/@systemd/systemd/test/test-fstab-generator/test-16-tmpfs.expected/initrd-usr-fs.target.requires/sysroot.mount to /home/fsumsal/repos/@systemd/systemd/test_install/usr/lib/systemd
/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-usr-fs.target.requires                                                                                                                        
Warning: trying to copy a symlink that points to a file. This will copy the file,                                                                                                                                
but this will be changed in a future version of Meson to copy the symlink as is. Please update your                                                                                                              
build definitions so that it will not break when the change happens.      
...
```

And the respective trees indeed differ:

source tree:
```
$ ls -lR test/test-fstab-generator/test-15-partuuid.expected/
test/test-fstab-generator/test-15-partuuid.expected/:
total 8
drwxrwxr-x. 1 fsumsal fsumsal  38 Jan  9 00:45 initrd-root-device.target.d
drwxrwxr-x. 1 fsumsal fsumsal  26 Jan  9 00:45 initrd-root-fs.target.requires
drwxrwxr-x. 1 fsumsal fsumsal  26 Jan  9 00:45 initrd-usr-fs.target.requires
-rw-rw-r--. 1 fsumsal fsumsal 434 Jan  9 00:45 sysroot.mount
-rw-rw-r--. 1 fsumsal fsumsal 648 Jan  9 00:45 systemd-fsck-root.service

test/test-fstab-generator/test-15-partuuid.expected/initrd-root-device.target.d:
total 4
-rw-rw-r--. 1 fsumsal fsumsal 236 Jan  9 00:45 50-root-device.conf

test/test-fstab-generator/test-15-partuuid.expected/initrd-root-fs.target.requires:
total 4
lrwxrwxrwx. 1 fsumsal fsumsal 16 Jan  9 00:45 sysroot.mount -> ../sysroot.mount

test/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires:
total 4
lrwxrwxrwx. 1 fsumsal fsumsal 16 Jan  9 00:45 sysroot.mount -> ../sysroot.mount
```

installed tree:
```
$ ls -lR test_install/usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/
test_install/usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/:
total 8
drwxr-xr-x. 1 fsumsal fsumsal  38 Jan  9 00:50 initrd-root-device.target.d
drwxr-xr-x. 1 fsumsal fsumsal  26 Jan  9 00:50 initrd-root-fs.target.requires
drwxr-xr-x. 1 fsumsal fsumsal  26 Jan  9 00:50 initrd-usr-fs.target.requires
-rw-r--r--. 1 fsumsal fsumsal 434 Jan  9 00:45 sysroot.mount
-rw-r--r--. 1 fsumsal fsumsal 648 Jan  9 00:45 systemd-fsck-root.service

test_install/usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-device.target.d:
total 4
-rw-r--r--. 1 fsumsal fsumsal 236 Jan  9 00:45 50-root-device.conf

test_install/usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-fs.target.requires:
total 4
-rw-r--r--. 1 fsumsal fsumsal 434 Jan  9 00:45 sysroot.mount

test_install/usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires:
total 4
-rw-r--r--. 1 fsumsal fsumsal 434 Jan  9 00:45 sysroot.mount
```

Not sure how much of an issue this actually is, but the difference is there.

/cc @evverx @yuwata @bluca @mbiebl

**Comment by mrc0mmand** [comment]
I guess the easiest "solution" (which would help with both of the issues) would be to `tar/zip/zstd/xz/...` the `test-fstab-generator` test directory into git and just extract it in the test script, since we already requires some of the archiving tools already for journal, but it doesn't sound too *elegant*.

**Comment by evverx** [comment]
> Meson already complains during ninja install:

Looks like it's a meson issue: https://github.com/mesonbuild/meson/issues/9233

**Comment by evverx** [comment]
On second thought to judge from https://github.com/mesonbuild/meson/issues/4069#issuecomment-415094562 looks like meson works as expected:
> I guess we should emulate the old behaviour in which a dangling symlink is copied as-is, but a real symlink is followed and the file itself is copied

**Comment by evverx** [comment]
> The systemd-tests package then looks like this

As far as I know that package is responsible for the "unit-tests" test there and it passes on Ubuntu CI as far as I can see. It's the "upstream" test that's broken somehow in "ubuntu ci" mode where "NO_BUILD" is apparently passed to it. It works fine on Ubuntu with just `make clean run`.

**Comment by evverx** [comment]
I think the easiest solution would be not to install the test and its data and just run it as a normal unit test.

**Comment by evverx** [comment]
> I guess the easiest "solution" (which would help with both of the issues) would be to tar/zip/zstd/xz/... the test-fstab-generator test directory into git and just extract it in the test script

I think it would make it hard to add new testcases because that archive would have to unpacked and packed again to do that

**Comment by evverx** [comment]
Anyway it appears `install_debian_systemd` is broken somehow in the sense that's it's different from whatever has to be installed by the `systemd-tests` package

**Comment by evverx** [comment]
@mrc0mmand this issue is Ubuntu CI specific (even though it's technically in the systemd repository) so I'm not sure what to do about it. It should be fixed but I still think the test has to be blocked with a denylist file until it's fixed.

**Comment by mrc0mmand** [comment]
Well, another relatively easy workaround would be to `rsync` the test data directory in the `install_debian_system` function to copy over missing test files; something which `install_suse_systemd` sort of already does:

https://github.com/systemd/systemd/blob/3989bdc1ad7cca4d75c06cdf601fea2cb37ba337/test/test-functions#L1106-L1110

**Comment by evverx** [comment]
I think the idea behind `install_debian_systemd` was to replicate the structure of the debian packages using test-functions. I'm not sure `rsync`ing the source tree on top of all those files copied from the debian packages would be in line with that. I'd wait for @mbiebl and @bluca. It would be nice to also figure out why the tests are run in three different modes there and somehow make it less complicated.

**Comment by evverx** [comment]
@mrc0mmand I've just reopened https://github.com/systemd/systemd/pull/22053 just in case :-)

**Comment by bluca** [comment]
> There are multiple things going "wrong":
> 
> 1. `debuild` strips empty directories
> 2. `debuild` (or something along the way) doesn't like dangling symlinks
> 
> Now, the `install_subdir()` in meson explicitly ignores `.gitatrributes`, so the respective installed `test-fstab-generator/*.expected/*.requires/` directory ends up with only a dangling symlink. And it looks like `debuild` doesn't like dangling symlinks so it strips them as well, leading to `test-{01..11}*.expected/*.requires/` directories being empty and subsequently stripped too. All this ends up in the `systemd-tests*.deb` package, which is then used when running the integration tests.

Can we use empty files instead of symlinks? The important thing is the filename, no?

**Comment by evverx** [comment]
Even if it's possible can Ubuntu CI not use three different ways to install files? Those symlinks is just a symptom.

**Comment by evverx** [comment]
Just to clarify, I think it should be easy to add new tests and contributors generally don't have to deal with the debian packages so even though I understand that it's likely be addressed by an on-off fix it would be nice to trim that unnecessary complexity.

**Comment by bluca** [comment]
Not really, autopkgtest works with packages

**Comment by evverx** [comment]
It doesn't. If it did the test wouldn't fail on Ubuntu CI. The packages are fine and the "unit-tests" test where the packages are installed properly doesn't fail.

**Comment by bluca** [comment]
Yes it does... anyway, changing to empty files in the repository seems to work locally, let's see if #22064 passes the CI too

**Comment by evverx** [comment]
> Yes it does...

If it does I wonder why the "upstream" test wasn't able to install the symlinks (while the "unit tests" test had no problem with that)?

**Comment by evverx** [comment]
@mrc0mmand even though that PR says it "fixes" this issue I'm going to reopen it because `install_debian_system` is still broken. I hope that's fine.

**Comment by evverx** [comment]
It would also be great if questions like https://github.com/systemd/systemd/pull/21944#issuecomment-1003472130 get answered from time to time. Even with the test fixed I think TEST-02-UNITTESTS should be blocked because apparently Ubuntu CI can't keep up with the systemd testsuite. The "unit tests" test should be enough to cover whatever it is Ubuntu CI is supposed to cover.

**Comment by keszybz** [comment]
@evverx what exactly is the issue that you want to track here?

**Comment by evverx** [comment]
@keszybz Ubuntu CI uses at least two different ways to install files, which basically caused the issue in the first place because if the packages were installed correctly everywhere the test wouldn't have failed.

Another issue is that it isn't clear why Ubuntu CI runs the "unit-tests" test considering it's already included in the "upstream" test.

**Comment by yuwata** [comment]
The test TEST-02-UNITTESTS was introduced to check the our unit tests also pass in container and qemu. Before I introduced that, sometimes we got reports that several tests cannot pass on container or virtual machines.

If there exist any issues in TEST-02 on a CI env, then I think it is better to fix them, and we should not skip it.
If there exist any issues in setup of testing environment, the issue should be fixed in the CI env, not upstream.

**Comment by evverx** [comment]
> The test TEST-02-UNITTESTS was introduced to check the our unit tests also pass in container and qemu. Before I introduced that, sometimes we got reports that several tests cannot pass on container or virtual machines.

@yuwata looking at https://github.com/systemd/systemd/pull/10047 I'm pretty sure I know why that test was introduced and how it works :-) And even there I mentioned the "root-unittest" package (which was renamed to the "unit-tests" package) :-)

> If there exist any issues in setup of testing environment, the issue should be fixed in the CI env, not upstream.

`install_debian_system` is in the systemd repository so I'd just keep tracking it here. I'm pretty sure It's never going to be fixed but at least this issue can be referred to going forward.

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/pull/21944#issuecomment-1003472130
> Apparently `test/TEST-02-UNITTESTS/deny-list-ubuntu-ci` can't be used to skip the "unit tests" test on Ubuntu CI/Semaphore CI. I'm not sure why it's still there though considering the "upstream" test basically includes the "unit tests" test.

TEST-02-UNITTESTS seems to be skipped on ppc64el, see e.g. https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/ppc64el/s/systemd-upstream/20220109_183853_e8ad8@/log.gz

**Comment by evverx** [comment]
@yuwata Ubuntu CI runs the unit tests three times as normal unit tests, as the "unit-tests" test and as the "upstream" test. TEST-02-UNITTESTS is included in the "upstream" test and it's true it can be skipped with a denylist file (which is done on ppc64el). (in that particular case the issue was that even though I skipped TEST-02-UNITTEST the "unit-test" kept failing). I have no idea why it is so complicated and why it should be dealt with every time new tests are added.

**Comment by mbiebl** [comment]
> Another issue is that it isn't clear why Ubuntu CI runs the "unit-tests" test considering it's already included in the "upstream" test.

One obvious benefit of having a separate "unit-tests" autopkgtest is that this test only requires `isolation-container`, so it e.g. can run on LXC, like used in the Debian CI infra.
This is in contrast to the monolithic "upstream" autopkgtest, which requires `isolation-machine`.

IIRC, the "unit-tests" autopkgtest also predates the upstream TEST-02-UNITTEST

**Comment by mbiebl** [comment]
I haven't really checked, but if TEST-02-UNITTEST and debian/tests/unit-tests run the exact same set of tests, then it might indeed make sense to skip TEST-02-UNITTEST.
Personally I would prefer that over dropping  debian/tests/unit-tests, as this autopkgtest, as said, is able to run on Debian CI via LXC (whereas unfortunately we can't run upstream on Debian CI yet).

**Comment by bluca** [comment]
the upstream suite is very different, as it runs in qemu and also in a completely different setup, so we want to keep both

**Comment by mbiebl** [comment]
> the upstream suite is very different, as it runs in qemu and also in a completely different setup, so we want to keep both

Ok, thanks for the clarification. Can this issue be closed now then?

**Comment by bluca** [comment]
yeah, I think so, there's nothing actionable left

**Comment by evverx** [comment]
@bluca FWIW https://github.com/systemd/systemd/issues/11195 is pretty actionable

**Comment by evverx** [comment]
> One obvious benefit of having a separate "unit-tests" autopkgtest is that this test only requires isolation-container, so it e.g. can run on LXC, like used in the Debian CI infra.

@mbiebl fair enough. Thanks!

Given that the "upstream" test and the "unit-tests" test depend on the "systemd-tests" package I wonder if it would be possible to somehow fix issues like https://github.com/systemd/systemd/issues/21975 by changing the debian package in one place only? I mean, force-pushing stuff until it works isn't the best developer experience :-)

**Comment by mbiebl** [comment]
@evverx you are all over the place. I have no idea anymore what you want to see fixed, btw. hijacking this issue with several unrelated issues doesn't really help.

**Comment by evverx** [comment]
This particular issue is about `install_debian_systemd`: https://github.com/systemd/systemd/issues/22059#issuecomment-1008340367

**Comment by mbiebl** [comment]
this issue was about skipping the test. If you want to see issues in install_debian_systemd addressed, file a new issue

**Comment by evverx** [comment]
> this issue was about skipping the test

I think it was just renamed along the way. The original issue was about "fstab-generator-test" (which broke Ubuntu CI because `install_debian_systemd` failed to copy symlinks that shouldn't have been there in the first place).

> btw. hijacking this issue with several unrelated issues doesn't really help.

Sorry about that. It's just that issues related to Ubuntu CI are ignored usually so I didn't expect anyone to pay attention to it.

**Comment by evverx** [comment]
FWIW I don't understand why there is an urge to close this issue right now considering it was just partly fixed. I generally have no problem with that because I can refer to closed issues (that aren't really fixed) as well. I'd let @mrc0mmand decide whether it should be closed or not though.

**Comment by mrc0mmand** [comment]
@evverx could you sum the `install_debian_systemd` woes up in a new issue? I agree that this one is pretty bloated already, so having it in a new one has a higher chance of someone taking a look at it (including me).

**Comment by evverx** [comment]
> I agree that this one is pretty bloated already

Agreed. Sorry about that.

> @evverx could you sum the install_debian_systemd woes up in a new issue?

I'll try to do that once I've gotten round to it.
