### ISSUE TITLE
Man pages unclear how keys in custom unit sections should be read

### ISSUE THREAD

**Issue by mikehearn** [systemd/systemd#22057]
Units can have [X-Foo] sections that systemd ignores, this is a nice and simple extension mechanism I'd like to use to associate metadata with units. However, there's no further information about this feature, like what the right way to read these extra fields actually is.

Ideally the man page would be extended to explain:

1. How to read this metadata via the DBUS API?
2. How to read this metadata from the CLI?

At the moment the only way I can see to read this data is to actually parse all the unit files myself and duplicate all the drop-in logic, but I'm sure I'm missing something obvious here. I looked at the DBUS API and didn't see any obvious way to read custom sections. Is there a way?

**Comment by keszybz** [comment]
There is no support for reading those keys over dbus. To read the whole file from the CLI, you could do something like `systemctl cat <unit-name>`, which would help with finding the right files and reading them in order, but the parsing would still need to be done by you.

This has been discussed a few times before (I think there should be a ticket open somewhere, but I can't find it right now). The main reason that nothing has been done about this is that D-Bus is a typed API, and for unknown keys, the only thing we could do would be to report them as series of strings. It's doable, but so far nobody took the challenge.

**Comment by keszybz** [comment]
The docs say "If an option or section name is prefixed with X-, it is ignored completely by systemd." — and that's pretty much it.

**Comment by mikehearn** [comment]
OK, thanks for the answer. I had interpreted "ignored completely" to mean they don't affect it's behavior, rather than the literal meaning that the extension mechanism is semantically identical to a file comment.

IMO exposing the metadata as strings would be fine. It would be unreasonable to expect systemd or dbus to impose semantics on keys it doesn't recognize.

**Comment by yuwata** [comment]
As already commented by @keszybz, I think it is already documented clearly. Is it OK to close this?

**Comment by mikehearn** [comment]
I do still think it could be helpful to note explicitly that there's no way to access this data other than by parsing the files yourself. Given the way the feature currently works it doesn't add anything over comment syntax, which is a bit unexpected. Normally metadata extension mechanisms do expose the metadata somewhere even if they don't use it.
