### ISSUE TITLE
Mount unit overrides don't work as expected

### ISSUE THREAD

**Issue by ssergiienko** [systemd/systemd#22061]
**systemd version the issue has been seen with**
 > systemd 250.1-1

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)

 > `5.15.13-arch1-1`

**Expected behaviour you didn't see**
 > Two possible use-cases:
1. I want to override some properties of autogenerated Mount unit to make corresponding directory automountable
2. Just modify mount options in some way (append/rewrite)

**Unexpected behaviour you saw**
 > Looks like any overrides are not actually applied properly (mount point is still not automount and not all options listed)
```
[root@some-host ~]# mount | grep bpool
bpool/ROOT/default on /boot type zfs (rw,nodev,relatime,xattr,posixacl,x-systemd.automount)
```

**Steps to reproduce the problem**
```
[root@some-host ~]# systemctl cat boot.mount
# /run/systemd/generator/boot.mount
# Automatically generated by zfs-mount-generator

[Unit]
SourcePath=/etc/zfs/zfs-list.cache/bpool
Documentation=man:zfs-mount-generator(8)

Before=zfs-mount.service local-fs.target
After=
Wants=

[Mount]
Where=/boot
What=bpool/ROOT/default
Type=zfs
Options=defaults,atime,relatime,nodev,exec,rw,suid,nomand,zfsutil

# /etc/systemd/system/boot.mount.d/override.conf
[Mount]
# I've tried various combinations
Options=atime,relatime,nodev,exec,rw,suid,nomand,zfsutil,noauto,x-systemd.automount,x-systemd.idle-timeout=1min
#Options=x-systemd.idle-timeout=1min,x-systemd.automount,noauto
```

```
[root@some-host ~]# systemctl cat boot.automount 
# /etc/systemd/system/boot.automount
[Automount]
Where=/boot
TimeoutIdleSec=30
```

```
[root@some-host ~]# systemctl show -p Options -p ExecMount boot.mount 
Options=rw,nodev,relatime,xattr,posixacl,x-systemd.automount
ExecMount={ path=/usr/bin/mount ; argv[]=/usr/bin/mount bpool/ROOT/default /boot -t zfs -o atime,relatime,nodev,exec,rw,suid,nomand,zfsutil,x-systemd.automount,x-systemd.idle-timeout=1min
```

Am I do configuration wrong or it's just not supported yet or it's a bug?

**Comment by yuwata** [comment]
If you reload units by `systemctl daemon-reload` and unmount /boot, then the /boot is mounted with the expected option?

**Comment by arvidjaar** [comment]
`Options` inside unit of type `mount` cannot magically change unit type to `automount`. The `x-systemd.automount` is interpreted only by fstab generator. There is no bug.

**Comment by poettering** [comment]
Yeah x-systemd.automount is an option understood by the fstab generator, not by PID1.
