### ISSUE TITLE
Building EFI components with -nostdinc is too restrictive

### ISSUE THREAD

**Issue by julian-klode** [systemd/systemd#2207]
The bootloader builds with too restricted settings, causing it to fail on ARM architectures, which use stdint.h in the gnu-efi headers - which is required by a freestanding C99 environment, but disabled by -nostdinc.

(I have not actually verified that removing -nostdinc fixes it, but it should).

**Comment by ardbiesheuvel** [comment]
As far as I can tell, the efibind.h headers for all architectures supported by GNU-EFI all include stdint.h, so I wonder why ARM is the odd case here. Are you passing -nostdinc for all architectures?

**Comment by julian-klode** [comment]
Sort of true. They include stdint.h if C standard is >= 99. The arm headers include them uncoditionally. And systemd builds the bootloader with -std=gnu90.

**Comment by ardbiesheuvel** [comment]
On 25 December 2015 at 20:00, Julian Andres Klode
notifications@github.com wrote:

> Sort of true. They include stdint.h if C standard is >= 99. The arm headers include them uncoditionally. And systemd builds the bootloader with -std=gnu90.

OK, that explains it perfectly. I will propose a patch to Nigel to
align ARM with x86 in this regard.

**Comment by poettering** [comment]
I presume what @ardbiesheuvel says is that this is going to be fixed in GNU-EFI instead? CLosing hence.
