### ISSUE TITLE
Increase defaults of systemd-coredump for ProcessSizeMax and ExternalSizeMax

### ISSUE THREAD

**Issue by kgibm** [systemd/systemd#22076]
**Is your feature request related to a problem? Please describe.**

The default values of `ProcessSizeMax` and `ExternalSizeMax` for `systemd-coredump` are [2GB](https://github.com/systemd/systemd/blob/v250/src/coredump/coredump.c#L52). We support Java customers who often run processes that are much larger. Truncated core dumps cause a lot of extra back-and-forth to have them understand and tune [`/etc/systemd/coredump.conf`](https://www.kernel.org/doc/man-pages/online/pages/man5/coredump.conf.5.html) and then they have to experience another production outage to reproduce the problem to get an untruncated core dump.

**Describe the solution you'd like**

Increase the default `ProcessSizeMax` and `ExternalSizeMax`. As far as what might be a good new default, I think that's open to debate. In my opinion, I suggest the default to be equal to `MaxUse`.

**Describe alternatives you've considered**

Many support engineers have just taken the simpler approach of disabling `systemd-coredump`; for [example](https://www.ibm.com/support/pages/node/72387):

> We know that settings like this will work:
> /proc/sys/kernel/core_pattern = core
> ** "core" with no other options

**The systemd version you checked that didn't have the feature you are asking for**

Most recently released upstream version

**Comment by keszybz** [comment]
@bluca you had some idea how to process core dumps without saving them to disk first. If we had that, that'd be beneficial on many fronts. We could unset ProcessSizeMax then, no?

**Comment by bluca** [comment]
Yeah I had a patchset to process corefiles directly from memory, but it was changed on review, see discussion at: https://github.com/systemd/systemd/pull/19166#discussion_r604742481
