### ISSUE TITLE
Full hostname does not include domain when nss-myhostame is in use

### ISSUE THREAD

**Issue by iandall** [systemd/systemd#22081]
**Is your feature request related to a problem? Please describe.**
The results of the shell command `hostname -f` depends on whether a proper DNS resolver is running (or not).
For example with systemd-resolved running, `hostname -f ` returns `host.domain` but with it stopped (or not started yet in early boot) `hostname -f ` returns `host` (depending on nsswitch.conf configuration).

Sometimes it is required that hostname works in early boot before systemd-resolved can be started.

**Describe the solution you'd like**
The `hostname -f` command is the result of `gethostbyaddr2_r()`, which, when the nss-myhostname plugin is active, comes from `_nss_myhostname_gethostbyaddr2_r()`. This function should return a fqdn if possible.

Proposed solution in PR #22078 

**Describe alternatives you've considered**
This can be worked around at the system administration level, by putting 'myhostname' after 'dns' in the hosts line of /etc/nsswitch, and ensuring that /etc/resolv.conf specifies a real name server (e.g. is a symlink to /run/systemd/resolve/resolv.conf not stub-resolv.conf). This may not even be enough if the real dns server is not available. However, it is desirable that 'myhostname' comes before 'dns' as it is quick because it doesn't have to connect to a server on a network. 

**The systemd version you checked that didn't have the feature you are asking for**

systemd 250 (250-246-g088193b)

**Comment by poettering** [comment]
as per discussion in #22078, I don't think we really should address this.
