### ISSUE TITLE
RFE: Support for TPM 1.2 in systemd-cryptenroll

### ISSUE THREAD

**Issue by surfaceflinger** [systemd/systemd#22091]
**Is your feature request related to a problem? Please describe.**
Many older devices simply can't update to TPM 2.0. While personally I have Haswell, there are also tons of Sandy/Ivy Bridge devices running Linux. TPM 1.2 might be deprecated and have some security issues but let's be real - most Linux users that would want to use TPM 1.2 most probably just want to protect their servers from potential thieves. Also, Windows BitLocker can integrate with TPM 1.2 by default so why can't we have nice things too?

**Describe the solution you'd like**
`systemd-cryptenroll --tpm-device` unified parameter for both TPM 1.2 and 2.0 maybe would be a good idea?

**Describe alternatives you've considered**
There are few projects on GitHub but they're hacky and distro specific eg: https://github.com/noahbliss/mortar

**The systemd version you checked that didn't have the feature you are asking for**
systemd 250.2-2 (Arch Linux)

**Comment by poettering** [comment]
Sorry, but no. TPM 1.2 works sufficiently differently to require major effort to support, and it's quite frankly obsolete. Adding new support code for obsolete technology is not something I am keen on. The major issue is that the crypto TPM 1.2 supports (SHA1) by today's standards is too weak. Thus TPM 1.2 can't really hold the security guarantees that people assume it provides. Supporting security tech that doesn't provide security is a waste of resources.

I mean, if the patch was minor I'd be OK with adding support for it if somebody hacked it up, but given this is non-trivial work, that someone then has to maintain, and it's basically dead tech that doesn't do what people think it does: no let's not do that.

Sorry, if that's disappointing.
