### ISSUE TITLE
Bridge stuck configuring after updating systemd to 250.2

### ISSUE THREAD

**Issue by su-ex** [systemd/systemd#22097]
**systemd version the issue has been seen with**
 > 250.2

**Used distribution**
 > Debian sid

**Linux kernel version used** (`uname -a`)

 > `Linux Server 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Bridge being `configured`

**Unexpected behaviour you saw**
 > Bridge stuck with `configuring`, wait online service fails

After updating from systemd 249.7-1 to 250.2-1 with Debian sid, a bridge which worked totally fine before is stuck in `degraded-carrier (configuring)`.
As a result, the wait online service fails and ipv6 prefix delegation is not working anymore.
Downgrading systemd solves this problem, then it's back to `degraded-carrier (configured)`.

The config looks like this:
```
# cat /etc/systemd/network/02-lan0.netdev                   [NetDev]
Name=lan0
Kind=bridge

# cat /etc/systemd/network/20-lan0.network
[Match]
Name=lan0

[Network]
Address=192.168.1.1/24
IPForward=yes
Address=fd11::1/64
MulticastDNS=no
IPv6AcceptRA=yes
IPv6DuplicateAddressDetection=1
IPv6PrivacyExtensions=no
LinkLocalAddressing=ipv6
ConfigureWithoutCarrier=yes
IPv6SendRA=yes
DHCPv6PrefixDelegation=yes

[IPv6AcceptRA]
PrefixDenyList=::/0

[IPv6PrefixDelegation]
RouterLifetimeSec=3600

[IPv6Prefix]
Prefix=fd11::/64

[IPv6SendRA]
RouterLifetimeSec=3600
EmitDNS=true
DNS=fd11::1
EmitDomains=true
Domains=home
```

**Comment by yuwata** [comment]
Please provide debugging logs of systemd-networkd. It can be generated by creating the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by su-ex** [comment]
@yuwata While updating systemd again so I can grab the logs I noticed that the bridge stuck in `configuring` is just a symptom:
The interface which should get the IPv6 prefix for the prefix delegation has multiple `wan0: DHCPv6 client: Failed to process received reply message, ignoring: Bad message`. If I set `DHCPv6PrefixDelegation=no` for my lan0 bridge interface, it get's configured again (of course without prefix delegation, which I want).
I've openend a new issue with attached logs: #22099

**Comment by yuwata** [comment]
As you already mentioned, according to the log provided in #22099, the reason why the bridge interface stays in the configuring state is that the wan0 cannot handle the DHCPv6 reply message. Let's continue to investigate why DHCPv6 message is dropped in #22099. Closing.

**Comment by su-ex** [comment]
Is there a way to have my bridge interface being configured although no IPv6 prefix could be delegated (but still using prefix delegation if it could acquire a prefix of course)?

**Comment by yuwata** [comment]
@su-ex Please apply #22106. Unfortunately, there is no workaround for the issue. Also, see the comment https://github.com/systemd/systemd/issues/22099#issuecomment-1012022896.
