### ISSUE TITLE
[journalctl] Always showing the current boot - `-e` option after `-b` option cancels the latter

### ISSUE THREAD

**Issue by getzze** [systemd/systemd#22107]
**systemd version the issue has been seen with**
 > 250.2

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.15.14-1-lts`

**CPU architecture issue was seen on**
 > x86_64

**Steps to reproduce the problem**
 > $ export SYSTEMD_LOG_LEVEL=debug;
 $ journalctl --list-boots
 ... 
 -2 48665a230e3346949035ea0130975d3b
 -1 7ef7a54648bf49cfb505825ae30d5df8
  0 d5c19bda3a884d9b953661c6fa7e5c2e
$ journalctl -e -b-1
...
Journal filter: _BOOT_ID=7ef7a54648bf49cfb505825ae30d5df8
...
$ journalctl -b-1 -r
...
Journal filter: _BOOT_ID=7ef7a54648bf49cfb505825ae30d5df8
...
$ journalctl -b-1 -e
...
Journal filter: _BOOT_ID=d5c19bda3a884d9b953661c6fa7e5c2e
...

**Expected behaviour you didn't see**
 > `journalctl -b-1 -e` displays the logs for the previous boot

**Unexpected behaviour you saw**
 > `journalctl -b-1 -e` displays the logs for the current boot
Also unexpected behavior with `journalctl -b-5 -e`. `journalctl -b -1 -e`, `journalctl --boot=-1 -e`, `journalctl --boot=-1 --pager-end`.
It seems that setting `pager-end` cancels the `boot` option if it's given before.

**Comment by yuwata** [comment]
This is a regression caused by 2dd9285bacc2212e20853312f44175303c84807b.
