### ISSUE TITLE
systemctl can't read symlinks to SysVinit service scripts in /etc/init.d after upgrading to RHEL 7.2's systemd-219-19.el7

### ISSUE THREAD

**Issue by nhlong** [systemd/systemd#2210]
https://bugzilla.redhat.com/show_bug.cgi?id=1288005

**Comment by evverx** [comment]
Fixed: https://github.com/systemd/systemd/pull/1249

**Comment by nhlong** [comment]
Hi @evverx, thanks for your response. 
I see that this fix was tagged with v228
Do you backport it to v219 since the Centos repo just contains v219 ?

**Comment by evverx** [comment]
> I see that this fix was tagged with v228

```
$ git describe --contains 7b729f8686a83b2
v227~114^2
```

So, `v227` contains that fix.

> Do you backport it to v219 since the Centos repo just contains v219 ?

It's not an upstream issue.
See [Reporting systemd Bugs](http://freedesktop.org/wiki/Software/systemd/Debugging/#index4h1):

> Please report bugs to your distribution's bug tracker first. If you are sure that you are encountering an upstream bug, then first check for existing bug reports, and if your issue is not listed file a new bug

**Comment by poettering** [comment]
Please ask the CentOS folks for help, we don't do bbackports upstream.

**Comment by nhlong** [comment]
Thanks @evverx
