### ISSUE TITLE
[hostnamed] Get "Serial Number" of device using hostnamed  

### ISSUE THREAD

**Issue by nitinexclusively** [systemd/systemd#22119]
Hello , 
Currently , I am working to display "Serial Number" of device in gnome-settings . I am using ThinkPad X1 Yoga G6
We can get "Serial Number" of the device using sysfs "/sys/class/dmi/id/product_serial" . But since this needs root permission , we cannot directly access it .
Is it acceptable to add "serial number" in hostnamed ? Any comment regarding this will be helpful. 
Thank you !1

**Comment by yuwata** [comment]
Now I am working on this.
