### ISSUE TITLE
Reboot hangs if volume group got renamed

### ISSUE THREAD

**Issue by poelzi** [systemd/systemd#22112]
**systemd version the issue has been seen with**
 
systemd 247 (247.3-6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
> Debian

**Linux kernel version used** (`uname -a`)

 > `Linux server8 5.13.19-2-pve #1 SMP PVE 5.13.19-4 (Mon, 29 Nov 2021 12:10:09 +0100) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > System should reboot

**Unexpected behaviour you saw**
 > Waiting for deactivating swap for ages

**Steps to reproduce the problem**
1. create swap on a lvm group and add it to fstab.
2. reboot system
3. use vgrename to rename volume group, adjust fstab
4. reboot

**Comment by yuwata** [comment]
Sorry, v247 is slightly old here... Could you reproduce the issue with recent release (v249 or v250) or current git HEAD?

**Comment by poettering** [comment]
Please contact the LVM community regardig LVM issues.
