### ISSUE TITLE
new Unit type request

### ISSUE THREAD

**Issue by ondrejv2** [systemd/systemd#22120]
Currently we only support few SystemD unit types which are mostly derived of two basic types:
- simple
- forking
Now I am wondering if we could add another "forking" - type of unit, which is considered "Active" immediately after main PID is started -
i.e. much like in "simple" unit-type, but will work like "forking" so will finish only after the main PID and all it's forks finishes.

Does it make a sense?

**Comment by bluca** [comment]
This can already be achieved with the new `ExitType=cgroup` setting, please check that one out (new in v250)
