### ISSUE TITLE
UpheldBy property does not exist

### ISSUE THREAD

**Issue by s7hoang** [systemd/systemd#22133]
**systemd version the issue has been seen with**
 > systemd 250 (250.1-1-arch)

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)

 > `Linux 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemctl show b.service | grep "UpheldBy"
   -> UpheldBy=a.service

**Unexpected behaviour you saw**
 > systemctl show b.service | grep "UpheldBy"
   -> \<empty\>

**Steps to reproduce the problem**
 > 1.  pick two services _a.service_ and _b.service_
 > 1.  stop both services
 > 1. in _[Unit]_ of _a.service_, add `Upholds=b.service`
 > 1. start _a.service_
 > 1. verify _a.service_ has started
 > 1. verify _b.service_ has started
 > 1. execute `systemctl show b.service |grep "UpheldBy"`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
<from systemd.unit>
       Upholds=
           Configures dependencies similar to Wants=, but as long as this unit is up, all units listed in Upholds= are started whenever found to be inactive or failed, and no job is queued for them. While a
           Wants= dependency on another unit has a one-time effect when this units started, a Upholds= dependency on it has a continuous effect, constantly restarting the unit if necessary. This is an
           alternative to the Restart= setting of service units, to ensure they are kept running whatever happens.

           When Upholds=b.service is used on a.service, this dependency will show as UpheldBy=a.service in the property listing of b.service. The UpheldBy= dependency cannot be specified directly.

```

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #22134.
