### ISSUE TITLE
systemd-portable (250) --extension documentation

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#22146]
The documentation for --extension=PATH in the portablectl manual page is unclear.

This feature functionality is also inconsistent with `ExtensionImages=` (systemd.exec)

I would argue that it should be interchangeable

ie if ExtensionImages=/var/lib/extensions/myext.raw works for a service then --extension=/var/lib/extensions/myext.raw should also work with a portable service

instead if fails with a confusing error:

```
root@myguest1:/usr/lib# portablectl attach /var/lib/portables/apache2.raw --runtime --extension=/var/lib/extensions/myext.raw --profile=trusted apache2
(Matching unit files with prefixes 'apache2'.)
AttachImageWithExtensions failed: Image '/var/lib/extensions/myext.raw' lacks extension-release data, refusing.
```
and I have no idea what that is trying to tell me....

**Comment by bluca** [comment]
They should be interchangeable - that error is telling you that the extension-release metadata of myext.raw doesn't match the os-release metadata of apache2.raw, what are the contents of the respective files?

https://www.freedesktop.org/software/systemd/man/os-release.html#/usr/lib/extension-release.d/extension-release.IMAGE

There's also more documentation here:

https://systemd.io/PORTABLE_SERVICES/#:~:text=no%20restrictions%20enforced.-,Extension%20Images,-Portable%20services%20can

**Comment by doverride** [comment]
The inconsistency is this

portables --extension= requires /usr/lib/extension-release.d/extension-release.NAME to exist *** on the extension image ***

systemd.exec ExtensionImages= requires that this file exists *** on the host *** only

**Comment by bluca** [comment]
Uhm, it shouldn't, both need to require it in the image, not in the host - what systemd version are you using, and can you share the directory structure of the images being used and the content of os-release and extension-release?

**Comment by doverride** [comment]
250

```
root@myguest1:/home/kcinimod# cat /usr/lib/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@myguest1:/home/kcinimod# 
```
```
root@myguest1:/home/kcinimod# cat /usr/local/lib/extension-release.d/extension-release.myext
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
root@myguest1:/home/kcinimod# systemd-dissect -m /var/lib/extensions/myext.raw /mnt
root@myguest1:/home/kcinimod# ls /mnt
opt  usr
root@myguest1:/home/kcinimod# ls /mnt/opt
mytest
root@myguest1:/home/kcinimod# ls /mnt/usr/lib/extension-release.d/
extension-release.myext
root@myguest1:/home/kcinimod# cat /mnt/usr/lib/extension-release.d/extension-release.myext 
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@myguest1:/home/kcinimod# 
```
If i remove the /usr dir from the "myext..raw" image then:
1. portablectl --extension= will break
2. system.exec ExtensionImages= will still work

bottom line: systemd.exec ExtensionImages= does not require a /usr/lib/extension-release.d on the image

**Comment by doverride** [comment]
but yes i guess `man systemd.exec` is clear about that requirement
```
Each image must carry a /usr/lib/extension-release.d/extension-release.IMAGE file, with the appropriate metadata which matches RootImage=/RootDirectory= or the host. See: os-release(5).
```

**Comment by bluca** [comment]
Ok, I'll try to repro later and fix it, thanks.

Is the documentation on systemd.io enough to clarify how --extension works? I need to link that doc in the manpage

**Comment by doverride** [comment]
I guess the documentation in systemd.exec and systemd-sysext are clear. The documentation in portablectl wrt --extension can probably be improved

But in the end what confused me is that ExtensionImages= works fine without a `/usr/local/lib/extension-release.d/extension-release.NAME` on the image (but I did have that one the host)

**Comment by doverride** [comment]
Not quite related but now that i have "myext.raw" to work with --extension and ExtensionImages= I wanted to try this on the host with systemd-sysext:

Jan 17 12:34:59 myguest1 (sd-sysext)[486]: Device '/var/lib/extensions/myext.raw' is loopback block device with partition scanning turned off, please turn it on.

What is it telling me? How do i turn this on?

This image was created with systemd-repart. Any idea why this image works with --extension and ExtensionImages= , but not with systemd-sysext?

```
[Partition]
Type=root
SizeMinBytes=2000M
SizeMaxBytes=2000M
Format=btrfs
```

**Comment by doverride** [comment]
never mind: https://blog.lazy-evaluation.net/posts/linux/ubuntu-loop-max_part.html

**Comment by doverride** [comment]
Actually no, that does not work reliably either....

https://github.com/systemd/systemd/blob/9519b41e529bc904b159acb87bdf84231599776b/src/shared/dissect-image.c#L3252

Strange because man systemd-sysext claims that gpt partition are supported

**Comment by doverride** [comment]
I think that is a bug in systemd-sysext ... it should maybe be setting "LO_FLAGS_PARTSCAN" during setup?

specifying "loop.max_part" on the kernel command line enables part scanning for all loop devices but causes other weird behavior so that is a no-go

**Comment by bluca** [comment]
Would you be able to test it and send a PR if it works?

**Comment by bluca** [comment]
Found the issue with the validation - we were skipping it entirely if there was no VERSION_ID or SYSEXT_LEVEL, which is of course the case for rolling releases

**Comment by bluca** [comment]
@doverride with the validation fix and the updated manpage, is there anything else left pending for your use case?

**Comment by bluca** [comment]
> I think that is a bug in systemd-sysext ... it should maybe be setting "LO_FLAGS_PARTSCAN" during setup?
> 
> specifying "loop.max_part" on the kernel command line enables part scanning for all loop devices but causes other weird behavior so that is a no-go

Would you be able to test this PR? https://github.com/systemd/systemd/pull/22164

**Comment by doverride** [comment]
https://github.com/systemd/systemd/pull/22164 fixes the aforementioned "partition scanning" issue. Thanks.

There is still an issue with systemd-sysext merge/refresh where it failed with "Failed to read metadata for image myext: File exists" but that is for another time.

**Comment by bluca** [comment]
> #22164 fixes the aforementioned "partition scanning" issue. Thanks.
> 
> There is still an issue with systemd-sysext refresh (unmerge+merge) where it failed with "Failed to read metadata for image myext: File exists" but that is for another time.
> 
> ```
> [   97.426483] BTRFS warning: duplicate device /dev/loop2p1 devid 1 generation 30 scanned by systemd-udevd (854)
> ```

Can you share exact instructions for building the image triggering that? We can reopen this or a new one

**Comment by doverride** [comment]
Something like this:
```
mkdir -p /run/repart.d
 cat > /run/repart.d/root.conf <<EOF
[Partition]
Type=root
SizeMinBytes=2000M
SizeMaxBytes=2000M
Format=btrfs
EOF
systemd-repart --no-pager --empty=create \
		   --seed=random --size=auto /var/lib/extensions/myext.raw
systemd-dissect -M /var/lib/extensions/myext.raw /mnt/myext
mkdir -p /mnt/myext/usr/lib/extension-release.d
cat > /mnt/myext/usr/lib/extension-release.d/extension-release.myext" <<EOF
ID=debian
EOF
system-mount -u /mnt/mytext
systemctl enable systemd-sysext
reboot
systemd-sysext refresh
systemd-sysext unmerge
systemd-sysext merge
dmesg
```

**Comment by bluca** [comment]
The original issues here are solved and this sounds quite different, so I've opened https://github.com/systemd/systemd/issues/22182
