### ISSUE TITLE
systemd crashes unexpectedly

### ISSUE THREAD

**Issue by Zeno-sole** [systemd/systemd#22155]
**systemd version the issue has been seen with**
 > 250

 

**Used distribution**
 >  deepin v20

**Linux kernel version used** (`uname -a`)

 > `kernel 5.10.60 or kernel 5.15.6`

**CPU architecture issue was seen on**
 >  i7-12700K anbd virtualbox

**Expected behaviour you didn't see**
 >  I want systemd to run fine and not crash

**Unexpected behaviour you saw**
 > Probabilistic crash during system update, After analysis, I think it is a systemd problem. After the crash, the current session is forced to quit, and you can log in again under tty. After logging in, it is found that the pid of important processes such as systemd --user has changed, and systemd-journald has also been logged out. 

**Steps to reproduce the problem**
 > It is a probabilistic occurrence when performing a system update, this is not a bug that can be reproduced stably

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
2022-01-16 10:28:22 uos-PC systemd[1]:  alsa-state.service: Main process exited, code=killed, status=9/KILL
2022-01-16 10:28:22 uos-PC systemd[1]:  systemd-journald.service: Main process exited, code=killed, status=9/KILL
2022-01-16 10:28:22 uos-PC systemd[1]:  systemd-journald.service: Failed with result 'signal'.
2022-01-16 10:28:22 uos-PC systemd-timesyncd[31571]:  The system is configured to read the RTC time in the local time zone. This mode cannot be fully supported. All system time to RTC updates are disabled.
2022-01-16 10:28:22 uos-PC systemd[1]:  user-runtime-dir@1000.service: Succeeded.

```

**Comment by Zeno-sole** [comment]
Since the log service has crashed, how should I get the crash information?

**Comment by yuwata** [comment]
Sorry, v241 is too old here. Please contact your distro, or try to reproduce the issue with recent release (v249 or v250) or the current git HEAD. Closing.

**Comment by Zeno-sole** [comment]
I also reproduced this problem on version 250. How can I debug? All debugging tools need to run under the current session, but the current session is also over due to the crash of systemd

**Comment by Zeno-sole** [comment]
@yuwata  Is there any way to debug systemd?

**Comment by yuwata** [comment]
First, please try to boot with systemd.log_level=debug.

**Comment by Zeno-sole** [comment]
@yuwata  systemd.log_level=debug Doing this does not seem to print out any more information, I think the log service has crashed, and the debug information cannot be printed

**Comment by mrc0mmand** [comment]
> @yuwata systemd.log_level=debug Doing this does not seem to print out any more information, I think the log service has crashed, and the debug information cannot be printed

Try `systemd.log_level=debug systemd.log_target=console`. If that doesn't help, try appending `systemd.default_standard_output=journal+console` as well.

Also, don't forget to check output of `dmesg` and possibly `coredumpctl list` as well (if the machine boots fine) - if you spot any relevant coredumps in `coredumpctl`'s output, `coredumpctl info <binary>` should give you a stack trace.
