### ISSUE TITLE
Not buildable with meson 0.61

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#22158]
Systemd build broke after upgrading meson from 0.60 to 0.61

The Meson build system
Version: 0.60.3
Source dir: /tmp/abf/rpmbuild/BUILD/systemd-fab79a85af29ba1c1e237ace6c8078357c04b488
Build dir: /tmp/abf/rpmbuild/BUILD/systemd-fab79a85af29ba1c1e237ace6c8078357c04b488/x86_64-rosa-linux-gnu
Build type: native build

meson.build:3:0: ERROR: Unknown options: "default_locale, python, static"

It was a WARNING, not ERROR, beforehand.

**Comment by mikhailnov** [comment]
Oh, I am sorry, those were incorrect options passed to meson, e.g. -Ddefault_locale instead of -Ddefault-locale

**Comment by eli-schwartz** [comment]
> Systemd build broke after upgrading meson from ***0.60 to 0.61***
> 
> The Meson build system
> Version: ***0.60.3***

https://mesonbuild.com/Release-notes-for-0-60-0.html#unknown-options-are-now-always-fatal

It's been a fatal error since 0.60.0, and you're not using meson 0.61 anyway. :p
