### ISSUE TITLE
pam_systemd(crond:session): Failed to create session: Maximum number of sessions (8192) reached, refusing further sessions

### ISSUE THREAD

**Issue by iranbingo** [systemd/systemd#22151]
**Linux kernel version used** (`uname -a`)

 > `SLES 15 SP1 x86_64`

**Steps to reproduce the problem**
 > 

Hi,

After we have updated SLES 15 SP1, Journal shows an Error:

Cron [45024]: PAM_SystemD (Crond: Session): Failed to Create Session: Maximum Number of Sessions (8192) Reached, Refusing Further Sessions.

SSHD [50481]: PAM_SystemD (SSHD: Session): Failed to Create Session: Maximum Number of Sessions (8192) Reached, Refusing Further Sessions.

With the PAM configuration, we have not changed anything.
At Limits.conf, SessionMax was and is commented.
Before the update there was no limit 8192.

tnx

**Comment by iranbingo** [comment]
I found out that a bug in Systemd remains no longer fictional the D-Bus. You have to update systemd.
This update for systemd fixes the following issues:

- Revert "core: rework how we connect to the bus" (bsc#1193521 bsc#1193481)
sleep-config: partitions can't be deleted, only files can
shared/sleep-config: exclude zram devices from hibernation candidates


Fixes
systemd-234-24.99.1 causes systemd randomly to fail utterly [ref:_00D1igLOd._5001inKB0R:ref]
sd_bus_call_method() - Message recipient disconnected from message bus without replying

**Comment by jmchepe** [comment]
@[iranbingo](https://github.com/iranbingo) how you fix this?

**Comment by iranbingo** [comment]
> @[iranbingo](https://github.com/iranbingo) how you fix this?

Simply run Linux update.  zypper update -y

**Comment by gleventhal** [comment]
I am seeing this issue as well, it causes sessions to leak, I believe, and sd_bus_call_method fails to establish a session with ENOTCONN.  I see things backup and a lot of cgroup rmdir and mkdir activity.  I've also noticed kworkers to backup and start contending on locks, aligning with this issue.  I suspect it's due to cgroup churn.
