### ISSUE TITLE
systemd-sysctl.service failed

### ISSUE THREAD

**Issue by xiyou123321** [systemd/systemd#22165]
#systemctl status systemd-sysctl.service 
鈼[0m systemd-sysctl.service - Apply Kernel Variables
   Loaded: loaded (/usr/lib/systemd/system/systemd-sysctl.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2022-01-19 10:45:03 GMT; 8min ago
     Docs: man:systemd-sysctl.service(8)
           man:sysctl.d(5)
  Process: 9349 ExecStart=/usr/lib/systemd/systemd-sysctl (code=exited, status=1/FAILURE)
 Main PID: 9349 (code=exited, status=1/FAILURE)

Jan 19 10:45:03 HikvisionOS systemd[1]: Starting Apply Kernel Variables...
Jan 19 10:45:03 HikvisionOS systemd-sysctl[9349]: Line is not an assignment in file '/etc/sysctl.d/99-sysctl.conf': (null)
Jan 19 10:45:03 HikvisionOS systemd-sysctl[9349]: Line is not an assignment in file '/etc/sysctl.conf': (null)
Jan 19 10:45:03 HikvisionOS systemd[1]: systemd-sysctl.service: main process exited, code=exited, status=1/FAILURE
Jan 19 10:45:03 HikvisionOS systemd[1]: Failed to start Apply Kernel Variables.
Jan 19 10:45:03 HikvisionOS systemd[1]: Unit systemd-sysctl.service entered failed state.
Jan 19 10:45:03 HikvisionOS systemd[1]: systemd-sysctl.service failed.

Yeah,i am running the following command as root
that 

#strace /usr/lib/systemd/systemd-sysctl
execve("/usr/lib/systemd/systemd-sysctl", ["/usr/lib/systemd/systemd-sysctl"], [/* 24 vars */]) = 0
brk(NULL)                               = 0x55e9e5227000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facac2f1000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=40698, ...}) = 0
mmap(NULL, 40698, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7facac2e7000
close(3)                                = 0
open("/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|S_ISUID|S_ISGID|0777, st_size=88776, ...}) = 0
mmap(NULL, 2184192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7facabebb000
mprotect(0x7facabed0000, 2093056, PROT_NONE) = 0
mmap(0x7facac0cf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7facac0cf000
close(3)   .......
open("/proc/sys/net/core/netdev_max_backlog", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facac2f0000
write(3, "5000\n", 5)                   = 5
close(3)                                = 0
munmap(0x7facac2f0000, 4096)            = 0
open("/proc/sys/kernel/sem", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facac2f0000
write(3, "1250 256000 100 8192\n", 21)  = 21
close(3)                                = 0
munmap(0x7facac2f0000, 4096)            = 0
exit_group(1)                           = ?
+++ exited with 1 +++

And
#rpm -qa | grep systemd
systemd-219-78.el7_9.3.x86_64
systemd-libs-219-78.el7_9.3.x86_64
systemd-python-219-78.el7_9.3.x86_64
systemd-devel-219-78.el7.x86_64
systemd-sysv-219-78.el7_9.3.x86_64

Thanks

**Comment by yuwata** [comment]
Sorry v219 is too old here. Please contact to your distro.

**Comment by xiyou123321** [comment]
> Sorry v219 is too old here. Please contact to your distro.

yesh,i know.But this problem did not occur on other machines

**Comment by yuwata** [comment]
I guess you use /etc/sysctl.conf and /etc/sysctl.conf.d/ files with newer format, which is not supported by old systemd.

**Comment by xiyou123321** [comment]
> I guess you use /etc/sysctl.conf and /etc/sysctl.conf.d/ files with newer format, which is not supported by old systemd.

the following is /etc/sysctl.conf ，But I don't think it's any different from a normal configuration file
#ll /etc/sysctl.conf 
-rwxrwxrwx. 1 root root 1730 Dec  2 07:46 /etc/sysctl.conf

**Comment by yuwata** [comment]
Anyway, here is not a support forum, but an issue or RFE tracker. Please contact to your distro.

Only I can say here is that try to check the contents of your sysctl files carefully. Sorry.
