### ISSUE TITLE
RFE: extend Password Agents to user instances of systemd

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#2217]
reference: http://www.freedesktop.org/wiki/Software/systemd/PasswordAgents/

services run by the user instance of systemd should also be able to ask for passwords, especially since one user instance of systemd can support several sessions (tty, X, ssh).

That means the /run/user/1000/systemd/ask-password should be created, and agents bundled with systemd updated. 

No need for pkexec whould be required for those services.

**Comment by Stebalien** [comment]
See: #1232

**Comment by poettering** [comment]
Duplicate of #1232.
