### ISSUE TITLE
resolve: ignore links in down state

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#22190]
Using Debian sid/unstable with

    $ systemd --version
    systemd 250 (250.3-1)
    +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

monitoring the system with `sudo opensnoop.bt`, `/lib/systemd/systemd-resolved` shows up several times querying the non-existing file `/run/systemd/netif/links/2`.

    […]
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    65285  systemd-resolve    -1   2 /run/systemd/netif/links/2
    […]

The directory is empty:

    $ LANG=C ls -l /run/systemd/netif/links
    total 0

**Comment by yuwata** [comment]
To retrieve information such as DNS servers from networkd. By accessing the file, resolved checks if the interface is managed by networkd or not. I guess that should not be harmful in general. Or, do you have any issues caused by that?

**Comment by paulmenzel** [comment]
It is not harmful. But unnecessary and waking the processor up needlessly I guess.

1.  Why does it (often) access the file several times in less than a second?
2.  NetworkManager is used on my system and not systemd-networkd. And can’t systemd-networkd inform systemd-resolved once it is taking over management of a device?

**Comment by yuwata** [comment]
There may be a chance that the networkd starts or processes the interface later than resolved does. So, resolved check the possibility every time when the interface state is changed. I guess such repeated access on the file occurs only when booting the system or configuring the network interface, and once the interface is configured, then the file merely accessed. Or do you observe the repeated access on the file continuously??

**Comment by paulmenzel** [comment]
> Or do you observe the repeated access on the file continuously??

Yes, I observe repeated access.

**Comment by yuwata** [comment]
Hm. Strange. Will check.

**Comment by yuwata** [comment]
The file is accessed through `link_update()`, it is called when resolved receives `RTM_NEWLINK` netlink message, or a file is moved to the directory, or a file in the directory is removed.

If networkd is not running, then the directory is never touched. So, I guess `RTM_NEWLINK` message is broadcasted by kernel repeatedly.

Try to monitor RTNL message, e.g. iwd contains iwmon which can also monitor RTNL.

At least, in my environment, RTM_NEWLINK message is not broadcasted so frequently.

**Comment by paulmenzel** [comment]
Thank you for digging into this. It looks like that event is sent every ten seconds on my system (Wireless LAN turned off, and only Ethernet cable connected (e1000e).

```
< RTNL: Get Link (0x12) len 16 [request,dump]                          6.061833
    Flags: 769 (0x301)
    Sequence number: 0 (0x00000000)
    Port ID: 0
> RTNL: New Link (0x10) len 1328 [multi]                               6.061884
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: New Link (0x10) len 1392 [multi]                               6.061884
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: New Link (0x10) len 1372 [multi]                               6.061905
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
    IFLA Family: Unknown
    IFLA Type: 1
    IFLA Index: 3
    IFLA ChangeMask: 0
    IFLA Flags: (0x1002) [broadcast,multicast]
        IfName (len:6): wlan0
        Txqlen: 1000 (0x000003e8)
        OperState: down (2)
        LinkMode: kernel controlled (0)
        MTU: 1500 (0x000005dc)
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 1
        Qdisc (len:8): noqueue
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 1
        Map: len 32
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        Interface Address: 92:5b:b6:a3:3d:27
        Broadcast Address: ff:ff:ff:ff:ff:ff
        Reserved: len 192
        Stats: len 96
            ab c7 00 00 12 52 00 00 a6 63 7e 03 44 74 2a 00  .....R...c~.Dt*.
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        Reserved: len 8
        Reserved: len 6
        Reserved: len 784
        Reserved: len 13
        Reserved: len 4
> RTNL: New Link (0x10) len 1324 [multi]                               6.061905
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: Done (0x03) len 4 [multi]                                      6.061918
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
    Status: 0
> RTNL: Done (0x03) len 4 [multi]                                      6.061955
    Flags: 2 (0x002)
    Sequence number: 1 (0x00000001)
    Port ID: 33507
    Status: 0
< RTNL: Get Link (0x12) len 16 [request,dump]                          6.062086
    Flags: 769 (0x301)
    Sequence number: 0 (0x00000000)
    Port ID: 0
> RTNL: New Link (0x10) len 1328 [multi]                               6.062126
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: New Link (0x10) len 1392 [multi]                               6.062126
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: New Link (0x10) len 1372 [multi]                               6.062141
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
    IFLA Family: Unknown
    IFLA Type: 1
    IFLA Index: 3
    IFLA ChangeMask: 0
    IFLA Flags: (0x1002) [broadcast,multicast]
        IfName (len:6): wlan0
        Txqlen: 1000 (0x000003e8)
        OperState: down (2)
        LinkMode: kernel controlled (0)
        MTU: 1500 (0x000005dc)
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 1
        Qdisc (len:8): noqueue
        Reserved: len 4
        Reserved: len 4
        Reserved: len 4
        Reserved: len 1
        Map: len 32
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        Interface Address: 92:5b:b6:a3:3d:27
        Broadcast Address: ff:ff:ff:ff:ff:ff
        Reserved: len 192
        Stats: len 96
            ab c7 00 00 12 52 00 00 a6 63 7e 03 44 74 2a 00  .....R...c~.Dt*.
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
            00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        Reserved: len 8
        Reserved: len 6
        Reserved: len 784
        Reserved: len 13
        Reserved: len 4
> RTNL: New Link (0x10) len 1324 [multi]                               6.062141
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
> RTNL: Done (0x03) len 4 [multi]                                      6.062150
    Flags: 2 (0x002)
    Sequence number: 0 (0x00000000)
    Port ID: 33507
    Status: 0
> RTNL: Done (0x03) len 4 [multi]                                      6.062186
    Flags: 2 (0x002)
    Sequence number: 1 (0x00000001)
    Port ID: 33507
    Status: 0
```

**Comment by yuwata** [comment]
Interesting. Maybe, resolved should ignore links in down state.

**Comment by yuwata** [comment]
I hope the situation becomes better with PR #22199.
Unfortunately, the attempts of reading the link file cannot be removed completely even if the relevant interface is down.

**Comment by paulmenzel** [comment]
Thank you for taking care of this so quickly.

Out of curiosity, is it expected that these RTNL events are sent every ten seconds?

**Comment by yuwata** [comment]
Unfortunately, I do not have any idea. Maybe, the first step to investigate who triggers the RTNL event is stopping NetworkManager or wlan manager like wpa_supplicant or iwd.
