### ISSUE TITLE
Allow override of HardwareModel value reported to org.freedesktop.hostname1

### ISSUE THREAD

**Issue by directhex** [systemd/systemd#22207]
**Is your feature request related to a problem? Please describe.**
It is ridiculously common for motherboard vendors to leave DMI information blank on hardware sold to consumers (rather than to Dell and HP), resulting in motherboards reporting their model as "To be filled in by O.E.M." or "System Product Name". GNOME Control Center dutifully reports the value taken from DMI:

![FJo_fMLXwAUWq4H](https://user-images.githubusercontent.com/308992/150569180-cea4edd8-9920-40dd-89e8-724924462eb7.jpeg)

Which mirrors the behaviour where Windows also reports the same value, so thoughtfully filled in by the motherboard manufacturer:

![FA8PXI5WQAogvOR](https://user-images.githubusercontent.com/308992/150569288-8f50c2be-2bca-45f2-9bb9-60e0b6663809.png)

Windows, however, has an override function. Setting the override will cause anything which asks Windows for the hardware model (as opposed to anything which probes DMI directly) to report a user-specified or vendor-specified value instead, as filled in via the Windows Registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation\Model`

**Describe the solution you'd like**
There should be some means to override the value hostnamed reports via dbus. The exact implementation of that override doesn't really matter, just that it should exist.

**Describe alternatives you've considered**
Per-app overrides could exist instead, but fixing it at the lower level seems like a better use of time. Of course, hostnamectl would need a per-app override too in that case, and we'd still be back here in GitHub with a feature request issue.

**The systemd version you checked that didn't have the feature you are asking for**
I looked at 249.5 and didn't see any relevant changes in git master

**Comment by hadess** [comment]
It can be overridden through quirks:
https://github.com/systemd/systemd/pull/15531/files

Though it could also be changed to respect the values in `/etc/machine-info` like we already support for chassis info.

**Comment by hadess** [comment]
cc @felipeborges

**Comment by yuwata** [comment]
Now I am working on this.

**Comment by directhex** [comment]
It looks like, as a rule, if you didn't buy it from Dell or HP, the chassis and system DMI values are junk (since the OEM is expected to fill them in). The board DMI values are usable in this case
