### ISSUE TITLE
core/namespace: Protect{Hostname,KernelTunables} and ProcSubset=pid

### ISSUE THREAD

**Issue by brauner** [systemd/systemd#22206]
This is with systemd 250.

Starting any service with:
```
ProtectHostname=true
ProtectSubset=pid
```
currently fails. A fix for this is waiting in https://github.com/systemd/systemd/pull/22203. That fix should be sound.

What I don't understand and would really like an explanation for is why the addition of `ProtectKernelTunables=true` makes a service with the aforementioned options work again:
```
ProtectHostname=true
ProtectSubset=pid
ProtectKernelTunables=true
```

I can understand it conceptually of course since `ProtectSubset=pid` implicitly protects the files under `ProtectKernelTunables` and `ProtectHostname` by not even exposing them anymore in `proc`. But I don't understand where in the code and how `protect_kernel_tunables` and `protect_hostname` interact with each other such that `protect_kernel_tunables` cancels `protect_hostname` and makes things work again.

**Comment by topimiettinen** [comment]
`ProtectKernelTunables=yes' makes a mount of `/proc/sys` with readonly flags. Maybe it defeats `ProcSubset=pidonly` by mounting the directory even if it wouldn't exist then?

**Comment by brauner** [comment]
I found the culprit; it's `normalize_mounts()`. I renamed that function to `drop_unused_mounts()` and documented it a bit.

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/22203
