### ISSUE TITLE
dbus-send introspect error 

### ISSUE THREAD

**Issue by Silicomancer** [systemd/systemd#2220]
The following didn't work using Kunbuntu 15.10 but I assume it should:

$ dbus-send --print-reply --type=method_call --dest=org.freedesktop.systemd1 / org.freedesktop.DBus.Introspectable.Introspect

Error org.freedesktop.DBus.Error.Spawn.ChildExited: Process 
org.freedesktop.systemd1 exited with status 1

**Comment by poettering** [comment]
Presumably your distro does not run a "systemd --user" instance, only a system instance. If you add "--systemd" to your dbus-send command line, things should work, and you can introspect the host systemd instance. If you really wanted to talk to the user instance, make sure it's actually enabled on your distro.

**Comment by zonque** [comment]
> Presumably your distro does not run a "systemd --user" instance, only a system instance. If you add "--systemd" to your dbus-send command line, things should work, and you can introspect the host systemd instance. If you really wanted to talk to the user instance, make sure it's actually enabled on your distro.

`--system`, not `--systemd` :)

**Comment by poettering** [comment]
true!
