### ISSUE TITLE
Google Chrome: Network service crashed, restarting service.

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [systemd/systemd#22223]
**systemd version the issue has been seen with**
 ```
$ systemd-resolve --version
systemd 250 (250.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**
 > EndeavourOS 2021.12.17

**Linux kernel version used**
 > `Linux macProKiller 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Chrome Opening Normally once I launch it

**Unexpected behaviour you saw**
 > Chrome startup hangs for a long time and then throws an error relating to network service.

**Steps to reproduce the problem**
 > Install chrome using `yay -S google-chrome` (stable version) and launch it.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
$ google-chrome-stable 
[6815:6815:0122/231549.506138:ERROR:network_service_instance_impl.cc(972)] Network service crashed, restarting service.
```

Launching from the application drawer doesn't even launch chrome.

**Comment by yuwata** [comment]
I am not sure, but at RHBZ, it is reported that stopping resolved and edit resolv.conf propery fixes the issue.

So, I guess it is an issue in nss-resolve. Maybe caused by ae78529fc75027b3487b64e0d22a572fd9c8ffeb. And I guess 6e8ecb8974db74eba716bfd75231987172e10d83 fixes the issue.

Could you test the commit?

**Comment by yuwata** [comment]
Anyway, please bisect which commit introduces the bug.

**Comment by xinthose** [comment]
Remove Chrome's config folder and it will work after that: `rm -r ~/.config/google-chrome`.

**Comment by licamla** [comment]
I use chromium 109.0.5414.74，the same error message is logged.
after update package `dev-libs/icu`  to version 72.1 and rebuild chromium, chromium work well.

Maybe an incompatible `icu` version caused this problem.

**Comment by poettering** [comment]
Let's close this, given the lack of response this was either fixed or people lost interest. Either way, no need to track this here, in particular as 250 is quite old by today's standards.
