### ISSUE TITLE
systemd-resolved returns SERVFAIL for reverse DNS lookups of 0.0.0.0/::0

### ISSUE THREAD

**Issue by rickyz** [systemd/systemd#22229]
Reverse DNS lookups for 0.0.0.0 and some other addresses listed in [RFC6303](https://datatracker.ietf.org/doc/html/rfc6303) fail with SERVFAIL:
```
$ host 0.0.0.0
Host 0.0.0.0.in-addr.arpa not found: 2(SERVFAIL)
$ resolvectl query 0.0.0.0
0.0.0.0: resolve call failed: No appropriate name servers or networks for name found
```

According to the RFC, NXDOMAIN should be returned for such queries. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961378 is an example of a program failure that can result from this behavior.

Looking at the code, it looks like reverse lookups for some (but not all) of the addresses in the RFC are prevented from going to global resolvers here:
https://github.com/systemd/systemd/blob/bb995f747afa17055c26b5d69a21f68f7dab0c28/src/resolve/resolved-dns-scope.c#L624-L627

However, they do not appear to be handled in the place where DNS answers are synthesized:
https://github.com/systemd/systemd/blob/bb995f747afa17055c26b5d69a21f68f7dab0c28/src/resolve/resolved-dns-synthesize.c#L373-L470

Here is a [completely untested patch](https://github.com/systemd/systemd/files/7921340/untested_rfc6303.patch.txt) that contains some experiments at fixing this. However, I probably won't have the time to clean up/test it to make a nice pull request, sorry!

**Comment by yuwata** [comment]
Fix is waiting in #22231.
