### ISSUE TITLE
Impossible to susbscribe to the mailing list 

### ISSUE THREAD

**Issue by felagund** [systemd/systemd#22228]
I reported this here: https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/411

but nothing is happening and I thought I would bring it to your attention.

The mailing list seems to require filling captcha for signing up, but the captcha does not work. It is not displayed at all. This has been like this at least since the start of the year.
![Screenshot_20220123_210125](https://user-images.githubusercontent.com/1218098/150695950-b7ca2128-c3a8-4b26-abf7-a147ef64428a.png)

I really hope I am just not making something wrong, but I cannot se what, I tried different browsers, different connections, different devices...

**Comment by mrc0mmand** [comment]
It indeed doesn't seem to display the captcha, but the subscription process seems to work nonetheless (after clicking on "Subscribe", I get an confirmation email). Does it work for you?

**Comment by felagund** [comment]
Ah, yes, all the confirmation e-mails were getting into spam, a basic mistake not to look there.

I was confused by the bold note there "(Note that you really have to sign up with the web form below, signing up via the mail service is not available for spam fighting reasons.)", I thought it meant no confirmation e-mail was involved at all.

Thank you, this can be ignored then.
