### ISSUE TITLE
`bootctl install` modifies currently running system's state, won't work without a machine ID

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#22224]
Using systemd v250 on carbonOS 2022.1

It seems like `bootctl install` now assumes that it will only ever be run inside of the system it will be booting. This assumption is wrong in many cases: it is only right if the system is being upgraded from a different bootloader to sd-boot. In most (all?) other cases, `bootctl install` will be invoked from within a _different_ copy of the OS than the one it will be booting. Here's two use cases that will elaborate exactly what I mean by this:

### The OS image builder case

When building an OS image, I use a transient container with the right packages staged into it to generate the ISO image. When `bootctl install` gets invoked, the userspace it's running in was created 30 seconds ago and will be destroyed as soon as the ISO image is created and stored. It doesn't have an /etc/machine-id because it isn't a machine, and creating the file is undesirable (it introduces randomness into the build, which is bad for the purposes of reproducible builds)

Upgrading to systemd v250 broke my ISO image builder. Basically, `bootctl install` now requires that /etc/machine-id exists (regression from #16687) even if I pass `--make-machine-id-directory=no`. Additionally, if I do create the /etc/machine-id file to work around this issue, `bootctl install` will write to `/etc/machine-info` in my build environment! This new file just contains `KERNEL_INSTALL_LAYOUT=bls`. This is definitely unexpected and unwanted. This created file is useless because it will immediately get destroyed once the ISO is generated

### The LiveOS or other OS case

I distribute a LiveOS image of my OS with a installer tool baked into it. At install time, the installer tool invokes `bootctl install` to install the bootloader, set up EFI variables, etc. This also has the unintended side-effect of writing /etc/machine-info into the LiveOS's filesystem. This file will never make it into the installed system, and really shouldn't be created. Luckily, this doesn't have any bad side-effects for the user because any changes to the LiveOS are thrown out on shutdown

Here's a situation where this can backfire for the user: Let's say the user has two machines. A botched bootloader upgrade on machine A caused it to stop booting, so they removed the SSD and connected it to machine B. In machine B, they mount the SSD's ESP to /mnt and delete all of the systemd-boot-related binaries (executables, random-seed, etc; not config). Then, they run `bootctl install --no-variables --esp-path=/mnt`. This will do two unintended things:
- Put machine B's machine-id into machine A's new bootloader config. This doesn't happen in the LiveOS because systemd (correctly) detects that /etc is on a temporary fs. This will probably mess up machine A's boot config and require some manual fixup
- Modify machine B's /etc/machine-info. This could reconfigure machine B's kernel-install, and the next time kernel-install is invoked, it'll misconfigure machine B's bootloader

### Extra note

I build systemd with kernel-install disabled in meson (since kernel-install would break my distro's configuration if used). bootctl should probably avoid doing anything specific for kernel-install if kernel-install cannot and will not ever be used on the system.

**Comment by yuwata** [comment]
@keszybz and @medhefgo I set 'regression' tag, but feel free to drop or downgrade the tag.

**Comment by DaanDeMeyer** [comment]
@AdrianVovk It'd be great if you could test #22290. It should make sure that bootctl works without a machine ID available.

**Comment by AdrianVovk** [comment]
@DaanDeMeyer your PR fixes the "doesn't install without machine-id present" bug, but it still writes `/etc/machine-info` into the running environment

**Comment by DaanDeMeyer** [comment]
@AdrianVovk Yeah writing /etc/machine-info is by design. Is there a reason you can't persist /etc/machine-info in the OS image? The information we put in there isn't machine-specific so it should be safe to ship as part of the image.

**Comment by AdrianVovk** [comment]
- At install time, `/etc` doesn't necessarily exist in the installed OS. It's created during the first boot (Oops: I misread and thought you were asking why I can't copy the file into the installed OS. I'll leave this point here anyway because it could apply to other use-cases)
- The configuration you're putting in `/etc/machine-info` is entirely unnecessary because `kernel-install` is not packaged on the system. Nothing will ever read that configuration
- Putting files in `/etc` to configure what kind of content is in `/efi` is antithetical to factory-reset-able systems. What happens when a factory-reset wipes out `/etc` and that file is lost?
- machine-info contains data other than the kernel-install details you're putting in there. Some of that data _is_ machine-specific (chassis-type, for instance)
- Even if it would make sense to get this file into the newly-installed system, that doesn't make it any more reasonable to put the file into the build or LiveOS environments

> The information we put in there isn't machine-specific

It is, though? You put the machine-id into that file (if not running on a LiveOS or somewhere where machine-id is backed by temporary storage). This applies to the scenario I came up with in the original issue description
