### ISSUE TITLE
systemd-resolved forward ad flag received from dns server

### ISSUE THREAD

**Issue by mateusz834** [systemd/systemd#22221]
**Is your feature request related to a problem? Please describe.**
So from my testing it looks like systemd-resolved is doing its own dnssec validation when DNSSEC is set to yes in /etc/systemd/resolved.conf. When DNSSEC=no then queries are not dnssec validated (as expected), but if the dns server is already doing dnssec validation  (ad flag is set in response), then systemd-resolved just removes it from the response.

![dnssec=no](https://user-images.githubusercontent.com/19653795/150646066-dab6d5e1-d89f-40ff-b94d-4aefc568b95b.png)

**Describe the solution you'd like**
Add a new option to DNSSEC option like: trust-ad, which won't do any dnssec validation. It would just forward ad flag received from the dns server (and store it in cache).

**The systemd version you checked that didn't have the feature you are asking for**

systemd 250 (250.3-1-arch)

**Comment by mildsunrise** [comment]
no commit or PR was referenced when fixing this issue. can someone point me to the fix?
this issue requested adding `DNSSEC=trust-ad`, but this doesn't appear to be implemented (or I can't find it)

**Comment by mateusz834** [comment]
@mildsunrise oh, sorry i closed it because i ended up doing this in a different way anyway. If needed i can reopen it, but the PR #31897 already lists different issues that seem to request the same feature.

**Comment by mildsunrise** [comment]
thanks. yes, no worries, there's #31365 which is basically requesting the same thing
