### ISSUE TITLE
Set network device group with systemd-networkd

### ISSUE THREAD

**Issue by jabberabbe** [systemd/systemd#22243]
**Is your feature request related to a problem? Please describe.**
Network interfaces reside in groups that can be used, e.g. in firewall rules, or to perform administration on multiple links (with `iproute2`). The default group is 0.

**Describe the solution you'd like**
It would be useful to have an option `Group=XX` in link configuration files to set the group via systemd-networkd as soon as the interface is discovered. I tried looking through the documentation but this doesn't seem to be implemented as of now.

**Describe alternatives you've considered**
This can also be done with a service unit bound to `sys-subsystem-net-devices-IFACE.device` that calls `ip link set dev IFACE group 1234`. However, it would be more idiomatic to do this through networkd, which is specifically designed to configure network devices.

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 250 (250.2-2-arch)`

**Comment by yuwata** [comment]
Hm? We have `Group=` setting in [Link] section of .network file. You mean, it does not work for you??

**Comment by jabberabbe** [comment]
Sorry, I think missed that. I mostly looked through the documentation of `.link` network files because I thought it could only make sense as a global per-link setting. RTFM to me.
