### ISSUE TITLE
Logitech Craft keyboard is detected as mouse

### ISSUE THREAD

**Issue by SethFalco** [systemd/systemd#22260]
I reported this bug in [upower](https://gitlab.freedesktop.org/upower/upower), and was suggested by one of the developers to forward it here.  
You can see the original bug report here: https://gitlab.freedesktop.org/upower/upower/-/issues/161

Similar to:
* https://github.com/systemd/systemd/pull/15711

**systemd version the issue has been seen with**
 > systemd 247 (247.3-6)

However, the issue should still be present in 250.

https://github.com/systemd/systemd/blob/main/hwdb.d/60-input-id.hwdb

**Used distribution**
 > Debian GNU/Linux 11 (bullseye) x86_64

**Linux kernel version used** (`uname -a`)

 > `Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Keyboard should be detected as keyboard.

**Unexpected behaviour you saw**
 > Keyboard is detected as mouse. 

This can lead to confusion when the device runs low on battery. For example, GNOME tells me my mouse is low on battery when it's actually my keyboard that's low.

![](https://gitlab.freedesktop.org/upower/upower/uploads/2b2229e9c7b3ed330bc885505e15095a/image.png)
![](https://gitlab.freedesktop.org/upower/upower/uploads/c5d179cf1a596c5bbe9e3d4a35021d76/image.png)

**Steps to reproduce the problem**
 > Connect [Logitech Craft](https://www.logitech.com/en-us/products/keyboards/craft.920-008484.html) keyboard to [Logitech Unifying Receiver](https://www.logitech.com/en-us/products/mice/unifying-receiver-usb.910-005235.html).

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
P: /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.2/3-1.2:1.2/0003:046D:C52B.0005/0003:046D:4066.0006
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.2/3-1.2:1.2/0003:046D:C52B.0005/0003:046D:4066.0006
E: SUBSYSTEM=hid
E: DRIVER=logitech-hidpp-device
E: HID_ID=0003:0000046D:00004066
E: HID_NAME=Logitech Craft
E: HID_PHYS=usb-0000:00:14.0-1.2/input2:1
E: HID_UNIQ=4066-82-58-a9-02
E: MODALIAS=hid:b0003g0102v0000046Dp00004066

P: /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.2/3-1.2:1.2/0003:046D:C52B.0005/0003:046D:4066.0006/input/input25
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.2/3-1.2:1.2/0003:046D:C52B.0005/0003:046D:4066.0006/input/input25
E: SUBSYSTEM=input
E: PRODUCT=3/46d/4066/111
E: NAME="Logitech Craft"
E: PHYS="usb-0000:00:14.0-1.2/input2:1"
E: UNIQ="4066-82-58-a9-02"
E: PROP=0
E: EV=12001f
E: KEY=3f000303ff 0 0 483ffff17aff32d bfd4444600000000 ffff0001 130ff38b17c007 ffff7bfad941dfff ffbeffdfffefffff fffffffffffffffe
E: REL=1943
E: ABS=100000000
E: MSC=10
E: LED=1f
E: MODALIAS=input:b0003v046Dp4066e0111-e0,1,2,3,4,11,14,k71,72,73,74,75,77,78,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,8B,8C,8E,8F,90,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B0,B1,B2,B3,B4,B5,B6,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,CE,CF,D0,D1,D2,D4,D8,D9,DB,DF,E0,E1,E4,E5,E6,E7,E8,E9,EA,EB,F0,F1,F4,100,110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,161,162,166,16A,16E,172,174,176,177,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,247,248,249,250,251,260,261,262,263,264,265,r0,1,6,8,B,C,a20,m4,l0,1,2,3,4,sfw
E: USEC_INITIALIZED=3808446
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c52b
E: ID_REVISION=2411
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=02
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:1.2:1.2
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_2_1_2
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_1_2_1_2
E: TAGS=:seat:
E: CURRENT_TAGS=:seat:
```

```
$ upower -D
…
Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                Craft Advanced Keyboard
  serial:               4066-82-58-a9-02
  power supply:         no
  updated:              Sat 18 Dec 2021 19:12:34 CET (18 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       low
    battery-level:       low
    percentage:          10% (should be ignored)
    icon-name:          'battery-caution-symbolic'
…
```

**Comment by SethFalco** [comment]
Based on the previous PR, I assume I just have to add this to `60-input-id.hwdb`:

```diff
+ # Logitech Craft Keyboard
+ id-input:modalias:input:b0003v046Dp4066e0111*
+  ID_INPUT_MOUSE=0
```

Sorry if this is a daft question, but I'm wondering how to test this locally though? ^-^'

**Comment by yuwata** [comment]
Please try to add the entry in /etc/udev/hwdb.d/ and run `systemd-hwdb update; udevadm control --reload; udevadm trigger --action add /dev/input/eventX`.

If it works, then please submit it as a PR. Thank you.

**Comment by SethFalco** [comment]
Just dropping this link here for future reference:
https://www.freedesktop.org/software/systemd/man/hwdb.html#Examples

Thanks for the help! Works fine locally so I'll open a PR.
