### ISSUE TITLE
COPY_HOLES is borked with holes at the end of files

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22288]
See my comment here:

https://github.com/systemd/systemd/pull/22125/commits/8646b5d6e6019e95063a49fb3105833b07da5ebc#r794588930

I think there's the bug with holes at end of files, but I only got this by reading the PR, not by actually trying it out, maybe I am missing something.

Opening this issue so that we can keep track of this.

@DaanDeMeyer

**Comment by yuwata** [comment]
This should be already fixed by f82f0b993740f4a9a3719c4df7c185411710df2b.

**Comment by poettering** [comment]
Ah, i didn't see that one, I am just looking at my backlog...

Hmm, those are 5 syscalls for each hole. I wonder if we can do this better... And issue truncate only once at the end, and make this configurable via COPY_TRUNCATE. It might make sense to truncate outside of the hole context anyway.

**Comment by poettering** [comment]
Also the punch hole stuff is only supported on some fs... this needs a better fallbcak logic still. (i think ramfs is an fs that doesn't implement hole punching, if you need one for testing)

**Comment by yuwata** [comment]
#22291 is merged.
