### ISSUE TITLE
test-bpf-lsm fails

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#22287]
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/9719/artifact//systemd-centos-ci/artifacts_all/artifacts_m85i3fds/vagrant-logs.7OK/vagrant-arch-sanitizers-clang-testsuite.Zzo/ninja-test_sanitizers_FAIL.log

Not sure this is reproducible.

**Comment by mrc0mmand** [comment]
I'll go ahead and close this, since I haven't seen the issue for a while, and the log file no longer exists.
