### ISSUE TITLE
[RFE] Add something like --ignore-lid-switch and --handle-lid-switch to loginctl

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#22339]
**Is your feature request related to a problem? Please describe.**
Since the lid switch (closed) state will persistently trigger logind to handle it, one can't really use an inhibit lock to make logind ignore the lid switch for only a couple times of closing.

**Describe the solution you'd like**
Some runtime command (option) that allow the lid switch to be ignored indefinitely without needing to edit logind.conf or have an overriding snippet and restart logind, like `loginctl --ignore-lid-switch`. And e.g. `--handle-lid-switch` should cause the handling methods for the keys of the lid switch family to be set to the ones that logind was started with. (In other words, the values should be stored.)

**Describe alternatives you've considered**
Adding a snippet and restarting logind can apparently crash GUI in some weird way. (The X server and clients are not killed but somehow it is not shown over the tty anymore.) Regardless of whether that is a bug (of systemd or some DRM stuff) or it will always happen, it is inconvenient anyway.

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by poettering** [comment]
I don't follow? Why not just take the blocking inhibitor lock for the lid switch as long as you want this behaviour?

**Comment by tomty89** [comment]
Well one sort of can, I suppose. It's just lame that you have to keep something running by some means (like with a terminal window opened or having a service running `systemd-inhibit while-true-sleep-1d-script`). Or is there some neater / less silly way to do it that I missed?

**Comment by poettering** [comment]
You want to make a persistent config change?

**Comment by poettering** [comment]
> only a couple times of closing.

What does that mean? You want the change persistently? Or not? I am confused...

**Comment by tomty89** [comment]
> You want to make a persistent config change?

You can see it as persistent-for-this-boot. Sometimes you just want it to be ignored because of a context/scenario that last for an indefinite (as in, not yet determinable) period of time, but not like till one specific program finishes its job. So it would be nice if the user can just like "tell" logind "to ignore" and "stop ignoring" on his/her will.

Persisting, but not permanent.

**Comment by poettering** [comment]
you know that all systemd tools that read /etc/…/xyz.conf also read /etc/…/xyz.conf.d/*.conf, /run/…/xyz.conf and /run/…/xyz.conf.d/*.conf, right? i.e. what you are looking for is:

```sh
mkdir -p /run/systemd/logind.conf.d
cat > /run/systemd/logind.conf.d/50-ignore-lid-switch.conf <<EOF
[Login]
HandleLidSwitch=…
EOF
```

because /run/ is flushed out on reboot you get the behaviour you want?

**Comment by tomty89** [comment]
Yeah the problem is you need to restart logind for the snippet to be in effect, no? Which seems to be kind of a dangerous thing to do. (I tried exactly the same thing and X is left in some half crashed state.)

Besides, regardless of whether this can work successfully, it is not at all less clumsy than `systemd-inhibit while-true-sleep-1d-script.

**Comment by tomty89** [comment]
Perhaps it would be even greater if this can be implemented like the linger file: logind checks for file (e.g. /run/systemd/ignore-lid-switch), if the file exists, logind consider the keys to have the value of `ignore`, if it does not, the cached values are used. This way one can even implement a "toggle" easily.

**Comment by poettering** [comment]
> Yeah the problem is you need to restart logind for the snippet to be in effect, no? 

No need to restart. Reload works too. i.e. "systemctl reload systemd-logind".

Which seems to be kind of a dangerous thing to do. (I tried exactly the same thing and X was left in some half crashed state.)

In theory that should work too, but some desktop stuff doesn't really like that.
