### ISSUE TITLE
mount is unable to create "What" directory if path is a symlink

### ISSUE THREAD

**Issue by landgraf** [systemd/systemd#22334]
**systemd version the issue has been seen with**
 > v250 (regression, v249.7 works fine)

**Used distribution**
 > Openembedded

**Linux kernel version used** (`uname -a`)

 > `5.10.61-yocto-standard`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > successful bind mount

**Unexpected behaviour you saw**
 > Failed to mount

**Steps to reproduce the problem**
 > Create mount unit with What=/var/run/dir1/dir2 where /var/run -> /run and dir1 doesn't exist

**Additional program output to the terminal or log subsystem illustrating the issue**

```text

Feb 01 08:23:27 qemux86-64 systemd[1]: var-lib-sysota.mount: Failed to make bind mount source '/var/run/mount/sysdata/rootfs-overlay/var/lib/sysota': Not a directory
Feb 01 08:23:27 qemux86-64 systemd[1]: Mounting /var/lib/sysota...
Feb 01 08:23:27 qemux86-64 mount[342]: mount: /var/lib/sysota: special device /var/run/mount/sysdata/rootfs-overlay/var/lib/sysota does not exist.
Feb 01 08:23:27 qemux86-64 systemd[1]: var-lib-sysota.mount: Mount process exited, code=exited, status=32/n/a
Feb 01 08:23:27 qemux86-64 systemd[1]: var-lib-sysota.mount: Failed with result 'exit-code'.
Feb 01 08:23:27 qemux86-64 systemd[1]: Failed to mount /var/lib/sysota.

# systemctl cat var-lib-sysota.mount 
# /lib/systemd/system/var-lib-sysota.mount
[Unit]
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target
After=run-mount-sysdata.mount
Requires=run-mount-sysdata.mount

[Mount]
What=/var/run/mount/sysdata/rootfs-overlay/var/lib/sysota
Where=/var/lib/sysota
Type=none
Options=bind

[Install]
WantedBy=local-fs.target

```

**Comment by landgraf** [comment]
This commit causes the regression https://github.com/systemd/systemd/commit/3008a6f21c1c42efe852d69798a2fdd63fe657ec

**Comment by yuwata** [comment]
Fix is waiting in #22359.

**Comment by landgraf** [comment]
@yuwata I can confirm that fixes the issue. Thanks

**Comment by yuwata** [comment]
@landgraf Thank you for testing the PR so quickly!
