### ISSUE TITLE
systemd-resolved: Intermittent failure resolving domain names

### ISSUE THREAD

**Issue by nandryshak** [systemd/systemd#22348]
Re-open of prior issue: #9690

**systemd version the issue has been seen with**
 250

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)
    Linux nick-arch-home 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
 Expected domain name to be resolved. It fails more often than not.

**Unexpected behaviour you saw**
 Intermittent lookup failures, especially for the domains: `api.dropboxapi.com`, `content.dropboxapi.com`, `management.azure.com`. I haven't actually noticed it happen for other domains. Error message:

>api.dropboxapi.com: resolve call failed: Lookup failed due to system error: Invalid argument

**Steps to reproduce the problem**
    `$ while resolvectl query api.dropboxapi.com ; do sleep 1 ; done`

**Additional program output to the terminal or log subsystem illustrating the issue**

Log output for `resolvectl query api.dropboxapi.com` on log level DEBUG:

    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Positive Trust Anchors:
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Negative trust anchors: home.arpa 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Using system hostname 'nick-arch-home'.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: New scope on link *, protocol dns, family *
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Found new link 3/docker0
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Found new link 2/enp4s0
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Found new link 1/lo
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: New scope on link enp4s0, protocol llmnr, family AF_INET6
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 38567 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET6 (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Delaying llmnr transaction 38567 for 75094us.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: New scope on link enp4s0, protocol llmnr, family AF_INET
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 315 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Delaying llmnr transaction 315 for 17744us.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Bus bus-api-resolve: changing state UNSET → OPENING
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: sd-bus: starting bus bus-api-resolve by connecting to /run/dbus/system_bus_socket...
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Bus bus-api-resolve: changing state OPENING → AUTHENTICATING
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Registering bus object implementation for path=/org/freedesktop/resolve1 iface=org.freedesktop.resolve1.Manager
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Registering bus object implementation for path=/org/freedesktop/resolve1/link iface=org.freedesktop.resolve1.Link
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Registering bus object implementation for path=/org/freedesktop/resolve1/dnssd iface=org.freedesktop.resolve1.DnssdService
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Creating stub listener using UDP/TCP.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Bus bus-api-resolve: changing state AUTHENTICATING → HELLO
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Bus bus-api-resolve: changing state HELLO → RUNNING
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=signal sender=org.freedesktop.DBus destination=:1.232 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=signal sender=org.freedesktop.DBus destination=:1.232 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Successfully acquired requested service name.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Initial jitter phase for transaction 315 elapsed.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Retrying transaction 315.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 315 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 315 on interface 2/AF_INET of size 32.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Initial jitter phase for transaction 38567 elapsed.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Retrying transaction 38567.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 38567 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET6 (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 38567 on interface 2/AF_INET6 of size 32.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=192.168.1.113, destination=224.0.0.252
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=fe80::d918:19d:91cd:353c, destination=ff02::1:3
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink: New incoming connection.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink: Connections of user 0: 0 (of 576 max)
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Setting state idle-server
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 38567.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Retrying transaction 38567.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 38567 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET6 (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 38567 on interface 2/AF_INET6 of size 32.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 315.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Retrying transaction 315.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 315 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 315 on interface 2/AF_INET of size 32.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"dev.azure.com","flags":0}}
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state idle-server → processing-method
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: idn2_lookup_u8: dev.azure.com → dev.azure.com
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Looking up RR for dev.azure.com IN A.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Looking up RR for dev.azure.com IN AAAA.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Switching to system DNS server 1.1.1.1.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/resolve1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Cache miss for dev.azure.com IN AAAA
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 61522 for <dev.azure.com IN AAAA> scope dns on */* (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Using feature level UDP+EDNS0 for transaction 61522.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Using DNS server 1.1.1.1 for transaction 61522.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Announcing packet size 1472 in egress EDNS(0) packet.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 61522 of size 42.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Cache miss for dev.azure.com IN A
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Firing regular transaction 64548 for <dev.azure.com IN A> scope dns on */* (validate=yes).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Using feature level UDP+EDNS0 for transaction 64548.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Using DNS server 1.1.1.1 for transaction 64548.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Announcing packet size 1472 in egress EDNS(0) packet.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Sending query packet with id 64548 of size 42.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state processing-method → pending-method
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=fe80::d918:19d:91cd:353c, destination=ff02::1:3
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=192.168.1.113, destination=224.0.0.252
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received dns UDP packet of size 70, ifindex=2, ttl=0, fragsize=0, sender=1.1.1.1, destination=192.168.1.113
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Processing incoming packet of size 70 on transaction 61522 (rcode=SUCCESS).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Verified we get a response at feature level UDP+EDNS0 from DNS server 1.1.1.1.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Added positive unauthenticated non-confidential cache entry for dev.azure.com IN AAAA 131s on enp4s0/INET/1.1.1.1
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Regular transaction 61522 for <dev.azure.com IN AAAA> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Received dns UDP packet of size 58, ifindex=2, ttl=0, fragsize=0, sender=1.1.1.1, destination=192.168.1.113
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Processing incoming packet of size 58 on transaction 64548 (rcode=SUCCESS).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Added positive unauthenticated non-confidential cache entry for dev.azure.com IN A 20s on enp4s0/INET/1.1.1.1
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Regular transaction 64548 for <dev.azure.com IN A> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Freeing transaction 61522.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Sending message: {"parameters":{"addresses":[{"ifindex":2,"family":10,"address":[38,32,1,236,0,33,0,0,0,0,0,0,0,0,0,32]},{"ifindex":2,"family":2,"address":[13,107,42,20]}],"name":"dev.azure.com","flags":8388609}}
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state pending-method → idle-server
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: Freeing transaction 64548.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Got POLLHUP from socket.
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state idle-server → pending-disconnect
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state pending-disconnect → processing-disconnect
    Feb 01 11:46:00 nick-arch-home systemd-resolved[37431]: varlink-23: Changing state processing-disconnect → disconnected
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 38567.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Retrying transaction 38567.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Firing regular transaction 38567 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET6 (validate=yes).
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Sending query packet with id 38567 on interface 2/AF_INET6 of size 32.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 315.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Retrying transaction 315.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Firing regular transaction 315 for <nick-arch-home IN ANY> scope llmnr on enp4s0/INET (validate=yes).
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Sending query packet with id 315 on interface 2/AF_INET of size 32.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=fe80::d918:19d:91cd:353c, destination=ff02::1:3
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Received llmnr UDP packet of size 32, ifindex=2, ttl=255, fragsize=0, sender=192.168.1.113, destination=224.0.0.252
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 38567.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Retrying transaction 38567.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Regular transaction 38567 for <nick-arch-home IN ANY> on scope llmnr on enp4s0/INET6 now complete with <not-found> from none (unsigned; non-confidential).
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Record nick-arch-home IN AAAA fe80::d918:19d:91cd:353c successfully probed.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Freeing transaction 38567.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Timeout reached on transaction 315.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Retrying transaction 315.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Regular transaction 315 for <nick-arch-home IN ANY> on scope llmnr on enp4s0/INET now complete with <not-found> from none (unsigned; non-confidential).
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Record nick-arch-home IN A 192.168.1.113 successfully probed.
    Feb 01 11:46:01 nick-arch-home systemd-resolved[37431]: Freeing transaction 315.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Got message type=method_call sender=:1.234 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: idn2_lookup_u8: api.dropboxapi.com → api.dropboxapi.com
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=5 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=6 reply_cookie=5 signature=u error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: D-Bus hostname resolution request from client PID 37474 (n/a) with UID 4294967295
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Looking up RR for api.dropboxapi.com IN A.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Looking up RR for api.dropboxapi.com IN AAAA.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=6 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=7 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=7 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Cache miss for api.dropboxapi.com IN A
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Firing regular transaction 56113 for <api.dropboxapi.com IN A> scope dns on */* (validate=yes).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Using feature level UDP+EDNS0 for transaction 56113.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Using DNS server 1.1.1.1 for transaction 56113.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Announcing packet size 1472 in egress EDNS(0) packet.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sending query packet with id 56113 of size 47.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Cache miss for api.dropboxapi.com IN AAAA
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Firing regular transaction 49563 for <api.dropboxapi.com IN AAAA> scope dns on */* (validate=yes).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Using feature level UDP+EDNS0 for transaction 49563.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Using DNS server 1.1.1.1 for transaction 49563.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Announcing packet size 1472 in egress EDNS(0) packet.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sending query packet with id 49563 of size 47.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.232 path=n/a interface=n/a member=n/a cookie=7 reply_cookie=6 signature=n/a error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.234' successfully installed.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Received dns UDP packet of size 123, ifindex=2, ttl=0, fragsize=0, sender=1.1.1.1, destination=192.168.1.113
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Processing incoming packet of size 123 on transaction 56113 (rcode=SUCCESS).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Not caching zero TTL cache entry: api.dropboxapi.com IN CNAME
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Not caching zero TTL cache entry: api.dropbox.com IN CNAME
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Not caching zero TTL cache entry: api-env.dropbox-dns.com IN A
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Regular transaction 56113 for <api.dropboxapi.com IN A> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Received dns UDP packet of size 135, ifindex=2, ttl=0, fragsize=0, sender=1.1.1.1, destination=192.168.1.113
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Processing incoming packet of size 135 on transaction 49563 (rcode=SUCCESS).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Added positive unauthenticated non-confidential cache entry for api.dropboxapi.com IN CNAME 12s on enp4s0/INET/1.1.1.1
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Added positive unauthenticated non-confidential cache entry for api.dropbox.com IN CNAME 12s on enp4s0/INET/1.1.1.1
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Added positive unauthenticated non-confidential cache entry for api-env.dropbox-dns.com IN AAAA 12s on enp4s0/INET/1.1.1.1
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Regular transaction 49563 for <api.dropboxapi.com IN AAAA> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Freeing transaction 56113.
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sent message type=error sender=n/a destination=:1.234 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Lookup failed due to system error: Invalid argument
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=9 reply_cookie=0 signature=s error-name=n/a error-message=n/a
    Feb 01 11:46:06 nick-arch-home systemd-resolved[37431]: Freeing transaction 49563.
    Feb 01 11:46:18 nick-arch-home systemd-resolved[37431]: Bus bus-api-resolve: changing state RUNNING → CLOSED
    Feb 01 11:46:18 nick-arch-home systemd-resolved[37431]: Removing scope on link enp4s0, protocol llmnr, family AF_INET
    Feb 01 11:46:18 nick-arch-home systemd-resolved[37431]: Removing scope on link enp4s0, protocol llmnr, family AF_INET6
    Feb 01 11:46:18 nick-arch-home systemd-resolved[37431]: Removing scope on link *, protocol dns, family *

I don't know if this helps much, but here's the `dig` and `traceroute` when it works:
    
    $ dig api.dropboxapi.com

    ; <<>> DiG 9.16.25 <<>> api.dropboxapi.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32480
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 65494
    ;; QUESTION SECTION:
    ;api.dropboxapi.com.            IN      A

    ;; ANSWER SECTION:
    api.dropboxapi.com.     202     IN      CNAME   api.dropbox.com.
    api.dropbox.com.        0       IN      CNAME   api-env.dropbox-dns.com.
    api-env.dropbox-dns.com. 0      IN      A       162.125.4.19

    ;; Query time: 13 msec
    ;; SERVER: 127.0.0.53#53(127.0.0.53)
    ;; WHEN: Tue Feb 01 11:54:08 EST 2022
    ;; MSG SIZE  rcvd: 123

    $ traceroute api.dropboxapi.com
    traceroute to api.dropboxapi.com (162.125.4.19), 30 hops max, 60 byte packets
     1  _gateway (192.168.1.1)  0.262 ms  0.298 ms  0.343 ms
     2  96.120.75.49 (96.120.75.49)  9.556 ms  9.617 ms  16.469 ms
     3  68.85.116.45 (68.85.116.45)  16.599 ms  16.560 ms  16.618 ms
     4  be-94-ar03.plainfield.nj.panjde.comcast.net (96.108.51.53)  18.497 ms  18.396 ms  18.484 ms
     5  be-31133-cs03.newark.nj.ibone.comcast.net (96.110.42.41)  19.462 ms be-31123-cs02.newark.nj.ibone.comcast.net (96.110.42.37)  19.343 ms *
     6  * be-1411-cr11.newark.nj.ibone.comcast.net (96.110.35.78)  15.505 ms be-1211-cr11.newark.nj.ibone.comcast.net (96.110.35.70)  13.921 ms
     7  be-301-cr12.newyork.ny.ibone.comcast.net (96.110.36.146)  13.778 ms be-304-cr12.newyork.ny.ibone.comcast.net (68.86.84.246)  18.721 ms  18.791 ms
     8  be-1212-cs02.newyork.ny.ibone.comcast.net (96.110.35.133)  35.729 ms be-1312-cs03.newyork.ny.ibone.comcast.net (96.110.35.137)  19.767 ms be-1412-cs04.newyork.ny.ibone.comcast.net (96.110.35.141)  19.647 ms
     9  be-4101-pe01.60hudson.ny.ibone.comcast.net (96.110.41.146)  18.760 ms  18.844 ms be-4301-pe01.60hudson.ny.ibone.comcast.net (96.110.41.154)  18.811 ms
    10  96-87-10-94-static.hfc.comcastbusiness.net (96.87.10.94)  25.585 ms  25.681 ms *
    11  * ae4-jfk1-ea01.net.dropbox.com (162.125.0.1)  13.766 ms  19.646 ms
    12  162.125.4.19 (162.125.4.19)  13.795 ms  14.670 ms  18.849 ms

**Comment by eworm-de** [comment]
Probably another duplicate of #20617...

**Comment by nandryshak** [comment]
> Probably another duplicate of #20617...

Yes I think so, thanks, I must've missed that one in my search. I'll close this.

**Comment by eworm-de** [comment]
Well possibly different cause with same symptoms... Can you confirm whether or not you use Cloudflare DNS?

**Comment by nandryshak** [comment]
> Well possibly different cause with same symptoms... Can you confirm whether or not you use Cloudflare DNS?

I do, yes. When I read through the issue, it looked exactly the same as mine.
