### ISSUE TITLE
RFE: ability to create externally controlled tunnels

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#22352]
**Describe the solution you'd like**
Additional .netdev options/properties that would generate an externally controlled tunnel. I noticed there are also restrictions currently on ip6tnl in systemd-networkd where we need to provide `Local=` and `Remote=` but in the desired state these would be `::` (is this the same as "any" in systemd-networkd?). This could also be a separate RFE for this issue to allow `Local=` and `Remote=` to be `::` for this purpose. In the next section I paste a command, but the ideal end state is to generate the following:
```
# ip -d link show tunlany0
4: tunlany0@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: promiscuity 0
    ip6tnl external addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
# ip -6 tun
tunlany0: any/ipv6 remote :: local :: encaplimit 0 hoplimit inherit tclass 0x00 flowlabel 0x00000 (flowinfo 0x00000000)
tunlany0: any/ipv6 remote :: local :: encaplimit 0 hoplimit inherit tclass 0x00 flowlabel 0x00000 (flowinfo 0x00000000)
```

**Describe alternatives you've considered**
I can run `ip link add tunlany0 type ip6tnl external` separately to create the device and then use .network files to configure it. But that's silly when it could be part of .netdev.

**The systemd version you checked that didn't have the feature you are asking for**
249

cc @yuwata for thoughts

**Comment by yuwata** [comment]
@anitazha You mean, `Local=::` and/or `Remote=::` do not work?

**Comment by yuwata** [comment]
Ah, 'external' case, tunnel should be created without local or remote address.

**Comment by yuwata** [comment]
@anitazha The external mode support is waiting in #22355.

ip-link(8) mentions `ip route encap`, but we have not implemented that feature on routes. What is your usecase? Do you also want encap support?

**Comment by anitazha** [comment]
Thanks for getting to this so quickly @yuwata!

We're only using this in ingress traffic so we don't need encap support on routes. Maybe in the future but no one has mentioned wanting it yet. I'll take a look at the PR.

**Comment by yuwata** [comment]
> We're only using this in ingress traffic so we don't need encap support on routes. Maybe in the future but no one has mentioned wanting it yet.

Thanks. OK. Let's add encap support when we get a request.
