### ISSUE TITLE
How to wait for non-root-user accessible tap devices

### ISSUE THREAD

**Issue by poidl** [systemd/systemd#22364]
I'm a beginner trying to start qemu on boot as a non-root user with tap devices. The non-root user is granted access to the tap devices in `.netdev` via the `User=` and `Group=` directives. 

I get an error message:

```
could not configure /dev/net/tun (lan0): Operation not permitted
```

I found I can solve this by adding 

```
[Unit]
After=sys-devices-virtual-net-IFNAME.device
Wants=sys-devices-virtual-net-IFNAME.device
```

where IFNAME is the tap device name. But this is cumbersome, because I need to hard-code all the interface names into the service files of the qemu instances.

The question is: Is there a better solution? Should I put all the  user-owned tap devices into one single service and then require this same service in all my qemu instances? Is there some sort of target I can wait for, after which I can be sure that non-root users can access the tun/tap devices?

I tried the `network-online.target`, but it takes much longer and I want the VM to start up quickly (i.e. before network-online.target is reached).

Thanks a lot for your help.

**Comment by yuwata** [comment]
How about to edit the systemd-networkd-wait-online.service like the following?
```
$ sudo systemctl edit systemd-networkd-wait-online.service
# /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i tun0:carrier -i tun1:carrier
```
Please replace `tun0` or `tun1` in the above with your actual tun/tap interface name, and tune `carrier` to other values you want.

Then, set the following
```
Want=network-online.target
After=network-online.target
```
to the services which requires the tun/tap interfaces.

------
BTW, it seems this is neither an issue report nor a RFE. Closing.

**Comment by poidl** [comment]
Thanks for your reply!

> Please replace tun0 or tun1 in the above with your actual tun/tap interface name, and tune carrier to other values you want.

Ok, so (if I understand correctly) I would still have to hard-code all the tun/tap interface names into the file. But yes it's an improvement because it's just one centralized file. Thanks for the suggestion.

> BTW, it seems this is neither an issue report nor a RFE. Closing.

Sorry I won't ask any more questions in the issue tracker.
