### ISSUE TITLE
#20833 must be reverted (OnFailure=/OnSuccess= metadata propagation)

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22370]
#20833 contains non-trivial to fix memory corruptions, see my comments there. THis needs some more rounds of review. I would have posted a revert PR, but it already got changed since, hence this issue instead.

This really isn't ready for release, and is a blocker issue hence.

**Comment by bluca** [comment]
Follow-ups here: https://github.com/systemd/systemd/pull/22378
For the rest, see comments on #20833

**Comment by poettering** [comment]
#22378 addressed some of the issues that need fixing, but not all. Hence reopening.

**Comment by poettering** [comment]
So I think there's some major disconnect in the discussions here. The current implementation focusses on a model where a single service unit processes OnFailure=/OnSuccess= events for a multitude of services. The problems I see all stem from that idea, i.e. the fact that the linked list will trigger a memory corruption in some cases (or that we need the linked list at all), and that events will be lost, if the handler service is already started when another unit requesting it sends out an event too, or that the environment vairable is so hard to process.

The model I always had in mind for this is that each service that shall be monitored this way will get its own private *instance* of a monitoring service. That removes *all* these issues: things become vastly simpler, we don't need linked lists, no complex env vars and we events will not get lost anymore.

i.e I think if you have a service foobar.service you want to monitor for failures you'd add a OnFailure=mymonitor@%N.service to it. If you have an instanced service quux@waldo.service you want to monitor you'd instead use OnFailure=mymonitor@%p-%i.service or so.

You then define mymonitor@.service as generic template unit that would get instantiated once for each failure service, and would get passed in the failure data as env var, without any ambiguities or complex way to parse things.

So hence, what's the rationale for the approach that was merged? Can we just rework the way I propose above? To me it appears quite clearly as the safer, cleaner approach.

**Comment by poettering** [comment]
or to elaborate on this, the usecase I thought this was for was for people who want to hook failing services to an automated email. i.e. with the design I suggested you'd be able to put together a script like this:

```sh
#!/bin/sh

(
    cat <<EOF
I am sorry to report that unit $MONITOR_UNIT on $HOSTNAME failed.

Service Status
--------------
EOF

    systemctl status $MONITOR_UNIT
    cat <<EOF

Execution Environment
---------------------
EOF

    export
) | mail admin@example.com -s "Unit $MONITOR_UNIT on $HOSTNAME failed!"
```

And then, wrap that in a service mymonitor@.service and there you go, you get an email about every failure you OnFailure=-link this template into. This is dead simple. Any approach that tries to multiplex failures from a multitude of services into a single handler service requires much more complex handling...

**Comment by bluca** [comment]
Do you have a reproducer for the memory corruption issue you mention?

The current implementation will work in both the way you describe (with an instance) and without. It seems a pity to me to remove functionality given it's there, documented, tested, and it works, but if you feel strongly about it, feel free to send a PR to do so.

**Comment by poettering** [comment]
> Do you have a reproducer for the memory corruption issue you mention?

Adding an item into mltiple linked lists as implemented by the `list.h` macros simply does not work, and is not supported. Hence, reading the code: just define a unit with OnFailure= onto two other units, trigger it, and see how things go south. Because that would mean the Unit object would be linked into two Job objects, right? And Boom!

> The current implementation will work in both the way you describe (with an instance) and without. It seems a pity to me to remove functionality given it's there, documented, tested, and it works, but if you feel strongly about it, feel free to send a PR to do so.

No it does not work. the lists thing doesn't work, and even if you don't trigger use that, then the fact that failure events will be lost if they happen while the monitor service is already started is just buggy behaviour. i.e. if you have both `foo.service` and `bar.service` both have `OnFailure=mymonitor.service`, and then `foo.service` fails and thus causes `mymonitor.service` to be started, which will work, and get the metadata passed in via an env var. Now `mymonitor.service` is a bit slow in what it does, maybe a Python script on an overloaded machine, talking to some external system which is slow. So it takes a couple of seconds to complete. Now, as result of `foo.service` failing `bar.service` also starts to fail. Now this causes `mymonitor.service` to be started – but it already is running! So the start request has no effect and noone will ever take notice of this second service failing, or collect the metadata.

So no, this PR does *not* work. 

And besides that, I wouldn't know how to parse the complex env var in simple shell. I.e. how would go for writing that simple shell script I showed above if you get a bunch of fields all in one for a variety of services.

**Comment by bluca** [comment]
I can't manage to cause any crashes. The references saved in the list are not modified at all from the list itself, and the atoms ensure they are always around, so the pointers are still valid.

But anyway, it's moot, here's a PR to do the change as requested: https://github.com/systemd/systemd/pull/22460
