### ISSUE TITLE
udev: Support for setting MDI-X state in .link files

### ISSUE THREAD

**Issue by GitArUs** [systemd/systemd#22386]
Low priority (very rarely needed).
If it is possible I would like to be able to set mdi-x state in similar way as speed/duplex can be set. Classic nework scripts (like in Fedora) allow to specify ethtool options in configuration file (ifcfg-xxx) in convenient way (ETHTOOL_OPTS="mdix on").

**Describe the solution you'd like**
Something like MdiX=auto|off|on in [Link] section would be great.

**Describe alternatives you've considered**
Alternatives considered:
- udev rule calling ethtool
- custom .service started after network-online.target calling ethtool
- calling ethtool in rc.local or other startup script

**The systemd version you checked that didn't have the feature you are asking for**
Feature does not exist in systemd-networkd-249.6-2.fc35.x86_64

**Comment by yuwata** [comment]
Waiting in #22415.
