### ISSUE TITLE
resolved: new handling of root domain looks wrong

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22401]
This is mostly a tracking bug because I think #22231 isn't right. i.e. it should probably only synthesize NXDOMAIN for A/AAAA lookups in the root zone, but let all other root zone lookups through as is, so that DNSSEC can work.

But I didn't test this, this is just an issue I am pretty sure exists, based on looking at the change.

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #22414.
