### ISSUE TITLE
portbled's new  GetImageMetadataWithExtensions() method's parameter list should be normalized

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22404]
See my comments on:

https://github.com/systemd/systemd/pull/22245#pullrequestreview-872177184

**Comment by bluca** [comment]
Copying comment from the PR:

> Looks conceptually OK, but please let's fix the the method parameters: don't shove unrelated data through existing parameters. It sucks that D-Bus method parameter lists are not reasonably extensible, but it is what it is, and let's not resort to tricks like overloading existing parameters with different meanings depending on some flag.
> 
> Hence, please add a new superset method for this.

The problem is that this is how it should have been from the beginning - so if anything, I'd prefer to break compatibility, but that's nasty. I don't think it makes much sense to have a GetImageMetadataWithExtensionsWithExtensions, it just looks like a copypasta...
