### ISSUE TITLE
networkd: ipv6 privacy extensions don't work in v228

### ISSUE THREAD

**Issue by worldowner** [systemd/systemd#2242]
I have configured privacy extensions for IPv6:

```
# cat /etc/sysctl.d/40-ipv6.conf
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
net.ipv6.conf.enp5s0.use_tempaddr = 2

# cat /etc/systemd/network/wired.network
[Match]
Name=enp5s0

[Network]
DHCP=ipv4
IPv6PrivacyExtensions=true
```

IPv6 address is set but only SLAAC, there is no temporary address set on the interface:

```
# ip -6 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
inet6 2002:5940:ff:ff:fff:ff:ff::ff/64 scope global noprefixroute dynamic
valid_lft 86397sec preferred_lft 14397sec
inet6 fe80::22cf:30ff:fef5:5be1/64 scope link
valid_lft forever preferred_lft forever
```

What is shown above is related to systemd-228. When I downgraded to 227 everything works fine. I also have another machine in the same network which doesn't use systemd-networkd and its network is configured by NetworkManager and it also is fine.

**Comment by jonathanio** [comment]
I noted the same issue yesterday in #1982: The issue appears to be that from systemd-228 a DHCPv6 client is forcefully started as soon as RAs are received and takes cover control from the kernel. This client appears to have major deficiencies in processing.

In this case when it adds the address it doesn't honour the `use_tempaddr` kernel setting, nor the `IPv6PrivacyExtensions` setting in the `.network` file. As such the `mngtmpaddr` is not being set as a flag on the address and the kernel cannot use it as the base value from which to generate new private addresses.

In theory you can get around it by running:

```
ip addr change 2002:5940:ff:ff:fff:ff:ff::ff/64 dev enp5s0 mngtmpaddr noprefixroute
```

but this is by no means an ideal or long-running option.

The DHCPv6 client needs to be disabled unless specifically set regardless of whether it is able to properly deal with this setting, or some of the issues I've seen within VMs. It is at this point I believe a less-than minimum viable product that shouldn't have left the alpha stage, let alone to be automatically enabled without the ability to control it.
