### ISSUE TITLE
glibc 2.35 installed but systemd ask again POSIX caps headers

### ISSUE THREAD

**Issue by Azaretdodo** [systemd/systemd#22429]
**systemd version the issue has been seen with**
 >v 250

**Used distribution**
 >ubuntu focal

**Linux kernel version used** (`uname -a`)

 > 5.13.0-27-generic

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > systemd sucess to install

**Unexpected behaviour you saw**
 > Has header "sys/capability.h" : NO 

meson.build:684:8: ERROR: Problem encountered: POSIX caps headers not found

**Steps to reproduce the problem**
 > meson build && make && make install

**Additional program output to the terminal or log subsystem illustrating the issue**

```
[meson-log.txt](https://github.com/systemd/systemd/files/8007823/meson-log.txt)

…
```

**Comment by mrc0mmand** [comment]
The `/usr/include/sys/capability.h` is provided by `libcap-devel`, not `glibc`.
