### ISSUE TITLE
Keyboard does not work in systemd-boot

### ISSUE THREAD

**Issue by nl6720** [systemd/systemd#22428]
**systemd version the issue has been seen with**
 > systemd 250 (250.3-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux archiso 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Keyboard input working in systemd-boot.

**Unexpected behaviour you saw**
 > Keyboard input did not work in systemd-boot. Pressing any key stops the boot timeout, but that's all that happens. No other interaction is possible. Nothing happens when arrow keys, `e`, or any other key is pressed.
> This was observed on HP ProBook 450 G2 with firmware version 01.54. Another Arch user also encountered the issue on a 2016 macbook air; see https://bbs.archlinux.org/viewtopic.php?id=273765 .

**Steps to reproduce the problem**
 > Boot `archlinux-2022.01.01-x86_64.iso` or `archlinux-2022.02.01-x86_64.iso` and try pressing keys when in systemd-boot.

**Additional program output to the terminal or log subsystem illustrating the issue**

Bisecting yields e628944b11a3465b77bcd704f9fb66b58757df01 as the offending commit.

**Comment by medhefgo** [comment]
Can you give this [branch](https://github.com/medhefgo/systemd/tree/boot-input) a try?

**Comment by nl6720** [comment]
> Can you give this [branch](https://github.com/medhefgo/systemd/tree/boot-input) a try?

Tried it. No change with 87528e11281d41484fd28fe1b2dbbe2f8bbfadf3.

**Comment by medhefgo** [comment]
Time will tell if I'll ever get UEFI input to work for everyone or if I go insane first…

I wonder if you were also affected by https://github.com/systemd/systemd/issues/19191 at the time?

I have quite a few things I'd love to try, but it's easier when I don't have to do it by proxy. With luck I can get my hands on a ProBook next week to poke at this myself.

**Comment by nl6720** [comment]
I don't recall having that issue. Then again, I don't use systemd-boot as my boot loader. My only interaction with it is via archiso.

**Comment by amidonc** [comment]
this also happens to me on my HP Elitebook 8470p
boots if I let it count down, freezes when I press any key.
Same issue with a USB keyboard plugged in
Without a usb keyboard plugged in, freezes after keypress, the only way to reboot is by holding down the power button to turn off.
When a USB keyboard is plugged in, freezes after keypress,  ctl-alt-delete works correctly on BOTH keyboards (reboots system)

This also happens when booting off the archiso

**Comment by nl6720** [comment]
With ae35d93a26bea1821d49fc90b8a7ffb29f1fd27c, the keyboard still didn't work, but I got:
```
ConIn: 2147768800
ConInEx: 0
ExtraConInEx: 0
```

After pressing a key once, it looped with:

```
Ready 0: 1 (ConIn*: Success) (ConInEx: 0000000A) (ExtraConInEx: 0000000A)


Ready 1: 1 (ConIn*: Success) (ConInEx: 0000000A) (ExtraConInEx: 0000000A)


Ready 2: 1 (ConIn*: Success) (ConInEx: 0000000A) (ExtraConInEx: 0000000A)
...
```

`test-conin.efi` produced `Success Success` on each keypress in the `ConIn>` prompt.
`test-coninex.efi` and `test-extraconinex.efi` exited upon launch.

**Comment by medhefgo** [comment]
The linked PR should fix this embarrassing mistake. Pleas give it a try.

**Comment by nl6720** [comment]
It works! 🎉
