### ISSUE TITLE
`assert_return` should probably be turned into `assert` on the CI

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#22425]
Turns out some projects like NetworkManager turn `assert_return` into `abort` when their tests are run and that helps to uncover various issues like https://github.com/systemd/systemd/pull/22406#issuecomment-1029391091. Issues like https://github.com/systemd/systemd/commit/26a63b81322a3bd8b9fbd43f75897c391708de2c could have been caught with the fuzzers and `abort` as well. To figure out what else breaks I added `assert` to `log_assert_failed_return` in https://github.com/systemd/systemd/pull/22413. The report with nice backtraces can be found at https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/9956/artifact//systemd-centos-ci/artifacts_pdsu40qu/vagrant-logs.bpb/vagrant-arch-testsuite.L8S/coredumpctl_collect_FAIL.log. I'm not sure how long logs are retained on CentOS CI so if they disappear I'll just force-push that PR to trigger it once again.

**Comment by mrc0mmand** [comment]
> I'm not sure how long logs are retained on CentOS CI so if they disappear I'll just force-push that PR to trigger it once again.

I marked the respective job as "Keep forever", so the artifacts shouldn't disappear (the retention policy is otherwise 30 days).

**Comment by evverx** [comment]
@mrc0mmand thanks! FWIW Looking at the log it seems `systemd-coredump` somehow fails to unwind backtraces:
```
                #0  0x00007f9d026ebd22 raise (libc.so.6 + 0x3cd22)
                #1  0x00007f9d026d5862 abort (libc.so.6 + 0x26862)
                #2  0x00007f9d02a2417d n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x18517d)
                #3  0x00007f9d02ae57fd n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x2467fd)
                #4  0x00007f9d02ae8329 n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x249329)
                #5  0x00007f9d02ac20ec n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x2230ec)
                #6  0x00007f9d02ac272b n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x22372b)
                #7  0x0000560c062dc06c write_to_journal (systemd-journald + 0xf06c)
                #8  0x0000560c062de711 dispatch_message_real (systemd-journald + 0x11711)
                #9  0x0000560c062de9de server_driver_message (systemd-journald + 0x119de)
                #10 0x0000560c062d5840 main (systemd-journald + 0x8840)
                #11 0x00007f9d026d6b25 __libc_start_main (libc.so.6 + 0x27b25)
                #12 0x0000560c062d532e _start (systemd-journald + 0x832e)
```
even though `gdb` seems to have no problem with them
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f9d026ebd22 in raise () from /usr/lib/libc.so.6
(gdb) Load new symbol table from "/systemd-meson-build/systemd-journald"? (y or n) [answered Y; input not from terminal]
Reading symbols from /systemd-meson-build/systemd-journald...
(gdb) 
Thread 1 (Thread 0x7f9d01d68e80 (LWP 18)):
#0  0x00007f9d026ebd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f9d026d5862 in abort () from /usr/lib/libc.so.6
#2  0x00007f9d02a2417d in log_assert_failed_return (text=text@entry=0x7f9d02b5beb0 "s->event->state != SD_EVENT_FINISHED", file=file@entry=0x7f9d02b5b7c1 "src/libsystemd/sd-event/sd-event.c", line=line@entry=2629, func=func@entry=0x7f9d02b5ad30 <__PRETTY_FUNCTION__.68> "sd_event_source_set_time") at ../build/src/basic/log.c:886
#3  0x00007f9d02ae57fd in sd_event_source_set_time (s=s@entry=0x560c06d5b7a0, usec=2377405548) at ../build/src/libsystemd/sd-event/sd-event.c:2629
#4  0x00007f9d02ae8329 in sd_event_source_set_time_relative (s=0x560c06d5b7a0, usec=<optimized out>) at ../build/src/libsystemd/sd-event/sd-event.c:2657
#5  0x00007f9d02ac20ec in schedule_post_change (f=f@entry=0x560c06d6d830) at ../build/src/libsystemd/sd-journal/journal-file.c:1947
#6  0x00007f9d02ac272b in journal_file_append_entry (f=0x560c06d6d830, ts=<optimized out>, ts@entry=0x7fffa894db20, boot_id=boot_id@entry=0x0, iovec=iovec@entry=0x7fffa894de00, n_iovec=<optimized out>, n_iovec@entry=20, seqnum=seqnum@entry=0x7fffa894ebf0, ret=<optimized out>, ret_offset=<optimized out>) at ../build/src/libsystemd/sd-journal/journal-file.c:2092
#7  0x0000560c062dc06c in write_to_journal (s=s@entry=0x7fffa894eb30, uid=0, iovec=iovec@entry=0x7fffa894de00, n=20, priority=priority@entry=6) at ../build/src/journal/journald-server.c:844
#8  0x0000560c062de711 in dispatch_message_real (s=s@entry=0x7fffa894eb30, iovec=iovec@entry=0x7fffa894de00, n=<optimized out>, m=m@entry=62, c=0x560c06d4f350, tv=tv@entry=0x0, priority=<optimized out>, object_pid=<optimized out>) at ../build/src/journal/journald-server.c:1028
#9  0x0000560c062de9de in server_driver_message (s=s@entry=0x7fffa894eb30, object_pid=object_pid@entry=0, message_id=message_id@entry=0x560c062ee1b0 "MESSAGE_ID=d93fb3c9c24d451a97cea615ce59c00b", format=format@entry=0x560c062ee211 "MESSAGE=Journal stopped") at ../build/src/journal/journald-server.c:1062
#10 0x0000560c062d5840 in main (argc=<optimized out>, argv=<optimized out>) at ../build/src/journal/journald.c:129
```

**Comment by mrc0mmand** [comment]
> @mrc0mmand thanks! FWIW Looking at the log it seems `systemd-coredump` somehow fails to unwind backtraces:
> 
> ```
>                 #0  0x00007f9d026ebd22 raise (libc.so.6 + 0x3cd22)
>                 #1  0x00007f9d026d5862 abort (libc.so.6 + 0x26862)
>                 #2  0x00007f9d02a2417d n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x18517d)
>                 #3  0x00007f9d02ae57fd n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x2467fd)
>                 #4  0x00007f9d02ae8329 n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x249329)
>                 #5  0x00007f9d02ac20ec n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x2230ec)
>                 #6  0x00007f9d02ac272b n/a (/usr/lib/systemd/libsystemd-shared-250.so + 0x22372b)
>                 #7  0x0000560c062dc06c write_to_journal (systemd-journald + 0xf06c)
>                 #8  0x0000560c062de711 dispatch_message_real (systemd-journald + 0x11711)
>                 #9  0x0000560c062de9de server_driver_message (systemd-journald + 0x119de)
>                 #10 0x0000560c062d5840 main (systemd-journald + 0x8840)
>                 #11 0x00007f9d026d6b25 __libc_start_main (libc.so.6 + 0x27b25)
>                 #12 0x0000560c062d532e _start (systemd-journald + 0x832e)
> ```
> 
> even though `gdb` seems to have no problem with them
> 
> ```
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> Core was generated by `/usr/lib/systemd/systemd-journald'.
> Program terminated with signal SIGABRT, Aborted.
> #0  0x00007f9d026ebd22 in raise () from /usr/lib/libc.so.6
> (gdb) Load new symbol table from "/systemd-meson-build/systemd-journald"? (y or n) [answered Y; input not from terminal]
> Reading symbols from /systemd-meson-build/systemd-journald...
> (gdb) 
> Thread 1 (Thread 0x7f9d01d68e80 (LWP 18)):
> #0  0x00007f9d026ebd22 in raise () from /usr/lib/libc.so.6
> #1  0x00007f9d026d5862 in abort () from /usr/lib/libc.so.6
> #2  0x00007f9d02a2417d in log_assert_failed_return (text=text@entry=0x7f9d02b5beb0 "s->event->state != SD_EVENT_FINISHED", file=file@entry=0x7f9d02b5b7c1 "src/libsystemd/sd-event/sd-event.c", line=line@entry=2629, func=func@entry=0x7f9d02b5ad30 <__PRETTY_FUNCTION__.68> "sd_event_source_set_time") at ../build/src/basic/log.c:886
> #3  0x00007f9d02ae57fd in sd_event_source_set_time (s=s@entry=0x560c06d5b7a0, usec=2377405548) at ../build/src/libsystemd/sd-event/sd-event.c:2629
> #4  0x00007f9d02ae8329 in sd_event_source_set_time_relative (s=0x560c06d5b7a0, usec=<optimized out>) at ../build/src/libsystemd/sd-event/sd-event.c:2657
> #5  0x00007f9d02ac20ec in schedule_post_change (f=f@entry=0x560c06d6d830) at ../build/src/libsystemd/sd-journal/journal-file.c:1947
> #6  0x00007f9d02ac272b in journal_file_append_entry (f=0x560c06d6d830, ts=<optimized out>, ts@entry=0x7fffa894db20, boot_id=boot_id@entry=0x0, iovec=iovec@entry=0x7fffa894de00, n_iovec=<optimized out>, n_iovec@entry=20, seqnum=seqnum@entry=0x7fffa894ebf0, ret=<optimized out>, ret_offset=<optimized out>) at ../build/src/libsystemd/sd-journal/journal-file.c:2092
> #7  0x0000560c062dc06c in write_to_journal (s=s@entry=0x7fffa894eb30, uid=0, iovec=iovec@entry=0x7fffa894de00, n=20, priority=priority@entry=6) at ../build/src/journal/journald-server.c:844
> #8  0x0000560c062de711 in dispatch_message_real (s=s@entry=0x7fffa894eb30, iovec=iovec@entry=0x7fffa894de00, n=<optimized out>, m=m@entry=62, c=0x560c06d4f350, tv=tv@entry=0x0, priority=<optimized out>, object_pid=<optimized out>) at ../build/src/journal/journald-server.c:1028
> #9  0x0000560c062de9de in server_driver_message (s=s@entry=0x7fffa894eb30, object_pid=object_pid@entry=0, message_id=message_id@entry=0x560c062ee1b0 "MESSAGE_ID=d93fb3c9c24d451a97cea615ce59c00b", format=format@entry=0x560c062ee211 "MESSAGE=Journal stopped") at ../build/src/journal/journald-server.c:1062
> #10 0x0000560c062d5840 in main (argc=<optimized out>, argv=<optimized out>) at ../build/src/journal/journald.c:129
> ```

Yeah, that's "expected", since the coredump is from a test VM (TEST-01-BASIC's VM in this particular case), so when we try to process it on the host, it tries to load the respective binaries and DSO's from the same paths as in the VM (obviously), i.e. `/usr/lib/systemd/systemd-journald`, etc. However, in the sanitizer runs we don't install the sanitized built on the host machine (for stability reasons), so the `/usr/lib/systemd/systemd-journald` binary is the "system" version, not the just-built version.

For that reason I added a "kludge"[0], which tries to find the the gdb'ed binary in the `$BUILD_DIR` (if set), and if found, it tells gdb to load the symbol table from it. That makes the backtraces in gdb "pretty", but `coredumpctl` still shows the original unsymbolized backtrace, which might be a bit confusing.

[0] https://github.com/systemd/systemd-centos-ci/blob/fb7d2895f20c2c9c3d847e28e49dc635357a4799/common/utils.sh#L345-L359

**Comment by evverx** [comment]
@mrc0mmand got it. Thanks!

I think summaries like
```
 362/1293 test-journal-match                                                                                                              FAIL           0.03s (killed by signal 6 SIGABRT)
```
are confusing :-) Backtraces on CentOS CI are actionable and helpful. Thanks for making them even more helpful with gdb!

**Comment by evverx** [comment]
I think I forgot to close this.
