### ISSUE TITLE
user services trigger "writing oom_score_adj error: Permission denied"

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#22437]
Version: v250

Originally filed as downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004543

It appears that starting with v250, quite a few user (all?) services now trigger an error message like this:

```
Jan 29 18:13:41 tucano dbus-daemon[5321]: [session uid=1000 pid=5321] Activating service name='org.freedesktop.Notifications' requested by ':1.47' (uid=1000 pid=6705 comm="/opt/telegram/telegram -workdir /home/pot/.Telegra")                                                                                            
Jan 29 18:13:41 tucano dbus-daemon[3502832]: writing oom_score_adj error: Permission denied       
```

```
$ journalctl -b --user | grep -A2 "writing oom_score_adj" | wc -l
190
```

Copying @luebking ' s response from a related issue (which was mistakenly deleted)

[ce7de0b#diff-c981a30c0e7b420b0ba50ce7d1d4174a511fdf20567b852ab02c774cb9a3591e](https://github.com/systemd/systemd/commit/ce7de0ba8ef355c5119e7dffc46e075b257dc90d#diff-c981a30c0e7b420b0ba50ce7d1d4174a511fdf20567b852ab02c774cb9a3591e) tries to set the score adjustment to 100 but it would seem that OOMScoreAdjust actually stacks values instead of controlling them so you end up w/ 200 on the session bus and that seems inherited by dbus activated services in some privileged manner and subsequent efforts to change the value to anything lower fail w/ the reported error.

Reverting the commit therefore prevents the error.

The warning for OOMScoreAdjust seems ok in general (to inform the author of the unit of the failure) but the general behavior is off and it would seem that this also only exposes an underlying bug about the behavior of OOMScoreAdjust

I'll update this week and take a closer look locally just for curiosity if you don't figure it yourself

**Comment by poettering** [comment]
these are log messages from traditional dbus-daemon which sets these on its own and logs about it. the issue is pretty much cosmetical though.

dbus-daemon should not try to reset the score adjust to 0 really.

Anyway, please report dbus-daemon, we can't do much about it.

You can of course in Debian undo the OOMScoreAdjust=100 setting in user@.service, if the cosmetic log message is such a biggie and you can't fix dbus-daemon for some reason, but that just hides the issue, makes actual runtime behaviour and is definitely something we shouldn't do upstream.

**Comment by poettering** [comment]
Here's where dbus-daemon tries to adjust the score, and logs but proceeds:

https://github.com/freedesktop/dbus/blob/master/dbus/dbus-spawn-unix.c#L1450

**Comment by poettering** [comment]
here's the commit they added this in:

https://github.com/freedesktop/dbus/commit/2fe59f1892825ced87c45ae25d9f5795b1d735b6

It appears this is only supposed to be run in the system instance of dbus (where the privs exist to reset the oom adjust value). However, this is also attempted when run without privs for the user instance. Which doesn't look right.

Also note this is only done for legacy services that do not have native systemd service files.

Either way, probably time to loop in @smcv.

And @mbiebl can you file this as bug against dbus-daemon?

**Comment by smcv** [comment]
This is already https://gitlab.freedesktop.org/dbus/dbus/-/issues/374, no new issue needed. Merge requests welcome!
