### ISSUE TITLE
journalctl --list-boots broken since 250.3

### ISSUE THREAD

**Issue by Nudin** [systemd/systemd#22431]
**systemd version the issue has been seen with**
> 250.3

**Used distribution**
> Arch Linux

**Linux kernel version used** (`uname -a`)
> `Linux numberone 5.16.4-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 29 Jan 2022 19:08:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
Until systemd 250.2 the command `journalctl --list-boots` prints a table of all boots recorded in the journal. Starting with 250.3 I get `Failed to determine boots: No data available` instead. Temporary downgrading to 250.2 shows the information again. The data is therefore existent.

**Comment by yuwata** [comment]
cc @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
Are you able to send me the relevant journal files? I can't reproduce the issue on my own system journal. You can post an archive here in the issue or you can find my email on my github profile page if you don't want anyone else to have access to those files.

**Comment by DaanDeMeyer** [comment]
Thank you for providing the journal files! https://github.com/systemd/systemd/pull/22442 fixes the issue.
