### ISSUE TITLE
`Checking if "-Werror=shadow with local shadowing" : compiles: YES` contains unnecessary comma

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#22459]
In systemd 249 meson printed
> Checking if "-Werror=shadow with local shadowing" compiles: YES

In systemd 250 meson prints
> Checking if "-Werror=shadow with local shadowing" : compiles: YES

The new colon is superfluous.

**Comment by yuwata** [comment]
This is not our bug. Please contact to meson team.

**Comment by dilyanpalauzov** [comment]
Moved to https://github.com/mesonbuild/meson/issues/9974.

**Comment by eli-schwartz** [comment]
FTR: I tracked down the cause and submitted a Meson fix for this.
