### ISSUE TITLE
Service fails to start with SetCredentialEncrypted (243/CREDENTIALS)

### ISSUE THREAD

**Issue by jprestwo** [systemd/systemd#22466]
systemd version v250 (built from source)

Fedora kernel 5.11.22 (VM)

I am trying to use the LoadCredentialEncrypted feature. First I tried with my full service file, then again with a very minimal service to simplify things. Both result in the same failure, 243/CREDENTIALS, when starting the service. I've created this LoadCredentialEncrypted value using systemd-creds, basically using [Example 2](https://www.freedesktop.org/software/systemd/man/systemd-creds.html#:~:text=Example%C2%A02.%C2%A0Encrypt%20a%20password%20and%20include%20it%20in%20a%20unit%20file):

`systemd-ask-password -n | systemd-creds encrypt --name=foo-secret -p - -`

Which results in:

    SetCredentialEncrypted=foo-secret:  \
        Whxqht+dQJax1aZeCGLxmiAAAAABAAAADAAAABAAAADzL0OdGFAtK2mnVBMAAAAA2WKlo \
        MnzXmrj12pjB+SLuKttEyjZRn05KEhAw+mjrmjC5GMm57OQThuwyqx24oRg1SIjU4CbLk \
        K+

And my entire foo.service file:

    [Unit]
    Description=foo
    
    [Service]
    ExecStart=/bin/bash -c "echo hello"
    SetCredentialEncrypted=foo-secret: \
        Whxqht+dQJax1aZeCGLxmiAAAAABAAAADAAAABAAAADzL0OdGFAtK2mnVBMAAAAA2WKlo \
        MnzXmrj12pjB+SLuKttEyjZRn05KEhAw+mjrmjC5GMm57OQThuwyqx24oRg1SIjU4CbLk \
        K+
    
    [Install]
    WantedBy=multi-user.target

I start foo.server:

    systemctl start foo.service

And I get:

    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Trying to enqueue job foo.service/start/replace
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Installed new job foo.service/start as 13761
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Enqueued job foo.service/start as 13761
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Passing 0 fds to service
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: About to execute /bin/bash -c "echo hello"
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Forked /bin/bash as 19160
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Changed dead -> running
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Job 13761 foo.service/start finished, result=done
    Feb 09 11:05:15 localhost.localdomain systemd[1]: Started foo.
    Feb 09 11:05:15 localhost.localdomain systemd[19160]: Successfully forked off '(sd-mkdcreds)' as PID 19161.
    Feb 09 11:05:15 localhost.localdomain systemd[19161]: Mounting /dev (MS_REC|MS_SLAVE "")...
    Feb 09 11:05:15 localhost.localdomain systemd[19161]: Mounting ramfs (ramfs) on /dev/shm (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700")...
    Feb 09 11:05:15 localhost.localdomain systemd[19160]: (sd-mkdcreds) failed with exit status 1.
    Feb 09 11:05:15 localhost.localdomain systemd[19160]: foo.service: Failed to set up credentials: Protocol error
    Feb 09 11:05:15 localhost.localdomain systemd[19160]: foo.service: Failed at step CREDENTIALS spawning /bin/bash: Protocol error
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Child 19160 belongs to foo.service.
    Feb 09 11:05:15 localhost.localdomain systemd[1]: foo.service: Main process exited, code=exited, status=243/CREDENTIALS

I've also tried adding a sleep to the service so it wont exit immediately, same result.

**Comment by jdoss** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=2096857 and https://github.com/fedora-selinux/selinux-policy/pull/1295.

**Comment by CSharpTeoMan911** [comment]
The source of this issue seems to be the fact that the "commands/services"(scripts) are timed out by some unknown variables. The workaround this issue is to override the default service's configuration file and set it to restart if a fail occurs. In order to do this enter the command  "sudo systemctl edit [ your service name ]". After you've entered this command the configuration file will appear. 

Insert the lines bellow  in the [ Service ] section of the configuration file and save it:

Restart=on-failure
RestartSec=5s


You need to set the service to restart on failure at an interval of 5 seconds, otherwise an error telling you that the service is restarted to quickly will appear. I hope this will save people of the headaches that I had with this issue.
