### ISSUE TITLE
RFE: add functionality that can "destroy" TPM2 PCR values at some points of boot, by measuring random values into them, to ensure unlocking via PCR policies only works during specific boot phases

### ISSUE THREAD

**Issue by grigorig** [systemd/systemd#22478]
Hi,

I hope this isn't too much off topic, but I have some observations and possible concerns about the security model of TPM2 based disk encryption with systemd-cryptenroll. Here's a short story of what I discovered:

I use Fedora with systemd-boot and unified kernel images retrofitted. Fully verified boot process: secure boot enabled with my own PK/KEK/DB and signed kernel images. The root filesystem is automatically unlocked, which means the user space access controls are vital for protecting data.

Now, when booting a "recovery kernel" on Fedora, automatic disk decryption fails. The initramfs for these kernels is created with dracut with "rescue" module enabled and "nohostonly" mode enabled. The failure happens because the initramfs does not have crypttab with the `tpm2-device=auto` option. Likely because of the "nohostonly" mode, but it doesn't really matter.

Now, at this point, systemd-cryptsetup will ask me for a passphrase. If I provide the recovery phrase I've set up, it'll happily boot. So far, so good, that's expected! However, I can cancel the prompt (by pressing CTRL-C several times), and the decryption unit will fail. After some timeout (several minutes), dracut will drop me into a recovery shell! And lo and behold, the TPM2 PCR 7 will of course match to a regular boot. I can now manually start `systemd-cryptsetup` with `tpm2-device=auto` to decrypt the root filesystem, and access all of the data. That means I have effectively circumvented the full disk encryption!

This means that, essentially, a bug in any initramfs implementation can easily break encryption. How can we reasonably protect against such scenarios? In this specific case, there is an obvious fix: you can disable the recovery shell in dracut. However, bugs happen and might give users a shell. Hoping for the best that such bugs do not exist is not good enough in my opinion. I think `systemd-cryptsetup` (and initramfs infrastructure as well) needs to be more proactive to avoid such issues.

**Comment by grigorig** [comment]
It's just a random idea, but wouldn't it be possible to extend PCRs with random data in case of a failure in `systemd-cryptsetup` to make unsealing operations effectively useless afterwards?

**Comment by poettering** [comment]
The usual approach is to bind TPM2 unlocking to a set of PCRs that contain measurements of all allowed initrd/kernel combinations. YOu have to re-enroll then whenever you update kernel/initrd, and make sure to enroll all kernel/initrd combos you want to be able to use TPM2 unlocking.

**Comment by poettering** [comment]
That said, measuring random stuff into PCR to "destroy" the PCR values for the time being does make some sense to me. We can certainly convert this issue into an RFE to add a switch to crypttab that optionally allows measuring random data into a set of PCRs when cryptsetup exits.

**Comment by grigorig** [comment]
> The usual approach is to bind TPM2 unlocking to a set of PCRs that contain measurements of all allowed initrd/kernel combinations. YOu have to re-enroll then whenever you update kernel/initrd, and make sure to enroll all kernel/initrd combos you want to be able to use TPM2 unlocking.

I'm not sure - how would that help in the case of a buggy initramfs that inadvertently gives users a shell or something comparable? You usually don't know security bugs in advance, so of course the kernel/initramfs combination would be allowed.

I think an overarching issue is that the traditional initramfs implementations like dracut simply aren't designed with security in mind, but nonetheless systemd-cryptsetup could still be a bit more proactive in its security.

> We can certainly convert this issue into an RFE to add a switch to crypttab that optionally allows measuring random data into a set of PCRs when cryptsetup exits.

That sounds interesting, but in my specific case, it wouldn't help, since the initramfs was created without a proper crypttab. It would probably need to be more like a default behavior. That is, if decryption fails, there are tpm2 slots on the LUKS device, and there is a single TPM available, destroy PCR 7 (that one would probably suffice). However, maybe there are use cases where you wouldn't want that to happen, too.

**Comment by poettering** [comment]
Well, whether PCRs should be "destroyed" like that or not depends highly on the usecase of your system. i.e. typically if the kernel/initrd is measured into some PCR you might need to reenroll the TPM2 on kernel/initrd updates, and to do that you first need to unlock the encrypted root fs, to then re-encrypt the decryption key with the new PCR policy params. But that of course only works if the TPM2 still provides access to the original PCR data that is needed to unlock the root fs...

So it depends a lot on the usecase what the right policy here. Yes, in some cases it might make sense to cut off the original PCR values, but in others it might not, hence all we can provide is an option for this. And it probably has to be opt-in for compat.

**Comment by poettering** [comment]
This functionality probably shouldn't be in cryptsetup btw, since there might be multiple file systems bound to TPM2 and you want to destroy the PCRs only after you unlocked all of them. Hence this should be done in a service that is run after all that.

**Comment by grigorig** [comment]
Yeah maybe securing the initramfs framework is the better choice at least for the attack scenario outlined. For instance, dracut could simply disable the emergency shell when secure boot is enabled.

**Comment by grigorig** [comment]
FYI, this guide also recommends PCR extension after unlock:

https://www.intel.com/content/www/us/en/developer/articles/code-sample/protecting-secret-data-and-keys-using-intel-platform-trust-technology.html#inpage-nav-2-4

The solution proposed for handling changed PCR values is probably impractical for many scenarios, though.

**Comment by poettering** [comment]
So we nowadays measure unified kernels we boot into PCR 11 from sd-stub. Since nothing else uses PCR 1 we can thus pre-calculate the PCR value offline. Now, I think we should measure a fixed value into PCR 11 when transitioning from initrd into host. That means we can pre-calculate the PCR value we'll see in the initrd, and the one we'll see on the host. And this can then be used by LUKS policies to allow unlocking only in the initrd, or both in the initrd and from regular userspace (in the latter case we'd use a TPM2 OR policy between the two possible PCR value policies).

This would deliver everything we need, no?

**Comment by poettering** [comment]
Since #24771 we'll measure the "boot phase" into PCR 11 too, thus we have something to ensure secrets can only be unlocked during a specific boot phase. That should be enough to address the remaining issue.

Closing.
