### ISSUE TITLE
After updat systemd and polkit on debian 9 get : "Failed to get cgroup ID" in syslog

### ISSUE THREAD

**Issue by seruff84** [systemd/systemd#22483]
After updat systemd and polkit on debian 9 get : "Failed to get cgroup ID" in syslog

Linux 145101.local 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux

 Feb 11 13:13:02 145101 systemd[1]: user.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[1]: user-0.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[1]: user-runtime-dir@0.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user-runtime-dir@0.service, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[1]: user@0.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user@0.service, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[395316]: -.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user@0.service, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[395316]: app.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user@0.service/app.slice, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[395316]: dbus.socket: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user@0.service/app.slice/dbus.socket, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[395316]: -.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/user@0.service, ignoring: Operation not supported
Feb 11 13:13:02 145101 systemd[1]: session-1787.scope: Failed to get cgroup ID on cgroup /sys/fs/cgroup/user.slice/user-0.slice/session-1787.scope, ignoring: Operation not supported

**Comment by poettering** [comment]
You appear to use a pretty old kernel with a very new systemd. The message is purely cosmetical though.

**Comment by seruff84** [comment]
Thank you!
