### ISSUE TITLE
LimitNPROC with PrivateUsers is broken on Linux >=5.15.12

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#22494]
On Linux 5.15.12 and later, the following service:

```
[Service]
User=nobody
PrivateUsers=yes
LimitNPROC=4
Type=oneshot
ExecStart=/bin/true
```

Fails with:

```
Failed to execute /bin/true: Resource temporarily unavailable
Failed at step EXEC spawning /bin/true: Resource temporarily unavailable
Main process exited, code=exited, status=203/EXEC
```

(Even though user `nobody` has no running processes besides this one)

Further investigation suggests this is not a systemd bug but a Linux kernel regression. See https://bugzilla.kernel.org/show_bug.cgi?id=215596

However, I am filing this as a systemd issue anyway for visibility as it directly affects systemd and might look like a systemd bug to unsuspecting users.

**Comment by bluca** [comment]
Generally kernel maintainers do not look at bugzilla, try reporting it on the kernel mailing list

**Comment by dechamps** [comment]
Yeah I already did :) https://lore.kernel.org/lkml/e9589141-cfeb-90cd-2d0e-83a62787239a@edechamps.fr/

**Comment by yuwata** [comment]
Offending patch seems to be https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/releases/5.15.12/ucounts-fix-rlimit-max-values-check.patch.

**Comment by Werkov** [comment]
The kernel [has fixes](https://bugzilla.kernel.org/show_bug.cgi?id=215596#c6). Can this be closed now?
