### ISSUE TITLE
ForceDHCPv6PDOtherInformation is not deprecated but removed

### ISSUE THREAD

**Issue by gertvdijk** [systemd/systemd#22493]
**systemd version the issue has been seen with**
250.3 via Debian Bullseye backports (250.3-2~bpo11+1)

**Used distribution**
Debian Bullseye

**Linux kernel version used** (`uname -a`)
5.10.0-11-amd64 (Debian)

**CPU architecture issue was seen on**
amd64

**Expected behaviour you didn't see**
Working DHCPv6-PD without managed flag set using `ForceDHCPv6PDOtherInformation=yes`, with a deprecation warning as mentioned in the NEWS:
https://github.com/systemd/systemd/blob/74c60fcbec9544b73e701158f80fea03282cd20d/NEWS#L386-L390

**Unexpected behaviour you saw**
The config line is ignored with a warning printed in the logs: 
```text
Support for option ForceDHCPv6PDOtherInformation= has been removed and it is ignored
```

**Steps to reproduce the problem**
Set up DHCPv6 prefix delegation with broken ISP-provided modem, see e.g. https://blog.g3rt.nl/systemd-networkd-dhcpv6-pd-configuration.html (look for `ForceDHCPv6PDOtherInformation` stanza in article)

**Additional program output to the terminal or log subsystem illustrating the issue**
Raw log line:
```text
Feb 12 11:37:17 o7070 systemd-networkd[68034]: /etc/systemd/network/mynetwork.network:29: Support for option ForceDHCPv6PDOtherInformation= has been removed and it is ignored
```

Please either adjust the NEWS file to reflect reality or bring back `ForceDHCPv6PDOtherInformation` in 250.x.

**Comment by kisy** [comment]
now this configuration is working

```
[Match]
Type=ppp

[Network]
DHCP=ipv6
IPv6AcceptRA=yes
IPv6PrivacyExtensions=yes
KeepConfiguration=yes

[DHCPv6]
UseDelegatedPrefix=true
WithoutRA=solicit
```

```
[Match]
Name=lan

[Network]
Address=10.0.0.1/24

IPv6PrefixDelegation=dhcpv6
IPv6AcceptRA=yes
```

**Comment by yuwata** [comment]
BTW, I've updated examples about prefix delegation in systemd.network(5) by d45798257b7811d197d26587d847b015623c2b5a.

**Comment by Curtis-Jiang-2020** [comment]
@gertvdijk I looked up the [codebase](https://github.com/systemd/systemd/blob/ec00453b1c3399abf47cc8a51c9f048d304c5a42/src/network/networkd-dhcp6.c#L665). It seems you have to set 
```
[DHCPv6]
UseDelegatedPrefix=true
UseAddress=false
```

to trigger the same code branch as `ForceDHCPv6PDOtherInformation`

I haven't updated to systemd 250 so I can't try it now
