### ISSUE TITLE
timedatectl / timesyncd doesn't follow the symlinks chain

### ISSUE THREAD

**Issue by Oxyd76** [systemd/systemd#22514]
**systemd version the issue has been seen with**
 > systemd 241 on Debian 9
 > systemd 250 (250.3-3-manjaro)

**Used distribution**
 > Manjaro 
 > Debian 9 stretch

**Linux kernel version used** (`uname -a`)

 > `5.15.16-1-MANJARO`
 > `4.4.138` (Debian, custom kernel) 

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `timedatectl` / `timesyncd` does not see the timezone if the symlink does not point to `/usr/share/zoneinfo/Continent/City` directly.

**Unexpected behaviour you saw**
 > My working project saves a permanent configuration in a non-standard path. And initialization scripts, at system startup, create symlinks to configuration files in `/etc`. For `/etc/localtime`, the symlink chain looks like this: `/etc/localtime` → `/mnt/config/etc/localtime` → `/usr/share/zoneinfo/Continent/City`. I expected systemd to expand the symlink chain, but alas. Instead of the correct timezone, `timedatectl` sets the timezone to UTC.

**Steps to reproduce the problem**
 > 1. Create symlink to zoneinfo in some place.
 > 2. Create symlink `/etc/localtime` to symlink from p1.
**Additional program output to the terminal or log subsystem illustrating the issue**

```bash
$ timedatectl
               Local time: Вт 2022-02-15 04:50:40 MSK
           Universal time: Вт 2022-02-15 01:50:40 UTC
                 RTC time: Вт 2022-02-15 01:50:40
                Time zone: Europe/Moscow (MSK, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 33 фев 15 04:03 /etc/localtime -> /usr/share/zoneinfo/Europe/Moscow

$ sudo cp -P /etc/localtime /run
$ ls -l /run/localtime
lrwxrwxrwx 1 root root 33 фев 15 04:50 /run/localtime -> /usr/share/zoneinfo/Europe/Moscow

$  sudo ln -sf /run/localtime /etc/localtime
$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 14 фев 15 04:50 /etc/localtime -> /run/localtime

$ timedatectl
               Local time: Вт 2022-02-15 01:51:15 UTC
           Universal time: Вт 2022-02-15 01:51:15 UTC
                 RTC time: Вт 2022-02-15 01:51:15
                Time zone: n/a (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by poettering** [comment]
This is simply not supported. The /etc/localtime symlinks is API for us, we read the symlink contents to determine the timezone as string. If you depart from this established logic you get to keep the pieces and can't use timedated to manage the symlink. 

We atomically update the symlink via rename(), hence if you place a symlink chain there, then only the first element of it will be replace, not the last.

**Comment by Oxyd76** [comment]
> This is simply not supported. The /etc/localtime symlinks is API for us, we read the symlink contents to determine the timezone as string. If you depart from this established logic you get to keep the pieces and can't use timedated to manage the symlink.
> 
> We atomically update the symlink via rename(), hence if you place a symlink chain there, then only the first element of it will be replace, not the last.

Maybe then highlight this point in the documentation? For example in `man (5) localtime`.

**Comment by poettering** [comment]
It says this pretty explicitly already, no? Quoting:

> It should be an absolute or relative symbolic link pointing to /usr/share/zoneinfo/,      followed by a timezone identifier such as "Europe/Berlin" or "Etc/UTC". The resulting link should lead to the corresponding binary tzfile(5) timezone data for the configured timezone.

> Because the timezone identifier is extracted from the symlink target name of /etc/localtime, this file may not be a normal file or hardlink.

**Comment by ckiee** [comment]
hi @poettering, some unusual NixOS systems have a tmpfs mounted on `/` in the hopes of enforcing a stricter allowlist policy of applications & services leaving gunk on the system, achieving a [_"new computer smell on every boot"_](https://grahamc.com/blog/erase-your-darlings/#your-stateless-future), with exceptions only specified by the user themselves.

Could the systemd project allow adding a configurable option to a `localtime` symlink file that systemd will read & write to, while also synchronizing `/etc/localtime` write-only? This way the existing API is not disrupted and something in Nix doesn't have to be invented to inotify `/etc/localtime`, which you have to agree would be much uglier.

This issue is not resolved.
