### ISSUE TITLE
RFE/RFD: lightweight integration of NFT sets for use in firewalls

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#22527]
**Is your feature request related to a problem? Please describe.**
Integrating firewall rules with systemd services is difficult or impossible. There are BPF options but they aren't very nice to administrate. Also, kernel's netfilter system for cgroup matching is based on numeric cgroup IDs, which change every time a service is restarted, making them useless in systemd environment. Typically DNS information isn't available for firewalls.

**Describe the solution you'd like**
PID1, networkd and resolved should optionally put discovered network and cgroup ID information to NFT sets, for use with firewall rules.
* PID1 should put cgroupv2 IDs to NFT sets named using cgroup path like `systemd.user.slice/user-1000.slice/user@1000.service/app.slice/`, or perhaps to set specified with `Service.CGroupNFTSet=systemd-app`
* networkd should put interface IP address ranges and possibly other information (at the extreme, same as [NetworkManager-dispatcher](https://developer-old.gnome.org/NetworkManager/unstable/NetworkManager-dispatcher.html)) to set named for example `systemd-eth0-ipv4` or perhaps instead specified with `Network.IPv4NFTSet=systemd-eth0-ipv4`
* resolved should put DNS information from resolved to set named according to requesting service (see also #17126) or explicitly configured

Then the firewall rules can make arbitrarily complex use of the sets. Systemd would not need to gain further firewalling abilities besides the rather simple management of specific NFT sets.

Example NFT rules:
```
table inet filter {
        set systemd-eth0-ipv4 {
                type ipv4_addr;
                flags interval;
        }
        set systemd-app {
                type integer;
        }
        set systemd-timesyncd {
                type ipv4_addr;
        }

        chain service_x_input {
                ip saddr @systemd-eth0-ipv4 counter accept
                counter drop
        }
        chain service_y_input {
                meta cgroup @systemd-app counter accept
                counter drop
        }
        chain systemd_timesyncd_output {
                ip daddr @systemd-timesyncd counter accept
                counter reject with icmpx admin-prohibited
        }
}
```

Related discussion in #7327 and #21899.

**Describe alternatives you've considered**
Daemons to manage cgroup IDs:
https://github.com/helsinki-systems/nft_cgroupv2/
https://github.com/mk-fg/systemd-cgroup-nftables-policy-manager

IPSet module for Unbound DNS puts resolved A and AAAA addresses to IPSet (but it can't identify the calling service):
https://github.com/NLnetLabs/unbound/blob/master/ipset/ipset.c

**Comment by topimiettinen** [comment]
Benefit of using NFT sets compared to external daemons is that modifying the set is synchronous but very lightweight operation. For example, `networkd` can set the IP address from DHCP to the set before applying it to the interface, so there are no time windows where the set would be updated too late. This could easily happen if there's an external daemon listening to events (unless PID1 or `networkd` would wait while scripts execute and signal completion).

@poettering @yuwata @keszybz @bluca WDYT?

**Comment by yuwata** [comment]
Sounds nice!

**Comment by topimiettinen** [comment]
[libnftnl](https://netfilter.org/projects/libnftnl/index.html) is licensed under GPL2+. Would that be a problem?

Its dependency, [libmnl](https://netfilter.org/projects/libmnl/index.html) is under LGPLv2.1+.

**Comment by bluca** [comment]
Yes, GPL2 library would be a problem, as the combined work after linking would be GPL2 as a whole - weird license choice for a library?

**Comment by topimiettinen** [comment]
> Yes, GPL2 library would be a problem, as the combined work after linking would be GPL2 as a whole - weird license choice for a library?

Yes, not very inviting. Luckily our own `sd-netlink` already can process some [netlink messages]( https://github.com/systemd/systemd/blob/9fa31df62dd504e8f3e43710df504a467ed430fa/src/libsystemd/sd-netlink/netlink-message-nfnl.c).

**Comment by poettering** [comment]
So we recently discussed whether we should add support to .network files to automatically load nft rules files on interface activation. i.e. that if networkd actviates foobar.network we also load the foobar.nft firewall. 

It appears to me that the concept suggested here of maintaining NFT set objects is a more flexible approach, right?

i.e. what model is preferable: having a static firewall ruleset with dynamic sets – or having a dynamic firewall ruleset? It appears to me the former makes more sense.

Thoughts?

**Comment by topimiettinen** [comment]
I think the models are complementary. Loading rules on interface activation is useful for `netdev` rules, which can't use a set for the interface name. In other cases, set objects may contain information which can be used with static (but also per-interface) rules.

The per-interface rules can be implemented with no changes. Example:

```
# /etc/udev/rules.d/90-netfilter.rules 
SUBSYSTEM!="net", GOTO="netfilter_end"
ENV{SYSTEMD_WANTS}+="nftables-dev@$name.service"
LABEL="netfilter_end"
```

```
# /etc/systemd/system/nftables-dev@.service
[Unit]
Description=nftables for device %i
Documentation=man:nft(8) http://wiki.nftables.org
Wants=network-pre.target nftables.service
Before=network-pre.target shutdown.target
Conflicts=shutdown.target
DefaultDependencies=no
After=nftables.service

[Service]
Type=oneshot
RemainAfterExit=yes
StandardInput=null
ProtectSystem=full
ProtectHome=true
ExecStart=/usr/sbin/nft -f /etc/nftables-%i.conf
ExecReload=/usr/sbin/nft -f /etc/nftables-%i.conf

[Install]
WantedBy=sysinit.target
```

```
# /etc/nftables-lan.conf 
#!/usr/sbin/nft -f

table netdev filter {
        chain lan_ingress {
                type filter hook ingress device lan priority filter; policy drop;
        }
}

flush chain netdev filter lan_ingress

table netdev filter {
        chain lan_ingress {
                type filter hook ingress device lan priority filter; policy drop;

                meta protocol vmap {
                     ip : jump validate_ipv4,
                     ip6 : jump validate_ipv6,
                     arp : jump validate_arp
                }
                counter log prefix "[netdev-lan-ingress] " flags all drop
        }
}
```
This uses static device name 'lan', but I suppose I could use `@@DEVICE@@` insted and use `sed` to replace the interface name with `%i` and feed its output in a pipe to `nft`.

Some rules above (like `validate_ipv4`) are defined in static part.

**Comment by sta-c0000** [comment]
**re: resolved and DNS query nft sets**
I think just that is a great idea, I'm using dnsmasq **v2.87** for this specific use case (easily backported to Debian bullseye).

As you might know [`dnsmasq v2.87`](https://thekelleys.org.uk/gitweb/?p=dnsmasq.git) added the `--nftset` domain name option.
It's great because the nft sets are populated when, and only when, an actual DNS query is performed by the application / service with the ip addresses returned to them by the DNS reply.  It's very efficient.

I had been trying to work out an allowlist firewall using systemd cgroupv2...
Instead I settled on forcing every service and application to use specific Linux users and or groups (one for _every_ that requires any network resources).
nftables is indeed easier, more powerful and flexible, and now better for [statistics](https://github.com/sta-c0000/galaf#generating-statistics).
I've detailed how I'm using nftables with dnsmasq nft sets (with some caveats) here: [Group Allow-List Application Firewall](https://github.com/sta-c0000/galaf)

**Comment by topimiettinen** [comment]
Further integration idea: `DynamicUser=yes` should be also enhanced so that PID1 would keep a NFT set updated when the dynamic UID is allocated and deallocated. The directive could be for example `DynamicUserNFTSet=nfproto:tablename:setname`. Then the firewall rules for protocol `nfproto` and table `tablename` could use the dynamic UID for access control with `meta skuid != @setname counter drop`.

**Comment by topimiettinen** [comment]
Another simple integration feature idea for networkd, this time not with firewalls but [NetLabel](https://github.com/netlabel/netlabel_tools) system (SELinux, Smack, perhaps AppArmor and other LSMs too): new directives `Network.IPv4NetLabelUnlabel=` and `Network.IPv6NetLabelUnlabel=` (perhaps the names could be improved...). This would improve handling of dynamic network interfaces with NetLabel subsystem.

Proposed manual page text:

`Network.IPv4NetLabelUnlabel=label...` and `Network.IPv6NetLabelUnlabel=label...`
- These settings provide a method for integrating dynamic network configuration into Linux NetLabel subsystem rules, used by Linux security modules (LSMs) for network access control. The options expect a whitespace separated list of NetLabel labels. The labels must conform to lexical restrictions of LSM labels. When an interface is configured with IP addresses, the addresses and subnetwork masks will be appended to the NetLabel Fallback Peer Labeling rules. They will be removed when the interface is deconfigured. Failures to manage the labels will be ignored.

- As an example for `IPv4NetLabelUnlabel=system_u:object_r:localnet_peer_t:s0` for interface `eth0`, when the interface is configured with an IPv4 address 10.0.0.0/8, networkd performs the equivalent of `netlabelctl` operation `unlbl add interface eth0 address:10.0.0.0/8 label:system_u:object_r:localnet_peer_t:s0` and the reverse when the IPv4 address is deconfigured.

I think this would also help with [NetLabel issue #8](https://github.com/netlabel/netlabel_tools/issues/8), for systems with systemd-networkd. @pcmoore WDYT?

**Comment by pcmoore** [comment]
The NetLabel integration seems reasonable to me, although there would likely need to be some additional configuration (or very prominent warnings!) as once you start labeling network traffic a lot of access control points go from dormant to active and it is easy for someone not familiar with the LSM per-packet access controls to get into a bad situation.

**Comment by pcmoore** [comment]
I should also add, if NetLabel integration is something systemd is serious about, I can make the netlabel_tools static library a shared library (and likely clean it up a bit too) if systemd wanted to take that approach instead of calling `netlabelctl` directly.

**Comment by topimiettinen** [comment]
> The NetLabel integration seems reasonable to me, although there would likely need to be some additional configuration (or very prominent warnings!) as once you start labeling network traffic a lot of access control points go from dormant to active and it is easy for someone not familiar with the LSM per-packet access controls to get into a bad situation.

Yes, the static configuration would have to be managed with `netlabelctl` like before, the new directive should be needed only if dynamic interfaces need extra configuration. There should be a warning and maybe a reference to NetLabel docs.

There could be a full-blown implementation, where networkd could be used to configure all NetLabel features, but I don't think that makes too much sense. Testing all features (CIPSO etc) with a CI setup would be also _interesting_ exercise.

> I should also add, if NetLabel integration is something systemd is serious about, I can make the netlabel_tools static library a shared library (and likely clean it up a bit too) if systemd wanted to take that approach instead of calling `netlabelctl` directly.

That would be great, assuming that the license will be compatible with systemd's LGPL2.1. Systemd also has an internal implementation of netlink message handling which could be used.

**Comment by bluca** [comment]
> > I should also add, if NetLabel integration is something systemd is serious about, I can make the netlabel_tools static library a shared library (and likely clean it up a bit too) if systemd wanted to take that approach instead of calling `netlabelctl` directly.
> 
> That would be great, assuming that the license will be compatible with systemd's LGPL2.1. Systemd also has an internal implementation of netlink message handling which could be used.

It would also need to be dlopen-safe, which usually is not a problem, but worth mentioning. But it looks like it's GPL-2.0-only https://github.com/netlabel/netlabel_tools/blob/main/LICENSE which is a problem - we'd need LGPL-2.1-or-later to use it here

**Comment by pcmoore** [comment]
> Testing all features (CIPSO etc) with a CI setup would be also interesting exercise.

We do basic SELinux/NetLabel testing as part of the kernel-secnext automated testing, via the selinux-testsuite, but I wouldn't consider that exhaustive testing.  In some sense, a fully exhaustive test is out-of-scope for the selinux-testsuite.

> That would be great, assuming that the license will be compatible with systemd's LGPL2.1. Systemd also has an internal implementation of netlink message handling which could be used.

... and ...

> ... it looks like it's GPL-2.0-only which is a problem ...

Part of that comes from the original idea that the only consumers of the netlabel_tools static library were going to be tools included in netlabel_tools.  I'm not sure I want to go through the hassle of re-licensing the package/library at this point, especially since systemd already knows how to talk to the kernel via netlink/attributes; it's likely easier and quicker to just have systemd issue whatever NetLabel commands it wants direclty via netlink.

**Comment by topimiettinen** [comment]
> Part of that comes from the original idea that the only consumers of the netlabel_tools static library were going to be tools included in netlabel_tools. I'm not sure I want to go through the hassle of re-licensing the package/library at this point, especially since systemd already knows how to talk to the kernel via netlink/attributes; it's likely easier and quicker to just have systemd issue whatever NetLabel commands it wants direclty via netlink.

Agreed. The [unlabeled](https://github.com/netlabel/netlabel_tools/blob/d41600dd298a9f8a1621a48e41cc978a557221ac/libnetlabel/mod_unlabeled.c#L362) protocol seems simple (command, iface, secctx, addr+mask), so we can implement it without any new libraries.

**Comment by topimiettinen** [comment]
Made a separate PR #23269 for NetLabel, since it doesn't use NFT sets.
