### ISSUE TITLE
Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl1

### ISSUE THREAD

**Issue by jshand2015** [systemd/systemd#22524]
systemd 249 (249.9+suse.82.g117bd7f14a)

Modules:

+PAM +AUDIT +SELINUX +APPARMOR -IMA -SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

opensuse tumbleweed
 > …

Kernel:

Linux johns-pc 5.16.8-1-default #1 SMP PREEMPT Thu Feb 10 11:31:59 UTC 2022 (5d1f5d2) x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 AMD 9420e

**Expected behaviour you didn't see**
I expected that the brightness of the screen was a safe maximum for the card and screen

**Unexpected behaviour you saw**
When loading backlight, it intermittently didn't always restore correct brightness, hence, 10% brightness was seen 

**Steps to reproduce the problem**
Load computer as per normal ie turn it on

**Comment by jshand2015** [comment]
[boot-logs.txt](https://github.com/systemd/systemd/files/8073798/boot-logs.txt)
[Uploading boot-logs-errors.txt…]()

**Comment by yuwata** [comment]
The log (boot-logs.txt) does not contain anything informative, and cannot download boot-logs-errors.txt.

If you think this is an issue in systemd-backlight, then please enable to generate debugging logs with the following drop-in config:
```
# /etc/systemd/system/systemd-backlight@.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
Also, please provide the values stored in /sys/class/backlight/amdgpu_bl1/actual_brightness, brightness, and max_brightness.


But, backlight control in amdgpu driver is broken, at least it was broken... As you can find many similar closed reports. I think it is better to contact to kernel's amdgpu driver team.

**Comment by poettering** [comment]
Closing due to lack of response
