### ISSUE TITLE
ntp client is not updating time after updating ntp server time

### ISSUE THREAD

**Issue by rakesh1225** [systemd/systemd#22530]
I am using an embedded board with customized linux on it configured with ntp. /etc/ntp.conf  configuration is as below:

driftfile /var/lib/ntp/drift

server 192.168.1.1 iburst minpoll 4 maxpoll 6

server 127.127.1.0
fudge 127.127.1.0 stratum 14

restrict default nomodify notrap nopeer noquery
restrict 127.0.0.1 nomodify
restrict ::1 nomodify

Time of (ntp client) device is updated with latest time of ntp server device after bootup. 
Issue:
         Date/time is not getting updated at (ntp) client device when date/time is updated at ntp server device. We had to reboot the (ntp) client device to get updated time from server device.
      When the date/time is changed at ntp server device it is not reflecting on the ntp client device as per the polling rate provided.

Please let me know the (ntp) configuration required to get live date/time from (ntp) server device every 20 seconds.

**Comment by yuwata** [comment]
Let me confirm that the client uses systemd-timesyncd, right? Then, try to adjust `PollIntervalMinSec=` and `PollIntervalMaxSec=` in /etc/systemd/timesyncd.conf.

This is just a question. Not an issue report. Closing.
