### ISSUE TITLE
networkd ignores UseDNS=no for DHCPv6

### ISSUE THREAD

**Issue by apsun** [systemd/systemd#22553]
**systemd version the issue has been seen with**
 > systemd 250 (250.3-4-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux <hostname> 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > When specifying `UseDNS=no` under my interface configuration under `[DHCPv4]` and `[DHCPv6]`, I expected `resolvectl` to not show any DNS servers at the link level.

**Unexpected behaviour you saw**
 > `resolvectl` shows the DNS server announced by DHCPv6 under the link. Using https://www.dnsleaktest.com/ indicates that this server is actually being used for DNS queries. This setting works fine for DHCPv4, but not DHCPv6.

**Steps to reproduce the problem**
 > Configure a network interface with `[DHCPv6] UseDNS=no`, then run `sudo systemctl restart systemd-networkd`. Check the output of `resolvectl`.

**Additional program output to the terminal or log subsystem illustrating the issue**

After a fresh reboot:
```text
$ cat /etc/systemd/network/20-wired.network 
[Match]
Name=enp3s0

[Network]
DHCP=yes

[DHCPv4]
UseDNS=no
UseNTP=no

[DHCPv6]
UseDNS=no
UseNTP=no

$ cat /etc/systemd/resolved.conf
[Resolve]
DNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
MulticastDNS=yes
LLMNR=no
```

Checking the actual network state:
```text
$ sudo resolvectl
Global
           Protocols: -LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
  Current DNS Server: 8.8.8.8
         DNS Servers: 8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
Fallback DNS Servers: 9.9.9.9#dns.quad9.net 8.8.8.8#dns.google 2620:fe::9#dns.quad9.net 2001:4860:4860::8888#dns.google

Link 2 (enp3s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 2600:1700:727c:470::1
       DNS Servers: 2600:1700:727c:470::1
```

**Comment by yuwata** [comment]
Is the DNS server comes really from DHCPv6? Have you tried `UseDNS=no` in `[IPv6AcceptRA]`?

**Comment by apsun** [comment]
OMG, you're right. Upon closer inspection with wireshark, it turns out that the DNS server was being announced using both DHCPv6 and IPv6 router advertisement. Setting `UseDNS=no` under both `[DHCPv6]` and `[IPv6AcceptRA]` fixes the problem. Thank you for your help!
