### ISSUE TITLE
Why  the permissions of the/run/systemd/notify and /run/systemd/private are 777?

### ISSUE THREAD

**Issue by JiangYong10000** [systemd/systemd#22556]
The permissions of the/run/systemd/notify and/run/systemd/private files are 777. Is there any security risk? For example, a malicious attacker can send messages at will, resulting in service rejection.

**Comment by poettering** [comment]
Both sockets do authentication/validation of incoming datagrams/connections via SCM_CREDS/SO_PEERCRED, hence no, there should not be a security risk.

Moreover, /run/systemd/notify is actually expressly an API for unprivileged clients, as main service programs should be able to send sd_notify() stuff to PID 1, and they are typically not privileged.
