### ISSUE TITLE
systemctl timestamp formats inadequate for machine parsing, no epoch

### ISSUE THREAD

**Issue by twojstaryzdomu** [systemd/systemd#22567]
**systemd version the issue has been seen with**
systemd 250

**Expected behaviour you didn't see**
None of the timestamp formats available in `systemctl` are machine parseable. For instance, GNU date has issues with all of those.
The `--timestamp` parameter inconveniently accepts only arbitrary human readable values.

**Steps to reproduce the problem**
`# LANG=C systemctl show systemd-journald | grep Timestamp`
no epoch values here

```
# systemctl --help
...
                         'pretty' (default): 'Day YYYY-MM-DD HH:MM:SS TZ
                         'us': 'Day YYYY-MM-DD HH:MM:SS.UUUUUU TZ
                         'utc': 'Day YYYY-MM-DD HH:MM:SS UTC
                         'us+utc': 'Day YYYY-MM-DD HH:MM:SS.UUUUUU UT
```

The epoch provides a convenient time specification for machine parsing. Sadly, systemctl isn't doing much in the way of enabling its output to be parsable by scripts easily.

Seeing as there is a choice of format, one would expect epoch there. For some reason, it's either 'us' or 'utc' or combination of both. Shouldn't there be a greater choice of formats here?

I don't see much difference between these formats anyway. None of them is accepted by `date` for machine parsing:

```
# date -d$(systemctl show --timestamp=pretty systemd-journald -P ActiveEnterTimestamp)
date: extra operand ‘19:20:05’
Try 'date --help' for more information.
# date -d$(systemctl show --timestamp=utc systemd-journald -P ActiveEnterTimestamp)
date: extra operand ‘19:20:05’
Try 'date --help' for more information.
# date -d$(systemctl show --timestamp=us+utc systemd-journald -P ActiveEnterTimestamp)
date: extra operand ‘19:20:05’
Try 'date --help' for more information.
# date -d$(systemctl show --timestamp=us systemd-journald -P ActiveEnterTimestamp)
date: extra operand ‘19:20:05’
Try 'date --help' for more information.
```

Please allow at least epoch to be displayed, or at best a free format string, with sequences similar to FORMAT used by `GNU Coreutils` (`%s` = epoch, etc).

**Comment by mrc0mmand** [comment]
> I don't see much difference between these formats anyway. None of them is accepted by `date` for machine parsing:
> 
> ```
> # date -d$(systemctl show --timestamp=pretty systemd-journald -P ActiveEnterTimestamp)
> date: extra operand ‘19:20:05’
> Try 'date --help' for more information.
> # date -d$(systemctl show --timestamp=utc systemd-journald -P ActiveEnterTimestamp)
> date: extra operand ‘19:20:05’
> Try 'date --help' for more information.
> # date -d$(systemctl show --timestamp=us+utc systemd-journald -P ActiveEnterTimestamp)
> date: extra operand ‘19:20:05’
> Try 'date --help' for more information.
> # date -d$(systemctl show --timestamp=us systemd-journald -P ActiveEnterTimestamp)
> date: extra operand ‘19:20:05’
> Try 'date --help' for more information.
> ```

This part isn't true - you have to quote the timestamp string, as it contains spaces:
```
$ date -d "$(systemctl show systemd-journald -P ActiveEnterTimestamp)"
Sat Dec 11 03:25:57 PM CET 2021
```

(`date` is even telling you that you have extra arguments on the command line)

**Comment by twojstaryzdomu** [comment]
Well spotted, that is precisely why epoch format is needed.

**Comment by poettering** [comment]
did you see systemd.time(7) man page? The format we generate is certainly machine parseable, because it's the format we parse all the time, for example in `journalctl --after=…` and similar.

Use `systemd-analyze timestamp …` for a tool that will parse/validate timestamps in the documented format.

what do you mean by "epoch format"? seconds since 1970?

**Comment by poettering** [comment]
so given we thoroughly established that all our formats are machine parsable by GNU date and by systemd, and that out format is pretty well documented, and we even provide you with parsing/validation/normalization tool set, can we close this?

(I mean, I'd not be opposed to adding a new value to `--timestamp=` that permits requesting seconds since 1970 output. After all, when parsing we actually accept that already, see man page, by prefixing with '@')

**Comment by twojstaryzdomu** [comment]
Of course I've gone through all that effort.

It's beside the point what format is used within systemd, that's not what this issue is about. These formats are poorly suited for machine parsing without passing through other tools.

Epoch time is a nice way of interoperating with other commands. No overhead is necessary to make use of timestamps elsewhere. `date` was an example.

**Comment by denis-beurive** [comment]
This may help:

`# systemctl show -p ActiveEnterTimestamp service1 | sed -e 's/^ActiveEnterTimestamp=//' | awk '{ printf("%s %s", $2, $3) }' | xargs -I %% date --date="%%" '+%s'
1669127394`

**Comment by jasonk** [comment]
You don't need the `sed` or the `awk` though:

```
date --date="$(systemctl show --value -p ActiveEnterTimestamp service1)" '+%s'
```
