### ISSUE TITLE
tmp.mount should escape %

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#22601]
**systemd version the issue has been seen with**
 > 250
 
Hello,

I just wonder why this aint giving a warning, [this line](https://github.com/systemd/systemd/blob/c972880640ee19e89ce9265d8eae1b3aae190332/units/tmp.mount#L25) should escape `%` like this:
`Options=mode=1777,strictatime,nosuid,nodev,size=50%%,nr_inodes=1m`

**Comment by poettering** [comment]
Yes we should.

**Comment by yuwata** [comment]
Fix is waiting in #22604.
