### ISSUE TITLE
journalctl cannot output journals in user mode.

### ISSUE THREAD

**Issue by daiaji** [systemd/systemd#22610]
**systemd version the issue has been seen with**
 > 80ff9567048d0a4aa57e13e9651713798c7fe7bb

**Used distribution**
 >Manjaro Linux 21.2.3

**Linux kernel version used** (`uname -a`)

 > `Linux HCTQD 5.16.10-1-MANJARO #1 SMP PREEMPT Wed Feb 16 22:11:21 UTC 2022 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 >amd64

**Expected behaviour you didn't see**
 > journalctl cannot output journals in user mode.

**Unexpected behaviour you saw**
 > journalctl outputs logs normally in user mode.

**Steps to reproduce the problem**
 > I have no idea.

**Additional program output to the terminal or log subsystem illustrating the issue**

https://gist.github.com/daiaji/69936ebad90045b4cb415078aded0d9e
```text
SYSTEMD_LOG_LEVEL=debug journalctl --user -b

Considering root directory '/run/log/journal'.
Root directory /run/log/journal added.
Considering root directory '/var/log/journal'.
Root directory /var/log/journal added.
Considering directory '/var/log/journal/a9cfc11502ba419aad78c9cecc0da0f6'.
Directory /var/log/journal/a9cfc11502ba419aad78c9cecc0da0f6 added.
No journal files were found.
Journal filter: _BOOT_ID=6c9f879c1f7d44d0870bf1b5987c266d
Successfully forked off '(pager)' as PID 7357.
Skipping PR_SET_MM, as we don't have privileges.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Failed to execute 'pager', using next fallback pager: No such file or directory
Pager executable is "less", options "FRSXMK", quit_on_interrupt: yes
-- No entries --
Root directory /var/log/journal removed.
Directory /var/log/journal/a9cfc11502ba419aad78c9cecc0da0f6 removed.
Root directory /run/log/journal removed.
mmap cache statistics: 0 context cache hit, 0 window list hit, 0 miss
```

**Comment by DaanDeMeyer** [comment]
Are there any user journals in /var/log/journal/a9cfc11502ba419aad78c9cecc0da0f6? Doing an `ls -l /var/log/journal/a9cfc11502ba419aad78c9cecc0da0f6` and posting the output would help to get to the bottom of this.

**Comment by daiaji** [comment]
After I modified the gid and uid, it seems that journalctl can work, dj I still don't know what happened.

**Comment by DaanDeMeyer** [comment]
`journalctl --user` will only show user journal files belonging to the user running journalctl. If there's a mismatch in ownership, you won't get any results.

**Comment by poettering** [comment]
Only users which are member of "wheel" or "adm" get read access to the system logs by default. I guess your original user is not a member of either of those.

THis sounds more like a support/help issue, but this is a bug tracker. If you have further questions about this please contact the systemd mailing list instead, or your distribution's help forums.

**Comment by davehouser1** [comment]
I know this is closed however I have a question related to the same issue.
I noticed that if the User's UID is < 1000, journalctl does not create a log in /var/log/journalctl, there fore `journalctl --user -u myunit` shows no logs. When I adjust the UID to a value >= 1000, journalctl creates logs properly. I cant find anywhere in the documentation that states this specifically. I get it that any user < 1000 is considered a system user, but is this expected?

**Comment by daiaji** [comment]
This may be exactly the problem.
