### ISSUE TITLE
systemctl --user failed to get d-bus connection operation not permitted

### ISSUE THREAD

**Issue by wxke** [systemd/systemd#22612]
**systemd version the issue has been seen with**
 > 219

**Used distribution**
 > centos

**Linux kernel version used** (`uname -a`)

 > 3.10.0-1160.11.1.el7.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
I want run systemctl with user mode. But get failed to get d-bus connection operation not permitted.
```

**Comment by yuwata** [comment]
v219 is too old here, and the report does not contain enough information. Closing.
