### ISSUE TITLE
journald: processing of SIGTERM can get starved by persistent incoming journal messages

### ISSUE THREAD

**Issue by dustymabe** [systemd/systemd#22642]
# Description

We are seeing [an issue in Fedora CoreOS](https://github.com/coreos/fedora-coreos-tracker/issues/1108) where the `systemd-journald` process gets leaked from the initramfs into the real root and is constantly trying to create a new journal file/directory structure in old root from the initramfs.

Our best efforts to characterize this behavior have lead us to the conclusion that the `systemd-journald` gets in a situation where the [sent SIGTERM](https://github.com/systemd/systemd/blob/c8aeb9d672fac7ac2d1e350431b7b4e734b90a5d/src/core/main.c#L1903-L1905) gets starved because of its [lowered priority](https://github.com/systemd/systemd/blob/c8aeb9d672fac7ac2d1e350431b7b4e734b90a5d/src/journal/journald-server.c#L1507-L1508).

How could this happen? What we've noticed by inspection is that `systemd-journald` is continously trying to create `/run/` so it can then create the journal in `/run/log/...`. The attempt to try to create `/run/` fails because of an SELinux denial (we think).

We're not sure exactly but we think the SELinux denial is happening because of the switch to the real root. The `systemd-journald` process still has a `cwd` in the initramfs `/` but now that SELinux is loaded `systemd-journald` can't create things in `/` (it's trying to create `/run/`):

```
avc:  denied  { associate } for  pid=254 comm="systemd-journal" name="run" scontext=system_u:object_r:var_run_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=filesystem permissive=0^M
```

The SELinux denial triggers another audit message to be written to the journal, which then gets added to the queue of things that are higher priority than processing the SIGTERM. We're fairly confident in this theory because on a system where `systemd-journald` is in this state we can simply `setenforce 0` and the leaked `systemd-journald` will then process the SIGTERM immediately.

SELinux context of the leaked `systemd-journald` process:

```
system_u:system_r:kernel_t:s0   root         318       1 92 18:43 ?        00:00:58 @journald
```

CWD of the leaked `systemd-journald` process:

```
[root@cosa-devsh ~]# ls -l /proc/318/cwd
lrwxrwxrwx. 1 root root 0 Mar  1 18:44 /proc/318/cwd -> /
[root@cosa-devsh ~]# ls -l /proc/318/cwd/
total 0
```

Stace (`strace -p $PID`) for the process shows us this loop over and over:

```
newfstatat(AT_FDCWD, "/run/log/journal", 0x7ffde0b827e0, 0) = -1 ENOENT (No such file or directory)
mkdir("/run", 0755)                     = -1 EACCES (Permission denied)
mkdir("/run/log/journal/76b43875f9c941f7b217748f35ea6c2e", 0750) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/log/journal/76b43875f9c941f7b217748f35ea6c2e/system.journal", O_RDWR|O_CREAT|O_NONBLOCK|O_CLOEXEC, 0640) = -1 ENOENT (No such file or directory)
gettid()                                = 318
epoll_wait(8, [{events=EPOLLIN, data={u32=1793716512, u64=94860441415968}}, {events=EPOLLIN, data={u32=1793715600, u64=94860441415056}}, {events=EPOLLIN|EPOLLHUP, data={u32=1793860208, u64=94860441559664}}, {events=EPOLLIN, data={u32=1793715904, u64=94860441415360}}, {events=EPOLLIN|EPOLLHUP, data={u32=1793728224, u64=94860441427680}}, {events=EPOLLIN|EPOLLHUP, data={u32=1793861488, u64=94860441560944}}, {events=EPOLLIN, data={u32=1793715296, u64=94860441414752}}], 30, 0) = 7
ioctl(5, FIONREAD, 0x7ffde0b82d94)      = -1 ENOTTY (Inappropriate ioctl for device)
recvmsg(5, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000001}, msg_namelen=128 => 12, msg_iov=[{iov_base=[{nlmsg_len=229, nlmsg_type=AUDIT_AVC, nlmsg_flags=0, nlmsg_seq=0, nlmsg_pid=0}, "\x61\x75\x64\x69\x74\x28\x31\x36\x34\x36\x31\x36\x30\x33\x35\x34\x2e\x30\x33\x36\x3a\x39\x35\x36\x30\x39\x33\x39\x29\x3a\x20\x61"...], iov_len=24583}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=0, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 229
```

And gdb (`gdb /usr/lib/systemd/systemd-journald -p $PID`) gives us some more information:

```
(gdb) t a a bt

Thread 1 (Thread 0x7fb86a0a4b40 (LWP 318) "systemd-journal"):
#0  0x00007fb86ac553eb in mkdir () at ../sysdeps/unix/syscall-template.S:120
#1  0x000056466955ff73 in system_journal_open (s=0x7ffde0b83210, flush_requested=<optimized out>, relinquish_requested=<optimized out>) at ../src/journal/journald-server.c:378
#2  0x000056466956034e in find_journal (s=0x7ffde0b83210, uid=0) at ../src/journal/journald-server.c:409
#3  0x000056466956242e in write_to_journal (priority=5, n=<optimized out>, iovec=0x56466aec9dd0, uid=0, s=0x7ffde0b83210) at ../src/journal/journald-server.c:825
#4  dispatch_message_real (s=0x7ffde0b83210, iovec=0x56466aec9dd0, n=<optimized out>, m=<optimized out>, c=<optimized out>, tv=<optimized out>, priority=<optimized out>, object_pid=<optimized out>) at ../src/journal/journald-server.c:1026
#5  0x000056466956abf3 in process_audit_string (s=0x7ffde0b83210, type=<optimized out>, data=<optimized out>, size=<optimized out>) at ../src/journal/journald-audit.c:413
#6  0x000056466955cba3 in server_process_audit_message (salen=<optimized out>, sa=0x7ffde0b82e60, ucred=0x7ffde0b82f80, buffer_size=230, buffer=<optimized out>, s=0x7ffde0b83210) at ../src/journal/journald-audit.c:467
#7  server_process_audit_message (salen=<optimized out>, sa=0x7ffde0b82e60, ucred=0x7ffde0b82f80, buffer_size=230, buffer=<optimized out>, s=0x7ffde0b83210) at ../src/journal/journald-audit.c:423
#8  server_process_datagram (es=<optimized out>, fd=5, revents=<optimized out>, userdata=0x7ffde0b83210) at ../src/journal/journald-server.c:1374
#9  0x00007fb86afcd8a4 in source_dispatch (s=0x56466ae9f120) at ../src/libsystemd/sd-event/sd-event.c:3526
#10 0x00007fb86afcdb8d in sd_event_dispatch (e=0x56466ae9e9a0) at ../src/libsystemd/sd-event/sd-event.c:4110
#11 0x00007fb86afcf1e8 in sd_event_run (e=0x56466ae9e9a0, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4171
#12 0x0000564669559f15 in main (argc=<optimized out>, argv=<optimized out>) at ../src/journal/journald.c:114
```

We're not completely sure why `systemd-journald` gets into this state but we have noticed that it [only happens when we start a bunch of VMs in parallel and have a system with a lot of activity in the initramfs]() (i.e. running Ignition for provisioning) This activity could mean journald is processing more when it receives the SIGTERM, which causes it process the SIGTERM later (after the root has been switched) and thus yielding this behavior. 

Is there anything we can do to make sure the processing of SIGTERM in systemd-journald doesn't get starved by messages coming into the journal?

---

**systemd version the issue has been seen with**

```
[core@cosa-devsh ~]$ rpm -q systemd
systemd-249.7-2.fc35.x86_64
```

**Used distribution**

Fedora CoreOS (currently based on Fedora 35)

**Linux kernel version used** (`uname -a`)
 
 ```
[core@cosa-devsh ~]$ uname -a 
Linux cosa-devsh 5.15.18-200.fc35.x86_64 #1 SMP Sat Jan 29 13:54:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 ```

**CPU architecture issue was seen on**

x86_64

**Expected behaviour you didn't see**

Journal from the initramfs receives and processes SIGTERM.

**Unexpected behaviour you saw**

Journal from the initramfs never gets taken down because the SIGTERM is never processed.

**Steps to reproduce the problem**

This is hard to reproduce because it's a race condition. We have been able to reproduce organically in our CI environment, but only under [certain conditions](https://github.com/coreos/fedora-coreos-tracker/issues/1108#issuecomment-1050239987). You can also reproduce the symptom by forcing there to never be a SIGTERM sent to `systemd-journald` by placing this override in the initramfs:

```
# cat /etc/systemd/system/systemd-journald.service.d/00-nokill.conf
[Service]
ExecStart=
ExecStart=@/usr/lib/systemd/systemd-journald @journald
KillMode=none
```

The `@journald` is taking advantage of [this](https://systemd.io/ROOT_STORAGE_DAEMONS/) special behavior of systemd when killing processes on switchroot.

You can also prove out the "starvation" theory by just adding a service to the initrd that spams the journal and watch that the journal from the initrd doesn't process the SIGTERM until after the spamming stops:

```
# cat /usr/lib/systemd/system/coreos-break-journald.service
[Unit]
Description=Break journald
DefaultDependencies=no
[Service]
Type=oneshot
RemainAfterExit=yes
KillMode=none
ExecStart=/usr/bin/timeout --signal=INT 10s env --ignore-signal=TERM yes
# ls -l /etc/systemd/system/initrd.target.requires/coreos-break-journald.service
lrwxrwxrwx 1 root root 53 Jan  1  1970 /etc/systemd/system/initrd.target.requires/coreos-break-journald.service -> /usr/lib/systemd/system/coreos-break-journald.service
```

The higher you adjust the timeout, the longer the SIGTERM to `systemd-journald` gets starved and the process from the initramfs will be around.

**Additional program output to the terminal or log subsystem illustrating the issue**

Here is a full log from a system boot where this happens organically: 
[non-exclusive-test-bucket-0-console.txt](https://github.com/systemd/systemd/files/8164499/non-exclusive-test-bucket-0-console.txt)

Note, while we haven't reproduced this organically with the latest systemd I was able to artificially reproduce it with the `00-nokill.conf` configuration and also to prove out the starvation with the `coreos-break-journald.service` configuration.

```
$ rpm -q systemd kernel
systemd-250.3-6.fc37.x86_64
kernel-5.17.0-0.rc6.109.fc37.x86_64
```

Here is the the backtrace on that system:

```
(gdb) t a a bt

Thread 1 (Thread 0x7f89d8f2c580 (LWP 322) "systemd-journal"):
#0  __GI___fstatat64 (fd=-100, file=0x7ffcce46f8d0 "/run", buf=0x7ffcce46f7f0, flag=256) at ../sysdeps/unix/sysv/linux/fstatat64.c:166
#1  0x00007f89d9dd9ce1 in mkdir_safe_internal (path=0x7ffcce46f8d0 "/run", mode=493, uid=4294967295, gid=4294967295, flags=0, _mkdirat=0x7f89d9dd8410 <mkdirat_errno_wrapper>) at ../src/basic/mkdir.c:39
#2  0x00007f89d9dda3d8 in mkdir_parents_internal (prefix=prefix@entry=0x0, path=<optimized out>, mode=<optimized out>, uid=uid@entry=4294967295, gid=gid@entry=4294967295, flags=flags@entry=0, _mkdirat=<optimized out>1
#3  0x00007f89d9dda4c8 in mkdir_parents (path=<optimized out>, mode=<optimized out>) at ../src/basic/mkdir.c:151
#4  0x000055cc777fbf52 in system_journal_open (s=0x7ffcce470860, flush_requested=<optimized out>, relinquish_requested=<optimized out>) at ../src/journal/journald-server.c:374
#5  0x000055cc777fc31e in find_journal (s=0x7ffcce470860, uid=0) at ../src/journal/journald-server.c:406
#6  0x000055cc77801b6b in write_to_journal (priority=<optimized out>, n=<optimized out>, iovec=<optimized out>, uid=<optimized out>, s=<optimized out>) at ../src/journal/journald-server.c:823
#7  dispatch_message_real (s=0x7ffcce470860, iovec=0x7ffcce46fd70, n=<optimized out>, m=<optimized out>, c=0x0, tv=<optimized out>, priority=<optimized out>, object_pid=<optimized out>) at ../src/journal/journald-ser9
#8  0x000055cc77809166 in process_audit_string (s=0x7ffcce470860, type=<optimized out>, data=<optimized out>, size=<optimized out>) at ../src/journal/journald-audit.c:404
#9  0x000055cc777fa162 in server_process_audit_message (salen=<optimized out>, sa=0x7ffcce4704b0, ucred=0x7ffcce4705d0, buffer_size=<optimized out>, buffer=<optimized out>, s=0x7ffcce470860) at ../src/journal/journal7
#10 server_process_audit_message (salen=<optimized out>, sa=0x7ffcce4704b0, ucred=0x7ffcce4705d0, buffer_size=<optimized out>, buffer=<optimized out>, s=0x7ffcce470860) at ../src/journal/journald-audit.c:413
--Type <RET> for more, q to quit, c to continue without paging--
#11 server_process_datagram (es=<optimized out>, fd=3, revents=<optimized out>, userdata=0x7ffcce470860) at ../src/journal/journald-server.c:1379
#12 0x00007f89d9e92738 in source_dispatch (s=0x55cc79572200) at ../src/libsystemd/sd-event/sd-event.c:3598
#13 0x00007f89d9e93a6d in sd_event_dispatch (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4183
#14 0x00007f89d9e957d8 in sd_event_run (e=<optimized out>, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4244
#15 0x000055cc777f7dcd in main (argc=<optimized out>, argv=<optimized out>) at ../src/journal/journald.c:114
```

For now we are working around the issue with another service that will detect the problem and send a SIGKILL to `systemd-journald`: https://github.com/coreos/fedora-coreos-config/pull/1542

---

Credits: A special thanks to @jlebon and @keszybz for helping me debug this issue.

**Comment by cgwalters** [comment]
Hmm, should we then block switchroot and policy load on journald being flushed?

**Comment by DaanDeMeyer** [comment]
See also #21164 where this was already reported.

**Comment by dustymabe** [comment]
Thanks for the link @DaanDeMeyer. I did do some searching last week to see if there was an open issue already but I think that was before we had determined that SIGTERM processing was being starved. Sorry I missed your open issue.

**Comment by DaanDeMeyer** [comment]
I'll close that one since this is more detailed anyway

**Comment by poettering** [comment]
i guess we could use the sd-event ratelimit stuff to combat this effectively

**Comment by dustymabe** [comment]
Thanks for looking at this @poettering - We can reproduce this fairly easily so if you have any potential fixes we could test it out and give feedback.

**Comment by dustymabe** [comment]
👍 - sounds reasonable to me
