### ISSUE TITLE
Contradictory information on polkit use in `man/org.freedesktop.systemd1.xml`

### ISSUE THREAD

**Issue by dc6c** [systemd/systemd#22648]
**systemd version the issue has been seen with**
 > HEAD

The Introduction section says "In contrast to most of the other services of the systemd suite, PID 1 does not use polkit for controlling access to privileged operations, but relies exclusively on the low-level D-Bus policy language." On the other hand, the Security section on the Manager object goes on in decent detail about the different polkit action ids that are required for various operations. Aren't the two statements contradictory? In particular, the Intro seems wrong, or at least misleading.

**Comment by poettering** [comment]
yeah, the docs are out of date, we do polkit from PID 1 these days.
