### ISSUE TITLE
systemd incorrectly calculates needed swap size for hibernation 

### ISSUE THREAD

**Issue by BeeFox-sys** [systemd/systemd#22666]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-6)

**Used distribution**
 > Debian (Bullseye)

**Linux kernel version used** (`uname -a`)

 >`Linux beefox 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Successful hibernation

**Unexpected behaviour you saw**
 > Computer either responds with `Failed to hibernate system via logind: Not enough swap space for hibernation` or goes to sleep, turns screen off, waits 10 seconds, and returns to login screen, with journal saying `systemd-sleep[53394]: Failed to suspend system. System resumed again: No space left on device`

**Steps to reproduce the problem**
 > Hibernate via systemd

**Other, relating information**
Ram: 8gi (7.5gi useable)
Swap: 19gi (usually around 400-900mi used)
Swap is in a separate partition
Hibernation via `echo disk > /sys/power/state` works as intended with no errors

**Comment by BeeFox-sys** [comment]
Some more information that i have discovered: The hibernation image being generated is only 2gb, 1/10th the size of the available space, yet i still get not enough space messages

**Comment by poettering** [comment]
We just expose the error code the kernel provides us with. Is there any further information in the kernel log message?

This looks more like a kernel issue, not something we could do anything about.

**Comment by BeeFox-sys** [comment]
No further info, and updating to gnome 41 solved this issue, the kernel logs said the image was successfully written so i have no clue what is going on. either way it is no longer a bug i experince

**Comment by yuwata** [comment]
Then, let's close this.
