### ISSUE TITLE
networkd: rename Filename=/NextServer= settings

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22661]
The options are a bit too generic for my taste. Let's make them a bit more specific, see:

https://github.com/systemd/systemd/pull/22615#issuecomment-1059037246

THis is purely about how we expose the options to users, not about the underlying dhcp options.

**Comment by poettering** [comment]
And i think the server option also should accept server names, not just IP addresses, see my comment on that other bug

**Comment by yuwata** [comment]
Hmm, I completely misunderstand options. These settings should use option 66 (or siaddr) and 67.

**Comment by yuwata** [comment]
For the record, dnsmasq uses `--dhcp-boot=[tag:<tag>,]<filename>,[<servername>[,<server address>|<tftp_servername>]]` to specify option 66 (or siaddr) and 67.
dhcpcd uses `next-server` and `filename` to specify them.

**Comment by yuwata** [comment]
However, ipxe can handle any URL in option 67, so, underlying protocol is not necessary to be TFTP.

@poettering How about the following:
NextServer= -> DHCPBootServerAddress= (for siaddr) and DHCPBootServerName= (for option 66),
Filename= -> DHCPBootConfigFile=

**Comment by poettering** [comment]
> NextServer= -> DHCPBootServerAddress= (for siaddr) and DHCPBootServerName= (for option 66),
> Filename= -> DHCPBootConfigFile=

The "DHCP" prefix seems redundant, no? It's in the [DHCPServer] section anyway, so the DHCP context should be really clear.

Hmm, does it really make sense to make the two server addresses configurable independently? it appears to me that we should offer a single setting that then propagates into the right field if suitable. i.e. is there any point in being able to set siaddr to some value but option 66 to something entirely different in the same lease? i don't think so?

**Comment by yuwata** [comment]
@poettering Thank you for the suggestions.

I hope #22618 addressed all comments.

**Comment by johannbg** [comment]
@poettering, @yuwata are there any plans on adding a Match sections to the DHCPServer section?

As in people will want to be able to provide different BootFilename= entries based on various matches.

For example a very basic sample would be serving serving different boot files based upon the architecture type 32-bit, 64-bit, BIOS or EFI. 

Such sample would be configured in ISC dhcp like this.

class "pxeclients" {
match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

if option architecture-type = 00:00 {
  filename "pxelinux.0"; # BIOS
} elsif option architecture-type = 00:07 {
  filename "syslinux.efi"; # EFI
  option bootfile-name "syslinux.efi";
} elsif option architecture-type = 00:09 {
  filename "EFIia64/syslinux.efi"; # ia64_EFI
  option bootfile-name "syslinux.ia64";
} elsif option architecture-type = 00:06 {
  filename "EFIia32/syslinux.efi"; # ia32_EFI
}

How would you go about expressing this .network file?

Another question given that I know how complex these files can become on a dhcp servers, are there any plans on splitting out the [DHCPServer] section from the .network file into it's own .server file or atleast add a support for a snippet? 
( then for example, in the example above each architecture-type could be contained in it's own snippet )

**Comment by poettering** [comment]
> @poettering, @yuwata are there any plans on adding a Match sections to the DHCPServer section?

I'd avoid it if possible. 

the architectures are quite well defined in rfc4578. Hence maybe instead of doing match based stuff just add simple expansion of specifier-like expresions to BootFileName=. i.e. let's say if `@a` appears in the specified filename we'll replace it with the EFI-style architecture name. So you could do `BootFilename=quux@awaldo` and this would translate to `quuxefiia32waldo` or so for the respective client.  That way we make this an fs arrangement issue: people would just have to symlink their files in a way that matches this behaviour. I think this should already get us quite far, since matching by arch is probably the most important key, and there's a limited number of archs defined.

**Comment by yuwata** [comment]
@johannbg Filed as a new RFE #22815, otherwise we easily forget the suggestion.
