### ISSUE TITLE
nfs-utils prevents network interface from returning to the host

### ISSUE THREAD

**Issue by greg-hydrogen** [systemd/systemd#2266]
Hello Everyone,

I have seem to hit a strange issue.  On a minimal install Centos 7.2 VM, using nspawn to spawn up either Fedora or Centos containers with the --network-interface switch, when the nfs-utils package is installed in the container and when the container is terminated the network interface does not return to the host as expected, here is the output and any potential helpful information
kernel - 3.10.0-327.3.1.el7.x86_64 
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

Host IP output (no container started omitting lo)
2: eno16777736: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:58:57:5d brd ff:ff:ff:ff:ff:ff
3: eno33554976: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:58:57:67 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.208/24 brd 192.168.2.255 scope global dynamic eno33554976
       valid_lft 604112sec preferred_lft 604112sec
    inet6 fd00:fc:8d40:17a2:20c:29ff:fe58:5767/64 scope global noprefixroute dynamic 
       valid_lft 535431sec preferred_lft 401574sec
    inet6 fe80::20c:29ff:fe58:5767/64 scope link 
       valid_lft forever preferred_lft forever

Starting Container without the nfs-utils package
[root@localhost /]# systemd-nspawn --network-interface=eno16777736 -bD /fed
IP output from within the container (omit loopback)
2: eno16777736: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:58:57:5d brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.8/24 brd 192.168.2.255 scope global eno16777736
       valid_lft forever preferred_lft forever
    inet6 fd00:fc:8d40:17a2:20c:29ff:fe58:575d/64 scope global mngtmpaddr dynamic 
       valid_lft 535426sec preferred_lft 401569sec
    inet6 fe80::20c:29ff:fe58:575d/64 scope link 
       valid_lft forever preferred_lft forever

check if the nfs-utils package is installed
[root@container~]# dnf list installed | grep -i nfs-utils
[root@conainer ~]# 

terminate the container with ctrl+]]] and run ip addr on the host
2: eno16777736: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:58:57:5d brd ff:ff:ff:ff:ff:ff
3: eno33554976: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:58:57:67 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.208/24 brd 192.168.2.255 scope global dynamic eno33554976
       valid_lft 603977sec preferred_lft 603977sec
    inet6 fd00:fc:8d40:17a2:20c:29ff:fe58:5767/64 scope global noprefixroute dynamic 
       valid_lft 535433sec preferred_lft 401576sec
    inet6 fe80::20c:29ff:fe58:5767/64 scope link 
       valid_lft forever preferred_lft forever

the eno16777736 has returned to the host as expected.  

Install the nfs-utils package and repeat the same steps above
in the container list installed packages
[root@container ~]# dnf list installed | grep -i nfs-utils
nfs-utils.x86_64                     1:1.3.3-5.rc2.fc23                 @updates
now terminate the container with ctrl +]]]
display ip information on the host
3: eno33554976: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:58:57:67 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.208/24 brd 192.168.2.255 scope global dynamic eno33554976
       valid_lft 603666sec preferred_lft 603666sec
    inet6 fd00:fc:8d40:17a2:20c:29ff:fe58:5767/64 scope global noprefixroute dynamic 
       valid_lft 535432sec preferred_lft 401575sec
    inet6 fe80::20c:29ff:fe58:5767/64 scope link 
       valid_lft forever preferred_lft forever

the eno16777736 is not returned to the host

just having the nfs-utils installed will cause this issue even if it is not in use

Please let me know if any more details are required

Thanks,
Greg

**Comment by poettering** [comment]
Sounds like a kernel bug. Please file this on kernel bugzilla.

I am pretty sure the kernel NFS server is not really compatible with network namespaces and keeps them pinned forever. Either way, closing here, there's nothing we can do about that here.

**Comment by f0** [comment]
@poettering  we also see such an issue , is there a way to clean up the namespace manually?

**Comment by f0** [comment]
any chance to get this fixed? (i am not a c guy, so i can not fix it myself)
