### ISSUE TITLE
systemctl --machine flag is only usable from pty console with SELinux enforcing

### ISSUE THREAD

**Issue by jmpolom** [systemd/systemd#22674]
**systemd version the issue has been seen with**
```
systemd 249 (v249.9-1.fc35)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Used distribution**
Fedora 35

**Linux kernel version used** (`uname -a`)

 `Linux archon.subly.me 5.16.9-200.fc35.x86_64 #1 SMP PREEMPT Fri Feb 11 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
See above.

**Expected behaviour you didn't see**
`systemctl --user --machine=<user>@.host <command>` should function over ssh with or without a pty, and from locally attached consoles (ex: tty0, ttyS0) without fuss and with SELinux in Enforcing mode.

```
$ ssh jon@archon sudo -S setenforce Permissive <-- this SHOULD NOT be necessary!
[sudo] password for jon: 
$ ssh jon@archon sudo -S systemctl --user --machine=dwspectrum@.host status
[sudo] password for jon: 
● dwspectrum@.host
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2022-03-02 16:03:03 EST; 1 day 5h ago
   CGroup: /user.slice/user-2000.slice/[user@2000.service](mailto:user@2000.service)
           ├─user.slice
           │ └─podman-pause-5888336200230828555.scope
           │   └─27309 /usr/bin/podman
           ├─app.slice
           │ └─dbus-broker.service
           │   ├─16380 /usr/bin/dbus-broker-launch --scope user
           │   └─16381 dbus-broker --log 4 --controller 9 --machine-id 7870a20d7a3d4d7d897c430d4c27a9b0 --max-bytes 100000000000000 --max-fds 25000000000000 --max-matches 5000000000
           └─init.scope
             ├─16370 /usr/lib/systemd/systemd --user
             └─16372 (sd-pam)
```

**Unexpected behaviour you saw**
```
$ ssh jon@archon sudo -S systemctl --user --machine=dwspectrum@.host status
[sudo] password for jon:
Failed to start transient service unit: Remote peer disconnected
Failed to read server status: Transport endpoint is not connected
```

**Steps to reproduce the problem**
Run `systemctl --user --machine=<user>@.host status` (for example) from either a locally attached console or via ssh without a pty (Use `ssh -T` or __do not__ issue `-t`) on a Fedora 35 system with SELinux set to enforcing mode.

**Full issue description**
Using the `--machine` flag with systemctl seems to result in a cryptic failure on Fedora systems with SELinux in Enforcing mode, unless the command is issued via an ssh session which requests a pty.

Illustrative example command that results in failure (please do not focus on the silly `-S` sudo flag, this is merely a contrived example to demonstrate the problem):
```
$ ssh jon@archon sudo -S systemctl --user --machine=dwspectrum@.host status
[sudo] password for jon:
Failed to start transient service unit: Remote peer disconnected
Failed to read server status: Transport endpoint is not connected
```

Issuing the same command from a local console (ex: tty0) or serial console (ex: ttyS0) results in the exact same failure and error message. This is not experienced on distros not using SELinux like Debian.

Let's try with a pty requested:
```
$ ssh -t jon@archon sudo systemctl --user --machine=dwspectrum@.host status
[sudo] password for jon:
● dwspectrum@.host
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2022-03-02 16:03:03 EST; 1 day 5h ago
   CGroup: /user.slice/user-2000.slice/[user@2000.service](mailto:user@2000.service)
           ├─user.slice
           │ └─podman-pause-5888336200230828555.scope
           │   └─27309 /usr/bin/podman
           ├─app.slice
           │ └─dbus-broker.service
           │   ├─16380 /usr/bin/dbus-broker-launch --scope user
           │   └─16381 dbus-broker --log 4 --controller 9 --machine-id 7870a20d7a3d4d7d897c430d4c27a9b0 --max-bytes 1>
           └─init.scope
             ├─16370 /usr/lib/systemd/systemd --user
             └─16372 (sd-pam)
```

The command succeeds albeit in interactive mode which is extremely undesirable if you're trying to interact with these systems over ssh programmatically. The main _extreme inconvenience_ of this issue is that it prohibits efficient scripted interaction with systemd user sessions via ssh unless SELinux is Permissive or disabled.

Now with SELinux in Permissive mode and no pty requested:
```
$ ssh jon@archon sudo -S setenforce Permissive
[sudo] password for jon: 
$ ssh jon@archon sudo -S systemctl --user --machine=dwspectrum@.host status
[sudo] password for jon: 
● dwspectrum@.host
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2022-03-02 16:03:03 EST; 1 day 5h ago
   CGroup: /user.slice/user-2000.slice/[user@2000.service](mailto:user@2000.service)
           ├─user.slice
           │ └─podman-pause-5888336200230828555.scope
           │   └─27309 /usr/bin/podman
           ├─app.slice
           │ └─dbus-broker.service
           │   ├─16380 /usr/bin/dbus-broker-launch --scope user
           │   └─16381 dbus-broker --log 4 --controller 9 --machine-id 7870a20d7a3d4d7d897c430d4c27a9b0 --max-bytes 100000000000000 --max-fds 25000000000000 --max-matches 5000000000
           └─init.scope
             ├─16370 /usr/lib/systemd/systemd --user
             └─16372 (sd-pam)
```

This works as expected and systemctl properly detects it is being run non-interactively and just spews out text output, _exactly as desired and expected_.

Unfortunately I am unable to locate __any__ clues in the audit logs via ausearch that might hint at what the specific problem is here. I am willing to provide complete audit logs but there are no avc or user_avc messages that I can find. I am at a complete loss for next steps at troubleshooting this behavioral inconsistency. However, disabling SELinux or setting Permissive mode resolves this issue so it seems to be very clearly an SELinux/policy issue.

Proof:
```
[jon@archon ~]$ sudo ausearch -m avc,user_avc -ts boot
[sudo] password for jon:
<no matches>
```

I also do not seem to have any setroubleshoot messages in the system journal, but the respective user's journal does have these entries that might be clues:

```
Mar 03 21:33:01 archon.subly.me dbus-broker-launch[16381]: avc:  op=setenforce lsm=selinux enforcing=1 res=1
Mar 03 21:33:01 archon.subly.me systemd[16370]: selinux: avc:  op=setenforce lsm=selinux enforcing=1 res=1
Mar 03 21:33:01 archon.subly.me dbus-broker[16381]: Peer :1.118 is being disconnected as it sent a message with an invalid header.
Mar 03 21:33:01 archon.subly.me systemd[45190]: pam_selinux(login:session): Setting file context "unconfined_u:object_r:user_devpts_t:s0" failed for /dev/pts/0: Operation not permitted
Mar 03 21:33:01 archon.subly.me systemd[45190]: pam_systemd(login:session): Failed to release session: Access denied
```

It seems like this could be a dbus-broker policy issue? I previously reported a recurring [issue][0] with that policy area that prevented systemd networkd from starting on boot so my suspicion is high this could be relevant info. However, I do not see additional errors later on if I re-run `ssh jon@archon sudo -S systemctl --user --machine=dwspectrum@.host status` with SELinux in Enforcing mode.

What would be helpful and where I can assist:
  - suggestions of additional troubleshooting steps
  - suggestions of additional log items to look at
  - suggestions of relevant SELinux booleans that could be set to alleviate the issue

This issue relates to:
  - https://bugzilla.redhat.com/show_bug.cgi?id=2060702
  - https://github.com/fedora-selinux/selinux-policy/issues/1106

**Comment by poettering** [comment]
selinux policy is a fedora thing. We do not control this upstream, please file against the dbus policy package of fedora. Sorry, but we are no selinux people really upstream, and as you have shown it's almost certainly a bug in the policy, not in the code.

**Comment by jmpolom** [comment]
@poettering thank you for taking a look. Your response is precisely what I wanted to see.

**Comment by rhatdan** [comment]
Please open a Bugizilla on the SELinux issue, including the AVCs.

**Comment by jmpolom** [comment]
@rhatdan that has been done, and there are no AVCs produced by this issue even with "full auditing" enabled. The bugzilla issue is linked in my first post in this issue.

**Comment by farblos** [comment]
@jmpolom Could you please provide a reference to the Bugzilla? A simplistic search with the rather generic keywords of this bug's subject did not bring up ynthing useful there.

Thanks!
