### ISSUE TITLE
Udevadm will fail to reload continuously for multiple times

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#22686]
**systemd version the issue has been seen with**
 > 250/main

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > linux 5.10

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 >
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service  
no failed

**Unexpected behaviour you saw**
 > 
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service  
failed

**Steps to reproduce the problem**
 > 
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service  

**Additional program output to the terminal or log subsystem illustrating the issue**
https://github.com/systemd/systemd/pull/21762 fix udev reload failed problem, but the latest version of main ，Udevd will fail to reload continuously for multiple times。

```
this is ok , even try multiple times
systemctl stop systemd-udevd-control.socket
systemctl stop systemd-udevd-kernel.socket
systemctl restart systemd-udevd.service
systemctl reload systemd-udevd.service
systemctl status systemd-udevd.service
```
```
this is not ok , when try multiple times。but the time interval becomes longer， it will ok
systemctl reload systemd-udevd.service
systemctl reload systemd-udevd.service
...
```
log
Mar 09 15:48:40 localhost.localdomain systemd[1]: systemd-udevd.service: Control process exited, code=killed, status=9/KILL
Mar 09 15:48:40 localhost.localdomain systemd[1]: Reload failed for Rule-based Manager for Device Events and Files.
Mar 09 16:02:32 localhost.localdomain systemd[1]: Reloading Rule-based Manager for Device Events and Files...
Mar 09 16:02:32 localhost.localdomain systemd[1]: Reloaded Rule-based Manager for Device Events and Files.
Mar 09 16:03:26 localhost.localdomain systemd[1]: Reloading Rule-based Manager for Device Events and Files...
Mar 09 16:03:26 localhost.localdomain systemd[1]: systemd-udevd.service: Control process exited, code=killed, status=9/KILL
Mar 09 16:03:26 localhost.localdomain systemd[1]: Reload failed for Rule-based Manager for Device Events and Files.
Mar 09 16:04:40 localhost.localdomain systemd[1]: Reloading Rule-based Manager for Device Events and Files...
Mar 09 16:04:40 localhost.localdomain systemd[1]: systemd-udevd.service: Control process exited, code=killed, status=9/KILL
Mar 09 16:04:40 localhost.localdomain systemd[1]: Reload failed for Rule-based Manager for Device Events and Files.
```
<!-- Please paste relevant program terminal or journal output here, ideally
     when generated in debug mode (try setting the SYSTEMD_LOG_LEVEL=debug
     environment variable). For very long copy/pasted data consider using a
     service like https://gist.github.com/. Where copy/paste is not possible
     (for example early boot or late shutdown), a photo of the screen might do
     too, but text is always much preferred. -->
```text
…
```

**Comment by yuwata** [comment]
I guess this is already fixed by ccadf9ac0d6d206767294b3f96f41eb42b48d1b0 (#21762). Closing.

Feel free to request to reopen this issue if you reproduce the issue with the current git HEAD?

**Comment by yangmingtai** [comment]
@yuwata 
from 1 to 4 success, 5 and 6 failed
![image](https://user-images.githubusercontent.com/17870505/157424581-54c2594b-0e75-4627-b8ab-0b28d1a03587.png)

systemd version is 2022/2/25
![image](https://user-images.githubusercontent.com/17870505/157425954-406696d6-c026-4c22-a058-6e4cb91ce1c6.png)

**Comment by yuwata** [comment]
@yangmingtai Sorry for late, I hope #22752 improves the situation. At least, I cannot reproduce the error with the PR.
If possible, could you test the PR?

**Comment by yangmingtai** [comment]
> @yangmingtai Sorry for late, I hope #22752 improves the situation. At least, I cannot reproduce the error with the PR. If possible, could you test the PR?
I test , This PR maybe not solve the problem。

before the PR, execute restart and reload will success,  execute reload alone will failed
![udev](https://user-images.githubusercontent.com/17870505/158553654-77e4f149-7d21-4fbd-8d3b-d3f03260631a.PNG)
after the PR, execute restart and reload will success,  execute reload alone will failed
![image](https://user-images.githubusercontent.com/17870505/158550795-f2e4aa28-7c1c-42d2-9504-34df55c6478b.png)
