### ISSUE TITLE
Provide better error message for units masked via kernel command line

### ISSUE THREAD

**Issue by lheckemann** [systemd/systemd#22689]
**systemd version the issue has been seen with**
 > v249.7

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)

 > `Linux ordnungsamd 5.15.22 #1-NixOS SMP Tue Feb 8 17:34:14 UTC 2022 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > `systemctl unmask $unit` should always unmask the given unit or report an error.

**Unexpected behaviour you saw**
 > `systemctl unmask $unit` neither unmasks the unit nor reports an error if `systemd.mask=$unit` was passed on the kernel command line.

**Steps to reproduce the problem**
 1. Boot with `systemd.mask=systemd-resolved.service`
 2. Attempt to unmask `systemd-resolved.service` using `systemctl unmask`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
… (todo)
```

**Comment by poettering** [comment]
Yeah, it's masked for the chosen boot from boot-up till shutdown. The man page mentions this briefly "is masked for the runtime". I guess we could make this more explicit in the docs. But this is not a bug, it's intended, documented behaviour.

**Comment by mfpx** [comment]
> Yeah, it's masked for the chosen boot from boot-up till shutdown. The man page mentions this briefly "is masked for the runtime". I guess we could make this more explicit in the docs. But this is not a bug, it's intended, documented behaviour.

What manpage is this in? I've done looked through relevant manpages and didn't see anything mentioning that.

**Comment by mrc0mmand** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-debug-generator.html (mentioned in https://www.freedesktop.org/software/systemd/man/kernel-command-line.html#systemd.mask=).

**Comment by mfpx** [comment]
Thanks, for some reason I couldn't find that exact string in the source, odd that.
I'll write up a clarification for this

**Comment by lheckemann** [comment]
`systemd unmask` should still report that the unit cannot be unmasked. Could this be reopened?

**Comment by mbiebl** [comment]
> `systemctl unmask` should still report that the unit cannot be unmasked. Could this be reopened?

Agreed, reopened accordingly.
