### ISSUE TITLE
systemd-cryptsetup-generator generating wrong service names

### ISSUE THREAD

**Issue by juangiordana** [systemd/systemd#22716]
**systemd 250.3-4 - systemd-cryptsetup-generator is generating wrong service names**

The generator script is converting dashes (-) to `\x2d` resulting in incorrect file/service names.

```
# /etc/crypttab
# <name>               <device>                         <password> <options>
luks-9998bf01-c4b9-4909-9f74-d54de2e1cafa UUID=9998bf01-c4b9-4909-9f74-d54de2e1cafa     /crypto_keyfile.bin luks
luks-883fc6d6-a632-402e-9a0f-e761eacb35c3 UUID=883fc6d6-a632-402e-9a0f-e761eacb35c3     /crypto_keyfile.bin luks
luks-home   /dev/sdb /root/luks/sdb-key.bin header=/root/luks/sdb-header.img,luks,readonly
luks-backup /dev/sdc /root/luks/sdd-key.bin header=/root/luks/sdd-header.img,luks,noauto,readonly
```

**Used distribution**
 > EndeavourOS Atlantis Neo

**Linux kernel version used** (`uname -a`)
 > `5.16.13-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
```
# systemctl list-unit-files | grep systemd-cryptsetup
systemd-cryptsetup@luks-883fc6d6-a632-402e-9a0f-e761eacb35c3.service generated       -
systemd-cryptsetup@luks-9998bf01-c4b9-4909-9f74-d54de2e1cafa.service generated       -
systemd-cryptsetup@luks-backup.service                                           generated       -
systemd-cryptsetup@luks-home.service                                             generated       -
```
**Unexpected behaviour you saw**
```
# systemctl list-unit-files | grep systemd-cryptsetup
systemd-cryptsetup@luks\x2d883fc6d6\x2da632\x2d402e\x2d9a0f\x2de761eacb35c3.service generated       -
systemd-cryptsetup@luks\x2d9998bf01\x2dc4b9\x2d4909\x2d9f74\x2dd54de2e1cafa.service generated       -
systemd-cryptsetup@luks\x2dbackup.service                                           generated       -
systemd-cryptsetup@luks\x2dhome.service                                             generated       -
```

**Steps to reproduce the problem**
 > Use dashes in volume names.

**Comment by poettering** [comment]
Hmm? We generating the unit name we escape characters that might have special significance in unit names. See details about %i vs. %I specifier in systemd.unit(5) man page, and the section "STRING ESCAPING FOR INCLUSION IN UNIT NAMES" there.

Or in other words, this is by design, and documented.

You can use the `systemd-escape` to apply or undo the escaping from the shell.
