### ISSUE TITLE
Unit status/request changes monitor

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#22720]
I'm struggling with running state monitoring (e.g. during some unit setup when I need to debug their relations and dependencies). I'm thinking about some tool working like `udevadm monitor` or `dmesg -w` attached to systemd and dumping the currently taken actions (like unit activation). I thought this could be seen on dbus, however I can't get both `dbus-monitor` nor `busctl monitor` to show timer-triggered activation. Consider the following:

beep.service

```
[Unit]
Description=Beep PC speaker

[Service]
ExecStart=-/bin/sh -c 'echo -n "\a" >> /dev/console'

```
beep.timer

```
[Timer]
OnActiveSec=1
OnUnitInactiveSec=1
AccuracySec=50ms
```

This timer fires service every second and sometimes it fails (Failed with result 'start-limit-hit'), as expected. However I can't find any way to watch every single invocation of beep.service, bus monitors are quiet about this (or require some non-obvious options).

**Comment by boucman** [comment]
systemd does send signals when a unit chage state, but you need to call the register() method on systemd itself for it to start sending the signals...

**Comment by bluca** [comment]
See JobNew and JobRemoved https://www.freedesktop.org/software/systemd/man/org.freedesktop.systemd1.html#Signals

**Comment by g0tar** [comment]
Thanks guys for your hints, but I really don't find them directly useful. I didn't seek a method to write my own snooper, simply requested a generic one to be written here, or be shown how to accomplish this by using provided utilities.

Single "reload" action returns about 900 lines of output in dbus monitor mode and doesn't specify the action taken in profile mode. JobNew returns only string containing unit name and no action nor transition between states. This is unusable.

Bus monitors are not the **end-user** tool for doing the job, just like manual dbus-activation is not sufficient and there is `systemctl` binary that handles the cryptic stuff. Therefore I don't find this "already-implemented" a valid statement.

However I do appreciate your comments in the sense of confirming there is no regular tool with simple invocation for doing this.

Since I didn't want to write anything, especially using bindings that might be not installed on target system, I've decided and spend about 2 hours working on a screen-long "one-liner" ("one-screener") just to demonstrate that this is not a trivial task (there's no JSON-like output in `dbus-monitor` and `busctl` doesn't handle filters) and so there is a need to support something like this upstream.

**Comment by g0tar** [comment]
The demo "program" I've attached is more reliable than `systemctl status`, shows complexity of the task using dbus and it's still not complex (in any way) usage; it's purely daily administrative one. Anyway, if you expect system status debugging to be as burdensome as it is now, let just be it, I already got my solution (although exposing some delay due to state transition mapping).
