### ISSUE TITLE
https://systemd.network certificate expired

### ISSUE THREAD

**Issue by kiwixz** [systemd/systemd#22726]
https://systemd.network/ certificate expired today.

An alternative is: https://www.freedesktop.org/software/systemd/man/index.html

Sorry if this is not the place for this, but I hope you'll have more insights about who to contact to fix this !

**Comment by yuwata** [comment]
Hm?? The address is really managed by us? cc @keszybz and @poettering.

**Comment by flokli** [comment]
Oops, sorry about that. The certificate is renewed - certbot stumbled on some domains that were still configured :-D

**Comment by kiwixz** [comment]
I'm glad I can go back to the fancy domain, thanks !
