### ISSUE TITLE
[hostnamed] Get "BIOS version" of device using hostnamed

### ISSUE THREAD

**Issue by nitinexclusively** [systemd/systemd#22728]
Hello ,
Currently , I am working to display "BIOS version" of device in gnome-settings . I am using ThinkPad X1 Yoga G6
We can get "BIOS version" of the device using sysfs "/sys/class/dmi/id/bios_version" . 
But reviewer has suggested to get bios version via hostnamed as per below comment , while submitting changes:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/1250

Is it acceptable to add "BIOS version" in hostnamed ? Any comment regarding this will be helpful.
Thank you!

**Comment by nitinexclusively** [comment]
@poettering Thank you for your comment.

**Comment by nitinexclusively** [comment]
I have created patch for this as shown below but not tested it .
[0001-Display-BIOS-version.zip](https://github.com/systemd/systemd/files/8347149/0001-Display-BIOS-version.zip)
Since , this is first time i am checking systemd code , i have some queries:
- I have just compiled systemd code using below but may i know how i can install it ? After installing it seems wifi is disappearing and other issue occured.
./configure
make && make install
- Is there a way to compile only hostnamed with current systemd version which is available in distros like , i am using Ubuntu 20.04 now instead of compiling systemd ?
I am sorry , if this is not the right place or its very basic question , Thank you !!

**Comment by nitinexclusively** [comment]
Any comment  regarding above update will be helpful !! Thank you

**Comment by keszybz** [comment]
Please submit the patch as a pull request. Nobody will look at this if it's in some obscure attachment.

**Comment by cerebro1** [comment]
Hey @nitinexclusively @anitazha @bluca ,
I am an Outreachy Applicant in contribution phase. I am supposed to pick a task marked as please-submit-as-pr. From what i understand here, i think i should be able to implement this. What is your suggestion here ? Could i take this up?

**Comment by bluca** [comment]
> Hey @nitinexclusively @anitazha @bluca , I am an Outreachy Applicant in contribution phase. I am supposed to pick a task marked as please-submit-as-pr. From what i understand here, i think i should be able to implement this. What is your suggestion here ? Could i take this up?

Yes, this looks doable, give it a try and let us know if you need help

**Comment by cerebro1** [comment]
Thanks!
Just one query :
In case, bios_version data is unavailable( could be a case with some vendor ), do i need to mention some fallback or ignore that ?

**Comment by cerebro1** [comment]
> > Hey @nitinexclusively @anitazha @bluca , I am an Outreachy Applicant in contribution phase. I am supposed to pick a task marked as please-submit-as-pr. From what i understand here, i think i should be able to implement this. What is your suggestion here ? Could i take this up?
> 
> Yes, this looks doable, give it a try and let us know if you need help

Thanks!
Just one query :
In case, bios_version data is unavailable( could be a case with some vendor ), do i need to mention some fallback or ignore that ?
`bios_date` and `bios_vendor` are other details related to bios.
Though dmi data could be unreliable so i will not play around it. Let me know in case i need to add any fallback else will handle error.
Thanks!

**Comment by cerebro1** [comment]
Raised PR https://github.com/systemd/systemd/pull/23068

**Comment by nitinexclusively** [comment]
> Please submit the patch as a pull request. Nobody will look at this if it's in some obscure attachment.

Thank you for your comment .. Sorry for this , Its my bad , i should have submitted the patch ..

**Comment by nitinexclusively** [comment]
> Hey @nitinexclusively @anitazha @bluca , I am an Outreachy Applicant in contribution phase. I am supposed to pick a task marked as please-submit-as-pr. From what i understand here, i think i should be able to implement this. What is your suggestion here ? Could i take this up?

Thank you for taking this up !!

**Comment by cerebro1** [comment]
@nitinexclusively This is now fixed and merged in main repo. Thanks!

**Comment by nitinexclusively** [comment]
> @nitinexclusively This is now fixed and merged in main repo. Thanks!
Thank you for this work and to all reviewers !
