### ISSUE TITLE
Issue in udev man page

### ISSUE THREAD

**Issue by hmartink** [systemd/systemd#22724]
'''
Dear udev maintainer,
the manpage-l10n project maintains a large number of translations of
man pages both from a large variety of sources (including udev) as
well for a large variety of target languages.

During their work translators notice different possible issues in the
original (english) man pages. Sometimes this is a straightforward
typo, sometimes a hard to read sentence, sometimes this is a
convention not held up and sometimes we simply do not understand the
original.

We use several distributions as sources and update regularly (at
least every 2 month). This means we are fairly recent (some
distributions like archlinux also update frequently) but might miss
the latest upstream version once in a while, so the error might be
already fixed. We apologize and ask you to close the issue immediately
if this should be the case, but given the huge volume of projects and
the very limited number of volunteers we are not able to double check
each and every issue.

Secondly we translators see the manpages in the neutral po format,
i.e. converted and harmonized, but not the original source (be it man,
groff, xml or other). So we cannot provide a true patch (where
possible), but only an approximation which you need to convert into
your source format.

Finally the issues I'm reporting have accumulated over time and are
not always discovered by me, so sometimes my description of the
problem my be a bit limited - do not hesitate to ask so we can clarify
them.

I'm now reporting the errors for your project. If future reports
should use another channel, please let me know.

Man page: udev.7
Issue:    \\&. → :

"Example for debugging uevent processing for network interfaces\\&."
'''

**Comment by yuwata** [comment]
In the source, `man 7 udev`, and https://www.freedesktop.org/software/systemd/man/udev.html#OPTIONS, I cannot find anything strange characters. I guess this is a bug in translating xml to po. Closing.

**Comment by hmartink** [comment]
I'm not sure what you mean with strange characters. The issue is right there in: https://www.freedesktop.org/software/systemd/man/udev.html#OPTIONS
In words:
Please replace the full stop after "interface" in the line "Example for debugging uevent processing for network interfaces" by a colon.

(Maybe you are confused because your tool chain converts a full stop to "\&." in the man source, but this is not the issue here).

**Comment by yuwata** [comment]
Ah, thank you for the explanation. Fix is waiting in #22725.
