### ISSUE TITLE
how to set OnUnitActiveSec with an environment variable value at systemd timer?

### ISSUE THREAD

**Issue by dayDPTR** [systemd/systemd#22747]
**systemd version the issue has been seen with**
 > v249

**Used distribution**
 > openwrt 1505

**Linux kernel version used** (`uname -a`)

 > `4.4.60`

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > systemd timer can work well

**Unexpected behaviour you saw**
 > systemd timer `OnUnitActiveSec` argument error

**Steps to reproduce the problem**
 > systemctl status auto_upgrade.timer

**Additional program output to the terminal or log subsystem illustrating the issue**

I am writing a systemd timer to trigger a periodic event, but requires that load the timer period from an environment variable rather than setting it with a fixed constant.

I wrote systemd timer name  `auto_upgrade.timer` as below:
```
[Unit]
Description=auto upgrade timer

[Timer]
EnvironmentFile=/etc/conf/auto_upgrade.conf
#Execute job if it missed a run due to machine being off
Persistent=true
#Run every n minutes thereafter
OnUnitActiveSec=${check_period}m
Unit=auto_upgrade.service

[Install]
WantedBy=sysinit.target
```
but there is an invalid argument at the line `OnUnitActiveSec=${check_period}m` as below:
```
root@212:/# systemctl status auto_upgrade.timer
● auto_upgrade.timer - auto upgrade timer
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
```
actually `check_period` was defined at `/etc/conf/auto_upgrade.conf`. If modified the line as: `OnUnitActiveSec=20m` , no error happens as below:
```
root@212:/# systemctl status auto_upgrade.timer
● auto_upgrade.timer - auto upgrade timer
   Loaded: loaded (/etc/systemd/system/auto_upgrade.timer; disabled; vendor preset: enabled)
   Active: inactive (dead)
```
I doubt whether we can set the timer argument with an environment variable. any expert can help resolve this problem ?

Thanks a lot

**Comment by yuwata** [comment]
Not only OnUnitActiveSec=, but setting value through environment variable is not supported in general. Please try to use `%` specifier. See [systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers).

**Comment by dayDPTR** [comment]
go through the specifier table just now, it seems that no "%*" cannot be leveraged to pass my needed parameters to OnUnitActiveSec.
I am wonder Why environment variable is not supported at systemd service, timer, so on.
actually, support environment variable is very meaningful.
for example, in some timer use cases, OnUnitActiveSec cannot be directly set with a digit/digits because it may depend on one of the user configuration items which saved on  user config file(key-value format).
if not support, we may need to write a script to read user config file to get timer period, then modify the systemd timer file to replace the value of OnUnitActiveSec with the timer period. then start the timer service. i think it's very complicated.

**Comment by yuwata** [comment]
I am not sure that if I fully understand what you want to do, but maybe `systemctl set-property` can be used, instead of modifying the timer unit file. Or, you can create a drop-in config for the timer unit from the environment file.

**Comment by dtardon** [comment]
> for example, in some timer use cases, OnUnitActiveSec cannot be directly set with a digit/digits because it may depend on one of the user configuration items which saved on user config file(key-value format). if not support, we may need to write a script to read user config file to get timer period, then modify the systemd timer file to replace the value of OnUnitActiveSec with the timer period.

You've just described a [generator](https://www.freedesktop.org/software/systemd/man/systemd.generator.html). Which is IMHO the right solution for the described case.
