### ISSUE TITLE
journalctl memory leak.

### ISSUE THREAD

**Issue by budRich** [systemd/systemd#22743]
**systemd version the issue has been seen with**
 >  250.4

**Used distribution**
 >  btw, I use Arch

**Linux kernel version used** (`uname -a`)

 > `5.16.14-arch1-1 #1 SMP PREEMPT Fri, 11 Mar 2022 17:40:36 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > intel i7 (its a thinkpad x280)

**Expected behaviour you didn't see**
 > simple `journalctl -f ....` consuming less than 5MB RSS

**Unexpected behaviour you saw**
 > simple `journalctl -f ....` consuming more than 200MB RSS

**Steps to reproduce the problem**
 > I tried a couple of different journalctl commands with different units and got quite different results:  
  - `NO_COLOR=1 journalctl --user -b -feu xfce*  -o cat` -> 221MB
  - `NO_COLOR=1 journalctl -b -feu keyd  -o cat` -> 40MB
  - `NO_COLOR=1 journalctl --user -b -feu i3wm  -o cat` -> 75MB

(`ps -ao rss,command | grep journalctl | grep -v grep`) <- command to get RSS usage

I measured this with both `ps` and `lxtasks` both showing the same results. And i made sure i was only running one journalctl process at a time.

I also tried, different commandline option combinations: (with/without `-x`, `-b`, `-n`), but it didn't make any difference to the RSS use.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by budRich** [comment]
I tried purging the journal, which before the purge was ~1.5G.  
```shell
$ du -h /var/log/journal
  1.4G
# journalctl --rotate --vacuum-time=1m
$ du -h /var/log/journal
  17M
$ journalctl --user -fxeu i3wm -o cat
.... # meanwhile in another terminal:
$ ps -ao rss,command | grep journalctl | grep -v grep
  8444 journalctl --user -fxeu i3wm -o cat
```

now the usage is much lower (8M compared to 70M), but still, something is not right here. I don't think 1.5G is unreasonable large logs.

from #archlinux@libera:  
> there is probably a bug in the parser/search which is leaking memory. This reminds me of when I wrote the regex search feature for tmux. It had a couple of issues

**Comment by Edu4rdSHL** [comment]
70MB for regexp-ing a 1.5GB log file is not a memory leak, if you know a little of programming, open and load a 1.5GB file, then do some regexp on it, you will find the answers.

**Comment by vcaputo** [comment]
@budRich Practically all journal IO in systemd/sd-journal is performed using mmap's shared file-backd (reclaimable) mappings.  As a result you must subtract shared pages from the resident set size to get a real sense of the process-specific memory consumption.  Please close this issue if after you've subtracted shared things look sane, I don't think `ps` makes this convenient but the default top output includes both SHR and RSS columns.  This isn't the first time this kind of issue has been created, and definitely won't be the last.  The decision to use mmap() IO with the journal has produced a lot of confusion in this area.
