### ISSUE TITLE
TEST-68-PROPAGATE-EXIT-STATUS fails randomly

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#22755]
E.g. https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/s390x/s/systemd-upstream/20220315_142252_35ed4@/log.gz and
https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/s390x/s/systemd-upstream/20220315_142856_d72a3@/log.gz

**Comment by bluca** [comment]
mmh looks like we didn't fix this completely @keszybz
