### ISSUE TITLE
machinectl shell broken between archlinux and debian-jessie

### ISSUE THREAD

**Issue by encbladexp** [systemd/systemd#2277]
I am using systemd v228 with systemd-nspawn/machinectl and an Debian Jessie Guest. `machinectl login debian-jessie` works well, but `machinectl shell debian-jessie` dont. I terminates with the following error message:

```
[root@server:~] # machinectl shell debian-jessie /bin/bash
Failed to get shell PTY: Cannot set property StandardInputFileDescriptor, or unknown property.
```

I there an Issue between different Host and Guest systemd Versions and nspawn? Using Ubuntu xenial as Guest (same systemd Version) works, but Jessie uses v215.

Any ideas how to get debian stable working as guest with `machinectl shell`?

**Comment by georgyo** [comment]
`machinectl shell` was introduced in v225. Your guest and host both need to be at least that version. For that command to work. You  can try upgrade the guest to at least that version.

`machinectl login` has existed for a while now and will put you into a psudo tty, allowing you to log into your container.

Lastly, if a password is too abrasive, you can install sshd in your container template and use ssh keys.

**Comment by encbladexp** [comment]
OK, thanks for the Info. So wen can close this for now.
