### ISSUE TITLE
systemctl set-property app.service WatchdogSec=0 doesn't work

### ISSUE THREAD

**Issue by cagnulein** [systemd/systemd#22776]
**systemd version the issue has been seen with**

 241

**Used distribution**

debian 10.9

**Linux kernel version used** (`uname -a`)
4.19.0

**CPU architecture issue was seen on**
x68_64

**Expected behaviour you didn't see**
I have a service that is configured with WatchdogSec=15. I need to debug it, so I need to temporarily disable the watchdog so it does not get killed while I have it stopped in the debugger.
I tried
systemctl set-property app.service WatchdogSec=0

but I am getting
Unknown assignment WatchdogSec=0.
It is not the 0 part; I get the same with any another number.
Is there a(ny other) way to temporarily disable the watchdog?
With old versions of systemd, I was used to change the app.service file and calling a “systemctl  daemon-reload” made the trick. BUT with the actual versions of systemd, calling a daemon-reload cause the process to receive a SIGABRT from the watchdog. So is there a regression? Or something is changed in the behaviour?
Thanks

**Unexpected behaviour you saw**
`systemctl set-property app.service WatchdogSec=0`

but I am getting
`Unknown assignment WatchdogSec=0`

**Steps to reproduce the problem**
systemctl set-property app.service WatchdogSec=0

**Comment by bluca** [comment]
It is intentionally not supported to change these settings at runtime. Change the unit with a drop-in, in /run to make it temporary, daemon-reload and then restart it.

**Comment by poettering** [comment]
this can't work. we tell services the selected watchdog timeout via an env var, and UNIX doesn't really allow those to be updated for running processes from the outside. Hence the concept simply doesn't allow this.

That said, I think what you are actually looking for is `systemctl service-watchdogs 0`. Hence closing.

**Comment by cagnulein** [comment]
@poettering thanks for the quick response! Probably i'm missing something, but if i do a 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/48216/159220867-639d14e4-e91e-4b87-86e5-d8a582e3246f.png)

**Comment by poettering** [comment]
Your version is way too old. Sorry. This is an upstream bug tracker, we only cover issues in the two most recent upstream versions here. Thats 249 and 250 right now. 241 is *ancient* compared to that.
