### ISSUE TITLE
systemd-networkd: Unable to acquire DHCPv6 lease

### ISSUE THREAD

**Issue by jpds** [systemd/systemd#22795]
**systemd version the issue has been seen with**

250.4

**Used distribution**

Gentoo

**Linux kernel version used** (`uname -a`)

`5.15.25-gentoo-dist`

**CPU architecture issue was seen on**

x64_86

**Unexpected behaviour you saw**

After upgrading from `249.9` to `250.4`, my router is no longer able to acquire a DHCPv6-PD lease:

```
Mar 19 11:11:40 router systemd-networkd[556]: enp1s0: DHCPv4 address 100.a.b.c/22, gateway 100.a.b.1 acquired from 141.zzz.yyy.xxx
Mar 19 11:30:44 router systemd-networkd[556]: enp1s0: DHCPv6 lease lost
```

This however worked fine with the same configuration before:

```
Mar 19 01:30:43 router systemd-networkd[697]: enp1s0: DHCPv4 address 100.a.b.c/22 via 100.a.b.1
Mar 19 01:30:45 router systemd-networkd[697]: enp1s0: DHCP6: received PD Prefix 2a01:....::/56
Mar 19 01:30:45 router systemd-networkd[697]: enp3s0: DHCPv6-PD address 2a01:.../64 (valid for 1d, preferred for 20h)
Mar 19 01:30:45 router systemd-networkd[697]: enp2s0: DHCPv6-PD address 2a01:.../64 (valid for 1d, preferred for 20h)
```

My WAN interface is configured as:

```
[Match]
Name=enp1s0

[Network]
Description=Link to ISP
Address=2a01:.../128
DHCP=yes
IPv6AcceptRA=yes
LinkLocalAddressing=ipv6

[DHCPv4]
UseHostname=no
UseDNS=no
UseNTP=no
UseSIP=no
UseRoutes=no
UseGateway=yes

[IPv6AcceptRA]
UseDNS=no
DHCPv6Client=yes

[DHCPv6]
ForceDHCPv6PDOtherInformation=yes
PrefixDelegationHint=::/56
UseHostname=no
UseDNS=no
UseNTP=no

[CAKE]
Bandwidth=500M

[Route]
# This will apply to the gateway supplied via DHCP.  If you manually specify
# your gateway, put it here instead.
Gateway=_dhcp4

InitialCongestionWindow=80
InitialAdvertisedReceiveWindow=80
```

**Comment by yuwata** [comment]
The setting `ForceDHCPv6PDOtherInformation=` was removed in v250. Please try to use `DHCPv6Client=always`.

If it does not help the situation, then please provide the debugging logs of networkd, it can be generated by creating the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by jpds** [comment]
@yuwata I adjusted my configuration as you suggested, and it has indeed fixed the issue. Thank you!

**Comment by yuwata** [comment]
@naraghavan Please open a new issue page with debugging logs.

Note, DHCP6 lease is never saved as a file, IIRC.
