### ISSUE TITLE
Incorrect touchpad dimensions on Thinkpad L14 Gen1

### ISSUE THREAD

**Issue by AmadorBarragan** [systemd/systemd#22793]
**systemd version the issue has been seen with**
 > systemd 249 (v249.9-1.fc35)

**Used distribution**
 > Fedora Workstation 35

**Linux kernel version used** (`uname -a`)

 > `Linux fedora 5.16.15-201.fc35.x86_64 #1 SMP PREEMPT Thu Mar 17 05:45:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

**CPU architecture issue was seen on**
 > x86-64

The touchpad on my laptop doesn't feel right, and especially annoying is the unreasonably fast scroll speed. Looking around on how to troubleshoot it I noticed that the output of `libinput list-devices` said 70x50mm, while the actual physical dimensions are 100x70mm.

Libinput documentation said that I needed to run `libinput measure touchpad-size`, try the suggested hwdb.d entry and submit a patch to systemd.  I don't know a thing about using git , so hopefully this is the right place to ask for help in order to get the fix into systemd.

I followed the instructions on https://github.com/systemd/systemd/blob/main/hwdb.d/60-evdev.hwdb and  now `libinput list-devices` says the dimensions are 100x71mm. I ran `libinput measure touchpad-size` thrice and it keeps insisting on the 71mm, while in reality it is more like 69.5mm, I don't know how to adjust it or if it's advisable to do so. 

Thus, the hwdb.d entry to be added is, as suggested by `libinput measure touchpad-size` : 

```
# Lenovo Thinkpad L14 Gen1 (AMD)
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnLENOVO:*pvrThinkPadL14Gen1**
 EVDEV_ABS_00=::44
 EVDEV_ABS_01=::50
 EVDEV_ABS_35=::44
 EVDEV_ABS_36=::50
```

**Considerations:**

1. The dmi match may need tuning, I used the one provided by `libinput measure touchpad-size` as is.
2. While the actual physical dimensions of the touchpad are 100x70mm, or more like 100x69.5mm, the previous hwdb.d entry causes libinput list devices to report the dimensions as 100x71mm.

This is the first time I use github for anything so I apologize if I did anything wrong, hopefully you can call out any mistakes I had.

**Comment by whot** [comment]
@AmadorBarragan: The kernel only allows integers for resolution/mm so there's always *some* discrepancy between the touchpad sizes, not much we can do about that. If it's less than 5mm it usually doesn't matter. The hwdb entry above looks fine, so please do submit a PR for this.

> especially annoying is the unreasonably fast scroll speed

fwiw, the scroll speed issue is more likely https://gitlab.gnome.org/GNOME/gtk/-/issues/3631

**Comment by Dewinsy** [comment]
@whot I am an Outreachy intern. I am currently working on a pull request for this.

**Comment by taniishkaaa** [comment]
@AmadorBarragan can you tell me the trackpad identifier?
