### ISSUE TITLE
networkd: allow 6to4 tunnels (Remote=any)

### ISSUE THREAD

**Issue by zdzichu** [systemd/systemd#2279]
According to http://www.tldp.org/HOWTO/Linux+IPv6-HOWTO/configuring-ipv6to4-tunnels.html , configuring 6to4 tunnel requires wildcard Remote=any:

`/sbin/ip tunnel add tun6to4 mode sit ttl <ttldefault> remote any local <localipv4address>`

This is not allowed by networkd:
`[/etc/systemd/network/6to4tunnel.netdev:7] Tunnel address is invalid, ignoring assignment: any`

The message is caused by:

``` ini
[NetDev]
Name=6to4t
Kind=sit

[Tunnel]
Local=176.56.236.173
Remote=any
TTL=64
```

**Comment by zonque** [comment]
Please add some more in-depth description of what you picture.

**Comment by zdzichu** [comment]
Sorry, pressed enter too fast. Description added.

**Comment by poettering** [comment]
@ssahani any idea?

**Comment by ssahani** [comment]
@poettering that's correct I will enhance it to support 'any'.
