### ISSUE TITLE
Firefox freezes if new volumes get mounted

### ISSUE THREAD

**Issue by plomari** [systemd/systemd#22790]
**systemd version the issue has been seen with**
 > Version: 250.4-1

**Used distribution**
 > Debian unstable

**Linux kernel version used** (`uname -a`)
Linux debian 5.10.102 #1.0.my SMP Wed Feb 23 18:37:42 CET 2022 x86_64 GNU/Linux
(Yes, this is a self-built kernel.)

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Firefox doesn't notice anything

**Unexpected behaviour you saw**
 > Firefox freezes for multiple seconds! It doesn't update graphics, X11 shows "old content". After that, it renders itself again and continues normally.

**Steps to reproduce the problem**
 > Just mount an external drive.

**Additional program output to the terminal or log subsystem illustrating the issue**

Well,  just to explain: I don't know what's happening. Analyzing this issue should be fun for developers. Note that Firefox only freezes if it has run for some days.

It might not be system'd fault, but I'm reporting it to systemd for 2 reasons:
- systemd broadcasts such events over dbus, giving reasons it could be the trigger to such problems
- systemd team is better at analyzing platform-specific behavior than firefox' team

Like I said, this should be fun for developers to analyze. For me, personally, as experienced developer and Linux user and long time firefox user even, this is entirely mysterious.

**Comment by poettering** [comment]
Sorry, but from your report I see nothing that would indicate systemd having anything to do with this. Smell's like IO scheduler issues, i.e. slow USB (not sure what "external drive" means). Linux kernels are notoriously bad at dealing with parallel IO from block devices that have extremely different speeds.

If you use a current, distro-built kernel, does it work then?

Quite frankly, this looks like the wrong place for tracking htis. Please contact your distro. It looks like some interaction of your old kernel with an ancient graphics stack (X11? yikes), not sure what systemd would have to do with that.

**Comment by plomari** [comment]
I tried with a 500KB filesystem image on a tmpfs (via loop), and it shows the same problem. Most likely not an I/O problem.

>If you use a current, distro-built kernel, does it work then?

That would require a reboot, can test in some days or weeks.

>Quite frankly, this looks like the wrong place for tracking htis.

You're probably right. Even if systemd is involved in this, the burden of proof should probably be on the apparently misbehaving user application first.

Still, I think it's not a bad guess. I know from past bugs (and journalctl) that systemd does something with manual mounts, instead of ignoring them and leaving everything to the kernel. Also, I never had this problem under systemv-init, but since I can't "prove" this, that would likely be a claim that could be interpreted as inflammatory - still made me look here first. Last but not least, most of the firefox team got fired and I doubt they care.

> old kernel

The 5.10 line is a long term release with an EOL at end of 2026. You as a developer of widely used system software will have to deal with it for a long time, even after EOL.

> with an ancient graphics stack (X11? yikes)

What else should I use? I need something that actually works and supports the software I have to use. Do note that only firefox freezes, but it's the most complicated user application on my system with the most interactions system interactions. A trivial video player runs without interruption.

> not sure what systemd would have to do with that.

Because systemd interacts with everything. Its dbus API is increasingly a proxy between userspace and kernel. Mounting a drive/image is a system operation and should not affect user applications badly. systemd is the first place to look.

**Comment by keszybz** [comment]
Sorry, but your report is void of any information that we could use to figure out what is going on. We don't know what versions of software you are using, and for a self-built kernel, just specifying the version is not enough, we'd need to know the details of the build config and patches applied. Diving into this would be a huge effort, and we don't have the resources for this. You might want to talk with the maintainers of the distribution, they know more about the specific setup, or might be able to figure out what is going on if you provide them with sufficient detail (logs, package versions, etc.).

**Comment by plomari** [comment]
systemd might be innocent for once. While it's true that there's dbus spam the moment a mount/umount happens, there's no indication Firefox uses these messages. Instead, Firefox, or actually glib/GTK, uses poll() on `/proc/mounts` to check for changes (using POLLERR on the opened file, didn't know this worked, neat trick even if a rather awful kernel interface). It then spends a lot of time dispatching g_signals and parsing XML for functionality I don't even use. Probably builds up a large list of signal receivers without properly removing or something, which would explain why it takes so long to reproduce. What a curse, but a different one.
