### ISSUE TITLE
systemd-resolved: why resolved serve /etc/hosts content ?

### ISSUE THREAD

**Issue by r4iponce** [systemd/systemd#22809]
**systemd version the issue has been seen with**
 > systemd 249.9

**Used distribution**
 > fedora 35

**Linux kernel version used** (`uname -a`)
 > `Linux hostname 5.16.15-201.fc35.x86_64 #1 SMP PREEMPT Thu Mar 17 05:45:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Normally resolver dont serve /etc/hosts file but with systemd-resolved localhost return 127.0.0.1 (from /etc/hosts) instead of NXDOMAIN normally return by resolver 

**Unexpected behaviour you saw**
 > Systemd-resolved  return content of /etc/hosts instead of record send by remote resolver

**Steps to reproduce the problem**
 > Use dns debug tools (dig for me) and make a query to systemd resolved with a domain contained into /etc/hosts

**Additional program output to the terminal or log subsystem illustrating the issue**

```
% dig @127.0.0.53 localhost
; <<>> DiG 9.16.24-RH <<>> localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64230
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;localhost.			IN	A

;; ANSWER SECTION:
localhost.		0	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Mar 21 18:24:57 CET 2022
;; MSG SIZE  rcvd: 54
```

**Comment by poettering** [comment]
It's a local DNS cache, stub, mDNS, LLMR client and some other stuff, and makes that available via a local stub. If you don't want any of that, don't use it?

Anyway, this is a bug report and RFE tracker, not a forum for support and questions. Consider contacting the systemd mailing list if you have further questins/need help.
