### ISSUE TITLE
is resolved able to store dns query to ipset tables?

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#22817]
I want to route specific internet sites to different gateways. I used to use ipset with dnsmask to set the rules in iptables. Does systemd-resolved has the feature to store the dns query of specific domain names or domain name lists in ipset tables? Or is it possible to trigger a script when a specific domain name matches the dns request?

**Comment by poettering** [comment]
This is not a support forum but a bug and issue track.

And not it doesn't support anything like that.
