### ISSUE TITLE
Improve "A stop job is running for Session X" message

### ISSUE THREAD

**Issue by bjourne** [systemd/systemd#22819]
When I reboot my desktop systemd tells me that "A stop job is running for Session 5 of User bjourne". This message is less informative than it could be. It should be formulated like: "Waiting for the stop job $path_or_identifier for session 5 of user bjourne to finish" $path_or_identifier is either the path to the binary or something that identifies the stop job. This would make it easier for me to debug the problem. Also, neither session nor user should be capitalized.

**Comment by poettering** [comment]
Which systemd version are you running?

Please always fill out the provided reporting form, it asks questions like this for a reason.

The message has been changed recently already.

**Comment by bjourne** [comment]
systemd 250 (250.4-2-arch)

**Comment by dtardon** [comment]
This has been implemented in https://github.com/systemd/systemd/commit/3889fc6fc347f0e12070f7b873d065508c8df816.

**Comment by utt54321** [comment]
It seems not merged （https://github.com/systemd/systemd/commit/3889fc6fc347f0e12070f7b873d065508c8df816）
Is it possible that anyone will help solving?

**Comment by dtardon** [comment]
> It seems not merged （[3889fc6fc347f0e12070f7b873d065508c8df816）](https://github.com/systemd/systemd/commit/3889fc6fc347f0e12070f7b873d065508c8df816）)

Huh? https://github.com/systemd/systemd/pull/20123 _is_ merged.
