### ISSUE TITLE
resolved incorrectly uncompresses target names in SRV records

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#22838]
**systemd version the issue has been seen with**
`main` (commit 7a692931ab1ce92916edf737837b7ff5cf87a2e9)

**Report**

From code inspection, it looks like resolved is uncompressing target names in SRV records: https://github.com/systemd/systemd/blob/5c09daf8ff337d05849b55918aa004aab282bfaf/src/resolve/resolved-dns-packet.c#L1733 — see the third argument to `dns_packet_read_name()`. It’s not supposed to do that.

This is not allowed in [the spec](https://datatracker.ietf.org/doc/html/rfc2782#page-4):
> Unless and until permitted by future standards
> action, name compression is not to be used for this field.

I’m not aware of any standards which supersede/amend RFC 2782 which change that.

This is highly related to a [previous bug report](https://github.com/systemd/systemd/issues/9793) which was about *writing out* SRV records. In this report I’m concerned with *reading SRV records*. The [previous fix](https://github.com/systemd/systemd/pull/9828) only affected writing out records. I spotted it in the context of [checking a similar behaviour in GLib](https://gitlab.gnome.org/GNOME/glib/-/issues/2622).

All that said, I don’t know if systemd should be changed here — the principle of being relaxed in what input is accepted suggests that it *should* accept compressed targets, and I can’t think of any harm which would come from doing so. In fact, uncompressing targets from DNS servers which have (incorrectly) compressed them would avoid issues with forwarding those targets further, as forwarding the packet is likely to change offsets and hence completely break the compression pointers. However, I’m definitely not an expert on DNS or SRV records, so I’m probably missing something.

In any case, I suggest there are two courses of action here:
 1. Either stop accepting compressed targets in SRV records,
 2. or, add a comment in the code to explicitly document why they’re accepted despite the RFC saying not to.

**Comment by poettering** [comment]
I am pretty sure we should uncompress the names for SRV too, even if the RFC doesn't say so. But yeah a comment should be added.
