### ISSUE TITLE
When processing a coredump abort after some max time of processing

### ISSUE THREAD

**Issue by Bob131** [systemd/systemd#2286]
I'm not sure this is a bug per se, as the result is just sub-optimal rather than fatal, but I've noticed on my X220 that segfaults in certain applications and the subsequent kick-off of the systemd-coredump process cause uncomfortably high temps and significant battery drain which can last for an extended period of time (rarely 10+ minutes). Since I don't have much use for coredumps, I've just disabled them via sysctl, but I was wondering if there was some tweaking that could be done to either adjust the defaults for such systems or reduce the runtime/load of systemd-coredump itself

**Comment by poettering** [comment]
We simply run the elfutil's coredump stacktracer on each coredump, and that consumes the CPU. I am not sure what we could do in systemd about this though... We could of course set a time limit on things, for example say that we rather abort processing a coredump than work for than 30s or so on it... WOuld that work for you?

**Comment by Bob131** [comment]
Yes, that'd do just fine. Thanks!
