### ISSUE TITLE
please do NOT migrate the cgroups of my processes 

### ISSUE THREAD

**Issue by csrenren** [systemd/systemd#22874]
Systemd provides pam_systemd.so for PAM module and takes effect for many commands such as 'su'.

When executing 'su' command, pam_systemd.so will be called and the process will be moved from /system.slice/{our-service}/{our-sub-group} to the /user.slice, this is what we do NOT expect.

Our service will create many child processes from shell scripts, execution of 'su' command is a common case, we have NO right to prohibit such behavior, but we MUST ensure that the whole process tree always being attached to /system.slice/{our-service}/{our-sub-group} with our designed resource limitation. systemd moves processes to /user.slice, this behavior is unacceptable.

Furthermore, the configuration 'Delegate=yes', it doesn't seem to have any effect.

So, we strongly recommend that systemd provides this feature: provide a switch configuration item to ensure that systemd will never move processes under /system.slice/{our-service}/** to any other cgroups.

Thanks.

**Comment by g0tar** [comment]
If I understand your problem correctly, you don't want the `pam_systemd` to do what's intented to do. What I don't understand is why you don't expect this obvious behaviour and simply don't disable it in PAM then.

**Comment by csrenren** [comment]
> If I understand your problem correctly, you don't want the `pam_systemd` to do what's intented to do. What I don't understand is why you don't expect this obvious behaviour and simply don't disable it in PAM then.

on Red Hat, pam_systemd.so is declared in the system-auth file which is included by many pam files, if I disable it, that means the pam_systemd being disabled for the whole system environment, may it cause any side effects ??  We do not want to change the default behaviour for the whole system, we do just expect systemd  donot move the cgroups of our service processes.

**Comment by TriMoon** [comment]
@csrenren 
I think to better understand what is going on and why, you should provide exact steps to reproduce.
That way readers can understand better and provide better feedback to all parties.
As it is now, it is unclear if `systemd` is in fault or your setup in this case.

Most common bugs are caused by wrong usage of the `systemd` system with all its parts being so many :wink:

**Comment by keszybz** [comment]
Since you're using RHEL, it'll be much more effective if you discuss it with support there.

**Comment by g0tar** [comment]
You don't need to modify (entire system scope) `system-auth`, as this file is probably included in `/etc/pam.d/su`. So you can easily make the changes limited to `su`.

This of course might be also too much, as it would alter every `su` invocation, so in the next step you could try to make `pam_systemd` excluded on per-user basis (if your scripts use their own, specific ones) or in the worst case - prepare your own `su` binary that uses different `/etc/pam.d/su-local_scripts` configuration.

**Comment by poettering** [comment]
"su" is about opening user sessions. Use "setpriv" if you just want to change privs without opening user sessions.
