### ISSUE TITLE
systemd-cryptsetup does not ask for password if any TPM2 operation fails with ENOTRECOVERABLE

### ISSUE THREAD

**Issue by aafeijoo-suse** [systemd/systemd#22870]
**systemd version the issue has been seen with**
 > v250

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux localhost.localdomain 5.16.15-1-default #1 SMP PREEMPT Wed Mar 16 23:33:05 UTC 2022 (d8f0e40) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Be able to boot the system by entering a text password if the TPM is cleared.

**Unexpected behaviour you saw**
 > Unable to boot.

**Steps to reproduce the problem**
 > 1. Example FS Layout (`cryptsetup luksFormat -y -v --type luks2 /dev/vda3`). 
```
dev@localhost:~> lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sr0            11:0    1 912.9M  0 rom   
vda           253:0    0    20G  0 disk  
├─vda1        253:1    0   512M  0 part  /boot/efi
├─vda2        253:2    0     2G  0 part  /boot
└─vda3        253:3    0  17.5G  0 part  
  └─cr-auto-1 254:0    0  17.5G  0 crypt /var
                                         /srv
                                         /root
                                         /home
                                         /opt
                                         /usr/local
                                         /
```
 > 2. `systemd-cryptenroll --tpm2-device=auto /dev/vda3`
 > 3. Add `tpm2-device=auto` to cr-auto-1 in /etc/crypttab
 > 4. Clear TPM SRK (run `tpm2_clear`)
 > 5. Reboot.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
sh-4.4# systemctl status "systemd-cryptsetup@cr\x2dauto\x2d1.service"
× systemd-cryptsetup@cr\x2dauto\x2d1.service - Cryptography Setup for cr-auto-1
     Loaded: loaded (/etc/crypttab; generated)
     Active: failed (Result: exit-code) since Thu 2022-03-24 08:01:35 UTC; 46min ago
       Docs: man:crypttab(5)
             man:systemd-cryptsetup-generator(8)
             man:systemd-cryptsetup@.service(8)
    Process: 404 ExecStart=/usr/lib/systemd/systemd-cryptsetup attach cr-auto-1 /dev/disk/by-uuid/7bb5cda8-0a95-42ef-b763-7386c5c72e49 none x-initrd.attach,tpm2-device=auto (code=exited, status=1/FAILURE)
   Main PID: 404 (code=exited, status=1/FAILURE)

Mar 24 08:01:35 localhost systemd[1]: Starting Cryptography Setup for cr-auto-1...
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/7bb5cda8-0a95-42ef-b763-7386c5c72e49.
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Automatically discovered security TPM2 token unlocks volume.
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x00000921)
Mar 24 08:01:35 localhost systemd-cryptsetup[404]: Failed to load HMAC key in TPM: tpm:warn(2.0): authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode
Mar 24 08:01:35 localhost systemd[1]: systemd-cryptsetup@cr\x2dauto\x2d1.service: Main process exited, code=exited, status=1/FAILURE
Mar 24 08:01:35 localhost systemd[1]: systemd-cryptsetup@cr\x2dauto\x2d1.service: Failed with result 'exit-code'.
Mar 24 08:01:35 localhost systemd[1]: Failed to start Cryptography Setup for cr-auto-1.
```

This happens in the `tpm2_unseal` method:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/shared/tpm2-util.c#L1132-L1135

Which is called from:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/cryptsetup/cryptsetup.c#L1328-L1338

Then ends here:

https://github.com/systemd/systemd/blob/e5531be27b034a7f4c517a0f76cbcbabe63c960e/src/cryptsetup/cryptsetup.c#L1906-L1909

Is the expected behavior not to continue with the boot process (and not prompt for password) if any of the TPM2 operations return ENOTRECOVERABLE?

**Comment by poettering** [comment]
We should probably provide a proper log message about DA lockout mode. And yes, we should not fail completely, but try with a pw
