### ISSUE TITLE
IOWeight= doesn't set io.bfq.weight (again)

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#22897]
**systemd version the issue has been seen with**
 > latest main (f777e74)

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `Linux xxx 5.18.0-0.rc0.20220325git34af78c4e616.7.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 25 15:53:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

**CPU architecture issue was seen on**
 > x86_64

Same as in #20519 - setting `IOWeight=` doesn't seem to affect the value of `io.bfq.weight`:

```
# systemctl --version
systemd 250 (250-1651-gf777e74)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
# systemd-run -u test.service -p IOWeight=666 /bin/sleep infinity
Running as unit: test.service
# systemctl is-active test.service
active
# systemctl show -p IOWeight test.service
IOWeight=666
# cat /sys/fs/cgroup/system.slice/test.service/io.bfq.weight 
default 151
```

/cc @yuwata @Werkov

**Comment by yuwata** [comment]
This is the expected result. `BFQ_WEIGHT(666)` is 151.

**Comment by mrc0mmand** [comment]
> This is the expected result. `BFQ_WEIGHT(666)` is 151.

Ah, I see, thanks!
