### ISSUE TITLE
DHCP request does not ask for domain-search (119) and DOMAIN_SEARCH_LIST is not set when system gets fresh lease

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#22893]
**systemd version the issue has been seen with**
 > …
systemd 249 (249.4+)

**Linux kernel version used** (`uname -a`)

 > `…`
Linux 5.15.30

**Expected behaviour you didn't see**
 > …
DHCP REQUEST should ask for the domain-search (119) and the leases file should get updated with `"DOMAIN_SEARCH_LIST=<>"`

**Unexpected behaviour you saw**
 > …
DHCP REQUEST's wireshark capture does not have domain-search (119) requested for. And the `/etc/resolv.conf` does not have any entry for the search list

**Steps to reproduce the problem**
 > …
Update the .network file with `UseDomains=true` and at DHCP server set ` option domain-search "example.com","example1.com";`
Once the DHCP request-response is exchanged, check for the resolv.conf and the `/run/systemd/netif/leases` file for the domain-search-list

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by sunharis** [comment]
I checked the issue https://github.com/systemd/systemd/issues/8174 and my system has this fix already running.

**Comment by sunharis** [comment]
@yuwata -or- @poettering Please check and suggest what i might be missing here ?

My network file is as below
`[Match]
Name=eth1
[Link]
MACAddress=08:94:ef:82:00:05
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=true
DHCP=true
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseNTP=true
UseHostname=true
SendHostname=true
UseDomains=true
`

DHCP server conf file is as below
`shared-network if0 {
  subnet 192.168.1.0 netmask 255.255.255.0 {
    authoritative;
    max-lease-time 300;
    min-lease-time 150;
    default-lease-time 300;
    next-server 192.168.1.1;
    range 192.168.1.20 192.168.1.45;
    option subnet-mask 255.255.252.0;
    option domain-name-servers 10.5.5.100, 10.5.5.1, 9.3.29.77;
    option domain-name "example.com";
    option domain-search "example.com","example1.com";
    option domain-name "aus.stglabs.ibm.com";
    option routers 192.168.1.1;
  } # 10.5.5.0/255.255.255.0 subnet_end
`

Lease file is as below
`
ADDRESS=192.168.1.21
NETMASK=255.255.252.0
ROUTER=192.168.1.1
SERVER_ADDRESS=192.168.1.1
NEXT_SERVER=192.168.1.1
T1=150
T2=262
LIFETIME=300
DNS=10.5.5.100 10.5.5.1 9.3.29.77
DOMAINNAME=aus.stglabs.ibm.com
CLIENTID=010894ef820005
`

resolv.conf is as below
`
nameserver 10.5.5.100
nameserver 10.5.5.1
nameserver 9.3.29.77
search .
`

I am expecting to see the resolv.conf updated as `search example.com, example1.com`

**Comment by yuwata** [comment]
Since e0c1341df2bc3b46ceaf1fb82da388a5d49b5897 (v243), we have a test for `UseDomains=`.

**Comment by yuwata** [comment]
> DHCP REQUEST's wireshark capture does not have domain-search (119) requested for. And the `/etc/resolv.conf` does not have any entry for the search list

Could you provide the captured packet?

**Comment by sunharis** [comment]
> > DHCP REQUEST's wireshark capture does not have domain-search (119) requested for. And the `/etc/resolv.conf` does not have any entry for the search list
> 
> Could you provide the captured packet?

Frame 2: 327 bytes on wire (2616 bits), 327 bytes captured (2616 bits)
Ethernet II, Src: WistronI_82:00:05 (08:94:ef:82:00:05), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
Internet Protocol Version 4, Src: 0.0.0.0, Dst: 255.255.255.255
User Datagram Protocol, Src Port: 68, Dst Port: 67
Dynamic Host Configuration Protocol (Request)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x8a5ec3fa
    Seconds elapsed: 1
    Bootp flags: 0x0000 (Unicast)
        0... .... .... .... = Broadcast flag: Unicast
        .000 0000 0000 0000 = Reserved flags: 0x0000
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: WistronI_82:00:05 (08:94:ef:82:00:05)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Request)
        Length: 1
        DHCP: Request (3)
    Option: (61) Client identifier
        Length: 7
        Hardware type: Ethernet (0x01)
        Client MAC address: WistronI_82:00:05 (08:94:ef:82:00:05)
    Option: (55) Parameter Request List
        Length: 9
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (6) Domain Name Server
        Parameter Request List Item: (12) Host Name
        Parameter Request List Item: (15) Domain Name
        Parameter Request List Item: (33) Static Route
        Parameter Request List Item: (42) Network Time Protocol Servers
        Parameter Request List Item: (120) SIP Servers
        Parameter Request List Item: (121) Classless Static Route
    Option: (57) Maximum DHCP Message Size
        Length: 2
        Maximum DHCP Message Size: 576
    Option: (50) Requested IP Address (192.168.1.21)
        Length: 4
        Requested IP Address: 192.168.1.21
    Option: (12) Host Name
        Length: 9
        Host Name: rain36bmc
    Option: (255) End
        Option End: 255

**Comment by sunharis** [comment]
> I cannot reproduce the issue with the current HEAD.
> 
> Is it possible to get the domain search list from the server with another DHCP client, e.g. dnsmasq?

I am using `isc-dhcpd-4.3.6` . I dont have the dnsmasq setup at my lab. I will try using this and update here

**Comment by yuwata** [comment]
ISC dhcp-client is also OK. I mean, please check that the server is working as expected.

**Comment by yuwata** [comment]
Hmm???
```
Parameter Request List Item: (120) SIP Servers
```

**Comment by sunharis** [comment]
> /etc/systemd/system/systemd-networkd.service.d

I dont have this path at my system. It has phosphor-networkd over the systemd-networkd.

**Comment by yuwata** [comment]
You can create the drop-in config by using `sudo systemctl edit systemd-networkd.service`, then the corresponding directory and file are automatically created as expected.

**Comment by sunharis** [comment]
I was able to figure-out the bug at my system with the help of debug enabled investigation. A change was needed at the networkd wrapper, and after making that, the systemd functionality to get the DOMAIN_SEARCH_LIST is exposed. Now things are working fine. 

Thank you so much for the support @yuwata
