### ISSUE TITLE
RFE: provide a helper for opening `/dev/XYZ` in a race-free way

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#22906]
**Is your feature request related to a problem? Please describe.**
Currently, opening almost any file under `/dev` is racy against device hotplug: the kernel uses major and minor numbers to identify the device, but those are subject to reuse.  I would like to be able to open such a device without a risk of reuse.

**Describe the solution you'd like**
I suggest using a layer of indirection: create a `/dev/disk/by-diskseq` directory, and have every block-device symlink point to one 

**Describe alternatives you've considered**
None

**The systemd version you checked that didn't have the feature you are asking for**
git HEAD

**Comment by poettering** [comment]
well, but how would that work? from userspace we cannot atomically have the device node removed whenver a major/minor is gone. I mean, the device nodes are on the lower level *always* about major/minor ids, no diskseqs, and we can't fake that...

So, if you find a device in the udev db, and you see major/minor + diskseq in the db entry, then the only fully safe way to open the device would be to open() the device node with O_PATH, pinning the device node inode, verify major/minor are right, then open the node via `/proc/self/fd/<fd>` properly (i.e. without O_PATH, so that we get the backing device), and then issue the diskseq ioctl, and compare it with the diskseq if the db entry. Only if everything matches we the fd refers to the device the udev db entry was about.

This is admittedly quite complex, but i don#t see how we could make this work otherwise.

We could add an sd-device API for that maybe, i.e.


```c
int sd_device_open(sd_device *d, int mode);
```

Which would return you an fd to the block device node you could then use.

I kinda like this idea.

@yuwata what do you say?

**Comment by poettering** [comment]
I guess, for starters, the various udev components that actually open devices for probing info should start using such a new api...

**Comment by DemiMarie** [comment]
> well, but how would that work? from userspace we cannot atomically have the device node removed whenver a major/minor is gone. I mean, the device nodes are on the lower level _always_ about major/minor ids, no diskseqs, and we can't fake that...

The advantage of the indirection layer is that it makes such helpers much, _much_ easier to implement.  All I need to do is open() the device node (to pin the inode), then issue an ioctl, and finally check that readlink() on the path I just opened returns what I expect based on the diskseq.  If it does, then I know that the symlink I opened was intended to point that to the device it does.  This has two huge advantages: it allows an API that takes a path as input, and it can be implemented in third-party code that might not want to link to libsystemd.  This makes it a much better fit for third-party tools, which almost always only have a string to work with.  The O_PATH dance is necessary if I need to worry about opening the device having side effects, which I often do not.

**Comment by yuwata** [comment]
> We could add an sd-device API for that

Done. Waiting in #22872.

**Comment by poettering** [comment]
> The advantage of the indirection layer is that it makes such helpers much, _much_ easier to implement. All I need to do is open() the device node (to pin the inode), then issue an ioctl, and finally check that readlink() on the path I just opened returns what I expect based on the diskseq. If it does, then I know that the symlink I opened was intended to point that to the device it does. This has two huge advantages: it allows an API that takes a path as input, and it can be implemented in third-party code that might not want to link to libsystemd. This makes it a much better fit for third-party tools, which almost always only have a string to work with. The O_PATH dance is necessary if I need to worry about opening the device having side effects, which I often do not.

Well, but how many projects who are willing to do the readlink()/ioctl() dance (which is not precisely trivial to implement I'd argue) but aren't also fine with just using sd_device for it? I mean, if you are fine with accepting udev for the naming regime, then you probably are also fine with just linking to our library?

But dunno. It's easy to add, so maybe OK. It would not hurt. It's a one-liner addition to 60-persistent-storage.rules I guess.

i.e. something like:

```
ENV{DISKSEQ}=="?*",SYMLINK+="disk/by-diskseq/$env{DISKSEQ}"
```

@yuwata what do you say? I think that would be OK to add?

**Comment by poettering** [comment]
→ #22916

**Comment by DemiMarie** [comment]
> > The advantage of the indirection layer is that it makes such helpers much, _much_ easier to implement. All I need to do is open() the device node (to pin the inode), then issue an ioctl, and finally check that readlink() on the path I just opened returns what I expect based on the diskseq. If it does, then I know that the symlink I opened was intended to point that to the device it does. This has two huge advantages: it allows an API that takes a path as input, and it can be implemented in third-party code that might not want to link to libsystemd. This makes it a much better fit for third-party tools, which almost always only have a string to work with. The O_PATH dance is necessary if I need to worry about opening the device having side effects, which I often do not.
> 
> Well, but how many projects who are willing to do the readlink()/ioctl() dance (which is not precisely trivial to implement I'd argue) but aren't also fine with just using sd_device for it? I mean, if you are fine with accepting udev for the naming regime, then you probably are also fine with just linking to our library?

I didn’t see an API for getting an `sd_device *` from a path under `/dev`, such as `/dev/mapper/`.  That’s usually what a command-line tool has to work with.  One can call `fstat()` on the FD, call `sd_device_new_from_stat_rdev()` to get an `sd_device *`, and then check the diskseq against `sd_device_get_seqnum()`, but that is neither simple nor obvious.

**Comment by poettering** [comment]
sd_device_new_from_devname() is added in #22872 actually.

**Comment by DemiMarie** [comment]
> sd_device_new_from_devname() is added in #22872 actually.

Would it be possible to have an API that opened the device, called `sd_device_new_from_devname()` or `sd_device_new_from_stat_rdev()`, checked the diskseq, and then returned the FD?

**Comment by poettering** [comment]
> Would it be possible to have an API that opened the device, called `sd_device_new_from_devname()` or `sd_device_new_from_stat_rdev()`, checked the diskseq, and then returned the FD?

Hmm? What would thta API take as input?

**Comment by DemiMarie** [comment]
> > Would it be possible to have an API that opened the device, called `sd_device_new_from_devname()` or `sd_device_new_from_stat_rdev()`, checked the diskseq, and then returned the FD?
> 
> Hmm? What would thta API take as input?

Something like `int sd_device_open_easy(const char *path, int flags);`.

**Comment by poettering** [comment]
yeah, but what would `path` precisely be?

**Comment by DemiMarie** [comment]
`/dev/mapper/luks-<something>`, for example

**Comment by poettering** [comment]
hmm, not following, for those symlinks what would sd_device_open_easy() precisely do that open() wouldn't?

**Comment by poettering** [comment]
(we should probably adjust all sd_device_new_from_xyz() constructors to validate that the device actually created/loaded matches the data passed in. i.e. if people use sd_device_new_from_devnum() should be verified to actually verify to a device by that major/minor, and sd_device_new_form_devname() should verify that the loaded device actually lists the specified path as devlink or devname...)

**Comment by DemiMarie** [comment]
> hmm, not following, for those symlinks what would sd_device_open_easy() precisely do that open() wouldn't?

Check (after `open()`) that the symlink really did point to what it was supposed to, and not to a new device with that `dev_t` that appeared before udev got to remove the stale symlink.
