### ISSUE TITLE
journalctl generates unwanted escape codes in output

### ISSUE THREAD

**Issue by sgleissner** [systemd/systemd#2291]
I want to filter a systemd journal and post-process the output in sed. Obviously the generated output by journalctl always contains escape codes for message highlighting, even if it is run in a batch file and not on an interactive console.

My command looks like this:
journalctl --quiet --no-pager -o short-iso -t cpu_load | reformatWithSedAsCSV

expected behaviour: unpaged output does not contain escape codes OR availability of ASCII-only option switch for journalctl

journalctl --version
systemd 224

**Comment by falconindy** [comment]
Ignoring the multiple problems with your example command, if your goal is to get rid of color codes and other escapes, then just filter it through `tr -cd '[:space:][:print:]'`

Altenatively, use an output format which is intended to be parseable (e.g. one of the json-based outputs).

**Comment by evverx** [comment]
> Obviously the generated output by journalctl always contains escape codes for message highlighting

Hm,
- [journalctl: strip TABs and ANSI color sequences from log messages when displaying them](https://github.com/systemd/systemd/commit/e8bc0ea2b100158bf)
- [`on_tty() * OUTPUT_COLOR`](https://github.com/systemd/systemd/blob/master/src/journal/journalctl.c#L2339)

Try:

```
printf "\x1B[0;1;32mabc\x1B[0m\n" | systemd-cat --priority err --identifier test-highlighting

journalctl --quiet --no-pager -o short-iso -t test-highlighting | hexdump -C
```

Do you see `[0;1;32mabc`?

**Comment by sgleissner** [comment]
Hello falconindy, hello evverx,

thanks for your help, i think i got it, sorry for the trouble. I did something lightly different that i wrote above.

Instead of calling jounalctl directly, i called it via ssh from a remote machine and piped that to my command. This did not bypass the escpape character generation, as jounalctl run directly in ssh without any direct output piping on the remote machine:

```
ssh xx@yy.zz journalctl --quiet --no-pager -o short-iso -t cpu_load | cat -
```

But when i call it i a quotation via ssh, then no escape codes are generated:

```
ssh xx@yy.zz "journalctl --quiet --no-pager -o short-iso -t cpu_load | cat -"
```

Again, thank you!

**Comment by evverx** [comment]
> But when i call it i a quotation via ssh, then no escape codes are generated:
> 
> ```
> ssh xx@yy.zz "journalctl --quiet --no-pager -o short-iso -t cpu_load | cat -"
> ```

I think `ssh -T xx@yy.zz journalctl ...` is better.

See [ssh(1)](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ssh.1):

> -T Disable pseudo-terminal allocation.

**Comment by poettering** [comment]
Yeah, I agree that "ssh -T" is the best option.

That said, I'd be open to adding a new env var SYSTEMD_COLOR= or so, which takes a bool and overrides the automatic color logic. Patch welcome!

**Comment by jsynacek** [comment]
See https://github.com/systemd/systemd/pull/2364.
