### ISSUE TITLE
new feature in mount unit for special mount program or module

### ISSUE THREAD

**Issue by jiamn** [systemd/systemd#22938]
make new feature in mount unit for special mount program or module
How to choice mount program or module with difference condition.
for example: same FS_TYPE like exfat, with three types mount program or module, 
when the drive made by SONY, choice /usr/sbin/mount.exfat, 
by Panasonic or one type: Panasonic XPD1, choice module exfat (by samsung).

----------------  over ---------------------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by poettering** [comment]
not sure I follow, but do note that util-linux' `/bin/mount` command (which systemd calls for .mount units) already calls out to `/bin/mount.<fstype>` for fstypes. So I think what you are asking for already is perfectly doable by some scripting that then executes the right program depending on your conditions.
