### ISSUE TITLE
Read `/etc/cmdline.{d/*,conf}` as well as `/proc/cmdline` especially for `rd.luks`

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [systemd/systemd#22935]
**Is your feature request related to a problem? Please describe.**
Posted here:
https://github.com/dracutdevs/dracut/issues/1754
in short:
My system relies on `rd.luks`. I use dracut which stores the `rd.luks` (given in the `dracut.conf`) in `/etc/cmdline.d/*conf` (of initrd)
`systemd-cryptsetup-generator` is responsible for creating units that in turn ask for decryption passphrase during boot.
But it only relies on `/proc/cmdline` and `/etc/crypttab` hence failing to decrypt a `rd.luks` partition as configured in `dracut.conf`

**Describe the solution you'd like**
Read `/etc/cmdline.{d/*,conf}` as well as `/proc/cmdline`

**Describe alternatives you've considered**
At the moment I have to configure `rd.luks` in the bootloader if I used a BIOS system. On UEFI it is enough to configure it in dracut, since the unified kernel image transports the cmdline args correctly.

**The systemd version you checked that didn't have the feature you are asking for**
```systemctl --version
systemd 250 (250.4-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by TriMoon** [comment]
I personally never heard of `/etc/cmdline.{d/*,conf}` i assume that's specific to `dracut` which i never used either?
Maybe its better to leave the solution for the BIOS bootloader's needs to `dracut` instead of `systemd` :thinking: 

Otherwise people using other utils will start asking for their specific needs also, instead of properly configuring stuff that is used by default...
That's my personal opinion though, the `systemd` devs might think differently...

**Comment by poettering** [comment]
We read /etc/kernel/cmdline, no other file, see kernel-install(8) man page.

We do not read .d/ dropins for it though

**Comment by poettering** [comment]
hhmm, or wait, i misunderstood: you are looking for a way to override/extend /proc/cmdline on read via a file in /etc?

That's pointless as 95% of kernel cmdline options take effect before userspace initializes, hence /etc is available.

So, sorry, but no, we can't do this.
