### ISSUE TITLE
Systemd startup non-deterministic hangs (riscv64)

### ISSUE THREAD

**Issue by troibe** [systemd/systemd#22947]
**systemd version the issue has been seen with**
`systemd 250.4-1 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)`

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)
`Linux version 5.17.0-246941-g282bd1b00eeb-dirty (martin@martin-ThinkPad-T14-Gen-1) (riscv64-unknown-linux-gnu-gcc (g5964b5cd727) 11.1.0, GNU ld (GNU Binutils) 2.38) #11 SMP Wed Mar 30 02:39:38 CEST 2022`

**CPU architecture issue was seen on**
 > riscv64

**Expected behaviour you didn't see**
 > Only in ~1/5 cases systemd successfully starts in emergency mode.
 > Only in ~1/10 cases systemd successfully starts in regular mode.

**Unexpected behaviour you saw**
 > Systemd hangs at seemingly random stages without producing any further (`systemd.log_level=debug`) output.
 > The kernel always successfully starts and is still running as can be observed in the logs when removing the sdcard from the system.
 > This occurs both during normal boot up and when using `systemd.unit=emergency.target`.
 > I consider the start process as hung up after waiting 10 minutes (usually the emergency boot takes about that long - this a system running at 50Mhz).

**Steps to reproduce the problem**
 > Just usual systemd start (optionally with `systemd.unit=emergency.target`).
 > 

**Additional program output to the terminal or log subsystem illustrating the issue**

Emergency target logs: https://gist.github.com/developandplay/79471ac1b33dd909eea26c6f38155216

**Comment by developandplay** [comment]
What would be the next steps in debugging this issue?
Is there an even finer grained setting than `systemd.log_level=debug` or maybe something similar to using `strace` on systemd?

**Comment by mrc0mmand** [comment]
Maybe adding `systemd.default_standard_output=journal+console` and `debug` (to get kernel debug messages as well) into the mix might reveal a bit more information.

**Comment by mbiebl** [comment]
have you made sure to enable all kernel options as outlined in the README? E.g. I notice
```
Unit type .automount is not supported on this system.
Unit type .automount is not supported on this system.
```

There is also this:
```
(sd-executor) terminated by signal ALRM.
```
Maybe your system is just so slow that the generators are killed by a timeout.
Would be good to have timestamps in the logs.

**Comment by mbiebl** [comment]
Afaics, execute_directories uses `DEFAULT_TIMEOUT_USEC` which is 90s by default.
Maybe that is too short for your system.

**Comment by mbiebl** [comment]
Might be a random pool issue.
I vaguely remember https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823337

**Comment by poettering** [comment]
this is not actionable without debug logs. 

what makes you think systemd hangs and not the kernel as a whole?

**Comment by developandplay** [comment]
Sorry for not following up yet. I didn't have the time to investigate the provided suggestions yet.
I will add the logs with `systemd.default_standard_output=journal+console` and `debug`.

@poettering I think the Kernel is still running as it still produces output when I remove the SD-card.
It is cut off in the logs with `systemd.log_level=debug` that I posted.

```
[  392.818982] mmc0: card 0001 removed
[  393.673240] mmc0: new SDHC card at address 0001
[  393.698366] mmcblk0: mmc0:0001 EB1QT 29.8 GiB 
[  393.732654]  mmcblk0: p1 p2
```

**Comment by poettering** [comment]
Let's close this, since the logs were never provided.
