### ISSUE TITLE
TEST-64-UDEV-STORAGE is not run (on Ubuntu CI)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#22949]
I notice that Ubuntu CI skips TEST-64-UDEV-STORAGE:

```
[18:34:19] --x-- Running TEST-64-UDEV-STORAGE --x--
+ make -C TEST-64-UDEV-STORAGE setup run
make: Entering directory '/tmp/autopkgtest.P371bQ/build.oFv/systemd/test/TEST-64-UDEV-STORAGE'
This test requires KVM, skipping...
This test requires KVM, skipping...
make: Leaving directory '/tmp/autopkgtest.P371bQ/build.oFv/systemd/test/TEST-64-UDEV-STORAGE'
[18:34:20] --x-- Result of TEST-64-UDEV-STORAGE: 0 --x--
```
Is that deliberate?

**Comment by mbiebl** [comment]
or put differently: should we set `TEST_NESTED_KVM=1` for ubuntu-ci?

**Comment by DaanDeMeyer** [comment]
I don't think this is something to track upstream, if the underlying hardware isn't sufficient to run an integration test fast enough that's something to track downstream in ubuntu. Let me know if you disagree and we should reopen
