### ISSUE TITLE
Since v250 systemd-networkd aborts if it don't have permissions to read one of the .network conf files

### ISSUE THREAD

**Issue by fmore-xyz** [systemd/systemd#22954]
More accurately this behavior change was introduced by 9202b567bcdd0c1f6a1fc2a5f36602e619960813.

@yuwata can you please tell if this is intended ?

I'm not sure whether networkd should fail when such condition happen, at least this wasn't the case before.

Thanks.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #22956.
