### ISSUE TITLE
'systemctl show --property' needs verification of property requested and return correct exit code

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#2295]
Description of problem:

systemctl --property doesn't validate if a requested property is valid or not, and always returns with an exit code of 0, regardless of whether the requested property exists or not.

How reproducible:

This works fine:

```
# systemctl show --property Id default.target
Id=multi-user.target
```

But put in a non-existing property:

```
# systemctl show --property Id default.targets
Id=default.targets.service
# systemctl show --property Id default.targets; echo $?
Id=default.targets.service
0
#
[root@shou18lkvm8 ~]# systemctl show --property Id this.is.rubbish; echo $?
Id=this.is.rubbish.service
0
```

**Comment by poettering** [comment]
--property= is implemented as client-side filtering. We could of course return an error if we don't find a single prop that matches the specified strings. Happy to take a patch for that!
