### ISSUE TITLE
homectl: --luks-volume-key-size interpreted in bytes

### ISSUE THREAD

**Issue by Nemris** [systemd/systemd#22966]
**systemd version the issue has been seen with**
 > systemd 250 (250.4.2-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux master 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The `--luks-volume-key-size` should take an argument in bits, as per the man page.

**Unexpected behaviour you saw**
 > The `--luks-volume-key-size` takes an argument in bytes.

**Steps to reproduce the problem**
 > Attempt to create a new user and pass e.g. `--luks-volume-key-size=512`, then observe the failure.
>
> Then, attempt to create a new user and pass e.g. `--luks-volume-key-size=64` (as in 512/8), then observe the success and confirm that `homectl inspect` reports `Volume Key: 512bit`.

**Comment by poettering** [comment]
so we typically try to stick to bytes as units for everything, i.e. we avoid bits, sectors, pages, and whatnot, and just want to use bytes.

**Comment by poettering** [comment]
or in other words, we should probably fix the man page here

**Comment by Nemris** [comment]
Makes sense that you would - although I'd probably suggest that, for consistency with how `cryptsetup` does things, using bits here might be justifiable.
