### ISSUE TITLE
systemd-repart ignores lexical order of repart.d files

### ISSUE THREAD

**Issue by cmhe** [systemd/systemd#22974]
**systemd version the issue has been seen with**

```
systemd 250 (250.4-1-gc3aead5+)
+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS +OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid
```

**Used distribution**
OpenEmbedded

**Linux kernel version used** (`uname -a`)
```
Linux sb 5.15.32-stable-standard #1 SMP Mon Mar 28 07:58:46 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**CPU architecture issue was seen on**
ARM64

**Expected behaviour you didn't see**
systemd-reparted creates partition ordered after the lexical order of the partition definition files in `/etc/repart.d/*.conf`

**Unexpected behaviour you saw**
systemd-reparted does not order the partitions in the lexical order.

**Steps to reproduce the problem**

1. Create partition layout:
```
# fdisk -l /dev/mmcblk1
Disk /dev/mmcblk1: 29.72 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 40724AE6-8CAB-4171-A25A-1B861004E803

Device         Start      End  Sectors Size Type
/dev/mmcblk1p1 24576 14750937 14726362   7G Linux root (ARM-64)
```

2. Define repart.d configuration files;
```
root@sb:/etc/repart.d# ls /etc/repart.d/
50-root-a.conf  55-root-b.conf  80-data.conf
root@sb# cat /etc/repart.d/50-root-a.conf 
[Partition]
Type=root
SizeMinBytes=8G
SizeMaxBytes=8G
root@sb# cat /etc/repart.d/55-root-b.conf 
[Partition]
Type=root
SizeMinBytes=8G
SizeMaxBytes=8G
root@sb:/etc/repart.d# cat /etc/repart.d/80-data.conf   
[Partition]
Type=linux-generic
Label=data
Format=ext4
FactoryReset=on
```

3. Call systemd-repart:
```
root@sb:~# systemd-repart --dry-run=yes
TYPE          LABEL      UUID                                 FILE           NODE                  SIZE       PADDING
root-arm64    root-a     6a056987-8c5a-4ed6-82f1-ee668273f7f1 50-root-a.conf /dev/mmcblk1p1 7.0G → 8.0G 22.6G → 13.7G
root-arm64    root-arm64 26054b5f-3417-490a-b67b-170449a36fd5 55-root-b.conf /dev/mmcblk1p3      → 8.0G          → 0B
linux-generic data       a3ddbb7f-4cda-4e74-916e-67cead5f52af 80-data.conf   /dev/mmcblk1p2     → 11.9M          → 0B
                                                                                              Σ = 16.0G     Σ = 13.7G

 ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░
 ├─ 80-data.conf                                                                     │                               
 │                                                                                   └─ 55-root-b.conf               
 └─ 50-root-a.conf                                                                                                   

Refusing to repartition, please re-run with --dry-run=no.
```

I expected that the second `root-arm64` partition is created as `/dev/mmcblk1p2` and the `linux-generic` `data` partition is created as `/dev/mmcblkp3`.

**Comment by cmhe** [comment]
I investigated this a bit more, and found that systemd-repart tries to put the data partition before the existing `Linux root` partition. I could fix this in my case by adding a `SizeMinBytes=50M` property in the `80-data.conf` file.

However when reading the `systemd-repart` manpage, I still get the impressions that the `data` partition should have been assigned the 3rd entry in the GPT partition table:

```
           [...] Similar, existing partitions that
           are determined to grow are grown. New partitions are always appended to the end of the
           existing partition table, taking the first partition table slot whose index is greater than
           the indexes of all existing partitions. Partition table slots are never reordered and thus
           partition numbers are ensured to remain stable. Note that this allocation happens in RAM
           only, the partition table on disk is not updated yet.
```

In this case, where only one rootfs partition exists, and both data and rootfs need to be created `data` would be the second partition and the second rootfs the third parition. However if the `80-data.conf` file was missing and was added later via an update, etc. Then the second rootfs would have been created beforehand and would be assigned the second partition and the `data` partition would be created afterwards and assigned the third partition.

This would be an inconsistency: The resulting partition table assignment would be different wherever `80-data.conf` was there initially or added later via an update.

**Comment by poettering** [comment]
> [...] Similar, existing partitions that
>            are determined to grow are grown. New partitions are always appended to the end of the
>            existing partition table, taking the first partition table slot whose index is greater than
>            the indexes of all existing partitions. Partition table slots are never reordered and thus
>            partition numbers are ensured to remain stable. Note that this allocation happens in RAM
>            only, the partition table on disk is not updated yet.

So, end of partition table doesn't mean end of disk. i.e. partitions can appear in any order in the partition table, the place on disk can be ordered differently.

so repart will place the partition at the end of the table (so that it has the newest highest index), but it will place it in the smallest area of free space it can find that it fits in. Thus, if you have some free space somewhere in the front, and the partition fits in there, it's going to be placed there, if the free space at the end of the disk is larger...

It's intended to optimize allocation, i.e. consume the small holes if we can, leave the long free areas free for later.

So I guess we should make this clearer in teh documentation, but I still think this is actually a good approach.

That said, we could maybe add a knob or so, that enforces strict ordering, i.e. that partition offsets and partition indexes both grow strictly monotonically in the table.
