### ISSUE TITLE
systemd- hwdb unexpected abort

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#22976]
Version: 250.4

Originally filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008989
by Эрик Шахов <jeshahov@astralinux.ru>

The following is a verbatim copy:

Hi. 

Error message: Code should not be reached 'Unknown option' at src/hwdb/hwdb.c:102, function parse_argv(). Aborting. Aborted 

To reproduce this bug we just need to run command `systemd-hwdb -ust` or `systemd-hwdb -u`. In normal way it must finish with "invalid option" error. 
Technical description: Program systemd-hwdb call function parse_argv(file hwdb.c:57). In « while ((c = getopt_long (argc, argv, " ust:r:h " , options, NULL )) >= 0 ) » (file hwdb.c:77) when we send "-u" or anything starting at "-u" the program will received Aborting 
```
System information: Linux debian 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07 ) x86_64 GNU/Linux 
libc-2.31.so 
```
CWE identifier for this bug: CWE- 617 : Reachable Assertion 

Way to fix this bug: Delete "ust" from « while ((c = getopt_long (argc, argv, " ust:r:h " , options, NULL )) >= 0 )» (file hwdb.c:77) 

Regards, 

Shahov Erik

**Comment by yuwata** [comment]
Fix is waiting in #22978.
