### ISSUE TITLE
`show-environment` seems to incorrectly double-quote some environment values

### ISSUE THREAD

**Issue by akdor1154** [systemd/systemd#22986]
**systemd version the issue has been seen with**
 > systemd 248 (248.3-1ubuntu8.2pop0\~1647542931\~21.10\~ab7b8e3)

**Used distribution**
 > Pop OS 21.10

**Linux kernel version used** 
 > `Linux herbie.lan 5.16.15-76051615-generic #202203161444~1647964027~21.10~e706226 SMP PREEMPT Tue Mar 22 17 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Set up**
Create a file in ~/.config/environment.d/test.conf, with
```ini
NIX_PROFILES=/nix/var/nix/profiles/default $HOME/.nix-profile
```
, and reboot.

After logging in, run:
```sh
systemctl --user show-environment | grep NIX_PROFILES
```

**Expected behaviour you didn't see**

I would expect the output of this to be:
```
NIX_PROFILES=$'/nix/var/nix/profiles/default /home/jarrad/.nix-profile'
```

**Unexpected behaviour you saw**

However, the output of this is actually:
```
NIX_PROFILES=$'$\'/nix/var/nix/profiles/default /home/jarrad/.nix-profile\''
```

Guessing something to do with the space+$HOME in the same entry.

**Comment by mrc0mmand** [comment]
This seems to work as expected with the latest main (v255-rc4 ATTOW):
```
$ cat ~/.config/environment.d/test.conf 
NIX_PROFILES=/nix/var/nix/profiles/default $HOME/.nix-profile
FOO1=hello world
FOO2=hello$HOME
FOO2=hello $HOME
ALSO_NIX_PROFILES=/nix/var/nix/profiles/default $HOME/.nix-profile
$ systemctl --user show-environment
HOME=/home/testuser
LANG=en_US.UTF-8
LOGNAME=testuser
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
SHELL=/bin/bash
USER=testuser
XDG_RUNTIME_DIR=/run/user/1001
NIX_PROFILES=$'/nix/var/nix/profiles/default /home/testuser/.nix-profile'
FOO1=$'hello world'
FOO2=$'hello /home/testuser'
ALSO_NIX_PROFILES=$'/nix/var/nix/profiles/default /home/testuser/.nix-profile'
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
```
