### ISSUE TITLE
Wrong F2FS mounting

### ISSUE THREAD

**Issue by MiloLug** [systemd/systemd#22982]
**systemd version the issue has been seen with**
 > 250.4-2

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.17.1-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > filesystem should've mounted without issues

**Unexpected behaviour you saw**
 > systemd-gpt-auto-generator fails to create mount services for F2FS filesystem when in /etc/fstab option atgc is specified and mounts it r/o instead

**Steps to reproduce the problem**
 > add atgc to /etc/fstab mount otptions of an f2fs partition

**Comment by keszybz** [comment]
Please attach dmesg output.

This some like the issue is in some other place. Systemd doesn't know anything about "atgc" so it would just pass the parameter through to the mount command.

**Comment by MiloLug** [comment]
Dmesg:
![image](https://user-images.githubusercontent.com/33329419/162053847-05358090-feff-4ca7-9502-43f21a23415c.png)

**Comment by MiloLug** [comment]
Also, it works correctly if `systemd.gpt_auto=no` and `fstab=no` is passed to kernel cmdline, but otherwise fails to create mount

**Comment by medhefgo** [comment]
Log at the logs, it says "switch atgc option is not allowed", so the remount to rw is refused by the kernel (I even looked at the kernel code).

> Also, it works correctly if `systemd.gpt_auto=no` and `fstab=no` is passed to kernel cmdline, but otherwise fails to create mount

Of course it works with those options because it doesn't look at options provided by fstab then.
