### ISSUE TITLE
message of systemctl enable seems not right.

### ISSUE THREAD

**Issue by byujiang** [systemd/systemd#2299]
when you enable a service, it says

```
Created symlink from /etc/systemd/system/*.service to /usr/lib/systemd/system/*.service.
```

Shouldn't  it be

```
Created symlink from /usr/lib/systemd/system/*.service to /etc/systemd/system/*.service
```

?

**Comment by lnykryn** [comment]
No, the message is correct, you have a symlink in /etc and the target is in /usr.

**Comment by byujiang** [comment]
Just weird and confusing...

**Comment by lnykryn** [comment]
Maybe we should reduce the information in that message again and print just. Enabling service *service in *target, or Created an alias *service of *service.

**Comment by poettering** [comment]
i figure the english language isn't that clear here. We could probably make this clearer by replacing "to" by "pointing to". I think in that case it would be clear which one is the symlink, and which one the symlink's target. Will prep a patch

**Comment by byujiang** [comment]
@poettering That sounds good.
