### ISSUE TITLE
Improve hotkey support for HP Victus 16

### ISSUE THREAD

**Issue by Jojonintendo** [systemd/systemd#23006]
**systemd version the issue has been seen with**
 > 250.4-2

**Used distribution**
 > Arch up to date as of 07/04/22.

**Linux kernel version used** (`uname -a`)
 > `Linux Victus 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Pressing the "Calculator" hotkey opens the calculator more than once.

**Unexpected behaviour you saw**
 > Pressing the "Calculator" hotkey only works once, exactly as described [in this other issue](https://github.com/pelrun/hp-omen-linux-module/issues/9#issuecomment-936474113). A reboot makes it available again, but only once.

**Steps to reproduce the problem**
 > Press the "Calculator" hotkey once, and notice it is no longer detected by the system (xev doesn't see it anymore) until a reboot.

**Additional program output to the terminal or log subsystem illustrating the issue**

>I've tried adding the below lines to /etc/udev/hwdb.d/70-keyboard.whdb, but this seems to be too model-specific and doesn't fix it for me:

>`# HP Omen 15`
>`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHP:pnOMENLaptop15*:pvr*`
>` KEYBOARD_KEY_a1=!calc`

>This is the exact same as can be seen on the linked issue, except for a different variant of laptop. The fix seems to be in the pipeline for the Omen model, but it doesn't work on the Victus variant.
I'd be glad to provide any additional information if necessary. Thanks for your time.

**Comment by frost-nzcr4** [comment]
Previous _systemd 249 (249.11-0ubuntu3.1)_ affected too. After that error the Omen key ◆ didn't fire any event either.
