### ISSUE TITLE
can RuntimeDirectoryInodesMax=400k is correctly parsed

### ISSUE THREAD

**Issue by JetXujing** [systemd/systemd#23017]
**systemd version the issue has been seen with**
 > systemd main branch

in [src/login/logind-gperf.gperf](https://github.com/systemd/systemd/blob/a520bb665417af7aa98dcb983f3583659bbab807/src/login/logind-gperf.gperf) 
`Login.RuntimeDirectoryInodesMax,    config_parse_uint64,                0, offsetof(Manager, runtime_dir_inodes)`
use config_parse_uint64 to parse argv, can RuntimeDirectoryInodesMax=400k is correctly parsed.

**Comment by poettering** [comment]
hmm, so i take it you are saying the man page of logind.conf doesn't matche code, as K, M, G, … suffixes are not actually understood.

I think we should fix the man page here though, as we generally only support K/M/G suffixes for byte values, and this one is not.

**Comment by JetXujing** [comment]
yes，I‘m saying the man page of logind.conf doesn't matche code

**Comment by JetXujing** [comment]
In addition，`#RuntimeDirectoryInodesMax=400k ` in a42a93830fcc also need to be modified.
