### ISSUE TITLE
`journalctl --user` should not issue hint about system messages

### ISSUE THREAD

**Issue by ukleinek** [systemd/systemd#23018]
On systemd 250.4-1 on Debian testing/unstable running 5.16.0-5-amd64 I see:
```
uwe@taurus:~$ journalctl --user --since 1s\ ago
Hint: You are currently not seeing messages from the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- No entries --
```
Given that I specified `--user` and so expect not see system messages anyhow, I wonder if the Hint should be suppressed in this case.

Not sure I missed something so I didn't try yet to come up with a patch.

**Comment by bluca** [comment]
Looks like a regression, on 247:

```
$ journalctl --user | head -n1
-- Journal begins at Thu 2022-03-10 18:04:17 GMT, ends at Fri 2022-04-08 11:36:37 BST. --
$ journalctl | head -n1
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Journal begins at Thu 2022-03-10 18:04:17 GMT, ends at Fri 2022-04-08 11:37:23 BST. --
$ journalctl --version
systemd 247 (247.3-7)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by bluca** [comment]
Mmh I actually don't see the warning on latest main either - can you try to build the journalctl from the latest main branch? No need to install or anything, you can just run it in place with `./build/journalctl --user` or such

**Comment by ukleinek** [comment]
Hm, I cannot reproduce this with 254.3-1 from Debian. And even if I compile 253.4 from source the problem doesn't occur. From my side this can be closed, I won't investigate this further. Thanks!
