### ISSUE TITLE
Systemd-journald should be able to log to a remote syslog server

### ISSUE THREAD

**Issue by ckuethe** [systemd/systemd#23013]
**Is your feature request related to a problem? Please describe.**
Systemd-journald should be able to log to a syslog server directly

**Describe the solution you'd like**
`ForwardToSyslog=syslog.example.com` - resolve the hostname, and transport via classic udp/514
`ForwardToSyslog=tcp:logger.example.com:5140` - resolve the hostname, but use tcp and a nonstandard port
`ForwardToSyslog=192.0.0.17` - or just use an IP

**Describe alternatives you've considered**
rsyslogd, other syslog implementations

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by KloudJack** [comment]
Seems like a duplicate of #7170

**Comment by poettering** [comment]
True.

**Comment by poettering** [comment]
Duplicate of #7170
