### ISSUE TITLE
systemd-networkd v251-rc1 requires CONFIG_NET_SCHED

### ISSUE THREAD

**Issue by tambry** [systemd/systemd#23014]
**systemd version the issue has been seen with**
[v251-rc1](https://github.com/systemd/systemd/releases/tag/v251-rc1)

**Used distribution**
Debian Unstable

**Linux kernel version used** (`uname -a`)
`Linux d11.cleveronmobility.dev 4.14.275-rt132 #4 SMP PREEMPT RT Fri Apr 8 08:24:12 EEST 2022 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
ARMv8.2-A (NVIDIA Carmel)

**Expected behaviour you didn't see**
systemd-networkd starting

**Unexpected behaviour you saw**
systemd-networkd fails to start with:
```
root@d11:~# /usr/lib/systemd/systemd-networkd
lo: Link UP
lo: Gained carrier
Could not enumerate QDisc: Operation not supported
```

**Steps to reproduce the problem**
1. Compile a kernel without `CONFIG_NET_SCHED`
2. `/usr/lib/systemd/systemd-networkd` will fail to start

**Additional information**
The issue seems to have been introduced in 828a81a93783248be15683c9639b85098f331328 due to the use of `RTM_GETQDISC`. If this is considered working-as-intended it would be nice to have this requirement bump mentioned in the changelog.

I encountered this issue on a fairly customized embedded-like system, which uses a fairly minimal kernel with all features not used disabled.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #23015.
