### ISSUE TITLE
Parametrise timezone link instead of hard-coding it to /etc/localtime

### ISSUE THREAD

**Issue by jdallaglio** [systemd/systemd#23023]
In systemd code decision has been made to hard-code /etc/localtime in different positions in a number of files:
- src/basic/time-util.c
- src/nspawn/nspawn.c
- src/timedate/timedated.c
- src/firstboot/firstboot.c
- src/core/manager.c

It may be desirable in some use cases to have the localtime link in a different location, a possible reason for that is persisting the timezone setting between system updates, or having a read-only /etc (I'm aware that overlays can be a solution here, but my experience is that they sometimes create mount order issues if not correctly handled).

Since it has been pointed out several times that following links when parsing /etc/localtime is not and will not be supported, which is fine to me, it would be nice to at least have the /etc/localtime location parametrised somewhere, e.g. in a define in some include.

It would also be super convenient to have a build-time option to set that define, so we don't have to patch the code to implement this feature.

If that is of any interest I can submit the patch I normally use to parametrise /etc/localime for reviewing.

**Comment by poettering** [comment]
Sorry, but /etc/localtime is a path defined by glibc, not us. We cannot move it.

And even if glibc would be willing to move it, there are a myriad of programs that expect the file under this path.

Sorry, but this cannot work.

**Comment by russdill** [comment]
glibc does support relocating this file:

https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

> The third format looks like this:
>
> :characters
>
> Each operating system interprets this format differently; in the GNU C Library, characters is the name of a file which describes the time zone.
>
> If the TZ environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘TZ=:/etc/localtime’ (or ‘TZ=:/usr/local/etc/localtime’, depending on how the GNU C Library was configured; see [Installing the GNU C Library](https://www.gnu.org/software/libc/manual/html_node/Installation.html)). Other C libraries use their own rule for choosing the default time zone, so there is little we can say about them.

It would be really useful to re-open this and have systemd respect the TZ variable.
