### ISSUE TITLE
Execute service for newly created users 

### ISSUE THREAD

**Issue by anaisbetts** [systemd/systemd#23039]
**Is your feature request related to a problem? Please describe.**

I'm writing software for a new [Linux-related project](https://docs.arquivolta.dev) and I'm trying to use systemd as much as possible. I'd like to create systemd services that run _in the context of any human user_ - a bit like `/etc/profile.d`. If the admin creates a new user after-the-fact, I want that user to also have this service run on their next login, in the context of That User

**Describe the solution you'd like**
I'm not sure what exactly the systemd Zen way to do this!

**Describe alternatives you've considered**

I can just use profile.d but it Feels Bad because I'm not trying to add something to a user's shell profile, I'm trying to run a oneshot command on user login

**The systemd version you checked that didn't have the feature you are asking for**
250.4

**Comment by bluca** [comment]
Have you looked at user units?

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#User%20Unit%20Search%20Path

**Comment by anaisbetts** [comment]
@bluca I feel like you're trying to just tell me about `systemctl --user` but that doesn't solve this bit:

> If the admin creates a new user after-the-fact, I want that user to also have this service run on their next login, in the context of That User

**Comment by bluca** [comment]
Yes, that's what user services do - they are installed under `/usr/lib/systemd/user/` and, when enabled, are run when a user logs in and a user session is started
