### ISSUE TITLE
options from .link file not applied

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#23036]
**systemd version the issue has been seen with**

249.7

**Used distribution**

PLD Linux

**Linux kernel version used** (`uname -a`)

5.15.24-6

**CPU architecture issue was seen on**

x86-64

**Expected behaviour you didn't see**

VLAN having an alias and altname.

**Unexpected behaviour you saw**

None of the above is set.

**Steps to reproduce the problem**

cluster-vlan.netdev
```
[NetDev]
Name=v8
Kind=vlan

[VLAN]
Id=8
```

cluster-dev.link
```
[Match]
Type=vlan
OriginalName=v8

[Link]
Alias=test2
AlternativeName=test
```

**Additional program output to the terminal or log subsystem illustrating the issue**

`udevadm -d test-builtin net_setup_link /sys/class/net/v8`
```
SELinux enabled state cached to: disabled
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          249
file size:        11124444 bytes
header size             80 bytes
strings            2374668 bytes
nodes              8749696 bytes
Load module index
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Loaded timestamp for '/etc/systemd/network'.
Parsed configuration file /etc/systemd/network/cluster-dev.link
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /etc/systemd/network/98-cluster-dev2.link
Created link configuration context.
ID_NET_DRIVER=802.1Q VLAN Support
v8: Device has name_assign_type=3
v8: Config file /etc/systemd/network/98-cluster-dev2.link is applied
v8: Failed to get ACTION= property: No such file or directory
v8: Could not apply link configuration, ignoring: No such file or directory
ID_NET_LINK_FILE=/etc/systemd/network/98-cluster-dev2.link
Unload module index
Unloaded link configuration context.
```

**Comment by yuwata** [comment]
Please try to use a number-prefixed filename. Otherwise, as you can see in the result of udevadm, 98-cluster-dev2.link will be assigned to the interface.

**Comment by g0tar** [comment]
98-cluster-dev2.link was already a copy of the cluster-dev.link (it took me a while to number-prefix this, it's not documented behaviour).

**Comment by g0tar** [comment]
I see a few problems here.

1. cryptic debug - this seems important, but doesn't go to journal, so maybe it's not?

```
v8: Failed to get ACTION= property: No such file or directory
v8: Could not apply link configuration, ignoring: No such file or directory
```

2. it tries to read drop-ins from /etc/systemd/network/97-cluster-dev2.link.d (97* is just another copy of the link file, still trying to figure this out) - if so, why doesn't it handle multiple matching files directly?

3. matching by `Path=[ID_PATH glob]` - no such property in `udevadm info /sys/class/net/eth3`

4. 95-eth1.link
```
[Match]
#Path=pci-0000:00:1c.5-*
OriginalName=eth1

[Link]
Name=internet0
```

`networkctl reload`
`udevadm trigger -c add /sys/class/net/eth1`
`systemctl restart systemd-networkd`
```
eth1: Failed to get ACTION= property: No such file or directory                                                                                                            
eth1: Could not apply link configuration, ignoring: No such file or directory                                                                                              
ID_NET_LINK_FILE=/etc/systemd/network/95-eth1.link                                                                                                                         
[...]

$ ip a
4: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 3c:ec:ef:e9:74:e1 brd ff:ff:ff:ff:ff:ff
```

5. `networkctl`
```
[...]
 14 v8              vlan     degraded    configured
```

Why is it degraded? My cluster-ip.network:

```
[Match]
Type=vlan
Name=v8

[Address]
Address=172.16.80.1/24
Scope=link
DuplicateAddressDetection=none

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no
ConfigureWithoutCarrier=yes
KeepConfiguration=static
```

Is this related to 482efedc08?

Actually this is only one problem - the entire thing doesn't work as expected... Either something is seriously broken or something else quietly interferes. I'm not even sure how much tickets this should be reported in...

**Comment by g0tar** [comment]
Please remove the "needs-reported-feedback" tag unless you need more data.

**Comment by yuwata** [comment]
@g0tar Sorry for late response.

> I see a few problems here.
> 
>     1. cryptic debug - this seems important, but doesn't go to journal, so maybe it's not?
> 
> 
> ```
> v8: Failed to get ACTION= property: No such file or directory
> v8: Could not apply link configuration, ignoring: No such file or directory
> ```

I guess this is from `udevadm test-builtin`, right? This is already fixed by 7ce05a8d6631b2e99fb101bd639838c5ce8f60a7 (v250).
The error messages come from udevadm, hence not logged to journal.

>     2. it tries to read drop-ins from /etc/systemd/network/97-cluster-dev2.link.d (97* is just another copy of the link file, still trying to figure this out) - if so, why doesn't it handle multiple matching files directly?

Sorry, I cannot follow what you say. Could you show the main config and its drop-ins, and elaborate the issue more?

>     3. matching by `Path=[ID_PATH glob]` - no such property in `udevadm info /sys/class/net/eth3`

Please show the result of `udevadm info`. Note, some devices do not have `ID_PATH` property.

> 
>     4. 95-eth1.link
> 
> 
> ```
> [Match]
> #Path=pci-0000:00:1c.5-*
> OriginalName=eth1
> 
> [Link]
> Name=internet0
> ```
> 
> `networkctl reload` `udevadm trigger -c add /sys/class/net/eth1` `systemctl restart systemd-networkd`

You also need to reload .link files: `udevadm control --reload`.

> 
> ```
> eth1: Failed to get ACTION= property: No such file or directory                                                                                                            
> eth1: Could not apply link configuration, ignoring: No such file or directory                                                                                              
> ID_NET_LINK_FILE=/etc/systemd/network/95-eth1.link                                                                                                                         
> [...]
> ```

As said in the above, the messages should be from `udevadm test-builtin`. Please provide debugging logs of udevd, instead of udevadm:
```
$ sudo udevadm control --log-level=debug # also --reload if necessary.
$ sudo udevadm trigger --action=add /sys/class/net/eth1
$ journalctl -b --no-hostname -u systemd-udevd.service
```

>     5. `networkctl`
> 
> 
> ```
> [...]
>  14 v8              vlan     degraded    configured
> ```
> 
> Why is it degraded? My cluster-ip.network:
> 
> ```
> [Match]
> Type=vlan
> Name=v8
> 
> [Address]
> Address=172.16.80.1/24
> Scope=link
> DuplicateAddressDetection=none
> 
> [Network]
> LinkLocalAddressing=no
> IPv6AcceptRA=no
> ConfigureWithoutCarrier=yes
> KeepConfiguration=static
> ```

There is nothing strange. The scope of the address is 'link'. If an interface has no global address, then the state is in 'degraded'. See networkctl(1).

**Comment by g0tar** [comment]
Ad. 2 - that was a question on the side. I only wonder why there's a rule of processing that "**first** matching file and it's drop-ins win" instead "apply **all** matching files (and all their respective drop-ins)". Once known there's not any issue by itself here (although it means that `99-default.link` doesn't apply for any link already handled, therefore it's rather `99-fallback.link`).

Ad. 3 - can't match by PCI path; in udev rules I match devices with `DEVPATH==...`, but there's no appropriate match in `systemd.link`. Shouldn't `Path=` catch both `ID_PATH` and `DEVPATH`?

```
# udevadm info /sys/class/net/eth3
P: /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth3
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth3
E: INTERFACE=eth3
E: IFINDEX=11
E: SUBSYSTEM=net
E: USEC_INITIALIZED=16563549
E: ID_NET_NAMING_SCHEME=v249
E: ID_NET_NAME_MAC=enx90e2ba16d6f6
E: ID_OUI_FROM_DATABASE=Intel Corporate
E: ID_NET_NAME_PATH=enp4s0f1
E: ID_BUS=pci
E: ID_VENDOR_ID=0x8086
E: ID_MODEL_ID=0x10fb
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=82599ES 10-Gigabit SFI/SFP+ Network Connection (Ethernet Server Adapter X520-2)
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth3
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

Ad. 4 - it turns out being related to masked `80-net_setup_link.rules` (obviously...); and this file is masked by default to keep original interface names (`ethN`) - which were specified per device (not in `networkd` way). The reason of this setup was already solved in #9006, so I just need to adjust to newer approach - just after resolving #3.

Ad. 5 - indeed, thanks.


So eventually the only problem not already resolved (somewhere, somehow) is 3 - matching `NM-device.link` by DEVPATH. What seems to be the issue is whether the ID_PATH is (re)calculated at all. After a fresh reboot:

```
#  udevadm info /sys/class/net/rename6
P: /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/rename6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/rename6
E: INTERFACE=rename6
E: IFINDEX=6
E: SUBSYSTEM=net
E: ID_RENAMING=1
```

Note:
a) interface renamed,
b) no ID_PATH.

After a minute and a half with no actions (!) performed:

```
#  udevadm info /sys/class/net/rename6
P: /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/rename6
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/rename6
E: INTERFACE=rename6
E: IFINDEX=6
E: SUBSYSTEM=net
E: USEC_INITIALIZED=107749999
E: ID_NET_NAMING_SCHEME=v249
E: ID_NET_NAME_MAC=enx90e2ba16d6f6
E: ID_OUI_FROM_DATABASE=Intel Corporate
E: ID_NET_NAME_PATH=enp4s0f1
E: ID_BUS=pci
E: ID_VENDOR_ID=0x8086
E: ID_MODEL_ID=0x10fb
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=82599ES 10-Gigabit SFI/SFP+ Network Connection (Ethernet Server Adapter X520-2)
E: ID_PATH=pci-0000:04:00.1
E: ID_PATH_TAG=pci-0000_04_00_1
E: ID_NET_DRIVER=ixgbe
E: ID_NET_LINK_FILE=/etc/systemd/network/95-cluster-dev2.link
E: ID_NET_NAME=rename6
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/rename6
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

# cat /etc/systemd/network/95-cluster-dev2.link
[Match]
Type=ether
Path=pci-0000:04:00.1

[Link]
Alias=test23
AlternativeName=test32
NamePolicy=
```

So due to the missing ID_PATH match (?) the interface was (`ID_NET_NAMING_SCHEME=v249`) renamed. Moreover, after `rmmod ixgbe; modprobe ixgbe` I got this and another one interface renamed to `rename12` and `rename13` (both hold by `bond` driver, but after releasing):

```
# udevadm info /sys/class/net/rename12
P: /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/rename12
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/rename12
E: INTERFACE=rename12
E: IFINDEX=12
E: SUBSYSTEM=net
E: USEC_INITIALIZED=481728112
E: ID_NET_NAMING_SCHEME=v249
E: ID_NET_NAME_MAC=enx90e2ba16d6f4
E: ID_OUI_FROM_DATABASE=Intel Corporate
E: ID_NET_NAME_PATH=enp4s0f0
E: ID_BUS=pci
E: ID_VENDOR_ID=0x8086
E: ID_MODEL_ID=0x10fb
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=82599ES 10-Gigabit SFI/SFP+ Network Connection (Ethernet Server Adapter X520-2)
E: ID_PATH=pci-0000:04:00.0
E: ID_PATH_TAG=pci-0000_04_00_0
E: ID_NET_DRIVER=ixgbe
E: ID_NET_LINK_FILE=/etc/systemd/network/98-default.link
E: ID_NET_NAME=rename12
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/rename12
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

# cat /etc/systemd/network/98-default.link
[Match]
OriginalName=*

[Link]
NamePolicy=
AlternativeNamesPolicy=
MACAddressPolicy=persistent
```

So in this case not only the `95-cluster-dev2.link` interface was renamed (missing==mismatching ID_PATH?), but also the disabled `NamePolicy=` was not applied via `OriginalName=*` (the supposed catch-all statement). Is there some other filesystem-based (i.e. not `net.ifnames=0`) way of disabling `NamePolicy=`?
Also worth noting - my `Alias=test23` was not set (while `AlternativeName=test32` is applied).

With no bonding applied consecutive 'rmmod ixgbe; modprobe ixgbe` keep renaming the interfaces and not applying any of the link settings **until 90 seconds passes** (!):

```
# rmmod ixgbe; modprobe ixgbe
# ip a | tail -n4
16: rename16: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff
17: rename17: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 90:e2:ba:16:d6:f6 brd ff:ff:ff:ff:ff:ff
[waiting...]
# ip a | tail -n5
16: rename16: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff
17: rename17: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 90:e2:ba:16:d6:f6 brd ff:ff:ff:ff:ff:ff
    altname test32
```

with following logs:
```
Apr 17 18:36:19 systemd-udevd[2796]: eth1: Worker [5708] processing SEQNUM=6973 is taking a long time
Apr 17 18:36:20 systemd-udevd[2796]: eth1: Worker [5705] processing SEQNUM=7105 is taking a long time
Apr 17 18:36:49 systemd-udevd[5708]: eth1: Failed to rename network interface 18 from 'eth1' to 'internet0': File exists
Apr 17 18:36:49 systemd-udevd[5708]: eth1: Failed to process device, ignoring: File exists
Apr 17 18:36:49 systemd-udevd[6682]: Using default interface naming scheme 'v249'.
Apr 17 18:36:50 systemd-udevd[5705]: eth1: Failed to rename network interface 19 from 'eth1' to 'internet0': File exists
Apr 17 18:36:50 systemd-udevd[5705]: eth1: Failed to process device, ignoring: File exists
```

Therefore:
6. why does it try to rename `eth1` (igb, not ixgbe) to `internet0` which was already renamed long before?
7. why does the `eth1/internet0` issue slows down processing of independent `eth2` and `eth3`?

**Comment by yuwata** [comment]
> Ad. 2 - that was a question on the side. I only wonder why there's a rule of processing that "**first** matching file and it's drop-ins win" instead "apply **all** matching files (and all their respective drop-ins)". Once known there's not any issue by itself here (although it means that `99-default.link` doesn't apply for any link already handled, therefore it's rather `99-fallback.link`).

Haha, exactly the same question comes #23105.

> Ad. 3 - can't match by PCI path; in udev rules I match devices with `DEVPATH==...`, but there's no appropriate match in `systemd.link`. Shouldn't `Path=` catch both `ID_PATH` and `DEVPATH`?

You can also use `Property=DEVPATH=...`. But, for your devices, ID_PATH should exist...

> With no bonding applied consecutive 'rmmod ixgbe; modprobe ixgbe` keep renaming the interfaces and not applying any of the link settings **until 90 seconds passes** (!):

rmmod and modprobe is not a good way to reset devices, and we cannot support the way. Please use `udevadm trigger --action=add /sys/class/net/INTERFACE` to reconfigure interfaces by udevd, or reboot system.

**Comment by g0tar** [comment]
:)

Ad. 3 - documentation skips the part that `Property=` can take wildcards:

```
Property="DEVPATH=/devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/*"
```
indeed matches and that's fine for me. ID_PATH eventually appears, but it's just too late and the interface get's already renamed, so this looks like some kind of race:

```
# udevadm monitor | grep -v queues
KERNEL[2538.678673] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/eth1 (net)
KERNEL[2538.689260] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/eth1/ixgbe-mdio-0000:04:00.0 (mdio_bus)
KERNEL[2538.689300] bind     /devices/pci0000:00/0000:00:02.3/0000:04:00.0 (pci)
KERNEL[2538.698152] move     /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/rename16 (net)
KERNEL[2538.900655] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth1 (net)
KERNEL[2538.911111] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth1/ixgbe-mdio-0000:04:00.1 (mdio_bus)
KERNEL[2538.911139] bind     /devices/pci0000:00/0000:00:02.3/0000:04:00.1 (pci)
KERNEL[2538.911170] add      /bus/pci/drivers/ixgbe (drivers)
KERNEL[2538.911193] add      /module/ixgbe (module)
UDEV  [2538.917796] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth1 (net)
UDEV  [2538.950929] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth1/ixgbe-mdio-0000:04:00.1 (mdio_bus)
UDEV  [2538.951240] add      /bus/pci/drivers/ixgbe (drivers)
UDEV  [2538.951405] add      /module/ixgbe (module)
UDEV  [2538.951566] bind     /devices/pci0000:00/0000:00:02.3/0000:04:00.1 (pci)
[90 seconds delay here!]
UDEV  [2628.980704] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/internet0 (net)
UDEV  [2628.989971] add      /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/eth1/ixgbe-mdio-0000:04:00.0 (mdio_bus)
UDEV  [2628.990576] bind     /devices/pci0000:00/0000:00:02.3/0000:04:00.0 (pci)
UDEV  [2628.992524] move     /devices/pci0000:00/0000:00:02.3/0000:04:00.0/net/rename16 (net)
```
...while in fact this is a simple clash with previous tests caused by `eth1` being recycled and reused after `rmmod+modprobe ixgbe`:

```
#  cat 94-eth1.link 
[Match]
#Path=pci-0000:00:1c.5-*
OriginalName=eth1

[Link]
Name=internet0
NamePolicy=
```

So what I see in 6 and 7 is now explained, only the `ID_NET_LINK_FILE` value after **failed** rename is misleading (to make me believe `NamePolicy=` was not disabled). Simply avoid using `OriginalName=` for anything...

As for the "rebooting the system" - this is a no-go for production machines I need as lower downtime as possible, while allowing the **NIC drivers to be updated**. `rmmod + modprobe` cause a few seconds delay at most (and only the NICs using the replaced module), while BIOS is about 5 minutes. If this cannot be supported it should be put in first line of docs not to waste time, but I don't see any reasonable cause for this to be not supported. Anyway, this only simulates hotplugging or device remove/rescan, so it is pretty valid requirement for the system to survive. It's not my intention to reconfigure the settings this way of course, but that part is merely a subset of operations chain.


OK, I think I got this solved (with only some documentation deficiencies, whatever). I will test this again in clean environment and probably close this ticket tomorrow (if the `ifalias` turns out to be related as well).

In the meantime thanks for all the help!

**Comment by g0tar** [comment]
I got only one issue left - not setting the `Alias=`; I've set it to 280 chars (i.e. more than `IFALIASZ`) expecting to see the warning from src/udev/net/link-config.c#L988, but nothing happens:

```
Apr 18 12:04:20 systemd-udevd[2794]: eth3: Device is queued (SEQNUM=5268, ACTION=add)
Apr 18 12:04:20 systemd-udevd[2794]: Validate module index
Apr 18 12:04:20 systemd-udevd[2794]: Check if link configuration needs reloading.
Apr 18 12:04:20 systemd-udevd[2794]: eth3: Device ready for processing (SEQNUM=5268, ACTION=add)
Apr 18 12:04:20 systemd-udevd[2794]: Successfully forked off 'n/a' as PID 3937.
Apr 18 12:04:20 systemd-udevd[2794]: eth3: Worker [3937] is forked for processing SEQNUM=5268.
Apr 18 12:04:20 systemd-udevd[2794]: ixgbe-mdio-0000:04:00.1: Device is queued (SEQNUM=5269, ACTION=add)
Apr 18 12:04:20 systemd-udevd[2794]: ixgbe-mdio-0000:04:00.1: SEQNUM=5269 blocked by SEQNUM=5268
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Processing device (SEQNUM=5268, ACTION=add)
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /lib/udev/rules.d/75-net-description.rules:6 Importing properties from results of builtin command 'net_id'
Apr 18 12:04:20 systemd-udevd[3937]: Using default interface naming scheme 'v249'.
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /lib/udev/rules.d/75-net-description.rules:12 Importing properties from results of builtin command 'hwdb --subsystem=pci'
Apr 18 12:04:20 systemd-udevd[3937]: eth3: hwdb modalias key: "pci:v00008086d000010FBsv00008086sd0000000Cbc02sc00i00" 
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /etc/udev/rules.d/80-net-setup-link.rules:5 Importing properties from results of builtin command 'path_id' 
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /etc/udev/rules.d/80-net-setup-link.rules:9 Importing properties from results of builtin command 'net_setup_link'
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Failed to query name_assign_type: Invalid argument
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Config file /etc/systemd/network/92-cluster-dev2.link is applied
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Failed to query name_assign_type: Invalid argument
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Policies didn't yield a name and Name= is not given, not renaming.
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /etc/udev/rules.d/80-net-setup-link.rules:11 NAME 'eth3'
Apr 18 12:04:20 systemd-udevd[3937]: eth3: /lib/udev/rules.d/99-systemd.rules:60 RUN '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/$name --prefix=/net/ipv4/neigh/$name --prefix=/net/ipv6/conf/$name --prefix=/net/ipv6/neigh/$name'
Apr 18 12:04:20 systemd-udevd[3937]: eth3: sd-device: Created db file '/run/udev/data/n6' for '/devices/pci0000:00/0000:00:02.3/0000:04:00.1/net/eth3' 
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Running command "/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/eth3 --prefix=/net/ipv4/neigh/eth3 --prefix=/net/ipv6/conf/eth3 --prefix=/net/ipv6/neigh/eth3"
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Starting '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/eth3 --prefix=/net/ipv4/neigh/eth3 --prefix=/net/ipv6/conf/eth3 --prefix=/net/ipv6/neigh/eth3'
Apr 18 12:04:20 systemd-udevd[3937]: Successfully forked off '(spawn)' as PID 3938.
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Process '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/eth3 --prefix=/net/ipv4/neigh/eth3 --prefix=/net/ipv6/conf/eth3 --prefix=/net/ipv6/neigh/eth3' succeeded.
Apr 18 12:04:20 systemd-udevd[3937]: eth3: Device processed (SEQNUM=5268, ACTION=add)
Apr 18 12:04:20 systemd-udevd[3937]: eth3: sd-device-monitor: Passed 782 byte to netlink monitor
Apr 18 12:04:20 systemd-udevd[2794]: ixgbe-mdio-0000:04:00.1: Device ready for processing (SEQNUM=5269, ACTION=add) 
Apr 18 12:04:20 systemd-udevd[2794]: ixgbe-mdio-0000:04:00.1: sd-device-monitor: Passed 209 byte to netlink monitor
Apr 18 12:04:20 systemd-udevd[3937]: ixgbe-mdio-0000:04:00.1: Processing device (SEQNUM=5269, ACTION=add)
Apr 18 12:04:20 systemd-udevd[3937]: ixgbe-mdio-0000:04:00.1: Device processed (SEQNUM=5269, ACTION=add)
Apr 18 12:04:20 systemd-udevd[3937]: ixgbe-mdio-0000:04:00.1: sd-device-monitor: Passed 209 byte to netlink monitor
Apr 18 12:04:23 systemd-udevd[2794]: Cleanup idle workers
Apr 18 12:04:23 systemd-udevd[3937]: Unload module index
Apr 18 12:04:23 systemd-udevd[3937]: Unloaded link configuration context.
Apr 18 12:04:23 systemd-udevd[2794]: Worker [3937] exited
```

I've been trackking this down to d2df0d0ed3a88e491405b403e6022e6619750130, would that be src/shared/conf-parser.h
 missing the:
```
CONFIG_PARSER_PROTOTYPE(config_parse_ifalias);
```
?

**Comment by g0tar** [comment]
No, there's no warning. Have you actually tested the `Alias=` directive?
