### ISSUE TITLE
UseDelegatedPrefix doesn't enable DHCPPrefixDelegation

### ISSUE THREAD

**Issue by jkhsjdhjs** [systemd/systemd#23041]
**systemd version the issue has been seen with**
 > 250.4

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.17.1-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Issue Description**
The `systemd.network(5)` docs state the following about the `UseDelegatedPrefix` option of the `[DHCPv6]` section:
>UseDelegatedPrefix=
           When true (the default), the client will request the DHCPv6 server to delegate prefixes. If the server provides prefixes to be delegated, then subnets of the prefixes are assigned to the interfaces which enables DHCPPrefixDelegation=. See also the
           DHCPPrefixDelegation= setting in the [Network] section, settings in the [DHCPPrefixDelegation] section, and RFC 8415[19].

This issue is specifically about the sentence:
>If the server provides prefixes to be delegated, then subnets of the prefixes are assigned to the interfaces which enables DHCPPrefixDelegation=.

This sentence implies that, if a prefix is delegated, then `DHCPPrefixDelegation=yes` is set automatically. This is not correct, because `DHCPPrefixDelegation=yes` would also mean, that an address of that prefix is assigned to the respective interface, which doesn't happen. An address is assigned when explicitly setting `DHCPPrefixDelegation=yes`.

Thus I suspect that the docs are wrong and the reception of a prefix doesn't enable `DHCPPrefixDelegation`. Maybe the sentence means that a delegated prefix enables the use of the `DHCPPrefixDelegation` setting. In this case the wording should be adjusted IMO.

**Comment by yuwata** [comment]
I cannot find anything confusing in the sentence, though, I am not native. Any suggestion?

**Comment by jkhsjdhjs** [comment]
I'm not a native speaker either, but as I said, to me it sounds like the reception of a delegated prefix also sets `DHCPPrefixDelegation=yes`, because its worded like
>If the server provides prefixes to be delegated, then subnets of the prefixes are assigned to the interfaces which enables DHCPPrefixDelegation=.

which I interpret as
> If server provides prefixes -> prefixes are assigned to interface -> DHCPPrefixDelegation=yes

How do you interpret this sentence @yuwata?

**Comment by yuwata** [comment]
I intended `assigned to the interfaces which enables DHCPPrefixDelegation=.` as `assigned to the interfaces which have DHCPPrefixDelegation=yes.`, or `assigned to the interfaces whose corresponding .network files enable DHCPPrefixDelegation=.`
If you think they are clear or better, I will rewrite so.

**Comment by jkhsjdhjs** [comment]
Ahh, I see. IMO the sentence is wrong the way it's currently in the manpage. To reflect the meaning you intended it should've been written this way:
```diff
- assigned to the interfaces which enables DHCPPrefixDelegation=.
+ assigned to the interfaces that enable DHCPPrefixDelegation=.
```

I also like your first proposal, namely
> assigned to the interfaces which have DHCPPrefixDelegation=yes.

but the `which` should be changed to `that` either way, because `which` is used to give additional information about an object while `that` is used to restrict a selection of objects with additional information.
I'm not good at explaining the difference, but there are several sites *that* explain the difference and give examples.
