### ISSUE TITLE
UID / GID mappings for mount units

### ISSUE THREAD

**Issue by quasicomputational** [systemd/systemd#23056]
**Is your feature request related to a problem? Please describe.**
I would like to mount a filesystem with remapped UIDs and GIDs declaratively, where the mapped-to UID is a system user looked up from /etc/passwd (and hence could vary between systems) and the mapped-from UID is statically known.

**Describe the solution you'd like**
New properties on mount units to describe the offset(s?) and range(s?) to map, where the offset can be a symbolic username that's looked up from /etc/passwd.

**Describe alternatives you've considered**
nspawn's support for automatically remapping bind mounts doesn't work for this use-case, which is matching to an already-assigned UID that may be anywhere within the container's private UID range.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 251.

**Comment by poettering** [comment]
I sympathize, but I am pretty sure this should not be in systemd, but be implemented in util-linux' /bin/mount command instead, via one of those `X-mount.<foo>` mount options. After all, this should be available for any kind of mount, not just those done through systemd.

@karelzak what do you say?

@quasicomputational can you file this as RFE against util-linux instead?

**Comment by poettering** [comment]
@brauner or did you ever look into adding this to /bin/mount yourself?

**Comment by brauner** [comment]
I did indeed. I had started a branch a while back but never had the time to finish it:
https://github.com/brauner/util-linux/tree/2021-08.16.idmapped_mounts

If @karelzak would be interested in this I can work on this. I wasn't sure if @karelzak had his own plans?

**Comment by quasicomputational** [comment]
> I sympathize, but I am pretty sure this should not be in systemd, but be implemented in util-linux' /bin/mount command instead, via one of those X-mount.<foo> mount options. After all, this should be available for any kind of mount, not just those done through systemd.

Sure. If you want, you can consider this an RFE for nice syntax on top of such a substrate; I don't really care too much how it looks under the covers so long as I can express the intent declaratively and I don't have to be invoking `mount_setattr(2)` myself.

I've gone ahead and filed util-linux/util-linux#1652 a suggested.

**Comment by poettering** [comment]
OK, let's close here, and continue over on util-linux
