### ISSUE TITLE
Freezing execution when plugging USB stick.

### ISSUE THREAD

**Issue by CptMitten** [systemd/systemd#23050]
**systemd version the issue has been seen with**
 ```/sbin/init --version
systemd 249 (249)
-PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK -SECCOMP -GCRYPT -GNUTLS +OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 +LZ4 -XZ +ZLIB -ZSTD -XKBCOMMON -UTMP -SYSVINIT default-hierarchy=hybrid
```

**Used distribution**
 > Custom buildroot (2021.08.03) distribution for embedded target.
 > glibc (2.27)

**Linux kernel version used** (`uname -a`)
 > `Linux target-cpt1 5.10.30-rt37 #1 SMP Mon Feb 28 12:19:13 CET 2022 armv7l GNU/Linux`

**CPU architecture issue was seen on**
 > armv7l

**Expected behaviour you didn't see**
 > I use a udev rule in association with systemd-mount to mount USB sticks. Same rule as the exemple in systemd-mount(1) man page i.e.
```
ACTION=="add", SUBSYSTEMS=="usb", SUBSYSTEM=="block", ENV{ID_FS_USAGE}=="filesystem", \
	RUN{program}+="/usr/bin/systemd-mount --no-block --owner=user --automount=yes --collect $devnode"
```
> So I expect my USB stick to be properly mounted / unmounted and `systemd` and friends to work as usual.

**Unexpected behaviour you saw**
 > After unplugging my USB stick the filesystem seems not to be properly unmounted. Normally this shouldn't be a big deal but when I reconnect the same USB stick on my system it leads `systemd` to crash.

**Steps to reproduce the problem**
 > This `systemd` behavior seems to be really specific. I suspect it to be linked with my target (a custom board) or my installation (custom distribution) and thus to be non-reproducible on your system. Anyway, here are the steps:

 > Plug a USB stick and do classic file operation (create/delete a file).
> Unplug it.
> Re-plug it.

**Additional program output to the terminal or log subsystem illustrating the issue**
Journal after `systemctl log-level debug` and `systemctl log-target kmsg`:
```
Apr 07 11:06:02 target-scd1 systemd[1]: Failed unmounting USB_DISK_2.0 1.
...
Apr 07 11:06:03 target-scd1 systemd[1]: Caught <SEGV>, dumped core as pid 969.
Apr 07 11:06:03 target-scd1 systemd[1]: Freezing execution.
```
Additional journal logs: https://pastebin.com/qKEhmr0P

Gdb backtrace of the core dump:
```
Thread 1 (LWP 969):
#0  0x76acb07c in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x004d0dbc in crash ()
#2  <signal handler called>
#3  0x00520364 in manager_loop ()
#4  0x004cbcc4 in main ()
```

strace of pid 1:
https://pastebin.com/1i2R1rir

I also tried to use gdb directly on pid 1 but it wasn't conclusive (systemd was too slow and I couldn't use it / reproduce the bug).

After all those investigation I found that **upgrading to version 250 of systemd fixed the issue**.
I was suprised it fixed my issue because I didn't saw anything related in the v250 patch note.
I wrote this issue in order to help other users. It could also interest someone who knows more than me. I can help to dig more.

Many thanks to the #systemd IRC community for their help.

**Comment by poettering** [comment]
That back trace is not usable. Please provide one with debug symbols, otherwise this is not actionable.

**Comment by daiaji** [comment]
A similar freeze occurred on my arm device.
```
Starting kernel ...

:: running early hook [udev]
Starting version 250.4-1-arch
:: running hook [udev]
:: Triggering uevents...
:: performing fsck on '/dev/mmcblk1p2'
:: mounting '/dev/mmcblk1p2' on real root
:: running cleanup hook [udev]
Failed to send exit request: Connection refused

Welcome to Manjaro ARM!

[  OK  ] Created slice Slice /system/getty.
[  OK  ] Created slice Slice /system/modprobe.
[  OK  ] Created slice Slice /system/serial-getty.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Started Dispatch Password …ts to Console Directory Watch.
[  OK  ] Started Forward Password R…uests to Wall Directory Watch.
[  OK  ] Set up automount Arbitrary…s File System Automount Point.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Local Integrity Protected Volumes.
[  OK  ] Reached target Path Units.
[  OK  ] Reached target Remote Encrypted Volumes.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Reached target Slice Units.
[  OK  ] Reached target Swaps.
[  OK  ] Reached target Local Verity Protected Volumes.
[  OK  ] Listening on Device-mapper event daemon FIFOs.
[  OK  ] Listening on Process Core Dump Socket.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket.
[  OK  ] Listening on Network Service Netlink Socket.
[  OK  ] Listening on Userspace Out-Of-Memory (OOM) Killer Socket.
[  OK  ] Listening on udev Control Socket.
[  OK  ] Listening on udev Kernel Socket.
[  OK  ] Listening on User Database Manager Socket.
         Mounting Huge Pages File System...
         Mounting POSIX Message Queue File System...
         Mounting Kernel Debug File System...
         Mounting Temporary Directory /tmp...
         Starting Create List of Static Device Nodes...
         Starting Load Kernel Module configfs...
         Starting Load Kernel Module drm...
         Starting Load Kernel Module fuse...
         Starting Journal Service...
         Starting Load Kernel Modules...
         Starting Generate network …ts from Kernel command line...
         Starting Remount Root and Kernel File Systems...
         Starting Coldplug All udev Devices...
[    7.520487] systemd[1]: Caught <SEGV>, dumped core as pid 314.
[    7.521034] systemd[1]: Freezing execution.
```

**Comment by CptMitten** [comment]
I tried to get a proper backtrace, but it was more difficult than I expected. I still have options to try e.g. recompile systemd without optimization flags... I will write another feedback on this issue asap.
