### ISSUE TITLE
Fix of the toggle touchpad key in Vaio FE14 

### ISSUE THREAD

**Issue by davijosw** [systemd/systemd#23058]
**systemd version the issue has been seen with**
 > 249.4-2.fc35

**Used distribution**
 > Fedora 35

**Linux kernel version used** (`uname -a`)

 > `Linux vaio-de-davi 5.16.18-200.fc35.x86_64 #1 SMP PREEMPT Mon Mar 28 14:10:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 `

**CPU architecture issue was seen on**
 > CPU:
  Info: quad core model: Intel Core i5-8250U bits: 64 type: MT MCP
    arch: Coffee Lake rev: A cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 800 min/max: 400/3400 cores: 1: 800 2: 800 3: 800
    4: 800 5: 800 6: 800 7: 800 8: 800 bogomips: 28800

**Expected behaviour you didn't see**
 > Fn+F1 in my device was to be able to toggle (on-off) touchpad

**Unexpected behaviour you saw**
 > The pressing of the keys wasn't responding

**Steps to reproduce the problem**
 > Press Fn+F1

**Additional program output to the terminal or log subsystem illustrating the issue**

``` ```
By a remap of the keyboard, the system is now able to do what the keys were meant to. There's the file that I made and I think that is generally applicable, thanks!
[keyboard-config.txt](https://github.com/systemd/systemd/files/8473094/keyboard-config.txt)

**Comment by yuwata** [comment]
I am not sure about the change, but please submit it if it works for you.

**Comment by davijosw** [comment]
ok

**Comment by davijosw** [comment]
I think that too. But I really don't know how to do it, because I don't want to make a mistake. I'm not a dev.

**Comment by yuwata** [comment]
1. fork the systemd repository,
2. clone the forked systemd repository,
3. edit hwdb.d/60-keyboard.hwdb, and make a commit,
4. push the commit into your repository,
5. create a PR.

Please let us know if you have trouble about that. Thank you!

**Comment by davijosw** [comment]
I did some cleaning on the file, still working! Could you take a look? Maybe now it will certainly help more users. 
[keyboard-config.txt](https://github.com/systemd/systemd/files/8473409/keyboard-config.txt)
