### ISSUE TITLE
user-.slice (hyphen templating pattern)

### ISSUE THREAD

**Issue by DSpeichert** [systemd/systemd#2305]
I am trying to create a configuration for the purpose of limiting CPU/MEM/etc. per-user.
According to systemd-cgls, it would be best to specify the limit at user-N.slice (e.g. user-1000.slice), which is under global user.slice. The user-1000.slice has typically `user@1000.service` an and session-cN.scope under itself.

Since I want to limit together both the lingering services (in `user@1000.service`) and interactive login, I tried to create a config following the well-known `user@.service`-style templating scheme: `/etc/systemd/system/user-.slice.d/foo.conf`. That doesn't get loaded. It would be a nice feature to have "-" (hyphen) be a templating pattern. This would allow the operator to configure all user slices at once.

**Comment by poettering** [comment]
Slices are recursive forming a tree structure. Limits set on higher slices are enforced on all slices and other units located below it. Thus, just make your changes on user.slice, and it will affect the settings of all user units, including user slices, user@.service and anything else.

**Comment by DSpeichert** [comment]
@poettering Thank you for your answer.
The way I understand it, if I set CPUQuota=100% on user.slice (the global slice), it will limit all my users collectively to 1 core.

What I intend to do is to limit every single one of my users to their own equivalent of 1 core. Therefore, I want to set CPUQuota=100% on each user-N.slice without imposing a limit on user.slice. Is there another way to do that already?

**Comment by KellerFuchs** [comment]
Encountered the same issue.
I tried to change `Slice` by a drop-in in `user@.service`, but it seems that the `user-${UID}` slice name is hardcoded somewhere in pid1, `logind` or `pam_systemd(8)` (I'm not sure which, as I didn't manage to find the right place).

Using `user@${PID}.slice` would be much nicer, as it would enable use of the existing templating mechanisms, but that would break backwards compatibility.

As mentionned, I do not want to enforce a limit on `user.slice` directly.

**Comment by KellerFuchs** [comment]
PS: My attempts at doing that can be found here: https://gist.github.com/KellerFuchs/c7f110baf9df8eb504ef

**Comment by KellerFuchs** [comment]
It seems there is code out there that relies on the `user-${PID}.slice` name like [`src/basic/cgroup-util.c:cg_path_get_owner_uid`](https://github.com/systemd/systemd/blob/bcbd1d0cd5a1e6ff068f251c99ed7905223fed67/src/basic/cgroup-util.c#L1548-L1571).
However, I only found this single function, so making it configurable (or at least converting to a templated form) should be doable.
