### ISSUE TITLE
The system is frozen.

### ISSUE THREAD

**Issue by daiaji** [systemd/systemd#23062]
**systemd version the issue has been seen with**
 > systemd 250.4

**Used distribution**
 > Manjaro linux

**Linux kernel version used** (`uname -a`)

 > `Linux version 5.16.15-2-MANJARO-ARM`

**CPU architecture issue was seen on**
 > arm64

**Expected behaviour you didn't see**
 > The system starts normally.

**Unexpected behaviour you saw**
 > The system is frozen.

**Steps to reproduce the problem**
 > Start the system.

**Additional program output to the terminal or log subsystem illustrating the issue**

[screen.log](https://github.com/systemd/systemd/files/8475073/screen.log)

**Comment by floppym** [comment]
```
[    7.998570] Unable to handle kernel NULL pointer dereference at virtual address 0000000000000009
```
Looks like a kernel bug, or faulty hardware, not a systemd issue.

**Comment by poettering** [comment]
yupp, @floppym is right: kernel problem, not systemd problem.
