### ISSUE TITLE
networkd: allow reaching online state with any interface

### ISSUE THREAD

**Issue by lheckemann** [systemd/systemd#23064]
**Is your feature request related to a problem? Please describe.**
I want the online state to be reached on a machine that is sometimes connected via WiFi and sometimes via Ethernet. Currently, I can't express this, because setting `RequiredForOnline=yes` on a single network file that matches both the wireless and the ethernet interface causes the online state to become conditional on _both_ being configured.

**Describe the solution you'd like**
I'd like some way to express that any of a set of network interfaces is sufficient to consider the system online.

**Describe alternatives you've considered**
- NetworkManager; networkd is far more pleasant to configure declaratively.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by clintonroy** [comment]
Have you tried the --any switch to systemd-networkd-wait-online ?

**Comment by yuwata** [comment]
Right. Please use --any.

**Comment by lheckemann** [comment]
Oh cool! I didn't realise I was just looking in the wrong place, thanks :)
