### ISSUE TITLE
Getty failed to restart on serial console

### ISSUE THREAD

**Issue by ArchGuyWu** [systemd/systemd#23085]
**systemd version the issue has been seen with**
 > 250.4-2

**Used distribution**
 > Arch Linux ARM

**Linux kernel version used** (`uname -a`)

 > `Linux ArchRPi 5.17.1-1-aarch64-ARCH #1 SMP Mon Mar 28 23:54:20 UTC 2022 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > Getty can restart after logging out.

**Unexpected behaviour you saw**
 > Getty failed to restart.

**Steps to reproduce the problem**
 > type exit,then press enter to logout

**Additional program output to the terminal or log subsystem illustrating the issue**
![Annotation 2022-04-14 224016](https://user-images.githubusercontent.com/52102426/163428767-84e61a10-7733-4dfb-8ef4-9ef985028845.png)

I finally found that this issue can be solved by setting the RestartSec value from 0 to 1.

**Comment by poettering** [comment]
Something is probably going on ith your serial port.

If you do "systemd-analyze log-level debug", does this generate more relevant output?

**Comment by poettering** [comment]
oh wait.

getty@.service is only for console ttys. Use serial-getty@.service for real serial ttys.

**Comment by ArchGuyWu** [comment]
Using serial-getty@.service works fine for me,but I cannot see the output during the early boot.
![Annotation 2022-04-20 170112](https://user-images.githubusercontent.com/52102426/164192402-365be3f5-c490-4d10-aaf5-a6d577380788.png)

**Comment by poettering** [comment]
if you want boot-time kernel output go to console you need to specify some console=ttyS0… option on the kernel cmdline. That's not a systemd thing though.

**Comment by ArchGuyWu** [comment]
Thanks.
