### ISSUE TITLE
Issue with Type=simple

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#2309]
I have a systemd unit file I wrote for the Hashicorp Vault service running on RHEL 7:

```
[Unit]
Description=Hashicorp Vault
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
ExecStart=/opt/hvault/vault server --config /etc/hvault/hvault.json
User=hvault
Group=hvault
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

The issue I am having is that if my service configuration file, in this case `/etc/hvault/hvault.json` is configured incorrectly and I run `/opt/hvault/vault server --config /etc/hvault/hvault.json` outside of systemd, I get the expected exit code of 1 and the service is not started.

The problem I am having in this context (when I expect a failure scenario) is running the service via systemd, I perform a `systemctl start hvault` and the exit code returned is 0.  However when I go to run `systemctl status hvault`, it indicates that there is an error in the service and its exit code was 1.  

Unless I am missing something, I would expect that if systemd could not start the service that `systemctl start hvault`would yield a non-zero exit code.

**Comment by poettering** [comment]
Type=simple does not expect any startup notifications from a service, and thus the service start job will not fail if the service decides to exit early with a failure.

Consider using Type=forking or Type=notify. In that case, systemd will wait until the daemon reported back that it finished initialization, and possible an error condition, and we will propagate that back to the caller.

Or in other words: by using Type=simple you explicitly told systemd that it shall not expect nor wait for initialization notifications and results, and hence you don't get any.
