### ISSUE TITLE
systemd-oomd cant detect zram swap /dev/zramX

### ISSUE THREAD

**Issue by pheiduck** [systemd/systemd#23095]
**systemd version the issue has been seen with**
 > 250.4

**Used distribution**
 > Manjaro Linux

**Linux kernel version used** (`uname -a`)

 > `Linux 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Apr 15 17:47:48 BlackBox systemd[1]: Starting Userspace Out-Of-Memory (OOM) Killer...
Apr 15 17:47:48 BlackBox systemd[1]: Started Userspace Out-Of-Memory (OOM) Killer.

**Unexpected behaviour you saw**
 > Apr 15 17:47:48 BlackBox systemd[1]: Starting Userspace Out-Of-Memory (OOM) Killer...
Apr 15 17:47:48 BlackBox systemd-oomd[884]: Swap is currently not detected; memory pressure usage will be degraded
Apr 15 17:47:48 BlackBox systemd[1]: Started Userspace Out-Of-Memory (OOM) Killer.

**Steps to reproduce the problem**
 > install zramd https://aur.archlinux.org/packages/zramd restart host see error on systemd-oomd

**Comment by poettering** [comment]
what does zramd do?

oomd just cares that swap devices are listed in /proc/swaps. Are they not for "zramd"?

**Comment by pheiduck** [comment]
earlyoom recognizes zram so maybe it does some things differently than systemd-oomd

**Comment by poettering** [comment]
my educated guess: zramd is a late boot service maybe? and thus runs after systemd-oomd? maybe zramd just needs to order itself against systemd-oomd?

**Comment by pheiduck** [comment]
> https://github.com/maximumadmin/zramd/blob/master/build/package/zramd.service shows that this is a late-boot service. `systemd-oomd.service` will generally start early, and there isn't any provision for ordering `zramd.service` before it. I don't think there's anything to fix here on our side.
> 
> (FWIW, I don't think this project makes much sense. It was created when zram-generator was already widely available, and I don't think it brings anything new to the table.)

Many thanks to all of you for your explanation, I will uninstall zramd and tryout zram-generator, btw does this have static or dynamic swap size?

**Comment by pheiduck** [comment]
Anyway `zram-generator` resolves my issue
