### ISSUE TITLE
Centos 7 which version of Systemd supports Cgroup V2

### ISSUE THREAD

**Issue by 0412jiangchong** [systemd/systemd#23109]
**systemd version the issue has been seen with**
 > …
219 cant supports cgroup v2 ,update to 244 but when building ，Check whether Centos7 supports cgroupv2 when the libmount version is greater than 2.30. What version of Systemd is supported?

 

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by yuwata** [comment]
Sorry, please contact to the downstream. Here is the upstream bug tracker.

**Comment by mrc0mmand** [comment]
As Yu said, there's nothing upstream can do about this. Also, I don't think you could use systemd with cgroups v2 on CentOS 7 without rebuilding a _lot_ of dependencies, including kernel, since cgroups v2 are (officially) supported in the RHEL 8.4 kernel.
