### ISSUE TITLE
documentation: `systemd.network` files must include numeric prefix?

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#23105]
**systemd version the issue has been seen with**

```
$ systemctl --version
systemd 250 (250.4-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

ArchLinux

**CPU architecture issue was seen on**
 
aarch64

**Steps to reproduce the problem**

Save the following to `/usr/lib/systemd/network/some-name.network`:

```dosini
[Match]
Name=wwan0

[Network]
DHCP=yes
```

**Expected behaviour you didn't see**

DHCP should be activated for `wwan0`.

**Unexpected behaviour you saw**
 
DHCP was not activated for `wwan0`

**Additional notes**

It seems that using  `/usr/lib/systemd/network/90-some-name.network` instead works.

I think a numeric prefix is required but not documented..?

**Comment by yuwata** [comment]
Strictly speaking, no, numeric prefix is not required. From systemd.network(5),
> All configuration files are collectively sorted and processed in lexical order, regardless of the directories in which they live.

However, prefixing with a number is highly recommended, as systemd-network-generator.service may generate .network files from the kernel command line under /run/systemd/network, which prefixed with a number.

I guess there exists another .network file which matches wwan0.

Please try `ls /run/systemd/network /usr/lib/systemd/network /etc/systemd/network`.

**Comment by WhyNotHugo** [comment]
The only files in the other directories are the package-provided ones:

```
➜ ll /run/systemd/network /usr/lib/systemd/network /etc/systemd/network

/run/systemd/network:

/usr/lib/systemd/network:
.rw-r--r-- root root 540 B Sat Mar 19 00:53:57 2022  80-6rd-tunnel.network
.rw-r--r-- root root 653 B Sat Mar 19 00:53:57 2022  80-container-host0.network
.rw-r--r-- root root 742 B Sat Mar 19 00:53:57 2022  80-container-ve.network
.rw-r--r-- root root 728 B Sat Mar 19 00:53:57 2022  80-container-vz.network
.rw-r--r-- root root  49 B Thu Mar 24 08:08:13 2022  80-iwd.link
.rw-r--r-- root root 696 B Sat Mar 19 00:53:57 2022  80-vm-vt.network
.rw-r--r-- root root 418 B Sat Mar 19 00:53:57 2022  80-wifi-adhoc.network
.rw-r--r-- root root 102 B Sat Mar 19 00:53:57 2022  80-wifi-ap.network.example
.rw-r--r-- root root  64 B Sat Mar 19 00:53:57 2022  80-wifi-station.network.example
.rw-r--r-- root root 499 B Sat Mar 19 00:53:57 2022  99-default.link
.rw-r--r-- root root  53 B Sun Apr 17 13:12:47 2022  ipv6-privacy.network
.rw-r--r-- root root  53 B Sun Apr 17 13:12:47 2022  wwan0.network
.rw-r--r-- root root 169 B Sun Apr 17 13:12:47 2022  mdns.network

/etc/systemd/network:
```

Renaming by prepending `95-` to the file makes it get picked up (interface uses DHCP), whereas when I remove the prefix, it stops using DHCP.

I assume it's the lack of a prefix that makes it get ignore; the lexical ordering for `wwlan0` would still put it in the same priority as adding the prefix.

**Comment by yuwata** [comment]
Could you show the [Match] section of ipv6-privacy.network and mdns.network?

**Comment by WhyNotHugo** [comment]
Sure!

```console
$ cat ipv6-privacy.network
[Match]
Name=*

[Network]
IPv6PrivacyExtensions=true

$ cat mdns.network
# Enable mDNS for ALL networks.
# TODO: only enable this on trusted networks.

[Match]
Name=*

[Network]
MulticastDNS=true

[Link]
Multicast=true
```

**Comment by yuwata** [comment]
Hey, they have `Name=*`!! So, ipv6-privacy.network is picked for wwan0, instead of wwan0.network.

**Comment by yuwata** [comment]
Note, you can find which .network file is applied to an interface by `networkctl status INTERFACE`. E.g.
```
$ networkctl status wlp59s0 
● 4: wlp59s0                                                                     
                     Link File: /etc/systemd/network/99-default.link
                  Network File: /etc/systemd/network/50-wifi-tokyo.network   <-- HERE!
                          Type: wlan
                         State: routable (configured)
                  Online state: online                                           
(snip)
```

**Comment by yuwata** [comment]
BTW, in #23107, I extended the explanation in man pages.

**Comment by WhyNotHugo** [comment]
> Hey, they have Name=*!! So, ipv6-privacy.network is picked for wwan0, instead of wwan0.network.

So only **one** file is read per each network? They don't "stack"?

**Comment by yuwata** [comment]
Right. Not stacked. Only one file is applied.

(Instead, files under drop-in directories _are_ 'stacked'.)

**Comment by WhyNotHugo** [comment]
Oh, right, only a single file's rules are applies to each network. I don't think I'd realised this before (maybe I need to re-read the docs again).

So, if I wanted rules to apply to _all_ networks, what would be the correct approach?

**Comment by WhyNotHugo** [comment]
> Note, you can find which .network file is applied to an interface by networkctl status INTERFACE. E.g.

Thanks, this is very handy!

**Comment by WhyNotHugo** [comment]
Actually, I don't see any mention on the docs that only a single `.network` file can be used for each network interface, so I guess my assumptions were not that off. I'd suggest also mentioning that in the man page?

**Comment by yuwata** [comment]
There are no cool way. But if you want to modularize the setting, then create several drop-in files e.g.
```
# /etc/systemd/network/privacy-extention.conf
[Network]
IPv6PrivacyExtensions=true
```
```
# /etc/systemd/network/mdns.conf
[Network]
MulticastDNS=true

[Link]
Multicast=true
```
Then, create drop-in directories e.g. `/etc/systemd/network/90-wwan0.network.d`, and create symlink to the .conf files in to each `.network.d` directories.

**Comment by yuwata** [comment]
> Actually, I don't see any mention on the docs that only a single `.network` file can be used for each network interface, so I guess my assumptions were not that off. I'd suggest also mentioning that in the man page?

Indeed. Sure, will update #23107.

**Comment by WhyNotHugo** [comment]
Many thanks!

**Comment by yuwata** [comment]
I found the sentence below in [Match] section.
```
The first (in lexical order) of the network files that matches a given device is
applied, all later files are ignored, even if they match as well.
```
