### ISSUE TITLE
Add support for  HP ProBook 11 G2 

### ISSUE THREAD

**Issue by rodin-ia** [systemd/systemd#23108]
Hallo,
on a laptop HP ProBook 11 G2 , when you press the fn + F2 key (disable | enable touchpad), I register events in dmsg:

atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.

The touchpad does not respond to the event.
Would it be possible to map those keys? How to find correct filter expression to add mapping to hwdb?
Thank you.

cat /sys/class/dmi/id/modalias
dmi:bvnHP:bvrN92Ver.01.49:bd07/12/2020:svnHP:pnHPProBook11G2:pvr:rvnHP:rn818F:rvrKBCVersion30.72:cvnHP:ct10:cvr:

systemd 245 (245.4-4ubuntu3.16)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Comment by yuwata** [comment]
Please try to modify 60-keyboard.hwdb, and if you find a way to make the key work, please submit as a PR. Thank you.

**Comment by rodin-ia** [comment]
Works with these values:
# HP ProBook 11G2
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHP*:pnHPProBook11G2*:pvr*
 KEYBOARD_KEY_d8=!f23  # fn+F2: touchpad off
 KEYBOARD_KEY_d9=!f22  # fn+F2: touchpad on

**Comment by poettering** [comment]
Still, please submit your patch as github PR, so that we can merge/CI test/attribute it properly.

**Comment by yuwata** [comment]
@rodin-ia Based on your suggestion, I opened PR #23202.
