### ISSUE TITLE
RFE/RFD: system call pointer checks with seccomp

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#23113]
**Is your feature request related to a problem? Please describe.**
Kernel may be confused by passing system call arguments with pointers pointing to high addresses used by kernel. Likewise, object sizes should not exceed available virtual address space.

**Describe the solution you'd like**
Systemd could provide an easy means to check pointers and object sizes with seccomp, for example with a new directive `SystemCallFilterCheckPointers=yes`.

For example, for system call `read(int fd, void *buf, size_t count)`, the following checks could be applied:
- 0 <= `buf` < `user_va_max_addr`
- `buf` + `count` < `user_va_max_addr` and there's no arithmetic overflow (for example, check also that  0 <= `count` < `user_va_max_addr`)
where `user_va_max_addr` is the highest virtual address available for the CPU for user applications, for example 1 << 47 for typical x86_64 (exact number can be read with CPUID).

The implementation could be in form of tables per architecture with a flag for each register (6 available for checking in seccomp), like
```
read: IGN, PTR0, COUNT0, IGN, IGN, IGN
open: PTR0, IGN, IGN, IGN, IGN, IGN
bind: IGN, PTR0, COUNT0, IGN, IGN, IGN
mmap: PTR0, COUNT0, IGN, IGN, IGN, IGN
munmap: PTR0, COUNT0, IGN, IGN, IGN, IGN
exit_group: IGN, IGN, IGN, IGN, IGN, IGN
```
The table would be used to construct a big seccomp filter which checks system call pointer arguments. Probably libseccomp can optimize the big switch into binary search and lots of leaf nodes are similar (read, write, bind etc). The entries which are not checked at all (`exit_group` above) don't have to be filtered.

**Describe alternatives you've considered**
The kernel of course performs similar checks, but doing it with seccomp BPF may provide additional protection in case there's a vulnerability in kernel checks.

In some cases, the system call arguments can be pointers to structures which also contain pointers (like `struct iovec` for `readv`) and seccomp can't check the pointers in the structures, so the protection is not complete. Checking (possibly) encoded size for `ioctl()` would be error prone.

**The systemd version you checked that didn't have the feature you are asking for**
main

**Comment by boucman** [comment]
that really sounds like something that should be checked unconditionnaly, and on the kernel side. no ?

**Comment by poettering** [comment]
does this really make sense? i.e. involving such heavy machinery  as seccomp for such basic, simple checks, that really really must be there anyway, and are the most superficial checks kernel code has to make anyway?

i mean, seccomp and bpf are known to not be free of security issues themselves, so usng them here for something the kernel has to do anyway, and that adds no new policy or anything sounds quite weird to me.

**Comment by topimiettinen** [comment]
Indeed the kernel should be and it _is_ doing this kind of basic checks. The filter would add extra protection in case the checks would be missing. But I think you are right and such a bug would be too simple to ever occur. Seccomp also can't do a good job at checking the pointers. Closing then.
