### ISSUE TITLE
Parameters not applied when executed from systemd service

### ISSUE THREAD

**Issue by andreevmipt** [systemd/systemd#23115]
Trying to apply parameters to amd gpu cards with the following
ExecStartPre=echo y | rocm-smi --setpoweroverdrive 130
(code=exited, status=0/SUCCESS)

rocm-smi returned 
0    74.0c  217.0W  2390Mhz  1000Mhz  46.67%  auto  255.0W   31%   99%   
1    69.0c  158.0W  2255Mhz  1000Mhz  46.67%  auto  215.0W   31%   99%
Parametes didnt applied

Run the same command from console with root access
echo y | rocm-smi --setpoweroverdrive 130
Parameters applied
0    61.0c  130.0W  1465Mhz  1000Mhz  46.67%  auto  130.0W   31%   99%   
1    64.0c  130.0W  2005Mhz  1000Mhz  46.67%  auto  130.0W   31%   99%  

The same problem with processor registers
setcap CAP_SYS_RAWIO=ep /usr/sbin/wrmsr
(code=exited, status=0/SUCCESS)
but actually not applied
msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW

What workarounds can be suggested?

uname -a
Linux gentoo64 5.13.5-gentoo #1 SMP PREEMPT Tue Oct 26 13:00:24 MSK 2021 x86_64 Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz GenuineIntel GNU/Linux

Installed
sys-apps/systemd-250.4-r1

eselect profile list
[9]   default/linux/amd64/17.1/desktop/plasma/systemd (stable)

**Comment by yuwata** [comment]
How about to wrap the command like `sh -c "echo y | ..."`?

**Comment by yuwata** [comment]
Otherwise `|` and later commands are handled as the argument of `echo`.

**Comment by andreevmipt** [comment]
sh -c "echo 'y' | rocm-smi --setpoweroverdrive 130" works, thank you

**Comment by poettering** [comment]
Yes, @yuwata is right. Your cmdline is a shell pipeline, and systemd does not implement a shell. wrap it in a "sh -c" call, and it should work. Closing.
