### ISSUE TITLE
Improving the touchpad precision vaio FE14

### ISSUE THREAD

**Issue by davijosw** [systemd/systemd#23120]
**systemd version the issue has been seen with**
 > 249.11-1.fc35

**Used distribution**
 > Fedora 35

**Linux kernel version used** (`uname -a`)

 > `5.16.20-200.fc35`

**CPU architecture issue was seen on**
 > Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz - 64bits

I'm doubt if the hwdb file has to be a pull request here or in libinut gitlab. I don't know if the two projects are managed together, like two brothers in the same family hahah. Anyway, if it is a make a pull request asap and modify the file to be more general for other users. Thanks. 

There's the file.
[61-evdev-local.hwdb.txt](https://github.com/systemd/systemd/files/8513715/61-evdev-local.hwdb.txt)

I'm based on `libinput measure touchpad-size` tool.

**Comment by poettering** [comment]
/cc @whot 

please submit as proper PR
