### ISSUE TITLE
apache2 + syslog + remote web statistics (matomo)

### ISSUE THREAD

**Issue by lposmb** [systemd/systemd#23129]
Hi,
By reading #6432, I see another use case that should be easy to do (and was with rsyslog), consider the following situation : 
- some staff in my job wants apache2 access logs to be sent to a matomo server (to get graphs of out websites's activity) "on the fly" (not rsync once a night).
- Javascript and pixels trackers are banned for good reasons nowadays.
- We have VMs with apache2 + php to serve the websites
- We have a separated VM with matomo (it have rsyslog udp 514 listening)
- Apache2 access logs are "direct write to files, no syslog", so no native easy remote forward
- Apache2 can do pipe logging, we use : 
CustomLog "|/usr/bin/logger -t apache -p local1.info" combined
- We can't prevent a write to /var/log/journal since then. Much wasted IO and space.
- In rsyslog we do : 
local1.info  @the-matomo-server:514
local1.info  stop
- We need a better solution other than drown the crucial information (system boot, services init 20+days ago) in the noise (unwanted local access apache logs) or wipe all logs from journald (by a global size threshold or so).
- I can't make a clue to get it work on my regular Debian 11 systems without loosing some logs.
- I can't even say the solution is "rm -rf /var/log/journal" and full fallback with rsyslog because there is some important information that aren't send to syslog facilities but stderr of daemons.

Things that came impossible with newer (and globally better) tools make people irritated and not open to consider the good aspects of it. This create systemd haters.

**Comment by poettering** [comment]
Closing, since this was apparently misfiled, as per comment.
