### ISSUE TITLE
udev assertion 'i < num' in device_update_properties_bufs() since 0bd29256

### ISSUE THREAD

**Issue by tambry** [systemd/systemd#23150]
**systemd version the issue has been seen with**
Bisected to 0bd292567a543d124cd303f7dd61169a209cae64

**Used distribution**
Debian Unstable

**Linux kernel version used** (`uname -a`)
`Linux v11.cleveronmobility.dev 5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
amd64

**Expected behaviour you didn't see**
Sucessful startup

**Unexpected behaviour you saw**
An assertion. As a result drivers necessary for the internal disk aren't loaded during initramfs and the system fails to boot.

**Steps to reproduce the problem**
Boot latest systemd master on PC Engines APU2

**Additional program output to the terminal or log subsystem illustrating the issue**
[Full boot log with `udev.log-priority=debug`](https://github.com/systemd/systemd/files/8529862/udev.boot.log.txt)

**Additional details**
Compiled using LLVM aed0e8b8056a with `-march=ivybridge`.

I built systemd with Debian tools and mostly downstream Debian patches. I'm hesitant to blame those at first as the offending commit seems innocuous.  
Will try building with the latest LLVM head soon. Happy to provide any further information or help with debugging.

**Comment by yuwata** [comment]
Maybe, compiler bug? Is it reproducible with a stable version of LLVM?

**Comment by tambry** [comment]
Reproduced with newer LLVM 7a98d8351b27 (yesterday's HEAD, no notable related changes committed since).

Not affected by disabling/enabling fortify and stackprotector. `-march=ivybridge` also isn't the culprit. Will try with an older LLVM release within a few days.

**Comment by thesamesam** [comment]
We've had people hit this in [Gentoo](https://bugs.gentoo.org/841770) with LLVM 14.0.3 and systemd-251-rc2.

**Comment by thesamesam** [comment]
CC @marxin @siddhesh in case you're interested, as it's related to #22801. But know you're both GCC people.

**Comment by evverx** [comment]
I'm not sure why GitHub didn't close it automatically. It was fixed by reverting that patch in https://github.com/systemd/systemd/pull/23621. Closing.
