### ISSUE TITLE
RFE: global ip addrlabel management (without matching `.network`/interface)

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#23159]
As described in https://github.com/systemd/systemd/pull/5529#issuecomment-1105770011, `ip addrlabel` can be independent of a specific device / `.network` / `.link`.

It's a bit annoying/confusing this is only accessible from a matching `.network` file. Even without systemd-networkd managing a specific interface, I'd expect to be able to configure this - we even have a global `networkctl label` command that's similar to `ip addrlabel list`.

I expect we could add this to `networkd.conf` system, into an `[IPv6Addresslabel]` section.

**Comment by maddes-b** [comment]
As a workaround I use a systemd service unit which executes a simple script.
Still I would prefer to define these in `networkd.conf`.

First the script named `net-addrlabel.sh` which I store in `/usr/local/sbin` (`chmod u=rwx-s,go=rx-s`):
```
#!/bin/sh

start() {
  /sbin/ip addrlabel add prefix 'fdxx:xxxx:xxxx:xxxx::/64' label '1111'
}

stop() {
  /sbin/ip addrlabel del prefix 'fdxx:xxxx:xxxx:xxxx::/64' label '1111'
}

case '${1}' in
  (start|stop) '$1' ;;
esac
```
Second the service unit file which calls the script:
```
## Service Unit file to handle custom IPv6 Address Labels
## https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
## https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html

[Unit]
Description=Custom IPv6 Address Labels
BindsTo=network-pre.target 
Before=network-pre.target 

[Install]
WantedBy=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/net-addrlabel.sh start
ExecStop=/usr/local/sbin/net-addrlabel.sh stop
```

**Comment by yuwata** [comment]
-> #34018.
