### ISSUE TITLE
What if I start a unit requiring a masked unit ?

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#2315]
Hi,

I'm wondering how systemd should react when starting a unit that requires a masked unit.

Currently it just accepts to do that but prior to v219 it had always refused.

Commit caffa4ef700fdd0eadd6c0b2ef9925611672a1bc changed this behaviour accidentally it seems.

Thanks

**Comment by fbuihuu** [comment]
Since masking tmp.mount is the "official" way to disable tmpfs on /tmp (cf http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems/) and basic.target has "RequiresMountsFor=/tmp" I assume that systemd shouldn't fail to start a unit that requires a masked one.

I'm surprised that this was broken for so long time though.

Also this seems to not be understood by several users, so I would suggest to improve the documentation a bit.

How about appending these words in systemctl(1) manpage section "mask" command:

> It worths noted that manual activation of a masked unit will result into an error whereas automatic activation won't. The dependency on the masked unit will be simply ignored in the later case.

**Comment by arvidjaar** [comment]
> I assume that systemd shouldn't fail to start a unit that requires a masked one

Why? Masked unit does not exist for all practical purposes. If it is required by other unit, other unit should obviously fail due to missing prerequisites. 

> basic.target has "RequiresMountsFor=/tmp"

It means _if_ /tmp is mount point, it must be mounted. If there is no mount unit for /tmp, nothing is required (OK, mount for / is required ...)

**Comment by fbuihuu** [comment]
@keszybz: since you changed this behaviour, could you comment ?

**Comment by keszybz** [comment]
Yes, this change wasn't intentional. Seems like a bug.

**Comment by poettering** [comment]
Fix waiting in #2565.
