### ISSUE TITLE
user service failing with: "Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy"

### ISSUE THREAD

**Issue by mika** [systemd/systemd#23163]
**systemd version the issue has been seen with**
 > 247.3-7 (latest on Debian/bullseye)

**Used distribution**
 > Debian (bullseye)

**Linux kernel version used**
 > `Linux sp2 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 
Every now and then `user@0.service: Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy` shows up.

Example from syslog:

```
/var/log/syslog:Apr 21 06:23:53 sp2 systemd[663650]: user@0.service: Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy
/var/log/syslog:Apr 21 06:23:53 sp2 systemd[663650]: user@0.service: Failed at step CGROUP spawning /lib/systemd/systemd: Device or resource busy
```

Corresponding journald entries:

```
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Succeeded.
Apr 21 06:23:53 sp2 systemd[1]: Starting User Manager for UID 0...
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Main process exited, code=exited, status=219/CGROUP
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Failed with result 'exit-code'.
Apr 21 06:23:53 sp2 systemd[1]: Failed to start User Manager for UID 0.
```

This is from a two node system, where automated SSH logins for user root take place multiple times every minute.
This *usually* works perfectly fine, but every now and then, I get this `Failed at step CGROUP spawning /lib/systemd/systemd: Device or resource busy` issue. (As a baseline: for a timerange with ~7k SSH logins there were 16 such failing CGROUP spawnings.)

I enabled `Environment=SYSTEMD_LOG_LEVEL=debug` for `user@.service`, and its corresponding output is available at https://michael-prokop.at/tmp/user-service-debug.txt - but I still don't see _what_ is actually going on, or _why_ it's failing.

Any ideas, how to further debug this? :thinking:

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
