### ISSUE TITLE
user service failing with: "Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy"

### ISSUE THREAD

**Issue by mika** [systemd/systemd#23164]
(Note: reporting https://github.com/systemd/systemd/issues/23163 again, as it's reproducible with v250 as well)

**systemd version the issue has been seen with**
 > 250 (250.4-1~bpo11+1)

**Used distribution**
 > Debian (bullseye)

**Linux kernel version used**
 > `Linux sp2 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 
Every now and then `user@0.service: Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy` shows up.

Example from syslog:

```
/var/log/syslog:Apr 21 06:23:53 sp2 systemd[663650]: user@0.service: Failed to attach to cgroup /user.slice/user-0.slice/user@0.service: Device or resource busy
/var/log/syslog:Apr 21 06:23:53 sp2 systemd[663650]: user@0.service: Failed at step CGROUP spawning /lib/systemd/systemd: Device or resource busy
```

Corresponding journald entries:

```
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Succeeded.
Apr 21 06:23:53 sp2 systemd[1]: Starting User Manager for UID 0...
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Main process exited, code=exited, status=219/CGROUP
Apr 21 06:23:53 sp2 systemd[1]: user@0.service: Failed with result 'exit-code'.
Apr 21 06:23:53 sp2 systemd[1]: Failed to start User Manager for UID 0.
```

This is from a two node system, where automated SSH logins for user root take place multiple times every minute.
This *usually* works perfectly fine, but every now and then, I get this `Failed at step CGROUP spawning /lib/systemd/systemd: Device or resource busy` issue. (As a baseline: for a timerange with ~7k SSH logins there were 16 such failing CGROUP spawnings.)

I enabled `Environment=SYSTEMD_LOG_LEVEL=debug` for `user@.service`, and its corresponding output is available at https://michael-prokop.at/tmp/user-service-debug.txt - but I still don't see _what_ is actually going on, or _why_ it's failing.

Any ideas, how to further debug this? :thinking:

**Comment by poettering** [comment]
Interesting. Is this a cgroupv2 system?

what is mounted at /sys/fs/cgroup? A `cgroup2` file system or `tmpfs`?

**Comment by poettering** [comment]
if you reproduce this after `systemd-analyze log-level debug`, is there anything more relevant in the logs?

**Comment by poettering** [comment]
the debug output you already posted shows v247. Are you sure this is reproducible with v250?

**Comment by poettering** [comment]
Would also be good if you could run `strace -p 1 -s 500 -y -f -o /tmp/log` immediately before reproducing the issue. This should then tell us which syscall precisely is failing with EBUSY here...

**Comment by mika** [comment]
> Interesting. Is this a cgroupv2 system?
> what is mounted at /sys/fs/cgroup? A cgroup2 file system or tmpfs?

```
root@sp2:~# grep /sys/fs/cgroup /proc/mounts 
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
```

> the debug output you already posted shows v247. Are you sure this is reproducible with v250?

Yes, the debug output is from v247 but I upgraded the affected system to v250 and it's still reproducible

> if you reproduce this after systemd-analyze log-level debug, is there anything more relevant in the logs?

Will provide the result as soon as it shows up again

> Would also be good if you could run strace -p 1 -s 500 -y -f -o /tmp/log immediately before reproducing the issue.
> This should then tell us which syscall precisely is failing with EBUSY here...

This will be hard to get, as the issue shows up randomly and usually around once per hour or so, but I'll see what I can do...

**Comment by mika** [comment]
Related `journalctl` lines with system running under `systemd-analyze log-level debug` (further output available https://michael-prokop.at/tmp/user-service-journald.txt)

```
Apr 24 13:22:41 sp2 systemd[1993564]: Bus bus-system: changing state RUNNING → CLOSED
Apr 24 13:22:41 sp2 systemd[1]: Received SIGCHLD from PID 1993564 (systemd).
Apr 24 13:22:41 sp2 systemd[1]: Child 1993564 (systemd) died (code=exited, status=0/SUCCESS)
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Child 1993564 belongs to user@0.service.
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Main process exited, code=exited, status=0/SUCCESS (success)
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Deactivated successfully.
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Service restart not allowed.
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Changed stop-sigterm -> dead
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Failed to destroy cgroup /user.slice/user-0.slice/user@0.service, ignoring: Device or resource busy
Apr 24 13:22:41 sp2 systemd[1]: user@0.service: Job 5754386 user@0.service/stop finished, result=done
Apr 24 13:22:41 sp2 systemd[1]: Stopped User Manager for UID 0.
```

**Comment by poettering** [comment]
Hmm this is interesting:

```
user@0.service: Failed to destroy cgroup /user.slice/user-0.slice/user@0.service, ignoring: Device or resource busy
```

So it appears something is first blocking detruction of the old cgroup so tht we get EBUSY, and then when the service is started next we'll also get EBUSY?

@htejun hmm, if we see EBUSY on removing a cgroup and later also EBUSY when trying to attach some process to it, what does that mean?

@mika do you have any per-user services that set KillMode=none or so? i.e. that expicitly intend to escape clean-up of their service? Or do you have sudo/su sessions you leave process around from or so?

**Comment by htejun** [comment]
@poettering, one obvious scenario is where the cgroup has a controller enabled and there's a sub-cgroup - the controller would prevent attaching a process to it and the sub-cgroup would disallow removing the cgroup.

```
root@test /s/f/cgroup# mkdir -p test/a
root@test /s/f/cgroup# echo +memory > test/cgroup.subtree_control
root@test /s/f/cgroup# rmdir test
rmdir: failed to remove 'test': Device or resource busy
root@test /s/f/cgroup [1]# echo $fish_pid > test/cgroup.procs
write: Device or resource busy
root@test /s/f/cgroup [1]# rmdir test/a
root@test /s/f/cgroup# rmdir test
```

**Comment by mika** [comment]
FTR, since I'm running PID 1 with strace attached, I didn't see the issue any longer (so it seems to be timing sensitive?)

**Comment by Werkov** [comment]
Yes, this looks like the cgroup cleanup is attempted too early (theory: upon SIGCHLD and not empty notification?).
(Consequently, if the service is quickly respawned, it can also prevent its start (in this particular case because of `Delegate=`).)

I can reproduce similar behavior with `systemd-250.4-5.1.x86_64`, kernel `5.18.0-rc4`.

```
# /etc/systemd/system/survive.service
[Service]
Type=notify
KillMode=mixed
ExecStart=/root/survive.sh
Delegate=pids memory

# /root/survive.sh
#!/bin/bash

function worker() {
        while true ; do
                echo $BASHPID: worker
                sleep 1
        done
}

echo "Main $BASHPID"
worker &
echo "Spawned $!"
systemd-notify --ready

sleep inf
```

It appears both `Type=notify` and `Delegate=pid memory` are necessary to trigger the issue (`Failed to destroy cgroup` in [my log](https://github.com/systemd/systemd/files/8563030/stop-log.txt)).

**Comment by holger24** [comment]
I am also seeing these messages:
Jul 14 20:02:01 athena systemd[2811393]: user@16246.service: Failed to attach to cgroup /user.slice/user-16246.slice/user@16246.service: Device or resource busy
Jul 14 20:02:01 athena systemd[2811393]: user@16246.service: Failed at step CGROUP spawning /usr/lib/systemd/systemd: Device or resource busy
Jul 14 20:02:01 athena systemd[1]: user@16246.service: Main process exited, code=exited, status=219/CGROUP
Jul 14 20:02:01 athena systemd[1]: user@16246.service: Failed with result 'exit-code'.
Jul 14 20:02:01 athena systemd[1]: Failed to start User Manager for UID 16246.

This happens for several different users, all are running a service of Type=notify. Is there anything I can do to avoid this?

**Comment by SeanConn15** [comment]
I have also seen this issue, using systemd version `245.4-4ubuntu3.15` on ubuntu focal, kernel `5.4.0-45-generic`

All I have to add is that it appears to only crash every other time user slice is created, and is possibly related to https://github.com/systemd/systemd/issues/12386

**Comment by poettering** [comment]
OK, let's close. If this resurfaces with current kernel+systemd later we can surely reopen this.
