### ISSUE TITLE
document how hibernate operates without resume= switch on kernel cmdline

### ISSUE THREAD

**Issue by OJFord** [systemd/systemd#23177]
**Is your feature request related to a problem? Please describe.**
I mistakenly thought that `resume`/`resume_offset` parameters were only needed on resume; not for hibernating in the first place. This led me on a bit of a wild goose chase wondering why resuming wasn't working properly, when it's simply because I never hibernated in the first place - `systemctl hibernate` (or from `HandleLidSwitch=hibernate`) was simply causing a shutdown.

**Describe the solution you'd like**
I'm a bit naive as to the implications, but ideally I'd think it could refuse to hibernate (exit with an error) if `/sys/power/resume` is `0:0`?

**Describe alternatives you've considered**
Alternatively, if not possible or the existing behaviour is desirable for some reason, I'd suggest putting a warning in the man page. Neither `systemctl(1)` nor `systemd.special(7)` mention this behaviour, as far as I can tell.

**The systemd version you checked that didn't have the feature you are asking for**

```
systemd 250 (250.4-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by arvidjaar** [comment]
`resume` kernel parameter is not **needed** for hibernating - systemd will use swap device if nothing was set earlier. So your system did hibernate (and stored image on swap), it just did not resume because `resume` parameter was missing. This probably should be indeed documented, may be in `systemd-sleep` man page.

**Comment by OJFord** [comment]
`resume` parameter was only missing on first boot; on the boot when I (intended to) resume it was present.

I'm not sure why that didn't work then; but at least it does now. Can close if wrong, or leave open to track document as you describe, I don't mind.

**Comment by smopucilowski** [comment]
> `resume` kernel parameter is not **needed** for hibernating - systemd will use swap device if nothing was set earlier.

Oh, I didn't know this. Documentation (esp in kernel) points to you requiring you specifying `resume=` to enable hibernation support.

**Comment by smopucilowski** [comment]
Had a play around with leaving `resume=` from the kernel cmdline, and hibernation stopped working --- booting the machine cold was the same as if it was a normal startup.

**Comment by YHNdnzj** [comment]
Fixed by https://github.com/systemd/systemd/pull/27330 on UEFI systems. Let's continue tracking this in https://github.com/systemd/systemd/issues/27247 with more details.
