### ISSUE TITLE
Adding link local addresses to wireguard interfaces will cause network configuration failure

### ISSUE THREAD

**Issue by Anillc** [systemd/systemd#23197]
**systemd version the issue has been seen with**
 > 250.4
 > this doesn't appear in systemd 249.7

**Used distribution**
 > NixOS and Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux an 5.15.34 #1-NixOS SMP Wed Apr 13 18:59:28 UTC 2022 x86_64 GNU/Linux`
 > `Linux arch 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > configure successfully

**Unexpected behaviour you saw**
 > failed or always configuring

**Steps to reproduce the problem**

Adding IPv4 link local addresses (169.254) will cause `failed`
Adding IPv6 link local addresses (fe80::xx) will cause endless `configuring`

test.netdev
```
[NetDev]
Kind=wireguard
Name=test

[WireGuard]
ListenPort=2333
PrivateKey=<private key>
RouteTable=off

[WireGuardPeer]
AllowedIPs=0.0.0.0/0
AllowedIPs=::/0
PublicKey=<public key>
```

test.network
```
[Match]
Name=test

[Address]
Address=fe80::1/64

[Address]
Address=169.254.11.1/24
```

**Additional program output to the terminal or log subsystem illustrating the issue**

![image](https://user-images.githubusercontent.com/23411248/165327858-7dcdfefa-befb-4331-809d-1a357bad90b5.png)

**Comment by AiyionPrime** [comment]
Can confirm, this bug is a thing, though it took us a while to recognize it's systemd and not our config, that throws this...

Annoying, as 250.4 is shipped in debians Bullseye-Backports.

> this doesn't appear in systemd 249.7

so this is a regression bug?

If somebody needs a tester for a fix, let us know.

~ @freifunkh
