### ISSUE TITLE
systemd keeps standard file descriptors open of services with RemainAfterExit=yes

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#23193]
**systemd version the issue has been seen with**
 > main branch

**Used distribution**
 > /

**Linux kernel version used** (`uname -a`)

 > /

**CPU architecture issue was seen on**
 > /

**Expected behaviour you didn't see**
 > Standard file descriptors are released after the service configured with RemainAfterExit=yes enters the SERVICE_EXITED state

**Unexpected behaviour you saw**
 > Standard file descriptors stay open until the unit is garbage collected

**Steps to reproduce the problem**
 > Write a program that creates a pipe, starts a transient unit with RemainAfterExit=yes and configures one end of the pipe as the standardoutput file descriptor of the transient service using StandardOutputFileDescriptor. Then wait for EOF in that program on the pipe in the same program. EOF will only be generated once the transient service is stopped explicitly and not when the transient service command exits.

Relevant code is [here](https://github.com/systemd/systemd/blob/c84fc00b371cb30b1b0d4bfde015662e1a8542a7/src/core/unit.c#L411)

I can't immediately think of a use case where we would want to keep the service resources (standard file descriptors and fd store) intact after the service exits so to me it makes sense to extend the check I linked to include service units in the SERVICE_EXITED state.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
(i.e. background is: we want that services can be restarted and continue with the fds from the fdstore. It's how the fdstore came to be)

**Comment by DaanDeMeyer** [comment]
Hmm, that makes sense. I have some users internally that were expecting the standard file descriptors to be closed when the service exited. They were looking to use EOF on stdout as an indicator that the service exited but EOF never happens since systemd keeps the fds open.

I'm going to see if we can get rid of RemainAfterExit=yes in their units since that should also fix their problem.

**Comment by poettering** [comment]
I guess we can close this?
