### ISSUE TITLE
systemctl status --failed, please?

### ISSUE THREAD

**Issue by harridu** [systemd/systemd#23207]
To show more details about failed units and to avoid typing lengthy service names, something like 
```
systemctl status --failed
```
would be very nice. Currently (250.4) the "--failed" appears to be ignored (without usage hint).

Just a suggestion, of course.

**Comment by keszybz** [comment]
Sounds reasonable. The code is already there to filter units for `list-units --failed`, so it shouldn't be too much work.

**Comment by poettering** [comment]
what should this show other than "systemctl --failed"?

**Comment by harridu** [comment]
"systemctl --failed" hides the details. I noticed that I have to use "systemctl status failed.service" *every time* I have to examine a failed service. Why not show this immediately?

if services someweirdname1, anotherweirdname2 and yetanotherservice2fail failed, then "systemctl status --failed" should show the same as "systemctl status someweirdname1 anotherweirdname2 yetanotherservice2fail". 2 advantages:

- easier to type / no need for copy-and-paste
- lightweight way to get detailed information in **one** step

**Comment by poettering** [comment]
ah, got it. make sense.
