### ISSUE TITLE
Warn in syslog if root directory permissions are not mode 755 when switching root from initramfs.

### ISSUE THREAD

**Issue by oddlama** [systemd/systemd#23201]
**Is your feature request related to a problem? Please describe.**
I have recently setup some systems using an overlayfs on `/` in an initramfs (no systemd in the initramfs), but unfortunately forgot
to make the upper directory mode 755. This resulted in the system booting just fine, but all systemd services which should not run as root failed to load with a too broad error message. Specifically systemd-networkd, systemd-resolved, systemd-timesyncd, logind, and dbus were those I encountered.

**Describe the solution you'd like**
If `/` is not mode 755, it will always lead to certain systemd-native services to fail, as they are fortunately not running as root. Therefore, I would consider this an invalid configuration and suggest systemd to warn about this on boot, if detected:

> systemd[1]: warning: root filesystem should have permission mode 755.

... or some equivalent warning.

**Describe alternatives you've considered**
I believe a more detailed error message from the involved services would also have helped. Even with debug-level logging enabled for those services, you currently get only this message:

> systemd-networkd.service: Failed to connect stdout to the journal socket, ignoring: Permission denied

While this message is absolutely correct, additional information in the debug-loglevel about what user tried to access what file might have helped to find the issue more quickly. While a more detailed error message is always welcome, personally I believe that a dedicated message might be more appropriate in this specific case.

**The systemd version you checked that didn't have the feature you are asking for**
systemd v250

**Comment by g0tar** [comment]
I guess the minimal set is 511 (or maybe even 111) not 755.

**Comment by poettering** [comment]
hmm, well, but there are plenty inodes that need some specific access mode and are borked if they haven't. we couldn't possible warn about all of them. why make a special fuss around the root dir inode?

**Comment by oddlama** [comment]
The root node might be considered special because it can be easily misconfigured using wrong mounts, as shown. But of course it would also be appreciated if systemd would detect more than just wrong config on the root node. More specific error messages (in systemd-networkd for example) would also help and might avoid adding behavior to detect some specific misconfigurations.

Obviously, there is no technical reason to implement any of this. After all this is not a bug. I'd still consider it immensely useful.

**Comment by keszybz** [comment]
I don't think we want to do this. There's just sooooo many ways that installation can be messed up (bad access modes, files instead of character devices in `/dev` when somebody does `>/dev/null` before `/dev` has been populated, unexpected selinux contexts, …), and we can't hope to catch all of them. There are linter tools which are more appropriate for this type of checks.
