### ISSUE TITLE
systemd fails to compile with --fatal-meson-warnings

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23212]
Since https://github.com/systemd/systemd/pull/23204 was merged `systemd` has been failing to compile with `--fatal-meson-warnings`

```sh
meson --version
0.62.0

meson --fatal-meson-warnings build
...
src/boot/efi/meson.build:429: WARNING: Project targeting '>= 0.53.2' but tried to use feature introduced in '0.60.0': install_tag arg in custom_target.

src/boot/efi/meson.build:415:8: ERROR: Fatal warnings enabled, aborting
```

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/23204#issuecomment-1113696550
```python
if meson.version().version_compare('>=0.62.0')
    custom_target(..., install_tag: 'foo')
else
    custom_target(...)
endif
```
is the canonical way to avoid warnings.

**Comment by eli-schwartz** [comment]
What was the ultimate resolution of this?

**Comment by evverx** [comment]
systemd still fails to compile with `--fatal-meson-warnings` and it's totally fine by systemd standards. It will keep failing to build until certain distributions can switch to meson >= 0.60.

**Comment by evverx** [comment]
As far as I can see there was an attempt to bump meson a bit in https://github.com/systemd/systemd/pull/26728 but looks like it was opened without asking permission first.

**Comment by keszybz** [comment]
We're waiting for ~~the anchor to be lifted~~ Debian Bookworm to be released.

**Comment by evverx** [comment]
I understand that systemd follows that release cycle. But given that it seems that that half-baked rust integration is on its way with its warnings I don't think that bumping meson can help much with `--fatal-meson-warnings` generally.

**Comment by eli-schwartz** [comment]
I see. :/

(By the way, github now supports closing an issue as "not planned" to distinguish it from "completed".)

**Comment by evverx** [comment]
Apologies. I closed a bunch of issues that day so I might have missed the right button.

**Comment by evverx** [comment]
For the record https://github.com/systemd/systemd/pull/35946 broke it again.
