### ISSUE TITLE
Deploy initial time via timesyncd

### ISSUE THREAD

**Issue by darkdragon-001** [systemd/systemd#23210]
**systemd version the issue has been seen with**
> systemd 244 (244.5+)
> -PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
> Yocto Dunfell

**Linux kernel version used** (`uname -a`)

 > Linux HOSTNAME 5.4.142+g05557cd55b18 #1 SMP PREEMPT Sat Sep 11 22:36:03 UTC 2021 armv7l armv7l armv7l GNU/Linux

**CPU architecture issue was seen on**
 > armv7l

**Expected behaviour you didn't see**
 > Setting modification timestamp of `/var/lib/systemd/timesync/clock` to the deployment time should set the time on first boot to this time when `systemd-timesyncd` is enabled (see [docs](https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html#/var/lib/systemd/timesync/clock))

**Unexpected behaviour you saw**
 > After first boot this time is reset to some older value (maybe _systemd build date_?)

**Steps to reproduce the problem**
1. Create file `/var/lib/systemd/timesync/clock` with desired `mtime` on freshly built root file system
2. Enable `systemd-timesyncd.service`
3. Configure non-existing NTP server to make sure time is not overwritten by NTP
4. Copy root file system to device
5. Boot device
6. See that time is not set to the desired one

**Additional program output to the terminal or log subsystem illustrating the issue**

Tagging you as you created the feature in #20142:
@dimitry-ishenko @poettering

**Comment by darkdragon-001** [comment]
I was writing the wrong file. Works now.

Would still be interesting to know how the _systemd build date_ is determined...

**Comment by poettering** [comment]
> Would still be interesting to know how the _systemd build date_ is determined...

SOURCE_DATE_EPOCH env var at build (as per reproducible build specs)

if not set and is built from a git tree, uses timestamp of last tag

if not set and not built from a git tree, uses timestamp of `NEWS` file.

btw, the official way to do what you are doing is touch `/usr/lib/clock-epoch` at buildtime. that means this info is hermetic to OS data, in /usr/, and the timestamp in /var is strictly a runtime thing.

**Comment by darkdragon-001** [comment]
@poettering Thanks you so much for the explanation and fast reply!

I added this info to the docs in #23214 :wink:

**Comment by darkdragon-001** [comment]
@poettering Neither `/usr/lib/clock-epoch` nor `/lib/clock-epoch` seem to work on my system (see details in initial post). Has this feature been added recently?

**Comment by poettering** [comment]
/usr/lib/clock-epoch was added in v247
