### ISSUE TITLE
boot: loader.conf options are not taking effect

### ISSUE THREAD

**Issue by benthetechguy** [systemd/systemd#23222]
Here is my loader.conf for systemd-boot:
```
default linux-signed.efi
timeout 5
```
Neither of these options take effect on my HP Envy x360. The timeout and default boot entry don't change if I change them in loader.conf.
I can still manually set these things inside of systemd-boot and the changes persist, but nothing inside the loader.conf is working.

**Comment by medhefgo** [comment]
Please press P when inside of systemd-boot to see what settings it picks up and which version of sd-boot is running. Also make sure it actually lists an entry with that id.

**Comment by benthetechguy** [comment]
version 250.5-1-arch
settings in loader.conf not being picked up
entry with id `linux-signed.efi` is listed

**Comment by medhefgo** [comment]
Are you sure `loader/loader.conf` is on the correct ESP partition? The partition uuid is shown by systemd-boot and/or bootctl. Also, please make sure it's actually utf-8 encoded.

**Comment by benthetechguy** [comment]
Yes and yes.

**Comment by medhefgo** [comment]
Is this a regression by any chance?

Here is a [branch](https://github.com/medhefgo/systemd/tree/boot-log) that adds some log messages to hopefully sheds some light. Please give it a try.

**Comment by benthetechguy** [comment]
Discovered the issue.
Apparently, when I first set up systemd-boot on a different installation of Linux, I was having trouble with the config, so I manually set the default entry and timeout from inside systemd-boot, and those EFI variables take priority over the config values. I cleared out the efivars and everything is working now. There is nothing wrong with systemd-boot; sorry for the hassle.

**Comment by medhefgo** [comment]
You previously said that the settings in loader.conf were not being picked up, but after clearing out the EFI vars, they took effect.  That must mean it should have listed a `default: ...` and a `default (EFI var): ...`, right? Or I am very confused. Would it help if the loader.conf one would have a `(config)` attached to it to make it clearer?

**Comment by benthetechguy** [comment]
Yes. The config values were indeed being picked up and listed, and this was a case of user error. It would certainly help if `(config)` was appended.
