### ISSUE TITLE
Resolved falls back to 127.0.0.1 if single-label domain cant  be resolved via DNS

### ISSUE THREAD

**Issue by zdm** [systemd/systemd#23232]
**systemd version the issue has been seen with**
 > systemd 249 (249.11-0ubuntu3)

**Used distribution**
 > ubuntu 22.04

**Linux kernel version used** (`uname -a`)

 > `5.15.0-27-generic`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > I need to resolve single-label domains via external DNS service. I added `ResolveUnicastSingleLabel=yes` to the `/etc/systemd/resolved,conf`. It works as expected when domain is resolved on DNS service, but if domain is not resolved - it falls back to the `127.0.0.1`.
I am expecting, that if domain name can not be resolved - resolved should return `not found` instead of `127.0.0.1`.

**Unexpected behaviour you saw**
 > See above.

**Steps to reproduce the problem**
 > You need to configure and use external DNS service, that will resolve single-label domain names. Then try to resolve single label names from linux using this service.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by zdm** [comment]
My English is not perfect, so I will try to describe gain the problem:
When option `ResolveUnicastSingleLabel` is turned on I am expecting that single-label domains will be resolved using DNS and if domain is not resolvable it will return no data.
But currently if domain is not resolved via DNS - `resolved` fallbacks it to the localhost.
I don't know is this the error of this by design.
In my opinion if user enabled `ResolveUnicastSingleLabel` - he obviously wants to resolve via DNS only. Otherwise this has no sense, anny random string can be resolved as valid domain name.

**Comment by zdm** [comment]
Use case:
I have several servers that I want to connect via ssh using single-labels names.
I have local intranet dns service that can resolve single-label names.
When I connect to the valid single-label domain name - it resolved and ssh connected to the correct server.
But if single-label name is unknown by dns service - ssh connected to the localhost, that is completely not what we need.

**Comment by poettering** [comment]
Hmm? you are saying *any* single label name gets resolved to the address 127.0.0.1 for you? that's weird. (or are you saying that resolved will talk to DNS server 127.0.0.1 for that?) what makes you think resolved is responsible?

please provide a debug trace of this, i.e. issue "systemctl service-log-level systemd-resolved debug", then reproduce the issue, and then paste the log output this generated somewhere

**Comment by zdm** [comment]
Example, lets take two single-label domains:
- `viche-development` - registered on DNS service;
- `unknown` - not registered on DNS service;
pings:
```
[root@devel~]# ping viche-development
PING viche-development.localhost (34.118.11.110) 56(84) bytes of data.
64 bytes from viche-development.localhost (34.118.11.110): icmp_seq=1 ttl=128 time=19.3 ms
^C

[root@devel~]# ping unknown
PING unknown.localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.209 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.047 ms
^C
```

You can see, that for `unknown` domain it try to resolve it via DNS service (this is confirmed by DNS service logs), DNS returns nothing, then it falls back to `localhost`.

**Comment by poettering** [comment]
you cannot use the `.localhost` domain. Everything in that domain is resolved to 127.0.0.1.

**Comment by zdm** [comment]
I am not using `.localhost`.
I just use single-label name.
`resolved` automatically falls back to the localhost if domain is not resolved via dns.

**Comment by zdm** [comment]
I am expected, that when `ResolveUnicastSingleLabel` is turned on - it should resolve using dns only, without fallback to localhost.

**Comment by poettering** [comment]
it appears you set your host's earch domain to "localhost". Stop doing that.

i.e. what does "resolvectl status" say? What does /etc/resolv.conf and /etc/systemd/resolved.conf actually say?

I am pretty sure one of these lists "localhost" as search domain. And it really shouldn#t do that...

**Comment by zdm** [comment]
no, `localhost` is not set as search domain anywhere.

```
[root@devel~]# cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search .



[root@devel~]# cat /etc/systemd/resolved.conf
#DNS=
#FallbackDNS=
#Domains=
#DNSSEC=no
#DNSOverTLS=no
#MulticastDNS=no
#LLMNR=yes
#Cache=no # no-negative
#CacheFromLocalhost=no
#DNSStubListener=yes
#DNSStubListenerExtra=
#ReadEtcHosts=yes

ResolveUnicastSingleLabel=yes


[root@devel~]# resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens32)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.175.1
       DNS Servers: 192.168.175.1

Link 3 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (docker_gwbridge)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 13 (vethe458890)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 19 (veth21771a0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 27 (vethf410be7)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 29 (veth962f4d4)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 31 (veth8533e62)
Current Scopes: none

```

**Comment by zdm** [comment]
All this settings are default or ubuntu 20.04.
I only set `ResolveUnicastSingleLabel` to `yes`.
If I correctly understand `resolved` automatically falls back to localhost for single-label domains by default.

**Comment by poettering** [comment]
please provide the requested debug trace.

are you sure it's not your DNS server that suffixes single label names like that?

**Comment by zdm** [comment]
fod DNS server - yes, I am sure, here is the log:
```
unknown A resolved Locally to unknown.localhost
unknown AAAA, DNS Query Type not supported
unknown A resolved Locally to unknown.localhost
unknown AAAA, DNS Query Type not supported
```

You can see, that DNS server receive request with `.localhost` suffix already added by the `resolved`.

**Comment by poettering** [comment]
what is that an output from? "A" records resolve to addresses, not other names.

Anywy, please provide the debug log i asked for otherwise this is not actionable.

**Comment by zdm** [comment]
What command I should run to provide debug?

**Comment by zdm** [comment]
If DNS resolved A record to address - everything is ok, this address will be used.

**Comment by zdm** [comment]
Also, if I make `ping unknown` from windows using this DNS service - it works as it should.
DNS returns nothing and windows didn't added `.localhost` suffix.

**Comment by zdm** [comment]
This is definitely broken logic in `resolved`. It shouldn't use `.localhost` if user enabled `ResolveUnicastSingleLabel`.

**Comment by poettering** [comment]
> please provide a debug trace of this, i.e. issue "systemctl service-log-level systemd-resolved debug", then reproduce the issue, and then paste the log output this generated somewhere

unless you provide what is requested here we'll never know what triggers this issue.

**Comment by zdm** [comment]
Please, tell me, what commands I should run?
I executed `systemctl service-log-level systemd-resolved debug`. Whats next? Where I can see log?

**Comment by poettering** [comment]
```
journalctl -u systemd-resolved -f
```

for example.

Then reproduce the issue, i.e. issue a "getent hosts zzzzz" for example, from another window

**Comment by zdm** [comment]
this is the log for `ping unknown`:

```
May 03 11:44:21 devel systemd-resolved[784]: Received dns UDP packet of size 36, ifindex=0, ttl=64, fragsize=0
May 03 11:44:21 devel systemd-resolved[784]: Got DNS stub UDP query packet for id 24412
May 03 11:44:21 devel systemd-resolved[784]: Looking up RR for unknown IN A.
May 03 11:44:21 devel systemd-resolved[784]: Removing cache entry for mirror.volia.net IN A (expired 415s ago)
May 03 11:44:21 devel systemd-resolved[784]: Removing cache entry for objects.githubusercontent.com IN A (expired 358s ago)
May 03 11:44:21 devel systemd-resolved[784]: Removing cache entry for archive.ubuntu.volia.net IN CNAME (expired 252s ago)
May 03 11:44:21 devel systemd-resolved[784]: Positive cache hit for unknown IN A
May 03 11:44:21 devel systemd-resolved[784]: Regular transaction 1981 for <unknown IN A> on scope dns on ens32/* now complete with <success> from cache (unsigned; non-confidential).
May 03 11:44:21 devel systemd-resolved[784]: Freeing transaction 1981.
May 03 11:44:21 devel systemd-resolved[784]: Following CNAME/DNAME unknown → unknown.localhost.
May 03 11:44:21 devel systemd-resolved[784]: Sending response packet with id 24412 on interface 1/AF_INET of size 121.
May 03 11:44:21 devel systemd-resolved[784]: Processing query...
May 03 11:44:21 devel systemd-resolved[784]: Received dns UDP packet of size 36, ifindex=0, ttl=64, fragsize=0
May 03 11:44:21 devel systemd-resolved[784]: Got DNS stub UDP query packet for id 17034
May 03 11:44:21 devel systemd-resolved[784]: Looking up RR for unknown IN AAAA.
May 03 11:44:21 devel systemd-resolved[784]: Positive cache hit for unknown IN AAAA
May 03 11:44:21 devel systemd-resolved[784]: Regular transaction 3723 for <unknown IN AAAA> on scope dns on ens32/* now complete with <success> from cache (unsigned; non-confidential).
May 03 11:44:21 devel systemd-resolved[784]: Freeing transaction 3723.
May 03 11:44:21 devel systemd-resolved[784]: Following CNAME/DNAME unknown → unknown.localhost.
May 03 11:44:21 devel systemd-resolved[784]: Sending response packet with id 17034 on interface 1/AF_INET of size 133.
May 03 11:44:21 devel systemd-resolved[784]: Processing query...
^C

```

**Comment by poettering** [comment]
Maybe do this with a name you haven#t cached yet, so that the answer is answered by the DNS server, not the resolved cached.

That said, the log output shows that a CNAME redirect unknown → unknown.localhost was cached, which meas your server is causing this. Figure out why your server answers like that.

**Comment by zdm** [comment]
This is log just after reboot, cache is empty.

```
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 36, ifindex=0, ttl=64, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Got DNS stub UDP query packet for id 892
May 03 13:25:56 devel systemd-resolved[741]: Looking up RR for unknown IN A.
May 03 13:25:56 devel systemd-resolved[741]: Removing cache entry for 0.ubuntu.pool.ntp.org IN A (expired 17s ago)
May 03 13:25:56 devel systemd-resolved[741]: Removing cache entry for 1.ubuntu.pool.ntp.org IN A (expired 10s ago)
May 03 13:25:56 devel systemd-resolved[741]: Removing cache entry for api.snapcraft.io IN A (expired 0s ago)
May 03 13:25:56 devel systemd-resolved[741]: Cache miss for unknown IN A
May 03 13:25:56 devel systemd-resolved[741]: Firing regular transaction 27341 for <unknown IN A> scope dns on ens32/* (validate=yes).
May 03 13:25:56 devel systemd-resolved[741]: Using feature level UDP+EDNS0 for transaction 27341.
May 03 13:25:56 devel systemd-resolved[741]: Using DNS server 192.168.175.1 for transaction 27341.
May 03 13:25:56 devel systemd-resolved[741]: Announcing packet size 1472 in egress EDNS(0) packet.
May 03 13:25:56 devel systemd-resolved[741]: Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
May 03 13:25:56 devel systemd-resolved[741]: Sending query packet with id 27341 of size 36.
May 03 13:25:56 devel systemd-resolved[741]: Processing query...
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 36, ifindex=0, ttl=64, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Got DNS stub UDP query packet for id 90
May 03 13:25:56 devel systemd-resolved[741]: Looking up RR for unknown IN AAAA.
May 03 13:25:56 devel systemd-resolved[741]: Cache miss for unknown IN AAAA
May 03 13:25:56 devel systemd-resolved[741]: Firing regular transaction 48108 for <unknown IN AAAA> scope dns on ens32/* (validate=yes).
May 03 13:25:56 devel systemd-resolved[741]: Using feature level UDP+EDNS0 for transaction 48108.
May 03 13:25:56 devel systemd-resolved[741]: Using DNS server 192.168.175.1 for transaction 48108.
May 03 13:25:56 devel systemd-resolved[741]: Announcing packet size 1472 in egress EDNS(0) packet.
May 03 13:25:56 devel systemd-resolved[741]: Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
May 03 13:25:56 devel systemd-resolved[741]: Sending query packet with id 48108 of size 36.
May 03 13:25:56 devel systemd-resolved[741]: Processing query...
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 136, ifindex=2, ttl=0, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Processing incoming packet of size 136 on transaction 27341 (rcode=SUCCESS).
May 03 13:25:56 devel systemd-resolved[741]: Server doesn't support EDNS(0) properly, downgrading feature level...
May 03 13:25:56 devel systemd-resolved[741]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 192.168.175.1.
May 03 13:25:56 devel systemd-resolved[741]: Server feature level is now lower than when we began our transaction. Restarting with new ID.
May 03 13:25:56 devel systemd-resolved[741]: Transaction 27341 is now 43194.
May 03 13:25:56 devel systemd-resolved[741]: Cache miss for unknown IN A
May 03 13:25:56 devel systemd-resolved[741]: Firing regular transaction 43194 for <unknown IN A> scope dns on ens32/* (validate=yes).
May 03 13:25:56 devel systemd-resolved[741]: Using feature level UDP for transaction 43194.
May 03 13:25:56 devel systemd-resolved[741]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
May 03 13:25:56 devel systemd-resolved[741]: Sending query packet with id 43194 of size 25.
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 98, ifindex=2, ttl=0, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Processing incoming packet of size 98 on transaction 48108 (rcode=NOTIMP).
May 03 13:25:56 devel systemd-resolved[741]: Server returned error NOTIMP, retrying transaction with reduced feature level UDP.
May 03 13:25:56 devel systemd-resolved[741]: Retrying transaction 48108.
May 03 13:25:56 devel systemd-resolved[741]: Cache miss for unknown IN AAAA
May 03 13:25:56 devel systemd-resolved[741]: Firing regular transaction 48108 for <unknown IN AAAA> scope dns on ens32/* (validate=yes).
May 03 13:25:56 devel systemd-resolved[741]: Using feature level UDP for transaction 48108.
May 03 13:25:56 devel systemd-resolved[741]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
May 03 13:25:56 devel systemd-resolved[741]: Sending query packet with id 48108 of size 25.
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 136, ifindex=2, ttl=0, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Processing incoming packet of size 136 on transaction 43194 (rcode=SUCCESS).
May 03 13:25:56 devel systemd-resolved[741]: Added positive unauthenticated non-confidential cache entry for unknown IN CNAME 7200s on ens32/INET/192.168.175.1
May 03 13:25:56 devel systemd-resolved[741]: Regular transaction 43194 for <unknown IN A> on scope dns on ens32/* now complete with <success> from network (unsigned; non-confidential).
May 03 13:25:56 devel systemd-resolved[741]: Following CNAME/DNAME unknown → unknown.localhost.
May 03 13:25:56 devel systemd-resolved[741]: Sending response packet with id 892 on interface 1/AF_INET of size 121.
May 03 13:25:56 devel systemd-resolved[741]: Freeing transaction 43194.
May 03 13:25:56 devel systemd-resolved[741]: Received dns UDP packet of size 98, ifindex=2, ttl=0, fragsize=0
May 03 13:25:56 devel systemd-resolved[741]: Processing incoming packet of size 98 on transaction 48108 (rcode=NOTIMP).
May 03 13:25:56 devel systemd-resolved[741]: Server returned error: NOTIMP
May 03 13:25:56 devel systemd-resolved[741]: Regular transaction 48108 for <unknown IN AAAA> on scope dns on ens32/* now complete with <rcode-failure> from network (unsigned; non-confidential).
May 03 13:25:56 devel systemd-resolved[741]: Sending response packet with id 90 on interface 1/AF_INET of size 83.
May 03 13:25:56 devel systemd-resolved[741]: Freeing transaction 48108.
^C

```

**Comment by poettering** [comment]
```
May 03 13:25:56 devel systemd-resolved[741]: Added positive unauthenticated non-confidential cache entry for unknown IN CNAME 7200s on ens32/INET/192.168.175.1
May 03 13:25:56 devel systemd-resolved[741]: Regular transaction 43194 for <unknown IN A> on scope dns on ens32/* now complete with <success> from network (unsigned; non-confidential).
May 03 13:25:56 devel systemd-resolved[741]: Following CNAME/DNAME unknown → unknown.localhost.
```

There you go: your DNS server 192.168.175.1 returned a CNAME redirect from `unknown` to `unknown.localhost` when we asked for the `A` RR. Interestingly that followup lookup then fails with a NOTIMP error from the server. This then activates the fallback logic in resolved, which maps anything in the `localhost` domain to 127.0.0.1.

Anyway, this appears to be caused by your DNS server, we are pretty much just the messengers here of what it tells us.

**Comment by zdm** [comment]
It uses local dns service at 127.0.0.53 that forwards requests to the intranet dns at 192.168.175.1.
Server at 127.0.0.53 returns cname record:
```
dig @127.0.0.53 unknown

;; ANSWER SECTION:
unknown.                6849    IN      CNAME   unknown.localhost.
unknown.localhost.      0       IN      A       127.0.0.1
```

What is this service? Standard service for linux?
I have docker installed. Possible, that this is docker dns.

**Comment by poettering** [comment]
hmm? it's your DNS server *192.168.175.1* that returns the CNAME. 127.0.0.53 ist just the local DNS stub implemented by resolved that more or less proxies requests to the upstream DNS server.

Fix your DNS server not to synthesize CNAME records like this...

**Comment by poettering** [comment]
> ;; ANSWER SECTION:
> unknown.                36000   IN      CNAME   unknown.localhost.

There you go. Your dig output shows the CNAME being returned by 192.168.175.1. Fix that and the issue will be gone.

**Comment by zdm** [comment]
ahh, yes, seems, that it returns cname.
