### ISSUE TITLE
Mention in README kernel required for ambient capabilities

### ISSUE THREAD

**Issue by marcosfrm** [systemd/systemd#23231]
https://github.com/systemd/systemd/blob/b528a62863961658165091985b565cf7be48ea98/README#L32-L43

≥ 4.3 for ambient capabilities

**Comment by bluca** [comment]
Can you please send a PR?

**Comment by g0tar** [comment]
Actually this is just another issue for #23198. While elaborative and complete `README` is a nice thing to have, maintaining this file and maintaining systems by using this file by hand is error prone and indirect.

**Comment by poettering** [comment]
As discussed elsewhere we should raise the baseline to 4.3, and make ambient caps mandatory.

**Comment by bluca** [comment]
> As discussed elsewhere we should raise the baseline to 4.3, and make ambient caps mandatory.

We should still document it, as it's good information to write down
