### ISSUE TITLE
networkd: vlan interfaces won't get created when the parent interface is removed and connected

### ISSUE THREAD

**Issue by OH6BPL** [systemd/systemd#23256]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-7)

**Used distribution**
 > Debian GNU/Linux 11 (bullseye)

**Linux kernel version used** (`uname -a`)

 > `4.19.0-0.bpo.18-amd64`

**CPU architecture issue was seen on**
 > x86_64 and arm

**Expected behaviour you didn't see**
 > VLAN interfaces being created when parent interface becomes available

**Unexpected behaviour you saw**
 > VLAN interface did not appear when the parent interface was reconnected

**Steps to reproduce the problem**
 > Create a VLAN on some removable interface, USB interface, TAP, etc. Remove the interface and reconnect.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text

---REMOVE THE INTERFACE---
May 03 19:03:05 testrouter systemd-networkd[29532]: VPN-TRUNK: Link DOWN
May 03 19:03:05 testrouter systemd-networkd[29532]: VPN-TRUNK: Lost carrier
May 03 19:03:05 testrouter systemd-networkd[29532]: vlan3-vpn: Link DOWN
May 03 19:03:05 testrouter systemd-networkd[29532]: vlan3-vpn: Lost carrier
May 03 19:03:05 testrouter systemd-networkd[29532]: vlan2-vpn: Link DOWN
May 03 19:03:05 testrouter systemd-networkd[29532]: vlan2-vpn: Lost carrier

---RECONNECT THE INTERFACE---
May 03 19:03:20 testrouter systemd-networkd[29532]: VPN-TRUNK: Link UP
May 03 19:03:20 testrouter systemd-networkd[29532]: VPN-TRUNK: Gained carrier

```

**Comment by OH6BPL** [comment]
By restarting systemd-networkd VLAN interfaces are being created again.

**Comment by yuwata** [comment]
Sorry, v247 is slightly old here. Please try to reproduce the issue with the current git HEAD, or newer release (v249 or v250).
I changed the internal logic of assigning vlan or other netdevs on an interface after v250 was released. So, testing on the current git HEAD is much appreciated.
