### ISSUE TITLE
RFE: To extend 'systemctl list-unit-files' with options --system, --user and --runtime

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#2327]
Hope, the topicstarter in `[systemd-devel] known but not-listed units` theme filed his RFE about displaying runtime unit-files by `systemctl list-unit-files` command.

Wanna to offer the method of separated displaying, sorted by additional subkeys (`--system`, `--user`, `--runtime`).

Nowadays we have list on `systemctl list-unit-files` command:

```
UNIT FILE                  STATE
serviceA.service           static
serviceB.service           enabled
mountpoint.mount           masked
```

By default `systemctl list-unit-files` should display all unit-files, including runtime generated ones.

`systemctl list-unit-files --system`: to display unit-files from `/usr/lib/systemd/system` dir.

`systemctl list-unit-files --user`: to display unit-files from `/etc/systemd/system` dir.

`systemctl list-unit-files --runtime`:  to display unit-files from `/run/systemd/` dir.

Hence to extend `systemctl list-unit-files` list in this way:

```
UNIT FILE                   STATE                STATUS
serviceA.service           static                system
serviceB.service           enabled               runtime
mountpoint.mount           masked                user
```

**Comment by MikhailKasimov** [comment]
Another variant of keynaming: --systemspace (/usr/lib/systemd/system), --userspace (/etc/systemd/system) and --runtimespace (/run/systemd).

**Comment by miaofengwei** [comment]
what about naming:--usr,--etc,--run

**Comment by MikhailKasimov** [comment]
I think any variations, that will not be confusing to already existed keynames, are acceptable. Simply names --system, --user, --runtime were the first keynames, that came onto mind.

**Comment by johannbg** [comment]
Arguably "Status" should be called "Type" instead but how do you intend to differentiate an type unit service that is started by a user or as an user? Will its "Status" be system,runtime or user?

**Comment by MikhailKasimov** [comment]
`-t --type=TYPE List only units of a paticular type` . That's why I defined STATUS colomn instead of TYPE, because TYPE is .service, .mount, .target so on and I'd like to avoid confusing.

`Will its "Status" be system,runtime or user?` Hmm, originally I wanted to differentiate by unit start-path only.

**Comment by miaofengwei** [comment]
what about naming:--from-usr,--from-etc,--from-run
"Status" should be called "From"?

**Comment by MikhailKasimov** [comment]
`what about naming:--from-usr,--from-etc,--from-run
"Status" should be called "From"?`

O! The most plain variant indeed.

**Comment by poettering** [comment]
I doubt this is really desirable, due to overriding logic: a unit file can exist anywhere, but only the on in /etc or /run matters. And if you want to see the difference between vendor and local config, then better use "systemd-delta".... Also note that whether a file is in /run or not is already indicated via the state that is suffixed with "-runtime". See the systemctl man page, the part about "is-enabled".

Anyway, I'd really like to take a step back on this: what information are you looking for, that you currently cannot see better from the reported unit file state or systemd-delta?

**Comment by MikhailKasimov** [comment]
You see, originally we have two ways of units-list displaying:
1. To run `systemctl` without keys, then we get all units-list (from /etc/, /usr/lib/ and /run) and we can grep with any parameter -- e.g. `systemctl | grep .mount`.
2. Or, due to, for example, `k_mikhail@linux-mk500:~> man systemctl | grep list-unit-files`
`To list all units installed on the system, use the list-unit-files command instead.`
`list-unit-files [PATTERN...]`, we get the unit-list with state of each installed unit without runtime-units.

But here is the question how to understand runtime-units, which are generated by parsing different conf-files (e.g. the famous `/etc/fstab`) and, in fact, they are also installed on system. For example, runtime-unit `-.mount` is coming from mount-point `/` from `/etc/fstab`, and while this mount-point is present and active, we can count, that `-.mount` is installed on system. But we don't display it when `systemctl list-unit-files` is given. So, the idea is to a) display runtime-units and b) to have a possibility to sort `systemctl list-unit-files` list by three categories: `--from-usr,--from-etc,--from-run`.

And yes, `"Status" should be called "From"`.

Hope, I've described my thoughts clearly. :)

**Comment by dtardon** [comment]
> a) display runtime-units and 

`systemctl list-unit-files` shows generated and transient units these days.

> b) to have a possibility to sort `systemctl list-unit-files` list by three categories: `--from-usr,--from-etc,--from-run`.

You still haven't shown any use case for which this would be useful.
