### ISSUE TITLE
ProtectProc doesn't seem to be working

### ISSUE THREAD

**Issue by JetXujing** [systemd/systemd#23270]
**systemd version the issue has been seen with**
 > systemd-250

**Expected behaviour you didn't see**
 > `cat /proc/<pid>/cmdline` can't shows the command

**Unexpected behaviour you saw**
 > `cat /proc/<pid>/cmdline` shows the command

**Steps to reproduce the problem**
 > `systemctl cat test.service`

> [Unit]
> Description=test
> [Service]
> User=xujing
> ProtectProc=invisible
> ExecStart=sleep 1200

 > Run the following command as the **root** user: `systemctl start test`
 > `grep ^proc /proc/<pid>/mounts`
proc /proc proc rw,nosuid,nodev,noexec,relatime,hidepid=invisible 0 0
 >  Run the following command as the **jet** user: `cat /proc/<pid>/cmdline`
sleep1200

Is the verification method incorrect or a bug?

**Comment by bluca** [comment]
ProtectProc works on the _service_ itself, not on external processes

**Comment by JetXujing** [comment]
> not on external processes

**Comment by JetXujing** [comment]
> ProtectProc works on the _service_ itself, not on external processes

The pid is get from `systemctl status test`, such as 334731,
> [root@localhost system]# systemctl status test
> ● test.service - test
>      Loaded: loaded (/usr/lib/systemd/system/test.service; static)
>      Active: active (running) since Thu 2022-05-05 19:37:23 CST; 5s ago
>    Main PID: 334731 (sleep)
>       Tasks: 1 (limit: 21528)
>      Memory: 112.0K
>      CGroup: /system.slice/test.service
>              └─334731 sleep 1200

In fact, I don't quite understand how it works on a service.

**Comment by bluca** [comment]
The processes in the service have a restricted view of /proc. Processes outside the service, like your terminal, are unaffected.

**Comment by JetXujing** [comment]
fine, thanks!
