### ISSUE TITLE
`edit` does not create leading directories.

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#23271]
**systemd version the issue has been seen with**
 
```
> systemctl --version
systemd 250 (250.5-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

ArchLinux

**Linux kernel version used** (`uname -a`)
```
Linux victory 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux/
```

**Steps to reproduce the problem**
 
```
> systemctl --user edit librespot.service
Failed to create directories for "/home/hugo/.config/systemd/user/librespot.service.d/override.conf": Not a directory
```

**Expected behaviour you didn't see**

Should create the directory and let me edit the override.

**Unexpected behaviour you saw**
 
I need to manually create the directory.

**Comment by bluca** [comment]
I cannot reproduce this:

```
$ systemctl --version
systemd 250 (250.4-1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ find ~/.config/systemd
find: ‘/home/luca/.config/systemd’: No such file or directory
$ systemctl --user edit gpg-agent.service
$ find ~/.config/systemd
/home/luca/.config/systemd
/home/luca/.config/systemd/user
/home/luca/.config/systemd/user/gpg-agent.service.d
/home/luca/.config/systemd/user/gpg-agent.service.d/override.conf
```

It says "not a directory":

```
> systemctl --user edit librespot.service
Failed to create directories for "/home/hugo/.config/systemd/user/librespot.service.d/override.conf": Not a directory
```

Are you sure there isn't already a file with the same name?

**Comment by poettering** [comment]
> Failed to create directories for "/home/hugo/.config/systemd/user/librespot.service.d/override.conf": Not a directory

This error suggests that some leading dir in the full path here already exists and is not a dir...

i.e. you already have some conflicting file in place somewhere (or symlink?), and thus we cannot create the dir, even though we try.

**Comment by WhyNotHugo** [comment]
`.config/systemd` is a symlink to a directory in my dotfiles repository, yes. However, it is a link to a directory; the tree can be traversed fine.

**Comment by stepnem** [comment]
I see a similar issue:

```
% systemctl status pkgfile-update
× pkgfile-update.service - pkgfile database update
     Loaded: loaded (/usr/lib/systemd/system/pkgfile-update.service; static)
[...]

% systemctl edit pkgfile-update
Failed to create directories for "/etc/systemd/system/pkgfile-update.service.d/override.conf": No such file or directory

% uname -a
Linux tipi 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

% systemctl --version
systemd 251 (251.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

% ls -l /etc/systemd/system
total 20K
drwxr-xr-x 2 root root 4.0K Jan  8  2022 getty.target.wants/
drwxr-xr-x 2 root root 4.0K Jul 25 23:24 multi-user.target.wants/
drwxr-xr-x 2 root root 4.0K Jan  8  2022 network-online.target.wants/
drwxr-xr-x 2 root root 4.0K Jul 11 23:12 sockets.target.wants/
drwxr-xr-x 2 root root 4.0K Jun  9 10:25 timers.target.wants/
lrwxrwxrwx 1 root root   57 Jan  8  2022 dbus-org.freedesktop.nm-dispatcher.service -> /usr/lib/systemd/system/NetworkManager-dispatcher.service

% ls -ld /etc/systemd/system
drwxr-xr-x 7 root root 4.0K Jul 25 23:22 /etc/systemd/system/

% ls -ld /etc/systemd
drwxr-xr-x 5 root root 4.0K Jul 26 10:34 /etc/systemd/
```

**Comment by stepnem** [comment]
I guess my issue is different in that the problem is one of permissions (with `sudo` the directory is created), which I assume was not the case for @WhyNotHugo.

Still, it looks like a bug to me in either case (at the very least I'd expect a better error message and/or the permissions gotcha being documented; ideally I should be asked for admin authentication and have the directory created for me, same as with other privileged `systemctl` operations without `sudo`).

**Comment by WhyNotHugo** [comment]
> I guess my issue is different in that the problem is one of permissions (with sudo the directory is created), 

Definitely a different issue, since I'm using `systemctl --user`, which is for user-services so sudo would definitely not make sense. In your case, you're editing system services, so you need to use `sudo` (or set up polkit).

**Comment by WhyNotHugo** [comment]
Any further feedback needed from my side? I believe this cause of the issue is `.config/systemd` being a symlink.

**Comment by yuwata** [comment]
I tried, but cannot reproduce the issue. Tested with v249.12 and the current git HEAD.
```shell
$ systemctl --version
systemd 249 (v249.12-5.fc35)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ systemd/build/systemctl --version
systemd 251 (251-1364-g645dedd+)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ ls -l .config/systemd
lrwxrwxrwx 1 watanabe watanabe 11 Aug 21 02:48 .config/systemd -> ../hogehoge
$ tree .config/systemd
.config/systemd
└── user
    ├── at-spi-dbus-bus.service.d
    │   └── override.conf
    └── pipewire.service.d
        └── override.conf

3 directories, 2 files
$ systemctl --user cat pipewire.service
# /usr/lib/systemd/user/pipewire.service
(snip)
# /home/watanabe/hogehoge/user/pipewire.service.d/override.conf
[Service]
#aaa
```

**Comment by yuwata** [comment]
Ah, this is already fixed by 5117059ee9f84ed2fd37801ec0b90473db475422.

**Comment by yuwata** [comment]
And the commit is already backported to v250.4 (https://github.com/systemd/systemd-stable/commit/df59c65a23fe3fb123fab4edf6114d64057bbe5c).

**Comment by SHAREN** [comment]
Hi! Sorry to comment on a closed issue. I’m seeing similar behavior on Ubuntu with systemd 255 (255.4-1ubuntu8.12).

When I run systemctl --user edit openclaw-node.service, it opens the editor, but the drop-in directory ~/.config/systemd/user/openclaw-node.service.d/ is not created, and override.conf is not saved unless I manually create the directory first (mkdir -p ...). As a result, running systemctl --user edit ... again opens the default template as if nothing was saved.

Minimal repro:

rm -rf ~/.config/systemd/user/openclaw-node.service.d

systemctl --user edit openclaw-node.service (add any content, Ctrl+O, Enter, Ctrl+X)

ls -la ~/.config/systemd/user/openclaw-node.service.d -> still missing
