### ISSUE TITLE
Unclear systemd-journald.socket destructive transaction error during shutdown

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#23287]
**systemd version the issue has been seen with**
 > 250.3

**Used distribution**
 > CentOS Stream 8

**Linux kernel version used** (`uname -a`)

 > `5.6`

**CPU architecture issue was seen on**
 > x86_64

**Steps to reproduce the problem**
 > Unsure

**Additional program output to the terminal or log subsystem illustrating the issue**

I'm looking into common journald error logs on our machines and one of the most common ones is the following:

```
systemd[1]: systemd-journald.socket: Failed to queue service startup job (Maybe the service file is missing or not a non-template unit?): Transaction for systemd-journald.service/start is destructive (shutdown.target has 'start' job queued, but 'stop' is inclu## in transaction).
```

It's a bit unclear to me what this exactly means. I suspect that something is accessing the journald socket during shutdown which tries to activate journald but this isn't allowed at that point in time? Maybe we can improve the logging message and maybe there's something we need to fix in the unit dependencies so that this can't happen (by stopping the journald socket if we know that activating journald is going to fail?)

**Comment by DaanDeMeyer** [comment]
Specifically, I don't quite get how systemd-journald.socket would cause a transaction to include shutdown.target since neither it nor systemd-journald.service seem to include shutdown.target.

**Comment by DaanDeMeyer** [comment]
> But we just stopped that, and since it conflicts with shutdown.target actually starting it again this late, would mean reversing shutdown.target/start to shutdown.target/stop, which we expressly don#t want to do.

This is what's confusing me. I'm probably just blind but I don't see how systemd-journald conflicts with shutdown.target from its service file.

> after all during shutdown we terminate the journald service before its socket

Why do we do this? If the socket can't do its job after journald is shut down, why destroy journald before it's socket?

**Comment by keszybz** [comment]
From discussion during videoconf: set `IgnoreOnIsolate=yes` on `systemd-journald.service`. It might help, though it's unclear if this is a fix for this issue.

**Comment by DaanDeMeyer** [comment]
Let's close this, we should try to expose better logging in the debug message but let's track that in a separate issue
