### ISSUE TITLE
boot: Allow installation to non-FAT partitions

### ISSUE THREAD

**Issue by benthetechguy** [systemd/systemd#23282]
**Is your feature request related to a problem? Please describe.**
When attempting to install systemd-boot onto a partition that's not vfat, I get the error `Not a FAT EFI System Partition (ESP) file system.` There are many situations in which an EFI system partition would be a different filesystem. Many modern machines are able to boot to NTFS ESPs, and Apple has had support for HFS+ in their UEFI since the beginning. Through a BIOS modification, my system supports ext4 and btrfs ESPs. The UEFI specification never mandates that FAT32 must be the filesystem used for EFI system partitions, but it became the de facto standard.

**Describe the solution you'd like**
I thought of two possible solutions:
1. If the specified ESP partition is not vfat, check the GPT partition type, and if it's `C12A7328-F81F-11D2-BA4B-00A0C93EC93B` (EFI System Partiton), then allow installation. If not, error out because it's not an EFI System Partition.
2. Add a flag that bypasses the filesystem check.

**Describe alternatives you've considered**
I am able to manually install to the partition by making all the necessary folders and copying `/usr/lib/systemd/boot/efi/systemd-bootx64.efi` to `$esp/EFI/systemd/systemd-bootx64.efi` and `$esp/EFI/boot/bootx64.efi`, but that's a lot of unnecessary work.

**The systemd version you checked that didn't have the feature you are asking for**
Yes

**Comment by smopucilowski** [comment]
> The UEFI specification never mandates that FAT32 must be the filesystem used for EFI system partitions

See [Page 498 of the UEFI spec.](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf)

**Comment by benthetechguy** [comment]
I didn't word that properly. What I meant to say was that it didn't say that ESPs were required to be FAT, simply saying that compliant EFI firmware is required to support FAT.

> Conformance to the EFI specification and its associate reference documents is the only definition of FAT that needs to be implemented to support EFI.
…
The EFI firmware must support the FAT32, FAT16, and FAT12 variants of the EFI file system. Which EFI filesystem to use is defined by the media.

In fact, they're also required to support ISO 9660.

> A DVD-ROM image shall be booted by UEFI if the DVD-ROM image contains exactly one ISO-9660 file system. Booting from a DVD-ROM that satisfies the above requirements is accomplished using the same methods as booting from a CD-ROM: the ISO-9660 file system shall be booted.

There are many applications for a non-FAT ESP out there and it's used in production more commonly than I previously knew. For example, when creating a bootable Windows 10 or 11 USB, Rufus creates two partitions: An NTFS one which is used as the EFI system partition to boot Windows, and a tiny FAT32 one only containing an NTFS driver for UEFI and a simple program that loads the driver and redirects the firmware to the other partition. This is required because the Windows ISO contains a file that is larger than 4 GB. This is not related to systemd-boot in any way, but it shows how common these situations are.

**Comment by benthetechguy** [comment]
I don't know C. If I did, this would be a pull request and not a feature
request.

**Comment by poettering** [comment]
This already exists: see https://systemd.io/ENVIRONMENT the part about bootctl.

**Comment by Valloric** [comment]
For other people coming in from search engines, this is the solution:

```bash
SYSTEMD_RELAX_ESP_CHECKS=1 bootctl install
```

> `$SYSTEMD_RELAX_ESP_CHECKS=1` — if set, the ESP validation checks are relaxed. Specifically, validation checks that ensure the specified ESP path is a FAT file system are turned off, as are checks that the path is located on a GPT partition with the correct type UUID.
