### ISSUE TITLE
ASUS C433 Chromebook accelerometer support

### ISSUE THREAD

**Issue by lucagoc** [systemd/systemd#23301]
ASUS C433 Chromebook (Rammus) accelerometer is reversed because of general Chromebooks configuration.

**Solution :**
Adding this hwdb rule in `60-sensor.hwdb`:
[61-sensor-local.txt](https://github.com/systemd/systemd/files/8645347/61-sensor-local.txt)

systemd version : 250.5-1-arch

**Comment by yuwata** [comment]
Could you submit the change as a PR?
