### ISSUE TITLE
systemd-resolved: stub resolver should only answer with on-link addresses for local queries

### ISSUE THREAD

**Issue by fghzxm** [systemd/systemd#23314]
**systemd version the issue has been seen with**
 > `250.3-8.fc36.x86_64`

**Used distribution**
 > `Fedora release 36 (Thirty Six)`

**Linux kernel version used** (`uname -a`)

 > `Linux host.example.net 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > `x86-64`

**Expected behaviour you didn't see**
 > Even if `host.example.net` is connected to both `10.1.0.1/16` and `10.2.0.1/16`,
   `dig @10.2.0.1 host.local A +short` should only return `10.2.0.1`,
   and not `10.1.0.1` which is off-link.

**Unexpected behaviour you saw**
 > I see both `10.1.0.1` and `10.2.0.1`.

**Steps to reproduce the problem**
 > 1. Set hostname to `host`.
 > 2. Create `br0: 10.1.0.1/16` and `br1: 10.2.0.1/16`.
 > 3. Enable mDNS on everything.
 > 4. `dig @10.2.0.1 host.local A +short`

**Comment by fghzxm** [comment]
This issue is more severe with IPv6, since it results in incorrect link-local addresses being returned.

**Comment by poettering** [comment]
I am sorry, I don't follow?

what does "host.example.net" play as role in your example?

your are issuing the dns request from the local host, i.e. they do not originate from any interface, but are shortcut into the local resolved socket by the kernel.

If you try to reproduce the issue from a peer on the relevant network, it should just work.
