### ISSUE TITLE
There is a memory-leak in bus_append_execute_property

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23317]
I ran the testsuite scripts under ASan one by one to collect valid dbus messages that can be passed to `dfuzzer` as a dictionary (https://github.com/matusmarhefka/dfuzzer/issues/81) and in the process ASan complained about `bus_append_execute_property`:
```sh
# systemd-run --wait -p RuntimeDirectoryPreserve=yes -p DynamicUser=0 -p StateDirectory=zzz touch /var/lib/zzz/test
Running as unit: run-u171.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 40ms
CPU time consumed: 21ms

=================================================================
==4989==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7ffb720f0c98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
    #1 0x7ffb70e57eae in greedy_realloc ../src/basic/alloc-util.c:70
    #2 0x7ffb70ea0ce5 in extract_first_word ../src/basic/extract-word.c:46
    #3 0x7ffb70ea308d in extract_many_words ../src/basic/extract-word.c:273
    #4 0x7ffb70aedbe1 in bus_append_execute_property ../src/shared/bus-unit-util.c:1951
    #5 0x7ffb70af689b in bus_append_unit_property_assignment ../src/shared/bus-unit-util.c:2543
    #6 0x7ffb70af6fad in bus_append_unit_property_assignment_many ../src/shared/bus-unit-util.c:2657
    #7 0x40921f in transient_unit_set_properties ../src/run/run.c:646
    #8 0x409d39 in transient_service_set_properties ../src/run/run.c:714
    #9 0x40fdb1 in start_transient_service ../src/run/run.c:1209
    #10 0x4193e2 in run ../src/run/run.c:1775
    #11 0x419599 in main ../src/run/run.c:1782
    #12 0x7ffb6f5aef1f in __libc_start_call_main (/lib64/libc.so.6+0x40f1f)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```
```
# systemd-mount -p RuntimeDirectory=hoge -p RuntimeDirectoryPreserve=yes -t tmpfs tmpfs /tmp/aaa
Failed to start transient mount unit: Unit tmp-aaa.mount already exists.

=================================================================
==5732==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f94b4ec6c98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
    #1 0x7f94b3c2deae in greedy_realloc ../src/basic/alloc-util.c:70
    #2 0x7f94b3c76ce5 in extract_first_word ../src/basic/extract-word.c:46
    #3 0x7f94b3c7908d in extract_many_words ../src/basic/extract-word.c:273
    #4 0x7f94b38c3be1 in bus_append_execute_property ../src/shared/bus-unit-util.c:1951
    #5 0x7f94b38ccb0d in bus_append_unit_property_assignment ../src/shared/bus-unit-util.c:2611
    #6 0x7f94b38ccfad in bus_append_unit_property_assignment_many ../src/shared/bus-unit-util.c:2657
    #7 0x40757d in transient_unit_set_properties ../src/mount/mount-tool.c:456
    #8 0x40770d in transient_mount_set_properties ../src/mount/mount-tool.c:469
    #9 0x408847 in start_transient_mount ../src/mount/mount-tool.c:578
    #10 0x4147bf in run ../src/mount/mount-tool.c:1528
    #11 0x4149d0 in main ../src/mount/mount-tool.c:1542
    #12 0x7f94b233ff1f in __libc_start_call_main (/lib64/libc.so.6+0x40f1f)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```

@mrc0mmand I thought the testsuite was run under ASan daily. I wonder if it was turned off?

**Comment by mrc0mmand** [comment]
> I ran the testsuite scripts under ASan one by one to collect valid dbus messages that can be passed to `dfuzzer` as a dictionary ([matusmarhefka/dfuzzer#81](https://github.com/matusmarhefka/dfuzzer/issues/81)) and in the process ASan complained about `bus_append_execute_property`:
> 
> ```shell
> # systemd-run --wait -p RuntimeDirectoryPreserve=yes -p DynamicUser=0 -p StateDirectory=zzz touch /var/lib/zzz/test
> Running as unit: run-u171.service
> Finished with result: success
> Main processes terminated with: code=exited/status=0
> Service runtime: 40ms
> CPU time consumed: 21ms
> 
> =================================================================
> ==4989==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 64 byte(s) in 1 object(s) allocated from:
>     #0 0x7ffb720f0c98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
>     #1 0x7ffb70e57eae in greedy_realloc ../src/basic/alloc-util.c:70
>     #2 0x7ffb70ea0ce5 in extract_first_word ../src/basic/extract-word.c:46
>     #3 0x7ffb70ea308d in extract_many_words ../src/basic/extract-word.c:273
>     #4 0x7ffb70aedbe1 in bus_append_execute_property ../src/shared/bus-unit-util.c:1951
>     #5 0x7ffb70af689b in bus_append_unit_property_assignment ../src/shared/bus-unit-util.c:2543
>     #6 0x7ffb70af6fad in bus_append_unit_property_assignment_many ../src/shared/bus-unit-util.c:2657
>     #7 0x40921f in transient_unit_set_properties ../src/run/run.c:646
>     #8 0x409d39 in transient_service_set_properties ../src/run/run.c:714
>     #9 0x40fdb1 in start_transient_service ../src/run/run.c:1209
>     #10 0x4193e2 in run ../src/run/run.c:1775
>     #11 0x419599 in main ../src/run/run.c:1782
>     #12 0x7ffb6f5aef1f in __libc_start_call_main (/lib64/libc.so.6+0x40f1f)
> 
> SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
> ```
> 
> ```
> # systemd-mount -p RuntimeDirectory=hoge -p RuntimeDirectoryPreserve=yes -t tmpfs tmpfs /tmp/aaa
> Failed to start transient mount unit: Unit tmp-aaa.mount already exists.
> 
> =================================================================
> ==5732==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 64 byte(s) in 1 object(s) allocated from:
>     #0 0x7f94b4ec6c98 in __interceptor_realloc (/lib64/libasan.so.6+0xaec98)
>     #1 0x7f94b3c2deae in greedy_realloc ../src/basic/alloc-util.c:70
>     #2 0x7f94b3c76ce5 in extract_first_word ../src/basic/extract-word.c:46
>     #3 0x7f94b3c7908d in extract_many_words ../src/basic/extract-word.c:273
>     #4 0x7f94b38c3be1 in bus_append_execute_property ../src/shared/bus-unit-util.c:1951
>     #5 0x7f94b38ccb0d in bus_append_unit_property_assignment ../src/shared/bus-unit-util.c:2611
>     #6 0x7f94b38ccfad in bus_append_unit_property_assignment_many ../src/shared/bus-unit-util.c:2657
>     #7 0x40757d in transient_unit_set_properties ../src/mount/mount-tool.c:456
>     #8 0x40770d in transient_mount_set_properties ../src/mount/mount-tool.c:469
>     #9 0x408847 in start_transient_mount ../src/mount/mount-tool.c:578
>     #10 0x4147bf in run ../src/mount/mount-tool.c:1528
>     #11 0x4149d0 in main ../src/mount/mount-tool.c:1542
>     #12 0x7f94b233ff1f in __libc_start_call_main (/lib64/libc.so.6+0x40f1f)
> 
> SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
> ```
> 
> @mrc0mmand I thought the testsuite was run under ASan daily. I wonder if it was turned off?

Interesting, the test suite is run under ASan/UBSan in each PR (with clang) and daily with gcc, so I wonder what's missing.

**Comment by evverx** [comment]
Looks like those commands are run in `test/units/testsuite-34.sh` and `test/units/testsuite-37.sh`. My guess would be that they could be skipped somewhere probably

**Comment by mrc0mmand** [comment]
> Looks like those commands are run in `test/units/testsuite-34.sh` and `test/units/testsuite-37.sh`. My guess would be that they could be skipped somewhere probably

Ah, I see, only a subset of the integration tests runs under sanitizers (performance reasons), so I guess it's time to extend the list a little.
