### ISSUE TITLE
allow compressed PE files in boot loader spec

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#23347]
Apparently some archs don't have kernels that self-decompress on invocation. Instead kernels are supposed to be decompressed by the boot loader.

The boot loader spec should probably explicitly allow that. i.e. allow that kernels (including PE files) are compressed with xz/zstd/gz/lz4 or suchlike, and need to be decompressed before they are executed.

**Comment by poettering** [comment]
@alexlarsson

**Comment by keszybz** [comment]
This should be trivial to add. Can someone who groks such arches provide a proposal text?

(We talk about suffix removal in various places. If we add this, those places probably will need to be adjusted.)

**Comment by alexlarsson** [comment]
Not sure how exactly this should be written, but the issue is that on aarch64 the kernel image on disk is actually a gzip compressed UEFI executable, not a self extracting UEFI executable, and it expects the firmware to do this uncompression before starting it.

**Comment by poettering** [comment]
See discussion in #23788.

would it be OK if this would be implemented in sd-stub (instead of sd-boot), i.e. require a unified kernel? That way, sd-stub would be uncompressed, and then be responsible for decompressing the embedded kernel, and invoke it? this has various benefits, see discussion there, but means, that the stub code would not be compressed, but that should be tiny...

**Comment by poettering** [comment]
So let's close this, the kernel learnt this natively, see discussion on https://github.com/systemd/systemd/issues/23788.
