### ISSUE TITLE
Systemd keeps restarting systemd-hostnamed.service

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#23356]
**systemd version the issue has been seen with**
 > …
systemctl --version
systemd 249 (249)
+PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC -KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -XKBCOMMON -UTMP +SYSVINIT default-hierarchy=hybrid

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`
'Linux  5.15.35-a75ce13 #1 SMP Wed May 11 20:53:23 UTC 2022 armv7l GNU/Linux'
**CPU architecture issue was seen on**
 > …
ARM
**Expected behaviour you didn't see**
 > …
I think systemd-hostnamed.service should not be restarted unless there is hostname change.

**Unexpected behaviour you saw**
 > …
don't see any trigger for systemd to restart this service systemd-hostnamed.service
**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
May 12 02:36:51  systemd[1]:Starting Hostname Service...
May 12 02:36:51  systemd[1]: Started Hostname Service.
May 12 02:37:21  systemd[1]: systemd-hostnamed.service: Deactivated successfully.

May 12 02:36:51 systemd[1]:Starting Hostname Service...
May 12 02:36:51  systemd[1]: Started Hostname Service.
May 12 02:37:21  systemd[1]: systemd-hostnamed.service: Deactivated successfully.
```

**Comment by raviteja-b** [comment]
I don't see any trigger from user programs to restart systemd-hostnamed.service.
but systemd keeps restarting this service after every few seconds.

**Comment by poettering** [comment]
it's a bus activated service that exits on idle. Almost certainly some client issued a dbus request to talk to it.

**Comment by raviteja-b** [comment]
yeah, its deactivated when its idle, but it restarts in few seconds and I don't see any related d-bus calls occurred

**Comment by boucman** [comment]
busctl monitor does not report any calls ?

**Comment by poettering** [comment]
This is not really an issue. It exits on idle, and gets restarted when requested next. If you want to know which command keeps triggering it, use busctl monitor.

Anyway, let's close this here.
