### ISSUE TITLE
Bashism in `/usr/lib/kernel/install.d/90-loaderentry.install`

### ISSUE THREAD

**Issue by thesamesam** [systemd/systemd#23374]
**systemd version the issue has been seen with**
 > 251-rc2

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `5.15.39-gentoo-dist-hardened`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > No errors when calling `installkernel` (indirectly here, through `eclean-kernel` in Gentoo).

**Unexpected behaviour you saw**
 > Error message during run: `/usr/lib/kernel/install.d/90-loaderentry.install: 21: shopt: not found`

**Steps to reproduce the problem**
 > Set `/bin/sh` to be provided by a POSIX-compliant shell like `dash` (definitely not `bash`)
> Try to run `eclean-kernel` in Gentoo (I suspect `installkernel` with appropriate args would work too, but the issue is obvious anyway)
> Get a Bashism error:
```
/usr/lib/kernel/install.d/90-loaderentry.install: 21: shopt: not found
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
# eclean-kernel -a
Preserving currently running kernel (5.15.39-gentoo-dist-hardened)
Legend:
[-] file being removed
[x] file does not exist (anymore)
[+] file being kept (used by other kernels)

* Removing kernel 5.15.38-gentoo-dist-hardened (not referenced by bootloader (symlinks))
/usr/lib/kernel/install.d/90-loaderentry.install: 21: shopt: not found
 [-] /boot/8c595ddc91b6b00a140266195f3f00ea/5.15.38-gentoo-dist-hardened/initrd
 [-] /lib/modules/5.15.38-gentoo-dist-hardened
 [-] /boot/8c595ddc91b6b00a140266195f3f00ea/5.15.38-gentoo-dist-hardened/linux
 [-] /boot/8c595ddc91b6b00a140266195f3f00ea/5.15.38-gentoo-dist-hardened
Removed 1 kernels
```

**Comment by thesamesam** [comment]
Introduced by 367165a4069ac0c04882a05a8a80f6afb1e42760 (cc @keszybz).

The gist is that it's okay to use Bashisms like `shopt`, but if we're going to, the shebang needs to be for Bash. In 662f45e3ea9f6e933234b81bec532d584bda6ead, @nabijaczleweli ported it to use `/bin/sh` and avoid Bashisms.

I don't really care which systemd uses as long as the shebang is correct for it. Cheers!

**Comment by mrc0mmand** [comment]
> FWIW, the `checkbashisms` script (or shellcheck?) could/should(?) be used in CI if more stuff is going to be ported to POSIX shell, as it found this at least:
> 
> ```
> $ checkbashisms /usr/lib/kernel/install.d/90-loaderentry.install
> possible bashism in /usr/lib/kernel/install.d/90-loaderentry.install line 21 (shopt):
> shopt -s nullglob
> ```
> 
> It's not easy for everybody to keep in mind what a Bashism is so it may be a good idea if going to keep porting stuff.

We do have shellcheck in CI, but the kernel-install stuff was excluded (since it was in a questionable state when I introduced shellcheck). I'll look into reenabling it for the kernel-install stuff as well.

**Comment by nabijaczleweli** [comment]
Does Fedora actually unironically run bash as /bin/sh in year of the pog 2020? Either way, please try #23377 :)

**Comment by bluca** [comment]
There is still some bashism in the kernel-install script:

```
$ checkbashisms src/kernel-install/kernel-install.in 
possible bashism in src/kernel-install/kernel-install.in line 294 (echo -e):
[ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && echo -e "Plugin files:\n$PLUGINS"
```

**Comment by nabijaczleweli** [comment]
That's a SysVism, technically, but what's more worrying is the lint job passed; thankfully, it left a useful log: https://github.com/systemd/systemd/runs/6525691640?check_suite_focus=true#step:4:75 (of what it removed from the image. no clue what it checks or how. quality!)

What's even more worrying is it doesn't actually seem to run shellcheck at all:
```
nabijaczleweli@tarta:~/store/code/systemd/src/kernel-install$ shellcheck ?0* kernel-install.in

In kernel-install.in line 115:
    . "$install_conf"
      ^-------------^ SC1090: Can't follow non-constant source. Use a directive to specify location.


In kernel-install.in line 133:
if [ -z "$MACHINE_ID" ] && [ -r /etc/machine-info ] && . /etc/machine-info && MACHINE_ID="$KERNEL_INSTALL_MACHINE_ID"; then
                                                         ^---------------^ SC1091: Not following: /etc/machine-info was not specified as input (see shellcheck -x).


In kernel-install.in line 160:
    [ -r /etc/os-release ] && . /etc/os-release
                                ^-------------^ SC1091: Not following: /etc/os-release was not specified as input (see shellcheck -x).


In kernel-install.in line 294:
[ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && echo -e "Plugin files:\n$PLUGINS"
                                            ^-- SC2039: In POSIX sh, echo flags are undefined.

For more information:
  https://www.shellcheck.net/wiki/SC1090 -- Can't follow non-constant source....
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, echo flags are undef...
  https://www.shellcheck.net/wiki/SC1091 -- Not following: /etc/machine-info ...
```

**Comment by nabijaczleweli** [comment]
Oh, great, it has two controlling variables for what we might want here:
```
VALIDATE_SHELL_SHFMT | true | Flag to enable or disable the linting process of Shell scripts. (Utilizing: shfmt)
VALIDATE_BASH | true | Flag to enable or disable the linting process of the Bash language.
```
...what the hell is "the Bash language", and how do you make it run shellcheck lmao. For something that purports to be a "super linter" it seems incredibly ass.
