### ISSUE TITLE
NEWS file contains text that is accidentally interpreted as Markdown styling

### ISSUE THREAD

**Issue by eriksjolund** [systemd/systemd#23371]
A very minor thing:

The release notes
https://github.com/systemd/systemd/releases/tag/v251-rc2
shows

_Capabilities_=

in italics.

Probably the Markdown styling is unintentional. The sources seem to be

```
*Capabilities*=
```
from
https://github.com/systemd/systemd/blob/main/NEWS#L272

**Comment by keszybz** [comment]
I see the issue, but I don't think we can reasonably fix this. The text in the tag is included for convenience, but the syntax is not markdown, it is just plain text copied from NEWS. We could adjust the text by hand, but I think that's too much work. Sorry ;)
