### ISSUE TITLE
Both laptop keyboard and usb keyboard don't work in systemd-boot

### ISSUE THREAD

**Issue by Zodigram** [systemd/systemd#23379]
**systemd version the issue has been seen with**
 > 250.5-1

**Used distribution**
 > Arch Linux

**Linux kernel version used** 
 > `5.17.7-arch1-1 #1 SMP PREEMPT Thu, 12 May 2022 18:55:54 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Ability to control systemd-boot with keypresses

**Unexpected behaviour you saw**
 > The first keypress removes the timer, but then no other keypresses do anything

**Steps to reproduce the problem**
 > Boot into systemd-boot on 2017 Macbook Air and press any keys on either the laptop's keyboard or a usb keyboard

**Additional program output to the terminal or log subsystem illustrating the issue**

I'm unsure what to do here, but I'll try to provide anything if you can give me some direction on how

**Comment by medhefgo** [comment]
Please try latest sd-boot from testing repo and make sure it's actually used by checking the "Current Boot Loader" output from `bootctl`

**Comment by Zodigram** [comment]
Bootctl shows the current version as 'systemd-boot 250.3-1-arch', but the issue is still there

**Comment by Zodigram** [comment]
Bootctl actually showed I was using 'systemd-boot 250.3-1-arch', so I've run bootctl update and now I'm properly on 250.5-1-arch and it works perfectly

Thanks for helping me resolve this, and sorry for bringing up a bug that was already solved
