### ISSUE TITLE
__start_BUS_ERROR_MAP and __stop_BUS_ERROR_MAP symbols exported by libsystemd.so

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#234]
When building git master, I get the following symbols exported by libsystemd.so:
__start_BUS_ERROR_MAP
__stop_BUS_ERROR_MAP
Those look like private symbols which should probably be hidden

**Comment by poettering** [comment]
@kaysievers hmm, did anything change in this regard when you rearranged the convenience libs?

**Comment by poettering** [comment]
@mbiebl hmm, those symbols are not listed in src/libsystemd/libsystemd.sym.m4, and the file says that every other symbol is internal... Not sure how that can happen...

**Comment by poettering** [comment]
readelf --syms indeed shows the symbols @mbiebl mentions... it also shows that the .sym file is otherwise correctly applied (i.e. the symbols are all versioned).

Note sure how these symbols end up being global exports...

**Comment by crrodriguez** [comment]
```
diff --git a/src/libsystemd/sd-bus/bus-error.c b/src/libsystemd/sd-bus/bus-error.c
index dac157b..6ae86da 100644
--- a/src/libsystemd/sd-bus/bus-error.c
+++ b/src/libsystemd/sd-bus/bus-error.c
@@ -71,8 +71,8 @@ BUS_ERROR_MAP_ELF_REGISTER const sd_bus_error_map bus_standard_errors[] = {
 };

 /* GCC maps this magically to the beginning and end of the BUS_ERROR_MAP section */
-extern const sd_bus_error_map __start_BUS_ERROR_MAP[];
-extern const sd_bus_error_map __stop_BUS_ERROR_MAP[];
+extern const sd_bus_error_map __start_BUS_ERROR_MAP[] __attribute__ ((visibility ("hidden")));
+extern const sd_bus_error_map __stop_BUS_ERROR_MAP[] __attribute__ ((visibility ("hidden")));

 /* Additional maps registered with sd_bus_error_add_map() are in this
  * NULL terminated array */
```

works for me.. if you need answers on why ..I have no idea, you will have to ask people familiar with the linker (as this is a GNU linker extension)

**Comment by kaysievers** [comment]
Thanks Christian. Added _hidden_ and a comment to the magic variables.

**Comment by dvdhrm** [comment]
This happens only with `-Wl,-fuse-ld=gold` and is easily reproducible with an example. I'll report it upstream.

**Comment by dvdhrm** [comment]
In case anyone cares: https://sourceware.org/bugzilla/show_bug.cgi?id=18548

I will drop the workaround, once this is fixed upstream (which doesn't look very promising, though).
