### ISSUE TITLE
`networkctl reload` doesn't reload configuration

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#23402]
**systemd version the issue has been seen with**

249.7

**Used distribution**

PLD Linux

**Linux kernel version used** (`uname -a`)

5.15.24

**CPU architecture issue was seen on**

x86_64

**Expected behaviour you didn't see**

`networkd` configures interfaces using current config.

**Unexpected behaviour you saw**

`networkd` configures interfaces using obsoleted config.

**Steps to reproduce the problem**

1. change the interface configuration (may be required to see a problem: in a way that isn't detected, like swapping entire directory with some older one),
2. `networkctl reload`
3. `networkctl down iface; networkctl up iface`

My current setup:
```
# ls 20-bond10-v2390.net*
lrwxrwxrwx 1 root root  18 Apr 18 10:50 20-bond10-v2390.network.d -> 00-common_settings
-rw-r--r-- 1 root root 228 May 16 12:42 20-bond10-v2390.netdev
-rw-r--r-- 1 root root  63 May 16 12:57 20-bond10-v2390.network
# cat 20-bond10-v2390.network.d/default.conf 
[Network]
LinkLocalAddressing=no
LLMNR=no
LLDP=yes
EmitLLDP=no
IPv6AcceptRA=no
IPv6SendRA=no
IPv4ProxyARP=false
ConfigureWithoutCarrier=yes
# IgnoreCarrierLoss=ConfigureWithoutCarrier
KeepConfiguration=static

# networkctl reload; networkctl down v2390; networkctl up v2390; ip a sh dev v2390
21: v2390@bond10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff
    inet 10.10.100.2/30 brd 10.10.100.3 scope global v2390
       valid_lft forever preferred_lft forever
    inet6 fe80::92e2:baff:fe16:d6f4/64 scope link 
       valid_lft forever preferred_lft forever
```

Interface should not have inet6 settings. I guess it keeps the old one as the #23128 is not effective in this version, however I expect the `reload` to do the actual reload of entire configuration, not some magic foo-shmoo-caching of files.

Apparently the entire `networkd` was written in a way that requires system reboot for reconfiguration to take place (see #23022), but it's high time to fix it and make it somehow usable.

**Comment by yuwata** [comment]
This is already fixed by 8524db502134135d96219ecd6df0d0fc5c475b9d (v250).

Closing. Feel free to request to reopen this v250 or newer still have the issue.
