### ISSUE TITLE
Dependency failed for [filesystem mount point] at boot with kernels 5.17.1+

### ISSUE THREAD

**Issue by rado84-github** [systemd/systemd#23431]
**systemd version the issue has been seen with**
 > 250.x+

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `5.17.1` (and newer)

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > mounting filesystems without errors

**Unexpected behaviour you saw**
 > "Dependency failed for [filesystem mount point]"

**Steps to reproduce the problem**
 > 1. Use Arch with systemd 250.1 or newer (250.5 will do as well) and kernel 5.17.1 or newer.
2. Have several different filesystem mount points in fstab.
3. Boot the system and watch for "dependency failed" messages in dmesg during startup. They're easy to spot cuz they're usually red and the system will hang after failing to mount the filesystems.

**Possible steps to temporarily fix the problem**
Reboot the system several times by switching off the power button on the power supply. Usually after the third reboot using this method, the system manages to boot without a problem. But if you reboot again after seeing the desktop, the whole story repeats all over again.

••Additional Information**
The described problem is happening for almost a month now, so I switched to LTS kernel and the problem disappeared. Two days ago I installed the regular kernel version which is currently 5.17.8 (I think) in order to see if the problem was fixed. It wasn't, so I changed the kernel to LTS again.

IDK if the cause is systemd or the kernel, or a conflict between the two. The reason I'm reporting this here is that I'm hoping that maybe you can work with whoever writes the Arch kernels to fix this problem. Otherwise when the LTS kernel reaches 5.17 version, I'll have to disable almost all updates on my system forever or go back to Windows, which I don't wanna do, especially after using linux for 7 years. And no, this is not a threat or something, I just don't see any other way to keep my system booting normally whenever 5.17 arrives at LTS and there's no telling what effect that will have on a rolling system like Arch.

**Comment by yuwata** [comment]
If so, please provide debugging logs. That can be generated with booting with systemd.log_level=debug kernel command line option.

**Comment by rado84-github** [comment]
> If so, please provide debugging logs. That can be generated with booting with systemd.log_level=debug kernel command line option.

I'm guessing this line has to go somewhere in grub.cfg. But where exactly?

**Comment by poettering** [comment]
please provide debug boot logs (i.e. with systemd.log_level=debug on the kernel cmdline), that show the issue, otherwise this is not actionable for us.

**Comment by rado84-github** [comment]
I just installed 5.18.10 and it didn't do that problem. For now, at least. It must have been something specific to 5.17.
