### ISSUE TITLE
fstab-generator questions

### ISSUE THREAD

**Issue by nmartensen** [systemd/systemd#2344]
A few questions came up while reading the fstab-generator code:
- If `add_sysroot_mount()` returns an error, then `add_sysroot_usr_mount()` will not be called, meaning the error does modify what the code does after that. However, subsequent errors from either `add_sysroot_usr_mount()` or `parse_fstab()` do not have any effect on the code flow and only affect the exit code. Should errors be treated consistently? If yes, stop at first error or always keep going?
- Some comments to the documentation:
  
  > rd.fstab= is honored only by initial RAM disk (initrd) while fstab= is honored by both the main system and the initrd.
  
  I am not sure if the `rd.fstab=` is really ignored in the main system.
  
  > root= is honored by the initrd.
  
  Indeed. If I understand correctly, it is also required if you have an initrd.
  
  > Otherwise, this parameter defaults to the /usr entry found in /etc/fstab on the root filesystem.
  
  This is mentioned for all three of the `mount.usr*` parameters. In other words, these parameters can be used to override the entire /usr entry in fstab (if there is one), but not to override only parts of the entry.
- What is the rationale behind using the `root=` value as default for the `mount.usr` parameter? Is there a use case where / and /usr are separate mounts, but share the same filesystem, only with different fstype and/or options? Should the presence of the `mount.usr` parameter be prerequisite for respecting any of the other two?

**Comment by nmartensen** [comment]
Further reading reveals that yes, `rd.fstab=` is really ignored in the main system.

**Comment by poettering** [comment]
Sorry for not replying more timely (though note that the issue tracker isn't really a discussion forum, the better place for this is is certainly the mailing list).

The first issue you raise is indeed ugliness in the code. I'll prep a fix for that, to make sure we don't skip the handling of /usr if the root mount handling already fails.

Your second issue you already answered, parse_proc_cmdline() filters out settings prefixed with "rd." if not running in an initrd.

The answer to your third issue is indeed the case where only the mount option string differs. Specifically, on btrfs you chose the subvolume with the mount option. hence it makes sense to only specify the usr mount option for it, and leave the usr mount device out, if it's the same as the root device

**Comment by poettering** [comment]
Some fixes for the raised points are now waiting in PR #3600.
