### ISSUE TITLE
is-enabled doesn't show correct status if service symlink is not under /etc/systemd/system

### ISSUE THREAD

**Issue by chaohub** [systemd/systemd#23446]
**systemd version the issue has been seen with**
 > 247.6

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `5.4.86`

**CPU architecture issue was seen on**
 > ARM

**Expected behaviour you didn't see**
 > systemctl is-enabled my-test.service
 enabled

**Unexpected behaviour you saw**
 > systemctl is-enabled my-test.service
disabled

**Steps to reproduce the problem**
 > Added multiple paths to systemd unit look up path.
Move my-test.service from /etc/systemd/system/multi-user.target.wants/my-test.service to /vendor/etc/systemd/system/multi-user.target.wants/my-test.service.
Reboot
my-test.service is loaded correctly.
But systemctl is-enabled my-test.service shows it's disabled.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by yuwata** [comment]
Sorry, v247 is slightly old here. Please contact to your downstream. Closing.

If you can reproduce this issue with a recent release or the current git HEAD, then feel free to request to reopen this.
