### ISSUE TITLE
ProtectSystem=strict does not restrict Unix domain sockets 

### ISSUE THREAD

**Issue by dcousens** [systemd/systemd#23470]
**systemd version**
> 250.5-1

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
```
5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux
```

**Unexpected behaviour you saw**
Unix domain sockets (in `/run`) are read-writable despite `ProtectSystem` implying that `/run` should be read-only?
This might be a documentation subtlety, or something to do with Linux.

**Steps to reproduce the problem**
Showing that `ProtectSystem=strict` is not enforcing a read-only filesystem by allowing read-write on a domain socket
```
(as root)
> rm -f /run/mysock
> bash -c 'echo hello | ncat -lU /run/mysock' &
Ncat: Listening on /run/mysock

> chmod 606 /run/mysock
> systemd-run -t -p ProtectSystem=strict -p User=dcousens ncat -U /run/mysock
hello
```

Showing that `chmod` permissions are respected
```
(as root)
> rm -f /run/mysock
> bash -c 'echo hello | ncat -lU /run/mysock' &
Ncat: Listening on /run/mysock

> chmod 600 /run/mysock
> systemd-run -t -p ProtectSystem=strict -p User=dcousens ncat -U /run/mysock
Ncat: Permission denied.
```
(`chmod 604` will fail too)

Maybe I'm misunderstanding something Linux related, in any event, hopefully this issue helps someone.

**Comment by yuwata** [comment]
I guess this is not an issue in systemd, but how unix socket works. Interesting.

**Comment by poettering** [comment]
yeah, this is how linux works. we should document that i guess.
