### ISSUE TITLE
systemd-250.4: DefaultStartLimitBurst=5 is not honored

### ISSUE THREAD

**Issue by pacho2** [systemd/systemd#23478]
**systemd version the issue has been seen with**
 > 250.4

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux dell-2017 5.15.33-gentoo #1 SMP PREEMPT Sun Apr 10 17:21:40 CEST 2022 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux
`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > gdm.service should stop getting restarted as it keeps failing forever

**Unexpected behaviour you saw**
 > gdm.service keeps restarting forever preventing me from even login in in consoles as it keeps getting on the input each time it tries to start 

**Steps to reproduce the problem**
 > In my case it seems nvidia drivers got broken causing X session to die, gdm crashed and got restarted by systemd... without limit

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
Not a useful bug report. Please provide logs that illustrate what happens, in systemd debug mode please (use `systemd-analyze log-level debug`, then reproduce the issue, or similar)

What does gdm.service even set for Restart=?

What did you set DEfaultStartLimitInterval to?

**Comment by poettering** [comment]
Closing due to lack of response.

**Comment by pacho2** [comment]
Oops, I don't know why I missed the mail notification

At the end it was caused by having those dead symlinks:
```# ls -l
total 0
lrwxrwxrwx 1 root root 34 abr  7  2019 getty@tty1.service -> /lib/systemd/system/getty@.service
lrwxrwxrwx 1 root root 38 may 24  2017 getty@tty2.service -> /usr/lib/systemd/system/getty@.service
lrwxrwxrwx 1 root root 38 may 24  2017 getty@tty3.service -> /usr/lib/systemd/system/getty@.service
lrwxrwxrwx 1 root root 38 may 24  2017 getty@tty4.service -> /usr/lib/systemd/system/getty@.service
lrwxrwxrwx 1 root root 38 may 24  2017 getty@tty5.service -> /usr/lib/systemd/system/getty@.service
lrwxrwxrwx 1 root root 38 may 24  2017 getty@tty6.service -> /usr/lib/systemd/system/getty@.service
```

After removing them, gdm could finally start normally.

Regarding the Restart value, it seems that it is "always"
https://gitlab.gnome.org/GNOME/gdm/-/blob/main/data/gdm.service.in

Regarding the limit interval... I didn't touch the defaults
#DefaultStartLimitIntervalSec=10s
