### ISSUE TITLE
systemd-cryptsetup fails opening luks2 pkcs#11 yubikey token

### ISSUE THREAD

**Issue by wkennington** [systemd/systemd#23479]
**systemd version the issue has been seen with**
 > `251`

**Used distribution**
 > `arch`

**Linux kernel version used** (`uname -a`)
 > `5.17.9`

**CPU architecture issue was seen on**
 > `x86_64`

**Expected behaviour you didn't see**
 > The pkcs#11 token should have performed the decryption routine to unlock the drive

**Unexpected behaviour you saw**
 > systemd-cryptsetup doesn't know how to find the private key object on the yubikey.
```
[   15.094304] systemd-tty-ask-password-agent[302]: Password query on /dev/tty1 finished successfully.
[   15.094883] pcscd[279]: 04852916 ifdhandler.c:1368:IFDHTransmitToICC() usb:1050/0404:libudev:0:/dev/bus/usb/001/003 (lun: 0)
[   15.104369] systemd-cryptsetup[277]: Successfully logged into security token 'YubiKey PIV #5621721'.
[   15.105399] systemd-cryptsetup[277]: Successfully written 512 bytes random data acquired via PKCS#11 to kernel random pool.
[   15.105525] systemd-cryptsetup[277]: Selected PKCS#11 object is not a private key, refusing.
```

**Steps to reproduce the problem**
 > Boot up the systemd and answer the disk unlock prompt with the PIN of the PIV module for the key.

**Additional program output to the terminal or log subsystem illustrating the issue**
This was initialized with
```
ykman piv keys generate --pin-policy NEVER --touch-policy NEVER --algorithm RSA2048 9e pubkey.pem
ykman piv certificates generate --subject "CN=yubico" --valid-days 3650 9e pubkey.pem
systemd-cryptenroll --pkcs11-token="pkcs11:model=YubiKey%20YK4;manufacturer=Yubico%20%28www.yubico.com%29;serial=5621721;token=YubiKey%20PIV%20%235621721;id=%03;object=X.509%20Certificate%20for%20Key%20Management;type=cert" /dev/nvme0n1p2
```

**Comment by wkennington** [comment]
Someone posted a workaround for a similar issue when using a nitrokey, but with the yubikey there are no pkcs#11 objects with `type=private` to satisfy the requirement.

**Comment by wkennington** [comment]
It turns out that it works fine if I perform a similar hack to that post, dumping the token from luks, transforming the public key path to private by replacing "Public" with "Private" Ie. `pkcs11:model=YubiKey%20YK5;manufacturer=Yubico%20%28www.yubico.com%29;serial=8677559;token=YubiKey%20PIV%20%238677559;id=%03;object=Public%20key%20for%20Key%20Management;type=public` -> `pkcs11:model=YubiKey%20YK5;manufacturer=Yubico%20%28www.yubico.com%29;serial=8677559;token=YubiKey%20PIV%20%238677559;id=%03;object=Private%20key%20for%20Key%20Management;type=private`, and then import the json back into a token.

**Comment by poettering** [comment]
I originally wrote/tested this against a Yubikey.



> What the yubikey objects look like

…

This list does not show any private keys being on the device? what's going on?

**Comment by poettering** [comment]
oh, if you enroll while dropping the `;type=public` thing, does it work then?

the specified URI must be reasonably "vague" that it matches both the private and the public object on the device. If you fixate it to the public one, then of course we cannot use it for decryption.

We should probably document that better...

**Comment by wkennington** [comment]
This doesn't seem to be any better by removing the type=public part, because the certificate object is a different object from the public key identified by the object field

**Comment by Manouchehri** [comment]
@wkennington Could you dump what you managed to get enrolled? I'm confused how you managed to get it working without p11tool being able to find any private data.

```
cryptsetup token export --token-id 0 /dev/nvme0n1p2 | jq
cryptsetup token export --token-id 1 /dev/nvme0n1p2 | jq
```

**Comment by Manouchehri** [comment]
I managed to get this working by:

```sh
ykman piv keys generate -a RSA2048 --pin-policy never --touch-policy never 9e pubkey.pem
ykman piv certificates generate --subject "demo4" -P 123456 -d 3650 9e pubkey.pem
p11tool --provider /lib/aarch64-linux-gnu/libykcs11.so --list-all --login

sudo systemd-cryptenroll --pkcs11-token-uri="pkcs11:model=YubiKey%20YK5;manufacturer=Yubico%20%28www.yubico.com%29;serial=13371337;token=YubiKey%20PIV%20%2313371337;id=%04;object=X.509%20Certificate%20for%20PIV%20Attestation%209e;type=cert" /dev/loop0

cryptsetup token export --token-id 0 /dev/loop0 > header.json
nano header.json
cryptsetup token import --json-file header.json --token-id 1 /dev/loop0
cryptsetup token remove --token-id 0 /dev/loop0
```

In header.json, I replaced:

```
pkcs11:model=YubiKey%20YK5;manufacturer=Yubico%20%28www.yubico.com%29;serial=13371337;token=YubiKey%20PIV%20%2313371337;id=%04;object=X.509%20Certificate%20for%20PIV%20Attestation%209e;type=cert
```

with:
```
pkcs11:model=YubiKey%20YK5;manufacturer=Yubico%20%28www.yubico.com%29;serial=13371337;token=YubiKey%20PIV%20%2313371337;id=%04;object=Private%20key%20for%20Card%20Authentication;type=private"
```

The only odd thing is that I'm still prompted for a PIN.

@poettering Does your private URI look like mine above?
