### ISSUE TITLE
systemd-firstboot don't prompt to ask new password when /etc/passwd exists

### ISSUE THREAD

**Issue by CoelacanthusHex** [systemd/systemd#23488]
**systemd version the issue has been seen with**
251

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)

5.17.9-zen1-1-zen

**CPU architecture issue was seen on**
x86_64 and riscv64

**Expected behaviour you didn't see**
When /etc/passwd exists but /etc/shadow doesn't, systemd-firstboot will ask new password at startup.

**Unexpected behaviour you saw**
When /etc/passwd exists but /etc/shadow doesn't, systemd-firstboot won't ask new password at startup.

**Steps to reproduce the problem**
setup systemd-firstboot service with `--prompt` option, remove /etc/shadow and /etc/machine-id but keep /etc/passwd, then reboot

**Additional infomation**

This problem since https://github.com/systemd/systemd/commit/c4a53ebf7a51674a14f2273bb6fac382ca75f9eb, in this commit, the author makes condition from "/etc/shadow doesn't exist" to "both /etc/shadow and /etc/passwd don't exist". This is a condition hard to reach, /etc/passwd record user list and some information, if delete it, This may cause the system to not work properly.

**Possible solution**

1. let users use `--force` option to force asking, but this will change the behavior of others asking
2. rollback this change, let systemd-firstboot only check /etc/shadow exist again
3. change check condition, from "both /etc/shadow and /etc/passwd don't exist" to "/etc/shadow doesn't exist and `x` in /etc/passwd root password"

**Comment by DaanDeMeyer** [comment]
@CoelacanthusHex Can you test https://github.com/systemd/systemd/pull/23907?
