### ISSUE TITLE
Homed - Support for fido2 hmac-secret encryption with fscrypt

### ISSUE THREAD

**Issue by ksy63** [systemd/systemd#23487]
**Is your feature request related to a problem? Please describe.**
Provide an option for systemd-homed to automatically decrypt a fscrypt home directory during login with hmac-secret from a fido2 device

**Describe the solution you'd like**
Use a fido2 device to log into a user account and also decrypt their fscrypt home directory in a single step. This should require only a one time authentication to the fido device (e.g. entering the device pin only once for both login and decryption)

This solution would allow to secure both login and encryption with fido2 hmac-secret, thereby only require entering a single fido2 device pin instead of passwords.

**Describe alternatives you've considered**
Since I am unaware of any options to implement both fido authentication and automatic home decryption, the only alternatives are to either stay with password authentication or go without home encryption.

**The systemd version you checked that didn't have the feature you are asking for**
251-1

**Comment by poettering** [comment]
This is already supported. Just enroll a fido2 device for a homed account using the fscrypt backend
