### ISSUE TITLE
LLMNR resolution breaks some verification queries.

### ISSUE THREAD

**Issue by pemensik** [systemd/systemd#23494]
**systemd version the issue has been seen with**
 > systemd-251-1.fc37.x86_64

**Used distribution**
 > Fedora Rawhide (37)

**Linux kernel version used** (`uname -a`)

 > `Linux *.redhat.com 5.18.0-0.rc7.54.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 16 14:40:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > All dnssec enabled queries reach destination

**Unexpected behaviour you saw**
 > dig org. dnskey ended with NXDOMAIN, which is a nonsense

**Steps to reproduce the problem**
 > dnf install ldns-utils && drill -S org. dnskey

**Additional program output to the terminal or log subsystem illustrating the issue**
- LLMNR=yes
- DNSSEC=yes

```
# drill -S src.fedoraproject.org @127.0.0.53
;; Number of trusted keys: 1
;; Chasing: src.fedoraproject.org. A


DNSSEC Trust tree:
src.fedoraproject.org. (A)
|---fedoraproject.org. (DNSKEY keytag: 60624 alg: 14 flags: 256)
    |---fedoraproject.org. (DNSKEY keytag: 58125 alg: 14 flags: 257)
    |---fedoraproject.org. (DS keytag: 58125 digest type: 2)
No trusted keys found in tree: first error was: No DNSSEC public key(s)
;; Chase failed.
```

- LLMNR=no
- DNSSEC=yes
```
# drill -S src.fedoraproject.org @127.0.0.53
;; Number of trusted keys: 1
;; Chasing: src.fedoraproject.org. A


DNSSEC Trust tree:
src.fedoraproject.org. (A)
|---fedoraproject.org. (DNSKEY keytag: 60624 alg: 14 flags: 256)
    |---fedoraproject.org. (DNSKEY keytag: 58125 alg: 14 flags: 257)
    |---fedoraproject.org. (DS keytag: 58125 digest type: 2)
        |---org. (DNSKEY keytag: 15843 alg: 8 flags: 256)
            |---org. (DNSKEY keytag: 26974 alg: 8 flags: 257)
            |---org. (DS keytag: 26974 digest type: 2)
                |---. (DNSKEY keytag: 47671 alg: 8 flags: 256)
                    |---. (DNSKEY keytag: 20326 alg: 8 flags: 257)
;; Chase successful
```

I have found [interesting document](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-llmnrp/eed7fe96-9013-4dec-b14f-5abf85545385) describing implementation on Windows. It clearly states no other resource records should be handled but A, AAAA and PTR.

I think because Fedora enables by default ``resolve`` NSS plugin, it should not serve the same records on DNS stub. It does not make sense for anything but host address queries anyway. I think it should be switched for DNS originated queries just as fallback in this case.

If it does not find it on DNS, check also LLMNR. Primary users would be via resolve plugin doing the translation directly. Programs using DNS want DNS reply in the first place. Queries done by unicast would be faster. But never respond to DNS query with negative LLMNR response without checking DNS as well.

**Comment by pemensik** [comment]
I have verified it on ``systemd-251.1-2.fc37.x86_64`` again. @msekletar told me this is not just llmnr related, but it seems to me.

```
$ sudo resolvectl dnssec host0 yes && sudo resolvectl llmnr host0 no && drill -S src.fedoraproject.org | tail -2
                    |---. (DNSKEY keytag: 20326 alg: 8 flags: 257)
;; Chase successful
$ sudo resolvectl dnssec host0 yes && sudo resolvectl llmnr host0 yes && drill -S src.fedoraproject.org | tail -2
No trusted keys found in tree: first error was: No DNSSEC public key(s)
;; Chase failed.
```
I get reliable results even if I repeat those steps.

**Comment by fermulator** [comment]
Same problem as we raised back in 2019 no? 13763

**Comment by pemensik** [comment]
Well, yes, very similar. A minor difference is that queried type of those records are not addresses, but DNSKEY and DS queries. Otherwise I agree, closely related, thanks for mentioning it. And one of differences is this is not yet closed. Also it breaks external tool, which does not do directly just single label query and nothing else.
