### ISSUE TITLE
systemd should support all hw revisions of the Trusted Platform Module (TPM) technology.

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#23514]
When running bootctl I noticed that systemd seemed to be only checking for TPM 2 support while the hardware I ran the command TPM 1.2 chip on it.

Granted if TPM <=2 was secure then obviously TPM 2.x would never have come to existance however hardware evolves in stages and each revision produced and implemented in devices in the billions so not supporting older hardware revision of the TPM's is equivalent of not supporting older hard drives, cpu, gpu's memory etc. so arguably the ( backward ) compatibility to older hardware revisions should always exist or what's the logic behind not supporting the older 1.2  hardware revision of the TPM, I mean is the plan here to stop supporting TPM 2 when it get's superseeded by next hardware revision or what's the engineering logic behind not supporting older hardware revisions of the TPM family?

**Comment by Winterhuman** [comment]
Just seached though https://0pointer.net/blog/archives.html, the man pages for crypttab, cryptsetup, and systemd-cryptenroll, but, I couldn't find any mentions of TPM1.2 (though I swear I've seen a mention of it somewhere...).

**Comment by bluca** [comment]
Please see https://github.com/systemd/systemd/issues/22091#issuecomment-1024344511
