### ISSUE TITLE
Make it possible to override rate limiting in write_to_kmsg()

### ISSUE THREAD

**Issue by mwilck** [systemd/systemd#23515]
**Is your feature request related to a problem? Please describe.**

The ratelimiting in `write_to_kmsg()` makes it impossible to retrieve all log messages that systemd prints during boot, in particular if `systemd.log_level=debug` is set. In some situations, it's crucial for developers to be able to retrieve all log messages from this important phase of the boot procedure.

While switching root, journald isn't running, and thus systemd logs to `/dev/kmsg`. This is rate limited both on the kernel side and on the systemd side. Kernel rate limiting can be overridden with the parameter `printk.devkmsg=on`. But there is no respective parameter to switch off the rate limiting in systemd.

The behavior was introduced with 78158d134b056ceb974292e40a58e5f8a9af4cbe. 

**Steps to reproduce the problem**
boot with kernel parameters `systemd.log_level=debug printk.devkmsg=on log_buf_len=4M`
This should normally enable `/dev/kmsg` to buffer all messages that systemd prints during boot.
But it doesn't; some messsages are always missing.

**Describe the solution you'd like**

Make it possible to switch off the rate limiting in `write_to_kmsg()` with some boot parameter that systemd recognizes, e.g. `systemd.ratelimit_dev_kmsg=0`.

**Describe alternatives you've considered**

 1. Simply check the existing kernel boot parameter `printk.devkmsg=on`  and switch rate limiting off if it's set.
 2. Completely avoid this rate limiting (revert 78158d1), because there is already rate limiting in the kernel, and we don't need two independent rate limiting mechanisms.

**The systemd version you checked that didn't have the feature you are asking for**
All versions since v244

**Comment by mwilck** [comment]
See https://github.com/systemd/systemd/pull/23437#issuecomment-1133077508 for a case where patching out the rate limiting actually helped analyzing a problem.

I'd submit a PR, but I wanted to discuss first how the maintainers would like to address this issue.

Adding @fbuihuu, @yuwata, @keszybz

**Comment by yuwata** [comment]
It seems `printk.devkmsg=on` is always set. See 6123dfaa72589735c3e8e9b9b9e075a287f523ab.

I think the concepts of 6123dfaa72589735c3e8e9b9b9e075a287f523ab and 78158d134b056ceb974292e40a58e5f8a9af4cbe conflict with each other. The commit 6123dfaa72589735c3e8e9b9b9e075a287f523ab is mostly for debugging early boot stage or late shutdown process. And, as reported, 78158d134b056ceb974292e40a58e5f8a9af4cbe disrupts debugging...

How about to conditionalize both `disable_printk_ratelimit()` and rate limiting in `write_to_kmsg()` with the current log level (and maybe also with PID)?

I do not think it is not necessary to introduce a new knob to control the behavior.

**Comment by mwilck** [comment]
> It seems `printk.devkmsg=on` is always set. See [6123dfa](https://github.com/systemd/systemd/commit/6123dfaa72589735c3e8e9b9b9e075a287f523ab).

Ugh, 6123dfa is a bit ugly. The kernel uses rate limiting by default [for a reason](http://lkml.kernel.org/r/20160719072344.GC25563@nazgul.tnic). 
 
> I think the concepts of [6123dfa](https://github.com/systemd/systemd/commit/6123dfaa72589735c3e8e9b9b9e075a287f523ab) and [78158d1](https://github.com/systemd/systemd/commit/78158d134b056ceb974292e40a58e5f8a9af4cbe) conflict with each other. 

Indeed.

> How about to conditionalize both `disable_printk_ratelimit()` and rate limiting in `write_to_kmsg()` with the current log level (and maybe also with PID)?

This makes sense to me. I think `disable_printk_ratelimit()` should only be called on startup if the initial log level is set to `debug` using the kernel command line (IOW, we shouldn't touch this setting if the log level is changed during runtime, or if systemd is just being reloaded). It might be wise to reset `printk.devkmsg` to  "ratelimiting" using some service later during boot, and re-enable "on" before shutting down.

Note that with `systemd.log_level=debug`, just setting `printk.devkmsg=on` usually won't be enough.  The amount of log messages is so high that the kernel log buffer is likely to overflow / wrap around unless the user passes something like `log_buf_len=4M`, too. Looking at it this way, we might as well not touch `printk.devkmsg` at all, but provide documentation how to enable log message capturing during boot.

**Comment by dustymabe** [comment]
Definitely would be nice to be able to get these messages somehow. I'm trying to debug some early boot stuff for https://github.com/coreos/fedora-coreos-tracker/issues/1527 and can't see anything past this even with `systemd.log_level=debug systemd.log_color=0 systemd.journald.forward_to_console=1 log_buf_len=5M printk.devkmsg=on debug`:

```
[    1.452076] systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/ignition-ostree-mount-subsequent-sysroot.service
[    1.453024] systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/ignition-ostree-mount-firstboot-sysroot.service
[    1.453949] systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/ignition-ostree-growfs.service
[    1.454760] systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/ignition-ostree-check-rootfs-size.service
[    1.455930] systemd[1]: Too many messages being logged to kmsg, ignoring
```

**Comment by DaanDeMeyer** [comment]
I added                       systemd.log_ratelimit_kmsg in this release. Set that to zero to disable rate limiting.

**Comment by keszybz** [comment]
Let's say that 8750a06b6caa9c1d33872cb7b0fa077497ef9888 resolves this issue.
I think it's enough: for debugging purposes, one can disable the ratelimit. We don't need to be more fancy than that and try to reset it and whatnot. Users who enable debugging need to know what they are doing.

**Comment by dustymabe** [comment]
I'm trying with `systemd 254~rc2-4.fc39` (IIUC https://github.com/systemd/systemd/commit/8750a06b6caa9c1d33872cb7b0fa077497ef9888 should be in there) and can't get this to work. When setting `systemd.log_level=debug` and `systemd.log_ratelimit_kmsg` on the kernel command line I always end up with a:

```
[    1.301878] systemd[1]: Too many messages being logged to kmsg, ignoring
```

after all the `systemd[1]: unit_file_build_name_map: normal unit file` messages.

**Comment by DaanDeMeyer** [comment]
Are you setting `systemd.log_ratelimit_kmsg=0`?

**Comment by dustymabe** [comment]
@DaanDeMeyer - my mistake. I read that wrong. I can confirm setting it to `systemd.log_ratelimit_kmsg=0` does what is desired here. Thank you
