### ISSUE TITLE
[RFE] `.mount` units option for `--internal-only`/`-i`

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#23525]
**Is your feature request related to a problem? Please describe.**
When setting up mount units with `ecryptfs`, the recommended approach is to use `mount -i` when you know the mount options in advance.  Systemd does not have a switch in the `.mount` units that allow me to bypass the `/sbin/mount.filesystem helper`

**Describe the solution you'd like**
Add a flag to gain the behavior of `/bin/mount -i`.  Perhaps something like `NoMountHelper` or a better name.

**Describe alternatives you've considered**
I'm working around it with a `.service` unit that manually calls mount with `-i`.

**The systemd version you checked that didn't have the feature you are asking for**
250

**Comment by poettering** [comment]
-i looks like a debug option. What's the precise usecase? why is -i recommended for ecryptfs? what happens if you don't specify it?

Any links regarding that?

if this is just optimization, then this sounds like a really weak case tbh.

**Comment by jcpunk** [comment]
The `mount.ecryptfs` binary is an interactive question/answer command (https://linuxhint.com/ecryptfs_linux/ has example output).  When run out of a systemd `.mount` unit it is unable to determine the expected results and just aborts.

The Arch Linux wiki has some instructions regarding the `-i` option.
https://wiki.archlinux.org/title/ECryptfs#Manual_setup

**Comment by poettering** [comment]
This sounds like a misdesign in the ecryptfs tools. If the questions are unnecessary in that case, why does it ask for them?

Why not get this fixed in the ecryptfs tools instead.

I am not convinced we should add a special hack around such a shortcoming, one that you can't even declare in /etc/fstab itself at all...

**Comment by jcpunk** [comment]
That makes sense to me.
