### ISSUE TITLE
Credential support for mount units

### ISSUE THREAD

**Issue by cthu1hoo** [systemd/systemd#23535]
I'm using Systemd 250 on Fedora 36 (Kinoite). I'm trying to use encrypted credentials with a CIFS mount unit. My mount looks like this:

```ini
[Mount]
What=//sambaserver/dir
Where=/var/mnt/test
# systemd-creds encrypt -p --name creds /root/.smbcredentials.smbserver -
SetCredentialEncrypted=creds: \
        ... \
        ...
Options=credentials=${CREDENTIALS_DIRECTORY}/creds
Type=cifs
```

However, credentials don't seem to load properly, because in logs I'm seeing the following:

```
May 27 11:13:04 castlepc systemd[1]: Mounting my-mount-unit-name.mount - CIFS: ...
May 27 11:13:04 castlepc mount[113801]: error 2 (No such file or directory) opening credential file /run/credentials/my-mount-unit-name.mount/creds
May 27 11:13:04 castlepc systemd[1]: my-mount-unit-name: Mount process exited, code=exited, status=2/INVALIDARGUMENT
May 27 11:13:04 castlepc systemd[1]: my-mount-unit-name: Failed with result 'exit-code'.
```

Credential path, including unit name, seems to be correct. I don't know how to verify if file is created in `CREDENTIALS_DIR` because mount units don't seem to accept any `Exec*` options. I've also tried loading unencrypted credentials from file with `LoadCredential=` but there was no difference. Am I doing something wrong or is it not supported?

```
$ systemctl --version
systemd 250 (v250.3-8.fc36)
```

Thanks in advance for any help.

**Comment by FrankCoetz** [comment]
I'm using systemd 252.7 on openSUSE. Similar to the original poster to this thread, I'm also trying to use encrypted credentials with a CIFS mount unit. My mounting parameters are as follows:
```
[Mount]
What=//sambaserver/dir
Where=/var/mnt/test
SetCredentialEncrypted=creds: \
        ... \
        ...
Options=credentials=${CREDENTIALS_DIRECTORY}/creds,...
Type=cifs
```
The logs indicate and error accessing the ${CREDENTIALS_DIRECTORY}/creds file
```
Mar 10 13:12:15 localhost systemd[1]: Mounting my-mount-name...
Mar 10 13:12:15 localhost mount[13425]: error 2 (No such file or directory) opening credential file /run/credentials/my-mount-unit-name.mount/creds
Mar 10 13:12:15 localhost systemd[1]: my-mount-unit-name.mount: Mount process exited, code=exited, status=2/INVALIDARGUMENT
Mar 10 13:12:15 localhost systemd[1]: my-mount-unit-name.mount: Failed with result 'exit-code'.
Mar 10 13:12:15 localhost systemd[1]: Failed to mount my-mount-name.
```
Does the executing unit have insufficient permissions to the credential's directory, or perhaps, is the ${CREDENTIALS_DIRECTORY} not available on the Options= line?

I've tried a second scenario by enabling the DynamicUser=yes flag, which seems to be recommended in the systemd documentation when using credential encryption, as follows:
```
[Mount]
What=//sambaserver/dir
Where=/var/mnt/test
DynamicUser=yes
SetCredentialEncrypted=creds: \
        ... \
        ...
Options=credentials=${CREDENTIALS_DIRECTORY}/creds,...
Type=cifs
```
The logs now indicate an error "This program is not installed setuid root -  "user" CIFS mounts not supported."
```
Mar 10 13:29:13 localhost systemd[1]: Mounting my-mount-name...
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring file `/etc/nsswitch.conf` (7)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring directory `/etc` (2)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring file `/etc/passwd` (1)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring directory `/etc` (2)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring file `/etc/nsswitch.conf` (7)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring directory `/etc` (2)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring file `/etc/group` (3)
Mar 10 13:29:13 localhost nscd[682]: 682 monitoring directory `/etc` (2)
Mar 10 13:29:13 localhost mount[13622]: This program is not installed setuid root -  "user" CIFS mounts not supported.
Mar 10 13:29:13 localhost systemd[1]: my-mount-unit-name.mount: Mount process exited, code=exited, status=1/FAILURE
Mar 10 13:29:13 localhost systemd[1]: my-mount-unit-name.mount: Failed with result 'exit-code'.
Mar 10 13:29:13 localhost systemd[1]: Failed to mount my-mount-name.
```
This again seems to be permissions related, where the assigned DynamicUser not having sufficient permissions executing the CIFS mount. Also, I'm uncertain if the ${CREDENTIALS_DIRECTORY} /creds was successfully resolved and accessed.

Would it be possible to provide the recommended parameters to use encrypted credentials with a CIFS mount unit.

Many thanks

**Comment by p3lim** [comment]
I've confirmed that the credentials are never created at the `$CREDENTIALS_DIRECTORY` path, and this should be labeled as a bug.

Testing with `systemd-run` (systemd 252.19) seems to work fine, as the docs suggest, the credentials file is available while the process is running:

```bash
echo 'foo:bar' > plaintext.txt
systemd-creds encrypt --name=cifs plaintext.txt encrypted.out
systemd-run -P --wait -p LoadCredentialEncrypted=cifs:$(pwd)/test -S

root@debian:/root# cat $CREDENTIALS_DIRECTORY/cifs
foo:bar
```

While I ran the above I had `inotifywait -mr /run/credentials/` running and saw run-u115.service being created and written to, and deleted when I exited the shell.

When I ran the (auto)mount unit I discovered that none of these directories/files were being created and written to.

**Comment by sigulete** [comment]
This would be an important addition considering that many remote filesystems require some sort of password to authenticate.
In my case, I'm connecting to an Object Storage.

**Comment by FederAndInk** [comment]
This would indeed be really usefull :+1:

**Comment by p3lim** [comment]
For those still subscribed to this issue, this is finally being shipped with [v258](https://github.com/systemd/systemd/releases/tag/v258).
