### ISSUE TITLE
systemd-oomd: Adding oom-kill status for scope units

### ISSUE THREAD

**Issue by nishalkulkarni** [systemd/systemd#23557]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to detect when an application gets killed by systemd-oomd as they are created as scope units and while previous work(#22629) added this result for .service units it would be helpful to have them for scope units too.

**Describe the solution you'd like**
For now, we can add oom-kill status only when systemd-oomd kills the whole unit, as having this behaviour for individual process OOM kills by the kernel is not feasible(and also out of scope for scope units according to current documentation)

From systemd.scope documentation
```
This also means that the exit statuses of these processes are not relevant for the scope unit failure state. Scope units may still enter a failure state, for example due to resource exhaustion or stop timeouts being reached...
```

**Describe alternatives you've considered**
None

**The systemd version you checked that didn't have the feature you are asking for**
v251

There's been some past discussion on this:
https://bugzilla.redhat.com/show_bug.cgi?id=2077496

There's also a notification mechanism in the works on GNOME's side (it works for service units but has no info on scope units)
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/295

If someone's already working on this, this can be a tracker and if it's not being worked on, let me know I'd like to pick it up!

CC: @benzea @anitazha

**Comment by anitazha** [comment]
Hey @nishalkulkarni! No one is working on it right now so happy to have a patch. There's ScopeResult in src/core/scope.h already that you can extend with a result for OOM kill. Otherwise it's the same flow as in service units that you added previously for checking and handling OOM kills.
