### ISSUE TITLE
Better CIFS documentation

### ISSUE THREAD

**Issue by tsmock** [systemd/systemd#23551]
**Is your feature request related to a problem? Please describe.**
It is non-obvious what settings are required and secure for a CIFS home directory. For example, some programs depend upon symlinks, which are disabled by default in Samba for security reasons.

**Describe the solution you'd like**
Recommended server settings for common CIFS servers for unix home directories or alternative mount options (e.g. `mfsymlinks`).

**Describe alternatives you've considered**
Internet searches for `samba unix home directory settings` (which mostly comes up with `[homes]`).

**The systemd version you checked that didn't have the feature you are asking for**
systemd 251 (251.1-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Comment by yuwata** [comment]
Hm? CIFS is not our project. Closing.
