### ISSUE TITLE
loginctl show current session id

### ISSUE THREAD

**Issue by saivert** [systemd/systemd#2356]
We need to be able to type something like
loginctl session-id
to get the session id of calling process.
That is: c1, c2, etc.. not what  you get from getsid() system call.

**Comment by saivert** [comment]
closing as I finally figured out $XDG_SESSION_ID should have this. maybe a hint in the documentation would be nice.

**Comment by poettering** [comment]
You can use $XDG_SESSION_ID for this, or when using C, you may use the `sd_pid_get_session(0, &session)` call, exported from libsystemd (it has a man page). The latter cannot be overriden by the user, the former of course can. Also note that most "loginctl" commands nowadays default to the calling user's session.
