### ISSUE TITLE
Udev: User-added rules don't work as before.

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#23586]
**systemd version the issue has been seen with**
 > systemd 250 (v250.3-8.fc36)

**Used distribution**
 > Fedora release 36

**Linux kernel version used** (`uname -a`)

 > Linux fedora 5.17.5-300.fc36.aarch64 #1 SMP Thu Apr 28 15:22:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**CPU architecture issue was seen on**
 > aarch64 

**Expected behaviour you didn't see**
 > udev rule  works ok

**Unexpected behaviour you saw**
 > udev rule doesn't work

**Steps to reproduce the problem**
 > 
I have a test_net.rules like below, it doesn’t work now. I guess it may be caused by this PR https://github.com/systemd/systemd/commit/51d9aec0ff333ff554079da4babf6dbfa9837096
[root@fedora ~]# cat /etc/udev/rules.d/test_net.rules
SUBSYSTEM=="net", KERNEL!="lo", ACTION=="add", TAG+="systemd", ENV{SYSTEMD_WANTS}+="test@$name.service"
[root@fedora ~]# cat /usr/lib/systemd/system/test@.service
[Unit]
Description=test interface %i
DefaultDependencies=no

[Service]
Type=oneshot
User=root
ExecStart=/usr/bin/echo %i
TimeoutStartSec=60s
RemainAfterExit=true

[Install]
WantedBy=multi-user.target

When it works well， it has  “SYSTEMD_WANTS=test@enp6s0.service”. But now it's lost.
[root@fedora ~]# udevadm info /sys/class/net/enp6s0
P: /devices/pci0000:00/0000:00:02.2/0000:06:00.0/virtio4/net/enp6s0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:02.2/0000:06:00.0/virtio4/net/enp6s0
E: INTERFACE=enp6s0
E: IFINDEX=3
E: SUBSYSTEM=net
E: USEC_INITIALIZED=19721075
E: ID_NET_NAMING_SCHEME=v250
E: ID_NET_NAME_MAC=enx525400929f34
E: ID_NET_NAME_PATH=enp6s0
E: ID_BUS=pci
E: ID_VENDOR_ID=0x1af4
E: ID_MODEL_ID=0x1041
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Red Hat, Inc.
E: ID_MODEL_FROM_DATABASE=Virtio network device
E: ID_MM_CANDIDATE=1
E: ID_PATH=pci-0000:06:00.0
E: ID_PATH_TAG=pci-0000_06_00_0
E: ID_NET_DRIVER=virtio_net
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=enp6s0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/enp6s0
E: SYSTEMD_WANTS=test@enp6s0.service
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

**Comment by yuwata** [comment]
Strictly speaking, the commit 51d9aec0ff333ff554079da4babf6dbfa9837096 (v247) actually changes the behavior on move event, but it just reverts b081b27e1433cdc7ac72b25ae8b4db887d79187f (v217). So, in other words, b081b27e1433cdc7ac72b25ae8b4db887d79187f breaks backward compatibility and 51d9aec0ff333ff554079da4babf6dbfa9837096 fixes the issue.

Sorry, but this will not be fixed. Please use `ACTION!="remove", which is a recommended way to write rule in general.
