### ISSUE TITLE
LinkLocal IP address assignment on a dual interface system

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#23595]
**Is your feature request related to a problem? Please describe.**
I see that on a dual interface system with eth0 and eth1 ethernet links, on the first boot, the link local IPs are assigned. But they both are at same subnet - 169.254.xxx.xxx with the same default route to reach them. In a scenario, where the physical cable is plugged in to one of the interface, both the IPs are reachable via this single physical link. ie. If you ping the eth1 address while the cable is plugged to eth0 port, its reachable. This may cause some confusions about the initial network settings

**Describe the solution you'd like**
Is there a way to control the link local address assignment in such a way that both interfaces will fall into different subnet ? 
Say eth0 - 169.254.aaa.xxx and eth1 - 169.254.bbb.xxx
 
**Describe alternatives you've considered**
None. 

**The systemd version you checked that didn't have the feature you are asking for**
systemd 249 (249.4+)

**Comment by yuwata** [comment]
Let me confirm that you use systemd-networkd, right?

**Comment by sunharis** [comment]
> Let me confirm that you use systemd-networkd, right?

yes

**Comment by sunharis** [comment]
@yuwata When linklocal is set on both interfaces after a factory reset, the system comes up with two default routes for eth0 and eth1 on same subnet. This causes confusions in the initial routing table, when a single physical cable connection is made from a local laptop. The connection drops are random, sometimes eth0 works and sometimes eth1 works.

**Comment by arvidjaar** [comment]
@sunharis 

> Is there a way to control the link local address assignment in such a way that both interfaces will fall into different subnet ?

No. IPv4 link local address is by definition 169.254.0.0/16. RFC 3927, 2.8, "The 169.254/16 address prefix MUST NOT be subnetted".

> When linklocal is set on both interfaces after a factory reset, the system comes up with two default routes for eth0 and eth1 on same subnet. 

You are mistaken, these are not default routes.

And yes, when you want to use link local addresses your application must know which link to use. If two links are separate, then both of them may have hosts with the same link local address. There is no way to disambiguate them.

**Comment by yuwata** [comment]
Yeah, this is not supported. Closing.

> In a scenario, where the physical cable is plugged in to one of the interface, both the IPs are reachable via this single physical link.

Do you use `ConfigureWithoutCarrier=yes` or `IgnoreCarrierLoss=yes`?? It sounds expected behavior.

**Comment by sunharis** [comment]
@yuwata @arvidjaar I have a further question.

In the dual port linklocal system, is there a way to setup the routing in such a way that the ping to eth0 is responded via eth0 link only and ping to eth1 is responded via eth1 only.
