### ISSUE TITLE
OnFailure units get triggered when service timesout on sigterm during restart of service

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#23599]
**systemd version the issue has been seen with**
 > 243

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 >
have a simple service which ignores sigterm and has OnFailure and Restart cfg in its service file
issue restart of that service.
expectation is that OnFailure units will not be triggered  (as per doc as service is gonna restart even if it timedout sigterm) but in it is observed that they are triggered 

**Unexpected behaviour you saw**
 > see above

4084182:May 31 09:44:02 mxbr-10-ptx10k systemd[1]: Stopping "X"...

4089507:May 31 09:45:32 mxbr-10-ptx10k systemd[1]: x.service: State 'stop-sigterm' timed out. Killing.
4089508:May 31 09:45:32 mxbr-10-ptx10k systemd[1]: x.service: Killing process 14923 (x) with signal SIGKILL.

4089515:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: x.service: Main process exited, code=killed, status=9/KILL
4089517:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: x.service: Failed with result 'timeout'.
4089518:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: Stopped "X".
4089519:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: x.service: Triggering OnFailure= dependencies.
4089522:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: Started "X".
4089526:May 31 09:45:33 mxbr-10-ptx10k systemd[1]: [failure_handler@x.service](mailto:failure_handler@x.service): Succeeded.

**Steps to reproduce the problem**
 >
have a simple service which ignores sigterm and has OnFailure and Restart cfg in its service file
issue restart of that service 

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
