### ISSUE TITLE
libudev API documentation replacement is incomplete

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#236]
The gtk-doc based API documentation for libudev has been removed in v221. 
There should be a suitable replacement using man pages before v221 is released.

**Comment by dvdhrm** [comment]
I added the skeletons in #253 now. This should at least provide the function definitions and some browsing hints. Further help regarding the DESCRIPTION part of the man-pages is highly welcome.

**Comment by mbiebl** [comment]
@dvdhrm can this be closed now or is there still work left to be done?

**Comment by dvdhrm** [comment]
@mbiebl There is still work to be done, but I'll close it anyway. I mean, we're as good as we were before, so I think no reason to keep it open.
