### ISSUE TITLE
Trigger a service on journal message

### ISSUE THREAD

**Issue by EdiDD** [systemd/systemd#23614]
Is there a way to trigger a systemd service when specific message appears in journal ? Even something similar to rsyslog functionality will be sufficient:
`:msg,contains, "pattern" /path/to/newlogfile`
It will be then possible to use **systemd.path** to trigger a service. I want to avoid installing secondary logging system (like rsyslog) unless it is the only way.

**Comment by yuwata** [comment]
Sorry, here is not a support forum. Closing.
