### ISSUE TITLE
resolved should also cache the scope ID (interface) of an IP address

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#2361]
One of the cooler features of resolved in combination with SSH is this:

```
alexander@shepard:~$ ssh root@thor
[...]
root@thor:~# echo $SSH_CONNECTION 
fe80::f8a2:50ff:fe3c:7846%tap42 46828 fe80::70fe:eff:fe2f:7c8c%tap42 22
```

As can be seen, resolved discovered the link-local address of the target host and supplied both it and the necessary scope ID (e.g. the interface on which this link-local address is valid) to SSH. This means that SSH'ing into a host by name will work as soon as there's a link and no further network configuration is necessary. I think this is awesome.

However, subsequent connections fail unfortunately:

```
alexander@shepard:~$ ssh root@thor
ssh: connect to host thor port 22: Invalid argument
alexander@shepard:~$ 
```

Looking at this...

```
alexander@shepard:~$ sudo systemctl restart systemd-resolved
alexander@shepard:~$ /lib/systemd/systemd-resolve-host thor
thor: fe80::70fe:eff:fe2f:7c8c%tap42

-- Information acquired via protocol LLMNR/IPv6 in 185.0ms.
alexander@shepard:~$ /lib/systemd/systemd-resolve-host thor
thor: fe80::70fe:eff:fe2f:7c8c

-- Information acquired via protocol LLMNR/IPv6 in 124.4ms.
alexander@shepard:~$ 
```

... suggests that resolved only emits the scope ID if the related IP address was just discovered, but not when the name is resolved from cache.

For increased awesomeness, please make resolved also emit the scope ID on cached responses. Alternatively, you could consider disabling caching for link-local addresses completely, since they are not very useful without a scope ID.

**Comment by poettering** [comment]
Fix waiting in PR #2524
