### ISSUE TITLE
New wall-by-default behaviour also unintendedly affects suspends, which leaves tens of lines of spew in interactive xterms

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/systemd#23627]
**systemd version the issue has been seen with**
 > Debian 251.2-2

**Used distribution**
 > sid

**Linux kernel version used** (`uname -a`)
 > `Linux amorbus 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > suspends not walling

**Unexpected behaviour you saw**
 > suspends wall

**Steps to reproduce the problem**
 > suspend from gnome UI

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Broadcast message from [interactive user]@amorbus (Sat 2022-06-04 12:00:02 CEST):

The system is going down for suspend NOW!
```

This starts in https://github.com/systemd/systemd/commit/cdf370626f, which, I mean, no opinion for actual power actions (except it matches 4.2BSD, what's old is new, &c.); but the manual says
```
--no-wall
  Do not send wall message before halt, power-off and reboot.
```
and lemme tell ya: it's *insanely* annoying to have this rag in all your tmuxes/xterms, sometimes *a good few times*. *Especially* when they're in curses (they may be permanently broken now!).

Given that the manual *explicitly says* "halt, power-off and reboot", all of which kill the machine so it doesn't matter if they dump garbage in your terminals, I'm assuming that this was unintended for suspends, because it's definitely unwanted for suspends. And hibernates.

As "beloved resolution" goes: make it the default, except for suspends (&c.).
By making
https://github.com/systemd/systemd/blob/0a11366280f7e6262ffb906463c5c0bb4c3827b0/src/login/logind-utmp.c#L71
```c
        if (!m->enable_wall_messages || !m->scheduled_shutdown_action || IN_SET(m->scheduled_shutdown_action->handle, HANDLE_SUSPEND, HANDLE_HIBERNATE, HANDLE_HYBRID_SLEEP, HANDLE_SUSPEND_THEN_HIBERNATE))
```
Or give another way of suppressing this. You get my point.

**Comment by mbiebl** [comment]
This issue has already been fixed in 251.2-1 which is available in unstable.
You need to reboot after the upgrade as logind can't be restarted safely.
