### ISSUE TITLE
`systemd-analyze blame` showing way more devices than before

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#23629]
Version: systemd 251.2-1

**Used distribution**
Arch Linux

**Linux kernel version used**
`Linux - 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC - x86_64 GNU/Linux`

**CPU architecture issue was seen on**
AMD 64-bit

**Expected behaviour you didn't see**
`systemd-analyze blame` returns a similar output to previous `systemd` versions.

**Unexpected behaviour you saw**
 `systemd-analyze blame` returns `sys-module-configfs`, `sys-devices-platform-serial8250-tty-ttySXX.device`, `dev-ttySXX.device`, and other devices including disks (returning duplicate entries for UUID, PARTUUID, PATH, etc).

**Steps to reproduce the problem**
Run `systemd-analyze blame` using systemd 251.2-1 (unknown if v251 introduced this or a minor version, command has not been run for a long time [3 months as a guess?]).

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
1.612s sys-module-configfs.device
1.534s dev-ttyS10.device
1.534s sys-devices-platform-serial8250-tty-ttyS10.device
1.534s sys-devices-platform-serial8250-tty-ttyS12.device
1.534s dev-ttyS12.device
1.533s sys-devices-platform-serial8250-tty-ttyS11.device
...
1.529s sys-devices-pnp0-00:05-tty-ttyS0.device
...
1.505s sys-devices-pci0000:00-0000:00:01.3-0000:02:00.1-ata1-host0-target0:0:0-0:0:0:0-block-sda.device
1.505s dev-disk-by\x2ddiskseq-1.device
1.422s dev-disk-by\x2duuid-916E\x2dF6EA.device
1.422s dev-disk-by\x2dpartuuid-bdd44bd1\x2d45cb\x2d4b87\x2d8fa0\x2d3ada485aa566.device
1.422s sys-devices-pci0000:00-0000:00:01.1-0000:01:00.0-nvme-nvme0-nvme0n1-nvme0n1p1.device
1.422s dev-nvme0n1p1.device
```

**Comment by Fxzzi** [comment]
Occurring for me also. Here's a log output http://ix.io/3Zrl

**Comment by rheijden1970** [comment]
Hi get also the same as above.

4.354s sys-module-configfs.device
4.152s dev-ttyS16.device
4.152s dev-ttyS15.device
4.152s sys-devices-platform-serial8250-tty-ttyS16.device
4.152s sys-devices-platform-serial8250-tty-ttyS15.device
4.152s dev-ttyS14.device
4.152s sys-devices-platform-serial8250-tty-ttyS14.device
4.152s dev-ttyS0.device
4.152s sys-devices-platform-serial8250-tty-ttyS0.device
4.152s dev-ttyS13.device
4.152s sys-devices-platform-serial8250-tty-ttyS13.device
4.152s dev-ttyS12.device
4.152s sys-devices-platform-serial8250-tty-ttyS12.device
4.152s sys-devices-platform-serial8250-tty-ttyS10.device
4.152s dev-ttyS10.device
4.152s dev-ttyS11.device
4.152s sys-devices-platform-serial8250-tty-ttyS11.device
4.152s dev-ttyS1.device
4.152s sys-devices-platform-serial8250-tty-ttyS1.device
4.152s dev-ttyS17.device
4.152s sys-devices-platform-serial8250-tty-ttyS17.device
4.151s dev-ttyS18.device
4.151s sys-devices-platform-serial8250-tty-ttyS18.device
4.151s dev-ttyS19.device
4.151s sys-devices-platform-serial8250-tty-ttyS19.device
4.151s dev-ttyS20.device
4.151s sys-devices-platform-serial8250-tty-ttyS20.device
4.150s dev-ttyS2.device
4.150s sys-devices-platform-serial8250-tty-ttyS2.device

**Comment by koshikas** [comment]
same issue on;
 Kernel: 5.15.46-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.1.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-5.15-x86_64
    root=UUID=e0d878c7-a550-4927-b2b9-cc0be95eeabb rw
    lsm=landlock,lockdown,yama,apparmor,bpf quiet rd.systemd.show_status=auto
    rd.udev.log_level=3 i915.fastboot=1 audit=0 ipv6.disable=1 nowatchdog
    nosmt
  Desktop: KDE Plasma v: 5.24.5 tk: Qt v: 5.15.4 wm: kwin_x11 vt: 1 dm: SDDM
    Distro: Manjaro Linux base: Arch Linux

systemd-analyze blame;
https://pastebin.com/8bDdb3NJ

**Comment by MR-Diamond** [comment]
Same for me (I am on Manjaro, with a fast SSD disk); I also noticed that `sys-module-configfs.device` introduced a slowdown in the boot process.
Previously the system (with systemd 250.5-1) usually taked 2.4 seconds to boot; now with systemd 251.2-3 take 2.7 - 2.9 seconds, and the culprit **seems** `sys-module-configfs.device, according to `systemd-analyze blame`:
`928ms sys-module-configfs.device` (it could also take 1.5 seconds).

**Comment by yuwata** [comment]
@Winterhuman Let me confirm, you mean, the devices e.g. sys-module-configfs or dev-disk-by were not listed by systemd-analyze on v250??

**Comment by Winterhuman** [comment]
@yuwata Maybe? As the issue mentions, I don't have a good time estimate (3 months was a complete guess) so I don't know how long it's been like this. But at some point in the past, it was a much shorter list that was mostly services (and *maybe* `dev-sda.device` style names, really unsure on this)

**Comment by yuwata** [comment]
I guess 75d7b5989f99125e52d5c0e5656fa1cd0fae2405 (v251) and its follow-up commits trigger this "issue".

Before the commit, on switch-root, `device_set_state()` -> `unit_notify()` is called only once. After the change, for each device unit, `device_set_state()` is called twice, first with DEVICE_TENTATIVE, then later with DEVICE_PLUGGED when udevd processed the device. On first call, `inactive_exit_timestamp` is set, and then `active_enter_timestamp` is set on the second call. That means, the two timestamp variables point to different time, hence, `systemd-analyze blame` shows device units with non-zero timespan. See
https://github.com/systemd/systemd/blob/fddad5f4a66a68682892e3fa7f22ec2689786d33/src/analyze/analyze-blame.c#L51-L53
and
https://github.com/systemd/systemd/blob/fddad5f4a66a68682892e3fa7f22ec2689786d33/src/analyze/analyze-time-data.c#L275-L280

So, this is not a bug, and expected. Closing.

**Comment by Winterhuman** [comment]
@yuwata I still think this is an issue, the duplicate names per device aren't useful output and just fill up the list, I can't imagine any users wanting or expecting this output when diagnosing boot times

**Comment by Winterhuman** [comment]
Actually, I'll open a separate enhancement issue, since you're right that this isn't a bug at this point; it's a UI thing.

**Comment by yuwata** [comment]
Yes. systemd-analyze is a kind of debugging tool for systemd, showing more entries is not a bug.

**Comment by cmprmsd** [comment]
I disagree on this issue not being a bug.
 
All module times in `systemd-analyze blame` accumulated should add up to approximately your boot time.
In this case this is not true any more since it shows a large number of entries with `2.nnns`.
This would indicate your boot would take 8000 seconds but in reality and also when looking at `systemd-analyze` the boot time is only 5 seconds.

Since my boot log now has 150 entries this makes the output less readable while only 20-30 records are useful to the viewer.

**Comment by yuwata** [comment]
> This would indicate your boot would take 8000 seconds

Why? Most units are processed in parallel.

> Since my boot log now has 150 entries this makes the output less readable while only 20-30 records are useful to the viewer.

As I already stated in the above, `systemd-analyze` is a kind of debugging tools. Showing much entries is not a bug.

**Comment by cmprmsd** [comment]
Okay, then I misunderstood the output. Scusi :)
