### ISSUE TITLE
systemd spams "Failed to canonicalize" and other messages with a user path that not even exists (anymore)

### ISSUE THREAD

**Issue by faerietree** [systemd/systemd#23657]
**systemd version the issue has been seen with**
 > systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian 10

**Linux kernel version used** (`uname -a`)

 > `Linux <host> 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86 64bit

**Expected behaviour you didn't see**
 > strange log entries on boot up (still debugging if the user logged in)

**Unexpected behaviour you saw**
 > `systemd: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-subsystem-net-devices-tun0.device.requires': Permission denied`

**Steps to reproduce the problem**
 > We today had dozens such messages without deleting any user (see #17849). We did nothing special. The machine suddenly was unavailable (not sure if it was a power supply issue). When we physically went to the machine, it happened to be dark, no display output, no power LED (i was told, so just 2nd hand information)

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
Full log with context: (I also ask the user if ovpn-client was launched on power reset or if this also is an anomaly)

Jun  7 13:51:52 <host> systemd[1]: session-c2.scope: Succeeded.
Jun  7 13:51:52 <host> ovpn-client[865]: SENT CONTROL [vpn.DN]: 'PUSH_REQUEST' (status=1)
Jun  7 13:51:52 <host> ovpn-client[865]: PUSH: Received control message: 'PUSH_REPLY,route <ip> <netmask>,route <gateway-ip>,ping 10,ping-restart 120,ifconfig <client-ip> <client-ip1>,peer-id 8,cipher <cipher>'
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: timers and/or timeouts modified
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: --ifconfig/up options modified
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: route options modified
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: peer-id set
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: adjusting link_mtu to 1625
Jun  7 13:51:52 <host> ovpn-client[865]: OPTIONS IMPORT: data channel crypto options modified
Jun  7 13:51:52 <host> ovpn-client[865]: Data Channel: using negotiated cipher '<cipher>'
Jun  7 13:51:52 <host> ovpn-client[865]: Outgoing Data Channel: Cipher '<cipher>' initialized with 256 bit key
Jun  7 13:51:52 <host> ovpn-client[865]: Incoming Data Channel: Cipher '<cipher>' initialized with 256 bit key
Jun  7 13:51:52 <host> ovpn-client[865]: ROUTE_GATEWAY <lan-gateway>/<lan-netmask> IFACE=<if> HWADDR=<MAC>
Jun  7 13:51:52 <host> ovpn-client[865]: TUN/TAP device tun0 opened
Jun  7 13:51:52 <host> systemd-udevd[365]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jun  7 13:51:52 <host> ovpn-client[865]: TUN/TAP TX queue length set to 100
Jun  7 13:51:52 <host> ovpn-client[865]: /sbin/ip link set dev tun0 up mtu 1500
Jun  7 13:51:52 <host> ovpn-client[865]: /sbin/ip addr add dev tun0 local <client-ip> peer <client-ip1>
Jun  7 13:51:52 <host> ovpn-client[865]: /path/to/add-ovpn-route.sh <params>
Jun  7 13:51:52 <host> kernel: [   17.770278] tun: Universal TUN/TAP device driver, 1.6
Jun  7 13:51:52 <host> openvpn[865]: RTNETLINK answers: No such process

Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-subsystem-net-devices-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> ovpn-client[865]: /sbin/ip route add <vpn-ip-range> via <client-ip1>
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-subsystem-net-devices-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-subsystem-net-devices-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-subsystem-net-devices-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> ovpn-client[865]: /sbin/ip route add <vpn-gateway-ip-range> via <client-ip1>
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-subsystem-net-devices-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-subsystem-net-devices-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-subsystem-net-devices-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-subsystem-net-devices-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-subsystem-net-devices-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-devices-virtual-net-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> ovpn-client[865]: Initialization Sequence Completed
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-devices-virtual-net-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-devices-virtual-net-tun0.device.wants': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-devices-virtual-net-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-devices-virtual-net-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-devices-virtual-net-tun0.device.requires': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user.control/sys-devices-virtual-net-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.config/systemd/user/sys-devices-virtual-net-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1245]: Failed to canonicalize path '/home/<user>/.local/share/systemd/user/sys-devices-virtual-net-tun0.device.d': Permission denied
Jun  7 13:51:52 <host> systemd[1246]: Started D-Bus User Message Bus.
Jun  7 13:51:52 <host> dbus-daemon[1388]: [session uid=113 pid=1388] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.0' (uid=113 pid=1340 comm="/usr/sbin/lightdm-gtk-greeter ")
Jun  7 13:51:52 uniqvan6 systemd[1246]: Starting Accessibility services bus...

```

**Comment by faerietree** [comment]
To relax the situation, I think that is an edge case.

241 isn't most recent version.

We'll soon update the entire infra to Debian 11 base.

**Comment by faerietree** [comment]
This also showed:

`Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.759681] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:18: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.760192] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:19: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.760696] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:20: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.761210] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:21: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.761715] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:22: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.762219] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:23: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.762724] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:24: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.763229] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:25: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.763744] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:27: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: <1051>[    1.764252] systemd-udevd[90]: /usr/lib/udev/rules.d/50-udev-default.rules:29: Invalid GROUP operation
Jun  7 13:51:41 uniqvan6 kernel: [    1.792658] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input0
`

**Comment by tkalfaoglu** [comment]
On systems with PLESK, this bug spams the logs ~ a dozen lines per SECOND..

Sep 26 18:17:19 storm.kalfaoglu.net systemd[15156]: Failed to canonicalize path '/usr/local/psa/admin/.config/systemd/user.control/run-user-10072.mount.wants': Permission denied
Sep 26 18:17:19 storm.kalfaoglu.net systemd[15156]: Failed to canonicalize path '/usr/local/psa/admin/.config/systemd/user/run-user-10072.mount.wants': Permission denied
Sep 26 18:17:19 storm.kalfaoglu.net systemd[15156]: Failed to canonicalize path '/usr/local/psa/admin/.config/systemd/user.control/run-user-10072.mount.requires': Permission denied
(...)

even if these files are created, even with 777, the errors still continue.
