### ISSUE TITLE
resolved ignores DNS servers listening on Linux dummy interfaces

### ISSUE THREAD

**Issue by pmattern** [systemd/systemd#23656]
**systemd version the issue has been seen with**
250.5-251.2
**Used distribution**
Arch Linux
**Linux kernel version used** (`uname -a`)
`Linux desk-1 5.18.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 06 Jun 2022 19:58:58 +0000 x86_64 GNU/Linux`
**CPU architecture issue was seen on**
amd64

**Expected behaviour you didn't see**
If a DNS server is listening on a Linux dummy interface and a domain handled by the server, say `foo.example.org`, is associated with the interface by directive `Domains` in its `*.network` configuration file as usual, then a query like `resolvectl query foo.example.org` should succeed.
**Unexpected behaviour you saw**
Queries like that fail with `foo.example.org: resolve call failed: 'foo.example.org' not found`.

**Steps to reproduce the problem**
* Set up a Linux dummy interface. Make sure a domain, which is about to be handled by the DNS server, is covered by directive `Domains` of the `*.network` file's section `[Network]`. E. g.
```
# *.netdev
[NetDev]
Kind=dummy
Name=local0
# *.network
[Match]
Name=local0
[Network]
Address=fd00:a:b:c::1/64
Address=10.3.2.1/24
DNSSEC=false
Domains=~foo.example.org
LLMNR=false
MulticastDNS=false
```
* Make a DNS server listen on the dummy interface and serve domain `foo.example.org`. Tested with either Knot or dnsmasq.
* Test that both the dummy interface and the DNS server behave as expected. E. g. `ping -6 -c3 fd00:a:b:c::1`, `drill @fd00:a:b:c::1 foo.example.org`, same with IPv4.
* Run `resolvectl query foo.example.org`. This will fail as stated above.

**Additional program output to the terminal or log subsystem illustrating the issue**
resolvectl status shows
```
Link 6 (local0)
Current Scopes: none
     Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
    DNS Domain: ~foo.example.org
```
and I'd assume `Current Scopes: none` is hinting to the underlying problem.

**Comment by poettering** [comment]
The interface has no DNS server configured, hence we will never use it for DNS resolution. You must also set DNS=… to configure some dns servers otherwise the domain configured on it is pointless.

**Comment by pmattern** [comment]
@poettering 
You yourself [called this a bug](https://lists.freedesktop.org/archives/systemd-devel/2022-May/047896.html) unless the configuration is faulty, which it isn't.

> The interface has no DNS server configured, hence we will never use it for DNS resolution.

Of course there is a DNS server listening on the interface.

> You must also set DNS=… to configure some dns servers otherwise the domain configured on it is pointless.

No. If a DNS server is listening on a hardware interface, it is taken into account by resolved automatically, and directive `Domains` works as expected without using `DNS`.

I do not know what drove you when you handled this issue. But it's pretty obvious that you didn't even bother glancing through the initial comment, in particular the "Steps to reproduce".   
Please reopen or provide some reasonable arguments for closing.
