### ISSUE TITLE
[sytemdboot] next kernel version after update

### ISSUE THREAD

**Issue by Drsheppard01** [systemd/systemd#23669]
It seems to me that the most correct behavior after updating the kernel is to switch to the new kernel automatically, if the new kernel does not start, you can use the previous one.

However, the logic of systemdboot is different: when switching to a new kernel, you need to manually write 
```
sudo bootctl set-default <id machine><next version kernel>.conf
```

OS: Fedora 36
systemdboot by default: No
Systemdboot is enabled: Yes (guide https://kowalski7cc.xyz/blog/systemd-boot-fedora-32)

**Comment by keszybz** [comment]
Please show `bootctl status`. In particular the version of sd-boot that is installed is crucial.

**Comment by Drsheppard01** [comment]
System:
     Firmware: UEFI 2.70 (American Megatrends 5.14)
  Secure Boot: disabled (setup)
 TPM2 Support: yes
 Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot v250.3-8.fc36
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/96496102-489e-4db9-9f74-75b34d9eba15
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/96496102-489e-4db9-9f74-75b34d9eba15)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot v250.3-8.fc36)
         File: └─/EFI/BOOT/BOOTIA32.EFI
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot v250.3-8.fc36)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0005
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/96496102-489e-4db9-9f74-75b34d9eba15
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

        Title: Fedora
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/96496102-489e-4db9-9f74-75b34d9eba15
         File: └─/EFI/FEDORA/SHIM.EFI

        Title: Fedora
           ID: 0x0002
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/96496102-489e-4db9-9f74-75b34d9eba15

**Comment by medhefgo** [comment]
The default can be a glob pattern. So to always pick the latest kernel you should be using something like `<id machine>*.conf` as the default. The version entry sorting *should* ensure the correct one is picked.

**Comment by keszybz** [comment]
There were various fixes to the sorting alg done in v251. But there were also changes done to make the *display* order easier to understand. At this point I'm not even sure what exactly the status in F36 is: was it only the display order that was borked, or also the actual selection of the newest entry…

Can you show `bootctl list` too?
