### ISSUE TITLE
mdns sends to wrong multi cast IP

### ISSUE THREAD

**Issue by RoadRunnr** [systemd/systemd#2366]
According to https://tools.ietf.org/html/rfc6762#section-22 mDNS should send to FF02::FB, instead is sends to FF02::1:FB.

avahi (and possibly zeroconf) do not see these queries.

**Comment by zonque** [comment]
Nicely spotted, thanks. Will queue a fix in my next PR. Note, however, that mDNS is not currently enabled by default, and the configuration knobs are not yet exposed.
