### ISSUE TITLE
Resolved answers randomly slow through Wireguard tunnel

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#23671]
**systemd version the issue has been seen with**
 > systemd 251 (251.2-1-arch)

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)

 > `5.18.2-zen1-1-zen`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > DNS answers in less than ~500ms (with TLS)

**Unexpected behaviour you saw**
```
github.com: 140.82.114.4                       -- link: wg0_client

-- Information acquired via protocol DNS in 23.1620s.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
-- Data from: network
archlinux.org: 2a01:4f9:c010:6b1f::1           -- link: wg0_client
               95.217.163.246                  -- link: wg0_client

-- Information acquired via protocol DNS in 5.1424s.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
-- Data from: network
bitbucket.org: 104.192.141.1                   -- link: wg0_client
               2406:da00:ff00::22c0:3470       -- link: wg0_client
               2406:da00:ff00::3403:4be7       -- link: wg0_client
               2406:da00:ff00::22cd:e0db       -- link: wg0_client
               2406:da00:ff00::22e9:9f55       -- link: wg0_client
               2406:da00:ff00::22c5:2ef4       -- link: wg0_client
               2406:da00:ff00::6b17:d1f5       -- link: wg0_client

-- Information acquired via protocol DNS in 3.1272s.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
-- Data from: network
gitlab.com: 172.65.251.78                      -- link: wg0_client
            2606:4700:90:0:f22e:fbec:5bed:a9b9 -- link: wg0_client

-- Information acquired via protocol DNS in 344.6ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
-- Data from: network
```

**Steps to reproduce the problem**
 > 1. Setup a Wireguard tunnel with NAT
 > 2. Redirect all traffic the the tunnel (VPN)
 > 3. About 1 DNS request out of 2 is slow to very, very slow (some seconds to 20+ seconds)

 > A note here: every other services: tunnels, SSH, HTTP, HTTPS, etc works well with my wireguard configuration. My own company use this exact same configuration as a VPN. If you want more details on that to figure out the issue, I can provide a client/server configuration.

**Additional program output to the terminal or log subsystem illustrating the issue**

 > Not sure exactly what I should look at to help debug this. Any suggestions?

**Comment by gui-don** [comment]
I did not hit this issue for quite a long time now, so I'm gonna consider it’s solved.
