### ISSUE TITLE
re-review #22587 and #23269

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#23676]
#22587 and #23269 were merged without approval. These needs to be reviewed before the next release.
Options.
1. review them and submit several follow-ups for the PRs.
2. once revert them, then re-submit and re-review them.

IIRC, #23269 was reviewed several times, hence, the option 1 can be taken for #23269.
I am not sure about #22587.

**Comment by topimiettinen** [comment]
Reverting may be tricky because of later commits like 2299b1cae, probably not impossible.

**Comment by topimiettinen** [comment]
Created #23712 for the fixes.
