### ISSUE TITLE
ConditionMemory does not support memory units (G / M / K)

### ISSUE THREAD

**Issue by thkoch2001** [systemd/systemd#23697]
I expected ConditionMemory and AssertMemory to support memory units like

    ConditionMemory=>1G

However systemd considers this illegal and thus I had to write

    ConditionMemory=>1000000000

(I don't care about 1024 vs. 1000 here.)

**Comment by keszybz** [comment]
Please specify the afflicted systemd version in the future, as the template requests. This makes it easier for us to figure out if the issue has been resolved already.
