### ISSUE TITLE
systemctl enable/preset should take over broken alias symlinks

### ISSUE THREAD

**Issue by rhertzog** [systemd/systemd#23694]
In Debian, when we remove a package, we are not disabling the service provided by that package, the "enablement state" of the service is kept along with the configuration files so that if you reinstall the package, you end up in the same state.

The downside to this is that when you have a service unit with an "Alias" directive, the symlink created for the aliased name also stays and becomes a broken symlink (because the underlying .service file has been removed from /usr/lib/systemd/).

This symlink is then causing issue when the same aliased name is reused by another service unit. For instance, when I try to switch from wireplumber to pipewire-media-session (or the opposite), I will get an error like this:

```
$ sudo systemctl enable --global pipewire-media-session.service 
Failed to enable unit, file "/etc/systemd/user/pipewire-session-manager.service" already exists and is a symlink to "/usr/lib/systemd/user/wireplumber.service".
```

I would like systemd to recognize that this symlink is broken and behave as if it didn't exist precisely because it's broken. I don't think that you would break backwards compatibility in any meaningful way with this change.

**Comment by yuwata** [comment]
Please provide version of systemd.

**Comment by yuwata** [comment]
We have fixed several issues in enabling/disabling units. Please try to v251 if you use older.

**Comment by rhertzog** [comment]
@yuwata Sorry that I forgot to mention the version, this was reproduced with version 251.2-2 (version in Debian unstable).
