### ISSUE TITLE
Unable to use luks.options for discovered partitions

### ISSUE THREAD

**Issue by Scrumplex** [systemd/systemd#23715]
**systemd version the issue has been seen with**
 > 251.2

**Used distribution**
 > Arch Linux (testing)

**Linux kernel version used** (`uname -a`)

 > `Linux doppler 5.18.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 09 Jun 2022 16:14:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > Setting `rd.luks.options=3121c3bd-f350-4b91-9468-7be3e63f71a4=fido2-device=auto` so that I can unlock my encrypted automatically discovered root partition using a FIDO2 key.

Alternatively:

 > Setting `rd.luks.options=verify` so that I need to enter my password twice.

**Unexpected behaviour you saw**
 > I couldn't find any reference that the options configured above were used to unlock the encrypted partition.

**Steps to reproduce the problem**
 > - Ensure that you are using discoverable partitions with a LUKS-encrypted rootfs
 > - Add `rd.luks.options=verify` to kernel cmdline
 > - Reboot and check if it asks you for your password twice

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
```

I can't find any meaningful logs. I think this is just not implemented with discovered partitions.

Searching for `luks.options` in this repository, I could only find it in https://github.com/systemd/systemd/blob/e99ca1474145f7fad38bb0255d344f4ad7717ef5/src/cryptsetup/cryptsetup-generator.c. There is no other reference as far as I can tell. I would assume that it would go somewhere into https://github.com/systemd/systemd/blob/24ccd953ba5af283d389e6f30150aeb6a154c8f9/src/gpt-auto-generator/gpt-auto-generator.c

**Comment by diabonas** [comment]
I think this should be fixed by #23511, though I only tested it with a TPM instead of a FIDO2 device. Therefore it would be much appreciated if you could test this pull request with your setup :)

**Comment by Scrumplex** [comment]
Yep. Applying your patch onto systemd-stable fixes this issue. Thanks!

**Comment by poettering** [comment]
yeah, it makes sense to honour the option string for auto-discovery cryptsetup volumes, indeed
