### ISSUE TITLE
udev: access systemd environment to set MAC address in .link files

### ISSUE THREAD

**Issue by sipraga** [systemd/systemd#23757]
**Is your feature request related to a problem? Please describe.**

Yes. We have an embedded device with an EEPROM storing `{ifname, macaddr}` key-value pairs. The network interfaces need their MAC address to be set to the appropriate value if it exists in the EEPROM. Currently, systemd's .link (udev) files are too rigid because the `MACAddress=` directive must be set statically in the file. Given that we have a read-only rootfs, this is not practical.

The solution we currently use is a .service file which runs a script which extracts the MAC address from the EEPROM and sets it with iproute2. This is slow and I feel like systemd could help make this easier.

**Describe the solution you'd like**

I would like to be able to do the following:
1. Create a systemd environment generator which handles the reading of our EEPROM data and adds to systemd's environment an environment variable of the form `MY_COOL_MACADDR_eth0=00:11:22:33:44:55` for each of the key-value pairs described above.
2. Be able to refer to this environment in a .link file, e.g.:
```
[Match]
Name=eth0

[Link]
MACAddress=$MY_COOL_MACADDR_eth0
```

This is just an outline. I am open to other suggestions for how to do this. I am willing to implement the functionality in systemd. First I want to get your thoughts on the suggestion and discuss alternative solutions. Thank you!

**Describe alternatives you've considered**

Maybe a systemd generator? But if I understand correctly, those are only for unit files. And given the restrictions of the generator environment, it seems a bit overkill just to generate some .link files. Especially if I want to put other unrelated stuff in my .link file.

**The systemd version you checked that didn't have the feature you are asking for**

v251

**Comment by yuwata** [comment]
Please try to create a udev rule. E.g.
```
# /etc/udev/rules.d/79-assign-mac.rules
SUBSYSTEM=="net", KERNEL=="eth0", ACTION=="add", PROGRAM="command to read EEPROM", ATTR{address}="$result"
```
And, set `MACAddressPolicy=none` for relevant .link file. E.g.
```
# /etc/systemd/network/99-default.link.d/10-disable-mac-policy.conf
[Link]
MACAddressPolicy=none
```

Reading a MAC address from an environment variable sounds not a good idea for me. Sorry. And here is not a support forum. Closing.
