### ISSUE TITLE
InvocationID missing in systemctl show output on manually started service

### ISSUE THREAD

**Issue by laped83** [systemd/systemd#23752]
**systemd version the issue has been seen with**
 > systemd 250 (v250.7-1.fc36)

**Used distribution**
 > Fedora 36

**Linux kernel version used** (`uname -a`)

> Linux laped 5.17.13-300.fc36.x86_64 #1 SMP PREEMPT Mon Jun 6 14:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Field InvocationID in systemctl show hello-world.service after service has run

**Unexpected behaviour you saw**
 > Missing InvocationID field in systemctl show hello-world.service after service has run

**Steps to reproduce the problem**
 > 1. Create file hello-world.service and put in /etc/systemd/system/
```
[Unit]
Description=Hello World Service

[Service]
Type=simple
ExecStart=bash -c 'echo "Hello world"'
```
> 2. systemctl daemon-reload
> 3. systemctl start hello-world.service
> 4. systemctl show hello-world.service (InvocationID missing)

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by dtardon** [comment]
I suspect this is because the unit has already finished and has been garbage-collected by the time you run `systemctl show`. Add `RemainAfterExit=yes` to ensure the unit remains loaded.
