### ISSUE TITLE
Please consider set TimeoutSec of rc-local.service to 30min

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#23768]
Some of our users may run scripts under `/etc/rc.local`. Sometimes the scripts may stuck in an infinite loop, then they can't login to system.
I'm wondering if we can set TimeoutSec to 30min. Killing the bad scripts is better than can't login.

**Comment by yuwata** [comment]
Unfortunately, rc-local is mostly deprecated, and we will not improve the situation about executing the script. Please consider to use normal service if you find an issue in existing script. Or, just fix your script.

Closing.
