### ISSUE TITLE
Systemd Crash

### ISSUE THREAD

**Issue by pawanbadganchi** [systemd/systemd#23761]
**systemd version the issue has been seen with**
 1_244.5

**Used distribution**
 Ubuntu

**Linux kernel version used** (`uname -a`)

 5.4.0-110-generic

**CPU architecture issue was seen on**
SA8155P Snapdragon processor

**Expected behaviour you didn't see**
 No crash should be observed.

**Unexpected behaviour you saw**
 Systemd crash  observed.

**Additional program output to the terminal or log subsystem illustrating the issue**

As per my analysis program is reading inaccessible memory location due to which program is terminated by SIGABRT signal i.e. segmenation fault.
In the below Backtrace in 11th frame, an array of buf variable is crossing it's boundary in the function manager_dispatch_notify_fd() due to which program is getting crash.

Backtrace:
**#0 0x00000072dbe0f848** in kill () at ../sysdeps/unix/syscall-template.S:120
No locals.
**#1 0x0000005763bb1674** in crash (sig=6) at ../git/src/core/main.c:216
sa = {__sigaction_handler =

{sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0,
sa_restorer = 0x0}
pid = <optimized out>
_func_ = "crash"
_PRETTY_FUNCTION_ = "crash"
**#2 <signal handler called>**
No symbol table info available.
**#3** __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
set = {__val = {8927191084203854339, 493318981716, 375977339032, 0, 549547950056, 8192, 377957122047, 0, 549547949928, 12,
549547949840, 1, 549547958248, 32, 0, 11996853159726153744}}
pid = <optimized out>
tid = <optimized out>
ret = <optimized out>
**#4 0x00000072dbdfcdd4** in __GI_abort () at abort.c:79
save_stage = 1
act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}
, sa_mask = {__val = {532575944823, 390842024046, 957000000, 0,
549547950320, 493315466396, 375979676624, 493316468784, 549547950464, 493315470292, 375979676624, 0, 549547950624,
493318981896, 549547950480, 493315453740}}, sa_flags = 4096, sa_restorer = 0x72dc1b48d0 <path_compare+252>}
sigs = {__val = {32, 0 <repeats 15 times>}}
**#5 0x00000072dbe472b4** in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x72dbf01590 "%s\n")
at ../sysdeps/posix/libc_fatal.c:155
ap = {__stack = 0x7ff39c4230, __gr_top = 0x7ff39c4230, __vr_top = 0x7ff39c4200, __gr_offs = -40, __vr_offs = 0}
fd = <optimized out>
list = <optimized out>
nlist = <optimized out>
cp = <optimized out>
**#6 0x00000072dbe4e51c** in malloc_printerr (str=str@entry=0x72dbefd0a0 "free(): invalid pointer") at malloc.c:5347
No locals.
**#7 0x00000072dbe4fcdc** in _int_free (av=0x72dbf3da28 <main_arena>, p=0x5789fee850, have_lock=<optimized out>) at malloc.c:4173
size = 0
fb = <optimized out>
nextchunk = <optimized out>
nextsize = <optimized out>
nextinuse = <optimized out>
-Type <RET> for more, q to quit, c to continue without paging-
prevsize = <optimized out>
bck = <optimized out>
fwd = <optimized out>
_PRETTY_FUNCTION_ = "_int_free"
**#8 0x0000005763c24dc8** in manager_get_unit_by_pid_cgroup (m=<optimized out>, pid=<optimized out>) at ../git/src/basic/process-util.h:139
cgroup = 0x0
_PRETTY_FUNCTION_ = "manager_get_unit_by_pid_cgroup"
**#9 0x0000005763be5194** in manager_dispatch_notify_fd (source=<optimized out>, fd=<optimized out>, revents=<optimized out>,
userdata=0x2a48a5125c97d300) at ../git/src/core/manager.c:2423
fds = 0x0
m = 0x2a48a5125c97d300
buf = '\000' <repeats 32 times>, "WATCHDOG=1\000\000ice.d\000\000\000\000\000\000\000p\003\070\212W\000\000\000PQ\234\363\177\000\000\000 \363\024\334r", '\000' <repeats 11 times>, "\001\000\000\000\000\000\000\000PQ\234\363\177\000\000\000\230\357\024\334r", '\000' <repeats 19 times>, "p\353\376\211W\000\000\000\200\214\377\211W\000\000\000\203i\306cW", '\000' <repeats 11 times>, "\353\345$\334r\000\000\000\000\360,\334r", '\000' <repeats 11 times>, "\320j@\212W", '\000' <repeats 11 times>...
iovec =

{iov_base = 0x3df63, iov_len = 18446743528248705000}
control = {cmsghdr =

{cmsg_len = 1, cmsg_level = -207862784, cmsg_type = 127, __cmsg_data = 0x7ff39c43f0 " "}
,
buf = "\001\000\000\000\000\000\000\000\000D\234\363\177\000\000\000 \000\000\000\000\000\000\000\000\000\000@\000\000\000\000\034\000\000\000\000\000\000\000\001\000\000\000\002\000\000\000\226\003\000\000\313\024=\000\313\024=", '\000' <repeats 3060 times>}
msghdr =

{msg_name = 0x0, msg_namelen = 0, msg_iov = 0x7ff39c5030, msg_iovlen = 4096, msg_control = 0x0, msg_controllen = 0, msg_flags = -207862856}
cmsg = 0x0
ucred = 0x7ff39c4340
array_copy = 0x5763c58482
u1 = 0x0
u2 = 0xa
array = <optimized out>
r = <optimized out>
fd_array = <optimized out>
n_fds = <optimized out>
found = <optimized out>
n = <optimized out>
_PRETTY_FUNCTION_ = "manager_dispatch_notify_fd"
_func_ = "manager_dispatch_notify_fd"
**#10 0x0000005763be511c** in hashmap_get (key=<optimized out>, h=<optimized out>) at ../git/src/basic/hashmap.h:164
No locals.
**#11** manager_dispatch_notify_fd (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x2a48a5125c97d300)
-Type <RET> for more, q to quit, c to continue without paging-
at ../git/src/core/manager.c:2405
fds = 0x0
m = 0x2a48a5125c97d300
buf = <error reading variable buf (Cannot access memory at address 0x7ff39c7000)>
iovec =

{iov_base = 0x72ffffffff, iov_len = 0}
control = {cmsghdr =

{cmsg_len = 549547958576, cmsg_level = 1673442160, cmsg_type = 87, __cmsg_data = 0x7ff39c60f0 "\260\253\375\211W"}
,
buf = "0a\234\363\177\000\000\000p\263\276cW\000\000\000\260\253\375\211W", '\000' <repeats 12 times>, "\020\316cW", '\000' <repeats 11 times>, "\250\331\070\212W\000\000\000\202\204\305cW\000\000\000\340a\234\363\177\000\000\000\360\377\377\377\200\377\377\377\000b\234\363\177\000\000\000\370\350\272cW", '\000' <repeats 12 times>, "\220\304cW\000\000\000\223\224\304cW\000\000\000\001\000\000\000\000\000\000\000\be\234\363\177\000\000\000\000 \316cW\000\000\000\260\253\375\211W\000\000\000\020c\234\363\177\000\000\000 c\234\363\177\000\000\000\060c\234\363\177\000\000\000\255\204\305cW\000\000\000\000\377\000\000\000\000\377\000\000\000\000\000\000\000\000\000"...}
msghdr =

{msg_name = 0x2a48a5125c97d300, msg_namelen = 4087111904, msg_iov = 0x72dc226998 <sd_event_run+408>, msg_iovlen = 375977262720, msg_control = 0x1, msg_controllen = 5000000, msg_flags = 1553453824}
cmsg = 0x0
ucred = 0x7ff39c6040
array_copy = 0x0
u1 = 0x72dc2cf000 <truncate_nl@got.plt>
u2 = 0x1
array = <optimized out>
r = <optimized out>
fd_array = <optimized out>
n_fds = <optimized out>
found = false
n = <optimized out>
_PRETTY_FUNCTION_ = "manager_dispatch_notify_fd"
_func_ = "manager_dispatch_notify_fd"
**#12 0x0000000000000001** in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

…
```

**Comment by yuwata** [comment]
Sorry, v244 is too old here. Closing.
Feel free to request to reopen this if you reproduce the issue with recent releases or current git HEAD.
