### ISSUE TITLE
Need dbus.socket to have no default dependencies

### ISSUE THREAD

**Issue by franksinankaya** [systemd/systemd#23763]
We have a critical networking related early boot service that uses dbus and have a dependency placed on dbus.socket,
During performance analysis, we noticed that our service is starting late due to default dependencies like sysinit.target injected into our service via dbus.socket. Therefore, we are missing our requirements.

before:
-dbus.socket @3.417s
-sysinit.target @3.415s
-cryptsetup.target @3.414s
-systemd-ask-password-wall.path @358ms
--.mount @339ms--.slice @339ms

We are able to resolve this issue if we inject DefaultDependencies=No into dbus.socket similar to all other socket entries started during boot.
![image](https://user-images.githubusercontent.com/41809318/174082254-4c482206-b572-4214-ad89-e9409b0a3c43.png)

after:
`-sys-devices-platform-xyz @742ms

Now, we are questioning the correctness of this approach and if this is something we could contribute upstream. I was going to send a pull request but I noticed I cannot locate dbus.socket file anymore.

cc: @bluca

**Comment by franksinankaya** [comment]
cross referencing: https://gitlab.freedesktop.org/franksinankaya/dbus/-/merge_requests/1

**Comment by yuwata** [comment]
The unit is not provided by us. Closing.

**Comment by smcv** [comment]
I would appreciate advice from systemd experts on whether https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/321 is appropriate as an upstream default, or whether it is something that only makes sense on tightly-controlled embedded platforms.
