### ISSUE TITLE
Timer triggered out of specyfic hours

### ISSUE THREAD

**Issue by EdiDD** [systemd/systemd#23760]
**systemd version the issue has been seen with**
 > 250.4-1

**Used distribution**
 > Raspberry Pi OS

**Linux kernel version used** (`uname -a`)

 > 5.15.32-v8+

**CPU architecture issue was seen on**
 > arm64

**Expected behaviour you didn't see**
 > [Timer]
OnCalendar=08..20:*

Should not be triggered after 21:00 and before 08:*

**Unexpected behaviour you saw**
 > Active: inactive (dead) since Thu 2022-06-16 01:00:16 CEST

Timer was triggered after 01:00 and it launched corresponding service. 

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by mbiebl** [comment]
I think what you are seeing here is that the timer was activated/started at `01:00:16 CEST`, not that it was triggered.

Can you show the journal log of the corresponding .service file?

**Comment by EdiDD** [comment]
Unfortunately it was not the case. In journal log there is  `Starting test1.service..` on the same hour as timer triggered.

**Comment by mbiebl** [comment]
Please post the full timer unit and the complete journal log of the timer and service unit

**Comment by EdiDD** [comment]
timer:
```
[Timer]
OnCalendar=08..20:*
Persistent=true
```

service:
```
[Unit]
Conflicts=test1.timer

[Service]
Type=oneshot
ExecStart=/path/to/script.sh
```

Timer is triggered by:

```
[Path]
PathModified=/path/to/file
Unit=test1.timer

[Install]
WantedBy=default.target
```
I don't want the timer is triggering the service within 21-08

**Comment by mbiebl** [comment]
I suppose your system was offline for a while and `Persistent=true` caused the timer to trigger.
See its man page:
```
       Persistent=
           Takes a boolean argument. If true, the time when the service unit was last triggered is stored on disk. When the
           timer is activated, the service unit is triggered immediately if it would have been triggered at least once during
           the time when the timer was inactive. 
```

**Comment by EdiDD** [comment]
No. It was not. `uptime`:
10:44:21 up 27 days, 22:47,  2 users,  load average: 0.82, 0.81, 0.82

**Comment by EdiDD** [comment]
Why you closed not resolved issue ? Even with persistent it should not be triggered.

**Comment by yuwata** [comment]
If the timer unit is not active during 08-21, and the path unit is triggered during 21-08, then Persistent= option makes the timer unit triggers the service. This should not be a bug.

Or, if you think this is really a bug, then please provide related logs.
