### ISSUE TITLE
Ctrl+C in `machinectl shell` interrupts X session

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#2377]
- Boot to GDM
- Log in to GNOME
- Start GNOME Terminal
- Run `machinectl shell`
- Enter password in polkit prompt
- Press Ctrl+C in started shell

→ X session gets killed by SIGINT

**Comment by poettering** [comment]
This is most like the same issue as #2198...

**Comment by heftig** [comment]
Yes, most likely.

**Comment by poettering** [comment]
Fix waiting in #2463
