### ISSUE TITLE
BindPaths= creating empty file outside of unit's filesystem

### ISSUE THREAD

**Issue by cedws** [systemd/systemd#23772]
**systemd version the issue has been seen with**
 > systemd 249 (249.11-0ubuntu3.1)

**Used distribution**
 > Ubuntu 22.04

**Linux kernel version used** (`uname -a`)

 > `5.15.0-37-generic`

**CPU architecture issue was seen on**
 > `aarch64`

**Expected behaviour you didn't see**
N/A

**Unexpected behaviour you saw**
According to [the documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#BindPaths=) for `BindPaths=` and `BindReadOnlyPaths=`, the destination path should only be visible to the unit. I'm using `BindPaths=` to mount a file to a specific location for the unit. While the actual file contents are only visible to the unit, systemd is for some reason creating an empty file at the destination path outside of the unit's filesystem.

**Steps to reproduce the problem**
1. Create the source file:
```
# echo hello > /tmp/test
```

2. Run this command:
```
# systemd-run --property=BindPaths=/tmp/test:/x true
```

3. Observe `/x` has been created but is empty:
```
# cat /x
```

**Additional program output to the terminal or log subsystem illustrating the issue**
N/A

**Comment by bluca** [comment]
A mount point is necessary, that's just how bind mounts work on Linux, if you don't want that you'll need to create it only in private tmpfs

**Comment by yuwata** [comment]
Hm? The report is about `/x` is created on host environment. Is it desired??

**Comment by bluca** [comment]
Where else would it be created? It's a mount point, it has to exist

**Comment by yuwata** [comment]
Sorry, I was confused.

**Comment by cedws** [comment]
Couldn't the empty file be created inside the unit's filesystem instead?

**Comment by bluca** [comment]
no, there's no such thing
