### ISSUE TITLE
 kexec reboot fails and reboots in normal cold boot way

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#23781]
**systemd version the issue has been seen with**
 > …
243.2+ version

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …
Hi,
In  systemd 243.2+ version, intermittently sometimes I see that 'systemctl kexec' does not result in kexec reboot but results in reguler cold boot reboot
In console logs, I see below logs.
At line#209, I see "FAIL" string but not sure where it is coming from.
In which cases do 'systemctl kexec' can fail and result in non-kexec reguler reboot?

 185 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/data/var/home/root/.ssh^[[0m.^M
 186 2022-06-13 13:56:18 [^[[0;1;31mFAILED^[[0m] Failed unmounting ^[[0;1;39m/etc^[[0m.^M
 187 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/soft/uswitch^[[0m.^M
 188 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmo[ 1130.272883] systemd-shutdown[1]: Could not deactivate swap /sda3: Transport endpoint is not
     connected^M
 189 2022-06-13 13:56:18 unted ^[[0;1;39m/u^[[0m.^M
 190 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/usr/conf^[[0m.^M
 191 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/usr/evo/share^[[0m.^M
 192 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/uswitch/data/var/external^[[0m.^M
 193 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/uswitch/dev^[[0m.^M
 194 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/uswitch/proc^[[0m.^M
 195 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/uswitch/soft^[[0m.^M
 196 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/uswitch/tmp^[[0m.^M
 197 2022-06-13 13:56:18 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/var/db^[[0m.^M
 198 2022-06-13 13:56:19 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/var/etc^[[0m.^M
 199 2022-06-13 13:56:19 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/var/pfe^[[0m.^M
 200 2022-06-13 13:56:19 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39m/var/rundb^[[0m.^M
 201 2022-06-13 13:56:19 [^[[0;32m  OK  ^[[0m] Unmounted ^[[0;1;39mTemporary Directory (/tmp)^[[0m.^M
 202 2022-06-13 13:56:19 [^[[0;32m  OK  ^[[0m] Stopped target ^[[0;1;39mSwap^[[0m.^M
 203 2022-06-13 13:56:19          Deactivating swap ^[[0;1;39m/sda3^[[0m...^M
 204 2022-06-13 13:56:19          Unmounting ^[[0;1;39m/data/var^[[0m...^M
 205 2022-06-13 13:56:19          Unmounting ^[[0;1;39m/soft^[[0m...^M
 206 2022-06-13 13:56:19          Unmounting ^[[0;1;39m/uswitch/data/var^[[0m...^M
 207 2022-06-13 13:56:19          Unmounting ^[[0;1;39m/var^[[0m...[ 1131.454830] reboot: Restarting system^M
 208 2022-06-13 13:56:19 ^M
 209 2022-06-13 13:56:19 [^[[0;1;31mFAIL^[c^M
 210 2022-06-13 13:56:19 Booting from Flash A^M
 211 2022-06-13 13:56:19 ^M
 212 2022-06-13 13:56:19 FPGA Reset Reason = 0x80^M
 213 2022-06-13 13:56:19 ^M
 214 2022-06-13 13:56:20 Primary BIOS version CBDE_P_LIG0_00.25.1^M

Thanks
**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by yuwata** [comment]
Sorry, v243 is too old here. Please try to reproduce the issue with recent releases (v250 or v251) or the current git HEAD.
Or please contact to your distro. Closing.

Feel free to request to reopen this page if you reproduce the issue with recent releases.
