### ISSUE TITLE
mount unit prefix What= (device) with slash when it appears to exist on the local filesystem

### ISSUE THREAD

**Issue by wdoekes** [systemd/systemd#23795]
**systemd version the issue has been seen with**

> 245.4-4ubuntu3.17 (on Ubuntu/Focal)

I did scan the source code and issues for related stuff, but did not see anything obvious.

**Expected behaviour you didn't see**

The `What=` from the mount point should not start with a slash when I do not supply any.

**Unexpected behaviour you saw**

The `What=` from the mount point starts with a slash when the `Where=` starts with the `What=`.

See these examples:

[1]
```
# systemctl show example.mount | grep -E 'What|Where'
Where=/example
What=example
```
```
# journalctl -o cat -q -u example.mount -t mount
GOT ARGS /example /example -o rw
```
[2]
```
# systemctl show example2.mount | grep -E 'What|Where'
Where=/example2
What=example
```
```
# journalctl -o cat -q -u example2.mount -t mount
GOT ARGS /example /example2 -o rw
```
[3]
```
# systemctl show example3.mount | grep -E 'What|Where'
Where=/example3
What=other_example
```
```
# journalctl -o cat -q -u example3.mount -t mount
GOT ARGS other_example /example3 -o rw
```
[4]
```
# systemctl show example4.mount | grep -E 'What|Where'
Where=/example4
What=exoplanet
```
```
# journalctl -o cat -q -u example4.mount -t mount
GOT ARGS exoplanet /example4 -o rw
```

Observe the args:
```
GOT ARGS /example /example -o rw
GOT ARGS /example /example2 -o rw
GOT ARGS other_example /example3 -o rw
GOT ARGS exoplanet /example4 -o rw
```
The first two start with a leading slash, the others don't.

I expect no `/` when I have no `/` in `What=`.

This behaviour conflicts with my ZFS mount scripts [5], which use a custom mount script. ZFS filesystems do not start with a leading slash, and this unexpected behaviour breaks them when the paths are similar (e.g. mounting `tank/somewhere` on `/tank/somewhere`).

[5] https://github.com/ossobv/vcutil/blob/main/mount.zfs-non-legacy

**Steps to reproduce the problem**

I added a sample `/usr/sbin/mount.echo` to show the behaviour:
```bash
#!/bin/sh
echo "GOT ARGS $*" >&2
exit 1
```

If you add this mount unit file as `/etc/systemd/system/example.mount`, you'll see the behaviour in action:
```
[Mount]
Type=echo
What=example
```
Alter the `What` per the description above. Change it to `exoplanet` and we get correct behaviour without a leading `/`.

--

I'm sorry if this has been fixed already. If so, I couldn't find it in the changes. I'll happily file a report at Ubuntu if there is a changeset I can point to.

Cheers,
Walter Doekes
OSSO B.V.

**Comment by poettering** [comment]
We normalize all source paths, since we need to generate deps from them. We do so for all block-based fs. Is zfs not block device based?

**Comment by wdoekes** [comment]
> Is zfs not block device based?

Not sure what answer you are looking for here.

ZFS provides zvols and datasets. A zvol would be a block device which you can format which whatever filesystem you want. A dataset is a filesystem which descends from a zpool.

The dataset names do _not_ start with a slash:
```
# zpool list -o name
NAME
rpool
zl-pve1-nvme1
```
^- zpools

```
# zfs list rpool -r -o name,mountpoint,type
NAME              MOUNTPOINT   TYPE
rpool             /rpool       filesystem
rpool/ROOT        /rpool/ROOT  filesystem
rpool/ROOT/pve-1  /            filesystem
rpool/data        /rpool/data  filesystem
```
^- datasets (filesystems) below `rpool`

```
# mount | grep ' on / '
rpool/ROOT/pve-1 on / type zfs (rw,relatime,xattr,noacl)
```
^- the mounted root fs (which has a name that does not start with a slash)

> We normalize all source paths, since we need to generate deps from them.

If _all_ paths were normalized, I'd expect every one of them to include a leading slash. The odd behaviour arises in that only some paths get a slash prepended: `exoplanet` did not get a slash prepended, while `example` did.

Also: the source "path" is not a path, but a "zpool dataset name" ( https://docs.oracle.com/cd/E26505_01/html/E37384/gbcpt.html ). Mutating this name by prefixing it with a slash causes the name to become invalid:

```
# zfs mount /rpool/ROOT/pve-1
cannot open '/rpool/ROOT/pve-1': leading slash in name
```
.. or, if it used a (so called) legacy mountpoint:
```
# mount -t zfs /rpool/ROOT/pve-1 /mnt/
filesystem '/rpool/ROOT/pve-1' cannot be mounted, unable to open the dataset
```

_Perhaps answering your question somewhat: the order/depth of the mounts is not necessarily the same as the source name._

As seen above, `rpool/ROOT/pve-1` is mounted on `/`, while its grandparent (`rpool`) is mounted on `/rpool`.

**Comment by wdoekes** [comment]
Okay. The following may have been obvious to you, but wasn't to me: the root cause is indeed the normalization _that only occurs when the paths appear to exist on the local filesystem_.

```
# cat mnt-test.mount 
[Unit]
Documentation=https://github.com/systemd/systemd/issues/23795

[Mount]
Type=echo
# 1
What=dev/null
# 2
#What=dev/null2
```
Results in:
```
# journalctl -o cat -q -u mnt-test.mount  -t mount
GOT ARGS /dev/null /mnt/test -o rw
GOT ARGS dev/null2 /mnt/test -o rw
```
**`dev/null` exists as `/dev/null`, so it gets a slash prepended to it. `dev/null2` does not exist, so it is untouched.**

But for ZFS mounts, these handles should be treated opaquely: they have _no relation_ to the existing mount point structure of the target filesystem.

As additional observation, _mount(8)_ mentions:
> Most devices are indicated by a filename (of a block special device), like /dev/sda1, but there are other possibilities.  _For example, in the case of an NFS mount, device may look like **knuth.cwi.nl:/dir**._

That example also breaks if that directory happens to exists:
```
# systemctl start mnt-nfs-knuth.mount
# journalctl -o cat -q -u mnt-nfs-knuth.mount -t mount
GOT ARGS knuth.cwi.nl:/dir /mnt/nfs/knuth -o rw
```
^- good
```
# mkdir -p /knuth.cwi.nl:/dir
# systemctl start mnt-nfs-knuth.mount
# journalctl -o cat -q -u mnt-nfs-knuth.mount -t mount
GOT ARGS /knuth.cwi.nl:/dir /mnt/nfs/knuth -o rw
```
^- bad

That confirms my stance that these source devices should be treated as opaque handles and no "normalization" should occur (unless one is 100% sure we're dealing with local paths, but even then I wonder if it is ever needed).

Another observation: `LABEL=`/`UUID=`/`PARTUUID=` "devices" are untouched. Creating `/LABEL=..` did not break things. That leads me to believe that `fstab_node_to_udev_node` is called (although I'm not seeing from where). But this is in line with mount(8) behaviour, which expands it before passing it to the mount-helper anyway.

**Comment by yuwata** [comment]
Prefixing with slash is not done by systemd, but by the `mount` command. Please try to run the following:
```
$ su -
# mkdir /foo
# cd /
# mount -o bind tmp /foo # this will mount /tmp on /foo
# cd /home
# mount -o bind tmp /foo
mount: /foo: special device tmp does not exist. <-- Yay!
```
systemd invoke mount option with `CWD=/`, hence your What=dev/null works, but What=/dev/null2 does not work.
