### ISSUE TITLE
Possible dead code in src/resolve/resolved-dns-packet.c

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#2380]
This was reported by last Coverity run and to me it seems like a real bug. However, I am maybe missing something, so instead of submitting PR I'd rather discuss the problem first. Also it doesn't seem to me that getting rid of the dead code is really the proper fix.

On line `src/resolve/resolved-dns-packet.c:2097` we set `DnsResourceRecord *previous = NULL;` and then on line `src/resolve/resolved-dns-packet.c:2115` we test if previous is `true` and if so then we call `dns_resource_key_reduce(&rr->key, &previous->key);`. 
But `previous` pointer is initially set to `NULL` and it is not used anywhere except the true branch of the if statement. Thus it can never have other than its initial value which is `NULL`. Thus the code annotated with comment `/* Try to reduce memory usage a bit */` is never called.

**Comment by poettering** [comment]
Indeed! There's a "previous = rr" missing. Will prep a fix!
