### ISSUE TITLE
 `sd_event_prepare()` fails to consider buffered inotify events

### ISSUE THREAD

**Issue by allisonkarlitskaya** [systemd/systemd#23826]
### systemd version the issue has been seen with

250

### Used distribution

Fedora 36

### Linux kernel version used

5.18.5-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

When there are pending inotify events (in the `inotify_data_buffered` of the event loop) then `sd_event_prepare()` ought to return non-zero and transition the loop to `SD_EVENT_PENDING`.

### Unexpected behaviour you saw

`sd_event_prepare()` returns `0` and the event loop is armed, instead.

### Steps to reproduce the problem

The issue appears to be related to the special treatment of `inotify_data_buffered` in `process_epoll()` in `sd-event.c`.  In particular, it sets the timeout to 0 in case there is buffered data:

```
          /* If we still have inotify data buffered, then query the other fds, but don't wait on it */
          if (e->inotify_data_buffered)
                  timeout = 0;
```

There's no way to know this when trying to iterate the loop from outside, though, and there's no equivalent check in `sd_event_prepare()`.  That allows things to function normally when systemd is driving the loop, but not when trying to drive it from outside.  This issue therefore also affects the example "glib glue" code in `man/glib-event-glue.c`.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #23827.
