### ISSUE TITLE
test, ci: disable debian/ubuntu specific hostname, locale, and timedate tests

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#23847]
debian/ubuntu specific tests for hostnamed, localed, and timedated are imported to upstream.
Let's disable the original tests from the ubuntu and debian CIs.

Note, logind test is also imported to upstream. But several sub tests in it require qemu, but ubuntu CI sets TEST_PREFER_NSPAWN=1, and they are skipped.

cc @martinpitt @bluca @mbiebl

**Comment by mbiebl** [comment]
One important difference is that those tests currently have `isolation-container`, i.e. they can run on LXC as used by Debian CI.
By importing them into upstream, they now require `isolation-machine`, i.e. they can no longer run on Debian CI.

**Comment by bluca** [comment]
Yeah, we need to keep them. The environment is also completely different from the Debian autopkgtest, so there's no guarantee the result would be the same.

**Comment by yuwata** [comment]
Thanks. Interesting. Feel free to close this page if that should not happen.

**Comment by martinpitt** [comment]
Agreeing with @mbiebl , and also Debian/Ubuntu have some persistent patches to adjust for some distro quirks -- these need to run downstream, so it would be good to ensure that they at least keep running in "upstream" mode. Also, these three are really quick (1:50 mins together), so shouldn't get much in the way? The heavy ones are boot-and-services and boot-smoke, but these are also the ones that helped us to find the trickier bugs.

**Comment by yuwata** [comment]
Thanks. OK, let's close this.
