### ISSUE TITLE
resolvectl: segfault when resolving mDNS service

### ISSUE THREAD

**Issue by vchillara** [systemd/systemd#23843]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 35

### Linux kernel version used

5.15.18-200.fc35.x86_64

### CPU architectures issue was seen on

x86_64

### Component

resolvectl, systemd-resolved

### Expected behaviour you didn't see

Resolved service data

### Unexpected behaviour you saw

systemd-resolved occasionally runs into a segfault when trying to resolve an mDNS service via resolvectl.

resolvectl output:

> Resolve call failed: Remote peer disconnected

systemd-resolved logs:

> Jun 03 11:53:31 image systemd-resolved[28]: enp0s3: Bus client set MulticastDNS setting: yes
Jun 03 11:53:37 image systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=11/SEGV
Jun 03 11:53:37 image systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.

### Steps to reproduce the problem

1. Run systemd-resolve --set-mdns=yes --interface=enp0s3
2. Run resolvectl --type=SRV service XStream_Smart_Box_00-xxxxx._googlecast._tcp.local
   "xxxxx" being a 16-byte ID

**Comment by yuwata** [comment]
Could you provide the result of the coredump in the journal or `coredumpctl`? If it does not provide enough information, then please install debug symbols of systemd.

**Comment by vchillara** [comment]
I was able to get [this coredump](https://github.com/systemd/systemd/files/9000396/resolve-coredump.txt) output.
Here's part of the stack trace translated to file/line number:
#&#x2060;0  0x0000000000478622 n/a (/usr/lib/systemd/systemd-resolved + 0x78622) [src/resolve/resolved-dns-rr.c:216]
#&#x2060;1  0x000000000047f2cf n/a (/usr/lib/systemd/systemd-resolved + 0x7f2cf) [src/resolve/resolved-dns-answer.c:279]
#&#x2060;2  0x000000000046032f n/a (/usr/lib/systemd/systemd-resolved + 0x6032f) [src/resolve/resolved-mdns.c:414]

I built from source (tags/v251; #b622e95f2f59fcb58e23ddafed745eee26a0f52f) and used the mkosi image for testing.

**Comment by evverx** [comment]
It could be that https://github.com/systemd/systemd/issues/23873 is the same issue.
