### ISSUE TITLE
`systemd-analyze blame` compacting/filtering

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#23852]
### Component

systemd-analyze

### Is your feature request related to a problem? Please describe

https://github.com/systemd/systemd/issues/23629#issuecomment-1168029454 mentions that systemd v251 now parses devices differently which causes multiple variations of the same device to show up in `systemd-analyze blame`, these duplicate devices do actually have timespans which is why they're displayed, but, to end-users these devices take a large portion of the list and provide little extra value when diagnosing.

### Describe the solution you'd like

For some output such as:

```
1.567s dev-ttyS18.device
1.566s sys-devices-platform-serial8250-tty-ttyS18.device
...
1.295s dev-disk-by\x2dpartlabel-Linux\x5cx20filesystem.device
1.295s dev-disk-by\x2did-nvme\x2dDEVICE_NAME_HERE\x2dpart2.device
1.294s dev-disk-by\x2dpartuuid-d69ecf54\x2d51a3\x2d43f5\x2d8530\x2dedcb7b8cbdbe.device
1.294s dev-disk-by\x2dlabel-root.device
1.293s dev-disk-by\x2did-nvme\x2deui.0025385b71b2df55\x2dpart2.device
1.293s dev-disk-by\x2duuid-8f63d4f6\x2d5bba\x2d40ae\x2da560\x2ddbd557f765ad.device
1.292s dev-nvme0n1p2.device
1.292s dev-disk-by\x2dpath-pci\x2d0000:01:00.0\x2dnvme\x2d1\x2dpart2.device
1.291s sys-devices-pci0000:00-0000:00:01.1-0000:01:00.0-nvme-nvme0-nvme0n1-nvme0n1p2.device
```

Compact it to:

```
1.567s dev-ttyS18.device
...
1.295s dev-nvme0n1p2.device
```

Instead of showing multiple entries, show just `dev-*.device`, but, use the timespan from the last device. This ensures the timespan is still accurate for all devices, but, without showing all the devices at once. To enable the current behaviour, an `--all-devices` flag could be introduced for when individual devices are desired.

### Describe alternatives you've considered

Introduce something like `--output devices|mounts|services` to narrow the output of `systemd-analyze blame`, this could be more advantageous for parsing by scripts and also means the new behaviour isn't changed by default.

### The systemd version you checked that didn't have the feature you are asking for

251.2-1

**Comment by yuwata** [comment]
As commented at #23629, systemd-analyze is a debugging tool for systemd. I do not think we should optimize the output.
Someone may be interested in dev-disk-by\x2dpartlabel-xxx.device, but another may in dev-sda.device. There is no generic way to optimize the output, I think.

**Comment by Winterhuman** [comment]
It is a debugging tool, but, a lot of regular users use it to measure boot times so it ends up having a dual purpose in practice; OS wiki's often mention `systemd-analyze blame` as a benchmarking-like tool: https://wiki.archlinux.org/title/Tweaking_for_a_faster_boot_time

Agreed that device compacting probably isn't a viable solution, `--output` is likely the way to go out of the two proposed solutions.

**Comment by Winterhuman** [comment]
I honestly don't have any argument against the `grep` idea, it's technically longer to type and thus less convenient, but I doubt that really justifies it. The only way I could see `--output` still being useful is if it could narrow down the output based on things that aren't `grep`-able, but, I don't know what information that could be

**Comment by Winterhuman** [comment]
I haven't been able to think of any information that `--output` could filter which isn't covered by `grep`. Closing
