### ISSUE TITLE
make systemctl exit when using --wait and SIGHUP is received

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#23854]
### Component

systemctl

### Is your feature request related to a problem? Please describe

What I do is starting a unit like in:
```
systemctl --wait start tigervncserver@:5.service
```
This in turn is executed remotely via ssh, and I set `trap`s in the (remote) shell to catch `EXIT`, `INT` and `HUP`.

On `EXIT` the service stopped via `systemctl`, on `INT` the shell is `exit`ed (causing the `EXIT` handler to kick in, too) and on `HUP` the other signals are reset to their defaults and the shell is `exit`ed, too.

This, with some extra `ssh` options gives the following nice behaviour.
`ssh`ing to the remote server starts the service (here, some VNC server), Ctrl-C cleanly stops it and exits the remote command, but if `ssh` dies some other way (e.g. network lost, `SIGKILL`, etc.), which causes only the `SIGHUP` remotely, the service doesn't get stopped (it' wasn't an "intentional" shutdown).

On `SIGHUP` the other signals are reset so that it doesn't cause the service stop.

Now the problem is that this doesn't work with `systemctl` and `--wait`, cause, I guess, because it ignores `SIGHUP`.

What I do right now (which works but is less nice) is:
```
systemctl start tigervncserver@:5.service
while true; do sleep 60; done
```
the `sleep` exits every 60 s and then the HUP gets processed.

### Describe the solution you'd like

Perhaps `systemctl` could exit when using `--wait` and `SIGHUP` is received.

Not sure whether this has some bad effects on other use cases, so perhaps this could be added with an extra option?

### The systemd version you checked that didn't have the feature you are asking for

251.2

**Comment by poettering** [comment]
Not sure I follow. Do you just want systemctl to exit on SIGHUP? (if it doesn't do that, it would be a bug, I guess)

Or do you want that when systemctl gets a SIGHUP it first undoes the the "start" it was run for, and then exits? (that would be a new feature request)

**Comment by calestyo** [comment]
I think I made a wrong assumption in how the signals are received by the remote processes, and `systemctl` actually does already quit on `HUP`.

Sorry for the noise. Closing.

**Comment by calestyo** [comment]
Hmm I checked again, and maybe closing this was a bit premature.

When I have an interactive shell on the node and use `systemctl` with `-wait` and then send `HUP` to that, it actually quits, as expected.

What I do however is the following via `ssh`:
```
RequestTTY                      force
RemoteCommand                   displaynumber=5; trap 'echo "$(date) HUP" >> /tmp/clog; trap - EXIT INT TERM QUIT; exit 0' HUP; trap 'echo "$(date) INT-TERM-QUIT" >> /tmp/clog; exit 0' INT TERM QUIT; trap "echo \"$(date) EXIT\" >> /tmp/clog; systemctl stop 'tigervncserver@:${displaynumber}.service'; systemctl --quiet is-active 'tigervncserver@:${displaynumber}.service'; [ \"\$?\" -ne 3 ] && printf '\n%%sWarning: The VNC server may not be (cleanly) stopped.%%s\n' \"\$(tput setaf 3 2>/dev/null)\" \"\$(tput sgr0 2>/dev/null)\" >&2; exit 0" EXIT; systemctl start "tigervncserver@:${displaynumber}.service" && printf '%%sVNC server started.%%s\n' "$(tput setaf 2 2>/dev/null)" "$(tput sgr0 2>/dev/null)" >&2; echo before wait; systemctl --wait start "tigervncserver@:${displaynumber}.service"; echo after wait >> /tmp/clog; exit 0
```
(with some debugging output).

That works fine when I don't use `systemctl --wait start "tigervncserver@:${displaynumber}.service"; echo after wait >> /tmp/clog; exit 0` but something like `while true; do sleep 5; systemctl --quiet is-active "tigervncserver@:${displaynumber}.service" || exit 0; done`.

But with the above (with `--wait`), when I kill the SSH connection (which causes a `HUP`), neither the remote shell command receives the signal (despite the `trap` on it), nor `systemctl --wait` seem to do so, cause it doesn't exit, and `after wait` doesn't get printed.

**Comment by poettering** [comment]
but what does that have to do with systemd? systemctl can't react on any signal it doesn't even get.

Figure out why the signal is not sent to the process, but that has nothing to do with systemd, has it?
