### ISSUE TITLE
Polkit does not propagate permissions to `systemd-sysv-install`

### ISSUE THREAD

**Issue by jerome-pouiller** [systemd/systemd#23861]
### systemd version the issue has been seen with

251.2

### Used distribution

Debian Bookworm

### Linux kernel version used

5.18

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When the user start `systemctl` without the root permissions, PolKit is used to get the `root` permission.

In the case the target service is a SysV service, systemctl will run `systemd-sysv-install`. `systemd-sysv-install` should be launched with the root permissions.

### Unexpected behaviour you saw

However, the permissions are not forwarded to `systemd-sysv-install`, so the user get:

    update-rc.d: error: Permission denied

Obviously, running `systemctl` with `sudo` (or equivalent) is sufficient to workaround the issue.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ systemctl disable xx.service
xx.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable xx
update-rc.d: error: Permission denied
```

**Comment by mbiebl** [comment]
This is likely a duplicate of #4957 which was closed as wontfix

**Comment by mbiebl** [comment]
The downstream bug report is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843191

**Comment by jerome-pouiller** [comment]
Indeed, it is a duplicate.
