### ISSUE TITLE
TEST-02-UNITTESTS does not install openssl

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#23871]
Looking through the test logs, I noticed
```
log:test-resolved-stream: Skipping TLS test since the 'openssl' command does not seem to be available, skipping tests.
log:test-resolved-stream: Skipping TLS test since the 'openssl' command does not seem to be available, skipping tests.
```

Afaics, this is from TEST-02-UNITTESTS which apparently is missing an `inst_binary openssl`

**Comment by mbiebl** [comment]
This could be installed conditionally (as in test/TEST-50-DISSECT/test.sh) or the test could fail hard if the binary is missing.

I'd vote for failing hard if test dependencies are missing. This makes such issues easier to spot and fix.

**Comment by yuwata** [comment]
This is also related to #21828.

**Comment by DaanDeMeyer** [comment]
Not relevant anymore since we removed the old bash test runner and mkosi does install openssl
