### ISSUE TITLE
tests exit silently without an error if dependencies are missing

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#23872]
In quite a few tests I see stuff like this:

```
test/TEST-50-DISSECT/test.sh:command -v mksquashfs >/dev/null 2>&1 || exit 0
test/TEST-50-DISSECT/test.sh:command -v veritysetup >/dev/null 2>&1 || exit 0
test/TEST-50-DISSECT/test.sh:command -v sfdisk >/dev/null 2>&1 || exit 0
```
```
test/TEST-70-TPM2/test.sh:command -v swtpm >/dev/null 2>&1 || exit 0
test/TEST-70-TPM2/test.sh:command -v tpm2_pcrextend >/dev/null 2>&1 || exit 0
```

Why are we exiting those tests silently with 0 exit code?
This gives the wrong impression that the tests were successful when actually they were skipped.

**Comment by mbiebl** [comment]
We still don't have a proper interface to mark tests as skipped, right?

**Comment by yuwata** [comment]
Related to #21828.

**Comment by DaanDeMeyer** [comment]
Not relevant anymore now that the old bash runner was removed
