### ISSUE TITLE
Support unlocking multiple LUKS devices with FIDO2

### ISSUE THREAD

**Issue by yshui** [systemd/systemd#23889]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

When there are multiple devices enrolled with a FIDO2 device, only one of them can be unlocked during boot.

systemd prompts me to confirm: `👆 Please confirm presence on security token to unlock.`, but when I confirm, one of the devices is unlocked and the other one immediately fails. 

The error:

```
Jul 03 02:40:04 node-02 systemd-cryptsetup[1355]: Failed to open FIDO2 device /dev/hidraw1: FIDO_ERR_INTERNAL
Jul 03 02:40:04 node-02 systemd-cryptsetup[1355]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/nvme1n1.
Jul 03 02:40:16 node-02 systemd-cryptsetup[1355]: Failed to open FIDO2 device /dev/hidraw1: FIDO_ERR_INTERNAL
Jul 03 02:40:16 node-02 systemd[1]: systemd-cryptsetup@enc3.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 02:40:16 node-02 systemd[1]: systemd-cryptsetup@enc3.service: Failed with result 'exit-code'.
Jul 03 02:40:16 node-02 systemd[1]: Failed to start Cryptography Setup for enc3.
```

### Describe the solution you'd like

Unlocking multiple devices works.

### The systemd version you checked that didn't have the feature you are asking for

```
systemd 251 (251.2-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by poettering** [comment]
Hmm, not sure how this is supposed to work with libfido2, i.e. how concurrent access to the same fido device should be handled.

@martelletto what's the idea here? we have two instances of cryptsetup compete for a fido2 device, one wins, the other fails?

Is this supposed to be safe? Do you expect libfido2 consumers to serialize access manually?

(Ideally, libfido2 would just take a BSD file lock on the fd it opens to the device, and serialize things implicitly with that)

**Comment by LDVG** [comment]
Hi,

(taking over from @martelletto as libfido2's main point of contact going forward)

Since v1.8.0, libfido2's Linux native HID backend utilises flock() to serialize access to an authenticator (see Yubico/libfido2#350). For other backends (such as the HIDAPI backend) or older releases, an error is returned. What OS/distribution and libfido2 version are you running, @yshui? 

> Is this supposed to be safe?

The CTAPHID protocol safely handles multiple concurrent clients. If an application tries to access the device while it's busy with another transaction, that request will immediately fail. 

> Do you expect libfido2 consumers to serialize access manually?

In general, libfido2 assumes no responsibility for managing concurrent access to an authenticator and we encourage applications to avoid it.

**Comment by poettering** [comment]
> Since v1.8.0, libfido2's Linux native HID backend utilises flock() to serialize access to an authenticator (see [Yubico/libfido2#350](https://github.com/Yubico/libfido2/pull/350)).

Ah, nice. I figure I suggested this even myself originally... ;-)

That's excellent then. If @yshui uses a new enough libfido2 then access should be properly synchronized already, then the issue would be something else...

**Comment by yshui** [comment]
I am on ArchLinux and libfido2 1.11.0

**Comment by poettering** [comment]
btw, which systemd version is this? please always fill in the submission form in full, and if you have a bug report, that includes the systemd version.

**Comment by yshui** [comment]
@poettering updated in OP.

**Comment by LDVG** [comment]
@yshui: Does unlocking these volumes require a user presence? If so, how long did you wait to provide user presence (e.g. touching the authenticator after it starts binking)?

**Comment by yshui** [comment]
@LDVG Yes. I think probably 5~10 seconds.

**Comment by LDVG** [comment]
Are you persistently seeing this problem or are all volumes unlocked successfully when you're quick to touch the authenticator?

**Comment by yshui** [comment]
After trying again several times I am no longer able to reproduce this problem. I will close this for now until it come up again.

**Comment by Thaodan** [comment]
> Are you persistently seeing this problem or are all volumes unlocked successfully when you're quick to touch the authenticator?

I tried that however that didn't work. Could it be that the services are starting to fast or do they wait till the token is no longer in use?

**Comment by Thaodan** [comment]
> Are you persistently seeing this problem or are all volumes unlocked successfully when you're quick to touch the authenticator?

I tried that however that didn't work. Could it be that the services are starting to fast or do they wait till the token is no longer in use?

**Comment by Thaodan** [comment]
> We believe we have identified the cause of your issue in libfido2, @Thaodan. [Yubico/libfido2#604](https://github.com/Yubico/libfido2/pull/604) contains more information. If you have the possibility to try it out, that is greatly appreciated.

Sure I can test it later.

While waiting I did test again and it seems to depend how fast I wait during unlocking.
If I wait at least a few seconds between each unlocking the unlocking works fine.

**Comment by Thaodan** [comment]
> We believe we have identified the cause of your issue in libfido2, @Thaodan.
> Yubico/libfido2#604 contains more information. If you have the possibility
> to try it out, that is greatly appreciated.

After applying the patch I was no longer able to trigger the issue no matter 
how fast I would touch the key repeatedly to unlock the volumes.
