### ISSUE TITLE
Default threads for login.conf too low.

### ISSUE THREAD

**Issue by BoBeR182** [systemd/systemd#2388]
I have been without any issue and after a kernel update from linux-4.2.5-1 to 4.3.3-2 in Arch Linux, I am  seem to get OOM errors, and I could not open new processes or threads.

After investigating it seems Systemd also applies a limit for programs run from a login-shell. These default to 4096 per user and are configured as UserTasksMax in the [Login] section of /etc/systemd/logind.conf.

This is far too small to run Docker and Freenet, and should be changed to something more reasonable such as ~32000 by default.

Steps to reproduce:
1. Start container.
2. Start many threads: for i in {1..1000}; do sleep 1000& done;
3. Look and quirks in the console:

bash: fork: retry: No child processes
bash: fork: Resource temporarily unavailable
bash: let: detached=: syntax error: operand expected (error token is "=")
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: Resource temporarily unavailable
bash: let: detached+=: syntax error: operand expected (error token is "+=")

Other steps to reproduce, 
1. Run Freenet for about 2hours
2. Check log files
3. OutOfMemoryError: unable to create new native thread from Java EVERYWHERE

**Comment by poettering** [comment]
I don't follow. Docker is a system service, no? it should set its service file TasksMax to a higher value if it wants that.

**Comment by poettering** [comment]
I don#t know what freenet is, but it appears to be a system service too, hence should bump TasksMax=

**Comment by BoBeR182** [comment]
Freenet runs from the normal user login environment.
It does not have a service file.

There are several other bug reports of apps[0][1][2], not working after the recent updates applied. It seems the default has changed with not much warning.

[0]https://bugs.archlinux.org/task/46490
[1]https://bugs.archlinux.org/task/47662
[2]https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

**Comment by BoBeR182** [comment]
https://bugs.archlinux.org/task/47303#comment143035 Recommended me to contact upstream.

**Comment by poettering** [comment]
There was a discussion about this:

http://lists.freedesktop.org/archives/systemd-devel/2015-November/035006.html

And an explicit heads-up in the NEWS file:

https://github.com/systemd/systemd/blob/master/NEWS#L60

I am pretty sure docker.service should simply bump TasksMax= to something higher, but as long as this is just docker where this became an issue, and can be fixed specifically in that service, and not all across the board, I am pretty sure we should stay with the defaults.

One of the archlinux bugs you linked mentions nothing about TasksMax=...

I will bump the per-user limit to 16k now (from 4k), let's see how things work out with that.
