### ISSUE TITLE
systemd-resolvd keeps nameserver of disconnected NIC after removal

### ISSUE THREAD

**Issue by pswilde** [systemd/systemd#23880]
### systemd version the issue has been seen with

251

### Used distribution

Arch Linux

### Linux kernel version used

5.18 and below (not yet tested with above)

### CPU architectures issue was seen on

i686

### Component

systemd-resolved

### Expected behaviour you didn't see

Once the NIC device is disconnected, the nameservers in /etc/resolv.conf should revert to only those available on the connected network.

### Unexpected behaviour you saw

the nameserver used on the, now disconnected NIC's, network is still in /etc/resolv.conf and is primary - leading to name resolutions delays and timeouts

### Steps to reproduce the problem

I have only seen this happen a handful of times, though I believe it happens after setting up a new router for a network via a temporary NIC on my laptop...

Connect to regular WiFi network as normal
Attach USB network device  
Connect USB network device to different network, for example, a new router being set up on a different IP range
Let the NIC device get an IP and DNS server details from DHCP  
Disconnect USB network device
USB NIC nameserver remains in /etc/resolv.conf and is "primary" nameserver

**Comment by poettering** [comment]
Are you sure your /etc/resolv.conf is even managed by resolved? Is it a symlink? Pointing to what? What's the contents?

What does "resolvectl" report in this case?

**Comment by pswilde** [comment]
Thanks for your reply.
I'm afraid I can't be 100% confident that /etc/resolv.conf is managed by resolvd on my system - I assumed it is as clearing the invalid nameserver entry and restarting resolvd resolves the problem (without restarting resolvd, the invalid nameserver returns back into /etc/resolv.conf again after some time).
/etc/resolv.conf is also _not_ symlinked anywhere.
Currently, the problem is not occurring, but I will run resolvectl when it next does and update appropriately.

**Comment by pswilde** [comment]
Apologies... looks like systemd-resolvd was not managing /etc/resolv.conf so completely unrelated, I'll close this thread down.
