### ISSUE TITLE
Stopping user sessions at shutdown (aka SSH sessions hang if socket activation is not being used)

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#2390]
The observed effect:
- ssh into the machine (`sshd.service` is used, not `sshd.socket`+`ssh@*.service`)
- issue `reboot`
- the session and the connection is not terminated properly, you get "Broken pipe" after some seconds

What apparently happens:
- sshd's per-login children place themselves in different cgroups (`session-*.scope`)
- stop on `sshd.service` does not terminate ssh sessions
- network goes down after `sshd.service` went down, but actual ssh sessions remain

Proposed plan: what about explicitly terminating user sessions (via logind) at stop of `systemd-user-sessions.service` or somewhere that early?

**Comment by michich** [comment]
Is this with a current version of systemd?

**Comment by intelfx** [comment]
Yes, that's observed with systemd 228 on arch.

**Comment by intelfx** [comment]
However... in two times of five, it did not happen and the session got terminated properly.

Looks like it's more complex that I've described. Probably the session scopes also get sequenced to shutdown, but are not ordered against network.

**Comment by intelfx** [comment]
An alternative option would be to propagate dependencies (somehow) from main `sshd.service` unit to "child" session scopes. Probably pam_systemd could look at the caller's cgroup and add an artificial After= dependency from the caller service to the newly-created session scope.

Or, again, we could blindly sequence all session scopes `After=systemd-user-sessions.service` and then somehow ensure that `systemd-user-sessions.service` gets ordered against `network.target`.

@poettering?

**Comment by msekletar** [comment]
> Or, again, we could blindly sequence all session scopes After=systemd-user-sessions.service and then somehow ensure that systemd-user-sessions.service gets ordered against network.target.

This is pretty much what we did in the past. See commit ba4c5d93b73ef7bba0ae0c6bf2b36a42360f7a34

**Comment by msekletar** [comment]
Current code looks OK wrt. to change from ba4c5d9. Something else must have changed.

**Comment by intelfx** [comment]
@msekletar 
Ugh. Should've looked at the code before suggesting reasons...

**Comment by intelfx** [comment]
In my setup, `systemd-user-sessions.service` is only indirectly ordered against `network.target` via `remote-fs.target`, then `remote-fs-pre.target`, then `nfs-server.service` — none of them are active as I do not use remote filesystems and NFS on this box.

Maybe it will make sense to add a direct dependency then?

**Comment by msekletar** [comment]
> Maybe it will make sense to add a direct dependency then?

I guess that should work. Care to send a patch?

**Comment by poettering** [comment]
PR fixing this waiting in #3078.
