### ISSUE TITLE
Systemd does not give information on daemon-reload e.g. for Ansible

### ISSUE THREAD

**Issue by ronator** [systemd/systemd#23925]
### Component

systemctl

### Is your feature request related to a problem? Please describe

_Before you consider this as an ansible issue, I urge you to read it all so we can possibly start a discussion if or how this should be addressed some day._

I am deploying configuration w/ Ansible onto Ubuntu 20 which uses systemd. Currently, I have to manage some service unit files, sometimes even remove them. This requires me to call `systemctl daemon-reload` as well, otherwise following tasks may fail.

According to system docs, the reload _will re-rurn all generators, reload all unit files, and recreate the entire dependency tree._

So I started the Ansible playbook and noticed that the ansible module for systemd is ALWAYS only reporting OK. But it should only report OK when nothing was changed. If the daemon-reload by systemd was successful - because it was required - I would have expected Ansible to report CHANGED. Moreover, I am using a when-clause in Ansible to specify IF daemon-reload is really required. In all cases, ansible always reported "OK" back which is apparently wrong when the daemon-reload was executed.

Sounds like an Ansible issue, right?
But is seems, that this behaviour was already reported to Ansible in https://github.com/ansible/ansible/issues/77606
 
The opinion of the Ansible Team is, besides backward incompatability, that:
_The current behavior is by design as systemd does not give information about any changes detected on restart/reexec and unlike a 'service restart' we didn't want to presume the many implications that a changed systemd configuration entails._

Therefore I would like to see a discussion between Ansible and Systemd taking place if the above statement is true from systemd perspective - because I would also be surprised if such a daemon-reload (that triggers all that stuff under the hood) - would not report anything back to the OS that could by used by Ansible.

### Describe the solution you'd like

I want systemd to give feedback if daemon-reload was fine so that deployment tools like Ansible are actually behaving correct and report back as expected in regards of states CHANGED or OK. 

Since the Ansible task feedback may be used for compliance/review purposes, I am totally surprised that we are in such a situation right now where ONE(?) ansible module cannot report the correct task state or will always report OK even when executed (meaning nothing changed which is incorrect)..

### Describe alternatives you've considered

There is none afaik but since this situation was only discussed in the Ansible issues, I was wondering if there could be a way to make ansible get the required information from systemd daemon-reload.
Maybe systemd does report something, but then we should let the ansible team know.

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by ronator** [comment]
Weil, tbh, I just want ansible to report as one would expect it. All services I have ever managed w/ Ansible behave as described for state change.
So I wonder how I should explain this to my superiors that there is actually one ansible Module (the one for systemd) that you can never be sure about from remote what it did. Did it really rebuild the tree?

So as I explained, when I want ansible to run systemd daemon-reload, I tell it do do it ONLY when something changed. There are situations, where not all servers have the correct settings, but some may already be fine.
So why would I need to run daemon-reload if there was no change to unit files?
And that is my point. It seems, the ansible Module will always call daemon-reload when set to yes, although it should be a conditional decision.
What I understand from Ansible Team, is that there is nothing reported from systemd and that is why ansible always gives ok.
I dont know if a solution for this requires all the things you suggested. I am just realizing that the use of that ansible Module is different to all other modules and the Ansible Team akknowledge

**Comment by ronator** [comment]
Hi,
I am not sure about the details of the implementation  you mentioned.
All I am saying is,  that this specific ansible Module behaves incorrect compared to all other daemons managed by ansible.
As I explained, I use conditionals to decide when the reload should actually take place. Sometimes, servers do not have the same config. So my issue here is: why would I run a daemon-reload even if nothing was changed on unit files?
I know systemd is not like any other Service. But any other Service would correctly tell me if it was reloaded or restarted when needed.
Apparently, when ansible Module always gives OK for System daemon-reload,  you cannot be sure what it really did and that is hard to accept and could also lead to decisions against any systemd managed OS deployed via ansible, just because of that situation.
Please consider, that imho this could also affects Puppet. Chef and Salt.

**Comment by ronator** [comment]
Accidentally closed

**Comment by ronator** [comment]
This is how puppet does it:
https://forge.puppet.com/modules/puppet/systemd#daemon-reloads

**Comment by yuwata** [comment]
I am not sure I understand the issue correctly, but we provide `NeedDaemonReload` dbus property for each unit. Please consider to use it. Note, at least currently, we do not have similar property for manager, but I am not sure it is worth to provide it.

**Comment by bluca** [comment]
ansible should know whether it deployed new units or not, it's its job. A daemon-reload cannot meaningfully fail, really. There's a D-Bus property with a timestamp that indicates when the last time a reload happened. You can watch that for changes, it's updated on completion. UnitsLoadTimestamp/UnitsLoadTimestampMonotonic.
