### ISSUE TITLE
systemd-journald occupies more space than RuntimeMaxUse limit

### ISSUE THREAD

**Issue by msutar** [systemd/systemd#2396]
Hi,
I am using systemd with version = 1:211+git0+3a450ec5c6-r0.1
man journald.conf says "SystemMaxUse= and RuntimeMaxUse= control how much disk space the journal may use up at most."

I have set RuntimeMaxUse=32M, with this value, I am expecting 7 archive files and one active journal file.
But I am getting 8 archive files each of 4M and one active journal file (4M). So in total it is taking 36M, instead of RuntimeMaxUse=32M.

Would anybody explain, why it is always consuming RuntimeMaxUse+4M size instead of RuntimeMaxUse only or is it a bug in systemd-journald ?

**Comment by msutar** [comment]
I understand from IRC chat conversation, this is a bug. Would somebody confirm it ?
Let me know, if it's been solved in latest version of systemd.

**Comment by poettering** [comment]
We do not track bugs in old systemd versions upstream. Please only file bug against the two most recent upstream versions upstream.

Note that in the past year or so a couple of issues with journal vacuuming have been fixed. More importantly though, please read the man page:

"Note that only archived files are deleted to reduce the number of files until this limit is reached; active files
           will stay around. "
