### ISSUE TITLE
RFE: add "lightweight" session class for logind, that can be used by cron jobs and similar which do not want to pull in user@.service

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#23978]
### systemd version the issue has been seen with

git main

### Used distribution

any

### Linux kernel version used

any

### Expected behaviour you didn't see

See discussion in https://github.com/systemd/systemd/pull/23569#pullrequestreview-1034462151 and comments further down.

**Comment by poettering** [comment]
This should be a blocker for 252

**Comment by msekletar** [comment]
Hence we need to revert the previously merged PR and introduce a new concept of "lightweight" sessions.

**Comment by poettering** [comment]
given that #23999 was reverted, i guess this one can be dropped from the milestone.

let#s renamed this one though, asking for the "lightweight" session

**Comment by poettering** [comment]
#30226 contains a fix.
