### ISSUE TITLE
systemd-sysext breaks some system binaries

### ISSUE THREAD

**Issue by hferreiro** [systemd/systemd#23971]
### systemd version the issue has been seen with

systemd-250.7-1.fc36.x86_64

### Used distribution

Fedora Silverblue 36

### Linux kernel version used

5.18.10-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysext

### Unexpected behaviour you saw

After enabling systemd-sysext, some things start breaking, e.g. if I lock the session, entering the password to unblock it won't work, neither trying to change to a different VT.

One thing I noticed just after enabling systemd-sysext is entried like these in the journal:

> fprintd[4760]: /usr/libexec/fprintd: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: Permission denied

> nm-dispatcher[901972]: /usr/libexec/nm-dispatcher: error while loading shared libraries: libnm.so.0: cannot open shared object file: Permission denied

> systemd-userdbd[901565]: /usr/lib/systemd/systemd-userdbd: error while loading shared libraries: libsystemd-shared-250.so: cannot open shared object file: Permission denied

### Steps to reproduce the problem

Run `sudo systemd-sysext merge --force`.

**Comment by bluca** [comment]
Which extension are you using?

**Comment by hferreiro** [comment]
I downloaded some official rpms and unpacked them in $HOME. Then created a link /usr/local/lib/extensions/. For example, vim and powertop.

**Comment by poettering** [comment]
selinux off?

**Comment by hferreiro** [comment]
> $ sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

do you mean that I should disable it?

**Comment by hferreiro** [comment]
Yes. It seems that fixed it. I guess I should open a bug in Fedora's BZ.
