### ISSUE TITLE
RFE: attach original syslog timestamp in journal messages

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#2398]
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1130093.

As far as I can tell, the timestamps that are present in syslog messages `[0]` (sent by logger(1) et al) are ignored by journald. Instead, new timestamps are generated when the message arrives.

journald already provides couple of "syslog" fields (SYSLOG_FACILITY=, SYSLOG_IDENTIFIER=, SYSLOG_PID=) but there doesn't seem to be any way to obtain the timestamp that arrived with the message. Perhaps a new field through which this information could be accessed would be appropriate.

`[0] e.g. "<30>Aug 12 11:50:49 vf17 systemd: Stopping System Logging Service..."`

**Comment by poettering** [comment]
What's the usecase for this? We use the time provided by SO_TIMESTAMP, which is generally a better choice, as it cannot be faked. Also, we don't accept syslog datagrams from remote systems, hence all our messages should be generated with the same clock.

What's the rationale?

**Comment by theinric** [comment]
> What's the usecase for this? We use the time provided by SO_TIMESTAMP, which is generally a better choice,

That is a different piece of data than the time stamp in the message...

> as it cannot be faked. 

... hence this is irrelevant.

> Also, we don't accept syslog datagrams from remote systems, hence all our messages should be generated with the same clock.

Use whatever internal time stamps you want for your own purposes, just don't mess with the message data.
"Extraneous" syslog data is already being stored inside the journal. You can't know how to interpret the syslog time stamp so please keep it intact.

**Comment by poettering** [comment]
Still wondering about a usecase...

**Comment by theinric** [comment]
> Still wondering about a usecase...

The journal time stamp marks message reception. The syslog time stamp can mark message creation or other.
In Fedora, when rsyslog pulls messages out of journald, it uses journald's time stamp because that is the more useful information. When rsyslog writes messages to journald, the syslog time stamp might be the more useful information.

**Comment by johannbg** [comment]
Rsyslog should be storing the entire log entry in the message field with it's timestamp.

Here's an example from such ( Apache Tomcat ) entry on a live instance

MESSAGE=Jan 06, 2016 10:52:33 AM org.apache.catalina.core.AprLifecycleListener init

Here's the full output from the journal 
Jan 06 10:52:33 host.example.com tomcat [21060]: Jan 06, 2016 10:52:33 AM org.apache.catalina.core.AprLifecycleListener init

There is uhum "lack of feature"  that you cannot display just the message itself via journalctl -u tomcat MESSAGE ( or something similar ) which would show the above entry like his...

"Jan 06, 2016 10:52:33 AM org.apache.catalina.core.AprLifecycleListener init" 

But instead journal's output always "journal message header+MESSAGE=" which means you see "double entry's/timestamps" 

"Jan 06 10:52:33 host.example.com tomcat [21060]: Jan 06, 2016 10:52:33 AM org.apache.catalina.core.AprLifecycleListener init" 

As in you cannot cut out the "Jan 06 10:52:33 host.example.com tomcat [21060]" preceding the MESSAGE= part so you end up having to result to hacks like or similar to this  "journalctl -u tomcat -o verbose --no-pager | grep "MESSAGE=" | cut -f 2 -d '='" to list just that output.

**Comment by johannbg** [comment]
I still fail to see what the usecase is for rsyslog storing log entry's in the journal to begin with since that leads to double logging, rsyslog should be reading from the journal ( like syslog-ng does ) unless ofcourse the journal is being turned into some form of centralized syslog server

**Comment by vcaputo** [comment]
It is worth noting that the timestamp journald assigns to a message reflects the time journald got around to servicing the event source and dispatching that particular message, which may be substantially later than when the message was emitted.  It's probably of value to record the supplied timestamp, especially in situations of such time-of-emission to time-of-dispatch stratification - like when the system is under severe memory pressure which can cause a busy journald to fall far behind, for example.

**Comment by johannbg** [comment]
Hmm I thought that was being done in _SOURCE_REALTIME_TIMESTAMP anyway under such conditions is not precise measurements of time already lost on the system so the event source itself is already experiencing the "time-delay" causing effect and or even the clock source it's based upon?

And what's the usecase for having that information as in what do end users gain of having the information that the message arrived second later then it was dispatched?

**Comment by vcaputo** [comment]
You're right about _SOURCE_REALTIME_TIMESTAMP as it's coming from the ancillary data for most of the sources (journald-stream::stdout_stream_log() doesn't supply a timestamp though), I forgot about that datum!

It's not a second, it's indeterminate, this isn't a realtime system... between memory pressure causing journald to become largely synchronous in its mmapped-IO and a busy storage subsystem it could be quite a long delay between a log-producing program emitting a message recording some event and journald getting around to dispatching it.

When it comes to logging knowing precisely when something occurred may be very important, time is often the only key for correlating events in complex systems.

**Comment by johannbg** [comment]
Second was just a sample providing measurement of time perhaps poor one at that. 

While I agree with you that when it comes to logging knowing precisely when something occurred is very important, with time being the only key for correlating events in complex systems, the fact is event data is recording things that happened which makes logs exist for one thing and one thing only and that is to producing a persistent,reliable, re-playable record of history. 

That cannot work with multiple time lines on standalone machine or in a cluster of machine so having multiple time stamps for the same event data serves no purpose because in the end you can only use one to achieve that.

**Comment by poettering** [comment]
@theinric hmm, but why would rsyslog send data to journald? sounds the wrong way round really. Note that journald is really intended for "live" data, not for resending older data. For that tools like the journal remote stuff are more useful.

What's your usecase for sending rsyslog data to journald?

**Comment by theinric** [comment]
> hmm, but why would rsyslog send data to journald?

It doesn't have to be rsyslog. It can be logger(1), it can be anything writing to /dev/log.

> sounds the wrong way round really. Note that journald is really intended for "live" data, not for resending older data.

Agreed, journald has a different philosophy and purpose than, say, a syslog daemon.
On the other hand, it hijacked a much older interface which might be used in ways not completely compatible with journald's philosophy.
Calling this an "RFE" is a bit euphemistic.

**Comment by poettering** [comment]
/dev/log is how local clients submit their live messages to the syslog daemon. Pushing historical data into it is done via other interfaces really...

I still don't see the usecase here. It appears quite weird to me to use /dev/log for non-live data...
