### ISSUE TITLE
systemd-hwdb update takes 50s to complete when built with sanitizers

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24023]
### systemd version the issue has been seen with

main

### Used distribution

Fedora 36

### Linux kernel version used

5.18.5-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

`systemd-hwdb update` completes quickly

### Unexpected behaviour you saw

`systemd-hwdb update` takes 50s to complete when built with sanitizers. This makes it a bit awkward to enable sanitizers by default in mkosi.

cc @mrc0mmand Have you dealt with this in the CI at all?

**Comment by mrc0mmand** [comment]
I don't think this is a bug. Reading hwdb does _a lot_ of string ops, which are heavily sanitized (and thus slowed) by ASan, hence the slowdown overall (@evverx correct me please if I'm wrong). In CIs we've dealt with that by bumping the timeout:

https://github.com/systemd/systemd/blob/5eab88a569c1bb5f79093f38e872e588d64a2b26/test/test-functions#L882-L883

The `create_asan_wrapper()` function overall is a great example of what all needs to be done to make a full system run under sanitizers.

**Comment by keszybz** [comment]
Yeah. This does not  sound like a bug, but just the expected thing with sanitizers. Valgrind is also slow.

**Comment by evverx** [comment]
> The create_asan_wrapper() function overall is a great example of what all needs to be done to make a full system run under sanitizers.

I'm not sure it would be (fully) suitable for mkosi. The test suite kind of controls the environment where the tests are run so it can more or less get away with installing `systemd` and setting `LD_PRELOAD` where necessary while `mkosi` has to additionally run services provided by distributions. I think there it would make sense to redirect `systemd` and all the `systemd` services to the directory where `systemd` is built. This way they would pick up the libraries built with ASan/UBSan (thanks to `rpath`) and everything else would be run as usual. `mkosi` still should set `log_path` for PID1 and journald and look for ASan/UBsan reports once VMs/containers are stopped though.

> In CIs we've dealt with that by bumping the timeout

I'd also add that `systemd-hwdb-update.service` is usually masked and run under ASan/UBsan in a couple of tests only.

**Comment by DaanDeMeyer** [comment]
For now I'm looking more at sanitizers just for development purposes. I figure we can do the same as CI and just disable systemd-hwdb-update.service by default in mkosi though, so that we can build with sanitizers by default

**Comment by evverx** [comment]
With `LD_PRELOAD` pointing to `libasan` globally some programs like `ps` hangs (as far as I can remember @mrc0mmand already reported it somewhere), the leak sanitizer reports a lot of irrelevant issues and so on so if `systemd` was built and run by default with ASan by `mkosi` it would be hard to use it interactively. Then again I'm not sure how it should be used. If by analogy with the test suite it should just boot VMs/containers and exit I think it should be fine to build systemd with ASan/UBsan by default.

**Comment by DaanDeMeyer** [comment]
> Also true, interactive shell in a "fully-sanitized" system is quite a pain, since it barely works (at least from my experience).

The two annoying things I've noticed are a memory leak in less and the deadlocks you mentioned. Aside from that, if I mask systemd-hwdb-update.service and disable syscall filters, everything is green in a mkosi VM.

**Comment by evverx** [comment]
> everything is green in a mkosi VM

Could you try introducing memory leaks to systemd, journald and a couple services to see if it's still green?

**Comment by evverx** [comment]
> The two annoying things I've noticed are a memory leak in less and the deadlocks

As far as I understand https://github.com/systemd/systemd/blob/main/docs/HACKING.md#hacking-on-systemd recommends using `mkosi` to test `systemd` and those deadlocks and memory leaks would probably confuse  contributors following the instructions so they at least should be warned somehow if that should be rolled out by default. Then again, I don't use mkosi so I don't know if those defaults affect anything mentioned there.

**Comment by DaanDeMeyer** [comment]
> FWIW on Fedora at least dnf-makecache.service (along with dnf) falls apart as soon as it starts so I have to admit I'm not sure why VMs built with mkosi are green

Very simple, there's no dnf on Fedora mkosi machines

> As far as I understand https://github.com/systemd/systemd/blob/main/docs/HACKING.md#hacking-on-systemd recommends using mkosi to test systemd and those deadlocks and memory leaks would probably confuse contributors following the instructions so they at least should be warned somehow if that should be rolled out by default. Then again, I don't use mkosi so I don't know if those defaults affect anything mentioned there.

Yeah I'm going to make it opt in via an environment variable until a few of the issues are fixed

**Comment by evverx** [comment]
> Very simple, there's no dnf on Fedora mkosi machines

If distros are that stripped there I think in terms of turning on ASan on the CI eventually `create_asan_wrapper()` should probably suffice there as well (instead of relying on `rpath` and pointing `systemd` to the build directory). Though I'm not sure how to do anything useful interactively with images like that.

**Comment by DaanDeMeyer** [comment]
> If distros are that stripped there I think in terms of turning on ASan on the CI eventually create_asan_wrapper() should probably suffice there as well (instead of relying on rpath and pointing systemd to the build directory). Though I'm not sure how to do anything useful interactively with images like that.

It's sufficient for testing systemd changes, but probably not much more than that yeah.

Anyway, this isn't a bug so let's close the issue, #24025 has the changes to build mkosi with sanitizers, where we just disable systemd-hwdb-update.service if that's the case
