### ISSUE TITLE
Fix freedesktop wiki page http://www.freedesktop.org/wiki/Software/systemd/machined/

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#2403]
Description of `CreateMachine` DBus API currently reads as follows,

`The virtual machine name must be suitable as a file name, and hence not contain any slashes, nor be the empty string, nor single/double full stops. Only 7 Bit ASCII is permitted.`

Above description don't match with what is currently implemented in `machined`. Actually, virtual machine name must be valid hostname and in discussion under #2185 we decided that we will not lift this requirement. Hence, wiki page must be fixed instead.

**Comment by poettering** [comment]
Done.
