### ISSUE TITLE
Add support for mapping multiple port at once

### ISSUE THREAD

**Issue by buddhi-deep** [systemd/systemd#24034]
### Component

systemd-nspawn

### Is your feature request related to a problem? Please describe

I have a set of service and I put them on port 600-700, but it seems that nspawn only support port mapping for single port at this time

### Describe the solution you'd like

Parse 900-800 or somethings like this as a port range, and then set rules on nat.

### Describe alternatives you've considered

Put a simple port mapping server(for example: frp or ngrok) on host machine, but that would waste lots of system resource

### The systemd version you checked that didn't have the feature you are asking for

systemd 251 (251.2-3-manjaro)

**Comment by happyeggchen** [comment]
Solved by scripting
```
if set -q _flag_port
                set port_range $_flag_port
                if echo $port_range | grep -qs -
                    set -e port_mapping_tcp port_mapping_udp port_mapping
                    set port_counter 0
                    for port_arrary in (seq $(echo $port_range | awk -F "-" '{print $1}') $(echo $port_range | awk -F "-" '{print $2}'))
                        set port_counter (math $port_counter+1)
                        set port_mapping_tcp[$port_counter] "-ptcp:$port_arrary"
                        set port_mapping_udp[$port_counter] "-pudp:$port_arrary"
                    end
                else
                    set port_mapping_tcp "-ptcp:$_flag_port"
                    set port_mapping_udp "-pudp:$_flag_port"
                end
                sudo systemd-nspawn --resolv-conf=off $port_mapping_tcp $port_mapping_udp -bnq -D $container
            else
                sudo systemd-nspawn --resolv-conf=off -bnq -D $container
            end
```
Basically by just adding multiple -p opt
