### ISSUE TITLE
Acer Aspire A317-33

### ISSUE THREAD

**Issue by MrCowKing** [systemd/systemd#24049]
### systemd version the issue has been seen with

251.2-3-manjaro

### Used distribution

Manjaro 22

### Linux kernel version used

5.15.53-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Power button would trigger the proper action configured elsewhere in the OS

### Unexpected behaviour you saw

Kernel would generate a warning about an unknown key action

> Jul 17 12:18:24 \<hostname\> kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0x55 on isa0060/serio0).
> Jul 17 12:18:24 \<hostname\> kernel: atkbd serio0: Use 'setkeycodes 55 <keycode>' to make it known.
> Jul 17 12:18:24 \<hostname\> kernel: atkbd serio0: Unknown key released (translated set 2, code 0x55 on isa0060/serio0).
> Jul 17 12:18:24 \<hostname\> kernel: atkbd serio0: Use 'setkeycodes 55 <keycode>' to make it known.

### Steps to reproduce the problem

Simply press the power button in meat space

**Comment by MrCowKing** [comment]
Issue fixed hwdb entry.

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAcer*:pnAspireA317-33:*
 KEYBOARD_KEY_55=power
```

Unknown whether this would fix other Acer Aspire 3 laptop buttons, but it 100% fixes the "A317-33" model.

Full DMI from evemu-describe:
\# DMI: dmi:bvnInsydeCorp.:bvrV1.10:bd07/08/2021:br1.10:efr1.2:svnAcer:pnAspireA317-33:pvrV1.10:rvnJSL:rnLilac_JL:rvrV1.10:cvnAcer:ct10:cvrV1.10:sku0000000000000000:

**Comment by yuwata** [comment]
Please submit the fix as a PR. Thank you.

**Comment by MrCowKing** [comment]
#24050
