### ISSUE TITLE
Boot Loader Entry Key `devicetree` Unsupported

### ISSUE THREAD

**Issue by theironrobin** [systemd/systemd#24059]
### systemd version the issue has been seen with

251.3

### Used distribution

Arch Linux

### Linux kernel version used

5.19 (rc1)

### CPU architectures issue was seen on

aarch64

### Component

systemd-boot

### Expected behaviour you didn't see

Should be jumping to the kernel.

### Unexpected behaviour you saw

![image](https://user-images.githubusercontent.com/25991564/179630230-65f9bdfa-2a14-4b5c-8e41-4768d7a5e686.png)

### Steps to reproduce the problem

Create an aarch64 archiso for the Lenovo ThinkPad X13s, like done here: https://github.com/ironrobin/archiso-x13s
Flash the ISO to a USB drive.
Boot into the USB drive.
Select an entry that looks something like this:
```
title   Arch Linux install medium (aarch64, UEFI)
linux      /arch/boot/aarch64/Image
devicetree /arch/boot/aarch64/sc8280xp-thinkpad.dtb
initrd     /arch/boot/aarch64/initramfs-linux.img
options archisobasedir=arch archisolabel=ARCH_AARCH64_202207 efi=novamap clk_ignore_unused console=tty0
```
Note: Things work if you use the `dtb=` kernel option in the options list. Yet if you use `devicetree` Entry Key it is showing as Unsupported.

**Comment by medhefgo** [comment]
This means your firmware does not support the device tree fixup protocol, which sd-boot relies upon for device tree support. (`dtb=` cmdline is handled directly by the kernel and therefore works)

**Comment by poettering** [comment]
@theironrobin that would mean we'd have to embedd an ftd stack, which we really don't want.

See https://github.com/systemd/systemd/pull/19417 for details of the discussion.

**Comment by theironrobin** [comment]
@poettering Do you suggest just using GRUB2 on ARM64 devices, then?

**Comment by poettering** [comment]
I am not experienced in the arm64 world. Is there no perspective on getting the dt fixup protocol into place in your environment?

**Comment by robclark** [comment]
in the vendor provided fw, unlikely.

I didn't quite get why lack of fixup proto would require full fdt stack.. from a quick look at the proto, it was just patching an already loaded dt.  So if the proto wasn't supported couldn't you just skip that?

**Comment by qzed** [comment]
@robclark I've been trying to figure that out too. As far as I can tell fixups are skipped with a warning and a 3s stall: https://github.com/systemd/systemd/blob/9e6df034128936895df2d6348eefce61317ebcc2/src/boot/efi/devicetree.c#L44-L47 So it doesn't seem like the lack of the fixup protocol is causing this error... please note that I've only looked at that very briefly.

**Comment by daniel-thompson** [comment]
I think they theory of failure here is wrong. sd-boot hasn't reported Unsupported because there is no fixup protocol, it has reported Unsupported because it cannot find any DT (e.g. right at the beginning on devicetree_install()).

Currently I think sd-boot only supports updating the DT on systems that *already* have a DT present. For the QCom laptops (which are ACPI by default) there is no existing DT and it gives up:
https://github.com/systemd/systemd/blob/9e6df034128936895df2d6348eefce61317ebcc2/src/boot/efi/devicetree.c#L84

**Comment by daniel-thompson** [comment]
This is not-even-compile tested but if someone wants to rebuild and test then I think this would fix it:
~~~
diff --git a/src/boot/efi/devicetree.c b/src/boot/efi/devicetree.c
index 0312670613..dee280a9d0 100644
--- a/src/boot/efi/devicetree.c
+++ b/src/boot/efi/devicetree.c
@@ -82,8 +82,6 @@ EFI_STATUS devicetree_install(struct devicetree_state *state, EFI_FILE *root_dir
         assert(name);
 
         state->orig = get_dtb_table();
-        if (!state->orig)
-                return EFI_UNSUPPORTED;
 
         err = root_dir->Open(root_dir, &handle, name, EFI_FILE_MODE_READ, EFI_FILE_READ_ONLY);
         if (err != EFI_SUCCESS)
@@ -122,8 +120,6 @@ EFI_STATUS devicetree_install_from_memory(struct devicetree_state *state,
         assert(dtb_buffer && dtb_length > 0);
 
         state->orig = get_dtb_table();
-        if (!state->orig)
-                return EFI_UNSUPPORTED;
 
         err = devicetree_allocate(state, dtb_length);
         if (err != EFI_SUCCESS)
@@ -141,7 +137,7 @@ EFI_STATUS devicetree_install_from_memory(struct devicetree_state *state,
 void devicetree_cleanup(struct devicetree_state *state) {
         EFI_STATUS err;
 
-        if (!state->pages)
+        if (!state->pages || !state->orig)
                 return;
 
         err = BS->InstallConfigurationTable(&EfiDtbTableGuid, state->orig);

**Comment by Alejandroguerra4915** [comment]
![00baf46d-8fc9-4e91-9f59-fcfb5a6dc610](https://user-images.githubusercontent.com/110067826/181870493-0f3e8bc4-84ec-4f41-801b-478097437706.jpg)

someone tell me what I can do here (enter a usb memory with linux and I get this)

**Comment by Alejandroguerra4915** [comment]
????
