### ISSUE TITLE
Allow distribution-independent sysext image matching and architecture matching

### ISSUE THREAD

**Issue by pothos** [systemd/systemd#24061]
### Component

systemd-sysext

### Is your feature request related to a problem? Please describe

A sysext image that merely contains static binaries has no dependency on the host distribution but needs to make sure it is used on the right CPU architecture.
Currently the matching rules are on the one hand too restricted and the `ID` for the distribution has to be set and `SYSEXT_LEVEL` has to be set on both, and on the other hand have no way to ensure that the right architecture is used.

### Describe the solution you'd like

The solution should support to have generic sysext images with static binaries that are not linked to a distribution and its version/`SYSEXT_LEVEL`. Architecture matching should become possible (but maybe not mandatory as it's too late already and it breaks backwards compatibility).

A new `ARCH` field should be supported in systext images to require a host CPU architecture (let's not consider to support binfmt binary translation for now). Also, it would be good to allow an empty `ID=` in sysext images and don't require `SYSEXT_LEVEL` either. One could say that in this case, at least an `ARCH` field should be required but since the sysext image could consist of shell scripts, I think it's not necessary to demand the `ARCH` in this case and it won't be mandatory elsewhere (see above).

I've created this single issue here to discuss both features at the same time instead of splitting the discussion.
If they sound good I can look into submitting patches.

### Describe alternatives you've considered

Use force-loading to skip the matching rules but it's not a good idea as it breaks those cases that rely on the matching rules because they supply multiple sysext images and only the matching one should be loaded.

**Comment by bluca** [comment]
> don't require SYSEXT_LEVEL either

This is already the case, only the `ID` field is mandatory.

**Comment by bluca** [comment]
> A new ARCH field should be supported in systext images to require a host CPU architecture

This makes sense to me as an optional field that if present needs to be satisfied - @poettering thoughts?

**Comment by bluca** [comment]
> Also, it would be good to allow an empty ID=

I think we need to strike a balance between catching obvious errors early to provide useful feedback, and allowing flexibility. I think we should mandate the presence of an extension-release, and we should mandate that the ID field exists. Rather than allowing it to be empty, which could easily happen say if there's a build script that fails to fill in a placeholder, what about an explicit 'don't care' value? Maybe `any`? That of course works until a Linux distro called `any` appears...

**Comment by pothos** [comment]
> This is already the case, only the ID field is mandatory.

That's only for the `isempty(host_os_release_version_id)` case where a rolling release host like ArchLinux has no `VERSION` set.

> I think we need to strike a balance between catching obvious errors early to provide useful feedback, and allowing flexibility. I think we should mandate the presence of an extension-release, and we should mandate that the ID field exists. Rather than allowing it to be empty, which could easily happen say if there's a build script that fails to fill in a placeholder, what about an explicit 'don't care' value? Maybe any? That of course works until a Linux distro called any appears...

Yes, I thought of the empty value as explicit setting but if we want to make it stronger, `any` or `*` seem good.

**Comment by bluca** [comment]
> > This is already the case, only the ID field is mandatory.
> 
> That's only for the `isempty(host_os_release_version_id)` case where a rolling release host like ArchLinux has no `VERSION` set.

We don't check the distro name, as we really don't want to maintain that list. We have tests in place enforcing that just having `ID` and nothing else works too.

> > I think we need to strike a balance between catching obvious errors early to provide useful feedback, and allowing flexibility. I think we should mandate the presence of an extension-release, and we should mandate that the ID field exists. Rather than allowing it to be empty, which could easily happen say if there's a build script that fails to fill in a placeholder, what about an explicit 'don't care' value? Maybe any? That of course works until a Linux distro called any appears...
> 
> Yes, I thought of the empty value as explicit setting but if we want to make it stronger, `any` or `*` seem good.

Can you send a PR?

**Comment by pothos** [comment]
> We don't check the distro name, as we really don't want to maintain that list. We have tests in place enforcing that just having `ID` and nothing else works too.

The problem is that as soon as the host has `VERSION` it must be specified (or `SYSEXT_LEVEL`), so just using `ID=flatcar` doesn't work at the moment.

**Comment by bluca** [comment]
> > We don't check the distro name, as we really don't want to maintain that list. We have tests in place enforcing that just having `ID` and nothing else works too.
> 
> The problem is that as soon as the host has `VERSION` it must be specified (or `SYSEXT_LEVEL`), so just using `ID=flatcar` doesn't work at the moment.

Ah understood now what you mean, that is indeed the case. Perhaps a similar `any` or `*` wildcard would work?

**Comment by pothos** [comment]
Yes, or semver comparisons like for dependencies in Cargo.toml would be even better but that's for later ;)
For the case of having `ID=any` the version field doesn't make sense anyway and it should be ok to omit it.

**Comment by pothos** [comment]
Didn't make it this week but probably the 2nd week of August should work

**Comment by pothos** [comment]
PR posted, I've also used the `any` value in the `ARCH` field to distinguish between an extension with an unkown/unspecified architecture and an extension that is arch-independent.

I think it would be nice to also opt-out of `VERSION/SYSEXT_LEVEL` checks explicitly but still match for the `ID`, what do you think? This way the extension can make basic assumptions about the host OS (e.g., being a Fedora system) while not being bound to a particular release.

**Comment by bluca** [comment]
> I think it would be nice to also opt-out of `VERSION/SYSEXT_LEVEL` checks explicitly but still match for the `ID`, what do you think? This way the extension can make basic assumptions about the host OS (e.g., being a Fedora system) while not being bound to a particular release.

Maybe - but I know @poettering has opinions on this, and would be good to hear from him
