### ISSUE TITLE
Support 4-message dhcpv6 exchange (no rapid commit) and/or rebind-renew

### ISSUE THREAD

**Issue by ti-mo** [systemd/systemd#24065]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

Posting this following my comment here: https://github.com/systemd/systemd/issues/22633#issuecomment-1188297372.

My problem is two-fold:

- My ISP's router/modem supports PD with rapid-commit (as in, it sends a `reply` containing a valid IA_PD after a `solicit`), but doesn't route return packets to my router. The return route is only created properly when using 4-message exchange (without rapid-commit), or, as of the first `renew` message after a rapid-commit `solicit`/`reply`.
- The ISP's modem is stateless. Whenever they push firmware updates, it reboots and comes back up without return routes to my box, **and** it also regenerates its server identifier, which, annoyingly, is an LLT. This makes it so I can't blindly replay `renew` messages periodically to get it to add a return route. (Additionally, my modem is not directly plugged into my router, so it doesn't receive interface down/up events when the modem reboots)

Unsurprisingly, getting the ISP to fix this is futile. :smiling_face_with_tear: I doubt they have much control over the firmware to begin with. (this is a Compal router-modem)

### Describe the solution you'd like

For making this 100% reliable for me, I'd need two things: reintroduce `RapidCommit=false` with full 4-message exchange, and implement `networkctl renew` to kick off a `rebind`/`solicit`/`renew`. Or, even better, make rebinding occur periodically with an interval config setting in `[DHCPv6]`.

As requested, here is a pcap of a working 4-message exchange: [dhcpv6_pcap.zip](https://github.com/systemd/systemd/files/9147514/dhcpv6_pcap.zip).
And here's a pcap of a rebind/solicit/renew: [dhcpcd_pcap.zip](https://github.com/systemd/systemd/files/9147981/dhcpcd_pcap.zip).

### Describe alternatives you've considered

I've used other dhcp clients like `wide-dhcpv6` and `dhcpcd`. Invoking dhcpcd with the `-N` flag does a rebind-solicit-renew as expected, but doesn't include a feature to run it periodically.

For now, though, I run a small Go program that periodically runs the 4-message exchange from another LL address in the subnet.

**Comment by yuwata** [comment]
Could you provide the pcap of a failure case? That is, the case when the solicit message has rapid commit flag.

**Comment by yuwata** [comment]
Waiting in #24074.

**Comment by ti-mo** [comment]
Thank you! Should I make a separate RFE for the `networkctl renew` support?

> Could you provide the pcap of a failure case? That is, the case when the solicit message has rapid commit flag.

There is nothing special about this case, it's really just a normal solicit/reply flow. Except, the modem doesn't send any ipv6 return packets to my gateway.

**Comment by yuwata** [comment]
@ti-mo I filed that as #24108.

**Comment by TuxCoder** [comment]
For docu reason,
I had the same problem with my ISP,
From the strings in the responses it looks like this software:
https://github.com/tomaszmrugalski/dibbler

also this commit that got never released looks like the issue:
https://github.com/tomaszmrugalski/dibbler/commit/ca60c9ebd2b45ec71a880031fea66a52ef34eb85

Project has no maintainer anymore so releases are not expected.

@yuwata thanks for reimplement the `RapidCommit`
