### ISSUE TITLE
systemd-sysusers group creation logic gets confused by existing user

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#24066]
### systemd version the issue has been seen with

251

### Component

systemd-sysusers

### Steps to reproduce the problem

I'm trying to port some existing systems to sysusers.d configuration files, starting from system groups entries.
In the process I seem to be reliably hitting some bug in `systemd-sysusers`, which results in groups being assigned an arbitrary dynamic GID instead of the configured one due to detected conflicts (even when `/etc/group` is wholly missing).

I haven't fully tracked down the logic responsible for this, but at least I managed to extract a minimal reproducer for the behavior:
```
# mkdir -p etc/sysusers.d
# echo 'g bin 1' > etc/sysusers.d/testcase.conf
# echo 'bin:x:1:1:bin:/bin:/sbin/nologin' > etc/passwd

# SYSTEMD_LOG_LEVEL=debug systemd-sysusers --root .
SELinux enabled state cached to: disabled
Reading config file "<...>/etc/sysusers.d/testcase.conf"…
Suggested group ID 1 for bin already used.
Creating group 'bin' with GID 999.

# cat etc/group 
bin:x:999:
```

This behavior looks buggy to me (i.e. breaking idempotence when `/etc/group` goes missing), but I'm happy to have a second pair of eyes on this.
I guess it could be related to a perceived conflict with the primary GID from the entry in the `passwd` file, but I am still reading through the code to understand what happens.

**Comment by lucab** [comment]
After some debugging, I pinned down this behavior (of this specific testcase) to `gid_is_ok()` doing a **GID** existence check against the database of **UIDs**:
https://github.com/systemd/systemd/blob/8d0c34f3673e6c28eb0c5abaf639260260249099/src/sysusers/sysusers.c#L1186-L1187

Empirically, this can be confirmed by using `bin:x:1:20:bin:/bin:/sbin/nologin` as `passwd` content in the testcase above (i.e. a conflicting UID is a sufficient condition).

Overall it feels like either `gid_is_ok()` is implementing an overly aggressive logic, or that the consumer is wrongly expecting it to have a "GID presence check" semantic as mentioned in this comment:
https://github.com/systemd/systemd/blob/8d0c34f3673e6c28eb0c5abaf639260260249099/src/sysusers/sysusers.c#L1259

Related, similar logic mixing UIDs and GIDs exists in `uid_is_ok()`, with an additional layer of cross-name checking:
https://github.com/systemd/systemd/blob/8d0c34f3673e6c28eb0c5abaf639260260249099/src/sysusers/sysusers.c#L957-L963

**Comment by poettering** [comment]
sysusers is opinionated to some level: if you a UID is taken, we won't use it as GID either. 

What's the usecase for doing that? do you have so many users without groups and groups without users that it is important to use the available space densely to the max?

**Comment by lucab** [comment]
> What's the usecase for doing that?

The context/usecase is trying to incrementally move existing traditional distributions (in this case, Fedora) to sysusers.d entries. User entries have some [additional misalignments](https://github.com/systemd/systemd/pull/23509#issuecomment-1143669656) to resolve first, so let's say that immediate focus is on group entries as a first step.

I started by trying to port basic system group entries (WIP at https://pagure.io/setup/pull-request/39) and emptying out `/etc/{group,gshadow}` from composes. That however resulted in static GIDs shifting around to dynamic IDs, as reported.

>  if you a UID is taken, we won't use it as GID either.

I understand where this sentiment/rationale is coming from, but I'm unsure this is much aligned with real word cases.

Specifically, it becomes problematic as soon as one encounters this kind of pattern (real IDs from [Fedora static allocations](https://pagure.io/setup/blob/master/f/uidgid)):
```
g mail 12
g saslauth 76
u mail 8:12
u cyrus 76:12
```
This same config may create the `saslauth` group with wildly different GIDs, depending on the presence of `/etc/passwd` and the (actually unrelated) user `cyrus`, which just happens to have the same number as its UID.

**Comment by poettering** [comment]
i guess we can relax the check if the uid/gid is explicitly specified. happy to take a patch for that.

if it is not explicitly specified, we'd should still avoid assigning the same numeric uid/gid two unrelate users/groups.

**Comment by lucab** [comment]
I have a work-in-process patch that I'm pinning [here](https://github.com/systemd/systemd/files/9270347/systemd-sysusers-gid_is_available.txt) for my own reference.
While that allowed me to move forward in my porting effort, I then encountered https://github.com/systemd/systemd/issues/24217 which is a similar but unrelated bug (it isn't affected by my patch).
I'll have a look into that too before opening PRs, in order to make sure that I can actually reach a working checkpoint and identify any other related further bugs.
