### ISSUE TITLE
restart a delegated unit shouldn't reset its cgroup.subtree_control

### ISSUE THREAD

**Issue by hxysayhi** [systemd/systemd#24064]
### Is your feature request related to a problem? Please describe

In the systemd v250 environment, when I restart the service, the subtree_control is reset. Is this reasonable?

If I modify the value of subtree_control, then when I restart the service, systemd will try to overwrite the value of subtree_control. For example, if I add a `cpu` controller to subtree_control, systemd will remove it from subtree_control when the service is restarted. If I create a subdirectory at this time, and there are still processes in the subgroup when restarting, the startup will fail. The error is as follows:   
```
Control process exited, code=exited, status=219/CGROUP
...
Unit process 543222  (xxx) remains running after unit stoped.
....
```
Which seems to be a failure when rewriting the subtree_control. 

### Describe the solution you'd like

I want to manage `cgroup.subtree_control` by myself when delegation is turned on. 

I hope systemd doesn't modify it, doesn't reset its `cgroup.subtree_control` when service is restarted.

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by hxysayhi** [comment]
#8645 
@Werkov 
A minimal reproducer (a unit file) is as follows:
```
[Unit]
Description=DelegateTest
Before=runlevel2.target
Before=runlevel3.target
Before=runlevel4.target
Before=runlevel5.target
Before=shutdown.target
Before=rhnsd.service
After=network-online.target
After=network.service
Conflicts=shutdown.target
StartLimitInterval=3600000000
StartLimitBurst=30

[Service]
Type=simple
Restart=always
TimeoutSec=60s
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
ExitType=main
RemainAfterExit=no
ExecStartPre=/bin/bash /test/start_pre.sh
ExecStart=/bin/bash /test/loader.sh
ExecStop=-/bin/bash /test/stop_pre.sh
ExecStop=/bin/kill $MAINPID
ExecStopPost=/bin/bash /test/stop_post.sh
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/delegatetest.pid
Delegate=yes
StartLimitInterval=3600000000
StartLimitBurst=30
RestartSec=63s

[Install]
WantedBy=multi-user.target
```

**Comment by hxysayhi** [comment]
Thank you for your attention to this issue.
I have updated the relevant information.
---
**Relevant files**

**unit file:**
```
[Unit]
Description=DelegateTest

[Service]
Type=simple
TimeoutSec=60s
KillMode=process
ExecStartPre=/bin/bash /test/start_pre.sh
ExecStart=/bin/bash /test/loader.sh
ExecStop=/bin/kill $MAINPID
ExecReload=/bin/kill -HUP $MAINPID
Delegate=yes
```

**/test/start_pre.sh:**
```
echo "start_pre"
```

**/test/loader.sh**
```
echo "executing"
CGROUP=$(cat /proc/$$/cgroup)
CGROUP_PATH=/sys/fs/cgroup${CGROUP#*::}
if [[ ! -d ${CGROUP_PATH}/job ]]; then
    mkdir ${CGROUP_PATH}/job
fi
echo $$ > ${CGROUP_PATH}/job/cgroup.procs
echo "+cpu" > ${CGROUP_PATH}/cgroup.subtree_control
ping 127.0.0.1 > /dev/null
```

---
**Answers to your questions**

Which of the Exec*commands write to cgroup.subtree_control?
`cpu`

Are you sure your ExecStopPost= command doesn't undo the cgroup.subtree_control configuration?
yes

Are there any surviving processes when you restart your service?
yes

---
**Steps to reproduce this problem**

1. systemctl start DelegateTest.service
2. systemctl status DelegateTest.service
```
Loaded: loaded (/usr/lib/systemd/system/DelegateTest.service; static)
     Active: active (running) since Thu 2022-07-21 09:58:31 CST; 1s ago
    Process: 541635 ExecStartPre=/bin/bash /test/start_pre.sh (code=exited, status=0/SUCCESS)
   Main PID: 541636 (bash)
      Tasks: 2 (limit: 23196)
     Memory: 660.0K
        CPU: 11ms
     CGroup: /system.slice/DelegateTest.service
             └─job
               ├─541636 /bin/bash /test/loader.sh
               └─541639 ping 127.0.0.1
```
3. systemctl stop DelegateTest.service
4. systemctl status DelegateTest.service
```
Loaded: loaded (/usr/lib/systemd/system/DelegateTest.service; static)
     Active: inactive (dead) since Thu 2022-07-21 09:58:36 CST; 981ms ago
    Process: 541635 ExecStartPre=/bin/bash /test/start_pre.sh (code=exited, status=0/SUCCESS)
    Process: 541636 ExecStart=/bin/bash /test/loader.sh (code=killed, signal=TERM)
    Process: 541644 ExecStop=/bin/kill $MAINPID (code=exited, status=0/SUCCESS)
   Main PID: 541636 (code=killed, signal=TERM)
      Tasks: 1 (limit: 23196)
     Memory: 300.0K
        CPU: 13ms
     CGroup: /system.slice/DelegateTest.service
             └─job
               └─541639 ping 127.0.0.1
```
5. systemctl start DelegateTest.service
```
Job for DelegateTest.service failed because the control process exited with error code.
See "systemctl status DelegateTest.service" and "journalctl -xeu DelegateTest.service" for details.
```
6. systemctl status DelegateTest.service
```
× DelegateTest.service - DelegateTest
     Loaded: loaded (/usr/lib/systemd/system/DelegateTest.service; static)
     Active: failed (Result: exit-code) since Thu 2022-07-21 09:58:53 CST; 1s ago
    Process: 541649 ExecStartPre=/bin/bash /test/start_pre.sh (code=exited, status=219/CGROUP)
      Tasks: 1 (limit: 23196)
     Memory: 300.0K
        CPU: 84us
     CGroup: /system.slice/DelegateTest.service
             └─job
               └─541639 ping 127.0.0.1
```

**Comment by Werkov** [comment]
Thanks for the detailed description.
`KillMode=process` is similar to (deprecated) `KillMode=none`. None of them is recommended since there is no well-defined state of the service after it's deactivated.
That's what happens in your case, the cgoup subtree is not properly cleaneup of processes and hence the issues upon subsequent start.
I'd suggest using `KillMode=mixed` in your unit.

However, I don't see where the reproducer steps lead to the unexpected write to `cgroup.subtree_control`. Can you please clarify?

**Comment by hxysayhi** [comment]
What I'm currently observing is the following. When restarting the service, the value of `cgroup.subtree_control` will be reset by systemd. If no processes are left in my cgroup, systemd successfully resets the value in `cgroup.subtree_control` to empty. If I have leftover processes in my cgroup, then systemd will fail when trying to reset `cgroup.subtree_control` and the service will not be able to start successfully. 

In my business scenario, after the service is stopped, there may be leftover processes. I hope that in this case, the service can be started normally, and the controller I set will not be overwritten and reset during the whole process. In order to ensure that my process is always within the limits of the cgroup controller.

**Comment by Werkov** [comment]
> If no processes are left in my cgroup, systemd successfully resets the value in `cgroup.subtree_control` to empty.

Aha, what likely happens is that the whole cgroup (subtree) is removed and created afresh, i.e. the (re)started service begins always with a clean slate. (That's how it should work, I was confused by the statement that `cgroup.subtree_control` is reset. Technically, it's a different `cgroup.subtree_control` file.)
So there are two aspects to this:

1. Handling (intentionally) leftover processes
  - this is currently not well supported with system, it works best when new and previous instances share nothing (hence `KillMode=none` deprecation)
  - Can't you defer new start after leftovers are gone?
2. `cgroup.subtree_control` setup
  - I suggest you make the setup part of you service's startup routine (as you already do with the example `/test/loader.sh`
  - systemd ensures service always starts within same environment (i.e. empty subtree_control) besides that it takes hands off the delegated subtree

**Comment by hxysayhi** [comment]
> That's how it should work, I was confused by the statement that `cgroup.subtree_control` is reset. Technically, it's a different `cgroup.subtree_control` file.

Here's another experimental scenario：
If I don't modify `cgroup.subtree_control`, the service can still be restarted normally even if there are leftover processes in our cgroup.
Based on this scenario, I mistakenly thought that when the service restarts, it will perform a reset operation on `cgroup.subtree_control`

> Can't you defer new start after leftovers are gone?

No, I can't.
My business scenario is that my service's main process will create child processes to perform tasks and continue to communicate to obtain the execution status of tasks. When my service main process exits, my task subprocess keeps running. And, after my service process restarts, the task process continues to communicate with the main process.

> I suggest you make the setup part of you service's startup routine (as you already do with the example /test/loader.sh

Are you suggesting that I execute the setting of `cgroup.subtree_control` in my own service process to make sure it is set to my desired state? But this approach currently identifies two challenges:

1. When `cgroup.subtree_control` is set to empty, the limit parameters of the relevant controller that I set before for the subtree cgroup are lost. (Perhaps I can save the relevant information in my own business logic and rebuild it for this problem.)

2. Based on the current experimental results, if I want the service to start normally, I need to ensure that there are no legacy processes or no modification to `cgroup.subtree_control`. But my business scenario can't do that there is no process left when the service is stopped. If I want to ensure that the value in `cgroup.subtree_control` is empty when the service is restarted, then I can only complete the cleanup of `cgroup.subtree_control` in the `StopPost` step. I tried to perform cleanup in `StartPre`, but systemd's processing of cgroups will be performed before StartPre, so this method will report an error. If I clean up `cgroup.subtree_control` during the `StopPost` phase, my legacy processes will be running without limits during the time the service is stopped until the service is restarted. In my business scenario, the unrestricted running state of the task process may bring greater risks.

**Comment by poettering** [comment]
I am sorry, but our goal is to guarantee that units are in a reasonably well designed state on activation. And that means we'll reset cgroup properties to configured values on unit restart.

If processes stick around after stop of a service, that's a bug in the service, and we support that only for compatibility, and do print warnings to the logs these days. If you ignore those warnings you get to keep the pieces and things might break later on, like they do for you.

Hence: don't use KillMode= to disable killing of processes, if you do, all bets are off, it's on you.



> My business scenario is that my service's main process will create child processes to perform tasks and continue to communicate to obtain the execution status of tasks. When my service main process exits, my task subprocess keeps running. And, after my service process restarts, the task process continues to communicate with the main process.

If you want subprocesses to stick around, make them allocate scope units, so that they are detached from the unit you start them from. If you do that, the issue should go away. Or in other words: if you have parts of your application that are supposed to have a different lifecycle than the main part of your application, they should be split out into separate services (if they are implemented as binaries of their own that systemd can start for you) or scope units (if they are forked off children that you want to start yourself).

Anyway, restarting should reset settings, this is a design choice, and what you are doing is simply not in-line with how this is intended to be used.

Sorry, but I don't think we should change anything here in systemd.
