### ISSUE TITLE
Cannot set network interface name using systemd-networkd

### ISSUE THREAD

**Issue by gima** [systemd/systemd#2406]
**Description:**
Cannot set a name for a network interface (USB ethernet dongle) using systemd-networkd (man:systemd.link)

**Additional info:**
_package version(s)_
systemd-228-3

**config and/or log files etc**
`/etc/systemd/network/50-test.link`:

```
[Match]
MACAddress=11:22:33:44:55:66
[Link]
Name=test0
```

**Steps to reproduce:**
1. `systemctl enable systemd-networkd`
2. Plug USB ethernet dongle to the computer

**Notes:**
Documentation states that _Name_ is used only if _NamePolicy_ fails. By looking at the source code, it seems that I can _apparently_ force the _NamePolicy_ to fail by setting it to some invalid value.

By changing the _NamePolicy_ to an invalid value, interface was named usb0 (instead of the usb0lpblabla). Yet my _Name=test0_ did not take effect.

This is as far as I could find the problem:
https://github.com/systemd/systemd/blob/master/src/udev/net/link-config.c#L409

**Comment by poettering** [comment]
Note that .link files are not read by networkd, but by udev already.

@teg ?

**Comment by gima** [comment]
It works and I was wrong. Though the documentation is not as informative as it could be, namely:

The man:systemd.link says on the first line that "net_setup_link udev builtin" does the network link configuration. I didn't find within the man-pages that I could use `udevadm test-builtin net_setup_link /sys/path/to/network/device` to find out what did or didn't work with my .link file.

It would be helpful if that could be added. Adding something along the lines of _"See man:udevadm for diagnosing problems with .link files."_  
[y/n]? :3

**Comment by teg** [comment]
Will add docs. Thanks!
