### ISSUE TITLE
ACPI battery is not always "BAT0"

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#24070]
I just saw #23640 in the Git commits and noticed that it hardcodes `/sys/class/power_supply/BAT0` as the device path. But on a Dell Inspiron laptop here, there is no BAT0 device and the internal battery is `BAT1`:

```
$ ls /sys/class/power_supply/
ACAD
BAT1
```

Should probably be changed to look for `POWER_SUPPLY_TYPE=Battery` devices via sd-device.

**Comment by DaanDeMeyer** [comment]
cc @cerebro1 @bluca

**Comment by bluca** [comment]
We are aware, support for multiple batteries will be added after BTP support
