### ISSUE TITLE
systemd-analyze security with path to a unit

### ISSUE THREAD

**Issue by septatrix** [systemd/systemd#24076]
### Component

systemd-analyze

### Is your feature request related to a problem? Please describe

Currently it is only possible to analyze the security of installed services. When developing new service files it is quite cumbersome to always copy it into the config directory (or directly edit it there). This also requires root privileges. The file could also be copied to a user service though this too is cumbersome and might yield different results in the future (#21240).

### Describe the solution you'd like

It should be possible to pass a path to the security command instead.

### Describe alternatives you've considered

Always copying the file is possible though cumbersome and requires superuser privileges.

**Comment by bluca** [comment]
This is already supported, check the `--offline` flag

**Comment by septatrix** [comment]
> This is already supported, check the `--offline` flag

Thanks I did not find that. Is it documented anywhere? There seems to be no help for the subcommands in the man pages nor with the `-h` flag...

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-analyze.html#--offline=BOOL
