### ISSUE TITLE
long style network device names are too long for vlans > 999

### ISSUE THREAD

**Issue by steverweber** [systemd/systemd#2407]
the new long style network device names are too long because vlans with 4 digits cause interface name to be > 15 chars 

related: https://bugzilla.redhat.com/show_bug.cgi?id=1300755

you get the error: 

```
systemctl stop NetworkManager
ifup eno33557248.3008
Error: argument "eno33557248.3008" is wrong: "name" too long

ERROR    : [/usr/sbin/ifup] ERROR: could not add vlan 3008 as eno33557248.3008 on dev eno33557248
```

and `ip a` list the interface as "eno33557248.300" missing the 8

```
...
8: eno33557248.300@eno33557248: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 00:50:56:84:21:80 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::250:56ff:fe84:2180/64 scope link 
       valid_lft forever preferred_lft forever
```

some thoughts, change:
https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-net_id.c
to generate names that are one char shorter.

Steps to Reproduce:
1. create a network device with a vlan > 999 while using longer name format
2. (optional) disable NetorkManager
3. try and bring the interface online

**Comment by poettering** [comment]
Well, "eno33557248" is already borked, and that's what should be fixed... Apparently your BIOS exposes rubbish interface indexes, and the kernel doesn't clean them up. This should really be fixed in the kernel, it should not pass on data that is obviously borked.

**Comment by steverweber** [comment]
this is a vm guest under vmware.
