### ISSUE TITLE
Nspawn overlayfs

### ISSUE THREAD

**Issue by tonobo** [systemd/systemd#2408]
Hey, 

i don't know if it is bug, but it is strange. I tried to bootup a nspawn container with an overlayfs.
Such as: 

> systemd-nspawn --boot --link-journal=try-guest --network-bridge=br0 --settings=override --machine=sslproxy --overlay-ro=/srv/config_overlay/root/:/root/config

As expected i get there my srv/config_overlay/root/ from host system to containers root/config directory.
But if i launch the command as the following: 

> systemd-nspawn --boot --link-journal=try-guest --network-bridge=br0 --settings=override --machine=sslproxy --overlay-ro=/srv/config_overlay/root/:/root

I will receive Hosts /root within the container. 

Is there any fail from my side? 

Another question ... Is there any ability to specify lowerdir in overlay option?

**Comment by alban** [comment]
According to man `systemd-nspawn(1)`, the parameters `--overlay=` and `--overlay-ro=` are parsed differently if there are 2 or 3 directories. In your example, `/root` is both the upper dir from the host and the mount point in the container.

You could try:

```
--overlay-ro=/srv/config_overlay/root/:/srv/config_overlay/root_upper/:/root
```
- `/srv/config_overlay/root/` is the overlay lowerdir on the host
- `/srv/config_overlay/root_upper/` is the overlay upperdir on the host
- `/root` is the mount point in the container

**Comment by poettering** [comment]
Seems to be a misunderstanding, closing.
