### ISSUE TITLE
hibernate to file handled by systemd

### ISSUE THREAD

**Issue by axet** [systemd/systemd#24085]
### Component

other

### Is your feature request related to a problem? Please describe

Hibernate to file requires additional tasks file-system specific done by user. For example handling ext4 and btrfs requires different approach and additional scripts to use.

It would be nice to have it all handled by systemd-swap module. So it would be easy to the end user to hibernate to the swapfile.

hibernate to partition is quite easy. I'm not going to describe it here.

hibernate to file on ext4 requires to get swapfile offset (using 'filefrag') and updating grub kernel default params.

hibernate to file on btrfs requires additional software ( using 'btrfs_map_physical' ) to get correct offset, updating grub kernel default params.

addition to previous steps also required to dynamically turn swapon before hibernate and turn swapoff after hibernate to prevent swap file get used by the system. Google once tried to suggest additional HIBERNATE_ONLY_FLAG for swap files, but it is not yet merged into kernel (https://lore.kernel.org/lkml/20210726171106.v4.1.I09866d90c6de14f21223a03e9e6a31f8a02ecbaf@changeid/)

### Describe the solution you'd like

Having something like systemd-swap --hibernate /swapfile would make it a standard, until we solve it more elegant way.

### Describe alternatives you've considered

I have few sets of scripts to complete task described above.

https://gitlab.com/axet/homebin/-/blob/debian/swap-only-hibernate

https://gitlab.com/axet/homebin/-/blob/debian/swap-resize

https://gitlab.com/axet/homebin/-/blob/debian/swap-resume

https://gitlab.com/axet/homebin/-/blob/debian/swapfrag

https://gitlab.com/axet/homebin/-/blob/debian/btrfs_map_physical.c

All of them together allows me to hibernate to the file using full disk encryption (luks) on my btrfs partition.

**Comment by poettering** [comment]
we already have support for hibernating to file. what's missing?

**Comment by axet** [comment]
Few things: enable swap file before hibernate and turn it off after resume. If hibernate file get filled with system memory dumps - it may have lack of space and hibernate fails.

Not sure if you can set the hibernate file which to use for hibernation using systemd.

Calculating hibernate file offsets for kernel params. Not handled by systemd (at least I'm not aware of it)

**Comment by poettering** [comment]
> enable swap file before hibernate and turn it off after resume.

There's an item in the TODO file in git main already for that. No need to track this here a second time.

> Not sure if you can set the hibernate file which to use for hibernation using systemd.

The usual rules apply: largest first if you have multiple.

> Calculating hibernate file offsets for kernel params. Not handled by systemd (at least I'm not aware of it)

it already does that.

Anyway, I think we can close this. As this is either already implemented, or there's a TODO list item for it anyway.

**Comment by djugei** [comment]
@poettering please reopen:
systemd overwrites the file offset kernel parameters, but on btrfs you need to find the correct offset differently than on ext4/all other fs, leading to hibernate being borked when invoked through systemctl with a swap file on btrfs.

see:
https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file_on_Btrfs
and
https://bugzilla.kernel.org/show_bug.cgi?id=202803
