### ISSUE TITLE
zpool units

### ISSUE THREAD

**Issue by devvythelopper** [systemd/systemd#24097]
### Is your feature request related to a problem? Please describe

systemd has device and mount units which are very useful for having services run only if some hardware is present or mounted. Testing for the presence of a zpool (whether the pool has been imported) can be used for very similar scenarios. It's just not a device (some devices of the pool may be present), and its not a mount (some datasets might not be mounted), but it can still be used as a target for backups (via zfs send/receive) for example and other things.

### Describe the solution you'd like

Add a unit type, maybe not named zpool, but named "pool". Because I can think of other types of pools that might be present (like a libvirtd storage pool for example). And allow units to depend on that.

### The systemd version you checked that didn't have the feature you are asking for

250.4

**Comment by poettering** [comment]
zpool? is that a zfs thing? zfs is noa available in the Linux kernel. Until that happened, I don't think we should add support for that in systemd. Moreover, isn't a zpool just a synthetic device in sysfs anyway? If not it probably should be, but that would require zfs work.

Either way, I doubt this is something we want in systemd, at least not until zfs is part of Linux. Sorry.

**Comment by devvythelopper** [comment]
@poettering  well the zpool does not show up in the list of systemd's devices, so I guess it isn't in sysfs? I opened a feature request with openzfs... so we'll see... makes sense tho, to see a zpool as a virtual device...

**Comment by devvythelopper** [comment]
I looked through /sys and the pools don't show up there, so I guess the zfs team needs to decied whether to implement this...

**Comment by devvythelopper** [comment]
[rincebrain](https://github.com/rincebrain) wrote in https://github.com/openzfs/zfs/issues/13689:

> Unfortunately, IIRC, sysfs and debugfs access are GPL-only in the Linux kernel, so proc is the only place we get to be. 

so no luck then? or can you guys work with what zfs populates under /proc?

**Comment by yuwata** [comment]
Unfortunately, no. sysfs support is necessary for udevd and PID1.
