### ISSUE TITLE
Netdev=yes failing to build or start new qemu instance. Still supports NetworkVeth.

### ISSUE THREAD

**Issue by cerebro1** [systemd/systemd#24093]
### systemd version the issue has been seen with

251

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-41-generic

### Component

other

### Expected behaviour you didn't see

```$mkosi build```
Should start the image build but throws error.

### Unexpected behaviour you saw

$mkosi build
mkosi: error: argument verb: invalid choice: 'yes' (choose from 'build', 'clean', 'help', 'summary', 'genkey', 'bump', 'serve', 'build', 'shell', 'boot', 'qemu', 'ssh')

### Steps to reproduce the problem

$mkosi build
mkosi: error: argument verb: invalid choice: 'yes' (choose from 'build', 'clean', 'help', 'summary', 'genkey', 'bump', 'serve', 'build', 'shell', 'boot', 'qemu', 'ssh')

Fix :
Change back ```Netdev to NetworkVeth```

Though this has long been changed in mkosi so not sure what is stopping it to work in Ubuntu machine.
https://github.com/systemd/mkosi/commit/309b0573dd8ac41ea92f85d6019f69af9b7d8041

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Netdev=yes
```

**Comment by cerebro1** [comment]
Related to https://github.com/systemd/systemd/commit/7ca9563ca18e0238d97f1b6eed8df62fdc2436aa

**Comment by yuwata** [comment]
Have you checked the version of mkosi you use?

**Comment by yuwata** [comment]
As you can see, Ubuntu 22.04 seems to have mkosi-12. Try to use mkosi-13 or newer.

**Comment by cerebro1** [comment]
https://github.com/systemd/mkosi/releases shows netdev change has been released with mkosi-13 which was released in Jun so yeah that is the reason Ubuntu 22.04 does not have the latest version and it is not updating mkosi also.
Installed mkosi-13 manually and that worked so thanks.
Shouldn't such things be mentioned because Ubuntu 22.04 is the latest distribution and mkosi fails to build image for systemd. So a message in HACKING maybe, that image build only supported for mkosi-13 (which is itself latest) or newer.
For a beginner, the HACKING guide is bible :)

**Comment by yuwata** [comment]
It sounds OK for me to mention that mkosi-13 or newer is required. Could you submit that as a PR?

**Comment by cerebro1** [comment]
> It sounds OK for me to mention that mkosi-13 or newer is required. Could you submit that as a PR?

Sure.

**Comment by cerebro1** [comment]
https://github.com/systemd/systemd/pull/24239
