### ISSUE TITLE
set-locale fails when the /etc is an overlayfs backed by btrfs with compression

### ISSUE THREAD

**Issue by hsitter** [systemd/systemd#24106]
### systemd version the issue has been seen with

250

### Used distribution

SteamOS 3.3 20220718.100

### Linux kernel version used

5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0

### Expected behaviour you didn't see

`localectl set-locale de_AT.UTF-8` should work.

### Unexpected behaviour you saw

Didn't work.

### Steps to reproduce the problem

- SteamOS
- Switch to desktop mode
- Open konsole
- localectl set-locale de_AT.UTF-8

The way this appears to be set up is that /etc is an overlay on top of a btrfs with encryption enabled and the upper dir is on an ext4 partition.

```
overlay on /etc type overlay (rw,relatime,lowerdir=/sysroot/etc,upperdir=/sysroot/var/lib/overlays/etc/upper,workdir=/sysroot/var/lib/overlays/etc/work)
````

then the btrfs attributes "leak" out of the overlay, causing the respective setxattr to fail because that makes no sense for overlayfs nor ext4

```
getfattr -d -m ".*" /etc/locale.gen
getfattr: Removing leading '/' from absolute path names
# file: etc/locale.gen
btrfs.compression="zstd"
```

Supposedly using the convenience of `rename()` in `locale_gen_enable_locale()` ought to have bespoke fallback code that replicates rename in a more "reliable" manner?

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
openat(AT_FDCWD, "/etc/locale.gen", O_RDONLY|O_CLOEXEC) = 7
umask(077)                              = 022
openat(AT_FDCWD, "/etc/.#locale.gencdpy4P", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 8
umask(022)                              = 077
fcntl(8, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
newfstatat(7, "", {st_mode=S_IFREG|0644, st_size=9983, ...}, AT_EMPTY_PATH) = 0
fchmod(8, 0644)                         = 0
flistxattr(7, "btrfs.compression\0", 103) = 18
fgetxattr(7, "btrfs.compression", "zstd", 103) = 4
fsetxattr(8, "btrfs.compression", "zstd", 4, 0) = -1 EOPNOTSUPP (Operation not supported)
unlink("/etc/.#locale.gencdpy4P")       = 0
close(8)                                = 0
close(7)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
writev(2, [{iov_base="\33[0;1;31m", iov_len=9}, {iov_base="Failed to enable locale for gene"..., iov_len=63}, {iov_base="\33[0m", iov_len=4}, {iov_base="\n", iov_len=1}], 4Failed to enable locale for generation: Operation not supported
) = 77
```

**Comment by poettering** [comment]
hmm, whaaaat? btrfs invented its own xattr namespace outside of `security.`, `trusted.`, `system.` and `user.`? Man, this is going to break so much software...

And this probably indicates a bug in overlayfs I guess: it probably shouldn't expose xattrs to consuming programs that it cannot also properly set. Dunno. @brauner what's your take on this? 

either way, we should make failures around this graceful in localed.

**Comment by poettering** [comment]
Fix waiting in #24107

**Comment by brauner** [comment]
Oh weird, yes they did add their own xattr namespace:
```c
#define XATTR_BTRFS_PREFIX "btrfs."
#define XATTR_BTRFS_PREFIX_LEN (sizeof(XATTR_BTRFS_PREFIX) - 1)
```
in

```
commit 63541927c8d11d2686778b1e8ec71c14b4fd53e4
Author:     Filipe David Borba Manana <fdmanana@gmail.com>
AuthorDate: Tue Jan 7 11:47:46 2014 +0000
Commit:     Chris Mason <clm@fb.com>
CommitDate: Tue Jan 28 13:20:24 2014 -0800

    Btrfs: add support for inode properties

    This change adds infrastructure to allow for generic properties for
    inodes. Properties are name/value pairs that can be associated with
    inodes for different purposes. They are stored as xattrs with the
    prefix "btrfs."
```

**Comment by brauner** [comment]
So the issue can be explained by:

> The way this appears to be set up is that /etc is an overlay on top of a btrfs with encryption enabled and the upper dir is on an ext4 partition.

So the `lowerdir` is `btrfs` and so you can retrieve those xattrs but the writable `upperdir` is `ext4` and `ext4` doesn't understand `btrfs.` xattrs. I mean, we could probably add logic that fs specific xattrs are ignored when the originating layer and the upper layer are on different filesystems but your bound to run into such situations in other cases. For example, when the fs used for the `upperdir` has been mounted or compiled without any xattr support. Might be a bit cumbersome to figure out all those cases and handle that within the kernel itself. Not sure.
