### ISSUE TITLE
bind mounts for NFS no longer working

### ISSUE THREAD

**Issue by thomasjfox** [systemd/systemd#24120]
### systemd version the issue has been seen with

250.8

### Used distribution

Fedora 36

### Linux kernel version used

5.18.13-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Successful bind mount for /home directory on NFS.

fstab entries:
fileserver.domain:/           /mnt/nfs4/fileserver         nfs4    defaults,vers=4.0        0 0
/mnt/nfs4/fileserver/home    /home                   none    bind,_netdev    0 0

### Unexpected behaviour you saw

systemd[1]: home.mount: Failed to make bind mount source '/mnt/nfs4/fileserver': Permission denied

### Steps to reproduce the problem

The problem relates to this code:
https://github.com/systemd/systemd/blob/5f4ccb0705a54f18f2010b9481039918c448a524/src/core/mount.c#L1057

systemd tries to mkdir() the source directory of a bind mount.

If the kernel cache for a NFS bind mount source path is cold, the kernel will send out the actual mkdir() request to the NFS server. This will result in a -EACCES return code instead of the "expected" -EEXIST mkdir().

This commit changed the error code of mkdir() into a hard error "goto fail":
https://github.com/yuwata/systemd/commit/e4de58c8231e47509ffeb3aa47620ca42f22d7f6

### Additional program output to the terminal or log subsystem illustrating the issue

A tested workaround is to stat() the source path before the mkdir() call, so the kernel knows if the directory or file is exists. Then the -EEXIST error code is also returned for NFS mounts and the bind mount proceeds as normal.

We encountered this issue after upgrading from Fedora 34 with systemd 248.10 to Federa 36 with systemd 250.8. Fedora 35 is also affected.

**Comment by thomasjfox** [comment]
Workaround used in production locally Fedora 36 (worked also on Fedora 35):
```
diff -u -r -p systemd-stable-249.12/src/core/mount.c systemd-stable-249.12.fixup/src/core/mount.c
--- systemd-stable-249.12/src/core/mount.c      2022-04-28 19:45:30.000000000 +0200
+++ systemd-stable-249.12.fixup/src/core/mount.c        2022-07-15 13:32:31.637375559 +0200
@@ -4,6 +4,7 @@
 #include <signal.h>
 #include <stdio.h>
 #include <sys/epoll.h>
+#include <sys/stat.h>
 
 #include "sd-messages.h"
 
@@ -1032,6 +1033,11 @@ static void mount_enter_mounting(Mount *
         /* Create the source directory for bind-mounts if needed */
         p = get_mount_parameters_fragment(m);
         if (p && mount_is_bind(p)) {
+                /* init inode cache for NFS mounts: If we call mkdir_p_label() without this and the kernel cache
+                   is cold, it will return -EACCES instead of -EEXIST. Don't care about the return value here. */
+                struct stat st;
+                stat(p->what, &st);
+
                 r = mkdir_p_label(p->what, m->directory_mode);
                 /* mkdir_p_label() can return -EEXIST if the target path exists and is not a directory - which is
                  * totally OK, in case the user wants us to overmount a non-directory inode. */
```
Not sure if the stat() call is the best fix as I don't know why systemd does a mkdir() call for the _source_ of a bind mount in the first place. I'm sure there are good reasons for it.

@yuwata may be you know more about this behavior?

Ubuntu is also affected by the issue: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1979952

**Comment by yuwata** [comment]
I guess #24122 should be enough. Could you test the PR?

**Comment by thomasjfox** [comment]
> I guess #24122 should be enough. Could you test the PR?

Will do so now. Results should be in the next 20 minutes.

**Comment by poettering** [comment]
> If the kernel cache for a NFS bind mount source path is cold, the kernel will send out the actual mkdir() request to the NFS server. This will result in a -EACCES return code instead of the "expected" -EEXIST mkdir().

Why that? Can you explain? That smells like a bug in the kernel, no? Why would it return EACCES in that case? I don't see how this would ever make sense.

**Comment by thomasjfox** [comment]
Fix works fine, thanks a lot @yuwata!

Thinking a bit more about this: I guess bind mounts from a read only source path are also broken?

Here's a quick test to check the kernel return codes, I didn't try with a systemd mount unit yet:
```sh
# create 1000 MB sparse file
dd if=/dev/zero of=fake-disk.img bs=1M count=1 seek=1000

losetup /dev/loop0 /tmp/fake-disk.img
mkfs.ext4 /dev/loop0

mkdir /mnt/read-only

mount /dev/loop0 /mnt/read-only
mkdir /mnt/read-only/source

# clear inode cache
umount /mnt/read-only

mount -o ro /dev/loop0 /mnt/read-only

strace mkdir /mnt/read-only/source
..
mkdir("/mnt/read-only/source", 0777) = -1 EROFS (Read-only file system)

```
Kernel returns -EROFS here. Yet a normal bind mount is fine of course:

```sh
mkdir /mnt/bind-mount-target

mount -o bind /mnt/read-only/source /mnt/bind-mount-target

mount |grep target
/dev/loop0 on /mnt/bind-mount-target type ext4 (ro,relatime)
```

So I'm not sure that mkdir() + masking individual errno return codes is a good strategy. A different (network) filesystem might return f.e. -EPERM instead of -EACCESS. The strerror() call for the -EACCES is already translated to "Permission denied", so it would not surprise me.

**Comment by thomasjfox** [comment]
> > If the kernel cache for a NFS bind mount source path is cold, the kernel will send out the actual mkdir() request to the NFS server. This will result in a -EACCES return code instead of the "expected" -EEXIST mkdir().
> 
> Why that? Can you explain? That smells like a bug in the kernel, no? Why would it return EACCES in that case? I don't see how this would ever make sense.

systemd is running as root. The NFS server in question does no allow file operations as root and maps them to the anonymous uid/gid, which is the default NFS behavior (root_squash).

From the "exports" man page:
**
       Very  often,  it  is  not desirable that the root user on a client machine is also treated as root when accessing files on the NFS server. To this
       end, uid 0 is normally mapped to a different id: the so-called anonymous or nobody uid. This mode of operation (called `root  squashing')  is  the
       default, and can be turned off with no_root_squash.
**


When the kernel filesystem cache is cold, it does not know anything about the source path on the NFS volume and sends the request over to the NFS server. This is sane behavior in my eyes. The server then denies the mkdir() request as root.

**Comment by thomasjfox** [comment]
> strace mkdir /mnt/read-only/source
> ..
> mkdir("/mnt/read-only/source", 0777) = -1 EROFS (Read-only file system)
> ```
> 
> Kernel returns -EROFS here. Yet a normal bind mount is fine of course:

for the record: Once the kernel cache is hot, it returns -EEXIST even for the read only mount point:

mkdir("/mnt/read-only/source/", 0777)   = -1 EEXIST (File exists)

**Comment by poettering** [comment]
> The server then denies the mkdir() request as root.

But that is kinda a bug in the NFS server. On Linux, if you ask to create inode X, but you lack the permissions to do so and the inode X already exists, then you get EEXIST, not EACCES! If the NFS server responds EACCESS instead of EEXIST, then that's incompatible with the usual Linux file system semantics.

Try it out: as regular user do "mkdir /usr". You'll get EEXIST, not EACCES...

**Comment by thomasjfox** [comment]
> Try it out: as regular user do "mkdir /usr". You'll get EEXIST, not EACCES...

see above for read only mount points, it's the same game: -EEXIST is returned only if the kernel cache is hot.

**Comment by poettering** [comment]
> > ```
> > 
> > ```
> 
> 
> for the record: Once the kernel cache is hot, it returns -EEXIST even for the read only mount point:
> 
> mkdir("/mnt/read-only/source/", 0777)   = -1 EEXIST (File exists)

So basically, Linux is consistent with itself, i.e. client-side everything is systematic, EEXIST trumps EACCESS on real file systems and if NFS request is answered from cache. But once the server is involved, and the actual request goes to the server, then the server is confused and lets EACCES trump EEXIST...

Which NFS server is that? The Linux one?

**Comment by thomasjfox** [comment]
> Which NFS server is that? The Linux one?

yes, it's Rocky Linux (RHEL) 8.6, kernel 4.18.0-372.9.1.el8.x86_64

**Comment by yuwata** [comment]
@thomasjfox Thank you for testing the PR. The PR is now updated. Could you test again?

**Comment by thomasjfox** [comment]
> @thomasjfox Thank you for testing the PR. The PR is now updated. Could you test again?

PR works fine, no "noise" logged during normal operation:

-- Boot 18dca3d884ca465992ba60e182d0a4b0 --
Jul 26 17:05:42 myhostname systemd[1]: Mounting home.mount - /home...
Jul 26 17:05:42 myhostname systemd[1]: Mounted home.mount - /home.


I doubled checked the source code in the rpm build directory that the changes from the PR were indeed applied.

Thanks a lot for the quick turnaround!
