### ISSUE TITLE
networkd: Cannot create multiple veth Interfaces

### ISSUE THREAD

**Issue by modzilla99** [systemd/systemd#24132]
### systemd version the issue has been seen with

250

### Used distribution

AlmaLinux 9

### Linux kernel version used

5.14.0-70.17.1.el9_0.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When defining multiple Veth-Pairs, multiple Veth-Pairs should be created.

### Unexpected behaviour you saw

Only one Veth-Pair got created and the systemd-networkd seems to think that second pair has already been created, so it doesn't do anything.
```log
Jul 26 22:30:00 os-hv-01 systemd[1]: Starting Network Configuration...
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br-03d57d6a921f: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br-int-br0: netdev ready
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br-int-br0: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br-int-br0: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br0-br-int: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br0-br-int: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo1: netdev ready
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo1: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo1: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge37: netdev ready
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge37: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge0: netdev ready
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge0: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge0: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: enp4s0: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: enp4s0: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo: Link UP
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo: Gained carrier
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo1: Gained IPv6LL
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge0: Gained IPv6LL
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: Enumeration completed
Jul 26 22:30:00 os-hv-01 systemd[1]: Started Network Configuration.
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge0: netdev exists, using existing without changing its parameters
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: bridge37: netdev exists, using existing without changing its parameters
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: lo1: netdev exists, using existing without changing its parameters
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br0-bridge37: netdev ready
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br0-bridge37: netdev exists, using existing without changing its parameters
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br-int-br0: netdev exists, using existing without changing its parameters
Jul 26 22:30:00 os-hv-01 systemd-networkd[2923]: br0-br-int: Failed to set master interface, ignoring: Operation not supported
Jul 26 22:30:01 os-hv-01 systemd-networkd[2923]: bridge0: DHCPv4 address 10.129.0.10/24, gateway 10.129.0.1 acquired from 10.129.0.1
```

### Steps to reproduce the problem

I used the following config:
<details>
  <summary>Networkd-Configs</summary>
  

    # cat br0-br37.network
    [Match]
    Name = br0-br37

    [BridgeVLAN]
    PVID = 37
    EgressUntagged = 37

    # cat br0-br-int.network
    [Match]
    Name = br0-br-int

    [Network]
    LinkLocalAddressing = false

    # cat br37-br0.network
    [Match]
    Name = br37-br0

    [Network]
    Bridge = bridge37

    # cat bridge0.netdev

    [NetDev]
    Name = bridge0
    Kind = bridge
    MTUBytes = 9000
    MACAddress = 96:34:77:C5:C3:C

    [Bridge]
    DefaultPVID = none
    VLANFiltering = true

    # cat bridge0.network
    [Match]
    Name = bridge0

    [Network]
    DHCP = ipv4

    [BridgeVLAN]
    EgressUntagged = 1 
    PVID = 1
    VLAN = 7-37

    # cat bridge37.netdev

    [NetDev]
    Name = bridge37
    Kind = bridge
    MTUBytes = 9000

    [Bridge]
    VLANFiltering = false

    # cat bridge37.network
    [Match]
    Name = bridge37

    [Network]
    Address = 10.129.37.9/24

    # cat br-int-br0.network
    [Match]
    Name = br-int-br0

    [Network]
    Bridge = bridge0

    [BridgeVLAN]
    VLAN = 7-37
    EgressUntagged = 7
    PVID = 7

    # cat enp4s0.network
    [Match]
    Name = enp4s0

    [Network]
    Bridge = bridge0

    [BridgeVLAN]
    VLAN = 7-37
    PVID = 1
    EgressUntagged = 1

    # cat lo1.netdev
    [NetDev]
    Name = lo1
    Kind = dummy

    # cat lo1.network
    [Match]
    Name = lo1

    [Network]
    DHCP = false
    Address = 10.129.50.10/32

    # cat veth.netdev
    [NetDev]
    Name = br-int-br0
    Kind = veth
    MTUBytes = 9000

    [Peer]
    Name = br0-br-int

    # cat veth-vlan37.netdev
    [NetDev]
    Name = br0-bridge37
    Kind = veth
    MTUBytes = 9000
    MACAddress = 02:42:d0:04:9c:0c

    [Peer]
    Name = br0-bridge37
    MACAddress = 02:42:d0:04:9c:0d

</details>

**Comment by yuwata** [comment]
> ```
> # cat veth-vlan37.netdev
> [NetDev]
> Name = br0-bridge37
> Kind = veth
> MTUBytes = 9000
> MACAddress = 02:42:d0:04:9c:0c
> 
> [Peer]
> Name = br0-bridge37
> MACAddress = 02:42:d0:04:9c:0d
> ```
You cannot specify the same name in `[NetDev]` and `[Peer]`.

**Comment by modzilla99** [comment]
@yuwata thank you very much for catching that, I am sorry! Keep up the great work!
