### ISSUE TITLE
repart: Add dropin support

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24145]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

I want to use repart definition files as the way to configure partitions for mkosi generated images. I'd like to ship a default set of repart configuration files with mkosi that users can then override via dropins if needed. We then apply the partitions to the image, dissect it using systemd-dissect, do some sanity checks to make sure we can do something with the final partition layout, and continue to build the image.

### Describe the solution you'd like

I'd like some form of dropins for repart configuration files. Without thinking about it to much, the same approach that's used for overriding units would probably work fine, so if a .d suffixed directory exists, look for dropins in that directory and apply them.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
makes sense.
