### ISSUE TITLE
StandardOutput=file:path doesn‘t work because of selinux(Enforcing)

### ISSUE THREAD

**Issue by jcg190701** [systemd/systemd#24149]
### systemd version the issue has been seen with

systemd-250.3-8.fc36.x86_64

### Used distribution

fedora36

### Linux kernel version used

5.17.5-300.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

test.service can work with selinux(Enforcing)
[root@fedora system]# cat test.service
[Unit]
Description=test StandardOutput
[Service]
ExecStart=/usr/bin/echo "Hello World!"
StandardOutput=file:/home/log

### Unexpected behaviour you saw

test.service start failed with selinux(Enforcing)
```
[root@fedora system]# systemctl status test.service
× test.service - test StandardOutput
     Loaded: loaded (/etc/systemd/system/test.service; static)
     Active: failed (Result: exit-code) since Fri 2022-07-29 10:53:35 CST; 4s ago
    Process: 832918 ExecStart=/usr/bin/echo Hello World! (code=exited, status=209/STDOUT)
   Main PID: 832918 (code=exited, status=209/STDOUT)
        CPU: 1ms

7月 29 10:53:35 fedora systemd[1]: Started test.service - test StandardOutput.
7月 29 10:53:35 fedora systemd[832918]: test.service: Failed to set up standard output: Permission denied
7月 29 10:53:35 fedora systemd[832918]: test.service: Failed at step STDOUT spawning /usr/bin/echo: Permission denied
7月 29 10:53:35 fedora systemd[1]: test.service: Main process exited, code=exited, status=209/STDOUT
7月 29 10:53:35 fedora systemd[1]: test.service: Failed with result 'exit-code'.
```
In /var/log/audit/audit.log, you can see this
```
type=AVC msg=audit(1659063215.855:6607): avc:  denied  { create } for  pid=832918 comm="(echo)" name="log" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:home_root_t:s0 tclass=file permissive=0
type=SERVICE_START msg=audit(1659063215.856:6608): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=test comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'^]UID="root" AUID="unset"
```

### Steps to reproduce the problem

just add test.service and start it
[root@fedora system]# cat test.service
[Unit]
Description=test StandardOutput
[Service]
ExecStart=/usr/bin/echo "Hello World!"
StandardOutput=file:/home/log

**Comment by bluca** [comment]
You need to raise this with the Fedora selinux policy maintainers, we can't do anything about it, as it's the policy that needs an update.
