### ISSUE TITLE
systemd timer service should remember status of last invocation

### ISSUE THREAD

**Issue by pampelmuse76** [systemd/systemd#24159]
### Component

systemctl

### Is your feature request related to a problem? Please describe

I am doing a systemd timer service (abc) every day at 01h00.
At about 02:00 the server was restarted.
Next morning I want to check, if the systemd timer service did run ok:
>systemctl status abc
○ abc.service - ABC start
     Loaded: loaded (/etc/systemd/system/abc.service; static)
     Active: inactive (dead)
TriggeredBy: ● abc.timer

### Describe the solution you'd like

Expected results:
systemd should keep track of the status of the last invocation regardless if a reboot has occurred.
>systemctl status abc
○ abc.service - ABC start
     Loaded: loaded (/etc/systemd/system/abc.service; static)
     Active: inactive (dead) since Sun 2022-07-31 13:01:05 CEST; 3min 43s ago
TriggeredBy: ● abc.timer
    Process: 7307 ExecStart=/usr/bin/echo Echo from abc (code=exited, status=0/SUCCESS)
   Main PID: 7307 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Jul 31 13:01:05 zorro.wonderland.loc systemd[1]: Started abc.service - ABC start.
Jul 31 13:01:05 zorro.wonderland.loc echo[7307]: Echo from abc
Jul 31 13:01:05 zorro.wonderland.loc systemd[1]: abc.service: Deactivated successfully.

Additional info:
This is needed to monitor generally if the last systemd timer service invocation was OK or not.
This is especially needed if there is a regularly reboot.
This is especially needed if the time intervall is large (e.g. monthly reports).

### Describe alternatives you've considered

The service "abc" could save the information about success on its own,
but I think systemd should be able to tell the outcome (exit cause) of the last invocation,
no matter if there was a reboot in-between.
(More or less like "Persistent=true" makes the last invocation time accessible after reboot.)

### The systemd version you checked that didn't have the feature you are asking for

250 (v250.8-1.fc36)

**Comment by pampelmuse76** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=2110867

**Comment by pampelmuse76** [comment]
About the argument: "This information should be in the journal":

The success (and the last time they run) of a timer based service should be part of the "current state".

If I ask "Is this machine OK?", I not only want to know if all current running service are OK,
but also did all timer bases service run within their expected time range and did they succeed.

**Comment by yuwata** [comment]
I think `systemctl list-timers` should help you.

**Comment by poettering** [comment]
Hmm, I don#t grok what is supposed to be missing here? The status output you pasted shows that your service exited successfully. So what's missing? Not sure I grok what the problem is supposed to be here?

**Comment by pampelmuse76** [comment]
I don't get the status (exit cause) if there was a reboot since the last invocation.
I only get:
>systemctl status abc
○ abc.service - ABC start
     Loaded: loaded (/etc/systemd/system/abc.service; static)
     Active: inactive (dead)
TriggeredBy: ● abc.timer

**Comment by poettering** [comment]
yeah, "systemctl status" only shows information of the most recent start of a service.

For older stuff use "journalctl -u abc.service"

it will given you the same info for evertyhing else.

**Comment by pampelmuse76** [comment]
But "most recent" depends if there was a reboot in between, because if there was **no** reboot it shows:
>systemctl status abc
○ abc.service - ABC start
     Loaded: loaded (/etc/systemd/system/abc.service; static)
     Active: inactive (dead) since Sun 2022-07-31 13:01:05 CEST; 3min 43s ago
TriggeredBy: ● abc.timer
    Process: 7307 ExecStart=/usr/bin/echo Echo from abc (code=exited, status=0/SUCCESS)
   Main PID: 7307 (code=exited, status=0/SUCCESS)
        CPU: 1ms
 
So if this information is show, depends if there was a reboot.

**Comment by pampelmuse76** [comment]
This is a RFE. Systemd should remember the exit cause of the most recent execution of a timer triggered service, even if there was a reboot.

**Comment by poettering** [comment]
It remembers in the logs. 

This was discussed before at various places, but we think "systemctl status" is about *runtime* status, and hence should not look into history. journalctl is about the overall history, and will give you more.

**Comment by pampelmuse76** [comment]
Hmm, can halfway follow.
For me runtime status = OK also means all timer services where run within their timeframe and they where OK (exit cause).
For me this is part of runtime status and not history.
But this may be seen different.

**Comment by pampelmuse76** [comment]
Why do I want this:
I monitor the backup which is a timer based service running at night.
So I check: Was the last service invocation less than 24 h ago and did it run OK?
I do not want to care if there was a reboot (due to some kernel updates) in between.

**Comment by poettering** [comment]
I prepped #24182 which tries to improve the documentation around this in the man page, and explains what "systemctl status" does, and how to get the older stuff.

**Comment by poettering** [comment]
> Was the last service invocation less than 24 h ago and did it run OK?

a better way to check that would be with 

```
`journalctl -u abc.service MESSAGE_ID=7ad2d189f7e94e70a38c781354912448 --since=-24h
```

**Comment by pampelmuse76** [comment]
So "systemd[1]: abc.service: Deactivated successfully." means exit cause=0.
This is OK, this I can use.

**Comment by poettering** [comment]
it's a structure log message, i.e. use "-o verbose" to see all fields of the log message.

**Comment by poettering** [comment]
(which includes more detailed success info)

**Comment by pampelmuse76** [comment]
But not the exit cause.
Maybe this should be included, because it is the default way to show success or failure of a process.

**Comment by poettering** [comment]
Look for MESSAGE_ID 98e322203f7a4ed290d09fe03c09fe15to see exit statusses of service processes.

**Comment by sedrubal** [comment]
If someone needs a nice list of the last exist statuses, this command might help:

```bash
journalctl CODE_FUNC=job_log_done_status_message -u unit.service
```
