### ISSUE TITLE
login1 doesn't send logout on the bus

### ISSUE THREAD

**Issue by m0yellow** [systemd/systemd#2415]
I'm searching for a signal to monitor user sessions in dbus.

busctl monitor 
shows the login (and lots of other stuff), but stays quiet on the logout, session end issue.
I would expect seeing symmetrical information on the bus about resources stopped, as I see about resources or sessions started. Otherwise I can resort to journal parsing (as lots of ugly examples on github show).

I personally would like to see more examples how to use the machine readable interfaces of systemd in bash. As I'm trying to get my python foo up to my shell foo, but some things are still faster the old way.

**Comment by poettering** [comment]
We do generate SessionRemoved signals each time a session vanishes, and that works fine here, when I use `busctl monitor org.freedesktop.login1`. Could you please run this command, and then log in and out (maybe simply by running a "ssh localhost" and exiting immediately from it again). What output does the command generate?

We provide "loginctl" as command line utility to access logind's interfaces. If you want to subscribe to bus signals however, I fear you need to use a higher-level language as bash does not provide access to bus objects for subscribing to signals.

**Comment by poettering** [comment]
I will close this now, please feel free to reopen if there's an actual issue somewhere...

**Comment by m0yellow** [comment]
It seems to be opensuse related, I'll check if I can get it running and open a ticket over there. 
To clarify: I used busctl monitor in bash, to check of the existence of the signal, I'll try to work out something more elaborated afterwards. Now I'll go and chase the opensuse bug.
