### ISSUE TITLE
Add DERE DBook D10

### ISSUE THREAD

**Issue by junocomp** [systemd/systemd#24163]
### Is your feature request related to a problem? Please describe

Please add brand `DERE`

Model: `DBook D10`

The Goodix touchscreen drivers have to be inverted, I am not sure how to do that if someone can help. 

Below will fix the display orientation.

### Describe the solution you'd like

```
sensor:modalias:acpi:KIOX000A*:dmi:bvnAmericanMegatrendsInternational,LLC.:bvrJP2V1.05:bd04/27/2022:br1.5:efr1.3:svnDefaultstring:*
 ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1
```

**Comment by yuwata** [comment]
Please submit the change as a PR. Thank you.

**Comment by junocomp** [comment]
@yuwata 

https://github.com/systemd/systemd/commit/4e36f489398250d4e6112c8e90941fe2322bb595

**Comment by yuwata** [comment]
@junocomp Could you open a PR with the commit?
