### ISSUE TITLE
__cplusplus and __STDC_VERSION__ defined in the same time results in compilation error

### ISSUE THREAD

**Issue by ctxnop** [systemd/systemd#24172]
### Component

other

### Is your feature request related to a problem? Please describe

I face an annoying issue that is systemd isn't directly responsible of, but I think it can make sense to fix it through systemd anyway.

I am writing some app that makes use of `sd-bus.h`, in C++. Unfortunately, I also have some other poorly written proprietary lib, written in C. To prevent ABI issue with this lib, I have to define  `__STDC_VERSION__` to `199901L` before including the header from this lib. Yeah, I know, it's ugly...

Unfortunately, it gets worst when including then `sd-bus.h`, because of this: https://github.com/systemd/systemd/blob/main/src/systemd/_sd-common.h#L88

It detects that I have a `__STDC_VERSION__` to `199901L` so it is defined to `static`, which end-up in g++ screaming at me that this keyword can't be used in this context.

### Describe the solution you'd like

I would like to change the code from:
```c
#ifndef _SD_ARRAY_STATIC
#  if __STDC_VERSION__ >= 199901L
#    define _SD_ARRAY_STATIC static
#  else
#    define _SD_ARRAY_STATIC
#  endif
#endif
```
into:
```c
#ifndef _SD_ARRAY_STATIC
#  if __STDC_VERSION__ < 199901L or defined(__cplusplus)
#    define _SD_ARRAY_STATIC
#  else
#    define _SD_ARRAY_STATIC static
#  endif
#endif
```

This way, in the unfortunate case of having `__STDC_VERSION__` AND `__cplusplus` defined in the same time, it will still work.

### Describe alternatives you've considered

I currently do this:
```cpp
#define _SD_ARRAY_STATIC
#include <sd-bus.h>
```
Which works, even if I think it's ugly.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by ctxnop** [comment]
To reproduce, simply create this main.cpp:
```cpp
#include <sd-bus.h>

int main() { return 0; }
```

Compiles it using:
```sh
g++ -o main -I/usr/include/systemd -lsystemd -D__STDC_VERSION__=199901L main.cpp
```

The result should be:
```
In file included from /usr/include/systemd/sd-event.h:29,
                 from /usr/include/systemd/sd-bus.h:26,
                 from main.cpp:2:
/usr/include/systemd/_sd-common.h:89:30: error: expected primary-expression before 'static'
   89 | #    define _SD_ARRAY_STATIC static
      |                              ^~~~~~
/usr/include/systemd/sd-id128.h:40:48: note: in expansion of macro '_SD_ARRAY_STATIC'
   40 | char *sd_id128_to_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX]);
      |                                                ^~~~~~~~~~~~~~~~
In file included from /usr/include/systemd/sd-bus.h:27:
/usr/include/systemd/sd-id128.h:40:48: error: expected ']' before 'static'
   40 | char *sd_id128_to_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX]);
      |                                                ^
      |                                                ]
/usr/include/systemd/sd-id128.h:40:48: error: expected ')' before 'static'
   40 | char *sd_id128_to_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX]);
      |                         ~                      ^
      |                                                )
/usr/include/systemd/_sd-common.h:89:30: error: expected initializer before 'static'
   89 | #    define _SD_ARRAY_STATIC static
      |                              ^~~~~~
/usr/include/systemd/sd-id128.h:40:48: note: in expansion of macro '_SD_ARRAY_STATIC'
   40 | char *sd_id128_to_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX]);
      |                                                ^~~~~~~~~~~~~~~~
/usr/include/systemd/_sd-common.h:89:30: error: expected primary-expression before 'static'
   89 | #    define _SD_ARRAY_STATIC static
      |                              ^~~~~~
/usr/include/systemd/sd-id128.h:41:53: note: in expansion of macro '_SD_ARRAY_STATIC'
   41 | char *sd_id128_to_uuid_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_UUID_STRING_MAX]);
      |                                                     ^~~~~~~~~~~~~~~~
/usr/include/systemd/sd-id128.h:41:53: error: expected ']' before 'static'
   41 | char *sd_id128_to_uuid_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_UUID_STRING_MAX]);
      |                                                     ^
      |                                                     ]
/usr/include/systemd/sd-id128.h:41:53: error: expected ')' before 'static'
   41 | char *sd_id128_to_uuid_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_UUID_STRING_MAX]);
      |                              ~                      ^
      |                                                     )
/usr/include/systemd/_sd-common.h:89:30: error: expected initializer before 'static'
   89 | #    define _SD_ARRAY_STATIC static
      |                              ^~~~~~
/usr/include/systemd/sd-id128.h:41:53: note: in expansion of macro '_SD_ARRAY_STATIC'
   41 | char *sd_id128_to_uuid_string(sd_id128_t id, char s[_SD_ARRAY_STATIC SD_ID128_UUID_STRING_MAX]);
```

**Comment by yuwata** [comment]
`__STDC_VERSION__` is not set when compiling c++, and is set by compiler when compiling c. Setting the macro by user sounds super strange for me.

I think the proposed change does not break anything. But, it may confuse people why such redundant conditions are introduced.

Sorry, but please use the alternative way in your code.

**Comment by ctxnop** [comment]
I agree, I dislike having to set the `__STDC_VERSION__`, but it is required by this proprietary lib...
Anyway, I'm okay to use the alternative way.

**Comment by poettering** [comment]
Please ask the people with your proprietary to fix their stuff, instead of asking us to work around it. We generally want that stuff is fixed where it is caused.

Setting  __STDC_VERSION__ is pretty bad btw, it's a macro that is owned by your compiler, not really you.

But what I don't get: why are you not simply `#undef`fing the macro again after the include of the broken library?

**Comment by ctxnop** [comment]
I know that, and I do agree. Nevertheless it happened.

We don't want to `#undef` because it makes g++ to emit a warning.

To be honest, I'm in a yocto context, building full images for embedded target. So I can just apply the patch on my side as I do think that it can't harm. I don't think it adds confusion, actually I think the opposite. Because this macro is not only "undefined" in c++, it is not defined at all. So basically c++ compilers can define it, and anyone is free to define it in a c++ context (even if this is a stupid idea). So, to me, it makes sense to add the check on `__cplusplus` as this syntax is indeed not supported in C++, whatever the version of it.

 I'm also considering patching the broken lib, but this is going to take way more time.

**Comment by smod** [comment]
Note: @ctxnop colleague here, same codebase, same issue, adding some context:

> Please ask the people with your proprietary to fix their stuff, instead of asking us to work around it. We generally want that stuff is fixed where it is caused.

Sure (they won't, we'll workaround). However, we noticed that libsystemd headers are C++ friendly (`_SD_BEGIN_DECLARATIONS`), but are confused when **STDC_VERSION** is also defined to **C99**. Then, we thought it might interest you.

> Setting **STDC_VERSION** is pretty bad btw, it's a macro that is owned by your compiler, not really you.

The proprietary library basically does something like:
```c
#if __STDC_VERSION__ < 199901L
    typedef BlaInt32 long;
#else
    #include <stdint.h>
    typedef BlaInt32 uint32_t;
#endif
```
Without patching it, we have no choice, and AFAIK lots of C headers do such things.

> But what I don't get: why are you not simply `#undef`fing the macro again after the include of the broken library?

That's indeed the underlying issue, however `g++` allows us to `#define` it, but unconditionnaly warns when `#undef`-ing it after. As a result, passing `__STDC_VERSION__` directly to `g++` to make all our C dependencies C99-happy didn't look so bad to us, but it broke here.

Nevertheless, I also think that `_SD_ARRAY_STATIC` should simply never expand to `static` when `__cplusplus` is defined but I too agree that what we have here is a very strange corner case.

**Comment by poettering** [comment]
> Sure (they won't, we'll workaround). However, we noticed that libsystemd headers are C++ friendly (`_SD_BEGIN_DECLARATIONS`), but are confused when **STDC_VERSION** is also defined to **C99**. Then, we thought it might interest you.

Afaics a compiler cannot qualify as both C99 and C++ standards compliant, already because one would identify `class` as a reserved word and the other wouldn't. hence it really doesn't make sense to set both...

**Comment by poettering** [comment]
> We don't want to `#undef` because it makes g++ to emit a warning.

Can't you turn that of with `-Wno-…`?

**Comment by ctxnop** [comment]
> > Sure (they won't, we'll workaround). However, we noticed that libsystemd headers are C++ friendly (`_SD_BEGIN_DECLARATIONS`), but are confused when **STDC_VERSION** is also defined to **C99**. Then, we thought it might interest you.
> 
> Afaics a compiler cannot qualify as both C99 and C++ standards compliant, already because one would identify `class` as a reserved word and the other wouldn't. hence it really doesn't make sense to set both...

I'm not saying that it qualifies as both C99 and C++. I'm saying that any C++ compiler is allowed to define `__STDC_VERSION__` because it's not prevented. It, at first, makes no sense to define it. But it is allowed to:
- define it to zero as to say "this is not C at all"
- define it to an existing version as C++ is allowed to include C files, which are known to test this macro, so it can make sense to define it so that those header behave correctly
- define it to anything because why not?

So, when a C header is included in a C++ context, one should never assume that this "C-only" macro is NOT defined.

Please keep in mind that I'm being really pedantic here just to answer you questions. I do agree that this situation is completely stupid and no one should ever set `__STDC_VERSION__` manually.

**Comment by smod** [comment]
> > We don't want to `#undef` because it makes g++ to emit a warning.
> 
> Can't you turn that of with `-Wno-…`?

Didn't find anything, looks like an "always on" warning: https://godbolt.org/z/WveETavbd

**Comment by ctxnop** [comment]
I don't know if you have access to the ISO C++ standard, here is a link to an online draft about what I'm saying: https://www.ece.uvic.ca/~frodo/cppdraft/n4659/html/cpp.predefined#2.3

It explicitly says that it CAN be defined, and if it is, it then implementation defined.

So assuming that it is not defined in C++ is not standard compliant. Even if none of the compilers I know defines it.

**Comment by poettering** [comment]
> > > We don't want to `#undef` because it makes g++ to emit a warning.
> > 
> > 
> > Can't you turn that of with `-Wno-…`?
> 
> Didn't find anything, looks like an "always on" warning: https://godbolt.org/z/WveETavbd

I presume that's the same output as `-fdiagnostics-show-option` would give you?

**Comment by ctxnop** [comment]
I slept over it and the more I think about it the more I'm convinced that the change should be made.

As I said, the C++ standard [says](https://timsong-cpp.github.io/cppwp/cpp.predefined#2.3):

> Whether `__STDC_­VERSION__` is predefined and if so, what its value is, are implementation-defined[.](https://timsong-cpp.github.io/cppwp/cpp.predefined#2.3.sentence-2)

Because of that, it means that assuming that `__STDC_VERSION__` is not defined in when the file is included by a C++ compiler is an issue. No matter if no current compiler does it, the standard says that it may happen.

As the rest of the file is already full of C++ specific guards, and considering that there is no impact, then I see no reason to reject the change.

Don't get me wrong, I'm not asking you to fix our broken code. As I said, I'm in a yocto context, so I'll will apply this patch nevertheless on my side. Even if you merge it, we won't update to the next release of systemd for a long time because of LTS.

This being said, our broken code put a spotlight onto this issue from systemd, and it should be patched, even if nobody else is currently facing it. This is why I pushed a pull request: #24188

**Comment by smod** [comment]
> I presume that's the same output as `-fdiagnostics-show-option` would give you?

This option didn't help, but you made me curious so I've just dig into gcc codebase:

https://github.com/gcc-mirror/gcc/blob/releases/gcc-12.1.0/libcpp/macro.cc#L3861-L3869
https://github.com/gcc-mirror/gcc/blob/releases/gcc-12.1.0/libcpp/directives.cc#L677-L679

What I found is: whenever a `#define` directive is processed, if it begins with `__STDC_`, it is tagged with a `NODE_WARN` flag, where `NODE_WARN` is later used to unconditionnaly warn if `#undef`ined, this cannot be inhibited. So what we observe seems by design, we can `#define` it once and only once.

**Comment by poettering** [comment]
> What I found is: whenever a `#define` directive is processed, if it begins with `__STDC_`, it is tagged with a `NODE_WARN` flag, where `NODE_WARN` is later used to unconditionnaly warn if `#undef`ined, this cannot be inhibited. So what we observe seems by design, we can `#define` it once and only once.

sounds like something to fix in gcc though... i.e. if the warning for definition can be turned off the warning for undefinition should be something that also can be turned off...
