### ISSUE TITLE
systemctl edit failed (canceled: temporary file is empty)

### ISSUE THREAD

**Issue by irvanherz** [systemd/systemd#24208]
### systemd version the issue has been seen with

systemd 251 (251.2-1-arch)

### Used distribution

Arch Linux 2022.07.01

### Linux kernel version used

5.18.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

The manual said:
```
       edit UNIT...
           Edit a drop-in snippet or a whole replacement file if --full
           is specified, to extend or override the specified unit.

           Depending on whether --system (the default), --user, or
           --global is specified, this command creates a drop-in file
           for each unit either for the system, for the calling user, or
           for all futures logins of all users. Then, the editor (see
           the "Environment" section below) is invoked on temporary
           files which will be written to the real location if the
           editor exits successfully.
```

### Unexpected behaviour you saw

However, I got a message  like this:
```
Editing "/etc/systemd/system/nats-server.service.d/override.conf" canceled: temporary file is empty.
```

### Steps to reproduce the problem

Run systemctl edit on any service

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[irvan@arch ~]$ systemctl --version
systemd 251 (251.2-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
[irvan@arch ~]$ sudo systemctl edit nats-server
[sudo] password for irvan: 
Editing "/etc/systemd/system/nats-server.service.d/override.conf" canceled: temporary file is empty.
[irvan@arch ~]$
```

**Comment by poettering** [comment]
hmm, do you have an editor installed? i.e. one of vim/vi/emacs/nano? do you have $EDITOR set or so?

**Comment by irvanherz** [comment]
Sorry, my mistake.
I've put the new configuration line in the wrong place 😅
This issue can be closed now.

**Comment by lukedupin** [comment]
For clarification, this is a really common error to run into. When you run systemd edit, everything is commented out INCLUDING THE SECTIONS. If a user isn't paying attention, its easy to add a valid rule under a commented out section, which will result in this "semi misleading" error. It's not that the temporary file is empty, the file doesn't have any uncommented sections.

For example, this will cause the error -> systemctl edit postgresql.service:
```
# [Service]
# Type=notify
# TimeoutSec=120
# User=postgres
# Group=postgres
TimeoutSec=60
```

Notice [Service] is commented out? Nothing on the dev's end needs to happen, but I wanted to leave this message here for the next person that runs into this situation the way I did.

**Comment by tuckerrc** [comment]
Another point of clarification. In Ubuntu 22.04.2 (maybe others) there are a few important comments that I missed. 

The file that opens is completely commented out but the first few lines look like this

```
### Editing /etc/systemd/system/NetworkManager.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file



### Lines below this comment will be discarded
```

Any edits you make need to be between these two comment blocks.

**Comment by keszybz** [comment]
Suggestions how to improve the text are welcome.

**Comment by tuckerrc** [comment]
I think the text is fine...I just completely missed it. I uncommented some of the example text and edited it. I was confused why it didn't work when saving the file. Asking the internet brought me here and I wanted to make a note for future searchers.

**Comment by lukedupin** [comment]
If the text said something along the lines "No valid sections found, were all the sections commented out?" That would pretty clearly let the users know what they did and how to fix it.

**Comment by jamesisin** [comment]
Or perhaps a line at the bottom that said something about seeing the section above for adding anything.  ("Don't add things here; add them up above.")

**Comment by martin3000** [comment]
Thank you for pointing me in the right direction!

**Comment by chiralsoftware** [comment]
> The file that opens is completely commented out but the first few lines look like this

Thank you for that suggestion. I put the [Service] and the value in that area, saved and it worked. The error is definitely not clear about what's causing it to fail.

**Comment by Stoppedwumm** [comment]
> > The file that opens is completely commented out but the first few lines look like this
> 
> Thank you for that suggestion. I put the [Service] and the value in that area, saved and it worked. The error is definitely not clear about what's causing it to fail.

Not for me, still refuses Connection

**Comment by FajnB** [comment]
> Suggestions how to improve the text are welcome.

I'd personally capitalise the letters of warning so that it is way harder to miss it. I know it might sound stupid, but it definitely captures admin's/user's attention as it is not common and thus will more likely look what it is.
It would look like this.

```
### Editing /etc/systemd/system/NetworkManager.service.d/override.conf
### ANYTHING BETWEEN HERE AND THE COMMENT BELOW WILL BECOME THE NEW CONTENTS OF THE FILE



### LINES BELOW THIS COMMENT WILL BE DISCARDED
```

Also there could be some fail-check that if there was anything changed underneath the valid area .ie. if there is anything beyond new line or comment (#) symbols as a first character of the line, give error message something like:
"_Modifications were made in an invalid section of the config file._"

As for if the user does not define section it can be something similar to what lukedupin said
> If the text said something along the lines "No valid sections found, were all the sections commented out?" That would clearly explain the mistake.

I'd personally also add "_...sections commented out / defined?_"

**Comment by mercster** [comment]
I'm having a hard time grok'ing why it works this way.  I want to change 2 lines in a long override.conf file.  I have to... put the lines I want to edit at the top...?  then uncomment other lines?  This process is wonky.  Why wouldn't anyone sane just cp the existing conf file over to override.conf and edit that in place and in peace.

**Comment by joehuangLGS** [comment]
> Another point of clarification. In Ubuntu 22.04.2 (maybe others) there are a few important comments that I missed.
> 
> The file that opens is completely commented out but the first few lines look like this
> 
> ```
> ### Editing /etc/systemd/system/NetworkManager.service.d/override.conf
> ### Anything between here and the comment below will become the new contents of the file
> 
> 
> 
> ### Lines below this comment will be discarded
> ```
> 
> Any edits you make need to be between these two comment blocks.

It's really helpful until I look this comment. :)

**Comment by n-zhi** [comment]
I also encountered this problem. On Ubuntu 24.04 I wasn't getting any error messages at all. The file simply wasn't being created when I tried to edit the Unit section itself and completely missed the text at the top

**Comment by Aracki** [comment]
For me it helped not to edit with systemctl but to edit myself 
```
vim /etc/systemd/system/<SERVICE>
```

**Comment by q2dg** [comment]
systemctl edit DOESN'T WORK: it doesn't create any override.conf file nor saves any change. It's a broken command. Please, ammend it!!

**Comment by kzajac83** [comment]
Well, for me still not working 

```
root@wyse:~# systemctl edit wmbusmeters.service
Editing "/etc/systemd/system/wmbusmeters.service.d/override.conf" canceled: temporary file is empty.
```

But I save the changes (in my example under file:   /etc/systemd/system/wmbusmeters.service.d/.#override.conf00063c683c2fadbb), try many times. Issie is still exist 


```
root@wyse:~# systemctl --version
systemd 252 (252.39-1~deb12u1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

```

**Comment by q2dg** [comment]
Issue closed from three years ago but without any solution. It's incredible.

**Comment by yuwata** [comment]
@q2dg @kzajac83 I cannot find anything related to the original issue in your comments. Please open a new issue with detailed explanation and debugging logs. Also, reproduce the issue with a recent release. v252 is too old here.

**Comment by a-carvallo** [comment]
Maybe it can help other people, if you **actually** want to cancel the override you cannot just run `systemctl edit <service>` and remove your changes but instead need to run `systemctl revert <service>`.

It feels like the message could have mentioned that...
