### ISSUE TITLE
Failed to configure DHCPv4 client: Device or resource busy

### ISSUE THREAD

**Issue by TheEdgeOfRage** [systemd/systemd#24201]
### systemd version the issue has been seen with

systemd 251.3-1

### Used distribution

ArchLinux (up-to-date)

### Linux kernel version used

5.18.16-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Get IPv4 address from DHCP server

### Unexpected behaviour you saw

Networkd sometimes fails to configure the DHCPv4 client to get an IPv4 address during boot. Restarting the service after logging in fixes the issue. I assume that the "Device or resource busy" message means that either the hardware wasn't ready yet, or something else is locking the NIC. I don't have any other network managers running, so I'm not sure what could be interfering here.

### Steps to reproduce the problem

Hard to say really, it only happens sometimes when booting, sometimes consecutively. I'd say about 1 in 4 or so boots fails to configure the adapter.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Aug 04 11:12:52 cuprum systemd[1]: Starting Network Configuration...
Aug 04 11:12:52 cuprum systemd-networkd[470]: lo: Link UP
Aug 04 11:12:52 cuprum systemd-networkd[470]: lo: Gained carrier
Aug 04 11:12:52 cuprum systemd-networkd[470]: Enumeration completed
Aug 04 11:12:52 cuprum systemd[1]: Started Network Configuration.
Aug 04 11:12:53 cuprum systemd-networkd[470]: tailscale0: Link UP
Aug 04 11:12:53 cuprum systemd-networkd[470]: tailscale0: Gained carrier
Aug 04 11:12:53 cuprum systemd-networkd[470]: tailscale0: Gained IPv6LL
Aug 04 11:12:58 cuprum systemd-networkd[470]: eth0: Interface name change detected, renamed to enp6s0.
Aug 04 11:12:58 cuprum systemd-networkd[470]: enp6s0: Configuring with /etc/systemd/network/20-wired.network.
Aug 04 11:12:58 cuprum systemd-networkd[470]: enp6s0: Failed to configure DHCPv4 client: Device or resource busy
Aug 04 11:12:58 cuprum systemd-networkd[470]: enp6s0: Failed
```
```

**Comment by yuwata** [comment]
Please provide debugging logs of networkd. It can be generated by creating the following drop-in:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_MESSAGE=debug
```

**Comment by TheEdgeOfRage** [comment]
Since enabling debugging, the issue hasn't come back. It might have just been a bug in the kernel or somewhere else and got fixed with an update :shrug:

I'll close this for now
