### ISSUE TITLE
machinectl: pass options to invoked shell command

### ISSUE THREAD

**Issue by gdzx** [systemd/systemd#2420]
Options specified after the path in `machinectl shell [[USER@]NAME [COMMAND...]]` are currently interpreted by `machinectl` itself.

```
$ machinectl shell root@archlinux /usr/bin/pacman -Syu
machinectl: invalid option -- 'S'
```

Maybe we should be able to pass options to the invoked command.

P.S.: Weird example:

```
$ machinectl shell root@archlinux '/bin/echo foo bar'
Connected to machine archlinux. Press ^] three times within 1s to exit session.
bar -bin/echo foo bar
Connection to machine archlinux terminated.
```

**Comment by poettering** [comment]
Well, getopt() isn't flexible enough to allow this really, I fear...

Note that inserting "--" in the command line will end the processing of arguments by machinectl, and is a standard GNU way to do this.

**Comment by keszybz** [comment]
What about `+`: "If the first character of optstring is '+' or the environment  variable POSIXLY_CORRECT is set, then option processing stops as soon as a nonoption argument is encountered."

**Comment by poettering** [comment]
@keszybz doesn't work, since we want this logic only for "machinectl shell" but not for the other commands, and that's something you cannot really do with getopt.

**Comment by keszybz** [comment]
Ah, OK. But it should be relatively easily to implement by hand if somebody wanted to... Before calling getopt walk argv by hand, and replace the first non-option argument after shell with NULL, then call getopt(), and then restore the argument to previous value. Or something like that. Hacky, but the sudo syntax is so nice.

If we don't implement this, we should add a note to the man page that option arguments might be interpreted by the shell command one day, even if they are not currently, so people don't start relying on putting options there.

**Comment by gdzx** [comment]
@poettering Thanks. `machinectl shell root@archlinux -- /usr/bin/pacman -Syu` is good enough. Maybe we could add this example to the `machinectl` man page.

**Comment by poettering** [comment]
@keszybz it's not that easy to walk the array.... after all if we see "--foo shell" while walking, then this could mean:
1. there's an option "--foo" and its parameter is "shell"
2. there's an option "--foo" with no parameter, which is then followed by the verb "shell" we are looking for

To discern these two cases walking the argv[] requires a full understanding of getopt() parameter list really I fear...
