### ISSUE TITLE
credential passwd.plaintext-password.root too long for qemu fw_cfg

### ISSUE THREAD

**Issue by lnussel** [systemd/systemd#24204]
### systemd version the issue has been seen with

251

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

5.18.4-1-default

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

There is a 55 character limit on qemu fw_cfg name strings. The credential name `opt/io.systemd.credentials/passwd.plaintext-password.root` exceeds that limit so can't actually be used that way :-)

Change to e.g. `opt/io.systemd.credentials/passwd.plaintext.root` instead?

### Steps to reproduce the problem

```
$ qemu-system-x86_64 -enable-kvm -device virtio-blk,drive=hd1 -drive file=/space/lnussel/git/reflink/testimg.raw,cache=unsafe,if=none,id=hd1 -machine type=q35,accel=kvm -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -smp 2 -snapshot -m 1024 -bios /usr/share/qemu/ovmf-x86_64.bin -serial stdio -vnc :1 -fsdev local,security_model=none,id=fsdev0,path=/space/lnussel/git/reflink -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=build-srcdir -fw_cfg name=opt/io.systemd.credentials/passwd.plaintext-password.root,string=1235
qemu-system-x86_64: -fw_cfg name=opt/io.systemd.credentials/passwd.plaintext-password.root,string=1235: name too long (max. 55 char)
```

**Comment by bluca** [comment]
unfortunate, as it's a well-defined name already - note that from 252 we will also support SMBIOS strings, which hopefully doesn't have the same issue

**Comment by poettering** [comment]
Christ, 55 chars? wtf...

I guess yeah, we should advocate SMBIOS stuff more.

**Comment by poettering** [comment]
fw_cfg is one way to propagate creds into a system. we now support smbios, sd-stub ESP pickup, kernel cmdline, fw_cfg, nspawn creds passing at least. Given that fw_cfg is one of the weakest of these I think we should probably document the limit here, and then ask people to use the SMBIOS stuff instead.

Or to say this differently: we already landed a fix for the issue at hand here: the SMBIOS hookup.

**Comment by lnussel** [comment]
so fw_cfg is considered deprecated in general in favor of smbios

smbios didn't seem to work so I tried fw_cfg. Turns out reading smbios settings requires dmi-sysfs which is a module on opensuse that is not loaded automatically. fw_cfg OTOH is loaded in initrd already as dracut puts it there. On Fedora dmi-sysfs is built in. If dmi-sysfs is preferred I'll ask to make opensuse load it by default.

**Comment by bluca** [comment]
yeah smbios is preferred as it seems to be available across many VMMs, it would be great if you could get that updated in suse
