### ISSUE TITLE
'systemd-run' | Accomplishment of invoked action fails

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#24219]
### systemd version the issue has been seen with

251 (built from systemd-251.tar.gz)

### Used distribution

Fedora

### Linux kernel version used

5.18.15-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

Accomplishment of invoked action

### Unexpected behaviour you saw

Invoked action not accomplished

### Steps to reproduce the problem

```
$ sudo systemd-run --on-active=2 /bin/touch 0
Running timer as unit: run-r2704a01b077e453cb35be47bcdcae33f.timer
Will run service as unit: run-r2704a01b077e453cb35be47bcdcae33f.service
```
Hello. Once two seconds have elapsed from the time of execution of the above command, it appears the accomplishment of the requested file creation failed.
```
$ ls 0
ls: cannot access '0': No such file or directory
```

**Comment by mrc0mmand** [comment]
That's because you're running the `systemd-run` command with `sudo`, thus changing the working directory for the `touch` command. In this case the full path of the `0` file is `/0`, not your current working directory:

```
$ sudo systemd-run --on-active=2 /bin/touch 0
Running timer as unit: run-r17c1dd3f156d42ed8fa393292d91bf1e.timer
Will run service as unit: run-r17c1dd3f156d42ed8fa393292d91bf1e.service
$ stat 0
stat: cannot statx '0': No such file or directory
$ stat /0
  File: /0
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 253,1	Inode: 2551        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-08-05 20:39:00.829300322 +0200
Modify: 2022-08-05 20:39:00.829300322 +0200
Change: 2022-08-05 20:39:00.829300322 +0200
 Birth: 2022-08-05 20:39:00.829300322 +0200
```

This is expected, not a bug.
