### ISSUE TITLE
meson.build | Incoherent warning related to attempt of using a feature

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#24218]
### systemd version the issue has been seen with

systemd-251.tar.gz

### Used distribution

Fedora

### Linux kernel version used

5.18

### Expected behaviour you didn't see

Absence of production of warning by Meson.

### Unexpected behaviour you saw

```
# ./configure
(...)
meson.build:2129: WARNING: Project targeting '>= 0.53.2' but tried to use feature introduced in '0.60.0': install_tag arg in meson.add_install_script.
(...)
```
Despite that warning, whose formulation i am unable to comprehend, the installation of _systemd_ component was successful.

Noticing the incoherence of the sentence "_Project targeting '>= 0.53.2' but tried to use feature introduced in '0.60.0_"; **0.60.0** is dully **>= 0.53.2**; thus that cannot be a "_but_" that the sentence requires in order to be coherent.

### Steps to reproduce the problem

```
# dnf -y install intltool gperf meson python3-jinja2 libcap-devel
$ rpm -q meson
meson-0.62.2-1.fc36.noarch
# ./configure
```

**Comment by bluca** [comment]
It's backward-compatible, you can ignore it
