### ISSUE TITLE
davfs stuck at shutdown/reboot

### ISSUE THREAD

**Issue by sthibaul** [systemd/systemd#24212]
### systemd version the issue has been seen with

251.3

### Used distribution

Debian bookworm

### Linux kernel version used

5.19.0

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Shutdown/reboot should proceed quickly, surely less than 90s.

### Unexpected behaviour you saw

The shutdown/reboot gets stuck for 90s without making progress

### Steps to reproduce the problem

This happens whenever I mount a davfs volume. In `/etc/fstab` I have

```
https://foo.bar.com/directory/ /net/directory davfs defaults,noauto 0 0
```

From a console session (without X/wayland started at all) I use `sudo mount /net/directory`, type my login and password. Then I type `sudo reboot` or `sudo shutdown`. After killing various daemons, systemd gets stuck for 90s before achieving actual reboot/shutdown.

In the same exact conditions (fresh reboot), if I don't `mount /net/directory`, or if I umount it before shutdown/reboot, I don't have the 90s pause.

### Additional program output to the terminal or log subsystem illustrating the issue

This shows up in journalctl, showing the 90s pause:

```log
[...]
août 05 11:28:59 begin acpid[908]: exiting
août 05 11:28:59 begin systemd[1]: acpid.service: Deactivated successfully.
août 05 11:28:59 begin systemd[1]: Stopped ACPI event daemon.
août 05 11:28:59 begin systemd[1]: systemd-fsckd.service: Deactivated successfully.
août 05 11:28:59 begin vmware-USBArbitrator[2732]: [10B blob data]
août 05 11:28:59 begin systemd[1]: vmware-USBArbitrator.service: Deactivated successfully.
août 05 11:28:59 begin systemd[1]: Stopped LSB: This services starts and stops the USB Arbitrator..
août 05 11:28:59 begin systemd[1]: vmware-USBArbitrator.service: Consumed 5.404s CPU time.
août 05 11:30:27 begin systemd[1]: session-1.scope: Stopping timed out. Killing.
août 05 11:30:27 begin systemd[1]: session-1.scope: Killing process 2644 (mount.davfs) with signal SIGKILL.
août 05 11:30:27 begin systemd[1]: session-1.scope: Failed with result 'timeout'.
août 05 11:30:27 begin systemd[1]: Stopped Session 1 of User samy.
août 05 11:30:27 begin systemd[1]: session-1.scope: Consumed 1.515s CPU time.
août 05 11:30:27 begin systemd[1]: Stopping User Login Management...
août 05 11:30:27 begin systemd[1]: Stopping User Manager for UID 1000...
août 05 11:30:27 begin systemd-logind[945]: Removed session 1.
août 05 11:30:27 begin systemd[1914]: Activating special unit Exit the Session...
août 05 11:30:27 begin systemd[1914]: Stopped target Main User Target.
août 05 11:30:27 begin systemd[1914]: Stopping dbus-:1.2-org.gnome.Identity@0.service...
août 05 11:30:27 begin systemd[1914]: Stopping dbus-:1.2-org.gnome.OnlineAccounts@0.service...
```

So it does seem it's mount.davfs which does not go down automatically. When I run systemd-cgls, that process is indeed within that session scope, and completely belongs to the davfs2 user (all the four *uid are davfs2)

Possibly that's related to https://github.com/systemd/systemd/issues/23580 which seems to be attempting to kill the mount when the user gets logged out.

**Comment by poettering** [comment]
So it seems your mount.davfs binary is not reacting to SIGTERM, hence gets killed by SIGKILL. 

But systemd is working here as it should, hence where is the problem?

**Comment by sthibaul** [comment]
Right, let me check with davfs
