### ISSUE TITLE
'Failed to start transient timer unit: Action org.freedesktop.systemd1.manage-units is not registered'

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#24227]
### systemd version the issue has been seen with

251 (built from systemd-251.tar.gz)

### Used distribution

Fedora

### Linux kernel version used

5.18.15-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

Uninhibited execution; thus:
```
$ systemd-run --on-active=2 /bin/touch 0
Running timer as unit: run-r(...).timer
Will run service as unit: run-r(...).service
```

### Unexpected behaviour you saw

Inhibited execution.
```
$ systemd-run --on-active=2 /bin/touch 0
Failed to start transient timer unit: Action org.freedesktop.systemd1.manage-units is not registered
```

### Steps to reproduce the problem

Hello. the execution of the involved command was operational in same OS being as virtual machine. Now executed while being in physical machine.
```
# dnf -y install intltool gperf meson python3-jinja2 libcap-devel && ./configure && make && make install
$ systemd-run --on-active=2 /bin/touch 0
```

**Comment by poettering** [comment]
> # dnf -y install intltool gperf meson python3-jinja2 libcap-devel && ./configure && make && make install
> $ systemd-run --on-active=2 /bin/touch 0

Are you saying you built systemd yourself? and just installed it over the already installed version?

The issue you are seeing suggests the polkit files from the systemd tree are not properly installed. But this isn't really a bug, but more of a support issue. Generally, unless you really know what you are doing you should not just install systemd from sources over your installed version, this is likely going to break.

Anyway, let's close this. This is not the right forum. Consider contacting the mailing list for help, but this issue tracker is not the right place.
