### ISSUE TITLE
systemd-backlight service not restoring backlight brightess on amdgpu_bl0

### ISSUE THREAD

**Issue by Rubonnek** [systemd/systemd#24223]
### systemd version the issue has been seen with

251

### Used distribution

Arch Linux

### Linux kernel version used

5.18.16-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Backlight setting restored after rebooting.

### Unexpected behaviour you saw

Backlight setting was never restored. Screen brightness is always at maximum after rebooting.

### Steps to reproduce the problem

On the following hardware:
```
        Manufacturer: LENOVO
        Product Name: 82K8
        Version: Legion S7 15ACH6
```
Change screen backlight setting and reboot.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Aug 05 20:26:20 hemera systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0...
Aug 05 20:26:20 hemera systemd-backlight[674]: amdgpu_bl0: Maximum brightness is 255
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scan all dirs
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scanning /sys/bus
Aug 05 20:26:20 hemera systemd-backlight[674]: sd-device-enumerator: Scanning /sys/class
Aug 05 20:26:20 hemera systemd-backlight[674]: Skipping backlight device amdgpu_bl0, since device nvidia_wmi_ec_backlight is a platform device and takes prec>
Aug 05 20:26:20 hemera systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:amdgpu_bl0.
```

**Comment by poettering** [comment]
hmm, you system has both an AMD GPU and an nvidia one?

**Comment by yuwata** [comment]
Could you show the result of `udevadm info --tree /sys/class/backlight/amdgpu_bl0` and `/sys/class/backlight/nvidia_wmi_ec_backlight` (and also other devices if there exist other backlight devices in /sys/class/backlight)?

**Comment by Rubonnek** [comment]
> hmm, you system has both an AMD GPU and an nvidia one?

Correct. In fact, through the BIOS I can disable the integrated GPU (AMD), and only leave the discrete one (NVIDIA).

If I disable the integrated GPU, I'm not able to configure the brightness at all. I tried changing the values of the remaining brightness settings in`/sys/class/backlight/*/brightness` but the screen brightness didn't change. The values changed within sysfs though, but that was it. I'm guessing that may be an issue with the kernel itself, I'm not sure.

> Could you show the result of `udevadm info --tree /sys/class/backlight/amdgpu_bl0` and `/sys/class/backlight/nvidia_wmi_ec_backlight` (and also other devices if there exist other backlight devices in /sys/class/backlight)?

Sure.

```bash
udevadm info --tree /sys/class/backlight/amdgpu_bl0
└─/devices/pci0000:00/0000:00:08.1
  ┆ P: /devices/pci0000:00/0000:00:08.1
  ┆ M: 0000:00:08.1
  ┆ R: 1
  ┆ U: pci
  ┆ V: pcieport
  ┆ E: DEVPATH=/devices/pci0000:00/0000:00:08.1
  ┆ E: SUBSYSTEM=pci
  ┆ E: DRIVER=pcieport
  ┆ E: PCI_CLASS=60400
  ┆ E: PCI_ID=1022:1635
  ┆ E: PCI_SUBSYS_ID=1022:1635
  ┆ E: PCI_SLOT_NAME=0000:00:08.1
  ┆ E: MODALIAS=pci:v00001022d00001635sv00001022sd00001635bc06sc04i00
  ┆ E: USEC_INITIALIZED=1330045
  ┆ E: ID_PCI_CLASS_FROM_DATABASE=Bridge
  ┆ E: ID_PCI_SUBCLASS_FROM_DATABASE=PCI bridge
  ┆ E: ID_PCI_INTERFACE_FROM_DATABASE=Normal decode
  ┆ E: ID_VENDOR_FROM_DATABASE=Advanced Micro Devices, Inc. [AMD]
  ┆ E: ID_MODEL_FROM_DATABASE=Renoir Internal PCIe GPP Bridge to Bus
  └─0000:05:00.0
    ┆ P: /devices/pci0000:00/0000:00:08.1/0000:05:00.0
    ┆ M: 0000:05:00.0
    ┆ R: 0
    ┆ U: pci
    ┆ V: amdgpu
    ┆ E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:05:00.0
    ┆ E: SUBSYSTEM=pci
    ┆ E: DRIVER=amdgpu
    ┆ E: PCI_CLASS=30000
    ┆ E: PCI_ID=1002:1638
    ┆ E: PCI_SUBSYS_ID=17AA:380C
    ┆ E: PCI_SLOT_NAME=0000:05:00.0
    ┆ E: MODALIAS=pci:v00001002d00001638sv000017AAsd0000380Cbc03sc00i00
    ┆ E: USEC_INITIALIZED=1339706
    ┆ E: ID_PCI_CLASS_FROM_DATABASE=Display controller
    ┆ E: ID_PCI_SUBCLASS_FROM_DATABASE=VGA compatible controller
    ┆ E: ID_PCI_INTERFACE_FROM_DATABASE=VGA controller
    ┆ E: ID_VENDOR_FROM_DATABASE=Advanced Micro Devices, Inc. [AMD/ATI]
    ┆ E: ID_MODEL_FROM_DATABASE=Cezanne
    └─backlight/amdgpu_bl0
      ┆ P: /devices/pci0000:00/0000:00:08.1/0000:05:00.0/backlight/amdgpu_bl0
      ┆ M: amdgpu_bl0
      ┆ R: 0
      ┆ U: backlight
      ┆ E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:05:00.0/backlight/amdgpu_bl0
      ┆ E: SUBSYSTEM=backlight
      ┆ E: USEC_INITIALIZED=3828770
      ┆ E: ID_PATH=pci-0000:05:00.0
      ┆ E: ID_PATH_TAG=pci-0000_05_00_0
      ┆ E: ID_FOR_SEAT=backlight-pci-0000_05_00_0
      ┆ E: SYSTEMD_WANTS=systemd-backlight@backlight:amdgpu_bl0.service
      ┆ E: TAGS=:seat:systemd:
      ┆ E: CURRENT_TAGS=:seat:systemd:
```

```bash
udevadm info --tree /sys/class/backlight/nvidia_wmi_ec_backlight
└─/devices/pci0000:00/PNP0C14:00
  ┆ P: /devices/pci0000:00/PNP0C14:00
  ┆ M: PNP0C14:00
  ┆ R: 00
  ┆ U: platform
  ┆ V: acpi-wmi
  ┆ E: DEVPATH=/devices/pci0000:00/PNP0C14:00
  ┆ E: SUBSYSTEM=platform
  ┆ E: DRIVER=acpi-wmi
  ┆ E: MODALIAS=acpi:PNP0C14:
  ┆ E: USEC_INITIALIZED=1125917
  ┆ E: ID_PATH=platform-PNP0C14:00
  ┆ E: ID_PATH_TAG=platform-PNP0C14_00
  └─wmi_bus/wmi_bus-PNP0C14:00
    ┆ P: /devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00
    ┆ M: wmi_bus-PNP0C14:00
    ┆ R: 00
    ┆ U: wmi_bus
    ┆ E: DEVPATH=/devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00
    ┆ E: SUBSYSTEM=wmi_bus
    └─603E9613-EF25-4338-A3D0-C46177516DB7
      ┆ P: /devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/603E9613-EF25-4338-A3D0-C46177516DB7
      ┆ M: 603E9613-EF25-4338-A3D0-C46177516DB7
      ┆ R: 7
      ┆ U: wmi
      ┆ T: method
      ┆ V: nvidia-wmi-ec-backlight
      ┆ E: DEVPATH=/devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/603E9613-EF25-4338-A3D0-C46177516DB7
      ┆ E: SUBSYSTEM=wmi
      ┆ E: DEVTYPE=method
      ┆ E: DRIVER=nvidia-wmi-ec-backlight
      ┆ E: MODALIAS=wmi:603E9613-EF25-4338-A3D0-C46177516DB7
      ┆ E: WMI_GUID=603E9613-EF25-4338-A3D0-C46177516DB7
      └─backlight/nvidia_wmi_ec_backlight
        ┆ P: /devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/603E9613-EF25-4338-A3D0-C46177516DB7/backlight/nvidia_wmi_ec_backlight
        ┆ M: nvidia_wmi_ec_backlight
        ┆ U: backlight
        ┆ E: DEVPATH=/devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/603E9613-EF25-4338-A3D0-C46177516DB7/backlight/nvidia_wmi_ec_backlight
        ┆ E: SUBSYSTEM=backlight
        ┆ E: USEC_INITIALIZED=1568625
        ┆ E: ID_PATH=platform-PNP0C14:00
        ┆ E: ID_PATH_TAG=platform-PNP0C14_00
        ┆ E: ID_FOR_SEAT=backlight-platform-PNP0C14_00
        ┆ E: SYSTEMD_WANTS=systemd-backlight@backlight:nvidia_wmi_ec_backlight.service
        ┆ E: TAGS=:systemd:seat:
        ┆ E: CURRENT_TAGS=:systemd:seat:
```

**Comment by yuwata** [comment]
Thanks. Could you also show the results of `udevadm info --attribute-walk` for these backlight devices?

**Comment by Rubonnek** [comment]
Sure. The output is very verbose for some so I've attached the output as files instead:

* [attribute-walk_amdgpu_bl0.txt](https://github.com/systemd/systemd/files/9283166/attribute-walk_amdgpu_bl0.txt)
* [attribute-walk_nvidia_0.txt](https://github.com/systemd/systemd/files/9283167/attribute-walk_nvidia_0.txt)
* [attribute-walk_nvidia_wmi_ec_backlight.txt](https://github.com/systemd/systemd/files/9283168/attribute-walk_nvidia_wmi_ec_backlight.txt)

**Comment by yuwata** [comment]
Thank you!

**Comment by yuwata** [comment]
Unfortunately, I do not have any good way to gracefully solve the issue. With PR #24250, you can save/load the backlight level for amdbpu_bl0. But, at the same time, you can now also save/load that for nvidia_0. You may need to call `systemctl mask systemd-backlight@backlight:nvidia_0.service` to make the service not interfere `nvidia_wmi_ec_backlight` backlight device.

Anyway, @Rubonnek if possible, could you test the PR?

**Comment by Rubonnek** [comment]
#24250 restores the brightness on both `amdgpu_bl0` and `nvidia_wmi_ec_backlight`. The value on `nvidia_0` resets upon reboot. For my use case, #24250 fixes the issue for me since `amdgpu_bl0` controls the physical screen brightness -- the rest of the devices don't.

**Comment by poettering** [comment]
Hmm, so do I get this right, you have a three backlight devices, of which two do not work *at* *all*?

That sounds like a kernel/driver issue: they shouldn't expose a device that has no effect.

**Comment by Rubonnek** [comment]
> Hmm, so do I get this right, you have a three backlight devices, of which two do not work _at_ _all_?

Well, I should have said I don't think two of them work. I suppose there could be something within the laptop casing that I can't see, but I'm not willing to open it. From the outside I don't see any notable changes when tweaking `nvidia_wmi_ec_backlight` and `nvidia_0`. Only `amdgpu_bl0` seems to matter for the screen brightness.

**Comment by yuwata** [comment]
@poettering 
Even if the reporter's laptop erroneously reports unnecessary backlight devices, the issue is potentially occurs on multi-GPU systems. E.g. a machine has multiple graphics cards and each has own LCD which supports backlight control.

**Comment by poettering** [comment]
> Even if the reporter's laptop erroneously reports unnecessary backlight devices, the issue is potentially occurs on multi-GPU systems. E.g. a machine has multiple graphics cards and each has own LCD which supports backlight control.

But this sounds like something the graphics drivers should detect somehow, i.e. that there are backlight control devices with zero effect...

Or if there's really no way, we should have an hwdb that tests against DMI...

**Comment by yuwata** [comment]
> > Even if the reporter's laptop erroneously reports unnecessary backlight devices, the issue is potentially occurs on multi-GPU systems. E.g. a machine has multiple graphics cards and each has own LCD which supports backlight control.
> 
> But this sounds like something the graphics drivers should detect somehow, i.e. that there are backlight control devices with zero effect...

I agree with that and hope so. But the issue is in a quite different level. The kernel may expose multiple backlight devices per GPU, and we have a workaround for that with `validate_device()`. But unfortunately, the function does not consider the multi GPU systems.
In short, the issue is that we have a buggy workaround, hence we need to fix it.

> Or if there's really no way, we should have an hwdb that tests against DMI...

If there is a way to test DMI or so, then that's OK. But I have no idea.
I think, `validate_device()` is just a workaround for filtering out unnecessary backlight devices. Hence, we should gracefully give up to handle unexpected cases, like multi GPU systems.
