### ISSUE TITLE
Execute <lsmod> failed after <udevadm control --reload-rules && udevadm trigger>

### ISSUE THREAD

**Issue by ZYLN** [systemd/systemd#24236]
### systemd version the issue has been seen with

219

### Used distribution

CentOS7.4

### Linux kernel version used

5.15.6

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

Execute <lsmod> failed after <udevadm control --reload-rules && udevadm trigger>.

# Log 1
for i in {1..1000}; do udevadm trigger;lsmod>/dev/null; sleep 2s; done

libkmod: kmod_module_get_holders: could not open '/sys/module/fjes/holders': No such file or directory
libkmod: kmod_module_get_holders: could not open '/sys/module/fjes/holders': No such file or directory
libkmod: kmod_module_get_holders: could not open '/sys/module/acpi_cpufreq/holders': No such file or directory

# Log 2
for i in {1..1000}; do udevadm trigger;udevadm settle;lsmod>/dev/null; sleep 2s; done
libkmod: kmod_module_get_holders: could not open '/sys/module/acpi_cpufreq/holders': No such file or directory

**Comment by poettering** [comment]
"lsmod" is not part of systemd. Also systemd v219 is waaaaaaaaaaaaaaaaaaaaaaay to old to be tracked here.

Please contakt kmod people. And update your OS first to something reasonably recent. Noone is helped with bug reports of software that has long been updated and quite possible been fixed
