### ISSUE TITLE
hwdb modalias matching issue on aarch64

### ISSUE THREAD

**Issue by leezu** [systemd/systemd#24232]
### systemd version the issue has been seen with

251

### Used distribution

Debian Testing

### Linux kernel version used

5.19.0

### CPU architectures issue was seen on

aarch64

### Component

hardware database files

### Expected behaviour you didn't see

In /etc/udev/hwdb.d/61-sensor-local.hwdb, I would expect the following rule to match on my system

```
sensor:modalias:platform:cros-ec-accel
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
```

### Unexpected behaviour you saw

Above rule did not take effect. Only the following catch-all rule would work:

```
sensor:modalias:platform:*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
```

### Steps to reproduce the problem

Get a Chromebook with aarch64 chip. Install Linux in developer mode. Observe `sudo su -s /bin/sh geoclue -c monitor-sensor` shows the sensor reads "upside down". Try fixing with first rule that matches the sensor's modalias.

### Additional program output to the terminal or log subsystem illustrating the issue

Note that CONFIG_DMIID documented in 60-sensor.hwdb is not applicable to the aarch64 platform.

https://github.com/systemd/systemd/blob/2fb11652381c199ad19bb469e530543366d99dd4/hwdb.d/60-sensor.hwdb#L13-L18

I suspect there is some x86 related behavior hardcoded that breaks the modalias based matching on aarch64 systems.

Once this is fixed, all the rules for individual chromebooks at

https://github.com/systemd/systemd/blob/2fb11652381c199ad19bb469e530543366d99dd4/hwdb.d/60-sensor.hwdb#L406-L430

can be replaced by a single rule matching all `sensor:modalias:platform:cros-ec-accel` as the `ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1` on all Chromebooks.

**Comment by poettering** [comment]
As we do not possess a device like this this is not really actionable for us. Happy to take a patch that addresses this issue though.

**Comment by leezu** [comment]
Do you know which part of the code handles parsing and matching of the strings like `sensor:modalias:platform:cros-ec-accel` and `sensor:modalias:*`? The device I used to find this issue is CP513-1H-S60F (US) or CP513-1H-S6RG (DE)

**Comment by alpernebbi** [comment]
This one seems to work for me, on a rk3399-gru-kevin:

```
# /etc/udev/hwdb.d/61-sensors-local.hwdb
sensor:modalias:platform:cros-ec-accel:*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
```

I can see it apply after running a few things:

```
$ sudo systemd-hwdb update
$ sudo udevadm trigger
$ sudo udevadm info /dev/iio*
P: /devices/platform/ff100000.saradc/iio:device0
M: iio:device0
R: 0
U: iio
T: iio_device
D: c 240:0
N: iio:device0
L: 0
E: DEVPATH=/devices/platform/ff100000.saradc/iio:device0
E: DEVNAME=/dev/iio:device0
E: DEVTYPE=iio_device
E: OF_NAME=saradc
E: OF_FULLNAME=/saradc@ff100000
E: OF_COMPATIBLE_0=rockchip,rk3399-saradc
E: OF_COMPATIBLE_N=1
E: MAJOR=240
E: MINOR=0
E: SUBSYSTEM=iio

P: /devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-accel.12.auto/iio:device1
M: iio:device1
R: 1
U: iio
T: iio_device
D: c 240:1
N: iio:device1
L: 0
E: DEVPATH=/devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-accel.12.auto/iio:device1
E: DEVNAME=/dev/iio:device1
E: DEVTYPE=iio_device
E: MAJOR=240
E: MINOR=1
E: SUBSYSTEM=iio
E: USEC_INITIALIZED=15363895
E: ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
E: IIO_SENSOR_PROXY_TYPE=iio-poll-accel iio-buffer-accel
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

P: /devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-gyro.13.auto/iio:device2
M: iio:device2
R: 2
U: iio
T: iio_device
D: c 240:2
N: iio:device2
L: 0
E: DEVPATH=/devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-gyro.13.auto/iio:device2
E: DEVNAME=/dev/iio:device2
E: DEVTYPE=iio_device
E: MAJOR=240
E: MINOR=2
E: SUBSYSTEM=iio

P: /devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-accel.14.auto/iio:device3
M: iio:device3
R: 3
U: iio
T: iio_device
D: c 240:3
N: iio:device3
L: 0
E: DEVPATH=/devices/platform/ff200000.spi/spi_master/spi0/spi0.0/cros-ec-dev.0.auto/cros-ec-sensorhub.1.auto/cros-ec-accel.14.auto/iio:device3
E: DEVNAME=/dev/iio:device3
E: DEVTYPE=iio_device
E: MAJOR=240
E: MINOR=3
E: SUBSYSTEM=iio
E: USEC_INITIALIZED=15362274
E: ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
E: IIO_SENSOR_PROXY_TYPE=iio-poll-accel iio-buffer-accel
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

Also with the `monitor-sensor` test command you  posted, which normally prints `(orientation: bottom-up)`:

```
$ sudo systemctl restart iio-sensor-proxy
$ sudo su -s /bin/sh geoclue -c monitor-sensor
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: normal)
=== No ambient light sensor
=== No proximity sensor
=== No compass
^C
Session terminated, killing shell... ...killed.
```

**Comment by leezu** [comment]
@alpernebbi, nice! Do you want to open a PR replacing the device specific rules with the general chromebook rule?

https://github.com/systemd/systemd/blob/2fb11652381c199ad19bb469e530543366d99dd4/hwdb.d/60-sensor.hwdb#L406-L430

with

```
sensor:modalias:platform:cros-ec-accel:*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
```
