### ISSUE TITLE
Documentation - systemd.target(5) - DESCRIPTION

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#24231]
### Component

systemd

### Is your feature request related to a problem? Please describe

systemd 251.3

Documentation - systemd.target(5) - DESCRIPTION

The description of a target unit in the man page is not "wrong", per se, but it is quite opaque, awkwardly worded or without context or references in places.

There is also nothing addressing the target unit "ACTIVE" and "SUB" states, partially articulated under  `systemctl --state=help`,
```
Available target unit substates:
dead
active
```
as might be expressed with `systemctl list-units --type target`. It appears that there may be only two actual target unit states, either `active active` or `inactive dead`.

### Describe the solution you'd like

I suggest and encourage a more "illustrated" style, something more like this:

>DESCRIPTION
>
>A unit configuration file with a name ending in ".target" encodes information about a target unit of systemd. Target units are primarily used to set synchronization points relative to Before= and After= dependencies in other unit files.
>
>Target units will automatically gain Conflicts= and Before= dependencies against shutdown.target.
>
>Target unit files do not include a [Service] section but may include [Unit] and [Install] sections. A target unit with no [Unit] or [Install] dependencies may still be started and stopped just like any other unit type.  However, a target unit file with [Unit] and [Install] dependencies might also provide transitive dependency effects. Importantly, see systemd.special(7) for examples and descriptions of standard systemd target unit files providing these transitive dependencies.
>
>Specifying "Wants= some.unit" or "Requires= some.unit" in the target unit file itself will result in "some.unit" automatically gaining an After= ordering dependency upon that target unit.
>
>Note that the reverse is not true.  For example, defining "Wants= that.target" in "some.service" will *not* automatically add the "After= that.target" ordering dependency for "some.service".  Instead, "some.service" should use the primary synchronization function of target type units, by setting a specific "After= that.target" or "Before= that.target" ordering dependency in this .service unit file.
>
>The target unit file for a target unit which is only used to provide Before= and After= synchronization between other units cannot be be completely empty. The target unit file must contain at least a single character to avoid being "masked". It might nevertheless be preferable that the target unit file also provide a [Unit] section which includes informative Description= and Documentation= options.

### Describe alternatives you've considered

Forcing the reader to search for additional documentation not provided by systemd is inappropriate.

### The systemd version you checked that didn't have the feature you are asking for

systemd 251.3

**Comment by thx1111** [comment]
Thanks for providing an update to the documentation.  However, I will note that the wording "It is recommended to provide a [Unit] section" is a proper phrase in the English language in the same sense that "All your base are belong to us" is a proper phrase in the English language, which is to say, not so much.  Many non-native English speakers have difficulty with the proper use of infinitives and gerunds, and often use infinitives improperly and inappropriately.  Here, "to provide" is the infinitive, and "providing" is the gerund.  Proper English language wording would be "Providing a [Unit] section is recommended".

I also note that the update closing this documentation request fails to provide any description or articulation of the target unit "ACTIVE" and "SUB" states, partially articulated under `systemctl --state=help`.

Additionally I note that the English language term  "dead", as used in the systemd description of "state", has the connotation of "broken" with a presumption of "finality", as in "never returning", which is not an accurate description of the state being referenced.  A proper term in the English language would be closer to "suspended" or "sleeping" or "hibernating", which connotes as state something like "dead" with the difference being that a create that is "sleeping" or "hibernating" or in a state of "suspended animation" presumably will be able to "wake" and "live again".  Conventionally, the "dead" do not ever again "awaken".

**Comment by keszybz** [comment]
A comment on a closed issue is unlikely to have much effect. If you have ideas for how to improve the docs, please open a pull request.
