### ISSUE TITLE
Build fails with LDFLAGS=-fuse-ld=mold and binutils 2.39

### ISSUE THREAD

**Issue by jpalus** [systemd/systemd#24241]
### systemd version the issue has been seen with

251.4

### Used distribution

PLD 3.0

### Linux kernel version used

5.19.0

### CPU architectures issue was seen on

aarch64

### Component

other

### Expected behaviour you didn't see

`systemd` builds successfully.

### Unexpected behaviour you saw

Build fails with:
```
/usr/bin/ld.bfd: warning: src/boot/efi/systemd-bootaa64.elf has a LOAD segment with RWX permissions
collect2: error: ld returned 1 exit status
```

Fix for `binutils 2.39` was already provided in #23996 however the issue with the fix is that it assumes default `cc` linker is the same as linker used for efi stub. That may not be true though -- for the most parts of `systemd` I'm using `mold` linker, while efi stub forces `bfd` in `efi_ldflags`:
https://github.com/systemd/systemd/blob/7b45d6b6f64e9f5c006bdf31559a77294dbe00ad/src/boot/efi/meson.build#L255-L256

Test for `--no-warn-rwx-segments` does not take `efi_ldflags` into account though:
https://github.com/systemd/systemd/blob/7b45d6b6f64e9f5c006bdf31559a77294dbe00ad/src/boot/efi/meson.build#L269-L273

and tests `mold` instead. In the end `bfd` fails linking because `mold` does not support `--no-warn-rwx-segments`.

### Steps to reproduce the problem

Build `systemd` with `LDFLAGS="-fuse-ld=mold"` on a system that supports efi stub and has `binutils 2.39` installed

**Comment by medhefgo** [comment]
You should be able to work around this with `"-Defi-cflags=['-Wl,--no-warn-execstack','-Wl,--no-warn-rwx-segments']"`.
