### ISSUE TITLE
CHUWI Ubook support

### ISSUE THREAD

**Issue by root2185** [systemd/systemd#24248]
### systemd version the issue has been seen with

251.3-1

### Used distribution

Debian 11

### Linux kernel version used

5.18.0-3-amd64

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

Auto-rotation working correctly.

The output of `udevadm info --export-db` as requested on https://github.com/systemd/systemd/blob/main/hwdb.d/60-sensor.hwdb is here:

https://gist.github.com/Scorpion2185/a93a7c18a1b556405fd71ce4b8a8e6b9

### Unexpected behaviour you saw

Auto-rotation working bad:

![chuwi-ubook-rotation](https://user-images.githubusercontent.com/32654091/183451279-988cffcd-aec6-412f-8e22-606d4c6de55d.png)

### Steps to reproduce the problem

Try to use auto-rotation on this device (CHUWI Ubook).

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
cat /sys/`udevadm info -q path -n /dev/iio:device0`/../modalias:
output:

acpi:KIOX000A:KIOX000A:

--------------------

/sys/class/dmi/id/modalias
content:

dmi:bvnAmericanMegatrendsInc.:bvrZW-BI-116-SF133GR300-GA60D-014-C:bd04/29/2020:br5.13:svnCHUWIInnovationAndTechnology(ShenZhen)co.,Ltd:pnUBook:pvrTobefilledbyO.E.M.:rvnTobefilledbyO.E.M.:rnTobefilledbyO.E.M.:rvrTobefilledbyO.E.M.:cvnTobefilledbyO.E.M.:ct32:cvrTobefilledbyO.E.M.:skuTobefilledbyO.E.M.:
```

**Comment by Scorpion2185** [comment]
Yes but it seems that I will have to experiment the values to fix the auto-rotation.

I uploaded an image to show the problem, any suggestion?

**Comment by awee85** [comment]
@Scorpion2185 
I installed pop-os today want to use this tablet on the next weeks for camping vacation and run into the same problem. figured it out by:

sudo nano /etc/udev/hwdb.d/61-sensor-local.hwdb

sensor:modalias:*
 ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1

sudo systemd-hwdb update
sudo udevadm trigger

reboot
check with monitor-sensor -a while moving the tablet around directions

wfm

**Comment by Scorpion2185** [comment]
I think that it should be then:
```
# Chuwi Ubook
sensor:modalias:acpi:KIOX000A*:dmi:bvnAmericanMegatrendsInc.:bvrZW-BI-116-SF133GR300-GA60D-014-C:bd04/29/2020:svnCHUWIInnovationAndTechnology*:pnUBook:*
 ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1
```
Thanks @awee85, I will check it.

**Comment by awee85** [comment]
Sorry my ubook died (battery bloated while charging on holidays in our camper and broke the display) really bad quality :(. Glad nothing more happened. Be careful with this device. Cant provide you with me sensor:modalias string. I suggest you should try and error every  KIOX000A* ACCEL_Mount_MATRIX options including  ACCEL_LOCATION=base from https://github.com/systemd/systemd/blob/main/hwdb.d/60-sensor.hwdb. 

cheers

**Comment by hfavisado** [comment]
I made the above PR which should fix it for the N4100 version.
Here's my modalias string:
`dmi:bvnAmericanMegatrendsInc.:bvrZW-BI-121-SF133GR310-GA60A-043-A:bd12/04/2020:br5.13:svnCHUWIInnovationAndTechnology(ShenZhen)co.,Ltd:pnUBookX:pvrTobefilledbyO.E.M.:rvnTobefilledbyO.E.M.:rnTobefilledbyO.E.M.:rvrTobefilledbyO.E.M.:cvnTobefilledbyO.E.M.:ct31:cvrTobefilledbyO.E.M.:skuTobefilledbyO.E.M.:`

I hope my tablet's battery will never turn into a spicy pillow!!

**Comment by keszybz** [comment]
#24248 was merged, let's close this. If the new hwdb entry doesn't cover older models, please open a new issue.
