### ISSUE TITLE
The ControlGroupNFTSet= unit file setting should be renamed before the 252 release

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#24255]
I am pretty sure we should rename the recently added ControlGroupNFTSet= unit file setting before the 252 release. The "ControlGroup" reference should be removed from the name. Unless a field is directly exposing ac group property (e.g. ControlGroupPath= or ControlGroupId=) in most ways control groups are an implementation detail for us. One that is worth mentioning in the man page, but I am sure we should not include in settings names, because it's irrelevant for the purpose of this setting.

Moreover, it would then be more symmetric with the NFTSet= setting in .network settings, which is also just called NFTSet= and not AddressNFTSet= or so.

**Comment by yuwata** [comment]
I thought the feature was dropped. Are there anything I forgot to remove?

**Comment by poettering** [comment]
Also see → https://github.com/systemd/systemd/pull/22587#pullrequestreview-1066376754

**Comment by poettering** [comment]
> I thought the feature was dropped. Are there anything I forgot to remove?

Oh, it was? It was reverted? I wasn't aware. Sorry. I am going through the git history, and didn't make it to the revert yet, if there was one. Sorry for the noise if so.

**Comment by poettering** [comment]
ok, i made it to the revert now. Let's close this issue hence, as there is no point!
