### ISSUE TITLE
Inconsistent configuration key name

### ISSUE THREAD

**Issue by wahjava** [systemd/systemd#24268]
### systemd version the issue has been seen with

245.4-4ubuntu3.17

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.0-122-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

`AllowPortToBeRoot` configuration in `Bridge` section of `systemd.network(5)` implies as per its manual page (`systemd.network(5)`):

>        AllowPortToBeRoot=
>           Takes a boolean. Configures whether a given port is allowed to become a root port. Only used when STP is enabled on the bridge. When unset, the
>           kernel's default will be used.

It essentially controls the `root_block` option of the interface participating in the bridge, and its manual page (`bridge(8)`) reads:

>        root_block on or root_block off
>           Controls whether a given port is allowed to become root port or not. Only used when STP is enabled on the bridge. By default the flag is off.

If one sets `root_block` to `on`, the port will be prevented from becoming `root`. Yet the only way to set it to `on` using `systemd-networkd` configuration is to set `AllowPortToBeRoot` to `true`, which seems like opposite of expected behaviour, if I understand it correctly, i.e. when `AllowPortToBeRoot` is `true` it should result in `root_block` to `false` therefore enabling the port to become the `root`.

Please feel free to correct me, if I misunderstood.

Thanks!

**Comment by yuwata** [comment]
Ouch! Thank you for the report. The issue is caused by 7f9915f0de67f3a10a4b22810d119da65af8c84a.

**Comment by yuwata** [comment]
UseBPDU is also flipped by the commit.
