### ISSUE TITLE
systemctl error messages should print '-M machine' (if this option was passed)

### ISSUE THREAD

**Issue by robert-scheck** [systemd/systemd#2431]
systemctl error messages should print `-M machine` (if this option was passed), because:

```
$ systemctl -M machine restart systemd-networkd.service
$ systemctl -M machine restart systemd-networkd.service
$ systemctl -M machine restart systemd-networkd.service
$ systemctl -M machine restart systemd-networkd.service
$ systemctl -M machine restart systemd-networkd.service
$ systemctl -M machine restart systemd-networkd.service
Job for systemd-networkd.service failed because start of the service was attempted too often. See "systemctl status systemd-networkd.service" and "journalctl -xe" for details.
To force a start use "systemctl reset-failed systemd-networkd.service" followed by "systemctl start systemd-networkd.service" again.
$ 
```

In this case it's quite obvious that
- `systemctl -M machine status systemd-networkd.service`,
- `journalctl -M machine -xe`,
- `systemctl -M machine reset-failed systemd-networkd.service` and
- `systemctl -M machine start systemd-networkd.service`

are needed, however this gets less obvious if the initial command above is run by a script and the output e.g. appears in a cron mail or whatever. Note that above repeated restarting was just an example, this also could be another failure.

Thus it would be very helpful if `-M machine` appears in the error messages as well (if this option was passed before). And if I am not completely mistaken, it is a difference if you run that command to the host system or to a container.

**Comment by keszybz** [comment]
Hm, I hacked up a quick patch for this. Before I create the PR though, a quick question:

```
$ rpm -q systemd
systemd-222-13.fc23.x86_64

$ sudo systemctl -M fedora-rawhide status systemd-networkd.service
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-02-15 10:17:22 EST; 1h 14min ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 29 (kblockd)
   Status: "Processing requests..."
   CGroup: /machine.slice/machine-fedora\x2drawhide.scope/system.slice/systemd-networkd.service
           └─3773 /usr/lib/systemd/systemd-networkd
           ‣ 29 [kblockd]
```

The status is compleetely borked, because the namespaced PID is not translated. Did I screw something up or is it supposed to be like this?

**Comment by poettering** [comment]
@keszybz yeah, the logic is borked there. We really should fix that, by adding a unit bus call that allows extracting the PID tree of a service via the bus. This is also fully borked for -H (but there we turn it off entirely at least)...

Something like a `GetProcesses()` call on the Unit that basically returns a dump of the processes in a unit, plus their names, and enough parental information that this may be used to build a tree of it.
