### ISSUE TITLE
Systemd：timedatectl set-ntp yes cannot recovery the system time back to real time when system time is set to 2037

### ISSUE THREAD

**Issue by utt54321** [systemd/systemd#24349]
### systemd version the issue has been seen with

247.3-7

### Used distribution

Debian11

### Linux kernel version used

5.10.0-14-amd64

### Expected behaviour you didn't see

execute "timedatectl set-ntp no; timedatectl set-time '20370909'; timedatectl set-ntp yes;" 
seeing the system time autoset back to today(real time)

### Unexpected behaviour you saw

execute "timedatectl set-ntp no; timedatectl set-time '20370909'; timedatectl set-ntp yes;" 
seeing the system time keeps at 20370909

### Steps to reproduce the problem

execute "timedatectl set-ntp no; timedatectl set-time '20370909'; timedatectl set-ntp yes;" and see wheather the system still keeps 2037

**Comment by yuwata** [comment]
I guess systemd-resolved is running with DNSSEC enabled? If so, PR #18563 already fixed this issue. Or, disabling DNSSEC may fix the issue.

BTW, this is the upstream issue tracker, and v247 is slightly old here. Please try to reproduce the issue with a recent release (v250 or v251) or the current git HEAD. Closing.
