### ISSUE TITLE
make configure in /etc/systemd/journald.conf,and it doesn't work

### ISSUE THREAD

**Issue by xdsb** [systemd/systemd#24347]
systemd version the issue has been seen with

systemd 244(244.5+)

Used distribution
yocto

Linux kernel version used (uname -a)

5.4

CPU architecture issue was seen on

aarch64

Expected behaviour you didn't see

journald log would recorded on disk, and with **MaxRetentionSec=1m** configed,the disk wouldn't be full,

Unexpected behaviour you saw
Config the log to be recorded on disk, and mount bind the /var/log/journal to /data/log/journal (disk).
Config /etc/systemd/journald.conf:
_[Journal]
**Storage=persistent**
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
#RateLimitBurst=10000
**SystemMaxUse=400M**
#SystemKeepFree=
**SystemMaxFileSize=20M**
**SystemMaxFiles=20**
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
**MaxRetentionSec=1m**
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
#LineMax=48K
#ReadKMsg=yes_

and it dosen't work for journald logs.
With  tests going ,the disk would be full and the size of log file is 33M,more than 20M.SystemMaxUse is growing more than 400M

Steps to reproduce the problem
see above 

Additional program output to the terminal or log subsystem illustrating the issue

**Comment by yuwata** [comment]
Sorry, v244 is too old here. Please try to reproduce the issue with newer release (v250 or v251) or the current git HEAD.
