### ISSUE TITLE
systemd not creating v4 routes with a v6 next hop

### ISSUE THREAD

**Issue by gpl** [systemd/systemd#24345]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-41-generic

### CPU architectures issue was seen on

x86_64

### Component

networkctl, systemd-networkd

### Expected behaviour you didn't see

Creating a v4 route entry with a v6 next-hop doesn't appear to be supported / fails silently.

Expected: 

> `ip r add 0.0.0.0/0 via inet6 2001::1 `
> ip r
default via inet6 2001::1 dev enp1s0
...

### Unexpected behaviour you saw

No routes were created.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[Route]
Destination = "0.0.0.0/0"
GatewayOnLink = "no"
Gateway = "2001::1"
```

**Comment by yuwata** [comment]
Could you provide full .network file?

**Comment by gpl** [comment]
```[Match]
Name=enp1s0

[Link]
RequiredForOnline=no

[Network]
Address=1.0.0.2/24
Address=2001::2/32
IPv6AcceptRA=no
ConfigureWithoutCarrier=yes

[Route]
Destination = "0.0.0.0/0"
GatewayOnLink = "no"
Gateway = "2001::1"```

**Comment by yuwata** [comment]
Thanks. Destination=, GatewayOnLink=, and Gateway= must be unquoted. I guess this is just a misconfiguration.

**Comment by gpl** [comment]
The behavior does not change when the quotes are removed -- does systemd support creating v6 next hops for v4 prefixes?

**Comment by yuwata** [comment]
yes. And I confirmed that the almost same config works fine.

Please provide debugging logs of networkd.

**Comment by yuwata** [comment]
Ah, you use v249. Maybe fixed by 3333350a0e1917395d3654731ca985ea668bca9b (#20498).

**Comment by robert-scheck** [comment]
I am experiencing the same (?) issue, however not with v6 nexthop, but with IPv4 `GatewayOnlink`, being supplied by e.g. Hetzner as default network configuration. In the end, `ip -4 r` shows simply nothing; configuration:

```
[Match]
Name=ens3

[Link]
RequiredForOnline=no

[Network]
LinkLocalAddressing=ipv6
Address=192.0.2.155/32
Address=2001:db8:1234:5678::1/64
Gateway=172.31.1.1
Gateway=fe80::1
DNS=1.1.1.1
DNS=1.0.0.1
DNS=2606:4700:4700::1111
DNS=2606:4700:4700::1001

[Route]
Destination=0.0.0.0/0
Gateway=172.31.1.1
GatewayOnlink=true
```

The affected system uses systemd 249.11-0ubuntu3.4 from Ubuntu 22.04 LTS.

**Comment by yuwata** [comment]
@robert-scheck In this case, the duplicated gateway is declared in the [Network] section. Please try to drop it.

**Comment by cooperlees** [comment]
FWIW, can confirm this works with `systemd/lunar,now 252.5-2ubuntu3`

Config:
```
# Test IPv4 via IPv6 route setting ...
[Route]
Destination=255.1.1.1/32
Gateway=fe80::2
Metric=1499
```

```
cooper@home2:~$ ip -4 route | grep ^255
255.1.1.1 via inet6 fe80::2 dev vlan69 proto static metric 1499
```
