### ISSUE TITLE
ODYS WINPAD V10 include ACCEL_MOUNT_MATRIX

### ISSUE THREAD

**Issue by zazou99vlc** [systemd/systemd#24346]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 36

### Linux kernel version used

5.18.17-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

bootctl, systemd

### Expected behaviour you didn't see

ACCEL_MOUNT_MATRIX for SMO8500 in WINPAD V10
Manufacturer: AXDIA International GmbH
DEVPATH=/devices/platform/80860F41:02/i2c-2/i2c-SMO8500:00/iio:device0
Product Name: WINPAD V10

Correct mount matrix

ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1

### Unexpected behaviour you saw

I'm not a developer or anything like that but if you want to include this in

https://github.com/systemd/systemd/blob/main/hwdb.d/60-sensor.hwdb

I think it will help others with the same hardware. Do not ask me for more cybernetic bureaucracy

**Comment by yuwata** [comment]
Please update the hwdb file and submit as a PR.

**Comment by poettering** [comment]
Let's close this here. We are happy to merge a record for this, but please file the patch as a PR, so that we can CI test it, attribute it to you and so on.

**Comment by zazou99vlc** [comment]
thanks but I don't know what it means "file the patch as a PR, so that we
can C" I'm just an amateur who reads and thinks. kisses
