### ISSUE TITLE
sysusers: consider making shell value for root user configurable (at build time)

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#24369]
### Component

systemd-sysusers

### Is your feature request related to a problem? Please describe

Currently the default shell for the `root` user is hardcoded to `/bin/sh` in several places:

https://github.com/systemd/systemd/blob/d5548eb618d426a3952746eb3a0e7d95d186ea7e/src/shared/user-record.c#L1752-L1765

https://github.com/systemd/systemd/blob/d5548eb618d426a3952746eb3a0e7d95d186ea7e/src/sysusers/sysusers.c#L393-L395

This is a conservative value which I think works as a bottom line for pretty much everything.

However, in many real-world cases, the `root` user actually uses a more modern shell.
For example, on Fedora `/bin/bash` is used by default for the `root` user: https://pagure.io/setup/blob/master/f/passwd#_1

In order to reduce the gap between distros defaults and system-sysusers entries, I think it would be useful to let distribution configure the default shell for the `root` user at build-time.

If there are concerns about the sprawl of too-many built-time parameters, @keszybz pointed out to me that there is already a `default-user-shell` option (defaulting to `/bin/bash`) that possibly could be re-used for this.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by lucab** [comment]
Somewhat related to this there is https://github.com/systemd/systemd/issues/24215, to avoid some noise if an explicit value is equal to the missing/default one from systemd.

**Comment by poettering** [comment]
In the case of "sysusers", the root shell is already configurable in unit files, in current git:

Use

```
SetCredential=passwd.shell.root=/bin/zsh
```
or similar, via a drop-in.
