### ISSUE TITLE
Special targets not documented  in systemd.special(7)

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2438]
slices.target is undocumented, even though it has a `Documentation=man:systemd.special(7)` annotation.

`mail-transport-agent.target` should similarly be documented in systemd.special, other SysV facility aliases are documented there.

**Comment by mbiebl** [comment]
mail-transport-agent.target is from a Debian downstream patch. This is not relevant upstream I'd say.

**Comment by fsateler** [comment]
@mbiebl Right, thanks. I should have looked first. So that leaves only `slices.target`

**Comment by poettering** [comment]
We don't do the mta thing since v198.

**Comment by mbiebl** [comment]
Right, as already said, it's a downstream patch in Debian which adds it back. We still have quite a few SysV init scripts which reference mail-transport-agent in their LSB header

**Comment by poettering** [comment]
There's a fix for this waiting in #2445.
