### ISSUE TITLE
Is it right that creating a log directory named machine-id which was changed after every boot.

### ISSUE THREAD

**Issue by xdsb** [systemd/systemd#24388]
### systemd version the issue has been seen with

244.5

### Used distribution

yocto

### Linux kernel version used

5.4

### CPU architectures issue was seen on

aarch64

### Component

journalctl

### Expected behaviour you didn't see

There is only one subdirectory which contains journal log files  the directory /var/log/journal 

root@imx6:/var/log/journal# ls -al
drwxr-sr-x   10 root     systemd-      4096 Aug 18 08:02 .
drwxr-xr-x    3 root     root          4096 Aug 18 08:02 ..
drwxr-sr-x    2 root     systemd-      4096 Aug 18 08:02 256b5c4f6a7f49ec9c74092bc9c116f4
the name of the directory is 256b5c4f6a7f49ec9c74092bc9c116f4 which is the name machine-id.

### Unexpected behaviour you saw

root@imx6:/data/log/journal# du -h
33M     ./8e55bcc984bb4a93b184e39bd14b00f3
33M     ./bda3bada31af463681002d927500c2ee
33M     ./f8d4cd16ea794e53aafbaa18e8769619
33M     ./a073312b1e614a24bcf4e086c6b89f38
33M     ./be20420436fd43df88f86cdc43838fc5
33M     ./f0fa86e51e534b3da588b207ab310b25
33M     ./babe1a77812c4157995776192ed5ff73
33M     ./ab14ece84bce4eb88690442a78acecbf
33M     ./2827544a5e5d49e88786319ed9b2dafa
33M     ./6aaaa16c9a2f4cfa8ba313d66139f832
33M     ./95e0719dd91a4dfc9c52964b39abf0b9
33M     ./e5cb29b8d4314983b7f36b46806d314b
33M     ./1a05521ed1044e2a8f948eeb65b90aef
33M     ./99782592807e4119bfd7185072b97689
33M     ./d4dba031fe194e5c8ba9e4a674ba53bb
33M     ./ddcd0408bc14492e87bc7e4c7392517c
33M     ./388018b8cf5e4b76a432dcdce542f08b
33M     ./84c154516e7f40ad82920523f18c4b05
33M     ./969c0f0cefeb437493a1d023aa64ba86
33M     ./b21f5df251f7476282a4138eaabf9123
41M     ./25ca84e501e5407c9edaea499a6b12c9
33M     ./3226cda2e2814cb691f6a9537c7c9a23
33M     ./1b05579c6f654e34a4290dac5a5afd44
33M     ./30d4033b6b6348bcbc44fd7e5ca8ff6e
33M     ./54786beb30ff4d7c8098c7964006346d
33M     ./9dc5c4d99d4d4a6da4114230b600e828
841M 
the name of the directory which is the name machine-id.
The directory which named by machine-id was produced after every boot.

### Steps to reproduce the problem

see above.

**Comment by bluca** [comment]
The machine-id needs to be stable for the same installation. If it's lost on reboot then the setup is not correct, for more details see https://www.freedesktop.org/software/systemd/man/machine-id.html
