### ISSUE TITLE
hostname: Chassis type through org.freedesktop.hostname1 but returned an emtpy string.

### ISSUE THREAD

**Issue by smallorange** [systemd/systemd#24384]
### systemd version the issue has been seen with

251.4-53

### Used distribution

Rawhide

### Linux kernel version used

6.0.0-0.rc1.20220819git4c2d0b039c5c.16.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-hostnamed

### Expected behaviour you didn't see

If we requested the chassis type through dbus org.freedesktop.hostname1 in a VM, we expected the chassis type should be "vm" rather than an empty string ''.

### Unexpected behaviour you saw

If we request the chassis type in qemu and virtual box, it always returns an empty string.
![in_vm](https://user-images.githubusercontent.com/1192641/185834802-542e59ba-ca95-47bb-8c15-c0dde3a104ab.png)
![Screen Shot 2022-08-22 at 11 40 14 AM](https://user-images.githubusercontent.com/1192641/185834834-ded86842-896b-4bc2-96af-cf9ebf3d84ea.png)

### Steps to reproduce the problem

1. Install Fedora in a VM (QEMU or Virtual box)
2. Request chassis type through dbus interface "org.freedesktop.DBus.Properties"
3. the returned value should be an empty string.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #24385.

**Comment by smallorange** [comment]
Thank you :)
