### ISSUE TITLE
group memberships not shown for drop in user records

### ISSUE THREAD

**Issue by Gibheer** [systemd/systemd#24381]
To add some login users to my images, I tried the userdb drop in users.
They show up in userdb, but the group memberships don't come up as expected.

My system is Archlinux with systemd 251.4-1-arch

```
USERDB_DIR="/etc/userdb"
mkdir $USERDB_DIR

cat <<EOF > ${USERDB_DIR}/test.user
{
  "userName": "test",
  "uid": 6000,
  "locked": false,
  "memberOf": [
    "test1"
  ]
}
EOF
cat <<EOF > ${USERDB_DIR}/test1.group
{
  "groupName": "test1",
  "gid": 6001
}
EOF
cat <<EOF > ${USERDB_DIR}/test2.group
{
  "groupName": "test2",
  "gid": 6002,
  "members": ["test"]
}
EOF
ln -s ${USERDB_DIR}/test1.group ${USERDB_DIR}/6000.group
ln -s ${USERDB_DIR}/test2.group ${USERDB_DIR}/6001.group
ln -s ${USERDB_DIR}/test.user ${USERDB_DIR}/6000.user

/usr/bin/userdbctl groups-of-user test
/usr/bin/userdbctl users-in-group test1
/usr/bin/userdbctl users-in-group test2
```

This should return
```
USER    GROUP
test    test1
test    test2

2 memberships listed.
USER         GROUP 
test          test1

1 memberships listed.
USER         GROUP 
test          test2

1 memberships listed.
```

but instead I get that no memberships exist

```
No memberships.
No memberships.
No memberships.
```

The services of userdb are up and running

```
$ userdbctl services
SERVICE                      LISTENING
io.systemd.DropIn            yes      
io.systemd.DynamicUser       yes      
io.systemd.Machine           yes      
io.systemd.Multiplexer       yes      
io.systemd.NameServiceSwitch yes      

5 services listed.
```

The records are available according to userdbctl

```userdbctl user test
   User name: test
 Disposition: regular
    Login OK: yes
 Password OK: no (none set)
         UID: 6000
         GID: 6000
   Directory: /home/test
     Storage: classic
       Shell: /bin/bash
      Locked: no
   Passwords: none
     Service: io.systemd.NameServiceSwitch
```

But somehow the relationship isn't loaded as it would have been when using homectl. I have investigated the code but couldn't find the place where the group memberships are left out or dropped.

**Comment by lutchann** [comment]
It doesn't look like additional group membership is properly loaded from drop-ins, neither with the `member` field of the group drop-in, nor with the `memberOf` field of the user drop-in. strace shows that `.user` files aren't even consulted when running `getent group`.

However, as a workaround, membership drop-ins do the trick: create a file named `<user>:<group>.membership` alongside your existing drop-ins. (The contents of the file don't seem to matter, but the file can't be zero-length as the parser will treat it as a mask file.) In your example above, you could use something like:

```
echo > ${USERDB_DIR}/test:test1.membership
echo > ${USERDB_DIR}/test:test2.membership
```

At least, this is working for me on Ubuntu 22.04 with systemd 249, which does not have userdbd.

**Comment by poettering** [comment]
how does your /etc/nsswitch.conf actually look like?

i.e. it must say:

```
group: compat [SUCCESS=merge] systemd
```

or something like that. i.e. the `[SUCCESS=merge]` thing is key.

**Comment by Gibheer** [comment]
Sorry for the late response. My nsswitch.conf contains

```
group: files [SUCCESS=merge] systemd
```

Thank you lutchan, I will try that.

**Comment by pothos** [comment]
Thanks for the workaround, indeed it helps :) But now I wonder, what are valid contents for a `.membership` file - is the content ignored? After a quick glimpse on the source code I think the filename consists of a user and a group name but now sure if the contents are even read somewhere.

**Comment by pothos** [comment]
@AdrianVovk fyi

**Comment by chewi** [comment]
I've looked into this and found that it's basically not implemented! Presumably an oversight. :smile: I started trying to fix this one way, and got the group to appear in `userdbctl user`, but I realised this wasn't going to work in other cases. My second attempt would be a more complete fix, but it's currently not working. I think I'm close, but it's not the easiest thing to debug!

**Comment by Gibheer** [comment]
@chewi thank you so much for looking into this issue :)

**Comment by chewi** [comment]
I got it to work!! It just needs some deduping. Hopefully that's not difficult.

**Comment by chewi** [comment]
All looking good now. Time to write some tests.

**Comment by chewi** [comment]
It turns out I'm still getting some duplication, although that's probably a minor issue. More importantly, my tests are failing because I'm bizarrely getting different results from userdbctl when requesting the output in JSON format. I don't think I should create a pull request yet, but [here is the branch](https://github.com/chewi/systemd/tree/dropin-membership) if you're interested.

**Comment by chewi** [comment]
It's ready. It still duplicates in places, but hopefully that's not a real issue. See the PR in #32871.

**Comment by poettering** [comment]
> Thanks for the workaround, indeed it helps :) But now I wonder, what are valid contents for a `.membership` file - is the content ignored? After a quick glimpse on the source code I think the filename consists of a user and a group name but now sure if the contents are even read somewhere.

so yeah, the contents is ignored indeed. 

this was the reason i never documented this part, i wasn't entirely sure what to write into the docs... and then i eventually totally forgot about this.

I think we should require that these files contain json objects matching the return parameter of what the io.systemd.UserDatabase.GetMemberships() call also returns.

**Comment by poettering** [comment]
BTW, since d1b04f47e32bd1012ae2e3e6ac9159702463bf15 the .membership files are documented. I think that resolves the issue.
