### ISSUE TITLE
Networkctl doesn't show SSID anymore

### ISSUE THREAD

**Issue by bermeitinger-b** [systemd/systemd#24411]
### systemd version the issue has been seen with

251.4-1-manjaro

### Used distribution

Manjaro

### Linux kernel version used

5.19.3-2-MANJARO

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

I want the SSID to be included in the status of `networkctl status` like it was in an older version. (I'm sorry, I can't provide the exact versions, but it might be introduced in version `251.4-1`.

### Unexpected behaviour you saw

The command `networkctl --json=pretty wlp0s20f3` doesn't list the SSID anymore or rather returns `null`:

`networkctl status --json=pretty wlp0s20f3 | jq .SSID` => `null`

### Steps to reproduce the problem

Use systemd-network to configure the wifi interface:

```
# /etc/systemd/network/50-wifi.network
[Match]
Name=wl*

[Network]
DHCP=yes
MulticastDNS=yes
IPv6PrivacyExtensions=yes

[DHCP]
RouteMetric=20

[DHCPv4]
UseDomains=true

[IPv6AcceptRA]
UseDomains=yes
```

And setup wpa_supplicant:
```
# /etc/wpa_supplicant/wpa_supplicant-wlp0s20f3.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1
country=CH

network={} ... //
```

Both services are running, the network is working, but the command 

`networkctl status --json=pretty wlp0s20f3 | jq .SSID` doesn't return the SSID anymore.

**Comment by GladOSkar** [comment]
Probably a linux `5.19` issue. Have seen it on other projects as well. Even `iw` does not seem to be able to report SSID anymore.

**Comment by keszybz** [comment]
I checked my local machine with systemd git tip, and SSID is shown. And I don't recall any changes in this area in systed… So it's reasonable to assume that this is not our issue. Please reopen if it turns out that we have something to fix.
