### ISSUE TITLE
networkctl does not show when configuration is loaded from Drop In

### ISSUE THREAD

**Issue by aijayadams** [systemd/systemd#24428]
### Component

networkctl

### Is your feature request related to a problem? Please describe

When .network|.link configuration is extended with Drop-Ins, the configuration is honored and used as with other components of systemd. However `networkctl` shows the Network File and Link File without showing the Drop-In files when viewing status. 
```
# networkctl status 2
● 2: enp0s6
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/00-enp0s6.network
                          Type: ether
                         State: routable (configured)
[...]

# cat /etc/systemd/network/00-enp0s6.network.d/routes.conf
[Route]
Destination=1.2.3.4
Gateway=192.168.64.20

# ip rou | grep static
1.2.3.4 via 192.168.64.20 dev enp0s6 proto static onlink

```

### Describe the solution you'd like

If `networkctl` reviled when Drop-In configuration was being used in a manner similar to what is done by `systemctl`, well that'd be just amazing!

```
# systemctl status sshd
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
    Drop-In: /usr/lib/systemd/system/ssh.service.d
             └─always.conf
...
``` 

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by cooperlees** [comment]
It would also be nice if some indication of the drop in configuration that is in use was also in `/run/systemd/netif/links/*` files too, but I think that's a requirement due to how `networkctl` works today.
