### ISSUE TITLE
Generators should run sandboxed

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#24430]
### Component

systemd

### Is your feature request related to a problem? Please describe

Generators are spawned by systemd and run as `root` with the same privileges as manager. Their only task it to generate unit files based on other "foreign" configuration. Hence they should just read input and generate output unit files. We can't really predict where input is going to be, but we know for sure they only need to read it. As for output, the locations where generators are supposed to write are well known. It is either `/tmp` or `/run/systemd/generator{,.early,.late}` directories. 

### Describe the solution you'd like

So far these constraints where only documented but not enforced. It would make a lot of sense to do that and run generators in some form of sandboxed environment.

**Comment by poettering** [comment]
sounds like a great candidate to play around with landlock.
