### ISSUE TITLE
no stdout/stderr for process started as sudo

### ISSUE THREAD

**Issue by olssonsimon** [systemd/systemd#24435]
### systemd version the issue has been seen with

245

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.10.65-rt53

### CPU architectures issue was seen on

aarch64

### Component

journalctl

### Expected behaviour you didn't see

Expected output to be visible in the journal logs.

### Unexpected behaviour you saw

stdout/stderr is lost

### Steps to reproduce the problem

Run something as root and watch the output disappear.

**Comment by poettering** [comment]
This is not a useful bug report. Moreover it really sounds like what you are looking for is support. For that, please contact the mailing list, not this bug tracker.

Also, 245 is waaay too old, this is a bug tracker for upstream issues only, in the two most recent upstream releases of systemd, i.e. 250 and 251.

**Comment by olssonsimon** [comment]
:disappointed: :cry:
