### ISSUE TITLE
Incorrect command line argument returned as success condition.

### ISSUE THREAD

**Issue by mhoye** [systemd/systemd#24433]
### Component

systemd-sysctl

### Is your feature request related to a problem? Please describe

It's a small thing, but: 

```
mhoye@patchwork:/etc$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6 = 1
sysctl: "net.ipv6.conf.all.disable_ipv6" must be of the form name=value
sysctl: malformed setting "="
sysctl: "1" must be of the form name=value
mhoye@patchwork:/etc$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6 = 1
mhoye@patchwork:/etc$ 
```

... if sysctl is going to report success by echoing its arguments, they should probably be printed verbatim.

### Describe the solution you'd like

`sysctl -w net.ipv6.conf.all.disable_ipv6=1`

return

`net.ipv6.conf.all.disable_ipv6=1`

rather than

`net.ipv6.conf.all.disable_ipv6 = 1`

**Comment by bluca** [comment]
The `sysctl` utility is not developed here, it comes from the procps project: https://gitlab.com/procps-ng/procps
