### ISSUE TITLE
systemd breaks services due to PIDFile directive in unit file

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#2443]
Dear People,

Today I've upgraded NGINX (upstream official packages) that provide a unit file with the following:

```
[Unit]
Description=nginx - high performance web server
Documentation=http://nginx.org/en/docs/
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf
ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

The nginx.conf file has a directive:

```
pid /var/run/nginx.conf;
```

From my understanding this seems nice because the pidfile is created in runtime variable placeholder (/var/run) according to FHS, http://www.pathname.com/fhs/2.2/fhs-5.13.html.

Now what happens is that when I start nginx, it starts but doesnt drop you to shell (nginx is working fine). At some point systemd nukes the process and drops back to the shell. Editing the unit file and changing /run/nginx.pid to /var/run/nginx.pid makes the software work good.

At first I believed that it was a NGINX specific issue and opened a ticket on: https://trac.nginx.org/nginx/ticket/884#ticket

After talking with some friends we've identified that Box Backup also has exactly the same problem... I would believe that this would be a packaging issue, but then again, is it really a packaging issue?

Can you guys provide any pointer/docs that explain what the PIDFile exactly does and how it impacts applications?

My common sense says you guys should take a look at this.

Kindest Regards,
NMM

**Comment by poettering** [comment]
You didn't read the contribution guidelines linked prominently from the issue form before posting this issue. You didn't specify which distro this is and which systemd version. Please read these guidelines _before_ filing an issue thanks.

https://github.com/systemd/systemd/blob/master/CONTRIBUTING.md

/var/run should be a symlink to /run on all systems. Is that the case for you? If so, then the two paths are entirely equivalent, and there shouldn't be a problem using either.

/var/run from a systemd perspective is an obsolete name for /run, and I wouldn't reference it in a systemd context at all.

**Comment by poettering** [comment]
Regarding, what PIDFile= does, have you considered checking the man pages?

http://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=

Next time, please first check the docs, and then please follow the guidelines for posting an issue, thanks.

**Comment by johannbg** [comment]
This is not a systemd bug but a pretty obvious misconfiguration in nginx.conf. 
your nginx.conf should contain
pid /run/nginx.pid; 
which matches the PIDFile= entry in the type service unit
not 
pid /var/run/nginx.conf; 

Systemd distributions shipping nginx should be providing you with a working nginx configuration which matches that type service unit file if not you should file a bug against that distribution.

**Comment by poettering** [comment]
@johannbg has a point, the pid file configured in ngninx.conf should have the suffix .pid, not .conf.

That said, /var/run or /run should be fully equivalent, unless your distro doesn't install the /var/run symlink properly...

Under the assumption this is simply confusion regarding the PID file suffix or the symlink, I'll close this now.

**Comment by ghost** [comment]
Hi,

I'll bring this issue to the manufacturer of the system, Red Hat (RHEL7) where /run isn't a symlink to /var/run and where the shipped version of nginx doesn't provide the required features by our application (nginx >= 1.7.3).

Many apologies for missing the proper form for a bug report.

Keep up the good work with systemd

NMM

**Comment by poettering** [comment]
/var/run should be a symlink that points to /run, not the other way round.

And on RHEL7 that's how the system is set up. If you don't see that, then something went really wrong during installation.
