### ISSUE TITLE
Allow to set TCP congestion control algorithm per route

### ISSUE THREAD

**Issue by kiwixz** [systemd/systemd#24432]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

We already have the similar InitialCongestionWindow, InitialAdvertisedReceiveWindow, QuickAck, FastOpenNoCookie, etc but we're missing an equivalent for the `congctl` (see [ubuntu man](https://manpages.ubuntu.com/manpages/jammy/en/man8/ip-route.8.html) option) setting the TCP congestion control algorithm.

### Describe the solution you'd like

I'd like a `TCPCongestionControlAlgorithm` (name is up to you!) so I could add this line to one of my route:
```
TCPCongestionControlAlgorithm=bbr
```

### The systemd version you checked that didn't have the feature you are asking for

249

**Comment by yuwata** [comment]
Waiting in #24456.
