### ISSUE TITLE
'Hardware vendor' and 'Hardware model' produce useless identity information on non OEM system (Asus)

### ISSUE THREAD

**Issue by dantob** [systemd/systemd#24446]
### systemd version the issue has been seen with

251

### Used distribution

Arch Linux

### Linux kernel version used

5.15.62

### Expected behaviour you didn't see

Referred from [https://gitlab.gnome.org/vstanek/gnome-info-collect/-/issues/23](https://gitlab.gnome.org/vstanek/gnome-info-collect/-/issues/23) @felipeborges 

My Asus motherboard doesn't have any useful identity info set under System Information in SMBIOS
```
System Information
	Manufacturer: System manufacturer
	Product Name: System Product Name
```

However, it does seem to have the right info set under Base Board Information
```
Base Board Information
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: Z170 PRO GAMING
```

Looking at a few other boards over at [https://github.com/linuxhw/DMI](https://github.com/linuxhw/DMI), it appears to be a common occurrence (at least for Asus boards). Maybe the base board info should be used as a fallback if system information reports `System manufacturer`, `System Product Name` or `To be filled by O.E.M.`

[dmidecode](https://gist.github.com/dantob/9b476a0b53b42b2dfbef1d4cbe20e873)

**Comment by yuwata** [comment]
Could you show the result of `cat /sys/class/dmi/id/modalias`?

**Comment by dantob** [comment]
cat /sys/class/dmi/id/modalias
````
dmi:bvnAmericanMegatrendsInc.:bvr3805:bd05/16/2018:br5.12:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnZ170PROGAMING:rvrRevX.0x:cvnDefaultstring:ct3:cvrDefaultstring:skuSKU:
````

**Comment by dantob** [comment]
Confirmed working with 251.5, thanks for sorting this out quickly 👍
