### ISSUE TITLE
Support `libbpf` v1.0.0

### ISSUE THREAD

**Issue by veehaitch** [systemd/systemd#24464]
### Component

systemd

### Is your feature request related to a problem? Please describe

systemd does not support the [recently released `libbpf` v1.0.0](https://github.com/libbpf/libbpf/releases/tag/v1.0.0).

### Describe the solution you'd like

- Bump the version of `libbpf.so`: https://github.com/systemd/systemd/blob/1a0e065e9f154f46fd68cd45f46310bc7df7a51c/src/shared/bpf-dlopen.c#L49
- Adapt implementation which currently relies on functions which got removed in v1.0.0 (`bpf_create_map`, `bpf_map__resize`, `bpf_probe_prog_type`, maybe others).

### Describe alternatives you've considered

None

**Comment by bluca** [comment]
They really went ahead and broke backward compatibility? Seriously? _sigh_

**Comment by bluca** [comment]
I'd much rather wait before adding ifdeffery all over the place, and ensure this is really ready for production usage. Breaking backward compatibility like that heavily suggests it's not. We need to make sure it's not going to happen again soon. We can't be in a situation where we accumulate piles and piles of ifdefs to chase whatever they are doing.

**Comment by vcunat** [comment]
AFAIK it was all deprecated features that have been printing warnings about it for some time.

**Comment by bluca** [comment]
That is irrelevant, a reliable and production ready library never breaks API, things can be marked as deprecated and rearranged internally but never removed. See libsystemd0 for an example.

**Comment by martinetd** [comment]
They properly upgraded the so version (it'll be libbpf.so.1), so won't require ifdeffery: just use the version you found. That's pretty standard too.

Yes it's possible to have symbol versioning and maintain compat symbols forever (they actually do symbol versioning), but that requires preparation and libbpf 0.x was 0.x for a reason...
Now it's stable it shouldn't break again (at least what's what I understood of the plan, cf. the dozen of issues for libbpf 1.0 planning on their repo: https://github.com/libbpf/libbpf/issues?q=is%3Aissue+1.0 )


Anyway, there shouldn't be any big breakage, just features requiring libbpf unavailable until the new interfaces are used if only the newer version is available. Until then both can be installed in parallel.

**Comment by bluca** [comment]
Of course it will require a mountain of ifdefs, since interfaces have changed/disappeared, so everything that is different will need to be behind an ifdef to support both versions. This is a huge mess that could have been very easily avoided with little effort, by providing a shim layer. Instead they decided not to care and push the work onto the users. It is very much not ok, and it reflects very badly on the quality of that project.

We already have to deal with the kernel breaking backward compatibility every other day, but we can't really avoid that. Userspace components though we can and should avoid like the plague if they start behaving like the kernel.

**Comment by vcunat** [comment]
The replacement APIs have been available for quite some time already in previous versions, but I don't know how the migration will turn out in systemd case.  (Still, as a different user of libbpf, the transition was too sudden for me.)

**Comment by DaanDeMeyer** [comment]
> The replacement APIs have been available for quite some time already in previous versions, but I don't know how the migration will turn out in systemd case. (Still, as a different user of libbpf, the transition was too sudden for me.)

`bpf_create_map()` was added not even a year ago unfortunately. I don't mind removing deprecated APIs, but if the replacement API can't be used yet on every distro it might be slightly early.

At least for now, we're not getting around ifdeffery to allow using v1.0.0 until more distros switch to a more recent version of libbpf.

**Comment by mrc0mmand** [comment]
Arch just moved to libbpf 1.0.0, so this should, probably, get resolved soon - https://archlinux.org/packages/core/x86_64/libbpf/

**Comment by mrc0mmand** [comment]
Resolved by https://github.com/systemd/systemd/pull/24511.
