### ISSUE TITLE
systemd can output invalid ANSI escape sequences to the serial console, breaking tmux

### ISSUE THREAD

**Issue by jlebon** [systemd/systemd#24502]
### systemd version the issue has been seen with

250, 251

### Used distribution

Fedora 36, 37, 38

### Linux kernel version used

5.18.16-200.fc36.x86_64 - 6.0.0-0.rc2.20220826git4c612826bec1.22.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

When booting Fedora CoreOS (stable or rawhide) via QEMU and connecting to the serial console, systemd writes valid ANSI escape sequences to the console when styling and colouring output.

### Unexpected behaviour you saw

When booting Fedora CoreOS (stable or rawhide) via QEMU and connecting to the serial console, systemd writes *invalid* ANSI escape sequences to the console when styling and colouring output. This can breaks at least tmux, which stops printing output following a particular bad sequence (clearly, there's a tmux bug to be filed there to strengthen its parser, but I think we should fix the systemd side too). GNOME Terminal does not break on this.

### Steps to reproduce the problem

Download and verify the Fedora CoreOS image from [getfedora.org](https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable&arch=x86_64). From within tmux, boot it up using QEMU while also `tee`ing its output to a file:

```
$ curl -L --remote-name-all https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220806.3.0/x86_64/fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2.xz{,.sig}
$ gpg --verify fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2.xz.sig fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2.xz
$ unxz fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2.xz
$ qemu-system-x86_64 -machine accel=kvm -cpu host -m 1G -smp 1 -nographic -drive if=virtio,file=fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2,format=qcow2 -snapshot -display none | tee console.log
...
[  OK  ] Listening on systemd-userd…0m - User Database Manager Socket.
[    6.158164] systemd[1]: Mounting dev-hugepages.mount - Huge Pages File System...
         Mounting dev-hugepages.mount - Huge Pages File System...
[    6.159810] systemd[1]: Mounting dev-mqueue.mount - POSIX Message Queue File System...
         Mounting dev-mqueue.mount
<no further output at this point - terminate with [Ctrl-A X]>
```

Looking at `console.log` directly using `less` (without `-R` to display the raw ANSI sequences), we see:

```
[ESC[0;32m  OK  ESC[0m] Started ESC[0;1;39msystemd-journald.serviceESC[0m - Journal Service.
[ESC[0;32m  OK  ESC[0m] Mounted ESC[0;1;39mdev-mqueue.mountESC[…- POSIX Message Queue File System.
[ESC[0;32m  OK  ESC[0m] Mounted ESC[0;1;39msys-kernel-debug.m…ntESC[0m - Kernel Debug File System.
[ESC[0;32m  OK  ESC[0m] Mounted ESC[0;1;39msys-kernel-tracing…ntESC[0m - Kernel Trace File System.
```

Notice this bit in the second line:

```
Mounted ESC[0;1;39mdev-mqueue.mountESC[…
```

What's supposed to be the reset ANSI escape sequence has been truncated and so remains incomplete. I believe this is part of what throws off tmux and causes it to stop displaying output.

I think the core issue is that the [`ellipsize_mem()`](https://github.com/systemd/systemd/blob/125d108665506e8abfd575f2cbf7adf9d0ae0a00/src/basic/string-util.c#L347) function (in this case, reached via `unit_status_printf()` -> `manager_status_printf()` -> `status_vprintf()` -> `ellipsize()`) used to shorten strings when writing status outputs is not ANSI sequence-aware and so can unknowingly ellipsize the input string in the middle of a sequence.

Possible options include enhancing `ellipsize()` to become sequence-aware, providing higher level callers like `unit_status_printf()` with a better interface so that e.g. the text to be stylized is passed separately so that it can be stylized *after* any ellipsizing, or changing callers to never include escape sequences in the middle of the string.

Possible workarounds for this include booting with `systemd.status_unit_format=name`, or with `systemd.log_color=0`, or not using tmux.

The original Fedora CoreOS bug is tracked at https://github.com/coreos/fedora-coreos-tracker/issues/1179.

**Comment by poettering** [comment]
ouch
