### ISSUE TITLE
network interface naming in container

### ISSUE THREAD

**Issue by tmartin-git** [systemd/systemd#24506]
### Component

systemd-nspawn

### Is your feature request related to a problem? Please describe

Allow naming of {mac,ip}vlan network interface inside the container.

### Describe the solution you'd like

Just like `--network-veth-extra=`, add `--network-{ip,mac}vlan-extra=`

... or directly support the <hostIfname>[:<containerIfname>] pattern as --network-{ip,mac}vlan option.

### Describe alternatives you've considered

[#24028](https://github.com/systemd/systemd/issues/24028)
Unfortunatly, this option involves:
- to embed specific tools inside the container 
- and let the container be "aware" of the host interface name.

**Comment by tmartin-git** [comment]
Because it seems easier to configure network interface name while using
systemd-nspaw and much more complex if you have to do it in your container.

Let's imagine you want to have an "orchestrator" on top of that.
While it's easy to define the interface name via the systemd-nspawn
interface, it gets more complicated / impossible to patch the container
image to fix interface names.

If you give direction on how you would implement this feature, I may give a
hand an provide patches.

**Comment by poettering** [comment]
I am not convinced the if name of the primary iface should really be a first class config option. it's just taping over bad userspace that hardcodes an archaic name. People shouldn't do that.

That said, I'd be fine with making it a second class config option. i.e. a new env var $SYSTEMD_NSPAWN_HOST_IFNAME that if set overrides the `host0` default we use. And then document it in docs/ENVIRONMENT.md.

**Comment by tmartin-git** [comment]
Sorry, my request was probably not clear.

As far as I understand, "host0" is for veth (not macvlan-interface).

I'd like to have a macvlan-interface with a user-defined name inside the
container.

Something like --network-macvlan=enp0s1:eth0

The user of systemd-nspawn can decide the mapping of network devices inside
of the container, for instance making sure that it properly assigns
production vs administration network devices based on the interface names
provided by container image maintainer.

**Comment by poettering** [comment]
ah, ok, it's for those. sure then, sounds ok. feel free to send a PR.

**Comment by tmartin-git** [comment]
Great, thanks !

**Comment by tmartin-git** [comment]
As discussed, I have submitted this:
systemd-nspawn: support colon-separated pair of host / container network interface names #24579
