### ISSUE TITLE
add udev rules for google titan security keys

### ISSUE THREAD

**Issue by wbolster** [systemd/systemd#24501]
### Component

udev rule files

### Is your feature request related to a problem? Please describe

udev does not seem to include support for [google titan security keys](https://store.google.com/gb/product/titan_security_key?hl=en-GB). it would be nice if this worked by default.

the google support website even suggests adding a `70-titan-key.rules` manually:

> Udev version 188 or higher:
> 
> ```
> KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="18d1|096e", ATTRS{idProduct}=="5026|0858|085b", TAG+="uaccess"
> ```

and

> Udev version 187 or lower:
> ```
> KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="5026", GROUP="plugdev", MODE="0660"
> ```

source: https://support.google.com/titansecuritykey/answer/9148044?hl=en

### Describe the solution you'd like

include udev rules

### Describe alternatives you've considered

manually add the udev rules

### The systemd version you checked that didn't have the feature you are asking for

251.4-1-arch

**Comment by poettering** [comment]
does udev's `fido_id` not detect the devices as FIDO? 

is it possible that google page is just badly out of date?

**Comment by poettering** [comment]
As it turns out I actually have a google titan usbc token here. And it just works:

```
$ udevadm info /dev/hidraw1
P: /devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5:1.0/0003:096E:085B.0006/hidraw/hidraw1
N: hidraw1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5:1.0/0003:096E:085B.0006/hidraw/hidraw1
E: DEVNAME=/dev/hidraw1
E: MAJOR=239
E: MINOR=1
E: SUBSYSTEM=hidraw
E: USEC_INITIALIZED=74837042197
E: ID_FIDO_TOKEN=1
E: ID_SECURITY_TOKEN=1
E: ID_PATH=pci-0000:00:14.0-usb-0:5:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_5_1_0
E: ID_FOR_SEAT=hidraw-pci-0000_00_14_0-usb-0_5_1_0
E: TAGS=:security-device:uaccess:seat:
E: CURRENT_TAGS=:security-device:uaccess:seat:
```

So the google stuff is just out of date, it can be removed altogether for current systemd versions. Maybe Google's anti-systemd stance makes them ignore all recent versions? dunno.

Closing. (Feel free to reopen, if this doesn't work for you)

**Comment by wbolster** [comment]
cool, thanks. i am still waiting for my own to arrive so i could test against a recent systemd. but you beat me to it 👍🏼
