### ISSUE TITLE
systemd-boot fails to load decompressed linux image

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24505]
### systemd version the issue has been seen with

main

### Used distribution

Fedora 36

### Linux kernel version used

5.19.4-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

systemd-boot can boot from a decompressed linux image

### Unexpected behaviour you saw

systemd-boot fails to boot from a decompressed linux image:

```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Scsi(0x0,0x0)
Error loading \3e596be891294e91a0efede3f40b1fe6\5.19.4-200.fc36.x86_64\linux: Unsupported
Failed to execute Fedora Linux 36 (Thirty Six) (5.19.4-200.fc36.x86_64) (\3e596be891294e91a0efede3f40b1fe6\5.19.4-200.fc36.x86_64\linux): Unsupported
```

This also fails when using unified kernel images but with a different error:

```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Scsi(0x0,0x0)
Error loading \EFI\Linux\mkosi-fedora-5.19.4-200.fc36.x86_64.efi: Load Error
Failed to execute Fedora Linux 36 (Thirty Six) (36 (Thirty Six)) (\EFI\Linux\mkosi-fedora-5.19.4-200.fc36.x86_64.efi): Load Error
BdsDxe: failed to start Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Scsi(0x0,0x0): Load Error
```

### Steps to reproduce the problem

```
git clone https://github.com/DaanDeMeyer/mkosi -b aarch64-vmlinux
cd mkosi
sudo mkosi --bootable --qemu-headless --autologin --without-unified-kernel-images -f qemu # Fails with "Unsupported"
sudo mkosi --bootable --qemu-headless --autologin -f qemu # Fails with "Load Error"
```

**Comment by DaanDeMeyer** [comment]
Extra information is that the decompressed kernel is an ELF executable which I guess might simply not be supported by systemd-boot

**Comment by medhefgo** [comment]
If it's not a valid EFI (PE) image, it cannot be booted.

**Comment by poettering** [comment]
Yeah, we only support booting UEFI PE stuff in sd-boot, as per docs. i think we can close this, no?
