### ISSUE TITLE
systemd-resolved fails to start

### ISSUE THREAD

**Issue by laur89** [systemd/systemd#24564]
### systemd version the issue has been seen with

251.4-3

### Used distribution

Debian testing (bookworm)

### Linux kernel version used

5.18.0-4-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Upon system start, `systemd-resolved` process starts.

`systemctl restart systemd-resolved.service` successfully restarts it.

### Unexpected behaviour you saw

systemd-resolved does not start on system boot. Explicitly starting it via `systemctl start systemd-resolved.service` also fails.

### Steps to reproduce the problem

```
$ sudo systemctl status systemd-resolved.service
[sudo] password for laur: 
× systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; preset: enabled)
     Active: failed (Result: signal) since Mon 2022-09-05 11:08:19 CEST; 11min ago
       Docs: man:systemd-resolved.service(8)
             man:org.freedesktop.resolve1(5)
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
    Process: 9167 ExecStart=/lib/systemd/systemd-resolved (code=killed, signal=SYS)
   Main PID: 9167 (code=killed, signal=SYS)
        CPU: 38ms

Sep 05 11:08:19 p14s systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
Sep 05 11:08:19 p14s systemd[1]: Stopped Network Name Resolution.
Sep 05 11:08:19 p14s systemd[1]: systemd-resolved.service: Start request repeated too quickly.
Sep 05 11:08:19 p14s systemd[1]: systemd-resolved.service: Failed with result 'signal'.
Sep 05 11:08:19 p14s systemd[1]: Failed to start Network Name Resolution.
```

```
$ sudo systemctl start systemd-resolved.service
Job for systemd-resolved.service failed because a fatal signal was delivered to the control process.
See "systemctl status systemd-resolved.service" and "journalctl -xeu systemd-resolved.service" for details.
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
- gist with relevant excerpt from syslog & unit file: https://gist.github.com/laur89/10fa7d24c756fd3e1c32fad764004d66
- `journalctl -xeu systemd-resolved.service` returns nothing
- nothing more useful in journalctl than what was seen in /var/log/syslog (see above)
```

**Comment by poettering** [comment]
interesting. SIGSYS happens on a bad system call, or when some seccomp filter is applied that triggers that. I am puzzled by this. Is this in some container, or in some sandboxed env, or on some emulator or strange arch combination?

**Comment by laur89** [comment]
Nah, it's running on metal.

**Comment by laur89** [comment]
Ah ffs, some clever debian package management is behind this, not you guys!

If anyone else stumbles upon this in the coming weeks, then it's likely caused by `systemd-resovled` package no longer being installed! Didn't receive any relevant news during last upgrade.
See [this mail list](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939904) for further info.

Shit-show of a change in my book, but that's neither here nor there. Closing.
