### ISSUE TITLE
journalctl - Can not follow merged journals (eg. remotes)

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#24565]
### systemd version the issue has been seen with

251.4

### Used distribution

archlinux

### Linux kernel version used

5.19.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

Following (multiple) remote journals should be possible

### Unexpected behaviour you saw

executing `journalctl -mf` throws:
> Using --boot or --list-boots with --merge is not supported

**Comment by arwie** [comment]
Commit 2dd9285 introduced this bug by adding `arg_boot = true;` to --follow
Is it really necessary because it breaks the merge feature?

**Comment by PeterMarkuson** [comment]
Would be nice to see this fixed, either by going back or enable the -b switch with -r -m together.
Basically all of my remote-monitoring is based on merge & follow logs from all machines in my cluster. I am using a central logserver for that. An update to this new journal version is not an option for me :(

**Comment by meehand** [comment]
I worked around this issue by adding `-b all` to the command
i.e. `journalctl -mf -b all` works for my use case at least
