### ISSUE TITLE
[networkd] Assertion '!(msg.msg_flags & MSG_TRUNC)' failed

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#2457]
systemd compiled from git (b3042837397380b9a4d0900f5e00452f0f87a808) ([Arch AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-git))
the system is a libvirt/kvm archlinux guest. It has a single ens5 interface set to use DHCP (just [Network] DHCP=yes).

networkd crashes with:

```
Jan 28 07:34:26 arch-uefi-test systemd[1]: Starting Network Service...
Jan 28 07:34:26 arch-uefi-test systemd-networkd[10140]: ens5: Gained IPv6LL
Jan 28 07:34:26 arch-uefi-test systemd-networkd[10140]: Enumeration completed
Jan 28 07:34:26 arch-uefi-test systemd[1]: Started Network Service.
Jan 28 07:34:26 arch-uefi-test systemd-networkd[10140]: ens5: Could not drop address: No such process
Jan 28 07:34:26 arch-uefi-test systemd-networkd[10140]: Assertion '!(msg.msg_flags & MSG_TRUNC)' failed at src/libsystemd-network/sd-ndisc.c:536, function ndisc_router_advertisment_recv(). Aborting.
Jan 28 07:34:26 arch-uefi-test systemd[1]: systemd-networkd.service: Main process exited, code=killed, status=6/ABRT
Jan 28 07:34:26 arch-uefi-test systemd[1]: systemd-networkd.service: Unit entered failed state.
```

**Comment by poettering** [comment]
@teg, any idea?

**Comment by gdamjan** [comment]
logging out len and buflen before that assert they are both 74.

**Comment by gdamjan** [comment]
But!
I've set buflen to a fixed 1500, len (from recvmsg) now is 144 bytes, and the assert no longer applies. it seems that the `r = ioctl(fd, FIONREAD, &buflen);` doesn't return the proper value??

**Comment by poettering** [comment]
Strange... that would indicate a kernel bug...

**Comment by gdamjan** [comment]
I tried both 4.4.1 and 4.1.17 (arch kernels) same behaviour. isn't it possible for data to arrive after FIONREAD is called?

**Comment by poettering** [comment]
well, but it's a datagram interface... datagrams should not change their size just because more datagrams have been received...

But maybe the local queuing drops datagrams for some reason (after all, they are allowed to do that, it's IP). and hence between FIONREAD and recvmsg() the packet we are about to process changes...

**Comment by gdamjan** [comment]
a quick workaround would be to use a `uint8_t buffer[BUFFER_MAX_SIZE];` on the stack to read into instead of the dynamically malloc/_cleanup_free_ heap variable?

(edit) … or malloc enough bytes for an RA.

**Comment by gdamjan** [comment]
Any ideas? I will send  a pull request to just malloc a buffer of 2048, it seem the better option than the current.

ps. there are no 74 byte icmp6 datagrams on the network, only 144 byte ones (checked with `sudo tcpdump -i bridge0 -nv icmp6`).

**Comment by teg** [comment]
Thanks for the report. This seems really odd. I'll have a look.

**Comment by teg** [comment]
how reproducible is this for you? if you add logging to record every successful packet, does it get the wrong size every time, or just some of the time?

**Comment by gdamjan** [comment]
fully reproducible 
I get the same thing all the time

**Comment by poettering** [comment]
@gdamjan could you check if the patch in #2626 fixes the problem for you?
