### ISSUE TITLE
[resolved]: Add DNS with custom port?

### ISSUE THREAD

**Issue by khusseini** [systemd/systemd#24578]
Hello, 

I am trying to add a local DNS with a custom port `127.0.0.1:30053` in a stub like so:
`/usr/local/lib/systemd/resolved.conf.d/myrpoject.conf`:
```
nameserver 127.0.0.1:30053

[Resolve]
DNS=127.0.0.1:30053
```

the configuration seems to be accepted:

```bash
$> resolvectl
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 127.0.0.1:30053
       DNS Servers: 127.0.0.1:30053
...
```

```bash
$> nslookup -port=30053 myproject.local 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#30053

Name:   myproject.local
Address: 192.168.102.109
```

however a normal nslookup doesnt work:

```bash
$> nslookup myproject.local                      
Server:         127.0.0.53
Address:        127.0.0.53#53

** server can't find myproject.local: SERVFAIL

```

Does anyone have an idea what's going on?

**Comment by poettering** [comment]
".local" is the mDNS zone. It is dispatched via mDNS and not classic DNS, and hence defining an upstream unicast DNS server won't have an effect on it.
