### ISSUE TITLE
confusing manual entry for systemctl kexec

### ISSUE THREAD

**Issue by giorgiga** [systemd/systemd#24588]
### systemd version the issue has been seen with

systemd-250.8-1.fc36

### Used distribution

fedora f36

### Linux kernel version used

5.19.6-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

    # man systemctl
    [...]
        kexec
            [...]
            This is equivalent to systemctl start kexec.target --job-mode=replace-irreversibly --no-block.
            [...]
    [...]

### Unexpected behaviour you saw

Without additional preparation `systemctl kexec` prints an error message, while `systemctl start kexec.target` reboots the system... so they don't seem to be equivalent at all.

The reason for the different behaviour is that starting the target ends up executing `systemctl --force kexec` (via systemd-kexec.service), which succedes even when a default boot entry cannot be clearly identified (compare `sudo sh -c 'SYSTEMD_LOG_LEVEL=debug systemctl kexec --dry-run'` and `sudo sh -c 'SYSTEMD_LOG_LEVEL=debug systemctl --force kexec --dry-run'` and see https://github.com/systemd/systemd/blob/main/src/systemctl/systemctl-start-special.c#L175).

That the two commands are different seems intentional, so I'd say the documentation in man/systemctl.xml (and possibly man/systemd.xml, where it talks about "SIGRTMIN+6") is not up to date.  

Note that whether failing with an error mesage is the best behaviour for `systemctl kexec` is the subject of existing ticket #15029. 

### Steps to reproduce the problem

Without prior calls to kexec, run `system kexec` and `systemd start kexec.target` and see the difference (the latter will restart your system).

**Comment by felagund** [comment]
I will note that manual for systemd uses:

> SIGRTMIN+6
           Reboots the machine via kexec, starts the kexec.target unit. This is mostly equivalent to systemctl start
           kexec.target --job-mode=replace-irreversibly.

„mostly“ is also not terribly clear - what is the difference actually? It got me confused, details in the issue linked just above this comment.

Also, per https://lists.freedesktop.org/archives/systemd-devel/2022-August/048235.html, they are expected to behave the same, so maybe this is a bug? Or are they not expected to work the same after all?
