### ISSUE TITLE
DHCP4 lease is lost when networkd service is stopped

### ISSUE THREAD

**Issue by sshedi** [systemd/systemd#24584]
### systemd version the issue has been seen with

247.11

### Used distribution

Photon OS 4.0

### Linux kernel version used

5.10.118

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

DHCP lease should not expire upon stopping networkd service or rebooting the system.

### Unexpected behaviour you saw

DHCP lease is lost when networkd is stopped or system is rebooted.
Attaching the networkd debug logs for more info.
[networkd.log](https://github.com/systemd/systemd/files/9498807/networkd.log)

My network file:
```
root@wdc-rdops-vm10-dhcp-0-139 [ ~ ]# cat /etc/systemd/network/10-eth0.network 

[Match]
Name=eth0
[Network]
LinkLocalAddressing=no
DHCP=ipv4
[DHCP]
UseDomains=true
ClientIdentifier=mac
```

If I append `CriticalConnection=true` to `[DHCP]` section, then IP is retained.
Also if I do `systemctl restart systemd-networkd` IP is not lost.

We have `systemd-239` in Photon OS 3.0 and the ip is not changing in it when networkd is stopped or system is rebooted.

### Steps to reproduce the problem

systemctl stop systemd-networkd & check journal logs.

We see something like:
```
Sep 06 15:11:31 wdc-rdops-vm10-dhcp-0-139.eng.vmware.com systemd[1]: systemd-networkd.service: Got notification message from PID 107700 (STOPPING=1, STATUS=Shutting down...)
Sep 06 15:11:31 wdc-rdops-vm10-dhcp-0-139.eng.vmware.com systemd-networkd[107700]: DHCP CLIENT (0x893a3129): STOPPED
Sep 06 15:11:31 wdc-rdops-vm10-dhcp-0-139.eng.vmware.com systemd-networkd[107700]: DHCP CLIENT (0x893a3129): RELEASE
Sep 06 15:11:31 wdc-rdops-vm10-dhcp-0-139.eng.vmware.com systemd-networkd[107700]: eth0: DHCP lease lost
```

Same when machine is rebooted.

**Comment by sshedi** [comment]
Yes, the existing ipv4 address is lost and a new one is given by server immediately.

**Comment by yuwata** [comment]
Even if `CriticalConnection=true` is set?? The option is mandatory if you want to keep the address.
Though, even with the setting, still journal log shows `DHCP lease lost`.

**Comment by sshedi** [comment]
No, if I set `CriticalConnection=true` then IP is not lost.
The thing is, it's working fine with systemd-239 but in systemd-247.11, lease is lost after rebooting the system. The lease time is 2 hr but it's not honored.

**Comment by yuwata** [comment]
I guess we have never kept acquired address on reboot. And, there is no guarantee in the DHCP protocol that DHCP server provides the same address on each request.

BTW, v239 and v247 is too old here, please contact to your downstream, or try to reproduce the 'issue' (though, I do not think it is an issue) with the recent release (v250 or v251) or the current git HEAD. Closing.

Feel free to request to reopen this page if you find anything on recent releases.

**Comment by sshedi** [comment]
I see the same issue in `systemd-251.4` as well.
```
Sep 06 17:19:05 photon-7577 systemd[1]: Stopping Network Configuration...
░░ Subject: A stop job for unit systemd-networkd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A stop job for unit systemd-networkd.service has begun execution.
░░
░░ The job identifier is 2968.
Sep 06 17:19:05 photon-7577 systemd-networkd[702]: eth0: DHCP lease lost
Sep 06 17:19:05 photon-7577 systemd-networkd[702]: eth0: DHCPv6 lease lost
Sep 06 17:19:05 photon-7577 systemd[1]: systemd-networkd.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
```

The acquired address is kept at least in `systemd-239` and I don't see `DHCP lease lost` message in it when I stop networkd service.

**Comment by yuwata** [comment]
Ah, I remembered. We have introduced `SendRelease=` which sends release message to the server on restarting networkd or reboot the machine. Hence, the server release the address and put back to the address pool.
Please try to set `SendRelease=no` in [DHCPv4] section.

**Comment by sshedi** [comment]
@yuwata thanks a lot, you saved my day. Just a small correction, it should be `SendRelease=false`.

Ultimately, we need to add this to .network file to get it working like earlier version of systemd.

```
...
[DHCPv4]
SendRelease=false
```

**Comment by sshedi** [comment]
Hi @yuwata, another query. What is the equivalent of this setting for `[DHCPv6]`?
