### ISSUE TITLE
Make systemd-gpt-auto-generator mount ESP with '-o flush'

### ISSUE THREAD

**Issue by marcosfrm** [systemd/systemd#2459]
`flush` option in vfat driver is supported since kernel 2.6.19. It is a lightweight `-o sync`, does not compromise performance too much and data is commited to disk faster.

References:
http://kernelnewbies.org/Linux_2_6_19#head-f01ddab8484abaf0ddea721f329b5a9499d0912e
https://bugs.freedesktop.org/show_bug.cgi?id=51063
https://bugs.kde.org/show_bug.cgi?id=273792

**Comment by poettering** [comment]
The ESP mount is already an automount, thus we cleanly unmount it after a short idle time, which is certainly better than "flush".

**Comment by marcosfrm** [comment]
Yes, but `flush` would narrow down the "dirty window" even more.
