### ISSUE TITLE
udev: support SYMLINK-=

### ISSUE THREAD

**Issue by Hi-Angel** [systemd/systemd#24607]
### systemd version the issue has been seen with

237, 250, 251

### Used distribution

Ubuntu 18.04, Fedora 36, Archlinux

### Linux kernel version used

5.19.6-lqx1.0.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

Symlink `/dev/test` shouldn't exist

### Unexpected behaviour you saw

Symlink `/dev/test` was created

### Steps to reproduce the problem

We have a number of system rules we want to override, but the "official" way with copying a `.rules` file is fragile, because the system file may change upon packages update, file names may change, so everything will silently break. So instead we use `-=` to remove from lists unwanted names, which is expected to work per `man udev`. Well, it actually doesn't 🤷

Steps to reproduce in terms of terminal commands:

```
# echo 'ENV{DEVTYPE}=="disk", SYMLINK+="test"' > /etc/udev/rules.d/98-test.rules
# echo 'ENV{DEVTYPE}=="disk", SYMLINK-="test"' > /etc/udev/rules.d/99-test.rules
# udevadm control --reload-rules && udevadm trigger
# ls /dev/test
/dev/test
```

**Comment by poettering** [comment]
See #9463

**Comment by Hi-Angel** [comment]
The operator `=` doesn't work as well.

**Comment by Hi-Angel** [comment]
Yaay! I found a workaround! Given the "steps-to-reproduce", just replace a `/etc/udev/rules.d/99-test.rules` content with

```
ENV{DEVTYPE}=="disk", RUN+="/bin/rm /dev/disk/by-id/test"
```

The `RUN` is also a list, and apparently it's executed in priority order. And since the `99-test..rules` has priority to be executed last, by the time it happens the symlink was created, and can just be removed. Excelent!

Yeah, it's worse than just using `-=` would be, but that's what workarounds are. It's still clearly better, than the official way with overriding the files.

**Comment by Hi-Angel** [comment]
Wow, too early to celebrate. At least on the older systemd 237 there's a bug where the symlink may occasionally be left a place. Good that I discovered that bug before I rewrote all our rules and commited. Gotta check now if it's reproducible in latest systemd version and then report a bug \*sigh\* Yeah, nice `.rules` support.

**Comment by Hi-Angel** [comment]
Okay, kinda good news is that on `systemd 250` the workaround works. I ran a cycle

```
for i in {1..100}; do udevadm control --reload-rules && udevadm trigger && ls /dev/test; echo $i; done
```

and never saw the `/dev/test` file created. So for future readers, this may work for you depending on a systemd version. Older ones has the race condition, newer ones don't and hopefully won't.

I personally though defeated. The system at work has older systemd where udev is apparently completely broken, so not much I can do besides the infamous `.rules` file override.

**Comment by Hi-Angel** [comment]
Using a `IMPORT{program}` feature to override SYMLINK doesn't work either.

**Comment by Hi-Angel** [comment]
@yuwata I see you replaced a label `bug` with `RFE`. It's not really correct, because this report is about something that is documented by `man udev` to work however it doesn't. So it is actually a bug.

**Comment by yuwata** [comment]
Comparing with udev(7), this actually sounds a bug, but the man page is not complete. Currently, it does not clarify what operands supported by each token.

`SYMLINK` has never supported `-=`. Hence, I think this should be RFE.

Besides of this is RFE or bug, I agree with that `SYMLINK` should support `-=` for consistency with other token. The meaning of `-=` for `SYMLINK` should be trivial. There is no reason we should to refuse it. Such syntax may be useful to tentatively disable specific symlinks.

**Comment by yuwata** [comment]
Anyway, I rebased #9463 and submitted as #26081.
