### ISSUE TITLE
Add OpenFile= to pass a path on the host as a file descriptor to a service

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24614]
### Component

systemd

### Is your feature request related to a problem? Please describe

I got an interesting question from an internal user who wants to run a sandboxed daemon that backs a fuse filesystem. So they want to do the mount of the fuse filesystem itself in the host mount namespace, but the process itself to live in its own private mount namespace. They were trying to use mount propagation to make it work, but sandboxing overrides `MountFlags=shared` so that didn't work.

I figure that to support this use case, we should support a way to pass a file descriptor to the host mount namespace (or any file really) to a service. `mount` could use the passed fd to access the host mount namespace to perform the mount

We should maybe support assigning specific file descriptor numbers to specific fds, so that a service can make reasonable assumptions about the intended use of a passed file descriptor.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
Note that you cannot mount an inode from a different mount namespace into your own currently (i.e. via a /proc/self/fd/ path). Kernel has an explicit check prohibiting that right now.

**Comment by poettering** [comment]
But yeah, there's somewhere an RFE for adding a concept of OpenFile= or so, which would allow opening arbitrary additional files when executing a service and passing that down. Independently of the specific usecase the concept I think makes a ton of sense.

**Comment by pallotron** [comment]
> I got an interesting question from an internal user 

it's a-me :) subscribing to this :)

**Comment by DaanDeMeyer** [comment]
We discussed exactly how this should work in the chat. systemd already supports passing names for passed file descriptors (see https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html), and `OpenFile=` would just hook into that. So the syntax would be `OpenFile=<path-to-file-on-host>:<fd-name>:<options>` where the initial options could be `rw` and `ro`. `fd-name` would be optional and if not provided, the name would default to the filename of the file on the host filesystem. Also, if the path points to an AF_UNIX socket, pid1 connect()'s to that socket and passes the connected file descriptor to the service.
