### ISSUE TITLE
following system log seems to default to --no-tail

### ISSUE THREAD

**Issue by automaticgiant** [systemd/systemd#2461]
Version 228.
Does --no-tail just not [supposed to] work on system log? It clips old user log messages, but as soon as a system message comes through, it dumps the entire system log.
Using Arch.
Reproduce with `sudo journalctl -f` or `journalctl -f` from systemd-journal group.

**Comment by keszybz** [comment]
No, `journalctl -f` should work the same on all kinds of logs. Most likely it was confused by some log file. We had various improvements to make `journalctl` more reliable recently. Please reopen if you can reproduce this with systemd 232 or later.
