### ISSUE TITLE
busctl - I am able to create a failed scope transient unit attaching the unexistent pid 0

### ISSUE THREAD

**Issue by lipixx** [systemd/systemd#24613]
### systemd version the issue has been seen with

246

### Used distribution

Fedora 33

### Linux kernel version used

5.14.18-100.fc33.x86_64

### Component

systemd

### Expected behaviour you didn't see

I would expect to see this error message when creating the scope and systemd refusing to create a failed unit:

Call failed: Process with ID 0 does not exist.

### Unexpected behaviour you saw

I saw the scope transient unit was created with a failed state and no cgroup associated.

### Steps to reproduce the problem

Run a call to dbus for creating a transient unit with pid 0 as the parameter:
```
]# busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartTransientUnit 'ssa(sv)a(sa(sv))' 'my_dbus.scope' fail 1 PIDs au 1 0 0
o "/org/freedesktop/systemd1/job/39873"
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
]# systemctl status my_dbus.scope
● my_dbus.scope
     Loaded: loaded (/run/systemd/transient/my_dbus.scope; transient)
  Transient: yes
     Active: failed (Result: resources)
        CPU: 0

sep 09 14:28:15 llit systemd[1]: Started my_dbus.scope.
sep 09 14:28:28 llit systemd[1]: my_dbus.scope: Succeeded.
sep 09 14:36:26 llit systemd[1]: my_dbus.scope: Failed to add PIDs to scope's control group: No such process
sep 09 14:36:26 llit systemd[1]: my_dbus.scope: Failed with result 'resources'.
sep 09 14:36:26 llit systemd[1]: Failed to start my_dbus.scope.
```

**Comment by yuwata** [comment]
v246 is too old here. Please try to reproduce with recent releases (v250 or v251) or current git HEAD.

**Comment by yuwata** [comment]
When `0` is specified for `PIDs`, then pid is obtained the dbus credential (in most cases, sender's pid, I guess). As busctl terminates soon after creating the slice unit, and before the slice is starting. So, I think the failure is expected.

**Comment by poettering** [comment]
pid 0 for apis like this is a shortcut for the client's pid.

it's inspired by how the kernel does this. i.e. kill(0, …) actually kills your own process and so on.
