### ISSUE TITLE
Please support RFC 8925 IPv6-Only Preferred Option for DHCPv4 (Option 108)

### ISSUE THREAD

**Issue by cvmiller** [systemd/systemd#24624]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

Testing with systemd v251 (the latest), systemd does not follow the behavour of RFC 8925, where as MacOS v12 & iOS v15 do. Systemd still requests an IPv4 address, even though option 108 is present in the DHCP offer.

### Describe the solution you'd like

Since Oct 2020, there has been a standard for DHCPv4 clients to accept Option 108  (IPv6-Only Preferred Option), and not request an IPv4 address if the option is present. RFC 8925 specifies the client behavour: https://www.ietf.org/rfc/rfc8925.html

Please include DHCPv4 Option 108 in your development roadmap.

### Describe alternatives you've considered

There are few alternatives, since systemd is included in all the major Linux distros.

**Comment by keszybz** [comment]
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2212357

**Comment by ssahani** [comment]
PR https://github.com/systemd/systemd/pull/28950

**Comment by pemensik** [comment]
This were fixed in PR #29472, thank you!
