### ISSUE TITLE
`dmesg -d` functionality for `journalctl`

### ISSUE THREAD

**Issue by elazarl** [systemd/systemd#24641]
### Component

systemd-journald

### Is your feature request related to a problem? Please describe

It is sometimes useful to print the time difference between adjacent kernel log lines, like `dmesg -d` does.

For example, during development, adding `printk` before and after a lock, can estimate how long you've been waiting for it. See `dmesg -d`:

```
[1130019.437698 <    0.000001>] R10: 0000000000000000 R11: 0000000000000207 R12: 00000000008ab000
[1130019.437699 <    0.000001>] R13: 0000000000000000 R14: 0000000000000000 R15: 0000008054000000
[1130043.432912 <   23.995213>] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [ld-linux-x86-64:1879727]
```

We can easily see the watchdog was triggered ~24 seconds after previous event.

I could not find any similar capability with `journalctl -k`.

I expect to be able to use `_SOURCE_MONOTONIC_TIMESTAMP` and print for each line the difference between this line and the previous one.

### Describe the solution you'd like

I would like `journalctl -dk` to have similar output to `dmesg -d`

### Describe alternatives you've considered

One way to achieve that is using `awk`:

```bash
 sudo journalctl -o short-monotonic -k|sed 's/\[\([^]]*\)\]/\1/'|awk '{printf "%.5f", ($1-prev); print " " $0;prev = $1}'|tail -5
 ```
 
 But this is a piece of obfuscated code, which is not easy to write, and neither easy to maintain.

We could also use general "operate with previous field" printing mechanism, but `dmesg -d` seems common enough

**Comment by q2dg** [comment]
Just for the record, _dmesg -C_ has not equivalent when using _journalctl -k_ neither

**Comment by elazarl** [comment]
@q2dg the problem with `dmesg -C` is that you do not have persistent place to keep the last record.

You can work around that with

```
$ sudo journalctl --show-cursor -qk -n 0 |sed 's/^.*cursor: //' >/tmp/cursor
$ sudo journalctl -k --after-cursor "`sed s/.*cursor:\ // </tmp/cursor`"
-- Logs begin at Thu 2022-09-15 08:51:31 UTC, end at Thu 2022-09-15 09:06:47 UTC. --
Sep 15 08:54:19 vm-srv06-rhel-8-01 kernel: nfs: Deprecated parameter 'intr'
$
```

Anyhow, that's beside the point.

**Comment by mrc0mmand** [comment]
> @q2dg the problem with `dmesg -C` is that you do not have persistent place to keep the last record.
> 
> You can work around that with
> 
> ```
> $ sudo journalctl --show-cursor -qk -n 0 |sed 's/^.*cursor: //' >/tmp/cursor
> $ sudo journalctl -k --after-cursor "`sed s/.*cursor:\ // </tmp/cursor`"
> -- Logs begin at Thu 2022-09-15 08:51:31 UTC, end at Thu 2022-09-15 09:06:47 UTC. --
> Sep 15 08:54:19 vm-srv06-rhel-8-01 kernel: nfs: Deprecated parameter 'intr'
> $
> ```
> 
> Anyhow, that's beside the point.

Actually, in this case you don't have to mess around with the cursor file by yourself, just use `--cursor-file=/tmp/xyz`, which creates/updates the file automagically.

**Comment by elazarl** [comment]
@mrc0mmand journalctl don't have a place to persist things, hence I think you'll have to.

I don't suggest using `--cursor-file`, since:

  1. It's not supported by older versions
  2. You need to postprocess the output anyone, so it doesn't buy you much.

Maybe there's a a way for the cursor-file that can be used verbatime, but I'm not aware of it

**Comment by mrc0mmand** [comment]
>     2. You need to postprocess the output anyone, so it doesn't buy you much.
> 
> 
> Maybe there's a a way for the cursor-file that can be used verbatime, but I'm not aware of it

What do you mean by that? You can just use it for all `journalctl` invocations without ever touching the cursor file:

```
# journalctl -k --no-hostname -n2 --cursor-file=/tmp/cursor
Sep 15 10:02:13 kernel: Buffer I/O error on dev sr0, logical block 7, async page read
Sep 15 12:17:17 unknown: hello
# echo world >/dev/kmsg
# journalctl -k --no-hostname -n2 --cursor-file=/tmp/cursor
Sep 15 12:18:01 unknown: world
```

**Comment by elazarl** [comment]
@mrc0mmand I was referring to the case you do not want to destroy the file, but just to view from it. `journalctl --after-cursor=$(cat /tmp/cursor)`.

Indeed it can work for destructive reading of the cursor.

**Comment by elazarl** [comment]
@mrc0mmand I stand corrected. It does work, probably some bash error on my part. Editing my comment.

**Comment by elazarl** [comment]
@mrc0mmand 

Does not work for my version

```
$ sudo journalctl --show-cursor -qk -n 0  >/tmp/cursor
$ sudo journalctl -k -c "$(cat /tmp/cursor)"
Failed to seek to cursor: Invalid argument
$ cat /tmp/cursor
-- cursor: s=ca3ac4ad630847b0852fdcccff0b0c73;i=8f2;b=ac646ad957764333be8689aeaf97c94c;m=15f735c11;t=5e8b4b844db39;x=c77cd0c7a90fde8b
$ journalctl --version
systemd 239 (239-51.el8)
```

**Comment by mrc0mmand** [comment]
> @mrc0mmand
> 
> Does not work for my version
> 
> ```
> $ sudo journalctl --show-cursor -qk -n 0  >/tmp/cursor
> $ sudo journalctl -k -c "$(cat /tmp/cursor)"
> Failed to seek to cursor: Invalid argument
> $ cat /tmp/cursor
> -- cursor: s=ca3ac4ad630847b0852fdcccff0b0c73;i=8f2;b=ac646ad957764333be8689aeaf97c94c;m=15f735c11;t=5e8b4b844db39;x=c77cd0c7a90fde8b
> $ journalctl --version
> systemd 239 (239-51.el8)
> ```

Yeah, because `--show-cursor` shows the cursor in a slightly different format than `--cursor-file` does:

```
# journalctl --show-cursor -n0 -q
-- cursor: s=da95329bc1f24b57b88096c5cfd5f817;i=43e19;b=29ff46d21c384f50a7f5498a538e3807;m=3a44d32db64;t=5e8b4ca2883cb;x=6ff9182dcd3c4955
# cat /tmp/cursor 
s=da95329bc1f24b57b88096c5cfd5f817;i=43e0f;b=29ff46d21c384f50a7f5498a538e3807;m=3a41273ecdf;t=5e8b48f699545;x=7b86d0de23f57c13
```

so, yeah, with `--show-cursor` you need to do some post-processing. I was referring just to the `--cursor-file` stuff.

**Comment by elazarl** [comment]
@mrc0mmand as I said, for the `dmesg -C` use case, the `cursor-file` doesn't help, since you don't want to destroy the file each time you show history. Hence I had to post process, and hence, I'd rather just pipe it instead of using `--cursor-file` which is not widely available yet.

**Comment by poettering** [comment]
by "difference between lines" you mean *time* difference, I presume?

**Comment by elazarl** [comment]
@poettering , yes I apologize. Will edit to clarify.

**Comment by d4nuu8** [comment]
I already played a bit with the implementation of this. Do you think it makes more sense to use a `-d` argument, or use a output formatting option (something like `-o short-delta`)?

**Comment by elazarl** [comment]
@d4nuu8 hmm... I don't like the fact that the formatting don't just change the formatting, but also change the time source.

Then again, this is what happens regardless of the feature.

The other thing is, you might want a specific formatting regardless of the diff (not to mention the diff delta duration can use formatting as well). So we might want both.

And `-kd` should reject non-monotonic time that doesn't make sense.

**Comment by d4nuu8** [comment]
> I don't like the fact that the formatting don't just change the formatting, but also change the time source.

But that's how it works right now, as far as I know. The only way the get a monotonic clock is to use `-o short-monotonic`. Correct me if I'm wrong.

> And -kd should reject non-monotonic time that doesn't make sense.

This would mean the only possible command to use is something like `journalctl -kdo short-monotonic`.

**Comment by elazarl** [comment]
> >Then again, this is what happens regardless of the feature.

> But that's how it works right now, as far as I know.

Agreed. That's my understanding as well. I was just noting it's unfortunate IMHO.

> This would mean the only possible command to use is something like `journalctl -kdo short-monotonic`.

IMHO, running `journalctl -k` is counter productive, even without diff, as times would be extremly imprecise, and could confuse the user. It happened.

Moreover, the poor soul who tries `journalctl -k` often do that as a replacemen to `dmesg`, and he's surprised to discovered the times, and time order, do not match.

But it is what it is, and this is not the topic of this bug.

However, if the usr specifies `-kd`, it is most likely he wishes to infer things about the time differences between log lines.

With non-monotonic time he'll see utter nonesense.

We can decide allowing it, but at the very least we should make sure we warn the user about it.

IMHO, having `journalctl -kd` (or even just `-k`) imply `-o short-monotonic` is a very good default.

**Comment by mrc0mmand** [comment]
I think having `-o short-monotonic-diff` or something similar would be quite useful on its own and would have use cases even without using `-k` (I'd certainly make use of it when debugging systemd/udevd or tests, instead of using `-o short-monotonic` and counting the time diff between events manually).

Also, since the diff stuff makes sense with just `-o short-monotonic` (as far as I understand), having a separate option for it would be a bit wasteful.

**Comment by mrc0mmand** [comment]
With this logic you could also have `-o short-delta` to simulate `dmesg --show-delta --notime` as well, which would be useful outside of the `-k` scope too.

**Comment by elazarl** [comment]
@mrc0mmand totally agree it could be useful never the less.

I understand and accept your stance about having a different format option for diff, given the current state of affairs.

That being said, we can have `-d` as a simple shorthand to `-o short-delta` and having `-d -o short` be runtime error as conflicting options.

While we at it, `-o short-delta-ms` and `-o short-delta-usec` could be useful to fine tune resolution?
