### ISSUE TITLE
Building a statically linked systemd-detect-virt

### ISSUE THREAD

**Issue by gutjuri** [systemd/systemd#24640]
### systemd version the issue has been seen with

251

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.0-124-generic

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Hello,
I am trying to build a self-contained/statically linked executable of "systemd-detect-virt".

The commands
```
meson build
ninja -C build systemd-detect-virt
```
produce a dynamically linked version of "systemd-detect-virt".

I am unable to figure out how to configure meson to produce statically linked binaries. 
Is this already a solved problem? I.e. is there a method for building a static "systemd-detect-virt"? If not, os ot even possible in theory?

Thank you for you time.
Best regards
Juri

**Comment by yuwata** [comment]
We have meson option `link-systemctl-shared` or friends. Please try to implement `link-detect-virt-shared` or so.

**Comment by mrc0mmand** [comment]
> We have meson option `link-systemctl-shared` or friends. Please try to implement `link-detect-virt-shared` or so.

I'm not sure if that's going to be enough, since `link-xxx-shared` only affects linking against `libsystemd-shared`. If I understand the original report correctly, the reporter wants `systemd-detect-build` binary to be linked statically against all dependencies, not only `libsystemd-shared`.

**Comment by gutjuri** [comment]
> > We have meson option `link-systemctl-shared` or friends. Please try to implement `link-detect-virt-shared` or so.
> 
> I'm not sure if that's going to be enough, since `link-xxx-shared` only affects linking against `libsystemd-shared`. If I understand the original report correctly, the reporter wants `systemd-detect-build` binary to be linked statically against all dependencies, not only `libsystemd-shared`.

Yes, that is my goal.

**Comment by gutjuri** [comment]
I noticed the option "standalone binaries". I have added the following section to meson.build:

```
if have_standalone_binaries
        exe = executable(
                'systemd-detect-virt.standalone',
                'src/detect-virt/detect-virt.c',
                include_directories : includes,
                c_args : '-DSTANDALONE',
                link_with : [libshared_static,
                             libbasic,
                             libbasic_gcrypt,
                             libsystemd_static],
                dependencies : [libacl],
                install : true,
                install_dir : rootbindir)
        public_programs += exe
endif
```

And compiled with 

```
meson build -Dstandalone-binaries=true
ninja -C build systemd-detect-virt.standalone
```

This now gives me a binary that includes libsystemd. However, if I'm correct, it still depends on glibc and is thus unable to run on e.g. alpine. Is this correct? If yes, do you know how this can be achieved?

**Comment by bluca** [comment]
We don't really support this for anything. In fact static linking with glibc is a bit iffy. What is your use case?

**Comment by gutjuri** [comment]
> We don't really support this for anything. In fact static linking with glibc is a bit iffy. What is your use case?

I'd like to have a standalone binary of systemd-detect-virt that is able to run on a wide range of hosts (e.g. ubuntu hosts, centos hosts, alpine hosts). 

I will go ahead and try to link against musl instead of glibc (making static linking easier). However, as I've never worked with meson before, I have no idea how I can tell the system that I'd like static linking.

**Comment by bluca** [comment]
Why not just use the one shipped by each distro? I'm not sire we want to support this model where anyone ships random versions of any of these components, they are pretty much designed to work in concert, in general

**Comment by gutjuri** [comment]
> Why not just use the one shipped by each distro? I'm not sire we want to support this model where anyone ships random versions of any of these components, they are pretty much designed to work in concert, in general

I'm not sure if there is one for systemd... https://pkgs.alpinelinux.org/packages?name=*detect-virt&branch=v3.16&repo=&arch=&maintainer= 

Also, i'd like to run systemd-detect-virt on systems I am not root on, so I can't really use the package manager to install systemd-detect-virt.

**Comment by poettering** [comment]
Alpine is a distro that is openly anti-systemd. Maybe pick another distro if you want to use systemd stuff.

**Comment by mrc0mmand** [comment]
> > We don't really support this for anything. In fact static linking with glibc is a bit iffy. What is your use case?
> 
> I'd like to have a standalone binary of systemd-detect-virt that is able to run on a wide range of hosts (e.g. ubuntu hosts, centos hosts, alpine hosts).
> 
> I will go ahead and try to link against musl instead of glibc (making static linking easier). However, as I've never worked with meson before, I have no idea how I can tell the system that I'd like static linking.

I mean, for start you could add `c_args=-static` and `link_args=-static` to the section you added before, but that's not going to help, for example, on Fedora, since at least `libacl` doesn't ship its static library. So I'd go with Lennart's advice and pick a systemd-friendly distro if you're going to use systemd stuff on it anyway.

**Comment by gutjuri** [comment]
I see, thanks for your help.
Unfortunately, changing distros is not an option.

**Comment by bluca** [comment]
Just do an alpine specific build so it doesn't need to be static and use the distro packaged tools elsewhere?

**Comment by poettering** [comment]
> I see, thanks for your help.
> Unfortunately, changing distros is not an option.

I am sorry, you picked like the most systemd hostile distro there is, and want systemd stuff, this is the price you have to pay then I guess..

OpenEmbedded carries some messy patches to build systemd on musl. But you really are on your own there. 

You might enjoy this fudfest: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/33329

Anyway, I think we should just close this, I see no point in making systemd more accomodating for workarounds for the politics of Alpine.
