### ISSUE TITLE
tmpfiles: suppressing `uninitialized /etc` warnings on offline systems

### ISSUE THREAD

**Issue by dvdhrm** [systemd/systemd#24655]
We are running `systemd-tmpfiles` as part of `dnf install --root=...` on an offline system to bootstrap a distribution. We explicitly want to create the directory-tree with an empty `/etc` (or as empty as possible). Therefore, no machine-id is available. Unfortunately, this means `systemd-tmpfiles` will print a warning whenever encountering `%m` specifiers. In particular `/var/log/journal/%m` cannot be created:

```
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
```

Now this isn't really a problem, because tmpfiles will just ignore it and continue. However, we would like to avoid seeing the warning and have a clear path forward on how such setups are supported. I see several options:

1. We leave everything as it is but document that running `systemd-tmpfiles` on offline systems might skip some entries and print warnings.
2. We add an `--offline` switch to `tmpfiles` and make it suppress those warnings.
3. We add `--live` to `tmpfiles` and add annotations to tmpfile lines which are only meant to be executed on live systems.

The status quo works fine and as long as tmpfiles is executed during boot all the `%m` modifiers will be resolved correctly. However, I would like to be able to properly document how this warning message is to be interpreted in `osbuild`.

**Comment by poettering** [comment]
maybe just downgrade them to LOG_DEBUG if `--root=` is set? Keep them at LOG_WARNING if `--root=` is not set?

**Comment by dvdhrm** [comment]
> maybe just downgrade them to LOG_DEBUG if `--root=` is set? Keep them at LOG_WARNING if `--root=` is not set?

Unfortunately, the rpm-macros do not pass `--root`. They run in a chroot. We can make them pass `--root=/`, but that might confuse readers needlessly.

**Comment by dvdhrm** [comment]
Slightly related, the following commit likely broke the tmpfiles code:

```
commit 6ec4c852c910b1aca649e87ba3143841334f01fa
Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
Date:   Tue Mar 8 12:08:00 2022 +0100

    shared/specifier: provide proper error messages when specifiers fail to read files
```

It changes the specifier code to return `EUNATCH` instead of `ENOENT`, but `specifier_machine_id_safe()` in `tmpfiles.c` was not adjusted.

(CC @keszybz)

**Comment by dvdhrm** [comment]
> Slightly related, the following commit likely broke the tmpfiles code:
> 
> ```
> commit 6ec4c852c910b1aca649e87ba3143841334f01fa
> Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
> Date:   Tue Mar 8 12:08:00 2022 +0100
> 
>     shared/specifier: provide proper error messages when specifiers fail to read files
> ```
> 
> It changes the specifier code to return `EUNATCH` instead of `ENOENT`, but `specifier_machine_id_safe()` in `tmpfiles.c` was not adjusted.

Presumably fixed in:

    commit 6db980988fd31559828822180518613f0bdc29bf
    Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
    Date:   Mon Sep 26 14:22:49 2022 +0200

        tmpfiles: fix detection of unitialized-/etc
