### ISSUE TITLE
watchdog support doesn't support legacy watchdog interface /dev/watchdog anymore, but ipmi_watchdog driver only supports that

### ISSUE THREAD

**Issue by ctheune** [systemd/systemd#24661]
### systemd version the issue has been seen with

250.4

### Used distribution

NixOS

### Linux kernel version used

5.15.67

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

I configured the explicit device:

```
[root@wendy00:/etc/nixos]# grep "WatchdogDevice" /etc/systemd/system.conf
WatchdogDevice=/dev/watchdog
```

However, system keeps trying /dev/watchdog0:

```
Sep 13 19:35:44 wendy00 systemd[1]: Failed to open watchdog device /dev/watchdog0, ignoring: No such file or directory
```

When symlinking /dev/watchdog0 to /dev/watchdog (this is an IPMI watchdog) it picks up the device properly.

However, I'm also confused because the documented option is not visible in any "show" inquiries:

```
[root@wendy00:/etc/nixos]# systemctl show --property=WatchdogDevice

[root@wendy00:/etc/nixos]# echo $?
0
```

I haven't found any other errors that would indicate me misspelling the property name.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 13 19:35:44 wendy00 systemd[1]: Failed to open watchdog device /dev/watchdog0, ignoring: No such file or directory
```

**Comment by yuwata** [comment]
Fix is waiting #24664.

**Comment by bluca** [comment]
@ctheune do you have some custom kernel patches or kconfig? AFAIK /dev/watchdog0 should be available since kernel 3.5, why is it not there on your system?

**Comment by jcpunk** [comment]
I'm seeing the same thing on CentOS Stream9.  I'm not sure why I don't have a `/dev/watchdog0`, but my IPMI device is showing up as `/dev/watchdog`.

**Comment by yuwata** [comment]
@ctheune and @jcpunk Could you provide more details about the watchdog device? E.g. wdctl for the device.

**Comment by jcpunk** [comment]
```shell
[root@hostname ~]# ls -l /dev/watch*
crw-------. 1 root root 10, 130 Sep 13 15:58 /dev/watchdog
[root@hostname ~]# wdctl /dev/watchdog 
Device:        /dev/watchdog
Identity:      IPMI [version 1]
Timeout:       300 seconds
Pre-timeout:    0 seconds
[root@hostname ~]# rpm -q  systemd
systemd-250-11.el9.x86_64
```

**Comment by yuwata** [comment]
Thanks. Could you also provide `udevadm info --name=watchdog` or `udevadm info /dev/watchdog`?

**Comment by jcpunk** [comment]
```shell
[root@hostname ~]# udevadm info --name=watchdog
P: /devices/virtual/misc/watchdog
N: watchdog
L: 0
E: DEVPATH=/devices/virtual/misc/watchdog
E: DEVNAME=/dev/watchdog
E: MAJOR=10
E: MINOR=130
E: SUBSYSTEM=misc

[root@hostname ~]# udevadm info /dev/watchdog
P: /devices/virtual/misc/watchdog
N: watchdog
L: 0
E: DEVPATH=/devices/virtual/misc/watchdog
E: DEVNAME=/dev/watchdog
E: MAJOR=10
E: MINOR=130
E: SUBSYSTEM=misc
```

**Comment by yuwata** [comment]
Thank you.

**Comment by poettering** [comment]
/dev/watchdog is a legacy interface, /dev/watchdog0 is how the first watchdog device is called.

It appears you are using a really old kernel or old/broken driver?

**Comment by yuwata** [comment]
Hm, looking at kernel source, most(?) watchdog driver registers their watchdog devices through `watchdog_register_device()` in drivers/watchdog/watchdog_core.c, but ipmi_watchdog does not. It seems ipmi_watchdog be a legacy watchdog device.

**Comment by poettering** [comment]
hmpf, is ipmi_watchdog still maintained? is this some legacy driver that's on the chopping block? Replaced by something else? Anyone knows the backstory of this?

iirc the watchdog subsystem was added to the linux kernel 10y ago or so, and the drivers converted. Why was the ipmi stuff not covered?

**Comment by yuwata** [comment]
I do not know the history, but the source code of ipmi_watchdog driver is located in drivers/char/ipmi/ipmi_watchdog.c, while other watchdog drivers are in drivers/watchdog.

**Comment by yuwata** [comment]
> ipmi_watchdog still maintained?

Not sure, but the last commit for ipmi_watchdog.c is `Tue Apr 12 15:49:47 2022 -0500`. Seems not outdated.

**Comment by jcpunk** [comment]
I can't speak to the conversion, but the IPMI spec itself requires a watchdog so having it along side the IPMI drivers makes sense to me.

**Comment by ctheune** [comment]
Thanks for fixing - I have no idea why the ipmi driver maintenance was stuck. I'd be happy to finance the conversion if I get in touch with the maintainers, though.

**Comment by ctheune** [comment]
It seems like @cminyard is the maintainer here. I'll try to get in touch.

**Comment by ctheune** [comment]
I was in touch with @cminyard and he allowed me to post his response about the situation that the IPMI watchdog isn't using the new interface. For posterity:

> Yeah, this has been a long-standing issue.  The IPMI watchdog driver has
> a lot of capabilities not in the main watchdog interface, and it
> predates the main watchdog interface by years.  So it was never moved
> over.  I'm not going to get the capabilities added to the main watchdog
> interface, and it's against the kernel rules to drop functionality.
>
> So I'm kind of stuck.  Funding is not really the issue.

**Comment by henning-schild** [comment]
I am not coming across this as well. Supermicro servers with two watchdogs ... in theory. In practice iTCO has been made to not work forcing people to use ipmi. And IPMI is that horribly outdated driver which does not auto-load and uses that legacy interface. That is all not very nice.

In the kernel the fact that it does not auto-load could in fact be a chance to write a modern version with less features that would auto-load and be mutually exclusive to "ipmi_watchdog". Effectively adding a second driver which will win and be more modern with possibly less features that hardly anyone uses. And one would not need to remove functionality, people who prefer that old driver could manually load it and blacklist the modern one while they are writing special config files for their machine.

So now about systemd ... it just has to support both the new and that legacy interface it seems. Maybe not nice, but there is at least still one legacy driver in any modern kernel, and IPMI is likely to be the only thing you can ever get working in a server.

I am on debian11 with systemd 250 and despite 

```
# cat /etc/systemd/system.conf.d/99-wd.conf 
[Manager]
RuntimeWatchdogSec=60s
ShutdownWatchdogSec=60s
WatchdogDevice=/dev/watchdog
```

```
# cat /proc/cmdline 
root=/dev/nvme0n1p4 rootwait rw console=ttyS0,115200 console=tty0 default_hugepagesz=1G hugepagesz=1G hugepages=10 intel_iommu=on iommu=pt vt.handoff=7 earlyprintk debug systemd.watchdog-device=/dev/watchdog modules_load=ipmi_watchdog
```

i am seeing

```
systemd[1]: Failed to open watchdog device /dev/watchdog0, ignoring: No such file or directory
```

and will have to use watchdogd because systemd does not work

From what i read that has been fixed, but there are non rolling distros out there that might be slow on updating things. Maybe again a server-world thing ;)
