### ISSUE TITLE
Hardware Watchdog information

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#24665]
### Component

systemd

### Is your feature request related to a problem? Please describe

When setting up a hardware watchdog, it would be helpful if there was some way I could ask systemd if the watchdog was configured and any applicable settings.

Because systemd has the `/dev` node open, `wdctl` can't get information about it.

### Describe the solution you'd like

Output similar to what `wdctl` provides from one of the existing tools would be great.  Exposure over dbus might also be nice.

**Comment by yuwata** [comment]
Waiting in #24666. If possible, could you test the PR?
