### ISSUE TITLE
Change the storage folder

### ISSUE THREAD

**Issue by GuilhemROLLAND** [systemd/systemd#24678]
### Component

systemd-coredump

### Is your feature request related to a problem? Please describe

On my system /var/lib/systemd/coredump is a volatile memory, so I lost my coredumps on reboot... 

### Describe the solution you'd like

I'd like to set the storage folder on a persistent memory such as a usb stick mapped at /persist.  
Hope I can do that using a .conf file.

### Describe alternatives you've considered

I edited the kernel.core_pattern, but this implies to no longer used systemd-coredump and that's not what I want.

**Comment by bluca** [comment]
Just symlink it in your image or bind-mount it early at boot?

**Comment by mrc0mmand** [comment]
Also see https://github.com/systemd/systemd/issues/16177 and https://github.com/systemd/systemd/pull/16078.

**Comment by GuilhemROLLAND** [comment]
> Just symlink it in your image or bind-mount it early at boot?

Thanks, I'll do that !

**Comment by GuilhemROLLAND** [comment]
It seems that systemd-coredump doesn't want to follow my symLink...  
ln -s /persist/coredump /var/lib/systemd/coredump --> Everything ok, work with touch.  
But no coredump file are created and journalctl give me :  
```bash
Sep 16 09:47:26 cygal-devbox systemd[79897]: systemd-coredump@11-79896-0.service: Failed to set up special execution directory in /var/lib: Not a directory
Sep 16 09:47:26 cygal-devbox systemd[79897]: systemd-coredump@11-79896-0.service: Failed at step STATE_DIRECTORY spawning /lib/systemd/systemd-coredump: Not a directory
Sep 16 09:47:26 cygal-devbox systemd[1]: systemd-coredump@11-79896-0.service: Deactivated successfully.
```

**Comment by mrc0mmand** [comment]
Yeah, symlinks won't work in this case, you need to use bind mounts (`mount --bind /persist/coredump /var/lib/systemd/coredump`).

**Comment by poettering** [comment]
systemd-coredump runs heavily sandboxed, and doesn't allow a symlink pointing outside the sandbox. You must use a bind mount (or turn off the sandbox)
