### ISSUE TITLE
`reboot -f` behaves like `--force` is specified twice.

### ISSUE THREAD

**Issue by ppppn** [systemd/systemd#24696]
### systemd version the issue has been seen with

239

### Used distribution

RHEL 8

### Linux kernel version used

4.18.0-372.26.1.el8_6.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

According to the document https://www.freedesktop.org/software/systemd/man/systemctl.html#reboot

>If combined with --force, shutdown of all running services is skipped, however all processes are killed and all file systems are unmounted or mounted read-only, immediately followed by the reboot. If --force is specified twice, the operation is immediately executed without terminating any processes or unmounting any file systems. This may result in data loss. Note that when --force is specified twice the reboot operation is executed by systemctl itself, and the system manager is not contacted. This means the command should succeed even when the system manager has crashed.

`reboot -f` unmounts or mounts read-only all the file systems before rebooting. And if `--force` is specified twice, the system is rebooted without unmounting file systems.

### Unexpected behaviour you saw

`reboot -f` doesn't unmount filesystems. It behaves like two `-ff` is specified.

I found this behaviour on RHEL 8, however, I believe that the issue isn't fixed even in the upstream.

Related codes are:
https://github.com/systemd/systemd/blob/main/src/systemctl/systemctl.c#L977
```
        } else if (invoked_as(argv, "reboot")) {
                if (kexec_loaded())
                        arg_action = ACTION_KEXEC;
                else
                        arg_action = ACTION_REBOOT;
                return halt_parse_argv(argc, argv);
```

https://github.com/systemd/systemd/blob/main/src/systemctl/systemctl-compat-halt.c#L103
```
                case 'f':
                        arg_force = 2;
                        break;
```

The `arg_force` counts how many `-f`s are specified, doesn't it?

I also found a related issue: https://github.com/systemd/systemd/pull/22518 .

### Steps to reproduce the problem

1. run `reboot -f`

```
$ sudo reboot -f
Rebooting.
```

2. check `dmesg`
After rebooting, I could found logs like below:
```
$ dmesg | grep XFS
[    4.368841] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    4.378674] XFS (xvda2): Mounting V5 Filesystem
[    4.470428] XFS (xvda2): Starting recovery (logdev: internal)
[    4.501210] XFS (xvda2): Ending recovery (logdev: internal)
```

These means that the file system isn't cleanly unmounted.

### Additional program output to the terminal or log subsystem illustrating the issue
Again after rebooting with `-f`, I could found logs like below:
```sh
$ dmesg | grep XFS
[    4.368841] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    4.378674] XFS (xvda2): Mounting V5 Filesystem
[    4.470428] XFS (xvda2): Starting recovery (logdev: internal)
[    4.501210] XFS (xvda2): Ending recovery (logdev: internal)
```

You can also see the issue by checking whether `umount2` system call is called or not:

1. `reboot`
```
$ sudo auditctl -a always,exit -S umount2
$ sudo reboot
...
$ sudo grep umount2 /var/log/audit/audit.log
type=SYSCALL msg=audit(1663338939.938:106): arch=c000003e syscall=166 success=yes exit=0 a0=557b6e8e0d10 a1=8 a2=1 a3=0 items=1 ppid=1 pid=1421 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(y-helper)" exe="/usr/lib/systemd/systemd" subj=system_u:system_r:init_t:s0 key=(null)ARCH=x86_64 SYSCALL=umount2 AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=SYSCALL msg=audit(1663338940.047:112): arch=c000003e syscall=166 success=yes exit=0 a0=7fff2f4abf60 a1=2 a2=16a90 a3=1 items=1 ppid=1 pid=1438 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-user-ru" exe="/usr/lib/systemd/systemd-user-runtime-dir" subj=system_u:system_r:systemd_logind_t:s0 key=(null)ARCH=x86_64 SYSCALL=umount2 AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
```
-> `umount2` is called.

2. `reboot -f`:
```
$ sudo auditctl -a always,exit -S umount2
$ sudo reboot -f
...
$ sudo grep umount2 /var/log/audit/audit.log; echo $?
1
```
-> `umount2` isn't called.

**Comment by ppppn** [comment]
I found a similar issue: https://github.com/systemd/systemd/issues/8909 (The `Bug 1`)

**Comment by yuwata** [comment]
(The reported version is too old, but the behavior is not changed.)

Though, if we change that, to follow the behavior described by 5d9adb5b60b815b477ba9e6b19ef0fd7e1854a38, we break backward compatibility.

@poettering @keszybz WDYT?

**Comment by yuwata** [comment]
Maybe, better to explain in the man page?

**Comment by mrc0mmand** [comment]
As Yu said, `systemctl reboot` follows what's described in the man page (i.e. it differentiates between `-f` and `-ff` https://github.com/systemd/systemd/blob/43deb1a8dce012c67a1285f7ef1bd40d971a4730/src/systemctl/systemctl.c#L688-L691), but the compat binary `reboot` doesn't do that for... compatibility reasons - SysV reboot understood only one `-f` - without it it would call `shutdown -r`, which would shut down the system in a safe manner; with `-f` it would call the `reboot()` syscall directly, basically doing what `systemctl reboot -ff` does. So I guess tweaking the man page would make sense in this case.

**Comment by ppppn** [comment]
Thank you for your checking it and I'm sorry for my confusing original title: "`systemctl reboot -f` behaves like `--force` is specified twice."

`systemctl reboot -f` seems to cleanly unmount filesystems:
```
$ sudo systemctl reboot -f
...
$ dmesg | grep XFS
[    3.607870] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    3.616504] XFS (xvda2): Mounting V5 Filesystem
[    3.652626] XFS (xvda2): Ending clean mount
```

I edited the title to "reboot -f behaves like --force is specified twice."

**Comment by yuwata** [comment]
Documentation update is waiting in #24698.
