### ISSUE TITLE
nspawn container traffic not tagged via net_cls.classid 

### ISSUE THREAD

**Issue by thechile** [systemd/systemd#2470]
Hi

I am trying to use the `net_cls.classid` feature with tc to apply bandwidth limits to a container and then  hopefully netem latency/pkt loss etc.. for testing. But following the tests below i can't get traffic originating from within the container to be tagged.

I don't know if this is systemd related or a kernel bug. Any help appreciated.

First i setup some tc rules

```
tc qdisc del dev enp0s3 root
tc qdisc add dev enp0s3 root handle 10: htb default 30
tc class add dev enp0s3 parent 10: classid 10:1 htb rate 1Mbit burst 2k
tc filter add dev enp0s3 protocol all parent 10: prio 10 handle 1: cgroup
```

Create new cgroup for net_cls to test

```
mkdir /sys/fs/cgroup/net_cls/clstest
/bin/echo 0x00100001 > /sys/fs/cgroup/net_cls/clstest/net_cls.classid
```

Add current shell pid to group tasks list, and launch a container then create some traffic

```
echo $$ > /sys/fs/cgroup/net_cls/clstest/tasks
systemd-nspawn -D ~/debian-tree/
ping -c 5 8.8.8.8
```

Now i'd expect container traffic to show, but it's empty.

```
tc -s -d class show dev enp0s3
```

However if from the shell i repeat the same ping or launch Firefox to generate traffic then it is reflected in the tc class stat's. So it seems that traffic within the container is somehow not having it's socket `sock->sk->sk_classid` updated with the configured cgroup classid.

Here is some info on what i'm testing with.

```
Ubuntu 15.10
4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
systemd 225
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

Thank you

**Comment by thechile** [comment]
i think this is due to the network namespace, so the skb marks are relevant only within the containers associated namespace.

There was some more info on this here http://lists.linuxfoundation.org/pipermail/containers/2014-January/033848.html which i think would have restored the classid as the traffic translated from one namespace to another but it was never accepted into kernel.

**Comment by ohsix** [comment]
ah that sucks, thanks for tracking it down

**Comment by poettering** [comment]
Closing, since this is not an issue in systemd.
