### ISSUE TITLE
systemd-stub fails to handover to linux on x86_64 if UEFI loads systemd-stub above 4 GB

### ISSUE THREAD

**Issue by gentoo-root** [systemd/systemd#24707]
### systemd version the issue has been seen with

251.4

### Used distribution

Arch linux

### Linux kernel version used

5.19.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub

### Expected behaviour you didn't see

Linux should boot on System76 Lemur Pro (lemp11) using systemd-stub.

### Unexpected behaviour you saw

UEFI on System76 Lemur Pro (lemp11) loads systemd-stub at some address higher than 4 GB:

```
systemd-stub@0x47BAE1000,0x47BAF0000
```

systemd-stub uses a legacy x86-specific procedure to handover to linux: https://github.com/systemd/systemd/blob/cb19517490104553907bb0b118cd2005d6e379cc/src/boot/efi/linux_x86.c#L110-L120

The problem is that this code jumps to a 32-bit address, while the kernel is loaded at a 64-bit address. For example, on my laptop `linux_buffer == 0x47CADD000` (bigger than 4 GB), but `start == 0x7CAE1200` (should be `0x47CAE1200`), because it was converted to a 32-bit value at: https://github.com/systemd/systemd/blob/cb19517490104553907bb0b118cd2005d6e379cc/src/boot/efi/linux_x86.c#L166

This leads either to a hang or an immediate shutdown.

I don't see a simple solution to this if the legacy boot protocol of linux requires the kernel to be located below 4 GB, but UEFI loads the whole stub above 4 GB. At least the conversion to 32-bit should fail gracefully, instead of jumping to some random address.

Besides, replacing linux_x86.c with linux.c (which jumps to the EFI/PE entry point) works perfectly, so the solution can be make linux.c the default and linux_x86.c optional for those who run old kernels (build two stubs and put the legacy one under a different name?). linux.c should work with all hardware, but only with new kernels, and linux_x86.c supports old and new kernels, but fails on some modern hardware, so it's reasonable to switch to the one that works with new kernels and doesn't fail on modern hardware. Alternatively, linux_x86.c can detect that it's loaded above 4 GB and fallback to linux.c in those cases, handling errors gracefully.

### Steps to reproduce the problem

1. Buy a System76 Lemur Pro :P (I believe it can also be reproduced by running https://github.com/system76/firmware-open/ in qemu with enough RAM, but I didn't test it in qemu.)
2. Prepare the stub:
```
objcopy \
    --add-section .osrel=/etc/os-release --change-section-vma .osrel=0x20000 \
    --add-section .cmdline=/etc/kernel/cmdline --change-section-vma .cmdline=0x30000 \
    --add-section .linux=/boot/vmlinuz-linux --change-section-vma .linux=0x1000000 \
    /usr/lib/systemd/boot/efi/linuxx64.efi.stub \
    /efi/EFI/Linux/stub.efi
efibootmgr -c -l /EFI/Linux/stub.efi -L test -d /dev/nvme0n1
```
3. Reboot, make sure to select "test" in the UEFI boot menu.

**Comment by medhefgo** [comment]
Does https://github.com/medhefgo/systemd/tree/stub-x86 fix it? I really need to rework this whole x86 boot protocol code…

**Comment by nvmmax** [comment]
> Does https://github.com/medhefgo/systemd/tree/stub-x86 fix it?

Yes, it works, thanks.

Does that basically mean that boot_params->hdr.code32_start is not used by linux and can be left unfilled? I was misled by thinking we need to put the valid address there...

**Comment by medhefgo** [comment]
We use the efi handover protocol on x86, and the way I read the doc is that we only need to pass the cmdline and initrd params that way.

**Comment by medhefgo** [comment]
Yes, if your initrd happens to live above 4G, the stub shouldn't have worked without `LINUX_INITRD_MEDIA_GUID` support, which any modern kernel has.

I updated my branch so that it should correctly handle 4G boot (3rd commit). It would be great if you could try this. Even better would be if you could remove the `initrd_register/initrd_unregister` calls to ensure boot still works without those.

And I would love it if you could also try just the first two commits applied and the initrd calls removed. Hopefully, the initrd will be above 4G and boot would break again. You can add some log calls in all these tries to double check if you want (use `%lx` if you do).

**Comment by medhefgo** [comment]
> Shouldn't it be `FLAGS_SET` without a negation?

Wups. At least the above 4G detection on unsupported kernels works then. :D

> I also think that the initrd boundary checks are not enough (what if it starts below 4 GB, is smaller than 4 GB, but ends above 4 GB?):

I initially did that and then for some reason discarded that. It should be be correct now. Thankfully the payloads are already in memory, so I don't have to care about overflow checks (EFI_PHYSICAL_ADDRESS is always 64bits).

This should hopefully work for you now (and again please check without initrd calls to make sure).
