### ISSUE TITLE
network-online.target seems to fire prematurely

### ISSUE THREAD

**Issue by hazzl** [systemd/systemd#24723]
### systemd version the issue has been seen with

251.4

### Used distribution

Archlinux

### Linux kernel version used

5.19.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd-wait-online

### Expected behaviour you didn't see

I'm trying to mount a cifs filesystem on boot from `/etc/fstab`. The autogenerated mount unit properly includes an `After=network-online.target` stanza. Therefore the filesystem should be automatically mounted during boot.

### Unexpected behaviour you saw

Mounting fails about 70% of the time with `mount error(101): Network is unreachable`

### Steps to reproduce the problem

I have the following line in `/etc/fstab`:

`//leporello/Daten/Musik /mnt/media      cifs    rw,domain=KOALANETZ,username=XXX,password=YYY`

On boot the mount fails more often than not :-(

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
× mnt-media.mount - /mnt/media
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: exit-code) since Sun 2022-09-18 08:11:17 CEST; 20min ago
      Where: /mnt/media
       What: //leporello/Daten/Musik
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
        CPU: 12ms

Sep 18 08:11:17 mozart systemd[1]: Mounting /mnt/media...
Sep 18 08:11:17 mozart mount[315]: mount error(101): Network is unreachable
Sep 18 08:11:17 mozart mount[315]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Sep 18 08:11:17 mozart systemd[1]: mnt-media.mount: Mount process exited, code=exited, status=32/n/a
Sep 18 08:11:17 mozart systemd[1]: mnt-media.mount: Failed with result 'exit-code'.
Sep 18 08:11:17 mozart systemd[1]: Failed to mount /mnt/media.
```

**Comment by hazzl** [comment]
It might help to have the ability to retry network mounts as suggested in #23186

**Comment by poettering** [comment]
Which network managing solution to you use? networkd? networkmanager?

Note that network-online.target is to be filled with meaning via "systemctl enable systemd-network-wait-online.service" or "systemctl enable NetworkManager-wait-online.target".

See this: https://systemd.io/NETWORK_ONLINE

**Comment by hazzl** [comment]
I'm using systemd-networkd as network manager and I had already enabled Network-Manager-wait-online.target

**Comment by yuwata** [comment]
No no, you need to enable systemd-networkd-wait-online.service. Network-Manager-wait-online.service is for NetworkManager.

Also, in most cases, arguments for systemd-networkd-wait-online command in the service need to be adjusted, as the meaning of 'online' is case-by-case.

Moreover, you may also need to pull nss-lookup.target for the mount, to resolve the server name.
