### ISSUE TITLE
Rotation matrix not working on new Medion Akoya E3224

### ISSUE THREAD

**Issue by Tuxman2** [systemd/systemd#24727]
### systemd version the issue has been seen with

251.4

### Used distribution

Manjaro 22.0 Gnome edition

### Linux kernel version used

5.19.7

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Rotation matrix not working.

### Unexpected behaviour you saw

No rotation on convertible laptop.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
I see these messages with the dmesg command:
 
$ sudo dmesg

kxcjk1013 i2c-KIOX010A:00: mounting matrix not found: using identity...
kxcjk1013 i2c-KIOX010A:00: supply vdd not found, using dummy regulator
kxcjk1013 i2c-KIOX010A:00: supply vddio not found, using dummy regulator
```

**Comment by Tuxman2** [comment]
If you need more information, tell me. 

Thanks.

**Comment by Tuxman2** [comment]
Hi,

the accelerometer matrix configuration in iio-sensor-proxy is good for Medion Akoya E3224 (Medion Akoya Exxxx serie).

The screen rotation didn't work on my device. The problem didn't came from iio-sensor-proxy but from Mutter of Gnome. I switched to a version of Mutter who support automatic screen rotation (AUR repository) and now it works. So, I will close this subject.

**Comment by MadhiasM** [comment]
I seem to face the same issue on Teclast F6 Pro using same Kionix Accelerometers which are correctly defined in 60-sensor.hwdb my device

![grafik](https://github.com/user-attachments/assets/f4cb7708-7692-4365-83b0-23579cb72404)

Which exact version of Mutter did you switch to? Is there any instruction available on how to do this?
