### ISSUE TITLE
Brightness keys F11 and F12 stopped working

### ISSUE THREAD

**Issue by D-EVE-R** [systemd/systemd#24733]
I ran the powertop --calibrate command and the screen suddenly went black, I thought my computer had crashed so I forced shutdown by holding the power button.
I powered back then I noticed that the F11 and F12 keys stopped working.
Fn + F11/F12 do work.

**Comment by yuwata** [comment]
Not sure, I guess the machine has a Fn-lock key. Just try to hit it.
Anyway this is not related to systemd. Closing.
