### ISSUE TITLE
systemd-cryptsetup with FIDO2 asks for recovery key first

### ISSUE THREAD

**Issue by rogueai** [systemd/systemd#24760]
### systemd version the issue has been seen with

251

### Used distribution

Arch

### Linux kernel version used

5.19.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Unlocking the luks volume should ask for FIDO2 authentication first, instead of recovery key.

### Unexpected behaviour you saw

I'm not sure this is actually a bug, apologies if this is some misconfiguration on my side, but if that's the case I can't figure out what went wrong with my setup.

I've setup luks volume unlocking with FIDO2 along with recovery key using sd-cryptenroll:
```
systemd-cryptenroll --fido2-device=auto /dev/my-luks-device
```
Slots are configured as following:
```
SLOT TYPE    
   1 recovery
   3 fido2
```
Everything works fine, but in a weird way: on boot I get asked for the recovery key first, then I hit enter a couple of times, basically failing the recovery key, and only then I get prompted for fido2 with user presence.

I thought it was something to do with the slot order, although the man page doesn't mention anything about that. I've actually setup TPM2 unlocking before trying FIDO, and even if TPM was set to slot 2 I was never asked for recovery key first, so this might not be the issue here.

**Comment by poettering** [comment]
How does your crypttab line look like?

**Comment by rogueai** [comment]
Ok I admit I feel a bit stupid right now, I had wiped the tpm2 slot, but left the options in my kernel cmdline:
```
rd.luks.options=tpm2-device=auto,fido2-device=auto
```
I removed the extra tpm2-device option and now it works as expected.
