### ISSUE TITLE
the size of journal files is random

### ISSUE THREAD

**Issue by wangcancan1996** [systemd/systemd#24761]
### systemd version the issue has been seen with

237

### Used distribution

Ubuntu

### Linux kernel version used

5.0.0-1032

### Expected behaviour you didn't see

the journal configuration is as follows:
[Journal]
Storage=persistent
SystemMaxUse=80G
SystemMaxFileSize=1G
SystemMaxFiles=2000
RuntimeMaxFileSize=1G
MaxRetentionSec=1month
MaxFileSec=1month

expect every journal file size being 1G.

### Unexpected behaviour you saw

the size of journal files various, seems being random.

root@itpv18096000021:/# ls -lh  /var/log/journal/35a737cde3b0421290e6add570c9b40f/
total 70G
-rw-r-----+ 1 root systemd-journal 416M Sep 20 08:48 system.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 16:46 system@bb4b0a80b7a64e5891da201b26b2f291-00000001575947b3-0005e8e13630d911.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 18:02 system@bb4b0a80b7a64e5891da201b26b2f291-00000001576d36b4-0005e8e239cadb9a.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 19:17 system@bb4b0a80b7a64e5891da201b26b2f291-000000015780e489-0005e8e349929f17.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 20:31 system@bb4b0a80b7a64e5891da201b26b2f291-000000015794a8f6-0005e8e453868d57.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 21:47 system@bb4b0a80b7a64e5891da201b26b2f291-0000000157a8731f-0005e8e55e11c830.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 17 23:16 system@bb4b0a80b7a64e5891da201b26b2f291-0000000157bc086d-0005e8e66dc45084.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 00:55 system@bb4b0a80b7a64e5891da201b26b2f291-0000000157cff824-0005e8e7acab3875.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 02:16 system@bb4b0a80b7a64e5891da201b26b2f291-0000000157e37e9d-0005e8e90b7307f3.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 03:22 system@bb4b0a80b7a64e5891da201b26b2f291-0000000157f74b7c-0005e8ea302de991.journal
-rw-r-----+ 1 root systemd-journal 184M Sep 18 03:31 system@bb4b0a80b7a64e5891da201b26b2f291-00000001580b1953-0005e8eb1a54e48b.journal
-rw-r-----+ 1 root systemd-journal  88M Sep 18 03:35 system@bb4b0a80b7a64e5891da201b26b2f291-00000001580e3494-0005e8eb3c855f2b.journal
-rw-r-----+ 1 root systemd-journal 256M Sep 18 03:53 system@bb4b0a80b7a64e5891da201b26b2f291-00000001580f3f6d-0005e8eb48c15157.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 05:09 system@bb4b0a80b7a64e5891da201b26b2f291-00000001581382c1-0005e8eb895ceb72.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 06:26 system@bb4b0a80b7a64e5891da201b26b2f291-000000015826eeae-0005e8ec98ec48df.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 18 07:43 system@bb4b0a80b7a64e5891da201b26b2f291-00000001583a69fe-0005e8edacab3e67.journal
-rw-r-----+ 1 root systemd-journal 152M Sep 18 07:51 system@bb4b0a80b7a64e5891da201b26b2f291-00000001584de274-0005e8eebfe14fd2.journal
-rw-r-----+ 1 root systemd-journal  40M Sep 18 07:52 system@bb4b0a80b7a64e5891da201b26b2f291-0000000158503024-0005e8eede5144c4.journal
-rw-r-----+ 1 root systemd-journal  40M Sep 18 07:52 system@bb4b0a80b7a64e5891da201b26b2f291-0000000158504b46-0005e8eedfa57e38.journal
......
-rw-r-----+ 1 root systemd-journal 152M Sep 20 06:37 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba02452-0005e915ed3fb394.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:37 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba28f16-0005e9160fd576f0.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:37 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba28f18-0005e9160fd9527d.journal
-rw-r-----+ 1 root systemd-journal  48M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba28f20-0005e9160fdac6db.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba2ecf2-0005e91613338e4d.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba2ecf4-0005e9161334e444.journal
-rw-r-----+ 1 root systemd-journal  40M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba2ecfc-0005e916133822fc.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba306eb-0005e91613b4658f.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba306ed-0005e91613b5da00.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba306f5-0005e91613b8ca90.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba30e36-0005e916142d21a0.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba30e38-0005e916142e408a.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba30e40-0005e91614316ef5.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba31d39-0005e91614a1be4a.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:38 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba31d3b-0005e91614a2f16a.journal
-rw-r-----+ 1 root systemd-journal  80M Sep 20 06:40 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba31d43-0005e91614a5cf00.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:40 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba408f6-0005e9161b08fc6a.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 20 06:40 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba408f8-0005e9161b0a0277.journal
-rw-r-----+ 1 root systemd-journal 1.0G Sep 20 08:10 system@bb4b0a80b7a64e5891da201b26b2f291-000000015ba40900-0005e9161b0eebd2.journal
-rw-r-----+ 1 root systemd-journal  32M Sep 19 11:46 user-1000.journal

There are total 440 journal files.
root@itpv18096000021:/# ls -lh  /var/log/journal/35a737cde3b0421290e6add570c9b40f/ | wc -l
440

### Steps to reproduce the problem

1. create /etc/systemd/journald.conf.d/logretention.conf file, and set configuration as follows:
[Journal]
Storage=persistent
SystemMaxUse=80G
SystemMaxFileSize=1G
SystemMaxFiles=200

2. restart systemd-journald

**Comment by poettering** [comment]
there are various reasons why we rotate (i.e. start a new jounral file, closing the old), size is only one of them.

We'll do this when:

1. size limit is hit
2. quota is hit
3. we start up and find an uncleanly closed file from the previous boot
4. when CLOCK_REALTIME changes (and thus time would no longer be monotonic in the journal file)
5. hash tables in the journal file see too many collisions
6. IO error


and a couple of other cases. Usually you should fine an explanation in the log files that say why we rotated.
