### ISSUE TITLE
/run/udev/control not unlinked on stop, breaking udev_queue_get_udev_is_active API

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2477]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794721

The udev_queue_get_udev_is_active() API call of libudev is used by
things like device-mapper to determine if it should wait for udev to settle
after doing various operations. The catch is that this API call only checks
whether or not the file /run/udev/control exists.

Up until udev 221-1, this file was removed by udev on shutdown. Starting
with 221-1 the file is left behind causing libudev to falsely report to
device-mapper that udev is running which causes device-mapper to hang
indefinitely for a notification that will never arrive.

This causes an indefinite hang during system halt/reboot because udev is
killed off right away by sendsigs long before cryptsetup/dmsetup runs to
close the device-mapper filesystems. The only way to recover is to
physically power cycle the system.

This regression was introduced in commit:
693d371 udevd: move main-loop to sd-event
and affects udev when being run under non-systemd systems.

**Comment by mbiebl** [comment]
@teg could you have a look? I think this regression was an unintended side-effect of your rework

**Comment by evverx** [comment]
This regression was introduced in commit:
f59118ec791173

> udevd: unify fd handling in forking/notify modes
> 
>   Hide the differenec in listen_fds, by simply opening the fds
>     here in case they are not passed in.

The first [`udev_ctrl_enable_receiving`](https://github.com/systemd/systemd/pull/43/commits/f59118ec7911730bb79b273bb4034f5eb4c80868#diff-67a7a6fb13bf7e5adfe383aed8a05ebeR1305) sets `uctrl->cleanup_socket` to `true`. But we destroy that `uctrl`.

We recreate a `ctrl` form the `fd_ctrl`
https://github.com/systemd/systemd/pull/43/commits/f59118ec7911730bb79b273bb4034f5eb4c80868#diff-67a7a6fb13bf7e5adfe383aed8a05ebeR1526

```
manager->ctrl = udev_ctrl_new_from_fd(manager->udev, fd_ctrl)
```

But `uctrl->cleanup_socket` is `false`. So, we never remove the `/run/udev/control`

**Comment by msekletar** [comment]
I think that previous behavior breaks socket activation. If you remove socket from the filesystem systemd will not notice that and it leaves socket unit in listening state. Then no client is able to connect and socket activate udev daemon until socket unit is manually restarted.

**Comment by evverx** [comment]
Well, there were two cases:

``` diff
         r = listen_fds(&fd_ctrl, &fd_uevent);
-        if (r >= 0) {
-                /* get control and netlink socket from systemd */
                 This branch doesn't set uctrl->cleanup_socket to true

...
-        } else {
-                /* open control and netlink socket */
-                manager->ctrl = udev_ctrl_new(manager->udev);
                 This branch sets uctrl->cleanup_socket to true
...
        }
```

So,

```
systemctl start systemd-udevd
systemctl stop systemd-udevd
```

worked fine.

But, yes

```
systemctl stop systemd-udevd
/usr/lib/systemd/systemd-udevd --daemon
udevadm control --exit
```

removed the `/run/udev/control`

**Comment by poettering** [comment]
If the socket should go away on socket stop we could add RemoveOnStop= to its socket file. Generally we avoid that however, see the docs for that option.
