### ISSUE TITLE
wrong interface used for DNSOverTLS

### ISSUE THREAD

**Issue by dougz** [systemd/systemd#24774]
### systemd version the issue has been seen with

251 (251.4-3)

### Used distribution

Debian 12 (bookworm)

### Linux kernel version used

5.18.0-3-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I think this is issue #11935, but for DNSOverTLS.

I have multiple interfaces and systemd-resolved configured to try two of them for resolutions. I have routing policy rules and routing tables that direct traffic according to the outbound interface. When i use regular DNS, this all works great. When I turn on DNSOverTLS as well, it stops working.

### Unexpected behaviour you saw

Without DNSOverTLS, strace on systemd-resolved shows it setting IP_UNICAST_IF and SO_BINDTOIFINDEX.  I think the latter of these is what works, and the traffic is routed correctly.

With DNSOverTLS enabled, it's only setting IP_UNICAST_IF, which seems to have no effect on traffic routing.

### Steps to reproduce the problem

Configure two networks to get lookups for "~.".  Use `ip rule add oif eth0 table 100` and `ip rule add oif eth1 table 101` to set up different routing tables for outbound traffic on the two interfaces. Delete the default route in the "main" table. Use `ip route add default ... table 100` to set a default route on one table but not the other.

"resolvectl query" should always work, since it should make the request on both interfaces. With DNSOverTLS enabled it will only work if the interface it picks happens to be the one with the default route.

**Comment by dougz** [comment]
Thanks for your reply.

My use case: I have a device with multiple independent connections to the internet, each of which is somewhat unreliable. When we want to do a DNS lookup, we send the query over _all_ of them in parallel, in hopes that at least one will get a response. systemd-resolved supports doing this; with classic DNS over UDP it works great.

We are not concerned with server privacy nor load on the server, since all of them are going to the same server anyway, which we run.  We _are_ concerned about them being observed or intercepted in transit, though, which is why we want to use DNSOverTLS.

When we enable DNSOverTLS, though, using multiple interfaces stops working. It _tries_ to work: it actually does send one request per interface, but it isn't binding them to the different interfaces correctly, so all of them end up trying to use the (same) default route. So it's really just broken in its current state.

**Comment by pemensik** [comment]
Does that mean that the target DNS servers are the same one(Google?) with the same address for both connections?

I don't think resolved has to send all queries over both interfaces. Instead, it should send periodically just *some* queries to all servers, especially if the current server has some delay. If the one interface resolver stops working, it should just fast enough to a working one. I guess 1s timeout would be still okay if it does not timeout users query. It should try other servers before the users query will fail. For example dnsmasq does such probing each 20s on all servers, but it does not have DNS over TLS support.

Unless you insist on using the same set of servers, you could specify different servers on each connection. For example 8.8.8.8 and 1.1.1.1 on one, 8.8.4.4 and 9.9.9.9 on the other. Then you would be able to configure routes to those addresses manually, each with defined outgoing interface. It would make more work to configure it, but should be possible with current implementation.

The remaining question is how fast is systemd willing to switch between current resolvers. Especially if it has two interfaces with equivalent metric.

**Comment by dougz** [comment]
I think we've gotten off track here.  systemd-resolved has two useful features: resolving over multiple interfaces, and using DNS-over-TLS. It claims they work and makes no mention of them being mutually exclusive. Each feature works, but when you try to use them together, they don't.  That's a bug, right? That's what I'm trying to report.

**Comment by pemensik** [comment]
It would be nice if you could add output of ``resolvectl status`` if used resolvers were public IPs, so it is clear what you are trying to archieve.

**Comment by poettering** [comment]
Neither SO_UNICAST_IF nor SO_BINDTODEVICE really work for TCP (SO_UNICAST_IF is a NOP for TCP and SO_BINDTODEVICE limits not just egress but also ingress which is generally not desirable for TCP).

Hence, I don't think we can change anything on resolved right now, even if we wanted to.

That said I am pretty sure the right fix for this is actually in your network management solution. For example, in networkd we by default place an explicit host route towards your DNS server (as retrieved via DHCP) unless this is disabled via RoutesToDNS=no, to ensure DNS traffic automatically goes through the interface the DNS info belongs to. I think this is a much more powerful and automatic solution

If you don't use networkd but some other network management tool, consider asking them to add an equivalent option.

Hence, closing, since I think that's a much preferable solution
