### ISSUE TITLE
repart should support creating btrfs subvolumes

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24776]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

I'd like to be able to copy files from the host directly into btrfs subvolumes in the repart generated partitions.

### Describe the solution you'd like

A way to configure btrfs subvolumes in the repart partition definition files. I initially thought about adding `MakeSubvolumes=`, but then I realized that we might want to be able to configure these subvolumes as read-only, or if per subvolume compression is ever added, we might want to enable that immediately on a subvolume, same for filesystem encryption when that lands.

To be able to support various subvolume options in the future, I figure we might want to add `Subvolume` sections instead, where each `Subvolume` section configures a single subvolume. These would take the obvious `Path=` setting, and extra settings to configure the subvolume. The first setting we'd add is `ReadOnly=`, and we'd leave room open to add `Compress=` or `Encrypt=` as well in the future when these get added.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
starts smelling a lot like "systemd-tmpfiles --root="

**Comment by poettering** [comment]
(that said, we currently don't support setting subvol attributes via tmpfiles. we proably should)

**Comment by DaanDeMeyer** [comment]
Yeah, considering your suggestions in the other issue, we don't actually need this in repart, tmpfiles should be a way better solution, but yes we do need to support setting subvol attributes via tmpfiles.

**Comment by poettering** [comment]
→ #24788
