### ISSUE TITLE
DynamicUser with no static User cannot create multiple StateDirectories that share a common prefix

### ISSUE THREAD

**Issue by RaitoBezarius** [systemd/systemd#24783]
### systemd version the issue has been seen with

251

### Used distribution

NixOS unstable

### Linux kernel version used

5.15.63

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

It creates multiple state directories, even if they do share a common prefix, by, e.g. sorting them or ignoring already existing prefixes.

### Unexpected behaviour you saw

The service fails with `status=238/STATE_DIRECTORY`.

### Steps to reproduce the problem

(1) Create a systemd service with `DynamicUser=true` and `User=user` where `user` is not static in the system (maybe static setups fails also, I did not test.)
(2) Add `StateDirectory=data data/uploads`, possible by manual pages and possible when `DynamicUser=false` for example

Run this service.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
machine # [    8.743574] systemd[945]: listmonk.service: Failed to set up special execution directory in /var/lib: File exists
machine # [    8.745210] nscd[880]: 880 monitoring directory `/etc` (2)
machine # [    8.745777] systemd[945]: listmonk.service: Failed at step STATE_DIRECTORY spawning /nix/store/bii7l73s4mldagsfrn86161xzsns1810-listmonk-2.2.0/bin/listmonk: File exists
machine # [    8.747025] nscd[880]: 880 monitoring file `/etc/passwd` (1)
machine # [    8.747586] systemd[1]: listmonk.service: Control process exited, code=exited, status=238/STATE_DIRECTORY
```

**Comment by yuwata** [comment]
Fix is waiting #24784.
