### ISSUE TITLE
tmpfiles.d: tmpfile cleanup should not remove /tmp/.X11-unix/X0

### ISSUE THREAD

**Issue by chergert** [systemd/systemd#2479]
`systemd-222-13` as found on `Fedora 23` with `x86_64`

Xorg creates both an abstract socket, and a real socket at `/tmp/.X11-unix/X0`. We need access to the real socket in xdg-app so that we can mount it in the inferiors namespace (since we cannot use the abstract socket with another network namespace without giving access to _all_ of the host network namespace). However, tmplfiles.d seems to be removing the real socket.

I verified this with GNOME 3.18 using the Control Center → Privacy → Purge Trash & Temporary Files → Purge Temporary Files.

I'm not familiar with the code-base, but I'd expect that we probably want some special case ignores for `/tmp/.X11-unix/`.

**Comment by ohsix** [comment]
if tmpfiles is even involved, http://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#x

**Comment by chergert** [comment]
Yup, looks like you're right. I assumed we were using systemd-tmpfiles for this, and it is in fact in `gnome-settings-daemon`.
