### ISSUE TITLE
Systemd component broken after update (resolved, timesyncd)

### ISSUE THREAD

**Issue by xebug** [systemd/systemd#24798]
### systemd version the issue has been seen with

systemd-245.4-4ubuntu3.18

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.0-122-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Steps to reproduce the problem

Upgraded this morning systemd

`Start-Date: 2022-09-23  06:06:35
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold upgrade --with-new-pkgs
Upgrade: libsystemd0:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), udev:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), libudev1:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), systemd-timesyncd:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), systemd-sysv:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), libpcre2-8-0:amd64 (10.34-7, 10.34-7ubuntu0.1), libpam-systemd:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), systemd:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), libnss-systemd:amd64 (245.4-4ubuntu3.17, 245.4-4ubuntu3.18), libjpeg-turbo8:amd64 (2.0.3-0ubuntu1.20.04.1, 2.0.3-0ubuntu1.20.04.3)
End-Date: 2022-09-23  06:07:34
`

Then, tryed to restart systemd-resolved, systemd-timesyncd :

`Sep 23 10:48:53 systemd[1]: Starting Network Name Resolution...
Sep 23 10:48:53 systemd[1672339]: systemd-resolved.service: Failed to set up mount namespacing: /run/systemd/unit-root/dev: Invalid argument
Sep 23 10:48:53 systemd[1672339]: systemd-resolved.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-resolved: Invalid argument
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Main process exited, code=exited, status=226/NAMESPACE
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
Sep 23 10:48:53 systemd[1]: Failed to start Network Name Resolution.
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 4.
Sep 23 10:48:53 systemd[1]: Stopped Network Name Resolution.
Sep 23 10:48:53 systemd[1]: /dev/null is not a device.
Sep 23 10:48:53 systemd[1]: Starting Network Name Resolution...
Sep 23 10:48:53 systemd[1672342]: systemd-resolved.service: Failed to set up mount namespacing: /run/systemd/unit-root/dev: Invalid argument
Sep 23 10:48:53 systemd[1672342]: systemd-resolved.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-resolved: Invalid argument
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Main process exited, code=exited, status=226/NAMESPACE
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
Sep 23 10:48:53 systemd[1]: Failed to start Network Name Resolution.
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
Sep 23 10:48:53 systemd[1]: Stopped Network Name Resolution.
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Start request repeated too quickly.
Sep 23 10:48:53 systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
Sep 23 10:48:53 systemd[1]: Failed to start Network Name Resolution.
`

(same for systemd-timesyncd)

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
