### ISSUE TITLE
bond for wlan/lan failover: how to reconfigure local services upon bond's ip address change?

### ISSUE THREAD

**Issue by m1027** [systemd/systemd#24809]
Hi,

I have a simple bond0 as a lan1/wlan0 failover for the outgoing internet connection.

```
[NetDev]
Name=bond0
Kind=bond
[Bond]
Mode=active-backup
AdSelect=bandwidth
FailOverMACPolicy=active
```
And the usual interface setup:
```
# 10-lan1.network:
[Match]
Name=lan1
[Network]
DHCP=no
Bond=bond0
PrimarySlave=true

# 10-wlan0.network:
[Match]
Name=wlan0
[Network]
DHCP=no
Bond=bond0

# 20-bond0.network:
[Match]
Name=bond0
[Network]
DHCP=yes
BindCarrier=wlan0 lan1
```

What works:

- bond0 works in general
- Pulling out lan1 cable activates wlan0
- The external DHCP servers (connected to lan1 resp. wlan0) get retriggered because of bond0's FailOverMACPolicy=active, so we get a new ip address for bon0 upon failover

What does NOT work:

- The local openvpn-client service that is enabled and started after boot (without password) always sticks to wlan0's initial ip address (which seems to receive one pretty fast, probably before bond0 kicks in and switches to lan1 as it is configured PrimarySlave=true)
- openvpn's man page says that it wishes to receive a SIGUSR1 in case the local ip address changes (see "--ipchange": "If  our  IP address changes due to DHCP, we should configure our IP address change script (see man page for dhcpcd(8)) to deliver a SIGHUP or SIGUSR1 signal to OpenVPN. OpenVPN will then re-establish a connection with its  most recently authenticated peer on its new IP address."

So the final problem is:

- When bond0 gets a new ip address (from extermal DHCP),
- and there is no local dhcpcd that allows hook scripts (as we use systemd's DHCP)
- how would we send the local OpenVPN client SIGUSR1 upon DHCP/ip address change of bond0?

FYI: Manual workaround:

- Indeed, after reboot, and after the openvpn client is up (but hangs on invalid wlan0 interface), sending SIGUSR1 to the openvpn process makes it use the correct ip address of bond0 (which is from lan1)

FYI: NetworkManager's dispatcher

- NetworkManager has a dispatcher
- but systemd for some reason stops the dispatcher service after a while automatically
- we don't feel that this is a proper solution and did not investigate further 

FYI: Our current automatic workaround:

- Configure the local OpenVPN client with an idle timeout ("inactive 60")
- Configure the openvpn client systemd service with Restart=always
- However this interrupts even working openvpn sessions after 60 seconds without interaction...

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
