### ISSUE TITLE
Lenovo Thinkpad P1 Gen 3: extra keys on keyboard

### ISSUE THREAD

**Issue by jeroenhd** [systemd/systemd#24814]
### systemd version the issue has been seen with

251.4-1

### Used distribution

Manjaro

### Linux kernel version used

5.19.7-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Several special keyboard combinations (Fn key + something) should generate somewhat standard key codes

### Unexpected behaviour you saw

Unknown keycodes reported by `evtest`

### Steps to reproduce the problem

1. Buy Lenovo Thinkpad P1 Gen 3
2. Run `sudo evtest` and pick "ThinkPad Extra Buttons"
3. Press the keys:
    - Fn + F9 (notifications key)
    - Fn + F10 (answer call key)
    - Fn + F11 (hangup call key)
    - Fn + right shift
    - Fn + PrtSc

Note: I have configured my laptop to use F-keys by default and activate special functions through the Fn-key. This is not the default.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
As requested, the output of `udevadm info /dev/input/event14`:

P: /devices/platform/thinkpad_acpi/input/input15/event14
M: event14
R: 14
U: input
D: c 13:78
N: input/event14
L: 0
S: input/by-path/platform-thinkpad_acpi-event
E: DEVPATH=/devices/platform/thinkpad_acpi/input/input15/event14
E: DEVNAME=/dev/input/event14
E: MAJOR=13
E: MINOR=78
E: SUBSYSTEM=input
E: USEC_INITIALIZED=4194462
E: KEYBOARD_KEY_01=screenlock
E: KEYBOARD_KEY_02=battery
E: KEYBOARD_KEY_03=sleep
E: KEYBOARD_KEY_04=wlan
E: KEYBOARD_KEY_06=switchvideomode
E: KEYBOARD_KEY_07=f21
E: KEYBOARD_KEY_08=f24
E: KEYBOARD_KEY_0b=suspend
E: KEYBOARD_KEY_0f=brightnessup
E: KEYBOARD_KEY_10=brightnessdown
E: KEYBOARD_KEY_11=kbdillumtoggle
E: KEYBOARD_KEY_13=zoom
E: KEYBOARD_KEY_14=volumeup
E: KEYBOARD_KEY_15=volumedown
E: KEYBOARD_KEY_16=mute
E: KEYBOARD_KEY_17=prog1
E: KEYBOARD_KEY_1a=f20
E: KEYBOARD_KEY_45=bookmarks
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_SWITCH=1
E: ID_PATH=platform-thinkpad_acpi
E: ID_PATH_TAG=platform-thinkpad_acpi
E: LIBINPUT_DEVICE_GROUP=19/17aa/5054:thinkpad_acpi
E: DEVLINKS=/dev/input/by-path/platform-thinkpad_acpi-event
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:
```

**Comment by jeroenhd** [comment]
I've generated this bug report as instructed by my `/usr/lib/udev/hwdb.d/60-keyboard.hwdb`

To use these key combinations, I've set up the following rules in `/etc/udev/hwdb.d/90-keyboard-fix.hwdb`:
```
# Lenovo Thinkpad P1 Gen 3
#
# IDs:
# /sys/class/input/event14/device/id/bustype:    0019
# /sys/class/input/event14/device/id/product:    5054
# /sys/class/input/event14/device/id/vendor:     17aa
# /sys/class/input/event14/device/id/version:    4101
# Matching definition copied from existing keyboard, I don't know how to specify this specific hardware
#
# Other Fn keybinds that are injected in the hardware level:
# - Fn + S = AltGr + SysRq
# - Fn + P = Pause
# - Fn + K = Scroll lock
# - Fn + Left = Home
# - Fn + Right = End
# - Fn + End = Insert
#
# Definitions start here
evdev:name:ThinkPad Extra Buttons:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:*
 KEYBOARD_KEY_46=prog1   # Fn + PrtSc, on Windows: Snipping tool
 KEYBOARD_KEY_4a=prog2   # Fn + Right shift, on Windows: No idea
 KEYBOARD_KEY_4b=chat    # Fn + F9, on Windows: Notifications panel key
 KEYBOARD_KEY_4c=connect # Fn + F10, on Windows: Answer (Teams) call
 KEYBOARD_KEY_4d=cancel  # Fn + F11, on Windows: Hangup/decline (Teams) call
```

I don't know how to make the selector specific enough to get the hwdb rules to only apply to this model keyboard, so I chose to create a bug report rather than a PR. Hopefully someone with more experience can tell me how?

**Comment by yuwata** [comment]
Currently, `prog2` is assigned to `KEY_46` recently by 376a30a7e55a61815bb86dde8ea64451b9986c5d, but it is done quite recently so feel free to change it, if it does not work for you. However, `prog1` is already assigned to `KEY_17`. I am not familiar with how we should assign `progX`, but maybe better to assign different number for `KEY_46` and `KEY_4a`?

Anyway, please consider to submit the change as a patch.

**Comment by jeroenhd** [comment]
The conflicting key definitions are the reason I opened this as an issue rather than a pull request, I get the feeling these key bindings only make sense on my specific model laptop, but I don't have alternative laptops to test with.

Is there a way to make key bindings like these only apply to my specific type of Thinkpad?
