### ISSUE TITLE
Fix Positivo-vaio FE14 V2 key toggle touchpad

### ISSUE THREAD

**Issue by drosdeck** [systemd/systemd#24822]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.1

### Linux kernel version used

5.15.0-43-generic

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Fn+F1 in my device was to be able to toggle (on-off) touchpad

### Unexpected behaviour you saw

The pressing of the keys wasn't responding

### Steps to reproduce the problem

Press Fn+F1

**Comment by yuwata** [comment]
Fixed by #24825.
