### ISSUE TITLE
Network config is not persisted while Disable/Enable Ethernet interface

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#24843]
### systemd version the issue has been seen with

249.7

### Used distribution

ubuntu

### Expected behaviour you didn't see

While enabling ethernet interface its expected to come back with old IP config which is persisted in network config file

### Unexpected behaviour you saw

loosing all old IP config(before disable interface) after enabling Ethernet interface back.

### Steps to reproduce the problem

1. configure static IP 
2. disable interface  (which sets Unmanaged=yes in config file)
3. enable interface and static IP config is not persisted 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemctl --version
systemd 249 (249.4+)

1. Network config before disabling NIC interface

cat /etc/systemd/network/00-sys-eth0.network 
[Match]
Name=eth0
[Link]
MACAddress=0x:xx:xx:xx:00:xx
[Network]
LinkLocalAddressing=yes
IPv6AcceptRA=true
NTP=google.time.com
DHCP=ipv6
[Address]
Address=9.x.xx.xx/24
[Route]
Gateway=9.x.x.1
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseDomains=true
UseNTP=true
UseHostname=true
SendHostname=true


2. Disable and  Enable NIC interface

3. Config file after enabling NIC interface

cat /etc/systemd/network/00-sys-eth1.network 
[Match]
Name=eth1
[Link]
MACAddress=0x:xx:xx:xx:xx:xx
Unmanaged=no
[Network]
IPv6AcceptRA=true
NTP=google.time.com
DHCP=ipv6
[DHCP]
ClientIdentifier=mac
UseDNS=true
UseDomains=true
UseNTP=true
UseHostname=true
SendHostname=true

earlier it used to persist IP config across interface enable/disables
```

**Comment by poettering** [comment]
"2. Disable and  Enable NIC interface"

What does this mean? how do you "disable and enable NIC interface"? which tool? which command?

**Comment by poettering** [comment]
Note that /etc/ is where user provided configuration is located. networkd just reads/consumes that, it does not write/provide that. So as I understand your local system changes this and you'd rather not have that? But if that#s the case that must be some tooling outside of systemd, because we never write there...

**Comment by poettering** [comment]
Morevoer, this is about an old systemd version, we only care about the two most recent systemd versions here. For the older versions please contact your distro instead.

Altogether, let's close this here for now. This looks like some issue with some other software that writes configuration files for you, and is with too old versions of systemd anyway, and it looks like a support question more than a bug report. So: wrong place to report it, too old, support question. hence this here is the wrong forum.

Please contact your distro for help.
