### ISSUE TITLE
systemctl does not work well with tomcat8 at Arch Linux

### ISSUE THREAD

**Issue by xiepeiyang** [systemd/systemd#2484]
konsole : pacman -S tomcat8
create /Catalina/localhost/bug.xml and write
`<Context path="/bug"  docBase="/home/myuser/bug" reloadable="true"/>`
konsole : systemctl start tomcat8
open http:.//localhost:8080 , it work well.
open http://localhost:8080/bug,  show 404.
konsole：systemctl stop tomcat8
....
konsole : sh startup.sh
open http://localhost:8080 , it work well.
open http://localhost:8080/bug , it work well !

or after pacman -S tomcat8
using sh  startup.sh rather systemctl . it will work.
it is a bug ?  or my mistake ?

Arch Linux : up to date, jdk 8u72-1 , tomcat8 8.0.30-1

**Comment by poettering** [comment]
Doesnt look like a systemd issue. please ask the archlinux tomcat packagers for help. thanks.
