### ISSUE TITLE
systemd cgroup hybrid mode lost entry on unified and systemd directory

### ISSUE THREAD

**Issue by smileusd** [systemd/systemd#24858]
When user run kubernetes pod on our cluster with systemd driver to create cgroup, sometimes the entry on unified and systemd (other subsystem not found this issue) cgroup subsystem of container lost so we can not exec into this container.

containerd version:
v1.6.6

runc --version
runc version 1.1.2
commit: v1.1.2-0-ga916309f
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.3

### systemd version the issue has been seen with

systemd 245

### Used distribution

ubuntu 20.04.4

### Linux kernel version used

5.4.0-96-generic

### Component

systemd

### Expected behaviour you didn't see

entry exist

### Unexpected behaviour you saw
```
OCI runtime exec failed: exec failed: unable to start container process: error adding pid 25541 to cgroups: failed to write 25541: open /sys/fs/cgroup/unified/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0f30b954_acf6_40c3_b939_d6e48f2d530c.slice/cri-containerd-d099a332b384b09ee67f829c67212f07e57a1111b9953cef418d7ce55d83a689.scope/cgroup.procs: no such file or directory: unknown

OCI runtime exec failed: exec failed: unable to start container process: error adding pid 303419 to cgroups: failed to write 303419: open /sys/fs/cgroup/systemd/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode61aa24c_a0c4_433b_90d9_2bf78fac64c5.slice/cri-containerd-6f216978cf6ab934cac4d336cf5edb064006be5768df76a4cb12a33f12b88d40.scope/cgroup.procs: no such file or directory: unknown
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by smileusd** [comment]
@poettering Thank you for reply. Yoy mean this is a systemd upstream bug but I still not sure which Change fix this issue. Could you point where is the original PR/Issue or Changes.  And so only v251 is available for this issue?
Thanks a lot.
