### ISSUE TITLE
Add an option to run a service with an inhibitor lock

### ISSUE THREAD

**Issue by fallenguru** [systemd/systemd#2486]
Use case: simple services, like backups or filesystem scrubs, that should not be interrupted

It's possible to wrap whatever you want to do in systemd-inhibit, but then User= stops working (because systemd-inhibit is privileged) and that requires another wrap in su(do). Even then your service might still fail if it gets scheduled to run after the system has resumed but before the resume is finished (because then systemd-inhibit will fail to get a lock). That can be fixed by After-dependencies on sleep.target suspend.target and hybrid-sleep.target.

This works but it's much less elegant than it could be. I'd much rather there be an Inhibit= option in the [Service] section that takes the same argument als systemd-inhibit --what= and just does the right thing.

**Comment by poettering** [comment]
That would mean PID1 would become a client of logind, and that's something I really don#t want.

Also, note that PolicyKit allows defining policies that allow your user of choice access to the inhibitors, and for that no change in PID 1 is necessary.

Hence, you can already do what you want by invoking systemd-inhibit and defining the right PK policy. Closing hence. Sorry!
