### ISSUE TITLE
global LLMNR=false/no ignored on per-link basis

### ISSUE THREAD

**Issue by msoltyspl** [systemd/systemd#24863]
### systemd version the issue has been seen with

systemd 251 (251.3-1~bpo11+1)

### Used distribution

debian bullseye 11

### Linux kernel version used

5.18.0-0.deb11.4-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

As per manual - the expected behavior as per resolved.conf manual is that LLMNR on a per-link basis should be enabled only if both per-link and global setting is enabled. But in practice per-link setting ignores global setting.

### Unexpected behaviour you saw

```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (mv-vlan10)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (mv-vlan13)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.13.36.2
       DNS Servers: 10.13.36.2
        DNS Domain: touk.pl

Link 4 (mv-vlan17)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (mv-vlan30)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 6 (mv-vlan31)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 7 (mv-vlan47)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 8 (mv-vlan250)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

LLMNR is enabled per-link despite being disabled globally, which conflicts with `Note that systemd-networkd.service(8) also maintains per-link LLMNR settings. LLMNR will be enabled on a link only if the per-link and the global setting is on.`

### Steps to reproduce the problem

Disable LLMNR in resolved.conf, restart relevant services.

**Comment by Tachi107** [comment]
See #25252 for an explanation why this happens
