### ISSUE TITLE
systemd-bootarm.efi "data abort" starting with v251

### ISSUE THREAD

**Issue by puppetjoy** [systemd/systemd#24871]
### systemd version the issue has been seen with

251

### Used distribution

Gentoo

### Linux kernel version used

5.19.4

### CPU architectures issue was seen on

arm

### Component

systemd-boot

### Expected behaviour you didn't see

U-boot executes systemd-bootarm.efi and displays the loader menu

### Unexpected behaviour you saw

U-boot executes systemd-bootarm.efi and crashes with a "data abort" error and resets the CPU

### Steps to reproduce the problem

1. Upgrade from systemd-250 to systemd-251
2. Update the boot loader (`bootctl update`)
3. Observe crash on 32-bit ARM system
4. Observe no crash on other platforms including aarch64 and x86_64

I also bisected the repository between tags v250 and v251 with the following build procedure:

1. `git bisect start`
2. `git bisect good v250`
3. `git bisect bad v251`
4. `rm -rf build && meson build && ninja -C build src/boot/efi/systemd-bootarm.efi`
5. `sudo cp build/src/boot/efi/systemd-bootarm.efi /boot/EFI/BOOT/BOOTARM.EFI`
6. `reboot`

And marking success/failure with `git bisect [good|bad]` and repeating until it identified commit 661615a0afacee3545cde0a48286c0fef983f8fe as the start of the failure.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
U-Boot 2021.01-gc4fddedc48 (Apr 15 2022 - 20:23:26 -0400)

CPU  : AM335X-GP rev 2.0
Model: TI AM335x BeagleBone Black
DRAM:  512 MiB
WDT:   Started with servicing (60s timeout)
NAND:  0 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
<ethaddr> not set. Validating first E-fuse MAC
Net:   eth2: ethernet@4a100000, eth3: usb_ether
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
Failed to load 'boot.scr'
Failed to load 'uEnv.txt'
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
69918 bytes read in 8 ms (8.3 MiB/s)
Scanning disk mmc@48060000.blk...
** Unrecognized filesystem type **
Scanning disk mmc@481d8000.blk...
** Unrecognized filesystem type **
Found 4 disks
** Unable to read file ubootefi.var **
Failed to load EFI variables
BootOrder not defined
EFI boot manager: Cannot load any image
Found EFI removable media binary efi/boot/bootarm.efi
148127 bytes read in 15 ms (9.4 MiB/s)
Booting /efi\boot\bootarm.efi
systemd-boot@0x9CF00000,0x9CF21CA0
data abort
pc : [<9cf1607c>]          lr : [<9cf3905e>]
reloc pc : [<7d7a807c>]    lr : [<7d7cb05e>]
sp : 9df41070  ip : 9df41080     fp : 9df410fc
r10: 9df5cb28  r9 : 00000000     r8 : 00000000
r7 : 9df5d0f8  r6 : 00000000     r5 : 9ff6ef40  r4 : 9ffaab81
r3 : 9cf3905e  r2 : 00000000     r1 : 00000000  r0 : 00000000
Flags: nZCv  IRQs off  FIQs on  Mode SVC_32
Code: e14b24fc e51b3010 e24bc07c e1a0e003 (e8be000f)
UEFI image [0x9cf00000:0x9cf22bdf] pc=0x1607c '/efi\boot\bootarm.efi'
Resetting CPU ...

resetting ...
```

**Comment by jameslikeslinux** [comment]
To rule out a failure due to code size increase, I compiled v251 with `-Os` resulting in an EFI binary 10k smaller than the working v250 version compiled with `-O2`. It still failed with the same data abort error.

**Comment by yuwata** [comment]
Is the issue reproducible with the current git HEAD?

**Comment by jameslikeslinux** [comment]
No. I should have tried that first.
