### ISSUE TITLE
Dbus reload when logged into gnome leads to hard lock

### ISSUE THREAD

**Issue by welsh-dwarf** [systemd/systemd#2488]
Steps to reproduce:

Log into gnome, start terminal, restart dbus service.

Observed on Debian testing (systemd 228, gnome 3.20)

**Comment by zdzichu** [comment]
This is dbus problem, but here is not dbus bug tracker.
You are not supposed to restart reference dbus-daemon implementation.

**Comment by poettering** [comment]
Dbus doesnt support restaeting during runtime. its a limitation of the dbus implememtation, and if considered a bug should be reported against dbus and not systemd. Closing.
