### ISSUE TITLE
repart CopyFiles=/usr/:/ ignores --root argument

### ISSUE THREAD

**Issue by pyfisch** [systemd/systemd#24895]
### systemd version the issue has been seen with

systemd 251 (251-2279-g8e52ed0)

### Used distribution

Arch

### Linux kernel version used

5.19.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

The command `systemd-repart --definitions=part/ --root=data/ --empty=create --size=auto --pretty=no image.raw` uses the partition definitions from the `part` folder and the contents of the `data/` folder to build `image.raw`. 

part/usr.conf:
```
[Partition]
Type=usr
SizeMinBytes=512M
SizeMaxBytes=512M
Format=squashfs
CopyFiles=/usr:/
```

With this partition file I expect that the contents of the `data/usr` folder are found in the squashfs file system.

### Unexpected behaviour you saw

Repart operates on the actual root file system, not the folder given by `--root`. 
Note that if the line `CopyFiles=/usr:/` is changed to `CopyFiles=/usr` it behaves as expected: the contents from `data/usr/` are placed in the `usr` folder of the squashfs.

**Comment by DaanDeMeyer** [comment]
Thanks for all the testing! Fix is waiting in #24896
