### ISSUE TITLE
initrd-root-device.target doesn't (but should?) depend on the root device

### ISSUE THREAD

**Issue by tomfitzhenry** [systemd/systemd#24904]
### systemd version the issue has been seen with

251

### Used distribution

NixOS

### Linux kernel version used

5.19.12

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

During initrd, I expect `initrd-root-device.target` to have a dependency on the root device `dev-sda1.device`.

This would be useful, because it'd allow me to wipe the root btrfs fs before it gets mounted, by creating a service unit `wipe-fs.service` that has `After=initrd-root-device.target` and `Before=sysroot.mount` that mounts, wipes by deleting/re-creating the rootfs subvolume, unmounts. initrd would then continue, by mounting the freshly created subvolume.

FWIW, my motivation to wipe the root partition is https://grahamc.com/blog/erase-your-darlings .

### Unexpected behaviour you saw

I see that `initrd-root-device.target` has no dependencies.

```
$ systemctl list-dependencies initrd-root-device.target
```

This means that `wipe-fs.service` can execute before `dev-sda1.device` is ready, and thus `wipe-fs.service` fails.

Rather, `sysroot.mount` has the dependency on the root device (output from memory).

```
$ systemctl list-dependencies sysroot.mount | grep ".device$"
* dev-sda1.device
```

I think this comes from https://github.com/systemd/systemd/blob/0a8720c7f087f17061a501d50e0dcd87bb58fa32/src/fstab-generator/fstab-generator.c#L896-L900 .

**Comment by poettering** [comment]
hmm, actually, such a dependency should be generated already, the code is there.

Are you running those cmmands from initrd context?

how do you define the rootfs?

when gpt-auto is used we should end up with a dep on /dev/gpt-auto-root. And with fstab-generator on the device specified via root= on the kernel cmdline.

**Comment by poettering** [comment]
does nixos even use systemd in the initrd?

**Comment by ElvishJerricco** [comment]
Yea, currently NixOS does it a little bit wrong. We have a `/sysroot` entry in initrd's `/etc/fstab`, which doesn't get the same treatment w.r.t. `initrd-root-device.target` as the `root=` cmdline parameter (#3551). One of the reasons we do this is because `root=` and `rootflags=` don't respect options like `x-systemd.makefs` and `x-systemd.growfs`.
