### ISSUE TITLE
systemctl daemon-reexec enables previously disabled service

### ISSUE THREAD

**Issue by smu-ggl** [systemd/systemd#24916]
### systemd version the issue has been seen with

251.4

### Used distribution

Debian testing

### Linux kernel version used

5.18.16

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

systemctl daemon-reexec shouldn't change the set of enabled/disabled services

### Unexpected behaviour you saw

It enabled systemd-networkd.service

### Steps to reproduce the problem

- Disable (not mask) systemd-networkd.service.
- Reboot
- Note that systemd-networkd.service is still disabled.
- Run `systemctl daemon-reexec`
- Note that systemd-networkd.service is now enabled.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# systemctl status systemd-networkd.service
○ systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; disabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
# systemctl daemon-reexec
# systemctl status systemd-networkd.service
○ systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
```

**Comment by mbiebl** [comment]
maybe something is triggering `systemctl preset-all`. The Debian package ships an unmodified 90-systemd.preset where networkd is enabled by default

**Comment by mbiebl** [comment]
> * Note that systemd-networkd.service is still disabled.
> * Run `systemctl daemon-reexec`
> * Note that systemd-networkd.service is now enabled.

fwiw, these steps are not sufficient to reproduce the problem here.

**Comment by poettering** [comment]
what are we supposed to do with this? if this is not reproducible and there are no logs and nothing, this is not actionable to us.

I am tempted to just close this...

Or is this reproducible? Are there debug logs available when this happens?

**Comment by smu-ggl** [comment]
I can't reproduce with 252.5 anymore, so marking this as closed (considered either Fixed or Obsolete)
