### ISSUE TITLE
systemctl list-jobs gets dependency relationships backwards

### ISSUE THREAD

**Issue by CFSworks** [systemd/systemd#24941]
### systemd version the issue has been seen with

251

### Used distribution

Debian "bookworm"

### Linux kernel version used

5.19.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

`systemctl list-jobs --after/before` lists, for each each job J, J itself and then the jobs J is waiting for as "waiting for job" and the jobs waiting for J as "blocking job"

### Unexpected behaviour you saw

`systemctl list-jobs --after/before` lists, for each each job J, J itself and then the jobs J is waiting for as "blocking job" and the jobs waiting for J as "waiting for job"

### Steps to reproduce the problem

1. Create 2 units A and B such that A includes `After=B`, and B takes a long time (e.g. 30 seconds) to start
2. Use `systemctl` to start A and B
3. Run `systemctl list-jobs --after`
4. Observe incorrect output saying that A is not waiting on anything but B is waiting on A's completion

**Comment by CFSworks** [comment]
This is due to the `list-jobs` verb getting its prefixes in the calls to [GetJobAfter](https://github.com/systemd/systemd/blob/v251/src/systemctl/systemctl-list-jobs.c#L105) and [GetJobBefore](https://github.com/systemd/systemd/blob/v251/src/systemctl/systemctl-list-jobs.c#L107) backwards.

That, in turn, probably arises from confusion about how the `--after` and `--before` flags are documented. For example with `--after`:
- `systemctl list-dependencies --after` is documented to `show the units that are ordered before the specified unit` (that is, for specified unit U, show the units U **is after**).
- `systemctl list-jobs --after` is documented to `show which other jobs are waiting for it` (that is, for each job J, show the jobs **after J**).

`systemctl list-jobs --after` does indeed show the jobs "after J" (which is inconsistent with `list-dependencies`) but it indicates them saying J is "waiting for job X" which is incorrect: X is actually waiting for J.

**Comment by msekletar** [comment]
I think that we should simply say "blocks job X" instead of very misleading "waiting for job X".

**Comment by wferi** [comment]
On the other hand `man systemctl` says about `list-jobs`:
> When combined with `--after` or `--before` the list is augmented with information on which other job each job is waiting for, and which other jobs are waiting for it

which would mean the verbiage ("waiting for job" for `--after` and "blocking job" for `--before`) is right, but wrong jobs are selected for display.

Since these command line switch names are rather ambiguous, I'd be equally okay with aligning the code with the documentation or reversing the documentation and aligning the code with that. But first of all the code should be fixed to be self-consistent. (Then it would be great to switch to clearer verbiage if possible.)

**Comment by CFSworks** [comment]
> On the other hand `man systemctl` says about `list-jobs`:
> 
> > When combined with `--after` or `--before` the list is augmented with information on which other job each job is waiting for, and which other jobs are waiting for it

It seems like this excerpt is not "respectively," since `man systemctl` later goes on to clarify:
```
       --after

...

           When passed to the list-jobs command, for each printed job show which other jobs are
           waiting for it. May be combined with --before to show both the jobs waiting for each
           job as well as all jobs each job is waiting for.
```

 
> which would mean the verbiage ("waiting for job" for `--after` and "blocking job" for `--before`) is right, but wrong jobs are selected for display.

`--after` (and vice versa `--before`) does map to a D-Bus call for `GetJobAfter(x)`, which intuitively (to me) should "get the job(s) after x," so it looks to me like the jobs are being selected correctly. I didn't check, but is it possible that the author(s) of the excerpt you pulled from the man page were *themselves* misled by the output?

> Since these command line switch names are rather ambiguous, I'd be equally okay with aligning the code with the documentation or reversing the documentation and aligning the code with that. But first of all the code should be fixed to be self-consistent. (Then it would be great to switch to clearer verbiage if possible.)

I do fully agree that, because it isn't immediately obvious to everyone what part of systemd is at fault here (documentation? strings? logic?) that the terms `before`/`after/`waiting for`/`blocking` are probably too unclear. For the latter two, I might suggest a very simple fix by adding the word "is":

```
J...
        ...is waiting for job X
        ...is blocking job Y
```

This way, it's immediately clear that J is the subject and X/Y are the object. Without the "is," "blocking job Y" could be misread as "the blocking job is Y."

I have no suggestions for `--after`/`--before` other than to make them not prepositions. English prepositions are highly position-dependent and, on their own, tend to lead to this kind of ambiguity.

**Comment by Villemoes** [comment]
Hm, I think the documentation is pretty clear, and that the right jobs are selected, but that the verbs in the output are just wrong (i.e., I think my #32450 is the proper fix). 

```
       list-jobs [PATTERN...]
...
           When combined with --after or --before the list is augmented with information on which
           other job each job is waiting for, and which other jobs are waiting for it, see above.
```
OK, so this doesn't say which is which. But I do believe that is quite clear from the individual descriptions of `--after` and especially `--before`:
```
       --after
           When passed to the list-jobs command, for each printed job show which other jobs are
           waiting for it. May be combined with --before to show both the jobs waiting for each job as
           well as all jobs each job is waiting for.
       --before
           When passed to the list-jobs command, for each printed job show which other jobs it is
           waiting for. May be combined with --after to show both the jobs waiting for each job as
           well as all jobs each job is waiting for.
```
Currently, when just using the `--before` flag, the verb used on the supplementary lines is "blocking", but it very much should be "waiting for". And similarly (re --after), if job X has some other job Y waiting for it, then the correct relationship is that job X is blocking job Y.
