### ISSUE TITLE
stub: incorrect handling of EFI_DEVICE_PATH

### ISSUE THREAD

**Issue by osteffenrh** [systemd/systemd#24955]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 37

### Linux kernel version used

5.19.14-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

**Expectation:** booting a unified kernel image from Grub2 works fine.

### Unexpected behaviour you saw

The efi stub prints the following error messages:

```
Failed to open extra directory of loaded image: Invalid Parameter
Failed to open extra directory of loaded image: Invalid Parameter
```
The boot process then continues after a short delay.

### Steps to reproduce the problem

Generate a unified kernel image using the systemd efi stub `linuxx64.efi.stub`.

Boot that image from Grub2 shell:

```
chainloader vmlinuz.efi
boot
```

The stub encounters an error very early when accessing the "extra dir" aka "dropin dir":
```
Failed to open extra directory of loaded image: Invalid Parameter
Failed to open extra directory of loaded image: Invalid Parameter
```

---
**Some analysis:**

According to the [UEFI Spec, Secton 10.3.5.4](https://uefi.org/specs/UEFI/2.10/10_Protocols_Device_Path_Protocol.html#file-path-media-device-path), a device path may contain multiple File Path Media Device Path nodes to describe the directory/filename path on a filesystem.
For example, Grub2 hands over a device path pointing to the origin of the loaded image which contains two consecutive file path nodes. One for the directory part of the path and the following one for the filename.

Grub generated the following device path (`grub-core/loader/efi/chainloader.c`):
```
/ACPI(a0341d0,0)/PCI(2,1f)/Sata(0,ffff,0)/File(\efi\Linux)/File(vmlinuz.efi)/EndEntire
```

A debug print revealed that the stub tries to access this path on the ESP:
```
\efi\Linux\/vmlinuz.efi.extra
```
Which results in the invalid parameter error.

The stub does not handle device paths with multiple file path nodes correctly when looking for the dropin/extra directories on the ESP.

Note: When patching Grub2 and unifying the directory and filename into one file path node, everything works as expected. But according to the spec Grub2 is allowed to use two file path nodes here.

The path string is the result of [cpio.c:362](https://github.com/systemd/systemd/blob/v251/src/boot/efi/cpio.c#L362)

```c
if (!dropin_dir)
    dropin_dir = rel_dropin_dir = xpool_print(L"%D.extra.d", loaded_image->FilePath);
```

The "/" that shows up between the two file path node strings is the EFI device path separator, not a directory separator in the sense of an EFI directory path (which uses the Windows style `\`).
The print functions behind `%D` (in EDK2 and gnu-efi alike) do not merge consecutive file path nodes into one. They just print reach node and separate them by `/`.

The actual error happens when using this path string as `FilePath` for [`EFI_FILE_PROTOCOL.Open()`](https://uefi.org/specs/UEFI/2.10/13_Protocols_Media_Access.html?highlight=efi_file#efi-file-protocol-open) in [util.c:664](https://github.com/systemd/systemd/blob/v251/src/boot/efi/util.c#L664).

Note: Patching the stub to replace or remove all `\` from `dropin_dir` also circumvents the problem in this particular case.

Possible solutions:
- Construct the path string by "manually" concatenating the file path nodes with the correct separator. Or
- Traverse the device path and open each file path node individually with

**Comment by medhefgo** [comment]
Please give #24962 a try.

**Comment by osteffenrh** [comment]
Does the trick.  Thanks a lot!
