### ISSUE TITLE
automount of a USB flash drive turns the system unusable

### ISSUE THREAD

**Issue by pauser0000001** [systemd/systemd#24964]
### systemd version the issue has been seen with

251

### Used distribution

OpenSuse

### Linux kernel version used

6.0

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Even if a flash drive is included in /etc/fstab with ,comment=systemd.automount. Accessing the mount point should be instantaneous if the flash drive isn't inserted in the usb.
Shouldn't systemd know what disks are present at any time?

### Unexpected behaviour you saw

Doing an ls /flash can take up to 2 minutes.
Starting kde dolphin with a tab in /flash can take up to 10 minutes.
Showing the open/save dialog (kde and gnome) can take up to 5 or more minutes.

### Steps to reproduce the problem

Just add the following line (customized for you USB ports) in /etc/fstab and restart systemd (or reboot).

/dev/sdf1             /flash         vfat    noauto,noexec,defaults,async,noatime,fmask=000,dmask=000,gid=100,comment=systemd.automount 0 2

**Comment by medhefgo** [comment]
You get what you asked for, so works as intended? Yo should see `man systemd.mount` for timeout options, which should give you what you want. Also, you should never use the regular device node paths. They are not guaranteed to be stable. You should really be using UUID or labels for mounting stuff.

**Comment by poettering** [comment]
if you start a .mount unit (and .automount units start .mount units when activated) we'll wait for the device backing it to show up, with a time-out. This is necessary to make booting up work, since devices pop up over a period of time, and we cannot mount them and progress boot until they booted up.

You can shorten the timeout via `x-systemd.device-timeout=`
