### ISSUE TITLE
networkd waits for interface to be renamed forever

### ISSUE THREAD

**Issue by d4nuu8** [systemd/systemd#24975]
### systemd version the issue has been seen with

251.3-1~bpo11+1

### Used distribution

Debian Bullseye

### Linux kernel version used

5.10.0-13

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

A renamed network interface is configured by networkd.

Output of `networkctl`:
```sh
IDX LINK     TYPE     OPERATIONAL SETUP
...
  3 kli      ether    routable    configured
```

### Unexpected behaviour you saw

A renamed network interface is **not** configured by networkd.

Output of `networkctl`:
```sh
IDX LINK     TYPE     OPERATIONAL SETUP
...
  3 kli      ether    off         unmanaged
...
```

### Steps to reproduce the problem

```service
# /etc/systemd/network/02_customboard_kli.link
[Match]
OriginalName=enp4s0
KernelCommandLine=systemd.setenv=BOARD_NAME=CustomBoard

[Link]
Name=kli
WakeOnLan=magic
```

```service
# /etc/systemd/network/kli.network
[Match]
Name=kli

[Network]
VLAN=kli_it
DHCP=ipv4

LinkLocalAddressing=no
IPv6AcceptRA=no

[DHCPv4]
ClientIdentifier=mac
```

Restart as long as the network interface is not configured anymore as expected

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/d4nuu8/0bcbaa2dbadcc44838fb70807d983709

**Comment by d4nuu8** [comment]
Maybe related issue #22538

**Comment by yuwata** [comment]
This sounds an issue in udevd, but the provided log does not contain anything about udevd.

**Comment by yuwata** [comment]
```
# /etc/systemd/network/02_customboard_kli.link
[Match]
OriginalName=enp4s0
KernelCommandLine=systemd.setenv=BOARD_NAME=CustomBoard

[Link]
Name=kli
WakeOnLan=magic
```
BTW, `OriginalName=enp4s0` may not be good. This requires the interface first renamed from `ethX` to `enp4s0`, and then renamed again `kli`. How about to use other conditions, e.g. `MACAddress=`, `PermanentMACAddress=`, `Path=`, or `Property=`?

**Comment by d4nuu8** [comment]
> This sounds an issue in udevd, but the provided log does not contain anything about udevd.

I've added the logs to https://gist.github.com/d4nuu8/0bcbaa2dbadcc44838fb70807d983709

> How about to use other conditions, e.g. MACAddress=, PermanentMACAddress=, Path=, or Property=?

Good point! I'm going to evaluate if we can adjust this. Thanks for the hint!

**Comment by d4nuu8** [comment]
It seems like removing the first renaming of the interfaces suppresses / resolves this issue.

At least I wasn't able to reproduce it within 2000 reboots. Before it took max. 30 reboots to see this.

**Comment by yuwata** [comment]
Thank you for the log. The log does not contain "move" action for `kli` interface... Is it a kernel bug? Or, the kernel never emit move event when an interface is renamed multiple times?? Hmm...

**Comment by yuwata** [comment]
At least with 5.18.19-100.fc35.x86_64, the kernel emits move event correctly:
```
$ sudo ip link add hoge type dummy
$ sudo ip link set hoge name foo
$ sudo ip link set foo name aaa
$ sudo ip link set aaa name bbb
```
then,
```
$ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[398825.789063] add      /devices/virtual/net/hoge (net)
KERNEL[398825.789231] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
KERNEL[398825.789325] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
UDEV  [398826.133168] add      /devices/virtual/net/hoge (net)
UDEV  [398826.175998] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
UDEV  [398826.238852] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
KERNEL[398881.845480] move     /devices/virtual/net/foo (net)
UDEV  [398882.103716] move     /devices/virtual/net/foo (net)
KERNEL[398894.228735] move     /devices/virtual/net/aaa (net)
UDEV  [398894.482348] move     /devices/virtual/net/aaa (net)
KERNEL[398923.620202] move     /devices/virtual/net/bbb (net)
UDEV  [398923.879779] move     /devices/virtual/net/bbb (net)
```

**Comment by yuwata** [comment]
@d4nuu8 Let me confirm, the provided udevd log is not edited, right? I.e. `move` event is not dropped from the log.

**Comment by yuwata** [comment]
@d4nuu8 Also, please try to manually rename the device like the above with running `udevadm monitor` on another terminal.

**Comment by d4nuu8** [comment]
@yuwata 

> Let me confirm, the provided udevd log is not edited, right? I.e. move event is not dropped from the log.

I only removed some internal version information and replaced them by `***`. But no complete lines has been removed.

> Also, please try to manually rename the device like the above with running udevadm monitor on another terminal.

```bash
$ ip link add hoge type bridge  # We do not have enabled the dummy device
$ ip link set hoge name foo
$ ip link set foo name aaa
$ ip link set aaa name bbb
```
```bash
$ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[646.059967] add      /devices/virtual/net/hoge (net)
KERNEL[646.060002] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
KERNEL[646.060014] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
UDEV  [646.072049] add      /devices/virtual/net/hoge (net)
UDEV  [646.073326] add      /devices/virtual/net/hoge/queues/rx-0 (queues)
UDEV  [646.074308] add      /devices/virtual/net/hoge/queues/tx-0 (queues)
KERNEL[654.924417] move     /devices/virtual/net/foo (net)
UDEV  [654.950463] move     /devices/virtual/net/foo (net)
KERNEL[662.636028] move     /devices/virtual/net/aaa (net)
UDEV  [662.658595] move     /devices/virtual/net/aaa (net)
KERNEL[669.587760] move     /devices/virtual/net/bbb (net)
UDEV  [669.610540] move     /devices/virtual/net/bbb (net)
```

I exported a complete journal matching the already uploaded ones, too. I can provide this, too. But I would prefer to not upload this for everybody.

BTW, the exact kernel version is `5.10.109` with Debian patches applied.

**Comment by yuwata** [comment]
Could you test the same renaming test with monitoring with the real interface, enp4s0 or so?

**Comment by d4nuu8** [comment]
I removed the networkd configuration files, restarted and run:

```bash
$ ip link set enp4s0 name foo
$ ip link set foo name aaa
$ ip link set aaa name bbb
```

```bash
$ udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[101.231443] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/foo (net)
UDEV  [101.251174] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/foo (net)
KERNEL[109.868599] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/aaa (net)
UDEV  [109.891135] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/aaa (net)
KERNEL[114.756861] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/bbb (net)
UDEV  [114.783265] move     /devices/pci0000:00/0000:00:1c.7/0000:04:00.0/net/bbb (net)
```

Is that what you need @yuwata ?

I've just discovered that a `networkctl reconfigure kli` is causing the renaming to be completed.

**Comment by d4nuu8** [comment]
With a downgrade of systemd to version `247.3-7+deb11u1` I was not able reproduce this anymore.

**Comment by yuwata** [comment]
@d4nuu8 Hopefully, PR #25143 should fix the issue. If possible, please test the PR.

**Comment by d4nuu8** [comment]
I applied the patch to the version of [Debian Bullseye (backports)](https://salsa.debian.org/systemd-team/systemd/-/tree/debian/bullseye-backports) which needed some adjustments.

I wasn't able to reproduce this within approx. 75 reboot cycles.

I'm going to let this run over the long weekend in Germany. So final results will be here on Wednesday. :wink:

[0001-Applied-patch.patch.txt](https://github.com/systemd/systemd/files/9889353/0001-Applied-patch.patch.txt)

**Comment by d4nuu8** [comment]
`13254` reboot cycles without error :+1: 

Thanks for fixing this @yuwata !
