### ISSUE TITLE
still have wall messages

### ISSUE THREAD

**Issue by Firestar-Reimu** [systemd/systemd#24971]
### systemd version the issue has been seen with

251.5

### Used distribution

Archlinux

### Linux kernel version used

6.0.0-arch-1.1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

> systemd 251.2 removes wall messages from suspend

https://github.com/systemd/systemd/pull/23574

### Unexpected behaviour you saw

but now it is  systemd 251.5-1 and I still can see `The system is going down for poweroff/reboot NOW!`

I set (I use KDE) systemsettings >> Login Screen (SDDM) >> Behaviour >>

Halt command: /usr/bin/systemctl poweroff --no-wall
Reboot command: /usr/bin/systemctl reboot --no-wall

do not work

but I run  `poweroff --no-wall` and `reboot --no-wall` from terminal can close wall messages

**Comment by Firestar-Reimu** [comment]
> where do you see those messages?

after reboot/shutdown

![1](https://github.com/systemd/systemd/assets/65082432/6e7f439e-9cd4-4ecc-9a48-349ed450621a)


https://github.com/systemd/systemd/assets/65082432/bfd1d687-b194-4c0e-b55a-d1d7a39e86bc

**Comment by Firestar-Reimu** [comment]
I will see https://bbs.archlinux.org/viewtopic.php?pid=2103947

**Comment by poettering** [comment]
that suggests you were logged in locally on a tty?

**Comment by Firestar-Reimu** [comment]
yes, locally on tty1

**Comment by poettering** [comment]
Sure, then everything is in order and working as expected.

**Comment by Firestar-Reimu** [comment]
But if I do not want the broadcast messages + watchdog + spi_nor, what can I do?

**Comment by poettering** [comment]
> But if I do not want the broadcast messages 

log out from the relevant tty

> watchdog + spi_nor, what can I do?

complain to kernel people or bump the cutoff log level to the console. but that's not really a systemd thing

**Comment by Kir-Antipov** [comment]
For everybody coming here from Google, here's what you want:

```sh
busctl set-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager EnableWallMessages b false
```

This command will disable those useful wall messages, which should absolutely be turned on by default and are not annoying in the slightest. However, the change is not permanent. In order to make it permanent, you can create a simple systemd service like this:

```properties
[Unit]
Description=Disable systemd wall messages

[Service]
ExecStart=/usr/bin/busctl set-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager EnableWallMessages b false

[Install]
WantedBy=multi-user.target
```

I created a very small repo to help my future self quickly set this up on any system I use. However, feel free to use - https://github.com/Kir-Antipov/disable-systemd-wall-messages :)

**Comment by Firestar-Reimu** [comment]
> you can create a simple systemd service like this

where do I put this file? Thanks!

**Comment by Kir-Antipov** [comment]
I have already outlined all the steps in my repository, but to reiterate:

1) Create `/etc/systemd/system/disable-systemd-wall-messages.service`
2) Start it via `systemctl start disable-systemd-wall-messages.service` to verify that everything is functioning correctly
3) Finally, enable it via `systemctl enable disable-systemd-wall-messages.service`

**Comment by Orlha** [comment]
> I have already outlined all the steps in my repository, but to reiterate:
> 
>     1. Create `/etc/systemd/system/disable-systemd-wall-messages.service`
> 
>     2. Start it via `systemctl start disable-systemd-wall-messages.service` to verify that everything is functioning correctly
> 
>     3. Finally, enable it via `systemctl enable disable-systemd-wall-messages.service`

I'm having `Invalid object path: /org/freedesktop/login1.Manager`
