### ISSUE TITLE
test-process-util and test-cgroup fail in Portage pid-sandbox environment

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#25015]
### systemd version the issue has been seen with

252-rc1

### Used distribution

Gentoo

### Linux kernel version used

5.15.70

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Passing tests.

### Unexpected behaviour you saw

```
Summary of Failures:

 514/1069 systemd:test / test-process-util  FAIL   0.24s   killed by signal 6 SIGABRT
 579/1069 systemd:test / test-cgroup        FAIL   0.15s   killed by signal 6 SIGABRT

Ok:                 1046
Expected Fail:      0   
Fail:               2   
Unexpected Pass:    0   
Skipped:            21  
Timeout:            0   
```
Full output of failing tests:
[test-process-util](https://gist.github.com/floppym/cead21e191cb7b2c7d1eeb55f7dd8a72)
[test-cgroup](https://gist.github.com/floppym/2395ce1849c6bdd78e63f76e27270a47)

### Steps to reproduce the problem

Run tests on Gentoo within Portage build environment with pid-sandbox enabled.
```
FEATURES="pid-sandbox test" emerge sys-apps/systemd
```
The pid-sandbox feature runs the build process inside a PID namespace, with a python-based helper script acting as PID 1.

I am happy to help further diagnose the issue with guidance on any further information that is required.

**Comment by floppym** [comment]
The relevant part of test-process-util:
```
        if (!detect_container())
                assert_se(get_ctty_devnr(pid, &h) == -ENXIO || pid != 1);
```
A possible solution would be to alter Portage so that `detect_container` returns non-zero. In other words, make Portage look more like a full container manager.

**Comment by poettering** [comment]
if you open a pid namespace your are a container manager. And vice versa. It's the key namespace type that constitutes a container manager.

Just set $container=portage as env var in your build process. But honestly, portage should just set that on its own.

if we could detect pid namespace use, we would. But there's no mechanism known to us that was better than a heuristic. Hence the $container thing. 

Anyway, I am pretty sure we should just close this: we have all the right conditionalizations in place, except that we can't properly test for anything since portage basically gives us a frankencontainer environment that is a container manager, but also isn't.

**Comment by floppym** [comment]
Alright. Do you think that will also resolve the problem with test-cgroup?

**Comment by poettering** [comment]
no idea. try it out. strace the test for the errno the test sees

**Comment by floppym** [comment]
Setting `container=portage` in the environment does not work.

The `detect_container` function checks for `container` in the environment of PID 1. If the current process is not PID 1, it attempts to read /proc/1/environ.

The python script acting as PID 1 runs as root. The build process runs as the user "portage". Therefore, the build process does not have access to read /proc/1/environ.

**Comment by floppym** [comment]
For test-cgroup, I applied this patch:
```
--- a/src/test/test-cgroup.c
+++ b/src/test/test-cgroup.c
@@ -62,6 +62,7 @@ TEST(cg_create) {
         log_info("Paths for test:\n%s\n%s", test_a, test_b);
 
         r = cg_create(SYSTEMD_CGROUP_CONTROLLER, test_a);
+        log_info_errno(r, "cg_create returned %d (%m)", r);
         if (IN_SET(r, -EPERM, -EACCES, -EROFS)) {
                 log_info_errno(r, "Skipping %s: %m", __func__);
                 return;
```
This results in the following output:
```
================================== 575/1069 ==================================
test:         systemd:test / test-cgroup
start time:   17:05:03
duration:     0.12s
result:       killed by signal 6 SIGABRT
command:      SYSTEMD_LANGUAGE_FALLBACK_MAP=/x/portage/sys-apps/systemd-252_rc1/work/systemd-252-rc1
/src/locale/language-fallback-map MALLOC_PERTURB_=68 PATH=/x/portage/sys-apps/systemd-252_rc1/work/s
ystemd-252-rc1-abi_x86_64.amd64:/x/portage/sys-apps/systemd-252_rc1/temp/python3.11/bin:/usr/lib/cca
che/bin:/home/floppym/src/portage/bin/ebuild-helpers/xattr:/home/floppym/src/portage/bin/ebuild-help
ers:/usr/sbin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/15/bin /x/po
rtage/sys-apps/systemd-252_rc1/work/systemd-252-rc1-abi_x86_64.amd64/test-cgroup
----------------------------------- stderr -----------------------------------
/* test_cg_create */
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Paths for test:
e/test-a
e/test-b
cg_create returned -2 (No such file or directory)
Assertion 'r == 1' failed at src/test/test-cgroup.c:71, function test_cg_create(). Aborting.
==============================================================================
```
It seems cg_create is returning `-ENOENT`.

**Comment by floppym** [comment]
Here's the [strace output](https://gist.github.com/floppym/03d1a493c9bcbc56f79e64ed0b1e8ff4) for test-cgroup.

**Comment by poettering** [comment]
your payload is more privileged than the container manager? that's just weird...

**Comment by floppym** [comment]
I'm not sure what you mean by that.

**Comment by poettering** [comment]
my educated guess regarding the cgroup test is that the frankencontainer manager you are having there sets up a cgroup namespace, but doesn't mount cgroupfs from inside the cgroup namespace, and thus the data from /proc/$PID/cgroup in the container and /sys/fs/cgroup match up.

Quite frankly, can't you just disable the tests? I am not sure it's worth testing anything in such a broken environment.

systemd makes certain assumptions when running in a container, which are documented here: https://systemd.io/CONTAINER_INTERFACE

If the container manager you are reimplementing there doesn't even follow the most superficial rules of that I am pretty sure we shouldn't support that and just skip the tests.

**Comment by poettering** [comment]
the detect virt logic also looks at `/run/host/container-manager` btw in addition to $container, due to the permission issues. The idea is that container managers can pass through all kinds of things via `/run/host/`, and one of them is this.

**Comment by floppym** [comment]
Portage isn't a container manager and doesn't aim to be. It (optionally) uses namespaces to isolate package builds. I don't think the assertion that any program that uses Linux namespaces is a "container manager" is valid.

The failure in test-process-util seems to due to an assumption that PID 1 will never have a controlling tty, which is not valid if PID 1 isn't systemd.

> my educated guess regarding the cgroup test is that the frankencontainer manager you are having there sets up a cgroup namespace

Portage does not create a separate cgroup namespace.

Anyway, if you don't want to help me debug this, feel free to close the issue; it doesn't have an major impact. Our systemd ebuild script already warns that that test failures can be expected when the pid-sandbox feature is enabled.

**Comment by poettering** [comment]
anyway, i am not sure we need to try accomodate for every homegrown incomplete container execution engine (regardless if portage calls it that, or not, it is one because it uses pid + mount namespacing). I don't think we really need to fix anything here.

**Comment by bluca** [comment]
The common understanding of what a "container manager" is, is Docker. Random scripts using a couple namespaces are not container managers. Unit tests need to work in package build systems, otherwise it's a bug in the unit test. @floppym please try again from latest main, if it still doesn't work we can add more fixes.

**Comment by floppym** [comment]
@bluca Thanks. The problems have mostly been fixed. There's just one part of test-process-util that we need to patch out.

https://github.com/gentoo/gentoo/blob/08925ddd173f638b78303c4c958d4c98a41c60d6/sys-apps/systemd/files/systemd-test-process-util.patch

The issue is that the test expects PID 1 to have no controlling terminal.
With the pid-sandbox feature enabled, Portage's stub init process does have a controlling terminal.

**Comment by bluca** [comment]
deetect_container should be able to detect your stub pid1 now, have you tried from the very latest main without that patch?

**Comment by floppym** [comment]
Ok, this is indeed fixed on main.

**Comment by solardiz** [comment]
Per the comments here, the `test-process-util` issue was apparently fixed by changes to `detect_container`, which it calls. However, I don't see anything that would have fixed the `test-cgroup` issue. I've just created PR #38158 to fix it as well.
