### ISSUE TITLE
Mount efivarfs read-only

### ISSUE THREAD

**Issue by orbea** [systemd/systemd#2503]
This is not a duplicate, this issue is still relevant and worth commenting on.  I would post on the previous issues, but puttering has unfortunately locked them so many can add any potentially useful information to them.

So here it is again, please do not lock important issues Poettering before you resolve them, thanks!

"Mounting efivarfs read/write by default can lead to accidental deletion of the EFI variables. It was already reported on Arch Linux forums, that running 'rm -rf' over a directory structure with mounted efivarfs did actually "hard-brick" some MSI notebook."

Serious question, when and how will this be fixed so that users do not accidentally brick their computers?

Here are the previous issues for additional information, its kind of silly they have to be split up like this.
https://github.com/systemd/systemd/issues/2402
https://github.com/systemd/systemd/issues/2502

**Comment by poettering** [comment]
Please find another place to troll. This is not the place. Please ask the firmware vendors to fix their issues, or the kernel folks to mask the broken firmware (which mjg59 already posted a patch for, btw, and he took the blame for the whole thing anyway, so you are seriously barking up the wrong tree here). systemd is simply not the right place to work around hardware brokeness. It never was, it never will be. Furthermore systemd components need write access to the EFI fs, hence mount it writable. 

And now, for christ's sake, stop trolling here. Find another place.
