### ISSUE TITLE
Enable OpenSSF Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [systemd/systemd#25042]
### Is your feature request related to a problem? Please describe

Hi, I am Joyce from Google and I'm working on behalf of the [Open Source Security Foundation][ossf] to help essential open-source projects improve their supply-chain security. Considering how systemd is relevant to countless projects, I want to offer my support to improve the project's supply-chain security. 

According to [Open Source Security and Risk Analysis Report](https://www.synopsys.com/software-integrity/resources/analyst-reports/open-source-security-risk-analysis.html?intcmp=sig-blog-ossra1), 84% of all codebases have at least one vulnerability, with an average of 158 per codebase. The majority have been in the code for more than 2 years and have documented solutions available.

Even in large tech companies, the tedious process of reviewing code for vulnerabilities falls down the priority list, and there is little insight into known vulnerabilities and solutions that companies can draw on.

That’s where the OpenSSF [Scorecards][sc] tool is helping. The tool's focus is to help maintainers understand their project's security posture and assess the risks that dependencies could introduce.

[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard

### Describe the solution you'd like

The tool I want to suggest here is the [Scorecards][sc]. Scorecards runs dozens of automated security [checks][checks] to help maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

To make maintainers' lives easier, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha]. It is very lightweight and runs on every change to the repository's main branch. The results of its checks are available on the project's [security dashboard](https://github.com/systemd/systemd/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. This Action has been adopted by 1800+ projects already, having some prominent users like [Tensorflow][tensorflow], [Angular][angular], [Flutter][flutter], [sos.dev][sos-dev] and [deps.dev][deps-dev].

As I've seen in the systemd project, you scored extremely high, being on top 0.1%! Congratulations to all the team for all the work to improve the overall security of the project, such as implementing the OpenSSF Security Best Practices, OSS-Fuzzing, Security Policy, etc.

Considering this scenario, the scorecard action and badge would be a great way to show all your commitment to security posture and also guarantee that future changes on the project won't affect negatively the project's security posture, or even improve even more the security posture of the project.

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

In case of doubts or concerns you can try to check [Scorecards FAQ][FAQ]. Anyway, feel free to reach me out.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[checks]: https://github.com/ossf/scorecard#scorecard-checks
[sc-gha]: https://github.com/ossf/scorecard-action
[FAQ]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

[tensorflow]: https://github.com/tensorflow/tensorflow
[Angular]: https://github.com/angular/angular  
[Flutter]: https://github.com/flutter/flutter 
[sos-dev]: https://sos.dev/ 
[deps-dev]: https://deps.dev/

**Comment by bluca** [comment]
Hi, thanks for taking the time to post this

> Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) with the project's score to be added to its README.

Sounds interesting to me, as long as it's not invasive - do you have an example of an existing project doing this to look at?

**Comment by joycebrum** [comment]
> Hi, thanks for taking the time to post this
> 
> > Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) with the project's score to be added to its README.
> 
> Sounds interesting to me, as long as it's not invasive - do you have an example of an existing project doing this to look at?

I have some PR openned in https://github.com/mihaimaruseac/hindent/pull/595 and an example of a project that have asked for the "minimum features" https://github.com/ethereum/solc-js/pull/667

**Comment by evverx** [comment]
As far as I understand GOOST is responsible for this stuff so it would be great if someone could help with https://github.com/google/oss-fuzz/issues/10090#issuecomment-1526486276

**Comment by evverx** [comment]
https://github.com/ossf/scorecard/issues/2018#issuecomment-1325431983 was supposed to be addressed in Q1 (which ended a month ago). I suspect it's safe to assume that those issues aren't going to be fixed.

**Comment by joycebrum** [comment]
> As far as I understand GOOST is responsible for this stuff so it would be great if someone could help with [google/oss-fuzz#10090 (comment)](https://github.com/google/oss-fuzz/issues/10090#issuecomment-1526486276)

About this, AFAIK it is not a problem to grant write permission to security-events to oss-fuzz because in the scorecard documetation https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions it says it can be granted to "recognized action for uploading SARIF results." and the oss-fuzz certainly will be the case. 

Thus, I think we don't need to worry about that.

**Comment by joycebrum** [comment]
About the false positives: have you tried using the "dismiss alert" github function?
<img width="427" alt="image" src="https://user-images.githubusercontent.com/22223372/236285631-bd42a5dc-244f-4aeb-9d8d-5c3368e7f860.png">

I though it should dismiss the alert automatically even in future runs in order to preventing you for being notified over a already dismissed alert. If you tried, does it not work?

This way the action would be useful on only notifying you about real possible fix/improvements and not bothering you with the "false positive" ones.

**Comment by joycebrum** [comment]
> I'm not sure about that. systemd has been "insecure" because of CIFuzz/CFLite (provided by OSS-Fuzz) for more than a year

Unfortunately it reports not pinned by hash even for oss-fuzz (we've discussed some possible solutions with both teams this week), but I believe that's not the case for token permissions at least. It would allow a security-event write and, if not, it definetly should.

**Comment by evverx** [comment]
> have you tried using the "dismiss alert" github function?

I think it was discussed somewhere and I think that maintainers shouldn't waste their time on that. Those are obvious false positives that should be fixed by scorecard.

Anyway I opened https://github.com/systemd/systemd/pull/27530.

**Comment by bluca** [comment]
> About the false positives: have you tried using the "dismiss alert" github function? <img alt="image" width="427" src="https://user-images.githubusercontent.com/22223372/236285631-bd42a5dc-244f-4aeb-9d8d-5c3368e7f860.png">
> 
> I though it should dismiss the alert automatically even in future runs in order to preventing you for being notified over a already dismissed alert. If you tried, does it not work?
> 
> This way the action would be useful on only notifying you about real possible fix/improvements and not bothering you with the "false positive" ones.

Yes we've already dismissed the non-useful ones, so this is not a really a problem, and it flagged a few improvements that were then made. Human-readable scorecard would be really good to have though, so please do update us when that's coming. Thanks!

**Comment by evverx** [comment]
> it flagged a few improvements that were then made

Which ones? The only thing it could have flagged was that unmaintained release action that can't even handle releases properly: https://github.com/systemd/systemd/pull/27209#issuecomment-1533567944.

**Comment by evverx** [comment]
Speaking of that release action looks like scorecard could actually flag it if something like https://github.com/ossf/scorecard-action/issues/1107 was implemented close to scorecard-action.

Anyway I'm still curious. What exactly did it flag and what was improved because of that?

**Comment by evverx** [comment]
Apparently it doesn't even flag those unsigned releases: https://github.com/ossf/scorecard/issues/2763#issuecomment-1536597473. systemd should get its well-deserved 0 there.

**Comment by evverx** [comment]
> I though it should dismiss the alert automatically even in future runs in order to preventing you for being notified over a already dismissed alert

I took a look at the security dashboard and as far as I can see the same alerts pop up over and over again (regardless of whether they are dismissed or not). I'm not sure who exactly keeps "fixing" them but the right fix for "differential-shellcheck" at least is to add it to the list of legit code scanning tools (which was discussed in https://github.com/google/oss-fuzz/issues/10090#issuecomment-1526486276):
![Screenshot 2023-05-07 at 15 47 10](https://user-images.githubusercontent.com/10195800/236678653-ef414aea-404d-49a4-b8a6-ba4cb8ecd0d8.png)

**Comment by evverx** [comment]
More generally alerts like that were supposed to be addressed in https://github.com/ossf/scorecard/issues/2338 but it was apparently half-implemented and then abandoned.

**Comment by evverx** [comment]
Some issues got reopened and hopefully should be addressed in the foreseeable future.

https://github.com/ossf/scorecard/issues/2979 was just opened (the timing is amazing I must say) and should bring human-readable dashboards like https://clomonitor.io/scorecard?platform=github.com&org=systemd&repo=systemd&theme=light. (those dashboards would be much useful without false positives and false negatives though).

The PR where support for PRs is discussed hasn't been updated yet.

**Comment by evverx** [comment]
@joycebrum I'm not sure when the dashboard should be officially released but since I think you probably participate in scorecard meetings (where everything is decided/announced as far as I understand) could you open a PR pointing the badge to that official dashboard once it officially lands?

I think it should also be possible to remove the SARIF part of the action to prevent scorecard from producing the false positives in the security tab over and over again. Its "security-events" permissions can be dropped too. The SARIF part would make sense if the action could be run on PRs though to be able to get diffs but it seems it isn't going to happen any time soon.

Also it seems Dependabot doesn't bump versions embedded in comments when at least one workflow doesn't embed them: https://github.com/systemd/systemd/commit/43a221473c9b24815a5a0a30d2464f307728e7f5#diff-649a84adf982ddf68273f1bb0de882a20e97b06632b5432a6a1504a3f23cb2e6. I think either the comments should be removed or all the workflows should be updated.

Anyway I'll go ahead and close https://github.com/systemd/systemd/pull/27530 for now. The false positives should be addressed in the foreseeable future hopefully.

**Comment by joycebrum** [comment]
Sure @evverx ! I'll open a PR updating the badge once it is released!

About the dependabot I think it should be `actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.0.0` to work
