### ISSUE TITLE
Build failure with clang

### ISSUE THREAD

**Issue by elkrejzi** [systemd/systemd#2504]
When building with clang-3.8.0rc1, with the latest systemd git I get the following error:

src/resolve/dns-type.c:251:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^
src/resolve/dns-type.c:260:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^
src/resolve/dns-type.c:270:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^

**Comment by poettering** [comment]
clang is stupid. It doesn't notice that our switch() statements contains case statements for all values of the used type. 

Will prep a work-around, but this is actually something clang should really fix themselves. Would be great if you could file a bug there, linking the code in question.
