### ISSUE TITLE
meson configure fails "Atomic builtin requires -latomic" test with new clang

### ISSUE THREAD

**Issue by mattst88** [systemd/systemd#25057]
### systemd version the issue has been seen with

251.6

### Used distribution

Gentoo

### Linux kernel version used

5.15.69-gentoo-dist

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Downstream bug: https://bugs.gentoo.org/877259

Context: Clang has made the choice to turn on `-Werror=implicit-function-declaration,implicit-int` (See Gentoo's tracker bug: https://bugs.gentoo.org/870412). That is, implicit function declarations will be an error in clang-16.

Added in commit 132c73b57ad1d363e97e1f4720f0e920826f34e1, systemd now does a check to see if libatomic is needed with some compile/link tests with e.g. `__atomic_exchange_1`, but the tests don't provide a prototype for `__atomic_exchange_1` so with clang-16 the test fails, breaking the build.

I've looked, and I don't see that either gcc or clang provide a header for `__atomic_*` built-in functions, so I'm not sure what the appropriate fix is.

cc: @xypron in case they have some idea.

**Comment by medhefgo** [comment]
Honestly, this should be reported to clang. The point of a builtin is that it's provided by the compiler itself and needs no header to be available. Yes, the generated code may call out to a function that may need linking to an external library, but that is a different matter.

**Comment by Arfrever** [comment]
A potential alternative is to not directly check for `__atomic_exchange_1`, but only check for libatomic library, and use it with `--as-needed` option, which defers decision about whether it is actually needed to linker.
```
-Wl,--push-state,--as-needed,-latomic,--pop-state
```

**Comment by medhefgo** [comment]
Actually, `--as-needed` is always turned on by meson, so that wouldn't even be necessary.

**Comment by xypron** [comment]
Commit https://github.com/systemd/systemd/commit/132c73b57ad1d363e97e1f4720f0e920826f34e1 introduced a test code which if it cannot be compiled and linked causes latomic to be added to the dependencies.

From what I read above I would assume:

- LLVM never provided the symbol _atomic_exchange_1. So when using Clang/LLVM said test would fail and latomic would be added.
- With -Wno-implicit-function-declaration for Clang builds the test will still fail and latomic will still be added.

What exactly is the problem?

**Comment by thesamesam** [comment]
> Commit [132c73b](https://github.com/systemd/systemd/commit/132c73b57ad1d363e97e1f4720f0e920826f34e1) introduced a test code which if it cannot be compiled and linked causes latomic to be added to the dependencies.
> 
> From what I read above I would assume:
> 
>     * LLVM never provided the symbol _atomic_exchange_1. So when using Clang/LLVM said test would fail and latomic would be added.
> 
>     * With -Wno-implicit-function-declaration for Clang builds the test will still fail and latomic will still be added.
> 
> 
> What exactly is the problem?

As per the linked Gentoo bug, one gets:
```
Program tools/choose-default-locale.sh found: YES (/var/tmp/portage/sys-apps/systemd-utils-251.6/work/systemd-stable-251.6/tools/choose-default-locale.sh)
Checking if "Atomic builtin requires -latomic" : links: NO 

../systemd-stable-251.6/meson.build:1002:8: ERROR: C shared or static library 'atomic' not found
```

**Comment by xypron** [comment]
LLVM build scripts use a symbol HAVE_CXX_ATOMICS_WITHOUT_LIB. So when building with clang I guess we need to check this instead of the compile test that works for gcc.

**Comment by thesamesam** [comment]
> 

Can you provide a link to the current repo? That one was archived a while back.

**Comment by xypron** [comment]
https://llvm.org/docs/Atomics.html#libcalls-atomic describes __atomic_exchange_1() as supported.

Here is LLVMs code to check for atomics:
[llvm/cmake/modules/CheckAtomic.cmake](https://github.com/llvm/llvm-project/blob/main/llvm/cmake/modules/CheckAtomic.cmake)
