### ISSUE TITLE
journal: Incorrect interaction between -n and -u for specific journal files

### ISSUE THREAD

**Issue by mvollmer** [systemd/systemd#25063]
### systemd version the issue has been seen with

251

### Used distribution

Arch

### Linux kernel version used

5.19.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

See below, describing unexpected behavior is easier.

### Unexpected behaviour you saw

Running `journalctl -n 1000 -u NetworkManager` with specific journal files produces only a subset of the expected lines.  I attach those files as `bad.tar.gz`.

There are two files.  The first contains 37 lines for -u NetworkManager:

```
# journalctl --file system@66b132a6f2ba46188d51022994bce81a-0000000000000693-0005eb5e85877c50.journal -u NetworkManager | wc -l
37
```

The second contains 84 lines:

```
# journalctl --file system.journal -u NetworkManager | wc -l
84
```

So together that is 122 lines. :-)

```
# journalctl -D . -u NetworkManager | wc -l
122
```

We can output the last couple of lines, which will come from the second file:

```
# journalctl -D . -u NetworkManager -n 50 |  wc -l
50
```

Now comes the unexpected part.  If we ask for more than 84 lines with `-n`, we only get lines from the first file:

```
# journalctl -D . -u NetworkManager -n 84 |  wc -l
84
# journalctl -D . -u NetworkManager -n 85 |  wc -l
1
```

The journal files have been written by systemd 251, and the behavior described above occurs when reading them with both journalctl from both 250 and 251. SO I guess the problem is in writing part, not the reading part.

Similar files written by systemd 250 seem to show the expected behavior. I will try to make some that are very similar to the problematic ones and attach them as well.

[bad.tar.gz](https://github.com/systemd/systemd/files/9818865/bad.tar.gz)

### Steps to reproduce the problem

See unexpected behavior.  I am not sure how to reproduce writing the problematic files, hopefully it is enough to find the exact problem with them.

**Comment by mvollmer** [comment]
Here is a look without using `-u`:

```
$ journalctl --file system.journal | wc -l
1682
$ journalctl -D . -n 1682 | wc -l
1683
$ journalctl -D . -n 1700 | wc -l
1701
```

The extra line printed by `journalctl -D . -n 1682 | wc -l`  is actually the last line of the first journal file.  This is also kinda unexpected, but it is not suppressing any lines, so *shrug*.

**Comment by mvollmer** [comment]
Here are two journal files produced by systemd 250 on Fedora 36 by (almost) the same CI test.  For unknown reasons running the test ordinarily produces only one file (`system.journal`).  I have added a artificial `journalctl --rotate` at the start of the test run to get two file. So maybe this isn't at all similar to what has happened on Arch in the original description above...

```
$ journalctl --file system@087c40d2821d4d22902080bcde329dc6-0000000000000e3d-0005eb5fc172d6e4.journal -u NetworkManager | wc -l
67
$ journalctl --file system.journal -u NetworkManager | wc -l
45
$ journalctl -D . -u NetworkManager | wc -l
112
$ journalctl -D . -u NetworkManager -n 45 | wc -l
45
$ journalctl -D . -u NetworkManager -n 46 | wc -l
46
```

[good.tar.gz](https://github.com/systemd/systemd/files/9819290/good.tar.gz)

**Comment by mvollmer** [comment]
Oh, and when you add `-r` in the bad case, you get this:

```
$ journalctl -D . -u NetworkManager -r -n 84 |  wc -l
84
$ journalctl -D . -u NetworkManager -r -n 85 |  wc -l
86
```

So no lines are omitted this time.  The extra line is a "-- Boot" marker, so that is also expected.

**Comment by mrc0mmand** [comment]
There was a _lot_ of work done in journalctl for the past couple of releases and it looks like the issue is now gone, at least with the provided logs:

```bash
#!/bin/bash

set -eux

for i in {0..121}; do
    [[ $(~/repos/@systemd/systemd/build/journalctl -D . -u NetworkManager -n "$i" -q | wc -l) -eq $i ]]
    [[ $(~/repos/@systemd/systemd/build/journalctl -D . -u NetworkManager -r -n "$i" -q | wc -l) -eq $i ]]
    echo "$i: GOOD"
done
```

```
$ ./repro.sh 
$ ./repro.sh 
+ for i in {0..121}
++ /home/mrc0mmand/repos/@systemd/systemd/build/journalctl -D . -u NetworkManager -n 0 -q
++ wc -l
+ [[ 0 -eq 0 ]]
++ /home/mrc0mmand/repos/@systemd/systemd/build/journalctl -D . -u NetworkManager -r -n 0 -q
++ wc -l
+ [[ 0 -eq 0 ]]
+ echo '0: GOOD'
...
+ [[ 121 -eq 121 ]]
++ /home/mrc0mmand/repos/@systemd/systemd/build/journalctl -D . -u NetworkManager -r -n 121 -q
++ wc -l
+ [[ 121 -eq 121 ]]
+ echo '121: GOOD'
121: GOOD
```
