### ISSUE TITLE
networkctl reload with bond devices causes slaves to go DOWN and UP, causung few seconds of network loss

### ISSUE THREAD

**Issue by Garagoth** [systemd/systemd#25067]
### systemd version the issue has been seen with

249 (249.11-0ubuntu3.6)

### Used distribution

Ubuntu 22.04.1 LTS

### Linux kernel version used

5.15.0-52-generic

### CPU architectures issue was seen on

x86_64

### Component

networkctl, systemd-networkd

### Expected behaviour you didn't see

Network is not iterrupted

### Unexpected behaviour you saw

After `netplan generate` creates config files (when their contents do not change, just timestamps get updated) for networkd - or simply by doing `touch /run/systemd/network/*`, running `networkctl reload` always causes network loss by bringing down and up all bond slave interfaces.

Does not happen when bond is not present.
Seems very similar to already closed in 2018 issue: https://github.com/systemd/systemd/issues/10118

### Steps to reproduce the problem

Create network config with one ethernet and one bond interace on it. Assign IP to bond interface.
Configure network, make sure it works.
Then:
`touch /run/systemd/network/*`
`networkctl reload`
Observe network loss and DOWN messages in `journalctl -xe`:
```
Oct 19 13:13:40 test systemd-networkd[691]: ens192: Re-configuring with /run/systemd/network/10-netplan-n1p1.network
Oct 19 13:13:40 test systemd-networkd[691]: bond_all: Re-configuring with /run/systemd/network/10-netplan-bond_all.network
Oct 19 13:13:40 test systemd-networkd[691]: ens192: Link DOWN
Oct 19 13:13:40 test systemd-networkd[691]: ens192: Lost carrier
Oct 19 13:13:40 test systemd-networkd[691]: ens192: Link UP
Oct 19 13:13:40 test kernel: vmxnet3 0000:0b:00.0 ens192: intr type 3, mode 0, 5 vectors allocated
Oct 19 13:13:40 test kernel: vmxnet3 0000:0b:00.0 ens192: NIC Link is Up 10000 Mbps
Oct 19 13:13:40 test systemd-networkd[691]: ens192: Gained carrier
```

/run/systemd/network/10-netplan-n1p1.network:
```
[Match]
Name=ens192

[Network]
LinkLocalAddressing=no
Bond=bond_all
```

/run/systemd/network/10-netplan-bond_all.network:
```
[Match]
Name=bond_all

[Network]
LinkLocalAddressing=ipv6
Address=10.1.1.206/24
DNS=10.1.1.1
ConfigureWithoutCarrier=yes

[Route]
Destination=0.0.0.0/0
Gateway=10.1.1.1
```

**Comment by yuwata** [comment]
Fix is waiting in #25162.
