### ISSUE TITLE
udev, Systemd, and syspath parameter missing.

### ISSUE THREAD

**Issue by silver2row** [systemd/systemd#25062]
### Component

udev rule files

### Is your feature request related to a problem? Please describe

Hello,

My feature request is due to an issue I am currently trying to overcome. udev rules are trying at times. Not so much the more I perform in the udev category of ideas but still trying at times.

```
KERNEL=="sd*", SUBSYSTEMS=="scsi", DEVPATH="/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/host0/target0:0:0/0:0:0:0/block/sda", \
         SYSPATH="/sys/class/block/sda", ATTRS{model}=="USB 2.0 CompactFlash Reader", SYMLINK+="mmcblk*"
```

That is the udev rule on my system for a USB Compact Flash Device via USB Dongle. I am receiving an error that seems missing from my research, i.e. hence why I stopped in to ask questions and for future "improvements."

Anyway, this is the error:

```
syspath parameter missing.
```

I thought adding in the syspath would work. It has not. Workarounds are welcome instead of keeping this issue alive.

Seth

### Describe the solution you'd like

Hello,

I would like to have a clear, concise way of studying udev rules. I know about the man pages and an older book so far. I was thinking of particular tutorials about specifics. I am still discussing tutorials about specifics like USB Compact Flash, GPIO, user permissions and so on.

Seth

### Describe alternatives you've considered

Hello,

I tried to get the udev rule tinkered to the point, I went blind. So, I am going to break and get back to it in a bit.

I also tried:

```
1. sudo udevadm info /dev/sda
2. sudo udevadm info /dev/block/sda
3. sudo udevadm info /dev/class/block/sda
```

Seth

### The systemd version you checked that didn't have the feature you are asking for

247

**Comment by yuwata** [comment]
What is SYSPATH= ? Please try to drop the setting.

Anyway, this is an upstream bug tracker. Closing.

**Comment by silver2row** [comment]
Thank you for your review.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
