### ISSUE TITLE
Some strings are not available for translation on Weblate

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#25071]
### systemd version the issue has been seen with

n/a

### Used distribution

n/a

### Linux kernel version used

n/a

### Steps to reproduce the problem

It looks like that some strings are not available for translation on Weblate (although they do appear on, for example, GNOME Damned Lies). These are the strings:

#: src/hostname/org.freedesktop.hostname1.policy:61
msgid "Get hardware serial number"

#: src/hostname/org.freedesktop.hostname1.policy:62
msgid "Authentication is required to get hardware serial number."

#: src/hostname/org.freedesktop.hostname1.policy:71
msgid "Get system description"

#: src/hostname/org.freedesktop.hostname1.policy:72
msgid "Authentication is required to get system description."

**Comment by AsciiWolf** [comment]
By the way, GNOME Damned Lies seems to have similar problem, but with different strings. These strings appear to be marked as not used anymore (commented out) [on Damned Lies](https://l10n.gnome.org/vertimus/systemd/main/po/cs/):

#: src/core/dbus-unit.c:359
msgid "Authentication is required to start '$(unit)'."
 
#: src/core/dbus-unit.c:360
msgid "Authentication is required to stop '$(unit)'."
 
#: src/core/dbus-unit.c:361
msgid "Authentication is required to reload '$(unit)'."
 
#: src/core/dbus-unit.c:362 src/core/dbus-unit.c:363
msgid "Authentication is required to restart '$(unit)'."
 
#: src/core/dbus-unit.c:535
msgid ""
"Authentication is required to send a UNIX signal to the processes of "
"'$(unit)'."
 
#: src/core/dbus-unit.c:566
msgid "Authentication is required to reset the \"failed\" state of '$(unit)'."
 
#: src/core/dbus-unit.c:599
msgid "Authentication is required to set properties on '$(unit)'."
 
#: src/core/dbus-unit.c:708
msgid ""
"Authentication is required to delete files and directories associated with "
"'$(unit)'."
 
#: src/core/dbus-unit.c:757
msgid ""
"Authentication is required to freeze or thaw the processes of '$(unit)' unit."

**Comment by mrc0mmand** [comment]
I kicked a manual Weblate update and the strings popped up https://translate.fedoraproject.org/browse/systemd/master/cs/?q=state:%3Ctranslated, so it seems to be DTRT.
