### ISSUE TITLE
network: non-independent 'sit' tunnel stays up after underlying interface is taken down

### ISSUE THREAD

**Issue by kpfleming** [systemd/systemd#25102]
### systemd version the issue has been seen with

251.6-1

### Used distribution

Debian testing

### Linux kernel version used

5.19.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Component

networkctl, systemd-networkd

### Expected behaviour you didn't see

Tunnel interface that is enslaved to an underlying interface should be taken down if the underlying interface is taken down.

### Unexpected behaviour you saw

Tunnel interface remained in 'routable' operational status even though underlying interface was in 'off' operational status.

### Steps to reproduce the problem

Create the following files in /etc/systemd/network:

fios.network
```
[Match]
Name=fios

[Link]
ActivationPolicy=manual

[Network]
LinkLocalAddressing=no
IPForward=yes
DHCP=ipv4
```

fios.network.d/tunnel.conf
```
[Network]
Tunnel=hetunnel
```

hetunnel.netdev
```
[NetDev]
Name=hetunnel
Kind=sit
MTUBytes=1480

[Tunnel]
Local=dhcp4
Remote=209.51.161.14
TTL=255
```

hetunnel.network
```
[Match]
Name=hetunnel

[Network]
Address=2001:470:1f06:fab::2/64
Gateway=2001:470:1f06:fab::1
IPForward=yes
```

1. On system startup, `networkctl` shows `fios` as 'off' (because of ActivationPolicy=manual), does not list `hetunnel` at all (this is annoying, but a separate issue).
2. Run `ip link set fios up`.
3. `networkctl` now shows both `fios` and `hetunnel` in 'routable' state.
4. Run `ip link set fios down`.
5. `networkctl` now shows `fios` in 'off' state, but `hetunnel` still in 'routable' state.

**Comment by yuwata** [comment]
Please try to append `BindCarrier=fios` in `hetunnel.network`.

**Comment by kpfleming** [comment]
Sorry for the response delay... took some time to find a maintenance window.

Adding `BindCarrier=fios` resolves the issue.

**Comment by poettering** [comment]
OK, closing then.
