### ISSUE TITLE
Allow specifying or using a persistent primary key when using systemd-cryptenroll

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#25101]
### Is your feature request related to a problem? Please describe

I would like to be able to use TPM2 for disk encryption when i first took ownership of it by setting owner auth value, or generally configured my own hierarchy of keys.

### Describe the solution you'd like

It would be useful to be able to specify the parent key handle for tpm key, or something like that. It is not uncommon that some small number of primary keys are persistent in tpm, I mean mostly the owner hierarchy key. It is probably common that this key has no set auth value, but owner hierarchy has auth value set, which makes current systemd-cryptenroll print an error.

### Describe alternatives you've considered

I have to either not set any auth values at all so that some administrative tpm functions are not protected, or I would have to instead make my own disk encryption service running before systemd-cryptsetup and unsealing/passing the key, which I probably have to do until that is implemented, because the alternative (clevis) doesn't seem to support it, too.

**Comment by poettering** [comment]
With the SRK support added recently, do you need anything else? 

i.e. acbb504eaf1be51572b1c0d0d490ac478bc41c64

**Comment by webczat** [comment]
i am not 100% sure. it's not exactly that it makes it possible for me to specify my own srk, but it seems to use the one that would already be there, which covers my needs. So I think it's enough.
