### ISSUE TITLE
systemd-timesyncd.service dies on autostart

### ISSUE THREAD

**Issue by sergey-safarov** [systemd/systemd#25125]
### systemd version the issue has been seen with

251.5-607

### Used distribution

Fedora 37

### Linux kernel version used

5.19.14-300.fc37.aarch64

### CPU architectures issue was seen on

aarch64

### Component

systemctl, systemd-timesync

### Expected behaviour you didn't see

`systemd-timesyncd.service` should be able automatically to start during server boot.

### Unexpected behaviour you saw

I have enabled `systemd-timesyncd.service` unit autostart but this dies with message
```
[root@localhost ~]# journalctl -flu systemd-timesyncd.service -o cat
systemd-timesyncd.service: Looking at job systemd-timesyncd.service/stop conflicted_by=yes
systemd-timesyncd.service: Looking at job systemd-timesyncd.service/start conflicted_by=no
systemd-timesyncd.service: Fixing conflicting jobs systemd-timesyncd.service/stop,systemd-timesyncd.service/start by deleting job systemd-timesyncd.service/start
systemd-timesyncd.service: Watching D-Bus name 'org.freedesktop.timesync1'.
systemd-timesyncd.service: D-Bus name org.freedesktop.timesync1 now not owned by anyone.
```
And if start unit manually it start properly.

### Steps to reproduce the problem

enable unit autostart on Fedora 37.

**Comment by sergey-safarov** [comment]
Could you also increase loglevel  for these messages?
```
systemd-timesyncd.service: Looking at job systemd-timesyncd.service/stop conflicted_by=yes
systemd-timesyncd.service: Looking at job systemd-timesyncd.service/start conflicted_by=no
systemd-timesyncd.service: Fixing conflicting jobs systemd-timesyncd.service/stop,systemd-timesyncd.service/start by deleting job systemd-timesyncd.service/start
systemd-timesyncd.service: Watching D-Bus name 'org.freedesktop.timesync1'.
systemd-timesyncd.service: D-Bus name org.freedesktop.timesync1 now not owned by anyone.
```

Reason - on the default installation `systemd-timesyncd.service` unit dies silently and needs to add a kernel param to see the reason why the unit dies.

**Comment by sergey-safarov** [comment]
The root of the issue enabled `chronyd.service`.
I have disabled `chronyd.service` start and `systemd-timesyncd.service` automatically starting properly now.

I think required to add `Conflicts=chronyd.service` into the `systemd-timesyncd.service` unit file.

**Comment by poettering** [comment]
You canot run two NTP services in parallel. Pick one. Given that chrony is a full NTP implementation and timesyncd only implement SNTP I am pretty sure chrony should win if both are enabled.

hence, I see nothing actionable here. don't enable two services for NTP and if you do anyway, you'll end up with the more powerful implementaiton. which works as it should really.
