### ISSUE TITLE
systemd preset enables masked DefaultInstance

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#2513]
`systemd preset-all` does funny things, which recently got me locked out from a server. Some units that should have been enabled, got disabled, including `systemd-networkd`.

I haven't found a triggering mechanism I can show to reproduce the problem, but I can reliably reproduce it on one machine, and I am willing to investigate it further when I find the time. Here are the symtoms, tested on arch linux with systemd form master (c5c41f1e57a6):
- preset-all disables a bunch of units, none of which should be disabled according to presets.
  
  ```
  abdo@skynet ~ $ sudo systemctl preset-all
  Removed symlink /etc/systemd/system/getty.target.wants/getty@tty1.service.
  Removed symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service.
  Removed symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
  Removed symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket.
  Created symlink from /etc/systemd/system/getty.target.wants/getty@tty1.service to /usr/lib/systemd/system/getty@.service.
  ```

Here `getty@tty1.service` is initially masked, and a vendor preset in `/usr/lib` reenables it. Maybe a `mask` instruction in presets would be useful, but that is an other story... The other units should not have been touched by `preset-all`.
- all the disabled units are in fact seen as vendor enabled by systemd.
  
  ```
  abdo@skynet ~ $ sudo systemctl status systemd-networkd
  ● systemd-networkd.service - Network Service
  Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: enabled)
  Active: active (running) since Tue 2016-02-02 20:11:57 CET; 3min 12s ago
  ```
- I can run preset specifically for each unit, and it works as expected
  
  ```
  abdo@skynet ~ $ sudo systemctl preset systemd-networkd
  Created symlink from /etc/systemd/system/multi-user.target.wants/systemd-networkd.service to /usr/lib/systemd/system/systemd-networkd.service.
  Created symlink from /etc/systemd/system/sockets.target.wants/systemd-networkd.socket to /usr/lib/systemd/system/systemd-networkd.socket.
  ```
- Additionally, I have an other machine with a similar setup (not identical) for which the following happens:
  
  ```
  abdo@grothendieck [=master√] systemd $ sudo systemctl preset-all
  Removed symlink /etc/systemd/system/getty.target.wants/getty@tty1.service.
  Removed symlink /etc/systemd/system/multi-user.target.wants/org.cups.cupsd.path.
  Removed symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
  Removed symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service.
  Removed symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket.
  Created symlink from /etc/systemd/system/multi-user.target.wants/org.cups.cupsd.path to /usr/lib/systemd/system/org.cups.cupsd.path.
  Created symlink from /etc/systemd/system/getty.target.wants/getty@tty1.service to /usr/lib/systemd/system/getty@.service.
  Created symlink from /etc/systemd/system/multi-user.target.wants/systemd-resolved.service to /usr/lib/systemd/system/systemd-resolved.service.
  Created symlink from /etc/systemd/system/multi-user.target.wants/systemd-networkd.service to /usr/lib/systemd/system/systemd-networkd.service.
  Created symlink from /etc/systemd/system/sockets.target.wants/systemd-networkd.socket to /usr/lib/systemd/system/systemd-networkd.socket.
  ```

Here the correct state is reached, but I find it odd that some units get disabled and reenabled, while others are not touched.

**Comment by mischief** [comment]
related to #2345, presets of template instances seems busted.

**Comment by yuwata** [comment]
I've report my test results and a workaround for the problem in https://github.com/systemd/systemd/issues/3616#issuecomment-233967783 and https://github.com/systemd/systemd/issues/3616#issuecomment-233970059. Please read and give comments to them.

**Comment by AdamWill** [comment]
`preset-all` seems to do lots of wrong things on a stock Fedora install, which is unfortunate since the systemd package's `%post` was recently changed to use it. This broke tty1, and probably some other stuff. https://bugzilla.redhat.com/show_bug.cgi?id=1363858

**Comment by keszybz** [comment]
After #3955, the only thing that is still known broken is that if getty@tty1.service is masked, and getty@.service is enabled in presets with DefaultInstance=tty1, presetting getty@.service will cause the symlink in .wants to be created. The mask prevents the unit from being started though. This probably should be fixed for consistency. I'll retitle the bug accordingly.
