### ISSUE TITLE
the unified cgroup hierarchy no longer has cgroup.populated

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#2515]
Since kernel 4.4, the unified hierarchy no longer has `cgroup.populated`, and has been replaced by `cgroup.events`: https://github.com/torvalds/linux/commit/4a07c222d3afb00e1113834fee38d23a8e5d71dc

**Comment by poettering** [comment]
That's really not the only thing that changed... See #2271...

So far I was not able to successfully boot any 4.4 kernel on my machine, hence I am not able to update things...

**Comment by keszybz** [comment]
Let's close this, and discuss things, if necessary, in #2271.
