### ISSUE TITLE
rsyslog CPU usage 100% due to ppoll() not switched to __ppoll64() in 32bit -D_TIME_BITS=64 compile

### ISSUE THREAD

**Issue by kabe-gh** [systemd/systemd#25176]
### systemd version the issue has been seen with

250

### Used distribution

Rocky Linux 9

### Linux kernel version used

5.14.0-70.26.1.el9.v1.i686

### CPU architectures issue was seen on

i686

### Component

systemd

### Expected behaviour you didn't see

rsyslog CPU usage should be minimal on quiscent system

### Unexpected behaviour you saw

top command shows nealy 100% CPU usage by rsyslogd

### Steps to reproduce the problem

Compile systemd with CFLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 -Wp,-D_FORTIFY_SOURCE=2" for i686., and run rsyslog with imjournal plugin enabled.

Under glibc environment, -D_TIIME_BITS=64 will switch ppoll() invocation in src/basic/io-util.c:ppoll_usec() to use __ppoll64().

But, additional compile option -Wp,-D_FORTIFY_SOURCE=2 nullifies this, and the resulting *.o will refer to 32bit API ppoll().

The resulting libsystemd.so  library code will call 32bit ppoll() with 64-bit struct timespec. which is incorrect; timeout request of struct timespec(64bit)=900000us from rsyslogd wil be parsed by kernel as struct timespec(32bit)=0us, resulting in rsyslog calling sd_journal_wait() rapidly (CPU 100%) in imjournal plugin,

### Additional program output to the terminal or log subsystem illustrating the issue

Propowed patch below, but very hackish. 
Only works on glibc environment.

```diff
diff -up ./src/basic/io-util.c.t64 ./src/basic/io-util.c
--- ./src/basic/io-util.c.t64   2022-01-18 20:35:43.000000000 +0900
+++ ./src/basic/io-util.c       2022-10-29 21:54:19.154666964 +0900
@@ -9,6 +9,13 @@
 #include "string-util.h"
 #include "time-util.h"

+/* -Wp,-D_FORTIFY_SOURCE=2 disables redirection of ppoll -> __ppoll64,
+ * so invoke it explicitly
+ */
+#if defined(_TIME_BITS) && _TIME_BITS == 64
+int __ppoll64(struct pollfd *fds, nfds_t nfds, const struct timespec *timeout, const sigset_t *sigmask);
+#endif
+
 int flush_fd(int fd) {
         int count = 0;

@@ -167,7 +174,11 @@ int ppoll_usec(struct pollfd *fds, size_
         if (nfds == 0)
                 return 0;

+#if !defined(_TIME_BITS) || _TIME_BITS != 64
         r = ppoll(fds, nfds, timeout == USEC_INFINITY ? NULL : timespec_store(&ts, timeout), NULL);
+#else
+        r = __ppoll64(fds, nfds, timeout == USEC_INFINITY ? NULL : timespec_store(&ts, timeout), NULL);
+#endif
         if (r < 0)
                 return -errno;
         if (r == 0)
```

**Comment by dtardon** [comment]
> Compile systemd with CFLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 -Wp,-D_FORTIFY_SOURCE=2" for i686., and run rsyslog with imjournal plugin enabled.
> 
> Under glibc environment, -D_TIIME_BITS=64 will switch ppoll() invocation in src/basic/io-util.c:ppoll_usec() to use __ppoll64().
> 
> But, additional compile option -Wp,-D_FORTIFY_SOURCE=2 nullifies this, and the resulting *.o will refer to 32bit API ppoll().

This looks like a bug in glibc headers then, doesn't it?

**Comment by poettering** [comment]
Yeah, definitely. We do not carry our own 64bit time_t or off_t support in systemd, this *must* come from your libc, and if that's broken in some cases, they need to address that.

hence, please file a bug against your distro/glibc, and ask them to fix this.
