### ISSUE TITLE
systemd-networkd silently fails to create netdevs with too long names

### ISSUE THREAD

**Issue by pshirshov** [systemd/systemd#25188]
### systemd version the issue has been seen with

systemd 251 (251.5)

### Used distribution

NixOS

### Linux kernel version used

5.19.16

### Expected behaviour you didn't see

The following netdev file silently fails to create a veth device, with no messages in the journal nor dmesg:

```
[NetDev]
Kind=veth
Name=veth-u-br-prometheus

[Peer]
Name=veth-u-prometheus
```

At the same time the following one works fine:

```
[NetDev]
Kind=veth
Name=veth-u-br-prom

[Peer]
Name=veth-u-prom
```

Apparently the problem is the name which is too long, but I believe that there must be some validation and verbose error reporting in place.

### Unexpected behaviour you saw

Silent failure with no messages

**Comment by poettering** [comment]
please provide logs of networkd when this happens

**Comment by yuwata** [comment]
I guess journal should contain `Interface name is not valid or too long, ignoring assignment`.
https://github.com/systemd/systemd/blob/995340074e554b4bf4a0fdb0cb7436692c5a4ffd/src/shared/conf-parser.c#L1381-L1384

**Comment by pshirshov** [comment]
Hmm. For some reason I don't see this line in my logs.

**Comment by yuwata** [comment]
Cannot reproduced, that is, I observe the following:
```
Nov 10 16:23:51 systemd-networkd[348684]: /etc/systemd/network/10-veth.netdev:3: Interface name is not valid or too long, ignoring assignment: veth-u-br-prometheus
Nov 10 16:23:51 systemd-networkd[348684]: NetDev without Name= configured in "/etc/systemd/network/10-veth.netdev", ignoring.
```
Please check the path of the .netdev file.

**Comment by pshirshov** [comment]
Ok, I don't know what's wrong with my system but whatever, sorry.
