### ISSUE TITLE
modules-load: should not fail when `module_blacklist` is used to blacklist modules

### ISSUE THREAD

**Issue by YHNdnzj** [systemd/systemd#25182]
Currently, `systemd-modules-load.service` fails when `module_blacklist=` is used to block a module from being loaded, while `modprobe.blacklist` allows it to start successfully. I think for both cases, `modules-load` should exit normally as the user is explicitly blacklisting those modules.

I know that `kmod` is responsible for the actual module loading. But in this specific case, I believe systemd should take care of this. Since `kmod` is usually used to manually load modules, and the kernel would still block it eventually, it's not that necessary for them to check kernel cmdline for this. However, what `systemd-modules-load` does is to autoload these modules in the boot process, and thus makes being aware of both of the blacklisting methods matter.

**Comment by arvidjaar** [comment]
> Currently, `systemd-modules-load.service` fails when `module_blacklist=` is used to block a module from being loaded, while `modprobe.blacklist` allows it to start successfully.

These two parameters have completely different semantic, are interpreted by different components and `modprobe.blacklist` is not related to `systemd-modules-load.service` in any way (the former is applied when resolving module alias while the latter explicitly loads module under its final canonical name).

> `modules-load` should exit normally as the user is explicitly blacklisting those modules

If you do not want the module to be loaded, do not force load it using `systemd-modules-load.service`. If you **do** want module to be loaded and it failed to load (for whatever reason) it certainly sounds wrong to silently ignore it.

`module_blacklist=` is kernel parameter that absolutely prohibits the specified modules to be loaded. There is no reason to use it unless you are debugging something at which point "failure" of `systemd-modules-load.service` is the least concern. If you want to permanently stop module from being loaded, remove it from `modules-load.d` after having booted once with `modules_blacklist=`.

**Comment by YHNdnzj** [comment]
> These two parameters have completely different semantic, are interpreted by different components and modprobe.blacklist is not related to systemd-modules-load.service in any way (the former is applied when resolving module alias while the latter explicitly loads module under its final canonical name).

I've mentioned my reasons towards whether systemd or kmod should handle this.

> If you do not want the module to be loaded, do not force load it using systemd-modules-load.service. If you do want module to be loaded and it failed to load (for whatever reason) it certainly sounds wrong to silently ignore it.

But by using `modprobe.blacklist`, it's doing what you call "wrong" (kmod silently ignores it, and modules-load exits normally). The loading strategy towards both methods of blacklisting should align.

> module_blacklist= is kernel parameter that absolutely prohibits the specified modules to be loaded. There is no reason to use it unless you are debugging something at which point "failure" of systemd-modules-load.service is the least concern. If you want to permanently stop module from being loaded, remove it from modules-load.d after having booted once with modules_blacklist=.

Sometimes the upstream/distro packaging would ship a `modules-load` conf that autoloads certain modules, and I want to prohibit it from loading in all possible ways. Based on my statement above, `modprobe.blacklist` can actually block it from loading automatically and make `modules-load` exit normally, with or without reconfiguring `modules-load`.


Anyways, if I use `modprobe.blacklist` together with `module_blacklist`, it would produce the desired behavior i.e. `modules-load` exits successfully and the module is blacklisted both manually and automatically. My idea is simply that I should only need one of them to blacklist autoloading without interfering `modules-load`.
