### ISSUE TITLE
systemd.pc: no substitution for @systemshutdowndir@

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#252]
In commit d6b07ef the old shutdownd implementation was removed.
Along with it, the substitution of @systemshutdowndir@.

This substitution is still used in src/core/systemd.pc.in
The result is a broken .pc file which contains:
systemdshutdowndir=@systemshutdowndir@

**Comment by poettering** [comment]
The dir should never have been removed. systemdshutdowndir has nothing to do with shutdownd. I figure @zonque's removal sed was a bit too eager...

THis should be readded.

**Comment by poettering** [comment]
#260 is merged now. Closing hence.
