### ISSUE TITLE
UKI (sd-stub) loses cmdline when booted from EFI shell (no SecureBoot)

### ISSUE THREAD

**Issue by osteffenrh** [systemd/systemd#25201]
### systemd version the issue has been seen with

252~rc3-74-g38c6289

### Used distribution

Fedora 37

### Linux kernel version used

5.19.15-301.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

Unified kernel image (UKI) started from the EFI shell without any additional arguments is launched with the command line from the `.cmdline` section of the image.

SecureBoot is disabled.

### Unexpected behaviour you saw

kernel command line is replaced with the path/filename of the booted UKI (plus some other stuff at the end?)

For example:

```
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):F0a65535a:;BLK0:
          PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)
     BLK1: Alias(s):
          PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
Press ESC in 5 seconds to skip startup.nsh or any other key to continue.
Shell> FS0:
FS0:\> EFI\Linux\vmlinuz.efi
systemd-stub@0x2744C000,0x2745E000
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
[...]
```
Later in userspace:
```
# cat /proc/cmdline
EFI\Linux\vmlinuz.efi ptal@
```

Although:
```
# objdump -s -j .cmdline EFI/Linux/vmlinuz.efi

EFI/Linux/vmlinuz.efi:     file format pei-x86-64

Contents of section .cmdline:
 30000 20636f6e 736f6c65 3d747479 53302063   console=ttyS0 c
 30010 6f6e736f 6c653d74 74793020 00        onsole=tty0 .
```

To my understanding the cmdline should not be replaced, since no additional arguments where given when launching the UKI. It seems the shell places the path/filename as first argument, which is then considered as a command line replacement by the stub.

### Steps to reproduce the problem

- Create UKI via dracut with a custom cmdline
- Place on ESP
- Launch Qemu + OVMF + EFI Shell, SecureBoot off
- Launch UKI from there
- Observe cmdline passed to kernel

**Comment by poettering** [comment]
So the .cmdline is the default command line if none is specified. it would be very annoying if you'd have to type out the cmdline each time you invoke an EFI binary just because you turned off SB.

So the rule is:

1. .cmdline is used when UKI is called without arguments
2. .cmdline is used when SecureBoot is on

If we don't document this properly right now, we should do that.

I am not entirely sure how quoting in the efi shell works, but if we don't have a way to force an empty kernel cmdline to be passed to the kernel then we should devise some syntax for that.

**Comment by poettering** [comment]
oh. sorry, i misread the issue. ignore me.

**Comment by medhefgo** [comment]
What's more concerning is that the NUL termination isn't done properly when converting things. Will look at this further tomorrow.

**Comment by poettering** [comment]
i wonder if this is an issue with overlapping offsets..

**Comment by medhefgo** [comment]
> i wonder if this is an issue with overlapping offsets..

Nope, it's our code.

**Comment by medhefgo** [comment]
Fix for the NUL termination handling is in https://github.com/systemd/systemd/pull/25222.

I am somewhat reluctant to deal with the EFI shell cmdline handling. Trying to detect whether we are called by the shell sounds like it'd be fraught with errors to me. And ultimately, the EFI shell is really just a debug tool for advanced users. I'd rather declare this a "You get what you ask for!"…

**Comment by medhefgo** [comment]
I guess I talked too soon. Turns out the shell provides an easy way to detect this. Please give the PR a try.

**Comment by osteffenrh** [comment]
Works! Thanks a lot. That makes UKIs more versatile.
