### ISSUE TITLE
Timedatectl should work without systemd

### ISSUE THREAD

**Issue by Harvie** [systemd/systemd#25214]
### Component

timedatectl

### Is your feature request related to a problem? Please describe

I have script that build OS image using debootstrap and chroot. I want to set timezone during the image build, before the system is actualy running. But `timedatectl set-timezone` fails without systemd. Also the host system which builds this OS image is not guaranteed to run systemd.

### Describe the solution you'd like

Can you please add some option to allow setting timezone in chroot (modifiing config files) without actualy needing to do anything in runtime? Eg.: `timedatectl set-timezone --offline Europe/Prague`

### Describe alternatives you've considered

Currently i am using chroot script like this:

```bash
timedatectl set-timezone Europe/Prague #Fails in chroot
echo Europe/Prague > /etc/timezone
ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime
```
But i would prefer timedatectl to set the files for me, so i can still have this convenient abstraction layer...

**Comment by bluca** [comment]
timedatectl talks to systemd-timedated over D-Bus, not sure what it would even mean to "work without systemd"? It's a systemd service

**Comment by bluca** [comment]
instead, you should use systemd-firstboot for that, which supports --root/--image: https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html

**Comment by mrc0mmand** [comment]
As Luca said, you should use `systemd-firstboot` instead:

```
# timedatectl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
# ls -l /etc/localtime
ls: cannot access '/etc/localtime': No such file or directory
# systemd-firstboot --timezone=Europe/Prague
/etc/localtime written
# ls -l /etc/localtime
lrwxrwxrwx 1 root root 35 Nov  1 11:45 /etc/localtime -> ../usr/share/zoneinfo/Europe/Prague
```

or you can run it outside of the chroot/image with `--root=xxx/--image=yyy`.

**Comment by Harvie** [comment]
> systemd-firstboot

i was not aware of this. thank you!
