### ISSUE TITLE
journal-remote: huge memory usage with v228

### ISSUE THREAD

**Issue by chaloulo** [systemd/systemd#2521]
Hello,

systemd-journal-remote from v228 uses an enormous amount of memory. For each journal-upload sender connected it uses about1.5GB of memory. 

Below is a top output before any journal-upload senders connect:

`PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND`
`489 root      20   0   22.7m   2.1m   0.0  0.0   0:00.00 S systemd-journal`

After one sender connects and a log entry is sent:

`PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND`
`495 root      20   0 1558.7m 1.503g   0.0 19.3   0:01.60 S systemd-journal`

After second journal-upload client connects:
`PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND`
`495 root      20   0 2326.7m 2.254g   0.0 28.9   0:02.51 S systemd-journal`

I tested with versions 225, 226 and 227 and the issue did not appear, so it looks like it is something introduced in v228.
Before any journal-upload clients connect, the memory usage is normal. Interesting is that if the journal-upload clients disconnect, the memory usage fell to 750MB.

In an other test I did, journal-remote used about 750MB per connected client.

Any idea why this is happening? 
I'll try to do some debugging myself, but if anyone can help, it will be much appreciated.

Best regards,

Klearchos

**Comment by ohsix** [comment]
is the command truncated? (i don't use journal-remote, but i'm looking at this)

**Comment by chaloulo** [comment]
Yes, the top output is truncated. I run top with "top -p $(pidof systemd-journal-remote).

**Comment by ohsix** [comment]
there aren't a lot of changes in journal-remote in that timeframe but there is 5e3efccfc97c521107057ab088f58acfae8a8956 which specifically mentions a memory limit, i don't know anything about microhttpd ;D

**Comment by ohsix** [comment]
from microhttpd docs

MHD_OPTION_CONNECTION_MEMORY_LIMIT
Maximum memory size per connection (followed by a size_t). The default is 32 kB (32*1024 bytes) as defined by the internal constant MHD_POOL_SIZE_DEFAULT. Values above 128k are unlikely to result in much benefit, as half of the memory will be typically used for IO, and TCP buffers are unlikely to support window sizes above 64k on most systems.

from systemd headers
`src/journal/journald-native.h:#define DATA_SIZE_MAX (1024*1024*768u)`

the gap between 128k and 768mb is pretty big.

**Comment by chaloulo** [comment]
Thanks! I verified that be removing this commit the problem disappears. So what is the way to go? Maybe replace the line
`{ MHD_OPTION_CONNECTION_MEMORY_LIMIT, DATA_SIZE_MAX}`
with 
`{ MHD_OPTION_CONNECTION_MEMORY_LIMIT, 256*1024}`
?
This should allow for the increase in memory that the original commit needed, but it will also set a reasonable upper value.

**Comment by ohsix** [comment]
i dunno, i'm new to this github thing, i could probably be adding some tags; uh i think you can attach a patch just changing it? or send a pull request with the value you think is appropriate (since you may be able to test performance in your situation, might as well maximize benefit for doing the work :)

**Comment by chaloulo** [comment]
OK, I'll post a new PR and will take it from there.

**Comment by chaloulo** [comment]
PR opened [link](https://github.com/systemd/systemd/pull/2525). I'll close this issue in order to follow the discussion from the PR.
