### ISSUE TITLE
Watchdog for session

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#25225]
### Component

systemd-logind

### Is your feature request related to a problem? Please describe

Today my Plasma5-wayland session hang. I must kill it by ctrl+alt+backspace twice. Some people research a way to  made application persist over sessions, so killing compositor do not kill applications and applications could connect to new compositor.

### Describe the solution you'd like

Implement programmable watchdog, which sends signal to all process in some session, when compositor hangup. Process, which need to repaint screen will send message(method call) to this watchdog and if there is no another method call invoked by compositor on watchog, we assumed session hang.

**Comment by nintyfan** [comment]
In case of session hang, we send signal to each process in session, so each process could save work/session.

**Comment by poettering** [comment]
I cannot really parse this, but note that in a wayland world it's unlikely you can save your apps if your compositor dies.

Either way, please talk to the KDE people about this. This needs to come from them, if they actually can make their compositor robust for this. If the KDE people have a good idea how to implement anything like this, they should mkae a proposal to us, and we can consider this, but this is really someting that must come from them, given this is primarily a compositor thing.

**Comment by nintyfan** [comment]
Sorry about responding in closed thread, but I think you do not understand my request :-(
