### ISSUE TITLE
Can't disable recursive mode in `systemd-cgtop`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#25248]
### systemd version the issue has been seen with

latest main

### Used distribution

Arch Linux, Fedora 36

### Unexpected behaviour you saw

While extending our test coverage I noticed I can't seem to disable the recursive mode in `systemd-cgtop` even if I follow the steps from the error message/man page:

```
$ build/systemd-cgtop --recursive=no
Non-recursive counting is only supported when counting processes, not tasks. Use -P or -k.
$ build/systemd-cgtop --recursive=no -P
Non-recursive counting is only supported when counting processes, not tasks. Use -P or -k.
$ build/systemd-cgtop --recursive=no -k
Non-recursive counting is only supported when counting processes, not tasks. Use -P or -k.
```

I suspect this happens because the set count mode is later overridden depending on the cgroup maks:

https://github.com/systemd/systemd/blob/6c83054c0133eb53245e479d71589dceff76cf74/src/cgtop/cgtop.c#L927-L935

Is this expected?

**Comment by Werkov** [comment]
I assume that if CI (with [updated tests](https://github.com/systemd/systemd/pull/25532/commits/236a4596fb2821d3e9b213c0722af5541466834c)) on #25532 succeeds, it's fixing this issue too.
