### ISSUE TITLE
memory accounting bug?

### ISSUE THREAD

**Issue by jelmd** [systemd/systemd#25271]
### systemd version the issue has been seen with

245

### Linux kernel version used

5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

systemd-cgtop, systemd-oomd

### Expected behaviour you didn't see

`systemd-cgtop` is severely out of sync with `ps -auxx`, i.e. it seems not to catch memory being implicitly freed, when a session gets killed, e.g. by oomd.

### Unexpected behaviour you saw

`systemd-cgtop -m` reports / 1.8 TB, however all processes within the related container consume max. 430 MB RSS, 1.4 GB VSS (checked using `ps -eo pmem,pcpu,vsize,rss,pid,cmd,user | awk '{ A+=$4 } END { print A }'`). Such a huge difference (~ 1.8 TB) is unexpected and actually keeps oomd busy - kills any new session because of an OOM condition, which actually does not exist - proc/meminfo::MemAvailable: 2068505368 kB)

### Steps to reproduce the problem

Just occurs from time to time. Haven't yet found a way to reproduce it.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/jelmd/456b47b220576302a6b0c669b4248d51


...
[Nov 5 00:46] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-42816.scope'  '0.00|0.00|0.00'  '166055 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 00:55] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43004.scope'  '0.00|0.00|0.00'  '4376 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[ +16.010610] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-42953.scope'  '0.00|0.00|0.00'  '4249 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 01:10] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43044.scope'  '0.00|0.00|0.00'  '6921 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 01:37] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43059.scope'  '0.00|0.00|0.00'  '3697 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 01:45] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43062.scope'  '0.00|0.00|0.00'  '3692 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 01:52] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43066.scope'  '0.00|0.00|0.00'  '3688 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 01:57] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-42646.scope'  '0.00|0.00|0.00'  '4332 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
[Nov 5 02:15] oomd kill: 'lxc.payload.n09-00/user.slice/user-1000.slice/session-43067.scope'  '0.00|0.00|0.00'  '6933 MiB'  'system protection'  'system memory usage above 98% for >= 60s'  'kill_by_memory_size_or_growth'
```
```

**Comment by bluca** [comment]
It's the other way around, cgroup accounting is the correct one and tools like ps miss too many things and are not reliable. You can find documentation on cgroups on kernel.org and if you think it's not working correctly, you need to bring it up with the kernel

**Comment by jelmd** [comment]
Hmmm, that's interesting. Actually, if I disable oomd and try to alloc and use the 1.8 TB, I get almost all the 1.8 TB. So what is missing? systemd reports, that there is all memory in use, but this obviously not the case. So where is the bug?

**Comment by poettering** [comment]
memory accounting is done by the kernel, we just use whatever the kernel reports. and cgtop literally shows whatever the kernel reports. 

"ps" is not a useful tool for tracking down memory use, it has no useful understanding of the complexities of memory management, i.e. shared pages, pages that are swapped out, and so on. 

Either way, please contact the kernel mm community for help, if you need further explanations, systemd is just the messenger here, the kernel implements the mm accounting logic, nut us.
