### ISSUE TITLE
systemd-networkd IP stealing

### ISSUE THREAD

**Issue by mbassiouny** [systemd/systemd#2527]
Consider node (A) have a static IP network configuration, and this IP already assigned to another node (B) on the same network. systemd-networkd still assigning the same IP to node (A) and sometime it steals the IP from node(B).

**Comment by poettering** [comment]
And?

What precisely do you intend to say with this issue? That this is a bug? Or a feature? Please explain.

**Comment by mbassiouny** [comment]
I can not say it's a bug, it's the same behaviour for Ubuntu, but redhat based systems does not allow stealing. I would say, it's a feature request. I would like to see this feature in systemd.

**Comment by mbassiouny** [comment]
I would like to see systemd-networkd NOT stealing the IP if some other node on the network has the same IP.

**Comment by zdzichu** [comment]
Do not configure the same IP on multiple hosts, maybe?
Also, have you manually disabled duplicate address detection? It is on by default (https://github.com/systemd/systemd/commit/14a081a0ff1db125ade7aea3540e5544fd3e57a9)

**Comment by teg** [comment]
We should do address conflict detection (the IPv4 equivalent to DAD), to address this. We have the library, just needs hooking up. On the TODO.
