### ISSUE TITLE
Haier 7G-Series/JWU: Pressing Wifi toggling function key results in unknown key pressed message

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#25293]
### systemd version the issue has been seen with

252

### Used distribution

Debian sid/unstable

### Linux kernel version used

6.0.0-2-amd64 (6.0.6)

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

On the Intel Haswell system HaierComputer 7G-Series/JWU, BIOS KQ122 05/08/2014, pressing the function key to toggle the Wifi device on and off, the desktop environment should give feedback, that the toggling happened.

### Unexpected behaviour you saw

GNOME does not provide any feedback, and Linux logs:

    [ 2177.373205] atkbd serio0: Unknown key pressed (translated set 2, code 0x91 on isa0060/serio0).
    [ 2177.373216] atkbd serio0: Use 'setkeycodes e011 <keycode>' to make it known.
    [ 2177.507512] atkbd serio0: Unknown key released (translated set 2, code 0x91 on isa0060/serio0).
    [ 2177.507528] atkbd serio0: Use 'setkeycodes e011 <keycode>' to make it known.

**Comment by paulmenzel** [comment]
The entry below seems to fix it.

    $ cat /etc/udev/hwdb.d/70-keyboard.hwdb
    evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHaierComputer:pn7G-Series:*
     KEYBOARD_KEY_91=wlan

GNOME toggles the airplane mode, when pressing the key. The device has *no* Bluetooth or other radio device, so this also turns (only) Wifi on or off.

**Comment by yuwata** [comment]
Please submit the change as a PR.
