### ISSUE TITLE
systemd-detect-virt: Distinguishing WSL1 from WSL2

### ISSUE THREAD

**Issue by EduardGomezEscandell** [systemd/systemd#25298]
### Component

systemd

### Is your feature request related to a problem? Please describe

`systemd-detect-virt` detects WSL, but does not distinguish WSL1 from WSL2. This has caused a proliferation of ad-hoc mechanisms to perform this distiction, and I believe `systemd-detect-virt` could become the standard authoritative source to use.

### Describe the solution you'd like

The technical aspect is simple enough: look at the root filesystem type. `wslfs` or `lxfs` means WSL1, anything else means `WSL2`.

I intend to implement this myself but first I'd like to know that this addition is welcome, and to agree on a design.

Currently `systemd-detect-virt`returns `wsl`. Changing this to `wsl1` or `wsl2` would break too many dependent applications, so I believe a more careful approach needs be taken.

I propose something like:
```
$ systemd-detect-virt --verbose # or -v
wsl 2
```

### Describe alternatives you've considered

- You can parse the kernel name, but that is customizable in WSL2.
- You can look for specific files in the filesystem, but with the customizable WSL2 kernel this may become complicated.

**Comment by bluca** [comment]
My understanding is that wsl1 is pretty much on life support and everyone is supposed to just use wsl2? Is this really needed?

**Comment by EduardGomezEscandell** [comment]
WSL1 is still alive as far as I understand. It still has its use when cross-filesystem speed is necessary.

**Comment by poettering** [comment]
yeah, adding new support for dead software sounds like it's a bad idea.
