### ISSUE TITLE
systemctl edit results in final missing final newline

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/systemd#25303]
### systemd version the issue has been seen with

247.3-7+deb11u1, 251.6-1

### Used distribution

Debian bullseye, sid

### Linux kernel version used

5.10.0-19-amd64, 6.0.0-2-amd64

### CPU architectures issue was seen on

amd64, x32

### Component

systemctl

### Expected behaviour you didn't see

/e/s/s/*svc*.s.d/o.c to be a text file.

### Unexpected behaviour you saw

It isn't.

### Steps to reproduce the problem

`systemctl edit systemd-networkd-wait-online`, put in some stuff, `cat /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf`, behold

I guess they don't *need* to be text files for systemd to accept them, but it's damn annoying, and means you can't process them in the usual ways.

### Additional program output to the terminal or log subsystem illustrating the issue

I can confirm from some older overrides that they *used* to be text files, so idk.

**Comment by mrc0mmand** [comment]
Could you give some example? I just tried on a couple of machines, but don't see any issue:

Arch Linux, systemd 251.7-4 (`EDITOR=vim`)
```
# systemctl edit systemd-networkd-wait-online
...
#  cat /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf 
[Unit]
Description=hello
# file /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf 
/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf: ASCII text
```

Fedora Rawhide, systemd-252~rc3-586.fc38.x86_64 (`EDITOR=nano`)
```
# systemctl edit systemd-networkd-wait-online
...
# cat /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf 
foo bar
# file /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf 
/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf: ASCII text, with no line terminators
```

**Comment by nabijaczleweli** [comment]
On both systems above I get:
```
$ cat -A /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
ExecStart=$
ExecStart=/lib/systemd/systemd-networkd-wait-online --timeout=300nabijaczleweli@tarta:~$
```
after typing in both lines (default editor that resolves to vim.nox and nvi, respectively). Attaching typescript from sid system above: [typescript.gz](https://github.com/systemd/systemd/files/9964816/typescript.gz) (note also how GNU ed starts with "Newline appended" here, but of course that doesn't really matter for the temporary file, so whatever).

**Comment by nabijaczleweli** [comment]
#25305

**Comment by mrc0mmand** [comment]
This now creates an empty `override.conf` if you close the editor after `systemctl edit` without any changes.

Before:
```
# rm -f /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# EDITOR=cat systemctl edit systemd-networkd-wait-online </dev/null
...
Editing "/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf" canceled: temporary file is empty.
# wc -l /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
wc: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf: No such file or directory
```

With this patch:
```
# rm -f /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# EDITOR=cat build/systemctl edit systemd-networkd-wait-online </dev/null
...
# wc -l /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
1 /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
# hexdump -c /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
0000000  \n                                                            
0000001
```
