### ISSUE TITLE
random-seed: don't ignore errors when failing to create /var/lib/systemd/random-seed

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2530]
In Debian-Bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813599 , a user had (accidentally) remounted /var ro. This resulted in a failure in systemd-random-seed load when trying to create the seed file. The code ignores the error from the first open():

```
seed_fd = open(RANDOM_SEED, O_RDWR|O_CLOEXEC|O_NOCTTY|O_CREAT, 0600);
       if (seed_fd < 0) {
                seed_fd = open(RANDOM_SEED, O_RDONLY|O_CLOEXEC|O_NOCTTY);
                if (seed_fd < 0) {
                          r = log_error_errno(errno, "Failed to open " RANDOM_SEED ": %m");
```

We should probably log an error message if the first open() call fails.

**Comment by keszybz** [comment]
I think that the idea is to not produce an error on read-only fs. Why do you want to warn in that case?

**Comment by keszybz** [comment]
Ah, OK, I get it now.
