### ISSUE TITLE
Lenovo P14s Gen2 (AMD) reports ConditionACPower false while on AC Power via USB-C

### ISSUE THREAD

**Issue by neurolabs** [systemd/systemd#25316]
### systemd version the issue has been seen with

systemd/testing,now 252-2

### Used distribution

Debian Bookworm

### Linux kernel version used

6.0.0-2-amd64

### Expected behaviour you didn't see

A unit with ConditionACPower=true runs when I manually start it while on AC Power using the stock USB-C power supply.

### Unexpected behaviour you saw

The unit did not start 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 09 13:01:37 leo systemd[1]: backup.service: Installed new job backup.service/start as 31081
Nov 09 13:01:37 leo systemd[1]: backup.service: Enqueued job backup.service/start as 31081
Nov 09 13:01:37 leo systemd[1]: BAT0: The power supply is battery.
Nov 09 13:01:37 leo systemd[1]: hidpp_battery_6: The power supply is a device battery, ignoring device.
Nov 09 13:01:37 leo systemd[1]: Found battery and no online power sources, assuming system is running from battery.
Nov 09 13:01:37 leo systemd[1]: backup.service: ConditionACPower=true failed.
Nov 09 13:01:37 leo systemd[1]: backup.service: Starting requested but condition failed. Not starting unit.
Nov 09 13:01:37 leo systemd[1]: backup.service: Job 31081 backup.service/start finished, result=done
Nov 09 13:01:37 leo systemd[1]: Create system backups was skipped because of an unmet condition check (ConditionACPower=true).
```

**Comment by yuwata** [comment]
Could you provide the result of the following command?
```
SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-ac-power
```

**Comment by yuwata** [comment]
@neurolabs Fix is waiting in #25334. If possible, could you test the PR?

**Comment by neurolabs** [comment]
@yuwata your assumptions are correct:

```
root@leo ~ # ls -l /sys/class/power_supply/
total 0
lrwxrwxrwx 1 root root 0  7. Nov 23:05 BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:37/PNP0C09:00/PNP0C0A:00/power_supply/BAT0
lrwxrwxrwx 1 root root 0 11. Nov 08:20 hidpp_battery_9 -> ../../devices/pci0000:00/0000:00:08.1/0000:07:00.4/usb5/5-1/5-1.2/5-1.2:1.2/0003:046D:C52B.004F/0003:046D:101A.0050/power_supply/hidpp_battery_9
```

I am eager to test your fix locally, but ran into problems building. I did:

```
git clone https://github.com/yuwata/systemd.git
cd systemd
git switch ac-power-discharging-battery
sudo apt-get build-dep systemd
meson build
```

and I'm ending up with the following configure error

```
meson.build:1145:0: ERROR: Dependency "mount" not found, tried pkgconfig and cmake
```

libmount-dev is installed.

**Comment by yuwata** [comment]
@neurolabs Thank you for trying to test the PR.

> and I'm ending up with the following configure error
> 
> ```
> meson.build:1145:0: ERROR: Dependency "mount" not found, tried pkgconfig and cmake
> ```
> 
> libmount-dev is installed.

Hm, the package is broken?? Or, some basic tools to detecting pkgconfig file is missing? Not familiar with debian, but the package seems to have the pkgconfig file:
https://packages.debian.org/bookworm/amd64/libmount-dev/filelist

@bluca Could you help us?

**Comment by bluca** [comment]
apt install pkg-config

**Comment by neurolabs** [comment]
Got it running using another user account:


```
# no power supply connected
ehlo@leo ~/systemd # SYSTEMD_LOG_LEVEL=debug ./build/systemd-ac-power
BAT0: The power supply is a battery and currently discharging.
Found at least one discharging battery and no online power sources, assuming system is running from battery.
# power supply connected
ehlo@leo ~/systemd # SYSTEMD_LOG_LEVEL=debug ./build/systemd-ac-power
BAT0: The battery status is 'Charging', assuming the battery is not used as a power source of this machine.
No power supply reported online and no discharging battery found, assuming system is running on AC.
```

So in the context of this issue the change works.

**Comment by yuwata** [comment]
@neurolabs Yay! Thank you for testing!
