### ISSUE TITLE
systemd-pstore: Failed to write temporary file 7163286974713/dmesg.txt: File exists

### ISSUE THREAD

**Issue by vivekrnv** [systemd/systemd#25324]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

5.10.0-12-2-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-pstore

### Unexpected behaviour you saw

`Nov  7 20:16:20.211509 host ERR systemd-pstore[294]: Failed to write temporary file /var/lib/systemd/pstore/7163286974713/dmesg.txt: File exists. 
`

**Triage:**

I suspect the dmesg pstore files were saved to ERST backend even before the first reboot. inferred from the first 32 bits of the record id. 

After the first boot, the systemd-pstore moved the 7163286974713823234 file and happened to create 7163286974713/dmesg.txt under `/var/lib/systemd/pstore/` but the 7163286974713823233 was not moved probably because the systemd-pstore process was halted because of the second reboot.

I couldn't comprehend why 7163286974713823233 wasn't moved to the archive store immediately since there was almost 2 mins before the second reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
<first boot>
Nov  7 18:13:16 sonic systemd-pstore[295]: PStore dmesg-erst-7163286974713823234 moved to /var/lib/systemd/pstore/7163286974713/dmesg-erst-7163286974713823234

<another reboot, ntp sync>
Nov  7 20:16:20.211494 sonic INFO systemd-pstore[294]: PStore dmesg-erst-7163286974713823233 moved to /var/lib/systemd/pstore/7163286974713/dmesg-erst-7163286974713823233
Nov  7 20:16:20.211509 sonic ERR systemd-pstore[294]: Failed to write temporary file /var/lib/systemd/pstore/7163286974713/dmesg.txt: File exists
```

**Comment by yuwata** [comment]
Should be fixed by #25469.
