### ISSUE TITLE
Feature Request: Let systemd-journal-gateway serve non-local journal

### ISSUE THREAD

**Issue by DSpeichert** [systemd/systemd#2532]
It seems to me like `systemd-journal-gateway` is hardcoded to serve only local journal (typically from `/var/log/journal/`).

I'd like to have a centralized server that would serve logs from all my machines received by `systemd-journal-remote` and saved into `/var/log/journal/remote/`.

Currently, `systemd-journal-gateway` ignores those and there seems to be no switch (like `-D` in `journalctl`) to point it to a custom directory.

**Comment by skob** [comment]
dup https://github.com/systemd/systemd/issues/3871

**Comment by poettering** [comment]
indeed.
