### ISSUE TITLE
DNS domain name is not forwarded to resolvd by networkd

### ISSUE THREAD

**Issue by HyP3r-** [systemd/systemd#25344]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

5.15.76-v7+

### CPU architectures issue was seen on

arm

### Component

networkctl, resolvectl

### Expected behaviour you didn't see

I use systemd-networkd to obtain an IP address via DHCPv4. Normally systemd-networkd should then forward the DNS search domain then systemd-resolvd. But this does not happen on my system.

`resolvectl status`:
```
Link 2 (eth0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.0.1
       DNS Servers: 192.168.0.1
```
`resolvectl domain`:
```
Global:
Link 2 (eth0):
Link 3 (wg0):
Link 4 (tun0):
```

`/run/systemd/network/10-netplan-eth0.network`:
```
[Match]
Name=eth0

[Network]
DHCP=yes
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true
```

`/run/systemd/netif/leases/2`:
```
# This is private data. Do not parse.
ADDRESS=192.168.0.198
NETMASK=255.255.255.0
ROUTER=192.168.0.1
SERVER_ADDRESS=192.168.0.1
NEXT_SERVER=192.168.0.1
T1=43200
T2=75600
LIFETIME=86400
DNS=192.168.0.1
NTP=192.168.0.1
DOMAINNAME=fritz.box
CLIENTID=ffad7b857f00020000ab11b213c80560a16e83
```

**Comment by HyP3r-** [comment]
This workaround does not work for me: https://github.com/systemd/systemd/issues/11391#issuecomment-454010328

**Comment by yuwata** [comment]
Please enable `UseDomains=`.
https://systemd.network/systemd.network.html#UseDomains=
