### ISSUE TITLE
With systemd 252.1-1 one machine has an error output from bootctl status

### ISSUE THREAD

**Issue by mcloaked** [systemd/systemd#25359]
### systemd version the issue has been seen with

systemd 252.1-1

### Used distribution

Arch Linux

### Linux kernel version used

6.0.8

### Component

bootctl

### Expected behaviour you didn't see

I expected no error lines starting Failed to read boot option, when running bootctl status.

### Unexpected behaviour you saw

$ sudo bootctl status
Failed to read boot option 8194: No such file or directory
Failed to read boot option 8196: No such file or directory
System:
      Firmware: UEFI 2.70 (INSYDE Corp. 3865.00)
 Firmware Arch: x64
   Secure Boot: disabled (disabled)
  TPM2 Support: yes
  Boot into FW: supported

### Steps to reproduce the problem

Run bootctl status

**Comment by mcloaked** [comment]
The system appears to boot fine, despite the error from the bootctl status command.

**Comment by medhefgo** [comment]
Please provide the output of `SYSTEMD_LOG_LEVEL=debug bootctl --no-pager status`

**Comment by mcloaked** [comment]
The output from that command is:
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Using EFI System Partition at /efi.
Using XBOOTLDR partition at /boot as $BOOT.
Reading EFI variable /sys/firmware/efi/efivars/LoaderFirmwareType-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/LoaderFirmwareInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/LoaderFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/StubFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/StubFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Reading EFI variable /sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Reading EFI variable /sys/firmware/efi/efivars/AuditMode-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/AuditMode-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/DeployedMode-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/DeployedMode-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Secure boot variables: SecureBoot=0 AuditMode=-2 DeployedMode=-2 SetupMode=0
System:
      Firmware: UEFI 2.70 (INSYDE Corp. 3865.00)
 Firmware Arch: x64
   Secure Boot: disabled (disabled)
  TPM2 Support: yes
Reading EFI variable /sys/firmware/efi/efivars/OsIndicationsSupported-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Reading EFI variable /sys/firmware/efi/efivars/OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c.
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 252.1-1-arch
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/07c3f646-6587-4f9e-a84a-f264d55fc6d2
         File: └─/EFI/systemd/systemd-bootx64.efi

Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/07c3f646-6587-4f9e-a84a-f264d55fc6d2)
         File: ├─/EFI/systemd/systemd-bootx64.efi (systemd-boot 252.1-1-arch)
               └─/EFI/BOOT/bootx64.efi (systemd-boot 252.1-1-arch)

Reading EFI variable /sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Reading EFI variable /sys/firmware/efi/efivars/Boot0000-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0000
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/07c3f646-6587-4f9e-a84a-f264d55fc6d2
         File: └─/EFI/systemd/systemd-bootx64.efi

Reading EFI variable /sys/firmware/efi/efivars/Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c.
        Title: Windows Boot Manager
           ID: 0x0001
       Status: inactive, boot-order
    Partition: /dev/disk/by-partuuid/07c3f646-6587-4f9e-a84a-f264d55fc6d2
         File: └─/EFI/Microsoft/Boot/bootmgfw.efi

Reading EFI variable /sys/firmware/efi/efivars/Boot2001-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Ignoring boot entry 8193 without partition information.
Reading EFI variable /sys/firmware/efi/efivars/Boot3000-8be4df61-93ca-11d2-aa0d-00e098032b8c.
Ignoring boot entry 12288 without partition information.
Reading EFI variable /sys/firmware/efi/efivars/Boot2002-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/Boot2002-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
Failed to read boot option 8194: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/Boot2004-8be4df61-93ca-11d2-aa0d-00e098032b8c.
open("/sys/firmware/efi/efivars/Boot2004-8be4df61-93ca-11d2-aa0d-00e098032b8c") failed: No such file or directory
Failed to read boot option 8196: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Ignoring invalid loader entry ''.
Reading EFI variable /sys/firmware/efi/efivars/LoaderEntryOneShot-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderEntryOneShot-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
open("/sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f") failed: No such file or directory
Reading EFI variable /sys/firmware/efi/efivars/LoaderEntrySelected-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Found default: id "linux-stable.conf" is matched by pattern "linux-stable.conf"
Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/56b36de4-6635-4768-ab37-8d7953d5ba82)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #1 (.conf)
        title: Linux Stable
           id: linux-stable.conf
       source: /boot/loader/entries/linux-stable.conf
        linux: /vmlinuz-linux-stable
       initrd: /initrd-linux-stable.img
      options: root="UUID=057a0295-1250-4ae9-95cd-8494d505c185" rw audit=0

**Comment by medhefgo** [comment]
/sys/firmware/efi/efivars/Boot2004-8be4df61-93ca-11d2-aa0d-00e098032b8c

**Comment by medhefgo** [comment]
Also, the output of `efibootmgr` would be nice.

**Comment by mcloaked** [comment]
Those two lines with Boot2002 and Boot2004 don't appear in the efivars list! The output of the efibootmgr command is:
$ sudo efibootmgr
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001,2001,3000,2002,2004
Boot0000* Linux Boot Manager    HD(1,GPT,07c3f646-6587-4f9e-a84a-f264d55fc6d2,0x800,0x82000)/File(\EFI\systemd\systemd-bootx64.efi)
Boot0001  Windows Boot Manager  HD(1,GPT,07c3f646-6587-4f9e-a84a-f264d55fc6d2,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000000000100000010000000040000007fff0400
Boot2001* EFI USB Device        RC
Boot3000* Internal Hard Disk or Solid State Disk        RC

**Comment by medhefgo** [comment]
This is nothing particularly concerning then. The EFI boot order var mentions these two boot entries, but those entries don't exist anymore. bootctl is just informing you of that fact.

You should be able to get rid of this with `sudo efibootmgr --bootorder 0,1,2001,3000` (or use a new boot order if you like).

**Comment by mcloaked** [comment]
Using the command to remove the last two entries by resetting the boot order, works immediately after that command, and efibootmgr status confirms that, but on rebooting those two errant entries come back and the bootctl command then shows the same original warnings.  Perhaps there is some other way to permanently remove the 2002 and 2004 entries?

**Comment by yuwata** [comment]
Fix is waiting in #25368.

**Comment by mcloaked** [comment]
Great, thank you.
