### ISSUE TITLE
Support custom filesystem mount options with homed

### ISSUE THREAD

**Issue by mfinelli** [systemd/systemd#25366]
### Component

systemd-homed

### Is your feature request related to a problem? Please describe

Some filesystems (e.g., `btrfs`) support transparent compression (passing e.g., `-o compress=lzo` to `mount`). AFAICT reading the manpage (https://man.archlinux.org/man/homectl.1.en) there's no way to pass such an option the `homectl` in order to pass this (or other) option to the filesystem mount command. I see that there is `--luks-extra-mount-options` but that appears to be related to the mount of the luks volume itself not the filesystem contained within, though please correct me if I'm not understanding.

### Describe the solution you'd like

I would like to be able to pass at least a compression mount option but I can envision that people may want to pass other filesystem mount options too when creating a user with `homectl` and `--fs-type=btrfs`.

### Describe alternatives you've considered

I though about requesting that homed just _always_ mount a btrfs filesystem with compression enabled, but that probably isn't really a very good idea for any number of reasons.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
> I see that there is `--luks-extra-mount-options` but that appears to be related to the mount of the luks volume itself not the filesystem contained within, though please correct me if I'm not understanding.

"luks volumes" cannot be mounted. Only file systems within them. And that's what this option applies to.
