### ISSUE TITLE
systemd-boot 252 fails to boot on MacBookAir4,2/Mac

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#25363]
### systemd version the issue has been seen with

252.1

### Used distribution

archLinux

### Linux kernel version used

6.0.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

Systemds UEFI boot manager should be loaded and working

### Unexpected behaviour you saw

after upgrading systemd to 252 and updating the UEFI bootloader, my macbook fails to boot my linux install. There are unfortunately no errors, the mac simply skips to the next bootloader available. Only solution is to downgrade to 251. I've never experienced any issue like that, the bootloader has always worked fine

### Steps to reproduce the problem

upgrade a MacBookAir4,2 to systemd-252 and update the bootloader

**Comment by medhefgo** [comment]
Is sd-boot configured to skip showing a menu and boot straight into the first entry or supposed to show a menu? Are you using a unified kernel image?

**Comment by SjonHortensius** [comment]
there is only a single loader entry so I have configured a default and no menu is shown. I'm not using a Unified kernel image

**Comment by medhefgo** [comment]
I you press space during boot does the sd-boot menu appear? It would be great if you could do a bisection to find the cause of the regression…

**Comment by SjonHortensius** [comment]
there's 202 commits between v251 and v252 in [src/boot](../tree/v252/src/boot) - can I expect to find the fault in there or should the whole tree be disected? Can I compile only the relevant bootctl code or should I compile the whole tree?

**Comment by medhefgo** [comment]
You can limit it to `src/boot/efi` and you only have to build the `systemd-boot` target.

**Comment by doyonm** [comment]
I have the same problem on a macpro 2009.

Boot Menu does not show up. A flashing disk icon is displayed.

If I boot with archiso on usb, this error is displayed in red before booting on usb : Error getting loaded image path: ? 

This string can be found at line 2681 in src/boot/efi/boot.c

systemd version :252.1
Used distribution : archLinux
Linux kernel version used : 6.0.8-arch1-1

Hope this help

**Comment by medhefgo** [comment]
That error message is bugged, a fix for that is in https://github.com/systemd/systemd/pull/25373, but that is unlikely to be the issue at hand here.

You'll either have to litter the code with print calls to find the culprit or better yet, do a bisection to find the commit that causes this.

**Comment by SjonHortensius** [comment]
I wouldn't mind attempting to disect this, but I have no experience with meson, would you mind providing some pointers on how to compile the systemd-boot target? I'm using Arch and for your reference, the complete recipe for building the full package can be found [here](https://github.com/archlinux/svntogit-packages/blob/packages/systemd/trunk/PKGBUILD)
It seems most (if not all) of the customizations / patches don't apply to `systemd-boot`

**Comment by medhefgo** [comment]
No need to involve pacman (other then to get the build deps) for this we are only interested in the boot loader:
```sh
git clone https://github.com/systemd/systemd.git
cd systemd
git bisect v252 v251
meson -Dgnu-efi=true build
ninja -C build systemd-boot
cp build/src/boot/efi/systemd-bootx64.efi $ESP/EFI/Linux/sdboot.efi
bootctl set-timeout 5
```
When using v251 as boot loader you should now see a separate system-boot entry in the boot menu that you can boot directly to test the build (double check the version info by pressing `p` after booting that entry).

From there do the usual `git bisect good/bad`, rebuild and retest.

**Comment by SjonHortensius** [comment]
616a80fe1aa94fae84e488c3cda4237e7b3c1759 is the first bad commit

**Comment by medhefgo** [comment]
> [616a80f](https://github.com/systemd/systemd/commit/616a80fe1aa94fae84e488c3cda4237e7b3c1759) is the first bad commit

Does it still not show an error message (when started from sd-boot)? If it does, please try https://github.com/systemd/systemd/pull/25373 to get the proper error code (though I have a guess to what it is).

**Comment by SjonHortensius** [comment]
Ah, I didn't realize I would get more useful output when running it like that, I replaced the whole bootloader to ensure the bisected version was executed.

It does fortunately print more, after manually updating `boot.c` as per your diff it prints `Error getting loaded image path: Not Found`. Please let me know if the `drivers.c` change is also relevant

**Comment by marcosfrm** [comment]
Maybe related:

https://github.com/pbatard/efifs/issues/21

**Comment by vp1981** [comment]
Hello. I seem to have the same problem. The same OS (Archlinux, x86_64), systemd and kernel (only installed couldn't boot it). This is on my ASUS K43E laptop. Though it has a bit buggy (?) EFI, but it used to boot without problems with systemd-boot. Now, when booting the laptop I see the message `Error getting loaded image path: ?`.

**Comment by medhefgo** [comment]
Please give #25409 a try.

**Comment by vp1981** [comment]
I tried the #25409, and it works!

Details of my steps: on working Arch Linux host I did
```
$ git clone https://github.com/systemd/systemd.git
$ cd systemd
$ git fetch origin pull/25409/HEAD:b25409
$ git checkout b25409
$ meson -Dgnu-efi=true build
$ ninja -C build systemd-boot
$ cp build/src/boot/efi/systemd-bootx64.efi PATH_ON_BOOTABLE_USB/systemd-bootx64.efi
```
On the laptop, I booted from the bootable USB to which I copied the `systemd-bootx64.efi`. Since I don't have any other system on the laptop I copied the efi file to `EFI/systemd` and `EFI/BOOT`
```
# ### mount / as /mnt
# ### mount /boot as /mnt/boot
# ### mount USB EFI as /media
# cd /media
# cp systemd-bootx64.efi /mnt/boot/EFI/systemd/system-bootx64.efi
# cp systemd-bootx64.efi /mnt/boot/EFI/BOOT/BOOTX64.EFI
```
After that I was able to boot into Arch Linux on the laptop. Then I immediately installed the updates (kernel) and (remotely) rebooted the laptop, it booted just fine.

**Comment by SjonHortensius** [comment]
@vp1981 yes for me too, but two notes:

* the correct command is `git fetch origin pull/25409/head:b25409`
* there is a newly introduced dependency on `efibind.h` which required me to install the `gnu-efi` package on arch

**Comment by medhefgo** [comment]
Of course you need gnu-efi to build it, that's nothing new. And the binary is larger because it's a debug build.

**Comment by diegoe** [comment]
I can confirm your branch fixes the failed black screen boot @medhefgo.

FTR, here's the info for my system, according to `p` in the `systemd-boot` menu (which I can finally see)

```
systemd-boot version: 252-387-g29db3e5
loaded image: \EFI\BOOT\BOOTX64.efi
loader partition UUID: 1C56E58E-DDDC-4540-BF69-ECF18DADBB77
architecture: x64
UEFI specification: 1.10
firmware vendor: Apple
firmware version: 1.10
OS indications: 0
secure boot: no (unsupported)
shim: no
TPM: no
console mode: 0/2 (80x25 @2560x1600)
Press any key to continue, ESC or a to quit.
```

This is a MacBookPro 13 (Late 2013) (`MacBookPro11,1`).

**Comment by diegoe** [comment]
@medhefgo The latest update of your PR continues to work for me. Thanks.

One related issue I have noticed is that holding down a key to force the menu to show does not work. I can only get a menu by setting a `timeout` in the config file. I can open a new issue for that if this seems unrelated.

**Comment by medhefgo** [comment]
> One related issue I have noticed is that holding down a key to force the menu to show does not work. I can only get a menu by setting a `timeout` in the config file. I can open a new issue for that if this seems unrelated.

Holding the key usually doesn't work with firmware in the wild. Generally, spamming a key (I recommend space) should work.

**Comment by diegoe** [comment]
> Holding the key usually doesn't work with firmware in the wild. Generally, spamming a key (I recommend space) should work.

Indeed, spamming space works. Holding it down does not work. Thanks
