### ISSUE TITLE
Fstab octal codes

### ISSUE THREAD

**Issue by Colour-Screen** [systemd/systemd#25371]
### systemd version the issue has been seen with

systemd 251.7-4

### Used distribution

Arch Linux

### Linux kernel version used

6.0.7

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

While it's seemingly impossible to find a canonical fstab manual, mount provided by util-linux translates octal codes to ascii that system-d doesn't, while system-d translates \040 into a space character, it doesn't translate \050 and \051 into left and right parentheses, there are probably more codes where this discrepancy exists.

### Steps to reproduce the problem

Use back slashed octal codes in the /etc/fstab file

**Comment by yuwata** [comment]
Could you show an example fstab entry?

**Comment by poettering** [comment]
the canonical implementation of an fstab parser that we all should follow is glibc's getmntent(). And for that glibc documents:

> Since fields in the mtab and fstab files are separated by whitespace, octal escapes are used to represent the characters space (\040), tab (\011), newline (\012), and backslash (\\) in those files when they occur in one of the four strings in a mntent structure.  The routines addmntent() and getmntent() will convert from string representation to escaped representation and back.  When converting from escaped representation, the sequence \134 is also converted to a backslash.

It says nothing about other than these four chars.

Also note, we actually parse this via libmount, the same library that /bin/mount actually uses. So we actually should come to the exact same results.

Anyway, this bug report is very light on details. Where precisely are you seeing these issues? How can this be reproduced?

**Comment by poettering** [comment]
right, we indeed still use the glibc apis for some things.

either way, i figure if glibc and libmount disagree, that's between them. We can't do much about this.

but before we close this, @Colour-Screen please let us know how precisely you ran into this, see my earlier quetsions

**Comment by Colour-Screen** [comment]
It turns out mount doesn't mind the raw special characters, I was trying to fix things and vim highlights them as an error, anyway with the following paths:
/mnt/mountpoint
/mnt/mountsourcewithparentheses()
And /etc/fstab looking like this:
# <file system> <dir> <type> <options> <dump> <pass>
/mnt/mountsourcewithparentheses\050\051 /mmt/mountpoint none bind 0 2
mount succeeds in mounting whereas systemd on boot fails, with the following error:
mnt-mountpoint.mount : Failed to make bind mount source '/mnt/bindmountsourcewithparentheses\050\051', ignoring: No such file or directory

-------- Original Message --------

**Comment by ldv-alt** [comment]
A bit of history:
* from one side, mount started using its own bundled edition of `getmntent` in 1998, it indeed translated all 3-digit octal codes, and years later the corresponding libmount code was based on that old code from mount.
* from another side, `getmntent` in glibc started translating a few octal codes in 1999, it has never been able to translate all 3-digit octal codes like mount did.

**Comment by karelzak** [comment]
Yes, mount/libmount accepts all octal codes, and we don't want to change it after all the years :-)

**Comment by poettering** [comment]
So, I think there's value in getting the discrepancy cleaned up between glibc and libmount, but this really is out of scope for systemd upstream. Please file a bug against either (or both) projects if you'd like to see this cleaned up.
