### ISSUE TITLE
Release critical: dracut initrd boot broken by 36c16a7cdd6c33d7980efc2cd6a2211941f302b4

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#2537]
I'm running one of my system with system updated frequently from git for testing purposes.
When updating to linux 4.4.1, the initramfs was regenerated by dracut (044), and the system didn't boot anymore, the logs starting with a timeout from dev-sda5.device (the root device).
Reverting 36c16a7cdd6c33d7980efc2cd6a2211941f302b4 fixes the issue.

Ftr, the logs without the revert: https://gist.github.com/Keruspe/738f39119a3d0472a37c

**Comment by Keruspe** [comment]
The logs with debug enabled https://gist.github.com/Keruspe/36d348571bd98451d8f7

**Comment by Keruspe** [comment]
Actually, not sure what the right solution is here, but https://github.com/haraldh/dracut/pull/114 seems to fix it too.

From what I read though, USEC_INFINITY is supposed to be "never", when 0 is supposed to be "no". In this cas 0 really seems not to be "no" but to really be 0 as the device immediately timeouts.

**Comment by poettering** [comment]
Fix waiting in PR #2555
