### ISSUE TITLE
systemd built-in OOM killer (*not* systemd-oomd) kills all processes in user session/scope unit upon kernel OOM and doesn't respect OOMPolicy=

### ISSUE THREAD

**Issue by drvink** [systemd/systemd#25376]
### systemd version the issue has been seen with

252.1-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.0.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Normal kernel OOM killer behavior, because the kernel is able to do the job perfectly well on its own.

### Unexpected behaviour you saw

systemd will kill an entire user slice's scope unit when a process under the scope is OOM killed by the kernel, wrecking *everything* the user was doing instead of limiting the damage to a single offending process. (As a bonus, explicitly disabling this "feature" also doesn't work.)

systemd also lies to you that this will work, even with the reproduction steps below:

```
arch-vm[788]:~% systemctl --user -p DefaultOOMPolicy show
DefaultOOMPolicy=continue
```

### Steps to reproduce the problem

1) Add the following to `/etc/systemd/user.conf.d/resources.conf`:

```
[Manager]
DefaultOOMPolicy=continue
```

Alternatively, edit `/etc/systemd/user.conf` and stick `DefaultOOMPolicy=continue` there; it means the same thing.

2) Run something that eventually triggers the **kernel** OOM killer (this report has **nothing to do with** `systemd-oomd`):

```sh
#!/usr/bin/env sh

exec tail /dev/zero
```

3) After a few seconds, watch as everything you were doing disappears!

### More stuff that doesn't work

* In `/etc/systemd/system.conf`:

  ```
  [Manager]
  DefaultOOMPolicy=continue
  ```

  This will theoretically disable the idiocy for stuff under the system slice, but has no effect on the user slice.

* In `/etc/systemd/system/user-.slice.d/resources.conf` (a "drop-in" which will affect all user slice):

  ```
  [Slice]
  OOMPolicy=continue
  ```

  The `OOMPolicy` key is not recognized under `[Slice]`, while `[Scope]` and `[Service]` are completely unrecognized:

  ```
  Nov 14 15:25:27 arch-vm systemd[1]: /etc/systemd/system/user-.slice.d/resources.conf:2: Unknown key name 'OOMPolicy' in section 'Slice', ignoring.
  ```

* In `/etc/systemd/system/user@.service.d/resources.conf`:
  ```
  [Service]
  OOMPolicy=continue
  ```

  Does nothing.

* In `/etc/systemd/system/session-.scope.d/resources.conf`:

  ```
  [Scope]
  OOMPolicy=continue
  ```

  The `OOMPolicy` key is not recognized under `[Scope]`:

  ```
  Nov 14 15:22:04 arch-vm systemd[1]: /etc/systemd/system/session-.scope.d/resources.conf:2: Unknown key name 'OOMPolicy' in section 'Scope', ignoring.
  ```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 14 11:53:50 arch-vm sshd[8404]: Accepted publickey for mdl from 192.168.204.1 port 54143 ssh2: RSA SHA256:LLfd0TPd0DL8Abh1c/g+Jb8nTV8i1D6BPGM/7VU6wRo
Nov 14 11:53:50 arch-vm sshd[8404]: pam_unix(sshd:session): session opened for user mdl(uid=1000) by (uid=0)
Nov 14 11:53:50 arch-vm systemd-logind[396]: New session 3 of user mdl.
Nov 14 11:53:50 arch-vm systemd[1]: Started Session 3 of User mdl.
...
Nov 14 12:34:17 arch-vm kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-3.scope,task=tail,pid=8656,uid=1000
Nov 14 12:34:17 arch-vm kernel: Out of memory: Killed process 8656 (tail) total-vm:25725656kB, anon-rss:25720108kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:50388kB oom_score_adj:0
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: A process of this unit has been killed by the OOM killer.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8404 (sshd) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8409 (sshd) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8411 (zsh) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd[1]: session-3.scope: Killing process 8656 (tail) with signal SIGKILL.
Nov 14 12:34:17 arch-vm systemd-logind[396]: Session 3 logged out. Waiting for processes to exit.
Nov 14 12:34:18 arch-vm systemd[1]: session-3.scope: Failed with result 'oom-kill'.
Nov 14 12:34:18 arch-vm systemd[1]: session-3.scope: Consumed 16.369s CPU time.
Nov 14 12:34:18 arch-vm systemd-logind[396]: Removed session 3.
```

**Comment by drvink** [comment]
@yuwata The oomd tag is incorrect. As I explicitly said, **oomd is not enabled** here; this is BUILT-IN systemd behavior.

**Comment by poettering** [comment]
I can't parse this. "entire user slice's scope"? 

Each user has a slice unit, and each session within it is encapsulated in a scope unit. Hence not sure what an "entire user slice's scope" is supposed to mean?

**Comment by drvink** [comment]
Yes.

**Comment by drvink** [comment]
Great. It wasn't obvious if any dbus junk needed to be added, and also systemd itself does some things inconsistently: for example, `src/core/service.c` checks `s->cgroup_context.delegate` directly in `service_add_extras`, while `src/core/scope.c` uses `unit_cgroup_delegate` in `scope_start` (which checks the vtable for `can_delegate` and whatnot) to do presumably the same thing, even though only scope units are passed to `scope_start`, but I don't think any of this matters. Feel free to add your genius to the PR I've just sent; it fixes the problem for me.

**Comment by ralokt** [comment]
Are there any known workarounds? I'm affected by this, and it's incredibly annoying...

Nothing like restarting your editor,  all your browser profiles, and a large number of terminal sessions (with their histories lost to the sands of KILL -9) once an hour to really spice up a workday :/

**Comment by poettering** [comment]
@drvink btw, I'd be fine with switching to OOMPolicy=continue for the scope units created for login sessions. but scopes in generall should probably stick to OOMPolicy=kill

**Comment by poettering** [comment]
and also, just stop the bs about "junk", "genius", "insane" and stuff. Not the place here for this tone.

**Comment by drvink** [comment]
> Are there any known workarounds? I'm affected by this, and it's incredibly annoying...

@ralokt Assuming you log in at a tty like a Real Computer Man and not some xdm-using quiche eater, the following steps should protect even your X server from systemd's wrath:

1. `systemd-run --user -p OOMPolicy=continue --service-type=forking -- screen -d -m`
2. `screen -dr`
3. `startx`
4. ???
5. Profit

(I'm pretty sure the issue only affects scope units, so the idea here is simply to run a *service* unit with a process that happens to be something useful for running more stuff.)

**Comment by ralokt** [comment]
@drvink sadly, I really enjoy pastries. However, I guess it might be time for me to complete my coming-of-age ritual :)

Thanks for the suggestion!

**Comment by spbnick** [comment]
Could somebody please post a clear explanation on how to get the fix for this and how to use it?

Should we wait for another systemd release, or was this already released? Would it be systemd v253 as the milestone implies? If yes, when should I expect the release? Which version do I need to have this fixed? Once I have the version, which settings do I need to stop systemd from killing my entire session when a single process goes OOM? Are there any workarounds to use before that?

I'm getting tired of all my precious tmux sessions getting wiped when chrome or firefox get too eager with their memory use :see_no_evil: 

Thank you!

**Comment by poettering** [comment]
@spbnick ping you distro, they might consider backporting this. But it's really up to them.

**Comment by drvink** [comment]
@spbnick Try what I posted earlier? I didn't test it but I think it ought to work based on what I understood while diagnosing and fixing the bug.

**Comment by spbnick** [comment]
Thanks, Lennart. Yeah I would go to the distro (Debian) with a question about a backport, if the fixed systemd is not released soon. Or just rebuild it myself with the patch. However, I'd still like to know when the fixed systemd is gonna be released approximately, to perhaps avoid doing the work. And afterwards, I would still like to know how to actually enable the fix.

@drvink, thank you. Do you mean the [comment](https://github.com/systemd/systemd/issues/25376#issuecomment-1326440102) recommending using startx after manual session setup?

**Comment by drvink** [comment]
@spbnick yes

**Comment by nicolas17** [comment]
I found a workaround that doesn't require compiling systemd from source: disable MemoryAccounting for the unit in question (or DefaultMemoryAccounting=no in user.conf). The oom-kill status stuff is disabled in systemd if memory accounting is off, even for scope units before OOMPolicy was implemented for it.

**Comment by richardjharris** [comment]
I just installed ElasticSearch on manjaro, the oom-killer killed it for whatever reason and systemd decided to SIGKILL everything in `session-2.scope`, destroying my X session.

**Comment by jedwabny** [comment]
It's incredible that systemd is doing some oom killing after kernel already did his job even if I have no systemd-oomd installed.

I'm constantly loosing my entire X session because of Teams (even on 16GB PC) which is properly killed by Kernel and it should be enough. Why is then system killing entire user session implemented for???!!!  We have pretty nice Deny of Service by single memory leaking process!

Why I have to reconfigure all PCs that I'm responsible for because you decided to activate this KILL EVERYTHING "feature" by default? Thanks to that "feature" Linux looks very professional...

Yet another problem created by systemd replacing piece by piece every part of Linux with it's mysterious behaviors. Now it's time to replace kernel features. Nice....

**Comment by MasterDDT** [comment]
So just to confirm, the workaround here is set `DefaultOOMPolicy=continue` in `/etc/system/system.conf`? That means if a process in a unit is killed the rest of the unit keeps continues running?

**Comment by koitsu** [comment]
> So just to confirm, the global workaround here is set `DefaultOOMPolicy=continue` in `/etc/system/system.conf`? That means if a process in a unit is killed the rest of the unit keeps continues running?

* Short answer: probably, but may depend on distro. See `systemd-system.conf(5)` for pathname details.
* Long answer: for me on on Ubuntu 22.04.3 LTS jammy -- rather than risk changing the distro-managed `/etc/system/systemd.conf` -- I chose to add the line to new file `/etc/systemd/system.conf.d/local.conf` instead

**Comment by 4DallasC** [comment]
Just adding my 2 cents on this one. The poor OOM documentation needs to be addressed.
