### ISSUE TITLE
tpm2-tss 4.0 release and .so-version change

### ISSUE THREAD

**Issue by AndreasFuchsTPM** [systemd/systemd#25391]
This is a heads up: tpm2-tss is approaching 4.0 release.
We will have to roll the .so version since we need to change the results from Esys_GetCapability for TPM2_CAP_VENDOR and according unmarshaling function.
So even though this does not touch the systemd use of our lib, we still need to change it.

Thus, you will have to update the `.so.0` to `.so.1` here:
https://github.com/systemd/systemd/blob/bf1886226724b3db0779d643195d428575cff0be/src/shared/tpm2-util.c#L65
https://github.com/systemd/systemd/blob/bf1886226724b3db0779d643195d428575cff0be/src/shared/tpm2-util.c#L99

For discussions, I've opened https://github.com/tpm2-software/tpm2-tss/issues/2483 as well.

**Comment by DaanDeMeyer** [comment]
We should stop hardcoding these in code and just figure out the so major name in meson and set a define which we use in code so this doesn't affect us unless API is broken which will result in a compilation error

**Comment by AndreasFuchsTPM** [comment]
Ok, so after some long discussion in tpm2-tss we will not bump the major version of the soname.
We will bump the minor version, but dlopen in systemd uses major only.
Rational is that the change code path was disfunctional anyways (not a good from our side, but helps here).
I will close this ticket now, since there is no AI for systemd.
