### ISSUE TITLE
stdout overwriting logger output for service units

### ISSUE THREAD

**Issue by jcmalek** [systemd/systemd#25416]
### systemd version the issue has been seen with

246

### Used distribution

Poky (Yocto Project Reference Distro) 3.2.4 \n \l

### Linux kernel version used

5.12.10

### CPU architectures issue was seen on

arm

### Component

journalctl

### Expected behaviour you didn't see

Expected both logger and standard output to appear in service unit logs:

journalctl -f -u test
Nov 16 15:05:08 c-00012 sh[1617]: Standard output: 1
Nov 16 15:05:08 c-00012 root[1650]: Logger: 1
Nov 16 15:05:08 c-00012 sh[1617]: Standard output: 2
Nov 16 15:05:08 c-00012 root[1652]: Logger: 2
Nov 16 15:05:09 c-00012 sh[1617]: Standard output: 3
Nov 16 15:05:09 c-00012 root[1654]: Logger: 3
Nov 16 15:05:10 c-00012 sh[1617]: Standard output: 4
Nov 16 15:05:10 c-00012 root[1656]: Logger: 4
Nov 16 15:05:11 c-00012 sh[1617]: Standard output: 5
Nov 16 15:05:11 c-00012 root[1658]: Logger: 5

### Unexpected behaviour you saw

I only get the standard output messages and every once and a while one of the logger messages sneaks through:

journalctl -f -u test
Nov 16 15:05:08 c-00012 sh[1617]: Standard output: 1
Nov 16 15:05:08 c-00012 sh[1617]: Standard output: 2
Nov 16 15:05:09 c-00012 sh[1617]: Standard output: 3
Nov 16 15:06:09 c-00012 root[1654]: Logger: 3
Nov 16 15:05:10 c-00012 sh[1617]: Standard output: 4
Nov 16 15:05:11 c-00012 sh[1617]: Standard output: 5

### Steps to reproduce the problem

test.service contents:
```
[Unit]
Description=Test
DefaultDependencies=no


[Service]
Type=oneshot
ExecStart=/bin/sh /mytest.sh
RemainAfterExit=yes
```

/mytest.sh contents:
```
#!/bin/sh
i=0
while [ $i -le 100 ]; do
  echo "Standard output: ${i}"
  logger "Logger: ${i}"
  sleep 1
  i=$((i+1))
done
```

1. journalctl -f -u test
2. systemctl start test

**Comment by yuwata** [comment]
Sorry, this is an upstream bug tracker. Please test the reproducer with the recent releases of systemd or the current git HEAD. And request to reopen this if still relevant. Closing, at least tentatively.
