### ISSUE TITLE
launching kexec.target fails because efi partition is unmounted already

### ISSUE THREAD

**Issue by felagund** [systemd/systemd#25417]
### systemd version the issue has been seen with

251

### Used distribution

Kubuntu 22.10

### Linux kernel version used

5.19.0-23

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-boot

### Expected behaviour you didn't see

I would expect that the following three commands will result in kexec:

    systemctl kexec
    systemctl start kexec.target --job-mode=replace-irreversibly
    qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

I am using systemd-boot, so my system follows the Boot Loader Specification.

### Unexpected behaviour you saw

     systemctl start kexec.target --job-mode=replace-irreversibly
     qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

did not result in kexec, I got the following error message:

    nov 16 10:39:04 GreenOne systemctl[2041]: No kexec kernel loaded and autodetection failed.
    nov 16 10:39:04 GreenOne systemctl[2041]: Cannot automatically load kernel: ESP mount point not found.
    nov 16 10:39:04 GreenOne systemctl[2041]: Failed to load kexec kernel, continuing without.

As per https://lists.freedesktop.org/archives/systemd-devel/2022-August/048235.html, it is because

> systemctl attempts to autodetect kernel
> for kexec and it needs ESP; final call to "systemctl --force kexec"
> happens late, when ESP (/boot/efi in your case) is already unmounted.

Putting the following to `/etc/systemd/system/boot-efi.mount.d/nodef.conf`:

    [Unit]
    DefaultDependencies=false

and the following to `/etc/systemd/system/systemd-fsck@dev-disk-by\\x2duuid-893B\\x2d91D8.service.d/exit.conf`

    [Service]
    RemainAfterExit=false

(replace `893B` and `91D8` with the first and second part of the UUID of your `/boot/efi`.)

makes the above commands work.

### Steps to reproduce the problem

Run either of the following on Kubuntu 22.10 (fresh install with systemd-boot turned on, I used this guide to set it up: https://blobfolio.com/2018/replace-grub2-with-systemd-boot-on-ubuntu-18-04/ – - not sure if this is distro specific, or even hardware specific. I tried this on Thinkpad X1 Extreme gen 2 and Thinkpad x1 Nano gen 1).

    systemctl start kexec.target --job-mode=replace-irreversibly
    qdbus --system org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit kexec.target replace-irreversibly

Reported as instructed on the mailing list (I was waiting for my distro's systemd to catch up with one recent enough to be allowed to report a bug): https://lists.freedesktop.org/archives/systemd-devel/2022-August/048237.html

I was also confused by the documentation here: https://github.com/systemd/systemd/issues/24588

**Comment by poettering** [comment]
I guess systemd-gpt-auto-generator needs to generate efi.mount and boot.mount so that they are activated if systemd-kexec.service is requested. 

distros that use the weird /boot/efi/ ath would have to add that manually, i don't think we should implement that in systemd. It's such a bad idea to mount the ESP nested under /boot/

**Comment by felagund** [comment]
> distros that use the weird /boot/efi/ ath would have to add that manually, i don't think we should implement that in systemd. It's such a bad idea to mount the ESP nested under /boot/

Where should the ESP be mounted then? as a separate directory in root?

**Comment by poettering** [comment]
→ https://0pointer.net/blog/linux-boot-partitions.html
