### ISSUE TITLE
systemd-cryptenroll implicitly references /run/systemd/tpm2-pcr-signature.json when verification was not requested

### ISSUE THREAD

**Issue by vittyvk** [systemd/systemd#25435]
### systemd version the issue has been seen with

252

### Used distribution

Fedora 38

### Linux kernel version used

6.1.0-0.rc4.20221111git4bbf3422df78.39.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup, other

### Expected behaviour you didn't see

(Note: there's no "systemd-cryptenroll" component to pick, using "systemd-cryptsetup" instead)

I'm only able to  issue new signed PCR policies for **current** PCR state but I'd like to issue a new
policy for **expected* PCR state instead. This is needed to implement kernel upgrade use-case when
private key which signed TPM2 signature is not available, e.g. the currently running UKI was signed
by one key and we need to install a new kernel where PCR state is signed by a complete different key (and neither of the two private keys is available on the target machine so I can't just sign current PCR state with the new key).

What works well (current PCR state):
```
# truncate -s 20M /tmp/test.img
# echo -n passphrase >/tmp/passphrase
# chmod 600 /tmp/passphrase
# cryptsetup luksFormat -q --pbkdf pbkdf2 --pbkdf-force-iterations 1000 --use-urandom /tmp/test.img /tmp/passphrase 
# openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "/tmp/pcrsign-private.pem"
..<snip>
# openssl rsa -pubout -in "/tmp/pcrsign-private.pem" -out "/tmp/pcrsign-public.pem"
writing RSA key
# /usr/lib/systemd/systemd-measure sign --current --bank=sha1 --bank=sha256 --private-key="/tmp/pcrsign-private.pem" --public-key="/tmp/pcrsign-public.pem" --phase=: | tee "/tmp/pcrsign.sig"
{"sha1":[{"pcrs": [11] 
 <snip>
# systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key="/tmp/pcrsign-public.pem" --tpm2-signature="/tmp/pcrsign.sig" /tmp/test.img 
New TPM2 token enrolled as key slot 1.
```

Now let's try to issue a new policy for non-current PCR state:
```
# echo HALLO > /tmp/tpmdata1
# echo foobar > /tmp/tpmdata2
#  /usr/lib/systemd/systemd-measure sign --linux=/tmp/tpmdata1 --initrd=/tmp/tpmdata2 --private-key="/tmp/pcrsign-private.pem" --public-key="/tmp/pcrsign-public.pem" --bank=sha1 --bank=sha256 --phase=: | tee "/tmp/pcrsign.sig2"
# systemd-cryptenroll --wipe-slot=tpm2 /tmp/test.img 
Wiped slot 1.
# systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key="/tmp/pcrsign-public.pem" --tpm2-signature="/tmp/pcrsign.sig2" /tmp/test.img 
Couldn't find signature for this PCR bank, PCR index and public key.
```

Expected:
```
"New TPM2 token enrolled as key slot 1."
```

### Unexpected behaviour you saw

With some debug

```
# export SYSTEMD_LOG_LEVEL=debug
Allocating context for crypt device /tmp/test.img.
Trying to open and read device /tmp/test.img with direct-io.
Trying to open device /tmp/test.img without direct-io.
Initialising device-mapper backend library.
Trying to load LUKS2 crypt type from device /tmp/test.img.
Crypto backend (OpenSSL 3.0.5 5 Jul 2022 [default][legacy]) initialized in cryptsetup library version 2.5.0.
Detected kernel Linux 6.1.0-0.rc4.20221111git4bbf3422df78.39.fc38.x86_64 x86_64.
Loading LUKS2 header (repair disabled).
Acquiring read lock for device /tmp/test.img.
Verifying lock handle for /tmp/test.img.
Device /tmp/test.img READ lock taken.
Trying to read primary LUKS2 header at offset 0x0.
Opening locked device /tmp/test.img
Verifying locked device handle (regular file)
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:0eacae40f649fea7a69923dfb721fdeedfc6f73eb3c4ab0db5050417390b5ef2 (on-disk)
Checksum:0eacae40f649fea7a69923dfb721fdeedfc6f73eb3c4ab0db5050417390b5ef2 (in-memory)
Trying to read secondary LUKS2 header at offset 0x4000.
Reusing open ro fd on device /tmp/test.img
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:c0dd239db092991d35659be859038a3370596b68578ce921ec63581d47e90b36 (on-disk)
Checksum:c0dd239db092991d35659be859038a3370596b68578ce921ec63581d47e90b36 (in-memory)
Device size 20971520, offset 16777216.
Device /tmp/test.img READ lock released.
PBKDF argon2id, time_ms 2000 (iterations 0), max_memory_kb 1048576, parallel_threads 4.
Requesting JSON for token 0.
Requesting JSON for token 1.
Requesting JSON for token 2.
Requesting JSON for token 3.
Requesting JSON for token 4.
Requesting JSON for token 5.
Requesting JSON for token 6.
Requesting JSON for token 7.
Requesting JSON for token 8.
Requesting JSON for token 9.
Requesting JSON for token 10.
Requesting JSON for token 11.
Requesting JSON for token 12.
Requesting JSON for token 13.
Requesting JSON for token 14.
Requesting JSON for token 15.
Requesting JSON for token 16.
Requesting JSON for token 17.
Requesting JSON for token 18.
Requesting JSON for token 19.
Requesting JSON for token 20.
Requesting JSON for token 21.
Requesting JSON for token 22.
Requesting JSON for token 23.
Requesting JSON for token 24.
Requesting JSON for token 25.
Requesting JSON for token 26.
Requesting JSON for token 27.
Requesting JSON for token 28.
Requesting JSON for token 29.
Requesting JSON for token 30.
Requesting JSON for token 31.
Keyslot 0 priority 1 != 2 (required), skipped.
Trying to open LUKS2 keyslot 0.
Running keyslot key derivation.
Reading keyslot area [0x8000].
Acquiring read lock for device /tmp/test.img.
Verifying lock handle for /tmp/test.img.
Device /tmp/test.img READ lock taken.
Reusing open ro fd on device /tmp/test.img
Device /tmp/test.img READ lock released.
Verifying key from keyslot 0, digest 0.
Using TPM2 TCTI driver 'device' with device '/dev/tpmrm0'.
Loaded TCTI module 'tcti-device' (TCTI module for communication with Linux kernel interface.) [Version 2]
TPM successfully started up.
Creating primary key on TPM.
Successfully created ECC primary key on TPM.
Generating primary key on TPM2 took 13ms.
Starting HMAC encryption session.
Starting authentication session.
PCR 7 value: b92c19a9f1628340fc49efa1ba6749a68e34f35e
PCR 11 value: 0000000000000000000000000000000000000000
PCR 7 value: dd794f2d0c4cfa28dc9b5a3266e8516378ba551190d9844c38b890f7ad272049
PCR 11 value: 0000000000000000000000000000000000000000000000000000000000000000
TPM2 device supports SHA256 PCR bank and SHA256 PCRs are valid, yay!
Configuring public key based PCR policy.
Configuring hash-based PCR policy.
Acquiring policy digest.
Session policy digest: 55e71efc9a2b2e55c75fd1b00237a5b7285ab83e068b10fe3e480a9fa7451434
Not adding TPM2 entropy to the kernel random pool again.
Generating secret key data.
Creating HMAC key.
Marshalling private and public part of HMAC key.
Completed TPM2 key sealing in 568.304ms.
Requesting JSON for token 0.
Requesting JSON for token 1.
Requesting JSON for token 2.
Requesting JSON for token 3.
Requesting JSON for token 4.
Requesting JSON for token 5.
Requesting JSON for token 6.
Requesting JSON for token 7.
Requesting JSON for token 8.
Requesting JSON for token 9.
Requesting JSON for token 10.
Requesting JSON for token 11.
Requesting JSON for token 12.
Requesting JSON for token 13.
Requesting JSON for token 14.
Requesting JSON for token 15.
Requesting JSON for token 16.
Requesting JSON for token 17.
Requesting JSON for token 18.
Requesting JSON for token 19.
Requesting JSON for token 20.
Requesting JSON for token 21.
Requesting JSON for token 22.
Requesting JSON for token 23.
Requesting JSON for token 24.
Requesting JSON for token 25.
Requesting JSON for token 26.
Requesting JSON for token 27.
Requesting JSON for token 28.
Requesting JSON for token 29.
Requesting JSON for token 30.
Requesting JSON for token 31.
PCR policy hash not yet enrolled, enrolling now.
Unsealing for verification...
Unmarshalling private part of HMAC key.
Unmarshalling public part of HMAC key.
Using TPM2 TCTI driver 'device' with device '/dev/tpmrm0'.
Loaded TCTI module 'tcti-device' (TCTI module for communication with Linux kernel interface.) [Version 2]
TPM successfully started up.
Creating primary key on TPM.
Successfully created ECC primary key on TPM.
Generating primary key on TPM2 took 13ms.
Loading HMAC key into TPM.
Starting HMAC encryption session.
Starting authentication session.
PCR 7 value: dd794f2d0c4cfa28dc9b5a3266e8516378ba551190d9844c38b890f7ad272049
PCR 11 value: 0000000000000000000000000000000000000000000000000000000000000000
Configuring public key based PCR policy.
Couldn't find signature for this PCR bank, PCR index and public key.
Releasing crypt device /tmp/test.img context.
Releasing device-mapper backend.
Closing read only fd for /tmp/test.img.
```

when the used signature doesn't match current PCR state.

### Steps to reproduce the problem

```
# truncate -s 20M /tmp/test.img
# echo -n passphrase >/tmp/passphrase
# chmod 600 /tmp/passphrase
# cryptsetup luksFormat -q --pbkdf pbkdf2 --pbkdf-force-iterations 1000 --use-urandom /tmp/test.img /tmp/passphrase 
# openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "/tmp/pcrsign-private.pem"
# openssl rsa -pubout -in "/tmp/pcrsign-private.pem" -out "/tmp/pcrsign-public.pem"
# echo HALLO > /tmp/tpmdata1
# echo foobar > /tmp/tpmdata2
#  /usr/lib/systemd/systemd-measure sign --linux=/tmp/tpmdata1 --initrd=/tmp/tpmdata2 --private-key="/tmp/pcrsign-private.pem" --public-key="/tmp/pcrsign-public.pem" --bank=sha1 --bank=sha256 --phase=: | tee "/tmp/pcrsign.sig2"
# systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key="/tmp/pcrsign-public.pem" --tpm2-signature="/tmp/pcrsign.sig2" /tmp/test.img 
```

**Comment by poettering** [comment]
Are you booting an UKI? signed PCR policies requires UKIs (i.e. sd-stub), since the EFI stub needs to execute the measurements.

**Comment by vittyvk** [comment]
Yes, I'm using UKI. The example above was a simplified version *without* UKI but I see exactly the same behavior with UKI under the condition that the UKI I'm using had PCRs signature signed with a *different* key.

Here's my "real world" example (CS9 based but this shouldn't matter). Check that we've booted with UKI
```
# tpm2_pcrread sha1:11+sha256:11
  sha1:
    11: 0xADEEE5BD6ADFA88EF3FEF89C0C937A516B2974D7
  sha256:
    11: 0xD306CE4F3691C0E16E8DA0D180EDB1D1E420F695A0897A9B64C4E9C4C9A6B15F
```

Create a test volume
```
# truncate -s 20M /tmp/test.img
# echo -n passphrase >/tmp/passphrase
# chmod 600 /tmp/passphrase
# cryptsetup luksFormat -q --pbkdf pbkdf2 --pbkdf-force-iterations 1000 --use-urandom /tmp/test.img /tmp/passphrase
```

Enroll signed PCR policy for the currently running kernel and check that it works
```
# systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key=/lib/modules/5.14.0-187_uki_test11.el9.x86_64/vmlinuz-virt-pcr-public.pem --tpm2-signature=/lib/modules/5.14.0-187_uki_test11.el9.x86_64/vmlinuz-virt-pcr-signature.json /tmp/test.img 
New TPM2 token enrolled as key slot 1.

# /usr/lib/systemd/systemd-cryptsetup attach testvol /tmp/test.img - tpm2-device=/dev/tpm0
<works!>
```

Now let's try to enroll signed PCR policy for a different kernel. Note: it's PCR signature is signed with a different key:
```
# /usr/lib/systemd/systemd-cryptsetup detach testvol
# # systemd-cryptenroll --wipe-slot=tpm2 /tmp/test.img 
Wiped slot 1.
# systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key=/lib/modules/5.14.0-187_uki_test10.el9.x86_64/vmlinuz-virt-pcr-public.pem --tpm2-signature=/lib/modules/5.14.0-187_uki_test10.el9.x86_64/vmlinuz-virt-pcr-signature.json /tmp/test.img 
Couldn't find signature for this PCR bank, PCR index and public key.
```

Honestly, I don't quite understand why running a UKI is a must if we're trying to issue a policy for a different kernel (which is UKI), zeroed PCR11 should be 'good enough' too. I'm probably missing something important in the TPM2 machinery...

**Comment by poettering** [comment]
> Now let's try to enroll signed PCR policy for a different kernel. Note: it's PCR signature is signed with a different key:
> 
> ```
> # /usr/lib/systemd/systemd-cryptsetup detach testvol
> # # systemd-cryptenroll --wipe-slot=tpm2 /tmp/test.img 
> Wiped slot 1.
> # systemd-cryptenroll --unlock-key-file=/tmp/passphrase --tpm2-device=auto --tpm2-public-key=/lib/modules/5.14.0-187_uki_test10.el9.x86_64/vmlinuz-virt-pcr-public.pem --tpm2-signature=/lib/modules/5.14.0-187_uki_test10.el9.x86_64/vmlinuz-virt-pcr-signature.json /tmp/test.img 
> Couldn't find signature for this PCR bank, PCR index and public key.
> ```
> 
> Honestly, I don't quite understand why running a UKI is a must if we're trying to issue a policy for a different kernel (which is UKI), zeroed PCR11 should be 'good enough' too. I'm probably missing something important in the TPM2 machinery...

You specified the signature on the cryptenroll command line. hence you asked for verification that the disk can be unlocked with current PCRs and the supplied signature. Of course this is going to fail, if you enroll things with the wrong PCR state then. To quote the man page:

> If a signature file is specified or found it is used to verify if the volume can be unlocked with it given the current PCR state, before the new slot is written to disk. This is intended as safety net to ensure that access to a volume is not lost if a public key is enrolled for which no valid signature for the current PCR state is available. If the supplied signature does not unlock the current PCR state and public key combination, no slot is enrolled and the operation will fail. If no signature file is specified or found no such safety verification is done.

I am not sure how we could document this any better.

To make this explicit: just drop the signature from the cmdline, so that no verification step is done.

**Comment by poettering** [comment]
> I may be completely wrong but looking at the code in tpm2_make_policy_session(), Esys_PolicyPCR() is always called with
> pcrDigest == NULL, this AFAIU means that _current_ PCR values are used to create policy digest and that's why find_signature() is failing to find it in the JSON (because it was created using _expected_ values).

Yes, this is correct. This is used when unlocking a volume: we calculate the policy for the status quo when unlocking (which includes current PCR state), then use the policy hash to find the signature for that. The signature has to be prepared via systemd-measure, where the expected PCR values are derived from the supplied UKI components, the policy calculated and then signed.

So yes, when unlocking the volume we have to take current PCR state into account, otherwise the excercsie would be entirely pointless. During signature generation we take the synthesized PCR state into account however, as signing the status quo is also kinda pointless...

**Comment by poettering** [comment]
> The example above was a simplified version _without_ UKI but I see exactly the same behavior with UKI under the condition that the UKI I'm using had PCRs signature signed with a _different_ key.

the signed PCR stuff only works with UKIs and sd-stub in the mix. Otherwise noone will measure the components, and thus the PCR values will all remain at zero, and thus no signature will be found for that state.

**Comment by poettering** [comment]
I would strongly advise to read the relevant systemd-measure, systemd-cryptenroll, systemd-stub man pages thoroughly. So far everything you asked was explained there already.

**Comment by vittyvk** [comment]
It does!

```
# ls -la /run/systemd/tpm2-pcr-signature.json
-r--r--r--. 1 root root 4134 Dec 31  1969 /run/systemd/tpm2-pcr-signature.json
# rm -f /run/systemd/tpm2-pcr-signature.json
# systemd-cryptenroll --tpm2-device=auto --tpm2-public-key=/lib/modules/5.14.0-187_uki_test11.el9.x86_64/vmlinuz-virt-pcr-public.pem /dev/vda2
🔐 Please enter current passphrase for disk /dev/vda2: ********                
New TPM2 token enrolled as key slot 0.
```
the volume was correctly attached after booting the target kernel so I guess it does what I need now. Thanks!

**Comment by poettering** [comment]
Ah, very good!

Then we found a bug here. We should not search for a signature unless requested explicitly in the cryptenroll verification step.

Everything else works now?

If this is all, let's rename the issue accordingly.
