### ISSUE TITLE
Disabling kernel install causes build failures

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#25432]
### systemd version the issue has been seen with

252.1

### Used distribution

carbonOS 2022.3

### Linux kernel version used

N/A

### CPU architectures issue was seen on

x86_64

### Component

kernel-install

### Expected behaviour you didn't see

Build completes without error

### Unexpected behaviour you saw

When passing in -Dkernel-install=false to meson, I get a build failure: ` meson.build:3842:8: ERROR: Unknown variable "test_kernel_install_sh".`

### Steps to reproduce the problem

Build systemd v252.1 w/ -Dkernel-install=false

**Comment by yuwata** [comment]
Fix is already waiting in #25389.
