### ISSUE TITLE
network: document default route to interface on IPv6 table

### ISSUE THREAD

**Issue by melvyn2** [systemd/systemd#25440]
### systemd version the issue has been seen with

250.4

### Used distribution

NixOS 22.05

### Linux kernel version used

5.15.60

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

For IPv4 routing tables, the documentation states the following:

> DefaultRouteOnDevice=
>    Takes a boolean. If set to true, sets up the default route bound to the interface. Defaults to false. This is useful when creating routes on point-to-point interfaces. This is equivalent to e.g. the following,
> `
>     ip route add default dev veth99
> `
>     or,
> `
>     [Route]
>     Gateway=0.0.0.0
> `
>     **Currently, there are no way to specify e.g., the table for the route configured by this setting. To configure the default route with such an additional property, please use the following instead:**
> `
>     [Route]
>     Gateway=0.0.0.0
>     Table=1234
> `

However, there is no documentation on how to do the equivalent action for an IPv6 table.
Using the `ip` tool, I can do: `ip -6 route add to default metric 1000 dev <interface> table <table>`

(In the long term, it may be more useful to add a way to select a table to use with `DefaultRouteOnDevice` instead of relying on using an unspecified gateway IP address.)

### Unexpected behaviour you saw

I cannot do any equivalent action in systemd-networkd for IPv6 tables, as using `::/0` instead of `0.0.0.0` as the gateway fails, stating that such an address is not allowed as gateway.

### Steps to reproduce the problem

1. Create an empty routing table and a systemd-networkd network.
2. Add
```
[Route]
Gateway=0.0.0.0
Table=1234
```
To the network configuration
3. Reload the network.
4. Observe the added rule with `ip route show table 1234`
5. Add
```
[Route]
Gateway=::/0
Table=1234
```
To the network configuration.
6. Reload the network.
7. Observe in `systemd-networkd`'s log that it refused to add the rule, and that it is missing from `ip -6 route show table 1234`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-networkd[4165548]: /etc/systemd/network/<name>.network:14: Invalid Gateway='::/0', ignoring assignment: Invalid argument
```

**Comment by yuwata** [comment]
Why with `/0`? Have you tried `Gateway=::`?

**Comment by melvyn2** [comment]
Sorry, mistake on my part. I believed I had tested with just `::` before but it did not work. I'd then change this to a feature request for a way to select a table to use with `DefaultRouteOnDevice`, and in the mean time include using `::` in the documentation where `0.0.0.0` is mentioned.
