### ISSUE TITLE
udev rules causing udev to hang when device enumerates

### ISSUE THREAD

**Issue by samuelfmlourenco** [systemd/systemd#25446]
### systemd version the issue has been seen with

249

### Used distribution

Kubuntu 22.04 LTS

### Linux kernel version used

5.15.0-53-generic

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

udev rules being applied promptly to Microchip devices.

### Unexpected behaviour you saw

Device not being accessible by the drivers (including libusb), while the rules are not being applied, which can take more than three minutes.

### Steps to reproduce the problem

Install MPLABX from Microchip, process which adds the following udev rules:

`
ENV{hotplugscript}="/etc/.mplab_ide/mchplinusbdevice"

ACTION!="add", GOTO="check_remove"
SUBSYSTEM=="usb_device", GOTO="check_add"
SUBSYSTEM!="usb", GOTO="rules_end"

LABEL="check_add"

ATTR{idVendor}=="04d8", MODE="666", RUN+="%E{hotplugscript} add"
ATTR{idVendor}=="03eb", MODE="666", RUN+="%E{hotplugscript} add"
GOTO="rules_end"

LABEL="check_remove"

ACTION=="remove", RUN+="%E{hotplugscript} remove %E{PRODUCT}"

LABEL="rules_end"
`

Any device having Microchip's VID will take time in order to be accessible. The binary at /etc/.mplab_ide/mchplinusbdevice is there and runs well with all the options. This is clearly a systemd/udev issue. People with distros that don't have systemd in it don't have such an issue.

This is clearly disruptive and breaks the user experience. It even made me think that the MCP2210 was a bad chip and shouldn't be used in my future projects, leaving me without any alternatives. The solution for now is to remove all the lines referring to the "hotplugscript".

But I'm expecting, as always, a canned response from the arrogant boss of this project. Funny how he accuses Linus Torvalds of breaking the user experience with a change around the versioning scheme of the kernel, but fails to realize that systemd is badly designed (more so because it relies on the kernel version to run, which is a very bad design practice), and the only possible fix is to yank it from the system.

Anyway, I'm not expecting this to be fixed. I'm only expecting a manual on how to remove this crap from my OS, because I don't wish to have similar misleading issues in the future that are being caused by a component that should have a simple task to run: give permissions to the freaking device! Not hard to do, at all.

**Comment by yuwata** [comment]
There are nothing we can do here. Please contact the project which provides the script.

If you just want to complain something, then please use an SNS.

**Comment by yuwata** [comment]
I found a solution at https://www.microchip.com/forums/m/tm.aspx?m=1051283&p=1
