### ISSUE TITLE
v252 changes name of ethernet adapter on Raspberry Pi 4

### ISSUE THREAD

**Issue by msilletti** [systemd/systemd#25444]
### systemd version the issue has been seen with

252

### Used distribution

ArchARM

### Linux kernel version used

5.15.79-1-rpi-ARCH

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd, systemd-networkd-wait-online

### Expected behaviour you didn't see

Onboard ethernet adapter should be named `eth0`

### Unexpected behaviour you saw

Onboard ethernet adapter was renamed to `end0`

### Steps to reproduce the problem

1. Install the current aarch64 image
2. Update system to systemd v252 and reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ usr/bin/dmesg --human -t | grep eth
bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
bcmgenet fd580000.ethernet end0: renamed from eth0
bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
bcmgenet fd580000.ethernet end0: Link is Down
bcmgenet fd580000.ethernet end0: Link is Up - 1Gbps/Full - flow control off
```
```

**Comment by yuwata** [comment]
That's intended. Please disable the persistent interface renaming if you do not like it.
