### ISSUE TITLE
service: Environment= variables are not available  in ExecStartPre= commands

### ISSUE THREAD

**Issue by steveej** [systemd/systemd#2545]
This would be a nice to have. I haven't tested the other `~ExecStart.+` but consistency should be achieved in all cases.

**Comment by poettering** [comment]
All ExecXYZ= settings already support that.

**Comment by wdoekes** [comment]
Are you sure?

With systemd 245.4-4ubuntu3.15 on Ubuntu/Focal the `Environment=` variable is NOT available in `ExecStartPre=` but it is available in `ExecStart=`

**Comment by wdoekes** [comment]
Wait wait.. my bad. Never mind.

I did this:
```
ExecStartPre=/usr/bin/docker pull --quiet $IMAGE >/dev/null
```
And thought it failed on the `$IMAGE`. But it failed on the `>/dev/null`

Carry on, nothing to see here :)
