### ISSUE TITLE
Why is soft LimitNOFILE 1024 by default?

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#25478]
`src/core/system.conf.in:61:#DefaultLimitNOFILE=1024:@HIGH_RLIMIT_NOFILE`

Why is soft ulimit 1024 by default? Does it really make sense of modern systems?

It is confusing when you try to understand why a process gets such a limit but you have no configs with it... For example my nginx hit too many open files.

I would suggest to at least increase the default limits.

**Comment by poettering** [comment]
See: https://0pointer.net/blog/file-descriptor-limits.html
