### ISSUE TITLE
resolved: support for bogus NXDOMAIN replies

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#2548]
In one of the networks I'm connecting, the resolver is hijacking A/AAAA lookups and translating NXDOMAIN responses to a fixed IP in order to redirect to the provider's "value added" search.

I vaguely remember that bind/lwresd had some support for such rogue servers by considering all nxdomain replies non-authoritative, but I'd love if resolved had some very simple approach, and with less latency impact, to handle this scenario.

A new key in resolved.conf:

```
 NXHosts=
```

accepting a list of v4/v6 addresses that, when matched through an A/AAAA lookup, just get translated back to NXDOMAIN.

I'd consider contributing the patch myself if there's consensus on the behavior.

**Comment by poettering** [comment]
Well, if this cannot be handled automatically, wouldn't it be a better idea to use better DNS servers instead (such as 8.8.8.8?)

**Comment by wavexx** [comment]
On 08/02/16 20:20, Lennart Poettering wrote:

> Well, if this cannot be handled automatically, wouldn't it be a better
> idea to use better DNS servers instead (such as 8.8.8.8?)

In theory yes, of course, but in practice on high-latency networks the
difference can be rather substantial. I wouldn't bother otherwise.

**Comment by wavexx** [comment]
On 08/02/16 23:22, Yuri D'Elia wrote:

> In theory yes, of course, but in practice on high-latency networks the
> difference can be rather substantial. I wouldn't bother otherwise.

In that sense, there's the added problem that on some closed networks I
have to use the internal servers, as external ones are not routable. In
these cases, I'd rather have DHCP do it's job.

AFAIK, in networkd I cannot "match" on something like a SSID in order to
override the DNS only for that specific profile. That could be helpful
to mitigate the issue, although not as fast as the initial proposal.

**Comment by poettering** [comment]
Honestly, I am not convinced this is really a logic we should have in resolved, which is supposed to be a simple stub resolver ultimately. It's really not its job to "rewrite" DNS responses. I think if this is necessary, then another implementation should be used, for example unbound, if it supports that.

Sorry, but I think this is simply out of focus for us!

**Comment by wavexx** [comment]
On Tue, Feb 23 2016, Lennart Poettering notifications@github.com wrote:

> Honestly, I am not convinced this is really a logic we should have in resolved,
> which is supposed to be a simple stub resolver ultimately. It's really not its
> job to "rewrite" DNS responses. I think if this is necessary, then another
> implementation should be used, for example unbound, if it supports that.

unbound doesn't provide any advantage for this scenario (sadly). It can
forward specific zones (including "."), but in doing so will consider
NXDOMAIN answers as authoritative. It merely becomes a caching resolver,
with the addition that you'll need the resolvconf machinery to setup the
forwarding.

The option taken by bind (consider NXDOMAIN as always non-authoritative)
also breaks whenever you connect to a network which blocks outbound DNS
queries.

But maybe what I wrote before isn't out of scope: would it be thinkable
to override the DNS servers only for a specific network/SSID?

While not directly addressing the problem, I definitely _can_ configure
a different resolver for the networks I experience issues. I just cannot
specify a fixed default.

And for those looking for a potential solution, REJECTing outbound
packets going to the bogus catch-all IP address is likely the best
solution you can get right now. It still breaks random software (as the
address resolves instead of being unknown), but at least it will fail
predictably downward the stack).

**Comment by lathiat** [comment]
I have another ISP that is doing this (Telstra in Australia - the largest ISP here). They hijack the DNS for domains they need to "filter" for reasons such as malware, piracy, etc (as per government requirements in the latter, and a product feature in the former - sadly even if you don't have their protection feature enabled they still hijack the DNS for those domains and then on the filtering appliance based on your IP just transparently proxy the traffic through untouched - stupid but what are you going to do!).

Unfortunately this server is broken and returns NXDOMAIN for "MX" record lookups when the "A" and "AAAA" already succeeded. In this case resolved appears to cache the NXDOMAIN and forget the already cached A/AAAA responses and thus on the second query you get no results.

lathiat@optane ~$ sudo systemctl restart systemd-resolved
[sudo] password for lathiat: 
lathiat@optane ~$ host launchpadlibrarian.net
launchpadlibrarian.net has address 61.9.242.43
launchpadlibrarian.net has IPv6 address 2001:8002:e61:f002::f5ff
Host launchpadlibrarian.net not found: 3(NXDOMAIN)
lathiat@optane ~$ host launchpadlibrarian.net
Host launchpadlibrarian.net not found: 3(NXDOMAIN)
lathiat@optane ~$ 

I'm not sure if it makes sense to have a configuration "NXHosts" override but it might make sense to consider caching NXDOMAINS specifically with respect to the record type requested. While that shouldn't technically be necessary, unfortunately this behavior is seen in the wild and results in broken DNS on such networks.

The only current evidence I collected is that dnsdist specifically (which I use as my DNS which then forwards onto Telstra) seems to CACHE the NXDOMAIN but for "MX" lookups (it doesn't re-issue the query) only and specifically caches the "A" and "AAAA" lookups separately and doesn't fail them in future based on the NXDOMAIN for the MX query.

It may make sense to split this into a new bug report/pull request but for now I'll document that research in this bug report.
