### ISSUE TITLE
Staircase pattern of text on shutdown

### ISSUE THREAD

**Issue by jonnygrant** [systemd/systemd#25490]
### systemd version the issue has been seen with

251

### Used distribution

Ubuntu 22.10

### Linux kernel version used

5.19.0-23-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Terminal displaying regular left aligned text on shutdown

### Unexpected behaviour you saw

Staircase pattern of text.

I will try add the photo

### Steps to reproduce the problem

Latest Ubuntu with GNOME Flashback (metacity)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
If you can tell me how to adjust to log this, I would be happy to create the logs.
```

**Comment by jonnygrant** [comment]
![staircase__IMG-8178](https://user-images.githubusercontent.com/29703560/203413814-bde3c282-efb1-44be-8c7c-739dd210a940.jpg)

**Comment by jonnygrant** [comment]
I had modified /etc/default/grub to replace GRUB_CMDLINE_LINUX_DEFAULT="quiet splash" with
GRUB_CMDLINE_LINUX_DEFAULT="" 

then ran sudo update-grub2

**Comment by halfline** [comment]
drive by comment... `ONLCR` needs to be paired with `OPOST` to work and a quick `git grep` suggests `OPOST` isn't getting set. 

```
╎❯ git grep ONLCR
src/basic/terminal-util.c:        termios.c_oflag |= ONLCR;

╎❯ git grep OPOST

╎❯ 
```

**Comment by jonnygrant** [comment]
> It seems that `ONLCR` option was reset by something. (systemd sets it up on startup in `console_setup()`/`reset_terminal_fd()`, I wouldn't be surprised it would not survive during runtime.)
> 
> 1. Does it change if you invoke `systemctl daemon-reexec` prior shutdown?

I tried that. Unfortunately no change.
I'll try take a photo.

> 2. How do you issue the shutdown?
Running GNOME Flashback in Ubuntu. So I click the top right computer icon, and then slick "Shut Down..."


May I ask - is there any way systemd could log all this output to a file, so I could go back through it and see? It doesn't go

**Comment by jonnygrant** [comment]
![systemd__IMG-8340](https://user-images.githubusercontent.com/29703560/204793748-18e1fbf7-c761-4494-a418-2a4bd8dae2d4.PNG)

**Comment by Werkov** [comment]
Re: shutdown log, see [Shutdown Completes Eventually](https://freedesktop.org/wiki/Software/systemd/Debugging/#diagnosingshutdownproblems). I'm posting it for reference, it'll surely be noisy and the console issue may not be visible in that log neither.
Your latest screen capture makes me wonder - the bottom part are properly aligned messages, were they actually printed _before_ the non-CR'd lines? (user services may be stopped before dbus (possibly other system service), the picture is not much legible, the full shutdown log may shed some light onto this (also why lightdm is the slow one in both cases....)

@halfline Would you prepare a PR with the implied change? :wink: (You clearly know termios well and it sounds applicable regardless of this issue.)

**Comment by halfline** [comment]
https://github.com/systemd/systemd/pull/25583

**Comment by jonnygrant** [comment]
Great you could fix it.
I could only think what sort of string was being sent to mess up the terminal. Then I thought the only way was to filter out any ANSI control codes that might cause.

**Comment by jonnygrant** [comment]
I wish GRUB had an easy way to start and go to console rather than graphical login. Then I could see what systemd is doing for longer

**Comment by jonnygrant** [comment]
Werkov, May I ask if that page could be updated to show how to edit Grub to book with those debug options please.


It would be great if systemd actually logged in /var/log like dmsg and syslog files are. Is that possible? Also Xorg logs its start and shutdown to a file.

**Comment by Werkov** [comment]
@jonnygrant It's a wiki (amendable), see section [Wiki accounts](https://www.freedesktop.org/wiki/AccountRequests/) (alas, I can't assist you there).

**Comment by jonnygrant** [comment]
> @jonnygrant It's a wiki (amendable), see section [Wiki accounts](https://www.freedesktop.org/wiki/AccountRequests/) (alas, I can't assist you there).

Probably I don't know enough about GRUB. I can raise an issue if that would help?

It's a bit tricky to type out on the command line

systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on enforcing=0
