### ISSUE TITLE
no uevent when block devices change (regression in udev 220)

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#255]
With udev 220, there is no change event any more for block devices when programs like `mkfs` or `e2label` open and change them. This causes e. g. udisks2 to break.

Simple reproducer:

```
 # modprobe scsi_debug
 # udevadm monitor
```

Then run this in another terminal: `#  sh -c '> /dev/sdb'

(Replace `sdb` with the actual scsi_debug drive. This ought to be a harmless command, but don't take chances in destroying your hard disk!)

Up to udev 219 you get

```
KERNEL[40.913525] change /devices/pseudo_0/adapter0/host2/target2:0:0/2:0:0:0/block/sdb (block)
UDEV [41.021205] change /devices/pseudo_0/adapter0/host2/target2:0:0/2:0:0:0/block/sdb (block)
```

With 220 there is no uevent.

**Comment by martinpitt** [comment]
When running udevd in the foreground with --debug, I see this with 219 when I issue the "open /dev/sda" call:

```
inotify event: 8 for /dev/sdb
device /dev/sdb closed, synthesising 'change'
seq 4915 queued, 'change' 'block'
Validate module index
Check if link configuration needs reloading.
seq 4915 forked new worker [10945]
seq 4916 queued, 'change' 'block'
seq 4915 running
removing watch on '/dev/sdb'
value '[dmi/id]sys_vendor' is 'LENOVO'
IMPORT 'scsi_id --export --whitelisted -d /dev/sdb' /lib/udev/rules.d/60-persistent-storage.rules:41
[...]
could not unlink /run/udev/queue: No such file or directory
cleanup idle workers
Unload module index
Unloaded link configuration context.
worker [10945] exited
```

But only this with 220:

```
cleanup idle workers
Unload module indexUnload module index
Unload module indexUnloaded link configuration context.Unload module index

Unloaded link configuration context.
Unloaded link configuration context.
Unloaded link configuration context.Validate module index
Check if link configuration needs reloading.
```

Running systemd-udevd 220/from trunk with the 219 package installed _does_ work; conversely, running systemd-udevd 219 with the 220 package installed _does not_ work. So it seems the regression isn't in the binary itself, but in the udev rules somewhere. Bisecting now..

**Comment by kaysievers** [comment]
b50063512d4be4d29e0ca5d28f66bc1121861e3b ?

**Comment by martinpitt** [comment]
@kaysievers , that indeed looks necessary, but it doesn't seem to be sufficient yet. I'll continue digging.

**Comment by martinpitt** [comment]
In any case, using packages built from upstream trunk works fine, so I'll just track down the patches for backporting. Closing this issue as trunk is fixed.
