### ISSUE TITLE
Systemd fails to unmount encrypted FS cleanly

### ISSUE THREAD

**Issue by lockie** [systemd/systemd#25538]
### systemd version the issue has been seen with

251.8

### Used distribution

Manjaro 21.3.0

### Linux kernel version used

5.15.78-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

The root filesystem umounted cleanly.

### Unexpected behaviour you saw

Every boot the root filesystem is being checked with fsck due to not being unmounted cleanly. Examining the log shows that systemd-cryptsetup fails to unmount fs, see below.
Closely related to #8472, which is not solved yet closed.

### Steps to reproduce the problem

Install Manjaro, select whole disk encryption while installing. Boot it.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
ноя 26 14:04:00 casper systemd[1]: dev-disk-by\x2did-dm\x2dname\x2dluks\x2d854a4224\x2d667b\x2d4ec9\x2d926a\x2d689cb9e65fcb.swap: Deactivated successfully.
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/disk/by-id/dm-name-luks-854a4224-667b-4ec9-926a-689cb9e65fcb.
ноя 26 14:04:00 casper systemd[1]: dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS1\x2d854a4224667b4ec9926a689cb9e65fcb\x2dluks\x2d854a4224\x2d667b\x2d4ec9\x2d>
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-854a4224667b4ec9926a689cb9e65fcb-luks-854a4224-667b-4ec9-926a-689cb9e>
ноя 26 14:04:00 casper systemd[1]: dev-disk-by\x2dlabel-swap.swap: Deactivated successfully.
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/disk/by-label/swap.
ноя 26 14:04:00 casper systemd[1]: dev-disk-by\x2duuid-b978d5c3\x2d5cf2\x2d46a2\x2d91bd\x2d3860b9e5be21.swap: Deactivated successfully.
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/disk/by-uuid/b978d5c3-5cf2-46a2-91bd-3860b9e5be21.
ноя 26 14:04:00 casper systemd[1]: dev-dm\x2d1.swap: Deactivated successfully.
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/dm-1.
ноя 26 14:04:00 casper systemd[1]: dev-mapper-luks\x2d854a4224\x2d667b\x2d4ec9\x2d926a\x2d689cb9e65fcb.swap: Deactivated successfully.
ноя 26 14:04:00 casper systemd[1]: Deactivated swap /dev/mapper/luks-854a4224-667b-4ec9-926a-689cb9e65fcb.
ноя 26 14:04:00 casper systemd[1]: Stopped target Block Device Preparation for /dev/mapper/luks-854a4224-667b-4ec9-926a-689cb9e65fcb.
ноя 26 14:04:00 casper systemd[1]: Stopping Cryptography Setup for luks-854a4224-667b-4ec9-926a-689cb9e65fcb...
ноя 26 14:04:00 casper systemd-cryptsetup[1877208]: Device luks-d7db5199-7e84-41c1-b750-4814d3e36fe0 is still in use.
ноя 26 14:04:00 casper systemd-cryptsetup[1877208]: Failed to deactivate: Device or resource busy
ноя 26 14:04:00 casper systemd-cryptsetup[1877209]: device-mapper: remove ioctl on luks-854a4224-667b-4ec9-926a-689cb9e65fcb  failed: Device or resource busy
ноя 26 14:04:00 casper systemd[1]: systemd-cryptsetup@luks\x2dd7db5199\x2d7e84\x2d41c1\x2db750\x2d4814d3e36fe0.service: Control process exited, code=exited, >
ноя 26 14:04:00 casper systemd[1]: systemd-cryptsetup@luks\x2dd7db5199\x2d7e84\x2d41c1\x2db750\x2d4814d3e36fe0.service: Failed with result 'exit-code'.
```

**Comment by poettering** [comment]
This is almost certainly an issue with your distro. They appear to miss "x-initrd.attach" on the crypttab line for your root LUKS volume. This mean system during regular system shutdown will try to disassemble the volume, which will of course fail given it is your root fs on it.

If you have a root fs on an encrypted volume then it's the job of the initrd (which will executed again during shutdown) to detach the rootfs and backing volume. It's the only place this can be done, as we need to transition away from the rootfs before it can be unmounted/detached properly.

Anyway, my educated guess is that your distro doesn't use Dracut or so, and hence maybe lacking the right hooks up there? Either way, please contact your distro for help. THis is almost cetrainly an issue between your distro and initrd, not with systemd. (SHould the distro folks determine this is an upstream systemd issue after all they'll propagate back to us, but I am pretty sure that's not going to happen).

Anyway, closing. Please contact your distro first.
