### ISSUE TITLE
/dev/disk/by-partuuid should have a variant which includes the disk

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#25540]
### Component

systemd-udevd

### Is your feature request related to a problem? Please describe

When we have multiple disks, each one might have e.g. an ESP partition, but /dev/disk/by-partuuid can only link to one. We should have a variant which includes the disk UUID in the partition symlink name.

### Describe the solution you'd like

Maybe `/dev/disk/by-partuuid/<part-uuid>-disk<disk-uuid>` ?

I guess the same would apply to `/dev/disk/by-label`. Labels may repeat between disks.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by cmurf** [comment]
`/dev/disk/by-partuuid` is based on unique partition GUID, not partition type GUID. So it is supposed to be globally unique.

If the use case is to ensure all bootloader pieces are updated on all available ESPs, I think it'd be something like:

- find all non-removable drives (exclude removables)
- find ESP partition type GUID on each drive, and store its /dev/disk/by-partuuid
- mount each stored /dev/disk/by-partuuid and update bootloader bits, in sequence

**Comment by cmurf** [comment]
There could be more than one ESP on a drive. It's not forbidden by the UEFI spec. We only need to update one of them.

And all the ESPs updated need to have proper UEFI NVRAM boot entries, otherwise the fallback we're trying to compel isn't going to work out.

a. Read NVRAM for the list of ESPs we should update, i.e. trust NVRAM
b. Always update NVRAM based on the list of ESPs we find, minus duplicates on a drive, i.e. trust the drives present

Probably b.

**Comment by poettering** [comment]
> When we have multiple disks, each one might have e.g. an ESP partition, but /dev/disk/by-partuuid can only link to one. We should have a variant which includes the disk UUID in the partition symlink name.

Hmm? there are two UUIDs per GPT partition: the one identifying the type, and the one identifying hte partition itself. the "by-partuuid" symlinks use the latter, not the former. This means if you have n disks in your system, then they their ESPs will have distinct symlinks, except of course, if they all use the exact same imag for the partition uuid too. But in that case the disk uuid is going to be the same too....

**Comment by keszybz** [comment]
Yeah, sorry, I mixed the partuiud and parttypeuuid.

> And all the ESPs updated need to have proper UEFI NVRAM boot entries, otherwise the fallback we're trying to compel isn't going to work.

OK, so the conditions are too complicated to try to squish all this information into a symlink. A program that want to DTRT will need to to look at efivars anyway. Let's close this.

**Comment by poettering** [comment]
@keszybz so there is a TODO list item somewhere, to add the logic from image-dissect.c also as udev symlinks. i.e. depending on what we are booted from we would create /dev/disk/by-parttype/<home|srv|var|tmp> and so on automatically, similar to how systemd-gpt-generator does it.
