### ISSUE TITLE
systemctl daemon-reload takes a long time on archlinx with systemd 252.2-1

### ISSUE THREAD

**Issue by patofan** [systemd/systemd#25543]
### systemd version the issue has been seen with

252

### Used distribution

Archlinux 

### Linux kernel version used

 5.15.80-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

[root@tissvr101 ~]# time  systemctl daemon-reload
real    0m0.445s
user    0m0.007s
sys     0m0.007s

### Unexpected behaviour you saw

[root@arch001 ~]# time systemctl daemon-reload
real    1m0.267s
user    0m0.000s
sys     0m0.009s

 It need a long time to execute "systemctl daemon-reload" .

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[root@arch001 ~]# SYSTEMD_LOG_LEVEL=debug
[root@arch001 ~]# systemctl daemon-reload
[root@arch001 ~]# time systemctl daemon-reload

real    1m0.422s
user    0m0.000s
sys     0m0.009s
```

**Comment by patofan** [comment]
I use https://gitlab.archlinux.org/archlinux/arch-boxes/-/jobs/106077/artifacts/file/output/Arch-Linux-x86_64-cloudimg-20221128.106077.qcow2 cloud image , and install on oracle OCI.  
After pacman -Syu upgrade the full system , then " systemctl daemon-reload" is very slow.

**Comment by imrejonk** [comment]
I'm seeing the same behavior, but using the latest Arch Linux cloud image (20221201.106936) on OpenStack with Linux 6.0.10-arch2-1. I further found out that disabling and enabling units using systemctl also takes a minute, but restarting services is quick.

The issue is however not present on my desktop, which runs Linux 5.15.80-1-lts (same version as you). Both systems run systemd 252.2-2 on x86_64.

**Comment by devvick** [comment]
I'm observing the same thing on EC2 Arch Linux instances, and not on my Arch Linux desktop.
The issue seems present every time there is a daemon-reload. I cannot even ssh to the host while this hangup is happening. Here is what journal outputs during the hang and just after, when it stopped and my ssh client could connect:
```
# time systemctl daemon-reload
systemctl daemon-reload  0.01s user 0.00s system 0% cpu 1:00.56 total
```
```
Dec 03 23:39:38 brick systemd[1]: Reloading.
Dec 03 23:40:11 brick dbus-daemon[362]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.73' (uid=0 pid=285080 comm="sshd:
Dec 03 23:40:36 brick dbus-daemon[362]: [system] Failed to activate service 'org.freedesktop.home1': timed out (service_start_timeout=25000ms)
Dec 03 23:40:36 brick sshd[285080]: pam_systemd_home(sshd:account): Failed to query user record: Connection timed out
Dec 03 23:40:36 brick sshd[285080]: Accepted publickey for (...)
```
In contrast, here's what it looks like on my desktop:
```
# time systemctl daemon-reload
systemctl daemon-reload  0,00s user 0,01s system 2% cpu 0,401 total
```

**Comment by imrejonk** [comment]
It looks like this regression was introduced in systemd 252. I don't observe this behavior when I downgrade my `systemd`, `systemd-libs` and `systemd-sysvcompat` packages to 251.7-4.

I'm wondering what in the Arch Linux cloud image triggers this. Could it be related to cloud-init or Netplan? Is there something special in the way devices are set up or something, given that this image was made for VM environments?

**Comment by devvick** [comment]
This is 99% *not* the image fault (as in: bad packaging or unofficial images) - I'm observing the same behavior on an Arch virtual machine in Proxmox (utilizing KVM), installed from an official iso. No cloud-init or any other special cloud facilities used there.

Hence, the problem appears to be present in any systemd 252 running in VM (or at least just in systemd 252 in Arch - haven't checked other distros).

**Comment by mrc0mmand** [comment]
Interesting, I tried to reproduced this locally in a VM (with KVM) with both the `archlinux/archlinux` Vagrant box from https://github.com/systemd/systemd/issues/25543#issuecomment-1328631649 and with a couple of other Arch VMs I have scattered around, and even with the latest Arch packages I failed to reproduce this.

Could someone who can reproduce this gather debug logs of the full reload? E.g.:

```
# systemctl log-level debug
# journalctl --cursor-file /tmp/journal.cursor -n 0 -q
# systemctl daemon-reload
# journalctl --cursor-file /tmp/journal.cursor -o short-monotonic --no-hostname
```

**Comment by imrejonk** [comment]
> Could someone who can reproduce this gather debug logs of the full reload?

Certainly: https://gist.github.com/imrejonk/00516e406ad1720012dd76ccc1c971fb

**Comment by imrejonk** [comment]
Looks like something related to Netplan took 20 seconds:
```
[  459.782010] systemd[964]: /usr/lib/systemd/system-generators/systemd-bless-boot-generator succeeded.
[  519.957145] systemd[964]: /usr/lib/systemd/system-generators/netplan succeeded.
```

**Comment by devvick** [comment]
Mine from EC2 machine:
https://gist.github.com/devvick/a7c2419ffb33551d0f2bf1ec93408cb8

**Comment by imrejonk** [comment]
Cloud-init applies this Netplan configuration on my OpenStack instance:
```
[arch@testvm2 ~]$ cat /etc/netplan/50-cloud-init.yaml 
# generated by cloud-init
network:
    version: 2
    ethernets:
        eth0:
            accept-ra: false
            addresses:
            - 2001:41d0:304:300::24f5/56
            dhcp4: true
            match:
                macaddress: fa:16:3e:d1:a2:c5
            mtu: 1500
            nameservers:
                addresses:
                - 213.186.33.99
                search: []
            routes:
            -   to: ::/0
                via: 2001:41d0:304:300::1
            set-name: eth0
```
Netplan, in turn, applies this systemd-networkd configuration:
```
[arch@testvm2 ~]$ cat /run/systemd/network/10-netplan-eth0.link 
[Match]
MACAddress=fa:16:3e:d1:a2:c5

[Link]
Name=eth0
WakeOnLan=off
MTUBytes=1500
[arch@testvm2 ~]$ cat /run/systemd/network/10-netplan-eth0.network 
[Match]
MACAddress=fa:16:3e:d1:a2:c5
Name=eth0

[Link]
MTUBytes=1500

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6
Address=2001:41d0:304:300::24f5/56
IPv6AcceptRA=no
DNS=213.186.33.99

[Route]
Destination=::/0
Gateway=2001:41d0:304:300::1

[DHCP]
RouteMetric=100
UseMTU=true
```

**Comment by mrc0mmand** [comment]
Also, strac'ing `systemd-udevd` at the same time shows a "stuck" `read()` for ~45 seconds:

```
     0.000017 newfstatat(AT_FDCWD</>, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=359, ...}, 0) = 0
     0.000020 openat(AT_FDCWD</>, "/etc/group", O_RDONLY|O_CLOEXEC) = 16</etc/group>
     0.000021 newfstatat(16</etc/group>, "", {st_mode=S_IFREG|0644, st_size=694, ...}, AT_EMPTY_PATH) = 0
     0.000017 lseek(16</etc/group>, 0, SEEK_SET) = 0
     0.000014 read(16</etc/group>, "root:x:0:root\nsys:x:3:bin\nmem:x:8:\nftp:x:11:\nmail:x:12:\nlog:x:19:\nsmmsp:x:25:\nproc:x:26:\ngames:x:50:\nlock:x:54:\nnetwork:x:90:\nfloppy:x:94:\nscanner:x:96:\npower:x:98:\nnobody:x:65534:\nadm:x:999:daemon\nwheel:x:998:\nutmp:x:997:\naudio:x:996:\ndisk:x:995:\ninput:x:994:\nkmem:x:993:\nkvm:x:992:\nlp:x:991:\noptical:x:990:\nrender:x:989:\nsgx:x:988:\nstorage:x:987:\ntty:x:5:\nuucp:x:986:\nvideo:x:985:\nusers:x:984:\nsystemd-journal:x:983:\nrfkill:x:982:\nbin:x:1:daemon\ndaemon:x:2:bin\nhttp:x:33:\ndbus:x:81:\nsystemd-coredum"..., 4096) = 694
     0.000019 close(16</etc/group>)     = 0
     0.000016 rt_sigprocmask(SIG_BLOCK, [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], [HUP INT TERM CHLD], 8) = 0
     0.000025 openat(AT_FDCWD</>, "/run/systemd/userdb/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 16</run/systemd/userdb>
     0.000023 newfstatat(16</run/systemd/userdb>, "", {st_mode=S_IFDIR|0755, st_size=60, ...}, AT_EMPTY_PATH) = 0
     0.000017 getdents64(16</run/systemd/userdb>, 0x5630b80fcee0 /* 3 entries */, 32768) = 96
     0.000019 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 17<socket:[23680]>
     0.000024 connect(17<socket:[23680]>, {sa_family=AF_UNIX, sun_path="/run/systemd/userdb/io.systemd.DynamicUser"}, 45) = 0
     0.000022 epoll_create1(EPOLL_CLOEXEC) = 18<anon_inode:[eventpoll]>
     0.000030 timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC|TFD_NONBLOCK) = 19<anon_inode:[timerfd]>
     0.000027 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_ADD, 19<anon_inode:[timerfd]>, {events=EPOLLIN, data={u32=3088203584, u64=94767246622528}}) = 0
     0.000023 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_ADD, 17<socket:[23680]>, {events=0, data={u32=3087476784, u64=94767245895728}}) = 0
     0.000034 getdents64(16</run/systemd/userdb>, 0x5630b80fcee0 /* 0 entries */, 32768) = 0
     0.000016 close(16</run/systemd/userdb>) = 0
     0.000014 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_MOD, 17<socket:[23680]>, {events=EPOLLIN|EPOLLOUT, data={u32=3087476784, u64=94767245895728}}) = 0
     0.000018 timerfd_settime(19<anon_inode:[timerfd]>, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=2368, tv_nsec=59425000}}, NULL) = 0
     0.000017 epoll_wait(18<anon_inode:[eventpoll]>, [{events=EPOLLOUT, data={u32=3087476784, u64=94767245895728}}], 8, 0) = 1
     0.000018 sendto(17<socket:[23680]>, "{\"method\":\"io.systemd.UserDatabase.GetGroupRecord\",\"parameters\":{\"groupName\":\"tty\",\"service\":\"io.systemd.DynamicUser\"}}\0", 120, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 120
     0.000022 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_MOD, 17<socket:[23680]>, {events=EPOLLIN, data={u32=3087476784, u64=94767245895728}}) = 0
     0.000017 epoll_wait(18<anon_inode:[eventpoll]>, [], 8, 0) = 0
     0.000014 recvfrom(17<socket:[23680]>, 0x5630b8146c90, 131080, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
     0.000022 epoll_wait(18<anon_inode:[eventpoll]>, [{events=EPOLLIN, data={u32=3088203584, u64=94767246622528}}], 8, -1) = 1
    45.041927 read(19<anon_inode:[timerfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
     0.000053 recvfrom(17<socket:[23680]>, 0x5630b8146c90, 131080, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
     0.000035 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_MOD, 17<socket:[23680]>, {events=0, data={u32=3087476784, u64=94767245895728}}) = 0
     0.000029 epoll_wait(18<anon_inode:[eventpoll]>, [], 8, 0) = 0
     0.000023 epoll_ctl(18<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 17<socket:[23680]>, NULL) = 0
     0.000027 close(17<socket:[23680]>) = 0
     0.000034 openat(AT_FDCWD</>, "/", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 16</>
     0.000043 openat(16</>, "etc", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17</etc>
     0.000030 newfstatat(17</etc>, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
     0.000032 close(16</>)              = 0

```

**Comment by yuwata** [comment]
I guess, the following chain causes the deadlock.
1. reloading udev rules
2. get_user_creds()/get_group_creds()
3. nss-systemd
4. groupdb_by_name() or friends
5. userdbd is not started, as PID1 is not ready yet.

**Comment by yuwata** [comment]
BTW, calling `udevadm control --reload` in generator is soooo bad idea. The generator should be used for generating units for PID1, e.g. .service, .mount, .slice or so, but not for .link, .network, .netdev.

We have systemd-network-generator.service, it generates network units before starting networkd and udevd.
Netplan should also follow in a similar way.

**Comment by yuwata** [comment]
@imrejonk 
This is off-topic, but from https://github.com/systemd/systemd/issues/25543#issuecomment-1338227196,
```
[arch@testvm2 ~]$ cat /run/systemd/network/10-netplan-eth0.link 
[Match]
MACAddress=fa:16:3e:d1:a2:c5

[Link]
Name=eth0         <--- !!
WakeOnLan=off
MTUBytes=1500
```
names such as `ethX` or `wlanX` should not be set in `Name=`. That can easily trigger conflict. I recommend to update the netplan config.

**Comment by imrejonk** [comment]
Thanks for looking into this @yuwata. Let me try to recap the issue before I report it to Netplan, just to see if I got everything:

During a systemd daemon-reload, the Netplan generator in `/usr/lib/systemd/system-generators/netplan` tries to reload the udev rules and databases with `udevadm control --reload` ([here](https://github.com/canonical/netplan/blob/bf8036d43837bc071d1d3f716f67dc24ef5a5b23/src/generate.c#L54)), which causes a deadlock, because reloading udev rules and databases requires a functioning systemd-userdbd.service, which is not the case during a systemd daemon-reload. The systemd developers will not consider making changes to any systemd component in order to prevent this deadlock, and instead suggest that the Netplan developers generate their systemd link/network/netdev units using a generator service like systemd-network-generator.service.

Is that about right?

\<offtopic\>
Regarding the `eth0` interface name in my Netplan configuration, I am well aware of the benefits of [predictable interface naming](https://systemd.io/PREDICTABLE_INTERFACE_NAMES/). That Netplan configuration file was put there by cloud-init. The Arch cloud image has `net.ifnames=0` in GRUB_CMDLINE_LINUX. My guess is that the image builders did that because the big cloud providers expect the first interface to always be named `eth0`. Take Azure for example:

>"'eth0' is the default NIC card requirement per the Azure Linux network configurations settings"

Source: https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-connect-debian-linux

It is also a requirement for Enhanced Networking on AWS: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-linux
\</offtopic\>

**Comment by yuwata** [comment]
> Thanks for looking into this @yuwata. Let me try to recap the issue before I report it to Netplan, just to see if I got everything:
> 
> During a systemd daemon-reload, the Netplan generator in `/usr/lib/systemd/system-generators/netplan` tries to reload the udev rules and databases with `udevadm control --reload` ([here](https://github.com/canonical/netplan/blob/bf8036d43837bc071d1d3f716f67dc24ef5a5b23/src/generate.c#L54)), which causes a deadlock, because reloading udev rules and databases requires a functioning systemd-userdbd.service, which is not the case during a systemd daemon-reload. The systemd developers will not consider making changes to any systemd component in order to prevent this deadlock, and instead suggest that the Netplan developers generate their systemd link/network/netdev units using a generator service like systemd-network-generator.service.
> 
> Is that about right?

Right.

**Comment by imrejonk** [comment]
Perfect. I've had some issues with the Launchpad login system, but now that a Launchpad administrator has resolved the issue I was able to create this bug report: https://bugs.launchpad.net/netplan/+bug/1999178

**Comment by imrejonk** [comment]
Courtesy ping for @patofan and @devvick
This issue has been [addressed](https://github.com/canonical/netplan/commit/05fcc806ad2a4ae9af493f863596a606fbf7da25) in Netplan version 1.1, which is available in the Arch Linux 'extra' package repository since Aug. 23, 2024, 6:53 a.m. UTC.

Note that the latest official Arch Linux cloud image does not yet include this updated package. I expect an updated image to arrive on September 1st: https://geo.mirror.pkgbuild.com/images/

**Comment by devvick** [comment]
And, like a boomerang the deadlock returned... Just noticed it on my Proxmox Archlinux guest:
Enabled netplan generator:
```
# time systemctl daemon-reload
systemctl daemon-reload  0.00s user 0.01s system 0% cpu 1:30.22 total
```
Removing the generator immediately fixes it:
```
# rm /usr/lib/systemd/system-generators/netplan
# time systemctl daemon-reload
systemctl daemon-reload  0.01s user 0.00s system 2% cpu 0.259 total
```
Current netplan package:
```
% pacman -Qi netplan                      
Name            : netplan
Version         : 1.1-2
Description     : Network configuration abstraction renderer
Architecture    : x86_64
URL             : https://github.com/canonical/netplan
Licenses        : GPL-3.0-only
Groups          : None
Provides        : libnetplan.so=1-64
Depends On      : dbus-python  gcc-libs  glibc  glib2  libyaml  python  python-cffi  python-yaml  python-netifaces  python-rich  iproute2  systemd
                  systemd-libs  util-linux-libs
Optional Deps   : None
Required By     : None
Optional For    : cloud-init
Conflicts With  : None
Replaces        : None
Installed Size  : 1091.00 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Thu 21 Nov 2024 05:42:22 PM UTC
Install Date    : Mon 20 Jan 2025 11:58:07 PM UTC
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```
This time I found a different error:
```
[  822.130819] systemd[1]: Reload requested from client PID 1379 ('systemctl') (unit session-1.scope)...
[  822.130827] systemd[1]: Reloading...

[  822.187643] systemd[1]: Serializing system-environment-generators to memfd.
[  822.187864] systemd[1]: Successfully forked off '(sd-exec-strv)' as PID 1396.
[  822.188039] (sd-exec-s[1396]: Serializing 10-arch to memfd.
[  822.188043] (sd-exec-s[1396]: About to execute /usr/lib/systemd/system-environment-generators/10-arch
[  822.188243] (sd-exec-s[1396]: Successfully forked off '(exec-inner)' as PID 1397.
[  822.189547] (sd-exec-s[1396]: /usr/lib/systemd/system-environment-generators/10-arch succeeded.
[  822.189810] systemd[1]: (sd-exec-strv) succeeded.
[  822.190037] systemd[1]: Successfully forked off '(sd-gens)' as PID 1398.
[  822.191199] (sd-gens)[1398]: Successfully forked off '(sd-exec-strv)' as PID 1399.
[  822.191355] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/cloud-init-generator (null)
[  822.191546] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1400.
[  822.191561] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/netplan (null)
[  822.191750] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1401.
[  822.191765] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/nfs-server-generator (null)
[  822.191954] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1402.
[  822.191974] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/rpc-pipefs-generator (null)
[  822.192157] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1403.
[  822.192176] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-bless-boot-generator (null)
[  822.192363] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1404.
[  822.192381] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-cryptsetup-generator (null)
[  822.192611] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1405.
[  822.192630] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-debug-generator (null)
[  822.192833] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1406.
[  822.192863] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-fstab-generator (null)
[  822.193052] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1407.
[  822.193072] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-getty-generator (null)
[  822.193252] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1408.
[  822.200035] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-gpt-auto-generator (null)
[  822.200271] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1410.
[  822.200286] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-hibernate-resume-generator (null)
[  822.200507] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1411.
[  822.200526] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-import-generator (null)
[  822.200687] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1412.
[  822.200706] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-integritysetup-generator (null)
[  822.200883] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1413.
[  822.200916] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-run-generator (null)
[  822.201109] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1414.
[  822.201127] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-ssh-generator (null)
[  822.201319] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1415.
[  822.201338] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-system-update-generator (null)
[  822.206882] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1416.
[  822.206900] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-tpm2-generator (null)
[  822.207059] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1417.
[  822.207073] (sd-exec-[1399]: About to execute /usr/lib/systemd/system-generators/systemd-veritysetup-generator (null)
[  822.207206] (sd-exec-[1399]: Successfully forked off '(exec-inner)' as PID 1418.
[  822.213805] (sd-exec-[1399]: /usr/lib/systemd/system-generators/systemd-import-generator succeeded.
[  822.213822] (sd-exec-[1399]: /usr/lib/systemd/system-generators/systemd-bless-boot-generator succeeded.
[  822.213831] (sd-exec-[1399]: /usr/lib/systemd/system-generators/systemd-ssh-generator succeeded.
[  822.218690] (sd-exec-[1399]: /usr/lib/systemd/system-generators/cloud-init-generator succeeded.
[  822.218711] (sd-exec-[1399]: /usr/lib/systemd/system-generators/systemd-getty-generator succeeded.


[  912.191785] (sd-gens)[1398]: (sd-exec-strv) terminated by signal ALRM.
[  912.192047] systemd[1]: (sd-gens) failed with exit status 1.
[  912.192055] systemd[1]: Failed to fork off sandboxing environment for executing generators: Protocol error
```
@imrejonk  Would you be so kind as to reopen (or create new) issue on netplan bugtracker? Let me know if you need more info.

**Comment by slyon** [comment]
@devvick I wonder if this would help with this? https://github.com/canonical/netplan/pull/529

There are some Ubuntu specific blockers of getting this merged upstream, but it might work just fine for Arch Linux?

**Comment by slyon** [comment]
@devvick FYI: With the latest release of [Netplan v1.2](https://github.com/canonical/netplan/releases/tag/1.2) this should be much improved, as that contains a full refactoring of the Netplan generator, which is now split in two binaries: `usr/libexec/netplan/generate` (the actuall generator, which was very much reduced in scope, to do generator things only) and `usr/libexec/netplan/configure` executed later via `netplan-configure.service` (doing all the other, unrelated stuff, such as writing config files).

see also: https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2133724
