### ISSUE TITLE
Network device naming deviates from naming scheme ...

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#25545]
### systemd version the issue has been seen with

systemd 252 (252.2-1-arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.0.9-hardened1-1-hardened

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

I was expecting for virtual functions (SR-IOV) of an interface (enp36s0f0) to be named with an letter v followed by an incrementing number e.g. enp36s0f0v0, enp36s0f0v1, enp36s0f0v2 and so on.

### Unexpected behaviour you saw

It seems no matter when I spawn the virtual functions (as a service before multi-user.target) or later during my own custom boot target, nor how I spawn them, via configuration file in /etc/modprobe.d or simply be echoing into `/sys/class/net/enp36s0f0/device/sriov_numvfs`, the naming of the virtual functions is all over the place. The physical NICs still receive enp36s0f0 and enp36s0f1 as their names but the virtual functions are now named enp37s17v4, enp37s18f4, enp38s16f1v0. There does not seem to be a logic involved in the number of the interface, slot or function. Sometimes the additional letter v for the virtual interface is missing entirely.

### Steps to reproduce the problem

I am not sure how to reproduce the problem since it did work as intended in the past. One of the recent updates must have introduced the unexpected behaviour. I am out of my field of expertise to debug this however.

### Additional program output to the terminal or log subsystem illustrating the issue

If additional output of an command or program is required, please let me know. I'll do my best to provide what is required.

**Comment by yuwata** [comment]
Could you provide the results of `udevadm info --attribute-walk /sys/class/net/INTERFACE_NAME` for each physical and virtual interface?

**Comment by presslab-us** [comment]
I just upgraded to 252.2-1 (debian) and I see the same problem with VFs.

Also I changed the network names in my systemd/network files and then the interfaces would come up but DHCP and RA aren't working.  I had to use `dhclient` and set `accept_ra` to get the IPs assigned.

Here's the udevadm attributes for all my interfaces:
https://pastebin.com/4KGaTBau

**Comment by little-helper-001** [comment]
@yuwata Please excuse my absence. I was unable to provide the output from these commands since I have banned the VF from being loaded by the host operating system (via the vfio-pci.ids kernel parameter) and have created a [SR-IOV Virtual Network Adapter Pool](https://www.intel.com/content/www/us/en/developer/articles/technical/configure-sr-iov-network-virtual-functions-in-linux-kvm.html) so that I am able to dynamically assign them to virtual machines and provide them with a spoofed MAC address so that they get the correct lease and IP address from the DHCP server.

I have several other X550 cards as well, but need to setup a computer to replicate the problem. The machine the problem occured to initially can't be shutdown at the moment.

**Comment by sotiris-bos** [comment]
Same here on Arch 5.15.82-1-lts. 

Do you need my udevadm attributes? I have 60 SR-IOV interfaces so it will take a while.

**Comment by keszybz** [comment]
> Here's the udevadm attributes for all my interfaces: https://pastebin.com/4KGaTBau

This is 404. Please don't use pastebins which expire for stuff like this.

**Comment by presslab-us** [comment]
> This is 404. Please don't use pastebins which expire for stuff like this.

I didn't want my MAC addresses out there for eternity.  I wasn't expecting it would take that long to download the information.

**Comment by yuwata** [comment]
BTW, I have not deeply checked yet, the current logic sounds quite racy for me. That is, when we try to rename a virtual function of an interface, then it depends on sysfs attributes of the 'main' interface, but it may be under renaming, and we may get partial or wrong information about the main interface.

Anyway, I will take it more deeply later, and check if the above guess is correct or not.

**Comment by yuwata** [comment]
Arghhh, sorry, the issue should not be so complicated. That should be a simple bug caused by 78463c6c4fdcb703bc0dc694c3ea77df3c5624e0. Fix is waiting in #26288.
