### ISSUE TITLE
Concurrently execute systemctl daemon rexec and systemd xxx abc.service, some error logs appear.

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#25542]
### systemd version the issue has been seen with

251

### Used distribution

fedora

### Unexpected behaviour you saw

Concurrently execute systemctl daemon reexec and systemctl xxx abc Service, some error logs appear.
![image](https://user-images.githubusercontent.com/17870505/204181362-fb4c0173-0403-49c5-b751-4a8adb022375.png)

The reason for these logs may be that the socket (/run/systemd/private) is closed.
It is found in the code that/run/systemd/private has set SOCK_ CLOEXEC, which may cause daemon-reexec to close the socket, and then other operations of systemctl fail.
![image](https://user-images.githubusercontent.com/17870505/204180747-4ee2e658-c5b1-4ffa-91ed-8c9ee2410b6f.png)
### Steps to reproduce the problem
step: sh test_reexec.sh
test_reexec.sh:
```#!/bin/bash

SERVICE_DIR_USR='/usr/lib/systemd/system'
cat << EOF > test_reexec.service
[Unit]
Description="sleep service ${RANDOM}"
[Service]
ExecStart=sleep 1000
StartLimitBurst=0
StartLimitIntervalSec=0
[Install]
WantedBy=multi-user.target
EOF

for ((i=0; i<10; ++i)); do
    cp -arf test_reexec.service "${SERVICE_DIR_USR}"/test_reexec_"${i}".service
done
systemctl daemon-reload

for ((i=0; i<10; ++i)); do
    sh -x systemctl.sh test_reexec_"$i" &> systemctl.log"$i" &
    systemctl_pid="${systemctl_pid} $!"
done

for ((i=0; i<100; ++i)); do
    systemctl daemon-reexec
done

kill -9 ${systemctl_pid}
sleep 5

grep -iEnr 'fail|err' systemctl.log*
```
systemctl.sh
```#!/bin/bash

service="$1"

while ((1)); do
    systemctl start "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl status "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    ls /etc/systemd/system/multi-user.target.wants/"${service}".service && fail=1
    systemctl enable "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl is-enabled "${service}" || fail=1
    ls /etc/systemd/system/multi-user.target.wants/"${service}".service || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl restart "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl disable "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl is-enabled "${service}" && fail=1
    ls /etc/systemd/system/multi-user.target.wants/"${service}".service || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl stop "${service}" || fail=1
    sleep "$((RANDOM%3+1))"
    systemctl status "${service}" && fail=1
    sleep "$((RANDOM%3+1))"
done
```

### Additional program output to the terminal or log subsystem illustrating the issue
Log related code
```
     src/shared/bus-wait-for-jobs.c:                        
     return log_error_errno(q, "Failed to wait for response: %m");   Connection reset by peer  
```
```  
src/systemctl/systemctl-is-enabled.c:                          
     return log_error_errno(r, "Failed to get unit file state for %s: %s", *name, bus_error_message(&error, r));
	 Transport endpoint is not connected
```
```
systemd-249/src/systemctl/systemctl-enable.c:224:                        return log_error_errno(r, "Failed to %s unit: %s", verb, bus_error_message(&error, r));	 
	 Failed to enable unit: Message recipient disconnected from message bus without replying
```

**Comment by yuwata** [comment]
Hmmm? Why do you think this is a bug? You re-execute PID1, then for me that's quite natural that the PID1 does not respond during the reexecution. I am not sure there is a way to 'fix' the issue...

**Comment by yangmingtai** [comment]
> Hmmm? Why do you think this is a bug? You re-execute PID1, then for me that's quite natural that the PID1 does not respond during the reexecution. I am not sure there is a way to 'fix' the issue...

thx

**Comment by dtardon** [comment]
> Hmmm? Why do you think this is a bug? You re-execute PID1, then for me that's quite natural that the PID1 does not respond during the reexecution. I am not sure there is a way to 'fix' the issue...

PID1 can keep fds for a service while it's restarting, so perhaps a similar mechanism could be used for PID1 itself. PID1 would fork a process as part of serialization and pass its fds to it, then request them back during deserialization. I have no idea how much work it would require and whether it's be worth the additional complexity, but I think it's doable.

**Comment by yuwata** [comment]
Theoretically, maybe yes. But to support that, at least we need to serialize sd-bus internal states... That sounds horrible for me.
