### ISSUE TITLE
systemd-detect-virt: support Charliecloud

### ISSUE THREAD

**Issue by reidpr** [systemd/systemd#25549]
### Component

systemd

### Is your feature request related to a problem? Please describe

`systemd-detect-virt` can detect a variety of virtualized or containerized environments. [Charliecloud](https://hpc.github.io/charliecloud/) is a well-known HPC container implementation but not apparently supported: it is not listed in the version 252 [man page](https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html#).

Note: I am the Charliecloud project lead.

### Describe the solution you'd like

Add Charliecloud support to `systemd-detect-virt`; a reasonable ID would be `charliecloud`.

Detection is simple; `ch-run(1)`, used to start a container, [sets the environment variable](https://hpc.github.io/charliecloud/ch-run.html#default-behavior) `CH_RUNNING`.

### Describe alternatives you've considered

One could also figure out some signature of a running Charliecloud container (e.g., which namespaces are in use), but since there is a documented method for detection, that seems best.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
why doesn't this container implementation set $container= like everyone else?

https://systemd.io/CONTAINER_INTERFACE/

"CH_RUNNING" is a bit generic, and we rather not add more individualized hacks to our list of things to check. So far docker was the one speciality that was too special to follow the logic everyone else implements.

Can you ping the people working on this new container thing, to implement the stuff listed in the container interface document? To the very least the $container thing?

(And if they care about being able to runs systemd inside their containers also the rest)

**Comment by poettering** [comment]
Closing, since they really should just implement the same logic as everyone else

**Comment by reidpr** [comment]
You get to run your project the way you want. But, regarding these:

> Can you ping the people working on this new container thing
> they really should just implement

I guess you missed this part of the initial bug report:

> Note: I am the Charliecloud project lead.

That is, third person is inappropriate and disrespectful.

As to the substantive question, that variable appears to be a systemd thing rather than any kind of standard, and plenty of “everyone else” gets their own checks. I'm disinclined to support “individualized hacks” for systemd.

**Comment by poettering** [comment]
at least nspawn, lxc, podman set $container=.

**Comment by poettering** [comment]
libvirt sets it too btw

**Comment by poettering** [comment]
If you are looking for more sw that checks for $container check this github search:

https://github.com/search?q=getenv%28%22container%22%29&type=code&p=2

Good luck convincing them all to check specifically for your own implementation instead...
