### ISSUE TITLE
Dhcp clientidentifier duid-only not working correctly

### ISSUE THREAD

**Issue by cobradevil** [systemd/systemd#25562]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

I have a dhcp server which expects a specific clientidentifier.
The following enhancement would apply for a correct way to specify a custom clientidentifier but that does not seem to work correctly: https://github.com/systemd/systemd/issues/7828.

It looks like it always prepends something before the DUIDRawData also when specifying the option : 
ClientIdentifier=duid-only

 

### Unexpected behaviour you saw

When i put in the dhclient.conf the following option:
`send dhcp-client-identifier 31:31:31:31;`
the output from dhcpdump is:
`OPTION:  61 (  4) Client-identifier         31:31:31:31`

When i set this in the networkconfig for my interface:
`[Match]`
`Name=enp6*`
`[Network]`
`DHCP=ipv4`
`[DHCPv4]`
`ClientIdentifier=duid-only`
`DUIDType=link-layer`
`DUIDRawData=31:31:31:31`

Then i get the following line in dhcpdump:

`OPTION:  61 (  7) Client-identifier         ff:00:00:00:00:00:03
`

So it seems that the option duid-only is not working or I have missed a configuration step.

### Steps to reproduce the problem

see above.

**Comment by yuwata** [comment]
Hm, indeed. `duid-only` mode is completely broken...

**Comment by cobradevil** [comment]
Could i use in the meantime the parameter `sendoption` to workaround this issue?
And if so would you have an example howto do that?
`SendOption="61:string:31\:31\:31\:31"` does not seem to work.

**Comment by yuwata** [comment]
Unfortunately, no way.

**Comment by yuwata** [comment]
If the DHCP server is under your control, then please adjust the client identifier to be accepted in the server side.

**Comment by cobradevil** [comment]
Unfortunately it is not under my control. So i have to use the `duid-only` option then.

**Comment by yuwata** [comment]
Currently, we only support `ClientIdentifier=mac` or `duid` (or broken `duid-only`). If `mac`, then the first octet is `01`. If `duid` (or `duid-only`), then the first octet is `ff`. We have not provided an option to specify an arbitrary client identifier.

**Comment by cobradevil** [comment]
ok, so even when `duid-only` is working then i still get the first octet as `ff`? Could that be configurable to be in the `DUIDRawData` also? So only use what is in the `DUIDRawData` ?

**Comment by yuwata** [comment]
> ok, so even when `duid-only` is working then i still get the first octet as `ff`?

Right.

Maybe, we should make `ClientIdentifier=` take a raw data, like `31:31:31:31` you want to specify.

**Comment by cobradevil** [comment]
That seems to match the configuation option in `dhclient.conf` or `dhcpcd,.conf`.

**Comment by arvidjaar** [comment]
> 
```[DHCPv4]
ClientIdentifier=duid-only
DUIDType=link-layer
DUIDRawData=31:31:31:31
```

> Then i get the following line in dhcpdump:

> `OPTION: 61 ( 7) Client-identifier ff:00:00:00:00:00:03`

How can we end with this value of option 61? According to systemd documentation for `DUIDRawData` (The DUID that is sent is composed of the DUID type specified by `DUIDType=` and the value configured here) the option value should be `ff:00:00:00:00:00:03:31:31:31:31` (`00:03` is `DUIDType`).

**Comment by eduvfalc** [comment]
Without the support for `duid-only`, how does one go about sending a custom client id to the DHCP server using `DUIDRawData`?
