### ISSUE TITLE
Left/Right arrows break VT login prompt, can edit the prompt message but login stops working

### ISSUE THREAD

**Issue by kparal** [systemd/systemd#25563]
### systemd version the issue has been seen with

systemd-251.8-586.fc37.x86_64

### Used distribution

Fedora 37

### Linux kernel version used

6.0.10-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

I expect to be able to edit only content after the login prompt:
```
hostname login: EDIT HERE
```
I expect Left/Right arrows to either work in that EDIT HERE section, or not work at all (use Backspace to go back a letter).

### Unexpected behaviour you saw

Problem 1: The whole prompt can be edited when using Left/Right arrows. So from this:
```
hostname login: EDIT HERE
```
I can easily change it to this:
```
you're not welcome: EDIT HERE
```

Problem 2: Once Left/Right arrow is used, the whole login prompt breaks, even if you *don't* edit the actual prompt before the colon. So even if you type:
```
hostname login: user1
```
and then use the Left arrow to go left a few letters and change it to
```
hostname login: uzer1
```
and hit Enter, the prompt just gets "stuck" and doesn't respond to any other input. If you wait long enough, it gets reset to the original state. That means if I hit Left/Right arrow by accident, my next login attempt will certainly fail and I'll have to wait and retry.

These problems only happen for the *first* login prompt on the screen. If you fail some login in a standard way and you see e.g. *Password incorrect* and the prompt repeats below, it is not affected by the bug. But if the screen refreshes and you see the prompt at the very top of the screen, it's susceptible to the bug again.

### Steps to reproduce the problem

1. Switch to a text VT
2. Use Left/Right arrows to move across the login prompt. You can overwrite any letter, use Backspace to delete it.
3. Hit Enter. The prompt gets stuck.
4. Wait for the prompt to reset.

See this video:
[login.webm](https://user-images.githubusercontent.com/755451/204578914-1615f849-c308-4eea-87c2-fa27819bad45.webm)

**Comment by dtardon** [comment]
Why do you think this has got anything to do with `systemd-logind`? The login prompt is handled by the `login` utility from util-linux.

**Comment by kparal** [comment]
Because that was simply my best guess. I reported this problem against util-linux here:
https://bugzilla.redhat.com/show_bug.cgi?id=2174714
