### ISSUE TITLE
systemd crash

### ISSUE THREAD

**Issue by TKSpyrop** [systemd/systemd#2558]
Hello,

Can you please help me with the investigation of the following coredump?

```
Core was generated by `/usr/lib/systemd/systemd --show-status=1 --log-target=journal-or-kmsg --log-lev'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5be630d757 in kill () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007f5be630d757 in kill () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000557fba23dd8c in crash (sig=11) at src/core/main.c:167
#2  <signal handler called>
#3  __pthread_create_2_1 (newthread=newthread@entry=0x7ffce3abe138, attr=attr@entry=0x7ffce3abe140, start_routine=start_routine@entry=0x557fba29b500 <close_thread>, arg=arg@entry=0x20) at pthread_create.c:698
#4  0x0000557fba29b5c3 in asynchronous_job (func=func@entry=0x557fba29b500 <close_thread>, arg=arg@entry=0x20) at src/basic/async.c:51
#5  0x0000557fba29b644 in asynchronous_close (fd=32) at src/basic/async.c:86
#6  0x0000557fba255564 in service_close_socket_fd (s=0x557fbbe68b00) at src/core/service.c:183
#7  0x0000557fba255893 in service_set_state (s=s@entry=0x557fbbe68b00, state=SERVICE_DEAD) at src/core/service.c:853
#8  0x0000557fba255cd2 in service_enter_dead (s=0x557fbbe68b00, f=<optimized out>, allow_restart=<optimized out>) at src/core/service.c:1329
#9  0x0000557fba259c88 in service_sigchld_event (u=0x557fbbe68b00, pid=<optimized out>, code=1, status=0) at src/core/service.c:2529
#10 0x0000557fba23f6c6 in manager_dispatch_sigchld (m=0x557fbbe0d690) at src/core/manager.c:1668
#11 0x0000557fba244813 in manager_dispatch_signal_fd (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x557fbbe0d690) at src/core/manager.c:1924
#12 0x0000557fba2d694b in source_dispatch (s=s@entry=0x557fbbe0dc10) at src/libsystemd/sd-event/sd-event.c:2116
#13 0x0000557fba2d7a1e in sd_event_dispatch (e=e@entry=0x557fbbe0d2f0) at src/libsystemd/sd-event/sd-event.c:2472
#14 0x0000557fba2d7bbd in sd_event_run (e=0x557fbbe0d2f0, timeout=15000000) at src/libsystemd/sd-event/sd-event.c:2500
#15 0x0000557fba245490 in manager_loop (m=0x557fbbe0d690) at src/core/manager.c:2043
#16 0x0000557fba23a0cd in main (argc=4, argv=0x7ffce3abe848) at src/core/main.c:1757
```

Thank you

**Comment by poettering** [comment]
Please read https://github.com/systemd/systemd/blob/master/CONTRIBUTING.md which is linked prominently from the issue submission form. We cannot help you if you don't tell us anything about your distro, systemd version, ...

**Comment by TKSpyrop** [comment]
You are right, i'm sorry. Systemd version is 225, while distro is custom build from source.
systemctl --version
systemd 225
+PAM +AUDIT -SELINUX -IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Comment by poettering** [comment]
any chance you can try to reproduce this with a newer systemd version? what glibc version?

**Comment by TKSpyrop** [comment]
Linux 4.1.13.x86_64
ldd /usr/lib/systemd/systemd
        linux-vdso.so.1 (0x00007ffc7176f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f747b8eb000)
        libpam.so.0 => /usr/lib64/libpam.so.0 (0x00007f747b6de000)
        libkmod.so.2 => /usr/lib64/libkmod.so.2 (0x00007f747b4cc000)
        libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007f747b286000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f747b081000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f747ae64000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f747aac6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f747baf3000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f747a8c2000)
        libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007f747a682000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f747a47e000)
        libattr.so.1 => /usr/lib64/libattr.so.1 (0x00007f747a27a000)

Unfortunately, it was one time occurence, couldn't reproduce.

**Comment by poettering** [comment]
OK, I am closing this now. If you manage to reproduce this with a current systemd version, please reopen. Note that we only track bugs in the two most recent systemd versions upstream.

**Comment by evverx** [comment]
@TKSpyrop, see #4905
