### ISSUE TITLE
Log the startup and shutdown output to a file like dmesg Xorg and syslog files already do

### ISSUE THREAD

**Issue by jonnygrant** [systemd/systemd#25592]
### Component

systemd

### Is your feature request related to a problem? Please describe

It would be great if systemd actually logged in /var/log like dmsg and syslog files are. Is that possible? Also Xorg logs its start and shutdown to a file.

This has some photos showing the output on screen. Would be great if this could go to a file so we could look later.
https://github.com/systemd/systemd/issues/25490

### Describe the solution you'd like

Logs like current logs I can see and review 
/var/log/systemd/

dmesg
dmesg.0
dmesg.1.gz
dmesg.2.gz
dmesg.3.gz
dmesg.4.gz

kern.log
kern.log.1
kern.log.2.gz
kern.log.3.gz
kern.log.4.gz

syslog
syslog.1
syslog.2.gz
syslog.3.gz
syslog.4.gz
syslog.6.gz
syslog.7.gz

**Comment by jonnygrant** [comment]
There are manual ways to achieve via these workarounds:
https://freedesktop.org/wiki/Software/systemd/Debugging/#diagnosingshutdownproblems

**Comment by poettering** [comment]
The journal already has all dmesg and syslog data. you can use "journalctl -k" to get just the dmesg data it collected, even. or without the "-k" to get everything.

to my knowledge Xorg also logs to syslog.

hence you should have everything you need already in the journal.

If you want this in classic text files, use a sylog implementation, they can read the data off journald.

**Comment by jonnygrant** [comment]
> The journal already has all dmesg and syslog data. you can use "journalctl -k" to get just the dmesg data it collected, even. or without the "-k" to get everything.
> 
> to my knowledge Xorg also logs to syslog.
> 
> hence you should have everything you need already in the journal.
> 
> If you want this in classic text files, use a sylog implementation, they can read the data off journald.

Hello @poettering 
Thank you for your reply. I ran that command it creates a 512MB log file, but none of the start up output from the screenshot.

I was hoping to see something like the screenshot text

[ OK ] Stopped target Sound Card
[ OK ] Stopped target Timer Units


![systemd](https://user-images.githubusercontent.com/29703560/206299534-e832c159-a48e-45d3-a797-6ae90925c2c3.jpg)
