### ISSUE TITLE
Apptainer/Singularity containerization frameworks detectable by systemd-detect-virt

### ISSUE THREAD

**Issue by thdesy** [systemd/systemd#25604]
### Component

systemd-machined

### Is your feature request related to a problem? Please describe

systemd-detect-virt / ConditionVirtualization can be used for detecting if running in a virtualized/cotainerized environment. 

Apptainer [1] and Singularity [2] are container solutions, which are established and heavily used in particle physics and HPC & HTC computing.  These are not yet detected by systemd-detect-virt.

Including them would be useful for a standardized approach to detect if a physics application runs in an Apptainer container.

[1]
https://apptainer.org/news/community-announcement-20211130
[2]
https://sylabs.io/singularity/

### Describe the solution you'd like

a Apptainer container application has a description file
```/.apptainer.d/labels.json```
or, respectively,
```/.singularity.d/labels.json```
which can be used for identifying if running in a containerized environment

Apptainer allows to flexibly constrain namespaces, so that a process' namespace can vary depending on its initiation

### Describe alternatives you've considered

currently detection is left to the actual user to improvise an own solution

tested on Fecora Core 36 with
```
6.0.7-200.fc36.x86_64

systemd-250.8-1.fc36.x86_64
systemd-container-250.8-1.fc36.x86_64
systemd-libs-250.8-1.fc36.i686
systemd-libs-250.8-1.fc36.x86_64
systemd-networkd-250.8-1.fc36.x86_64
systemd-oomd-defaults-250.8-1.fc36.noarch
systemd-pam-250.8-1.fc36.x86_64
systemd-resolved-250.8-1.fc36.x86_64
systemd-rpm-macros-250.8-1.fc36.noarch
systemd-udev-250.8-1.fc36.x86_64
```

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by bluca** [comment]
Please have these frameworks implement the container interface instead - at least the $container environment variable, ideally the rest too, and then detection will work out of the box everywhere: https://systemd.io/CONTAINER_INTERFACE/

**Comment by thdesy** [comment]
thanks - I will open a feature request for Apptainer
