### ISSUE TITLE
test-cgroup failed in docker

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#25626]
### systemd version the issue has been seen with
249, I think this problem also exists in other versions

### Used distribution
openEuler

### Linux kernel version used
5.15

### CPU architectures issue was seen on
x86_64

### Component
test-cgroup

### Expected behaviour you didn't see
we try compile systemd in docker, but test-cgroup test failed
In the VM test-cgroup, test ok,log:
![image](https://user-images.githubusercontent.com/17870505/205544307-1b55494a-a328-44a4-bf6e-0c28f186433b.png)
In the docker test-cgroup, test failed, log:
![image](https://user-images.githubusercontent.com/17870505/205545027-79757551-4252-4d86-ad12-f43b4bb56a04.png)

![image](https://user-images.githubusercontent.com/17870505/205545503-ee739d16-f32f-48ef-a9cb-cdf12d780b52.png)
I don't know whether it is related to the "shifted". Assemble the test_ B with "shift", but assert without

**Comment by poettering** [comment]
this smells as if docker is simply broken and /sys/fs/cgroup/ mount setup doesn't match what /proc/self/cgroup/ reports.

Please note we make certain requirements for container managers to implement:

https://systemd.io/CONTAINER_INTERFACE/

if yours doesn't implement that, you are on your own, basically.
