### ISSUE TITLE
systemd use of tpm2 is insecure

### ISSUE THREAD

**Issue by jejb** [systemd/systemd#25620]
The best security practice for TPM2's nowadays requires that it be proof against interposer snooping and thus must use HMAC proof instead of sending passwords down and must protect sensitive material by using session encryption/decryption.  The key sensitive TPM functions of systemd tpm2_seal() and tpm2_unseal() which do neither of these things meaning that both the password and disk decryption key could be captured in-flight by a snooper.

The fix is to use session hmac and encryption/decryption.  For the tpm2_unseal you can simply use the policy handle you already created for this by adding the correct parameters.  It may be possible to do the same in tpm2_seal, although I'm not sure because I've only ever used a non-policy session for this.  There is an additional complexity for parameter encryption/decryption in that you have to salt the session somehow to prevent a snooper deducing the encryption parameters, which is traditionally done using the parent key.

Given that some of the code seems to be unsealing and resealing, there is an additional security consideration: you need to make sure the TPM doesn't change under you.  You can easily do a trust on first use model, where you make sure the name of the parent stays the same.  Ideally you would generate the primary outside the unseal/reseal operation to make sure of this and use that for session salting as well.  However, if you want to keep the primary generation where it is you could save the name of the primary somewhere (like in the key json) and make sure it doesn't change.

**Comment by bluca** [comment]
Mmh session encryption is already used? And has been for the past couple releases? Introduced by https://github.com/systemd/systemd/pull/22630 and since https://github.com/systemd/systemd/pull/24524 it also uses the PIN as the bind key.

Regarding authenticating the TPM, there's already a long discussion on https://github.com/systemd/systemd/issues/22637 with the TSS folks

**Comment by tempusfugit991** [comment]
i think we need more than this.

wie should have defined filepath (uapi group style) for storing the known primary key of the currend (tofu) tpm.
after this we can/should always use a hmac session for talking to the tpm.
this would detect any change of the tpm + provides mitm protection.
exception: trial sessions of systemd-measure.
trial sessions can't be hmac sessions but are no problem and not bound to that specific tpm.

special case booting:
there is no access to the trusted primary key file in the initramfs.
solution:
add a hash of the tpm primary key to the luks header. (via a new field for the systemd-tpm2 token)
problem: the luks header is not signed.
it would be possible to change the hash + a tpm-genie device to fool  the user to enter the tpm-pin.
solution: we have a signing key infrastructure now for pcr signing.
just sign the the systemd-tpm2 token with the same key.
the signing-pubkey in the initramfs is protected via secureboot.

this should do the trick?!?

**Comment by jejb** [comment]
On Sun, 2022-12-04 at 09:04 -0800, Luca Boccassi wrote:
> Mmh session encryption is already used? And has been for the past
> couple releases? Introduced by
> https://github.com/systemd/systemd/pull/22630 and since
> https://github.com/systemd/systemd/pull/24524 it also uses the PIN as
> the bind key.

Sorry about that.  Apparently systemd switched from a master branch to
a main branch and I didn't notice so my pulls stopped updating the
head.

I took a look: the HMAC and parameter encryption seem fine.  There's a
marginal inefficiency in that the sessions are always encrypt/decrypt.
However, I think those two were separated because the TCG feared TPMs
wouldn't be efficient at key derivation and AES, which has proven not
to be the case in practice.

> Regarding authenticating the TPM, there's already a long discussion
> on https://github.com/systemd/systemd/issues/22637 with the TSS folks

Well trust on first use really isn't authentication, it's just
insurance that the TPM you've selected can't be switched under you once
you selected it for the initial key enroll.   I notice storing the name
in the luks keyslot still isn't implemented, but I think I pick up from
that issue that it will be, so you can close this one.

I'd advise that the longer problem of proving the TPM is the one the EK
cert says it is can actually be done separately once you have the name
stored somewhere, because that name can be validated at any time.  You
should absolutely do it before you commmit sensitive data to the
encrypted disk, but it doesn't have to be done when you first create an
encrypted disk because it doesn't contain any secrets and can be
disposed of if the name validation doesn't check out.

Regards,

James

**Comment by bluca** [comment]
Let's continue talking about authenticating the TPM over in the existing issue, to avoid splitting the discussions up: https://github.com/systemd/systemd/issues/22637

**Comment by poettering** [comment]
@jejb do you have some prior art/example code that does pinning of the TPM? i.e. what precisely would you actually pin? The "name" of the EK? and how would you verify the name later? request proof it can sign?

**Comment by jejb** [comment]
On Wed, 2022-12-14 at 07:41 -0800, Lennart Poettering wrote:
> @jejb do you have some prior art/example code that does pinning of
> the TPM? i.e. what precisely would you actually pin? The "name" of
> the EK? and how would you verify the name later? request proof it can
> sign?

This depends on your use case and threat model.  Traditionally the EK
certificate is what you use to verify the genuineness of the EK, so
Keylime

https://github.com/keylime/keylime

has all the eccentric code a TPM uses to prove it's the real owner of
an EK.  However, for a trust on first use model, you can simplify all
this to the name of a known derivative of the storage seed, say the EC
one you're already using.  TPM people don't see this as effective
binding because the storage seed changes with ownership (using the
TPM2_Clear command) but it matches precisely your use case (you'd have
to begin again with TPM based disk keys if the ownership changes
because all keys in the owner hierarchy are invalidated).

For interposer threats, binding, HMAC and encryption isn't sufficient
anyway and you have to prove the TPM you're talking to hasn't been
tampered with.  The active interposer attack that survives is the reset
one: the interposer waits until the malicious OS has sufficiently
booted, then resets the TPM, clearing the PCRs and then replays PCR
values to simulate an approved OS before getting to the key release. 
The method we've been toying with to defeat this in the kernel is
actually basing our encryption and HMAC sessions on the null hierarchy,
because its seed will change on an unexpected reset causing HMAC
failures

***@***.***/T/#u

You obviously can't bind to the null key because it changes on every
boot, but if you know the storage key, you can certify the null key
directly with the storage root key and avoid all the complicated make
credential/activate credential stuff you have to do with the
endorsement key.

The way you validate the storage key if you know the name is simply to
run a TPM2_Certify on it using it as the certification key as well. 
Effectively you get a self signed certification but that's enough to
prove the TPM you're talking to knows the private part of the storage
key (it's simple too: you just verify the signature and then compare
the name you have to the qualifiedSigner of TPMS_ATTEST).  Once you
have that, you can use the storage key to certify the null key.

James
