### ISSUE TITLE
test-mount-util failed in docker

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#25631]
### systemd version the issue has been seen with
249, I think this problem also exists in other versions

### Used distribution
openEuler

### Linux kernel version used
5.15

### CPU architectures issue was seen on
x86_64

### Component
test-mount-util

### Expected behaviour you didn't see
we try compile systemd in docker, but test-mount-util test failed
it is try remount "/run"
![image](https://user-images.githubusercontent.com/17870505/205645214-1ac5118a-09b4-4dc1-a6e1-08c6f9665dcd.png)
failed here
![image](https://user-images.githubusercontent.com/17870505/205646243-d28a5dec-c729-48f0-bb20-b94647aa1e7b.png)

**Comment by poettering** [comment]
We assume /run/ is a tmpfs. Please fix your environment if it isn't.

See https://systemd.io/CONTAINER_INTERFACE
