### ISSUE TITLE
systemd.journal-fields

### ISSUE THREAD

**Issue by woodz-** [systemd/systemd#25647]
### Component

- journalctl
- journal API
- systemd-journald

### Is your feature request related to a problem? Please describe

The [systemd.journal-fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#) documentation states that [Address Fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Address%20Fields) can not be matched by [sd_journal_add_match(3)](https://www.freedesktop.org/software/systemd/man/sd_journal_add_match.html#).

I'd like to ask, whether there is a possibility to receive those [Address Fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Address%20Fields)?

### Describe the solution you'd like

Could we use [`sd_journal_get_data`](https://www.freedesktop.org/software/systemd/man/sd_journal_get_data.html#) to receive those [Address Fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Address%20Fields)?

Or is there any other possibility to receive those [Address Fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Address%20Fields)?

I am especially interested on `__REALTIME_TIMESTAMP`.

### Describe alternatives you've considered

Same would be valid for all [Address Fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Address%20Fields):

- `__REALTIME_TIMESTAMP`
- `__CURSOR`
- `__MONOTONIC_TIMESTAMP`

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
sd_journal_get_monotonic_usec(), sd_journal_get_realtime_usec(), sd_journal_get_cursor() give you that data.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
