### ISSUE TITLE
configure.ac: a confusing help string.

### ISSUE THREAD

**Issue by Shuangistan** [systemd/systemd#2567]
Hi,
In the master branch we have the following lines in congifure.ac (currently from line 1178)
`have_gnuefi=no`
`AC_ARG_ENABLE(gnuefi, AS_HELP_STRING([--enable-gnuefi], [Disable optional gnuefi support]))`

The option for gnuefi is `--enable-gnuefi`
and the help string is `Disable optional gnuefi support`

This is a little bit confusing.

**Comment by Shuangistan** [comment]
Okay, I checked this also happens by bzip2.
`have_bzip2=no`
`AC_ARG_ENABLE(bzip2, AS_HELP_STRING([--enable-bzip2], [Disable optional BZIP2 support]))`
Now I wonder if this is an intention.

**Comment by poettering** [comment]
copy/paste error i figure...
