### ISSUE TITLE
HandleLidSwitchExternalPower not functioning as designed.

### ISSUE THREAD

**Issue by 31337-4554551n** [systemd/systemd#25694]
### systemd version the issue has been seen with

249

### Used distribution

Pop!_OS 22.04

### Linux kernel version used

6.0.6-76060006-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

/etc/systemd/logind.conf

HandleLidSwitch=lock
HandleLidSwitchExternalPower=suspend

Plug in laptop.
Close lid.
System locks.
Come back a few hours later.
Open lid.
System still locked.

The expectation is that while a power cable is plugged in, HandleLidSwitchExternalPower is obeyed.

### Unexpected behaviour you saw

/etc/systemd/logind.conf

HandleLidSwitch=lock
HandleLidSwitchExternalPower=suspend

Plug in laptop.
Close lid.
System locks.
Computer charges to 100%
System suspends.

I suspect that once battery hits 100% there is a short window while it's not charging, and HandleLidSwitch takes over.
May need some checks/timers to get this working as intended.

### Steps to reproduce the problem

Set

/etc/systemd/logind.conf

HandleLidSwitch=lock
HandleLidSwitchExternalPower=suspend

Close lid
Wait

**Comment by poettering** [comment]
Sorry, but 249 is too old here, and the power source detection logic recently received a lot of fixes and corrections. Hence let's close this. Please report back if you can reproduce on the current systemd release, i.e. 252
