### ISSUE TITLE
Tilde not expanded in ExecStart statement when used with "bash -c"

### ISSUE THREAD

**Issue by monochromec** [systemd/systemd#25695]
### systemd version the issue has been seen with

247

### Used distribution

Bullseye

### Linux kernel version used

5.10.0-19

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Tilde expanded properly in the following .service file excerpt

```
[Service]
Type=simple
User=synapse
WorkingDirectory=/home/synapse
EnvironmentFile=-/etc/default/matrix-synapse
ExecStart=bash -c '. ~/venv/bin/activate; python3 -m synapse.app.homeserver --config-path=~/homeserver.yaml'
```

Replacing the second ~with an explicit '/home/synapse' prefix did work though.

More than happy to provide additional info as required.

### Unexpected behaviour you saw

Python backtrace indicating that the config file path wasn't expanded properly (although the first tilde for the venv _**did**_ expand properly).

Dec 10 09:47:52 linuxinlaws.eu bash[1186133]:   File "/home/synapse/venv/lib/python3.9/site-packages/synapse/config/_base.py", line 846, in read_config_files
Dec 10 09:47:52 linuxinlaws.eu bash[1186133]:     with open(config_file) as file_stream:
Dec 10 09:47:52 linuxinlaws.eu bash[1186133]: FileNotFoundError: [Errno 2] No such file or directory: '~/homeserver.yaml'

### Steps to reproduce the problem

Put a venv and a Synapse installation in that directory and start it via the above service definition.

**Comment by bluca** [comment]
is that a system or user unit?

**Comment by monochromec** [comment]
system unit

**Comment by bluca** [comment]
That cannot possibly work, it wouldn't know what to expand it to, you need to specify it

**Comment by monochromec** [comment]
Or to be more precise (as this is missing from the somewhat superficial (read: vague) RCA in the previous comment): systemd is not to be blamed here; it rather boils down to the fact how the bash expands a tilde. As the bash [manual](https://www.gnu.org/software/bash/manual/html_node/index.html) explains: Tilde expansion is performed as part of the general parameter expansion process of bash which takes place _after_ [tokenization](https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html). As `--config=~/...` is interpreted as one word, tilde [expansion](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html) is not performed as the tilde has to be at the beginning of a word rather than in the middle of it.

So either specify a full path or use `$HOME` as variables are expanded regardless of position in a token.
