### ISSUE TITLE
journal is not stored in /var/log/journal and not persistent after reboots

### ISSUE THREAD

**Issue by rohitpai** [systemd/systemd#25712]
### systemd version the issue has been seen with

251

### Used distribution

Yocto Linux 

### Linux kernel version used

Linux hgx 5.15.50-bc6f78b 

### CPU architectures issue was seen on

arm

### Component

systemd-journald

### Expected behaviour you didn't see

I am using the [open bmc](https://github.com/openbmc/openbmc) distro on aspeed arm soc. 
I have the below configuration to make journal persistent. 

```
File - /usr/lib/systemd/journald.conf.d/journald-storage-policy.conf 
[Journal]
Storage=persistent
SystemMaxUse=16M
SyncIntervalSec=15

```
When I boot my system I see folder getting created under /var/log/journal directory 
```
ls -alt /var/log/journal/
drwxr-sr-x    2 root     systemd-         0 Jan  1 00:03 2b4305f670484d1fa6b9c4deee336b91
```

but the actual logs are still under /run/log/journal. 
journalctl --flush does not seem to create any new entry under /var/log/journal. 
After reboot the journal is lost. 

I have persistent jffs2 partition under which the directory /var/log/journal exists. 
I have also added file system dependency to ensure journal service can see this directory. 

```
[Unit]
Wants=local-fs.target
After=local-fs.target
```

/etc/machine-id is not changing on every boot and remain consistent after every boot.

 I have also tried modifying directory the file /etc/systemd/journal.conf and rebooting the system but it also has no effect. 

### Unexpected behaviour you saw

jouranal is lost after each boot despite persistent journal configuration.

**Comment by rohitpai** [comment]
Journal logs 
`root@hgx:~# journalctl -u systemd-journald
Jan 01 00:00:12 hgx systemd-journald[180]: Journal started
Jan 01 00:00:12 hgx systemd-journald[180]: Runtime Journal (/run/log/journal/b81d64f9c385494f87d5750793dd496d) is 8.0M, max 64.0M, 56.0M free.
Jan 01 00:00:12 hgx systemd-journald[180]: Runtime Journal (/run/log/journal/b81d64f9c385494f87d5750793dd496d) is 8.0M, max 64.0M, 56.0M free.
Jan 01 00:00:12 hgx systemd-journald[180]: Received client request to flush runtime journal.
Jan 01 00:00:12 hgx systemd-journald[180]: ;1;39mFailed to open system journal: Address family not supported by protocol
Jan 01 00:00:30 hgx systemd-journald[180]: Forwarding to syslog missed 25 messages.
Jan 01 00:01:01 hgx systemd-journald[180]: Forwarding to syslog missed 97 messages.
Jan 01 00:01:51 hgx systemd-journald[180]: Forwarding to syslog missed 55 messages.
Jan 01 00:03:47 hgx systemd-journald[180]: Forwarding to syslog missed 1 messages.`

**Comment by rohitpai** [comment]
The file system on the /var/log/journal is jffs2 
reading through the code of journald I found below section 

```
        r = mmap_cache_fd_get(f->cache_fd, CONTEXT_HEADER, true, 0, PAGE_ALIGN(sizeof(Header)), &f->last_stat, &h);
        if (r == -EINVAL) {
                /* Some file systems (jffs2 or p9fs) don't support mmap() properly (or only read-only
                 * mmap()), and return EINVAL in that case. Let's propagate that as a more recognizable error
                 * code. */
                r = -EAFNOSUPPORT;
                goto fail;
        }

```
can you please confirm that persistent journal is not supported with jffs2 file system ?
is there any work around for this ?

**Comment by yuwata** [comment]
We heavily use mmap() in journald. So, if the filesystem you use do not support it, then unfortunately there is nothing we can do. Please try to request to the jffs2 team about the support of mmap().

**Comment by M-Kamalesh** [comment]
Hi @rohitpai , what happen to this issue? So jffs2 file system does not support persistent journal?
