### ISSUE TITLE
LoadCredentials from a unix socket causes assertion errors

### ISSUE THREAD

**Issue by Mic92** [systemd/systemd#25719]
### systemd version the issue has been seen with

252.1

### Used distribution

NixOS unstable (23.05.20221212.f277f5a)

### Linux kernel version used

5.15.82

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

When loading secrets from a unix socket (instead of a file) i.e.: `LoadCredential=CA:/run/systemd-vaultd/sock`
it will open and load data from the socket.

### Unexpected behaviour you saw

it now throws an assertion error

```
Assertion 'dir_fd == AT_FDCWD || dir_fd >= 0' failed at src/basic/socket-util.c:1437, function connect_unix_path(). Aborting.
```

The same exception can be not reproduced in `251.7`

### Steps to reproduce the problem

1. Create a unix socket.
2. use `LoadCredential` in a systemd service file

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Dec 13 09:31:32 dev-00 systemd[6940]: Assertion 'dir_fd == AT_FDCWD || dir_fd >= 0' failed at src/basic/socket-util.c:1437, function connect_unix_path(). Aborting.
Dec 13 09:31:33 dev-00 systemd[6939]: grafana-agent.service: Failed to set up credentials: Protocol error
Dec 13 09:31:33 dev-00 systemd[6939]: grafana-agent.service: Failed at step CREDENTIALS spawning /nix/store/yrs2sl5g8irv3giwj3fz70kzgz2xcpdm-unit-script-grafana-agent-start/bin/gr
afana-agent-start: Protocol error
```

**Comment by Mic92** [comment]
I actually came up with a very similar fix independently and it fixed the issue:

https://github.com/Mic92/systemd/commit/c6779c09a9eb7d0bb182b160041c334ace11309e

I think you nailed the root cause already.

**Comment by Mic92** [comment]
@keszybz I think this is a candidate for systemd-stable (regression since 251.7)

**Comment by DaanDeMeyer** [comment]
It's been tagged as needing a backport so it'll end up in the next stable release
