### ISSUE TITLE
[networkd] bridged intefaces still get RA ipv6 addresses

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#2572]
I'm not sure if this is a kernel or networkd issue. My config is 2 (or 3 including wifi) interfaces in a bridge. All of the UP intefaces in the bridge will get an advertised ipv6 address. That makes ipv6 inoperable in the LAN.

The configs are:

```
#bridge.netdev
[NetDev]
Name=bridge0
Kind=bridge
```

```
#bridge.network 
[Match]
Name=bridge0
[Network]
DHCP=yes
```

```
#eth.network
[Match]
Name=ens5
[Network]
Bridge=bridge0
```

```
#tap.netdev
[NetDev]
Name=tap0
Kind=tap
```

```
#tap.network 
[Match]
Name=tap0
[Network]
Bridge=bridge0
```

```
# ip addr
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bridge0 state UP group default qlen 1000
    link/ether 52:54:00:f8:53:1a brd ff:ff:ff:ff:ff:ff
    inet6 fd02:bc52:2de8:0:5054:ff:fef8:531a/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fef8:531a/64 scope link 
       valid_lft forever preferred_lft forever
3: tap0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master bridge0 state DOWN group default qlen 500
    link/ether e6:cb:0d:9f:f5:c1 brd ff:ff:ff:ff:ff:ff
4: bridge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 26:eb:27:ae:6a:fe brd ff:ff:ff:ff:ff:ff
    inet 192.168.15.212/24 brd 192.168.15.255 scope global dynamic bridge0
       valid_lft 42427sec preferred_lft 42427sec
    inet6 fd02:bc52:2de8::64e/128 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fd02:bc52:2de8:0:24eb:27ff:feae:6afe/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::24eb:27ff:feae:6afe/64 scope link 
       valid_lft forever preferred_lft forever
```

Now, if I add LinkLocalAddressing=no in all the .network files eth, wifi, tap (pass the bridge), those intefaces don't get the ipv6 addresses and all is fine.

(edit)
if it's not obvious, the `ens5` inteface shouldn't have the fd02:bc52:2de8:0:5054:ff:fef8:531a/64 address.

Should networkd do this automatically or it's a kernel bug/mis-feature?

**Comment by aboe76** [comment]
@zonque you could try the following:

```
#eth.network
[Match]
Name=ens5
[Network]
Bridge=bridge0
IPv6AcceptRouterAdvertisements=no
```

**Comment by gdamjan** [comment]
that works. (but I need to set it on each inteface). shouldn't it be automatic?

**Comment by pkgadd** [comment]
Assuming @gdamjan reported his findings against systemd v229, I think the issue might be a bit larger (and a post v228 regression). 

With networkd v229 (Debian packaged version 229-1), I've noticed IPv6 addresses routes not just bleeding over to the physical bridge members, but also to unrelated (no physical connection, no forwarding involved) bridges. While IPv6AcceptRouterAdvertisements=false seemed to be worth a test (although probably "wrong"), it had devastating effects on the other bridges configured on my system. So far I haven't been able to achieve stable IPv6 connectivity with networkd v229 (the duplicate routes just lead to huge packet loss and problems with DHCPv6), while the very same configuration has been working well with networkd for close to a year (until/ including v228, Debian packaged version 228-6).

From the description in this issue thread, I think this might actually part of the same problem I've reported in detail (including my exact networkd configuration) to [https://bugs.debian.org/814566](networkd >= 229-1 starts assigning IPv6 addresses/ routes to lower bridge members) and it seems to also be an explanation for [https://bugs.debian.org/814667](systemd-networkd overrides default kernel net.ipv6.conf.interface.accept_ra) reported by someone else. Both have been reported as v228 --> v229 regression to the Debian BTS. My personal networkd configuration is [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814566;msg=5;filename=network.tar.gz;att=1], involving two independent physical network cards (br0 with an internet uplink and IPv6 connectivity (DHCPd, DHCPv6, RA) and br1 only connected to an isolated switch spanning an internal network for multiple clients (no internet uplink, static IPv4 addresses, not IPv6 addresses, no forwarding anywhere).

So far I've observed the following behaviour:
- Link local addresses and routes (fe80::/64) bleed over to the physical bridge members with both v229 and v228 (and earlier), while this might be technically wrong, this doesn't result in practical problems for me.
- The ULA prefix (fc00::/7), IPv6 addresses and routes, only bleed over to both physical bridge members and unrelated bridges starting with networkd v229; <= v228 is fine.
- Globally routable addresses (2001:470:xxxx:10::/64, both SLAAC and IPv6 privacy extensions), IPv6 addresses and routes, only bleed over to both physical bridge members and unrelated bridges starting with networkd v229; <= v228 is fine.

**Comment by pkgadd** [comment]
Bisecting this issue in a disposable VM points me at 'Revert "networkd: ndisc - revert to letting the kernel handle NDisc"', [https://github.com/systemd/systemd/commit/fe30727643a7c53faa29f1caa8dcabcb2b6f6fcb]. 

Reverting just fe30727643a7c53faa29f1caa8dcabcb2b6f6fcb on top of systemd v229 (technically the Debian packaged version 229-1) results in functional IPv6 connectivity again, without IPv6 addresses and routes bleeding over to individual bridge members or unrelated bridges.

**Comment by gdamjan** [comment]
as of 1db30ae an ethernet port in a bridge still gets an ipv6 address.

**Comment by revellion** [comment]
Is this issue solved?, it's a fairly problematic issue.

**Comment by gdamjan** [comment]
seems to be fixed post v230

**Comment by poettering** [comment]
OK, closing then.
