### ISSUE TITLE
systemd-gpt-auto-generator wrong device for /home mount on LUKS

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#25727]
### systemd version the issue has been seen with

252.3

### Used distribution

Archlinux

### Linux kernel version used

6.0.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

My /home volume is on LUKS on GPT partition 3, with GPT type UUID set to 933AC7E1-2EB4-4F13-B844-0E14E2AEF915 (Home Partition). The mount unit created by systemd-gpt-auto-generator should have the LUKS DM device node as the resource to mount:
```
[Mount]
What=/dev/mapper/home
```
this works properly on `main` and in `v252.2`, or when fc60072926989a97e52228b65106efad45fa7542 is reverted.

### Unexpected behaviour you saw

in v252.3, gpt-auto-generator generates an unit with the raw partition as the resource:
```
[Mount]
What=/dev/nvme0n1p3
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ fdisk -x ...
Device             Start        End   Sectors Type-UUID                            UUID                                 Name     Attrs
/dev/nvme0n1p3 201861120 1000215182 798354063 933AC7E1-2EB4-4F13-B844-0E14E2AEF915 A93A934C-BD30-2442-922E-11AD09E5BE19          


# 252.3 reverted fc60072926989a97e52228b65106efad45fa7542
$ sudo SYSTEMD_LOG_LEVEL=debug _build/systemd-gpt-auto-generator a b c
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Adding /: /dev/gpt-auto-root fstype=(any)
Kernel was quicker than us in adding partition 1.
Opened /dev/nvme0n1p1 (fd=5, whole_block_devnum=259:0, diskseq=1).
Kernel was quicker than us in adding partition 2.
Opened /dev/nvme0n1p2 (fd=6, whole_block_devnum=259:0, diskseq=1).
Kernel was quicker than us in adding partition 3.
Opened /dev/nvme0n1p3 (fd=7, whole_block_devnum=259:0, diskseq=1).
Probed fstype 'crypto_LUKS' on partition /dev/nvme0n1p2.
Probed fstype 'crypto_LUKS' on partition /dev/nvme0n1p3.
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Adding /boot: /dev/nvme0n1p1 fstype=vfat
Adding /home: /dev/nvme0n1p3 fstype=crypto_LUKS


# 252.3
sudo SYSTEMD_LOG_LEVEL=debug _build/systemd-gpt-auto-generator a b d
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Adding /: /dev/gpt-auto-root fstype=(any)
Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Adding /boot: /dev/nvme0n1p1 fstype=vfat
Adding /home: /dev/nvme0n1p3 fstype=(any)
```

**Comment by yuwata** [comment]
I guess, also backporting c80c9079c895f8e0285682a99fb3f91b892b8734 should fix the issue.
Could you try to backport the commit? Or, test the current git HEAD?

**Comment by yuwata** [comment]
Background: the offending commit drops the file descriptor of the partition node from the dissected partitions, so without the commit c80c9079c895f8e0285682a99fb3f91b892b8734, we cannot probe fstype of the partitions.
