### ISSUE TITLE
Unblock RTC-less system initial NTP synchronization by ignoring DNSSEC at ridiculous time

### ISSUE THREAD

**Issue by Icenowy** [systemd/systemd#25733]
### Is your feature request related to a problem? Please describe

When a system w/o RTC is booted with timesyncd enabled and resolved DNSSEC enabled and a domain-name-based NTP server configured, resolved DNSSEC will prevent the NTP server domain address (and most other things) from being resolved, thus the time won't be updated to the correct value, making a chicken-and-egg issue.

### Describe the solution you'd like

Maybe we can have systemd remember if it tweaks the system clock on boot, and disregard DNSSEC before another time change happen.

(In addition systems w/ RTC but w/o battery could have their RTC drivers loaded by udev, and thus having a date earlier the systemd build date after this, so time before systemd build should also be considered invalid for DNSSEC).

**Comment by yuwata** [comment]
We have already supported `$SYSTEMD_NSS_RESOLVE_VALIDATE` environment variable. See PR #18563, which is included in v248.
So, please set the environment variable to the NTP service you want to use. systemd-timesyncd.service already use it.
