### ISSUE TITLE
systemd-boot fails after updating systemd to 252.3

### ISSUE THREAD

**Issue by crondrift** [systemd/systemd#25737]
### systemd version the issue has been seen with

252.3-1

### Used distribution

Arch Linux

### Linux kernel version used

6.0.12-arch1-1 and 5.15.82-1-lts

### CPU architectures issue was seen on

x86_64

### Component

bootctl, systemd-boot

### Expected behaviour you didn't see

System booting correctly with systemd-boot.

### Unexpected behaviour you saw

System hangs immediately after choosing the boot-entry, just showing a black screen with the following message in top left corner in red letters:

Failed to open random seed file: Media changed
Error opening root path: Invalid Parameter

### Steps to reproduce the problem

- Coming from systemd 251.7-4 (which worked flawlessly) and updating to 252.3-1.
- Running 'bootctl update'
- Reboot

Updating to 252.3-1 WITHOUT running 'bootctl update' afterwards works fine. The system boots without any problems.

So the problem seems really systemd-boot related. Maybe something in 'systemd-bootx64.efi' has changed and my Lenovo E15 Gen 2 doesn't like that.

**Comment by medhefgo** [comment]
Does sd-boot from v252, v252.1 or v252.2 work? If possible can you do a [regression test](https://github.com/systemd/systemd/issues/25363#issuecomment-1312816824)?

**Comment by crondrift** [comment]
- v252.1 works
- v252.2 works
- v252.3 fails

**Comment by medhefgo** [comment]
I don't see how any commits in between could cause this. Which version of v252.2 did you check? There is v252.2-1 to v252.2-4.

For the non-working sd-boot, do you see a device path for that entry in the listing if you press `p` at the boot menu and is it the same compared to a working sd-boot? Is the loader path listed there also correct?

Also, the output of `bootctl` would be helpful.

**Comment by crondrift** [comment]
@medhefgo 
I've tested with v252.1-2 and with v252.2-4 - the device path is showing and is the same in every version (even v252.3-1).

`bootctl`

System:
      Firmware: UEFI 2.70 (Lenovo 0.4960)
 Firmware Arch: x64
   Secure Boot: disabled (setup)
  TPM2 Support: yes
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 252.2-4-arch
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/fba529a3-073a-504d-8d7b-767868e8a5e0
         File: └─/EFI/systemd/systemd-bootx64.efi

Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/fba529a3-073a-504d-8d7b-767868e8a5e0)
         File: ├─/EFI/systemd/systemd-bootx64.efi (systemd-boot 252.2-4-arch)
               └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 252.2-4-arch)

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0001
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/fba529a3-073a-504d-8d7b-767868e8a5e0
         File: └─/EFI/systemd/systemd-bootx64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/fba529a3-073a-504d-8d7b-767868e8a5e0)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #1 (.conf)
        title: Arch Linux
           id: 04-arch.conf
       source: /boot/loader/entries/04-arch.conf
        linux: /vmlinuz-linux
       initrd: /intel-ucode.img
               /initramfs-linux.img
      options: root=/dev/nvme0n1p2 rw net.ifnames=0 nowatchdog loglevel=3

**Comment by medhefgo** [comment]
The device path showing in v252.3 is just weird as the device handle changing is the only thing I can think of that could cause the error.

The culprits should be one of the December 8 commits on stable: https://github.com/systemd/systemd-stable/commits/v252-stable/src/boot/efi (probably either 87add68b396a3d8e75a82f1b405141a948072869 or 1c9e7fc8f28347e7151baa7163f0d5bb2cdb9611). But really, neither of these *should* be causing this…

Can you check whether the latest git main branch works? (Ideally a regression test so I don't have to make a guess to which commit is the culprit.)

**Comment by crondrift** [comment]
I did a regression test starting with defining `v251` as good version:

`git bisect bad`

b99bf5811850afdb2502ba37251c48348da63c82 is the first bad commit

**Comment by medhefgo** [comment]
> [b99bf58](https://github.com/systemd/systemd/commit/b99bf5811850afdb2502ba37251c48348da63c82) is the first bad commit

Connecting console devices making the ESP suddenly inaccessible makes no sense to me, are you sure this is the one?

Can you try this branch, hopefully that will fix it (or at least tell me which call exactly is failing): https://github.com/medhefgo/systemd/tree/boot-fixes

You plug one hole and another firmware gets their panties in a bunch. EFI vendors are gonna drive me insane.

**Comment by crondrift** [comment]
@medhefgo 

This time, the error is slightly different. I tried my best and I'm not sure, if I did it right.

![error](https://user-images.githubusercontent.com/75867848/208030802-ae09a0db-6c7f-496a-8407-42efdbe91249.png)

What's also curious...on every version that fails, the boot menu doesn't show as normal. It's alligned to the left and the entries only pop up one after another, when you select them with the arrow keys (sorry for the bad quality, but I think you get the idea).

![bootmenu2](https://user-images.githubusercontent.com/75867848/208031362-4acfc932-8e54-46b1-a336-09da18efd386.png)

**Comment by medhefgo** [comment]
Please try the attached PR to see if it fixes your issue.

**Comment by crondrift** [comment]
@medhefgo 

I've tested it. Now everything is working again as expected: bootloader menu is back to normal, system boots fine.

**Comment by eybisi** [comment]
> @medhefgo 
> 
> I've tested it. Now everything is working again as expected: bootloader menu is back to normal, system boots fine.

Can you explain how you did it? I'm struggling with updating systemd

**Comment by crondrift** [comment]
I've built the bootloader binary from this branch: https://github.com/medhefgo/systemd/tree/boot-fixes
