### ISSUE TITLE
Use XDG_STATE_HOME in StateDirectory= and LogsDirectory= unit directives

### ISSUE THREAD

**Issue by runiq** [systemd/systemd#25739]
### Component

systemd

### Is your feature request related to a problem? Please describe

Systemd units have the very useful properties `{Runtime,State,Cache,Logs,Configuration}Directory=`. However, for user units, `StateDirectory=` and `LogsDirectory=` default to `$XDG_CONFIG_HOME`.

On the one hand, this is understandable since these should probably not be deleted carelessly. On the other hand, application state and logs are not strictly configuration files—system units don't place app state and logs in `/etc`, either, but use subdirectories under `/var/lib` and `/var/log`.

### Describe the solution you'd like

Starting with version 0.8 from May 2021, the XDG basedir spec [has a new entry](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) `XDG_STATE_HOME`, which defaults to `$HOME/.local/state`. This is arguably a more fitting base directory for app state and possibly logs.

### Describe alternatives you've considered

I'm currently not using the `{State,Logs}Directory=` directives as a result of the above, though I really like the functionality and would love to be able to use them (I use `{Runtime,Cache,Configuration}Directory=` extensively).

An alternative for logs might be `$HOME/.local/log`, akin to `/var/log` for system units, seeing how `$HOME/.local` appears to fulfill the role that `/var` fulfills for the system.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by runiq** [comment]
I just realized that the same thing is going on with the `%S` and `%L` placeholders in units, which point to `$XDG_CONFIG_HOME` and `$XDG_CONFIG_HOME/logs`, respectively.

**Comment by YHNdnzj** [comment]
@poettering Hmm, do we want to retain the compatibility with existing directories under `$XDG_CONFIG_HOME`?

**Comment by poettering** [comment]
@YHNdnzj i think we do. not sure what the best strategy here is. $XDG_STATE_HOME should definitely be honoured if set. But what to do if it isn't, I am not sure? i.e. search for the resource in both $XDG_STATE_HOME and $XDG_CONFIG_HOME? let the apps search? i have no idea. all options i can think of suck in some way...

**Comment by poettering** [comment]
Fix → #28168
