### ISSUE TITLE
SystemD & IMA & TPM : the order of the service is important

### ISSUE THREAD

**Issue by mickae1** [systemd/systemd#25746]
### systemd version the issue has been seen with

230

### Used distribution

Debian

### Linux kernel version used

4.4.13

### CPU architectures issue was seen on

arm

### Component

systemd

### Expected behaviour you didn't see

I've enabled IMA ( integrity measurement architecture) on my device.
But at each boot, the order of the service changed because some of them are starting at the same time.

therefore when I check /sys/kernel/security/ima/ascii_runtime_measurements the order of the process changed.

And at the end, my PCR 10 is different at each boot.

I would like to know how people get around this ? Is there a way to tell systemD to disable starting service at the same time, or a special mode for IMA ?

**Comment by yuwata** [comment]
Sorry, v230 is too old here. Please test with the recent release (v251 or v252) or the current git HEAD.
Or, please contact to your downstream.

**Comment by poettering** [comment]
I don't think IMA even intends to provide a stable PCR value. It uses it only as a mechanism to protect the IMA logs, so that it can be proven it checks out.

Linux is a multitasking OS, things run in parallel, that's intended. If you serialize everything and run it in order you'd have an amazingly slow OS.

Anyway, this is probably something to bring up with the IMA people, it's not a systemd issue really.

**Comment by mickae1** [comment]
OK thank you,

@yuwata  I know it's an old version, but I just wanted to have opinion from expert here that use IMA.
@poettering Yes the PCR is something that is moving. But I thought that at the beginning the PCR 10 was the same. In the policy I removed the FILE_CHECK to have only binary, library and module in the list of measurements

**Comment by poettering** [comment]
(btw, even if systemd would run services in a strictly defined order, you never know what the services will then do, i.e. for off processes in any order. I mean, many services fork off worker processes, and if they do the order in which they get invoked might end up being entirely undeterministic)
