### ISSUE TITLE
[RFE] systemctl edit

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#25767]
### Component

systemctl

### Is your feature request related to a problem? Please describe

As more and more people and packages in distro's start to use "drop-in" files to modify default unit configs, we can have multiple drop-in files for different adjustments.

But it occurred to me that the `systemctl edit` functionality is lacking behind, because it only allows to edit one file eg. the `override.conf` drop-in only.
And we have no way to tell to use a different name, or to edit another drop-in of same unit, except using a manual route to create/edit the said drop-in and do a `daemon-reload` :wink: 

### Describe the solution you'd like

I would like to suggest an enhancement to the `systemctl edit` functionality to accept an optional second argument where you provide the name you want for the drop-in file, eg:
- `systemctl edit "$UNIT_NAME" "$DROPIN_FILENAME"`

As in <kbd>systemctl edit myservice 99-admin</kbd>, which would open the `99-admin.conf` file in the editor as drop-in file to create/edit.
_(Ofcourse with a backwards-compatible fall-back to the current drop-in filename used, if no second argument was provided)_

### Describe alternatives you've considered

There's no alternative AFAIK, except using a manual route to create/edit the said drop-in and do a `daemon-reload` :wink:

**Comment by YHNdnzj** [comment]
> systemctl edit "$UNIT_NAME" "$DROPIN_FILENAME"

Since it's allowed to edit multiple units at once, such way of specifying filename can't be used. But adding a new option for this should be fine :)

**Comment by TriMoon** [comment]
> Since it's allowed to edit multiple units at once

ohhh? Didn't know that :rofl:
