### ISSUE TITLE
Mention in the docs that LoadCredential= & friends is only available for the system service manager

### ISSUE THREAD

**Issue by runiq** [systemd/systemd#25768]
### Component

systemd

### Is your feature request related to a problem? Please describe

I tried for a good while to get `LoadCredential=` to work with my systemd user service until I found out that it is `--system` only. The only place mentioning that fact appears to be [the `NEWS` file](https://github.com/systemd/systemd/blob/ea4b8f4cbfffe193486c7995db49564ebea61191/NEWS#L3651).

### Describe the solution you'd like

Mention in `systemd.exec` that `LoadCredential=` etc. are available for system services only.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by bluca** [comment]
It works fine in v252?

```
$ systemd-run --user -t --property LoadCredential=foo --property SetCredential=foo:bar --unit foo sh -c 'cat $CREDENTIALS_DIRECTORY/foo'
Running as unit: foo.service
Press ^] three times within 1s to disconnect TTY.
bar
```

**Comment by runiq** [comment]
Ah, alright, I can reproduce, thank you! Must have made some other mistake, then. Sorry for the noise!
