### ISSUE TITLE
Wrong systemd PCR measurement for EFI stub without .splash or .dtb sections

### ISSUE THREAD

**Issue by kamel-bouhara** [systemd/systemd#25761]
### systemd version the issue has been seen with

252

### Used distribution

Yocto custom distribution

### Linux kernel version used

6.0.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot, systemd-cryptsetup, systemd-stub, other

### Expected behaviour you didn't see

Expected values seen in PCR register 11 on the UKI build machine:

/usr/lib/systemd/systemd-measure calculate \
         --linux=bzImage-initramfs.bin \
         --osrel=os-release \
         --cmdline=cmdline \
         --initrd=initrd \
         --pcrpkey=tpm2-pcr-public.pem \
         --phase=: \
         --bank=sha256

### Unexpected behaviour you saw

PCR 11 Hash value returned doesn't not match because the measured sections are not reflecting the UKI sections.

On x86_64 section **.dtb** is not used and **.splash** is not used in the above example so currently sd-stub measure empty sections which doesn't allow to enroll PCR policies on such UKI.

### Steps to reproduce the problem

Command to reproduce a stub without .dtb/.splash sections :

objcopy \
        --add-section .osrel=os-release \
        --change-section-vma .osrel=0x20000 \
        --add-section .cmdline=cmdline \
        --change-section-vma .cmdline=0x30000 \
        --add-section .linux=bzImage-initramfs.bin \
        --change-section-vma .linux=0x2000000 \
        --add-section .initrd=initrd \
        --change-section-vma .initrd=0x30000000 \
        --add-section .pcrsig=tpm2-pcr-signature.json \
        --change-section-vma .pcrsig=0x80000 \
        --add-section .pcrpkey=tpm2-pcr-public.pem \
        --change-section-vma .pcrpkey=0x90000 linuxx64.efi.stub \
        linux.efi \

**Comment by bluca** [comment]
@kamel-bouhara are you able to reproduce the issue if you build using ukify ( https://github.com/systemd/systemd/blob/main/src/ukify/ukify.py )? There is a suspicion this might be due to overlapping sections in the PE

**Comment by keszybz** [comment]
I tested this locally in a VM, and I get the expected value with`ukify`. I didn't try with `objcopy`, but that might not be useful anyway, because whether `objcopy` has issues depends on how large the stub and other components are, so my result wouldn't mean much for the reporter.

**Comment by keszybz** [comment]
I cleared the milestone because it seems reasonable to assume that there's no general issue.
Please also report precise version of system-stub and other details. If possible, please attach the original kernel and initrd and the combined efi that shows the issue.

**Comment by poettering** [comment]
Closing due to lack of response. Feel free to reopen if this is reproducible with ukify and current sd-stub.
