### ISSUE TITLE
networkd: link marked failed after adapter reset

### ISSUE THREAD

**Issue by baloo** [systemd/systemd#25765]
### systemd version the issue has been seen with

247

### Used distribution

Nixos

### Linux kernel version used

5.4

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Interface should come back up

### Unexpected behaviour you saw

Due to cable failure or hardware mishap, the NIC adapter decided to reset itself, after the link would back up networkd would have marked the link as failed and would not configure it.

Here is an extract of the logs:
```
Dec 15 12:33:22 hub kernel: ixgbe 0000:01:00.0 enp1s0f0: initiating reset due to tx timeout
Dec 15 12:33:24 hub kernel: ixgbe 0000:01:00.0 enp1s0f0: Reset adapter
Dec 15 12:33:30 hub systemd-networkd[2666]: enp65s0f0: Could not set NDisc route: Connection timed out
Dec 15 12:33:30 hub systemd-networkd[2666]: enp65s0f0: Failed
Dec 15 12:33:30 hub kernel: ixgbe 0000:01:00.0 enp1s0f0: NIC Link is Up 10 Gbps, Flow Control: RX/TX
Dec 15 12:33:32 hub systemd-networkd[2666]: enp1s0f0: Lost carrier
Dec 15 12:33:32 hub systemd-networkd[2666]: enp1s0f0: DHCPv6 lease lost
Dec 15 12:33:32 hub systemd-networkd[2666]: enp1s0f0: Gained carrier
```

### Steps to reproduce the problem

I don't have a way to reproduce this failure. I've spent some hours playing with Qemu but have been unable to so far.

**Comment by yuwata** [comment]
Sorry, v247 is too old here. Please contact to your downstream, or reproduce the issue with a recent release (v251 or v252) or the current git HEAD. Closing.

**Comment by baloo** [comment]
sorry but if I read the code correctly, this behavior will reproduce. If the ndisc route is failing it will mark the link as failed.

I was mostly opening this case to see what could be the best course of action, whether to just reflag the link as healthy when the link came back or something else.

**Comment by yuwata** [comment]
Several NIC drivers (e.g. one for Intel NIC) reset an interface when its MTU is changed. Do you set MTU related settings in the corresponding .network file for the interface?

Anyway, please please reproduce the issue with one of the recent release or the current git HEAD.
We have several commits, e.g. b732606950f8726c0280080c7d055a714c2888f5, to handle interface reset more gracefully.

**Comment by baloo** [comment]
looks related to https://github.com/systemd/systemd/issues/29246
