### ISSUE TITLE
Harden default ESP/XBOOTLDR automount

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#25776]
### Component

systemd-gpt-auto-generator

### Is your feature request related to a problem? Please describe

`boot.mount` (as created by automounting) can potentially be hardened further without affecting the majority of setups (at least as far as I know, please say if not).

### Describe the solution you'd like

Add `noexec` and maybe `nosuid` to the `Options` line in `boot.mount` by default. The thinking being:

- `noexec`: There's no reason for anything executable by the OS to be in here.
- `nodev`: Automounts don't create nested mounts to `/boot/efi`, so mounting a device under `/boot` won't be needed. But, future loopback devices won't work.
- `nosuid`: Not sure if FAT32 can even handle `suid` bits, so this one's unclear.

### Describe alternatives you've considered

If some of these options do conflict with a significant number of setups, or aren't as useful if FAT32 lacks the capability anyways, only adding some of these options would be fine (but to be honest, I'd be fine with none getting through if it turns out all of them are each too restrictive; this issue would be useful as reference).

### The systemd version you checked that didn't have the feature you are asking for

252.3-1-arch

**Comment by TriMoon** [comment]
> * `noexec`: There's no reason for anything executable by the OS to be in here.

Why restrict people to place special purpose scripts/binaries in `/boot` at all by default?
The files in `/boot` include (by purpose) binaries **to-be executed**, although by the UEFI instead of the Kernel, but you can imagine people wanting to place utilities there...
fe. to generate PK/MoK keys that is shared between multiple OS's, to keep them in one spot.

> * `nodev`: Automounts don't create nested mounts to `/boot/efi`, so mounting a device under `/boot` won't be needed. But, future loopback devices won't work.

It's rather normal practice to mount the `$ESP` on `/boot/efi` after `/boot` is mounted.
I even "bind-mount" `$ESP/xxxx` as `/boot` or `$ESP` as `/boot/efi` when/as needed :wink: 

> * `nosuid`: Not sure if FAT32 can even handle `suid` bits, so this one's unclear.

By the way the `/boot` partition can (IIRC) also be another filesystem type beside FAT32.
Think about grub that supports `btrfs` as example, or `ntfs` etc...

**Comment by Winterhuman** [comment]
@TriMoon You're right, I just realised `boot.mount` literally means whatever is mounted at `/boot`, and not the ESP or XBOOTLDR specifically. In that case, the following is probably better(?):

For the default `efi.mount` (and maybe `boot-efi.mount` too since that won't affect `/boot/efi`, only `/boot/efi/*` would be), set `nodev` since mounting devices in the ESP like `/efi/*` isn't a typical mount scenario. `noexec` may interfere with scripts so should be left out, and it's still unclear if `nosuid` would even help `efi.mount` since I don't think FAT32 even supports those bits (though `boot.mount` for XBOOTLDR may be useful)

**Comment by Winterhuman** [comment]
Is it possible for systemd to change `boot.mount`'s default options depending on if the ESP or XBOOTLDR is being used?

**Comment by Winterhuman** [comment]
On second thoughts, yeah, this isn't a good idea; there's too many options when talking about boot scripts to even use `nosuid` without affecting at least something. Closing issue

**Comment by TriMoon** [comment]
@poettering , just a side-question: Wondering about `gpt-auto-discovery`...

Does `gpt-auto-discovery` count for multiple `$ESP`'s on different disks?
I know that `sd-boot` provides the used `$ESP` to the OS, but how about other boot loaders?

In case non of the bootloaders used, provide the actual used `$ESP` to the OS:
- How does `gpt-auto-discovery` decide which one to mount as `$ESP` ?

**Comment by poettering** [comment]
> @poettering , just a side-question: Wondering about `gpt-auto-discovery`...
> 
> Does `gpt-auto-discovery` count for multiple `$ESP`'s on different disks?

No. It only mounts the ESP on the disk backing the root fs, and only if it was the one the firmware actually used for booting.

gpt-auto-discovery is actually two things:

1. mount the rootfs is root= is not specified on kernel cmdline. here we look for the root fs exclusively on the disk the ESP used for booting is on.
2. mount all other related partitions. Here we look for the partitions on the same disk as the root fs used.

These two parts are fairly independent. For the first item to work we need a boot loader that tells userspace the used ESP. For the second part we don't however.

anyway, no raid in any of this.
