### ISSUE TITLE
MSI Bravo 15-B5DD - additional hwdb entry for micmute

### ISSUE THREAD

**Issue by noodlejetski** [systemd/systemd#25782]
### systemd version the issue has been seen with

252.3-1

### Used distribution

Arch Linux

### Linux kernel version used

6.0.12-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Pressing `Fn+F5` combination mutes the microphone

### Unexpected behaviour you saw

Pressing `Fn+F5` combination doesn't mute the microphone; `dmesg` logs an error about an unknown key being presesd.

### Steps to reproduce the problem

1. Launch system on an MSI Bravo 15-B5DX laptop
2. Press `Fn+F5`
3. Observe the lack of microphone status change

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[113881.503355] atkbd serio0: Unknown key pressed (translated set 2, code 0xf1 on isa0060/serio0).
[113881.503367] atkbd serio0: Use 'setkeycodes e071 <keycode>' to make it known.
```

**Comment by noodlejetski** [comment]
adding the following lines to `60-keyboard.hwdb` makes the `Fn+F5` combination work as expected:

`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*Bravo15B5D*:*`
` KEYBOARD_KEY_f1=f20                                    # Fn+F5 Micmute`

**Comment by yuwata** [comment]
The proposed change looks basically good to me. But please drop the apostrophe at the end of the modalias line.

Still, please try to submit the change by a PR. Your help is much appreciated.

**Comment by noodlejetski** [comment]
> The proposed change looks basically good to me. But please drop the apostrophe at the end of the modalias line.
> 
> Still, please try to submit the change by a PR. Your help is much appreciated.

yeah, the apostrophe was a remnant of me tinkering with Github formatting. 
anyway, I *think* I've created the (deapostrophied) pull request with my change?
