### ISSUE TITLE
hwdb/sensors: Mismatch between PROXIMITY_NEAR_LEVEL property and in_proximity_nearlevel sysfs attribute

### ISSUE THREAD

**Issue by pjungkamp** [systemd/systemd#25793]
The kernel documentation for the in_proximity_nearlevel on iio
proximity devices (link: [0]) states:

> If the value read from the sensor is above or equal to the value in
> this file an object should typically be considered near.

Meaning a 'greater than or equal to' comparison.

The documentation of PROXIMITY_NEAR_LEVEL in 60-sensors.hwdb (link: [1]) on the
other hand states:

> ```
> # and <value> is an integer value above which an object is considered
> # close by a proximity sensor:
> #   PROXIMITY_NEAR_LEVEL=100
> ```

Suggesting a 'greater than' comparison.

The iio/light/hid-sensor-prox.c driver in the kernel exposes 'human
presence' HID sensor devices, which are binary 0 or 1.

Per the comment in 60-sensors.hwdb the proper value for these devices seems to be 0. But the proper value for exposing it as a sysfs attribute
in the driver should be 1.

An example where these meanings were confused is the proximity sensor driver in iio-sensor-proxy (link: [2]). Which reads the hwdb PROXIMITY_LEVEL_NEAR and falls back to the sysfs attribute, considering both values to mean the same threshold.

[0]:
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-iio-proximity
[1]: https://github.com/systemd/systemd/blob/e6319a102e5b6f7c1588ca851d66db7c3ade1665/hwdb.d/60-sensor.hwdb#L48-L50
[2]: https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/blob/master/src/drv-iio-poll-proximity.c#L82

**Comment by yuwata** [comment]
Could you submit a PR that updates the document in the hwdb file?
