### ISSUE TITLE
bus-proxyd uses cpu too much than dbus-daemon.

### ISSUE THREAD

**Issue by ganadist** [systemd/systemd#2580]
Systemd Version: 
systemd 228
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

Distribution:
ArchLinux ( linux 4.4.1-2-ARCH with kdbus-git(aur, https://aur.archlinux.org/packages/kdbus-git/ ) )

Details:

I tried some benchmarks between kdbus and dbus reference daemon using modified test-bus-benchmark.c.

And I uploaded results at https://gist.github.com/ganadist/fa94384e5091ce4165e6

It is evident that KDbus is faster than dbus-daemon, but I found that I got horrible benchmark result when using bus-proxyd, and it is slower as data size as bigger.

And I made another script, and it seems bus-proxyd itself is bottleneck.
https://gist.github.com/ganadist/1b6100f0433d00331c6a

**Comment by poettering** [comment]
Obsoleted by #2618.
