### ISSUE TITLE
90-uki-copy.install should autodetect unified kernels

### ISSUE THREAD

**Issue by kraxel** [systemd/systemd#25822]
### Component

kernel-install

### Is your feature request related to a problem? Please describe

Current `90-uki-copy.install` depends on a global switch to turn on uki mode.
This makes it impossible to install uki and non-uki kernels side-by-side.

### Describe the solution you'd like

 `90-uki-copy.install` could autodetect (using the .sdmagic section) whenever a given kernel binary is a UKI or not.

### Describe alternatives you've considered

We could add a `--uki` switch to `kernel-install` so the caller can specify whenever the given kernel is a UKI or not.

**Comment by kraxel** [comment]
See also discussion in https://gitlab.com/kraxel/kernel-ark/-/commit/a74829a7c4c1e296be6a1f18cc5cc655d6935e8e

**Comment by poettering** [comment]
probably should look for .osrel or .initrd rather than .sdmagic, to make the logic less systems-specific.

I figure this should be selectable, i.e. one of:

1. auto mode: install ukis as type2 and other stuff as type1
2. uki mode: install everything as type2
3. type1 mode: install everything as type1

after all you can install ukis via type1 snippets too if you like.

**Comment by 05storm26** [comment]
The linked discussion also mentions adding a `--layout` option to kernel-install to override the layout configured inside `/etc/kernel/install.conf`. 

That seems like a nice addition anyway. Could we have that in kernel-install?

**Comment by kraxel** [comment]
> probably should look for .osrel or .initrd rather than .sdmagic, to make the logic less systems-specific.

Ideas how to do that best?  `objdump` would work of course, but I guess we better don't depend on binutils being installed.  Other candidates?  Or do we need a new utility for that?  Something to inspect + pretty-print UKIs (show cmdline, version etc.) would be quite useful anyway I think.

**Comment by kraxel** [comment]
https://github.com/systemd/systemd/pull/26082 adds `is-uki` to `bootctl`
