### ISSUE TITLE
Hibernate forgets to poweroff the computer on kernel 6.0.12

### ISSUE THREAD

**Issue by initzx** [systemd/systemd#25821]
### systemd version the issue has been seen with

252.4-1

### Used distribution

Arch Linux 

### Linux kernel version used

6.0.12.arch1-1

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Closing the lid, or running `systemctl hibernate` should freeze the ram to disk and then proceed to poweroff the computer. 
In sleep.conf, I also have `HibernateMode=shutdown`

### Unexpected behaviour you saw

The freezing of the ram occurs as it should, but the system does not shut down. You have to force a hard shutdown by pressing the power button. Upon rebooting the system loads the previous hibernation state without loss of data, so it is just that the system fails to poweroff. 

The hibernation works properly with kernel 5.15 lts and 5.16, so something happened between 5.15 and 6.0

**Comment by poettering** [comment]
That's not a systemd issue, we just tell the kernel to hibernate. Please contact your distro for help, as this is a kernel issue and they can help you with it.
