### ISSUE TITLE
systemd-fsck : fsck failed with exit status 8

### ISSUE THREAD

**Issue by morialo3** [systemd/systemd#25833]
### systemd version the issue has been seen with

v252.4

### Used distribution

Manjaro 22.0.0

### Linux kernel version used

5.15.85-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-fsck

### Expected behaviour you didn't see

`fsck` shouldn't give a wrong statement `systemd-fsck[]: fsck: /usr/bin/fsck.btrfs: execute failed: No such file or directory`, 
from terminal:
```
/usr/bin/fsck.btrfs
If you wish to check the consistency of a BTRFS filesystem or
repair a damaged filesystem, see btrfs(8) subcommand 'check'.
```
and should run as expected at boot.

### Unexpected behaviour you saw

`Systemd-fsck` failed and exited.

### Steps to reproduce the problem

Add `fsck` to `HOOKS` in `/etc/mkinitcpio`, rebuild image(s), go to `/etc/fstab` and add `1` to the `fsck` relevant section for your mount drive, reboot, see `journalctl`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/morialo3/25b287cca86c3010cecbb368e892c922
```

**Comment by Zesko** [comment]
`base` is missing from `HOOKS` in the file `/etc/mkinitcpio`, that's what causes the issue.

You need to add `base` to `HOOKS` .

**Comment by morialo3** [comment]
Will adding `base` solved it, looks like the Arch Wiki needs to correct  `base` being  "Optinal" hook when `systemd`  is used inside `mkinitcpio.conf` `HOOKS` and `fsck` is present. thanks @Zesko.
