### ISSUE TITLE
cgroup2: Unknown parameter 'memory_recursiveprot'

### ISSUE THREAD

**Issue by xiacunshun** [systemd/systemd#25834]
### systemd version the issue has been seen with

251

### Used distribution

OpencloudOS

### Linux kernel version used

5.4.119-20.0009.15

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

None error occured when os is booting.

### Unexpected behaviour you saw

[root@localhost ~]# grep -nr "recursiveprot" /var/log/messages 
397:2022-12-21T04:26:13.063658+00:00 localhost kernel: cgroup2: Unknown parameter 'memory_recursiveprot'
1853:2022-12-21T06:43:11.102594+00:00 localhost kernel: cgroup2: Unknown parameter 'memory_recursiveprot'
3154:2022-12-21T06:48:36.067793+00:00 localhost kernel: cgroup2: Unknown parameter 'memory_recursiveprot'
4467:2022-12-21T08:48:04.222439+00:00 localhost kernel: cgroup2: Unknown parameter 'memory_recursiveprot'
5795:2022-12-22T13:41:46.444856+00:00 localhost kernel: cgroup2: Unknown parameter 'memory_recursiveprot'

Is there any method that can mute this error shown when booting?

### Steps to reproduce the problem

none

**Comment by xiacunshun** [comment]
I knew that the version of kernel caused it, but I just want to let this log not be shown.

**Comment by xiacunshun** [comment]
Like this.
https://github.com/xiacunshun/systemd/commit/875deb1b0a880142c839979673972e0a6967c7ed

**Comment by poettering** [comment]
You are using a really new systemd on an old kernel. Upgrade to kernel 5.7 and the message will go away. 

The mount option is only available on new kernels, it is ignored on older ones (but you'll see the warning). We want to use it, hence we set it.

This is mostly a cosmetic issue you can safely ignore.

**Comment by xiacunshun** [comment]
This message can be muted by this patch.
https://github.com/systemd/systemd/pull/28154
