### ISSUE TITLE
coredump: Missing documentation that `kernel.core_pattern=|/bin/false` is done by systemd

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#25831]
systemd 252

### Is your feature request related to a problem? Please describe

We tried to figure out why Linux’ kernel core pattern is piped to `/bin/false`.

    $ more /proc/sys/kernel/core_pattern
    |/bin/false

We had

    $ ls -lh /etc/sysctl.d/50-coredump.conf
    lrwxrwxrwx 1 root root 9 Apr 23  2018 /etc/sysctl.d/50-coredump.conf -> /dev/null

Looking at the source, it’s done by systemd:

https://github.com/systemd/systemd/blob/bf1886226724b3db0779d643195d428575cff0be/src/shared/coredump-util.c#L84

But is not documented.

**Comment by poettering** [comment]
This should never be visible. It's done during early boot, and late shutdown, when coreumps cannot be processed sanely.

I doubt we need to document such internal behaviour officially.

**Comment by poettering** [comment]
Anyway, let's close this.

**Comment by paulmenzel** [comment]
> This should never be visible. It's done during early boot, and late shutdown, when coredumps cannot be processed sanely.
> 
> I doubt we need to document such internal behaviour officially.

Sorry for not explaining the issue properly. We disable systemd-coredump by following https://github.com/systemd/systemd/issues/659#issuecomment-123785644

    $ ls -lh /etc/sysctl.d/50-coredump.conf
    lrwxrwxrwx 1 root root 9 Apr 23  2018 /etc/sysctl.d/50-coredump.conf -> /dev/null

Then we see,

    $ more /proc/sys/kernel/core_pattern
    |/bin/false

and do not find the reason in the documentation. So it’s not internal behavior, but very user visible.

**Comment by poettering** [comment]
Masking stuff is quit an intrusive concept, we generally expect that you are ready to deal with the implications of such an intrusive operation.

Where would you even suggest we document that, where you'd have looked?
