### ISSUE TITLE
SERVFAIL after temporary dns outage

### ISSUE THREAD

**Issue by geovex** [systemd/systemd#25841]
### systemd version the issue has been seen with

252.4-2-arch

### Used distribution

arch

### Linux kernel version used

6.1.1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

resolving domains

### Unexpected behaviour you saw

SERVFAIL on every request

### Steps to reproduce the problem

- stop DNS server (simulate outage)
- wait for `Using degraded feature set TCP...` in logs (you may need to make some queries)

at this point resolved sends nothing on the wire forever (or at least for a very long time) until restart

- start dns server 
- `host google.com <dns-ip>` works while `host google.com` return SERVFAIL (again, nothing in wireshark)

there are so many similar duplicates, I couldn't find original.

**Comment by geovex** [comment]
Ok. now i can't reproduce this behavior in 253.4. So most likely it's fixed.

**Comment by yrro** [comment]
> Ok. now i can't reproduce this behavior in 253.4. So most likely it's fixed.

Can you close the issue then?
