### ISSUE TITLE
boot menu doesn't repaint (countdown/boot entry selection)

### ISSUE THREAD

**Issue by fkroener** [systemd/systemd#25846]
### systemd version the issue has been seen with

252

### Used distribution

Archlinux

### Linux kernel version used

6.0.12

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

Kernel selection updating to reflect the chosen kernel.

Timer updating to reflect the seconds until boot.

### Unexpected behaviour you saw

Keyboard input (via USB) works, confirmed by booting a non-default kernel. Boot menu appears frozen.

### Steps to reproduce the problem

Reboot the system
wait for vendor logo to disappear
boot menu appears but doesn't refresh

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
System:
      Firmware: UEFI 2.70 (Lenovo 0.4944)
 Firmware Arch: x64
   Secure Boot: disabled (disabled)
  TPM2 Support: yes
  Boot into FW: supported

Current Boot Loader:
      Product: systemd-boot 252.4-1-arch
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/d1b2afb8-ed73-1b4f-a46c-dcf7c1573708
         File: └─/EFI/systemd/systemd-bootx64.efi

loaders.conf:
default arch
timeout 4
console-mode keep 
editor yes

possibly relevant kernel options: quiet splash loglevel=3 rd.udev.log_priority=3
```

**Comment by medhefgo** [comment]
Please try the attached PR to see if it fixes your issue.

This looks like it's related to #25737 as it's also a Lenovo firmware. It's interesting that you can still boot fine while the other issue report cannot even boot the loaded entry.

I expect that this one could simply be fixed by reordering the menu redraw logic (you can test this yourself by pressing `R` (uppercase) in the boot menu to force this). But the other issue calls for a different solution, making this one unnecessary.

**Comment by fkroener** [comment]
I can boot and select alternative kernerls - the menu just doesn't get repainted upon updates (switched selection / timer counting down).

Pressing `R` didn't change anything here.

I might have a look these days how to install git versions of systemd.

**Comment by medhefgo** [comment]
> I might have a look these days how to install git versions of systemd.

There's no need to install it at all. You only need to build and then replace the bootloader binary on the ESP.

**Comment by bluca** [comment]
@medhefgo there was no further feedback - do you think we can close this given the revert is in?

**Comment by medhefgo** [comment]
It's most likely fixed by the revert. But it hasn't been backported yet?

**Comment by bluca** [comment]
I'll do a round of backporting soon as we tag rc1, unless someone else does it first, but we can close this as we don't need it for the backports
