### ISSUE TITLE
Directives are no longer included in the seed corpora

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#25859]
Looks like they were automated away in https://github.com/systemd/systemd/pull/24958.

**Comment by Werkov** [comment]
Thanks for providing some context in [the comment](https://github.com/systemd/systemd/pull/24958#issuecomment-1364490075).

The files with lists of (empty) directives were supposed to be replaced with same files generated with empty directives too and these files should be [fed to the same programs](https://github.com/systemd/systemd/pull/24958/commits/7e343b530e68c55f868a4a8261824ca543319a52#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4L4151).

Could you please add more information what was removed with the PR #24958? Or where should the (empty) directives corpus be put into?

**Comment by evverx** [comment]
> Could you please add more information what was removed with the PR https://github.com/systemd/systemd/pull/24958? Or where should the (empty) directives corpus be put into?

The OSS-Fuzz build script puts `test/fuzz/fuzz-*` in the seed corpora in
https://github.com/systemd/systemd/blob/4f06325ce97a072be84130c6ca8d29c52dcf9d0d/tools/oss-fuzz.sh#L97-L101

I have to admit I haven't figured out why the empty directives no longer end up there yet. It could be that that's because builds are reduced to just
```
meson build
ninja -C build fuzzers
```
