### ISSUE TITLE
Clarify `systemctl edit` override message

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#25856]
### systemd version the issue has been seen with

systemd 252.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.1.1-arch1-1

### CPU architectures issue was seen on

aarch64

### Component

systemctl

### Expected behaviour you didn't see

The `.#override...` file should state, when not using `systemctl edit --force` where this is actually true, that (roughly):

"Any changed options between here and the comment below will change those options in the resulting file"

### Unexpected behaviour you saw

The `.#override...` file created by `systemctl edit` states:

"Anything between here and the comment below will become the new contents of the file" as well as "Lines below this comment will be discarded".

I read this to mean that any options I don't specify in the override will be missing in the resulting unit, but this isn't the case, and instead you only need to specify the options you want to change.

### Steps to reproduce the problem

Run `systemctl edit` on any unit and see the default override message.

**Comment by YHNdnzj** [comment]
> "Any changed options between here and the comment below will change those options in the resulting file"

`change` might not be so accurate either. E.g. for dependency-related settings like `After=`, what's specified in drop-in files will be appended to the original one, rather than overriding.

Maybe something like "Anything between here and the comment below will become part of the contents of the file"?
