### ISSUE TITLE
systemd-boot: Setting console-mode in loader.conf doesn't change screen resolution

### ISSUE THREAD

**Issue by casswarry0** [systemd/systemd#25867]
### systemd version the issue has been seen with

systemd-252.2-2-x86_64

### Used distribution

Arch

### Linux kernel version used

6.1.1-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

Any setting of console-mode in loader.conf doesn't change screen resolution. Before update to systemd 252 the setting console-mode 3 switched to native 1920 x 1080 resolution of my Asus Zephyrus G14 notebook.

### Unexpected behaviour you saw

Display resolution too small before loading linux kernel and display resolution correctly set by KMS. The setting of console-mode has no influence on the display resolution while systemd-boot lists the available boot options.

### Steps to reproduce the problem

Change setting of console-mode and observe the display resolution while booting.

**Comment by medhefgo** [comment]
It's possible that it is overridden by a efivar. Pressing `p` in the menu will tell you. You can reset it with `R` and/or select a mode with `r`.

If neither of that helps, you're probably a victim of https://github.com/systemd/systemd/pull/25848, in that case, please give the PR a try.

**Comment by casswarry0** [comment]
Thank you for your quick reply @medhefgo I reset the mode like you suggested and it worked.
