### ISSUE TITLE
Airplane mode on HP Spectre x360 2-in-1 16 inches

### ISSUE THREAD

**Issue by Hannoskaj** [systemd/systemd#25861]
As with many similar HP models (from the look of /usr/lib/udev/hwdb.d/60-keyboard.hwdb ); this one will toggle airplane mode when going into tablet mode, and off.

I solved the issue for mine with the line in /etc/udev/hwdb.d/91-my-airplane.hwdb
```
# Spectre x360 16 2022 (Prevents random airplane mode activation)
evdev:name:Intel HID events:dmi:bvn*:bvr*:bd*:svnHP*:pn*HP[sS][pP][eE][cC][tT][rR][eE]*x3602-in-1*:*
 KEYBOARD_KEY_08=unknown
```

I suggest to add this; or a variation, to /usr/lib/udev/hwdb.d/60-keyboard.hwdb .

For reference, I am adding 
* /sys/class/dmi/id/modalias;
* the output of "evtest /dev/input/event17" when toggling between tablet and desktop mode;
*  the current output of  "udevadm info -a /dev/input/event17". 

Feel free to ask for any other relevant information.
[output_of__evtest_dev_input_event17.txt](https://github.com/systemd/systemd/files/10300044/output_of__evtest_dev_input_event17.txt)

[output_of__udevadm_info_-a_dev_input_event17.txt](https://github.com/systemd/systemd/files/10300039/output_of__udevadm_info_-a_dev_input_event17.txt)
[sys_class_dmi_id_modalias.txt](https://github.com/systemd/systemd/files/10300032/sys_class_dmi_id_modalias.txt)

**Comment by yuwata** [comment]
The suggested change looks good to me. Could you submit the change as a PR?
When submitting the change, please move the comment `(Prevents random airplane mode activation)` to the line `KEYBOARD_KEY_08=unknown`. As, other keys may be added in a future. (I know other similar entry already exists, and you just follow that. But please.)
