### ISSUE TITLE
Missing dependency/assertion for DynamicUser - unit started with partial settings

### ISSUE THREAD

**Issue by pajod** [systemd/systemd#25863]
### systemd version the issue has been seen with

251.4-1ubuntu7

### Used distribution

Ubuntu 22.10

### Linux kernel version used

5.19.0-26-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-userdb

### Expected behaviour you didn't see

Reliable User= application, also for the DynamicUser=true case, so far only guaranteed in #14565 for DynamicUser=false:
> If the user does not exist by then program invocation will fail.
```
# systemd-run -G -p DynamicUser=true -p User=dynamicuser -P strace whoami 2>&1 >/dev/null | grep -i user
Failed to start transient service unit: Failure to setup DynamicUser=true: Assertion foo=bar failed in systemd-userdb

# systemd-run -G -p DynamicUser=true -p User=dynamicuser -P strace whoami 2>&1 >/dev/null | grep -i user
connect(4, {sa_family=AF_UNIX, sun_path="/run/systemd/userdb/io.systemd.DynamicUser"}, 45) = 0
write(1, "dynamicuser\n", 12) = 12
```

### Unexpected behaviour you saw

The unit appears to start successfully, then crashes depending on application behaviour.
```
# systemd-run -G -p DynamicUser=true -p User=dynamicuser -P strace whoami 2>&1 >/dev/null | grep -i user
connect(4, {sa_family=AF_UNIX, sun_path="/run/systemd/userdb/io.systemd.DynamicUser"}, 45) = -1 ECONNREFUSED (Connection Refused)
write(2, "cannot find name for user ID 62867", 34) = 34
```
(underlying trigger: ECONNREFUSED - is from a separate bug I so far failed to reproduce on v251+, starting after dependency failures of services with `User=prefix-%i`, could be worked around via `systemctl daemon-reexec`)

### Steps to reproduce the problem

The system condition in which a unit is started with broken environment can be *mimicked* by simply temporarily renaming the socket. That way is becomes clear that systemd just assumed the socket *must* be there, without actually ordering the unit startup after whatever other step (or assertion) would create it (or verify that it is there).
e.g. `mv /run/systemd/userdb/io.systemd.DynamicUser{,.deliberately-renamed-to-break-userdb}`
Then start a service that tries to lookup its dynamic User=name.

**Comment by poettering** [comment]
> Temporarily rename the socket which systemd assumes is available without telling the dependency system.
> e.g. `mv /run/systemd/userdb/io.systemd.DynamicUser{,.deliberately-renamed-to-break-userdb}`
> Then start a service that tries to lookup its dynamic User=name.

I am sorry, what?

that's a socket that pid1 creates and makes its users available on, and you move that away and are surprised things fail then?

I am not sure I follow what you are trying to describe here? 

userdbd is not necessary for making things work btw. it primarily operates as multiplexer for lookups, but if you don#t have it, clients will do the same logic client-side. Which lacks the sandboxing, but should generally give the same results.

Anyway, I am not grokking what you are getting at: the socket you are moving away is necessary for lookups of the dynamic user logic to work. hence: don't move it away

**Comment by poettering** [comment]
PID 1 binds that socket during it's early initialization. hence I think it's absolutely fine for PID 1 to assume that socket exists. If it is removed by the user manually, then that voids the warranty, and I am not sure we need a special failure mode for that.

hence, closing

**Comment by enr0n** [comment]
No, I never figured out why the socket wasn't created (or went away) across upgrades. That was across upgrades from 249 to 255.
