### ISSUE TITLE
Dependency failed for cryptsetup.target (Can't boot after Fedora 36 upgrade)

### ISSUE THREAD

**Issue by gmipf** [systemd/systemd#25874]
### systemd version the issue has been seen with

systemd-250.8-1.fc36.x86_64

### Used distribution

Fedora 36 KDE Spin

### Linux kernel version used

5.17.11-200.fc35.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Unexpected behaviour you saw

After upgrading from Fedora 35 to Fedora 36 my drives can't be decrypted any more at boot. My only entry point remains the old Kernel before the upgrade from F35. Already upgraded several times the system. Every new kernel upgrade gave the same error. Above entered Kernel version is my entry point. Doing a `dracut --regenerate-all -f && grub2-mkconfig -o /boot/grub2/grub.cfg` will also break my only entry point remained. Further testing such as the dracut command was done on a backup within Qemu.

### Steps to reproduce the problem

Can't reproduce on my specific system, haven't done any backups before the upgrade.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://imgur.com/a/DkyA7wq
```

**Comment by poettering** [comment]
you are using "serpent" as a cipher? that's not the default choice.

This really smells as if is some issue between your initrd, cryptsetup and kernel crypto api.

i.e. some kernel module missing in the initrd that is required if you make non-default cipher choices, such as serpent.

I am pretty sure this has nothing to do with systemd.

Please ask your distro for help first, and if they are sufficiently sure that systemd is at fault, they'l escalate this back to us. But frankly, this is almost certainly between fedora, dracut, cryptsetup and the kernel, not systemd. Hence closing for now.

**Comment by gmipf** [comment]
@poettering Yes I'm using serpent. How did you knew? Could you at least tell me if serpent support was removed from the Fedora 36? And whether if its possible for me to add that crypto back to the kernel? I already asked about my problem here: https://ask.fedoraproject.org/t/after-upgrading-to-fedora-36-the-kernel-cant-decrypt-my-system-at-boot/23111/2

Wasn't very helpful.

**Comment by wowpetr** [comment]
@gmipf , https://fedoraproject.org/wiki/Building_a_custom_kernel
If it's only a matter of mission kernel option enabled, generally you need to run `make menuconfig` from kernel directory and enable serpent in cryptography section (can be found using search in ncurses kernel menu) then rebuild and install you custom kernel.

**Comment by poettering** [comment]
```console
$ grep SERPENT /lib/modules/`uname -r`/config
CONFIG_CRYPTO_SERPENT=m
CONFIG_CRYPTO_SERPENT_SSE2_X86_64=m
CONFIG_CRYPTO_SERPENT_AVX_X86_64=m
CONFIG_CRYPTO_SERPENT_AVX2_X86_64=m
```

(the output above is from f36)

So that suggests serpents is built as a kmod. My guess is that that kmod might be missing in your initrd though.

**Comment by poettering** [comment]
> How did you knew?

the screenshot says so, literally

**Comment by gmipf** [comment]
OK I have found the problem. I should had mention that I also use the hashing algorithm whirlpool. I have done a clean Fedora 36 install with default encryption and after that changed only the keyslot via `cryptsetup luksConvertKey --pbkdf argon2id --hash whirlpool /dev/vda3` and it caused the same exact problem again. 

Also tried reencryption to serpent without changing the default hashing method:
```
cryptsetup reencrypt --cipher serpent-xts-plain64 --key-size 512 --use-random /dev/vda3
cryptsetup luksConvertKey --pbkdf argon2id --cipher serpent-xts-plain64 /dev/vda3
```

And everything was fine again. Sorry for the inconvenience. Any suggestions what I can do without changing the hashing method now? Is there any place where I can also check whether whirlpool support is given? In /proc/crypto it isn't listed.

**Comment by wowpetr** [comment]
@gmipf whirlpool is also need to be enabled in kernel or the corresponding modules has to be loaded
Check for CONFIG_CRYPTO_WP512 https://cateee.net/lkddb/web-lkddb/CRYPTO_WP512.html and the wp512 module if it's loaded by typing lsmod.

**Comment by gmipf** [comment]
I think I found the main cause of the problem. It is related to OpenSSL v3. OSSL has deprecated many hashing methods including ripemd160 and whirlpool. Fedora 35 was still using OpenSSL v1.1.1. Here are reports related to the problem: 

https://bugs.launchpad.net/ubuntu/+source/cryptsetup/+bug/1979159
https://bugs.archlinux.org/task/76440

OpenSSL 3 moved deprecated algorithms to the legacy.so library. The fix is to hook that library to the initramfs according to the comment sections. ArchLinux and Ubuntu has already fixed that problem but Fedora didn't. Therefore I have tried to add that file to dracut by adding following line to the dracut.conf: `libdirs+=" /usr/lib64/ossl-modules/legacy.so "`
After `dracut --force` and confirming with `lsinitrd` if that library was added to initramfs. Also tried adding kernel modules to dracut (`force_drivers+=" wp512 "`). Still didn't fix the problem. cryptsetup beginning with the version 2.5.0 also seems to fix something related to legacy stuff but upgrading cryptsetup didn't helped either. In Ubuntu updating cryptsetup seems to help. Interestingly after further testing Fedora 38 seems to support booting off ripemd160 drives again but still not whirlpool, F36 and F37 doesn't support either of them. F38 is a pre-release version and maybe they remove that in final.

**Comment by gmipf** [comment]
So I have found the solution now. To hook the legacy library to dracut we need to edit the following file:
`/usr/lib/dracut/modules.d/90crypt/module-setup.sh`

And add the following below `install() {`

```
# Install required legacy libraries.
_arch=${DRACUT_ARCH:-$(uname -m)}
inst_libdir_file \
      {"tls/$_arch/",tls/,"$_arch/",}"/ossl-modules/fips.so" \
      {"tls/$_arch/",tls/,"$_arch/",}"/ossl-modules/legacy.so"
```

After that just upgrade to the latest kernel or reinstall your latest kernel but avoid `dracut --regenerate-all` since it can maybe still brake your only entry point, just to be sure.

Source: https://github.com/dracutdevs/dracut/issues/2137#issuecomment-1364940355
