### ISSUE TITLE
homed: password is requested two times during login

### ISSUE THREAD

**Issue by schaarsc** [systemd/systemd#25877]
### systemd version the issue has been seen with

251

### CPU architectures issue was seen on

None

### Component

systemd-homed

### Expected behaviour you didn't see

```
su - testUser
Password:
```

### Unexpected behaviour you saw

```
su - testUser
Passwort:
Password:
```

### Steps to reproduce the problem

```
sudo homectl create  --disk-size=512M   testUser
su - testUser
```

if a token is also configured the password is only requested once
`sudo homectl update testUser --fido2-device=auto --fido2-with-client-pin=no --fido2-with-user-presence=no`

**Comment by poettering** [comment]
smells like a PAM misconfiguration. i.e. which distro is this? does it use a pam fragment for "su" that matches pam_systemd_home man page?

**Comment by schaarsc** [comment]
re-tested  with v252 and cannot reproduce
