### ISSUE TITLE
--output-fields  doesn't work correctly

### ISSUE THREAD

**Issue by niron1** [systemd/systemd#25887]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

5.10.0-20-cloud-amd64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

I was expecting to be able to see journalctl messages with only timestamp,unit, message, but I got hostname and process id as well:

````
journalctl  --output-fields=SYSLOG_TIMESTAMP,UNIT,MESSAGE  -u kestrel-dotnetruntime.service

Dec 29 13:41:04  dotnet-shos: WHERE a.order_id = @__orderId_0
Dec 29 13:41:04  dotnet-shos: ORDER BY a.activation_id DESC

````

### Unexpected behaviour you saw

````
journalctl  --output-fields=SYSLOG_TIMESTAMP,UNIT,MESSAGE  -u kestrel-dotnetruntime.service

Dec 29 13:41:04 ip-172-26-3-142 dotnet-shos[522]: WHERE a.order_id = @__orderId_0
Dec 29 13:41:04 ip-172-26-3-142 dotnet-shos[522]: ORDER BY a.activation_id DESC

````

### Steps to reproduce the problem

run journalctl the way I ran it

**Comment by poettering** [comment]
Please consult the man page:

```
       --output-fields=
           A comma separated list of the fields which should be included in
           the output. This has an effect only for the output modes which
           would normally show all fields (verbose, export, json, json-pretty,
           json-sse and json-seq), as well as on cat. For the former, the
           "__CURSOR", "__REALTIME_TIMESTAMP", "__MONOTONIC_TIMESTAMP", and
           "_BOOT_ID" fields are always printed.
```

the command lines you pasted do not use --output= to select the output mode, hence the whole option of course is without effect.

**Comment by niron1** [comment]
it doesn't work as "man" describes it - "A comma separated list" 
in neither of the modes mentioned: "verbose, export, json, json-pretty,  json-sse and json-seq,  cat." you wouldn't be getting a comma separated list.

**Comment by poettering** [comment]
```
journalctl --output-fields=MESSAGE,SYSLOG_TIMESTAMP,_SYSTEMD_UNIT -o verbose
```

this works perfectly.

**Comment by niron1** [comment]
on which build? here's what I got from that command:

````
Wed 2022-12-14 14:01:07.295262 UTC [s=33676f6efc244c858c863bf9ee3a2330;i=e;b=b4c1f99fcfbf44f8b7d65185158ff241;m=5d41ef;t=5efca2afe501e;x=166fff30797578a0]
    MESSAGE=printk: bootconsole [earlyser0] enabled
Wed 2022-12-14 14:01:07.295290 UTC [s=33676f6efc244c858c863bf9ee3a2330;i=f;b=b4c1f99fcfbf44f8b7d65185158ff241;m=5d420a;t=5efca2afe503a;x=f79d112d04186ddb]
    MESSAGE=NX (Execute Disable) protection: active
Wed 2022-12-14 14:01:07.295307 UTC [s=33676f6efc244c858c863bf9ee3a2330;i=10;b=b4c1f99fcfbf44f8b7d65185158ff241;m=5d421b;t=5efca2afe504b;x=7affaa444c8965e7]
    MESSAGE=SMBIOS 2.7 present.
````
problems: 
1. entries are not separated by commas
2. there are unrequested new line between fields
3. there is a "MESSAGE=" prefix prior to the message (in CSV there shouldn't be)

**Comment by niron1** [comment]
my bad. I guess the feature indeed is working as designed. 
it doesn't have the ability to customize fields in a way that's simple and similar to the default formatting
