### ISSUE TITLE
bootctl list default/next-boot kernel in json output

### ISSUE THREAD

**Issue by kwizart** [systemd/systemd#25889]
### Component

bootctl, systemd-boot

### Is your feature request related to a problem? Please describe

There is a need to properly determine what is the next-boot/default kernel uname -r from bootctl list.

Currently, bootctl list show several entries that need to be manually parsed in order to discover what is the next boot (default) expected kernel uname -r.

This is particularly needed by the akmods framework that targets recompilation of out of tree kernel modules on a local end-user system. In this context the framework can easily know the current kernel (using uname -r) and recompile the external kernel modules at system runtime, and before the end-users reboot. 
But we need to know what is the targeted next-boot kernel in order to recompile the kernel modules before booting to the kernel.

### Describe the solution you'd like

sudo bootctl list --default would be a mean to properly select the default entry, but then I will need to parse the right field from this output.
I only really need the uname -r format: (6.0.15-200.fc36.x86_64 in my distro).

### Describe alternatives you've considered

Previously, using grubby was providing the right information easily without (much) parsing:
```
sudo grubby --default-kernel
/boot/vmlinuz-6.0.15-200.fc36.x86_64
```

Note that the current way I have parsed the bootctl list output is with:
```
LANG=C bootctl list | grep -A 1 default | awk '/id/ {print $2}' | cut -f 2,3 -d "-"
```
But it looks very fragile. And I can make some wrong assumptions.

### The systemd version you checked that didn't have the feature you are asking for

current 250.8

**Comment by bluca** [comment]
There's json output, but it doesn't mark the default/next entry, it probably should
