### ISSUE TITLE
Let `systemd-cat` set `JOURNAL_STREAM` in exec'uted processes

### ISSUE THREAD

**Issue by farblos** [systemd/systemd#25880]
### Component

systemd

### Is your feature request related to a problem? Please describe

I would like to re-exec a shell script to redirect its STDOUT and STDERR to the journal, along the following lines:

```
if test -z "${XYZ_RECURSIVELY_CALLED-}"; then
  export XYZ_RECURSIVELY_CALLED=1
  exec systemd-cat --level-prefix=0 --identifier xzy "$0" "$0"
fi
```

When I learned about `$JOURNAL_STREAM` I thought I could do away with the extra env var and redo above along the lines of

```
# do not use /dev/stdout in $( ... ) below - it points to the wrong STDOUT
if test "$( stat -c '%d:%i' -L "/proc/$$/fd/1" )" != "${JOURNAL_STREAM-}"; then
  exec systemd-cat --level-prefix=0 --identifier xzy "$0" "$0"
fi
```

but unfortunately `systemd-cat` does not export the newly assigned stream to the environment of the executed process.

### Describe the solution you'd like

When `systemd-cat` is called to execute a process, set `JOURNAL_STREAM` in the new process' environment to the correct journal stream.

### Describe alternatives you've considered

See above.

### The systemd version you checked that didn't have the feature you are asking for

252

### Update:

Fixed the restart snippet to not refer to `/dev/stdout`.

**Comment by poettering** [comment]
makes sense.
