### ISSUE TITLE
systemd-resolved: Failed to send hostname reply: Transport endpoint is not connected

### ISSUE THREAD

**Issue by Zesko** [systemd/systemd#25892]
### systemd version the issue has been seen with

252.4

### Used distribution

Manjaro or Arch Linux

### Linux kernel version used

6.1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I followed Arch Wiki: [Auto sync hardware clock time in BIOS once per boot](https://wiki.archlinux.org/title/Network_Time_Protocol_daemon#Synchronize_time_once_per_boot)

My BIOS shows incorrect hardware clock time, so I need to enable `ntpdate.service` to automatically sync the time in the hardware BIOS .
1. Use `systemd-resolvconf` instead of `openresolv`.
```
$ ls -al | grep /etc/resolv
resolv.conf -> /run/systemd/resolve/stub-resolv.conf
```
That works well with any browsers using internet without any issue.

2. Install `ntp` package in any Arch based distros.
2. Enable `systemctl enable --now ntpdate.service`
2.  I got the error message from journalctl:
```
systemd-resolved[1139]: Failed to send hostname reply: Transport endpoint is not connected
```
The systemd service `ntpdate.service` uses the command line `ntpd -q -n -g -u ntp:ntp`

5. I tried to run this command line manually:
```
$ sudo ntpd -q -n -g -u ntp:ntp
```
Journalctl shows the same error message:
```
systemd-resolved[29469]: Failed to send hostname reply: Transport endpoint is not connected
```

I'm not sure what problem is related to this?

Can you please try to run ` sudo ntpd -q -n -g -u ntp:ntp` with systemd-resolve if the problem can be reproduced?

**Comment by Zesko** [comment]
I am not sure, if this issue is related to IPv6? #23406

Running ` sudo ntpd -q -n -g -u ntp:ntp`  listens on IPv4 and IPv6 in the log in any terminal .

**Comment by Zesko** [comment]
> I am not sure, if this issue is related to IPv6?

I do not think it, Running `sudo ntpd -4 -n -g -u ntp:ntp` without IPv6 still  appears the same error message. 

I would uninstall `ntp` and use `hwclock -w` .

**Comment by poettering** [comment]
> systemd-resolved[1139]: Failed to send hostname reply: Transport endpoint is not connected

This doesn't mean much, it just says: a local client asked for a hostname resolution, but then didn't actually wait for the answer. Which is fine, it might not need the reply anymore.

We should really downgrade the issue.
