### ISSUE TITLE
timedatectl gets back to January 2022 after 2022/12/31

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#25897]
### systemd version the issue has been seen with

251.8-586.fc37

### Used distribution

Fedora 37

### Linux kernel version used

6.0.12-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

timedatectl

### Expected behaviour you didn't see

Time and date didn't continue from 00:00:00 2023/01/01

### Past 23:59 on 2022/12/31, the date gets stuck in 2022 and sets itself to 2022/01/31

**Video of `timedatectl` in action: [utc.webm](https://user-images.githubusercontent.com/52470625/210158544-ec8bee02-2f5e-470d-a74d-bc24a078ff51.webm)**
As you can see the RTC time achieves 2023/01/01 00:00:00 successfully, but one second later becomes 2022/01/31 along with local time and universal time. The same behaviour occurs wether you are using your RTC time in local time zone or not.

Tested on local timezone (UTC-5) and UTC timezone. My report is in `251.8-586.fc37` and kernel `6.0.12-300.fc37.x86_64`, but I also tested on  `251.10-588.fc37` with kernel `6.0.8-300.fc37.x86_64` and the behaviour was the same. However didn't happen on `247.3-7+deb11u1` with kernel `5.10.0-18-686-pae`.

### Steps to reproduce the problem

1. NTP time disabled.
2. Set the date to 2022/12/31 and date to 23:59.
3. Oversee the date on `timedatectl` or on a GUI.

Or 
> sudo timedatectl set-ntp false && sudo timedatectl set-time "2022-12-31 23:59:56" && watch -n1 timedatectl

**Comment by TriMoon** [comment]
So it only increments the month from 12 to 1? :rofl:

**Comment by poettering** [comment]
timedatectl is not involved with the clock beyond setting it at the moment you ask it to. if the clock doesn't progress sanely after that timedatectl is not involved anymore. It's a command that runs briefly and then never again.

Anything intereszing in the logs when this happens? do you have chrony or so installed?

I seriously doubt this has anything to do with systemd.
