### ISSUE TITLE
add check to configure to suggest installing meson build system

### ISSUE THREAD

**Issue by jonnygrant** [systemd/systemd#25905]
### Is your feature request related to a problem? Please describe

$ ./configure
+ exec meson build
./configure: line 24: exec: meson: not found

### Describe the solution you'd like

Latest repo 1 Jan 2023.

Could the configure script add check to configure to suggest installing meson build system?

At the moment I see an error.

### The systemd version you checked that didn't have the feature you are asking for

Latest git clone

**Comment by poettering** [comment]
isn't that error string pretty clear already? 

"meson: not found" couldn't be any clearer, could it?

I mean, this is build system level software, you should be very technical if you run this script, and that means way beyond the level where you couldn't deduce that if your build fails with "meson: not found" that you might want to install meson.

Seriously, I am not convinced we should do anything about this. This does *not* have to be more user friendly.
