### ISSUE TITLE
QuickAck shall belong also to [DHCP] section to allow enable quickack

### ISSUE THREAD

**Issue by rdslw** [systemd/systemd#25906]
### systemd version the issue has been seen with

systemd 252 (252.4-2-arch)

### Used distribution

Archlinux

### Linux kernel version used

6.1.2-zen2

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Ability to add 'QuickAck=true' parameter to ALL routes being added by networkd for dhcp, the same way as Metric=X is used in [DHCP] section.

Currently you can use QuickAck= only on [Route] secions, which I consider a bug, as it does NOT allow to use quickack at all if using dhcp.

There are usually 3 routing table entries being added if using dhcp configuration, being:
default, gateway, gateway network

Currently it is impossible to tell systemd to use quickack setting in such case.

This is highly needed due to recent discovery https://withinboredom.info/blog/2022/12/29/golang-is-evil-on-shitty-networks/
and original John Nagle comments: https://news.ycombinator.com/item?id=10608356 that quickack should be enabled by default (it is not).

**Comment by yuwata** [comment]
Waiting in #26071.
