### ISSUE TITLE
Infinite loop when obtaining DHCP lease with MTU option (ye olde systemd-237)

### ISSUE THREAD

**Issue by rgov** [systemd/systemd#25934]
A device running Ubuntu 18.04.6 and systemd 237 displayed a link flapping behavior in which a network interface rapidly switched between up and down states in an infinite loop.

I isolated the issue to networkd trying to obtain a DHCP lease, when networkd processes the Interface MTU (26) option in the DHCP ACK.

On this hardware, which uses the Intel Gigabit Ethernet (`igb`) driver, setting the MTU on the link causes a brief interruption in the link state, and the `IFF_RUNNING` flag toggles off. See the implementation of [`igb_change_mtu()`](https://elixir.bootlin.com/linux/v4.9.299/source/drivers/net/ethernet/intel/igb/igb_main.c#L5431) that calls `igb_down/up/reset()`.  (This manifests as the `NO-CARRIER` status appearing in the output of `ip addr`.)

This brief interruption triggers an error condition in networkd's configuration of the interface, which causes the DHCP leasing process to go into a `STOPPED` state, and the interface configuration is reset (e.g., the MTU is set back to the default).

Then networkd attempts to configure the device again, repeating the process in an infinite loop.

I was able to break the loop by either (a) changing the DHCP server's MTU setting to match the interface's default, or (b) disabling the `UseMTU` setting on the interface.

I understand this release of systemd is nearly 5 years old at this point so the problem is likely resolved. However it would be good to know if this is the case. Unfortunately Ubuntu 18.04 is still widely used (e.g., across Nvidia Jetson devices).

<details>
<summary>Summary of log output from networkd</summary>

```
eth1: Flags change: +LOWER_UP +RUNNING
eth1: Gained carrier
eth1: Acquiring DHCPv4 lease
DHCP CLIENT (0xe616919c): STARTED on ifindex 4
DHCP CLIENT (0xe616919c): DISCOVER
DHCP CLIENT (0xe616919c): OFFER
DHCP CLIENT (0xe616919c): REQUEST (requesting)
DHCP CLIENT (0xe616919c): ACK
DHCP CLIENT (0xe616919c): lease expires in 1d 23h 59min 59s
DHCP CLIENT (0xe616919c): T2 expires in 1d 18h
DHCP CLIENT (0xe616919c): T1 expires in 1d
eth1: DHCPv4 address 192.168.13.110/24 via 192.168.13.31
eth1: Setting MTU: 1430
eth1: Flags change: -LOWER_UP
eth1: Setting MTU done.
eth1: Updating address: 192.168.13.110/24 (valid for 2d)
eth1: DHCP error: could not get routes: No data available
eth1: Flags change: -RUNNING
eth1: Lost carrier
DHCP CLIENT (0xe616919c): STOPPED
eth1: DHCP lease lost
eth1: Removing address 192.168.13.110
eth1: Setting MTU: 1500
eth1: Removing address 192.168.13.110
eth1: State is configuring, dropping config
eth1: Removing address: 192.168.13.110/24 (valid for 2d)
eth1: Setting MTU done.
eth1: Adding address: fe80::206:d5ff:fe2f:60c2/64 (valid forever)
eth1: Gained IPv6LL
eth1: Discovering IPv6 routers
eth1: Flags change: +LOWER_UP +RUNNING
```
</details>

<details>
<summary>netplan.io-generated /run/systemd/network/10-netplan-eth1.network file</summary>

```
[Match]
Name=eth1

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true
UseRoutes=false
```
</details>

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by yuwata** [comment]
Note, the issue should be already fixed in recent releases. One of the relevant commit is b732606950f8726c0280080c7d055a714c2888f5.
