### ISSUE TITLE
LogRateLimitIntervalSec & LogRateLimitBurst are disabled when StandardOutput and StandardError are used

### ISSUE THREAD

**Issue by 3mmarahm1** [systemd/systemd#25951]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-56-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

Limit logs written to the file specified by StandardOutput and StandardError options.

### Unexpected behaviour you saw

Logs are not being rate limited.

### Steps to reproduce the problem

StandardOutput=append:/var/log/test.log
StandardError=append:/var/log/test.log
LogRateLimitIntervalSec=1
LogRateLimitBurst=200

**Comment by poettering** [comment]
if you connect stdout/stderr to a file, then systemd is not involved whatsoever, but the fd is directly passed through, hence we couldn't apply ratelimiting even if we wanted.

But I think this is even expected, if you redirect stdout/stderr like this you explicitly bypass the logging framework after all.

Anyway, will prep a man page fix that makes this clearer.
