### ISSUE TITLE
Want to sd_notify the "real" MAINPID (great-grandchild of ExecStart) to systemd and then make NotifyAccess secure

### ISSUE THREAD

**Issue by jimklimov** [systemd/systemd#25963]
### Is your feature request related to a problem? Please describe

Following the situation described in #25961 I have a daemon started "indirectly" by systemd as the actual payload of a service unit. 

Being neither a direct child nor grandchild of systemd, its PID does not match notification permissions of `NotifyAccess=(main|exec)` so the lax `NotifyAccess=all` has to be used.
* https://access.redhat.com/solutions/3062191 suggests "all" is not secure
* Issue #24516 suggests `NotifyAccess=cgroup` as a safer option for such great-grand-children, but it is not available in current codebase nor in releases

While `sd_notify()` https://www.freedesktop.org/software/systemd/man/sd_notify.html supports sending `MAINPID=…` I could not confirm that it would also protect the unit from subsequent messages coming from unexpected PIDs (like in that errata).

### Describe the solution you'd like

A special message or additional keyword (e.g. `MAINPID=...\nNOTIFYACCESS=...`) to reset systemd's permissions for the unit from lax to constrained ("main", "exec" or eventually "cgroup"). This would allow services with complex start-up stack of processes, running a single daemon in the end, to benefit from reduced exposure. Note that access like `exec` may be still desirable, e.g. to spawn children that handle notifications as an independent thread to avoid blocking, etc.

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by poettering** [comment]
makes a lot of sense, i like.

**Comment by mathstuf** [comment]
Should `systemd-notify --ready --reset-access none` be possible? Currently it is a separate notification. Or is `systemd-notify --ready NOTIFYACCESS=none` already properly ordered?
