### ISSUE TITLE
NotifyAccess does not help (grand-)child processes send WATCHDOG=1 (`sd_watchdog_enabled==0`)

### ISSUE THREAD

**Issue by jimklimov** [systemd/systemd#25961]
### systemd version the issue has been seen with

245

### Used distribution

Debian 11 (in Proxmox)

### Linux kernel version used

5.15.64-1-pve

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Running a systemd service with an ExecStart pointing to a script which determines some things and eventually launches a program which further daemonizes (so not a systemd child process running as the actual service => using `NotifyAccess=all`), with `WatchdogSec=15s` and calling `sd_watchdog_enabled()` to see if it should currently post watchdog messages via `sd_notify()`, I expected `sd_watchdog_enabled()` to say that the current process is eligible to post the message.

### Unexpected behaviour you saw

Despite `NotifyAccess=all`, the `sd_watchdog_enabled()` returns 0.

Bluntly using `sd_notify()` does work to send the message in fact (note that with restrictive `NotifyAccess=(main|exec)` it is rejected by systemd, so generally NotifyAccess works there as expected).
* Issue #24516 suggests `NotifyAccess=cgroup` as a safer option for such great-grand-children, but it is not available in current codebase nor in releases

Although this was noticed with systemd 245 in Debian 11, looking at current codebase as of this writing, this problem should still be there:
* sd_watchdog_enabled() calls getpid_cached() at https://github.com/systemd/systemd/blob/7122aee5ab12376926362cbe6eeeaa3b144b9eed/src/libsystemd/sd-daemon/sd-daemon.c#L710
* getpid_cached() as of https://github.com/systemd/systemd/blob/a6e16d949cc290017c79db2d27805ad3c6ebe4a6/src/basic/process-util.c#L1049 does register some support to reset the cached value when forking, it seems. However I suppose that if the original ExecStart program (e.g. shell interpreter) is not a libsystemd client that called this method at least once, it would not register this ability.
* perhaps daemons can explicitly call `reset_cached_pid()` when started as libsystemd-integrated entities after all the init rituals and forking that they do (e.g. just before posting "READY=1"), but I only found this from code and not from docs.
* sending a notification earlier with `MAINPID=...` did not make a difference for this watchdog check, although `systemctl status` does report the actual daemon
* even for better-behaved programs, if `NotifyAccess=exec` works to allow separate "main" and "control" processes, one of those would *seemingly* not be able to post the messages (would be able and allowed in fact, but not according to this check helper)
* on related note, sd_watchdog_enabled() does not check that NOTIFY_SOCKET envvar is set/valid - shouldn't it? can notifications be posted without that?

### Steps to reproduce the problem

Use a shell script which starts a helper program (or sub-shells inside) to finally run a classically styled daemon which forks to detach from console. This Nth-level long-running program is the actual service; scaffolding before it is either dormant or even exited after its daemonization.

If that daemon calls `sd_watchdog_enabled()` it always gets `0`.

If the daemon asks for `getenv("WATCHDOG_USEC")` it gets the number, as well as for `getenv("WATCHDOG_PID")` (getting the original MAINPID I guess, not the current great-grandchild PID).

If the daemon then just calls `sd_notify()`, it can post the message (NotifyAccess setting permitting).

My example at hand is trying to marry NUT to sd_notify per https://github.com/networkupstools/nut/pull/1777 (WIP at this moment) which has a lot going on before a device driver runs :)

### Additional program output to the terminal or log subsystem illustrating the issue

* During unit start-up, `systemctl status` shows the stack of processes executed while the service is initializing (device data walked):
````
# systemctl status nut-driver@eco650
● nut-driver@eco650.service - Network UPS Tools - device driver for NUT device 'eco650'
     Loaded: loaded (/lib/systemd/system/nut-driver@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nut-driver@eco650.service.d
             └─nut-driver-enumerator-generated-checksum.conf, nut-driver-enumerator-generated.conf
     Active: activating (start) since Fri 2023-01-06 17:28:59 CET; 4s ago
   Main PID: 1638565 (sh)
      Tasks: 4 (limit: 154436)
     Memory: 1.1M
        CPU: 24ms
     CGroup: /system.slice/system-nut\x2ddriver.slice/nut-driver@eco650.service
             ├─1638565 /bin/sh -c NUTDEV="`/usr/local/ups/libexec/nut-driver-enumerator.sh --get-device-for-service eco650`" && [ -n "$NUTDEV" ] || { echo "FATAL: Could not find a NUT device section for s>
             ├─1638600 /usr/local/ups/sbin/upsdrvctl start eco650
             └─1638601 /usr/local/ups/bin/usbhid-ups -a eco650

Jan 06 17:29:04 pve nut-driver@eco650[1638601]:    4.711040        [D1] Path: UPS.PowerSummary.PercentLoad, Type: Feature, ReportID: 0x07, Offset: 0, Size: 8, Value: 26
````

* ...Then the driver forks to detach and run infinitely, and posts `READY=1\nMAINPID=...` while its stack of parents continues to exit immediately:
````
# systemctl status nut-driver@eco650
● nut-driver@eco650.service - Network UPS Tools - device driver for NUT device 'eco650'
     Loaded: loaded (/lib/systemd/system/nut-driver@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/nut-driver@eco650.service.d
             └─nut-driver-enumerator-generated-checksum.conf, nut-driver-enumerator-generated.conf
     Active: active (running) since Fri 2023-01-06 17:29:06 CET; 5s ago
   Main PID: 1652133 (usbhid-ups)
      Tasks: 1 (limit: 154436)
     Memory: 748.0K
        CPU: 34ms
     CGroup: /system.slice/system-nut\x2ddriver.slice/nut-driver@eco650.service
             └─1652133 /usr/local/ups/bin/usbhid-ups -a eco650

````

* Apparent lack of watchdog support causes lack of pings so the service is killed (screenshot from a different run, numbers do not match the above ones):
```sh
Jan 06 17:16:19 pve usbhid-ups[1212784]: [D6] upsnotify: sd_enabled_watchdog query returned: 0 (0msec remain)
Jan 06 17:16:19 pve usbhid-ups[1212784]: [D6] upsnotify: WATCHDOG_USEC=15000000
Jan 06 17:16:19 pve usbhid-ups[1212784]: [D6] upsnotify: WATCHDOG_PID=1267860
Jan 06 17:16:19 pve usbhid-ups[1212784]: [D6] upsnotify: failed to tickle the watchdog: not enabled for this unit

...
Jan 06 17:16:33 pve systemd[1]: nut-driver@eco650.service: Watchdog timeout (limit 15s)!
Jan 06 17:16:33 pve systemd[1]: nut-driver@eco650.service: Killing process 1212784 (usbhid-ups) with signal SIGABRT.
Jan 06 17:16:33 pve systemd[1]: nut-driver@eco650.service: Main process exited, code=killed, status=6/ABRT
Jan 06 17:16:58 pve systemd[1]: nut-driver@eco650.service: Failed with result 'watchdog'.
```

**Comment by poettering** [comment]
sd_watchdog_enabled() will return 1 only if the PID of the process it is called from matches what is set in $WATCHDOG_PID. This is a safety check because env vars get inherited down the process tree, and if we turn it on for a service we don#t want to get flooded by arbitrary watchdog notifications from everything down the process tree of the service. Hence via $WATCHDOG_PID we make clear from which process we want the watchdog keepalive notifications, and thus all processes which have a different PID will consider the watchdog not enabled for themselves.

Thus, in the process you fork off down the tree you need to update the WATCHDOG_PID env var point to the process' own PID.

**Comment by poettering** [comment]
or in other words: NotifyAccess= will open up notifications from any process in the cgroup, but we still will tell the processes we fork off from which one we expect them.

**Comment by jimklimov** [comment]
Makes sense, in a way. So extending locations wherever it calls `fork()` with `setenv("WATCHDOG_PID", ltoa(getpid()))` (roughly) should do it? Thanks for the speedy reply!

**Comment by poettering** [comment]
yeah, that should work, but make sure you don't end up doing that in multiple processes. it probably would be safer if each process that wants to do something like that first checks WATCHDOG_PID and validates it points to its own pid, then, unsets it, then forks, and in the child then sets the new WATCHDOG_PID. That way it is guaranteed there will never be more than one process sending the watchdog notifications.

I mean, it's not really a security problem if ultiple processes send us watchdog notifications, but it generates senseless load *and* it makes the watchdog exercise mostly pointless because if the service manager gets flooded from all kinds of processes with keep-alive messages then of course the service will always be considered alive, and never be hung, so why have the watchdog logic at all?

**Comment by jimklimov** [comment]
getenv(WATCHDOG_USEC) ends up null now, if I setenv(WATCHDOG_PID) before (in same process, after forking) :\
