### ISSUE TITLE
I get rfkill when I press Insert on my IdeaPad 5

### ISSUE THREAD

**Issue by shashurup** [systemd/systemd#25968]
### systemd version the issue has been seen with

252

### Used distribution

Archlinux

### Linux kernel version used

5.15.86-1-lts

### CPU architectures issue was seen on

x86_64

### Component

hardware database files

### Expected behaviour you didn't see

My WiFi gets blocked when I press Insert key

### Unexpected behaviour you saw

My Insert key work as Insert key, without blocking WiFi

### Steps to reproduce the problem

1. By Lenovo IdeaPad 5 14ACN6 :)
2. Press Insert key
3. Profit
4. Seriously, I believe this problem is related to my particular hardware.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Here is what I get on evtest /dev/input/event3

Event: time 1673075430.878861, -------------- SYN_REPORT ------------
Event: time 1673075435.095527, type 4 (EV_MSC), code 4 (MSC_SCAN), value 81
Event: time 1673075435.095527, type 1 (EV_KEY), code 247 (KEY_RFKILL), value 1
Event: time 1673075435.095527, -------------- SYN_REPORT ------------
Event: time 1673075435.104210, type 4 (EV_MSC), code 4 (MSC_SCAN), value 81
Event: time 1673075435.104210, type 1 (EV_RFKILL), code 247 (KEY_RFKILL), value 0

I believe this line in 60-keyboard.hwdb makes my Insert key produce rfkill keycode

# lenovo-ideapad
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*IdeaPad*:*
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pnS10-*:*
 KEYBOARD_KEY_81=rfkill                                 # does nothing in BIOS

Here is my modalias content (replaced : with \n)
dmi
bvnLENOVO
bvrGECN30WW(V1.14)
bd03/04/2022
br1.30
efr1.30
svnLENOVO
pn82L7
pvrIdeaPad5Pro14ACN6
rvnLENOVO
rnLNVNB161216
rvrNoDPK
cvnLENOVO
ct10
cvrIdeaPad5Pro14ACN6
skuLENOVO_MT_82L7_BU_idea_FM_IdeaPad5Pro14ACN6
```

**Comment by yuwata** [comment]
Please submit the hwdb entry for the device as a PR.
