### ISSUE TITLE
test-event fails with 'clock_gettime(clock_id, &ts) == 0' on exotic architectures

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#2597]
Version 229 now has a failure in `test-event` on powerpc, ppc64 (BE and LE), System/390, and some others [1]. They all fail here:

```
$ ./test-event
[...]
got quit handler on g
Assertion 'clock_gettime(clock_id, &ts) == 0' failed at src/basic/time-util.c:48, function now(). Aborting.
Aborted

```

[1] https://buildd.debian.org/status/package.php?p=systemd

**Comment by martinpitt** [comment]
Specifically, this fails on

```
   assert_se(sd_event_now(e, CLOCK_REALTIME_ALARM, &event_now) > 0);
```

in `test_sd_event_now()`, where `clock_gettime()` fails with `EINVAL`. According to the manpage this means "this clock type is not supported on this hardware". (CLOCK_REALTIME_ALARM seems to be fairly new or so, it's not even in my version of the manpage).

This came from https://github.com/systemd/systemd/commit/2c86ba5a51b29e41 -- @keszybz , should we just change these two asserts to expect `> 0` or `errno == EINVAL`?

**Comment by martinpitt** [comment]
Actually, no, this is more serious -- the `assert_se`() is already in `now()`, i. e. one gets a program crash if you call it with an unsupported clock type. This kind of assertion is really nasty, shouldn't `now()` and `now_nsec()` rather return the `-EINVAL`, and let the caller handle the error? Otherwise there's no sensible way to handle this kind of situation where the error is platform specific, and _not_ a clear bug in the code.

**Comment by martinpitt** [comment]
Quite fortunately `CLOCK_BOOTTIME_ALARM` isn't being used anywhere yet except for the test case, so this does not currently translate to a systemd crash. But it's certainly a trap.

**Comment by keszybz** [comment]
`now()` is an internal function and should not be called with any clock type that can fail.
- `sd_event_now` should be changed not to use `now` internally.
- `test_sd_event_now` should be changed to also accept ENOSYS.
- Additionally, we should make sure that tests calls `now()` with all clock types that are actually used in main code.

**Comment by martinpitt** [comment]
@keszybz , thanks for commenting, sounds good (except that the error code is really `EINVAL`, but we can certainly check for both). I can't work on this right now (travelling), but unless someone beats me to it I can prepare a PR on Monday.

**Comment by poettering** [comment]
Well, I think we should simply map CLOCK_REALTIME_ALARM to CLOCK_REALTIME when querying the clock, after all they are identical in that regard. The only difference between the two clocks is if you actually set a timer. 

If we silently make sd_event_now() work with the two _ALARM clocks, and make sd_event_add_time() fail, then everything should be good.

**Comment by poettering** [comment]
@martinpitt #2600 should have your fix. Since I don't have any of these weird machines, could you test if that fixes things for you? If so, press the green button please!

**Comment by keszybz** [comment]
Yep, looks like the best solution.

**Comment by martinpitt** [comment]
Cheers! Works fine at least on s390x where I tested this manually. But it should really apply to all the other arches too.
