### ISSUE TITLE
systemd-gpt-auto-generator man page does not mention "optionally in LUKS"

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#25972]
The man page does not mention "optionally in LUKS" like https://uapi-group.org/specifications/specs/discoverable_partitions_specification/ does, regarding swap.

**Comment by Gertalitec** [comment]
Just realized, neither do the other partition types.

**Comment by poettering** [comment]
It currently says:

> The /home/, /srv/, /var/ and /var/tmp/ partitions may be encrypted in LUKS format. In this case, a device mapper device is set up under the names /dev/mapper/home, /dev/mapper/srv, /dev/mapper/var and /dev/mapper/tmp. Note that this might create conflicts if the same partition is listed in /etc/crypttab with a different device mapper device name.
> When systemd is running in the initrd the / partition may be encrypted in LUKS format as well. In this case, a device mapper device is set up under the name /dev/mapper/root, and a sysroot.mount is set up that mounts the device under /sysroot. For more information, see bootup(7).

but you are right, it doesn't say that for swap.

**Comment by keszybz** [comment]
I'll submit a patch to mention swap-on-luks. I'm not doing other changes: the table is wide enough already and we don't want to add even more information here. The man page doesn't need to duplicate the specification in full.
