### ISSUE TITLE
`--type` should apply to `list-dependencies`

### ISSUE THREAD

**Issue by bernd-wechner** [systemd/systemd#25975]
### Component

systemctl

### Is your feature request related to a problem? Please describe

The man page says:

       -t, --type=
           The argument is a comma-separated list of unit types such as
           service and socket. When units are listed with **list-units**,
           **show**, or **status**, only units of the specified types will be
           shown. By default, units of all types are shown.

I think this:

```
$ systemctl list-dependencies | grep '.target'
default.target
● └─multi-user.target
●   ├─basic.target
●   │ ├─paths.target
●   │ ├─slices.target
●   │ ├─sockets.target
●   │ ├─sysinit.target
●   │ │ ├─cryptsetup.target
●   │ │ ├─local-fs.target
●   │ │ └─swap.target
●   │ └─timers.target
●   ├─getty.target
●   └─remote-fs.target
```

is a view that, while available as a workaround (as shared here) is so powerfully useful in conveying the idea and relationship of start-up target units for anyone choosing a `WantedBy` options for their unit that it warrants recognition inside of `systemctl` IMHO by simply extending support `--type` to that command.

Just a though, for rounding out this command a little.

### Describe the solution you'd like

`systemctl --type target list-dependencies` or `systemctl list-dependencies --type target` should produce a tree containing only `.target` units.

### Describe alternatives you've considered

`systemctl list-dependencies | grep '.target'`

Works fine, but I believe this view is so powerful and important it warrants inclusion, and moreover, the current implementation of silently (without complaint) not honouring the --type options is disorienting and confusing until the manual is read closely.

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by YHNdnzj** [comment]
Implemented in https://github.com/systemd/systemd/pull/26051.

However, it won't actually produce the same result as the `grep` example. When using `--type=` or `--state=` with `--all`, it stops recursion once it hits a non-specified type, while in your case you actually want to recurse through all the deps and get the corresponding types later.

**Comment by bernd-wechner** [comment]
Yes, indeed, that would be what I'd want. Does it make any sense not to show all the units of a given type in the dependencies list when asking for it?

**Comment by YHNdnzj** [comment]
> Yes, indeed, that would be what I'd want. Does it make any sense not to show all the units of a given type in the dependencies list when asking for it?

We'll have to determine whether they're the end nodes in the tree, which isn't trivial to do as for the current way of printing things.

And IMO I think the current implementation fits the concept better. We may need a new option for your use case 🤔

**Comment by bernd-wechner** [comment]
Interesting. I'd have thought if the test were applied only at the time the unit is printed vs. when they are collected, all would be good, but seems not so trivial. 

The C source is not so easy to read for a naive eye, alas and comprehension would take some background reading (apparent macros at play - STRV_FOREACH -  and other functions - unit_type_suffix, strv_contains, list_dependencies_print ...) so I'll have to trust you ;-)
