### ISSUE TITLE
[RFE] To extend RuntimeMaxSec= mechanism by using TimeoutStopSec= directive

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#2598]
``````
From v.229: A new service setting ```RuntimeMaxSec=``` has been added that may be used to specify a maximum runtime for a service. If the timeout is hit, the service is terminated and put into a failure state.
``````

I offer not to terminate units with immediate status `failed`, because it's normal to expect `on-success` exit code, when `RuntimeMaxSec=` is hit. It seems to be more logical to use `RuntimeMaxSec=` only together with `TimeoutStopSec=` directive.

So, if unit is still active, then systemd waits for time, defined in `TimeoutStopSec=`, and only after `TimeoutStopSec=` is hit, then mark unit as `failed`. Otherwise, if unit was stopped earlier then
`TimeoutStopSec=` is hit, mark unit as normally stopped\exited. But here we should define the default-value for `TimeoutStopSec=`. If `RuntimeMaxSec=` is defined in [Service] without `TimeoutStopSec=`, then systemd will ignore it. This mechanism looks more flexible instead of immediate marking units as `failed`.

**Comment by poettering** [comment]
See ML discussion really. RuntimeMaxSec= is the timeout applied to the main process of the service, while TimeoutStopSec= the one applied to ExecStop= and ExecStopPost=. And when the the runtime timeout hits, we'll shut down the service by proceeding with the ExecStop= commands.

Also TimeoutStopSec= defaults to 90s anyway.

Currently regardless if the RuntimeMaxSec= or TimeoutStopSec= timeout hit (or both) the service will be placed in a failed state after shutting down. I'd be willing to make timeout behaviour configurable with SuccessExitStatus= and RestartForceExitStatus=. 

Anyway, I think this bug report is a misunderstanding, closing hence. Let's continue the discussion on the ML.

**Comment by MikhailKasimov** [comment]
Ok.
