### ISSUE TITLE
Implementation of x-systemd.conditionhost

### ISSUE THREAD

**Issue by MischaBaars** [systemd/systemd#25983]
### Component

systemd, other

### Is your feature request related to a problem? Please describe

Related to mounting swap partitions of PXE booted network nodes (https://github.com/systemd/systemd/issues/25220).

### Describe the solution you'd like

An implementation of the x-systemd.conditionhost directive, that would place a ConditionHost directive in the corresponding .mount files when used as a mount option in /etc/fstab.

### The systemd version you checked that didn't have the feature you are asking for

251.10

**Comment by poettering** [comment]
hmm, does this really need to be a new mount option? this sounds awfully specific, and would probably prompt a proliferation of similar such condition checks.

You can achieve what you want without a new mount option, simply by using drop-ins. i.e.

```
mkdir -p /etc/systemd/foo.mount.d
cat > /etc/systemd/foo.mount.d/50-mycondition.conf <<EOF
[Unit]
ConditionHost=waldo
EOF
systemctl daemon-reload
```

That should deliver all you need. Sure it's a tiny bit more involved, but ultimately it's a single two-liner text file you have to drop in, that's not too bad.

Hence, closing. Hope that's OK.

**Comment by MischaBaars** [comment]
Hi Lennart,

Thank you for your help. Didn't think of using drop-ins yet. It's indeed sort of half the solution, but at least it will work.

**Comment by MischaBaars** [comment]
Lennart,

It's not only half the solution, it really breaks on mounting the server root partition and systemd-remount-fs.service which depends on either the hostname or the machine-id being set, which is not the case even when the machine id is passed as a kernel parameter. Mounting swap partitions and extra server nfs partitions seems to work.

Btw. machine-id passed as kernel parameters passed to booting clients change the server machine-id, which is sort of nifty.

For now it appears I have no choice other than to manually switch between two /etc/fstabs, one for pxe booting clients and one for booting the server itself.

**Comment by poettering** [comment]
> It's not only half the solution, it really breaks on mounting the server root partition and systemd-remount-fs.service which depends on either the hostname or the machine-id being set, which is not the case even when the machine id is passed as a kernel parameter. Mounting swap partitions and extra server nfs partitions seems to work.

if you set them via kernel cmdline switch, then they should be applied already the initrd. are they not?

maybe your initrd ships with a built-in /etc/hostname + /etc/machine-id? if so, they take precedence. remove them from your initrd

**Comment by MischaBaars** [comment]
Lennart,

Everything seems to work now more or less. Comments that were added to the ConditionHost= lines broke the directive. All comments are on separate lines now.

One thing though:

With ConditionHost=localhost, I end up with a hostname "localhost.localdomain" and I get warnings like: "was skipped because of a failed condition check [(ConditionHost=localhost)".](url)

With ConditionHost=localhost.localdomain, I end up with a hostname "localhost" and I end up with a broken system.

// **** example ****

● dev-disk-by\x2duuid-D301\x2dB776.device - KINGSTON SFYRS1000G EFI\x20System\x20Partition
    Follows: unit currently follows state of sys-devices-pci0000:00-0000:00:01.1-0000:01:00.0-nvme-nvme0-nvme0n1-nvme0n1p1.device
     Loaded: loaded
    Drop-In: /etc/systemd/system/dev-disk-by\x2duuid-D301\x2dB776.device.d
             └─dev-disk-by\x2duuid-D301\x2dB776.device.conf
     Active: active (plugged) since Thu 2023-01-12 11:59:37 CET; 1min 20s ago
      Until: Thu 2023-01-12 11:59:37 CET; 1min 20s ago
     Device: /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1

Jan 12 11:59:37 localhost systemd[1]: dev-disk-by\x2duuid-D301\x2dB776.device - KINGSTON SFYRS1000G EFI\x20System\x20Partition was skipped because of a failed condition check (ConditionHost=localhost).
