### ISSUE TITLE
Heavy traffic on the D-bus due to network d-bus calls 

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#25996]
### systemd version the issue has been seen with

251.2 +

### Linux kernel version used

5.15.50-3814f39

### CPU architectures issue was seen on

None

### Component

systemd-networkd

### Expected behaviour you didn't see

Is it expected to have to many D-bus calls very frequently?

method call time=313889.709780 sender=:1.55259 -> destination=org.freedesktop.network1 serial=2 path=/org/freedesktop/network1; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.Manager"
   string "NamespaceId"
method call time=313889.723775 sender=:1.55259 -> destination=org.freedesktop.network1 serial=3 path=/org/freedesktop/network1/link/_32; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.Link"
   string "BitRates"
method call time=313889.729320 sender=:1.55259 -> destination=org.freedesktop.network1 serial=4 path=/org/freedesktop/network1/link/_32; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.DHCPServer"
   string "Leases"

Our network file as follows
 cat /etc/systemd/network/00-bmc-usb0.network
[Match]
Name=usb0
[Network]
# static IP
Address=192.168.31.3/29

# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 5a:97:89:14:c2:95 brd ff:ff:ff:ff:ff:ff
    inet 192.168.31.3/29 brd 192.168.31.7 scope global usb0
       valid_lft forever preferred_lft forever
    inet6 fe80::5897:89ff:fe14:c295/64 scope link
       valid_lft forever preferred_lft forever

### Unexpected behaviour you saw

Too many d-bus calls on the system.
method call time=313889.709780 sender=:1.55259 -> destination=org.freedesktop.network1 serial=2 path=/org/freedesktop/network1; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.Manager"
   string "NamespaceId"
method call time=313889.723775 sender=:1.55259 -> destination=org.freedesktop.network1 serial=3 path=/org/freedesktop/network1/link/_32; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.Link"
   string "BitRates"
method call time=313889.729320 sender=:1.55259 -> destination=org.freedesktop.network1 serial=4 path=/org/freedesktop/network1/link/_32; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.network1.DHCPServer"
   string "Leases"

### Steps to reproduce the problem

dbus-monitor --system "type=method_call"

**Comment by poettering** [comment]
Check with "busctl" which client is behind `:1.55259` and you'll know who is the culprit if generating that traffic.

**Comment by poettering** [comment]
anyway, let's close as this is not really actionable, and more a support question than anything else. please follow-up on the systemd mailing list if you have further questions
