### ISSUE TITLE
Per-unit log filtering won't work with delegated units

### ISSUE THREAD

**Issue by Werkov** [systemd/systemd#26024]
### systemd version the issue has been seen with

origin/main

### Used distribution

none

### Linux kernel version used

none

### CPU architectures issue was seen on

None

### Component

systemd-journald

### Expected behaviour you didn't see

Log messages from all processes within a delegated service properly honor `LogFilterPatterns=`.

### Unexpected behaviour you saw

```
foo.service
`- deleg-cgroup
   ` PID
```
The process PID is under a delegatee's created cgroup, the code in `client_context_read_cgroup/client_context_read_log_filter_patterns` would look at `foo.service/deleg-cgroup` xattr, however, it was only (rightfully) configured on the `foo.service`.

The code should look for xattr's at the unit's level cgroup (cf. `cg_path_get_unit`).

### Steps to reproduce the problem

I noticed it while I was rebasing #24961 onto current `main`, it's theoretical but it may happen unless I've overlooked something (tm).

Cc: @qdeslandes

**Comment by poettering** [comment]
yeah, this is a bug.

**Comment by qdeslandes** [comment]
Sorry for the delay, I had an issue with the notifications in this repo. 

Regarding the issue, thanks for raising this is, and for the fix suggestion. I'll update the code and submit a PR :)
