### ISSUE TITLE
systemd-coredump truncates dumps

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#26026]
### systemd version the issue has been seen with

252

### Used distribution

openSUSE Tumbleweed 20221119

### Linux kernel version used

6.1.3

### CPU architectures issue was seen on

x86_64

### Component

coredumpctl

### Expected behaviour you didn't see

If the process size is larger than what coredump.conf allows, systemd-coredump should just not write the dump at all, similar to when RSS is larger than the `ulimit -c` value.

### Unexpected behaviour you saw

When both `ProcessSizeMax=2G` and `ExternalSizeMax=2G` are set in `/etc/systemd/coredump.conf`, systemd-coredump will truncate the dump at 2G.

### Steps to reproduce the problem

Set `ProcessSizeMax=2G` and `ExternalSizeMax=2G` in `/etc/systemd/coredump.conf`.

```
$ cat x.cpp
#include <cstdlib>
#include <cstdio>
#include <cstdlib>
#include <cstring>
int main()
{
    size_t z = 3ULL << 30;
    auto x = malloc(z);
    memset(x, 0xFF, z);
    system("ps fu");
    abort();
}

$ g++ x.cpp -g
$ ./a.out
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ej       10169 97.2 19.2 3160072 3148552 pts/0 S+   17:50   0:00  \_ ./a.out
Aborted (core dumped)

# zstd -d --rm /var/lib/systemd/coredump/core.a\\x2eout.25121.ae0ddef8aa2b41c0be6cf0e85d482248.23595.1673457266000000.zst 
/var/lib/systemd/coredump/core.a\x2eout.25121.ae0ddef8aa2b41c0be6cf0e85d482248.23595.1673457266000000.zst: 2147483648 bytes 

# gdb a.out /var/lib/systemd/coredump/core.a\\x2eout.25121.ae0ddef8aa2b41c0be6cf0e85d482248.23756.1673457363000000
...
warning: Error reading shared library list entry at 0x1a3d00746473
Failed to read a valid object file image from memory.
Core was generated by `./a.out'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f5feca957ec in ?? ()
(gdb) bt
#0  0x00007f5feca957ec in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fff05d5b560
(gdb) 
```

A dump that is not gdb-able does not have all that much value.

**Comment by Werkov** [comment]
Just a note -- kernel's `RLIMIT_CORE` does truncate unpiped coredumps too (i.e. I don't see the expected behavior similar to `rlimit -c`).

**Comment by jengelh** [comment]
Seems you are right. And it's weird.

```
$ ulimit -c 4 && ./a.out
Aborted (core dumped)
$ ulimit -c 3 && ./a.out 
Aborted
```
