### ISSUE TITLE
.serice file variables parsing bug

### ISSUE THREAD

**Issue by socketpair** [systemd/systemd#26039]
### systemd version the issue has been seen with

systemd-250.8-1.fc36.x86_64

### Used distribution

Fedora 36

### Linux kernel version used

6.0.12-200.fc36.x86_64

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

`$RUNTIME_DIRECTORY/` should expand to `/run/my-service-name/`

This one works OK:
`${RUNTIME_DIRECTORY}/`

This one also works OK:
`$RUNTIME_DIRECTORY x`

### Unexpected behaviour you saw

`$RUNTIME_DIRECTORY/` expanded to empty string.

### Steps to reproduce the problem
```
[Service]
RuntimeDirectory=ideco-ipsec-backend
RuntimeDirectoryMode=0750
RuntimeDirectoryPreserve=yes

# Note slash at the end of string
ExecStartPre=cp -a /some-dir/ $RUNTIME_DIRECTORY/
```

**Comment by vcaputo** [comment]
The behavior you're observing is consistent with the documentation @ https://github.com/systemd/systemd/blob/v252/man/systemd.service.xml#L1205

It's shell-inspired, but not identical...
