### ISSUE TITLE
Assign static ipv4 addresses without having to explicitly assign a static ipv6 address first

### ISSUE THREAD

**Issue by mtekman** [systemd/systemd#26037]
### systemd version the issue has been seen with

252.4

### Used distribution

Arch Linux

### Linux kernel version used

6.1.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Given a config file at `/etc/systemd/network/10-eno1.network` with the following contents

```
[Match]
Name=eno1

[Network]
Address=123.234.345.456/24
Gateway=123.234.345.444
DNS=1.1.1.1
```

assign an ipv4 static address, and automatically assign a ip6 address if not specified.

### Unexpected behaviour you saw

The output of `journalctl --unit=systemd-networkd`: 

```
Jan 11 15:54:36 escargot systemd[1]: Starting Network Configuration...
Jan 11 15:54:36 escargot systemd-networkd[1011]: /etc/systemd/network/10-eno1.network:5: Invalid address '123.234.345.456/255.255.255.0', ignoring assignment: Invalid argument
Jan 11 15:54:36 escargot systemd-networkd[1011]: /etc/systemd/network/10-eno1.network: Gateway= without static address configured. Enabling GatewayOnLink= option.
Jan 11 15:54:36 escargot systemd-networkd[1011]: eno1: Link UP
Jan 11 15:54:36 escargot systemd-networkd[1011]: eno1: Gained carrier
Jan 11 15:54:36 escargot systemd-networkd[1011]: lo: Link UP
Jan 11 15:54:36 escargot systemd-networkd[1011]: lo: Gained carrier
Jan 11 15:54:36 escargot systemd-networkd[1011]: eno1: Gained IPv6LL
Jan 11 15:54:36 escargot systemd-networkd[1011]: Enumeration completed
Jan 11 15:54:36 escargot systemd[1]: Started Network Configuration.
```

Systemd-networkd would not assign an ipv4 address **UNTIL** I specified an additional link-local ipv6 address.
For example, the following config works fine:

```
[Match]
Name=eno1

[Network]
Address=fe80::1234:abcd:5678:efab/64
Address=123.234.345.456/24
Gateway=123.234.345.444
DNS=1.1.1.1
```

### Steps to reproduce the problem

1. Create the contents of `/etc/systemd/network/10-eno1.network` with the config given in **first** section
2. Run `systemctl restart systemd-networkd`
3. Run `ip a` and witness unassigned ip4 address
4. Run `journalctl --unit=systemd-networkd` to witness error messages about the Address being invalid
5. Modify the contents of `/etc/systemd/network/10-eno1.network` with the config given in **second** section (with the additional link-local ipv6 address)
6. Run `systemctl restart systemd-networkd`
7. Run `ip a` and witness the properly assigned static ip4 address

**Comment by yuwata** [comment]
As the log message says, the IPv4 address is invalid. Please fix the .network file.

**Comment by mtekman** [comment]
I put in a dummy address because I did not wish to share my public IP. If one were to use a real address, the error message would still persist.

If you say this is fixed and that there is something I'm clearly overlooking, then I'm happy to keep this closed. Nonetheless, searching for "systemd-networkd Invalid address" yielded very few resources to actually understand what the problem was and how to fix it, so I hope this closed issue serves as a reachable solution for those who might need it.

Thanks
