### ISSUE TITLE
SD-PAM related memory leak

### ISSUE THREAD

**Issue by hguo3** [systemd/systemd#26046]
### systemd version the issue has been seen with

225

### Used distribution

Windriver Linux

### Linux kernel version used

kernel version 4.1.21

### CPU architectures issue was seen on

ppc64 (big endian)

### Expected behaviour you didn't see

[systemd-mem.log](https://github.com/systemd/systemd/files/10407295/systemd-mem.log)
[sd-pam.log](https://github.com/systemd/systemd/files/10407296/sd-pam.log)
I get a 8Mb  memory increase in both systemd (pid 1) and its fork (sd-pam). Refer to attached ps result.
systemd : 225
Valgrind: 3.16.1

I refer to https://github.com/systemd/systemd/issues/2187, try to use valgrind to debug systemd.
> exec /usr/bin/valgrind --leak-check=full --log-file=/valgrind.out /usr/lib/systemd/systemd

So I change it in linux kernel_init() as below.
>--      if (!try_to_run_init_process("/sbin/init") ||
>++    if (!try_to_run_init_process("/usr/bin/valgrind --leak-check=full --log-file=/valgrind.out /lib/systemd/systemd") ||`

But I get below error log during linux boot:
> [   11.653187] /usr/bin/valgrind --leak-check=full --log-file=/valgrind.out /lib/systemd/systemdsh: cannot set terminal process >group (-1): Inappropriate ioctl for device
>sh: no job control in this shell

Then I manually run it as below:
> sh-4.3# /usr/bin/valgrind /lib/systemd/systemd
>valgrind: warning (non-fatal): readlink("/proc/self/exe") failed.
>valgrind: continuing, however --trace-children=yes will not work.
>--247:0: aspacem Valgrind: FATAL: can't open /proc/self/maps
>--247:0: aspacem Exiting now.
>sh-4.3# 

I create a valgrind bug case : https://bugs.kde.org/show_bug.cgi?id=464185. But valgrind think this is systemd issue.

So could you please help check if there is anything wrong in my valgrind debug

Thanks a lot.

**Comment by yuwata** [comment]
Sorry, v225 is too old here. Please contact to your downstream.

**Comment by hguo3** [comment]
After I upgrade systemd to 244.5 and kernel version 4.9.299, I can still get below boot failure. So I cannot use valgrind to debug systemd.
>  /usr/bin/valgrind --leak-check=full --log-file=/valgrind.out /lib/systemd/systemdsh: cannot set terminal process >group (-1): >  >  >  Inappropriate ioctl for device
>  sh: no job control in this shell
Is version 244 still out of support?

**Comment by yuwata** [comment]
Unfortunately, no. Please try to reproduce the issue with v251 or v252, or the current git HEAD.

**Comment by hguo3** [comment]
Thanks!

Just want to know if there is something wrong to use valgrind to debug systemd(pid 1) in below. 
(!try_to_run_init_process("/usr/bin/valgrind --leak-check=full --log-file=/valgrind.out /lib/systemd/systemd") 

Is it possbile to get some advice from you upstream?

Thanks a lot

**Comment by poettering** [comment]
usually people just replace /sbin/init with a script that `exec`s the real init system, instead of patching the whole kernel...

you need to use "exec" really, so that systemd is invoked as PID 1, not some other pid.

and not sure if valgrind is ready to run as pid 1. I haven't run it like that in a while, and when i did i only did this inside of an nspawn container (i.e. a pid namespace, not the host).

**Comment by hguo3** [comment]
Thanks for your reply and advice.

I replace  /sbin/init with a script (as below)
`#!/bin/sh
exec /usr/bin/valgrind -d /lib/systemd/systemd`
Then I get below boot error:
---------------------------
[   11.209439] VFS: Mounted root (nfs filesystem) on device 0:20.
[   11.215558] devtmpfs: mounted
[   11.220517] Freeing unused kernel memory: 6280K (c000000004c50000 - c000000005272000)
--1:1:debuglog DebugLog system started by Stage 1, level 1 logging requested
--1:1:launcher no tool requested, defaulting to 'memcheck'
--1:1:launcher selected platform 'ppc64be-linux'
valgrind: warning (non-fatal): readlink("/proc/self/exe") failed.
valgrind: continuing, however --trace-children=yes will not work.
--1:1:launcher launching /usr/lib64/valgrind/memcheck-ppc64be-linux
valgrind: execve
 toolfile: /usr/lib64/valgrind/memcheck-ppc64be-linux
--1:1:debuglog DebugLog system started by Stage 2 (main), level 1 logging requested
--1:1:    main Welcome to Valgrind version 3.16.1 debug logging
--1:1:    main Checking current stack is plausible
--1:1:    main Checking initial stack was noted
--1:1:    main Starting the address space manager
--1:1: aspacem               minAddr = 0x0004000000 (computed)
--1:1: aspacem Reading /proc/self/maps
--1:0: aspacem Valgrind: FATAL: can't open /proc/self/maps
--1:0: aspacem Exiting now.
[   11.433567] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
----------------------------

As my understanding, seems  valgrind exit before our systemd starts. Could you please share your advice?
In https://bugs.kde.org/show_bug.cgi?id=464185, Valgrind upstream is still waiting for Systemd upstream's advice.

I can upgrade my systemd to 251 and reproduce this "valgrind systemd", then create a new bug case again. If you think it is necessary.

Thanks a lot,
Heng

**Comment by hguo3** [comment]
@vcaputo 
I can boot up with valgrind with your advice. script is below:
`mount -t proc proc /proc`
`exec /usr/bin/valgrind --leak-check=full --log-file=/valgrind.log /lib/systemd/systemd`

Thanks for your kind help.
