### ISSUE TITLE
rfe: add interactive authentication for scheduled shutdown

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#2605]
It seems that shutdown binary does not request/allow interactive authentication, and that seems to be quite useful if you want to schedule shutdown from normal user.
In addition, I believe systemctl should also have the ability to schedule shutdowns, if the shutdown binary is only a compatibility bit.

**Comment by poettering** [comment]
Well, we are reluctant to add interactive auth to the old sysv compat tools.

**Comment by webczat** [comment]
What about the second part, adding scheduled shutdowns and friends to
systemctl? I understand (I believe) why adding interactive auth to
compat tools may be a bad idea.

**Comment by poettering** [comment]
Implemented by 1433e1f998465b7acf472c73d58c14e7e2eb3f13
