### ISSUE TITLE
Automount config leads to hanging boot

### ISSUE THREAD

**Issue by derhelge** [systemd/systemd#26060]
### systemd version the issue has been seen with

systemd-251.10-588.fc37

### Used distribution

Fedora 37

### Linux kernel version used

6.0.18-300.fc37.x86_64

### CPU architectures issue was seen on

None

### Component

systemd

### Unexpected behaviour you saw

Since Fedora 37, the gdm login hangs for about two minutes after the laptop has been in idle-mode:
dmesg output:
``
CIFS: VFS: \\10.0.0.1 has not responded in 180 seconds. Reconnecting...
``

### Steps to reproduce the problem
To reproduce the issue, the cifs-folder at 10.0.0.1 must be unreachable.

If I remove the automount configuration, the login works directly. Actually i dont know if its a systemd, gdm or gnome-shell issue.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
cat /etc/systemd/system/mnt-data.automount
[Unit]
Description=Automount /mnt/data
Requires=NetworkManager.service
After=network-online.target
Wants=network-online.target
DefaultDependencies=no

[Automount]
Where=/mnt/data
TimeoutIdleSec=10min

[Install]
WantedBy=multi-user.target


cat /etc/systemd/system/mnt-datpool.mount 
[Unit]
Description=data mount

[Mount]
What=//10.0.0.1/data
Where=/mnt/data
Options=credentials=/home/user/.smbcreddata,noperm,vers=3.11,rw
Type=cifs
```

**Comment by poettering** [comment]
so, the server is not reachable in "idle mode" (for whatever that is?)

how is this a systemd problem?

**Comment by derhelge** [comment]
Sorry, i meant suspend mode.

I am not saying it is a systemd problem but it was my first (stupid) guess.
