### ISSUE TITLE
networkd: should not default to /0 as IPv6 prefix

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#26102]
### systemd version the issue has been seen with

252

### Used distribution

Debian Unstable

### Linux kernel version used

6.1.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

IPv6 default prefix should be /128

2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ba:f6:bc brd ff:ff:ff:ff:ff:ff
    inet6 2a01:238:42bc:a192:5054:ff:feba:f6bc/64 scope global deprecated dynamic mngtmpaddr noprefixroute
       valid_lft 3476sec preferred_lft 0sec
    inet6 2a01:238:42bc:a192::d1:100/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feba:f6bc/64 scope link
       valid_lft forever preferred_lft forever

### Unexpected behaviour you saw

If no prefix is given on an Address line for IPv6, the IP address is configured with a /0 prefix. The kernel then proceeds to expect the complete Internet on-link which kind of makes Internet communication impossible despite the rest of the system configuration being correct.

2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ba:f6:bc brd ff:ff:ff:ff:ff:ff
    inet6 2a01:238:42bc:a192:5054:ff:feba:f6bc/64 scope global deprecated dynamic mngtmpaddr noprefixroute
       valid_lft 3498sec preferred_lft 0sec
    inet6 2a01:238:42bc:a192::d1:100/0 scope global
       valid_lft forever preferred_lft forever

### Steps to reproduce the problem

Have a local network with a correct and working RA, add the following networkd configuration:

```
[Match]
Name=e*

[Network]
DHCP=no
IPForward=no
IPv6AcceptRA=yes
IPv6SendRA=no
DHCPv6PrefixDelegation=no

[Address]
Address=2a01:238:42bc:a192::d1:100
```

Not the missing prefix in the "Address" line, adding /64 leads to a correctly configured network.

**Comment by yuwata** [comment]
Related to #11307 and 0f707207b9fc04d45ad176930cfefc77c0068545 (v241).
The last change was done in Jan 2019. So I think we can change the default behavior.

**Comment by yuwata** [comment]
Waiting in #26105.
