### ISSUE TITLE
Support for Utimaco PKCS11 library with systemd-cryptenroll

### ISSUE THREAD

**Issue by type4ranjan** [systemd/systemd#26106]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

We are trying to do full linux disk encryption using Utimaco PKCS11 library with the help of systemd-cryptenroll.

We have done the following the steps:

1. Install and configure Utimaco HSM software
2. Generated keys and Certificate on the HSM token
3. Able to get the URL of the certificate from p11tool command
p11tool --provider /opt/utimaco/lib/libcs_pkcs11_R3.so --list-all pkcs11:model=CryptoServer;manufacturer=Utimaco%20IS%20GmbH;serial=SI003001_0000;token=LUKS 
Object 0:
        URL: pkcs11:model=CryptoServer;manufacturer=Utimaco%20IS%20GmbH;serial=SI003001_0000;token=LUKS;id=%45;object=LUKSCert;type=cert
        Type: X.509 Certificate (RSA-2048)
        Expires: Sat Feb 11 11:06:26 2023
        Label: LUKSCert
        Flags: CKA_SENSITIVE;
        ID: 45

 4. While running systemd-cryptenroll command it is not enrolling with the specified certificate URL
root@SWAP-Ubun22:/etc/pkcs11/modules# systemd-cryptenroll --pkcs11-token-uri="pkcs11:model=CryptoServer;manufacturer=Utimaco%20IS%20GmbH;serial=SI003001_0000;token=LUKS;id=%45;object=LUKSCert;type=cert" /dev/sdc1
🔐 Please enter current passphrase for disk /dev/sdc1:
root@SWAP-Ubun22:/etc/pkcs11/modules#
 

[FW Requesting commercial support if applicable for systemd-cryptenroll --pkcs11-token-uri.zip](https://github.com/systemd/systemd/files/10456807/FW.Requesting.commercial.support.if.applicable.for.systemd-cryptenroll.--pkcs11-token-uri.zip)

### Describe the solution you'd like

systemd-cryptenroll should be able to enroll the certificate present on the Utimaco HSM token.

**Comment by poettering** [comment]
my educated guess is that you need to add the pkcs11 module to a place p11kit can just find it.

but anyway, i don't know what ultimaco even is. but it might be worth pinging them about this.

Also, consider enabling SYSTEMD_LOG_LEVEL=debug env var when enrolling.

And you didn't even provide any log output indicating what might fail.

and sorry, there's no commercial support available from us.

**Comment by poettering** [comment]
oh, i understand now you are *from* ultimaco.

**Comment by type4ranjan** [comment]
Hi @poettering ,

Thanks for your response. We have tried the suggested way to get extra log.
Here is the output of logs that we are getting now after running systemd-cryptenroll command:
root@SWAP-Ubun22:~# SYSTEMD_LOG_LEVEL=debug systemd-cryptenroll --pkcs11-token-uri="pkcs11:model=CryptoServer;manufacturer=Utimaco%20IS%20GmbH;serial=SI003001_0000;token=LUKS;id=%45;object=LUKSCert;type=cert" /dev/sdc1
Allocating context for crypt device /dev/sdc1.
Trying to open and read device /dev/sdc1 with direct-io.
Initialising device-mapper backend library.
Trying to load LUKS2 crypt type from device /dev/sdc1.
Crypto backend (OpenSSL 3.0.2 15 Mar 2022 [default][legacy]) initialized in cryptsetup library version 2.4.3.
Detected kernel Linux 5.15.0-1030-azure x86_64.
Loading LUKS2 header (repair disabled).
Acquiring read lock for device /dev/sdc1.
Opening lock resource file /run/cryptsetup/L_8:33
Verifying lock handle for /dev/sdc1.
Device /dev/sdc1 READ lock taken.
Trying to read primary LUKS2 header at offset 0x0.
Opening locked device /dev/sdc1
Verifying locked device handle (bdev)
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:8a6ed53b7ffac8cb5da430f4a0311752ff1054f2d07203c8bca5e574fe47ca20 (on-disk)
Checksum:8a6ed53b7ffac8cb5da430f4a0311752ff1054f2d07203c8bca5e574fe47ca20 (in-memory)
Trying to read secondary LUKS2 header at offset 0x4000.
Reusing open ro fd on device /dev/sdc1
LUKS2 header version 2 of size 16384 bytes, checksum sha256.
Checksum:5dae212064de899fe3d1951aa25795b3ab4bada4b9d312b2be08d8459dffe43c (on-disk)
Checksum:5dae212064de899fe3d1951aa25795b3ab4bada4b9d312b2be08d8459dffe43c (in-memory)
Device size 4292870144, offset 16777216.
Device /dev/sdc1 READ lock released.
Only 2 active CPUs detected, PBKDF threads decreased from 4 to 2.
PBKDF argon2id, time_ms 2000 (iterations 0), max_memory_kb 1048576, parallel_threads 2.
🔐 Please enter current passphrase for disk /dev/sdc1: Failed to add password to kernel keyring: Invalid argument

 

Keyslot 0 priority 1 != 2 (required), skipped.
Trying to open LUKS2 keyslot 0.
Running keyslot key derivation.
Reading keyslot area [0x8000].
Acquiring read lock for device /dev/sdc1.
Opening lock resource file /run/cryptsetup/L_8:33
Verifying lock handle for /dev/sdc1.
Device /dev/sdc1 READ lock taken.
Reusing open ro fd on device /dev/sdc1
Device /dev/sdc1 READ lock released.
Verifying key from keyslot 0, digest 0.
PKCS#11 key enrollment not supported.
Releasing crypt device /dev/sdc1 context.
Releasing device-mapper backend.
Closing read only fd for /dev/sdc1.
root@SWAP-Ubun22:~#
``

**Comment by poettering** [comment]
> PKCS#11 key enrollment not supported.

Seems your distribution disables PKCS#11 support? Ping your distro about that. Or switch distro. Fedora at least enables pkcs#11 support.

**Comment by bluca** [comment]
we have enabled pkcs11 only recently in debian, as it was not dlopen-inified yet, it should percolate in ubuntu for the next version or so as well

**Comment by type4ranjan** [comment]
We have used  Ubuntu 22.04.1 LTS and the man page shows that systemd on this distro supports pkcs11 as per this link 
[](https://manpages.ubuntu.com/manpages/jammy/en/man1/systemd-cryptenroll.1.html)

**Comment by bluca** [comment]
22.04 does not support pkcs11, it will be added to 23.04, that manpage is just about general remarks and not what the distro enables.

Run `systemd-cryptenroll --version` and you'll see the list of modules that are supported or not.

**Comment by type4ranjan** [comment]
Thanks @bluca for this info.

We are now testing with Fedora 37 and we can see it has been built with support of p11kit as shown below
![image](https://user-images.githubusercontent.com/15943938/214050852-e99192b2-1776-47bd-acec-70c15d3cfcee.png)

We will upload the test results once done.
