### ISSUE TITLE
Unable to query domain names like 'pn', 'ai', and others that are 'dotless'.

### ISSUE THREAD

**Issue by Tynach** [systemd/systemd#26112]
### systemd version the issue has been seen with

249.11-0ubuntu3.6

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-57-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Being able to load web pages on domains like [pn] and [ai].

[pn]: http://pn/
[ai]: http://ai/

### Unexpected behaviour you saw

Web browsers and other software, including the `ping` utility, were unable to resolve the domain names.

It's worth noting that these are *not* local domains, but are domains on the Internet itself. I've seen some discussion about exclusively handling 'dotless' domains via LLMNR, for servers on the local network, and setting up the network differently so that `resolved` explicitly looks for them (or something like that?), but I have not seen any discussion about domains on the actual Internet itself which are dotless.

I would expect that all domain names that are on the Internet itself would be resolvable by `resolved`, but since this is *not* the case, I must assume this behavior is a bug.

### Steps to reproduce the problem

Simply try to `ping` such a domain, or click on the links I provided above and find that your web browser cannot resolve them (assuming you're using `resolved`).

To verify that these domain names work in *other* systems, try loading `http://pn/` or `http://ai/` on your phone's web browser. I'll admit that I have a phone with a rather outdated version of Android, so I cannot verify it works on newer phones, but on my aging LG V20 those domain names resolve just fine. My phone and desktop are on the same network.

**Comment by poettering** [comment]
Consider reading the docs. This is mentioned or referenced on more places in the man page then I have fingers on my hand.

Here for example:

https://www.freedesktop.org/software/systemd/man/resolved.conf.html#ResolveUnicastSingleLabel=

**Comment by Tynach** [comment]
@poettering, the document you link to explicitly states that it's for, and I quote, "where *public DNS servers are not used*."

I am using public DNS servers, and the websites in question are publicly available. The statement made later in the document, "Forwarding single-label names to servers not under your control is not standard-conformant," is demonstrably incorrect.
