### ISSUE TITLE
 systemd-vconsole-setup service starts too early if system not using early KMS

### ISSUE THREAD

**Issue by je-vv** [systemd/systemd#2612]
The system is a laptop HP eliteBook 8540w with a Nvidia graphics card:

01:00.0 VGA compatible controller: NVIDIA Corporation GT216GLM [Quadro FX 880M](rev a2) (prog-if 00 [VGA controller])
...
Kernel driver in use: nouveau
Kernel modules: nouveau

Which works great for me with the nouveau module.

The resolution the display has is 1920x1080, a high one to be able to read small fonts on the terminal. Therefore I have set "FONT=ter-v24n" under "/etc/vconsole.conf".

When using early KMS (loading nouveau on the mkinitcipio initrd image), there's no problem since the module is loaded way early for any systemd process. So "systemd-vconsole-setup" has no problem using the specified font on the terminal.

However when not using early KMS, then systemd-vconsole-setup is started before the nouveau module has been loaded, leading to the following error:

% systemctl --failed
UNIT LOAD ACTIVE SUB DESCRIPTION
● systemd-vconsole-setup.service loaded failed failed Setup Virtual Console
...

Exploring the reason:

% systemctl status systemd-vconsole-setup
● systemd-vconsole-setup.service - Setup Virtual Console
Loaded: loaded (/usr/lib/systemd/system/systemd-vconsole-setup.service; static; vendor preset: disabled)
Active: failed (Result: exit-code) since Sun 2016-02-14 10:24:04 CST; 3min 32s ago
Docs: man:systemd-vconsole-setup.service(8)
man:vconsole.conf(5)
Process: 167 ExecStart=/usr/lib/systemd/systemd-vconsole-setup (code=exited, status=1/FAILURE)
Main PID: 167 (code=exited, status=1/FAILURE)
Feb 14 10:24:18 m1 systemd-vconsole-setup[167]: putfont: KDFONTOP: Invalid argument
...

As you can see, it complains about the font. Which seems reasonable since before loading nouveau the resolution supported won't allow such big fonts.

So, systemd-vconsole-setup should be started only after graphics modules are loaded (for some systems more than one).

If no easy way to detect such event, I would suggest waiting until systemd-modules-load is done, which usually happens after udev auto detection, and better yet, that would wait until any graphics module specified in "/etc/modules-load.d" is also loaded.

Relying on ealry KMS only might not be good for all systems, specially those not using initrd, and even so, one might want to reduce the number things loaded into the initrd to the bare minimum...

Systemd version:  228
Distribution:  Arch GNU/Linux

% cat /etc/vconsole.conf
KEYMAP=la-latin1
FONT=ter-v24n

**Comment by poettering** [comment]
Well, I don't see how this could ever work: we simply don't know whether there will be another KMS driver showing up or not. Device probing is full async, hence it might appear any time, and there's no point in time where we know everything has shown up. Hence wey cannot delay vconsole accordingly.

I am pretty sure, that if somebody cares about cases like this, then he should write some daemon that watches for KMS events, and reloads the fonts each time, with a fallback logic in place if the big fonts don't work. But I am not sure that this would fit in the minimal tool we ship with systemd.

Anyway, I'll leave this open as RFE. But don't hold you breath: this isomething we are unlikely to work on in systemd, and if somebody does, it should probably live outside of systemd. 

Sorry.

**Comment by keszybz** [comment]
@je-vv in systemd 231-232 we reworked the vconsole font setup process, fixing various issues (and possibly introducing others ;( ). Can you check if it fixes your issue?

**Comment by je-vv** [comment]
Need to check on a different box, but on the laptop I'm using, with nvidia graphics, it's working.  I'll confirm with the other box (intel graphics) later.  Thx!

**Comment by je-vv** [comment]
Tried on another box with intel graphics, and it also works there, as well as with gnu/linux on a external disk, and it also worked, :-)
So it looks fixed as far as I can tell, :-)  Thanks a lot!
