### ISSUE TITLE
Is there a schema or machine-readable definition of unit keys?

### ISSUE THREAD

**Issue by mikehearn** [systemd/systemd#26148]
### Component

systemd

### Is your feature request related to a problem? Please describe

I'm making a tool that generates systemd units and lets the user customize the results. As part of this I wanted to be able to show keys in a gui, autocompletion, validation and especially to check that you're not trying to use a key that requires a newer systemd than the one you actually have.

Although `systemd-analyze` can be used to do some of this validation on a Linux host, this doesn't help with creating other tools. 

As far as I can see, the only machine-readable place where all the keys are listed is in the docbook, and the only way to find a mapping of what keys were added in what versions would be to write a program to rummage through the git history.

Is there a better way?

### Describe the solution you'd like

Some JSON, XML or whatever that lists the keys, ideally some basic types and when they were added.

**Comment by poettering** [comment]
try `systemd --dump-configuration-items`

**Comment by mikehearn** [comment]
Looks good, thanks.
