### ISSUE TITLE
systemd 229 - sequencing, race condition, and timer pass-through problems related to "restart".

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#2615]
systemd 229, on Arch, 
Three issues, but all seem to be associated with "systemctl restart ...".

This is seen with a Service Unit which configures a wired and wireless bonded interface and runs wpa_supplicant on the wireless interface, and then DHCP clients on the bond0 interface.  A systemctl stop tears-down the entire group - DHCP clients, wpa_supplicant, and bond0.

There is, in part,
ExecStartPre=-/usr/bin/ip link add bond0 type bond
and then
ExecStart=/usr/bin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant.conf -Dnl80211 -i %I -b bond0
with
BindsTo=sys-subsystem-net-devices-%i.device
and
ExecStop=\
 /usr/bin/systemctl stop dhcp6c@bond0.service ;\
 /usr/bin/systemctl stop dhclient@bond0.service ;\
 /usr/bin/wpa_cli -i %I terminate ;\
and
ExecStopPost= /usr/bin/ip link delete bond0 type bond

The, DHCP Clients are also started in the Service Unit.  They are started on bond0, either with a Service Unit Wants or Requires - which functions properly on a start, but which fails on restart, presumably because the DHCP clients are assumed to be still running - or with a systemctl enable - which functions properly with a restart, presumably because the dependency is on the bond0 device, not the ExecStart process.  The DHCP Service Unit has, for instance,
WantedBy=sys-subsystem-net-devices-%i.device

First Problem - when there is a Wants or Requires dependency, during a restart, it seems reasonable to assume that systemd should notice if and when the Wanted or Required service unit is in a stopped state and would then start it.  It appears that systemd does not check this state during restart, where it can be seen that the wanted or required units are started on a start, but not on a restart.  This seems especially odd when the dependency is Requires.  An explicit stop followed by an explicit start works properly, but not a restart.

Second Problem - it is desirable for the defining service unit to have a BindsTo dependency upon the bond0 device being created in the ExecStartPre, as
BindsTo=sys-subsystem-net-devices-bond0.device

Again, this functions perfectly after a start, but fails during a restart.  It appears that the state of the device is checked _before_ all the ExecStartPre, ExecStart, and ExecStartPost commands are run, instead of _after_ they are run, as if changing BindsTo into Requisite.  In this case, the commands in the defining service unit create the device upon which the defining service unit depends.  A "Before=sys-subsystem-net-devices-bond0.device" does not help here.  There also appears to be a race condition here, because this restart can always fail on a slower, single processor, machine, and only sometimes fail on a faster dual processor machine.

Third problem - timer unit / service unit coupling during restart.  When using an OnActiveSec timer with RemainAfterElapse=no in front of the service unit, a DHCP client in this case, and setting the service unit to  Restart=always, and then supposing that circumstances cause the ExecStart process to fail repeatedly, _if_ the timer unit has been started directly with systemctl, and the associated service unit is subsequently stopped, the timer unit is also stopped.  That works.  However, if the timer unit is initiated through another service unit dependency - the enabled bond0 device dependency in this case - and the associated service unit is explicitly stopped with systemctl stop, _either_ from within the defining service unit or on the command line, the timer unit is _not_ stopped, and apparently restarts the associated service unit repeatedly.  Again, this problem only occurs on restart.  After a start of the defining unit, if the bond0 device is then gratuitously destroyed, the DHCP service unit will stop and the associated timer will also stop.  But if the bond0 device is lost during a restart, because of the above BindsTo problem, then the timer is not stopped.

If an After dependency defined inside the timer delayed service unit stops the unit, then the timer will also be stopped.  But that is just fortuitous, and the underlying problem is still there.

**Comment by ohsix** [comment]
the definition of [Requires](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Requires=) is much more narrow than you're implying, it literally assures all 'required' units are running before the unit that Requires them begins to start, it says nothing about restarts nor is any of that type of relationship implied.

[BindsTo](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#BindsTo=) is a completely separate thing as well, no relation to what Exec\* and friends do, if you structure it assuming that, you will have problems.

if you need units to be closely coupled like that consider [PartOf](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#PartOf=) or using your own target, but more often than not i personally see that as a design problem and a signal to start over.

there's a handy index to all of the keywords here https://www.freedesktop.org/software/systemd/man/systemd.directives.html

and an index to so many things
https://www.freedesktop.org/wiki/Software/systemd/

**Comment by thx1111** [comment]
> it says nothing about restarts nor is any of that type of relationship implied.

That may be true, and then, that would be why and how there is a problem.  Having unspecified, undefined, "mystery" behavior is very bad design practice.  It surprises me that anyone would defend such practice.

More likely would be that some assumption about state prior to restart is not being fulfilled.

Similarly with BindsTo, it makes no sense to have one kind of behavior during "start" and another kind of behavior during "restart".  Some people get a thrill out of "complex" systems with lots of special cases and exceptions.  That is fun in obfuscated programming languages, and not so fun for day to day production systems administration.

With respect to the PartOf dependency, the documentation says specifically: "Note that this is a one-way dependency — changes to this unit do not affect the listed units."  PartOf is therefor intentionally limited to "reverse" dependencies and useless for defining "forward" dependencies.

With respect to "target" units, the documentation says specifically: "Target units do not offer any additional functionality on top of the generic functionality provided by units."  I do not see what additional functionality is being implied by the suggestion of using a Target unit.

**Comment by ohsix** [comment]
well, it is specified; anyone with some preconceived notion of how it should work can carry their experience to a new thing that actually works differently

i'm not defending it or attempting to explain it away

lets work on making this an actionable issue

**Comment by ohsix** [comment]
one way is a matter of perspective, you can have a unit be PartOf a target, guess what happens when you restart the target.

if you can come by irc i think this kind of discussion or this tone of discussion might be better hashed out there

**Comment by thx1111** [comment]
> well, it is specified

"It", as I am understanding, refers to the "restart" behavior of the Requires= dependency option, where previously, the documentation was described as "it says nothing about restarts nor is any of that type of relationship implied."  Please summarize the specified "restart" behavior of the Requires= dependency option, in your understanding.

My understanding of "restart" is that it is merely a combination of a "stop" phase followed by a "start" phase.  My observation is that the "stop" phase functions identically to a "stop" command acting alone, but that the "start" phase does _not_ act identically to a "start" command acting alone.

> you can have a unit be PartOf a target, guess what happens when you restart the target.

Yes, I imagine that restarting a target unit would cause a unit with a PartOf dependency on that target unit to restart also.  I have never had reason to use "PartOf", so I have not tested it.  But then, you raise the issue of "forward" and "reverse" dependencies, which I have discussed elsewhere.  It appears to me that issues with dependencies are distinct from issues with restart behavior.

The timer unit coupling issue seems more subtle to me.  I am amazed and pleased that, for the most part, timers "just work".  I suspect that there is some underlying commonality in the three issues described that is effecting the timer unit, and that the timer unit mechanism itself is blameless.

**Comment by poettering** [comment]
Hmm, I think it's time to close this. THe unit file is full of deadlocks, i.e. uses synchronous systemctl on depending units. If this is still an issue, please bring up on systemd-devel, since this more likely incorrect usage than an actual bug. If this is a bug then it should be file as result of a discussion on the ML, not beforehand.
