### ISSUE TITLE
return from hibernate triggers timer if timer would have triggered while in hibernation

### ISSUE THREAD

**Issue by jkinum** [systemd/systemd#26166]
### systemd version the issue has been seen with

systemd-251.10-588.fc37.x86_64

### Used distribution

Fedora 37

### Linux kernel version used

6.1.5-200.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Persistent directive should apply to sleeping or hibernation time.  For example, if a timer is set to run at 2 a.m that places the system into hibernate then when the system resumes from hibernation any missed timers should not run if persistent=false.

Currently the persistent directive only applies  to actual system downtime.  There is no way to tell the timer service not to execute a missed event due to the system having been in hibernation.

### Unexpected behaviour you saw

A sleep timer that places the system into hibernation using an OnCalendar event is triggered again immediately on resume forcing the system back into hibernation even though persistent=false.  

### Steps to reproduce the problem

1.  Create a new timer to put the system into hibernate once a day using an OnCalendar event.
2.  Allow the timer to trigger.
3.  Allow enough time for the next OnCalendar event to pass
4. resume the system from hibernate

unexpected result is that the system is forced back into hibernation even if the persistent flag is set to false.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[Unit]
Description=hibernate timer

[Timer]
OnCalendar=*-*-* 02:00:00
Unit=systemd-hibernate.service
WakeSystem=true
RemainAfterElapse=true
Persistent=false

[Install]
WantedBy=timers.target
```

**Comment by JudgeGregg** [comment]
To reproduce the behaviour without having to wait for a full cycle:

1. Set up a timer at a given time e.g 18:00.
2. Manually suspend the host a few minutes before the timer elapses e.g. at 17:58.
3. Wake the host a few minutes after the timer elapsed, e.g. 18:02.

The timer will fire immediately, despite persistent=false.

Example simple service: foo.service

```
[Unit]
Description=Test timer

[Service]
Type=simple
ExecStart=echo "TEST TIMER"
```

And the corresponding timer: foo.timer

```
[Unit]
Description=Run foo every day

[Timer]
OnCalendar=Mon..Sun 18:00:00
```

**Comment by poettering** [comment]
i am pretty sure as many people would be upset if we'd miss their timer jobs if the system was briefly put to sleep. Generally, system suspend/hibernate across the system is mostly treated as a large scheduling latency, and all programs will "catch up" on what they were missing when coming back from suspend. And so does systemd.

the Persistent= option has nothing to do with suspend/hibernate btw. it has an effect on system shutdown (as in: poweroff/halt/reboot).

**Comment by bakhtiyarneyman** [comment]
I have a timer that upgrades my mostly-always-on system when I'm asleep. But if I suspend the machine overnight, the upgrades make it unresponsive during the first few minutes after the resume. It's annoying, and I wonder if a feature request for  a parameter `MaxSchedulingLatency` would be accepted.
