### ISSUE TITLE
udev: ID_MODEL is missing at the remove event

### ISSUE THREAD

**Issue by alexanderzhirov** [systemd/systemd#26171]
### systemd version the issue has been seen with

244

### Used distribution

ThinStation

### Linux kernel version used

5.15.51

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd, udevadm, udev rule files

### Expected behaviour you didn't see

Complete data about the device at the "remove" event

### Unexpected behaviour you saw

There is no information about `ID_MODEL` when disconnecting the phone by the "remove" event

### Steps to reproduce the problem

Connecting and disconnecting the device via USB, viewing data in the output of `udevadm monitor -p`

### Additional program output to the terminal or log subsystem illustrating the issue

When the phone is connected to the computer, `udev` determines variables by the "add" event. But for some reason, when the "remove" event occurs, there are no variables such as `ID_MODEL`, which makes it impossible to unify the algorithm for working with different devices. Maybe there is no support inside the kernel? Or what could it be related to? Or does the `systemd` version or its configuration play a role?

```sh
KERNEL[5440.719559] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0
SUBSYSTEM=usb
DEVTYPE=usb_interface
PRODUCT=2717/ff40/223
TYPE=0/0/0
INTERFACE=255/255/0
MODALIAS=usb:v2717pFF40d0223dc00dsc00dp00icFFiscFFip00in00
SEQNUM=2473

KERNEL[5440.720452] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=unbind
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/098
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=098
SEQNUM=2474
MAJOR=189
MINOR=97

KERNEL[5440.720665] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/098
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=098
SEQNUM=2475
MAJOR=189
MINOR=97

UDEV  [5440.914560] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0
SUBSYSTEM=usb
DEVTYPE=usb_interface
PRODUCT=2717/ff40/223
TYPE=0/0/0
INTERFACE=255/255/0
MODALIAS=usb:v2717pFF40d0223dc00dsc00dp00icFFiscFFip00in00
SEQNUM=2473
USEC_INITIALIZED=5433050990
ID_VENDOR_FROM_DATABASE=Xiaomi Inc.
ID_MODEL_FROM_DATABASE=Mi/Redmi series (MTP)
ID_PATH=pci-0000:00:14.0-usb-0:3.2:1.0
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2_1_0

KERNEL[5440.996828] add      /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/099
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=099
SEQNUM=2476
MAJOR=189
MINOR=98

KERNEL[5441.000344] add      /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0
SUBSYSTEM=usb
DEVTYPE=usb_interface
PRODUCT=2717/ff40/223
TYPE=0/0/0
INTERFACE=255/255/0
MODALIAS=usb:v2717pFF40d0223dc00dsc00dp00icFFiscFFip00in00
SEQNUM=2477

KERNEL[5441.000456] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=bind
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/099
DEVTYPE=usb_device
DRIVER=usb
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=099
SEQNUM=2478
MAJOR=189
MINOR=98

UDEV  [5441.086179] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=unbind
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/098
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=098
SEQNUM=2474
USEC_INITIALIZED=5432832949
ID_PATH=pci-0000:00:14.0-usb-0:3.2
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2
MAJOR=189
MINOR=97

UDEV  [5441.279093] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/098
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=098
SEQNUM=2475
USEC_INITIALIZED=5432832949
ID_PATH=pci-0000:00:14.0-usb-0:3.2
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2
adb_user=yes
MAJOR=189
MINOR=97
DEVLINKS=/dev/android /dev/android2
TAGS=:uaccess:

UDEV  [5441.499605] add      /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/099
DEVTYPE=usb_device
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=099
SEQNUM=2476
USEC_INITIALIZED=5441281617
ID_VENDOR=Xiaomi
ID_VENDOR_ENC=Xiaomi
ID_VENDOR_ID=2717
ID_MODEL=Redmi_9A
ID_MODEL_ENC=Redmi\x209A
ID_MODEL_ID=ff40
ID_REVISION=0223
ID_SERIAL=Xiaomi_Redmi_9A_****************
ID_SERIAL_SHORT=****************
ID_BUS=usb
ID_USB_INTERFACES=:ffff00:
ID_VENDOR_FROM_DATABASE=Xiaomi Inc.
ID_MODEL_FROM_DATABASE=Mi/Redmi series (MTP)
adb_user=yes
ID_PATH=pci-0000:00:14.0-usb-0:3.2
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2
ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_3_2
MAJOR=189
MINOR=98
DEVLINKS=/dev/android_adb /dev/android /dev/android2
TAGS=:seat:uaccess:

UDEV  [5441.716011] add      /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0
SUBSYSTEM=usb
DEVTYPE=usb_interface
PRODUCT=2717/ff40/223
TYPE=0/0/0
INTERFACE=255/255/0
MODALIAS=usb:v2717pFF40d0223dc00dsc00dp00icFFiscFFip00in00
SEQNUM=2477
USEC_INITIALIZED=5441501441
ID_VENDOR_FROM_DATABASE=Xiaomi Inc.
ID_MODEL_FROM_DATABASE=Mi/Redmi series (MTP)
ID_PATH=pci-0000:00:14.0-usb-0:3.2:1.0
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2_1_0

UDEV  [5441.891958] bind     /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2 (usb)
ACTION=bind
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2
SUBSYSTEM=usb
DEVNAME=/dev/bus/usb/001/099
DEVTYPE=usb_device
DRIVER=usb
PRODUCT=2717/ff40/223
TYPE=0/0/0
BUSNUM=001
DEVNUM=099
SEQNUM=2478
USEC_INITIALIZED=5441281617
ID_VENDOR=Xiaomi
ID_VENDOR_ENC=Xiaomi
ID_VENDOR_ID=2717
ID_MODEL=Redmi_9A
ID_MODEL_ENC=Redmi\x209A
ID_MODEL_ID=ff40
ID_REVISION=0223
ID_SERIAL=Xiaomi_Redmi_9A_****************
ID_SERIAL_SHORT=****************
ID_BUS=usb
ID_USB_INTERFACES=:ffff00:
ID_VENDOR_FROM_DATABASE=Xiaomi Inc.
ID_MODEL_FROM_DATABASE=Mi/Redmi series (MTP)
adb_user=yes
ID_PATH=pci-0000:00:14.0-usb-0:3.2
ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_2
ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_3_2
MAJOR=189
MINOR=98
DEVLINKS=/dev/android_adb /dev/android /dev/android2
TAGS=:seat:uaccess:
```

**Comment by arvidjaar** [comment]
`remove` is sent when device is not more there so it is not possible to query its attributes. As your own example shows, you get `ID_MODEL_FROM_DATABASE` - what udev knew about your device before it was removed.

**Comment by AlexanderZhirov** [comment]
> `remove` is sent when device is not more there so it is not possible to query its attributes. As your own example shows, you get `ID_MODEL_FROM_DATABASE` - what udev knew about your device before it was removed.

How then to explain this behavior on `kernel 4.14.70` and `udev 231`?

```sh
KERNEL[166.735616] add      /devices/pci0000:00/0000:00:0f.5/usb1/1-3 (usb)
ACTION=add
BUSNUM=001
DEVNAME=/dev/bus/usb/001/003
DEVNUM=003
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3
DEVTYPE=usb_device
MAJOR=189
MINOR=2
PRODUCT=5c6/1/318
SEQNUM=1436
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[166.743985] add      /devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0
DEVTYPE=usb_interface
INTERFACE=255/255/0
MODALIAS=usb:v05C6p0001d0318dc00dsc00dp00icFFiscFFip00in00
PRODUCT=5c6/1/318
SEQNUM=1437
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[166.981458] add      /devices/virtual/bdi/0:20 (bdi)
ACTION=add
DEVPATH=/devices/virtual/bdi/0:20
SEQNUM=1440
SUBSYSTEM=bdi

UDEV  [166.993620] add      /devices/virtual/bdi/0:20 (bdi)
ACTION=add
DEVPATH=/devices/virtual/bdi/0:20
SEQNUM=1440
SUBSYSTEM=bdi
USEC_INITIALIZED=166993200

UDEV  [167.015251] add      /devices/pci0000:00/0000:00:0f.5/usb1/1-3 (usb)
ACTION=add
BUSNUM=001
DEVLINKS=/dev/android /dev/android3
DEVNAME=/dev/bus/usb/001/003
DEVNUM=003
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3
DEVTYPE=usb_device
ID_BUS=usb
ID_MODEL=Swift_2_Plus
ID_MODEL_ENC=Swift\x202\x20Plus
ID_MODEL_ID=0001
ID_REVISION=0318
ID_SERIAL=Wileyfox_Swift_2_Plus_********
ID_SERIAL_SHORT=********
ID_USB_INTERFACES=:ffff00:
ID_VENDOR=Wileyfox
ID_VENDOR_ENC=Wileyfox
ID_VENDOR_ID=05c6
MAJOR=189
MINOR=2
PRODUCT=5c6/1/318
SEQNUM=1436
SUBSYSTEM=usb
TAGS=:uaccess:
TYPE=0/0/0
USEC_INITIALIZED=166749862
adb_user=yes

UDEV  [167.020189] add      /devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0
DEVTYPE=usb_interface
INTERFACE=255/255/0
MODALIAS=usb:v05C6p0001d0318dc00dsc00dp00icFFiscFFip00in00
PRODUCT=5c6/1/318
SEQNUM=1437
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=167018789

KERNEL[171.884452] remove   /devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0
DEVTYPE=usb_interface
INTERFACE=255/255/0
MODALIAS=usb:v05C6p0001d0318dc00dsc00dp00icFFiscFFip00in00
PRODUCT=5c6/1/318
SEQNUM=1442
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[171.888589] remove   /devices/pci0000:00/0000:00:0f.5/usb1/1-3 (usb)
ACTION=remove
BUSNUM=001
DEVNAME=/dev/bus/usb/001/003
DEVNUM=003
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3
DEVTYPE=usb_device
MAJOR=189
MINOR=2
PRODUCT=5c6/1/318
SEQNUM=1444
SUBSYSTEM=usb
TYPE=0/0/0

UDEV  [171.896356] remove   /devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0 (usb)
ACTION=remove
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3/1-3:1.0
DEVTYPE=usb_interface
INTERFACE=255/255/0
MODALIAS=usb:v05C6p0001d0318dc00dsc00dp00icFFiscFFip00in00
PRODUCT=5c6/1/318
SEQNUM=1442
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=171885181

KERNEL[172.067605] remove   /devices/virtual/bdi/0:20 (bdi)
ACTION=remove
DEVPATH=/devices/virtual/bdi/0:20
SEQNUM=1445
SUBSYSTEM=bdi

UDEV  [172.076637] remove   /devices/virtual/bdi/0:20 (bdi)
ACTION=remove
DEVPATH=/devices/virtual/bdi/0:20
SEQNUM=1445
SUBSYSTEM=bdi
USEC_INITIALIZED=172068525

UDEV  [172.104393] remove   /devices/pci0000:00/0000:00:0f.5/usb1/1-3 (usb)
ACTION=remove
BUSNUM=001
DEVLINKS=/dev/android /dev/android3
DEVNAME=/dev/bus/usb/001/003
DEVNUM=003
DEVPATH=/devices/pci0000:00/0000:00:0f.5/usb1/1-3
DEVTYPE=usb_device
ID_BUS=usb
ID_MODEL=Swift_2_Plus
ID_MODEL_ENC=Swift\x202\x20Plus
ID_MODEL_ID=0001
ID_REVISION=0318
ID_SERIAL=Wileyfox_Swift_2_Plus_********
ID_SERIAL_SHORT=********
ID_USB_INTERFACES=:ffff00:
ID_VENDOR=Wileyfox
ID_VENDOR_ENC=Wileyfox
ID_VENDOR_ID=05c6
MAJOR=189
MINOR=2
PRODUCT=5c6/1/318
SEQNUM=1444
SUBSYSTEM=usb
TAGS=:uaccess:
TYPE=0/0/0
USEC_INITIALIZED=166749862
adb_user=yes
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
> `remove` is sent when device is not more there so it is not possible to query its attributes. As your own example shows, you get `ID_MODEL_FROM_DATABASE` - what udev knew about your device before it was removed.

No, you don't. ID_MODE_FROM_DATABASE is set via hwdb and that is by default only pulled in by ACTION != "remove".

But yeah, devices that vanish are not around anymore hence cannot be probed, hence the ID_XYZ props are generally not set anymore.

**Comment by AlexanderZhirov** [comment]
I still don't understand how then it worked on the old kernel and the old version of udev? I didn't find any information about this in changes.

**Comment by poettering** [comment]
there are ways you can import props from earlier database entries. maybe some rule did that for you. (look for `IMPORT{db}`…)

But typically it's bad style to use that, in particular if blanket importing old props.

**Comment by AlexanderZhirov** [comment]
@poettering Thank you, I will work in this direction.

**Comment by poettering** [comment]
also, old kernels didn't generate bind/unbind events. new kernels do. they have the effect that props are flushed out via one additional event if not covered explicitly. See NEWS entry for v247

**Comment by AlexanderZhirov** [comment]
> also, old kernels didn't generate bind/unbind events. new kernels do. they have the effect that props are flushed out via one additional event if not covered explicitly. See NEWS entry for v247

Still, yes, the problem was importing the data. This method helped me to mount and unmount the device. However, I did this by bypassing the script launch directly, because `udev` refused to save the mount and immediately unmounted the device. I had to put my script in a separate service and run this service when connecting/disconnecting my device. I do not know how well I did all this, but I did not find anything useful on this topic, since `systemd-mount` does not know how to mount MTP, and I do not know how to use another utility instead of `systemd-mount`. In general, I didn't find any examples, so I did it my own way.

But now there is a problem. When booting a PC with an MTP device connected to it, the computer refuses to boot properly. It feels like at the boot stage, when scanning USB, a mount script is launched and blocks further loading.

The main topic where I opened the request is [here](https://github.com/Thinstation/thinstation/issues/760#issuecomment-1406456764).

Here's what I can share:
![boot](https://user-images.githubusercontent.com/37277056/215141772-85b2d69b-ca7a-4f35-8898-37a4aadc05f2.svg)
[kernel.log](https://github.com/systemd/systemd/files/10521001/kernel.log)

I do not know what to do in this situation. Either to redo the mounting process (which, in fact, I can't do differently, because I found only this one way), or to configure some dependencies when booting the PC (I can't figure it out)

**Comment by poettering** [comment]
@AlexanderZhirov note that udev nowadays runs in a mount namespace, hence any mounts you do from udev rules will not be visible on the host.

This is explicitly documented for the `RUN{program}` stanza, and has been that way for many years:

> Note that running programs that access the network or mount/unmount filesystems is not allowed inside of udev rules, due to the default sandbox that is enforced on systemd-udevd.service.

**Comment by poettering** [comment]
you are synchronously starting your service from an udev rule via systemctl. And you picked Type=oneshot, so that your script needs to complete before the udev rule can finish.

Use `systemctl --no-block`.

Or better: use ENV{SYSTEMD_WANTS}=

or better fix the mtp implementation to just work with regular /bin/mount.

**Comment by AlexanderZhirov** [comment]
@poettering Thank you very much for your reply!

[I finally managed to implement the mount.](https://github.com/AlexanderZhirov/mtp-automount)

> or better fix the mtp implementation to just work with regular /bin/mount.

I have to use the available tools to mount an MTP device, either [simple-mtpfs](https://github.com/phatina/simple-mtpfs) or [aft-mtp-mount](https://github.com/whoozle/android-file-transfer-linux)

I just can't figure out why `systemd` doesn't fire with the `add` [event](https://github.com/AlexanderZhirov/mtp-automount/blob/de3b4f2952788765bb0260732823440a9a94e13f/etc/udev/rules.d/51-android.patch#L29)?

I had to do it without it, only in this case the mount trigger was triggered.

Do I understand correctly that my implementation allows me to "[bind](https://github.com/AlexanderZhirov/mtp-automount/blob/de3b4f2952788765bb0260732823440a9a94e13f/etc/systemd/system/mtp%40.service#L3)" to the device and hang the event of stopping the mounting process on it? [I had to do a lot of work](https://unix.stackexchange.com/questions/733591/mount-mtp-devices-using-systemd/733677#733677) to come to this conclusion.

**Comment by poettering** [comment]
> [](https://github.com/whoozle/android-file-transfer-linux)
> 
> I just can't figure out why `systemd` doesn't fire with the `add` [event](https://github.com/AlexanderZhirov/mtp-automount/blob/de3b4f2952788765bb0260732823440a9a94e13f/etc/udev/rules.d/51-android.patch#L29)?

The events come from the kernel, not systemd or udev. And usually on usb you will get add, then bind and possibly change in between.

Note that various sysfs attributes only show up during bind or later, hence checking for them early is not going to work (or racy).

Generally: in almost all cases udev rules should use `ACTION!="remove"` rather than `ACTION=="add|change|bind"` or similar. i.e. do not try to list "positive" rules, but list the one and only "negative" one, where the device actually disappears.

**Comment by poettering** [comment]
> Do I understand correctly that my implementation allows me to "[bind](https://github.com/AlexanderZhirov/mtp-automount/blob/de3b4f2952788765bb0260732823440a9a94e13f/etc/systemd/system/mtp%40.service#L3)" to the device and hang the event of stopping the mounting process on it? [I had to do a lot of work](https://unix.stackexchange.com/questions/733591/mount-mtp-devices-using-systemd/733677#733677) to come to this conclusion.

No idea what you are trying to say.
