### ISSUE TITLE
machinectl edit

### ISSUE THREAD

**Issue by psztoch** [systemd/systemd#26246]
### Component

machinectl

### Is your feature request related to a problem? Please describe

Simply access to `/etc/systemd/nspawn/machine.nspawn` editor will be very useful.
More information in `machinectl show machine` would be useful too...

**Comment by poettering** [comment]
makes sense.

**Comment by yuwata** [comment]
(Also, I'd like to have `networkctl edit`.)

**Comment by smopucilowski** [comment]
> (Also, I'd like to have `networkctl edit`.)

In the same vein, `networkctl cat` in much the same way `systemctl cat <unit>`.
