### ISSUE TITLE
Xen Dom0 not detected

### ISSUE THREAD

**Issue by nafets227** [systemd/systemd#2625]
when running on a xen Dom0 systemd-detect-virt returns "xen" as in DomU.

consequently all units with ConditionVirtualisation=yes are started on xen Dom0.

Looking into the code src/basic/virt.c  my interpretation (did not debug) is:
detect_vm is first calling detect_vm_cpuid.
This returns VIRTUALISATION_XEN. Subsequently the special handling of Dom0 in detect_vm_xen is not executed.

running ArchLinux with Linux 4.4.1-2-ARCH and systemd 228-4

I am available to compile & test a possible fix.

**Comment by poettering** [comment]
we don't really have access to Xen machines. we kinda rely on patches to make this work.

**Comment by keszybz** [comment]
Thanks for the patch.
