### ISSUE TITLE
udevd: whether udevd can keep watch during event processing?

### ISSUE THREAD

**Issue by jiayi0118** [systemd/systemd#26250]
### Component

Whether udevd can keep watch during event processing?

### Is your feature request related to a problem? Please describe

Disabling watch during event processing may result in race problems. Although udevd leverages whole disk locking mechanism (https://github.com/systemd/systemd/blob/main/docs/BLOCK_DEVICE_LOCKING.md) to deal with race problems, it requires a lot of block device commands to implement locking functions. Thus I am wondering whether udevd can originally avoid disabling watch.

### Describe the solution you'd like

Let udevd keep watch during event processing.

### Describe alternatives you've considered

As far as I have seen, if udevd keeps watch, it may cause inotify events loop. From my opinion, this problem may be solved by some process tracking mechanisms, e.g. `fanotify`, because if udev can distinguish watch event originating from processes in rules, udev can avoid repeatedly synthesizing change uevents.

***But I am not sure whether there are other reasons that udevd decides to disable watch during event processing.***

@yuwata @poettering @keszybz 

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
> As far as I have seen, if udevd keeps watch, it may cause inotify events loop.

How so? udev installs an inotify watch for IN_CLOSE_WRITE only. And it never opens any device for write. So how would that trigger an events loop?
