### ISSUE TITLE
-O3 caused faulty sytemd | check is failing

### ISSUE THREAD

**Issue by ptr1337** [systemd/systemd#26263]
### systemd version the issue has been seen with

252.5

### Used distribution

CachyOS

### Linux kernel version used

6.2.0-rc6-1-cachyos-rc

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Check is working without problems with -O2, with -O3 it is failing.
Maybe duplicate of https://github.com/systemd/systemd/issues/26118

gcc -v

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/pkg/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --with-build-config=bootstrap-lto --enable-link-serialization=1 --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20230111 (GCC) 
```

### Unexpected behaviour you saw

Checks are failing

### Steps to reproduce the problem

asp export systemd
cd systemd
export CFLAGS="-O3"
makepkg -si

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/ptr1337/fda5647a179109ee8905af30d00d4d0a
```

**Comment by ventureoo** [comment]
Can reproduce. With -O3 there is a falling in the tests.
[Uploading testlog.txt…]()

**Comment by bluca** [comment]
duplicate of https://github.com/systemd/systemd/issues/26118

**Comment by mrc0mmand** [comment]
I'm not sure if it's exactly a duplicate of #26118, but I couldn't reproduce the issue anywhere (Fedora Rawhide, Arch Linux, CachyOS in a podman container) with any `CFLAGS` I could extract from the attached test logs.

**Comment by bluca** [comment]
yeah I tried with gcc13 from Debian with O3 and couldn't reproduce either, so I assumed it was the same issue

**Comment by ptr1337** [comment]
I can reproduce this in a arch chroot, arch docker, as well as cachyos chroot and cachyos docker.
Please compile from this PKGBUILD and enable -O3 in the makepkg.conf:
https://github.com/archlinux/svntogit-packages/blob/packages/systemd/trunk/PKGBUILD

**Comment by bluca** [comment]
That's not building from main, can you reproduce the problem in main?

**Comment by ptr1337** [comment]
> That's not building from main, can you reproduce the problem in main?

I can check if main works. I have pointed above which systemd version is affected.
252.4 was NOT affected from this.
252.5 is affected from this.

Actually using 252.5 + -O3 breaks the complete dbus implementation.

I look if main also affected, but so far is the stable release the problem.

**Comment by ptr1337** [comment]
Yes, main is also affected.
Using following PKGBUILD:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-git

Log is attached.

Used Flags:
```
CFLAGS="-march=native -O3 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,r
[testlog.txt](https://github.com/systemd/systemd/files/10568518/testlog.txt)
elro,-z,now"
LTOFLAGS="-flto=auto -falign-functions=32 -fdevirtualize-at-ltrans"
```

Using -O2 fixes the problem.

**Comment by ptr1337** [comment]
[testlog.txt](https://github.com/systemd/systemd/files/10568520/testlog.txt)

**Comment by yuwata** [comment]
Please try to bisect between v252.4..v252.5.

I guess, 7929e180aa47a2692ad4f053afac2857d7198758 (backported as 34b9eddfc12936917fab000b780a451d6277c2b4) and its follow-up 4f79f545b3c46c358666c9f5f2b384fe50aac4b4 (backported as e998c9d7c1a52ab02ff6e9c363c1cfe0b76cd6f4) may be relevant.

**Comment by bluca** [comment]
I cannot reproduce with gcc 13.0.1 in Debian with those exact build flags, are you sure this is not an issue in your toolchain? Which exact compiler versions are you using?

**Comment by bluca** [comment]
ah I see gcc 12, I'll try that too

**Comment by ptr1337** [comment]
> ah I see gcc 12, I'll try that too

gcc 12.1.1 commit eec3a65ed638a1c58fa08ddf508d2d60b64d311d

**Comment by bluca** [comment]
Cannot reproduce with gcc 12.2.0 either.

You have this:

```
 542/1092 systemd:bus / test-bus-track                                         TIMEOUT         30.07s   killed by signal 15 SIGTERM
 649/1092 systemd:fuzzers / fuzz-bus-match_bugzilla1935084.input               FAIL             0.07s   killed by signal 11 SIGSEGV
 650/1092 systemd:fuzzers / fuzz-bus-match_test.input                          FAIL             0.08s   killed by signal 11 SIGSEGV
```

All related to the bus tracking - are you sure it's not an issue with the dbus setup in whatever environment you are running into? Can you reproduce in a different environment? Also run those individually, as from the log you attached it's pretty much impossible to tell where the output is, it's way too verbose and noisy

**Comment by ptr1337** [comment]
https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

https://github.com/WhyNotHugo/docker-makepkg

Here you have two options to build in a archlinux system. It could be that the current commit is faulty, which archlinux is using as default.

**Comment by bluca** [comment]
Sorry but I don't have any time to set up corner case, special environments like that. We have our own coverage of Archlinux and those tests are working fine: https://github.com/systemd/systemd/actions/runs/4073793966/jobs/7018148826

If there's a problem related to that specific environment, I suggest to bring the issue to the maintainers of such environment. If that then results in needing some changes here, you can then open a PR and we'll review it.

**Comment by ptr1337** [comment]
> Sorry but I don't have any time to set up corner case, special environments like that. We have our own coverage of Archlinux and those tests are working fine: https://github.com/systemd/systemd/actions/runs/4073793966/jobs/7018148826
> 
> If there's a problem related to that specific environment, I suggest to bring the issue to the maintainers of such environment. If that then results in needing some changes here, you can then open a PR and we'll review it.

That is not a special environment. It is simply the default arch based environment.
Replace in your tests -O2 with -O3 and you will face this issue.

Just tested same compilation with clang 15.0.7 and the issue was not possible to reproduce.

**Comment by ptr1337** [comment]
I just gonna close here.

**Comment by NextWork123** [comment]
> Sorry but I don't have any time to set up corner case, special environments like that. We have our own coverage of Archlinux and those tests are working fine: https://github.com/systemd/systemd/actions/runs/4073793966/jobs/7018148826
> 
> If there's a problem related to that specific environment, I suggest to bring the issue to the maintainers of such environment. If that then results in needing some changes here, you can then open a PR and we'll review it.

Isn't better to use docker, instead of create an Arch QEMU session and compile that? anyway Can someone test in the default enviroment of Arch Linux? (Building in a clean chroot) isn't much difficult. I ask too if someone other can manage this issue instead of you.

Best Regards,
NextWorks

**Comment by ptr1337** [comment]
It seems like this was due a faulty gcc commit.
I just did update my toolchain against the staging branch:
https://github.com/archlinux/svntogit-packages/commit/862e20983b55ecb21e8469907fc30802c16b5eaf

And this was not reproduce able. I think that was a compiler issue then
