### ISSUE TITLE
Systemd-boot fails on UEFI systems with no secure boot at all

### ISSUE THREAD

**Issue by mirh** [systemd/systemd#2627]
First and only thing I get after booting arch image on my Asus laptop is:

```
Failed to install override security policy: (14) Not Found
```

After a quick check, I [found](http://superuser.com/questions/615142/uefi-failed-to-install-override-security-policy/#676059) it seems to be the Secure boot loader (bootx64.efi) that doesn't work when Secure boot isn't _present_ (not just disabled). 

I don't think this is about "broken EFI implementations" but just _older_ (~~short of version 2.2 I guess~~ 2.1 to be accurate). 
For the records, if I check loader.efi, it seems to be systemd 228.

**Comment by jejb** [comment]
OK, give me some debugging help.  It seems that the 

```
status = RT->GetVariable(L"SecureBoot",
             &GV_GUID, NULL, &DataSize, &SecureBoot);
```

Test actually passed on your platform.  Can you get the contents of this variable from the EFI shell?  It should be accessible with dmpstore

**Comment by mirh** [comment]
[Here you are](https://github.com/systemd/systemd/files/198593/dmpstore.txt)

**Comment by jejb** [comment]
Hmm, well it shows there's no SecureBoot variable in the actual variables.  It must be some type of override within the platform itself.  I'm afraid I've got a bad feeling because it looks like it's some hack put in by the platform vendor for something that doesn't work unless the SecureBoot variable is set, so there may not be a way of reliably detecting it.  I'll put together an efi program for you to run from the shell to analyse the situation.

**Comment by poettering** [comment]
@msekletar @kaysievers something for you?

**Comment by msekletar** [comment]
@poettering I think that in this case systemd-boot did not even start and boot failed earlier, in PreLoader.efi.

PreLoader.efi is a tool written by James and it is used to install override to EFI_SECURITY_PROTOCOL which causes EFI Firmware to also check signatures on EFI binaries against MOK (Machine Owner Keys)  Security Database.

This probably isn't even bug in PreLoader but really borked EFI implementation. EFI FW implementing EFI 2.1 claims to support SecureBoot, but it was first introduced in EFI 2.3.

**Comment by mirh** [comment]
It's not claiming to support SecureBoot, you can check dmpstore above. 
Albeit yes, it's not technically a systemd-boot bug. I would have preferred to discuss it on the efitools repo, but James replied here.

**Comment by msekletar** [comment]
> First and only thing I get after booting arch image on my Asus laptop is:
> 
> `Failed to install override security policy: (14) Not Found`

From `PreLoader.c` 

``` C
    status = security_policy_install();
    if (status != EFI_SUCCESS) {
        console_error(L"Failed to install override security policy",
                  status);
        /* Don't die, just try to execute without security policy */
        goto override;
    }
```

Note that we attempt to install override only if SecureBoot variable is present and its value is 1. AFAICT your FW is schizophrenic, because it claims to support SecureBoot when you run PreLoader but at the same time SecureBoot variable is not present in output of dmpstore.

**Comment by poettering** [comment]
OK, if this is about an error generated by some software running before sd-boot, then let's close this here.

**Comment by mirh** [comment]
Yes, I had already checked that. 
What I totally fail to see, is how 2010/2011 products (with FW dated around that time, if not earlier) are passing the check, given their release date seems a good reason to believe they don't even know what Secure Boot was in the first place. 
And it's not just about my laptop specifically. It seems plenty of older hardware by asus and msi are affected by this. 

Said this, I see it's OT relative to systemd, and I'll continue to discuss on the other repo.
