### ISSUE TITLE
ConditionEnvironment always fails for units inside an LXC container

### ISSUE THREAD

**Issue by arren-ru** [systemd/systemd#26273]
### Component

systemd

### Is your feature request related to a problem? Please describe

Running systemd inside an LXC container as PID1 with configured env variable for container itself, but variable is visible only for PID1, so unit like so will never start:
```ini
[Unit]
ConditionEnvironment=VAR

[Service]
PassEnvironment=VAR
```
But passing variable works well.
So how to check such condition/assertion?

### Describe the solution you'd like

Seems to be we need to check environment variable condition considering also PassEnvironment.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
I am not sure I grok what you are saying.

ConditionEnvironment= checks the env var set for the service manager (i.e. for PID 1), as per docs. Hence if you set the env var there, ConditionEnvironment= should just work to test against it.

Are you saying this doesn't work? Can show a minimal reproducer?

**Comment by poettering** [comment]
Closing due to lack of response, and almost certainly just a misunderstanding how this works.
