### ISSUE TITLE
systemd-resolved - DNS zone conflict

### ISSUE THREAD

**Issue by gelven4sec** [systemd/systemd#26290]
### systemd version the issue has been seen with

249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb

### Used distribution

PopOS 22.04

### Linux kernel version used

6.0.12-76060006-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I use a private DNS server behind a Wireguard VPN, which serve a public domain zone, let's say `domain.tld`, which is **also** served by a public registrar.

`public.domain.tld` record is on my public zone, resolvable from internet
`internal.domain.tld` record is on my private zone, behind my VPN

When I'm connected to my Wireguard server, my `/etc/resolv.conf` becomes this:
```
10.0.2.2 ; my internal DNS server behind VPN
127.0.0.53 : systemd-resolved stub resolver
```

So I should be able to resolve `internal.domain.tld` from `10.0.2.2`, and to resolve `public.domain.tld` from `127.0.0.53`.

Theses are my test commands : 
```bash
nslookup internal.domain.tld # Should resolve and it does
nslookup public.domain.tld # Should resolve and it doesn't
```

### Unexpected behaviour you saw

Based on my previous test commands  : 
```bash
nslookup internal.domain.tld # It resolves
nslookup public.domain.tld # It doesn't resolves :'( (NXDOMAIN)
```

So here comes some points I observed : 
```
nslookup public.domain.tld 127.0.0.53 # Does resolves ! 
```
So why isn't my resolver capable of looking for the record in `127.0.0.53` after it fails to resolve in `10.0.2.2` ?

I think I have an idea, if I try to `dig` (`dig public.domain.tld`) in, I get the NXDOMAIN response and the SOA record from my internal DNS server.

So my guess is that it gets the NXDOMAIN response from my first nameserver in `resolv.conf` but it doesn't go on the second one where it will resolve.

So my point, the Linux resolver should still try to resolve a domain on all the nameserver even if one of them returns a NXDOMAIN response.

### Steps to reproduce the problem

1. Get a public TLD and setup a DNS record
2. Setup a DNS server accessible from LAN, with the same TLD domain, and setup a different record than the public one
3. Add your internal DNS server first in your `resolv.conf` and then whatever public DNS resolver
4 Try to resolve your internal record (should work)
5. Try to resolve your public record (it shouldn't)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> public.domain.tld
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 34370
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 02fb357898a1d22f0100000063da871535f8692d07a6b142 (good)
;; QUESTION SECTION:
;public.domain.tld.		IN	A

;; AUTHORITY SECTION:
domain.tld.		7200	IN	SOA	ns.domain.tld. info.domain.tld. 20220121 43200 900 1814400 7200

;; Query time: 4 msec
;; SERVER: 10.0.2.2#53(10.0.2.2) (UDP)
;; WHEN: Wed Feb 01 16:36:53 CET 2023
;; MSG SIZE  rcvd: 121
```

**Comment by poettering** [comment]
resolved switches DNS servers on failure and sticks to one that works.

You appear to think resolved should always start with the first listed and try until it finds a successful reply. But htat's not how this works. See #5755.

But note that your usecase is explicitly supported by resolved, via per-interface DNS servers and per-interface domain routing.

use "resolvectl dns" and "resolvectl domain" to specify per-interface DNs servers and domains to route to them. see docs for details.
