### ISSUE TITLE
gpt-auto-generator: fails to trace through dm-crypt+lvm layers

### ISSUE THREAD

**Issue by hlieberman** [systemd/systemd#26300]
Hello!

Currently, gpt-auto-generator doesn't correctly handle LVM-on-dm-crypt'ed disks correctly, misidentifying the decrypted VG  partition as the physical disk root.  For example, for the following disk structure, "vineta-crypt" is what `block_device_get_originating` in `src/shared/blockdev-util.c` selects as the root drive to search for the GPT table:
```
NAME                          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
nvme0n1                       259:0    0 931.5G  0 disk
├─nvme0n1p1                   259:1    0   1.9G  0 part
└─nvme0n1p2                   259:2    0 929.7G  0 part
  └─vineta-crypt              254:0    0 929.6G  0 crypt
    ├─vineta--vg-vineta--swap 254:1    0    32G  0 lvm   [SWAP]
    └─vineta--vg-vineta--root 254:2    0 897.6G  0 lvm   /
```

Rather than simply check for the existence of `/queue` in `block_get_whole_disk` (i.e., https://github.com/systemd/systemd/blob/42c042cfd100b163d1f3f29b2980cf9e6fc70136/src/shared/blockdev-util.c#L224-L229), we should continue following the chain of slaves up to the physical partition or disk.

For example, on the same disk above, `dm-2` (aka 254:2) has a single entry in `/slaves`: `dm-0` (aka 254:0).  In `dm-0`, there is a single entry in `/slaves`: `nvme0n1p2`, which has `/partition` present.

**Comment by poettering** [comment]
gpt-auto is about deriving purpose from GPT partition tables on single disks, not more. LVM is an enterprise volume manager that can span disks. It's entirely out of focus. Maybe it might make sense to add something similar for LVM, but if so, it should be done as part of LVM, not systemd.

**Comment by hlieberman** [comment]
While I completely agree that LVM in a multi-disk environment is unsuitable for gpt-auto-generator, since that would add all sorts of complexity, I do think that it's worth considering the LVM-on-top-of-dm-crypt case for a single disk.  This is a fairly common pattern for Linux distributions (dm-crypt+LVM); in fact, it's the default in Debian([1]), Ubuntu([2]), the recommended approach to get hibernation to work on Arch Linux([3]), and one of many documented approaches for Gentoo([4]).

Importantly, I think there's a big difference between crypt-on-LVM and LVM-on-crypt.  The former there's no clear path for gpt-auto-generator to take (which disk does it follow? What about VGs on non-disks, like a file?) for all the reasons you specified.  But for the former, I think there's a possible "simple" case that might be worth supporting.

Let me know if that clarifies my ask at all.  If it's still not something you see in scope, at least I've made my pitch.

[1]: https://www.debian.org/releases/stable/amd64/ch06s03.en.html#partman-auto
[2]: https://ubuntu.com/tutorials/install-ubuntu-desktop#7-optional-enable-encryption
[3]: https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS
[4]: https://wiki.gentoo.org/wiki/Full_Disk_Encryption_From_Scratch_Simplified

**Comment by poettering** [comment]
sorry, but LVM stuff is out of scope. Contact LVM people, maybe they can add something like gpt-auto-generator for you. 

But outside of a server LVM is a mistake I am sure, and a dead-end. I am sure people disagree, and that's OK, but we'll still not make LVM our problem.
