### ISSUE TITLE
Many Failures on services when /home symlinked to non-existent.

### ISSUE THREAD

**Issue by 5x3** [systemd/systemd#26312]
### systemd version the issue has been seen with

246.6-3

### Used distribution

Fedora 33 and onward

### Linux kernel version used

5.8.15.301

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

in additional info

### Unexpected behaviour you saw

in additional info

### Steps to reproduce the problem

in additional info

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
cd /
mv -iv /home /home.orig
ln -s /mnt/luksprivate/ /home
reboot
```
#profit

Regrading problem - you may noticed many services will fail to start on boot.
Example:
sytemd-userdhd.service: Failed to set up mount namespacing: /run/systemd/unit-root/mnt/luksprivate/ <-- *

and many others with the same error.

systemctl status is degraded, many services not working.

/mnt/luksprivate/ will be mounted later by me after I logged in in system or by the rc.local script but this did not help.

/home symlink to non existent dir - problem.
/home regular dir (even empty) - ok.
/home non existed dir - also ok.

Please provide fix for all users and workaround for me, since I will not upgrade.

**Comment by poettering** [comment]
I am not sure we can fix this even if we wanted to. We set up mount namespacing for many many services to sandbox them and take away the chance to write to /home/ and other dirs. We can only send up such sandboxing for inodes that exists, not those which do not.

I am not convinced we should cover a setup like this which is pretty obviously broken, given it carries dead symlinks for a crucial directory.

**Comment by 5x3** [comment]
we should\obvious\broken\crucial - beautiful literary style.
not broken since it works as expected and mounted later my own script (you probably hate user own scripts here), not critical - or maybe just for you (since you own stuff is always - critical, but is one of the FHS dir, there is no such term in FHS critical and not critical dirs), but I see another blinkered systemd-centrists person? asking you to be objective with a problem -I asked, - oh no, by no means -they answered.

symlinks can be "broken" while traget may missing, by the nature of symlinks, this just one of the state of symlinks.
well, here's my presidential campaign promise to you, your systems won't crash because of missing symlink target files (read as because of systemd). i'm just joking, isn't?

you code already ready for missing /home, but not for missing symlink target, ask yourself about the difference without the husk.

And no discussion needed, just bugfix. 

And yes, you see problems, you don't recognize them by trying to get away from the problem, and you don't know what to do because your product is not good by the design, so any fixing of a bug will cause difficulties.

that's enough discussion for now? maybe just fix the problem now?

thanks in advance.

**Comment by poettering** [comment]
i am sorry, but this is not the tone of discussion we enjoy. I can understand you disagree with my response, but if you can't be civil, then I am just thoroughly disinterested in your problem. And discussing this with you will just steal my time, so let's end this here.
