### ISSUE TITLE
https://www.freedesktop.org/wiki/Software/systemd/inhibit/ : Is there wrong formating of a single line?

### ISSUE THREAD

**Issue by ZjYwMj** [systemd/systemd#26314]
Not sure if this is the correct place to report. I couldn't find a better one.
Almost a verbatim copy of the [message](https://lists.freedesktop.org/archives/systemd-devel/2023-February/048802.html) at systemd-devel mailing list.

Referring to https://www.freedesktop.org/wiki/Software/systemd/inhibit/ .
There is a bullet list of cases at the top of the page. 
line100, namely
```
    Applications which want to make use of the inhibition logic shall take an inhibitor lock via the <a href="http://www.freedesktop.org/wiki/Software/systemd/logind">logind D-Bus API</a>.
```
is at the last point of that list.
Doesn't that line should be placed out of, and after, the whole bullet list? That is, after the ``</ul>`` tag? probably within a ``<p></p>`` tags, adjacent, and prior to, the
```
<p>Seven distinct inhibitor lock types may be taken, or a combination of them:</p>
```
line.

**Comment by keszybz** [comment]
https://cgit.freedesktop.org/wiki/www/commit/Software/systemd/inhibit.mdwn?id=f858d699a7fa4ac9fb89c82a708e75a5f975e566

We should move this page to docs here…
