### ISSUE TITLE
udevd errors "Failed to get cgroup" in non-systemd initramfs

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#2635]
I assume this is still a supported use case... See downstream bug report: https://bugs.archlinux.org/task/48188

What I suspect happens is:

udevd.c -> cg_pid_get_path(SYSTEMD_CGROUP_CONTROLLER, 0, &cgroup) -> cg_unified() -> [returns -ENOMEDIUM]

In the non-systemd initramfs case, /sys/fs/cgroup exists as a directory, but it isn't a mountpoint. My guess is the error is benign, but I think maybe udevd.c needs to treat -ENOMEDIUM as a case similar to -ENOENT and -ENOEXEC.

**Comment by poettering** [comment]
I figure this is all-out from 8b3aa503c171acdb9ec63484a8c50e2680d31e79 and the ENOEXEC should be replaced by ENOMEDIUM.

**Comment by poettering** [comment]
Fix waiting in #2623.
