### ISSUE TITLE
Regression: broken specifiers in v229

### ISSUE THREAD

**Issue by jsagarribay** [systemd/systemd#2637]
According to man page, the specifier %% translates to a single % in unit files, and it worked fine before. Starting with v229 this:
`ExecStart=/bin/touch /tmp/%%Uanything`
will touch `/tmp/1000anything` instead of `/tmp/%Uanything`
You need to repeat the percent signs twice to workaround this bug:
`ExecStart=/bin/touch /tmp/%%%%Uanything`
will touch `/tmp/%Uanything`

**Comment by evverx** [comment]
I can confirm this.
Regression was introduced by cb48dfca6a8bc15d9081.
@walyong, please, have a look
