### ISSUE TITLE
Should clearing `RandomizedDelaySec` enable default behavior?

### ISSUE THREAD

**Issue by adrian5** [systemd/systemd#26399]
I tried overriding the following:

```ini
[Timer]
OnCalendar=daily
RandomizedDelaySec=12h
AccuracySec=20min
Persistent=true
```

With this:

```ini
[Timer]
OnCalendar=Tue *-*-* 18:00
RandomizedDelaySec=
AccuracySec=
```

This didn't work, the randomization persisted.

---

What was need to clear randomization is:

```ini
RandomizedDelaySec=0
```

Is this the intended systemd behavior for value overrides, i.e. clearing does not imply defaulting?

**Comment by poettering** [comment]
Please fill in the full bug submission form. This is otherwise not useful. i.e. systemd version at a minimum.

**Comment by poettering** [comment]
Closing this one in favour of #26411
