### ISSUE TITLE
check-help-ukify fails on wide terminal

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#26414]
### systemd version the issue has been seen with

253-rc3

### Used distribution

Gentoo

### Linux kernel version used

5.15.90

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Tests pass.

### Unexpected behaviour you saw

```
1087/1090 systemd:dist-check / check-help-ukify                                FAIL             0.30s   exit status 1
>>> MALLOC_PERTURB_=99 /x/portage/sys-apps/systemd-253_rc3/work/systemd-253-rc3/tools/check-help.sh /x/portage/sys-apps/systemd-253_rc3/work/systemd-253-rc3-abi_x86_64.amd64/ukify
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
ukify --help output is too wide:
  --pcrpkey KEY         embedded public key to seal secrets to [.pcrpkey section]
                        path to key file or engine-specific designation for SB signing
                        path to certificate file or engine-specific designation for SB signing
  --tools TOOLS         Directories to search for tools (systemd-measure, llvm-objcopy, ...)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

```

### Steps to reproduce the problem

Run tests on a terminal with 100 columns.

**Comment by yuwata** [comment]
Hm? I cannot reproduce the issue. I tested `meson test check-help-ukify` with <100, ==100, >100 width.

**Comment by yuwata** [comment]
Maybe, issue in python or a module?

**Comment by floppym** [comment]
When I call `ukify.py --help` from a command line, the output is wrapped differently based on the width of my terminal. This happens with Python 3.9.16, 3.10.10, and 3.11.2.

**Comment by floppym** [comment]
Hmm, I'm unable to reproduce it myself when calling `meson test` directly. It fails when I run it from an ebuild environment though.

**Comment by yuwata** [comment]
Even when `$COLUMNS` unset, I cannot reproduce the issue. Also, I tested direct call of `tools/check-help.sh build/ukify`, but still cannot be reproduced.

I use python3.11.1.

**Comment by floppym** [comment]
Thanks for trying. I'll do some more research on my end.

**Comment by floppym** [comment]
Ah, the problem is that Portage actually sets COLUMNS=100 in the environment.

https://github.com/gentoo/portage/blob/portage-3.0.44/lib/portage/package/ebuild/doebuild.py#L495
