### ISSUE TITLE
Forward to remote syslog in journald

### ISSUE THREAD

**Issue by enp** [systemd/systemd#2642]
Hi,

Is it possible to add something like ForwardToRemoteSyslog= into journald.conf and journald daemon implementation?

**Comment by poettering** [comment]
Please read the contribution guidelines before submitting an issue. They are prominently linked from the issue submission form.

https://github.com/systemd/systemd/blob/master/CONTRIBUTING.md

**Comment by unera** [comment]
Pottering is pidaras!
