### ISSUE TITLE
RootImage= with NetworkNamespacePath= does not mount /sys in the correct namespace

### ISSUE THREAD

**Issue by isodude** [systemd/systemd#26422]
### systemd version the issue has been seen with

252

### Used distribution

Debian 11

### Linux kernel version used

6.0.0-0.deb11.6-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

```
root@ciliumlb01 (prod!):~# systemd-run -t --collect -p RootImage=/tmp/image -p PrivateNetwork=yes ls -1 /sys/class/net
lo
```

### Unexpected behaviour you saw

```
root@ciliumlb01 (prod!):~# systemd-run -t --collect -p RootImage=/tmp/image -p PrivateNetwork=yes ls -1 /sys/class/net
eth0
lo
```

### Steps to reproduce the problem

Run the command in the unexpected behaviour. The problem here is that MountAPIVFS= does not change namespace before setting up mounts. According to sysfs documentation the namespace tag on /sys is set to the one mounting.

This affects NetworkNamespacePath= as well.

Workaround:
```
# systemd-run -t --collect -p RootImage=/tmp/image -p PrivateNetwork=yes -p MountAPIVFS=off /bin/bash -c 'mount sysfs -t sysfs /sys; ls -1 /sys/class/net'
Running as unit: run-u100.service
Press ^] three times within 1s to disconnect TTY.
lo
```

**Comment by yuwata** [comment]
sysfs does not support network namespace. There is nothing we can do. Closing.

**Comment by isodude** [comment]
> sysfs does not support network namespace. There is nothing we can do. Closing.

If it is not supported, how come the workaround works?

**Comment by yuwata** [comment]
Oh, I may misunderstand, and as you already commented, mounting sysfs in the new network namespace works as expected. Hm...

**Comment by yuwata** [comment]
Yeah, I already re-opened. Sorry.

**Comment by isodude** [comment]
@yuwata Thanks for looking into this, I ser that it was a bit of work.

Just to make sure, this will work if you specifiy a namespace with NetworkNamespacePath= as well right?

**Comment by yuwata** [comment]
> Just to make sure, this will work if you specifiy a namespace with NetworkNamespacePath= as well right?

That should work, though we do not have any integrated tests for `NetworkNamespacePath=`...

**Comment by yuwata** [comment]
@isodude A simple test for `NetworkNamespacePath=` is added in #26662.
