### ISSUE TITLE
A way for mount units to specify a fallback for Options and What would be nice

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#26434]
### Component

other

### Is your feature request related to a problem? Please describe

When dealing with certain filesystems in a raid setup (e.g. BTRFS) if a device becomes unmountable then they need to be mounted with the `degraded` option. Additionally with BTRFS specifically it also mounts the pool through any device in the pool so if the one you picked is the one going missing, tough luck. I'm not sure if that should be part of this issue though but maybe it would fit into a more generic fallback unit approach?
For the former it's generally frowned upon to mount them always in degraded and it would also make it harder to detect when it actually goes into degraded mode, but at the same time it is currently the only way if you want to use such a setup on e.g. a rootfs (especially on a remote/headless machine) because otherwise it will not boot even when it is still within capabilities to function.
For the latter there just isn't a workaround currently to the best of my knowledge, making BTRFS unfit for a rootfs

### Describe the solution you'd like

A way to express `mount foo $Where || mount bar $Where -o degraded` basically. Maybe something like a `FallbackOptions`/`FallbackWhat` directive for mount units that if set will make systemd retry a mount with the respective directives replaced? If there needs to be a fstab compatible `x-systemd-` directive too im not sure about its syntax for the options one though.
Otherwise a way to specify a different .mount file as a fallback alltogether though i'm not sure that fits well into the current system of one mount unit per path only.

Im not entirely sure about `FallbackWhat` as i dont know how it will affect dependency resolution if `What` changes, which still sucks for BTRFS but `FallbackOptions` would still be helpful for e.g. the upcoming bcachefs.

### Describe alternatives you've considered

Alternative would be writing a .service unit that calls `mount` manually, but that seems like a shortcoming of the current mount subsystem and doesn't have the nice auto dependency resolving that comes with regular mounts. 
If there's other things i missed i'd be willing to try them but if there already is such functionality I don't think it was documented too clearly(?)

### The systemd version you checked that didn't have the feature you are asking for

252.4

**Comment by maddiethecafebabe** [comment]
Oh thanks for letting me know, i didn't see that.

Multiple kernel cmdlines still seem awkward to do from a headless/remote machine but i'll look into it once support is there. But i dont think this in particular will solve the issue of a disk in a rootfs raid failing meaning the machine cant boot anymore without manual intervention, which depending on the hoster might be non trivial :/.

Automatic Boot Assessment sounds like it could be used the best for what i want to do, its just gonna require some fiddling with my setup but that should be doable, that atleast will be automatic. 
Sounds like i just need to generate an extra fallback kernel that has different mount options for the rootfs for every "normal" kernel?

If what i proposed was already discussed though ill close the issue, dont think i have anything relevant to add then
