### ISSUE TITLE
[autofs] system shutdown hangs because systemd attempts unmount before autofs

### ISSUE THREAD

**Issue by tgharib** [systemd/systemd#2645]
Original bug report: https://bugs.archlinux.org/task/40200

This is still an issue as of Feb 16, 2016. His fix of adding `remote-fs.target` to `After=` in `autofs.service` worked.

Systemd version: 228
Distribution: Manjaro

To reproduce the issue, use autofs to auto-mount a NFS share. Then, while the NFS share is still mounted, attempt to shutdown or reboot and the systemd will hang as it tries to shutdown.

**Comment by tgharib** [comment]
Wait, I just realized that this might be an autofs bug and not systemd since autofs is the one who created autofs.service, right?

**Comment by poettering** [comment]
yeah, autofs.service should be fixed to add After=remote-fs.target. This is nothing we can or should fix in systemd itself. Closing hence.

**Comment by ghost** [comment]
I have more than one `autofs.service` file on my (Linux Mint) system, namely:

(1) /lib/systemd/system/autofs.service
(2) /etc/systemd/system/multi-user.target.wants/autofs.service

Perhaps someone could advise me which of those files to alter. Thanks.

**Comment by tgharib** [comment]
On arch, I believe it was /usr/lib/systemd/system/autofs.service

It couldn't hurt to edit both to be honest but I believe it's the first.

**Comment by boucman** [comment]
I wouldn't be suprised if (2) was a symbolic link to (1)

**Comment by ghost** [comment]
My mistake: as boucman suggested, file 2 was merely a link to file 1. Apologies.
