### ISSUE TITLE
`systemd-cryptenroll`: allow sealing to signatures of PCRs

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#26456]
### Component

systemd-cryptsetup, other

### Is your feature request related to a problem? Please describe

Sealing to specific PCR hashes is fragile.  Relying on secure boot data measured into PCR 7 doesn’t work if Dynamic Root of Trust for Measurement (DRTM, see #26454) is used or if downgrade attacks are a concern.

### Describe the solution you'd like

`systemd-cryptenroll` should support sealing the key to a signature of a PCR.  The signing key would be held by the (trusted) OS vendor.  A Security Version Number (SVN) should be used to prevent downgrade attacks.

### Describe alternatives you've considered

Ugly, error-prone manual scripting :cry:.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
We already support that. See `--tpm2-public-key=`, `--tpm2-public-key-pcrs=`, `--tpm2-signature=` switches to `systemd-cryptenroll`.
