### ISSUE TITLE
Include poweroff/shutdown tool with sd-boot

### ISSUE THREAD

**Issue by WolfWings** [systemd/systemd#26461]
### Component

sd-boot

### Is your feature request related to a problem? Please describe

Some UEFI systems (especially x86 tablets) do not get powered down properly by the Linux kernel, and they'll either hang with a black screen but still running down the battery, or else quickly power back on. Rebooting to trigger the SystemTable->RuntimeServices->ResetSystem UEFI call properly powers them off.

### Describe the solution you'd like

Add a `poweroff` and/or `shutdown` auto-generated boot entry of perhaps `auto-poweroff` or if that's not viable would including a pre-built EFI poweroff.efi binary be possible?

Allowing `systemctl poweroff` to be configured to use this on systems that otherwise won't power off properly would be helpful as well.

### Describe alternatives you've considered

Installing UEFIShell and setting up scripting just to trigger `reset -s` is cumbersome at best, lots of extra moving parts, things to update due to poor packaging availability on most Linux distro's, etc.

Compiling a custom `poweroff.efi` or similar is simple enough using gnu-efi, but added maintenance steps and seemed worthwhile to suggest upstreaming, thus this issue.

### The systemd version you checked that didn't have the feature you are asking for

252 (252.5-1-arch)

**Comment by medhefgo** [comment]
Quite frankly, you should really be complaining to the kernel folks to get that fixed. At the very least they ought to add a "shutdown=efi" option or make "reboot=efi" also use the EFI services for shutdown.

**Comment by WolfWings** [comment]
I actually had looked into the `reboot=efi` and related paths when I discovered that the EFI ResetSystem method resulted in a clean shutdown.

I've had zero luck the 3-4 times in the past I've tried to contact kernel folks I admit, compared to a simple github request it's byzantine trying to route things to the correct maintainers, etc, simply due to the size of the kernel project.

As the additional binary from limited testing was so small (literally less than 4KB) and in general sd-boot has been so much nicer to use than fighting with grub2's ridiculous generated configuration files I thought it worth suggesting as an enhancement.

If it's a judged a bad fit for sd-boot that's understandable. I wasn't sure and felt it best to raise a simple issue to ask formally.

**Comment by poettering** [comment]
You could probably install the EFI shell and then add a boot menu entry which makes it call "reset -s", which should shutdown the system, no?

I am not sure systemd-boot needs to cover for this, seems too much like a local bug that the kernel should fix properly.

**Comment by WolfWings** [comment]
It may not be a good fit to include, and that's fine as an outcome.

Especially with sd-boot's move towards UKIs and becoming the modern standard for booting though I see how there's nowhere (from a control flow or configuration language perspective) to add this request now.

I'd considered EFI shell, but as mentioned above that has very poor availability as a package (it won't be available in Debian for instance until 2025 at the earliest with the release of Trixie) so it becomes extra moving parts keeping it compiling, updated, etc.

A dedicated minimal poweroff.efi binary has become a usable stopgap for the time being for me since it's a permanently unchanging EFI binary at that point.

Thank you for your time and consideration.
