### ISSUE TITLE
"Stop" ordering and dependency - administratively problematic and not explicitly documented - a "forward" syntax is needed.

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#2647]
Apparently the _only_ way - and let me repeat that, since it seems to go against the general tone of the documentation at man systemd.unit - the ONLY way to establish a Stop ordering between units A and B, where unit A is first to Start and last to Stop, is to define _both_ "Requires=A" _and_ "After=A" _in unit B_.

All the implied references to the inverse nature of the "Before=" dependency apparently _do not apply_, and _have no effect_, upon the Stop ordering of units A and B.  In particular, the use of "Requires=B" and "Before=B" in unit A will _not_ create a Stop ordering between units A and B.

The documentation at systemd.unit is misleading here and should be corrected!

This convention of defining a Stop ordering in unit B, and providing no mechanism to define an equivalent Stop ordering in unit A is problematic for writing concise Unit Files when a specific Stop ordering is necessary across two or more related service units.  In particular, it becomes necessary to create multiple custom modified unit files for unit B, instead of allowing the use of simpler generic template unit files, which would be preferable.

An example of this occurs when "bonding" a wired and a wireless interface to a third "bond" interface, where wpa_supplicant will run on the wireless interface and DHCP servers will run on the bond interface.  The DHCP service files can no longer be generic because all three of a bond interface name, a wireless interface name, and a "calling" unit file name, must be specified, while there is only the one template variable available.  For instance, the DHCP servers, defined in unit B, will run on "bond0", while the Stop ordering must be defined on "UnitA@wlp2s0".  Here, the DHCP unit file must be custom modified to reference the particular wireless interface name, and the particular "calling" service unit file name.  And, when more than one wireless interface name is in use, a custom DHCP service unit file must be created for each wireless interface name.  That sucks.

Providing a "forward" Stop ordering syntax for service unit files could alleviate this annoyance.  The simplest approach would be to make "Requires=B" and "Before=B" in unit A entirely equivalent to "Requires=A" and "After=A" in unit B, for the purpose of enforcing a Stop ordering.  Then, nothing additional need be written into unit file B, which then remains a generic unit file.

**Comment by arvidjaar** [comment]
> The documentation at systemd.unit is misleading here and should be corrected!

Please provide systemd log with log level debug that demonstrate this problem as well as full definitions of units that are used to produce this log.

**Comment by thx1111** [comment]
Before I do the work to demonstrate this, let me clarify:  Is it your understanding and expectation that a "Requires=B" and "Before=B" in unit A _should be_ entirely equivalent to a "Requires=A" and "After=A" in unit B, and that that configuration in unit A _should_ produce a functioning Stop ordering between units A and B?

**Comment by arvidjaar** [comment]
> "Requires=B" and "Before=B" in unit A should be entirely equivalent to a "Requires=A" and "After=A" in unit B

No. "A requires B" is not the same as "B requires A" so these two are not equivalent. But "Before=B in A" is entirely equivalent to "After=A in B".

**Comment by thx1111** [comment]
Given that "A requires B" is not the same as "B requires A", still, do you expect that "Requires=B" and "Before=B" in unit A _should_ produce a functioning Stop ordering between units A and B?

**Comment by filbranden** [comment]
> Is it your understanding and expectation that a "Requires=B" and "Before=B" in unit A should be entirely equivalent to a "Requires=A" and "After=A" in unit B

@thx1111 Are you maybe looking for `RequiredBy=B` and `Before=B` in unit A instead?

**Comment by poettering** [comment]
@filbranden we don't allow configuration of RequiredBy= in unit files. "RequiredBy=" are basically an internal concept that is implicitly created as we discover Requires= fields. Note that systemd only loads the minimal unit tree, starting from a given unit. That means if we start loading from a unit "foo.service" and some other unit "bar.service" lies around somewhere, which might have "RequiredBy=foo.service", then we'd never see that because "foo.service" has zero references to it...

**Comment by poettering** [comment]
Anyway, I thought the docs are sufficiently clear about that, but let me spell this out again:
- In systemd "requirement" and "ordering" dependencies are orthogonal (meaning: independent). That means After= and Before= purely define ordering, and Wants=, Requires= and BindsTo= purely define requirement. Sometimes it makes sense to only use ordering deps, sometimes it makes sense to only use requirement deps betweento units, but in many cases you want to combine both.
- systemd loads "minimal" unit trees, always follow configured deps from unit files. Hence we don't allow RequiredBy= to be defined in unit files.

This is explained in the systemd documentation in systemd(1), as well as systemd.unit(5). There are also numerous documents about this available on the Internet everywhere. I am not convinced this really needs more documentation, it just requires actually reading it. 

Closing hence.

**Comment by thx1111** [comment]
The issue here is about Stop ordering.  Does anyone believe that there _will_ be a Stop ordering created by a particular configuration?  And does anyone believe that there _should_ be a Stop ordering created by any particular configuration?  In particular, with respect to some configuration in unit A.  We already know how to configure unit B for a Stop ordering.

I point-out that using "ExecStop=/usr/bin/systemctl stop B" in unit A creates a Stop ordering between A and B, _but_ that this has not been the officially "sanctioned" solution.

So either, "systemctl stop" in unit A shall be the "official" configuration mechanism for configuring a Stop ordering from unit A, _by default_, or come-up with something else.

**Comment by poettering** [comment]
I don#t understand a word you are saying.

In systemd, if two units are queued for stopping, and A contains Before=B, then B will be stopped first, and A second. (Why? because in systemd the stop order is the inverse of the start order and with After=/Before= you declare he start order.)

Now, if you want to make sure that a unit A never runs without a unit B, then make sure to add BindsTo=B to A. This way, enqueuing a stop for B will also enqueue a stop for A.

Again, typically you'd do both: define the ordering via Before= (or After=), and define the requirement (via BindsTo=).

**Comment by thx1111** [comment]
> In systemd, if two units are queued for stopping, and A contains Before=B,
> then B will be stopped first, and A second.

Yeah - no - does _not_ happen that way.  If you think that that is the way it works, then it is broken, and there is a bug.

**Comment by poettering** [comment]
Well, please provide a _minimal_ test case that shows what you are saying. Otherwise there's little we can do.

**Comment by thx1111** [comment]
This is fairly straightforward, because it just does what it says.  It's trivial.

Here, a Stop ordering is _not_ generated because there is no "forward" Stop dependency.  Only unit A gets queued for stopping.  Hmm - ok, I misspoke.  The big "if" is "if two units are queued for stopping".  My issue is about the way in which unit B gets included in the stop queue when unit A is stopped.

``` systemd
[Unit]
Description=Unit_A
Requires=B.service
Before=B.service
# If one of the other units gets deactivated [B] or its activation fails,
# this unit [A] will be deactivated.
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/echo Unit A starting...
ExecStop=/usr/bin/echo Unit A stopping...
```

``` systemd
[Unit]
Description=Unit_B
[Service]
Type=simple
ExecStart=/usr/bin/bash -c 'echo Unit B starting...;sleep 6000'
ExecStop=/usr/bin/echo Unit B stopping...
```

`systemctl start A.service`
Feb 18 17:46:54 garnet systemd[1]: Starting Unit_A...
Feb 18 17:46:54 garnet echo[3047]: Unit A starting...
Feb 18 17:46:54 garnet systemd[1]: Started Unit_A.
Feb 18 17:46:54 garnet systemd[1]: Started Unit_B.
Feb 18 17:46:54 garnet bash[3050]: Unit B starting...
`systemctl stop A.service`
Feb 18 17:53:04 garnet systemd[1]: Stopping Unit_A...
Feb 18 17:53:04 garnet echo[3117]: Unit A stopping...
Feb 18 17:53:04 garnet systemd[1]: Stopped Unit_A.

Unit B does not stop, and it does not stop _first_.
`systemctl list-units B.service`
B.service loaded active running Unit_B

The "sanctioned" method for creating a Stop ordering is to modify unit _B_.  It works, but it requires a modification in unit B, not in unit A.  The modification appears somewhat trivial here, but it is not so trivial when configuring a string of template unit files and the name required in unit B@Y.service is from some other template file, A@X.service.  B@Y.service is no longer generic.  Whenever X changes, B@Y must be revised manually.  And if there are more than one X and/or more than one Y, there will probably need to be many customized B@Y.service files.

``` systemd
[Unit]
Description=Unit_A
Wants=B.service
Before=B.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/echo Unit A starting...
ExecStop=/usr/bin/echo Unit A stopping...
```

``` systemd
[Unit]
Description=Unit_B
Requires=A.service
# If one of the other units gets deactivated [A] or its activation fails,
# this unit [B] will be deactivated.
[Service]
Type=simple
ExecStart=/usr/bin/bash -c 'echo Unit B starting...;sleep 6000'
ExecStop=/usr/bin/echo Unit B stopping...
```

`systemctl stop A.service`
Feb 18 18:22:26 garnet systemd[1]: Stopping Unit_B...
Feb 18 18:22:26 garnet echo[3243]: Unit B stopping...
Feb 18 18:22:26 garnet systemd[1]: Stopped Unit_B.
Feb 18 18:22:26 garnet systemd[1]: Stopping Unit_A...
Feb 18 18:22:26 garnet echo[3247]: Unit A stopping...
Feb 18 18:22:26 garnet systemd[1]: Stopped Unit_A.

If you want to achieve a mostly similar result _without_ modifying unit B, you have to use an explicit `systemctl stop B.service` in unit A.  This will then add unit B to the stop queue when unit A is stopped, but not in exactly the same order as above.  Still, unit B will stop before unit A, and the unit B service file is unmodified.

``` systemd
[Unit]
Description=Unit_A
Wants=B.service
Before=B.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/echo Unit A starting...
ExecStop=/usr/bin/systemctl stop B.service
ExecStop=/usr/bin/echo Unit A stopping...
```

``` systemd
[Unit]
Description=Unit_B
[Service]
Type=simple
ExecStart=/usr/bin/bash -c 'echo Unit B starting...;sleep 6000'
ExecStop=/usr/bin/echo Unit B stopping...
```

`systemctl stop A.service`
Feb 18 18:28:58 garnet systemd[1]: Stopping Unit_A...
Feb 18 18:28:58 garnet systemd[1]: Stopping Unit_B...
Feb 18 18:28:58 garnet echo[3319]: Unit B stopping...
Feb 18 18:28:58 garnet systemd[1]: Stopped Unit_B.
Feb 18 18:28:58 garnet echo[3325]: Unit A stopping...
Feb 18 18:28:58 garnet systemd[1]: Stopped Unit_A.

I say that there is a configuration option missing which would allow a declaration in the unit A service file to create a "forward" stop dependency on unit B.  The option causes unit B to be added to the stop queue when unit A is added to the stop queue.  The option definition would say something like "If this unit gets _deactivated_, the units listed here will be _deactivated_ as well."  You could call it "ForwardStop=" or "AlsoStops=" or "Terminates=" or "Restrict=" or "Scrub=" or "Discontinue=" or some such.

And then, the unit B service file would remain unmodified, and the unit A service file would instead look like:

``` systemd
[Unit]
Description=Unit_A
Wants=B.service
Before=B.service
AlsoStops=B.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/echo Unit A starting...
ExecStop=/usr/bin/echo Unit A stopping...
```

Much cleaner, yes?

**Comment by arvidjaar** [comment]
When you discuss something, you need to follow established terminology. The notion of "ordering dependencies" has very precise meaning in systemd; all the time you were talking about something entirely different. Instead of picking up arbitrary definitions and giving them your own meaning (completely different from the meaning they have) and then complaining that they do not work as you think they should you had to simply state what you want to do.

> The option [of unit A, that] causes unit B to be added to the stop queue when unit A is added to the stop queue.

Now when it is clear what you actually mean - what is your use case?

**Comment by thx1111** [comment]
> you need to follow established terminology.

Door knobs are very simple _after_ you learn what they are and how they work.

> what is your use case?

Did you not read it?  There are four different examples there to compare.

**Comment by poettering** [comment]
I have trouble following. Note that you can extend unit files without changing them by dropping in .conf snippets in .d/ directories next to their name. i.e. if you want to extend "foobar.service" without changing it you can do so by adding "foobar.service.d/waldo.conf" and then placing stuff in there. That way you can add "reverse Requires=" to a unit without modifying it, if that's what you are asking for.

But generally, please try to read up on documentation, these things are all documented there, you just have to read it.

**Comment by thx1111** [comment]
OK, not a bug, per se.

> if you want to extend "foobar.service" without changing it you can do so by adding
> "foobar.service.d/waldo.conf" and then placing stuff in there.

I don't see that that changes the issues with referencing template file names.  Whether you edit "foobar@.service.d/A@X.conf" or "foobar@Y.service", it is still not automatic, and you have to do it manually.

So, I can just keep using "ExecStop=/usr/bin/systemctl stop B@Y.service" in the unit A service file.  But please stop telling people that that is a "mistake" or a "misunderstanding" when, in fact, it is the only way to configure a Stop ordering for unit B from unit A.  That just adds to the confusion and wastes time, with a futile search for some non-existent configuration option.

Still, the discussion has clarified how this all works.  Thanks for that.

**Comment by thx1111** [comment]
> Now when it is clear what you actually mean - what is your use case?

@arvidjaar 
It occurs to me that by "case" you meant "real world" case, as Lennart and I had discussed previously, as opposed to the simple example set presented here.  In which case, ;) to elaborate:

Unit A is Type=oneshot, a series of commands to set-up and tear-down an active-backup master "bonding" device interface with a wired interface and wireless interface as slaves.  For convenience, the wireless interface name is specified using the template variable.  The wired interface is specified using an environment variable.  Unit A has a forward dependency upon unit B.

Unit B is wpa_supplicant with an explicit "-b bond0" switch to enable receiving EAPOL frames from an additional interface when EAPOL is used.  The wireless interface name is passed forward from unit A.  The bonding interface name is "hard coded" in unit B.  Except for the forward dependency from unit A, all dependency and ordering is configured in unit B, because unit B can "reach" the other units through forward and reverse references.  In practice, units A and B could be combined, except for a restart bug. If unit A were to include a "fail-safe" BindsTo dependency upon the bonding interface device, unit A fails before establishing the bonding interface on restart.  A work-around is to put the fail-safe bonding device BindsTo dependency in unit B,  and make A Requires=B.

Units C and D are generic DHCP clients, dhclient and dhcp6c, which connect to the bonding interface, where the bonding interface name is specified through the template variable.  Units C and D "know nothing" about units A and B, and are otherwise quite independent.  They can be separately "started", "stopped", or "restarted" with "systemctl".  In practice, dhclient is activated through a timer unit and also requires an explicit ExecStop configuration.

The entire set, units A, B, C, and D, can be "enabled" for a specified wireless interface, WantedBy=default.target.  The set could also be made BindsTo a removable wireless device, falling back to a wired-only interface, WantedBy=sys-subsystem-net-devices-%i.device.  It all actually works quite nicely on a laptop.

The Stop ordering is critical.  C and D must Stop before the network link is taken down, giving time to Release their address leases.  wpa_supplicant has a reference to the bonding interface, so B must Stop before A.  It is preferable to configure the Stop ordering in unit B, either with a, for instance, "Terminates=C D", which does not exist, or with an "ExecStop=...systemctl stop C D", which is not "sanctioned".

**Comment by thx1111** [comment]
BTW, a "Wants=C@bond0 D@bond0" in either unit A or B starts perfectly well, but utterly fails during a "systemctl restart A@...".  This seems especially ironic, given that C and D have been explicitly stopped during the stop phase of unit A, and cannot, in any way, be assumed to be still in an active state during the start phase of either unit A or B.  _That_ I consider a bug.  A necessary work-around is to use an explicit "WantedBy=sys-subsystem-net-devices-%i.device" in units C and D, and "systemctl enable C@bond0 D@bond0", a forward dependency from the device special file instead of from the unit service file which creates that device.  Altogether, these are a lot of ad hoc workarounds, and systemd feels rather fragile and not robust.  Fixing the restart bugs and adding a forward Stop ordering option would clean-out these needed workarounds and eliminate some unnecessary systemd "surprises".

**Comment by arvidjaar** [comment]
> utterly fails during a "systemctl restart A@..."

That's what PartOf is for.

You still fail to explain _what_ you want to achieve and continue to repeat _how_ you want to do it. As far as can be inferred, you want to have several services that are stopped and (re-)started together as a single entity (to avoid pun with "unit"). Create top-level target if@bond0.target, make all other services PartOf if@bond0.target and use if@bond0.target when you need to start/stop interface. Or you can simply make B, C and D PartOf A if you insist on using A as "primary" service.

**Comment by thx1111** [comment]
> to avoid pun with "unit"

:)

I certainly do not mean to be difficult.  Yet, when I read at man systemd.unit:

PartOf=
           Configures dependencies similar to Requires=, but limited to stopping and restarting of units. When systemd stops or restarts the units listed here [A], the action is propagated to this unit [B, C, D]. Note that this is a one-way dependency — changes to this unit do not affect the listed units.

That is a "reverse" dependency.  I have already described a reverse dependency with Requires=A.  The "reverse" dependency is not a "missing" option.  As the man page says "PartOf= Configures dependencies similar to Requires=".  It is just nuanced, removing the forward Start dependency.  It specifically disavows any "forward" dependency effect.

At the expense of repeating myself, I have been talking instead about an option to create a _forward Stop_ dependency, which is something different.  There is currently no such option in systemd, let alone some nuanced multiple versions of forward Stop dependencies, as we see with forward Start dependencies, Requires, Wants, and BindsTo.

I do not know how to more plainly illustrate the distinctions between a forward Start dependency and a forward Stop dependency, or a reverse Stop dependency and a forward Stop dependency, than with the simple examples I gave earlier.

In your PartOf suggestion, it is still necessary to modify units B, C, and D.  _This is exactly what I want to NOT do._  Ideally, the "named" unit or "specialized" unit - unit A - is created with all the customization, and is _built upon_ or _constructed from_ otherwise generic, standard, unmodified unit files, as "parts", simple building blocks.  Units B, C, and D should not have to "know anything" about unit A.  That requires a _foward_ Start dependency option, which already exists, and a _forward_ Stop dependency option, which does not exist.

> You still fail to explain _what_ you want to achieve

I am running out of ideas, past the simple examples given, and taken to repeating myself.

> and continue to repeat _how_ you want to do it.

As I have said, I already know of "a" way to do it, using "ExecStop=/usr/bin/systemctl stop ...", but that triggers "restart" bugs.  I suppose then, that this really _is_ a matter of "how", which is to say, by using a proper "Unit option" for unit A, to produce a result entirely equivalent to "Requires=A" in unit B, for instance.  

Except that you say I have failed to explain _what_, but also say "Now when it is clear what you actually mean".  I am getting mixed messages. 

This is not that hard: forward/reverse, start/stop.

|  | Forward | Reverse |
| :-: | :-: | :-: |
| **Start** | Wants, Requires, BindsTo | PartOf |
| **Stop** |  | Requires, BindsTo, PartOf |

The group of Forward Stop option types is composed of the null list, the empty set.  "Wants" is the only single cell option.  There is no set of options from which you can "build your own" dependency, through combination.  systemd imposes its own "policy" on dependency types, and if it does not provide what you want, you are SOL.  It creates an artificial aura of mystery and complexity over something simple.

For the moment, consider:

Terminates=
        If this unit gets deactivated, the units listed here will be deactivated as well.

**Comment by thx1111** [comment]
BTW, I suppose it should be mentioned, on reflection, as the ordering mechanism is distinct from the dependency mechanism, that the Stop ordering issue has nothing to do with the ordering mechanism and involves simply the dependency mechanism.  In my experience, the ordering mechanism always "just works", as advertised.  The Stop ordering issue comes down to providing a dependency option that causes the listed units to be added to the stop queue when the defining unit is added to the stop queue, and just that.

**Comment by craigphicks** [comment]
I stumbled across this page while trying to understand why my unit wouldn't stop.  I found [this:](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StopWhenUnneeded=)

```

> StopWhenUnneeded=  
> 
> Takes a boolean argument. If true, this unit will be stopped when it is no longer used. Note that, in order to minimize the work to be executed, systemd will not stop units by default unless they are conflicting with other units, or the user explicitly requested their shut down. If this option is set, a unit will be automatically cleaned up if no other active unit requires it. Defaults to false.

```

**Comment by celesteking** [comment]
I'm in the same boat. I found this issue by looking for docs on `stop` ordering. I'd like to have a custom ordering of units and it seems you have to either be a systemd developer or push really hard on test cases in order to understand what's going on. A wiki page or tutorial with a table would be useful.

**Comment by gleventhal** [comment]
I am not sure that I'd say that the fact that After= or Before= are considered to dictate ordering is so cut and dry.. I believe they only define when the start command is run, but that's inherently asynchronous, isn't it?  Such that stating A having a Before=B only means ExecStart for A will be run first, but that the service B might be up and running, listening for connections, etc well before A because only the ordering of the start command is actually implied, correct?

Assuming that is correct, then I believe people may be using Requires to wait on success for A before starting B despite there being no dependencies between the two except an ordering one, such that all you want is for A to be actually running before B.  This results in B failing if A fails when that may not be the behavior one wants.

Do I misunderstand the situation?  Is the solution to have A's ExecStart be a foreground operation which blocks systemd if you want service availability-based ordering?

**Comment by arvidjaar** [comment]
@gleventhal 

> Do I misunderstand the situation?

Yes. Ordering is between jobs. `Before=B` in `A` means systemd waits until `A`'s start job has completed before selecting `B`'s start job for execution. What exactly "start job has completed" means depends on service type. Only for `Type=simple` "start job has completed" is mostly equal to "`ExecStart` command was run". Other service types offer more precise means to indicate to systemd that startup has completed.

Same applies to stop job in reverse order, except on stop systemd simply waits for all processes of one service to terminate before continuing with another service.

> service availability-based ordering

systemd has no way to know what service does internally and when it becomes "available". It is up to service process to indicate to systemd when service became "available".  It can do it by creating PID file, by registering D-Bus name or by notifying systemd depending on service type.
