### ISSUE TITLE
kernel-install 90-uki-copy.install fails with `... is missing .efi suffix.`

### ISSUE THREAD

**Issue by 05storm26** [systemd/systemd#26477]
### systemd version the issue has been seen with

core/systemd 253-1 [installed]

### Used distribution

Arch

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

kernel-install

### Expected behaviour you didn't see

`90-uki-copy.install` shouldn't fail when the mkinitcpio hook generates the uki image to the proper place.

### Unexpected behaviour you saw

```
$ sudo kernel-install -v add 6.1.11-hardened1-1-hardened /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz /boot/intel-ucode.img
[...]
+ mkinitcpio -k '6.1.11-hardened1-1-hardened' --kernelimage /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz --microcode /boot/intel-ucode.img -U '/efi/EFI/Linux/46e5b7b51f69426fade60fe0cc165d7a-6.1.11-hardened1-1-hardened.efi'
==> Starting build: 6.1.11-hardened1-1-hardened
  -> Running build hook: [base]
  -> Running build hook: [systemd]
  -> Running build hook: [sd-vconsole]
  -> Running build hook: [kms]
==> WARNING: Possibly missing firmware for module: ast
  -> Running build hook: [sd-plymouth]
  -> Running build hook: [btrfs]
  -> Running build hook: [autodetect]
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: xhci_pci
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [lvm2]
  -> Running build hook: [sd-encrypt]
==> WARNING: Possibly missing firmware for module: qat_4xxx
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
  -> Running build hook: [sd-shutdown]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: /tmp/mkinitcpio.yhhdte
==> Image generation successful
==> Creating unified kernel image: /efi/EFI/Linux/46e5b7b51f69426fade60fe0cc165d7a-6.1.11-hardened1-1-hardened.efi
  -> Using UEFI stub: /usr/lib/systemd/boot/efi/linuxx64.efi.stub
  -> Using cmdline file: /etc/kernel/cmdline
  -> Using os-release file: /etc/os-release
  -> Using microcode image: /boot/intel-ucode.img
==> Unified kernel image generation successful
+/usr/lib/kernel/install.d/90-loaderentry.install add 6.1.11-hardened1-1-hardened /efi/46e5b7b51f69426fade60fe0cc165d7a/6.1.11-hardened1-1-hardened /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz /boot/intel-ucode.img
+/usr/lib/kernel/install.d/90-uki-copy.install add 6.1.11-hardened1-1-hardened /efi/46e5b7b51f69426fade60fe0cc165d7a/6.1.11-hardened1-1-hardened /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz /boot/intel-ucode.img
Error: /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz is missing .efi suffix.
```

### Steps to reproduce the problem

When the layout is set to uki the 90-uki-copy.install fails with `Error: /usr/lib/modules/6.1.11-hardened1-1-hardened/vmlinuz is missing .efi suffix.`, when the initramfs generation generates the uki image directly to the destination `<esp>/EFI/Linux/<target>`. 90-uki-copy shouldn't fail when the mkinitcpio hook generates the uki image to the proper place, and there is nothing to be copied by 90-uki-copy.

**Comment by 05storm26** [comment]
cc @behrmann

**Comment by YHNdnzj** [comment]
IIUC isn't this a mkinitcpio issue? The resulting files should be stored in `$KERNEL_INSTALL_STAGING_AREA` rather than being installed to `esp/EFI/Linux` directly.

**Comment by 05storm26** [comment]
I was under the impression that that is only optional and that the initrd generator can do whatever they want including installing the image to where they wish.

**Comment by behrmann** [comment]
This is something to be fixed in mkinitcpio and is mostly an artifact that we reused the name `uki` for the layout before a systemd version with `90-uki-copy.install` was released, which maybe wasn't the greatest idea, so putting the file into `$KERNEL_INSTALL_STAGING_AREA` didn't make sense, because from there it wouldn't get anywhere. As a workaround until this is fixed I recommend masking `90-uki-copy.intall` in `/etc/kernel/install.d` (make a symlink of the same name pointing to `/dev/null`).

**Comment by 05storm26** [comment]
Okay that works, not sure if there is a mkinitcpio bug about this yet or not. I have added this to the [wiki](https://wiki.archlinux.org/title/Unified_kernel_image#kernel-install)

**Comment by behrmann** [comment]
Cool, thanks! I'll submit a MR to address this to mkinitcpio on Monday.

**Comment by nougad** [comment]
I just created a issue for mkinicpio: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/163

**Comment by behrmann** [comment]
I think this bug can be closed now, since this has a [pending fix downstream](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/207)
