### ISSUE TITLE
systemd 253: cannot start container with init: "Failed to fork: Operation not permitted"

### ISSUE THREAD

**Issue by felixfontein** [systemd/systemd#26474]
### systemd version the issue has been seen with

253 (253-1-arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Init starts up in container (output of `podman run --rm -it archlinux:latest /usr/sbin/init`, which right now uses systemd 252):
```
systemd 252.5-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.

Welcome to Arch Linux!

Initializing machine ID from container UUID.
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Populated /etc with preset unit settings.
Queued start job for default target Graphical Interface.
[  OK  ] Created slice Slice /system/getty.
...
```

### Unexpected behaviour you saw

```
systemd 253-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.

Welcome to Arch Linux!

Initializing machine ID from container UUID.
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Failed to fork: Operation not permitted
[!!!!!!] Failed to start up manager.
Exiting PID 1...
```

### Steps to reproduce the problem

Create an image with the latest systemd (253) in it.

Dockerfile:
```
FROM archlinux:latest
RUN pacman -Syu --noconfirm # so you actually get systemd 253
CMD /usr/sbin/init
```
Build and run with podman:
```sh
podman build -t archlinux-253 .
podman run --rm -it archlinux-253
```
Alternatively, build and run with docker:
```
docker build -t archlinux-253 .
docker run --tmpfs /tmp:exec --tmpfs /run:exec -t archlinux-253 sh -c 'mount -o remount,rw /sys/fs/cgroup/ ; exec /usr/sbin/init'
```
Both produce the same result.

The same seems to happen with Fedora rawhide according to https://bugzilla.redhat.com/show_bug.cgi?id=2165004 (has apparently been using systemd-253~rc1-1.fc38 and systemd-253~rc2-3.fc38). I guess this is a problem with systemd itself and not something specific to Arch Linux or Fedora rawhide, but I couldn't find an issue here, so here we go...

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Output of `podman run --env SYSTEMD_LOG_LEVEL=debug --rm -it archlinux-253`:

systemd 253-1-arch running in system mode (+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Detected first boot.
Kernel version 6.1.12-arch1-1, our baseline is 4.15

Welcome to Arch Linux!

Hostname was already set to <09b6cf300ea9>.
Initializing machine ID from container UUID.
Bind-mounting /run/machine-id on /etc/machine-id (MS_BIND "")...
Failed to mount /run/machine-id (type n/a) on /etc/machine-id (MS_BIND ""): Operation not permitted
Failed to add address 127.0.0.1 to loopback interface: Operation not permitted
Failed to add address ::1 to loopback interface: Operation not permitted
Failed to bring loopback interface up: Operation not permitted
Setting '/proc/sys/net/unix/max_dgram_qlen' to '512'
Failed to bump AF_UNIX datagram queue length, ignoring: Permission denied
Setting '/proc/sys/fs/file-max' to '9223372036854775807'
Setting '/proc/sys/fs/nr_open' to '2147483640'
Failed to bump fs.nr_open, ignoring: Permission denied
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Unified cgroup hierarchy is located at /sys/fs/cgroup.
bpf-firewall: Can't load kernel CGROUP SKB BPF program, BPF firewalling is not supported: Operation not permitted
Can't load kernel CGROUP DEVICE BPF program, BPF device control is not supported: Operation not permitted
bpf-socket-bind: BPF program type cgroup_sock_addr is not supported
restrict-interfaces: BPF program type cgroup_skb is not supported
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: no
Controller 'cpuset' supported: no
Controller 'io' supported: no
Controller 'blkio' supported: no
Controller 'memory' supported: yes
Controller 'devices' supported: no
Controller 'pids' supported: yes
Controller 'bpf-firewall' supported: no
Controller 'bpf-devices' supported: no
Controller 'bpf-foreign' supported: yes
Controller 'bpf-socket-bind' supported: no
Controller 'bpf-restrict-network-interfaces' supported: no
Set up TFD_TIMER_CANCEL_ON_SET timerfd.
Failed to stat /etc/localtime, ignoring: No such file or directory
/etc/localtime doesn't exist yet, watching /etc instead.
bpf-lsm: BPF LSM hook not enabled in the kernel, BPF LSM not supported
Enabling (yes) showing of status (commandline).
Serializing system-environment-generators to memfd.
Successfully forked off '(sd-executor)' as PID 2.
Skipping PR_SET_MM, as we don't have privileges.
Serializing 10-arch to memfd.
Successfully forked off '(direxec)' as PID 3.
/usr/lib/systemd/system-environment-generators/10-arch succeeded.
(sd-executor) succeeded.
Failed to fork: Operation not permitted
[!!!!!!] Failed to start up manager.
Exiting PID 1...
```
```

**Comment by bluca** [comment]
Are you using selinux/apparmor/seccomp or something like that? There's lots of permission denied errors. Try to run it under strace and see what exactly is getting denied.

**Comment by yuwata** [comment]
That should be caused `unshare()` is disabled by seccomp or so.
See ca6ce62d2a437432082b5c6e5d4275d56055510f.

**Comment by yuwata** [comment]
Fix is waiting in #26478.

**Comment by felixfontein** [comment]
@bluca I use neither selinux nor apparmor, and haven't set up anything specific with seccomp. The same problem happens when a similar image is used in Docker on GitHub with ubuntu-latest (no idea what exact kind of environment that is), and it produced the same error in another CI environment (Zuul) as well.

I don't really have any experience with seccomp and strace; I simply ran `strace podman run --env SYSTEMD_LOG_LEVEL=debug --rm -it archlinux-253 > stdout.txt 2> stderr.txt`, the resulting files are [stdout.txt](https://github.com/systemd/systemd/files/10775207/stdout.txt) and [stderr.txt](https://github.com/systemd/systemd/files/10775206/stderr.txt). I couldn't find anything suspicious in it, but as I said, I have no experience, so :shrug: I hope they help.

@yuwata thanks for the quick fix! I'll try to try it out during the next days.

**Comment by bluca** [comment]
> That should be caused by that `clone()` and/or `unshare()` are disabled by seccomp or so. See [ca6ce62](https://github.com/systemd/systemd/commit/ca6ce62d2a437432082b5c6e5d4275d56055510f).

The selinux policy/seccomp filters/apparmor profile should just get updated?

**Comment by yuwata** [comment]
@bluca
Not familiar with LSM, but if it is blocked by seccomp, then I think it is hard to do.
Here, clone() is called by pid1 unconditionally in the very early stage. Unlike the cases that unshare() is called in the forked proceses for creating sandbox environment, currently we have no way to avoid the failure.
Of course, we can introduce an environment variouble or an option in system.conf, but that sounds overkill for me, and not user-friendly.

**Comment by poettering** [comment]
Yeah, we should gracefully fall back to non-namespaced operation if we can't se up the namespace.

**Comment by felixfontein** [comment]
@yuwata sorry it took me so long, but I now managed to build a container image with your PR integrated into the installed systemd, and with it it works fine!

**Comment by bluca** [comment]
> Yeah, we should gracefully fall back to non-namespaced operation if we can't se up the namespace.

Sure, but a bug needs to be opened so that the seccomp filters get fixed in podman - @felixfontein have you done that already?

**Comment by felixfontein** [comment]
@bluca I haven't.

**Comment by poettering** [comment]
> Sure, but a bug needs to be opened so that the seccomp filters get fixed in podman - @felixfontein have you done that already?

I don't think they are broken.

If podman doesn't allow namespaces for a container, that's fine actually. We generally degrade gracefully if namespaces are not available for whatever reason that might be. Because turned off in kernel, or because policy doesn't allow it. Only for the generators we broke this, and we shouldn't.

So yeah, you might argue that the podman's policy is a bit too strict there and they should just allow mount namespacing, but also, we should be compatible with such a policy either way, maybe people don't trust namespacing because the complexity it adds, and we should be able to deal with this, and so far could everywhere – except now here, for a pretty auxiliary thing.

**Comment by bluca** [comment]
Having a fallback is fine, but I'm pretty sure the default policy needs to change too. Policies need to evolve and not remain static, otherwise we'll always be limited by the least common denominator, which is not good. This is a useful thing that should work out-of-the-box.

**Comment by felixfontein** [comment]
@bluca I can create issues for podman and moby/Docker.

I agree that it's better if the filters are updated eventually, but I also agree that they are not broken. Right now it is not possible to use systemd's init process in containers with the default seccomp rules with both podman and Docker, and since you meet all kind of older podman/Docker instances in CI (or other) systems a fallback would be really helpful :)

**Comment by poettering** [comment]
my educated guess is that in particular docker people have no interest in running systemd as payload, hence they certainly are not going to change their policies to accomodate to what systemd would like to make use of.

IIRC they only recently acquired support for running containers in userns, and even then it's totally terrible because they share uid ranges (?), hence they might have plenty reasons to not enable fs namespaces because it would just open more security holes to something that is already a swiss cheese...

but i appreciate your enthusiasm. ;-)

**Comment by felixfontein** [comment]
@poettering I don't really expect much to change on Docker's side, but if nobody reports it to them the chances that something will change are even lower :)

**Comment by felixfontein** [comment]
On the podman side, it looks like this might not be due to seccomp: https://github.com/containers/common/issues/1337#issuecomment-1437238161

**Comment by giuseppe** [comment]
The Podman default seccomp profile doesn't block `clone()`.  I've looked into the strace log and the failure I see is the following:

```
# strace -f -o /tmp/log  podman run  --rm -it archlinux-253:latest /usr/sbin/init
# grep clone.*EPERM /tmp/log 
58200 clone(child_stack=NULL, flags=CLONE_NEWNS|SIGCHLD) = -1 EPERM (Operation not permitted)
# grep CLONE_NEWUSER /tmp/log 
#
```

Podman doesn't grant `CAP_SYS_ADMIN` by default, since I don't see any user namespace created inside the container, I guess at the time of the failure the process still doesn't have `CAP_SYS_ADMIN`.

From the Podman side, if you want to get it working you need to add `CAP_SYS_ADMIN`, either from the host or creating a user namespace for the container:

Just a thought: would it make sense for systemd to create a user namespace first to gain `CAP_SYS_ADMIN` and attempt creating the mount namespace there?

**Comment by poettering** [comment]
> Just a thought: would it make sense for systemd to create a user namespace first to gain `CAP_SYS_ADMIN` and attempt creating the mount namespace there?

without privs we could get a userns but it would be quite restrictive: it could only map its own user and nothing else. Which is unlikely what we want here.

but dunno i doubt it's worth bothering here. the namespace we set up for generators is mostly a thing to track down misbehaving generators that write stuff to places they really shouldn't write stuff to. it's totally OK if we degrade gracefully in very restrictive environments on this. Or in other words: badly behaving LVM generators really shouldn't run in a container anyway, hence it's not really worth locking them into a sandbox there too.

**Comment by bluca** [comment]
> > Just a thought: would it make sense for systemd to create a user namespace first to gain `CAP_SYS_ADMIN` and attempt creating the mount namespace there?
> 
> without privs we could get a userns but it would be quite restrictive: it could only map its own user and nothing else. Which is unlikely what we want here.
> 
> but dunno i doubt it's worth bothering here. the namespace we set up for generators is mostly a thing to track down misbehaving generators that write stuff to places they really shouldn't write stuff to. it's totally OK if we degrade gracefully in very restrictive environments on this. Or in other words: badly behaving LVM generators really shouldn't run in a container anyway, hence it's not really worth locking them into a sandbox there too.

But the user the generator is running under is also the user we want the files to be owned by, no? Ie, it would be root inside the container. So it should work? I'm pretty sure there are many generators that are supposed to be running inside containers

**Comment by MichaIng** [comment]
Sorry for necromancing this issue: Do I understand it correctly that it has been fixed in systemd 254?

We still face the very same issue/error message when trying to boot a Debian Sid or Trixie container, starting with systemd 253, but still with systemd 254 (container side), via `systemd-nspawn` and `qemu-user-static`. Without emulation, it works, and also Debian Bookworm containers (systemd 252) boot successfully with emulation.

To replicate on any Debian or Ubuntu system with a fresh `debootstrap` system:
```sh
sudo apt -y install debootstrap dbus systemd-container qemu-user-static binfmt-support
sudo systemctl restart systemd-binfmt
debootstrap --arch=arm64 --variant=minbase --include=systemd-sysv trixie ./rootfs
systemd-nspawn -bD rootfs
```
=>
```
Spawning container rootfs on /root/rootfs.
Press Ctrl-] three times within 1s to kill container.
systemd 254.1-2 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture arm64.

Welcome to Debian GNU/Linux trixie/sid!

Hostname set to <VM-Trixie>.
Failed to fork off sandboxing environment for executing generators: Invalid argument
[!!!!!!] Failed to start up manager.
Exiting PID 1...
Container rootfs failed with error code 255.
```
Adding `--capability=CAP_SYS_ADMIN` does not help (it is the default anyway) and the same happens when using the `sid` suite, but works well with the `bookworm` suite or when using a natively supported architecture for the system.

Let me know whether I should better create a dedicated issue for this, in case I am not just doing something wrong.
