### ISSUE TITLE
journal: do not leak internal error code

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#26496]
### systemd version the issue has been seen with

253

### CPU architectures issue was seen on

None

### Component

systemd-journald

### Unexpected behaviour you saw

From https://github.com/systemd/systemd/pull/26198#issuecomment-1435793933
```
[ 2988.374664] systemd-journald[328]: /var/log/journal/bd3be28df719f3499cdef198566abc2e/user-1000.journal: Montonic clock jumped backwards relative to last journal entry, rotating.
[ 2988.374673] systemd-journald[328]: Failed to write entry to /var/log/journal/bd3be28df719f3499cdef198566abc2e/user-1000.journal (28 items, 781 bytes), rotating before retrying: Not a XENIX named type file
```

C.f.
https://github.com/systemd/systemd/pull/26198#discussion_r1086761701
https://github.com/systemd/systemd/pull/26198#issuecomment-1436018077

**Comment by neilromig** [comment]
I'm seeing this on my Arch system since systemd 253.

**Comment by jp-wheeler** [comment]
> I'm seeing this on my Arch system since systemd 253.

Arch as well and same message.  Actually swapped out my BIOS battery thinking it might be the culprit! ;)
