### ISSUE TITLE
_COMM field value is only limited within 15 characters

### ISSUE THREAD

**Issue by JonathanKang** [systemd/systemd#2649]
For example, I have a log entry as the picture below shows. It's from systemd-cryptsetup, but the _COMM field value is systemd-cryptse. The value of _COMM field is cut off within 15 characters. Did you design this on perpose? Or it's a issue that needs to be fixed.

![screenshot from 2016-02-18 13-29-55](https://cloud.githubusercontent.com/assets/5607743/13134670/04fb653e-d644-11e5-9b3b-20926f8cc654.png)

**Comment by ohsix** [comment]
it's a kernel limitation on the field length

[ohsix@field ~]$  cat /proc/$(pidof systemd-journald)/comm
systemd-journal

see section 3.6 https://www.kernel.org/doc/Documentation/filesystems/proc.txt

**Comment by ohsix** [comment]
there have been lkml threads about changing the length in the ancient past, it's a mess; if it were to be changed in the future i think another thing like 'comm2' or something would be introduced with a bigger limit; lots of tools would need to be modified to look there for that information

**Comment by JonathanKang** [comment]
@ohsix Okay. Thanks for the reply. If I want to get the full name, I think I have to use another field, for instance SYSLOG_IDENTIFIER.

**Comment by ohsix** [comment]
if you can, the related unit name should be good; paths for ExecStart and stuff have to be absolute, and all the Exec\* entries the unit runs will be linked together, as with a bunch of other metadata

**Comment by JonathanKang** [comment]
What I want is a field that can replace _COMM, the full version of _COMM field exactly. I find that for some entries, related unit name is not a very good option.

**Comment by poettering** [comment]
_COMM= is the kernel process name as exposed in /proc/$PID/comm, or settable with PR_SET_NAME (see prctl(2) for details). The kernel limits that name to 16 bytes, and hence that's all you can use for it.  It's basically the name "top" shows for a process.

Use _CMDLINE= to get the full command line of a process. This can be much longer, and is the name "ps" shows for a process.

There's also _EXE= which just contains the path name of the executable.

There's also SYSLOG_IDENTIFIER= which is a field that programs supply to us, and is not extractedautomatically from the kernel. It usually contains the same information as _COMM= but is not truncated.

Anyway, closing, as there's very little we can do about this. It's a kernel limitation.

**Comment by JonathanKang** [comment]
@poettering Thanks for the information.

Yep. Fine for me to close it.
