### ISSUE TITLE
UKI embedded PCR signature is not accessible in the auto discovered pathes for rootfs unlock

### ISSUE THREAD

**Issue by Faerbit** [systemd/systemd#26490]
### systemd version the issue has been seen with

253

### Used distribution

Archlinux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub, systemd-tmpfiles

### Expected behaviour you didn't see

Embedding a systemd-measure PCR signature in my UKI leading to the signature being unpacked to a location, where it would be picked up automatically when the rootfs is unlocked in the initrd.

### Unexpected behaviour you saw

Rootfs was not unlocked and I needed to enter the password/I needed to specify `tpm2-signature=/.extra/tpm2-pcr-signature.json` in my `/etc/crypttab` in my initrd

### Steps to reproduce the problem

* Deploy UKI with `ukify`
* Boot it
* Be confused

AFAICT what is happening, is that sd-stub is unpacking the embedded signature to `/.extra/tpm2-pcr-signature.json`, where it will be eventually picked up by `systemd-tmpfiles`, moved to `/run/systemd` where it can be auto-discovered by `systemd-cryptsetup`. However looking at `systemd-tmpfiles-setup.service` it seems to me that is not started early enough for it to be available to unlock the rootfs.

**Comment by tempusfugit991** [comment]
i hit the same bug on arch. the .json + .pem files exist in /.extra in the initramfs but are not found by systemd-cryptsetup.
on my system the tmpfiles service does not copy the files to the /run/systemd folder. not in the initramfs and even after complete boot they are not there.

thanks @Faerbit for your workaround!

**Comment by poettering** [comment]
Fix pending in #28125
