### ISSUE TITLE
DefaultStartupMemoryLow is undocumented

### ISSUE THREAD

**Issue by SJrX** [systemd/systemd#26493]
### systemd version the issue has been seen with

latest

### Used distribution

n/a

### Linux kernel version used

n/a

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

The key `DefaultStartupMemoryLow` should be documented

### Unexpected behaviour you saw

It isn't documented

### Steps to reproduce the problem

Look at documentation.

**Comment by SJrX** [comment]
I think that the `DefaultStartupMemoryLow` option was added as part of #26384 but it is not documented.

**Comment by yuwata** [comment]
cc @bluca

**Comment by poettering** [comment]
yeah, system.conf's DEfaultStartupMemoryLow= setting appears not to be documented yet.
