### ISSUE TITLE
Remarkable does not work out of the box, needs config with systemd-networkd

### ISSUE THREAD

**Issue by seanyoung** [systemd/systemd#26517]
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The [remarkable 2](https://remarkable.com/) is a device which presents a usb network interface when plugged in via usb (cdc_ether driver). The remarkable instructions tell you to go http://10.11.99.1/ to download/upload files from the device, which works fine with network manager.

With systemd-networkd, I first need to create a `.network` file like such:
```
[Match]
MACAddress=42:6f:07:e0:8a:6f

[Network]
DHCP=yes
```
This is not very user friendly.

### Unexpected behaviour you saw

remarkable 2 should have it network interface configured by default, just like with network manager.

### Steps to reproduce the problem

- Plug remarkable in
- go to http://10.11.99.1/  
- not working

`networkctl` shows `unconfigured`

**Comment by yuwata** [comment]
Unfortunately, we cannot change the policy, that is, defaults to no interface managed.
You should have /usr/lib/systemd/network/80-ethernet.network.example. Please copy it to /etc/systemd/network.
See also 9bd4181ef53907997d117e9f218c8f6ed7e40648 and the discussion at #3998.
