### ISSUE TITLE
build failure when linking test-dns-packet

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#2651]
In most (but _not_ all) cases, building master with `-j4` fails when trying to link `test-dns-packet`:

```
libtool: link: gcc -pipe -Wall -Wextra -Wundef -Wformat=2 -Wformat-security -Wformat-nonliteral -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong -fPIE --param=ssp-buffer-size=4 -Werror=shadow -flto -ffunction-sections -fdata-sections -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wl,--gc-sections -Wl,--no-undefined -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -Wl,-fuse-ld=gold -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -o test-dns-packet  -Wl,--as-needed
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
Makefile:12109: recipe for target 'test-dns-packet' failed
make[4]: *** [test-dns-packet] Error 1
```

This can be seen in e. g. https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160218_074949@/log.gz

I'm not sure why this doesn't happen in semaphore. Semaphore runs in Ubuntu 14.04 LTS, while the above tests run in Ubuntu 16.04 LTS, so it could be a bug in a newer gcc/binutils/toolchain. But I've ran a few tests in a similar environment two weeks ago and they never ran into this.

I'm investigating and bisecting.

**Comment by filbranden** [comment]
Hi Martin,

It's weird, looking at the command line you pasted, looks like it's including no objects in the link... When I run this with V=1 I get:

```
libtool: link: gcc -pipe -Wall [...] -o test-dns-packet src/resolve/test_dns_packet-test-dns-packet.o src/resolve/test_dns_packet-resolved-dns-dnssec.o src/resolve/test_dns_packet-resolved-dns-packet.o src/resolve/test_dns_packet-resolved-dns-rr.o src/resolve/test_dns_packet-resolved-dns-answer.o src/resolve/test_dns_packet-resolved-dns-question.o src/resolve/test_dns_packet-dns-type.o  ./.libs/libshared.a -lcap -lrt -lm -lresolv -llzma -llz4 -lgcrypt -lgpg-error -lacl -lidn -lseccomp -pthread
```

(A bunch of objects, shared libs and system libs.)

While you're getting:

```
libtool: link: gcc -pipe -Wall [...] -o test-dns-packet  -Wl,--as-needed
```

(Two spaces, indicating a possibly empty variable, and not sure where the last `-Wl,--as-needed` is coming from.)

My generated Makefile has:

```
am__objects_16 = src/resolve/test_dns_packet-resolved-dns-dnssec.$(OBJEXT) \
        src/resolve/test_dns_packet-resolved-dns-packet.$(OBJEXT) \
        src/resolve/test_dns_packet-resolved-dns-rr.$(OBJEXT) \
        src/resolve/test_dns_packet-resolved-dns-answer.$(OBJEXT) \
        src/resolve/test_dns_packet-resolved-dns-question.$(OBJEXT) \
        src/resolve/test_dns_packet-dns-type.$(OBJEXT)
am_test_dns_packet_OBJECTS = src/resolve/test_dns_packet-test-dns-packet.$(OBJEXT) \
        $(am__objects_16)
test_dns_packet_OBJECTS = $(am_test_dns_packet_OBJECTS)
...
test-dns-packet$(EXEEXT): $(test_dns_packet_OBJECTS) $(test_dns_packet_DEPENDENCIES) $(EXTRA_test_dns_packet_DEPENDENCIES) 
        @rm -f test-dns-packet$(EXEEXT)
        $(AM_V_CCLD)$(LINK) $(test_dns_packet_OBJECTS) $(test_dns_packet_LDADD) $(LIBS)
```

Can you check what yours has? Or share the generated Makefile (mine was with automake 1.15) and I could have a look to try to troubleshoot that.

BTW, I tried to access your log.gz, but it seems it's a private IP in 10.24.x.x network, maybe copy it somewhere else like a GitHub Gist?

Cheers!
Filipe

**Comment by filbranden** [comment]
Looking at [this URL you posted in #2641](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160217_092934@/log.gz) now for the logs.

It looks like `test-dns-packet` builds fine under build-deb but fails in build-udeb. Is there something specific about build-udeb that could be causing this failure? I know I've had problems with it before and had to disable it (but unfortunately don't recall all the details.) Can you maybe disable build-udeb for now?

**Comment by filbranden** [comment]
And now looking at `Makefile.in` I see this:

```
@ENABLE_RESOLVED_TRUE@am__objects_16 = src/resolve/test_dns_packet-resolved-dns-dnssec.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  src/resolve/test_dns_packet-resolved-dns-packet.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  src/resolve/test_dns_packet-resolved-dns-rr.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  src/resolve/test_dns_packet-resolved-dns-answer.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  src/resolve/test_dns_packet-resolved-dns-question.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  src/resolve/test_dns_packet-dns-type.$(OBJEXT)
@ENABLE_RESOLVED_TRUE@am_test_dns_packet_OBJECTS = src/resolve/test_dns_packet-test-dns-packet.$(OBJEXT) \
@ENABLE_RESOLVED_TRUE@  $(am__objects_16)
test_dns_packet_OBJECTS = $(am_test_dns_packet_OBJECTS)
```

So looks like `--disable-resolved` is what is causing this failure. I'll try to reproduce that and see if we can disable building tests that depend on it... Hang on.

**Comment by filbranden** [comment]
PR #2652 should fix it. Looks like it's queued on Ubuntu CI, so we'll know for sure then :-)

Cheers!
Filipe

**Comment by martinpitt** [comment]
Wow, I just go to a dentist appointment, and you figured it all out already, many thanks @filbranden!

Indeed I don't actually intend to build udebs, that's just a waste of time. I'll ask @zonque to adjust the test parameters to disable that, but only after landing PR #2652 (as that's an actual build system bug fix).

**Comment by martinpitt** [comment]
@filbranden: I edited the description to use the public URL, whoops :)

**Comment by filbranden** [comment]
Hey @martinpitt 

I'm happy to help! I've been busy with other stuff so not a lot of time to polish the big stuff I have on the back burner (hoping to get back to it soon) but build system is certainly what I know best and it didn't really take me long to figure this one out (sorry for the rambling updates) :-D

Building udeb has the advantage of testing a "minimal" configuration but I can see how it maybe doesn't belong in Ubuntu CI. Perhaps it would be a good fit for Semaphore CI, not sure how much we care about whether it still builds with everything disabled and whether we care about finding weird combinations of flags that end up being incompatible... Anyways, I'll let that for you guys to figure out.

And I hope dentist wasn't too painful :-)

Cheers,
Filipe

**Comment by martinpitt** [comment]
> Building udeb has the advantage of testing a "minimal" configuration but I can see how it maybe doesn't belong in Ubuntu CI. Perhaps it would be a good fit for Semaphore CI,

Right, @zonque and I discussed that a bit, and indeed it would be more efficient to do a `--disable-all` run in semaphore, where it parallelizes better. The autopkgtests already take long enough as they are.
