### ISSUE TITLE
systemctl restart xxx.socket failed: Address already in use

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#26512]
When restarting the socket, first stop (close fd), release the address, and then rebind at start (bind)
However, close is an asynchronous function. The work of releasing fd will not be executed immediately. It will be released only after it is scheduled by the CPU.
If the CPU is not scheduled to close (in the kernel) and the start socket has started, it will report
“Address already in use”
Whether the socket can have the same function as the service as Restart=on failure

**Comment by poettering** [comment]
This is not a useful bug report. Please fill in the provided form, we ask various questions there for a reason.

We generally use SO_REUSEADDR wen binding IP sockets to avoid this issue.
