### ISSUE TITLE
Add button swap for Logitech Lift Vertical mouse (left-handed)

### ISSUE THREAD

**Issue by vit-zikmund** [systemd/systemd#26523]
### systemd version the issue has been seen with

251.11-2.fc37

### Used distribution

Fedora 37

### Linux kernel version used

6.1.9-200.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Left button being registered as left, right button being right.

### Unexpected behaviour you saw

Left button clicks as right, right button clicks as left.
This is happening while the GNOME's primary mouse button being set to 'Left' (left-handed setting disabled) and all other pointer devices (other mouse, touchpad) acting properly.

### Steps to reproduce the problem

There's not much to it, I guess. The mouse buttons seem to be swapped out of the box. `evtest` proved the scancodes are flipped (90001 is sent for the right button and 90002 for the left, but normally it's the other way around).

This hwdb rule fixed to problem, I'd even make a PR, but unsure which file this should go into:
```
$ cat /etc/udev/hwdb.d/71-logitech-lift-left.hwdb
# Logitech USB Receiver Mouse (Lift Vertical - left-handed)
# /sys/class/input/eventXX/device/modalias 
# input:b0003v046DpC548e0111-e0,1,2,4,k110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,r0,1,6,8,B,C,am4,lsfw
evdev:input:b0003v046DpC548e0111*
 KEYBOARD_KEY_90001=btn_right
 KEYBOARD_KEY_90002=btn_left
```

**Comment by yuwata** [comment]
Please apply the change into 60-keyboard.hwdb, and submit as a PR.

**Comment by vit-zikmund** [comment]
Just submitted https://github.com/systemd/systemd/pull/26536. We should close this.
