### ISSUE TITLE
systemd-nspawn container's networkd show Failed to Increase Receive Buffer Size 

### ISSUE THREAD

**Issue by Handsome1080P** [systemd/systemd#26538]
### systemd version the issue has been seen with

253

### Used distribution

arch

### Linux kernel version used

6.1

### CPU architectures issue was seen on

None

### Component

systemd-nspawn,systemd-networkd

### Unexpected behaviour you saw

![image](https://user-images.githubusercontent.com/13675031/220602437-58bd82c2-b7e2-4013-811b-83e57e780147.png)

**Comment by yuwata** [comment]
Could you provide the relevent .nspawn file or command line of systemd-nspawn you use?
Also, could you show the capability of systemd-networkd in the nspawn container? I guess `sudo cat /proc/PID_OF_NETWORKD/status | grep Cap` should be enough.

**Comment by Handsome1080P** [comment]
@yuwata This is
![image.png](https://s2.loli.net/2023/02/22/nGuTxtdBkEQa7c4.png)
![image.png](https://s2.loli.net/2023/02/22/STlGR4yE8aYpCvz.png)
![image.png](https://s2.loli.net/2023/02/22/lpY51DJxAUybQRF.png)

**Comment by Handsome1080P** [comment]
![image.png](https://s2.loli.net/2023/02/22/bDaIPp2sOFvhXji.png)

**Comment by yuwata** [comment]
Cannot reproduce the issue. Maybe, SELinux issue??

**Comment by Handsome1080P** [comment]
> Cannot reproduce the issue. Maybe, SELinux issue?? Please try to reproduce the issue without SELinux.

Closed,bcz it out-of-date
