### ISSUE TITLE
systemctl edit systemd-nspawn@XXX Aborted (core dumped)

### ISSUE THREAD

**Issue by Handsome1080P** [systemd/systemd#26537]
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1.8-arch1-1 

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Unexpected behaviour you saw

> [root@JohnServer test]# systemctl edit systemd-nspawn@Media
free(): double free detected in tcache 2
Aborted (core dumped)

CoreDump:
![image.png](https://s2.loli.net/2023/02/22/ayMr1A4bYmepBRc.png)

**Comment by YHNdnzj** [comment]
Already fixed in https://github.com/systemd/systemd/pull/26483

**Comment by Handsome1080P** [comment]
> Already fixed in #26483

ok,when will have a update?
