### ISSUE TITLE
Double free error on instance unit edit

### ISSUE THREAD

**Issue by ndroppo** [systemd/systemd#26531]
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1.12-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

`systemctl edit foo@1.service` opens drop-in file in editor for instance 1 of `foo@.service`

### Unexpected behaviour you saw

returns 
`free(): double free detected in tcache 2`
`Aborted (core dumped)`
and creates `/etc/systemd/system/foo@1.service.d/` directory but leaves it empty.

### Steps to reproduce the problem

The first time this occurred I had manually copied an `override.conf` file from another instance of the same template service. When I got this error I assumed it was because of a dirty copy so I deleted the offending `.d` directory and tried some more troubleshooting steps up to and including reinstalling systemd. The error persists every time I try to edit an instance unit. Normal units and template units still edit fine.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Feb 21 15:50:18 <hostname> systemd[1]: Started Process Core Dump (PID 684/UID 0).
Feb 21 15:50:18 <hostname> systemd-coredump[685]: Process 683 (systemctl) of user 0 dumped core.
                                                  
                                                  Stack trace of thread 683:
                                                  #0  0x00007f61fe4a08ec n/a (libc.so.6 + 0x878ec)
                                                  #1  0x00007f61fe451ea8 raise (libc.so.6 + 0x38ea8)
                                                  #2  0x00007f61fe43b53d abort (libc.so.6 + 0x2253d)
                                                  #3  0x00007f61fe43c29e n/a (libc.so.6 + 0x2329e)
                                                  #4  0x00007f61fe4aa657 n/a (libc.so.6 + 0x91657)
                                                  #5  0x00007f61fe4ac9d7 n/a (libc.so.6 + 0x939d7)
                                                  #6  0x00007f61fe4aee63 __libc_free (libc.so.6 + 0x95e63)
                                                  #7  0x000055c7a27fa1a4 n/a (systemctl + 0x1b1a4)
                                                  #8  0x000055c7a27ed0cc n/a (systemctl + 0xe0cc)
                                                  #9  0x00007f61fe43c790 n/a (libc.so.6 + 0x23790)
                                                  #10 0x00007f61fe43c84a __libc_start_main (libc.so.6 + 0x2384a)
                                                  #11 0x000055c7a27ee7d5 n/a (systemctl + 0xf7d5)
                                                  ELF object binary architecture: AMD x86-64
Feb 21 15:50:18 <hostname> systemd[1]: systemd-coredump@7-684-0.service: Deactivated successfully.
```

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/26483
