### ISSUE TITLE
sd_event_loop not processing timers if boot_id is not available

### ISSUE THREAD

**Issue by luker128** [systemd/systemd#26549]
### systemd version the issue has been seen with

systemd 252 (252.4-1ubuntu1)

### Used distribution

Ubuntu Lunar Lobster

### Linux kernel version used

5.19.0-31-generic

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Timers added by  sd_event_add_time() were not handled in sd_event_loop() at expected time.

### Unexpected behaviour you saw

Event handlers called couple of minutes later than requested.

### Steps to reproduce the problem

I've identified two prerequisites for this bug to manifest itself:

1. The issue was originally observed for a service that was started at boot time, and added timers early in it's startup. This resulted in relatively low values of 'usec' parameter for in sd_evet_add_time() call (less than 30 000 000 us from boot). 
2. Due to it's AppArmor profile service was denied access to **/proc/sys/kernel/random/boot_id** 

Following is a minimal program that I managed to reproduce the problem with.
  
```
#include <systemd/sd-event.h>

int timerHandler(sd_event_source *timerEvent, uint64_t usec, void *userdata)
{
    sd_event* event = sd_event_source_get_event(timerEvent);
    sd_event_exit(event, 0);
    return 0;
}

int main(int argc, char** argv)
{
    uint64_t wakeAt = 10000000;
    sd_event* event;
    sd_event_source* timer;
    sd_event_default(&event);
    sd_event_add_time(event, &timer, CLOCK_MONOTONIC, wakeAt, 0, timerHandler, 0);
    sd_event_loop(event);
    return 0;
}
```

In order to simulate denied access to boot_id I used following strace invocation:
> strace -P /proc/sys/kernel/random/boot_id -e inject=file:error=EACCES ./a.out

Expected behaviour is to terminate immediately (as requested wake up time is most probably in the past).
When run with this command program doesn't terminate (or at least not within seconds).

The issue is most probably due to missing handling of sd_id128_get_boot() errors in initialize_perturb() in sd-event.c.

**Comment by yuwata** [comment]
Fix is waiting in #26554.
