### ISSUE TITLE
udevd: document that using .link's Name= setting with names such as eth0 means racing against the kernel and is a bad idea

### ISSUE THREAD

**Issue by vindicatorr** [systemd/systemd#2657]
```
$ uname -r
4.4.0+
$ systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

$ journalctl
...
Feb 18 15:49:36 server.lan kernel: ax88179_178a 4-1.1.3:1.0 eth0: register 'ax88179_178a' at usb-xhci-hcd.6.auto-1.1.3, ASIX AX88179 USB 3.0 Gigabit Ethernet,
Feb 18 15:49:36 server.lan kernel: usbcore: registered new interface driver ax88179_178a
Feb 18 15:49:36 server.lan kernel: usb 5-1: reset high-speed USB device number 2 using xhci-hcd
Feb 18 15:49:36 server.lan kernel: r8152 5-1:1.0 eth1: v1.08.2
Feb 18 15:49:36 server.lan kernel: usbcore: registered new interface driver r8152
Feb 18 15:49:36 server.lan kernel: usbcore: registered new interface driver cdc_ether
...
Feb 18 15:49:33 server.lan systemd-udevd[1789]: Error changing net interface name 'eth1' to 'eth0': File exists
Feb 18 15:49:33 server.lan systemd-udevd[1789]: could not rename interface '3' from 'eth1' to 'eth0': File exists
Feb 18 15:49:33 server.lan systemd-udevd[1791]: Error changing net interface name 'eth0' to 'eth1': File exists
Feb 18 15:49:33 server.lan systemd-udevd[1791]: could not rename interface '2' from 'eth0' to 'eth1': File exists
...
$ cat /etc/udev/rules.d/10-network.rules 
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="<r8152=sanitized>", NAME="eth0"
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="<ax88179_178a=sanitized>", NAME="eth1"
```

Looks to be a race-condition:
1) Kernel sets interface names early without any knowledge/care of udev rules.
2a) Device r8152 is onboard and IS defined as eth0 in udev rules
2b) Device ax88179_178a is connected to a usb port and IS defined as eth1 in udev rules

In the meantime, I changed the udev names by prepending them with "custom_"

**Comment by arvidjaar** [comment]
> Looks to be a race-condition

It is race condition. In the past udev attempted to resolve it. This code was explicitly removed from udev a long time ago. Use different namespace that does not conflict with default enumeration (like net0, net1, ...) - that is what udev does today by default.

**Comment by vindicatorr** [comment]
Got it. I must have just been lucky up to this point.

I'm using an ARM device and I guess it just doesn't use the same naming scheme as my AMD64 system.
Odd that isn't even trying to name it with the bus location or MAC address.
If you feel that oddity isn't enough to keep this issue open, feel free to close it. Otherwise, I can run some tests for you.

I will try systemd-link files again, but like you said, using a different namespace.

**Comment by poettering** [comment]
You are racing against the kernel there. Use different names than "eth0", "eth1" and so on, otherwise this will always be racy.

**Comment by mjmeehan** [comment]
Would configuring the kernel to use the newer bios/device location naming also solve the problem, by causing the kernel to avoid the ethX namespace? As in, if I pass biosdevname=1, are the new-style interface names set by the kernel, or by udev later?

**Comment by guilhermepiccoli** [comment]
@poettering : Is this documented somewhere? Thanks in advance!

**Comment by poettering** [comment]
> You are racing against the kernel there. Use different names than "eth0", "eth1" and so on, otherwise this will always be racy.

Yeah, we should really document this better, maybe in network.link(5)
