### ISSUE TITLE
systemd-logind

### ISSUE THREAD

**Issue by nehuby** [systemd/systemd#26583]
### systemd version the issue has been seen with

last

### Used distribution

Arch

### Linux kernel version used

Last

### CPU architectures issue was seen on

None

### Component

systemd, systemd-logind

### Expected behavior you didn't see

I don't want my laptop to go to sleep

### Unexpected behavior you saw

Laptop goes to sleep and shuts down

### Steps to reproduce the problem

Leave the laptop alone

**Comment by leophys** [comment]
You might mask the suspend target
```
sudo systemctl mask suspend.target
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
> You might mask the suspend target
> 
> ```
> sudo systemctl mask suspend.target
> ```

that's such a bad idea. don't.

**Comment by leophys** [comment]
> > You might mask the suspend target
> > ```
> > sudo systemctl mask suspend.target
> > ```
> 
> that's such a bad idea. don't.

I am trying to understand why, maybe because this will prevent from working all the units that have that target as `WantedBy` in the `[Install]` section?

I posted this because that is what I do with my laptop, and it achieves the aim :confused:

**Comment by leophys** [comment]
> > > You might mask the suspend target
> > > ```
> > > sudo systemctl mask suspend.target
> > > ```
> > 
> > 
> > that's such a bad idea. don't.
> 
> I am trying to understand why, maybe because this will prevent from working all the units that have that target as `WantedBy` in the `[Install]` section?
> 
> I posted this because that is what I do with my laptop, and it achieves the aim 😕

To the internet stranger who might land here, sometime in the future, I want to share with you why this is a bad idea.

When you mask a target you don't disable it, you are just preventing systemd to enter it (forgive if the words are wrong, I am no systemd domain expert, just a user). The thing I didn't realize is that, if you trigger a condition where systemd wants to enter the target that you masked, as long as the condition persists systemd will loop and try to enter it. This happened to me when I masked `suspend.target` and closed the lid of the laptop: it ate CPU cycles incessantly trying to enter the suspend state.

I think that the right way to control the behavior of suspension is through `logind.conf`:
 - https://www.freedesktop.org/software/systemd/man/latest/logind.conf.html#HandlePowerKey=
 - https://www.freedesktop.org/software/systemd/man/latest/logind.conf.html#HandlePowerKey=
