### ISSUE TITLE
Ноутбук уходит в сон

### ISSUE THREAD

**Issue by nehuby** [systemd/systemd#26581]
### systemd version the issue has been seen with

последняя

### Used distribution

Арч

### Linux kernel version used

Последняя

### CPU architectures issue was seen on

None

### Component

systemd, systemd-logind

### Expected behaviour you didn't see

Хочу чтобы ноутбук не уходил в сон

### Unexpected behaviour you saw

Ноутбук уходит в сон и отключается

### Steps to reproduce the problem

Отсавить ноутбук в покое

**Comment by yuwata** [comment]
Sorry, please file in English.
