### ISSUE TITLE
Wrong (unrelated) error message when masking user's `default.target`

### ISSUE THREAD

**Issue by LEdoian** [systemd/systemd#26589]
### systemd version the issue has been seen with

253-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When executing `systemctl --user get-default` with `default.target` masked, the output should mention what would happen. If it really is not possible to find the default target, an explanation or relevant error message should be output. As a last resort, the error message should not look like a failed syscall when that is not the case.

### Unexpected behaviour you saw

The output is `Failed to get default target: Operation not possible due to RF-kill`. This is the case even in a VM with no RF-kill capabilities, no WiFi device, etc.

Moreover the part after the colon looks like a syscall failed with `ERFKILL`, yet this errno is quite unlikely to happen in a minimal virtual machine.

### Steps to reproduce the problem

1. `systemctl --user mask default.target` (or whatever the default target is)
2. `systemctl --user get-default`
3. Read the output

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
running_in_chroot(): Permission denied
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/user/1001/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetDefaultTarget cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=System.Error.ERFKILL error-message=Operation not possible due to RF-kill
Failed to get default target: Operation not possible due to RF-kill
Bus n/a: changing state RUNNING → CLOSED
```

**Comment by dtardon** [comment]
Apparently #22646 has been forgotten by all, including myself...
