### ISSUE TITLE
missing specifiers in user.conf

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#26596]
### Component

systemd

### Is your feature request related to a problem? Please describe

A subset of common specifiers are available to `ManagerEnvironment=` in `~/.config/systemd/user.conf`, detailed in `systemd-system.conf(5)`. Absent from the list is the user name and user home specifiers, which I would like to use to set the value of XDG_CONFIG_DIRS in the user manager's environment so that it can be used for unit path lookup exactly as described in `systemd.unit(5)`. Specifically, I'd like to include a path like `$HOME/.hostconfig/$HOST`. The `%H` hostname specifier is available, but no `%h` "user home dir" spcecifier as is available to unit files.

The discussion in this issue seems related #1476, however in this case I'm interested in the `~/.config/systemd/user.conf` file, where I think it should in principle be possible to retrieve the user's $HOME, especially since the file itself resides in $HOME and we are currently parsing it.

### Describe the solution you'd like

Please support the `%h` "user home dir" common specifier for the ManagerEnvironment= field of `~/.config/systemd/user.conf`. I made a brief attempt at this myself in `config_parse_environ` but i'm not sure how to get at the appropriate scope.

### Describe alternatives you've considered

I haven't found any alternative method to set a value derived from $HOME in user.conf.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by rpigott** [comment]
Actually, would this be enough?

```diff
diff --git a/src/core/load-fragment.c b/src/core/load-fragment.c
index d4a874eafa5c..c7a55ead8127 100644
--- a/src/core/load-fragment.c
+++ b/src/core/load-fragment.c
@@ -2743,6 +2743,13 @@ int config_parse_environ(
                 return 0;
         }
 
+        const Specifier table[] = {
+                COMMON_SYSTEM_SPECIFIERS,
+                COMMON_TMP_SPECIFIERS,
+                {'h', specifier_user_home, NULL}
+        };
+
+
         for (const char *p = rvalue;; ) {
                 _cleanup_free_ char *word = NULL, *resolved = NULL;
 
@@ -2760,7 +2767,7 @@ int config_parse_environ(
                 if (u)
                         r = unit_env_printf(u, word, &resolved);
                 else
-                        r = specifier_printf(word, sc_arg_max(), system_and_tmp_specifier_table, NULL, NULL, &resolved);
+                        r = specifier_printf(word, sc_arg_max(), table, NULL, NULL, &resolved);
                 if (r < 0) {
                         log_syntax(unit, LOG_WARNING, filename, line, r,
                                    "Failed to resolve specifiers in %s, ignoring: %m", word);
```

**Comment by yuwata** [comment]
Please submit the change as a PR, and let's discuss about that in the PR page.
