### ISSUE TITLE
'Domains=' in resolved.conf not recognised. 'Domains=' in .network file with static IP not reflected in /etc/resolv.conf

### ISSUE THREAD

**Issue by vinaykul** [systemd/systemd#2659]
Hi, 

We have run into a couple of potential issues and I could not find another issues thread about this. So I'm wondering if this is an issue or if I'm misconfiguring somehow. Please read:

1) systemd-228 documentation says it now supports setting "Domains=foo.com" in /etc/systemd/resolved.conf file. Please see: https://www.freedesktop.org/software/systemd/man/resolved.conf.html

However, resolved does not appear to recognize it. Am I misconfiguring this somehow?
![screen shot 2016-02-18 at 4 05 15 pm](https://cloud.githubusercontent.com/assets/12750645/13162373/6ba148b6-d659-11e5-8315-242a131e3c82.png)
2) When Domains is configured with static IP, this does not reflect in /etc/resolv.conf. networkctl status does show it though. And this works if I use DHCP.
![screen shot 2016-02-18 at 4 19 07 pm](https://cloud.githubusercontent.com/assets/12750645/13162708/642784fe-d65b-11e5-9e2b-c3826ba029e9.png)
Are these known issues? If yes, are there any workarounds? (I tried a lot of combinations of the configuration options to get the search string to show up in /etc/resolv.conf to no avail)

Thanks,
Vin

**Comment by poettering** [comment]
Domains= is a v229 feature, it's not available in v228. The documentation available online is the one from the most recently released version.

**Comment by poettering** [comment]
And the /etc/resolv.conf logic has changed substantially in v229 too. Please try with v229. Closing hence. Feel free to reopen if this doesn't work with v229 either.
