### ISSUE TITLE
syslog.socket in failed state after entering emergency mode

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#266]
When entering emergency mode e.g. due to a wrong fstab entry, I get the following log failure for syslog.socket:

```
Jun 17 18:29:00 debian systemd[1]: syslog.socket: Failed to queue service startup job (Maybe the service file is missing or not a non-template unit?): Transaction is destructive.
Jun 17 18:29:00 debian systemd[1]: syslog.socket: Unit entered failed state.
```

I'm using ForwardToSyslog=yes and rsyslog is installed and configured for socket forwarding mode.

Afaics, syslog.socket is active when emergency.service is activated. This triggers a log message and a start attempt for rsyslog.service. Since this would conflict with the ongoing transaction, the start request fails and syslog.socket is marked as failed.

A simple solution (which we have shipped in Debian for a while), is to add 

```
Conflicts=syslog.socket
```

to emergency.service. This ensures that syslog.socket is stopped when emergency mode is entered.
For systems, which use rsyslog-journal (i.e.  ForwardToSyslog=no and a syslogger which pulls from the journal directly), this is a nop.

I can prepare a PR for this issue, but wanted to gather some feedback first, if this is the right approach.

**Comment by arvidjaar** [comment]
openSUSE is using the same as well, so my only comment would be that it is incomplete. Any other third party unit could have the same behavior.

Can we detect that unit cannot be started due to irreversible transaction and somehow fail gracefully?

**Comment by mbiebl** [comment]
@arvidjaar So far I haven't seen another unit triggering this particular issue, so the explicit Conflicts was sufficient.
But you are right that this points at a more general problem and if a more general solution can be found, even better.

**Comment by martinpitt** [comment]
This breaks emergency mode quite hard with `ForwardToSyslog=yes`, does not break the default `ForwardToSyslog=no`, and has been proven for a long time in production. I think this is harmless and important enough to apply upstream; I'll send a PR for this.

**Comment by fbuihuu** [comment]
hmm I don't see why sockets.target is activated when entering in emergency mode. I just tested here and it isn't.

However I can see another related issue when using the emergency mode: as soon as I start a unit that pulls in the sockets.target then the emergency shell is killed. But I don't think your patch helps in this case.

**Comment by arvidjaar** [comment]
@fbuihuu 

> hmm I don't see why sockets.target is activated when entering in emergency mode

It is not activated _when_ entering emergency mode; rather it remains active. In the past emergency mode was called with isolate which caused everything else to be stopped; commit https://github.com/systemd/systemd/commit/80cfe9e163b1c92f917e0a5e053b148fca790677 changed it to simply call emergency.target leaving everything that had been started previously active, thus exposing this issue.

**Comment by mbiebl** [comment]
@fbuihuu to trigger it, simply add a faulty entry to /etc/fstab.
I suppose you explicitly started emergency mode via the kernel command line switch. In that case syslog.socket is indeed no started.
One could argue, that this is a bug on its own.

**Comment by fbuihuu** [comment]
@arvidjaar @mbiebl yep I thought that emergency was triggered via the kernel command line switch that's the reason why I didn't see the issue.

@mbiebl I just realized that emergency unit can only be used to debug very low-level units. As soon as a socket unit or a service (with DefaultDependencies=yes) is started then sysinit.target will be pull in and will kill emergency.service.
