### ISSUE TITLE
Logitech Wireless Mouse detected as tablet

### ISSUE THREAD

**Issue by holzgeist** [systemd/systemd#26600]
### systemd version the issue has been seen with

253

### Used distribution

Arch linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

Being able to use my mouse

### Unexpected behaviour you saw

Logitech Wireless Mouse was detected as tables. This meant that the mouse pointer wasn't shown, rendering my desktop machine a keyboard-only box. This was reported by someone else here too (with additional infos): https://bbs.archlinux.org/viewtopic.php?id=283719

I could bisect the issue to #25866, which looks like a relevant candidate to me

### Steps to reproduce the problem

* Upgrade to systemd >=v253
* try to use logitech wireless mouse

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ lsusb
...
Bus 003 Device 003: ID 046d:c51b Logitech, Inc. V220 Cordless Optical Mouse for Notebooks
...
```

**Comment by holzgeist** [comment]
@redstrate is there a way to further refine the detection of mouse vs tablet?
I can provide more information on hardware if someone provides me with the commands I have to run :smile:

**Comment by holzgeist** [comment]
Here you go:
```
/dev/input/event16:	Logitech Wireless Mouse PID:0080
Select the device event number: 16
Recording to 'stdout'.
# libinput record
version: 1
ndevices: 1
libinput:
  version: "1.22.1"
  git: "unknown"
system:
  kernel: "6.1.12-arch1-1"
  dmi: "dmi:bvnAmericanMegatrendsInc.:bvrF5:bd05/30/2014:br4.6:svnGigabyteTechnologyCo.,Ltd.:pnZ97P-D3:pvrTobefilledbyO.E.M.:rvnGigabyteTechnologyCo.,Ltd.:rnZ97P-D3:rvrx.x:cvnGigabyteTechnologyCo.,Ltd.:ct3:cvrToBeFilledByO.E.M.:skuTobefilledbyO.E.M.:"
devices:
- node: /dev/input/event16
  evdev:
    # Name: Logitech Wireless Mouse PID:0080
    # ID: bus 0x3 vendor 0x46d product 0x80 version 0x111
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 256 (BTN_0)
    #   Event code 257 (BTN_1)
    #   Event code 258 (BTN_2)
    #   Event code 259 (BTN_3)
    #   Event code 260 (BTN_4)
    #   Event code 261 (BTN_5)
    #   Event code 262 (BTN_6)
    #   Event code 263 (BTN_7)
    #   Event code 272 (BTN_LEFT)
    #   Event code 273 (BTN_RIGHT)
    #   Event code 274 (BTN_MIDDLE)
    #   Event code 275 (BTN_SIDE)
    #   Event code 276 (BTN_EXTRA)
    #   Event code 277 (BTN_FORWARD)
    #   Event code 278 (BTN_BACK)
    #   Event code 279 (BTN_TASK)
    # Event type 2 (EV_REL)
    #   Event code 0 (REL_X)
    #   Event code 1 (REL_Y)
    #   Event code 6 (REL_HWHEEL)
    #   Event code 8 (REL_WHEEL)
    #   Event code 11 (REL_WHEEL_HI_RES)
    #   Event code 12 (REL_HWHEEL_HI_RES)
    # Event type 4 (EV_MSC)
    #   Event code 4 (MSC_SCAN)
    # Properties:
    name: "Logitech Wireless Mouse PID:0080"
    id: [3, 1133, 128, 273]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [256, 257, 258, 259, 260, 261, 262, 263, 272, 273, 274, 275, 276, 277, 278, 279] # EV_KEY
      2: [0, 1, 6, 8, 11, 12] # EV_REL
      4: [4] # EV_MSC
    properties: []
  hid: [
    0x05, 0x01, 0x09, 0x02, 0xa1, 0x01, 0x85, 0x02, 0x09, 0x01, 0xa1, 0x00, 0x05, 0x09, 0x19, 0x01, 
    0x29, 0x08, 0x15, 0x00, 0x25, 0x01, 0x95, 0x08, 0x75, 0x01, 0x81, 0x02, 0x05, 0x01, 0x16, 0x01, 
    0xf8, 0x26, 0xff, 0x07, 0x75, 0x0c, 0x95, 0x02, 0x09, 0x30, 0x09, 0x31, 0x81, 0x06, 0x15, 0x81, 
    0x25, 0x7f, 0x75, 0x08, 0x95, 0x01, 0x09, 0x38, 0x81, 0x06, 0x05, 0x0c, 0x0a, 0x38, 0x02, 0x95, 
    0x01, 0x81, 0x06, 0xc0, 0xc0, 0x06, 0x00, 0xff, 0x09, 0x01, 0xa1, 0x01, 0x85, 0x10, 0x75, 0x08, 
    0x95, 0x06, 0x15, 0x00, 0x26, 0xff, 0x00, 0x09, 0x01, 0x81, 0x00, 0x09, 0x01, 0x91, 0x00, 0xc0, 
    0x06, 0x00, 0xff, 0x09, 0x02, 0xa1, 0x01, 0x85, 0x11, 0x75, 0x08, 0x95, 0x13, 0x15, 0x00, 0x26, 
    0xff, 0x00, 0x09, 0x02, 0x81, 0x00, 0x09, 0x02, 0x91, 0x00, 0xc0, 0x06, 0x00, 0xff, 0x09, 0x04, 
    0xa1, 0x01, 0x85, 0x20, 0x75, 0x08, 0x95, 0x0e, 0x15, 0x00, 0x26, 0xff, 0x00, 0x09, 0x41, 0x81, 
    0x00, 0x09, 0x41, 0x91, 0x00, 0x85, 0x21, 0x95, 0x1f, 0x15, 0x00, 0x26, 0xff, 0x00, 0x09, 0x42, 
    0x81, 0x00, 0x09, 0x42, 0x91, 0x00, 0xc0
  ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_MOUSE=1
    - LIBINPUT_DEVICE_GROUP=3/46d/80:usb-0000:00:14.0-12
  quirks:
  events:
```

I'm currently on systemd commit `0a207d8` (i.e. the one before your PR, leftover from bisecting.. )

**Comment by redstrate** [comment]
Ah I see, the reported keys are almost exactly the same as my tablet pad, except for `REL_X` and `REL_Y`. I suspect that we can use those to determine whether or not the mouse is indeed not a tablet, but I'll grep through the libinput recordings and see if there's any drawing tablets that contain `REL_X` and `REL_Y`.

**Comment by holzgeist** [comment]
Thanks for looking into it! :heart:

**Comment by holzgeist** [comment]
Thanks, it works with `!has_rel_coordinates` :tada:

**Comment by redstrate** [comment]
> Thanks, it works with `!has_rel_coordinates` 🎉

That’s great to hear! I’m really curious now if my own Logitech mouse was considered a tablet and I didn’t notice  :-P

**Comment by yuwata** [comment]
@holzgeist or @redstrate Could you submit the fix as a PR?

**Comment by redstrate** [comment]
> @holzgeist or @redstrate Could you submit the fix as a PR?

Sorry about the delay, I still haven't gotten around to testing it (apart from a grep): https://github.com/systemd/systemd/pull/26666
