### ISSUE TITLE
NFS root on IPv6 fails to boot

### ISSUE THREAD

**Issue by iandall** [systemd/systemd#26602]
### systemd version the issue has been seen with

252

### Used distribution

Fedora 37

### Linux kernel version used

6.0.8-200.fc36.x86_64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

A clean boot.

### Unexpected behaviour you saw

During boot, after switch-root, the system hangs. It some times eventually completes to a login prompt, but with many failures caused by stale file handles.

### Steps to reproduce the problem

Configure an initrd for nfs root (dracut customization file included).
Configure the network for IPv6. A sample systemd.network file included. It doesn't seem to matter whether it is configured by route advertisements or DHCPv6 (as per this example).

Boot with a command line like `root=nfs4:<server>:<exported fs>`

[config.zip](https://github.com/systemd/systemd/files/10839159/config.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/iandall/746bd4546f7629d15f39483825204772

**Comment by iandall** [comment]
This works with IPv4. It seems that KeepConfiguration only works for IPv4.

This can also be seen, perhaps more quickly, by:
- setting `rd.break` on the command line
- at the initrd prompt, verify /sysroot is mounted using IPv6 addresses (eg `grep /sysroot /proc/mounts`)
-  stop the networkd: `systemctl stop systemd-networkd.{socket,service}`
- access the sysroot: `ls /sysroot`

which hangs.

**Comment by yuwata** [comment]
Yeah, unfortunately, currently, DHCPv6 addresses are not kept even if KeepConfiguration=yes is set.

**Comment by yuwata** [comment]
Fix is waiting in #34989.
