### ISSUE TITLE
systemd-cryptenroll using none-default luks values

### ISSUE THREAD

**Issue by fuba832** [systemd/systemd#26615]
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

When adding a fido2 token to an existing luks device using systemd-cryptenroll, the parameters used would be expected to be the cryptsetup default for luks2

### Unexpected behaviour you saw

After adding a fido2 token for disk encryption to a luks device, luksDump shows none-default values for the used PBKDF and Iterations used for the new keyslot.

While all other keyslots (both for passphrases and keyfiles) added via cryptsetup listed PBKDF: argon2id, the new keyslot added with systemd-cryptenroll seems to use the old luks1 default values with  PBKDF: pbkdf2 and Iterations: 1000 (luks2 defaults to 2000 iterations when using pbkdf2 and also uses argon2id)

If I understand the fido2 hmac-secret feature correctly, the key material used here is the hash of a combination of a salt value stored in the luks header and a static symmetric secret key stored securely on the fido2 device, which means this should not be too much of an issue in general. However, since the default values like argon2id are also used with keyfiles as well, which would work similar to the fido2 secret, using the default values would be expected here, especially since these parameters cannot be specified with systemd-cryptenroll.

### Steps to reproduce the problem

```
## setup luks device (parameters are the default values for luks2)
cryptsetup --type luks2 --cipher aes-xts-plain64 --hash sha512 --key-size 512 --pbkdf argon2id --use-urandom --verify-passphrase luksFormat device

## add a keyfile to the second slot
cryptsetup luksAddKey /dev/sda2 /etc/mykeyfile

## add a fido2 token
systemd-cryptenroll --fido2-device=auto  /dev/sdXY

cryptsetup luksDump /dev/sdXY

```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Keyslots:
  0: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      argon2id
	Time cost:  10
	Memory:     xxx
	Threads:    x
	Salt:       xx yy zz ...
	AF stripes: 4000
	AF hash:    sha512
	Area offset:xxx [bytes]
	Area length:xxx [bytes]
	Digest ID:  0
  1: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      argon2id
	Time cost:  10
	Memory:     xxx
	Threads:    x
	Salt:       xx yy zz ...
	AF stripes: 4000
	AF hash:    sha256
	Area offset:xxx [bytes]
	Area length:xxx [bytes]
	Digest ID:  0
  2: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      pbkdf2
	Hash:       sha512
	Iterations: 1000
	Salt:       xx yy zz ...
	AF stripes: 4000
	AF hash:    sha512
	Area offset:xxx [bytes]
	Area length:xxx [bytes]
	Digest ID:  0
Tokens:
  0: systemd-fido2
	fido2-credential: xxxxxxx...
	fido2-salt: yyyyy...
	fido2-rp:   io.systemd.cryptsetup
	fido2-clientPin-required:
	            true
	fido2-up-required:
	            true
	fido2-uv-required:
	            false
	Keyslot:    2
Digests:
  0: pbkdf2
	Hash:       sha512
	Iterations: 275224
	Salt:       xxxxx..
	Digest:     yyyyy..
```

**Comment by poettering** [comment]
we set the kdf to minimal parameters when we use a high-quality random key, like we do in the fido2 case. if the key used is already high quality entropy there's no point in applying a KDF to it, which should increase quality, but is pretty pointless if the key is already as high quality as it gets.

hence, this is on purpose. In fact, we'd disable the KDF entirely if we could, but LUKS doesn't allow that.

(this is by recommendation of the LUKS upstream people btw.)
