### ISSUE TITLE
SD_RESOLVED_REQUIRE_PRIMARY flag is always invalid

### ISSUE THREAD

**Issue by jafuehre-froeling** [systemd/systemd#26619]
### systemd version the issue has been seen with

upstream

### CPU architectures issue was seen on

None

### Component

resolvectl

### Expected behaviour you didn't see

The [SD_RESOLVED_REQUIRE_PRIMARY](https://github.com/systemd/systemd/blob/077c5cf66936f830ae8af818a93097b3cbcfa56a/src/resolve/resolved-def.h#L50) should be a valid flag. `gdbus call --system --dest org.freedesktop.resolve1 --object-path /org/freedesktop/resolve1 --method org.freedesktop.resolve1.Manager.ResolveRecord 0 _http._tcp.local 1 12 65536` should be valid (65536 = 1<<16 = SD_RESOLVED_REQUIRE_PRIMARY)

### Unexpected behaviour you saw

`Error: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Invalid flags parameter`

### Additional program output to the terminal or log subsystem illustrating the issue

I spotted that https://github.com/systemd/systemd/blob/9eba03c7b10fe98e0443508402b3f9804230453e/src/resolve/resolved-bus.c#L354-L363 validates the provided flags, but `SD_RESOLVED_REQUIRE_PRIMARY` is never valid. It is never passed as ok and is not in the list of valid flags.

**Comment by poettering** [comment]
Yeah, that's on purpose. We don't open up all flags to clients. The fact this flag was documented was a mistake. Will prep fix.
