### ISSUE TITLE
RouteTable in networkd.conf seems to be ignored by subsequent Table lookups in ".network" files

### ISSUE THREAD

**Issue by pernu** [systemd/systemd#26637]
### systemd version the issue has been seen with

253-1

### Used distribution

Arch Linux

### Linux kernel version used

6.2.1-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

```
/etc/systemd.networkd.conf:
[Network]
RouteTable=one:1
```

```
/etc/systemd/network/20-main-wired.network:
[Match]
Name=enp6s0

[Network]
Address=192.168.1.18/24
Gateway=192.168.1.1
DNS=192.168.1.1

[RoutingPolicyRule]
FirewallMark=1
Table=one

[RoutingPolicyRule]
TypeOfService=20
Table=one

[Route]
Gateway=192.168.1.5
Table=one
```

`networkctl reload`

```
~> ip rule
0:      from all lookup local
32764:  from all fwmark 0x1 lookup one proto static
32765:  from all tos 0x14 lookup one proto static
32766:  from all lookup main
32767:  from all lookup default
```

```
~> ip route show table 1
default via 192.168.1.5 dev enp6s0
```

### Unexpected behaviour you saw

`networkctl status`

```
[...]
systemd-networkd[342]: /etc/systemd/network/20-main-wired.network:11: Could not parse RPDB rule route table "one", ignoring assignment: Invalid argument
systemd-networkd[342]: /etc/systemd/network/20-main-wired.network:15: Could not parse RPDB rule route table "one", ignoring assignment: Invalid argument
systemd-networkd[342]: /etc/systemd/network/20-main-wired.network:19: Could not parse route table "one", ignoring assignment: Invalid argument
```

```
~> ip route show table 1
Error: ipv4: FIB table does not exist.
Dump terminated
```

```
> ip rule
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default
```

### Steps to reproduce the problem

All the steps are already shown above.

Not only does the behavior documented in the man pages not work as expected, but it also seems redundant to have to define `RouteTable=` in `networkd.conf` given that the source of truth should probably be coming from `/etc/iproute2/rt_tables` anyway. At the very least, `systemd-networkd` should be respecting/consulting those iproute2 route table definitions.

**Comment by yuwata** [comment]
> ```
> /etc/systemd.networkd.conf:
> [Network]
> RouteTable=one:1
> ```

The path is wrong. Please use /etc/systemd/networkd.conf. See networkd.conf(5).

**Comment by yuwata** [comment]
Feel free to request to reopen this page, if the path does not work.
