### ISSUE TITLE
journalctl -n misbehaves when combined with --since or --until

### ISSUE THREAD

**Issue by georgmu** [systemd/systemd#26657]
### systemd version the issue has been seen with

systemd-251.11-2.fc37.x86_64

### Used distribution

Fedora 37

### Linux kernel version used

6.1.9-200.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

the man page of journalctl states that `-n` shows "the most recent journal events".

given there are more than 10 log lines in every time interval:
* when running `journalctl --since today -n 10`, I expect to see the same as `journalctl -n 10` 
* when running `journalctl --until today -n 10`, I expect to see the last 10 entries of yesterday (e.g. 23:59...).

### Unexpected behaviour you saw

* `journalctl --since today -n 10` returns the 10 oldest entries of today (same as `journalctl --since today | head -n 10`)
* `journalctl --until today -n 10` returns no entries at all

**Comment by YHNdnzj** [comment]
It seems that this had been observed in
https://github.com/systemd/systemd/pull/11766#issuecomment-465362631 but
didn’t get fixed.

**Comment by georgmu** [comment]
Ok, I didn't find this. Thx.

As a general note to the comments in #11766:
In my opinion, `-n` showing the "bottom" n lines should be always the goal - as stated in the man page.
When I want to have the top 10 lines, I could use `| head -n 10`.
Showing the bottom entries using `| tail -n 10` requires systemctl to render everything, which does not sound optimal.

**Comment by YHNdnzj** [comment]
@yuwata I think we can apply the same kind of fix as
https://github.com/systemd/systemd/commit/db4691961ca52759fe6645d0fddb659ee4299ac2.
WDYT?
