### ISSUE TITLE
LoadCredentialsEncrypted unconditionally sets DeviceAllow

### ISSUE THREAD

**Issue by anpandey** [systemd/systemd#26673]
### systemd version the issue has been seen with

251.12

### Used distribution

nixos-22.11

### Linux kernel version used

5.15.96

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

For services that set `LoadCredentialsEncrypted`, `DeviceAllow` shouldn't be set to anything if it's unset in the service definition, according to the documentation:

>When DevicePolicy= is set to "closed" or "strict", or set to "auto" and DeviceAllow= is set, or PrivateDevices= is set, then this setting adds /dev/tpmrm0 with rw mode to DeviceAllow=.

I was expecting any service that uses `LoadCredentialsEncrypted` to have access to all block devices by default.

### Unexpected behaviour you saw

`DeviceAllow=/dev/tpmrm0 rw`  shows up in `systemctl show`, even though we didn't set `DeviceAllow=` to anything in the service definition. The service ends up not having access to any block devices (since `DevicePolicy=auto` is the default).

I think this behavior was added with https://github.com/systemd/systemd/pull/26346.

### Steps to reproduce the problem

This breaks e.g. this service that tries to access a block device using credentials loaded via  `LoadCredentials` :

```
[Unit]

[Service]
Environment=CREDPATH=%d/disk
ExecStart=cryptsetup luksOpen /dev/sda2 wd < $CREDPATH
LoadCredentialEncrypted=disk:disk
RemainAfterExit=true
Type=oneshot
```

Trying to start the service:

```
Mar 04 13:54:12 nixos systemd[1]: Starting mount-wd.service...
Mar 04 13:54:13 nixos ext4-wd-start[8766]: Device /dev/sda2 does not exist or access denied.
```

`systemctl show`  shows us that `DeviceAllow` is only set to `/dev/tmprm0`, so it can't access any other devices:

```
> systemctl show ext4-wd.service | grep DeviceAllow
DeviceAllow=/dev/tpmrm0 rw
```

**Comment by bluca** [comment]
A missing backport in v251-stable caused a bad backport so it's not an issue in main https://github.com/systemd/systemd-stable/pull/266
