### ISSUE TITLE
libsystemd calls getenv, getenv is documented non-thread-safe

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#26688]
In https://bugzilla.redhat.com/show_bug.cgi?id=2086188 `gnome-shell` (a multi-threaded program with ~60 threads running) crashes with a backtrace where one of the threads is just doing `getenv()` from `device_set_syspath()` called from `udev_enumerate_scan_devices()`. `getenv()` accessing memory which just is being modified by `setenv()` from another thread might or might not be the problem in this particular case. But @fweimer-rh raised the issue that according to the docs, `getenv()` is not thread-safe. It seems iffy to call `getenv()` from deep inside of `libsystemd` / `sd-device`.

We have been calling `getenv()` from `sd-daemon` and `sd-bus` always, seeming without bad effects. 
Is it safe to assume that `setenv()` / `getenv()` is thread safe? Looking at the glibc code, I see `LOCK` in `setenv.c`, but no locking in `getenv.c`. ??

**Comment by keszybz** [comment]
https://blogs.gnome.org/mcatanzaro/2018/02/28/on-setenv-and-explosions/

**Comment by keszybz** [comment]
One case which is fairly obvious is when `getenv()` returns a pointer to a string and `unsetenv()` kills that variable or `setenv()` replaces the value. In that case, the original string becomes invalid and I don't think there's much that can be done in that case. But the interesting case is when some *other* variable is changed, which is what might be happening here.

**Comment by poettering** [comment]
frankly, modifying the environment block is super icky anyway, everybody knows that. it's a global resource, and people keep pointers to it. memory ownership is unsettled.

hence, i would just say: it is how it is - a totally unsafe and terrible API, but we have to live with it, hence *everyone* involve should simply refrain from modifying the envionment variables unless they *know* for sure that noone else might touch/reference it.

this is what we actually do in systemd. we never modify the env block unless we know for suer we are the only piece of code currently running in our process.

I'd thus put the blame clearly in gnome-shell's field: they really should not modify env vars druing runtime, but do this only early during initialization (as long as they know they are the only thing running) or maybe in a forked off child or so.

it's not just systemd code that checks env vars from libraries. It's pretty much *any* library that is non-trivial. i.e. $PATH, $LANG, $SHELL, $USER, $HOME and so on are pretty much *always* refernced from anything that is more complex than a hello world app.

Or is gnome-shell claiming it wasn't using an innocuous call such as g_get_home_dir()? under the hood that immediately calls getenv("HOME").

**Comment by poettering** [comment]
> I'm no longer sure if this isn't just a glibc bug/quality-of-implementation issue. AFAICS, we never deallocate memory allocated by `setenv`, so there is really no fundamental reason for not making `getenv` thread-safe. However, for lock ordering reasons (involving replacement `malloc`s), we'd have to use a custom allocator instead of `malloc` instead of `setenv`, I think.

Note that glibc exposes environ[], and people use that. You cannot really make that thread-safe hence, because your locking proto wouldn't be honoured by people using that.

And they really have to use that, because it's the only way to enumerate env vars.

**Comment by poettering** [comment]
Anyway, I would just close this here, and tell gnome-shell people to fix their code?

**Comment by keszybz** [comment]
> Anyway, I would just close this here, and tell gnome-shell people to fix their code?

FWIW, we haven't really confirmed that the issue is caused by setenv/getenv interaction. It seems likely that the error is in gnome-shell, but that's just a hypothesis.

Ideally, the fix would be in glibc to make this safe. I'm not sure if we can tell people to avoid using setenv altogether. For high-level frameworks that are used in graphical applications and such it is very hard to push those setenv before any multithreaded code could be running.

Hmm. Even though the real fix would be in other places, I think we could make the issue less likely from our side by only doing the getenv when compiled in developer mode. I'll submit a patch for discussion.

**Comment by yuwata** [comment]
This is off-topic, but `tzset()` also update global variables, and they are used in `parse_timestamp()` and `in_utc_timezone()`. Fortunately, they are not used in libsystemd, though.

**Comment by poettering** [comment]
> Another option is to do the lookup upfront in an ELF constructor. The process is more likely to be single-threaded at that point.

Uh, no. it should be totally ok for people to rearrange env vars during early init in main(). We should then take that into consideration. If we'd put things in constructors, then we'll make that impossible.

Experience tells me that ELF constructors are usually a source of problems, not a solutoin to problems. Same here I am very sure.
