### ISSUE TITLE
Mailing list subscription not possible

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#26703]
### systemd version the issue has been seen with

252

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Wanted to subscribe to the mailing list as per the instruction on https://github.com/systemd/systemd/issues/new/choose

### Unexpected behaviour you saw

Entering one's email address in the standard GNU mailman interface https://lists.freedesktop.org/mailman/listinfo/systemd-devel presents a result page (https://lists.freedesktop.org/mailman/subscribe/systemd-devel ) like so:

![1](https://user-images.githubusercontent.com/8861948/223409347-563b7f5d-863f-4446-b6e7-48df01cd3433.png)

**Comment by mrc0mmand** [comment]
Did you check the reCAPTCHA "I'm not a robot" tick box at the bottom of the form?

![image](https://user-images.githubusercontent.com/679338/223421938-1ca653c0-c1f3-4206-bd84-c5acd66ace2d.png)

**Comment by jengelh** [comment]
That's a very uncanny placement. (it's not visible in the first 1920x1080 viewport; and I traditionally could just press enter right there to trigger the HTML form submission - i.e. a case of https://xkcd.com/1172/ ).

Would be better to place the captcha part above the first HTML input field. Looking at https://github.com/mailman/mailman to modify it though, I see no captcha support. Is this some offbeat extension or something?

**Comment by mrc0mmand** [comment]
> That's a very uncanny placement. (it's not visible in the first 1920x1080 viewport; and I traditionally could just press enter right there to trigger the HTML form submission - i.e. a case of https://xkcd.com/1172/ ).
> 
> Would be better to place the captcha part above the first HTML input field. Looking at https://github.com/mailman/mailman to modify it though, I see no captcha support. Is this some offbeat extension or something?

https://bazaar.launchpad.net/~mailman-coders/mailman/2.1/view/head:/Mailman/Cgi/listinfo.py#L220
https://bazaar.launchpad.net/~mailman-coders/mailman/2.1/view/head:/Mailman/Cgi/subscribe.py#L140

We don't really have power over where the captcha is rendered, it's part of Mailman, which is administered by freedesktop.

**Comment by jengelh** [comment]
Ok so after completing the captcha, I get the confirmation request, but responding to _that_ then leads to

```
                   The mail system

<systemd-devel-request@lists.freedesktop.org>: host
    gabe.freedesktop.org[2610:10:20:722:a800:ff:fe36:1795] said: 550 5.1.1
    <systemd-devel-request@lists.freedesktop.org>: Recipient address rejected:
    User unknown in local recipient table (in reply to RCPT TO command)
```

Something is really broken at freedesktop.

**Comment by yuwata** [comment]
The service is not under our control. Please contact to freedesktop.

**Comment by yuwata** [comment]
And, here is an upstream issue tracker, not a support forum of web service issue. Sorry.
