### ISSUE TITLE
systemd-boot: 4 out of 10 boots fails after the menu with a black screen hanging forever

### ISSUE THREAD

**Issue by feixm1** [systemd/systemd#26710]
### systemd version the issue has been seen with

253

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

While booting on a Lenovo IdeaPad 5 14ITL05 laptop with systemd-boot as an UEFI bootloader, the configured boot menu shows up perfectly but after selecting Linux entry to boot, the system SOMETIMES hangs with a black screen and hard shutdown is needed. My observed statistical probability says that approx 4 out of 10 boots end with an immediate hang after selecting the Linux boot entry.

In the most probable scenario when the system boots up properly, after selecting the Linux entry, the OEM Lenovo logo shows up briefly and right after that Linux kernel starts spinning its own messages to console. As the OEM logo is not showing up during the failing scenarios, I suspect that the hang happens might happend while systemd-boot tries to load and launch the kernel or around that moment.

### Unexpected behaviour you saw

Boot hangs right before any message from linux kernel is shown, black screen, no OEM logo, no error messages, system unresponsive, probably idling as the CPU fan on the notebook is quiet as usual. Only way out via hard shutdown by holding the power button for several seconds.

### Steps to reproduce the problem

1. Launch the Lenovo IdeaPad 5 14ITL05 notebook.
2. Wait for the systemd-boot menu to display.
3. Select the Linux boot option or wait for the set timeout to pass.
4. With approx. 40% probability the systems hangs with a black screen.

**Comment by feixm1** [comment]
I'm using a regular boot entry. So far I was not able to invoke the bug via grub.  I'm not able to confirm if this is a regression of any kind as I see this bug since I started to use this laptop. Will try the `debug efi=debug` kernel command line.

**Comment by feixm1** [comment]
[bootctl-status.txt](https://github.com/systemd/systemd/files/10950411/bootctl-status.txt)

**Comment by medhefgo** [comment]
Unfortunately, there is no proper logging system (yet). Try installing `edk2-shell`, copy the shell to `$ESP/Shellx64.efi` and then see if you can boot the new entry. That will narrow things down.

You can also try this PR to see if any UB is causing this: https://github.com/systemd/systemd/pull/26759
Build it like this:
```sh
meson setup -Dbootloader=true -Db_sanitize=undefined build
ninja -C build systemd-boot
```
And then replace the loader on your esp with `build/src/boot/efi/systemd-bootx64.efi`. You may also try sprinkling the code in `src/boot/efi/` with some `log_trace()` calls to narrow things down. One would be best before `err = BS->StartImage(image, NULL, NULL)` in `boot.c`.

**Comment by feixm1** [comment]
So with kernel cmd line `debug efi=debug` I caught a hangup with only two rows of messages spitted on the console:
```
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
EFI stub: Measured initrd data into PCR 9

```
Does that mean its already out of systemd-boot in that moment?

**Comment by medhefgo** [comment]
Yes, the error happens after the kernel is already started. Please try booting the kernel efistub directly as explained in the arch wiki to see if it's only the kernel or the way it's booted by us. (grub boots the kernel differently, which would be the reason why it works)

**Comment by TriMoon** [comment]
@feixm1 
> [bootctl-status.txt](https://github.com/systemd/systemd/files/10950411/bootctl-status.txt)

Your kernel options need to be changed, these are grub specific AFAIK...
> options: cryptdevice=UUID=<redacted-content1>:cryptroot:allow-discards root=/dev/mapper/cryptroot

You need to use `crypttab` to setup your config.
In past i made a nice tutorial that might help you:
- :woman_teacher:[[HowTo] Boot without a password for encrypted root partition](https://forum.manjaro.org/t/howto-boot-without-a-password-for-encrypted-root-partition/44684)
