### ISSUE TITLE
Create alternative to printf.h usage

### ISSUE THREAD

**Issue by nwmcsween** [systemd/systemd#2672]
It seems the printf.h usage in systemd is superfluous as it doesn't actually use any custom format specifiers (which is good) and over-rides global _print_ usage. A better alternative would be just to use __builtin_choose_expr_p or even _Generic to call snprintf with wanted format specifiers.

**Comment by crrodriguez** [comment]
systemd requires glibc this is mandatory and is very unlikely to change.

**Comment by nwmcsween** [comment]
I never stated anything about glibc, it's completely useless to use printf.h which is meant mainly for custom format specifiers when the code in question doesn't use any.

**Comment by poettering** [comment]
Hmm? we use it for parse_printf_format(), which the VA_FORMAT_ADVANCE() macro needs. I have no idea how __builtin_choose_expr_p or _Generic is supposed to be useful for that.

**Comment by nwmcsween** [comment]
Because it seems to just map some format specifiers to others?

**Comment by poettering** [comment]
Hmm? did you look at the code? it's a macro that advances the va_arg pointer by the parameters specified in a format string. Please have a look at the macro. There's no "mapping" to specifiers in place...
