### ISSUE TITLE
journalctl `--user --unit` and `--user-unit` differ

### ISSUE THREAD

**Issue by smopucilowski** [systemd/systemd#26742]
### systemd version the issue has been seen with

systemd 253 (253) +PAM -AUDIT -SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 +LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

### Used distribution

Gentoo

### Linux kernel version used

6.1.12-gentoo

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

I have a backup script that invokes `rsync` using `systemd-run`:

```
systemd-run \
        --user \
        --collect \
        --pty \
        --quiet \
        --wait \
        --property=ExitType=cgroup \
        --property=IOSchedulingClass=idle \
        --slice backup \
        --unit "backup" \
        rsync -aPh $args $src $dst
```

When inspecting the journal naively, I can see the journal entries for the invocation (ignore the ctrl-C aborts):

```
# journalctl -b -g backup
Mar 10 12:36:07 wanderweg.smoddom.local systemd[709036]: Created slice backup.slice.
Mar 10 12:36:07 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:37:09 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 2.408s CPU time.
Mar 10 12:37:09 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=23/n/a
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 52.683s CPU time.
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:43:25 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=23/n/a
Mar 10 12:43:25 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:43:25 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 5.110s CPU time.
Mar 10 12:44:08 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:44:08 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:47:19 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=23/n/a
Mar 10 12:47:19 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:47:19 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 46.194s CPU time.
Mar 10 12:47:19 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:47:24 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=23/n/a
Mar 10 12:47:24 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:47:24 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 1.815s CPU time.
Mar 10 12:48:32 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:48:34 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=20/n/a
Mar 10 12:48:35 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:48:35 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:48:36 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=20/n/a
Mar 10 12:48:36 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:48:36 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 1.048s CPU time.
Mar 10 12:48:36 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:48:37 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=20/n/a
Mar 10 12:48:37 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:50:38 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:50:51 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 2.360s CPU time.
Mar 10 12:50:51 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:53:27 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 56.583s CPU time.
Mar 10 12:53:27 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 13:06:42 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 4min 32.738s CPU time.
```

When trying to view the journal entries directly, they do not appear:

```
# journalctl -b --unit backup
-- No entries --
# journalctl -b --user --unit backup
No journal files were found.
-- No entries --
```

The desired entries only appear when using `--user-unit`, which the documentation appears to suggest is equivalent to `--user --unit`:
```
# journalctl -b --user-unit backup
Mar 10 12:36:07 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:37:09 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 2.408s CPU time.
Mar 10 12:37:09 wanderweg.smoddom.local systemd[709036]: Started backup.service.
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Main process exited, code=exited, status=23/n/a
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Failed with result 'exit-code'.
Mar 10 12:41:00 wanderweg.smoddom.local systemd[709036]: backup.service: Consumed 52.683s CPU time.
etc
```

1. It is not clear from `journalctl -b -g backup` which are entries from the user journal vs the system journal, leaving a lot of puzzled confusion on viewing relevant journal entries, and
2. It appears that `--user --unit` and `--user-unit` are different and not working as expected.

Possibly related to bug #23679

### Unexpected behaviour you saw

As above.

### Steps to reproduce the problem

As above.

**Comment by smopucilowski** [comment]
The above commands were all executed as root.

**Comment by YHNdnzj** [comment]
After some investigation, I think the only difference between `--user --unit=` and `--user-unit=` is that the former sets `arg_journal_type` to `SD_JOURNAL_CURRENT_USER`. In both this issue and the mention one (#23679), the involved user is a system user (i.e. has a UID < 1000), and thus doesn't have dedicated journal files starting with `user-UID`, breaking the logic down below:

https://github.com/systemd/systemd/blob/262299dccbb09f36c8c830dabd6a104469d9852b/src/libsystemd/sd-journal/sd-journal.c#L1330-L1337

**Comment by YHNdnzj** [comment]
@yuwata Is it intended to store system user's journal in `system-`?

**Comment by YHNdnzj** [comment]
https://github.com/systemd/systemd/blob/5f64d2bf332371bdfdcb91b588e57d4c0c20428f/src/journal/journald-server.c#L241-L246

**Comment by poettering** [comment]
> The desired entries only appear when using `--user-unit`, which the documentation appears to suggest is equivalent to `--user --unit`:

where does it suggest that?

**Comment by smopucilowski** [comment]
> 

From the `journalctl` man pages, under `-u, --unit` viz:

> With --user, all --unit arguments will be converted to match user messages as if specified with --user-unit.

**Comment by dawagner** [comment]
I have the same issue with a UID >= 1000 but then I'm hitting https://github.com/systemd/systemd/issues/2744 as well (my user logs are not split but rather stored with the system logs. I'm not sure why my logs are volatile even though my configuration says otherwise but that's another story).
