### ISSUE TITLE
systemd-networkd: DHCP entirely manual DUID

### ISSUE THREAD

**Issue by lspgn** [systemd/systemd#26745]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

This is related to a setup of IPv6 on [Scaleway](https://www.scaleway.com/en/docs/dedibox-network/ipv6/quickstart/) servers.
In order to have IPv6 routed to a server, the DHCPv6 client needs to send a custom 10 bytes DUID.
Unfortunately this is not possible with `systemd-networkd` and restricts to specific types.

It's possible this provider may not follow an RFC and should aim to provide a better solution. Although I think the DUID should be more customizable. Let me know what you think.

Thank you

### Describe the solution you'd like

Per the [doc](https://www.freedesktop.org/software/systemd/man/networkd.conf.html#%5BDHCPv4%5D%20Section%20Options)
We can use a DUID like:
```
[DHCPv6]
DUIDType=vendor
DUIDRawData=00:00:ab:11:f9:2a:c2:77:29:f9:5c:00
```

But because of the `vendor` type, two bytes are appended at the beginning and this would not work.

My ideal solution would be something like
```
[DHCPv6]
DUIDType=custom
DUIDRawData=00:00:ab:11:f9:2a:c2:77:29:f9:5c:00
```
That would send only the RawData.

After diving into the code, I noticed a `raw` that could be used
https://github.com/systemd/systemd/blob/0b40688d1830abc6f59b1f1f67eccd757c23eb09/src/libsystemd-network/dhcp-identifier.h#L53-L55

### Describe alternatives you've considered

Per the documentation, Scaleway recommends to setup [isc-dhcp-client](https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhclientconf) with `send dhcp.client-identifier` ([options](https://linux.die.net/man/5/dhcp-options)).
Without this, it is not possible to receive IPv6 traffic.
This has the disadvantage of clearing the IP addresses on the interface until `systemd-networkd` reconfigures-it.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by ssahani** [comment]
Could you please test with https://github.com/systemd/systemd/pull/28846
