### ISSUE TITLE
Booting with net.ifnames=0 biosdevname=0 still results in interface name enp9s0

### ISSUE THREAD

**Issue by dbeusee** [systemd/systemd#2674]
I have the above in all menu entries in the grub2 menu, and still I get enp9s0.  This is on a Dell laptop running fedora core 23.  This is working on other systems.  What could be overriding this?

**Comment by dbeusee** [comment]
Ok, this is weird.  I tried one last thing.  I renamed ifcfg-enp9s0 to ifcfg-eth0 and changed the DEVICE= line to eth0 and rebooted.  This fixed it!  So it seems systemd considers these scripts in naming the device.  I wonder if it should be doing that...

**Comment by poettering** [comment]
systemd doesn't care about ifcfg files, but Fedora's/RHEL's networking package will use the info to rename the interfaces.

Closing, since this has nothing to do with systemd.
