### ISSUE TITLE
'bootctl update --graceful' does not ignore EFI variable errors as documented

### ISSUE THREAD

**Issue by kpfleming** [systemd/systemd#26773]
### systemd version the issue has been seen with

systemd_252.6-1_amd64.deb

### Used distribution

Debian Bookworm

### Linux kernel version used

6.1.0-6-amd64

### CPU architectures issue was seen on

arm

### Component

bootctl

### Expected behaviour you didn't see

`bootctl update --graceful` should complete without errors on a system which does not support EFI variables (U-boot in this case).

### Unexpected behaviour you saw

`bootctl update --graceful` reported a failure to access EFI variables and exited with a non-zero status.

### Steps to reproduce the problem

Run `bootctl update --graceful` on a system which does not support EFI variables and has systemd-boot already installed (using `bootctl install --no-variables`).

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@core23-a:~# bootctl update --graceful
Skipping "/efi/EFI/systemd/systemd-bootaa64.efi", since same boot loader version in place already.
Skipping "/efi/EFI/BOOT/BOOTAA64.EFI", since same boot loader version in place already.
Failed to create EFI Boot variable entry: No such file or directory
```

**Comment by poettering** [comment]
hmm, what? a systemd that does not support efi variables? what is that? efi implies efi var, what is uefi without efi vars?

This doesn't really make any sense to me.

Sounds like something your frankenuefi implementation really should fix. It's one thing not to offer persistant efi vars. It's something very different not offering efi vars at all. And that latter thing is so broken I doubt we need to bother.
