### ISSUE TITLE
Suspend and Resume Services

### ISSUE THREAD

**Issue by tkna91** [systemd/systemd#26798]
### Component

systemd

### Is your feature request related to a problem? Please describe

The ability to suspend and resume the service.

When closing the laptop lid and suspending the system, if rsync, cp, or other services are running, the suspension will be delayed.
In such a case, if it is possible to suspend to the target service, system suspend can be performed immediately.
When you open the laptop lid and return from system suspend, if you can resume the corresponding service, you will not have to start over with rsync or other processes running on the service.

### Describe the solution you'd like

Command Example:

- systemctl suspend SERVICE
  * Suspend all process trees started by the service by `kill -s SIGSTOP`

- systemctl resume  SERVICE
  * Resume all process trees suspended by the above functions by `kill -s SIGCONT`

### Describe alternatives you've considered

When closing the laptop lid and suspending the system, suspending is delayed if rsync, cp, etc. are running. That is why I created this shell script to allow immediate system suspend. Suspend to the relevant process with `kill -s SIGSTOP $PID` before system suspend and process resume with `kill -s SIGCONT $PID` after system suspend.
```bash
$ cat /usr/lib/systemd/system-sleep/process-suspend-continue.sh
#!/bin/sh

sigstop() {
    /usr/bin/kill -s SIGSTOP `pidof $*`
}

sigcont() {
    /usr/bin/kill -s SIGCONT `pidof $*`
}

case "$1" in
    pre)
        sigstop /usr/bin/rsync
        sigstop /usr/bin/cp
        sigstop /usr/bin/syncthing
        exit 0
        ;;
    post)
        sigcont /usr/bin/rsync
        sigcont /usr/bin/cp
        sigcont /usr/bin/syncthing
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
$
```
However, I was thinking that if systemd could specify suspend and resume for each service, it would be good to centralize the management.

### The systemd version you checked that didn't have the feature you are asking for

253.1-1

**Comment by dtardon** [comment]
See `systemctl freeze`  and `systemctl thaw`.
