### ISSUE TITLE
Multiple warning during rpm upgrade to run 'systemctl daemon-reload' to reload units.

### ISSUE THREAD

**Issue by shaleenbathla** [systemd/systemd#26809]
### systemd version the issue has been seen with

systemd-251.13-5

### Used distribution

Fedora 37

### Linux kernel version used

6.1.18-200

### CPU architectures issue was seen on

x86_64

### Component

rpm scriptlets

### Expected behaviour you didn't see

I am hoping to eliminate these warnings during upgrade.

### Unexpected behaviour you saw

3 warnings when upgrading gssproxy and nfs-utils together :
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.

### Steps to reproduce the problem

Step 1 : dnf install gssproxy nfs-utils -y
Step 2 : dnf downgrade gssproxy nfs-utils -y
Step 3 : dnf update gssproxy nfs-utils -y

If older rpm is absent, try manual download and upgrade.
During step 3, I see 3 warnings as written above of which I can eliminate later 2 by redirecting triggerin in nfs-utils to /dev/null
But the 1st warning seems to be coming before triggerin, after post phase likely from inside systemd.

I am trying to understand why and where the 1st warning is coming from and if it is a bug in systemd or expected behaviour.

### Additional program output to the terminal or log subsystem illustrating the issue

[shaleenbathla@fedora ~]$ sudo rpm -Uvh gssproxy-0.9.1-5.fc38.x86_64.rpm nfs-utils-2.6.2-2.rc6.fc37.x86_64.rpm
warning: gssproxy-0.9.1-5.fc38.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 18b8e74c: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:gssproxy-0.9.1-5.fc38            ################################# [ 25%]
   2:nfs-utils-1:2.6.2-2.rc6.fc37     ################################# [ 50%]
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of gssproxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Cleaning up / removing...
   3:nfs-utils-1:2.6.2-1.rc2.fc37     ################################# [ 75%]
Not supported unit type
   4:gssproxy-0.9.1-4.fc37            ################################# [100%]
[shaleenbathla@fedora ~]$

**Comment by poettering** [comment]
Please contact your distro for help, this is an issue with their packaging scripts, not with systemd.
