### ISSUE TITLE
Conditions are ignored when starting Wanted Units

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/systemd#26805]
### systemd version the issue has been seen with

252.6

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-6-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

I want to run units based on a timer and on first boot. For this I added a `WantedBy=first-boot-complete.target` to these units and enabled them. The units should be activated once, when the target is being activated and not when the target is being skipped.

### Unexpected behaviour you saw

The units also activate on every reboot, even though `first-boot-complete.target` is being skipped due to `ConditionFirstBoot`.

### Steps to reproduce the problem

I Created two units, a service and a target with a condition based on flag file `/root/myfile`.

```
# /etc/systemd/system/myservice.service
[Service]
Type=oneshot
ExecStart=/usr/bin/touch /root/myfile

[Install]
WantedBy=mytarget.target

# /etc/systemd/system/mytarget.target
[Unit]
ConditionPathExists=!/root/myfile

[Install]
WantedBy=multi-user.target
```

Running
```
systemctl enable myservice.service
systemctl enable mytarget.target
systemctl reboot
# Wait for myservice.service to create /root/myfile
systemctl reboot
systemctl status myservice.service
systemctl status mytarget.target
```
will show that `myservice.service` also activated after the second reboot, while `mytarget.target` didn't.

**Comment by YHNdnzj** [comment]
This is working as intended I believe. From [man:systemd.unit(5)](https://man.archlinux.org/man/systemd.unit.5#Conditions_and_Asserts):

> The conditions and asserts are checked at the time the queued start job is to be executed. The ordering dependencies are still respected, so other units are still pulled in and ordered as if this unit was successfully activated, and the conditions and asserts are executed the precise moment the unit would normally start and thus can validate system state after the units ordered before completed initialization.
