### ISSUE TITLE
promiscuous mode set on [Link] not working

### ISSUE THREAD

**Issue by vans163** [systemd/systemd#26817]
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.5

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

promiscuous mode is set on adapter during boot from .link file
```
[Match]
MACAddress=00:11:22:33:44:55

[Link]
Name=uplink
MTUBytes=9000
RequiredForOnline=yes
Promiscuous=true
```

```
ip a

uplink: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP>
```

### Unexpected behaviour you saw

promiscuous mode was not set on adapter in .link file

```
ip a

uplink: <BROADCAST,MULTICAST,UP,LOWER_UP>
```

We need to execute `ip link set uplink promisc on` to correctly enable it

### Steps to reproduce the problem

Set `Promiscuous=true` in .link config and restart system, notice how PROMISC is not set.

**Comment by yuwata** [comment]
`Promiscuous=` is not supported by .link file. Please specify it in .network file. See systemd.network(5) and systemd.link(5) for more details.
