### ISSUE TITLE
[nspawn] An error occurs in iptables even though Capability is given

### ISSUE THREAD

**Issue by WinLinux1028** [systemd/systemd#26859]
### systemd version the issue has been seen with

systemd-252.5-1

### Used distribution

Manjaro Linux

### Linux kernel version used

6.2.6-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

iptables runs fine.

### Unexpected behaviour you saw

iptables prints the following error.
```
iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```

### Steps to reproduce the problem

1. Write the following contents to `/etc/systemd/nspawn/container_name.nspawn`.
```
[Exec]
Boot=yes
Capability=CAP_NET_ADMIN
PrivateUsers=pick
NotifyReady=yes

[Network]
Private=no
VirtualEthernet=no
```
2. Start the container with `machinectl start container_name`.
3. Run some iptables command in the container (e.g. `iptables -L`)

Note 1:
The same happens if I replace `CAP_NET_ADMIN` in `Capability` with `all`.

Note 2:
The result seems to change depending on the value of `PrivateUsers`.
`PrivateUsers=pick`: Error
`PrivateUsers=identity`: Error
`PrivateUsers=0:65536`: Error
`PrivateUsers=0`: Error
`PrivateUsers=no`: OK

**Comment by poettering** [comment]
i am pretty sure nftables is not accessible from user namespaces (which your second note actually shows). This is a kernel enforced rule, not under our control.

Hence, there's nothign we can do about this. If you want so much control about a host feature you have to disable userns. i see no other way.
