### ISSUE TITLE
journalctl: Empty result with '--show-cursor' throw exit status 1

### ISSUE THREAD

**Issue by Bodenhaltung** [systemd/systemd#26899]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

5.10.0-21-amd64

### CPU architectures issue was seen on

i686

### Component

journalctl

### Expected behaviour you didn't see

Exit status 0 even for "-- No entries --".

No logs are not an error.

### Unexpected behaviour you saw

```
[root@srv:~] # journalctl --no-pager --show-cursor -l -p 0..5 '--after-cursor=s=8ebaba9911394dfc833748fab7727618;i=3b968e;b=61ce41d2732143dd8feaf3a4ec808316;m=16dbc6677f5;t=5f6c8219c65de;x=2f7826011f23edac'
-- No entries --
[root@srv:~] # echo $?
1
```

### Steps to reproduce the problem

Try to get `--show-cursor` with an empty result:
```
[root@srv:~] # journalctl --no-pager --show-cursor -l -p 0..5 '--after-cursor=s=8ebaba9911394dfc833748fab7727618;i=3b968e;b=61ce41d2732143dd8feaf3a4ec808316;m=16dbc6677f5;t=5f6c8219c65de;x=2f7826011f23edac'
```

**Comment by yuwata** [comment]
Already fixed by 9556e79be538776e91794d1d5f10f252f49da1bd. Closing.
