### ISSUE TITLE
networkctl cat/edit/edit-link

### ISSUE THREAD

**Issue by psztoch** [systemd/systemd#26906]
### Component

networkctl

### Describe the solution you'd like

As in https://github.com/systemd/systemd/issues/26246, it would be worth adding a command to conveniently edit configuration files.

On the networkctl, things are more complicated because we have two types of files: .network and .link.
However, 90% of the time we edit the network file, it could be the main one accessed by the edit command.

The cat command will be very useful diagnostically.

**Comment by YHNdnzj** [comment]
Already on my to-do list 😉

**Comment by psztoch** [comment]
@YHNdnzj Hello. networkctl cat @wg0 works very well, but does not scan/show *.netdev files (only *.network).
Is it possible to easy fix it?
If can submit separated feature request issue if you accept my proposal.

**Comment by YHNdnzj** [comment]
> If can submit separated feature request issue if you accept my proposal.

Feel free to track this in a new RFE :)
