### ISSUE TITLE
StartTransientUnit with PIDs that are already parts of other units does not fail but replaces it (without 'replace')

### ISSUE THREAD

**Issue by 3v1n0** [systemd/systemd#26925]
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.1.0

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

We have a race between a process that is calling itself `org.freedesktop.systemd1.Manager.StartTransientUnit` and gnome-desktop that is doing the same for all the apps launched from GNOME Shell.

### Unexpected behaviour you saw

Basically, the 2nd process that calls `StartTransientUnit` always wins and the 2nd unit that is created overtakes the 1st one, even if `replace` is not used.

So we have only one transient unit running, that is not the 1st one launched.

### Steps to reproduce the problem

This can be simulated easily with:

```bash
set +x

sleep 10 &
proc=$!

gdbus call --session \
  --dest org.freedesktop.systemd1 \
  --object-path /org/freedesktop/systemd1 \
  --method org.freedesktop.systemd1.Manager.StartTransientUnit \
  "app-test-$proc-1.scope" 'fail' \
  "[('Description', <'Application launched by test'>), ('PIDs', <[uint32 $proc]>), ('CollectMode', <'inactive-or-failed'>)]" \
  "@a(sa(sv)) []"

echo
echo "App cgroups"
cat /proc/$proc/cgroup

gdbus call --session \
  --dest org.freedesktop.systemd1 \
  --object-path /org/freedesktop/systemd1 \
  --method org.freedesktop.systemd1.Manager.StartTransientUnit \
  "app-test-$proc-2.scope" 'fail' \
  "[('Description', <'Application launched by test'>), ('PIDs', <[uint32 $proc]>), ('CollectMode', <'inactive-or-failed'>)]" \
  "@a(sa(sv)) []"

# echo
# echo "Unit for pid $proc"
# gdbus call --session \
#   --dest org.freedesktop.systemd1 \
#   --object-path /org/freedesktop/systemd1 \
#   --method org.freedesktop.systemd1.Manager.GetUnitByPID \
#   $proc

# If you sleep you'll see that 1st unit is now stopped
# sleep 1 

echo
echo "Both units are there!"
systemctl --user list-units | grep "app-test-$proc"

echo
echo "App cgroups"
cat /proc/$proc/cgroup
kill $proc

echo
echo "No more apps"
systemctl --user list-units | grep "app-test-$proc" || true
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
❯ bash /tmp/systemd-transient-debug.sh
(objectpath '/org/freedesktop/systemd1/job/1326',)

App cgroups
13:pids:/user.slice/user-1000.slice/user@1000.service
12:cpuset:/
11:devices:/user.slice
10:net_cls,net_prio:/
9:memory:/user.slice/user-1000.slice/user@1000.service
8:freezer:/
7:rdma:/
6:hugetlb:/
5:perf_event:/
4:misc:/
3:blkio:/user.slice
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/app-test-245730-1.scope
0::/user.slice/user-1000.slice/user@1000.service/app-test-245730-1.scope
(objectpath '/org/freedesktop/systemd1/job/1329',)

Both units are there!
  app-test-245730-1.scope                                                                                               loaded active     running   Application launched by test
  app-test-245730-2.scope                                                                                               loaded active     running   Application launched by test

App cgroups
13:pids:/user.slice/user-1000.slice/user@1000.service
12:cpuset:/
11:devices:/user.slice
10:net_cls,net_prio:/
9:memory:/user.slice/user-1000.slice/user@1000.service
8:freezer:/
7:rdma:/
6:hugetlb:/
5:perf_event:/
4:misc:/
3:blkio:/user.slice
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/app-test-245730-2.scope
0::/user.slice/user-1000.slice/user@1000.service/app-test-245730-2.scope

No more apps
```

**Comment by poettering** [comment]
the process is migrated to the first scope, and then on to the second, as per your request. This looks exactly how it should be?

**Comment by poettering** [comment]
(note, just issuing a method call or StartTransientUnit() is not enough, it just enqueues the scope generation, doesn't wait for it. You need for the returned job object to fire a JobComplete dbus signal before it is complete. systemd-run --scope will do that for you.)

**Comment by 3v1n0** [comment]
To put this in a real scenario what happens is:
 - Application start, crates a new transient unit
 - GNOME detects the application being started and create a new transient unit for it, with different name
 - The application checks whether the transient unit is the one it expected to be and it's not.

So, I was wondering how we can avoid this race to happen, given that when GNOME detects the PIDs, `GetUnitByPID` gives not the app-created unit, so we have no way to detect that the app is already part of an unit.

**Comment by jhenstridge** [comment]
> Is this correct to happen if there's not a flag saying "force migration to new-unit" even if one is set already (and by the launched process itself?

The process is always going to belong to some cgroup prior to the StartTransientUnit call being run, so it's not clear how you'd define which cgroups are valid "move from" sources and which aren't.

Maybe if the caller specified which cgroup it expected the pid to initially belong to you could detect such conflicts.

**Comment by 3v1n0** [comment]
Yeah, I can see that... But for example in our case, the app could support replacing the current unit whatever name it has, while GNOME desktop could only replace the name if it's matching a given pattern.

However, from what I can see, in the DBus API nothing is exposed when the process is moved from an unit to another, so it's also impossible to track this to readjust it in case the change is affecting a component.

**Comment by Werkov** [comment]
> * GNOME detects the application being started and create a new transient unit for it, with different name

This seems like the wrong step.
How does GNOME detect an application start? (asynchronously?)
Of course, it'd race with anything the application is free to do while it is already running.

You want to `StartTransientUnit()` early at application startup (like: fork,STU,exec)
and once only to prevent cgroup migrations of running workloads.

**Comment by 3v1n0** [comment]
It does it once it knows the pid of the new process, during the "launched" signal that is triggered by gdesktopappinfo at https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L3078

(or otherwise in other cases when doing manual launch).

**Comment by Werkov** [comment]
I see. Why cannot the app call `StartTransientUnit()` on itself when it can do this signalling?
(Note that launcher/direct start distinction is an [open topic](https://systemd.io/DESKTOP_ENVIRONMENTS/) (at least in that document).)

**Comment by 3v1n0** [comment]
> I see. Why cannot the app call `StartTransientUnit()` on itself when it can do this signalling?

Well, right now the problem is that _both the app and the launcher_ are calling `StartTransientUnit`, the problem for gnome-shell or any launcher is knowing whether the application supports or not this feature itself.

Maybe it could be controlled via a desktop-file entry, but this wouldn't still be enough for apps launched from command-line using the shell (i.e. alt+f2 launcher).

**Comment by Werkov** [comment]
The launcher should be:
```
fork
  sync call STU (1)
  execve(/bin/app)               ^^^ strip away this part on direct launch
    gdesktopapp... entry
       sync call STU (2)
       emit DBus signal
       ... actual run of the application
```

What is the problem? a) The call (1) asynchronous? b) Mismatching policy between launcher and app on what the target scope should be?
Something else -- that'd really fall under systemd scope?

**Comment by poettering** [comment]
I am not sure we can do anything about this. There's issue #6356 which asked for allowing to "lock" migration of processes from cgroups. But the kernel simply doesn't offer that, hence nothing we can do I think.

I guess we can close this as duplicate of #6356 though, right?

**Comment by 3v1n0** [comment]
Duplicate of #6356
