### ISSUE TITLE
systemd-boot crashes on aarch64

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#26951]
### systemd version the issue has been seen with

253

### Used distribution

OpenMandriva cooker

### Linux kernel version used

6.2

### CPU architectures issue was seen on

aarch64

### Component

systemd-boot

### Expected behaviour you didn't see

Boot EFI menu

### Unexpected behaviour you saw

Segfault when loading bootaa64.efi
Looking for a help how to debug this. Worth to mention that everything(except glibc) in OpenMandriva is compiled with LLVM/clang and linked with LLD 

![IMG_3128](https://user-images.githubusercontent.com/13415195/227269434-d01b49b3-337c-4777-bf0f-81c95fe689b5.jpeg)
![IMG_3127](https://user-images.githubusercontent.com/13415195/227269457-4ec0edcc-536d-4b57-9e89-804a6e5c5d51.jpeg)

**Comment by medhefgo** [comment]
Does the crash happen when you press a button at the menu or on its own?

Can you try latest git main? Make sure to pass `-Dbootloader=true -Db_sanitize=undefined` to meson.

Can you also try if disabling fast boot / enabling full input device initialization in the firmware options fixes this?

**Comment by tpgxyz** [comment]
Yes this crash happens on its own. Firmware here is uboot, so it just boots straight forward. 
Well trying systemd from git was already on my weekend todo list as i saw https://github.com/systemd/systemd/pull/26641 got merged

**Comment by medhefgo** [comment]
That diff doesn't tell me anything. What commits are being compared and what c/meson flags were used? Are you saying main branch is working or is it a clang-15 vs clang-16 thing?

Also, looking at the screenshots, the crash likely happens while looking for user input. Changing the timeout in `loader.conf` to `menu-hidden` or `menu-force` might make the crash happen earlier or fix it.

**Comment by tpgxyz** [comment]
I'm comparing systemd-253.1 with a latest archived systemd-bootaa64.efi know to me that works iirc it is from june 2022. I'll try with that options for the menu, but first i need to finish updating systemd to latest git to try your new EFI approach.

**Comment by tpgxyz** [comment]
Good news. I just compiled systemd git snapshot with `-Dbootloader=true` and it boots without any problem on my rockpro64 with uboot as firmware stage. Any chance to get this https://github.com/systemd/systemd/pull/26641  and related to be merged into systemd-stable ?

**Comment by medhefgo** [comment]
Nope, that PR has no business getting backported. You could try a reverse-bisection to see what commit actually fixed it.

**Comment by YHNdnzj** [comment]
Let's close this here. It's already fixed in the latest main, and there seems to be no interest in bisecting.
