### ISSUE TITLE
RuntimeMaxSec=0 is pointless

### ISSUE THREAD

**Issue by poodledoodle** [systemd/systemd#2697]
```
root@debian:~# > /tmp/shit.log 
root@debian:~# cat shit.sh 
#!/usr/bin/env bash

while :; do
    echo `date '+%s'`" shit" >> /tmp/shit.log
    sleep 0.2;
done
root@debian:~# ./shit.sh 
^C
root@debian:~# cat /tmp/shit.log 
1456143749 shit
1456143749 shit
1456143749 shit
1456143749 shit
1456143750 shit
1456143750 shit
root@debian:~# > /tmp/shit.log 
root@debian:~# cat /tmp/shit.log 
root@debian:~# cat /etc/systemd/system/runshit.service 
[Unit]
Description=shit logger

[Service]
ExecStart=/root/shit.sh
RuntimeMaxSec=0
root@debian:~# systemctl start runshit.service
root@debian:~# systemctl status runshit.service
● runshit.service - shit logger
   Loaded: loaded (/etc/systemd/system/runshit.service; static; vendor preset: enabled)
   Active: failed (Result: timeout) since Пнд 2016-02-22 14:23:06 EET; 5s ago
  Process: 1171 ExecStart=/root/shit.sh (code=killed, signal=TERM)
 Main PID: 1171 (code=killed, signal=TERM)
root@debian:~# cat /tmp/shit.log 
root@debian:~# systemctl --version
systemd 229
```

So, why do we need such complicated things as maintaining a compatibility layer between old timeout settings and the new ones if they are pointless? The result of using `RuntimeMaxSec=0` is same as if we just mask the service. Please, consider making the behaviour of zero value in `RuntimeMaxSec=` as it was before v229(I mean no timeout).

**Comment by falconindy** [comment]
RuntimeMaxSec didn't exist prior to v229. If you don't like what RuntimeMaxSec=0 does, don't specify it in the unit?

**Comment by poodledoodle** [comment]
@falconindy it is not about like/don't like. It is about transparency of understanding and ease of maintaining.

**Comment by falconindy** [comment]
What specific "old" and "new" timeout settings are you referring to? How do they clash? Why do you need to ever set RuntimeMaxSec?

**Comment by evverx** [comment]
> What specific "old" and "new" timeout settings are you referring to?

Maybe, https://github.com/systemd/systemd/blob/master/NEWS#L130

> - Most configurable timeouts in systemd now expect an argument of
>         "infinity" to turn them off, instead of "0" as before. The semantics
>         from now on is that a timeout of "0" means "now", and "infinity"
>         means "never". To maintain backwards compatibility, "0" continues to
>         turn off previously existing timeout settings.

But I'm not sure.

**Comment by poettering** [comment]
Hmm? RuntimeMaxSec= is a new addition in 229, and it never understood the "=0" syntax as disabling the timeout. 

Moreover, it actually defaults to "disabled", hence why would you bother disabling it explicitly?

There's no compat break here, and it's all pretty systematic now, and there's no need to disable this anyway, since it defaults to off. I really don't see what there could be to fix. This appears to be a misunderstanding. Hence closing.

**Comment by poodledoodle** [comment]
@poettering can you explain me, please, what's the need of restricting execution time of service with 0(zero) seconds? It won't start, so it is the same as just masking the service.

**Comment by poettering** [comment]
@poodledoodle there isn't afaics (except maybe for testing?), which makes me wonder why you set it like this in the first place?

**Comment by poodledoodle** [comment]
@poettering I set it because I've read the NEWS and I wanted to explore new features of systemd. So, if the new settings allow to use zero value as "zero seconds", then it means that I can set it and use it. But I didn't found any use case of it. And it seems like you didn't too. If I want to test something, I'll use the same values as I would use in production, but in a testing environment.  So, how can I understand why did you implement that feature(I mean new treating of zero value) if even you don't know how to use it? I think it makes systemd pointlessly complicated.

**Comment by falconindy** [comment]
An analogy: it hurts when you hit your own hand with a hammer. I don't know why you'd want to do that, but it's certainly possible. It doesn't make the hammer pointlessly complicated, it just means you need to know how to (and how not to) use it.

**Comment by poodledoodle** [comment]
@falconindy looks like you have a good sense of humour. But what if there is no need in hammer at all?

**Comment by poettering** [comment]
@poodledoodle well, i find it easier to grok, and very systematic, if "0" means "now" and "infinity" means never, everywhere. You are welcome to disagree, of course. But I am pretty sure we don't have the discuss this matter of taste here any further, thanks.

**Comment by poodledoodle** [comment]
@poettering

> i find it easier to grok

It is not easier since we have two different meanings of zero.

> and very systematic

It is not systematic since we have two different meanings of zero.

One more time: this change was absolutely pointless. Of course I respect your right to make things prettier and I wouldn't raise my eyebrow and start ranting if this change won't introduce such [ugly hacks](https://github.com/systemd/systemd/commit/89beff89edba592366b2960bd830d3f6e602c2c7).
