### ISSUE TITLE
ld.lld: error: undefined symbol: __ubsan_handle_type_mismatch_v1

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#26975]
### systemd version the issue has been seen with

git shapshot from 2023-03-24

### Used distribution

OpenMandriva cooker

### Linux kernel version used

6.2.7-server-1omv2390

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Compile and link without errors

### Unexpected behaviour you saw

https://gist.github.com/tpgxyz/0536fedb0b06fbcf7d4bebe9f278ab21

### Steps to reproduce the problem

Compile with LLVM/clang-16.x a systemd git snapshot form 2023-03-24
Full logs avaiable here https://abf.openmandriva.org/build_lists/296258

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/tpgxyz/0536fedb0b06fbcf7d4bebe9f278ab21
```

**Comment by medhefgo** [comment]
With clang you need to pass `-Db_lundef=false` to meson to make sanitizers work. Dunno why though.

**Comment by medhefgo** [comment]
Closing this, as it's a meson bug.

**Comment by tpgxyz** [comment]
@medhefgo hi i tried to build systemd with `-Db_lundef=false` and meson warning is gone, yet systemd fails to build as with the same error as original. Please take a second look.

https://abf.openmandriva.org/build_lists/296356

**Comment by medhefgo** [comment]
`LDFLAGS` contains `-Wl,--no-undefined`. Either strip that or append `-z undefs`.
