### ISSUE TITLE
manpage udevadm(8) does not mention --env switch

### ISSUE THREAD

**Issue by jaystrictor** [systemd/systemd#2699]
The manpage for `udevadm monitor` does not mention the switch `--environment`.

`--environment` is just an alias for `--property`. This should be explained in the manpage, because the switch is used in numerous examples on the net, e.g. on stackoverflow.

**Comment by poettering** [comment]
we generally do not document options we consider unofficial and support only for legacy, in order to keep the docs simply and short.
