### ISSUE TITLE
sleep-config: heads up, there's a nice btrfs-progs command now for getting the swapfile offset

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#26990]
### Component

other

### Is your feature request related to a problem? Please describe

I recently tried to confirm in the code, that `systemd` really just uses either admin supplied information (`resume` and `resume_offset`) or already active swapfiles/devices for selecting the one for hibernation (which AFAICS is the case)... just to be sure that it doesn't accidentally write the RAM to one that's unencrypted (and might have been silently attached by an attacker).

Anyway, when doing so I noticed that there's quite some code in https://github.com/systemd/systemd/blob/main/src/shared/sleep-config.c that disables auto-detection and so on in case of btrfs, like:
https://github.com/systemd/systemd/blob/main/src/shared/sleep-config.c#L737-L744

Recently, btrfs developers were so kind and by my request [added](https://github.com/kdave/btrfs-progs/commit/b16b35e074138dfca71145468050d65a7949b912) commands for detecting the btrfs-specific offset of swapfiles, namely `btrfs inspect-internal map-swapfile -r` (that gives output proper for `resume_offset`).<br>
Think progs version 6.1 was the first with it.

So this is merely a heads up (just close the feature request if not needed), that there is some nice way now to detect that.

Perhaps `systemd` could re-use this internally.

HTH,
Chris.

**Comment by poettering** [comment]
any reason why btrfs doesn#t just implement the FIEMAP ioctls for this, like everyone else?

**Comment by calestyo** [comment]
IIRC, the reason is that for btrfs this needs to give the virtual offset of a multi-device fs... while for swapfile the kernel needs the true physical offset in the (single) device.

**Comment by poettering** [comment]
I guess we can close now that 596873c10cb300733ed126b65fcc099b3f63598f has been merged, i.e. we support btrfs swap files natively now.
