### ISSUE TITLE
networkd unable to get DHCPv4 - "Stale file handle"

### ISSUE THREAD

**Issue by soundscape84** [systemd/systemd#27002]
### systemd version the issue has been seen with

253

### Used distribution

Arch 6.2.8

### Linux kernel version used

6.2.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

DHCPv4 address not forthcoming. Setting a static IP functions normally.

### Unexpected behaviour you saw

- `ip addr` shows no IP address assigned on interface ens18.
- `networkctl` status shows state as "degraded".
- `networkctl renew ens18` returns "Stale file handle" error.

### Steps to reproduce the problem

Reboot has no effect. Restarting `systemd-networkd` has no effect. Setting a static IPv4 address causes network to function as normal.

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/soundscape84/870bbf8a4a3c6a255270ae26c40e72c5

**Comment by yuwata** [comment]
Sorry for late response.

```
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: DISCOVER
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: Received message from RAW socket, processing.
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: OFFER
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: REQUEST (requesting)
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: Received message from RAW socket, processing.
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: received message was not an ACK, ignoring
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: Received message from RAW socket, processing.
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: NAK: wrong server-ID
Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: REBOOT in 0
```
What kind of messages received?? Could you try to dump DHCP packets?

**Comment by shimarin** [comment]
@soundscape84 Has your machine-id been generated properly?  If not, DHCPv4 fails and "networkctl renew" returns ESTALE.
In my similar case, executing "systemd-machine-id-setup" and reboot solved the issue.

**Comment by ssahani** [comment]
```Mar 27 14:29:15 omada systemd-networkd[16424]: ens18: DHCPv4 client: NAK: wrong server-ID```

Is there multiple DHCP servers in the network? If So please use https://www.freedesktop.org/software/systemd/man/systemd.network.html#DenyList= or https://www.freedesktop.org/software/systemd/man/systemd.network.html#AllowList=

**Comment by yuwata** [comment]
There is nothing we can do if the server sends wrong packet. Closing.
