### ISSUE TITLE
make distcheck failed

### ISSUE THREAD

**Issue by 0xAX** [systemd/systemd#2700]
### Submission type

Bug report
### systemd version the issue has been seen with

> master ( 7c7c0cb )
### Used distribution

> Fedora 23, x86_64
### In case of bug report: Unexpected behaviour you saw

```
../src/libsystemd-network/sd-lldp.c:27:27: fatal error: lldp-internal.h: No such file or directory
 #include "lldp-internal.h"
                           ^
compilation terminated.
../src/libsystemd-network/lldp-neighbor.c:25:27: fatal error: lldp-internal.h: No such file or directory
 #include "lldp-internal.h"
                           ^
```

full output can be found at semaphore - https://semaphoreci.com/systemd/systemd/branches/pull-request-2671/builds/7
### In case of bug report: Steps to reproduce the problem

> make V=1 -j10 distcheck CFLAGS='-g -O0 -ftrapv'

Why the `src/libsystemd-network/lldp-internal.h` was removed from the `Makefile.am` in the https://github.com/systemd/systemd/pull/2685/files#diff-c949f93d03f44a4217d7a138f9e2e54aL3308? In CI I see compilation error (see above). Also I'm able to reproduce this on local machine.

**Comment by poettering** [comment]
Fix waiting in #2704.
