### ISSUE TITLE
pid1: warn about badly named env vars referenced from ExecStart= env variable expansion

### ISSUE THREAD

**Issue by oficsu** [systemd/systemd#27036]
### systemd version the issue has been seen with

252

### Used distribution

Manjaro

### Linux kernel version used

6.1.12-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Journalctl contains the following messages:
```
systemd[123]: Started test1.service.
bash[123454]: 123
systemd[123]: Started test2.service.
bash[123455]: 123
systemd[123]: Started test2.service.
bash[123456]: 123
```

### Unexpected behaviour you saw

Journalctl contains the following messages:
```
systemd[123]: Started test1.service.
bash[123454]: /bin/bash: -c: option requires an argument
systemd[123]: Started test2.service.
bash[123455]: 123
systemd[123]: Started test3.service.
bash[123456]: 123
```

It looks like pair of `"` and `$` has some special undocumented meaning inside `ExecStart=` or there is a bug with basic environment variable substitution. The same with `'` instead of `"`

### Steps to reproduce the problem

1. Create the following unit file `~/.config/systemd/user/test1.service`:
```
[Service]
Type=simple
Environment="FOO=/usr/bin"
ExecStart=/bin/bash -c "$FOO/echo 123"
```

2. Create the following unit file `~/.config/systemd/user/test2.service` (note: space between `"` and `$`):
```
[Service]
Type=simple
Environment="FOO=/usr/bin"
ExecStart=/bin/bash -c " $FOO/echo 123"
```

3. Create the following unit file `~/.config/systemd/user/test3.service` (no space, but other syntax):
```
[Service]
Type=simple
Environment="FOO=/usr/bin"
ExecStart=/bin/bash -c "${FOO}/echo 123"
```

4. `systemctl --user daemon-reload`
5. `systemctl --user restart test1.service`
6. `systemctl --user restart test2.service`
6. `systemctl --user restart test3.service`
8. check logs with `journalctl`

**Comment by oficsu** [comment]
> did you read the man page of ExecStart= at all?

Can you please highlight the point I missed? I read `man systemd.service`, but there is nothing about a special meaning of `$` in `ExecStart=` section. It looks like `$` doesn't have a special meaning here. So, I don't see how this symbol could disappear from the last bash argument, `$FOO/echo 123` should be literally passed as single bash argument, am I right?

**Comment by poettering** [comment]
There's a whole section about this:

https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines

This is not that hard to find?

**Comment by oficsu** [comment]
Yes, I've seen the next sentence:

> Basic environment variable substitution is supported. Use "${FOO}" as part of a word, or as a word of its own, on the command line, in which case it will be erased and replaced by the exact value of the environment variable (if any) including all whitespace it contains, always resulting in exactly a single argument. **Use "$FOO" as a separate word on the command line**, in which case it will be replaced by the value of the environment variable split at whitespace,
resulting in zero or more arguments. For this type of expansion, quotes are respected when splitting into words, and afterwards removed.

But there is no clue, why the behavior of `"$FOO"` and `" $FOO "` is different. Because `" $FOO "` is a separate word. This is not a separate item (the term from [systemd.syntax](https://www.freedesktop.org/software/systemd/man/systemd.syntax.html#), **the term I searched man pages for**), but this is a definitely separate **word**. (I should note, I don't think, users should search for these details after hours of debugging at all, but ok, I can accept this answer —  bad design choice happens to every big tool)

The other, the real issue here is an irrelevant bash error message. Do you see that error stands for `-c: option requires an argument`? It's not something like `line 1: /echo: No such file or directory`. It's not about empty variable substitution, no. The whole item is gone; I don't expect that `/echo 123` can be a part of a variable name and can disappear too. No one expects this, and there is no any clue in logs, man pages... anywhere. When you encounter this, it's just magical behavior with irrelevant error messages and it is completely undebuggable. Maybe there should be a warning about empty substitutions (with a full name of a variable) in journalctl or something like... anything that can help users?

**Comment by poettering** [comment]
> Because `" $FOO "` is a separate word.

No. That might be a separate word, but a word distinct from `"$FOO"`.

**Comment by oficsu** [comment]
As mentioned above, I accept this interpretation. But what about `"$FOO/BAR"`. Do I understand correctly that the full name of the variable is not `FOO`, but `FOO/BAR` and, by substitution, we replace `FOO/BAR` with an (empty) value, so there is no a `/BAR` part after that?

**Comment by poettering** [comment]
> As mentioned above, I accept this interpretation. But what about `"$FOO/BAR"`. Do I understand correctly that the full name of the variable is not `FOO`, but `FOO/BAR` and, by substitution, we replace `FOO/BAR` with an (empty) value, so there is no a `/BAR` part after that?

yes

**Comment by oficsu** [comment]
> Yes, "FOO/echo 123" is a weird env var name, but you asked for this.

Shouldn't we change this behavior? I realize that it may be a bit hard to change substitution rules, so I don't propose this. But every such weird variable name is a potential bug; I think no one wants to use (consciously or not) such variable names because no one can even set them in the system (in POSIX at least). So, can't we just warn users about "impossible" vars?

**Comment by poettering** [comment]
Yeah, we should warn about env var names that are apparently bogus.

**Comment by twojstaryzdomu** [comment]
May I point out spaces or slashes aren't typically permitted in variable names in the shell. The error in output of `test1.service` reveals that the parser assumed both the slash and the space are part of the variable name. If the variable parser were to stop at the slash, like a shell for any path containing a variable name, there would be no ambiguity as to what `$FOO` is referring to. Doubtless `${FOO}` would dispel the confusion.
