### ISSUE TITLE
unlocking root partition with FIDO2 token

### ISSUE THREAD

**Issue by smoebody** [systemd/systemd#27055]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 37

### Linux kernel version used

6.2.7-200.fc37.x86_64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

When booting up with my FIDO2-Stick plugged in i expect to unlock the LUKS-encrypted root partition by touching the FIDO2-Stick.

### Unexpected behaviour you saw

I always have to provide the passphrase regardless whether the FIDO2-Stick is plugged in or not.

### Steps to reproduce the problem

use the following docs to enroll a FIDO2-Token on a luks-encrypted root-partition: 
https://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html 

additionally i tried further more steps from here without any luck:
http://daemons-point.com/blog/2022/11/25/fido2-mit-systemd-cryptenroll/

I found the following log excerpt possibly responsible. In case the full log is necessary i can provide on demand. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Mär 20 22:28:24 moe systemd-cryptsetup[556]: Token activation unsuccessful for device /dev/disk/by-uuid/99c9dbda-ed01-4587-8eb4-b7ba63502a1f: No such file or directory
Mär 20 22:28:24 moe systemd-cryptsetup[556]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/99c9dbda-ed01-4587-8eb4-b7ba63502a1f.
Mär 20 22:28:24 moe systemd-cryptsetup[556]: Activating volume luks-99c9dbda-ed01-4587-8eb4-b7ba63502a1f using token (systemd-fido2 type) -1.
Mär 20 22:28:24 moe systemd-cryptsetup[556]: dm versions   [ opencount flush ]   [16384] (*1)
Mär 20 22:28:24 moe systemd-cryptsetup[556]: dm status luks-99c9dbda-ed01-4587-8eb4-b7ba63502a1f  [ opencount noflush ]   [16384] (*1)
Mär 20 22:28:24 moe systemd-cryptsetup[556]: Automatic FIDO2 metadata discovery was not possible because missing or not unique, falling back to traditional unlocking.
```

**Comment by poettering** [comment]
Anyway, this is almost certainly a distro/initrd/packaging problem. Please contact your distro for details. This is outside of what we can control
