### ISSUE TITLE
Check uid rather than username when SSH to login

### ISSUE THREAD

**Issue by tristone13th** [systemd/systemd#27082]
### systemd version the issue has been seen with

systemd 249 (249.11-0ubuntu3.7)

### Used distribution

Ubuntu 22.04

### Linux kernel version used

6.2.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

Sometimes (though rare) multi-users will share 1 uid if they modify the `/etc/passwd` accordingly. Such as I can change the username `me` to share the same privilege as `root` when I name my uid and group both as 0 in the `/etc/passwd` file.

Though the public key for SSH has been put in the correct location, when login in as `me`, it still prompts me to enter the password. I checked the log file `/var/log/auth.log` and it says:

```
Authentication refused: bad ownership or modes for directory /home/me
```

So I think the current logic is when I log in as `me`, it will first identify `me` as `root`, it then will check the owner of `/home/me` should be `root`, but actually it is `me`, so it refuses to let me login using the public key, and so I need to enter the password each time.

I think it should let me login directly without prompting me to enter the password.

### Unexpected behaviour you saw

Prompts me to enter the password though I have put the public key in the right place.

### Steps to reproduce the problem

1. create a normal user and put the public key in the `~/.ssh/authorized_keys`, setup up your local environment with your private key.
2. change the user uid and gid in `/etc/passwd` to 0.
3. change `/etc/ssh/sshd_config` to permit root login.
4. login with the username, it will prompt you with the password.

**Comment by poettering** [comment]
Sorry, but that#s just a terrible practice. Don't do this.

But either way, systems is not involved in what you describe. That's between shadow/libc/ssh, not systemd. Closing.
