### ISSUE TITLE
[RFE] Do not downgrade features if upstream resolver indicates connectivity issues

### ISSUE THREAD

**Issue by pemensik** [systemd/systemd#27097]
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

Systemd-resolved is attempting to reduce used features on outgoing queries if it received SERVFAIL response. But sometime that is the best response it can get. If the upstream resolver has upstream connectivity issues itself, no feature reduction we do on resolved is going to help it.

It can signal more detailed reason using Extended DNS Error Code (EDE), defined by [RFC 8914](https://www.rfc-editor.org/rfc/rfc8914.html). 

### Describe the solution you'd like

If such detail is present in response and clearly indicates our features used are okay, but something else like connectivity is not, do not attempt to downgrade features used. Just schedule a retry and hope it will improve soon. Just nice to have feature. Keep the current behaviour if upstream server cannot indicate details.

Requested as separate issue by: https://github.com/systemd/systemd/pull/27078#issuecomment-1492300026

**Comment by xnox** [comment]
EDE look nice. For the ones that are defined, it is not clear what we need to do about them. The ones that are DNSSEC related it seems like resolved should treat them as DNSSEC is working and errors are fatal/permissive (depending on the resolved setting to perform DNSSEC in enforcing/opportunistic mode).

The rest do seem to indicate that server is responding as well as it can, and feature downgrade should not happen.

If EDE is missing or truncated, I guess we will continue to downgrade connections.

This RFC seems quite recent. Do popular DNS servers already implement it? I.e. both public ones (like 1.1.1.1  8.8.8.8 etc) and the ones one can deploy (knot bind etc). If they already do that, it means resolved is quite behind the curve of not supporting this and there is higher urgency to implement support for EDE.

**Comment by pemensik** [comment]
From the major providers it seems not working yet. Some already have it, for example knot-based odvr.nic.cz:

```
$ dig @odvr.nic.cz dnssec-failed.org

; <<>> DiG 9.18.13 <<>> @odvr.nic.cz dnssec-failed.org
; (4 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9676
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus): (EXRU)
;; QUESTION SECTION:
;dnssec-failed.org.		IN	A

;; Query time: 540 msec
;; SERVER: 185.43.135.1#53(odvr.nic.cz) (UDP)
;; WHEN: Sun Apr 02 17:44:29 CEST 2023
;; MSG SIZE  rcvd: 56
```

**Comment by mjl-** [comment]
I was searching if systemd-resolved supports EDE and arrived at this issue.

The situation seems to have changed, with cloudflare and google's public resolvers implementing EDE, and so does unbound:

https://developers.cloudflare.com/1.1.1.1/infrastructure/extended-dns-error-codes/
https://developers.google.com/speed/public-dns/docs/troubleshooting/domains#edelist
https://blog.nlnetlabs.nl/extended-dns-error-support-for-unbound/

The date on https://blog.cloudflare.com/unwrap-the-servfail/ indicates they supported it for a while.

Examples:

```
$ dig dnssec-failed.org @1.1.1.1

; <<>> DiG 9.19.17-1-Debian <<>> dnssec-failed.org @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32281
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 9 (DNSKEY Missing): (no SEP matching the DS found for dnssec-failed.org.)
;; QUESTION SECTION:
;dnssec-failed.org.             IN      A

;; Query time: 12 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Mon Sep 25 16:29:35 CEST 2023
;; MSG SIZE  rcvd: 103
```

```
$ dig dnssec-failed.org @8.8.8.8

; <<>> DiG 9.19.17-1-Debian <<>> dnssec-failed.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 54103
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; EDE: 9 (DNSKEY Missing): (No DNSKEY matches DS RRs of dnssec-failed.org)
;; QUESTION SECTION:
;dnssec-failed.org.             IN      A

;; Query time: 204 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Mon Sep 25 16:29:40 CEST 2023
;; MSG SIZE  rcvd: 97
```

Unbound:

```
$ dig dnssec-failed.org @127.0.0.1

; <<>> DiG 9.19.17-1-Debian <<>> dnssec-failed.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 3108
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus): (validation failure <dnssec-failed.org. A IN>: no keys have a DS with algorithm RSASHA1 from 68.87.76.228 for key dnssec-failed.org. while building chain of trust)
;; QUESTION SECTION:
;dnssec-failed.org.             IN      A

;; Query time: 1168 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Mon Sep 25 16:40:34 CEST 2023
;; MSG SIZE  rcvd: 213
```

**Comment by xnox** [comment]
@mjl- having public resolves support this is great! as one can develop and test code properly.

**Comment by rpigott** [comment]
I think this can be closed.

**Comment by poettering** [comment]
EDE is implemented now. Let's close.
