### ISSUE TITLE
Systemd service cannot run as higher priority before starting suspend.target or sleep.target 

### ISSUE THREAD

**Issue by Zesko** [systemd/systemd#27098]
### systemd version the issue has been seen with

253

### Used distribution

Manjaro or Arch Linux

### Linux kernel version used

Kernel 6.2 and 6.1

### CPU architectures issue was seen on

x86_64

### Component

systemctl 

### Expected behaviour you didn't see

KVM/QEMU guest is running on my host. When I enable suspend to corrupt something in the KVM guest.

**My expectation is:**
The KVM guest should first be automatically shut down slowly before starting the suspend.

I created a new systemd service script:

`$ sudo systemctl edit --force --full shutdown-KVM-before-suspend.service`

```
[Unit]
Description=Shutdown KVM guest before suspend or hibernate
Before=suspend.target

[Service]
Type=oneshot
ExecStart=/bin/sleep 10  # <--- Test if waiting 10 sec runs before suspend.
#ExecStartPost=/usr/bin/virsh shutdown linux-guest

[Install]
WantedBy=suspend.target
```

Then enable the service unit: `shutdown-KVM-before-suspend.service`.

### Unexpected behaviour you saw

I tried to run: `$ sudo systemctl start suspend.target` to start suspend or click **Suspend** button in KDE

 **but the issue is:
  my computer goes into suspend immediately and ignores `ExecStart=/bin/sleep 10`.**  Delaying 10 sec does not work before Suspend.

But the service unit will run later **after waking up** from the suspend. That is not my expectation. 

I am not sure, if Kernel ignores running systemd-service before suspend or systemd has a bug?

**Comment by Zesko** [comment]
I created a executable script `KVM.sleep` in `/usr/lib/systemd/system-sleep/`

```
#!/bin/sh

if [ "${1}" = "pre" ]; then
   # Before shutdown
   /usr/bin/virsh shutdown linux-guest
   /bin/sleep 10

elif [ "${1}" = "post" ]; then
   # After suspend 
   /bin/sleep 10
   /usr/bin/virsh start linux-guest
fi
```

Run `systemctl daemon-reload.

That works with KDE suspend as my expectation.

> I am not sure, if Kernel ignores running systemd-service before suspend or systemd has a bug?

But why systemd-service-unit script does not work before suspend. Maybe systemd had this bug with KDE suspend.

**Comment by YHNdnzj** [comment]
The unit that handles the actual suspend is `systemd-suspend.service`, which is ordered after `sleep.target` but _before_ `suspend.target`. By ordering your custom `shutdown-KVM-before-suspend.service` before `suspend.target`, they will both be pulled in by `suspend.target` and run _in parallel_ with `systemd-suspend.service`. Therefore, the system suspends as `systemd-suspend.service` starts, although `shutdown-KVM-before-suspend.service` hasn't finished starting.

You should order your service before `sleep.target`, as suggested in [systemd.special(7)](https://man.archlinux.org/man/systemd.special.7.en#Special_System_Units):

> sleep.target
> A special target unit that is pulled in by suspend.target, hibernate.target and hybrid-sleep.target and may be used to hook units into the sleep state logic.

**Comment by YHNdnzj** [comment]
P.S. `/usr/lib/systemd/system-sleep/` is handled by systemd-sleep binary itself. So it works as intended.

**Comment by Zesko** [comment]
Thanks, I will test it if it works

**Comment by Zesko** [comment]
Oh that works as my expectation.
