### ISSUE TITLE
Expose a mechanism to read journald without needing to link against libsystemd or spawn an external command

### ISSUE THREAD

**Issue by dead-claudia** [systemd/systemd#27109]
### Component

systemd-journald

### Is your feature request related to a problem? Please describe

I have multiple motivating reasons:

1. The thread pinning requirement for `sd_journal_t` is commonly not possible to satisfy in most multi-threaded runtimes for technical reasons.
	- [Go intentionally doesn't provide any way to run anything on a dedicated OS-level thread, and they've resisted proposals to add this functionality in the past.](https://github.com/golang/go/issues/23758)
	- Node.js has similar limitations in some areas, though I *believe* execution contexts (both the main and those for workers) correspond 1:1 with OS threads (I might be wrong, though). You'd still have to use a native extension to access the APIs, though, since neither Node.js nor its underlying JS engine V8 expose any sort of native FFI to JS directly.
	- [In Tokio in Rust, it's possible to get an escape hatch, but it mucks with the scheduler.](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) (One *could* just spawn an OS thread directly in Rust, so this isn't much of a concern.)
2. In some runtimes (like Node.js), FFI isn't first-class and is often relegated to a third-party library. Even ignoring 1 and 2, this makes it a lot more difficult to integrate.
3. All calls block, which makes it even more awkward to use in async runtimes.

### Describe the solution you'd like

A `/run/systemd/journal/ctl` socket exposing the various operations `sd_journal` exposes.

<details>
<summary>Example protocol</summary>

On socket open:

1. Client: Send protocol version
2. Client: Send `SD_JOURNAL_*` open flag mask
3. Server: If user privileges not sufficient, respond with failure ack and close
4. Server: Open `/var/log/journal`/`/run/log/journal` for reading, respond with failure ack and close if missing
5. Server: Respond with success ack

On socket close, treat similarly to `sd_journal_close`.

Client messages:

- Seek head/tail
- Seek monotonic timestamp with boot ID
- Seek realtime timestamp
- Seek cursor
- Seek `n`th previous entry
- Seek `n`th next entry
- Get list of field names used in the journal
- Get allowed values for specified field
- Get list of fields for current entry, optionally with an "available-only" flag
- Get field data for current entry with max data length
	- A reader only interested in length could just read this with a "max data length" of 0
- Set match filter with an "or" list of `FIELD=value` "and" lists

Server messages:

- Success ack
- Failure ack
- Seek success ack with number of values skipped + optional current cursor
- Get used field names success ack with list of field names
- Get allowed values success ack with list of values
- Get field list success ack with list of field names
- Get field value success ack with true byte length + possibly-truncated field value
	- The true length is something not directly returned by `sd_journal_get_data`, but I know it's available.
	- The field value would only be truncated by the max data length, not any stateful threshold.

Nothing here is to imply a particular type of protocol (like binary, JSON, or textual).
</details>

In theory, the `sd_journal` API itself as well as `journalctl` could be (re-)built on top of this to provide thread independence at a mild hit to performance.

Additional support for IDs isn't necessary - the algorithm for each is already documented, and it's easy to just re-implement it from the docs alone:

- IDs are just parsed V4 UUIDs
- `sd_id128_get_machine()` -> 128-bit hex string from `/etc/machine-id`
- `sd_id128_get_boot()` -> V4 UUID from `/proc/sys/kernel/random/boot_id`
- `sd_id128_OP_app_specific(app_id)` -> `HMAC_SHA256(sd_id128_OP(), app_id)`
- `sd_id128_get_invocation()` -> `$INVOCATION_ID` environment variable for most cases

### Describe alternatives you've considered

1. Just biting the bullet and using `libsystemd` directly and not using higher-level languages like Go. That's what I'm currently doing, but only because it's faster than any of the other alternatives (and my use case is actually pretty critical for me).
2. Implementing this in userland. While obviously technically possible, I *really* don't want to go through that same song and dance a second time. Also, there's a number of special efficiency gains to be had by implementing this natively, like only using one shared journal descriptor, resuming only matching connections, and leveraging the format and `pread` to do things in batch better.
3. Stabilizing the journal file format to the extent that backwards compatibility is maintained between versions and just reading it all manually. Technically the easiest for you all ([and it's already documented](https://systemd.io/JOURNAL_FILE_FORMAT/)), but I strongly doubt you all would be willing to expose the format publicly anytime soon.
4. Using `journalctl --follow`. This *can* work, but I'd rather avoid that overhead for something that could be potentially high-throughput if I can help it. (Also why the suggested protocol offers a way to read field lengths without having to read the whole field itself.)

**Comment by dead-claudia** [comment]
> I don't follow. What are you trying to do? Build a dynamic binary on a new distro that shall work on an old distro? That's a mess, not just with Rust or Go or any other language. Just don't do that. Everyone knows that...

Rust is just generally a mess with glibc, but that's unique to Rust and not the point of this feature request.

**Comment by dead-claudia** [comment]
I'll remove that point to make the other points stand out a bit better.

**Comment by poettering** [comment]
accessing the journal via IPC means it's going to be a lot slower. I guess performance is not the goal of these web programming languages though?

you could just use systemd-journal-gatewayd, which allows you to access the journal via http.

Also, what's wrong with invoking journalctl as child process with --output=export? You would get the full data, relatively efficiently, out-of-prcess through a pipe, with stable interface?

**Comment by dead-claudia** [comment]
Closing as I don't feel like pursuing this anymore.
