### ISSUE TITLE
Cryptsetup is not activated by systemd if _netdev option used in /etc/crypttab

### ISSUE THREAD

**Issue by dpantel** [systemd/systemd#27101]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

6.1.0-0.deb11.5-amd64

### CPU architectures issue was seen on

None

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Activation of systemd-cryptsetup@*.service unit, calling cryptsetup to ask for a password, etc.

### Unexpected behaviour you saw

Startup proceeds without activating systemd-cryptsetup@\*.service unit. Cryptsetup never prompts to unlock the volume; systemd-cryptsetup@\*.service is listed as "inactive" after startup.

### Steps to reproduce the problem

This entry in `/etc/crypttab` activates cryptsetup
```
vol    UUID=<xxx>    none
```

This entry does not; no mention of cryptsetup in syslog
```
vol    UUID=<xxx>    none    _netdev
```

**Comment by arvidjaar** [comment]
Is `remote-cryptsetup.target` enabled and acrive?

**Comment by YHNdnzj** [comment]
This is the upstream bug tracker for latest two systemd versions. Earlier versions are unsupported here and should be reported to your distro bug tracker instead.

**Comment by YHNdnzj** [comment]
Let's close this here. If you can reproduce it with latest systemd stable, feel free to ask for reopen :)

**Comment by dpantel** [comment]
@arvidjaar That was it, thank you. Any hints as to what should have enabled it in the first place?
