### ISSUE TITLE
systemd-networkd: parse DHCP option 119 (Domain Search List)

### ISSUE THREAD

**Issue by mikken** [systemd/systemd#2710]
### Submission type

Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux ARM
### Description

Currently systemd-networkd looks into DHCP option 15 (DNS domain suffix) to put into its domain list used for searching. Since I'd like to have 2 domains in the list, I need it to also parse option 119 (Domain Search List) when `UseDomains=yes` is set.

**Comment by sjpotter** [comment]
this impacts me too.  In GCE google's DHCP provides multiple search domains and google.internal is one of them and many tools try to access just "metadata" instead of "metadata.google.internal".

**Comment by marineam** [comment]
For reference, the only slightly funky thing about implementing DHCP's Domain Search List is that it uses DNS style name compression. The equivalent option in DHCPv6 has already been implemented back in https://github.com/systemd/systemd/pull/924 and I'll bet `dhcp6_option_parse_domainname` can be easily reused for v4.

**Comment by thetuxkeeper** [comment]
Is there any progress on this issue? this impacts us too. We need to specify more than one domain for the dhcp clients.

**Comment by wonderfly** [comment]
Echoing what @thetuxkeeper asked. Is this on the roadmap?

**Comment by jonesmz** [comment]
Was recently effected by the lack of option 119. Could we get a comment on if this is being planned for any future release?

**Comment by poettering** [comment]
Well, adding this is definitely on the roadmap, but to actually happen it would need somebody work on it. If you want it to happen quickly best would be to contribute a patch!

**Comment by wonderfly** [comment]
> If you want it to happen quickly best would be to contribute a patch

@poettering I sorted out a patch, #5932. Anybody you have in mind could be a good reviewer?
