### ISSUE TITLE
`LogTarget=null` causes systemd unable to poweroff or reboot.

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#27105]
### systemd version the issue has been seen with

253.2

### Used distribution

Archlinux

### Linux kernel version used

6.1.22-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

`systemctl reboot` `systemctl poweroff` works as usual (<= 253.1)

### Unexpected behaviour you saw

`systemctl reboot` `systemctl poweroff` hang with no details. I see a suspicious message but don't know if it is related:

```
Apr 02 12:46:05 umount[707]: umount: /run/credentials/systemd-tmpfiles-setup.service: no mount point specified.
```

but `reboot -f` still works from another tty.

### Steps to reproduce the problem

upgrade systemd to 253.2 and reboot/poweroff.

**Comment by bluca** [comment]
please enable debug level logging with systemctl log-level debug and then attach the logs

**Comment by enihcam** [comment]
> please enable debug level logging with systemctl log-level debug and then attach the logs

could you give me an example of how to enable debug level, log-level debug, and how to export logs? thanks.

**Comment by enihcam** [comment]
> `systemctl log-level debug`
> 
> after rebooting
> 
> `journalctl -b -1`

`systemctl log-level debug` doesn't give me any more useful messages, and

```
~ $ sudo journalctl -b -1
Data from the specified boot (-1) is not available: No such boot ID in journal
```

however, after `systemctl reboot`, the terminal is cleared + hung, but left with only one message: `Failed to umount /var/log`

FYI the mount info:
```
~ $ mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4096k,nr_inodes=988887,mode=755,inode64)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=1586344k,nr_inodes=819200,mode=755,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
/dev/sda2 on / type btrfs (rw,relatime,thread_pool=2,ssd_spread,noacl,space_cache,subvolid=5,subvol=/)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
ramfs on /run/credentials/systemd-sysctl.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-tmpfiles-setup-dev.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
tmpfs on /var/log type tmpfs (rw,nosuid,nodev,size=1586344k,nr_inodes=819200,mode=755,inode64)
/dev/sda1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
ramfs on /run/credentials/systemd-tmpfiles-setup.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
```

also, `home.mount` is missing, because i disabled systemd-homed by removing `pam_systemd_home.so` from pam.d configuration.

```
~ $ sudo systemctl status home.mount
Unit home.mount could not be found.
```

Hope these info will be enough for your troubleshooting. Thanks.

**Comment by YHNdnzj** [comment]
Journal from earlier boots is lost if you mount the whole `/var/log` as tmpfs... This is terrible practice.

Please use persistent storage for `/var/log/journal` and try again. `journalctl -b -1` should give you debug logs.

**Comment by YHNdnzj** [comment]
> systemctl log-level debug doesn't give me any more useful messages

It just sets the debug level, so that's expected. You need to reboot after enabling debug log, and upload the journal from the last boot.

**Comment by enihcam** [comment]
> Journal from earlier boots is lost if you mount the whole `/var/log` as tmpfs... This is terrible practice.
> 
> Please use persistent storage for `/var/log/journal` and try again. `journalctl -b -1` should give you debug logs.

i don't understand.
1. `systemctl log-level debug` sets the debug level and immediately takes effect.
2. `systemctl reboot` does not work but i still have the prompt from another tty to get the journal in which i find nothing but few umount errors i mentioned.
3.  `reboot -f` is almost as the same as a hard reboot, and it just works without giving any errors.

**Comment by YHNdnzj** [comment]
Hmm, try `SYSTEMD_LOG_LEVEL=debug systemctl reboot` then?

**Comment by enihcam** [comment]
> SYSTEMD_LOG_LEVEL=debug systemctl reboot

```
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Setting wall message "".
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.5 path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=SetWallMessage cookie=2 reply_cookie=0 signature=sb error-name=n/a error-message=n/a
Got message type=method_return sender=:1.2 destination=:1.5 path=n/a interface=n/a member=n/a  cookie=9 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
Executing org.freedesktop.login1.Manager RebootWithFlags dbus call.
Sent message type=method_call sender=n/a destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=RebootWithFlags cookie=3 reply_cookie=0 signature=t error-name=n/a error-message=n/a

Broadcast message from root@localhost on pts/1 (Mon 2023-04-10 23:19:57 CST):

The system will reboot now!

Got message type=method_return sender=:1.2 destination=:1.5 path=n/a interface=n/a member=n/a  cookie=16 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Bus n/a: changing state RUNNING → CLOSED
```

**Comment by enihcam** [comment]
![hang](https://user-images.githubusercontent.com/7010097/231486589-951bf45a-f28c-4711-8c6f-e1c37d916d84.jpg)

**Comment by yuwata** [comment]
I guess this is another variant of my recent commit d2ebd50d7f9740dcf30e84efc75610af173967d2, which was backported to v253 in v253.2 https://github.com/systemd/systemd-stable/commit/0417b2875521424104d27229c13681c03baf9290, and v253.3 fixes the issue. Could you test v253.3?

**Comment by enihcam** [comment]
> I guess this is another variant of regression caused by my recent commit [d2ebd50](https://github.com/systemd/systemd/commit/d2ebd50d7f9740dcf30e84efc75610af173967d2), which was backported to v253 in v253.2 [systemd/systemd-stable@0417b28](https://github.com/systemd/systemd-stable/commit/0417b2875521424104d27229c13681c03baf9290), and v253.3 [systemd/systemd-stable@4f4e0ba](https://github.com/systemd/systemd-stable/commit/4f4e0bab0d66ca6501432854aa3d3fcb53887796) fixes the issue. Could you test v253.3?


Upgraded to v253.3 but the issue remains.

```
~ $ pacman -Qi systemd
Name            : systemd
Version         : 253.3-3
Description     : system and service manager
Architecture    : x86_64
URL             : https://www.github.com/systemd/systemd
Licenses        : GPL2  LGPL2.1
Groups          : None
Provides        : nss-myhostname  systemd-tools=253.3  udev=253.3
...
```

**Comment by yuwata** [comment]
Hm, then, please provide debugging logs as requested in the above. Otherwise there is almost nothing we can do.

**Comment by enihcam** [comment]
> Hm, then, please provide debugging logs as requested in the above. Otherwise there is almost nothing we can do.

interesting, i made the following change then `systemctl reboot` worked.

```diff
diff --git a/systemd/system.conf.d/override.conf b/systemd/system.conf.d/override.conf
index 25c5b3e..d85a87b 100644
--- a/systemd/system.conf.d/override.conf
+++ b/systemd/system.conf.d/override.conf
@@ -1,6 +1,6 @@
 [Manager]
-LogLevel=notice
-LogTarget=null
+LogLevel=debug
+LogTarget=journal
 DumpCore=no
 CrashReboot=yes
 TimerSlackNSec=60000
diff --git a/systemd/user.conf.d/override.conf b/systemd/user.conf.d/override.conf
index ad776bc..f7290f1 100644
--- a/systemd/user.conf.d/override.conf
+++ b/systemd/user.conf.d/override.conf
@@ -1,6 +1,6 @@
 [Manager]
-LogLevel=notice
-LogTarget=null
+LogLevel=debug
+LogTarget=journal
 TimerSlackNSec=60000
 DefaultEnvironment=GOGC=800
 DefaultLimitNOFILE=1048576
```

**Comment by YHNdnzj** [comment]
-> https://github.com/systemd/systemd/pull/27259

> I guess this is another variant of regression caused by my recent commit [d2ebd50](https://github.com/systemd/systemd/commit/d2ebd50d7f9740dcf30e84efc75610af173967d2).

Turned out to be true I guess 😂

**Comment by enihcam** [comment]
Can systemd provide LTS release model?
I caught 3 bugs in half a year where 2 of them are regressions. :)

**Comment by enihcam** [comment]
> @enihcam It does, sort of: https://github.com/systemd/systemd-stable

that's exactly where the bugs are caught. ;)
