### ISSUE TITLE
HWDB entry for Logitech G502 X conflicts with other logitech mouses

### ISSUE THREAD

**Issue by aruhier** [systemd/systemd#27118]
### systemd version the issue has been seen with

253.2

### Used distribution

Gentoo

### Linux kernel version used

6.2.9-x86_64

### CPU architectures issue was seen on

x86_64

### Component

hardware database files

### Expected behaviour you didn't see

My Logitech G Pro X Superlight in Wireless is configured at 800 DPI in its onboard memory. I expect Libinput to apply this DPI by default, in Wireless or when plugged in.

This DPI can be tweaked and saved in the onboard memory of the mouse, therefore I should be able to set any value and not be restricted to a list of possibilities.

### Unexpected behaviour you saw

Since commit dede07d, libinput doesn't respect the DPI of my Logitech G Pro X Superlight in Wireless, configured at 800 DPI. The sensitivity is lower. Plugging in the mouse uses the correct sensitivity.

I see 2 problems:
1/ As the DPI can be tweaked in the profile of the mouse, I don't think a list of DPIs should be exposed by udev.
2/ Different mouses can share the same receiver, therefore it does not seem to be a reliable way to expose the information of a mouse. For example, the Logitech G502 X is apparently shipped with the same receiver as the Logitech G Pro X Superlight.

### Steps to reproduce the problem

Set the DPI to 800 in the onboard memory of a Logitech G Pro X Superlight. In wireless, the DPI is lower than expected, but is ok when plugged in.

Revert dede07d and the sensitivity is as expected (verify with the libinput tool `mouse-dpi-tool`).

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Here is the output of `udevadm` on the receiver on systemd 252.7 (FYI, it's before commit dede07d, the MOUSE_DPI property is not there): https://gist.github.com/aruhier/fb2f6141aa4e518d9f3bf495652672d0

Udev in systemd 253.2 exposes `MOUSE_DPI=1200@1000 *2400@1000 3200@1000 6400@1000`.
```

**Comment by keszybz** [comment]
How does one set the DPI in the onboard memory?

**Comment by aruhier** [comment]
From Solaar on Linux (https://pwr-solaar.github.io/Solaar/usage), or from the logitech software on Windows.

**Comment by aruhier** [comment]
Here is a screenshot of Solaar to show how it works on this mouse. The DPI is an integer, and is in the range of 100 to 25600.

![solaar](https://user-images.githubusercontent.com/1174685/230374623-0a3829a3-6430-44ff-8442-60dde7be0c32.png)

**Comment by aruhier** [comment]
Any news about this one? As a direct action, I think that a revert of dede07d3d would be enough before a solution for generics wireless receiver is found.

**Comment by yuwata** [comment]
Waiting in #27336.
