### ISSUE TITLE
systemd.socket manpage: clarification

### ISSUE THREAD

**Issue by opk12** [systemd/systemd#27116]
### Component

systemd

### Is your feature request related to a problem? Please describe

[systemd.socket(5)](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) discusses the service unit name that must match the socket unit name, in the section `Description`. As this is heavily dependent on the setting of `Accept=`, there should be a few words in the section `Accept=` that point to this discussion.

On a second thought, maybe the words `(also see above)` in the section `Accept=` are meant to point to that discussion. If that's the intended meaning, it should be explicit.

**Comment by poettering** [comment]
→ #27972
