### ISSUE TITLE
libgcrypt dependency is missing in configure.ac

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#2711]
### Submission type

[ X] Bug report

[ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> master
### Used distribution

> Fedora rawhide
### Problem

1) sh autogen.sh && ./configure
2) make
#### Actual behavior

...
src/resolve/resolve-tool.c:20:20: fatal error: gcrypt.h: No such file or directory
...
src/shared/gcrypt-util.c:22:20: fatal error: gcrypt.h: No such file or directory
...
#### Expected behavior

Either bail out when running autogen.sh or ifdef the code that requires gcrypt.h.

**Comment by net147** [comment]
For me, it also fails to link if --disable-gcrypt is specified as part of configure but gcrypt headers/libraries are present:
src/shared/gcrypt-util.c:29: error: undefined reference to 'gcry_control'
src/shared/gcrypt-util.c:50: error: undefined reference to 'gcry_md_get_algo_dlen'
src/shared/gcrypt-util.c:53: error: undefined reference to 'gcry_md_open'
src/shared/gcrypt-util.c:57: error: undefined reference to 'gcry_md_write'
src/shared/gcrypt-util.c:59: error: undefined reference to 'gcry_md_read'
src/shared/gcrypt-util.c:32: error: undefined reference to 'gcry_check_version'
src/shared/gcrypt-util.c:38: error: undefined reference to 'gcry_control'
src/shared/gcrypt-util.c:39: error: undefined reference to 'gcry_control'

@keszybz Ideas?

**Comment by bluecmd** [comment]
+1. I get gcry linking errors even though I use --disable-gcrypt. Using 229.
