### ISSUE TITLE
libsystemd C API documentation

### ISSUE THREAD

**Issue by jtmoon79** [systemd/systemd#27124]
### Component

systemd

### Is your feature request related to a problem? Please describe

I am trying to call `libsystemd.so` C API endpoints. To understand how they work, I'm having to read through the C code. I'm new to this code base so it's quite a lot to hold in my head.

In my case, I want to iterate through all of a journal file's entries. I am figuring out how to do this slowly, but it's more than a chore than it should be. I'm using `python-systemd` to make some calls I want my other Rust program to make, but I'm tracing the Python calls and then investigating the `libsystemd` API calls that are made, the parameters passed, and their return values.

After scrounging around in the two code bases, [`systemd`](https://github.com/systemd/systemd/) and [`python-systemd`](https://github.com/systemd/python-systemd), I found important function [`sd_journal_enumerate_data`](https://github.com/systemd/systemd/blob/16a9ad557de7173c182e9587a9cc0ca146293ec8/src/libsystemd/sd-journal/sd-journal.c#L2649)
```lang-c
_public_ int sd_journal_enumerate_data(sd_journal *j, const void **data, size_t *size)
```
But I wasn't sure how that relates to [`sd_journal_next`](https://github.com/systemd/systemd/blob/16a9ad557de7173c182e9587a9cc0ca146293ec8/src/libsystemd/sd-journal/sd-journal.c#L979)
```lang-c
_public_ int sd_journal_next(sd_journal *j)
```
(when should I call either? what exactly does each do?)

Understanding expected behavior and return values is quite a bit of work.

### Describe the solution you'd like

It'd be great if the `systemd` project added API documentation.

[Doxygen](https://www.doxygen.nl/manual/docblocks.html) is a mature, well known project that can parse code and code comments and generate documentation pages ([examples](https://www.doxygen.nl/results.html)).
If developers code comment the C-code in a particular way then Doxygen will generate some very user-friendly HTML pages. These documentation pages could be hosted at the systemd website.

I'm sure there other tools, as well.

### Describe alternatives you've considered

Relates to #235 _sd-bus API documentation is incomplete_ which is a subsection of the work I'm requesting here. But #235 was closed before being fully completed.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by mrc0mmand** [comment]
The libsystemd stuff is (mostly) already documented, though: https://www.freedesktop.org/software/systemd/man/#S

From what you've mentioned, `sd_journal_enumerate_data()` has a man page [0] as well as `sd_journal_next()`.

[0] https://www.freedesktop.org/software/systemd/man/sd_journal_enumerate_data.html#
[1] https://www.freedesktop.org/software/systemd/man/sd_journal_next.html#

**Comment by keszybz** [comment]
libsystemd is documented, with the exception of some calls under sd-device. As @mrc0mmand wrote, the functions you mention are documented and even have code examples in the man pages.

**Comment by poettering** [comment]
Have you tried googling? It's a really excellent tool to finding stuff on the internet. For example, try this:

https://www.google.com/search?q=systemd+sd_journal_enumerate_data+documentation

Highly recommended.

**Comment by jtmoon79** [comment]
> The libsystemd stuff is (mostly) already documented, though: https://www.freedesktop.org/software/systemd/man/#S

Wow, I scrolled right past section _Manual Pages_ on https://systemd.io/ . 🤦
Pardon the noise. Thanks!
