### ISSUE TITLE
Unable to restart systemd-networkd.service when systemd-networkd.socket is active

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#27125]
### systemd version the issue has been seen with

systemd-252.4-598.9.hs+fb.el9

### Used distribution

CentOS 9 Hyperscale build

### Linux kernel version used

5.12.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

While `systemd-networkd.socket` is active, I should be able to restart systemd-networkd.service successfully.

### Unexpected behaviour you saw

When I try to restart systemd-networkd.service when systemd-networkd.socket is active, I get `systemd-networkd[199814]: Could not setup manager: Bad address` and systemd-networkd.service no longer starts. However on boot, both units are active.

### Steps to reproduce the problem

Here is what my network config looks like:
```
$ cat /etc/systemd/network/1-fb_networkd-eth0.network 
# This file is maintained by Chef. Do not edit, all changes will be
# overwritten. See fb_networkd/README.md

[Match]
MACAddress = <omitted>
Name = eth0

[Network]
Address = <omitted>
IPv4LLRoute = true
IPv6AcceptRA = true

[Link]
RequiredForOnline = true

[IPv6AcceptRA]
UseMTU = false
UseAutonomousPrefix = false
UseOnLinkPrefix = false
DHCPv6Client = false

[Address]
Address = <omitted>
PreferredLifetime = 0
```

Run `systemctl restart systemd-networkd.service` and it will fail to start with the message above when systemd-networkd.socket is active.
If you mask the socket unit with `systemctl mask systemd-networkd.socket` then systemd-networkd.service will restart successfully.

I strace-ed pid 1 when restarting systemd-networkd and this appears to be the source of the problem:
```
[pid 354023] signalfd4(6, [INT USR2 TERM], 8, SFD_CLOEXEC|SFD_NONBLOCK) = 6
[pid 354023] fcntl(3, F_GETFD)          = 0
[pid 354023] fcntl(3, F_SETFD, FD_CLOEXEC) = 0
[pid 354023] newfstatat(3, "", {st_mode=S_IFSOCK|0777, st_size=0, ...}, AT_EMPTY_PATH) = 0
[pid 354023] getsockopt(3, SOL_SOCKET, SO_TYPE, [3], [4]) = 0
[pid 354023] getsockname(3, {sa_family=AF_NETLINK, nl_pid=1, nl_groups=0x000551}, [128 => 12]) = 0
[pid 354023] getsockopt(3, SOL_SOCKET, SO_PROTOCOL, [0], [4]) = 0
[pid 354023] setsockopt(3, SOL_NETLINK, NETLINK_EXT_ACK, [1], 4) = 0
[pid 354023] setsockopt(3, SOL_NETLINK, NETLINK_GET_STRICT_CHK, [1], 4) = 0
[pid 354023] setsockopt(3, SOL_NETLINK, NETLINK_PKTINFO, [1], 4) = 0
[pid 354023] bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 16) = -1 EINVAL (Invalid argument)
[pid 354023] getsockname(3, {sa_family=AF_NETLINK, nl_pid=1, nl_groups=0x000551}, [16 => 12]) = 0
[pid 354023] getsockopt(3, SOL_NETLINK, NETLINK_LIST_MEMBERSHIPS, NULL, [0]) = -1 EFAULT (Bad address)
```

It's possible this could be an environment issue? We don't have SELinux enabled but not sure what else it could be.

**Comment by DaanDeMeyer** [comment]
I'm unable to reproduce the issue in a Fedora 37 mkosi image booted with qemu as follows:

```
mkosi --kernel-command-line-extra=systemd.wants=systemd-networkd.socket -f qemu
systemctl restart systemd-networkd
```

**Comment by anitazha** [comment]
Suspecting conflicts with BPF. So I guess it's confined to our fleet.

**Comment by anitazha** [comment]
Confirmed that this was a bug in BPF (undecided if this should be fixed in core or the user program) preventing both units from running together.
