### ISSUE TITLE
systemd-networkd-wait online times out with ipv6 disabled

### ISSUE THREAD

**Issue by suezzelur** [systemd/systemd#2713]
With ipv6 disabled using sysctl parameters (net.ipv6.conf.all.disable_ipv6), systemd-networkd-wait-online times out on reboot with the /run/systemd/netif/links/2 stating ADMIN_STATE=configuring and ROUTES= empty. Adding a patch like the below to networkd gets rid of the issue. What is the expected way to completely disable ipv6 using systemd and not face any network link bringup issues?

[systemd-wait-online-fix.patch](https://gist.github.com/suezzelur/4df0b62df729311295e1)

**Comment by johannbg** [comment]
Why do you want to disable ipv6 in the first place?

**Comment by arvidjaar** [comment]
My provider does not support IPv6; my CPE does not have any trace of IPv6; why would I want to configure it in the first place?

**Comment by johannbg** [comment]
Because your ISP might suddenly switch to ipv6, which would mean you would have reconfigure all your machines, applications aren't being tested with ipv6 disabled ( and most likely will break if link local is not available) and in some cases expect it to be available, come out of the box configured to listen on it by default etc. 

Again why are you actually disabling it in the first place instead of leaving it running but unconfigured? 
What are you thinking you are gaining by this? 

BTW you need to disable ipv6 on the kernel command line if you intend to disable it.

**Comment by suezzelur** [comment]
I disable it in a deterministic system where I do not expect ISPs to change and I do not want IPV6 addresses to lurk around. I have control over applications, so that is not a problem. Lets say it is similar to say GCE(compute engine) which disables ipv6 in the images. I use sysctl to do it.

**Comment by poettering** [comment]
Yeah, we should probably cover this.

**Comment by qrpike** [comment]
+1 also having this issue

**Comment by ssahani** [comment]
I think this should be fixed by https://github.com/systemd/systemd/pull/4224/commits/5d2eee9359aab10db33356fd9633cd1cf3afed8d.

**Comment by dm0-** [comment]
@ssahani I tried testing that commit using `sysctl net.ipv6.conf.all.disable_ipv6=1`, and it seems that file always exists regardless of the sysctl setting.  The difference is that it is empty when IPv6 is disabled.  I tried modifying your patch and sent it as #4235, which works correctly for me.  Can you verify this?

**Comment by net147** [comment]
Note this issue also occurs if IPv6 is enabled on the system but LinkLocalAddressing=no is set in [Network] section.

**Comment by ssahani** [comment]
@net147 yes I reproduced it. Please try with https://github.com/systemd/systemd/commit/fb81f57f4d467d0db8397775352b1f04e38f5313.

**Comment by software-artificer** [comment]
@ssahani, I have tried your patch and it does not work for me (just for clarity: playing around inside of nspawn container with `LinkLocalAddressing` set to `no`).

```
test ~ # cat /run/systemd/netif/links/2 
# This is private data. Do not parse.
ADMIN_STATE=configuring
OPER_STATE=routable
NETWORK_FILE=/etc/systemd/network/80-container-host0.network
DNS=
NTP=
DOMAINS=
ROUTE_DOMAINS=
LLMNR=yes
MDNS=no
ADDRESSES=10.0.0.6/26
ROUTES=
```
```
test ~ # networkctl status host0
● 2: host0
       Link File: n/a
    Network File: /etc/systemd/network/80-container-host0.network
            Type: ether
           State: routable (configuring)
      HW Address: aa:a7:53:93:94:a7
         Address: 10.0.0.6
```
```
test ~ # /usr/lib/systemd/systemd-networkd-wait-online -i host0
Event loop failed: Connection timed out
```

**Comment by ssahani** [comment]
works for me 

root@rawhide:/lib/systemd/network $ systemd-detect-virt 
systemd-nspawn


~~~
root@rawhide:~ $ networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  4 guest            ether              routable    unmanaged 
  5 host             ether              routable    configured
~~~

~~~
[Match]
Name=host

[Network]
DHCP=yes
LinkLocalAddressing=no
Address=192.168.10.1/24

~~~

**Comment by software-artificer** [comment]
Fails for me with the following:
```
test ~ # systemd-detect-virt 
systemd-nspawn
```
```
test ~ # cat /etc/systemd/network/80-container-host0.network 
[Match]
Name=host0
Virtualization=container

[Network]
DHCP=yes
LinkLocalAddressing=no
Address=10.0.0.6/26
```
```
test ~ # networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 host0            ether              routable    configuring

2 links listed.
```
```
test ~ # networkctl status host0
● 2: host0
       Link File: n/a
    Network File: /etc/systemd/network/80-container-host0.network
            Type: ether
           State: routable (configuring)
      HW Address: aa:a7:53:93:94:a7
         Address: 10.0.0.6
```
However, made it work by setting `DHCP=ipv4` in `.network` file
```
test ~ # cat /etc/systemd/network/80-container-host0.network 
[Match]
Name=host0
Virtualization=container

[Network]
DHCP=ipv4
LinkLocalAddressing=no
Address=10.0.0.6/26
```
Is that considered working?

**Comment by ssahani** [comment]
`DHCP=` should not matter also if IPv6 disabled for the interface does it work for you?
```
cat /proc/sys/net/ipv6/conf/host/disable_ipv6
1
```

**Comment by software-artificer** [comment]
Just tried that, but unfortunately, doesn't help.

**Comment by software-artificer** [comment]
@ssahani, my apologies, after extensive testing and playing around, I can confirm that your patch indeed fixed an issue. All my interfaces are now properly `configured` and `systemd-networkd-wait-online` works as expected. Thanks a lot.

**Comment by ssahani** [comment]
Thanks for testing and confirm.  Fix PR https://github.com/systemd/systemd/pull/7012

**Comment by L3P3** [comment]
Hello, for the kernel we use, there is `ipv6.disable=1` setted which causes the sysctl directory to not even exist so we cannot set `net.ipv6.conf.all.disable_ipv6=1`! I have no power over the kernel parameter... How can I tell `systemd-networkd-wait-online.service` to ignore ipv6? Maybe you should not rely on that sysfs entry but check if it even exists before. If the key is not even existing, it means we have no ipv6 present...
