### ISSUE TITLE
test: add reproducer for recent daemon-reexec regression

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#27139]
Add reproducer for regression https://github.com/systemd/systemd/issues/27106 introduced by https://github.com/systemd/systemd/pull/26956.
See also https://github.com/systemd/systemd/pull/26964, https://github.com/systemd/systemd/pull/26982, https://github.com/systemd/systemd/pull/27107, and https://github.com/systemd/systemd/pull/27112.

**Comment by bluca** [comment]
@mrc0mmand any idea what we could do here? We have rexec tests, but they apparently missed this

**Comment by mrc0mmand** [comment]
> @mrc0mmand any idea what we could do here? We have rexec tests, but they apparently missed this

I have a couple of ideas, but I need to tackle a couple of other things first. So, I can definitely look into this, unless Yu already started.

**Comment by yuwata** [comment]
I have not started yet.
