### ISSUE TITLE
systemd-resolved prefers IPv4 DNS servers

### ISSUE THREAD

**Issue by wanneut** [systemd/systemd#27142]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu jammy

### Linux kernel version used

5.15.0-1030-kvm

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

resolved starts with the first DNS server configured, and then stick with it until we notice some issue with it, which is where we then switch to the next one, and so on — if we reached the end of the list, then we start from the beginning again.

This is a followup to issue 16322. Since  Lennart Poettering is describing a very different behavior than I can see, it is now a bug and not an enhancement any more.

Also _I_ would much prefer fallowing the RFC 6724. Which is a little bit bigger than one sentence but basically breaks down in most cases to section 6: prefer the matching scope of the preferred source address which is usually the native IPv6 address. RFC 6724 explicitly says address for communication because you can never know if behind different addresses are different destinations or one one multi homed. And btw: If you get IPv4 and IPv6 DNS server addresses it is in most of the cases a multi homed DNS server. So arvidjaar is wrong that it does not apply.

Both ways are better than what is going on at the moment.

### Unexpected behaviour you saw

Even if resolved receives the IPv6 DNS via RA first AND the IPv4 DNS server (via DHCP) is not working, resolved uses only the IPv4 variant and fails to resolve names for a while. So neither the "starts with the first DNS server" nor the "we then switch to the next one" is true. (Or the later not in time to get DNS resolved without timeouts.)

### Steps to reproduce the problem

Run a dual stack setup and announce a non existing IPv4-DNS-server. Delay the DHCP packets with tc.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
resolvectl status
Link 2 (ens3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 2001:4860:4860::8888
       DNS Servers: 2001:4860:4860::8888 2620:fe::fe:10

Link 3 (ens9)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.10.3
       DNS Servers: 192.168.10.4 192.168.10.3 192.168.10.5


journalctl -eu systemd-resolved
systemd-resolved[453]: Using degraded feature set TCP instead of UDP for DNS server 192.168.10.3.
systemd-resolved[453]: Using degraded feature set UDP instead of TCP for DNS server 192.168.10.3.
systemd-resolved[453]: Using degraded feature set TCP instead of UDP for DNS server 192.168.10.3.
...
```

**Comment by poettering** [comment]
hmm?

you have two interfaces, both with DNS servers. In that case resolved will actually ask on both interfaces and use the first positive reply it gets (or last negative if it only gets negative replies).

So, on the first interface we'll us ethe ipv6 server, on the second one the ipv4 one. The latter might fail of course, as you describe.

I see nothing to fix here?

**Comment by wanneut** [comment]
> So, on the first interface we'll us ethe ipv6 server, on the second one the ipv4 one.
No. This would be the expected behavior. It try ONLY 192.168.10.3 and fails.

**Comment by poettering** [comment]
please provide debug output, i.e. `systemd-analyze log-level systemd-resolved debug` and then `resolvectl flush-cashes && resolvectl query google.com` or so. Then paste the log output this generated for the full query

**Comment by poettering** [comment]
Closing due to lack of response.
