### ISSUE TITLE
Unable to suspend to ram

### ISSUE THREAD

**Issue by ambasta** [systemd/systemd#2714]
### Submission type

[ x] Bug report

[ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd-228

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Gentoo
### In case of bug report: Expected behaviour you didn't see

> systemctl suspend should suspend to ram
### In case of bug report: Unexpected behaviour you saw

> Attempting to suspend via systemctl suspend leads to Failed to suspend system via logind: Sleep verb not supported, alternately on lid close/open systemd-logind[266]: Requested operation not supported, ignoring.
### In case of bug report: Steps to reproduce the problem

> I am not sure how others can reproduce the issue. However I have no swap ( and donot want one for hybrid sleep or hibernate) I literally just want the sleep functionality provided by echo mem > /sys/power/state

This is my logind.conf

```
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
HandlePowerKey=suspend
HandleSuspendKey=suspend
HandleHibernateKey=suspend
HandleLidSwitch=suspend
#HandleLidSwitchDocked=ignore
PowerKeyIgnoreInhibited=yes
SuspendKeyIgnoreInhibited=yes
HibernateKeyIgnoreInhibited=yes
LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#UserTasksMax=4096

```

And finally, inhibitors list

systemd-inhibit --list --mode=block 

```
 Who: amitprakash (UID 1000/amitprakash, PID 543/gnome-settings-)
What: handle-power-key:handle-suspend-key:handle-hibernate-key
 Why: GNOME handling keypresses
Mode: block

 Who: gdm (UID 105/gdm, PID 338/gnome-settings-)
What: handle-power-key:handle-suspend-key:handle-hibernate-key
 Why: GNOME handling keypresses
Mode: block
```

2 inhibitors listed.

**Comment by arvidjaar** [comment]
Does it work if you manually execute `echo mem > /sys/power/state`?

**Comment by ambasta** [comment]
Yes it does.

**Comment by michich** [comment]
What does this say?:
busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanSuspend
and this?:
grep "" /sys/power/{state,disk}
Do you have anything in a file sleep.conf or in a directory sleep.conf.d under /etc/systemd/ or /usr/lib/systemd/ or /run/systemd/ ?

**Comment by ambasta** [comment]
busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanSuspend
`s "na"`

 grep "" /sys/power/{state,disk}

```
/sys/power/state:freeze mem
grep: /sys/power/disk: No such file or directory

```

cat /etc/systemd/sleep.conf

```
[Sleep]
SuspendMode=suspend
SuspendState=mem
HibernateMode=suspend
HibernateState=mem
HybridSleepMode=suspend
HybridSleepState=mem
```

**Comment by michich** [comment]
It should work if you remove sleep.conf, or at least the *Mode= assignments in it. By assigning those, you're asking systemd to write these settings to /sys/power/disk, which does not exist in your kernel (presumably CONFIG_HIBERNATION=n).

**Comment by ambasta** [comment]
Hey,

This works perfectly.
Thanks!

**Comment by poettering** [comment]
I am pretty sure we should not make suspending unavailable if there's bogus hibernation config around...

**Comment by keszybz** [comment]
This seems to be fixed now (probably since a long while):
```console
$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanSuspend
s "yes"
$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanHibernate
s "na"
```
(with the config from https://github.com/systemd/systemd/issues/2714#issuecomment-187676476 and with the defaults.)
