### ISSUE TITLE
NVMe by-id/ symlink changed when device serial has leading whitespace starting from v249

### ISSUE THREAD

**Issue by jlebon** [systemd/systemd#27155]
### systemd version the issue has been seen with

v253

### Used distribution

Fedora 37+, RHEL 9.2

### CPU architectures issue was seen on

None

### Component

systemd-udevd

### Expected behaviour you didn't see

[This commit](https://github.com/systemd/systemd/commit/5118e8e71dda211d20e34ec8d3012186ba27d3d3) changed how the `by-id/` symlink is created for NVMe devices where the device serial has leading whitespace. E.g. with a serial of `      foobar`, it changed from

```
nvme-QEMU_NVMe_Ctrl__foobar -> ../../nvme0n1
```

to

```
nvme-QEMU_NVMe_Ctrl_______foobar -> ../../nvme0n1
```

This is noticeable when upgrading from RHEL 8.6 to RHEL 9.2, but I don't think there's anything RHEL-specific about the change.

Changes in symlinks in turn break userspace programs that rely on them not changing across updates.

Should a backcompat rule be added back for this? Or is the upstream stance that stable symlinks are best effort but not guaranteed?

We don't want to re-introduce https://github.com/systemd/systemd/issues/19309 though, which is what the commit fixes, so this would require tweaking it further.

**Comment by yuwata** [comment]
Note, the issue seems not caused by the 5118e8e71dda211d20e34ec8d3012186ba27d3d3, but caused by ea0f4578a7e90f5227817058bfb11bb91dbb1431.
