### ISSUE TITLE
systemctl list-dependencies: red instead of gray dot for stopped service

### ISSUE THREAD

**Issue by benjarobin** [systemd/systemd#2718]
### Submission type

[ X] Bug report

[X ] Request for enhancement (RFE)

> I have no idea if this is a bug or expected.
### systemd version the issue has been seen with

> systemd-228
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> I think the dot should be gray (the same dot displayed with `systemctl status` )
### In case of bug report: Unexpected behaviour you saw

> The red dot should only be displayed for failed service
### In case of bug report: Steps to reproduce the problem

> Stop a service that is enabled, then run `systemctl list-dependencies`

**Comment by shibumi** [comment]
@benjarobin could you please specify when you think the dot should be grey.. if the service fails or if the service stopped or.. you know what I mean..
