### ISSUE TITLE
Backspace and Backslash keys not working on ThinkPad X230

### ISSUE THREAD

**Issue by ml-foo** [systemd/systemd#27195]
### systemd version the issue has been seen with

253.3-1.1

### Used distribution

OpenSUSE Tumbleweed

### Linux kernel version used

6.2.9-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

Backspace and backslash key working after upgrading to systemd-253.3-1.1 on a ThinkPad X230 / NitroPad X230.

### Unexpected behaviour you saw

hwdb was picking up config for X200 Tablet, hence the backspace key was now set to lock the screen and the backslash (for en_us keyboard layout) or in my case '#' key for en_gb keyboard layout was set to the menu key - effectively doing nothing.

I could trace this back to this commit:
https://github.com/systemd/systemd/commit/a5c0ad9a9a2964079a19a1db42f79570a3582bee

Changing
`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X2*Tablet*:*`
back to:
`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X2*T*:*`
in /usr/lib/udev/hwdb.d/60-keyboard.hwdb

and running:
systemd-hwdb update
and a subsequent reboot resolved the issue for me

output of my modalias:
cat /sys/devices/virtual/dmi/id/modalias
`dmi:bvncoreboot:bvrCBET4000heads:bd01/01/1970:br4.0:efr0.0:svnLENOVO:pn2324HV6:pvrThinkPadX230:rvnLENOVO:rn2324HV6:rvrThinkPadX230:cvnLENOVO:ct9:cvr:sku:`

I think the `rvrThinkpadX230` in my modalias made it match with the `X2*T*.*` bit of the X200 Tablet config.

Maybe an additional section that matches the modalias for "X200T" as per the above commit would be necessary - for example:
`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X200T*:*`

Though this will be difficult for me to judge as I don't have a tablet version of a Thinkpad myself.

### Steps to reproduce the problem

Have a ThinkPad which modalias matches the new X2* tablet version and notice how keys no longer work as expected.

**Comment by mattbeshara** [comment]
I also had this occur on an X230 running Arch.  Downgrading to `systemd-253.1-1`, `systemd-libs-253.1-1`, and `systemd-sysvcompat-253.1-1` works around the problem.
