### ISSUE TITLE
Large tables not displayed when rendering man pages on PDF

### ISSUE THREAD

**Issue by sebastiancarlos** [systemd/systemd#27213]
### systemd version the issue has been seen with

253

### CPU architectures issue was seen on

None

### Component

other

### Expected behaviour you didn't see

Man pages should render correctly when formatted as PDF.

### Unexpected behaviour you saw

When trying to render the man page for `systemd.unit` as PDF, the table named "Table 4. Specifiers available in unit files" doesn't render because of an error on the Groff formatter. I haven't checked other man pages, but there could be similar errors with PDF output too.

### Steps to reproduce the problem

`$ man -t systemd.unit > systemd.unit.pdf`

Note errors from Groff:
```
troff: random_roff_file:487: warning [p 5, 5.0i, div '3tbd1,0', 0.0i]: can't break line
troff: random_roff_file:500: warning [p 5, 5.0i, div '3tbd4,0', 0.0i]: can't break line
troff: random_roff_file:2003: warning [p 18, 9.3i, div '3tbd10,1', 0.0i]: can't break line
troff: random_roff_file:2008: warning [p 18, 9.3i, div '3tbd11,0', 0.0i]: can't break line
warning: file 'random_roff_file', around line 1913:
  table wider than line width
troff: random_roff_file:2241: warning [p 20, 4.9i, div '3tbd6,2', 0.2i]: can't break line
error: page 21: table will not fit on one page; use .TS H/.TH with a supporting macro package
```

Also reproduced by running Groff directly:
`$ groff -Tpdf -mandoc -c -t systemd.unit_source_roff_file > systemd.unit.pdf`

man-db version: `2.11.2`
groff version: `1.22.4`

**Comment by matt-daugherty** [comment]
I ran into the same issue:

```
$ man -t systemctl | ps2pdf - systemctl.pdf

error: page 11: table will not fit on one page; use .TS H/.TH with a supporting macro package

```

It looks like the content it is having trouble with is `Table 1. is−enabled output`

Fedora Linux 38 (Workstation Edition) x86_64
Kernel 6.2.11-300.fc38.x86_64
bash 5.2.15

**Comment by matt-daugherty** [comment]
[systemctl.pdf](https://github.com/systemd/systemd/files/11303954/systemctl.pdf)

Here is the PDF that is generated in case it is helpful

**Comment by keszybz** [comment]
Sorry, but there isn't much we can do about this. We don't generate pdfs ourselves and we cannot support their formatting. We try to make do with the docbook pipeline, but it is quite inflexible in how the output is generated. Many things are not rendered correctly even in the supported man and html outputs. Despite our best efforts, it's hard to improve this. Maybe some day we'll switch to some better pipeline.
