### ISSUE TITLE
(Arch Nvidia x86) When booting, main linux drive (not EFI), partuuid times out

### ISSUE THREAD

**Issue by QueenOfDancingStars** [systemd/systemd#27218]
### systemd version the issue has been seen with

253

### Used distribution

Arch 2023.04.01

### Linux kernel version used

6.2.1-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-boot, udevadm

### Expected behaviour you didn't see

System not booting with no errors, and drivers mounting properly.

### Unexpected behaviour you saw

When attempting to boot my Arch installation after updating my system, it did not boot correctly. The error log will be below. Not quite sure what caused this to happen, since nothing big seemed to be updated. I suspected an overcurrent problem but even with nothing plugged in the same problem is still happening.
![7E5A6A9B-BA7F-419E-B6C9-68EB0FF45E32](https://user-images.githubusercontent.com/70240564/231310190-823692b4-4a91-4f18-82cf-129c75280b48.jpeg)
This first image demonstrates the error which I got when booting.
![C6040EF3-A06C-43A2-A315-BD7784514980](https://user-images.githubusercontent.com/70240564/231310251-4083efdd-3490-45c4-922a-3151b6a52af2.jpeg)
![78BB165E-5D19-4CCF-AD81-1B06B1C5FC7F](https://user-images.githubusercontent.com/70240564/231310256-1f660b5f-d486-492c-a79e-a05f8e9bf90a.jpeg)
These two demonstrate the IDs shown in fstab and blkid, and when I checked, they were identical to the ones in the error. (The ID to look out for is “F959eddd…”)
![D8D27DA0-5725-48A9-852B-4E4FE57291B1](https://user-images.githubusercontent.com/70240564/231310352-8c4e8ebb-3225-4e20-8ddf-c2ce10426cc6.jpeg)
This last image demonstrates what I got when using udevadm. I’ve never used this command so I don’t really know what I am looking for, but I hope it gives useful information.

### Steps to reproduce the problem

1. Pacman -Syuu
2. Reboot

**Comment by yuwata** [comment]
The photo about blkid result is badly cropped... And, it seems that the UUID does not match with listed in fstab.

1. Please check UUIDs in fstab
2. Please check kernel command line (you can get it by `cat /proc/cmdline`), especially, `root=` option or so.
3. Please check your boot loader settings.

Anyway, this seems not an issue in systemd, but misconfiguration when the system is updated. Closing.

@Pipenguim Please contact to a support forum of your distro at first.
