### ISSUE TITLE
systemd: systemd crashed in function unit_free_requires_mounts_for and path_hash_func during constant stress test restart

### ISSUE THREAD

**Issue by ALTNT** [systemd/systemd#27222]
### systemd version the issue has been seen with

241-7~deb10u1

### Used distribution

deepin

### Linux kernel version used

4.19.0-arm64-desktop

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

We are installing the deepin system on an arm machine and doing a stress test with constant restarts, expecting the system to start normally every time

### Unexpected behaviour you saw

During the stress test, we found two black screen problems caused by systemd errors.
1、 When the unit_gc_sweep function is executed to reclaim the sysinit.target unit, unit_gc_mark_good（in src/core/manager.c） returns a null pointer "other" when traversing "u->dependencies[UNIT_REFERENCES]"，causing "other->gc_marker == gc_marker + GC_OFFSET_UNSURE to directly" crashed. The following is the stack displayed by the core file I obtained：
```
(gdb) bt
#0  0x0000ffff9dcf6b68 in kill () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000aaaae065ef9c in crash (sig=11) at ../src/core/main.c:197
#2  <signal handler called>
#3  0x0000aaaae061f188 in unit_gc_mark_good.isra.5.lto_priv.426 (gc_marker=9064, u=<optimized out>, u=<optimized out>) at ../src/core/manager.c:1093
#4  0x0000aaaae062c820 in unit_gc_sweep (u=0xaaab0f504770, gc_marker=gc_marker@entry=9064) at ../src/core/manager.c:1160
#5  0x0000aaaae062c780 in unit_gc_sweep (u=0xaaab0f50f4d0, gc_marker=9064) at ../src/core/manager.c:1120
#6  0x0000aaaae065bd04 in manager_dispatch_gc_unit_queue (m=0xaaab0f4e9ae0) at ../src/core/manager.c:1180
#7  manager_loop (m=0xaaab0f4e9ae0) at ../src/core/manager.c:2883
#8  invoke_main_loop (m=0xaaab0f4e9ae0, ret_reexecute=0xfffff546c71a, ret_retval=0xfffff546c71c, ret_shutdown_verb=0xfffff546c730, ret_fds=0xfffff546c720, ret_switch_root_dir=0xfffff546c740, 
    ret_switch_root_init=0xfffff546c738, ret_error_message=0xfffff546c728) at ../src/core/main.c:1842
#9  0x0000aaaae05c05b4 in main (argc=2, argv=0xfffff546ca28) at ../src/core/main.c:2625
(gdb) f 3
#3  0x0000aaaae061f188 in unit_gc_mark_good.isra.5.lto_priv.426 (gc_marker=9064, u=<optimized out>, u=<optimized out>) at ../src/core/manager.c:1093
1093    ../src/core/manager.c: 没有那个文件或目录.
(gdb) list
1088    in ../src/core/manager.c
(gdb) p other
$1 = (Unit *) 0x0


static void unit_gc_mark_good(Unit *u, unsigned gc_marker) {
        Unit *other;
        Iterator i;
        void *v;

        u->gc_marker = gc_marker + GC_OFFSET_GOOD;

        /* Recursively mark referenced units as GOOD as well */
        HASHMAP_FOREACH_KEY(v, other, u->dependencies[UNIT_REFERENCES], i)
                if (other->gc_marker == gc_marker + GC_OFFSET_UNSURE)
                        unit_gc_mark_good(other, gc_marker);
}
```
I have checked the unit_add_dependency function to add dependency to the code of u->dependencies[UNIT_REFERENCES], here one has executed assert(other), so I don’t understand why traversing the hashmap of u->dependencies[UNIT_REFERENCES] returns a null pointer.

2、In addition, we have reproduced another situation where the hash array returns a null pointer , which occurs in the assert(q) assertion error in the path_hash_func function：
```
4月 10 16:19:08 uos-PC systemd[1]: Started Reboot.
4月 10 16:19:08 uos-PC systemd[1]: Reached target Reboot.
4月 10 16:19:08 uos-PC systemd[1]: Shutting down.
4月 10 16:19:08 uos-PC systemd[1]: Assertion 'q' failed at ../src/basic/hash-funcs.c:17, function path_hash_func(). Aborting.
4月 10 16:19:08 uos-PC systemd-coredump[5369]: Due to PID 1 having crashed coredump collection will now be turned off.
4月 10 16:19:08 uos-PC systemd[1]: Caught <ABRT>, dumped core as pid 5368.
4月 10 16:19:08 uos-PC systemd[1]: Freezing execution.
4月 10 16:19:08 uos-PC kernel: systemd: 1757 output lines suppressed due to ratelimiting
4月 10 16:19:08 uos-PC systemd-coredump[5369]: Process 5368 (systemd) of user 0 dumped core.
                                                
                                                Stack trace of thread 5368:
                                                #0  0x0000ffffba4ffb68 kill (libc.so.6)
                                                #1  0x0000aaaab0b97f9c crash (systemd)
                                                #2  0x0000ffffba687698 n/a (linux-vdso.so.1)
                                                #3  0x0000ffffba687698 n/a (linux-vdso.so.1)
                                                #4  0x0000ffffba4ff814 raise (libc.so.6)
                                                #5  0x0000ffffb97cb490 n/a (n/a)
4月 10 16:20:26 uos-PC systemd-journald[400]: Forwarding to syslog missed 1058 messages.


void path_hash_func(const char *q, struct siphash *state) {
        size_t n;

        assert(q);
        assert(state);
```
Sorry, we did not get the core file this time, but according to the "Shutting down." log, we can find that the problem occurred in the execution of the manager_free function. The following is the stack information I analyzed and processed:
`main->manager_free->manager_clear_jobs_and_units->unit_free->unit_free_requires_mounts_for->hashmap_get2->bucket_hash->path_hash_func`
This seems to be another problem about traversing the "u->manager->units_requiring_mounts_for" hash table returning a null pointer:
```
static void unit_free_requires_mounts_for(Unit *u) {
        assert(u);

        for (;;) {
                _cleanup_free_ char *path;

                path = hashmap_steal_first_key(u->requires_mounts_for);
                if (!path)
                        break;
                else {
                        char s[strlen(path) + 1];

                        PATH_FOREACH_PREFIX_MORE(s, path) {
                                char *y;
                                Set *x;

                                x = hashmap_get2(u->manager->units_requiring_mounts_for, s, (void**) &y);
```

### Steps to reproduce the problem

We just reproduce the problem by  constant restarts

**Comment by dtardon** [comment]
_[Canned reply follows]_

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
