### ISSUE TITLE
timesyncd fails with assertion on 32bit system with 64bit time_t e.g. RISCV32

### ISSUE THREAD

**Issue by kraj** [systemd/systemd#27241]
### systemd version the issue has been seen with

253.3

### Used distribution

Yocto Project (tip of trunk)

### Linux kernel version used

6.1.20-yocto-standard

### CPU architectures issue was seen on

other

### Component

systemd-timesync

### Expected behaviour you didn't see

Normal run.

### Unexpected behaviour you saw

aborts with assertion error

```
Assertion '((uintptr_t) _p) % __alignof__(struct timespec) == 0' failed at src/timesync/timesyncd-manager.c:448, function manager_receive_response(). Aborting.

Thread 1 "systemd-timesyn" received signal SIGABRT, Aborted.
```

GDB backtrace

```
0x94838a9a in __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44      pthread_kill.c: No such file or directory.
(gdb) bt
#0  0x94838a9a in __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x94838acc in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x948023f2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x947f2842 in __GI_abort () at abort.c:79
#4  0x94acb84c in log_assert_failed (text=0x369 <error: Cannot access memory at address 0x369>, file=0x6 <error: Cannot access memory at address 0x6>, line=-1802442724,
    func=0x1 <error: Cannot access memory at address 0x1>) at ../git/src/basic/log.c:889
#5  0x68806284 in manager_receive_response (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x6880d310) at ../git/src/timesync/timesyncd-manager.c:448
#6  0x94b6d96a in source_dispatch (s=0x688121e0) at ../git/src/libsystemd/sd-event/sd-event.c:3676
#7  0x94b6d61c in sd_event_dispatch (e=0x6880d510) at ../git/src/libsystemd/sd-event/sd-event.c:4252
#8  0x94b6e220 in sd_event_run (e=0x6880d510, timeout=18446744073709551615) at ../git/src/libsystemd/sd-event/sd-event.c:4313
#9  0x94b6e432 in sd_event_loop (e=0x6880d510) at ../git/src/libsystemd/sd-event/sd-event.c:4334
#10 0x68802e4e in run (argc=<optimized out>, argv=<optimized out>) at ../git/src/timesync/timesyncd.c:217
#11 main (argc=<optimized out>, argv=<optimized out>) at ../git/src/timesync/timesyncd.c:231
```

The issue is due to alignment of `struct timespec` being 8 on rv32 because time_t is 64bit by default on this architecture.
and uintptr_t is 4

see the call sequence below

https://github.com/systemd/systemd/blob/main/src/timesync/timesyncd-manager.c#L449
https://github.com/systemd/systemd/blob/main/src/basic/socket-util.h#L178
https://github.com/systemd/systemd/blob/main/src/basic/socket-util.h#L187
https://github.com/systemd/systemd/blob/main/src/fundamental/macro-fundamental.h#L363

### Steps to reproduce the problem

```
git clone git://git.yoctoproject.org/poky
. ./oe-init-build-env
echo 'DISTRO="poky-altcfg"' >> conf/local.conf
echo 'MACHINE="qemuriscv32"' >> conf/local.conf
echo 'IMAGE_FEATURES:append = " dbg-pkgs tools-debug"' >> conf/local.conf
bitbake core-image-minimal
runqemu
```

Once qemu boots run it under gdb

```
gdb /lib/systemd/systemd-timesyncd
```

**Comment by yuwata** [comment]
@kraj Is it reproducible with glibc?

**Comment by kraj** [comment]
> @kraj Is it reproducible with glibc?

Yes happens with latest glibc release

**Comment by yuwata** [comment]
@kraj Could you test #27253?

**Comment by poettering** [comment]
@kraj any chance you could try to compile #27254 for me on riscv32. The goal of that PR is to turn this issue in a compile-time error already, so that we can systematically fix the issue. 

Would love if someone with access to riscv32 would try to compile that PR on riscv32. It should fail of course, and would be good to get a paste of the failure this generates. If that PR compiles cleanly it would not do its job. it's one of the rare cases where build time failures indicate success and build time successes indicate failure ;-)

**Comment by kraj** [comment]
> @kraj any chance you could try to compile #27254 for me on riscv32? The goal of that PR is to turn this issue into a compile-time error already, so that we can systematically fix the issue.
> 
> Would love if someone with access to riscv32 would try to compile that PR on riscv32. It should fail of course, and would be good to get a paste of the failure this generates. If that PR compiles cleanly it would not do its job. it's one of the rare cases where build time failures indicate success and build time successes indicate failure ;-)

yep. Thanks for the patch. I will test it on rv32 qemu later today

**Comment by kraj** [comment]
@yuwata the patch quoted here moves the error from runtime assertion to compile time assertion. but it does not fix the underlying problem. So I think this issue is closed prematurely.

**Comment by yuwata** [comment]
GitHub mistakenly parse the commit message. As mentioned, the commit 79dec6f5cc0b72d43dfb0469fa68b5cd023fbaf9 does _not_ fix the issue.

@kraj Please test #27253. Thank you!
