### ISSUE TITLE
resource-control doesn't  support for user-slice with cgroupv1?

### ISSUE THREAD

**Issue by FlyWM** [systemd/systemd#27250]
### systemd version the issue has been seen with

252

### Used distribution

manjaro 6.1.22

### Linux kernel version used

6.1.22-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

The cpu useage of processes in the .service is limited by cgroup

### Unexpected behaviour you saw

The cpu useage of process in the .service is not limited

### Steps to reproduce the problem

1. Enable the cgroupv1 and update-grub
2. Edit the user@.service `Delegate=cpu pids memory`
3. `systemctl --user stress --cpu 8`  and output:` Running as unit: run-r4b3ca6cf54cd4569aa427701b14c3df1.service`
4. `systemctl --user stress --cpu 8`  and output:` Running as unit: run-re273898ac0af41f2b11a3f310908c1d4.service`
5. `systemctl --user set-property run-r4b3ca6cf54cd4569aa427701b14c3df1.service CPUShares=10`
6. run `top` 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;%CPU
3445        20   0    3424    116      0 R  51.3   0.0   4:57.50 stress                                                                
3439        20   0    3424    116      0 R  50.7   0.0   5:00.01 stress                                                                
3442        20   0    3424    116      0 R  50.3   0.0   4:52.98 stress                                                                
3443        20   0    3424    116      0 R  50.3   0.0   4:52.12 stress                                                                
3499        20   0    3424    116      0 R  50.3   0.0   4:25.58 stress                                                                
3438        20   0    3424    116      0 R  50.0   0.0   5:03.45 stress                                                                
3444        20   0    3424    116      0 R  50.0   0.0   5:01.53 stress                                                                
3501        20   0    3424    116      0 R  50.0   0.0   4:27.47 stress                                                                
3503        20   0    3424    116      0 R  50.0   0.0   4:28.63 stress                                                                
3504        20   0    3424    116      0 R  50.0   0.0   4:32.37 stress                                                                
3441        20   0    3424    116      0 R  49.7   0.0   4:59.57 stress                                                                
3500        20   0    3424    116      0 R  49.7   0.0   4:29.21 stress                                                                
3502        20   0    3424    116      0 R  49.7   0.0   4:28.51 stress                                                                
3505        20   0    3424    116      0 R  49.7   0.0   4:28.60 stress                                                                
3498        20   0    3424    116      0 R  49.0   0.0   4:30.80 stress                                                                
3440        20   0    3424    116      0 R  46.3   0.0   4:53.88 stress

**Comment by poettering** [comment]
CPUShares= just dictates how much cpu time a unit will get relative to other units that also want cpu time. Hence, if nothing else wants cpu time your service will still get all of it.

You might be looking for CPUQuota= instead, which allows to specify hard limits, and will let CPU time that is available but outside of the quota rather go to waste.

anyway, this is not a support forum, please contact the systemd mailing list or similar for support questions, do not file github issues, thank you
