### ISSUE TITLE
Support defining mount and swap units via credentials

### ISSUE THREAD

**Issue by bmr-cymru** [systemd/systemd#27260]
### Component

other

### Is your feature request related to a problem? Please describe

Linux today supports a variety of block and file system snapshot mechanisms (LVM2, btrfs, split mirrors etc.) and it is possible to boot a simple system with just a single (root) file system into a snapshot of the system state using the existing `root=` and `rootflags=` kernel command line options.

Being able to boot into a snapshot has application for rolling back unsuccessful updates, system recovery and troubleshooting.

It is not currently directly possible to boot into a snapshot state for more complex file system layouts (for e.g. with separate `/var`, `/home` etc.) without first modifying the snapshot content to reference the appropriate block devices or subvolumes in `/etc/fstab`.

### Describe the solution you'd like

The ability to specify mount and swap units directly on the kernel command line. This would allow (in combination with `fstab=no`) the overriding of the file system mount structure for a given boot of the operating system image.

This allows a complete snapshot of the system state to be booted for e.g. in the case of a failed upgrade that renders the system unbootable.

The user can then roll back to the snapshot state minimizing down time and providing a valuable safety net around updates to the operating system.

The syntax would be something like:

```
  systemd.mount=what:where:fstype:options

  systemd.swap=what:options
```
Where a literal ':' in any of the fields is escaped as '::'.

This could be implemented as a new generator or by extending the existing fstab-generator.

### Describe alternatives you've considered

It's possible to implement these options in a separate component that provides a new system generator to recognise and act on the unit syntax. This would require users to install additional packages to take advantage of the feature.

It's also possible to mount the snapshot of the root file system and directly modify /etc/fstab however this complicates rollback (since the changes to the fstab must either be reverted, or preserved in a separate block or file system snapshot).

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by keszybz** [comment]
We already support autodetection of swap and many other mount points automatically: https://uapi-group.org/specifications/specs/discoverable_partitions_specification/. This doesn't cover all the cases you describe, but at least for swap it's reasonable to never define it in `/etc/fstab`. Similarly for `/home`: it would almost always be shared between different snapshots, so it's just fine to autodiscover the partition and mount it automatically.

**Comment by poettering** [comment]
so, this makes a ton of sense to me, and i would like to see this too.

i'd suggest implementing this inside of systemd-fstab-generator, which already interprets root= and usr= as well as /etc/fstab.

I'm not convinced escaping via :: is the way to go. We probably need a way to escape spaces too after all, hence something backslash-based sounds more appropriate, since it can cover all characters.

It would probably be wise doing some reasearch how other components from us and the kernel actually do escaping in similar case, and then follow that.

**Comment by poettering** [comment]
There's a line in TODO that asks for the same thing btw, and can be removed by any PR implementing this:

```
* systemd-fstab-generator: support addition mount specifications via kernel
  cmdline. Usecase: invoke a VM, and mount a host homedir into it via
  virtio-fs.
```

**Comment by bmr-cymru** [comment]
Thanks. I'll take a look at the options for escaping. We have a similar need in libdevmapper where we store file system paths in the kernel aux_data word (which can not contain whitespace).

Something that could be handled by `systemd-escape` may be a good option since it's already easy for administrators to produce the properly escaped strings.

**Comment by yuwata** [comment]
Waiting in #27563.

**Comment by bluca** [comment]
Wouldn't it be better to use credentials for this? This is not kernel configuration, it's purely userspace

**Comment by Winterhuman** [comment]
Given the existence of `root` and `mount.usr`, it's probably better to have both a cmdline and credential method for specifying this, otherwise it may look like to users that `mount.usr` is special-cased to exist, but no other parition types can be configured

**Comment by yuwata** [comment]
@bluca and @poettering How creds can be loaded from generators?

**Comment by bluca** [comment]
We are picking them up from sd-stub and making them available in `/.extra/credentials` so they should be available to generators too in the initrd - not sure in terms of what internal helper to call, but in theory it should work, and it's intended to afaik

**Comment by keszybz** [comment]
I think it's fine to *also* support credentials. But please keep the command line option too. This is much easier to use for people and familiar.

**Comment by bluca** [comment]
Sure, adding that as well is fine. But I think we should emphasize more the credentials approach, especially for programmatic usage.

**Comment by bmr-cymru** [comment]
@yuwata thanks! This looks like it will do exactly what we need.

**Comment by Winterhuman** [comment]
Continuing from https://github.com/systemd/systemd/issues/27260#issuecomment-1538282620, once `systemd.mount` becomes a thing, what will happen with `mount.usr`? Will it be kept, but marked deprecated? Or is it considered better to use the dedicated option when working with `usr` partitions, therefore it won't be marked as deprecated?

**Comment by poettering** [comment]
> Continuing from [#27260 (comment)](https://github.com/systemd/systemd/issues/27260#issuecomment-1538282620), once `systemd.mount` becomes a thing, what will happen with `mount.usr`? Will it be kept, but marked as deprecated? Or is it considered better to use the dedicated option when working with `usr` partitions, therefore it won't be marked as deprecated?

We should keep that, it's interpreted by different code and gets quite different handling. Moreover, there's usrhash and things too, for referencing /usr/ partitions by verity top-level hash, which really suggests we should leave that as is.

**Comment by bluca** [comment]
> Sure, adding that as well is fine. But I think we should emphasize more the credentials approach, especially for programmatic usage.

reopening to track creds support
