### ISSUE TITLE
machinectl: add `import-fs` to import directories (result of `debootstrap`, `dnf --installroot=…`, etc)

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#2728]
### Submission type

[ ] Bug report

[ x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> git master 3349f77
### Description

Currently, when building new base images for machines, I execute these steps:

```
mkdir -p /var/tmp/machines
debootstrap wily /var/tmp/machines/ubuntu-wily http://archive.ubuntu.com/ubuntu
cd /var/tmp/machines/ubuntu-wily
tar cvzf ../ubuntu-wily.tar.gz .
machinectl import-tar ../ubuntu-wily.tar.gz
```

I'd like to see an `import-dir` or `import-fs` command in `machinectl` which just imports a plain filesystem structure, so building a tarball from a bootstrapped filesystem to be then imported through `import-tar` again as plain FS structure into the machine store could be streamlined quite a bit and the process outlined above would end up looking just like this:

```
mkdir -p /var/tmp/machines
debootstrap wily /var/tmp/machines/ubuntu-wily http://archive.ubuntu.com/ubuntu
machinectl import-fs /var/tmp/machines/ubuntu-wily
```

**Comment by poettering** [comment]
Hmm, note that you can just create the dir /var/lib/machines/ubuntu-wily directly and run debootstrap there, there's no need to use "machinectl" for importing for this case, is there?

**Comment by eliasp** [comment]
@poettering This means bypassing `machinectl`/`systemd-machined` which controls the quota of the machine backing store (see also: #1968).

**Comment by ioquatix** [comment]
I too would like this feature :) I was trying to import an image I made following the arch wiki and it wasn't obvious how to do it.
