### ISSUE TITLE
Reporting of service-specific status info

### ISSUE THREAD

**Issue by fallenguru** [systemd/systemd#2729]
### Submission type

[X] Request for enhancement (RFE)

A lot of legacy init scripts could be called with a "status" action or similar, which would return daemon specific status info. E.g. apcupsd would dump current data from/about the current UPS. I've been missing this fuctionality after Debian's switch to systemd, especially as I've tried to move more stuff to systemd servics (filesystem scrubs, SMART tests) that could use some way to query status/progress.

An idea would be to add ExecStatus=, the output of which is appended to systemctl status $service output.

**Comment by poettering** [comment]
This has been requested many times before, but we always said no to this, as systemd cannot make any sense of the output. It has no effect on the state engine for a service, it's not generic behaviour but explicitly specific bheaviour. Thus we always said the same thing: this makes a lot of sense, but it should live in seperate tools, outside of systemd. For example apache has apachectl that exposes these additional verbs, and a similar thing is what the other services should do.

Sorry, but beyond that I don't think we should add something to systemd itself. Closing hence.

**Comment by gdamjan** [comment]
while apachectl exists, if you run it from the shell, it does not run in the same environment as the service runs (environment vars, i.e configuration, and User/Group, WorkingDirectory, namespaces, mounts etc).

Some services would benefit from custom actions like for ex. initdb, reset-sessions, dropdb and similar
