### ISSUE TITLE
PrivateNetwork=yes fails to set up loopback when running under systemd-nspawn

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#27292]
I'm testing `mkosi boot`, and `systemd-hostnamed` emits a warning about `lo`.  It seems any unit with PrivateNetwork=yes will fail similarly, e.g. `systemd-run -p PrivateNetwork=yes -S`:
```
Apr 16 12:20:56 image (ostnamed)[1147]: Failed to add address 127.0.0.1 to loopback interface: Operation not permitted
Apr 16 12:20:56 image (ostnamed)[1147]: Failed to add address ::1 to loopback interface: Operation not permitted
Apr 16 12:20:56 image (ostnamed)[1147]: Failed to bring loopback interface up: Operation not permitted
Apr 16 12:20:56 image (ostnamed)[1147]: Failed to configure loopback network device: Operation not permitted
```

```console
$ systemd-run -p PrivateNetwork=yes -S
Running as unit: run-u20.service
Press ^] three times within 1s to disconnect TTY.
[654475.510359] (ip)[1196]: Failed to configure loopback network device: Operation not permitted
$ ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
$ ping localhost
ping: connect: Cannot assign requested address
```

I'm confused why we can set up the namespace but not the device inside…

The container is invoked like this: `systemd-nspawn --quiet --image /home/zbyszek/src/systemd-stable/mkosi.output/fedora~38/image.raw --boot --machine image --bind=.:/root/src --chdir=/root/src --set-credential=firstboot.timezone:Europe/Warsaw --set-credential=firstboot.locale:C.UTF-8 --set-credential=firstboot.hostname:image loglevel=4 systemd.mask=auditd systemd.journald.max_level_console=warning systemd.journald.forward_to_console systemd.log_level=debug systemd.crash_shell systemd.tty.term.hvc0=xterm-256color systemd.tty.columns.hvc0=126 systemd.tty.rows.hvc0=52 console=hvc0`
`systemd-nspawn --version` → `systemd 253 (253-1316-g3bbdb32)`
`getenforce` → `Disabled`

**Comment by poettering** [comment]
so you invoked the container without netns and without userns. Which means we'll that way remove CAP_NET_ADMIN for your container, and you cannot get it back (unless something opens its own userns where it could...)

hence what you are seeing is expected: you are creating a net namespace you cannot actually interact with because you lack the caps for it...

i figure we should tweak this somehow, i.e. magically suppress PrivateNetwork= if we lack CAP_NET_ADMIN and PrivateUsers= is not used.

**Comment by poettering** [comment]
→ #28142
