### ISSUE TITLE
systemd-cryptsetup: Support keys other than RSA to pkcs11 enrollment

### ISSUE THREAD

**Issue by andsens** [systemd/systemd#27331]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

Yubikey 5 supports ECC P-256 keys for the PIV certificates. I would like to be able to enroll that key with systemd-cryptenroll to unlock my luks volume.

### Describe the solution you'd like

[Checking the source](https://github.com/systemd/systemd/blob/main/src/cryptenroll/cryptenroll-pkcs11.c#L44-L46) I can see that the assumption is that all enrolled keys are RSA. There're quite a few alternatives out there now and HSMs are starting to support them. It'd be great if support for e.g. P256 and ed22519 were added.

### Describe alternatives you've considered

For now I'll either enroll an RSA key in a different slot or switch the PIV cert key to RSA.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by YHNdnzj** [comment]
-> https://github.com/systemd/systemd/pull/23209

**Comment by andsens** [comment]
Ah apologies, should've removed a "C" when searching for "ECC" in the issues :-)  
Closing.

**Comment by YHNdnzj** [comment]
Actually you can keep this open until the PR gets merged :)

**Comment by andsens** [comment]
Hehe, alright then :-)

**Comment by andsens** [comment]
Oh wow, you're right. Though it looks like NIST [is starting to warm](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf) to the idea of ed2**5**519 (sorry for the typo). Fingers crossed this makes its way into the PIV standard within the next ... 10 years? :-P
