### ISSUE TITLE
large-ish (12k) number of static routes causes high cpu usage + timeout

### ISSUE THREAD

**Issue by arthurdarcet** [systemd/systemd#27353]
### systemd version the issue has been seen with

253

### Used distribution

Archlinux

### Linux kernel version used

6.2.11-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

routes are loaded

### Unexpected behaviour you saw

- systemd-networkd sits at 100% CPU usage for about 25 seconds
- no routes are added
- logs a timeout

### Steps to reproduce the problem

configure a static IP address interface, ipv4 only, and a file with ~13k static routes (on my machine, I time out when there is more than 12500 routes to load. But even with a smaller number, systemd-networkd sits at 100% for some time to load everything)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-networkd[798]: eno1: Failed to set static address: Connection timed out
systemd-networkd[798]: eno1: Failed
```

**Comment by yuwata** [comment]
If the routes are managed by other service or daemon, then please try to create something like the following:
```
# /etc/systemd/networkd.conf.d/ignore-routes.conf
[Network]
ManageForeignRoutes=no
```

**Comment by yuwata** [comment]
If it does not work, then please request to reopen this page. Closing (at least tentatively).
