### ISSUE TITLE
Programmatically controlling service watchdog

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [systemd/systemd#27354]
### Component

systemd

### Is your feature request related to a problem? Please describe

I want to programmatically enable, disable or modify the service watchdog inside the daemon code. 
Currently, we enable service watchdog through the service file configuration WATCHDOG_SEC=
We service(pet) the watchdog by programmatically calling sd_notify(0,"WATCHDOG=1") periodically in the daemon code.

In addition to this, I have a busy condition in the daemon which could slightly take more time then the typically watchdog timeout. Hence whenever I reach this condition, I want to either temporarily disable the watchdog or increase the watchdog timeout. Is this feasible?

Can I make use of sd_notify(0, "WATCHDOG_USEC=XYZ") option to modify the timeout?
For example, can I set it to 0.  sd_notify(0, "WATCHDOG_USEC=0")  to temporarily disable the watchdog as well as set to higher value sd_notify(0, "WATCHDOG_USEC=100") to increase the watchdog timeout?

Additionally, can I use this API sd_notify(0, "WATCHDOG_USEC=XYZ") to enable watchdog for a service which doesn't have WATCHDOG_SEC= set in its service configuration?

### Describe the solution you'd like

I prefer to introduce a set of APIs inline with sd_watchdog_enabled() as follows
sd_watchdog_disable()
sd_watchdog_enable()
sd_watchdog_setTimeout()

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by poettering** [comment]
This is not a support forum, but a bug tracker. The submission form should have made that very clear. And yes sd_notify() with WATCHDOG_USEC= was added in v231. It's documented.
