### ISSUE TITLE
NetworkManager.service does not bring my network card out of sleep

### ISSUE THREAD

**Issue by ags1234** [systemd/systemd#27364]
### systemd version the issue has been seen with

systemd-253.2-1.fc39.src.rpm

### Used distribution

Fedora 39 Rawhide KDE

### Linux kernel version used

6.3.0-0.rc7.20230420gitcb0856346a60.59.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When resuming computer from sleep, network card should properly be also resumed and it should function properly.

### Unexpected behaviour you saw

After resuming from sleep, all network activity is lost, network is not accessible.

### Steps to reproduce the problem

KDE Menu -> Sleep. When waking up, network icon from system tray has a red x on it. Network does not work.

### Additional program output to the terminal or log subsystem illustrating the issue

I attached the log from journalctl. One can jump at the point when resuming from sleep starts, by searching for:
apr 23 05:43:56 fedora systemd-logind[895]: Operation 'sleep' finished.
[log.txt](https://github.com/systemd/systemd/files/11302830/log.txt)

**Comment by ags1234** [comment]
Also, lspci lists my network card as:
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2) I219-V

**Comment by YHNdnzj** [comment]
How is this a systemd issue? According to the journal, you're not using systemd-networkd, so it's more likely that `NetworkManager` is the one to blame, or the kernel `e1000e` driver didn't bring your NIC up correctly.

**Comment by ags1234** [comment]
Oh, isn't `NetworkManager` is a `systemd` component?

**Comment by YHNdnzj** [comment]
> Oh, isn't `NetworkManager` a `systemd` component?

Nope. And a quick search can bring you to them: https://gitlab.freedesktop.org/search?search=resume&project_id=411&group_id=1204&scope=issues

**Comment by ags1234** [comment]
Understood. Thanks for your help.
