### ISSUE TITLE
auto-gpt-generator destroys hibernate image of other Linux installation

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#27360]
### systemd version the issue has been seen with

252.6

### Used distribution

Debian bookworm (12)

### Linux kernel version used

6.1.0-7-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Description

Once I got into this situation:
- I have some Linux installed on particular partition (say, sda1) with swap configured via fstab (sda2)
- I have another Linux installed on sda3 without any configured swap
- I hibernated sda1, because I wanted to temporary boot into sda3
- I booted sda3, it discovered swap via auto-gpt-generator and enabled it, destroying hibernation image

This is inappropriate. Please, ignore swaps with hibernation images in auto-gpt-generator, they may be owned by another system!

My usual workflow is so: I have one big disk (1Tb) with GPT partition table. It contains my main OS. Main OS has swap (because I need hibernation). And also the disk has some alternative Linux installation for testing or other purposes. They don't have swap, because I don't want hibernation there. So, this situation naturally occurs on my computer.

You may say "just pass `systemd.gpt_auto=no`". Well, current situation causes data loss! Systemd should data-loss-safe by default

**Comment by YHNdnzj** [comment]
The future plan is to use the detected swap space for resume: https://github.com/systemd/systemd/issues/27247.

**Comment by safinaskar** [comment]
@YHNdnzj , it seems you didn't understand me. The issue you pointed at says (AFAIK) about detection of hibernate image in initramfs time. But I tell about another thing: about swap detection _after_ switch to main root device. (All my systems are Debian, Debian seems not to use systemd/drakut inside its initramfs.) I tell about situation when systemd finds hibernation image of _other OS_ and mistakenly destroys it, causing data loss

**Comment by safinaskar** [comment]
@poettering , normal swap can be distinguished from hibernation image by magic bytes. So, please, do this!
