### ISSUE TITLE
switch-root: Fails to account for double symlink to systemd binary, which skips serialization

### ISSUE THREAD

**Issue by polarina** [systemd/systemd#27379]
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 22.10

### Linux kernel version used

5.19.0-31-generic

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When `systemctl switch-root /sysroot /sbin/init` is invoked, serialization is skipped. When the init path is instead either `/lib/systemd/systemd` or `/usr/lib/systemd/systemd`, serialization is performed.

The issue stems from the double symlink of `/sbin/init` to `/lib/systemd/systemd` which in turn symlinks to `/usr/lib/systemd/systemd` where the actual systemd binary resides.

The utility fails to chase the symlink chain. The function `same_file_in_root` in `src/systemctl/systemctl-switch-root.c` compares the inodes of the given init path with the hard-coded path `/usr/lib/systemd/systemd` (adjustable at compile-time), and if equal, will NULL out the path. But in the above-mentioned scenario, it is comparing the inode of the target symlink with the binary.

P.S. I would like to add that, post-fix, we need a way to unconditionally skip serialization. We switch-root to a much older systemd version in the sysroot and that causes issues with serialization as it barely understands what the initramfs' systemd is saying.

**Comment by poettering** [comment]
Already fixed by 457bbbce7b8d27e7fe0eab2b35662472a21a3e3c
