### ISSUE TITLE
bus-proxyd: please try reading configuration from /usr

### ISSUE THREAD

**Issue by smcv** [systemd/systemd#274]
I've merged the dbus branch requested on https://bugs.freedesktop.org/show_bug.cgi?id=89280 which makes files in /etc optional for dbus.daemon: the canonical source of bus setup is now `/usr/share/dbus-1/BUS.conf` where _BUS_ is either `system` or `session` as appropriate. Please load that file if it is present at runtime, falling back to the traditional `/etc/dbus-1/BUS.conf`. Up to you whether this includes `${prefix}` handling - in practice I expect that dbus is installed in /usr and /etc on any reasonable system. This is not in a release yet, let alone a stable release, but I intend to have it in a new 1.10 stable branch before too long.

Because bus-proxyd doesn't currently understand the `<include*>` directives, it needs to know the whole search path, which is:
- `/usr/share/dbus-1/BUS.conf` (lowest priority, intended for dbus upstream / distro packagers)
- `/etc/dbus-1/BUS.conf` (deprecated, now effectively empty by default, may be deleted)
- `/usr/share/dbus-1/BUS.d` (intended for non-dbus packages eventually)
- `/etc/dbus-1/BUS.d` (intended for the sysadmin but can also be used by packages)
- `/etc/dbus-1/BUS-local.conf` (highest priority, intended for the sysadmin)

For compatibility with older dbus, please continue to install systemd's bus policy snippets in /etc by default - if distributions want an empty /etc they can easily be moved around via `--with-dbuspolicydir`, and I expect there to be a somewhat long transitional period.

No patch here since I don't currently have a kdbus system.

**Comment by smcv** [comment]
@xnox, I imagine this is of interest to you.

**Comment by poettering** [comment]
OK, prepped a patch to add the new search paths as #276.

**Comment by poettering** [comment]
OK, closing as #276 has been merged now.

**Comment by xnox** [comment]
+1 thank you everyone.
