### ISSUE TITLE
`journalctl --vacuum-size=0` does nothing

### ISSUE THREAD

**Issue by abitrolly** [systemd/systemd#27401]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 37

### Linux kernel version used

kernel-6.2.10-200.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

```bash
$ sudo journalctl --vacuum-size=0
Vacuuming done, freed 0B of archived journals from /var/log/journal.
Vacuuming done, freed 0B of archived journals from /run/log/journal.
Vacuuming done, freed 0B of archived journals from /var/log/journal/c3b1f5b205ed4158bd61c304044f4bb7.
$
```

### Unexpected behaviour you saw

```bash
$ sudo journalctl --vacuum-size=0
$
```

### Steps to reproduce the problem

```
sudo journalctl --vacuum-size=0
```

**Comment by abitrolly** [comment]
The same problem with `--vacuum-size=0`.

**Comment by mrc0mmand** [comment]
This is expected and documented.

From [journalctl(1)](https://www.freedesktop.org/software/systemd/man/journalctl.html) man page:

> --vacuum-size=, --vacuum-time= and --vacuum-files= may be combined in a single invocation to enforce any combination of a size, a time and a number of files limit on the archived journal files. Specifying any of these three parameters as zero is equivalent to not enforcing the specific limit, and is thus redundant.

**Comment by abitrolly** [comment]
> This is expected and documented.

Are you sure it is expected? Normally I would rely on UX research or at least a poll to gather the proof.

**Comment by dxdxdt** [comment]
Any competent C programmer would use negative integer values for such meaning. 0 should mean "clean as much as possible", not "don't worry about it". Having to use `1` is not at all a good design.

I don't really care what the document says. This is clearly a design error. I'm raising this issue to the mailing list where the real Systemd devs hang out to see what they think.

**Comment by abitrolly** [comment]
@dxdxdt did you have any success in discussion this in the mailing list?

 -1 or empty value like `--vacuum-suze= --vacuum-time=` if the args parser supports this. That would also allow empty env vars to be used with no workarounds.

**Comment by abitrolly** [comment]
Found the thread - https://lists.freedesktop.org/archives/systemd-devel/2026-February/051917.html

Left the PR to better document the gotcha in the meanwhile.

**Comment by dxdxdt** [comment]
@abitrolly That was me.

It's not about the doc. As I've said: I couldn't care less about what the doc says. This is wrong. The behaviour has to be fixed. Period.

**Comment by abitrolly** [comment]
@dxdxdt I agree, the proper value for "unlimited" size is -1, 0 should be 0.  But because the weird bug is documented and released, it is now feature and a breaking change, no?

**Comment by dxdxdt** [comment]
The greatest dev once said: we do not break userspace. But, in this case, there's nothing to be broken. The existing scripts would just use value greater than 0. Changing the behaviour to accept 0 wouldn't break anything.
