### ISSUE TITLE
Unsupported RuntimeWatchdogSec value results in no watchdog

### ISSUE THREAD

**Issue by K900** [systemd/systemd#27427]
### systemd version the issue has been seen with

253.3

### Used distribution

NixOS unstable

### Linux kernel version used

6.1.25

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

The documentation states:

> Not all hardware watchdogs allow configuration of all possible reboot timeout values, in which case the closest available timeout is picked.

So I set `RuntimeWatchdogSec=30s` on my Raspberry Pi 4, expecting some value to be picked.

Turns out the maximum supported value is 15s, and the watchdog quietly EINVALs and ends up ignored.

### Unexpected behaviour you saw

The watchdog was not actually enabled; the error was logged into the journal but not displayed in `systemctl status` or anywhere else really.

### Steps to reproduce the problem

1. Use a Raspberry Pi 4
2. Set `RuntimeWatchdogSec=30s`
3. Reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Feb 15 19:22:31 yui systemd[1]: Using hardware watchdog 'Broadcom BCM2835 Watchdog timer', version 0, device /dev/watchdog0
Feb 15 19:22:31 yui systemd[1]: Failed to set timeout to 30s: Invalid argument
```

**Comment by K900** [comment]
Thanks, will do!

**Comment by K900** [comment]
Filed a kernel bug at https://bugzilla.kernel.org/show_bug.cgi?id=217374.

**Comment by poettering** [comment]
I doubt kernel people look there. → https://www.kernel.org/doc/html/v6.3/admin-guide/reporting-issues.html

**Comment by asavah** [comment]
If your device is a raspberry pi and judging by BCM2835 it should be you might want to report the issue here https://github.com/raspberrypi/linux and let RPF people handle the issue itseld and upstreaming the fix.

**Comment by lategoodbye** [comment]
I noticed the bugzilla issue and submitted a patch:
https://lore.kernel.org/linux-arm-kernel/20231112173251.4827-1-wahrenst@gmx.net/T/

The RPF people have limited time, so upstreaming patches doesn't have high prio for them.
