### ISSUE TITLE
`Activation failed: Required key not available` everytime I login via systemd-homed

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#27423]
### systemd version the issue has been seen with

253.3

### Used distribution

Archlinux

### Linux kernel version used

6.1.25-1-lts

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

no errors or warnings to be found in `journalctl` right after login via `systemd-homed`

### Unexpected behaviour you saw

Everytime i've logined, i can see `Activation failed: Required key not available`
```yaml
Apr 26 23:12:51 archlinux systemd-homed[696]: testuser: changing state inactive → activating-for-acquire
Apr 26 23:12:51 archlinux systemd-homework[707]: User record has no recovery keys, plaintext passwords not tested against it.
Apr 26 23:12:51 archlinux systemd-homework[707]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Apr 26 23:12:51 archlinux systemd-homed[696]: Worker reported error code ENOKEY.
Apr 26 23:12:51 archlinux systemd-homed[696]: Activation failed: Required key not available
Apr 26 23:12:51 archlinux systemd-homed[696]: Sent message type=error sender=n/a destination=:1.5 path=n/a interface=n/a member=n/a cookie=7 reply_cookie=3 signature=s error-name=org.freedesktop.home1.BadPassword error-message=Password for home testuser is incorrect or not sufficient for authentication.
Apr 26 23:12:51 archlinux systemd-homed[696]: testuser: changing state activating-for-acquire → inactive
Apr 26 23:12:51 archlinux systemd-homed[696]: Got notification that all sessions of user testuser ended, deactivating automatically.
```

### Steps to reproduce the problem

Follow the steps in https://wiki.archlinux.org/title/Systemd-homed
btw, `testuser` is newly created.

```bash
$ cat system-auth
#%PAM-1.0

auth       required                    pam_faillock.so      preauth
# Optionally use requisite above if you do not want to prompt for the password
# on locked accounts.
-auth      [success=2 default=ignore]  pam_systemd_home.so
auth       [success=1 default=bad]     pam_unix.so          try_first_pass nullok
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
auth       required                    pam_env.so
auth       required                    pam_faillock.so      authsucc
# If you drop the above call to pam_faillock.so the lock will be done also
# on non-consecutive authentication failures.

-account   [success=1 default=ignore]  pam_systemd_home.so
account    required                    pam_unix.so
account    optional                    pam_permit.so
account    required                    pam_time.so

-password  [success=1 default=ignore]  pam_systemd_home.so
password   required                    pam_unix.so          try_first_pass nullok shadow sha512
password   optional                    pam_permit.so

-session   optional                    pam_systemd_home.so
session    required                    pam_limits.so
session    required                    pam_unix.so
session    optional                    pam_permit.so
```

```yaml
$ userdbctl user testuser
   User name: testuser
       State: active
 Disposition: regular
 Last Change: Wed 2023-04-26 23:37:52 UTC
    Login OK: yes
 Password OK: yes
         UID: 60143
         GID: 60143 (testuser)
 Aux. Groups: wheel
   Directory: /home/testuser
     Storage: subvolume (no encryption)
  Image Path: /home/testuser.homedir
   Removable: no
       Shell: /bin/bash
 Mount Flags: nosuid nodev exec
   Disk Size: 1.9T
   Disk Free: 1.9T (= 99.5%)
  Disk Floor: 5.0M
Disk Ceiling: 5.0T
  Good Auth.: 26
   Last Good: Thu 2023-04-27 00:25:09 UTC
   Bad Auth.: 26
    Last Bad: Thu 2023-04-27 00:25:09 UTC
    Next Try: anytime
 Auth. Limit: 30 attempts per 1min
SSH Pub. Key: 1
   Passwords: 1
  Local Sig.: yes
     Service: io.systemd.Home
```

```bash
$ ls -la .identity
-rw------- 1 nobody nobody 1.1K Apr 26 23:37 .identity
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/enihcam/e35e1baaa5e954102f132dd3560bef28
```

**Comment by enihcam** [comment]
might be related: https://github.com/systemd/systemd/issues/26722

**Comment by poettering** [comment]
this is not a bug. When authenticating a user pam_systemd_home will always try to authenticate without any password first, because a fido2 or pkcs11 key might be present which can authenticate the user instead of the password, and only homed knows about that. If no fido2/pkcs11 device was configured or present, then homed will tell the client "no, sorry, i need a password", and then the client will prompt the user for it.

hence there will always be two requests be made if you auth via password: one that tests if password might not be necessary, and then another one after the password has been prompted.

you turned on debug logging so you get all this in all detail.

**Comment by enihcam** [comment]
> this is not a bug. When authenticating a user pam_systemd_home will always try to authenticate without any password first, because a fido2 or pkcs11 key might be present which can authenticate the user instead of the password, and only homed knows about that. If no fido2/pkcs11 device was configured or present, then homed will tell the client "no, sorry, i need a password", and then the client will prompt the user for it.
> 
> hence there will always be two requests be made if you auth via password: one that tests if password might not be necessary, and then another one after the password has been prompted.
> 
> you turned on debug logging so you get all this in all detail.

i totally understood, and i just felt annoyed with the error message. I made the following change but it did not suppress the error message.

```bash
/etc/systemd/system $ cat systemd-homed.service.d/override.conf
[Unit]
StandardError=null
```

any suggestions? @poettering
