### ISSUE TITLE
cryptsetup: Capping TPM PCR banks to prevent subsequent LUKS password unsealing

### ISSUE THREAD

**Issue by mkopec** [systemd/systemd#27430]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

If a LUKS volume is used with systemd-cryptsetup and a password is sealed to one or more PCR banks, there is currently no mechanism that would prevent a user with root access from unsealing the password again. An attacker might use this to extract the password stored in the TPM and use it at some point later to decrypt the disk.

### Describe the solution you'd like

One solution could be to "cap" the used PCR banks by extending them with a measurement, e.g. just a `0x1`, so that the password cannot be unsealed again after the initial unlocking. Ideally this would be done as soon as the secret is unsealed, to minimize the time in which it can be extracted. This would probably also have to be an option, in case someone has bound other secrets to the same PCRs.

### Describe alternatives you've considered

I don't know if there is an alternative, more fitting mechanism in TPM 2.0 to prevent subsequent unsealing of secrets.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by poettering** [comment]
We already measure a boot phase into PCR 11 if UKIs are used (and thus we'll measure the kernel). This is done to ensure you can bind your secrets to specific parts of the boot, such as "only in initrd" and so on.

See https://www.freedesktop.org/software/systemd/man/systemd-pcrphase.service.html for details.

**Comment by mkopec** [comment]
Thanks, I wasn't aware of that. This solves my problem just as well.
