### ISSUE TITLE
test-network: FAIL: test_qdisc_htb_fifo

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#27473]
See https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-centos8/1932/artifact/systemd-centos-ci/artifacts_k40ra81y/testsuite-logs-upstream.ktu/systemd-networkd-tests.py_FAIL.log

```
======================================================================
FAIL: test_qdisc_htb_fifo (__main__.NetworkdTCTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 3639, in test_qdisc_htb_fifo
    self.assertRegex(output, 'class htb 2:37 root leaf 37:')
AssertionError: Regex didn't match: 'class htb 2:37 root leaf 37:' not found in 'class htb 2:3b root leaf 3bprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0 \nclass htb 2:3a root leaf 3aprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0 \nclass htb 2:37 root leaf 37prio 1 quantum 4000 rate 1Mbit overhead 100 ceil 500Kbit linklayer ethernet burst 123456b/1mpu 0b cburst 123457b/1mpu 0b level 0 \nclass htb 2:3c root leaf 3cprio 1 quantum 6250 rate 1Mbit ceil 500Kbit linklayer ethernet burst 1600b/1mpu 0b cburst 1600b/1mpu 0b level 0'

----------------------------------------------------------------------
Ran 158 tests in 1416.742s
```

**Comment by yuwata** [comment]
Ah, this is a bug in iproute2.
Caused by https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=010a8388aea11e767ba3a2506728b9ad9760df0e, and fixed by https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=4e0e56e0ef05387f7f5d8ab41fe6ec6a1897b26d.

**Comment by yuwata** [comment]
And, recently, CentOS8 and CentOS9 updated iproute package to v6.2.0.

**Comment by yuwata** [comment]
@mrc0mmand Until the issue is fixed, could you pin the iproute packages to the previous version?

**Comment by yuwata** [comment]
Filed as https://bugzilla.redhat.com/show_bug.cgi?id=2192318

**Comment by bluca** [comment]
Can the test get a workaround instead? This is going to start failing everywhere

**Comment by yuwata** [comment]
@bluca 
> Can the test get a workaround instead? This is going to start failing everywhere

-> #27482.
