### ISSUE TITLE
machinectl shell sets echoprt termios flag, which is undesired

### ISSUE THREAD

**Issue by gentoo-root** [systemd/systemd#27480]
### systemd version the issue has been seen with

253.3

### Used distribution

Arch Linux

### Linux kernel version used

6.2.13-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

machinectl

### Expected behaviour you didn't see

Ideally, terminal settings shouldn't change after `machinectl shell`, because it's now what a user would expect (for example, `sudo -i` doesn't change any flags on my machine). At least echoprt shouldn't be enabled, because it turns on counter-intuitive behavior.

### Unexpected behaviour you saw

Running `machinectl shell` (e.g., to gain root access to the local host) changes termios flags, specifically, enables echoprt (I guess, it happens [here](https://github.com/systemd/systemd/blob/5c519a56f5caf73c5d418563af939974b0af43be/src/basic/terminal-util.c#L274), although I didn't try to track it up to `machinectl shell`), which is undesirable for me, because it produces weird artifacts when using backspace.

For example, if you answered "y", then changed your mind, pressed backspace and "n", it will look like this on the screen, and it's really confusing:

```
:: Do you want to remove these packages? [Y/n] y\y/n
```

### Steps to reproduce the problem

1. Check `stty` output. For example, in gnome-terminal I see:
```
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
```
2. `machinectl shell` to become root.
3. Check `stty` output again, after systemd changed the termios flags:
```
speed 38400 baud; line = 0;
-brkint iutf8
echoprt
```
4. Note that echoprt and imaxbel got enabled.

**Comment by poettering** [comment]
This was fixed in d5b6c6e3781b0c48f819bdfe2548d44a6583ec41

> 4\. Note that echoprt and imaxbel got enabled.

So "machinectl shell" actually gets you an entirely new tty, it does not pass the tty through. It's quite different from sudo and similar things. we do not copy the termios settings from one to ther other hence.
