### ISSUE TITLE
BPFProgram ignores errors

### ISSUE THREAD

**Issue by c-ryan747** [systemd/systemd#27497]
### systemd version the issue has been seen with

252

### Used distribution

Centos 8

### Linux kernel version used

5.12

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The `BPFProgram` property doesn't seem to handle failures, instead allowing the unit to startup without the program attached. 

Bpf programs can fail to attach for a variety of reasons (e.g. program does not exist, no permissions to attach, etc)

In this example, the path provided to BPFProgram does not exist, but the unit starts successfully:
```
$ sudo systemd-run --unit="bpf-test" --property=BPFProgram=connect6:/non_existant_path sleep 9999
Running as unit: bpf-test.service
```
I'd expect the unit to fail to start.

This can be a little dangerous as bpf programs are commonly used for sandboxing.

### Unexpected behaviour you saw

Failure being written to `/var/log/messages` and ignored
```
May  2 07:55:54 <HOST> systemd[1]: bpf-test.service: bpf-foreign: Failed to determine filesystem type of /non_existant_path: No such file or directory
May  2 07:55:54 <HOST> systemd[1]: bpf-test.service: bpf-foreign: Failed to prepare foreign BPF hashmap: No such file or directory
```

### Steps to reproduce the problem

```
$ sudo systemd-run --unit="bpf-test" --property=BPFProgram=connect6:/non_existant_path sleep 9999
```

**Comment by poettering** [comment]
I tried to clean things up a bit here → #28159.

It doesn't the underlying logic though: BPFPrograms= are considered auxiliary: if they don't work we will continue with activation.

**Comment by poettering** [comment]
This adds explicit documentation about the situation.

If you need a way to make a unit fail if a bpf program is not loaded, then maybe add AssertPathExists= to the bpf program.

**Comment by poettering** [comment]
> This can be a little dangerous as bpf programs are commonly used for sandboxing.

Well, we don't know this. It's probably more often used for tracing/profiling stuff. We just can't know.

But even if it is sandboxing, we generally implement sandboxing gracefully if we cannot strictly expect that the underlying kernel supports the functionality or not. For example, most our sandboxing options gracefully get disabled if you run systemd inside a container that simply makes them inaccessible to us. BPF programs for example are one such thing, hence I think the current behavour is actually the behaviour we want, we should make this nicely visible though, hence I polished the log messages a bit around this.
