### ISSUE TITLE
Systemd dumped core - Tumbleweed 20230403

### ISSUE THREAD

**Issue by Frank-Schruefer** [systemd/systemd#27503]
Hy,

the following coredump happened when I closed a little popup/overlay system update message window showing how many packets are out of date:

`2023-05-03T09:59:01.673824+02:00 merlin systemd-coredump[22042]: Process 27027 (plasmashell) of user 1000 dumped core.#012#012Stack trace of thread 27696:#012#0  0x00007f4816e2fe73 _ZN7logging10LogMessageD2Ev (libQt5WebEngineCore.so.5 + 0x2a2fe73)#012#1  0x00007f4816e30e51 _ZN7logging15ErrnoLogMessageD0Ev (libQt5WebEngineCore.so.5 + 0x2a30e51)#012#2  0x00007f4816e440c9 _ZN4base8internal19ScopedFDCloseTraits4FreeEi (libQt5WebEngineCore.so.5 + 0x2a440c9)#012#3  0x00007f481674aa31 _ZN4mojo4core12_GLOBAL__N_112ChannelPosix18ShutDownOnIOThreadEv (libQt5WebEngineCore.so.5 + 0x234aa31)#012#4  0x00007f4816e8deee _ZN4base13TaskAnnotator7RunTaskEPKcPNS_11PendingTaskE (libQt5WebEngineCore.so.5 + 0x2a8deee)#012#5  0x00007f4816ea2ee4 _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl10DoWorkImplEPNS0_7LazyNowE (libQt5WebEngineCore.so.5 + 0x2aa2ee4)#012#6  0x00007f4816ea33ec _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl6DoWorkEv (libQt5WebEngineCore.so.5 + 0x2aa33ec)#012#7  0x00007f4816eec5f0 _ZN4base19MessagePumpLibevent3RunEPNS_11MessagePump8DelegateE (libQt5WebEngineCore.so.5 + 0x2aec5f0)#012#8  0x00007f4816ea06d8 _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl3RunEbNS_9TimeDeltaE (libQt5WebEngineCore.so.5 + 0x2aa06d8)#012#9  0x00007f4816e77c44 _ZN4base7RunLoop3RunEv.part.0 (libQt5WebEngineCore.so.5 + 0x2a77c44)#012#10 0x00007f48193d6b29 _ZN7content23BrowserProcessSubThread11IOThreadRunEPN4base7RunLoopE (libQt5WebEngineCore.so.5 + 0x4fd6b29)#012#11 0x00007f4816ebf4c8 _ZN4base6Thread10ThreadMainEv (libQt5WebEngineCore.so.5 + 0x2abf4c8)#012#12 0x00007f4816edd0db _ZN4base12_GLOBAL__N_110ThreadFuncEPv (libQt5WebEngineCore.so.5 + 0x2add0db)#012#13 0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#14 0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 27027:#012#0  0x00007f488ab0c08f __poll (libc.so.6 + 0x10708f)#012#1  0x00007f488d540108 poll (libKF5Crash.so.5 + 0x7108)#012#2  0x00007f488d540cdd _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5 + 0x7cdd)#012#3  0x00007f488aa43420 __restore_rt (libc.so.6 + 0x3e420)#012#4  0x00007f488ca9364d _ZNK14QScopedPointerI11QObjectData21QScopedPointerDeleterIS0_EEptEv (libQt5Qml.so.5 + 0x29364d)#012#5  0x00007f488cf78a99 _ZN16QQuickTransition7prepareER5QListI17QQuickStateActionERS0_I12QQmlPropertyEP23QQuickTransitionManagerP7QObject (libQt5Quick.so.5 + 0x178a99)#012#6  0x00007f488cf6e2d7 _ZN23QQuickTransitionManager10transitionERK5QListI17QQuickStateActionEP16QQuickTransitionP7QObject (libQt5Quick.so.5 + 0x16e2d7)#012#7  0x00007f488b318d2b _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x318d2b)#012#8  0x00007f488c1a52ce _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x1a52ce)#012#9  0x00007f488b2ecb28 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2ecb28)#012#10 0x00007f488b3454a9 _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5 + 0x3454a9)#012#11 0x00007f488b345d8c timerSourceDispatch (libQt5Core.so.5 + 0x345d8c)#012#12 0x00007f4889e79f96 g_main_dispatch (libglib-2.0.so.0 + 0x5df96)#012#13 0x00007f4889e7a358 g_main_context_iterate (libglib-2.0.so.0 + 0x5e358)#012#14 0x00007f4889e7a3ec g_main_context_iteration (libglib-2.0.so.0 + 0x5e3ec)#012#15 0x00007f488b3460b6 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x3460b6)#012#16 0x00007f488b2eb5cb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2eb5cb)#012#17 0x00007f488b2f3a50 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2f3a50)#012#18 0x000056215859e47d n/a (plasmashell + 0x2947d)#012#19 0x00007f488aa2cbb0 __libc_start_call_main (libc.so.6 + 0x27bb0)#012#20 0x00007f488aa2cc79 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x27c79)#012#21 0x000056215859e845 n/a (plasmashell + 0x29845)#012#012Stack trace of thread 28635:#012#0  0x00007f488aa8f4ce __futex_abstimed_wait_common (libc.so.6 + 0x8a4ce)#012#1  0x00007f488aa92210 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8d210)#012#2  0x00007f487e0c7f2b cnd_wait (crocus_dri.so + 0xc7f2b)#012#3  0x00007f487e10f167 impl_thrd_routine (crocus_dri.so + 0x10f167)#012#4  0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#5  0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 20836:#012#0  0x00007f488ab0c08f __poll (libc.so.6 + 0x10708f)#012#1  0x00007f484c050e01 n/a (libpulse.so.0 + 0x33e01)#012#2  0x00007f484c03a854 pa_mainloop_poll (libpulse.so.0 + 0x1d854)#012#3  0x00007f484c0450a6 pa_mainloop_iterate (libpulse.so.0 + 0x280a6)#012#4  0x00007f484c045150 pa_mainloop_run (libpulse.so.0 + 0x28150)#012#5  0x00007f484c054db9 n/a (libpulse.so.0 + 0x37db9)#012#6  0x00007f482ffd62cf n/a (libpulsecommon-16.1.so + 0x5d2cf)#012#7  0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#8  0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 28637:#012#0  0x00007f488aa8f4ce __futex_abstimed_wait_common (libc.so.6 + 0x8a4ce)#012#1  0x00007f488aa92210 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8d210)#012#2  0x00007f487e0c7f2b cnd_wait (crocus_dri.so + 0xc7f2b)#012#3  0x00007f487e10f167 impl_thrd_routine (crocus_dri.so + 0x10f167)#012#4  0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#5  0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 27034:#012#0  0x00007f488ab0c08f __poll (libc.so.6 + 0x10708f)#012#1  0x00007f4889e7a2ce g_main_context_poll (libglib-2.0.so.0 + 0x5e2ce)#012#2  0x00007f4889e7a3ec g_main_context_iteration (libglib-2.0.so.0 + 0x5e3ec)#012#3  0x00007f488b3460ce _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x3460ce)#012#4  0x00007f488b2eb5cb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2eb5cb)#012#5  0x00007f488b10297e _ZN7QThread4execEv (libQt5Core.so.5 + 0x10297e)#012#6  0x00007f488bf86257 _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5 + 0x1a257)#012#7  0x00007f488b103b4d _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0x103b4d)#012#8  0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#9  0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 22039:#012#0  0x00007f488aa8f4ce __futex_abstimed_wait_common (libc.so.6 + 0x8a4ce)#012#1  0x00007f488aa92535 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x8d535)#012#2  0x00007f4816eda350 _ZN4base17ConditionVariable9TimedWaitERKNS_9TimeDeltaE (libQt5WebEngineCore.so.5 + 0x2ada350)#012#3  0x00007f4816edad07 _ZN4base13WaitableEvent9TimedWaitERKNS_9TimeDeltaE (libQt5WebEngineCore.so.5 + 0x2adad07)#012#4  0x00007f4816eafd94 _ZN4base8internal12WorkerThread8Delegate11WaitForWorkEPNS_13WaitableEventE (libQt5WebEngineCore.so.5 + 0x2aafd94)#012#5  0x00007f4816eb3f4f _ZN4base8internal12WorkerThread9RunWorkerEv (libQt5WebEngineCore.so.5 + 0x2ab3f4f)#012#6  0x00007f4816eb443d _ZN4base8internal12WorkerThread15RunPooledWorkerEv (libQt5WebEngineCore.so.5 + 0x2ab443d)#012#7  0x00007f4816edd0db _ZN4base12_GLOBAL__N_110ThreadFuncEPv (libQt5WebEngineCore.so.5 + 0x2add0db)#012#8  0x00007f488aa92f24 start_thread (libc.so.6 + 0x8df24)#012#9  0x00007f488ab19f50 __clone3 (libc.so.6 + 0x114f50)#012#012Stack trace of thread 22040:#012#0  0x00007f488aa8f4ce __futex_abstimed_wait_common (libc.so.6 + 0x8a4ce)#012#1  0x00007f488aa92535 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x8d535)#012#2  0x00007f4816eda350 _ZN4base17ConditionVariable9TimedWaitERKNS_9TimeDeltaE (libQt5WebEngineCore.so.5 + 0x2ada350)#012#3  0x00007f4816edad07 _ZN4base13WaitableEvent9TimedWaitERKNS_9TimeDeltaE (libQt5WebEngineCore.so.5 + 0x2adad07)#012#4  0x00007f4816eafd94 _ZN4base8internal12WorkerThread8Delegate11WaitForWorkEPNS_13WaitableEventE (libQt5WebEngineCore.so.5 + 0x2aafd94)#012#5  0x00007f4816eb3d0b _ZN4base8internal12WorkerThread9RunWorkerEv (libQt5WebEngineCore.so.5 + 0x2ab3d0b)#012#6  0x00007f4816eb443d _ZN4base8internal12WorkerThread15RunPooledWorkerEv (libQt5WebEngineCore.so.5 + 0x2ab443d)#012#7  0x00007f4816edd0db _ZN4base12_GLOBAL__N_110ThreadFuncEPv`

Regards,
   Frank

**Comment by YHNdnzj** [comment]
How does this have anything to do with systemd? It shows clearly that `plasmashell` is the one that crashed.

**Comment by YHNdnzj** [comment]
https://invent.kde.org/plasma/plasma-desktop/-/issues

**Comment by YHNdnzj** [comment]
> Well, I have no idea. The dump starts with saying 'systemd-coredump' so I thought I should report it here.

That's the systemd component used to collect coredumps from other processes. You can refer to https://github.com/systemd/systemd/blob/main/docs/COREDUMP.md for more information.
