### ISSUE TITLE
Faulty entry in "60-keyboard.hwdb" due to "#" char

### ISSUE THREAD

**Issue by flagel** [systemd/systemd#27516]
### systemd version the issue has been seen with

253.1-3

### Used distribution

Arch

### Linux kernel version used

6.2.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Unexpected behaviour you saw

In "systemd/hwdb.d/60-keyboard.hwdb" the below 2 lines can be found:

```
	# HP Laptop 15s-eq0023nl
	evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pnHPLaptop15s-eq0*:sku9MG38EA#ABZ:*
```
 
I lack the hardware, but I suspect the above does not work as intended. Having used the aforementioned lines as inspiration, I ran into issues with matching the "#" char:
```
	evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pn*:skuFoo#Bar:* # Does not work
	evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pn*:skuFoo[#]Bar:* # Does not work
	evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pn*:skuFoo\#Bar:* # Does not work
	evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pn*:skuFoo?Bar:* # Does work
```
	 
There seems to be no way to match the "#"-char without resorting to wildcards.

**Comment by yuwata** [comment]
Thank you for the report.
Fix is waiting in #27551.
