### ISSUE TITLE
freedesktop wiki: outdated and broken links to gummiboot on pages referenced from man

### ISSUE THREAD

**Issue by ChALkeR** [systemd/systemd#2751]
### Submission type

[x] Bug report
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> All links from the documentation should be valid, including nested links.
### In case of bug report: Unexpected behaviour you saw

> Broken links in the documentation.
### In case of bug report: Steps to reproduce the problem

> 1. `man 1 bootctl`
> 2. Follow these links:
>    
>    > NOTES
>    > 1. Boot loader specification
>    >         http://www.freedesktop.org/wiki/Specifications/BootLoaderSpec
>    > 2. Systemd boot loader interface
>    >         http://www.freedesktop.org/wiki/Software/systemd/BootLoaderInterface
> 3. Scroll to the bottom of those pages.
> 4. Click on
>    
>    > http://www.freedesktop.org/wiki/Software/gummiboot/
>    
>    and
>    
>    > This interface is currently implemented by [http://freedesktop.org/wiki/Software/gummiboot](Gummiboot).
> 5. You will see 404 pages. That shouldn't happen when browsing the documentation.

**Comment by keszybz** [comment]
I updated the links on the wiki to refer to bootctl(1) and sd-boot.

**Comment by keszybz** [comment]
I think we should have a man page for sd-boot, but that's another story.
