### ISSUE TITLE
systemd-id128 my-id and -m for batch script

### ISSUE THREAD

**Issue by psztoch** [systemd/systemd#27514]
### Component

other

### Is your feature request related to a problem? Please describe

uuid manipulation for bash script is very difficult.
systemd-id128 tool is very useful, but this tool is not adapted for script use.

### Describe the solution you'd like

Please add -m or other for machine friendly format:
```
# systemd-id128 show root -m
4f68bce3e8cd4db196e7fbcaf984b709
# systemd-id128 show root -m -u
4f68bce3-e8cd-4db1-96e7-fbcaf984b709
```

Add action for user id with -a:
```
# systemd-id128 my-id 615b1bc973b34a699901f73923ca3f1c -a 3c7c3d9924e14e75bfeb563bdd59748f
72ebe67fae4748a8b21753c3d95b789b
# systemd-id128 my-id 615b1bc973b34a699901f73923ca3f1c -a 3c7c3d9924e14e75bfeb563bdd59748f -u
72ebe67f-ae47-48a8-b217-53c3d95b789b
```
Without -a it can be used as validator and uuid formatter - it will be useful in bash script too:
```
# systemd-id128 my-id 615b1bc973b34a699901f73923ca3f1c
615b1bc973b34a699901f73923ca3f1c
# systemd-id128 my-id 615b1bc973b34a699901f73923ca3f1c -u
615b1bc9-73b3-4a69-9901-f73923ca3f1c
# systemd-id128 my-id 615b1bc973b34a699901f73923ca3f1
Failed to parse "615b1bc973b34a699901f73923ca3f1": Invalid argument
```

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
Hmm, what is "my-id" supposed to do precisely? 

And what is "-a" supposed to do? 

Not grokking what you mean?

"-m" is supposed to mean "only output the uuid, no other columns and no header please"?

**Comment by psztoch** [comment]
> Hmm, what is "my-id" supposed to do precisely?
to process id128 from command line. In my example it is 615b1bc973b34a699901f73923ca3f1c.
Currently systemd-id128 can use machine-id or one from builtin dictionary (systemd-id128 show) only.
But I want to use it with my own id (for example for foreign machine-id), and I can't.

> And what is "-a" supposed to do?
man systemd-id128 -> With this option, an identifier that is the result of hashing the application identifier app-id and ... my-id from command line.

> 
> Not grokking what you mean?
> 
> "-m" is supposed to mean "only output the uuid, no other columns and no header please"?

Yes. But after consideration: `systemd-id128 show usr` should only print 8484680c952148c69c11b0720656f69e.
Table and two columns of output should be printed for `systemd-id128 show` (without [NAME]) only.
Then -m will be obsolete.

**Comment by abielan** [comment]
I also find it very useful in my scripts. Please, implement it.
