### ISSUE TITLE
networkd loads cfg80211.ko causing big fat kernel error message on radio-less systems

### ISSUE THREAD

**Issue by mjt0k** [systemd/systemd#27520]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12 Bookworm

### Linux kernel version used

6.1.20-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Unexpected behaviour you saw

On a completely radio-less machine (eg, in a qemu-kvm VM), with no WIFI interfaces whatsoever, when systemd-networkd is starting, the following error message is displayed by the kernel:
```
platform regulatory.0: firmware: failed to load regulatory.db (-2)
platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
cfg80211: failed to load regulatory.db
```
(in all red color).

This is not an error per se, the system operates as usual. But the error message is scary still, and causes quite some confusion to the user.

src/network/networkd-manager.c: `manager_enumerate()`, it calls  `manager_enumerate_nl80211_wiphy()` and `manager_enumerate_nl80211_config()`, which causes cfg80211.ko to load, which, in turn, tries to loads the regdb.

Blacklisting cfg80211 module eliminates this error message, but it makes it impossible to use stuff when actual wifi hardware is available.

I'm not sure where this can be fixed best: in kernel or in systemd-networkd, though.

**Comment by yuwata** [comment]
This should be fixed in the kernel side, as other tools can trigger to load the module.
