### ISSUE TITLE
Return non-0 from`systemd-analyze verify` when warnings are printed

### ISSUE THREAD

**Issue by punkeel** [systemd/systemd#27540]
### Component

systemd-analyze

### Is your feature request related to a problem? Please describe

I'm always frustrated when I write systemd units with typos/mistakes that prevent them from behaving properly, in subtle ways.

- This doesn't show in the `journalctl`/`syslogs` logs, as nothing is printed by my service.
- I do not run `systemctl status myservice` often enough to notice the (yellow) warnings.

### Describe the solution you'd like

I would like `verify` to provide a way to fail on warnings.
I would like `verify` to let me decide which checks are errors/warnings (similar to a linter).

eg:
`systemd-analyze verify --strict test1.service`
`systemd-analyze verify -Wall test1.service`

### Describe alternatives you've considered

```
root@deus-ex:~# systemd-analyze verify test1.service
/etc/systemd/system/test1.service:52: Unknown key name 'After' in section 'Install', ignoring.
/etc/systemd/system/test1.service:53: Unknown key name 'BindsTo' in section 'Install', ignoring.
...
root@deus-ex:~# echo $?
0
```

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-analyze.html#--recursive-errors=MODE

**Comment by punkeel** [comment]
TIL, thanks!
