### ISSUE TITLE
systemd failed to feed HW watchdog in time

### ISSUE THREAD

**Issue by freebendy** [systemd/systemd#27545]
### systemd version the issue has been seen with

250

### Used distribution

Yocto

### Linux kernel version used

5.10.120

### CPU architectures issue was seen on

arm

### Component

systemd

### Unexpected behaviour you saw

I have HW watchdog with 1 second timeout and it can't be disabled. The kernel is configured to feed the watchdog before the user space open it.

Systemd opens the /dev/watchdog1 in main() before loading units and determined initial transaction, and then feeds the HW watchdog in the main loop afterward. The loading units and determined initial transaction takes about 2.5 seconds on my board and thus cause HW watchdog reset. 

Systemd should ensure the HW watchdog is fed at least half of it timeout. This is not guaranteed in its startup phase. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[    4.286796] systemd[1]: Initializing machine ID from random generator.
[    4.298668] systemd[1]: Installed transient /etc/machine-id file.
[    4.429116] systemd[1]: Using hardware watchdog 'GPIO Watchdog', version 0, device /dev/watchdog1
[    4.439473] systemd[1]: Watchdog running with a timeout of 1s.
[    4.445592] systemd[1]: @@ watchdog_ping_now: 4423362
[    7.050061] systemd[1]: @@ invoke_main_loop: 7027765
[    7.057561] systemd[1]: @@ manager_loop: 7034249
[    7.062539] systemd[1]: @@ watchdog_ping_now: 7040302
```

**Comment by bluca** [comment]
> Systemd should ensure the HW watchdog is fed at least half of it timeout. This is not guaranteed in its startup phase.

The entire purpose of the watchdog in pid1 is to ensure it doesn't get stuck processing while reading external input, so that would completely defeat its purpose. You need to fix the configuration to set an appropriate timer for normal operations of your system.

**Comment by freebendy** [comment]
@bluca Thanks for your comment. Just want to clarify if my understanding is correct: systemd watchdog feature is not expected to be used in a board with a watchdog timeout value less than systemd's initialization time, right?

**Comment by bluca** [comment]
The watchdog feature is not expected to be used with a timeout configuration that is not sufficient to cover all normal and expected system behaviors, including boot time. The configuration needs to be changed to account for expected boot time.

**Comment by freebendy** [comment]
@bluca Thanks, I understand it. There are some watchdog circuits does not have configurable timeout. E.g. the one in the HW I am using has a fixed 1 second timeout. I tried to understand if I should go for a different solution if it is not the case for systemd watchdog.

**Comment by bluca** [comment]
You can enable it after boot if boot is your problem - however, you are likely going to have the same issues with other slow operations, ie reload or reexec. A watchdog that cannot be configured to attune for the use case is not very useful I'm afraid.
