### ISSUE TITLE
Partial decryption of fscrypt encrypted home

### ISSUE THREAD

**Issue by JP-Ellis** [systemd/systemd#27556]
### systemd version the issue has been seen with

253.4-1

### Used distribution

Arch Linux

### Linux kernel version used

{to be filled}

### CPU architectures issue was seen on

x86_64

### Component

homectl, systemd-homed

### Expected behaviour you didn't see

Activating an account should decrypt the entire home directory

### Unexpected behaviour you saw

Activating an account decrypts the base directory only, and all subdirectories remain encrypted (with encrypted names).

### Steps to reproduce the problem

I have a `dd`-backup of my drive which I made as a backup when migrating my data.

I tried unlocking my backed up home directory as follows:

- Copied over the `local.public` and `local.private` files to the new computer
- Copied over the identity JSON to the new computer (in `/var/lib/systemd/home`)
- Mounted the old drive to `/mnt/bkp`, and modified the copied identity file to point the image path to `/mnt/bkp/home/me.homedir`
- After restarting `systemd-homed`, I was able to successfully activate my home directory, but as described above, if I go into any subdirectory, the files are still encrypted.

I do not know what caused the partial decryption of the files, and more importantly, I do not know how to recover this.

I have also tried booting from the `dd` backup, and the same issue appears.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
{to be filled}
```

**Comment by poettering** [comment]
(recently fscrypt gained a new mode, where the availability of the key in the process tha accesses the fs is not rquired anymore, but so far we haven't updated homed to use it.)

**Comment by JP-Ellis** [comment]
Indeed, I was used `sudo` to try and open up the home directory on the backup drive without actually logging in as the user. I did figure out eventually that if I logged in with the user directly, then it worked out fine (sorry forgot to update this thread).

It would be nice I think to be able to open up an fscrypt-encrypted home directory if I have the key, without needing to log in as said user.

**Comment by poettering** [comment]
porting homed to use the new policies that do not bother with keyring inheritance is already requested in #18280. hence I guess we can close this one.

**Comment by ebiggers** [comment]
> (recently fscrypt gained a new mode, where the availability of the key in the process tha accesses the fs is not rquired anymore, but so far we haven't updated homed to use it.)

This mode was released in kernel v5.4, before systemd-homed was merged into systemd.  So not exactly "recently".
