### ISSUE TITLE
[DHCPServerStaticLease] doesn't work with link-layer type MACs

### ISSUE THREAD

**Issue by tambry** [systemd/systemd#27562]
### systemd version the issue has been seen with

251.4

### Used distribution

Debian Unstable

### Linux kernel version used

6.1.0-6-amd64

### CPU architectures issue was seen on

amd64, arm64

### Component

systemd-networkd

### Expected behaviour you didn't see

systemd-networkd hands the correct static lease.

#### Details
[captures.zip](https://github.com/systemd/systemd/files/11419799/captures.zip)

`network_identifier_mac.pcap` – with `[DHCPv4] ClientIdentifier=mac` in the network file.
`networkd_link_layer.pcap` – with `[DHCPv4] DUIDType=link-layer` in `networkd.conf`.

`networkd_link_layer.pcap` doesn't work though it includes the MAC address within just like `network_identifier_mac.pcap`. I'd expect both cases to work. Specifying the DHCPv4 identifier in `networkd.conf` is in some cases more convenient.

### Unexpected behaviour you saw

systemd-networkd hands an address from the pool.

### Steps to reproduce the problem

Client:
```
[Match]
Type=ether

[Network]
DHCP=yes
```
Server:
```
[Match]
Type=ether

[Network]
DHCPServer=yes

[Address]
Address=10.0.5.1/24

[DHCPServerStaticLease]
MACAddress=06:9a:69:fd:d5:5b
Address=10.0.5.31
```
`networkd.conf`:
```
[DHCPv4]
DUIDType=link-layer
```

**Comment by yuwata** [comment]
Already fixed by #27313.
