### ISSUE TITLE
login1 call 'poweroff' doesn't honor inhibitions

### ISSUE THREAD

**Issue by hsitter** [systemd/systemd#27568]
### systemd version the issue has been seen with

249

### Used distribution

KDE neon 22.04

### Linux kernel version used

5.19.0-41-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

PowerOff should not let me PowerOff if there is a shutdown inhibition in place.

### Unexpected behaviour you saw

My machine powered off. I am not quite sure if this is intended behavior. Should I first check the active inhibitors before calling poweroff? The documentation doesn't really say.

### Steps to reproduce the problem

```
systemd-inhibit --mode=block sleep 30
busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager PowerOff b true
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CanPowerOff
s "yes"



systemd-inhibit 
WHO            UID  USER PID  COMM            WHAT                                                                       WHY              >
ModemManager   0    root 893  ModemManager    sleep                                                                      ModemManager need>
NetworkManager 0    root 771  NetworkManager  sleep                                                                      NetworkManager ne>
UPower         0    root 1828 upowerd         sleep                                                                      Pause device poll>
PowerDevil     1000 me   1811 org_kde_powerde handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch KDE handles power>
Screen Locker  1000 me   1730 ksmserver       sleep                                                                      Ensuring that the>
sleep 30       1000 me   3407 systemd-inhibit shutdown:sleep:idle                                                        Unknown reason   >

6 inhibitors listed.
```

**Comment by bluca** [comment]
You need to use the PowerOffWithFlags method and pass the `SD_LOGIND_ROOT_CHECK_INHIBITORS` flag as explained in the documentation https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#Methods
