### ISSUE TITLE
Misleading log message

### ISSUE THREAD

**Issue by vbezhenar** [systemd/systemd#27575]
### systemd version the issue has been seen with

253.4-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.1.27-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I stumbled upon a known issue with nginx. Basically I was getting log message

```
nginx.service: Can't open PID file /run/nginx.pid (yet?) after start: Bad file descriptor
```

At this moment I've already found out that this message is caused by nginx creating its pid file after its first process exited.

The issue was misleading log message. It's not about bad file descriptor. It should have been "file not found" or something like that. I spent time digging systemd sources trying to figure out why exactly systemd thinks that /run/nginx.pid is bad file descriptor and it turned out to be a bug with logging code. Not a big deal, but bug nonetheless IMO.

[Here](https://github.com/systemd/systemd/blob/477fdc5afed0457c43d01f3d7ace7209f81d3995/src/core/service.c#L1009) is code which prints this error message. It's my understanding that log_unit_full_errno third parameter is error code. fd is initialized with -EBADF value and it's supposed to be changed by chase_symlinks functions, but this function returned error, so fd still had that value and in the end, this value will be printed to the log.

Probably third parameter should be `r`, though I'm not really sure about that.

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #27577.
