### ISSUE TITLE
OnFailure/OnSuccess= fires between service auto-restarts

### ISSUE THREAD

**Issue by YHNdnzj** [systemd/systemd#27594]
### systemd version the issue has been seen with

latest main

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

`OnFailure=` fires only after start limit is hit, as per our documentation ([systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#OnFailure=)):

> A space-separated list of one or more units that are activated when this unit enters the "failed" state. A service unit using Restart= enters the failed state only after the start limits are reached.

### Unexpected behaviour you saw

`OnFailure=` fires between auto-restarts. This is originally mentioned in https://github.com/systemd/systemd/pull/26751#issuecomment-1483339684.

**Comment by YHNdnzj** [comment]
cc @poettering

**Comment by poettering** [comment]
the man page is simply wrong it appears.

**Comment by YHNdnzj** [comment]
> the man page is simply wrong it appears.

So the wrong information was added in https://github.com/systemd/systemd/pull/7646. Don't really know how the original reporter reached that conclusion...

**Comment by yuwata** [comment]
@YHNdnzj Why did you reopen this?

**Comment by YHNdnzj** [comment]
After some more investigations, things got much weirder. This behavior was (supposed to be at least) changed in https://github.com/systemd/systemd/commit/2ad2e41a7, and we still carry the code for that in `core/unit`:

https://github.com/systemd/systemd/blob/9e36da1541f3ff204290547ce1da0a18b0df75b8/src/core/unit.c#L2781-L2782

**Comment by YHNdnzj** [comment]
So it's either some other regression was introduced or we should remove this dangling code too.

**Comment by YHNdnzj** [comment]
The `will_auto_restart` attribute for `Service` was introduced in https://github.com/systemd/systemd/commit/deb4e7080, where `service_set_state` would have happened before `will_auto_restart` was reset to `false`. However, in the latest code, that's not the case anymore, rendering `will_auto_restart` useless and the confusing situation above.

https://github.com/systemd/systemd/blob/9e36da1541f3ff204290547ce1da0a18b0df75b8/src/core/service.c#L1997-L2002

**Comment by YHNdnzj** [comment]
I've tried this on systemd v240, and the problem persists. Now I think it's never been properly fixed... Given that we'll be introducing `RestartMode` that can handle this, I'll prepare a PR to remove the unneeded code.
