### ISSUE TITLE
Strange /dev/disk/by-path disk path confusion

### ISSUE THREAD

**Issue by jpsinthemix** [systemd/systemd#2762]
### Submission type
- [\* ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> …
> 229
> _NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> …
> Built from source
> ### In case of bug report: Expected behaviour you didn't see
> 
> …
> distinct /dev/disk/by-path nodes for different disk devices 
> ### In case of bug report: Unexpected behaviour you saw
> 
> …
> I'm seeing the following errors under systemd-229
# journalctl -b | grep Dev

Feb 28 19:59:09 b-movie systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart3.device: Dev dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart3.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sda/sda3 and /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:1/2:0:1:0/block/sdb/sdb3
Feb 28 19:59:09 b-movie systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart1.device: Dev dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart1.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:1/2:0:1:0/block/sdb/sdb1 and /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sda/sda1
Feb 28 19:59:10 b-movie systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart2.device: Dev dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart2.device appeared twice with different sysfs paths /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:1/2:0:1:0/block/sdb/sdb2 and /sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sda/sda2

This issue is present at least since systemd-228; I'm seeing it in systemd-229, and not in systemd-228, because
in systemd-229/src/core/device.c, the line
   log_unit_debug(u, "Device %s appeared twice with different sysfs paths %s and %s", e, DEVICE(u)->sysfs, sysfs);
was changed to
   log_unit_error( ..);

Additional info (I've attached a complete journal -b debug log as well):

Note that under /dev/disk/by-path, sda3, sdb1 and sdb2 are absent, and that
sdb3 (rather than sda3) is associated with pci-0000:00:1f.2-ata-1-part3.
# sys/devices entries:

/sys/devices/pci0000:00/0000:00:1f.1/ata1/host0/target0:0:0/0:0:0:0/block/sr0
/sys/devices/pci0000:00/0000:00:1f.1/ata1/host0/target0:0:1/0:0:1:0/block/sr1

/sys/devices/pci0000:00/0000:00:1f.1/ata2/host1/ No targets

/sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sda
/sys/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:1/2:0:1:0/block/sdb
/sys/devices/pci0000:00/0000:00:1f.2/ata4/host3/target3:0:0/3:0:0:0/block/sdc
# ls -l /dev/disk/by-path

lrwxrwxrwx 1 root root  9 Feb 28 19:59 pci-0000:00:1f.1-ata-1 -> ../../sr1
lrwxrwxrwx 1 root root  9 Feb 28 19:59 pci-0000:00:1f.2-ata-1 -> ../../sdb
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part1 -> ../../sda1
lrwxrwxrwx 1 root root 11 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part10 -> ../../sda10
lrwxrwxrwx 1 root root 11 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part11 -> ../../sda11
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part3 -> ../../sdb3
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part4 -> ../../sda4
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part6 -> ../../sda6
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part7 -> ../../sda7
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part8 -> ../../sda8
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-1-part9 -> ../../sda9
lrwxrwxrwx 1 root root  9 Feb 28 19:59 pci-0000:00:1f.2-ata-2 -> ../../sdc
lrwxrwxrwx 1 root root 10 Feb 28 19:59 pci-0000:00:1f.2-ata-2-part1 -> ../../sdc1
# ls -l /dev/disk/by-id

lrwxrwxrwx 1 root root  9 Feb 28 19:59 ata-ASUS_CRW-5232A4 -> ../../sr1
lrwxrwxrwx 1 root root  9 Feb 28 19:59 ata-ASUS_DRW-1608P3S -> ../../sr0
lrwxrwxrwx 1 root root  9 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH -> ../../sda
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part1 -> ../../sda1
lrwxrwxrwx 1 root root 11 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part10 -> ../../sda10
lrwxrwxrwx 1 root root 11 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part11 -> ../../sda11
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part4 -> ../../sda4
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part6 -> ../../sda6
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part7 -> ../../sda7
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part8 -> ../../sda8
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-Maxtor_6L200M0_L415MLCH-part9 -> ../../sda9
lrwxrwxrwx 1 root root  9 Feb 28 19:59 ata-ST3200822AS_5LJ07WEJ -> ../../sdc
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-ST3200822AS_5LJ07WEJ-part1 -> ../../sdc1
lrwxrwxrwx 1 root root  9 Feb 28 19:59 ata-ST3250410AS_6RYEWQBZ -> ../../sdb
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-ST3250410AS_6RYEWQBZ-part1 -> ../../sdb1
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-ST3250410AS_6RYEWQBZ-part2 -> ../../sdb2
lrwxrwxrwx 1 root root 10 Feb 28 19:59 ata-ST3250410AS_6RYEWQBZ-part3 -> ../../sdb3
### In case of bug report: Steps to reproduce the problem

> …
> on each boot
> [00-systemd-udev-disk-by-path-journalctl_b.debug.txt](https://github.com/systemd/systemd/files/150338/00-systemd-udev-disk-by-path-journalctl_b.debug.txt)

**Comment by poettering** [comment]
Fixed by 071e0b8b3a698e73bcaecba09ffccab5553d2365. Closing.
