### ISSUE TITLE
networkd: Setting `IPForward` breaks SLAAC

### ISSUE THREAD

**Issue by exploide** [systemd/systemd#27639]
### systemd version the issue has been seen with

systemd-253.4-1.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

6.2.15-300.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When setting the `IPForward=yes` setting within a network config file, IPv6 SLAAC stops working. Without that setting, it works fine. I discovered this on a Debian 11 system but can reproduce on Fedora 38 with latest systemd.

### Steps to reproduce the problem

Without the `IPForward` setting, SLAAC works and all IP addresses are obtained:

```console
$ cat test.network 
[Match]
Name=enp0s20f0u4

[Network]
DHCP=ipv4

$ # restart networkd now, attach cable

$ ip a show enp0s20f0u4
7: enp0s20f0u4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:xx:xx:xx:xx:7f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.174/24 metric 1024 brd 192.168.1.255 scope global dynamic enp0s20f0u4
       valid_lft 43194sec preferred_lft 43194sec
    inet6 2003:xx:xxxx:xxxx::75c/128 scope global dynamic noprefixroute 
       valid_lft 43190sec preferred_lft 43190sec
    inet6 fd4b:xxxx:xxxx:xx::75c/128 scope global dynamic noprefixroute 
       valid_lft 43190sec preferred_lft 43190sec
    inet6 fd4b:xxxx:xxxx:xx:xxx:xxxx:xxxx:57f/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2003:xx:xxxx:xxxx:xxx:xxxx:xxxx:57f/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 81772sec preferred_lft 81772sec
    inet6 fe80::xxx:xxxx:xxxx:57f/64 scope link 
       valid_lft forever preferred_lft forever
```

But with `IPForward=yes` only an IPv4 address is obtained via DHCP but no IPv6 via SLAAC:

```console
$ cat test.network
[Match]
Name=enp0s20f0u4

[Network]
DHCP=ipv4
IPForward=yes

$ # restart networkd now, attach cable

$ ip a show enp0s20f0u4
7: enp0s20f0u4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:xx:xx:xx:xx:7f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.174/24 metric 1024 brd 192.168.1.255 scope global dynamic enp0s20f0u4
       valid_lft 43194sec preferred_lft 43194sec
```

**Comment by polarina** [comment]
Does setting `IPv6AcceptRA=` to `true` on the interface resolve your issue? The sysctl `accept_ra` has two positive values, `1` and `2`. The former enables RA only when forwarding is disabled, the latter enables it unconditionally. I suspect you may be running with the former.

**Comment by exploide** [comment]
Thanks, adding `IPv6AcceptRA=yes` indeed solved the issue.

I was not aware of this behavior. But if one reads the man page section of `IPv6AcceptRA` carefully:

> The default is to disable RA reception for bridge devices or when IP forwarding is enabled, and to enable it otherwise.

This was even more non obvious because it worked when enabling IP forwarding via sysctl instead of via networkd and without setting the sysctl `accept_ra`. Maybe this is because the man page section of `IPv6AcceptRA` furthermore states:

> Note that kernel's implementation of the IPv6 RA protocol is always disabled, regardless of this setting. If this option is enabled, a userspace implementation of the IPv6 RA protocol is used

So if one knows all this, it makes sense. I'm not sure whether the documentation could/should be improved. But apparently it's not a networkd specific issue, as the kernel's sysctl settings documents the same behavior. So I'm closing this issue for now.
