### ISSUE TITLE
selinux-autorelabel-generator.sh: SC3046 (warning): In POSIX sh, 'source' in place of '.' is undefined.

### ISSUE THREAD

**Issue by wileyhy** [systemd/systemd#27642]
### systemd version the issue has been seen with

253

### Used distribution

Fedora 38

### Linux kernel version used

6.2.9-300.fc38.x86_64

### CPU architectures issue was seen on

i686

### Unexpected behaviour you saw

Ran shellcheck on /usr/lib/systemd/system-generators/selinux-autorelabel-generator.sh on Fedora 38; got back a warning.  

### Steps to reproduce the problem

`shellcheck -x /usr/lib/systemd/system-generators/selinux-autorelabel-generator.sh`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
In /usr/lib/systemd/system-generators/selinux-autorelabel-generator.sh line 22:
    source /etc/selinux/config
    ^------------------------^ SC3046 (warning): In POSIX sh, 'source' in place of '.' is undefined.
    ^------------------------^ SC3051 (warning): In POSIX sh, 'source' in place of '.' is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC3046 -- In POSIX sh, 'source' in place of...
  https://www.shellcheck.net/wiki/SC3051 -- In POSIX sh, 'source' in place of...
```

**Comment by yuwata** [comment]
This is not provided by us.

**Comment by yuwata** [comment]
```sh
$ rpm -q --whatprovides /usr/lib/systemd/system-generators/selinux-autorelabel-generator.sh
policycoreutils-3.5-1.fc37.x86_64
```

**Comment by wileyhy** [comment]
copy that

**Comment by wileyhy** [comment]
Reported on Red Hat bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=2210593
