### ISSUE TITLE
Possible regression/ABI breakage in socket activation for Xorg bewteen v210 and v225

### ISSUE THREAD

**Issue by lbssousa** [systemd/systemd#2765]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229 (also affects previous releases since at least 225)

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.04 beta1 and 15.10
### In case of bug report: Expected behaviour you didn't see

> A X client must return gracefully after Xorg server has been started via systemd socket activation.
### In case of bug report: Unexpected behaviour you saw

> See this [Xorg bug](https://bugs.freedesktop.org/show_bug.cgi?id=93072).
### In case of bug report: Steps to reproduce the problem

> - Provide suitable socket/service unit files to start Xorg via socket activation.
> - Enable/start this socket unit.
> - Start a X client on the display that socket unit is listening on.
### Additional notes

> I've also observed this problem with Ubuntu 16.04, which ships systemd 229. However, this problem does **not** occur with openSUSE Leap 42.1, which ships the same Xorg version than Ubuntu 15.10, but stays with systemd 210. Thus I'm not sure whether it's a real Xorg bug, a systemd regression between v210 and v225, or some possible change in libsystemd that requires some update in Xorg.

**Comment by lbssousa** [comment]
I've finally tested Xorg socket activation in openSUSE Tumbleweed (Xorg 1.18.1 + systemd 228) and it's also not affected by this issue. Thus it's more likely to be a Debian/Ubuntu regression (or an upstream issue for which openSUSE already has a patch).

**Comment by kfiz** [comment]
I'm seeing this on Archlinux (Xorg 1.18.1-3 + systemd 229-3). This is consistent with what you are seeing as this seems to be a bug that started with systemd 229.

**Comment by poettering** [comment]
This bug report does not explain what precisely is supposedly not working. The linked fdo one is better, though.

Anyway, this very much looks like a problem in the X11 code, and I don#t see in anyway how systemd could be causing this. The socket activation code in systemd hasn't been touched in quite some time.

hence, please ask the X11 folks for help. If they let you know they are sure this is actually a systemd problem, please reopen this bug, but I think it's best to close this here for now. I hope that makes sense.
