### ISSUE TITLE
logind: Buggy Lid Switch Behavior on HP x360 Laptops

### ISSUE THREAD

**Issue by FaridZelli** [systemd/systemd#27665]
### systemd version the issue has been seen with

253

### Used distribution

Fedora 38

### Linux kernel version used

kernel-6.2.9-300.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

Closing the lid suspends the device, or performs any other action specified in the logind.conf file.

### Unexpected behaviour you saw

Closing the lid turns off the display, and ramps up the fans. Opening it again suspends the device. Additionally, leaving the lid closed for too long can sometimes result in overheating and a soft freeze.

### Steps to reproduce the problem

This problem can be reproduced with an HP Pavilion x360 Convertible (11th Gen) on any Linux distribution, regardless of the desktop environment. **To reproduce, simply boot or install Fedora 38 and close the lid.**

The exact model of the laptop in question is: ` HP Pavilion x360 Convertible 14-dy0183TU `

---

I have successfully reproduced this bug on:
- Debian 12
- Ubuntu 23.04
- Fedora 38
- openSUSE Tumbleweed
- Arch Linux (both with and without a desktop environment)

Note (1): Lid open and close events are successfully detected in all cases, see [gist bellow](https://gist.github.com/FaridZelli/f2470aad255fab61b4b0f613b4d3794f).

Note (2): Behavior is the same regardless of whether "suspend", "hibernate" or "poweroff" is assigned to HandleLidSwitch. Closing the lid turns off the display, fans ramp up, and re-opening the lid triggers the specified action.

Note (3): All three of these actions work fine when run using systemctl or assigned to the power button.

Note (4):  Closing the lid while the devices is suspended temporarily wakes up the device, and then enters a partially broken s2idle state where the fans may continue to run.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/FaridZelli/f2470aad255fab61b4b0f613b4d3794f
```

**Comment by FaridZelli** [comment]
To clarify, this is not a suspend/sleep issue. The problem persists with any action assigned to the lid switch as stated in Note (2). I haven't experienced anything remotely similar on Windows 10 or 11.

**Comment by poettering** [comment]
Sorry, but this is not the right place to report this. Please contact your distro for help. ACPI/PM issues are not something systemd is involved with, we do not manage such things.

Sorry, but this is smply not the right forum.

**Comment by FaridZelli** [comment]
> Sorry, but this is not the right place to report this. Please contact your distro for help. ACPI/PM issues are not something systemd is involved with, we do not manage such things.
> 
> Sorry, but this is smply not the right forum.

This is not an ACPI/PM issue, please read the details carefully and see Note (3). All ACPI events are registered correctly by the OS in this case. Distros utilizing e/logind are failing to complete actions triggered by the lid switch for some reason. I'd be happy to provide additional info if you guide me on how to debug this issue further.
