### ISSUE TITLE
systemctl show showing wrong timer value

### ISSUE THREAD

**Issue by hadmut** [systemd/systemd#27695]
### systemd version the issue has been seen with

249.11-0ubuntu3.9

### Used distribution

xubuntu 22.04

### Linux kernel version used

5.15.0-71-generic

### CPU architectures issue was seen on

None

### Component

systemctl

### Unexpected behaviour you saw

I'm having a service unit with a timer, set to 

[Timer]
OnStartupSec=30
OnUnitActiveSec=3600

and it works like expected. 

Output of systemctl list-timers is correct:

# systemctl list-timers | fgrep h-ipset
Fri 2023-05-19 00:18:06 EEST 13min left    Thu 2023-05-18 23:18:05 EEST 46min ago    h-ipset-update.timer           h-ipset-update.service

But systemctl show shows wrong next_elapse values:

# systemctl show h-ipset-update.timer |fgrep Timers    
TimersMonotonic={ OnUnitActiveUSec=1h ; next_elapse=2d 5h 51min 14.136440s }
TimersMonotonic={ OnStartupUSec=30s ; next_elapse=19min 998.368ms }

1. It says USec instead of Sec
2. It shows a next_elapse for OnStartupSec, although already run
3. It shows 2d 5h 51min for OnUnitActiveSec, although 1 hour is set and next run scheduled in 13min. 

### Steps to reproduce the problem

Create a dummy service unit with any command and set at timer as described.

**Comment by yuwata** [comment]
v249 is too old here.
Could you reproduce the issue with the latest release or the current git HEAD?

**Comment by yuwata** [comment]
> 1. It says USec instead of Sec

That's intentional. Unit settings end with `Sec`, but DBus properties end with `USec`.
