### ISSUE TITLE
Too verbose logging when systemd-backlight doesn't exist.

### ISSUE THREAD

**Issue by nunojpg** [systemd/systemd#27693]
### systemd version the issue has been seen with

252.4

### Used distribution

Buildroot master

### Linux kernel version used

6.1.28

### CPU architectures issue was seen on

aarch64

### Component

other

### Unexpected behaviour you saw

I have systemd without systemd-backlight.

Every time my display goes to sleep and the respective backlight is somehow cycled I get this error message:

sys-devices-platform-backlight-backlight-backlight.device: Failed to enqueue SYSTEMD_WANTS= job, ignoring: Unit systemd-backlight@backlight:backlight.service not found.

In my case it's every few seconds.

This is caused by 99-systemd.rules:  SUBSYSTEM=="backlight", TAG+="systemd", IMPORT{builtin}="path_id", ENV{SYSTEMD_WANTS}+="systemd-backlight@backlight:$name.service"

Since this is already a templated .in file, can't we just get rid of it when systemd-backlight is not included in the build?

**Comment by yuwata** [comment]
Fix is waiting in #27694.
