### ISSUE TITLE
[XEN] Use /sys/hypervisor/uuid to generate deterministic machine IDs

### ISSUE THREAD

**Issue by RA-Kooi** [systemd/systemd#27706]
### Component

other

### Is your feature request related to a problem? Please describe

Systemd parses the hypervisor UUID through DMI for KVM, Amazon, and QEMU. The UUID for these hypervisors is normally retrieved through `/sys/class/dmi/id/product_uuid`. Xen exposes this as well, but through `/sys/hypervisor/uuid`.

### Describe the solution you'd like

Please try fetching the UUID from `/sys/hypervisor/uuid`.

### Describe alternatives you've considered

1. Not caring.
2. Write a script/program that fetches the UUID and runs it through the same algorithm used in systemd and write it before `systemd-machine-id-commit.service` runs.

### The systemd version you checked that didn't have the feature you are asking for

253.4

**Comment by poettering** [comment]
Certainly makes sense, but would really require someone to supply a patch to add this.

**Comment by RA-Kooi** [comment]
I could try to submit a patch myself. I already have pretty clear idea of what would need to happen.

**Comment by poettering** [comment]
that would be very welcome. please submit as github PR
