### ISSUE TITLE
systemd-sysv-generator does not acknowledge services that are symlinks

### ISSUE THREAD

**Issue by veselov** [systemd/systemd#2772]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 222

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora 23
### In case of bug report: Expected behaviour you didn't see

> DSE (that doesn't really matter) sets up /etc/init.d/dse script that is a symlink, systemd-sysv-generator ignores the start-up script as a result.
### In case of bug report: Steps to reproduce the problem

> You can see the change made in 805e5dda0a01c99d231824e1a9c4a208418bf342, the service is added to the service list only if the /etc/init.d script is a regular file. I've seen packages use symlinks for /etc/init.d all the time. DSE definitely using it. Is there a particular reasoning for this check?

**Comment by evverx** [comment]
See https://github.com/systemd/systemd/pull/1249

> systemd version the issue has been seen with
> 222
> NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!

https://github.com/systemd/systemd/releases

**Comment by veselov** [comment]
Thank you.
And sorry! (blames Fedora)
