### ISSUE TITLE
shutdown fails if libgpg-error is installed to non-standard path

### ISSUE THREAD

**Issue by squeevee** [systemd/systemd#27729]
### systemd version the issue has been seen with

253

### Used distribution

Arch Linux

### Linux kernel version used

6.3.1-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Unexpected behaviour you saw

I extended my ldconfig cache to include a non-standard path (/opt/kde/lib), which happens to contain `libgpg-error.so`. Now `shutdown` fails to power off the machine. The last message on the tty reads:
```
/shutdown: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory
```

The machine (a VM) remains powered on but is unresponsive to everything except to a hard poweroff.

With `systemd.log_level=debug` in my kernel cmdline, the last messages on the tty are:
```
Successfully changed into root pivot.
Returning to initrd...
```

This seems to imply that the dynamic linker failure occurs when trying to execute /shutdown in the initrd. I attempted to rebuild my initcpio with the new ldconfig enabled to see if that would help, but the error still occurred and I started getting similar errors from systemd-tmpfiles during startup.

The problem does not occur if the custom build of libgpg-error is uninstalled, or if /usr/lib is explicitly added above the custom path in ldconfig.

**Comment by poettering** [comment]
That's a local issue. gpg-error is used by libgcrypt i guess. If you put such a core library onto some auxiliary partition such as /opt/ that is a pretty bad idea, but eiter way, it's for your initrd to address, not systemd, as we are not involved in building your initrd.

Hence closing. Please contact your distro for help. Or better: just don#t do what you are doing, it's a bad idea to have basic userspace depend on a library outside of /usr/

**Comment by squeevee** [comment]
> Or better: just don#t do what you are doing.

fwiw the only reason I'm using ldconfig is a work-around for an unrelated bug. I've already fixed my machine, but I'm not the most familiar with this init stuff thought this would be relevant info to systemd

Thanks for the prompt response
