### ISSUE TITLE
When two GPUs are present in the system, getty would start upon request, but would be irresponsive. 

### ISSUE THREAD

**Issue by feature-engineer** [systemd/systemd#27765]
### systemd version the issue has been seen with

252.10-2

### Used distribution

Manjaro

### Linux kernel version used

5.15.112-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

After successful Boot to X using a discrete GPU (with the integrated GPU\another discrete GPU active, but not connected to display) and pressing Ctrl+Alt+FN thereby opening getty@ttyN and transferring the display to VTN:
* Display getty@ttyN
* Ask for user login - get keyboard input and display it
* Ask for user password
* login after correct password is entered

### Unexpected behaviour you saw

After successful Boot to X using a discrete GPU (with the integrated GPU\another discrete GPU active, but not connected to display)
* Press Ctrl+Alt+FN - open getty@ttyN and transfer the display to VTN.
* Display last boot frame (if it was using plymouth or bootsplash-systemd), UEFI logo if it was quiet boot or boot output if it was not quiet.
* No prompt for login, and no input being collected (if trying to enter user name and password blindly to login without video output, it won't work).

### Steps to reproduce the problem

Have two GPUs enabled in your system.
e.g. intel's iGpu alongside NVIDIA's GPU, or 2 descrete GPUs.

Upon blacklisting i915, or pulling the other discrete GPU out, the expected behavior returned.

The boot sequence gets displayed fine, it is only after X starts that the tty stops responding.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
After Ctrl+Alt+F2 getty starts fine:

getty@tty2.service - Getty on tty2
     Loaded: loaded (/usr/lib/systemd/system/getty@.service; disabled; preset: enabled)
     Active: active (running) since Mon 2023-05-22 10:15:21 IDT; 16s ago
       Docs: man:agetty(8)
             man:systemd-getty-generator(8)
             http://0pointer.de/blog/projects/serial-console.html
   Main PID: 3417 (agetty)
      Tasks: 1 (limit: 38292)
     Memory: 400.0K
        CPU: 2ms
     CGroup: /system.slice/system-getty.slice/getty@tty2.service
             └─3417 /sbin/agetty -o "-p -- \\u" --noclear - linux



journalctl shows

... systemd[1]: Started Getty on tty2.
... audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=getty@tty2 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

After trying to input username and password to the frozen screen, loginctl list-sessions doesn't display another session (displays just the X session).
```

**Comment by poettering** [comment]
sorry, but this is not a systemd problem, we are not involved in graphics management, or multi-gpu handling. Please contact your distro for help, they will help you route this to the right people, but systemd is not it and is really not the right place for this. sorry.
