### ISSUE TITLE
Add VENDOR_NAME field to os-release

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#27777]
### Component

systemd-hostnamed

### Is your feature request related to a problem? Please describe

Currently there is no information in `os-release` about the OS vendor/distributor — all the information is about the OS product itself. For most use cases that’s fine. For a new feature in gnome-software, though, we’d like to be able to say something like “This app has been reviewed by ${os_vendor}”.

That requires a slightly different string from the OS name, as “This app has been reviewed by Red Hat Enterprise Linux” doesn’t quite make sense. In that case, it should be “Red Hat”.

See [the discussion here](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1712#note_1753864).

### Describe the solution you'd like

A new, optional, `VENDOR_NAME` field to be documented in `man os-release`. I don’t envisage systemd setting a default for it; the main reason for adding it in systemd would be to reserve the key name and make sure the semantics of it are consistent between vendors.

I can put together a pull request if this is desirable.

### Describe alternatives you've considered

We can use the static string “This app has been reviewed by the OS vendor” in gnome-software instead. Or we could opportunistically use the `VENDOR_NAME` key from os-release if it’s set, but without it being standardised. That’s asking for problems in the future though, when someone else defines it with different semantics.

### The systemd version you checked that didn't have the feature you are asking for

main (0de4bf4, 2023-05-24)

**Comment by poettering** [comment]
makes sense, send a patch!

**Comment by poettering** [comment]
do you also want a vendor URL too? so if you present the vendor name you can optionally make it clickable?

**Comment by pwithnall** [comment]
#27868 !
