### ISSUE TITLE
Journalctl has a problem of the log parser with Samba messages

### ISSUE THREAD

**Issue by Zesko** [systemd/systemd#27799]
### systemd version the issue has been seen with

253.4

### Used distribution

Arch Linux

### Linux kernel version used

6.1.29-1-lts

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

The messages about "Samba version" and "copyright" should not show  in journalctl log with the error level.

### Unexpected behaviour you saw

I get the same messages about "Samba version" and "copyright" at error level in systend-journal log every starting Samba service in Arch Linux.

Run `$ journalctl --no-pager -p err -b --output=cat`  to show these "error "messages of samba after starting smb.service:
```
[2023/05/25 09:39:08.726464,  0] ../../source3/smbd/server.c:1746(main)
  smbd version 4.18.2 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
```
I know these messages should not be at error level.  

Samba developer said:

> This is not a primary Samba problem, it's a problem of the log parser, which is mis-interpreting the strings for whatever reason.

Bugzilla of samba:
https://bugzilla.samba.org/show_bug.cgi?id=15377

### Steps to reproduce the problem

1. Use Arch Linux in VM
2. Install `samba`
3. Enable `smb.service`
4. Run `$ journalctl --no-pager -p err -b`
5. See the same "error" messages:
```
[2023/05/25 09:39:08.726464,  0] ../../source3/smbd/server.c:1746(main)
  smbd version 4.18.2 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023
```

**Comment by poettering** [comment]
how does samba send the log messages to journald? classic syslog protocol?

please provide the output of `journalctl -o verbose` for the relevant log lines, i.e. the full structured data.

**Comment by poettering** [comment]
So here's the relevant message:

```
Fri 2023-05-26 14:25:32.337872 CEST [s=a26c3524021b4250951cc819b8b6854a;i=b55dda;b=ad7c3dc0a90f4216813b4d8846f9beee;m=546c73;t=5fc97d54beed4;x=b8fc4e3c00945454]
    _BOOT_ID=ad7c3dc0a90f4216813b4d8846f9beee
    _MACHINE_ID=7595aaf89ae140ba9a7719bb326eb740
    _HOSTNAME=arch-nas
    SYSLOG_FACILITY=3
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _CAP_EFFECTIVE=1ffffffffff
    _RUNTIME_SCOPE=system
    _TRANSPORT=syslog
    SYSLOG_TIMESTAMP=May 26 14:25:32 
    PRIORITY=3
    SYSLOG_IDENTIFIER=smbd
    SYSLOG_PID=1017
    _PID=1017
    _COMM=smbd
    _EXE=/usr/bin/smbd
    _CMDLINE=/usr/bin/smbd --foreground --no-process-group
    _SYSTEMD_CGROUP=/system.slice/smb.service
    _SYSTEMD_UNIT=smb.service
    _SYSTEMD_INVOCATION_ID=7067b81e893c4a228de94d708376b371
    MESSAGE=  Copyright Andrew Tridgell and the Samba Team 1992-2023
    SYSLOG_RAW=<27>May 26 14:25:32 smbd[1017]:   Copyright Andrew Tridgell and the Samba Team 1992-2023
    _SOURCE_REALTIME_TIMESTAMP=1685103932337872
```

The message was received via the old BSD syslog proto (the _TRANSPORT= field indicates that). The `SYSLOG_RAW` field contains the literal, raw, unmodified string we received via that.

It starts with the prio + facility in `<>`. i.e. 27. that's calculated as (prio | (facility << 3), which if you reverse this means prio=3 and facility=3, i.e. `3 | (3 << 3) == 27`.

As you can see that's exactly what journald also parsed from it, in the split out fields PRIORITY=3 and SYSLOG_FACILITY=3.

And now, if you look into /usr/include/sys/syslog.h on your system you'll find that priority 3 is LOG_ERR. 

Hence journald is doing everything right. sambda simply sets a bogus priority on the message it sent there.

Closing here hence, please report to samba people.

**Comment by poettering** [comment]
Also, looking at the samba sources they invoke `DEBUG(0,` for logging these strings. afcais, the 0 is actually the literal value corresponding to DBGLVL_ERR. 

And someone in the bugzilla bug you linked even pointed to exactly that. So why even report this here? This needs to be fixed in the sambda codebase, they should probbaly change `DEBUG(0, … ` → `DEBUG(DBGLVL_INFO, …` in their codebase for the relevant messages.

**Comment by Zesko** [comment]
Thanks, I reopened the issue in the bugzilla.

**Comment by bjacke** [comment]
Lennart, can you please point out what systemd considers bogous about below log lines? Is systemd considering nothing to be logged by daemons under normal circumstances? I don't see anything wrong about version number and copyright notices in lowest log level. Don't argue with "DBGLVL_ERR" because this is just a samba interval function to log in log level 0.

[2023/05/25 09:39:08.726464,  0] ../../source3/smbd/server.c:1746(main)
  smbd version 4.18.2 started.
  Copyright Andrew Tridgell and the Samba Team 1992-2023

**Comment by bjacke** [comment]
never mind, I got the syslog prority point now :)
