### ISSUE TITLE
Load modules from non-standard places

### ISSUE THREAD

**Issue by FedericoVaga** [systemd/systemd#27797]
### Component

systemd-modules-load

### Is your feature request related to a problem? Please describe

All tools from `kmod` allow users to configure a different root directory (e.g. `depmod -b`, `modprobe -d`). However, `systemd-modules-load` initialize libkmod with [`kmod_new(NULL, NULL)`](https://github.com/systemd/systemd/blob/main/src/modules-load/modules-load.c#L177) hence it relies only on default values.

It would be nice to allow a custom path so that `systemd-modules-load` supports all those use cases where it is actually useful to have a different root directory

### Describe the solution you'd like

An additional option should be added to `systemd-modules-load` to set a different root. I would add `-d` to be similar to what `modprobe` does.

### Describe alternatives you've considered

 I would also consider adding an environment variable to achieve the same goal.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by poettering** [comment]
what's the rationale?

i mean, for low-level tools it might make sense to load modules from arbitrary places, but this one just loads a bunch of stuff at boot, possibly already from the initrd. what point is there to redirect kmods elsewhere then?

can't you just add a symlink in one direction or the other?

i am not convinced we need to make every path configurable. paths are handles, and fixed handles are nice. good thing is that these handles can be redirected via symlinks and bind mounts, hence why not use those?

**Comment by FedericoVaga** [comment]
I will describe the use case I've at hand.

I've a generic read-only root filesystem distributed over NFS to a few thousands of machines. Each machine has different needs in terms of what drivers must be loaded. These drivers are distributed to machines using a different mount point specific to the machine.

(Note. These drivers are custom drivers for specific internal industrial uses)

Because of the read-only option on the shared OS image, I can't just re-run `depmod` to rebuild `modules.dep` to take into account the machine-specific drivers in a different location. I will need to use `depmod -b <mypath>`.

I might add a symlink into `lib/modules/<kver>` to point to drivers from another location. Actually, `depmod.d` allows specifying `external` directories for this purpose. However, the problem is that I can't update `modules.dep` because it is read-only. And this forces me to have it elsewhere.

My idea was to re-run `systemd-modules-load` and tell the tool about my non-standard path.

I can change the mount point of `lib/modules/<kver>` to be elsewhere with RW permission. In my opinion, a CLI option is cleaner because it makes evident a problem/need and its solution; while symlinks and mount points are a bit hiding it. But again, my personal view.

**Comment by poettering** [comment]
Sorry, this seems really specialist. 

In particular as manual driver loading is really unnecessary these days, Linux/udev can very well load all drivers that are needed entirely automatically. what kind of drivers do you actually have in mind? nvidia stuf? uh, closed source crap makes this very uninteresting to us...

And what#s the problem with just serving every machine the full set of drivers? udev picks the right ones necessary anyway? What am I missing here?

**Comment by poettering** [comment]
still, why not serve all drivers on all systems and then just have one .dep file built for all?

**Comment by FedericoVaga** [comment]
Because:
- We are speaking about (our use case) of more than 20G of drivers (and their variants) for a quite large catalogue of hardware,
- Dozen of people actively working on new hardware/HDL/drivers.
- Dozen of people can't keep touching a common filesystem to add/remove/modify their driver and running `depmod`. A mistake could quickly propagate to hundreds of machines. To some extent also serious physical damage could happen. 

Hence:
- to limit potential damages or downtime, all software is delivered/installed per machine. And because root is RO they are elsewhere.

What you suggest is clearly doable. The environment I'm “describing” is far from perfect, and many changes could be done to improve the situation and go in the direction you propose. However, today we are not there. The suggestion I've made could help a bit. But it is not the end of the world if it is not implemented.

**Comment by poettering** [comment]
Sorry, but I remain unconvinced. This seems like a very specific solution to a very specific setup which happens to be less than ideal in my eyes. use symlinks, bind mounts (or even overlayfs if you must). but i am not convinced we should depart from our model of enforcing that resources are read from well-known and defined entry points and rather than changing them people should redirect them.

Sorry.

**Comment by FedericoVaga** [comment]
No sorry. That's also my feeling: the use case is very specific to our system. I just thought that such an option is not that exotic (`kmod` offers it), and it could have been added with a `--dirname` or something.

Thanks for discussion
