### ISSUE TITLE
test-barrier sometimes flaky on a VM with many vcpus (possibly related to crappy clocks)

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#278]
This is the same environment where I reproduced #175 in which often two subsequent calls of `test-journal-{stream,interleaving}` would produce the exact same result.

I also have some (less frequent) flakiness with `test-barrier`.

I haven't traced the exact source of the problem but it looks related to alarms triggering at the wrong time.

Sample assertions:

```
Assertion 'WIFEXITED(status)' failed at src/test/test-barrier.c:228, function test_barrier_wait_next_twice_sync(). Aborting.
FAIL test-barrier (exit status: 134)
```

Or:

```
Assertion 'WIFEXITED(status)' failed at src/test/test-barrier.c:438, function test_barrier_pending_exit(). Aborting.
Aborted (core dumped)
```

Also:

```
Assertion '0' failed at src/test/test-barrier.c:207, function test_barrier_wait_next_twice_local(). Aborting.
Assertion 'WTERMSIG(status) == SIGALRM' failed at src/test/test-barrier.c:207, function test_barrier_wait_next_twice_local(). Aborting.
Aborted (core dumped)
```

And finally:

```
Assertion 'WIFSIGNALED(status)' failed at src/test/test-barrier.c:411, function test_barrier_no_exit(). Aborting.
Aborted (core dumped)
```

I noticed this seems to happen when the machine is under load... I put it through a loop >1,000 times and it didn't fail, then as soon as I started a parallel make job on another session it started failing consistently.

I started adding some instrumentation to try to figure out what might be happening, but unfortunately still haven't found anything... Any suggestions would be really appreciated.

Cheers!
Filipe

**Comment by poettering** [comment]
@dvdhrm any idea?

**Comment by dvdhrm** [comment]
So I looked through the failing tests and they definitely look fine. However, the barrier tests use alarm() and usleep() with a BASE_TIME value to explicitly test for races. That is, all relative timing events that are tested, are multiples of BASE_TIME. Therefore, increasing BASE_TIME should fix all issues (@filbranden can you verify setting BASE_TIME in test-barrier.c to `USEC_PER_SEC` fixes your issues? Tests will take significantly longer then).

Anyway, I dislike pushing increased BASE_TIME to -git. This is still not guaranteed to succeed if your scheduler decides to not run your task for >BASE_TIME usecs (and it is free to do that under load).

Preferably, the kernel would have a clock that measures time a process spends on CPU and !RUNNING (i.e., measuring the exact process-cpu time but also the time it sleeps on purpose). Cannot figure out a way to achieve that, though. I could use busy-sleep, but that's nasty.

I will push a fix later on to TEST_SKIP test-barrier by default (except if you pass an argument).

**Comment by dvdhrm** [comment]
Pushed a workaround: fd23f9c9a70e1214507641d327da40d1688b74d7 (commit message explains it in some more detail)

Thanks a lot for the report! I will close this now, as I doubt there's anything we can "fix". If someone wants to port the barrier tests to use explicit synchronization instead of alarm/usleep, go ahead. But I doubt it's worth the effort (I put it on my long-time-TODO, anyway...).

**Comment by poettering** [comment]
@dvdhrm there are  actually multiple way to get timer events on the process time: 

a) RLIMIT_CPU + SIGXCPU. However, it's only precise to one second...

b) setitimer(ITIMER_VIRTUAL, ...)+ SIGVTALRM. That's the API you actually should use.

**Comment by dvdhrm** [comment]
Yeah, RLIMIT_CPU is useless.. I need microsecond precision, otherwise it takes ages to run the tests. ITIMER_VIRTUAL is also useless with the current code, as I want time I spend in usleep() to be accounted on the timer (which ITIMER_VIRTUAL does not do). Sure, I can rewrite the code to not do that, but then I can use explicit synchronization right from the beginning,
