### ISSUE TITLE
[enhancement] Permit nesting of `ReadWriteDirectories`, `ReadOnlyDirectories` and `InaccessibleDirectories`

### ISSUE THREAD

**Issue by nicoonoclaste** [systemd/systemd#2780]
### Submission type

> Request for enhancement (RFE)
### systemd version the issue has been seen with

> 228
### Used distribution

> Debian Stretch
### Proposal

Currently, it is impossible to use `ReadWriteDirectories`, `ReadOnlyDirectories` and `InaccessibleDirectories` on nested folders: this results in the following error:

```
Failed at step NAMESPACE spawning /some/binary: No such file or directory
```

This makes it rather difficult to express things like the following:

```
[Service]
InaccessibleDirectories=/srv
ReadOnlyDirectories=/srv/some-application
ReadWriteDirectories=/srv/some-application/cache
```

Instead, one has to rely on a “blacklist approach” by listing all the directories in (for example) `/srv`.

Moreover, while attempting to reproduce the issue on systemd 228, I discovered that if `PrivateTmp=true` is set, and `InaccessibleDirectories` and `ReadOnlyDirectories` are set in `/tmp`, they silently fail to be mounted in the service's namespace.

**Comment by poettering** [comment]
This is a misconception. You may nest them freely, with one exception: you cannot make stuff accessible below something that is inaccessible. That's simply because UNIX is that way, if you have a path /a/b/c/d/e/f, and you make the "c" in the middle completely inaccessible, then the full path becomes inaccessible too.

You may hence freely place ro dirs in rw dirs, and vice versa, plus inaccessible dirs below either, but not ro or rw dirs below inaccessible dirs.

I hope this makes sense?

**Comment by nicoonoclaste** [comment]
@poettering Sorry, it seems I didn't explain my issue very clearly: yes, I can nest `ReadOnlyDirectories` and `ReadWriteDirectories` freely.
My issue is that `InaccessibleDirectories` can only be put at the “leaves”, making it very cumbersome to describe some things (like my `/srv` example).

Would it be reasonable to automatically `mkdir -p` as needed when a mountpoint is specified under an `InaccessibleDirectory`?  That cannot break existing unit files, and it seems like a fairly desirable feature.

**Comment by poettering** [comment]
Again, InaccessibleDirectories= is by definition not nestable: it makes a whole subtree inaccessible. This is different from ReadWriteDeirectories= or ReadOnlyDirectories=: they still allow access, and hence you can stack them.

We shoul definitely document this better though, and clarify that InaccessibleDirectories= applys to the whole subtree and allows no nested exceptions, while the other two do allow nested exceptions.

Or in other words, the behaviour you are seeing is kinda a technical necessity and expected. The bug hence is pretty much just missing documentation clarifying this behaviour.

**Comment by nicoonoclaste** [comment]
@poettering I understand the current behavior.  I was merely asking about the feasibility of relaxing it (in a backwards-compat behavior) by:
- making `InaccessibleDirectories` be empty `tmpfs`;
- (recursively) creating directories for mount points (of `ReadWriteDirectories` and `ReadOnlyDirectories`) when they are under an `InaccessibleDirectory`;
- making the `tmpfs` read-only.

As I have argued, I think it makes those features much more applicable.
The main issue is that I'm not 100% certain how problematic things like `InaccessibleDirectories=/foo` and `ReadWriteDirectories=/foo/bar` are.

**Comment by poettering** [comment]
OK, makes sense as an RFE. So let's turn this into both a bug about improving the docs, and about extending behaviour as an RFE.

**Comment by nicoonoclaste** [comment]
@poettering Since #3048 was merged, I think you can drop the documentation label.
I had a look at how to implement this, and it feels like it would involve some refactoring of the current logic.

**Comment by sbocahu** [comment]
+1, would be nice !

**Comment by yuwata** [comment]
Please use `TemporaryFileSystem=` and `Bind{,ReadOnly}Paths=` as a workaround. For your example,
```
[Service]
TemporaryFileSystem=/srv
BindReadOnlyPaths=/srv/some-application
BindPaths=/srv/some-application/cache
```
may be sufficient to achieve your demand, I hope.
