### ISSUE TITLE
TEST-01-BASIC timed out

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#27807]
E.g. see https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/2659/artifact/systemd-centos-ci/artifacts_rwdcsaf3/vagrant-logs.lJj/vagrant-arch-sanity-boot-check.log

Maybe, caused by d689f70a2c18666bbf6500df7a53962a8f3e91a4.

**Comment by mrc0mmand** [comment]
> E.g. see https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/2659/artifact/systemd-centos-ci/artifacts_rwdcsaf3/vagrant-logs.lJj/vagrant-arch-sanity-boot-check.log
> 
> Maybe, caused by [d689f70](https://github.com/systemd/systemd/commit/d689f70a2c18666bbf6500df7a53962a8f3e91a4).

I think the fail is #27287, https://github.com/systemd/systemd/commit/d689f70a2c18666bbf6500df7a53962a8f3e91a4 just exacerbates the issue as it does a lot of reexecs.
