### ISSUE TITLE
cryptsetup does not check for given alternative keyfile in crypttab

### ISSUE THREAD

**Issue by Cyborgscode** [systemd/systemd#27815]
### systemd version the issue has been seen with

253

### Used distribution

Fedora 38

### Linux kernel version used

kernel-6.2.15-300.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

testing one keyfile after the other , if one keyfile device is not found

/etc/crypttab ( tested initramfs version ) 

luks-92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-uuid/92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_408D5CBFD9DDE691295618EB-0:0 luks,tries=5,keyfile-size=8192,keyfile-offset=512,keyfile-timeout=10,nofail
luks-1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 /dev/disk/by-uuid/1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_408D5CBFD9DDE691295618EB-0:0 luks,tries=5,keyfile-size=8192,keyfile-offset=512,keyfile-timeout=10,nofail,force
luks-92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-uuid/92b93668-3c6b-4b88-9c19-8575292c14ed /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_60A44C41388DE691293603F9-0:0 luks,tries=5,keyfile-size=8192,keyfile-offset=512,keyfile-timeout=20,nofail,force
luks-1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 /dev/disk/by-uuid/1ba1a9d5-7aef-4ccc-83fe-15b43458d9b9 /dev/disk/by-id/usb-Kingston_DataTraveler_3.0_60A44C41388DE691293603F9-0:0 luks,tries=5,keyfile-size=8192,keyfile-offset=512,keyfile-timeout=20,nofail,force

as you can see, we have two entries for each luks partition with a different usb key.

This behaviour is required if multiply usb drives with different keys are required to work i.e. as a security copy of the master key, multiply admins running around with the same key, but on different sticks etc. etc. etc.

### Unexpected behaviour you saw

Cryptsetup failed to recognize, that the device in line 3+4 is present and that it matched the crypttab entry. So it did not unlock the device, instead it falls back to password.

As fallback to password is the desired keyfile is not present, that part works, but needs adjustment to check for alternatives.

### Steps to reproduce the problem

none

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
none
```

**Comment by Cyborgscode** [comment]
workaround: use i.e.  /dev/disk/by-path/pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0

Which is the same for any usb stick inserted if nothing else changed in the usb environment.

**Comment by poettering** [comment]
this is simply not supported, /etc/crypttab entries must have a unique volume name, all but the first entry for each volume name will be ignored (and logged about).
