### ISSUE TITLE
systemctl restart systemd-vconsole-setup breaks others ttys

### ISSUE THREAD

**Issue by galdralag** [systemd/systemd#2784]
### Used distribution

Arch
Fedora22,23
### Description

After changing font in vconsole.conf and restarting systemd-vconsole-setup font changed in current tty but other ttys become broken.
### Steps to reproduce
1. Change font in /etc/vconsole.conf (I am using "UniCyr_8x14" or "UniCyr_8x8"). New font size and old font size should be differrent (for example 8x14 and 8x8).
2. Go to tty3 and login as root
3. Run "systemctl restart systemd-vconsole-setup"
4. Press Alt+F2 or Alt+F4 and see that tty2 and tty4 are broken

It is reproducable only when KMS applied or when added vga=0x318 (or other mode) to kernel command line (not in 80x25 text mode)

On some hardware configurations when font is not default ttys become broken on system boot.
I can see it when OS located on SSD drive and boot process very fast.

**Comment by poettering** [comment]
What precisely is "break" supposed to mean?

we simply use the KD_FONT_OP_COPY font ioctl to copy the font btween the various VCs. if that "breaks" the other VCs, then that sounds like a kernel console subsystem bug, noting we have control over.

Anyway, what do you mean by "broken"?

**Comment by galdralag** [comment]
"Broken" means that ttys become unreadable. See screenshots (current tty and broken tty).
![current tty](https://cloud.githubusercontent.com/assets/17591333/14572233/b4230494-035e-11e6-9067-c5506aee1932.png)
![broken tty](https://cloud.githubusercontent.com/assets/17591333/14572236/b83e4dd6-035e-11e6-9487-3316bdb02fdd.png)

**Comment by poettering** [comment]
OK, then definitely looks like a kernel console subsystem problem. We simply update the fonts, and don't draw or redraw anything. Please file a bug against the kernel. Thanks.
