### ISSUE TITLE
Extend SBAT rules to cover also the linux section in UKI

### ISSUE THREAD

**Issue by esposem** [systemd/systemd#27866]
### Component

systemd-stub

### Is your feature request related to a problem? Please describe

Currently an UKI is built with systemd-stub .sbat. This is good, as we have an sbat section that looks like this:
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
systemd,1,The systemd Developers,systemd,253,https://systemd.io/
systemd.rhel,1,Red Hat Enterprise Linux,systemd,253-2486-g7600c70,https://bugzilla.redhat.com/
```
where `systemd.rhel` probably is distro-dependent.

However, this is tied to systemd. If we have a bug in linux for example, we don't want to invalidate all systemd-stub executable, but just the ones containing the given linux section.
Therefore `ukify` should be extended to extend `.sbat` of UKI to cover also additional components.
For example one possibility proposed by @berrange would be:
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
systemd,1,The systemd Developers,systemd,251,https://www.freedesktop.org/wiki/Software/systemd
systemd.rhel,1,Red Hat Enterprise Linux,systemd,251.5-607.fc37,https://bugzilla.redhat.com/
linux,1,The systemd Developers,linux,5.19.1,https://www.linux.org
linux.rhel,1,Red Hat Enterprise Linux,linux,5.19.1-37.fc37,https://bugzilla.redhat.com/
```

Opinions?

**Comment by esposem** [comment]
@bluca @poettering @keszybz  FYI
Happy to work on this if it makes sense to you

**Comment by bluca** [comment]
Yes, we already talked about this, ukify should merged the stub and the kernel sbat sections

**Comment by poettering** [comment]
yeah, fully agree, ukify should extract the data from the embedded kernel, append whatever is specified on its own command line and insert the result in the UKI

**Comment by bluca** [comment]
Nice, thank you, will check it out (but not a kernel dev)

**Comment by esposem** [comment]
Don't worries, my main goal is to agree to have a proper SBAT naming.
