### ISSUE TITLE
systemctl preset warns about missing install section when there is a disable preset

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2786]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian

Running `systemctl preset unit.service` when there is a disable preset for that unit results in the following message:

> The unit files have no [Install] section. They are not meant to be enabled                                                                                                                     using systemctl.  
> Possible reasons for having this kind of units are:  
> 1) A unit may be statically enabled by being symlinked from another unit's .wants/ or .requires/ directory.  
> 2) A unit's purpose may be to act as a helper for some other unit which has a requirement dependency on it.  
> 3) A unit may be started when needed via activation (socket, path, timer, D-Bus, udev, scripted systemctl call, ...).                                                                                                                                                  

This message is not correct, as the unit does have an [Install] section.

**Comment by poettering** [comment]
Fixed a while back by 39207373dd638e548019ddb49929f15795b8b404
