### ISSUE TITLE
Eth1 Interface Address &Default gateway config does not work when eth0's config erased

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#27888]
### systemd version the issue has been seen with

251

### Used distribution

ubuntu

### CPU architectures issue was seen on

arm

### Component

systemd-networkd

### Expected behaviour you didn't see

Configured two ethernet interfaces eth0 and eth1 and both Ethernet Interfaces have routable IP addresses.
Erased IP address and default gateway on eth0 interface then eth1 network configuration stoped working. Seems eth1 default gateway is not getting used

### Unexpected behaviour you saw

IPaddress and Default Gateway configuration on Eth1,  did not work when Eth0 configuration erased.

### Steps to reproduce the problem

1. Configure two ethernet interfaces eth0 and eth1 interfaces with routable static IP    addresses 
2. Erase eth0's IP address and Gateway configuration.
3. Eth1 Network configuration stops working

### Additional program output to the terminal or log subsystem illustrating the issue

networkctl status eth1
* 3: eth1                                                                      
                     Link File: /lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/00-bmc-eth1.network
                          Type: ether
                          Kind: n/a
                         State: routable (configured)
                  Online state: online                                         
                          Path: platform-1e690000.ftgmac
                        Driver: ftgmac100
              Hardware Address: 08:94:xx:xx:00:05
                           MTU: 1500 (min: 68, max: 1500)
                         QDisc: pfifo_fast
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: 9.3.xxx.172
                                169.254.6.144
                                fe80::axx:exxx:fxxx:5
                       Gateway: 9.3.x.1
             Activation Policy: up
           Required For Online: yes

May 23 11:35:11  systemd-networkd[2801]: eth1: Link UP
May 23 11:35:11  systemd-networkd[2801]: eth1: Gained carrier
May 23 11:35:11  systemd-networkd[2801]: eth1: Gained IPv6LL
May 23 11:35:11 systemd-networkd[2801]: eth1: found matching network '/etc/systemd/network/00-bmc-eth1...e name.
May 23 11:35:11 systemd-networkd[2801]: eth1: Configuring with /etc/systemd/network/00-bmc-eth1.network.
May 23 12:20:26 systemd-networkd[2865]: eth1: Link UP
May 23 12:20:26 systemd-networkd[2865]: eth1: Gained carrier
May 23 12:20:26 systemd-networkd[2865]: eth1: Gained IPv6LL
May 23 12:20:26 systemd-networkd[2865]: eth1: found matching network '/etc/systemd/network/00-bmc-eth1...e name.
May 23 12:20:26 systemd-networkd[2865]: eth1: Configuring with /etc/systemd/network/00-bmc-eth1.network.

 networkctl status eth0
* 2: eth0                                                                                                
                     Link File: /lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/00-bmc-eth0.network
                          Type: ether
                          Kind: n/a
                         State: routable (configured)
                  Online state: online                                                                   
                          Path: platform-1e670000.ftgmac
                        Driver: ftgmac100
              Hardware Address: 08:94:ef:82:00:04
                           MTU: 1500 (min: 68, max: 1500)
                         QDisc: pfifo_fast
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: 169.254.236.138
                                2002:xxx:15f:xxx:9:41:xx:208
                                fe80::a94:exxx:fe82:4
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client IAID: 0x97301563
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab119fbacceebf1b51c30000
                  Connected To: aus-045-3n25-rack-f10-4-5100a.aus.stglabs.ibm.com on port 570 (xe-0/0/42)

May 23 11:35:11  systemd-networkd[2801]: eth0: Gained carrier
May 23 11:35:11 systemd-networkd[2801]: eth0: Gained IPv6LL
May 23 11:35:12 systemd-networkd[2801]: eth0: found matching network '/etc/systemd/network/00-bmc-eth0...e name.
May 23 11:35:12 systemd-networkd[2801]: eth0: Configuring with /etc/systemd/network/00-bmc-eth0.network.
May 23 12:20:25 systemd-networkd[2801]: eth0: DHCPv6 lease lost
May 23 12:20:26 systemd-networkd[2865]: eth0: Link UP
May 23 12:20:26 systemd-networkd[2865]: eth0: Gained carrier
May 23 12:20:26 systemd-networkd[2865]: eth0: Gained IPv6LL
May 23 12:20:26 systemd-networkd[2865]: eth0: found matching network '/etc/systemd/network/00-bmc-eth0...e name.
May 23 12:20:26 systemd-networkd[2865]: eth0: Configuring with /etc/systemd/network/00-bmc-eth0.network.

**Comment by poettering** [comment]
systemd version is too old to be tracked here. For old versions please contact your distro for help.

Also, this sounds more like support question, not a bug report, hence this place is wrong anyway.

**Comment by raviteja-b** [comment]
can you please share link where can I get distro help for this one
