### ISSUE TITLE
sudo unshare systemctl needs an extra sudo command

### ISSUE THREAD

**Issue by ericwoud** [systemd/systemd#27894]
### systemd version the issue has been seen with

253.4-1

### Used distribution

Archlinux / Archlinuxarm

### Linux kernel version used

linux 6.3.5.arch1-1

### CPU architectures issue was seen on

None

### Component

systemctl

### Expected behaviour you didn't see

`sudo unshare --fork --kill-child --pid --root=/tmp/loopdevmount systemctl --force --no-pager reenable systemd-timesyncd.service
`

Should remove and create symlinks.

### Unexpected behaviour you saw

It fails silently, not creating the symlinks.

With an extra sudo, before systemctl, it does work:

`sudo unshare --fork --kill-child --pid --root=/tmp/loopdevmount sudo systemctl --force --no-pager reenable systemd-timesyncd.service
`
But the user already is the root user, from the sudo at the start. The extra sudo should not be necessary, or should it?

### Steps to reproduce the problem

I was creating an image for an aarch64 system running Archlinuxarm, mounted on /tmp/loopdevmount. It is bootstrapped containing archlinuxarm. The systemctl command is the aarch64 version from archlinuxarm. The unshare command is executed on Archlinux x86_64, the host used to create the image.

The systemctl command is used to enable a service that will run on aarch64 when the image is booted from the development board.

Although it does not seem to be related to the architecture.

**Comment by poettering** [comment]
unshare's --root= sets up a chroot() environment. systemctl detects that and becomes a NOP.

Use `systemctl --root=` to do this cleanly.

**Comment by ericwoud** [comment]
Then perhapse it is a bug that chroot detection is not functioning when using the extra sudo?

**Comment by ericwoud** [comment]
> Use `systemctl --root=` to do this cleanly.

This indeed works, but on services enabled, that do not exist on the host, I get (unnecessary) warnings.

**Comment by poettering** [comment]
i have no idea what sudo does when run inside a chroot environment and what is in your PAM stack for sudo (which might even do more).

> This indeed works, but on services enabled, that do not exist on the host, I get (unnecessary) warnings.

hu? what do you mean? When you pass --root= to systemctl it will only operate on said root, not on the host. Anything else would be a bug.

**Comment by ericwoud** [comment]
It is a bit different then I remember. The warnings are about non-existent devices.  I know these are non existent...

The warnings are:
`
Unit /tmp/bpirootfs.8312/etc/systemd/system/hostapd@.service is added as a dependency to a non-existent unit sys-subsystem-net-devices-wlan0.device.

Unit /tmp/bpirootfs.8312/etc/systemd/system/hostapd@.service is added as a dependency to a non-existent unit sys-subsystem-net-devices-wlan1.device.
`
With my service file being:
`
[Unit]
Description=Access point and authentication server for Wi-Fi and Ethernet (%I)
Documentation=man:hostapd(8)
Before=ssh-fix-reboot.service
After=network.target
BindsTo=sys-subsystem-net-devices-%i.device

[Service]
Type=forking
PIDFile=/run/hostapd.%i.pid
Restart=on-failure
RestartSec=2
EnvironmentFile=-/etc/default/hostapd
ExecStart=/usr/local/sbin/hostapd-launch --pidfile /run/hostapd.%i.pid --device %i

[Install]
WantedBy=multi-user.target sys-subsystem-net-devices-%i.device
`

**Comment by arvidjaar** [comment]
> ```
>[Install]
>WantedBy=sys-subsystem-net-devices-%i.device
>```

Does it work at all? Device units are not "started", systemd simply waits for them to appear.

**Comment by ericwoud** [comment]
I am only using systemctl inside a script to prepare an image that will run on my development board. Nothing needs to be started, only the symlinks need to be created. The warnings in this case are unwanted and confusing for the user of the script.

I prefer using the systemctl binary from the chroot, as I know exactly which version it is, unlike the hosts systemctl binary. For me then it works best using the extra sudo, although it remains unclear why this bypasses chroot detection. In this way also no confusing warnings.

Anyway thanks for the support.
