### ISSUE TITLE
Can not set SCHED_FIFO or SCHED_RR in service when started by systemd.

### ISSUE THREAD

**Issue by h2cw2l** [systemd/systemd#27893]
**systemd version**
nvidia@EAXVA05_A:~$ systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**In process below, I set main thread to SCHED_FIFO.**
```
#include <sched.h>
#include <stdio.h>

int main(int argc,char *argv[])
{
  struct sched_param param;
  int maxpri, count;

  maxpri = sched_get_priority_max(SCHED_FIFO);
  if(maxpri == -1) {
    perror("sched_get_priority_max() failed");
    return -1;
  }
  printf("max priority of SCHED_FIFO is %d\n", maxpri);

  param.sched_priority = maxpri;
  if (sched_setscheduler(getpid(), SCHED_FIFO, &param) == -1) {
    perror("sched_setscheduler() failed");
    return -1;
  }

  while(1) {
      count++;
  }

  return 0;
}

```

**I let process above start by systemctl start xxx**
[Unit]
Description=test

[Service]
User=root
Group=root
ExecStart=/home/wyl/a.out

[Install]
WantedBy=multi-user.target

**error**
sched_setscheduler() failed: Operation not permitted

**When I directly run a.out not by systemctl, it will set succesfully.**

**Comment by YHNdnzj** [comment]
Sorry, this is the upstream bug tracker for systemd, and we only support the latest two versions here, namely v252 and v253. Please report to your distro if you're using older versions.

Closing. Feel free to ask for reopen if this can be reproduced on newer versions.

**Comment by poettering** [comment]
your kernel probably has the rt period via cgroup configuration stuff on. which means no service will get rt priv unless you configure an rt budget, but we offer no concept for that. disable this stuff in kernel really. 

contact your distro for help though, this is all ancient stuff, which we don't track upstream.
