### ISSUE TITLE
ppoll called with fds buffer too small file nfds entries

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#279]
I'm seeing this warning when building with gcc-5.1.0/glibc-2.20. I'm not sure if it is significant, but I wanted to bring it to your attention.

```
In function '__ppoll_alias',
    inlined from 'bus_poll' at src/libsystemd/sd-bus/sd-bus.c:2822:11:
/usr/include/bits/poll2.h:71:9: warning: call to '__ppoll_chk_warn' declared with attribute warning: ppoll called with fds buffer too small file nfds entries
  return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));
```

**Comment by crrodriguez** [comment]
This is a compiler bug.. see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61886 for details.

**Comment by floppym** [comment]
Thanks.

**Comment by bogdanr** [comment]
I have gcc-5.3.0 and glibc-2.23 and it also happens to me on systemd-229.
What version of gcc should I use ?

**Comment by wlhlm** [comment]
The bug report linked above lists working/failing GCC versions.

> Known to work:    4.7.4, 6.0
> Known to fail:  4.8.3, 4.9.1, 5.3.0
