### ISSUE TITLE
`systemd-xdg-autostart-generator` terminating process a bit too eagerly?

### ISSUE THREAD

**Issue by polarathene** [systemd/systemd#27919]
### systemd version the issue has been seen with

253.4-1-arch

### Used distribution

EndeavourOS

### Linux kernel version used

6.3.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-xdg-autostart-generator

### Expected behaviour you didn't see

Service `Exec=` in `.desktop` is run and provides it's functionality.

### Unexpected behaviour you saw

Service generated by `systemd-xdg-autostart-generator` frequently failed to run due to timeout. Functionality of service was not available until manually starting it or rebooting with a successful start before the timeout.

### Steps to reproduce the problem

This has been reported at `vmware/open-vm-tools` since Jan 2022: https://github.com/vmware/open-vm-tools/issues/568#issuecomment-1575478623

The package provides a file `/etc/xdg/autostart/vmware-user.desktop` which on a VMware guest running a distro using systemd and KDE Plasma, is commonly found to fail to start via the generated systemd service.

**UPDATE:** Initially I suspected `TimeoutSec=5s`, which when unset does seem to prevent terminating the otherwise working executable.
- Increasing the timeout did not help, so it was not too low.
- Overrides can be applied for special cases like this, until the project behaves better with systemds generated service or they opt-out of `.desktop` and supply their own service file.

Changing the `Exec=` binary in the `.desktop` to run a shell script that calls the same executable does not seem to fail. Perhaps because that becomes the main process, instead of the original `Exec=/usr/bin/vmware-user-suid-wrapper` affecting the exit status tracked by systemd for `ExitType=cgroup`? (_which presumably is what the `TimeoutSec=` tracks?_)

---

This `.desktop` file:

```
[Desktop Entry]
Type=Application
Exec=/usr/bin/vmware-user-suid-wrapper
Name=VMware User Agent
X-KDE-autostart-phase=1
```

Results in this generated service:

```
# /run/user/1000/systemd/generator.late/app-vmware\x2duser@autostart.service
# Automatically generated by systemd-xdg-autostart-generator

[Unit]
Documentation=man:systemd-xdg-autostart-generator(8)
SourcePath=/etc/xdg/autostart/vmware-user.desktop
PartOf=graphical-session.target

Description=VMware User Agent
After=graphical-session.target

[Service]
Type=exec
ExitType=cgroup
ExecStart=:/usr/bin/vmware-user-suid-wrapper
Restart=no
TimeoutSec=5s
Slice=app.slice
```

### Additional program output to the terminal or log subsystem illustrating the issue

Presently you'll get one of the current logs.

**Successful run log:**

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

● app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
     Active: active (running) since Mon 2023-06-05 18:09:19 NZST; 12s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 878 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 878 (code=exited, status=0/SUCCESS)
      Tasks: 4 (limit: 4624)
     Memory: 36.7M
        CPU: 279ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-vmware\x2duser@autostart.service
             └─884 /usr/bin/vmtoolsd -n vmusr --blockFd 3

Jun 05 18:09:19 polarathene systemd[590]: Starting VMware User Agent...
Jun 05 18:09:19 polarathene systemd[590]: Started VMware User Agent.
Jun 05 18:09:21 polarathene vmtoolsd[884]: gtk_disable_setlocale() must be called before gtk_init()
```

**Failed run log:**

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

× app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
     Active: failed (Result: timeout) since Mon 2023-06-05 18:14:21 NZST; 13s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 878 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 878 (code=exited, status=0/SUCCESS)
        CPU: 318ms

Jun 05 18:14:16 polarathene systemd[595]: Starting VMware User Agent...
Jun 05 18:14:18 polarathene vmtoolsd[882]: gtk_disable_setlocale() must be called before gtk_init()
Jun 05 18:14:21 polarathene systemd[595]: app-vmware\x2duser@autostart.service: start operation timed out. Terminating.
Jun 05 18:14:21 polarathene systemd[595]: app-vmware\x2duser@autostart.service: Failed with result 'timeout'.
Jun 05 18:14:21 polarathene systemd[595]: Failed to start VMware User Agent.
```

**Comment by polarathene** [comment]
`TimeoutSecs=5s` is just a guess as the cause, since a non-generated unit doesn't seem to reproduce it (_even when I tried a lower `TimeoutSecs=2s`_). I suppose an override drop-in unit might help verify that? (_assuming that works for generated units like this_)

---

I've also opened a PR at `open-vm-tools` to resolve it there with an explicit unit instead (_but historically they've delegated this to packagers_): https://github.com/vmware/open-vm-tools/pull/670

Reporting the issue here in the event it affects any other services (_a [potentially other service affected might be `insync`](https://bugs.kde.org/show_bug.cgi?id=433538#c5)_).

**Comment by polarathene** [comment]
- Unsetting the timeout via an override does seem to resolve it, although the status reported differs vs earlier success log.
- A permissive timeout of `120s` didn't help, the service functioned correctly until that was reached and triggered killing the process.
- Further experimentation suggests it's likely due to some dependency the command executed is expecting to be ready, a separate `vmtoolsd.service` exists and may be a race condition that triggers systemd to kill the process.

---

<details>
<summary>Override to `Type=forking` + `ExitType=main`</summary>

The child process became the Main PID and exited with failure status.
- Another process `/usr/bin/vmtoolsd -n vmusr --blockFd 3` (PID 867) was still running and providing the expected functionality however. Normally this PID 867 would match the `vmtoolsd` log line and be listed in the CGroup for the service.

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

× app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Mon 2023-06-05 19:37:09 NZST; 7s ago
   Duration: 2.179s
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 856 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 871 (code=exited, status=1/FAILURE)
        CPU: 276ms

Jun 05 19:37:07 polarathene systemd[601]: Starting VMware User Agent...
Jun 05 19:37:07 polarathene systemd[601]: Started VMware User Agent.
Jun 05 19:37:09 polarathene vmtoolsd[871]: gtk_disable_setlocale() must be called before gtk_init()
Jun 05 19:37:09 polarathene systemd[601]: app-vmware\x2duser@autostart.service: Main process exited, code=exited, status=1/FAILURE
Jun 05 19:37:09 polarathene systemd[601]: app-vmware\x2duser@autostart.service: Failed with result 'exit-code'.
```

This failure was probably more informative, but after enough restarts of the guest, it did eventually succeed:

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

● app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: active (running) since Mon 2023-06-05 19:55:06 NZST; 28s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 875 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 886 (vmtoolsd)
      Tasks: 4 (limit: 4624)
     Memory: 36.7M
        CPU: 360ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-vmware\x2duser@autostart.service
             └─886 /usr/bin/vmtoolsd -n vmusr --blockFd 3

Jun 05 19:55:06 polarathene systemd[547]: Starting VMware User Agent...
Jun 05 19:55:06 polarathene systemd[547]: Started VMware User Agent.
Jun 05 19:55:08 polarathene vmtoolsd[886]: gtk_disable_setlocale() must be called before gtk_init()
```

The Main PID is now aligned to that log line again.

</details>

<details>
<summary>Valid Override (TimeoutSec=120s)</summary>

The failure event still occurs at the timeout of `120s`. This can be avoided with an override that unsets the `5s` default with `TimeoutSec=` instead.

**Success:**

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

○ app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: inactive (dead) since Mon 2023-06-05 19:14:36 NZST; 7s ago
   Duration: 1.864s
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 876 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 876 (code=exited, status=0/SUCCESS)
        CPU: 223ms

Jun 05 19:14:34 polarathene systemd[609]: Starting VMware User Agent...
Jun 05 19:14:34 polarathene systemd[609]: Started VMware User Agent.
Jun 05 19:14:36 polarathene vmtoolsd[882]: gtk_disable_setlocale() must be called before gtk_init()
```

**Failure:**

```console
$ systemctl --user status "app-vmware\x2duser@autostart.service"

● app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: activating (start) since Mon 2023-06-05 19:18:51 NZST; 1min 59s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 877 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 877 (code=exited, status=0/SUCCESS)
      Tasks: 4 (limit: 4624)
     Memory: 30.5M
        CPU: 995ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-vmware\x2duser@autostart.service
             └─884 /usr/bin/vmtoolsd -n vmusr --blockFd 3

Jun 05 19:18:51 polarathene systemd[572]: Starting VMware User Agent...
Jun 05 19:18:53 polarathene vmtoolsd[884]: gtk_disable_setlocale() must be called before gtk_init()


# After the 120s timeout is reached, process killed:
$ systemctl --user status "app-vmware\x2duser@autostart.service"

× app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: failed (Result: timeout) since Mon 2023-06-05 19:20:51 NZST; 2s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 877 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 877 (code=exited, status=0/SUCCESS)
        CPU: 1.016s

Jun 05 19:18:51 polarathene systemd[572]: Starting VMware User Agent...
Jun 05 19:18:53 polarathene vmtoolsd[884]: gtk_disable_setlocale() must be called before gtk_init()
Jun 05 19:20:51 polarathene systemd[572]: app-vmware\x2duser@autostart.service: start operation timed out. Terminating.
Jun 05 19:20:51 polarathene systemd[572]: app-vmware\x2duser@autostart.service: Failed with result 'timeout'.
Jun 05 19:20:51 polarathene systemd[572]: Failed to start VMware User Agent.
Jun 05 19:20:51 polarathene systemd[572]: app-vmware\x2duser@autostart.service: Consumed 1.016s CPU time.
```

</details>

<details>
<summary>Invalid override (but prevented failure)</summary>

Mistake, config override was missing the relevant `[Service]` section as hinted by log. Oddly this still seemed more reliable at avoiding timeout failures.

`systemctl --user edit "app-vmware\x2duser@autostart.service"`:

```
### Anything between here and the comment below will become the contents of the drop-in file

TimeoutSec=15s

### Edits below this comment will be discarded
```

```
○ app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: inactive (dead) since Mon 2023-06-05 19:03:06 NZST; 6s ago
   Duration: 7.531s
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 878 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 878 (code=exited, status=0/SUCCESS)
        CPU: 253ms

Jun 05 19:02:58 polarathene systemd[522]: Starting VMware User Agent...
Jun 05 19:02:58 polarathene systemd[522]: Started VMware User Agent.
Jun 05 19:03:06 polarathene vmtoolsd[890]: gtk_disable_setlocale() must be called before gtk_init()
Jun 05 19:03:12 polarathene systemd[522]: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d/override.conf:1: Assignment outside of section. Ignoring.
```

```
○ app-vmware\x2duser@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; generated)
    Drop-In: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d
             └─override.conf
     Active: inactive (dead) since Mon 2023-06-05 19:04:42 NZST; 6s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 885 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 885 (code=exited, status=0/SUCCESS)
        CPU: 279ms

Jun 05 19:04:40 polarathene systemd[598]: Starting VMware User Agent...
Jun 05 19:04:42 polarathene vmtoolsd[888]: gtk_disable_setlocale() must be called before gtk_init()
Jun 05 19:04:42 polarathene systemd[598]: Started VMware User Agent.
Jun 05 19:04:48 polarathene systemd[598]: /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d/override.conf:1: Assignment outside of section. Ignoring.
```

</details>

**Comment by polarathene** [comment]
Closing since further inspection with overrides provided enough insight that the issue probably needs to be resolved within the `vmware-user-suid-wrapper` executable.

**Comment by polarathene** [comment]
Opening again to be considered for triage:
- `Type=forking` + `ExitType=main` appears like it may not be suitable after reading `ExitType=cgroup` discussions below being introduced to resolve this sort of issue.
- Potentially `TimeoutSec` should not behave this way with `ExitType=cgroup`? But it is intentionally part of the generated service from `systemd-xdg-autostart-generator`, so there is presumably some intent behind that?

---

Part of the adoption of `systemd-xdg-autostart-generator` [revealed quite a few processes not working well](https://bugs.kde.org/show_bug.cgi?id=433299), which motivated introduction of `ExitType=cgroup` (_[systemd v250 Dec 2021](https://github.com/systemd/systemd/blob/85614c6e2fb791b742941a8f98ea1851cf705240/NEWS#L2056-L2060)_) to resolve.

There was some race conditions discussed, and collection of the main process exit status, perhaps the failure (`code=exited, status=1/FAILURE`) that `Type=forking` + `ExitType=main` showed for Main PID is related to this causing `TimeoutSec=5s` to trigger the cgroup kill? (_despite the child process working correctly_)

<details>
<summary>Quoted references that may have some relevance</summary>

[Preferring `Type=cgroup`](https://github.com/systemd/systemd/pull/18782#issuecomment-786530309) over `Type=forking` (_renamed to `ExitType=cgroup` few comments later_):
> _The service ends up inactive instead of active after all processes exit, and reliably becomes running as soon as it should. This means restarts can work._
> _Also we are able to track the exit reason of the last process and eg restart accordingly_

https://github.com/systemd/systemd/pull/20813#issue-1004392814
> _This version instead uses the main process exit status if there is one and just listens to the cgroup empty event otherwise._

https://github.com/systemd/systemd/pull/20813#discussion_r726156458
> _on slow virtual machines this might be a bit racy, make it 10?_

https://github.com/systemd/systemd/pull/20813#discussion_r735690759
> _Builds with coverage and without optimization, on nested VMs without kvm on overworked nodes, will likely be racy. Can you make this deterministic?_
> _The point is that there's no guarantee that it will work as you want it with just a sleep. It might take much longer than 5s to schedule the job and get to the point in the script where you want it to happen._

That review feedback wasn't sufficient for the testsuite: https://github.com/systemd/systemd/pull/21483

https://github.com/systemd/systemd/pull/20813#discussion_r727063049
> _this appears unnecessary a change no? if we know a main or control pid it's worth waiting for them_

https://github.com/systemd/systemd/pull/20813#discussion_r727147719
> _I thought delaying setting the result until the cgroup became empty made more sense, but I think you're right._

</details>

**Comment by polarathene** [comment]
`systemctl --user cat "app-vmware\x2duser@autostart.service"` with the added content of `#` seems to be sufficient at preventing the failure. I've restarted the VM guest many times and cannot seem to reproduce the failure. Yet if I remove the override file, I can.

```console
$ systemctl --user cat "app-vmware\x2duser@autostart.service"

# /run/user/1000/systemd/generator.late/app-vmware\x2duser@autostart.service
# Automatically generated by systemd-xdg-autostart-generator

[Unit]
Documentation=man:systemd-xdg-autostart-generator(8)
SourcePath=/etc/xdg/autostart/vmware-user.desktop
PartOf=graphical-session.target

Description=VMware User Agent
After=graphical-session.target

[Service]
Type=exec
ExitType=cgroup
ExecStart=:/usr/bin/vmware-user-suid-wrapper
Restart=no
TimeoutSec=5s
Slice=app.slice

# /home/polarathene/.config/systemd/user/app-vmware\x2duser@autostart.service.d/override.conf
#
```

Perhaps that affects the timing in some manner?

---

## Reproduced with explicit unit

Disabled implicit service generation by including `X-systemd-skip=true` into the `.desktop` file, recreated the generated service as an explicit user unit with appended `[Install]` section and enabled it:

```console
$ systemctl --user cat vmware-user

# /home/polarathene/.config/systemd/user/vmware-user.service
[Unit]
Documentation=man:systemd-xdg-autostart-generator(8)
SourcePath=/etc/xdg/autostart/vmware-user.desktop
PartOf=graphical-session.target

Description=VMware User Agent
After=graphical-session.target

[Service]
Type=exec
ExitType=cgroup
ExecStart=:/usr/bin/vmware-user-suid-wrapper
Restart=no
TimeoutSec=5s
Slice=app.slice

[Install]
WantedBy=graphical-session.target
```

Within 10 restarts reproduced the failure:

```console
$ systemctl --user status vmware-user

× vmware-user.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; enabled; preset: enabled)
     Active: failed (Result: timeout) since Tue 2023-06-06 14:50:21 NZST; 1s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 879 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 879 (code=exited, status=0/SUCCESS)
        CPU: 313ms

Jun 06 14:50:16 polarathene systemd[567]: Starting VMware User Agent...
Jun 06 14:50:18 polarathene vmtoolsd[881]: gtk_disable_setlocale() must be called before gtk_init()
Jun 06 14:50:21 polarathene systemd[567]: vmware-user.service: start operation timed out. Terminating.
Jun 06 14:50:21 polarathene systemd[567]: vmware-user.service: Failed with result 'timeout'.
Jun 06 14:50:21 polarathene systemd[567]: Failed to start VMware User Agent.
```

Manually starting the service after failure:

```console
$ systemctl --user status vmware-user

● vmware-user.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user.desktop; enabled; preset: enabled)
     Active: active (running) since Tue 2023-06-06 14:51:08 NZST; 2min 7s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 1223 ExecStart=/usr/bin/vmware-user-suid-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 1223 (code=exited, status=0/SUCCESS)
      Tasks: 4 (limit: 4624)
     Memory: 10.1M
        CPU: 405ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/vmware-user.service
             └─1224 /usr/bin/vmtoolsd -n vmusr --blockFd 3

Jun 06 14:51:08 polarathene systemd[567]: Starting VMware User Agent...
Jun 06 14:51:08 polarathene systemd[567]: Started VMware User Agent.
Jun 06 14:51:08 polarathene vmtoolsd[1224]: gtk_disable_setlocale() must be called before gtk_init()
```

**Comment by polarathene** [comment]
Given all the above, assuming that an empty override may eventually trigger failure. It's probably best to either unset the `TimeoutSec` or possibly changing from `Type=exec` to `Type=fork` is appropriate in this case. It'd seem that `ExitType=cgroup` is preferable over `ExitType=main` based on discussions linked in an earlier comment.

`nano '~/.config/systemd/user/app-vmware\x2duser@autostart.service.d/override.conf'` with either:

```
[Service]
Type=forking
```

or 

```
[Service]
TimeoutSec=
```

Should can be used as a workaround until it's better understood if this is a quirk/incompatibility with the systemd generator, or related to the forking logic of `vmware-user-suid-wrapper` :man_shrugging:

**Comment by benzea** [comment]
> 5s is awfully short. @benzea and rationale for choosing such a super-short timeout? Why not use our default time-outs for that?

The default timeout of 90s is awfully long ...

Basically, the problem is when one of these get stuck, we cannot log out properly. So, if e.g. the desktop crashes you need to wait for 90s before being able to log in again. Though to be fair, this was about shutdown, not startup.

**Comment by polarathene** [comment]
Just to re-iterate, this isn't an issue where increasing the timeout duration would resolve it.

---

I'm still trying to identify what causes it without knowing much about the `open-vm-tools` codebase. They seem to be using GTK to support the clipboard sync and other features, the child process triggers a dbus request to activate the `at-spi-dbus-bus.service` which is usually intended for Accessibility features for services like Screen Readers. There is a `.desktop` file specifically for this on Gnome and Unity environments, and KDE has it's own `kaccess.desktop` (_calls a different program though_) but the VMware program seems interested in the SPI service.

So far it seems making that implicit dependency explicit with a service that triggers the SPI service before the VMware one is working reliably, getting the service to reach "Started".

**Comment by poettering** [comment]
> Basically, the problem is when one of these get stuck, we cannot log out properly. So, if e.g. the desktop crashes you need to wait for 90s before being able to log in again. Though to be fair, this was about shutdown, not startup.

sounds ok to me to have a short stop timeout, but a longer start timeout

**Comment by polarathene** [comment]
FWIW, I can reliably reproduce the failure or success now by overriding the `vmware-user.desktop` generated unit with:

Failure: (_Drop-in override won't work for unsetting `After=`, must create an explicit unit without `After=` condition instead_):
```
[Unit]
Before=graphical-session.target
```

Success (Delay start, requires increasing timeout):
```
[Service]
ExecStartPre=sleep 10
TimeoutSec=15
```

---

The failure can be resolved if I add an additional service:

```
[Unit]
Description=VM SPI
Wants=at-spi-dbus-bus.service
After=at-spi-dbus-bus.service

[Service]
Type=exec
ExitType=cgroup
ExecStart=/usr/lib/at-spi2-registryd --use-gnome-session
TimeoutSec=5s
Slice=session.slice
```

`at-spi-dbus-bus.service` directly was not reliable, the VMware unit would still request `registryd` via DBus once it started, but even with the VMware unit starting the new one defined above via `Wants=` + `After=` entries as well, if the unit above excludes the `Wants=` and `After=` to `at-spi-dbus-bus.service` (_which changes to requesting this unit via DBus instead of starting it directly first_) it would fail. Only with that direct VMware unit => custom registryd unit => at-spi-dbus-bus unit, does the VMware unit reliably start.

This unit would normally be invoked when the VMware unit calls `gtk_init()` AFAIK:

```console
$ systemctl --user cat "at-spi-dbus-bus.service"

# /usr/lib/systemd/user/at-spi-dbus-bus.service
[Unit]
Description=Accessibility services bus
PartOf=graphical-session.target

[Service]
Type=dbus
BusName=org.a11y.Bus
ExecStart=/usr/lib/at-spi-bus-launcher
Slice=session.slice
TimeoutStopSec=5
```

On GNOME, a `.desktop` XDG autostart file would have started the same `at-spi-bus-launcher`, which might be why it's a non-issue there (_not sure if `systemd-xdg-autostart-generator` is used by Gnome_).

---

Additionally:
- This whole explicit dependency chain above can be ignored by taking the same successful override, and delaying the VMware unit from starting long enough.
- I can mask the `at-spi-dbus-bus.service` preventing the process from being started, and all functionality still works.
- I assume either the delay added from the dependency chain or something started by the SPI service is providing the VMware unit with what it needs? I am aware that it uses X11/XLib features to perform some functionality before it calls `gtk_init()`.

The `gtk_init()` call will happen regardless of the VMWare unit being "Started", but for it to be "Started" successfully and avoid the Timeout kill, it needs to be successful before this point is reached, an extended timeout won't affect that, but as noted delaying unit from "Starting" via some sleep will allow time for whatever is needed to be available.

---

## Main problem?

What I don't quite understand is why this only affects `Type=exec` + `ExitType=cgroup`?

100% reproducible for me when I use the modified VMware unit to `Before=graphical-session.target` instead of `After=graphical-session.target` (_even without placing heavy load on the system_):
- :x: `Type=exec` + `ExitType=cgroup`
- :heavy_check_mark: `Type=exec` + `ExitType=main`
- :heavy_check_mark: `Type=forking` + `ExitType=cgroup`
- :heavy_check_mark: `Type=forking` + `ExitType=main`

Regardless of what is going on with the VMware unit `ExecStart=` and the race condition affecting `Type=exec` + `ExitType=cgroup`, why does it reliably fail to reach "Started" unlike the other combinations? **Is that expected?**
