### ISSUE TITLE
systemd-networkd drops config (routes/IP/etc.) of unmanaged wlan in rare race

### ISSUE THREAD

**Issue by c-andy-martin** [systemd/systemd#27910]
### systemd version the issue has been seen with

250

### Used distribution

Yocto Kirkstone

### Linux kernel version used

5.15.85-intel-pk-standard

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

systemd-networkd stays out of the way of unmanaged interfaces (in this case, the wireless interface is managed by NetworkManager). Normal journal output during wifi roaming (redacted):

```
2023-05-30T20:15:54.882440-04:00 hostname systemd-networkd[1016]: wlp3s0: Lost carrier
2023-05-30T20:15:54.882479-04:00 hostname systemd-networkd[1016]: wlp3s0: Connected WiFi access point: apname (XX:XX:XX:XX:XX:XX)
2023-05-30T20:15:55.325858-04:00 hostname systemd-networkd[1016]: wlp3s0: Gained carrier
```

### Unexpected behaviour you saw

systemd-networkd, in a rare race, drops the entire wireless interface when roaming (drops the routes, IPs, etc). Very rarely, the order of events between 'Gained carrier' and 'Connected WiFi...' are reversed, and 'Unmanaging interface.' is printed:

```
2023-05-30T20:20:36.939080-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Lost carrier
2023-05-30T20:20:36.939338-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Gained carrier
2023-05-30T20:20:36.939377-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Unmanaging interface.
2023-05-30T20:20:36.943075-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Connected WiFi access point: apname XX:XX:XX:XX:XX:XX)
```

The system in this case is a remote headless system installed in a customer's network (hence redacted journal). Immediately after this print, all outbound network connections get ENETUNREACH (101). I think this is because `link_drop_config` is called because `link_reconfigure_impl` is called with `force` set to `true` in this code path in `src/networkd/networkd-link.c`:

```
        /* If a wireless interface was connected to an access point, and the SSID is changed (that is,
         * both previous_ssid and ssid are non-NULL), then the connected wireless network could be
         * changed. So, always reconfigure the link. Which means e.g. the DHCP client will be
         * restarted, and the correct network information will be gained.
         *
         * However, do not reconfigure the wireless interface forcibly if it was not connected to any
         * access points previously (previous_ssid is NULL in this case). As, a .network file may be
         * already assigned to the interface (in that case, the .network file does not have the SSID=
         * setting in the [Match] section), and the interface is already being configured. Of course,
         * there may exist another .network file with higher priority and a matching SSID= setting. But
         * in that case, link_reconfigure_impl() can handle that without the force_reconfigure flag.
         *                      
         * For non-wireless interfaces, we have no way to detect the connected network change. So,
         * setting force_reconfigure = false. Note, both ssid and previous_ssid are NULL in that case. */
        force_reconfigure = link->previous_ssid && !streq_ptr(link->previous_ssid, link->ssid);
        link->previous_ssid = mfree(link->previous_ssid);
```

I have two problems with this code path. First is in this ordering race I assume `link->previous_ssid` is set to the value of the SSID (let's call it 'apname' b/c its actually a customer's network), and I assume `link->ssid` is NULL b/c the 'Connected WiFi' has not yet printed. In such a case, the logic in this code sets `force` to true. This looks like a bug, and the test should include a `&& link->ssid`

My second problem is a bigger one. The design should really be such that unmanaged interfaces are protected from such intrusion. I would assume as a user of systemd-networkd that if an interface is unmanaged that systemd-networkd would simply ignore all events on said interface. In such a case, this bug would be irrelevant to me (but not to those who are *managing* wifi and also hit this race, but to them they probably just witness a network reset that heals when systemd-networkd reconfigures the network). It actually really surprised me to see systemd-networkd outputting information about an unmanaged interface.

### Steps to reproduce the problem

Unfortunately I have no way to reproduce this. It does appear from the journal output some high load event pushed systemd-networkd to process the events very quickly, that may help expose the race. I have so far only seen this issue once, but it is a high severity for me as it forces manual intervention to get the remote, headless machine back on the network.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
2023-05-30T20:20:36.939080-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Lost carrier
2023-05-30T20:20:36.939338-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Gained carrier
2023-05-30T20:20:36.939377-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Unmanaging interface.
2023-05-30T20:20:36.943075-04:00 bar1071 systemd-networkd[1016]: wlp3s0: Connected WiFi access point: apname XX:XX:XX:XX:XX:XX)
```

**Comment by yuwata** [comment]
Sorry, v250 is slightly old here. Please contact to your downstream. Closing.

Feel free to request to reopen this if you reproduce the issue with v253 (or newer) or the current git HEAD.
In that case, please provide debugging logs of networkd and relevant .network file for the wlan interface.
Debugging logs can be generated by creating the following drop-in by `systemctl edit systemd-networkd.service`:
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
then restart networkd or reboot system.

**Comment by c-andy-martin** [comment]
This problem does not reproduce on v253. I looked at the source and see that the call was changed to only drop *managed* configs. I will work around this issue in v250 with a local patch.

**Comment by c-andy-martin** [comment]
For posterity sake, the fix for this is in v251 (from the beginning of v251), and is fixed in this commit:

```
commit a0e99a377a2f22c0ba460d3e7228214008714c14
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Mon Jan 31 19:08:27 2022 +0900

    network: remove only managed configs on reconfigure or carrier lost
    
    Otherwise, if the carrir of the non-managed interface is lost, the
    configs such as addresses or routes on the interface will be removed by
    networkd.
```
