### ISSUE TITLE
systemd-repart fully encrypts new encrypted partitions, which takes forever

### ISSUE THREAD

**Issue by valentindavid** [systemd/systemd#27923]
### systemd version the issue has been seen with

253.4

### Used distribution

Freedesktop SDK 23.08 beta 4

### Linux kernel version used

6.3.4

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

When a partition with `Encrypt=` is created. I expect the partition to be created in a very short time.

### Unexpected behaviour you saw

The partition, after being formatted, is being reencrypted. For a 512Gb nvme disk, it takes more than 5 hours.

Mailing list thread:
https://lists.freedesktop.org/archives/systemd-devel/2023-June/049152.html

Issue was introduced by 48a09a8fff480aab9a68e95e95cc37f6b1438751

### Steps to reproduce the problem

Make a repart.d partition spec with `Encrypt=tpm2`. Add that with systemd-repart in initrd. And try to boot.

**Comment by DaanDeMeyer** [comment]
I'm preparing a patch for this

**Comment by DaanDeMeyer** [comment]
@valentindavid Can you test with https://github.com/systemd/systemd/pull/27925?
