### ISSUE TITLE
measure: Make it possible to use a smart card for pcrsig (openssl engine)

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#27935]
### Component

other

### Is your feature request related to a problem? Please describe

I'm building a Linux distro and I want to keep the `pcrsig` signing keys for my UKIs secure. The best way to do that is to put my signing keys into a YubiKey or other HSM. 

I can do so for essentially every other kind of signature I'm producing, but `systemd-measure` does not give me a way to use a pkcs11 URI

### Describe the solution you'd like

Make it possible to specify a pkcs11 URI to `systemd-measure` (and to `ukify`)

### Describe alternatives you've considered

Encrypt the private key on disk with GPG (with a Smart Card), then decrypt it right before use

### The systemd version you checked that didn't have the feature you are asking for

main (as of 06390e2)

**Comment by poettering** [comment]
gpg yuck.

but yeah, we should support an openssl "engine" for this, which could then be anything people like, including smartcards.

**Comment by poettering** [comment]
Addressed by ed896a5b85ed6ef8b0abb79b0a76e4eb40d15233 I guess.
