### ISSUE TITLE
repart: CopyBlocks for volatile/overlay backed devices

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/systemd#27948]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

I'd like to install a verity-backed disk to another one by using CopyBlocks.  
I'm also using systemd.volatile=overlay.

### Describe the solution you'd like

When using CopyBlocks and the device behind the mount is a overlayfs (due to systemd.volatile=overlay), it should automatically guess the backing device and use that.

### Describe alternatives you've considered

Not using systemd.volatile.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
hmm, wha? not following?

are you suggesting we should automatically determine the backing block device of the "main" layer of an overlayfs? firstly, there's no sane API for that, overlayfs doesn't allow us to query anything like that. Also though: what does this even mean: overlayfs combines layers, so which layer is the one that matters for this?

**Comment by MariusSchiffer** [comment]
Hm, I see the problem. Maybe if we limit it to the specific case of `systemd.volatile=overlay`, can we avoid trying to query overlayfs?

In that case, there is only one lower layer, the /sysroot mounted by the initrd (whose mountpoint isn't even available anymore after the initrd).  
Do you think there is any reasonable way to find the block device from this?

**Comment by poettering** [comment]
in the special case of systemd.volatile= we actually provide a symlink pointing to the original block device in /run/systemd/volatile-root

**Comment by poettering** [comment]
that's all you need, no?

**Comment by MariusSchiffer** [comment]
It is. Thanks!
