### ISSUE TITLE
Error decrypting multiple LUKS encrypted devices using FIDO2

### ISSUE THREAD

**Issue by foxiagouhe** [systemd/systemd#27947]
### systemd version the issue has been seen with

systemd 253 (253.5-1-arch) +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

### Used distribution

ArchLinux 6.3.6

### Linux kernel version used

6.3.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Successfully unlocked multiple LUKS encrypted devices using FIDO2 during boot.

### Unexpected behaviour you saw

During boot, none of the LUKS encrypted devices with FIDO2 support could be decrypted successfully.Viewing the boot log may reveal related errors：
```
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Failed to open FIDO2 device /dev/hidraw2: FIDO_ERR_INTERNAL
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token returned error during pre-flight: Input/output error
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token 0 (systemd-fido2) open failed with -5.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token activation unsuccessful for device /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c: Input/output error
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Activating volume crypttest0 using token (systemd-fido2 type) -1.
```

### Steps to reproduce the problem

The hard disk partition is as follows：
```
Disk /dev/nvme0n1: 40 GiB, 42949672960 bytes, 83886080 sectors
Disk model: VMware Virtual NVMe Disk
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: B95413B4-0A3E-4F74-8EDD-04A776C587C8

Device           Start      End  Sectors  Size Type
/dev/nvme0n1p1    2048  1050623  1048576  512M EFI System
/dev/nvme0n1p2 1050624  5244927  4194304    2G Linux filesystem
/dev/nvme0n1p3 5244928  9439231  4194304    2G Linux filesystem
/dev/nvme0n1p4 9439232 83884031 74444800 35.5G Linux filesystem
```
`/dev/nvme0n1p2` and `/dev/nvme0n1p3` are encrypted partitions in LUKS2 format and will be decrypted during the boot of Arch Linux.

Use the following command to add FIDO2 support for them:
```
systemd-cryptenroll /dev/nvme0n1p2 --fido2-device=auto
systemd-cryptenroll /dev/nvme0n1p3 --fido2-device=auto
```
Entered the password for slot 0 and PIN for FIDO2 on the YubiKey during the process.

The luksheaders of these two partitions are as follows：
```
[root@archlinux ~]# cryptsetup luksDump /dev/nvme0n1p2
LUKS header information
Version:       	2
Epoch:         	5
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c
Label:         	(no label)
Subsystem:     	(no subsystem)
Flags:       	(no flags)

Data segments:
  0: crypt
	offset: 16777216 [bytes]
	length: (whole device)
	cipher: aes-xts-plain64
	sector: 512 [bytes]

Keyslots:
  0: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      argon2id
	Time cost:  20
	Memory:     1048576
	Threads:    4
	Salt:       92 a0 36 ef f0 05 0f 35 1f 1d d2 a8 d5 07 2a 37 
	            d2 70 e2 c2 69 ca 06 18 65 4e 4e 6e 52 73 10 5c 
	AF stripes: 4000
	AF hash:    sha512
	Area offset:32768 [bytes]
	Area length:258048 [bytes]
	Digest ID:  0
  1: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      pbkdf2
	Hash:       sha512
	Iterations: 1000
	Salt:       78 fc 03 7e f0 7e e9 f8 4e 09 50 44 cb f9 ef 91 
	            89 16 a6 76 83 95 3a d8 20 7b 89 ef 64 3b 37 dc 
	AF stripes: 4000
	AF hash:    sha512
	Area offset:290816 [bytes]
	Area length:258048 [bytes]
	Digest ID:  0
Tokens:
  0: systemd-fido2
	fido2-credential:
	            f9 33 71 8f 24 50 e8 0e 6f c8 b8 3b 0c 6e 12 ea
	            08 49 9e 38 fc d4 5b 39 ef ce 87 de d1 f5 3b a8
	            74 9e a2 6b 69 ea 0e 86 85 30 e2 8d e2 e1 fe fb
	            4e d6 68 d3 8f af d5 9d cc 30 29 8c 10 58 5e 7f
	fido2-salt: 00 06 62 23 0f 2d d0 30 fd 3a a0 2a 3d b0 09 30
	            62 dc 16 9c e9 77 97 47 d6 bd 66 f6 9b 75 69 0c
	fido2-rp:   io.systemd.cryptsetup
	fido2-clientPin-required:
	            true
	fido2-up-required:
	            true
	fido2-uv-required:
	            false
	Keyslot:    1
Digests:
  0: pbkdf2
	Hash:       sha512
	Iterations: 183317
	Salt:       b7 ce 32 5f 05 65 2c 06 39 14 e5 a4 44 25 06 8d 
	            2a 56 3d 2f bd d0 fd 9f 86 c1 ed 0f 43 ec 61 f4 
	Digest:     6a 72 07 9a 9f 62 7e d3 70 b7 0e 1b a2 d6 a1 d6 
	            d7 b2 36 a0 8b 55 e4 8f 3c 8a c2 03 30 09 1a 77 
	            1f 90 9b 81 20 d8 61 b2 cf 4b 06 f3 5d 5b 5f 46 
	            14 f2 1e 25 2b e7 0c 9d 5a 5b 03 84 fc 39 01 9a 

```

```
[root@archlinux ~]# cryptsetup luksDump /dev/nvme0n1p3
LUKS header information
Version:       	2
Epoch:         	5
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	4d3beb47-cec0-4a07-aba9-6ce17345f85c
Label:         	(no label)
Subsystem:     	(no subsystem)
Flags:       	(no flags)

Data segments:
  0: crypt
	offset: 16777216 [bytes]
	length: (whole device)
	cipher: aes-xts-plain64
	sector: 512 [bytes]

Keyslots:
  0: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      argon2id
	Time cost:  21
	Memory:     1048576
	Threads:    4
	Salt:       ce 6b 1d 7c b7 8b b4 38 2f 42 c6 e4 9a 8f 2e 74 
	            56 a1 d8 2a 59 72 da 77 d6 c5 45 68 f6 7e 4d 68 
	AF stripes: 4000
	AF hash:    sha512
	Area offset:32768 [bytes]
	Area length:258048 [bytes]
	Digest ID:  0
  1: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      pbkdf2
	Hash:       sha512
	Iterations: 1000
	Salt:       ee 25 87 1d 66 3a d3 cb cb 4f db 7b cd 12 d9 47 
	            97 3e de 7e a0 11 fd 4b 62 aa 88 f1 3a 91 ae ed 
	AF stripes: 4000
	AF hash:    sha512
	Area offset:290816 [bytes]
	Area length:258048 [bytes]
	Digest ID:  0
Tokens:
  0: systemd-fido2
	fido2-credential:
	            b3 05 c6 5f 3d b9 0d b3 80 c4 21 00 41 d7 36 28
	            a0 0a db 86 55 0a 42 ee 79 b3 8e 73 49 6c 99 c8
	            6b e7 aa d7 9b b0 44 a6 af 25 34 e1 45 62 82 0a
	            3f e3 06 54 57 db a3 fa 34 6f 0b d2 37 67 89 1c
	fido2-salt: c4 c9 1e b3 17 0c 0b 31 f7 4b 7c db e5 1f f7 73
	            dc e7 a7 b7 33 b2 d3 8a 97 a2 07 90 49 08 a8 c2
	fido2-rp:   io.systemd.cryptsetup
	fido2-clientPin-required:
	            true
	fido2-up-required:
	            true
	fido2-uv-required:
	            false
	Keyslot:    1
Digests:
  0: pbkdf2
	Hash:       sha512
	Iterations: 185391
	Salt:       52 38 67 8e 7e f4 71 0c 13 0c 0c ee db 97 da 8c 
	            a2 64 d8 8f d9 4a a6 89 39 92 2e 34 b4 9a 31 b9 
	Digest:     15 03 84 7d d7 ca 14 db b3 09 67 4b af fd 5e f2 
	            3c 9b fb c7 7c f2 ca 95 4e 1c 9a 6d 56 be 30 51 
	            47 80 ac 1d 1f 8e aa bd 97 6a 4d 90 08 87 05 53 
	            3a da 9f 3e e3 07 0b 10 64 7b de 7e 65 72 6f dd 
```

Set the devices to be decrypted during boot in the /etc/crypttab.initramfs file. The format of the file is as follows：
```
[root@archlinux ~]# cat /etc/crypttab.initramfs
cryptroot  UUID=e7503cf0-0f08-4533-a353-61bd248aae60  none  none
crypttest0  UUID=53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c  none  fido2-device=auto
crypttest1  UUID=4d3beb47-cec0-4a07-aba9-6ce17345f85c  none  fido2-device=auto
```

During startup, the screen displays `Please enter LUKS2 token PIN:` and `Please enter security token PIN:`. There is no indication as to which partition to enter the password for.  `/dev/nvme0n1p2` and `/dev/nvme0n1p3` partitions do not use the same password. enter the LUKS2 token PIN and security token PIN for one of the partitions, it will display:
```
(1 of 2) A start job is running for Cryptography Setup for crypttest0 (30s / no limit)
(2 of 2) A start job is running for Cryptography Setup for crypttest1 (30s / no limit)
```
After a while, a message may appear saying "failed to start Cryptography Setup for crypttest1".During this process, YubiKey did not prompt to be touched and in the end, both devices failed to decrypt successfully.

The complete startup log will be provided below. The related errors during the startup process are as follows:
```
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Failed to open FIDO2 device /dev/hidraw2: FIDO_ERR_INTERNAL
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token returned error during pre-flight: Input/output error
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token 0 (systemd-fido2) open failed with -5.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token activation unsuccessful for device /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c: Input/output error
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Activating volume crypttest0 using token (systemd-fido2 type) -1.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: dm versions   [ opencount flush ]   [16384] (*1)
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Detected dm-crypt version 1.24.0.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: dm status crypttest0  [ opencount noflush ]   [16384] (*1)
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token 0 unusable for segment 0 with desired keyslot priority 2.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Requesting JSON for token 0.
Jun 07 14:25:05 archlinux systemd-cryptsetup[176]: Token 0 (systemd-fido2) open failed with -55.
Jun 07 14:25:05 archlinux systemd-tty-ask-password-agent[184]: Starting password query on /dev/tty1.
Jun 07 14:25:08 archlinux systemd-tty-ask-password-agent[184]: Password query on /dev/tty1 finished successfully.
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: Added key to kernel keyring as 526384520.
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: Activating volume crypttest0 using token (systemd-fido2 type) -1.
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: dm versions   [ opencount flush ]   [16384] (*1)
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: dm status crypttest0  [ opencount noflush ]   [16384] (*1)
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: Token 0 unusable for segment 0 with desired keyslot priority 2.
Jun 07 14:25:08 archlinux systemd-cryptsetup[176]: Requesting JSON for token 0.
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Failed to open FIDO2 device /dev/hidraw2: FIDO_ERR_INTERNAL
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Token returned error during pre-flight: Input/output error
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Token 0 (systemd-fido2) open failed with -5.
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Releasing crypt device /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c context.
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Releasing device-mapper backend.
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Closing read only fd for /dev/disk/by-uuid/53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c.
Jun 07 14:25:29 archlinux systemd-cryptsetup[176]: Unloading systemd-fido2 token handler.
```

When I modify the `/etc/crypttab.initramfs` file to use fido2 decryption for only one partition, the partition can be successfully decrypted by YubiKey.
```
[root@archlinux ~]# cat /etc/crypttab.initramfs
cryptroot  UUID=e7503cf0-0f08-4533-a353-61bd248aae60  none  none
crypttest0  UUID=53d8cbdb-a0a3-4334-a727-2c7fbd91fb5c  none  none
crypttest1  UUID=4d3beb47-cec0-4a07-aba9-6ce17345f85c  none  fido2-device=auto
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/foxiagouhe/84f3bc623167a5d3bdb081f089361882
```

**Comment by poettering** [comment]
Hmm, this smells more like a libfido2 problem than a systemd problem.

libfido2 actually locks the fido2 devices to ensure concurrent access is properly synchronized. I am not sure why this doesn't work here. @martelletto any idea about this one?

Also see: https://github.com/Yubico/libfido2/pull/350

**Comment by martelletto** [comment]
Ping @LDVG

**Comment by foxiagouhe** [comment]
This is the software package information of `libfido2` in the system.
```
Name            : libfido2
Version         : 1.13.0-1
Description     : Library functionality for FIDO 2.0, including communication with a device over USB
Architecture    : x86_64
URL             : https://developers.yubico.com/libfido2/
Licenses        : BSD
Groups          : None
Provides        : libfido2.so=1-64
Depends On      : glibc  openssl  libcbor  libcbor.so=0.10-64  hidapi  systemd-libs  libudev.so=1-64  zlib
Optional Deps   : None
Required By     : None
Optional For    : openssh  systemd
Conflicts With  : None
Replaces        : None
Installed Size  : 521.10 KiB
Packager        : Christian Hesse <eworm@archlinux.org>
Build Date      : Wed 22 Feb 2023 05:18:18 AM CST
Install Date    : Wed 07 Jun 2023 01:12:12 AM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by MHOOO** [comment]
I can confirm the same issue inside a VM (when building a nixos-unstable Image):
* unlocking a single drive with FIDO2 (+ PIN) works without issue. During boot, I get prompted for the FIDO2 PIN via `Please enter LUKS2 token PIN:`  after which I can enter the PIN which causes my FIDO2 device to blink. Touching it, successfully decrypts the single drive.
* unlocking two drives, on the other hand, causes me to be asked `Please enter LUKS2 token PIN:`. Entering same PIN as above, does not appear to do anything. In particular, the FIDO2 device *does not* begin to blink. After a while I get `Please enter security token PIN:`. Neither my FIDO2 PIN, nor the LUKS2 password for the device work here. The two (concurring?) start-jobs for decrypting the LUKS devices just wait forever.

**Comment by poettering** [comment]
> Just wanted to chime in and say that we're looking. Nothing definitive yet, but given a modified build of libfido2 where debug output is always enabled (since systemd does not call `fido_init()`) my VM looks like it gets stuck indefinitely waiting for a response from the device.

i guess we should call that and hook up libfido2's logging with ours. for now i have file an issue about this, so that we don't forget about this: #27984

**Comment by foxiagouhe** [comment]
> Hi,
> 
> Just wanted to chime in and say that we're looking. Nothing definitive yet, but given a modified build of libfido2 where debug output is always enabled (since systemd does not call `fido_init()`) my VM looks like it gets stuck indefinitely waiting for a response from the device.
> 
> To verify that you're having the same problem: after the decryption fails, could you check if you have similar output to the below?
> 
> ```
> $ lslocks
> COMMAND           PID  TYPE SIZE MODE  M START END PATH
> systemd-cryptse   692 FLOCK      WRITE 0     0   0 /dev/hidraw1
>  
> $ strace -p 692
> strace: Process 692 attached
> ppoll([{fd=8, events=POLLIN}], 1, NULL, NULL, 8
> ```
> 
> Why this happens is not entirely clear to me yet.


Hello, I checked the output of the `lslocks` command (the disk decryption still failed during system startup) and didn't find any similar output:
```
[root@archlinux ~]# lslocks
COMMAND   PID  TYPE SIZE MODE  M START END PATH
dhcpcd    645 FLOCK   4B WRITE 0     0   0 /run/dhcpcd/pid

[root@archlinux ~]# systemd-cryptenroll --fido2-device=list
PATH         MANUFACTURER PRODUCT              
/dev/hidraw2 Yubico       YubiKey OTP+FIDO+CCID
```

**Comment by LDVG** [comment]
> Hello, I checked the output of the lslocks command (the disk decryption still failed during system startup) and didn't find any similar output

OK -- was the authenticator unplugged or used for anything else between startup and you running these commands?

**Comment by foxiagouhe** [comment]
> OK -- was the authenticator unplugged or used for anything else between startup and you running these commands?

I started the system after connecting the yubikey on the grub boot interface, and did not perform other operations on the yubikey during the system boot to run these commands.

![vm-grub](https://github.com/systemd/systemd/assets/113080189/fd905de8-d28c-4cd0-b7e9-56e90d949b69)


To use YubiKey in a vm, the following content was added to the vm's configuration file：
![linux-vmx](https://github.com/systemd/systemd/assets/113080189/693c0050-5246-4404-9ab9-1d651c91c4c5)

**Comment by tiberious726** [comment]
I'm experiencing this issue too. I tried to be clever and created a few UKIs without reference to fido2 in the kennel cmdline (I'm not using a initram cryptab) however, even without my token plugged in, I still get the "Please enter LUKS2 token PIN:" message! If I put something wrong in it, I then get the normal prompt asking for my password, which can unlock a device (I've never actually unlocked both this way, and it seems to be random as to which one gets unlocked, then it hangs on an earlier job).

Could it be that something has been added that triggers the fido2 module just from looking at the LUKS header? And thus causing the libfido locking issues suggested above? Would certainly be a nice feature when it works if so, no real reason this has to be on the kernel command line.

Furthermore, to add another datapoint, in my kernels with fido2 turned on, I can, unreliably, unlock my system: I put a wrong password in at the "LUKS token" prompt, and then get two "security token" prompts (strangely sometimes one is a second "LUKS token" prompt) which I can put my PIN into and touch my token, unlocking the system. I have not yet determined whether this works or hangs indefinitely not is correlated with the second prompt being "LUKS" or "security token"

With fido2 in the kennel cmdline it never falls back to password

**Comment by LDVG** [comment]
Hi all,

An update from the libfido2 side of things. We have been running a small test program[^1] that concurrently tries to

- call `fido_dev_open(3)` followed by `fido_dev_close(3)`; and
- in another thread, call `open(2)` followed by `close(2)`

on the same device path.
 
This causes `fido_dev_open(3)` to block indefinitely, waiting for a response to a command sent to the authenticator -- the same observation I made while looking at libfido2 debug output during cryptsetup. As far as we can tell, the authenticator itself _is_ responding, but the response never reaches the application. This suggests that opening multiple hidraw file descriptors concurrently perturbs the communication with the device.

Looking at the implementation of `hidraw_open()`[^2], the function acquires a read semaphore but, among other things, increments a shared counter (`dev->open`). This stands out to us as a potential race condition. If we modify the function to acquire the write semaphore instead, we can no longer get our test program to hang and cryptsetup works fine:

```diff
diff --git a/drivers/hid/hidraw.c b/drivers/hid/hidraw.c
index 197b1e7bf029..7aaa705d579d 100644
--- a/drivers/hid/hidraw.c
+++ b/drivers/hid/hidraw.c
@@ -272,7 +272,7 @@ static int hidraw_open(struct inode *inode, struct file *file)
 		goto out;
 	}

-	down_read(&minors_rwsem);
+	down_write(&minors_rwsem);
 	if (!hidraw_table[minor] || !hidraw_table[minor]->exist) {
 		err = -ENODEV;
 		goto out_unlock;
@@ -301,7 +301,7 @@ static int hidraw_open(struct inode *inode, struct file *file)
 	spin_unlock_irqrestore(&hidraw_table[minor]->list_lock, flags);
 	file->private_data = list;
 out_unlock:
-	up_read(&minors_rwsem);
+	up_write(&minors_rwsem);
 out:
 	if (err < 0)
 		kfree(list);
```

The read-write semaphore was introduced in commit torvalds/linux@8590222e4b021054a7167a4dd35b152a8ed7018e, and we believe with moderate confidence that it introduced this regression. While we can't yet definitively say the above is the proper fix it seems sensible. Any input is appreciated!

[^1]: https://gist.github.com/LDVG/1c847f279721594b84bcb63a88491da6
[^2]: https://github.com/torvalds/linux/blob/b6dad5178ceaf23f369c3711062ce1f2afc33644/drivers/hid/hidraw.c#L262

**Comment by poettering** [comment]
hey, @bentiss this looks like a kernel hidraw bug then, any chance you can have a look?

**Comment by bentiss** [comment]
> The read-write semaphore was introduced in commit https://github.com/torvalds/linux/commit/8590222e4b021054a7167a4dd35b152a8ed7018e, and we believe with moderate confidence that it introduced this regression. While we can't yet definitively say the above is the proper fix, it seems sensible. Any input is appreciated!

I think your analysis is correct. There is indeed a race condition introduced here, between `hidraw_release()` and `hidraw_open()`. However, there are several problems:
- `minors_rwsem` supposedly protects `hidraw_table` accesses and writes. It is not supposed to protect the content of the elements in the table, which makes the patch harder to justify
- `hid_hw_open()/close()` already has a ref count which is protected by a per device mutex. So hidraw having its own ref count is not great as both are not in sync
- hidraw is one of the few drivers who calls `hid_hw_power()` directly, which is only available in USB devices (not sure why they need this when it should be transparent IMO).
- fixing all of this logic is going to be hard and will require quite some tests...

So I would say that the patch is not "the" proper fix, but is OK given that the proper fix would consist in rethinking the whole hidraw code for little benefit.

I would still add a comment before the first `down_write(&minors_rwsem);` explaining that we technically don't protect a write on `hidraw_table`, but we need this to be a `down_write()` call to be symmetrical from `hidraw_release()`, as we are using our own refcount.

**Comment by foxiagouhe** [comment]
Hello everyone, I have upgraded the Linux kernel to the latest version(6.4.7-arch1-1) and tested unlocking with multiple devices using YubiKey. It was able to work successfully. Thank you all for your efforts!
