### ISSUE TITLE
Child cgroups do not inherit enabled cgroup.controllers

### ISSUE THREAD

**Issue by sjug** [systemd/systemd#27943]
### systemd version the issue has been seen with

253.5

### Used distribution

Arch Linux

### Linux kernel version used

6.3.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd, systemd-run

### Expected behaviour you didn't see

After enabling delegation for cgroup controllers for `user@1000.service`, I would expect the children to inherit the delegated cgroup controllers.

### Unexpected behaviour you saw

The child cgroups do not receive the delegated cgroup controllers, just the default of `cpu memory pids`

### Steps to reproduce the problem

1. Enable delegation for the user (id 1000) service:

**/etc/systemd/system/user@1000.service.d/delegate.conf**
```
[Service]
Delegate=cpuset cpu memory pids
```

Can just set `Delegate=true` to enable all controllers, but no functional difference is present.

2. Reboot(?) for the cgroup hierarchy to be updated.

3. Validate the cgroup controller delegation has been enabled for the desired cgroup:
```
# cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.controllers
cpuset cpu memory pids
```

4. Check any child cgroup to see if they have the same controllers delegated:
```
# cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/cgroup.controllers
cpu memory pids
# cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/cgroup.controllers
cpu memory pids
```

5. Create new user (unprivileged) cgroup to test controller delegation:
```
# pwd
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service
# mkdir test.slice
# cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test.slice/cgroup.controllers
cpu memory pids
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
I have also tried to use cpuset functionality for a service to define `cpuset.cpus` in a desired user cgroup in the hopes that if the functionality is requested in a systemd drop-in it will somehow assist in enabling the cpuset controller.

For example we can run:

# systemctl --user set-property test.slice AllowedCPUs=0-7
```

Which will create a drop-in file in the user directory:
```
# cat /home/user/.config/systemd/user.control/test.slice.d/50-AllowedCPUs.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Slice]
AllowedCPUs=0-7
```

Then we can test:
```
# systemd-run --user --slice=test.slice -t bash
Running as unit: run-u38.service
Press ^] three times within 1s to disconnect TTY.
#
```

We can check to see that the new `run-u38.service` cgroup is created under the `test.slice`:
```
$ find /sys/fs/cgroup/ -name run-u38.service -type d
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test.slice/run-u38.service
```

Then we can check what processor the `bash` process is running on. It is not limited to the `AllowedCPUs` specified because the slice that the new `run-u38.service` cgroup is created in does not have the `cpuset` controller enabled despite enabling delegation of this cgroup controller in the parent service.

I would appreciate assistance in getting the user cgroups to inherit the delegated cgroup controllers.

**Comment by poettering** [comment]
> 4\. Validate the cgroup controller delegation has been enabled for the desired cgroup:
> 
> 
> ```
> # cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.controllers
> cpuset cpu memory pids
> ```

This is not useful for validating delegation. You need to check `cgroup.subtree_control` instead.

`cgroup.controllers` shows what controllers have been enabled for the cgroup itself, it's read-only.

`cgroup.subtree_control` is what controls what to enable for the controllers, it's writable. It has no effect on the cgroup itself, only for the children of it.

**Comment by poettering** [comment]
anyway, if you wannt app.slice to have "cpuset" enabled, 

> 9\. 
> 
> 
> ```
> # pwd
> /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service
> # mkdir test.slice
> # cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/test.slice/cgroup.controllers
> cpu memory pids
> ```

Since nothing added "cpuset" to the subtree control file this will not be enabled.

Also, don't do direct change to the cgroup tree that systemd owns, it will just override all changes you made if you try. you void your warranty like that.

Anyway, closing, as this appears to be confusion around how delegation works.

**Comment by sjug** [comment]
> Since nothing added "cpuset" to the subtree control file this will not be enabled.

What is the correct way to add "cpuset" to the subtree control file for cgroup trees that systemd owns? 
If I use delegate on the slice drop in above, then it will work correctly.
```
# cat /home/user/.config/systemd/user.control/test.slice.d/50-AllowedCPUs.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Slice]
Delegate=cpuset
AllowedCPUs=0-7
```

However in the [old systemd doc on cgroup delegation](https://systemd.io/CGROUP_DELEGATION/), it says to not to set a `Delegate=` property on slices?

**Comment by poettering** [comment]
cgroup delegation is on for a unit, then almost all aspects of the cgroup itself remain under systemd's ownership. except:

1. you may create and remove subcrgoups
2. you may migrate processes from the cgroup into its children (or back)
3. you may turn on and turn off controllers for the child cgroups via the subtree_control attribute file

Or in other words, you will may have write access to cgroup.procs and cgroup.subtree_control as well as the cgroup inode itself, but none of the other attribute files

if you combine delegation with User= you'll see btw that exactly these three inodes are chowned over to.

**Comment by poettering** [comment]
or in other words: you may echo the controllers you want to enable for your subcgroups yourself by writing to subtree_control
