### ISSUE TITLE
user root directory could be configurable

### ISSUE THREAD

**Issue by Louson** [systemd/systemd#27959]
### Component

systemd

### Is your feature request related to a problem? Please describe

As described in sysusers.d/basic.conf.in, the root home directory is /root. Some distributions use /home/root (I have a distribution built on yocto)

Could this be defined in the build configuration ?

### Describe the solution you'd like

It's possible to replace the line:
`u root    0     "Super User" /root`

with
`u root    0     "Super User" {{ROOT_HOME_DIRECTORY}}`

and set ROOT_HOME_DIRECTORY as '/root' by default

### The systemd version you checked that didn't have the feature you are asking for

250.5-r0

**Comment by poettering** [comment]
Well, the root user is really the only user you shold be able to log into safely even if /home cannot be mounted. Which is a property that is a lot more important than the writability.

Anyway, note that te above is just about a fallback in case your /etc/passwd got lost. I am pretty sure that even if yocto wants to do its own thing, it can do so easily by just populating /etc/passwd the way it wants.

Anyway, closing this, as I am sure this is really not desirable.
