### ISSUE TITLE
Can't mask a service that is defined in /etc/systemd/system/vncserver-akik.service

### ISSUE THREAD

**Issue by aki-k** [systemd/systemd#27965]
### systemd version the issue has been seen with

251.14

### Used distribution

Fedora 37

### Linux kernel version used

6.3.4-101.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

vncserver-akik.service should've been masked

### Unexpected behaviour you saw

```
# systemctl mask vncserver-akik.service
Failed to mask unit: File /etc/systemd/system/vncserver-akik.service already exists.
```

### Steps to reproduce the problem

1) Create /etc/systemd/system/vncserver-akik.service with contents:
```
[Unit]
Description= Tiger VNC Server service
After=syslog.target network.target

[Service]
Type=forking
User=akik
ExecStart=/usr/bin/vncserver -geometry 1400x900 -depth 16 -localhost -once -reset -terminate :1
Restart=always

[Install]
WantedBy=multi-user.target
```
2) enable succeeds
```
# systemctl enable vncserver-akik.service
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver-akik.service → /etc/systemd/system/vncserver-akik.service.
```
3) mask fails
```
# systemctl mask vncserver-akik.service
Failed to mask unit: File /etc/systemd/system/vncserver-akik.service already exists.
```

**Comment by poettering** [comment]
Yeah, masking just places a /dev/null symlink in /etc/systemd/system/. This means if you defined the unit file itself there, it won't work.

This is probably something we should explicitly document.
