### ISSUE TITLE
shutdown from cron job results in segfault from systemd-logind

### ISSUE THREAD

**Issue by scwalla** [systemd/systemd#2796]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> … systemd 229-3

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> … Archlinux
### In case of bug report: Expected behaviour you didn't see

> … System should shutdown
### In case of bug report: Unexpected behaviour you saw

> … No shutdown.  Get segfault in logind
### In case of bug report: Steps to reproduce the problem

> … shutdown -P from cronjob.  Tried with both dcron and cronie

***\* journalctl output: ****

Mar 03 10:32:01 scwalla CROND[3586]: (root) CMD (shutdown -P)
Mar 03 10:32:01 scwalla kernel: systemd-logind[3433]: segfault at 0 ip 00007fdb6169bf3e sp 00007ffd1d99e148 error 4 in libc-2.23.so[7fdb6160e000+198000]
Mar 03 10:32:01 scwalla systemd[1]: Started Process Core Dump (PID 3587/UID 0).
Mar 03 10:32:01 scwalla systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=11/SEGV
Mar 03 10:32:01 scwalla systemd[1]: systemd-logind.service: Unit entered failed state.
Mar 03 10:32:01 scwalla systemd[1]: systemd-logind.service: Failed with result 'core-dump'.
Mar 03 10:32:01 scwalla systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
Mar 03 10:32:01 scwalla systemd[1]: Stopped Login Service.
Mar 03 10:32:01 scwalla systemd[1]: Starting Login Service...
Mar 03 10:32:01 scwalla systemd[1]: Started Login Service.
Mar 03 10:32:01 scwalla systemd-logind[3592]: New seat seat0.
Mar 03 10:32:01 scwalla systemd-logind[3592]: Watching system buttons on /dev/input/event1 (Power Button)
Mar 03 10:32:01 scwalla systemd-logind[3592]: Watching system buttons on /dev/input/event0 (Power Button)
Mar 03 10:32:01 scwalla systemd[1]: Started User Manager for UID 1000.
Mar 03 10:32:01 scwalla systemd-logind[3592]: New session c2 of user steve.
Mar 03 10:32:01 scwalla systemd-coredump[3588]: Process 3433 (systemd-logind) of user 0 dumped core.

```
                                            Stack trace of thread 3433:
                                            #0  0x00007fdb6169bf3e __strcmp_sse2_unaligned (libc.so.6)
                                            #1  0x000055e6290951e7 n/a (systemd-logind)
                                            #2  0x000055e6290c424a n/a (systemd-logind)
                                            #3  0x000055e629098659 n/a (systemd-logind)
                                            #4  0x000055e6290bfbcb n/a (systemd-logind)
                                            #5  0x000055e629078ee6 n/a (systemd-logind)
                                            #6  0x000055e6290ab93b n/a (systemd-logind)
                                            #7  0x000055e6290d4a51 n/a (systemd-logind)
                                            #8  0x000055e6290cdb03 n/a (systemd-logind)
                                            #9  0x000055e62907ba23 n/a (systemd-logind)
                                            #10 0x00007fdb6162e710 __libc_start_main (libc.so.6)
                                            #11 0x000055e62907c239 n/a (systemd-logind)
```

Mar 03 10:32:01 scwalla CROND[3585]: pam_unix(crond:session): session closed for user root

**Comment by neheb** [comment]
might wanna rebuild with debug symbols

**Comment by poettering** [comment]
The coredump is not useful without debug symbols. Any chance you can reproduce this with debug symbols?

**Comment by scwalla** [comment]
Here is a coredump with symbols this time.  Hopefully more useful.

---

Apr 17 20:03:56 scwalla systemd[1]: Starting Power off...
Apr 17 20:03:56 scwalla kernel: systemd-logind[1639]: segfault at 0 ip 00007fcdd7449f3e sp 00007fff06cb45e8 error 4 in libc-2.23.so[7fcdd73bc000+198000]
Apr 17 20:03:56 scwalla systemd[1]: Started Process Core Dump (PID 1656/UID 0).
Apr 17 20:03:56 scwalla systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=11/SEGV
Apr 17 20:03:56 scwalla sh[1654]: Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Message recipient disconnected from message bus without replying
Apr 17 20:03:56 scwalla systemd[1]: systemd-logind.service: Unit entered failed state.
Apr 17 20:03:56 scwalla systemd[1]: systemd-logind.service: Failed with result 'core-dump'.
Apr 17 20:03:56 scwalla systemd[1]: poweroff.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 20:03:56 scwalla systemd[1]: Failed to start Power off.
Apr 17 20:03:56 scwalla systemd[1]: poweroff.service: Unit entered failed state.
Apr 17 20:03:56 scwalla systemd[1]: poweroff.service: Failed with result 'exit-code'.
Apr 17 20:03:56 scwalla systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
Apr 17 20:03:56 scwalla systemd[1]: Stopped Login Service.
Apr 17 20:03:56 scwalla systemd[1]: Starting Login Service...
Apr 17 20:03:56 scwalla systemd[1]: Started Login Service.
Apr 17 20:03:56 scwalla systemd-logind[1661]: New seat seat0.
Apr 17 20:03:56 scwalla systemd-logind[1661]: Watching system buttons on /dev/input/event6 (Power Button)
Apr 17 20:03:56 scwalla systemd-logind[1661]: Watching system buttons on /dev/input/event5 (Power Button)
Apr 17 20:03:56 scwalla systemd[1]: Started User Manager for UID 1000.
Apr 17 20:03:56 scwalla systemd-logind[1661]: New session c2 of user steve.
Apr 17 20:03:56 scwalla systemd-coredump[1657]: Process 1639 (systemd-logind) of user 0 dumped core.

```
                                            Stack trace of thread 1639:
                                            #0  0x00007fcdd7449f3e __strcmp_sse2_unaligned (libc.so.6)
                                            #1  0x0000560fa26693e6 logind_wall_tty_filter (systemd-logind)
                                            #2  0x0000560fa269a84a utmp_wall.constprop.9 (systemd-logind)
                                            #3  0x0000560fa266c9b8 warn_wall.lto_priv.352 (systemd-logind)
                                            #4  0x0000560fa2695f2b manager_setup_wall_message_timer (systemd-logind)
                                            #5  0x0000560fa264bee8 method_callbacks_run (systemd-logind)
                                            #6  0x0000560fa2680fd0 bus_process_object (systemd-logind)
                                            #7  0x0000560fa26abe70 sd_bus_process (systemd-logind)
                                            #8  0x0000560fa26a4bf3 source_dispatch.lto_priv.380 (systemd-logind)
                                            #9  0x0000560fa264eb53 sd_event_dispatch (systemd-logind)
                                            #10 0x00007fcdd73dc710 __libc_start_main (libc.so.6)
                                            #11 0x0000560fa264f369 _start (systemd-logind)
```

**Comment by poettering** [comment]
@zonque i think you touched the code last, any idea?

**Comment by evverx** [comment]
I think this was fixed by b4944d2df248fbd2f9

**Comment by evverx** [comment]
- b4944d2~1

```
-bash-4.3# systemd-run bash -c 'exec -a shutdown systemctl -P'
Running as unit run-r1a4512b4506d42a38fb1f9479c0439c0.service

-bash-4.3# journalctl -b -u systemd-logind  | grep -i segv
Jun 20 05:44:29 systemd-testsuite systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=11/SEGV
```

```
(gdb) thread apply all bt

Thread 1 (Thread 0x7f36d2520900 (LWP 195)):
#0  0x00007f36d157ba14 in __strcmp_sse2 () from /lib64/libc.so.6
#1  0x000055b3a45a81fb in logind_wall_tty_filter (tty=0x55b3a5f3db70 "/dev/ttyS0", userdata=0x55b3a5f32010) at src/login/logind-utmp.c:71
#2  0x000055b3a4638a14 in utmp_wall (message=0x55b3a5f3d000 "The system is going down for poweroff at Mon 2016-06-20 05:45:27 UTC!", username=0x55b3a5f3d050 "root", origin_tty=0x0,
    match_tty=0x55b3a45a8177 <logind_wall_tty_filter>, userdata=0x55b3a5f32010) at src/shared/utmp-wtmp.c:437
#3  0x000055b3a45a83f2 in warn_wall (m=0x55b3a5f32010, n=1466401467293752) at src/login/logind-utmp.c:98
#4  0x000055b3a45a86e2 in manager_setup_wall_message_timer (m=0x55b3a5f32010) at src/login/logind-utmp.c:158
#5  0x000055b3a459f91f in method_schedule_shutdown (message=0x55b3a5f3c1a0, userdata=0x55b3a5f32010, error=0x7ffd0f3cb8d0) at src/login/logind-dbus.c:2006
#6  0x000055b3a45d3017 in method_callbacks_run (bus=0x55b3a5f34d80, m=0x55b3a5f3c1a0, c=0x55b3a5f38580, require_fallback=false, found_object=0x7ffd0f3cb9f3) at src/libsystemd/sd-bus/bus-objects.c:418
#7  0x000055b3a45d58a9 in object_find_and_run (bus=0x55b3a5f34d80, m=0x55b3a5f3c1a0, p=0x55b3a5f44748 "/org/freedesktop/login1", require_fallback=false, found_object=0x7ffd0f3cb9f3)
    at src/libsystemd/sd-bus/bus-objects.c:1255
#8  0x000055b3a45d5eeb in bus_process_object (bus=0x55b3a5f34d80, m=0x55b3a5f3c1a0) at src/libsystemd/sd-bus/bus-objects.c:1371
#9  0x000055b3a4647311 in process_message (bus=0x55b3a5f34d80, m=0x55b3a5f3c1a0) at src/libsystemd/sd-bus/sd-bus.c:2562
#10 0x000055b3a46474f4 in process_running (bus=0x55b3a5f34d80, hint_priority=false, priority=0, ret=0x0) at src/libsystemd/sd-bus/sd-bus.c:2604
#11 0x000055b3a4647daa in bus_process_internal (bus=0x55b3a5f34d80, hint_priority=false, priority=0, ret=0x0) at src/libsystemd/sd-bus/sd-bus.c:2793
#12 0x000055b3a4647e7b in sd_bus_process (bus=0x55b3a5f34d80, ret=0x0) at src/libsystemd/sd-bus/sd-bus.c:2812
#13 0x000055b3a4648aa2 in io_callback (s=0x55b3a5f3b4e0, fd=12, revents=1, userdata=0x55b3a5f34d80) at src/libsystemd/sd-bus/sd-bus.c:3082
#14 0x000055b3a465c2bb in source_dispatch (s=0x55b3a5f3b4e0) at src/libsystemd/sd-event/sd-event.c:2265
#15 0x000055b3a465d5a9 in sd_event_dispatch (e=0x55b3a5f33260) at src/libsystemd/sd-event/sd-event.c:2625
#16 0x000055b3a465d9e8 in sd_event_run (e=0x55b3a5f33260, timeout=18446744073709551615) at src/libsystemd/sd-event/sd-event.c:2684
#17 0x000055b3a45881df in manager_run (m=0x55b3a5f32010) at src/login/logind.c:1096
#18 0x000055b3a4588527 in main (argc=1, argv=0x7ffd0f3cbe58) at src/login/logind.c:1164
```
- b4944d2

```
-bash-4.3# systemd-run bash -c 'exec -a shutdown systemctl -P'
Running as unit run-r51c275e4aba145609e1161ceaf0edd09.service
-bash-4.3#
Broadcast message from root@systemd-testsuite (Mon 2016-06-20 05:52:35 UTC):

The system is going down for poweroff at Mon 2016-06-20 05:53:35 UTC!

Broadcast message from root@systemd-testsuite (Mon 2016-06-20 05:53:35 UTC):

The system is going down for poweroff NOW!
```

I think we can close this

**Comment by poettering** [comment]
indeed
