### ISSUE TITLE
TPM2 SRK setup should be done in a service of its own

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#27986]
So I think we should have a service of its own that sets up the TPM2 SRK. I think it#s OK if systemd-cryptsetup does this automatically if it's needed, but I think we should already do this ahead of time in a separate service.

Why? 

1. Speed. Key generation is slow. waiting for disks is slow. If we generate the SRK in systemd-cryptsetup we serialize this. if we have a separate service we can parallelize that.
2. more importantly: i think there are various other users of the SRK than just systemd-cryptsetup. Specifically I am thinking of the kernel keyring's "trusted" keys concept, i.e. https://www.kernel.org/doc/html/v5.4/security/keys/trusted-encrypted.html

hence, we should make the SRK setup code reusable, and then invoke it also from a new small service `systemd-srk-setup.service` or so.

**Comment by poettering** [comment]
@ddstreet do you think this makese sense?

**Comment by arianvp** [comment]
Such a service should maybe also give an option to clear the Owner Hierarchy completely?   Maybe this could run as part of the `-firstboot` stuff.

I also think clearing the Owner Hierarchy should be part of factory reset. I'm just curious if Systemd is the one that should be responsible for it. My gut feeling is yes.

**Comment by poettering** [comment]
> I also think clearing the Owner Hierarchy should be part of factory reset. When I re-intall my OS, I want all the TPM things to be cleared and make sure everything is in a clean slate. I'm just curious if Systemd is the one that should be responsible for it. My gut feeling is yes.

i guess this means you'd fuck up multi-boot scenarios, no?

so far we shied away from that, i.e. always tried to be cooperative and use what is already is there, never break what another tenant of the current system might have set up.

That said, a kernel cmdline option or so might make sense.

**Comment by arianvp** [comment]
Should not we simply call out to the tss FAPI for SRK provisioning? It already has a config file format for describing the SRK template etc:

https://man.archlinux.org/man/fapi-profile.5.en

**Comment by ddstreet** [comment]
> @ddstreet do you think this makese sense?

Sorry for the obviously extremely late reply...yes, I think it does make sense to do this, and I see you've got PR open already.
