### ISSUE TITLE
machinectl shell root@.host .. getting root without root password on default

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#2799]
Hello,
I have just realized that I can get root on my machine via machinectl without typing in my root password.
This is on default. It is maybe a good idea to disable this this on default. 
I am not sure if this is a bug or not but it's a big security problem on multi-user systems. I really think that  most of the users don't know this..
How can I disable this now? I want to use my root password for getting a root shell not my user password.

I am running systemd version:

```
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

EDIT: I have sudo installed, but i configured sudo that sudo asks for the root password not for the normal user password.. Why has systemd a different behaviour? This is a fresh installed Arch Linux system 64Bit.

**Comment by shibumi** [comment]
Seems like the reason of this problem is the default polkit configuration:

```
polkit.addAdminRule(function(action, subject) {
    return ["unix-group:wheel"];
});
```

My user is in the group `wheel` but I have configured sudo that it should ask for the root password..
It's not a systemd bug

**Comment by martinpitt** [comment]
FTR, systemd uses polkit, not sudo, so the sudo configuration does not matter at all. Indeed the `wheel` group is rather strange -- basically all members are equivalent to root without authentication with that (unlike sudo, which still asks for authenticating with the password).

**Comment by shibumi** [comment]
@martinpitt 
I have changed the default rule to this one now:

```
polkit.addAdminRule(function(action, subject) {
    return ["unix-user:root"];
});
```

this works. I will open a bug report for arch linux that they should fix their default polkit rule

**Comment by martinpitt** [comment]
Well, the problem is not that "wheel" has an admin role -- it's supposed to have that. The problem is that polkit does not ask for a password for this admin group in your case. We still run polkit 0.105, where setting `AdminIdentities=unix-group:sudo;unix-group:admin` does the right thing -- it asks for a password if you try to do an `Admin` thing as a member of this group. So indeed, please report this to Arch.

**Comment by Scimmia22** [comment]
Except it is asking the OP for a password. He's complaining that it's just the user's password instead of root's.

**Comment by martinpitt** [comment]
Ah sorry, I misread that. Yes, so that's not a bug at all, it's working as designed.

**Comment by shibumi** [comment]
@martinpitt Yes it's not a bug. Thats the reason why I have closed it already. The polkit rule is just to weak in my distribution.

**Comment by Scimmia22** [comment]
No, it's not. What you're seeing is intended behavior from upstream
