### ISSUE TITLE
Script for unloading Nouveau when shutdown or reboot performed

### ISSUE THREAD

**Issue by Alex-from-the-90s** [systemd/systemd#27995]
### Component

systemd

### Is your feature request related to a problem? Please describe

On my 2nd Linux (Simply Linux - Alt), I decided not to replace open Nouveau driver for my Nvidia graphics card with a proprietary one. In this regard, I faced the problem of not completing reboot and turning off the PC. As it was possible to establish, while Nouveau is loaded and used listed operations cannot be fully completed and this problem, according to reviews on the Internet, has been present for quite a long time. Adding certain kernel parameters related to Nouveau does not help everyone, while changing driver settings may negatively affect system performance. I assumed that if I use /lib/systemd/system-shutdown/ folder, just as I previously used /lib/systemd/system-sleep/ for problems with switching to sleep mode, and information from official website of driver, I can try to find more widely applicable fix. It happened, as a result of which new script appeared, which I'm going to offer as an improvement.

### Describe the solution you'd like

I suggest including **vtcon.shutdown** script with the following contents in **/lib/systemd/system-shutdown/** folder:

```
#!/bin/bash

# Deactivating KMS and unloading Nouveau for avoid uncompleted shutdown/reboot
# as described here: https://nouveau.freedesktop.org/KernelModeSetting.html
if [ -z "$(lsmod | grep 'nouveau')" ];
  then
  exit 0
else
  echo '0' > /sys/class/vtconsole/vtcon0/bind;
  rmmod nouveau;
  rmmod ttm;
  rmmod drm_kms_helper;
  rmmod drm;
  exit 0
fi

```

Script tested with KMS and nomodeset - reboot and shutdown work fine. It should not affect these processes in any way in systems with Intel and AMD graphics cards (can't test).

### Describe alternatives you've considered

As noted above, there are many alternatives, but they are individual (applicable to certain video cards and OS configurations).

### The systemd version you checked that didn't have the feature you are asking for

249

**Comment by mrc0mmand** [comment]
Sorry, but no. We definitely don't want to ship workarounds for broken proprietary drivers in systemd. If this works for you locally, then great, keep it there, but it has no place in the systemd tree. If anything, it should be shipped together with the proprietary driver if necessary.

**Comment by poettering** [comment]
Please contact the nouveau folks about this. Working around shutdown failures with such a script is certainly just that: a work-around, and those have no place in systemd. I am pretty sure the nouveau people consider inability to shut down properly a bug too, and are interested to get this fixed.
