### ISSUE TITLE
systemd.exec with InaccessiblePaths=/run fails within latest systemd versions

### ISSUE THREAD

**Issue by taoky** [systemd/systemd#27997]
### systemd version the issue has been seen with

systemd 253.5-1

### Used distribution

Arch Linux

### Linux kernel version used

6.3.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-run

### Expected behaviour you didn't see

Services start successfully with InaccessiblePaths=/run

### Unexpected behaviour you saw

Service fails with exit code 226 (NAMESPACE).

```
> sudo systemd-run -P -pInaccessiblePaths=/run ls                                                                          
Running as unit: run-u6214.service
> sudo systemctl status run-u6214.service                                                                            
× run-u6214.service - /usr/bin/ls
     Loaded: loaded (/run/systemd/transient/run-u6214.service; transient)
  Transient: yes
     Active: failed (Result: exit-code) since Sun 2023-06-11 19:24:53 CST; 4s ago
   Duration: 6ms
    Process: 1209107 ExecStart=/usr/bin/ls (code=exited, status=226/NAMESPACE)
   Main PID: 1209107 (code=exited, status=226/NAMESPACE)
        CPU: 7ms

Jun 11 19:24:53 hostname systemd[1]: Started /usr/bin/ls.
Jun 11 19:24:53 hostname systemd[1]: run-u6214.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 11 19:24:53 hostname systemd[1]: run-u6214.service: Failed with result 'exit-code'.
```

### Steps to reproduce the problem

1. Add `InaccessiblePaths=/run` to a service for testing, or just `systemd-run` with this.
2. Service cannot be started no matter what `ExecStart` it has.

This issue also exists in Debian 12 systemd (252.6-1), but not in Debian 11 (247.3-7+deb11u2).

**Comment by taoky** [comment]
Supplementary info: 

the `dmesg` shows following msg:

```
[931414.598063] (ls)[1209107]: Failed to remount /run/systemd/incoming with MS_SLAVE: Operation not permitted
[931414.598110] (ls)[1209107]: run-u6214.service: Failed to set up mount namespacing: Operation not permitted
[931414.598145] (ls)[1209107]: run-u6214.service: Failed at step NAMESPACE spawning /usr/bin/ls: Operation not permitted
```

And in my environment, Debian 12 kernel = `6.1.0-9-cloud-amd64`, Debian 11 kernel = `6.0.0-0.deb11.6-amd64`

**Comment by bluca** [comment]
Why are you setting ` InaccessiblePaths=/run`?

**Comment by taoky** [comment]
> Why are you setting ` InaccessiblePaths=/run`?

It's from a systemd service written by hand by another admin which no longer works after a upgrade to Debian bookworm, and that service is a simple Golang HTTP server and it does not require `/run` to execute.

If this is expected behavior it is fine to close this issue, but I'm still very curious how to set a service not to read/write system's `/run` when necessary. I have read `systemd.exec(5)` but did not find a clue.

**Comment by bluca** [comment]
Use `TemporaryFileSystem=/run`. A writable /run is pretty much a requirement for most of userspace these days.

**Comment by taoky** [comment]
It works, thanks!

Is it necessary to mention this in systemd's documentation though?
