### ISSUE TITLE
symlink by-partuuid will be automatically deleted if ambivalent result (more FS) 

### ISSUE THREAD

**Issue by huangwenhua** [systemd/systemd#28004]
### systemd version the issue has been seen with

253

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

if if ambivalent result (more FS) on sdb1, the symlink(/dev/disk/by-partuuid/aa29c77b-01 -> ../../sdb1) will be automatically deleted

### Steps to reproduce the problem

[root@node util-linux]# wipefs /dev/sdb1
DEVICE OFFSET TYPE             UUID LABEL
sdc1   0x0    ceph_bluestore        
sdc1   0x200  xfs_external_log

**Comment by poettering** [comment]
i am not sure i grok what this issue is about?

is this a complaint that we do not create symlinks for devices with ambiguous disk labels? or is it a complain about the opposite, i.e. that we don't do so?

**Comment by huangwenhua** [comment]
[ambivalent.csv](https://github.com/systemd/systemd/files/11720801/ambivalent.csv)

`[root@work tmp]# hexdump -C ambivalent.csv 
00000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
00000010  64 65 76 69 63 65 0a 33  34 36 66 61 65 37 31 2d  |device.346fae71-|
00000020  35 33 65 66 2d 34 37 31  39 2d 62 37 36 37 2d 64  |53ef-4719-b767-d|
00000030  65 36 65 34 37 65 36 31  61 33 36 0a 02 01 2d 00  |e6e47e61a36...-.|
00000040  00 00 34 6f ae 71 53 ef  47 19 b7 67 de 6e 47 e6  |..4o.qS.G..g.nG.|
00000050  1a 36 00 00 00 c0 26 00  00 00 94 5d 75 64 97 34  |.6....&....]ud.4|
00000060  e1 2a 05 00 00 00 63 61  63 68 65 00 00 00 00 d2  |.*....cache.....|
00000070  29 19 17 00 00 00 00 00  00 00 00 00 00 00 00 00  |)...............|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000200  fe ed ba be 00 00 00 01  00 00 00 02 00 00 02 00  |................|
00000210  00 00 00 01 00 00 00 00  00 00 00 01 00 00 00 00  |................|
00000220  00 00 00 00 ff ff ff ff  00 00 00 01 b0 c0 d0 d0  |................|
00000230  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000320  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 01  |................|
00000330  36 e3 20 de 91 71 4d a8  b2 31 ca 20 cc bb 6b a3  |6. ..qM..1. ..k.|
00000340  00 00 80 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000350  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400
[root@work tmp]# 
`

dd if=ambivalent.csv of=/dev/sdb1
then the symlinks (/dev/disk/by-partuuid/xx ->sdb1) will be automatically deleted，This is not what we want to see

**Comment by huangwenhua** [comment]
(sdb1,sdc1,...sdx1)             iscsi
      ceph pool               ----------- >   client ( mkfs.xfs -l logdev)

For this case,  the disks in ceph pool may have two disk labels (ceph_bluestore and xfs_external_log)，because xfs logdev superblock may not in the start of the disk.  So I think It is reasonable that  having am ambiguous superblock.

**Comment by poettering** [comment]
that sounds wrong, because then something might automatically make use of the xfs device ignoring the ceph thing and things just go bad.

**Comment by huangwenhua** [comment]
we added sdb1,sdc1,...sdx1 to a Ceph pool, created a volume from the Ceph pool, and then the client  mkfs.xfs -l logdev used the volume.  There was no Ceph thing in the volume, Ceph managed the disks.
