### ISSUE TITLE
QEMU with Hyper-V enlightenments incorrectly identified as Hyper-V

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#28001]
### systemd version the issue has been seen with

systemd 253.4+suse.28.g25aec15788

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.3.6-1-default

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

The VM is running on top of QEMU+KVM and `systemd-detect-virt` should identify this as KVM.

### Unexpected behaviour you saw

```
# SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Virtualization QEMU found in DMI (/sys/class/dmi/id/sys_vendor)
UML virtualization not found in /proc/cpuinfo.
Virtualization found, CPUID=Microsoft Hv
Found VM virtualization microsoft
microsoft
```

### Steps to reproduce the problem

Start QEMU with any Hyper-V enlightenment enabled. This causes QEMU to use `Microsoft Hv` as vendor in CPUID:

`qemu-system-x86_64 -enable-kvm -cpu host,hv_relaxed ...`

This is the documented behaviour: https://www.qemu.org/docs/master/system/i386/hyperv.html

> When any set of the Hyper-V enlightenments is enabled, QEMU changes hypervisor identification (CPUID 0x40000000..0x4000000A) to Hyper-V. KVM identification and features are kept in leaves 0x40000100..0x40000101.

The systemd virtualization detection code implies that QEMU would use `Linux KVM Hv`, but this is not/no longer the case: https://github.com/systemd/systemd/blob/d30d9bf0acbd8dce97299b7485691f6309810da6/src/basic/virt.c#L43

**Comment by septatrix** [comment]
> The systemd virtualization detection code implies that QEMU would use `Linux KVM Hv`, but this is not/no longer the case:

This seems to have been that way in QEMU since basically forever (https://github.com/qemu/qemu/commit/eab70139a6772f1735444d4f1daadc7bcfa7dc47, 12y ago) unless it was broken at some point. What I find puzzling is that detect-virt correctly states that QEMU has been found but does not return it directly (or at least rule out Hyper-V for future checks). It would be great to know how Hyper-V actually poses towards the system
