### ISSUE TITLE
networkd v253: Waiting for IPv6 addresses to become ready before using them as source in static routes seems broken

### ISSUE THREAD

**Issue by rnurgaliyev** [systemd/systemd#28009]
### systemd version the issue has been seen with

253

### Used distribution

Debian 11

### Linux kernel version used

6.1.27

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Sometimes when a static route has `PreferredSource` set, systemd-networkd doesn't wait for the address to be active before trying to create route. Let's say we have this network file:
```
[Match]
Name=vlan123

[Address]
Address=2001:db8::1000:123/64

[Route]
Gateway=2001:db8::1000:1
PreferredSource=2001:db8::1000:123

[Link]
MTUBytes=1600
```
I would expect systemd-networkd to create a default static route, with 2001:db8::1000:123 as the source.

### Unexpected behaviour you saw

When I create such network file and run `networkctl reload`, sometimes it would fail because of race in systemd-networkd. Debug output looks like this:
```
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: link_check_ready(): static addresses are not configured.
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: Addresses set
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: link_check_ready(): address 2001:db8::1000:123/64 is not ready.
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: Could not set route: Invalid source address. Invalid argument
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: Failed
Jun 12 14:14:37 labhost systemd-networkd[217440]: vlan123: State changed: configuring -> failed
...
Jun 12 14:14:39 labhost systemd-networkd[217440]: vlan123: Received updated static address (configured): 2001:db8::1000:123/64 (valid forever, preferred forever), flags: permanent, scope: global
```
As seen in this log, 2001:db8::1000:123/64 was only configured 2 seconds after an attempt to create static route, which failed. I believe that similar issue was fixed in https://github.com/systemd/systemd/issues/5882, but it seems that we get this or similar behaviour again.

### Steps to reproduce the problem

This shell script reveals the race in ~10 cycles.

```
#!/bin/sh

while : ; do
  ip -4 addr flush dev vlan123
  ip -6 addr flush dev vlan123
  ip -6 ro flush proto static
  
  rm -fr /etc/systemd/network
  cp -dpR ./original /etc/systemd/network

  systemctl restart systemd-networkd
  
  sleep 10

  rm -fr /etc/systemd/network
  cp -dpR ./updated /etc/systemd/network

  networkctl reload

  sleep 5

  ip -6 ro sh default | grep '2001:db8::1000:1' || break
done
```

`./updated` has the new .network file in it. If I change `networkctl reload` here with `systemctl restart systemd-networkd` then it seems that I cannot reproduce this issue.

**Comment by rnurgaliyev** [comment]
I've added a check to `route_is_ready_to_configure()`, which blocks configuration of any static routes with preferred source if not all of static address messages are processed on the link, and it seems to fix the race. Will prepare a PR.

**Comment by rnurgaliyev** [comment]
Full debug log: https://gist.github.com/rnurgaliyev/83c025b53893ab0c711863d5ddc099db

**Comment by yuwata** [comment]
Reopening, as the fix will be reverted.
