### ISSUE TITLE
test-execute fails on beaglebone_black

### ISSUE THREAD

**Issue by Sangeetha-E** [systemd/systemd#28015]
Hi,

The **test-execute** fails on beaglebone_black.

Here I have attached the error log.
[test-execute-logs.txt](https://github.com/systemd/systemd/files/11731125/test-execute-logs.txt)

I used **buildroot** build system but it is not distro specific.

Kindly give me suggestions to fix this failure.

systemd: 253

Thank you.

**Comment by bluca** [comment]
```
Successfully forked off '(spawn-ldd)' as PID 293.
Assertion 's' failed at src/basic/strv.c:230, function strv_split_newlines_full(). Aborting.
```

do you have a working `ldd`?

**Comment by Sangeetha-E** [comment]
Thank you for your response. After installing the ldd, the above mentioned issue got resolved.
But now I am facing the below issue.

```
exec-readonlypaths.service: Child 375 belongs to exec-readonlypaths.service.
exec-readonlypaths.service: Main process exited, code=exited, status=1/FAILURE
exec-readonlypaths.service: Failed with result 'exit-code'.
exec-readonlypaths.service: Service will not restart (restart setting)
exec-readonlypaths.service: Changed start -> failed
exec-readonlypaths.service: Unit entered failed state.
        PID: 375
        Start Timestamp: Tue 2022-12-20 18:17:52 UTC
        Exit Timestamp: Tue 2022-12-20 18:17:52 UTC
        Exit Code: exited
        Exit Status: 1
src/test/test-execute.c:474:test_exec_readonlypaths: exec-readonlypaths.service: can_unshare=yes: exit status 1, expected 0
Aborted
```

**Comment by yuwata** [comment]
The test service contains multiple `test` commands.
Please try to comment out some of them, and find which commands fail.

**Comment by Sangeetha-E** [comment]
I have verified that the following directories have been assigned the appropriate permissions:

```
chmod -R 555 /usr
chmod -R 555 /etc
chmod -R 555 /sys
chmod -R 555 /sys/fs/cgroup
chmod -R 555 /dev
chmod -R 555 /dev/shm
touch /i-dont-exist
chmod 555 /i-dont-exist
chmod 755 /var
```
Ref: https://github.com/systemd/systemd/blob/v253/test/test-execute/exec-readonlypaths.service

**Comment by yuwata** [comment]
What? Did you create `/i-dont-exist` before running the test?

**Comment by Sangeetha-E** [comment]
I ran the test both before and after creating this file, but the issue remains unresolved.

**Comment by yuwata** [comment]
The test assume that the file `/i-dont-exist` does not exist. Please do not create it.

Anyway, please find which `test` command fails.

**Comment by Sangeetha-E** [comment]
Thank you for your response, I will check.

**Comment by wileyhy** [comment]
Should those '&&'s maybe be '||'s?

**Comment by wileyhy** [comment]
...or is the `&& test -w /var` missing an exclamation point? 
    -- "The bashful never learn, and the sort tempered cannot teach."  - Avot

**Comment by wileyhy** [comment]
/me googles "build system"
I'm sorry for adding extra noise, and thanks for that tip.

**Comment by Sangeetha-E** [comment]
As per your suggestions, I manually executed the commands and obtained the following results:

```
# /bin/sh -x -c 'test ! -w /usr && test ! -w /etc && test ! -w /sys && test ! -w /sys/fs/cgroup'
+ test '!' -w /usr
# echo $?
1
#
```

https://github.com/systemd/systemd/blob/main/test/test-execute/exec-readonlypaths.service

I need some clarifications regarding the purpose of this test service. By default, the root user typically possesses write permissions for directories like /usr, /etc, and others. 
Could you kindly explain the functionality of this test service?

**Comment by mrc0mmand** [comment]
The test service has `ReadOnlyPaths=` set for those paths which creates a new namespace where the paths are read-only for that specific service.

**Comment by Sangeetha-E** [comment]
To ensure the successful execution of this test, it is essential to consider any kernel configurations, required any additional packages?

**Comment by mrc0mmand** [comment]
I don't think so, but you can check each directive separately, i.e.:

```
# systemd-run --wait --pipe -pReadOnlyPaths=/tmp touch /tmp/foo
Running as unit: run-u16.service
/usr/bin/touch: cannot touch '/tmp/foo': Read-only file system
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
Service runtime: 4ms
CPU time consumed: 4ms
```

```
# systemd-run --wait --pipe -pPrivateDevices=yes touch /dev/foo
Running as unit: run-u17.service
/usr/bin/touch: cannot touch '/dev/foo': Read-only file system
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
Service runtime: 6ms
CPU time consumed: 6ms
```

It should complain about read-only fs in both cases.
```

**Comment by mrc0mmand** [comment]
Closing, given the lack of response. If there's still an issue, please feel free to reopen and provide requested logs.

**Comment by Sangeetha-E** [comment]
Apologies for the delayed response. The previously mentioned issue has been resolved. It was caused by `busybox sh`, and switching to `bash` resolved the problem.

Now, I am encountering another issue. Here is the error log. I would appreciate any suggestions regarding this matter.

Error logs:
```
exec-ambientcapabilities.service: Will spawn child (service_enter_start): sh
exec-ambientcapabilities.service: Passing 0 fds to service
exec-ambientcapabilities.service: About to execute sh -x -c "c=\$\$(grep \"CapAmb:\" /proc/self/status); test \"\$\$c\" = \"CapAmb:\t0000000000002001\""
exec-ambientcapabilities.service: Forked sh as 1112
exec-ambientcapabilities.service: Changed dead -> start
exec-ambientcapabilities.service
    UMask: 0022
    WorkingDirectory: /root
    RootDirectory: /
    NonBlocking: no
    PrivateTmp: no
    PrivateDevices: no
    ProtectKernelTunables: no
    ProtectKernelModules: no
    ProtectKernelLogs: no
    ProtectClock: no
    ProtectControlGroups: no
    PrivateNetwork: no
    PrivateUsers: no
    ProtectHome: no
    ProtectSystem: no
    MountAPIVFS: no
    IgnoreSIGPIPE: yes
    MemoryDenyWriteExecute: no
    RestrictRealtime: no
    RestrictSUIDSGID: no
    KeyringMode: inherit
    ProtectHostname: no
    ProtectProc: default
    ProcSubset: all
    RuntimeDirectoryPreserve: no
    RuntimeDirectoryMode: 0755
    StateDirectoryMode: 0755
    CacheDirectoryMode: 0755
    LogsDirectoryMode: 0755
    ConfigurationDirectoryMode: 0755
    TimeoutCleanSec: infinity
    StandardInput: null
    StandardOutput: null
    StandardError: inherit
    AmbientCapabilities: cap_chown cap_net_raw
    User: daemon
    DynamicUser: no
    LockPersonality: no
exec-ambientcapabilities.service: User lookup succeeded: uid=102 gid=102
exec-ambientcapabilities.service: Control group is empty.
Received SIGCHLD from PID 1112 (sh).
Child 1112 (sh) died (code=exited, status=1/FAILURE)
exec-ambientcapabilities.service: Child 1112 belongs to exec-ambientcapabilities.service.
exec-ambientcapabilities.service: Main process exited, code=exited, status=1/FAILURE
exec-ambientcapabilities.service: Failed with result 'exit-code'.
exec-ambientcapabilities.service: Service will not restart (restart setting)
exec-ambientcapabilities.service: Changed start -> failed
exec-ambientcapabilities.service: Unit entered failed state.
    PID: 1112
    Start Timestamp: Wed 2024-02-07 19:39:33
    Exit Timestamp: Wed 2024-02-07 19:39:33
    Exit Code: exited
    Exit Status: 1
src/test/test-execute.c:1023:test_exec_ambientcapabilities: exec-ambientcapabilities.service: can_unshare=yes: exit status 1, expected 0
Aborted (core dumped)

```
