### ISSUE TITLE
notify-reload change causes regression when dbus service restarts

### ISSUE THREAD

**Issue by ChenQi1989** [systemd/systemd#28016]
### systemd version the issue has been seen with

253 & main

### Used distribution

Yocto

### Linux kernel version used

6.1.29

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

No timeout failure and org.freedesktop.login1 could be actived.

### Unexpected behaviour you saw

root@qemux86-64:~# systemctl status -l --no-pager dbus
* dbus.service - D-Bus System Message Bus
     Loaded: loaded (/lib/systemd/system/dbus.service; static)
     Active: active (running) since Tue 2023-06-13 06:16:09 UTC; 1min 53s ago
TriggeredBy: * dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 508 (dbus-daemon)
      Tasks: 1 (limit: 4714)
     Memory: 496.0K
     CGroup: /system.slice/dbus.service
             `-508 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

Jun 13 06:16:09 qemux86-64 systemd[1]: Starting D-Bus System Message Bus...
Jun 13 06:16:09 qemux86-64 systemd[1]: Started D-Bus System Message Bus.
Jun 13 06:16:10 qemux86-64 dbus-daemon[508]: [system] Activating via systemd: service name='org.freedesktop.login1' unit='dbus-org.freedesktop.login1.service' requested by ':1.1' (uid=0 pid=512 comm="sshd: root [priv]")
Jun 13 06:16:35 qemux86-64 dbus-daemon[508]: [system] Failed to activate service 'org.freedesktop.login1': timed out (service_start_timeout=25000ms)

### Steps to reproduce the problem

systemctl restart dbus && ssh root@localhost
systemctl status dbus

The ssh localhost command takes a long time and we can see timeout messages in the output of 'systemctl status dbus'.

In fact, system is not in correct status after 'systemctl restart dbus'. When I run 'shutdown -h now', I will get the following error.
Failed to set wall message, ignoring: Connection timed out

**Comment by ChenQi1989** [comment]
I've tracked this issue down to the change of notify-reload. 
If I remove Type=notify-reload from systemd-logind.service, there'll be no such issue.

**Comment by ChenQi1989** [comment]
This issue is generic to all 'notify-reload' type services that connect to dbus.
Workaround: systemctl restart <that_service>

**Comment by ChenQi1989** [comment]
@poettering Just in case you didn't notice this issue.
If you could provide some suggestion how to look into this problem, that would be great.

**Comment by poettering** [comment]
restarting dbus during runtime is simply not supported on today's systems, as a lot of programs lose state then.

**Comment by ChenQi1989** [comment]
@poettering Thanks for the reply. This make things very clear. I'll close this issue.
