### ISSUE TITLE
IOAccounting= vs DefaultBlockIOAccounting= deprecation complete?

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#28045]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

linux-image-6.1.0-9-amd64 version 6.1.27-1

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

`systemd-system.conf(5)` documents the `DefaultIOAccounting=` directive. In the `HISTORY` section it notes that `DefaultBlockIOAccounting=` is deprecated.

```
$ systemctl show | grep 'Default.*Accounting'
DefaultCPUAccounting=yes
DefaultBlockIOAccounting=yes
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes
```

The value of `DefaultIOAccounting=` is not printed.

### Unexpected behaviour you saw

The value of `DefaultBlockIOAccounting=` is printed instead.

I don't know if this is because the deprecation/renaming process isn't finished yet or if this is just an oversight.

(I also noticed that `systemd-system.conf(5)` also documents `DefaultIPAccounting=` which is missing from `systemctl show`. And there's a minor

**Comment by Geass-LL** [comment]
DefaultIOAccounting and DefaultIPAccounting are missing, I think we should add them when `systemctl show`.

Although DefaultBlockIOAccounting is deprecated, maybe some users are still using them, so I think it should still be kept in `systemctl show`.
