### ISSUE TITLE
systemd-resolved: manually dhclient ethx，dns nameserver  in the /etc/resolve.conf  will be written duplicate

### ISSUE THREAD

**Issue by LXYD001** [systemd/systemd#28055]
### systemd version the issue has been seen with

249

### Used distribution

ubuntu22

### Linux kernel version used

5.15.0-72-generic

### CPU architectures issue was seen on

None

### Component

systemd-resolved

### Unexpected behaviour you saw

![20230616-143226](https://github.com/systemd/systemd/assets/37770037/fc2d4eea-4897-4d57-910f-dee53adb1205)
![20230616-143234](https://github.com/systemd/systemd/assets/37770037/5b044591-d980-4ba6-a3c0-05c635fabd5e)
not this problem when I was on ubuntu20. The version of systemd is 245

this problem when I was on ubuntu22. The systemd version is 249

I compared the codes and suspected that v248  commit  cbf23f385381f1df2149b18d1fa2411356d76ad8
caused by

I saw this issuse about netplan on ubuntu  
https://superuser.com/questions/1721017/remove-redundant-dns-servers-in-ubuntu-22-04

But it doesn't work for dhclient (why I use dhclient, because I found it out of curiosity)

### Steps to reproduce the problem

1: Start a virtual machine on the cloud
2: Insert multiple network cards (auxiliary network card)
3: Manually use dhclient to start ethx (except eth0)   dhclient -v -d eth1
4: View /etc/resolve.conf

**Comment by poettering** [comment]
please rais this with your distro, not upstream systemd. it's a dhclient packaging matter.
