### ISSUE TITLE
bootctl install/update fails with exit code 1 for some ESP mounts

### ISSUE THREAD

**Issue by Majiir** [systemd/systemd#28068]
### systemd version the issue has been seen with

253.3

### Used distribution

NixOS 23.05

### Linux kernel version used

6.1.31

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl install` should either succeed or print an error message.

### Unexpected behaviour you saw

`bootctl install` returns exit code 1 and prints no output.

### Steps to reproduce the problem

1. Mount a ZFS filesystem at `/boot`
2. Mount the ESP at `/boot/efi`
3. `bootctl install` or `bootctl update`

I found that when `/` is a ZFS filesystem and `/boot` is just a directory in it, `bootctl install` works fine. See https://github.com/NixOS/nixpkgs/issues/223579#issuecomment-1592401234 and subsequent comments for details, including BTRFS users experiencing a similar problem.

I bisected systemd and found that the issue began at https://github.com/systemd/systemd-stable/commit/bd80fd7e5621f1b07e789725d9f8813c37e8571c.

**Comment by poettering** [comment]
Already fixed: f26c794308975a875a98faf22a6650d7134f17c1
