### ISSUE TITLE
systemd-inhibit doesn't prevent a laptop from sleeping when lid is closed

### ISSUE THREAD

**Issue by abacabadabacaba** [systemd/systemd#28067]
### systemd version the issue has been seen with

252.11-1

### Used distribution

Debian GNU/Linux trixie/sid

### Linux kernel version used

6.1.0-9-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

Running `systemd-inhibit sleep 1000000000` should prevent a laptop from going to sleep when lid is closed.

### Unexpected behaviour you saw

Despite the above command running, the laptop still goes to sleep when lid is closed. I tried to run it as as a regular user as well as as root, the result is the same.

Adding `HandleLidSwitch=ignore` to `/etc/systemd/logind.conf` does prevent the laptop from sleeping when lid is closed, so I know that it is systemd-logind that is responsible for the above behavior.

### Steps to reproduce the problem

* Make sure that systemd-logind is using default configuration,
* Run `systemd-inhibit sleep 1000000000`,
* Close the lid.
* Now the laptop goes to sleep.

**Comment by poettering** [comment]
See LidSwitchIgnoreInhibited= switch in logind.conf(5)
