### ISSUE TITLE
Environment variable set via --setenv option is not set for process launched with systemd-run

### ISSUE THREAD

**Issue by alexbrand** [systemd/systemd#2806]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 219
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS Linux release 7.2.1511 (Core)
### In case of bug report: Expected behaviour you didn't see

> Environment variable passed via --setenv to systemd-run was not available from the launched process.
### In case of bug report: Steps to reproduce the problem

```
# systemd-run -t --setenv=TEST=Success echo TEST:$TEST
Running as unit run-20711.service.
Press ^] three times within 1s to disconnect TTY.
TEST:

```

**Comment by ronnychevalier** [comment]
No it works fine, the `$TEST` in your example is evaluated by your shell, since no `TEST` variable has been set it prints an empty value.

Try this, and you will see that it prints `Success` as expected.

`systemd-run -t --setenv=TEST=Success bash -c 'echo TEST:$TEST'`
