### ISSUE TITLE
Wrong naming in hwdb for Focusrite Scarlett 2i2 3rd gen (including patch)

### ISSUE THREAD

**Issue by j-sax** [systemd/systemd#28072]
### systemd version the issue has been seen with

252 and git main (18th june 2023)

### Used distribution

Gentoo

### Linux kernel version used

6.1.31-gentoo-jsax-r1

### CPU architectures issue was seen on

x86_64

### Component

hardware database files

### Expected behaviour you didn't see

I have bought a Focusrite Scarlett 2i2 3rd Gen device which is an usb dac/soundcard.
This device should be named something like:
Focusrite-Novation Scarlett 2i2 3rd Gen
when using lsub, like similar devices also show up.

### Unexpected behaviour you saw

The device listed with lsusb is:
ID 1235:8210 Focusrite-Novation Scarlett 2i2 Camera
This device is NOT a camera.

I tracked this down to the entry in:
hwdb.d/20-usb-vendor-model.hwdb

I have added a patch in "Additional program output..." made against main today. I applied it to the 252 version in my gentoo and now lsusb give a correct output.

Note the naming scheme is not really consequent in that file, so I just used the mostly used naming scheme for recent Scarlett devices.

### Steps to reproduce the problem

Plug such a device and do lsusb.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
diff --git a/hwdb.d/20-usb-vendor-model.hwdb b/hwdb.d/20-usb-vendor-model.hwdb
index c2fbbc9a47..b640ec5dcf 100644
--- a/hwdb.d/20-usb-vendor-model.hwdb
+++ b/hwdb.d/20-usb-vendor-model.hwdb
@@ -50862,7 +50862,7 @@ usb:v1235p8204*
  ID_MODEL_FROM_DATABASE=Scarlett 18i8 2nd Gen
 
 usb:v1235p8210*
- ID_MODEL_FROM_DATABASE=Scarlett 2i2 Camera
+ ID_MODEL_FROM_DATABASE=Scarlett 2i2 3rd Gen
 
 usb:v1235p8211*
  ID_MODEL_FROM_DATABASE=Scarlett Solo (3rd Gen.)
```

**Comment by poettering** [comment]
We import the usb vendor/product database wholesale from here:

http://www.linux-usb.org/usb-ids.html

Please submit corrections/additions there, it will then be imported into our tree on the next release. Thank you!
