### ISSUE TITLE
local DNSSEC validation

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#28086]
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

feature request:
systemd-resolved should perform local DNSSEC validation.

When DNSSEC=true, does systemd-resolved perform local DNSSEC validation or is systemd-resolved only DNSSEC aware and doesn't perform local DNSSEC validation?

In other words, is  systemd-resolved a validating or non-validating DNSSEC resolver?

This is not a given. Other DNS resolver with DNSSEC capability are at time of writing only DNSSEC aware but not performing local DNSSEC validation.

* https://github.com/DNSCrypt/dnscrypt-proxy/discussions/1954
* https://github.com/cloudflare/cloudflared/issues/520

### Describe the solution you'd like

* Clarify in documentation if systemd-resolved is only DNSSEC aware of DNSSEC validating. And/or
* Implement local DNSSEC validation if not already implemented.

**Comment by poettering** [comment]
See man page, it's literally in the second sentence of the systemd-resolved man page.

Also see DNSSEC= option in resolved.conf.

That said, turning this on is problematic, since consumre DNS servers are so bad this seldom just works
