### ISSUE TITLE
systemd-resolved gives SERVFAIL rather than NXDOMAIN for invalid reverse lookups

### ISSUE THREAD

**Issue by Keno** [systemd/systemd#28085]
### systemd version the issue has been seen with

245.4-4ubuntu3.20

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.0-121-generic

### CPU architectures issue was seen on

None

### Component

systemd-resolved

### Expected behaviour you didn't see

When querying an invalid reverse-record, I would expect to see an empty NXDOMAIN reply. E.g. here is the behavior of `8.8.8.8` and `1.1.1.1`:
```
$ dig @8.8.8.8 -x 0
; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 -x 0
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39106
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;0.in-addr.arpa.			IN	PTR

;; AUTHORITY SECTION:
in-addr.arpa.		1342	IN	SOA	b.in-addr-servers.arpa. nstld.iana.org. 2022091512 1800 900 604800 3600

;; Query time: 11 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Jun 19 21:40:33 UTC 2023
;; MSG SIZE  rcvd: 111
```

```
; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 -x 0
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39716
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;0.in-addr.arpa.			IN	PTR

;; Query time: 3 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Jun 19 21:40:59 UTC 2023
;; MSG SIZE  rcvd: 43
```

### Unexpected behaviour you saw

systemd-resolve instead returns SERVFAIL for these queries:
```
$ dig -x 0

; <<>> DiG 9.16.1-Ubuntu <<>> -x 0
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 34751
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;0.in-addr.arpa.			IN	PTR

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jun 19 21:41:21 UTC 2023
;; MSG SIZE  rcvd: 43
```

The behavior is inconsistent across systemd versions. Very old versions of systemd used to give NXDOMAIN here,
then it became SERVFAIL in 234, before going back to NXDOMAIN in 235 (my notes from the time say that https://github.com/systemd/systemd/pull/6946 was what fixed it, but I'm not 100% on that). However, the version of systemd-resolve I have in Ubuntu 20.04 is back to SERVFAIL for these queries, so presumably something changed again.

The reason I keep noticing these is that we have a test for this behavior in the JuliaLang testsuite. Our understanding was that an NXDOMAIN is required by RFC6303:

> Unless configured otherwise, an iterative resolver will now return
   authoritatively (AA=1) name errors (RCODE=3) for queries within the
   zones in [Section 4](https://www.rfc-editor.org/rfc/rfc6303#section-4), with the obvious exception of queries for the
   zone name itself where SOA, NS, and "no data" responses will be
   returned as appropriate to the query type.  One common way to do this
   all at once is to serve empty (SOA and NS only) zones.

So we ended up using these queries as something we expected to give NXDOMAIN relatively reliably ;).
That said, I'm not a DNS expert, so perhaps there is some other reason to SERVFAIL these.

### Steps to reproduce the problem

Just `dig -x 0` and see SERVFAIL vs NXDOMAIN.

**Comment by Keno** [comment]
(Sorry, hit enter while in still editing - one sec)

**Comment by poettering** [comment]
Works fine here. 245 is ancient. Please update.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
