### ISSUE TITLE
Unable to login to GNOME using homed-managed user

### ISSUE THREAD

**Issue by arturasb** [systemd/systemd#28096]
### systemd version the issue has been seen with

systemd 252 (252.6-1)

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-9-amd64

### CPU architectures issue was seen on

x86_64

### Component

homectl

### Expected behaviour you didn't see

I want to login to GNOME session using my homed-managed user by entering user's credentials - user name and password.

### Unexpected behaviour you saw

I enter my homed-managed user's credential and GNOME's login screen reports there was no such user found. I checked user in CLI before trying login to GNOME session:```

`sudo homectl activate <my user name>`
`sudo homectl inspect <my user name>`
`sudo homectl deactivate <my user name`

### Steps to reproduce the problem

1. Install systemd-homed - `sudo apt install systemd-homed`
2. Create homed-managed user - `homectl create <user name> --real-name="user real name" -G wheel --disk-size=10G --storage=luks --fs-type=ext4`
3. `sudo homectl activate <my user name>`
4. `sudo homectl inspect <my user name>`
5. `sudo homectl deactivate <my user name`
6. Log out current user
7. In the log in screen choose "Not Listed"
8. Enter homed-managed user name, press Enter
9. Enter homed-managed user's password, press Enter

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://gist.github.com/arturasb/28401878338cc806f8efcabd27511202
```

**Comment by poettering** [comment]
my educated guess is that debian doesn't do the PAM or NSS hookup? i.e. see the pam_systemd_home and nss-systemd man pges.

**Comment by arturasb** [comment]
Well, I found `pam_systemd_home` added to all common-* PAM's configs. Then, /etc/nsswitch.conf has `systemd` to `passwd` and `group` - is that enough ?

**Comment by poettering** [comment]
> ```shell
> https://gist.github.com/arturasb/28401878338cc806f8efcabd27511202
> ```

your user name is literally `<user name>`? seriously?

**Comment by poettering** [comment]
does it show up with `getent passwd` after you created it?

**Comment by arturasb** [comment]
> > ```shell
> > https://gist.github.com/arturasb/28401878338cc806f8efcabd27511202
> > ```
> 
> your user name is literally `<user name>`? seriously?

I'm from Europe, GDPR-aware. Logs are cleared out a bit before posting it to Github  :smile: 

Of course, I have a normal user name for my homed-managed user.

**Comment by poettering** [comment]
> I'm from Europe, GDPR-aware. Logs are cleared out a bit before posting it to Github smile

well whatever, but you replaced only some of the data. also, useless and confusing.

**Comment by arturasb** [comment]
> Anyway, it really looks as if your NSS config is fucked, as accountsservice seems to think the user doesn't exist.

this is the contents of nsswitch.conf, anything suspicious in particular ?

# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd
group:          files systemd
shadow:         files systemd
gshadow:        files systemd

hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

**Comment by arturasb** [comment]
Should I provide more logs to help to debug this ?

**Comment by ArchangeGabriel** [comment]
I’m having the same or at least a very similar issue. Fresh minimal Debian 12 install.

Here is a logging attempt from a tty:
https://gist.github.com/ArchangeGabriel/cc0df0bf6415a2fba7083a84d60934e3

I can confirm that by default, `nsswitch.conf` does not contain references to systemd:
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files
group:          files
shadow:         files
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```
I’ve added `systemd` as expected, but it does not change the issue.

Regarding PAM, here are matching lines from the default Debian configuration:
```sh
$ grep systemd_home /etc/pam.d/*
/etc/pam.d/common-account:account	[success=2 default=ignore]	pam_systemd_home.so 
/etc/pam.d/common-auth:auth	[success=2 default=ignore]	pam_systemd_home.so 
/etc/pam.d/common-password:password	[success=2 default=ignore]	pam_systemd_home.so 
/etc/pam.d/common-session:session	optional	pam_systemd_home.so 
/etc/pam.d/common-session-noninteractive:session	optional	pam_systemd_home.so 
```

> does it show up with `getent passwd` after you created it?

No. That is the proof something is going wrong there, but I have no idea how to fix it. It works OOTB on Arch, I’ve tried to look in configuration differences but they are just too many…

**Comment by arturasb** [comment]
> @arturasb since you also had to add `systemd` manually, I guess you do not have `libnss-systemd` installed.

Yes, that was the case. Installing the `libnss-systemd` solved the problem. Thank you so much !

How could I redirect this issue to Debian before closing it here ? What is the proper way of doing that ?

**Comment by ArchangeGabriel** [comment]
Well there is a [bug reporting procedure](https://www.debian.org/Bugs/Reporting.en.html), but it seemed too complicated for the time I was willing to spend on it. Instead I’ve emailed @bluca that seems to maintain `systemd` in Debian and with who I worked a bit on another project in the past, hopping he will be able to handle it. I’ll keep you updated if he doesn’t do it himself. ;)

**Comment by arturasb** [comment]
@ArchangeGabriel , maybe you know answer to this question/issue - I tried to update my homed-managed user with FIDO2 (Yubikey 5) logging in capabilities, but I get this error - "Security token is not inserted, refusing". I guess there is some LUKS/FIDO dependency is missing, but which ? Maybe you know ?

**Comment by ArchangeGabriel** [comment]
Sorry, I have no idea about FIDO2, and do not have anything to test it.

**Comment by ArchangeGabriel** [comment]
Fix commited in Debian: https://salsa.debian.org/systemd-team/systemd/-/commit/a66cc245ebc86dc5794608194a4c1bb316a92d27
