### ISSUE TITLE
systemd-binfmt inside WSL distribution resets inherited binfmt_misc

### ISSUE THREAD

**Issue by vbatts** [systemd/systemd#28126]
### systemd version the issue has been seen with

252 (252.6-1)

### Used distribution

debian bookworm/12

### Linux kernel version used

5.15.90.2-microsoft-standard-WSL2

### CPU architectures issue was seen on

None

### Component

systemd-binfmt

### Expected behaviour you didn't see

the inherited registered `/proc/sys/fs/binfmt_misc/WSLInterop` handler from the WSL `--system` OS.
```shell
$ cat /proc/sys/fs/binfmt_misc/WSLInterop
enabled
interpreter /init
flags: PF
offset 0
magic 4d5a
```

### Unexpected behaviour you saw

after upgrading from debian bullseye/11 to bookworm/12, this behavior began. (I was using systemd in bullseye on WSL, and this binfmt_misc was inherited just fine).

Now it seems when the `systemd-binfmt.service` starts, it wipes the registered handlers, and I'm left only with something for Python3.11.

### Steps to reproduce the problem

on windows:
1. install windows subsystem for linux (WSL2)
2. install the debian distro (currently was bullseye)
3. configure it use systemd
```shell
root@weasel:~# cat /etc/wsl.conf
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config
[boot]
systemd = true
```
5. inplace dist-upgrade to bookworm
6. `ls /proc/sys/fs/binfmt_misc/`

### Additional program output to the terminal or log subsystem illustrating the issue

the systemd inside the WSL Distro seems to detect it is running in an hypervisor, rather than something that's more like a container..
`Jun 22 10:59:00 weasel kernel: Hypervisor detected: Microsoft Hyper-V`

There are a couple of separate work-arounds, that are something of a stop-gap. Ideally this is handled properly.
1. `systemctl mask systemd-binfmt.service` will stop things from getting reset
2. create a file `/etc/binfmt.d/WSLInterop.conf` with content like: `:WSLInterop:M::MZ::/init:`
3. if users have the `binfmt-support` package installed, that provides its own service, they can create a similar file (albeit different format) in /var/lib/binfmts/ or /usr/share/binfmts/; or just run the command `update-binfmts --install WSLInterop /init --magic '\x4d\x5a'`

**Comment by poettering** [comment]
hmm, what does that binfmt actually do?

wsl really should add their entry to `/run/binfmt.d/` before invoking systemd, otherwise this will always conflict because we never know whether an entry we find in the kernel should be deleted because we can't find any config for it, or if it should stay because it was inherited down.

I don't think we should change anything in systemd here. On systems where systemd-binfmt is enabled the subsystem is kinda owned by it, and you cannot have multiple owners of it without stepping on each others toes.

Can you file a bug against WSL asking them to fix that? Fix should be simple: just provide whatever they want to provide in a drop-in /run/binfmt.d/ from their agent and things should be good.

**Comment by vbatts** [comment]
well, that binfmt is a magic handler that allows the host to execute the *.exe
✨ magic ✨ 

The `/run/binfmt.d/*.conf` suggestion I've passed along.

**Comment by bluca** [comment]
Can this be configured via credentials? IIRC they prefer not to write files in the guest fs, so if you can pass something directly to systemd via creds when starting it, it would be more likely to be fixed

**Comment by puetzk** [comment]
> IIRC they prefer not to write files in the guest fs

Though it may help that in this case, they still really aren't modifying the persistent guest fs;
they know they're in calling systemd, and (I think?) they're directly in control of having made /run a tmpfs. In any case they're already generating other systemd units in /run, like the WSLg Remount Service in /run/systemd/generator.early/wslg-mount.service. So generating something in /run for systemd-binfmt doesn't seem outside of that precedent.

**Comment by poettering** [comment]
So, let's close this here, it's not actionable to us. They really should ship their binfmt.d stuff as drop-in for /run/binfmt.d/ (and they can also apply it directly if they want, for compat). But there's nothing we should change from our side I am sure. Hence closing.

**Comment by vbatts** [comment]
right on
