### ISSUE TITLE
systemd-bootchart support for partitions

### ISSUE THREAD

**Issue by famo** [systemd/systemd#2812]
I have on my system `/ , /usr , /var and / home` (all ext4) on different partitions.

It is an UEFI system with GPT using systemd-boot to boot.
systemd-bootchart is invoked via kernel parameters ("`initcall_debug printk.time=y init=/usr/lib/systemd/systemd-bootchart`").

With this setup I get a bootchart which only spans ~ 3 seconds, here is an example:
http://imgh.us/before-bootchart-20160306-1332.svg

It would be nice if systemd-bootchart could properly support this case and chart all data / up to the login.

**Comment by zonque** [comment]
systemd-bootchart has been given a new home:

  https://github.com/systemd/systemd-bootchart

Could you please file your issue over there again? Thanks :)
