### ISSUE TITLE
GPT partition flag 59 support

### ISSUE THREAD

**Issue by punoko** [systemd/systemd#28133]
### Component

systemd-gpt-auto-generator, systemd-growfs

### Is your feature request related to a problem? Please describe

I'm trying to build an image following the storage guidelines [here](https://systemd.io/BUILDING_IMAGES/), which mention support for GPT partition flag 59 `SD_GPT_FLAG_GROWFS` to automatically grow filesystems according to the [specification](https://uapi-group.org/specifications/specs/discoverable_partitions_specification/), but my attempts to use that flag have not been successful and I couldn't find any references to this mechanism in either [systemd-growfs](https://www.freedesktop.org/software/systemd/man/systemd-growfs.html) or [systemd-gpt-auto-generator](https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html).

### Describe the solution you'd like

Automatically grow the filesystem when GPT partition flag 59 is set. Also growing the partition would be nice but I believe that to be out of scope for that flag.

### Describe alternatives you've considered

Right now, as far as I'm aware, automatically growing the partition and the filesystem requires a `repart.d` drop-in along with an fstab entry with `x-systemd.growfs` at bare minimum. That is a shame because we're already able to do all the mounting without interacting with fstab or the kernel command line by simply applying proper partition type UUIDs.

### The systemd version you checked that didn't have the feature you are asking for

253 (253.5-2-arch)

Thanks

**Comment by poettering** [comment]
this should just work if you mount things with systemd-gpt-auto-generator. it will honour that flag and basically do automatically what x-systemd.growfs does explicitly

**Comment by clement-dufour** [comment]
I'm also facing this situation with a similar setup following the [guidelines](https://systemd.io/BUILDING_IMAGES/).

[An entry in the TODO](https://github.com/systemd/systemd/blob/d98037166929b87ed119a1560d398a9460113eb7/TODO#L2227) seems to indicate that this behavior is yet to be implemented.

I also tried to use the GrowFileSystem= setting in a repart.d drop-in but according to the documentation and the code, this setting only sets the partition flag 59 and does not by its own trigger the corresponding systemd-growfs@ service.

If needed, I would also be happy to provide more information and logs.

**Comment by punoko** [comment]
Thank you !
