### ISSUE TITLE
Unclear documentation on multiple units watching same file with systemd.path

### ISSUE THREAD

**Issue by mdivyamohan** [systemd/systemd#28135]
### systemd version the issue has been seen with

244

### Used distribution

Custom distribution

### Linux kernel version used

4.19.284

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Following are a bit unclear from systemd.path man page:

Assume I have one file, that needs to be monitored by two different units. 

Option-1: Can two units `watcher-1` and `watcher-2` be activated by a single `watcher .path`?

Example: watcher.path:
```
[Unit]
Description=Monitor file

[Path]
PathChanged=<file>
Unit=watcher-1.service
Unit=watcher-2.service

[Install]
WantedBy=multi-user.target
```

Option-2: Should `watcher-1.path` and `watcher-2.path` be created, which will activate `watcher-1.service` and `watcher-2.service` respectively?

In both of these options, will `watcher-1.service` and `watcher-2.service` be activated in parallel or in sequence?

**Comment by dtardon** [comment]
> Option-1: Can two units `watcher-1` and `watcher-2` be activated by a single `watcher .path`?

No. A path unit can only activate a single service.
 
> Option-2: Should `watcher-1.path` and `watcher-2.path` be created, which will activate `watcher-1.service` and `watcher-2.service` respectively?

Yes.
 
> In both of these options, will `watcher-1.service` and `watcher-2.service` be activated in parallel or in sequence?

In parallel.

Also, please send questions like this to the mailing list next time.
