### ISSUE TITLE
systemd doesn't unmount loopback files at system's shutdown/reboot which corrupts live USB sticks

### ISSUE THREAD

**Issue by v-fox** [systemd/systemd#2814]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> [228](https://build.opensuse.org/package/show/openSUSE:Factory/systemd?rev=228)
### Used distribution

> [Customized](https://github.com/v-fox/live_opensuse_hsf/tree/180155df0b1a2874b57c6f26b285db1a0beac40f) openSUSE Factory / "Tumbleweed" build
### In case of bug report: Expected behaviour you didn't see

> Safe system shutdown of live system on USB stick.
### In case of bug report: Unexpected behaviour you saw

> Corruption of R/W-overlay that's kept in a ext4 loop-file.
### In case of bug report: Steps to reproduce the problem

> I make my openSUSE live cd/usb build with universal "[kiwi](https://github.com/openSUSE/kiwi)" live build system. In my case, the target device is partitioned in two: FAT partition with a bootloader and R/O-squashfs root filesystem loop-file ("Hackeurs_Sans_Frontieres-read-only.x86_64-0.9.0" -> /dev/loop0) mounted as /livecd and exFAT partition with R/W-ext4 overlay filesystem in the loop-file ("Live OS's persistent storage.fs" -> /dev/loop1) mounted as /cow. Those are mounted by initrd script and then are given to systemd via mount --move. BUT on shutdown systemd seem to try unmounting /livecd and /cow without first unmounting /livecd/Hackeurs_Sans_Frontieres-read-only.x86_64-0.9.0 and /cow/Live OS's persistent storage.fs which results in corruption of /cow/Live OS's persistent storage.fs where all permanent changes to the live system are kept.

[Here's journald log from that system](https://gist.github.com/v-fox/241076a3f0f63062380c).

**Comment by michich** [comment]
The output from "findmnt" and "losetup -a" might better convey what's mounted where.

Anyway, journald cannot record what happens after it's killed. systemd-shutdown should attempt to detach remaining loop devices and unmount filesystems. You should be able to see it doing it:
`systemd-analyze set-log-level debug; systemd-analyze set-log-target console; systemctl halt`

If the root filesystem needs some action to be brought down cleanly, it is the responsibility of the initramfs that brought it up in the first place to put it down again:
https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

**Comment by v-fox** [comment]
> The output from "findmnt" and "losetup -a" might better convey what's mounted where.

`findmnt`:

```
TARGET                                SOURCE     FSTYPE          OPTIONS
/                                     overlay    overlay         rw,relatime,lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work
├─/sys                                sysfs      sysfs           rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/security              securityfs securityfs      rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs      tmpfs           ro,nosuid,nodev,noexec,mode=755
│ │ ├─/sys/fs/cgroup/systemd          cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
│ │ ├─/sys/fs/cgroup/devices          cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,devices
│ │ ├─/sys/fs/cgroup/memory           cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,memory
│ │ ├─/sys/fs/cgroup/perf_event       cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/blkio            cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,blkio
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,cpu,cpuacct
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,net_cls,net_prio
│ │ ├─/sys/fs/cgroup/freezer          cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,freezer
│ │ ├─/sys/fs/cgroup/hugetlb          cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,hugetlb
│ │ ├─/sys/fs/cgroup/pids             cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,pids
│ │ └─/sys/fs/cgroup/cpuset           cgroup     cgroup          rw,nosuid,nodev,noexec,relatime,cpuset
│ ├─/sys/fs/pstore                    pstore     pstore          rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/debug                 debugfs    debugfs         rw,relatime
│ └─/sys/fs/fuse/connections          fusectl    fusectl         rw,relatime
├─/proc                               proc       proc            rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc          systemd-1  autofs          rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
├─/dev                                devtmpfs   devtmpfs        rw,relatime,size=1695956k,nr_inodes=423989,mode=755
│ ├─/dev/shm                          tmpfs      tmpfs           rw,relatime,size=705728k
│ ├─/dev/pts                          devpts     devpts          rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ ├─/dev/mqueue                       mqueue     mqueue          rw,relatime
│ └─/dev/hugepages                    hugetlbfs  hugetlbfs       rw,nosuid,nodev,noexec,noatime
├─/run                                tmpfs      tmpfs           rw,nosuid,nodev,relatime,mode=755
│ ├─/run/user/0                       tmpfs      tmpfs           rw,nosuid,nodev,relatime,size=352864k,mode=700
│ └─/run/user/1000                    tmpfs      tmpfs           rw,nosuid,nodev,relatime,size=352864k,mode=700,uid=1000,gid=100
│   └─/run/user/1000/gvfs             gvfsd-fuse fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=100
├─/cow                                /dev/vda1  exfat           rw,relatime,fmask=0022,dmask=0022,iocharset=utf8,namecase=0,errors=remount-ro
├─/livecd                             /dev/vda2  udf             ro,relatime,utf8
├─/read-only                          /dev/loop1 squashfs        ro,relatime
├─/read-write                         /dev/loop0 ext4            rw,nodiratime,relatime,block_validity,delalloc,barrier,user_xattr,acl,stripe=128
├─/tmp                                tmpfs      tmpfs           rw,relatime,size=352864k,mode=755
└─/home/hacker/shared                 shared     9p              rw,relatime,sync,dirsync
```

`losetup -a`:

```
/dev/loop0: []: (/cow/Live OS's persistent storage.fs)
/dev/loop1: []: (/livecd/Hackeurs_Sans_Frontieres-read-only.x86_64-0.9.0)
```

> Anyway, journald cannot record what happens after it's killed. systemd-shutdown should attempt to detach remaining loop devices and unmount filesystems. You should be able to see it doing it:
> systemd-analyze set-log-level debug; systemd-analyze set-log-target console; systemctl halt

Ending of `systemd-analyze set-log-target kmsg; systemd-analyze set-log-level debug; systemctl halt` from virtual machine with serial->file emulation:

```
[ 1546.055700] systemd[1]: Stopped target Local File Systems.
[ 1546.121291] systemd[1]: Unmounting /run/user/457...
[ 1546.127575] systemd[1]: Unmounting /run/user/0...
[ 1546.131208] systemd[1]: Unmounting /home/hacker/shared...
[ 1546.139229] systemd[1]: Unmounting /tmp...
[ 1546.153466] systemd[1]: Unmounting /read-only...
[ 1546.156839] systemd[1]: Unmounting /cow...
[ 1546.159739] systemd[1]: Unmounting /read-write...
[ 1546.163271] systemd[1]: Unmounting /livecd...
[ 1546.188992] systemd[1]: Unmounted /run/user/457.
[ 1546.192545] systemd[1]: Unmounted /run/user/0.
[ 1546.196710] systemd[1]: Unmounted /home/hacker/shared.
[ 1546.200168] systemd[1]: Unmounted /tmp.
[ 1546.202446] systemd[1]: Unmounted /read-only.
[ 1546.204841] systemd[1]: cow.mount: Mount process exited, code=exited status=32
[ 1546.206774] systemd[1]: Failed unmounting /cow.
[ 1546.209076] systemd[1]: Unmounted /read-write.
[ 1546.210984] systemd[1]: livecd.mount: Mount process exited, code=exited status=32
[ 1546.213280] systemd[1]: Failed unmounting /livecd.
[ 1546.237040] systemd[1]: Reached target Unmount All Filesystems.
[ 1546.240052] systemd[1]: Stopped target Local File Systems (Pre).
[ 1546.242547] systemd[1]: Stopped Create Static Device Nodes in /dev.
[ 1546.244572] audit: type=1131 audit(1457620507.277:247): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 1546.249250] systemd[1]: Stopped Remount Root and Kernel File Systems.
[ 1546.251397] audit: type=1131 audit(1457620507.284:248): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 1546.255685] systemd[1]: Reached target Shutdown.
[ 1546.321351] systemd[1]: Starting /etc/init.d/halt.local Compatibility...
[ 1546.331068] systemd[1]: Started /etc/init.d/halt.local Compatibility.
[ 1546.333242] audit: type=1130 audit(1457620507.366:249): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=halt-local comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 1546.340036] systemd[1]: Reached target Final Step.
[ 1546.342371] systemd[1]: Starting Halt...
[ 1546.357714] systemd[1]: Shutting down.
[ 1546.417171] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[ 1546.442325] systemd-journald[5551]: Received SIGTERM from PID 1 (systemd-shutdow).
[ 1546.586293] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[ 1546.614179] systemd-shutdown[1]: Unmounting file systems.
[ 1546.615813] systemd-shutdown[1]: Remounting '/' read-only with options 'lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work'.
[ 1547.064649] systemd-shutdown[1]: Remounting '/livecd' read-only with options 'utf8'.
[ 1547.074280] systemd-shutdown[1]: Unmounting /livecd.
[ 1547.075911] systemd-shutdown[1]: Remounting '/cow' read-only with options 'fmask=0022,dmask=0022,iocharset=utf8,namecase=0,errors=remount-ro'.
[ 1547.080500] systemd-shutdown[1]: Unmounting /cow.
[ 1547.081798] systemd-shutdown[1]: Remounting '/' read-only with options 'lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work'.
[ 1547.084877] systemd-shutdown[1]: Remounting '/livecd' read-only with options 'utf8'.
[ 1547.086695] systemd-shutdown[1]: Unmounting /livecd.
[ 1547.088049] systemd-shutdown[1]: Could not unmount /livecd: Device or resource busy
[ 1547.089810] systemd-shutdown[1]: Remounting '/cow' read-only with options 'fmask=0022,dmask=0022,iocharset=utf8,namecase=0,errors=remount-ro'.
[ 1547.092925] systemd-shutdown[1]: Unmounting /cow.
[ 1547.094234] systemd-shutdown[1]: Could not unmount /cow: Device or resource busy
[ 1547.095983] systemd-shutdown[1]: Not all file systems unmounted, 2 left.
[ 1547.097573] systemd-shutdown[1]: Deactivating swaps.
[ 1547.100687] systemd-shutdown[1]: All swaps deactivated.
[ 1547.102107] systemd-shutdown[1]: Detaching loop devices.
[ 1547.117103] systemd-shutdown[1]: Detaching loopback /dev/loop1.
[ 1547.118797] systemd-shutdown[1]: Detaching loopback /dev/loop0.
[ 1547.121850] systemd-shutdown[1]: All loop devices detached.
[ 1547.123354] systemd-shutdown[1]: Detaching DM devices.
[ 1547.124878] systemd-shutdown[1]: All DM devices detached.
[ 1547.126447] systemd-shutdown[1]: Unmounting file systems.
[ 1547.128031] systemd-shutdown[1]: Remounting '/' read-only with options 'lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work'.
[ 1547.131136] systemd-shutdown[1]: Remounting '/livecd' read-only with options 'utf8'.
[ 1547.132930] systemd-shutdown[1]: Unmounting /livecd.
[ 1547.134275] systemd-shutdown[1]: Remounting '/cow' read-only with options 'fmask=0022,dmask=0022,iocharset=utf8,namecase=0,errors=remount-ro'.
[ 1547.137322] systemd-shutdown[1]: Unmounting /cow.
[ 1547.138647] systemd-shutdown[1]: Remounting '/' read-only with options 'lowerdir=/read-only,upperdir=/read-write/rw,workdir=/read-write/work'.
[ 1547.143248] systemd-shutdown[1]: Remounting '/livecd' read-only with options 'utf8'.
[ 1547.145105] systemd-shutdown[1]: Unmounting /livecd.
[ 1547.146436] systemd-shutdown[1]: Could not unmount /livecd: Device or resource busy
[ 1547.148529] systemd-shutdown[1]: Remounting '/cow' read-only with options 'fmask=0022,dmask=0022,iocharset=utf8,namecase=0,errors=remount-ro'.
[ 1547.152165] systemd-shutdown[1]: Unmounting /cow.
[ 1547.153666] systemd-shutdown[1]: Could not unmount /cow: Device or resource busy
[ 1547.155751] systemd-shutdown[1]: Not all file systems unmounted, 2 left.
[ 1547.157769] systemd-shutdown[1]: Cannot finalize remaining file systems, continuing.
[ 1547.276872] systemd-shutdown[25645]: /usr/lib/systemd/system-shutdown/nutshutdown failed with error code 1.
[ 1547.295257] systemd-shutdown[1]: Failed to finalize  file systems, ignoring
[ 1547.352330] systemd-shutdown[1]: Halting system.
[ 1547.684253] reboot: System halted
```

[Full serial log file](https://gist.github.com/v-fox/5f76e94d5fd3506fa082).

> If the root filesystem needs some action to be brought down cleanly, it is the responsibility of the initramfs that brought it up in the first place to put it down again:
> https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

squashfs root is pretty much how all livecds are doing things, if I'm not mistaken. This bug may be largely unnoticed because very few of them use Read/Write and can get their filesystems corrupted but treating loop-files properly and figuring out filesystem hierarchy is a necessity for an init system. At least it should sync the changes and put those mounts in R/O or something.

**Comment by v-fox** [comment]
I see, however, that in the log it reports that it has unmounted the loop-files but for me, just after that, the loop-file ext4 image was in the dirty state and manual fsck found errors. I can only assume that's because its "parental" exfat filesystem in /cow didn't get changes to the loop-file properly finalized or something.

It may have something to do with handling overlayfs rather than loop-files.

**Comment by poettering** [comment]
systemd is unable to determine dependencies from overlayfs automatically. Please specify the file systems your overlayfs depends on explicitly via x-systemd.requires-mounts-for=. Otherwise systemd will try to unmount the overlayfs possibly only after it already tried to unmount the backing file systems... See systemd.mount(5), the section about fstab for details.

afaics everything works the way it should, except that the overlayfs deps are not declared. Hence closing.

(Given that overlayfs is in upstream kernel now, I could be convinced that the fstab generator should maybe learn to automatically parse the mount parameters and ad the mount deps automatically...)

**Comment by v-fox** [comment]
> Given that overlayfs is in upstream kernel now, I could be convinced that the fstab generator should maybe learn to automatically parse the mount parameters and ad the mount deps automatically

Well, it certainly should, given that's how hybrid livecd's are made in general. Maybe livecd building scripts could try some workaround hacks for now but if something fails by design I wouldn't exactly call it "as should".

Shouldn't systemd parse `/etc/mtab` on shutdown anyway ? fstab is only holding boot-up mounts and /etc/mtab is nowadays a symlink to kernel's actual current status of mounts. openSUSE's "kiwi" live building framework doesn't even populate fstab with correct `/` data. There is no reason for systemd not to figure out how to safely detect & unmount all mainline filesystems at shutdown. Or it just doesn't get overlayfs' `{upper,lower,work}dir` options and that's it ? It's probably not the only filesystem that may use several devices for different purposes either.

**Comment by arvidjaar** [comment]
@v-fox 

> it has unmounted the loop-files but for me, just after that, the loop-file ext4 image was in the dirty state

It sounds like the actual problem is block device caching and the fact that loop devices were not cleanly unconfigured. Later systemd remounts underlying filesystem as read-only which prevents flushing of loop device. Just guessing here (I do not know if loop device keeps backing store busy in this case).

Could you try to create additional units for loop devices that would go between /read-write and corresponding underlying file system? I.e. something like

```
[Unit]
Before=read-write.mount
After=cow.mount
DefaultDependencies=no
Conflicts=umount.target

[Service]
Type=oneshot
RemainAfterExit=true
ExecStop=/sbin/losetup -d /dev/loop0
```

And make read-write.mount pull it in e.g. via x-systemd.requires fstab option or drop ins (actually would say for testing you could simply drop this unit in /run/systemd/system, do daemon-reload and start this unit manually; should be enough to trigger it on shutdown).

**Comment by poettering** [comment]
> Well, it certainly should, given that's how hybrid livecd's are made in general. Maybe livecd building scripts could try some workaround hacks for now but if something fails by design I wouldn't exactly call it "as should".

Again, you can already do this, you just have to correctly declare the deps on the fstab option lines. Hence, the only additoin is to do this more automatically, instead of requiring dep configuration for this by hand.

> Shouldn't systemd parse /etc/mtab on shutdown anyway ?

/etc/mtab is obsolete. systemd will never read that file. It should not exist in modern systems, and our README states clearly that you have to remove mtab support from util-linux when building it (via a configure switch), or the resulting build will not be compatible with systemd.

That said, systemd does read /proc/self/mountinfo, i.e. where the kernel exposes which file systems are mounted currently.

> Or it just doesn't get overlayfs' {upper,lower,work}dir options and that's it ?

Yes. We only parse the mount source device, we don't mount file system specific options. And I am pretty sure we shouldn't start with that either, we simply don#t want to carry a table for tons of weird file systems in systemd that makes it understand their options. However, I figure for overlayfs we could make an exception, since it's kinda an API fs, and not a real fs...

**Comment by eelko** [comment]
I have the same problem. Did you manage to resolve this, and if so, how did you proceed?

**Comment by v-fox** [comment]
> I have the same problem. Did you manage to resolve this, and if so, how did you proceed?

No, I haven't been updating my builds for a while and recently kiwi has been completely rewritten, so I don't know if details of its workings changed or not.

> It sounds like the actual problem is block device caching and the fact that loop devices were not cleanly unconfigured. Later systemd remounts underlying filesystem as read-only which prevents flushing of loop device. Just guessing here (I do not know if loop device keeps backing store busy in this case).

Shouldn't kernel figure out to flush everything before cutting out write support ? Or, at least, systemd - to send such command before demanding R/O ? It's all too complex to test easily, unfortunately.

> Yes. We only parse the mount source device, we don't mount file system specific options. And I am pretty sure we shouldn't start with that either, we simply don#t want to carry a table for tons of weird file systems in systemd that makes it understand their options. However, I figure for overlayfs we could make an exception, since it's kinda an API fs, and not a real fs...

As a Linux-only init system shouldn't systemd at least fully support all in-kernel filesystems ? Especially "logical" ones, like overlayfs, ecryptfs, NFS, LVM. Otherwise, how is it different from bunch of script-based hacks of its predecessors ? Either you'll do that "the correct way" or someone will have to figure out bunch of snots and crutches.

**Comment by klausenbusk** [comment]
> If the root filesystem needs some action to be brought down cleanly, it is the responsibility of the initramfs that brought it up in the first place to put it down again:

I have a similar setup to @v-fox (squashfs + overlayfs + tmpfs, Debian Stretch), before I can umount the EXT4 parititon I need to umount the rootfs (`/`) and `<squashfs mount: /run/overlay/squashfs>`.
Is it correctly understood that rootfs (`/`) need to be the last mount? or can systemd umount `/`, `/run/overlay/squashfs`, `/run/overlay` and lastly `/run/ext4`, or do I need a shutdown initramfs for that?

**Comment by klausenbusk** [comment]
> systemd is unable to determine dependencies from overlayfs automatically. Please specify the file systems your overlayfs depends on explicitly via x-systemd.requires-mounts-for=. Otherwise systemd will try to unmount the overlayfs possibly only after it already tried to unmount the backing file systems... See systemd.mount(5), the section about fstab for details.

@poettering would what work with circular dependency?

Let say I have the following mounts:
```
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=101980k,mode=755)
/dev/vda3 on /run/medium type ext4 (rw,relatime,data=ordered)
tmpfs on /run/overlay type tmpfs (rw,relatime)
/dev/loop0 on /run/overlay/filesystem.squashfs type squashfs (ro,relatime)
overlay on / type overlay (rw,relatime,lowerdir=/run/overlay/filesystem.squashfs,upperdir=/run/overlay/upper,workdir=/run/overlay/work)
[...]
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                            DIO
/dev/loop0         0      0         1  0 /run/medium/live/filesystem.squashfs   0
```
In that situation. `/mnt/medium` is used by `/dev/loop0` which is mounted at `/run/overlay/filesystem.squashfs` and used by `overlayfs` to mount the rootfs `/`.

So I would first need to umount `/`, then `/run/overlay/filesystem.squashfs` and then I should be able to umount `/run/medium`, but I can't umount `/` as it is in use by `/run/overlay/filesystem.squashfs` and `/run/medium`. Looking at the [`umount`](https://github.com/systemd/systemd/blob/bbc79ae5c9fdfc76999c306376d4a876dbf29b21/src/core/umount.c#L646) logic `systemd-shutdown` use, it way to simple to handle a circular dependency case.

**Comment by poettering** [comment]
> @poettering would what work with circular dependency?

no, systemd doesn't support that. How did you even manage to set up things like that? MS_MOVE? 

I am not sure it's worth supporting stuff with cyclic deps like that really, I think it would make more sense to rework this not to be cyclic

**Comment by klausenbusk** [comment]
> How did you even manage to set up things like that? MS_MOVE?

Yeh, I do something like the following in the initramfs:
`${rootmnt}` is the real disk, which contain a squashfs file.
```
mkdir "${rootmnt}.tmp" "/run/overlay"
mount -n -o move "${rootmnt}" "${rootmnt}.tmp"
mount -t tmpfs tmpfs /run/overlay

mkdir "/run/overlay/filesystem.squashfs" "/run/overlay/upper" "/run/overlay/work"
mount "${rootmnt}.tmp/filesystem.squashfs" "/run/overlay/filesystem.squashfs" -t squashfs -o loop
mount -t overlay overlay -o lowerdir=/run/overlay/filesystem.squashfs,upperdir=/run/overlay/upper,workdir=/run/overlay/work "${rootmnt}"

mkdir -p "${rootmnt}/mnt/medium"
mount -n -o move "${rootmnt}.tmp" "${rootmnt}/mnt/medium"
```
The initscript then takeover and move `/run/` to `${rootmnt}/run` and switchroot to `${rootmnt}`.

> I think it would make more sense to rework this not to be cyclic

I don't think I can avoid that. I need access to the disk, so I need to move the real `${rootmnt}` inside the squashfs mount.

I solved it for now, by running the following script from [the shutdown initrd](https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/).
```
mkdir -p /mnt
mount --move /oldroot/mnt/medium /mnt
umount -R /oldroot
umount /mnt
exec /lib/systemd/systemd-shutdown "$@"
```
