### ISSUE TITLE
udevadm trigger fails when run in lxd container

### ISSUE THREAD

**Issue by JBau32** [systemd/systemd#28156]
### systemd version the issue has been seen with

249.11-0ubuntu3.9

### Used distribution

Ubuntu 22.04.2

### Linux kernel version used

5.19.0-45-generic

### CPU architectures issue was seen on

x86_64

### Component

udevadm

### Expected behaviour you didn't see

`udevadm trigger` return success / no errors

### Unexpected behaviour you saw

`udevadm trigger` throws errors

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# udevadm trigger
SELinux enabled state cached to: disabled
sd-device-enumerator: Scan all dirs
sd-device-enumerator: Scanning /sys/bus
sd-device-enumerator: Scanning /sys/class
LNXSYSTM:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
ACPI0008:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/ACPI0008:00/uevent': Permission denied
INT339B:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/INT339B:00/uevent': Permission denied
INT3420:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/INT3420:00/uevent': Permission denied
[...]

Full log here: https://gist.github.com/JBau32/526acd01eae9ecfabf1fed5717dcdce0
```

**Comment by poettering** [comment]
sysfs is not virtualized for containers on Linux kernel. RUnning udev inside containers hence is not supported. udevadm trigger is conditioned on /sys/ being writable, which is how container managers should communicate that udev is not supposed to run.

Closing.
