### ISSUE TITLE
resolve queries to the reverse mapping domains (.in-addr.arpa, ip6.arpa) are slow on negative response

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#28166]
Queries to the reverse mapping domains are slow when there is not a positive answer available.

They are slow because systemd-resolved considers all queries to these domains to be in scope for mDNS (and LLMNR), and as a result does not consider NXDOMAIN status from upstream nameservers to be authoritative for these queries. In mDNS, by design, usually no host can return authoritative negative responses to rdns questions, and we must wait for a timeout on each retry before sd-resolved retires the query and returns a negative answer. This timeout is on the order of 7 seconds in total — almost certainly much slower than any dns response.

Most other queries don't share this issue because they are not in scope for mDNS, or as .local hostnames can reasonably be expected to give a response. Most global scope addresses do not belong to the local subnet most of the time, so rdns questions for these addresses will almost never get a response in mDNS, and there is a steep penalty in mDNS for asking questions that cannot be answered.

In practice, this causes issues for applications that make rnds queries. Here is an example ping to (literally) "example.com":

```
$ time ping -c4 example.com
PING example.com (93.184.216.34) 56(84) bytes of data.
64 bytes from 93.184.216.34: icmp_seq=1 ttl=56 time=37.0 ms
64 bytes from 93.184.216.34: icmp_seq=2 ttl=56 time=36.4 ms
64 bytes from 93.184.216.34: icmp_seq=3 ttl=56 time=36.7 ms
64 bytes from 93.184.216.34: icmp_seq=4 ttl=56 time=37.0 ms
[...]
ping -c4 example.com  0.00s user 0.00s system 0% cpu 30.872 total
```

4 pings, 1 per second, but it takes 30 seconds to complete. That is because ping makes an rdns query for each output line, and we cannot cache the non-answer from mDNS. `resolvectl query 93.184.216.34` demonstrates the timeout more directly, and here is a debug log (systemd-253.5) from that command:

<details><summary>sd-resolved debug log for resolvectl query 93.184.216.34</summary>

```
Jun 26 20:29:16 systemd-resolved[647]: Setting log level to debug.
Jun 26 20:29:16 systemd-resolved[647]: Sent message type=method_return sender=n/a destination=:1.368 path=n/a interface=n/a member=n/a cookie=33 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Got message type=method_call sender=:1.369 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveAddress  cookie=2 reply_cookie=0 signature=iiayt error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=34 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=12 reply_cookie=34 signature=u error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: D-Bus address resolution request from client PID 270699 (resolvectl) with UID 1000
Jun 26 20:29:17 systemd-resolved[647]: Looking up RR for 34.216.184.93.in-addr.arpa IN PTR.
Jun 26 20:29:17 systemd-resolved[647]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=35 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=36 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=14 reply_cookie=36 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: NXDOMAIN cache hit for 34.216.184.93.in-addr.arpa IN PTR
Jun 26 20:29:17 systemd-resolved[647]: Regular transaction 422 for <34.216.184.93.in-addr.arpa IN PTR> on scope dns on enp4s0/* now complete with <rcode-failure> from cache (unsigned; non-confidential).
Jun 26 20:29:17 systemd-resolved[647]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 26 20:29:17 systemd-resolved[647]: Firing regular transaction 27408 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 26 20:29:17 systemd-resolved[647]: Delaying mdns transaction 27408 for 0us.
Jun 26 20:29:17 systemd-resolved[647]: Initial jitter phase for transaction 27408 elapsed.
Jun 26 20:29:17 systemd-resolved[647]: Retrying transaction 27408.
Jun 26 20:29:17 systemd-resolved[647]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 26 20:29:17 systemd-resolved[647]: Firing regular transaction 27408 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 26 20:29:17 systemd-resolved[647]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 26 20:29:17 systemd-resolved[647]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 26 20:29:17 systemd-resolved[647]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=13 reply_cookie=35 signature=n/a error-name=n/a error-message=n/a
Jun 26 20:29:17 systemd-resolved[647]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.369' successfully installed.
Jun 26 20:29:18 systemd-resolved[647]: Timeout reached on transaction 27408.
Jun 26 20:29:18 systemd-resolved[647]: Retrying transaction 27408.
Jun 26 20:29:18 systemd-resolved[647]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 26 20:29:18 systemd-resolved[647]: Firing regular transaction 27408 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 26 20:29:18 systemd-resolved[647]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 26 20:29:18 systemd-resolved[647]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 26 20:29:20 systemd-resolved[647]: Timeout reached on transaction 27408.
Jun 26 20:29:20 systemd-resolved[647]: Retrying transaction 27408.
Jun 26 20:29:20 systemd-resolved[647]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 26 20:29:20 systemd-resolved[647]: Firing regular transaction 27408 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 26 20:29:20 systemd-resolved[647]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 26 20:29:20 systemd-resolved[647]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 26 20:29:24 systemd-resolved[647]: Timeout reached on transaction 27408.
Jun 26 20:29:24 systemd-resolved[647]: Retrying transaction 27408.
Jun 26 20:29:24 systemd-resolved[647]: Regular transaction 27408 for <34.216.184.93.in-addr.arpa IN PTR> on scope mdns on enp4s0/INET now complete with <attempts-max-reached> from none (unsigned; non-confidential).
Jun 26 20:29:24 systemd-resolved[647]: Freeing transaction 422.
Jun 26 20:29:24 systemd-resolved[647]: Sent message type=error sender=n/a destination=:1.369 path=n/a interface=n/a member=n/a cookie=37 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.Timeout error-message=All attempts to contact name servers or networks failed
Jun 26 20:29:24 systemd-resolved[647]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=38 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:24 systemd-resolved[647]: Freeing transaction 27408.
Jun 26 20:29:25 systemd-resolved[647]: Got message type=method_call sender=:1.370 destination=org.freedesktop.resolve1 path=/org/freedesktop/LogControl1 interface=org.freedesktop.DBus.Properties member=Set  cookie=3 reply_cookie=0 signature=ssv error-name=n/a error-message=n/a
Jun 26 20:29:25 systemd-resolved[647]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=39 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 26 20:29:25 systemd-resolved[647]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=15 reply_cookie=39 signature=u error-name=n/a error-message=n/a
Jun 26 20:29:25 systemd-resolved[647]: Setting log level to info.
```
</details>

DNS returns NXDOMAIN (retrieved from dns cache here, after ping), and 7 more seconds are wasted waiting for a reply that will not come from mDNS. There is no PTR record at 34.216.184.93.in-addr.arpa, hence the NXDOMAIN, and this is not an error on the part of the domain operator. When sending rdns queries we should expect that they may not have a positive response.

Currently, the only real option to avoid this issue is to disable mDNS (and LLMNR), but this also remove the ability to resolve .local hostnames, which is useful on its own, and necessary for dns-sd. I think there is value in a solution that enables mDNS without penalizing rdns queries.

In #14735 I suggested a network configuration option that would enable the administrator to choose what domains are in scope for mDNS. In #27001 I suggested to stop considering (general) rdns queries for mDNS scope. But apparently neither is palatable. Since this previously didn't have a dedicated issue, I'm creating this one.

I did consider the suggestion in #27001 to listen to installed routes up to some heuristic limit so that we can guess suitable subnets on which to enable mDNS scope. Afaik the v4 multicast address used for mDNS is only valid on the local subnet, so such a rule would only enable usable mDNS on a host that both doesn't already have an interface with a suitable address and has access to some kind of repeater to carry those packets to the other subnet. Additionally, it wouldn't even solve my issue since I have routes installed that are not suitable for mDNS (e.g. cross a wireguard link w/o multicast support). So I don't really see the value in that solution. At least I won't be implementing it.

**Comment by rpigott** [comment]
In #26594 @FranklinYu wrote:

> How was it implemented in other mDNS clients? Do they simply break the protocol?

---

sd-resolved is an outlier for considering public rdns queries for mdns scope. A typical avahi setup uses the mdns_minimal nss module ([like so](https://wiki.archlinux.org/title/Avahi#Hostname_resolution)), which only considers .local and the link-local rdns domains .254.169.in-addr.arpa, and .{8,9,a,b}.e.f.ip6.arpa. in scope.

By my interpretation, sd-resolved goes against the rfc6762 recommendation to enable this behavior, based on the following quotations.

The rfc calls out the above addresses:

> Any DNS query for a **name ending with ".local."** MUST be sent to the mDNS IPv4 link-local multicast address 224.0.0.251 (or its IPv6 equivalent FF02::FB).

> Like ".local.", the IPv4 and IPv6 reverse mapping domains are also defined to be link-local:
> Any DNS query for a **name ending with "254.169.in-addr.arpa."** MUST be sent to the mDNS IPv4 link-local multicast address 224.0.0.251 or the mDNS IPv6 multicast address FF02::FB.

> Likewise, any DNS query for a **name within the reverse mapping domains for IPv6 link-local addresses ("8.e.f.ip6.arpa.", "9.e.f.ip6.arpa.", "a.e.f.ip6.arpa.", and "b.e.f.ip6.arpa.")** MUST be sent to the mDNS IPv6 link-local multicast address FF02::FB or the mDNS IPv4 link-local multicast address 224.0.0.251.

and earlier it states:

>  DNS queries for names that do not end with ".local" MAY be sent to the mDNS multicast address, **if no other conventional DNS server is available.**

In combintation, I consider it to mean that the rdns domains not listed are not considered to be "link-local" in scope and so the above statement would apply to them as well.

In the status quo, sd-resolved ignores an authoritative response from DNS only to have the query fail again in mdns, counter to this interpretation. See #27001 for justification.

**Comment by rpigott** [comment]
(Information about this behavior is scattered across a dozen or more issues going back 5+ years. I'm trying to keep discussion informed and focused on this dedicated issue rather than repeatedly replying to each new "ping is slow" report.)

**Comment by Atemu** [comment]
I experience this bug without systemd-networkd involved.
It might actually be inside `ping` or another component `ping` depends on.

https://github.com/iputils/iputils/issues/491

**Comment by rpigott** [comment]
networkd is not related. This behavior is entirely within resolved.

**Comment by Atemu** [comment]
I do not use systemd-resolved either.

**Comment by rpigott** [comment]
Then you aren't experiencing this bug.

**Comment by pemensik** [comment]
It might be related to this bug. Reported on Fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=2122942. The reporter is getting timeouts instead of negative response for local addresses, which do not have positive answer. LLMNR needs to be enabled to hit this. It does not cache recent result and timeouts again and again. Negative answer is not considered valid result.

**Comment by pemensik** [comment]
DNR? We want that in Network Manager, would you prepare it there as well?

**Comment by pemensik** [comment]
I still think LLMNR should not be fixed, but disabled. As I have proposed in PR #28263. If there is DNS server supplied for that interface, queries for reverse mapping domains should be sent to it. Always. If there are additional helpers with mdns, that should be done asynchronously and stored in cache only, but should not add visible delay after DNS response were received.

**Comment by rpigott** [comment]
> DNR? We want that in Network Manager, would you prepare it there as well?

No, I don't use network manager.

> I still think LLMNR should not be fixed, but disabled.

These aren't exclusive. As long as it is implemented, it might as well work. Besides, it's the same fix for both and mdns is going nowhere.

 > If there is DNS server supplied for that interface, queries for reverse mapping domains should be sent to it. Always. If there are additional helpers with mdns, that should be done asynchronously and stored in cache only, but should not add visible delay after DNS response were received.

This is a bug. It's getting fixed.
