### ISSUE TITLE
libsystemd doesn't define libcrypt as a dependency

### ISSUE THREAD

**Issue by tbsuht** [systemd/systemd#28161]
### Component

other

### Is your feature request related to a problem? Please describe

I'm trying to cross-compile `libsystemd` for armv8 using [conan](https://github.com/conan-io/conan) package manager (see related [bug report](https://github.com/conan-io/conan-center-index/issues/15101)).

The problem is that this is failing with:
```
../source/meson.build:991:0: ERROR: C shared or static library 'crypt' not found
```

Which is triggered by [this line](https://github.com/systemd/systemd/blob/main/meson.build#L1064).

I'm not experienced with meson but locally this can be fixed for my case with the following, as conan generates `*.pc` files for the dependencies.
```
diff --git a/meson.build.old b/meson.build
index f38385c..dfa1b55 100644
--- a/meson.build.old
+++ b/meson.build
@@ -988,7 +988,7 @@ threads = dependency('threads')
 librt = cc.find_library('rt')
 libm = cc.find_library('m')
 libdl = cc.find_library('dl')
-libcrypt = cc.find_library('crypt')
+libcrypt = dependency('crypt')
 
 crypt_header = conf.get('HAVE_CRYPT_H') == 1 ? '''#include <crypt.h>''' : '''#include <unistd.h>'''
 foreach ident : [
```

Is this a valid fix that can be upstreamed to systemd?

### Describe the solution you'd like

See the given patch, so that libcrypt can be found outside the root-file system.

### The systemd version you checked that didn't have the feature you are asking for

251.4

**Comment by yuwata** [comment]
Fix is waiting in #28165.

**Comment by tbsuht** [comment]
Thanks for the fast fix! For which version(s) can this be expected?

**Comment by yuwata** [comment]
If the fix is merged, I think it is OK to backport it to stable repository, e.g. v252, and v251. Not sure which point releases get the backport.
