### ISSUE TITLE
input_id: function test_pointers can't return an or result

### ISSUE THREAD

**Issue by migcr** [systemd/systemd#2817]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd 228

> …
### openSUSE Tumbleweed

> …

The function test_pointers (src/udev/udev-builtin-input_id.c:) shoud return an or of bits, as the actual source code shows:

`return is_tablet || is_mouse || is_touchpad || is_touchscreen || is_joystick || is_pointing_stick;`

> …

But previously in the same function there is: 

```
        if (has_abs_coordinates) {
                if (stylus_or_pen)
                        is_tablet = true;
                else if (finger_but_no_pen && !is_direct)
                        is_touchpad = true;
                else if (has_mouse_button)
                        /* This path is taken by VMware's USB mouse, which has
                         * absolute axes, but no touch/pressure button. */
                        is_mouse = true;
                else if (has_touch)
                        is_touchscreen = true;
                else if (has_joystick_axes_or_buttons)
                        is_joystick = true;
        }
```

so you can't never have a combination (or) of those.

e.g.: If you use a gamepad  with a touchpad (like Nvidia SHIELD controler) is always reported as a mouse. When it should be reported as a mouse and a joystick.

> …

If you can test a gamepad with a touchpad like the Nvidia SHIELD Controller, you can see the funcion only returns "is_mouse".

> …

**Comment by poettering** [comment]
This code was touched substantially in the recent years, for example here: bc85f8b51d962597360e982811e674c126850f56

The code does various different checks these days. My guess is that this is all fixed by now. if not and this remains relevant, please file a new bug.
