### ISSUE TITLE
systemctl daemon-reexec forgets running services and tries to restart all services

### ISSUE THREAD

**Issue by kubicgruenfeld** [systemd/systemd#28184]
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu 22.04 (on openvz)

### Linux kernel version used

3.10.0-1160.80.1.vz7.191.4 (openvz host kernel)

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

After a systemctl daemon-reexec command, we expected that the existing services would not be affected or restarted, and the state of the systemd daemon should be updated without interrupting the running services.

### Unexpected behaviour you saw

During a regular update of our container environment, systemd (and the related packages libpam-systemd, libsystemd0, libudev1, systemd-sysv, and udev) were updated from 249.11-0ubuntu3.6 to 249.11-0ubuntu3.7. After this update, when the systemctl daemon-reexec command from the postinst script was executed, it seems that systemd forgot all its started children and tried to start nearly every configured service again. This caused conflicts as the old services were still running and the ports couldn't be opened twice.
We could reproduce this with a current version (253) of systemd too.

### Steps to reproduce the problem

Execute the systemctl daemon-reexec command in an openvz container.
Check the status of the services and observe that systemd has forgotten its started children and is trying to start nearly every configured service again.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
See Ubuntu bug report at: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2013543
```

**Comment by bluca** [comment]
You are saying you are on Ubuntu 22.04 but with kernel 3.10? Is that right? It seems weird that a combination like that can even work, that kernel is ancient. The minimum supported version is 3.15.

**Comment by kubicgruenfeld** [comment]
> You are saying you are on Ubuntu 22.04 but with kernel 3.10? Is that right? It seems weird that a combination like that can even work, that kernel is ancient. The minimum supported version is 3.15.

Yes, i know, this looks odd. We are using Virtuozzo and the virtualization hosts are running with a kernel in this version with backports to support modern distributions. Then there are templates to fake a newer kernel version to the guest OS:

```
# cat /vz/template/ubuntu/22.04/x86_64/config/os/default/osrelease 
5.2.0
```

Still, everything works for Ubuntu 20.04 and systemd 245 in these containers.

**Comment by bluca** [comment]
Can you try with a newer kernel? As mentioned the minimum we support is 3.15, older than that and stuff might break

**Comment by bluca** [comment]
Note that 3.10 has been EOL for 6 years now, you really shouldn't run any production workloads on that...

**Comment by kubicgruenfeld** [comment]
These kernels are the currently supported kernels of the product we are using. See https://docs.virtuozzo.com/virtuozzo_advisory_archive/virtuozzo-hybrid-server/index.html

We can't use other kernels than these.

**Comment by bluca** [comment]
Can you reproduce it anywhere else?

**Comment by kubicgruenfeld** [comment]
No, only on openvz hosts.

**Comment by mrc0mmand** [comment]
I read through the original Ubuntu bug report and I can reproduce the issue with `ubuntu-22.04.2-desktop-amd64.iso` in a regular QEMU (KVM) VM. I'll try to debug this a bit further to see what's going on.

**Comment by kubicgruenfeld** [comment]
I did some debugging too. I noticed this logline during the daemon-reexec:
`systemd[1]: Serializing systemd-state to memfd.`

Then i looked for the PID of the systemd process on the virtuozzo host  and started strace on this PID.

`strace -e trace=memfd_create,write -p 972036`

found something interesting:

```
memfd_create("systemd-state", MFD_CLOEXEC) = 22
write(22, "current-job-id=376\nn-installed-j"..., 4096) = 4096
write(22, "es-base=0\nio-accounting-read-ope"..., 4096) = 4096
write(22, "245468 53373716\ncondition-result"..., 4096) = 4096
write(22, "nvocation-id=no\nexported-log-lev"..., 4096) = 4096
write(22, "ult=success\nmain-pid-known=no\nbu"..., 4096) = 4096
write(22, "up-realized=no\ninvocation-id=1be"..., 4096) = 4096
write(22, "o-accounting-read-operations-bas"..., 4096) = 4096
write(22, "o\nn-restarts=0\nflush-n-restarts="..., 4096) = 4096
write(22, "987142859604 7987852\nforbid-rest"..., 4096) = 4096
write(22, "counting-write-bytes-base=0\nio-a"..., 4096) = 4096
write(22, "mestamp=1687987140339654 5467902"..., 4096) = 4096
write(22, "ed-mask=memory pids\ninvocation-i"..., 4096) = 4096
write(22, "ss\nreload-result=success\nmain-pi"..., 4096) = 4096
write(22, "o-accounting-write-bytes-base=0\n"..., 4096) = 4096
write(22, "d-mask=bpf-firewall\nfreezer-stat"..., 4096) = 4096
write(22, "te=running\nresult=success\nreload"..., 4096) = 4096
write(22, "ner=no\nn-restarts=0\nflush-n-rest"..., 4096) = 4096
write(22, "ax=no\nexported-log-extra-fields="..., 4096) = 4096
write(22, "st=no\ncpu-usage-base=0\nio-accoun"..., 4096) = 4096
write(22, "\ncgroup-realized=no\ninvocation-i"..., 4096) = 4096
write(22, "mestamp=1687987140260844 5389095"..., 4096) = 4096
write(22, "lt=success\nreload-result=success"..., 4096) = 4096
write(22, "rate-limit-burst=no\ncpu-usage-ba"..., 4096) = 4096
write(22, "ns-base=0\ncgroup-realized=no\ncgr"..., 4096) = 4096
write(22, "ted-invocation-id=no\nexported-lo"..., 4096) = 4096
write(22, "forbid-restart=no\ncondition-time"..., 4096) = 4096
write(22, "memory devices pids\nref-uid=995\n"..., 4096) = 4096
write(22, "id=no\nexported-log-level-max=no\n"..., 4096) = 4096
write(22, "unting-read-bytes-base=0\nio-acco"..., 4096) = 4096
write(22, "mote-cryptsetup.target\nstate=act"..., 4096) = 4096
write(22, "k=bpf-firewall\nfreezer-state=run"..., 4096) = 4096
write(22, "imit-interval=no\nexported-log-ra"..., 4096) = 4096
write(22, "tes-base=0\nio-accounting-write-b"..., 4096) = 4096
write(22, "p-realized=yes\ncgroup-realized-m"..., 4096) = 4096
write(22, "-extra-fields=no\nexported-log-ra"..., 4096) = 4096
write(22, "state=running\n\ndev-mqueue.mount\n"..., 4096) = 4096
write(22, "tions-base=0\ncgroup-realized=no\n"..., 2347) = 2347
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c990, 0, 0x100, 0, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c970, 0, 0x100, 0, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(6, "1\n", 2)                      = 2
write(7, "1\n", 2)                      = 2
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0x55afa6489360, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c9c0, 0x2, 0x100, 0, 0x73636f72702e70) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c530, 0, 0x100, 0, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c530, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c530, 0, 0x100, 0x5, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c530, 0, 0x100, 0x11, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c260, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(28, "1395\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c260, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(28, "1424\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c1f0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(29, "1407\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c1f0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(29, "1408\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c2d0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(27, "405\n", 4)                   = 4
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c2d0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(27, "2084\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c2d0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(27, "2085\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c2d0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(27, "2086\n", 5)                  = 5
syscall_0x1b7(0xffffff9c, 0x7ffe9cc4c2d0, 0, 0x100, 0xe, 0x2f70756f726763) = -1 ENOSYS (Function not implemented)
write(27, "2087\n", 5)
```

Then I compared this with a similar strace on my Thinkpad (same OS, same systemd with kernel 5.19). These ENOSYS messages weren't there.

Looked up the syscall 0x1b7, which is 439 in decimal notation, which is faccessat2: https://github.com/torvalds/linux/blob/89181f544ffa4da682b0145738342f9b78b9e8dc/arch/x86/entry/syscalls/syscall_64.tbl#L363C11-L363C11

This syscall is at least unsupported on default openvz kernels: https://github.com/OpenVZ/vzkernel/blob/vz7-latest/arch/x86/syscalls/syscall_64.tbl

I could confirm, that the syscall isn't supported on our Virtuozzo hosts.

This may or may not be related to the problem. I am not very familiar with syscalls.
I've found this commit https://github.com/systemd/systemd/commit/bcf08acbffdee0d6360d3c31d268e73d0623e5dc and compiled systemd 245 on my openvz guest, the behaviour was the same and the strace looked similar. 

Since I am unsure if this leads to anything, I decided to stop for now. I hope it is helpful.

**Comment by mrc0mmand** [comment]
After some digging I noticed that the Ubuntu live image is booted with a strange cmdline:

```
# cat /proc/cmdline 
BOOT_IMAGE=/casper/vmlinuz layerfs-path=minimal.standard.live.squashfs --- quiet splash
```

And the "strangeness" is then passed to the systemd process:
```
# cat /proc/1/cmdline | tr '\0' '\n' 
/lib/systemd/systemd
---
splash
--system
--deserialize
54
```

So my guess would be that the `--deserialize` argument with the serialized memfd is not parsed by systemd thanks to `---` and hence we start with a clean slate. When I edit the kernel cmdline and drop `---` from it `systemctl daemon-reexec` then works as expected.

**Comment by mrc0mmand** [comment]
Maybe we should shuffle the arguments around in `do_reexec()` to put the `--deserialize` stuff first and then the arbitrary arguments we might get from the kernel cmdline last to avoid this.

**Comment by bluca** [comment]
Yeah, that sounds like a good idea

**Comment by kubicgruenfeld** [comment]
Seems to be an other issue than the one on openvz:

```
# cat /proc/1/cmdline | tr '\0' '\n'
init
-z
```

**Comment by mrc0mmand** [comment]
> Seems to be an other issue than the one on openvz:
> 
> ```
> # cat /proc/1/cmdline | tr '\0' '\n'
> init
> -z
> ```

I assume that's PID 1 from the host? Otherwise I'm confused why it's not systemd.

**Comment by kubicgruenfeld** [comment]
> > Seems to be an other issue than the one on openvz:
> > ```
> > # cat /proc/1/cmdline | tr '\0' '\n'
> > init
> > -z
> > ```
> 
> I assume that's PID 1 from the host? Otherwise I'm confused why it's not systemd.

Actually it is systemd on the guest:

```
# ls -lsha /sbin/init 
0 lrwxrwxrwx 1 root root 20 Mar 27 19:54 /sbin/init -> /lib/systemd/systemd
```

The cmdline from the host looks like this:

```
# cat /proc/1/cmdline | tr '\0' '\n'
/usr/lib/systemd/systemd
--switched-root
--system
--deserialize
```

**Comment by mrc0mmand** [comment]
I spun up a local OpenVZ installation and given that and the output above I'd say the issue should get resolved by #28193 as well.

The issue here is that we get started with `init -z` as shown above:
```
[root@localhost ~]# vzctl enter 1
entered into CT 1
root@localhost:/# cat /proc/1/cmdline | tr '\0' '\n'
init
-z
```

And once we call `systemctl reexecute` we'll append `--deserialize=` after existing arguments, which is `-z` in this case:
```
# cat /proc/1/cmdline | tr '\0' '\n'
/lib/systemd/systemd
-z
      
--system
--deserialize
21
```

But that's an issue, since we fall-through on sysvinit arguments (`-z` in this case) and if we're running as PID 1 we'll stop parsing further arguments:

https://github.com/systemd/systemd/blob/49bf8bd57a1c44583cfbc5e68a8b43b59f2f9eca/src/core/main.c#L1053-L1064

#28193 should address this, as it reorders the `--deserialize=` argument before the "old" ones.

**Comment by kubicgruenfeld** [comment]
Thanks for the effort!
I will try to build systemd with the changes later today in our environment. It's still odd to me, since it works on Ubuntu 20.04 on openvz and the init arguments are the same.

**Comment by mrc0mmand** [comment]
> Thanks for the effort! I will try to build systemd with the changes later today in our environment. It's still odd to me, since it works on Ubuntu 20.04 on openvz and the init arguments are the same.

I think that's because of 846f1da465beda990c1c01346311393f485df467 after which we propagate the original command line to the newly exec'ed process.

**Comment by kubicgruenfeld** [comment]
> > Thanks for the effort! I will try to build systemd with the changes later today in our environment. It's still odd to me, since it works on Ubuntu 20.04 on openvz and the init arguments are the same.
> 
> I think that's because of [846f1da](https://github.com/systemd/systemd/commit/846f1da465beda990c1c01346311393f485df467) after which we propagate the original command line to the newly exec'ed process.

Yes, i can confirm this. Unfortunately the changes from https://github.com/systemd/systemd/pull/28193 don't fixes the issue for me on openvz. But I got it working without the line `filter_args(args, &i, argv, argc);` (https://github.com/systemd/systemd/blob/v253/src/core/main.c#L1854) completely removed.

Ubuntu 22.04 on openvz with systemd 249 from Ubuntu repo:

```
# ps -p 1 -o command=
init -z
# ps -p 1 -o command=
/lib/systemd/systemd -z        --system --deserialize 16
```

Ubuntu 22.04 on openvz with systemd 249 on openvz with changes from https://github.com/systemd/systemd/pull/28193:

```
# ps -p 1 -o command=
init -z
# /bin/systemctl daemon-reexec 
# ps -p 1 -o command=
/lib/systemd/systemd --system --deserialize 21 -z
```

Ubuntu 22.04 on openvz with `filter_args(args, &i, argv, argc);` removed:

```
# ps -p 1 -o command=
init -z
# /bin/systemctl daemon-reexec 
# ps -p 1 -o command=
/lib/systemd/systemd --system --deserialize 21
```

So yes, the patch puts the "-z" argument at the end. But since this isn't a valid argument, as far as i can see, it breaks the reexecution and renders the system in a failed state. Withouth the arguments from the init process from before the deserialization it works fine. Ubuntu or Debian seems to have [846f1da] backported in their 249 release.

**Comment by mrc0mmand** [comment]
> So yes, the patch puts the "-z" argument at the end. But since this isn't a valid argument, as far as i can see, it breaks the reexecution and renders the system in a failed state. Withouth the arguments from the init process from before the deserialization it works fine. Ubuntu or Debian seems to have [[846f1da](https://github.com/systemd/systemd/commit/846f1da465beda990c1c01346311393f485df467)] backported in their 249 release.

Hmpf, that's strange, systemd should just ignore the `-z` argument on reexec when running as PID 1. What exactly is a 'failed state' in this case? Is it the same scenario as before (i.e. the deserialization gets skipped) or it's something else?

**Comment by kubicgruenfeld** [comment]
The failed state looks exactly as the initial one.

Meanwhile i found the origin of the "-z" argument: https://github.com/OpenVZ/libvzctl/blob/master/lib/env.c#L905

The post-install scripts from Virtuozzo for systemd based distributions include this hack:

```
# Setup systemd as /sbin/init
rm -f sbin/init > /dev/null 2>&1
ln -s ../lib/systemd/systemd sbin/init > /dev/null 2>&1
```

When replacing the /sbin/init process in the container with the following, everything is working nicely:

```
#!/bin/bash

# This is the path to the actual systemd binary
SYSTEMD_BIN="/lib/systemd/systemd"

# Strip out -z argument
args=()
for arg in "$@"; do
    [[ $arg != "-z" ]] && args+=("$arg")
done

# Execute systemd with the remaining arguments
exec "$SYSTEMD_BIN" "${args[@]}"
```

So, the initial problem isn't coming from systemd, not sure if the behaviour justify a change in systemd.

**Comment by mrc0mmand** [comment]
Interesting. I'll play around with it tomorrow again to see what's going on.

**Comment by mrc0mmand** [comment]
I have a Ubuntu 22.04 container on top of OpenVZ 7 and with [06afda6](https://github.com/systemd/systemd/commit/06afda6b38d5d730fca3c65449096425933272bc) cherry-picked [0] on top of both v249.16 and v249.11 stable tags I can't seem to reproduce the issue anymore:

```
# vzctl enter 1000
entered into CT 1000
# systemctl --version
systemd 249 (249.11-1-g918b6b0)
...
# cat /proc/1/cmdline | tr '\0' '\n'
init
-z
      
# systemctl daemon-reexec
# cat /proc/1/cmdline | tr '\0' '\n'
/usr/lib/systemd/systemd
--system
--deserialize
21
-z
      
# journalctl -e
...
Jun 30 13:14:42 localhost.localdomain systemd[1]: Started OpenBSD Secure Shell server.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Reached target Multi-User System.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Reached target Graphical Interface.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Starting Record Runlevel Change in UTMP...
Jun 30 13:14:42 localhost.localdomain systemd[1]: Starting Tell that Container is started...
Jun 30 13:14:42 localhost.localdomain systemd[1]: vzfifo.service: Deactivated successfully.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Started Tell that Container is started.
Jun 30 13:14:42 localhost.localdomain systemd[1]: systemd-update-utmp-runlevel.service: Deactivated successfully.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Finished Record Runlevel Change in UTMP.
Jun 30 13:14:42 localhost.localdomain systemd[1]: Startup finished in 333ms.
Jun 30 13:14:42 localhost.localdomain systemd[1]: dmesg.service: Deactivated successfully.
Jun 30 13:15:58 localhost.localdomain systemd[1]: Reexecuting.
Jun 30 13:15:58 localhost.localdomain systemd[1]: systemd-logind.service: unit configures an IP firewall, but the local system does not support BPF/cgroup firewalling.
Jun 30 13:15:58 localhost.localdomain systemd[1]: (This warning is only shown for the first unit using IP firewalling.)
# systemctl status
● localhost.localdomain
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Fri 2023-06-30 13:14:42 CEST; 1min 50s ago
...
```

I'm not sure if there's something I'm missing. I simply rebuilt the respective tags from https://github.com/systemd/systemd-stable in the container, installed it with `ninja -C build install`, and restarted the container (`vzctl stop/vzctl start`). When I drop [06afda6](https://github.com/systemd/systemd/commit/06afda6b38d5d730fca3c65449096425933272bc) everything starts failing again.

[0]
<details>
<summary>patch</summary>

```diff
diff --git a/src/core/main.c b/src/core/main.c
index 40cf3ddea2..3251fd3af6 100644
--- a/src/core/main.c
+++ b/src/core/main.c
@@ -1816,13 +1816,17 @@ static void do_reexecute(
                 xsprintf(sfd, "%i", fileno(arg_serialization));
 
                 i = 1;         /* Leave args[0] empty for now. */
-                filter_args(args, &i, argv, argc);
 
+                /* Put our stuff first to make sure it always gets parsed in case
+                 * we get weird stuff from the kernel cmdline (like --) */
                 if (switch_root_dir)
                         args[i++] = "--switched-root";
                 args[i++] = arg_system ? "--system" : "--user";
                 args[i++] = "--deserialize";
                 args[i++] = sfd;
+
+                filter_args(args, &i, argv, argc);
+
                 args[i++] = NULL;
 
                 assert(i <= args_size);
diff --git a/test/TEST-01-BASIC/test.sh b/test/TEST-01-BASIC/test.sh
index d42c0df9a0..dbca6ac90b 100755
--- a/test/TEST-01-BASIC/test.sh
+++ b/test/TEST-01-BASIC/test.sh
@@ -6,6 +6,11 @@ IMAGE_NAME="basic"
 RUN_IN_UNPRIVILEGED_CONTAINER=${RUN_IN_UNPRIVILEGED_CONTAINER:-yes}
 TEST_REQUIRE_INSTALL_TESTS=0
 
+# Check if we can correctly deserialize if the kernel cmdline contains "weird" stuff
+# like an invalid argument, "end of arguments" separator, or a sysvinit argument (-z)
+# See: https://github.com/systemd/systemd/issues/28184
+KERNEL_APPEND="foo -- -z bar --- baz $KERNEL_APPEND"
+
 # shellcheck source=test/test-functions
 . "${TEST_BASE_DIR:?}/test-functions"
 
-- 
2.34.1
```

**Comment by kubicgruenfeld** [comment]
A colleague could reproduce that the patch is indeed working as intendend.
Thank you.
