### ISSUE TITLE
Allow enabling IPv6PrivacyExtensions globally

### ISSUE THREAD

**Issue by yu-re-ka** [systemd/systemd#28186]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

I'm frustrated that it is so complicated to enable IPv6 privacy extensions globally on my system, when interfaces are managed by systemd-networkd

### Describe the solution you'd like

One way would be to make the default of the IPv6PrivacyExtensions option configurable globally.
However that doesn't seem ideal because it seems like a too specific workaround.
A generic solution to provide default values that apply to all interfaces, would be great.

### Describe alternatives you've considered

I currently write IPv6PrivacyExtensions into each .network file I create, however this is error prone because I might forget to set the option when creating a new .network file.

In my config management, the .network file might also originate from another module, that generates .network files for multiple hosts, but I only want to enable the IPv6 privacy extensions globally on one host.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by yuwata** [comment]
Waiting in #28191. If possible, please test the PR.
