### ISSUE TITLE
Please consider allowing `~` in ReadWritePaths

### ISSUE THREAD

**Issue by Undef-a** [systemd/systemd#28190]
### Component

systemd

### Is your feature request related to a problem? Please describe

Now that `ReadWritePaths` is available to user units when using `PrivateUsers` it'd be good to be able to generically be able to restrict a service's access to the user's home directory. For example a voicemail parsing daemon would only have access to it's configuration and downloaded files under the user's home directory.

### Describe the solution you'd like

I believe this would be best solved using the same method as `WorkingDirectory`:
> If set to "~", the home directory of the user specified in User= is used. If not set, defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user.

### Describe alternatives you've considered

I'm currently hard coding this, however this fails for the use-case of a distribution generated unit file which has to account for multiple usernames.

### The systemd version you checked that didn't have the feature you are asking for

253-3 (Debian Trixie)

**Comment by poettering** [comment]
just use `%h` specifier? see systemd.unit(5)
