### ISSUE TITLE
There is a double-free in systemd-networkd caused by router advertisements with bogus captive portal options

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#28229]
While I was sending bogus RAs (as one does) I noticed that `systemd-networkd` went sideways somewhere:
```sh
systemd-networkd[169]: =================================================================
systemd-networkd[169]: ==169==ERROR: AddressSanitizer: attempting double-free on 0x602000006350 in thread T0:
systemd-networkd[169]:     #0 0x7fe74c2b9388 in __interceptor_free.part.0 (/lib64/libasan.so.8+0xb9388)
systemd-networkd[169]:     #1 0x642f26 in link_free ../src/network/networkd-link.c:199
systemd-networkd[169]:     #2 0x643947 in link_unref ../src/network/networkd-link.c:220
systemd-networkd[169]:     #3 0x41fb62 in manager_free ../src/network/networkd-manager.c:626
systemd-networkd[169]:     #4 0x412412 in manager_freep ../src/network/networkd-manager.h:123
systemd-networkd[169]:     #5 0x413925 in run ../src/network/networkd.c:24
systemd-networkd[169]:     #6 0x413a4f in main ../src/network/networkd.c:119
systemd-networkd[169]:     #7 0x7fe74964a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)
systemd-networkd[169]:     #8 0x7fe74964a5c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8)
systemd-networkd[169]:     #9 0x411764 in _start (/usr/lib/systemd/systemd-networkd+0x411764)
systemd-networkd[169]: 0x602000006350 is located 0 bytes inside of 4-byte region [0x602000006350,0x602000006354)
systemd-networkd[169]: freed by thread T0 here:
systemd-networkd[169]:     #0 0x7fe74c2b9388 in __interceptor_free.part.0 (/lib64/libasan.so.8+0xb9388)
systemd-networkd[169]:     #1 0x683532 in ndisc_router_process_captive_portal ../src/network/networkd-ndisc.c:737
systemd-networkd[169]:     #2 0x685655 in ndisc_router_process_options ../src/network/networkd-ndisc.c:873
systemd-networkd[169]:     #3 0x6893b6 in ndisc_router_handler ../src/network/networkd-ndisc.c:1097
systemd-networkd[169]:     #4 0x689945 in ndisc_handler ../src/network/networkd-ndisc.c:1127
systemd-networkd[169]:     #5 0x7cae7a in ndisc_callback ../src/libsystemd-network/sd-ndisc.c:42
systemd-networkd[169]:     #6 0x7cd610 in ndisc_handle_datagram ../src/libsystemd-network/sd-ndisc.c:197
systemd-networkd[169]:     #7 0x7ce7a9 in ndisc_recv ../src/libsystemd-network/sd-ndisc.c:251
systemd-networkd[169]:     #8 0x7fe74b349d50 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
systemd-networkd[169]:     #9 0x7fe74b353529 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
systemd-networkd[169]:     #10 0x7fe74b354644 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
systemd-networkd[169]:     #11 0x7fe74b3549c5 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
systemd-networkd[169]:     #12 0x4137ef in run ../src/network/networkd.c:112
systemd-networkd[169]:     #13 0x413a4f in main ../src/network/networkd.c:119
systemd-networkd[169]:     #14 0x7fe74964a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)
systemd-networkd[169]: previously allocated by thread T0 here:
systemd-networkd[169]:     #0 0x7fe74c2ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
systemd-networkd[169]:     #1 0x7fe74aebbf3c in memdup_suffix0 ../src/basic/alloc-util.c:33
systemd-networkd[169]:     #2 0x7fe74b00608a in make_cstring ../src/basic/string-util.c:1352
systemd-networkd[169]:     #3 0x68359b in ndisc_router_process_captive_portal ../src/network/networkd-ndisc.c:741
systemd-networkd[169]:     #4 0x685655 in ndisc_router_process_options ../src/network/networkd-ndisc.c:873
systemd-networkd[169]:     #5 0x6893b6 in ndisc_router_handler ../src/network/networkd-ndisc.c:1097
systemd-networkd[169]:     #6 0x689945 in ndisc_handler ../src/network/networkd-ndisc.c:1127
systemd-networkd[169]:     #7 0x7cae7a in ndisc_callback ../src/libsystemd-network/sd-ndisc.c:42
systemd-networkd[169]:     #8 0x7cd610 in ndisc_handle_datagram ../src/libsystemd-network/sd-ndisc.c:197
systemd-networkd[169]:     #9 0x7ce7a9 in ndisc_recv ../src/libsystemd-network/sd-ndisc.c:251
systemd-networkd[169]:     #10 0x7fe74b349d50 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
systemd-networkd[169]:     #11 0x7fe74b353529 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
systemd-networkd[169]:     #12 0x7fe74b354644 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
systemd-networkd[169]:     #13 0x7fe74b3549c5 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
systemd-networkd[169]:     #14 0x4137ef in run ../src/network/networkd.c:112
systemd-networkd[169]:     #15 0x413a4f in main ../src/network/networkd.c:119
systemd-networkd[169]:     #16 0x7fe74964a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)
systemd-networkd[169]: SUMMARY: AddressSanitizer: double-free (/lib64/libasan.so.8+0xb9388) in __interceptor_free.part.0
```
It was introduced in https://github.com/systemd/systemd/pull/28132.

**Comment by rpigott** [comment]
Any suggestion for how to add a test? I couldn't find any ipv6ra examples in systemd-networkd-tests.py.

**Comment by evverx** [comment]
I don't think at this point the router advertisements are covered. I generate stuff and send it to networkd using scapy but it would probably be better to bring `radvd` or something like that to the systemd-networkd-tests test suite to start testing it normally and then maybe extend it with some sort of fuzzing. @mrc0mmand @yuwata what do you think? Generally every time this code changes it breaks one way or another. The latest example would be https://github.com/systemd/systemd/issues/25891.

**Comment by rpigott** [comment]
Can you try #28232?

**Comment by mrc0mmand** [comment]
> I don't think at this point the router advertisements are covered. I generate stuff and send it to networkd using scapy but it would probably be better to bring `radvd` or something like that to the systemd-networkd-tests test suite to start testing it normally and then maybe extend it with some sort of fuzzing. @mrc0mmand @yuwata what do you think? Generally every time this code changes it breaks one way or another. The latest example would be #25891.

Hehe, just yesterday I was looking for the next fuzzing *target* and this definitely sounds like something we should cover next. Extending the networkd test suite would make sense too, though I'd have to read through some docs first as my knowledge in this particular area is a bit rudimentary.

**Comment by evverx** [comment]
> Can you try https://github.com/systemd/systemd/pull/28232?

Thanks! I'll try to build systemd with that PR applied a bit later today.

> I was looking for the next fuzzing target and this definitely sounds like something we should cover next

To be fair I added a fuzz target covering https://storage.googleapis.com/oss-fuzz-coverage/systemd/reports/20230702/linux/src/systemd/src/libsystemd-network/ndisc-router.c.html#L72 back in the day so the basic parser is more or less covered and infinite loops are gone :-) The problem is that networkd handles that stuff in other places too and they are out of reach at this point.

**Comment by evverx** [comment]
> it would probably be better to bring radvd

Looks like https://github.com/radvd-project/radvd/pull/141 hasn't been officially released yet so `radvd` should be built from source by the CI and I can't say I'm a fan. `scapy` can be used instead (and as far as I can tell https://github.com/systemd/systemd/pull/22532 brings it (even though I don't think it's needed there)). Either way unfortunately there is no easy way to add tests covering that stuff. Without that it's like whack-a-mole.

**Comment by mrc0mmand** [comment]
> > it would probably be better to bring radvd
> 
> Looks like [radvd-project/radvd#141](https://github.com/radvd-project/radvd/pull/141) hasn't been officially released yet so `radvd` should be built from source by the CI and I can't say I'm a fan. `scapy` can be used instead (and as far as I can tell #22532 brings it (even though I don't think it's needed there)). Either way unfortunately there is no easy way to add tests covering that stuff. Without that it's like whack-a-mole.

I definitely agree that this should get some test coverage, and will look into that as soon as possible. Building radvd in CI shouldn't be a problem - I have to already build [a couple](https://github.com/systemd/systemd-centos-ci/blob/main/vagrant/boxes/Vagrantfile_archlinux_systemd#L69-L94) of tools for the networkd test suite, so adding one more into the mix won't make a difference.

**Comment by mrc0mmand** [comment]
> > it would probably be better to bring radvd
> 
> Looks like [radvd-project/radvd#141](https://github.com/radvd-project/radvd/pull/141) hasn't been officially released yet so `radvd` should be built from source by the CI and I can't say I'm a fan. `scapy` can be used instead (and as far as I can tell #22532 brings it (even though I don't think it's needed there)). Either way unfortunately there is no easy way to add tests covering that stuff. Without that it's like whack-a-mole.

I was thinking about this and I wonder if it would make sense to introduce a new test similar to TEST-21-DFUZZER, but with scapy. With radvd we'd get coverage for the one particular implementation, but generating bogus entries would be difficult. With scapy we'd have more flexibility and we could cover significantly more code, but I guess the setup would be slightly more complex.

**Comment by evverx** [comment]
>  if it would make sense to introduce a new test similar to TEST-21-DFUZZER, but with scapy

I think it would certainly make sense to bring something like that eventually. It could cover resolved too. The problem is that it can't be used to make sure that the code works correctly. (For example as far as I can remember the first attempt to fix some resolved UAFs made the fuzzer and ASan happy but resolved just stopped resolving services and there were no tests to even catch that regression). The idea was to use `radvd` to make sure that that part of networkd can handle normal RAs and then fuzz it to make sure all sorts of weird packets can be handled as well. scapy can send normal RAs too though.

Another problem is that fuzzing makes coverage reports look impressive but it makes it really hard to figure out what's actually covered. I think the "fuzzing" coverage should be kept separately.

**Comment by mrc0mmand** [comment]
> > if it would make sense to introduce a new test similar to TEST-21-DFUZZER, but with scapy
> 
> I think it would certainly make sense to bring something like that eventually. It could cover resolved too. The problem is that it can't be used to make sure that the code works correctly. (For example as far as I can remember the first attempt to fix some resolved UAFs made the fuzzer and ASan happy but resolved just stopped resolving services and there were no tests to even catch that regression). The idea was to use `radvd` to make sure that that part of networkd can handle normal RAs and then fuzz it to make sure all sorts of weird packets can be handled as well. scapy can send normal RAs too though.
> 
> Another problem is that fuzzing makes coverage reports look impressive but it makes it really hard to figure out what's actually covered. I think the "fuzzing" coverage should be kept separately.

Makes sense, let's start with radvd then.

**Comment by evverx** [comment]
I've just opened https://github.com/systemd/systemd/issues/28277 and I give up.
