### ISSUE TITLE
bootctl -R should be renamed to -r, and -R should print the disk device

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#28221]
### Is your feature request related to a problem? Please describe

The NEWS entry says `cfdisk $(bootctl -R)`, but this opens the partition and is not useful.
I think we should make `-R` show the whole disk, and let `-r` show just the single partition.
It should be lowercase in analogy to `-p` and `-x` which also show partitions.

Setting as `rc-blocker` because of the proposed interface change.

**Comment by poettering** [comment]
uh, the news file is wrong indeed, the idea was that -R shows the partition block device and -RR shows the whole block device.

**Comment by bluca** [comment]
so this is only a documentation issue for the news entry?
