### ISSUE TITLE
Make `ProtectControlGroups=` option available in per-user instances.

### ISSUE THREAD

**Issue by black-desk** [systemd/systemd#28220]
### Component

systemd

### Is your feature request related to a problem? Please describe

In man page of `systemd.exec(5)`

> ProtectControlGroups=
> ...
> Except for container managers no services should require write access to the control groups hierarchies;
> it is hence recommended to turn this on for most services.
> ...

Systemd recommend to turn `ProtectControlCgroups` on. But we cannot do it in per-user instances as the per-user instance do not have the capability to create mount namespace while keeping uid/gid mapping.

### Describe the solution you'd like

Maybe systemd can add a helper binary with extra capability to support this feature in per-user instances?

As that binary will only do very simple job as creating new mount namespace and remounting /sys/fs/cgroup as read only, it seems to be secure, as this behavior is not going to take any arguments.

I am not sure about other options like `ReadOnlyPaths=` can be support in per-user instances in this way or not.

### Describe alternatives you've considered

Maybe systemd can add a helper binary with extra capability to support this feature in per-user instances?

As that binary will only do very simple job as creating new mount namespace and remounting /sys/fs/cgroup as read only, it seems to be secure, as this behaivor is 

I am not sure about other options like `ReadOnlyPaths=` can be support in per-user instances in this way or not.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by bluca** [comment]
Use PrivateUsers=yes, this will become the default from v254 already when sandboxing is specified

**Comment by black-desk** [comment]
I took a look at the document of `PrivateUsers`.  I don't think this configuration could be applied to a normal per-user instance.

In the document:

> If true, sets up a new user namespace for the executed processes and configures a minimal user and group mapping, that maps the "root" user and group as well as the unit's own user and group to themselves and everything else to the "nobody" user and group.

When a user wants to use docker, which requires that user in group `docker`, in a shell is launched by per-user instance with `PrivateUsers` enabled, it will failed to connect to docker daemon as the `docker` group is mapped to nobody in that  user namespace.

And what do you mean by `when sandboxing is specified`?

**Comment by bluca** [comment]
Use it on individual services, not the whole instance

**Comment by Xtricman** [comment]
Maybe we can unshare user namespace twice？
The first level maps 0 to the real uid, then we got full capabilities to mount a private /sys/fs/cgroup instance.
The second level maps real uid to 0(which is just the real uid).
But of course this would either making all mounts locked together or current user ns not owning current mount/cgroup ns.
