### ISSUE TITLE
Chokes on byte-order-mark, misreports as "Assignment outside of section. Ignoring."

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2823]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229, git
### In case of bug report: Expected behaviour you didn't see

When reading a service file with byte order mark, system should either skip the BOM or emit a helpful error message.
### In case of bug report: Unexpected behaviour you saw

The warning is "[file:1] Assignment outside of section. Ignoring." This is especially unfortunate because the BOM is detected correctly by most editors, and thus becomes invisible to the user (which then complain, 'what assignment?').
### In case of bug report: Steps to reproduce the problem

```
echo -e '\uFEFF\n[Service]\nExecStart=/bin/true' > test.service
./systemd-analyze --user verify test.service
```

**Comment by keszybz** [comment]
I'd vote for allowing BOMs. They are useless, but meh, some editors will occasionally insert them and it's most helpful to users to silently ignore them.

**Comment by poettering** [comment]
what concerns me a bit is that we have a couple of other parsers (such as the env file parsers) where the BOM check should probably be added too...

**Comment by keszybz** [comment]
Indeed.
