### ISSUE TITLE
mount-monitor-dispatch delays initrd after being ratelimited too early

### ISSUE THREAD

**Issue by ElvishJerricco** [systemd/systemd#28264]
### systemd version the issue has been seen with

253.2-1.fc38

### Used distribution

Fedora Linux 38 (Cloud Edition)

### Linux kernel version used

6.2.9-300.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Mount units in initrd should start promptly.

### Unexpected behaviour you saw

Mount units are delayed because the `mount-monitor-dispatch` event source becomes rate limited extremely early. It isn't by much (a smidge less than a second), but it is consistent, at least on Fedora and NixOS. The majority of this delay is spent idle, in a log gap between `Finished systemd-fsck-root.service` and `Event source 0x55a7a0cda480 (mount-monitor-dispatch) left rate limit state.`

I added a log statement to `mount_dispatch_io` to see how often it was firing, but it only seemed to fire one time before I got this message: `Event source 0x55a7a0cda480 (mount-monitor-dispatch) entered rate limit state.` Once it leaves rate limit state, boot finally proceeds with `sysroot.mount`. It seems that a single event firing at the very beginning of boot is causing `mount-monitor-dispatch` to rate limit, which is causing `sysroot.mount` to be delayed by nearly one second.

This can be worked around by setting the manager environment variable `SYSTEMD_DEFAULT_MOUNT_RATE_LIMIT_BURST` to something larger, like 40, but this doesn't really make sense to me. The default is 5, and the event is only firing once as far as I can tell. It shouldn't be rate limited in the first place.

### Steps to reproduce the problem

Boot a system with systemd in initrd, and use `rd.systemd.log_level=debug` to see the rate limiting events for `mount-monitor-dispatch`. This issue does occur without `rd.systemd.log_level=debug`, but there is no logging to indicate why.

### Additional program output to the terminal or log subsystem illustrating the issue

Full systemd log during initrd: https://gist.github.com/ElvishJerricco/280a3710d2a8399d4e7c8d67e3ee93fa

```sh
Jul 05 21:16:50.041706 localhost systemd[1]: Finished systemd-fsck-root.service - File System Check on /dev/disk/by-uuid/94fc4136-6c15-43b0-8d86-094c126ee7d4.
Jul 05 21:16:50.726770 localhost systemd[1]: Event source 0x55a7a0cda480 (mount-monitor-dispatch) left rate limit state.
Jul 05 21:16:50.726896 localhost systemd[1]: sys-kernel-config.mount: ConditionCapability=CAP_SYS_RAWIO succeeded.
Jul 05 21:16:50.726910 localhost systemd[1]: sys-kernel-config.mount: ConditionPathExists=/sys/kernel/config succeeded.
Jul 05 21:16:50.727123 localhost systemd[1]: Failed to read pids.max attribute of root cgroup, ignoring: No data available
Jul 05 21:16:50.727193 localhost systemd[1]: sys-kernel-config.mount: About to execute /usr/bin/mount configfs /sys/kernel/config -t configfs -o nosuid,nodev,noexec
Jul 05 21:16:50.727437 localhost systemd[1]: sys-kernel-config.mount: Forked /usr/bin/mount as 566
Jul 05 21:16:50.736369 localhost systemd[1]: sys-kernel-config.mount: Changed dead -> mounting
Jul 05 21:16:50.736392 localhost systemd[1]: Mounting sys-kernel-config.mount - Kernel Configuration File System...
Jul 05 21:16:50.737079 localhost systemd[1]: Failed to read pids.max attribute of root cgroup, ignoring: No data available
Jul 05 21:16:50.737132 localhost systemd[1]: sysroot.mount: About to execute /usr/bin/mount /dev/disk/by-uuid/94fc4136-6c15-43b0-8d86-094c126ee7d4 /sysroot -o subvol=root,ro
Jul 05 21:16:50.737266 localhost systemd[1]: sysroot.mount: Forked /usr/bin/mount as 567
Jul 05 21:16:50.737390 localhost systemd[1]: sysroot.mount: Changed dead -> mounting
Jul 05 21:16:50.737401 localhost systemd[1]: Mounting sysroot.mount - /sysroot...
```

**Comment by ElvishJerricco** [comment]
I discovered this issue while working on an unrelated issue. This bug accidentally prevents the other issue, but only *most* of the time. Sometimes the rate limiting happens a little later and `/sysroot` gets mounted promptly, which allows the other issue I'm messing with to happen as expected.

**Comment by ElvishJerricco** [comment]
So, it appears to be somewhat fixed on `main` now. I bisected it and found that https://github.com/systemd/systemd/pull/27525/commits/21dd1de659935c829a3776b6772f803c2eb4eae3 is the commit that improved things. Not exactly sure what to make of that.

**Comment by poettering** [comment]
OK, let's close. It might make sense to raise the limits eventually if this comes up again. But the credentials mounts are largely suppressed now, hence let's not use it as reason to bump this just yet.
