### ISSUE TITLE
failure to set 0640 for lightdm.log within /var/log/lightdm using systemd-tmpfiles service

### ISSUE THREAD

**Issue by ipatch** [systemd/systemd#28302]
### systemd version the issue has been seen with

253

### Used distribution

arch linux

### Linux kernel version used

Linux rogue 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

expecting to see the created log file of `/var/log/lightdm/lightdm.log` with a file perms of root:adm and of 0640

### Unexpected behaviour you saw

the file `/var/log/lightdm/lightdm.log` on boot has the perms of 0600 with root:root

### Steps to reproduce the problem

create the below file, `/etc/tmpfiles.d/lightdm.conf` it is my understanding that the settings in this directory will take precedence over all other configuration settings.

```
# /etc/tmpfiles.d/lightdm.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

#--
# NOTE: ipatch, my custom settings for lightdm
# sudo systemctl status systemd-tmpfiles-setup.service
# /etc/tmpfiles.d/lightdm.conf
#-
# https://developers.redhat.com/blog/2016/09/20/managing-temporary-files-with-systemd-tmpfiles-on-rhel7#configuration_files
#-
d /var/log/lightdm 0755 root adm -
f /var/log/lightdm/lightdm.log 0640 root adm -
f /var/log/lightdm/seat0-greeter.log 0640 root adm -
f /var/log/lightdm/x-0.log 0640 root adm -

# NOTE: ipatch, no bueno NO WORK! 👇
# the below line does NOT glob all *.log files but rather creates a literal `*.log` file BOOOO!
# f /var/log/lightdm/*.log 0640 root adm -

# Set permissions for all files in /var/log/lightdm
# Use `Z` to match all files in the directory recurisvely
Z /var/log/lightdm/* 0640 root adm -


# f /var/log/Xorg.0.log 0664 root adm -
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
total 28K
drwxr-xr-x+  2 root adm  4.0K Jul  7 16:25 ./
drwxr-xr-x+ 15 root adm  4.0K Jul  7 16:26 ../
-rw-------   1 root root 4.5K Jul  7 16:25 lightdm.log
-rw-r-----   1 root adm     0 Jul  7 16:25 lightdm.log.old
-rw-------   1 root root  867 Jul  7 16:25 seat0-greeter.log
-rw-r-----   1 root adm     0 Jul  7 16:25 seat0-greeter.log.old
-rw-------   1 root root  963 Jul  7 16:25 x-0.log
-rw-r-----   1 root adm     0 Jul  7 16:25 x-0.log.old
-rw-r-----   1 root adm   939 May 20 23:48 x-1.log.old
```

**Comment by poettering** [comment]
I am pretty sure lightdm renames the old file, and creates a new one, which means the perms/ownership lightdm chose are in effect for the new file, and whatever tmpfiles set up earlier doesn't have any effect (or only has an effect on the old file that is moved away)

There's nothing actionable for us here. It's just how lightdm works.
