### ISSUE TITLE
systemd-resolved: returns SERVFAIL for unknown domain

### ISSUE THREAD

**Issue by PSLLSP** [systemd/systemd#28310]
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu

### Linux kernel version used

kernel

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

CloudFlare DNS, reference, I believe this is expected answer:

$ khost oops. 1.1.1.1
Host oops. type A error: NXDOMAIN
Host oops. type AAAA error: NXDOMAIN
Host oops. type MX error: NXDOMAIN

### Unexpected behaviour you saw

systemd-resolved, the bug (and the reply is not consistent, MX record has different error):

$ khost oops.
Host oops. type A error: SERVFAIL
Host oops. type AAAA error: SERVFAIL
Host oops. type MX error: NXDOMAIN

### Steps to reproduce the problem

See above or Launchpad https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2024320

**Comment by PSLLSP** [comment]
Other example, with IPv6 address:

CloudFlare DNS, OK:
```
$ khost 2001:bc8:1204:9e02 1.1.1.1
Host 2001\:bc8\:1204\:9e02. type A error: NXDOMAIN
Host 2001\:bc8\:1204\:9e02. type AAAA error: NXDOMAIN
Host 2001\:bc8\:1204\:9e02. type MX error: NXDOMAIN
```
systemd-resolved, a bug:
```
$ khost 2001:bc8:1204:9e02
Host 2001\:bc8\:1204\:9e02. type A error: SERVFAIL
Host 2001\:bc8\:1204\:9e02. type AAAA error: SERVFAIL
Host 2001\:bc8\:1204\:9e02. type MX error: NXDOMAIN
```
IPv6 address can be resolved, CloudFlare DNS is OK
```
$ khost 2a00:1450:4014:80a::200e 1.1.1.1
e.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.a.0.8.0.4.1.0.4.0.5.4.1.0.0.a.2.ip6.arpa. points to prg03s10-in-x0e.1e100.net.
```
IPv6 address can be resolved, systemd-resolved is OK
```
$ khost 2a00:1450:4014:80a::200e
e.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.a.0.8.0.4.1.0.4.0.5.4.1.0.0.a.2.ip6.arpa. points to prg03s10-in-x0e.1e100.net.
```

**Comment by MartijnLievaart** [comment]
Exactly same issue om proxmox 7.2, systemd 249.11-0ubuntu3.6.

**Comment by poettering** [comment]
Please read docs, about single-label lookups:

https://www.freedesktop.org/software/systemd/man/resolved.conf.html#ResolveUnicastSingleLabel=
