### ISSUE TITLE
journald: when syncing journal file, also sync the dir the journal file is located in

### ISSUE THREAD

**Issue by portante** [systemd/systemd#2831]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> all

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora, CentOS, RHEL
### In case of bug report: Expected behaviour you didn't see

> fsync of parent directory when new file name created
### In case of bug report: Unexpected behaviour you saw

> no fsync performed on the journal directory itself to persist the new journal file names
### In case of bug report: Steps to reproduce the problem

> Set max individual file size low and drive high volume of traffic to drive log file rotation, only fsync's performed are on the data for the files themselves.

**Comment by portante** [comment]
See also  http://lwn.net/Articles/457667/

**Comment by evverx** [comment]
Do you mean something like that: https://github.com/rsyslog/rsyslog/blob/bbc6812162843ed5de10d3bd06b83e1fda9b6a8c/runtime/stream.c#L1338 ?

But:

> sync [switch]
> Default: off
> 
> enables file syncing capability of omfile.
> 
> When enabled, rsyslog does a sync to the data file as well as the directory it resides after processing each batch. There currently is no way to sync only after each n-th batch.
> 
> Enabling sync causes a severe performance hit. Actually, it slows omfile so much down, that the probability of loosing messages increases. In short, you should enable syncing only if you know exactly what you do, and fully understand how the rest of the engine works, and have tuned the rest of the engine to lossless operations.

http://www.rsyslog.com/doc/v8-stable/configuration/modules/omfile.html

**Comment by portante** [comment]
@evverx, yes, when systemd creates a new file on rotation, it needs to sync the directory to ensure it persists the reference to the file in the directory itself.  That LWN article describes why.  Thanks!

**Comment by evverx** [comment]
@portante , yes, I've read that article. Thanks!

[`man fsync`](http://man7.org/linux/man-pages/man2/fsync.2.html) is much shorter:

> Calling  fsync() does not necessarily ensure that the entry in the directory containing the file has also reached disk.  For that an explicit fsync() on a file descriptor for the directory is
>        also needed.

:)

**Comment by poettering** [comment]
PR waiting for this in #3126.
