### ISSUE TITLE
sudo systemctl hibernate falsely reports not enough swap space

### ISSUE THREAD

**Issue by nalply** [systemd/systemd#28332]
### systemd version the issue has been seen with

systemd 253.5-2

### Used distribution

Arch Linux

### Linux kernel version used

6.4.1-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

The error should be:

Call to Hibernate failed: swapfile fragmented

I am assuming here that's because I could not create an unfragmented swapfile.

### Unexpected behaviour you saw

Error message:

Call to Hibernate failed: Not enough swap space for Hibernation

### Steps to reproduce the problem

Have a fragmented swapfile then invoke `sudo systemctl hibernate`

Additionally, I need help to create an unfragmented swapfile. I could not. Please help. Where can I ask for help? `sudo fallocate -l 16G /swapfile` didn't create an unfragmented swapfile as `sudo filefrag /swapfile` showed, the extents weren't always following each other contiguously.

**Comment by poettering** [comment]
> I am assuming here that's because I could not create an unfragmented swapfile.

hmm, you have a swapfile that is fragmented? And the kernel accepted that as swap file? i.e. it shows up in /proc/swaps?

Generally, if something got accepted as suitable for swapping, i.e. shows up in /proc/swaps, then it should also be good enough for hibernation.

Hence i cannot make sense of your request?


> Additionally, I need help to create an unfragmented swapfile. I could not. Please help. Where can I ask for help?

This is not a support forum. There are plenty of docs avaulable about this. For example here:

https://wiki.archlinux.org/title/swap

**Comment by nalply** [comment]
I could solve the problem myself. I think what happened was one or both of:

1. There was fragmentation and I managed to defragment the partition the swapfile was in.

2. I had two swap instances (one small partition for normal kernel use and one large file for hibernation only) and I forgot to enable the swap file.

but I am not sure what exactly because I fixed both things at the same time. Sorry for the missed opportunity.

If possible, indicate in the error message how much swap is needed and how much swap is available. Else, just close the issue and forgive me. Thank you.

**Comment by poettering** [comment]
We don#t really know how much swap is needed, that's the thing. the kernel only figures that out once you try to hibernate...

**Comment by nalply** [comment]
That's a pity. Whatever (shrugs). Thank you for looking at my issue. Closing.

**Comment by nalply** [comment]
By the way, to help someone else who needs to defragment a partition and found this issue. What did I do exactly? I resized the partition to about 110% of current usage then resized back to original size.

1. Deactivated the swap file with swapoff
2. Deleted the file
3. Backed up my files
4. Cleaned up .cache, removed node_modules, deleted /tmp/* and so on
5. Looked up how much space was needed
6. Booted from a rescue disk because to make the partition smaller you need to unmount it
7. Invoked resize2fs  (see manpage) and resized to about 110% of space determined in step 5 (DANGEROUS)
8. Invoked resize2f again and resized back to original size
9. Reboot

It took about 30 minutes for me.
