### ISSUE TITLE
implement virtual and/or dummy graphical seats/sessions

### ISSUE THREAD

**Issue by fallenguru** [systemd/systemd#2833]
### Submission type
- [X] Request for enhancement (RFE)

Once upon a time most any X display manager could start and manage as many X servers / displays / greeters as desired, for example two local ones (:0 on vt7, :1 on vt8) an XDMCP chooser (:2 on vt9) and a couple of VNC servers (:3+). Depending on the dm that was one line/section per instance in some config file. gdm2 and kdm could certainly do it, reportedly lightdm until recently. I suppose xdm would still work, but ...

Nowadays virtually all dms seem to use logind to tell them how many displays they should manage, based on the "seats" concept. And since a seat seems to be linked to (dedicated) physical hardware, all the above setups are not possible anymore. Persistent "graphical consoles" over VNC using the regular greeter and login mechanisms become a conceptual chicken and egg problem because the dm won't launch a new server instance until a new seat becomes available and the new seat doesn't become available until the VNC server has launched (even if it had logind support and did register as a seat, which it probably does not).

For text mode logins (ssh) there's virtual sessions, I'd like to have the same for graphical remote logins, esp. VNC. Both on demand (user connects, gets a new VNC instance, which vanishes on disconnect), which I'd call a virtual graphical session; and persistent (a certain number of VNC servers are started, if nobody is logged in on one of those a greeter is shown, if somebody is then that session can be disconnected from / reconnected to at will until they actively log out), which I'd call a virtual seat. The latter would require the admin being able to define a number of existing but hw-less ("dummy") seats manually.

Losing the dm-can-manage-arbitrary-number-of-servers functionality obliterates one major use-case of mine -- which isn't systemd/logind's fault, of course, but in a scenario where dms are managed by logind would need at least some support there.

**Comment by keszybz** [comment]
I think there's some misunderstanding here. DMs (gdm certainly, but others too afaik) allow you to start multiple sessions for different users ("switch-user" menu entry under gnome-shell).

**Comment by fallenguru** [comment]
Switching users is something else entirely. This is not about having multiple users share one seat (virtual or otherwise) by switching back and forth, this is about being able to start as many (possibly different) X servers as one likes and have them running sessions concurrently. Pre-logind dms could do this as a matter of course, it wasn't even considered a feature.
Maybe running multiple X servers on one local seat does not make that much sense anymore (vt-switching used to be faster and less buggy than user-switching and allow using/testing different desktop environments). But if you take VNC/RDP into account a single machine can have a lot of virtual seats by launching e.g. Xvnc. In the past I'd just add another display definition line or three to /etc/gdm2.conf and it would start, restart, provide a greeter on and just generally manage the additional servers, giving me additional "graphical consoles" that could be used in parallel from or even shared between multiple clients.
By analogy: Using ssh I'm not limited to just one ssh session and "su - $OTHERUSER".

**Comment by keszybz** [comment]
When you "switch users", you start a new server. You can still start servers manually by switching VTs and starting X there. If you want the DM to start more servers automatically for you, take it up with them. logind does not specify how many servers should be started or limit that in any way.

**Comment by fallenguru** [comment]
> logind does not specify how many servers should be started or limit that in any way.
> Maybe in theory it doesn't ... in practice dm-writers all(!) seem to have taken the interpretation that
> a) X server = seat and
> b) all information about seats comes from logind.
> Seeing as logind manages physical seats these assumptions don't seem unreasonable. Why shouldn't it manage seats that aren't backed by physical hardware? 
> All it would take in the short run is the ability for the admin to create a virtual/dummy hardware-less seat.

**Comment by eugenesan** [comment]
I agree with fallenguru's claim.
There should be a mechanism to "define" virtual/pseudo seats.

These days all distros rely on logind for seats management and as result all VirtualDesktop solutions (VNC, Xspice, x2o, xRDP etc) are partially broken since PolicyKit rely on proper seat registration.

**Comment by lobdellb** [comment]
I relate to fallenguru's issue:   I've been trying to figure out how to add an arbitrary number of Xvfb+VNC based virtual terminals on a machine, and it seems to be impossible for the reason discussed above.

**Comment by lobdellb** [comment]
Another use case is:  "I have three monitors which makes VNC borderline unusable.  I'd like to create another single-screen seat which runs behind-the-scenes which has dimensions which work well for VNC."

**Comment by moocan** [comment]
Hello,

Why this feature seems to be so "not allowed" ?
Before it was possible (not so simple but not so hard too) to start at the same time some Display Manager as LightDM on vt7, vt8, v9 without using "switch user" (which is not the same things).

Now that all Display Manager rely on logind it is **impossible** !
We have many available vt ... dedicated to a blinking cursor.

They are many users who try to do it as me ...
https://unix.stackexchange.com/questions/335612/display-manager-on-multiple-tty

Kind Regards

**Comment by mfulz** [comment]
Is there any solution to it already?

**Comment by thanatos** [comment]
I too ran into this. `loginctl` [apparently requires a seat to have a graphics card?](https://www.freedesktop.org/software/systemd/man/loginctl.html)

> Persistently attach one or more devices to a seat. The devices should be specified via device paths in the /sys/ file system. To create a new seat, **attach at least one graphics card to a previously unused seat name.**

I ran into this while using VNC, too. I wanted to mount a USB disk, so I opened `caja`, and clicked the disk. "Not authorized." Some debugging reveals that this is done with `udisks`, and to be "authorized", you have to be the current session of the seat to which the USB disk is attached.

The USB disk is attached to `seat0`, which makes sense, and best represents the physical chair in front of this machine. (A desktop.)

But I'm not sitting in `seat0`, I'm sitting on the couch. I'd call the couch (and my VNC from it) `seat1` (as `couch0` is not a valid seat name, apparently) and attach the USB drive to it … except for this bug, of course.

I can't "unseat" `seat0`, either. My fiancée is watching the game from `seat0`.

So I need most of the hardware (in particular, the graphics card & the sound card) to remain on `seat0`. Only the external USB disk needs to move.

I can manually `sudo -i`; `umount; mount; … sshfs` … but that's a workaround to the session in VNC being broken/unable to mount the disk.

**Comment by mattarroz** [comment]
> I too ran into this. `loginctl` [apparently requires a seat to have a graphics card?](https://www.freedesktop.org/software/systemd/man/loginctl.html)
> 
> > Persistently attach one or more devices to a seat. The devices should be specified via device paths in the /sys/ file system. To create a new seat, **attach at least one graphics card to a previously unused seat name.**
> 
> I ran into this while using VNC, too. I wanted to mount a USB disk, so I opened `caja`, and clicked the disk. "Not authorized." Some debugging reveals that this is done with `udisks`, and to be "authorized", you have to be the current session of the seat to which the USB disk is attached.
> 
> The USB disk is attached to `seat0`, which makes sense, and best represents the physical chair in front of this machine. (A desktop.)
> 
> But I'm not sitting in `seat0`, I'm sitting on the couch. I'd call the couch (and my VNC from it) `seat1` (as `couch0` is not a valid seat name, apparently) and attach the USB drive to it … except for this bug, of course.
> 
> I can't "unseat" `seat0`, either. My fiancée is watching the game from `seat0`.
> 
> So I need most of the hardware (in particular, the graphics card & the sound card) to remain on `seat0`. Only the external USB disk needs to move.
> 
> I can manually `sudo -i`; `umount; mount; … sshfs` … but that's a workaround to the session in VNC being broken/unable to mount the disk.
> 
> > logind does not specify how many servers should be started or limit that in any way.
> 
> Oh but it does! There's no way to get a seat for an X server that's managing a VNC session…

Just to add another data point: Rustdesk headless support is not usable when a X Server using a 
 physical graphics card is used in addition to a dummy x server for rust headless: https://github.com/rustdesk/rustdesk/wiki/Headless-Linux-Support

Bo seat for a dummy x server is created by systemd, in consequence, lightdm does not add a seat no matter what you configure in lightdm.conf.

Because of systemd's behavior it is not possible to use other resolutions than the physical for rustdesk, as a consequence. Quite annoying when you want your tablet's native resolution, for example.

The only workaround I found is to chose between either the physical or the dummy seat, but I cannot have both :-(
