### ISSUE TITLE
Logitech MX Ergo Trackball on Bluetooth, does not match against it's hwdb entry

### ISSUE THREAD

**Issue by rgammans** [systemd/systemd#28349]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.38+

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

I would expect the device to be 'tagged as' a 'Mouse Trackball'

### Unexpected behaviour you saw

I would expect the device to be 'tagged as' a 'Mouse'

### Steps to reproduce the problem

Connect Logitech MX Ergo device (of the same sub-model  I have, since I have no reason to doubt the existing definition works fro some devices)  .
Run `libinput  --device /dev/input/eventXY --verbose`
Output is: `eventXY - Logitech MX Ergo Multi-Device Trackball : is tagged by udev as: Mouse`

**Comment by rgammans** [comment]
I note that adding 
`mouse:bluetooth:v046dpb01d:name:*`

To the devices hunk in `/usr/lib/udev/hwdb.d/70-mouse.hwdb` , resolves the problem but I not 100% certain this sisthe best fix, so I've raised this as a bug not a PR.

**Comment by rgammans** [comment]
I should also say this is important because it without it libinput wont activate scroll-method=button.

**Comment by yuwata** [comment]
> I note that adding `mouse:bluetooth:v046dpb01d:name:*`

We already have a similar entry with the same bluetooth ID:
```
mouse:bluetooth:v046dpb01d:name:MX Ergo Mouse:*
 ID_INPUT_TRACKBALL=1
 MOUSE_DPI=380@125
```

So, instead of `*`, please add with the exact name, e.g. `mouse:bluetooth:v046dpb01d:name:MX Ergo Multi-Device Trackball:*` (not sure if this works), and open a PR.

**Comment by rgammans** [comment]
Certainly using the name `Logitech MX Ergo Multi-Device Trackball`  Did not work .

Is there any way to make systemd log the name is using when searching the database?

**Comment by yuwata** [comment]
name can be found from /sys/class/input/inputX/name. On my laptop,
```
$ head /sys/class/input/*/name
==> /sys/class/input/input0/name <==
Sleep Button

==> /sys/class/input/input1/name <==
Lid Switch

==> /sys/class/input/input11/name <==
Synaptics TM3381-002

==> /sys/class/input/input12/name <==
TPPS/2 Elan TrackPoint

==> /sys/class/input/input13/name <==
Video Bus

==> /sys/class/input/input14/name <==
HDA Intel PCH Mic

==> /sys/class/input/input15/name <==
HDA Intel PCH Headphone

==> /sys/class/input/input16/name <==
HDA Intel PCH HDMI/DP,pcm=3

==> /sys/class/input/input17/name <==
HDA Intel PCH HDMI/DP,pcm=7

==> /sys/class/input/input18/name <==
HDA Intel PCH HDMI/DP,pcm=8

==> /sys/class/input/input2/name <==
Power Button

==> /sys/class/input/input3/name <==
AT Translated Set 2 keyboard

==> /sys/class/input/input7/name <==
PC Speaker

==> /sys/class/input/input9/name <==
ThinkPad Extra Buttons
```

**Comment by rgammans** [comment]
Thanks, I doubt I had found it without that. There appears to be a trailing space in the name.

PR incoming,
