### ISSUE TITLE
udev rule only works when a specific device is triggered (works in 250.9)

### ISSUE THREAD

**Issue by name-snrl** [systemd/systemd#28345]
### systemd version the issue has been seen with

253.5

### Used distribution

Nixos-23.05

### Linux kernel version used

5.15.85

### CPU architectures issue was seen on

x86_64

### Component

udevadm, udev rule files

### Expected behaviour you didn't see

The rule works completely on boot. The `udevadm trigger` applies my rule, just as if I were triggering it on a specific device.

### Unexpected behaviour you saw

Only speed ATTR is set on boot, or when I run `udevadm trigger`.

### Steps to reproduce the problem

1. Add a rule that can be found in many places to configure trackpoint:

echo `ACTION=="add|change", SUBSYSTEM=="input", ATTR{name}=="TPPS/2 IBM TrackPoint", ATTR{device/speed}="250", ATTR{device/sensitivity}="150"` >> /etc/udev/rules.d/99-local.rules

2. Reboot
3. Check setup with `udevadm info -a /dev/input/mouse1`, only speed ATTR is set.
4. Trigger only the device for which the rule was written `udevadm trigger -v --attr-match="name=TPPS/2 IBM TrackPoint"`
5. Check setup again, both ATTR is set now.
6. Trigger all devices `udevadm trigger`.
7. Again, only speed is set :C

As I wrote in the issue title, everything works fine on 250.9. NixOS allows you to quickly and easily build any configuration using the binary cache, so first I built the minimum possible configuration, which consisted only of the bootloader, users, udev rule and various default configuration values. No results...

Okay, I change the `nixpkgs` (explained bellow) version to an older version for the test and build NixOS 22.05, with the same minimal config. Here the version of systemd is 250.9, and everything works fine.

```
systemd 250 (250.9)
+PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

version on unstable:

```
systemd 253 (253.5)
+PAM +AUDIT -SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

The last thing I checked was changing the kernel to the kernel from NixOS 22.05 - 5.15.85. But that also didn't give any results.

So I think the problem is with systemd.

___

`nixpkgs` is repo where all NixOS modules and packages are stored. This means that if you change the revision of `nixpkgs`, the NixOS version changes completely

**Comment by yuwata** [comment]
If writing a sysattr fails, then udev should log something about that. Please find relevant log messages from journal and provide them.

**Comment by name-snrl** [comment]
> If writing a sysattr fails

I don't think is it fails. When I trigger a particular device, it works. It looks more like something is happening and the value is being overridden. Anyway, I don't know much about `udev`. Where can I find the log? I checked `journalctl` and `dmesg` - nothing.

**Comment by name-snrl** [comment]
Okay, I found something. This is my device in sysfs:

```fish
> sudo udevadm trigger -v --attr-match="name=TPPS/2 IBM TrackPoint"
/sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33
```

And this command does what I want. But if I trigger the whole tree:

```fish
> sudo udevadm trigger -v /sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33/
/sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33
/sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33/event16
/sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33/mouse1
```

This gives a bad result. So I just tested all three devices from the tree with `udevadm test` and found that `event16` does something bad.

```fish
sudo udevadm test /sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33/
```
[input33.log](https://github.com/systemd/systemd/files/12021457/input33.log)


```fish
sudo udevadm test /sys/devices/pci0000:00/0000:00:1f.3/i2c-9/9-002c/rmi4-00/rmi4-00.fn03/serio2/input/input33/event16/
```
[input33-event16.log](https://github.com/systemd/systemd/files/12021461/input33-event16.log)

**Comment by yuwata** [comment]
Still I have no idea what introduced the behavior change between v250..v253, but I found why the rule does not work for you.

When udevd processes event16, (it is processed after input33 on boot)
1. 70-pointingstick.hwdb sets POINTINGSTICK_SENSITIVITY=200 to event16, as the device matches the following entry,
```
# Lenovo Thinkpad *40 series
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad??40:*
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad??40?:*
```
2. 'keyboard' builtin sets sensitivity based on the property.

So, please try to create `/etc/udev/hwdb.d/71-pointingstick.hwdb`:
```
# Lenovo Thinkpad *40 series
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad??40:*
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPad??40?:*
 POINTINGSTICK_SENSITIVITY=150
```
then run `systemd-hwdb update`.

**Comment by yuwata** [comment]
Ah, that may be 953c928c24455744d5534679998d129b947a5e04 (and its follow-up de8409ac43f6e4596de4cecce8dbbb5f1f2a18b1).

The change is intentional, and will not be reverted.
