### ISSUE TITLE
Serialize state to FDSTORE in user managers on SIGTERM

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#28367]
### Describe the solution you'd like

Ideally `systemctl restart user@*` would be equivalent to `systemctl --user daemon-reexec`. To make this possible we should use the file descriptor store to serialize user manager state when it is restarted and use `sd_listen_fds()` to receive it again on startup.

We could also look into enabling `RestartMode=direct` for user services at the same time as restarts should not be noticeable anymore after implementing the above (I think).

**Comment by DaanDeMeyer** [comment]
I want to be able to daemon-reexec all user managers from an rpm scriptlet on systemd upgrades. It seems most natural to do this using `systemctl restart user@*.service` but then of course a restart should not be noticeable which means it needs to serialize its state to the FDSTORE and retrieve it again after restarting.

**Comment by YHNdnzj** [comment]
See also: https://github.com/systemd/systemd/pull/30884#issuecomment-1887283181

**Comment by Werkov** [comment]
> user managers are tracked as sessions

I don't understand. User manager being the leader? user@.service being a user@.scope? Could you please elaborate?

---

Nevertheless, a half-idea to the original issue:
```
RestartKillSignal=SIGRTMIN+25 # daemon-reexec without exit.target
KillMode=process # to preserve user services
```
(The unknown second half is how to get rid of `KillMode=process`.)

---

Or completely different approach:
```
for i in /run/user/*/systemd/private ; do
   systemctl --address=$i daemon-reexec
done
```
(where `address` would need to be a proper generalization between users and capsules.)
