### ISSUE TITLE
schroot fails with a PAM error when run from inside a DynamicUser

### ISSUE THREAD

**Issue by mikehearn** [systemd/systemd#28369]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22 LTS

### Linux kernel version used

5.15.0-69-generic

### CPU architectures issue was seen on

x86_64

### Component

pam_systemd, systemd

### Expected behaviour you didn't see

The `schroot` command that comes with Debian is a nice and lightweight alternative to "real" containers because it doesn't require any messing around with networking, users, logging in, starting, stopping etc. For some tasks e.g. building against an old glibc, this is sufficient.

schroot layers features on top of regular chroot, for example, it is suid root so anyone listed in the users= line in the chroots config file can run commands as themselves. It can also copy nss databases into the root. So all the users from the host appear can run `schroot -c my-chroot-name` and be dropped into a shell inside the chroot as your current user, as long as the chroot config authorizes that.

### Unexpected behaviour you saw

It works fine for normal users but not for dynamic users:

```
$ schroot -c xenial-build --debug=notice

[snip]

D(2): auth ruid = 65,422, rgid = 65,422
D(2): auth uid = 65,422, gid = 65,422
D(1): pam_start OK
D(2): In users: 1
In groups: 0
In root-users: 0
In root-groups: 0
D(1): Inserted into environment: PATH=/usr/local/bin:/usr/bin:/bin
D(1): Inserted into environment: HOME=/
D(1): Inserted into environment: LOGNAME=jetbrains-teamcity-agent
D(1): Inserted into environment: USER=jetbrains-teamcity-agent
D(1): Inserted into environment: TERM=xterm
D(1): Inserted into environment: SHELL=/usr/sbin/nologin
D(2): pam_putenv: set HOME=/
D(2): pam_putenv: set LOGNAME=jetbrains-teamcity-agent
D(2): pam_putenv: set PATH=/usr/local/bin:/usr/bin:/bin
D(2): pam_putenv: set SHELL=/usr/sbin/nologin
D(2): pam_putenv: set TERM=xterm
D(2): pam_putenv: set USER=jetbrains-teamcity-agent
D(1): pam_putenv OK
D(3): pam_acct_mgmt FAIL
D(1): pam_end OK
E: PAM error: Authentication failure
```

So `pam_acct_mgmt` fails. I wonder if this is related to the fact that `su` also fails?

The same thing happens even if schroot is run as root with the `--user` flag.

### Steps to reproduce the problem

Create/start my-service.service that uses DynamicUser and accepts commands that it then runs (netcat to a shell or something). Then:

```sh
$ su
# cat /etc/debian_version
bookworm/sid

# apt install schroot debootstrap

# cd /root

# debootstrap --variant=buildd xenial $PWD/xenial

# cat <<EOF >/etc/schroot/chroot.d/xenial.conf
[xenial]
directory=/root/xenial
users=my-service
type=directory
preserve-environment=true
EOF
 
# schroot -c xenial
// should work and give a root prompt, exit
```

Now try running `schroot -c xenial` from within the DynamicUser context and it will fail.

**Comment by mikehearn** [comment]
From digging, I think this may be something like `DynamicUser=yes` doesn't simply create a user but also flips lots of other bits like disabling the use of suid binaries. This is quite confusing. One doesn't obviously imply the other and worse, there seems to be no way to override this `NoNewPrivileges=yes` other than abandoning the whole `DynamicUser` feature, which I guess I must now do :(

**Comment by bluca** [comment]
https://freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=

> Furthermore NoNewPrivileges= and RestrictSUIDSGID= are implicitly enabled (and cannot be disabled), to ensure that processes invoked cannot take benefit or create SUID/SGID files or directories.

Don't use suid binaries, it's a really bad legacy pattern that is just a security nightmare.

**Comment by mikehearn** [comment]
If there's a way to let this binary do its thing without being suid  and without forking it / rewriting it then sure, but my Linux-fu isn't strong enough to do that. Maybe something with extended attributes and capabilities? The systemd user guide doesn't provide any guidance on how to migrate apps to be DynamicUser compatible.

Is it at least possible to at least make programs stop with a sensible error if they try to use a suid binary? It appears that DynamicUser=yes makes this bit silently not take effect, which is confusing. What if I didn't know this program needed suid to work? It could have taken a long time to figure that out. A clear error message would help.
