### ISSUE TITLE
Wrong password message is not localized

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#28379]
### Component

pam_systemd_home, systemd-homed

### Is your feature request related to a problem? Please describe

With systemd-homed users, entering a wrong password (eg sudo or GDM) results in an error message which is not localized. This seems inconsistent with the password prompt, which is:
```
$ sudo -i
[sudo] Mot de passe de bob : **** 
Password incorrect or not sufficient for authentication of user bob.
Sorry, try again: 
```

### Describe the solution you'd like

Provide a localized message when the password is wrong

**Comment by poettering** [comment]
I am pretty sure #28380 was just a placebo, reopening.
