### ISSUE TITLE
Set primary slave for bonding in systemd-networkd

### ISSUE THREAD

**Issue by leoluk** [systemd/systemd#2837]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### Feature request

systemd-networks currently lacks the capability to set the primary slave in an active-backup bonding. This is necessary if you prefer one interface over the other. A common example is a eth0-wlan0 bonding on a laptop where you'd want to switch to the wired connection whenever it's available.

The sysfs toggle for this feature is `/sys/devices/virtual/net/bondN/bonding/primary`.

You can already set the primary reselect policy, it's just the ability to set the actual primary interface that's not yet available.

See also: 
- [[systemd-devel] How to set primary slave in active-backup mode (bonding)](https://lists.freedesktop.org/archives/systemd-devel/2015-May/032077.html)

**Comment by poettering** [comment]
@ssahani maybe something for you?

**Comment by ssahani** [comment]
Working on this patch:
https://github.com/ssahani/systemd/commit/f13d4c0fd5182299b85dc0294b695d2b6fc90efe

Not sure what permission is required for networkd to write to /sys/devices/virtual/net/%s/bonding/primary

Now it's failing with "Cannot set primary slave for bonding , ignoring: Permission denied"

**Comment by lnykryn** [comment]
@ssahani  It is probably not related, but we had some timing issues with setting "primary" in initscripts https://bugzilla.redhat.com/show_bug.cgi?id=236897

https://git.fedorahosted.org/cgit/initscripts.git/commit/?id=1a98c7e9

**Comment by ssahani** [comment]
@lnykryn Yes It's different. Here we not able to write to /sys from networkd

**Comment by poettering** [comment]
Is there no way to set the primary bonding device via netlink?

**Comment by lnykryn** [comment]
I think it should be possible https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/net/bonding/bond_netlink.c?id=refs/tags/v4.6-rc3#n287

**Comment by poettering** [comment]
Using netlink for this definitely looks like the right way to go then.

**Comment by ssahani** [comment]
Thanks @lnykryn this actually works. I tried to fit this in our architecture. We need .network files as @teg suggested. But This parameter only can be set during creation not afterwards. We need to know the index of the interface. Will discuss with @teg .

https://github.com/systemd/systemd/compare/master...ssahani:bond?expand=1
