### ISSUE TITLE
systemd-stub: Regression - no valid EFI binary generated

### ISSUE THREAD

**Issue by freswa** [systemd/systemd#28419]
### systemd version the issue has been seen with

254rc2

### Used distribution

Arch Linux

### Linux kernel version used

6.4.3-arch1-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub

### Expected behaviour you didn't see

System boots from generated EFI executable including the systemd efi-stub.[](url)

### Unexpected behaviour you saw

EFI doesn't even consider the EFI executable as bootable. If forced manually you get no more than a black screen.

### Steps to reproduce the problem

- Install Arch Linux with testing repos enabled (includes systemd 254rc2)
- Install dracut
- Generate an EFI executable including these lines in `dracut.conf`:
```
uefi=yes
uefi_stub=/usr/lib/systemd/boot/efi/linuxx64.efi.stub
```

### Additional program output to the terminal or log subsystem illustrating the issue

I bisected the issue to https://github.com/systemd/systemd/commit/dfca5587cf2032f9ad06041b93b0da5cb39b9989.
I guess also https://github.com/systemd/systemd/commit/2afeaf1675a6a68636be493a9461e72ce067db19 is involved since that is the new code.

Dracut gives a hint in the logs:
```sh
objcopy: /var/tmp/dracut.ku25Sp/uefi/linux.efi:.osrel: section below image base
objcopy: /var/tmp/dracut.ku25Sp/uefi/linux.efi:.cmdline: section below image base
objcopy: /var/tmp/dracut.ku25Sp/uefi/linux.efi:.splash: section below image base
objcopy: /var/tmp/dracut.ku25Sp/uefi/linux.efi:.linux: section below image base
objcopy: /var/tmp/dracut.ku25Sp/uefi/linux.efi:.initrd: section below image base
```

Downstream bug reports:
https://bugs.archlinux.org/task/79115
https://github.com/dracutdevs/dracut/issues/2431

**Comment by bluca** [comment]
What's the exact objcopy command used to assemble the image? If you use ukify instead does that work?

**Comment by freswa** [comment]
The objcopy cmd:
```
objcopy --add-section .osrel=/etc/os-release --change-section-vma .osrel=0x20000 --add-section .cmdline=/var/tmp/dracut.rmOyGH/uefi/cmdline.txt --change-section-vma .cmdline=0x30000 --add-section .splash=/usr/share/systemd/bootctl/splash-arch.bmp --change-section-vma .splash=0x40000 --add-section .linux=/lib/modules/6.4.3-arch1-2/vmlinuz --change-section-vma .linux=0x2000000 --add-section .initrd=/var/tmp/dracut.rmOyGH/initramfs.img --change-section-vma .initrd=0x3000000 /usr/lib/systemd/boot/efi/linuxx64.efi.stub /var/tmp/dracut.rmOyGH/uefi/linux.efi
```

Ukify generates a good, bootable EFI executable.

**Comment by bluca** [comment]
How are those offsets calculated?

**Comment by freswa** [comment]
The code can be found here: https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L2521
Calculation starts at line 2470.

**Comment by bluca** [comment]
Can you file a bug with dracut? Either those calculations need to be fixed, or it can just use ukify (probably easier)

**Comment by freswa** [comment]
Not a systemd issue. See
https://github.com/dracutdevs/dracut/issues/2431
