### ISSUE TITLE
M4, GPERF and GEN operations aren’t done when building only a single binary

### ISSUE THREAD

**Issue by linkmauve** [systemd/systemd#2841]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 70e43ee7be6ee8d1e8aa4b2984a72baa25709c2e and 229 both.

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ArchLinux up to date (as of 2016-03-15)
### In case of bug report: Expected behaviour you didn't see

> systemd-path compiling correctly
### In case of bug report: Unexpected behaviour you saw

> src/basic/af-list.c:28:26: fatal error: af-from-name.h: No such file or directory
> src/basic/arphrd-list.c:28:30: fatal error: arphrd-from-name.h: No such file or directory
> src/basic/errno-list.c:28:29: fatal error: errno-from-name.h: No such file or directory
### In case of bug report: Steps to reproduce the problem

> ./autogen.sh
> ./configure
> make -j4 systemd-path

**Comment by ohsix** [comment]
yep, there is a make target just for running those: built-sources

see 7ee7b225bd2fc3e7a3980f5fb7b10dfc6e205578

**Comment by poettering** [comment]
Yeah that is how autotools works with built sources really. nd there's a make target to deal with that...

**Comment by poettering** [comment]
Closing this, because this isn't really a bug, but intended autotools behaviour.

**Comment by ohsix** [comment]
Hello friend, 

I've found very nice driving  glasses  that perfectly protect  from  brigth  sunlight,  and they are also so stylish,  just take a look <http://baxuchyque.artistryminerals.com/aeeonwa>

All best, steubens

**Comment by ohsix** [comment]
wtf, spam related to yahoo hax probably, sorry
