### ISSUE TITLE
IPv6 Compliance RFC4861: Neighbor Advertisement Processing, R-bit Change (Hosts Only) [v6LC.2.1.21a]

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [systemd/systemd#28421]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

[RFC 4861 Neighbor Discovery in IPv6, page 66](https://www.rfc-editor.org/rfc/rfc4861#section-6.3.4:~:text=%2D%20The%20IsRouter%20flag,as%20a%20host.), Extract:

       - The IsRouter flag in the cache entry MUST be set based on the
         Router flag in the received advertisement.  In those cases
         where the IsRouter flag changes from TRUE to FALSE as a result
         of this update, the node MUST remove that router from the
         Default Router List and update the Destination Cache entries
         for all destinations using that neighbor as a router as
         specified in Section 7.3.3.  This is needed to detect when a
         node that is used as a router stops forwarding packets due to
         being configured as a host.

### Unexpected behaviour you saw

Networkd is not honoring this behaviour.  Instead, it continues to preserve the route entry, ignoring the change of the NA's `IsRouter` flag. 

### Steps to reproduce the problem

Reproducing this requires a protocol exchange. If you need help setting something up, please ask, FWIW, I find `tcpreplay` a useful tool).  Otherwise, I'll assume you have the tools necessary to duplicate this in your own environment.

Please find attached a zip file containing two PCAP files, `legacy` and `networkd`.  The `legacy` PCAP shows the correct behavior.  It was recorded when our host was configured using Debian's legacy `/etc/network/interfaces` file and `networkd` was disabled and stopped.  The `networkd` PCAP shows incorrect behavior. It was recorded after configuring `networkd` to manage the interface.

There are associated log files that provide additional information.  If you need more, please ask.

[2_1_21a - Neighbor Advertisement Processing, R-bit Change.zip](https://github.com/systemd/systemd/files/12066187/2_1_21a.-.Neighbor.Advertisement.Processing.R-bit.Change.zip)

**Comment by ssahani** [comment]
packet 1
```
Frame 1: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0x1c3b [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
    Router lifetime (s): 20
    Reachable time (ms): 100000
    Retrans timer (ms): 1000
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)

```
networkd
```
❯ ip -6 r  show dev veth99
2001:2:0:1000::/64 proto ra metric 1024 expires 65530sec pref medium
fe80::/64 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 15sec pref medium
```

packet 13
```
Frame 12: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0xa718 [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
    Router lifetime (s): 0
    Reachable time (ms): 0
    Retrans timer (ms): 0
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)

```

networkd
```
❯ ip -6 r  show dev veth99
fe80::/64 proto kernel metric 256 pref medium

```

```
veth99: Forgetting foreign route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
veth99: NDISC: Received Router Advertisement: flags none preference medium lifetime 0 sec
veth99: NDISC: Invoking callback for 'router' event.
veth99: Removing NDisc route (configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
veth99: Forgetting NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 1024, flags: n/a
veth-peer: NDISC: Sent Router Solicitation, next solicitation in 9min 22s

```


packet 17

```
Frame 17: 63 bytes on wire (504 bits), 63 bytes captured (504 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:80 (00:00:10:10:10:80), Dst: HewlettP_d6:dc:d7 (94:40:c9:d6:dc:d7)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1080, Dst: fe80::9640:c9ff:fed6:dcd7
Internet Control Message Protocol v6
    Type: Echo (ping) request (128)
    Code: 0
    Checksum: 0x253b [correct]
    [Checksum Status: Good]
    Identifier: 0x0000
    Sequence: 0
    [No response seen]
        [Expert Info (Warning/Sequence): No response seen to ICMPv6 request in frame 17]
    Data (1 byte)
        Data: 00
        [Length: 1]


```

**Comment by ssahani** [comment]
I think this should fix by https://github.com/systemd/systemd/commit/1b41aa9a82735960b0870b3b49f81deca5599526

**Comment by ssahani** [comment]
This should fix by https://github.com/systemd/systemd/pull/28496/commits/4ccd48cb2693a3603f14a30b6286228597285d92 since it's lft is zero.

```
    Flags: 0x00, Prf (Default Router Preference): Medium
    Router lifetime (s): 0
    Reachable time (ms): 0
    Retrans timer (ms): 0
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)


```

**Comment by yuwata** [comment]
Not sure, but the original report is about IsRouter flag, not zero lifetime. I do not think your recent fix is related to this issue.

**Comment by ssahani** [comment]
I dont see a isrouter flag 

packet 1 networkd capture
```
Frame 1: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0x1c3b [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
        0... .... = Managed address configuration: Not set
        .0.. .... = Other configuration: Not set
        ..0. .... = Home Agent: Not set
        ...0 0... = Prf (Default Router Preference): Medium (0)
        .... .0.. = Proxy: Not set
        .... ..0. = Reserved: 0
    Router lifetime (s): 20
    Reachable time (ms): 100000
    Retrans timer (ms): 1000
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)
        Type: Prefix information (3)
        Length: 4 (32 bytes)
        Prefix Length: 64
        Flag: 0xc0, On-link flag(L), Autonomous address-configuration flag(A)
            1... .... = On-link flag(L): Set
            .1.. .... = Autonomous address-configuration flag(A): Set
            ..0. .... = Router address flag(R): Not set
            ...0 0000 = Reserved: 0
        Valid Lifetime: 65535
        Preferred Lifetime: 65535
        Reserved
        Prefix: 2001:2:0:1000::

```


packet12

```
Frame 12: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0xa718 [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
        0... .... = Managed address configuration: Not set
        .0.. .... = Other configuration: Not set
        ..0. .... = Home Agent: Not set
        ...0 0... = Prf (Default Router Preference): Medium (0)
        .... .0.. = Proxy: Not set
        .... ..0. = Reserved: 0
    Router lifetime (s): 0
    Reachable time (ms): 0
    Retrans timer (ms): 0
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)
        Type: Prefix information (3)
        Length: 4 (32 bytes)
        Prefix Length: 64
        Flag: 0x80, On-link flag(L)
            1... .... = On-link flag(L): Set
            .0.. .... = Autonomous address-configuration flag(A): Not set
            ..0. .... = Router address flag(R): Not set
            ...0 0000 = Reserved: 0
        Valid Lifetime: 0
        Preferred Lifetime: 0
        Reserved
        Prefix: 2001:2:0:1000::


```


legacy packet 1
```
Frame 1: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0x1c3b [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
        0... .... = Managed address configuration: Not set
        .0.. .... = Other configuration: Not set
        ..0. .... = Home Agent: Not set
        ...0 0... = Prf (Default Router Preference): Medium (0)
        .... .0.. = Proxy: Not set
        .... ..0. = Reserved: 0
    Router lifetime (s): 20
    Reachable time (ms): 100000
    Retrans timer (ms): 1000
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)
        Type: Prefix information (3)
        Length: 4 (32 bytes)
        Prefix Length: 64
        Flag: 0xc0, On-link flag(L), Autonomous address-configuration flag(A)
        Valid Lifetime: 65535
        Preferred Lifetime: 65535
        Reserved
        Prefix: 2001:2:0:1000::


```

packet 12
```
Frame 8: 102 bytes on wire (816 bits), 102 bytes captured (816 bits) on interface unknown, id 0
Ethernet II, Src: Sytek_10:10:60 (00:00:10:10:10:60), Dst: IPv6mcast_01 (33:33:00:00:00:01)
Internet Protocol Version 6, Src: fe80::200:10ff:fe10:1060, Dst: ff02::1
Internet Control Message Protocol v6
    Type: Router Advertisement (134)
    Code: 0
    Checksum: 0xa718 [correct]
    [Checksum Status: Good]
    Cur hop limit: 64
    Flags: 0x00, Prf (Default Router Preference): Medium
        0... .... = Managed address configuration: Not set
        .0.. .... = Other configuration: Not set
        ..0. .... = Home Agent: Not set
        ...0 0... = Prf (Default Router Preference): Medium (0)
        .... .0.. = Proxy: Not set
        .... ..0. = Reserved: 0
    Router lifetime (s): 0
    Reachable time (ms): 0
    Retrans timer (ms): 0
    ICMPv6 Option (Prefix information : 2001:2:0:1000::/64)
        Type: Prefix information (3)
        Length: 4 (32 bytes)
        Prefix Length: 64
        Flag: 0x80, On-link flag(L)
        Valid Lifetime: 0
        Preferred Lifetime: 0
        Reserved
        Prefix: 2001:2:0:1000::

```

**Comment by Zugschlus** [comment]
The IsRouter Flag is not part of the Router Advertisement, it is part of the _Neighbor_ Advertisement as specified in RFC 4861 Chapter 4.4. This issue is about networkd not acting properly on reception of a neighbor advertisement that changed the router flag.

Node behavior regarding received IsRouter flags is specified in RFC4861 chapter 7.3.3

**Comment by LiveFreeAndRoam** [comment]
@yuwata @ssahani @Zugschlus, I have just begun looking at this one and wonder if you have any insights to get me moving in the right direction.

The problem is that the kernel is not removing the `default route` when the NA's R-flag is cleared. This only happens when the `default route` is created by `networkd`. When `networkd` is disabled, the kernel deletes the `default route`.

In brief, the expected protocol exchange is:

1. Router sends RA to configure a prefix. The host creates two routes, one for the prefix and the other is the default route
2. There's a successful exchange of Ping Request and Reply
3. Router sends NA with IsRouter=false. The host should delete the default route.

When the host is running `networkd`, in step 3, the default route is NOT deleted.
When the host is running with `native` networking, the host correctly deletes the default route in step 3.

**Comment by yuwata** [comment]
That's simple, networkd does not read NA packets currently.

**Comment by LiveFreeAndRoam** [comment]
> That's simple, networkd does not read NA packets currently.

I'm aware networkd is not intercepting NA packets.  The thing I don't understand is when the kernel receives an NA that requires the default route to be deleted, why isn't it deleting the default route that is created by networkd? Is there something unique about the routes created by networkd that prevents the kernel from deleting it?

**Comment by yuwata** [comment]
WIP patches are available in #30569.

**Comment by LiveFreeAndRoam** [comment]
Oh, wow! From the code changes, I see you are adding NA processing to networkd. Presumably, this means the kernel will no longer process the NA, correct? When it's ready, I'll rerun most of the IPv6 Logo Certification tests to see what overall impact this has.

As an aside... I realise your patches are still WIP, but I couldn't resist, I had to try them.  Fwiw, the test still fails (the default route is not being removed by the NA), but by the look of the code changes, it's on the right track.  Let me know if I can help with the validation along the way.

**Comment by yuwata** [comment]
@LiveFreeAndRoam Please test PR #30569 (https://github.com/yuwata/systemd/tree/network-next branch) again. I hope the situation should be now better, and the previously passed test cases should be still green, I hope.

**Comment by LiveFreeAndRoam** [comment]
I hope so too, 😁

I'll retest tomorrow and post the results here.
