### ISSUE TITLE
Hybernate: issue a warning if suspending to a swap file but resuming from it is not configured

### ISSUE THREAD

**Issue by Pipeliner** [systemd/systemd#28432]
### Component

systemd

### Is your feature request related to a problem? Please describe

If the system has a swap file enabled, it requires some additional setup done to be able to resume from there. [Example.](https://askubuntu.com/questions/6769/hibernate-and-resume-from-a-swap-file)
However, `systemd hibernate` happily runs even if no such setup was done.

### Describe the solution you'd like

It clearly isn't systemd's fault that the user hasn't configured their system correctly. However, hibernation failing silently is very confusing.

Some sanity checks could be performed, e.g. if
1. The only swap device is a swap file
2. The bootloader used is Grub
3. The `resume=...` parameters are not set in `/boot/grub/grub.cfg` for the current kernel (or maybe `/etc/default/grub`?)

then issue a warning and wait 10 seconds before performing hibernation / require manual user confirmation or some flag passed on the command line.
Also issues like #25130 could be checked during this process.

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by YHNdnzj** [comment]
Manually configuring `resume=` is no longer required on EFI systems, see https://github.com/systemd/systemd/pull/27330.

And this is already implemented in https://github.com/systemd/systemd/pull/28145. Closing.
