### ISSUE TITLE
IPv6 Compliance RFC4191: Processing Router Advertisements with Router Preference (Host Only) [v6LC.2.2.22]

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [systemd/systemd#28439]
### systemd version the issue has been seen with

250

### Used distribution

Embedded Linux - Debian-based

### Linux kernel version used

5.15.71-rt51+gc36e774d0d9a

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

**Purpose**: Verify that the HUT uses a Default Router List with preference values for Type B Host.

When there are two routers on the network and Router1 sends an RA with `Reserved Route Preference`, meanwhile Router2 sends an RA with `Low Preference` route.  Later, Router2 changes from `Reserved` to `High` route preference. This change in preference route ought to result in the host sending to Router2 as the default route.  Instead, it continues to use Router1 as the default router.

From [RFC4191](https://www.rfc-editor.org/rfc/rfc4191.txt):

Section 2.1:
```
   Preference values are encoded as a two-bit signed integer, as
   follows:

      01      High
      00      Medium (default)
      11      Low
      10      Reserved - MUST NOT be sent
```

Section 2.2:
```
Prf (Route Preference)
    If the Reserved (10) value is received, the receiver MUST treat
    the value as if it were (00).
```

Section 3.1:

```
   Type B hosts use a Default Router List augmented with preference
   values, but ignore all Route Information Options.  They use the
   Default Router Preference value in the Router Advertisement header.
   They ignore Route Information Options.
```

### Unexpected behaviour you saw

The router with `Reserved Preference` was used instead of the `High Preference` router.

### Steps to reproduce the problem

Please find attached a zip file containing two PCAP files, `legacy` and `networkd`.  The `legacy` PCAP shows the correct behavior.  It was recorded when our host was configured using Debian's legacy `/etc/network/interfaces` file and `networkd` was disabled and stopped.  The `networkd` PCAP shows incorrect behavior. It was recorded after configuring `networkd` to manage the interface.

Under the `networkd` folder, the PCAP file `v6LC_2_2_22c-Net0-20230707043553-filtered.pcapng` shows the incorrect behaviour. 

Packet 1: Router1 sends an RA with a `Default Router Preference` equal `Reserved`.
Packet 2: Router2 sends an RA with a `Default Router Preference` equal to `Low`.
Packet 6: Router2 sends an RA with a `Default Router Preference` equal to `High`.
Packet 8: Ping reply is sent via Router1, when it should have been sent via Router2.

Compare that with the PCAP showing the correct behaviour in the `legacy` folder, `v6LC_2_2_22c-Net0-20230705084630.pcapng`.

Packet 1: Router1 sends an RA with a `Default Router Preference` equal `Reserved`.
Packet 2: Router2 sends an RA with a `Default Router Preference` equal to `Low`.
Packet 5: Router2 sends an RA with a `Default Router Preference` equal to `High`.
Packet 7: Ping reply is sent via Router2

[2_2_22c - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076148/2_2_22c.-.Processing.Router.Advertisements.with.Router.Preference.zip)

#### Changing Router Preference High to Low
I have second variation where the router preference for Router1 was changed from High to Low, meanwhile Router2 had a preference of Medium.  The host continues to choose Router1 as the default router, when it should be choosing Router2.  This suggests `networkd` is not updating the router preference.  See PCAP files in attached zip.

[2_2_22d - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076417/2_2_22d.-.Processing.Router.Advertisements.with.Router.Preference.zip)

#### Changing Router Low to High
A third variation has Router1 changing from Low to High, meanwhile Router 2 had a preference of Medium.  The host continues to choose Router2 when it should be choosing Router1.

[2_2_22e - Processing Router Advertisements with Router Preference.zip](https://github.com/systemd/systemd/files/12076622/2_2_22e.-.Processing.Router.Advertisements.with.Router.Preference.zip)

**Comment by yuwata** [comment]
@LiveFreeAndRoam Thank you for finding many RFC incompliant behaviors in networkd. But, v250 is slightly old here. Could you test the behaviors in a recent release or the current git HEAD?

**Comment by LiveFreeAndRoam** [comment]
It's difficult for me to update, due to this being an embedded system. Though, I have scanned the release notes and there has been nothing mentioned about IPv6 improvements since v250.  If the release notes are accurate, then we can assume the behaviour will be the same.

Meanwhile, I do have a plan to try to upgrade to the latest and greatest. Ultimately, we need these fixes and I understand you will only be supporting the two most recent releases.  So I am motivated to get to the latest, but it's not a simple task at the moment.

**Comment by yuwata** [comment]
OK. No problem. I have not read your reports in detail yet, but some of them are clearly not supported yet or wrongly implemented in networkd even on recent release. I will take a look. Feel free to open any other incompliance if you find (even that's on v250). Thank you again!

**Comment by evverx** [comment]
@LiveFreeAndRoam just out of curiosity I wonder if those issues have been found automatically using some sort of test suite where `networkd` is compared to `legacy` (which is known to be compliant)? I think if it's already automated somewhere (and can be shared) it would be great to somehow integrate it into the systemd CI to let it do its thing automatically and catch regressions. That part of networkd is being covered in https://github.com/systemd/systemd/pull/28424 but it's more of a smoke test.

**Comment by LiveFreeAndRoam** [comment]
I'm using an IPv6 compliance test suite to identify non-conformance.  The test suite we use is a commercial product.  Though, in years gone by, I have used Tahini.  I can't vouch for whether it's still being maintained, but on their home page, they have links to their conformance test tools: https://www.ipv6ready.org/resources.html.

**Comment by ssahani** [comment]
>Prf (Route Preference)
    If the Reserved (10) value is received, the receiver MUST treat
    the value as if it were (00).

https://github.com/systemd/systemd/blob/df1dccd25547b430258bd42ec60428fc9aff1370/src/libsystemd-network/ndisc-router.c#L100

It's setting pref to `medium` that is `00`.

Here is what is getting configured

> Packet 1: Router1 sends an RA with a Default Router Preference equal Reserved.
```
❯ ip -6 r  show dev veth99
2001:2:0:1000::/64 proto ra metric 1024 expires 65529sec pref medium
fe80::/64 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 29994sec pref medium

❯ ip a show dev veth99    
5: veth99@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ce:a9:a8:53:66:9b brd ff:ff:ff:ff:ff:ff
    inet6 2001:2:0:1000:cca9:a8ff:fe53:669b/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 65515sec preferred_lft 65515sec
    inet6 fe80::cca9:a8ff:fe53:669b/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever

```

> Packet 2: Router2 sends an RA with a Default Router Preference equal to Low.

```
❯ ip -6 r  show dev veth99
2001:2:0:1000::/64 proto ra metric 1024 expires 65529sec pref medium
fe80::/64 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 29923sec pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 2048 expires 29994sec pref low


❯ ip a show dev veth99    
5: veth99@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ce:a9:a8:53:66:9b brd ff:ff:ff:ff:ff:ff
    inet6 2001:2:0:1000:cca9:a8ff:fe53:669b/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 65528sec preferred_lft 65528sec
    inet6 fe80::cca9:a8ff:fe53:669b/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever

```

> Packet 6: Router2 sends an RA with a Default Router Preference equal to High.
```
❯ ip -6 r  show dev veth99
2001:2:0:1000::/64 proto ra metric 1024 expires 65529sec pref medium
fe80::/64 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 512 expires 29994sec pref high
default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 29879sec pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 2048 expires 29949sec pref low

❯ ip a show dev veth99    
5: veth99@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ce:a9:a8:53:66:9b brd ff:ff:ff:ff:ff:ff
    inet6 2001:2:0:1000:cca9:a8ff:fe53:669b/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 65528sec preferred_lft 65528sec
    inet6 fe80::cca9:a8ff:fe53:669b/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever

```

What I am missing ?

**Comment by ssahani** [comment]
With https://github.com/systemd/systemd/pull/28496

> Packet 6: Router2 sends an RA with a Default Router Preference equal to High.
```
❯ ip -6 r  show dev veth99
2001:2:0:1000::/64 proto ra metric 512 expires 65533sec pref high
2001:2:0:1000::/64 proto ra metric 1024 expires 65533sec pref medium
2001:2:0:1000::/64 proto ra metric 2048 expires 65514sec pref low
fe80::/64 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 512 expires 29998sec pref high
default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 29969sec pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 2048 expires 29979sec pref low

```

**Comment by Zugschlus** [comment]
> It's difficult for me to update, due to this being an embedded system. Though, I have scanned the release notes and there has been nothing mentioned about IPv6 improvements since v250. If the release notes are accurate, then we can assume the behaviour will be the same.
> 
> Meanwhile, I do have a plan to try to upgrade to the latest and greatest. Ultimately, we need these fixes and I understand you will only be supporting the two most recent releases. So I am motivated to get to the latest, but it's not a simple task at the moment.

I guess that most of the issues you have discovered might be easily reproducible on a non-embedded system. How about running the test suite against a normal x86_64 system or a Raspi, probably using Arch Linux or Debian unstable? In such envronment it would be vastly easier to run against current code and to try patches.

Btw, I appreciate your work, it is really important.

**Comment by LiveFreeAndRoam** [comment]
A lot has changed since then.  I now have a dedicated network and updated to systemd v255.  My development environment is far more streamlined today, so I can readily validate fixes.

> I guess that most of the issues you have discovered might be easily reproducible on a non-embedded system.

100%.  Our embedded system is still using standard Linux.  We're currently using Linux 6.1.22.

> Btw, I appreciate your work, it is really important.

Thanks.  I'm glad to be in a position to help out with this.  Protocol non-conformance brings a whole mess of issues for network administrators and security pundits.

**Comment by yuwata** [comment]
Fix is waiting in #31173.

**Comment by LiveFreeAndRoam** [comment]
@yuwata, I merged your changes into my branch and reran the IPv6 Conformance tests, 2.2.22[abcde].  The signature has changed a little.  The results show:

* **2.2.22a** - PASS: Processed RA with high preference, no Echo Reply to TR1
* **2.2.22b** - FAIL: Didn't process RA with low preference, no Echo Reply to TR2
* **2.2.22c** - PASS: Processed RA with Reserved preference, Echo Reply to TR2
* **2.2.22d** - FAIL: No Echo Reply to TR2 after RA with a high preference
* **2.2.22e** - FAIL: No Echo Reply to TR2 after RA with Medium preference

Do those failure signatures provide enough information for you to tweak the solution to cover those cases?  If not, then I can go into much greater detail.  Let me know, either way.

**Comment by yuwata** [comment]
Please also provide the debugging logs of networkd during the test.

**Comment by yuwata** [comment]
I may find a root cause why #31173 does not work. I will try to update.

**Comment by LiveFreeAndRoam** [comment]
Let me know when you have it updated and I will retest.

**Comment by pickaxprograms** [comment]
Test V6LC.2.2.22d was broken by the following change in v256-rc4

commit **01420b2db512002cba0600e1d2b4d690efa66688**
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Tue Jun 4 05:29:59 2024 +0900

systemd 256~rc4-g73df6cd^ running in system mode (+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP -LIBCRYPTSETUP_PLUGINS +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT -LIBARCHIVE)

`2024-06-06 14:41:27:
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium

2024-06-06 14:41:34:
2001:2:0:1000::/64 proto ra metric 512 expires 65534sec pref high
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 512 expires 29999sec pref high

2024-06-06 14:41:34:
2001:2:0:1000::/64 proto ra metric 512 expires 65534sec pref high
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 512 expires 29999sec pref high
default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 29999sec pref medium

2024-06-06 14:41:39:
2001:2:0:1000::/64 proto ra metric 512 expires 65529sec pref high
2001:2:0:1000::/64 proto ra metric 2048 expires 65534sec pref low
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 512 expires 29994sec pref high
default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 29994sec pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 2048 expires 29999sec pref low

2024-06-06 14:41:49:
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium`


Test passes for **68adffed0224e4b9c787af296ab34c826c845241** 

systemd[1]: systemd 256~rc1-g68adffe^ running in system mode (+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP -LIBCRYPTSETUP_PLUGINS +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT -LIBARCHIVE)

`2024-05-13 17:24:58:
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium

2024-05-13 17:25:07:
2001:2:0:1000::/64 proto ra metric 512 expires 65534sec pref high
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 512 expires 29999sec pref high

2024-05-13 17:25:07:
2001:2:0:1000::/64 proto ra metric 512 expires 65534sec pref high
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 512 expires 29999sec pref high
default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 29999sec pref medium

2024-05-13 17:25:13:
2001:2:0:1000::/64 proto ra metric 2048 expires 65534sec pref low
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 29994sec pref medium
default via fe80::200:10ff:fe10:1060 proto ra metric 2048 expires 29999sec pref low

2024-05-13 17:25:13:
fe80::/64 proto kernel metric 256 pref medium
multicast ff00::/8 proto kernel metric 256 pref medium`

**Comment by yuwata** [comment]
@pickaxprograms Thank you for testing. Could you test with the current git HEAD? I hope e2060bc124238581d48be159b4da44017f96a26d or something already fixes the issue.

**Comment by pickaxprograms** [comment]
v256.9 fails.
https://github.com/systemd/systemd/commit/e2060bc124238581d48be159b4da44017f96a26d passes.
