### ISSUE TITLE
No colors supported on s390x, log_color is not honored

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#2845]
### Submission type
- [ X ] Bug report
- [ X ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

git master
### Used distribution

ubuntu
### In case of bug report: Expected behaviour you didn't see

1) colors disabled by default on s390[x]
2) systemd.log_color honored by job_print_status_message
### In case of bug report: Unexpected behaviour you saw

1) colors enabled by default on s390x, yet consoles do not support ANSI escape sequence colors
2) systemd.log_color is not honored by job_print_status_message and hence always print ANSI colors
### In case of bug report: Steps to reproduce the problem

1) set LogColor=no via any means
2) boot
3) observe colored green status messages from starting units / reaching targets

**Comment by keszybz** [comment]
If you could check if the PR works for you that'd be great.

**Comment by xnox** [comment]
+1 from me, works like a charm.
