### ISSUE TITLE
systemd-cryptenroll doesnt recognize LUKS key

### ISSUE THREAD

**Issue by LSuessmuth** [systemd/systemd#28451]
### systemd version the issue has been seen with

254rc2-2

### Used distribution

Archlinux

### Linux kernel version used

6.4.3.arch1-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Creation of new LUKS key slot.

### Unexpected behaviour you saw

I feel like you're already aware of the problem, but I didn't find it as an issue.
After running:
`systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7 --tpm2-public-key=pkey.pem --tpm2-public-key-pcrs=11 /dev/sda2`
and typing in the password for the only LUKS keyslot systemd-cryptenroll errors with:

`Password not correct, please try again: Success`

Interestingly enough if I type in the password incorrectly I get a slightly different error:

`Password not correct, please try again: Operation not permitted`

Even more so because I can easily add a key slot using (not systemd) cryptsetup. 

### Steps to reproduce the problem

Basic Arch Linux QEMU VM setup using UEFI Secure Boot, SWTPM with a system partition supposed to be unlocked by a public key policy. Boots and mounts everything perfectly, the only thing missing is the auto unlock of the LUKS2 container. The problem can't be local, I've set up a similar system to this just days before, and it worked just fine using almost the exact same commands as I ran this time (added the public key policy). 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Digest 0 (pdkdf2) verify failed with -1.
Password not correct, please try again: Success
```

**Comment by ddstreet** [comment]
I think this was caused by cefa4a02ab8f3c941e54b5ad1a90b5cf133264a7, which removed the needed second `break`.

**Comment by LSuessmuth** [comment]
Glad that was sorted, but also I want to apologize for misreading tags. Somehow I built it in a testing state. I have trouble understanding how that happened. I genuinely just cloned the arch package, patched something on my own, then built and installed it.
