### ISSUE TITLE
Add the pre-release flag to /etc/os-release as a new variable

### ISSUE THREAD

**Issue by poncovka** [systemd/systemd#28459]
### Is your feature request related to a problem? Please describe

For the Anaconda installer, it would be very helpful to have a new variable in the `/etc/os-release` file that would allow to identify an operating system as a pre-release version. The `fedora-release` package already has a logic for identification of pre-release versions and it is used to generate the `VERSION` and `PRETTY_NAME` values [0]. However, these values are suitable for presentation to the user, not for automatic detection.

At this moment, the Anaconda installer uses two methods for the pre-release identification:

1. We read the `IsFinal` variable in the `/.buildstamp` file [1] generated by Lorax on the boot.iso. This file doesn't exist on Live media, so this method is only usable for systems like Fedora Server.
2. We parse the version of the `fedora-release` package on Live media [2]. This method is used for systems like Fedora Workstation.

We are slowly dropping our dependency on the /.buildstamp file since we cannot rely on its existence and trying to use more values from the /etc/os-release file, because it is more suitable to our needs [3, 4]. It would be great if we could drop both detection methods and rely on the `/etc/os-release` file as the only source of truth.

[0] https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/fedora-release.spec#_1219
[1] https://github.com/rhinstaller/anaconda/blob/135028ec7780bed7642351dc71e17f2f62a6394b/pyanaconda/product.py#L37C1-L37C1
[2] https://github.com/rhinstaller/anaconda/blob/135028ec7780bed7642351dc71e17f2f62a6394b/data/liveinst/liveinst#L36-L41
[3] https://anaconda-installer.readthedocs.io/en/latest/configuration-files.html#profile-detection
[4] https://github.com/rhinstaller/anaconda/pull/4830

### Describe the solution you'd like

Add a machine-readable variable to the `/etc/os-release` file that would allow automatic detection of pre-release versions.

### Describe alternatives you've considered

The same can be achieved with any other file, but that would probably require to synchronize the pre-release detection used for `/etc/os-release` with the pre-release flag from the other file.

* Add a similar variable to any other file that could be used for this purpose.
* Create a new flag file that would exist only on pre-release versions.

**Comment by bluca** [comment]
There are tons of ID fields already, can't you use one of the existing ones?

**Comment by sgallagher** [comment]
The request is specifically to have a distribution-agnostic way of detecting pre-release. I think it's absolutely sensible to have a documented variable for this purpose.

I propose `PRERELEASE_ID` for which any non-zero-length string indicates a prerelease OS. This string must be machine-readable. We may also want `PRETTY_PRERELEASE` as a translatable presentation string.

**Comment by bluca** [comment]
Can't you use the VARIANT fields, for example? There's also BUILD_ID that you can use for this

**Comment by VladimirSlavik** [comment]
These are all free form text, the request is for something that can be interpreted as a boolean.

**Comment by poncovka** [comment]
Let me show you what we have available right now:

* Here is an example of `/etc/os-release` from a final release (`Fedora-Server-netinst-x86_64-38-1.6.iso`):

```
NAME="Fedora Linux"
VERSION="38 (Server Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Server Edition"
VARIANT_ID=server
```

* Here is an example of `/etc/os-release` from a pre-release (`Fedora-Server-netinst-x86_64-38_Beta-1.3.iso`):

```
NAME="Fedora Linux"
VERSION="38 (Server Edition Prerelease)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Server Edition Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Server Edition"
VARIANT_ID=server
```

Some additional info about the Anaconda installer:

* The  installer is used by many distributions (not just Fedora, CentOS and RHEL).
* We don't have a full list of distributions and we are not aware of their release schedules.
* We have no control over the switch from a pre-release to a final release. That's up to the distributions.
* Our releases are not in any way tied to this switch. The final release doesn't require a new release of Anaconda.
* The solution should have minimal impact on all distributions. If it breaks something, we will be probably asked to provide an alternative method (and we don't want to support two different methods again).

> Can't you use the VARIANT fields, for example?

These fields are used to identify specific variants or editions of the operating system (Workstation vs Server). Variants can be also pre-releases and we need to be able to identify them by their `VARIANT_ID`.

> There's also BUILD_ID that you can use for this.

Based on the [documentation](https://www.freedesktop.org/software/systemd/man/os-release.html), this field should be used to uniquely identify the system image originally used as the installation base (for example, `BUILD_ID=201303203`). I don't see how it fits into our use case.

> There are tons of ID fields already, can't you use one of the existing ones?

I couldn't find in the documentation any machine-readable field that could be used to somehow mark a pre-release. I have found that "lines beginning with "#" are treated as comments", so another option would be to mark pre-releases via a special comment in `/etc/os-release`.

**Comment by sgallagher** [comment]
> I couldn't find in the documentation any machine-readable field that could be used to somehow mark a pre-release. I have found that "lines beginning with "#" are treated as comments", so another option would be to mark pre-releases via a special comment in `/etc/os-release`.

Comments are meant to be about the content of the `os-release` file, not to be read by other services. The `os-release` file itself is meant to be `source`-able from most shells. Let's absolutely not start making comments into code, please.




> Can't you use the VARIANT fields, for example? There's also BUILD_ID that you can use for this

```
A lower-case string (no spaces or other characters outside of 0–9, a–z, ".", "_" and "-"),
identifying a specific variant or edition of the operating system. This may be interpreted by
other packages in order to determine a divergent default configuration. This field is optional
and may not be implemented on all systems.
```

That sounds pretty clearly about describing a different OS configuration rather than pre-release state.

**Comment by poettering** [comment]
hmm, I think this might make sense, so that things like gnome system config UI could even show "hey, this is a pre-release" in red or so when you look there.

I wonder though whether it wouldn#t be better to introduce this as special SUPPORT_STATUS= field that can more precisely decalre the lifecycle/support state of the image, i.e. would take one of "development", "testing", "production", "ci-build" or so? "pre-releases" would then set SUPPORT_STATUS=testing or so, and the final build SUPPORT_STATUS=production. Images that are not build for human testing, but as part of CI for CI testing would use SUPPORT_STATUS=ci-build or so? Developers on their local machines "development"?

**Comment by sgallagher** [comment]
> 

I like this idea a lot, but the main concern I have about defining an ENUM of the status values is the classic bikeshedding problem. Also, we will need to be **very** specific about the definitions. For example, what is the difference between "development", "testing" and "ci-build"? Why would we use one over another?

I'd like to counter-propose:
Add `SUPPORT_STATUS_ID` which allows only two options "production" and "non-production" as machine-readable values indicating whether this is or is not intended for general usage.
Add `SUPPORT_STATUS` which is a human-readable string that should be used only for display purposes that more clearly describes it.

**Comment by poettering** [comment]
sure, i mean, for the enum we shouldn#t define values noone is asking for ahead of time, but have the option to add them eventually if people ask for this. so if fedora/rhel wants just distinguish two cases we should just add these two initially, and extend later, and document that there will be new values added eventually.

**Comment by poettering** [comment]
This was addressed in the meantime, via the new RELEASE_TYPE= field.

d25a9bfa8f8bd42b769dbf2f9786348864cf5e08 (and later commits).

here's how this currently reads:

https://github.com/systemd/systemd/blob/main/man/os-release.xml#L329

I guess we can close this now.

**Comment by sgallagher** [comment]
I concur; using `RELEASE_TYPE=development` or `RELEASE_TYPE=stable` seems like the appropriate solution here and should meet @poncovka 's original requirements.
