### ISSUE TITLE
PREF64 Option support for Router Advertisements

### ISSUE THREAD

**Issue by mweinelt** [systemd/systemd#28462]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

Linux is currently lacking RAdv implementations, that can announce a translation prefix via the PREF64 option ([RFC8781](https://datatracker.ietf.org/doc/html/rfc8781)), which is required for nudging clients to make use of a NAT64 translator on the network.

### Describe the solution you'd like

Allow announcing the PREF64 option, containing one or multiple prefixes (up to /96 in size), in Router Advertisements.

```
[IPv6SendRA]
EmitPref64=true
Pref64Prefix=64:ff9b::/96
```

or

```
[Pref64Prefix]
Prefix=64:ff9b::/96
```

https://github.com/systemd/systemd/issues/23674 asks for the client side (setting up a SIIT tunnel) based on the PREF64 option seen in RAdvs. This issue is about being able to send out the PREF64 option in RAdvs.

### Describe alternatives you've considered

Using an alternative RAdv implementation.

- https://github.com/radvd-project/radvd/pull/179 (merged, but unreleased)
- https://gitlab.nic.cz/labs/bird/-/commit/9c81250c04798fd274ae9d77380e93b941ac2d7f (merged, but unreleased)

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by ssahani** [comment]
I posted a draft https://github.com/systemd/systemd/pull/28565

**Comment by ssahani** [comment]
We can close this

**Comment by Neustradamus** [comment]
@mweinelt and others: I have commented the issue to request a radvd 2.20 release build, maybe you can comment too?
- https://github.com/radvd-project/radvd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by pemensik** [comment]
Does this merge mean systemd-networkd can emit RA containing PREF64 or it can *also* receive and process such announces?
It seems to me only server-side of the problem were handled, but client-side is not handled in any way. Can it present also range obtained from RA at client?

**Comment by mweinelt** [comment]
It can emit them. Processing them is IMO part of https://github.com/systemd/systemd/issues/23674.

**Comment by Djfe** [comment]
[v2.20](https://github.com/radvd-project/radvd/releases/tag/v2.20) was released recently, in-case you missed it :)
