### ISSUE TITLE
"failed to get cgroup ignoring no medium found"

### ISSUE THREAD

**Issue by memory-colors** [systemd/systemd#28469]
### systemd version the issue has been seen with

254-rc2-3

### Used distribution

Debian Unstable

### Linux kernel version used

6.3.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

The message "failed to get cgroup ignoring no medium found" appears after GRUB screen. System boots normally.

### Steps to reproduce the problem

Upgrade to 254-rc2-3, reboot.

**Comment by mbiebl** [comment]
I'm seeing that as well (initramfs-tools, not dracut). Besides the error message during early boot, I haven't noticed any ill effects caused by it.

**Comment by mbiebl** [comment]
Do we have to update initramfs-tools in the way it mounts / sets up cgroups ?

**Comment by bluca** [comment]
@yuwata will anything break in udev if it runs without cgroup fs?

**Comment by memory-colors** [comment]
> valid

I've never set up cgroups. This is a relatively recent installation.

**Comment by yuwata** [comment]
Fix is waiting in #28477.
