### ISSUE TITLE
With v254-rc2 and with ISO-Hybrid images udev chooses to assign the by-label symlink to the parent device 

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#28468]
### systemd version the issue has been seen with

254-rc2

### Used distribution

openSUSE TW

### Linux kernel version used

Not relevant

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Commit 331aa7aa15ee5dd12b369b276f575d521435eb52 has an unexpected side effect: with this commit applied and when a block device has several partitions and one of the partition and the parent device share the same label then the symlink /dev/disk/by-label/<shared-label> will be owned by the parent device, not by the partition anymore.

This is a pretty common setup with ISO-Hybrid images actually, see https://github.com/systemd/systemd/issues/12409 for more details.

The problem is that if one mounts the device by following the label symlink it will mount the parent device instead of the partition one as before. And mounting the parent device prevents the partitions from being mounted.

I know that there hasn't been any guaranty for the partition device to always get the symlink but from the user perspective this is a regression.

We could simply workaround this by increasing the priority of by-label symlinks for partition devices but I'm not sure whether this won't introduce other new issues.

### Steps to reproduce the problem

Grab any ISO-Hybrid image and dump it into a disk. Plug the disk into the system and look at where the by-label symlink points to:

```
# lsblk --fs /dev/vdb
NAME   FSTYPE  FSVER            LABEL                            UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
vdb    iso9660 Joliet Extension openSUSE-Leap-15.5-NET-x86_64484 2023-05-11-23-41-04-05                              
├─vdb1 vfat    FAT16                                             FC15-5145                                           
└─vdb2 iso9660 Joliet Extension openSUSE-Leap-15.5-NET-x86_64484 2023-05-11-23-41-03-72 
                        
# ls -l /dev/disk/by-label/
total 0
lrwxrwxrwx 1 root root 9 Jul 19 17:34 openSUSE-Leap-15.5-NET-x86_64484 -> ../../vdb
```

Mount the device owning the symlink:
```
# mount /dev/disk/by-label/openSUSE-Leap-15.5-NET-x86_64484 /mnt
mount: /mnt: WARNING: source write-protected, mounted read-only.
```
Then mounting any partition of the disk fails:
```
# mount /dev/vdb1  /mnt/
mount: /mnt: /dev/vdb1 already mounted or mount point busy.
```

**Comment by fbuihuu** [comment]
Cc @yuwata @bluca

**Comment by bluca** [comment]
Can you provide instructions to create a minimal block device that shows the issue? With sfdisk or so?

**Comment by fbuihuu** [comment]
I simply grabbed the ISO-Hybrid image available at https://download.opensuse.org/distribution/leap/15.5/iso/openSUSE-Leap-15.5-NET-x86_64-Build491.1-Media.iso and booted a VM with the image as a secondary disk.

**Comment by bluca** [comment]
something like that cannot be added to the CI, and also if you want someone else to look at it, with a self-contained small reproducer it's going to be much easier

**Comment by yuwata** [comment]
@fbuihuu Could you provide result of `udevadm info /dev/vdb /dev/vdb2` ?

**Comment by fbuihuu** [comment]
Sure: https://gist.github.com/fbuihuu/891414bda89aa6856e9f7b880af8d47b
