### ISSUE TITLE
systemd-shutdown[1] - Failed to get MD_LEVEL property

### ISSUE THREAD

**Issue by kdeb881** [systemd/systemd#28490]
### systemd version the issue has been seen with

252.12

### Used distribution

Debian 12 (Proxmox PVE8)

### Linux kernel version used

6.2.16-4-pve

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-udevd, udevadm, other

### Expected behaviour you didn't see

The server shutdown/reboot should work without issue.

### Unexpected behaviour you saw

The server shutdown/reboot is not possible, because the systemd process is hanging and looping the following message:
"sytemd-shutdown[1] - Failed to get MD_LEVEL property for /dev/md0, ignoring: No such file or directory"
"sytemd-shutdown[1] - Failed to get MD_LEVEL property for /dev/md0, ignoring: No such file or directory"
...

Manual "reset-button" or power-cut is needed to reboot/shutdown the server.
Is it related to?
 https://github.com/canonical/probert/issues/125

As far as I can tell you, the "/etc/fstab" mount option "errors=remount-ro" causing this loop problem. ( I'm using this option in every mount ).
The systemd process reaching "reboot.target" / "shutdown.target" - it tries executing the "sd-remount.service" and "sd-mount.service" this causing the loop ( the mapper devices are already stopped/deleted - it is impossible to mount/remount the filesystem from it)

### Steps to reproduce the problem

1., Install Base System
Install Debian12,
Install PVE kernel,

/etc/apt/sources.list
`deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription`

`$> wget -q "http://download.proxmox.com/debian/proxmox-release-bookworm.gpg" -O- | apt-key add -`

2., Install PVE kernel
`$> apt-get install pve-kernel-6.2`
REBOOT
`$> apt-get install systemd mdadm dracut-core sgdisk parted`
REBOOT

3., Create MD device RAID-1 - add LVM, add EXT4 - on top
--> /dev/sdc
--> /dev/sdd

`$> sgdisk --clear -Z /dev/sdc`
`$> sgdisk --clear -Z /dev/sdd`

`$> parted -s /dev/sdc mklabel gpt`
`$> parted -s /dev/sdd mklabel gpt`

`$> parted -s /dev/sdc mkpart primary 0% 100%`
`$> parted -s /dev/sdd mkpart primary 0% 100%`

`$> mdadm --create /dev/md1 --name="PVE_DATA" --assume-clean --verbose --metadata 1.0 --level=1 --raid-devices=2 /dev/sdc1 /dev/sdd1`

`$> wipefs --all --force /dev/md1`

`$> pvcreate -v /dev/md1`
`$> vgcreate -v RAID /dev/md1`
`$> lvcreate -v -l 90%FREE -n NAS RAID`

`$> parted -s /dev/mapper/RAID-NAS mklabel gpt`
`$> mkfs.ext4 /dev/mapper/RAID-NAS -L RAID-NAS -E lazy_itable_init=0,lazy_journal_init=0`

4., Add EXT4 Volume to the fstab
`$> mkdir /raid`
`$>blkid /dev/mapper/RAID-NAS`
/etc/fstab
UUID="<blkid>" /raid ext4 defaults,acl,nodiscard,nobarrier,errors=remount-ro,nofail 0 1

5., Add mdadm config to the initramfs
`$> echo "AUTO * -all" > /etc/mdadm/mdadm.conf`
`$> mdadm --detail --scan >> /etc/mdadm/mdadm.conf`
`$> update-initramfs -c -d -u`

6., Update Mount
`$> mount -a`

7., Add file test file to the RAID/LVM/EXT4
`$> echo "test123" > /raid/test123`

8., Try to Reboot/Shutdown the system
`$> systemctl reboot`
or
`$> systemctl poweroff`

9, System will hang, looping the following message:
`"sytemd-shutdown[1] - Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory"`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[54.882310] watchdog: watchdogo: watchdog did not stop!
[55.047108] systemd-shutdown [1]: Could not stop MD /dev/md1: No such device
[55.047134] watchdog: watchdog: watchdog did not stop!
[55.055696] systemd-shutdown [1]: Failed to finalize MD devices, ignoring.

[3.811775] systemd-shutdown [1]: Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory
[43.812342] systemd-shutdown[1]: Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory
[43.812905] systemd-shutdown[1]: Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory
[43.813468] systemd-shutdown[1]: Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory
[43.814082] systemd-shutdown[1]: Failed to get MD_LEVEL property for /dev/md1, ignoring: No such file or directory
```

**Comment by poettering** [comment]
@mtkaczyk any chance you can comment on this? how come MD_LEVEL is not set for @kdeb881's MD device?

Is that a new property? where it is precisely set?

I have the suspicion we should treat the absence of the property as an indication we should detach the device though, i.e. invert the current logic on ENOENT of the property.

but first I'd like to udnerstand more..

**Comment by poettering** [comment]
Ah, so @YHNdnzj tracked it down. the property comes from mdadm:

https://github.com/neilbrown/mdadm/blob/5f4184557a98bb641a7889e280265109c73e2f43/udev-md-raid-arrays.rules#L20
https://github.com/neilbrown/mdadm/blob/5f4184557a98bb641a7889e280265109c73e2f43/super0.c#L291

So my educated guess is that your system @kdeb881 lacks a properly configured mdadm setup, i.e. the udev property is simply missing?

**Comment by poettering** [comment]
Does #28705 help on your system?

(It might solve the issue you are running into fully, but fix at least part of it)

**Comment by mtkaczyk** [comment]
@kdeb881 could you please provide:
```
# cat /sys/block/md1/md/level
# mdadm --detail --export --no-devices /dev/md1
```
I'm really surprised that the property may not exist. The property exists for every MD device, from the beginning.
I did some stupid testing:
```
[gklab-localhost ~]# echo md74 > /sys/module/md_mod/parameters/new_array
[gklab-localhost ~]# cat /sys/block/md74/md/level
[gklab-localhost ~]# echo 8 > /sys/block/md74/md/level
[gklab-localhost ~]# cat /sys/block/md74/md/level
8
[gklab-localhost ~]# echo "" > /sys/block/md74/md/level
[gklab-localhost ~]# cat /sys/block/md74/md/level
[gklab-localhost ~]# cat /sys/block/md74/md/level
```
Here kernel code:
https://elixir.bootlin.com/linux/latest/source/drivers/md/md.c#L3831
Looks like the filed may take whatever you write.

@poettering in case of `--detail` the MD_LEVEL property comes from this place:
https://github.com/neilbrown/mdadm/blob/5f4184557a98bb641a7889e280265109c73e2f43/Detail.c#L232

It is NULL aware, may not be printed, but is is extremally weird to have this filed cleared because nobady cares. In case of stopping "clear" is written to the `md/array_state` an the level is removed with MD device but it is never overwritten (expect some reshapes- not in this scenario ). It is set once on create/assembly.

There must be something else but agree that if we cannot obtain it we should skip the device.

**Comment by yuwata** [comment]
#28705 is already merged. Closing.
Please request to reopen this page if the commit does not work for you.
