### ISSUE TITLE
Udev symlink collisions can cause root fs to be replaced

### ISSUE THREAD

**Issue by ElvishJerricco** [systemd/systemd#28491]
### systemd version the issue has been seen with

253.5

### Used distribution

NixOS 23.11-pre

### Linux kernel version used

6.3.12

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

The device mounted on `/` should not change when a new device is plugged in before booting.

### Unexpected behaviour you saw

If a device is plugged in that would claim the same symlink via udev rules as the root FS, initrd might end up mounting and booting that device instead if it has an OS on it.

### Steps to reproduce the problem

Create a device with a file system on it that will claim the same symlink that the root FS should. There are a variety of scenarios that might require different approaches.

- If `root=UUID=...`, then create a file system with that UUID.
- If `root=gpt-auto`, then create a device with an ESP (even if empty) that has the same PartUUID as the system's ESP, and add another partition with the appropriate `gpt-auto` partition type GUID to that device.
- If `root=/dev/mapper/vgname_lvname` (for some LVM VG and LV), create a device with the same LVM layout.
- I'm sure there are other scenarios and methods that will trigger the issue.

If initrd has kernel modules for the attached device, it can see that device take the symlink first, set the corresponding device unit to active, and continue with the boot using that device. It's possible that the real device appears in the middle, such as during fsck, so that it ends up taking the link by the time `sysroot.mount` starts, but this is not guaranteed and if the device is delayed by mechanisms like LUKS it is rather unlikely.

**Comment by poettering** [comment]
yeah, uuids are just hints where to find resources, they are not cryptographic handles. 

if you want cryptographic handles, use cryptographic handles, i.e. verity root hashes or luks disk encryption keys, maybe bound to TPM. In that case you can still produce a DoS by providing two disks with the same uuid, but it won't be mountable anymore.

Hence: don#t misunderstand what fs uuids are for.

systemd-gpt-auto-generator will reference disks by "DISKSEQ" on new enough kernels btw, i.e. via an identifier that is guaranteed to be unique for a specific medium and only as long as it remains plugged in continously. This will make certain attacks harder where you swap out a disk or medium while it is being used. But it's still not complete, as the diskseq is only tracked in the time where we dissect the GPT and mount it. the kernel's fs implementations do not invalidate mounts with the diskseq of their block devices changes yet. but this is being discussed upstream, and I don't think we need to track this here.

hence. closing, as there's nothing actionable for us here afaics. or what am I missing?

**Comment by ElvishJerricco** [comment]
@poettering One idea I had was having the boot loader or the stub pass along the UEFI device path of the ESP. Wouldn't that be significantly less flimsy than using the ESP's PartUUID?

As for "cryptographic handles", I don't see how to accomplish what you're talking about when using vendor keys rather than self signing. As is, `gpt-auto` will decrypt your LUKS root fs with the TPM and then boot a different vendor signed disk. The problem here isn't the keys; it's that it chose to decrypt one disk and boot another, which is caused by these udev rules: https://github.com/systemd/systemd/blob/bcb299e461a1d0b58e1cac26e28e6f22b3e1115f/rules.d/99-systemd.rules.in#L30-L33
