### ISSUE TITLE
systemd-binfmt fails on boot if binfmt is missing from fstab

### ISSUE THREAD

**Issue by bobrik** [systemd/systemd#28501]
### systemd version the issue has been seen with

252

### Used distribution

Debian Bookworm

### Linux kernel version used

6.5.0-rc3, but irrelevant

### CPU architectures issue was seen on

aarch64

### Component

systemd-binfmt

### Expected behaviour you didn't see

No errors on boot.

### Unexpected behaviour you saw

This on the console:

```
[FAILED] Failed to start systemd-bi… Set Up Additional Binary Formats.
```

```
ivan@vm:~$ sudo systemctl status systemd-binfmt
× systemd-binfmt.service - Set Up Additional Binary Formats
     Loaded: loaded (/lib/systemd/system/systemd-binfmt.service; static)
     Active: failed (Result: exit-code) since Mon 2023-07-10 21:44:35 UTC; 1 week 6 days ago
       Docs: man:systemd-binfmt.service(8)
             man:binfmt.d(5)
             https://docs.kernel.org/admin-guide/binfmt-misc.html
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
    Process: 826 ExecStart=/lib/systemd/systemd-binfmt (code=exited, status=1/FAILURE)
   Main PID: 826 (code=exited, status=1/FAILURE)
        CPU: 2ms

Jul 10 21:44:35 vm systemd[1]: Starting systemd-binfmt.service - Set Up Additional Binary Formats...
Jul 10 21:44:35 vm systemd-binfmt[826]: Failed to flush binfmt_misc rules, ignoring: No such file or directory
Jul 10 21:44:35 vm systemd-binfmt[826]: /usr/lib/binfmt.d/python3.11.conf:1: Failed to add binary format 'python3.11': No such file or directory
Jul 10 21:44:35 vm systemd[1]: systemd-binfmt.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 21:44:35 vm systemd[1]: systemd-binfmt.service: Failed with result 'exit-code'.
Jul 10 21:44:35 vm systemd[1]: Failed to start systemd-binfmt.service - Set Up Additional Binary Formats.
```

In `/lib/systemd/system/systemd-binfmt.service` there's this:

```
After=proc-sys-fs-binfmt_misc.automount
After=proc-sys-fs-binfmt_misc.mount
```

Both of these do not apply if `binfmt_misc` is missing from `/etc/fstab`. Still, `systemd-binfmt.service` starts and fails at runtime.

I think we want to have `ConditionPathIsMountPoint=/proc/sys/fs/binfmt_misc` in the unit file as it seems to work as expected whether the mount is present (the service runs successfully) or not (the service doesn't run, which means it doesn't fail). I'm happy to make a PR if this makes sense.

### Steps to reproduce the problem

1. Start systemd without binfmt mount present in `/etc/fstab`

**Comment by yuwata** [comment]
That's already fixed by f74a7cb45c2458f90de6d37c70fa3afc1a3be279 (v253). Closing.
