### ISSUE TITLE
IPv4 LinkLocal IP does not ping while IPv6 LinkLocal IP reachable

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#28510]
### systemd version the issue has been seen with

253.1

### Used distribution

linux 

### Linux kernel version used

6.1.12-c66ca96

### CPU architectures issue was seen on

arm

### Component

systemd-networkd

### Expected behaviour you didn't see

Directly connected a helper machine to system's ethernet port using ethernet cable.
I see both IPv6 and IPv4 link local IPs on system's ethernet interface
I see IPv6 link local IP is reachable while IPv4 link local IP does not ping from helper machine.
Expecting both IPv4 and IPv6 link local ip addresses needs to be reachable on a direct point to point ethernet connection 

### Unexpected behaviour you saw

IPv4 link local IP does not work while IPv6 link local IP reachable.

### Steps to reproduce the problem

1. Connect system's ethernet interface to helper machine via ethernet cable 
2. check if ping work for both ipv4 and ipv6 link local addresses.

**Comment by poettering** [comment]
not actionable. You didnt provide the .network files you used. You didn't show us what "ip addr" or "networkctl status" reports. No tcpdump info. No cmdlines you used. Nothing.

This smells a lot like a user support problem, not a bug tbh. Hence please contact the systemd mailing list. This is only for bugs and feature requests, and this looks very much like neither to me, but a user config issue.

hence: → https://lists.freedesktop.org/mailman/listinfo/systemd-devel
