### ISSUE TITLE
spell error

### ISSUE THREAD

**Issue by maliangzhu** [systemd/systemd#28539]
### systemd version the issue has been seen with

254

### CPU architectures issue was seen on

None

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
swapiness should be swappiness


static const JsonDispatch table[] = { 
                { "swapiness",        JSON_VARIANT_NUMBER,  oci_unsupported,         0,                                         JSON_PERMISSIVE }, 
                {}
        };
```

**Comment by keszybz** [comment]
Unfortunately we're just following the OCI spec here:
https://github.com/systemd/systemd/blob/859ecf0aaa51ac1f5bcefab3fb1ba6156de9d851/src/nspawn/nspawn-oci.c#L62

We don't want to introduce an alternative spelling, because that'd create an incompatibility.
