### ISSUE TITLE
capture memory.peak before cgroups ending for memoryaccounting enabled units

### ISSUE THREAD

**Issue by toppk** [systemd/systemd#28542]
### Component

systemd, systemd-run

### Is your feature request related to a problem? Please describe

I would like to capture memory.peak from cgroup v2 information for units with memoryaccounting enabled.

### Describe the solution you'd like

so if I were to run `systemd-run --wait -t    --property=MemoryAccounting=1 --property=CPUAccounting=1 --property=IOAccounting=1 dnf upgrade --assumeno`

would include the output:
```
MEM peak bytes used: 1.1GB
```

### Describe alternatives you've considered

writing software to trying to capture /sys/fs/cgroup/*/memory.peak information right before it disappears.

### The systemd version you checked that didn't have the feature you are asking for

253.7 as in f38

**Comment by Flowdalic** [comment]
With 255_rc3 I no longer see the "Memory peak:" output

```bash
$ sudo systemd-run --wait -t --property=MemoryAccounting=1 sleep .1
Running as unit: run-u121.service; invocation ID: f57e01138cfe4a8598f61e7a1fe93452
Press ^] three times within 1s to disconnect TTY.
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 101ms
CPU time consumed: 776us
```

it previously was

```bash
$ sudo systemd-run --wait -t --property=MemoryAccounting=1 sleep .1 
Running as unit: run-u246.service; invocation ID: d9a71ef36b844378b379f3ef49642389
Press ^] three times within 1s to disconnect TTY.
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 115ms
CPU time consumed: 2ms
Memory peak: 256.0K
```

Can someone verify this and potentially re-open this issue?

**Comment by YHNdnzj** [comment]
@Flowdalic Indeed... I'll try to look into it.
