### ISSUE TITLE
fstab-generator: make fsck and remount-fs work with systemd.mount-extra=

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#28541]
From https://github.com/systemd/systemd/pull/28518#issuecomment-1652228998
```
root=/dev/fedora/root-snap ro rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/fedora/root-snap:/:ext4:rw systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults
```
Then, the root mount is in read only as remount-fs.service is not pulled in.

https://github.com/systemd/systemd/pull/28518#issuecomment-1653390555
If `root=` is dropped, then /sysroot is mounted in rw as expected, but fsck will not be enabled on the mounts.

**Comment by bmr-cymru** [comment]
I have a strong preference for using `root=` to specify the root file system. There is existing tooling that generates this boot syntax and it would be complicated to adapt it to handle either `root=` or `systemd.mount-extra` for the root fs.

It would be ideal if this could work like systemd-gpt-auto-generator and support `root=` if it is defined.

**Comment by poettering** [comment]
i am not sure i follow? the kernel cmdline said "ro" for the root fs, and there's no other source of truth that says otherwise, so we should stick to it, which sounds totally how it should be.

if you want the root fs writable, then drop "ro", or specify "rw" instead?

**Comment by bmr-cymru** [comment]
Yes it's expected that it's initially mounted ro during the initrd but I'd like to see it behave like a regular fstab boot case, where `systemd-remount-fs.service` remounts to rw later in the boot. I realise that that service parses the fstab (and we're booting with `fstab=no`...) but could this be handled like gpt-auto-generator and allow the conventional `root=... ro` and later remount? That would make everything consistent with the regular case and would mean there's no special twiddling or ro/rw needed for snapshot boot.

**Comment by bmr-cymru** [comment]
OK that's something we can deal with. I didn't realise that the ro/rw handling for fstab was only preserved for compat reasons. It's a minor issue - this is otherwise working exactly as expected.

**Comment by poettering** [comment]
> OK that's something we can deal with. I didn't realise that the ro/rw handling for fstab was only preserved for compat reasons. It's a minor issue - this is otherwise working exactly as expected.

yeah, the ro/rw thing is really weird, as we generally say that kernel cmdline params override configuration files, but this one is the other way round, fstab trumps ro/rw. We have to do it like this for compat reasons but I am not convinced that it should be a model for anything or something we have to extend for new developments-

**Comment by yuwata** [comment]
I agree with that `ro/rw` setting should be honored. We already do that in gpt-auto generator.

> so i guess we can close this?

Yeah. Closing.
