### ISSUE TITLE
Weird warnings with bind mount

### ISSUE THREAD

**Issue by plomari** [systemd/systemd#28553]
### systemd version the issue has been seen with

254~rc3-3

### Used distribution

Debian unstable

### Linux kernel version used

5.10.179

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

No warnings.

### Unexpected behaviour you saw

During apt dist-upgrade I got multiple messages (maybe 20-40 times) of this:
` systemd-fstab-generator[3933506]: Checking was requested for "/mnt/foo/bar", but it is not a device.`
Always with the same path, but a different PID every time. The path isn't literally `foo/bar`, I edited the actual path because I didn't want to mention it in a public issue. The same applies to the fstab excerpts below.

### Steps to reproduce the problem

Unknown. I have 2 bind mounts in my `/etc/fstab`:
```
LABEL=whatever /mnt/home_noo/ ext4 noatime            0       3
/mnt/home_noo/home /home/noo none    rw,bind         0       0
<other stuff>
LABEL=main02 /mnt/foo ext4 noauto,noatime 0 3
LABEL=main01 /mnt/main01 ext4 noauto,noatime 0 3
/mnt/main01/bar /mnt/foo/bar none rw,bind 0 4
```
It never warns about that first bind mount, only the second one.

I don't know if there's a problem, but I don't want systemd to mess up and corrupt my disks by somehow using old fstab entries or other completely intransparent, undebuggable mysterious problems. Why is the message appearing multiple times? Why is there some kind of "generator"?

**Comment by mrc0mmand** [comment]
The issue is that you explicitly requested to run file system check for the second bind mount by setting the sixth field to a non-zero value. From `fstab(5)`:

```
   The sixth field (fs_passno).
       This field is used by fsck(8) to determine the order in which filesystem checks are done at boot time.
       The root filesystem should be specified with a fs_passno of 1. Other filesystems should have a fs_passno
       of 2. Filesystems within a drive will be checked sequentially, but filesystems on different drives will
       be checked at the same time to utilize parallelism available in the hardware. Defaults to zero (don’t
       check the filesystem) if not present.
```

> Why is there some kind of "generator"?

systemd provides `systemd-fstab-generator` that generates native mount units for every mount in `/etc/fstab`, see `systemd-fstab-generator(8)`.

**Comment by plomari** [comment]
> The issue is that you explicitly requested to run file system check for the second bind mount by setting the sixth field to a non-zero value. From fstab(5):

I misunderstood this field. I thought it was used for mount order too. Thanks for clarifying and sorry for the noise.

> systemd provides systemd-fstab-generator that generates native mount units for every mount in /etc/fstab, see systemd-fstab-generator(8).

Can I prevent the generation of native mount units? I only want them to be mounted at boot time, in this specific case I don't even want that (`noauto`), I just want `mount` to work. (I forgot to add a `noauto` to one of the entries.)

**Comment by mrc0mmand** [comment]
> > The issue is that you explicitly requested to run file system check for the second bind mount by setting the sixth field to a non-zero value. From fstab(5):
> 
> I misunderstood this field. I thought it was used for mount order too. Thanks for clarifying and sorry for the noise.
> 
> > systemd provides systemd-fstab-generator that generates native mount units for every mount in /etc/fstab, see systemd-fstab-generator(8).
> 
> Can I prevent the generation of native mount units? I only want them to be mounted at boot time, in this specific case I don't even want that (`noauto`), I just want `mount` to work. (I forgot to add a `noauto` to one of the entries.)

No, not really, it's how systemd works and how it tracks the state of the mounts among other things.

**Comment by plomari** [comment]
>No, not really, it's how systemd works and how it tracks the state of the mounts among other things.

What for? Doesn't it just need to call `mount -a` on boot and `umount -a` on shutdown?
