### ISSUE TITLE
systemd-udevd runs out of FDs on large systems

### ISSUE THREAD

**Issue by balrog-kun** [systemd/systemd#28583]
### systemd version the issue has been seen with

252

### Used distribution

CentOS Stream 9 based

### Linux kernel version used

6.2.0 based

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

systemd-udevd keeps responding to udevadm requests for the whole runtime of the system.

### Unexpected behaviour you saw

On these test machines with 8 sockets (960 CPUs) and 6.2.0-based kernels, `udevadm settle` would time out every time, during OS installation (which would take 13 hours because of this) and on the installed system (which was harmless).  Max open files ulimit is 1024, this seems suspiciously close to the 960 number.  The logs show, among other messages:
```
Jul 11 16:32:26 localhost systemd-udevd[9746]: Failed to accept ctrl connection: Too many open files
Jul 11 16:32:28 localhost systemd-udevd[9746]: Failed to send readiness notification, ignoring: Too many open files
```

For some reason this didn't happen with a CentOS Stream 8-based system, but I don't think it was because of the kernel version.  Our CS9 installer still runs a 5.15 kernel during installation and 6.2.0 on the installed system.  So possibly it was related to an older systemd version, I don't know what version it was and I have no means to bisect the issue.

It didn't happen on 4-socket systems either.

**Comment by balrog-kun** [comment]
So I have no explanation why the number of CPUs would affect systemd-udevd, maybe there is a sysfs or procfs file per-CPU that it was opening.  Or maybe there was a client process per-CPU.  In any case it may be something outside of systemd-udevd's control.

If it was systemd-udevd opening that many sysfs or procfs files, then I have no explanation why it'd do this in parallel -- otherwise it wouldn't reach so many open FDs at the same time.

But two things should happen that apparently didn't happen:
- systemd-udevd didn't recover after that situation.  When I log into the device, the number of open FDs shows in `/proc/``pidof systemd-udevd``/fdinfo` was low but that the daemon wouldn't respond to ctrl socket connections until it was restarted.  Once it was restarted, for some reason it wouldn't hit that bug again.
- Since there is no universal LimitNOFILE value that will suit every future machine, systemd-udevd itself possibly should watch its max open files limit and avoid reaching queueing requests, or by enlarging it own limit (not sure if possible in process runtime...)

**Comment by yuwata** [comment]
As a workaround, please set `udev.children_max=` in the kernel command line.

**Comment by poettering** [comment]
So we should call rlimit_nofile_bump() early on in udev's main(), and then make sure to add rlimit_nofile_safe() before each callout. That should suffice.

(this would mean, udev itself runs with RLIMIT_NOFILE's soft limit upgraded to the hard limit, but the soft limit is reset to 1K for callouts, since larger soft limits break select() – which we never use, but crappy callouts might still do).

since a longer time systemd will raise the fd hard limit to very high values at boot, so that basically everyone can have as many fds as they want – as long as they raise the soft limit to the hard limit (and thus declare "hey i will never use select()").

**Comment by poettering** [comment]
#29322 should be all that's necessary. PTAL.

**Comment by poettering** [comment]
#29322 has been merged now. Would be great if you could report back if this comprehensively fixes the issue for you.
