### ISSUE TITLE
systemd-resolved: Incorrect CNAME response returned

### ISSUE THREAD

**Issue by gomasy** [systemd/systemd#28584]
### systemd version the issue has been seen with

253.7-1

### Used distribution

Arch Linux x86_64

### Linux kernel version used

6.4.6-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

If ReadEtcHosts is enabled and /etc/hosts is as follows, the CNAME for web01 -> server01 is returned.

#### /etc/hosts
```
192.0.2.1 server01
2001:db8::1234 server01
192.0.2.1 web01
```

### Unexpected behaviour you saw

When querying record A of "web01", the CNAME of "server01" is returned.
"web01" has no IPv6 address and should not be equated with "server01". it should respond with an A record.
This causes some software to behave as if "web01" has an IPv6 address. (Checked with Blackbox exporter)

**Comment by ldv-alt** [comment]
This happens because resolved treats
```
192.0.2.1 server01
192.0.2.1 web01
```
as
```
192.0.2.1 server01 web01
```
