### ISSUE TITLE
Wrong permissions for /dev/vfio/vfio

### ISSUE THREAD

**Issue by mriedel87** [systemd/systemd#28588]
### systemd version the issue has been seen with

systemd v254

### Used distribution

Debian sid

### Linux kernel version used

kernel-6.4-9

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles, systemd-udevd

### Expected behaviour you didn't see

Correct permissions set for "/dev/vfio/vfio" with mode=0666

### Unexpected behaviour you saw

Permissions for "/dev/vfio/vfio" are mode=0600

### Steps to reproduce the problem

Upgrade from 253.5-1 to 254-1 and reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[    1.747028] systemd-tmpfiles[317]: Entry "/dev/vfio/vfio" matches include prefix "/dev".
[    1.751287] systemd-tmpfiles[317]: Running create action for entry c /dev/vfio/vfio
[    1.751307] systemd-tmpfiles[317]: Created char device node "/dev/vfio/vfio" 1:128.
[    1.830822] systemd-udevd[328]: Setting permissions /dev/vfio/vfio, uid=0, gid=0, mode=0666
[    2.167485] (udev-worker)[374]: vfio: Preserve permissions of /dev/vfio/vfio, uid=0, gid=0, mode=0666
[    2.167505] (udev-worker)[374]: vfio: Successfully created symlink '/dev/char/10:196' to '/dev/vfio/vfio'
[    2.878296] systemd-tmpfiles[659]: Running remove action for entry c /dev/vfio/vfio
[    2.883837] systemd-tmpfiles[659]: Running create action for entry c /dev/vfio/vfio
[    2.883855] systemd-tmpfiles[659]: Found existing char device node "/dev/vfio/vfio" 1:128.
[    2.883857] systemd-tmpfiles[659]: Changing "/dev/vfio/vfio" to mode 600.
```

**Comment by mriedel87** [comment]
Propably the bug is related to commit b42482a

**Comment by mrc0mmand** [comment]
Fix is waiting in https://github.com/systemd/systemd/pull/28590.
