### ISSUE TITLE
pid1: creating mount namespace does something inefficient??

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#28603]
### systemd version the issue has been seen with

v254

### Unexpected behaviour you saw

I am not sure it is expected or not, but starting a service with mount namespace produces more than 1000 lines of debugging log. See the attached log. IIRC, previously, relevant logs were ~30 lines or so. At most less than 100.
[hoge.txt](https://github.com/systemd/systemd/files/12216466/hoge.txt)

**Comment by bluca** [comment]
Yeah I guess those 'Not unmounting' messages could be downgraded to tracing level
