### ISSUE TITLE
nspawn doesn't handle bind-mounts for symlinks correctly

### ISSUE THREAD

**Issue by alban** [systemd/systemd#2860]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> git master
### Used distribution

> Fedora
### In case of bug report: Expected behaviour you didn't see

`--bind` should be able to make a directory available in the container even when the target directory is a symlink such as `/var/run`.
### In case of bug report: Unexpected behaviour you saw

When `/var/run` in the image is a relative link, it works. But when it is an absolute link, it does not work.

See this example with an absolute link (Debian) and a relative link (Fedora):

```
$ ls -l ~/distro-trees/debian/var/run
lrwxrwxrwx. 1 root root 4 Oct  6 23:05 /home/alban/distro-trees/debian/var/run -> /run
$ sudo touch /var/run/HOST
$ sudo systemd-nspawn -D ~/distro-trees/debian/ --bind /var/run:/var/run ls -l /var/run/HOST
ls: cannot access /var/run/HOST: No such file or directory
```

```
$ ls -l ~/distro-trees/fedora-22/var/run
lrwxrwxrwx. 1 root root 6 Dec  6 16:47 /home/alban/distro-trees/fedora-22/var/run -> ../run
$ sudo touch /var/run/HOST
$ sudo systemd-nspawn -D ~/distro-trees/fedora-22/ --bind /var/run:/var/run ls -l /var/run/HOST
-rw-r--r--. 1 root root 0 Mar 17 18:21 /var/run/HOST
```

It happens because the bind mount is done before the chroot/root-MS_MOVE. 

Related workaround in rkt: https://github.com/coreos/rkt/pull/2290

/cc @yifan-gu @philips @jonboulle @iaguis

**Comment by evverx** [comment]
Indeed.
I've checked [`--tmpfs`](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--tmpfs=) and [`--overlay`](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--overlay=).
`nspawn` doesn't handle tmpfs-mounts and overlayfs-mounts for symlinks correctly too.

```
# ls -l /var/tmp/systemd-test.KO5xK4/nspawn-root/hola/bro
lrwxrwxrwx 1 root root 4 Mar 25 07:09 /var/tmp/systemd-test.KO5xK4/nspawn-root/hola/bro -> /bro

# systemd-nspawn --directory /var/tmp/systemd-test.KO5xK4/nspawn-root/ --tmpfs /hola/bro
...
Creating mount point for tmpfs /var/tmp/systemd-test.KO5xK4/nspawn-root/hola/bro failed: No such file or directory
```

```
# mkdir A B
# >A/a >B/b
# systemd-nspawn --directory /var/tmp/systemd-test.KO5xK4/nspawn-root/ --overlay $(pwd)/A:$(pwd)/B:/hola/bro
...
overlay mount to /var/tmp/systemd-test.KO5xK4/nspawn-root/hola/bro failed: No such file or directory
```

**Comment by alban** [comment]
Code in rkt doing that:
[EvaluateSymlinksInsideApp](https://github.com/coreos/rkt/blob/master/stage1/init/common/pod.go#L757)

**Comment by poettering** [comment]
I figure as soon as #4018 is applied, we can reuse the symlink chasing code included in it for nspawn too and fix this properly.

**Comment by poettering** [comment]
#4694 should fix this issue. please have a look.
