### ISSUE TITLE
Need a way to query DHCP DUID and IAID values

### ISSUE THREAD

**Issue by vinaykul** [systemd/systemd#2861]
### Submission type
- [ ] Bug report
- [ X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with 229

Hi @teg ,

Is there a recommended way to query the DHCP DUID / IAID information used to acquire a DHCP IP address?

networkd displays DHCP IPv4 lease information in a file /run/systemd/netif/leases/<ifindex>
This could potentially be used to query the DHCP DUID and IAID values from CLIENTID field. However, no such leases file is present for IPv6. Perhaps there should be a /run/systemd/netif/leases6/<ifndex> set of files for DHCP IPv6 interfaces. Is this left out by intent?

Would you recommend using these files to query the DHCP DUID and IAID information from systemd? Alternately, we could extend the functionality of networkctl.  

Our use case goes back to the VM upgrade scenario ...  we would need to query this information for upgrading from a Photon VM to a newer version.

Thanks,
Vinay

**Comment by ssahani** [comment]
I think we can close this as below got merged.

https://github.com/systemd/systemd/pull/16124
https://github.com/systemd/systemd/pull/16104
https://github.com/systemd/systemd/pull/16085
