### ISSUE TITLE
Ability to forward date real-time stamps for RTCless systems

### ISSUE THREAD

**Issue by wak-google** [systemd/systemd#28618]
### Component

systemd-journald

### Is your feature request related to a problem? Please describe

We have systems without an RTC, that start at some point in the unknown past and keep a bunch of journal logs during bootup. At some point they sync with NTP, and all new logs are written with the correct realtime. We'd like to ship all of the logs off to a logserver, but we need to correct the realtimes in the logs prior to doing so. The monotimes are accurate enough for our use, so backdating based on logged mono + current real - current mono should work.

### Describe the solution you'd like

It would be nice if there was some kind of utility or bus command to update an existing catalog or all journals that contain boot=0 to have their real-time stamps rewritten based on the monotime + current system time parameters.

### Describe alternatives you've considered

Even with rough time keeping such that bootup has some idea of what time it is, we can't globally correlate logs without more accurate timestamps.

An RTC would have been nice :laughing:

**Comment by bluca** [comment]
journals are write-only, so you'll have to correct on the receiving end, it's probably less error prone too. Or you can build a poor man's RTC using the kernel command line option `systemd.clock-usec=` - been there...

**Comment by wak-google** [comment]
We can't correct it on the remote end, because it goes through an rsyslog pipeline and we don't have the ability to send both types of timestamps. Maybe the rsyslog pipeline could do the correction though with some patching.

**Comment by bluca** [comment]
The journal entry records the monotonic timestamp as one of the fields, can't you export that and then use it to correct entries before time is synced? The first entry with synced clock will also have a monotonic timestmap, so you can use that to do the calculation

**Comment by wak-google** [comment]
Yeah, we can do that. The problem is the journals on the systems will still have broken real time stamps, which means we have to train everyone not to use them and do their own calculations by hand when viewing the logs directly. If the consensus here is that systemd will not maintain this type of tooling, we will just have to write our own.

**Comment by bluca** [comment]
As mentioned journals are append-only. But if what you want is a command line option to journalctl that corrects things when printing, maybe that could be done. There's a range of --output= types, one more would do the trick. Happy to review a PR that does something like that.

**Comment by wak-google** [comment]
They are append only, but we would just rewrite the entire old catalog into a new one. Not overwrite in place.

**Comment by bluca** [comment]
I'm not sure, that could be extremely expensive, and it could only be done for archived journals. Converting on output seems cheaper and safer to me, messages are processed and formatted anyway at that point, so the extra cost shouldn't be too large, just the one-time to find the anchor point.

**Comment by bluca** [comment]
and even finding the anchor point could be cheap - it would be enough to add a new MESSAGE_ID that time syncing programs would use to log when the time has been synced. Then it's just one indexed lookup.

**Comment by wak-google** [comment]
It won't be super expensive for us, as it would only be the boottime journal up until the point of timesync that can only be stored in ram (We have 1GB total). The journal max is something like 64M.

**Comment by bluca** [comment]
There's no such guarantee for the general use case

**Comment by wak-google** [comment]
Yeah, but that's why it would just be a tool that the user chooses to use with the obvious caveat WRT performance.

**Comment by wak-google** [comment]
I mean, I think I would be happy with a journal configuration to ignore + recalculate the realtime stamps based on monotime + current realtime any time the journal is read.

**Comment by bluca** [comment]
It would have to be on journalctl's side - but yeah I think that can work fine. Would you be able to send a PR to implement it?

BTW, I was in the exact same situation - my long term solution was to beg and nag, beg and nag, beg and nag until management caved in and approved budget for an RTC for the next hardware revision of the board :-)

**Comment by poettering** [comment]
This is already implemented since 262299dccbb09f36c8c830dabd6a104469d9852b.

i.e. we nowadays correct output time of log entries in journalctl automatically based on the most recent information we have about the CLOCK_MONOTONIC/CLOCK_REALTIME delta for each boot.

This is done at display time automatically. (i.e. we don't rewrite data on disk, but just fix this up on display)

Closing hence.

**Comment by bluca** [comment]
eheh I had completely forgot about that change, thanks
