### ISSUE TITLE
There will be `SecureBoot` issue when build the main branch code with mkosi

### ISSUE THREAD

**Issue by Zheaoli** [systemd/systemd#28631]
### systemd version the issue has been seen with

main

### Used distribution

Arch

### Linux kernel version used

Kernel-6.4.7

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Unexpected behaviour you saw

When I try to build the systemd by following [Hacking on systemd](https://github.com/systemd/systemd/blob/main/docs/HACKING.md), I found some issue when I run the command in the Documentation

```bash
meson setup build -Danalyze=true -Drepart=true -Defi=true -Dbootloader=true -Dukify=true
ninja -C build
mkosi genkey
mkosi qemu
```

The error has been raised with the following message:

```text
‣ Removing output files…
‣ Building final image
Create subvolume '/home/manjusaka/Documents/projects/systemd/.mkosi.tmp85kc9nh3/root'
‣  Mounting image…
‣   Copying in base trees…
Create a snapshot of '/home/manjusaka/Documents/projects/systemd/mkosi.presets/20-final/../../mkosi.output/base' in '/home/manjusaka/Documents/projects/systemd/.mkosi.tmp85kc9nh3/root'
‣   Copying cached trees
‣   Setting up autologin…
‣   Copying in extra file trees…
‣   Signing systemd-boot binaries…
‣ One of sbsign or pesign is required to use SecureBoot=
```
Now I try to modify the `mkosi.presets/20-final/mkosi.conf` to disable the SecureBoot option, this issue has been fixed.

Should we update the documentation to add some tips?

**Comment by DaanDeMeyer** [comment]
You have to install the sbsigntools package

**Comment by poettering** [comment]
Let's close this, as this is not really a bug or anything, it's just a polite request to install one of those to packages.
