### ISSUE TITLE
Automatic Boot Assessment not working due to "LoaderBootCountPath" missing 

### ISSUE THREAD

**Issue by dmrauh** [systemd/systemd#28637]
### systemd version the issue has been seen with

254

### Used distribution

Custom-built using Buildroot

### Linux kernel version used

6.1.22

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

The EFI variable `LoaderBootCountPath` should be created and
and the UKI shall be renamed.

### Unexpected behaviour you saw

Although according to systemd-boot's status, boot counting seems to be ok:

```
 config entry: 1/2
             id: 0ec751c47f004391891eea14f75d41be-6.1.22+3.efi
          title: Buildroot 2023.02
       sort key: buildroot
        version: 2023.02-7-g15557ec88b-dirty
         device: PciRoot(0x0)/Pci(0x1A,0x0)/eMMC(0x0)/Ctrl(0x0)/HD(2,GPT,3D280C0D-2728-0F48-8097-7FB990521075,0x40800,0x80000)
         loader: \EFI\Linux\0ec751c47f004391891eea14f75d41be-6.1.22+3.efi
        options: root=UUID=e137e91b-3bdb-4484-ae45-fdd1d2a774c8
  internal call: no
 counting boots: yes
          tries: 3 left, 0 done
   current path: \EFI\Linux\0ec751c47f004391891eea14f75d41be-6.1.22+3.efi
      next path: \EFI\Linux\0ec751c47f004391891eea14f75d41be-6.1.22+2-1.efi
 
 config entry: 2/2
             id: auto-reboot-to-firmware-setup
          title: Reboot Into Firmware Interface
  internal call: yes
 counting boots: no
```

after booting into the OS,

executing `ls /sys/firmware/efi/efivars/Loader*`

returns all expected variables execept "LoaderBootCountPath", necessary for
Automatic Boot Assessment to successfully complete. Also `/usr/lib/systemd/systemd-bless-boot` only prints _clean_ and the UKI's file name has _not_ been changed.

### Steps to reproduce the problem

Install UKI via `kernel-install` and `/etc/kernel/tries` containing `3` and reboot.

**Comment by medhefgo** [comment]
It certainly works for me. Does systemd-boot *actually* rename the entry on boot, aka perform boot counting? What's the output of `journalctl -u systemd-bless-boot.service`?

**Comment by dmrauh** [comment]
Can confirm that boot counting is working now. Thanks!
