### ISSUE TITLE
Rule triggered for (not quite) devices during udev hotplug but not coldplug

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#28638]
### systemd version the issue has been seen with

systemd 253.7+suse.31.g2dac0aff9c

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.4.6-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

I have an udev rule which matches a specific namespace in the QEMU fwcfg device to make systemd aware of its existence:

```
# QEMU fw_cfg blob with key opt/org.opensuse.combustion
ACTION=="add", SUBSYSTEM=="opt", ENV{DEVPATH}=="/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion", ENV{SYSTEMD_ALIAS}+="/dev/combustion/config", TAG+="systemd"
```

The matching criteria were derived from what `udevadm monitor` outputs when loading the `qemu_fw_cfg` module after unloading it before:

```
KERNEL[4644.047886] add      /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/QEMU0002:00/wakeup/wakeup20 (wakeup)
KERNEL[4644.056020] add      /firmware/qemu_fw_cfg/by_name/etc (by_name)
KERNEL[4644.063497] add      /firmware/qemu_fw_cfg/by_name/etc/acpi (etc)
KERNEL[4644.079852] add      /firmware/qemu_fw_cfg/by_name/etc/smbios (etc)
UDEV  [4644.094056] add      /firmware/qemu_fw_cfg/by_name/etc (by_name)
KERNEL[4644.096755] add      /firmware/qemu_fw_cfg/by_name/etc/tpm (etc)
UDEV  [4644.099328] add      /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/QEMU0002:00/wakeup/wakeup20 (wakeup)
KERNEL[4644.102915] add      /firmware/qemu_fw_cfg/by_name/genroms (by_name)
UDEV  [4644.105363] add      /firmware/qemu_fw_cfg/by_name/etc/acpi (etc)
KERNEL[4644.107615] add      /firmware/qemu_fw_cfg/by_name/opt (by_name)
UDEV  [4644.109843] add      /firmware/qemu_fw_cfg/by_name/etc/smbios (etc)
UDEV  [4644.114525] add      /firmware/qemu_fw_cfg/by_name/genroms (by_name)
KERNEL[4644.116977] add      /firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion (opt)
UDEV  [4644.120063] add      /firmware/qemu_fw_cfg/by_name/opt (by_name)
KERNEL[4644.122527] bind     /devices/pci0000:00/QEMU0002:00 (platform)
KERNEL[4644.127644] add      /bus/platform/drivers/fw_cfg (drivers)
UDEV  [4644.129997] add      /firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion (opt)
KERNEL[4644.133077] add      /module/qemu_fw_cfg (module)
UDEV  [4644.135161] bind     /devices/pci0000:00/QEMU0002:00 (platform)
UDEV  [4644.137588] add      /bus/platform/drivers/fw_cfg (drivers)
UDEV  [4644.139384] add      /module/qemu_fw_cfg (module)
UDEV  [4644.140722] add      /firmware/qemu_fw_cfg/by_name/etc/tpm (etc)
```

This already looks a bit weird with the subsystem being `by_name`, `etc` and `opt`, but putting it into a rule does match correctly: When the module is loaded, the rule is executed and `sys-firmware-qemu_fw_cfg-by_name-opt-org.opensuse.combustion.device` appears as active device unit.

### Unexpected behaviour you saw

On boot during the initrd phase, the device unit is not up. The module is already loaded before udev starts, so this should be triggered through udev coldplug, but it's not the case.

`udevadm trigger -c add /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion`  does not have any effect either.

`udevadm test /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion` prints:

```
[...]
Reading rules file: /usr/lib/udev/rules.d/99-xx-ignition-systemd-cryptsetup.rules
org.opensuse.combustion: Failed to clone sd_device object: No such file or directory
DEVPATH=/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion
ACTION=add
Unload kernel module index.
Unloaded link configuration context.
```

My suspicion is that those events aren't really for any "devices", so coldplug does not trigger them. That does however raise the question why they are generated and trigger the rules during hotplug.

**Comment by Vogtinator** [comment]
> That sounds driver issue.

Could be. The "device" for the event is actually just a kset containing some symlinks to kobjects. There are no events for the actual kobjects they point to.

> Could you show the results of the following?

I booted with `rd.udev.log_level=debug` as well.

> ```shell
> SYSTEMD_LOG_LEVEL=debug udevadm trigger -c add /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion
> ```

```
SELinux enabled state cached to: disabled
```

No output otherwise. udevd didn't log anything either. (When triggering other devices there is, so not a logging issue).

> ```
> SYSTEMD_LOG_LEVEL=debug udevadm info /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion
> ```

```
SELinux enabled state cached to: disabled
Successfully forked off '(pager)' as PID 1099.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
sd_pid_get_owner_uid() failed, enabling pager secure mode: No data available
Pager executable is "less", options "FRSXMK", quit_on_interrupt: yes
P: /firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion
M: org.opensuse.combustion
```

**Comment by Vogtinator** [comment]
> Could be. The "device" for the event is actually just a kset containing some symlinks to kobjects. There are no events for the actual kobjects they point to.

Yep, definitely a driver bug. It's missing the call to `kobject_uevent(&entry, KOBJ_ADD)` for those.

I have an explanation for hotplug vs. coldplug meanwhile as well: The device monitor reacts to all kernel events, even for those in `/sys/firmware`, while the coldplug only iterates `/sys/devices` and `/sys/bus`. It's basically what I suspected and I'm not sure whether this is proper behavior. IMO it should try to keep this consistent, because currently this results in race conditions.

**Comment by yuwata** [comment]
Hmm. if the syspath has uevent, then we can trigger uevent and coldplug should work.
But if not, there is no way we can take...

Could you show `ls /sys/firmware/qemu_fw_cfg/by_name/opt/org.opensuse.combustion` ?

**Comment by Vogtinator** [comment]
> Hmm. if the syspath has uevent file, then we can and should trigger uevent to make coldplug work.

There is no uevent file, just the directory for the key inside the namespace:

```
script
```

**Comment by poettering** [comment]
(btw, friends don't let friends use fw_cfg anymore for propagating data into a VM, it's qemu specific. A better approach is using SMBIOS, which is generic. systemd creds use fw_cfg too, but only for compat, we recommend people to use SMBIOS type 11 vendor objects instead.)

**Comment by Vogtinator** [comment]
> (btw, friends don't let friends use fw_cfg anymore for propagating data into a VM, it's qemu specific. A better approach is using SMBIOS, which is generic. systemd creds use fw_cfg too, but only for compat, we recommend people to use SMBIOS type 11 vendor objects instead.)

Is there a good libvirt interface for that which also allows to specify a file as source? Is it easily accessible from userspace and maybe properly usable through udev? (Though if that's completely kernel built-in, a rule wouldn't be needed anymore)

FTR, the needs-reporter-feedback label can be removed.

**Comment by poettering** [comment]
https://libvirt.org/formatdomain.html#smbios-system-information i.e. the part about `<oemStrings>`

Accessible from userspace easily via `/sys/firmware/dmi/entries/11-*/raw`.

not a device, so no udev.

it's a million times faster btw, since just some memory mapped region, and not io port reads.

**Comment by yuwata** [comment]
> > Hmm. if the syspath has uevent file, then we can and should trigger uevent to make coldplug work.
> 
> There is no uevent file, just the directory for the key inside the namespace:
> 
> ```
> script
> ```

Thanks. Then, sorry, udevd does not support to coldplug such device.
As we have no way to rebuild uevent data that we receive on hotplug, and that's necessary for coldplugging.

**Comment by Vogtinator** [comment]
That's somewhat expected, but is there something that can be done against this asymmetry? Not emitting any events for such "not quite devices" probably breaks stuff...

**Comment by yuwata** [comment]
Not sure if it works, but how about to introduce a generator that enumerates such 'devices' and creates relevant .device units??

**Comment by Vogtinator** [comment]
Can a generator create .device units which are `up` that way? Technically it would be possible to create them as an alias to `/dev/null` or something but that seems wrong.

Currently as a workaround I changed the udev rule to trigger on the `qemu_fw_cfg` module itself, using a `TEST==` condition to check that the fw_cfg key exists. This appears to work well enough, though I'm not entirely sure whether coldplug for modules is guaranteed and it probably breaks if it's built-in and not a loadable module. FWICT at least the sysfs registration is synchronous, so performing the check after the module got loaded isn't racy.

**Comment by poettering** [comment]
note that udev doesn't generate the events, but the kernel does. udev just propagates them.

if you think that fwcfg or smbios should generate uevents bring this up to the kernel people. But I doubt they'll care much. Both of these interfaces are "static", i.e. they are just there, and don't change, hence generating events for them seems quite unnecessary.

If all you want to do is run some tool when some data blob is passed into a VM, consider passing the data blob in as systemd credentials (see https://systemd.io/CREDENTIALS for details), which will give you both smbios + fwcfg at the same time, plus more. And there's ConditionCredential= to condition a unit on the existance of a credential.
