### ISSUE TITLE
Failed to move /run/initramfs to /

### ISSUE THREAD

**Issue by Freyon77** [systemd/systemd#28645]
### systemd version the issue has been seen with

254-1-arch

### Used distribution

Archlinux

### Linux kernel version used

6.4.7

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

I want to see my shutdown clean and fast

### Unexpected behaviour you saw

While shutting down / reboot archlinux receiving errors but system reboot correctly.

systemd-shutdown: Failed to move /run/initramfs to /: invalid argument

systemd-shutdown: Failed to switch root to "run/initramfs" invalid argument

### Steps to reproduce the problem

Shutdown system / reboot system

**Comment by Freyon77** [comment]
Propably releated

Generated archiso with latest systemd few minutes ago and on shutdown getting same errors as abowe plus one error extra.

system-d shutdown: Unable to finalize remaining loop device, ignoring

**Comment by yuwata** [comment]
Could anyone test #28648?

**Comment by akiirui** [comment]
> Could anyone test #28648?

I've tried building systemd with your PR. But it looks like it doesn't solve the issue.

**Comment by WebReflection** [comment]
same issue here, looking forward to see the patch landed in ArchLinux, thanks for the fix :wave:

**Comment by Oldfart28** [comment]
Same issue here.

**Comment by Puxap-3opre** [comment]
The same. Also it seems shutdown takes a couple of seconds longer.

**Comment by vecinohk** [comment]
Hi, I am also adding 6.4.8-arch1-1 + 254-1 and every time I reboot I get this error. If you want to test the fix - I'm happy to test it on myself. Thanks

**Comment by Freyon77** [comment]
Exactly, it is not possible. To test it properly you would have to check after a fresh system installation without any system shutdown.

**Comment by DrPicklez** [comment]
I also have this issue on:
6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023

systemd-shutdown[1]: Failed to move /run/initramfs to /: Invalid argument
systemd-shutdown[1]: Failed to switch root to "/run/initramfs": Invalid argument

This is my first Arch install have I done something wrong?

**Comment by Freyon77** [comment]
> I also have this issue on:
> 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023
> 
> systemd-shutdown[1]: Failed to move /run/initramfs to /: Invalid argument
> systemd-shutdown[1]: Failed to switch root to "/run/initramfs": Invalid argument
> 
> This is my first Arch install have I done something wrong? No, you will get rid of it in next update.

**Comment by vecinohk** [comment]
Guys this bug has already been fixed in the upstream and now we are waiting for a release. No need to report it anymore just wait for the patch to be released.

**Comment by WebReflection** [comment]
> No need to report it anymore just wait for the patch to be released.

all Arch users are waiting indeed ... thinking *Y U SO LONG* in the process :sweat_smile:

**Comment by vecinohk** [comment]
It's here ... after today's installation of systemd **254.1-1** the error message is gone. 👍 

**systemd 254.1-1**
https://archlinux.org/packages/core/x86_64/systemd/
