### ISSUE TITLE
permissions issues with openzfs

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#28653]
### systemd version the issue has been seen with

254

### Used distribution

Endeavouros

### Linux kernel version used

6.1.39, 6.1.42, 6.4.7

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Excecuting `zpool status` as a normal user generates correct output like 
```
# zpool status zstore
  pool: zstore
 state: ONLINE
  scan: scrub repaired 0B in 06:50:11 with 0 errors on Sat Jul  1 14:27:21 2023
config:

	NAME                       STATE     READ WRITE CKSUM
	zstore                     ONLINE       0     0     0
	  mirror-0                 ONLINE       0     0     0
	    WD40EFRX-WCCaaaa       ONLINE       0     0     0
	    WD40EFRX-WCCbbbb       ONLINE       0     0     0
	  mirror-1                 ONLINE       0     0     0
	    WD40EFRX-WCCcccc       ONLINE       0     0     0
	    WD40EFRX-WCCdddd       ONLINE       0     0     0

errors: No known data errors

```

### Unexpected behaviour you saw

Excecuting `zpool status` as a regular users gives an error message: 
`Permission denied the ZFS utilities must be run as root`

### Steps to reproduce the problem

Upgrading from 253.7-1 -> 254-1 introduces the issue.
Downgrading from 254-1 -> 253.7-1 fixes the issue

See also: https://github.com/openzfs/zfs/issues/15146

**Comment by robn** [comment]
Almost certainly a repeat of #28588. OpenZFS wants `/dev/zfs` to be 0666, and ships this udev rule to do so:

```
KERNEL=="zfs", MODE="0666", OPTIONS+="static_node=zfs"
```

**Comment by mabod** [comment]
This rule is not fixing it.
I have 

```
[matthias@rakete] /etc/udev/rules.d
# cat 90-zfs.rules         
KERNEL=="zfs", MODE="0666", OPTIONS+="static_node=zfs"
```

But permissions are wrong
```
# ls -l /dev/zfs
crw------- 1 root root 10, 249 2023-08-03@09:58 /dev/zfs
```

And as normal user I get:
```
# zpool status
Permission denied the ZFS utilities must be run as root.
```


Doing a 
`sudo chmod 0666 /dev/zfs`
fixes the issue

**Comment by ryanmjacobs** [comment]
`sudo chmod 0666 /dev/zfs` fixed it for me as well! Frustrating to run into this issue... `zfs list` is in a lot of my userspace scripts.

**Comment by mabod** [comment]
Some more info regarding this udev rule.
It is somehow not applied after reboot. 

After reboot permissions are:
```
# ls -l /dev/zfs
crw------- 1 root root 10, 249 2023-08-03@10:07 /dev/zfs
```

But when I do a 
`udevadm test /dev/zfs`

The rule gets applied:
```
# udevadm test /dev/zfs
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.
...
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
zfs: /etc/udev/rules.d/90-zfs.rules:1 MODE 0666
zfs: Setting permissions /dev/zfs, uid=0, gid=0, mode=0666
zfs: Successfully created symlink '/dev/char/10:249' to '/dev/zfs'
zfs: sd-device: Created empty file '/run/udev/data/c10:249' for '/devices/virtual/misc/zfs'
DEVPATH=/devices/virtual/misc/zfs
DEVNAME=/dev/zfs
MAJOR=10
MINOR=249
SUBSYSTEM=misc
ACTION=add
USEC_INITIALIZED=179638523
Unload kernel module index.
Unloaded link configuration context.
```

And the permissions are:
```
# ls -l /dev/zfs          
crw-rw-rw- 1 root root 10, 249 2023-08-03@10:10 /dev/zfs
```

**Comment by mrc0mmand** [comment]
In case of https://github.com/systemd/systemd/issues/28588 it was `kmod-static-nodes.service`, and its generated tmpfiles.d file, that was overwriting the permissions:

```
$ systemctl status kmod-static-nodes.service
● kmod-static-nodes.service - Create List of Static Device Nodes
     Loaded: loaded (/usr/lib/systemd/system/kmod-static-nodes.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (exited) since Sun 2023-07-23 11:30:42 CEST; 1 week 3 days ago
    Process: 1065 ExecStart=/usr/bin/kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/static-nodes.conf (code=exited, status=0/SUCCESS)
   Main PID: 1065 (code=exited, status=0/SUCCESS)
        CPU: 1ms

$ grep vfio /run/tmpfiles.d/static-nodes.conf
d /dev/vfio 0755 - - -
c! /dev/vfio/vfio 0600 - - - 10:196
```

If it's the case with `/dev/zfs` as well you'll need to add a tmpfiles.d file/dropin in similar fashion to https://github.com/systemd/systemd/blob/main/tmpfiles.d/static-nodes-permissions.conf.in.

**Comment by mabod** [comment]
That was it. I edited /usr/lib/tmpfiles.d/static-nodes-permissions.conf:

```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# This file adds permissions on top of static-nodes.conf generated by
# kmod-static-nodes.service. Rules specified here should match the
# permissions specified for udev in 50-udev-default.rules.

z /dev/zfs          0666 - -     -
#
z /dev/snd/seq      0660 - audio -
z /dev/snd/timer    0660 - audio -
z /dev/loop-control 0660 - disk  -
z /dev/net/tun      0666 - -     -
z /dev/fuse         0666 - -     -
z /dev/kvm          0666 - kvm -
z /dev/vhost-net    0666 - kvm -
z /dev/vhost-vsock  0666 - kvm -
```
This solves the issue even without an extra udev rule. 

Can this line be added to this file ot of the box?

`z /dev/zfs          0666 - -     -`

**Comment by yuwata** [comment]
> Can this line be added to this file out of the box?

Unfortunately, but I do not think so.
zfs provides their own udev rules file. So, zfs should also provide tmpfiles config. Please.

**Comment by mabod** [comment]
> So, zfs should also provide tmpfiles config.

What is the proper way to do this? I just edited `/usr/lib/tmpfiles.d/static-nodes-permissions.conf`
Is there are better way of doing it?

**Comment by yuwata** [comment]
It is enough to add a single line file, e.g. `/usr/lib/tmpfiles.d/zfs-node-permission.conf`, that contains the rule for zfs.

**Comment by larsch** [comment]
I have similar issue with ydotool.

```
# cat /usr/lib/udev/rules.d/80-uinput.rules
## ydotoold fix
##     https://github.com/ReimuNotMoe/ydotool/issues/25#issuecomment-535842993
SUBSYSTEM=="misc", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
```

But tmpfiles.d has different mode than specified in udev rule.

```
# grep uinput /run/tmpfiles.d/static-nodes.conf
c! /dev/uinput 0600 - - - 10:223
```

In fact, many additional static_node device from udev have incorrect permissions?

```
c! /dev/vhost-net 0600 - - - 10:238
c! /dev/vhost-vsock 0600 - - - 10:241
```

**Comment by yuwata** [comment]
Okay, so the commit https://github.com/systemd/systemd/commit/b42482af904ae0b94a6e4501ec595448f0ba1c06 breaks so many setups, let's fix it. Please wait for a while.

**Comment by yuwata** [comment]
> Okay, so the commit [b42482a](https://github.com/systemd/systemd/commit/b42482af904ae0b94a6e4501ec595448f0ba1c06) breaks so many setups, let's fix it. Please wait for a while.

(Then, zfs specific change will not necessary.)

**Comment by yuwata** [comment]
Fix is waiting in #28681.

**Comment by yuwata** [comment]
Hmm. By re-considering the post-merge discussion in #28681, the offending commit breaks many existing setup, and #28681 does not fix the issue when people only add/change udev rules for static nodes...

**Comment by yuwata** [comment]
So, there are several options:
- revert the offending commit b42482af904ae0b94a6e4501ec595448f0ba1c06,
- generate tmpfiles entries from udev rules, like we generate from `kmod static-nodes`,
- request people to also provide tmpfiles settings that consistent with their udev rules.

**Comment by yuwata** [comment]
I hope #28732 should fix the issue, finally.
