### ISSUE TITLE
race: systemctl --wait start UNIT followed by journalctl -u UNIT: output sometimes missing

### ISSUE THREAD

**Issue by edsantiago** [systemd/systemd#28650]
### systemd version the issue has been seen with

systemd-253.7-1.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

6.4.6-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

[ context: SERVICE emits one line of output and exits immediately ]
```
# systemctl --wait start SERVICE
# journalctl -u SERVICE
...date..host... one line of output!
```

### Unexpected behaviour you saw

Sometimes fail to see output. 

It is possible that this is the same as #2913 or #3767 or perhaps another issue I couldn't find. Or perhaps there's a `--flush-output` option to `systemd start`. If so I apologize.

### Steps to reproduce the problem

[journald-race.sh](https://github.com/systemd/systemd/files/12243551/journald-race.sh.txt)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
...........................................................................
**FAILED foo-ZHFwFXrHH5PcmrEuilyD.service in 170 seconds

-- No entries --
retrying after 2 seconds:
Aug 02 14:28:15 host bash[144555]: GOT HERE
Aug 02 14:28:15 host systemd[1]: Started foo-ZHFwFXrHH5PcmrEuilyD.service - foo.
Aug 02 14:28:15 host systemd[1]: foo-ZHFwFXrHH5PcmrEuilyD.service: Deactivated successfully.
```

**Comment by yuwata** [comment]
That's expected. Please specify `Type=oneshot` for such testcase. Please see [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) for more details.

**Comment by edsantiago** [comment]
@yuwata thank you for your quick response. I've modified the reproducer script as follows and I still see the same symptom:
```diff
@@ -15,6 +15,7 @@
 
 [Service]
 ExecStart=/bin/bash -c "echo GOT HERE"
+Type=oneshot
 EOF
 
     systemctl daemon-reload
```

**Comment by yuwata** [comment]
Then, such 'race' is still expected. Simply, journald has not processed the output.
