### ISSUE TITLE
repart: set salt & uuid to create reproducible verity partitions

### ISSUE THREAD

**Issue by veehaitch** [systemd/systemd#28656]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

Partition definitions which set `Verity=` are not created in a reproducible fashion because the call to _libcryptsetup_ does neither set a [`salt`][cryptsetup-salt] nor a superblock [`uuid`][cryptsetup-uuid]:

https://github.com/systemd/systemd/blob/e3b7fe92e90fd107ea9be30112e00e227ca18501/src/partition/repart.c#L3730-L3740

As a result, even in a hermetic environment, subsequent calls will always result in a different roothash (due to the missing salt) and image (due to the missing uuid in the verity superblock).

[cryptsetup-salt]: https://gitlab.com/cryptsetup/cryptsetup/-/blob/ef46ded7b4e7a95546a2d6d68bfec8abd18f560a/lib/libcryptsetup.h#L535
[cryptsetup-uuid]: https://gitlab.com/cryptsetup/cryptsetup/-/blob/ef46ded7b4e7a95546a2d6d68bfec8abd18f560a/lib/setup.c#L2948

### Describe the solution you'd like

_systemd-repart_ already accepts a [`--seed`][repart-seed] command line argument to generate reproducible partition UUIDs. If `--seed` is omitted, it defaults to the machine ID. The code uses HMAC-SHA256 to derive a UUID from the seed and the partition type:

https://github.com/systemd/systemd/blob/e3b7fe92e90fd107ea9be30112e00e227ca18501/src/partition/repart.c#L4569-L4576

In a similar fashion, `partition_format_verity_hash` could use the seed as an HMAC key to derive a stable salt.

[repart-seed]: https://www.freedesktop.org/software/systemd/man/systemd-repart.html#--seed=

### Describe alternatives you've considered

A possible alternative is adding a new setting to allow configuring the salt explicitly. In that case, it probably makes sense to introduce a new configuration section, e.g., `[Verity]`, to make more parameters configurable (`hash_name`, `salt_size`, ...). As far as I understand, this is something @DaanDeMeyer [also suggests](https://github.com/systemd/systemd/pull/28480#issuecomment-1644998421).

Arguably, this approach allows passing more secure salt values (i.e., more bytes of random data) to dm-verity. Yet, it might still make sense to have a sensible default for a stable uuid and salt value.

**Comment by DaanDeMeyer** [comment]
Making it reproducible by default as well as adding the Verity settings both sound like great ideas, will happily review PRs for that.

**Comment by veehaitch** [comment]
Apart from passing a salt, systemd-repart also needs to pass a superblock UUID to create reproducible verity volumes. I updated the issue description accordingly.

I gave it a shot to derive both arguments from the seed value in #28695, @DaanDeMeyer.
