### ISSUE TITLE
reboot and shutdown -r will reboot but shutdown -r now halts

### ISSUE THREAD

**Issue by carbontwelve** [systemd/systemd#28666]
### systemd version the issue has been seen with

252.12-1~deb12u1

### Used distribution

Debian12

### Linux kernel version used

6.1.0-10-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When running `shutdown -r now` on a brand new install of Debian12 I expect the behaviour to be the same as running `reboot`, that is the system shutsdown and reboots.

### Unexpected behaviour you saw

When running `shutdown -r now` the system shuts down but remains powered on and does not reboot; requiring a power cycle to resume operation.

This is not experienced when excluding the time, `shutdown -r` behaves as exepcted.

### Steps to reproduce the problem

- Install fresh copy of Debian12
- Run `shutdown -r now`
- System shutsdown but remains powered on

I have asked a few other people and with the same kernel and systemd version they aren't experiencing the same issue.

**Comment by carbontwelve** [comment]
I have done some additional testing this morning; on the same hardware I did a complete fresh install of Debian 11 (bullseye) Linux 5.10.0-23-amd64 running systemd 247.3-7+deb11u2 and both `reboot` and `shutdown -r now` work as expected.

I then ran `apt update && apt upgrade` which brought systemd upto version 247.3-7+deb11u4 both commands continued to work as expected, I tested ten iterations of each.

Then on the same hardware I did a complete fresh install of Debian 12 (bookworm) Linux 6.1.0-9-amd64; first reboot with `reboot` took about 159 seconds, a subsequent reboot with `shutdown -r now` took 749 seconds!

Looking at the system log for the shutdown from `shutdown -r now` being invoked to the last log entry is 90 seconds.
```
Aug 04 12:33:45 moose systemd-logind[701]: The system will reboot now!
...
Aug 04 12:35:15 moose systemd-journald[379]: Journal stopped
```

Then from the first log entry on boot to the system able to recieve ssh connections is 21 seconds.

```
Aug 04 12:46:15 moose kernel: Linux version 6.1.0-9-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)
...
Aug 04 12:46:21 moose sshd[915]: Server listening on 0.0.0.0 port 22.
Aug 04 12:46:21 moose sshd[915]: Server listening on :: port 22.
Aug 04 12:46:21 moose systemd[1]: Started ssh.service - OpenBSD Secure Shell server.
Aug 04 12:46:21 moose systemd[1]: Reached target multi-user.target - Multi-User System.
Aug 04 12:46:21 moose systemd[1]: Reached target graphical.target - Graphical Interface.
Aug 04 12:46:21 moose systemd[1]: Starting systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP...
Aug 04 12:46:21 moose systemd[1]: systemd-update-utmp-runlevel.service: Deactivated successfully.
Aug 04 12:46:21 moose systemd[1]: Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.
Aug 04 12:46:21 moose systemd[1]: Startup finished in 3.457s (kernel) + 5.791s (userspace) = 9.249s.
Aug 04 12:46:22 moose systemd-timesyncd[593]: Contacted time server [2a01:4f8:0:a101::2:3]:123 (ntp.hetzner.com).
Aug 04 12:46:22 moose systemd-timesyncd[593]: Initial clock synchronization to Fri 2023-08-04 12:46:22.631401 CEST.
Aug 04 12:46:36 moose sshd[918]: Accepted publickey for root from 81.132.76.96 port 64068 ssh2: RSA SHA256:ZyZO0+7rY2s1PCZDCi1KKdX21TF0GF0/0OwtAt+gRuM
Aug 04 12:46:36 moose sshd[918]: pam_unix(sshd:session): session opened for user root(uid=0) by (uid=0)
Aug 04 12:46:36 moose systemd[1]: Created slice user-0.slice - User Slice of UID 0.
Aug 04 12:46:36 moose systemd[1]: Starting user-runtime-dir@0.service - User Runtime Directory /run/user/0...
Aug 04 12:46:36 moose systemd-logind[710]: New session 1 of user root.
Aug 04 12:46:36 moose systemd[1]: Finished user-runtime-dir@0.service - User Runtime Directory /run/user/0.
Aug 04 12:46:36 moose systemd[1]: Starting user@0.service - User Manager for UID 0...
Aug 04 12:46:36 moose (systemd)[921]: pam_unix(systemd-user:session): session opened for user root(uid=0) by (uid=0)
```

**Comment by carbontwelve** [comment]
After some additonal testing I am pretty sure this is a hardware issue with Hetzners dedicated server platform and subsequently why (unbeknownst to me at the time,) they do not yet support Debian 12. My suspicion is that their hardware for remotely managing servers is interfering with the reboot process and while its odd its broken for Debian 12 but not for Debian 11; this feels like a them problem.

**Comment by poettering** [comment]
OK, let's close this then, if this indeed a Hetzner problem.
