### ISSUE TITLE
networkd: ARP=no in carrier.network changes default for vlan.network

### ISSUE THREAD

**Issue by Kentzo** [systemd/systemd#28678]
### systemd version the issue has been seen with

247 (buster-backports)

### Used distribution

Debian 10

### Linux kernel version used

kernel-5.10.103-v7+

### CPU architectures issue was seen on

arm

### Component

networkd

### Expected behaviour you didn't see

Kernel default is used as default for VLANs

### Unexpected behaviour you saw

ARP value of the carrier interface is used as default for VLANs

### Steps to reproduce the problem

*00-eth.network:*
```
[Match]
...
Type=ether

[Network]
VLAN=...
...

[Link]
ARP=no
```

*01-vlan.network:*
```
[Match]
...
Type=vlan

[Network]
...
```

With such configuration unicast IP packets routed via the VLAN interface will have incorrect destination MAC address, in particular destination MAC will be the same as source MAC. Note that broadcast IP packets will use have appropriate destination MAC.

Removal of `ARP=no` from the carrier interface or addition of `ARP=yes` to the VLAN interface and reboot resolves the problem

**Comment by bluca** [comment]
That release is very old and no longer maintained, are you able to reproduce it on 254 or 253?

**Comment by Kentzo** [comment]
That's all I have at the moment.

**Comment by yuwata** [comment]
IIRC, the current behavior is the kernel's default. And as you commented, that's simply you made something spurious in your config.
Do you observe anything different from e.g. when you create vlan interface with `ip` command?

**Comment by Kentzo** [comment]
I had previously set it up via ifupdown without altering the ARP setting.

I do not know what "default kernel behavior" is. Perhaps vlan interfaces inheriting arp from underlying physical device is the default. But that was not immediately obvious from an example in systemd.network that I followed:

> For example, disabling ARP is useful when creating multiple MACVLAN or VLAN virtual interfaces atop a single lower-level physical interface, which will then only serve as a link/"bridge" device aggregating traffic to the same physical link and not participate in the network otherwise. Defaults to unset.

If the behavior is as expected, can a note be added to the documentation?

**Comment by yuwata** [comment]
Not sure. That depends on the network what you want to configure, no?
Extending man page is welcome. Please submit changes. Thank you.

**Comment by Kentzo** [comment]
> That depends on the network what you want to configure, no?

Physical ethernet interface whose only job is be a carrier for a number of VLAN interfaces.

Currently this ethernet interface is configured like this:

```
[Match]
Name=...
Type=ether

[Network]
VLAN=...
VLAN=...

DHCP=no
LinkLocalAddressing=no
LLDP=no
EmitLLDP=no
IPv6AcceptRA=no

[Link]
ARP=no
```

> Extending man page is welcome. Please submit changes. Thank you.

Sure, but before I can do that I'd like to understand whether what I experienced was due to "default kernel behavior", systemd-networkd as expected or a systemd-networkd bug (possibly fixed as I'm running the old version).

**Comment by yuwata** [comment]
IIRC, nothing changed related to ARP= setting recently. And we simply pass ARP setting to the kernel in the same way that `ip` command does.

Please try to create vlan interfaces and set the arp setting on the interface by `ip` command, and check the behavior.
If you observe anything different from the case when you configure with networkd, then that may be a bug in networkd. Otherwise, that is the kernel default behavior when you configure such.

Adding test case is highly welcome, though.
