### ISSUE TITLE
INFO: task shutdown:1 block for more then 120 seconds

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#2868]
### Submission type
- [X ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229-3 on Arch Linux

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> System shutdown cleanly
### In case of bug report: Unexpected behaviour you saw

The machine does not reliability poweroff on a shutdown under the 4.4.x series on my Haswell machine.  About 30% of the time when I issue `shutdown -h now` the machine does not shutdown but does hang displaying a loop of error which repeat every 2 min until I hold in the power button.

After manually shutting off the box, I don't see anything in `journalctl -b -1` that indicates an error or warning, so I'm thinking whatever is happening occurs after the journal logging as evident by the last few lines lines shown below; the complete journalctl is [here](https://gist.github.com/graysky2/20e5bddd8a1e016e0c4c).

```
Feb 14 11:02:41 quartz systemd[1]: Reached target Shutdown.
Feb 14 11:02:41 quartz systemd[1]: Reached target Final Step.
Feb 14 11:02:41 quartz systemd[1]: Starting Power-Off...
Feb 14 11:02:41 quartz systemd[1]: Shutting down.
Feb 14 11:02:41 quartz systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Feb 14 11:02:41 quartz systemd-journald[186]: Journal stopped
```
### In case of bug report: Steps to reproduce the problem

> Poweroff the system with `shutdown -h now` ... about 30% of the time, the above is what I get.

```
INFO: task shutdown:1 block for more then 120 seconds.
Not tainted 4.4.4-1-ARCH #1
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
INFO: task kworker/0:3:1642 block for more than 120 seconds.
Not tainted 4.4.4-1-ARCH #1
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

Note - I opened [this bug against the kernel](https://bugzilla.kernel.org/show_bug.cgi?id=113701) since this only began to happen with the 4.4.x series and downgrading to 4.3.6 totally fixes the bug, but it has been suggested that the problem is in fact not with the kernel but with systemd due to this experiment:

**Goal:** rule out the kernel as the culprit.

**Experiment:**  boot with init=/bin/bash added to the kernel command line and after boot, do this:

```
echo 1 > /proc/sys/kernel/sysrq  # enable sysrq
echo o > /proc/sysrq-trigger     # immediately power off
```

**Expected result:** The above two commands will immediately shutoff the computer without doing anything(syncing file system, shutting off user space daemons, etc.), but since we are using bash as init and nothing gets started and the filesystem is mounted read only, it shouldn't cause any harm to your system.

**Conclusion:** Poweroff works with all the kernels so the the shutoff problem lies elsewhere possibly with the initi system.

**Result:** Booted into v4.4.5 a total of 5 times in a row and in all 5 cases the system went down instantaneously as I have observed with the v4.3.6 kernel.  I can only conclude that systemd 229 + linux 4.4.x causes these problems.

**Comment by graysky2** [comment]
@evverx - Any thoughts?

**Comment by evverx** [comment]
> 229-3 on Arch Linux
> I can only conclude that systemd 229 + linux 4.4.x causes these problems.

Are you sure?

> Feb 14 08:47:43 quartz systemd[1]: systemd 228 running in system mode.

**Comment by graysky2** [comment]
@evverx - Yes, it initially began with version 228 but persists under 229.

```
% pacman -Q systemd      
systemd 229-3
```

**Comment by evverx** [comment]
OK.
What is the output of:

```
type shutdown
ls -l $(type -P shutdown)
```

?

Does `systemctl poweroff` work?

**Comment by evverx** [comment]
Also,
https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

> If the executable /run/initramfs/shutdown exists systemd will use it to jump back into the initrd on shutdown. /run/initramfs should be a usable initrd environment to which systemd will pivot back and the "shutdown" executable in it should be able to detach all complex storage that for example was needed to mount the root file system. It's the job of the initrd to set up this directory and executable in the right way so that this works correctly. The shutdown binary is invoked with the shutdown verb as argv[1], optionally followed (in argv[2], argv[3], ...) by systemd's original command line options, for example --log-level= and similar.

What does your `initramfs` put in the `/run/initramfs/shutdown`?

**Comment by graysky2** [comment]
Sorry, was away.  Here are the answers you asked about:

```
% type shutdown
shutdown is /usr/bin/shutdown

% ls -l $(type -P shutdown)
lrwxrwxrwx 1 root root 9 Feb 18 21:56 /usr/bin/shutdown -> systemctl
```

I don't know how to answer your question about the `initramfs` on Arch.  I do have an empty directory at /run/initramfs.

**Comment by evverx** [comment]
There is a [`mkinitcpio-generate-shutdown-ramfs.service`](https://projects.archlinux.org/mkinitcpio.git/tree/systemd/mkinitcpio-generate-shutdown-ramfs.service).

I've found [`systemd[1]: Started Generate shutdown-ramfs`](https://gist.github.com/graysky2/20e5bddd8a1e016e0c4c#file-journalctl-with-hang-L1465) in your logs.

**Comment by graysky2** [comment]
> Does systemctl poweroff work?

It does.  As I said in the initial report, this behavior doesn't occur 100% of the time which makes it tough to troubleshoot.  In my dmesg, it does show that kodi segfaulted upon shutdown which might be to blame?  I am initiating the powerdown from kodi's UI selecting [shutdown](http://kodi.wiki/view/Shutdown_Menu#Shutdown_menu).  Kodi is starting using [this](https://github.com/graysky2/kodi-standalone-service/blob/master/init/kodi.service) systemd service.  Before updating to the linux kernel 4.4.x series, kodi shutdown the system without a glitch.

**Comment by kyawthusoe45** [comment]
Same problem here, Debian 8 with systemd version 215.

**Comment by graysky2** [comment]
@kyawthusoe3142 - Are you seeing the [kodi segfault](https://gist.github.com/graysky2/20e5bddd8a1e016e0c4c#file-journalctl-with-hang-L1416) line in your journalctl output like I am?  Is systemd causing the segfault or is kodi...???

**Comment by kyawthusoe45** [comment]
Why? No. Mine is avahi-daemon problem. I calmed myself down. I thought if it'd no problems on ubuntu 15.04, then it'll evolve itself in next few months.

**Comment by poettering** [comment]
Such "INFO: task shutdown:1 block for more then 120seconds" messages are generally kernel problems, which detects its own hangs. systemd might be the trigger for this, but the bug is not in systemd but in the kernel. Under no circumstances should userspace (of which systemd is  a part of) be able to make the kernel hang like this, even if userspace has privileges (which systemd) has.

Hence, please report this to the kernel folks, this needs to be tracked down and fixed in the kernel. This is probably some kernel component that systemd touches and that is simply not touched if you boot with init=/bin/sh.

Anyway, closing here, as this is a kernel issue.

**Comment by Aaahh** [comment]
Not your bug but @graysky2 @kyawthusoe3142 any updates?

**Comment by kyawthusoe3142** [comment]
@Aaahh I'm on Arch for over a year now.
