### ISSUE TITLE
Disconnecting USB stick kills systemd?

### ISSUE THREAD

**Issue by jaystrictor** [systemd/systemd#2869]
### Submission type
- Bug report
### systemd version the issue has been seen with

systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

ArchLinux
### In case of bug report: Expected behaviour you didn't see

I ran `systemctl` and expected to see the unit list.
### In case of bug report: Unexpected behaviour you saw

``` sh
# systemctl
Failed to list units: Connection timed out
```

Issuing any commands to systemd was not possible anymore. I could not reboot, also cd'ing into `/proc/sys/fs/binfmt_misc` was not possible anymore.

Looking at `journalctl`, I can see the following messages, probably at the time when I disconnected a USB stick:

```
Mar 18 19:18:00 desktop kernel: usb 2-2: USB disconnect, device number 2
Mar 18 19:18:00 desktop udisksd[682]: Cleaning up mount point /run/media/jay/USB Stick Data (device 8:34 no longer exist)
Mar 18 19:18:00 desktop systemd[526]: Assertion 'b' failed at src/basic/path-util.c:390, function path_compare(). Aborting.
Mar 18 19:18:00 desktop systemd[1]: Assertion 'b' failed at src/basic/path-util.c:390, function path_compare(). Aborting.
Mar 18 19:18:00 desktop mount.exfat[1047]: failed to write super block
Mar 18 19:18:00 desktop udisksd[682]: Cleaning up mount point /run/media/jay/Windows (device 8:33 no longer exist)
Mar 18 19:18:00 desktop ntfs-3g[1054]: Unmounting /dev/sdc1 (Windows)
Mar 18 19:18:03 desktop dbus[473]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Mar 18 19:18:28 desktop dbus[473]: [system] Failed to activate service 'org.freedesktop.Avahi': timed out
Mar 18 19:18:29 desktop dbus[473]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
```
### In case of bug report: Steps to reproduce the problem

I cannot reproduce the problem by connecting/disconnecting the USB stick. It was a one time issue so far. I am not expecting to see it again. Still reporting, maybe it is useful to you.

**Comment by evverx** [comment]
See https://github.com/systemd/systemd/pull/2834

**Comment by jaystrictor** [comment]
Ahh thank you, I see. This should fix it then.
