### ISSUE TITLE
zsh completion is slow with recent systemd version

### ISSUE THREAD

**Issue by maru-sama** [systemd/systemd#28707]
### systemd version the issue has been seen with

254

### Used distribution

Debian Sid

### Linux kernel version used

6.3.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Quick completion when doing systemctl status cr<TAB>

### Unexpected behaviour you saw

Instead of an immediate return it takes several seconds to complete, cron.service in this case.

### Steps to reproduce the problem

I tracked this problem down to a change introduced in https://github.com/systemd/systemd/commit/8139407ec109594c11c8c7d2936e9f0eba610f05. This change removed the $PREFIX in the systemctl_get_non_template_names function. https://github.com/systemd/systemd/blob/main/shell-completion/zsh/_systemctl.in#L198

As a result the cache is apparently not working correctly and the completion is slow. Adding the $PREFIX again results in a fast completion again.

```
__systemctl list-unit-files "$PREFIX*"
__systemctl list-units --all "$PREFIX*"
```

I found this by comparing version 252 I was running on another machine which did not have this issue and 254 from debian sid.

**Comment by rpigott** [comment]
What zsh version?

**Comment by rpigott** [comment]
Oh I see this is about systemctl status. systemctl status was never cached. You're just observing that `systemctl list-units --all` is a slow operation without a glob to filter the results.

That said, seems like non-template names uses the same invocations as _sys_really_all_units which is a cached parameter, so we should probably just use that instead.

**Comment by rpigott** [comment]
Please try #28710.

**Comment by maru-sama** [comment]
Hello, this does not make a big difference for me. For testing I took the _systemctl file from version 252.6 and status as well as stop and start are fast again.

**Comment by maru-sama** [comment]
> Oh I see this is about systemctl status. systemctl status was never cached. You're just observing that `systemctl list-units --all` is a slow operation especially without a glob to filter the results.

For the record this command is not slow on the machine I am testing this on...

time systemctl list-units --all --no-pager  0,01s user 0,01s system 48% cpu 0,041 total

**Comment by rpigott** [comment]
Can you share the output of `zstyle -L ':completion:*' maybe?

**Comment by maru-sama** [comment]
Hello,

Apparently it does not seem to be enabled...
```
zstyle ':completion:*' accept-exact-dirs true
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==32=31}:${(s.:.)LS_COLORS}")'
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu 'select=long'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
```

That said it works fine with the old _systemctl version without the need for caching apparently.

**Comment by rpigott** [comment]
> That said it works fine with the old _systemctl version without the need for caching apparently.

Well, it didn't really. The glob argument previously provided by PREFIX can speed up the execution of list-unit-files, but it unfortunately caused the completions to incorrectly filter results. With caching disabled I suppose you would never get the error though.

**Comment by maru-sama** [comment]
I see, so this means that starting with newer versions caching needs to be enabled to get the same level of performance as before. I will try with caching enabled.

**Comment by maru-sama** [comment]
Ok, apparently I am doing something wrong. I enabled caching `zstyle ':completion:*' use-cache true` but the cache is not being created.

**Comment by rpigott** [comment]
With or without #28710?

**Comment by rpigott** [comment]
If its necessary for perf maybe we can reintroduce the pattern parameter to the verbs that are not practical to cache, like `systemctl start`.

**Comment by maru-sama** [comment]
Ok, with #28710 "status" is fast again, but start and stop are still slow. Quick question is it possible to have this in way that it is also fast with cache disabled, since I guess this is the standard setup. So something along the line of without cache use the prefix, with cache do not use it?

**Comment by rpigott** [comment]
I think I'd rather try to teach systemd some kinda ListStartableUnits method or something that would be useful for this purpose. After all, even if you apply PREFIX as a pattern for list-unit-files you can still expect start to be quite slow when the user attempts completion at the beginning of the word.

**Comment by maru-sama** [comment]
The ListStartableUnits sounds loke a good idea, but ad interim would it be possible to add back the PREFIX to start and stop to make it perform normally again?

**Comment by rpigott** [comment]
See if the latest commit in #28710 is helpful to you.

**Comment by maru-sama** [comment]
Hello,

I ran a quick check with this and it looks a lot better, "status", "start", "stop" all work ok now for me. That said you have to enable use_cache now to have the same performance with the "status" call. I understand that this change fixes an issue but it might be surprising once a user witout cache enabled move to a newer version and then sees this speed issue. That said I am apparently the first one to notice this, so it might be a non-issue at all. :)
