### ISSUE TITLE
systemd-sysusers create no group or users anymore

### ISSUE THREAD

**Issue by MaxFberg** [systemd/systemd#28700]
### systemd version the issue has been seen with

253

### Used distribution

Manjaro 

### Linux kernel version used

kernel 6.4.6-1-Manjaro

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysusers

### Expected behaviour you didn't see

new system user/group is created after running 20-systemd-sysusers.hook (or manually with systemd-sysusers)

### Unexpected behaviour you saw

new system group/user is not created. get an Error "Failed to check if group already exists: Unknown error 358416419"

### Steps to reproduce the problem

If the groups and users are already created and exists, no error will arise. The system runs fine until a package with new system groups is installed (for me it was cups).  A new conf-file is saved under /usr/libs/sysusers.d/. While upgrading system, 20-systemd-sysusers.hook shows an error message and stop to create new group/user.

The groups and user can be manually created without any problem. After checking pacman.log, the error arises the first time in march 23 after upgrading systemd from 252.5-1 to 252.8-1. Before the 20-systemd-sysuers.hook runs without any problems. 

To reproduce:
Create file test.conf with 'g test 299 -' in /usr/lib/sysusers.d and start as root systemd-sysusers. The group is not created. Error "Failed to check if group test already exists: Unknown error 358416419" shows up. 

Version installed now: systemd 253.7-1-manjaro

**Comment by keszybz** [comment]
Arch hooks and and nss config need to be debugged downstream. This error message is after a call to `getgrnam`, which calls into the nss stack and the results depend on `nsswitch.conf`. It sounds like some module there is returning a bogus error.

**Comment by MaxFberg** [comment]
Yes, after checking the error message on sysusers code, I have seen that this error shows up after checking nss. I have found nothing inside nsswitch.conf: 

```
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files systemd sss
group: files [SUCCESS=merge] systemd sss
shadow: files systemd
gshadow: files systemd

publickey: files

hosts: mymachines mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

**Comment by MaxFberg** [comment]
I have found the reason. And yes, it has nothing to do with sysusers. After checking the sssd.log, I have seen that sssd get incorrect user information. The problem was inside the sssd.conf. The information from our institute side was not correct. After changing this line:
re_expression = (((?P<domain>[^\\]+)\\(?P<name>.+$))|((?P<name>[^@]+)@(?P<domain>.+$)))

to 

re_expression = (((?P<domain>[^\\]+)\\(?P<name>.+$))|((?P<name>[^@]+)@(?P<domain>.+$))|(?P<name>.+$))  

everything is working now.
