### ISSUE TITLE
Need some help to find problem with hight cpu usage of udevd

### ISSUE THREAD

**Issue by manfredlotz** [systemd/systemd#28701]
### systemd version the issue has been seen with

254

### Used distribution

EndeavourOS

### Linux kernel version used

6.1.39-3-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

udevd daemon should not use much cpu.

### Unexpected behaviour you saw

udevd daemon has hight cpu usage

Actually, I don't think it is a bug in udevd but like to get some hints how to get to the root of the problem. It somehow has to do with usb ports.... Thanks for looking into it.

### Steps to reproduce the problem

Constantly hight cpu usage

```
842 root      20   0  169944  59460  58388 R  79.4   0.2  29:38.06 systemd-journal
```
This is after 42 minutes uptime

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
udevadm monitor shows

...
KERNEL[2575.438044] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6/tty/ttyACM2 (tty)
KERNEL[2575.438083] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.7 (usb)
KERNEL[2575.438120] unbind   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
KERNEL[2575.438156] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.6 (usb)
KERNEL[2575.438194] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.7 (usb)
KERNEL[2575.438240] remove   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.8 (usb)
...

more or less repeating.
```

**Comment by poettering** [comment]
the output you show actually shows that the kernel is generating your flood of uevents. udev then just has to react to that.

i.e. this is probably some buggy usb hw or driver, and we just get flooded with the events this causes.

maybe a faulty usb cable or so?

anyway, this is not actionable here, the "udevadm monitor" line you ran shows the kernel is seeing these events already. 

closing hence.

**Comment by manfredlotz** [comment]
@poettering Thanks for your reply. 

For the records: This is an older HP ZBook G4 laptop. I disabled `Mobile Network Device(WWAN)` in bios and now `udevd` daemon runs ok.
