### ISSUE TITLE
busctl misrepresents dict entry as JSON array rather than object as of commit 684bce3

### ISSUE THREAD

**Issue by jasonccox** [systemd/systemd#28711]
### systemd version the issue has been seen with

254-1

### Used distribution

Arch Linux

### Linux kernel version used

6.4.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

busctl should represent a dbus `DICT_ENTRY` as a JSON object (e.g., `{"key": "value"}`).

### Unexpected behaviour you saw

busctl represents a dbus `DICT_ENTRY` as a JSON array (e.g., `["key", "value"]`).

### Steps to reproduce the problem

I'm listing notifications using the `makoctl` script provided by [mako](https://github.com/emersion/mako). Under the hood, this runs the following command:

```
busctl -j --user call org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako -- ListNotifications
```

With a single test notification, this produces the following output using systemd 254 (formatted for readability):

```
{
  "type": "aa{sv}",
  "data": [
    [
      [
        "app-name",
        {"type": "s", "data": "notify-send"},
        "app-icon",
        {"type": "s", "data": ""},
        "category",
        {"type": "s", "data": ""},
        "desktop-entry",
        {"type": "s", "data": ""},
        "summary",
        {"type": "s", "data": "test"},
        "body",
        {"type": "s", "data": ""},
        "id",
        {"type": "u", "data": 88},
        "urgency",
        {"type": "y", "data": 1},
        "actions",
        {"type": "a{ss}", "data": []}
      ]
    ]
  ]
}
``` 

Without the `-j` flag, still on version 254: 

```
aa{sv} 1 9 "app-name" s "notify-send" "app-icon" s "" "category" s "" "desktop-entry" s "" "summary" s "test" "body" s "" "id" u 88 "urgency" y 1 "actions" a{ss} 0
```

I get the same thing using busctl compiled from the latest `main` (commit 81e0478).

As can be seen from the output without the `-j` flag, the response is a `DICT_ENTRY` associating `STRING` keys to `VARIANT` values. To me, it seems that a `DICT_ENTRY` is best represented in JSON as an object, but busctl is representing it as an array, with the key element followed by the value element.

In fact, busctl used to represent `DICT_ENTRY`s as JSON objects. However, commit 684bce3 (busctl: use json_variant_append_array()) seems to have changed that. For example, with that commit reverted, I get the same output without the `-j` flag, but I get the following with the `-j` flag:

```
{
  "type": "aa{sv}",
  "data": [
    [
      {
        "app-name": {"type": "s", "data": "notify-send"},
        "app-icon": {"type": "s", "data": ""},
        "category": {"type": "s", "data": ""},
        "desktop-entry": {"type": "s", "data": ""},
        "summary": {"type": "s", "data": "test"},
        "body": {"type": "s", "data": ""},
        "id": {"type": "u", "data": 88},
        "urgency": {"type": "y", "data": 1},
        "actions": {"type": "a{ss}", "data": {}}
      }
    ]
  ]
}
```

I haven't had the time to dig in deeply and see exactly what in commit 684bce3 is causing this new behavior. I'm also not sure if this behavior is specific to the response provided by mako or if it happens with all `DICT_ENTRY` data types, but I suspect the latter.

I don't know if this change was intentional. It feels like a bug to me -- a key-value data type maps much better to a JSON object than a JSON array.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #28713. If possible, please test the patch.
