### ISSUE TITLE
udev: can't get the filesystem in multisession CD-ROMs

### ISSUE THREAD

**Issue by robertxgray** [systemd/systemd#2872]
Hi,

Udev seems unable to get the file system in multisession CD-ROMs since version 219 (Fedora 22). The problem was not present before version 216 (Fedora 21). I have also confirmed the problem in Ubuntu 15.10. This means all the file managers ignore the disks and they can't be mounted via udisksctl (udisks2). They can still be mounted via the mount command or udisks.

Also, there's an error in the journal when the disks are inserted.

```
mar 19 02:10:39 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#5 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
mar 19 02:10:39 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#5 Sense Key : Medium Error [current] 
mar 19 02:10:39 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#5 Add. Sense: L-EC uncorrectable error
mar 19 02:10:39 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#5 CDB: Read(10) 28 00 00 03 ce fc 00 00 02 00
mar 19 02:10:39 warlock.net01 kernel: blk_update_request: I/O error, dev sr0, sector 998384
mar 19 02:10:44 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#8 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
mar 19 02:10:44 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#8 Sense Key : Medium Error [current] 
mar 19 02:10:44 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#8 Add. Sense: L-EC uncorrectable error
mar 19 02:10:44 warlock.net01 kernel: sr 0:0:0:0: [sr0] tag#8 CDB: Read(10) 28 00 00 03 ce fc 00 00 02 00
mar 19 02:10:44 warlock.net01 kernel: blk_update_request: I/O error, dev sr0, sector 998384
mar 19 02:10:44 warlock.net01 kernel: Buffer I/O error on dev sr0, logical block 124798, async page read
```

I have uploaded the output of "udevadm info", using the same disk and computer with three different distributions. Remember the problem is not present in Fedora 21.
[udev_fedora21.txt](https://github.com/systemd/systemd/files/180585/udev_fedora21.txt)
[udev_fedora22.txt](https://github.com/systemd/systemd/files/180586/udev_fedora22.txt)
[udev_ubuntu1510.txt](https://github.com/systemd/systemd/files/180587/udev_ubuntu1510.txt)

Here's also the output of cd-info.
[cd-info.txt](https://github.com/systemd/systemd/files/180583/cd-info.txt)

More reports about the problem are available here:
https://ask.fedoraproject.org/en/question/74796/fedora-22-cd-rs-with-cdfsiso9660-fail-to-mount/
https://bugzilla.redhat.com/show_bug.cgi?id=1234317

I was not even aware that most of my CD-ROMS are multisession before the problem. It just happens to be the default in K3B. Other people are using Easy CD Creator in the reports.

Thank you and best regards.

**Comment by robertxgray** [comment]
I have written to the CD again to finalize the multisession.

Before

```
E: ID_CDROM_MEDIA_SESSION_NEXT=2
E: ID_CDROM_MEDIA_STATE=appendable
E: ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
E: USEC_INITIALIZED=28425
```

After

```
E: ID_CDROM_MEDIA_SESSION_LAST_OFFSET=483917824
E: ID_CDROM_MEDIA_STATE=complete
E: ID_CDROM_MEDIA_TRACK_COUNT_DATA=2
E: USEC_INITIALIZED=71456
```

But still no ID_FS_\* attributes in udev :disappointed:

**Comment by robertxgray** [comment]
Another udevadm info with Ubuntu 16.04 beta 2 (udev v229). The problem persists. 
[udev_ubuntu1604.txt](https://github.com/systemd/systemd/files/201546/udev_ubuntu1604.txt)

Some people are recovering the cdrom entries in fstab as a workaround.
http://askubuntu.com/questions/689105/cannot-mount-cds-after-update-to-15-10
https://bbs.archlinux.org/viewtopic.php?id=202272

**Comment by poettering** [comment]
So, the general problem is that none of us in the systemd camp really have CDROM drives anymore, and not they expertise to do anything about this either. cdrom_id should really be moved to some package maintained by the storage people, i.e. people who understand this and care about it. Otherwise I feel there's little that will change about this issue.

Also see:

https://github.com/systemd/systemd/pull/2500#issuecomment-178071901

**Comment by robertxgray** [comment]
Good news. I tried to fix the problem by myself and at this point I am pretty confident about two things. First, the problem was not introduced in udev itself but in libblkid 2.26. Second, it has already been fixed upstream.

In Fedora, you can get libblkid.so.1.1.0 from Rawhide (2.28-1.fc25) as a workaround. The same file from Fedora 21 also works.

**Comment by poettering** [comment]
Ah, very good. Thanks for reporting back!
