### ISSUE TITLE
veritysetup-generator generated units are missing After=veritysetup-pre.target

### ISSUE THREAD

**Issue by polarina** [systemd/systemd#28725]
### systemd version the issue has been seen with

254

### CPU architectures issue was seen on

None

### Component

systemd-veritysetup

### Expected behaviour you didn't see

Units generated by `systemd-veritysetup-generator` should order themselves after `veritysetup-pre.target` as documented by the `systemd.special` man page.

### Unexpected behaviour you saw

Generated units are ordered after `cryptsetup-pre.target`. There is no ordering with regards to `veritysetup-pre.target`.

See https://github.com/systemd/systemd/blob/5a96b32dead5132ba37a8b968c59101c2aac8d23/src/shared/generator.c#L832

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #28729.
