### ISSUE TITLE
cifs automount timeout

### ISSUE THREAD

**Issue by AeliusSaionji** [systemd/systemd#2873]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 229
### Used distribution

> archlinux
### Problem

In my fstab, I have an entry

``` fstab
//192.168.1.101/Music /media/PC/Music cifs credentials=/etc/PC.smb,uid=Link,gid=users,noauto,x-systemd.automount,x-systemd.idle-timeout=1min,x-systemd.device-timeout=5s 0 0
```

However when I'm not on my local network, the timeout is not 5s, and any process that glances at the mount point gets locked up. I learned from a comment here on a github issue that device-timeout refers to block devices and will not work on CIFS- would have been nice to read that in the manpage :)

It seems the only way to specify a timeout for network shares is to use the `TimeoutSec` option in a .mount file. I created an override for the unit file generated from the fstab entry (and it appears in `systemctl cat media-PC-Music.mount`):

```
[Mount]
TimeoutSec=5
```

Here's the bug: the 5s timeout is only honored on the first attempt to access the mountpoint.
`$ time ls /media/PC/Music` ends in 5s on the first attempt, but hangs indefinitely on all successive attempts. Sometimes the process can't even be killed and I need to reboot!

**Comment by poettering** [comment]
such a timeout logic really needs to be implemented by the underlying file system in case of network file systems. i.e. the CIFS mount tool needs to support this, otherwise we cannot do anything about it...

**Comment by poettering** [comment]
have you checked whether CIFS allows you to configure such a timeout?

**Comment by AeliusSaionji** [comment]
I have, and it does not, unfortunately.
