### ISSUE TITLE
Strange "thawing" tag while executing a bash script

### ISSUE THREAD

**Issue by Zhaoxun** [systemd/systemd#28753]
### systemd version the issue has been seen with

239

### Used distribution

CentOS 7.6

### Linux kernel version used

4.18.0-240.1.1.el8_3.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Unexpected behaviour you saw

the '**thawing**' tag of the bash script that systemd service runs:
```
systemctl status auto_quote
● auto_quote.service - run run_quotelive.sh ## <-change run_XXX.sh
   Loaded: loaded (/usr/lib/systemd/system/auto_quote.service; enabled; vendor preset: disabled)
   Active: active (running) (thawing) since Thu 2023-08-10 15:21:20 CST; 3s ago
 Main PID: 3084861 (bash)
    Tasks: 2 (limit: 5366)
   Memory: 8.6M
   CGroup: /system.slice/auto_quote.service
           ├─3084861 /bin/bash /root/run_quotelive.sh ## <-change run_XXX.sh
           └─3084863 python3 -m http.server 1234

Aug 10 15:21:20 10-13-107-213 systemd[1]: Started run run_quotelive.sh ## <-change run_XXX.sh.
```

### Steps to reproduce the problem

/lib/systemd/system/auto_quote.service:
```
[Unit]
Description=run run_quotelive.sh ## <-change run_XXX.sh
After=network.service

[Service]
Type=simple
ExecStart=/bin/bash /root/run_quotelive.sh ## <-change run_XXX.sh
Restart=on-failure
RestartSec=3
## systemd bears daemon duty

[Install]
WantedBy=multi-user.target
```
/root/run_quotelive.sh:
```
cd /root/quotelive
cmd='python3 -m http.server 1234'

echo -e '\n'  `date +'%Y/%m/%d %a, %X'`: STARTING - "$cmd" '\n'  >> out.log
$cmd >>out.log 2>&1
#if [ $? -ne 0]; then
#  echo -e '\n'  `date +'%Y/%m/%d %a, %X'`: PROCESS FAILED  >> out.log
#  exit 5 # make an error exit for service to restart
#fi
```
After saving both scripts, enter `systemctl start auto_quote`

**Comment by poettering** [comment]
i can't make sense of what you are asking. But note this is a bug tracker and feature request tracker, and only submissions for the two most recent systemd versions shallbe posted here. i.e. 254 and 253 at the moment. 239 is *ancient* for that.

but it seems you have more of a support question, hence plesae contact systemd-devel instead, i.e. https://lists.freedesktop.org/mailman/listinfo/systemd-devel

the issue submission for should have made all this very clear actually.
