### ISSUE TITLE
Mount attempt receives SIGTERM from systemd after unknown timeout

### ISSUE THREAD

**Issue by pittburgher** [systemd/systemd#28776]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-1039-oracle

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The mount completes successfully.

### Unexpected behaviour you saw

A SIGTERM is sent by systemd and received by the mount attempt.

### Steps to reproduce the problem

I am attempting to mount three mountpoints on a remote, parallel filesystem. Periodically, one of the the three mounts will not succeed. An inspection of the journal suggests that systemd is sending a SIGTERM to the failing mount, approximately 69 seconds after the mount attempt. It is not clear to me where the 69 second timeout is originating, or configured.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Aug 08 17:37:25 vrr-20230804-cst-client-1 mount[883]: Mounting 10.114.96.165/fs3 on /mnt/fs3

Aug 08 17:38:34 vrr-20230804-cst-client-1 systemd[1]: mnt\x2dfs1.mount: Mount process exited, code=killed, status=15/TERM

Aug 08 17:38:34 vrr-20230804-cst-client-1 mount[883]: SIGTERM received, quitting
```

**Comment by yuwata** [comment]
Sorry, v249 is too old here. Closing.
