### ISSUE TITLE
journalctl --verify memory leak

### ISSUE THREAD

**Issue by cairb** [systemd/systemd#28775]
### systemd version the issue has been seen with

246.9+

### Used distribution

Digi Yocto Linux ccimx6ulsbc 

### Linux kernel version used

5.4.84-dey+g43e12e2c1baa+

### CPU architectures issue was seen on

arm

### Component

systemd-journald

### Expected behaviour you didn't see

1, run journalctl --verify against each individual journal file,
2, When you run it against on all the journal files each time, you should not encounter memory problem because there is no reason to keep the memory allocated for those journal files that have verified passed

### Unexpected behaviour you saw

1, you can not run journalctl --verify against each individual journal file
2, when you have enough journal files, journalctl --verify will fail at 'Cannot allocate memory' on a journal file after a few PASS ahead of it. If you remove those files that had been verified PASS, and run journalctl --verify again, the failed one will show PASS

### Steps to reproduce the problem

1, accumulate enough journal ( My embedded has 1GB memory with each journal file max size 256MB):
`root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ ls -ltr
-rw-r-----    1 root     systemd- 268435456 Aug  4 18:39 system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal
-rw-r-----    1 root     systemd- 268435456 Aug  4 21:16 system@8abb438fa2664a25b292dc167785634b-0000000000084042-0006021d36e331cc.journal
-rw-r-----    1 root     systemd- 268435456 Aug  5 00:07 system@8abb438fa2664a25b292dc167785634b-00000000000c509e-0006021f67df7ed5.journal
-rw-r-----    1 root     systemd- 268435456 Aug  5 08:17 system@8abb438fa2664a25b292dc167785634b-0000000000105fdc-00060221cbec6bd2.journal
-rw-r-----    1 root     systemd- 268435456 Aug  6 04:18 system@8abb438fa2664a25b292dc167785634b-000000000014710e-00060228a56062f1.journal
-rw-r-----    1 root     systemd- 268435456 Aug  6 18:52 system@8abb438fa2664a25b292dc167785634b-0000000000191525-000602396d7919e2.journal
-rw-r-----    1 root     systemd- 268435456 Aug  7 09:26 system@8abb438fa2664a25b292dc167785634b-00000000001d9962-00060245a2259f8d.journal
-rw-r-----    1 root     systemd- 268435456 Aug  8 00:01 system@8abb438fa2664a25b292dc167785634b-0000000000221f69-00060251d877559f.journal
-rw-r-----    1 root     systemd- 268435456 Aug  8 14:36 system@8abb438fa2664a25b292dc167785634b-000000000026a4a5-0006025e10659e02.journal
-rw-r-----    1 root     systemd- 268435456 Aug  8 18:39 system@8abb438fa2664a25b292dc167785634b-00000000002b2926-0006026a4953a888.journal
-rw-r-----    1 root     systemd- 218103808 Aug  8 22:51 system.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ `
2,  Run 'journalctl --verify':
`root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ journalctl --verify
ff3c4b0: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000221f69-00060251d877559f.journal
ffffe78: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-00000000000c509e-0006021f67df7ed5.journal
ff221c0: Unused data (entry_offset==0)
ff22210: Unused data (entry_offset==0)
ff22278: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-000000000026a4a5-0006025e10659e02.journal
ffec1e0: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-00000000002b2926-0006026a4953a888.journal
fffff70: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000084042-0006021d36e331cc.journal
fffff38: Unused data (entry_offset==0)
File corruption detected at /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal:fffff38 (of 268435456 bytes, 99%).
FAIL: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal (Cannot allocate memory)
ffffea0: Unused data (entry_offset==0)
File corruption detected at /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000105fdc-00060221cbec6bd2.journal:ffffea0 (of 268435456 bytes, 99%).
FAIL: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000105fdc-00060221cbec6bd2.journal (Cannot allocate memory)
ff0d6b0: Unused data (entry_offset==0)
^C██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  57%
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$`
3, remove those journals that had been verified PASS:
`root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ rm system@8abb438fa2664a25b292dc167785634b-0000000000221f69-00060251d877559f.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ rm  system@8abb438fa2664a25b292dc167785634b-00000000000c509e-0006021f67df7ed5.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ rm system@8abb438fa2664a25b292dc167785634b-000000000026a4a5-0006025e10659e02.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ rm system@8abb438fa2664a25b292dc167785634b-00000000002b2926-0006026a4953a888.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ rm system@8abb438fa2664a25b292dc167785634b-0000000000084042-0006021d36e331cc.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ ls -ltr
-rw-r-----    1 root     systemd- 268435456 Aug  4 18:39 system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal
-rw-r-----    1 root     systemd- 268435456 Aug  5 08:17 system@8abb438fa2664a25b292dc167785634b-0000000000105fdc-00060221cbec6bd2.journal
-rw-r-----    1 root     systemd- 268435456 Aug  6 04:18 system@8abb438fa2664a25b292dc167785634b-000000000014710e-00060228a56062f1.journal
-rw-r-----    1 root     systemd- 268435456 Aug  6 18:52 system@8abb438fa2664a25b292dc167785634b-0000000000191525-000602396d7919e2.journal
-rw-r-----    1 root     systemd- 268435456 Aug  7 09:26 system@8abb438fa2664a25b292dc167785634b-00000000001d9962-00060245a2259f8d.journal
-rw-r-----    1 root     systemd- 268435456 Aug  8 23:19 system@8abb438fa2664a25b292dc167785634b-00000000002f508a-0006026db04f5247.journal
-rw-r-----    1 root     systemd-  67108864 Aug  9 00:06 system.journal
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$`
4, run 'journalctl --verify' again:
`root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$ journalctl --verify
f76f508: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-00000000002f508a-0006026db04f5247.journal
fffff38: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal
ffffea0: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000105fdc-00060221cbec6bd2.journal
ff0d6b0: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-0000000000191525-000602396d7919e2.journal
ff655e8: Unused data (entry_offset==0)
PASS: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-00000000001d9962-00060245a2259f8d.journal
File corruption detected at /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-000000000014710e-00060228a56062f1.journal:ffffdf8 (of 268435456 bytes, 99%).
FAIL: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system@8abb438fa2664a25b292dc167785634b-000000000014710e-00060228a56062f1.journal (Cannot allocate memory)
File corruption detected at /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system.journal:7dccc20 (of 134217728 bytes, 98%).
FAIL: /var/log/journal/220cd229b8604ef5bc4444e3ea9d059a/system.journal (Cannot allocate memory)
root@ccimx6ulsbc:/var/log/journal/220cd229b8604ef5bc4444e3ea9d059a$`
5,  As you can see here, journal file 'system@8abb438fa2664a25b292dc167785634b-0000000000042d61-0006021636d619a3.journal' was initially verified failed, and now showing PASS. You can repeats steps 3,4 and get the same result again and again

**Comment by yuwata** [comment]
Sorry, v246 is too old here. Closing

**Comment by vcaputo** [comment]
@cairb maybe you can reproduce the issue on a current version, this would be a bug upstream cares about if current.
