### ISSUE TITLE
sensor hwdb

### ISSUE THREAD

**Issue by colonia** [systemd/systemd#28783]
### Component

systemd-hwdb

### Is your feature request related to a problem? Please describe

I have an ASUS T100 with Debian12. On Xorg, the display is upside down. In /lib/udev/hwdb.d/60-sensor.hwdb it says:
sensor:modalias:acpi:INVN6500*:dmi:*svnASUSTeK*:*pnM80TA:*
sensor:modalias:acpi:INVN6500*:dmi:*svnASUSTeK*:*pnT100TA:*
sensor:modalias:acpi:INVN6500*:dmi:*svnASUSTeK*:pnT200TA:*
 ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1

### Describe the solution you'd like

However, the company was still called ASUS at the time...
Hence my change:
`/lib/udev/hwdb.d/61-sensor-local.hwdb
sensor:modalias:acpi:INVN6500*:dmi:*svnASUS*:*pnT100TAS:*\
sensor:modalias:acpi:INVN6500*:dmi:*svnASUS*:*pnT100TA:*\
 ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1`

**Comment by yuwata** [comment]
Please submit the change as a PR. Thank you.

**Comment by poettering** [comment]
Let's close this here. Please submit your new addition as PR, happy to review/merge then.
