### ISSUE TITLE
Kernel panic on boot with "Failed to execute /init (error -2)"

### ISSUE THREAD

**Issue by wKollendorf** [systemd/systemd#28780]
### systemd version the issue has been seen with

252.12

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

Booting successfully.

### Unexpected behaviour you saw

While booting, systemd-bootx64.efi (v252.12) does not find /init and the kernel panics. When replacing systemd-bootx64.efi with version 247, the system boots up fine.

On endeavouros forum, the issue is also discussed:
[Panic screen output](https://forum.endeavouros.com/t/package-update-kernel-included-frozen-at-running-post-transaction-hooks-1-9-reloading-system-manager-configuration/36165/16)

This only happens when the EFI partition is on an external disk connected by USB. And only on my older macbook pro from 2012. Using systemd-bootx64.efi (v252.12) on modern hardware does not have an issues.

So what changed from 247 to 252 in systemd-bootx64.efi that breaks bootup on older EFI hardware?

### Steps to reproduce the problem

Install EFI files on external USB disk and connect to an macbook pro from 2012 or older.

**Comment by medhefgo** [comment]
> So what changed from 247 to 252 in systemd-bootx64.efi that breaks bootup on older EFI hardware?

Too many to enumerate.

Are you booting a regular entry or a UKI? Please provide the output of `bootctl list` and/or the config snippet of the affected boot entry. If you press `p` in the boot menu, does the information listed match the config snippet?

You can try booting with `efi=debug` to see if it actually picks up the initrd we are passing.

Also, please try latest git or at least v254 (extracted from arch for example)? Also, a git bisection would be best.)

**Comment by wKollendorf** [comment]
I am booting a regular entry.

bootctl list:
```
type: Boot Loader Specification Type #1 (.conf)
        title: Debian GNU/Linux 12 (bookworm) (default) (selected)
           id: 499040a14a9db7c4fed137d264d28fe2-6.1.0-10-amd64.conf
       source: /boot/efi/loader/entries/499040a14a9db7c4fed137d264d28fe2-6.1.0-10-amd64.conf
     sort-key: debian
      version: 6.1.0-10-amd64
   machine-id: 499040a14a9db7c4fed137d264d28fe2
        linux: /499040a14a9db7c4fed137d264d28fe2/6.1.0-10-amd64/linux
       initrd: /499040a14a9db7c4fed137d264d28fe2/6.1.0-10-amd64/initrd.img-6.1.0-10-amd64
      options: root=UUID=8449ac0f-c165-4409-a0cf-2904a9a6a8b5 ro systemd.machine_id=499040a14a9db7c4fed137d264d28fe2
```

This is identical to what pressing p while being in boot menu:
![IMG_2262](https://github.com/systemd/systemd/assets/83725977/b77ea42a-4608-4eb1-a164-9bc9066f5614)

This is the output with debug option active:
![IMG_2263](https://github.com/systemd/systemd/assets/83725977/fa99f9f3-b1e9-4709-9583-52dbe922fc10)

**Comment by wKollendorf** [comment]
Just installed systemd version 254.1 and this version works. So I guess the issue can be closed. 

247 | 252.12 | 254.1
ok   | bad      | ok
