### ISSUE TITLE
Digital clock stops when changing user and going back to first user

### ISSUE THREAD

**Issue by HerbyW** [systemd/systemd#28842]
### systemd version the issue has been seen with

253.8-1.1

### Used distribution

Tumbleweed Opensuse

### Linux kernel version used

kernel 6.4.9-1-default (64-bit)

### CPU architectures issue was seen on

other

**Comment by poettering** [comment]
Hmm, what's this? This doesn't look like a systemd problem. Please talk to your distro of choice first.
