### ISSUE TITLE
journalctl lists multiple boot ids for the current boot

### ISSUE THREAD

**Issue by francispereira** [systemd/systemd#2884]
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> 215
### Used distribution

> McDebian based on Debian GNU/Linux 8 (jessie) 
> root@airport:~# uname -a
> Linux airport 4.2.4 #64 SMP Tue Dec 29 13:16:42 CST 2015 armv7l GNU/Linux
### Expected behaviour you didn't see

> One boot id for the current boot
### Unexpected behaviour you saw

> Three boot ids for the current boot
### Steps to reproduce the problem

> Happens randomly on platforms that do not have a RTC.
### Details

journalctl lists multiple boots for the current boot id. Logs from none of the boot ids are readable by journalctl.

`journalctl -f` appears to show current logs. 

```
root@airport:~# cat /proc/sys/kernel/random/boot_id
4860f8a9-014c-4da9-866c-f323fc4373c3
root@airport:~# journalctl --list-boots | grep 'f323fc4373c3'
-50 4860f8a9014c4da9866cf323fc4373c3 Thu 1970-01-01 05:30:08 IST—Tue 2016-03-22 15:24:32 IST
-49 4860f8a9014c4da9866cf323fc4373c3 Thu 1970-01-01 05:30:08 IST—Tue 2016-03-22 15:24:32 IST
-48 4860f8a9014c4da9866cf323fc4373c3 Thu 1970-01-01 05:30:08 IST—Tue 2016-03-22 15:24:32 IST
root@airport:~# journalctl -b -50
Failed to look up boot -50: Cannot assign requested address
root@airport:~# journalctl -b -49
Failed to look up boot -49: Cannot assign requested address
root@airport:~# journalctl -b -48
Failed to look up boot -48: Cannot assign requested address
```

**Comment by poettering** [comment]
215 is ancient, and we generally only track bugs in the two most recent systemd versions upstream (this is prominently visible in the issue template btw...)

Closing this. Please file a new issue, if you can reproduce this with a recent systemd version. Thanks.
