### ISSUE TITLE
systemd-boot is not showing the list of entries at the boot

### ISSUE THREAD

**Issue by Digitalone1** [systemd/systemd#28858]
### systemd version the issue has been seen with

254.1

### Used distribution

Arch Linux

### Linux kernel version used

6.4.10.arch1

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

systemd-boot showing the list of entries at the boot.

I have 3 `.conf` files in `/boot/loader/entries`. systemd-boot should show them in a list at the startup.

### Unexpected behaviour you saw

In the last days (maybe related to the last release of systemd) the entries are not shown at the boot.

I only see a black screen and a short message suggesting to press ESC if I want to reboot into the firmware.

### Steps to reproduce the problem

1. Turn on the laptop.
2. systemd-boot does not show the list.
3. On a blank screen, it waits 3-4 seconds and then starts loading the default entry.

### Additional program output to the terminal or log subsystem illustrating the issue

For years systemd-boot showed the correct entries at the boot. Now the only way to show them is to press ESC.

It's not even following the timeout I set. The following is my configuration in `/boot/loader/loader.conf`:

```sh
timeout 5
default arch
```

Only the default is respected. If I increase the timeout to 10, 15 or more seconds, systemd-boot is always waiting 3-4 seconds on a blank screen and then loads the default entry. The only way to stop it and show the list is to press ESC.

**Comment by YHNdnzj** [comment]
> It's not even following the timeout I set.

From [loader.conf(5)](https://man.archlinux.org/man/loader.conf.5.en):

> timeout
>    How long the boot menu should be shown before the default entry is booted, in seconds. This may be changed in the boot menu itself and will be stored as an EFI variable in that case, overriding this option.

Please try `bootctl set-timeout ""` to reset the EFI variable.

**Comment by Digitalone1** [comment]
> Please try `bootctl set-timeout ""` to reset the EFI variable.

Thanks @YHNdnzj, that solved the issue.
