### ISSUE TITLE
/dev is not yet bind mounted on /sysroot/dev when service with "Before=initrd-switch-root.service" run

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#28863]
### systemd version the issue has been seen with

253-6.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

6.4.7-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Some services running in the initrd want to tell the running daemon to transition to (or re-exec from) the real-root before initrd-switch-root.service switches root from the initrd to the real rootfs.

E.g. `/lib/systemd/system/plymouth-switch-root.service` (simplified):

```
[Unit]
Before=initrd-switch-root.service

[Service]
Type=oneshot
ExecStart=-/usr/bin/plymouth update-root-fs --new-root-dir=/sysroot
```

When the transition happens just before plymouth is processing udev events to open /dev/dri/card0, the following error might happen:

```
load_driver                                      : Opening '/dev/dri/card0'
load_driver                                      : open failed: No such file or directory
```

I believe this is happening because /dev/ has not been bind-mounted on /sysroot/dev at this point yet.

And the same problem happens with /proc just after plymouth has chroot-ed itself to /sysroot:

```
ply_get_process_command_line                  : Could not open /proc/1/cmdline: No such file or directory
```

I think that ideally what we want here is to split the `systemctl --no-block switch-root /sysroot` into 2 steps:

1. bind mount /sys, /proc and /dev are bind-mounted under /sysroot
2. do the actual chroot

This way services like `plymouth-switch-root.service` and also `mdmon@.service` can order themselves between the steps by using `After=step1`, `Before=step2`.

**Comment by poettering** [comment]
software that wants to survive the switch must do detach itself from the fs it runs in itself, it cannot assume it is called when both the old and the new tree are fully set up.

At this point I am very sure plymouth should be fixed to just upload the fds it wants to keep open to the fdstore and then a new plymouth should be run off the new root fs, deserializing the fds and picking them up again. i.e. letting code from the initrd survive into the host is always ugly as fuck, and we have way better mechanisms.

**Comment by jwrdegoede** [comment]
> software that wants to survive the switch must do detach itself from the fs it runs in itself, it cannot assume it is called when both the old and the new tree are fully set up.

I see, TBH it would be nice if this (both trees fully setup wrt /dev, /sys and /proc mount points) would be possible. But I can see how this is an unreasonable demand to make of systemd, so that we will need to fix this somehow on the plymouth side. So lets close this.

> At this point I am very sure plymouth should be fixed to just upload the fds it wants to keep open to the fdstore and then a new plymouth should be run off the new root fs, deserializing the fds and picking them up again. i.e. letting code from the initrd survive into the host is always ugly as fuck, and we have way better mechanisms.

The problem with that approach is that it would be quite ugly visually since then the boot animation would freeze until the new plymouth is ready to take it over, which can easily take a second.
