### ISSUE TITLE
LogsDirectory{Owner,Group} and LogsDirectoryFileMode required

### ISSUE THREAD

**Issue by jelmd** [systemd/systemd#28876]
### Component

systemd

### Is your feature request related to a problem? Please describe

Right now, if one specifies LogsDirectory= in a service file, systemd creates it if missing (the good part), does something like `find $logsdir -type d -exec chmod ${LogsDirectoryMode} {} +` (ok), and than it seems to do always a `find $logsdir -not -type d -exec chmod 0600 {} +` as well as a `chown -R ${UnitUser}:${UnitGroup}`. This is a real nightmare and makes the LogsDirectory= totally useless - giving user's root permissions just to read the logs is simply brain damaged. Using ExecStartPre= to create the missing directories and apply the desired ownership and mode does not work either, because systemd dies with can't create the StandardOutput= (which is usually a file within the LogsDirectory): the directory does not exist. A chicken-and-egg problem.

### Describe the solution you'd like

To make LogsDirectory= (and optionally its friends like StateDirectory=, etc.) really usable, systemd should provide directives to control the ownership of such directories and stop modifying the ownership/mode of files and directories beneath it. If this is not an option, it should provide directives to control the file mode and ownership and possibly a directive to specify, for which files systemd is allowed to screw up ownership and mode (a simple list of filenames is probably sufficient, a regex might be useful, too).

### Describe alternatives you've considered

```
[Unit]
Description=Slurm node daemon
After=slurmctld.service munge.service network-online.target remote-fs.target
Wants=network-online.target
ConditionPathExists=/etc/slurm/slurm.conf

[Service]
Type=forking

StateDirectory=slurmd
LogsDirectory=slurm

Environment='SLURM_LOG_OWNER=slurm'
Environment='SLURM_LOG_GROUP=staff'
EnvironmentFile=-/etc/default/slurmd
ExecStartPre=+-/usr/bin/mkdir -v -m 0750 %L/slurm
ExecStartPre=+-/usr/bin/chown ${SLURM_LOG_OWNER}:${SLURM_LOG_GROUP} %L/slurm
ExecStart=/usr/sbin/slurmd -s $ARGS
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
LimitNOFILE=131072
LimitMEMLOCK=infinity
LimitSTACK=infinity
Delegate=yes
TasksMax=infinity
PIDFile=%t/slurmd.pid

StandardOutput=append:%L/slurm/slurmd-svc.log
StandardError=inherit

[Install]
WantedBy=multi-user.target
```

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by mrc0mmand** [comment]
There's already `LogsDirectoryMode=`, see https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectoryMode=

**Comment by jelmd** [comment]
@mrc0mmand: As already said above in the description: this is not sufficient at all.

**Comment by yuwata** [comment]
Why not to use User= and/or Group= ?

**Comment by jelmd** [comment]
Because the service needs to run as root and BTW a service should never run with the privileges of an "admin" group like staff or user like operator just to be able to read the logs ...

**Comment by poettering** [comment]
The assumption is that for each service their's own pair of associated user/group, and that's declared with User=/Group=/DynamicUser= and that gets the ownership for LogDirectory= and such.

"associated" means that by default systemd will change to this UID/GID also when running ExecStart=. But this is not required, you can use `ExecStart=!…`, i.e. if you prefix the cmdline, systemd will invoke binaries without doing setresuid(), and will let the binary itself do that.

**Comment by poettering** [comment]
btw, if you continue writing things like "brain damaged", then I'll block you here. Not appropriate. We do not accept behaviour like this in our community. https://systemd.io/CODE_OF_CONDUCT

**Comment by jelmd** [comment]
Haven't had the time to test it yet. The issue is IMHO not resolved/should not be closed.

Probably never used `!` because  "... unlike '+' the '!' character exclusively alters the effect of User=, Group= and SupplementaryGroups=, i.e. only the stanzas that affect user and group credentials." is a complete riddle.  Is anywhere documented or a list of stanzas "that affect user and group credentials" and how? Also it says that it alters the effect of ..., but not how. Any hints?

Furthermore I do not think, that '!' is a solution. E.g. a service needs to run as UserA:GroupB and directories need 0750 permission (obviously owned by UserA) with read/search permission for GroupC.

Last but not least the `chown -R` is toxic. There should be at least a directive to prevent the -R.

**Comment by jelmd** [comment]
In addition please remember, that there are even people, which recommend neither to daemonize nor to seteuid() nor to use any logging like syslog etc. - just to write to stderr/out because systemd takes care of it ...

**Comment by poettering** [comment]
> Haven't had the time to test it yet. The issue is IMHO not resolved/should not be closed.
> 
> Probably never used `!` because "... unlike '+' the '!' character exclusively alters the effect of User=, Group= and SupplementaryGroups=, i.e. only the stanzas that affect user and group credentials." is a complete riddle. Is anywhere documented or a list of stanzas "that affect user and group credentials" and how? 

They are listed right in the the quote you provided? User=, Group=, SupplementaryGroups=.

> Also it says that it alters the effect of ..., but not how. Any hints?

It's right in the text, it refers to the "+" prefix, for which we say: "In this mode privilege restrictions ... are not applied to the invoked command line".

It's that simple.

> Furthermore I do not think, that '!' is a solution. E.g. a service needs to run as UserA:GroupB and directories need 0750 permission (obviously owned by UserA) with read/search permission for GroupC.

That's not support and doesn#t work anyway, since it has no effect on new files created. On Linux, each process only has one pair of uid/gid that decides how files are created, and hence if you'd set the groups of the dir different from the group of the process run, then disparity in the contained file ownership will happen once the first file is created by the service. Hence we don't support it: pick *one* pair of uid/gid for process *and* resulting files and stick to it.

It appears to me what you are actually looking for here is ACLs: with those you can add additional users/groups to the files/dirs of your choice, *including* future files created below.
 
> Last but not least the `chown -R` is toxic. There should be at least a directive to prevent the -R.

It's necessary to avoid disparity of file ownership and service identity. The chowning is ACL-aware btw.

Anyway, I think your usecase for configuring a directory gid separately from a process gid is deeply flawed, and there's a much better alternative in file ACLs, hence I see no need to reopen this.

**Comment by poettering** [comment]
> In addition please remember, that there are even people, which recommend neither to daemonize nor to seteuid() nor to use any logging like syslog etc. - just to write to stderr/out because systemd takes care of it ...

I am one of those people, btw. But I also know that ACLs exist.
