### ISSUE TITLE
I was thinking the ipv4 dhcp/linklocal fallback feature made it into systemd v247, but it seems not.  I grabbed yocto-hardknott (latest yocto release), which uses systemd v247.6 and it's pretty clear the changes are not there.  From https://layers.openembedded.org/layerindex/recipe/5979/ it looks as if v247 is the most recent version available in any yocto release.  I am tempted to patch the 247.6 networkd-dhcp4.c to get this feature.  Any advice or suggestions?

### ISSUE THREAD

**Issue by nikhilsunilkumar** [systemd/systemd#28883]
I was thinking the ipv4 dhcp/linklocal fallback feature made it into systemd v247, but it seems not.  I grabbed yocto-hardknott (latest yocto release), which uses systemd v247.6 and it's pretty clear the changes are not there.  From https://layers.openembedded.org/layerindex/recipe/5979/ it looks as if v247 is the most recent version available in any yocto release.  I am tempted to patch the 247.6 networkd-dhcp4.c to get this feature.  Any advice or suggestions?

_Originally posted by @BillPlunkett in https://github.com/systemd/systemd/issues/17692#issuecomment-898648490_

**Comment by bluca** [comment]
For yocto-specific questions please use yocto-specific channels

**Comment by BillPlunkett** [comment]
Hardknott is no longer the latest release.  I'm using kirkstone, which has systemd 250.
