### ISSUE TITLE
Blanket "secure by default" or "recommended" setting

### ISSUE THREAD

**Issue by xi** [systemd/systemd#28895]
### Component

systemd

### Is your feature request related to a problem? Please describe

At the time of writing, `systemd-analyze security` lists 80 different security settings. This is great because it gives us a lot of control over security. But it is also annoying to have to copy the same ~80 settings to every new service file.

This is one of the reasons I like `DynamicUser`: It implied a lot of other useful settings, so my service files can be much shorter.

What is interesting is that the man pages have recommendations for reasonably secure options, but they are not the defaults. The defaults always seem to be the most insecure options. For example, `ProtectSystem` is "recommended for all long-running services", but completely deactivated by default.

`systemd-analyze security` reports that most services on my system are unsafe. I guess this is partially because systemd's security features are hard to use.

### Describe the solution you'd like

I can think of two different solutions:

- Add an option (e.g. `SecureByDefault`) that selects the most secure options as defaults
- Add an option (e.g. `FollowRecommndations`) that selects a curated list of recommended options as defaults

### Describe alternatives you've considered

The idea of allowlists and "security by default" is widely considered to be a good one. I guess the reason that chooses the least secure options by default is necessary for backwards compatibility. Still, I think an opt-in mechanism would be extremely useful for service authors.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by topimiettinen** [comment]
Related discussion about pure (or less pure) allowlist mode in #18441.

**Comment by xi** [comment]
Thanks for the hint, I hadn't found that when I looked. Everything I proposed is covered by https://github.com/systemd/systemd/pull/18441#issuecomment-841797830, so I can close this as a duplicate.
