### ISSUE TITLE
No Proxy ARP option for bridge interfaces

### ISSUE THREAD

**Issue by Kubuxu** [systemd/systemd#2889]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> v229
### Used distribution

> Arch Linux
### Description

I need to enable proxy ARP for on of my bridge interfaces. This is currently impossible using provided configuration options. Networkd provides proxy ARP option only for VXLAN. Also sysctl options are not applied or get overridden by networkd.

My solution for now is to have delayed service running following command:

```
sysctl net.ipv4.conf.br0.proxy_arp=1
```

But it isn't the best solution for that problem.
The solution would be allowing proxy APR option to be enabled from `.netdev` file.

**Comment by poettering** [comment]
@ssahani maybe something for you?

**Comment by ssahani** [comment]
yes will post a patch.
