### ISSUE TITLE
reboot/poweroff unnecessarily query dbus and systemd-logind

### ISSUE THREAD

**Issue by MichaIng** [systemd/systemd#28902]
### systemd version the issue has been seen with

254.1-2

### Used distribution

Debian 13/Trixie/Sid

### Linux kernel version used

6.4.11-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

When running `reboot` or `poweroff` on a system with `systemd` as init system, providing the two commands as symlinks to `systemctl`, I expect them to not require `dbus` or `systemd-logind`, as long as no shutdown/reboot timer is set explicitly.

### Unexpected behaviour you saw

Both commands try to connect to `dbus` and throw an error message if it is not running. With `dbus` running, further error messages reveal that the commands try to connect to `systemd-logind` via `dbus`.

This is expected when using the `shutdown` command with a timer, but not for direct reboots/poweroffs. The error message indicate an attempt and failure to send a wall message. Not sure if this is intended for immediate shutdowns/reboots, but the `wall` command works properly without `dbus` and `systemd-logind`.

Referring to this Debian bug report, while I do not thing that it is a Debian issue in particular: https://bugs.debian.org/1042015

### Steps to reproduce the problem

On any Debian or Ubuntu system with systemd >=252:
```sh
sudo systemctl mask --now systemd-logind
sudo systemctl mask --now dbus dbus.socket # optional
sudo reboot
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Failed to set wall message, ignoring: Unit 
dbus-org.freedesktop.login1.service failed to load properly, please 
adjust/correct and reload service manager: File exists
Call to Reboot failed: Unit dbus-org.freedesktop.login1.service failed 
to load properly, please adjust/correct and reload service manager: File 
exists
```

**Comment by poettering** [comment]
dbus is not an optional component and we communicate this clearly.

logind is responsible for enforce shutdown inhibitors, managing wall messages, timed shutdown, generating recognizable log messages, audit recording and more. Because of that we'll always try to talk to logind first. There's however an automatic fallback in place if we can't reach it. Are you saying this fallback doesn't work for you?

You can also pass "-f" to poweroff to bypass logind and directly go for the fallback. And you can pass "-ff" even, to immediately call the reboot() syscall and doesn't event talk to PID 1 anymore.

Unless the automatic fallback doesn't work I see nothing to fix here. The above behaviour is fully documented.

**Comment by MichaIng** [comment]
> There's however an automatic fallback in place if we can't reach it. Are you saying this fallback doesn't work for you?

The fallback works, just the error messages are confusing users.

Has any particular feature been added to those commands with v252 for them to now try to talk to logind and throw errors if they cannot? And is there probably a setting to enforce bypassing logind? I know the `-f` flag for `systemctl`, but knowing that the fallback works just nice, there is no reason to type that in for every poweroff/reboot 🙂. The `-f` flag for `poweroff` and `reboot` on the other hand is problematic, as it is translated into `systemctl -ff`, which also bypasses important steps like `sync`ing the write buffer to disk, AFAIK?

I highly appreciate the features added by systemd, but many of them, particularly what dbus and logind are used for, are often not needed on headless embedded systems, SBCs/small servers for home or small office use cases and similar. Such systems may have limited resources so that the ~10 MiB additional available RAM can be valuable. And I personally like to have a short list of running processes I can easily overlook and manage. We provide minimal OS images for such environments without dbus and logind pre-installed for those reasons, and I would like to keep it that way without users worrying and asking about those new error messages, if possible.

EDIT: I just see #28904. The error message was already indicating it, but `poweroff --no-wall`/`reboot --no-wall` does not mitigate the dbus/logind call. I am wondering whether a wall message makes sense at all if the poweroff/reboot is done immediately? For a scheduled shutdown, with multiple users working on the same system, it makes sense of course, but then dbus (and logind?) is required anyway.

**Comment by poettering** [comment]
> > There's however an automatic fallback in place if we can't reach it. Are you saying this fallback doesn't work for you?
> 
> The fallback works, just the error messages are confusing users.

Are they? Something is really broken if D-Bus isn#t around.

The "File exists" error is not what I see here in this case btw. I see instead:

"Could not activate remote peer: activation request failed: unit is invalid."

But I presume you are using legacy dbus-daemon rather than dbus-broker? These messages are returned by the broker, not by systemd, we just put them on screen in systemctl.

> Has any particular feature been added to those commands with v252 for them to now try to talk to logind and throw errors if they cannot? 

This has always been that way.

> And is there probably a setting to enforce bypassing logind?

No.

>  I know the `-f` flag for `systemctl`, but knowing that the fallback works just nice, there is no reason to type that in for every poweroff/reboot 🙂. The `-f` flag for `poweroff` and `reboot` on the other hand is problematic, as it is translated into `systemctl -ff`, which also bypasses important steps like `sync`ing the write buffer to disk, AFAIK?

Don't use plain `poweroff`, just use `systemctl poweroff` if you want proper control.

> I highly appreciate the features added by systemd, but many of them, particularly what dbus and logind are used for, are often not needed on headless embedded systems, SBCs/small servers for home or small office use cases and similar. 

Well, I vehemently disagree. Having an IPC system is kind the base for any sensible OS. If you try to avoid D-Bus you are on your own, really. Maybe don't bother with systemd at all then, we require that everywhere. Also things like the power key handling is also necessary on embedded systems, so logind is usually what you want everywhere. And it's tiny anyway.

That said, you can build systemd without logind support. Why don't you? (But D-Bus is strictly mandatory.)

> EDIT: I just see #28904. The error message was already indicating it, but `poweroff --no-wall`/`reboot --no-wall` does not mitigate the dbus/logind call. I am wondering whether a wall message makes sense at all if the poweroff/reboot is done immediately? For a scheduled shutdown, with multiple users working on the same system, it makes sense of course, but then dbus (and logind?) is required anyway.

As mentioned, it's not just the wall messages, it's inhibitors and stuff too.

Anyway, I don#t think there's anything actionable for us here. Things appear to work as they should, and I am not going to get lost in discussions on whether an IPC system really has to be mandatory for a sensible OS, to me the answer is so clear that any discussion around that is a waste of time.

**Comment by MichaIng** [comment]
Let me correct and clarify some things and explain our use case:
- We provide minimal Debian based OS images with a framework/set of scripts which allow to easily install and configure about 200 end user software titles (mostly server applications). We intentionally use Debian as basis to make use of the large APT repository and have a well known standard distribution with all of the common features admins expect available (not all pre-installed). We intentionally compile only a small number of end user software packages ourselves, but no base system packages like systemd, to assure Debian quality standards, and also because we are a very small team and wouldn't be able to provide a complete package repository. systemd is the default init system on most relevant Linux distributions, for a good reason, as it shines in its simple and rich service management. However, aside of as init system, service manager and timesyncd, we do not use other systemd features OOTB, but we do not limit admins to use whatever they want.
- We cannot and do not want to teach our ~a hundred thousand users which shutdown/reboot command they must use with which flags, so our aim is to have all of them working without error messages.
- Since several years we ship our images without `dbus` pre-installed and with logind masked. Whether logind or an IPC system are needed or not, is not an opinion, but a fact: If there are nether any processes using the IPC, nor the admin calls commands which require it, is not needed. If systemd internally at some point always tried to use it, then it never caused issues, neither does it now (only visually). There are two things which we know do not work without dbus and logind: Scheduled shutdowns/reboots and `timedatectl`. Both are however extremely rarely needed by our users, most don't even know that the features exist, and hence these are the two things we decided to sacrifice in favour of 10 MiB more RAM, two running processes less and a bunch of packages less installed. Such questions are always a balancing act, of course. For desktop installations and other software which do require dbus, logind, policykit or dependants, we install dbus and unmask logind on demand.
- As said, our users mostly use SBCs as small server systemd managed by a single admin only, so neither wall messages nor shutdown inhibitors, nor power button handling (most SBCs do not have any, and are usually only remotely managed, not physically), and `last`/`lastlog` logs are usually sufficient. For this rare cases where any of those features is needed, it can be easily enabled on demand.
- `systemctl -f poweroff` is also not a great option, since it skips shutting down all systemd units properly. Basically `-f` and `-ff` are bost emergency options, but definitely not if one just wants to skip a dbus/logind call for a wall message.
- `systemctl --no-wall poweroff` explicitly exists for this purpose, but despite this option, the dbus/logind call is done, same error messages as in OP. Is this a bug?
- Until including Debian Bullseye (247.3), there are no error messages, neither with logind masked, nor with dbus itself removed. So if the dbus call was always attempted, then it failed silently.

> The "File exists" error is not what I see here in this case btw. I see instead:
>
> "Could not activate remote peer: activation request failed: unit is invalid."

This happens here on a fresh Debian Trixie VM:
```console
root@VM-Trixie:~# systemctl --version
systemd 254 (254.1-2)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
root@VM-Trixie:~# systemctl mask --now systemd-logind
Created symlink /etc/systemd/system/systemd-logind.service → /dev/null.
root@VM-Trixie:~# systemctl mask --now dbus dbus.socket
Created symlink /etc/systemd/system/dbus.service → /dev/null.
Created symlink /etc/systemd/system/dbus.socket → /dev/null.
root@VM-Trixie:~# systemctl reboot
Failed to connect to bus: Connection refused
# after reboot
root@VM-Trixie:~# systemctl unmask dbus dbus.socket; systemctl start dbus dbus.socket
Removed "/etc/systemd/system/dbus.service".
Removed "/etc/systemd/system/dbus.socket".
root@VM-Trixie:~# systemctl reboot
Failed to set wall message, ignoring: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists
Call to Reboot failed: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists
# after reboot
root@VM-Trixie:~# systemctl --no-wall reboot
Failed to set wall message, ignoring: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists
Call to Reboot failed: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists
root@VM-Trixie:~# systemctl unmask systemd-logind; systemctl start systemd-logind
Removed "/etc/systemd/system/systemd-logind.service".
root@VM-Trixie:~# systemctl reboot
```
Also with logind active, there is no wall message, neither on the SSH console, nor on TTY1, as I actually expected anyway from an immediate poweroff/reboot. So the logind connection seems to be done even if no wall message is sent and even that one explicitly asks via `--no-wall` to not send a wall message.

> But I presume you are using legacy dbus-daemon rather than dbus-broker? These messages are returned by the broker, not by systemd, we just put them on screen in systemctl.

Indeed, Debian seem to not provide another solution than the `dbus-daemon`: https://packages.debian.org/source/sid/dbus

**Comment by arvidjaar** [comment]
> * `systemctl --no-wall poweroff` explicitly exists for this purpose, but despite this option, the dbus/logind call is done, same error messages as in OP. Is this a bug?

No. `systemctl poweroff` will **always** try logind first. Also, `--no-wall` is really an option for logind, not for systemctl. Documentation could be clearer on this point.

If you do not want logind, explicitly use `systemctl start poweroff.target`. Which is what systemctl does as fallback.

**Comment by mbiebl** [comment]
> > But I presume you are using legacy dbus-daemon rather than dbus-broker? These messages are returned by the broker, not by systemd, we just put them on screen in systemctl.
> 
> Indeed, Debian seem to not provide another solution than the `dbus-daemon`: https://packages.debian.org/source/sid/dbus

While dbus-daemon is indeed the default, you can install dbus-broker as a drop-in replacement:
https://tracker.debian.org/pkg/dbus-broker

**Comment by MichaIng** [comment]
> No. `systemctl poweroff` will always try logind first. Also, `--no-wall` is really an option for logind, not for systemctl. Documentation could be clearer on this point.

Since `--no-wall` is part of the man pages of `systemctl` as well as all the `reboot`/`poweroff`/... commands, do you mean that it is handled by logind, i.e. the commands always connect via dbus to logind, pass the argument and logind then does not send an actual wall message? More efficient would be of course to skip the logind connection in the first place.

However, if I interpret the error messages correct, then it is indeed two dedicated logind calls, one for the wall message and another one "Call to Reboot"/"Call to PowerOff", likely for the shutdown inhibitors?

> If you do not want logind, explicitly use `systemctl start poweroff.target`. Which is what systemctl does as fallback.

Thanks, that sounds like good alternative, e.g. to create at least `poweroff`/`reboot` aliases from. However, if `dbus` and `logind` keep getting more integrated as mandatory parts, i.e. more commands start using them (and failing loudly) without a way to configure it via config file, then we may give up on the approach and start shipping our images with them installed/enabled OOTB.

> While dbus-daemon is indeed the default, you can install dbus-broker as a drop-in replacement:
https://tracker.debian.org/pkg/dbus-broker

Ah thanks, so it uses a different source package. As it uses features from recent Linux versions, which minimum Linux does it require? There are still some SBCs which only run properly with older vendor kernel sources.

**Comment by arvidjaar** [comment]
> the commands always connect via dbus to logind, pass the argument and logind then does not send an actual wall message?

Correct,

> it is indeed two dedicated logind calls

Correct. The result of the first one seems to be simply ignored by the systemctl.
