### ISSUE TITLE
during boot systemd-networkd-wait-online exit with time-out error 

### ISSUE THREAD

**Issue by phil524** [systemd/systemd#28927]
### systemd version the issue has been seen with

systemd-253.8-1.1.x86_64

### Used distribution

opensuse tumbleweed

### Linux kernel version used

6.4.11-1-default

### CPU architectures issue was seen on

x86_64

### Component

networkctl

### Expected behaviour you didn't see

I have a server with 3 network hardware devices. I use systemd-networkd to manage these devices
device 1 (eno1) is enslaved in bridge br0
device 2 (en02) is used for 4 vlans (vlan1, vlan2, vlan3 and vlan4)
device 3 (eno3) is used for a ppp connection to internet (ppp0)

hpprol2:~ # networkctl list
IDX LINK   TYPE     OPERATIONAL SETUP      
  1 lo     loopback carrier     unmanaged
  2 eno1   ether    enslaved    configured 
  3 eno2   ether    carrier     configured 
  4 eno3   ether    carrier     configured 
  5 eno4   ether    off         unmanaged
  6 br0    bridge   routable    configuring
  7 vlan1  vlan     routable    configured 
  8 vlan2  vlan     routable    configured 
  9 vlan3  vlan     routable    configured 
 10 vlan4  vlan     routable    configured 
 11 ppp0   ppp      routable    unmanaged
 12 virbr0 bridge   no-carrier  unmanaged

12 links listed.

since  5 months I see a long delay during boot which end with a timeout error in systemd-networkd-wait-online.
The system works and the network is up and availlable

### Unexpected behaviour you saw

hpprol2:~ # systemd-analyze blame
2min 304ms systemd-networkd-wait-online.service
   27.093s clamd.service
   11.103s webmin.service
    9.632s [ppp@proximus.service](mailto:ppp@proximus.service)
    8.615s dev-ttyS13.device
    8.615s sys-devices-platform-serial8250-tty-ttyS13.device

hpprol2:~/Script # journalctl -xeu systemd-networkd-wait-online
Aug 22 11:35:27 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:27 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:27 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:27 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is being processed by networkd: setup state is configuring.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:28 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: Found link ppp0(11)
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to determine whether the link is required for online or not, assuming required: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get required operational state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get operational state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get required address family, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get IPv4 address state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get IPv6 address state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to get setup state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: ppp0: Failed to update link state, ignoring: No such file or directory
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:40 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:42 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:42 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: vlan3: link is configured by networkd and online.
Aug 22 11:35:43 hpprol2 systemd-networkd-wait-online[1350]: eno2: Operational state 'carrier' is not in range ['degraded':'routable']
Aug 22 11:37:24 hpprol2 systemd-networkd-wait-online[1350]: Timeout occurred while waiting for network connectivity.
Aug 22 11:37:24 hpprol2 systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit systemd-networkd-wait-online.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 22 11:37:24 hpprol2 systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit systemd-networkd-wait-online.service has entered the 'failed' state with result 'exit-code'.
Aug 22 11:37:24 hpprol2 systemd[1]: Failed to start Wait for Network to be Configured.
░░ Subject: A start job for unit systemd-networkd-wait-online.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit systemd-networkd-wait-online.service has finished with a failure.
░░ 
░░ The job identifier is 284 and the job result is failed.
lines 156-224/224 (END)

but if I look in journalctl for systemd-networkd all seems working: the devices are started and the link goes up.

After end of boot, the network is up and all network devices have a correct IP address. Network is up and works

output 
hpprol2:~/Script # journalctl -b0  -u systemd-networkd
Aug 22 11:35:23 hpprol2 systemd[1]: Starting Network Configuration...
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: lo: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: lo: Gained carrier
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: br0: netdev ready
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: Enumeration completed
Aug 22 11:35:24 hpprol2 systemd[1]: Started Network Configuration.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno1: Configuring with /etc/systemd/network/04-eno1br0.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno2: Configuring with /etc/systemd/network/20-eno2vlan.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno3: Configuring with /etc/systemd/network/30-eno3.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: br0: Configuring with /etc/systemd/network/03-br0.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno2: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno3: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: br0: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan2: netdev ready
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan1: netdev ready
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan4: netdev ready
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan3: netdev ready
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: eno1: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan2: Configuring with /etc/systemd/network/22-vlan2.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan1: Configuring with /etc/systemd/network/21-vlan1.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan4: Configuring with /etc/systemd/network/24-vlan4.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan3: Configuring with /etc/systemd/network/23-vlan3.network.
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan2: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan1: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan4: Link UP
Aug 22 11:35:24 hpprol2 systemd-networkd[1242]: vlan3: Link UP
Aug 22 11:35:27 hpprol2 systemd-networkd[1242]: eno2: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: vlan1: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: vlan2: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: vlan3: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: vlan4: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: eno3: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: eno1: Gained carrier
Aug 22 11:35:28 hpprol2 systemd-networkd[1242]: br0: Gained carrier
Aug 22 11:35:43 hpprol2 systemd-networkd[1242]: ppp0: Link UP
Aug 22 11:35:43 hpprol2 systemd-networkd[1242]: ppp0: Gained carrier

### Steps to reproduce the problem

use systemd-networkd to manage the network I wrote the netdev and network files for br0, vlan1-> vlan4, eno1, eno2 and eno3

See attached Document
[systemd-networkd files.odt](https://github.com/systemd/systemd/files/12409328/systemd-networkd.files.odt)

**Comment by yuwata** [comment]
> See attached Document
> [systemd-networkd files.odt](https://github.com/systemd/systemd/files/12409328/systemd-networkd.files.odt)

Why odt... Please provide them in plain text, or at least by a tar ball.

> 6 br0 bridge routable configuring

What blocks 'br0' from entering configured state ?

Please provide debugging logs of systemd-networkd, which can be generated by creating the following drop-in config by using `sudo systemctl edit systemd-networkd.service`:
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
then, restart networkd or reboot system and provide the journal shown by `journalctl --no-hostname -u systemd-networkd.service`.

**Comment by phil524** [comment]
Hello,
br0 is a bridge to be used by a VM. This VM is not started at boot.

I attach the  output of  journalctl -b0 --no-hostname -u systemd-networkd.service with loglevel=debug, and a tar.gz file  with the netdev and network files
[jrnctl.txt](https://github.com/systemd/systemd/files/12409950/jrnctl.txt)
[netdev_network.tar.gz](https://github.com/systemd/systemd/files/12409955/netdev_network.tar.gz)

**Comment by phil524** [comment]
I removed the gateway in  03-br0.network and rebooted but this change doesn't solve the problem.
I attach the journalctl output
[jrnctl2.txt](https://github.com/systemd/systemd/files/12412223/jrnctl2.txt)

Here the status op ppp@service which change the default route and start on eno3
hpprol2:/etc # systemctl status ppp@proximus.service
● ppp@proximus.service - PPP link to proximus
     Loaded: loaded (/usr/lib/systemd/system/ppp@.service; enabled; preset: disabled)
     Active: active (running) since Tue 2023-08-22 20:46:42 CEST; 42min ago
       Docs: man:pppd(8)
    Process: 1354 ExecStart=/usr/sbin/pppd call proximus linkname proximus updetach nolog (code=exited, status=0/SUCCESS)
   Main PID: 1711 (pppd)
      Tasks: 1 (limit: 4915)
        CPU: 635ms
     CGroup: /system.slice/system-ppp.slice/ppp@proximus.service
             └─1711 /usr/sbin/pppd call proximus linkname proximus updetach nolog

Aug 22 20:46:41 hpprol2 pppd[1354]: CHAP authentication succeeded
Aug 22 20:46:41 hpprol2 pppd[1354]: peer from calling number 20:E0:9C:0A:CD:47 authorized
Aug 22 20:46:42 hpprol2 pppd[1354]: Script /etc/ppp/ip-pre-up finished (pid 1706), status = 0x0
Aug 22 20:46:42 hpprol2 pppd[1354]: replacing old default route to vlan1 [192.168.1.1]
Aug 22 20:46:42 hpprol2 pppd[1354]: local  IP address 91.177.41.68
Aug 22 20:46:42 hpprol2 pppd[1354]: remote IP address 10.XXX.XXX.XXX
Aug 22 20:46:42 hpprol2 pppd[1354]: primary   DNS address 195.238.2.21
Aug 22 20:46:42 hpprol2 pppd[1354]: secondary DNS address 195.238.2.22
Aug 22 20:46:42 hpprol2 systemd[1]: Started PPP link to proximus.
Aug 22 20:46:42 hpprol2 pppd[1711]: Script /etc/ppp/ip-up finished (pid 1712), status = 0x0
hpprol2:/etc # 

for info I attach also the network topology
[PCE23_topologyGR.txt](https://github.com/systemd/systemd/files/12412290/PCE23_topologyGR.txt)

Regards
Philippe

**Comment by yuwata** [comment]
> 3 eno2 ether carrier configured
> 4 eno3 ether carrier configured

LinkLocalAddressing= is disabled on these interfaces, hence they do not enter degraded state or routable state.
Please add
```
[Link]
RequiredForOnline=carrier
```
or
```
[Link]
RequiredForOnline=no
```
to .network files for eno2 and eno3.

**Comment by phil524** [comment]
Many thanks,

I updated the network files with
[Link]
RequiredForOnline=no
and this solved the problem
