### ISSUE TITLE
udevd produce same ID_NET_NAME_SLOT for different NIC, so break rename

### ISSUE THREAD

**Issue by clan** [systemd/systemd#28929]
### systemd version the issue has been seen with

253

### Used distribution

Gentoo

### Linux kernel version used

6.1.41-gentoo

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

on a Dell PowerEdge R740xd2, with 6 nic card, the NIC names should be predictable, i.e., there should be no eth? exist, otherwise the nic name will be unpredictable.

### Unexpected behaviour you saw

ip link show (unrelated info removed) as following:

2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    altname enp4s0f0
    altname ens6f0
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    altname enp4s0f1
    altname ens6f1
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    altname enp177s0f0
5: ens3f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    altname enp177s0f1
6: ens3f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    altname enp178s0f0
7: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    altname enp178s0f1

vimdiff <(udevadm  test-builtin net_id /sys/class/net/eth0 2>&1) <(udevadm  test-builtin net_id /sys/class/net/ens3f0 2>&1)
shows eth0 & ens3f0 have same ID_NET_NAME_SLOT, 
since Slot identifier is same: domain=0 slot=3 func=0 phys_port= dev_port=0 → s3f0
so even ID_NET_NAME_PATH is different (show in altname), but since ID_NET_NAME_SLOT has higher priority, so only one eth* be renamed.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# lspci |grep Ethernet
04:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
04:00.1 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5720 Gigabit Ethernet PCIe
b1:00.0 Ethernet controller: Intel Corporation 82571EB/82571GB Gigabit Ethernet Controller (Copper) (rev 06)
b1:00.1 Ethernet controller: Intel Corporation 82571EB/82571GB Gigabit Ethernet Controller (Copper) (rev 06)
b2:00.0 Ethernet controller: Intel Corporation 82571EB/82571GB Gigabit Ethernet Controller (Copper) (rev 06)
b2:00.1 Ethernet controller: Intel Corporation 82571EB/82571GB Gigabit Ethernet Controller (Copper) (rev 06)

# udevadm  test-builtin net_id /sys/class/net/eth0
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          253
file size:        11993393 bytes
header size             80 bytes
strings            2530257 bytes
nodes              9463056 bytes
Loading kernel module index.
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Using default interface naming scheme 'v253'.
Parsed configuration file "/lib/systemd/network/99-default.link"
Created link configuration context.
ID_NET_NAMING_SCHEME=v253
ID_NET_NAME_MAC=enxa0369fcb198d
eth0: MAC address identifier: hw_addr=a0:36:9f:cb:19:8d → xa0369fcb198d
ID_OUI_FROM_DATABASE=Intel Corporate
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/of_node".
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/physfn".
eth0: Parsing slot information from PCI device sysname "0000:b1:00.0": success
eth0: dev_port=0
eth0: PCI path identifier: domain=0 bus=177 slot=0 func=0 phys_port= dev_port=0 → p177s0f0
0000:ae:00.0: Device is a PCI bridge.
eth0: Slot identifier: domain=0 slot=3 func=0 phys_port= dev_port=0 → s3f0
ID_NET_NAME_PATH=enp177s0f0
ID_NET_NAME_SLOT=ens3f0
Unload kernel module index.
Unloaded link configuration context.

# udevadm  test-builtin net_id /sys/class/net/ens3f0
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          253
file size:        11993393 bytes
header size             80 bytes
strings            2530257 bytes
nodes              9463056 bytes
Loading kernel module index.
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Using default interface naming scheme 'v253'.
Parsed configuration file "/lib/systemd/network/99-default.link"
Created link configuration context.
ID_NET_NAMING_SCHEME=v253
ID_NET_NAME_MAC=enxa0369fcb198f
ens3f0: MAC address identifier: hw_addr=a0:36:9f:cb:19:8f → xa0369fcb198f
ID_OUI_FROM_DATABASE=Intel Corporate
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.0/of_node".
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.0/physfn".
ens3f0: Parsing slot information from PCI device sysname "0000:b2:00.0": success
ens3f0: dev_port=0
ens3f0: PCI path identifier: domain=0 bus=178 slot=0 func=0 phys_port= dev_port=0 → p178s0f0
0000:ae:00.0: Device is a PCI bridge.
ens3f0: Slot identifier: domain=0 slot=3 func=0 phys_port= dev_port=0 → s3f0
ID_NET_NAME_PATH=enp178s0f0
ID_NET_NAME_SLOT=ens3f0
Unload kernel module index.
Unloaded link configuration context.
```

**Comment by yuwata** [comment]
This is caused by 66425daf2c68793adf24a48a26d58add8662e83f. cc @msekletar

**Comment by yuwata** [comment]
Workaround for the issue is creating /etc/systemd/network/10-workaround.link something like the following:
```
[Match]
OriginalName=*

[Link]
NamePolicy=keep kernel database onboard path
AlternativeNamesPolicy=database onboard path
MACAddressPolicy=persistent
```

**Comment by msekletar** [comment]
@clan Do you get expected interface names if you boot with "net.naming-scheme=v250" on kernel cmdline?

**Comment by clan** [comment]
> @clan Do you get expected interface names if you boot with "net.naming-scheme=v250" on kernel cmdline?

it works as expected. So what's the problem? The default naming schems is not v250?

**Comment by yuwata** [comment]
> > @clan Do you get expected interface names if you boot with "net.naming-scheme=v250" on kernel cmdline?
> 
> it works as expected. So what's the problem? The default naming schems is not v250?

By default, the latest naming scheme is used, so in your case, v253 is used. You can find the naming scheme currently used in the output of `udevadm test-builtin`:
> Using default interface naming scheme 'v253'.

**Comment by clan** [comment]
> Could you provide the result of `udevadm info --attribute-walk /sys/class/net/IFNAME` for the intel NICs ?

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/net/enp177s0f0':
    KERNEL=="enp177s0f0"
    SUBSYSTEM=="net"
    DRIVER==""
    ATTR{addr_assign_type}=="0"
    ATTR{addr_len}=="6"
    ATTR{address}=="a0:36:9f:cb:19:8d"
    ATTR{broadcast}=="ff:ff:ff:ff:ff:ff"
    ATTR{carrier}=="1"
    ATTR{carrier_changes}=="2"
    ATTR{carrier_down_count}=="1"
    ATTR{carrier_up_count}=="1"
    ATTR{dev_id}=="0x0"
    ATTR{dev_port}=="0"
    ATTR{dormant}=="0"
    ATTR{duplex}=="full"
    ATTR{flags}=="0x1003"
    ATTR{gro_flush_timeout}=="0"
    ATTR{ifalias}==""
    ATTR{ifindex}=="4"
    ATTR{iflink}=="4"
    ATTR{link_mode}=="0"
    ATTR{mtu}=="1500"
    ATTR{name_assign_type}=="4"
    ATTR{napi_defer_hard_irqs}=="0"
    ATTR{netdev_group}=="0"
    ATTR{operstate}=="up"
    ATTR{power/control}=="auto"
    ATTR{power/runtime_active_time}=="0"
    ATTR{power/runtime_status}=="unsupported"
    ATTR{power/runtime_suspended_time}=="0"
    ATTR{proto_down}=="0"
    ATTR{queues/rx-0/rps_cpus}=="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000"
    ATTR{queues/rx-0/rps_flow_cnt}=="0"
    ATTR{queues/tx-0/byte_queue_limits/hold_time}=="1000"
    ATTR{queues/tx-0/byte_queue_limits/inflight}=="0"
    ATTR{queues/tx-0/byte_queue_limits/limit}=="250"
    ATTR{queues/tx-0/byte_queue_limits/limit_max}=="1879048192"
    ATTR{queues/tx-0/byte_queue_limits/limit_min}=="0"
    ATTR{queues/tx-0/tx_maxrate}=="0"
    ATTR{queues/tx-0/tx_timeout}=="0"
    ATTR{queues/tx-0/xps_rxqs}=="0"
    ATTR{speed}=="1000"
    ATTR{statistics/collisions}=="0"
    ATTR{statistics/multicast}=="591"
    ATTR{statistics/rx_bytes}=="200880"
    ATTR{statistics/rx_compressed}=="0"
    ATTR{statistics/rx_crc_errors}=="0"
    ATTR{statistics/rx_dropped}=="0"
    ATTR{statistics/rx_errors}=="0"
    ATTR{statistics/rx_fifo_errors}=="0"
    ATTR{statistics/rx_frame_errors}=="0"
    ATTR{statistics/rx_length_errors}=="0"
    ATTR{statistics/rx_missed_errors}=="0"
    ATTR{statistics/rx_nohandler}=="0"
    ATTR{statistics/rx_over_errors}=="0"
    ATTR{statistics/rx_packets}=="2439"
    ATTR{statistics/tx_aborted_errors}=="0"
    ATTR{statistics/tx_bytes}=="9955"
    ATTR{statistics/tx_carrier_errors}=="0"
    ATTR{statistics/tx_compressed}=="0"
    ATTR{statistics/tx_dropped}=="0"
    ATTR{statistics/tx_errors}=="0"
    ATTR{statistics/tx_fifo_errors}=="0"
    ATTR{statistics/tx_heartbeat_errors}=="0"
    ATTR{statistics/tx_packets}=="52"
    ATTR{statistics/tx_window_errors}=="0"
    ATTR{testing}=="0"
    ATTR{threaded}=="0"
    ATTR{tx_queue_len}=="1000"
    ATTR{type}=="1"

  looking at parent device '/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0':
    KERNELS=="0000:b1:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="e1000e"
    ATTRS{ari_enabled}=="0"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x020000"
    ATTRS{consistent_dma_mask_bits}=="64"
    ATTRS{current_link_speed}=="2.5 GT/s PCIe"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x10bc"
    ATTRS{devspec}==""
    ATTRS{dma_mask_bits}=="64"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="55"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000fff"
    ATTRS{max_link_speed}=="2.5 GT/s PCIe"
    ATTRS{max_link_width}=="4"
    ATTRS{msi_bus}=="1"
    ATTRS{msi_irqs/55}=="msi"
    ATTRS{numa_node}=="-1"
    ATTRS{power/control}=="on"
    ATTRS{power/runtime_active_time}=="1118013"
    ATTRS{power/runtime_status}=="active"
    ATTRS{power/runtime_suspended_time}=="0"
    ATTRS{power/wakeup}=="enabled"
    ATTRS{power/wakeup_abort_count}=="0"
    ATTRS{power/wakeup_active}=="0"
    ATTRS{power/wakeup_active_count}=="0"
    ATTRS{power/wakeup_count}=="0"
    ATTRS{power/wakeup_expire_count}=="0"
    ATTRS{power/wakeup_last_time_ms}=="0"
    ATTRS{power/wakeup_max_time_ms}=="0"
    ATTRS{power/wakeup_total_time_ms}=="0"
    ATTRS{power_state}=="D0"
    ATTRS{remove}=="(not readable)"
    ATTRS{rescan}=="(not readable)"
    ATTRS{reset}=="(not readable)"
    ATTRS{reset_method}=="pm bus"
    ATTRS{revision}=="0x06"
    ATTRS{subsystem_device}=="0x10bc"
    ATTRS{subsystem_vendor}=="0x8086"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0':
    KERNELS=="0000:b0:02.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="pcieport"
    ATTRS{ari_enabled}=="0"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{current_link_speed}=="2.5 GT/s PCIe"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x8018"
    ATTRS{devspec}==""
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="0"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000fff"
    ATTRS{max_link_speed}=="2.5 GT/s PCIe"
    ATTRS{max_link_width}=="4"
    ATTRS{msi_bus}=="1"
    ATTRS{numa_node}=="-1"
    ATTRS{power/autosuspend_delay_ms}=="100"
    ATTRS{power/control}=="auto"
    ATTRS{power/runtime_active_time}=="1118017"
    ATTRS{power/runtime_status}=="active"
    ATTRS{power/runtime_suspended_time}=="0"
    ATTRS{power/wakeup}=="disabled"
    ATTRS{power/wakeup_abort_count}==""
    ATTRS{power/wakeup_active}==""
    ATTRS{power/wakeup_active_count}==""
    ATTRS{power/wakeup_count}==""
    ATTRS{power/wakeup_expire_count}==""
    ATTRS{power/wakeup_last_time_ms}==""
    ATTRS{power/wakeup_max_time_ms}==""
    ATTRS{power/wakeup_total_time_ms}==""
    ATTRS{power_state}=="D0"
    ATTRS{remove}=="(not readable)"
    ATTRS{rescan}=="(not readable)"
    ATTRS{reset}=="(not readable)"
    ATTRS{reset_method}=="bus"
    ATTRS{revision}=="0x0e"
    ATTRS{secondary_bus_number}=="177"
    ATTRS{subordinate_bus_number}=="177"
    ATTRS{subsystem_device}=="0x0000"
    ATTRS{subsystem_vendor}=="0x0000"
    ATTRS{vendor}=="0x111d"

  looking at parent device '/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0':
    KERNELS=="0000:af:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="pcieport"
    ATTRS{ari_enabled}=="0"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{current_link_speed}=="2.5 GT/s PCIe"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x8018"
    ATTRS{devspec}==""
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="0"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000fff"
    ATTRS{max_link_speed}=="2.5 GT/s PCIe"
    ATTRS{max_link_width}=="4"
    ATTRS{msi_bus}=="1"
    ATTRS{numa_node}=="-1"
    ATTRS{power/autosuspend_delay_ms}=="100"
    ATTRS{power/control}=="auto"
    ATTRS{power/runtime_active_time}=="1118018"
    ATTRS{power/runtime_status}=="active"
    ATTRS{power/runtime_suspended_time}=="0"
    ATTRS{power/wakeup}=="disabled"
    ATTRS{power/wakeup_abort_count}==""
    ATTRS{power/wakeup_active}==""
    ATTRS{power/wakeup_active_count}==""
    ATTRS{power/wakeup_count}==""
    ATTRS{power/wakeup_expire_count}==""
    ATTRS{power/wakeup_last_time_ms}==""
    ATTRS{power/wakeup_max_time_ms}==""
    ATTRS{power/wakeup_total_time_ms}==""
    ATTRS{power_state}=="D0"
    ATTRS{remove}=="(not readable)"
    ATTRS{rescan}=="(not readable)"
    ATTRS{reset}=="(not readable)"
    ATTRS{reset_method}=="bus"
    ATTRS{revision}=="0x0e"
    ATTRS{secondary_bus_number}=="176"
    ATTRS{subordinate_bus_number}=="178"
    ATTRS{subsystem_device}=="0x0000"
    ATTRS{subsystem_vendor}=="0x0000"
    ATTRS{vendor}=="0x111d"

  looking at parent device '/devices/pci0000:ae/0000:ae:00.0':
    KERNELS=="0000:ae:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="pcieport"
    ATTRS{acpi_index}=="18"
    ATTRS{aer_rootport_total_err_cor}=="0"
    ATTRS{aer_rootport_total_err_fatal}=="0"
    ATTRS{aer_rootport_total_err_nonfatal}=="0"
    ATTRS{ari_enabled}=="0"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{current_link_speed}=="2.5 GT/s PCIe"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x2030"
    ATTRS{devspec}==""
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="30"
    ATTRS{label}=="SLOT 3"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000fff"
    ATTRS{max_link_speed}=="8.0 GT/s PCIe"
    ATTRS{max_link_width}=="16"
    ATTRS{msi_bus}=="1"
    ATTRS{msi_irqs/30}=="msi"
    ATTRS{numa_node}=="-1"
    ATTRS{power/autosuspend_delay_ms}=="100"
    ATTRS{power/control}=="auto"
    ATTRS{power/runtime_active_time}=="1118025"
    ATTRS{power/runtime_status}=="active"
    ATTRS{power/runtime_suspended_time}=="0"
    ATTRS{power/wakeup}=="enabled"
    ATTRS{power/wakeup_abort_count}=="0"
    ATTRS{power/wakeup_active}=="0"
    ATTRS{power/wakeup_active_count}=="0"
    ATTRS{power/wakeup_count}=="0"
    ATTRS{power/wakeup_expire_count}=="0"
    ATTRS{power/wakeup_last_time_ms}=="0"
    ATTRS{power/wakeup_max_time_ms}=="0"
    ATTRS{power/wakeup_total_time_ms}=="0"
    ATTRS{power_state}=="D0"
    ATTRS{remove}=="(not readable)"
    ATTRS{rescan}=="(not readable)"
    ATTRS{revision}=="0x07"
    ATTRS{secondary_bus_number}=="175"
    ATTRS{subordinate_bus_number}=="178"
    ATTRS{subsystem_device}=="0x0000"
    ATTRS{subsystem_vendor}=="0x8086"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:ae':
    KERNELS=="pci0000:ae"
    SUBSYSTEMS==""
    DRIVERS==""
    ATTRS{power/control}=="auto"
    ATTRS{power/runtime_active_time}=="0"
    ATTRS{power/runtime_status}=="unsupported"
    ATTRS{power/runtime_suspended_time}=="0"
    ATTRS{waiting_for_supplier}=="0"

**Comment by clan** [comment]
> By default, the latest naming scheme is used, so in your case, v253 is used. You can find the naming scheme currently used in the output of `udevadm test-builtin`:

i see. so this is still a bug to be fixed.

**Comment by clan** [comment]
# xxd -p /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/config
8680bc10070410000600000210008000000016e1000014e121d000000000
00000000000000000000000000008680bc100000feffc800000000000000
ff0200000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000001d022c80020002105e0
81007800e0fe000000000000000010000100c10c000034281a0041640302
4000411000000000000000000000000001000114000010000000110011f0
060000000000c111000014000000010000040f0000ae000002b100000000
0000000000000000000000000000000000000000030001008c19cbffff9f
36a000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
... (0000 removed)
# cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/modalias
pci:v00008086d000010BCsv00008086sd000010BCbc02sc00i00
# cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/modalias
pci:v0000111Dd00008018sv00000000sd00000000bc06sc04i00
# cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/modalias
pci:v0000111Dd00008018sv00000000sd00000000bc06sc04i00
# cat /sys/devices/pci0000:ae/0000:ae:00.0/modalias
pci:v00008086d00002030sv00008086sd00000000bc06sc04i00

**Comment by champtar** [comment]
Hello @clan

If you still have access to this server, can you run:
```
cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/firmware_node/sun
cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/firmware_node/sun
cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/firmware_node/sun
cat /sys/devices/pci0000:ae/0000:ae:00.0/firmware_node/sun
```

**Comment by clan** [comment]
In my case, directory /sys/devices/pci0000:ae/0000:ae:00.0 not exist

> ls /sys/devices/pci0000\:ae/
> 0000:ae:05.0  0000:ae:05.4  0000:ae:09.0  0000:ae:0a.1  0000:ae:0a.3  0000:ae:0a.5  0000:ae:0a.7  0000:ae:0b.1  0000:ae:0b.3  0000:ae:0c.1  0000:ae:0c.3  0000:ae:0c.5  0000:ae:0c.7  0000:ae:0d.1  0000:ae:0d.3   pci_bus  uevent
> 0000:ae:05.2  0000:ae:08.0  0000:ae:0a.0  0000:ae:0a.2  0000:ae:0a.4  0000:ae:0a.6  0000:ae:0b.0  0000:ae:0b.2  0000:ae:0c.0  0000:ae:0c.2  0000:ae:0c.4  0000:ae:0c.6  0000:ae:0d.0  0000:ae:0d.2  firmware_node  power    waiting_for_supplier

**Comment by clan** [comment]
only one file exist, see following:

> # cat /sys/devices/pci0000\:ae/0000\:ae\:00.0/firmware_node/sun
> 3

**Comment by champtar** [comment]
Maybe the path have changed a bit since when you reported the issue
```
ls -l /sys/class/net/
```

**Comment by clan** [comment]
>  \# ls -l /sys/class/net/
> total 0
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 docker0 -> ../../devices/virtual/net/docker0
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 eno1 -> ../../devices/pci0000:00/0000:00:1c.5/0000:04:00.0/net/eno1
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 eno2 -> ../../devices/pci0000:00/0000:00:1c.5/0000:04:00.1/net/eno2
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 enp177s0f0 -> ../../devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/net/enp177s0f0
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 enp177s0f1 -> ../../devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.1/net/enp177s0f1
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 enp178s0f0 -> ../../devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.0/net/enp178s0f0
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 enp178s0f1 -> ../../devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.1/net/enp178s0f1
> lrwxrwxrwx 1 root root 0 Jul  8 13:17 lo -> ../../devices/virtual/net/lo
>

**Comment by champtar** [comment]
@clan 2 more checks (likely will not exists)
```
cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/firmware_node/sun
cat /sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.0/firmware_node/sun
```

**Comment by clan** [comment]
yes

> cat: '/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:02.0/0000:b1:00.0/firmware_node/sun': No such file or directory
> cat: '/sys/devices/pci0000:ae/0000:ae:00.0/0000:af:00.0/0000:b0:04.0/0000:b2:00.0/firmware_node/sun': No such file or directory
>
