### ISSUE TITLE
timesyncd: talks only to one NTP server at a time

### ISSUE THREAD

**Issue by hggh** [systemd/systemd#2893]
### Submission type
- [ ] Bug report
- [X ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> ubuntu 1604

timesyncd is a good replacement for ntpd, you can configure more timeservers inside timesyncd.conf.

But systemd-timesyncd talks only to one NTP server at a time, so if that particular NTP Server responds with a incorrect time timesyncd will have a correct time. That's why the old ntpd talks to more ntp servers. Mostly three ntp server are the best option.

It would be great if timesyncd talks also to all configured ntp servers.

**Comment by keszybz** [comment]
systemd-ntpd by implements SNTP, and only talk to one server. I don't have an opinion whether this should ever change, but it's but design.

**Comment by poettering** [comment]
Yeah, systemd-timesyncd implements SNTP, not NTP, hence multi-server support is out of focus. If you want a full NTP implementation, please use ntpd or chrony.
