### ISSUE TITLE
systemd-resolved: DNSSEC-enabled resolution of www.toolstop.co.uk fails

### ISSUE THREAD

**Issue by mikken** [systemd/systemd#2894]
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> 229
### Used distribution

> Gentoo
### In case of bug report: Expected behaviour you didn't see

> successful resolution
### In case of bug report: Unexpected behaviour you saw

> www.toolstop.co.uk: resolve call failed: DNSSEC validation failed: no-signature
### In case of bug report: Steps to reproduce the problem

$ systemd-resolved www.toolstop.co.uk
### Details

This looks like a normal not-signed DNS name.
This tool does not report any problem with it (only warnings): http://dnsviz.net/d/www.toolstop.co.uk/dnssec/
Google Public DNS and my local Unbound do not see any problem as well.
However, systemd-resolved reports bogus signature. 

<pre><code>
Transaction 15157 for <net. IN SOA> on scope dns on eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 64704 (incapdns.net. IN SOA).
Found verdict for lookup incapdns.net. IN SOA: bogus
DNSSEC validation failed for question incapdns.net. IN SOA: no-signature
Transaction 64704 for <incapdns.net. IN SOA> on scope dns on eth0/* now complete with <dnssec-failed> from network (unsigned).
</code></pre>

**Comment by poettering** [comment]
Fix waiting in #3173.
