### ISSUE TITLE
Can't it be optional to automatically add some well-known loaders found to the end of the list？

### ISSUE THREAD

**Issue by TommyJerryMairo** [systemd/systemd#2895]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 229-3
### Used distribution

While I was using the systemd-boot(bootctl), it automatically add **Windows Boot Manager** , **EFI Default Loader** as well as **Reboot Into Firmware Interface**.

I would like to rename the **Windows Boot Manager** , or hide this entry and make a new entry with the name I wanted.

I also want to hide the **EFI Default Loader** as well as **Reboot Into Firmware Interface** , in that before bootloader, there is a chance to choose whether get into BIOS or use which EFI APP next.

So, these three automatically added entries are not what I wanted.
But, there is no way else to deal with them, except remove line 1765~1772 from the [source code](https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L1766) and recompile it.

Thus, I hope it is possible to edit a config file to switch the auto-entries on/off, rather than edit the source code.

**Comment by febin92** [comment]
As a workaround, you can change the name of the concerned .efi entries. For instance the Windows Boot Manager entry looks for EFI/Microsoft/Boot/bootmgfw.efi. Renaming the 'Microsoft' to something else, say 'Windows' will get rid of the auto entry and can then be manually loaded with whatever Title is desired

**Comment by akoidan** [comment]
@febin92 is right. It looks for files and automatically [adds entries](https://wiki.archlinux.org/index.php/Systemd-boot#Adding_boot_entries). If someone is still confused to rename windows boot entry:

-  Don't re rename the directory, window still need that structure to load.
-  Move/rename `bootmgfw.efi` file somewhere.
-  Create file  `loader/entries/windows.conf` with content:
```
title Windows Boot Manager
efi \EFI\Microsoft\Boot\path_to_new_bootmgfw.efi
```

To remove `EFI Default Loader`:
 - Remove `/EFI/Boot/bootx64.efi` file
