### ISSUE TITLE
"systemd-run -p SELinuxContext=..." does not work 

### ISSUE THREAD

**Issue by alban** [systemd/systemd#2896]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 229-9.fc25
### Used distribution

> Fedora Rawhide
### Feature

The option [SELinuxContext=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SELinuxContext=) works when used in a .service file but using `systemd-run -p SELinuxContext=...` does not work:

```
$ sudo systemd-run -p SELinuxContext='system_u:system_r:unconfined_t:s0' id
Unknown assignment SELinuxContext=system_u:system_r:unconfined_t:s0.
Failed to create bus message: Invalid argument
```

Could this be added in systemd-run? Where should it be added?

**Comment by ghost** [comment]
Not sure if it makes sense to add this here. I can't make sense of your example at least.

without specifying an selinux context, systemd would (i believe) in fedora run the command in the unconfined_service_t domain, which is roughly the equivalent of unconfined_t AFAIK.

But also, this would only work if there is policy to allow this. The same goes for SELinuxContext= in service units but there, there are real good examples of why we would want this, and also a sane
way to deal with it policy-wise.

for example:

```
ExecStart=/usr/sbin/php-fpm --fpm-config=/etc/php-fpm.d/wordpress-pool.conf
SELinuxContext=sys.id:sys.role:wordpress.php_fpm.subj:s0
```

The above wouldn't  make sense systemd-run AFAICT. I do not think any policy authors are eager to allow systemd to just manually type transition from anywhere to anywhere. The above just automatically works for all `init_daemon_domain()`. no extra policy needed, except "setexec" for systemd.

So would be nice if you could come up with a good example.

**Comment by poettering** [comment]
This is a property that is currently not exposed for transient units, but we really should. The only reason it currently isn't exposed is because we didn't find the time to yet.

To expose this, it needs to be added to the transient logic in src/basic/dbus-execute.c and to the parser in bus_append_unit_property_assignment() in src/shared/bus-util.c.

The code for that should be pretty straigh-forward. Happy to take a patch.
