### ISSUE TITLE
error: undefined reference to 'MHD_lookup_connection_value'

### ISSUE THREAD

**Issue by yurikoles** [systemd/systemd#2897]
I'm trying to create lib32-systemd-git package for AUR and I have reached this problem while build.

```
/tmp/ccNY8xSQ.ltrans0.ltrans.o:<artificial>:function request_parse_accept: error: undefined reference to 'MHD_lookup_connection_value'
/tmp/ccNY8xSQ.ltrans0.ltrans.o:<artificial>:function request_handler.lto_priv.279: error: undefined reference to 'MHD_get_connection_info'
/tmp/ccNY8xSQ.ltrans0.ltrans.o:<artificial>:function request_handler.lto_priv.279: error: undefined reference to 'MHD_create_response_from_buffer'
```

and many other references to MHD_*
Here is the gist with all logs and the PKGBUILD: https://gist.github.com/yurikoles/120cffc84c141261f85d

**Comment by keszybz** [comment]
Is this before or after 2adeb166daee2a5d002cc0ccf0d96bcc6bdf04fb? (Please always specify the version in bug reports.)

**Comment by yurikoles** [comment]
It was master as of yesterday.

**Comment by keszybz** [comment]
I think it's an issue on your end, with `pkg-config` and `-m32`:

```
checking for MICROHTTPD... yes
...
/usr/bin/ld.gold: warning: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libmicrohttpd.so while searching for microhttpd
/usr/bin/ld.gold: warning: skipping incompatible /usr/lib/libmicrohttpd.so while searching for microhttpd
/usr/bin/ld.gold: error: cannot find -lmicrohttpd
```

You override the pkg-config search path, but maybe those 32-bit pkg-config files don't override the ld search path properly?

**Comment by poettering** [comment]
looks like a problem with your build, not sytemd upstream indeed. see @keszybz's comments. Please fix that first. Closing this one hence.
