### ISSUE TITLE
Warn against / Translate {,PART}{UUID,LABEL}=... in mount unit?

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#28989]
### Component

systemd

### Is your feature request related to a problem? Please describe

When `{,PART}{UUID,LABEL}=...` is used for the first field of an fstab entry, the generated mount unit would have proper dependency and ordering against its corresponding device unit because the field would be translated into a device path. But when `{,PART}{UUID,LABEL}=...` is used directly on a "handwritten" mount unit, no translation would be done and yet the mount unit is not deemed invalid either.

The result is that people will likely assume that it is "fine" to use `{,PART}{UUID,LABEL}=...` for `What=` and get "unexpected" race / mount failure.

### Describe the solution you'd like

I think we should either:

- warn in the system log when a mount unit with `{,PART}{UUID,LABEL}=...` is loaded / started
- translate `{,PART}{UUID,LABEL}=...` in `What=` into a device path when loading a mount unit, like the fstab generator does for an fstab entry

(One caveat of the second option is that there will then be no way to create mount unit that does not make use of `/dev/disk/by-*` symlinks. It's probably only a caveat when udev is not running yet / working properly though.)

### Describe alternatives you've considered

Well of course, if the user has read the man page of `systemd.mount` carefully and think thoroughly enough, they will know that they should avoid writing a mount unit with `What=` being `{,PART}{UUID,LABEL}=...` in the usual cases. Still it doesn't change the fact that there's a "silent pitfall".

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by lheckemann** [comment]
Agreed. I ran into this and it took me quite a while to work out why the mount was failing nondeterministically!
