### ISSUE TITLE
Adding .local to resolved.conf search domains sends to unicast DNS

### ISSUE THREAD

**Issue by dhouck** [systemd/systemd#28983]
### systemd version the issue has been seen with

254

### Used distribution

Arch

### Linux kernel version used

6.4.11-zen2-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

When I have
```
Domains=~. local.
MulticastDNS=yes
LLMNR=no
```
in my `resolved.conf`, and I try to resolve a single-label domain "foo", `systemd-resolved` should make an mDNS request for `foo.local` and return results appropriately for that

### Unexpected behaviour you saw

A query is sent to the public-internet unicast DNS for `foo.local`, which of course responds with NXDOMAIN, and does not do mDNS lookup.

### Steps to reproduce the problem

1. Configure `systemd-resolved` to have `local` in the `Domains` list, and with multicast DNS enabled
2. Request a single-label domain such as `foo` which is not resolved statically
3. Observe network traffic contains no multicast DNS requests but does contain a unicast DNS request.

**Comment by dhouck** [comment]
Further quotes from RFC 6762 about why this behavior is expected:

**Comment by dhouck** [comment]
I apparently missed some `systemd-resolved` documentation.  For some reason, adding `local` to the domain search list, instead of causing `systemd-resolved` to additionally search for `whatever.local` when you query `whatever`, means “send all `.local` queries to the unicast DNS resolver”, which is not behavior I expected.  I would expect that to be controlled differently and adding the `.local` domain to the search list to behave exactly as detailed in the RFC.

**Comment by poettering** [comment]
Search domains are a unicast DNS concept for us. We do not support the concept for mDNS, it's a trainwreck if you try, because mdns has no concept of "domain does not exist". It only knows "timeout" for that. Hence search domains on mdns is just a bad idea and not supported.

**Comment by poettering** [comment]
We can certainly make this clearer in the docs.
