### ISSUE TITLE
RFE: networkctl add options to show used files and settings.

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#28984]
### Component

networkctl

### Is your feature request related to a problem? Please describe

Just for consistency and ease of info for the admin's, i think it would be very welcomed to add the `show` and `cat` functionalities we have in `systemctl` to `networkctl`.
That way it will be much easier for the admin to see what files and values are actually used by `systemd-networkd`.

### Describe the solution you'd like

1. `networkctl cat dev`
This would show all the files with contents used in configuring the `dev`, especially when drop-in's are used.
1. `networkctl show dev`
This would show all settings in effect for `dev` due to the files used in (1) above.

### The systemd version you checked that didn't have the feature you are asking for

all to now

**Comment by YHNdnzj** [comment]
> all to now

Are you sure though? ;-)

`cat` is implemented in #27157

`show` has an existing request in #27248

Hence closing.

**Comment by TriMoon** [comment]
@YHNdnzj owwww hahaha oopsy, thanks for the headsup ! :+1: 
_Great minds think alike..._

**Comment by YHNdnzj** [comment]
> I didn't have a chance to try the newest, so which version will they be in?

`cat` and `edit` are available in v254 :)

**Comment by TriMoon** [comment]
Just a FYI, and others who might stumble on this issue via search engines, for people who are running an older systemd as `v254` _(Like current Kubuntu 23.04)_:

I created a wrapper script to view a similar output as what you described for the `networkctl cat` verb althoug no '@' support (yet)
- [Show involved Systemd-Networkd config files](https://gitlab.com/-/snippets/3612816)
