### ISSUE TITLE
Odd/impractical behaviour of journalctl with both --follow and --grep

### ISSUE THREAD

**Issue by tokred** [systemd/systemd#28996]
### systemd version the issue has been seen with

systemd 252 (252.12-1~deb12u1)

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-11-amd64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

`journalctl -f` mimics the traditional `tail -f /var/log/syslog` by showing the most recent 10 lines (old to new), and then subsequently displaying any new journal message instantly. This is perfectly documented in the manpage: `-f` implies the parameter `--lines`, and its default value is 10, so all good and practical.

`journalctl -g myterm` mimics `grep myterm /var/log/syslog | less` (broadly speaking, ignoring additional regex capabilities and case-insensitivity, etc). It displays matching lines, old-to-new, from the beginning of the journal. Optionally it can be combined with `-e` to jump to the most-recent end of the journal. If combined with `-n number`, it reverses the order to new-to-old (not immediately obvious but documented) and only shows the most recent _number_ matches. This is all documented behaviour, fine.

Combining `-f` with `-g myterm` gets odd and impractical though, in my view, as it does NOT mimic the common `tail -f | grep myterm`: I would expect `-g` to just "add" a pattern matching to the `journalctl -f` behaviour described above, i.e. showing the most recent lines of the journal (old-too-new) which match the term, and then staying in foreground to subsequently displaying any new matching journal message. Yes, this can be achieved with `journalctl -f | grep` too.

### Unexpected behaviour you saw

When running `journalctl -g myterm -f`, the most recent 10 matching lines are shown new-to-old, and after a short pause, the entire remaining journal is dumped (with only matching lines but depending on the pattern that can be A LOT). During the 5-15sec pause, the CPU spikes as apparently the entire journal is loaded/processed. Newly appearing messages are weirdly mixed in between (I think, hard to track).

This behaviour appears more like a `journalctl -g myterm -n <all> -r` as it reverses the line order, but without the PAGER!

### Steps to reproduce the problem

Run `journalctl -g myterm -f` with an arbitrary search term, e.g. `kernel` or `systemd`.

**Comment by YHNdnzj** [comment]
This should already be fixed by https://github.com/systemd/systemd/pull/26995.

Note that we only support the latest two releases here. Anything older than that should be reported to distro bug tracker first. Feel free to ask for re-opening if you can reproduce this with v253 or v254.
