### ISSUE TITLE
Global scope with `+DNSOverTLS` causes DNS leaks

### ISSUE THREAD

**Issue by soupglasses** [systemd/systemd#29005]
### systemd version the issue has been seen with

pm4gxdsl1jjn3yr063si78b6636vvda7-systemd-253.6

### Used distribution

NixOS 23.11

### Linux kernel version used

6.4.7-zen1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

When global configuration is set with `+DNSOverTLS` and another DNS server is used, for example OpenVPN (`tun0`), the global DNS will cause leaks outside the VPN DNS.

Bad configuration:

```console
Global
         Protocols: -LLMNR -mDNS +DNSOverTLS
                    DNSSEC=allow-downgrade/unsupported
  resolv.conf mode: stub
Current DNS Server: 1.1.1.1#cloudflare-dns.com
       DNS Servers: 1.1.1.1#cloudflare-dns.com
                    1.0.0.1#cloudflare-dns.com
                    2606:4700:4700::1111#cloudflare-dns.com
                    2606:4700:4700::1001#cloudflare-dns.com

Link 2 (eno1)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS +DNSOverTLS
                    DNSSEC=allow-downgrade/supported

Link 14 (tun0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
Current DNS Server: 10.14.0.1
       DNS Servers: 10.14.0.1
```

This does not occur if you set `-DNSOverTLS` and keep everything else the same.

This configuration works correctly with no leaked Global DNS queries.

```console
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS
                    DNSSEC=allow-downgrade/unsupported
  resolv.conf mode: stub
Current DNS Server: 1.1.1.1#cloudflare-dns.com
       DNS Servers: 1.1.1.1#cloudflare-dns.com
                    1.0.0.1#cloudflare-dns.com
                    2606:4700:4700::1111#cloudflare-dns.com
                    2606:4700:4700::1001#cloudflare-dns.com

Link 2 (eno1)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS +DNSOverTLS
                    DNSSEC=allow-downgrade/supported

Link 13 (tun0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS
                    DNSSEC=no/unsupported
Current DNS Server: 10.14.0.1
       DNS Servers: 10.14.0.1
```

### Unexpected behaviour you saw

The configuration of `DNSOverTLS` should not cause leakages in an unrelated Link where `DNSOverTLS` is explicitly disabled.

### Steps to reproduce the problem

The problematic configuration as-is:
```ini
# /etc/systemd/resolved.conf 
[Resolve]
DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
FallbackDNS=

LLMNR=false
DNSSEC=allow-downgrade
MulticastDNS=no
DNSOverTLS=yes
```

Use something like NetworkManager or similar tooling to set up a 2nd route that is preferred for DNS that does not go over `DNSOverTLS`. A simple example can be `9.9.9.9`.

Use https://mullvad.net/en/check and look under `Leaking DNS servers`. There should show up both Cloudflare and the 2nd DNS server.

```console
% resolvectl
Global
         Protocols: -LLMNR -mDNS +DNSOverTLS
                    DNSSEC=allow-downgrade/supported
  resolv.conf mode: stub
Current DNS Server: 1.1.1.1#cloudflare-dns.com
       DNS Servers: 1.1.1.1#cloudflare-dns.com
                    1.0.0.1#cloudflare-dns.com
                    2606:4700:4700::1111#cloudflare-dns.com
                    2606:4700:4700::1001#cloudflare-dns.com

Link 2 (eno1)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS
                    DNSSEC=allow-downgrade/supported
Current DNS Server: 9.9.9.9
       DNS Servers: 9.9.9.9
```

**Comment by poettering** [comment]
i cannot parse this. what are you trying do say with "dns leaks"? that requests are routed to dns servers where you don#t want them?

You didn't configure and dns routes, hence resolved sends requests everwhere, so this behaviour is expected from you configuration?

the tool associating the dns server with the interface should also set up dns routes as needed, for example via "resolvectl domain" or similar.

anyway, i can't make much sense of the request.

**Comment by soupglasses** [comment]
Yeah sorry. When `DNSOverTLS=yes` is set in the Global configuration, it will send out queries on what seems like both DNS servers. Disabling DNSOverTLS will make queries only go over the configured DNS server and not touch the Global DNS server.

I have a gut feeling its may not be all queries, but rather a subset which the tool at https://mullvad.net/en/check is able to create an edgecase for. I am unsure if there exists a local alternative to test this against which can reproductive the problem more clearly.

**Comment by soupglasses** [comment]
My gut feeling about "not all queries" is wrong from some more looking, it instead seems like the irregularity for what shows up on the test page is timing based.

**Comment by soupglasses** [comment]
So i looked into this further. And `+DNSOverTLS` has little to do with it.

Working trough the "bad configuration" with debug logs showed this:
```
varlink-19: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net","flags":0}}
varlink-19: Changing state idle-server → processing-method
idn2_lookup_u8: 24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net → 24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net
Looking up RR for 24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net IN A.
Looking up RR for 24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net IN AAAA.
Cache miss for 24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net IN AAAA
Firing regular transaction 16497 for <24785973d8714c48a13fbc3e776d8db1.dnsleak.am.i.mullvad.net IN AAAA> scope dns on */* (validate=yes).
Using feature level TLS+EDNS0+DO for transaction 16497.
Using DNS server 1.0.0.1#cloudflare-dns.com for transaction 16497.
Sending query via TCP since UDP isn't supported or DNS-over-TLS is selected.
Using feature level TLS+EDNS0+DO for transaction 16497.
...
```

Its using a scope `scope dns on */*` and sets a `Using DNS server 1.0.0.1#cloudflare-dns.com` even if something like `+DefaultRoute` is set explicitly for `tun0`.

Removing all DNS configuration from the Global section causes the following correct output:

```
varlink-25: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net","flags":0}}
varlink-25: Changing state idle-server → processing-method
idn2_lookup_u8: 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net → 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net
Looking up RR for 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN A.
Looking up RR for 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN AAAA.
Cache miss for 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN A
Firing regular transaction 459 for <53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN A> scope dns on tun0/* (validate=yes).
Using feature level UDP+EDNS0 for transaction 459.
Using DNS server 10.14.0.1 for transaction 459.
Announcing packet size 1472 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
Sending query packet with id 459 of size 86.
Cache miss for 53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN AAAA
Firing regular transaction 16759 for <53b22290a2e84019b592246fdc41ecba.dnsleak.am.i.mullvad.net IN AAAA> scope dns on tun0/* (validate=yes).
Using feature level UDP+EDNS0 for transaction 16759.
Using DNS server 10.14.0.1 for transaction 16759.
Announcing packet size 1472 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
Sending query packet with id 16759 of size 86.
```

Interestingly it now specifies `scope dns on tun0/*` instead of `*/*` as before, and correctly takes the DNS server to be `10.14.0.1`.

---

I am not quite sure what is happening here, nor how i could make sure such a scope is applied even when I have configured Global DNS servers.

My current workaround is likely just gonna be applying my default TLS based DNS servers with `nmcli` for every connection. As this seems to get handled correctly compared to using a global configuration.

**Comment by poettering** [comment]
is this still relevant? if you configure proper routing domains on the vpn, it should just work? so far you didn't hence all dns queries get blasted everywhere, this is by design.

If you set a routing domain on that vpn, then things should start working.

(I can't tell you how – or even if – NM allows you to configure routing domains, but it should just work if you do)

**Comment by poettering** [comment]
Closing due to lack of response (and it appears to be local misconfiguration anyway)
