### ISSUE TITLE
coredump.conf(5) needs to explain what to do to load new configuration

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#2901]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> …
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

**Comment by archenemies** [comment]
I changed `/etc/systemd/coredump.conf` to have "Storage=both", however, when a process segfaults and says "Core dumped", "sudo coredumpctl dump" reports

```
Cannot retrieve coredump from journal nor disk.
Coredump retrieval failed: No such file or directory
```

(By the way, it should be "or" not "nor" above)

So I go back to the `coredump.conf(5)` man page but it doesn't tell me what to do to get Systemd to reload the configuration. I think that the man page would be a natural place for this information to exist. Thanks!

(P.S. When Googling, I found some information - it said just "ln -s /dev/null /etc/systemd/coredump.conf" and you can get core dumps in the current directory like before. But I tried that, rebooted, and it didn't work. Is there a way to get the old behavior, of dumping into the current directory - and can the man page be updated to explain how to do this?)

(By the way this is under Systemd 229, Arch Linux distribution)

**Comment by keszybz** [comment]
You're right, both things need fixing.

There's no need to reload anything, the handler is started for each new coredump by the kernel and reads the configuration on start-up.

**Comment by evverx** [comment]
>  Is there a way to get the old behavior, of dumping into the current directory - and can the man page be updated to explain how to do this?

https://www.freedesktop.org/software/systemd/man/systemd-coredump.html

> Systemd installs /usr/lib/sysctl.d/50-coredump.conf which configures kernel.core_pattern to invoke systemd-coredump. This file may be masked or overridden to use a different setting following normal sysctl.d(5) rules.

Try

```
sysctl kernel.core_pattern=core
echo kernel.core_pattern=core >/etc/sysctl.d/99-coredump.conf
```

**Comment by archenemies** [comment]
Thanks. So it seems that coredump.conf(5) should explain that additional configuration documentation is to be found in systemd-coredump(8) (which is not so obvious). The latter (or both, or a man page referenced prominently by both) should describe
- exactly what syntax to use in kernel.core_pattern, or where to find it documented
- how to create a custom kernel.core_pattern, using a file in /etc/sysctl.d/
- how to get this file reloaded when it changes
- explicitly how to get the Linux default (pre-Systemd) behavior, and 
- how to switch to the Systemd default behavior (where coredump.conf fits in?)

This is in addition to adding the following additions to coredump.conf(5):
- the fact that the file is read after each core dump, so doesn't need to be "loaded" by e.g. daemon-reload (if this is indeed true)
- I would suggest, it should describe an easy way to create a core dump, so that the configuration can be tested, along with an example of using `coredumpctl dump` to retrieve the core file

It seems a bit awkward having this data spread across multiple man pages, but I guess core(5) is a Linux man page so we can't put it there... Hope this all makes sense.

**Comment by evverx** [comment]
Do you really mean a man page?
Looks like a book "secrets of the coredump ninja":)

> describe an easy way to create a core dump

```
sh -c 'kill -SEGV $$'
```

**Comment by archenemies** [comment]
Yeah, why not put it in a man page? I didn't think of it, I made a little C program, your solution is much better. And it answers the question "how do I test this configuration". Back when I was first encountering this config file, I had a program that was making 1GB core dumps, which made for an annoying test cycle. Ta.

**Comment by archenemies** [comment]
Yay! Thank you.
