### ISSUE TITLE
`hostnamectl` JSON format requires root

### ISSUE THREAD

**Issue by laurelmay** [systemd/systemd#29014]
### systemd version the issue has been seen with

systemd 254.1-1

### Used distribution

Arch Linux

### Linux kernel version used

6.4.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

hostnamectl

### Expected behaviour you didn't see

I expected `hostnamectl --json=pretty` to work just as well as `hostnamectl` but to provide it in a JSON format.

### Unexpected behaviour you saw

Without root permissions, `hostnamectl --json=pretty` returns the error `Could not get description: Access denied` while `--json=off` works as expected.

### Steps to reproduce the problem

1. Run `hostnamectl --json=off`, see that it outputs correctly
1. Run `hostnamectl --json=pretty` or `hostnamectl --json=short`.
1. See that the `Describe` call to `org.freedesktop.hostname1` fails with `org.freedesktop.DBusError.AccessDenied`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ hostnamectl --json=pretty
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.207 path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 member=Describe cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=error sender=:1.202 destination=:1.207 path=n/a interface=n/a member=n/a  cookie=15 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.AccessDenied error-message=Permission denied
Could not get description: Access denied
Bus n/a: changing state RUNNING → CLOSED
```

**Comment by yuwata** [comment]
This is already fixed by b56ee692334231f0312c2fd142b9f2a84da14ac9.
