### ISSUE TITLE
using systemd-nspawn to boot f2fs images is broken

### ISSUE THREAD

**Issue by greyltc** [systemd/systemd#29026]
https://github.com/systemd/systemd/blob/c27465d72d22e23be3ad0a6bdd139d8ed1aeb80e/src/shared/dissect-image.c#L2180

I used to be able to use `systemd-nspawn`  to boot my f2fs images, but now I can't. What's the reason for locking out f2fs?

**Comment by poettering** [comment]
We by default will not automatically mount exotic file systems, of which so far f2fs is considered one. You can use the mentioned env var to extend the list.

I am not convinced f2fs really should be among the default file systems to allow. I never had contact with a f2fs file system, it seems to be very niche.
