### ISSUE TITLE
systemctl isolate sometimes stops the wrong service

### ISSUE THREAD

**Issue by yshui** [systemd/systemd#29053]
### systemd version the issue has been seen with

254

### Used distribution

Archlinux

### Linux kernel version used

6.5.1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Context

I am not 100% sure if my services are setup incorrectly, and because this happens in initrd it's difficult for me to debug.

What I was seeing is that _sometimes_ my initrd will fail at switch-root. Whether a particular boot will fail or not seems to be unpredictable. If I look at the journal, it appears that systemd chose to stop the `sysroot.mount` service before trying to switch-root, and then fails because `/sysroot` is not mounted.

Relevant parts of the log:

```
Sep 04 09:24:41 archlinux systemd[1]: Reached target Initrd Root File System.
Sep 04 09:24:41 archlinux systemd[1]: Starting Mountpoints Configured in the Real Root...
Sep 04 09:24:41 archlinux systemd[1]: initrd-parse-etc.service: Deactivated successfully.
Sep 04 09:24:41 archlinux systemd[1]: Finished Mountpoints Configured in the Real Root.
Sep 04 09:24:41 archlinux systemd[1]: Reached target Initrd File Systems.
Sep 04 09:24:41 archlinux systemd[1]: Reached target Initrd Default Target.
Sep 04 09:24:41 archlinux systemd[1]: Starting Cleaning Up and Shutting Down Daemons...
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Initrd Default Target.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Basic System.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Initrd Root Device.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Initrd Root File System.             <------ HERE
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Path Units.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Slice Units.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Socket Units.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target System Initialization.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Local File Systems.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Swaps.
Sep 04 09:24:41 archlinux systemd[1]: Stopped target Timer Units.
Sep 04 09:24:41 archlinux systemd[1]: systemd-modules-load.service: Deactivated successfully.
Sep 04 09:24:41 archlinux systemd[1]: Stopped Load Kernel Modules.
Sep 04 09:24:41 archlinux systemd[1]: Stopping Rule-based Manager for Device Events and Files...
Sep 04 09:24:41 archlinux systemd[1]: initrd-cleanup.service: Deactivated successfully.
Sep 04 09:24:41 archlinux systemd[1]: Finished Cleaning Up and Shutting Down Daemons.
Sep 04 09:24:41 archlinux systemd[1]: Unmounting /sysroot...                                  <------ and HERE
Sep 04 09:24:41 archlinux systemd[1]: sysroot.mount: Deactivated successfully.
Sep 04 09:24:41 archlinux systemd[1]: Unmounted /sysroot.
```

OTOH when it boots successfully, it does not do that.

In `initrd-switch-root.target`, there is clearly `Wants=initrd-root-fs.target`, so I don't understand why isolating this target will stop `initrd-root-fs.target`. And also why systemd is doing it non-deterministically.

**Comment by mrc0mmand** [comment]
Could you boot the system with `systemd.log_level=debug` and then provide the journal when the issue happens?

**Comment by yshui** [comment]
Can you tell me what I should be looking for? Does systemd log why it's stopping a service?

**Comment by yshui** [comment]
Maybe this?

```
Sep 05 08:49:22 archlinux systemd[1]: initrd-switch-root.target: Trying to enqueue job initrd-switch-root.target/start/isolate
Sep 05 08:49:22 archlinux systemd[1]: initrd-switch-root.target: Fixing conflicting jobs initrd-switch-root.target/stop,initrd-switch-root.target/start by deleting job initrd-switch-root.target/stop
Sep 05 08:49:22 archlinux systemd[1]: systemd-ask-password-console.service: Deleting job systemd-ask-password-console.service/start as dependency of job initrd-switch-root.target/stop
Sep 05 08:49:22 archlinux systemd[1]: sysroot.mount: Deleting job sysroot.mount/start as dependency of job systemd-ask-password-console.service/start
```

**Comment by yshui** [comment]
I see, the generated `sysroot.mount` has a `Requires=systemd-ask-password-console.service`. So when that's stopped, sysroot is umounted.

Now what I don't understand is why it only happens _some_ of the times.

**Comment by yshui** [comment]
And also, what's the best solution here? `sysroot.mount` does require ask-password-console, so I can't use `Wants`, but I also don't want `sysroot.mount` to be stopped

**Comment by Werkov** [comment]
`Wants=` may still be good enough. The mount would fail/timeout without it, no? (Comparable with a failed `Requires=` dependency.)

**Comment by Werkov** [comment]
@yshui Is this still a systemd bug?

**Comment by poettering** [comment]
> Now what I don't understand is why it only happens _some_ of the times.

how does the unit precisely look like? what generates that? systemd certainly not, we don't generate such dependencies? is that a local thing?

my educated guess: you have Requires= but no order dep, i.e. no After= or so. Which makes the ordering of things undefined.

Anyway, there hasn't been any further comment in a while. Closing hence.
