### ISSUE TITLE
[RFE] systemctl help (more as man pages)

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#29061]
- https://github.com/systemd/systemd/blob/main/src/systemctl/systemctl-show.c#L831-L835
https://github.com/systemd/systemd/blob/47d8770aace000e0bfcc68ecf7d84e0bd9886431/src/systemctl/systemctl-show.c#L831-L835

Could this be enhanced to allow `file:`, `http:` and `https:` :thinking: 
The more and more people create units, the more they like to add links to some documentation to accompany the unit...

- For `file:` you could use [the default pager](https://github.com/systemd/systemd/blob/main/src/shared/pager.c) to display the plain text contents of the file.
- For `http:` and `https:` you could possibly make use of an environment variable, to select the viewer to launch?
fe `${SYSTEMD_HELP_VIEWER}`, `${SYSTEMD_HELP_ONLINE_VIEWER}` or similar...
Which defaults to lets say `www-browser` or `x-www-browser` or the value from `xdg-settings get default-web-browser`.
(see also https://linuxconfig.org/how-to-set-browser-environment-variable-on-linux)

**Comment by poettering** [comment]
> * For `file:` you could use [the default pager](https://github.com/systemd/systemd/blob/main/src/shared/pager.c) to display the plain text contents of the file

why do you think that would be appropriate? `file:` is a (pseudo-) protocol, and not a hint about the file format used. the referenced doc could be an html or PDF or so, you really shouldn't dumb that in a pager.

**Comment by TriMoon** [comment]
@poettering 
> why do you think that would be appropriate? `file:` is a (pseudo-) protocol, and not a hint about the file format used.

I know... But it is mostly, or will be, used to link to local text/markdown files.

> the referenced doc could be an html or PDF or so, you really shouldn't dump that in a pager.

If you find it too dangerous, you could check the extension or even check the mime-type of the file pointed at, before feeding it to the pager...

Besides, it's the responsibility of the Unit writer to point the documentation using `file:` to a **text file** fit for display in the default pager right?
