### ISSUE TITLE
Try to adjust the order of network interface by udev but failed.

### ISSUE THREAD

**Issue by xiacunshun** [systemd/systemd#29073]
### systemd version the issue has been seen with

253

### Used distribution

OpenCloudOS stream

### Linux kernel version used

6.1.11-2302.1.1

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

interface with MAC AAAA is named eth1
interface with MAC BBBB is named eth0

### Unexpected behaviour you saw
interface with MAC AAAA is named eth0
interface with MAC BBBB is named eth1

and I got this in journal log.

Sep 05 16:11:32 TENCENT64 systemd-udevd[564]: eth1: Failed to rename network interface 2 from 'eth0' to 'eth1': File exists
Sep 05 16:11:32 TENCENT64 systemd-udevd[564]: eth1: Failed to process device, ignoring: File exists
Sep 05 16:11:32 TENCENT64 systemd-udevd[565]: Network interface NamePolicy= disabled on kernel command line.
Sep 05 16:11:32 TENCENT64 systemd-udevd[565]: eth0: Failed to rename network interface 3 from 'eth1' to 'eth0': File exists
Sep 05 16:11:32 TENCENT64 systemd-udevd[565]: eth0: Failed to process device, ignoring: File exists

### Steps to reproduce the problem

`biosdevname=0 net.ifnames=0` in cmdline
and following udev rules.
[root@TENCENT64 ~]# cat  /etc/udev/rules.d/70-persistent-net.rules
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="AAAA", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="BBBB", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"

**Comment by xiacunshun** [comment]
I have seen the doc. https://www.freedesktop.org/software/systemd/man/systemd.link.html#Name=
But I just wonder how can I change the order of these two interfaces (for some reasons).

**Comment by xiacunshun** [comment]
And It seems that this issue https://github.com/systemd/systemd/issues/16665 can not resolve my problem.

**Comment by YHNdnzj** [comment]
> I have seen the doc. https://www.freedesktop.org/software/systemd/man/systemd.link.html#Name=
> But I just wonder how can I change the order of these two interfaces (for some reasons).

Please assign prefixes other than eth* and wlan*. The man page has made it very clear that this is not supported by kernel. There's nothing actionable for udev here.

**Comment by yuwata** [comment]
The name ethX is used by the kernel. We cannot swap names without race. Please use other names.

**Comment by liufeng123456** [comment]
Is there a suitable solution now?
