### ISSUE TITLE
systemd-import should preserve extended attributes

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#2908]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

v229
### Used distribution

Gentoo Linux
### Description

Extended attributes are used to implement things like file-based capabilities and PaX markings. They should be preserved by systemd-import when creating a container image.

For tar archives, this would mean passing the `--xattrs` flag to tar. This is only recently supported by GNU tar, so there might need to be some fallback mechanism.

I'm not sure what (if anything) would need to be done for raw archives. If they just get loop mounted, maybe nothing needs to be done.

**Comment by floppym** [comment]
The tar command would have to be something like this:

```
tar --xattrs-include=* ...
```

Or, to include only some useful subset of xattrs:

```
tar --xattrs-include=security.capability --xattrs-include=user.* ...
```

**Comment by poettering** [comment]
The docs of GNU tar suggest that xattrs are saved/restored by default anyway:

```
     By default, all extended attributes are stored into the archive.
     The reason is that we want to make the backup process as complete
     as possible by default.  On the other hand, during extracting only
     the 'user.*' domain is extracted by default.  Anyway, this default
     behaviour may be easily modified by the '--xattrs-include' and
     '--xattrs-exclude' options.
```

Hence, what you are asking for should already be the default. What am I missing?

**Comment by floppym** [comment]
What is your documentation source? These options were undocumented upstream for a long time, and I had a hard time figuring them out as a result. I suspect your distro might be patching the manual.

It looks like documentation was added to the upstream tar git repo on 2016-03-16, and it says something different from the paragraph you have quoted.

http://git.savannah.gnu.org/cgit/tar.git/commit/doc/tar.texi?id=e4b246c14abc36ed3f4cb36b929e287223a9139f

tar.texi indicates that `--no-xattrs` is the default. You would need to pass `--xattrs` to enable it.

```
@item --xattrs
Enable extended attributes support.  When used with @option{--create},
this option instructs @GNUTAR to store extended file attribute in the
created archive.  This implies POSIX.1-2001 archive format
(@option{--format=pax}).

When used with @option{--extract}, this option tells @command{tar},
for each file extracted, to read stored attributes from the archive
and to apply them to the file.

@item --no-xattrs
Disable extended attributes support.  This is the default.
```

Your quoted documentation says that only `user.*` is extracted by default. This means any filecaps stored in the `security.capability` attribute would be lost.

In contrast, the upstream docs say that all names are extracted by default if `--xattrs` is enabled.

My real-world experience with tar-1.28 seems to indicate that the former behavior is accurate. You would need to pass the following options to tar to restore all extended attributes on extraction:

```
tar --xattrs --xattrs-include=* --extract ...
```

**Comment by poettering** [comment]
It's the "info" pages for tar as shipped with Fedora 23.

If this was a Fedora-specific patch then I am fine with adding "--xattrs --xattrs-include=*" to the default arguments, when invoking "tar". Any chance you can prep a patch for that? Should be pretty trivial, just patch import_fork_tar_x() and import_fork_tar_c() in src/import/import-common.c, and test. Given that I don't have an unpatched tar version around, it would be pretty important if you could test this before submitting.

**Comment by floppym** [comment]
Sure, I'll give it a shot.
