### ISSUE TITLE
serial-getty@.service could inherit $TERM from /proc/cmdline (`systemd.tty.term.console=` or `TERM=`)

### ISSUE THREAD

**Issue by trentbuck** [systemd/systemd#29097]
### Component

systemd

### Is your feature request related to a problem? Please describe

As at `systemd 252 (252.12-1~deb12u1)` and `systemd 254 (254.1-2)`, if I boot with `earlyprintk=ttyS0 console=ttyS0 TERM=dumb`,

1.  the `[  OK  ] Started foo@.service - Foo.` lines stop getting bold and color escape sequences -- good.
2. actually logging into the serial getty and doing `echo $TERM` still shows `vt220` -- bad!

Am I missing something obvious here?  It looks like `serial-getty@.service` is already supposed to inherit `$TERM` from *somewhere,* and I can't see where else it could be meant to inherit from. 

I want this so I can hook up a VM's single OS image to different terminal emulators at different boots (TERM=dumb, TERM=linux, TERM=screen-256color, TERM=xterm-256color).  With `kvm -nographic -append 'console=ttyS0 TERM=dumb'` this is already working for pid1, but not for `serial-getty@.service`. 

### Describe the solution you'd like

systemd is already getting the PID1's terminal from /proc/cmdline: https://github.com/systemd/systemd/blob/v254/src/core/main.c#L1476-L1494
systemd is already passing $TERM to serial-getty@.service by default: https://github.com/systemd/systemd/blob/v254/units/serial-getty@.service.in#L36
I would like these to be glued together, so that `console=ttyS0 TERM=X` causes both pid1 *and* the serial getty to "see" TERM=X.

PS: I guess a counterargument might be that TERM= on in /proc/cmdline is setting the terminal type for /dev/console, which is not necessarily the terminal type for *all* serial terminals.  So perhaps this should only be setting `TERM=<TERM from /proc/cmdline>` for `serial-getty@<console from /proc/cmdline>.service`, rather than *all* `serial-getty@.service`?

### Describe alternatives you've considered

- Put up with the current behaviour (serial-getty@.service is always TERM=vt220).
- Write a `/lib/systemd/system-generators/foo` that re-parses `/proc/cmdline` and if it sees `systemd.tty.term.console` or `TERM`, writes `[Service] Environment=TERM=X` to `/run/systemd/system/serial-getty@.service.d/foo.conf`

### The systemd version you checked that didn't have the feature you are asking for

254.1

**Comment by trentbuck** [comment]
Attached is a minimal script and its output demonstrating the issue on Debian 13 / systemd v254.
[debian-13-minimal.py.txt](https://github.com/systemd/systemd/files/12532367/debian-13-minimal.py.txt)
[debian-13-minimal.log.txt](https://github.com/systemd/systemd/files/12532368/debian-13-minimal.log.txt)

**Comment by trentbuck** [comment]
The "alternate method" workaround seems to be working.  In `/lib/systemd/system-generators/bootstrap2020-fix-serial-getty-terminal-type`:

```python
#!/usr/bin/python3 
import logging
import pathlib
import re

__doc__ = """ https://github.com/systemd/systemd/issues/29097 """

# FIXME: deal with quoting/escaping &c in /proc/cmdline 
# FIXME: for "TERM=x TERM=y", which should win? 
# FIXME: /proc/cmdline might not be UTF-8 clean. 
cmdline = pathlib.Path('/proc/cmdline').read_text()
try:
    console, = re.search(r'console=(\w+)', cmdline).groups()
    term, = re.search(r'(?:systemd.tty.term.console|TERM)=(\w+)', cmdline).groups()
except AttributeError:
    logging.debug('Did not find both keys; doing nothing')
else:
    # FIXME: systemd-escape console 
    erratum_path = pathlib.Path(
        f'/run/systemd/generator/serial-getty@{console}.service.d/foo.conf')
    erratum_path.parent.mkdir(exist_ok=True, parents=True)
    erratum_path.write_text(
        '[Service]\n'
        f'Environment=TERM={term}\n')
```

![Screenshot from 2023-09-06 14-50-44](https://github.com/systemd/systemd/assets/64124132/e09d932b-d615-4813-8441-b3974f877eb5)

**Comment by DaanDeMeyer** [comment]
Can you try with systemd.tty.tty.term.ttyS0? that should do the trick

**Comment by trentbuck** [comment]
> Can you try with systemd.tty.tty.term.ttyS0? that should do the trick

Thanks!  `systemd.tty.tty.term.ttyS0` didn't work, but `systemd.tty.term.ttyS0` did work.

Specifically I did `chroot $1 /lib/systemd/ukify build --linux=/vmlinuz --initrd=/initrd.img --cmdline="boot=live earlyprintk=ttys0 console=ttyS0 systemd.tty.term.console=dumb systemd.tty.term.ttyS0=dumb"` and once booted and logged into the serial console, `echo $TERM` correctly reports `dumb`, when testing with `systemd 254 (254.1-2)`.

It did *not* work with `systemd 252 (252.12-1~deb12u1)` using `boot=live earlyprintk=ttyS0 console=ttyS0 TERM=dumb systemd.tty.term.ttyS0=dumb`.

I can just code up `console=ttyS0 systemd.tty.term.console=$TERM systemd.tty.term.ttyS0=$TERM` now, and it'll start working whenever Debian upgrades from https://github.com/systemd/systemd/releases/tag/v252 to https://github.com/systemd/systemd/releases/tag/v254

I think this is a Good Enough fix, so I'll click the "Close with comment" button and see what github does...
