### ISSUE TITLE
networkd DHCP client search domains parse error - '032' string

### ISSUE THREAD

**Issue by zarianu** [systemd/systemd#29107]
### systemd version the issue has been seen with

systemd 254 (254.1-1-arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.4.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

networkctl, resolvectl, systemd-networkd, systemd-resolved

### Expected behaviour you didn't see

Non-FQDN names can't be resolved using search domains list from DHCP server

### Unexpected behaviour you saw

DNS Domains list is received from DHCP server with strange '032' string between two domains:
```
[kost@archie ~]$ resolvectl 
Global
           Protocols: -LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
Fallback DNS Servers: 1.1.1.1#cloudflare-dns.com 9.9.9.9#dns.quad9.net 8.8.8.8#dns.google
                      2606:4700:4700::1111#cloudflare-dns.com 2620:fe::9#dns.quad9.net
                      2001:4860:4860::8888#dns.google

Link 3 (wlan0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.101
       DNS Servers: 192.168.1.101
        DNS Domain: domain1.tld032domain2.tld

```

Here's networkd config:
```

[kost@archie ~]$ cat /etc/systemd/network/20-wireless.network 
[Match]
Name=wlan0

[Network]
DHCP=yes

[DHCP]
UseDomains=true

```

### Steps to reproduce the problem

DHCP server should send multiple DNS search domains (option 15).

There's no problem with Windows/MacOS/iOS DHCP clients parsing multiple domains in this list. Only systemd-networkd.

**Comment by yuwata** [comment]
Which protocol provides the domain ? DHCPv4 ? DHCPv6 ? NDisc (RA)?

Please provide the corresponding packet dump.

**Comment by zarianu** [comment]
> Which protocol provides the domain ? DHCPv4 ? DHCPv6 ? NDisc (RA)?
> 
> Please provide the corresponding packet dump.

Sorry, my bad, DHCPv4, pls see pcap attached

**Comment by zarianu** [comment]
> Which protocol provides the domain ? DHCPv4 ? DHCPv6 ? NDisc (RA)?
> 
> Please provide the corresponding packet dump.

Sorry, my bad, pls find packet 
[dhcp4.pcap.gz](https://github.com/systemd/systemd/files/12540268/dhcp4.pcap.gz)
capture attached.

**Comment by yuwata** [comment]
Thanks. Indeed option 15 provides multiple domains, and in that case we wrongly concatenate the domains.
But, [RFC 2132](https://datatracker.ietf.org/doc/html/rfc2132#section-3.17) does not mention how we should handle multiple domains, unlike option 119 ([RFC3397](https://datatracker.ietf.org/doc/html/rfc3397#section-2)).

But yeah, maybe we should parse the option in the same way as option 119.

**Comment by yuwata** [comment]
Hm, the format is seems to be different from the option 119. Domains are separated with space...

**Comment by yuwata** [comment]
Are there any RFC how to parse the option?

**Comment by yuwata** [comment]
I found an old document http://support.novell.com/docs/Tids/Solutions/10060439.html, and it says windows does not support multiple domains in option 15.

Could you confirm that the parsed domains on other implementations (Windows, MacOS, ...) actually handle the list. I guess they simply show the string in the option, while we escape the unsupported characters in the string.

**Comment by zarianu** [comment]
Just checked on Microsoft Windows [Version 10.0.19041.1415] - it treats all the string from option 15 as a single domain (see attached picture) - so it's not working as intended. Will check on iOS and other linux later.

![win10-domains](https://github.com/systemd/systemd/assets/2607073/dbe75f7b-0d77-4162-9ba5-a47b35354deb)

**Comment by zarianu** [comment]
Tested on different OSes - only Apple MacOS and iOS treats multiple domains in Option 15 in some proprietary way. Linuxes, Windows can't parse multiple domain string. So I think the best way is to use Option 119.

Thanks for your great job!

**Comment by yuwata** [comment]
Thank you for testing. Closing then.
