### ISSUE TITLE
systemd-networkd does not reconfigure IPv6 after link up event

### ISSUE THREAD

**Issue by cvmiller** [systemd/systemd#2912]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

`# /usr/lib/systemd/systemd --version`

> systemd 229
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> After issuing the commands:
> ip link set eth0 down
> ip link set eth0 up

Expected to see IPv6 config reapplied to eth0 interface. Expected to see static IPv6 address, and SLAAC addresses reassigned to interface (see /etc/systemd/network/eth0.network below).
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

1) setup a IPv6 SLAAC environment with RAs advertising IPv6 prefix (no DHCPv6).
2) note the output of 'ip addr'
3) disable/enable interface

```
ip link set eth0 down
ip link set eth0 up
```

4) Note link up event

```
[865151.713531] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[865153.329833] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
```

5) note that DHCPv4 acquires an address, but there is NO ipv6 prefixes (other than fe80) assigned.
### Additional information:

'ip addr' output before problem:

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:56:b3:04:cb:e5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.151/24 brd 192.168.11.255 scope global dynamic eth0
       valid_lft 43198sec preferred_lft 43198sec
    inet6 2607:c000:8124:ca05:54f3:9748:e048:9820/64 scope global temporary dynamic 
       valid_lft 7198sec preferred_lft 1798sec
    inet6 2607:c000:8124:ca05:12:34:56:78/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 7198sec preferred_lft 1798sec
    inet6 2001:470:1d:583::cbe5/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::256:b3ff:fe04:cbe5/64 scope link 
       valid_lft forever preferred_lft forever
```

After disable/enabling the interface:

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:56:b3:04:cb:e5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.151/24 brd 192.168.11.255 scope global dynamic eth0
       valid_lft 43197sec preferred_lft 43197sec
    inet6 fe80::256:b3ff:fe04:cbe5/64 scope link 
       valid_lft forever preferred_lft forever
```
### systemd-networkd configuration /etc/systemd/network/eth0.network

```
# cat /etc/systemd/network/eth0.network`
[Match]
Name=eth0

[Network]
DHCP=ipv4
# static IPv6 address assignment
Address=2001:470:1d:583::cbe5/64
IPv6PrivacyExtensions=yes
IPv6Token=::12:34:56:78
```
### Work-around

Restart networkd service after disable/enable eth0
`systemctl restart systemd-networkd.service`

**Comment by vindicatorr** [comment]
In a separate terminal/session, you should run "ip monitor" to see what else is going on.
In my case, it was "Error sending Router Solicitation" (https://github.com/systemd/systemd/issues/2365)
So while it's not a new issue, I haven't seen anything being done with it.

I don't know about your results, but for some reason, I'm also not getting any ipv6 gateway/route:

```
$ ip -6 route
ff00::/8 dev custom_eth0  metric 256  pref medium
default via fe80::... dev custom_eth0  proto ra  metric 1024  pref medium
$ networkctl status custom_eth0
● 2: custom_eth0
...
         Address: <isp dhcpv4 address>
                  <isp ipv6 address>
                  fe80::...
         Gateway: <isp ipv4 gateway address> (Cisco Systems, Inc)
                  fe80::...
```

Mind you, this only shows the ipv6 address after a clean boot, not after a systemd-networkd which won't pull v6 at all.

At this very moment, I'm looking into netctl to see if that'll be a viable temporary option.

EDIT:
or for that matter, I'm wondering how one would pull v6 manually using the "ip" command.

**Comment by cvmiller** [comment]
Attaching 'ip monitor' file, as requested. As you can see when the link goes down, the IPv6 config is cleared out. But when the link comes up, only IPv4 config is applied.
[mon.txt](https://github.com/systemd/systemd/files/196551/mon.txt)

**Comment by cvmiller** [comment]
Here is my networkctl output before link disable/enable:

```
networkctl status eth0
* 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/eth0.network
            Type: ether
           State: routable (configured)
            Path: platform-4a064c00.ehci-usb-0:1.1:1.0
          Driver: smsc95xx
          Vendor: Standard Microsystems Corp.
           Model: SMSC9512/9514 Fast Ethernet Adapter
      HW Address: 00:56:b3:04:cb:e5
             MTU: 1500
         Address: 192.168.11.151
                  2001:470:1d:583::cbe5
                  2607:c000:8124:ca05:12:34:56:78
                  2607:c000:8124:ca05:8948:6c5:241e:98ec
                  fe80::256:b3ff:fe04:cbe5
         Gateway: 192.168.11.1 (BUFFALO.INC)
                  fe80::213:3bff:fe99:19ba (Speed Dragon Multimedia Limited)
                  fe80::224:a5ff:fed7:3088 (BUFFALO.INC)
             DNS: 10.1.1.14
```

And after link disable/enable:

```
networkctl status eth0
* 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/eth0.network
            Type: ether
           State: routable (configured)
            Path: platform-4a064c00.ehci-usb-0:1.1:1.0
          Driver: smsc95xx
          Vendor: Standard Microsystems Corp.
           Model: SMSC9512/9514 Fast Ethernet Adapter
      HW Address: 00:56:b3:04:cb:e5
             MTU: 1500
         Address: 192.168.11.151
                  fe80::256:b3ff:fe04:cbe5
         Gateway: 192.168.11.1
             DNS: 10.1.1.14
```

+1 on this. I think this may be the root cause of [#2365](https://github.com/systemd/systemd/issues/2365). While sniffing the wire, I see no Router Solicitation is sent out upon link up,  and IPv6 will remains unconfigured even after next RA is received.

**Comment by cvmiller** [comment]
Retested link up/down with systemd 229-3 (on Arch). Same result, IPv6 addresses are dropped, do not return when RA is received from router.

**Comment by ssahani** [comment]
I am not sure does this release contains this patch ?

**Comment by gfa** [comment]
is not on debian's 230-1,  @poettering  do you plan to make this part of a release soon? tnx

**Comment by cvmiller** [comment]
Retested in 231 on Arch. Passed

```
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

Output of test:

```
ip link set eth0 down
[63483.405578] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[root@alarm alarm]# ip link set eth0 up
[63484.476135] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[root@alarm alarm]# 
Waiting: [63486.053436] smsc95xx 1-1.1:1.0 eth0: link up 


Sleeping: 5 
....+ 

, 100Mbps, full-duplex, lpa 0xCDE1
[63486.071502] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1

[root@alarm alarm]# ip addr show eth0 | egrep -v '(/128|fe80)'
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether b6:79:05:58:90:3d brd ff:ff:ff:ff:ff:ff
       valid_lft forever preferred_lft forever
    inet6 2001:470:ebbd:8:a1f7:304:458b:6d5e/64 scope global temporary dynamic 
       valid_lft 7197sec preferred_lft 1797sec
```

**Comment by cvmiller** [comment]
Recommend closing this issue
