### ISSUE TITLE
Collect data from syslog via systemd-journal-remote

### ISSUE THREAD

**Issue by basti122303** [systemd/systemd#29128]
### Component

journalctl

### Is your feature request related to a problem? Please describe

Hello, I have some embedded systems with openWRT for example. OpenWRT can log to a remote server but only in syslog format.

I have try to log to systemd-journal-remote but I get an error about missmached format.

Is the a way to collect logfiles via systemd-journal-remote in syslog format?

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by poettering** [comment]
No this is not available. syslog format is too vaguely defined to be something we would accept from arbitrary peers. Timestamping is just bonkers in syslog.

Hence we only accept the format generated by local glibc, and do our own timestamping.

There are various syslog implementations around that accept syslog traffic from external hosts, and they invest a lot of time in log normalization to deal with this mess. But we won't reproduce this in systemd, sorry. There's no shame in using rsyslog/syslog-ng if you want a proper syslog server.
