### ISSUE TITLE
OnCondFailed

### ISSUE THREAD

**Issue by Cronvs** [systemd/systemd#29144]
### Component

systemd

### Is your feature request related to a problem? Please describe

Would be nice to have the possibility for checking against a service's `ExecCondition`, if it failed or not, for example in conjunction with `Restart=OnCondFailed`.

### Describe the solution you'd like

A `OnCondFailed` or similar option for service configuration which checks if a service failed to execute with respect to `ExecCondition`.

### Describe alternatives you've considered

`ExecStartPre` in conjuction with `OnFailure` does indeed work, but are logged as errors and not sure what the overhead is compared to `ExecCondition`

**Comment by poettering** [comment]
You can build this already, by wrapping your condition in a separate service which you start initially. it then starts the main service via OnSuccess= and your other service on OnFailure=.

I am not convinced we should add speciailist OnConditionFailed= or so, it's too much in fully-turing-complete territory for me.

**Comment by Xavantex** [comment]
If I understand your suggested solution this would still log it as a failure no, while in my case it is expected behavior.

**Comment by Xavantex** [comment]
Actually ingeniously simple. Cheers mate!
