### ISSUE TITLE
No SIP server information in `networkctl status` JSON

### ISSUE THREAD

**Issue by ngkz** [systemd/systemd#29145]
### systemd version the issue has been seen with

253.6

### Used distribution

NixOS 23.05

### Linux kernel version used

6.1.47-hardened1

### CPU architectures issue was seen on

x86_64

### Component

networkctl

### Expected behaviour you didn't see

The output of `networkctl status IFACE --json=XXX` contains SIP server information

### Unexpected behaviour you saw

SIP server information in the output of `networkctl status IFACE --json=XXX` is always empty list

### Steps to reproduce the problem

1. Receive SIP server information from DHCP
2. networkctl status IFACE --json=pretty

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ networkctl status wan_hgw | grep SIP
                           SIP: 192.168.18.1
$ networkctl status wan_hgw --json=pretty | grep SIP
	"SIP" : [],
```

**Comment by yuwata** [comment]
I guess this is already fixed by 8d3c5b39b9bbc89953d1da3e9fbff1524c952ac6.

**Comment by yuwata** [comment]
Fix for v253 is waiting in https://github.com/systemd/systemd-stable/pull/334.

**Comment by yuwata** [comment]
> Fix for v253 is waiting in [systemd/systemd-stable#334](https://github.com/systemd/systemd-stable/pull/334).

Merged. Closing.
