### ISSUE TITLE
Handle system shutdown in applications and program languages RTL

### ISSUE THREAD

**Issue by galaxysite** [systemd/systemd#29146]
### Is your feature request related to a problem? Please describe

Hi,
When system shutdown aplications must handle this. But many developers can not do it. And they doubt the very possibility of this ( https://bugzilla.mozilla.org/show_bug.cgi?id=1837907 ). There is an assumption that need to process the SIGTERM signal, but it does not practically give birth to.
Or don't known, or this feature not implemented in current systemd. In first case need article about it  with example (C, FreePascal,...), in second case need implement it in systemd.
The absence of this leads to data losses for reloading systems.

**Comment by YHNdnzj** [comment]
We emit `PrepareForShutdown` dbus signal before/after initiating the shutdown process: https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#Signals

**Comment by galaxysite** [comment]
Thank You ! I send answer to developers and try in myself applications.

**Comment by poettering** [comment]
SIGTERM is pretty much the UNIX way to get notified about a request to tstop. I am pretty sure that firefox should just hook into that, and not bother with the systemd shutdown logic. firefox should exit cleanly on SIGTERM which will sent for many reasons, including user session end and so on, which is what is key here.

Hence, please ignore the systemd shutdown logic, just handle SIGTERM properly.
