### ISSUE TITLE
broken boot: uuid does not exist

### ISSUE THREAD

**Issue by rottenwheel** [systemd/systemd#29153]
### systemd version the issue has been seen with

253

### Used distribution

Fedora 38

### Linux kernel version used

6.4.14-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

Machine: HP ProBook 455 G8 Notebook PC.
Rebooting or initializing the system after a shutdown stops working, trying with older kernel versions, including the default, doesn't work either.

### Unexpected behaviour you saw

Can't get past the LUKS passphrase input. After a minute or two, following error message is displayed:

```
Warning: /dev/disk/by-uuid/... does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

Press Enter for maintenance
(or press Control-D to continue):
```

rdsosreport.txt timeout error:

```
"/dev/disk/by-uuid/..."
Warning: dracut-initqueue: starting timeout scripts
Warning: dracut-initqueue: timeout, still waiting for following intiqueue hooks:
Warning: /lib/dracut/hooks/initqueue/finished/90-crypt.sh: "[ -c /dev/disk/by-uuid-CRYPT-LUKS7-... ] || exit 1"
Warning: /lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fdisk\x2fby-uuid\x2f...sh: "if ! grep -q After=remote-fs-pre.target /run/systemd/generator/systemd-cryptsetup@#.service 2>/dev/null; then
```

![image](https://github.com/systemd/systemd/assets/92872541/686fbe65-d63b-4dac-a16e-5b3f61c741f5)
![image](https://github.com/systemd/systemd/assets/92872541/f6bd4cf9-d8a4-47e5-b578-90c16f9051a2)

### Steps to reproduce the problem

Just performing a regular reboot, or booting the laptop after it was off would trigger the bug and leave me stuck with it.

**Note**: As a workaround, booted into a Fedora 38 live USB stick, unlocked and mounted the encrypted partition. Edited the crypttab file at /root/etc/ via nano, adding `timeout=0,x-systemd.device-timeout=5m` at the end.

crypttab should look like this: `luks-... UUID=... none discard,timeout=0,x-systemd.device-timeout=5m`

Rebooted into the installed system as I'd normally boot it and it worked. Seems to have fixed the problem for now, will keep monitoring.

**Comment by poettering** [comment]
So what kind of disk is this? Is this referneced in your fstab? Is that disk physically present?

**Comment by rottenwheel** [comment]
@poettering not sure what you mean by what kind of disk it is, just using OEM one: 1 TB PCIe Gen 3 x4 NVMe M.2 TLC SSD. UUID is referenced in fstab, system is running after applying that change to crypttab. Disk has always been physically present.

**Comment by poettering** [comment]
ok, what i meant, that encrypted file system, what's it's purpose? is it listed in fstab? does it actually exist?

apparently dracut waits for the fs to show up, but it never does. it would wait for it, because it's listed in /etc/fstab. But if it doesn#t actually exist, then this will necessary time out.

**Comment by rottenwheel** [comment]
It's the main, daily driver partition. It is listed in fstab, does exist, as I could mount and decrypt it via the live USB.

Raising the systemd timeout seems to have solved the issue for the time being.

**Comment by poettering** [comment]
so, this is purely a timeout problem? the device needs more than 90s to pop up?

**Comment by rottenwheel** [comment]
@poettering Looks like, yes. It's an annoyance to have the booting process break randomly; frightening too, because once it happens, it doesn't stop occuring regardless of how many reboots, different kernel versions or power intake.

Has anyone been able to reproduce?

**Comment by poettering** [comment]
I amsorry, but nvme taking 90s to show up is almost certainly a bug somewhere. nvme is generally blazingly fast.

Anyway, please provide full debug logs of a failing boot, otherwise this is not actionable to us.

**Comment by poettering** [comment]
```
[   17.973523] fedora systemd-cryptsetup[620]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/6be15c97-d417-4102-ad0b-3e27bb0dbb45.
[   20.262217] fedora systemd-cryptsetup[620]: Failed to activate with specified passphrase. (Passphrase incorrect?)
[   29.357563] fedora systemd-cryptsetup[620]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/6be15c97-d417-4102-ad0b-3e27bb0dbb45.
[   31.663710] fedora systemd-cryptsetup[620]: Failed to activate with specified passphrase. (Passphrase incorrect?)
[   55.439806] fedora systemd-cryptsetup[620]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/6be15c97-d417-4102-ad0b-3e27bb0dbb45.
[   57.690944] fedora systemd-cryptsetup[620]: Failed to activate with specified passphrase. (Passphrase incorrect?)
[   57.691323] fedora systemd-cryptsetup[620]: Too many attempts to activate; giving up.
```

Did you try with the correct LUKS password?

**Comment by TriMoon** [comment]
IMHO, this is an issue that is not related to systemd...
I personally am also using root-fs on LUKS2 encrypted partition on a onboard NVMe with no problem at all.
I'm using systemd-boot as boot manager in Secure-Boot mode.

So the OP should check and double check it's configuration wrt unlocking and using the encrypted volume.
Using an encrypted root filesystem on boot is tricky and complex stuff, which needs many steps to work in sequence...
But if it doesn't work it isn't systemd that is causing the problem, otherwise others me included would have the same problem...
