### ISSUE TITLE
DHCPv6 sends IA_NA request instead of IA_PD

### ISSUE THREAD

**Issue by t0mas** [systemd/systemd#29151]
### systemd version the issue has been seen with

249.11-0ubuntu3.9

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-83-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

DHCPv6 requests with "IA_PD" set instead of "IA_NA"

### Unexpected behaviour you saw

I see this in tcpdump:
`21:56:48.217339 IP6 (flowlabel 0xb320c, hlim 1, next-header UDP (17) payload length: 82) fe80::b988:2299:f7fd:33ad.546 > ff02::1:2.547: [udp sum ok] dhcp6 solicit (xid=62f6cf (rapid-commit) (IA_NA IAID:1508121418 T1:0 T2:0) (Client-FQDN) (option-request DNS-server DNS-search-list NTP-server SNTP-servers rapid-commit) (client-ID vid 0000ab114a94cec7) (elapsed-time 318))`

My ISP does not respond to IA_NA, only an IA_PD request is answered.

### Steps to reproduce the problem

I used example 3 from the documentation, on a ppp interface from my ISP:
```[Match]
Name=ppp0
Type=ppp

[Network]
KeepConfiguration=yes
DHCP=ipv6
DHCPPrefixDelegation=yes
IPv6AcceptRA=no

[DHCPv6]
WithoutRA=solicit

[DHCPPrefixDelegation]
UplinkInterface=:self
SubnetId=0
Announce=no```

On the lan side:
```[Match]
Name=v-private
Type=vlan

[Network]
Address=192.168.0.1/24
DHCPPrefixDelegation=yes
IPv6SendRA=yes
IPv6AcceptRA=no

[DHCPPrefixDelegation]
UplinkInterface=ppp0
SubnetId=1
Announce=yes```


### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

**Comment by yuwata** [comment]
Sorry, v249 is too old here. Please contact to your downstream.
Note, since v250 networkd has `UseDelegatedPrefix=`.
