### ISSUE TITLE
systemd-boot clang-16: error: invalid linker name in argument '-fuse-ld=bfd'

### ISSUE THREAD

**Issue by sm-moshi** [systemd/systemd#29165]
### systemd version the issue has been seen with

254.3

### Used distribution

Gentoo

### Linux kernel version used

6.4.14-gentoo-dist

### CPU architectures issue was seen on

aarch64

### Expected behaviour you didn't see

I wanted to compile the Gentoo package `sys-apps/systemd-utils-254.3` with the USE-Flag `boot` which allows me to install systemd-boot aka. bootctl onto my openRC system. I'll attach our discussion on the Gentoo Bugs website also and attach our logs. https://bugs.gentoo.org/914008

The system looks like this:
- MacBook Pro 14" M2 Pro 2023 running UTM as a front-end for QEMU 7.2
- the VM is running the latest `musl llvm profile from Gentoo, so no glibc is included`
- VM: 12 Threads, 14 GB RAM, 128GB /dev/vda containing boot, swap and ext4 as root
- command to install:  `USE="boot" emerge sys-apps/systemd-utils`

Greetings,
Stuart Meya

### Unexpected behaviour you saw

When I compiled it with Clang 16.0.6 on aarch64-gentoo-linux-musl the following error appeared in the log: 
`clang-16: error: invalid linker name in argument '-fuse-ld=bfd'`

Detailed:

`FAILED: src/boot/efi/linuxaa64.elf.stub 
clang  -o src/boot/efi/linuxaa64.elf.stub src/boot/efi/linuxaa64.elf.stub.p/cpio.c.o src/boot/efi/linuxaa64.elf.stub.p/linux.c.o src/boot/efi/linuxaa64.elf.stub.p/splash.c.o src/boot/efi/linuxaa64.elf.stub.p/stub.c.o -Wl,--as-needed -Wl,--no-undefined -pie -fstack-protector -O2 -pipe -march=native -Wl,-O1 -Wl,--as-needed -Wl,--as-needed -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed -Wl,--start-group src/boot/efi/libefiaa64.a -fuse-ld=bfd -lgcc -Wl,--end-group -nostdlib -static-pie -Wl,--entry=efi_main -Wl,--fatal-warnings -Wl,--no-dynamic-linker -z text -z common-page-size=4096 -z max-page-size=4096 -z noexecstack -z norelro -T/var/tmp/portage/sys-apps/systemd-utils-254.3/work/systemd-stable-254.3/tools/elf2efi.lds -Wl,-z,nopack-relative-relocs -fcf-protection=none -fno-asynchronous-unwind-tables -fno-exceptions -fno-unwind-tables -fno-sanitize=all -Wno-unused-command-line-argument
clang-16: error: invalid linker name in argument '-fuse-ld=bfd'`

### Steps to reproduce the problem

- start a Gentoo install ISO (https://www.gentoo.org/downloads/)
- go through the stage3 process picking a musl clang/llvm profile
- try to install sys-apps/systemd-utils with the USE flag `boot` via:
- `cat "sys-apps/systemd-utils boot" >> /etc/portage/package.use/boot`
- `emerge sys-apps/systemd-utils`

### Additional program output to the terminal or log subsystem illustrating the issue

`emerge --info '=sys-apps/systemd-utils-254.3::gentoo'`: https://914008.bugs.gentoo.org/attachment.cgi?id=870320
`emerge -pqv '=sys-apps/systemd-utils-254.3::gentoo'`: https://914008.bugs.gentoo.org/attachment.cgi?id=870321
`/var/tmp/portage/sys-apps/systemd-utils-254.3/temp/build.log`: https://914008.bugs.gentoo.org/attachment.cgi?id=870322

**Comment by sm-moshi** [comment]
@Fuchskaute (https://github.com/Fuchskaute) proposed a quick fix after some testing, but I and I also we from the Gentoo community do think this topic should be addressed with the rising Linux support in Apple Silicon. Hopefully, we can use systemd-boot on bare metal then.

The following would be the gentoo based quick patch:

[disable_forced_bfd.patch](https://github.com/systemd/systemd/files/12580926/disable_forced_bfd.patch)

**Comment by medhefgo** [comment]
We currently, do not support linking sd-boot without bfd, mostly because of https://github.com/llvm/llvm-project/issues/61101.

**Comment by medhefgo** [comment]
Btw, the proper way to not use libgcc is to pass `--rtlib=compiler-rt`.
