### ISSUE TITLE
bootctl --print-esp-path fails, if esp on RAID

### ISSUE THREAD

**Issue by marcusweinhold** [systemd/systemd#29169]
### systemd version the issue has been seen with

254.3

### Used distribution

archlinux

### Linux kernel version used

6.5.2

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl --print-esp-path` prints the esp path

### Unexpected behaviour you saw

```bash
~ # bootctl --print-esp-path
Couldn't find EFI system partition. It is recommended to mount it to /boot or /efi.
Alternatively, use --esp-path= to specify path to mount point.
~ # bootctl --print-esp-path --esp-path=/boot                                                                                                                                                        
File system "/dev/md126" is not located on a partitioned block device.
```

### Steps to reproduce the problem

Install system with ESP located on a RAID1 configured with mdadm:
* have a system with 2 disks, for instance `/dev/nvme0n1` and `/dev/nvme1n1` 
* partition table on each:
  ```
  Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         2099199   1024.0 MiB  EF00  EFI system partition
   2         2099200      1953525134   930.5 GiB   FD00  Linux RAID
   ```
* create a RAID1 on using the 1st partition of each disk
  ```
  mdadm --create --verbose --level=1 --metadata=1.0 --raid-devices=2 /dev/md126 /dev/nvme0n1p1 /dev/nvme1n1p1
  ```
* format the created RAID1 with vfat and install system, mounting the RAID1 to `/boot`

**Comment by poettering** [comment]
This is not supported. ESP must be as VFAT directly on GPT, as firmwares generally do not support RAID1 or any other complex storage like that. 

Note that the firmware VFAT drivers are writable, and various components, including our own sytemd-boot + systemd-stub actually write to it (sparingly, but still do), to maintain an early boot RNG seed and a boot counting.

hence, if firmware and your OS disagree about storage tech used then things will fall apart sooner or later (specifically in your case, on every boot your RAID mirror will be out of sync), and hence we simply don't support that.

You can disable the checks via the SYSTEMD_RELAX_ESP_CHECKS=0 env var, but outside of testing envs that's a pretty bad idea.
