### ISSUE TITLE
bootctl install silently fails when /boot is a zfs dataset

### ISSUE THREAD

**Issue by stackcoder** [systemd/systemd#29176]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12.1 (Bookworm)

### Linux kernel version used

6.1.0-10-amd64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl install --esp-path /var/tmp/espmounts/XXXX-XXXX` copies files from /boot to esp-path and installs EFI loader

### Unexpected behaviour you saw

```bash
> bootctl install --esp-path /var/tmp/espmounts/2020-4AAE
> echo $?
> 1
```

```bash
> SYSTEMD_LOG_LEVEL=debug bootctl install --esp-path /var/tmp/espmounts/2020-4AAE
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Using EFI System Partition at /var/tmp/espmounts/2020-4AAE.
> echo $?
> 1
```

```bash
> SYSTEMD_LOG_LEVEL=debug strace bootctl install --esp-path /var/tmp/espmounts/2020-4AAE &> strace.log
> tail -20 strace.log 
munmap(0x7f36794e9000, 266240)          = 0
munmap(0x7f36794a8000, 266240)          = 0
munmap(0x7f3679467000, 266240)          = 0
close(4)                                = 0
writev(2, [{iov_base="Using EFI System Partition at /v"..., iov_len=59}, {iov_base="\n", iov_len=1}], 2Using EFI System Partition at /var/tmp/espmounts/2020-4AAE.
) = 60
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 3
openat(3, "boot", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 4
newfstatat(4, "", {st_mode=S_IFDIR|0755, st_size=7, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
close(4)                                = 0
openat(AT_FDCWD, "/boot", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 3
faccessat2(3, "trigger", F_OK, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_TYPE|STATX_INO|STATX_MNT_ID, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=STATX_ATTR_MOUNT_ROOT, stx_mode=S_IFDIR|0755, stx_size=7, ...}) = 0
openat(3, ".", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 4
fstatfs(4, {f_type=ZFS_SUPER_MAGIC, f_bsize=131072, f_blocks=4095641, f_bfree=4095091, f_bavail=4095091, f_files=1048343325, f_ffree=1048343312, f_fsid={val=[0xb662774d, 0x906e67]}, f_namelen=255, f_frsize=131072, f_flags=ST_VALID|ST_RELATIME}) = 0
close(4)                                = 0
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

### Steps to reproduce the problem

1. Mount ZFS dataset to `/boot`
2. Execute `bootctl install`

**Comment by stackcoder** [comment]
Maybe this issue is related to #29169

**Comment by poettering** [comment]
is this reproducible with a newer systemd release? i.e. you should get a clear error message about this not being supported.

**Comment by stackcoder** [comment]
As 252 is the latest version available in the Debian repositories, I assume so. But also uncertain about any upstream patches (by Debian maintainers).

Why should placing `/boot` on a separated dataset / or mountpoint be  unsupported?

**Comment by poettering** [comment]
ESP and XBOOTLDR need to be vfat, so that they are accessible from firmware. uefi firmware generally only supports vfat.

**Comment by stackcoder** [comment]
Of course ESP is vfat. Debian is installed on ZFS as root filesystem and the system boots up correctly. So it should be no difference if `/boot` is an *sub folder* on ZFS or a *dataset* it self.

My setup likely the one described in the [Proxmox Wiki - ZFS: Switch Legacy-Boot to Proxmox Boot Tool](https://pve.proxmox.com/wiki/ZFS:_Switch_Legacy-Boot_to_Proxmox_Boot_Tool) or implemented as [script](https://github.com/stackcoder/pve-zol/blob/71c20fe7958cde7571cf6b1f39f1a571eb35363d/install-pve-zol.sh). In this case the ESP contains both EFI Loader *and* Kernel + Initrd.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
