### ISSUE TITLE
Error in the definition of DECIMAL_STR_MAX macro may cause FTBFS

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#2918]
While doing code review of downstream backport I came across the definition of `DECIMAL_STR_MAX` macro. Here it is,

``` C
#define DECIMAL_STR_MAX(type)                                           \
        (2+(sizeof(type) <= 1 ? 3 :                                     \
            sizeof(type) <= 2 ? 5 :                                     \
            sizeof(type) <= 4 ? 10 :                                    \
            sizeof(type) <= 8 ? 20 : sizeof(int[-2*(sizeof(type) > 8)])))
```

I noticed very suspiciously looking use of `sizeof` operator (last one in the macro). It seems like `DECIMAL_STR_MAX` can't really be used with types larger than 8 bytes because systemd will fail to compile.

Here is the minimal reproducer I used to confirm the hypothesis, 

``` C
#include <stdio.h>

#define DECIMAL_STR_MAX(type)                                           \
        (2+(sizeof(type) <= 1 ? 3 :                                     \
            sizeof(type) <= 2 ? 5 :                                     \
            sizeof(type) <= 4 ? 10 :                                    \
            sizeof(type) <= 8 ? 20 : sizeof(int[-2*(sizeof(type) > 8)])))

int main(void) {
        printf("%d\n", DECIMAL_STR_MAX(unsigned __int128));
        return 0;
}
```

```
[msekleta@thinkpad-t500 tmp]$ gcc sizeof.c 
sizeof.c: In function ‘main’:
sizeof.c:10:9: error: size of unnamed array is negative
         printf("%d\n", DECIMAL_STR_MAX(unsigned __int128));
```

I think that `DECIMAL_STR_MAX` is unlikely to be used with such type in systemd code anyway. Hence I propose to replace `sizeof` computation with `LINE_MAX` for large numeric types. `macro.h` contains quite a lot of cleverness for my taste already.

**Comment by keszybz** [comment]
I'd rather change it to something that produces an error. If anyone ever wants to use DECIMAL_STR_MAX with something bigger, they will have to extend the definition.

`sizeof(int[-1])` ?

**Comment by msekletar** [comment]
Current code produces an error, so nothing needs to change in order to achieve that, but my point was to actually prevent build failure and instead return sensible default (`LINE_MAX`) for bigger types.

**Comment by poettering** [comment]
The code is supposed to be a static assert that makes the build fail if you build things on systems with larger types than 64bit.

In other words: if this fails, then the thing that is supposed to happen happens. And the right fix is to add the missing and correct mapping then, and not hide the problem already now by using a much too large size...

Or in other words, there's really nothing to fix here.

**Comment by poettering** [comment]
Your test case uses the gcc __int128 type. Does that type have support in printf formatters? If so, then i figure it would be time to also cover 16byte types in the macro now.

**Comment by msekletar** [comment]
> Your test case uses the gcc __int128 type. Does that type have support in printf formatters?

I don't think there is glibc support for that. I guess that closing this one is fair enough then.

**Comment by poettering** [comment]
OK, if the printf formatter doesnt do 128bit integers yet, then there's no point in covering it in DECIMAL_STR_MAX yet, after all that macro's primary purpose is to size buffers for printf buffers...

As soon as glibc's printf() learns support for 128bit integers (and we start making use of them in systemd) we should revisit this however. But due to the macro's definition the build will automatically fail the moment we come to that point.
