### ISSUE TITLE
Hibernate is refused with "Not enough space" but there is

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#29189]
### systemd version the issue has been seen with

254.3

### Used distribution

Arch Linux

### Linux kernel version used

6.5.3-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

`systemctl hibernate` should hibernate, but it refuses.

/sys/power/resume is populated, but notably not with the device specified on the kernel command line: /dev/dm-0 is a luks volume on top of /dev/nvme1n1p2, /swap/swapfile is a plain 16G swapfile on a btrfs subvolume. resume=/resume_offset= were specified manually on the kernel command line.

### Unexpected behaviour you saw

```
$ systemctl hibernate
Call to Hibernate failed: Not enough swap space for hibernation
```

### Steps to reproduce the problem

```
$ cat /proc/swaps 
Filename				Type		Size		Used		Priority
/swap/swapfile                          file		16777212	0		-2
$ findmnt -n /swap 
/swap /dev/mapper/root[/swap] btrfs  rw,noatime,ssd,space_cache=v2,subvolid=261,subvol=/swap
$ tr ' ' '\n' </proc/cmdline | grep resume
resume=/dev/disk/by-label/root
resume_offset=139654701
$ cat /sys/power/{resume,resume_offset}
259:3
139654701
$ sudo cryptsetup status /dev/disk/by-label/root
/dev/disk/by-label/root is active and is in use.
  type:    LUKS2
  cipher:  aes-xts-plain64
  keysize: 512 bits
  key location: keyring
  device:  /dev/nvme1n1p2
  sector size:  4096
  offset:  32768 sectors
  size:    3999737856 sectors
  mode:    read/write
  flags:   discards no_read_workqueue no_write_workqueue
$ realpath /sys/dev/block/$(</sys/power/resume)
/sys/devices/pci0000:00/0000:00:06.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p2
$ stat -c %n$'\t'%Hr:%Lr /dev/nvme1n1p2 /dev/dm-0
/dev/nvme1n1p2	259:3
/dev/dm-0	254:0
```
Then,
```
$ systemctl hibernate
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ systemctl service-log-level systemd-logind.service debug
$ journalctl --no-hostname -b -u systemd-logind -f
[...]
Sep 15 17:53:11 systemd-logind[736]: Got message type=method_call sender=:1.98 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=HibernateWithFlags  cookie=4 reply_cookie=0 signature=t error-name=n/a error-message=n/a
Sep 15 17:53:11 systemd-logind[736]: Sleep mode "disk" is supported by the kernel.
Sep 15 17:53:11 systemd-logind[736]: Disk sleep mode "platform" is supported by the kernel.
Sep 15 17:53:11 systemd-logind[736]: /swap/swapfile: detection of swap file offset on Btrfs is not supported
Sep 15 17:53:11 systemd-logind[736]: /swap/swapfile: is a candidate device.
Sep 15 17:53:11 systemd-logind[736]: No swap partitions or files matching resume config were found in /proc/swaps.
[...]
```

**Comment by rpigott** [comment]
Upon further investigation, the /dev/disk/* paths aren't actually supported for the resume= target by the kernel. I'm not sure why /sys/power/resume was populated at all in that case, but I don't think it is systemd's fault. Closing.

**Comment by poettering** [comment]
our hibernation logic does not support swap files on btrfs right now. (there's an RFE bug open about that somewhere). It hence won't consider your swap files as suitable candidates and then come to the conclusion that there's not enough suitable swap place around.

**Comment by rpigott** [comment]
@poettering In this case resume= and resume_offset= were specified in advance on the kernel command line — systemd _did_ find a suitable candidate because `find_hibernate_location` specifically allows this case, choosing to trust the explicit offset in /sys/power/resume_offset over fiemap, and it records `/swap/swapfile: is a candidate device` in the log. Btrfs swap files may be unsupported, but I don't think that diagnosis is correct. It seems like all the necessary logic is there.

If I strace logind it's clear we reach `btrfs_get_block_device_at`, systemd determines that /swap/swapfile belongs to device /dev/mapper/root and (correctly) records its dev type 254:0 in the swap_devno, however /sys/power/resume is 259:3, which corresponds to the real block devices under the the luks volume.

```
$ sudo strace -e trace=%stat,%fstat -v -e decode-fds=path -p `pgrep systemd-logind`
[...]
newfstatat(39</swap/swapfile>, "", {st_dev=makedev(0, 0x28), st_ino=257, st_mode=S_IFREG|0600, [...]}, AT_EMPTY_PATH) = 0
newfstatat(AT_FDCWD</>, "/dev/mapper/root", {[...], st_rdev=makedev(0xfe, 0), [...]}, 0) = 0 # rdev=254:0
```
```
$ realpath /sys/dev/block/254:0                
/sys/devices/virtual/block/dm-0
$ realpath /sys/dev/block/$(</sys/power/resume)
/sys/devices/pci0000:00/0000:00:06.0/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
```
259:3 != 254:0, so `location_is_resume_device` returns false and we get kicked out here: https://github.com/systemd/systemd/blob/8fbf0a214e2fe474655b17a4b663122943b55db0/src/shared/sleep-util.c#L873-L875

Seems like that would happen with or without btrfs, no? It's apparently tripped up by luks instead. I'm not actually sure why /sys/power/resume == 259:3. Originally I had `resume=/dev/disk/by-label/root` which I determined is not supported by linux. Changing it to `resume=LABEL=root`, which is supported has the behavior though. Changing it to `resume=/dev/dm-0` actually changes /sys/power/resume == 254:0, in which case `systemctl hibernate` works as intended.

What I don't understand is why resume=LABEL=root yields /sys/power/resume == 259:3 instead of 254:0 when
```
$ stat -Lc %Hr:%Lr /dev/disk/by-label/root 
254:0
```
It seems to me that is a bug in either Linux or systemd.
