### ISSUE TITLE
systemd-journald floods dmesg. 

### ISSUE THREAD

**Issue by rewolff** [systemd/systemd#29182]
### systemd version the issue has been seen with

123

### Used distribution

ubuntu 20.04

### CPU architectures issue was seen on

aarch64

### Component

systemd-journald

### Expected behaviour you didn't see

rate limit of error messages. At least not loop as fast as possible spewing messages. 

### Unexpected behaviour you saw

Journald apparently couldn't open a journal: No space on device. 
It then looped and caused a message in the system log (dmesg) indicating that this was the case. From the timestamps it seems I got a duplcate of this message more than 1000 times each second. 

### Steps to reproduce the problem

Fill up your root partition probably works. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Note: I cleared some space and rebooted the machine. It did not come back up in a timely manner (and I'm not near the machine to debug). So I don't have access to kernel version or stuff like that. Hardware is "Odroid-HC4".
```

**Comment by yuwata** [comment]
Should be already fixed by 8522691d4dafda542a65b1113128ac7d689302ac (v253).

Closing, as the report does not contain valid version number.
