### ISSUE TITLE
Failed to start up manager

### ISSUE THREAD

**Issue by D3vil0p3r** [systemd/systemd#29191]
### systemd version the issue has been seen with

254.3

### Used distribution

Arch Linux

### Linux kernel version used

linux-zen 6.5.3.zen1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Boot by Arch-based ISO to live environment with no systemd error.

### Unexpected behaviour you saw

I created a Arch-based ISO by Archiso some day after the release of latest version of systemd. When I mount the ISO the first time on VMware Workstation, and I run the VM, I get:
![image](https://github.com/systemd/systemd/assets/83867734/6424ce19-cbff-4214-8653-cd002ee1e6d5)

Note that my system uses zRAM. I don't know if it can cause some conflicts with the latest version of systemd. I say this because of https://bbs.archlinux.org/viewtopic.php?id=284565

### Steps to reproduce the problem

Generate an ISO by Archiso by installing also systemd as package. Once the ISO has been created, mount it on VMware.

**Comment by YHNdnzj** [comment]
Please boot with `systemd.log_level=debug` set in kernel cmdline and attach the logs. There's currently too little information for any investigation.

**Comment by D3vil0p3r** [comment]
I set it as shown in the image:
![image](https://github.com/systemd/systemd/assets/83867734/5f5370a7-5d15-4929-80ab-710755ff8eae)

but I don't still see relevant logs:
![image](https://github.com/systemd/systemd/assets/83867734/1839e39e-54e8-47d3-b2c3-340d137d53ed)

**Comment by D3vil0p3r** [comment]
I set systemd kernel params like:
![image](https://github.com/systemd/systemd/assets/83867734/ef1b8e11-365d-4a2c-b429-360f014eab9e)

and now the output is:
![image](https://github.com/systemd/systemd/assets/83867734/d4fee724-57d0-4b8e-9b8d-c2968866795f)

**Comment by YHNdnzj** [comment]
Hmm, it seems that the `60-flatpak-system-only` environment generator timed out.

**Comment by D3vil0p3r** [comment]
> 60-flatpak-system-only

How can I remove it?

**Comment by YHNdnzj** [comment]
> > 60-flatpak-system-only
> 
> How can I remove it?

It should be located under `/usr/lib/systemd/system-environment-generators/`.

**Comment by D3vil0p3r** [comment]
> > > 60-flatpak-system-only
> > 
> > 
> > How can I remove it?
> 
> It should be located under `/usr/lib/systemd/system-environment-generators/`.

Do you think it could be the cause of this issue?
Meanwhile I try to remove the package ([malcontent](https://archlinux.org/packages/extra/x86_64/malcontent/)) that uses flatpak as dependency of the ISO since it generates this file.

**Comment by YHNdnzj** [comment]
> > > > 60-flatpak-system-only
> > > 
> > > 
> > > How can I remove it?
> > 
> > It should be located under `/usr/lib/systemd/system-environment-generators/`.
> 
> Do you think it could be the cause of this issue?
> Meanwhile I try to remove the package ([malcontent](https://archlinux.org/packages/extra/x86_64/malcontent/)) that uses flatpak as dependency of the ISO since it generates this file.

The direct cause of manager failing to start should be that the generator times out. But whether that relates to the recent changes in systemd is unknown yet.

**Comment by D3vil0p3r** [comment]
Ok. I will generate a new ISO without this component and I let you know. But the second last ISO that has been generated before the date of the latest update of systemd Arch package worked well also with that flatpak generator.

**Comment by D3vil0p3r** [comment]
It seems to not block there anymore, now it stucks at:
![image](https://github.com/systemd/systemd/assets/83867734/5d2a54b4-f9e1-4208-b3e0-b12d0341210d)

**Comment by YHNdnzj** [comment]
Now I suspect that there's something really wrong going on in your custom ISO environment...

**Comment by D3vil0p3r** [comment]
> Now I suspect that there's something really wrong going on in your custom ISO environment...

I did some tests. It should be probably a bug on the Linux kernel. If I use `linux` or `linux-zen` 6.5.x version, I get an high CPU load and also this very long Rebuild Dynamic Linker Cache job. If I use `linux-lts` no.
