### ISSUE TITLE
Journal seeking broken in v254

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#29216]
### systemd version the issue has been seen with

254.3-1

### Used distribution

Arch Linux

### Linux kernel version used

6.5.3-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Assuming the journal is not empty, stepping to the previous entry after seek_tail always works.

### Unexpected behaviour you saw

`seek_tail` > `previous` > `seek_tail` > `previous` encounters an EOF, see reproducer.

### Steps to reproduce the problem

```c
#include <systemd/sd-journal.h>
#include <stdio.h>

#define dbg(x) do { int ret = (x); printf(#x " returned %d\n", ret); } while (0)

int main (void) {
    sd_journal *j;
    dbg(sd_journal_open(&j, 0));
    dbg(sd_journal_seek_tail(j));
    dbg(sd_journal_previous(j));
    dbg(sd_journal_seek_tail(j));
    dbg(sd_journal_previous(j));
    return 0;
}
```

outputs:

```
sd_journal_open(&j, 0) returned 0
sd_journal_seek_tail(j) returned 0
sd_journal_previous(j) returned 1
sd_journal_seek_tail(j) returned 0
sd_journal_previous(j) returned 0
```

The second `sd_journal_previous` did not manage to move the cursor.

**Comment by heftig** [comment]
Seems to be the issue that broke GNOME Logs (https://gitlab.gnome.org/GNOME/gnome-logs/-/issues/67)

**Comment by yuwata** [comment]
Fix is waiting in #29235.

**Comment by yuwata** [comment]
Maybe, related to https://bugzilla.redhat.com/show_bug.cgi?id=2234710.

**Comment by dtardon** [comment]
> Maybe, related to https://bugzilla.redhat.com/show_bug.cgi?id=2234710.

Unfortunately not. The bug is still reproducible with this PR.
