### ISSUE TITLE
memory leak in function 'on_method'

### ISSUE THREAD

**Issue by JoraGevorgyan** [systemd/systemd#29222]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
memory is allocated [here](https://github.com/systemd/systemd/blob/701a945e44930b4b0919a9c15ad47fc6e97916a3/src/busctl/busctl.c#L847) and in case of failure of function ['set_put'](https://github.com/systemd/systemd/blob/701a945e44930b4b0919a9c15ad47fc6e97916a3/src/busctl/busctl.c#L872) the memory will left w/o free

**Comment by poettering** [comment]
that static analyzer appears not to understand the gcc `cleanup` attribute.

The `_cleanup_(member_freep)` decorator on the the local variable ensures it is freed when it goes out of scope.
