### ISSUE TITLE
networkd: interface goes into 'failed' state when ndisc is configured before a flap

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#29246]
### systemd version the issue has been seen with

254

### Linux kernel version used

5.14

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

when someone does ip link down/up in a row, sometimes networkd gets in a pickle, because it sends a netlink to configure ndisc just before the interface goes down, and the kernel receives it and returns ENETDOWN just after it has gone down, so then the interface is placed in failed state because a netlink error with ENETDOWN is received here:

https://github.com/systemd/systemd/blob/0d05d1623e1e6c2a26bf7ea8f3eddb8891921d6f/src/network/networkd-ndisc.c#L142
https://github.com/systemd/systemd/blob/0d05d1623e1e6c2a26bf7ea8f3eddb8891921d6f/src/network/networkd-route.c#L1152

```
Could not set NDisc route: Nexthop device is not up. Network is down
Failed
State changed: configuring -> failed
```

Should ENETDOWN be ignored like EEXIST?

**Comment by yuwata** [comment]
@bluca
> Should ENETDOWN be ignored like EEXIST?

The error should not be ignored there, as we should not continue to configure any other settings (routes or so), and the failed route should be re-configured later.

But, yeah, we should make such the error not critical and handle more gracefully. Currently, once we get the error like that, the interface will not be reconfigured even if the interface become up later, but we need to call `networkctl reconfigure INTERFACE`. Maybe, it is better to split the failed state into two, critical and recoverable. Then, when an interface that in the recoverable failed state gains IFF_UP flag or its carrier, we should reconfigure the interface.

**Comment by bluca** [comment]
Got it, thanks
