### ISSUE TITLE
systemd-journal abort when journal capacity exceeded

### ISSUE THREAD

**Issue by klement** [systemd/systemd#2924]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

~> systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

arch linux
### In case of bug report: Expected behaviour you didn't see

shouldn't abort
### In case of bug report: Unexpected behaviour you saw

system froze for a minute or two, checking logs revealed the abort..

Mar 31 10:48:08 ksekera-arch systemd-journald[22207]: System journal (/var/log/journal/) is 62.6M, max 50.0M, 0B free.
Mar 31 10:48:08 ksekera-arch systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=6/ABRT
Mar 31 10:48:08 ksekera-arch systemd[1]: systemd-journald.service: Unit entered failed state.
Mar 31 10:48:08 ksekera-arch systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
Mar 31 10:48:08 ksekera-arch systemd[1]: systemd-journald.service: Service has no hold-off time, scheduling restart.
Mar 31 10:48:08 ksekera-arch systemd[1]: Stopped Flush Journal to Persistent Storage.
Mar 31 10:48:08 ksekera-arch systemd[1]: Stopping Flush Journal to Persistent Storage...
Mar 31 10:48:08 ksekera-arch systemd[1]: Stopped Journal Service.
Mar 31 10:48:08 ksekera-arch systemd[1]: Starting Journal Service...
Mar 31 10:48:08 ksekera-arch systemd-coredump[22194]: Detected coredump of the journal daemon itself, diverted to /var/lib/systemd/coredump/core.systemd-journal.0.4fbf9e25e5c5477e84d616a55806
Mar 31 10:48:08 ksekera-arch systemd-journald[22207]: Journal started
Mar 31 10:48:08 ksekera-arch systemd[1]: Started Journal Service.
Mar 31 10:48:07 ksekera-arch rtkit-daemon[1292]: The canary thread is apparently starving. Taking action.
Mar 31 10:48:07 ksekera-arch rtkit-daemon[1292]: Demoting known real-time threads.
Mar 31 10:48:08 ksekera-arch systemd[1]: Starting Flush Journal to Persistent Storage...
Mar 31 10:48:08 ksekera-arch rtkit-daemon[1292]: Successfully demoted thread 1288 of process 1288 (/usr/bin/pulseaudio).
Mar 31 10:48:08 ksekera-arch rtkit-daemon[1292]: Demoted 1 threads.
Mar 31 10:48:08 ksekera-arch systemd[1]: Started Flush Journal to Persistent Storage.

gdb isn't very helpful:
# lz4 core.systemd-journal.0.4fbf9e25e5c5477e84d616a558068818.338.1459414088000000.lz4

Decoding file core.systemd-journal.0.4fbf9e25e5c5477e84d616a558068818.338.1459414088000000
Successfully decoded 966656 bytes
# gdb core.systemd-journal.0.4fbf9e25e5c5477e84d616a558068818.338.1459414088000000

GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/var/lib/systemd/coredump/core.systemd-journal.0.4fbf9e25e5c5477e84d616a558068818.338.1459414088000000": not in executable format: File format not recognized
### In case of bug report: Steps to reproduce the problem

unknown, didn't happen before

**Comment by evverx** [comment]
> gdb isn't very helpful

Seems like you run

```
gdb /var/lib/systemd/coredump/core.systemd-journal.0.4fbf9e25e5c5477e84d616a558068818.338.1459414088000000
```

Try

```
lz4cat your-core.lz4 >uncompressed-core
gdb path-to-systemd-journald uncompressed-core
```

**Comment by klement** [comment]
oops, my bad ... I don't have the time to build debug packages atm, however...

Reading symbols from /usr/lib/systemd/systemd-journald...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 338]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa23b5f1cdb in __getdents64 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fa23b5f1cdb in __getdents64 () from /usr/lib/libc.so.6
#1  0x00007fa23b5f1892 in readdir64 () from /usr/lib/libc.so.6
#2  0x0000557082347da1 in ?? ()
#3  0x000055708236b956 in ?? ()
#4  0x00005570823619a1 in ?? ()
#5  0x00005570823718b9 in ?? ()
#6  0x0000557082368d53 in ?? ()
#7  0x00005570823422ab in ?? ()
#8  0x00007fa23b55e710 in __libc_start_main () from /usr/lib/libc.so.6
#9  0x0000557082342e69 in ?? ()

**Comment by poettering** [comment]
I fear this is of little help without debug symbols. Please rebuild systemd with debug symbols (minimal debug symbols suffice, like distros like fedora have them enabled by default), and try to retrigger the issue. Otherwise we have to little information to work on.

**Comment by poettering** [comment]
Closing due to lack of response
