### ISSUE TITLE
Network status signaling using /sys/class/leds device

### ISSUE THREAD

**Issue by psztoch** [systemd/systemd#29250]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

Add new config parameters for systemd-networkd with led class device (i.e. /sys/class/leds/blue:network)

Network status configure led:
- off - off/nocarrier
  `echo 0 > /sys/class/leds/blue:network/brightness`
- slow blink - carrier ok, but no address (1000ms on, 1000ms off)
  `echo timer > /sys/class/leds/blue:network/trigger; echo 1000 > ../delay_on; echo 1000 > ../delay_off`
- fast blink - carrier ok, address ok, but no routing (500ms on, 500ms off)
  `echo timer > /sys/class/leds/blue:network/trigger; echo 500 > ../delay_on; echo 500 > ../delay_off`
- on - all is ok
  `echo default-on > /sys/class/leds/blue:network/trigger`

The best solution will be overall leds for overall network status, and optional leds for specified interface in /etc/systemd/network/... configs.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by psztoch** [comment]
Example of use in other project https://github.com/cminyard/ser2net/blob/master/led_sysfs.c

**Comment by yuwata** [comment]
Interesting, but I do not think we should introduce such, as it is only useful for limited cases (I guess, only for real servers and embedded systems).

Note, you can easily implement it by monitoring networkd's DBus property.

**Comment by abielan** [comment]
In my opinion limited case will be quite big.
More and more embedded solutions use systemd. And I guess it's good that it is so.
I would use this functionality in many places. It's a pity you don't want to add it.

**Comment by yuwata** [comment]
One ploblem here that we cannot integrate that to networkd is networkd cannot write sysfs. So, another privileged service is necessary. That's not hard to implement, as networkd (and the kernel) already expose enough API to get the current interface. You can do it.

**Comment by midaczy** [comment]
> In my opinion limited case will be quite big. More and more embedded solutions use systemd. And I guess it's good that it is so. I would use this functionality in many places. It's a pity you don't want to add it.

agree

**Comment by poettering** [comment]
I'd actually be fine with adding something like this.

We shouldn't weaken the networkd sandbox for this though. hence my proposal would be something like this:

1. tiny daemon, socket activated, speaking varlink, with Accept=yes. It just takes a short command what it should configure into the leds sysfs. Then it iterates through udev leds devices, looking for any device marked with some special udev tag. It then makes the changes and exits. 

2. networkd when its overall state changes tries to conenct to that varlink socket. If it works, great, if not it doesn't do anything.

3. if a user wants this on some device, all they'd need to do, is drop-in some udev rule that sets the tag on the led device of their choice, and do "systemctl enable" on that new varlink service, and you are set.

Would probably require somebody to hack this up though.
