### ISSUE TITLE
Allow immediate compression for coredumps

### ISSUE THREAD

**Issue by bobrik** [systemd/systemd#29263]
### Component

systemd-coredump

### Is your feature request related to a problem? Please describe

We have most of our services outside of `system.slice`. Whatever is left shares a 20GiB memory limit and only ~5GiB of it is available with everything else taken. When a coredump for a large process (19GiB RSS) happens, a large coredump is written, which is a ~41GiB file. This file is then compressed.

The problem is that 5GiB is not nearly enough for coredump like this, even when writing on durable storage. We see that the write path is getting completely decimated by memory reclaim:

<img width="1504" alt="image" src="https://github.com/systemd/systemd/assets/89186/d6a0300c-95e5-4513-91bd-fecf3e432336">

In the end it just fails to do the job:

```
Sep 20 13:36:17 52m212 systemd[1]: systemd-coredump@1-77506-0.service: Failed with result 'timeout'.
```

All this time we're in a situation where a big service is not able to serve customer requests and it's not allowed to exit and restart because coredump is ongoing, resulting in traffic disruption. What's worse, we don't even get a coredump at the end of this to investigate, because of the timeout.

If we move the `systemd-coredump@.service` into a separate slice with a generous memory limit, we can see that it happily takes 40GiB+ of memory:

```
ivan@52m217:~$ sudo systemctl status coredump.slice
● coredump.slice - Coredump infrastructure
     Loaded: loaded (/etc/systemd/system/coredump.slice; static)
    Drop-In: /etc/systemd/system.control/coredump.slice.d
             └─50-EarlyHierarchy.conf
     Active: active since Wed 2023-09-20 21:35:58 UTC; 4min 14s ago
      Tasks: 36
     Memory: 43.5G (max: 100.3G swap max: 100.3G available: 56.7G)
        CPU: 2min 51.309s
     CGroup: /coredump.slice
             ├─coredumpd.service
             │ └─1270164 /usr/bin/coredumpd --config /etc/coredumpd.conf
             └─systemd-coredump@1-1283335-0.service
               └─1283337 /lib/systemd/systemd-coredump
```

We can also clearly see two stages of coredump writing:

1. Raw coredump being written:

<img width="1504" alt="image" src="https://github.com/systemd/systemd/assets/89186/dc9e6698-15fc-41f4-a6a0-90e139a7f53c">

```
systemd-c 1418030 root    6u   REG              254,3 45052067840      1600 /var/lib/systemd/coredump/#1600 (deleted)
```

2. Raw coredump is read back and compressed:

<img width="1502" alt="image" src="https://github.com/systemd/systemd/assets/89186/6df5e6da-9f0c-442e-b6e7-2f4457c28e40">

```
systemd-c 1418030 root    6u   REG              254,3 45052067840      1600 /var/lib/systemd/coredump/#1600 (deleted)
systemd-c 1418030 root    7u   REG              254,3  1769760992      1605 /var/lib/systemd/coredump/#1605 (deleted)
```

The sizes above are just before the coredump process is complete, so we're looking at 25x compression ration with zstd.

### Describe the solution you'd like

There is already code in `systemd-coredump` to deal with coredumps on tmpfs, where it can compress on the fly:

* https://github.com/systemd/systemd/blob/v254/src/coredump/coredump.c#L469-L479

This is from #19166 (cc @bluca).

I suggest we add a toggle to let compression happen on the fly from the start. This would save a ton of memory pressure and storage i/o. From my understanding, there wouldn't even be any latency cost, as we don't allow the victim process to exit until compression is complete.

---

I would also argue for an option to add parallel zstd compression. People can control resource usage with service drop-ins if they want to limit how much CPU is getting used by this.

Decompressed coredump from above:

```
$ sudo cat '/var/lib/systemd/coredump/core.edgeworker\x2fsbox.2171.1bccc9a4e64b4f7ebce9284c9c5b2064.424722.1695247541000000.zst' | sudo zstd -d -o /cache/coredump.raw
/*stdin*\           : 45052067840 bytes
```

Reading directly to warm up the page cache (this is on an idle machine with 512GiB of RAM with no memory pressure):

```
$ cat /cache/coredump.raw | pv --average-rate --bytes --timer --width 60 > /dev/null
42.0GiB 0:00:24 [1.73GiB/s]
```

Single thread compression:

```
ivan@52m216:~$ cat /cache/coredump.raw | pv --average-rate --bytes --timer --width 60 | zstd - > /dev/null
42.0GiB 0:01:09 [ 621MiB/s]
```

Multiple threads compression:

```
ivan@52m216:~$ cat /cache/coredump.raw | pv --average-rate --bytes --timer --width 60 | zstd -T0 - > /dev/null
42.0GiB 0:00:35 [1.19GiB/s]
```

Lower wall clock time is better here and we see a 2x speedup. Given that it takes a lot longer to write to actual storage than to compress, I think it's very beneficial to give this sort of toggle.

I'm happy to open a separate feature request for this.

### Describe alternatives you've considered

Currently we're moving coredumps into a separate slice with a high memory limit, but it:

* Wasteful in terms of memory
* Bad in terms of restart latency

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by bluca** [comment]
This was discussed and rejected, and implemented as you noted. You can create a tmpfs on /var/lib/systemd/coredump on boot, and then you'll get the compress-on-the-fly behaviour.

**Comment by bobrik** [comment]
I don't want to waste memory on coredumps, storing them on tmpfs goes directly against that desire.

**Comment by yump** [comment]
@bobrik what about just not using systemd-coredump?

It appears that the coredump is written uncompressed so that the stack trace can be extracted by [this internal library](https://github.com/systemd/systemd/blob/6cd1f6546c6c3709f31b23f16b7f33f3dcbd2cfe/src/shared/elf-util.c#L573) which wants a seekable core file, and logged to the journal.

But if you don't need a stack trace in the journal, and are content with a core file you can load up in gdb at your leisure, drop a new `50-coredump.conf` in `/etc/sysctl.d` to override the one in `/usr/lib/sysctl.d`. Set core_pattern to pipe the core dump to `zstd -T0 -o filename_template.zst`

As an uninvolved third party, my read of that discussion is that the rejection was the result of assuming near-zero cost for disk space, flash write cycles, disk I/O, and the attendant noisy neighbor problems.  But that assumption also seems to be behind many contentious choices in journald, so I don't expect you will find much traction trying to change it.

**Comment by bobrik** [comment]
Not using systemd-coredump is the choice we ended up with eventually.
