### ISSUE TITLE
systemd-resolve doing weird stuff

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#29269]
### systemd version the issue has been seen with

systemd-253.9-1.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

6.5.3 vanilla

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I do not understand why systemd-resolve is sending packets to port 5355 (Link-Local Multicast Name Resolution) to peers on my VPN connection. I though it was reserved strictly for multicast addresses 224.0.0.252 and FF02::1:3.

This makes no sense.

### Unexpected behaviour you saw

Kernel log (from nft):

[systemd-resolve.log](https://github.com/systemd/systemd/files/12686645/systemd-resolve.log)

### Steps to reproduce the problem

Set up a VPN connection.

systemd-resolve occasionally goes haywire.

My daemon conf:

```
/etc/systemd/resolved.conf.d/resolved.conf

[Resolve]
DNS=8.8.8.8#dns.google
DNSSEC=yes
DNSOverTLS=yes
Cache=no-negative
# Never fallback
FallbackDNS=
```

**Comment by poettering** [comment]
when doing reverse name lookups in LLMNR you are supposed to contact the address itself via LLMNR, not send anything to the mcast group. see spec.
