### ISSUE TITLE
ReadWritePaths has no effect if the underlying file system was originally mounted read-only

### ISSUE THREAD

**Issue by mkszuba** [systemd/systemd#29266]
### systemd version the issue has been seen with

253

### Used distribution

Gentoo

### Linux kernel version used

6.1.46

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Let us take a systemd unit containing

ProtectSystem=full
SystemCallFilter=~@mount
ReadWritePaths=-/boot/EFI

and launch it on a system where /boot is mounted read-only. Then have /boot remounted read-write. One would - naively perhaps, as I am not familiar with the internals of Linux filesystem namespaces - expect the running service to automatically picks up on this change and be allowed to write files into /boot/EFI.

The real-life example here is fwupd.service from the eponymous package, which does need write access to the mounted ESP in order to stage UEFI capsules for installation but not for (a large number of) other operations such as checking for updates, listing devices, installing non-capsule updates and so on. See also: https://github.com/fwupd/fwupd/issues/6046 .

### Unexpected behaviour you saw

fwupd continues to report the target file system as read-only until fwupd.service has been restarted.

### Steps to reproduce the problem

* Mount /boot read-only
* Install fwupd
* Start fwupd.service, by running _fwupdmgr get-updates_ for instance
* Remount /boot read-write
* Attempt an fwupd operation expected to write into /boot/EFI, for instance reinstallation of system firmware in the form of a UEFI capsule
* Stop fwupd.service and try the previous step again

**Comment by poettering** [comment]
Hmm, the namespaces are detached, Linux does not allow the mount flags alone to be propagated.

This deserves documentation, but is nothing we can change, Linux semantics are how they are.
