### ISSUE TITLE
man: missing /usr/local/lib config search path

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#29271]
### systemd version the issue has been seen with

254

### Used distribution

n/a

### Linux kernel version used

n/a

### CPU architectures issue was seen on

None

### Component

systemd-modules-load

### Expected behaviour you didn't see

There are some inconsistencies in the documentation.

### Unexpected behaviour you saw

It should be consistent.

### Steps to reproduce the problem

The synopsis on the html render of the man page mentions three paths where conf files may exist:

https://www.freedesktop.org/software/systemd/man/modules-load.d.html#Synopsis

However, the "Configuration Directories and Precedence" section, mentions `/usr/local/lib/`, making it a total of four paths:

https://www.freedesktop.org/software/systemd/man/modules-load.d.html#confd

I checked `man/modules-load.d.xml` in this repository, and it has no mention of `/usr/local` at all. Is the above HTML generated using some different source?

https://github.com/systemd/systemd/blob/main/man/modules-load.d.xml

Running `git log -p man/modules-load.d.xml` doesn't indicate that there was ever any mention of `/usr/local`.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
n/a
```

**Comment by WhyNotHugo** [comment]
Actually, the man pages for arch also mention `/usr/local/lib`: https://man.archlinux.org/man/modules-load.d.5

I see that this is mentioned in a file which is included when generating the man page: https://github.com/systemd/systemd/blob/main/man/standard-conf.xml

So I guess that it's just a matter of adding the missing path to the Synopsis section?

**Comment by yuwata** [comment]
> So I guess that it's just a matter of adding the missing path to the Synopsis section?

Yeah, I think so.
