### ISSUE TITLE
journalctl -b NUM shows off-by-one entry

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#29275]
### systemd version the issue has been seen with

254

### CPU architectures issue was seen on

None

### Component

journalctl, systemd-journald

### Expected behaviour you didn't see

`journalctl -b -1` shows the previous boot's journal.

### Unexpected behaviour you saw

https://bugzilla.redhat.com/show_bug.cgi?id=2234710

There's an off-by-one error interpreting the argument of `journalctl -b`, i.e., `journalctl -b -1` shows the log of boot -2, `journalctl -b -2` shows the log of boot -3, and so on. (`journalctl -b 0` works, though.) Bisecting shows its a regression from https://github.com/systemd/systemd/commit/9204fc642acef5cfc3a411fdec3ce9a5fd9f8d37 .

**Comment by yuwata** [comment]
Maybe related to
https://github.com/systemd/systemd/issues/28250#issuecomment-1666514311
https://github.com/systemd/systemd/issues/29167#issuecomment-1730057693

**Comment by jlebon** [comment]
Can we have the fix for this be backported to Fedora 39? It breaks a bunch of our tests that query the journal. (See e.g. https://github.com/cgwalters/ostree/commit/088f12a3514b163badcb830076487a7ca10b05ba and https://github.com/coreos/rpm-ostree/pull/4692#issuecomment-1819139751).
