### ISSUE TITLE
systemd 254.4-1 cant find UUID, cant mount root

### ISSUE THREAD

**Issue by WhitePeace36** [systemd/systemd#29288]
### systemd version the issue has been seen with

254.4-1

### Used distribution

Endeavor os

### Linux kernel version used

6.5.3-273-tkg-eevdf

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

PC should boot up normally.

### Unexpected behaviour you saw

The system didnt boot anymore and was stuck in a shell which i couldn't use because the hardware i tried ,like a keyboard, didnt work. 
Reboots also didn't fix it. I had to boot from a live usb stick and downgrade these packages:  `systemd-sysvcompat systemd-libs systemd lib32-systemd` to the 254.3-1 version to get it to boot again.

But i don't exactly know which one was the culprit because i downgraded all of these packages in one go.

I also sadly have no logs or at least i think i dont have any. (At least not in the journalctl where i looked for uuid) But i can roughly remember the output and it was as follows:

`Couldnt find uuid="f53226fe-96e3-4547-be01-be2efb09ed78". root could not be mounted . dropping into emergency shell. Kernel isn't loaded. Can't start emergency shell.`

And then it opened some shell which i couldn't use and was stuck there.

**Comment by poettering** [comment]
Pleae contact your distro for help first. This looks like an initrd-specific issue, and the initrd is apparently not using systemd. Hence this is simply the wrong place to ask for help.

Please ask Endeavor os for help. If they find an issue with systemd upstream after all, they'll escalate this back to us then.
