### ISSUE TITLE
Backport zsh tab completion fixes to 252 (Debian Stable/Bookworm)

### ISSUE THREAD

**Issue by danalderman** [systemd/systemd#29289]
### Component

systemctl

### Is your feature request related to a problem? Please describe

Tab completion with sudo systemctl hangs up with zsh and oh-my-zsh.

### Describe the solution you'd like

It seems the fix was made in this commit in 254 stable

https://github.com/systemd/systemd-stable/commit/dfc0445cb86e500732125da9f758092641a4c5a2

I have partially tested this by pulling /usr/share/zsh/vendor-completions/_systemctl from a systemd-254 deb in unstable and putting it in place.  So far it works as expected but I have not extensively tested it.  Is it possible to back port the zsh fixes to the 252 stable branch so they make it into Debain stable (bookworm) please?

### The systemd version you checked that didn't have the feature you are asking for

252 stable

**Comment by poettering** [comment]
please file is on the systemd-stable repo, not here.
