### ISSUE TITLE
Rootless (Podman) containers fail to pull or run for Homed-managed users.

### ISSUE THREAD

**Issue by IPlayZed** [systemd/systemd#29297]
### systemd version the issue has been seen with

254.4-1.arch.x86_64

### Used distribution

Arch Linux

### Linux kernel version used

6.5.4-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

homed

### Expected behaviour you didn't see

Rootless containers running correctly under a user managed by homed, just like on a non-homed managed user.

### Unexpected behaviour you saw

It is impossible to run rootless containers (for instance with Podman) for users managed by Homed.

### Steps to reproduce the problem

1. Create a homed managed user.
2. Login to the homed managed user.
3. Install Podman.
4. Ensure that rootless Podman is configured correctly.
5. Try pulling an image, for instance: `podman pull quay.io/pypa/manylinux2010_x86_64:latest`.
6. `Error: writing blob: adding layer with blob "sha256:5f017a04f42a1aff95e44de723588e2fa7bfc1801eac3734e6d973f9704b6f1a": processing tar file(lchown /usr/libexec/utempter: value too large for defined data type): exit status 1`

**Comment by IPlayZed** [comment]
This issue is a followup of [the one I created under Podman](https://github.com/containers/podman/issues/20040).

**Comment by IPlayZed** [comment]
The output of `userdbctl` seems to show that container UIDs begin at 524288, which is supposed to be good according to the [Arch Wiki](https://wiki.archlinux.org/title/Podman#Set_subuid_and_subgid), although the referenced source points to a deleted Reddit post, I do not know _why_ is that good, but the GIDs are not set (again, no idea if they should be) :

```
   NAME                           DISPOSITION        UID   GID REALNAME                         HOME                     SHELL
   root                           intrinsic            0     0 -                                /root                    /bin/bash
┌─ ↓ begin system users ↓         system               1     - First system user                -                        -
   bin                            system               1     1 -                                /                        /usr/bin/nologin
   daemon                         system               2     2 -                                /                        /usr/bin/nologin
   mail                           system               8    12 -                                /var/spool/mail          /usr/bin/nologin
   ftp                            system              14    11 -                                /srv/ftp                 /usr/bin/nologin
   rpc                            system              32    32 Rpcbind Daemon                   /var/lib/rpcbind         /usr/bin/nologin
   http                           system              33    33 -                                /srv/http                /usr/bin/nologin
   clamav                         system              64    64 Clam AntiVirus                   /                        /usr/bin/nologin
   uuidd                          system              68    68 -                                /                        /usr/bin/nologin
   dbus                           system              81    81 System Message Bus               /                        /usr/bin/nologin
   polkitd                        system             102   102 PolicyKit daemon                 /                        /usr/bin/nologin
   gdm                            system             120   120 Gnome Display Manager            /var/lib/gdm             /usr/bin/nologin
   rtkit                          system             133   133 RealtimeKit                      /proc                    /usr/bin/nologin
   usbmux                         system             140   140 usbmux user                      /                        /usr/bin/nologin
   nvidia-persistenced            system             143   143 NVIDIA Persistence Daemon        /                        /usr/bin/nologin
   cups                           system             209   209 cups helper user                 /                        /usr/bin/nologin
   fwupd                          system             951   951 Firmware update daemon           /var/lib/fwupd           /usr/bin/nologin
   systemd-journal-upload         system             953   953 systemd Journal Upload           /                        /usr/bin/nologin
   saned                          system             955   955 SANE daemon user                 /                        /usr/bin/nologin
   mysql                          system             956   956 MariaDB                          /var/lib/mysql           /usr/bin/nologin
   sddm                           system             958   958 Simple Desktop Display Manager   /var/lib/sddm            /usr/bin/nologin
   nm-openconnect                 system             960   960 NetworkManager OpenConnect       /                        /usr/bin/nologin
   openvpn                        system             961   961 OpenVPN                          /                        /usr/bin/nologin
   nm-openvpn                     system             962   962 NetworkManager OpenVPN           /                        /usr/bin/nologin
   dnsmasq                        system             963   963 dnsmasq daemon                   /                        /usr/bin/nologin
   qemu                           system             964   964 QEMU user                        /                        /usr/bin/nologin
   libvirt-qemu                   system             965   965 Libvirt QEMU user                /                        /usr/bin/nologin
   gluster                        system             966   966 GlusterFS daemons                /var/run/gluster         /usr/bin/nologin
   git                            system             968   968 git daemon user                  /                        /usr/bin/git-shell
   geoclue                        system             969   969 Geoinformation service           /var/lib/geoclue         /usr/bin/nologin
   flatpak                        system             970   970 Flatpak system helper            /                        /usr/bin/nologin
   colord                         system             971   971 Color management daemon          /var/lib/colord          /usr/bin/nologin
   brltty                         system             972   972 Braille Device Daemon            /var/lib/brltty          /usr/bin/nologin
   avahi                          system             973   973 Avahi mDNS/DNS-SD daemon         /                        /usr/bin/nologin
   tss                            system             975   975 tss user for tpm2                /                        /usr/bin/nologin
   systemd-timesync               system             976   976 systemd Time Synchronization     /                        /usr/bin/nologin
   systemd-resolve                system             977   977 systemd Resolver                 /                        /usr/bin/nologin
   systemd-journal-remote         system             978   978 systemd Journal Remote           /                        /usr/bin/nologin
   systemd-oom                    system             979   979 systemd Userspace OOM Killer     /                        /usr/bin/nologin
   systemd-network                system             980   980 systemd Network Management       /                        /usr/bin/nologin
   systemd-coredump               system             981   981 systemd Core Dumper              /                        /usr/bin/nologin
└─ ↑ end system users ↑           system             999     - Last system user                 -                        -
   developer-no-homed             regular           1000  1000 developer (not Homed managed)    /home/developer-no-homed /bin/bash
┌─ ↓ begin systemd-homed users ↓  regular          60001     - First systemd-homed user         -                        -
   gaming                         regular          60197 60197 Börcsök Balázs Róbert (gaming)   /home/gaming             /bin/bash
   admin                          regular          60282 60282 Börcsök Balázs Róbert (admin)    /home/admin              /bin/bash
   personal                       regular          60311 60311 Börcsök Balázs Róbert (personal) /home/personal           /bin/bash
└─ ↑ end systemd-homed users ↑    regular          60513     - Last systemd-homed user          -                        -
┌─ ↓ begin mapped users ↓         regular          60514     - First mapped user                -                        -
└─ ↑ end mapped users ↑           regular          60577     - Last mapped user                 -                        -
┌─ ↓ begin dynamic system users ↓ dynamic          61184     - First dynamic system user        -                        -
└─ ↑ end dynamic system users ↑   dynamic          65519     - Last dynamic system user         -                        -
   nobody                         intrinsic        65534 65534 Kernel Overflow User             /                        /usr/bin/nologin
┌─ ↓ begin container users ↓      container       524288     - First container user             -                        -
└─ ↑ end container users ↑        container   1878982656     - Last container user              -                        -

46 users listed.
```

**Comment by IPlayZed** [comment]
I have also seen issue #21952, but I am not sure if it is closed and the merge was supposed to fix this.

**Comment by poettering** [comment]
if you allocate your subuids from the container range (i.e. 54288…1878982656) it should really just work. 

Which range did you use?

**Comment by IPlayZed** [comment]
> if you allocate your subuids from the container range (i.e. 54288…1878982656) it should really just work.
> 
> Which range did you use?

Sorry, I am not exactly sure what do you mean by which range I used, I did not set anything manually regarding that.

**Comment by IPlayZed** [comment]
The subuid and subguid configuration files contain the following:
```
~ 
❯ sudo bat /etc/subgid-
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/subgid-
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ admin:100000:65536
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~ 
❯ sudo bat /etc/subuid 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/subuid
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ admin:100000:65536
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by IPlayZed** [comment]
> if you allocate your subuids from the container range (i.e. 54288…1878982656) it should really just work.
> 
> Which range did you use?

Hi, I have provided feedback to your question, is there further information needed?
Again, I would like to emphasize that I did not poke around any UUID or SUBUID range manually, I just installed Podman and try to pull and use an image, but it does **not** work, only for systemd-homed.

**Comment by IPlayZed** [comment]
@poettering 
Lilipod also seems to be broken:

```
lilipod run --rm -ti alpine cat /etc/os-release
cannot extract agent: exit status 2: tar: pty: Cannot change ownership to uid 1000, gid 1000: Value too large for defined data type
tar: Exiting with failure status due to previous errors

pulling image manifest: index.docker.io/library/alpine:latest
pulling layer 96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa.tar.gz
Copying blob sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa 100% |██████████████████████████████| (5.6 MB/s)        
saving layer sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa done
saving manifest for index.docker.io/library/alpine:latest
saving config for index.docker.io/library/alpine:latest
saving metadata for index.docker.io/library/alpine:latest
done
2023/11/22 22:48:41 exit status 2
2023/11/22 22:48:41 exit status 1
2023/11/22 22:48:41 exit status 1
```
I will try Docker as well.

**Comment by IPlayZed** [comment]
> @poettering Lilipod also seems to be broken:
> 
> ```
> lilipod run --rm -ti alpine cat /etc/os-release
> cannot extract agent: exit status 2: tar: pty: Cannot change ownership to uid 1000, gid 1000: Value too large for defined data type
> tar: Exiting with failure status due to previous errors
> 
> pulling image manifest: index.docker.io/library/alpine:latest
> pulling layer 96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa.tar.gz
> Copying blob sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa 100% |██████████████████████████████| (5.6 MB/s)        
> saving layer sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa done
> saving manifest for index.docker.io/library/alpine:latest
> saving config for index.docker.io/library/alpine:latest
> saving metadata for index.docker.io/library/alpine:latest
> done
> 2023/11/22 22:48:41 exit status 2
> 2023/11/22 22:48:41 exit status 1
> 2023/11/22 22:48:41 exit status 1
> ```
> 
> I will try Docker as well.

Docker seems to work normally.
It looks like Lilipad and Podman does stuff which is not compatible.
But again, if they don't want to fix it... It should probably be fixed here, it is a check-mat otherwise for the user :(

**Comment by IPlayZed** [comment]
After googling random pages, I found a hackaround based on [this guide](https://wiki.archlinux.org/title/User:Bai-Chiang/Rootless_podman_with_LinuxServer.io_nextcloud_and_SWAG_images).

I added the line `homeduser:524288:65536` to `/etc/subuid` and `/etc/subgid` files, where _homeuder_ is your homed managed user. Ran `podman system migrate` and `sudo podman system migrate`. Voilá, it works now.

Everything Podman, Lilipod, etc. works now.

Why is this not the default?

**Comment by cryobry** [comment]
Seems like a distro or packaging problem? I don't know if /etc/subuid and /etc/subgid can be touched by the package manager but it would make sense to add these entries as defaults or append them when systemd-homed is installed.

**Comment by IPlayZed** [comment]
> Seems like a distro or packaging problem?

Why would it be?

**Comment by lakano** [comment]
> I added the line `homeduser:524288:65536` to `/etc/subuid` and `/etc/subguid` files, where _homeuder_ is your homed managed user. Ran `podman system migrate` and `sudo podman system migrate`. Voilá, it works now.
> 
> Everything Podman, Lilipod, etc. works now. 

Thank you! You save me a lot of hours to make it works!

> Why is this not the default?
>
I thought this should be injected dynamically per systemd-homed at login time, because if you host your homed on a USB key, this make sense that the new computer doesn't yet known you.

**Comment by IPlayZed** [comment]
@lakano
> I thought this should be injected dynamically per systemd-homed at login time, because if you host your homed on a USB key, this make sense that the new computer doesn't yet known you.

Yes, I think that is a good idea for that use case. In addition there might should be some attribute maybe which defines if a given user should be able to access it. The question is, should the host computer first apply it, similar to the concept of adding the user to a group on the system.

**Comment by poettering** [comment]
Let's close this. If the documented uid rnage for containers is used things should generally just work, as mentioned (https://github.com/systemd/systemd/issues/29297#issuecomment-1737332269) and then verified (https://github.com/systemd/systemd/issues/29297#issuecomment-1851193496)

Closing.

**Comment by IPlayZed** [comment]
> Let's close this. If the documented uid rnage for containers is used things should generally just work, as mentioned ([#29297 (comment)](https://github.com/systemd/systemd/issues/29297#issuecomment-1737332269)) and then verified ([#29297 (comment)](https://github.com/systemd/systemd/issues/29297#issuecomment-1851193496))
> 
> Closing.

@poettering I still do not get it, maybe it is bc I am misunderstanding something:

- Is this supposed to work out of the box?
- If not, how do I "allocate my subuids from the container range (i.e. 54288…1878982656)" when I use a container? Do I do something when I create a rootles Podman container or what? Should _I the end-user_ do something, or is this something the maintainer of the container or Podman should be aware of?

Gnome is implementing Homed support to work out of the box. I wonder how many people who use containers will start reporting bug reports if Homed goes mainstream.

**Comment by poettering** [comment]
I don't really know podman. In systemd we have defined UID ranges for various purposed. newuidmap/podman do their own thing however. 

they really should allocate their subuid ranges from the ranges we document, otherwise it's always going to be a mess...

**Comment by IPlayZed** [comment]
I see, so for using homed and rootless containers via Podman-like solutions, the user will need to tweak `/etc/subuid` and `/etc/subgid`. I thought maybe adding an experimental flag when creating the user to auto-fill these entries as a compatibility fix would make sense.

Btw I do agree with the fact that Podman is the black sheep here, but if both projects wontfix, it will be a broken use-case.

**Comment by tv42** [comment]
Isn't manually tweaking `/etc/subuid` against the point of using `systemd-homed`?

**Comment by IPlayZed** [comment]
> Isn't manually tweaking `/etc/subuid` against the point of using `systemd-homed`?

The problem is that both maintainers of these project have their own views on how their corresponding projects should handle this issue.

Now as a fellow developer (on other projects), I think that everyone should strive to satisfy users by default. For instance, Podman was not made in mind of Homed, and vica versa. Ideally the maintainers would communicate directly with each other to get to a solution, but in this case neither of them do sadly.

Now as SystemD is "under" user space, even for new feature in my opinion, it should not break it, or if it does and it has such an easy solution, it should offer this as a workaround. This would not be the first.

You can of course talk about what goes wrong against a philosophy, but I still want to use my system as I want to (afterall, that is why I am not on Windows here).

Also, I think Homed is especially good for immutable systems, but of course those immutable systems rely on Podman by default to serve local development environments and such. So, I think it would be in the best interest of both projects to work together to solve the issue...

But in reality, none of them will and this will be forgotten, and we will be stuck in 2010 using the same ill-rooted way of managing using even in 2035, because no distro will implement Homed actually if things like this are breaking. At least I can cry about it here.

**Comment by linux-universe** [comment]
> After googling random pages, I found a hackaround based on [this guide](https://wiki.archlinux.org/title/User:Bai-Chiang/Rootless_podman_with_LinuxServer.io_nextcloud_and_SWAG_images).
> 
> I added the line `homeduser:524288:65536` to `/etc/subuid` and `/etc/subguid` files, where _homeuder_ is your homed managed user. Ran `podman system migrate` and `sudo podman system migrate`. Voilá, it works now.
> 
> Everything Podman, Lilipod, etc. works now.
> 
> Why is this not the default?

there's a typo, `/etc/subgid`
