### ISSUE TITLE
shutdown hangs if swap is disabled before (full) tmpfs file systems are unmounted

### ISSUE THREAD

**Issue by frankheckenbach** [systemd/systemd#2930]
### Submission type
- [X] Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

229

(Tested with 215, but bug still present in github, as of this writing.)
### Used distribution

Debian
### In case of bug report: Expected behaviour you didn't see

Proper system shutdown
### In case of bug report: Unexpected behaviour you saw

swapoff failed
### In case of bug report: Steps to reproduce the problem

Various possibilities, e.g.:
- Enable swap partition(s)
- Fill /tmp tmpfs with data exceeding physical RAM size
- Try to shut down

Since systemd tries to swapoff before umounting /tmp, the former fails and shutdown hangs.

Longer discussion on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788303
Copied here on request of Felipe Sateler.

A partial fix has been applied in current systemd verisons, what's left to do is to add one ordering:

--- /lib/systemd/system/tmp.mount
+++ /lib/systemd/system/tmp.mount
@@ -13,6 +13,7 @@
 DefaultDependencies=no
 Conflicts=umount.target
 Before=local-fs.target umount.target
+After=swap.target

 [Mount]
 What=tmpfs

**Comment by fsateler** [comment]
Alternatively, all tmpfs mounts could have that dependency added implicitly. It seems there is very little reason to need swap deactivated before tmpfs mounts.

**Comment by poettering** [comment]
I am not convinced we should do this implicitly for all tmpfs. But doing this for /tmp sounds OK. @frankheckenbach could you post your patch as PR please? Will merge then.

**Comment by poettering** [comment]
Closing, as #3087 has been merged.
