### ISSUE TITLE
Systemd does not tell when slices are not applied to units

### ISSUE THREAD

**Issue by dasJ** [systemd/systemd#29305]
### systemd version the issue has been seen with

253

### Used distribution

NixOS 23.05

### Linux kernel version used

6.1.53

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I added my GitLab Runner to a slice which limits resources of the runner and similar units.
The runner did have left-over processes when restarting, causing the option to just be ignored and the runner to be started in the regular system slice.

I would have expected the option to just work or if it's not possible to apply it, I'd love to get a log message that states why.

### Unexpected behaviour you saw

No message that the change wasn't applied and that the cause is a left-over process.

### Steps to reproduce the problem

- Have a unit that leaves processes after stopping
- Add a `Slice=` option with a valid slice
- Restart the service

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 25 14:09:18 helsinki-hydra-builder01 systemd[1]: gitlab-runner.service: Found left-over process 3085073 (ssh-agent) in control group while starting unit. Ignoring.
Sep 25 14:09:18 helsinki-hydra-builder01 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

**Comment by poettering** [comment]
One unit may not have multiple cgroups. Hence as long as at least one process is running we will not migrate the cgroup belonging to a service.

generally, setting KillMode=none or so (to allow such left-over processes) is a bad idea, and will result in problems like yours, hence I am pretty sure we should not consider this a problem, it's effect of a bad choice pretty much, and hence expected.

The man page kinda points to this problem already hence I don't even think there's a documentation issue here:

> If set to none, no process is killed (strongly recommended against!). In this case, only the stop command will be executed on unit stop, but no process will be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless empty.

(That's from systemd.kill(5)).

Hence, closing.
