### ISSUE TITLE
nspawn fails to restart the container

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#2932]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 228
### Used distribution

> openSUSE Leap 42.1
### In case of bug report: Expected behaviour you didn't see

> That an nspawn container comes back up when the `reboot` command was issued from within.
### In case of bug report: Unexpected behaviour you saw

On the host side:

```
11:45 niw-hv03:~ # systemctl status systemd-nspawn@iridium
● systemd-nspawn@iridium.service - Container iridium
   Loaded: loaded (/etc/systemd/system/systemd-nspawn@iridium.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2016-04-01 11:45:18 CEST; 11s ago
     Docs: man:systemd-nspawn(1)
  Process: 10288 ExecStart=/usr/bin/systemd-nspawn --keep-unit --boot --network-veth -D /D/machines/iridium-191 -M iridium (code=exited, status=133)
 Main PID: 10288 (code=exited, status=133)
   Status: "Terminating..."

Apr 01 11:45:16 niw-hv03 systemd-nspawn[10288]: [  OK  ] Stopped Remount Root and Kernel File Systems.
Apr 01 11:45:16 niw-hv03 systemd-nspawn[10288]: [  OK  ] Reached target Shutdown.
Apr 01 11:45:16 niw-hv03 systemd-nspawn[10288]: Sending SIGTERM to remaining processes...
Apr 01 11:45:18 niw-hv03 systemd-nspawn[10288]: Sending SIGKILL to remaining processes...
Apr 01 11:45:18 niw-hv03 systemd-nspawn[10288]: Rebooting.
Apr 01 11:45:18 niw-hv03 systemd-nspawn[10288]: Container iridium is being rebooted.
Apr 01 11:45:18 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Main process exited, code=exited, status=133/n/a
Apr 01 11:45:18 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Unit entered failed state.
Apr 01 11:45:18 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Failed with result 'exit-code'.
Apr 01 11:45:18 niw-hv03 systemd[1]: Stopped Container iridium.
```
### In case of bug report: Steps to reproduce the problem

> Issue `reboot` from within the container.

**Comment by poettering** [comment]
Are you using the upstream systemd-nspawn@.service template file? It contains RestartForceExitStatus=133 to ensure that the special exit status 133 results in a service restart. It appears that that line is missing from your unit file, and 133 thus results in service failure.

Can you check if your unit file contains that line?

**Comment by jengelh** [comment]
Spot on, thanks! I now went with replacing `/etc/systemd/system/systemd-nspawn@iridium.service` with a `/etc/systemd/system/systemd-nspawn@iridium.service.d/command.conf` so that the template is not just overriden, but inherited.
