### ISSUE TITLE
Systemd-stub fails to boot if booted by grub on non-efi readable partition

### ISSUE THREAD

**Issue by lufsc** [systemd/systemd#29331]
### systemd version the issue has been seen with

254.4-2

### Used distribution

Arch

### Linux kernel version used

6.5.4-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub

### Expected behaviour you didn't see

I have a UKI generated by ukify, sitting on an ext4 formatted boot partition. As this partition is not readable by my uefi, i would expect systemd-stub to not check for additional files and just boot Linux.

### Unexpected behaviour you saw

 When my UKI is called by grub, grub passes `null` as the `DeviceHandle` in the loaded image protocol. `systemd-stub` asserts the device handle to be non-null, causing the boot to fail, and shows the very non-helpful error message
```
systemd-boot: Assertion 'device' failed at ../systemd-stable/src/boot/efi/part-discovery.c:251@partition_open, halting.
```

### Steps to reproduce the problem

Use the grub `chainloader` command to boot a UKI containing `systemd-stub`, which is loaded from an ext4 partition.

**Comment by lufsc** [comment]
I could make a PR replacing the assert in [`partition_open`](https://github.com/systemd/systemd/blob/5808300c442359aea1ad4c0d1eb3e7717673bd38/src/boot/efi/part-discovery.c#L251) with a check, and returning an error, if it `device` is null. As errors are already ignored in [`run`](https://github.com/systemd/systemd/blob/5808300c442359aea1ad4c0d1eb3e7717673bd38/src/boot/efi/stub.c#L397), this would just cause `systemd-stub` to boot normally.

I don't know, how to test that though, `ukify` doesn't allow me, to specify a custom stub.

**Comment by medhefgo** [comment]
> I don't know, how to test that though, `ukify` doesn't allow me, to specify a custom stub.

It always had the `--stub` option exactly for that.
