### ISSUE TITLE
Systemd tries to stop crypt devices before unmounting file systems

### ISSUE THREAD

**Issue by mahahn** [systemd/systemd#29336]
### systemd version the issue has been seen with

254.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.5.4-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Expected file systems to be unmounted before underlying LUKS volumes are closed. This appeared to be the case prior to systemd version 254.

### Unexpected behaviour you saw

Systemd tries to stop cryptsetup units before unmounting the underlying file system of the device. Resulting in errors in the system journal.

### Steps to reproduce the problem

This appears to only affect encrypted devices other than the root file system. In my case, a swap device and an encrypted data drive.

To reproduce, setup a non-root file system crypt device in crypttab and fstab.

Adding "x-systemd.requires=systemd-cryptsetup@data.service" to fstab appears to resolve the issue for the data drive but not for the swap device.

See this paste bin for the following outputs:
https://paste.rs/tmj8D
 
 * /etc/fstab
 * /etc/crypttab.initramfs
 * /etc/crypttab
 * /run/systemd/generator/systemd-cryptsetup@swap.service
 * /run/systemd/generator/systemd-cryptsetup@data.service
 * /run/systemd/generator/dev-mapper-swap.swap
 * /run/systemd/generator/data.mount
 * /run/systemd/generator/btrfs-data.mount
 * System Journal

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 26 14:13:11 archtest systemd-cryptsetup[634]: Device data is still in use.
Sep 26 14:13:11 archtest systemd-cryptsetup[634]: Failed to deactivate 'data': Device or resource busy
Sep 26 14:13:11 archtest systemd-cryptsetup[635]: device-mapper: remove ioctl on swap  failed: Device or resource busy
Sep 26 14:13:11 archtest systemd[1]: systemd-cryptsetup@data.service: Control process exited, code=exited, status=1/FAILURE
Sep 26 14:13:11 archtest systemd[1]: systemd-cryptsetup@data.service: Failed with result 'exit-code'.
```

**Comment by mahahn** [comment]
I was able to rebuild the Arch Linux systemd package with @YHNdnzj 's commit back ported. I can confirm that I no longer get the error messages. Thanks!

**Comment by steveyh25** [comment]
something similar appears to still be occurring? see [here](https://forums.fedoraforum.org/showthread.php?335203-quot-Failed-to-deactivate-luks-xxx-Device-or-resource-busy-quot-during-shutdown)
