### ISSUE TITLE
systemd-delta does not display a case of template inheritance

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#2934]
### Submission type
- [ ] Bug report
- [*] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 228
### Used distribution

> openSUSE Leap 42.1
### Steps to reproduce

Let `/etc/systemd/system/systemd-nspawn@iridium.service.d/main.conf` be a file:

```
[Service]
ExecStart=
ExecStart=/usr/bin/systemd-nspawn --keep-unit --boot --network-veth -D /D/machines/iridium-191 -M iridium

[Install]
WantedBy=multi-user.target
```

And let `/etc/systemd/system/systemd-nspawn@iridium.service` _not_ exist. To verify that the extend file was read, one can run:

```
# systemctl status systemd-nspawn@iridium
● systemd-nspawn@iridium.service - Container iridium
   Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/systemd-nspawn@iridium.service.d
           └─main.conf
```
### Observed current behavior

```
# systemd-delta | grep nspawn@ir
#
```
### Expected/desired behavior

```
[EXTENDED] /usr/lib/systemd/system/systemd-nspawn@.service -> /etc/systemd/system/systemd-nspawn@iridium.service.d/main.conf
```

I wonder if this way of extending an implicit service is actually supported, or whether I found quite a hack :-)

**Comment by poettering** [comment]
Already tracked in #1685
