### ISSUE TITLE
[libsystemd-network] expose dhcp_lease_save() and dhcp_lease_store() in public API

### ISSUE THREAD

**Issue by thom311** [systemd/systemd#2935]
Commit bd91b83e578165b4c242c9f34ff1d3be8fb3ab22 makes the functions `sd_dhcp_lease_save()` and `sd_dhcp_lease_load()` internal.

For NetworkManager, we use those functions to persist the lease. I think these functions should be public because it is useful to a library user to be able to store/restore a lease to file.

On second though, maybe in the public API those functions should take a FILE\* pointer instead of a path name. This gives the user more flexibility and he could pass a stream from fmemopen().

I'd be willing to send a pull request to either revert commit bd91b83 or follow the FILE\* approach.

**Comment by poettering** [comment]
I am pretty sure that we should not make this serialization official API of libsystem-network. It's very arbitrary, and little more than a reserialization of another serialization, which is the raw DHCP lease data.

I'd much prefer if we could get rid of the file and its concept altogether, both inside of networkd (and libsystemd-network) and in any other users. Instead, let's move towards the model I recently implemented for sd-lldp. There: the raw lldp data may be extracted from a sd_lldp_neighbor object, and a new sd_lldp_neighbor object may be recreated by passing that raw extracted data to a new constructor. This way, we a prefectly extensible, do not define our own serialization, but expose the raw DHCP lease data to clients.

or to be more specific, I think we should add:

``` c
int sd_dhcp_lease_from_raw(sd_dhcp_lease **ret, const void *raw, size_t raw_size);
int sd_dhcp_lease_get_raw(sd_dhcp_lease *lease, const void **ret, size_t *ret_size);
```

this copies the concepts in sd-lldp:

``` c
int sd_lldp_neighbor_from_raw(sd_lldp_neighbor **ret, const void *raw, size_t raw_size);
int sd_lldp_neighbor_get_raw(sd_lldp_neighbor *n, const void **ret, size_t *size);
```

Then, when networkd (or any other consumer of the lib) wants to serialize the DHCP lease data, it may just call sd_dhcp_lease_get_raw(), store the returned raw blob somewhere, and when it wants to turn this back into a DHCP lease object it jzust calles sd_dhcp_lease_from_raw() with the same data.

Benefits:
- we define no new serialization
- we provide consumers raw access to the DHCP lease data, with no additional APIs for that
- writing of the raw data to disk is left to the consumer, which may use any format or place it likes for it

I hope this makes sense?

**Comment by thom311** [comment]
That makes a lot of sense to me. I think sd_lldp_neighbor is well done.

**Comment by teg** [comment]
I'm working on this, along with what Lennart proposed.

**Comment by thom311** [comment]
I am closing this, because it's not clear how to proceed.

NetworkManager still copies a large number of systemd source files and uses the LLDP and DHCP part. This reuse of systemd code not as a proper library is still a bit problematic (but works in practice quite well).

Eventually we should fix that, by NetworkManager and systemd using the same networking library which has a stable API. But there is more to do then just the lease load/store API.

Tom was mentioning plans about stand-alone C libraries and possibly small standalone daemons.
