### ISSUE TITLE
Does systemd-timesyncd still check for the presence of other ntp daemons?

### ISSUE THREAD

**Issue by seamusdemora** [systemd/systemd#29433]
This is something that has been bugging me for a while (~ 2 years!). I'm finally getting around to posting the question:

I use a Debian derivative called Raspbian for my Raspberry Pi computers. I am now using **_bullseye_**; previously, I used **_buster_**.  When I used **_buster_**, the file displayed by `systemctl cat systemd-timesyncd` included the following: 

```bash
[Unit]
# don't run timesyncd if we have another NTP daemon installed
ConditionFileIsExecutable=!/usr/sbin/ntpd
ConditionFileIsExecutable=!/usr/sbin/openntpd
ConditionFileIsExecutable=!/usr/sbin/chronyd
ConditionFileIsExecutable=!/usr/sbin/VBoxService
``` 

Sometime after the release of **_bullseye_**, the above section of code was removed from the `systemctl cat systemd-timesyncd` listing.

This has led me to wonder if `systemd-timesyncd` no longer checks for conflicting timekeeping daemons, thereby requiring a manual intervention to prevent issues - or if it's something else???

Could someone clue me in?

Thanks,
~S

**Comment by yuwata** [comment]
We have never introduced such conditions. Maybe, that's Debian specific. Please contact to your downstream. Closing.

**Comment by seamusdemora** [comment]
*"We have never introduced such conditions. "*??? 

So you simply allow any combination of timekeeping daemons to run alongside `systemd-timesyncd`?

**Comment by yuwata** [comment]
> _"We have never introduced such conditions. "_???
> 
> So you simply allow any combination of timekeeping daemons to run alongside `systemd-timesyncd`?

Right. At least, systemd-timesyncd can run with other NTP clients, and may cause unstable system clock, as, IIUC, there is no mechanism to detect there are other NTP clients running.

Listing other NTP services in `Conflicts=` in upstream side is not a good way. As, distro may install an NTP service with a different service unit name, distro may provide quite minor NTP service, user may install their own NTP client...
At most, introducing/managing such list of conflicting services should be done by distro.

Note, we already introduced a way to manage list of NTP services in `timedated`, to make distor or users easily manage NTP services. See timedatectl(5) and systemd-timedated.service(8) for more detail. Not sure, but I guess Debian bullseye switched to use that mechanism. However, still enabling/starting multiple NTP services by `systemctl` is possible.

Anyway. There is nothing actionable in upstream side. Please contact to your downstream.

**Comment by mbiebl** [comment]
In debian bullseye, systemd-timesyncd was split into a separate binary package which has
```
Conflicts: time-daemon
Replaces: time-daemon
Provides: time-daemon
```
which means it can't be installed in parallel with other ntp daemons. That's why the Conflits= in the .service file are no longer necessary and have been dropped (as we basically solved this issue on the packaging level)

**Comment by mbiebl** [comment]
https://salsa.debian.org/systemd-team/systemd/-/commit/d6483013d5779d4d465a1e174e44a754b941d0e6

**Comment by seamusdemora** [comment]
@mbiebl ,

Yes, I became aware of Debian's technique of dealing with the conflicts at the package level recently - after posting the Q here.  FWIW, it seems to me that the systemd project and the Debian project have chosen two extremes for dealing with this issue...   I'll let it go at that - I don't wish to engage in a discussion.
