### ISSUE TITLE
SendOption causes option to be sent twice

### ISSUE THREAD

**Issue by Tecol87** [systemd/systemd#29437]
### systemd version the issue has been seen with

254.5-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.5.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

DHCP Options should only be sent once.

### Unexpected behaviour you saw

systemd-networkd sends DHCP option twice.

### Steps to reproduce the problem

I configured the DHCP client to ask for a specific IP-Address (Option 50).
When the client already has the IP and I use `systemctl restart systemd-network` the Option 50 is sent twice, which causes the server to NAK.
Here is the configuration:
```
[Match]
Name=wl*

[Network]
DHCP=yes
IPv6PrivacyExtensions=true
IPv6AcceptRA=yes

[DHCPv4]
RouteMetric=200
UseMTU=yes
ClientIdentifier=duid
IAID=1111111111
SendOption=50:ipv4address:192.168.178.22

[DHCP]
RouteMetric=200
```

**Comment by yuwata** [comment]
Using `SendOption=` for such purpose is not good, as the specified option is always sent.
I guess you want to request a specific address in the initial stage.
Maybe, introducing a setting `PreferredAddress=` or so is better.

**Comment by yuwata** [comment]
If you'd like, please test PR #29442.
