### ISSUE TITLE
RFE: pam_systemd should probably raise RLIMIT_NICE for regular user sessions, so that they can acquire higher privileged processes than the default

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#29446]
As discussed here:

https://mastodon.social/@pid_eins/111177281351567765

**Comment by Werkov** [comment]
Notice pam_systemd already accepts PAM data like (from pam_systemd(8)):
>  pam_set_data(handle, "systemd.cpu_weight", (void *)"100",  cleanup);

(This RFE may have some sense when CPU controller is disabled or the user wants to differentiate between their processes.)

OTOH, the original use case talks about compositor, which would likely by a user service which would not benefit from this increased RLIMIT_NICE.

**Comment by poettering** [comment]
RLIMIT_NICE doesn't priorize user process, but it allows users to priorize them within bounds if they want to. 

the cpu weight cgroups stuff priorizes them over other users.

note the user@.service also goes through PAM, hence the raised RLIMIT_NICE would also allow user services to optionally renice themselves higher.

**Comment by Werkov** [comment]
The difference between RLIMIT_NICE (potential/bound} and actual priority  (nice} is clear. I was getting at the situation when users decide to realize the priority; think of nice as cpu.weight on the leaf level (between tasks}, like weights it applies among siblings only. I.e. no cpu controller (all in root cg} -> nice is useful, partitioning with cpu controller -> not so much (depends what is shared on the leaf level}.

s/other users/other sessions of the user/

Another option for user@.service would be `LimitNICE=`.
Actually, when you mention everything going through PAM -- cannot this RFE already be achieved with pam_limits?

**Comment by poettering** [comment]
yeah, pam_limits can do this too.
