### ISSUE TITLE
Unit fails to setup `memory.pressure` unless `DynamicUser=true` is set

### ISSUE THREAD

**Issue by andir** [systemd/systemd#29449]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 40

### Linux kernel version used

6.6.0-0.rc4.33.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The service should start successfully.

### Unexpected behaviour you saw

The unit failed to start:

```console
$ systemctl status test-service
× test-service.service - test
     Loaded: loaded (/etc/systemd/system/test-service.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Wed 2023-10-04 21:32:23 CEST; 2s ago
   Duration: 16ms
    Process: 5311 ExecStart=/usr/bin/sleep 10000 (code=exited, status=226/NAMESPACE)
   Main PID: 5311 (code=exited, status=226/NAMESPACE)
        CPU: 12ms

Oct 04 21:32:23 localhost-live systemd[1]: Started test-service.service - test.
Oct 04 21:32:23 localhost-live (sleep)[5311]: test-service.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/test-service.service/memory.pressure: No such file or directory
Oct 04 21:32:23 localhost-live (sleep)[5311]: test-service.service: Failed at step NAMESPACE spawning /usr/bin/sleep: No such file or directory
Oct 04 21:32:23 localhost-live systemd[1]: test-service.service: Main process exited, code=exited, status=226/NAMESPACE
Oct 04 21:32:23 localhost-live systemd[1]: test-service.service: Failed with result 'exit-code'.

$ systemctl cat test-service
# /etc/systemd/system/test-service.service
[Unit]
Description=test

[Service]
BindReadOnlyPaths=/usr
ExecStart=/usr/bin/sleep 10000
PrivateNetwork=true
ProtectControlGroups=true
TemporaryFileSystem=/:ro
User=andi

# /usr/lib/systemd/system/service.d/10-timeout-abort.conf
# This file is part of the systemd package.
# See https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer.
#
# To facilitate debugging when a service fails to stop cleanly,
# TimeoutStopFailureMode=abort is set to "crash" services that fail to stop in
# the time allotted. This will cause the service to be terminated with SIGABRT
# and a coredump to be generated.
#
# To undo this configuration change, create a mask file:
#   sudo mkdir -p /etc/systemd/system/service.d
#   sudo ln -sv /dev/null /etc/systemd/system/service.d/10-timeout-abort.conf

[Service]
TimeoutStopFailureMode=abort
```

Curiously when adding `DynamicUser=true` to the unit it just works.

### Steps to reproduce the problem

Create a system unit like so:

```ini
# /etc/systemd/system/test-service.service
[Unit]
Description=test

[Service]
BindReadOnlyPaths=/usr
ExecStart=/usr/bin/sleep 10000
PrivateNetwork=true
ProtectControlGroups=true
TemporaryFileSystem=/:ro
User=andi # replace with your user / any existing user on your system
```

Reload the daemon (`systemctl daemon-reload`) and start the unit (`systemctl start test-service.service`).

Checking the status of the service should now show that the `memory.pressure` file access failed and the service startup should be failing with `NAMESPACE`.

If you now add `DynamicUser=true` to your unit, reload the daemon and restart the service the unit will start.

### Additional program output to the terminal or log subsystem illustrating the issue

Since I originally encountered this on the latest NixOS unstable version that just recently updated to systemd v254 I started a test-vm with debug loglevel. The logs can be seen at https://gist.github.com/andir/9314c9c6cd65e4949822066a13aa5748.

**Comment by bluca** [comment]
```
BindReadOnlyPaths=/usr
TemporaryFileSystem=/:ro
```

This is not a good way to do sandboxing. Use ProtectSystem= instead.

**Comment by YHNdnzj** [comment]
At the minimum, `/run/` in the mount namespace should be writable, or most basic functionalities would not work.

And yes, please use `ProtectSystem=` for this kind of hardening.

**Comment by YHNdnzj** [comment]
And the reason why adding `DynamicUser=true` makes this work is that it implies `ProtectSystem=true`, which overrides `TemporaryFileSystem=/`.

**Comment by andir** [comment]
> ```
> BindReadOnlyPaths=/usr
> TemporaryFileSystem=/:ro
> ```
> 
> This is not a good way to do sandboxing. Use ProtectSystem= instead.

Please note that this is a stripped down "minimal" version of a unit to reproduce the behavior. The actual unit configuration that I experienced this (but didn't author) can be found here: https://github.com/NixOS/nixpkgs/blob/3dc2b4f8166f744c3b3e9ff8224e7c5d74a5424f/nixos/modules/services/misc/paperless.nix#L38-L90

I believe, since this setup used to work in previous systemd versions it is likely a bug.

**Comment by YHNdnzj** [comment]
> I believe, since this setup used to work in previous systemd versions it is likely a bug.

We simply assume `/run/` is writable all the time since it's required to setup namespacing. Please also check https://github.com/systemd/systemd/issues/27997. As we introduce new features, inevitably this requirement gets stricter.

**Comment by YHNdnzj** [comment]
-> #29450

**Comment by lf-** [comment]
> > I believe, since this setup used to work in previous systemd versions it is likely a bug.
> 
> We simply assume `/run/` is writable all the time since it's required to setup namespacing. Please also check #27997. As we introduce new features/bugfixes, inevitably this requirement gets stricter.

I also ran into this bug on the same service, said "wtf", wasted 15 minutes reading systemd source to try to figure out why, then didn't get around to filing a bug. My request in this respect is that the very bad error message resulting from this misconfiguration should be improved and the situation should be caught earlier.
