### ISSUE TITLE
systemd-bsod leaves tty in an unusable state if terminated via a signal

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#29478]
### systemd version the issue has been seen with

latest main

### Used distribution

Arch Linux

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

While trying to write a test for systemd-bsod I noticed that if systemd-bsod is terminated via a signal (i.e. `SIGINT` when running the binary directly from the terminal and ctrl-c'ing it, or just doing `systemctl stop systemd-bsod`), it leaves the terminal in an unusable state with the "BSOD" just stuck there and not responding to any input. Restarting the respective getty service (`systemctl restart getty@tty1`) doesn't seem to help, and the only way how to get a sane tty seems to be rebooting the machine. This is a bit annoying, especially if we want test coverage for systemd-bsod.

### Steps to reproduce the problem

```
# systemctl start systemd-bsod
# systemd-cat -p emerg echo hello
## Wait for the "BSOD" to show up on a tty
# systemctl stop systemd-bsod
## The respective tty is now unusable
```

**Comment by 1awesomeJ** [comment]
Thank you so much @mrc0mmand for fishing this out.
I'm sure we'll find a fix for it soon.
Let me see if Poettering has time to take a look.

@poettering, good evening sir.
Please whenever you're chanced, could you guide on fixing this bug?

Thank you.

**Comment by 1awesomeJ** [comment]
@mrc0mmand, @yuwata , @bluca @poettering 
This is the basic flow:
1. bsod finds the first free tty on the machine using an ```ioctl()``` call with the ```VT_GETSTATE``` request.
2. The free tty is opened and activated like so:
```
  r = open_terminal(tty, O_RDWR|O_NOCTTY|O_CLOEXEC);
        if (r < 0)
                return log_error_errno(fd, "Failed to open tty: %m");

        close_and_replace(fd, r);

        if (ioctl(fd, TIOCGWINSZ, &w) < 0)
                log_warning_errno(errno, "Failed to fetch tty size, ignoring: %m");
        
        if (ioctl(fd, VT_ACTIVATE, free_vt + 1) < 0)
                return log_error_errno(errno, "Failed to activate tty: %m");
```

3. On Keypress, the terminal that was previously active gets reactivated like so:
```
  r = read_one_char(stream, &read_character_buffer, USEC_INFINITY, NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to read character: %m");

        if (ioctl(fd, VT_ACTIVATE, original_vt) < 0)
                return log_error_errno(errno, "Failed to switch back to original VT: %m");
```

Is there a place where we should explicitly close the terminal or so?

Thank you sirs.

**Comment by 1awesomeJ** [comment]
I'm thinking we could use ```tcgetattr()``` and ```tcsetattr()``` or our own equivalents of these to save the state of the tty before we do things like turning it blue and moving cursor positions, then we add a logic to handle when SIGTERM, SIGINT or any other relevant signal(s) is received. The tool resets the terminal to its old state, and exits gracefully.

Kindly guide on this sirs in your spare time.

Thank you.

**Comment by 1awesomeJ** [comment]
I'm also looking at using ```signal()``` to handle the signals.
