### ISSUE TITLE
lvm mount point got un mounted during lvrename

### ISSUE THREAD

**Issue by HarinadhD** [systemd/systemd#29543]
### systemd version the issue has been seen with

253 and above

### Used distribution

photon

### Linux kernel version used

6.1.45

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

lvrename command should not unmount the LVM mount point when mount point entry exists in /etc/fstab

### Unexpected behaviour you saw

lvrename command unmounted the mount point when an entry  exists in /etc/fstab

This issue is not observed in systemd version 247.13

root@machine [ ~ ]# systemctl status local-fs.target
● local-fs.target - Local File Systems
     Loaded: loaded (/usr/lib/systemd/system/local-fs.target; static)
     Active: active since Thu 2023-10-12 06:23:53 UTC; 33s ago
       Docs: man:systemd.special(7)

Oct 12 06:23:53 photon-machine systemd[1]: Reached target local-fs.target - Local File Systems.

root@photon-machine [ ~ ]# lsblk
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda              8:0    0   16G  0 disk
├─sda1           8:1    0    4M  0 part
├─sda2           8:2    0   10M  0 part /boot/efi
├─sda3           8:3    0  128M  0 part /boot
└─sda4           8:4    0 15.9G  0 part
  ├─vg1-rootfs 254:0    0 15.7G  0 lvm  /
  └─vg1-root   254:1    0  128M  0 lvm  /root
sdb              8:16   0    5G  0 disk
└─sdb1           8:17   0    5G  0 part
  └─vg2-lv6    254:2    0    5G  0 lvm  /sdb
sr0             11:0    1  4.3G  0 rom

root@photon-machine [ ~ ]# cat /etc/fstab
#system	mnt-pt	type	options	dump	fsck
UUID=989ada28-ceef-4efd-8d8d-1db6d5ea6983	/	ext4	defaults,barrier,noatime,data=ordered	1	1
PARTUUID=286ec042-5577-c6c1-31cd-88f328133f56	/boot	ext4	defaults	1	2
UUID=3a55846a-37f2-40c8-9bed-b38b29208026	/root	ext4	defaults	1	2
PARTUUID=e00c4a2d-894f-2e35-9bf1-482f42248569	/boot/efi	vfat	defaults	1	2
/dev/cdrom	/mnt/cdrom	iso9660	ro,noauto	0	0
UUID=6d3abb94-7644-4551-a3de-2008068739b6	/sdb	ext4	defaults

root@photon-machine [ ~ ]# lvrename vg2 lv6 lv7
  Renamed "lv6" to "lv7" in volume group "vg2"

root@photon-machine [ ~ ]# lsblk
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda              8:0    0   16G  0 disk
├─sda1           8:1    0    4M  0 part
├─sda2           8:2    0   10M  0 part /boot/efi
├─sda3           8:3    0  128M  0 part /boot
└─sda4           8:4    0 15.9G  0 part
  ├─vg1-rootfs 254:0    0 15.7G  0 lvm  /
  └─vg1-root   254:1    0  128M  0 lvm  /root
sdb              8:16   0    5G  0 disk
└─sdb1           8:17   0    5G  0 part
  └─vg2-lv7    254:2    0    5G  0 lvm
sr0             11:0    1  4.3G  0 rom

root@photon-machine [ ~ ]# systemctl status local-fs.target
○ local-fs.target - Local File Systems
     Loaded: loaded (/usr/lib/systemd/system/local-fs.target; static)
     Active: inactive (dead) since Thu 2023-10-12 06:25:39 UTC; 10s ago
       Docs: man:systemd.special(7)

Oct 12 06:23:53 photon-machine systemd[1]: Reached target local-fs.target - Local File Systems.
Oct 12 06:25:39 photon-machine systemd[1]: local-fs.target: Installed new job local-fs.target/stop as 22980
Oct 12 06:25:39 photon-machine systemd[1]: local-fs.target: Job 22980 local-fs.target/stop finished, result=done
Oct 12 06:25:39 photon-machine systemd[1]: Stopped target local-fs.target - Local File Systems.

### Steps to reproduce the problem

1. Add lvm mount point entry to /etc/fstab
2. Execute lvrename command on lvm mount point

### Additional program output to the terminal or log subsystem illustrating the issue

Journal Logs :
https://gist.github.com/HarinadhD/37ced2e50b5d315536fbca8942fbe295

**Comment by poettering** [comment]
sorry, we cannot support lvm issues here. please contact the lvm community for help

**Comment by HarinadhD** [comment]
> sorry, we cannot support lvm issues here. please contact the lvm community for help

This issue is not observed in systemd version 247.13

**Comment by YHNdnzj** [comment]
> > sorry, we cannot support lvm issues here. please contact the lvm community for help
> 
> This issue is not observed in systemd version 247.13 with the same lvm version , This issue happens only when added mount entry in /etc/fstab , Please check the shared journal logs where systemd initiated unmount

Please try #29549 and set `x-systemd.device-bound=no` on the corresponding fstab mount option.

**Comment by yuwata** [comment]
> sorry, we cannot support lvm issues here. please contact the lvm community for help

I will consider if we have a good way to handle such case. Reopening at least for a while.

**Comment by HarinadhD** [comment]
> > This issue is not observed in systemd version 247.13 with the same lvm version , This issue happens only when added mount entry in /etc/fstab , Please check the shared journal logs where systemd initiated unmount
> 
> Please try #29549 and set `x-systemd.device-bound=no` in the corresponding fstab mount option.

I have tried and it's working.
root@photon-machine [ ~ ]# lsblk
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda              8:0    0   16G  0 disk
├─sda1           8:1    0    4M  0 part
├─sda2           8:2    0   10M  0 part /boot/efi
├─sda3           8:3    0  128M  0 part /boot
└─sda4           8:4    0 15.9G  0 part
  ├─vg1-rootfs 254:0    0 15.7G  0 lvm  /
  └─vg1-root   254:2    0  128M  0 lvm  /root
sdb              8:16   0    5G  0 disk
└─sdb1           8:17   0    5G  0 part
  └─vg2-lv13   254:1    0    5G  0 lvm  /sdb
sr0             11:0    1  4.3G  0 rom
root@photon-machine [ ~ ]# lvrename vg2 lv13 lv14
  Renamed "lv13" to "lv14" in volume group "vg2"
root@photon-machine [ ~ ]# lsblk
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda              8:0    0   16G  0 disk
├─sda1           8:1    0    4M  0 part
├─sda2           8:2    0   10M  0 part /boot/efi
├─sda3           8:3    0  128M  0 part /boot
└─sda4           8:4    0 15.9G  0 part
  ├─vg1-rootfs 254:0    0 15.7G  0 lvm  /
  └─vg1-root   254:2    0  128M  0 lvm  /root
sdb              8:16   0    5G  0 disk
└─sdb1           8:17   0    5G  0 part
  └─vg2-lv14   254:1    0    5G  0 lvm  /sdb
sr0             11:0    1  4.3G  0 rom
root@photon-machine [ ~ ]# cat /etc/fstab
#system	mnt-pt	type	options	dump	fsck
UUID=989ada28-ceef-4efd-8d8d-1db6d5ea6983	/	ext4	defaults,barrier,noatime,data=ordered	1	1
PARTUUID=286ec042-5577-c6c1-31cd-88f328133f56	/boot	ext4	defaults	1	2
UUID=3a55846a-37f2-40c8-9bed-b38b29208026	/root	ext4	defaults	1	2
PARTUUID=e00c4a2d-894f-2e35-9bf1-482f42248569	/boot/efi	vfat	defaults	1	2
/dev/cdrom	/mnt/cdrom	iso9660	ro,noauto	0	0
UUID=6d3abb94-7644-4551-a3de-2008068739b6	/sdb	ext4	defaults,x-systemd.device-bound=no
