### ISSUE TITLE
Systemd-Networkd Fails after 1-3 hours

### ISSUE THREAD

**Issue by jakesteele** [systemd/systemd#29555]
### systemd version the issue has been seen with

253.5

### Used distribution

Ubuntu Server 23.10

### Linux kernel version used

6.5.0-9-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Internet works fine for a long period of time as expected.

### Unexpected behaviour you saw

The Internet works fine for around 1-3 hours, then abruptly stops working. 

### Steps to reproduce the problem

Create a network bond of 2 ethernet interfaces using netplan, generate and apply the netplan, leave the server alone for 3 hours and check back. 

### Additional program output to the terminal or log subsystem illustrating the issue

systemd-networkd debug logs:

https://pastebin.com/raw/Vp7BjUsH

- Expected ip 192.168.1.179
- Router: Unifi Dream Machine Pro
- IPv6 Disabled in Netplan / sysctl
- Intel SPF+ Adapter 700

I can fix it instantly by doing: systemctl restart systemd-networkd
It will run fine again for an hour or two, then stop.

**Comment by poettering** [comment]
This is the relevant log line:

"Terminate operation initiated."

This happens if someone sends SIGTERM or SIGINT to networkd. Figure out what that is.

Either way, this doesn't look like a networkd problem, but is simply a clean shutdown on an external request.

**Comment by jakesteele** [comment]
Sorry, I had run it manually in console with debug settings on, that SIGTERM was doing a control + c to stop the process after the internet stopped working. It wasn't relevant to the logs.

I am preparing you a new log file without that in it.

**Comment by jakesteele** [comment]
So I ran it until my internet dropped again, this is in the dropped state (however since boot, I keep restarting the systemd-networkd service every time it stops)

systemd-networkd logs: https://pastebin.com/9H4m7ZM1

ping test:

```
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
From 192.168.1.165 icmp_seq=1 Destination Host Unreachable
From 192.168.1.165 icmp_seq=2 Destination Host Unreachable
From 192.168.1.165 icmp_seq=3 Destination Host Unreachable
From 192.168.1.165 icmp_seq=5 Destination Host Unreachable
From 192.168.1.165 icmp_seq=6 Destination Host Unreachable

--- 1.1.1.1 ping statistics ---
8 packets transmitted, 0 received, +5 errors, 100% packet loss, time 7162ms
pipe 4

```

networkctl
```
IDX LINK            TYPE     OPERATIONAL SETUP
  1 lo              loopback carrier     unmanaged
  2 enp2s0f0        ether    enslaved    configured
  3 enp2s0f1        ether    enslaved    configured
  4 bond0           bond     routable    configured
  5 docker0         bridge   no-carrier  unmanaged
  6 br-abb567d8b179 bridge   routable    unmanaged
  8 veth11789ae     ether    enslaved    unmanaged
 10 veth5032a5f     ether    enslaved    unmanaged
 12 veth7acf3a9     ether    enslaved    unmanaged
 14 vethec9903b     ether    enslaved    unmanaged
 16 veth43ce72c     ether    enslaved    unmanaged
 18 veth150e668     ether    enslaved    unmanaged
 20 veth7d9c3a8     ether    enslaved    unmanaged

13 links listed.
```

ip addr: https://pastebin.com/5K1vrnc3

ip route:
```
default via 192.168.1.1 dev bond0 proto dhcp src 192.168.1.165 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
172.18.0.0/16 dev br-abb567d8b179 proto kernel scope link src 172.18.0.1 
192.168.1.0/24 dev bond0 proto kernel scope link src 192.168.1.165 metric 100 
192.168.1.1 dev bond0 proto dhcp scope link src 192.168.1.165 metric 100 
```

dmesg: https://pastebin.com/YmfXs4mJ

systemd-network status
```
● systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/systemd-networkd.service.d
             └─10-debug.conf
     Active: active (running) since Fri 2023-10-13 16:30:24 UTC; 40min ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
             man:org.freedesktop.network1(5)
   Main PID: 176448 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 76890)
     Memory: 1.1M
        CPU: 72ms
     CGroup: /system.slice/systemd-networkd.service
             └─176448 /lib/systemd/systemd-networkd

Oct 13 16:45:28 ubuntu systemd-networkd[176448]: bond0: Requesting NDisc route (configuring,configured): dst: fd53:b5d0:dfb0::/64, src: n/a, gw: fe80::18ff:3bae:4525:4246, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Oct 13 16:45:28 ubuntu systemd-networkd[176448]: bond0: Setting SLAAC addresses and router.
Oct 13 16:45:28 ubuntu systemd-networkd[176448]: bond0: Configuring NDisc route (requesting,configuring,configured): dst: fd53:b5d0:dfb0::/64, src: n/a, gw: fe80::18ff:3bae:4525:4246, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Oct 13 16:45:28 ubuntu systemd-networkd[176448]: bond0: SLAAC addresses and routes set.
Oct 13 17:07:49 ubuntu systemd-networkd[176448]: Got message type=method_call sender=:1.88 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get  cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Oct 13 17:07:49 ubuntu systemd-networkd[176448]: Sent message type=method_return sender=n/a destination=:1.88 path=n/a interface=n/a member=n/a cookie=57 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Oct 13 17:07:53 ubuntu systemd-networkd[176448]: Got message type=method_call sender=:1.89 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=Get  cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Oct 13 17:07:53 ubuntu systemd-networkd[176448]: Sent message type=method_return sender=n/a destination=:1.89 path=n/a interface=n/a member=n/a cookie=58 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Oct 13 17:09:58 ubuntu systemd-networkd[176448]: bond0: Removing NDisc route (configuring,configured): dst: n/a, src: n/a, gw: fe80::68d7:9aff:fe5d:2726, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Oct 13 17:09:58 ubuntu systemd-networkd[176448]: bond0: Removed NDisc route (configuring): dst: n/a, src: n/a, gw: fe80::68d7:9aff:fe5d:2726, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
```

dhclient -v logs: https://pastebin.com/jDAg9kn3

**Comment by yuwata** [comment]
Please provide relevant .network and .netdev files.

**Comment by yuwata** [comment]
Hm? You also run dnsmasq as a DHCP client??

**Comment by jakesteele** [comment]
I don't run dnsmasq no. 

I've simplified my network files just to see but no luck:

01-bond0.network
```
[Match]
Name=bond0

[Network]
DHCP=yes
```

01-bond0.netdev
```
[NetDev]
Name=bond0
Kind=bond

[Bond]
Mode=802.3ad
```

02-enp.network
```
[Match]
Name=enp*

[Network]
Bond=bond0
```

before I changed to these, they were the default ones generated by the ubuntu-server installer (23.10)

**Comment by ssahani** [comment]
Are there an external DHCP client is running with networkd

foreign:
```
Oct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign address (configured): 192.168.1.165/24 (valid for 23h 57min 29s, preferred for 23h 57min 30s), flags: n/a, scope: global
ct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign route (configured): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.165, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
```

networkd:
```
Oct 13 16:30:27 ubuntu systemd-networkd[176448]: bond0: DHCPv4 address 192.168.1.165/24, gateway 192.168.1.1 acquired from 192.168.1.1
Oct 13 16:30:27 ubuntu systemd-networkd[176448]: bond0: Requesting DHCPv4 address (n/a): 192.168.1.165/24 (valid for 23h 59min 59s, preferred for 23h 59min 59s), flags: tentative, scope: global

```

**Comment by sdirkwinkel** [comment]
I'm seeing something similar on debian bookworm.
When it fails I get `Partner Churn State: churned` in /proc/net/bonding/bond1

It's pretty hard to debug / reproduce as it takes days between failures. I'll try switching to ifupdown, to see if it's actually networkd

**Comment by ssahani** [comment]
> @ssahani
> 
> Thanks for reaching out, I have an external DHCP server which is at 192.168.1.1
> 
> That should be the only DHCP server present on my network. I have DHCP Guarding, on the router 192.168.1.1.

I mean do you have another DHCP client running along with networks in the same machine ? networks is logging  foreign i.e. from another source

```
Oct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign address (configured): 192.168.1.165/24 (valid for 23h 57min 29s, preferred for 23h 57min 30s), flags: n/a, scope: global
ct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign route (configured): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.165, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
```

**Comment by jakesteele** [comment]
I do not; it's a default install of Ubuntu server 23.10. I have not installed or set up any other packages (other than Docker). I have not set up any docker packages that create a DHCP Client.

**Comment by poettering** [comment]
Well, somethings set thats IP address on the bond0 and it's not networkd. i.e. that's why the networkd log message says "*foreign*".

This looks like local misconfiguation. Figure out which component interferes with the device.

**Comment by jakesteele** [comment]
Are you sure the foreign isn't just my router, which is running the DHCP server? the 179 in the debug logs is a valid IP address in my network that is open, and the 192.168.1.1 is my router. 

I tried a default install of Ubuntu Server 23.10 without docker, and the CachyOS Live CD both give me the same issue. If it is another package its being shipped by default :(

**Comment by sdirkwinkel** [comment]
@jakesteele could you try using an older kernel (for example from 23.04). I've tried that and haven't had any issues again yet, but it might just be because it's rarer for me

**Comment by jakesteele** [comment]
A fresh install of 23.04 works fine for me, it's the 23.10 fresh install that's broken.

**Comment by poettering** [comment]
> Are you sure the foreign isn't just my router, which is running the DHCP server?

a router cannot set a route on your local PC, some local software does that. figure out which one that this. 

you probably have a 2nd dhcp client running, maybe dnsmasq, maybe NM, something...

**Comment by yuwata** [comment]
> > @ssahani
> > Thanks for reaching out, I have an external DHCP server which is at 192.168.1.1
> > That should be the only DHCP server present on my network. I have DHCP Guarding, on the router 192.168.1.1.
> 
> I mean do you have another DHCP client running along with networkd in the same machine ? networkd is logging foreign i.e. from another source
> 
> ```
> Oct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign address (configured): 192.168.1.165/24 (valid for 23h 57min 29s, preferred for 23h 57min 30s), flags: n/a, scope: global
> Oct 13 16:30:24 ubuntu systemd-networkd[176448]: bond0: Received new foreign route (configured): dst: n/a, src: n/a, gw: 192.168.1.1, prefsrc: 192.168.1.165, scope: global, table: main(254), proto: dhcp, type: unicast, nexthop: 0, priority: 100, flags: n/a
> ```

These comes when enumerated. That should be expected when networkd is restarted.

**Comment by yuwata** [comment]
@sdirkwinkel First of all, the original statement "The Internet works fine for around 1-3 hours, then abruptly stops working." is quite ambiguous. What component becomes broken? address? routes? or networkd crashes? Please explain the situation when something broken.

Then, please provide the journal for networkd when something broken. It seems [the log](https://pastebin.com/9H4m7ZM1) you provided is about when networkd is restarted.

**Comment by jakesteele** [comment]
Sorry, while all the components seem to be still configured correctly, data is no longer able to reach out of my device. No pings to local clients work, no DNS resolution, no pings outside to external devices. 

I have, however, installed a distro that had no networking; I enabled Systemd-Networkd as the only networking component, and it has been running fine now for two days. I am closing this ticket because it appears a package installed by default in Ubuntu-Server seems to be conflicting with Systemd-Networkd, or the version ship by Ubuntu Server 23.10 is causing the issue. 

Sorry to waste your time, Jake
