### ISSUE TITLE
kernel-install doesn't work for kernel tree-produced rpms

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#29568]
### systemd version the issue has been seen with

254 (254.5-2.fc40)

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.6.0-0.rc5.40.fc40.aarch64

### CPU architectures issue was seen on

aarch64

### Component

kernel-install

### Expected behaviour you didn't see

`/boot/vmlinuz-$kver` exists after the kernel RPM is installed

### Unexpected behaviour you saw

`/boot/vmlinuz-$kver` does not exist after the kernel RPM is installed

### Steps to reproduce the problem

On a Fedora Rawhide (or Fedora ELN) system:

```
# build the kernel rpm
$ git clone linux.git
$ make defconfig
$ make rpm-pkg
# look at the scripts
$ rpm -q --scripts rpmbuild/RPMS/aarch64/kernel-6.6.0_rc5_00234_g8cb1f10d8c4b_dirty-2.aarch64.rpm
# install the kernel
$ sudo dnf install -y rpmbuild/RPMS/aarch64/kernel-6.6.0_rc5_00234_g8cb1f10d8c4b_dirty-2.aarch64.rpm
# notice how vmlinuz is missing in /boot
$ ls -la /boot
```

What's happening here is that the kernel RPM spec includes this logic: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3c9c7a14b627 which moves vmlinuz away before calling installkernel. This then leads to errors in the output (coming from `/usr/lib/kernel/install.d/20-grub.install` I believe), but these don't interrupt the install:

```
Successfully forked off '(direxec)' as PID 18420.
grub2-mkrelpath: error: failed to get canonical path of `/boot/vmlinuz-6.6.0_rc5_00234_g8cb1f10d8c4b_dirty'.
dirname: missing operand
Try 'dirname --help' for more information.
/usr/lib/kernel/install.d/20-grub.install succeeded.
```

and at the end of it, `/boot/vmlinuz-6.6.0_rc5_00234_g8cb1f10d8c4b_dirty` is missing. We originally discovered this on Fedora ELN, but I've verified it repros on Rawhide as well (and likely any other distro with 254). I suspect this is a side effect of the kernel-install rewrite in C.

**Comment by davide125** [comment]
Also filed https://bugzilla.redhat.com/show_bug.cgi?id=2244131 for this to track it downstream

**Comment by davide125** [comment]
I've submitted https://lore.kernel.org/linux-kbuild/20231103-rpmpost-v1-1-9c18afab47f4@meta.com/ to simplify the `%post` on the kernel end, which would avoid triggering this issue. Nonetheless, this should still be fixed on the systemd side as previously created RPMs will still be impacted.

**Comment by keszybz** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2244131#c1 has a longer debugging session. I'll paste just the gist here:

```console
$ /sbin/installkernel -v 6.7.0+ /boot/.vmlinuz-6.7.0+-rpm /boot/.System.map-6.7.0+-rpm
...
kernel version (6.7.0+) set via command line.
kernel image file (/boot/.vmlinuz-6.7.0+-rpm) set via command line.
...
Plugin arguments: add 6.7.0+ /boot/fb878d0057c640258a53deec11a1c2f7/6.7.0+ /boot/.vmlinuz-6.7.0+-rpm
...
About to execute /usr/lib/kernel/install.d/10-devicetree.install add 6.7.0+ /boot/fb878d0057c640258a53deec11a1c2f7/6.7.0+ /boot/.vmlinuz-6.7.0+-rpm
...
About to execute /usr/lib/kernel/install.d/20-grub.install add 6.7.0+ /boot/fb878d0057c640258a53deec11a1c2f7/6.7.0+ /boot/.vmlinuz-6.7.0+-rpm
...
grub2-mkrelpath: error: failed to get canonical path of `/boot/vmlinuz-6.7.0+'.
dirname: missing operand
Try 'dirname --help' for more information.
/usr/lib/kernel/install.d/20-grub.install succeeded.
About to execute /usr/lib/kernel/install.d/50-depmod.install add 6.7.0+ /boot/fb878d0057c640258a53deec11a1c2f7/6.7.0+ /boot/.vmlinuz-6.7.0+-rpm
...
```

There is no /boot/vmlinuz-6.7.0+, there's only /boot/.vmlinuz-6.7.0+-rpm.
It seems that the scriptlet is called correctly. 20-grub.install tries to guess
the name and gets it wrong.

**Comment by DaanDeMeyer** [comment]
@keszybz We've already figured out this regression was caused by your change in grubby to drop the /sbin/installkernel script: https://src.fedoraproject.org/rpms/grubby/c/aa9b1b454fd0c792226cefb65d744fadfaa8acda?branch=rawhide. kernel-install isn't a drop-in replacement for the grubby script since the grubby script also copied the kernel to /boot which kernel-install doesn't do unconditionally. Regardless, this is not a bug in kernel-install though.

**Comment by keszybz** [comment]
> kernel-install isn't a drop-in replacement for the grubby script since the grubby script also copied the kernel to /boot which kernel-install doesn't do unconditionally.

`kernel-install` calls `20-grub.install` or `90-loaderentry.install` that are supposed to install the kernel in whatever place they like. `20-grub.install`  is an unholy mess, but it has a line like `cp --remove-destination --preserve=timestamps -T "${KERNEL_IMAGE}" "/boot/vmlinuz-${KERNEL_VERSION}"`, so I think it's *supposed* to do that.

> Regardless, this is not a bug in kernel-install though.

Yes.
