### ISSUE TITLE
networkd: DHCPv4: UseGateway=no seems to be ignored

### ISSUE THREAD

**Issue by iam-TJ** [systemd/systemd#29564]
### systemd version the issue has been seen with

252.17-1~deb12u1

### Used distribution

Debian 12

### Linux kernel version used

6.2.16-tj

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

DHCPv4 router option 3 not requested by client when `.network` file contains:
```
[DHCPv4]
# do not use an IPv4 default route to avoid packets leaking out
UseGateway=no
```
`man systemd.network` in the `[DHCPV4]` section says:
```
UseGateway=
When true, the gateway will be requested from the DHCP server ...
```
which seems to imply when `=no` (false) the gateway (option 3 router? - it isn't clear that is what this controls) would not be requested.

It may be the man-page is incorrectly describing the option and should say something like "When false will not use the received gateway (option 3) ..."

I found this whilst trying to prevent a default IPv4 route being added. The DHCP is from a Starlink terminal where I am tunnelling an IPv6-only local network over wireguard and do not want any leakage of potential IPv4 packets into the Starlink CGNAT.
As it turns out the Starlink terminal also puts the default route in option 121 Classless Static Route as `0/${terminal_ip}` so I'm also looking for ways to ignore (not use) specific static routes!

### Unexpected behaviour you saw

DHCP request, option 55 Parameter Request List includes `(3) Router` 

### Steps to reproduce the problem

Working with a DHCPv4 server that can/will provide option 3 router and configure the client with `UseGateway=no` and then monitor request packets on the network.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# Using termshark to inspect packets:

[Dynamic Host Configuration Protocol (Request)]
  [Message type: Boot Request (1)]
  [Hardware type: Ethernet (0x01)]
  [Hardware address length: 6]
  [Hops: 0]
  [Transaction ID: 0x1a68be1b]
  [Seconds elapsed: 9895]
  [Bootp flags: 0x0000 (Unicast)]
    [0... .... .... .... = Broadcast flag: Unicast]
    [.000 0000 0000 0000 = Reserved flags: 0x0000]
  [Client IP address: 100.101.43.75]
  [Your (client) IP address: 0.0.0.0]
  [Next server IP address: 0.0.0.0]
  [Relay agent IP address: 0.0.0.0]
  [Client MAC address: PCEngine_4a:72:2c (00:0d:b9:4a:72:2c)]
  [Client hardware address padding: 00000000000000000000]
  [Server host name not given]
  [Boot file name not given]
  [Magic cookie: DHCP]
  [Option: (53) DHCP Message Type (Request)]
    [Length: 1]
    [DHCP: Request (3)]
  [Option: (61) Client identifier]
    [Length: 19]
    [IAID: 56504d98]
    [DUID Type: assigned by vendor based on Enterprise number (2)]
    [Enterprise-number: Tom Gundersen (systemd) (43793)]
    [Identifier: a1190be53cd792b4]
  [Option: (55) Parameter Request List]
    [Length: 8]
    [Parameter Request List Item: (1) Subnet Mask]
    [Parameter Request List Item: (3) Router]
    [Parameter Request List Item: (6) Domain Name Server]
    [Parameter Request List Item: (12) Host Name]
    [Parameter Request List Item: (15) Domain Name]
    [Parameter Request List Item: (33) Static Route]
    [Parameter Request List Item: (120) SIP Servers]
    [Parameter Request List Item: (121) Classless Static Route]
  [Option: (57) Maximum DHCP Message Size]
    [Length: 2]
    [Maximum DHCP Message Size: 1472]
  [Option: (12) Host Name]
    [Length: 4]
    [Host Name: apu2]
  [Option: (255) End]
    [Option End: 255]
```

**Comment by ssahani** [comment]
The config provides not to use rather than sent as request. Hence it's a complete misunderstanding

**Comment by yuwata** [comment]
Yeah, Susant is right. That's expected.

**Comment by iam-TJ** [comment]
The point here is that networkd ***is*** using the default route... not the option 3 router but the option 121 `0/${terminal_ip}` - the `0/` would be, in human-readable form, `0.0.0.0`/ - if this is intended behaviour then the man-page should make it clear it only affects option 3. If that holds then there needs to be a way to ignore arbitrary option 121 routes to achieve the aim of not using a default route.l

**Comment by yuwata** [comment]
Note, when classless static routes option (121) is received, router option (3) is always ignored regardless UseGateway=.
See RFC3442. I mentioned that in #29843.
