### ISSUE TITLE
StartLimitIntervalSec=infinity is undocumented, and also is not preserved across reloads

### ISSUE THREAD

**Issue by mooreye** [systemd/systemd#29574]
### systemd version the issue has been seen with

253

### Used distribution

Fedora 38

### Linux kernel version used

6.5.6-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Manual of systemd.unit(5) doesn't state that you can use `infinity` as an interval for `StartLimitIntervalSec=` option, however, it seems to work as intuition implies (allows `StartLimitBurst` value to be contained within an unlimited timeframe).

### Unexpected behaviour you saw

`infinity` works despite being undocumented

### Steps to reproduce the problem

create a systemd unit with `StartLimitBurst=5` and `StartLimitIntervalSec=infinity` options, make it so that it fails on start (like `ExecStart=/bin/false`), then start it and observe the journal. It will stop restarting after restart count reaches 5 no matter the `RestartSec=` value.

**Comment by smod** [comment]
I probably had a similar use case as yours and the same intuition, FYI it did not work before https://github.com/systemd/systemd/issues/17572 and https://github.com/systemd/systemd/pull/17582

I've been using this "feature" since my PR was accepted.

**Comment by Werkov** [comment]
This doesn't work as you may expect -- system reboot won't preserve the rate-limiting state. Nor does `systemctl daemon-reload`, that may be called arbitrarily.
