### ISSUE TITLE
systemd-networkd: no default route when UseRoutes=yes UseGateway=yes AND option 121 used on server

### ISSUE THREAD

**Issue by fyvfy** [systemd/systemd#29579]
### systemd version the issue has been seen with

254.5-1

### Used distribution

archlinux

### Linux kernel version used

6.5.7-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

no default route added
while `man 5 systemd.network` says
>       UseRoutes=
>           When true (the default), the static routes will be requested from the DHCP server and
>           added to the routing table with a metric of 1024, and a scope of global, link or host,
>           depending on the route's destination and gateway. If the destination is on the local
>           host, e.g., 127.x.x.x, or the same as the link's own address, the scope will be set to
>           host. Otherwise if the gateway is null (a direct route), a link scope will be used.
>           For anything else, scope defaults to global.
>       UseGateway=
>           When true, the gateway will be requested from the DHCP server and added to the routing
>           table with a metric of 1024, and a scope of link. When unset, the value specified with
>           UseRoutes= is used.

### Unexpected behaviour you saw

no internet until manually add default route

### Steps to reproduce the problem

* on lan router (where isc dhcp server is running) add option 121 (rfc3442 aka static classless route for dhcp) static route

* on client pc configure network using systemd-network
   `$ cat /etc/systemd/network/24-macvtap-if-config.network`
   ```
   [Match]
   Name=macvtap-if
   
   [Network]
   DHCP=ipv4
   LinkLocalAddressing=no
   LLMNR=no
   LLDP=yes
   EmitLLDP=no
   
   [DHCPv4]
   UseDNS=yes
   UseNTP=yes
   UseSIP=no
   SendHostname=yes
   UseRoutes=yes
   UseGateway=yes
   ClientIdentifier=mac
   ```
* now `# systemctl restart systemd-networkd.service` and check routes `ip r` - there will be no default route.

### Additional program output to the terminal or log subsystem illustrating the issue

So, this `/etc/systemd/network/24-macvtap-if-config.network` is fine.
Interesting part is:
* when dhcp server does **not** send option 121 then systemd-networkd will add default route
* when dhcp server does send option 121 then systemd-networkd will **not** add default route

1. when dhcp option 121 **disabled** on server
   <details>
   <summary>client routes `ip r`</summary>

   ```
   default via 192.168.10.1 dev macvtap-if proto dhcp src 192.168.10.7 metric 1024 
   192.168.10.0/24 dev macvtap-if proto kernel scope link src 192.168.10.7 metric 1024 
   192.168.10.1 dev macvtap-if proto dhcp scope link src 192.168.10.7 metric 1024 
   ```
   </details>
   <details>
   <summary>client lease `cat /var/run/systemd/netif/leases/5`</summary>

   ```
   # This is private data. Do not parse.
   ADDRESS=192.168.10.7
   NETMASK=255.255.255.0
   ROUTER=192.168.10.1
   SERVER_ADDRESS=192.168.10.1
   T1=1800
   T2=3150
   LIFETIME=3600
   DNS=192.168.10.1
   NTP=192.168.10.1
   CLIENTID=01000086060606
   ```
   </details>
2. when dhcp option 121 **enabled** on server
   <details>
   <summary>client routes `ip r`</summary>

   ```
   192.168.1.0/24 via 192.168.10.1 dev macvtap-if proto dhcp src 192.168.10.7 metric 1024 
   192.168.10.0/24 dev macvtap-if proto kernel scope link src 192.168.10.7 metric 1024 
   192.168.10.1 dev macvtap-if proto dhcp scope link src 192.168.10.7 metric 1024 
   ```
   </details>
   <details>
   <summary>client lease `cat /var/run/systemd/netif/leases/5`</summary>

   ```
   # This is private data. Do not parse.
   ADDRESS=192.168.10.7
   NETMASK=255.255.255.0
   ROUTER=192.168.10.1
   SERVER_ADDRESS=192.168.10.1
   T1=1800
   T2=3150
   LIFETIME=3600
   DNS=192.168.10.1
   NTP=192.168.10.1
   CLASSLESS_ROUTES=192.168.1.0/24,192.168.10.1
   CLIENTID=01000086060606
   ```
   </details>

**Comment by ssahani** [comment]
https://datatracker.ietf.org/doc/html/rfc3442
```
DHCP Client Behavior: 
If the DHCP server returns both a Classless Static Routes option and a Router option, the DHCP client MUST ignore the Router option.
```
