### ISSUE TITLE
Iterating the journal is slow since 254

### ISSUE THREAD

**Issue by lilydjwg** [systemd/systemd#29575]
### systemd version the issue has been seen with

254.5

### Used distribution

Arch Linux

### Linux kernel version used

6.5.2-arch1-2-lily

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

```
$ time LD_LIBRARY_PATH=systemd-libs-253.7-1-x86_64/usr/lib ~target/release/journal-usage > /dev/null
== TIME REPORT FOR LD_LIBRARY_PATH=systemd-libs-253.7-1-x86_64/usr/lib  > /dev/null ==
   User: 1.31s  System: 0.02s  Total: 1.338s
   CPU:  99%    Mem:    225 MiB
```

[journal-usage](https://github.com/lilydjwg/journal-usage) is a simple program that iterates through the whole journal and calculates some stats.

### Unexpected behaviour you saw

```
$ time ~target/release/journal-usage > /dev/null
== TIME REPORT FOR ~target/release/journal-usage > /dev/null ==
   User: 30.29s System: 103.86s  Total: 2:14.35s
   CPU:  99%    Mem:    227 MiB
```

It takes a lot of time `stat`ing the journal files repeatedly:

![out](https://github.com/systemd/systemd/assets/440661/b8314fb7-7b4f-405c-bf58-e2f663518bc2)

### Steps to reproduce the problem

Build and run my program. Or build and run the example program listed in `sd_journal_next(3)`.

**Comment by vcaputo** [comment]
You may want to look at https://github.com/systemd/systemd/pull/29261

**Comment by lilydjwg** [comment]
Oh yes, with #29366 and `SD_JOURNAL_FAST_QUERY` it is fast again. Thank you. (I searched for the problem (slow journal) and it didn't hit.)
