### ISSUE TITLE
 systemd.resource-control man page has dead links related to cgroups

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2958]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819970

This issue was originally reported in the Debian bug tracker against v215, but this issue is still valid with v229. The following URLs in systemd.resource-control give a 404:

```
    3. memory.txt
       https://www.kernel.org/doc/Documentation/cgroups/memory.txt

    4. pids.txt
       https://www.kernel.org/doc/Documentation/cgroups/pids.txt

    5. blkio-controller.txt
       https://www.kernel.org/doc/Documentation/cgroups/blkio-controller.txt

    6. devices.txt
       https://www.kernel.org/doc/Documentation/cgroups/devices.txt

    7. cgroups.txt
       https://www.kernel.org/doc/Documentation/cgroups/cgroups.txt

    8. cpuacct.txt
       https://www.kernel.org/doc/Documentation/cgroups/cpuacct.txt
```

**Comment by martinpitt** [comment]
Fixed in https://github.com/martinpitt/systemd/commits/cgroup-doc-links . I'll send a PR once github gets back alive.

**Comment by jharbott** [comment]
The webserver still shows the old content, does it get updated automatically after some time or does it need some button to be pushed?

**Comment by keszybz** [comment]
I gets updated after release.
