### ISSUE TITLE
Undocumented methods in org.freedesktop.resolve1

### ISSUE THREAD

**Issue by evelikov** [systemd/systemd#29598]
### systemd version the issue has been seen with

254

### Used distribution

Arch

### Linux kernel version used

N/A

### CPU architectures issue was seen on

None

### Component

systemd-resolved

### Expected behaviour you didn't see

Looking for any documentation/examples of the Register/UnregisterService and falling short. In particular I'm interested if there are any non-obvious differences, wrt to Avahi's AddService - from an API user's POV.

Thanks in advance

Disclaimer: Don't usually deal with dbus, pardon for the noob question.

### Unexpected behaviour you saw

`man org.freedesktop.resolve1` lists the interface signatures but are otherwise undocumented. In particular RegisterService and UnregisterService.

### Steps to reproduce the problem

`man org.freedesktop.resolve1`

**Comment by TTimo** [comment]
Online version of this man page: https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.resolve1.html (also lacking documentation of `RegisterService`).

An attempt to migrate code that uses Avahi's AddService to RegisterService here: https://gitlab.steamos.cloud/devkit/steamos-devkit-service/-/commit/58ad7677088d6677702681d99a2cc659bfc461cd

Currently returns `org.freedesktop.DBus.Error.InteractiveAuthorizationRequired: Interactive authentication required.` - does resolved require authentication where Avahi didn't?
