### ISSUE TITLE
udev.conf(5) should explain when udev.conf is read

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#296]
I get the impression that /etc/udev/udev.conf is incorporated into a RAM disk which is used during boot-up. In any case, the changes I made to it a few days ago were not recognized until I reinstalled my linux kernel package (Arch distro). Then I rebooted and a bunch of stuff flashed by too quickly for me to read, slowing the boot time to a minute or more. It took a while to figure out what had happened, since I couldn't read the text. I think this experience could be avoided if the udev.conf(5) man page were to explain which command has to be run in order to get changes to the file to take effect. (I originally modified it because I was trying to debug some uses of udev) Thank you.

**Comment by arvidjaar** [comment]
Whether initrd is using udev, what initrd implementation is used and how to recreate initrd is still largely distro-specific, so I do not think it is possible to describe it in upstream documentation.

**Comment by archenemies** [comment]
Suggestion?: "The file /etc/udev/udev.conf is typically incorporated into an initial ram disk image associated with the kernel executable, which will have to be rebuilt in a distribution-specific way before changes can fully take effect."

**Comment by kaysievers** [comment]
There is no reason to include the file in the initrd. The behavior is controlled with kernel cmdline options. Therfore we do not have to document anything here.
