### ISSUE TITLE
Services sharing sockets with inconsistent NonBlocking= results in silent change of flag state

### ISSUE THREAD

**Issue by Hawk777** [systemd/systemd#29600]
### systemd version the issue has been seen with

systemd-253.11

### Used distribution

Gentoo

### Linux kernel version used

6.1.57-gentoo

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

A single socket unit shared between two service units, where the service units have different `NonBlocking=` values, should result in an error message because the same socket cannot simultaneously be both blocking and non-blocking.

### Unexpected behaviour you saw

The socket’s `O_NONBLOCK` flag is silently changed to match whichever service is started last, probably breaking the earlier services that require it to be in the other state if those earlier services are still running.

### Steps to reproduce the problem

```
$ cat /tmp/showblocking 
#!/usr/bin/env python3

import os
import time

print(f"FD 3 is blocking? {os.get_blocking(3)}")
time.sleep(5)
print(f"FD 3 is still blocking after five seconds? {os.get_blocking(3)}")

$ cat /run/user/1000/systemd/user/mysocket.socket 
[Socket]
ListenStream=/tmp/mysocket
Service=fooservice.service

$ cat /run/user/1000/systemd/user/fooservice.service 
[Service]
Sockets=mysocket.socket
ExecStart=/tmp/showblocking
NonBlocking=true

$ cat /run/user/1000/systemd/user/barservice.service 
[Service]
Sockets=mysocket.socket
ExecStart=/tmp/showblocking
NonBlocking=false

$ systemctl --user start fooservice ; sleep 1 ; systemctl --user start barservice ; sleep 6 ; systemctl --user status fooservice
○ fooservice.service
     Loaded: loaded (/run/user/1000/systemd/user/fooservice.service; static)
     Active: inactive (dead) since Tue 2023-10-17 17:42:04 PDT; 5s ago
   Duration: 5.018s
TriggeredBy: ● mysocket.socket
    Process: 2980 ExecStart=/tmp/showblocking (code=exited, status=0/SUCCESS)
   Main PID: 2980 (code=exited, status=0/SUCCESS)
        CPU: 18ms

Oct 17 17:41:59 amdahl.home.chead.ca systemd[1758]: Started fooservice.service.
Oct 17 17:42:04 amdahl.home.chead.ca showblocking[2980]: FD 3 is blocking? False
Oct 17 17:42:04 amdahl.home.chead.ca showblocking[2980]: FD 3 is still blocking after five seconds? True
```

**Comment by poettering** [comment]
I am pretty sure we should document this and be done with this. A test sounds unnecessary to me, and is hard to do, since additional units might be loaded any time, thus there's no clear time where we could check the settings for consistency.

**Comment by Hawk777** [comment]
Hm, what if the validation and error message generation happened when trying to *start* the second service? From a user perspective, that provides more flexibility (it’s actually totally fine if `fooservice` and `barservice` disagree about the flag state, as long as only one of them is running at a time—systemd’s existing logic will already put the socket in whichever state the running service needs it to be in; it’s only if both are running at the same time that there’s a problem). From an implementation perspective, that should AFAICT solve all the problems with generated units or garbage collected units, since if `fooservice` is running and `barservice` is trying to start, both of them must be loaded into memory and available to sanity check. Or am I missing something?

**Comment by Werkov** [comment]
IIUC fcntl(2):
> Duplicated file descriptors (made with dup(2), fcntl(F_DUPFD), fork(2), etc.)
> refer to the same open file description, and thus share the
> same file status flags.

`O_NONBLOCK` is a property of underlying kernel object not various FDs.
So Service.NonBlocking= should be deprecated and possibly Socket.NonBlocking= added instead.

The proposed sanity check could be rather a best-effort propagation of the setting from the .service to its .socket when there's 1:1 match.

IMHO, the easy way to document out of this would be marking the directive deprecated.

**Comment by Hawk777** [comment]
Moving the directive to the socket unit would make sense to me too. That would even allow the same service to consume two sockets, one of them blocking and one non-blocking, which AFAIK is currently impossible. I hadn’t realized breaking compat in that way was a possibility, but I like it if it can be done.

**Comment by poettering** [comment]
> `O_NONBLOCK` is a property of underlying kernel object not various FDs.
> So Service.NonBlocking= should be deprecated and possibly Socket.NonBlocking= added instead.

I vehemently disagree. Whether an fd is O_NONBLOCK or not is ultimately a question how the program is written, different programs will need it set differently. Hence it should be set on the program, not on the socket.

I am sorry, but I think this case is somewhat artifical/corner. I don#t think we need to spend too much time on it. Mention this in the docs, fine, but other than that I don't think it really matters, it's just not a common case, and whatever we do the outcome people probably really want (i.e. that one program can access the fd with O_NONBLOCK behaviour and the other without) is not reachable anyway. Hence I really wouldn't make a fuss about this, and just doc the fact that you better keep these in sync, because you ultimately have to anyway.

**Comment by Hawk777** [comment]
I don’t feel strongly either way about where the directive belongs (I can see both perspectives). I just feel that *silently* doing the wrong thing (e.g. *silently* handing a program a blocking socket when it asked for a nonblocking one) isn’t a good user experience. Documenting it is good, but complaining about it if it happens would be IMO better.

**Comment by Werkov** [comment]
(I'm surprised that Sockets= directive exists since v11 already and NonBlocking= even earlier.)  So it's apparently not that pressing as I initially thought.
@Hawk777 Do you fancy extending [this](https://github.com/systemd/systemd/blob/758a3aeb4c8229e8849fef7e1276bbca4b55ae56/man/systemd.service.xml#L1121)?

**Comment by Hawk777** [comment]
Thanks for updating this! I would eventually have looked into it myself, but looks like you got there first.
