### ISSUE TITLE
systemd-oomd can kill the video when you "force" the GPU (forcing you to restart)

### ISSUE THREAD

**Issue by 00pandora00** [systemd/systemd#29602]
### systemd version the issue has been seen with

systemd 253

### Used distribution

fedora 38

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

the program, in this case a game, should get kill (no all  the video interface), or in the worst case the video should restart again after killing the program.

### Unexpected behaviour you saw

the video  get kill.

i still can hear the sounds so i think the pc is not freezed but the video dont work

### Steps to reproduce the problem

similar to the behavior of systemd-oomd when the RAM when  is full. 
 
1. use a "extreme" video/gpu demanding app (example: a game) for "x" amount of time. 
2. the video get killed be systemd-oomd

**Comment by poettering** [comment]
i am not sure i understand this report. I think i get that oomd killed something for you that you think should not have been killed? please provide logs of the time frame where this happened, otherwise this is not actionable to us.

**Comment by poettering** [comment]
I presume this is the nvidia binary driver?

**Comment by 00pandora00** [comment]
> I presume this is the nvidia binary driver?

No, is an amd gpu with amdgpu drivers: 

 Device-2: AMD Oland XT [Radeon HD 8670 / R5 340X OEM R7 250/350/350X OEM]
    driver: amdgpu
cpu: intel 
is and old gpu but i don't think that is the problem. 

Note: i think is mesa  problem. today i have checked in different sites and  have found data that indicate that:
https://forum.endeavouros.com/t/gnome-shell-core-dump-with-wayland/46208

plus, i think the problem still show up after stopping systemd-oomd

But still, i not sure. because of this:

1. the message anterior show systemD stopping gnome-session-wayland@gnome.target (that is a coincidence of i riding that wrong?)
2.  systemd-oomd still can be started by systemd-oomd.socket. 

 I know this is possible when you "stop" systemd-oomd, but I don't know if it's possible when you "kill" it. If it doesn't wake up when you kill it then the problem is less likely to be "systemd-oomd".

But I need feedback on what was said above.

3. I still don't know if the problem in MESA is solved or not (I'm in the middle of reading the information on the pages). If it is solved, I have to check in which version it was solved. The above to verify if my version of MESA is lower than the version that solves the problem. (It also helps me to know if the MESA problem is still open)

Final note (for now): I will be reviewing the information on the pages provided by MESA. If in the end it turns out to be a MESA problem I will write a message here and close this bug report. (also if anyone can confirm the pending points above, I will close this report)

**Comment by 00pandora00** [comment]
small update:

After reading the comments on the page:
https://forum.endeavouros.com/t/gnome-shell-core-dump-with-wayland/46208/21
It seems that the problem is solved in version 1:23.2.1-2 of MESA (or downgrading to MESA 1:23.1.8-1)

My version of MESA is 1:23.1.9-1 (I think... my system show 23.1.9-1.fc38 xD). Considering the above, it makes sense that I am affected by the error shown on the page above. But I'm not 100% sure, due to point 1 and 2 of my previous message.

So please don't close this bug report until Fedora has updated its MESA packages. That so I can verify if the problem persists or disappears.

**Comment by poettering** [comment]
Anyway, with at least a copy of the logs this is not actionable to us anyway.

**Comment by poettering** [comment]
So I am pretty sure this is just a memory leak in the graphics driver or GNOME, i.e. oomd is acting on it and is just the messenger that something is wrong, but it's not wrong but in the graphics driver or GNOME. Hence please ping these communities about it.

They'll escalate this back to us, if it turns out to be a systemd problem after all (which i am quite sure is very unlikely though)

**Comment by 00pandora00** [comment]
> driver or GNOME. Hence please ping these communities about it.
> 
> They'll escalate this back to us, if it turns out to be a systemd problem after all (which i am quite sure is very unlikely though)

i think is a driver problem.   i have checked some thinks and i think the problem *now* is with the amdgpu drivers.  i will update here if  any changes happen.

Note/update:

> small update:
> 
> After reading the comments on the page: https://forum.endeavouros.com/t/gnome-shell-core-dump-with-wayland/46208/21 It seems that the problem is solved in version 1:23.2.1-2 of MESA (or downgrading to MESA 1:23.1.8-1)

after updating to MESA 1:23.2.1-2  the problem "change" but still the effects is the same. now  journalctl show problems with amdgpu and not org.gnome.Shell@wayland.service
