### ISSUE TITLE
User groups in  scope unit is incorrect.

### ISSUE THREAD

**Issue by hongjinghao** [systemd/systemd#29613]
### systemd version the issue has been seen with

249

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

When the `socpe` and `service` are running as a common user, the user group displayed by running the `groups` command should be the same as the user group of the common user.

### Unexpected behaviour you saw

When `socpe` and `service` are running as a common user, the user group queried by using `groups` in `scope` is different from the user group of the common user. The `service` is the same.

### Steps to reproduce the problem

\# useradd testuser

\# groupadd testgroup1

\# groupadd testgroup2

\# usermod -G testgroup1,testgroup2 testuser

\# cat << EOF > /home/testuser/test.sh
#!/bin/bash
echo \`whoami\` >> /home/tu/log
echo \`groups\` >> /home/tu/log
EOF

\# chmod 777 /home/testuser/test.sh

\# systemd-run --scope --uid=testuser /home/testuser/test.sh

\# cat /home/testuser/log
testuser
testuser root

\# systemd-run --uid=testuser /home/testuser/test.sh

\# cat /home/testuser/log
testuser
testuser testgroup1 testgroup2

**Comment by xiacunshun** [comment]
I guess it maybe caused by the following reason:

> If a command is run as transient scope unit, it will be executed by systemd-run itself as parent process and will thus inherit the execution environment of the caller. However, the processes of the command are managed by the service manager similarly to normal services, and will show up in the output of systemctl list-units. Execution in this case is synchronous, and will return only when the command finishes. This mode is enabled via the --scope switch (see below).

**Comment by YHNdnzj** [comment]
Sorry, this is the upstream bug tracker for systemd, and we only support the latest two versions here, namely v253 and v254. Please contact your distro for help if you're using older versions.
