### ISSUE TITLE
proposal: support truecrypt file container (regular file) paths in /etc/crypttab

### ISSUE THREAD

**Issue by blitmap** [systemd/systemd#2963]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> v229?

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux

I want systemd to support entries for truecrypt file containers (paths to regular files) in /etc/crypttab.

cryptsetup supports mounting truecrypt file containers already, I believe this is missing features in the (cryptsetup-generator?).  it looks like in /etc/crypttab you have to specify devices by UUID, but what I'm looking for is to specify a path to a truecrypt file container.

if I were invoking cryptsetup directly it would look like this:

`cryptsetup open /path/to/container.truecrypt --type=tcrypt mappedName`

Again, cryptsetup already supports this - but crypttab does not.  I'm trying to use /etc/crypttab to unlock my root "device" from a pre-mounted partition where the file container resides.

(please and thank you?)

**Comment by medhefgo** [comment]
RTFM. This has always been supported and is stated in man crypttab: "The second field contains a path to the underlying block device or file, or a specification of a block device via "UUID=" followed by the UUID."

If it doesn't work it's either a genuine bug or your crypttab line is wrong.

**Comment by blitmap** [comment]
I specified the mapped name as LOCKLESS - in journalctl I see:

```
Apr 04 23:54:19 roxbox systemd[1]: systemd-cryptsetup@LOCKLESS.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 23:54:19 roxbox systemd[1]: Failed to start Cryptography Setup for LOCKLESS.
Apr 04 23:54:19 roxbox systemd[1]: Dependency failed for /dev/mapper/LOCKLESS.
Apr 04 23:54:19 roxbox systemd[1]: dev-mapper-LOCKLESS.device: Job dev-mapper-LOCKLESS.device/start failed with result 'dependency'.
Apr 04 23:54:19 roxbox systemd[1]: Dependency failed for Encrypted Volumes.
Apr 04 23:54:19 roxbox systemd[1]: cryptsetup.target: Job cryptsetup.target/start failed with result 'dependency'.
Apr 04 23:54:19 roxbox systemd[1]: systemd-cryptsetup@LOCKLESS.service: Unit entered failed state.
Apr 04 23:54:19 roxbox systemd[1]: systemd-cryptsetup@LOCKLESS.service: Failed with result 'exit-code'.
...
Apr 04 23:54:19 roxbox systemd-cryptsetup[469]: crypt_init() failed: Block device required
```

I had read the manual - there seems to be a requirement that the path resolves to a block device.  This will not allow for unlocking Truecrypt file containers (regular files).

**Comment by medhefgo** [comment]
Hmmmm. We're not doing anything different when setting things up, if I read cryptsetup code properly. Can you run this with systemd.log_level=debug on kernel command line and also give me the crypttab line and the generated unit file for the device from /run/systemd/generator?

**Comment by medhefgo** [comment]
I just took a look at this myself and I can successfully attach a truecrypt container using systemd-cryptsetup. So most likely your container file path in crypttab is wrong. It seems that the cryptsetup library returns that error code even if the device/file does not exist.

**Comment by blitmap** [comment]
Okay, sorry I was inactive for a bit - I still don't know what I'm doing wrong here.

I know for a certainty the path in /etc/crypttab.initramfs is valid, though:

```
<LABEL> /windows/Users/<USER>/Desktop/container.tc - tcrypt
```

Aside from the replacements, does this look correct?  I currently have this working with Arch's non-systemd `encrypt` hook.  I know this path is correct - but perhaps there's something else I'm missing.

Before this I was using /etc/crypttab when I should have been using /etc/crypttab.initramfs.  Now I am using the correct crypttab, but I still don't get prompted to unlock the root device.  It skips ahead saying it can't find `/dev/mapper/<LABEL>`

Am I making a simple mistake?

How are you testing cryptsetup-generator to see if it correctly unlocks a truecrypt container file path?

**Comment by medhefgo** [comment]
The crypttab line looks okay. You can run "/usr/lib/systemd/systemd-cryptsetup attach <LABEL> <DEVICE> - tcrypt" manually at runtime to see that it indeed works. You most likely have the wrong file path. Can you provide me with the generated unit file from /run/systemd/generator?

**Comment by blitmap** [comment]
Okay well... running `/usr/lib/systemd/systemd-cryptsetup attach - tcrypt` I immediately get this:

```
[root@roxbox ~]# /usr/lib/systemd/systemd-cryptsetup attach - tcrypt
crypt_init() failed: Block device required
```

There doesn't seem to be a generated file for the crypttab entry in `/run/systemd/generator`.

Is the `-` in the systemd-cryptsetup invocation the name of the entry to attach?

I then tried with: `/usr/lib/systemd/systemd-cryptsetup attach LOCKLESS tcrypt`

I received the same output, and there was no generated file in `/run/systemd/generator`...

The exact line I have in `/etc/crypttab` and `/etc/crypttab.initramfs` is this:

```
LOCKLESS /windows/Users/teau/Desktop/archlinux-root.tc - tcrypt
```

Again, I know for a certainty that path is good.  It seems to be requiring that the path resolves to a device and not a regular file...  This is my issue?

I don't think the generator continues working on that entry if `crypt_init()` returns an error code?

**Comment by medhefgo** [comment]
You need to give it the device to decrypt too. Sorry, the input parameter must've been lost during edit.

`/usr/lib/systemd/systemd-cryptsetup attach /windows/Users/teau/Desktop/archlinux-root.tc LOCKLESS - tcrypt`

**Comment by blitmap** [comment]
Okay, here's what I have now:

```
[root@roxbox generator]# /usr/lib/systemd/systemd-cryptsetup attach /windows/Users/teau/Desktop/archlinux-root.tc LOCKLESS - tcrypt
crypt_init() failed: Block device required
```

I see nothing for that device name (LOCKLESS) in `/run/systemd/generator`.

Are you sure this works?

**Comment by medhefgo** [comment]
For crying out loud. I got the order wrong. The label comes before the device:
`/usr/lib/systemd/systemd-cryptsetup attach LOCKLESS /windows/Users/teau/Desktop/archlinux-root.tc - tcrypt`

**Comment by medhefgo** [comment]
Well, if you only have it in /etc/crypttab.initramfs, then it'll either be somewhere in /run/initramfs/ or got deleted in the transition away from initramfs.

**Comment by blitmap** [comment]
1) First I want to say I'm very thankful for the amount of patience you've had with me, here.

2) Perhaps the parameter-checking for systemd-cryptsetup needs improvement.  If it's supposed to accept the mapped device name first and the path 2nd, then it has been complaining that the path is not a block device (when it should have been complaining it didn't exist first).  Should it be sophisticated at all since this is not a very user-facing utility?

Anyway, I have yet to try this again - sorry I'm somewhat slow getting back to you.  I've had some health problems recently and it's hard for me to sit in a chair with my laptop.  (I had surgery on my tailbone).

I'll update soon enough :smile:

**Comment by poettering** [comment]
Also see #1541...

**Comment by medhefgo** [comment]
I finally decided to give it a try using crypttab too. The support luks or truecrypt container files just fine. The generator creates the proper RequiresMountsFor dependency and libcryptsetup itself does the job of allocating a loopback device.

**Comment by blitmap** [comment]
Okay, I can confirm it works here too.  The problem is then my own - I think I'm using Arch Linux' init hooks incorrectly.  I manually did the systemd-cryptsetup invocation and I can confirm it prompts and unlocks the device as expected without even complaining that it's not a block device.

(thank you for all your help!)

I think I might have conflicting init hooks in my `/etc/mkinitcpio.conf`.  I know I need the `systemd` and `sd-encrypt` hooks, but I think there is another I should not have in that list which is triggering before `sd-encrypt` and making it impossible for me to get to that step where systemd unlocks my root device.

Anyway - my problem.  It's an Arch problem I'm having :smile:  My confusion is I don't know how to specify on the kernel cmdline which device is the root device (from /etc/crypttab.initramfs).  Everything in the man page for systemd-cryptsetup-generator seems luks specific.

(Thanks for your patience)

**Comment by medhefgo** [comment]
Actually, if I read the code properly, they aren't luks specific. You just need to make sure to add rd.luks.options=tcrypt. I'll have a look some time and maybe add a neutral prefix for them.

On second look. It wouldn't work. There are no UUIDs in truecrypt on disc structure for this to work for partitions (and right now it only allows UUID based mounting through command line) nor does the feature support container files right now.

**Comment by blitmap** [comment]
What I'm looking to do is simply say that my root device has the LABEL=LOCKLESS.  How would I say this from the kernel cmdline?  Is this even the right place?  Would it be: luks.name=LOCKLESS or something?

(sorry this is off-topic)

**Comment by medhefgo** [comment]
Right now there is no support for mounting truecrypt volumes using the kernel command line.

**Comment by blitmap** [comment]
Well I mean the truecrypt file container is specified in /etc/crypttab.initramfs... are you saying there's no way for me to tell systemd which entry is my root device once unlocked?

**Comment by medhefgo** [comment]
My simple bet is that you have your file path wrong. And why would you even use truecrypt for the root device in the first place?! Plausible deniability is a pointless thing anyway.

**Comment by blitmap** [comment]
1) I took the path directly from the kernel cmdline and put it in /etc/crypttab.initramfs. I manually unlocked it following your instructions using the same path.

2) LUKS/dm-crypt is not portable to Windows and Mac OS X.

Now that we know it works (my bad) - I just need a way to tell systemd what my root device is.  Do I use `root=/dev/mapper/LOCKLESS` ?

**Comment by poettering** [comment]
@blitmap yes, root= is usually how you specify the root device and it expects a full /dev path.
