### ISSUE TITLE
configure interface created by another service

### ISSUE THREAD

**Issue by nnovikov** [systemd/systemd#29639]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

I have DPDK application, which create bond interface on startup.
```
10: bond0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
```
I want set up link and add addresses/routes for this interface via networkd config files. But if this config files exist networkd creates bond0 interface himself and DPDK can't works correct if interface already exist.
Is it possible configure networkd for this case? Ideally, networkd should not make and action on boot, but configure interface on networkctl up command.

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by poettering** [comment]
> I want set up link and add addresses/routes for this interface via networkd config files. But if this config files exist networkd creates bond0 interface himself and DPDK can't works correct if interface already exist.
> Is it possible configure networkd for this case? Ideally, networkd should not make and action on boot, but configure interface on networkctl up command.

.netdev files create network devices.

.link files configure network devices.

.network files then assign network configuration to them.

Use .netdev only for devices you want systemd-networkd to create hence. If something else creates the devices, then don't use a .netdev file, but just a .link and/or .network files.

**Comment by poettering** [comment]
For support questions like this contact the systemd mailing list please, do not use this bug tracker for that.
