### ISSUE TITLE
RFE: add generic PAM module that takes password from kernel keyring and inserts it into PAM authtok (for replacing pam_gdm)

### ISSUE THREAD

**Issue by jinliu** [systemd/systemd#29658]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

GDM has this pam_gdm.so (https://github.com/GNOME/gdm/blob/main/pam_gdm/pam_gdm.c) which reads the LUKS passphrase from the kernel keyring (put there earlier by systemd-cryptsetup), and sets it as the auth token, so it can unlock GNOME Keyring and KDE KWallet in their PAM modules.

The code has nothing GDM specific. Rather, it depends on an implementation detail in systemd-cryptsetup (the keyname "cryptsetup"). So perhaps systemd is a better place for this PAM module.

### Describe the solution you'd like

Move https://github.com/GNOME/gdm/blob/main/pam_gdm/pam_gdm.c into the systemd project. So besides GDM, other display managers (or even console logins) can use it for auto logins and auto unlocking of password store.

### Describe alternatives you've considered

The user can install GDM to get that PAM module. However, it would bring in a lot of GNOME dependencies that a non-GNOME desktop doesn't need.

### The systemd version you checked that didn't have the feature you are asking for

254.5

**Comment by YHNdnzj** [comment]
Hmm, I'm not sure if the LUKS password would be a good fit for the use case? Especially when FIDO2/TPM is in use.

A better alternative could be https://github.com/systemd/systemd/issues/26306#issuecomment-1494055957

**Comment by jinliu** [comment]
I see. That is indeed better, as you said it also covers the case where no password entered at all in the boot process.

**Comment by poettering** [comment]
So I think this would be OK to add, but of course won't work if FIDO2/PKCS11/TPM2 is enrolled on the root disk. I think the general model of having the root FDE password synced with the user's pw is a bit weir,d but I see no reason why we would not merge something like this if someone proposes this.

Would require a PR.

**Comment by poettering** [comment]
I think such a module should probably be entirely generic, i.e. you should be able to specify a generic key name on the module cmdline, if you want. We'd default to the cryptsetup one if none is specified though.

**Comment by poettering** [comment]
Fixed by #29776

**Comment by lnussel** [comment]
Very cool! I have been thinking about writing something like this too. Now if we in addition optionally had a way to relate a key slot to a user name the system could even log in different users based on keyslot unlocked

**Comment by poettering** [comment]
@lnussel we could certainly add that as metadata via the json token stuff.

In the homed usecase we probably want something similar, but for recovery key slots: link a recovery key slot to a specific user. (@AdrianVovk)
