### ISSUE TITLE
systemctl is-enabled returns confusing results for symlinks in /usr/lib/systemd/system

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#29655]
### systemd version the issue has been seen with

main

### Used distribution

Fedora 39

### Linux kernel version used

n/a

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

`systemctl is-enabled <unit>` returns some variation of `enabled` for a unit that's symlinked in a .wants/ directory in /usr/lib/systemd/system.

### Unexpected behaviour you saw

`systemctl is-enabled <unit>` returns `static` or `disabled` for a unit that's symlinked in a .wants/ directory in /usr/lib/systemd/system depending on whether the unit file has an `Install` section or not.

**Comment by YHNdnzj** [comment]
This is a duplicate of #9569...

**Comment by DaanDeMeyer** [comment]
Cool let's close this one then
