### ISSUE TITLE
Add feature to update TPM unlocking policy by Systemd automatically

### ISSUE THREAD

**Issue by IPlayZed** [systemd/systemd#29661]
### Component

systemd, systemd-cryptsetup

### Is your feature request related to a problem? Please describe

When updating the system there are certain intentional changes which can affect configured TPM PCRs. For instance changing the kernel command line (affecting PCR 12), or changing the components of unified kernel images (affecting PCR 11) among many others.

Even if these changes were approved by the system administrator, one has to manually wipe and add enroll a new TPM record into the LUKS header manually.

### Describe the solution you'd like

Add a feature to automatically check if the enrolled policy is different from upgraded state's policy. If not, display the changes, ask the administrator to verify and accept the changes (in a traceable manner). Based on configuration ask for the administrator to use a FIDO/PKCS or similar to overwrite the policy, but also support automatically changing this without further verification if the user is allowed to do so. It is OK if this only checks systemd-related changes, but not hardware changes (like setting changing CPU), as it is not related to OS-level updates.

### The systemd version you checked that didn't have the feature you are asking for

systemd 254.5-1

**Comment by poettering** [comment]
PR #28891 is supposed to be the way out for automatic PCR policy management.

**Comment by poettering** [comment]
I am pretty sure #28891 is the way to the future. It has been merged now, let's focus on that hence.
