### ISSUE TITLE
Documentat that LISTEN_PID/LISTEN_FDS are not set if StandardInput=socket is used

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#29670]
### Is your feature request related to a problem? Please describe

I am trying to implement socket activation.  I spent many many hours trying to work out why my process was not getting these environment variables:

LISTEN_PID
LISTEN_FDS

Eventually after many wasted hours I found that StandardInput=socket means there will be no such variables, presumably because the socket is plugged into stdin.

### Describe the solution you'd like

I'd love it if documentation of LISTEN_PID and LISTEN_FDS explained the relationship.

and conversely it would be great if the documentation of StandardInput=socket explained this.

### Describe alternatives you've considered

Going nuts trying to work out where the missing variables are.

**Comment by poettering** [comment]
yes, it is intentional. StandardInput=socket enables inetd compat, where the env vars don't exist.

**Comment by bootrino** [comment]
Thanks all!  I love systemd - I'm a huge fan.
