### ISSUE TITLE
Assertion 'percent <= 100' failed at src/shared/format-table.c:724, function table_set_ellipsize_percent(). Aborting.

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#29684]
### systemd version the issue has been seen with

main

### Used distribution

Fedora 38

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

systemd-repart finishes succesfully

### Unexpected behaviour you saw

```
Assertion 'percent <= 100' failed at src/shared/format-table.c:724, function table_set_ellipsize_percent(). Aborting.
```

**Comment by DaanDeMeyer** [comment]
Nvm can't reproduce after rebuilding
