### ISSUE TITLE
`systemd-run --pipe` does not restore tty settings

### ISSUE THREAD

**Issue by duament** [systemd/systemd#29714]
### systemd version the issue has been seen with

254

### Used distribution

NixOS

### Linux kernel version used

6.5.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

Output of `stty -a` should be the same before and after running `systemd-run --pipe`

### Unexpected behaviour you saw

TTY settings changed by `systemd-run --pipe` and not restored.

### Steps to reproduce the problem

Run a bash script:
```bash
stty -echo
stty -a
echo
systemd-run --user --pipe --wait --collect true
echo
stty -a
```

The output is below. Obviously `-echo` becomes `echo`.

(Original issue: https://github.com/NixOS/nixpkgs/issues/262686#issuecomment-1775270043)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
speed 38400 baud; rows 50; columns 196; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop echoprt echoctl echoke -flusho -extproc

Running as unit: run-u44.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 3ms
CPU time consumed: 3ms

speed 38400 baud; rows 50; columns 196; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop echoprt echoctl echoke -flusho -extproc
```

**Comment by poettering** [comment]
hmm, systemd-run --pipe should actually not touch any tty settings at all

**Comment by Werkov** [comment]
Interensting, different flags get change when I try locally:
```diff
 speed 38400 baud; rows 63; columns 274; line = 0;
 intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
--ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
+-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
+isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop echoprt echoctl echoke -flusho -extproc
```

the changes are: `-imaxbel` -> `imaxbel`, `-echopr` -> `echoprt`

There is no change without `--pipe` arg.

systemd-254.5-2.1.x86_64
coreutils-9.4-2.1.x86_64
glibc-2.38-5.1.x86_64

**Comment by duament** [comment]
Did some strace

`systemd-run` itself did not touch tty settings. But `systemd` (the service manager) made exact one `TCSETS` `ioctl` call.

```
201852 ioctl(0, KDSETMODE, KD_TEXT)     = -1 ENOTTY (Inappropriate ioctl for device)
201852 openat(AT_FDCWD, "/sys/module/vt/parameters/default_utf8", O_RDONLY|O_CLOEXEC <unfinished ...>
201852 <... openat resumed>)            = 3
201852 newfstatat(3, "",  <unfinished ...>
201852 <... newfstatat resumed>{st_mode=S_IFREG|0644, st_size=4096, ...}, AT_EMPTY_PATH) = 0
201852 read(3,  <unfinished ...>
201852 <... read resumed>"1\n", 4096)   = 2
201852 ioctl(3, TCGETS, 0x7ffd8da4e4b0) = -1 ENOTTY (Inappropriate ioctl for device)
201852 read(3, "", 4096)                = 0
201852 close(3 <unfinished ...>
201852 <... close resumed>)             = 0
201852 ioctl(0, KDSKBMODE, K_UNICODE <unfinished ...>
201852 <... ioctl resumed>)             = -1 ENOTTY (Inappropriate ioctl for device)
201852 ioctl(0, TCGETS <unfinished ...>
201852 <... ioctl resumed>, {c_iflag=ICRNL|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B9600|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOPRT|ECHOKE, ...}) = 0
201852 ioctl(0, TCSETS, {c_iflag=ICRNL|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B9600|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOPRT|ECHOKE, ...} <unfinished ...>
201852 <... ioctl resumed>)             = 0
201852 ioctl(0, TCFLSH, TCIOFLUSH)      = 0
201852 dup2(29, 1 <unfinished ...>
201852 <... dup2 resumed>)              = 1
201852 dup2(30, 2 <unfinished ...>
201852 <... dup2 resumed>)              = 2
```

full trace: [systemd_strace.txt](https://github.com/systemd/systemd/files/13213567/systemd_strace.txt)

It's like the `reset_terminal_fd` call in `setup_input` https://github.com/systemd/systemd/blob/d19434fbf81db04d03c8cffa87821f754a86635b/src/core/exec-invoke.c#L376-L400

**Comment by Werkov** [comment]
Thanks for tracking it down. So to keep `--pipe` as unintrusive as possible (whereas `--pty` allocates a new PTY and service can do whatever to it), this might help:

```diff
--- a/src/core/exec-invoke.c
+++ b/src/core/exec-invoke.c
@@ -390,8 +390,9 @@ static int setup_input(
                 if (dup2(params->stdin_fd, STDIN_FILENO) < 0)
                         return -errno;
 
-                /* Try to make this the controlling tty, if it is a tty, and reset it */
-                if (isatty(STDIN_FILENO)) {
+                /* Try to make this the controlling tty, if it is a tty, and reset it
+                 * but don't touch tty if it was passed via systemd-run --pipe */
+                if (isatty(STDIN_FILENO) && !context->stdio_as_fds) {
                         unsigned rows = context->tty_rows, cols = context->tty_cols;
 
                         (void) exec_context_tty_size(context, &rows, &cols);
```

But [machine-dbus.c](https://github.com/systemd/systemd/blob/7e472fc9847f921133ecdfc96cd7a7b640cfb9cc/src/machine/machine-dbus.c#L707) would need adjustment to rely only on TTYPath=. There is also TTYReset= but that may not be apply to `setup_input()`.

**Comment by poettering** [comment]
We kinda fixed this once before:

1e22b5cda04b6d5e0dd83ab8e6ecb452cf34851f

**Comment by vindicatorr** [comment]
v259
I don't know if this will warrant opening a new issue, but I've encountered tty settings changes as well.
I mentioned it in IRC maybe a few days ago because I didn't know what was happening.
I didn't know if it had anything to do with my changing my custom commands from shell aliases to functions.

As stated here, it seemed to relate to my use of `--pty`, and someone suggested using `--scope` instead which makes sense for the use of the commands.
EG (shell function):
```
pacman ()
{
  \command -p "systemd-run" --user --same-dir --collect --pty "pacman" "${@}"
# bad
#   \command -p "systemd-run" --user --same-dir --collect --scope  "pacman" "${@}"
# good
}
```
Control characters are displayed in the output:
```
$ pacman -Qi libav<tab><tab>
libavc1394^M  libavif^M
```

Now you can see I transitioned to using `--scope` for the function commands instead (which is how I should have done it), and that works fine.

HOWEVER, I'm noticing the problem also exists with `run0` which I've transitioned to using now from sudo (and see it's essentially `systemd-run`).
While the former command could be 100% repo'd, this one is a little hit-or-miss:
```
ls ()
{
  \command -p "ls" --color=auto "${@}"
  echo echoing hmm in ls function
}
```
`$ run0 ls` does what it's supposed to other than any stdin afterwards isn't displayed until I `reset`.
I mentioned this in IRC today, and the `stty -a` difference between a fresh terminal and the broken one is: `-igncr -icrnl -opost -isig -icanon -iexten -echo`.

I was going to `strace`, but apparently my ENV `.shinit` doesn't get loaded (no ls coloring, nor echo at the end).

I have not implemented a `run0` function override (though maybe I ought to solely for the `--scope`?).

EDIT0: I can state that it has nothing to do with my shell functions...
I had `$ run0 mount` to mount a drive partition, and again the tty blanked for any new stdin until I `$ reset`.
Is there a timing/race issue? My ancient Haswell system has a rough time sometimes getting the agent prompt to get displayed.
