### ISSUE TITLE
Unexpected bind mount from an entry with a non-existent source in `BindReadOnlyPaths=`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#29725]
While trying to break the sd-executor stuff (again, sorry!) I noticed a strange anomaly regarding `BindPaths=/BindReadOnlyPaths=` and I'm still not sure if it's an intended behavior.

Long story short, when specifying a read only bind mount with an invalid source, but with a `-` prefix, the bind mount appears to be correctly ignored, but *some* bind mount still happens on the destination.

For example:
```
# systemd-run -q --wait --pipe -p BindReadOnlyPaths="-/this/does/not/exists:/opt" mount -l | grep /opt
/dev/vda3 on /opt type btrfs (ro,relatime,compress-force=zstd:3,discard=async,space_cache=v2,subvolid=5,subvol=/)
```

Logs seem to correctly show that the mount has been skipped:
```
[60786.132781] (mount)[13979]: Applying namespace mount on /run/systemd/mount-rootfs/opt
[60786.132901] (mount)[13979]: Path /this/does/not/exists does not exist, ignoring.
```

This does *not* happen with `BindPaths=`:
```
# systemd-run -q --wait --pipe -p BindPaths="-/this/does/not/exists:/opt" mount -l | grep /opt || echo nope
nope
```

Is this expected and I'm just missing something obvious?

**Comment by bluca** [comment]
I can reproduce this on 252 - _wut_

**Comment by mrc0mmand** [comment]
> I can reproduce this on 252 - _wut_

Oh yeah, I can reproduce it on C8S with v239, so it's definitely nothing new.

**Comment by bluca** [comment]
I can't see anywhere that would actually do a mount - is it possible that it's simply _appearing_ in the mount table of the namespace because of some probing? But again I can't see where the probing would be different for a read-only one

**Comment by mrc0mmand** [comment]
strace shows there's something actually mounting this stuff:

```
# strace -e mount -p 1 -o pid1.strace -v -f -y -s500 &
# systemd-run -q --wait --pipe -p BindReadOnlyPaths="-/this/does/not/exists:/opt" mount -l | grep /opt
strace: Process 14076 attached
/dev/vda3 on /opt type btrfs (ro,relatime,compress-force=zstd:3,discard=async,space_cache=v2,subvolid=5,subvol=/)
strace: Process 14077 attached
strace: Process 14078 attached
strace: Process 14079 attached
# cat pid1.strace 
14076 mount(NULL, "/", NULL, MS_REC|MS_SLAVE, NULL) = 0
14076 mount("/", "/proc/self/fd/3", NULL, MS_BIND|MS_REC, NULL) = 0
14076 mount("/run/systemd/inaccessible/dir", "/proc/self/fd/4", NULL, MS_BIND|MS_REC, NULL) = 0
14076 mount("/run/systemd/propagate/run-u164.service", "/proc/self/fd/4", NULL, MS_BIND, NULL) = 0
14076 mount("/run/systemd/mount-rootfs/opt", "/proc/self/fd/4", NULL, MS_BIND|MS_REC, NULL) = 0
14076 mount(NULL, "/proc/self/fd/4", NULL, MS_RDONLY|MS_REMOUNT|MS_BIND, NULL) = 0
14076 mount(NULL, "/proc/self/fd/4", NULL, MS_RDONLY|MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND, NULL) = 0
14076 mount(NULL, "/proc/self/fd/4", NULL, MS_RDONLY|MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND, NULL) = 0
14076 mount(NULL, "/proc/self/fd/4", NULL, MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND, NULL) = 0
14076 mount(NULL, "/", NULL, MS_REC|MS_SHARED, NULL) = 0
14076 mount(NULL, "/run/systemd/incoming", NULL, MS_SLAVE, NULL) = 0
14076 +++ exited with 0 +++
14077 +++ exited with 0 +++
14079 +++ exited with 0 +++
14078 +++ exited with 0 +++
```

And with some *strategic* printf()s I managed to trace it back to this part:
https://github.com/systemd/systemd/blob/34931384ac55efc97d6431b886fb4e8f27f0381e/src/core/namespace.c#L1940-L1947

but that's all I got for now.

**Comment by bluca** [comment]
Ah excellent find, yes of course we simply don't check whether something has been actually applied, for real, or not. I'll prep a fix. Do you have something resembling a test case already?

**Comment by mrc0mmand** [comment]
> Ah excellent find, yes of course we simply don't check whether something has been actually applied, for real, or not. I'll prep a fix. Do you have something resembling a test case already?

This should do the trick:

```diff
diff --git a/test/units/testsuite-07.exec-context.sh b/test/units/testsuite-07.exec-context.sh
index de9edd7640..0c3e742b70 100755
--- a/test/units/testsuite-07.exec-context.sh
+++ b/test/units/testsuite-07.exec-context.sh
@@ -75,3 +75,8 @@ if ! systemd-detect-virt -cq; then
     systemd-run --wait --pipe -p ProtectKernelLogs=no -p User=testuser \
         bash -xec "test -r /dev/kmsg"
 fi
+
+systemd-run --wait --pipe -p BindPaths="/etc /usr:/usr /home:/mnt:norbind -/foo/bar/baz:/opt:rbind" \
+    bash -xec "mountpoint /etc; test -d /etc/systemd; mountpoint /usr; mountpoint /mnt; ! mountpoint /opt"
+systemd-run --wait --pipe -p BindReadOnlyPaths="/etc /usr:/usr /home:/mnt:norbind -/foo/bar/baz:/opt:rbind" \
+    bash -xec "test ! -w /etc; test ! -w /usr; test ! -w /mnt; ! mountpoint /opt"
```

**Comment by bluca** [comment]
It accidentally passes on main for me:

```
Oct 26 13:11:22 H testsuite-07.sh[485]: + mountpoint /opt
Oct 26 13:11:22 H testsuite-07.sh[489]: mountpoint: /opt: No such file or directory
```

**Comment by mrc0mmand** [comment]
> It accidentally passes on main for me:
> 
> ```
> Oct 26 13:11:22 H testsuite-07.sh[485]: + mountpoint /opt
> Oct 26 13:11:22 H testsuite-07.sh[489]: mountpoint: /opt: No such file or directory
> ```

Ah, it looks like /opt is not always in the image. I guess `mkdir /opt` somewhere at the beginning of the test should take care of that.

**Comment by bluca** [comment]
I'll use /usr instead as that exists
