### ISSUE TITLE
Create nspawn container to test changes

### ISSUE THREAD

**Issue by ShalokShalom** [systemd/systemd#29724]
### Is your feature request related to a problem? Please describe

I just came across an issue, that blocked the creation of a nspawn container according to a popular tutorial on 0-pointer. 

I don't have the time to manually compile systems, and I wouldn't even know, how to properly boot my machine into it, and don't wanna risk altering my system unreliable. 

Still, as it stands now, was a possible fix closed since nobody seems to be able to test. 

### Describe the solution you'd like

I suggest to provide nspawn container **via CI**, to test future issues like that. 
This is, what nspawn has been created for, ultimately. 

### Describe alternatives you've considered

The alternative would be, to provide other container solutions, and to leave potential contributions [like this](https://github.com/systemd/systemd/pull/29665) one untested.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by mrc0mmand** [comment]
There's a detailed guide in https://github.com/systemd/systemd/blob/main/docs/HACKING.md that describes how to easily set up such environment using mkosi.

**Comment by ShalokShalom** [comment]
How does this replace CI?
