### ISSUE TITLE
Missing option for tmpfiles.d to ignore the file access time

### ISSUE THREAD

**Issue by bjoernv** [systemd/systemd#2974]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 228
### Used distribution

openSUSE Tumbleweed 20160405
KDE Plasma 5 desktop (5.5.5)
### In case of bug report: Expected behaviour you didn't see

Temp files should be cleared according the settings in /etc/tmpfiles.d/tmp.conf.
### In case of bug report: Unexpected behaviour you saw

Many temp files in /tmp and /var/tmp are never cleared, if a desktop like KDE is used.
### In case of bug report: Steps to reproduce the problem

1) Example configuration:
/etc/tmpfiles.d/tmp.conf

```
d /tmp 1777 root root 3d
d /var/tmp 1777 root root 5d
```

2) Use a file manager like KDE Dolphin and open the temp directories. It's probably not necessary to open the file manager manually because the desktop environment will scan the temp directories periodically automatically (not really tested by me).

Explanation:
File managers (e.g. the KDE file manager Dolphin) open all files with matching access rights during directory scan. This behavior can not be disabled (as far as I know). After each scan the access time (atime) is updated. Even with default mount option "relatime" atime will be updated every day (see "man mount").

Only the mount option "noatime" fixes the problem, but often causes other problems (see "man mount").

It should be possible to ignore the atime in systemd-tmpfiles configuration. Instead of the access time the modification time (mtime) can be used. Here is the existing code for atime evalutation:

systemd-228/src/tmpfiles/tmpfiles.c:

```
                       age = timespec_load(&s.st_atim);
                        if (age >= cutoff) {
                                char a[FORMAT_TIMESTAMP_MAX];
                                log_debug("Directory \"%s\": access time %s is too new.",
                                          sub_path,
                                          format_timestamp_us(a, sizeof(a), age));
                                continue;
                        }
```

For many users the following behavior is acceptable: Files in temp directories which have not been modified over a long time, can be deleted.

The problem can also be fixed on the applications side (here in KDE desktop). But this issue exists over many years and there is no progress. There are probably many other applications and desktop environments with the same problem.

**Comment by keszybz** [comment]
It's absolutely crucial that we look at access time of files. After all, if somebody is using them, they should not be deleted. This even applies to things like copying a file to /tmp to have copy for comparison or whatnot — the file could have modification time in the past, but be newly created. The bug is in desktops that try to do the cleanup from inside the user session and bump the access time.

Doing cleanup from the user session doesn't make sense for two reasons
- first, you bump the access time, since not doing that requires root privileges,
- second, cleanup stop working as soon as you log out.
  The second is a deal-breaker on a multi-user machine, the first is deal-breaker in general. So the solution is to simply rip out or disable that part of the DE.

https://bugzilla.gnome.org/show_bug.cgi?id=747737

**Comment by poettering** [comment]
Yeah, this really sounds like a bug in your desktop environment. It should not open random files unless you tell it so. And if you do tell it so, then this should disable the automatic clean-up the way it currently does.

I really don't think it's a DE's business to muck around in /tmp and touch the atime of all files there, unless it does that on user request.

**Comment by bjoernv** [comment]
The DE people see this not as a bug, but as a feature.

The KDE filemanager Dolphin (and other programs which use the same API) open all files in a directory, read some bytes of each file, determine the MIME type according to a magic file (like /usr/share/misc/magic) and (optionally) create a preview for each file. The opening actions update the atime.

The problem is, that the user can not disable the MIME type determination globally of for some directories. Personally I do not need the MIME type for each file in temp directories, but I need (or like to have) a working cleanup function for temp directories.

KDE seems to use functions like  KIO::mimetype:
Doc: http://api.kde.org/frameworks-api/frameworks5-apidocs/kio/html/namespaceKIO.html#abdf502fa5febb734ccd584d8c3e4a325
Source: http://api.kde.org/frameworks-api/frameworks5-apidocs/kio/html/mimetypejob_8cpp_source.html

I see, that ignoring the atime in systemd-tmpfiles at all it not generally a good solution. A problem comes up, if a user copies a file with "cp -p" to a temp directory. mtime will be preserved in this case and systemd-tmpfiles may delete the file soon.

Thanks anyway. With this information in the hindquarters I can go to the KDE people again. The linked GNOME bug is related too.

**Comment by keszybz** [comment]
I guess KDE checks those thumbnails if you open the directory, right? I think that's OK, and it's OK if bumps the access time and delays the cleanup. After all, you _are_ accessing those files (at least some of them). Such behaviour would be problematic if it was automatic, without any user action, like in the gnome /tmp-cleaner which runs whenever the user is logged in.

**Comment by bjoernv** [comment]
KDE not only checks thumbnails. If checks every file with matching read permissions. Until now, I haven't found out, if I manually have to open a temp file directory in filemanager or if the process is started somehow automatically (e.g. when the Desktop icons are drawn or when I open another directory in a KDE application). The Kernel audit subsystem may help to evaluate the process, which opens all my temp files regularly. Baloo (the file indexer) is also a candidate, but I haven't configured it to index temp files.

**Comment by poettering** [comment]
If the user explicitly pointed the file browser to /tmp, then it's completely OK if the file browser opens the files in it to see what they contain. In this case it's the right thing that the atimes get bumped, so the behaviour is right.

Problematic is behavour of DEs if the keep iterating through all files in /tmp all the time in the background (which GNOME appears to do), which is really buggy and broken.

**Comment by bjoernv** [comment]
BTW, I found the "wrongdoer" with the Kernel audit subsystem. It was Mozilla Firefox together with the KDE integration. If I download a file with Firefox, I usually use the "save as..." function and save the download in /var/tmp. Since I do this often, the atime of all my files in /var/tmp are updated often and get never cleared by systemd-tmpfiles.

The following entry in /etc/audit/audit.rules logs all read/write/attribute-change file accesses within the directories /tmp and /var/tmp:

```
# Temp directories
-a exit,always  -F dir=/tmp -F perm=war -F key=temp-access
-a exit,always  -F dir=/var/tmp -F perm=war -F key=temp-access
```

I manually downloaded a file "mypackage.rpm" in Firefox with the "save as" menu entry.

This is an example entry queried with "ausearch -f /var/tmp/"

```
time->Thu Apr  7 19:44:06 2016
type=PROCTITLE msg=audit(1460051046.361:551474): proctitle="/usr/lib64/firefox/firefox-bin"
type=PATH msg=audit(1460051046.361:551474): item=0 name="/var/tmp/example.txt" inode=40766394 dev=08:16 mode=0100644 ouid=1000 ogid=201 rdev=00:00 nametype=NORMAL
type=CWD msg=audit(1460051046.361:551474):  cwd="/home/myuser"
type=SYSCALL msg=audit(1460051046.361:551474): arch=c000003e syscall=2 success=yes exit=139 a0=7f53c514ce00 a1=40000 a2=0 a3=0 items=1 ppid=22206 pid=28338 auid=1000 uid=1000 gid=201 euid=1000 suid=1000 fsuid=1000 egid=201 sgid=201 fsgid=201 tty=pts0 ses=11 comm="pool" exe="/usr/lib64/firefox/firefox-bin" key="temp-access"
```

"syscall=2" is the "open" syscall (see "ausyscall 2"). The opened file "/var/tmp/example.txt" itself is old and is not affected by the download. But the atime of this and all other files with read-access is updated.

A package named mozilla-kde4-integration builds the bridge between Firefox and the KDE file open/save dialogs. The bridge in action can be seen, if I start "pstree -a" while the "save as" dialog is open:

  |   |-bash
  |   |   |-firefox https://software.opensuse.org/package/kio
  |   |   |   |-kmozillahelper
  |   |   |   |   |-2*[{QInotifyFileSys}]
  |   |   |   |   `-{QProcessManager}

Other desktop programs like LibreOffice use such KDE integration bridges too.

I will probably uninstall the bridges and continue to search the next "wrongdoer". May be not only the "open/save as" dialogs from KDE behave like described.
