### ISSUE TITLE
systemd-cryptenroll and systemd-cryptsetup compatibility

### ISSUE THREAD

**Issue by glance-** [systemd/systemd#29743]
### systemd version the issue has been seen with

253 and main (6cd1f6546c6c3709f31b)

### Used distribution

Custom

### Linux kernel version used

6.1.59

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

To use systemd-cryptenroll with against a specific pcr value, I built a main version of systemd-cryptenroll and used that to enroll against a tpm and pcr 7 of a specific hash.

As far as I've managed to read the documentation, I haven't seen any references that states in which way different versions might be incompatible with each other, thus I expected the unlocking procedure to be compatible with newer enrollment when the pcr hash is in the expected state.

### Unexpected behaviour you saw

When trying to unlock that device with systemd-cryptsetup v253 this ends in failure.

### Steps to reproduce the problem

Enroll a encrypted device against tpm with systemd-cryptenroll from main, and try to unlock it with systemd-cryptsetup from v253.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/sda2.
Automatically discovered security TPM2 token unlocks volume.
WARNING:esys:../tpm2-tss/src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error 
ERROR:esys:../tpm2-tss/src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df) 
Failed to load HMAC key in TPM: tpm:parameter(1):integrity check failed
TPM2 operation failed, falling back to traditional unlocking: State not recoverable
```

**Comment by glance-** [comment]
I'm not sure what compatibility between different versions of systemd-cryptenroll/systemd-cryptsetup is expected so this can either be that i've missed some documentation, documentation can be missing or there's some kind of incompatibility that is expected but not documented.

**Comment by glance-** [comment]
If I enroll the device with a systemd-cryptenroll from main I can unlock that device as expected with a systemd-cryptsetup from main.

**Comment by bluca** [comment]
Generally these are backward-compatible, but not forward-compatible - ie a disk enrolled with an older version, can be unlocked with the new version. But not viceversa, because new fields might be added, that the old version can't deal with.

**Comment by poettering** [comment]
Yes, old enrollments should always be able to be unlocked with new systemd-cryptsetup. But new enrollments not necessarily with old systemd-cryptsetup.

**Comment by poettering** [comment]
> ```shell
> WARNING:esys:../tpm2-tss/src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error 
> ERROR:esys:../tpm2-tss/src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df) 
> Failed to load HMAC key in TPM: tpm:parameter(1):integrity check failed
> TPM2 operation failed, falling back to traditional unlocking: State not recoverable
> ```

This is an error from the TPM2 when we load the encrypted key into the TPM so that it unseals it for us. This is a very early step, done long before any PCR validation takes place. This should generally always work, except if the enrollment originates from a different TPM (or the TPM got reset since then, which in many ways is the same thing).
