### ISSUE TITLE
Socket configuration does not honor /etc/services port names

### ISSUE THREAD

**Issue by hontvari** [systemd/systemd#29757]
### systemd version the issue has been seen with

253.5-1ubuntu6

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-10-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

For example overriding ssh.socket using systemctl edit ssh.socket and adding:
[Socket]
ListenStream=ssh-alt

assuming ssh-alt is defined in /etc/services, for example as 1234/tcp.
I expect that after reboot sshd will listen on both 22 and 1234.

### Unexpected behaviour you saw

sshd only listens on 22 after reboot

### Steps to reproduce the problem

See above

**Comment by YHNdnzj** [comment]
IIRC we've never supported `/etc/services`. It's not mentioned in `systemd.socket(5)` either, so why do you expect it work?

Anyways, converting this to an RFE.

**Comment by hontvari** [comment]
> IIRC we've never supported `/etc/services`. It's not mentioned in `systemd.socket(5)` either, so why do you expect it work?

I noticed that it is not mentioned in man either. /etc/services and similar alias definitions (like the ones in /etc/ip2route2 or /etc/ethers) are supported everywhere in Linux where more or less meaningless numbers must be displayed/specified. With or without mentioning them in the man page. Of course there may be places where they aren't, but I have not met them personally. 

> Anyways, converting this to an RFE.
I understand.

**Comment by poettering** [comment]
Yeah we don't support this, and it's 2023, so this is not going to be added anymore.

/etc/services is a terrible idea, and it should be phased out.

Sorry if that's disappointing.
