### ISSUE TITLE
RFE: add --json= mode support to resolvectl query

### ISSUE THREAD

**Issue by ManuLinares** [systemd/systemd#29755]
### systemd version the issue has been seen with

systemd 254.5-1

### Used distribution

Arch

### Linux kernel version used

6.5.9

### CPU architectures issue was seen on

x86_64

### Component

resolvectl

### Expected behaviour you didn't see

output in json format

### Steps to reproduce the problem

`resolvectl query google.com --json=short`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
resolvectl query --json=short google.com
google.com: 2800:3f0:4002:80a::200e            -- link: eno1
            142.251.133.14                     -- link: eno1

-- Information acquired via protocol DNS in 688us.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
-- Data from: cache
```

**Comment by rpigott** [comment]
Should probably document that the option is only supported for a few verbs, e.g. `resolvectl --json=short show-cache`

**Comment by poettering** [comment]
Let's turn this into an RFE issue asking for this new functionality.

**Comment by gdamjan** [comment]
also `resolvectl service` should support json output.

**Comment by cyqsimon** [comment]
I'm very surprised that `--json` does not support the `status` verb, which I believe has a very compelling use case.

Should I open a new issue for this?

**Comment by yuwata** [comment]
> I'm very surprised that `--json` does not support the `status` verb, which I believe has a very compelling use case.
> 
> Should I open a new issue for this?

@cyqsimon Yes, please.
