### ISSUE TITLE
RFE: networkd: honour a new ID_NET_MANAGED_BY udev propery or so

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#29768]
Right now NetworkManager and networkd are happy to fight for ownership of network interfaces. That kinda sucks.

Here's an idea: let's make both unconditionally honour a NET_MANAGED_BY= udev property, and if set to any string that is different from some identifier for the respective project, the interfaces will be left unmanaged.

And example:

1. systemd-networkd would leave all interfaces unmanaged where NET_MANAGED_BY= is set to a string other than io.systemd.networkd
2. NetworkManager would leave all interfaces unmanaged where NET_MANAGED_BY= is set set to a string other than dev.networkmanager.nm

If the property is not set we'll live in the wild-west as before. 

What's the usecase?

Allowing the admin to make an explicit choice which project shall manage which interfaces. (Could even be generated dynamically via rules files in /run/)

What's not the usecase?

This is not a locking concept: if both NM and networkd are told to configure a device then they will still fight for it.

**Comment by poettering** [comment]
Since this obviously means NetworkManager needs to be on board too with this, @thom311 would this make sense to you?

**Comment by thom311** [comment]
NetworkManager already honors `NM_UNMANAGED=1` (it defaults to managing interfaces that it finds, under the assumption that you run NetworkManager to use it).

Supporting a `NET_MANAGED_BY=` (in addition) makes sense to me.

**Comment by yuwata** [comment]
-> #29782.

**Comment by poettering** [comment]
As discussed over at #29782 let's please clal the prop ID_NET_MANAGED_BY=, i.e. let's stick to the `ID_` prefix, which we traditionally use for systemd/udev's properties, to ensure we don't collide with unprefixed names the kernel includes in its uevents.
