### ISSUE TITLE
Crash on hppa boot with systemd-254 (MemoryDenyWriteExecute isn't supported)

### ISSUE THREAD

**Issue by thesamesam** [systemd/systemd#29775]
### systemd version the issue has been seen with

254

### Used distribution

Gentoo

### Linux kernel version used

6.5.9

### CPU architectures issue was seen on

parisc

### Component

systemd

### Expected behaviour you didn't see

Originally reported downstream in Gentoo at https://bugs.gentoo.org/916469.

The system fails to start up (ditto in an nspawn container) because the systemd-udevd unit (among others) tries to use MemoryDenyWriteExecute.

This is perfectly reasonable, but on HPPA, we need executable stacks still, so `MemoryDenyWriteExecute` doesn't work.

When I wired up seccomp in https://github.com/systemd/systemd/commit/344e6b62fceea0f5fac1f1efcff7e0ccf4a4e3c8#diff-60141857536525beb87708eaf458438b24ce034aed48172f0db7ee1cd1acc648R1723, I made sure to exclude it, but as of systemd-254 (https://github.com/systemd/systemd/pull/25276), the new attempted `prctl` method "succeeds" before seccomp is attempted (which would correctly fail).

We need to wire up some exclusion in `apply_memory_deny_write_execute`, although I haven't yet decided which way would be cleanest. Suggestions welcome.

### Unexpected behaviour you saw

Failure to boot because `MemoryDenyWriteExecute` is used on HPPA where it is unsupported.

### Steps to reproduce the problem

Boot systemd-254 on HPPA.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Oct 29 08:17:30 ladder systemd-nspawn[12550]:          Starting systemd-network-generator.service...
Oct 29 08:17:30 ladder systemd-nspawn[12550]:          Starting systemd-remount-fs.service...
Oct 29 08:17:30 ladder systemd-nspawn[12550]:          Starting systemd-tmpfiles-setup-dev-early.service...
Oct 29 08:17:30 ladder systemd-nspawn[12550]: [  OK  ] Mounted dev-hugepages.mount.
Oct 29 08:17:30 ladder systemd-nspawn[12550]: systemd-journald.service: Main process exited, code=killed, status=11/SEGV
Oct 29 08:17:30 ladder systemd-nspawn[12550]: systemd-journald.service: Failed with result 'signal'.
Oct 29 08:17:30 ladder systemd-nspawn[12550]: [FAILED] Failed to start systemd-journald.service.
Oct 29 08:17:30 ladder systemd-nspawn[12550]: See 'systemctl status systemd-journald.service' for detail

...

Oct 29 09:36:12 ladder (md-udevd)[25741]: systemd-udevd.service: Enabled MemoryDenyWriteExecute= with PR_SET_MDWE
Oct 29 09:36:12 ladder (md-udevd)[25741]: systemd-udevd.service: Executing: /usr/lib/systemd/systemd-udevd
Oct 29 09:36:12 ladder systemd[1]: systemd-journald.service: Received EPOLLHUP on stored fd 45 (stored), closing.
Oct 29 09:36:12 ladder systemd[1]: Received SIGCHLD from PID 25741 (systemd-udevd).
Oct 29 09:36:12 ladder systemd[1]: Child 25741 (systemd-udevd) died (code=killed, status=11/SEGV)
Oct 29 09:36:12 ladder systemd[1]: systemd-udevd.service: Child 25741 belongs to systemd-udevd.service.
Oct 29 09:36:12 ladder systemd[1]: systemd-udevd.service: Main process exited, code=killed, status=11/SEGV
░░ Subject: Unit process exited
```

**Comment by thesamesam** [comment]
I don't know why the prctl call succeeds and I'll report it upstream to the kernel, but that doesn't do us much good anyway as it may not get backported if they even agree to fix it.

**Comment by poettering** [comment]
This looks like a kernel bug. If the functionality doesn't work, the prctl should not succeed.

**Comment by hdeller** [comment]
I have this Linux kernel patch, which might fix it.
Sam, would be nice if you could test:
https://git.kernel.org/pub/scm/linux/kernel/git/deller/parisc-linux.git/commit/?h=for-next-maybe2&id=339b41ec357c24c02ed4aed6267dbfd443ee1e8e

**Comment by thesamesam** [comment]
@hdeller There's a typo in your patch (`errir` instead of `error`). Fixing that doesn't help though, as systemd handles `ENODEV` differently (can't grab the logs).

But systemd handles `EINVAL` fine and the fallback to seccomp is OK, as I fixed that codepath within the seccomp handling a while ago to not try to prevent executable stacks. So the fallback with `EINVAL` is ok (changing `ENODEV` -> `EINVAL` in your patch works) as while this function carries on, the seccomp logic does the right thing.

**Comment by hdeller** [comment]
Thanks for testing, @thesamesam !
I've fixed the typo, changed it to return EINVAL, and added a Tested-by from you.
Would be great if you could double-check again.
Fixed version is now in the for-next git repo and will go upstream in the next 0-2 weeks:
https://git.kernel.org/pub/scm/linux/kernel/git/deller/parisc-linux.git/log/?h=for-next
specifically:
https://git.kernel.org/pub/scm/linux/kernel/git/deller/parisc-linux.git/commit/?h=for-next&id=0c7f7f50ed23f4ead1ff0a6510991dc87ea70e59

**Comment by thesamesam** [comment]
Thanks @hdeller! Confirmed that version works.

**Comment by thesamesam** [comment]
This is fixed on the kernel side now, so closing. Thanks.
