### ISSUE TITLE
`systemd-growfs-root.service` not working for root partition marked with GPT autogrow flag

### ISSUE THREAD

**Issue by septatrix** [systemd/systemd#29791]
### systemd version the issue has been seen with

systemd 252 (252.12-1~deb12u1)

### Used distribution

Debian 12 ("Bookwork")

### Linux kernel version used

6.1.0-12-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator, systemd-growfs

### Expected behaviour you didn't see

Partitions with the `SD_GPT_FLAG_GROWFS` flag (e.g. created using `mkosi` or `systemd-repart`) should be detected by `gpt-auto-generator` and the filesystem should be grown.

### Unexpected behaviour you saw

Nothing happened and the filesystem stayed the same size even though the fs did not fill the whole space of the partition (grown by `systemd-repart`).

### Steps to reproduce the problem

Create a image with mkiso with a partition which grows upon boot. Boot that image on a disk and compare the partition size reported by `systemd-repart` and `df -h`.

This is cause by always setting the growfs parameter of `add_mount` to false in `add_root_mount`:

https://github.com/systemd/systemd/blob/448a21abbd23d18c0ed50c894b9f73118112dc55/src/gpt-auto-generator/gpt-auto-generator.c#L730-L740

More information can be seen in the mail thread: https://lists.freedesktop.org/archives/systemd-devel/2023-October/049639.html

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
No messages about errors were shown in the dmesg output or journal.
```

**Comment by Cornelicorn** [comment]
I would consider this a bug not a feature request.
The manpage of `systemd-gpt-auto-generator` says it's implementing the DPS, [which says](https://uapi-group.org/specifications/specs/discoverable_partitions_specification/#partition-attribute-flags)

> For the root, /usr/, home, server data, variable data, temporary data and extended boot loader partitions, the partition flag bit 59 ("grow-file-system", SD_GPT_FLAG_GROWFS) may be used to mark a partition for automatic growing of the contained file system to the size of the partition when mounted. Tools that automatically mount disk image with a GPT partition table are suggested to implicitly grow the contained file system to the partition size they are contained in, if they are found to be smaller. This flag is without effect on partitions marked “read-only”.

The manpage on `repart.d` also states in the section for `GrowFileSystem`

> Note that the three flags affect only automatic partition mounting, as implemented by [systemd-gpt-auto-generator(8)](https://www.freedesktop.org/software/systemd/man/latest/systemd-gpt-auto-generator.html#) or the --image= option of various commands (such as [systemd-nspawn(1)](https://www.freedesktop.org/software/systemd/man/latest/systemd-nspawn.html#)).

Implying that `systemd-gpt-auto-generator` respects this flag.

**Comment by yuwata** [comment]
Indeed...

**Comment by bluca** [comment]
I am trying the following approach: add a new flag to the growfs binary, set it from gpt-auto-generator, and use it to conditionalise growing the filesystem on the gpt flag being set
