### ISSUE TITLE
Allow management of individual units using polkit authorization

### ISSUE THREAD

**Issue by djmattyg007** [systemd/systemd#2980]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> v229
### Used distribution

> Arch Linux

It would be nice if there was a way to allow management of individual units using polkit's authorisation mechanisms, instead of blindly allowing allowed users to manage all units or none.

I'm not sure if this functionality already exists or not as it's a bit difficult to find useful documentation on systemd's integration with polkit (most search results seem to be about polkit failing to start).

**Comment by poettering** [comment]
We already pass that info to PK, it's just a matter of using this in your PK policies. Specifically the PK details of `unit` and `verb` are passed to PK, which may be used in policies. For details on how to do this, see the PK docs.

**Comment by djmattyg007** [comment]
Thanks for the pointer, it's most appreciated.

**Comment by djmattyg007** [comment]
For anyone looking at this in the future, here's an example polkit rules file for making this work: https://gist.github.com/djmattyg007/6b5e845ad1140c8a0fa66b64f953bf9a
