### ISSUE TITLE
logind: Doesn't inhibit suspend when inhibited in the same session

### ISSUE THREAD

**Issue by agx** [systemd/systemd#29818]
### systemd version the issue has been seen with

254

### Used distribution

Debian

### Linux kernel version used

6.5.0-2-amd64

### CPU architectures issue was seen on

None

### Component

systemd-logind

### Expected behaviour you didn't see

Adding a sleep inhibitor as user like

```sh
systemd-inhibit --what=sleep --mode=block bash
```

and then issuing `suspend`:

```sh
busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager SuspendWithFlags t 1
```

in the same session should prevent suspend as there is an inhibitor set.

### Unexpected behaviour you saw

The above does *not* prevent suspend for me. 

(`systemctl suspend` does inhibit suspend but that's because it checks for inhibitors first.)

### Steps to reproduce the problem

See above under "expected behaviour".

**Comment by JackDinn** [comment]
So what was the answer here? I have been going crazy trying to get this to work but even though i run something under systemd-inhibit i can still suspend, shutdown etc

I am testinbg with just leafpad, i added all --what flags.
`systemd-inhibit --what=shutdown:sleep:idle:handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch --why="Testing inhibition" leafpad`

It shows as a listed inhibit:
```
❱systemd-inhibit --list
WHO            UID  USER PID    COMM            WHAT                                                                                           WHY                         >
ModemManager   0    root 638    ModemManager    sleep                                                                                          ModemManager needs to reset >
NetworkManager 0    root 543    NetworkManager  sleep                                                                                          NetworkManager needs to turn>
UPower         0    root 4305   upowerd         sleep                                                                                          Pause device polling        >
PowerDevil     1000 greg 4379   org_kde_powerde handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch                     KDE handles power events    >
leafpad        1000 greg 464257 systemd-inhibit shutdown:sleep:idle:handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch Testing inhibition          >

5 inhibitors listed.
```
But i can still manually suspends or shutdown?

What was the answer here?

```
System:
  Kernel: 6.9.5-1-MANJARO arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.0.5 Distro: Manjaro Linux
Machine:
  Type: Desktop System: Dell product: OptiPlex 7050 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 055H3G v: A01 serial: <superuser required> UEFI: Dell
    v: 1.26.0 date: 08/20/2023
```

**Comment by mpeter50** [comment]
Currently you cannot do that without replacing the shutdown-like commands with a custom wrapper that enforces it.
However, it looks like the linked PR will fix it. I'm so happy that inhibitors will become actually useful, thank you!
