### ISSUE TITLE
systemd-networkd inventing routes for nameservers

### ISSUE THREAD

**Issue by neonknight** [systemd/systemd#29820]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

linux-image-6.1.0-13-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Unexpected behaviour you saw

A system configuring itself using "traditional" network setup methods of Debian (e.g. ifup invoking dhclient) would only set a default route, a route for the local network, and routes pushed via DHCP. e.g.:
```
# route -n
0.0.0.0         10.1.0.1        0.0.0.0         UG    0      0        0 ens3
10.0.0.0        10.1.0.5        255.0.0.0       UG    0      0        0 ens3
10.1.0.0        0.0.0.0         255.255.0.0     U     0      0        0 ens3
```

After switching to systemd-networkd additional routes for every nameserver pointing to default gateway are added:
```
# route -n
0.0.0.0         10.1.0.1        0.0.0.0         UG    1024   0        0 ens3
10.0.0.0        10.1.0.5        255.0.0.0       UG    1024   0        0 ens3
10.1.0.0        0.0.0.0         255.255.0.0     U     1024   0        0 ens3
10.1.0.1        0.0.0.0         255.255.255.255 UH    1024   0        0 ens3
10.1.0.5        0.0.0.0         255.255.255.255 UH    1024   0        0 ens3
10.1.0.53       0.0.0.0         255.255.255.255 UH    1024   0        0 ens3
10.2.0.53       10.1.0.1        255.255.255.255 UGH   1024   0        0 ens3
# cat /etc/resolv.conf
nameserver 10.1.0.53
nameserver 10.2.0.53
```

This may lead to nameservers being unreachable

### Steps to reproduce the problem

apt remove ifupdown; systemctl enable systemd-networkd; reboot

**Comment by neonknight** [comment]
Thank you for the answer, however neither setting it to true nor false changed the behaviour. Added it to /etc/systemd/networkd.conf and /etc/systemd/network/*.network. Routes are still created :shrug:

**Comment by poettering** [comment]
did you reload the configuration and upped and downed the interface?

**Comment by poettering** [comment]
How does your relevant .network file look like precisely?

what does "networkctl status" on the interface say?

**Comment by neonknight** [comment]
I rebooted and after reboot the routes are back.

the .network file looks like this:
```
[Match]
MACAddress=xx:xx:xx:xx:xx:xx
Name=ens3

[Network]
DHCP=ipv4
DNSDefaultRoute=false
```

and networkctl reports:
```●        State: routable                                      
  Online state: online                                        
       Address: 10.1.3.42 on ens3
                2001:xx:xx:xx::xx on ens3
                fe80::xx on ens3
       Gateway: 10.1.0.1 on ens3
                fe80::yy on ens3
           DNS: 10.1.0.53
                10.2.0.53
                
ens3: Configuring with /etc/systemd/network/ens3.network.
ens3: Link UP
ens3: Gained carrier
ens3: DHCPv4 address 10.1.3.42/16, gateway 10.1.0.1 acquired from 10.1.0.4
ens3: Gained IPv6LL
```

**Comment by andreaskem** [comment]
Maybe
```
       RoutesToDNS=
           When true, the routes to the DNS servers received from the DHCP server will be
           configured. When UseDNS= is disabled, this setting is ignored. Defaults to
           true.
```
or
```
       UseRoutes=
           When true (the default), the static routes will be requested from the DHCP
           server and added to the routing table with a metric of 1024, and a scope of
           global, link or host, depending on the route's destination and gateway. If the
           destination is on the local host, e.g., 127.x.x.x, or the same as the link's
           own address, the scope will be set to host. Otherwise if the gateway is null
           (a direct route), a link scope will be used. For anything else, scope defaults
           to global.
```
?

**Comment by neonknight** [comment]
neither option (resp. combination of all three options) influenced the routing table.

**Comment by yuwata** [comment]
Please read the man page for `RoutesToDNS=`. Note that it must be in [DHCPv4] section instead of [Network].

**Comment by neonknight** [comment]
Thank you @yuwata the following snippet in /etc/systemd/network/*.network file restores the expected behaviour:
```
[DHCPv4]
RoutesToDNS=false
```
