### ISSUE TITLE
sometimes "systemd-coredump[<PID>]: Coredump file descriptor missing." is seen

### ISSUE THREAD

**Issue by pmattern** [systemd/systemd#2984]
### Submission type

Bug report
### systemd version the issue has been seen with

229
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

Core dumps of a particular application triggered the same way should be handled consistently.
### In case of bug report: Unexpected behaviour you saw

Most of the time core dumps as depicted above are handled as known from versions ≤ 228 , that is a stack trace gets written to the journal and the core dump saved in `/var/lib/systemd/coredump`.

But sometimes there's just a message

> "systemd-coredump[<PID>]: Coredump file descriptor missing."

in the journal and no further processing takes place.
### In case of bug report: Steps to reproduce the problem

Trigger a crash of a particular application the same way several times one after the other. Problem takes place sporadically only but normally gets manifest that way after several crashes.
### additional findings

Limited resources like disk space don't seem to be involved as the regular handling can also be seen after the sparse one.
Problem can only be seen when a real crash due to a problem takes places. Couldn't provoke it by `kill -SIGSEGV` so far.
Configuration files `/etc/systemd/coredump.conf`and `/usr/lib/sysctl.d/50-coredump.conf` are the same as upstream. The only apparent difference compared to 228 is an additional argument `%c` in the latter but removal just triggers a message

> Failed to parse resource limit: <binary>"

and the dumps don't get saved either.
Problem could not bee seen in versions ≤ 228 at all.

**Comment by poettering** [comment]
hmm, the coredump fd missing message is really weird. I have no idea how it can happen that the fd is missing... I am really surprised by that...

is the system under any load when this happens?

**Comment by pmattern** [comment]
> is the system under any load when this happens?

Besides I didn't look at the load too thoroughly so far this can rather be ruled out.
After stumbling upon the problem tests were performed with `lxqt-leave`, a tiny GUI of LXQt handling the session and affected by [crashes involving DRI driver swrast](https://bugs.kde.org/show_bug.cgi?id=360433#c2), while no single other application was running.

But your question made me realize that both my findings and the [only other manifestation](https://de.manjaro.org/index.php?topic=5378.msg40969#msg40969) (German) I found so far took place in KVM/QEMU guests.

So eventually a problem involving the instantiated services introduced in 229 plus the characteristics of virtual hardware, maybe the storage devices?

**Comment by evverx** [comment]
Could you provide the output of

```
journalctl | grep -F 'Failed to send coredump fd'
```

?

Do you have something like this:

```
Apr 18 21:28:03 systemd-testsuite systemd-coredump[234]: Failed to send coredump fd: Bad file descriptor
...
Apr 18 21:28:03 systemd-testsuite systemd[235]: systemd-coredump@0-234-0.service: Executing: /lib/systemd/systemd-coredump
Apr 18 21:28:03 systemd-testsuite systemd-coredump[235]: Coredump file descriptor missing.
```

?

**Comment by pmattern** [comment]
There's no string `Failed to send coredump fd` in the journal here. Normally the messages are like this

```
Apr 19 14:14:35 arch-64-lxqt-git kernel: traps: lxqt-leave[1493] trap divide error ip:7fad298afc19 sp:7ffd37504e38 error:0 in libpthread-2.23.so[7fad298a2000
Apr 19 14:14:35 arch-64-lxqt-git systemd[1]: Started Process Core Dump (PID 1496/UID 0).
Apr 19 14:14:35 arch-64-lxqt-git systemd-coredump[1497]: Coredump file descriptor missing.
```

so the message about the missing descriptor is right where normally the stack trace starts.
If you stated the OS you're running and which way you triggered the messages stated above I could eventually try and reproduce.

**Comment by evverx** [comment]
@pmattern , I'm trying to trigger [that code](https://github.com/systemd/systemd/blob/0c7739039b090a2c1f8c894c0e6eb75fc25663a0/src/coredump/coredump.c#L820):

```
if (!found) {
    log_error("Coredump file descriptor missing.");
    r = -EBADMSG;
    goto finish;
}
```

One way is the ["send_one_fd"](https://github.com/systemd/systemd/blob/0c7739039b090a2c1f8c894c0e6eb75fc25663a0/src/coredump/coredump.c#L894)-error:

```
r = send_one_fd(fd, input_fd, 0);
if (r < 0)
    return log_error_errno(r, "Failed to send coredump fd: %m");
```

I trigger that error by closing `input_fd`.
But seems like it's not your case (you don't see `Failed to send coredump fd`)

Another way is the signal in the middle of the message sending:

```
@@ -884,20 +885,22 @@ static int send_iovec(const struct iovec iovec[], size_t n_iovec, int input_fd)

         for (i = 0; i < n_iovec; i++) {
                 ssize_t n;
                 assert(iovec[i].iov_len > 0);

                 n = send(fd, iovec[i].iov_base, iovec[i].iov_len, MSG_NOSIGNAL);
                 if (n < 0)
                         return log_error_errno(errno, "Failed to send coredump datagram: %m");
         }

+        raise(SIGTERM);
+
         r = send_one_fd(fd, input_fd, 0);
         if (r < 0)
                 return log_error_errno(r, "Failed to send coredump fd: %m");

         return 0;
 }
```

**Comment by evverx** [comment]
Try to set your `kernel.core_pattern`:

```
|/usr/bin/strace -s 500 -v -o /coredump-handler -ff /lib/systemd/systemd-coredump %P %u %g %s %t %c %e
```

So, we'll see what's going on.
I.e.

```
Apr 19 23:20:08 systemd-testsuite systemd[1]: Started Process Core Dump (PID 471/UID 0).
Apr 19 23:20:08 systemd-testsuite systemd-coredump[472]: Coredump file descriptor missing.
```

```
$ cat /coredump-handler.471
...
sendto(3, "COREDUMP_TIMESTAMP=1461108007000000", 35, MSG_NOSIGNAL, NULL, 0) = 35
sendto(3, "MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1", 43, MSG_NOSIGNAL, NULL, 0) = 43
sendto(3, "PRIORITY=2", 10, MSG_NOSIGNAL, NULL, 0) = 10
tgkill(471, 471, SIGTERM)               = 0
--- SIGTERM {si_signo=SIGTERM, si_code=SI_TKILL, si_pid=471, si_uid=0} ---
+++ killed by SIGTERM +++
```

**Comment by pmattern** [comment]
So I had another look using `strace` as you proposed, the only exception was that I set the path of `systemd-coredump` to `/usr/lib/systemd/` in order to avoid the symbolic link that `/lib/` is on Arch Linux.
Aside from the regular handling of core dumps the only result was

```
Mai 06 19:09:19 arch-64-lxqt-git kernel: traps: lxqt-leave[692] trap divide error ip:7f9f059dbc19 sp:7ffc180197b8 error:0 in libpthread-2.23.so[7f9f059ce000+18000]
Mai 06 19:09:19 arch-64-lxqt-git kernel: Core dump to |/usr/bin/strace -s 500 -v -o /coredump-handler -ff /usr/lib/systemd/systemd-coredump 692 1002 1002 8 1462554559 18446744073709551615 lxqt-leave pipe failed
```

in the journal. As no processing of the core dump in question took place I can only assume this output is affecting crashes where message "Coredump file descriptor missing." could have been seen otherwise.
After reverting `kernel.core_pattern` to the value provided by upstream `50-coredump.conf` the usual mixture of regular handling and message "Coredump file descriptor ..." could be seen again.

**Comment by evverx** [comment]
> Core dump to |/usr/bin/strace ... failed

What is the output of:

```
type -p strace
```

and

```
findmnt /
```

?

**Comment by pmattern** [comment]
```
$ type -p strace 
/usr/bin/strace

$ findmnt / 
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/vda3 ext4   rw,relatime,data=ordered
```

**Comment by evverx** [comment]
Well, is

```
sudo sh -c 'echo DummyDump | /usr/bin/strace -s 500 -v -o /coredump-handler -ff /usr/lib/systemd/systemd-coredump 692 1002 1002 8 1462554559 18446744073709551615 lxqt-leave'
```

working?

**Comment by pmattern** [comment]
Yes. After giving the respective user permissions in `/etc/sudoers` that invocation writes file `/coredump-handler.<PID>`.

**Comment by evverx** [comment]
Hm, interesting.

What is the output of

```
echo '|/usr/bin/strace -s 500 -v -o /coredump-handler -ff /usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e' >/proc/sys/kernel/core_pattern
sh -c 'kill -SEGV $$'
journalctl --sync
journalctl -b | grep -i core | tail
```

?

**Comment by pmattern** [comment]
The corresonding lines in the journal are

```
Mai 07 00:34:38 arch-64-openbox systemd[1]: Started Process Core Dump (PID 2937/UID 0).                                                                      
Mai 07 00:34:38 arch-64-openbox systemd-coredump[2938]: Process 2934 (sh) of user 0 dumped core.
```

(As I need my VM running LXQt for something different right now the findings in my last two comments were from a VM which lacks binary `lxqt-leave` but is set up exactly the same way otherwise. If I got the commands you asked me to invoke right this should be ok, shouldn't it?)

**Comment by evverx** [comment]
> If I got the comments you asked me to invoke right this should be ok

Yeah, it's ok.

Anyway, try to check `strace` and add the `-D` option:

```
|/usr/bin/strace -D -s 500 -v -o /coredump-handler -ff /usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e
```

**Comment by pmattern** [comment]
Switch `-D` of `strace` seemed to do the trick.

You may find results involving `lxqt-leave` as depicted [above](https://github.com/systemd/systemd/issues/2984#issuecomment-210423560) in a [Gist](https://gist.github.com/pmattern/92ac52774538a78597d0e170ff697376). In detail
1. `coredump-handler-strace-D_lxqt-leave_tiny0{1,2}`: Renamed files `/coredump-handler.<PID>` corresponding to crashes resulting in message "Coredump file descriptor missing." only. First and last of a series of crashes which all happened to yield this result in a row.
2. `coredump-handler-strace-D_lxqt-leave_regular01`: Renamed file `/coredump-handler.<PID>` corresponding to a crash which took place right after 1. and resulted in regular processing of the core dump.
3. `traces-strace-D_lxqt-leave_regular01`: Traces corresponding to 2. Namely stack trace as found in systemd's journal and backtrace by gdb after having `coredumpctl` hand the core dump to gdb.

Strangely crashes of KDE components triggered by that swrast issue as well in a VM set up the same way still resulted in nothing but that "pipe failed" output:

```
Mai 07 19:10:44 arch-64-div-des kwin_x11[585]: QXcbConnection: XCB error: 3 (BadWindow), sequence: 45250, resource id: 50331652, major code: 25 (SendEvent), minor code: 0
Mai 07 19:10:44 arch-64-div-des kwin_x11[585]: QXcbConnection: XCB error: 3 (BadWindow), sequence: 45286, resource id: 50331652, major code: 15 (QueryTree), minor code: 0
Mai 07 19:10:44 arch-64-div-des kernel: traps: systemsettings5[715] trap divide error ip:7fd3006cfc19 sp:7ffe75bc1688 error:0 in libpthread-2.23.so[7fd3006c2000+18000]
Mai 07 19:10:44 arch-64-div-des kernel: Core dump to |/usr/bin/strace -D -s 500 -v -o /coredump-handler -ff /usr/lib/systemd/systemd-coredump 715 1002 1002 8 1462641044 18446744073709551615 systemsettings5 pipe failed
```

**Comment by evverx** [comment]
`*-regular`:

```
sendmsg(3, {msg_name(0)=NULL, msg_iov(0)=[], msg_controllen=24, [{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, [0]}], msg_flags=0}, MSG_NOSIGNAL) = 0
```

`*-tiny`:

```
sendmsg(3, {msg_name(0)=NULL, msg_iov(0)=[], msg_controllen=24, [{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, [0]}], msg_flags=0}, MSG_NOSIGNAL) = 0
```

There is no difference. Hm.

Let's check the reading side:

``` sh
mkdir -p /etc/systemd/system/systemd-coredump@.service.d

cat <<'EOF' >/etc/systemd/system/systemd-coredump@.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/usr/bin/strace -D -s 500 -v -ff -o /coredump-reading-side /usr/lib/systemd/systemd-coredump
EOF

systemctl daemon-reload
```

So, we'll get:
- `coredump-handler.*`
- `coredump-reading-side.*`

**Comment by evverx** [comment]
Well, I've found  a race between [`ioctl(fd, FIONREAD, &l)`](https://github.com/systemd/systemd/blob/master/src/coredump/coredump.c#L749) and [`send()s`](https://github.com/systemd/systemd/blob/master/src/coredump/coredump.c#L853)

``` c
ioctl(3, FIONREAD, [29])                = 0
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"COREDUMP_UNIT=session-1.scope", 29}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 29
ioctl(3, FIONREAD, [0])                 = 0
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"", 0}], msg_controllen=0, msg_flags=MSG_TRUNC|MSG_CMSG_CLOEXEC}, MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 0
sendmsg(5, {msg_name(0)=NULL, msg_iov(4)=[{"PRIORITY=3\nSYSLOG_FACILITY=3\nCODE_FILE=src/coredump/coredump.c\nCODE_LINE=789\nCODE_FUNCTION=process_socket\nSYSLOG_IDENTIFIER=systemd-coredump\n", 141}, {"MESSAGE=", 8}, {"Coredump file descriptor missing.", 33}, {"\n", 1}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 183
```

> Warning:  Using  FIONREAD,  it  is
>               impossible  to  distinguish  the case where no datagram is pending from the case where the next pending datagram contains zero bytes of data.

Any chance you can test that patch: https://github.com/evverx/systemd/commit/31e58224e951d9c76d257f7d1e2a697789b5b005 ?

**Comment by pmattern** [comment]
_ad strace / files /coredump-_*
Meanwhile it pretty much looks like redirecting the core dumps via strace reduces the frequency at which the problem we're discussing here gets manifest. In particular, using a file `/etc/systemd/system/systemd-coredump@.service.d/override.conf` as you proposed the problem could not be seen at all any longer, no matter whether `kernel.core_pattern` was comprising `strace` as well or left at the default values defined in `/usr/lib/sysctl.d/50-coredump.conf`.
So no news regarding `strace`.

_ad evverx/systemd@31e5822_
Running that commit, installed by having Arch Linux AUR package [systemd-git](https://aur.archlinux.org/packages/systemd-git/) point to your branch `fix-2984`, the problem could not be seen any longer.
Cannot tell for sure whether this is due to the commit solving the problem or just by incident as the problem happened not to appear so far. But I've really triggered a bunch of crashes which various applications and if I'm not mistaken a race condition seems like a plausible cause of a problem that takes place sporadically only.

**Comment by evverx** [comment]
> In particular, using a file /etc/systemd/system/systemd-coredump@.service.d/override.conf as you proposed the problem could not be seen at all any longer

I'd like to label this issue as "heisenbug". But there is no such label:)

I reproduced that race reliably by slowing down a sender:

``` c
diff --git a/src/coredump/coredump.c b/src/coredump/coredump.c
index 01fdcfa..fae5049 100644
--- a/src/coredump/coredump.c
+++ b/src/coredump/coredump.c
@@ -857,6 +857,7 @@ static int send_iovec(const struct iovec iovec[], size_t n_iovec, int input_fd)
                 n = send(fd, iovec[i].iov_base, iovec[i].iov_len, MSG_NOSIGNAL);
                 if (n < 0)
                         return log_error_errno(errno, "Failed to send coredump datagram: %m");
+                sleep(1);
         }

         r = send_one_fd(fd, input_fd, 0);
```

Sender:

```
09:29:21.315906 socket(PF_LOCAL, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = 3
09:29:21.316627 connect(3, {sa_family=AF_LOCAL, sun_path="/run/systemd/coredump"}, 23) = 0
09:29:21.326863 sendto(3, "COREDUMP_UNIT=session-1.scope", 29, MSG_NOSIGNAL, NULL, 0) = 29
09:29:21.328259 nanosleep({1, 0}, 0x7ffeb77c1980) = 0
09:29:22.330338 sendto(3, "COREDUMP_PID=567", 16, MSG_NOSIGNAL, NULL, 0) = 16
09:29:22.331672 nanosleep({1, 0}, 0x7ffeb77c1980) = 0
09:29:23.333734 sendto(3, "COREDUMP_UID=0", 14, MSG_NOSIGNAL, NULL, 0) = 14
09:29:23.335682 nanosleep({1, 0}, 0x7ffeb77c1980) = 0
```

Receiver:

```
09:29:23.266403 connect(5, {sa_family=AF_LOCAL, sun_path="/run/systemd/journal/socket"}, 29) = 0
09:29:23.268354 ioctl(3, FIONREAD, [45]) = 0
09:29:23.269569 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"COREDUMP_UNIT=session-1.scope", 45}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 29
09:29:23.272049 ioctl(3, FIONREAD, [16]) = 0
09:29:23.272885 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"COREDUMP_PID=567", 16}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 16
09:29:23.273637 ioctl(3, FIONREAD, [0]) = 0
09:29:23.274250 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"", 0}], msg_controllen=0, msg_flags=MSG_TRUNC|MSG_CMSG_CLOEXEC}, MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 0
09:29:23.338616 sendmsg(5, {msg_name(0)=NULL, msg_iov(4)=[{"PRIORITY=3\nSYSLOG_FACILITY=3\nCODE_FILE=src/coredump/coredump.c\nCODE_LINE=789\nCODE_FUNCTION=process_socket\nSYSLOG_IDENTIFIER=systemd-coredump\n", 141}, {"MESSAGE=", 8}, {"Coredump file descriptor missing.", 33}, {"\n", 1}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 183
```

Note:

```
Receiver: 09:29:23.273637 ioctl(3, FIONREAD, [0]) = 0
Sender: 09:29:23.333734 sendto(3, "COREDUMP_UID=0", 14, MSG_NOSIGNAL, NULL, 0) = 14
```

@pmattern , thanks for the testing!
