### ISSUE TITLE
Kernel comand line - Failure parsing multiple addresses for the same interface

### ISSUE THREAD

**Issue by martafolf** [systemd/systemd#29855]
### systemd version the issue has been seen with

253

### Used distribution

Fedora CoreOS 38.20231014.3.0

### Linux kernel version used

6.5.6-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-network-generator

### Expected behaviour you didn't see

Setting multiple Kernel command line arguments to assign multiple IPv4 addresses to the same interface does not get handled correctly by network-generator, but works as expected from the Kernels perspective. 

Added cmdline arguments: `ip=:::::enp7s0f0:dhcp ip=192.0.2.10::192.0.2.1:255.255.255.0::enp7s0f1:none:1.1.1.1:9.9.9.9 ip=192.0.2.11:::255.255.255.0::enp7s0f1:none::`

Kernel behaviour works as expected, with the enp7s0f1 interface showing two IP's: 
```
6: enp7s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 9c:69:b4:64:f1:b7 brd ff:ff:ff:ff:ff:ff
    inet 192.0.2.10/24 brd 192.0.2.255 scope global noprefixroute enp7s0f1
       valid_lft forever preferred_lft forever
    inet 192.0.2.11/24 brd 192.0.2.255 scope global secondary noprefixroute enp7s0f1
       valid_lft forever preferred_lft forever
```

I would expect this to be parsed into NetworkManager files as it would when a single ip= entry for an interface is provided. 

### Unexpected behaviour you saw

systemd-network-generator fails to start: 
```
[root@hostname ~]# systemctl status systemd-network-generator
× systemd-network-generator.service - Generate network units from Kernel command line
     Loaded: loaded (/usr/lib/systemd/system/systemd-network-generator.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Fri 2023-11-03 17:38:00 UTC; 4min 15s ago
       Docs: man:systemd-network-generator.service(8)
    Process: 1705 ExecStart=/usr/lib/systemd/systemd-network-generator (code=exited, status=1/FAILURE)
   Main PID: 1705 (code=exited, status=1/FAILURE)
        CPU: 3ms

Nov 03 17:38:00 hostname systemd[1]: Starting systemd-network-generator.service - Generate network units from Kernel command line...
Nov 03 17:38:00 hostname systemd-network-generator[1705]: Failed to parse kernel command line: Invalid argument
Nov 03 17:38:00 hostname systemd[1]: systemd-network-generator.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 17:38:00 hostname systemd[1]: systemd-network-generator.service: Failed with result 'exit-code'.
Nov 03 17:38:00 hostname systemd[1]: Failed to start systemd-network-generator.service - Generate network units from Kernel command line.
```

Removing the second `ip=` statement for the same interface shows systemd-network-generator work as usual. 

### Steps to reproduce the problem

Specify more than one `ip=` Kernel command line argument for the same interface, for static IP configuration. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[root@localhost ~]# export SYSTEMD_LOG_LEVEL=debug && /usr/lib/systemd/systemd-network-generator
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Failed to parse kernel command line: Invalid argument
[root@localhost ~]# 
[root@localhost ~]# cat /proc/cmdline 
BOOT_IMAGE=http://10.5.1.1:8080/fedora-coreos-38.20231014.3.0-live-kernel-x86_64 initrd=http://10.5.1.1:8080/fedora-coreos-38.20231014.3.0-live-initramfs.x86_64.img,http://10.5.1.1:8080/fedora-coreos-38.20231014.3.0-live-rootfs.x86_64.img ip=:::::enp7s0f0:dhcp ip=192.0.2.10::192.0.2.1:255.255.255.0::enp7s0f1:none:1.1.1.1:9.9.9.9 ip=192.0.2.11:::255.255.255.0::enp7s0f1:none:: rd.bootif=0 ignition.firstboot ignition.platform.id=metal ignition.config.url=http://10.5.1.1:8080/install.ign BOOTIF=01-9c-69-b4-64-f1-b6
[root@localhost ~]#
```

**Comment by mrc0mmand** [comment]
The culprit here is the last assignment:

```
# SYSTEMD_LOG_LEVEL=debug SYSTEMD_PROC_CMDLINE="ip=192.0.2.11:::255.255.255.0::enp7s0f1:none::" /usr/lib/systemd/systemd-network-generator 
Failed to parse kernel command line: Invalid argument
```

And I assume the issue here is the ambiguity, since the last two fields can be either MTU and MAC address, or two DNS servers:

```
ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<mtu>][:<macaddr>]]
ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<dns1>][:<dns2>]]
```

But since the fields are empty, the parser can't determine which form to use. Omitting the last two empty fields completely should fix this.

I'm not completely sure if this is expected, but I'd assume that the fields should either be set to a non-empty value or omitted completely.

**Comment by martafolf** [comment]
Hey @mrc0mmand, interesting find! 

I ended up with that format by just removing the various options I didn't want to set again. Interesting that the kernel did not seem to have an issue applying the configuration, but I suspect it too would need to deal with the ambiguity. Perhaps it did print something and I missed it. 

Thanks for posting the debug command, I was iterating trough boots to test it, that looks a lot easier to run instead! 

I'm happy for this issue to close if it's not actually a bug with the parser, although if the fields are empty I suppose the parser could ignore them, which I'd imagine is what the kernel does too when given it, but it's definitely not as seriuous of an issue. 

Let me know what you think is best, in the interim, thank you for your help, that's clarified the issue I'm seeing. :)

**Comment by mrc0mmand** [comment]
> Hey @mrc0mmand, interesting find!
> 
> I ended up with that format by just removing the various options I didn't want to set again. Interesting that the kernel did not seem to have an issue applying the configuration, but I suspect it too would need to deal with the ambiguity. Perhaps it did print something and I missed it.

Kernel itself actually supports only [one format](https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/nfs/nfsroot.rst):
```
ip=<client-ip>:<server-ip>:<gw-ip>:<netmask>:<hostname>:<device>:<autoconf>:<dns0-ip>:<dns1-ip>:<ntp0-ip>
```

so there's no ambiguity here. However, looking at the dracut stuff[0][1] on which the sd-network-generator syntax is based on, it seems to be more lenient in such cases. Since the change should be pretty easy I'll try to prep something up.

[0] https://github.com/dracutdevs/dracut/blob/master/modules.d/40network/net-lib.sh
[1] https://github.com/dracutdevs/dracut/blob/4d594210d6ef4f04a9dbadacea73e9461ded352d/modules.d/35network-legacy/ifup.sh
