### ISSUE TITLE
Possible race condition(?) when calling `udevadm trigger --settle`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#29863]
Thanks to a regression introduced in https://github.com/systemd/systemd/pull/29847 CI started hitting a strange race condition where `udevadm trigger --settle` sometimes gets stuck indefinitely even when the uevent queue is empty.

One of the regressions from https://github.com/systemd/systemd/pull/29847 was that we always set the log level to 0, which makes the race condition more likely (for whatever reason):

```
# udevadm control -l 0; while SYSTEMD_LOG_LEVEL=debug timeout -v 10 udevadm trigger -w; do :; done
...
blkcg_punt_bio: Triggered device with action 'change'.
scsi_tmf_0: Triggered device with action 'change'.
scsi_tmf_1: Triggered device with action 'change'.
scsi_tmf_2: Triggered device with action 'change'.
scsi_tmf_3: Triggered device with action 'change'.
scsi_tmf_4: Triggered device with action 'change'.
scsi_tmf_5: Triggered device with action 'change'.
writeback: Triggered device with action 'change'.
sd-device-monitor(n/a): Failed to get the received message size: No buffer space available
timeout: sending signal TERM to command ‘udevadm’
```

I had little luck reproducing this locally, but a beefy CI machine (with 72 cores) can hit this on the first or second iteration.

/cc @yuwata

**Comment by yuwata** [comment]
> Thanks to a regression introduced in #29847 CI started hitting a strange race condition

Haha, we recently introduced nice regressions to reveal other issues 👍
I will take a look tomorrow or next week.
