### ISSUE TITLE
systemd-networkd: cannot manually remove managed interface from bridge

### ISSUE THREAD

**Issue by lukakudra** [systemd/systemd#29896]
### systemd version the issue has been seen with

systemd 254.5-1

### Used distribution

Arch Linux

### Linux kernel version used

6.1.60-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Interface `enp0s31f6` is removed from bridge `br0`.

### Unexpected behaviour you saw

Interface `enp0s31f6` is not removed from bridge `br0`.

### Steps to reproduce the problem

1. Create a bridge `br0`:

1-br0.netdev:
```
[NetDev]
Name=br0
Kind=bridge
```

3-br0.network:
```
[Match]
Name=br0

[Network]
ConfigureWithoutCarrier=yes
```

2. Add interface `enp0s31f6` to bridge `br0`

3-enp0s31f6.network:
```
[Match]
Name=enp0s31f6

[Network]
Bridge=br0
```

3. Verify that the interface `enp0s31f6` is in bridge `br0` with the command `brctl show`:

```
bridge name	bridge id		STP enabled	interfaces
br0		8000.e246f830d05f	no		enp0s31f6
```

4. Try to manually remove the interface `enp0s31f6` from bridge `br0` using the `ip` command:

```
sudo ip link set dev enp0s31f6 nomaster
```

5. Run the `brctl show` command to confirm that the interface `enp0s31f6` is still in the bridge `br0`:

```
bridge name	bridge id		STP enabled	interfaces
br0		8000.e246f830d05f	no		enp0s31f6
```

**Comment by yuwata** [comment]
That's expected, as you didn't edit the .network file, so networkd try to reconfigure the interface on such case.

**Comment by lukakudra** [comment]
> That's expected, as you didn't edit the .network file, so networkd try to reconfigure the interface on such case.

Ok, I understand that, but is there a way we can disable that behavior so that networkd doesn't try to reconfigure the interface?

Also, is it expected behavior that the network interface stays in a bridge when you delete it's network configuration file and restart systemd-networkd serivice?

Basically, I'm trying to remove an interface from a bridge by deleting it's network configuration file and restarting  systemd-networkd but since that did not work I tried to manually remove the interface using the netlink code equivalent to the command `ip link set dev enp0s31f6 nomaster` while the interface is still managed by systemd-networkd i.e. before the service restart.

If I remove the .network file, restart the service and then manually remove the interface from the bridge using netlink that works fine but I would like to be able to remove the interface manually before the networkd service is restarted.

**Comment by yuwata** [comment]
> > That's expected, as you didn't edit the .network file, so networkd try to reconfigure the interface on such case.
> 
> Ok, I understand that, but is there a way we can disable that behavior so that networkd doesn't try to reconfigure the interface?

1. Edit the .network file and comment out `Bridge=` setting,
2. call `networkctl reload`

Then, the interface should escape from the bridge interface.

> Also, is it expected behavior that the network interface stays in a bridge when you delete it's network configuration file and restart systemd-networkd serivice?

If the .network file is removed (and `networkctl reload` is called), then the interface goes to `unmanaged` state and any configuration for the interface is kept, at least not touched by networkd. So, if you remove the .network file, then you need to call `ip` command manually.

> Basically, I'm trying to remove an interface from a bridge by deleting it's network configuration file and restarting systemd-networkd but since that did not work I tried to manually remove the interface using the netlink code equivalent to the command `ip link set dev enp0s31f6 nomaster` while the interface is still managed by systemd-networkd i.e. before the service restart.
> 
> If I remove the .network file, restart the service and then manually remove the interface from the bridge using netlink that works fine but I would like to be able to remove the interface manually before the networkd service is restarted.

As I said in the above, restarting networkd is not necessary. Try to call `networkctl reload`.
