### ISSUE TITLE
Preserve order of search domains within an interface

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#29898]
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

I have multiple 'search domains' (one for internal-only hosts, another for general use... and a third for work, perhaps), where some hosts are duplicated across both domains but with different addresses – e.g. `NAS.lan` would have a VPN address while `NAS.example.com` would have a public address, and some services are only accessible via VPN, etc.

But if I configure both domains as `Domains=` in a .network file, it seems that systemd-resolved ignores the order in which they were specified and instead uses alphabetical order. This means that even though I listed the "internal" domain first, it ends up being checked last because alphabetically it sorts last, so DNS lookup results end up giving a different result.

### Describe the solution you'd like

I would like systemd-resolved to preserve the order of search domains I specify in a .network file's `Domains=`, e.g. if I use:

```
[Network]
Domains=foo
Domains=example.net
```

the domain `foo` should remain first.

### Describe alternatives you've considered

I could disable the nss-resolve module and directly edit `/etc/resolv.conf` (relying on the stub resolver) – in fact, it seems /etc/resolv.conf already preserves the order – but that doesn't seem like it's a good approach.

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by rpigott** [comment]
I'm pretty sure this is already the intended behavior for some time (0061695507e88). Maybe there is a bug?

Strangely, I notice that `resolvectl status 2` prints domains in alphabetical order, but

```
$ busctl get-property org.freedesktop.resolve1 /org/freedesktop/resolve1/link/_32 org.freedesktop.resolve1.Link Domains
```

Correctly shows the domains in insertion order. I didn't try to verify the search order.

**Comment by rpigott** [comment]
This feature works as expected for me. Can you share a debug log from sd-resolved that demonstrates the unintended search order? Can you also include the busctl output to verify the intended search order?

**Comment by rpigott** [comment]
Please reopen if you can still reproduce.
