### ISSUE TITLE
Make loginctl optionally show all master devices attached to a given seat

### ISSUE THREAD

**Issue by lbssousa** [systemd/systemd#2989]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> any

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> any

I'm planning to write a simple assistant to handle device attachments among systemd-logind seats, maybe even forking [multiseat-wizard-bicefalo](https://code.google.com/archive/p/multiseat-wizard-bicefalo/). However, the only easy way to query systemd-logind for available master devices is the command `loginctl seat-status [seat name]`, which doesn't generate a well machine-parseable output.

I wonder if `loginctl` could gain an optional feature to list all master devices  attached to a given seat (e.g. `loginctl list-master-devices [seat name]`).

**Comment by poettering** [comment]
query the udev DB instead via libudev (or with udevadm from the shell if you must), and look for all devices that have MASTER_OF_SEAT=1 and ID_SEAT= set to the seat of your choice. This hasn't really place in loginctl. Sorry.
