### ISSUE TITLE
systemd-networkd segfault with missing bridge module (220-r5)

### ISSUE THREAD

**Issue by qantourisc** [systemd/systemd#299]
If the kernel module bridge is not available and the bridge option is compiled into the kernel (BRIDGE=n)

kernel: systemd-network[11425]: segfault at 7f00eab21c54 ip 00007f00eb66014b sp 00007fff43b4a590 error 7 in systemd-networkd[7f00eb637000+a5000]

lan_bridge.netdev:

```
[NetDev]
Kind=bridge
Name=lan
```

lan_slave_eno1.network:

```
[Match]
Name=eno1

[Network]
Bridge=lanwork
```

**Comment by poettering** [comment]
Any chance you can get us a backtrace for this? For example like the ones systemd-coredump generates and writes to the journal?

**Comment by qantourisc** [comment]
Sure should be possible, don't dig in yet then, will need to get to the machine and do it locally :)

**Comment by qantourisc** [comment]
```
            #0  0x00007f69294cb14b netdev_join_handler.lto_priv.235 (systemd-networkd)
            #1  0x00007f69294cefe4 netdev_cancel_callbacks (systemd-networkd)
            #2  0x00007f69294cfdb1 netdev_unref (systemd-networkd)
            #3  0x00007f69294dc2be network_free.part.2.lto_priv.423 (systemd-networkd)
            #4  0x00007f69294c2025 manager_free (systemd-networkd)
            #5  0x00007f69294b460b main (systemd-networkd)
            #6  0x00007f69288d0800 __libc_start_main (libc.so.6)
            #7  0x00007f69294b59b9 _start (systemd-networkd)
```

Sorry for the late reply, life + fs.suid_dumpable got in the way.

**Comment by poettering** [comment]
@teg any idea about this?

**Comment by teg** [comment]
@qantourisc could you verify that the fix in PR #409 fixes this for you?

**Comment by qantourisc** [comment]
Is it possible it doesn't compile ? Or do I have to update binutils to some version for this branch to work ?

```
Makefile:12013: recipe for target 'test-bus-marshal' failed
Makefile:18150: recipe for target 'all-recursive' failed
Makefile:9010: recipe for target 'all' failed
In function '__ppoll_alias',
    inlined from 'bus_poll' at src/libsystemd/sd-bus/sd-bus.c:2822:11:
/usr/x86_64-pc-linux-gnu/include/bits/poll2.h:71:2: warning: call to '__ppoll_chk_warn' declared with attribute warning: ppoll called with fds buffer too small file nfds entries
  return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));
  ^
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld.gold: error: hidden symbol '__stop_BUS_ERROR_MAP' is not defined locally
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld.gold: error: hidden symbol '__start_BUS_ERROR_MAP' is not defined locally
collect2: error: ld returned 1 exit status
make[2]: *** [test-bus-marshal] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by teg** [comment]
Hm, I haven't seen that. Very strange. You should be able to just cherry pick the one commit onto whatever compiles for you.

**Comment by qantourisc** [comment]
Seems to be related to my build environment, not the specific branch. Not sure what caused it, the only updates/changes I recall are systemd.

**Comment by teg** [comment]
This branch was just merged, so hopefully this is fixed for you with the next release. Thanks for the report!

**Comment by teg** [comment]
This branch was just merged, so hopefully this is fixed for you with the next release. If not, please reopen. Thanks for the report!
