### ISSUE TITLE
systemd-run does not make the new scope unit part of the slice specified via the --slice arg

### ISSUE THREAD

**Issue by alexbrand** [systemd/systemd#2991]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 219, but also in master
### Used distribution

> CentOS Linux release 7.2.1511 (Core)
### Expected behaviour you didn't see

> Scope unit started with `systemd-run --scope --slice=$someSlice` is not part of the specified slice
### In case of bug report: Unexpected behaviour you saw

> Scope unit started with `systemd-run --scope --slice=$someSlice` is part of the `system.slice` instead of the slice specified via the `--slice` flag.
### In case of bug report: Steps to reproduce the problem

> Use `systemd-run` to start a transient scope using the `--scope` flag. Also set the `--slice` flag to make the new scope unit part of a given slice. Observe that the transient scope is started in the system slice, instead of the slice specified via the `--slice` flag.
> e.g. `systemd-run --scope --slice=test sleep 5`
### Further investigation

Inspecting the `run.c` source, I noticed that the `transient_cgroup_set_properties` function (which seems to be the place where the `--slice` arg is used) is not in the call hierarchy of `start_transient_scope`. In other words, the `transient_cgroup_set_properties` function is only called when starting a service or a timer.

**Comment by poettering** [comment]
Looks like a bug.

**Comment by poettering** [comment]
Fix is waiting in #3094.
