### ISSUE TITLE
Support schedutil's utilization hints (utilization clamping / uclamp)

### ISSUE THREAD

**Issue by Flowdalic** [systemd/systemd#29934]
### Is your feature request related to a problem? Please describe

Linux's schedutil allows to clamp the utilization of units (see https://docs.kernel.org/scheduler/sched-util-clamp.html). Unlike other scheduling options currently exposed by systemd, those scheduling attributes affect Linux's  Energy Aware and Capacity Aware Scheduling (EAS/CAS) and processor frequency selection.

Setting those values is only available via `SYS_sched_setattr` and, unfortunately, not via `sched_setscheduler(2)` which is currently used by systemd.

### Describe the solution you'd like

New options `UtilizationClampMin` and `UtilizationClampMax` for suitable unit kinds.

**Comment by poettering** [comment]
how does this relate to #26705?

**Comment by Flowdalic** [comment]
Mine is a dupe of this. Sorry for the noise.
