### ISSUE TITLE
LogExtraFields= fields are not attached to user services

### ISSUE THREAD

**Issue by abeluck** [systemd/systemd#29956]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-13-cloud-amd64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

When I attach LogExtraFields=FOO=BAR inside a `[Service]` section of a user service, I expect to be able to see the FOO=BAR field when querying journald.

### Unexpected behaviour you saw

When I attach LogExtraFields=FOO=BAR inside a `[Service]` section of a user service, and query journald with `journalctl --user FOO=BAR` I get `-- No entries --`

### Steps to reproduce the problem

1. Create a simple user service with `LogExtraFields=FOO=BAR` in the `[Service]` section
2. Reload and start the service
3. `journalctl --user FOO=BAR`

**Comment by mrc0mmand** [comment]
Yeah, the extra fields are exported only in the system manager:

https://github.com/systemd/systemd/blob/f3066d635ab97b414ee5c0cf6753406dc457e889/src/core/unit.c#L5791-L5800

Not sure if this intentional or just nobody needed it until now, so it's not implemented for the user manager.

**Comment by abeluck** [comment]
FWIW: Our use case for this is running podman rootless containers as systemd services (using podman's quadlet feature) and tagging the services with multiple fields for log analysis.
