### ISSUE TITLE
libudev: documentation should clarify when multiple matches are combined via OR and when via AND

### ISSUE THREAD

**Issue by Julio-Guerra** [systemd/systemd#2995]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229-3
### Used distribution

> archlinux with linux kernel 4.4.1-2
### Expected behaviour you didn't see

I am using `udevadm trigger --dry-run --verbose` to enumerate devices from the shell exactly as I would with corresponding `udev_enumerate_*()` libudev functions. 

The returned list is wrong (or maybe the documentation is?) when several matchers are combined (libudev: `udev_enumerate_add_match_*()`): I am expecting that every "matchers" are combined, so that the list of devices matching **every** criteria should be returned. But it does not in the following example.

Given a usb-serial device, I want to get its node (/sys/.../ttyUSB0) by enumerating the list of devices uniquely matching it (subsystem usb AND vendor/product ids AND subsystem tty):

```
$ udevadm trigger --dry-run --verbose --subsystem-match=usb --attr-match=idVendor=0e0f --attr-match=idProduct=0002 -subsystem-match=tty
```

Resulting in `/sys/.../ttyUSB0` in my case:

```
/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1/2-2.1:1.0/ttyUSB0/tty/ttyUSB0
```
### Unexpected behaviour you saw

But only the usb node is returned:

```
/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2
```

Either the documentation about how matchers are added is wrong/incomplete (but in my opinion, the "add" suggests the union), or there is a problem in the combination of matchers.

My workaround for now is to rerun it with the `--parent-match` option:

```
$ udevadm trigger --dry-run --verbose --parent-match=$(udevadm trigger --dry-run --verbose --subsystem-match=usb --attr-match=idVendor=0e0f --attr-match=idProduct=0002 --subsystem-match=tty) --subsystem-match=tty
/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1/2-2.1:1.0/ttyUSB0/tty/ttyUSB0
```

**Comment by arvidjaar** [comment]
subsystem match is cumulative - `--subsystem-match=usb --subsystem-match=tty` will match for devices with either `usb` or `tty` subsystems. Attribute match is mandatory - if `--attr-match=idVendor=0e0f` is given, device must have this attribute with given value. If multiple attributes are given, all attributes must be present and have given values. Does `/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1/2-2.1:1.0/ttyUSB0/tty/ttyUSB0` have this attribute? I suspect no, which explains why only USB device matches.

Documentation probably could be improved by explaining how various matchers are combined.

**Comment by poettering** [comment]
Yeah, this is expected behaviour really. But should be documented better.
