### ISSUE TITLE
StopIdleSessionSec ignored for Controlmaster ssh sessions 

### ISSUE THREAD

**Issue by jsahpc** [systemd/systemd#29967]
### systemd version the issue has been seen with

239-68

### Used distribution

Rocky Linux 8.7

### Linux kernel version used

4.18.0-425.13.1.el8_7.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

Terminate multiplexed control master ssh sessions that are idle for longer than StopIdleSessionSec timeout.

### Unexpected behaviour you saw

Multiplexed control master sessions that are idle for longer than StopIdleSessionSec timeout are *not* terminated.  

### Steps to reproduce the problem

On remote system:
* Configure StopIdleSessionSec=300 in /etc/systemd/logind.conf
* Run systemctl restart systemd-logind.service

On local system: Open control master ssh session to remote system (initial master connection)
* ssh -M -S ~/.ssh/controlmasters/%r@%h:%p user@remote

On local system: Open subsequent slave ssh connection to remote system via control socket of master connection
* ssh -S ~/.ssh/controlmasters/%r@%h:%p user@remote

On remote system: Observe IDLE time of both sessions increasing beyond configured StopIdleSessionSec of 300 seconds.
* watch w

Both ssh sessions remain alive when their IDLE time exceeds timeout of 300 seconds. 

Is that expected behaviour? 

Regular (non multiplexed) ssh sessions are being stopped when their idle time exceeds 300 seconds.

**Comment by dtardon** [comment]
Sorry, but 239 is too old. The submission form should be pretty clear about this. Please contact your distro for help.
