### ISSUE TITLE
HP ProBook 640 G2

### ISSUE THREAD

**Issue by joakim-tjernlund** [systemd/systemd#2997]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> current git 
### Used distribution

> Gentoo

HP ProBook 640 G2 has the same keys HP Probook 440 G3 and needs to be added to
440 pattern. See https://github.com/systemd/systemd/pull/2679 for details.
One note though, I don't think the rfkill button should be mapped to unknown, wlan/rfkill would be better
in case someone wants to do any extra processing, especially as rfkill on my 640 G2 do do anything.

Anyone have scripts ready for rfkill ? How do one control the LED on the rfkill button?

**Comment by martinpitt** [comment]
We actually have two different patterns for these HP notebooks:

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnHP440G2:pvr*

evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pnHP*ProBook*440*G3*
```

... where the former adds the micmute key, while the latter disables events for "lid close" and "rfkill" as these are being handled in hardware.

Please tell me the output of `cat /sys/class/dmi/id/modalias` and which keys are actually misbehaving on this model. Thanks!

**Comment by joakim-tjernlund** [comment]
cat /sys/class/dmi/id/modalias
dmi:bvnHP:bvrN76Ver.01.00:bd12/07/2015:svnHP:pnHPProBook640G2:pvr:rvnHP:rn80FD:rvrKBCVersion22.36:cvnHP:ct10:cvr:

The key that are unmapped are the same as for 440
KEYBOARD_KEY_85=unknown                                # lid close; also reported via special evdev
KEYBOARD_KEY_f8=unknown                                # rf kill; also reported via special evdev

Key_85 seems surplus as there is a "ACPI event unhandled: button/lid LID close" event
already.

Key_f8 is rfkill and nothing happens when I press it, other that getting a keykode report.

**Comment by martinpitt** [comment]
> Key_85 seems surplus as there is a "ACPI event unhandled: button/lid LID close" event already.

Then this means that there's no point setting it to "unknown" indeed.

> Key_f8 is rfkill and nothing happens when I press it, other that getting a keykode report.

Ah, then on this model we need to _set_ it to rfkill instead of unsetting it.

So it turns out this is not the same keymap as on the 440 G3 at all, but we need a new one. PR coming.

**Comment by joakim-tjernlund** [comment]
I decided to retest as I was messing around quite a bit last Friday.
It turns out that rfkill works using Soft blocking:
rfkill list
0: phy0: Wireless LAN
    Soft blocked: yes
    Hard blocked: no
1: hci0: Bluetooth
    Soft blocked: yes
    Hard blocked: no

I can see stuff like this in my logs:
Apr 11 10:28:15 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: L1 Enabled - LTR Enabled
Apr 11 10:28:15 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: L1 Enabled - LTR Enabled
Apr 11 10:28:15 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: can't access the RSA semaphore it is write protected
Apr 11 10:28:16 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: L1 Enabled - LTR Enabled
Apr 11 10:28:16 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: L1 Enabled - LTR Enabled
Apr 11 10:28:16 gentoo-LABBBB kernel: iwlwifi 0000:02:00.0: can't access the RSA semaphore it is write protected
wlan0: deauthenticating from 84:b2:61:2c:e4:df by local choice (Reason: 3=DEAUTH_LEAVING)

The rfkill LED is NOT working though.

**Comment by martinpitt** [comment]
Oh, so you are saying that pressing the  rfkill button actually _does_ work (yes, it uses soft blocking), it's just the LED that doesn't work? That part is not a keymap problem, that needs to be done in hardware or the kernel driver.

**Comment by joakim-tjernlund** [comment]
KEY 85 should be set to unknown or it will log 
Apr 11 10:32:09 gentoo-LABBBB kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xf8 on isa0060/serio0).
Apr 11 10:32:09 gentoo-LABBBB kernel: atkbd serio0: Use 'setkeycodes e078 <keycode>' to make it known.
Apr 11 10:32:09 gentoo-LABBBB kernel: atkbd serio0: Unknown key released (translated set 2, code 0xf8 on isa0060/serio0).
Apr 11 10:32:09 gentoo-LABBBB kernel: atkbd serio0: Use 'setkeycodes e078 <keycode>' to make it known.
Apr 11 10:46:05 gentoo-LABBBB kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0x85 on isa0060/serio0).
Apr 11 10:46:05 gentoo-LABBBB kernel: atkbd serio0: Use 'setkeycodes e005 <keycode>' to make it known.

**Comment by joakim-tjernlund** [comment]
yes, rfkill works. Only LED does not.

**Comment by martinpitt** [comment]
> KEY 85 should be set to unknown or it will log 

That doesn't work -- setting it to "unknown" explicitly will still make the kernel log about this. There is currently no way to quiesce that log message.

OK, thanks -- so it turns out that there's nothing left to do here for this model, thus closing. I'll revert the keymap patch in my branch.

**Comment by joakim-tjernlund** [comment]
hmm, if I set these 2 keys to unknown(like 440 does) the logging stops.
Why have 440 set them to unknown if there is no change?

**Comment by martinpitt** [comment]
> Why have 440 set them to unknown if there is no change?

The idea of that is normally that the key is set to something by default, but we want to suppress it.

> hmm, if I set these 2 keys to unknown(like 440 does) the logging stops.

That's a bit of a surprise as this did not work on other laptops in similar scenarios. But _shrug_, if it helps, I'll add it.
