### ISSUE TITLE
systemd-networkd: changing the vlan in configuration file does not remove the vlan from the old configuration

### ISSUE THREAD

**Issue by lukakudra** [systemd/systemd#29975]
### systemd version the issue has been seen with

254.5-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.1.60-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The interface enp0s31f6 should have changed vlan from VLAN 10 to VLAN 20.

### Unexpected behaviour you saw

The interface enp0s31f6 remained in the VLAN 10 and also got added to VLAN 20.

### Steps to reproduce the problem

1. create a bridge interface with VLANFiltering enabled
    1-brvlan.netdev:
    ```
    [NetDev]
    Name=brvlan
    Kind=bridge

    [Bridge]
    VLANFiltering=1
    DefaultPVID=none
    ```
    3-brvlan.network:
    ```
    [Match]
    Name=brvlan

    [Network]
    ConfigureWithoutCarrier=yes
    ```
2. Add interface enp0s31f6 to bridge brvlan and assign it to VLAN 10
    3-enp0s31f6.network
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    VLAN=10
    ```
3. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
4. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10
    ```
5. Modify the file `3-enp0s31f6.network` to the following configuration:
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    VLAN=20
    ```
6. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
7. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10
                      20
    ```

The same issue happens if I use the untagged VLAN configuration, for example (starting from step 2.):

2. Add interface enp0s31f6 to bridge brvlan and assign it to VLAN 10
    3-enp0s31f6.network
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    PVID=10
    EgressUntagged=10
    ```
3. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
4. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10 PVID Egress Untagged
    ```
5. Modify the file `3-enp0s31f6.network` to the following configuration:
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    PVID=20
    EgressUntagged=20
    ```
6. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
7. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10 Egress Untagged
                      20 PVID Egress Untagged
    ```

In both of these described examples I'm expecting to see that the interface enp0s31f6 has changed the VLAN from VLAN 10 to VLAN 20, instead of being assigned to both VLAN 10 and VLAN 20. It seems to me that the new configuration is applied, but the old one isn't cleared. Since the configuration file is not deleted (i.e. the interface is still being managed by systemd-networkd) I would expect the new configuration to be applied and the old one to be cleared.

**Comment by yuwata** [comment]
Fix is waiting in #29987.
