### ISSUE TITLE
Can sd_notify in hostnamectl be replaced with sd_notify_barrier?

### ISSUE THREAD

**Issue by willwu1217** [systemd/systemd#29983]
### Component

hostnamectl

### Is your feature request related to a problem? Please describe

Hi,
I have a service that frequently creates and deletes processes. There is a very low probability that my service enters stop-sigterm state after executing hostnamectl. I think the problem is that hostnamectl exits too early after sending sd_notify. 

### Describe the solution you'd like

I notice that sd_notify_barrier was introduced in version 246. So is it possible to replace sd_notify called in hostnamectl with sd_notify_barrier.  Other xxxctl process may have the same problem which use sd_notify in it's exit.

**Comment by yuwata** [comment]
Maybe. But could you elaborate more? What your service expects?

**Comment by willwu1217** [comment]
Thanks for your reply.
My service set NotifyAccess=all，and I want my service not to be accidentally set to stop-sigterm state by systemd, after executing hostnamectl.
I can also set my service to NotifyAccess=main to avoid setting it by mistake， but I think hostnamectl itself should ensure that stopping messages have been consumed by the manager before it exits.

**Comment by poettering** [comment]
i am not sure i get this? hostnamectl is a client tool, why would NotifyAccess= even make sense in context with that?

**Comment by willwu1217** [comment]
hostnamectl exit from bus_event_loop_with_idle, and send STOPPING=1 to systemd.
![image](https://github.com/systemd/systemd/assets/148855842/2a49c727-0861-492e-8514-e73292df329d)

I think when systemd receive this notify, hostnamectl  has released the pid, and my service "A"'s subprocess occupy the same pid. Systemd set my service A to stop-sigterm status by mistake.

**Comment by Geass-LL** [comment]
> i am not sure i get this? hostnamectl is a client tool, why would NotifyAccess= even make sense in context with that?

systemd-hostnamed, not hostnamectl. I guess he doesn't care the difference of these two components.

From this commit <https://github.com/systemd/systemd/commit/430e21c2f7e77d600257ead56419f511e48e854a> systemd-hostnamed starts to notify systemd before it exits. If the SIGCHLD of systemd-hostnamed is dispatched before `STOPPING=1` message, and the PID of systemd-hostnamed is reused by other unit (foo.service), systemd will mistakely kill foo.service.

So we need to use sd_notify_barrier in `bus_event_loop_with_idle` to make sure the notify message has been dispatched before systemd-hostnamed exits.

**Comment by poettering** [comment]
Let's close this given that we kill by pidfd these days.
