### ISSUE TITLE
systemd-networkd: Option to persist DHCP leases

### ISSUE THREAD

**Issue by jpds** [systemd/systemd#29991]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

There does not appear to be an option available to have `networkd` persist its DHCP server leases to a file, so that these can be restored on restart/reload.

### The systemd version you checked that didn't have the feature you are asking for

254.3

**Comment by bluca** [comment]
This is already possible, see the KeepConfiguration option https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#KeepConfiguration=

**Comment by yuwata** [comment]
> This is already possible, see the KeepConfiguration option https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#KeepConfiguration=

No no, this request is about DHCP server, instead of DHCP client.
