### ISSUE TITLE
localectl removes LC_* if set to the same value as LANG

### ISSUE THREAD

**Issue by devurandom** [systemd/systemd#30001]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39

### Linux kernel version used

6.5.11-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

I expected
```
❯ sudo localectl set-locale LANG=en_US.UTF-8 LC_NUMERIC=de_DE.UTF-8 LC_TIME=de_DE.UTF-8  LC_MONETARY=de_DE.UTF-8 LC_PAPER=de_DE.UTF-8 LC_NAME=de_DE.UTF-8 LC_ADDRESS=de_DE.UTF-8 LC_TELEPHONE=de_DE.UTF-8 LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
```
to honor `LC_CTYPE` even if `LANG` is set to the same value. It should save and set all env vars passed.

### Unexpected behaviour you saw

It only sets those env vars that are different from `LANG`:
```
❯ sudo localectl
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=de_DE.UTF-8
               LC_TIME=de_DE.UTF-8
               LC_MONETARY=de_DE.UTF-8
               LC_PAPER=de_DE.UTF-8
               LC_NAME=de_DE.UTF-8
               LC_ADDRESS=de_DE.UTF-8
               LC_TELEPHONE=de_DE.UTF-8
               LC_MEASUREMENT=de_DE.UTF-8
    VC Keymap: us
   X11 Layout: us
❯ cat /etc/locale.conf
LANG=en_US.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
 ```
The others do not appear in the output of `localectl`, they are not added to `/etc/locale.conf`, and shell and desktop environments do not have these variables set.

**Comment by devurandom** [comment]
P.S. This is a problem with JetBrains IntelliJ 2023.2.4 (installed via JetBrains Toolbox) which it detects the "system default" for "file encoding" as `US-ASCII` unless I set `LC_CTYPE=en_US.UTF-8`. This seems to be result of how [Java specifically reads `LC_CTYPE`](https://github.com/openjdk/jdk/blob/03db82818b905f21cb5ad1d56a687e238b4a6e33/src/java.base/unix/native/libjava/java_props_md.c#L437-L456) go get the [`defaultCharset`](https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html#defaultCharset--).

**Comment by devurandom** [comment]
> we suppress redundant settings, because LC_xyz default to $LANG anyway.
> 
> Seems to a bug in java?

Might be, but it works this way since at least JDK 11, cf. https://github.com/openjdk/jdk/blob/03db82818b905f21cb5ad1d56a687e238b4a6e33/src/java.base/unix/native/libjava/java_props_md.c#L437-L456 where the JDK uses `setlocale(LC_CTYPE, NULL)` since a long time. I can report a bug there, too, but there will still be JDKs out there for years that expect `LC_CTYPE` to be set. So from a pragmatic point of view it would be nice if systemd would have a way to not do more than what I tell it to.

**Comment by yuwata** [comment]
> > we suppress redundant settings, because LC_xyz default to $LANG anyway.
> > Seems to a bug in java?
> 
> Might be, but it works this way since at least JDK 11, cf. https://github.com/openjdk/jdk/blob/03db82818b905f21cb5ad1d56a687e238b4a6e33/src/java.base/unix/native/libjava/java_props_md.c#L437-L456 where the JDK uses `setlocale(LC_CTYPE, NULL)` since a long time. I can report a bug there, too, but there will still be JDKs out there for years that expect `LC_CTYPE` to be set. So from a pragmatic point of view it would be nice if systemd would have a way to not do more than what I tell it to.

Why not `setlocale(LC_CTYPE, "")`, instead of `NULL`?

**Comment by devurandom** [comment]
> Why not `setlocale(LC_CTYPE, "")`, instead of `NULL`?

I do not know. I can just point you to the source, where it is done with `NULL` and not `""`: https://github.com/openjdk/jdk/blob/03db82818b905f21cb5ad1d56a687e238b4a6e33/src/java.base/unix/native/libjava/java_props_md.c#L106

**Comment by devurandom** [comment]
I solved my problem. The desktop environment, KDE Plasma, hangs in between `systemd-localed` and the Java application and sets a user-defined locale. `rm .config/plasma-localerc` made the Java application use the correct encoding.
