### ISSUE TITLE
Every single reboot hangs for at least 3-10 minutes due to sd-sync.

### ISSUE THREAD

**Issue by sweetbbak** [systemd/systemd#30025]
### systemd version the issue has been seen with

254.6-2

### Used distribution

Arch Linux

### Linux kernel version used

6.6.1.arch1-1 (and linux-zen 6.6.1.zen1-1)

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I expect the machine to reboot in a reasonable time frame. However, every reboot takes nearly 10 minutes. Every single time I reboot this happens.

![PXL_20231105_192428790](https://github.com/systemd/systemd/assets/75046310/5e1a70d2-636d-4d4d-9a1d-806dc666dd47)
![PXL_20231105_192256783](https://github.com/systemd/systemd/assets/75046310/a9b6dda8-699b-4e40-a240-a361e09e878f)

### Unexpected behaviour you saw

systemd remounts a file system and then spends a ton of time sending a kill signal to sd-sync which never completes and maxes out the time limit until it is eventually killed and a reboot takes place.

### Steps to reproduce the problem

I have absolutely no idea what is causing this issue. I have tried reinstalling the OS, formatting the disks, removing all non-essential disks from my Fstab, and moving my root partition to another nvme. None of them worked.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
![PXL_20231105_192428790](https://github.com/systemd/systemd/assets/75046310/5e1a70d2-636d-4d4d-9a1d-806dc666dd47)
![PXL_20231105_192256783](https://github.com/systemd/systemd/assets/75046310/a9b6dda8-699b-4e40-a240-a361e09e878f)

Journalctl:

Nov 14 09:53:19 sweetd systemd[1]: Unmounting /efi...
Nov 14 09:53:19 sweetd systemd[1]: Unmounting /tmp...
Nov 14 09:53:19 sweetd systemd[1]: efi.mount: Deactivated successfully.
Nov 14 09:53:19 sweetd systemd[1]: Unmounted /efi.
Nov 14 09:53:19 sweetd systemd[1]: tmp.mount: Deactivated successfully.
Nov 14 09:53:19 sweetd systemd[1]: Unmounted /tmp.
Nov 14 09:53:19 sweetd systemd[1]: Stopped target Swaps.
Nov 14 09:53:19 sweetd systemd[1]: Deactivating swap /swapfile...
Nov 14 09:53:19 sweetd systemd[1]: systemd-fsck@dev-disk-by\x2duuid-44A4\x2dF78F.service: Deactivated s>
Nov 14 09:53:19 sweetd systemd[1]: Stopped File System Check on /dev/disk/by-uuid/44A4-F78F.
Nov 14 09:53:19 sweetd systemd[1]: Removed slice Slice /system/systemd-fsck.
Nov 14 09:53:19 sweetd systemd[1]: Stopped target Preparation for Local File Systems.
Nov 14 09:53:19 sweetd systemd[1]: Stopping Monitoring of LVM2 mirrors, snapshots etc. using dmeventd o>
Nov 14 09:53:19 sweetd systemd[1]: systemd-tmpfiles-setup-dev.service: Deactivated successfully.
Nov 14 09:53:19 sweetd systemd[1]: Stopped Create Static Device Nodes in /dev.
Nov 14 09:53:19 sweetd systemd[1]: systemd-sysusers.service: Deactivated successfully.
Nov 14 09:53:19 sweetd systemd[1]: Stopped Create System Users.
Nov 14 09:53:19 sweetd systemd[1]: systemd-tmpfiles-setup-dev-early.service: Deactivated successfully.
Nov 14 09:53:19 sweetd systemd[1]: Stopped Create Static Device Nodes in /dev gracefully.
Nov 14 09:53:19 sweetd systemd[1]: swapfile.swap: Deactivated successfully.
Nov 14 09:53:20 sweetd systemd[1]: Deactivated swap /swapfile.
Nov 14 09:53:20 sweetd systemd[1]: Reached target Unmount All Filesystems.
Nov 14 09:53:20 sweetd systemd[1]: systemd-remount-fs.service: Deactivated successfully.
Nov 14 09:53:20 sweetd systemd[1]: Stopped Remount Root and Kernel File Systems.
Nov 14 09:53:20 sweetd systemd[1]: systemd-fsck-root.service: Deactivated successfully.
Nov 14 09:53:20 sweetd systemd[1]: Stopped File System Check on Root Device.
Nov 14 09:53:20 sweetd systemd[1]: systemd-fsck-root.service: Consumed 2.558s CPU time.
Nov 14 09:53:20 sweetd systemd[1]: lvm2-monitor.service: Deactivated successfully.
Nov 14 09:53:20 sweetd systemd[1]: Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or>
Nov 14 09:53:20 sweetd systemd[1]: Reached target System Shutdown.
Nov 14 09:53:20 sweetd systemd[1]: Reached target Late Shutdown Services.
Nov 14 09:53:20 sweetd systemd[1]: systemd-reboot.service: Deactivated successfully.
Nov 14 09:53:20 sweetd systemd[1]: Finished System Reboot.
Nov 14 09:53:20 sweetd systemd[1]: Reached target System Reboot.
Nov 14 09:53:20 sweetd systemd[1]: Shutting down.
Nov 14 09:53:20 sweetd systemd[1]: Using hardware watchdog 'iTCO_wdt', version 6, device /dev/watchdog0
Nov 14 09:53:20 sweetd systemd[1]: Watchdog running with a timeout of 10min.
Nov 14 09:53:20 sweetd kernel: watchdog: watchdog0: watchdog did not stop!
Nov 14 09:53:20 sweetd systemd-shutdown[1]: Using hardware watchdog 'iTCO_wdt', version 6, device /dev/>
Nov 14 09:53:20 sweetd systemd-shutdown[1]: Watchdog running with a timeout of 10min.
Nov 14 09:53:20 sweetd systemd-shutdown[1]: Syncing filesystems and block devices.
Nov 14 09:54:17 sweetd systemd-journald[500]: Failed to send WATCHDOG=1 notification message: Connectio>
Nov 14 09:54:20 sweetd systemd-shutdown[1]: Syncing filesystems and block devices - timed out, issuing >
Nov 14 09:54:20 sweetd systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Nov 14 09:54:20 sweetd systemd-journald[500]: Received SIGTERM from PID 1 (systemd-shutdow).
Nov 14 09:54:20 sweetd systemd-journald[500]: Journal stopped
```

**Comment by sweetbbak** [comment]
The attached images and journal are fairly early in the process, it ends up just hanging there for 5 minutes at least and then eventually rebooting or sometimes just hanging. It's quite disruptive.

**Comment by sweetbbak** [comment]
![PXL_20231114_200822618](https://github.com/systemd/systemd/assets/75046310/a78a64bf-d005-45c4-9ef1-71e9c26f7aa4)
Heres a picture of this last reboot I did that gives a more comprehensive scope of the issue.

**Comment by poettering** [comment]
sd-sync just calls the good old venerable sync() syscall. 

If that hangs, you have some driver or other storage problem or so. i.e. there are some unwritten changes in memory, and we try hard to sync it to disk, but this apparently doesn't work. So we time-out eventually. 

systemd is just the messenger here really. it's safety net did work though, as we don#t let the kernel sync forever...

do you have any kind of weird storage? i see lvm in the mix?

**Comment by sweetbbak** [comment]
My configuration is pretty simple and straightforward. Just my root partition and 3 ssd's and a hdd mounted on home. Maybe that is enough to cause an issue with sync though. I just noticed that if I run the "sync" command, it just never finishes and goes on indefinitely in the background so it probably isn't systemds fault. 

Heres the output of lsblk just in case:
```sh
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0   3.6T  0 disk 
└─sda1        8:1    0   3.6T  0 part /home/sweet/hdd
nvme1n1     259:0    0 931.5G  0 disk 
└─nvme1n1p1 259:1    0 931.5G  0 part /home/sweet/ssd
nvme0n1     259:2    0   1.8T  0 disk 
└─nvme0n1p1 259:3    0   1.8T  0 part /home/sweet/sdx
nvme3n1     259:4    0 931.5G  0 disk 
├─nvme3n1p1 259:5    0  1000M  0 part /efi
└─nvme3n1p2 259:6    0 930.5G  0 part /
nvme2n1     259:7    0 931.5G  0 disk 
└─nvme2n1p1 259:8    0 931.5G  0 part /home/sweet/sda
```
Thank you for your time.

**Comment by keszybz** [comment]
What are the file system types?

**Comment by sweetbbak** [comment]
@keszybz they are now all Ext4. I had a btrfs volume and an XFS volume so I suspected some kind of corruption or user error on my part and I ended up re-formatting those two disks to ext4. It seemed the issue had stopped but it came back pretty quickly.

Maybe I should try reformatting every disk? Sometimes if I unmount all of the disks and use `systemctl reboot` it doesn't get stuck syncing forever.

**Comment by mrc0mmand** [comment]
You can maybe do the sync separately for each filesystem (i.e. `sync -f /home/sweet/hdd`) to check if the hang is caused by a particular disk/fs or if it's a system-wide issue.

**Comment by bluca** [comment]
This is a disk/filesystem issue given 'sync' reproduces the behaviour, so closing

**Comment by dca00** [comment]
Same thing started after upgrade from Fedora 36 to Fedora 41.
Need at least a workaround.

**Comment by dca00** [comment]
Neither.
There is a LUKS partition though.

**Comment by dca00** [comment]
> LUKS uses DM as a backend. So the bug fix should work for you.

Ah, got it! Thanks!



> BTW, huge jump !!

Huge in the amount of broken stuff, yes. In terms of something useful new - not so much.

**Comment by dca00** [comment]
This is now fixed.

**Comment by adamency** [comment]
@dca00 How did you fix it ? or how was it fixed ?

**Comment by dca00** [comment]
It was fixed by one of the Fedora updates. Dunno which one.
