### ISSUE TITLE
hwdb: MOUSE_DPI for ROCCAT Kone XTD

### ISSUE THREAD

**Issue by GordanV** [systemd/systemd#3003]
There you go:

```
mouse:usb:v1e7dp2e22:name:ROCCAT ROCCAT Kone XTD:
 MOUSE_DPI=XXX@1002
```

**Comment by martinpitt** [comment]
You need to actually tell us the value of XXX for this to  make any sense. Also, 1002 Hz is a very strange frequency, how did you get this number?

http://who-t.blogspot.de/2014/12/building-a-dpi-database-for-mice.html describes how to measure this.

**Comment by medhefgo** [comment]
What's the point to this in the first place for roccat kone mice anyways? You can actually program these mice to use any DPI in a range you want.

**Comment by poettering** [comment]
cc @whot?

**Comment by whot** [comment]
@medhefgo so they work fine out of the box. if a user reconfigures them that's fine but then the behaviour will change too. this is explained at the top of the hwdb file

**Comment by poettering** [comment]
Closing, since @GordanV didn't provide the XXX values...
