### ISSUE TITLE
systemctl daemon-reexec changes keyboard mode

### ISSUE THREAD

**Issue by marmarek** [systemd/systemd#30046]
### systemd version the issue has been seen with

systemd-253.2-1.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

6.2.9-300.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Re-exec of systemd leaves keyboard mode unchanged

### Unexpected behaviour you saw

After systemd re-exec (done by glibc rpm update for example), keyboard is reset to unicode (I think?) mode. Especially, key combos like alt+f2 or ctrl+c are no longer handled by Xorg/Wayland session and behave as the system was on the text console. Specifically:
 - alt+f2 switches to tty2 (that should require alt+ctrl+f2)
 - ctrl+c kills the whole Xorg or Wayland session (confirmed on both)

There are likely other key combos that misbehave.

Starting Xorg/Wayland again fixes the issue.

### Steps to reproduce the problem

1. Have a graphical session active
2. Call `sudo systemctl daemon-reexec`
3. Press ctrl+c

**Comment by marmarek** [comment]
FWIW the issue does not happen on systemd 245.9-1.fc32.

**Comment by dtardon** [comment]
Already fixed by https://github.com/systemd/systemd/commit/4f44d2c4f76922a4f48dd4473e6abaca40d7e555 (https://github.com/systemd/systemd-stable/commit/4f4e0bab0d66ca6501432854aa3d3fcb53887796 on `v253-stable`).
