### ISSUE TITLE
`test_sysctl` from `systemd-networkd-tests.py` is unstable

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#30056]
```
07:17:45 FAIL: test_sysctl (__main__.NetworkdNetworkTests.test_sysctl)
07:17:45 ----------------------------------------------------------------------
07:17:45 Traceback (most recent call last):
07:17:45   File "/build/test/test-network/systemd-networkd-tests.py", line 3561, in test_sysctl
07:17:45     self.check_ipv4_sysctl_attr('dummy98', 'rp_filter', '0')
07:17:45   File "/build/test/test-network/systemd-networkd-tests.py", line 863, in check_ipv4_sysctl_attr
07:17:45     self.assertEqual(read_ipv4_sysctl_attr(link, attribute), expected)
07:17:45 AssertionError: '2' != '0'
07:17:45 - 2
07:17:45 + 0
```

_Originally posted by @bluca in https://github.com/systemd/systemd/issues/30050#issuecomment-1814089312_

It looks like this already happened several times from since the test was introduced (#28391) - https://github.com/systemd/systemd/pull/28571#issuecomment-1657175111

**Comment by yuwata** [comment]
Yeah, thank you for filing this issue.

**Comment by yuwata** [comment]
https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/7911/artifact/systemd-centos-ci/artifacts_all/artifacts_dqw0acr7/vagrant-logs.YDw/vagrant-arch-sanitizers-clang-testsuite.Rv7/systemd-networkd-tests.py_FAIL.log

**Comment by yuwata** [comment]
Uh... This is serious than I initially anticipated...
1. udevd saves state file _before_ executing commands specified in RUN=,
2. So, the interface may enter the initialized state _before_ udevd RUN= commands finished, by manager_rtnl_process_link() -> link_check_initialized() -> link_initialized() -> link_initialized_and_synced().
3. Then, networkd may set rp_filter value for the interface _before_ udevd invokes systemd-sysctl.
4. systemd-sysctl command requested in RUN= is invoked by udevd, and changes rp_filter again.

**Comment by yuwata** [comment]
Possible solution:
- Introduce a flag, e.g. `ID_PROCESSING=1`, when we save udev state file before invoking RUN= commands, then remove the flag at the final stage of the process. We already introduced `ID_RENAMING=1`, which is set when a network interface is renamed.

@poettering Do you have any better idea?
