### ISSUE TITLE
Able to delete messages within a time range

### ISSUE THREAD

**Issue by mailinglists35** [systemd/systemd#30063]
### Component

journalctl

### Is your feature request related to a problem? Please describe

Assume the case when a malfunction in some user binary or an inappropriate use of existing system binaries make it generates a large number of distinct log messages.

Despite preconfiguring journald.conf to accomodate a large number of messages, processing those messages with `journalctl` takes unreasonable large amount of time (without being journalctl's fault due to large numbers of messages), with `journalctl` consuming 100% of a core

````
$ nohup vmstat -w 10 | tee -a journalctl.txt & (time (journalctl --since today --no-pager 2>/dev/null | wc -l) 2>&1) | tee -a journalctl.txt; nproc |tee -a journal
ctl.txt; pkill vmstat
[2] 948447
nohup: ignoring input and redirecting stderr to stdout
--procs-- -----------------------memory---------------------- ---swap-- -----io---- -system-- --------cpu--------
   r    b         swpd         free         buff        cache   si   so    bi    bo   in   cs  us  sy  id  wa  st
   1    0         2304       200404      2318796     12562452    0    0     0    13    3    2   0   0 100   0   0
   2    0         2304       199900      2318804     12562456    0    0     0     4 8589 13803  23   2  74   0   0
   1    0         2304       199900      2318808     12562456    0    0     0     5 8740 14064  23   3  74   0   0
   1    0         2304       199868      2318808     12562456    0    0     0     2 8807 14156  23   3  74   0   0
3994801

real    0m31.855s
user    0m29.201s
sys     0m3.084s
4
[2]+  Done                    nohup vmstat -w 10 | tee -a journalctl.txt
````

### Describe the solution you'd like

an option to journalctl that can delete messages within a start and end time interval

### Describe alternatives you've considered

stopping `journald`, moving all journal files somewhere else out of `/var/log/journal` and start again with zero message history

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by bluca** [comment]
This is already implemented: https://www.freedesktop.org/software/systemd/man/latest/journalctl.html#--vacuum-size=

**Comment by vcaputo** [comment]
> This is already implemented: https://www.freedesktop.org/software/systemd/man/latest/journalctl.html#--vacuum-size=

@mailinglists35 is asking for a mid-range delete though, which isn't implemented - you can just vacuum stuff older than a point in time.

We don't really have such editing style vacuum capabilities AIUI, but maybe one could ad-hoc achieve something like this by pushing the journal data through `journalctl -o export | systemd-journal-remote -o /new/journals` with a filter in the middle to strip the unwanted entries.

**Comment by mailinglists35** [comment]
> This is already implemented: https://www.freedesktop.org/software/systemd/man/latest/journalctl.html#--vacuum-size=

how --vacuum* can cut an arbitrary time interval from the logs?

I did read the manual before posting but I could not imagine a method to delete messages starting today 1pm to today 8pm

**Comment by bluca** [comment]
It's not possible to carve arbitrary slices, and it's unlikely it can be sensibly implemented given how the journal format works. You can delete "older than" with --vacuum-time which is close enough.

**Comment by mailinglists35** [comment]
> It's not possible to carve arbitrary slices, and it's unlikely it can be sensibly implemented given how the journal format works. You can delete "older than" with --vacuum-time which is close enough.

I am afraid it is not close enough to what I asked - I *do* want to keep a long history of logs, and only trim accidents out of the journal. See my real example where I got 4.000.000 entries and it takes half a minute to process them.

**Comment by vcaputo** [comment]
> > It's not possible to carve arbitrary slices, and it's unlikely it can be sensibly implemented given how the journal format works. You can delete "older than" with --vacuum-time which is close enough.
> 
> I am afraid it is not close enough to what I asked - I _do_ want to keep a long history of logs, and only trim accidents out of the journal. See my real example where I got 4.000.000 entries and it takes half a minute to process them.

The problem is there isn't really any ability to edit journals like you're implicitly wanting here.

The closest thing today is rewriting them via an export piped into journal-remote.  Which could be better streamlined for your specific scenario if journalctl supported --since *before* --until when combined.  That may be a sensible RFE IMO.

**Comment by mailinglists35** [comment]
> The closest thing today is rewriting them via an export piped into journal-remote. 

I was able to do a test export like this

`$ journalctl --since "18:17:16" --until "18:45:19" -o export > export.j`

I am reading now how to import them back using `systemd-journal-remote`. I though it would be an easy equivalent import but apparently is way more complicated.

**Comment by mailinglists35** [comment]
alright so then I imported:

````
$ sudo /usr/lib/systemd/systemd-journal-remote -o /var/log/journal/58a5f44a949a43c1b01bdb83ee0296ac/export.journal export.j
````

then query
````
$ journalctl --file /var/log/journal/58a5f44a949a43c1b01bdb83ee0296ac/export.journal
````

one last question though, can I safely import back into the main journal (after deleting the old journal file and letting journald recreate it), without stopping journald first? I could import into an existing system file instead of a separate one, but only if journald is not running, or else it would say is corrupted and wipe it's contents and replace with the imported contents.

**Comment by vcaputo** [comment]
I think it would be preferable to place the new export.journal as an appropriately named archive and leave the current journals alone... starting the whole process off with a forced rotate so the currently active journals are empty.

But just taking a closer look at actually doing this all, I saw that systemd-journal-remote doesn't support --split-mode=host for "active" sources.  Which is unfortunate, because it's only --split-mode=host that applies the automatic rotation logic based on size etc.  With --split-mode=none you're just getting a single large resulting journal file.  This seems like a silly (and unexpected) limitation of systemd-journal-remote.  When you provide a "-" (stdin) source, it should still be able to use a directory destination with all the rotation logic.

Sorry this is so cumbersome, the tools are lacking and this scenario in particular is kind of trying to bend them to do what you want.
