### ISSUE TITLE
RemainAfterElapse=false seems not effected with a Calendar timer

### ISSUE THREAD

**Issue by wanted002** [systemd/systemd#30072]
### systemd version the issue has been seen with

245.4

### Used distribution

ubuntu20.04

### Linux kernel version used

5.4.18-91-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-timedate

### Expected behaviour you didn't see

When I write RemainAfterElapse=false in systemd-timer-test.timer,  which is timer based on calendar, I expected the timer will change to dead state after the associated service is inactive. The associated service will live 6s since triggered by systemd-timer-test.timer and will exit as expected and become inactive state.

### Unexpected behaviour you saw

However, systemd-timer-test..timer unit remains active state as waiting, and will be elapsed next time.
I tried enabled and disabled systemd-timer-test.timer but not effected at all.

### Steps to reproduce the problem

I wrote a simple test demo. The systemd-timer-test.timer file is as below:
[Unit]
Description=systemd timer test

[Timer]
OnCalendar=*-*-* *:*:30 Asia/Shanghai
AccuracySec=1
Unit=systemd-timer-test.service
RemainAfterElapse=no

[Install]
WantedBy=timers.target

The associated systemd-timer-test.service file is like this:
[Unit]
Description=Test demo

[Service]
Type=simple
ExecStart=/bin/bash -c "echo SystemdTimerTest-start && sleep 6 && echo SystemdTimerTest-end"

[Install]
WantedBy=multi-user.target

And I load these files at /lib/systemd/system/ .

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
I checked function timer_enter_waiting@timer.c. As I thought, found_realtime will be true if it's a calendar based timer, then timer_enter_elapsed will not be invoked under this condition,and as a result, the timer will not be dead since timer_enter_dead is not invoked.

By the way, I'm a newbie to systemd, especially to the code. So possibly I misunderstood this logic.Please give me some help, thanks.
```

**Comment by YHNdnzj** [comment]
> `OnCalendar=*-*-* *:*:30 Asia/Shanghai`

**Comment by YHNdnzj** [comment]
> `OnCalendar=*-*-* *:*:30 Asia/Shanghai`

Why do you think this can only elapse once? If you inspect it using `systemd-analyze calendar`, it actually triggers repeatedly.

Also, v245 is too old to be reported here. We only support the latest two versions, namely v253 and v254. Anything older than that should be reported to the distro bugtracker instead.

Closing, since this is clearly a misunderstanding and the version is ancient.

**Comment by wanted002** [comment]
Sorry for my understood , and I ignored this detail OnCalendar=*-*-* *:*:30 Asia/Shanghai, which indicates that this is a periodic clock.
