### ISSUE TITLE
Journal file rotation because of different sequence number ID

### ISSUE THREAD

**Issue by lourdas** [systemd/systemd#30092]
### systemd version the issue has been seen with

254.5

### Used distribution

Gentoo

### Linux kernel version used

6.5.11-gentoo

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

The user journal file from the previous boot should be used.

### Unexpected behaviour you saw

User log rotation happens. The kernel log reports this:

    systemd-journald[856]: /var/log/journal/xxxxxxx/user-xxxxx.journal: Journal file uses a different sequence number ID, rotating.

This happens on 3 different machines with the same systemd version.

### Steps to reproduce the problem

Version 254.4 seems to have this issue.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
The contents of journald.conf:

[Journal]
Storage=auto
Compress=yes
SystemMaxUse=2G
```

**Comment by mrc0mmand** [comment]
Yup, this happens on every reboot on a fresh Rawhide box with the latest main (514c70eb52):
```
# journalctl -o short-monotonic --no-hostname --grep rotating
[  119.477817] systemd-journald[675]: Received client request to rotate journal, rotating.
-- Boot fcd0e99ad1ab401d8f5d196419a180ae --
[    4.226909] systemd-journald[683]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/system.journal: Journal file uses a different sequence number ID, rotating.
[    4.229343] systemd-journald[683]: Rotating system journal.
[    7.233792] systemd-journald[683]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/user-1000.journal: Journal file uses a different sequence number ID, rotating.
-- Boot aee53ee593744fb9b3a16e0af67a7816 --
[    4.230151] systemd-journald[685]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/system.journal: Journal file uses a different sequence number ID, rotating.
[    4.232045] systemd-journald[685]: Rotating system journal.
[    7.506687] systemd-journald[685]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/user-1000.journal: Journal file uses a different sequence number ID, rotating.
-- Boot 6ddbdc309c9a4145ba5bcd9837dc0aad --
[    4.173848] systemd-journald[683]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/system.journal: Journal file uses a different sequence number ID, rotating.
[    4.176591] systemd-journald[683]: Rotating system journal.
[   10.305777] systemd-journald[683]: /var/log/journal/751e178cfc614b99ba96f4ef599fa7cc/user-1000.journal: Journal file uses a different sequence number ID, rotating.
```

**Comment by yuwata** [comment]
Possible solution is save seqnum ID and seqnum to EFI on shutdown, and read them on boot. @poettering WDYT?

**Comment by yuwata** [comment]
Moving this to v256 milestone.
This 'issue' is an expected side effect of e5d60d1b3b0c0b229571823c7fdd390a9562982e, and this is not serious.

**Comment by poettering** [comment]
Why is this even considered a bug, I don't follow?

**Comment by tekstryder** [comment]
> Why is this even considered a bug, I don't follow?

For frequently rebooted systems, this is causing the `SystemMaxFiles` to hit it's default 100 file limit extremely quickly.

This is causing the head of the journal to be lost well before desired to be rotated out based on other parameters, including defaults.

```
$ ll /var/log/journal/b1fa067dbeb84216ab8d4c29c1b78033/ | wc -l
100
```

The journal files have very sparse actual usage. Example from `$ journalctl --header`:

```
File path: /var/log/journal/b1fa067dbeb84216ab8d4c29c1b78033/user-1000@f7f6b01541d34e4b9fd1c851edf00009-0000000000955474-00060e263862ced8.journal
File ID: 233067d8633b4da1aa341eaae0c89441
Machine ID: b1fa067dbeb84216ab8d4c29c1b78033
Boot ID: 21af9c237f78412b9e57b090a7460e80
Sequential number ID: f7f6b01541d34e4b9fd1c851edf00009
State: ARCHIVED
Compatible flags: TAIL_ENTRY_BOOT_ID
Incompatible flags: COMPRESSED-ZSTD KEYED-HASH COMPACT
Header size: 272
Arena size: 8388336
Data hash table size: 29127
Field hash table size: 333
Rotate suggested: no
Head sequential number: 9786484 (955474)
Tail sequential number: 9787908 (955a04)
Head realtime timestamp: Thu 2024-01-04 17:26:17 EST (60e263862ced8)
Tail realtime timestamp: Thu 2024-01-04 19:27:59 EST (60e27eb9cece8)
Tail monotonic timestamp: 2h 2min 3.646s (1b485f954)
Objects: 3243
Entry objects: 626
Data objects: 1765
Data hash table fill: 6.1%
Field objects: 47
Field hash table fill: 14.1%
Tag objects: 0
Entry array objects: 803
Deepest field hash chain: 1
Deepest data hash chain: 1
Disk usage: 936.0K
```

What brought me here was the curious case where my individual journal file sizes and overall journal disk usage were never approaching their limits, regardless of setting.

As a temporary workaround measure until this is resolved, I've simply set `SystemMaxFiles` to a very high number so as to preserve older journals of interest.
