### ISSUE TITLE
"systemctl status" should not show available memory if it is merely the available physical memory

### ISSUE THREAD

**Issue by Flowdalic** [systemd/systemd#30102]
### Is your feature request related to a problem? Please describe

Systemd 255 changed the semantic of MemoryAvailable with 3565c709f587 ("cgroup: Fix MemoryAvailable= by considering physical memory"). If there is no artificial constraint, it will hold the amount of available physical memory, while it previously contained UINT64_MAX.

It support this change, it is sensible.

However, now `systemctl status` always displays the available physical memory. This creates a lot of noise, especially since systemd recently started to also show the "peak" memory. For example

```
$ systemctl status foo
…
Memory: 3.9G (available: 21.2G peak: 5.4G)
…
```

However, while "peak" memory is a unit specific value, the "available" memory is a generic value for all units that are not under memory accounting constraints.

### Describe the solution you'd like

I propose that `systemctl status` does not show the "available" memory, if it is merely the available physcial memory of the machine. The example above thus would become:

```
$ systemctl status foo
…
Memory: 3.9G (peak: 5.4G)
…
```

Note that I explicitly propose this for `systemctl status` only. The `MemoryAvailable` dbus property can still hold the value of the available physical memory. But I wonder if it wouldn't be sensible that the property also holds the information whether or not the available memory is based on the available physical memory or due to some artificial limit. But this is outside of the scope of this feature request.

### Describe alternatives you've considered

Keeping the existing behavior, as one could argue that it is consistent. However, I personally would favor the herein suggested approach and hence gave this feature request a try and see what others think.

**Comment by YHNdnzj** [comment]
I think you are actually referring to `systemctl status`? `systemctl show` just dumps all dbus properties of the unit?

**Comment by YHNdnzj** [comment]
(BTW, not closely related, but maybe we should separate different memory attributes with `, ` instead of a plain space. It feels more readable to me that way)

**Comment by Werkov** [comment]
> However, while "peak" memory is a unit specific value, the "available" memory is a generic value for all units that are not under memory accounting constraints.

Also "available" memory is unit specific (depending on accounted memory) but you likely do not see it in `systemctl status` due to rounding.

Personally, I'd display "available" never. How would that suit your needs?

**Comment by Flowdalic** [comment]
> Also "available" memory is unit specific

It's only unit specific if there the unit is subject to cgroup-based memory limiting. Otherwise it is only limited by physical memory, which applies to all units.

> Personally, I'd display "available" never. How would that suit your needs?

Maybe. But I feel like showing the available memory of the unit is advantageous if the unit's memory was explicitly limited (as opposed to be implicitly limited by physical memory).

**Comment by Flowdalic** [comment]
> I think you are actually referring to `systemctl status`? `systemctl show` just dumps all dbus properties of the unit and doesn't match the description?

Right, thanks! (the code is in `systemctl-show.c` though)
