### ISSUE TITLE
AllowList= option from [DHCPv4] section in a .network file doesn't work

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#30107]
### systemd version the issue has been seen with

252.5

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Unexpected behaviour you saw

I have a running DHCP server in my LAN.
I've configured a AllowList= option below a [DHCPv4] section in a .network file from a client machine with another,  **inexistent** DHCP Server IP address
What I expected was Systemd-networkd would warn me about the impossibility of getting any valid network data (maybe at Journal, maybe though an console error...) because that bad DHCP server, but, instead, it gets network data from my other running DHCP server without any problem.

### Steps to reproduce the problem

Add for instance this line into your .network file ...

```
[Match]
Name=yourinterfacename
[Network]
DHCP=yes
AllowList=whatevernonexistantIP
```

... and restart Systemd-networkd. If you have a valid DHCP server, you'll continue to get valid network data from it, instead of blocking it.

**Comment by yuwata** [comment]
You can find log message in the journal something like the following:
```
test.network:5: Unknown key name 'AllowList' in section 'Network', ignoring.
```

**Comment by q2dg** [comment]
Sorry, I've written badly my example (rush is not my friend).  This is the good one:

[Match]
Name=yourinterfacename
[Network]
DHCP=yes
[DHCPv4]
AllowList=whatevernonexistantIP

**Comment by yuwata** [comment]
Still you can find something like the following:
```
test.network:6: Address prefix is invalid, ignoring assignment: whatevernonexistantIP
```

**Comment by yuwata** [comment]
-> #30110

**Comment by q2dg** [comment]
> Still you can find something like the following:
> 
> ```
> test.network:6: Address prefix is invalid, ignoring assignment: whatevernonexistantIP
> ```
> 
> (Yeah, the log message neither show the setting name `AllowList=` nor section name `[DHCPv4]`. I will improve the message.)

Sorry, but I've not explained well :  assignement "whatevernonexistantIP" has to be ignored, of course. What I meant is that if you put a VALID IP as a value of AllowedIPs= **but this address IS NOT BELONGING TO ANY DHCP server**, Systemd-Networkd continues searching others DHCP servers and, if there are some, getting leases from them, which it's not what I expect; I'd expect Systemd-Networkd threw some error.

**Comment by yuwata** [comment]
Feel free to request to reopen this page when you provide the detailed info.
