### ISSUE TITLE
Allow different MTU range for AF_CAN family

### ISSUE THREAD

**Issue by ragazenta** [systemd/systemd#30140]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

We want to configure virtual CAN interface (vcan) using `systemd.networkd`.

```ini
[Match]
Type=can

[Link]
MTUBytes=16
RequiredForOnline=no
```

But I got a warning
```log
Maximum transfer unit (MTU) value out of range. Permitted range is 68…4294967295, ignoring: 16
```

I see that currently, systemd will assume IPV4 MTU if unspecified. See [parse-util.c](https://github.com/systemd/systemd/blob/main/src/basic/parse-util.c#L140)

There are 2 MTUs for CAN, see Kernel [doc](https://docs.kernel.org/networking/can.html#can-fd-flexible-data-rate-driver-support):
```
MTU = 16 (CAN_MTU)   => Classical CAN device
MTU = 72 (CANFD_MTU) => CAN FD capable device
```

### Describe the solution you'd like

Modify `parse-util.c` to handle `AF_CAN` family.

### Describe alternatives you've considered

n/a

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by yuwata** [comment]
Hm... After briefly reading the kernel doc, the MTU should be changed by the kernel automatically when `FD` feature(?) is enabled or disabled, right?

**Comment by yuwata** [comment]
Fix is waiting in #30156.

**Comment by ragazenta** [comment]
Is that pull request will also fix if I specify `MTUBytes` in .netdev file?

```ini
[NetDev]
Name=vcan0
Kind=vcan
MTUBytes=16
```

**Comment by yuwata** [comment]
Not sure. I will check.

**Comment by yuwata** [comment]
> ```ini
> MTUBytes=16
> ```

Confirmed, it works with PR #30156.
