### ISSUE TITLE
Assertion failure in `loop_write_full`

### ISSUE THREAD

**Issue by richardmaw-codethink** [systemd/systemd#30152]
```
[   36.321469] systemd-logind[546]: Assertion '(size_t) k <= nbytes' failed at src/basic/io-util.c:171, function loop_write_full(). Aborting.
```

I think it's failing to handle EAGAIN properly,
since the alternative is that the write succeeded and k returned more than nbytes
which should not be possible.

`k = write(fd, p, nbytes);` returns some k < 0 if it fails
and `if (errno != EAGAIN || timeout == 0) return -errno`
means the assert is only reachable on EAGAIN on a non-zero and non-infinite timeout.

The `fd_wait_for_event` is supposed to block until writable
and should return `r == POLLOUT` since it returns .revents
on success, which is a mask of the passed events.

However, instead of trying again it falls-through to the assert
because it only retries when the poll returns a transient error or the timeout was infinite.

This appears to have been added in https://github.com/systemd/systemd/pull/29071 by @YHNdnzj 

The test where I encountered this failure can be run by `mkosi --image=system '--kernel-command-line-extra=SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-23.units:/usr/lib/systemd/tests/testdata/units: systemd.unit=testsuite.target systemd.wants=testsuite-23.service noresume oops=panic panic=1 systemd.wants=end.service' qemu` but it doesn't reliably happen.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #30154.
