### ISSUE TITLE
TPM module must be loaded by the pcrphase-initrd time

### ISSUE THREAD

**Issue by t184256** [systemd/systemd#30164]
### systemd version the issue has been seen with

254

### Used distribution

NixOS

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

I expect my / bound to TPM2 and PCR registers to reliably automatically decrypt.

### Unexpected behaviour you saw

During boots when pcrphase-initrd wins the race against loading the TPM module (which is done in systemd-modules-load.service in my case), `systemd-pcrextend --graceful enter-initrd` became a no-op, my PCR measurements were off and my unattended boot failed.

### Steps to reproduce the problem

1. have your tpm driver compiled as a module
2. `ukify build ... --measure --phases enter-initrd`
3. use the resulting hash in `systemd-cryptenroll --tpm2-pcrs=...`
4. have a sometimes-unattended boot

**Comment by t184256** [comment]
More context in #30160. Summary of proposals:

a. @t184256: pcrphase-initrd grows an `After=systemd-modules-load.service`, TPM module has to be listed or compiled in, `ConditionSecurity=measured-uki` users have to stomach an extra delay
b. @poettering: require users/distributions to compile in TPM drivers
c. @poettering: add a unit waiting for TPM, generate a dependency on it if TPM hardware is present

**Comment by t184256** [comment]
d. @t184256: have two pcrphase-initrd units: an opportunistic one that tries to enter-initrd asynchronously; and a pessimistic one conditioned on the first one failing due to the lack of TPM device, that waits on all possible module loading, tries again (and warns that this configuration is suboptimal and can be sped up)

**Comment by poettering** [comment]
#30194 should fix your issue
