### ISSUE TITLE
systemctl reboot command not loggin optional message to journal

### ISSUE THREAD

**Issue by hruskape** [systemd/systemd#30167]
### systemd version the issue has been seen with

254.5

### Used distribution

Fedora 39

### Linux kernel version used

6.5.11-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

After executing `systemctl reboot --message="TEST_REBOOT"` expecting journal log `System is rebooting. (TEST_REBOOT)`
This was working in v250 (Fedora 36), since v251 extra message is missing in log. Man page still suggesting that message should be written to journal.

### Unexpected behaviour you saw

In log can be found only default message `System is rebooting.`, optional message is omitted.

### Steps to reproduce the problem

Execute reboot command with --message option specified. And after system is back online, check journal log.

**Comment by yuwata** [comment]
Caused by 5ed73478e1b1560274038ef30ec6f89022b4d8f6 and aa6123e85e0baea21b6daad175da43ffea30629f.
Fix is waiting in #30174.

**Comment by hruskape** [comment]
Thank you. I have cherry-picked change on top of v254.6 release and change is solving issue in my test.
