### ISSUE TITLE
hwdb: MOUSE_DPI for Zelotes wireless gaming mouse

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#3017]
mouse::usb:v1d57pfa60:name:Compx 2.4G Receiver:
MOUSE_DPI=1200@511

**Comment by martinpitt** [comment]
http://www.amazon.com/Zelotes-Wireless-Gaming-Buttons-Optical/dp/B00VE3JWB0 says that this defaults to 1000 dpi, but it can be configured. But this does not even have 1200 DPI as an option?

**Comment by poettering** [comment]
cc @whot?

**Comment by poettering** [comment]
@whot? @jfranc0?

**Comment by whot** [comment]
sorry, was waiting for feedback from @jfranc0 

@martinpitt given that this is a receiver there's a chance that this one is re-used for other devices. In which case we can't really add DPI information, we'd mess up the other devices. This would have to be a local config.

**Comment by martinpitt** [comment]
So that sounds like closing because it is "won't fix"?

**Comment by whot** [comment]
Closing as wontfix until someone disproves my comment above :)
