### ISSUE TITLE
Stair step text on shutdown

### ISSUE THREAD

**Issue by jonnygrant** [systemd/systemd#30184]
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-13-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Still seeing this stairstep text systemd 253 (253.5-1ubuntu6.1)
Ubuntu 23.10

I reported the issue in 251, and fix was 1st Dec 2022  #25490

The release of 253 was Feb 2023, so looks like that fix wasn't enough.

### Unexpected behaviour you saw

Same #25490  staircase pattern of text on shutdown 

### Steps to reproduce the problem

Shutdown Ubuntu 23.10 (mantic) with the text visible on screen.

I recall once I needed to set "nosplash" in GRUB_CMDLINE_LINUX_DEFAULT
/etc/default/grub  text file

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
How should I set SYSTEMD_LOG_LEVEL=debug environment variable ?

ps. I did wonder why this github bug report has emoji 🐛 in the url.
```

**Comment by yuwata** [comment]
I guess this will be fixed by #30183.

**Comment by poettering** [comment]
→ 30190 should address this. would be lovely if you could test this.

**Comment by jonnygrant** [comment]
> → 30190 should address this. would be lovely if you could test this.

Thank you Poettering for making the fix.

Sorry I don't have a spare computer to test a new systemd build on.  Maybe if you do a new release, Ubuntu will push out a new package.

I did wonder why it only shows up for me in Ubuntu.
