### ISSUE TITLE
[Feature Request] Add new keys "start-and-enable" and "stop-and-disable" for services

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#302]
Nowadays user should type "systemctl start something.service && systemctl enable something.service" to start service and make it enabled with system start. The same case when user stops and makes service disabled. I think the possibility of "systemctl start-and-enable something.service" and "systemctl stop-and-disable something.service" will be more convenient for a user as the _additional keys_ to stand-alone "start", "stop", "enable", "disable" keys.

P.S. The logic is about the same to "restart-or-reload" and "reload-or-try-restart" keys in systemctl.

**Comment by ronnychevalier** [comment]
Hi,

There is already the --now option.

systemctl --now enable xxx.service
systemctl --now disable xxx.service
systemctl --now mask xxx.service

It will stop or start the service only if disable/enable/mask is successful.

**Comment by belm0** [comment]
The behavior of `systemctl enable --now` and `systemctl disable --now` are subtly different than start & enable / stop & disable.  The former are only effective if the service isn't already in the requested enabled / disabled state.

This seems very likely to catch users by surprise.  (E.g. they might think `disable --now` is sufficient in package prerm script, but it will leave service of the removed package running if the user happened to have disabled the package.
