### ISSUE TITLE
utmp_put_dead_process doesn't lookup entries properly

### ISSUE THREAD

**Issue by NeilW** [systemd/systemd#30213]
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu (development branch)

### Linux kernel version used

6.5.0-9-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

systemd should clean up utmp/wtmp entries after using `machinectl shell <user>@` logins. 

### Unexpected behaviour you saw

No 'DEAD PROCESS' entries are being written to utmp or wtmp on logout. 

### Steps to reproduce the problem

Use machinectl shell to login to another user locally while running 'utmpdump' on the utmp and wtmp files (var/run/utmp and /var/log/wtmp on Ubuntu).

**Comment by NeilW** [comment]
The problem is at

https://github.com/systemd/systemd/blob/6a42bdb37e3963f2d1e29814b714f1673fbbc595/src/shared/utmp-wtmp.c#L224

The `copy_suffix` call should be directed to `lookup`, not `store`

**Comment by poettering** [comment]
Yeah, this was broken in f1d553e9dfd56f95b7564dd20a0b56e6a0d6492c

**Comment by yuwata** [comment]
-> #30221.
