### ISSUE TITLE
Systemd 255~rc3 Journal failure ' Assertion 'left < right' failed ' when debugging enabled (sleep state changes)

### ISSUE THREAD

**Issue by aenertia** [systemd/systemd#30210]
### systemd version the issue has been seen with

systemd-255~rc3-1.fc40.src.rpm

### Used distribution

Fedora Rawhide (F40)

### Linux kernel version used

6.7.0amdfw-rc2+

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-journald

### Expected behaviour you didn't see

Journal should continue to function as normal (regression from 255-rc2).

### Unexpected behaviour you saw

after upgraded package from rawhide of 255-rc3 was pushed on the 25/11/2023 several debugging scripts now fail. Appears to be related to enabling several debug outputs at once. systemd fails to return state correctly to the debug script and then keeps temporary debug output enabled and spams the journal.

### Steps to reproduce the problem

Was conducted using the following debug script which is designed to test s2idle state on amd platforms 

https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py

This script works fine preceding the -rc3 updates and now segfaults with the newer version of systemd. A separate bug was filled initially on the tracker here:

https://gitlab.freedesktop.org/drm/amd/-/issues/3012

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 27 10:44:09 emiemi kernel: GPIO 8 is actRoot directory /var/log/journal removed.
Root directory /run/log/journal removed.
Directory /var/log/journal/0abbe6bede8c469781f868961fdc7aae removed.
mmap cache statistics: 142755 category cache hit, 8240 window list hit, 109 miss
ive: 0x18141b00
Nov 27 10:44:10 emiemi kernel: GPIO 8 is active: 0x18141b00
Nov 27 10:44:11 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:12 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:13 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:14 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:15 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:16 emiemi kernel: GPIO 5 is active: 0x10141b00
Nov 27 10:44:17 emiemi kernel: GPIO 5 is active: 0x10141b00
aenertia@emiemi:~/Downloads$
```

**Comment by aenertia** [comment]
Example of error in stdout from journal

```
aenertia@emiemi:~/Downloads$ sudo ./amd_s2idle.py 
[sudo] password for aenertia: 
Location of log file (default s2idle_report-2023-11-26.txt)? 
Debugging script for s2idle on AMD systems
💻 Framework Laptop 13 (AMD Ryzen 7040Series) (Laptop) running BIOS 3.3 (03.03) released 10/17/2023 and EC unknown
🐧 Fedora Linux 40 (KDE Plasma Prerelease)
🐧 Kernel 6.7.0-master+
🔋 Battery BAT1 ( ) is operating at 100.64% of design
Checking prerequisites for s2idle
✅ Logs are provided via systemd
✅ AMD Ryzen 7 7840U w/ Radeon  780M Graphics (family 19 model 74)
✅ LPS0 _DSM enabled
✅ ACPI FADT supports Low-power S0 idle
✅ HSMP driver `amd_hsmp` not detected (blocked: False)
✅ PMC driver `amd_pmc` loaded (Program 0 Firmware 76.70.0)
✅ USB4 driver `thunderbolt` loaded
✅ GPU driver `amdgpu` available
✅ System is configured for s2idle
✅ NVME Sandisk Corp WD Black SN850X NVMe SSD is configured for s2idle in BIOS
✅ GPIO driver `pinctrl_amd` available
How long should suspend cycles last in seconds (default 10)? 
How long to wait in between suspend cycles in seconds (default 4)? 
How many suspend cycles to run (default 1)? 
Started at 2023-11-26 20:20:07.596579 (cycle finish expected @ 2023-11-26 20:20:21.596600)
Results from last s2idle cycle
Assertion 'left < right' failed at src/libsystemd/sd-journal/journal-file.c:3086, function generic_array_bisect(). Aborting.
Aborted
aenertia@emiemi:~/Downloads$ 
```

**Comment by yuwata** [comment]
Could you provide the .journal file(s) that causes the assertion?

**Comment by aenertia** [comment]
Could you advise how and where to obtain these?

**Comment by aenertia** [comment]
Just a comment this issue persisted when reverting to older / known stable kernels. Initially I had thought it was something to do with the patchset I was running trying  to debug unrelated issues with amd-pstate, but the bug followed. This was encountered on my daily driver so I have since moved to a non rawhide release. I'll need to reinstall rawhide to trigger the bug again if you need additional debug output. The linked bug initially filed includes additional output/logs.

**Comment by yuwata** [comment]
> Could you advise how and where to obtain these?

You can find .journal files under /var/log/journal/MACHINE_ID/ or /run/systemd/journal/.
If the journal contains some private data you want not to make public, then please save the journals e.g. google drive or so, and send me a link.

**Comment by yuwata** [comment]
Or, could you test #30211 ?
