### ISSUE TITLE
ukify produces unbootable UKIs

### ISSUE THREAD

**Issue by SoapGentoo** [systemd/systemd#30228]
### systemd version the issue has been seen with

255-rc3

### Used distribution

Gentoo

### Linux kernel version used

6.1.63-gentoo-dist

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

After running dracut+ukify to produce a UKI, I have a bootable kernel.

### Unexpected behaviour you saw

`ukify` produces an unbootable kernel. Without `ukify` (using only dracut for producing the UKI), the kernel works fine.

### Steps to reproduce the problem

In Gentoo, I produce the kernel normally by setting `uki_generator=ukify` in `/etc/kernel/install.conf` and the resulting UKI is broken.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-boot: Assertion 'prefix' failed at ../systemd-255-rc3/src/boot/efi/stub.c:372@load_addons, halting.
```

**Comment by poettering** [comment]
What boot loader did you use? i presume some legacy thing like grub?

**Comment by yuwata** [comment]
Could you test #30238 ?

**Comment by SoapGentoo** [comment]
> What boot loader did you use? i presume some legacy thing like grub?

vanilla systemd-boot 255

**Comment by poettering** [comment]
Interesting. That would suggest your firmware generates device paths we cannot quite parse correctly. is there anything weird about your boot? i.e. network boot, or so? vm? anything?

**Comment by SoapGentoo** [comment]
nope, vanilla UEFI on a X570 chipset, nothing fancy

**Comment by poettering** [comment]
#30240 should address the issue for you, but there's an underlying issue we might need to address, the fact that we cannot parse the device paths your firmware gives us.

if you hit "p" in sd-boot, does it show you the "loaded image" line? (should be the second in the info dump). What does it say there?

**Comment by SoapGentoo** [comment]
![Uploading IMG_1117.jpeg…]()

**Comment by SoapGentoo** [comment]
![IMG_1117](https://github.com/systemd/systemd/assets/16636962/49146676-2eb0-4c59-9a46-840e886b2f93)

**Comment by SoapGentoo** [comment]
Ok, both #30238 and #30240 fix the issue for me. And yes, please backport this, since 254 is also affected by it.
