### ISSUE TITLE
rootless systemd-nspawn

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#30239]
### Component

machinectl, systemd-nspawn

### Is your feature request related to a problem? Please describe

As mentioned [here](https://github.com/systemd/mkosi/issues/726#issuecomment-863028220) by @poettering, a rootless mode for systemd-nspawn would be great to be able to boot into a container without needing root. As that comment was a few years ago and I didn't find an open feature request I'd like to just open this one to revive that idea and ask nicely about the progress on it.

### Describe the solution you'd like

on Jun 17, 2021 @poettering described it as:
> systemd-nspawn does not support invocation by non-root users though, but that#s something to address in nspawn

Basically I'd like to be able to use systemd-nspawn to start a container without the invoking user having to have root privileges to allow for a rootless usage. Usages are for example within "makechrootpkg" on archlinux (which uses systemd-nspawn internally) to run reproducible builds without needing needing root privileges to enter the build environment.

### Describe alternatives you've considered

A yanked setup using a combination of unshare, chroot, and bind mounts to launch nspawn within a separate namespace without root privileges. I've seen it being mentioned in some docs for non-systemd systems, but the instructions weren't entirely clear and complete, so I didn't try if that actually works. But systemd these days sometimes also runs within docker containers, so it probably will.
While testing my main issue was to mount /dev into the new root directory, but anything else appeared to just work. Sadly because of the problems with /dev systemd couldn't be initialized within the new namespace and just failed to start with a permission error.

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by septatrix** [comment]
How would this compare security wise to setting `--user` and `--private-users`? Would it be better, worse, or should they even be combined?

Currently the nspawn documentation states for its `--user` flag, which is different from systemd.exec's `User=`:

> Like all other systemd-nspawn features, this is not a security feature [...]

My guess would be that using `User=dynamic` and rootless nspawn might improve security compared to the status quo?

**Comment by poettering** [comment]
Fixed by #26826
