### ISSUE TITLE
s390x default consoles cannot parse colored output

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#3024]
### Submission type
- [ X ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu
> Centos/RHEL/z/KVM
### In case of bug report: Expected behaviour you didn't see

on mainframes there are a few virtualisation modes:
- LPAR
- z/VM
- z/KVM (kvm / qemu)

Most of installs are LPAR or z/VM and installing things into qemu hypervisor is relatively new thing (ditto e.g. OpenStack).

LPAR and z/VM do not have a typical console available, at most one has line console access via HMC, which is a java web-app running on the mainframe. Those line consoles cannot display color escape codes, nor do they strip them.

The end result is that ones Operating System Messages is spammed with:

```
[[0;32m   OK  [0m] Started whatever
```

Which is not nice. qemu / kvm is amazing, it does color escape codes right and is really fast, uses ASCII encoding and all the usual things one expects from a console.

So, may I ask for LogColor=no setting to be automatically used?

There are a couple of options/conditions to default to LogColor=no:
- on all s390x, always
- on s390x, when console is slcp*
- on s390x, when systemd-detect-virt is "none", "zvm"

I understand it is not nice to have arch-specific defaults, but if we don't fix this upstream every distribution on mainframes needs to either ship a system.conf snippet or otherwise turn-off LogColor support.

I'll check when the colors are setup, and weather at the time systemd-detect-virt is called, the color support can be turned off.
### In case of bug report: Steps to reproduce the problem

> Just boot and watch console messages via HMC

**Comment by poettering** [comment]
A new issue to track this is #3115. Closing this one.
