### ISSUE TITLE
ExecStartPreRoot= and ExecStartPostRoot= required

### ISSUE THREAD

**Issue by hadmut** [systemd/systemd#30243]
### Component

systemd

### Is your feature request related to a problem? Please describe

I need to run services as a non-root user and start them as a systemd service unit, even as a template unit. Even the user name itself may be set as the template variable, i.e. User=%i  to have a particular daemon run for each user where it has been started as a template. 

Unfortunately, something like 

ExecStartPre=mkdir /var/someservice/%i
ExecStartPre=chown %i:%i /var/someservice/%i

to create a per-user-directory owned by the user wouldn't work, since ExecStartPre is run by the user given in User= and thus lacks the privileges to do so. 

### Describe the solution you'd like

I'd like to have a second set of directives, e.g.

ExecStartPreRoot= 
ExecStartPostRoot=

which do work like ExecStartPre and ExecStartPost, but run as root (before ExecStartPre and after ExecStartPost)

(May/could/should be restricted to units where User= is used.)

### Describe alternatives you've considered

ugly workarounds with sudo, but difficult to get smooth, clean, and secure.

**Comment by bluca** [comment]
This is already implemented by using `!` or `+` in ExecStartPre= and friends, see: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines
