### ISSUE TITLE
Reboot is needed to update PCR set after updating initramfs

### ISSUE THREAD

**Issue by MathijsNL** [systemd/systemd#30259]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-13-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

After updating initramfs and running systemd-cryptenroll there should be a new PCR set but this does not seem the case.

### Unexpected behaviour you saw

This message is displayed:
**This PCR set is already enrolled, executing no operation.**

Aftar an initramfs update the PCRs can't be enrolled until after a reboot.

### Steps to reproduce the problem

```
sudo update-initramfs -u
sudo systemd-cryptenroll --wipe-slot tpm2 --tpm2-device auto --tpm2-pcrs "0+1+2+3+4+5+7+8+9" /dev/nvme0n1p3
>>> This PCR set is already enrolled, executing no operation.
```

Is there a specific command that needs to be run after updating initramfs to make the cryptenroll aware that there are changes to the initramfs?

**Comment by poettering** [comment]
The logic will enroll *current* PCRs, so if you rebuild your initrd, the tool won#t care.

Update to systemd 255, and you can specify PCRs literally, and thus pre-calculate them and specify them and the enroll.

That sais, just use systemd-pcrlock instead which also comes with systemd 255, and automates all this comprehensively.
