### ISSUE TITLE
[RFE] Systemd ask password clients must be run as root: should be a group to allow access 

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#3027]
### Submission type
- [ ] Bug report
- [ X] Request for enhancement (RFE)

Short version:
Introduce new group which would have access to the ask-password directory, so it could be used by daemons that run under non-root user.

Long version:
https://bugzilla.redhat.com/show_bug.cgi?id=1322167

**Comment by fsateler** [comment]
semi-duplicate of #1232 ?

**Comment by poettering** [comment]
Yeah, closing as duplicate of #1232.
