### ISSUE TITLE
/var/tmp on NFS is currently not supported when networkd is used for connectivity, due to ordering cycle

### ISSUE THREAD

**Issue by TKSpyrop** [systemd/systemd#3028]
Hello,

It has been observed that if /var/tmp is bind-mounted on network storage, after basic.target is up, the following ordering cycle is discovered during system reboot:

systemd-logind[174]: System is rebooting.
systemd[1]: basic.target: Found ordering cycle on basic.target/stop
systemd[1]: basic.target: Found dependency on var-tmp.mount/stop
systemd[1]: basic.target: Found dependency on network.target/stop
systemd[1]: basic.target: Found dependency on systemd-networkd.service/stop
systemd[1]: basic.target: Found dependency on dbus.service/stop
systemd[1]: basic.target: Found dependency on basic.target/stop
systemd[1]: basic.target: Breaking ordering cycle by deleting job var-tmp.mount/stop
systemd[1]: var-tmp.mount: Job var-tmp.mount/stop deleted to break ordering cycle starting with basic.target/stop

mount | grep /var/tmp
x.x.x.x:/mstate on /var/tmp type fuse.glusterfs

systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

Is this some known/harmless behaviour?
If /var/tmp is manually unmounted before reboot, the cycle is absent.
What is the meaning of the dependency between basic.target and mount units listed in RequiresMountsFor= ?

Thank you

**Comment by poettering** [comment]
Well, networkd currently is ordered after dbus, which means it cannot be used during early boot, but only late boot. And /var/tmp is one of those dirs that must be mounted during early-boot, and cannot be mounted in late boot. Hence you get the cyclic loop.

Or in other words: we simply don't support what you are doing there, at the moment. We should support it eventually, but that would mean we'd have to make some form of D-Bus available during early-boot. Which won't be any time soon i fear.

**Comment by TKSpyrop** [comment]
Thanks for the detailed info. How severe is this, can it cause trouble? 
I tried to add a service, as a temporary solution, that umnounts /var/tmp before shutdown, but it seems that it is invoked after the point at which the dependencies are calculated, so it has no effect. Have you any other idea of a possible workaround?

**Comment by poettering** [comment]
My suggested work-around would be to no use /var/tmp on NFS. And if that's not possible consider overriding basic.target, and dropping /var/tmp from the RequiresMountsFor= line. YMMV.

**Comment by TKSpyrop** [comment]
Can mounting on NFS cause unmounting to malfunction during shutdown? I mean, logs like:
systemd[1]: Failed unmounting /mnt/mstate
where:
x.x.x.x:/mstate on /mnt/mstate type fuse.glusterfs
can be related to this issue?

**Comment by poettering** [comment]
I don't know glusterfs, I can't help you there. Sorry.

**Comment by yuwata** [comment]
This should be already fixed. Closing.
