### ISSUE TITLE
systemd-homed service unit SystemCallFilter needs quotactl 

### ISSUE THREAD

**Issue by NeilW** [systemd/systemd#30287]
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-13-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-homed

### Expected behaviour you didn't see

Unable to set quotas on a standard ext4 home directory 

### Unexpected behaviour you saw

`Dec 01 15:20:55 srv-bxqub systemd-homework[1406]: Failed to query disk quota for UID 60163: Operation not permitted`

### Steps to reproduce the problem

`homectl create --real-name="Agent 1" --disk-size=100M --storage=directory --tasks-max=20 --noexec=true agent0001`

**Comment by NeilW** [comment]
This line in the service unit

https://github.com/systemd/systemd/blob/ba47598aef731c0945eab2248af862815c8d2b43/units/systemd-homed.service.in#L35

needs `quotactl` adding to it

as called from here

https://github.com/systemd/systemd/blob/ba47598aef731c0945eab2248af862815c8d2b43/src/shared/quota-util.c#L22

**Comment by bluca** [comment]
Can you please send a PR to do so?
