### ISSUE TITLE
IPv6 shorthand to make IPv6 address more readable

### ISSUE THREAD

**Issue by RmsMit** [systemd/systemd#3030]
### Submission type
- [ ] Bug report
- [ x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_

IPv6 addresses are long and difficult to remember but you might not want to go to the trouble of setting up DNS host resolution.

I propose that the IPv6 interfaceID component (last 64bit) of the address could be set to the Hash of the hostname. This will mean that resolved could simply convert the hostname to an IPv6 address based on the hostname supplied.

eg if you did "ping myhost" then resolved could return an IPv6 address based on the same first 64bits  of the local network and the last 64bit as the hash of "Myhost"

Ethernet interface IPv6 addresses are based of the Router Announcement (prefix and subnet) and the next 64 bit (the interfaceID can be picked based on ethernet's Mac address or picked at random. If instead of picking the last 64bits at random we set it to the hash of the hostname then the above proposal could easily just resolve hostnames without any special effort, while still being a pseudo random IPv6 address since you can't easily reverse a hash.

Further to this if you prefixed the hash-hostname with a real resolvable hostname then resolved could return the first 64bits (prefix and subnet) from the prefixed host and the last 64bits from the hash of the hostname. This way you could use a known hostname with a hash-hostname to resolve a host on a different network.

eg if we have the following servers on the same network 

```
myserver 2001:2:2:2:8b88:6da3:68de:29c1 ## where 8b88:6da3:68de:29c1 is the hash of myserver 
othersvr   2001:2:2:2:36f9:2b23:b02c:d4c4 ## where 36f9:2b23:b02c:d4c4 is hash of "othersrv"
```

Then running "ping othersvr" on myserver will result in pinging 2001:2:2:2:36f9:2b23:b02c:d4c4 with the 2001:2:2:2 coming from the same network component as myserver and the rest coming from hashing the hostname othersvr.

Also if we had the hosts remotenet 2001:3:3:3::3 defined in our hosts file then we could resolve any other machine in the same net as remotenet in a similar manor.

ping remotenet:otherremote

Would resolved to pinging 2001:3:3:3:c599:4215:7f80:63a6 getting the 2001:3:3:3 part from the conventionally resolved remotenet hostname and the remainder being the has of "otherremote"

I think this could be done without interfearing with normal revolve methods. If the IPv6 address is set to the hash of the hostname it will make life easy and if not you have lost nothing.

Would this work? 

Would it be useful?

**Comment by RmsMit** [comment]
Additional to my last post maybe to prevent any clash with normal hostname resolving and so not have to wait till normall resolve method timesout we could be more specific about the fact that we want to resolve to the hash of the host as follows:-

Proposal part 1:

host-names beginning with R: would be used to write the shorthand for the first 64bit (the RA announced part) so
R:mynet: would be replaced by the RA component of the host mynet this way if you wanted to ping a server in the same network as mynet host but it did not have a resolvable hostname of its own you could save yourself writing/remembering the 1st 4 blocks of hex address numbers. You could put a host mynet as 2001:32:ed:a3:: in your DNS or hosts file and only have to remember the "mynet" when trying to address any host in that net.
If you left out the mynet name and just had R:: that would be a shortcut for R:localhost: and so save you typing the first 4 blocks of your own local network.

Proposal part 2:

For the remaining 4 address blocks we can use the has of the hostname. In IPv6 the last 4 blocks of the address are often picked at random by the OS when it starts. It could just as easily pick those last 4 blocks based on the has of the hostname. To all intents and purposes this would still be random to anyone who did not know the hostname of the machine but now we could use the hostname in our ping and have it calculate the address without having to have a DNS.

Result:

a local lookup of the hostname R::myhost even when resolved only localy would result in an IPv6 address with the 1st 4 blocks of my localnetwork and the last 4 blocks of address based on the has of "myhost' and if myhost server set the address the same way it would just ping

Likewise R:mynet:myhost would resolve for a host in mynet network. So if you just setup mynet in your /etc/hosts file you could resolve any machine in your network without DNS or relying on bonjour/avahi or neighbour discovery (all of which do not traverse network boundaries) and if mynet is an IP routable address (which everyone would have with IPv6) you could access these machines from anywhere (firewalls permitting of course).

Now My questions:-
1) Is this a good idea? are there other ideas that work better or already in place for this?

2) If it is a good idea then I think resolved is good upstream project to put it in as it is widespread and may lead the adoption?

**Comment by poettering** [comment]
I am not sure we should invent our own logic here. This is about interoperability after all, i.e. hosts finding each other on the network. If there'd be an RFC or so about this, then sure, we can look into this, but we are not in the business of defining our own protocols and behaviours here, we just implement established standards...

**Comment by RmsMit** [comment]
Respectfully this is not a protocol and it would not affect normal host resolution. It would be only a local resolution. The resolved service checks several sources for possible ways to figure out the IP of the host not all of them are based on RFCs. 

The resolution of the host-name "gateway" for example is very much along the same lines as what is proposed here. The difference is instead of looking up the the default IP routing we take the hash of the passed "hostname" and use that as the IP.

There are characters that are not used in hostnames that could be used for this kind of text to hash/IP to ensure there is no ambiguity between regular hostname. This is what I tried to allude to in my last post but there are possibly better ways to ensure no ambiguity.

**Comment by teg** [comment]
I agree with @poettering on this. Let's not invent something new. This is a general problem, so if anything there should be some RFC with a general solution that we could adopt. But we should not roll our own (sure I see the analogy to 'gateway', but that is arguably very, very limited, and not something we should be extending I think).
