### ISSUE TITLE
Ability to manually configure / start network interfaces

### ISSUE THREAD

**Issue by vinaykul** [systemd/systemd#3031]
### Submission type
- [ ] Bug report
- [ X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with v229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_

Currently, networkd configures a network interface if it finds a matching configuration file for the interface name.

We are increasingly seeing the need to support a "manual" mode to configure an interface similar to STARTMODE = onboot | manual | hotplug with the ifup / ifdown facility. There is a scenario where we need to have the configuration for a particular network interface around, but not actively configured.

What is recommended way to implement such a facility in systemd-networkd?

/cc: @poettering @teg @keszybz

**Comment by clemensg** [comment]
In my (embedded system) use case, we have two modes: In mode A the ethernet port is a VLAN trunk port with several .netdev and respective .network files. In mode B it is a naive access port with just one .network file for that. To distinguish between them I am at the moment trying to use KernelCommandLine [Match] constraints in each .netdev and .network file. (for example: `KernelCommandLine=portmode=trunk` and `KernelCommandLine=portmode=access`).

Having to reboot with different kernel commandline parameters is obviously not ideal.

At the moment, the libsystemd/sd-network API can only be used to query information from systemd-networkd. Would be great if we could change that and add functions to override the active configuration file or to change the current network configuration directly?
Some way to choose between different configuration files / profiles at runtime without modifying the files themselves. In our case, the profiles are static, it's just the decision between being behind a managed switch with VLAN support or not.

Any ideas / suggestions?

**Comment by keszybz** [comment]
We've been talking about dbus interface for networkd for some time. When that happens something like "noauto" will be a natural extension. But until we have the dbus interface, there's no way to tell networkd to bring up an interface, except to update the configuration and restart it.

**Comment by clemensg** [comment]
@poettering Do you have any suggestions how a simple mechanism to switch network configuration profiles at runtime could look like?

I am thinking about adding an additional match constraint `ProfileName` which can then be set and changed at runtime through networkctl to select a subset of .network and .netdev files. This could also be used for example `ProfileName=work` or `ProfileName=home` and not just my `ProfileName=vlantrunk` and `ProfileName=vlanaccess` usecase.

Before I start working on it:
Do you think that would be a good idea? / Would you accept such a patch / PR or do you have something else in mind?

@teg @keszybz @kaysievers

**Comment by patrick7** [comment]
My suggestion is to implement something like systemd does for services:

networkctl enable eth0
networkctl start eth0
networkctl stop eth0
networkctl restart eth0
networkctl disable eth0
networkctl status eth0
networkctl daemon-reload

etc

**Comment by patrick7** [comment]
Any news? :-)

**Comment by keszybz** [comment]
This is still waiting for a champion to take this on.

**Comment by q2dg** [comment]
Somewhat related: https://github.com/systemd/systemd/issues/7593

**Comment by lkraav** [comment]
What's the current best work-around for "stopping" a single non-critical interface controlled by `systemd-networkd`?

Perhaps:
`# systemctl stop systemd-networkd`
`# ip link delete <if>

Later:
`# systemctl start systemd-networkd`

**Comment by ssahani** [comment]
```networkctl enable eth0
networkctl start eth0
networkctl stop eth0
networkctl disable eth0
```
These requires to manage config .

```
networkctl daemon-reload
networkctl restart eth0
networkctl status eth0
```
These already implemented with networkctl

**Comment by poettering** [comment]
See #16228

**Comment by keszybz** [comment]
Implemented in c30ffcee9b4960987bc8cf201138aaf0d7b26b14.

**Comment by TCB13** [comment]
Look's like `ActivationPolicy=manual` doesn't work in VLANs:

> For some reason, neither ActivationPolicy=manual nor ActivationPolicy=down shut the interfaces down; instead, systemd-networkd just ignores it on VLANs and leaves the interface up.

https://superuser.com/questions/1678714/configure-systemd-network-vlans-that-dont-auto-start

Any ideas?

**Comment by yuwata** [comment]
Could you open a new issue page about that?
