### ISSUE TITLE
systemd-dissect reports "File system type not supported or not known." for erofs DDI

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#30326]
### systemd version the issue has been seen with

main

### Used distribution

Fedora 39

### Linux kernel version used

6.5.10-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

systemd-dissect can dissect a DDI with an erofs partition

### Unexpected behaviour you saw

systemd-dissect fails with: `File system type not supported or not known.`

### Steps to reproduce the problem

- Build DDI with erofs partition
- Run `systemd-dissect <ddi> -M abc`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
➜  tmp git:(initrd) ✗ sudo SYSTEMD_LOG_LEVEL=debug ../../systemd/build/systemd-dissect mkosi.output/btrfs.raw -M abc
Opened '/home/daandemeyer/projects/mkosi/tmp/mkosi.output/btrfs.raw' in O_RDWR access mode, with O_DIRECT enabled.
Determined sector size 512 based on discovered partition table.
loop0: Acquired exclusive lock.
Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=207
Kernel was quicker than us in adding partition 1.
Opened /dev/loop0p1 (fd=3, whole_block_devnum=7:0, diskseq=207).
Kernel was quicker than us in adding partition 2.
Opened /dev/loop0p2 (fd=4, whole_block_devnum=7:0, diskseq=207).
Kernel was quicker than us in adding partition 3.
Opened /dev/loop0p3 (fd=7, whole_block_devnum=7:0, diskseq=207).
No type detected on partition /dev/loop0p1
File system type not supported or not known.
Removed partition /dev/loop0p1
Removed partition /dev/loop0p2
Removed partition /dev/loop0p3
```

**Comment by poettering** [comment]
if you attach the thing, what does "blkid -p" say about /dev/loop0p1? i mean, we just call libblkid for all signature detection stuff
