### ISSUE TITLE
systemd-udevd core file - watchdog timeout / sigabort in epoll_wait

### ISSUE THREAD

**Issue by vinaykul** [systemd/systemd#3032]
### Submission type
- [ X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 228

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> photon
### In case of bug report: Expected behaviour you didn't see

> No core files should be generated.
### In case of bug report: Unexpected behaviour you saw

> systemd-udevd generated a core due to SIGABRT from 3 min watchdog timeout while in epoll_wait in sd_event_wait().

![screen shot 2016-04-13 at 3 37 13 pm](https://cloud.githubusercontent.com/assets/12750645/14511635/bad4893e-018d-11e6-88a7-da2f28d99bc2.png)
### In case of bug report: Steps to reproduce the problem

> We see this issue occasionally in the automated test setup, and appears to happen around the times of high I/O and CPU load, especially with a NFS mounted VM datastore. We also see systemd-journald core in fsync - issue https://github.com/systemd/systemd/issues/2899 .

**Comment by poettering** [comment]
This is pretty strange. It appears as if udevd on your system is not sending the watchdog keep alive messages. Consider attaching to udevd via gdb and see whether it ever invokes sd_notify(). I have no idea why this doesn't work, but I fear there's no way to figure this out without gdb...

**Comment by poettering** [comment]
Closing. Theres not much we can do on this. thismustbe debugged locally with gdb. Sorry.
