### ISSUE TITLE
Systemd-cryptenroll with TPMA_OBJECT_NODA

### ISSUE THREAD

**Issue by glance-** [systemd/systemd#30330]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

I'm building a embedded-ish system and are using systemd-cryptenrolled root devices against a tpm2 module. We keep the rootfs read-only almost all the time, so we're really quite insensitive to abrupt power losses.

After a series of rapid power losses and returns I noted that these tpm2 locked machines coudn't unlock their root partitions, because the tpm2 module wen't into dictionary attack lockout mode. This is because if a object not flagged as TPMA_OBJECT_NODA is trying to be accessed, and the tpm2-module looses power without a tpm shutdown(clear) it increases the TPM2_PT_LOCKOUT_COUNTER. The counter is always increased on a unclean tpm shutdown, because otherwise a unclean shutdown could be used to negate the lockout-counter.

Due to the series of rapid power losses and returns, this caused the machines to increase their TPM2_PT_LOCKOUT_COUNTER higher than TPM2_PT_MAX_AUTH_FAIL , thus they wen't into DA lockout.

We lock the disk against the tpm2 module's specific PCR-values so there's nothing that can be attacked with a dictionary attack.

### Describe the solution you'd like

I'd like to see systemd-cryptenroll setting the object attribute TPMA_OBJECT_NODA if protection against dictionary attacks doesn't make sense.

If you're using a PIN, sure, dictionary attack protection makes sense, but if you're only locked against PCR-values, it doesn't.

Ugly prototype code which creates the suggested behavior but breaks other things:
```diff
diff --git i/src/shared/tpm2-util.c w/src/shared/tpm2-util.c
index ae15879..5cd487a 100644
--- i/src/shared/tpm2-util.c
+++ w/src/shared/tpm2-util.c
@@ -4052,7 +4052,8 @@ int tpm2_seal(Tpm2Context *c,
         TPMT_PUBLIC hmac_template = {
                 .type = TPM2_ALG_KEYEDHASH,
                 .nameAlg = TPM2_ALG_SHA256,
-                .objectAttributes = TPMA_OBJECT_FIXEDTPM | TPMA_OBJECT_FIXEDPARENT,
+                // TODO: ADD NODA here unless pin?
+                .objectAttributes = TPMA_OBJECT_FIXEDTPM | TPMA_OBJECT_FIXEDPARENT | TPMA_OBJECT_NODA,
                 .parameters.keyedHashDetail.scheme.scheme = TPM2_ALG_NULL,
                 .unique.keyedHash.size = SHA256_DIGEST_SIZE,
                 .authPolicy = policy ? *policy : TPM2B_DIGEST_MAKE(NULL, TPM2_SHA256_DIGEST_SIZE),
```

### Describe alternatives you've considered

I've contemplated setting TPM2_PT_MAX_AUTH_FAIL to 0xFFFFFFFF and TPM2_PT_LOCKOUT_INTERVAL / TPM2_PT_LOCKOUT_RECOVERY to 0x1 but that feels quite odd, and will interfere with other things that might in the future be tied to the tpm module.

Also, I've contemplated always running a tpm shutdown(clean) on boot, but I'm not really sure what other consequences this might cause, and the potential race is still there.

### The systemd version you checked that didn't have the feature you are asking for

254-f45536503187a45295d65d8fb42ac7bc2f4b751f

**Comment by poettering** [comment]
Related: #20668

Anyway, seems reasonable to me, but please make the flag dependent on the `pin` parameter being set.
