### ISSUE TITLE
systemd-networkd-wait-online.service fails to complete if one of the network interfaces is not physically connected

### ISSUE THREAD

**Issue by xypron** [systemd/systemd#30345]
### systemd version the issue has been seen with

253.5-1ubuntu6.1

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.5.0-13-generic

### CPU architectures issue was seen on

riscv64

### Component

systemd-networkd-wait-online

### Expected behaviour you didn't see

systemd-networkd-wait-online.service succeeds.

### Unexpected behaviour you saw

My StarFive VisionFive 2 board has two network interfaces of which I have only connected one to a switch. The systemd-networkd-wait-online.service always fails delaying boot by 150 s. The problem does not occur if both network interfaces are physically connected.

It does not make any sense to wait for the initialization of a network interface that is not physically connected.

As described in https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net the physical link state can be determined via /sys/class/net/<iface>/carrier.

### Steps to reproduce the problem

Run systemd-networkd-wait-online.service with one of the multiple network interfaces is not connected.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[  *** ] Job systemd-networkd-wait-online.se…tart running (1min 54s / no limit)

× systemd-networkd-wait-online.service - Wait for Network to be Configured
     Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Wed 2023-12-06 09:27:56 UTC; 53min ago
       Docs: man:systemd-networkd-wait-online.service(8)
    Process: 586 ExecStart=/lib/systemd/systemd-networkd-wait-online (code=exited, status=1/FAILURE)
   Main PID: 586 (code=exited, status=1/FAILURE)
        CPU: 33ms

Dec 05 10:48:40 vf21 systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
Dec 06 09:27:56 vf21 systemd-networkd-wait-online[586]: Timeout occurred while waiting for network connectivity.
Dec 06 09:27:56 vf21 systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 09:27:56 vf21 systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
Dec 06 09:27:56 vf21 systemd[1]: Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured.
```

**Comment by xypron** [comment]
Launchpad bug https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2045756

**Comment by yuwata** [comment]
I guess you have both network interface have matching .network files. In that case, then that's expected.
There are several ways to make not delay the boot process:
- Set `RequiresForOnline=no` for the .network file matching with the network interface that does not have a cable.
- Update systemd-networkd-wait-online.service to pass `--any` option.
- Update systemd-networkd-wait-online.service to pass `--interface INTERFACE`, or use systemd-networkd-wait-online@.service to watch only interface which has a cable.

Closing.

If the above does not work, feel free to request to reopen this issue. In that case, please provide all relevant .network files and debugging logs of systemd-networkd-wait-online, which can be obtained by invoking like the followng:
`SYSTEMD_LOG_LEVEL=debug systemd-networkd-wait-online`.

**Comment by xypron** [comment]
The following files where created when installing the system:

/run/systemd/network/10-netplan-end0.network
```
[Match]
Name=end0

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true
```

/run/systemd/network/10-netplan-end1.network
```
[Match]
Name=end1

[Network]
DHCP=ipv4
LinkLocalAddressing=ipv6

[DHCP]
RouteMetric=100
UseMTU=true
```

**Comment by xypron** [comment]
When adding ` [LINK] optional` to the *.network /lib/systemd/systemd-networkd-wait-online returns even if none of network interfaces is online. This does not give me the behavior described in man/systemd-networkd-wait-online.service.xml where at least one online interface is required:

"The service systemd-networkd-wait-online.service invokes systemd-networkd-wait-online without any options. Thus, it waits for all managed interfaces to be configured or failed, and for at least one to be online."

**Comment by xypron** [comment]
An overlay # /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf finally resolved my issue:
```
[Service]
ExecStart=
ExecStart=/lib/systemd/systemd-networkd-wait-online --any
```

**Comment by bam80** [comment]
No suggested solutions work for me.

I have no cables connected to the iface, WiFi only.
Also, my network is managed by Network Manager, if it makes difference:
```
$ cat /etc/netplan/00-installer-config.yaml 
# This is the network config written by 'subiquity'
network:
  ethernets:
    eno0:
      dhcp4: true
      dhcp6: true
      optional: true
  renderer: NetworkManager
  version: 2

**Comment by dejoebad** [comment]
in my case, systemd-networkd-wait-online stuck, always after switch from ubuntu server to ubuntu server with gnome.
what i do
1. install network-manager and network-manager-gome
2. disable cloud init network
3. disable all netplan.yaml network interface and promote to render with NetworkManager
4. of course disable systemd-networkd-wait-online
5. then automatically NetworkManager-networkd-wait-online takes over the systemd-networkd-wait-online
