### ISSUE TITLE
HibernateDelaySec in systemd/sleep.conf defaults to infinity and not 2h.

### ISSUE THREAD

**Issue by dlundqvist** [systemd/systemd#30350]
### systemd version the issue has been seen with

254.5-1

### Used distribution

Debian testing

### Linux kernel version used

6.5.0-5-amd64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Using IdleAction=suspend-then-hibernate in systemd/logind.conf I expect the system to hibernate after 2 hours as man page indicates is the default value.

### Unexpected behaviour you saw

It never hibernates.

**Comment by dlundqvist** [comment]
I believe the problem is at https://github.com/systemd/systemd/blob/261ee3d5392783bb171419c304ddfb9a48d41f33/src/shared/sleep-config.c#L125.

This was added in #25374. Then https://github.com/systemd/systemd/blob/261ee3d5392783bb171419c304ddfb9a48d41f33/src/sleep/sleep.c#L373 cannot set the default value because hibernate_delay_usec is already set to non-zero from above.

**Comment by YHNdnzj** [comment]
`systemd-sleep(5)` documents this as follows:

>  If the system has a battery, then defaults to the estimated timespan until the system battery charge level goes down to 5%. If the system has no battery, then defaults to 2h.

Please confirm that your system has no battery?

**Comment by dlundqvist** [comment]
> `systemd-sleep.conf(5)` documents this as follows:
> 
> > If the system has a battery, then defaults to the estimated timespan until the system battery charge level goes down to 5%. If the system has no battery, then defaults to 2h.
> 
> Please confirm that your system has no battery?

Sorry, I should have clarified that. Correct, it has no battery.

Without `HibernateDelaySec` in `sleep.conf` it never hibernates after suspend.

**Comment by YHNdnzj** [comment]
Could you please try systemd v255? If my analysis is correct, fbc1dbf29 should have fixed the problem.

**Comment by dlundqvist** [comment]
I'm running v255.2 in Debian testing, and it hibernates correctly without HibernateDelaySec configured. Thanks.

**Comment by YHNdnzj** [comment]
Thanks for the confirmation :) Closing.
