### ISSUE TITLE
Support for early/late mounting of disks and partitions

### ISSUE THREAD

**Issue by minfrin** [systemd/systemd#30356]
### Component

systemd

### Is your feature request related to a problem? Please describe

Large disks are high risk - if a problem happens with a system, it is likely to be the largest disk that causes the problem. The most likely problems on large disks are mounts that take too long because reasons, and timeouts that lose patience because reasons.

Large disks are typically mounted at the same time as the smaller system disks, and this introduces a problem - an outage on a large disk takes out the whole box.

In turn, disasters are amplified, because the broken system is now in a state where it hasn't booted, other disks are not available, software that is missing and is useful for troubleshooting isn't installed and cannot be installed because there is no network and no drives on which to install missing software.

### Describe the solution you'd like

I want the option to mount some disks early in the boot process (like now, the fstab), and then mount risky disks late in the boot process.

Crucially, the late disk mounts must not prevent the network from starting, not prevent the box being able to log in, not prevent sshd from working, not prevent software being installed.

Any service depending on a late disk should depend explicitly on that disk.

### Describe alternatives you've considered

Crying. It hasn't worked.

**Comment by dtardon** [comment]
> I want the option to mount some disks early in the boot process (like now, the fstab), and then mount risky disks late in the boot process.

There are at least two options already available:

1. Mark the disk as `noauto` in `fstab` (so it won't be mounted automatically by systemd) and add the relevant mount unit(s) as a dependency to all units that need it.
2. Mark the disk as automount. This is esp. suitable for disks/partitions that are accessed only occasionally.
