### ISSUE TITLE
analyze: systemd-analyze verify does not take unit files in the current working directory

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#30357]
### systemd version the issue has been seen with

255

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

https://github.com/systemd/systemd/pull/30172#issuecomment-1844699620
> This PR triggers a failure in Git's test suite (which has some support for setting up repository maintenance via systemd). It has unit files for several timers (`git-maintenance@hourly.timer`, `git-maintenance@daily.timer`, etc) along with a template service file (`git-maintenance@.service`) and expects to be able to verify per-timer services (e.g. `git-maintenance@hourly.service`) even though no specific unit file exists.
> 
> As a more minimal example, this used to work:
> 
> ```shell
> cat >foo@.service <<-\EOF
> [Service]
> ExecStart=ls
> EOF
> systemd-analyze verify foo@bar.service
> ```
> 
> and would use the `foo@.service` file. But as of [2f6181a](https://github.com/systemd/systemd/commit/2f6181ad4d6c126e3ebf6880ba30b3b0059c6fc8), it yields:
> 
> ```
> Unit foo@bar.service not found.
> ```
> 
> presumably because we break out of `verify_set_unit_path()` after seeing that the literal unit filename does not exist (and then whatever code later resolved the template name does not see that unit path at all).

**Comment by yuwata** [comment]
@peff Fix is waiting in #30363.

**Comment by peff** [comment]
@yuwata Thanks for looking at this so promptly! The fix you have in #30363 looks good to me.
