### ISSUE TITLE
`systemd-nologin.conf` ships with deprecated syntax `F!`

### ISSUE THREAD

**Issue by adelton** [systemd/systemd#30368]
### systemd version the issue has been seen with

systemd-254.5-2.fc39.x86_64

### Used distribution

Fedora 39

### Linux kernel version used

6.5.10-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

In `/usr/lib/tmpfiles.d/systemd-nologin.conf` I see

```
F! /run/nologin 0644 - - - "System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)."
```

I started to read tmpfiles.d(5) to find out what that `F!` means but did not find any documentation there. So what I did not see was systemd shipping configuration which would be documented.

### Unexpected behaviour you saw

I saw undocumented
```
F! /run/nologin 0644 - - - "System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)."
```

### Steps to reproduce the problem

1. `cat /usr/lib/tmpfiles.d/systemd-nologin.conf`
2. `man tmpfiles.d`

**Comment by adelton** [comment]
Checking https://github.com/systemd/systemd/blob/9f7d1899235a237ba7a6000479cbf3965b224fd9/tmpfiles.d/systemd-nologin.conf#L10, this is still present upstream.

Checking https://github.com/systemd/systemd/blob/9f7d1899235a237ba7a6000479cbf3965b224fd9/src/tmpfiles/tmpfiles.c#L90 this is deprecated.

**Comment by YHNdnzj** [comment]
Could you please send a PR?

**Comment by adelton** [comment]
I prefer not to.
