### ISSUE TITLE
NO_CAST.INTEGER_OVERFLOW in src/oom/test-oomd-util.c

### ISSUE THREAD

**Issue by aslepykh** [systemd/systemd#30364]
### systemd version the issue has been seen with

249

### Used distribution

Alt 10

### Linux kernel version used

kernel-5.15.0-52-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd, other

### Unexpected behaviour you saw

The  `.mem_total` variable at _test-oomd-util.c:333_ has `uint64_t` type, therefore, when multiplying the number `20971512` by the number `1024` with the suffix `U`, we will not get the expected result of `21,474,828,288`, since the number `20971512` without an explicit type indication has `uint32_t` type.

First, multiplication will occur in accordance with the `uint32_t` type; this operation will cause a **type overflow**, and only then will this result be assigned to a `uint64_t` type variable.

It's worth adding the `UL` suffix to the number `20971512` to avoid **overflow**.

This are places where this problem occurs:

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L335

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L337

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L338

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L344

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L345

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/oom/test-oomd-util.c#L346

Even though we analyzed version 249, this problem is present in version 255.

Found by Linux Verification Center (portal.linuxtesting.ru) with SVACE.
Author A. Slepykh.

**Comment by evverx** [comment]
> SVACE

I wonder if it's possible to somehow integrate this into CI? For example Coverity provides Coverity Scan with a daily reports like https://scan.coverity.com/projects/350 where all the issues can be viewed. This sort of integration is much more useful than one-off bug reports about issues introduced more than a year ago.
