### ISSUE TITLE
systemd.mount: DirectoryMode not respected when creating the "Where" directory

### ISSUE THREAD

**Issue by osnyx** [systemd/systemd#30376]
### systemd version the issue has been seen with

i0sdqs34r68if9s4sfmpixnnj36npiwj-systemd-254.6

### Used distribution

NixOS 23.11

### Linux kernel version used

6.1.64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

According to man 5 systemd.mount:

>    DirectoryMode=
>        Directories of mount points (and any parent directories) are automatically created if needed. This option specifies the file system access mode used when creating these
>        directories. Takes an access mode in octal notation. Defaults to 0755.

Thus I suspect the mount unit file (see below) to create the `What=` directory `/mnt/testmount` with the permissions `0700` or `drwx------` if it does not already exist.
Whether permissions on existing but empty mount point directories should be adjusted at mount time is another question on its own.

### Unexpected behaviour you saw

```
/mnt/ > ls -la
insgesamt 0
drwxr-xr-x 1 root root   0  8. Dez 00:06 .
drwxr-xr-x 1 root root 166  2. Dez 2021  ..
/mnt/ > systemctl start mnt-testmount.mount          
/mnt/ > ls -la                             
insgesamt 16
drwxr-xr-x 1 root root  18  8. Dez 00:06 .
drwxr-xr-x 1 root root 166  2. Dez 2021  ..
drwxr-xr-x 1 root root  46 29. Okt 2018  testmount
```

### Steps to reproduce the problem

The mount unit I used as a demonstrator is

```
# /etc/systemd/system/mnt-testmount.mount
[Unit]

[Mount]
DirectoryMode=0700
What=/dev/mapper/ssd2
Where=/mnt/testmount
```

generated from the following NixOS config:

```nix
  systemd.mounts = [{
    where = "/mnt/testmount";
    what = "/dev/mapper/ssd2";
    mountConfig = {
      DirectoryMode = "0700";
    };
  }];
```

**Comment by bluca** [comment]
The directory is created with the appropriate permissions, but if the root of the filesystem being mounted has different permissions, then you'll see those. Try to umount it, and you'll see the right settings:

```
# ls -li /tmp | grep img
# systemd-mount -q -p DirectoryMode=0700 /dev/sda1 /tmp/img
# ls -li /tmp | grep img
 1 drwxr-xr-x 4 root root 4096 Jan  1  1970 img
# umount /tmp/img
# ls -li /tmp | grep img
15 drwx------ 2 root root 40 Dec  8 00:22 img
```

**Comment by osnyx** [comment]
@bluca Thanks for clearing up my misconception, you're correct indeed.

Do you deem the knowledge that mounted devices kind of "shadow" the mountpoint directory to be widespread and rather common sense? I wonder whether it makes sense to mention this in the docs/ manpage and would even volunteer to do this.

**Comment by bluca** [comment]
sure feel free to send a PR

**Comment by YHNdnzj** [comment]
> Do you deem the knowledge that mounted devices kind of "shadow" the mountpoint directory to be widespread and rather common sense?

I think this is common sense. It's a mount point after all, and thus the inode is from the fs you mounted.
