### ISSUE TITLE
Unable to use `/dev/net/tun` with `PrivateDevices=true`

### ISSUE THREAD

**Issue by pfactum** [systemd/systemd#30372]
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.0-pf3

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Having a daemon that needs access to `/dev/net/tun`, the following worked prior to systemd v255:

```ini
PrivateDevices=true
BindPaths=/dev/net/tun
DeviceAllow=/dev/net/tun rw
```

### Unexpected behaviour you saw

After an upgrade to systemd v255 the following error is seen after starting the service:

```
Failed to create destination mount point node '/run/systemd/mount-rootfs/dev/net/tun', ignoring: No such file or directory
Failed to mount /dev/net/tun to /run/systemd/mount-rootfs/dev/net/tun: No such file or directory
tinc@pfx.service: Failed to set up mount namespacing: /dev/net/tun: No such file or directory
tinc@pfx.service: Main process exited, code=exited, status=226/NAMESPACE
```

### Steps to reproduce the problem

The following `tinc@.service` is used:

```ini
# /usr/lib/systemd/system/tinc@.service
[Unit]
Description=Tinc net %i
Documentation=info:tinc
Documentation=man:tinc(8) man:tinc.conf(5)
Documentation=http://tinc-vpn.org/docs/
PartOf=tinc.service
ReloadPropagatedFrom=tinc.service

[Service]
DynamicUser=true
User=tinc-%i
Group=tinc-%i
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
PrivateDevices=true
BindPaths=/dev/net/tun
DeviceAllow=/dev/net/tun rw
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=yes
ProtectProc=invisible
ProcSubset=pid
SystemCallArchitectures=native
RestrictRealtime=true
LockPersonality=true
MemoryDenyWriteExecute=true
ProtectHostname=true
SystemCallFilter=@system-service
SystemCallFilter=~@resources @privileged
TasksMax=2
UMask=0066
WorkingDirectory=/var/lib/tinc/%i
ConfigurationDirectory=tinc/%i
RuntimeDirectory=tinc/%i
StateDirectory=tinc/%i
CacheDirectory=tinc/%i
PIDFile=${RUNTIME_DIRECTORY}/pid
LoadCredential=%i:/etc/credstore/tinc/%i
ExecStart=/usr/bin/tincd -D --pidfile=${RUNTIME_DIRECTORY}/pid -n %i -o Ed25519PrivateKeyFile=${CREDENTIALS_DIRECTORY}/%i_ed25519_key.priv -o PrivateKeyFile=${CREDENTIALS_DIRECTORY}/%i_rsa_key.priv -o Interface=tinc-%i
ExecReload=/usr/bin/tinc --pidfile=${RUNTIME_DIRECTORY}/pid -n %i reload
ExecStop=/usr/bin/tinc --pidfile=${RUNTIME_DIRECTORY}/pid -n %i stop
Type=notify
WatchdogSec=10
Restart=on-failure

[Install]
WantedBy=tinc.service
```

### Additional program output to the terminal or log subsystem illustrating the issue

If the `BindPaths=/dev/net/tun` is removed from the `.service` file, the daemon is still unable to use `/dev/net/tun` with the following error:

```
2023-12-07 19:23:02 ERROR   Could not open /dev/net/tun: No such file or directory
```

Please let me know if this is a regression, or such a behaviour change is expected, and if it is expected, please let me know how to approach this.

Thank you.

**Comment by bluca** [comment]
It's a regression disabling PrivateDevices= should work around it for now

**Comment by pfactum** [comment]
Sure, disabling `PrivateDevices=` works around this. Thanks for confirming this to be a regression.

**Comment by bluca** [comment]
I think this is caused by https://github.com/systemd/systemd/pull/29343 as it makes the mount read-only immediately, so we can't add bind mounts. Normally we flip the r/o bits at the end, when everything has been set up. I'll prep a fix and a test.

**Comment by pfactum** [comment]
@bluca @yuwata Thank you for taking care of this! Could you please make sure this reaches `systemd-stable` too?

**Comment by yuwata** [comment]
The PR already has the needs-stable-backport tag, hence it will be backported to the next stable releases.
