### ISSUE TITLE
Suboptimal error message displayed when wrong shebang in a script

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#3038]
Hi,

Let's say I've the following .service file and script:

bigon@valinor:/etc/systemd/system$ cat plop.service 

``` ini
[Unit]
Description=plop

[Service]
ExecStart=/tmp/plop.sh
Type=oneshot
```

The shell script has a bogus shebang:

bigon@valinor:/etc/systemd/system$ cat /tmp/plop.sh 

``` bash
#!/bin/bash42

echo plop
```

When starting the service, systemd displays:

> systemd[10035]: plop.service: Failed at step EXEC spawning /tmp/plop.sh: No such file or directory
> systemd[1]: plop.service: Main process exited, code=exited, status=203/EXEC

The error message make it difficult to understand that it's actually a wrong shebang rather than the script file being missing.

Starting the same script directly from bash, I get the following message and return code:

> bigon@valinor:/etc/systemd/system$ /tmp/plop.sh ; echo $?
> bash: /tmp/plop.sh: /bin/bash42: bad interpreter: No such file or directory
> 126

**Comment by jaromil** [comment]
Involuntarily helping systemd to suck less... anyway, you are welcome! https://twitter.com/jaromil/status/720539448174358529

**Comment by poettering** [comment]
THis is really outside of the scope of systemd. We simply invoke the execve() syscall, and the kernel figures out the rest. It returns ENOENT if the shebang line cannot be resolved, but it will do so in other cases too, for example when the script itself wasn't around either.

The "bad interpretor" message you see in bash is actually code in bash that after getting ENOENT from the kernel then tries to guess the reason by opening the file and looking for a shebang line. It might be useful to do that in a user-facing tool such as bash, but I am pretty sure a similar hack has no place in systemd. After all, it's really second guessing the kernel in a racy way. And even if you ignore the raciness: in times of bimfmt_misc the check in userspace is likely to be simply wrong.

I am open to doing our part in fixing this properly, but that would mean that the kernel actually would return a more precise error code (ENOXEC would be a good candidate) in this case, which we then key a more useful error message off. Hence please ask the kernel people for help, to change the error code in this case, and then we are happy to adapt to that.

I hope this makes sense, and I am sorry if this is disappointing.

**Comment by bigon** [comment]
The ENOENT error is a one size fits all :/

```
ENOENT The file filename or a script or ELF interpreter does not exist, or a shared library needed for file or interpreter cannot be found.
```

**Comment by jaromil** [comment]
ACK. for a (long) moment I thought systemd was substituting itself to the shebang.
I agree `ENOEXEC` would be a good  error code to be returned by the Linux kernel in case of a shell scripts missing the shell interpreter. Yet all shells so far (also ZSh) work around this ambiguity in application space.
