### ISSUE TITLE
boot.mount occasionally times out on boot

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#30386]
### systemd version the issue has been seen with

v255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.4.arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

`boot.mount` automount mounts succesfully

### Unexpected behaviour you saw

`boot..mount` occasionally times out during boot. Debug logs don't say anything useful, just that we've forked off `mount` and after that nothing.

### Steps to reproduce the problem

```
git clone https://github.com/systemd/mkosi
cd mkosi
MKOSI_TEST_DISTRIBUTION=arch pytest tests/test_boot.py::test_boot[disk] -m "integration" -svx --tb=no
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Mounting EFI System Partition Automount...
boot.mount: Mounting timed out. Terminating.
boot.mount: Mount process exited, code=killed, status=15/TERM
boot.mount: Failed with result 'timeout'.
[FAILED] Failed to mount EFI System Partition Automount.
See 'systemctl status boot.mount' for details.
[   96.746717] bootctl[351]: Couldn't find EFI system partition, skipping.
```

**Comment by bluca** [comment]
Reminds me of: https://github.com/systemd/systemd/issues/29682

**Comment by DaanDeMeyer** [comment]
Should be fixed by https://github.com/legionus/kbd/pull/105

**Comment by DaanDeMeyer** [comment]
Fix was merged. If you encounter this and need a quick workaround, add a dropin for systemd-vconsole-setup.service with the following contents:

```
[Service]
WorkingDirectory=/usr/share/empty
```
