### ISSUE TITLE
Selection bug

### ISSUE THREAD

**Issue by Phoking14** [systemd/systemd#30391]
### systemd version the issue has been seen with

255-1

### Used distribution

Endeavor os

### Linux kernel version used

6.1.65-1-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Most recent update on arch made it so it gets stuck on the selection screen that allows you to go into your os or into the firmware interface when turning on the device.

**Comment by YHNdnzj** [comment]
The description contains no valuable information, closing.
