### ISSUE TITLE
systemd.time - Allow range-of-values for time specification in OnCalendar

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#3042]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### RFE: Expected behaviour you didn't see

When using OnCalendar; a range of weekdays can be specified which is useful. However, I would also like to allow ranges in the time specification; to specify working-hours. This is currently not possible, the range-syntax is only allowed for weekdays.

For example, I'd like to specify: `OnCalendar=Mon-Fri 08-18:00/5`. This would execute a timer every five minutes, on working days, at working-hours. This currently results in:

> Failed to parse calendar specification, ignoring: Mon-Fri 08-18:00/5

**Comment by commel** [comment]
I would also love to see this feature. The documentation even says it would work:

> In the date and time specifications, any component may be specified as "*" in which case any value will match. Alternatively, each component can be specified as a list of values separated by commas. Values may also be suffixed with "/" and a repetition value, which indicates that the value and all values plus multiples of the repetition value are matched.

https://www.freedesktop.org/software/systemd/man/systemd.time.html#Parsing%20Timestamps

Current workaround: 
`OnCalendar=Mon-Fri *-*-* 6-23:0/30`
changed to
`OnCalendar=Mon-Fri *-*-* 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23:0/30`
