### ISSUE TITLE
Systemd may hang when outputting serial port logs.

### ISSUE THREAD

**Issue by yantul** [systemd/systemd#30420]
### systemd version the issue has been seen with

246.6

### Linux kernel version used

linux 5.10.67

### CPU architectures issue was seen on

arm

### Component

systemd

### Expected behaviour you didn't see

I cannot use systemctl to view and operate the service. The command will get stuck and a connection timeout will be prompted after a period of time.

### Unexpected behaviour you saw

I am using an ast2600 machine. I can use a cpld to switch the physical serial port to the host or bmc. When I use it, I may encounter a high probability that systemd will hang when the login fails. The specific manifestation is that systemctl cannot be used. , no return, busctl to check bus: org.freedesktop.systemd1 obj: /org/freedesktop/systemd1 intf: org.freedesktop.systemd1.Manager, it is also blocked, but when I used strace to debug, I found that it may be due to When systemd is writing logs to /dev/console, because the serial port is switched away by cpld, systemd cannot complete the writing, and will always be stuck in the writev system call. If it gets stuck, even if it is switched back to BMC, it will still not work.  Unless I execute ctrl-c on the physical serial port or manually execute a getty on the serial port again, it can return to normal.

![image](https://github.com/systemd/systemd/assets/45206781/599599ac-aeac-4db4-9cf9-dc60992b3a79)

In the picture above, on the BMC side, when systemd hung up, I executed systemctl, but when there was no response, I used ctrl-c to cancel the execution of the command. Then I executed ctrl-c on the console of the physical serial port to bring systemd back to normal.

Following debugging, modify as shown below, I modified the file src/core/show-status.c, where /dev/console was opened, and added 'O_NDELAY' to the open flag. After compiling and retesting, I found that the above error no longer appeared. so I want to know, is it necessary to add a non-blocking flag to all places where /dev/console is opened?

![image](https://github.com/systemd/systemd/assets/45206781/4ff43b93-09b3-450d-8fb7-f58e97ce0aec)

### Steps to reproduce the problem

On the bmc side, logging in with an illegal username when the serial port service is started will cause agetty to exit abnormally, such as "-". When exiting, use the relevant command to write cpld to switch the serial port to the host, and then switch to the BMC. Repeat the above steps.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
/dev/console is blocked and does not output anything.
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
