### ISSUE TITLE
LUKS unlocking with keyfile during gpt-automount broken

### ISSUE THREAD

**Issue by jhvoigts** [systemd/systemd#30425]
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.5-arch1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup, systemd-gpt-auto-generator

### Expected behaviour you didn't see

After entering my password for the LUKS encrypted root-partition, gpt-automount detects the encrypted SWAP and home-partition and tries to decrypts them. systemd-cryptsetup then automatically finds the keyfiles for my SWAP and home-partition in /etc/cryptsetup-keys.d and unlocks those partitions, without needing entries in the fstab or crypttab.

### Unexpected behaviour you saw

After entering my password for the root-partition, systemd asks for passwords for the SWAP partition and the home-partition, without considering the keyfiles. I have to fail the prompt to be able to login into an emergency shell.
[debug.log](https://github.com/systemd/systemd/files/13636390/debug.log)

### Steps to reproduce the problem

- Use systemd v255
- Setup a separate partition for /home or SWAP with LUKS encryption using keyfiles in /etc/cryptsetup-keys.d
- Rely on gpt-automount to decrypt and mount the partitions together by having empty fstab and crypttab

**Comment by SoapGentoo** [comment]
I can confirm this problem for manually entered passphrases too: on my laptop, I have both the swap and root encrypted with the same passphrase, yet need to enter it twice, in the case of swap at a very late stage, after root switching. On my TPM2 based Ryzen, unlocking the swap and root with the TPM2 happens in one go and works fine.

**Comment by joedavid0** [comment]
Ping @poettering

**Comment by YHNdnzj** [comment]
@poettering Could you take a look? I think this should be resolved before v256-final.

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/33183 fixes it for me

**Comment by poettering** [comment]
@joedavid0 any chance you can check if #33197 fixes this for you?

**Comment by SoapGentoo** [comment]
let me check it quickly
