### ISSUE TITLE
RFE: Variation on lexicographic order sorting of conf files

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#30439]
### Component

systemd

### Is your feature request related to a problem? Please describe

Distributions will ship config files in /usr/lib/ with some arbitrary file name. In this case we're concerned about a theoretical `/usr/lib/sysctl.d/50-foo.conf` with `vm.swappiness=60`. But on the sysadmin side we had `/etc/sysctl.d/10-bar.conf` with `vm.swappiness=0`. As documented, the distribution value will be applied because it is lexicographically later.

Although we can override it with the same file name in `/etc`, this can easily go unnoticed and cause issues. And there's nothing stopping a package that decides to ship a config named `zzz.conf` and being really problematic.

### Describe the solution you'd like

2 ideas (ideally both are implemented):

- A system-wide knob that makes it so that configs are sorted lexicographically within their directory and options are resolved per directory. Then the final value of the options follow the `/usr/lib/`, `/usr/local/lib/`, `/run`, `/etc` order of precedence.
  - So in the previous example, `vm.swappiness=0` would be set because that was the value in `/etc`, overriding the value in `/usr/lib/` even though under the current model `/usr/lib/sysctl.d/50-foo.conf` is lexicographically later.
- We document that vendors should keep their file names prefixed with `50-` and below (number range TBD). Then sysadmins can expect that `51-` and above is a safe enough range such that their configs will take precedence.

### Describe alternatives you've considered

The two solutions suggested are what I've considered.

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by YHNdnzj** [comment]
I think the second choice is the way to go, i.e. beef up the documentation. Having a flag that changes the whole conf-parser behavior is kinda hard to track and potentially creates more problems for casual users and debugging.
