### ISSUE TITLE
Teach systemd-udevd to support dropin files for `udev.conf`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#30460]
Currently `udev.conf` doesn't support dropins, which seems to be an annoying exception compared to our other stuff. It would be nice if the behavior was consistent, even though this particular config file has only a couple of lines.

Originally mentioned in https://github.com/systemd/systemd/pull/30387#issue-2033069437.

**Comment by poettering** [comment]
Duplicate of #19488 btw
