### ISSUE TITLE
loader.conf not applied unless pressing and holding a key before systemd-boot is launched, regardless of timeout, and default @saved not working

### ISSUE THREAD

**Issue by digitalsignalperson** [systemd/systemd#30471]
### systemd version the issue has been seen with

255-1

### Used distribution

arch linux

### Linux kernel version used

6.6.5.16.realtime1-1-rt

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

In all configs with `default @saved` after booting there is a /sys/firmware/efi/efivars/LoaderEntryLastBooted*

with /efi/loader/entries/loader.conf set to 
```
default @saved
console-mode max
```
(timeout default is 0)

expected behaviour
- when not holding a key down during initialization:
    - don't show a menu
    - immediately boot the last booted entry
    - show the splash screen at high resolution
- when holding a key down during initializtion:
    - show the boot menu in high resolution
    - the last booted entry is selected
    - press enter and the splashscreen of the entry is shown at high resolution

with /efi/loader/entries/loader.conf set to 
```
default @saved
timeout 1
console-mode max
```
expected behaviour
- see the menu for 1 second with the last booted entry highlighted
- after 1 second show the splash screen of booted entry at high resolution

### Unexpected behaviour you saw

In all configs with `default @saved` after booting ~~there is a /sys/firmware/efi/efivars/LoaderEntryLastBooted*~~ there is not a /sys/firmware/efi/efivars/LoaderEntryLastBooted* variable saved

with /efi/loader/entries/loader.conf set to 
```
default @saved
console-mode max
```

observed behaviour:
- when not holding a key down during initialization:
    - ✔️ don't show a menu
    - ❌~~immediately boot the last booted entry~~ what would be the top entry by the sort order is booted immediately
    - ❌~~show the splash screen at high resolution~~ the splash screen is shown at low resolution
- when holding a key down during initialization:
    - ✔️ show the boot menu in high resolution
    - ❌~~the last booted entry is selected~~ the topmost entry is selected
    - ✔️ press enter and the splashscreen of the entry is shown at high resolution

with /efi/loader/entries/loader.conf set to 
```
default @saved
timeout 1
console-mode max
```
observed behaviour
- ❌~~see the menu for 1 second with the last booted entry highlighted~~ immediately boots the top entry by the sort order
- ❌show the splash screen of booted entry at ~~high resolution~~ low resolution

### Steps to reproduce the problem

- Secureboot is enabled
- fastboot is disabled
- no default entry is set (e.g. with "d" key)

The /efi filesystem contains only these files:
- /efi/EFI/BOOT contains
    - loader.EFI (/usr/lib/systemd/boot/efi/systemd-bootx64.efi)
    - bootx64.efi ([signed PreLoader.efi](https://blog.hansenpartnership.com/wp-uploads/2013/PreLoader.efi))
    - HashTool.efi ([signed](https://blog.hansenpartnership.com/wp-uploads/2013/HashTool.efi))
- /efi/EFI/Linux only contains UKI .efi binaries generated by ukify
- /efi/loader/entries/ contains the loader.conf with contents as described in the expected behaviour section
- /efi/shellx64.efi

For another data point: when there is no loader.conf, the menu and splash screens are always low resolution, as expected.

**Comment by YHNdnzj** [comment]
Please check for `LoaderEntryDefault`, `LoaderConfigTimeout` and `LoaderConfigConsoleMode` EFI variables. They have higher precedence than what's set in `loader.conf`.

**Comment by digitalsignalperson** [comment]
> with /efi/loader/entries/loader.conf set to

Oops somehow I was using this instead of /efi/loader/loader.conf. User error. Thanks for the suggestions it helped me narrow it down.
