### ISSUE TITLE
TEST-26-SYSTEMCTL: /etc/init.d/issue-24990: No such file or directory

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#30478]
The upstream test TEST-26-SYSTEMCTL fails on Debian sid with the following error message:
```
[  232.358850] testsuite-26.sh[49]: + [[ -x /usr/lib/systemd/system-generators/systemd-sysv-generator ]]
[  232.358850] testsuite-26.sh[49]: + [[ -d /etc/rc.d/init.d ]]
[  232.359286] testsuite-26.sh[49]: + SYSVINIT_PATH=/etc/init.d
[  232.359286] testsuite-26.sh[49]: + cat
[  232.359637] testsuite-26.sh[891]: /usr/lib/systemd/tests/testdata/units/testsuite-26.sh: line 352: /etc/init.d/issue-24990: No such file or directory
[  232.360558] testsuite-26.sh[49]: + at_exit
[  232.360558] testsuite-26.sh[49]: + [[ -v UNIT_NAME ]]
[  232.360558] testsuite-26.sh[49]: + [[ -e /usr/lib/systemd/system/systemctl-test-21942.service ]]
[  232.360558] testsuite-26.sh[49]: + rm -fvr /usr/lib/systemd/system/systemctl-test-21942.service /etc/systemd/system/systemctl-test-21942.service.d +4
[  232.361816] testsuite-26.sh[892]: removed '/usr/lib/systemd/system/systemctl-test-21942.service'
[  232.362500] testsuite-26.sh[49]: + rm -f /etc/init.d/issue-24990
[  232.363777] testsuite-26.sh[49]: + return 0
[  232.365215] systemd[1]: testsuite-26.service: Failed with result 'exit-code'.
[  232.365615] systemd[1]: Failed to start testsuite-26.service.
Spawning getter /bin/journalctl -o export -D /var/tmp/systemd-tests/systemd-test.MRA9Jp/root/var/log/journal...
Finishing after writing 25813 entries
TEST-26-SYSTEMCTL: (failed; see logs)
-rw-r----- 1 root root 25165824 Dec 14 11:28 /tmp/autopkgtest.z1zmo3/upstream-artifacts/TEST-26-SYSTEMCTL.journal
nspawn-root test failed
make: *** [Makefile:4: run] Error 1
make: Leaving directory '/tmp/autopkgtest.z1zmo3/build.Qm4/real-tree/test/TEST-26-SYSTEMCTL'
[11:28:03] --x-- Result of TEST-26-SYSTEMCTL: 2 --x--

TEST-26-SYSTEMCTL:                  FAIL     ( 91 s)
```
Full log attached.
[log.txt](https://github.com/systemd/systemd/files/13672705/log.txt)

**Comment by mbiebl** [comment]
It appears there is neither a `/etc/rc.d/init.d/` nor `/etc/init.d/` in the assembled image, so the cat invocation fails.
A simple
```
+    [ -d $SYSVINIT_PATH ] || mkdir -p $SYSVINIT_PATH
```
fixes that.
But I guess this somehow defeats the point as we actually use that directory to determine where to put the init script.

I suspect this directory should be copied from the host file system into the image instead.

**Comment by mbiebl** [comment]
btw, I'm a bit surprised, this doesn't fail on ubuntu-ci

**Comment by mrc0mmand** [comment]
> It appears there is neither a `/etc/rc.d/init.d/` nor `/etc/init.d/` in the assembled image, so the cat invocation fails. A simple
> 
> ```
> +    [ -d $SYSVINIT_PATH ] || mkdir -p $SYSVINIT_PATH
> ```
> 
> fixes that. But I guess this somehow defeats the point as we actually use that directory to determine where to put the init script.
> 
> I suspect this directory should be copied from the host file system into the image instead.

Yup, I already have a fix, will post a PR once I finish a couple of other test-related things as well.
