### ISSUE TITLE
systemd-networkd does not report all used files in debug log

### ISSUE THREAD

**Issue by fluchtkapsel** [systemd/systemd#30483]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.66-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

After `systemctl edit systemd-netword.service` and putting
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
in the override file, systemd-networkd does not report loading of drop-in files. FWIW, systemd-networkd doesn't report that without log level set to debug.

### Unexpected behaviour you saw

No mention of drop-in files loaded.

### Steps to reproduce the problem

1. Create a drop-in file for a network in `/etc/systemd/network/<network_file_name>.d/`
2. Increase debug level according to section "Expected behaviour you didn't see"
3. `systemctl restart systemd-networkd.service`

**Comment by MasinAD** [comment]
I also checked with Arch Linux, systemd 255

**Comment by yuwata** [comment]
Waiting in #30544.
