### ISSUE TITLE
systemctl incorrectly reports propagated stateful resource limits

### ISSUE THREAD

**Issue by ATLief** [systemd/systemd#30499]
### systemd version the issue has been seen with

255-1

### Used distribution

Debian 13 (Testing)

### Linux kernel version used

6.6.6-1

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

After creating nested units/cgroups, `systemctl status` should report the effective cgroup resource limits (TasksMax, MemoryMax, MemoryMin, MemoryLow, and MemoryHigh) on child units.

### Unexpected behaviour you saw

If the child unit specifies TasksMax=infinity and MemoryMax=infinity (explicitly or by default), `systemctl status` does not report these maximums or remaining available resources. If the child unit specifies TasksMax=100% and MemoryMax=100%, `systemctl status` incorrectly reports percentages of the global resource limits rather than percentages of the resource limits on its parent Slice. In both cases, MemoryMin, MemoryLow, and MemoryHigh are not displayed on child units.

Despite the incorrect reporting, cgroup limits are still propagated and enforced as expected. I'm not sure whether these incorrect stats change how systemd distributes resources, however.

### Steps to reproduce the problem

1. Create a Slice, Scope, or Service
2. Create a Slice, Scope, or Service within the first unit
3. Specify stateful resource limits on the parent unit
4. Add various stateful resource limits directly to the child
5. View the reported stateful resource limits on the child via `systemctl status`

These are the files I used for the example, but make sure to remove the txt extension:
[kitty.slice.txt](https://github.com/systemd/systemd/files/13691395/kitty.slice.txt) [kitty-cat.slice.txt](https://github.com/systemd/systemd/files/13691394/kitty-cat.slice.txt)

This issue is also present in v252 and v254, but I also replicated it on v255. I haven't tested v253.

Most testing was done with the boot arguments "cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1", but this problem also exists without them.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
TasksMax=100%, MemoryMax=100%:

● kitty.slice - Slice /kitty
     Loaded: loaded (/etc/systemd/system/kitty.slice; static)
     Active: active since Fri 2023-12-15 22:55:12 EST; 58s ago
      Tasks: 1 (limit: 114263)
     Memory: 464.0K (min: 1.5G low: 3.1G high: 12.4G max: 13.9G available: 12.4G peak: 1.7M)
        CPU: 5ms
     CGroup: /kitty.slice
             └─kitty-cat.slice
               └─run-r90891f12ca5645be96789f10874e5e04.service
                 └─202 /usr/bin/sleep 1000

Dec 15 22:55:12 bootstrap systemd[1]: Created slice kitty.slice - Slice /kitty.

● kitty-cat.slice - Slice /kitty/cat
     Loaded: loaded (/etc/systemd/system/kitty-cat.slice; static)
     Active: active since Fri 2023-12-15 22:55:12 EST; 58s ago
      Tasks: 1 (limit: 126959)
     Memory: 252.0K (max: 15.5G available: 12.4G peak: 1.5M)
        CPU: 5ms
     CGroup: /kitty.slice/kitty-cat.slice
             └─run-r90891f12ca5645be96789f10874e5e04.service
               └─202 /usr/bin/sleep 1000

Dec 15 22:55:12 bootstrap systemd[1]: Created slice kitty-cat.slice - Slice /kitty/cat.

TasksMax=infinity, MemoryMax=infinity:

● kitty.slice - Slice /kitty
     Loaded: loaded (/etc/systemd/system/kitty.slice; static)
     Active: active since Fri 2023-12-15 22:50:34 EST; 2min 56s ago
      Tasks: 1 (limit: 114263)
     Memory: 368.0K (min: 1.5G low: 3.1G high: 12.4G max: 13.9G available: 12.4G peak: 704.0K)
        CPU: 1ms
     CGroup: /kitty.slice
             └─kitty-cat.slice
               └─run-r90891f12ca5645be96789f10874e5e04.service
                 └─164 /usr/bin/sleep 1000

Dec 15 22:50:34 bootstrap systemd[1]: Created slice kitty.slice - Slice /kitty.

● kitty-cat.slice - Slice /kitty/cat
     Loaded: loaded (/etc/systemd/system/kitty-cat.slice; static)
     Active: active since Fri 2023-12-15 22:50:34 EST; 2min 56s ago
      Tasks: 1 
     Memory: 304.0K (peak: 640.0K)
        CPU: 1ms
     CGroup: /kitty.slice/kitty-cat.slice
             └─run-r90891f12ca5645be96789f10874e5e04.service
               └─164 /usr/bin/sleep 1000

Dec 15 22:50:34 bootstrap systemd[1]: Created slice kitty-cat.slice - Slice /kitty/cat.
```

**Comment by Werkov** [comment]
@ATLief, thanks for reporting. I believe this will be covered by https://github.com/systemd/systemd/pull/28797. Please comment there, if you have any extra wishes.

**Comment by Werkov** [comment]
Percentages are by design relative to the system (not a parent).
