### ISSUE TITLE
pass service env vars to PAM session hooks when using PAMName=

### ISSUE THREAD

**Issue by joukewitteveen** [systemd/systemd#3050]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229, but probably present for a few years already

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Some PAM modules, notably pam_systemd, are sensitive to environment variables. I would expect variables specified using Environment= in units that use PAMName=/User= to be available to the PAM module being loaded.
### In case of bug report: Unexpected behaviour you saw

> Currently, systemd does not set the variables specified in Environment= before calling pam_start in src/core/execute.c:setup_pam. As a result it is not possible to influence the behavior of PAM modules through environment variables.
### In case of bug report: Steps to reproduce the problem

> I considered adding `Environment=XDG_SESSION_TYPE=x11` to [xlogin](https://github.com/joukewitteveen/xlogin/blob/master/xlogin%40.service.in) so that `logind` would get to know the proper session type. However, `loginctl` shows the default session type ("tty").

**Comment by poettering** [comment]
Yeah, I figure PID 1 should indeed pass the env vars configured for a service to the PAM session hooks.
