### ISSUE TITLE
networkd: Interface stuck in configuring state with DHCPv6-PD and `UplinkInterface=:self`

### ISSUE THREAD

**Issue by Majiir** [systemd/systemd#30502]
### systemd version the issue has been seen with

254.6

### Used distribution

NixOS 23.11

### Linux kernel version used

6.1.51

### CPU architectures issue was seen on

x86_64, aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

When requesting a prefix with IPv6 Prefix Delegation and `UplinkInterface=:self`, the WAN interface should enter the `routable (configured)` state after receiving a prefix.

### Unexpected behaviour you saw

After 195b83edf852f4e40e0d3a3b630cde97c84d77ba, the WAN interface remains in a `routable (configuring)` state indefinitely. Addresses are successfully configured on all interfaces as usual, but the state never transitions to `configured`.

### Steps to reproduce the problem

I discovered the issue on an `aarch64` host acting as a residential router. I reproduced in an `x86_64` VM and bisected the issue to 195b83edf852f4e40e0d3a3b630cde97c84d77ba. This is the configuration in the VM:

```
[Match]
Name=eth1

[Link]
RequiredForOnline=routable

[Network]
DHCP=ipv6
DHCPPrefixDelegation=true
IPv6AcceptRA=true
IPv6SendRA=false

[DHCPv6]
PrefixDelegationHint=::/48

[DHCPPrefixDelegation]
Announce=false
UplinkInterface=:self
```

The `aarch64` router additionally configures an address with DHCPv4 and otherwise has a similar config.

### Additional program output to the terminal or log subsystem illustrating the issue

[`systemd-networkd` log](https://gist.githubusercontent.com/Majiir/8de6724fddd7f826a28ab65097e7641d/raw/904ba309ad54940d479755d666e8daeb66fa66f3/networkd.log)

**Comment by Majiir** [comment]
@yuwata I think this was introduced in https://github.com/systemd/systemd/pull/27826. Let me know if any more details would help. Thanks!

**Comment by yuwata** [comment]
Interesting:
```
Dec 16 16:00:37 router systemd-networkd[485]: eth1: Configuring DHCPv6 address (requesting): 2001:db8::/128 (valid for 1h 59min 59s, preferred for 1h 14min 59s), flags: tentative,no-prefixroute, scope: global
Dec 16 16:00:37 router systemd-networkd[485]: eth1: Configuring DHCP-PD address (requesting): 2001:db8:1000:0:5054:ff:fe12:103/64 (valid for 1h 59min 59s, preferred for 1h 14min 59s), flags: tentative,manage-temporary-address, scope: global
Dec 16 16:00:37 router systemd-networkd[485]: eth1: Received updated DHCPv6 address (configured): 2001:db8::/128 (valid for 1h 59min 59s, preferred for 1h 14min 59s), flags: tentative,no-prefixroute, scope: global
Dec 16 16:00:37 router systemd-networkd[485]: eth1: Received updated DHCP-PD address (configured): 2001:db8:1000:0:5054:ff:fe12:103/64 (valid for 1h 59min 59s, preferred for 1h 14min 59s), flags: tentative,manage-temporary-address, scope: global
Dec 16 16:00:38 router systemd-networkd[485]: eth1: Forgetting DHCPv6 address (n/a): 2001:db8::/128 (valid for 1h 59min 59s, preferred for 1h 14min 59s), flags: tentative,no-prefixroute, scope: global
Dec 16 16:00:38 router systemd-networkd[485]: eth1: Received updated DHCP-PD address (configured): 2001:db8:1000:0:5054:ff:fe12:103/64 (valid for 1h 59min 58s, preferred for 1h 14min 58s), flags: manage-temporary-address, scope: global
Dec 16 16:00:38 router systemd-networkd[485]: eth1: DHCP-PD addresses and routes set.
Dec 16 16:00:38 router systemd-networkd[485]: eth1: link_check_ready(): DHCPv6 IA_PD prefix is assigned, but DHCPv6 protocol is not finished yet.
```

**Comment by yuwata** [comment]
So, I guess, the provided address conflicts in the upstream network.
Maybe, adding the following in the .network file should work:
```
[DHCPv6]
UseAddress=no
```

**Comment by Majiir** [comment]
I tried `UseAddress=no` and the issue still occurs. I tested on both my VM and my actual router. Updated networkd log is [here](https://gist.githubusercontent.com/Majiir/61d6c484b2bc32e073447b5fe611b9c4/raw/ae04c81f44a7e0f92480446789a2101dd52729bb/networkd.log.2). It's no longer logging about forgetting an address, but still hitting the `link_check_ready()` check and failing to transition out of configuring.

**Comment by yuwata** [comment]
Do you really set the option to 01-eth1.network ?? Now, eth2 works fine.

**Comment by yuwata** [comment]
Ah, should be already fixed by fc4aa64c2d7bf1443bf30b66d334e33addb0d27a (#29981).

**Comment by yuwata** [comment]
The commit is already backported to v254-stable https://github.com/systemd/systemd-stable/commit/24be2b51246af4db1a57ce6d2c8c7f96bf2f8178 (v254.7).

**Comment by yuwata** [comment]
So, please test v254.7 or newer.

**Comment by Majiir** [comment]
> Do you really set the option to 01-eth1.network ??

Yes, it was set on `eth1`.

> Ah, should be already fixed by https://github.com/systemd/systemd/commit/fc4aa64c2d7bf1443bf30b66d334e33addb0d27a (https://github.com/systemd/systemd/pull/29981).

> So, please test v254.7 or newer.

Using both v254.7 and setting `UseAddress=no`, the issue is resolved. Thanks for your help. I'll be sure to test on `master` next time.

**Comment by yuwata** [comment]
No problem. Thank you for the confirmation.
