### ISSUE TITLE
systemd-backlight: No way to clamp min brightness for leds class

### ISSUE THREAD

**Issue by jekhor** [systemd/systemd#30507]
### systemd version the issue has been seen with

255

### Used distribution

Debian sid

### Linux kernel version used

any

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Clamping of minimal brightness for any led if ID_BACKLIGHT_CLAMP is defined for it. I have a sensor keyboard with LED backlight, for example.

### Unexpected behaviour you saw

ID_BACKLIGHT_CLAMP works only for backlight subsystem, not for leds.

This logic is hardcoded in clamp_brightness():
```
       if (streq(subsystem, "backlight"))
                min_brightness = MAX(1U, (unsigned) ((double) max_brightness * percent / 100));
        else
                min_brightness = 0;
```

### Steps to reproduce the problem

1. Add udev rule for any led and set ID_BACKLIGHT_CLAMP=20% and apply it (by reboot for example)
2. Set the led brightness to 0
3. Call systemd-backlight save _dev_
4. Call systemd-backlight load _dev_
5. Brightness will be set to 0, not to 20% of max_brightness

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# udevadm info /sys/devices/platform/PNP0C14\:03/wmi_bus/wmi_bus-PNP0C14\:03/243FEC1D-1963-41C1-8100-06A9D82A94B4/leds/ybwmi\:\:kbd_backlight
P: /devices/platform/PNP0C14:03/wmi_bus/wmi_bus-PNP0C14:03/243FEC1D-1963-41C1-8100-06A9D82A94B4/leds/ybwmi::kbd_backlight
M: ybwmi::kbd_backlight
U: leds
E: DEVPATH=/devices/platform/PNP0C14:03/wmi_bus/wmi_bus-PNP0C14:03/243FEC1D-1963-41C1-8100-06A9D82A94B4/leds/ybwmi::kbd_backlight
E: SUBSYSTEM=leds
E: USEC_INITIALIZED=10572284
E: ID_BACKLIGHT_CLAMP=20%
E: ID_PATH=platform-PNP0C14:03
E: ID_PATH_TAG=platform-PNP0C14_03
E: ID_FOR_SEAT=leds-platform-PNP0C14_03
E: SYSTEMD_WANTS=systemd-backlight@leds:ybwmi::kbd_backlight.service
E: TAGS=:systemd:seat:
E: CURRENT_TAGS=:systemd:seat:


# SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-backlight load leds:ybwmi::kbd_backlight
ybwmi::kbd_backlight: Maximum brightness is 255
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Using saved brightness 0.
```

**Comment by jekhor** [comment]
Related to #29328

**Comment by yuwata** [comment]
-> #30562.
