### ISSUE TITLE
After root partition switch over, 2 servers out of 25 had failed PCIe interface

### ISSUE THREAD

**Issue by geotransformer** [systemd/systemd#30533]
### systemd version the issue has been seen with

 245 (245.4-4ubuntu3.22)

### Used distribution

ubunu 20.04

### Linux kernel version used

5.4.0-163-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Unexpected behaviour you saw

ifconfig did not show the PCIE interface and interface showed failed. Reboot the server fixed the issue

server-8:~$ sudo networkctl
IDX LINK            TYPE     OPERATIONAL SETUP     
  1 lo              loopback carrier     unmanaged 
  2 eno5            ether    enslaved    configured
  3 eno6            ether    enslaved    configured
  4 enp94s0f0       ether    off         failed    
  5 enp94s0f1       ether    off         failed    
  6 enp216s0f0      ether    off         failed    
  7 enp216s0f1      ether    off         failed    
  8 eno1            ether    degraded    configured
  9 eno2            ether    off         unmanaged 

server-8:~$ sudo  ethtool enp94s0f0
Settings for enp94s0f0:
        Supported ports: [ FIBRE ]
        Supported link modes:   40000baseCR4/Full 
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  40000baseCR4/Full 
        Advertised pause frame use: No
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: 40000Mb/s
        Duplex: Full
        Port: Direct Attach Copper
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: on
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x0000000f (15)
                               drv probe link timer
        Link detected: no
 

### Steps to reproduce the problem

Netplan

server-8:~$ cat /etc/netplan/cloud-init.yaml 
# network: {config: disabled}
network:
    bonds:
        bd0:
            dhcp4: false
            dhcp6: false
            interfaces:
            - eno5
            - eno6
            optional: true
            parameters:
                fail-over-mac-policy: active
                mii-monitor-interval: '100'
                mode: active-backup
    ethernets:
        eno1:
            dhcp4: false
            dhcp6: false
        eno5:
            dhcp4: false
            dhcp6: false
        eno6:
            dhcp4: false
            dhcp6: false
    version: 2

server-8:~$ cat /etc/netplan/netplan-additions.yaml 
network:
  bonds:
    bd1:
      dhcp4: false
      dhcp6: false
      interfaces: [enp216s0f1, enp94s0f0]
      optional: true
      parameters: {fail-over-mac-policy: active, mii-monitor-interval: '100', mode: active-backup}
    bd2:
      dhcp4: false
      dhcp6: false
      interfaces: [enp216s0f0, enp94s0f1]
      optional: true
      parameters: {fail-over-mac-policy: active, mii-monitor-interval: '100', mode: active-backup}
  ethernets:
    enp216s0f0: {dhcp4: false, dhcp6: false}
    enp216s0f1: {dhcp4: false, dhcp6: false}
    enp94s0f0: {dhcp4: false, dhcp6: false}
    enp94s0f1: {dhcp4: false, dhcp6: false}
  version: 2

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Some journal and systemd logs

Dec 14 09:28:55 server-8 kernel: i40e 0000:5e:00.1: failed to get phy cap., ret =  I40E_ERR_ADMIN_QUEUE_TIMEOUT last_status =  OK
Dec 14 09:28:55 server-8 kernel: bd2: (slave enp94s0f1): Opening slave failed
Dec 14 09:28:55 server-8 kernel: i40e 0000:5e:00.0: failed to get phy cap., ret =  I40E_ERR_ADMIN_QUEUE_TIMEOUT last_status =  OK
Dec 14 09:28:55 server-8 kernel: bd1: (slave enp94s0f0): Opening slave failed
Dec 14 09:28:55 server-8 kernel: enic 0000:1d:00.1 eno6: vNIC resources used: wq 1 rq 4 cq 5 qp 4 intr 6 rq_desc 512 wq_desc 256 intr mode MSI-X
Dec 14 09:28:55 server-8 kernel: enic 0000:1d:00.1 eno6: Link UP
Dec 14 09:28:55 server-8 kernel: enic: 0000:1d:00.1:Timed out devcmd 36
Dec 14 09:28:55 server-8 kernel: bd0: (slave eno6): making interface the new active one
Dec 14 09:28:55 server-8 kernel: bd0: (slave eno6): Enslaving as an active interface with an up link
Dec 14 09:28:55 server-8 kernel: enic 0000:1d:00.0 eno5: vNIC resources used: wq 1 rq 4 cq 5 qp 4 intr 6 rq_desc 512 wq_desc 256 intr mode MSI-X
Dec 14 09:28:55 server-8 kernel: enic 0000:1d:00.0 eno5: Link UP

Dec 14 09:28:55 server-8 kernel: bd0: (slave eno5): Enslaving as a backup interface with an up link
Dec 14 09:28:55 server-8 kernel: 8021q: adding VLAN 0 to HW filter on device bd2

Dec 14 09:28:55 server-8 systemd-networkd[1348]: eno1: Link UP
Dec 14 09:28:55 server-8 kernel: 8021q: adding VLAN 0 to HW filter on device bd1
Dec 14 09:28:55 server-8 kernel: 8021q: adding VLAN 0 to HW filter on device bd0
Dec 14 09:28:55 server-8 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): bd0: link becomes ready
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp216s0f1: Could not join netdev: Device or resource busy
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp216s0f1: Failed
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp216s0f0: Could not join netdev: Resource temporarily unavailable
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp216s0f0: Failed
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp94s0f1: Could not join netdev: Resource temporarily unavailable
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp94s0f1: Failed
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp94s0f0: Could not join netdev: Resource temporarily unavailable
Dec 14 09:28:55 server-8 systemd-networkd[1348]: enp94s0f0: Failed
Dec 14 09:28:55 server-8 systemd-networkd[1348]: eno6: Link UP
Dec 14 09:28:55 server-8 systemd-networkd[1348]: eno5: Link UP
```

**Comment by yuwata** [comment]
Please provide relevant .network and .netdev files, rather than netplan config.

**Comment by yuwata** [comment]
Hmm... v245 is too old here. Please test v254 or newer, or contact to your downstream.
