### ISSUE TITLE
systemd-npsawn: containers running out of memory

### ISSUE THREAD

**Issue by Kentoseth** [systemd/systemd#30540]
### systemd version the issue has been seen with

254

### Used distribution

Manjaro Stable

### Linux kernel version used

6.6.5-3-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

Containers wouldn't run out of memory and just scale as LXC containers do.

### Unexpected behaviour you saw

Containers run out of memory when installing NLP or other large Python packages.

### Steps to reproduce the problem

Create a standard Ubuntu container:

`sudo debootstrap --include=systemd-container --components=main,universe,multiverse jammy /var/lib/machines/ubuntu http://archive.ubuntu.com/ubuntu/`

Start the container:

`sudo systemd-nspawn -b --bind-ro=/etc/resolv.conf --bind=/dev/dri --bind=/dev/shm -D /var/lib/machines/ubuntu`

```bash
apt install python3-pip python3-venv

mkdir test/
cd test/

python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip

pip install stanza
```

Any reasonably large Python package will do. This has happened for any scenario where large packages and/or large datasets associated with said packages are downloaded.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# output when installing

Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 644.8/670.2 MB
ERROR: Exception:
Traceback (most recent call last):
  File "/root/ubuntu/stanza/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/root/ubuntu/stanza/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/root/ubuntu/stanza/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/root/ubuntu/stanza/.venv/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 102, in read
    self.__buf.write(data)
  File "/usr/lib/python3.10/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 28] No space left on device

---

# output of df

du -sh /var/lib/machines/ubuntu
2.7G    /var/lib/machines/ubuntu

# output of df -h shows no folders with >50% usage
```

**Comment by YHNdnzj** [comment]
Please check if your `/tmp/` is on `tmpfs`. If so, try monitoring its usage while installing `python` packages.

**Comment by Kentoseth** [comment]
> Please check if your container's `/tmp/` is on `tmpfs`. If so, try monitoring its usage while installing `python` packages.
> 
> Note that in `systemd-nspawn` we mount that by default, with the size being `10%` of your total memory.

Can you indicate how to do this? 

This problem was so niche that I could not even find ways to debug accurately (Docker results kept coming up).

**Comment by Kentoseth** [comment]
Okay I figured it out and the /tmp is indeed running out of memory.

For those who don't know how to check, do this:

From the host, connect to the existing container a 2nd time: `sudo machinectl shell <container>`

Check if the /tmp is a `tmpfs` (in the container) by running: `df -T /tmp`

I attempted to install stanza again and I monitored using `df -T /tmp` getting the final result:

```
df -T /tmp
Filesystem     Type  1K-blocks    Used Available Use% Mounted on
tmpfs          tmpfs   2397432 2328788     68644  98% /tmp
```

So how do I increase the size of /tmp ?

**Comment by poettering** [comment]
This seems like a bug in python. They should not put massive data in /tmp/, but in /var/tmp/, which is backed by a real disk.

**Comment by Kentoseth** [comment]
> This seems like a bug in python. They should not put massive data in /tmp/, but in /var/tmp/, which is backed by a real disk.

Thanks, I'll report upstream.
