### ISSUE TITLE
systemd-networkd: Allow independent bridges

### ISSUE THREAD

**Issue by jpds** [systemd/systemd#30554]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

`networkd` does not support creating bridges that do not have an enslaved Ethernet interface. `Independent=` seems to exist for VXLAN and other types.

I require this to set up a virtual machine network on a range that's routed to my hypervisor by my network provider, as is shown in this diagram: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/configuring-virtual-machine-network-connections_configuring-and-managing-virtualization#virtual-networking-routed-mode_types-of-virtual-machine-network-connections

It can also be useful if two virtual machines need to be able to privately communicate to each other.

**Comment by yuwata** [comment]
Bridge is not a stacked interface, but a master interface. So the requested setup should be supported for long time. Please try at first.

**Comment by jpds** [comment]
Just a quick follow-up that I was indeed able to make this work in the end.
