### ISSUE TITLE
Luks2 swap partition after hibernation gets stuck on dev by uuid with no limit

### ISSUE THREAD

**Issue by TheSoultrigger** [systemd/systemd#30557]
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.7-arch1-1 

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup, systemd-gpt-auto-generator

### Expected behaviour you didn't see

On systemd up to release 254 my system would unlock all partitions with the passphrase supplied in early initramfs.

### Unexpected behaviour you saw

On systemd release 255 systemd fails to unlock/recognize my luks2 swap partition and gets stuck requesting the open luks2 swap UUID with dev/by-uuid/xxxx (xx / no limit)

And thus I get stuck forever without being able to boot in my system. The workaround for now is to create an unencrypted swap partition with the UUID systemd requests (mkswap -U) and then the system boots. 

I tested it a bit futher and it actually reads the encrypted swap with normal reboots, and I could recover from suspend properly. But when the system hibernates it is when systemd refuses to unlock/recognize the swap and gets stuck forever.

What is troublesome is that even nuking my install and reinstalling it, systemd still requested that specific UUID and there was no file in any partition pointing to it, so I believe it might be some data in UEFI PCR / NV index that systemd keeps to validate the system when we boot up? (I even installed with a new EFI  and root partitions on another storage device and it still asked for that specific UUID).

After many tries, it wil ask for the open luks2 swap UUID that systemd last used on boot. (since I nuked this partition 3 times, I can attest to it). By open luks2 open UUID I mean not /dev/sdb3 UUID, but /dev/mapper/swap UUID.

### Steps to reproduce the problem

I guess it is as simple as create a partition, encrypt it with luks2, open it, mkswap the partition, and swapon on it and add it to fstab, put the system to hibernate and get yourself stuck. (At least 4 topics with similar issue were open on Arch newbie or installl categories, but I dont know if it is systemd or systemd Archs implementation that causes the issue, but since Arch usually supplies 'vanilla' (untouched) versions from packages, it might be systemd.

I am a Linux newbe, so I am sorry if it is not an issue and it is something wrong on my end.

### Additional program output to the terminal or log subsystem illustrating the issue

Below is my last post in the Arch forum topic I created, but I think it will be useful:

I created a new partition, encrypted it, created the swap and I could boot the system, and tried 3 times to reboot just to make sure. After I tried suspend and I could still recover and use the system. After I tried hibernate and it failed to mount the swap or recognize it, and asked device by uuid with no limit again. So it seems not that systemd release 255 cant open a luks2 swap, but it has some issue with it after a hibernate.

So some details about my system.

I ran bootctl install --esp-path=/efi, but didnt configure any of its configuration files. So he auto finds the UKIs (/efi/EFI/Linux/arch-linux.efi (and arch-linux-fallback.efi).

Mkinitcpio.conf have hooks systemd (in place of udev), sd-vconsole and sd-encrypt so that it will auto mount root partition with ID 8304 (root x86_64) and when asking for the passphrase to unlock it, save it so it will use it to unlock eveything that is in the file /etc/crypttab, and later mounts as usual with /etc/fstab.

LSBLK:
```
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda           8:0    0 894,3G  0 disk  
├─sda1        8:1    0     1G  0 part  /efi
├─sda2        8:2    0 892,3G  0 part  
│ └─root    254:0    0 892,2G  0 crypt /mnt/games
│                                      /home
│                                      /
└─sda3        8:3    0     1G  0 part  
sdb           8:16   0   1,8T  0 disk  
├─sdb1        8:17   0   1,8T  0 part  
│ └─storage 254:2    0   1,8T  0 crypt /mnt/media
│                                      /mnt/arquivos
│                                      /home/soultrigger/.cache
│                                      /mnt/backup
│                                      /mnt/gameshdd
│                                      /mnt/vm
├─sdb2        8:18   0    32G  0 part  
│ └─var     254:1    0    32G  0 crypt /var/log
│                                      /var/tmp
│                                      /var/cache
│                                      /var/lib/portables
│                                      /var/lib/machines
│                                      /var
└─sdb3        8:19   0    32G  0 part  [SWAP]
```

BLKID
```
/dev/mapper/var: LABEL="var" UUID="57bf5d10-b9f9-497c-8a69-c7b4c8db22de" UUID_SUB="70fc0aba-5933-4fc0-b044-42095b9ce37d" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sdb2: UUID="3b821399-fad7-4c0d-a066-b4979a628ec8" TYPE="crypto_LUKS" PARTLABEL="var" PARTUUID="d4092f44-9502-4e16-adec-14ab8158e3a7"
/dev/sdb3: LABEL="swap" UUID="aab7fafb-3e91-46cb-87c3-5117e7428e92" TYPE="swap" PARTLABEL="swap" PARTUUID="e4d7fd45-f9d5-4b9f-abe2-4c05ea6450cf"
/dev/sdb1: UUID="48c479d9-f61a-4b84-9ff0-07e5b3c46f5b" TYPE="crypto_LUKS" PARTLABEL="storage" PARTUUID="6045f7b7-f955-4391-9cc2-f847095b7214"
/dev/mapper/storage: LABEL="storage" UUID="c1c9b477-c528-4491-b443-963e1c4385ab" UUID_SUB="08e0e17d-1da2-4b10-8869-58fe532d3e39" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/mapper/root: LABEL="root" UUID="6212af1d-9acc-418e-9965-676230b0f323" UUID_SUB="f82a4cb6-019c-4bee-9986-7356e95c86f6" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sda2: UUID="89e38b91-c88a-4562-a24b-0af7445ea4b4" TYPE="crypto_LUKS" PARTLABEL="root" PARTUUID="bc034072-b3e9-4000-ad9b-bbd10a0496d9"
/dev/sda3: UUID="4F3C-39E6" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="rescue" PARTUUID="9c622e66-cc88-46c1-9a66-b8b5d5fdbcf4"
/dev/sda1: LABEL_FATBOOT="EFI" LABEL="EFI" UUID="87CC-D1E5" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="efi" PARTUUID="d0c00661-f809-46b7-a203-1b6c646d2d58"
```

At this moment the swap is unencrypted, but just to illustrate what I mean for swap luks2 opened UUID, lets compare the var partition, its UUID is 89e38b91-c88a-4562-a24b-0af7445ea4b4, but when the luks2 is open /dev/mapper/var its UUID is 57bf5d10-b9f9-497c-8a69-c7b4c8db22de.

So the UUID for the swap that he gets stuck is whatever was the last encrypted swap that systemd used when it is opened as /dev/mapper/swap. So we are with 3 different ones, the original one that I nuked, the second one that I used in the new install and nuked to make an unencrypted one,  and the actual one that is the same UUID as the unencrypted swap partition, but was originally for the opened luks2 as /dev/mapper/swap. 

etc/crypttab
```
# Configuration for encrypted block devices.
# See crypttab(5) for details.

# NOTE: Do not list your root (/) partition here, it must be set up
#       beforehand by the initramfs (/etc/mkinitcpio.conf).

# <name>       <device>                                     <password>              <options>
# home         UUID=b8ad5c18-f445-495d-9095-c9ec4f9d2f37    /etc/mypassword1
# data1        /dev/sda3                                    /etc/mypassword2
# data2        /dev/sda5                                    /etc/cryptfs.key
# swap         /dev/sdx4                                    /dev/urandom            swap,cipher=aes-cbc-essiv:sha256,s>
# vol          /dev/sdb7                                    none

storage         UUID=48c479d9-f61a-4b84-9ff0-07e5b3c46f5b
var             UUID=3b821399-fad7-4c0d-a066-b4979a628ec8
#swap           UUID=16d87301-9170-4bbc-a219-8dbce3f3a742
```

Swap is commented because it is not encrypted at this time.

/etc/fstab
```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>

# /dev/mapper/root LABEL=root
UUID=6212af1d-9acc-418e-9965-676230b0f323       /               btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/@     0 0

# /dev/sda1 LABEL=EFI
UUID=87CC-D1E5                                  /efi            vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro  0 2

# /dev/mapper/root LABEL=root
UUID=6212af1d-9acc-418e-9965-676230b0f323       /home           btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@home 0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /home/soultrigger/.cache        btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/@home_cache   0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var            btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/@var  0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var/log        btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@var_log      0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var/tmp        btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@var_tmp      0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var/cache      btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=259,subvol=/@var_cache    0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var/lib/portables      btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=260,subvol=/@var_lib_portables    0 0

# /dev/mapper/var LABEL=var
UUID=57bf5d10-b9f9-497c-8a69-c7b4c8db22de       /var/lib/machines       btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=261,subvol=/@var_lib_machines     0 0

# /dev/mapper/root LABEL=root
UUID=6212af1d-9acc-418e-9965-676230b0f323       /mnt/games      btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@games        0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /mnt/arquivos   btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@arquivos     0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /mnt/gameshdd   btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=260,subvol=/@gameshdd     0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /mnt/media      btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=259,subvol=/@media        0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /mnt/backup     btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@backup       0 0

# /dev/mapper/storage LABEL=storage
UUID=c1c9b477-c528-4491-b443-963e1c4385ab       /mnt/vm         btrfs           rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=262,subvol=/@vm   0 0

# /dev/mapper/swap LABEL=swap
UUID=aab7fafb-3e91-46cb-87c3-5117e7428e92       none            swap            defaults        0 0
```

/etc/kernel/cmdline
```
splash
```

It is "slpash" just to be passed to plymouth and have it work.

gdisk /dev/sda
```
GPT fdisk (gdisk) version 1.0.9.1

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk /dev/sda: 1875385008 sectors, 894.3 GiB
Model: KINGSTON SA400S3
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): 3EF6C011-3388-4A47-A391-3FD5210E7935
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 1875384974
Partitions will be aligned on 2048-sector boundaries
Total free space is 2669 sectors (1.3 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         2099199   1024.0 MiB  EF00  efi
   2         2099200      1873287167   892.3 GiB   8304  root
   3      1873287168      1875384319   1024.0 MiB  0700  rescue

Command (? for help): 
```

gdisk /dev/sdb
```
GPT fdisk (gdisk) version 1.0.9.1

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk /dev/sdb: 3907029168 sectors, 1.8 TiB
Model: WDC WD20EZRX-00D
Sector size (logical/physical): 512/4096 bytes
Disk identifier (GUID): 07849991-5CC2-4C36-A422-F6672E266613
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 3907029134
Partitions will be aligned on 2048-sector boundaries
Total free space is 2157 sectors (1.1 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048      3772782591   1.8 TiB     8300  storage
   2      3772782592      3839891455   32.0 GiB    8300  var
   3      3839891456      3907028991   32.0 GiB    8200  swap

Command (? for help): 
```

I think the above sums it up well, but if you want to check this is the topic I opened in Arch Forum https://bbs.archlinux.org/viewtopic.php?id=290990

**Comment by YHNdnzj** [comment]
This should be mitigated by #30438. For more information, refer to #30395.

Yes, systemd now tries to store the hibernate location in an EFI variable, and use that information for resuming. With the said patch, we won't be waiting for the swap forever, so that the boot process can be resilient. However, regarding why your encrypted swap is not opened in initrd, it is likely a misconfiguration and should be fixed on your side. I mean, if that doesn't work, then resume can't neither right?

**Comment by YHNdnzj** [comment]
Oh, according to your post on Arch forum, you didn't configure root/swap in `/etc/crypttab.initramfs` for mkinitcpio, but use `gpt-auto` in initrd? gpt-auto only does root mount when running in initrd, so your swap won't appear until switching root into your real root, but resume must be completed before real root is mounted, i.e. in the initrd.

**Comment by TheSoultrigger** [comment]
You are spot on, after adding the swap to the /etc/crypttab.initramfs it seems to be working fine.

Thanks for teaching me someothing else.

Even though it is strange how I could still resume about 80% of the time with swap just in /etc/crypttab before systemd 255. But overall I understand this as an improvement. 

When I recreated the new encrypted swap partitiion, I did swapoff, removed the partition, created it, luks2 on it, mkswap which generated a new UUID,  swapon on it and changed crypttab.initramfs, fstab, mkinitcpio -P, but when I rebooted systemd still asked for the previous UUID, so I had to open the partiton and mkswap -U with the requested UUID. My question is: is there a command in systemd to update the swap UUID in the UEFI variable so that it will get the new one? (Not really needed, but worth asking).

I do have ``HibernateLocation-8cf2644b-4b0b-428f-9387-6d876050dc67```, should I remove it as you pointed out in another post? (it is not an UUID in use right now).

I do run ```systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 --tpm2-with-pin=yes /dev/sda2```, but I dont think it is measured boot with just that, can you point me in the right direction on how to do it (something to read on it)

I also accept tips on what to read to become a good technical knowledgeable person in Linux, sysadmin and so on. I just  used encryptiong without needing it, to see and learn how it works and it seems I failed a bit with the swap.  I mean bookds, sites, anything really, I am eager to learn.

Thanks for your time in helping me and  all the hard work with systemd, it is awesome.

**Comment by YHNdnzj** [comment]
> My question is: is there a command in systemd to update the swap UUID in the UEFI variable so that it will get the new one? (Not really needed, but worth asking).

Ideally this should never be needed, as it will be cleared by `systemd-hibernate-resume` before resuming. However, as I mentioned in the other post, the clearance logic is changed between versions, so this is likely a leftover.

> I do have ``HibernateLocation-8cf2644b-4b0b-428f-9387-6d876050dc67```, should I remove it as you pointed out in another post? (it is not an UUID in use right now).

Yes. Or a hibernation should refresh the record.

**Comment by YHNdnzj** [comment]
> I do run systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 --tpm2-with-pin=yes /dev/sda2, but I dont think it is measured boot with just that, can you point me in the right direction on how to do it (something to read on it)

Indeed. To measure the PCR values, refer to `ukify` and `systemd-measure`. You can generate a UKI with ukify, and use its `systemd-measure` integration to pre-calculate the expected PCR values. You might find https://0pointer.net/blog/brave-new-trusted-boot-world.html worth reading.

But I'm no TPM expert. We also have a new `systemd-pcrlock` component in systemd v255 that I haven't got time to look at. Consider consulting someone else for details :)

Anyways, let's close this issue here, since it's already fixed.
