### ISSUE TITLE
Document explicitly that you cannot escape the effect of SocketBindAllow=/SocketBindDeny= even if you create your own netns

### ISSUE THREAD

**Issue by krumelmonster** [systemd/systemd#30555]
### systemd version the issue has been seen with

255.1-1 + systemd-254.7-1.fc39.src.rpm

### Used distribution

archlinux + fedora39

### Linux kernel version used

6.6.7-arch1-1 + 6.6.6-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

I expected that SocketBindAllow/SocketBindDeny would deny applications only from binding to interfaces available in the default network namespace; Only these would affect actual host resources.

### Unexpected behaviour you saw

Instead it seems that even within containers or other network namespaces (such as created by PrivateNetwork=yes), binds to virtual network interfaces, which would have no effect to the host system, are blocked.

### Steps to reproduce the problem

 - configure a SocketBindAllow/SocketBindDeny restriction for a user slice
 - run a rootless podman container within that slice
 - binds within the container are impossible although they'd never reach the host network namespace (note: these ports are not exposed to the host via --expose!)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[arch@archlinux ~]$ cat /etc/systemd/system/user-1000.slice.d/resources.conf
[Slice]
SocketBindAllow=4321
SocketBindDeny=any
[arch@archlinux ~]$ podman run --rm -it alpine nc -l 1234
nc: bind: Operation not permitted
[arch@archlinux ~]$ sudo rm /etc/systemd/system/user-1000.slice.d/resources.conf
[arch@archlinux ~]$ sudo systemctl daemon-reload
[arch@archlinux ~]$ podman run --rm -it alpine nc -l 1234
^Cpunt!

----

[root@fedora ~]# systemd-run -t -p SocketBindAllow=4321 -p SocketBindDeny=any -p PrivateNetwork=yes /bin/nc -l 1234
Running as unit: run-u180.service
Press ^] three times within 1s to disconnect TTY.
nc: Operation not permitted

----

[root@archlinux ~]# systemd-run -t -p SocketBindAllow=4321 -p SocketBindDeny=any -p PrivateNetwork=yes /bin/nc -l 1234
Running as unit: run-u47.service; invocation ID: 67b14978c8064ca5a7cf68479246d5a9
Press ^] three times within 1s to disconnect TTY.
Error: Couldn't setup listening socket (err=-3)
[root@archlinux ~]# systemd-run -t -p PrivateNetwork=yes /bin/nc -l 1234
Running as unit: run-u48.service; invocation ID: 8c2ac8a7c6e94b51ac527f52dbe5d4fc
Press ^] three times within 1s to disconnect TTY.
^C
[root@archlinux ~]#
```

**Comment by krumelmonster** [comment]
previously mentioned in https://github.com/systemd/systemd/issues/30512#issuecomment-1864822632

**Comment by poettering** [comment]
SocketBindAllow= has nothing to do with userns, but with cgroups. What made you think otherwise?

**Comment by krumelmonster** [comment]
I know that.

My reports is about the interaction of SocketBindAllow with network namespaces, particularly those of containers.

SocketBindAllow should only ever deny bind calls to actual host resources but is affects any bind-call whatsoever.

I would expect that a user or service that has only SocketBindAllow=8080 could run a containerized web application that listens on port 80 internally on the containers own network namespaces veth and expose this to port 8080 to the host. E.g.:

```
podman run -p 8080:80 nginx
```

This would really only bind to the host port 8080 yet the eBPF filters are written in a way that they block the nginx process *within* the container from binding to it's virtual interface although this has no effect whatsoever on the host port 80.

This behavior is easily demonstrated with systemds own `PrivateNetwork` option. As netcats bind to port 1234 never reaches the systems network namespace, I propose to not block it:
`systemd-run -t -p SocketBindAllow=4321 -p SocketBindDeny=any -p PrivateNetwork=yes /bin/nc -l 1234`

The expected behaviour would be for SocketBind-Rules to only deny binding to actual hosts resources.

**Comment by poettering** [comment]
No, the idea is that you cannot escape SBA=/SBD= down the tree, no matter what you do.
