### ISSUE TITLE
SocketBindDeny=any allows all binds

### ISSUE THREAD

**Issue by krumelmonster** [systemd/systemd#30556]
### systemd version the issue has been seen with

255.1-1 + systemd-254.7-1.fc39.src.rpm

### Used distribution

archlinux + fedora39

### Linux kernel version used

6.6.7-arch1-1 + 6.6.6-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The Documentation for systemd.resource-control presents this example in the [SocketBindAllow=bind-rule, SocketBindDeny=bind-rule](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#SocketBindAllow=bind-rule)
```
# Deny binding IPv4 and IPv6 socket addresses.
[Service]
SocketBindDeny=any
```

and intuitively, I would assume that this denies any binds whatsoever

### Unexpected behaviour you saw

however, `SocketBindDeny=all` without anything listed to `SocketBindAllow=` seems to not deny any bind calls.

### Steps to reproduce the problem

Configure a slice or a service with `SocketBindDeny=any` but no `SocketBindAllow`-Option, verify it is able to bind to any port

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[root@archlinux ~]# systemd-run -t -p SocketBindDeny=any nc -l 1234
Running as unit: run-u49.service; invocation ID: 43a3e69507a042c5926d00497d0a69b0
Press ^] three times within 1s to disconnect TTY.
^C
[root@archlinux ~]# systemd-run -t -p SocketBindAllow= -p SocketBindDeny=any nc -l 1234
Running as unit: run-u50.service; invocation ID: 2de91e45ab094a34b578e35e6173c92b
Press ^] three times within 1s to disconnect TTY.
^C
[root@archlinux ~]# systemd-run -t -p SocketBindAllow=1 -p SocketBindDeny=any nc -l 1234
Running as unit: run-u51.service; invocation ID: 5673ffb1b8a841bd8cfb9179f0888116
Press ^] three times within 1s to disconnect TTY.
Error: Couldn't setup listening socket (err=-3)
[root@archlinux ~]# # note how only when SocketBindAllow is set to a rule, permission to bind is actually denied
```

**Comment by kumargu** [comment]
what version carries this fix? We were using version 252 (on Redhat linux) and I could still see the issue. 

here's a reference to our [config](https://github.com/opensearch-project/OpenSearch/pull/17107/files#diff-bee108494385410aec51bb0e93cad2adf6bdb0900f4b499d8cf138cda25c2d03R155-R156).

**Comment by networkException** [comment]
As far as I know 256 and a backport to 255. The patch should be pretty self contained and apply to earlier releases without much effort though
