### ISSUE TITLE
WRONG_ARGUMENTS_ORDER in src/systemctl/systemctl-edit.c

### ISSUE THREAD

**Issue by ellena13** [systemd/systemd#30570]
Possibly mismatched call arguments in function `unit_find_paths` : *cached\_id\_map* and *cached\_name\_map*  

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/systemctl/systemctl-edit.c#L63

passed in place of *Hashmap \*\* cached\_name\_map* and *Hashmap \*\* cached\_id\_map*

https://github.com/systemd/systemd/blob/bab787396444466e5a71e5f01b1924646959f6e0/src/systemctl/systemctl-util.h#L38

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova (e.bykhanova@fobos-nt.ru).

**Comment by yuwata** [comment]
-> #30576.
