### ISSUE TITLE
some btrfs mount options ignored when fstab entry has x-initrd.mount

### ISSUE THREAD

**Issue by HazelHex** [systemd/systemd#30583]
### systemd version the issue has been seen with

254.5-7.1

### Used distribution

openSUSE Aeon 20231219-2654.1

### Linux kernel version used

6.6.6-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

openSUSE Aeon (MicroOS) has some /etc/fstab btrfs subvolume mounts with the **x-initrd.mount** option. For example: /var, /root, /etc. I've added the _noatime_ option to these entries. When the host booted, I see the _relatime_ default kernel option in `mount` output, instead of the _noatime_ under such entries.
Without the **x-initrd.mount** all options are correctly applied.
The _subvol_, _subvolid_ options are working fine in both cases.

### Unexpected behaviour you saw

It seems that, when such entries get mounted under the initrd, some mount options for them are ignored and are not propagated when transitioning to a host. For example: _noatime_, _enospc_debug_ and maybe others.

### Steps to reproduce the problem

1. Find in /etc/fstab a btrfs entry with the _x-initrd.mount_ mount option;
2. Add the _noatime_ option to such entry;
3. Reboot;
4. Observe the output of `mount` command with this entry, it says _relatime_.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
user@host:~> cat /etc/fstab 
UUID=... / btrfs ro,noatime 0 0
UUID=... /var btrfs subvol=/@/var,x-initrd.mount,noatime 0 0
UUID=... /usr/local btrfs subvol=/@/usr/local,noatime 0 0
UUID=... /srv btrfs subvol=/@/srv,noatime 0 0
UUID=... /root btrfs subvol=/@/root,x-initrd.mount,noatime,enospc_debug  0 0
UUID=... /opt btrfs subvol=/@/opt,noatime 0 0
UUID=... /boot/writable btrfs subvol=/@/boot/writable,noatime 0 0
UUID=... /boot/grub2/x86_64-efi btrfs subvol=/@/boot/grub2/x86_64-efi,noatime 0 0
UUID=... /boot/grub2/i386-pc btrfs subvol=/@/boot/grub2/i386-pc,noatime 0 0
UUID=... /.snapshots btrfs subvol=/@/.snapshots,noatime 0 0
UUID=... /boot/efi vfat utf8,noatime,nodev,noexec,nosuid,discard 0 2
overlay /etc overlay lowerdir=/sysroot/var/lib/overlay/9/etc:/sysroot/etc,upperdir=/sysroot/var/lib/overlay/10/etc,workdir=/sysroot/var/lib/overlay/10/work-etc,x-systemd.requires-mounts-for=/var,x-systemd.requires-mounts-for=/sysroot/var,x-initrd.mount,noatime 0 0

user@host:~> mount
/dev/nvme0n1p2 on / type btrfs (ro,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=277,subvol=/@/.snapshots/10/snapshot)
/dev/nvme0n1p2 on /root type btrfs (rw,relatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=260,subvol=/@/root)
/dev/nvme0n1p2 on /var type btrfs (rw,relatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@/var)
overlay on /etc type overlay (rw,relatime,seclabel,lowerdir=/sysroot/var/lib/overlay/9/etc:/sysroot/etc,upperdir=/sysroot/var/lib/overlay/10/etc,workdir=/sysroot/var/lib/overlay/10/work-etc)
...
/dev/nvme0n1p2 on /.snapshots type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=266,subvol=/@/.snapshots)
/dev/nvme0n1p2 on /boot/grub2/i386-pc type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=265,subvol=/@/boot/grub2/i386-pc)
/dev/nvme0n1p2 on /boot/grub2/x86_64-efi type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=264,subvol=/@/boot/grub2/x86_64-efi)
/dev/nvme0n1p2 on /boot/writable type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=263,subvol=/@/boot/writable)
/dev/nvme0n1p2 on /opt type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=261,subvol=/@/opt)
/dev/nvme0n1p2 on /srv type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=259,subvol=/@/srv)
/dev/nvme0n1p2 on /usr/local type btrfs (rw,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@/usr/local)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,nosuid,nodev,noexec,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro,discard)
...

user@host:~> cat /run/mount/utab
SRC=/dev/nvme0n1p2 TARGET=/sysroot/root ROOT=/@/root OPTS=x-initrd.mount
SRC=/dev/nvme0n1p2 TARGET=/sysroot/var ROOT=/@/var OPTS=x-initrd.mount
SRC=overlay TARGET=/sysroot/etc ROOT=/ OPTS=x-systemd.requires-mounts-for=/var,x-systemd.requires-mounts-for=/sysroot/var,x-initrd.mount

user@host:~> systemctl cat root.mount
# /run/systemd/generator/root.mount
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/etc/fstab
Before=local-fs.target
After=blockdev@dev-disk-by\x2duuid-....target

[Mount]
What=/dev/disk/by-uuid/...
Where=/root
Type=btrfs
Options=subvol=/@/root,x-initrd.mount,noatime,enospc_debug

user@host:~> sudo systemctl status root.mount
[sudo] password for user: 
● root.mount - /root
     Loaded: loaded (/etc/fstab; generated)
     Active: active (mounted) since Fri 2023-12-22 07:42:32 EET; 1h 44min ago
      Where: /root
       What: /dev/nvme0n1p2
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
```

**Comment by HazelHex** [comment]
Today came the 254.5-8.1 update, and now I see:
`user@host:~> mount
/dev/nvme0n1p2 on / type btrfs (ro,noatime,seclabel,ssd,discard=async,space_cache=v2,subvolid=278,subvol=/@/.snapshots/11/snapshot)
/dev/nvme0n1p2 on /root type btrfs (rw,**noatime**,seclabel,ssd,discard=async,space_cache=v2,subvolid=260,subvol=/@/root)
/dev/nvme0n1p2 on /var type btrfs (rw,**noatime**,seclabel,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/@/var)
overlay on /etc type overlay (rw,**noatime**,seclabel,lowerdir=/sysroot/var/lib/overlay/10/etc:/sysroot/etc,upperdir=/sysroot/var/lib/overlay/11/etc,workdir=/sysroot/var/lib/overlay/11/work-etc)`

So now at least the _noatime_ option works. But in my fstab, for example, for /root there is still _enospc_debug_ set, which this `mount` output doesn't show.

Maybe it is something going on with the Aeon's transactional update behaviour or dracut, but when I rebooted a million times before this update, only the fstab entries without the _x-initrd.mount_ worked for sure.

I must note, that I'm the ordinary user, and, frankly, the dracut, initrd and systemd's role in this process is a black box to me. I just want my mount options to work :) Nevertheless, I will happily assist to diagnose this and to provide additional info. Merry X-mas, btw!

**Comment by YHNdnzj** [comment]
I can't seem to reproduce this with `mkinitcpio` + `systemd` hook BTW.

**Comment by poettering** [comment]
are you sure you rebuilt your initrds after chaning those options?

**Comment by poettering** [comment]
CLosing due to lack of response.
