### ISSUE TITLE
systemd-pcrlock/systemd-measure binaries installed, their man pages not with -Dbootloader=false

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#30588]
Building with `-Dbootloader=false` results in the binaries `systemd-pcrlock` and `systemd-measure` being installed, but not their man pages:
```
Message: Skipping systemd-measure.1 because ENABLE_BOOTLOADER is false
Message: Skipping systemd-pcrlock.8 because ENABLE_BOOTLOADER is false
...

Installing systemd-measure to /<<PKGBUILDDIR>>/debian/tmp/usr/lib/systemd
Installing systemd-pcrlock to /<<PKGBUILDDIR>>/debian/tmp/usr/lib/systemd
```

I would expect, that the binaries are not installed in this case.

**Comment by mbiebl** [comment]
hm, this is actually getting weirder.
We have a whole bunch of other pcr related man pages and files, which *are* installed with `-Dbootloader=false`:

```
systemd.manpages:usr/share/man/man5/systemd.pcrlock.5
systemd.manpages:usr/share/man/man5/systemd.pcrlock.d.5
systemd.manpages:usr/share/man/man8/systemd-pcrlock.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-file-system.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-firmware-code.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-firmware-config.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-machine-id.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-make-policy.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-secureboot-authority.service.8
systemd.manpages:usr/share/man/man8/systemd-pcrlock-secureboot-policy.service.8
systemd.install:<!stage1> usr/lib/pcrlock.d/
systemd.install:usr/lib/systemd/systemd-pcrlock
systemd.install:usr/lib/systemd/system/systemd-pcrlock-file-system.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-firmware-code.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-firmware-config.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-machine-id.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-make-policy.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-secureboot-authority.service
systemd.install:usr/lib/systemd/system/systemd-pcrlock-secureboot-policy.service
```
Are those files supposed to be installed if built with `-Dbootloader=false`?
If yes, why is `systemd-pcrlock.8` as only man page conditionalized on `ENABLE_BOOTLOADER`

**Comment by bluca** [comment]
I think what we want is to install binaries and their manapges, but not units when bootloader=false. However I am seeing that we still install everything, including the actual bootloader, when bootloader=false...

**Comment by bluca** [comment]
So what needs to be avoided without the bootloader stuff is the units, which perform measurements but are really useful only if sd-stub runs first and provides the first measurements. The binaries we always want to install, in case somebody wants to use them. The documentation for them is wrongly conditionalized, the linked PR fixes it.
