### ISSUE TITLE
Systemctl hibernate "Not enough swap space for hibernation" with BTRFS Swap

### ISSUE THREAD

**Issue by charmoniumQ** [systemd/systemd#30599]
### systemd version the issue has been seen with

254.3

### Used distribution

NixOS

### Linux kernel version used

6.1.64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

System should hibernate, because there is plenty of swap space

### Unexpected behaviour you saw

```
$ systemctl hibernate
Call to Hibernate failed: Not enough swap space for hibernation

$ free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       6.8Gi       199Mi       2.5Gi       8.4Gi       5.8Gi
Swap:           23Gi       9.0Mi        23Gi
```

### Steps to reproduce the problem

Not entirely sure? Maybe make make a btrfs swap file.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ # If it matters (which I don't think it should), my swap partition is a btrfs subvolume on luks encrypted disk.

$ swapon
NAME           TYPE SIZE   USED PRIO
/swap/swapfile file  24G 139.2M   -2

$ # No, I am not splitting the swapfile across multiple disks. I have one btrfs subvolume for `/swap`.

$ mount -v | grep swap
/dev/mapper/crypted on /swap type btrfs (rw,relatime,compress=zstd:3,ssd,noacl,space_cache=v2,subvolid=260,subvol=/swap)

$ cat /etc/fstab | grep -i swap
# To make changes, edit the fileSystems and swapDevices NixOS options
/dev/mapper/crypted /swap btrfs subvol=swap 0 0
# Swap devices.
/swap/swapfile none swap defaults

$ sudo btrfs sub list / | grep swap
ID 260 gen 6590 top level 5 path swap
```

**Comment by YHNdnzj** [comment]
Have you configured `resume=` and `resume_offset=` kernel parameter? Swapfile offset calculation for btrfs is added in v255.

**Comment by YHNdnzj** [comment]
Anyways, systemd v255 has also got more detailed error messages for hibernation. If it doesn't work on v255 either, feel free to ask for reopen.
