### ISSUE TITLE
Support hardware buttons in systemd-boot

### ISSUE THREAD

**Issue by appsforartists** [systemd/systemd#30598]
### Component

systemd-boot

### Is your feature request related to a problem? Please describe

Tablets and handheld gaming devices, much like phones, don't typically have physical keyboards.  Therefore, a user cannot select a systemd-boot entry without connecting one.

### Describe the solution you'd like

Following the convention set by Android phones, systemd-boot should support volume up/down in lieu of arrow up/down, and power in lieu of select.  (Tapping power would be used for selection; holding the button down could be used for shutdown).

### Describe alternatives you've considered

It would be really handy if the gamepad buttons on a gaming handheld were also supported; however, I suspect systemd-boot already has plumbing for keyboard events, and it might be out-of-scope to add gamepad support for what's intended to be a minimalist loader.

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by AdrianVovk** [comment]
See also #8466

**Comment by appsforartists** [comment]
Thanks @AdrianVovk.

@poettering how can I figure out what the key codes are in UEFI?

**Comment by appsforartists** [comment]
According to [the spec](https://uefi.org/specs/UEFI/2.10/Apx_B_Console.html), it looks like `80`, `81`, and `102` might be the magic numbers.

**Comment by appsforartists** [comment]
which is `SCAN_VOLUME_UP`, `SCAN_VOLUME_DOWN`, `SCAN_SUSPEND` in [`simple-text-io.h`](https://github.com/systemd/systemd/blob/17f3e91e8107b2b29fe25755651b230bbc81a514/src/boot/efi/proto/simple-text-io.h#L93-L97)

**Comment by poettering** [comment]
ah, good. the fix should be easy then. See menu_run() in src/boot/efi/boot.c, and how it already covers SCAN_UP, SCAN_DOWN and so on. Just add the relevant additional lines there. Happy to review/merge a patch for that.
