### ISSUE TITLE
Incorrect behavior of nested Freeze/Thaw in a Slice

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#30640]
_Originally posted by @AdrianVovk in https://github.com/systemd/systemd/pull/30612#discussion_r1436138503_

Test I just ran on my machine:
```
# systemctl freeze user@60071.service
# systemctl freeze user.slice
# systemctl status user@60071.service
(indicates that it's frozen)
# systemctl status user.slice
(indicates that it's frozen)
# systemctl thaw user.slice
# systemctl status user.slice
(indicates that it's no longer frozen. Expected)
# systemcl status user@60071.service
(indicates that it's no longer frozen. UNEXPECTED!)
```

I feel that this behavior is wrong. It also negates the benefits of freezing the homed user session:

- User closes lid
- gnome-shell decides that it wants to drop encryption keys. So, it switches to GDM and calls Lock on the home dir
- homed freezes the user session, to protect against the aforementioned edge cases, then drops the encryption keys and freezes the LUKS device
- systemd-sleep now executes. It freezes all user.slice to freeze all user sessions
- system goes into suspend
- (some time later) system is resumed
- systemd-sleep continues execution. It thaws user.slice
- This now thaws the homed user session too!
- gnome-shell and the rest of the user session are running again. But file I/O is still blocked! Queue all of the edge cases I mentioned in a previous comment
- (some time later) the user enters their password. This unlocks the LUKS device and the danger has passed.

There can be an arbitrary amount of time between the resume and the user entering their password. Thus, we can have any of the edge cases happen and lead to data loss.

Any insight on this? Why is it behaving this way? Anything we can do about it?

**Comment by AdrianVovk** [comment]
I did some git archaeology, and it looks like nobody tested the scenario of freezing the child, then parent and thawing parent, then child

Some relevant links:
- Commit that introduced the Freeze/Thaw behavior on Slices: [d9e45bc](https://github.com/systemd/systemd/commit/d9e45bc3abb8adf5a1cb20816ba8f2d2aa65b17e#diff-f5420072dd309e571f3c7ebbf4b609dbb2336cbe54435ca6a44680b49489e459R377)
- PR that introduced the same: https://github.com/systemd/systemd/pull/13512
- Relevant discussion from the PR: https://github.com/systemd/systemd/pull/13512#issuecomment-573007207

CC @msekletar

**Comment by AdrianVovk** [comment]
Any context as to why we recurse through the dependencies of a slice and freeze them individually? Why not just freeze the slice and let the kernel freeze all descendants implicitly? Looks like the code was written this way from the very first version of #13512

**Comment by msekletar** [comment]
It just made sense to me at the time, I guess. Slice units imply further organization of cgroup tree down the line, they are not opaque black boxes (as opposed to delegated sub-hierarchies) hence we don't treat them that way and apply requested operation to units residing in them. Also, accounting of freezing/thawing "progress" is much cleaner when we do recursive walk. 

So I think that current behavior is correct. However, if we figure out that no one depends on it I am fine with changing it the way you described.

**Comment by Werkov** [comment]
Looks like a dup of #15850.

>  it seems to be that user's request to have child.service frozen was wiped by thawing parent.slice.
