### ISSUE TITLE
Bluetooth can't connect to both keyboard and headphones

### ISSUE THREAD

**Issue by katkasoft** [systemd/systemd#30659]
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.8-arch1-1 

### CPU architectures issue was seen on

amd64

### Component

bluetooth

### Expected behaviour you didn't see

I expected working both bluetooth devices

### Unexpected behaviour you saw

Bluetooth can't connect to both keyboard and headphones

**Comment by yuwata** [comment]
No useful information. There is no hint that the issue is caused by systemd. Closing.

**Comment by YHNdnzj** [comment]
This report contains no valuable information. An how does bluetooth have anything to do with systemd?

Closing as misfiled.

**Comment by katkasoft** [comment]
> This report contains no valuable information. And how does bluetooth have anything to do with systemd?
> 
> Closing as misfiled.

i thought bluetooth.service is built-in in systemd

**Comment by yuwata** [comment]
> > This report contains no valuable information. And how does bluetooth have anything to do with systemd?
> > Closing as misfiled.
> 
> i thought bluetooth.service is built-in in systemd

No.
