### ISSUE TITLE
systemd-tpm2-setup.service fails to start with TPM 1.2

### ISSUE THREAD

**Issue by andreyv** [systemd/systemd#30650]
### systemd version the issue has been seen with

255.2

### Used distribution

Arch Linux

### Linux kernel version used

6.1.69-1-lts

### CPU architectures issue was seen on

x86_64

### Component

other

### Unexpected behaviour you saw

2e64cb71b9c0160c335d8e52954149e078bba2fb added two new TPM-related services, `systemd-tpm2-setup.service` and `systemd-tpm2-setup-early.service`. `sysinit.target` depends on these services.

On a Dell Latitude E5550 system, which doesn't seem to have TPM 2.0:
```
tpm_tis 00:08: 1.2 TPM (device-id 0x3205, rev-id 80)
```
these units are still started and fail to load:
```
systemd-tpm2-setup[454]: ERROR:tcti:src/tss2-tcti/tcti-device.c:451:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory
systemd[1]: Starting TPM2 SRK Setup...
systemd-tpm2-setup[454]: Failed to create TPM2 context: State not recoverable
luna systemd[1]: systemd-tpm2-setup.service: Main process exited, code=exited, status=1/FAILURE
luna systemd[1]: systemd-tpm2-setup.service: Failed with result 'exit-code'.
luna systemd[1]: Failed to start TPM2 SRK Setup.
```

`ConditionSecurity=measured-uki` is satisfied because I boot using systemd-stub.

systemd is configured with
```
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by bluca** [comment]
Only TPM 2.0 are supported - as the name suggests, systemd-**tpm2**-setup.service

**Comment by andreyv** [comment]
> Only TPM 2.0 are supported - as the name suggests, systemd-tpm2-setup.service

Sure, this is fine.

The problem is that these services are started on an unsupported system and fail with errors during boot.

**Comment by andreyv** [comment]
Found another possibly related MR: #30194
