### ISSUE TITLE
RFE: way to set a default (or override the) hostname via DMI/SMBIOS

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#30667]
### Component

systemd, systemd-hostnamed

### Is your feature request related to a problem? Please describe

I'm using a lot of stateless VMs for experimentation and homelab workloads that all boot from a shared immutable source (such as a live CD in the simplest case, but it can also be network boot). All of those VMs start with a default hostname that's hardcoded into the immutable rootfs.

My network setup includes a dnsmasq instance that sets up internal DNS records for all hosts according to their hostnames. However, because all those VMs share a hostname, I find that I cannot easily address them if manual intervention is needed.

### Describe the solution you'd like

I'd like a way for systemd to set up (or override) a machine's hostname according to _some_ information that can be provided by the VMM/hypervisor (that is supported by unpatched free software VMMs like qemu).

This could be done via:

- Raw SMBIOS items
- Raw fw_cfg items
- Credentials passed via any of the above (to match machine-id import)

### Describe alternatives you've considered

- writing some tooling around libvirt and dnsmasq to gather MAC addresses, map them to IPs and install custom DNS entries (this is hacky and fragile);
- using cloud-init or writing custom code that pulls from SMBIOS or fw_cfg.

However, this seems to be a generic enough feature to warrant its inclusion in systemd (after all, machine-id is already being imported from credentials).

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by septatrix** [comment]
You can assign hostnames via DHCP if your VMM supports it. Regardless, I agree that a `firstboot.hostname` credential would be great for scenarios where this is not feasible.

**Comment by septatrix** [comment]
You can assign hostnames via DHCP if your VMM supports it though anything present in `/etc/hostname` will take precedence.

There is also `systemd.hostname` kernel cmdline arg though that is only for early boot (I would assume initrd before it gets a chance to set something better). There is `systemd.setenv`, too, which you could use to set `SYSTEMD_DEFAULT_HOSTNAME`. That will be used if neither `/etc/hostname` nor DHCP yield any hostname result. You should be able to set kernel cmdline args via the VMM (unless you use signed UKIs AFAIK... ).

Regardless, I agree that a `firstboot.hostname` credential would be great for scenarios where this is not feasible.

**Comment by intelfx** [comment]
> You can assign hostnames via DHCP if your VMM supports it

Unless the plan is to limit myself to libvirt's or qemu's integrated networking (and even then I'm not aware of any such feature), this would amount to scripting around the VMM and the external DHCP server, which is not really a viable solution.

> You should be able to set kernel cmdline args via the VMM

Not sure how would I do it?

**Comment by poettering** [comment]
yeah, we should have firstboot.hostname I guess.

**Comment by septatrix** [comment]
> > You can assign hostnames via DHCP if your VMM supports it
> 
> Unless the plan is to limit myself to libvirt's or qemu's integrated networking (and even then I'm not aware of any such feature), this would amount to scripting around the VMM and the external DHCP server, which is not really a viable solution.

At least qemu support it: https://man.archlinux.org/man/qemu.1.en#hostname=name

> > You should be able to set kernel cmdline args via the VMM
> 
> Not sure how would I do it?

From the mkosi docs:

> When booting in a VM, these are appended to the kernel command line via the SMBIOS io.systemd.stub.kernel-cmdline-extra OEM string. This will only be picked up by systemd-boot/systemd-stub versions newer than or equal to v254.

**Comment by intelfx** [comment]
@septatrix

> At least qemu support it: https://man.archlinux.org/man/qemu.1.en#hostname=name

Yep, that's what I meant by using qemu's integrated networking. For VMs that have to integrate into a larger network this is not an option.

> From the mkosi docs:
>> When booting in a VM, these are appended to the kernel command line via the SMBIOS io.systemd.stub.kernel-cmdline-extra OEM string. This will only be picked up by systemd-boot/systemd-stub versions newer than or equal to v254.

Looks like the docs are slightly wrong; there is no support for `io.systemd.stub.kernel-cmdline-extra` in systemd-boot (only the stub). That would have indeed solved my problem but unfortunately rebuilding the distribution boot process to use UKIs with systemd-stub is quite invasive.
