### ISSUE TITLE
sd-netlink:  inverse order cause the bond's slave is empty

### ISSUE THREAD

**Issue by zhangjian3032** [systemd/systemd#30682]
### systemd version the issue has been seen with

255

### Used distribution

Yocto

### Linux kernel version used

N/A

### CPU architectures issue was seen on

None

### Component

systemd-networkd

### Expected behaviour you didn't see

If we have 2 links, slave and master, in the inverse order,
the master will be created first, then the slave will be created,

so the `link_append_to_master` and `link_update_master` work well.
but in the normal order, the slave will be created first,
maybe we need add a new function `link_update_slave` to update the slaves of current master.
or keep the inverse order.

see: https://github.com/systemd/systemd/commit/52ceba53d3

### Unexpected behaviour you saw

N/A

### Steps to reproduce the problem

N/A

**Comment by zhangjian3032** [comment]
@yuwata 
Would you mind taking a moment to glance at this?

**Comment by yuwata** [comment]
Fix is waiting in #30767.
