### ISSUE TITLE
tmpfiles cleaning blocks on FIFOs

### ISSUE THREAD

**Issue by lheckemann** [systemd/systemd#30690]
### systemd version the issue has been seen with

254.6

### Used distribution

NixOS

### Linux kernel version used

6.6.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

systemd-tmpfiles completes.

### Unexpected behaviour you saw

systemd-tmpfiles blocks on trying to open a FIFO whose other end is not open.

### Steps to reproduce the problem

Place a FIFO in a directory which is cleaned up by systemd-tmpfiles, wait for the age to expire and systemd-tmpfiles-cleanup.timer to trigger (or invoke `systemd-tmpfiles --clean` manually under faketime).

NixOS test:
```nix
let
  pkgs = import <nixpkgs> {};
in pkgs.nixosTest {
  name = "systemd-tmpfiles-fifo";
  nodes.machine = {
    systemd.tmpfiles.settings."test"."/tmp/foo"."d" = {
      age = "1m";
    };
    environment.systemPackages = [ pkgs.libfaketime ];
  };
  testScript = ''
    machine.wait_for_unit("multi-user.target")
    print(machine.succeed("""
      set -x
      exec >&2
      mkfifo /tmp/foo/blocker
      SYSTEMD_LOG_LEVEL=debug faketime 2030-01-01 timeout 5 systemd-tmpfiles --clean
    """))
  '';
}
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Running clean action for entry d /tmp/foo
Cleanup threshold for directory "/tmp/foo" is Mon 2029-12-31 23:59:00.218353 UTC; age-by: abcmABM
(hangs here)
```

**Comment by lheckemann** [comment]
Testing with v255 as well (but the build needs to finish first).

I suspect it won't be fixed there; the hang seems to be in this call:
https://github.com/systemd/systemd/blob/c0d672f1615c9af026a53de426206725798dc5ce/src/tmpfiles/tmpfiles.c#L820-L824

Maybe the lock checking should just be skipped for FIFOs?

**Comment by poettering** [comment]
uff.

**Comment by poettering** [comment]
we should be able to just add O_NONBLOCK here.
