### ISSUE TITLE
bootctl install fails with "Failed to probe file system "/dev/nvme0n1p2": Input/output error"

### ISSUE THREAD

**Issue by maru-sama** [systemd/systemd#30708]
### systemd version the issue has been seen with

255.2-3

### Used distribution

Debian sid

### Linux kernel version used

6.6.9-amd64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

bootctl install works without any issues

### Unexpected behaviour you saw

Running bootctl install fails with 
Failed to probe file system "/dev/nvme0n1p2": Input/output error

### Steps to reproduce the problem

run `bootctl install`
If the esp partiion is mounted I see the following error

"Failed to probe file system "/dev/nvme0n1p2": Input/output error"

If I umount the partition this error message disappears but then I get

"Couldn't find EFI system partition. It is recommended to mount it to /boot or /efi."

Which makes sense since it is mounted ok.

**Comment by poettering** [comment]
can you strace this (`strace -s 500 -y -o log bootctl install`) and paste the output this generates in (in the `log` file). We need to see what precisely causes the EIO error

**Comment by maru-sama** [comment]
Hello,

I added the complete strace log
[log.txt](https://github.com/systemd/systemd/files/13819999/log.txt)

**Comment by poettering** [comment]
The EIO doesn't come from the kernel. It's probably something from libblkid. Weird.

Does 'blkid -p /dev/nvme0n1p2` work for you? Does it output useful info (please paste)

**Comment by maru-sama** [comment]
Ok, that's strange 'blikid' actually prints nothing at all for this partition. no error just blank output. Another partition on the same nvme works fine.

**Comment by maru-sama** [comment]
Here the partition table of the device
```
Model: Samsung SSD 970 EVO 500GB (nvme)
Disk /dev/nvme0n1: 500GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
 2      1049kB  538MB   537MB   fat32        EFI   boot, esp
 3      538MB   1612MB  1074MB  zfs
 4      1612MB  500GB   498GB   zfs
```

**Comment by maru-sama** [comment]
So at least the name should show up in blkid.

**Comment by poettering** [comment]
so if the partition is misrecognized by libblkid then this needs to be addressed there. Can you file a bug on https://github.com/util-linux/util-linux/issues about this? (and link this issue there)

Also, can you rerun this blkid -p thing with `LIBBLKID_DEBUG=all` env var set? anything more interesting in the output then?

/cc @karelzak

**Comment by maru-sama** [comment]
Hi,

I fixed this, apparently something in the partition itself tripped the detection logic. I formatted the partition as ext4 and then as fat -F 32 again. After that blkid gave output and also the install worked.

I'll close this ticket now, thanks for pointing me in the right direction
