### ISSUE TITLE
inst_rule_programs() fails for multipath-tools

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#30703]
Trying to run the multipath-tools tests in TEST-64-UDEV-STORAGE I noticed the following failure:

```
123s I: Skipping program $env{MPATH_SBIN_PATH}/multipath used in udev rule 56-dm-mpath.rules as it cannot be found
```
and a subsequent failure of `testcase_multipath_basic_failover`

Upstream multipath-tools uses constructs like this in its udev rules:
```
ENV{MPATH_SBIN_PATH}="/sbin"
TEST!="$env{MPATH_SBIN_PATH}/multipath", ENV{MPATH_SBIN_PATH}="/usr/sbin"

# Don't run multipath -U during "coldplug" after switching root,
# because paths are just being added to the udev db.
ACTION=="add", ENV{.MPATH_DEVICE_READY_OLD}=="1", GOTO="paths_ok"

# Check the map state directly with multipath -U.
# This doesn't attempt I/O on the device.
PROGRAM=="$env{MPATH_SBIN_PATH}/multipath -U -v1 %k", GOTO="paths_ok"
```

**Comment by mrc0mmand** [comment]
The "Skipping" message is expected (and harmless), the issue was in the wrong kpartx rule file being installed on Debian, please see https://github.com/systemd/systemd/pull/30711.
