### ISSUE TITLE
OnCalendar isn't causing timer to run more than once

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#3070]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> arch,centos7
### In case of bug report: Expected behaviour you didn't see

> timer runs periodically every 3 minutes
### In case of bug report: Unexpected behaviour you saw

> timer started, ran once, didn't run again
### In case of bug report: Steps to reproduce the problem

> create service
> create timer with `OnCalendar=*:0/3:*`
> `systemctl start <svc>.timer`
> (wait a few minutes)
> `systemctl list-timers` shows the timer only runs on start and never again

Besides just starting the timer, I also tried various combinations of enabling it and the service it triggers, and playing around with other `[Timer]` settings but I couldn't make the timer run a second time without manually restart it.

See [this gist](https://gist.github.com/zfjagann/67ab3c8927e441b1a1bd8a4206e8174b) for details on the services and commands I used to test this.

**Comment by evverx** [comment]
Try to remove [RemainAfterExit=yes](https://gist.github.com/zfjagann/67ab3c8927e441b1a1bd8a4206e8174b#file-say-hello-service-L9). Does it work?

https://www.freedesktop.org/software/systemd/man/systemd.service.html#RemainAfterExit=

> Takes a boolean value that specifies whether the service shall be considered active even when all its processes exited.

**Comment by poettering** [comment]
Yeah, @evverx is right, please drop the RemainAfterExit= line. That makes sure that your service sticks around forever, and thus the timer unit won't activate it again, since it is still active.

**Comment by zealws** [comment]
I tried it with and without `RemainAfterExit`. When I get to a computer I can try it again and provide a gist of the behavior.

**Comment by zealws** [comment]
I removed `RemainAfterExit` from the service and it started running periodically, but I noticed an even stranger behavior while running `list-timers` repeatedly while tailing the journal for the service.

Each time I ran `list-timers` (about once per second) it reported that there was less than a second left on the `say-hello.timer` and re-ran the service. This behavior would continue so long as I continued running `list-timers` every second, and once I stopped the runs of the service would go back to the 3s duration matching `OnCalendar`.

https://gist.github.com/zfjagann/aa3e36820fe9edb472747f3bbf17926c

**Comment by zfjagann** [comment]
Can we document in the manpage that `RemainAfterExit` prevents timers from being triggered periodically, and also the default for `Persistent` which isn't in the manpage at all.

**Comment by zealws** [comment]
Can we document the relationship between `RemainAfterExit` and the periodic timer. It's not clear from the manpage that periodic timers don't work if `RemainAfterExit` is provided.

**Comment by arvidjaar** [comment]
> Each time I ran list-timers (about once per second) it reported that there was less than a second left on the say-hello.timer and re-ran the service. 

I cannot reproduce it, in my case it correctly shows remaining time and start service only when timer expires (subject to some slack in evaluation). I use "minutely" timer. Using openSUSE Tumbleweed (systemd 229).

**Comment by poettering** [comment]
@zfjagann hmm, so how does your timer unit look like now when your an it like in your latest gist?

The output you posted suggests there's once per second timer installed. Note that the AccuracySec= logic (which defaults to 1min) will actually result in never fully accurate timers, unless you turn that to 1us or so...

Note that your timer was started to frequently in that example that the start limit of the service hit, i.e. StartLimitBurst= and StartLimitInterval=, see systemd.service for details.

Or in other words: if you have really high-frequency timers, you need to configure both AccuracySec= and StartLimit*= accordingly. 

And yeah, we should document that explicitly in the man page, and also that you have to turn off RemainAfterExit=.

**Comment by zealws** [comment]
It's running once per second because the timer is configured with `OnCalendar=*:0/3:*`.
It needs to be `OnCalendar=*:0/3:0`. :disappointed:

**Comment by poettering** [comment]
Ah, OK! Then everything is cleared up, right? Closing!
