### ISSUE TITLE
unable to automount overlayfs with upperdir set to mount point

### ISSUE THREAD

**Issue by dffischer** [systemd/systemd#3076]
(I already posted this to the systemd-devel mailinglist, but without any reaction, so I leave it here not to be forgotten.)
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

299
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

Overlayfs automatically mounting over its configured automount point as soon as it is accessed.  This works as long as overlayfs' `upperdir` is distinct from the mount point.
### In case of bug report: Unexpected behaviour you saw

When `upperdir` is equal to the mount point, mounting fails.

```
# systemctl start tmp-upper.automount
# ls /tmp/uppper
ls: cannot open directory '/tmp/upper': No such device 
```

Journalctl also shows a message from the kernel that says `overlayfs: filesystem on '/tmp/upper' not supported`. I suspect that this is because autofs is still mounted at /tmp/upper when the overlayfs tries to establish it as its upperdir.
### In case of bug report: Steps to reproduce the problem

These are the unit files used.

```
# tmp-upper.mount

[Unit]
Description=Overlayfs test mount point

[Mount]
What=overlay
Where=/tmp/upper
Type=overlay
Options=upperdir=/tmp/upperr,lowerdir=/tmp/lower,workdir=/tmp/work
```

```
# tmp-upper.automount

[Unit]
Description=Overlayfs test automount point

[Automount]
Where=/tmp/upper

[Install]
WantedBy=local-fs.target
```

With them present and active and all directories created, the directory can be accessed for testing using `ls`.

```
# mkdir /tmp/{upper,lower,work}
# touch /tmp/upper/a /tmp/lower/b
# systemctl start tmp-upper.automount
# ls /tmp/uppper
```

**Comment by poettering** [comment]
This is a kernel limitation really (as overlayfs doesn't support autofs as backing device), and I am not even sure if this _should_ work... I can see the usecase why you want that, but we cannot really make things work the kernel doesn't allow us to. 

Closing now, please bring this up with the kernel folks first. If they make it work, it should work just like that for us too. And if it doesn't, then please bring it up then again.

Sorry if this is disappointing.

**Comment by dffischer** [comment]
This is in no way disappointing: Now I know that the problem is not in my unit files.

I filed [a corresponding bug against the kernel](https://bugzilla.kernel.org/show_bug.cgi?id=117341).
