### ISSUE TITLE
systemd-tmpfiles deletes open files

### ISSUE THREAD

**Issue by baryluk** [systemd/systemd#30760]
### systemd version the issue has been seen with

252

### Used distribution

Centos 9

### Linux kernel version used

5.14.0-391.el9.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

Hard to say if bug, but this a very surprising behavior, mostly because it differs from traditional Unix and Linux behavior.

I have (non-systemd manage) software putting small files in `/tmp` for purpose of locking and managing runtime state. Some of these files are empty or just few bytes in size. They need to be there until machine reboots (after that, they can stay or be removed - doesn't matter).  These programs usually runs for weeks or months non-stop. Some of these files are created (and possibly locked using advisory locks), and then usually not modified.

But because of `systemd-tmpfiles` (which is new to me), and its default rules, it will automatically delete files after 10 days.

This breaks locking semantic in the software, as now second process can start, create a lock file (atomically), but it will be a different inode, so locking will success, possibly causing data corruption in other data structures (on disk and shared memory) software manages.

This should be communicated better, because it did bite us and differs from pre-systemd days.

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html

says:

> The /tmp directory must be made available for programs that require temporary files.
> 
> Programs must not assume that any files or directories in /tmp are preserved between invocations of the program.
Rationale
> 
> IEEE standard POSIX.1-2008 lists requirements similar to the above section.
> 
> Although data stored in /tmp may be deleted in a site-specific manner, it is recommended that files and directories located in /tmp be deleted whenever the system is booted.
> 
> FHS added this recommendation on the basis of historical precedent and common practice, but did not make it a requirement because system administration is not within the scope of this standard.

The Open Group Base Specifications Issue 7, 2018 edition

Section 10.1 says

> /tmp
>    A directory made available for applications that need a place to create temporary files. Applications shall be allowed to create files in this directory, but shall not assume that such files are preserved between invocations of the application. 

The issue is that one can imply from this that at least open files will not be deleted.

For us, we would want to preserve these files (until reboot), even if they are not open. (the ones that are open are most critical to NOT be deleted, otherwise data corruption will happen; the ones that are not open possibly could be deleted, but we would prefer not. It is hard to detect if the file is open or not and perform deletion in an atomic fashion, but at least some effort could be made to detect this).

As implemented, it makes `/tmp` quite unusable for anything, until ones takes extra assumption how long file are preserved. I.e. one cannot even use this directory from bash, because files just can disappear there anytime.

Out of the box I do not see any reasonable default location, that has "classic" semantic. There is `/run/lock`, but it is kind of deprecated (defined in `/usr/lib/tmpfiles.d/legacy.conf`), and only suitable for small files. It is ok for our use case (we do want it to be on tmpfs and small). But it is not suitable for small non-lock state.

We cannot use `/var/lib` due to permission issues, and because it is not on `tmpfs` usually.

An indirect indication that is not the only case, can be seen in some packages overwriting default behaviour, ie. `/usr/lib/tmpfiles.d/podman.conf` to prevent containers running for days, from having their files removed by systemd-tmpfiles.

Looking at default configuration of `tmpfiles.d` there is no suitable directory available by default to use with "classic" semantic. Manual page of `tmpfiles.d` does not provide suitable guidance on this either.

PS. We cannot use `RuntimeDirectory`, `StateDirectory`, because our software is not managed (and cannot be) by systemd.

### Unexpected behaviour you saw

See above

### Steps to reproduce the problem

See above

**Comment by bluca** [comment]
/run is for runtime state. Given /tmp is world writable by default, it's not a great to use it for critical operational runtime state. Anyway, you can simply mask the cleanup tmpfiles.d by creating an empty file or a symlink to dev/null in `/etc/tmpfiles.d/tmp.conf`, and no cleanup of /tmp will occur (assuming no other tmpfiles.d creates such rules, but you can check that easily

**Comment by poettering** [comment]
/tmp/ is not a suitable place for lock files. Use /run/ for that (if this is system-level code) or $XDG_RUNTIME_DIR (if this is user-level code). They are not subject to automatic clean-up.

Also see https://systemd.io/TEMPORARY_DIRECTORIES which explains in a ton of detail how the expected semantics are and how to use these dirs and for what.

I don't think we should change anything here, in particular as these semantics have been commonplace on many distros since about forever, on rh based distros for example via the tmpwatch logic that preceeded tmpfiles. Or in other words: there *never* was a time where leaving around files in /tmp/ forerver was universally accepted.

**Comment by poettering** [comment]
Note btw, that using /tmp/ for lock files kinda implies you have a guessable filename. But that's a local DoS because any app can take arbitrary names and thus block your software from running.

Please let me know which software we are talking about, so that I can file the appropriate CVE. ;-)

(No, please don't, this is a joke. Not a believer in the CVE process anyway.)

**Comment by baryluk** [comment]
@poettering 

> I don't think we should change anything here,

Agreed. I just thing it is rather surprising.

I will read a bit more, and see if `/run` (preferably without extra subdirectory) would work.

> Note btw, that using /tmp/ for lock files kinda implies you have a guessable filename.
>
> Please let me know which software we are talking about, so that I can file the appropriate CVE. ;-)

It is a custom software, and machine access is restricted, so all users (or processes of that machine) on that machine are free to read these files without any security issues. So no worries.


Thanks for the quick response.

**Comment by bluca** [comment]
The issue is not that they are readable, but that any unprivileged process can create the lock file ahead of time and keep it locked forever to cause a DOS.

**Comment by poettering** [comment]
> It is a custom software, and machine access is restricted, so all users (or processes of that machine) on that machine are free to read these files without any security issues. So no worries.

The problem is that guessable names can be taken by anyone before your software starts (/tmp/ is world-writable) and thus block your software from running, or even worse pass data to your clients pretending it was your software even though it isn't.

Basically, using /tmp/ is only safe if you use an API such as mkostemp() or similar which generates unguessable names in /tmp/. If you use fixed names you immediately lost and are vulnerable.

**Comment by baryluk** [comment]
So, unfortunately `/var/run` (aka `/run`) cannot be used. It is owned by root, and not writable by others. Same issue also with `/var/run/lock`.



> The problem is that guessable names can be taken by anyone before your software starts (/tmp/ is world-writable) and thus block your software from running, or even worse pass data to your clients pretending it was your software even though it isn't.

Not a concern.

I want it to be world writable.

> Basically, using /tmp/ is only safe if you use an API such as mkostemp() or similar which generates unguessable names in /tmp/. If you use fixed names you immediately lost and are vulnerable.

Not a concern either.

**Comment by baryluk** [comment]
I will put them in `/dev/shm/` for the time being. That is appears to be the only reliable and reasonably portable way.

**Comment by poettering** [comment]
> So, unfortunately `/var/run` (aka `/run`) cannot be used. It is owned by root, and not writable by others. Same issue also with `/var/run/lock`.

`/var/run` is an obsolete alias to `/run/. Do not use.

Is this for a system service? then make pid1 create a subdir with the approproate privs via RuntimeDirectory=.

Is this for user code? then use $XDG_RUNTIME_DIR.

**Comment by poettering** [comment]
> Not a concern.
> 
> I want it to be world writable.
> 
> > Basically, using /tmp/ is only safe if you use an API such as mkostemp() or similar which generates unguessable names in /tmp/. If you use fixed names you immediately lost and are vulnerable.
> 
> Not a concern either.

Please let me know which software this is for, so that I can ask for a CVE ;-)

**Comment by poettering** [comment]
> I will put them in `/dev/shm/` for the time being. That is appears to be the only reliable and reasonably portable way.

/dev/shm is the backend for shm_open(), i.e. POSIX shared memory. Don't use it for anything else.

It's cleaned up by RemoveIPC= in service files as well as the option by the same name in logind.conf for regular users.

**Comment by baryluk** [comment]
> > So, unfortunately `/var/run` (aka `/run`) cannot be used. It is owned by root, and not writable by others. Same issue also with `/var/run/lock`.
> 
> `/var/run` is an obsolete alias to `/run/. Do not use.
> 
> Is this for a system service? then make pid1 create a subdir with the approproate privs via RuntimeDirectory=.
> 
> Is this for user code? then use $XDG_RUNTIME_DIR.

It is user code, running as a daemon (but they are frequently stopped and started, and new ones are started, old ones are stopped and never run again, etc. Very dynamic environment.).

Runs as normal user. (not a root). Or multiple users.

```
$ env | grep XDG_RUNTIME_DIR
$ 
```

nope.

Even if I assume it is `/run/user/$UID`, this is still nope, for few reasons: 1) Requires extra logic (i.e. read env variables), 2) In our case different components run as different users, yet they need to be able to access common locks, so they need to be in more universal place, than per-user directory.

> /dev/shm is the backend for shm_open(), i.e. POSIX shared memory. Don't use it for anything else.

It is used for shared memory in the code, but we need extra files for locks (and single lock on the shared memory file itself is not sufficient, because we support multiple concurrent lock).

> It's cleaned up by RemoveIPC= in service files as well as the option by the same name in logind.conf for regular users.

Very unfortunate if true. We were using manually (using `shm_open()`) created files in `/dev/shm/` for years (primarly Centos 8 and Centos 9, but also various Fedora 3x systems), without issues. They do not appear to be cleaned by anything. But this is probably because `RemoveIPC` only performs cleanup if all processes of the user terminate, and user session is stopped. That is mostly fine for both usage in this case.

> Please let me know which software this is for, so that I can ask for a CVE ;-)

:)

I understand, for generic software, or multi-user servers, using such pattern might not be suitable and be a security problem. But this system have different trust model. If you can log into a machine running this code as any user, it is already game over, and `/tmp`, `/dev/shm` or DoS is really least of our worries.



I want a consistent portable location that: works out of the box, is world writable, is not automatically cleaned by anything until reboot, is in memory.

**Comment by rrauenza** [comment]
This seems to affect tmux, too.  tmux sessions greater than 10 days can have their /tmp/tmux-12345 socket files removed.

I didn't see open files specifically addressed in here, but is the team open to skipping files that are currently opened by another process?   

To @baryluk , I'm confused because the docs say that locked files are skipped.  Are you flock()ing your lock files, or just using its existence?   

>  Note that while the aging algorithm is run a 'shared' BSD file lock (see flock(2)) is taken on each directory the algorithm descends into (and each directory below that, and so on). If the aging algorithm finds a lock is already taken on
>        some directory, it (and everything below it) is skipped. Applications may use this to temporarily exclude certain directory subtrees from the aging algorithm: the applications can take a BSD file lock themselves, and as long as they keep
>        it aging of the directory and everything below it is disabled.

Oh -- it only honors locked directories...  Maybe you can put your locks in a locked subdir?

**Comment by poettering** [comment]
> This seems to affect tmux, too. tmux sessions greater than 10 days can have their /tmp/tmux-12345 socket files removed.

Please fix tmux to not place socket inodes in /tmp/. terrible idea. Use XDG_RUNTIME_DIR for that.

**Comment by rrauenza** [comment]
>Please fix tmux to not place socket inodes in /tmp/. terrible idea. Use XDG_RUNTIME_DIR for that.

Tmux is not my project, so it is not my call.

Is the team open to skipping files that are currently opened by another process?  That sounded like a no?

**Comment by daandemeyer** [comment]
> >Please fix tmux to not place socket inodes in /tmp/. terrible idea. Use XDG_RUNTIME_DIR for that.
> 
> Tmux is not my project, so it is not my call.
> 
> Is the team open to skipping files that are currently opened by another process?  That sounded like a no?

flock() the socket fd and tmpfiles will skip it. But like @poettering said, /tmp is not the place for sockets.

**Comment by poettering** [comment]
Maybe file an issue against tmux, asking them to move the socket.

There is no sane api on linux to determine whether a file is opened by any other process, hence what you are asking is not really feasible, sorry.

This behaviour has been like this for a decade or more, how come this wasn't noticed in all those years?

**Comment by rrauenza** [comment]
> This behaviour has been like this for a decade or more, how come this wasn't noticed in all those years?

No idea.

Yeah, I think I read /usr/bin/tmpwatch doesn't even try to do the API.  It fork's /usr/bin/fuser, which I find not ideal, adding a dependency.

I filed a bug for them to flock() the parent directory of their socket ..
