### ISSUE TITLE
Add `DeviceAllow=~` or `DeviceDeny`

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#30780]
### Component

systemctl, systemd

### Is your feature request related to a problem? Please describe

I'm creating a service which explicitly shouldn't access some specific devices, in this case `@char-tty` & `@char-/dev/console`, but should be able to access anything else. However, `DeviceAllow` doesn't provide any form of negation, `DeviceAllow=~@char-tty` isn't recognised.

### Describe the solution you'd like

Allowing `DeviceAllow=~`, or adding `DeviceDeny=`, (whichever is more appropriate) as an available option would solve this issue.

### Describe alternatives you've considered

The only other alternative is adding `DeviceAllow` lines for every device, which isn't future proof in case new character devices are added (globbing helps in the case of `@block-*`, but not anywhere else).

### The systemd version you checked that didn't have the feature you are asking for

255.2-1

**Comment by Winterhuman** [comment]
Unfortunately no, `DevicePolicy` can only configure an allowlist of `DeviceAllow`s, and can't be used for denylists.

**Comment by Werkov** [comment]
cgroup v1 had both `devices.allow` and `devices.deny`, that was difficult to evaluate. (Re)adding a denylist sounds like going in circles to me.

> should be able to access anything else

You really cannot determine what the service would need for its operation?

> isn't future proof in case new character devices are added 

The service would need other adjustments besides `DeviceAllow=` if such an event occurred. If not, the new device could generally also be similar to TTYs and suddenly the service would be allowed what it was originally denied. (This is a far-fetched reasoning but it illustrates why allowlist is preferable to denylist.)

**Comment by Winterhuman** [comment]
The service contains a user-facing shell, so I can't really know ahead of time what devices are needed, besides the TTY not being needed (it's a VT-less service that uses framebuffers). If you have an alternative for hiding the TTY and `console` devices from a service, `InaccessiblePaths=` didn't work for me, I'd happily use that.

I agree that allowlists are preferable in nearly all cases for security, however, the alternative of specifying every other `char-*` device when it could be as simple as `DeviceAllow=~@char-tty @char-/dev/console` seems tedious. That being said, you have reminded me that `DeviceAllow=` takes more than just devices (e.g. `@char-tty [rwm]`), which yeah, trying to parse that *with* negation in the equation sounds trickier than I first realised.

**Comment by Winterhuman** [comment]
Closing issue. Parsing the device options with negation sounds like a nightmare to handle, and generally speaking, user-facing shells inside services isn't a standard thing to do anyway.
