### ISSUE TITLE
Add specifier for user home directory that respects `User=` setting of unit

### ISSUE THREAD

**Issue by LunarLambda** [systemd/systemd#30782]
### Component

systemd

### Is your feature request related to a problem? Please describe

On my systems I tend to relocate `XDG_CONFIG_HOME` to `~/cfg` for convenience since I make frequent edits.

For the systemd user instance, there exists a chicken-and-egg problem: systemd will load units, environment.d files, etc, from XDG_CONFIG_HOME, but who tells it where that is?

I can set it in `~/.config/environment.d`, but now I have a mostly empty `.config` directory just for telling systemd my config directory is somewhere else.

I found that I can add an drop-in file for `user@UID.service` to set `Environment=XDG_CONFIG_HOME=...`, and that works perfectly, but I have to specify an absolute path. I thought `%h/cfg` would work, but as the manpage explains, `%h` is with respect to the user executing the unit (i.e. `root` for the systemd user instance), not the `User=` setting.

As I understand, systemd allows subtituting `$HOME` with respect to `User=` in settings like `ExecStart=`, but since `Environment=` doesn't allow variable substitution, this means there's no way to substitute the `User=`'s home directory in environment variables for the service, except maybe through wrapping `ExecStart=` in `/usr/bin/env` invocation, which is highly messy.

This doesn't affect user units, which will be run by the user manager and thus have the correct `%h` specifier, but it affects any system unit (including `user@.service`) that wants to execute as another user.

### Describe the solution you'd like

It would be nice to have a specifier or other mechanism to define `User=`-home-relative environment variables for a service. The other specifiers that are affected by this are `%u` and `%s`, but those are exposed via `$USER` and `$SHELL` in `ExecStart=`, and aren't commonly used to compose other environment variables, so I only care for `%h`.

### Describe alternatives you've considered

Using an absolute path in `Environment=`:
```
[Service]
Environment=XDG_CONFIG_HOME=/home/myuser/cfg
```
Overriding `ExecStart=`:
```
[Service]
ExecStart=/usr/bin/env XDG_CONFIG_HOME=$HOME/cfg /usr/lib/systemd/systemd --user
```
Writing a `/etc/systemd/user-environment-generators/` script, but this requires special care to check against the name/uid of the user, and isn't as declarative as a service drop-in file.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
specifiers are resolved as the config file lines are parsed. User= might appear after the first %h use, and it cannot look forward. In addition we can't do NSS from PID 1 (i.e. not resolve users), since those are typically managed by services that systemd itself manages, and we really want to avoid that PID 1 is client to the services it actually manages.

my recommendation, set this from pam, with pam_environment or a similar thing.

with homed you can use "homectl --setenv=" to set arbitrary env vars for your users.

**Comment by drws** [comment]
> User= might appear after the first %h use, and it cannot look forward. In addition we can't do NSS from PID 1 (i.e. not resolve users)

All this reads as if `%h` is so limited in system context that it should only return the root's home or possibly be removed altogether and only be available in user context (if preventing as much user errors in system units as possible is desired). Perhaps another letter could be used for root's home, and it could also be available in user units if deemed useful.
