### ISSUE TITLE
Overrides named 80-container-www[digit].network is ignored

### ISSUE THREAD

**Issue by parsko** [systemd/systemd#30810]
### systemd version the issue has been seen with

255.2-1

### Used distribution

Arch

### Linux kernel version used

6.6.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

To set network configuration for nspawn containers I create a file /etc/systemd/network/80-container-<container name>.network

-------------------
from /lib/systemd/network/80-container-ve.network
-------------------

To make local modifications, one of the following methods may be used:
1. add a drop-in file that extends this file by creating the
   /etc/systemd/network/80-container-ve.network.d/ directory and creating a
   new .conf file there.
2. copy this file into /etc/systemd/network or one of the other paths checked
   by systemd-networkd and edit it there.

### Unexpected behaviour you saw

If you name the container www2, www3, etc. it gets the default config from /lib/systemd/network/80-container-ve.network for some strange reason. All other names I tried works as intended.

### Steps to reproduce the problem

1. Create nspawn container called "www2"
2. Create file /etc/systemd/network/80-container-www2.network with some special config
3. Start container and bring up the interface in the container

**Comment by yuwata** [comment]
That's expected, as '-ve' is alphanumerically earlier than '-www2'.
When you want to create a custom .network file, then please use smaller prefix number, e.g. `30-container-www2.network`.

**Comment by parsko** [comment]
D'oh! I blindly followed a guide and apparently need to go to bed now.

Sorry for wasting your time!
