### ISSUE TITLE
Settings MACAddressPolicy=none and MACAddress=none does not result in bridge using correct mac address

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#30813]
### systemd version the issue has been seen with

systemd 252 (252.5-2ubuntu3.2)

### Used distribution

Ubuntu 23

### Linux kernel version used

6.2.0-1017-oracle

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

I expect the bridge to come up with the mac address of the NIC.

### Unexpected behaviour you saw

 I have to set MACAddressPolicy=none in /usr/lib/systemd/network/99-default.link for the bridge to come up with the hardware address of the nic.

### Steps to reproduce the problem

I am trying to bring up a bridge on a virtual machine which gets its address from a DHCP server.

It appears that the DHCP server expects the mac address to NOT be a randomly assigned mac address, which is what I understand systemd does by default.

Thus I must either hard code the correct mac address for the bridge or find a way to configure the bridge with the mac address of the network interface.

I have read that setting MACAddressPolicy=none in the link file for the bridge and settings MACAddress=none in the netdev file for the bridge does this, but those changes seem to have no effect.

Instead, I have to set MACAddressPolicy=none in /usr/lib/systemd/network/99-default.link

I would have expected the code below to work without the need to  set MACAddressPolicy=none in /usr/lib/systemd/network/99-default.link

```
#!/bin/bash

# Set MACAddressPolicy to none in /usr/lib/systemd/network/99-default.link
# PROBLEM!  THIS ENTIRE CONFIGURATION ONLY WORKS IF THIS LINE IS PRESENT ---->  WHY?
sed -i 's/MACAddressPolicy.*/MACAddressPolicy=none/' /usr/lib/systemd/network/99-default.link

# Create a custom .link file for br0 to set MACAddressPolicy to none
# refer: https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#MACAddress=
cat <<EOF > /etc/systemd/network/br0.link
[Link]
MACAddressPolicy=none
EOF

# the bridge cannot have a random mac address assigned by systemd or it will not get its address from DHCP
# refer: https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#MACAddress=
cat <<EOF > /etc/systemd/network/br0.netdev
[NetDev]
Name=br0
Kind=bridge
MACAddress=none
EOF

cat <<EOF > /etc/systemd/network/br0.network
[Match]
Name=br0

[Network]
DHCP=yes
DNS=8.8.8.8
DNS=8.8.4.4

#[Link]
# IMPORTANT!
# systemd will allocate a random mac address to the bridge and this causes a problem because 
# the DHCP server then does not give the bridge an IP address
# so we set the MAC address to the actual address
#MACAddress=$(ip link show ens3 | awk '/ether/ {print $2}')
EOF

cat <<EOF > /etc/systemd/network/ens3.network
[Match]
Name=ens3

[Network]
Bridge=br0
EOF
```

**Comment by yuwata** [comment]
It is not necessary to modify 99-default.link.

Please prefix br0.link (and possibly .network and friends) with a digits, e.g. `10-br0.link`, `10-br0.network`.

From systemd.link(5):
> All configuration files are collectively sorted and processed in alphanumeric order, regardless of the directories in which they live. However, files with identical filenames replace each other. It is recommended that each filename is prefixed with a number smaller than "70" (e.g.  10-eth0.link). Otherwise, the default .link files or those generated by systemd-network-generator.service(8) may take precedence over user configured files.

**Comment by bootrino** [comment]
There's alot to know.

**Comment by bootrino** [comment]
I made the changes you suggest as follows but the problem is not fixed.  Any other suggestions?

Also I read here https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html that 

"Drop-in files in /etc/ take precedence over those in /run/ which in turn take precedence over those in /usr/lib/. Drop-in files under any of these directories take precedence over the main network file wherever located."

So, given the order of precedence above, can you help me understand why I would need to prefix the networkd files with "10-"

```
#!/bin/bash

# Set MACAddressPolicy to none in /usr/lib/systemd/network/99-default.link
# PROBLEM!  THIS ENTIRE CONFIGURATION ONLY WORKS IF THIS LINE IS PRESENT ---->  WHY?
#sed -i 's/MACAddressPolicy.*/MACAddressPolicy=none/' /usr/lib/systemd/network/99-default.link
#sed -i 's/MACAddressPolicy.*/MACAddressPolicy=persistent/' /usr/lib/systemd/network/99-default.link

# Create a custom .link file for br0 to set MACAddressPolicy to none
# refer: https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#MACAddress=
cat <<EOF > /etc/systemd/network/10-br0.link
[Link]
MACAddressPolicy=none
EOF

# the bridge cannot have a random mac address assigned by systemd or it will not get its address from DHCP
# refer: https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#MACAddress=
cat <<EOF > /etc/systemd/network/10-br0.netdev
[NetDev]
Name=br0
Kind=bridge
MACAddress=none
EOF

cat <<EOF > /etc/systemd/network/10-br0.network
[Match]
Name=br0

[Network]
DHCP=yes
DNS=8.8.8.8
DNS=8.8.4.4

#[Link]
# IMPORTANT!
# systemd will allocate a random mac address to the bridge and this causes a problem because
# the DHCP server then does not give the bridge an IP address
# so we set the MAC address to the actual address
#MACAddress=$(ip link show ens3 | awk '/ether/ {print $2}')
EOF

cat <<EOF > /etc/systemd/network/11-ens3.network
[Match]
Name=ens3

[Network]
Bridge=br0
EOF


```

**Comment by yuwata** [comment]
10-br0.link does not have [Match] section. E.g.,
```
[Match]
Kind=bridge
```

**Comment by bootrino** [comment]
Apologies but I still can't get it working with the changes you suggest.  Here's the config that is the result of my script above:

ubuntu@instance-20240108-0822:~$ ls /etc/systemd/network/*

```
/etc/systemd/network/10-br0.link    
/etc/systemd/network/10-br0.network
/etc/systemd/network/10-br0.netdev  
/etc/systemd/network/10-ens3.network
```

ubuntu@instance-20240108-0822:~$ cat /etc/systemd/network/10-br0.link

```
[Link]
MACAddressPolicy=none

[Match]
Kind=bridge
```

ubuntu@instance-20240108-0822:~$ cat /etc/systemd/network/10-br0.network 

```
[Match]
Name=br0

[Network]
DHCP=yes
DNS=8.8.8.8
DNS=8.8.4.4

#[Link]
# IMPORTANT!
# systemd will allocate a random mac address to the bridge and this causes a problem because
# the DHCP server then does not give the bridge an IP address
# so we set the MAC address to the actual address
#MACAddress=02:00:17:00:8c:56
```

ubuntu@instance-20240108-0822:~$ cat /etc/systemd/network/10-br0.netdev 

```
[NetDev]
Name=br0
Kind=bridge
MACAddress=none
```

ubuntu@instance-20240108-0822:~$ cat /etc/systemd/network/10-ens3.network 

```
[Match]
Name=ens3

[Network]
Bridge=br0
```

**Comment by yuwata** [comment]
The setting should work. I added explicit test case in #30858. The test pass at least on my local machine.

Note, .link and .netdev files are applied only when the interface is created. If the interface already exists, changing these files does not take any effect.

Please try the following steps:
```sh
# reload .link file(s) by udevd
$ sudo udevadm control --reload
# remove existing bridge interface
$ sudo ip link del br0
# restart networkd, to make the bridge interface created again
$ sudo systemctl restart systemd-networkd.service
```
If the above does not work, then please show `networkctl status br0`, and check the expected .link file is applied to the interface.
Also, there exists no other conflicting .netdev file that also try to create `br0`.

**Comment by alvarofernandezavalos** [comment]
Thank you @yuwata ! Works like a charm.
