### ISSUE TITLE
70-mouse.hwdb trust gxt 152 DPI

### ISSUE THREAD

**Issue by FedeDP** [systemd/systemd#3082]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 229 on archlinux

Following instructions here: http://who-t.blogspot.it/2014/12/building-a-dpi-database-for-mice.html?m=1 , here are my collected data for my "trust illuminated mouse gxt 152".
Here they are:
mouse:usb:v145fp01ac:name:HID-compliant Mouse Trust Gaming Mouse:
 MOUSE_DPI=*800@528 1200@537 1600@536 2400@521

Thank you very much @whot for your post!

**Comment by poettering** [comment]
Any chance you can post this as proper PR? If you do it will nicely attributed to you, and you'll show up in the NEWS and everything!

**Comment by FedeDP** [comment]
You surely know how to properly tempt people :D 
I'm gonna make it asap.
Thank you very much!

**Comment by poettering** [comment]
#3085 got merged. Closing this one.
