### ISSUE TITLE
ConditionCPUFeature false negative with avx2, bmi1, and bmi2

### ISSUE THREAD

**Issue by kiplingw** [systemd/systemd#30822]
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu Mantic (23.10)

### Linux kernel version used

6.5.0-14-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Service unit starts.

### Unexpected behaviour you saw

systemd emits says that my service "was skipped because of an unmet condition check (ConditionCPUFeature=X)". Where X is avx2, bmi1, and bmi2.

### Steps to reproduce the problem

My service unit has the following in it:

```
...

ConditionCPUFeature=avx
ConditionCPUFeature=avx2
ConditionCPUFeature=bmi1
ConditionCPUFeature=bmi2
```

My CPU supports all four:

```
...

processor	: 15
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 113
model name	: AMD Ryzen 7 3700X 8-Core Processor
stepping	: 0
microcode	: 0x8701030
cpu MHz		: 2580.002
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips	: 7186.37
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

The service will only start if I comment out the stanzas for avx2, bmi1, and bmi2, despite my CPU clearly supporting all four and all four being [supported](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#ConditionCPUFeature=) by systemd. This might be related to #23075.

**Comment by yuwata** [comment]
-> #30828.

**Comment by kiplingw** [comment]
Thanks @yuwata. Just to confirm, users can expect this fix in systemd version >= 257?

**Comment by yuwata** [comment]
> Thanks @yuwata. Just to confirm, users can expect this fix in systemd version >= 257?

The patch will be backported. Please wait for new stable releases.

**Comment by kiplingw** [comment]
I'm using Ubuntu Mantic (23.10) which ships systemd 253. Do you expect the patch to be backported to Mantic?

**Comment by yuwata** [comment]
> I'm using Ubuntu Mantic (23.10) which ships systemd 253. Do you expect the patch to be backported to Mantic? And thank you for the quick patch.

I am not familiar with update processes of Ubuntu and any downstream. But, @bluca still manages v253 tree in upstream (https://github.com/systemd/systemd-stable). So, I guess the patch will come to Ubuntu.
