### ISSUE TITLE
dnssec: systemd-resolved failure to resolve ams-sga.cra-arc.gc.ca

### ISSUE THREAD

**Issue by rocketraman** [systemd/systemd#30856]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39

### Linux kernel version used

6.6.7-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

The domain `ams-sga.cra-arc.gc.ca` (Revenue Canada) should resolve normally.

### Unexpected behaviour you saw

I have intermittent resolution failures with `ams-sga.cra-arc.gc.ca` (Revenue Canada).

```
resolvectl query ams-sga.cra-arc.gc.ca
Name 'ams-sga.cra-arc.gc.ca' not found`
```

Adding `gc.ca` as a dnssec negative trust anchor appears to fix the problem, but its hard to say because the problem is intermittent.

Nothing was found in `journalctl` when the problem occurred and I cannot replicate it.

**Comment by rocketraman** [comment]
> you have dnssec enabled i presume?

Yes, this appears to be a dnssec issue. I noted:

> Adding gc.ca as a dnssec negative trust anchor appears to fix the problem, but its hard to say because the problem is intermittent.

**Comment by rocketraman** [comment]
@rpigott Do you think that PR would resolve this as well?

**Comment by rpigott** [comment]
Yes.
