### ISSUE TITLE
Systemd.path not triggering systemd.service

### ISSUE THREAD

**Issue by EdiDD** [systemd/systemd#30888]
### systemd version the issue has been seen with

252.19

### Used distribution

Debian

### Linux kernel version used

kernel 6.1

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

Want to execute service when  **/proc/self/mounts** changes. Can't find a good way to execute service if mount point is lost eg. because of systemd.automount `TimeoutIdleSec=`      
`ConditionPathIsMountPoint=!/some/path` `is not working for some reason.

### Unexpected behaviour you saw

systemd.path disregard /proc/self/mounts for monitoring changes
`PathModified=/proc/self/mounts`     
Systemd.path is not executing service file

**Comment by poettering** [comment]
inotify is only really supported for files where users make changes to. it doesn't work for virtual files such as those exposed by procfs, whose contents is only generated on demand when somebody reads()s from them.

This is not a limitation of systemd, but one of the Linux kernel.

Sorry, we cannot fix this.

**Comment by EdiDD** [comment]
@poettering Thank you for fast reply. Is there a better way than **systemd timer** for monitoring unmounted disk and than taking some service action ?

**Comment by poettering** [comment]
systemd exposes all mounts as .mount units.
