### ISSUE TITLE
systemd-executor moving its cgroup late makes journald log incorrect cgroup metadata

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#30886]
First of all, I suspect this is a kernel issue (especially given that downgrading the kernel fixes it), I just want to make sure before reporting it further.

Long story short, yesterday the Rawhide systemd job started suddently failing, and after a quite painful amount of time I managed to isolate it to the following reproducer:

```
# systemctl log-level debug
# systemd-run -u foo.service --service-type=exec --wait echo foo
Running as unit: foo.service; invocation ID: f515da7a30e849e9bdadfb4176598431
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 4ms
CPU time consumed: 3ms
Memory peak: 328.0K
Memory swap peak: 0B
# journalctl -o export -t echo
__CURSOR=s=cdd8ebb3ec5143028a56299e2de9a784;i=8e11;b=dcf281458b334429b394105286c2983f;m=f37cbf667;t=60ead61600ee8;x=6421f6cd59b317d5
__REALTIME_TIMESTAMP=1704987686080232
__MONOTONIC_TIMESTAMP=65360623207
__SEQNUM=36369
__SEQNUM_ID=cdd8ebb3ec5143028a56299e2de9a784
_BOOT_ID=dcf281458b334429b394105286c2983f
SYSLOG_FACILITY=3
PRIORITY=6
_UID=0
_GID=0
_SELINUX_CONTEXT=kernel
_MACHINE_ID=1cc2313b3a074e32a4d61133e2586a5f
_HOSTNAME=localhost.localdomain
_RUNTIME_SCOPE=system
_CAP_EFFECTIVE=1ffffffffff
_SYSTEMD_CGROUP=/init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_SLICE=-.slice
_PID=668859
_COMM=(echo)
_EXE=/usr/lib/systemd/systemd-executor
_CMDLINE="(echo)"
_TRANSPORT=stdout
_STREAM_ID=8ddacbd6a72e4a409457eb93080e47f0
SYSLOG_IDENTIFIER=echo
MESSAGE=foo
```

Notice the incorrect `_SYSTEMD_*` fields. For comparison, this is with info log level, on the same kernel version:

```
 journalctl -o export -t echo
__CURSOR=s=cdd8ebb3ec5143028a56299e2de9a784;i=8e4a;b=dcf281458b334429b394105286c2983f;m=f3dbcfacf;t=60ead67511350;x=2c5494b401957133
__REALTIME_TIMESTAMP=1704987785761616
__MONOTONIC_TIMESTAMP=65460304591
__SEQNUM=36426
__SEQNUM_ID=cdd8ebb3ec5143028a56299e2de9a784
_BOOT_ID=dcf281458b334429b394105286c2983f
SYSLOG_FACILITY=3
PRIORITY=6
_UID=0
_GID=0
_SELINUX_CONTEXT=kernel
_SYSTEMD_SLICE=system.slice
_MACHINE_ID=1cc2313b3a074e32a4d61133e2586a5f
_HOSTNAME=localhost.localdomain
_RUNTIME_SCOPE=system
_CAP_EFFECTIVE=1ffffffffff
_TRANSPORT=stdout
_STREAM_ID=96c4efda83814352a95ce63c82aac726
SYSLOG_IDENTIFIER=echo
MESSAGE=foo
_PID=668878
_COMM=echo
_SYSTEMD_CGROUP=/system.slice/foo.service
_SYSTEMD_UNIT=foo.service
_SYSTEMD_INVOCATION_ID=6b83f1163aa043189527b0c1a3ed5f8c
```

A couple of important points:
  - this seems to happen only with kernel 6.8 (I tried it with `kernel-core-6.8.0-0.rc0.20240109git9f8413c4a66f.1.fc40.x86_64` and `kernel-core-6.8.0-0.rc0.20240110gitab27740f7665.4.fc40.x86_64`); downgrading to `kernel-core-6.7.0-68.fc40.x86_64` makes the issue go away
  - this happens only with debug logging enabled; switching to info level makes it go away even with kernel 6.8
  - it's intermittent (doesn't happen always, but still quite frequently)

**Comment by mrc0mmand** [comment]
Hmmm, on the other hand, if I build systemd v254 on the same machine, the issue goes away as well, so I'm not really sure who to blame here.

**Comment by mrc0mmand** [comment]
With:
```bash
#!/bin/bash
set -eu
set -o pipefail

systemctl log-level debug
systemctl log-level
uname -r
systemctl --version

for i in {0..31}; do
        CURSOR="$(journalctl --show-cursor -n0 -q | awk '{print $3}')"
        systemd-run -q -u "test$i.service" --service-type=exec --wait echo hello
        journalctl --sync
        journalctl --cursor="$CURSOR" -o export -t echo | grep "_SYSTEMD_UNIT="
done
```

latest main:
```
debug
6.8.0-0.rc0.20240110gitab27740f7665.4.fc40.x86_64
systemd 255 (255-1031-g3df2b71)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test1.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test3.service
_SYSTEMD_UNIT=test4.service
_SYSTEMD_UNIT=test5.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test9.service
_SYSTEMD_UNIT=test10.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test12.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test21.service
_SYSTEMD_UNIT=test22.service
_SYSTEMD_UNIT=test23.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=test27.service
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
_SYSTEMD_UNIT=init.scope
```

v254:
```
debug
6.8.0-0.rc0.20240110gitab27740f7665.4.fc40.x86_64
systemd 254 (254)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
_SYSTEMD_UNIT=test0.service
_SYSTEMD_UNIT=test1.service
_SYSTEMD_UNIT=test2.service
_SYSTEMD_UNIT=test3.service
_SYSTEMD_UNIT=test4.service
_SYSTEMD_UNIT=test5.service
_SYSTEMD_UNIT=test6.service
_SYSTEMD_UNIT=test7.service
_SYSTEMD_UNIT=test8.service
_SYSTEMD_UNIT=test9.service
_SYSTEMD_UNIT=test10.service
_SYSTEMD_UNIT=test11.service
_SYSTEMD_UNIT=test12.service
_SYSTEMD_UNIT=test13.service
_SYSTEMD_UNIT=test14.service
_SYSTEMD_UNIT=test15.service
_SYSTEMD_UNIT=test16.service
_SYSTEMD_UNIT=test17.service
_SYSTEMD_UNIT=test18.service
_SYSTEMD_UNIT=test19.service
_SYSTEMD_UNIT=test20.service
_SYSTEMD_UNIT=test21.service
_SYSTEMD_UNIT=test22.service
_SYSTEMD_UNIT=test23.service
_SYSTEMD_UNIT=test24.service
_SYSTEMD_UNIT=test25.service
_SYSTEMD_UNIT=test26.service
_SYSTEMD_UNIT=test27.service
_SYSTEMD_UNIT=test28.service
_SYSTEMD_UNIT=test29.service
_SYSTEMD_UNIT=test30.service
_SYSTEMD_UNIT=test31.service
```

**Comment by mrc0mmand** [comment]
I can track this down all the way back to bb5232b6a3b8af075ee06cc87416e5f49a6170d3 which introduced sd-executor, i.e. with bb5232b6a3b8af075ee06cc87416e5f49a6170d3 I get "incorrect" metadata, and with a commit before it (56df7a461f05b39851e9f95581cd6f6c66dc3b22) I get the "expected" stuff.

**Comment by YHNdnzj** [comment]
My guess is that this is similar to #11187, i.e. we should move to the target cgroup even earlier 🤔

**Comment by bluca** [comment]
The cgroup attach in the child is done quite late in exec_invoke, any reason for that or can we move it up? https://github.com/systemd/systemd/blob/64b74c86d022eec9164f9c6ec80e16625b4ec27a/src/core/exec-invoke.c#L4279

I guess next month glibc will give us spawn-in-cgroup which will solve this nicely and comprehensively

**Comment by YHNdnzj** [comment]
> The cgroup attach in the child is done quite late in exec_invoke, any reason for that or can we move it up? 

I looked at it and I think it's fine to move up. But I have no 6.8 kernel to test the change.

**Comment by mrc0mmand** [comment]
If you prep a patch I can run some tests on it.

**Comment by bluca** [comment]
--> https://github.com/systemd/systemd/pull/30906

**Comment by poettering** [comment]
so, journald caches sender metainfo by pid. so i guess because the excutor logs a thing, and then moves cgroups, the logged info will still reflect out of date data.

We have conflicting goals here:

we want to cache, since it's expensive to get the full set of metadata. Also, we want things to be fully up-to-date always.

If the kernel would give us cgroupid metadata for messages sent via AF_UNIX we'd notice the changing info. But unfortunately we don't have that....

maybe one approach to deal with this could be to allow clients to ask for a resync explicitly, via some log field they can include in a logged journal record. i.e. if a client sets JOURNAL_FLUSH_CACHE=1 in a log message then journald would not check the process' cache entry, but gather all data anew. Then on the client side in log.h we'd add some api log_request_flush_cache(), which can be called by program code, and which would set some bool which would have the effect that the next message being logged will have the field set. The boolean would then be unset.

Then sd-executor would set thta flag once, when it migrated the process.

Still sucks though.

Maybe we should use our own vfork() wrapper after all to avoid this mess. I somehow have no illusions that glibc will actually deliver the cgroup stuff anytime soon

**Comment by DaanDeMeyer** [comment]
> maybe one approach to deal with this could be to allow clients to ask for a resync explicitly, via some log field they can include in a logged journal record. i.e. if a client sets JOURNAL_FLUSH_CACHE=1 in a log message then journald would not check the process' cache entry, but gather all data anew. Then on the client side in log.h we'd add some api log_request_flush_cache(), which can be called by program code, and which would set some bool which would have the effect that the next message being logged will have the field set. The boolean would then be unset.

This seems like it would quickly lead to some service DOSSing journald by flushing too often.

**Comment by bluca** [comment]
> Maybe we should use our own vfork() wrapper after all to avoid this mess. I somehow have no illusions that glibc will actually deliver the cgroup stuff anytime soon

pidfd_spawn with the cgroup option has been merged in main months ago and will be in glibc 2.39, which is being tested now and will be released in February. I have a branch ready to use it, but building and using your own glibc is extremely inconvenient so I'll wait for it to be available in Arch or Fedora to send the PR.

**Comment by vcaputo** [comment]
Since `sd-executor` is always a transient, if it could be reliably and efficiently identified as the log source the cache could be suppressed/discarded until it's executing the target executable.  It wouldn't be a huge performance killer to not cache that metadata for the duration of `sd-executor` execution until its /proc/$(pidof sd-executor)/exe) != `which sd-executor` ?  I guess the question then becomes "can just anyone run sd-executor to force journald into an uncached DoS mode?" but I think that's basically already an issue with just anyone creating lots of processes which briefly log something before exiting... rate limit to the rescue?

**Comment by bluca** [comment]
Given this is an issue only with debug level (no logs before) and we are getting a comprehensive fix via the new glibc api, I am not sure we should risk a complex change to fix it for older systems

**Comment by mrc0mmand** [comment]
Hmpf, this also started showing up on Arch with kernel 6.7-2 as well. And I can reproduce it even without debug logging, with or without this patch, so I can't even properly workaround it.

```
[    4.959179] testsuite-44.sh[663]: + systemd-run --wait -p LogNamespace=foobar echo 'hello world'
[    5.016908] systemd[1]: Started dbus-broker.service.
[    5.042500] dbus-broker-launch[665]: Ready
[    5.060316] systemd[1]: Started run-u1.service.
[    5.420460] systemd[1]: run-u1.service: Deactivated successfully.
[    5.421631] testsuite-44.sh[676]: Running as unit: run-u1.service; invocation ID: 01dad7f2f071431fa3e6fb8b8236c134
[    5.430526] testsuite-44.sh[676]: Finished with result: success
[    5.430526] testsuite-44.sh[676]: Main processes terminated with: code=exited/status=0
[    5.430526] testsuite-44.sh[676]: Service runtime: 360ms
[    5.430526] testsuite-44.sh[676]: CPU time consumed: 9ms
[    5.430526] testsuite-44.sh[676]: Memory peak: 396.0K (swap: 0B)
[    5.431612] testsuite-44.sh[663]: + systemd-run --wait -p LogNamespace=foobaz echo 'hello world'
[    5.438775] systemd[1]: Starting systemd-journald@foobar.service...
[    5.466157] systemd-journald[682]: Failed to open /dev/kmsg, ignoring: Operation not permitted
[    5.466483] systemd-journald[682]: Collecting audit messages is disabled.
[    5.557372] systemd[1]: Started systemd-journald@foobar.service.
[    5.708375] systemd[1]: Listening on systemd-journald-varlink@foobaz.socket.
[    5.843188] systemd[1]: Listening on systemd-journald@foobaz.socket.
[    5.996750] systemd[1]: Started run-u4.service.
[    5.998946] systemd[1]: Finished systemd-vconsole-setup.service.
[    6.003124] systemd[1]: run-u4.service: Deactivated successfully.
[    6.007590] testsuite-44.sh[681]: Running as unit: run-u4.service; invocation ID: 92eac504f4ad416ca3c0bd2fb0b91bb3
[    6.011723] systemd[1]: systemd-journald-varlink@foobaz.socket: Deactivated successfully.
[    6.011906] systemd[1]: Closed systemd-journald-varlink@foobaz.socket.
[    6.012062] systemd[1]: systemd-journald@foobaz.socket: Deactivated successfully.
[    6.012123] systemd[1]: Closed systemd-journald@foobaz.socket.
[    6.015463] testsuite-44.sh[681]: Finished with result: success
[    6.015463] testsuite-44.sh[681]: Main processes terminated with: code=exited/status=0
[    6.015463] testsuite-44.sh[681]: Service runtime: 10ms
[    6.015463] testsuite-44.sh[681]: CPU time consumed: 6ms
[    6.015463] testsuite-44.sh[681]: Memory peak: 516.0K (swap: 0B)
[    6.016767] testsuite-44.sh[663]: + journalctl --namespace=foobar --sync
[    6.024195] systemd-journald[682]: Received client request to sync journal.
[    6.026204] testsuite-44.sh[663]: + journalctl --namespace=foobaz --sync
[    6.031392] testsuite-44.sh[663]: + ls -l /var/log/journal/
[    6.038397] testsuite-44.sh[689]: total 16
[    6.038397] testsuite-44.sh[689]: drwxr-sr-x+ 2 root systemd-journal 4096 Jan 30 14:45 56d85d3fa7024b7c80b7fe1d589103dd
[    6.038397] testsuite-44.sh[689]: drwxr-sr-x+ 2 root systemd-journal 4096 Jan 30 14:45 56d85d3fa7024b7c80b7fe1d589103dd.foobar
[    6.038871] testsuite-44.sh[663]: + journalctl --list-namespaces
[    6.046142] testsuite-44.sh[690]: NAMESPACE
[    6.046142] testsuite-44.sh[690]: foobar
[    6.047269] testsuite-44.sh[663]: + journalctl -o cat --namespace=foobar
[    6.052271] testsuite-44.sh[663]: + journalctl -o cat
[    6.105724] testsuite-44.sh[693]: + journalctl --list-namespaces
[    6.106245] testsuite-44.sh[694]: + grep foobar
[    6.110601] testsuite-44.sh[694]: foobar
[    6.111188] testsuite-44.sh[695]: + journalctl --list-namespaces
[    6.111523] testsuite-44.sh[696]: + grep foobaz
[    6.116532] systemd[1]: testsuite-44.service: Main process exited, code=exited, status=1/FAILURE
[    6.116709] systemd[1]: testsuite-44.service: Failed with result 'exit-code'.
[    6.117151] systemd[1]: Failed to start testsuite-44.service.
```

This happens even after removing any debug logging from the whole test run.

I'll just disable the test for the Rawhide job for now, so I can unpin the kernel (as the build I currently use is no longer installable).

**Comment by mrc0mmand** [comment]
It's also weird that it's always the second journal namespace that is missing the "hello world" message :shrug:

**Comment by mrc0mmand** [comment]
It appears that there are different two issues (or at least it looks like that) - one that _misappropriates_ journal messages when debug logging is on (this affects TEST-04-JOURNAL and TEST-45-TIMEDATE), which is reproducible pretty much consistently and occurs only on kernel 6.8+, and then the journal namespace stuff that affects TEST-44-LOG-NAMESPACE, which occurs intermittently and seems to be reproducible even with kernel 6.7.

I worked around the former issue in the Rawhide job by just temporarily running everything with `systemd.log_level=info`, which seems to help (at least in my testing), it just might make debugging of fails slightly more annoying (so try to not break anything ;)). The latter one will require a bit more investigation.

**Comment by bluca** [comment]
Any idea what changed in the kernel to trigger this?

**Comment by mrc0mmand** [comment]
Not yet, but I'll try to look into that and, most likely, do a bisect on kernel.

**Comment by mrc0mmand** [comment]
Some debugging notes for my future less sleep-deprived me:
  - latest reproducer: https://mrc0mmand.fedorapeople.org/systemd/repro.sh
  - kernels
    - `6.8.0-0.rc0.20240109git9f8413c4a66f.1.fc40.x86_64` - pass
    - `6.8.0-0.rc0.20240110gitab27740f7665.4.fc40.x86_64` - pass?
      - failed only twice in ~10k iterations, doesn't match the frequency of "regular" fails (fail in the first ~250 iterations)
    - ...
    - `6.8.0-0.rc0.20240112git70d201a40823.5.fc40.x86_64` - fail

**Comment by mrc0mmand** [comment]
I gave this another ~50k iterations and this time without any fail, so let's close this as resolved. As for the journal corruption, I managed to isolate it into a simple reproducer; I'll file a new issue for that shortly.
