### ISSUE TITLE
#28370 beak nss resolution when running networkd

### ISSUE THREAD

**Issue by eskytthe** [systemd/systemd#30882]
### systemd version the issue has been seen with

254.6

### Used distribution

NixOS 23.11

### Linux kernel version used

6.1.69

### CPU architectures issue was seen on

x86_64

### Component

resolved ,systemd-networkd

### Expected behaviour you didn't see

#28370 changed resolved of local hostname when running networkd:

Useing `getnent` before merge of this PR (running systemd ver. 253.6) on a hoste named "artihost":
```
$ getent hosts artihost 
::1             artihost
```

### Unexpected behaviour you saw

After merge of #28370 - running systemd ver. 254.6:
```
$ getent hosts artihost 
::1             localhost
```

### Steps to reproduce the problem

Disable nss under systemd ver. 254.6 bring back the expected output
```
$ getent hosts artihost 
::1             artihost
```

See also https://github.com/NixOS/nixpkgs/issues/272426#issuecomment-1853759747 and https://github.com/NixOS/nixpkgs/issues/272426#issuecomment-1850236620

**Comment by poettering** [comment]
how does your /etc/hosts file look like?

**Comment by poettering** [comment]
but frankly, the behaviour to report "localhost" as canonical name for `::1` sounds right to me,

**Comment by eskytthe** [comment]
Sorry for late respond - /etc/hosts look like this:
```
127.0.0.1 localhost
::1 localhost
127.0.0.2 artihost.dbc.dk artihost
::1 artihost.dbc.dk artihost
```

**Comment by andreaskem** [comment]
You have two lines for `::1`? From what I can tell, that is understood to cause issues and is generally frowned upon:
https://unix.stackexchange.com/questions/102660/hosts-file-is-it-incorrect-to-have-the-same-ip-address-on-multiple-lines
https://lists.debian.org/debian-devel/2004/06/msg00468.html

**Comment by eskytthe** [comment]
Did a more simple test and with a more simple  /etc/resolv.conf, using NixOS test system, instead of using our live servers. Still same result. 

(Networkd enable on test systems)

```
# NixOS 23.11:
$ hostname
ahost
$ cat /etc/resolv.conf
...
nameserver 127.0.0.53
options edns0 trust-ad
search .
$ 
$ getent hosts ahost
::1             localhost
$ 
$ systemctl --version
systemd 254 (254.6)
```
```
# NixOS 23.05: 
$ hostname
ahost

$ cat /etc/resolv.conf
...
nameserver 127.0.0.53
options edns0 trust-ad
search adomain

$  getent hosts ahost
::1             ahost

$ systemctl --version
systemd 253 (253.6)
```

**Comment by YHNdnzj** [comment]
> (Networkd enable on test systems)

The relevant component is resolved, not networkd.

**Comment by eskytthe** [comment]
Did forget to include /etc/hosts in output from my last (NixOS test system)  tests, here it is:
```
$ cat /etc/hosts
127.0.0.1 localhost
::1 localhost
127.0.0.2 ahost.adomain ahost
::1 ahost.adomain ahost
192.168.1.1 ahost.adomain ahost
```
(Networkd is mention in the test because it trigger the issue in NixOS - so mostly a comment to us NixOS people) 

Will try to get other people from the NixOS community to comment on this issue.
