### ISSUE TITLE
network/dhcp: RFC8925 violation (IPv6OnlyMode) resulting in broken IPv4 in IPv6-preferring networks

### ISSUE THREAD

**Issue by Leseratte10** [systemd/systemd#30891]
### systemd version the issue has been seen with

255

### Used distribution

Affects any distribution (but I first noticed it on Arch Linux)

### Linux kernel version used

Affects any kernel version (but I first noticed it on 6.1.61-1-rpi-ARCH)

### CPU architectures issue was seen on

aarch64 and x86_64 - most likely affects any architecture

### Component

systemd-networkd

### Expected behaviour you didn't see

Since the PR #29472 by @yuwata has been merged, systemd is violating [RFC8925](https://datatracker.ietf.org/doc/html/rfc8925). 

This RFC says that a client (in this case, systemd) should only send the IPv6-only DHCP option to a DHCPv4 server if it will automatically set up a CLAT / 464XLAT when necessary. 

Quote from RFC:
> **IPv6-only-capable host**: A host that does not require an IPv4 address and can operate on IPv6-only networks. More precisely, IPv6-only capability is specific to a given interface of the host: if some applications on a host require IPv4 and the 464XLAT CLAT (customer-side translator) [[RFC6877](https://datatracker.ietf.org/doc/html/rfc6877)] is only enabled on one interface, the host is IPv6-only capable if connected to a NAT64 network via that interface.

systemd is sending this DHCPv4 option by default, but does NOT set up a 464XLAT/CLAT as required by RFC. 

### Unexpected behaviour you saw

systemd tells the DHCPv4 server it will set up a 464XLAT in IPv6-only networks (which is the point of the IPv6-only DHCPv4 option), but then doesn't do that. 

The new config option `IPv6OnlyMode` defaults to "yes" which causes this behaviour in systemd. 

This option should be set to "no" by default. Then it can be enabled by admins when a 464XLAT is implemented by another software or IPv4 support is not required. 

The default value can be set to "yes" again when a future version of systemd comes with a 464XLAT that'll automatically be enabled in such networks. 

--- 

Sidenote: The very point of the DHCP option 108 is so that clients capable of setting up a 464XLAT automatically no longer waste IPv4 addresses, but clients that aren't yet capable of that (like systemd) still get an IPv4 to reach IPv4 destinations. It doesn't make any sense to implement one of these things (option 108) but not the other (464XLAT).

Additional context provided by @oskar456 on another issue report: 

> Hey, I couldn't agree more with @Leseratte10 that `IPv6OnlyMode` should default to disabled, until CLAT is implemented and enabled in systemd. The whole point of RFC 8925 is to have just one network, which is used as IPv6-only for devices featuring CLAT (so that the IPv4 connectivity is established via CLAT) and as IPv4/IPv6 dual-stack for devices without CLAT. If systemd by default opt out from native IPv4 while not providing CLAT feature, this leads to breakage of IPv4-only dependent applications which is exactly what the authors of RFC 8925 wanted to avoid.
> 
> If such breakage was acceptable, then the network could have been run as IPv6-only without any IPv4 support. The whole point of running IPv4 DHCP with option 108 support is to provide IPv4 connectivity for devices without CLAT. Such devices should not opt out from IPv4.

### Steps to reproduce the problem

1. Have a Dual-Stack network with IPv4 and IPv6, with a NAT64 prefix announced through RAs (PREF64, like with [radvd](https://github.com/radvd-project/radvd/pull/179)) or through DNS (ipv4only.arpa)
2. Configure your network's DHCPv4 server to hand out the new option defined in RFC8925. 

In the isc-dhcp-server this can be done with the following config:
```
option no-legacy-ip code 108 = unsigned integer 32;
option no-legacy-ip 3600;
```

In the Kea DHCP server this can be done with this config (untested):
```
        "option-data": [
            {
                "name": "v6-only-preferred",
                "data": "3600"
            }
```

3. Connect a machine with systemd v255 and default settings to this network. 
4. Observe that the machine doesn't receive an IPv4 address from DHCP (because systemd sends option 108 to the DHCP server), but also doesn't set up a 464XLAT, violating RFC8925 and breaking the machine's reachability of IPv4 targets. 
5. Set config option `IPv6OnlyMode=no` and observe that the issue is fixed.

With this network configuration, any other device not running systemd will work properly and have both IPv4 and IPv6 targets reachable - either with IPv6-only and a 464XLAT (Android, iOS, MacOS), or with IPv6/IPv4 Dual Stack (Windows, older Android, embedded devices, whatever). 

What should happen instead is either A) systemd knows there's no working 464XLAT and and grabs an IPv4 from DHCPv4 anyways, or B) systemd sets up a working 464XLAT using the NAT64 prefix learned from [RAs](https://datatracker.ietf.org/doc/html/rfc8781), [DNS](https://datatracker.ietf.org/doc/html/rfc7050) or [PCP](https://datatracker.ietf.org/doc/html/rfc7225) or through explicit configuration. But not "systemd runs in IPv6-only mode and IPv4-only applications break". 

### Additional information

More information about this issue can be found in the related [issue about missing 464XLAT support](https://github.com/systemd/systemd/issues/23674#issuecomment-1872486022) , which is marked as a feature request since 2022.

I was advised to open a new issue (this one) marked as a bug report so this important bug doesn't get missed in a feature request issue. In my opinion this is a regression/bug and no longer just a feature request (since PR #29472 was merged).

The easiest quick fix for this would probably be to switch the default value of `IPv6OnlyMode` back to "no" (in a hotfix release). The proper fix would be, eventually, implementing 464XLAT as mentioned in #23674.

**Comment by Leseratte10** [comment]
I've seen that you've been working on network stuff for the last two weeks, did you already have time to take a closer look at this issue yet? The workaround should be fairly simple (make `IPv6OnlyMode` default to false) and I'd really like to have this fixed soon-ish. 

Sure, for my own systems I can just set it to false manually, but if this bug gets deployed to more and more machines, it'll be yet another excuse for people to be like "IPv6 is always breaking stuff, let's turn it off", which was exactly what the RFC tried to prevent with the requirement for a 464XLAT translator.

**Comment by ronnyaa** [comment]
note. it is not enough to just have a CLAT installed, systemd-networkd should only send the DHCP  option if a CLAT is installed and a detected 464XLAT prefix is actually working. 
blindly ignoring ipv4 if a CLAT is installed  on a dualstack network without any 464xlat PLAT would be just as broken.

**Comment by SoniEx2** [comment]
@ronnyaa a network that honors the DHCP option but doesn't provide a 464XLAT prefix is a broken network.

**Comment by Leseratte10** [comment]
Is it really, though?

The RFC says:
> if some applications on a host require IPv4 [...] the host is IPv6-only capable if connected to a NAT64 network via that interface.

So, if a host requires IPv4 connectivity due to the installed applications (which is going to be the case for most client installs probably), and the host is not connected to a NAT64 network (= was unable to find a working NAT64/464XLAT prefix), then that statement would mean the host is not considered to be an IPv6-only capable host. It doesn't matter if the network *would* honor the DHCPv4 option, the client (systemd) is not supposed to send it because it is not considered an IPv6-only capable client unless it has set up a valid and working 464XLAT.

It's perfectly fine for a network to announce the IPv6-only flag in DHCPv4 while not providing any NAT64 - this would mean that *only* devices that KNOW they can function in an IPv6-only network without NAT64 and without 464XLAT (so, like, devices and servers that know all their software is v6-capable and know all the servers they need to contact are v6-capable).

But that's a question for #23674 and isn't really relevant for fixing this current bug.

**Comment by SoniEx2** [comment]
there is an entire v6ops thread about this very issue. it is very long. the optimal solution is to move to an ipv6-only kernel and delegate setting up ipv4 (on e.g. dual-stack or ipv4-only networks) to an userspace daemon, but that's not gonna happen.

**Comment by yuwata** [comment]
Sorry for late. I opened #31200. Hopefully it will backported to the next stable release (v255.4 ?).

**Comment by zatricky** [comment]
@yuwata #31200 mentions #39891 ; was that supposed to be this issue #30891 maybe?

**Comment by yuwata** [comment]
> @yuwata #31200 mentions #39891 ; was that supposed to be this issue #30891 maybe?

Ouch. Will fix.
