### ISSUE TITLE
systemd-binfmt deletes binfmt_misc entries which it doesn't manage

### ISSUE THREAD

**Issue by radzikpwnz** [systemd/systemd#30892]
### systemd version the issue has been seen with

249.11-0ubuntu3.11

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.4.229

### CPU architectures issue was seen on

aarch64

### Component

systemd-binfmt

### Expected behaviour you didn't see

systemd-binfmt start/stop should not touch binfmt_misc entries which are not managed by systemd-binfmt.

User may register it's own binfmt_misc handlers (and use it's own services to manage them), and systemd-binfmt should not touch these handlers.

### Unexpected behaviour you saw

systemd-binfmt start/stop removes all binfmt_misc handlers which were registered not by systemd-binfmt

It causes problems when we have Docker container with registered binfmt_misc handler, and then create 2nd container on same server. Systemd in 2nd container will remove handler registered in 1st container (because binfmt_misc is shared between all containers, it is separate Kernel problem but anyway).
In some scenarios we can get problems even without Docker (e.g. if user's service which registers it's binfmt_misc entries starts before systemd-binfmt).

So for now systemd-binfmt exclusively manages binfmt_misc, which I think is wrong.
(There were some discussion about it in https://github.com/systemd/systemd/issues/13129 and everyone agreed that it is wrong.)

### Steps to reproduce the problem

```
$ echo ':myarch:M::\xff:\xff:/bin/true:PC' > /proc/sys/fs/binfmt_misc/register
$ ls /proc/sys/fs/binfmt_misc/
myarch  python3.10  register  status
$ systemctl restart systemd-binfmt
$ ls /proc/sys/fs/binfmt_misc/
python3.10  register  status
```

**Comment by radzikpwnz** [comment]
Yes, binfmt is not namespaced.  There were some attempts to fix it in kernel (e.g. https://patchwork.kernel.org/project/linux-fsdevel/cover/20181010161430.11633-1-laurent@vivier.eu/), but these patches were not committed.

"Writing binfmt from container is not good" actually means that systemd-binfmt can't work in container (because it writes to binfmt). So I don't think it is an option. If some software uses systemd and binfmt, it should be possible to run this software inside container, not VM. Moreover, you can have software installed on host (not conteiner) which uses binfmt, and you can't run containers with systemd on this host.

But even without container, what if some software creates it's own service to manage it's own binfmt handlers? This service can't work properly because at any time these handlers can be removed by systemd-binfmt start/restart.

Of course, there is workaround - completely disable systemd-binfmt.  And I understand that there are some problems caused by shared binfmt which are not related to systemd and require separate workarounds.

But why systemd-binfmt touches something that it doesn't manage? Why we can't register only entries from configs on start, remember them, and unregister only these entries on stop?

**Comment by radzikpwnz** [comment]
@poettering
Sorry, didn't check for new comments before posting mine.
So your point is that exclusive binfmt management by systemd is fine and was intended. Ok. 5 years ago you wrote that it's not good (https://github.com/systemd/systemd/issues/13129#issuecomment-513672660), that's why I created this issue.
Thank you anyway for pointing out @brauner's patch, glad to know that is was finally fixed in kernel.

**Comment by brauner** [comment]
> Yes, binfmt is not namespaced. There were some attempts to fix it in kernel (e.g. https://patchwork.kernel.org/project/linux-fsdevel/cover/20181010161430.11633-1-laurent@vivier.eu/), but these patches were not committed.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21ca59b365c091d583f36ac753eaa8baf947be6f

**Comment by mbiebl** [comment]
fwiw, I made sure that in Debian, all packages shipping a binfmt-support snippet also ship a binfmt.d config file.
https://salsa.debian.org/systemd-team/systemd/-/commit/72ee131f875c7ed229cab94851261328ead0101a

Those changes should trickle down to Ubuntu eventually.

**Comment by radzikpwnz** [comment]
So actually systemd forces developers to use systemd-binfmt for binfmt management. Because I can't just disable systemd-binfmt if my software uses it's own service, it will break software which uses systemd-binfmt.
Strange decision. I'm not expert in systemd, maybe there are some reasons for doing this, but I still don't understand them.

**Comment by mbiebl** [comment]
> So actually systemd forces developers to use systemd-binfmt for binfmt management.

It doesn't. Why do think so?

**Comment by radzikpwnz** [comment]
> It doesn't. Why do you think so?

If I create my own service which creates binfmt handler, systemd-binfmt will remove this handler. Yes, I can make dependency to start my service after systemd-binfmt, but there is no guarantee that systemd-binfmt won't be restarted at arbitrary moment. And it may be critical to have my handler active 100% of time. Yes, without containers it may be not a big problem, but anyway.

**Comment by yuwata** [comment]
Or, why not to disable systemd-bimfmt.service ?
Or, why not to override the service to drop ExecStop= line ?

If a service for managing something is enabled, then usually no other services should do the same. E.g. systemd-networkd vs NetworkManager, systemd-timesynchd vs chronyd...

That's usual, and not special for binfmt.

**Comment by mbiebl** [comment]
This is not a new problem. Debian/Ubuntu that traditionally used binfmt-support had exactly the same problem.
If you restarted binfmt-support it would wipe any local modifications. 

Which means, if you want your local modifications to be preserved by a restart, you have to register it with the service that manages it.

**Comment by radzikpwnz** [comment]
> If a service for managing something is enabled, then usually no other services should do the same. E.g. systemd-networkd vs NetworkManager, systemd-timesynchd vs chronyd

Network (single interface) is the single entity, it can't be managed by multiple services by definition. (I still can manage different interfaces by different services.)
Time is the single entity, it can't be managed by multiple services by definition.
Binfmt handlers are different and completely independent entities, why I can't manage each of them with different services?

> Which means, if you want your local modifications to be preserved by a restart, you have to register it with the service that manages it.

Hope that systemd won't begin to manage /tmp/ or /home/.  \</sarcasm>

Seriously, why systemd-binfmt removes handlers which were set by another software? Why it can't just register those which are in config and unregister those which were registered before and not in config?

**Comment by poettering** [comment]
> Yes, binfmt is not namespaced. There were some attempts to fix it in kernel (e.g. https://patchwork.kernel.org/project/linux-fsdevel/cover/20181010161430.11633-1-laurent@vivier.eu/), but these patches were not committed.

They *were* commited. Kernel 6.7.

> "Writing binfmt from container is not good" actually means that systemd-binfmt can't work in container (because it writes to binfmt). So I don't think it is an option. If some software uses systemd and binfmt, it should be possible to run this software inside container, not VM. Moreover, you can have software installed on host (not conteiner) which uses binfmt, and you can't run containers with systemd on this host.

systemd-binfmt doesn't run in a well setup container environment (unless it runs with namespaced binfmt_misc), because of the conditionalization:

```
ConditionPathIsMountPoint=/proc/sys/fs/binfmt_misc
```

> But even without container, what if some software creates it's own service to manage it's own binfmt handlers? This service can't work properly because at any time these handlers can be removed by systemd-binfmt start/restart.

binfmt_misc is not an interface that supports multiple writers nicely, because there's no concept of ownership. The general expectations is that on systems that have systemd you drop in a binfmt.d/ drop-in and then systemd-binfmt manages this.

> But why systemd-binfmt touches something that it doesn't manage? Why we can't register only entries from configs on start, remember them, and unregister only these entries on stop?

systemd-binfmt's job is to make binfmt.d/ drop-ins match up with /proc/sys/fs/binfmt_misc/, so that package managers can add or remove binfmt.d/ drop-ins and rerun systemd-binfmt and the right thing happens. If you want to allow multiple different programs to manage binfmt.d/ simultaneously without stepping on each others toes then you would need a concept of ownership of entries, but that simply doesn't exist, hence systemd-binfmt cannot determine if entries were created by itself in earlier runs or by something else.

**Comment by poettering** [comment]
> So your point is that exclusive binfmt management by systemd is fine and was intended. Ok. 5 years ago you wrote that it's not good ([#13129 (comment)](https://github.com/systemd/systemd/issues/13129#issuecomment-513672660)), that's why I created this issue.

So this has changed because kernel learned the ability to add binfmt_misc rules that pin inodes by fd, and that means file systems remained busy unless we actively delete entries whenever they are no longer referenced. So we nowadays manage the stuff in full.
