### ISSUE TITLE
udevd tries to get its cgroup even when PID1 isn't systemd

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#309]
In Arch Linux we start an instance of udevd in the initramfs using `/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never`. In this context, udevd's parent process is busybox's ash shell.

Starting with commit c26d1879c72fbaa147c0a82df433f676df139a90 udevd calls `cg_pid_get_path()` and outputs the warning `failed to get cgroup: No such file or directory` (since systemd is not running at this point).

It appears that the `getppid() == 1` check is insufficient to determine whether udevd is running under systemd or not. Would it be possible to restore the old behavior where udevd won't try to get its cgroup in the context I describe above?

**Comment by kaysievers** [comment]
I guess we should suppress the error, it is expected to fail in this setup.

**Comment by poettering** [comment]
Closing, because #319 was merged.

**Comment by jamespharvey20** [comment]
Just installed arch on a new machine a few hours ago, which included core/systemd 221-1, which was released to the arch core repository 29 hours ago.  (Well before I installed on the new machine.)  The package an hour before it was released to core cherry-picked the warning suppression commit.  See all this at https://projects.archlinux.org/svntogit/packages.git/log/?h=packages/systemd

Upon boot, I see the message: "failed to get cgroup: No such file or directory\nstarting version 221"

**Comment by jamespharvey20** [comment]
Just installed arch on a new machine a few hours ago, which included core/systemd 221-1, which was released to the arch core repository 29 hours ago. (Well before I installed on the new machine.) The package an hour before it was released to core cherry-picked the warning suppression commit. See all this at https://projects.archlinux.org/svntogit/packages.git/log/?h=packages/systemd

Upon boot, I see the message: "failed to get cgroup: No such file or directory\nstarting version 221"

**Comment by foutrelis** [comment]
We did cherry-pick the fix in `/trunk` but didn't push a new package because the error is harmless. (See the `upgpkg: systemd 221-1` commit that indicates what changes are included in the current package.)

**Comment by jamespharvey20** [comment]
Ahh, I see.  Sorry about that!  New to Arch.  Misunderstood how the page I linked to worked.  I'm not running #319, like I thought I was.  Now I'm confused, but I'll take that to the Arch packages forum.
