### ISSUE TITLE
systemctl -M doesn't work with rkt, but journalctl -M does

### ISSUE THREAD

**Issue by rlpowell** [systemd/systemd#3090]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> Systemd 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora Rawhide
### In case of bug report: Expected behaviour you didn't see

I may be confused, but I expected this to list the units inside the machine:

root@vrici# journalctl -M rkt-17148c12-fc73-4cba-a4b9-736361cde7aa
-- Logs begin at Fri 2016-04-22 00:32:50 PDT, end at Fri 2016-04-22 00:32:50 PDT. --
Apr 22 00:32:50 rkt-17148c12-fc73-4cba-a4b9-736361cde7aa systemd-journald[2]: Runtime journal (/run/log/journal/) is 8.0M, max 143.4M, 135.4M free.
Apr 22 00:32:50 rkt-17148c12-fc73-4cba-a4b9-736361cde7aa systemd-journald[2]: System journal (/var/log/journal/) is 8.0M, max 1.4G, 1.4G free.
Apr 22 00:32:50 rkt-17148c12-fc73-4cba-a4b9-736361cde7aa systemd-journald[2]: Time spent on flushing to /var is 837us for 2 entries.
Apr 22 00:32:50 rkt-17148c12-fc73-4cba-a4b9-736361cde7aa systemd-journald[2]: Journal started
root@vrici# systemctl list-machines
  NAME                                     STATE    FAILED JOBS
● vrici.digitalkingdom.org          (host) degraded      1    0
● rkt-17148c12-fc73-4cba-a4b9-736361cde7aa n/a           0    0

2 machines listed.
root@vrici# systemctl list-units -M rkt-17148c12-fc73-4cba-a4b9-736361cde7aa
Failed to connect to bus: No such file or directory
### In case of bug report: Unexpected behaviour you saw

See above
### In case of bug report: Steps to reproduce the problem

I tried both:

systemd-run --slice=machine rkt run --insecure-options=image --no-overlay --interactive docker://busybox

and:

rkt run --insecure-options=image --no-overlay --interactive docker://busybox

**Comment by poettering** [comment]
what do you run inside your container? a systemd-based system? "systemctl -M" is used to talk to systemd inside it.

**Comment by alban** [comment]
It does not work because rkt's stage1 doesn't have dbus and `systemctl -M` requires dbus inside the container.

There is a feature request in rkt to add that support: https://github.com/coreos/rkt/issues/1463

**Comment by poettering** [comment]
OK, closing this here then, please follow up on the rkt bug tracker. Thanks.

**Comment by rlpowell** [comment]
Super helpful.  Thanks!
