### ISSUE TITLE
systemd-xdg-autostart-generator should not skip desktop files with Hidden=true

### ISSUE THREAD

**Issue by OJFord** [systemd/systemd#30925]
### Component

systemd-xdg-autostart-generator

### Is your feature request related to a problem? Please describe

Background services such as lxpolkit reasonably ship with an /etc/xdg/autostart/*.desktop file that uses `Hidden=true` to prevent them appearing in launcher menus, but we do want them to autostart - surely the presence of a file is an indication of that.

### Describe the solution you'd like

systemd-xdg-autostart-generator already also respects `X-systemd-skip=true`, I would suggest just ceasing to also check `Hidden`.

### Describe alternatives you've considered

Possible workarounds are:
1. Modify or create a copy of the desktop file which does not have `Hidden`
2. Manually create a systemd service for it

(1) of course means that it _would_ then appear in menus, which is undesirable.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by YHNdnzj** [comment]
No. As defined in [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys):

> Hidden should have been called Deleted. It means the user deleted (at their level) something that was present (at an upper level, e.g. in the system dirs). It's strictly equivalent to the .desktop file not existing at all, as far as that user is concerned. This can also be used to "uninstall" existing files (e.g. due to a renaming) - by letting make install install a file with Hidden=true in it.

-----------

> Background services such as lxpolkit reasonably ship with an /etc/xdg/autostart/*.desktop file that uses Hidden=true to prevent them appearing in launcher menus, but we do want them to autostart - surely the presence of a file is an indication of that.

Then `NoDisplay=` should be used instead.

Sorry, but this is against the spec and there's nothing actionable for us.

**Comment by OJFord** [comment]
Oof, ok, thanks, I didn't realise. Seems like a mistake in lxsession, surely the intention was `NoDisplay`, I'll take it up there.

Cheers.
