### ISSUE TITLE
network share wifi

### ISSUE THREAD

**Issue by mfulz** [systemd/systemd#30948]
### systemd version the issue has been seen with

255

### Used distribution

Arch

### Linux kernel version used

6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

reboot / shutdown without waiting for mounted network share as result of killing network before unmount / stop of autofs

### Unexpected behaviour you saw

Wifi (user) shut down on logout but network share still mounted and therefore hanging

### Steps to reproduce the problem

Setup wifi under user (NOT GLOBAL) with ae. nm-applet. Config network share via autofs. Reboot while the share is mounted.

**Comment by mfulz** [comment]
I'll refer to: https://github.com/systemd/systemd/issues/15913

Ok I run into the same problem with a nfs mount (autofs).
The "fix" making the wifi conn global is working but honestly it's not a fix.

What if a multiuser system with different vlans for the users on the wifi and user folders on networks are shutting down the network before the umount?

I mean you can't allow the connections to all users as the permissions are different.

Is there any way to keep the user wifi connection open on reboot / shutdown, till network shares are unmounted?

**Comment by poettering** [comment]
systemd provides all the right hooks to make this safe, but network management solutions (i presume NetworkManager in your case?) need to order themselves properly against them for things to work. This is not a systemd problem however, but an issue for your network management solution of choice.

Hence, please file a bug against that. It's nothing we can address in systemd.
