### ISSUE TITLE
Assertion 's' failed at src/basic/cgroup-util.c:1852, function cg_mask_to_string(). Aborting.

### ISSUE THREAD

**Issue by iugo** [systemd/systemd#30957]
### systemd version the issue has been seen with

249.11-0ubuntu3.11

### Used distribution

Ubuntu 22.04.3

### Linux kernel version used

6.2.0-39-generic

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Expecting systemctl status to be usable without encountering any systemd-related issues.

### Unexpected behaviour you saw

1. Periodically encountering the error `[system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)`.
2. After executing `sudo systemctl status abcabc`, I encountered the following error: `Failed to get properties: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)` or `Failed to get properties: Connection timed out`.

### Steps to reproduce the problem

Occurs after running normally for a period of time.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
1月 02 15:28:51 zsqk-pc-01 snapd[803]: storehelpers.go:773: cannot refresh: snap has no updates available: "bare", "core20", "core22", "gnome-3-38-2004", "gnome-42-2204", "gtk-common-themes", "snap-store", "snapd", "snapd-desktop-integration"
1月 02 15:29:14 zsqk-pc-01 systemd[1]: Reloading.
1月 02 15:29:14 zsqk-pc-01 systemd[1]: Assertion 's' failed at src/basic/cgroup-util.c:1852, function cg_mask_to_string(). Aborting.
1月 02 15:29:59 zsqk-pc-01 systemd[1]: Caught <ABRT>, dumped core as pid 113634.
1月 02 15:29:59 zsqk-pc-01 systemd[1]: Freezing execution.
1月 02 15:30:00 zsqk-pc-01 systemd-oomd[623]: Failed to connect to /run/systemd/io.system.ManagedOOM: Connection refused
1月 02 15:30:00 zsqk-pc-01 systemd-oomd[623]: Failed to acquire varlink connection: Connection refused
1月 02 15:30:00 zsqk-pc-01 systemd-oomd[623]: Event loop failed: Connection refused
1月 02 15:30:01 zsqk-pc-01 CRON[113644]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
1月 02 15:30:01 zsqk-pc-01 CRON[113645]: (root) CMD ([ -x /etc/init.d/anacron ] && if [ ! -d /run/systemd/system ]; then /usr/sbin/invoke-rc.d anacron start >/dev/null; fi)
1月 02 15:30:01 zsqk-pc-01 CRON[113644]: pam_unix(cron:session): session closed for user root
1月 02 15:30:24 zsqk-pc-01 dbus-daemon[784]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
1月 02 15:30:24 zsqk-pc-01 snapd[803]: taskrunner.go:299: [change 8 "Mount snap \"firefox\" (3600)" task] failed: systemctl command [daemon-reload] failed with exit status 1: Failed to reload daemon: Connection reset by peer
1月 02 15:30:50 zsqk-pc-01 dbus-daemon[784]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
```
```

**Comment by poettering** [comment]
Sorry, 249 is too old to be tracked here. Please contact your distro for help.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
