### ISSUE TITLE
`journalctl --follow` does not free memory on exit

### ISSUE THREAD

**Issue by aafeijoo-suse** [systemd/systemd#30995]
### systemd version the issue has been seen with

255-1269-g2d1e7d1

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.6.9-1-default

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

`journalctl --follow` frees memory on exit.

### Unexpected behaviour you saw

`journalctl --follow` does not free memory on exit.

### Steps to reproduce the problem

This was a design choice in #27519, instead of returning cleanly from the main process, the signal is re-sent to exit with the signal's exit code.

https://github.com/systemd/systemd/blob/ee8f3e489e200c05e23bb3d7c6c75804df58e752/src/journal/journalctl.c#L2690-L2693

But, the common way to exit `--follow` is with `Ctrl+c`, so maybe at least SIGINT should not be propagated and return 0 in this case.

**Comment by yuwata** [comment]
-> #31028.
