### ISSUE TITLE
timedatectl status output: incorrect naming "NTP service"-> "SNTP service"

### ISSUE THREAD

**Issue by ProBackup-nl** [systemd/systemd#31029]
### systemd version the issue has been seen with

255.2-2

### Used distribution

Arch

### Linux kernel version used

6.7.0-arch3-1

### CPU architectures issue was seen on

x86_64

### Component

timedatectl

### Expected behaviour you didn't see

```
timedatectl status | grep service
              SNTP service: active
```

Because the systemd-timesyncd is not fully RFC compliant, factually the output of timedatectl is not regarding an "NTP service" but referring to a simplified "SNTP service". Better use "SNTP service" over "NTP service" to be factual correct. 

PS I still prefer the old naming "systemd-timesyncd service" in this output, because its most descriptive for is shown here as output.

### Unexpected behaviour you saw

```
timedatectl status | grep service
              NTP service: active
```

### Steps to reproduce the problem

Issue timedatectl status | grep service

**Comment by poettering** [comment]
It can also control other NTP implementations. Also, frankly, this is just needless nit picking, if you ask me
