### ISSUE TITLE
A4Tech Bloody V8 handled as a joystick

### ISSUE THREAD

**Issue by mradermaxlol** [systemd/systemd#3103]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Gentoo Linux ~amd64
### In case of bug report: Expected behaviour you didn't see

> Normal mouse detection.
### In case of bug report: Unexpected behaviour you saw

> My mouse (A4Tech Bloody V8) is recognized as a mouse and **as a joystick device**. There are events created for the device, actually:
> ![2016-04-24 11-27-29](https://cloud.githubusercontent.com/assets/11138966/14766370/f25d7cf2-0a17-11e6-886d-94844578d030.png)
> Unless I delete them my system's telling me of a joystick present. I thus can't, for example. use Steam BigPicture or play Metro games, because they use that "joystick" if it's present. I've also been trying to create a rule for udev, but no success there.
> 
> As far as I'm concerned, udev is responsible for device handling.
### In case of bug report: Steps to reproduce the problem

> - Buy such a mouse
> - Get some systemd-equipped Linux distro
> - Go to console and type `ls /dev/input/by-id`
> - PROFIT!

**Comment by mradermaxlol** [comment]
Will anybody at least review stuff?

**Comment by martinpitt** [comment]
Can you please copy&paste the output of

```
udevadm test-builtin input_id /sys/class/input/inputN
```

for the appropriate device `N`?

**Comment by mradermaxlol** [comment]
@martinpitt OK, will do ASAP, maybe in a few hours. And how do I determine that _N_? Is that the deviceid or something?

**Comment by poettering** [comment]
@mradermaxlol see cat /proc/bus/input/devices. It lists all input devices, and shows you the input device numbers along with them.

**Comment by mradermaxlol** [comment]
[devices.txt](https://github.com/systemd/systemd/files/250367/devices.txt)
[udevadm.txt](https://github.com/systemd/systemd/files/250369/udevadm.txt)
@martinpitt @poettering here's the output of both commands.

**Comment by mradermaxlol** [comment]
Soooo... Any update?

**Comment by mradermaxlol** [comment]
Oh, my bad. I've just checked stuff, seems like everything's OK... At least for now.
