### ISSUE TITLE
Failed to set up IPC namespacing: Resource temporarily unavailable

### ISSUE THREAD

**Issue by zeha** [systemd/systemd#31037]
### systemd version the issue has been seen with

systemd_255.2-4

### Used distribution

Debian testing

### Linux kernel version used

Linux 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09)

### CPU architectures issue was seen on

x86_64

### Component

systemd

###  Problem description

Debian CI runs package tests (and thus systemd) inside LXC containers. Some packages use `PrivateIPC=yes` in their service files, f.e. pdns does.

In Debian bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059995 elbrus@d.o noted that on one amd64 worker (and an s390x worker), pdns.service fails to start like this:

```
 29s Jan 20 04:16:22 ci-020-dcd36dc4 (s_server)[1287]: pdns.service: Failed to set up IPC namespacing: Resource temporarily unavailable
```

This seems to mean something inside `setup_shareable_ns` returned EAGAIN. There is already one check for `if (ns != -EAGAIN)` in there, but maybe other calls inside can also fail with EAGAIN.

As this is quite hard to debug, I'm hoping someone with knowledge of this code can "stare out the problem" :-)

**Comment by yuwata** [comment]
Could you provide relevant .service file?

Is it a new issue in v255?

**Comment by zeha** [comment]
> Could you provide relevant .service file?

Ah yes, my bad. Here:

```
[Unit]
Description=PowerDNS Authoritative Server
Documentation=man:pdns_server(1) man:pdns_control(1)
Documentation=https://doc.powerdns.com
Wants=network-online.target
After=network-online.target mysqld.service postgresql.service slapd.service mariadb.service time-sync.target

[Service]
ExecStart=/usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no
SyslogIdentifier=pdns_server
User=pdns
Group=pdns
Type=notify
Restart=on-failure
RestartSec=1
StartLimitInterval=0
RuntimeDirectory=pdns

# Sandboxing
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_CHOWN
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_CHOWN
LockPersonality=true
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
# Setting PrivateUsers=true prevents us from opening our sockets
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
# ProtectSystem=full will disallow write access to /etc and /usr, possibly
# not being able to write slaved-zones into sqlite3 or zonefiles.
ProtectSystem=full
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
SystemCallFilter=~ @clock @debug @module @mount @raw-io @reboot @swap @cpu-emulation @obsolete
ProtectProc=invisible
PrivateIPC=true
RemoveIPC=true
DevicePolicy=closed
# Not enabled by default because it does not play well with LuaJIT
# MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
```

> Is it a new issue in v255?

No, but it is unclear when it started. Sorry.

**Comment by zeha** [comment]
@yuwata I've added the systemd unit. Do you still need additional "[needs-reporter-feedback ❓]" here?
