### ISSUE TITLE
List hardware resources and attached devices

### ISSUE THREAD

**Issue by dmedri** [systemd/systemd#3104]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

222
### (RFE) Request for enhancements

These features/tools could be in many ways useful, for a sysadmin on cli or desktop app developers. Functions in a public library to import. With a cli command.

Question: "systemd, list _all_ the hardware resources on my computer with basic info."
Question: "systemd, list all the _video_ device available."
Question: "systemd, list all devices of class "net" and subclass "wl" _available_."

On command line, `udevadmin info ...` can already show many info on a specified device.
On command line, `hwinfo --short` can show the list of hardware resources and basic info.
The systemd-hwdb has already info about device names and manufacturers.

**Comment by poettering** [comment]
Well, I am not sure we really should provide more in this area. If you want a nice browser for this consider using a tool like udev-browse:

http://0pointer.de/blog/projects/udev-browse.html

But I doubt that anything higher level than udevadm belongs in systemd itself, sorry.
