### ISSUE TITLE
systemctl should warn if a unit is asked to be masked but not its triggering units, the same way as we warn if a unit is asked to be stopped but not its triggering units

### ISSUE THREAD

**Issue by elkrejzi** [systemd/systemd#311]
When booting with kdbus enabled, I see the following as errors:

Jun 21 11:54:15 krejzi systemd[1]: org.freedesktop.NetworkManager.busname: Bus service dbus-org.freedesktop.NetworkManager.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: org.freedesktop.NetworkManager.
Jun 21 11:54:15 krejzi systemd[1]: fi.epitest.hostap.WPASupplicant.busname: Bus service wpa_supplicant.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: fi.epitest.hostap.WPASupplicant.
Jun 21 11:54:15 krejzi systemd[1]: org.freedesktop.ModemManager1.busname: Bus service dbus-org.freedesktop.ModemManager1.service not loaded, refusing.
Jun 21 11:54:15 krejzi systemd[1]: Failed to listen on DBUS1: org.freedesktop.ModemManager1.

These services are explicitly disabled through systemctl and can't even be dbus-activated until they are enabled by systemctl enable. dbus-daemon wouldn't spawn them, but would print a warning.

My issue is that systemd prints an error instead of warning when it can't load an explicitly disabled dbus service file. It would be nice to print a warning instead, since when an error is printed at boot, systemd starts outputting to screen at boot, breaking the "quiet" kernel option.

**Comment by dvdhrm** [comment]
Sounds valid to me. Might not be easy to implement, though. These busname units are generated during boot and as such are not handled special by pid1. We want this error for real busname units, but for fallbacks we want warnings. Hmm, maybe @poettering has an idea.

**Comment by dvdhrm** [comment]
Discussing this a bit more, I doubt we will fix this. The correct way to deal with this is to simply mask the busname-unit. `dbus-daemon` doesn't allow that, but with kdbus you can just mask the `<busname>.busname` unit and systemd will no longer enable it.

Sure, that means disabling both, the unit (so it is disabled for dbus1) and the busname (so it is disabled for kdbus). But I think that's a reasonable compromise.

Comments?

**Comment by elkrejzi** [comment]
So, what you mean is that systemctl will issue a mask operation itself when disabling an unit or an user has to do it manually, which also means user would need to manually unmask it if the service is to be enabled in the future?

I'm all for the first approach, but not sure how easy would it be to implement. The second aproach wouldn't need a thing to be done, but not really desireable.

**Comment by poettering** [comment]
I figure we should add a logic to systemctl to warn if people mask a service but not its triggering units. We already have a warning in place if people stop a service but not its triggering units, and we should really copy that for masking.

I think this would be the best solution to the problem, will accordingly rename the issue now.
