### ISSUE TITLE
Verifying DNS of <hostname> takes +3sec if <hostname> does not exist

### ISSUE THREAD

**Issue by cmonty14** [systemd/systemd#31114]
### systemd version the issue has been seen with

249

### Used distribution

SUSE Linux Enterprise Server 15 SP4

### Linux kernel version used

5.14.21-150400.24.97-default

### CPU architectures issue was seen on

x86_64

### Component

resolvectl

### Expected behaviour you didn't see

Verifying DNS of `<hostname>` by using any of the commands below completes within ms.
```
resolvectl query <hostname>
host <hostname>
dig <hostname>
```

This would be in accordance to documentation:
```
Domains=
A space-separated list of domains, optionally prefixed with "~", used for two distinct purposes described below. Defaults to the empty list.

Any domains not prefixed with "~" are used as search suffixes when resolving single-label hostnames (domain names which contain no dot), in order to qualify them into fully-qualified domain names (FQDNs). These "search domains" are strictly processed in the order they are specified in, until the name with the suffix appended is found. For compatibility reasons, if this setting is not specified, the search domains listed in /etc/resolv.conf with the search keyword are used instead, if that file exists and any domains are configured in it.
```
Using `<FQDN>` for relevant host works as expected, means the verification takes some ms.

This is my current configuration:
```
sles-client:~ # cat /etc/systemd/resolved.conf.d/dns.conf
[Resolve]
DNS=147.204.9.200 147.204.9.201
Domains=foo.bar example.com
```

And here's the output of `resolvectl status` (all good imo):
```
sles-client:~ # resolvectl status
Global
         Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 147.204.9.200
        DNS Servers 147.204.9.200 147.204.9.201
         DNS Domain foor.bar example.com

Link 2 (enp11s0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp19s0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

### Unexpected behaviour you saw

Time to execute this command is 3-4 sec:
```
sles-client:~ # time resolvectl query ls3683
ls3683: resolve call failed: 'ls3683' not found

real    0m3.514s
user    0m0.000s
sys     0m0.005s

sles-client:~ # time host ls3683
Host ls3683 not found: 3(NXDOMAIN)

real    0m3.761s
user    0m0.000s
sys     0m0.009s
```

### Steps to reproduce the problem

1. Create configuration file `/etc/systemd/resolved.conf.d/dns.conf`
2. Run `systemctl restart systemd-resolved.service`
3. Verify settings with `resolvectl status`
4. Run `host <hostname>`

**Comment by mrc0mmand** [comment]
That's most likely caused by LLMNR, which resolved uses to resolve single-label names, as it waits for a potential response (and retries a couple of times on timeout). If you disable it (by setting `LLMNR=no` in `/etc/resolved.conf`), the mentioned single-label query should return much faster.

**Comment by cmonty14** [comment]
> If you disable it (by setting `LLMNR=no` in `/etc/systemd/resolved.conf`), the mentioned single-label query should return much faster.

Many thanks for sharing this information.

After creating this file `/etc/systemd/resolved.conf.d/disable-llmnr.conf` with content
```
[Resolve]
LLMNR=no
```
I get this output for command `resolvectl status`:
```
# resolvectl status
Global
         Protocols: -LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 147.204.9.200
        DNS Servers 147.204.9.200 147.204.9.201
         DNS Domain devsys.net.sap wdf.sap.corp

Link 2 (enp11s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp19s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

I just wonder that `+LLMNR` is (still) shown for individual interfaces `Link 2 (enp11s0)` and `Link 3 (enp19s0)`.
If I want to modify this setting, I need to change relevant config in `/etc/systemd/network/<interface>.network`?

But the issue is solved.

**Comment by mrc0mmand** [comment]
If you use `systemd-networkd` then yes, as there's `LLMNR=` directive in the `[Network]` section of `.network` files, that defaults to `true`, and this setting is read by `systemd-resolved` (see `systemd.network(5)`).

**Comment by cmonty14** [comment]
_Solution:_
Setting LLMNR=no in /etc/systemd/resolved.conf
