### ISSUE TITLE
Support sched_load_balance for cpusets

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#31118]
### Component

systemd

### Is your feature request related to a problem? Please describe

I am trying to fins a substitute to the `isolcpus` kernel argument,
and from my understanding you can do this with the help of the `sched_load_balance` cpusets option.

Here is an example setting cgroups directly: https://www.suse.com/c/cpu-isolation-practical-example-part-5/

### Describe the solution you'd like

Add a flag to [systemd.resource-control](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html),
which controls `sched_load_balance`.

### Describe alternatives you've considered

`isolcpus` is a kernel boot argument and deprecated.

Setting CPU-Affinity does not do enough, Linux should stop sending scheduler interrupts to the CPU Core.

(I currently havent verified that setting `sched_load_balance` will disable IRQ like `isolcpus` does)

**Comment by poettering** [comment]
Sorry, but no. `sched_load_balance` is a cgroupv1 field. It doesn't exist in cgroupv2. At this time, we are not adding support for new cgroupv1 concepts, it's obsolete.

Sorry.
