### ISSUE TITLE
No PropertiesChanged signal emitted when freezing/thawing unit

### ISSUE THREAD

**Issue by engelmi** [systemd/systemd#31115]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.3

### Linux kernel version used

6.5.0-14-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

`PropertiesChanged` signal with the updated `FreezerState` property is emitted on
**service**: org.freedesktop.systemd1
**path**: /org/freedesktop/systemd1/unit/<masked-unit-name> (e.g. cow_2eservice)
**interface**: org.freedesktop.DBus.Properties

### Unexpected behaviour you saw

No `PropertiesChanged` signal is emitted on `org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/<masked-unit-name> org.freedesktop.DBus.Properties`

### Steps to reproduce the problem

Using the gist here: https://gist.github.com/engelmi/a1ed5af612dbecb51a27b28b83d1a33e

1. Copy the `cow.service` from gist (could be any other service, the unit name is just hardcoded in `watch.py`)
2. Copy and run python script `watch.py` from gist to watch for property changed signals on D-Bus
3. In other terminal run
   1. `systemctl start cow.service` (signals are received)
   2. `systemctl freeze cow.service` (no signal is received)
   3. `systemctl thaw cow.service` (also no signal received)
   4. `systemctl stop cow.service` (signals are received again, with Freezerstate)

**Comment by dofmind** [comment]
`PropertiesChanged` signal is emitted if calls `bus_unit_send_change_signal` function when the unit's `freezer_state` is changed.
