### ISSUE TITLE
Confusing "Logs begin at" when using "journalctl -f"

### ISSUE THREAD

**Issue by kripper** [systemd/systemd#31111]
### systemd version the issue has been seen with

255 (255.3-1 Arch)

### Used distribution

Arch Linux

### Linux kernel version used

6.7.1-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

When using `journalctl -f -t <id>` the initial line `Logs begin at <date>` should not be included, since it is confusing in this specific use case.

Note that when using `journalctl -f` this line is ommited.

### Unexpected behaviour you saw

When using `journalctl -f -t <id>` the output starts with `Logs begin at <date>`

### Steps to reproduce the problem

journalctl -f -t <id>

**Comment by YHNdnzj** [comment]
Sorry, this is the upstream bug tracker for systemd, and we only support the latest two versions here, namely v254 and v255. Please report to your distro if you're using older versions.

Closing. Feel free to ask for reopen if this can be reproduced on newer versions.

**Comment by kripper** [comment]
Issue updated. Please reopen.

**Comment by YHNdnzj** [comment]
This should have already been fixed by https://github.com/systemd/systemd/commit/a2d7654f99eba250eddf988db262abef96ebbe7a. Did you actually test on a newer version??

**Comment by kripper** [comment]
@YHNdnzj you are right. I tested an older version. After updating the message is not displayed any more. Closing.
