### ISSUE TITLE
systemd-repart in the initramfs to create the root partition sometimes fails

### ISSUE THREAD

**Issue by richardmaw-codethink** [systemd/systemd#31142]
### systemd version the issue has been seen with

v255-223-g1f3d4ced49

### Used distribution

Fedora Linux 39

### Linux kernel version used

6.6.12-200.fc39.x86_64 / 6.1.0-17-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

`systemd-repart.service` creates root partition and system boots.

### Unexpected behaviour you saw

root device times out and system enters emergency console

### Steps to reproduce the problem

1. Create a disk image that lacks a root partition with `mkosi build`.
2. Copy the output directory with `cp -a --reflink=auto mkosi.output tmp`.
3. Start the image with `mkosi --output-dir=tmp qemu` immediately afterwards.

Repeat steps 2-3 until it happens. I find it happens at least once in every 38.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Relevant boot logs from qemu console

[   17.846563] systemd[1]: Failed to start systemd-tpm2-setup-early.service.
[  OK  ] Started systemd-networkd.service.
[  OK  ] Reached target network.target.
         Starting systemd-vconsole-setup.service.
[  OK  ] Finished systemd-vconsole-setup.service.
[  OK  ] Found device dev-disk-by\x2dpartuu…121\x2d95da\x2d9719a121f8a9.device.
[  OK  ] Found device dev-disk-by\x2dpartuu…ea5\x2d52fe\x2defd95748ff16.device.
         Starting systemd-veritysetup@usr.service...
[  OK  ] Found device dev-mapper-usr.device.
[  OK  ] Finished systemd-veritysetup@usr.service.
[  OK  ] Reached target blockdev@dev-mapper-usr.target.
[  OK  ] Reached target veritysetup.target.
[  OK  ] Reached target sysinit.target.
[  OK  ] Reached target timers.target.
[  OK  ] Listening on dbus.socket.
[  OK  ] Reached target sockets.target.
         Starting systemd-fsck-usr.service...
[m  OK  ] Reached target basic.target.
         Starting dbus-broker.service...
[  OK  ] Started dbus-broker.service.
[  OK  ] Finished systemd-fsck-usr.service.
         Mounting sysusr-usr.mount...
[  OK  ] Mounted sysusr-usr.mount.
[  OK  ] Reached target initrd-usr-fs.target.
         Starting systemd-repart.servicem...
[ TIME ] Timed out waiting for device dev-gpt\x2dauto\x2droot.device.
[DEPEND] Dependency failed for sysroot.mount.
[DEPEND] Dependency failed for systemd-pcrfs@sysroot.service.
[DEPEND] Dependency failed for initrd-root-fs.target.
[DEPEND] Dependency failed for initrd-parse-etc.service.
[DEPEND] Dependency failed for sysroot-usr.mount.
[DEPEND] Dependency failed for initrd-fs.target.
[DEPEND] Dependency failed for initrd-root-device.target.
[   20.593940] systemd[1]: dev-gpt\x2dauto\x2droot.device: Job dev-gpt\x2dauto\x2droot.device/start timed out.
[   20.597802] systemd[1]: Timed out waiting for device dev-gpt\x2dauto\x2droot.device.
[   20.610246] systemd[1]: Dependency failed for sysroot.mount.

systemd-dissect logs run immediately after failure

env SYSTEMD_LOG_LEVEL=debug SYSTEMD_LOOP_DIRECT_IO=0 systemd-dissect --json=short /home/richardmaw/workspace/sy002/systemd-wt/build/testsuite-03.service/system.raw
Opened '/home/richardmaw/workspace/sy002/systemd-wt/build/testsuite-03.service/system.raw' in O_RDONLY access mode, with O_DIRECT disabled.
Determined sector size 512 based on discovered partition table.
loop1: Acquired exclusive lock.
Successfully acquired /dev/loop1, devno=7:1, nr=1, diskseq=2857
Kernel was quicker than us in adding partition 1.
Opened /dev/loop1p1 (fd=3, whole_block_devnum=7:1, diskseq=2857).
Kernel was quicker than us in adding partition 2.
Opened /dev/loop1p2 (fd=4, whole_block_devnum=7:1, diskseq=2857).
Kernel was quicker than us in adding partition 3.
Opened /dev/loop1p3 (fd=7, whole_block_devnum=7:1, diskseq=2857).
Kernel was quicker than us in adding partition 4.
Opened /dev/loop1p4 (fd=8, whole_block_devnum=7:1, diskseq=2857).
Kernel was quicker than us in adding partition 5.
Kernel was quicker than us in adding partition 6.
Opened /dev/loop1p6 (fd=9, whole_block_devnum=7:1, diskseq=2857).
Probed fstype 'btrfs' on partition /dev/loop1p6.
Probed fstype 'erofs' on partition /dev/loop1p2.
Probed fstype 'swap' on partition /dev/loop1p5.
Successfully forked off '(sd-dissect)' as PID 2016398.
Mounting /proc/self/fd/9 (btrfs) on /tmp/dissect-Abnhe0 (MS_RDONLY|MS_NODEV "norecovery")...
Failed to mount dissected image: No such file or directory
Failed to read /etc/hostname of image: No such file or directory
/etc/machine-id file of image is empty.
Failed to read has-init-system boolean: Input/output error
(sd-dissect) failed with exit status 1.
Failed to acquire image metadata: No such file or directory
Removed partition /dev/loop1p1
Removed partition /dev/loop1p2
Removed partition /dev/loop1p3
Removed partition /dev/loop1p4
Removed partition /dev/loop1p5
Removed partition /dev/loop1p6
```

**Comment by richardmaw-codethink** [comment]
It appears to also fail with `--reflink=never`.

**Comment by DaanDeMeyer** [comment]
@richardmaw-codethink Can you add the debug logs from the initramfs here by any chance? And maybe an `strace` (create a dropin for systemd-repart in the initrd image that executes it with `strace`.)

**Comment by DaanDeMeyer** [comment]
@richardmaw-codethink Can you try changing the root filesystem and see if that changes things? Instead of `btrfs` try `ext4`.

Also, can I get an strace of that `systemd-dissect` run so we see what triggers the `ENOENT`?

**Comment by richardmaw-codethink** [comment]
I'll get you strace logs after I've got a `--reflink=none` after clearing more disk space in case that was causing problems.

**Comment by richardmaw-codethink** [comment]
[dissect-strace.txt](https://github.com/systemd/systemd/files/14114086/dissect-strace.txt)

The strace for the repart only ended up going to the journal, which wasn't recoverable, so I'm re-running with `StandardOutput=journal+console`.

**Comment by richardmaw-codethink** [comment]
```
[pid 2078413] openat(28, "usr", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
```
This looks like the last error before writing "Failed to mount dissected image: No such file or directory" and there's this soon before it, and FD 28 appears to be opened by `openat(26, ".", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 28`

```
[pid 2078413] mkdirat(26, "usr", 0755)  = -1 EROFS (Read-only file system)
```
FD 26 appeaars to be the `/tmp/dissect-kra4zP` directory, which was mounted by
```
[pid 2078413] openat(AT_FDCWD, "/tmp/dissect-kra4zP", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 26
[pid 2078413] mount("/proc/self/fd/9", "/proc/self/fd/26", "btrfs", MS_RDONLY|MS_NODEV, "norecovery") = 0
```
FD 9 appears to be `/dev/loop0p6` which is the root partition.

**Comment by poettering** [comment]
strace -y is your friend

**Comment by richardmaw-codethink** [comment]
> strace -y is your friend

Thanks, that'll be very handy in future.

**Comment by richardmaw-codethink** [comment]
Ok, I think the root cause for the error I was seeing was running this in a heavily overloaded VM.
I had not noticed the `systemd.default_device_timeout_sec=10` in `mkosi.conf ` and seeing `systemd-repart.service` finish and still see the device timeout led me to believe repart had somehow failed rather than that the timeout was tight enough and the VM slow enough that it processed the timeout ending before the disk became visible to systemd.

Under those conditions, the swap and scratch partitions could also timeout even without repart being run, and once I saw a timeout for the ttyS0 device.

Extending the default device timeout and continuing to run as many integration test VMs as you have CPUs but limiting them to 1GB and 1 CPU isn't a practical solution, since there are tests that assume a reasonably responsive system, e.g.

* UDEV assumes that an overrunning command is killed within 20 seconds
* RELOAD-RESTART assumes that running `systemctl daemon-reload --no-block` in a loop will result in it being rate-limited within 15 seconds.

Running half as many integration tests in parallel but giving them 2 CPUs and 2GB works more reliably.
