### ISSUE TITLE
[RFE] Allow symlinked "/loader" directory in sd-boot

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#31179]
### Component

systemd-boot

### Is your feature request related to a problem? Please describe

I came along this issue because [Bazzite](https://github.com/ublue-os/bazzite/), a [uBlue](https://universal-blue.org/) variant, uses a symbolic linked `/boot/loader` directory and noticed `bootctl` complaining about it and refusing to follow the symlink.

### Describe the solution you'd like

I'm aware that the [BLS](https://uapi-group.org/specifications/specs/boot_loader_specification/) mentions that symlinks are not allowed, but it could be enhanced to allow when using a `XBOOTLDR` partition using a filesystem that supports symlinks.
It would make certain stuff much easier and open posibilities.

See also my post on their discourse platform:
https://universal-blue.discourse.group/t/ublue-bootloader-fixup/534

**Comment by poettering** [comment]
sd-boot doesn't really support anything but vfat, and there are no symlinks on vfat.

I am really sure we should not allow this, as this would mean we'd start dealing with ttsuff that cannot be placed in regular ESPs anymore.

Also, why even?

**Comment by TriMoon** [comment]
I thought as much, and i actually agree with you...
As to the "WHY", see the linked post :wink: 

A related question if you don't mind:
Do the kernel and ramdisks mentioned in the loader entry config need to be on same disk/partition as the config file itself?
Eg. Can people place the loader entries in the ESP to load images from the `XBOOTLDR` partition if it exist?

**Comment by AdrianVovk** [comment]
The real fix here is to change ostree to handle vfat correctly, or to keep using grub.

GNOME OS / freedesktop-sdk have been carrying a patch to this effect for a long time now (years). carbonOS used to, until we dropped ostree entirely. Silverblue/Fedora never has, and thus you have the issue. Patch: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/patches/ostree/no-boot-symlink.patch. Looks like it should apply thru version v2023.8 of ostree. Relevant (but seemingly out-of-date) MR: https://github.com/ostreedev/ostree/pull/1967

**Comment by AdrianVovk** [comment]
>Do the kernel and ramdisks mentioned in the loader entry config need to be on same disk/partition as the config file itself?

At least for the kernel yes they do. According to the BLS:

> `linux` is the Linux kernel image to execute and takes a path relative to the root of the file system containing the boot entry snippet itself

As for initrd, I'm not sure. Loading the initrd is handled by the kernel's EFI stub, not by sd-boot. The [kernel docs](https://www.kernel.org/doc/html/latest/admin-guide/efi-stub.html) seems to imply that the firmware resolves relative paths for the kernel's EFI stub. If I had to guess, there's probably some EFI-specific device syntax that you can use to specify which disk and partition to load the initrd from (ala UNC path in Windows), but it would have to be mounted. TL;DR don't bother with it

**Comment by poettering** [comment]
> Do the kernel and ramdisks mentioned in the loader entry config need to be on same disk/partition as the config file itself?

yes. this is expicitly mentioned in the boot loader spec. paths in type 1 drop-ins are relative to the file system root they are on. i.e. type1 entries in the ESP use paths relative to the ESP's root, and type 1 enrties in the XBOOTLDR use paths relative to the XBOOTLDR root.

**Comment by poettering** [comment]
anyway, ostree is not compatible with sd-boot anyway, since ostre requires hardlinks or symlinks which are not supproted on vfat at all. 

hence not sure why we would even bother with this? ostree rooted in a grub world, and i see no way to make sd-boot compatible with that without becoming grub, and well, fuck that. ;-)

Kinda tempted to just close this?

**Comment by TriMoon** [comment]
Lets hope they see the light and fix their end i guess...
