### ISSUE TITLE
BAD_COPY_PASTE in src/basic/env-file.c

### ISSUE THREAD

**Issue by AlexRudyuk** [systemd/systemd#31187]
[src/basic/env-file.c](https://github.com/systemd/systemd/blob/00fcd79e65305a0d2657312b001467a055b04801/src/basic/env-file.c#L75C1-L82C66)

https://github.com/systemd/systemd/blob/00fcd79e65305a0d2657312b001467a055b04801/src/basic/env-file.c#L82

in line 82:
Line 82 contains a typo in the variable name: it should be `last_key_whitespace` instead of `last_value_whitespace,` based on the name of the case KEY:

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author A. Slepykh ([a.slepykh@fobos-nt.ru](mailto:a.slepykh@fobos-nt.ru)).

**Comment by dtardon** [comment]
There's no typo there. The variable is initialized for parsing of _value_ that is about to follow.
