### ISSUE TITLE
systemd-networkd does not realize the link is back up on it's own

### ISSUE THREAD

**Issue by qookei** [systemd/systemd#31192]
### systemd version the issue has been seen with

systemd-254.8-r1

### Used distribution

Gentoo Linux

### Linux kernel version used

6.6.13-gentoo-dist

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When using an AX88179 USB NIC, after booting, waking up from sleep, or unplugging the network cable and plugging it back the link should automatically be brought up.

### Unexpected behaviour you saw

The link is only brought up after running `networkctl` and remains untouched prior to that.

### Steps to reproduce the problem

1. Unplug the network cable
2. Observe `enp3s0f3u1c2: Lost carrier` in `systemctl status systemd-networkd`
3. Plug the network cable back in
4. Wait a bit
5. Observe no new log messages
6. Run `networkctl`
7. Observe `enp3s0f3u1c2: Gained carrier` in the log

**Comment by yuwata** [comment]
It sounds a bug in driver. Or do you reproduce the issue with other interface?

**Comment by qookei** [comment]
Wi-Fi on the same system works without issues, and I don't have other interfaces to test.

**Comment by qookei** [comment]
As for the driver, the NIC is using the cdc_ncm kernel driver.

**Comment by qookei** [comment]
Actually, I just remembered USB tethering is a thing on Android, and trying that, it works fine (using the rndis_host driver)

**Comment by yuwata** [comment]
Still that should be a driver issue. Please contact to the driver maintainer.

**Comment by poettering** [comment]
OK, let's close this here under the assumption this is a driver problem.

**Comment by qookei** [comment]
Sorry for the late response, could you point me to where I should report this bug to the kernel developers? Unsure if bugzilla.kernel.org is the appropriate place or if I need to report it on some mailing list.
