### ISSUE TITLE
systemd-gpt-auto-generator automatically generates units, manual says it oughtn't on the count of (a) not being EFI and (b) not/or having an ESP

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/systemd#31199]
### systemd version the issue has been seen with

255.3-1

### Used distribution

Debian 2024-01-20

### Linux kernel version used

6.6.11

### CPU architectures issue was seen on

aarch64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

not doing anything

### Unexpected behaviour you saw

generated
```ini
# /run/systemd/generator.late/systemd-remount-fs.service.d/50-remount-rw.conf
# Automatically generated by systemd-gpt-auto-generator

[Service]
Environment=SYSTEMD_REMOUNT_ROOT_RW=1 
```
(admittedly this one I don't really mind) and
```ini
# /run/systemd/generator.late/dev-disk-by\x2ddiskseq-1\x2dpart102.swap
# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=Swap Partition
Documentation=man:systemd-gpt-auto-generator(8)
After=blockdev@dev-disk-by\x2ddiskseq-1\x2dpart102.target

[Swap]
What=/dev/disk/by-diskseq/1-part102
```
(which is baffling) and the appropriate wants= links

### Steps to reproduce the problem

1. buy a Lenovo 300e (Google Hana) chromebook
2. format the eMMC to include properly rootfs- and swap-tagged partitions
3. install debian there
4. boot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Disabling root partition auto-detection, root= is defined.
Failed to chase block device, ignoring: No such file or directory
Probed fstype 'ext2' on partition /dev/disk/by-diskseq/1-part101.
Probed fstype 'swap' on partition /dev/disk/by-diskseq/1-part102.
Adding swap: /dev/disk/by-diskseq/1-part102
Failed to create unit file '/tmp/l/dev-disk-by\x2ddiskseq-1\x2dpart102.swap': File exists
Not an EFI boot, skipping loader partition UUID check.
Root partition not marked for growing the file system in the GPT partition table, not generating drop-in for systemd-growfs-root.service.
```

**Comment by nabijaczleweli** [comment]
appending here because the form doesn't have space

fdisk -l:
```
Disk /dev/mmcblk0: 29.12 GiB, 31268536320 bytes, 61071360 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 8648551F-D8FC-AC44-AA00-C0CA32C4A9BC

Device              Start      End  Sectors  Size Type
/dev/mmcblk0p1    3614720  4663295  1048576  512M Microsoft basic data
/dev/mmcblk0p2      16448    49215    32768   16M ChromeOS kernel
/dev/mmcblk0p3      51200  3614719  3563520  1.7G ChromeOS root fs
/dev/mmcblk0p11        64    16447    16384    8M unknown
/dev/mmcblk0p100  4663296  4712447    49152   24M ChromeOS kernel
/dev/mmcblk0p101  4712448 52682751 47970304 22.9G Linux root (ARM-64)
/dev/mmcblk0p102 52682752 61069311  8386560    4G Linux swap

Partition table entries are not in disk order.


Disk /dev/mmcblk0boot0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mmcblk0boot1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

fdisk -lx:
```
Disk /dev/mmcblk0: 29.12 GiB, 31268536320 bytes, 61071360 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 8648551F-D8FC-AC44-AA00-C0CA32C4A9BC
First usable LBA: 34
Last usable LBA: 61071326
Alternative LBA: 61071359
Partition entries starting LBA: 2
Allocated partition entries: 128
Partition entries ending LBA: 33

Device              Start      End  Sectors Type-UUID                            UUID                                 Name          Attrs
/dev/mmcblk0p1    3614720  4663295  1048576 EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 DE9260C7-B796-4681-82E1-6BF5E1DDC405 STATE         
/dev/mmcblk0p2      16448    49215    32768 FE3A2A5D-4F32-41A7-B725-ACCC3285A309 B9393B88-B27F-438D-BF88-93BE6E66E4A9 KERN-A        GUID:48,56
/dev/mmcblk0p3      51200  3614719  3563520 3CB8E202-3B7E-47DD-8A3C-7FF2A13CFCEC ACB76082-35D1-46F0-A8E9-97006C40B632 ROOT-A        
/dev/mmcblk0p11        64    16447    16384 CAB6E88E-ABF3-4102-A07A-D4BB9BE3C1D3 530A6C46-BDFA-7C40-A446-FC05001BDA82 RWFW          
/dev/mmcblk0p100  4663296  4712447    49152 FE3A2A5D-4F32-41A7-B725-ACCC3285A309 B404D487-BF0B-A842-B93F-742DFB050BA5 chwast-kernel GUID:49,56
/dev/mmcblk0p101  4712448 52682751 47970304 B921B045-1DF0-41C3-AF44-4C6F280D3FAE A1A44681-9DB6-5640-81F7-F469F51EAA7B chwast-root   
/dev/mmcblk0p102 52682752 61069311  8386560 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F 0AAF87E8-B293-964A-8073-605103B71460 chwast-swap   

Partition table entries are not in disk order.


Disk /dev/mmcblk0boot0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mmcblk0boot1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

cmdline: `cros_secure root=PARTLABEL=chwast-root rootwait console=pstore-1 console=tty1`

[kernel config](https://lfs.nabijaczleweli.xyz/0018-debian-chromebook-lenovo-300e-gen2-mtk-real/newkernel/mandeb+initrd+1+tabs2+reg+drm+adc+d_t_c-initrd.config)

Тhis system boots from the google bootloader/vboot2/depthcharge/whatever. No EFI obviously (in the firmware or in the kernel). Nor is there an ESP anywhere, as you can see. The manual would imply this means the generator wouldn't do anything, but it clearly does.

**Comment by grawity** [comment]
> No EFI obviously (in the firmware or in the kernel). Nor is there an ESP anywhere, as you can see. The manual would imply this means the generator wouldn't do anything, but it clearly does.

The manual doesn't say that anywhere; it says "this generator has no effect on **non-GPT** systems".

If there's no ESP, it won't look for the _root_ partition only (but that only applies to the initrd; it's moot when the root partition is already mounted), but given that it's explicitly told where the root partition was, it'll still look for everything else "on the same physical disk".

**Comment by nabijaczleweli** [comment]
[For me](https://manpages.debian.org/unstable/systemd/systemd-gpt-auto-generator.8.en.html) the manual says

Partition Type GUID | Name | Mount Point | Explanation
-- | -- | -- | --
SD_GPT_ROOT_X86_64       4f68bce3-e8cd-4db1-96e7-fbcaf984b709 | Root Partition (x86-64) | / | The first partition with this type UUID, located on the same disk as the       ESP, is used as the root file system / on AMD64 / 64-bit x86 systems.
SD_GPT_SWAP 0657fd6d-a4ab-43c4-84e5-0933c84b4f4f | Swap | n/a | All partitions with this type UUID on the same disk as the ESP are used       as swap.

which, to me, means that since there is no ESP then there must not be anything generated.

As you highlight, it does also say "GPT systems", which, without further refinement to say what the manual means by this, I don't think means anything at all. You'd be hard-pressed to find a *non*-GPT system – one with `CONFIG_EFI_PARTITION=n` – in the present day.

**Comment by grawity** [comment]
> You'd be hard-pressed to find such a "non-GPT system" – one with CONFIG_EFI_PARTITION=n – in the present day.

If you redefine "non-GPT system" to mean that, then yeah, sure. In the usual definition it means a system that doesn't *use* GPT, not one that isn't capable of understanding, and you'll find plenty of the former.

**Comment by poettering** [comment]
Discovering the root fs is one thing, finding the other fs is a different thing. Finding the root fs is an EFI-only thing (in fact, even requires a nice boot loader), since it's modelled around the boot loader reporting to us the used ESP via an efi var. And without uefi there are no efivars, hence no root fs discovery.

But the discovery of the other fs is modelled around where the root fs is. Thus, if you managed to mount the root fs already via other means than the other fs will still be auto-discovered.

You can turn off this logic in two way:

1. set `systemd.gpt_auto=0` on the kerne cmdline
2. set the SD_GPT_FLAG_NO_AUTO flag in the gpt part table entry for the partition, i.e. bit 63.

I think the docs are already clear enough about all this, no:


> This generator will only look for the root partition on the same physical disk where the EFI System Partition (ESP) is located. Note that support from the boot loader is required: the EFI variable LoaderDevicePartUUID of the 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f vendor UUID is used to determine from which partition, and hence the disk, from which the system was booted. If the boot loader does not set this variable, this generator will not be able to detect the root partition. See the Boot Loader Interface[3] for details.

> Similarly, this generator will only look for the other partitions on the same physical disk as the root partition. In this case, boot loader support is not required. These partitions will not be searched for on systems where the root file system is distributed on multiple disks,        for example via btrfs RAID.

I think we should probably just clsoe this, since this is documented clearly I think, has been like this since a long long time, and there are two documented mechanisms to disable this.

**Comment by nabijaczleweli** [comment]
I don't really want to disable it, it's just surprised me, because the documentation is not clear on this.

Well it *is* clear, but it explicitly says it will *not* happen on my system:

Partition Type GUID | Name | Mount Point | Explanation
-- | -- | -- | --
SD_GPT_SWAP 0657fd6d-a4ab-43c4-84e5-0933c84b4f4f | Swap | n/a | All partitions with this type UUID on the same disk as the ESP are used as swap.

No ESP => no swapon. This is what it says. This is not what the generator does.

Every type-UUID is formatted like this, except SD_GPT_ESP/SD_GPT_XBOOTLDR which say "on the same disk as the root partition".

**Comment by bluca** [comment]
It probably should say "same disk as the ESP or root partition" or something like that
