### ISSUE TITLE
qdisc cake options don't apply

### ISSUE THREAD

**Issue by RX14** [systemd/systemd#31226]
### systemd version the issue has been seen with

255.3-1-arch

### Used distribution

Arch

### Linux kernel version used

6.7.0-arch3-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Using the following network file:

```
[Match]
Name=wg-kanamin
Kind=wireguard

[Link]
RequiredForOnline=false
Multicast=yes

[Network]
Address=fe80::1de/64

[CAKE]
Bandwidth=200M
NAT=yes
RTTSec=30ms
```

I expect for systemd-networkd to reconfigure the qdisc as `qdisc cake 800d: dev wg-kanamin root refcnt 2 bandwidth 200Mbit diffserv3 triple-isolate nat nowash no-ack-filter split-gso rtt 30ms raw overhead 0`

### Unexpected behaviour you saw

Instead, systemd added the qdisc as `qdisc cake 800d: dev wg-kanamin root refcnt 2 bandwidth 200Mbit diffserv3 triple-isolate nonat nowash no-ack-filter split-gso rtt 100ms raw overhead 0`. All options are default except bandwidth.

### Steps to reproduce the problem

Create a unit file similar to the one above on a test interface, reconfigure, then check qdisc options with `tc qdisc`.

### Additional program output to the terminal or log subsystem illustrating the issue

debug logs from systemd-networkd: https://stephanie.is/tiril-ziduh

**Comment by yuwata** [comment]
Is the .network file really applied to the interface? Have you called `networkctl reload` or restarted networkd after the .network file edited? Can the cake setting be applied to another interface?

**Comment by RX14** [comment]
> Is the .network file really applied to the interface? Have you called `networkctl reload` or restarted networkd after the .network file edited? Can the cake setting be applied to another interface?

Please check the debug logs I provided from a `networkctl reload`, the traffic controls are applied, just wrongly. I checked `tc qdisc` before and no tc was applied to the interface, confirming again that the qdisc was applied by systemd. I also checked straces of networkd and `tc qdisc` and the `TCA_OPTIONS` from networkd and `tc qdisc` are vastly different in length.

**Comment by yuwata** [comment]
Thanks for the clarification.

A workaround for the issue is once remove the qdisc from the interface, i.e. `tc qdisc delete dev wg-kanamin ...`, then call `networkctl reconfigure wg-kanamin` or restart systemd-networkd.
Currently, already configured qdisc config seems not changed, that is, networkd always does something similar to `tc qdisc add` rather than `tc qdisc change` or `tc qdisc replace`.

**Comment by RX14** [comment]
I removed the qdisc and reconfigured, the qdisc was created solely by systemd-networkd, without replacing an existing qdisc. Despite that, the qdisc options were wrong. Are you sure that your proposed workaround is correct, because I couldn't get systemd to apply the options correctly using any method.

**Comment by RX14** [comment]
I tried to reproduce this after rebooting the machine but failed. I did a lot of debugging when I did have a reproducer in front of me, including following strace of the configuration process and reading source code, so I am convinced that a bug occurred similar to the one I described. However, the state required to produce the failure must be rare.

I'll leave this open to track the qdisc improvements you mentioned.

**Comment by epilatow** [comment]
I've been seeing similar problem with `systemd-255.5-1.4.hs+fb.el9.x86_64` while trying to reconfigure link Flow Control parameters (specifically `AutoNegotiationFlowControl`, `RxFlowControl`, and `TxFlowControl`) for a pre-existing link. I've been checking the status of flow control on the interface via `ethtool -a $IFACE`. No amount of `udevadm ...`, `systemctl ...` or `networkctl ...` subcommands seem to be able to change these parameters. I'm curious if this might be the same issue as described here @yuwata?

**Comment by DaanDeMeyer** [comment]
@yuwata Currently we use `NLM_F_CREATE | NLM_F_EXCL` for any netlink message that creates a new object. Isn't it as simple as switching to `NLM_F_CREATE | NLM_F_REPLACE` instead to replace existing objects?

**Comment by yuwata** [comment]
> @yuwata Currently we use `NLM_F_CREATE | NLM_F_EXCL` for any netlink message that creates a new object. Isn't it as simple as switching to `NLM_F_CREATE | NLM_F_REPLACE` instead to replace existing objects?

For some cases, yes, but not in general. At least for qdisc, NLM_F_REPLACE seems to work.

**Comment by schm0** [comment]
RTTSec does not automatically adjust the target (stuck at 5ms) like cake normally would do.
