### ISSUE TITLE
Provide access to seats without user login

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#31227]
### Component

loginctl, pam_systemd, systemctl, systemd, systemd-logind

### Is your feature request related to a problem? Please describe

Related: https://github.com/systemd/systemd/issues/22036

Currently, using `systemd-logind` for setups without kernel VTs (no built-in TTYs), is very tedious and involves a lot of tricks involving `socat` and multiple services & scripts. See https://github.com/n3rdopolis/fakekmscon for an example of a working setup.

When trying to replace kernel VTs with something like `cage foot` in a system service that uses `User=` (which is needed since `cage` normally requires a non-root user to execute it), you get the following cyclic dependency problem:

1. `cage`, a Wayland kiosk, wants a seat from `systemd-logind`.
2. However, `systemd-logind` only gives seats to logged in users, and `cage` is inside a system service by necessity (there's no TTYs available for login before this point).
3. `foot`, a Wayland terminal, creates PTS devices which can be logged into, however, `foot` is running inside `cage` and so is too late in the process.

### Describe the solution you'd like

I don't understand the technical details of where or what changes need to be made for seats to be available in such a setup, but for clarity, here's two solutions I'm thinking of.

1. Add a way for systemd services to be allocated seats, like with a `Seat=` option under `[Service]` vaguely similar to the `PAMName=` option.
2. And/or, add an `Autologin=` option for `logind.conf` to tell `systemd-logind` to immediately allocate a seat for a user, the same user as in the `cage foot` system service as configured with `User=`, without needing them to login.

### Describe alternatives you've considered

Besides the `socat`-based techniques mentioned earlier, `seatd.service` (as provided by the `wlroots` dependency: `libseat`) can provide a seat as it simply gives one to whoever accesses `/run/seatd.socket`, however, `systemd-logind` then isn't fully in control of the seat.

Functionally, it doesn't cause majors issues outside of `loginctl seat-status` printing errors (adding an argument for a specific seat then fixes it), however, it'd be nice to not need two seat-managing services running simultaneously.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
> 1. `cage`, a Wayland kiosk, wants a seat from `systemd-logind`.

I don't understand what this means.

seats are defined via udev rules. You assign hardware to a specific seat, and that makes up the seat.

> 2\. However, `systemd-logind` only gives seats to logged in users, and `cage` is inside a system service by necessity (there's no TTYs available for login before this point).

Use PAMName= in the service unit file, and make sure to set XDG_SEAT env var to the seat of your choice. That will ensure that your service gets a session and that the session is assigned to the selected seat.

> 3\. `foot`, a Wayland terminal, creates PTS devices which can be logged into, however, `foot` is running inside `cage` and so is too late in the process.

Too late for what precisely?

To assign devices to seats see this documentation:

https://www.freedesktop.org/software/systemd/man/latest/sd-login.html#udev%20Rules

To read up on pam_systemd and the env vars it looks for see this documentation:

https://www.freedesktop.org/software/systemd/man/latest/pam_systemd.html#Environment

**Comment by poettering** [comment]
> Besides the `socat`-based techniques mentioned earlier, `seatd.service` (as provided by the `wlroots` dependency: `libseat`) can provide a seat as it simply gives one to whoever accesses `/run/seatd.socket`, however, `systemd-logind` then isn't fully in control of the seat.

I don't know what seatd is, or what socat has to do with any of this?

**Comment by YHNdnzj** [comment]
> Add a way for systemd services to be allocated seats, like with a Seat= option under [Service] vaguely similar to the PAMName= option.

I assume you're actually talking about "seat/session _device access_", not "allocating seats". A seat is a collection of physical devices, which is established through udev  rules.

What you're asking for is precisely achieved through PAMName=login or something, so that pam_systemd would create session through logind and you'll be granted session dev access. What else is missing?

**Comment by Winterhuman** [comment]
I have an `mkosi` config if needed which can reproduce this problem inside `mkosi qemu`. Would sharing it possibly help, or is there some other debug method I should try to see what "VT number out of range" could be caused by?

**Comment by Winterhuman** [comment]
As for the `socat` stuff, the repo I linked explains it better than I can as to why it's needed, but the point I was generally making is that it's currently pretty complicated to get this idea working in practice.

"Too late for what": As in even if you logged into `/dev/pts/N` as created by `foot`, `foot` is running inside `cage` which could never of run because `cage` needs the session that login would of provided; the login can only happen after `cage` is run.

All the `pam_systemd` documentation mentions that a session is tie to a user logging in and out, which I thought meant that `PAMName=login` wasn't sufficient if this service runs before user login, however, are you saying this isn't actually the case?

**Comment by poettering** [comment]
> pam_systemd(login:session): Failed to create session: VT number out of range

This you only see if your seat has VTs but you didn't specify a VT number, i.e. you used seat0 and your kernel has the VT logic enabled The latter is detected if /sys/class/tty/tty0/active can be opened.

You claimed you have no VTs. It seems you do?

Either pick a different seat name, or disable VTs?

**Comment by poettering** [comment]
> As for the `socat` stuff, the repo I linked explains it better than I can as to why it's needed, but the point I was generally making is that it's currently pretty complicated to get this idea working in practice.

Man, sorry, I am not going to read through that. You made me read up about "seatd" and what this is, already, and wtf, you really lost me there. You are making everything a mess, by inserting yet another layer of abstraction? If you don#t want to use our APIs, good for you, but then maybe you shouldn't be coming back to us for any of this?

**Comment by Winterhuman** [comment]
I've tried adding `InaccessiblePaths=/sys/class/tty/tty0` to the service, but it doesn't seem to of changed anything unfortunately. Is there another way to tell `systemd-logind` not to use the VT logic?

**Comment by poettering** [comment]
> "Too late for what": As in even if you logged into `/dev/pts/N` as created by `foot`, `foot` is running inside `cage` which could never of run because `cage` needs the session that login would of provided; the login can only happen after `cage` is run.

I really don't know what foot and cage is, and I am not sure I want to know.

> All the `pam_systemd` documentation mentions that a session is tie to a user logging in and out, which I thought meant that `PAMName=login` wasn't sufficient if this service runs before user login, however, are you saying this isn't actually the case?

I cannot parse this.

pam_systemd allocates a session of a user. A session is either bound to one seat or it's unbound. A seat consists of local physical hw. Typically a GNOME or VT session is bound to a seat, but an ssh login is not.

PAMName=login is not OK to use. login is something getty logins use, it assumes you have a TTY. If you use that for something else things won#t work. Define your own PAM service file.

**Comment by Winterhuman** [comment]
The goal is to make the service work without requiring TTYs, and ignore them if they are present so systems configured either way act the same.

Some good news though! Now that I've added `InaccessiblePaths=/sys/class/tty/tty0` as a drop-in to `systemd-logind.service`, since I realised setting it in the `cage foot` service wouldn't do anything, it's actually somewhat working again (the keyboard isn't responding, but I should be able to fix this?).

Sorry for the confusing report, I'm trying to figure this out myself.

**Comment by Winterhuman** [comment]
Just before I close this, is `InaccessiblePaths=` with `systemd-logind.service` the best way to stop logind from detecting TTYs, or is there a more official way I've missed?

**Comment by poettering** [comment]
> The goal is to make the service work without requiring TTYs, and ignore them if they are present so systems configured either way act the same.

I am not sure that's realistic, because the VT subsystem will then start fighting for the devices with you. If the VT subsystem is there you need to cooperate with it, you cannot just ignore it.

**Comment by poettering** [comment]
> Just before I close this, is `InaccessiblePaths=` with `systemd-logind.service` the best way to stop logind from detecting TTYs, or is there a more official way I've missed?

I already mentioned that this doesn't work, because it leaves the inode around. And even if this would work, it likely only tricks one part of logind into believing that there is not VT, but others might not.

It's a hack. Don't do this.

**Comment by Winterhuman** [comment]
Okay, so I **must** handle VTs if they do genuinely exist, otherwise it causes as whole bunch of possible issues. As for the "unless your software asks for it to be redirected" part, would the software you're referring to be `systemd-logind` or `cage`?

**Comment by poettering** [comment]
> Okay, so I **must** handle VTs if they do genuinely exist, otherwise it causes a whole bunch of possible issues.

Yes.

>  As for the "unless your software asks for it to be redirected" part, would the software you're referring to be `systemd-logind` or `cage`?

I don't know what cage is. But I meant: your wayland server, your gnome, your kde.

**Comment by Winterhuman** [comment]
Yeah, that's what `cage` would be; a Wayland kiosk (one app) compositor. In that case, I think I have an idea of how to handle this. Sorry again for the confusion, but thanks for your help! Closing issue

**Comment by Winterhuman** [comment]
@poettering I've managed to get the hacky and non-hacky versions of the above service working! However, I have one more question:

Does setting `console=ttynull` on the kernel cmdline ([added in this patch](https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/tty.git/commit/?h=tty-next&id=3117ff13f104e98b05b61e19cc754d1377e92e15)) solve the issue of input going to the VT subsystem at the same time in the hacky case, or is it still a security issue even with this TTY driver?

**Comment by poettering** [comment]
> @poettering I've managed to get the hacky and non-hacky versions of the above service working! However, I have one more question:
> 
> Does setting `console=ttynull` on the kernel cmdline ([added in this patch](https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/tty.git/commit/?h=tty-next&id=3117ff13f104e98b05b61e19cc754d1377e92e15)) solve the issue of input going to the VT subsystem at the same time in the hacky case, or is it still a security issue even with this TTY driver?

I can't tell you that. I don't grok the implications, never seen that before.

But I'd assume it is orthogonal to the VT situation. The console=ttynull will not make the VT subsys go away

**Comment by Winterhuman** [comment]
Damn, that's what I thought. The driver works by discarding all writes, so I was hoping it would make the input going to the VT subsystem inaccessible and preventing the "plenty bugs about just this in the past" you mentioned.

**Comment by aeroevan** [comment]
Sorry to post on an old issue, but this is the closest to an issue 

Not sure if this would be related, but user services with enable-linger that assume devices will be attached (like running SDRs, see https://github.com/airspy/airspyhf/issues/46 for an example) won't be assigned a seat, so they won't be able to see uaccess tagged devices.

is there some way to either associate a uaccess tagged device directly in a systemd user service or is it possible for enable-linger to also bring a specific seat with an attached device?
