### ISSUE TITLE
systemctl: 'daemon-reload' warning is always shown when foo.service.d/bar.conf exists

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#3123]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> git snapshot 4f4d6ee4be1c5d3bb2f3ebce7d2d332285963830 

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora rawhide
### In case of bug report: Expected behaviour you didn't see

> systemctl do not output the following warning
### In case of bug report: Unexpected behaviour you saw

> systemctl shows the following warning
> 
> ```
> # systemctl daemon-reload
> # systemctl start slurmctld.service
> Warning: slurmctld.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> # systemctl stop slurmctld.service
> Warning: slurmctld.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> # systemctl status slurmctld.service
> ● slurmctld.service - Slurm controller daemon
>    Loaded: loaded (/usr/lib/systemd/system/slurmctld.service; disabled; vendor preset: disabled)
>   Drop-In: /etc/systemd/system/slurmctld.service.d
>            └─after.conf
>    Active: inactive (dead) since Tue 2016-04-26 13:16:06 JST; 30s ago
>   Process: 12180 ExecStart=/usr/sbin/slurmctld $SLURMCTLD_OPTIONS (code=exited, status=0/SUCCESS)
>  Main PID: 12182 (code=exited, status=0/SUCCESS)
> (snip)
> Warning: slurmctld.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> ```
### In case of bug report: Steps to reproduce the problem

> 1. create service drop-in directory and .conf file
> 2. run systemctl daemon-reload or reboot system
> 3. call systemctl start, stop, or status command.
> 
> I use the following service and drop-in conf file.
> 
> ```
> # systemctl cat slurmctld.service
> # /usr/lib/systemd/system/slurmctld.service
> [Unit]
> Description=Slurm controller daemon
> After=network.target
> ConditionPathExists=/etc/slurm/slurm.conf
> [Service]
> Type=forking
> EnvironmentFile=-/etc/sysconfig/slurmctld
> ExecStart=/usr/sbin/slurmctld $SLURMCTLD_OPTIONS
> ExecReload=/bin/kill -HUP $MAINPID
> PIDFile=/var/run/slurmctld.pid
> [Install]
> WantedBy=multi-user.target
> # /etc/systemd/system/slurmctld.service.d/after.conf
> [Unit]
> After=nss-user-lookup.target munge.service
> ```
> 
> Note that the above service and drop-in conf files work and systemctl does not show warning in systemd-229-14.fc25.x86_64

**Comment by poettering** [comment]
Fix waiting in #3170.

**Comment by yuwata** [comment]
Thanks. The commits 87ec20e and ab932a6 work for me.
