### ISSUE TITLE
DHCP client option 28 "Broadcast Address"

### ISSUE THREAD

**Issue by marlene-jacquier** [systemd/systemd#31252]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

DHCP option 28 doesn't seem to be supported in the DHCP client provided by systemd, is there a plan to support it ?

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by poettering** [comment]
It *is* used. See function dhcp4_request_address() in src/network/networkd-dhcp4.c, the call to sd_dhcp_lease_get_broadcast().

What makes you think it isn't supported? Did you test it and it didn't work for you?

**Comment by poettering** [comment]
Ah, you are on v250. That's simply too old. See a49cf370ac97ad6f5439968842f345c87bdc32a2

**Comment by yuwata** [comment]
I will take a look tomorrow. Tentatively reopen this issue

**Comment by yuwata** [comment]
If you want to explicitly request broadcast option, then please set `RequestOptions=28` in `[DHCPv4]` section.
If the server provides broadcast option, then networkd uses the broadcast address, as already mentioned in the above.

**Comment by marlene-jacquier** [comment]
Thanks a lot, I completely missed this setting...
