### ISSUE TITLE
DHCP DUID code cannot be released this way

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#3127]
This is an issue to track the DHCP DUID configuration code in networkd, in order to work towards making this releasable.

I made some initial changes in PR #3126, but I am still not happy with the code that this would be releasable. Sorry for not looking at this thoroughly earlier. But I must say I don't think we should do a release in the current state.

The following changes should be made before we can release this:
- The DUID should get its on structure "typedef struct DUID DUID" or so, that incorporates the duid_type, dhcp_duid_type, dhcp_duid_len, dhcp_duid[] fields into one, and config_parse_duid_rawdat() should simply get a pointer to that, so that it doesn't have to distuingish Manager and Network objects.
- The config_parse_duid_rawdata() must work without checking the associated Manager->duid_type or Network->duid_type. Our settings may appear in any order, and checking the value from the parser call breaks that. This is a deal-breaker.
- What's the point of maintainting both duitype and dhcp_duid_type, and in fact converting one into the other by simple casts? if the type is a 16bit value, then use it like that everywhere, don't define an enum type for it (there are anonymous enums for this kind of thing)
- The DUIDType= field needs documentation in the man pages
- Why does DUIDRawData= expect the ":" seperators between bytes? Is that established syntax by other tools? If not, I'd prefer if this could just be a hexdump without any separators, after all they are completely redundant.

CC @vinaykul.

**Comment by vinaykul** [comment]
Thanks for the detailed review. I'm dealing with some release critical issues at work. I'm hoping to find a way to address these as soon as I get some cycles. 

The ':' separators in DUIDRawData is a standard way of representing DUID, MAC address, IPv6 addresses, etc. Currently, dhcpcd prints DUID in this format. It is very easy to read and if the user needs to type it in, a lot less error prone. 

The only good way to address the ordering issue is perhaps to find a way to not have the DUIDType at all, and determine the type automatically. This would need a full implementation of the design that @teg had proposed in https://github.com/systemd/systemd/issues/394#issuecomment-124225892 which is fairly complex. I don't know if we can determine type without ambiguity. Currently only RawData is supported and DUIDType code was added for future support. 

duid_type holds the user specified type including type 'raw' per https://github.com/systemd/systemd/pull/2761#issuecomment-190835118 But 'raw' only means that the actual DUID type ( https://tools.ietf.org/html/rfc3315#section-9.1 ) is specified in the RawData which is set in dhcp_duid_type and passed to the dhcp_client configuration API. So the two fields hold two different meanings.

**Comment by poettering** [comment]
@vinaykul ok, if other tools. such as dhdpcd use the ":" format, then that's OK... Should probably have a comment though... Something like "We use the same colon-separated format as dhcpcd here." or so.

**Comment by poettering** [comment]
I figure this has all been implemented by #3156. Closing this one hence.
