### ISSUE TITLE
missing_syscall.h wrapper for close_range() doesn't match glibc API

### ISSUE THREAD

**Issue by smcv** [systemd/systemd#31270]
### systemd version the issue has been seen with

255

### Used distribution

n/a

### Linux kernel version used

n/a

### CPU architectures issue was seen on

other

### Component

other

### Expected behaviour you didn't see

Recent glibc unistd.h declares close_range() as:

```
int close_range (unsigned int, unsigned int, int);
```

### Unexpected behaviour you saw

systemd's `missing_syscall.h` has the signedness of all arguments the other way round:

```
int close_range (int, int, unsigned);
```

and then does some hopefully-no-op arithmetic to turn that into three unsigned arguments for the underlying syscall.

### Steps to reproduce the problem

n/a, source code inspection only (while adding a close_range() fallback to libglnx, which has a subset of systemd's missing_syscall infrastructure)

**Comment by poettering** [comment]
hmm, that is so weird. why would glibc do it like that?

on the kernel side an fd is always unsigned, but in userspace it's always signed, so why would they depart from that here?

**Comment by poettering** [comment]
freebsd also uses unsigned...

so weird. i guess we should change our definition then to match the glibc one...

**Comment by smcv** [comment]
I think it's using unsigned because of the `close_range (3, ~0U, flags)` pattern - making at least the second argument be unsigned avoids the arithmetic that systemd's fallback implementation needed to do.
