### ISSUE TITLE
systemd not honouring TimeoutStopSec

### ISSUE THREAD

**Issue by ihatethecloud** [systemd/systemd#31288]
### systemd version the issue has been seen with

239

### Used distribution

AlmaLinux 8.9

### Linux kernel version used

4.18.0-513.9.1.el8_9.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Systemd sending SIGTERM and then waiting for my_service to shutdown for TimeoutStopSec=400 before sending SIGKILL.

### Unexpected behaviour you saw

my_service stopped with SIGKILL after 90 seconds

### Steps to reproduce the problem

```
[Unit]
Description=My Service
Wants=network-online.target
After=network-online.target

[Service]
Restart=on-failure
TimeoutStopSec=400
TimeoutStartSec=100
ExecStart=/opt/bin/myservice run
ExecStop=/opt/bin/myservice stop
Type=notify
NotifyAccess=all

[Install]
WantedBy=default.target
```

stopping the takes ~ 173 seconds
```
$ systemctl stop my_service.service
Feb 12 16:15:34 server systemd[1]: Stopping My Service...
Feb 12 16:18:27 server systemd[1]: my_service.service: Succeeded.
Feb 12 16:18:27 server systemd[1]: Stopped My Service
```

reboot causes a SIGKILL to my_service after 91 which is consistent with DefaultTimeoutStopSec=90.
```
$ reboot
Feb 12 15:57:13 server systemd[1]: Stopping My Service...
Feb 12 15:58:44 server systemd[1]: my_service.service: Main process exited, code=exited, status=137/n/a
Feb 12 15:58:44 server systemd[1]: my_service.service: Failed with result 'exit-code'.
Feb 12 15:58:44 server systemd[1]: Stopped  My Service.
```

**Comment by poettering** [comment]
That's not how this works. If you define ExecStop=, then it's assumed that it does the stopping of your service, and the stop timeout is applied to that. If the stop command terminates earlier than that then we'll immediately do the SIGKILL of whatever is remaining.

Or in other words: your ExecStop= command must be synchronous, i.e. terminate the service correctly and ensure it's complete, so that the only left-overs that might remain are fine to be killed via SIGKILL.

This explained in very much detail in the man page, for ExecStop= btw.

https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#ExecStop=

Hence I think we don#t really have to do anything here: the behaviour is as intended, and I think it makes sense that way and is amply documented.

**Comment by OhNoMoreGit** [comment]
> If the stop command terminates earlier than that then we'll immediately do the SIGKILL of whatever is remaining.

This doesn't appear to be the case on systemd 253. For instance:

```
[Service]
ExecStart=perl -e '$$SIG{TERM} = "IGNORE"; sleep'
ExecStop=true
TimeoutStopSec=120
```

waits the full 120 seconds when it is stopped. Is this not intended?

**Comment by ihatethecloud** [comment]
I have the following unit.

```[Unit]
Description=Podman container-myservice.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=no
TimeoutStopSec=200
ExecStart=/usr/bin/podman run \
	--cidfile=%t/%n.ctr-id \
	--cgroups=no-conmon \
	--rm \
	--sdnotify=conmon \
	-d \
	--replace \
	--name=myservice \
	--security-opt seccomp=unconfined \
	--label io.podman.compose.config-hash=123 \
	--label io.podman.compose.project=myservice \
	--label io.podman.compose.version=0.0.1 \
	--label com.docker.compose.container-number=1 \
	--label com.docker.compose.service=myservice \
	--network host \
	--cap-add CAP_SYS_PTRACE \
	--cap-add CAP_NET_ADMIN \
	--cap-add SYS_RAWIO \
	-e "PS1=[\\u@\\h (myservice) \\W]\\$$ " \
	-v /mnt/data/myservice:/mnt/data 
	--add-host nginx:127.0.0.1 project/myimage
ExecStop=/usr/bin/podman stop \
	--ignore -t 200 \
	--cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm \
	-f \
	--ignore -t 200 \
	--cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=default.target
```

Stopping with systemctl stop is fast.

```
$ sudo systemctl stop container-myservice.service
Feb 14 14:31:02 server systemd[1]: Stopping Podman container-myservice.service...
Feb 14 14:31:03 server podman[19658]: e5f5904ee9feb17f130f931be3269e7cec36ec47307417a0d952b5f863c4c52b
Feb 14 14:31:03 server podman[19749]: e5f5904ee9feb17f130f931be3269e7cec36ec47307417a0d952b5f863c4c52b
Feb 14 14:31:03 server systemd[1]: container-myservice.service: Succeeded.
Feb 14 14:31:03 server systemd[1]: Stopped Podman container-myservice.service.
```


Stopping with reboot

podman stop keeps running
```
 │ ├─container-myservice.service
           │ │ ├─19983 /usr/bin/conmon --api-version 1 -c 2d4e793d7b4552744ae051f61f5650b8924a6bdbe7bf49a9dfde9f508534c91d -u 2d4e793d7b4552744ae051f61f5650b8>
           │ │ └─20284 /usr/bin/podman stop --ignore -t 100 --cidfile=/run/container-myservice.service.ctr-id
```

after the reboot looking at the journal I see a 90 second timeout between stopping and killing which is consistent with DefaultTimeoutStopSec=90s.
```
Feb 14 14:34:14 server systemd[1]: Stopping Podman container-myservice.service...
Feb 14 14:35:24 server systemd[1]: container-myservice.service: Stopping timed out. Terminating.
Feb 14 14:35:44 server systemd[1]: container-myservice.service: Main process exited, code=exited, status=137/n/a
Feb 14 14:35:44 server systemd[1]: container-myservice.service: Failed with result 'timeout'.
Feb 14 14:35:44 server systemd[1]: Stopped Podman container-myservice.service.
```

Worth metioning the fact that the container has system running inside it. If I run the ExecStop command the container closes cleanly after a few seconds.

```
$ sudo /usr/bin/podman stop --ignore -t 100 --cidfile=/run/container-myservice.service.ctr-id
$ sudo podman inspect --format '{{.State.ExitCode}}' myservice
0
```

Somehow my container doesn't understand SIGTERM if the podman stop is sent by systemd.
