### ISSUE TITLE
Delegation not respected while creating a transient scope via StartTransientUnit DBus API

### ISSUE THREAD

**Issue by idleroamer** [systemd/systemd#31295]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39

### Linux kernel version used

6.5.6-300.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

A scope created via the StartTransientUnit() of the systemd DBus API by an unpriv user should create the delegated controls (or the default ones) with the right ownership.
The right ownership would be the user who initiated the API call as there is no explicit "User" field available in `scope`s. That would be the intuitive (expected) behaviour which would be similiar to `service` units behaviour.

```
osboxes@fedora:~1$ cat /sys/kernel/cgroup/delegate 
cgroup.procs
cgroup.threads
cgroup.subtree_control
memory.oom.group
memory.reclaim
```
I would expect that the `/sys/fs/cgroup/<dummy>.slice/<dummy>.scope/{cgroup.procs,cgroup.threads,cgroup.subtree_control,memory.oom.group,memory.reclaim}` to be owned by the user invoked the DBus call.

The unit properties show that `Delegation` is set via `systemctl show <dummy>.scope`
```
Delegate=yes
DelegateControllers=cpu cpuacct cpuset io blkio memory devices pids bpf-firewall bpf-devices bpf-foreign bpf-socket-bind bpf-restrict-network-interfaces
```

### Unexpected behaviour you saw

The above controllers are owned by root.

### Steps to reproduce the problem

A simple python script to reproduce the issue
```
import dbus
from random import randint

bus = dbus.SystemBus()
systemd = bus.get_object('org.freedesktop.systemd1', '/org/freedesktop/systemd1')
manager = dbus.Interface(systemd, 'org.freedesktop.systemd1.Manager')

unit_name = ''.join(["{}".format(randint(0, 9)) for num in range(0, 10)]) + '.scope'

result = manager.StartTransientUnit(unit_name, 'fail', [('Slice', '<dummy>.slice'), ('DefaultDependencies', False),
                   ("PIDs", [dbus.UInt32(<some-pid>)]), ("Delegate", True)], [])
```

**Comment by poettering** [comment]
You need to specify the "User" property to delegate the cgroup to some user.

**Comment by poettering** [comment]
You need 03860190fefce8bbea3a6f0e77919b882ade517c at least

**Comment by poettering** [comment]
i.e. 252.

**Comment by poettering** [comment]
but you said you have v254 anyway? so all should be good?

**Comment by idleroamer** [comment]
yes, we are good. It is working fine in v254.
