### ISSUE TITLE
Key data incorrect?

### ISSUE THREAD

**Issue by delijati** [systemd/systemd#31321]
### systemd version the issue has been seen with

systemd 255 (255.2-2-manjaro)

### Used distribution

Manjaro 23.1.3

### Linux kernel version used

6.6.10-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

systemd-cryptsetup asks for password but password file is given:
```
❯ sudo /usr/bin/systemd-cryptsetup attach luks-<UID>/dev/disk/by-uuid/<UID> /home/foo/usbcrypttab.keyfile
Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/<UID> 
Failed to activate with key file '/home/foo/usbcrypttab.keyfile'. (Key data incorrect?)
🔐 Please enter passphrase for disk Samsung_SSD_970_EVO_500GB (luks-<UID> ): (press TAB for no echo) 
```
but cryptsetup works:
```
❯ sudo cat /home/foo/usbcrypttab.keyfile | sudo cryptsetup open --verbose --test-passphrase /dev/disk/by-uuid/<UID> 
Es ist kein verwendbares Token verfügbar.
Schlüsselfach 0 entsperrt.
Befehl erfolgreich.
```

**Comment by poettering** [comment]
there's a difference beteween a passphrase and a keyfile: newline handling.

you are comparing apples and oranges here. use `cryptsetup --key-file=-` if you want to compare the commands. See the man page comment explicitly about that in the cryptsetup docs.
