### ISSUE TITLE
What /usr/lib/systemd/systemd-shutdown do?

### ISSUE THREAD

**Issue by korpe1** [systemd/systemd#31353]
I investigate shutdown process of Linux and I can't understand /usr/lib/systemd/systemd-shutdown file, what it does?

AFAIK shutdown process is:
1. shutdown/reboot etc command ask systemd process (/usr/sbin/init) to shutdown via D-Bus(?)
2. systemd process switch to shutdown.target/reboot.target and execute services that belongs to them

And following is unclear. I have heard that systemd process replace itself with /usr/lib/systemd/systemd-shutdown, but why? Systemd process need anyway handle all processes to stop. If it replace itself before that all processes become zombie, right?

3. ???
4. Linux (kernel) shutdown

**Comment by DaanDeMeyer** [comment]
@korpe1 This is an issue tracker, not a forum for questions. Please send any questions on how systemd works to the systemd-devel mailing list.

**Comment by YHNdnzj** [comment]
`systemd-shutdown(8)` should have a pretty straightforward explanation for this. 

But yeah, please send further questions to the mailing list instead, if there's any.

**Comment by korpe1** [comment]
> @korpe1 This is an issue tracker, not a forum for questions. Please send any questions on how systemd works to the systemd-devel mailing list.

Oh, sorry then 😅 Can you though shortly tell or link explanation, what is /usr/lib/systemd/systemd-shutdown and does it really replace the init?

**Comment by korpe1** [comment]
> `systemd-shutdown(8)` should have a pretty straightforward explanation for this.
> 
> But yeah, please send further questions to the mailing list instead, if there's any.

Oh that helps:

       When these services are run, they ensure that PID 1 is replaced by the
       /usr/lib/systemd/systemd-shutdown tool which is then responsible for
       the actual shutdown. Before shutting down, this binary will try to
       unmount all remaining file systems (or at least remount them
       read-only), disable all remaining swap devices, detach all remaining
       storage devices and kill all remaining processes.

       It is necessary to have this code in a separate binary because
       otherwise rebooting after an upgrade might be broken — the running PID
       1 could still depend on libraries which are not available any more,
       thus keeping the file system busy, which then cannot be re-mounted
       read-only.

But one question: okay, so /usr/lib/systemd/systemd-shutdown really replace the init and above is explanation for this, but it also says "/usr/lib/systemd/systemd-shutdown .. this binary will try to .. kill all remaining processes.". How this is possible? If the init replace itself with systemd-shutdown binary and not kill processes, all processes become zombie?
