### ISSUE TITLE
SystemMaxUse not work with other machine-id files. How to delete the other machine-id journald directories

### ISSUE THREAD

**Issue by copyandrun** [systemd/systemd#31368]
Is there any easy way to delete the other machine-id journald directories?
![image](https://github.com/systemd/systemd/assets/75425799/ef06f7c0-676b-4b16-9940-2fc1c0421944)
I think i can use a script to do this. But is there any way to do this in systemd?

**Comment by poettering** [comment]
There's something wrong with your setup: your machine ID should be stable and thus not result in multiple directories.

There's a bug submisson form for a reason. Please fill it in. If you don't we cannot help you.
