### ISSUE TITLE
Future of halt, poweroff, reboot and shutdown commands

### ISSUE THREAD

**Issue by korpe1** [systemd/systemd#31366]
From https://github.com/systemd/systemd/issues/31359#issuecomment-1949029090:
> I'm worried about this PR. I have nothing against drop support for `shutdown` interface someday, but I think `halt`, reboot and `poweroff` should keep here forever. In addition to backward compatibility, them are useful and logical shorthands for `systemctl [halt, poweroff, reboot]` and just make sense. And `shutdown` is just an old relic then scheduling will be supported in systemctl.
> 
>> if you drop support for that, then also drop reboot/poweroff as my PR does.
>>
>>_Originally posted by @poettering in https://github.com/systemd/systemd/issues/31251#issuecomment-1934120338_

**Comment by poettering** [comment]
Hmm, that discussion was about chainloading sysvinit legacy commands if systemd tools are invoked on sysvinit systems.

The discussion was not about dropping the compat comands that we provide if you use systemd tools on systemd systems.
