### ISSUE TITLE
Extending a R/O base OS similar to sysext but for the whole OS.

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#31376]
### Is your feature request related to a problem? Please describe

While brainstorming on the [`uBlue/Bazzite`](https://discord.com/channels/1072614816579063828/1207724265516957706) discord server i commented the below:
> So we can't use `sysext` to "package" sub parts of the base-OS to make up an OS variant...
Maybe we need to propose that to `systemd` 😉
A new `systemd-osext` maybe 🙂

I would love to have an atomic OS that can update specific OS-Parts in an immutable way while still allowing the admin at the end to override parts of the whole OS.

What do you think guys, especially @poettering :wink: 

### Describe the solution you'd like

Similar functionality as `systemd-sysext` / `systemd-confext` but this time for the base OS parts.

Yes this would need an extra "dependency" functionality to make parts depend on certain versions or version ranges of other parts of the OS or extensions that are applied in same way.

### Describe alternatives you've considered

N/A

### The systemd version you checked that didn't have the feature you are asking for

254.9-1.fc39

**Comment by bluca** [comment]
What does "base OS parts" mean precisely? The OS vendor is shipped in /usr and the configuration in /etc. Everything else is local. What's the use case?

**Comment by TriMoon** [comment]
By "base OS parts" i mean the individual packages that get installed that form the OS.

Respective packages have files in them that belong to __THEM__, like what is used in `deb`, `rpm` packages etc...
Which means some need to populate fe. `/lib`, some populate other dirs, some populate a combination of dirs...

Basically anything that is loaded or used after the `systemd` functionalities have been setup and ready for usage by the rest of the bootup.

Use case would most likely be a second-stage `initrd` that populates the final filesystem for usage.
Thus not an ability to modify the system while it is running in it's final stage...

**Comment by bluca** [comment]
> Which means some need to populate fe. /lib

/lib is a symlink to /usr/lib

> maybe even /dev who knows

/dev is a tmpfs, no packages can install to it, it's literally impossible

> Basically anything that is loaded or used after the systemd functionalities have been setup and ready for usage by the rest of the bootup.

This is already covered by /usr and /etc. Everything an OS ships is shipped to /usr or /etc, everything else is generated locally

**Comment by TriMoon** [comment]
hmmm let me think a bit more about what you say... :thinking:

**Comment by TriMoon** [comment]
@bluca I did some testing using a `confext` and found a **major** flaw, well at least IMHO:

When an `confext` is "merged in" the whole `/etc` subtree gets R/O, which is of-course not desirable due to the usage of that tree for the local admin.
See: #31376
