### ISSUE TITLE
mutable /etc/ leayers in confext

### ISSUE THREAD

**Issue by TriMoon** [systemd/systemd#31392]
### systemd version the issue has been seen with

254.9-1.fc39

### Used distribution

uBlue/Bazzite

### Linux kernel version used

6.7.4-204.fsync.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-confext

### Expected behaviour you didn't see

Keeping the `/etc` tree R/W for the admin, minus the actual files inside the `confext` which would be R/O as expected.

### Unexpected behaviour you saw

A single `confext` merged into the system will render the whole `/etc` OS-tree __Read-Only__.

### Steps to reproduce the problem

1. Create a simple `confext` with one service file/conf inside it, in proper tree-struture, along with a `extension-release` file.
_(For ease i used a directory instead of a raw image)_
1. `sudo systemd-confext merge`
1. `sudo touch /etc/test123` <-- will give an error.
1. `sudo systemd-confext unmerge` to revert.

**Comment by TriMoon** [comment]
As an end-user, one expects that only the parts inside the `confext` that get "merged" into the system will be R/O, while the rest of `/etc` remains R/W for the admin to alter as wanted as usual.
But as-is this functionality locks the whole `/etc` OS-tree which is NOT what any end-user of this functionality expects. (despite it being mentioned in the docs briefly somewhere)

**Comment by t-lo** [comment]
@TriMoon You might be interested in https://github.com/systemd/systemd/pull/31000 :wink:

**Comment by TriMoon** [comment]
@t-lo Yea i noticed that and commented in https://github.com/uapi-group/specifications/pull/78#issuecomment-1952611735 already as you saw :+1: 
although the optional R/W in that topic might be something that could be wanted, in this topic `/etc` should stay R/W by default don't you agree? :wink:

**Comment by poettering** [comment]
> As an end-user, one expects that only the parts inside the `confext` that get "merged" into the system will be R/O, while the rest of `/etc` remains R/W for the admin to alter as wanted as usual.
> But as-is this functionality locks the whole `/etc` OS-tree which is NOT what any end-user of this functionality expects. (despite it being mentioned in the docs briefly somewhere)

sysext/confext are not really "end-user" facing. They are tools for OS builders really. Yeah, traditional desktop systems and the tools for that expect to be able to write to arbitrary files in /etc/, but confext is not really designed with that usecase in mind. With #31000 things will be opened up a bit, for specific usecases, but that's still not primarily focussed on a desktop usecase.

I mean, what are you using confext for, if I may ask? What's your specific usecase?

The concept was implemented with immutable OS in mind, which want to extend the immutability to /etc/ and ensure it's always a combination of various immutable images. With #31000 this is opened up a bit, so that on top of all that you can also have a mutable layer, but at it's core it's focussed on OSes which care about immutability (cryptographic even, dm-verity and stuff), hence I am curious what you intend to use it for?

**Comment by TriMoon** [comment]
@poettering 
> sysext/confext are not really "end-user" facing.

By end-user in that sentence's context i actually meant the local admin being the end-user of this functionality...

> The concept was implemented with immutable OS in mind, which want to extend the immutability to /etc/ and ensure it's always a combination of various immutable images.

That could be done in the `initrd` phase to mount `/etc` R/O.

I don't quite understand why using a feature, that can overlay stuff inside a neatly distributed raw image, would render the `/etc` tree R/O which is in principle designed to give the local admin freedom to make changes in.

> I mean, what are you using confext for, if I may ask? What's your specific usecase?

My goal was to be able to "package" certain configurations under `/etc` in a locked-down form, but keep the spirit of the `/etc` tree R/W.
Thus only the parts of the applied `confext` would be "locked-down".
The current state as-is, is just all R/O or not :disappointed:

**Comment by TriMoon** [comment]
By the way i just noticed you changed the title, but...
But this topic is about leaving the whole `/etc` OS-tree R/w, while you guys in that other topic try to keep the applied parts inside a `sysext` R/W.
These are two independent different uses...

**Comment by t-lo** [comment]
> This topic is about leaving the whole /etc OS-tree R/W, while you guys in that other topic try to keep the applied parts inside a sysext R/W.

The PR referenced above introduces "write routing" via directories (or symlinks) in `/var/lib/extensions.mutable/[etc|usr|opt]` so the base OS remains mutable even when extensions are merged. The sysexts itself are not changed (and in many cases can't, e.g. when they are shipped in a squashfs). For your use case (`/etc` mutable) one would create a symlink `/var/lib/extensions.mutable/etc → /etc`.

(BTW. we have the exact same `/etc` use case in Flatcar, which is one of the main motivators for this work. We currently use a custom overlay mount which we'd like to move away from).

**Comment by TriMoon** [comment]
I don't think the solution to a problem is to create by-passes for a flaw in the original implementation...
IMHO, it's better to fix/change the original to not have this flaw in my point of view...

**Comment by TriMoon** [comment]
Maybe that is the flaw here...
Instead of overlafs, they maybe need to use internal bind-mount's (or similar) that only "overlay" the specific files in the `confext`

**Comment by t-lo** [comment]
> Instead of overlayfs for the whole tree, they maybe need to use internal bind-mount's (or similar) that only "overlay" the specific files from the respective `confext`

Sysexts / confexts were conceived with immutable Linux distributions in mind, and our mutability feature only covers some edge cases where all-out immutability is not (yet) desirable. One of the cornerstones of extensions is their simplicity - a single overlayfs mount - which makes the feature very robust and secure.
For shipping sub-trees / individual files there are better options available than overlayfs mounts; the management overhead of handling arbitrary sub-trees would be hard to justify against these.

**Comment by poettering** [comment]
> This topic is about leaving the whole `/etc` OS-tree R/W, while you guys in that other topic try to keep the applied parts from a `sysext` R/W.
> These are two independent different usages...

sysext/confext are implemented via overlayfs, and overlayfs currently has not mechanism for allowing inodes from certain layers to remain immutable while prohibiting this for inodes from other layers.

I have proposed this personally to some kernel fs people already, but don#t hold your breath.

**Comment by TriMoon** [comment]
@poettering 
> Many consider it a problem even, and prefer that /etc/ exclusively consists of properly authenticated confexts, with no chance of local modifications, so that an attacker simply cannot modify anything to gain persistency.

That's exactly where `confext` can "lockdown" specific stuff in `/etc` that are expected to stay in an authenticated state and immutable...

I think i don't have to point out that there are other places that provide persistency... _(fe. `/var/`)_
Unless they want that tree to be R/O also, in which case they might as-well throw away the whole R/W functionality of the OS for the normal filesystems...


> Nope. /tmp/ must be writable to be useful, but /etc/ not so much.

From a vendor's point of view maybe, but not from a local admin's point of view. (The machine owner and operator)
Like i already pointed out, in those scenarios where it would be desirable to have a R/O `/etc` they can create an `initrd` that mounts the `/etc` OS-tree in such a R/O way by explicit choice.

> sysext/confext are implemented via overlayfs, and overlayfs currently has not mechanism for allowing inodes from certain layers to remain immutable while prohibiting this for inodes from other layers.

I have understand that by now, that's why i suggested you to use `bind-mount's` for the `confext` functionality.
Note that i'm not talking about `sysext` functionality, in which the current behavior might be the preferred way.
_(I have not tested any scenario where i wanted to use that functionality yet)_

---
@t-lo 


> One of the cornerstones of extensions is their simplicity - a single overlayfs mount - which makes the feature very robust and secure.

Simplicity for the user of the functionality is **GOOD**, but **BAD** when it is for the coding itself.

Sorry to say but this is in my point-of-view, just a matter of "lazy" coding...
All security flaws start because of "lazy" coding, until fixed by more verbose coding.
This doesn't mean that i view `overlayfs` as insecure as an option, it just means i think it is improper usage for the use-case in this `/etc` case..

> For shipping sub-trees / individual files there are better options available than overlayfs mounts; the management overhead of handling arbitrary sub-trees would be hard to justify against these.

Well ofcourse i don't know how much an impact it would have with respect to the overhead of `bind-mount`ing single files individually.
But in this case i think it would be justified by the need of keeping the rest of the `/etc` tree R/W..
_(By "the rest" i mean anything that was not part of the final result of the respective `confext` image or dir)_

And, IMHO, that overhead would mostly only occur when accessing the respective files that need extra handling right?

**Comment by TriMoon** [comment]
PS: @pebenito i would appriciate if you would rename the title back, because this issue is NOT about having mutable layers inside a `confext`...
The current title is just misleading with respect to it's goal.

**Comment by poettering** [comment]
> PS: @poettering i would appriciate if you would rename the title back, because this issue is NOT about having mutable layers inside a `confext`...
> The current title is just misleading with respect to it's goal.

i don't understand what you are looking for then?

**Comment by poettering** [comment]
> I have understand that by now, that's why i suggested you to use `bind-mount's` for the `confext` functionality.
> Note that i'm not talking about `sysext` functionality, in which the current behavior might be the preferred way.
> _(I have not tested any scenario where i wanted to use that functionality yet)_

i don't understand what bind mounts have to do with overlay mounts? binds mounts just make some inode appear at multiple places along with any children in case the inode is a dir. overlay mounts however merger trees, and can thus augment new inodes at arbitrary places.

Also overlayfs as this nice atomic behaviour, either it's there in full, or not at all. there's never a half setup. Which is ideal

**Comment by TriMoon** [comment]
@poettering , first off excuses for leaving this discussion mid-way, but i had to sleep :smiley_cat: 

> i don't understand what you are looking for then?
> i don't understand what bind mounts have to do with overlay mounts?

Let me explain in a more verbose way then if i can:

Currently:
- You combine the `/etc` tree of the destination `OS-tree` with the `/etc` tree of the `confext` using `overlayfs`.
- This causes the `/etc` tree on the host to become R/O.

What i mean/ask to happen is:
- In the case of `confext`, replace or create inode's on the destination `OS-tree` with the respective inode's of the source tree, **on a per-file-basis**.
- Because the respective files inside a `confext` are located inside an `/etc` directory tree, you would need to create and maintain eventually missing directories in the destination `OS-tree`.
- Doing this on a per-file-basis will make sure that the directories in the destination `OS-tree` stay as they are with respect to R/W, while at same time make the individual files R/O because they originate from within a R/O image.
_(unless a directory is used instead of a raw image, in which case they would inherit the eventual R/W state which needs to be forced to R/O)_
- This would use `bind-mounts` IMHO.
_(Not sure if the underlaying technical term is actually called that, but it is the functionality i describe and propose)_

IF it is still unclear, don't hesitate to ask for more explanation. :wink:

**Comment by TriMoon** [comment]
So while you guys try to implement a way to make the files **INSIDE** the `confext` modifiable in #31000 , this topic is about keeping the **OUTSIDE** or destination R/W.
These are independent goals.

**Comment by TriMoon** [comment]
Maybe you can create some kind of `namespace-overlay` for this functionality.

Like what `systemctl bind` does for specific units, you could use a `namespace-overlay` that injects the contents of the `confext` onto the OS-tree (without rendering directories R/O) that is accessible by the whole OS after that point..

:thinking:

**Comment by poettering** [comment]
> * In the case of `confext`, replace or create inode's on the destination `OS-tree` with the respective inode's of the source tree, **on a per-file-basis**.
>       _(This is not a copy-over but rather a `bind-mount`)_

You cannot bind mount over inodes that don't exist. You cannot "create inodes" with that.

**Comment by poettering** [comment]
> So while you guys try to implement a way to make **the files INSIDE** the `confext` modifiable in #31000 , this topic is about keeping the **OUTSIDE around the destination** of the `confext` _(thus the `/etc` OS-tree itself)_ R/W by default.

I am not sure what you mean by inside/outside.

But i kinda sense what you are asking for is that inodes in the resulting hierarchy made available by confext/sysext images you want to be immutable, but inodes from the underlying base dir you want to be mutable, did i get this right?

As mentioned, I already discussed this with some kernel fs folks, and I think there's not much opposition to such an idea, but it needs kernel work.

And sorry, bind mounts have no role in any of this. They don't scale, they are not atomic in behaviour, they cannot synthesize new inodes.

**Comment by bluca** [comment]
You are still missing the main point: either the system is immutable, or it isn't. There is no point whatsoever in having a system that is a little-bit-immutable-but-not-really, it's a charade, it's security theater. You have to pick one: if you want a writable system, just ignore all of this and have a normal writable root partition. If you want an immutable system, then use this stuff as it is.

We are most definitely not going to do a mess of bind mounts everywhere, as it would be an absolute mess, and for a use case that makes no sense.

**Comment by TriMoon** [comment]
@bluca , i think you are missing the point that this functionality is perfectly usable in systems like `uBlue` where the base system is immutable but the running system has a writable `/etc` and `/var` that are linked from parts of `/usr`....

**Comment by bluca** [comment]
Again, you are missing the point: it's not that it cannot be coerced into somewhat-working, it's that it's completely pointless to do so. There are only complications, and no advantage whatsoever. If you want a writable /etc/, use a writable /etc/.

**Comment by TriMoon** [comment]
Please take a look at:
- https://universal-blue.org/
- https://bazzite.gg/

Then you will understand why it is preferable to have a immutable system that has mutable parts...

I'm currently using the Bazzite version with nVidia build-in, and it works great :wink:

**Comment by bluca** [comment]
Those are just marketing pages, they are meaningless

**Comment by bluca** [comment]
> Again, you are missing the point: it's not that it cannot be coerced into somewhat-working, it's that it's completely pointless to do so. There are only complications, and no advantage whatsoever. If you want a writable /etc/, use a writable /etc/.

^^^

**Comment by TriMoon** [comment]
> If you want a writable /etc/, use a writable /etc/.

That is actually what is being used...a writable `/etc` and i would like to keep it that way while being able to use `confext`...

**Comment by t-lo** [comment]
@TriMoon  What you're asking for is precisely what's implemented by #31000 .

> current overlayfs way:
> `Image_A` is the base OS-tree. (the lower image layer?)

Plain old `/etc` on the root fs basically. Lowerdir in overlayfs lingo.

> This image is mutable (R/W) per definition because it is on the drive of the end-user (or in RAM using tempfs).

 Not _by definition_ (both Lennart and Luca gave examples where this is not the case) but let's assume for our case at hand it is.

> `Image_B` is the contents of the sysext/confext. (the upper image layer?)
> This image is immutable (R/O) by definition of the functionality of sysext/confext.

The middle layer(s). _Also_ called lowerdir in overlayfs lingo (there can be many lowerdirs).

> The viewer is looking at the combination of the two from the top towards the bottom: Viewer ⇒ `Image_B` ⇒ `Image_A`
> The viewer can see pixels (files) from `Image_A` if they are in spots that are not occupied in `Image_B`.
> `Image_B` acts like hard-glass where the viewer can see through but not change anything on, which also makes `Image_A` unchangeable / immutable / (R/O) from this angle of view, because you access the result from top-to-bottom 
(through the hard-glass).
> That is why there is a need to create a mutable `Image_C` that needs to be placed on top of Image_B to make the total result mutable again, which is called the workdir.
> (Current sysext/confext does not use a workdir)
>Correct so far?

No. First of all, in sysexts as currently implemented, both `Image_A` and `Image_B` are lowerdirs. Additionally, `Image_A` is the _mount point_. Mounts are opaque, but since `Image_A` is part of the stack, it will _look like_ you can see thorugh.

One can _optionally_ specify an upperdir to overlayfs.  _If specified_, that's where the writes go. But it is optional. So if you don't specify an upper layer at all (like sysext implementation currently), your resulting merged overlayfs mount will be immutable.

So you stack the _lowerdirs_, and then mount them where `Image_A` happens to reside in the file system. The mount point is opaque - if you mount anything over a directory with contents, then the contents will disappear, hidden by whatever is mounted. However, since `Image_A` is _also_ part of the overlayfs stack, it will "look like" you can see through `Image_B`. 

Because there is no upperdir specified, the mount will result in a read-only filesystem:
* `<mount point which happens to be the position of Image_A in the file system>`
* `Image_B` (lowerdir)
* `Image_A` (lowerdir)

If you run `mount` on a system with sysexts merged you'll see
```
...
sysext on /usr type overlay (ro,relatime,seclabel,lowerdir=/run/systemd/sysext/meta/usr:/run/systemd/sysext/extensions/oem-qemu/usr:/run/systemd/sysext/extensions/docker-flatcar/usr:/run/systemd/sysext/extensions/containerd-flatcar/usr:/usr)
...
```
This is on the latest Flatcar alpha which ships containerd and docker as sysexts. As you see there is _only_ `lowerdir=`, no `upperdir=` or `workdir=`.

#31000 extends this.

If you specify the `--mutable` option, the overlayfs mount will now use an upperdir. Upperdirs take writes, and the overlayfs mount thus will be writable. The directories in `/var/extensions.mutable/...` are used to set up the upperdir.

To get back to your image example:
* If  `/var/extensions.mutable/etc` is a directory, it will be the upperdir. The stack is then
   * `Image_C`  (upperdir, `/var/extensions.mutable/etc`)
   * `Image_B` (lowerdir)
   * `Image_A` (lowerdir)
* If  `/var/extensions.mutable/etc` is a _symlink_ to `/etc`; then `/etc` (aka `Image_A`) will be the upperdir. The stack is then
   * `Image_A`  (upperdir, `/etc`)
   * `Image_B` (lowerdir)

Like I stated further up this thread, this should address your issue.

**Comment by TriMoon** [comment]
@t-lo 
Ok thank you for your time and efforts with the in-depth explanation, i appreciate that as im sure everyone else who will be reading this :+1: 

> Like I stated further up this thread, this should address your issue.

I'm looking forward for it then :+1:

**Comment by pothos** [comment]
Just FYI, the overlayfs feature idea is tracked in the https://uapi-group.org/kernel-features/ list:
> `overlayfs` should permit *immutable* layers, i.e. layers whose non-directory inodes may not be overriden in an upper writable layer.
