### ISSUE TITLE
Cannot reload services after merging sysext containing a /usr/lib directory

### ISSUE THREAD

**Issue by chergert** [systemd/systemd#31404]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39 - Workstation and Asahi Remix

### Linux kernel version used

 * 6.6.3-413.asahi.fc39.aarch64+16k
 * 6.6.11-200.fc39.x86_64

### CPU architectures issue was seen on

 * aarch64
 * x86_64

### Component

systemd-sysext

### Expected behaviour you didn't see

I should be able to reload services even if a sysext is installed which contains an overlapping directory structure of `/usr/lib`.

### Unexpected behaviour you saw

I could not restart any service. They all resulted in exit codes.

### Steps to reproduce the problem

```
root@fedora:/var/lib/extensions# mkdir -p testing/usr/lib 
root@fedora:/var/lib/extensions# systemd-sysext --force refresh 
Using extensions 'testing'.
Merged extensions into '/usr'.
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
Job for polkit.service failed because the control process exited with error code.
See "systemctl status polkit.service" and "journalctl -xeu polkit.service" for details.
root@fedora:/var/lib/extensions# systemd-sysext unmerge 
Unmerged '/usr'.
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
root@fedora:/var/lib/extensions# 
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
Job for polkit.service failed because the control process exited with error code.
See "systemctl status polkit.service" and "journalctl -xeu polkit.service" for details.
root@fedora:/var/lib/extensions# systemctl status polkit.service 
× polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Mon 2024-02-19 21:51:00 PST; 2s ago
   Duration: 5min 36.963s
       Docs: man:polkit(8)
    Process: 377046 ExecStart=/usr/lib/polkit-1/polkitd --no-debug (code=exited, status=127)
   Main PID: 377046 (code=exited, status=127)
        CPU: 24ms

Feb 19 21:51:00 fedora systemd[1]: Starting polkit.service - Authorization Manager...
Feb 19 21:51:00 fedora polkitd[377046]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libpolkit-gobject-1.so.0: cannot open shared object file: Permission denied
Feb 19 21:51:00 fedora systemd[1]: polkit.service: Main process exited, code=exited, status=127/n/a
Feb 19 21:51:00 fedora systemd[1]: polkit.service: Failed with result 'exit-code'.
Feb 19 21:51:00 fedora systemd[1]: Failed to start polkit.service - Authorization Manager.
```

**Comment by chergert** [comment]
I did use `--force` here just to simplify testing. But if I include a file like this in the extension, the same issue occurs.

```
cat testing/usr/lib/extension-release.d/extension-release.testing
ID=_any
```

**Comment by chergert** [comment]
```
root@fedora:/var/lib/extensions# cat testing/usr/lib/extension-release.d/extension-release.testing 
ID=_any
EXTENSION_RELOAD_MANAGER=1
```

Reload works fine before merging

```
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
root@fedora:/var/lib/extensions# 
```

Merge things

```
root@fedora:/var/lib/extensions# systemd-sysext merge 
Using extensions 'testing'.
Merged extensions into '/usr'.
root@fedora:/var/lib/extensions# cat /usr/lib/extension-release.d/extension-release.testing 
ID=_any
EXTENSION_RELOAD_MANAGER=1
```

Still fails

```
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
Job for polkit.service failed because the control process exited with error code.
See "systemctl status polkit.service" and "journalctl -xeu polkit.service" for details.
```

Try to reload daemon just to be sure in case extension key didn't work

```
root@fedora:/var/lib/extensions# systemctl daemon-reload 
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
Job for polkit.service failed because the control process exited with error code.
See "systemctl status polkit.service" and "journalctl -xeu polkit.service" for details.
```

```
root@fedora:/var/lib/extensions# journalctl -xeu polkit.service | grep ^Feb | tail -n 10
Feb 20 10:48:58 fedora systemd[1]: Starting polkit.service - Authorization Manager...
Feb 20 10:48:58 fedora polkitd[397700]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libpolkit-gobject-1.so.0: cannot open shared object file: Permission denied
Feb 20 10:48:58 fedora systemd[1]: polkit.service: Main process exited, code=exited, status=127/n/a
Feb 20 10:48:58 fedora systemd[1]: polkit.service: Failed with result 'exit-code'.
Feb 20 10:48:58 fedora systemd[1]: Failed to start polkit.service - Authorization Manager.
Feb 20 10:49:35 fedora systemd[1]: Starting polkit.service - Authorization Manager...
Feb 20 10:49:36 fedora polkitd[397881]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libpolkit-gobject-1.so.0: cannot open shared object file: Permission denied
Feb 20 10:49:36 fedora systemd[1]: polkit.service: Main process exited, code=exited, status=127/n/a
Feb 20 10:49:36 fedora systemd[1]: polkit.service: Failed with result 'exit-code'.
Feb 20 10:49:36 fedora systemd[1]: Failed to start polkit.service - Authorization Manager.
```

Unmerge, things work fine

```
root@fedora:/var/lib/extensions# systemd-sysext unmerge 
Unmerged '/usr'.
root@fedora:/var/lib/extensions# systemctl restart polkit.service 
root@fedora:/var/lib/extensions# 
```

**Comment by chergert** [comment]
I also notice that if I do this, `/usr` is no longer writable. So I can't `dnf install` or anything. Is that expected? I would expect it doesn't matter when it's an "immutable" OS, but it would be handy to use this as a layer even when the host is mutable.

**Comment by poettering** [comment]
> Feb 20 10:49:36 fedora polkitd[397881]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libpolkit-gobject-1.so.0: cannot open shared object file: Permission denied

Uh?

That's weird. Why would that result in EACCESS? maybe the access rights in your image are not in order? or selinux?

**Comment by poettering** [comment]
> I also notice that if I do this, `/usr` is no longer writable. So I can't `dnf install` or anything. Is that expected? I would expect it doesn't matter when it's an "immutable" OS, but it would be handy to use this as a layer even when the host is mutable.

Yeah, sysext is designed with immutable OSes in mind. That said there's #31000 that adds mutability.

**Comment by chergert** [comment]
> That's weird. Why would that result in EACCESS? maybe the access rights in your image are not in order? or selinux?

Not sure, but I didn't see anything in the logs related to selinux/etc. All I did was the `mkdir -p testing/usr/lib` as `root` to make it happen.

**Comment by bluca** [comment]
Are you using selinux with enforcing? Overlayfs was broken w.r.t. selinux policy some kernel releases ago

**Comment by bluca** [comment]
`setenforce 0` and try again

**Comment by bluca** [comment]
This is something that needs to be fixed in the selinux policy. The policy needs to allow the entity that sets up the overlay (pid1 or systemd-sysext) ALL the permissions that the entities accessing any file in the overalyfs have. Yes, it makes no sense whatsoever, but that's the backward incompatible change the kernel did in 5.something. There is nothing we can do about it, the policy needs to be updated.

**Comment by FlyinPancake** [comment]
Sorry for necrobumping, but I'm a bit at a loss with SELinux. Can you provide an example policy to implement? I've been trying to make this work, but I've come up short

**Comment by DaanDeMeyer** [comment]
@FlyinPancake We are not SELinux experts, we know just as much about it (probably less) as you do. Please reach out the SELinux community for questions on SELinux.

**Comment by FlyinPancake** [comment]
@DaanDeMeyer Thank you for the reply I'll go and reach out to them :)

**Comment by chergert** [comment]
Running with `selinux=0` certainly does fix being able to run the merged directories.

However, https://github.com/systemd/systemd/pull/31000 (assuming it is in 256-rc1 which I think it is) does not fix the issue of being able to `dnf install` anything while `/usr` is merged.

Tested with Fedora Rawhide (41) with koji installation of `systemd-256~rc1`.

**Comment by pothos** [comment]
What error message did you get?
I tried this on Fedora 39 with the `systemd-sysext` binary from `v256~rc1` and it works without errors:
```
$ getenforce 
Permissive
$ ls -l /var/lib/extensions.mutable/
total 8
lrwxrwxrwx. 1 root root 4 28. Feb 22:59 etc -> /etc
lrwxrwxrwx. 1 root root 4 28. Feb 23:00 usr -> /usr
$ sudo build/systemd-sysext refresh --mutable=auto
Using extensions 'wasmtime'.
Merged extensions into '/usr'.
$ sudo dnf install wasmedge
[…]
$ sudo build/systemd-sysext unmerge
[…]
$ wasmedge --version
[…]
$ sudo dnf remove wasmedge
[…]
```
