### ISSUE TITLE
Allow turning backlight to 0

### ISSUE THREAD

**Issue by ldelossa** [systemd/systemd#31410]
### Component

systemd-logind

### Is your feature request related to a problem? Please describe

When writing 0 to a backlight's brightness file it turns the screen. 

This is actually very useful when you want to use a laptop with 'audio only'.

When I write 0 to the backlight file via Logind's SetBrightness DBUS API it seems to clamp the brightness on my machine:
```
cat /sys/class/backlight/intel_backlight/brightness 
730
```

### Describe the solution you'd like

This maybe a "nice" feature which intends to allow the user to not be confused about a blank screen.

However, this is a bit heavy handed as a simple API goes and does not allow the user to turn off the screen temporarily. 

### Describe alternatives you've considered

It's not very convenient to pick another method due to SetBrightness handling the necessary permissions to write to this file. 

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by poettering** [comment]
We don't clamp the brightness in the logind SetBrightness() path. Maybe something else is?

if you change the brightness via sysfs, is it not clamped?

**Comment by AdrianVovk** [comment]
In my experience the kernel is inconsistent about these things. Sometimes you can write 0 into the sysfs file to turn off the screen, and other times you can't and the kernel driver will clamp it to some minimum value.

In other words, you should verify on that specific machine if writing 0 into /sys/class/backlight/intel_backlight/brightness works. It might work on a different machine but fail on this one

You may also want to look into DPMS, which was designed for actually turning displays on/off, unlike the brightness settings. Usually it's managed by your DE, so you'll need to find a way to ask your DE to turn the display off for you w/o suspending the whole system

**Comment by poettering** [comment]
so i verified this here on my system. It works fine, there is no clamping done in logind. 

i.e.:

```console
$ busctl call org.freedesktop.login1 /org/freedesktop/login1/session/auto org.freedesktop.login1.Session SetBrightness "ssu" "backlight" intel_backlight 0
$ cat /sys/class/backlight/intel_backlight/brightness 
0
``

**Comment by poettering** [comment]
Hence what you are seeing must be effect of something else, but logind is not at fault...

**Comment by ldelossa** [comment]
Thanks everyone for the quick answer. 

I'm on a x1 carbon gen 11. I'm able to write zero to turn off the screen to the brightness file. However even I use the DBus API to write 0, i get a procol error response. I'm using glib dbus libraries and their code gen. 

Thanks for the input, I'll test a bit more, maybe I'm sending an odd value out some integer size mismatch. 

Anyway, you're right, DPMS is probably the right way to do this anyways. Thanks
