### ISSUE TITLE
systemd-cryptenroll does not re-enroll PCRs if only the PIN changes

### ISSUE THREAD

**Issue by flixman** [systemd/systemd#31453]
### systemd version the issue has been seen with

255

### Used distribution

Arch linux

### Linux kernel version used

6.7.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

After providing a different PIN, the PCR registers + the new PIN get enrolled in LUKS.

### Unexpected behaviour you saw

Systemd-cryptenroll reported "This PCR set is already enrolled, executing no operation.", and therefore the new PIN was not used.

### Steps to reproduce the problem

Assuming a valid value is set in the environment variable PCR11:
1. Enroll a new set of PCRs into LUKS, providing a PIN, and will report success:
```
    systemd-cryptenroll --unlock-key-file=/mnt/password.bin --tpm2-with-pin=yes --wipe-slot=tpm2 --tpm2-device=auto --tpm2-pcrs=7+$PCR11+14 /dev/nvme0n1p5
```
2. Enroll the same set of PCRs _but provide a different PIN_, and will report that PCR set is already enrolled:
```
No signature table present
# PCR[11] Phase <enter-initrd>
Signing Unsigned original image
Resetting the tpm2 key in LUKS, PCR11=8e96a...
This PCR set is already enrolled, executing no operation.
```

**Comment by poettering** [comment]
Fixed by 47ec2c8a8ee53fbdde30dc73747dbbe1ddd7bdfd already.
