### ISSUE TITLE
systemd-boot fails to load efi files bigger than 2Gb

### ISSUE THREAD

**Issue by Itxaka** [systemd/systemd#31452]
### systemd version the issue has been seen with

254

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

To load the files with no issues

### Unexpected behaviour you saw

Fails to load the files:
![image](https://github.com/systemd/systemd/assets/1447686/b969535e-9546-456f-9db7-e08024db4d10)

### Steps to reproduce the problem

Have a big EFI file >= 2Gb and try to load it from any media

**Comment by Itxaka** [comment]
Same with 255. Testing with master build now.

**Comment by Itxaka** [comment]
This is being tested in qemu in a vm with 16G of ram and 12vcpu

**Comment by Itxaka** [comment]
same thing with boot and stub built from master:

![image](https://github.com/systemd/systemd/assets/1447686/0a7a1820-5dc1-4163-bddc-745a62f0eb32)

**Comment by poettering** [comment]
Well, it seems the firmware in question simply doesn't allow us to allocate this much contiguous memory, which hence means you simply cannot load such large images. THere's not much we can do about that.

**Comment by Itxaka** [comment]
:(

Thanks for the info @poettering Closing this as there is nothing systemd-boot can do to alleviate this :(
