### ISSUE TITLE
systemd-sysext doesn't recognize image with a symlinked `usr`

### ISSUE THREAD

**Issue by jinliu** [systemd/systemd#31523]
### systemd version the issue has been seen with

255

### Used distribution

Arch

### Linux kernel version used

6.7.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysext

### Steps to reproduce the problem

1. Make an image dir in `/var/local/my-ext`, with metadata in `$HOME/my-ext/usr/lib/extension-release.d/extension-release.my-ext`.
2. `ln -s /var/local/my-ext /run/extensions/`
3. `systemd-sysext refresh` works as expected, merging `my-ext/usr` onto `/usr`.
4. `rm /run/extensions/my-ext && systemd-sysext refresh`
5. `mkdir /run/extensions/my-ext && cd /run/extensions/my-ext && ln -s /var/local/my-ext/usr .`
6. `systemd-sysext refresh` reports `No suitable extensions found (1 ignored due to incompatible image(s)).`

It seems `systemd-sysext` works if the image root is a symlink. But the `usr` directory inside the image can't be symlink. IMHO, allowing `usr`, `opt`, `etc` to be symlinks would make it easier to build images.

User scenario:
We (KDE developers) build the development version of KDE in a prefix dir. Because some of KDE files (e.g. PolicyKit rules) must be in `/usr`, we are currently trying to use `systemd-sysext` to overlay the prefix dir onto `/usr`. (https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1715)

Normally, the prefix dir is named `usr`, so we symlink its parent dir to the image root, and it works. But some developers might set a different name for the prefix dir (e.g. "kde"). We tried to link it like the Step 5 above, but `systemd-sysext` won't recognize the image then.

**Comment by bluca** [comment]
That's expected, top-level filesystem directories can't be symlinks outside of their hierarchy. Otherwise all sorts of symlink-based escapes vulnerabilities will be open.

**Comment by ratijas** [comment]
> Otherwise all sorts of symlink-based escapes vulnerabilities will be open.

Kinda sure, but also the primary use-case for this tool (for us at least) is to override system stuff with locally built software owned by the $user, so it can't get any more dangerous than that

**Comment by bluca** [comment]
> I don't expect `/usr` to be a symlink when merged. But could `systemd-sysext` resolves `image-root/usr` into the actual dir and merge that dir onto `/usr`? Any vulnerabilities in this way?

No, make image-root itself a symlink instead, that is fine

**Comment by jinliu** [comment]
>  stop recommending people use /usr/local/kde as an install-dir prefix which is used to act as a replacement for "usr" root.

`/usr/local/kde/usr` should do.

**Comment by poettering** [comment]
So I am pretty sure we should not follow symlinks outside of the extension image for security reasons. And the root of the disk image is not the /usr/ dir inside it, but the parent of it. Hence I think the current behaviour is correct and should stay the way it is.

or in other words, I too think /usr/local/kde/usr is what you should do.

I think we should just close this one?

**Comment by jinliu** [comment]
OK. We will make sure it's named `usr` in our side.
