### ISSUE TITLE
autopkgtest failure of networkd-test.py: ERROR: test_resolved_domain_restricted_dns (__main__.DnsmasqClientTest.test_resolved_domain_restricted_dns)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#31528]
Version: git master

Running autopkgtest for networkd-test.py in Debian sid yields the following failure:
```
======================================================================
ERROR: test_resolved_domain_restricted_dns (__main__.DnsmasqClientTest.test_resolved_domain_restricted_dns)
resolved: domain-restricted DNS servers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.TESDOU/tree/test/networkd-test.py", line 703, in test_resolved_domain_restricted_dns
    out = subprocess.check_output(['resolvectl', 'query', '-4', 'math.lab'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['resolvectl', 'query', '-4', 'math.lab']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 35 tests in 144.719s

FAILED (errors=1, skipped=2)
autopkgtest [15:20:12]: test networkd-test.py: -----------------------]
autopkgtest [15:20:12]: test networkd-test.py:  - - - - - - - - - - results - - - - - - - - - -
```
Full test log attached.
[log.txt](https://github.com/systemd/systemd/files/14435594/log.txt)

**Comment by mbiebl** [comment]
Not sure if it's a duplicate of #10487, since I haven't seen this issue for a while.

**Comment by mbiebl** [comment]
do we have anyone who understand sthe interactions between networkd/resolved/DNSSEC etc.
@rpigott , @LiveFreeAndRoam maybe?

**Comment by rpigott** [comment]
Pretty sure there is no interesting DNS interaction here.

```
 95s Feb 28 14:13:42 host systemd-resolved[7303]: Firing regular transaction 64159 for <math.lab IN A> scope dns on testvpnclient/* (validate=yes).
 95s Feb 28 14:13:42 host systemd-resolved[7303]: Using feature level UDP+EDNS0+DO for transaction 64159.
 95s Feb 28 14:13:42 host systemd-resolved[7303]: Using DNS server 10.241.3.1 for transaction 64159.
[....]
 95s Feb 28 14:13:45 host systemd-resolved[7303]: Regular transaction 64159 for <math.lab IN A> on scope dns on testvpnclient/* now complete with <EHOSTUNREACH> from none (unsigned; non-confidential).
 95s Feb 28 14:13:45 host systemd-resolved[7303]: Sent message type=error sender=n/a destination=:1.60 path=n/a interface=n/a member=n/a cookie=9 reply_cookie=2 signature=s error-name=System.Error.EHOSTUNREACH error-message=Lookup failed due to system error: No route to host
```

Sure seems like a prefix route should be present but /shrug. Wonder if it could have to do with: https://github.com/systemd/systemd/blob/e72ae41b51a2738438e1f3669265d7c37d9d33f6/src/resolve/resolved-dns-scope.c#L466-L484

P.S. This kernel issue has since been resolved: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0e4d354762cefd3e16b4cff8988ff276e45effc4

**Comment by rpigott** [comment]
@mbiebl If you remove the SO_BINDTODEVICE workaround, does it work?

**Comment by bluca** [comment]
Trying that here https://github.com/systemd/systemd/pull/31553

**Comment by mbiebl** [comment]
> Not sure if it's a duplicate of #10487, since I haven't seen this issue for a while.

actually, I haven't seen this for a while because I disabled that test in Debian /o\ 

https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/patches/debian/Skip-flaky-test_resolved_domain_restricted_dns-in-network.patch?ref_type=heads

It

**Comment by bluca** [comment]
> Trying that here #31553

still fails unfortunately 
[networkd-test.py-stdout.gz](https://github.com/systemd/systemd/files/14455402/networkd-test.py-stdout.gz)

**Comment by rpigott** [comment]
It occurs to me that if the issue of IP_UNICAST_IF not being accounted for in connect was fixed, perhaps this was resolved "the wrong way" for us and IP_UNICAST_IF alone is now sufficient to cause EHOSTUNREACH and skipping SO_BINDTODEVICE for local addresses alone is no longer enough.

**Comment by rpigott** [comment]
idk how to get the logs for this test...

**Comment by bluca** [comment]
the failing job has to be triggered manually, given it doesn't work it's not enabled yet, I've done so now for that PR
