### ISSUE TITLE
nvmf devices are not showed up in /dev/disk/by-path in -254/-255

### ISSUE THREAD

**Issue by wen2xiong** [systemd/systemd#31535]
### systemd version the issue has been seen with

254/255

### Used distribution

rhel94

### Linux kernel version used

5.14.0-425

### CPU architectures issue was seen on

ppc64le

### Component

systemd

### Expected behaviour you didn't see

nvme devices are showed up in /dev/disk/by-path:
[root@ltcden7-lp12-test by-path]# pwd
/dev/disk/by-path
[root@ltcden7-lp12-test by-path]# ls -l
total 0
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-53 -> ../../nvme3n1
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-542 -> ../../nvme3n3
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-543 -> ../../nvme3n4
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-544 -> ../../nvme3n5
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-545 -> ../../nvme3n6
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part1 -> ../../nvme3n6p1
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part2 -> ../../nvme3n6p2
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part3 -> ../../nvme3n6p3
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part4 -> ../../nvme3n6p4
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-66 -> ../../nvme3n2

### Unexpected behaviour you saw

nvmf device are not showed up in /dev/disk/by-path

### Steps to reproduce the problem

# system boot up
#ls -l /dev/disk/by-path

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
none
```

**Comment by wen2xiong** [comment]
commit 67c3e1f63a5221b47a8fea85ae421671f29f3b7e
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Wed Sep 21 02:26:42 2022 +0900

    udev: support by-path devlink for multipath nvme block devices

    If multipath feature is enabled, nvme block devices may belong to the
    "nvme-subsystem" subsystem, instead of "nvme" subsystem.
    (What a confusing name...)

    Then, the syspath is something like the following,
        /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
    Hence, we need to find the 'real parent' device, such as
        /sys/devices/pci0000:00/0000:00:1c.4/0000:3c:00.0/nvme/nvme0

Above patch fixed the issue in  9/2022. Looks something is broken in systemd-254/255.

**Comment by yuwata** [comment]
That's expected. We do not support by-path symlink for nvmf devices. See 39a39f18f2bd2b1ef7b4fa4823472d129c514030.

**Comment by wen2xiong** [comment]
From  ibm test team, looks they still need support by-path symlink for nvmf devices

"Based on our prior experience in the field, for block devices customers have used scripts which depend on /dev/disk/by-path/ path to uniquely identify the devices across reboot/ udev."

Do you mind share the reason why you withdrawn the fix?

Thanks,
Wendy

**Comment by yuwata** [comment]
@wen2xiong 
The by-path symlinks should be based on how the device is connected to the system. E.g. 
```
ll /dev/disk/by-path
total 0
lrwxrwxrwx 1 root root  9 Feb 27 14:32 pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 13 Feb 27 14:32 pci-0000:3c:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx 1 root root 15 Feb 27 14:32 pci-0000:3c:00.0-nvme-1-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root 15 Feb 27 14:32 pci-0000:3c:00.0-nvme-1-part2 -> ../../nvme0n1p2
```
In this case, sda is connected to USB bus on PCI (express) bus, and nvme0n1 is connected to another PCI bus, and so on.
But, the paths for nvmf devices you shown in the above do not explain such and mostly meaningless. These paths were wrongly introduced by 67c3e1f63a5221b47a8fea85ae421671f29f3b7e.

Theoretically, we can support by-path symlink for nvmf devices, but we (at least I) do not have any nvmf devices, so I cannot implement proper by-path symlink for nvmf devices. Patches are welcome.

**Comment by wen2xiong** [comment]
by-path]# ls -l
total 0
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-53 -> ../../nvme3n1
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-542 -> ../../nvme3n3
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-543 -> ../../nvme3n4
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-544 -> ../../nvme3n5
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-545 -> ../../nvme3n6
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part1 -> ../../nvme3n6p1
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part2 -> ../../nvme3n6p2
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part3 -> ../../nvme3n6p3
lrwxrwxrwx. 1 root root 15 Feb 29 04:40 nvme-545-part4 -> ../../nvme3n6p4
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-66 -> ../../nvme3n2
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-2 -> ../../nvme0n2
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-3 -> ../../nvme0n3
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-4 -> ../../nvme0n4
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-5 -> ../../nvme0n5
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-6 -> ../../nvme0n6
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-7 -> ../../nvme0n7
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-8 -> ../../nvme0n8
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 pci-0573:98:00.0-nvme-9 -> ../../nvme0n9

**Comment by wen2xiong** [comment]
[root@ltcden7-lp12-test by-path]# nvme list|grep nvme3
/dev/nvme3n1          /dev/ng3n1            20420006cea          IBM     2145                             0x35         6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9
/dev/nvme3n2          /dev/ng3n2            20420006cea          IBM     2145                             0x42         6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9
/dev/nvme3n3          /dev/ng3n3            20420006cea          IBM     2145                             0x21e        6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9
/dev/nvme3n4          /dev/ng3n4            20420006cea          IBM     2145                             0x21f        6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9
/dev/nvme3n5          /dev/ng3n5            20420006cea          IBM     2145                             0x220        6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9
/dev/nvme3n6          /dev/ng3n6            20420006cea          IBM     2145                             0x221        6.49  TB /  64.42  GB    512   B +  0 B   8.5.0.9

Above are nvmf devices

nvmf devices are showed up in /dev/disk/by-path in systemd-252.

**Comment by wen2xiong** [comment]
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-53 -> ../../nvme3n1
                                                                           ---> nsid number
lrwxrwxrwx. 1 root root 13 Feb 29 04:40 nvme-542 -> ../../nvme3n3
                                                                          ---> nsid number
Do you want to add pci address in front of nvmf device in by-path?
