### ISSUE TITLE
Unable to Set MemoryHigh Property Using systemctl

### ISSUE THREAD

**Issue by codebyoul** [systemd/systemd#31542]
### systemd version the issue has been seen with

systemd 245 (245.4-4ubuntu3.23)

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.0-171-generic

### CPU architectures issue was seen on

None

### Component

systemctl

### Expected behaviour you didn't see

The memory of user 1005 must be limited

### Steps to reproduce the problem

1. As the root user, I have limited the memory for the user ID 1005.
2. Executed the command: systemctl set-property user-1005.slice MemoryHigh='1G'
3. Checked the configured property value using: systemctl show -p MemoryHigh user-1005.slice
4. Verified that the value is set correctly: MemoryHigh=1073741824
5. Connected as user 1005 and executed the command: stress -m 1 --vm-bytes 1G --vm-keep
6. Returned to the root terminal and run: top
7. Observed that the memory is not limited.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
(also, maybe read the docs, the effect of MemoryHigh= is pretty explicitly explained.)

**Comment by oulfr** [comment]
> (also, maybe read the docs, the effect of MemoryHigh= is pretty explicitly explained.)

Can you share the link to this ?

**Comment by poettering** [comment]
Are you kidding? Do you know "Google"? it's a search engine. It's pretty good. Try googling for "Google", and you might find it. Then type in "MemoryHigh= systemd man" and click on the very first link.

Anything else I can help you with?

**Comment by oulfr** [comment]
No, I'm not kidding. Before opening this issue, I thoroughly reviewed all available documentation and spent numerous hours searching through forums and in repository issues. Unfortunately, I couldn't find any information that explains why it's not working for this specific configuration. It works in other Linux versions, but the issue persists in the current one.

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/devel/systemd.resource-control.html#MemoryHigh=bytes

Look at the difference between MemoryHigh and MemoryMax

**Comment by oulfr** [comment]
> https://www.freedesktop.org/software/systemd/man/devel/systemd.resource-control.html#MemoryHigh=bytes
> 
> Look at the difference between MemoryHigh and MemoryMax

@bluca :Thank you for your response. To simplify my question: all metrics are not applied to the specific user (CPU, memory, IO, etc.), and all are set correctly. There is something that has not yet been identified causing this issue. It works in many other Linux distributions, but not in this particular one in Hetzner Cloud : ubuntu 20.04 , kernel 5.4.0-171-generic and systemd 245 (245.4-4ubuntu3.23).
