### ISSUE TITLE
The system has a low probability of continuously hanging on startup

### ISSUE THREAD

**Issue by linzhanglong** [systemd/systemd#31540]
### systemd version the issue has been seen with

255

### Used distribution

centos

### Linux kernel version used

4.18.0-372.19.1.49.po1.x86_64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

The system enter emergency.target.

### Unexpected behaviour you saw

The system has been continuously hanging.

### Steps to reproduce the problem

The systemd-fsck-root.service is BindsTo dev-disk-by\x2dlabel-vtproot.device. If during the boot process the dev-disk-by\x2dlabel-vtproot.device is found to be dead, it will trigger a stop of the systemd-fsck-root.service.
Since sysroot.mount has a Requires dependency on systemd-fsck-root.service, initrd-root-fs.target has a Requires dependency on sysroot.mount, and initrd-parse-etc.service has a Requires dependency on initrd-root-fs.target.
Therefore, the services will stop in the following order: initrd-parse-etc.service -> initrd-root-fs.target -> sysroot.mount -> systemd-fsck-root.service.
Subsequently, the system will hang and will not enter emergency.target.
Because initrd-parse-etc.service has not executed ExecStart(start initrd-cleanup.service -> initrd-switch-root.target) before stopping. Switch Root After initrd-cleanup.service.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# initrd-parse-etc.service

[Unit]
Description=Reload Configuration from the Real Root
DefaultDependencies=no
Requires=initrd-root-fs.target
After=initrd-root-fs.target
OnFailure=emergency.target
OnFailureJobMode=replace-irreversibly
ConditionPathExists=/etc/initrd-release

Wait for start to complete before stopping ?
```

**Comment by poettering** [comment]
not sure i follow? if your "vtproot" device does not show up and it's the root device, then what else would you expect that the the system to wait for it? where's the issue in systemd?

**Comment by linzhanglong** [comment]
I created scenarios for IO failure and IO recovery, but even after IO was restored, the system still remained stuck during startup.
