### ISSUE TITLE
Systemd-resolved: Calling gethostbyaddr on non-local/non-private causes connection attempt

### ISSUE THREAD

**Issue by goldstar611** [systemd/systemd#31547]
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39

### Linux kernel version used

6.7.5-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

N/A

### Unexpected behaviour you saw

A connection request to a non link-local address on port 5355. *edited*

Discussed on systemd-devel mailing list at https://lists.freedesktop.org/archives/systemd-devel/2024-February/050072.html

### Steps to reproduce the problem

Install and open wireshark
Set filter to `tcp.port == 5355`
Run this python script `python3 -c 'import socket; socket.gethostbyaddr("123.123.123.123")' `

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Port 5355 is used for LLMNR and RFC-4795, states in the abstract that "LLMNR only operates on the local link" so I think the current behavior of contacting hosts on port 5355 is incorrect.

https://datatracker.ietf.org/doc/html/rfc4795
```

**Comment by poettering** [comment]
turn off llmnr?

**Comment by goldstar611** [comment]
> turn off llmnr?

Disabling LLMNR does prevent the incorrect behavior from occurring and is my current "fix" to the situation. LLMNR should still only reach out to link local addresses IMO.

**Comment by goldstar611** [comment]
quick note: I'm not a great networking/routing person and even less so regarding IPv6.

> llmnr is supposed to work with both regular (i.e. dhcp-provided for example) addresses and link-local (i.e. ipv4ll aka 169.254.0.0/16) addresses.

In a well configured environment, LLMNR multicast packets should be sufficient, IMO.

> and if you meant "link-local" in the sense of "use only address range configured on the network interface", then the big problem is that it is very difficult to determine what addresses are local on a network, 


So my general concern is the attempt to resolve a host name from an IP address that is:
- Not a configured DNS server (i.e. /etc/resolv.conf, ...)
- Not in the RFC-1918 "private" space (i.e. 10/8, 172.16/12, 192.168/16, ...)
- Not in the RFC-3927 "link-local" space (i.e. 169.254/16, ...)

The LLMNR RFC says link-local many times, but doesn't define "link-local", but I would argue that the public routable IP space should be excluded for such LLMNR unicast packets, and thus, `gethostbyaddr("123.123.123.123")` should not cause a connection to such IP on port 5355.

Hopefully we're saying the same thing and not talking past each other. :)

**Comment by rpigott** [comment]
I think this can now be closed.

**Comment by poettering** [comment]
Hmm, why didn't github close this on its own? weird.
