### ISSUE TITLE
small improvement to Iterator

### ISSUE THREAD

**Issue by pinskia** [systemd/systemd#31558]
https://github.com/systemd/systemd/blame/d5e6df24bd5031d9f41a2faaa70d46ed2b1a19ac/src/basic/hashmap.h#L43

If we swap idx and next_key fields in Iterator, the ENABLE_DEBUG_HASHMAP case would use 8 bytes less for Iterator on LP64 targets and having 2 4 bytes padding.
There will be still some padding in the case of !ENABLE_DEBUG_HASHMAP for LP64 targets but at least the padding will be at the end of the struct rather than in the middle.
This will not change any thing for ILP32 targets either.

**Comment by poettering** [comment]
Sure, why not: → #31578 

Thanks.

**Comment by pinskia** [comment]
I should mention I found this while trying to better understand why `-ftrivial-auto-var-init=zero` is causing some preformance issues in the code. It was a side issue so from the main issue.
