### ISSUE TITLE
catalog: RateLimitInterval= → RateLimitIntervalSec= replacement missing in systemd.hr.catalog file

### ISSUE THREAD

**Issue by muzena** [systemd/systemd#3158]
@poettering 
Why this RateLimitInterval fix not commited on systemd.hr.catalog file ?https://github.com/systemd/systemd/commit/f0367da7d1a61ad698a55d17b5c28ddce0dc265a

**Comment by poettering** [comment]
@muzena ah, uh, that's because the patch that added it is newer than my original PR, and when I rebase the PR I missed it hence.

**Comment by muzena** [comment]
@poettering 
I don't understand, if I translated systemd why during system boot eg, ubuntu xenial or yakkety systemd starting service messages isn't localized, they are on english?

**Comment by poettering** [comment]
@muzena please direct questions like this one to the proper forums, not here...

(that said: note that PID 1 isn't translatable right now, we so far avoided that due to it being so low-level. Only some user-facing bits are translatable so far.)

**Comment by muzena** [comment]
Aha, I understand now, thanks for answer.
