### ISSUE TITLE
After resuming from standby, systemd is stuck trying to unmount a disk

### ISSUE THREAD

**Issue by wil93** [systemd/systemd#316]
I suspended my laptop while having a USB drive connected, then I disconnected the drive. Later on, I resumed the laptop and (as expected) some apps weren't happy because they were working with some files from that drive.

I tried to unmount using nautilus but it said something like "the drive is busy", I noticed that there was another item named "usb" in the nautilus sidebar so I proceeded to click it and the drive was promptly mounted on a different location (before: `/media/myusbdrive`, now: `/run/media/wil93/usb`) ~~however, I can access the data under both locations~~ if I try to access `/media/myusbdrive` I get an input/output error.

This is the current situation:
![usb](https://cloud.githubusercontent.com/assets/1285361/8280082/5806cef8-18da-11e5-959a-daf5d8cd92ea.png)

It's not really bothering me, however, this is what I see under `htop`:
![htop](https://cloud.githubusercontent.com/assets/1285361/8280158/d5487da8-18da-11e5-9539-248f51b1431b.png)

It seems like systemd is constantly trying to unmount `/media/myusbdrive`, many times a second. I collected [some logs](https://gist.github.com/wil93/a709d4a8112e6f5ccb74#file-gistfile1-txt) using the command:

``` bash
> $ date && (journalctl -xeb > log) && date
Mon Jun 22 12:35:36 CEST 2015
Mon Jun 22 12:35:36 CEST 2015
```

(I used `journalctl -xeb` because the output of `journalctl -xb` was _far_ too big to be uploaded)

It seems that each second there are countless logs of `umount` and `systemd` tryng to unmount and failing.

**Comment by wil93** [comment]
For what it's worth, this is what I did to work around the issue:

``` bash
> $ lsof | grep myusbdrive
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/120/gvfs
      Output information may be incomplete.
zsh        1353       wil93  cwd       DIR               8,65      4096     139097 /media/myusbdrive/tesi
```

And then:

``` bash
> $ kill -9 1353
```

After that, the CPU usage went back to normal and the nautilus sidebar went back to having only one entry of "usb".

**Comment by poettering** [comment]
Which systemd version is this? Is that an issue with v221?

**Comment by wil93** [comment]
It's 219. I'll try to see if I can try with 221...

**Comment by wil93** [comment]
It's probably worth noting that I had `RateLimitBurst=0` in journald.conf

I'm now installing 221

**Comment by poettering** [comment]
Any luck?

**Comment by wil93** [comment]
I can't reproduce the issue with 221 (not sure if it's really fixed). I think the issue could be closed, I'll ask to reopen it if I see the bug again... :smile:
