### ISSUE TITLE
local-fs.target is shown as before for bind-mount with remote shares (NFS)

### ISSUE THREAD

**Issue by cmonty14** [systemd/systemd#31609]
### systemd version the issue has been seen with

249

### Used distribution

SUSE Linux Enterprise Server 15 SP4

### Linux kernel version used

5.14.21-150400.24.97-default

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

No local-fs.target in any condition based on this fstab-entry:
```
/backup/SID             /hana/shared/SID/HDB02/backup   none    bind,noauto,x-systemd.automount,x-systemd.after=backup.mount,x-systemd.after=hana.mount,x-systemd.requires=backup.mount,x-systemd.requires=hana.mount 0 0
```

### Unexpected behaviour you saw

`systemctl show -p` shows `local-fs.target` in before and after condition:
```
# systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After hana-shared-SID-HDB02-backup.mount
Requires=backup.mount system.slice hana.mount -.mount
Requisite=
Wants=network-online.target
BindsTo=
PartOf=
Before=local-fs.target umount.target remote-fs.target
After=backup.mount network-online.target hana-shared-SID-HDB02-backup.automount system.slice remote-fs-pre.target -.mount hana.mount network.target systemd-journald.socket local-fs-pre.target
```

### Steps to reproduce the problem

1. create entry in `/etc/fstab`
2. `systemctl daemon-reload`
3. `systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After <mountpoint>.mount

**Comment by YHNdnzj** [comment]
This is expected. Please specify `_netdev` option for the mount.

**Comment by TriMoon** [comment]
I fail to see `local-fs.target` in his output.
I do however see `local-fs-pre.target` in his output, which are not the same :wink:

**Comment by cmonty14** [comment]
> This is expected. Please specify `_netdev` option for the mount.

Could you please specify what is needed to specify `_netdev`option?

I checked another server with same `/etc/fstab` entry, but `local-fs.target` is **not** included in any condition.

**Comment by cmonty14** [comment]
> Before=local-fs.target umount.target remote-fs.target

`Before=local-fs.target umount.target remote-fs.target`

**Comment by TriMoon** [comment]
That comment was in regard to:
> systemctl show -p shows local-fs.target in before and after condition:

**Comment by poettering** [comment]
if you have mounts that depend on the network and this is not obvious to determine (i.e. because it's not nfs/smb, … but instead an iscsi device or a bind mount off some other network fs) you have to add `_netdev` to the mount options of your mount in fstab.

THis is not a systemd invention, this was already true in pre-systemd times.

Closing.

**Comment by dtardon** [comment]
I wonder if systemd could be a bit smarter regarding bind mounts and propagate the "remoteness" of the source path to the bind mount. This issue causes circular dependencies and it's often not obvious from the logs why it's happening.
