### ISSUE TITLE
25-second timeouts everywhere: "Failed to start reboot.target: Connection timed out"

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#3161]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

```
$ uname -a
Linux thutmose 4.4.8-1-lts #1 SMP Wed Apr 20 15:13:52 CEST 2016 x86_64 GNU/Linux
```
### In case of bug report: Expected behaviour you didn't see

From my desktop:

```
$ time ssh thutmose echo hi
hi
ssh thutmose echo hi  0.01s user 0.00s system 0% cpu 25.261 total
```

On "thutmose":

```
$ sudo reboot
Failed to start reboot.target: Connection timed out
See system logs and 'systemctl status reboot.target' for details.
Failed to talk to init daemon.
$ systemctl status reboot.target
Failed to get properties: Connection timed out
[1]$ sudo systemctl status reboot.target 
Failed to get properties: Connection timed out
[1]$ time sudo systemctl hibernate                
Failed to hibernate system via logind: Connection timed out
Failed to start hibernate.target: Failed to activate service 'org.freedesktop.systemd1': timed out
See system logs and 'systemctl status hibernate.target' for details.
sudo systemctl hibernate  0.03s user 0.00s system 0% cpu 50.068 total
```

I don't know if this will help:

[journal.txt](https://github.com/systemd/systemd/files/243855/journal.txt)
### In case of bug report: Steps to reproduce the problem

The laptop is 7 years old, whether there was memory corruption or something, I don't know. However, I recently experienced another problem with systemd, where I couldn't hibernate because it said something about a suspend already in progress. I don't experience this sort of trouble with other packages. I had to use "magic sysrq" for the first time, on the advice of #archlinux.

The laptop is mostly usable right now, aside from the 25-second delay to `ssh` to it, I can check email and so forth.

One thing which might be easy to fix is the 25-second delay. That's really annoying. I find it hard to envision a scenario where somebody's system would take even 2 seconds to connect to a Unix-domain socket. I'm not sure what is timing out, but there is a timeout somewhere which is a bit too large. You can see that the timeout seems to have taken place twice in the last "hibernate" command.

Another thing which could be improved is documentation. I started using Systemd about a year or two ago and I still don't know where to look for documentation on how I could work around a problem like this without rebooting. Obviously there's some inter-process communication, but I don't know what form it takes or how to restart the "server" process when `systemctl` is broken. None of the error messages give any hint about where to find out that information, and the people on #archlinux only suggested "magic sysrq", so maybe it doesn't exist.

Sorry if this bug report doesn't offer much in the way of debugging leads. I'll keep my laptop on for the next few hours or so in case someone here asks me to gather more information about its present semi-broken state.

**Comment by evverx** [comment]
```
Apr 30 14:01:56 thutmose systemd[1]: Assertion 'b' failed at src/basic/path-util.c:390, function path_compare(). Aborting.
...
Apr 30 14:01:57 thutmose systemd[1]: Caught <ABRT>, dumped core as pid 25675.
Apr 30 14:01:57 thutmose systemd[1]: Freezing execution.
```

Any chance you can extract the stacktrace from that coredump?

Seems like https://github.com/systemd/systemd/issues/2869
Was fixed by https://github.com/systemd/systemd/commit/5e1558f4a09e596561c9168384f2258e7c0718a

**Comment by poettering** [comment]
Yeah, looks like a duplicate, and was fixed already. Closing.

**Comment by archenemies** [comment]
Let me know if I should file separate issue tracker entries for the 25-second-timeout-is-too-long issue, or the no-documentation-for-how-to-fix-broken-reboot issue.

**Comment by magankur** [comment]
a
