### ISSUE TITLE
Moving ascii produced by manager_print_jobs_in_progress wreaks havoc on console based logging systems

### ISSUE THREAD

**Issue by scub** [systemd/systemd#3164]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> v299+

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> N/A
### In case of bug report: Expected behaviour you didn't see

> Expose support for disabling the `manager_print_jobs_in_progress` event during boot [[0]](https://github.com/systemd/systemd/blob/master/src/core/manager.c#L211-216).
### In case of bug report: Unexpected behaviour you saw

> This particular event commonly wreaks havoc on console based logging systems as they are unable to correctly parse the "moving ascii" produced by this particular method. 
### In case of bug report: Steps to reproduce the problem

> Use any console based logging system

https://github.com/systemd/systemd/blob/master/src/core/manager.c#L169

**Comment by poettering** [comment]
Please turn off ShowStatus= in system.conf, or use the kernel cmdline option systemd.show_status, and systemd won't output it's status info anymore on the console
