### ISSUE TITLE
Systemd cgroups v2 user memory control does not appear to work

### ISSUE THREAD

**Issue by tom-crane** [systemd/systemd#31660]
### systemd version the issue has been seen with

systemd-252-18.el9.x86_64

### Used distribution

Alma 9

### Linux kernel version used

5.14.0-362.18.1.el9_3.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Added a 'MemoryHigh=226M' directive in /etc/systemd/system/user-.slice.d/memtest-all-users.conf.
Expected the setting to appear as memory.max  in the user slice and then propagate to services and scopes belonging to the user.

### Unexpected behaviour you saw

The setting propagated to the user slice but not the services and scopes under that slice.

### Steps to reproduce the problem

Add a 'MemoryHigh=' directive in /etc/systemd/system/user-.slice.d/memtest-all-users.conf. Do 'systemctl daemon-reload. Do a user login, e.g. on the system console for simplicity. View the O/P of systemd-cgls. Check the relevant Control Group files user /sys. Observed that the user services & scopes under the user slice have failed to receive the specified memory restriction and report the default 'max' value.  See below.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
grep MemoryHigh /etc/systemd/system/user-.slice.d/memtest-all-users.conf
MemoryHigh=226M

echo $[226*1024*1024]
236978176

# cat /sys/fs/cgroup/user.slice/user-12345.slice/memory.max 
236978176
# cat /sys/fs/cgroup/user.slice/user-12345.slice/user@12345.service/memory.max 
max
# cat /sys/fs/cgroup/user.slice/user-12345.slice/session-5.scope/memory.max # NB: Session 5 is from a user console login
max
```

**Comment by rpigott** [comment]
> Added a 'MemoryHigh=226M' directive

> Expected the setting to appear as memory.max

MemoryHigh= controls /memory.high. MemoryMax controls /memory.max.

**Comment by tom-crane** [comment]
Oops! I do apologise. Sloppy copy&pasting on my part I'm afraid. I was working from notes rather than the target system.

I should have written.

```
# grep MemoryMax /etc/systemd/system/user-.slice.d/memtest-all-users.conf
MemoryMax=226M
# echo $[226*1024*1024]
236978176
# cat /sys/fs/cgroup/user.slice/user-12345.slice/memory.max
236978176
# cat /sys/fs/cgroup/user.slice/user-12345.slice/user@12345.service/memory.max 
max
# cat /sys/fs/cgroup/user.slice/user-12345.slice/session-4.scope/memory.max # NB: Session 4 is from a user console login
max

```

**Comment by bluca** [comment]
> Expected the setting to appear as memory.max in the user slice and then propagate to services and scopes belonging to the user.

cgroups do not work in that way - settings aren't replicated down a tree, otherwise you couldn't set further limits. But they are still respected - a child node cannot go above the parent's limits.

**Comment by tom-crane** [comment]
OK. Thanks for the clarification.  I had wondered about this which is why I added the 'appear to' in the title.  The documentation at https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/ is not at all clear on this point.  

The wider question is how does one apply memory and other user resource limits now that Control Groups have been brought under Systemd?  The requisite references to pam_systemd.so are present in the out-of-the-box /etc/pam.d/ config files, which led me to believe that all that would be needed was to add the MemoryHigh= etc. directives to the /etc/systemd/system/ user slice files.  Could anyone shed any light or provide a working example of the required configuration? Thanks.

**Comment by SmartProjectSolutions** [comment]
# cat /sys/fs/cgroup/user.slice/user-12345.slice/memory.max 
236978176
# cat /sys/fs/cgroup/user.slice/user-12345.slice/user@12345.service/memory.max 
max   ->> here max is your 236978176 from parent

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
