### ISSUE TITLE
resolved: DNSKEY and DS queries servfail when DNSSEC=no

### ISSUE THREAD

**Issue by pemensik** [systemd/systemd#31679]
### systemd version the issue has been seen with

255.4-1

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.8.0-0.rc7.55.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

dig -t DNSKEY example.org returns response, when the domain contains it. No servfail, if upstream servers do not servfail on it.

### Unexpected behaviour you saw

DNSSec specific types queries fail with servfail, even when upstream server does not.

Reported on Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2268581

### Steps to reproduce the problem

- dig -t DS example.org
- dig -t DNSKEY example.org
- resolvectl query -p dns -t DS example.org

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# dig -t DS example.org
; <<>> DiG 9.18.24 <<>> -t DS example.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 13144
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;example.org.			IN	DS

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri Mar 08 07:42:34 EST 2024
;; MSG SIZE  rcvd: 40

# dig -t DNSKEY example.org

; <<>> DiG 9.18.24 <<>> -t DNSKEY example.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 31200
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;example.org.			IN	DNSKEY

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri Mar 08 07:43:44 EST 2024
;; MSG SIZE  rcvd: 40

# resolvectl query -p dns -t DS example.org
example.org: resolve call failed: Server does not support requested resource record type
```

**Comment by pemensik** [comment]
Can this be related to PR #31621?

**Comment by pemensik** [comment]
Okay, that behaviour is not so new. At least systemd-resolved-254.10-1.fc39.x86_64 behaves the same way.

```
; <<>> DiG 9.18.24 <<>> -t DS example.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 37286
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;example.org.			IN	DS

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri Mar 08 07:57:50 EST 2024
;; MSG SIZE  rcvd: 40
```

**Comment by rpigott** [comment]
I can reproduce on master.

It usually helps if you can share your resolved config, `resolvectl status` should be enough. But I think I see where this goes wrong.

**Comment by YellowOnion** [comment]
I wonder if this is why firefox is constantly throwing error messages on some domains.

This shit has been trying me crazy for months, I guess moving to networkd was a mistake.

**Comment by rpigott** [comment]
This has nothing to do with firefox.

**Comment by YellowOnion** [comment]
> This has nothing to do with firefox.

I honestly have zero clue why both firefox and resolved are failing to resolve non-cached domains and throwing useless error messages and not logging anything useful in journalctl even on highest log level.

Maybe its related to this bug or not, All I know is I see SERVFAIL errors, and they go away when I use network manager, or my router IP.

I shouldn't need network engineering degree with a specialty in DNS to debug a website failing to load every time the TTL expires, and the issue goes away when bypass resolved.

And I honestly don't see how a DNS query bug wouldn't adversely effect software making DNS queries.

**Comment by rpigott** [comment]
Sorry, that's all quite off-topic here. Open a new issue if you want.
