### ISSUE TITLE
The "Describe" method starts failing when the DHCP server receives messages with non UTF-8 hostnames

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#31708]
When the DHCP server receives DHCPDISCOVER messages with non UTF-8 hostnames like
```python
>>> rdpcap('dhcp-non-utf-8-hostname.pcap')[0][DHCP].options
[('message-type', 1),
 ('client_id', b'\xffX\x88\xc0\xc1\x00\x02\x00\x00\xab\x11o;\xa9\x08 p\xa5S'),
 ('param_req_list', [1, 3, 6, 12, 15, 33, 42, 101, 114, 120, 121]),
 ('max_dhcp_size', 1472),
 ('rapid_commit', b''),
 ('hostname', b'\xff\xfe'),
 'end']
```
the "Describe" method starts failing with "Structure needs cleaning":
```sh
networkctl status  --json short 
Failed to get description: Structure needs cleaning

busctl call org.freedesktop.network1 /org/freedesktop/network1 org.freedesktop.network1.Manager Describe
Call failed: Structure needs cleaning
```
```sh
varlink-25: Changing state processing-disconnect → disconnected
Got message type=method_call sender=:1.16354 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Describe  cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Failed to build JSON data: Structure needs cleaning
Sent message type=error sender=n/a destination=:1.16354 path=n/a interface=n/a member=n/a cookie=41 reply_cookie=2 signature=s error-name=System.Error.EUCLEAN error-message=Structure needs cleaning
Failed to process message type=method_call sender=:1.16354 destination=org.freedesktop.network1 path=/org/freedesktop/network1 interface=org.freedesktop.network1.Manager member=Describe cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a: Structure needs cleaning
```
It was found in https://github.com/systemd/systemd/pull/30021#discussion_r1518478633 and should be partly addressed in that PR but I'm not sure why UTF-8 should be enforced there in the first place.

**Comment by poettering** [comment]
I am pretty sure we should enforce UTF-8 everywhere, and ever pass that on. I see no reason why we would allow this through for consumption of apps further up the stack. I mean, we are too dumb to handle this correctly right now, and when we fix this, then I am sure similar issues arise on every other level of the stack too, which will mishandle this.

If there was a valid usecase for non-UTF8 hostnames it might be something to cover, but I see none, hence I'd just suppress or escape the bad data, and not let it leak to higher levels of the stack.
