### ISSUE TITLE
syslog-ng apparmor profile not working as expected

### ISSUE THREAD

**Issue by sshedi** [systemd/systemd#31732]
### systemd version the issue has been seen with

255.2

### Used distribution

Photon OS

### Linux kernel version used

6.1.62

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

syslog-ng service should start with given apparmor profile

### Unexpected behaviour you saw

```
[   52.850621] kauditd_printk_skb: 51 callbacks suppressed
[   52.850624] audit: type=1400 audit(1710238133.968:62): apparmor="DENIED" operation="capable" profile="syslog-ng" pid=900 comm="syslog-ng" capability=12  capname="net_admin"
[   52.850638] audit: type=1400 audit(1710238133.968:63): apparmor="DENIED" operation="sendmsg" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="systemd/notify" pid=900 comm="syslog-ng" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
[   52.906508] audit: type=1400 audit(1710238134.024:64): apparmor="DENIED" operation="sendmsg" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="systemd/notify" pid=900 comm="syslog-ng" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
[   52.906529] audit: type=1400 audit(1710238134.024:65): apparmor="DENIED" operation="sendmsg" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="systemd/notify" pid=900 comm="syslog-ng" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
```

### Steps to reproduce the problem

```
root@phdev [ ~ ]# cat /etc/apparmor.d/sbin.syslog-ng
# ------------------------------------------------------------------
#
#    Copyright (C) 2006-2009 Novell/SUSE
#    Copyright (C) 2006 Christian Boltz
#    Copyright (C) 2010 Canonical Ltd.
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 2 of the GNU General Public
#    License published by the Free Software Foundation.
#
# ------------------------------------------------------------------

abi <abi/3.0>,

include <tunables/global>

#define this to be where syslog-ng is chrooted
@{CHROOT_BASE}=""

profile syslog-ng /{usr/,}{bin,sbin}/syslog-ng {
  include <abstractions/base>
  include <abstractions/consoles>
  include <abstractions/nameservice>
  include <abstractions/mysql>
  include <abstractions/openssl>
  include <abstractions/python>
  include <abstractions/hosts_access>

  capability chown,
  capability dac_override,
  capability dac_read_search,
  capability fsetid,
  capability fowner,
  capability sys_tty_config,
  capability sys_resource,
  capability syslog,

  unix (receive) type=dgram,
  unix (receive) type=stream,

  /run/systemd/notify rw,
  /var/* rw,
  /etc/ssl/*.cnf r,
  /dev/log w,
  /dev/syslog w,
  /dev/tty10 rw,
  /dev/xconsole rw,
  /dev/kmsg r,
  /etc/machine-id r,
  /etc/syslog-ng/* r,
  /etc/syslog-ng/conf.d/ r,
  /etc/syslog-ng/conf.d/* r,
  @{PROC}/kmsg r,
  /{usr/,}{bin,sbin}/syslog-ng mr,
  @{sys}/devices/system/cpu/online r,
  /usr/share/syslog-ng/** r,
  /var/lib/syslog-ng/syslog-ng-?????.qf rw,
  # chrooted applications
  @{CHROOT_BASE}/var/lib/*/dev/log w,
  @{CHROOT_BASE}/run/systemd/* rw,
  @{CHROOT_BASE}/var/lib/syslog-ng/* rw,
  @{CHROOT_BASE}/var/log/** w,
  @{CHROOT_BASE}/@{run}/syslog-ng.pid krw,
  @{CHROOT_BASE}/@{run}/syslog-ng.ctl rw,
  /{var,var/run,run}/log/journal/ r,
  /{var,var/run,run}/log/journal/*/ r,
  /{var,var/run,run}/log/journal/*/*.journal r,
  /{var,var/run,run}/log/journal/*.journal r,
  @{run}/syslog-ng.ctl a,
  @{run}/syslog-ng/additional-log-sockets.conf r,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/sbin.syslog-ng>
}
```
Install apparmor
Enable it through kernel command line
Use the above syslog-ng apparmor profile
Reload apparmor service
Try to start syslog-ng service and some unusual denials will show up in dmesg.

Why I suspect that this is a systemd issue?
The same profile works fine with `systemd-253.12` but not in `systemd-255`

And the info shown in denial is not seem okay, `name="systemd/notify"` here, `name=` should contain an absolute path but it's not.

**Comment by poettering** [comment]
This is a systemd bug tracker. It's not an photonos, apparmor or syslog-ng tracker.

AFAICS this has exactly *nothing* to do with systemd. Hence please contact your distro instead or the relevant communities of the packages involved.

**Comment by sshedi** [comment]
The only variable in my system is the version of systemd that is being used.

The same profile works fine with systemd-253.12 but not in systemd-255

I don't understand how this can not be a systemd issue. Please let me know if there are any configurations that restrict access to /run/systemd/notify. Probably if I probe in that direction, I might get something. Thanks.

**Comment by mbiebl** [comment]
https://packages.ubuntu.com/noble/apparmor-profiles is the package shipping that apparmor profile. Try contacting its maintainers.

**Comment by poettering** [comment]
> I don't understand how this can not be a systemd issue.

Changes in one package may cause different codepaths to be triggered in other packages. Apparmor needs a deep understanding of the services they provide policies for and the subsystems and libraries they use. If you change some of the services, subsystems or libraries this might require changes in those policies.

But the policies are not maintained by use, they are maintained by your distro generally, hence contact them

**Comment by sshedi** [comment]
Thanks @poettering and @mbiebl for the inputs. I will try to bring it to the attention of apparmor upstream devs.
Have a nice time ahead.
