### ISSUE TITLE
Inconsistent token PIN caching behavior between cryptsetup plugins and native code

### ISSUE THREAD

**Issue by Gigadoc2** [systemd/systemd#31744]
### systemd version the issue has been seen with

255.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.7.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

When systemd-cryptsetup asks for a token PIN (tested with a TPM2 pin), it should always either cache the PIN in the kernel keyring or not (subject to security considerations).

### Unexpected behaviour you saw

Whether the PIN is cached or not depends on which code path is taken: If the native code path is taken then systemd-askpass is not instructed to cache the PIN. If the cryptsetup plugin code path is taken then systemd-askpass _is_ instructed to cache the PIN (and re-use the cache if possible).

As I understand the code, in [attach_luks_or_plain_or_bitlk_by_tpm2](https://github.com/systemd/systemd/blob/b8e25bff386548f679902c6b797a5a8ff1542c8b/src/cryptsetup/cryptsetup.c#L1733), when the native code path calls https://github.com/systemd/systemd/blob/b8e25bff386548f679902c6b797a5a8ff1542c8b/src/cryptsetup/cryptsetup.c#L1858 the `arg_ask_password_flags` is statically defined 0, but in the token case the flags get explicitly added: https://github.com/systemd/systemd/blob/b8e25bff386548f679902c6b797a5a8ff1542c8b/src/cryptsetup/cryptsetup.c#L1275

### Steps to reproduce the problem

1. Create a VM capable of booting both measured and unmeasured, for example by having both a measured UKI and a type 1 bootloader entry in place, have it boot from an encrypted root partition enrolled to a TPM2 with PIN.
2. Boot the system with the measured UKI, entering the PIN when prompted
3. Log in as root (`sudo` does not suffice as you don't inherit the keyring this way, `machinectl shell` _might_ work)
4. Observe with `keyctl list @u` that there is no cached PIN.
5. Now boot the system in an unmeasured state, for example by booting from a type 1 bootloader entry, still entering the PIN when prompted
6. Log in as root again
7. Observe with `keyctl list @u` that now there is a key in the keyring: `user: luks2-pin`

**Comment by Gigadoc2** [comment]
Should one of the code paths go away (https://github.com/systemd/systemd/issues/30105) this inconsistency would of course cease to exist, though it might be worthwile to decide which behaviour to keep anyway.

I'd personally wish for the PIN to be cached to ease stuff like gnome-keyring unlocking (until gnome-keyring properly plugs into systemd-homed), but I do realize that especially for the TPM2 pin there might be security concerns associated with that.

**Comment by Gigadoc2** [comment]
Also now that I've written about it, it looks like the code paths also use different keyring names (if the native path _would_ have the flags set):

The native path includes the token name:
https://github.com/systemd/systemd/blob/b8e25bff386548f679902c6b797a5a8ff1542c8b/src/shared/cryptsetup-tpm2.c#L39
The plugin path uses a generic "luks2-pin":
https://github.com/systemd/systemd/blob/b8e25bff386548f679902c6b797a5a8ff1542c8b/src/cryptsetup/cryptsetup.c#L2399

**Comment by kszczek** [comment]
This inconsistency was resolved here: https://github.com/systemd/systemd/pull/32761#issuecomment-2172008759. Will have to wait for v257 to drop though.

**Comment by Gigadoc2** [comment]
Thanks a lot! I think the correct action is then to close the issue, as it is solved and doesn't need additional attention?
