### ISSUE TITLE
Set `NeedDaemonReload` when override directory is created

### ISSUE THREAD

**Issue by WilliamDEdwards** [systemd/systemd#31752]
### Component

systemd

### Is your feature request related to a problem? Please describe

systemd determines whether a unit was changed using `NeedDaemonReload` (paraphrasing).

Its value is incorrect in one specific case: when the override directory is created before having run `daemon-reload` once.

For example, let's say `/etc/systemd/system/test.service` looks like this:

```
[Unit]
Description=Test

[Service]
ExecStart=sleep 999
Type=simple

[Install]
WantedBy=multi-user.target
```

`systemctl -P NeedDaemonReload show test` returns `no`, because we're all up to speed.

Now, we create an override directory, and a file inside it (`/etc/systemd/system/test.service.d/test.conf`):

```
[Service]
ExecStartPre=true
```

`systemctl -P NeedDaemonReload show test` still returns `no`. Even though we need to `daemon-reload` to pick up this override. So, `NeedDaemonReload` should be `yes`.

Once we've done the initial `daemon-reload` after adding the override directory, changes _are_ taken into account by `NeedDaemonReload`.

### Describe the solution you'd like

When an override directory is added, let `NeedDaemonReload` take it into account right away, rather than only after the first `daemon-reload`.

### The systemd version you checked that didn't have the feature you are asking for

252.6

**Comment by poettering** [comment]
252 is ancient. Please reproduce with 255, as there have been changes in this area in the not so recent past

**Comment by WilliamDEdwards** [comment]
> 252 is ancient. Please reproduce with 255, as there have been changes in this area in the not so recent past

252 is the version on the most recent Debian (Bookworm), haha.

I'll try finding a distro with systemd 255, and report back.

**Comment by WilliamDEdwards** [comment]
> I'll try finding a distro with systemd 255, and report back.

Same behaviour on 255.4.

**Comment by WilliamDEdwards** [comment]
And for the time being: is there a first-party way of knowing which drop-in files _would_ be used?

Then I could `daemon-reload` based on that comparison.

**Comment by WilliamDEdwards** [comment]
> Hmm, I can't seem to reproduce this. Was the unit active before you added new drop-in?

Yes.

> If not, it would be GC'd, and each query for properties actually loads in a new unit into memory, thus requiring no reload.

No, I can confirm that the unit is 'missing' settings.
