### ISSUE TITLE
abnormal increase of RSS in systemd

### ISSUE THREAD

**Issue by YoruStar** [systemd/systemd#31757]
### systemd version the issue has been seen with

253

### Used distribution

centos 8

### Linux kernel version used

kernel-5.1

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

the RSS of systemd abnormal increase 

### Unexpected behaviour you saw

the RSS of systemd remains stable

### Steps to reproduce the problem

We are conducting stress tests on systemd. Previously, systemd’s RSS remained stable, but after adding the udevadm test test case, we observed an abnormal increase in systemd’s RSS. An example of the udevadm test test is as follows:
```
while true; do
    udevadm test //sys/class/net/enp5s0 -N late
    udevadm test -a remove /sys/class/block/sdb -N late
    udevadm test -a remove /sys/class/net/enp5s0 -N late
    udevadm test -a change /sys/class/block/sdc -N late
done
```

 We have conducted extensive tests on this and found as follow:
- after commenting out FileDescriptorStoreMax=4224 in systemd-journald.service, the RSS no longer increases
- After removing the log_debug() function called in the udevadm test, the RSS no longer increases

I currently cannot understand why the log printing in udevadm test would affect systemd. 

I hope to receive your assistance

**Comment by poettering** [comment]
RSS is not a useful metric, and systemd and glibc manage various allocation caches which means that unused memory is not immediately returned to the OS when released.

Starting with systemv v254 you can ask systemd explicitly to release its own allocation caches and those maintained by glibc by sending SIGRTMIN+18 with sigqueue() argument 0x300 to PID 1.

This is a bug tracker for te current systemd upstream versions btw. 253 is too old, the place to inquire for help for old versions is your distribution not systemd upstrream

Anyway, you are look at the wrong metric anyway, use cgroup metrics, not process metrics such as RSS.


Closing.
