### ISSUE TITLE
units of a unit chain created using requires and after do not die together

### ISSUE THREAD

**Issue by xh3b4sd** [systemd/systemd#3175]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 219
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

```
$ uname -a
Linux xxx 4.0.5 #2 SMP Thu Jun 18 08:53:45 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5620 @ 2.40GHz GenuineIntel GNU/Linux

$ systemctl version
Unknown operation 'version'.

$ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=681.2.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 681.2.0"
```
###### setup
- 1 "unit chain" consisting of 3 units
- all unit files are configured to execute `docker run` commands
###### the "unit chain"
- 1. unit requires 2. unit
- 2. unit requires 1. and 3. unit
- 2. unit "afters" 1. unit
- 3. unit requires 2. unit

The expected behaviour of this "unit chain" is that the chain acts as if it would be one unit. In case any of the units restarts or dies, the other units within the "unit chain" do so as well. 
### In case of bug report: Unexpected behaviour you saw

On `kill 1` within a container only the "killed" container's unit dies. All other units of the "unit chain" keep running.
### In case of bug report: Steps to reproduce the problem

Executing `kill 1` within one container of the "unit chain" makes the issue reproducible.

**Comment by poettering** [comment]
First of all, we only track issues in the two most recent systemd versions upstream, and 219 is too old. Please report this downstream instead.

Secondly, I am pretty sure you are looking for BindsTo=, not Requires=, see man page systemd.unit(5).
