### ISSUE TITLE
systemd-firstboot does not follow symlinked dirs when descending recursively into keymaps dirs

### ISSUE THREAD

**Issue by frederictobiasc** [systemd/systemd#31759]
### systemd version the issue has been seen with

255.2

### Used distribution

nixos-unstable

### Linux kernel version used

6.1.78

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

`systemd-firstboot` considers also keymaps symlinked from /usr/share/kbd/keymaps/*

### Unexpected behaviour you saw

`systemd-firstboot` does not recurse into the keymaps symlinked from `/usr/share/kbd/keymaps/*` causing systemd-firstboot to fail with `No keymaps are installed.`

### Steps to reproduce the problem

Add a symbolic link to a keymap into the search path of `systemd-firstboot` and see it not being considered.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
strace: https://gist.github.com/frederictobiasc/977114a618a341e4e3f6c2bccae5d1a5

# ls -l /usr/share/kbd/keymaps/
total 32
lrwxrwxrwx 1 root root 73 Jan  1  1970 amiga -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/amiga
lrwxrwxrwx 1 root root 73 Jan  1  1970 atari -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/atari
lrwxrwxrwx 1 root root 72 Jan  1  1970 i386 -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/i386
lrwxrwxrwx 1 root root 75 Jan  1  1970 include -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/include
lrwxrwxrwx 1 root root 71 Jan  1  1970 mac -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/mac
lrwxrwxrwx 1 root root 72 Jan  1  1970 pine -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/pine
lrwxrwxrwx 1 root root 71 Jan  1  1970 ppc -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/ppc
lrwxrwxrwx 1 root root 71 Jan  1  1970 sun -> /nix/store/gpqfmncz1xrqvv257pc7ps9c88hbxw3p-kbd-2.6.4/share/keymaps/sun
```

**Comment by frederictobiasc** [comment]
Hi, thanks for your quick reply!

> My understanding is that you are symlinking whole dirs into the dir [...]

Yes, that is correct. In my setup, `/usr/share/kbd/keymaps/` contains symlinks to directories. These directories contain the actual keymap files.

I'm working on getting `systemd-firstboot` running in NixOS. Unlike other distributions, NixOS doesn't maintain a `/usr` directory. All packages reside in `/nix/store`
I'm creating a bind mount inside the unit file to provide the keymaps at one of the [expected locations](https://github.com/systemd/systemd/blob/823ef2675d379186145094aed6fdb601ac2c914d/src/shared/kbd-util.h#L6):

```
--- a/systemd-firstboot.service
+++ b/systemd-firstboot-override.service
@@ -31,7 +31,12 @@ Before=shutdown.target
 [Service]
 Type=oneshot
 RemainAfterExit=yes
-ExecStart=systemd-firstboot --prompt-locale --prompt-timezone --prompt-root-password
+ExecStart=systemd-firstboot --prompt-locale --prompt-timezone --prompt-root-password --prompt-keymap
+# Bind mount keymaps to search path
+# https://github.com/systemd/systemd/blob/823ef2675d379186145094aed6fdb601ac2c914d/src/shared/kbd-util.h#L6
+TemporaryFileSystem=/usr:rw
+BindPaths=/nix/store/y4l5k6w71ggs86s5n2gdma428k53mcfn-console-env/share:/usr/share/kbd
 StandardOutput=tty
 StandardInput=tty
 StandardError=tty
```

Regarding the [hard-coded keymap search paths](https://github.com/systemd/systemd/blob/823ef2675d379186145094aed6fdb601ac2c914d/src/shared/kbd-util.h#L6): Is there any reason not to allow more flexibility here by setting additional search paths eg. via environment variables?

**Comment by yuwata** [comment]
@frederictobiasc

> Is there any reason not to allow more flexibility here by setting additional search paths eg. via environment variables?

-> #31778

**Comment by frederictobiasc** [comment]
> -> #31778

Wow, that was fast :)
