### ISSUE TITLE
journalctl --until is not inclusive

### ISSUE THREAD

**Issue by nrwahl2** [systemd/systemd#31798]
### systemd version the issue has been seen with

systemd-254.7-1.fc39.x86_64

### Used distribution

Fedora 39

### Linux kernel version used

6.6.4-200.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

The `journalctl(1)` man page says:

>        -S, --since=, -U, --until=
>            Start showing entries on or newer than the specified date, or on or older than the specified date, respectively.

Note "on or older." I expect that if I run `journalctl --until '2024-03-15 01:40:22'`, the output will include any log messages with timestamp `2024-03-15 01:40:22`.

### Unexpected behaviour you saw

The output of `journalctl --until '2024-03-15 01:40:22'` does not include log messages with timestamp `2024-03-15 01:40:22`.

### Steps to reproduce the problem

1. Get the timestamp of the most recent log message, in this case `2024-03-15 01:40:21`.
```
# journalctl --lines=1 --no-pager
Mar 15 01:40:21 fastvm-fedora39-21 audit[1]: SERVICE_STOP ...
```

2. Run `journalctl --until=<timestamp>` with that timestamp. The message from step 1 is not included in the output.
```
# journalctl --until='2024-03-15 01:40:21' --lines=1 --no-pager
Mar 15 01:40:11 fastvm-fedora39-21 systemd[1]: Started NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.
```

3. Run `journalctl --until=<timestamp + 1 second>`. The message from step 1 is included in the output.
```
# journalctl --until='2024-03-15 01:40:22' --lines=1 --no-pager
Mar 15 01:40:21 fastvm-fedora39-21 audit[1]: SERVICE_STOP ...
```

**Comment by YHNdnzj** [comment]
`01:40:21` means the µsec will be 0, while the message is _after_ `01:40:21.0`. If you specify `01:40:21.99` the message should be shown.

**Comment by YHNdnzj** [comment]
You can use `-o export` to get the exact timestamp of the message.
