### ISSUE TITLE
systemd-sysv-install is not invoked in preset operations

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#3179]
### Submission type
- Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

`systemctl preset my.service` should invoke `systemd-sysv-install` to synchronize the state. It doesn't currently do that:

```
$ sudo systemctl disable ssh
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install disable ssh
sysv-install invoked!
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
Removed symlink /etc/systemd/system/sshd.service.
$ sudo systemctl preset ssh                 
Created symlink from /etc/systemd/system/sshd.service to /lib/systemd/system/ssh.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/ssh.service to /lib/systemd/system/ssh.service.
$ sudo systemctl enable ssh
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ssh
sysv-install invoked!
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
```

Please ignore the insserv warnings. As you can see, preset does not invoke systemd-sysv-install to synchronize state.

**Comment by poettering** [comment]
Quite frankly I am not convinced that we should support features with sysv stuff beyond the level that sysv supported on its own. And presets are really not a concept sysv had, hence I am not convinced we shoul cover presets with sysv scripts.

**Comment by fsateler** [comment]
@poettering A preset is really a conditional enable/disable. So, if a service is enabled or disabled as part of a preset operation, that state should also be synchronized to the sysv world. Or in other words, systemd should issue a sysv-install enable for each unit it enables, and a sysv-disable for each unit it disables.

My idea is to synchronize state, not operations.

**Comment by poettering** [comment]
Given that systemd-sysv-generator really is a deprecated compat feature these days, let's just close this. I think this is conceptually a bad idea, and we should really work on removing this code altogether rather than extend it further.
