### ISSUE TITLE
The output lines of a script executed by a user service *sometimes* have a missing _SYSTEMD_USER_UNIT field in journal

### ISSUE THREAD

**Issue by correabuscar** [systemd/systemd#31800]
### systemd version the issue has been seen with

255.2

### Used distribution

NixOS

### Linux kernel version used

6.6.21

### CPU architectures issue was seen on

x86_64

### Component

journalctl, systemd-journald

### Expected behaviour you didn't see

I'm expecting that the stdout/stderr lines from my user service (named `user_startup.service`)'s executed bash script will always be shown in the output of `systemctl --user status user_startup` and `journalctl --user -u user_startup` just like they're always\* shown in `journalctl -b` and in `journalctl --since=-2h --user`

\* ie. whether this issue happens or not.

### Unexpected behaviour you saw

Starting/Finished lines are always shown on the output of `systemctl --user status user_startup` (regardless of this issue being at play or not), but the stdout/stderr of the script being executed by my user service is sometimes\* missing from the output. (apparently all lines at once, not just some lines)

\* sometimes, as if due to a race condition in systemd. (speculation)

The diff between two entries of the same message in the .journal files (gotten via `journalctl -o verbose --file=/var/log/journal/some_MACHINE_IDdirhere/*`) of two different reboots showing why this happens(missing fields attached to one stderr message, for example) is:
```diff
--- present	2024-03-15 10:00:44.906484081 +0100
+++ notpresent	2024-03-15 10:00:40.159484604 +0100
@@ -1,25 +1,14 @@
-Thu 2024-03-14 18:49:51.185260 CET [s=7df1d6f759ab4384918f6779348bb23d;i=546a9;b=b60f4327ae8d4fb68b4e07fd763da448;m=1eda512;t=613a284a3416c;x=6d8b267270d1c178]
+Thu 2024-03-14 19:41:32.649381 CET [s=0c58f041cb5840608d1969c3a8d3e6ed;i=5fdd1;b=6e053e8b342e4f03ac8b2879b9bd4a66;m=2f20a79;t=613a33d7fd7a5;x=a1ce25b12e3b537d]
     PRIORITY=6
     SYSLOG_FACILITY=3
     _UID=1000
     _GID=100
-    _AUDIT_SESSION=3
-    _AUDIT_LOGINUID=1000
-    _SYSTEMD_OWNER_UID=1000
-    _SYSTEMD_UNIT=user@1000.service
-    _SYSTEMD_SLICE=user-1000.slice
-    _BOOT_ID=b60f4327ae8d4fb68b4e07fd763da448
+    _BOOT_ID=6e053e8b342e4f03ac8b2879b9bd4a66
     _MACHINE_ID=e485504011a34ba5b4e595f0a89c9806
     _HOSTNAME=vbox1
     _RUNTIME_SCOPE=system
     _TRANSPORT=stdout
-    _STREAM_ID=d1e2858fcf7f4567bd30ce107a409a42
+    _STREAM_ID=87a6ef3f157a4cb98a78fc236b1e5db7
     SYSLOG_IDENTIFIER=_user startup.bash
-    _PID=1086
-    _COMM=bash
-    _CAP_EFFECTIVE=0
-    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/user@1000.service/app.slice/user_startup.service
-    _SYSTEMD_USER_UNIT=user_startup.service
-    _SYSTEMD_USER_SLICE=app.slice
-    _SYSTEMD_INVOCATION_ID=258e24fc8a9d4e85953f89797f9668e3
+    _PID=1148
     MESSAGE=/home/user/bin/_user startup.bash says hi on stderr before redirecting to /tmp/user_startup.log
```

This suggests that this message is missing from the output (of `systemctl --user status user_startup`) because the field `_SYSTEMD_USER_UNIT=user_startup.service` is missing from the journal log.

### Steps to reproduce the problem

This is gonna be difficult to reproduce the problem because the issue seems to be a race condition and it happens only sometimes... but if I use `systemd.log_target=kmsg` on kernel cmdline, then it's the issue that happens most of the time and works correctly only sometimes(or so it seems to me, at least). However, with that =kmsg (instead of =journal or =auto) it will never log the Starting/Finished log lines (which may be a normal thing with =kmsg, I'm unsure), but it will log the stdout/stderr from the script (when the issue isn't happening)

Please give me a few hours to devise the repro. steps from scratch in a fresh virtualbox install of NixOS, and I will edit this later with the steps to reproduce soon (unless someone says not to do it in a reply).

I've previously thought it was due to this issue: https://github.com/systemd/systemd/issues/30092#issuecomment-1997458203

The below `Additional program output to the terminal or log subsystem illustrating the issue` but with SYSTEMD_LOG_LEVEL=debug is here: https://gist.github.com/correabuscar/5064028a86ce82811a3229cb8e4ecb3d

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[user@vbox1:~]$ systemctl --user status user_startup |cat ; echo --------; journalctl -S -1h --user |grep user |tail -24|head -10 ; echo -------; journalctl -u systemd-journald.service | tail -2
● user_startup.service - user-level startup stuff
     Loaded: loaded (/etc/systemd/user/user_startup.service; enabled; preset: enabled)
     Active: active (exited) since Fri 2024-03-15 09:22:29 CET; 48min ago
   Main PID: 1078 (code=exited, status=0/SUCCESS)
        CPU: 9ms

Mar 15 09:22:29 vbox1 systemd[1068]: Starting user-level startup stuff...
Mar 15 09:22:29 vbox1 systemd[1068]: Finished user-level startup stuff.
--------
Mar 15 09:22:29 vbox1 nixos-activation-start[1083]: removed '/home/user/.cache/icon-cache.kcache'
Mar 15 09:22:29 vbox1 _user startup.bash[1078]: /home/user/bin/_user startup.bash says hi on stdout before redirecting to /tmp/user_startup.log
Mar 15 09:22:29 vbox1 _user startup.bash[1078]: /home/user/bin/_user startup.bash says hi on stderr before redirecting to /tmp/user_startup.log
Mar 15 09:22:29 vbox1 systemd[1068]: Starting Run user-specific NixOS activation...
Mar 15 09:22:29 vbox1 systemd[1068]: Starting user-level startup stuff...
Mar 15 09:22:29 vbox1 systemd[1068]: Finished user-level startup stuff.
Mar 15 09:22:29 vbox1 nixos-activation-start[1088]: removed '/home/user/.cache/ksycoca5_en_A5V7xjE3kQrHGFhkalEn4Z4ndy8='
Mar 15 09:22:29 vbox1 nixos-activation-start[1088]: removed '/home/user/.cache/ksycoca5_en_NOkp7MEgDggTd9qUQSaCSAs_KlY='
Mar 15 09:22:29 vbox1 nixos-activation-start[1088]: removed '/home/user/.cache/ksycoca5_en_OHUu+ApaW6tYOnqMDyhBnfEu+q8='
Mar 15 09:22:29 vbox1 nixos-activation-start[1088]: removed '/home/user/.cache/ksycoca5_en_QBz3GGts+neh1AX+eDSOIHoKH_Q='
-------
Mar 15 09:22:15 vbox1 systemd-journald[442]: Rotating system journal.
Mar 15 09:22:29 vbox1 systemd-journald[442]: /var/log/journal/e485504011a34ba5b4e595f0a89c9806/user-1000.journal: Journal file uses a different sequence number ID, rotating.
```

**Comment by arvidjaar** [comment]
This sounds like https://github.com/systemd/systemd/issues/1347

But I am curious.


> ```diff
> -    _SYSTEMD_UNIT=user@1000.service
> -    _SYSTEMD_SLICE=user-1000.slice
> ...
> -    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/user@1000.service/app.slice/user_startup.service
> ```

I would actually expect `_SYSTEMD_UNIT=user_startup.service` and `_SYSTEMD_SLICE=app.slice`, but maybe I misunderstand what they mean.

**Comment by correabuscar** [comment]
Thank you for your quick reply, at first glance I believe you're right, it might just be https://github.com/systemd/systemd/issues/1347

To be honest, I actually forgot to search for _SYSTEMD_USER_UNIT in issue after I've realized what was going on (the diff).

**Comment by correabuscar** [comment]
closing in favor of the still opened https://github.com/systemd/systemd/issues/2913

reopen if you think I'm wrong
