### ISSUE TITLE
RFE: PID1 add ExecFail= option to start executables on service failure

### ISSUE THREAD

**Issue by alban** [systemd/systemd#3184]
**Submission type**:  Request for enhancement (RFE)

This is to continue the discussion that has been initially started on https://bugs.freedesktop.org/show_bug.cgi?id=89840

> When starting a systemd unit file, it might print the following error based on errno=ENOENT:
> `testscript[9959]: Failed at step EXEC spawning /testscript: No such file or directory`
> This could mean /testscript is missing, or ld-2.19.so is missing or the interpreter in the shebang is missing.
> But the error message is not precise enough to know. The kernel does not give more details when execve() fails with errno=ENOENT.
> In order to print better error messages, we could have an option ExecFail in the unit file:
> `ExecFail=/usr/bin/diagexec`
> It would start the diagnostic tool to guess why execve() returned ENOENT.
> The code for diagexec is there:
> https://github.com/coreos/rocket/blob/master/stage1/rootfs/diagexec/diagexec.c#L58

rkt is tracking this feature request via https://github.com/coreos/rkt/issues/2506

I would like ExecFail to work with ExecStartPre and ExecStopPost as well (the table in https://github.com/coreos/rkt/issues/1495#issuecomment-216614082 can be useful).

**Comment by poettering** [comment]
Yes, I think this would make a lot of sense to add.

**Comment by vcaputo** [comment]
In the context of rkt, if the `RootDirectory=` directive is being utilized, and this hypothetical `ExecFail=` directive were implemented consistent with the other `Exec*` directives, then `diagexec` would need to be present in the per-app chroot directory hierarchy.

This was something we chose to avoid because we didn't want to inject binaries into the tree visible to the application container.

**Comment by johannbg** [comment]
Is "ExecFail=" a new directive that is supposed to replace/behave the same as OnFailure in type units?

**Comment by alban** [comment]
ExecFail= takes a command line, but OnFailure= takes an unit name. Also, ExecFail= could run only when execve() fails, not necessarily on other failures (like a non zero return value).

**Comment by alban** [comment]
FYI, @alepuccetti is currently implementing an alternative method for running the diagnostic tool in rkt without needing a new option `ExecFail=` in systemd. See https://github.com/coreos/rkt/pull/2872

**Comment by poettering** [comment]
BTW, there's not `$SERVICE_RESULT` that is set in ExecStop= and allows you to implement what you need... Not sure it's really necessary to still implement ExecFail=

**Comment by poettering** [comment]
I think $SERVICE_RESULT is ver appropriate for the usecase. Closing hence.
