### ISSUE TITLE
IPv6 Compliance RFC4861: Router Advertisement Processing, Reachable Time [v6LC.2.2.15]

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [systemd/systemd#31842]
### systemd version the issue has been seen with

255 
```
$ git log -n 1
commit 3f340facd6d0f3e4cc9c90a68c244520f3b5affd (HEAD -> network-next, origin/network-next)
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Tue Mar 12 18:41:38 2024 +0900
```

### Used distribution

Ubuntu 23

### Linux kernel version used

6.5.0-17-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

#### Test v6LC.2.2.15: Router Advertisement Processing, Reachable Time
**Purpose**: Verify that a node updates its BaseReachableTime variable and re-computes its ReachableTime variable upon receipt of a Router Advertisement or a configuration with a specified Reachable Time.
**Reference**: RFC4861 – [Section 6.3.4](https://www.ietf.org/rfc/rfc4861.html#section-6.3.4)

#### Network Configuration
```
        TR1
         |
    +----+-----+
    |          |
   TN1        HUT
```

#### Procedure
| Step | Action | Expected Behavior of HUT<sup>(1)</sup> |
|--------|--------|--------|
| 1 | TR1 sends `RA RouterLifetime=0 ReachableTime=10s` to HUT | |
| 2 | TN1 sends LL `Echo request` to HUT. TN1 replies to any NS from the HUT. | HUT sends `NS for TN1's LLA` and sends `Echo reply`. |
| 3 | Repeat step 2 every second for 40 seconds. | HUT sends `NS TargetAddress="TN1's LLA"` at an interval between 10-20s. [ReachableTime time (between 5-15s) + DELAY_FIRST_PROBE_TIME (5s)] |
| 4 | TR1 sends `RA ReachableTime=40s` | |
| 5 | Repeat step 2 every second for 140 seconds. | HUT sends `NS TargetAddress="TN1's LLA"` at an interval between 25-65s. [ReachableTime time (between 20-60s) + DELAY_FIRST_PROBE_TIME (5s)] |
 * **(1)** - Host Under Test

### Unexpected behaviour you saw

In Step 3, the HUT never sends a `NS TargetAddress="TN1's LLA"`.

### Steps to reproduce the problem

[v6LC_2_2_15a.zip](https://github.com/systemd/systemd/files/14644737/v6LC_2_2_15a.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

```
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 0
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: NDISC: Received Neighbor Advertisement from fe80::200:10ff:fe10:1080: Router=no, Solicited=yes, Override=no
enp0s9: NDISC: Invoking callback for 'neighbor' event.
enp0s9: NDISC: Received Neighbor Advertisement from fe80::200:10ff:fe10:1080: Router=no, Solicited=no, Override=yes
enp0s9: NDISC: Invoking callback for 'neighbor' event.
enp0s9: NDISC: Received Router Advertisement: flags none preference medium lifetime 0
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Requesting NDisc route (n/a): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Setting SLAAC addresses and router.
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Refuse to configure NDisc route with zero lifetime.
enp0s9: NDISC: Received Neighbor Advertisement from fe80::200:10ff:fe10:1060: Router=yes, Solicited=no, Override=yes
enp0s9: NDISC: Invoking callback for 'neighbor' event.
```

**Comment by LiveFreeAndRoam** [comment]
@yuwata, the test is expecting the ReachableTime be updated, even when the RouterLifetime value is set to zero.  As you'd be aware, the code currently requires two things:

1. The RA is received from a default router
2. The router lifetime is non-zero

However, the certification test clearly requires the ReachableTime to be updated, regardless of the two checks above.

An extract from RFC486,

>    If the received Reachable Time value is non-zero, the host SHOULD set
   its BaseReachableTime variable to the received value.  If the new
   value differs from the previous value, the host SHOULD re-compute a
   new random ReachableTime value.  ReachableTime is computed as a
   uniformly distributed random value between MIN_RANDOM_FACTOR and
   MAX_RANDOM_FACTOR times the BaseReachableTime.  Using a random
   component eliminates the possibility that Neighbor Unreachability
   Detection messages will synchronize with each other.

>   In most cases, the advertised Reachable Time value will be the same
   in consecutive Router Advertisements, and a host's BaseReachableTime
   rarely changes.  In such cases, an implementation SHOULD ensure that
   a new random value gets re-computed at least once every few hours.

>   The RetransTimer variable SHOULD be copied from the Retrans Timer
   field, if the received value is non-zero.

Notice the RetransTimer is being treated in the same way as ReachableTime, so I suspect for correct behaviour, we need this code stanza removed:

https://github.com/yuwata/systemd/blob/network-next/src/network/networkd-ndisc.c#L926
https://github.com/yuwata/systemd/blob/network-next/src/network/networkd-ndisc.c#L2096

```C
        /* Ignore the xxxxxx field of the RA header if the lifetime is zero. */
        r = sd_ndisc_router_get_lifetime(rt, NULL);
        if (r <= 0)
                return r;
```

**Comment by yuwata** [comment]
How about MTU? Also managed and other flags?

**Comment by LiveFreeAndRoam** [comment]
Yes, I think all of them, but I have not been exhaustive with the RFC.  I'm still reading.

**Comment by LiveFreeAndRoam** [comment]
BTW, I tried modifying the code so that the ReachableTime gets updated, though that still wasn't enough to get this test to pass.  Something else must also be controlling the transmission of the NS.

**Comment by LiveFreeAndRoam** [comment]
Here is the definitive statement about the [RouterLifeTime](https://www.ietf.org/rfc/rfc4861.html#section-4.2:~:text=The%20Router%20Lifetime%20applies%20only%20to%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20the%20router%27s%20usefulness%20as%20a%20default%20router%3B%20it%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20does%20not%20apply%20to%20information%20contained%20in%20other%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20message%20fields%20or%20options.)

> The Router Lifetime applies only to
                     the router's usefulness as a default router; it
                     does not apply to information contained in other
                     message fields or options.
 
So yes, that check should be removed from MTU, CurHopLimit, ReachableTime, RetransmissionTimer. The exception would be  CaptivePortal, as per your comment in the code.

**Comment by yuwata** [comment]
Force-pushed and the offending commit is dropped.

**Comment by LiveFreeAndRoam** [comment]
I retested and it is passed. I will close this issue. Thank you @yuwata.

For the record, I used:

```
$ git log -n 1
commit 2e96fcb0a8a5a82adb5afad425c23cadffc70b1c (HEAD -> network-next, origin/network-next)
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Sat Mar 16 02:32:50 2024 +0900
```

**Comment by LiveFreeAndRoam** [comment]
For tracking, this change also corrected:

Test | Title
-- |--
v6LC_2_2_15a | Router   Advertisement Processing, Reachable Time (Host only)
v6LC_2_2_16f | Router Advertisement   Processing, Neighbor Cache (Hosts Only) (SLLA change, NCE Probe)
v6LC_2_2_16g | Router Advertisement   Processing, Neighbor Cache (Hosts Only) (SLLA nochange, NCE Probe)
v6LC_2_2_16h | Router Advertisement   Processing, Neighbor Cache (Hosts Only) (SLLA omitted, NCE Probe)
v6LC_2_2_16j | Router Advertisement   Processing, Neighbor Cache (Hosts Only) (SLLA nochange, NCE Stale)
v6LC_2_2_16k | Router Advertisement   Processing, Neighbor Cache (Hosts Only) (SLLA omitted, NCE Stale)

**Comment by LiveFreeAndRoam** [comment]
In the merge back to main, this test was failing once again. I have identified the cause and will raise a PR.  Basically, the code was once again checking for a non-zero router lifetime before setting other option values.  In fact, the router lifetime is unrelated to other option settings, as per:

Here is the definitive statement about the [RouterLifeTime](https://www.ietf.org/rfc/rfc4861.html#section-4.2:~:text=The%20Router%20Lifetime%20applies%20only%20to%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20the%20router%27s%20usefulness%20as%20a%20default%20router%3B%20it%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20does%20not%20apply%20to%20information%20contained%20in%20other%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20message%20fields%20or%20options.)

> The Router Lifetime applies only to
the router's usefulness as a default router; it
does not apply to information contained in other
message fields or options.

**Comment by LiveFreeAndRoam** [comment]
Fixed by: https://github.com/systemd/systemd/pull/32792
