### ISSUE TITLE
sd_notify: support sending notification over stream VSOCK

### ISSUE THREAD

**Issue by bouk** [systemd/systemd#31849]
### Component

systemd

### Is your feature request related to a problem? Please describe

Hi, I'm trying to get the credential-based `vmm.notify_socket` working under [cloud-hypervisor](https://www.cloudhypervisor.org). Unfortunately its (and firecracker's) vsock implementation only supports STREAM sockets, not DGRAM or SEQPACKET. 

### Describe the solution you'd like

I'd like to be able to send the notification over a stream VSOCK if it is available. Although this might not be enough, since the `NOTIFY_SOCKET` on the host side is a Unix datagram socket so cloud-hypervisor might not be able to forward the traffic—since it will try to open the socket as a unix stream.

### Describe alternatives you've considered

https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6307

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by DaanDeMeyer** [comment]
This is already supported, use `vsock-stream` instead of `vsock`
