### ISSUE TITLE
Cannot set property Delegate, or unknown property.

### ISSUE THREAD

**Issue by vanloswang** [systemd/systemd#3186]
### Submission type
- [ ] Bug report
### systemd version the issue has been seen with

> systemd-216
### Used distribution

> fedora 21
### In case of bug report: Expected behaviour you didn't see

> Cannot set property Delegate, or unknown property.
> This error is reported in src/core/dbus-unit.c at bus_unit_set_properties.
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

**Comment by vanloswang** [comment]
How to fix it? upgrade the systemd to a latest version?

**Comment by poettering** [comment]
This is not a help forum, but a bug tracker. Moreover, we explicity don't track issues here in versions older than the two most recent releases. If you are looking for support, consider contacting the systemd mailing list. Thanks.
