### ISSUE TITLE
Failing to load touchpad, microphone, various other devices

### ISSUE THREAD

**Issue by atauln** [systemd/systemd#31876]
### systemd version the issue has been seen with

255.4-2-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.8.1-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Load devices under `fwupdmgr get-devices` and be able to use them.

### Unexpected behaviour you saw

Not able to use microphone or touchpad. Checked logs and TPM seems to be skipped due to unmet condition check `ConditionSecurity=measured-uki`. Also, running `fwupdmgr get-devices` lists these devices but says they have no firmware updates with a bunch of miscellaneous question marks.

### Steps to reproduce the problem

1. Occurs on boot

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/atauln/9f3dbf2c975f4c6beb7fa18039acf4a5

**Comment by atauln** [comment]
Based on what I've delved into, I think this is probably a TPM2 issue, but I checked my BIOS and TPM2 is enabled. I have a Lenovo Thinkpad P14s.

**Comment by yuwata** [comment]
> Not able to use microphone or touchpad.

Why these device depend on TPM2? Which unit uses `ConditionSecurity=measured-uki` ??
I guess some services for microphone or so simply not installed or disabled, and TPM2 logs are unrelated.

**Comment by poettering** [comment]
Sorry, but this seems unrelated to systemd. Please contact your distro for help first. If they determine there's a systemd problem, they'll report back to us.
