### ISSUE TITLE
networkd / networkctl should have a command to hard-reset a device to configured state

### ISSUE THREAD

**Issue by maikzumstrull** [systemd/systemd#3188]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229-4ubuntu4 (Ubuntu xenial)
### Used distribution

> Ubuntu xenial
### Problem description

I've noticed that when reconfiguring the network (dropping additional .network files in /etc/systemd/network, then running systemctl restart systemd-networkd), networkd avoids changing the configuration in certain ways:
- If the link is already up, the MTU isn't changed
- If the device already has IP addresses on it, they aren't removed even when they're not in the config
- IP addresses the device doesn't have but should have according to the new config are added, though

I assume this behavior is intentional to avoid interrupting connectivity. However, there are situations when I want to be sure devices are configured exactly according to spec. Specifically, I'm currently working on machine deployment scripts, which pivot the network config from DHCP (used for installation and early setup) to static configuration (for production use).

It would be very useful for me to have a `networkctl reset ens2f0` (or similar) command to tell networkd, no seriously, I've changed the config, please take the device down and rebuild the state _exactly_ as specified.

**Comment by ssahani** [comment]
similar to #1546

**Comment by yuwata** [comment]
`networkctl reconfigure IFNAME` or `networkctl reload` should work. Closing.
