### ISSUE TITLE
Misconfigured UNIX socket activation fails with cryptic error message: "Failed to set socket on service: Invalid argument"

### ISSUE THREAD

**Issue by CyberShadow** [systemd/systemd#31915]
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.7.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Socket activation works as before

### Unexpected behaviour you saw

Attempting to connect to the socket created by systemd results in:

```
Mar 23 06:52:48 localhost systemd[841]: socket-test.socket: Failed to set socket on service: Invalid argument
Mar 23 06:52:48 localhost systemd[841]: socket-test.socket: Failed with result 'resources'.
```

### Steps to reproduce the problem

```bash
#!/bin/bash
set -eEuo pipefail

cat > ~/.config/systemd/user/socket-test.socket <<EOF
[Socket]
ListenStream=%h/test.socket
Accept=yes
EOF

cat > ~/.config/systemd/user/socket-test.service <<EOF
[Service]
ExecStart=/bin/bash
StandardInput=socket
EOF

systemctl --user daemon-reload
systemctl --user start socket-test.socket
curl --unix-socket ~/test.socket http://server/
```

Note, this seems to be a regression. It worked a few years ago when I set it up :)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Mar 23 06:52:48 localhost systemd[841]: Listening on socket-test.socket.
Mar 23 06:52:48 localhost systemd[841]: socket-test.socket: Failed to set socket on service: Invalid argument
Mar 23 06:52:48 localhost systemd[841]: socket-test.socket: Failed with result 'resources'.
```

**Comment by YHNdnzj** [comment]
Quoted from `systemd.socket(5)`:

> The name of the .service unit is by default the same as the name of the .socket unit, but can be altered with the Service= option described below. Depending on the setting of the Accept= option described below, this .service unit must either be named like the .socket unit, but with the suffix replaced, unless overridden with Service=; or it must be a template unit named the same way. Example: a socket file foo.socket needs a matching service foo.service if Accept=no is set. If Accept=yes is set, a service template foo@.service must exist from which services are instantiated for each incoming connection.

Here you have a socket unit with `Accept=yes` but no associated template service unit.

**Comment by CyberShadow** [comment]
Alright, let's change this to an enhancement for a reasonable error message. Currently, the error message printed by systemd is not mentioned absolutely anywhere.

This used to work in previous systemd versions. Where is the breaking change described, please?

**Comment by YHNdnzj** [comment]
> This used to work in previous systemd versions. Where is the breaking change described, please?

I don't think this ever worked? If you want to activate a non-template service, just use `Accept=no`? (The name of the option is potentially misleading, but the man page is pretty clear on this).

**Comment by CyberShadow** [comment]
> I don't think this ever worked?

Yes, you are right - I renamed it accidentally (removing the `@`) a few months ago and `git log` did not show the rename.

The error message does look like a regression, though; systemd 245 prints something more sensible:

```
Mar 23 19:07:29 ubuntu systemd[1376]: Listening on socket-test.socket.
Mar 23 19:07:41 ubuntu systemd[1376]: socket-test.socket: Failed to queue service startup job (Maybe the service file is missing or not a template unit?): Invalid argument
Mar 23 19:07:41 ubuntu systemd[1376]: socket-test.socket: Failed with result 'resources'.
```

> If you want to activate a non-template service, just use Accept=no? (The name of the option is potentially misleading, but the man page is pretty clear on this).

Indeed, making it a template unit fixed it again. Thank you!
