### ISSUE TITLE
reboot check-inhibitors does not work the same as dbus RebootWithFlags with SD_LOGIND_ROOT_CHECK_INHIBITORS

### ISSUE THREAD

**Issue by Gunni** [systemd/systemd#31910]
### systemd version the issue has been seen with

255.4-1ubuntu5

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-14-generic

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd, other

### Expected behaviour you didn't see

`systemctl reboot --check-inhibitors=yes`

should work the same as

`busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager RebootWithFlags t 1`

Documentation states:
> When the `flags` is `0` then these methods behave just like the versions without flags. When `SD_LOGIND_ROOT_CHECK_INHIBITORS` (0x01) is set, active inhibitors are honoured for privileged users too.

p.s. this br references `RebootWithFlags` but `PowerOffWithFlags` has the same problem.

### Unexpected behaviour you saw

If inhibitor uid is different than invoker of `RebootWithFlags` with `SD_LOGIND_ROOT_CHECK_INHIBITORS` then reboot is blocked.

If inhibitor uid is the same as the invoker of `RebootWithFlags` with `SD_LOGIND_ROOT_CHECK_INHIBITORS` then reboot happens regardless of flag.

### Steps to reproduce the problem

currently inhibiting as user other than root

```
root@example [ ~ ]$ systemd-inhibit 
WHO            UID  USER       PID  COMM            WHAT     WHY            MODE 
sleep infinity 1000 example-us 1137 systemd-inhibit shutdown Unknown reason block

1 inhibitors listed.
root@example [ ~ ]$ systemctl reboot --check-inhibitors=yes
Operation inhibited by "sleep infinity" (PID 1137 "systemd-inhibit", user edge-admin), reason is "Unknown reason".
Please retry operation after closing inhibitors and logging out other users.
Alternatively, ignore inhibitors and users with 'systemctl reboot -i'.
(failed reverse-i-search)`list': systemct^Creboot --check-inhibitors=yes
root@example [ ~ ]$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager ListInhibitors
a(ssssuu) 1 "shutdown" "sleep infinity" "Unknown reason" "block" 1000 1137
root@example [ ~ ]$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager RebootWithFlags t 1
Call failed: Access denied
```

previous inhibit removed and created new inhibit by user root

```
root@example [ ~ ]$ systemd-inhibit
WHO            UID USER PID  COMM            WHAT     WHY            MODE 
sleep infinity 0   root 1275 systemd-inhibit shutdown Unknown reason block

1 inhibitors listed.
root@example [ ~ ]$ systemctl reboot --check-inhibitors=yes
Operation inhibited by "sleep infinity" (PID 1275 "systemd-inhibit", user root), reason is "Unknown reason".
Please retry operation after closing inhibitors and logging out other users.
Alternatively, ignore inhibitors and users with 'systemctl reboot -i'.
root@example [ ~ ]$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager ListInhibitors
a(ssssuu) 1 "shutdown" "sleep infinity" "Unknown reason" "block" 0 1275
root@example [ ~ ]$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager RebootWithFlags t 1
root@example [ ~ ]$ Connection to 2001:db8:: closed by remote host.
Connection to 2001:db8:: closed.
```

**Comment by YHNdnzj** [comment]
Note that the inhibitor logic is being reworked in v256, where the `SD_LOGIND_ROOT_CHECK_INHIBITORS` flag will be deprecated: https://github.com/systemd/systemd/pull/30307

**Comment by Gunni** [comment]
I was _juuust_ reading it as you commented, it looks good to me, I'd love inhibitors to always be honored, not only when asking to honor them.

Until that's merged, this inconsistency is still a thing though.
