### ISSUE TITLE
udev not matching correctly on USB model ID

### ISSUE THREAD

**Issue by github-k8n** [systemd/systemd#3192]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229
### Used distribution

Gentoo
### In case of bug report: Expected behaviour you didn't see

Neither of those rules does match an usb device with ID_VENDOR_ID=20a0 / ID_MODEL_ID=0004
`SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="20a0", ATTR{idProduct}=="0004", MODE="0666"`
Neither does this:
`SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ENV{ID_VENDOR_ID}=="20a0", ENV{ID_MODEL_ID}=="0004", MODE="0666"`
### In case of bug report: Unexpected behaviour you saw

However they DO match if I add an asterisk at the end of the model ID ("0004*") then the resulting device is actually mode 666
`SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="20a0", ATTR{idProduct}=="0004*", MODE="0666"`
or also with this
`SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ENV{ID_VENDOR_ID}=="20a0", ENV{ID_MODEL_ID}=="0004*", MODE="0666"`
### In case of bug report: Steps to reproduce the problem

Enter the rules mentioned above then connect a flirc usb device:
UDEV  [5152.137085] add      /devices/pci0000:00/0000:00:14.0/usb3/3-1 (usb)
ACTION=add
BUSNUM=003
DEVNAME=/dev/bus/usb/003/008
DEVNUM=008
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_MODEL=flirc
ID_MODEL_ENC=flirc
ID_MODEL_ID=0004
ID_REVISION=0100
ID_SERIAL=flirc.tv_flirc
ID_USB_INTERFACES=:030001:ffffff:
ID_VENDOR=flirc.tv
ID_VENDOR_ENC=flirc.tv
ID_VENDOR_FROM_DATABASE=Clay Logic
ID_VENDOR_ID=20a0
MAJOR=189
MINOR=263
PRODUCT=20a0/4/100
SEQNUM=2176
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=5152123054

**Comment by keszybz** [comment]
This should be fixed by #3185. Can you check with the latest git?

**Comment by poettering** [comment]
What is this rule supposed to do? what do you want that MODE== applied on?

**Comment by github-k8n** [comment]
It is MODE="0666" not MODE=="0666"
And it applies to the created usb device below /dev/bus/usb

@keszybz, i'll try to test the latest git tonight

**Comment by github-k8n** [comment]
@keszybz , tested with current git and it looks good, now it matches without the asterisk!
Any timeline for the next release containing this?
Thanks.

**Comment by keszybz** [comment]
A few days. We're going through the remaining bugs and regressions.
