### ISSUE TITLE
After TPM2 encryption is invalid, provide methods to reregister?

### ISSUE THREAD

**Issue by Doomsdayrs** [systemd/systemd#31936]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

Every so often, I have to re-register my encryption with my TPM2 chip.
This is a tedious process, especially given that this happens every so often.

Re-register steps (per each luks partition):
1. Wipe TPM slot
2. Re-enroll with TPM

### Describe the solution you'd like

A few solutions:

1. Re-enroll upon a successful password entry.
3. Provide a way to toggle # 1 so that password entries can provide a checkbox or toggle to change the behavior during entry.
4. A system where tpm2 is checked to match the *new* state after an update, but before a reboot, to then re-register with the new state while system is operational.

### Describe alternatives you've considered

1. "systemd-cryptenroll reregister --tpm2-device=auto": Goes through each device, and re-registers the TPM (as described before)

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by grawity** [comment]
> A system where tpm2 is checked to match the new state after an update, but before a reboot, to then re-register with the new state while system is operational.

Doesn't that already exist as systemd-measure?

I've written my own tools for this (re-enrolling PCR4 before reboot), although unfortunately they're a bit neglected – I've the impression that the new "signed PCR" feature in systemd-measure/cryptenroll is supposed to supersede that.

**Comment by poettering** [comment]
systemd-pcrlock is supposed to cover this case. i.e. the TPM access policy is automatically regenerated on each successful boot and stored in an NVindex, which the disk locks against.
