### ISSUE TITLE
systemd fails to compile when openssl is built with 'no-deprecations'

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#31956]
### systemd version the issue has been seen with

255 / master

### Used distribution

custom

### Linux kernel version used

6.1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

systemd should compile

### Unexpected behaviour you saw

Multiple missing symbols in the form:

```
../src/shared/openssl-util.c: In function 'rsa_encrypt_bytes':
../src/shared/openssl-util.c:515:13: error: implicit declaration of function 'EVP_PKEY_CTX_set_rsa_padding'; did you mean 'EVP_PKEY_CTX_set_app_data'? [-Werror=implicit-function-declaration]
  515 |         if (EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_PADDING) <= 0)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             EVP_PKEY_CTX_set_app_data
```

### Steps to reproduce the problem

-   Use openssl >= 3.0
-   either build openssl with no-deprecated, or manually define `OPENSSL_NO_DEPRECATED` (like in `openssl-util.h` before including any openssl header)
-   try to build systemd

Solved by adding the include to `src/shared/openssl-util.c`:

``` c
#if HAVE_OPENSSL
#include <openssl/rsa.h>
```

Maybe add the `OPENSSL_NO_DEPRECATED` define for CI/Codequality runs to catch this stuff early?

**Comment by keszybz** [comment]
With `OPENSSL_NO_DEPRECATED`, we fail massively because openssl engine stuff is missing, so `openss-util.h` is completely broken. In Fedora, we recently discussed and rejected a proposal to drop engine support: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/SEH75XSFCVS44VKDYOP2ZECLTH4YETNC/.

I don't think we can commit to supporting `OPENSSL_NO_DEPRECATED`.

If there's some combination which would work with `OPENSSL_NO_DEPRECATED` without too much work, please submit a patch though.

**Comment by nolange** [comment]
AFAIK, `OPENSSL_NO_DEPRECATED` can be set without `OPENSSL_NO_ENGINE`

I made a separate bug report for that: #31958

The fix for this issue would still be to just include the `rsa.h` Header.

**Comment by nolange** [comment]
ok, the functions will be missing when **either** `OPENSSL_NO_DEPRECATED` or `OPENSSL_NO_ENGINE` is set.
when is v256 due? I locally have some fixes I could dress up, apply some lipstick and and open a PR.

> I don't think we can commit to supporting OPENSSL_NO_DEPRECATED.

This gets me though, there might be some more places that need fixup, but there aint that much to do. Once the flag is covered with CI there shouldnt be much of an issue.
