### ISSUE TITLE
Inconsistent character encoding

### ISSUE THREAD

**Issue by opoplawski** [systemd/systemd#31976]
### systemd version the issue has been seen with

systemd-252-18.el9.x86_64

### Used distribution

EL9

### Linux kernel version used

5.14.0-362.18.1.el9_3.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup, systemd-udevd

### Unexpected behaviour you saw

I need to write a udev rule that will restart the cryptsetup service for a luks encoded volume.  The cryptsetup service has a name like `systemd-cryptsetup@luks\x2d16f5b686\x2d8669\x2d407b\x2d920d\x2d427fa8b81328.service` but the udev event has:
```
ID_FS_UUID=16f5b686-8669-407b-920d-427fa8b81328
ID_FS_UUID_ENC=16f5b686-8669-407b-920d-427fa8b81328
```
If we're going to be encoding `-` as `\x2d`, it would be helpful if it were done consistently.

**Comment by yuwata** [comment]
Please try systemd-escape:
```sh
$ systemd-escape 16f5b686-8669-407b-920d-427fa8b81328
16f5b686\x2d8669\x2d407b\x2d920d\x2d427fa8b81328
```
