### ISSUE TITLE
systemd-vmspawn: Support trimming for disk images

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#32024]
### Component

systemd-vmspawn

### Is your feature request related to a problem? Please describe

Long running VMs (#31283), using disk images, will over time consume more storage than what they really need, if the unused blocks are not discarded so the host can reuse the blocks.

This may result in a ton of wasted space.

### Describe the solution you'd like

A way to enable `discard=unmap` for the `-drive` option which is passed to QEMU.

It is worth noting, that it is not always desirable to enable the option, as mentioned when [it was introducted](https://wiki.qemu.org/ChangeLog/1.5):
> IDE and SCSI disks always have the ability to issue "discard" (aka TRIM or UNMAP) commands. However, by default "discard" commands are silently ignored as they can cause performance degradation and fragmentation. To enable them, the "-drive" option now supports a "discard" suboption; the default value is "ignore" (or its synonym "off"), and the other valid value is "unmap" (or "on").

### Describe alternatives you've considered

One option is using the `directory image` option (#31076), but using a image is sometimes more desirable (e.g. for experimenting with filesystems).

### The systemd version you checked that didn't have the feature you are asking for

255 (and git)

**Comment by poettering** [comment]
We trim by default when nspawn mounts disk images, hence yes, it makes sense to trim by default in vmspawn too
