### ISSUE TITLE
Failed resume does not clear HibernateLocation EFI variable

### ISSUE THREAD

**Issue by kleinph** [systemd/systemd#32021]
### systemd version the issue has been seen with

255.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.8.2-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Clearing resume state, so that after a failed resume from hibernate attempt no further failed ones occur.

### Unexpected behaviour you saw

I tried to hibernate with a Luks2 encrypted swap, which is not supported when only using gpt-auto detection according to #30557. 

So resume times out and fails with error:
> Timed out waiting for device /dev/disk/by-uuid/\<UUID-of-swap\>.

But the _HibernateLocation_ EFI variable is not cleared and after booting and rebooting, the time out and error appear again.

To stop the failing resume attempts the EFI varaible must be cleared manually as described in https://github.com/systemd/systemd/issues/30395#issuecomment-1852613917.

### Steps to reproduce the problem

- Hibernate with an unsupported setup (like Luks2 encrypted swap without crypttab).
- Resume from hibernation.
- Resume fails as expected
- Reboot
- Resume is attempted again and fails again. Not expected.

**Comment by YHNdnzj** [comment]
So apparently people encounter this at a much higher rate than I originally expected... Fix is waiting in #32043.
