### ISSUE TITLE
Daylight saving time switch causes CPU high

### ISSUE THREAD

**Issue by CPAltair** [systemd/systemd#32047]
### systemd version the issue has been seen with

249.11-0ubuntu3.9

### Used distribution

Ubuntu 22.04

### Linux kernel version used

6.5.0-1014-aws

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-journald, systemd-logind, systemd-udevd

### Expected behaviour you didn't see

because the host use Dublin timezone, When the time reaches 00:59:59, the next second will jump to 02:00:00, and resource usage will remain normal.

### Unexpected behaviour you saw

The CPU usage will suddenly increase to 100% starting from 00:00:00 and last for 1 hour, but return to normal at 02:00:00.
![screenshot-20240402-141930](https://github.com/systemd/systemd/assets/161670869/1c69ae43-e2a0-43b2-ac70-d0085d8cae32)
![screenshot-20240402-142051](https://github.com/systemd/systemd/assets/161670869/b2cb5b45-61f3-4993-814b-ff81a02d45b5)

And I saw  Failed to start Restart atop daemon to rotate logs
![screenshot-20240402-142437](https://github.com/systemd/systemd/assets/161670869/36e90329-ae58-487f-a617-638a09129a33)

$ cat /lib/systemd/system/atop-rotate.service
[Unit]
Description=Restart atop daemon to rotate logs

[Service]
**Type=oneshot**
ExecStart=/bin/systemctl try-restart atop.service

**Many logs are refreshed in the same second “Failed to start Restart atop daemon to rotate logs”**

$ systemctl status atop-rotate.service 
× atop-rotate.service - Restart atop daemon to rotate logs
     Loaded: loaded (/lib/systemd/system/atop-rotate.service; static)
     Active: failed (Result: start-limit-hit) since Sun 2024-03-31 00:17:01 GMT; 2 days ago
**TriggeredBy: ● atop-rotate.timer**
    Process: 158473 ExecStart=/bin/systemctl try-restart atop.service (code=exited, status=0/SUCCESS)
   Main PID: 158473 (code=exited, status=0/SUCCESS)
        CPU: 6ms

Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.
Mar 31 00:17:02 xxxx systemd[1]: Failed to start Restart atop daemon to rotate logs.

### Steps to reproduce the problem

1. Stop clock synchronization 
`systemctl stop chrony`

2. Set the timezone to Dublin
`timedatectl set-timezone Europe/Dublin`

3. Change the time to waitting for Daylight saving time switch
`timedatectl set-time "2024-03-30 23:59:50"`

**Comment by yuwata** [comment]
Interesting. But v249 is too old here. Please try to reproduce the issue with a recent release or the current git HEAD. Sorry, but closing.

**Comment by volkalexey** [comment]
I saw this issue on March 30, 2025 with systemd v257.4 on Arch Linux, the same Europe/Dublin timezone.
Behavior is identical to that in issue description.

**Comment by FederAndInk** [comment]
Hi,

I am having a similar issue with time jumps, the more in the future it goes, the more time systemd will hang

When we try going 25 years into the future, systemd will hang for around 25minutes, unable to process requests (systemctl, tty, timers, socket, ...).

with systemd v257.5
