### ISSUE TITLE
CI build coverage for examples embedded in documentation is missing

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#32054]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Just to keep track of @evverx's findings here:

https://github.com/systemd/systemd/pull/32030#issuecomment-2032540493

This really should be addressed.

### Unexpected behaviour you saw

see above

### Steps to reproduce the problem

see above

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
foo
```

**Comment by poettering** [comment]
The right fix for this issue is probably not just to fix the example, but to test-build all examples we ship as part of CI

**Comment by evverx** [comment]
```
gcc -std=c99 ./man/notify-selfcontained-example.c
```

**Comment by evverx** [comment]
> The right fix for this issue is probably not just to fix the example, but to test-build all examples we ship as part of CI

Agreed. As far as I know currently the headers are compiled but I'm not sure what's going on with the examples. To judge from https://github.com/systemd/systemd/pull/32030#issuecomment-2032081759 at least some examples should be compiled as far as I understand but that's something @mrc0mmand probably knows better.

**Comment by yuwata** [comment]
I am working on this.

**Comment by yuwata** [comment]
BTW, should the test code built with -std=gnu11, which is our default? Or, -std=c99 or something non-gnu standard?

**Comment by evverx** [comment]
As far as I can see at least the headers are compiled with all sorts of standards
```sh
src/systemd/meson.build:        foreach opt : ['-std=c++14',
src/systemd/meson.build:                       '-std=c++17',
src/systemd/meson.build:                       '-std=c++20',
src/systemd/meson.build:                       '-std=c++23',
src/systemd/meson.build:                       '-std=c++26',
```
because they can be embedded in all sorts of things. The example is supposed to be copy-pastable too so it should probably be compiled with `-std=c*`. (I just copy-pasted the example to a build system where it failed to compile spectacularly)

**Comment by yuwata** [comment]
WIP branch -> #32057.

**Comment by bluca** [comment]
Turns out man/notify-selfcontained-example.c did compile on all tested combinations without changes, hence retitling accordingly

**Comment by evverx** [comment]
It doesn't. Without `-D_GNU_SOURCE` it isn't exactly self-contained. That being sad I poked it and it's useless because `sd_notify` usually comes with `sd_listen` and it's necessary to look at libsystemd anyway.
