### ISSUE TITLE
Support `journalctl --since 1h`

### ISSUE THREAD

**Issue by guettli** [systemd/systemd#32051]
### Component

journalctl

### Is your feature request related to a problem? Please describe

I want to see only the logs which got created during the last hour.

### Describe the solution you'd like

I love to have this:

```
journalctl --since 1h 
```

But it fails up to now:

```
root@b40aa6bb66c0:/# journalctl --since 1h
Failed to parse timestamp: 1h
```

I used this (via ubuntu:24.04 then `apt update; apt install systemd`)

```
root@b40aa6bb66c0:/# journalctl --version
systemd 255 (255.2-3ubuntu2)journalctl --since 1h
```

### Describe alternatives you've considered

This seems to work, too.

But this needs additional quoting characters which are not convenient to type:

```
journalctl --since "-1 hour"
```

---

Additional: The message "Failed to parse timestamp" is a bit short. It would be nice if the tool would provide a hint which format is supported.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
hmm? what's wrong with `journalctl --with=-1h`? short, clear, no quotes, nothing?

**Comment by mrc0mmand** [comment]
> hmm? what's wrong with `journalctl --with=-1h`? short, clear, no quotes, nothing?

Yeah, the long options come with the equal sign exactly for such cases where the value starts with a dash. So this should all already work as expected.

**Comment by mrc0mmand** [comment]
> It would be nice if the tool would provide a hint which format is supported.

The `journalctl(1)` man page hints at what format is supported and that it is documented in `systemd.time(7)`.

**Comment by poettering** [comment]
I am tempted to just close this, as the help texts, and the an page all spell this out as `--since=` rather than `--since`, hence the docs already lead you to the right way to write the switches.

**Comment by guettli** [comment]
> hmm? what's wrong with `journalctl --with=-1h`? short, clear, no quotes, nothing?

❯ LANG=C journalctl --with=-1h
journalctl: unrecognized option '--with=-1h'

---

I am a human, and for me ` journalctl --since=1h` feels right. If this gives me the output "Failed to parse timestamp: 1h" then I don't think "-1h" is failed. I did not try that.

**Comment by yuwata** [comment]
Or, `--since '1 hour ago'` should work for you.

**Comment by mrc0mmand** [comment]
> > hmm? what's wrong with `journalctl --with=-1h`? short, clear, no quotes, nothing?
> 
> ❯ LANG=C journalctl --with=-1h journalctl: unrecognized option '--with=-1h'
> 
> I am a human, and for me ` journalctl --since=1h` feels right. If this gives me the output "Failed to parse timestamp: 1h" then I don't think "-1h" is valid. I did not try that.

That was a typo, it should be `--since=-1h` of course. Or, as Yu said, `--since '1 hour ago` works as well. Please refer to the menitoned `systemd.time` man page where all this is pretty well documented.
