### ISSUE TITLE
systemd.timer man page

### ISSUE THREAD

**Issue by eatdust** [systemd/systemd#3208]
### Submission type
- [ ] Bug report
- [X ] Request for enhancement (RFE)

Hi there,
after reading ten times the systemd.timer man page, I am concluding that there is not enough information in there to understand all of its subtleties and use it properly.
[mode useless complain on]
As a general complain against systemd, I think you guys should lean how to write man pages [in addition to rewrite from scratch journald ;)]
[mode useless complain off]

How all the OnActiveSec= OnBootSec= options behave under a resuming after a suspend?
If I am reverse engineering and crosschecking with ten of tests done, nothing happens on monotonic timers, meaning the clock get frozen and the timer starts from its previous frozen state.

First of all, I think, if correct, that's an important information to appear in the man page. Second, if correct, then OnResumeSec= is crucially missing!!!

Thanks for considering it guys!
Cheers,
Chris.

**Comment by poettering** [comment]
I think you guy should learn how to write issues without insulting the very people you'd like an answer from. A good attitude generally helps if you want quick and useful answers.

As to your question, the man page says pretty explicitly, in the documentation for `OnActiveSec=` and `OnBootSec=`, if I may quote:

> These are monotonic timers, independent of wall-clock time and timezones. If the computer is temporarily suspended, the monotonic clock stops too.

I think this is pretty clear, isn't it?

And if you want timers that don't stop during system suspend and can resume the system, then use `WakeSystem=` for that.

Closing, as there's nothing to fix here.

**Comment by dmedri** [comment]
@eatdust you could find a collection of timers examples here:
https://github.com/dmedri/enterprise-timers
New examples -- with the cited options -- are welcome. Please, make PR.

**Comment by eatdust** [comment]
Thanks for giving me back your set of critics too! No it is not clear, otherwise I would not have posted it here right?

Ok, then I am giving you more details to what I need:
1) monotonic timers triggering a service, let's say every 30mn
2) I want it to go frozen when the machine (phone) is suspended (battery!) So forget about OnCalendar= and WakeSystem=
3) I want the service to be triggered a few seconds, let's say 10s, after the phone is resumed AND 30mn of monotonic after the last activation

Now, tell me in the superb man page where any of this could be guessed? As far as I understand (and again, systemd manpages are usually not clear enough), that's impossible.
Unless a resume also triggers a  OnStartupSec=, but that's not my impression and it is even not mentioned what is "a startup" of systemd. Does it include a resume for hibernation, just the first boot? So no, mister, the behaviour of the timers during suspend/resume does not boil down to 2 lines in the man page.

cheers.

PS: they were not insults by the way, but facts from users of systemd, even if you don't like them...

**Comment by poettering** [comment]
Ok, so you want to use the resume event as starting point for a timer? Given how you criticize us for our documentation skills, I find your skills of asking questions pretty unconvincing...

The man page is a reference manual, it documents the feature set available. It's not supposed to a HOWTO covering any usecase people might have. 

Questions like yours really don't belong in the issue tracker, that's for bugs and RFEs, and this is neither; please direct questions like yours to our mailing list, which is where we deal with such support questions. The issue submission template and contributor guidelines linked from the form should really make this clear...

Anyway, to answer your question: systemd currently does not know a concept of timers that are started at resume time, and I am not sure it really should. That said, you can easily implement this, by writing a timer unit that uses OnActiveSec= and then start that timer unit whenever the system comes back from a suspend and stop it when beofre it goes to sleep. You can use the /usr/lib/systemd/system-sleep/ drop-in directory for issuing the start/stop requests for this.

**Comment by eatdust** [comment]
Thank you for your answer, that's indeed a useful one. I don't know i too much about systemd competencies, but I think it could be useful. Systemd being already in charge of suspending the system on idle, that would be very convenient to have this OnResumeSec, or whatever events on systemd happening after resume.

In fact I thought I have filled a RFE, which apparently I did not, so that is my fault..
Concerning my way to ask questions, point taken... But, with 24h of restfull night, you may understand that simply adding careful wordings in the man may spare a lot of time to _average_ people (like me) searching and testing for nothing, without being a HOWTO of course. Anyway, thanks for the time taken to answer my no-very well formulated complain.

Cheers.
