### ISSUE TITLE
recursive freezing of units whith currently unrealized cgroups needs some clean-ups

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#32122]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

See my comments here:

https://github.com/systemd/systemd/pull/32009#issuecomment-2040312082

This is just a tracker bug, so that we don#t forget to address this eventually.

@AdrianVovk

**Comment by AdrianVovk** [comment]
Sounds good to me. I'll take care of it when I'm back from vacation, after the 14th
