### ISSUE TITLE
journald: downgrade "Unused data (entry_offset == 0)" message to LOG_DEBUG

### ISSUE THREAD

**Issue by FabienRCT** [systemd/systemd#32153]
### systemd version the issue has been seen with

255.4-2

### Used distribution

archlinux

### Linux kernel version used

6.8.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Unexpected behaviour you saw

After each boot, some new journal files are made that failed the verification with `journalctl --verify` with error "...: Unused data (entry_offset==0) ". It's not clear if the data in these files are completely useless, but a `journalctl --vacuum-time 100` delete all of them even when they are younger than 100 days old. And it takes a lot of space for useless data if you reboot the system often.

### Steps to reproduce the problem

Reboot the system and run  `journalctl --verify`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# journalctl --verify
23bc98: Unused data (entry_offset==0)                                                                                                              
23bd00: Unused data (entry_offset==0)                                                                                                              
23bd60: Unused data (entry_offset==0)                                                                                                              
23bdc0: Unused data (entry_offset==0)                                                                                                              
23beb0: Unused data (entry_offset==0)                                                                                                              
PASS: /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@fdcfc803ee5844909a11b1bab276651e-000000000002c612-000615936388a297.journal          
21d810: Unused data (entry_offset==0)                                                                                                              
21d860: Unused data (entry_offset==0)                                                                                                              
21d8b0: Unused data (entry_offset==0)                                                                                                              
21d928: Unused data (entry_offset==0)                                                                                                              
PASS: /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/user-1000@fdcfc803ee5844909a11b1bab276651e-000000000002c611-000615936387a387.journal       
PASS: /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/user-1000.journal                                                                          
PASS: /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@b15c6c7c95074121b5ed6edb7c1cf2a0-000000000002c6e8-000615936d35716f.journal          
PASS: /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system.journal

# journalctl --vacuum-time 100
Vacuuming done, freed 0B of archived journals from /run/log/journal.
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/user-1000@fdcfc803ee5844909a11b1bab276651e-000000000002c611-000615936387a387.journal (2.1M).
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@fdcfc803ee5844909a11b1bab276651e-000000000002c612-000615936388a297.journal (2.2M).
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@b15c6c7c95074121b5ed6edb7c1cf2a0-000000000002c6e8-000615936d35716f.journal (2.4M).
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/user-1000@b15c6c7c95074121b5ed6edb7c1cf2a0-000000000002ca42-000615936f3cc692.journal (2.1M).
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@b15c6c7c95074121b5ed6edb7c1cf2a0-000000000002ca43-000615936f3df1b8.journal (2.2M).
Deleted archived journal /var/log/journal/c42af750a4a64b2cac4c939781b6bafa/system@788985a74ebb4aeeb0d0b367cc31f36f-000000000002cb11-00061593799a05f3.journal (2.5M).
Vacuuming done, freed 13.7M of archived journals from /var/log/journal/c42af750a4a64b2cac4c939781b6bafa.
Vacuuming done, freed 0B of archived journals from /var/log/journal.
```

**Comment by farblos** [comment]
Same here on systemd version 255.4-1 on Debian testing.  Also running on a system that gets rebooted daily.

However, in contrast to the bug report I wouldn't go as far as to say that "the verfication failed" for these journal files or that they got corrupted.  After all, on my system the call to `journalctl --verify` succeeds with a positive overall outcome (== exit value zero):

```
[~]$ journalctl --verify 2>&1 | head -5 
47d2d8: Unused data (entry_offset==0)
47d340: Unused data (entry_offset==0)
47d450: Unused data (entry_offset==0)
47d4c8: Unused data (entry_offset==0)
PASS: /var/log/journal/e9a7104c5a904888af3f7971a1a82f6c/system@e7b97b9c52e44f53acca37ed6fb57a32-000000000017126b-000615917ad5cdd1.journal

[~]$ journalctl --verify 2>/dev/null && echo OK
OK
```

So it could be that these "unused data" messages are probably only warnings that better shouldn't be written.

Regarding the "lot of space for useless data", @FabienRCT, you probably may want to have a look at my false issue #32248.  It may or may not apply to your particular case as well.

**Comment by poettering** [comment]
we should really suppress these messages i guess. 

What happens is this: we append a structured log message to the journal. it consists of various data fields, which we add first, if they haven't been seen before. Finally, we write the entry record that actually glues the whole thing together to become a log entry.

But if the size limit is hit while we have written a data field, but before we write the entry then the data field will be there, not referened by anything then.

This is really not a problem, it's simply how appending works in combination with size management.

We should really downgrade this message to DEBUG I guess.

**Comment by FabienRCT** [comment]
> we should really suppress these messages i guess.
> 
> What happens is this: we append a structured log message to the journal. it consists of various data fields, which we add first, if they haven't been seen before. Finally, we write the entry record that actually glues the whole thing together to become a log entry.
> 
> But if the size limit is hit while we have written a data field, but before we write the entry then the data field will be there, not referened by anything then.
> 
> This is really not a problem, it's simply how appending works in combination with size management.
> 
> We should really downgrade this message to DEBUG I guess.

It is still not clear if those files that multiplies, seemingly taking way more disk space at each boot that their useful content should and get always deleted with a --vacuum command, really contain useful data. Maybe the "Unused data" message are not a bug, but "empty" log files growing bigger at each boot regardless of their content definitely is.

**Comment by farblos** [comment]
@FabienRCT: I'm not related to the systemd project, but I have been trying to optimize my journals as well during the last couple of weeks, so maybe I can help ... unless of course the "moderators" here frown upon such discussions in issues.

It is not quite clear to me what you object to:

- The number of journal files or
- their size or
- their "emptiness" (meaning that they seem to contain mostly zeroes or other "useless" data) or
- that they do not get cleaned up automatically (so you have to vacuum manually).

Depending on what it is I can think of the following options:

- If it's about their emptiness/filling level, please ensure to look at the journal files not with a plain `ls -l`, but with some other means (`journal-ctl --disk-usage --file ...`, `du`, `stat`, `ls -s`).  Chances are that the file size displayed by `ls -l` shows a bigger value than the files actually allocate on file system.

- If we're talking about their number, size, or age, you can configure automatic clean-up with `SystemMaxFiles=`, `SystemMaxUse=`, `MaxRetentionSec=`, respectively. And a bunch of other options.

- Finally, if you are on a single-user system, you might want to configure `SplitMode=none` to collect log entries of all users in the system journal files.  This would reduce the number of journal files and at the same time increase their (perceived) filling level.
