### ISSUE TITLE
systemd-xdg-autostart-generator does not correctly quote paths for `ExecStart=`

### ISSUE THREAD

**Issue by guss77** [systemd/systemd#32173]
### systemd version the issue has been seen with

249

### Used distribution

KDE Neon

### Linux kernel version used

6.5.0-26-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-xdg-autostart-generator

### Expected behaviour you didn't see

When systemd-xdg-autostart-generator is run with a Desktop Entry file that has a correctly quoted `Exec` line containing reserved characters (for example - space), the resulting autostart unit should have its `ExecStart=` value quoted to allow it to run.

### Unexpected behaviour you saw

When systemd-xdg-autostart-generator is run with a Desktop Entry file that has a correctly quoted `Exec` line containing reserved characters (for example - space), the resulting autostart unit has its `ExecStart=` value unquoted causing spaces in the executable file name to be interpreted as argument separators.

### Steps to reproduce the problem

1. Create an executable with a space in its file name. For example, I created `~/.local/bin/test with space.sh` as a bash script that just runs `true`.
2. Create an autostart Desktop Entry file, for example `~/.config/autostart/test-autostart.desktop` with correctly quoted `Exec=` setting:

```
[Desktop Entry]
Name=Testing Autostart
Exec="/home/odeda/.local/bin/test with space.sh"
Comment=Not this is just a test
Hidden=false
Type=Application
```

3. Run `systemd-xdg-autostart-generator`
4. Run `systemctl --user daemon-reload`
5. Run `systemctl cat --user app-test\\x2dautostart@autostart.service` - observe that the `ExecStart=` is not quoted correctly.
6. Run `systemctl start --user app-test\\x2dautostart@autostart.service` - observe an error message saying "... failed because the control process exited with error code."
7. Run `systemctl status --user app-test\\x2dautostart@autostart.service` - see below for the output on my system.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
× app-test\x2dautostart@autostart.service - Testing Autostart
     Loaded: loaded (/home/odeda/.config/autostart/test-autostart.desktop; generated)
     Active: failed (Result: exit-code) since Tue 2024-04-09 12:55:11 IDT; 43s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 2716395 ExecStart=/home/odeda/.local/bin/test with space.sh (code=exited, status=203/EXEC)
   Main PID: 2716395 (code=exited, status=203/EXEC)
        CPU: 1ms

Apr 09 12:55:11 vesho systemd[3792]: Starting Testing Autostart...
Apr 09 12:55:11 vesho systemd[2716395]: app-test\x2dautostart@autostart.service: Failed to locate executable /home/odeda/.local/bin/test: No such file or directory
Apr 09 12:55:11 vesho systemd[2716395]: app-test\x2dautostart@autostart.service: Failed at step EXEC spawning /home/odeda/.local/bin/test: No such file or directory
Apr 09 12:55:11 vesho systemd[3792]: app-test\x2dautostart@autostart.service: Main process exited, code=exited, status=203/EXEC
Apr 09 12:55:11 vesho systemd[3792]: app-test\x2dautostart@autostart.service: Failed with result 'exit-code'.
Apr 09 12:55:11 vesho systemd[3792]: Failed to start Testing Autostart.
```

**Comment by YHNdnzj** [comment]
Sorry, but this is the upstream bug tracker for systemd, and we only support the latest two versions here, namely v254 and v255. Anything older than that should be reported to distro bugtracker.

Also, this is already fixed by https://github.com/systemd/systemd/pull/22854.
