### ISSUE TITLE
RFE: allow creating new unit files with "systemctl edit"

### ISSUE THREAD

**Issue by faddat** [systemd/systemd#3218]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

229

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

debian

> …

Okay, here goes!  So there's a set template for a new unit

```
[Unit]
Description=Foo

[Service]
ExecStart=/usr/sbin/foo-daemon

[Install]
WantedBy=multi-user.target
```

Wouldn't it be great if systemctl was able to pop one down for the user?  Functionality:

```
systemctl create caddy  
```

.....creates

caddy.service, which reads:

```
[Unit]
Description=Foo

[Service]
ExecStart=/usr/sbin/foo-daemon

[Install]
WantedBy=multi-user.target
```

It's also possible that caddy.service could contain a brief primer on the making of unit files.  This way, users will not begin by googling how to write a unit :).

**Comment by poettering** [comment]
There's a TODO list item since a while to permit creating new unit files with "systemctl edit". I think that would cover it quite nicely.

**Comment by faddat** [comment]
Covers it perfectly.  Is it just a matter of making a template that opens
when a user chooses to edit a file that doesn't yet exist, or...?

If so, happy to put one together.... I've been setting up servers lately
and it has led me to become a devoted convert to the unchurch of systemd :)!

**Comment by poettering** [comment]
@faddat well, I think using "systemctl edit" on a file that doesn't exist should probably continue to be an error, but the error message should say "in order to create a new file, retry with systemctl edit --new" or so...

**Comment by keszybz** [comment]
`systemctl edit --force` is implemented now. If further enhancements are needed, please open a new issue.
