### ISSUE TITLE
respect ".uname" section in ESP/loader/addons/*.addon.efi 

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#32183]
### Component

systemd-stub

### Is your feature request related to a problem? Please describe

`ESP/loader/addons/*.addon.efi` addons are picked up even if they contain a `.uname` section not relevant to the current booting kernel.

### Describe the solution you'd like

From the man page, concerning addons in `foo.efi.extra.d/*.addon.efi` :

> Additionally, if the both the addon and the UKI contain a a ".uname" section, the addon will be rejected if they do not match exactly.

Why is the same behavior not used for addons in `ESP/loader/addons/` ?

### Describe alternatives you've considered

Only using `foo.efi.extra.d/*.addon.efi` for UKI specific things. Not really convenient.

### The systemd version you checked that didn't have the feature you are asking for

255.4-2

**Comment by poettering** [comment]
Fixed by 2f49ed9a01014f9704409edb70f217d3fa94e383
