### ISSUE TITLE
IOAccounting for network devices

### ISSUE THREAD

**Issue by clusterfons** [systemd/systemd#32184]
### Component

systemd

### Is your feature request related to a problem? Please describe

Currently there is no easy way to limit a single user in their network IO. For example: on a shared system where /home is mounted over NFS, a single user can saturate the shared connection and slow down /home access for everyone. It would be really nice if it were possible to configure per-user limits for networking, much like the already configurable limits for CPU and memory through user-.slice, using cgroups.

### Describe the solution you'd like

Config like this in user-.slice.d/*.conf:

NetIOAccounting=true
NetIOLimit=eno1 100M

To limit every individual user to a certain bandwidth on the specified network interface

### Describe alternatives you've considered

Using net_cls together with tc might be able to get something like this done, but that will not be like the easy setup provided by systemd user-.slice

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
I am pretty sure NFS traffic is not accounted to users on Linux. Hence sorry, but I don't think we can implement what you are asking for. Please ask the NFS kernel folks for this. If you convince them (good luck!) then we can hook this up.

**Comment by poettering** [comment]
Closing, since this is not actionable to use. Please convince kernel folks to add such accounting, and we can expose it. But without it, sorry, no can do.
