### ISSUE TITLE
`start-limit-hit` not possible as status result

### ISSUE THREAD

**Issue by hellow554** [systemd/systemd#32203]
### systemd version the issue has been seen with

256 (latest main)

### Used distribution

Ubuntu 23.10

### Linux kernel version used

5.15.146.1-microsoft-standard-WSL2

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

According to [the docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#$SERVICE_RESULT) `$SERVICE_RESULT` contains the result for a service passed to a `ExecStopPost` script.
I always see `exit-code`, although the limit was reached.

I managed to observe the result somewhat.

https://github.com/systemd/systemd/blob/5538b62f59f126d5a1761697417ff5cd7e2c77b1/src/core/service.c#L4929-L4933

These lines are triggered correctly and [`service_enter_dead`](https://github.com/systemd/systemd/blob/5538b62f59f126d5a1761697417ff5cd7e2c77b1/src/core/service.c#L1963) is called with the correct error code `SERVICE_FAILURE_START_LIMIT_HIT`.
The problem is, that in `service_enter_dead` the `f` variable is never used and therefore the correct result will never be set.

### Unexpected behaviour you saw

```
systemd[1]: Failed to start foo.service - FooBar Service.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Start request repeated too quickly.
systemd[1]: Stopped foo.service - FooBar Service.
systemd[1]: foo.service: Scheduled restart job, restart counter is at 5.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Started foo.service - FooBar Service.
systemd[1]: Stopped foo.service - FooBar Service.
systemd[1]: foo.service: Scheduled restart job, restart counter is at 4.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Started foo.service - FooBar Service.
systemd[1]: Stopped foo.service - FooBar Service.
systemd[1]: foo.service: Scheduled restart job, restart counter is at 3.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Started foo.service - FooBar Service.
systemd[1]: Stopped foo.service - FooBar Service.
systemd[1]: foo.service: Scheduled restart job, restart counter is at 2.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Started foo.service - FooBar Service.
systemd[1]: Stopped foo.service - FooBar Service.
systemd[1]: foo.service: Scheduled restart job, restart counter is at 1.
systemd[1]: foo.service: Failed with result 'exit-code'.
systemd[1]: foo.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Started foo.service - FooBar Service.
```

### Steps to reproduce the problem

Use the following service file

```
[Unit]
Description=FooBar Service
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
ExecStart=/usr/bin/false
Restart=on-failure
RestartSec=2
```

and start it via `systemctl start foo`.

What I would expect to happen is (only the last start)

```
Failed to start foo.service - FooBar Service.
foo.service: Failed with result 'exit-code'.
foo.service: Start request repeated too quickly.
Stopped foo.service - FooBar Service.
foo.service: Scheduled restart job, restart counter is at 5.
foo.service: Failed with result 'start-limit-hit'.
foo.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by YHNdnzj** [comment]
>  The problem is, that in service_enter_dead the f variable is never used and therefore the correct result will never be set.

Hmm? It's clearly used?

What's happening here is that we record the last exit status in `s->result`. So when a restart job gets to run and `unit_start` -> `service_can_start` is called, `s->result` already contains the previous  `exit-code` exit status, and that doesn't get overridden.

I personally like the current behavior more. I.e. you always get the "real" failure instead of something that come later as a side effect. Therefore I won't deem it as a bug. But some might, and if that's the case maybe we can change it, dunno.

**Comment by hellow554** [comment]
Hey @YHNdnzj 
Of course you're right and it is used but only in one line.
What I (and many other according to some open issues) want it to detect whether a job has hit the limit and I thought just observing the `$SERVICE_RESULT` env variable would be sufficient, but it is not.
Does that make sense to you?

**Comment by YHNdnzj** [comment]
> detect whether a job has hit the limit and I thought just observing the $SERVICE_RESULT env variable 

I don't understand how this would actually work? If the job limit is hit, the service goes straight to `dead` state. Nothing in between can observe that?

**Comment by hellow554** [comment]
I'm no expert by any means, but I thought `ExecStopPost` would be called with `$SERVICE_RESULT` set to `start-limit-hit`. That way I could detect and react to it.
Isn't it like this?

**Comment by YHNdnzj** [comment]
Nope. When start limit is hit we suppress spawning anything for the unit.

**Comment by hellow554** [comment]
Well... That's a bummer, but thanks for the clarification.
Then I need a different approach to detecting that :/

Thanks for your help...

**Comment by hellow554** [comment]
For anyone stumbling over this:

At least `OnFailure=` is triggered. There you can do something along:

```
# systemctl cat repair-foo
# /etc/systemd/system/repair-foo.service
[Unit]
Description=LKJALSKDJ

[Service]
ExecStart=/opt/repair.sh
```

```
# cat /opt/repair.sh
systemctl show -p StartLimitBurst -p NRestarts foo
```

which gives me:

```
NRestarts=5
StartLimitBurst=5
```

which then I know, that the limit has been reached.
