### ISSUE TITLE
Broken link to non-deprecated Inhibitor Locks documentation page

### ISSUE THREAD

**Issue by jpetso** [systemd/systemd#32209]
### systemd version the issue has been seen with

255

### Used distribution

www.freedesktop.org

### CPU architectures issue was seen on

None

### Component

systemd-logind

### Expected behaviour you didn't see

The official docs for the [org.freedesktop.login1 D-Bus interface](https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.login1.html) link to https://www.freedesktop.org/wiki/Software/systemd/inhibit in a number of places. Example:

> For more information see [Inhibitor Locks](https://www.freedesktop.org/wiki/Software/systemd/inhibit).

On the linked page, there is a prominent banner:

> This page has been obsoleted and replaced: https://systemd.io/devdocs/INHIBITOR_LOCKS.html.

The web page behind the INHIBITOR_LOCKS.html link should exist. Furthermore, the docs for org.freedesktop.login1 should not link to a deprecated page in the first place.

### Unexpected behaviour you saw

The docs for org.freedesktop.login1 link to a page that's marked as deprecated. The supposedly non-deprecated INHIBITOR_LOCKS.html link points to a 404 Not Found page.

**Comment by poettering** [comment]
Fixed by 5507480cf44a47bab401a9477ba783ac528bb4e9
