### ISSUE TITLE
some sysext review points need addressing

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#32217]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Just a tracker for the post-merge review points listed here:

https://github.com/systemd/systemd/pull/31801#pullrequestreview-1993682430

**Comment by krnowak** [comment]
Thanks, will get at it. There is already one PR for sysext here, so I'll update this one to address your review issues: https://github.com/systemd/systemd/pull/31987.
