### ISSUE TITLE
 /run/systemd/tpm2-pcr-signature.json and /run/systemd/tpm2-pcr-public-key.pem are not created when booting a UKI

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#32232]
### systemd version the issue has been seen with

255.4-2

### Used distribution

Arch

### Linux kernel version used

6.8.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub

### Expected behaviour you didn't see

From man/systemd-stub:

> When ".pcrsig" and/or ".pcrpkey" sections are present in a unified kernel image their contents are passed to the booted kernel in an synthetic initrd cpio archive that places them in the /.extra/tpm2-pcr-signature.json and /.extra/tpm2-pcr-public-key.pem files. Typically, a [tmpfiles.d(5)](https://man.archlinux.org/man/tmpfiles.d.5.en) line then ensures they are copied into /run/systemd/tpm2-pcr-signature.json and /run/systemd/tpm2-pcr-public-key.pem where they remain accessible even after the system transitions out of the initrd environment into the host file system. Tools such [systemd-cryptsetup@.service(8)](https://man.archlinux.org/man/systemd-cryptsetup@.service.8.en), [systemd-cryptenroll(1)](https://man.archlinux.org/man/systemd-cryptenroll.1.en) and [systemd-creds(1)](https://man.archlinux.org/man/systemd-creds.1.en) will automatically use files present under these paths to unlock protected resources (encrypted storage or credentials) or bind encryption to booted kernels.

The booted UKI does contain the .pcrsig and .pcrkpkey section:
```
# ukify inspect /efi/EFI/Linux/<...>-6.8.4-arch1-1.efi 
.sbat:
<...>
.osrel:
<...>
.cmdline:
<...>
.uname:
<...>
.splash:
<...>
.pcrpkey:
<...>
.initrd:
<...>
.pcrsig:
<...>
.linux:
<...>
```

### Unexpected behaviour you saw

With existing `/etc/systemd/tpm2-pcr-public-key.pem` which is automatically picked up:
```
# echo -n hunter2 | systemd-creds encrypt - password.cred
# systemd-creds decrypt password.cred
Failed to unseal secret using TPM2: No such device or address
# nano pcrsig.json <-- enter data from .pcrsig section of ukify inspect output
# systemd-creds --tpm2-signature=pcrsig.json  decrypt password.cred
hunter2
```
```
# ls /run/systemd/tpm2*
/run/systemd/tpm2-srk-public-key.pem  /run/systemd/tpm2-srk-public-key.tpm2b_public
```

**Comment by dylanjan313** [comment]
If using Fedora, the dracut's systemd module [adds](https://github.com/dracutdevs/dracut/blob/bee1c4824a8cd47ce6c01892a548bdc07b1fa678/modules.d/00systemd/module-setup.sh#L131) the `/usr/lib/tmpfiles.d/systemd.conf` file in the initrd.
Searching for it in the initrd:
```bash
dylan@fedora:~$ sudo objcopy -O binary --only-section=.initrd /path/to/uki.efi initrd.img
dylan@fedora:~$ lsinitrd initrd.img | grep "tmpfiles.d/systemd.conf"
-rw-r--r--   1 root     root         2289 Nov 16 01:00 usr/lib/tmpfiles.d/systemd.conf
[dylan@arch ~]$ 
```
As a result, these two files (.json and .pem) are found in `/run/systemd/` once the boot is completed, as expected.

If using Arch Linux, the mkinitcpio's [systemd hook](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/blob/master/install/systemd) does not import the required files.
As a result, the file is not found in the initrd:
```
[dylan@arch ~]$ objcopy -O binary --only-section=.initrd /path/to/uki.efi initrd.img
[dylan@arch ~]$ lsinitcpio initrd.img | grep "tmpfiles.d/systemd.conf"
[dylan@arch ~]$ 
```

It looks like an issue for https://gitlab.archlinux.org/archlinux/mkinitcpio

**Comment by poettering** [comment]
OK, let's close this then, seems to be an arch initrd issue. Close.
