### ISSUE TITLE
Journal file truncation does not seem to work

### ISSUE THREAD

**Issue by farblos** [systemd/systemd#32248]
### systemd version the issue has been seen with

255.4-1

### Used distribution

Debian testing

### Linux kernel version used

6.6.15-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

Mostly because of the fix for RFE #17613 I expect to see journal files that are smaller than 8MiB.  

### Unexpected behaviour you saw

However, on my laptop with daily reboots and all default `journald.conf` I can see that all 100 journal files have size 8MiB:

```
[e9a7104c5a904888af3f7971a1a82f6c]$ cd /var/log/journal/e9a7104c5a904888af3f7971a1a82f6c

[e9a7104c5a904888af3f7971a1a82f6c]$ ls -lS | head -2
total 422776
-rw-r-----+ 1 root systemd-journal 8388608 Apr 12 14:43 system.journal
ls: write error: Broken pipe

[e9a7104c5a904888af3f7971a1a82f6c]$ ls -lS | tail -2
-rw-r-----+ 1 root systemd-journal 8388608 Apr 11 10:22 user-2001@f3a00aaa97df4a86a6bc433f8fedb56a-0000000000172de5-000615b9e04c1f71.journal
-rw-r-----+ 1 root systemd-journal 8388608 Mar 22 20:56 user-2001@f741e33bcd2d49a1a948040ffda91d56-0000000000167f3c-0006143ca30d60d8.journal
```

I first thought that this might be because journal files that get archived due to rotation during reboot would *not* be truncated, but in fact even an explicit `journalctl --rotate` does not seem to truncate the rotated, archived journal file.

### Steps to reproduce the problem

Ensure that the current journal files are equal to 8MiB in size, for example, by rotating them.  Then execute `journalctl --user --rotate` and observe that the newly archived journal files also have size 8MiB.

### Background

This was all triggered because I wanted to have a bit more than approx. one month of journal on my laptop.  It took me some reading to understand that, because of the relatively frequent reboots and rotations, I actually hit the 100 `SystemMaxFiles=` limit.

To see how sparse these journal files are, I followed the example of vcaputo from #17613 and inspected the `tail_object_offset` header field of my journal files (at offset 0x88 == 136, I hope), with the following:

```
ls /var/log/journal/e9a7104c5a904888af3f7971a1a82f6c/* |
while read journal; do od -An -t dL -j 136 -N 8 $journal; done
```

From that I get a mean tail object offset of 4200789, meaning (?) that half the disk space used by the journal files is wasted.

**Comment by vcaputo** [comment]
Add '-s' to your ls to show the allocated size of the files, or use `stat` to query it.  The st_size member doesn't account for sparseness...
