### ISSUE TITLE
systemd-stub: skip systemd-boot-random-seed

### ISSUE THREAD

**Issue by rupansh** [systemd/systemd#32265]
### Component

bootctl

### Is your feature request related to a problem? Please describe

I am using UKI on Arch Linux with systemd-stub, to optimize my boot times. Unfortunately, `systemd-boot-random-seed` is running on every boot and writing to `/boot/loader/random-seed`, which increases my boot time
`# systemd-analyze critical-chain`:
```
graphical.target @4.447s
└─multi-user.target @4.447s
  └─libvirtd.service @4.404s +42ms
    └─network.target @4.388s
      └─NetworkManager.service @3.750s +637ms
        └─basic.target @3.749s
          └─dbus-broker.service @3.726s +22ms
            └─dbus.socket @3.723s
              └─sysinit.target @3.722s
                └─systemd-boot-random-seed.service @2.771s +950ms
                  └─local-fs.target @2.722s
                    └─boot.mount @3.701s +11ms
                      └─systemd-fsck@dev-disk-by\x2duuid-6CE1\x2dB8BB.service @2.784s +31ms
                        └─dev-disk-by\x2duuid-6CE1\x2dB8BB.device @2.000s
```

### Describe the solution you'd like

Some way to skip running `systemd-boot-random-seed.service` with systemd-stub (other than masking)

### Describe alternatives you've considered

Masking the service

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
add systemd.mask=systemd-boot-random-seed.service to your kernel cmdline?
