### ISSUE TITLE
Freedesktop debugging page deserves some updates

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#3226]
https://freedesktop.org/wiki/Software/systemd/Debugging/
- mention systemd.debug-shell
- some links points to old freedesktop bugzilla
- systemctl dump was obsoleted

**Comment by keszybz** [comment]
https://secure.freedesktop.org/cgit/www/commit/Software/systemd/Debugging.mdwn?id=903f710189c403077b30917b77b91c3ae29f8eb1
