### ISSUE TITLE
Get loaded policy while DBUS-daemon is running

### ISSUE THREAD

**Issue by PoneyUHC** [systemd/systemd#32282]
About DBUS and the dbus-daemon API

I am currently doing researches around DBUS, especially looking how I could implement some tooling to point out which exchanges are possible on the bus, and what data leak they would imply.
For this, I would like to be able to get the running system bus policy, which I cannot find how to request. Is there any interface / way to do so ?

**Comment by poettering** [comment]
This is nt the D-Bus community, but the systemd community. Please contact the D-Bus community for D-Bus questions.
