### ISSUE TITLE
failed to start reboot.target - no way to reboot without magic sysrq

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#3229]
### Submission type
- [x ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch
### In case of bug report: Unexpected behaviour you saw

```
$ sudo reboot
Failed to start reboot.target: Failed to activate service 'org.freedesktop.systemd1': timed out
See system logs and 'systemctl status reboot.target' for details.
Failed to talk to init daemon.
[1]$ time systemctl status reboot.target
Failed to get properties: Failed to activate service 'org.freedesktop.systemd1': timed out
systemctl status reboot.target  0.00s user 0.00s system 0% cpu 25.008 total
```

I don't know if this is the same as my previous bug, but
1. The 25-second timeout is too long
2. There needs to be a better way to recover a system with broken systemd. I don't even know which process is broken, which socket is not connected, or whatnot. The error messages do not tell me anything useful. Where is this stuff documented?

[journal.txt](https://github.com/systemd/systemd/files/256307/journal.txt)

**Comment by evverx** [comment]
Closing in favor of #3282

**Comment by TopCheff** [comment]
gracias!
