### ISSUE TITLE
Systemd won't boot from compressed btrfs

### ISSUE THREAD

**Issue by darlingm** [systemd/systemd#323]
Using btrfs option compress=lzo, for example.

**Comment by poettering** [comment]
This report is useless the way it is.

How about telling what precisely the error is, and why you believe this has anything to do with systemd. Also, let us know which distro you are using, and which systemd version. Whether you use an initrd, and which one. 

Without this information we really cannot help you.

**Comment by darlingm** [comment]
I left it quite basic, because it was my understanding booting from a compressed btrfs volume was planned to be added to systemd as a feature, but never was.  Should systemd support operating this way?

**Comment by poettering** [comment]
whether a btrfs volume uses compression or not is pretty much irrelevant to systemd, it's something between the kernel, the bytes on disk and the user, but systemd doesn't really care.

**Comment by crrodriguez** [comment]
This is not a systemd problem.. your initrd probably lacks of the required compression kernel modules. It is entirely a kernel setup problem.
ps: it works, the laptop I'm writting this message from boots from lzo compressed rootfs.
