### ISSUE TITLE
Search engines link to pages with trailing slashes and end up in a 404

### ISSUE THREAD

**Issue by nachtjasmin** [systemd/systemd#32310]
> I hope this doesn't break something somewhere else. (#32207)

Unfortunately, that happened. Search engines linked to the pages with the trailing slash and all of those now return a 404.

For example, a [DuckDuckGo search for portable services](https://duckduckgo.com/?q=portable+services+systemd) links to `https://systemd.io/PORTABLE_SERVICES/` (with the trailing slash), so opening those search results now ends up in a 404.

**Comment by mrc0mmand** [comment]
*[screams internally]*

I'm not really sure what to do here. It seems [0][1] that GH pages have a really strange way of handling trailing slashes, so we can either have broken relative links or broken search engine links for some time. @keszybz should we revert #32207 and come up with some, potentially very ugly, solution for the relative links or just wait a bit until search engines drop the old indexed pages?

[0] https://saveman71.com/2023/remove-trailing-slash-cloudflare-jekyll
[1] https://stackoverflow.com/questions/54727643/trailing-slashes-in-jekyll-github-pages-site-cause-404

**Comment by keszybz** [comment]
Hmm, if this was just about search engines, then I'd answer "let's wait". But I am afraid that people have the URLs with slashes linked in various places or bookmarked. Can we somehow add a redirect?

**Comment by mrc0mmand** [comment]
Unfortunately not without introducing some other service into the mix (Cloudflare). Or at least I'm not aware of any other way. It indeed sucks. But before I give up completely, I'll try look into the trailing slash stuff a bit more, if there's possibly some other way to make the relative links work with it.

Should we revert the change in the meantime to unbreak existing links?

**Comment by mrc0mmand** [comment]
Huh, one potentially easy solution is to just use absolute links, which doesn't seem to be an issue for us, since the docs/ layout is flat. I'll do a couple more tests, but it really appears to be the easy way out.

**Comment by mrc0mmand** [comment]
-> https://github.com/systemd/systemd/pull/32324
