### ISSUE TITLE
networkd: "route_expire_handler" cannot work because it passes "NULL", which is not allowed

### ISSUE THREAD

**Issue by jstuyts** [systemd/systemd#3232]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229-3
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

I want to have a host with a static IPv6 address on a subnet with hosts that must use a managed (i.e. DHCP) address. There is no route to the public IPv6 internet, so the router(s) on the subnet send router advertisements with a lifetime of zero. The RAs also have the M and O flags enabled, and the A flag disabled. On hosts that must have a static IPv6 address, the router(s) sending a RA with a lifetime of zero should not be added as a default router.
### In case of bug report: Unexpected behaviour you saw

The router(s) were added as a default router because the removal of the route failed:

```
NDisc CLIENT: Received Router Advertisement: flags MANAGED preference medium lifetime 0 sec
NDisc CLIENT: Update prefix fd06:b8ef:d73e:0002:0000:0000:0000:0000/64 lifetime 86400 expires in 1d
Assertion 'in_addr_is_link_local(AF_INET6, (const union in_addr_union *) &client->local_address) > 0' failed at src/libsystemd-network/sd-dhcp6-client.c:1154, function sd_dhcp6_client_start(). Ignoring.
eth0: Starting DHCPv6 client on NDisc request failed: Invalid argument
Assertion 'callback' failed at src/libsystemd/sd-netlink/sd-netlink.c:529, function sd_netlink_call_async(). Ignoring.
Could not send rtnetlink message: Invalid argument
Could not remove route: Invalid argument
```

Note: The fact that the DHCPv6 client could not be started is expected as this host must keep its static address.
### In case of bug report: Steps to reproduce the problem

Create a host with a static IPv6 address and DHCP disabled:

```
[Match]
Name = eth0

[Network]
Address = 192.168.0.6/24
Gateway = 192.168.0.1
Address = fd06:b8ef:d73e:0002:0001:0001:0000:6700/64
DHCP = none
```

Start another host that sends router advertisements with the M, O flags enabled, the A flag disabled, and a lifetime of zero:

```
interface eth0
{
    AdvSendAdvert on;

    # This is not a default router.
    AdvDefaultLifetime 0;

    # The Tayga router does not care about how IPv6 addresses are obtained,
    # but all router advertisements must have the same values for this
    # information.
    AdvManagedFlag on;
    AdvOtherConfigFlag on;

    prefix fd06:b8ef:d73e:2::/64
    {
        AdvOnLink on;
        AdvAutonomous off;
    };

    route fd06:b8ef:d73e:ff02::/96
    {
    };
};
```
### Problem analysis

`route_expire_handler` is invoked properly, but it passes a `NULL` as a callback to `route_remove`: https://github.com/systemd/systemd/blob/b37bf74411a44d8efb51173195e532442f8226e5/src/network/networkd-route.c#L415

`route_remove` passes this `NULL` to `sd_netlink_call_async`:
https://github.com/systemd/systemd/blob/b37bf74411a44d8efb51173195e532442f8226e5/src/network/networkd-route.c#L406

But `sd_netlink_call_async` does not accept `NULL` for the callback:
https://github.com/systemd/systemd/blob/09541e49ebd17b41482e447dd8194942f39788c0/src/libsystemd/sd-netlink/sd-netlink.c#L517

**Comment by ssahani** [comment]
Indeed  Fix is #3242
