### ISSUE TITLE
Can't override OnCalendar

### ISSUE THREAD

**Issue by trapperhoney** [systemd/systemd#3233]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229-4ubuntu4
### Used distribution

> Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

> Drop-in override of timer OnCalendar should be authoritative.
### In case of bug report: Unexpected behaviour you saw

> Drop-in override of timer OnCalendar seems to be a union of base OnCalendar value and the override in the drop-in.
### In case of bug report: Steps to reproduce the problem

I'm trying to modify the default execution time of the apt-daily.timer unit that ships with the current version of Ubuntu.  With the configuration below, I expect my override of OnCalendar to explicitly define the timer's timing behavior.  However, it appears that the actual schedule times I get are a union of the two OnCalendar definitions.  Note that the RandomizedDelaySec field is properly overriden in the 'show' output, but OnCalendar does not appear in this output.  The list-timer output shows a time related to the base value of OnCalendar.  I've tried reloading the timer and service units, restarting the systemd daemon, removing the timestamp files in /var/lib/systemd/timers/ and even rebooting ;)  I believe there is a bug in the way scheduled times are calculated in the presence of drop-in overrides.

Timer definitions:

```
~: systemctl cat apt-daily.timer
# /lib/systemd/system/apt-daily.timer
[Unit]
Description=Daily apt activities

[Timer]
OnCalendar=*-*-* 6,18:00
RandomizedDelaySec=12h
AccuracySec=1h
Persistent=true

[Install]
WantedBy=timers.target

# /etc/systemd/system/apt-daily.timer.d/override.conf
[Timer]
OnCalendar=06:00
RandomizedDelaySec=1h
```

Scheduled timer:

```
~: systemctl list-timers apt-daily.timer
NEXT                         LEFT    LAST                         PASSED       UNIT            ACTIVATES
Tue 2016-05-10 18:37:28 EDT  7h left Tue 2016-05-10 06:59:52 EDT  4h 25min ago apt-daily.timer apt-daily.service

1 timers listed.
Pass --all to see loaded but inactive timers, too.
```

Interpreted configuration:

```
~: systemctl show apt-daily.timer
Unit=apt-daily.service
NextElapseUSecRealtime=46y 4month 1w 1d 16h 37min 28.889468s
NextElapseUSecMonotonic=0
LastTriggerUSec=46y 4month 1w 1d 4h 59min 52.529432s
LastTriggerUSecMonotonic=3d 9h 24min 745.122ms
Result=success
AccuracyUSec=1h
RandomizedDelayUSec=1h
Persistent=yes
WakeSystem=no
RemainAfterElapse=yes
Id=apt-daily.timer
Names=apt-daily.timer
Requires=var.mount -.mount sysinit.target
WantedBy=timers.target
Conflicts=shutdown.target
Before=apt-daily.service timers.target shutdown.target
After=time-sync.target var.mount -.mount sysinit.target
Triggers=apt-daily.service
RequiresMountsFor=/var/lib/systemd/timers
Description=Daily apt activities
LoadState=loaded
ActiveState=active
SubState=waiting
FragmentPath=/lib/systemd/system/apt-daily.timer
DropInPaths=/etc/systemd/system/apt-daily.timer.d/override.conf
UnitFileState=enabled
UnitFilePreset=enabled
StateChangeTimestamp=Tue 2016-05-10 06:59:56 EDT
StateChangeTimestampMonotonic=293044781020
InactiveExitTimestamp=Fri 2016-05-06 21:35:56 EDT
InactiveExitTimestampMonotonic=5880869
ActiveEnterTimestamp=Fri 2016-05-06 21:35:56 EDT
ActiveEnterTimestampMonotonic=5880869
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Fri 2016-05-06 21:35:56 EDT
ConditionTimestampMonotonic=5879656
AssertTimestamp=Fri 2016-05-06 21:35:56 EDT
AssertTimestampMonotonic=5879656
Transient=no
StartLimitInterval=10000000
StartLimitBurst=5
StartLimitAction=none
```

**Comment by falconindy** [comment]
Same as any other setting which can be repeated, you need to reset it with an empty OnCalendar= directive, i.e. your dropin should have:

```
[Timer]
OnCalendar=
OnCalendar=06:00
```

**Comment by trapperhoney** [comment]
Sorry, I completely missed the fact that OnCalendar was repeatable :\  Adding the empty version fixed this for me.  Thanks for the quick response!
