### ISSUE TITLE
docs: make clear that BindPaths= implies PrivateMounts= which detaches the mount namespace of a service from the host

### ISSUE THREAD

**Issue by willwu1217** [systemd/systemd#32339]
### systemd version the issue has been seen with

249

### Used distribution

euleros v2r12

### Linux kernel version used

5.10.0-136.12.0.86.h1428.eulerosv2r12.aarch64

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

execute `ip netns` with no error.

### Unexpected behaviour you saw

failed with "Error: Peer netns reference is invalid."

### Steps to reproduce the problem

1、create a service with BindPaths 
2、add netns in service ExecStart
3、The new netns cannot be accessed

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
linux-mhaKqL:/var/run/netns # cat /lib/systemd/system/netns_test.service
[Unit]
Description=netns test

[Service]
User=root
Group=root
Type=oneshot
RemainAfterExit=true
#BindPaths=/lib64/libc.so.6:/usr/local/lib64/libc.so.6
ExecStart=/usr/bin/env ip netns add ns_created_in_service
ExecStart=/usr/bin/env ip netns
ExecStop=/usr/bin/env ip netns delete ns_created_in_service

[Install]
WantedBy=multi-user.target
Alias=test.service

linux-mhaKqL:/var/run/netns # systemctl start netns_test
linux-mhaKqL:/var/run/netns #
linux-mhaKqL:/var/run/netns # systemctl status netns_test
● netns_test.service - netns test
     Loaded: loaded (/usr/lib/systemd/system/netns_test.service; disabled; vendor preset: disabled)
     Active: active (exited) since Thu 2024-04-18 22:15:01 CST; 6s ago
    Process: 3605819 ExecStart=/usr/bin/env ip netns add ns_created_in_service (code=exited, status=0/SUCCESS)
    Process: 3605822 ExecStart=/usr/bin/env ip netns (code=exited, status=0/SUCCESS)
   Main PID: 3605822 (code=exited, status=0/SUCCESS)

Apr 18 22:15:01 linux-mhaKqL systemd[1]: Starting netns test...
Apr 18 22:15:01 linux-mhaKqL env[3605822]: Error: Peer netns reference is invalid.
Apr 18 22:15:01 linux-mhaKqL env[3605822]: Error: Peer netns reference is invalid.
Apr 18 22:15:01 linux-mhaKqL env[3605822]: ns_created_in_service
Apr 18 22:15:01 linux-mhaKqL env[3605822]: br-tun (id: 0)
Apr 18 22:15:01 linux-mhaKqL systemd[1]: Finished netns test.
linux-mhaKqL:/var/run/netns # ip netns
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
ns_created_in_service
br-tun (id: 0)
```

**Comment by yuwata** [comment]
That's not a issue in systemd. `ip netns` command mounts several paths. With BindPaths=, we setup a new mount namespase, hence it interferes `ip netns`.

**Comment by willwu1217** [comment]
So, Is there any trick to use bindpaths and support netns creation at the same time?

**Comment by bluca** [comment]
There is a native network namespace option, you should use that instead of ip netns

**Comment by poettering** [comment]
Yeah, ip netns sets up bind mounts, but once you do BindPaths detaches the mount namespace, and hence undoes the effect of ip netns.

**Comment by poettering** [comment]
we could probably document that better, i.e. say clearly in the docs that BindPaths= implies PrivateMounts=. We say something like that for many of the other options that do this, but it's not explicitly sad for BindPaths= right now.

**Comment by willwu1217** [comment]
Yes, I notice the /proc/pid in service/ns/net is different from host when use BindPaths. Maybe BindPaths can support not create new ns/net, just create new ns/mnt？

**Comment by willwu1217** [comment]
I have verified a solution to create an ip netns visible to the host in the systemd service using bindpaths configuration.
change `ip netns add ns_in_bindpath_service` to
`nsenter -m -n -t 1 ip netns add ns_in_bindpaths_service` .
Force the creation of netns in host netns and host mntns in the service.
