### ISSUE TITLE
ExecMainHandoverTimestamp needs fixing

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#32404]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

A tracker bug, since the way ExecMainHandoverTimestamp (i.e. #32380) is implemented it really shouldn't stay.

1. Either it should become a concept for all kinds of executed processes (which I'd prefer)

2. or it should be moved out of the ExecStatus structure

In the first case it really should be renamed however.

**Comment by bluca** [comment]
It's about service activation tracking, so moving it to a different place is enough, which is not an API but just an internal rearrangement so no need to block rc

**Comment by poettering** [comment]
well, my think was that it actually would be nice to track this for all forked processes, and in that case it would probably have to change name

**Comment by bluca** [comment]
ExecMain timestamps are for the main processes already. It would require a new and separate exec_fd, which means there won't be a single last-thing-to-do-before-execve anymore, but two of them, which will race each other. If there's no use case for it, let's not make things more complicated for no benefit.

**Comment by poettering** [comment]
> ExecMain timestamps are for the main processes already. It would require a new and separate exec_fd, which means there won't be a single last-thing-to-do-before-execve anymore, but two of them, which will race each other. If there's no use case for it, let's not make things more complicated for no benefit.

I don't see a race there? how would there be a race?

sure you have to decide what to do first, i.e. take/send the timestamp or mark the execfd as "hot", but that's fine. neither of these are "risky" or "slow" operations, hence just do one first, doesn't really matter which one you pick.
