### ISSUE TITLE
networkd: imply KeepConfiguration= for network devices if root fs has _netdev set

### ISSUE THREAD

**Issue by Kxuan** [systemd/systemd#32426]
### systemd version the issue has been seen with

255.4-2-arch

### Used distribution

ArchLinux

### Linux kernel version used

6.8.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

system does not hang during shutdown when the root file system is on an iscsi device.

### Unexpected behaviour you saw

system hang due to network has been stopped before root file system.

### Steps to reproduce the problem

1. root file system is a "local" file system (e.g ext4/btrfs)
2. reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
```
### Additional
This is very similar to #22383 #21967 

But due to #22383 is using `path_is_network_fs`, if the root fs is a "local file system" on a network device, the changes to the value `KeepConfiguration=` will not be applied for this situation.

So I think systemd should use the "_netdev" options in `fstab` to detect whether if network is required by the root filesystem.
A filesystem name whitelist is insufficient and incorrect.

**Comment by yuwata** [comment]
Waiting in #35040.
