### ISSUE TITLE
Grasping for straws here. 

### ISSUE THREAD

**Issue by 1490kdrm** [systemd/systemd#32421]
But with the security mailing list closed to the appropriate individuals, here i go. 

Hi,

On the ArchLinux forum, we currently have a running quandry:

Both libsystemd-core (sha256 b1a9e5be43c028442c07071e202f44f33e3a2df167822c5cfed8f998e01fe169) and libsystemd-shared (sha256 ff42428f0fcc346cc56e2b00d4b5c4bd43b55f3465b4ccab0efba9c88f4a1c03) are coming up as malicious on VirusTotal, Hybrid-Analysis and a slew of other different, independent, malware analysis websites.

This is also happening for elf binaries such as kmod, go, and elf binaries such as libgo.so.*.

All of the above said packages are being delivered by Arch certified mirrors.

The quandry is also that when run on these sandboxing websites, they are VM and datacenter aware. But when they do run, they contact and can deliver distribution specific files. Meaning for Ubuntu, for instance, it contacts malicious domains, either typosquatted(sp?) or otherwise slightly modified from the clean, normal domains.

So, in short. I don't believe this is an ArchLinux specific issue.

I'm not a security researcher. But, given my experiences the past two years. Which i'll refrain from the gory details here and let my previous posts and data uploads speak for themselves. Those links to my otx.alienvault pulses, my VirusTotal account with attached collections and graphs, and the ArchLinux threads in question.

When i first uploaded the files in early March, they had 0 detections. But, a week after the XZ debacle coming to light, they suddenly had 14, and now 16 and 17 detections, respectively.

One, two, three, or even five i can write off as a false positive. But 17, one a file as critical as the lynchpin of systemd i feel like should not be ignored the way it has been.

At risk of overwhelming everyone with stuff; a plethora of data, relevant or not, is within the Arch posts and the links below.

Most recent arch thread unrelated to my post: https://bbs.archlinux.org/viewtopic.php?pid=2166519#p2166519

My post on arch's forum: https://bbs.archlinux.org/viewtopic.php?id=294456

Virustotal for libsystemd-core: https://www.virustotal.com/gui/file/b1a9e5be43c028442c07071e202f44f33e3a2df167822c5cfed8f998e01fe169/detection/f-b1a9e5be43c028442c07071e202f44f33e3a2df167822c5cfed8f998e01fe169-1713795432

Virustotal for libsystemd-shared: https://www.virustotal.com/gui/file/ff42428f0fcc346cc56e2b00d4b5c4bd43b55f3465b4ccab0efba9c88f4a1c03/detection/f-ff42428f0fcc346cc56e2b00d4b5c4bd43b55f3465b4ccab0efba9c88f4a1c03-1713795504

Link to OTX profile: https://otx.alienvault.com/user/Merkd1904/pulses

Links to relevant pulses:

https://otx.alienvault.com/pulse/66207a021131686c618c5239
Stix2.1 download link: https://otx.alienvault.com/otxapi/pulses/66207a021131686c618c5239/export/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1lcmtkMTkwNCIsInZhbHVlIjpbIjY2MjA3YTAyMTEzMTY4NmM2MThjNTIzOSIsInN0aXgyLjEiXSwiZXhwIjoxNzEzOTE4NjU2fQ.eoCWoHXUnYiJP4v84iV7pnSEwCtEh7rX11QQR2G2jlw&format=stix2.1

https://otx.alienvault.com/pulse/661db37bf549518bf6f7f377
Stix2.1 download link: https://otx.alienvault.com/otxapi/pulses/661db37bf549518bf6f7f377/export/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1lcmtkMTkwNCIsInZhbHVlIjpbIjY2MWRiMzdiZjU0OTUxOGJmNmY3ZjM3NyIsInN0aXgyLjEiXSwiZXhwIjoxNzEzOTE4NzYwfQ.0EcBtkFgC2kF79kECjoAwTBWLxXEolGkp5z6pW4srSk&format=stix2.1

https://otx.alienvault.com/pulse/6621872309f454a3d9ca765e
Stix2.1 download link: https://otx.alienvault.com/otxapi/pulses/6621872309f454a3d9ca765e/export/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1lcmtkMTkwNCIsInZhbHVlIjpbIjY2MjE4NzIzMDlmNDU0YTNkOWNhNzY1ZSIsInN0aXgyLjEiXSwiZXhwIjoxNzEzOTE4ODIzfQ.wfYXc0tKjYT6T3lxHxn1cot9BXpahSuet-r3HaC_Ii0&format=stix2.1

As i said, i'm not a security researcher. So if this is out of scope. Or completely out of line, or just batshit crazy let me know.

**Comment by poettering** [comment]
I am sorry, but this is not actionable for us. I don't now those websites in question and we are not providing any built binaries. Please contact your distro for help, and verify those websites aren't just making stuff up.

Anyway, I don't think it makes sense to track this here, as those binaries are not supplied by us, we just provide source code you can trivially look at.
