### ISSUE TITLE
drm and fb nodes for the same GPU get different ID_FOR_SEAT

### ISSUE THREAD

**Issue by alkisg** [systemd/systemd#3243]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229-4ubuntu4
### Used distribution

Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

drm and fb nodes for the same secondary GPU should (?) get the same ID_FOR_SEAT assigned to them.
### In case of bug report: Unexpected behaviour you saw

/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1 gets ID_FOR_SEAT=drm-pci-0000_01_00_0, while
/devices/pci0000:00/0000:00:01.0/0000:01:00.0/graphics/fb0 gets ID_FOR_SEAT=graphics-pci-0000_01_00_0
i.e. they appear to target different seats, even though they're both nodes of the same graphics card.

This is done by this rule:

> $ grep ID_FOR_SEAT /lib/udev/rules.d/71-seat.rules 
> TAG=="seat", ENV{ID_FOR_SEAT}=="", ENV{ID_PATH_TAG}!="", ENV{ID_FOR_SEAT}="$env{SUBSYSTEM}-$env{ID_PATH_TAG}"

SUBSYSTEM is "drm" and "graphics" for those 2 nodes, so they appear to target different seats.

So I guess my question here is, should SUBSYSTEM really be used to construct ID_FOR_SEAT?
It makes seat matching confusing...
### In case of bug report: Steps to reproduce the problem

Connect a second GPU to some computer and run `udevadm info -e`.

**Comment by poettering** [comment]
Actually, let's close this. ID_FOR_SEAT is a naming suggestion for a seat, if you create a new seat, not more. It synthesizes a name from hw that might be suitable to name the seat after. Which name you pick is up to you, you can also name it "seat-foo", and hence it doesn't matter much whether it derives from one subsystem or the other, key is that is unique.

This is used the ID_AUTOSEAT feature, i.e. when we automatically synthesize a new seat based on some special multi-seat hw being plugged in. We need to name that seat somehow in a unique way, hence derive it from the hardware that has the ID_AUTOSEAT stuff set. And if that's a drm device, we derive the name from that. If it's a fb device we derive it from that. Hence, it really doesn't matter too much, as long as the name is unique and well-formed.

This is documented here btw:

https://www.freedesktop.org/software/systemd/man/sd-login.html#udev%20Rules

Closing.
