### ISSUE TITLE
Virtual Console shows LUKS passphrase in plaintext when entering it

### ISSUE THREAD

**Issue by heis2201** [systemd/systemd#32446]
### systemd version the issue has been seen with

systemd-255.4-1.fc40.x86_64

### Used distribution

Fedora 40

### Linux kernel version used

6.8.7-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

Passphrase marked by asterix

### Unexpected behaviour you saw

Passphrase in clear text

### Steps to reproduce the problem

When booting luks encrypted Fedora 40, hit ESC to switch from graphical plymouth to virtual console, type password
 
See attached screenshots below

### Additional program output to the terminal or log subsystem illustrating the issue

![screenshotcryptsetup](https://github.com/systemd/systemd/assets/17801574/dfce38e0-719d-4318-abcc-95dfdcdc6ae7)

![luks](https://github.com/systemd/systemd/assets/17801574/c43107c0-cec2-44ce-a274-35ad13dfedb0)

**Comment by poettering** [comment]
this suggests that plymout is not properly grabbing the input devices, and the keypresses end up both in plymouth and on the VT.
