### ISSUE TITLE
mount is failing with below error message "cgroup already mounted or mount point busy."

### ISSUE THREAD

**Issue by kashwindayan** [systemd/systemd#32444]
### systemd version the issue has been seen with

255.2

### Used distribution

Photon 5.0

### Linux kernel version used

kernel-6.1.62-11.ph5

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

root@photon-d6c47b79e68e [ ~ ]# sh check.sh
+ mkdir 1
+ mount -t cgroup -o none,name=foo cgroup 1/
+ umount 1
+ echo ----------------------------------------
----------------------------------------
+ systemctl daemon-reload <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
+ mount -t cgroup -o none,name=foo cgroup 1/ 
+ umount -f 1
+ rm -rf 1
root@photon-d6c47b79e68e [ ~ ]# echo $?
0

From Journalctl logs,
journalctl -xe -u root-1.mount

Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed dead -> mounted
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit root-1.mount has successfully entered the 'dead' state.
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed mounted -> dead
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Collecting.
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed dead -> mounted
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit root-1.mount has successfully entered the 'dead' state.
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed mounted -> dead
Apr 25 00:32:57 photon-d6c47b79e68e systemd[1]: root-1.mount: Collecting.

### Unexpected behaviour you saw

This issue was discovered in Photon while running the ltp test "cgroup cgroup_regression_test.sh"
Simplified the issue in below script.

For below script, I am seeing below error message.
+ mkdir 1
+ mount -t cgroup -o none,name=foo cgroup 1/
+ umount 1
+ echo ----------------------------------------
----------------------------------------
+ mount -t cgroup -o none,name=foo cgroup 1/
mount: /root/1: cgroup already mounted or mount point busy. <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error
       dmesg(1) may have more information after failed mount system call.  <<<<<<<<<<<<<
+ umount -f 1
umount: 1: not mounted.
+ rm -rf 1

From Journalctl logs,
journalctl -xe -u root-1.mount
Apr 25 00:29:45 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed dead -> mounted
Apr 25 00:29:45 photon-d6c47b79e68e systemd[1]: root-1.mount: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit root-1.mount has successfully entered the 'dead' state.
Apr 25 00:29:45 photon-d6c47b79e68e systemd[1]: root-1.mount: Changed mounted -> dead
Apr 25 00:29:45 photon-d6c47b79e68e systemd[1]: root-1.mount: Collecting.

### Steps to reproduce the problem

mkdir 1
mount -t cgroup -o none,name=foo cgroup 1/
umount 1
echo "----------------------------------------"
systemctl daemon-reload
mount -t cgroup -o none,name=foo cgroup 1/
umount -f 1
rm -rf 1

**Comment by kashwindayan** [comment]
cc: @sshedi @ssahani

**Comment by poettering** [comment]
On systemd systems systemd is responsible for mounting cgroupfs, and it will do so to /sys/fs/cgroup and the tree below. 

Moreover, cgroupv1 is deprecated.

**Comment by sshedi** [comment]
@poettering Thanks for the response. Couple of points:
- This is not cgroup v1, probably you got confused by the target directory name used.
- Introducing a systemctl daemon-reload or sleep 1 before running mount second time is solving the issue.

So, we suspect this is something happening at systemd level.

We are hitting this issue in VMware PhotonOS while running the following LTP test.
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/controllers/cgroup/cgroup_regression_test.sh#L121

At this point in time, we are really unsure of the cause of the issue, reporting it here to bring it to systemd upstream maintainers attention, this might be some regression which got introduced but not caught.

**Comment by poettering** [comment]
> * This is not cgroup v1, probably you got confused by the target directory name used.

"name=…" is a mount option that only exists for cgroupv1.

**Comment by poettering** [comment]
Also "-t cgroup" is the cgroupv1 fs. the cgroupv2 fs would be "-t cgroup2"

and also, this is not an fs that you mount yourself. It's mounted by systemd, just like procfs and sysfs.

**Comment by sshedi** [comment]
You mean to say the LTP's cgroup regression checks are wrongly written?

We have `systemd.unified_cgroup_hierarchy=yes` set in kernel command line, does this play any role for this failure?
AFAIK, `systemd.unified_cgroup_hierarchy=yes` enables cgroupv2, which implies cgroupv1 should not work. But cgroupv1 mounts are working, so does this mean both cgroup v1 & v2 both are in effect?

**Comment by mrc0mmand** [comment]
> You mean to say the LTP's cgroup regression checks are wrongly written?
> 
> We have `systemd.unified_cgroup_hierarchy=yes` set in kernel command line, does this play any role for this failure? AFAIK, `systemd.unified_cgroup_hierarchy=yes` enables cgroupv2, which implies cgroupv1 should not work. But cgroupv1 mounts are working, so does this mean both cgroup v1 & v2 both are in effect?

The `systemd.` kernel command line options affect only what  cgroup hierarchy _systemd_ mounts; if you mount stuff manually these settings have no effect on it at all.

And given you call `mount` directly without ever involving systemd (or at least that's what the linked test case shows), I don't think systemd is to blame here.

**Comment by sshedi** [comment]
@mrc0mmand Thanks for your time and for looking into this issue. If systemd is not involved, then it should not create `.mount` units for the same right? I see systemd creating mount units when I run this operation. Somehow it looks like systemd is involved in this.

**Comment by mrc0mmand** [comment]
> @mrc0mmand Thanks for your time and for looking into this issue. If systemd is not involved, then it should not create `.mount` units for the same right? I see systemd creating mount units when I run this operation. Somehow it looks like systemd is involved in this.

That's actually pretty easy to verify. Can you reproduce the issue when doing the mounts from a mount namespace? I.e. wrapping the reproducer in `unshare -m` or something similar, so systemd doesn't see the mounts (and hence doesn't create mount units for them).

**Comment by sshedi** [comment]
Thanks @mrc0mmand tried the same after doing `unshare -m` and issue still happening.
Looks like issue is somewhere else. Thanks for all the assistance.

**Comment by poettering** [comment]
> You mean to say the LTP's cgroup regression checks are wrongly written?

i don't know what this is, but if that stuff tries to mount cgroupfs (i.e. does cgroupv1 stuff) on a cgroupv2 system, then it's broken.

> We have `systemd.unified_cgroup_hierarchy=yes` set in kernel command line, does this play any role for this failure? AFAIK, `systemd.unified_cgroup_hierarchy=yes` enables cgroupv2, which implies cgroupv1 should not work. But cgroupv1 mounts are working, so does this mean both cgroup v1 & v2 both are in effect?

some cgroupv1 stuff continues to work for compat with containers. i.e. you don't get controllers and such. It's messy.

Anyway, this is not a systemd problem. we just mount cgroupv2's cgroup2 fs, and everything else is up to the kernel.
