### ISSUE TITLE
tcp sending RST signal in place of FIN at the time of reboot

### ISSUE THREAD

**Issue by abhishpaliwal** [systemd/systemd#3244]
### Submission type
- [YES] Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

216

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> When we rebooting the system using this script we are seeing that TCP is not able to close open socket and because it is not sending FIN signal to receiver.

After doing further analysis on that found that systemd-reboot.service script is using --force option which causes immature shutdown means just kill all the running process and restarted. If TCP found this kind of reboot/restart then treated it as crash in system and sends RST signal.

So, I want to know that what are the impact if we want to remove this --force option from this script and why we are not trying to mature shutdown in place of immature.
## In case of bug report: Expected behaviour you didn't see

> It should close all TCP open sockets
### In case of bug report: Unexpected behaviour you saw

> It is not closing TCP open sockets
### In case of bug report: Steps to reproduce the problem
1. Create any TCP socket.
2. Run this script
3. Check the netstat at receiver end you will still see the ESTABLISHED connection status as an output of netstat command.

**Comment by michich** [comment]
> After doing further analysis on that found that systemd-reboot.service script is using --force option 

Of course it is using --force. systemd-reboot.service is expected to run after ordinary services have already stopped cleanly.

> 1. Create any TCP socket.

In a systemd service? As a systemd socket unit? Or how?

> 1. Run this script

What script?

**Comment by abhishpaliwal** [comment]
means start the systemd-reboot.service

**Comment by michich** [comment]
So do not start systemd-reboot.service.
The command to perform an orderly reboot is "systemctl reboot". And "systemctl poweroff" for an orderly poweroff.
