### ISSUE TITLE
The journal socket should be mounted automatically if MountAPIVFS= is applied and StandardOutput/Error=journal

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#32478]
### Component

systemd

### Is your feature request related to a problem? Please describe

Currently, when MountAPIVFS= takes effect (either implicitly or explicitly) and the service is configured to log to the journal, we lose all logs from systemd-executor as it will neither be able to log to the console, nor will it be able to log to the journal.

### Describe the solution you'd like

If a service is configured to log to the journal and we decide to mount in the APIVFS directories (because it has its own image or other reasons), we should automatically mount in the journal socket so that the service can log to the journal.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
I don't follow? What does MountAPIVFS= do precisely that would cause logging to fail? I don't see the connection?

**Comment by YHNdnzj** [comment]
> I don't follow? What does MountAPIVFS= do precisely that would cause logging to fail? I don't see the connection?

`exec_invoke` enables log open_when_needed. Therefore, it requires access to the journal socket in the target root after switching into it, in order to log there.
