### ISSUE TITLE
Journalctl shows wrong timestamp on some hibernation-related log messages after waking from hibernation

### ISSUE THREAD

**Issue by reallyimeric** [systemd/systemd#32492]
### systemd version the issue has been seen with

systemd 255.4-2

### Used distribution

Arch Linux

### Linux kernel version used

6.8.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

journalctl, systemd-journald

### Expected behaviour you didn't see

Some log messages about preparing for hibernation like `Freezing user space processes` should be before I wake up the system at the next day

### Unexpected behaviour you saw

Some of the messages described above are after the time I press power button at next day

see logs below

### Steps to reproduce the problem

1. press power button to show logoff screen of KDE 6
2. click Hibernate
3. press power button at next day
4. view log using `journalctl -b -e`

### Additional program output to the terminal or log subsystem illustrating the issue

The issue is observed on KDE 6 wayland session for this time, but I noticed the same behavior before on KDE 5 X11.

logs
https://fars.ee/Evb9

**Comment by YHNdnzj** [comment]
Hmm, the frozen user processes also include journald, no? So it can only process the new logs after resuming from hibernation. I doubt if there's anything actionable for systemd?

**Comment by yuwata** [comment]
Yeah, journald is freezed. I have no idea to 'fix' the issue. I guess `journalctl -o show-monotonic` will show these logs with a 'correct' timestamp.

**Comment by dreirund** [comment]
> *logs https://fars.ee/Evb9*

I wanted to see logs because I want to compare to what I observe.

The page loads for a long time and then shows only an empty page, or just shows HTTP error 504 "Gateway time-out".

Can you upload the logfile to github.com and attach it? (Use the "Attach files" option; file needs to have an extension like `.log` or `.txt`; or compressed.)

Regards!
