### ISSUE TITLE
machinectl copy-to should understand relative path arguments

### ISSUE THREAD

**Issue by jernst** [systemd/systemd#325]
Apparently, currently only this works:

```
machinectl copy-to machine /full/path/to/file1 /full/path/to/file2
```

In analogy to `cp`, the current working directory (at least on the source) and a destination ending in a directory should also be supported, e.g.

```
machinectl copy-to machine file1 /full/path/to/
# should be same as
machinectl copy-to machine $(pwd)/file1 /full/path/to/file1
```

**Comment by poettering** [comment]
Closing, since this was implemented in #855
