### ISSUE TITLE
BTRFS mount usability with subvolumes and umlauts

### ISSUE THREAD

**Issue by Zomtir** [systemd/systemd#32517]
### Component

systemctl

### Is your feature request related to a problem? Please describe

I have a huge BTRFS storage partition for uncritical data collections. Each of those ~10 collections is big enough to justify a dedicated subvolume (50GB-500GB) for individual snapshots.

Here is an illustrative example ( `@subvolume -> mountpoint`)

```
@audio -> "/media/Hörspiele"
@music -> "/media/Musik"
@movies -> "/media/Filme"
@club_rsvA -> "/media/Vereine/RSV A"
@club_fcAE -> "/media/Vereine/FC Ä"
```

This is the necessary procedure to implement a single mount:

```
$ systemd-escape -p --suffix=mount /media/Hörspiele
media-H\xc3\xb6rspiele.mount
$ sudo vim 'media-H\xc3\xb6rspiele.mount'
[Unit]
Description=Mount btrfs subvolume: Hörspiele

[Mount]
What=UUID=fxc7dcdd-81a0-4b5c-af33-8etb0xafb7c9
Where=/media/Hörspiele
Type=btrfs
Options=defaults,auto,nofail,x-gvfs-hide,subvol=@audio

[Install]
WantedBy=multi-user.target
$ sudo systemctl enable 'media-H\xc3\xb6rspiele.mount'
```

Notice that you **have** to address the mountpoint in quotation marks in bash because the backslash is a reserved character in bash. Without quotation marks the mountpoint requires escaping the escaping sequence:

`/etc/systemd/system/media-Storage-H\\xc3\\xb6rspiele.mount`

I am fully aware that the latter effects of this chain are neither directly caused nor designed by systemd. Nonetheless it creates two points of friction:

1) The main obstacle was this restriction documented in [systemd.mount(5)](https://manpages.debian.org/testing/systemd/systemd.mount.5.en.html):

`Mount units must be named after the mount point directories they control.`

Although the unit files directly support non-trivial mountspoints with `Where=/media/Hörspiele`, this benefit is directly nullified by being required to jump trough loops for the file name. As mentioned further down in the alternatives section, I would love to have considered systemd units as a viable and modern mount option, but in this case it seems to drag outdated design with it. I would be interested in the reasoning why this file name scheme is mandatory.

2) You cannot specify multiple mountpoints in a single unit file.

Indirectly related to point (1), because once the filename is bound to the mountpoint, it is obvious that one unit file is restricted to a single mountpoint.

From a user perspective this seems like an arbitrary restriction, especially for BTRFS. A single partition is designed to provide multiple mountable subvolumes. All of them shall be available on the same conditions (e.g. device plugged in, partition intact). There is no huge benefit in having dedicated systemd units for each and every subvolume, because in most cases the failure of one mount applies to all others (assuming all locations exist).

### Describe the solution you'd like

Regarding 1)

If the unit filename was not tied to the mountpoint, one could freely abbreviate or substitute the the mountpoint folder.  This would also allow prefixing for a cleaner file structure:

```
/etc/systemd/system/mount_audio.mount --> "Where=/media/Hörspiele"
/etc/systemd/system/mount_music.mount --> "Where=/media/Musik"
/etc/systemd/system/mount_movies.mount --> "Where=/media/Filme"
/etc/systemd/system/mount_club_rsvA.mount --> "Where=/media/Vereine/RSV A"
/etc/systemd/system/mount_club_fcAE.mount --> "Where=/media/Vereine/FC Ä"
```

Regarding 2)

Even more preferable would be to chain mountpoints in a single unit file. One could let all of them fail if a single one fails.

```
# /etc/systemd/system/mount_storage.mount
[Unit]
Description=Mount btrfs partition: Storage

[Mount]
What=UUID=fxc7dcdd-81a0-4b5c-af33-8etb0xafb7c9
Where=/media/Hörspiele
Type=btrfs
Options=defaults,auto,nofail,x-gvfs-hide,subvol=@audio

[Mount]
What=UUID=fxc7dcdd-81a0-4b5c-af33-8etb0xafb7c9
Where=/media/Musik
Type=btrfs
Options=defaults,auto,nofail,x-gvfs-hide,subvol=@music

[Install]
WantedBy=multi-user.target
```

### Describe alternatives you've considered

**Using the english names as mountpoints**

For aesthetic reasons and consistency, I prefer to have verbose folder names in my native language. It seems to be counter-intuitive to be able to name folders in certain way, but have them unusable as mount points.

Having an `~/audio` folder next to a `~/Dokumente` folder is not very flattering in a file browser.

**Using fstab**

This is what got me here in the first place. As mentioned in #25371, not all octal codes are supported. Beside that every other page lists different octal codes for the extended table, no official documentation was to be found.

The [fstab 5 manpages](https://manpages.debian.org/unstable/mount/fstab.5.en.html) only contain two octal codes: 040 (space) and 011 (tab). I manually tested 042 (double quotes), which does work. 224 (ö) does not work.

So using mount points with umlauts is literally impossible with `fstab`.

**Using a single topfolder as mountpoint**

One could use a single btrfs subvolume `@storage` and put all folders in there. But you will no longer be able to make individual snapshot and not be able to mount them at different locations.

**Using softlinks**

It is possible to mount all directories unter `/mnt/`, where they will be hidden in any graphical file browser by default. Then you can create softlinks to `/media/` or `/home/user/`. I would count this as a solution with high compromise level. But yes it works.

**Using PAM**

Ironically it gets easier when you encrypt your data with LUKS and use PAM mount. Just add one unicode line to `/etc/security/pam_mount.conf.xml` and you are done for a single mountpoint:

<volume user="root" fstype="btrfs" path="/dev/disk/by-uuid/fxc7dcdd-81a0-4b5c-af33-8etb0xafb7c9" mountpoint="/media/Hörspiele" options="defaults,auto,nofail,x-gvfs-hide,subvol=@audio" />

I would very welcome it to also have the level of usability from PAM for the systemd mount unit files.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by arvidjaar** [comment]
> [/etc/fstab] not all octal codes are supported

What octal codes do you need?
```
bor@tw:~> grep /mnt /etc/fstab
/dev/vdb                                   /mnt/Hörspiele        ext4   nofail                 0  0
bor@tw:~> findmnt /mnt/Hörspiele
TARGET         SOURCE   FSTYPE OPTIONS
/mnt/Hörspiele /dev/vdb ext4   rw,relatime
bor@tw:~> 
```

**Comment by Zomtir** [comment]
> What octal codes do you need?

Well this is awkward. Was about to mention `224` (`ö`) but as you demonstrateded, it just works. It seems I have never tried this combination. Only whitespaces need to be escaped.

Any use in keeping this open then? fstab not picking up all octal codes (such as 224) is annoying but unrelated. The strict unit filename policy also takes time to digest, but there may be good reasons for it.

**Comment by poettering** [comment]
Sorry, that strict mount unit naming policy is really important to us, we need it to order things properly, i.e. because foo.mount must be mounted before foo-bar.mount. Similar for RequiresMountsFor= we need a clear way how to figure out which units to add the req deps for.

i.e. by declaring that the unit naming and the file system paths must have a bijective mapping things are relatively easy, for each fs path we know exactly which mount units to conisder, without having to enumerate them all.

Hence, we are not going to change the mount unit naming policy, sorry.

And the 2nd item, we really need to be able to schedule individual mount points, i.e. when precisely they are created. This is straightforward if each mount is a unit, because we have After=/Before= and can order them precisely against everything. If we'd allow a single unit file to mount multiple mount points at completely different places all that wouldn't work anymore.

And yes, having umlauts in mount point names should generally just work, because you can escape them. It's not necessarily pretty, but it works.

Hence, I think there's nothing actionable for us here. Closing.
