### ISSUE TITLE
systemd silently fails to set persistent network names if they are too long

### ISSUE THREAD

**Issue by robinchrist** [systemd/systemd#32525]
### systemd version the issue has been seen with

252.22-1~deb12u1

### Used distribution

Debian 12 / Proxmox VE 8.2

### Linux kernel version used

6.8.4-2-pve

### CPU architectures issue was seen on

x86_64

### Component

systemd-network-generator

### Expected behaviour you didn't see

Sanely generated ethernet device names taking the 15-character limit into account

### Unexpected behaviour you saw

systemd silently fails to set persistent names for ethernet interfaces, resulting in `eth0`, `eth1`...

### Steps to reproduce the problem

This particular platform has very long interfaces names

```
root@pve-4:~# udevadm test-builtin net_id /sys/class/net/enp45s0f1np1
[...]
Using default interface naming scheme 'v252'.
Parsed configuration file "/usr/lib/systemd/network/99-default.link"
Parsed configuration file "/usr/lib/systemd/network/73-usb-net-by-mac.link"
[...]
Created link configuration context.
ID_NET_NAMING_SCHEME=v252
enp45f1np1: addr_assign_type=3, MAC address is not permanent.
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:03.1/0000:2d:00.1/of_node".
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:03.1/0000:2d:00.1/physfn".
enp45f1np1: Parsing slot information from PCI device sysname "0000:2d:00.1": success
enp45f1np1: dev_port=0
enp45f1np1: PCI path identifier: domain=0 bus=45 slot=0 func=1 phys_port=p1 dev_port=0 → p45s0f1np1
ID_NET_NAME_PATH=enp45s0f1np1
Unload kernel module index.
Unloaded link configuration context.
```

and even worse for the virtual functions
```
root@pve-4:~# udevadm test-builtin net_id /sys/class/net/enp45s0f0npf0vf0 
[...]
Using default interface naming scheme 'v252'.
Parsed configuration file "/usr/lib/systemd/network/99-default.link"
Parsed configuration file "/usr/lib/systemd/network/73-usb-net-by-mac.link"
[...]
Created link configuration context.
ID_NET_NAMING_SCHEME=v252
enp45f0npf0vf0: addr_assign_type=1, MAC address is not permanent.
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:03.1/0000:2d:00.0/of_node".
sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:03.1/0000:2d:00.0/physfn".
enp45f0npf0vf0: Parsing slot information from PCI device sysname "0000:2d:00.0": success
enp45f0npf0vf0: dev_port=0
enp45f0npf0vf0: PCI path identifier: domain=0 bus=45 slot=0 func=0 phys_port=pf0vf0 dev_port=0 → p45s0f0npf0vf0
ID_NET_NAME_PATH=enp45s0f0npf0vf0
Unload kernel module index.
Unloaded link configuration context.
```

As you can see, `enp45s0f0npf0vf0` is a pretty long name. Longer than the allowed maximum, which means that renaming will silently fail. This only gets visible if you debug via `sudo SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/enp45s0f1np1`

The problem is: It fails silently. The kernel log shows
```
[  515.377673] mlx5_core 0000:2d:01.0 enp45s0f0v6: renamed from eth8
```

But in fact, it doesn't. It would rename to `enp45s0f0npf0vf6`, but this name is too long.

So either, there should be an error in the kernel log or a different strategy for such long interface names.

**Comment by yuwata** [comment]
> As you can see, `enp45s0f0npf0vf0` is a pretty long name. Longer than the allowed maximum, which means that renaming will silently fail.

If the generated name is too long, the name will be ignored. systemd-udevd will log that in debug level.
You can see that in by creating the following udev rules:
```
# cat /etc/udev/rules.d/00-debug-net.rules 
SUBSYSTEM=="net", OPTIONS="log_level=debug"
```

> This only gets visible if you debug via `sudo SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/enp45s0f1np1`

As said in the above, you can also get from the debugging logs of systemd-udevd. Also, `udevadm test /sys/class/net/ethX` is your friend.

> The problem is: It fails silently. The kernel log shows
> 
> ```
> [  515.377673] mlx5_core 0000:2d:01.0 enp45s0f0v6: renamed from eth8
> ```
>
> But in fact, it doesn't. It would rename to `enp45s0f0npf0vf6`, but this name is too long.

No, systemd-udevd filters invalid names, and will not try to rename interfaces with such long names.

> So either, there should be an error in the kernel log

The kernel returns error _if_ we try to rename an interface with an invalid name. But we do _not_ try to rename in such case.

> or a different strategy for such long interface names.

As said, `udevadm test /sys/class/net/ethX` is one of the easiest way.

**Comment by yuwata** [comment]
BTW, v252 is too old here, sorry. Please try newer release, or contact to your downstream.

Note, since v256, `udevadm test` shows results in a slightly better form.

Closing.
