### ISSUE TITLE
journalctl --sync should guarantee all currently in flight logs are written to the journal

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#32539]
### Is your feature request related to a problem? Please describe

We currently have a bunch of racy code in our integration tests to check if a message was written to the journal. This is because there's is no command in `journalctl` to wait until all currently in flight logs have been written to the journal. We could implement this by iterating over all open log streams, checking the number of bytes in each stream and only reading up to that amount from the socket. This will guarantee all currently in flight logs have been written to the journal.

**Comment by poettering** [comment]
hmm what's wrong with the existing journalctl --sync? what am i missing?

**Comment by yuwata** [comment]
Yeah, currently `journalctl --sync` does not check stream, and there may be some pending data.

**Comment by yuwata** [comment]
-> #32617.
