### ISSUE TITLE
[networkd] IPv6 setting in `DHCP=` of a bridge interpreted as opposite value?

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#3255]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229 (and possibly earlier)
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> With DHCP=ipv4 or DHCP=no, `Starting DHCPv6 client after NDisc timeout failed: Invalid argument` will not show up for the bridge; Or, it will show up with all of the four possible values (yes, no, ipv4, ipv6)
### In case of bug report: Unexpected behaviour you saw

> With DHCP=ipv4 or DHCP=no, `Starting DHCPv6 client after NDisc timeout failed: Invalid argument` showed up for the bridge and its slave; With DHCP=ipv6 or DHCP=yes, `Starting DHCPv6 client after NDisc timeout failed: Invalid argument` showed up only for its slave
### In case of bug report: Steps to reproduce the problem

> General Configuartion:
> 
> [tom@localhost ~]$ ls /etc/systemd/network/
> br0.netdev  br0.network  enp3s0.network
> [tom@localhost ~]$ cat /etc/systemd/network/br0.netdev 
> [NetDev]
> Name=br0
> Kind=bridge
> [tom@localhost ~]$ cat /etc/systemd/network/enp3s0.network 
> [Match]
> Name=enp3s0
> [Network]
> Bridge=br0
> 
> yes:
> 
> [tom@localhost ~]$ cat /etc/systemd/network/br0.network 
> [Match]
> Name=br0
> [Network]
> DHCP=yes
> [tom@localhost ~]$ journalctl -b -f -p 4 -u systemd-networkd
> -- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
> May 14 20:45:31 localhost systemd-networkd[265]: enp3s0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> ^C
> [tom@localhost ~]$ 
> 
> no:
> 
> [tom@localhost ~]$ cat /etc/systemd/network/br0.network 
> [Match]
> Name=br0
> [Network]
> DHCP=no
> [tom@localhost ~]$ journalctl -b -f -p 4 -u systemd-networkd
> -- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
> May 14 20:47:34 localhost systemd-networkd[262]: enp3s0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> May 14 20:47:34 localhost systemd-networkd[262]: br0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> ^C
> [tom@localhost ~]$ 
> 
> ipv6:
> 
> [tom@localhost ~]$ cat /etc/systemd/network/br0.network 
> [Match]
> Name=br0
> [Network]
> DHCP=ipv6
> [tom@localhost ~]$ journalctl -b -f -p 4 -u systemd-networkd
> -- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
> May 14 20:48:58 localhost systemd-networkd[267]: enp3s0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> ^C
> [tom@localhost ~]$ 
> 
> ipv4:
> 
> [tom@localhost ~]$ cat /etc/systemd/network/br0.network 
> [Match]
> Name=br0
> [Network]
> DHCP=ipv4
> [tom@localhost ~]$ journalctl -b -f -p 4 -u systemd-networkd
> -- Logs begin at Wed 2016-05-04 14:49:19 HKT. --
> May 14 20:50:00 localhost systemd-networkd[264]: br0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> May 14 20:50:00 localhost systemd-networkd[264]: enp3s0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
> ^C
> [tom@localhost ~]$

**Comment by KalelCooper** [comment]
How did you  fix? @tomty89

**Comment by tomty89** [comment]
This bug report is a misinterpretation of #3256/#1982, which are fixed with #3304.

EDIT: You inspired me to file #3399 btw

**Comment by cvmiller** [comment]
I see this issue in version 231. The DHCPv6 client ignores the DHCP=no setting, and if the M-bit is set in the RA, the DHCPv6 client will make a DHCPv6 request.

DHCPv4 does respect the DHCP=no setting.
