### ISSUE TITLE
Intermittent boot failures with systemd segfault

### ISSUE THREAD

**Issue by lots0logs** [systemd/systemd#3259]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch
### In case of bug report: Expected behaviour you didn't see

> System to boot successfully to login screen.
### In case of bug report: Unexpected behaviour you saw

> systemd segfault, boot stalled.
### In case of bug report: Steps to reproduce the problem

> The problem does not happen consistently. Usually simply powering off and on again will boot successfully. I have included links to journal contents from the most recent occurrence of the event where it actually happened twice and then on the third time booted successfully. 

[1st Boot Attempt (FAILED)](http://paste2.org/3Iw744My)
[2nd Boot Attempt (FAILED)](http://paste2.org/xI2Uf3d8)
[3rd Boot Attempt (SUCCESSFUL)](http://paste2.org/3e91vPjX)

**Comment by ohsix** [comment]
you might want to investigate these messages from the fail logs

May 14 13:59:29 dUsTiN-XPS kernel:   Magic number: 0:398:999
May 14 13:59:29 dUsTiN-XPS kernel: system 00:01: hash matches
May 14 13:59:29 dUsTiN-XPS kernel:  pnp0: hash matches

May 14 14:01:44 dUsTiN-XPS kernel:   Magic number: 0:24:41
May 14 14:01:44 dUsTiN-XPS kernel: memory memory77: hash matches

something very wrong is going on with your system as well
May 14 13:59:29 dUsTiN-XPS kernel: traps: systemd[1] trap invalid opcode ip:7fe5ac586b57 sp:7ffcb66019c8 error:0 in libmount.so.1.1.0[7fe5ac55b000+47000]
May 14 13:59:29 dUsTiN-XPS systemd[1]: Caught <ILL>, dumped core as pid 308.
May 14 13:59:29 dUsTiN-XPS systemd[1]: Freezing execution.

when i see vboxdrv i ask people to try without it, you're also using the nvidia binary driver neither are probably relevant until you check out the magic number matches

**Comment by crrodriguez** [comment]
I bet  money this is yet another bug in the virtualbox kernel drivers, which are known to be unreliable.

**Comment by poettering** [comment]
SIGILL? that's quite something. if you run a mainstream kernel (rather than one with zfs and vbox and whatnot), does this happen too?

If it does, are you using any weird compiler or so or some werid compiler settings? SIGILL really suggests some code generation issues.

Either way, this should have resulted in a coredump, any chance you can get the backtrac for it? (coredumpctl should help you...)

**Comment by keszybz** [comment]
Closing because of lack of response.
