### ISSUE TITLE
Not able to add device/event to watch list of systemd-logind

### ISSUE THREAD

**Issue by spikerguy** [systemd/systemd#32590]
### systemd version the issue has been seen with

255.4-1

### Used distribution

Manjaro Linux

### Linux kernel version used

6.8.5-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

` Watching system buttons on /dev/input/event16 8BitDo 8BitDo Ultimate wireless Controller for PC`

### Unexpected behaviour you saw

This device and event does not get added to the watch list.  

I have added the required ENV and TAG to the device which can be seen in the udev log below.

### Steps to reproduce the problem

Added `ENV{ID_INPUT_KEY}=="1", TAG+="power-switch"` to the device Product and Vendor ID.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
udevadm info /dev/input/event16
P: /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-2/3-2:1.0/input/input31/event16
M: event16
R: 16
U: input
D: c 13:80
N: input/event16
L: 0
S: input/by-path/pci-0000:04:00.4-usb-0:2:1.0-event-joystick
S: input/by-id/usb-8BitDo_8BitDo_Ultimate_wireless_Controller_for_PC_E417D8568335-event-joystick
S: input/by-path/pci-0000:04:00.4-usbv2-0:2:1.0-event-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-2/3-2:1.0/input/input31/event16
E: DEVNAME=/dev/input/event16
E: MAJOR=13
E: MINOR=80
E: SUBSYSTEM=input
E: USEC_INITIALIZED=5696426700
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_BUS=usb
E: ID_MODEL=8BitDo_Ultimate_wireless_Controller_for_PC
E: ID_MODEL_ENC=8BitDo\x20Ultimate\x20wireless\x20Controller\x20for\x20PC
E: ID_MODEL_ID=3106
E: ID_SERIAL=8BitDo_8BitDo_Ultimate_wireless_Controller_for_PC_E417D8568335
E: ID_SERIAL_SHORT=E417D8568335
E: ID_VENDOR=8BitDo
E: ID_VENDOR_ENC=8BitDo
E: ID_VENDOR_ID=2dc8
E: ID_REVISION=0114
E: ID_TYPE=generic
E: ID_USB_MODEL=8BitDo_Ultimate_wireless_Controller_for_PC
E: ID_USB_MODEL_ENC=8BitDo\x20Ultimate\x20wireless\x20Controller\x20for\x20PC
E: ID_USB_MODEL_ID=3106
E: ID_USB_SERIAL=8BitDo_8BitDo_Ultimate_wireless_Controller_for_PC_E417D8568335
E: ID_USB_SERIAL_SHORT=E417D8568335
E: ID_USB_VENDOR=8BitDo
E: ID_USB_VENDOR_ENC=8BitDo
E: ID_USB_VENDOR_ID=2dc8
E: ID_USB_REVISION=0114
E: ID_USB_TYPE=generic
E: ID_USB_INTERFACES=:ff5d01:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=xpad
E: ID_PATH_WITH_USB_REVISION=pci-0000:04:00.4-usbv2-0:2:1.0
E: ID_PATH=pci-0000:04:00.4-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_04_00_4-usb-0_2_1_0
E: ID_FOR_SEAT=input-pci-0000_04_00_4-usb-0_2_1_0
E: LIBINPUT_DEVICE_GROUP=3/2dc8/3106:usb-0000:04:00.4-2
E: ID_INPUT_KEY=1
E: DEVLINKS=/dev/input/by-path/pci-0000:04:00.4-usb-0:2:1.0-event-joystick /dev/input/by-id/usb-8BitDo_8BitDo_Ultimate_wireless_Controller_for_PC_E417D8568335-event-joystick /dev/input/by->
E: TAGS=:power-switch:seat:uaccess:
E: CURRENT_TAGS=:power-switch:seat:uaccess:
```

**Comment by poettering** [comment]
hmm, this is a joystick?

we generally only watch for keyboards that have a poweroff/suspend/… key. Does your device even have that?

**Comment by poettering** [comment]
> No the device does not have those keys.

hmm, so why do you care about the power-switch then? i don't follow?

What are you trying to do?

**Comment by spikerguy** [comment]
> > No the device does not have those keys.
> 
> hmm, so why do you care about the power-switch then? i don't follow?
> 
> What are you trying to do?

I want to make the host pc wake up from sleep using a button on the controller. I am in talk with the vendor of the controller to see if they can add POWER_KEY on long press for 5s of the home button on the controller.  That is the reason I asked if we can get Power_key mapped to the firmware of the controller  then will that be enough to get this added to the watch list where we can wake up the host from sleep. 


Without this  approach the wake up method would be to use usb wakeup where it detected device activity and wakes up the host but it is not very smooth and not very precise. 

[Example Video here](https://www.youtube.com/watch?v=Q2tuKK1HXBk)
With this method the host wakes up even when the device is powered down by the user.

**Comment by poettering** [comment]
If an input device with POWER_KEY/SUSPEND_KEY/… shows up logind will watch on it. if it lacks that it will not.

Hence, if you make your device announce those keys things should just work?

**Comment by spikerguy** [comment]
> If an input device with POWER_KEY/SUSPEND_KEY/… shows up logind will watch on it. if it lacks that it will not.
> 
> Hence, if you make your device announce those keys things should just work?

That was my question. Does it need POWER_KEY and SUSPEND_KEY both ? cause looking at the current firmware, I can only request 8bitdo team to add `POWER_KEY` and not totally sure about `SUSPEND_Key`. 

So the question is the same. Does it need both key to be added to watch list or only 1 key is enough ?

Thanks for all the response. Please help me with this question. 
Regards,

**Comment by poettering** [comment]
We need at least one of the following keys announced on the input device: KEY_POWER, KEY_POWER2, KEY_SLEEP, KEY_SUSPEND, KEY_RESTART, SW_LID, SW_DOCK.

If *any* of these is announced by an input device we'll watch it. So if you can make your device generate at least one of them you should be set.
