### ISSUE TITLE
Nondeterministic service restart (sometimes it works and sometimes it doesn't)

### ISSUE THREAD

**Issue by itaywss** [systemd/systemd#3260]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

> service restart not always occurs 
### In case of bug report: Unexpected behaviour you saw

> Nondeterministic service restart (sometimes it works and sometimes it doesn't)
### In case of bug report: Steps to reproduce the problem

> Killing the process (killall -9 node_runner)

I have a system that is comprised of 5 processes (5 services) divided to 2 targets (platform and engine) that should be started in a specific order. In case of an error in any of the 3 processes in the engine target they (all the 3 engine services) should all be stopped and restarted in the correct order.
This restart workflow works every time if the second to start process is killed but not every time the 3rd (and last) process is killed.

Here is the 3rd process service unit file:

`[Unit]
Description=Engine Node.
Requires=engine_adapter.service bridge.service
After=bridge.service engine_adapter.service
BindsTo=bridge.service engine_adapter.service engine.target
OnFailure=crash_notifier.service

[Service]
Type=forking
PIDFile=/tmp/node.pid
User=ubuntu
Group=ubuntu
ExecStartPre=/bin/rm -f /tmp/node.pid
ExecStartPre=/bin/mkdir -p /tmp/igzfs /tmp/igzfs/p1 /tmp/igzfs/p2 /tmp/igzfs/p3 /tmp/igzfs/p4
ExecStart=/home/ubuntu/workspace/engine/zeek/build/x86_64/Debug/node/node_runner -f /home/ubuntu/configs/node_config.json
ExecStopPost=/bin/rm -f /tmp/node.pid
Restart=always
RestartSec=5s

[Install]
RequiredBy=engine.target`

And here are the logs from journal that show this behavior working a couple of times and than stop working:
[node restart.txt](https://github.com/systemd/systemd/files/264914/node.restart.txt)

**Comment by poettering** [comment]
Is this still an issue? Any chance you can get these logs, but with debug logging enabled? i.e. "systemd-analyze set-log-level debug", then reproduce the issue?

**Comment by bl33pbl0p** [comment]
This is most likely related to the restart job racing against the stop job due to the timer expiring when a stop job is running, since it is a conflicting type, and is scheduled by PID 1 as JOB_FAIL, it does not replace your stop job and instead gets failed.

See #11305. There too, the 3rd service is the culprit (since it tries to wake up the other two) and is ordered in a locking manner.
