### ISSUE TITLE
`systemctl disable [--now] someunit@*` gives an error message

### ISSUE THREAD

**Issue by PenelopeFudd** [systemd/systemd#32614]
### systemd version the issue has been seen with

255.4-1.fc40

### Used distribution

Fedora 40

### Linux kernel version used

6.8.7-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

```
# systemctl disable [--now] servicename@\*
  (it should just work)
```

### Unexpected behaviour you saw

```
# systemctl disable [--now] servicename@\*
Glob pattern passed to enable, but globs are not supported for this.
Invalid unit name "servicename@*" escaped as "servicename@\x2a".
```
This was supposedly fixed in https://github.com/systemd/systemd/issues/15620
Here's a workaround:
```
systemctl disable --now $(systemctl show -P Id servicename@\*)
```

### Steps to reproduce the problem

1. `systemctl enable --now servicename@something`
2. `systemctl disable --now servicename@\*`

**Comment by YHNdnzj** [comment]
Please just pass the template unit to `systemctl disable`, rather than a glob. This is not a bug, closing.

**Comment by PenelopeFudd** [comment]
Glob support works fine for `systemctl show`:
```
$ systemctl show -P Id \* | grep -c .
295

$ systemctl show -P Id \*serial\* | grep -c .
32

$ systemctl show -P Id \*serial\*ttyS1\* | grep -c .
11

$ systemctl status \*serial\*ttyS1\* | grep -c Device: 
11

$ systemctl restart \*serial\*ttyS1\* |& grep -c .
11

$ systemctl start \*serial\*ttyS1\* |& grep -c reload
11
```
It may not be a bug, but maybe it should be a feature request: please add glob support to `systemctl disable`.

There doesn't seem to be an obvious reason not to have all the commands support globs, apart from `systemctl enable` because it prints this warning: 
```
$ systemctl start \*serial\*ttyS1\*

Warning: systemctl start called with a glob pattern.
Hint: unit globs expand to loaded units, so start will usually have no effect.
      Passing --all will also load units which are pulled in by other units.
      See systemctl(1) for more details.
```

**Comment by wolfgangkarall** [comment]
@YHNdnzj Hi Mike, any chance to get this reopened?

As it stands, the advice of using the template unit is not good, as it matches all instance units, while using a glob pattern one could only match some units.
