### ISSUE TITLE
Strange results when using sd_device_monitor to monitor USB device events

### ISSUE THREAD

**Issue by sonicbhoc** [systemd/systemd#32632]
### systemd version the issue has been seen with

systemd/jammy-updates,now 249.11-0ubuntu3.12

### Used distribution

Ubuntu Jammy (22.04.4 LTS)

### Linux kernel version used

6.5.0-27-generic

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

I'm using libsystemd 249.11 and trying to use sd_device, sd_device_monitor, and sd_event to monitor USB events, capture the information about the device, and pass the data to callbacks as necessary.

I've observed a few behaviors that I can't explain, and I'm not sure how to mitigate them, or if they're bugs.

First off, the code I'm using to start the event loop:
``` C
void StartLinuxWatcher(UsbDeviceCallback insertedCallback, UsbDeviceCallback removedCallback, int includeTTY)
    {
        InsertedCallback = insertedCallback;
        RemovedCallback = removedCallback;

        if (sd_device_monitor_new(&sddm) < 0)
            return;

        if (sd_device_monitor_filter_add_match_subsystem_devtype(sddm, "usb", "usb_device") < 0)
            return;

        if (includeTTY)
            if (sd_device_monitor_filter_add_match_subsystem_devtype(sddm, "tty", NULL) < 0)
                return;

        if (sd_device_monitor_start(sddm, monitor_handler, NULL) < 0)
            return;

        event = sd_device_monitor_get_event(sddm);

        if (event == NULL)
            return;

        sd_event_loop(event);
    }
```

The callbacks, `sddm`, and `event` are declared outside of the function.

What I'm trying to do is capture information about devices as they're plugged in and removed. The information is as follows:

* Device Name via `sd_device_get_devname`
* System Path via `sd_device_get_syspath`
* Product via `sd_device_get_property_value` with the property `ID_MODEL`
* Product Description `sd_device_get_property_value` with the property `ID_MODEL_FROM_DATABASE`
* Product ID `sd_device_get_property_value` with the property `ID_MODEL_ID`
* Serial Number `sd_device_get_property_value` with the property `ID_SERIAL_SHORT`
* Vendor `sd_device_get_property_value` with the property `ID_VENDOR`
* Vendor Description `sd_device_get_property_value` with the property `ID_VENDOR_FROM_DATABASE`
* Vendor ID `sd_device_get_property_value` with the property `ID_VENDOR ID`

What I expected was the data I queried. What I got: 

* On plug in: Everything except `Serial Number` comes in fine.
* On plug out: `Vendor ID` is not returned on top of `Serial Number` also being blank

### Unexpected behaviour you saw

Now here's where it gets weird. If you plug in a device and *then* start watching events, ***then*** unplug the device, *all* fields are empty except Vendor and Vendor ID, which have garbage data (`//////�` and `�����`, respectively).

On unplug, `Vendor ID` is *always* garbage (`�����`).

### Steps to reproduce the problem

1. Start watching for events using the code above with a USB device already attached.
2. Unplug the device. Observe that most fields are empty, except Vendor and Vendor ID being garbage.
3. Plug a device in. Observe that all data is present and correct except the Serial Number.
4. Plug a device out. Observe that Vendor ID is the only garbage field.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
USB events:
Removed: /dev/bus/usb/001/013 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product: 
        Product Description: 
        Product ID: 
        Serial Number: 
        Vendor: //////�
        Vendor Description:  
        Vendor ID:| 
Removed: /dev/bus/usb/001/013 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product: 
        Product Description: 
        Product ID: 
        Serial Number: 
        Vendor: //////�
        Vendor Description:  
        Vendor ID:����� 
Inserted: /dev/bus/usb/001/014 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product:USB_Optical_Mouse 
        Product Description:M105 Optical Mouse 
        Product ID:c077 
        Serial Number: 
        Vendor: Logitech 
        Vendor Description: Logitech, Inc. 
        Vendor ID:046d 
Inserted: /dev/bus/usb/001/014 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product:USB_Optical_Mouse 
        Product Description:M105 Optical Mouse 
        Product ID:c077 
        Serial Number: 
        Vendor: Logitech 
        Vendor Description: Logitech, Inc. 
        Vendor ID:046d 
Removed: /dev/bus/usb/001/014 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product:USB_Optical_Mouse 
        Product Description:M105 Optical Mouse 
        Product ID:c077 
        Serial Number: 
        Vendor: Logitech 
        Vendor Description: Logitech, Inc. 
        Vendor ID:����� 
Removed: /dev/bus/usb/001/014 /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.2 
Data: 
        Product:USB_Optical_Mouse 
        Product Description:M105 Optical Mouse 
        Product ID:c077 
        Serial Number: 
        Vendor: Logitech 
        Vendor Description: Logitech, Inc. 
        Vendor ID:�����
```

**Comment by sonicbhoc** [comment]
As an aside, I also noticed that I get *two* events for every plug and unplug. Is there a way to prevent that?

**Comment by poettering** [comment]
I don't grok your code. you never allocate an event loop, not sure how anything would work there. Hence sd_device_monitor_get_event() should always return NULL?

**Comment by poettering** [comment]
> As an aside, I also noticed that I get _two_ events for every plug and unplug. Is there a way to prevent that?

my edcuated guess, it's the "add" and "bind" events. i.e. use sd_device_get_action() to see which event it is

**Comment by sonicbhoc** [comment]
> > As an aside, I also noticed that I get _two_ events for every plug and unplug. Is there a way to prevent that?
> 
> my edcuated guess, it's the "add" and "bind" events. i.e. use sd_device_get_action() to see which event it is

Thank you, I'll look into this.



> I don't grok your code. you never allocate an event loop, not sure how anything would work there. Hence sd_device_monitor_get_event() should always return NULL?

No offense, but the documentation for some these libraries is just short of nonexistent.

Doesn't `sd_device_monitor_new` and `sd_device_monitor_start` set up an event loop? If not, how are they supposed to work in relation to `sd_device_monitor_get_event`?

**Comment by sonicbhoc** [comment]
Oh... I'm surprised this code doesn't explode then.

**Comment by sonicbhoc** [comment]
I just need a simple event that runs in its own thread and spits out structures. I'll start by looking at the options available to me in sd_event (which seems to be somewhat better documented) and see what happens. Thank you for taking the time to point me in the right direction.

**Comment by sonicbhoc** [comment]
> > Doesn't `sd_device_monitor_new` and `sd_device_monitor_start` set up an event loop?
> 
> They do not.
> 
> > If not, how are they supposed to work in relation to `sd_device_monitor_get_event`?
> 
> You attach them to an event loop via sd_device_monitor_attach_event(). That event loop you can in turn integrate into another event loop of your choice, see sd_event_get_fd()


So, if I'm using `sd_device_monitor_attach_event`, should I not use `sd_device_monitor_get_event`? What is the purpose of that function?

**Comment by sonicbhoc** [comment]
After starting the event loop myself and attaching the monitor to the event loop using `sd_device_monitor_attach_event`, the results are the same. I'll try to use valgrind next to see what's happening.

**Comment by poettering** [comment]
> I just need a simple event that runs in its own thread

threads you say? i do hope you are not passing around the memory that sd-device gives you pointers to to other threads. sd-device/sd-event/… is not thread-safe (it's threads aware though, i.e. as long as you use an object only from a single thread you are fine), and you must copy out everything you want to pass to other threads.

**Comment by sonicbhoc** [comment]
> > Now here's where it gets weird. If you plug in a device and _then_ start watching events, _**then**_ unplug the device, _all_ fields are empty except Vendor and Vendor ID, which have garbage data (`//////�` and `�����`, respectively).
> > On unplug, `Vendor ID` is _always_ garbage (`�����`).
> 
> smells a lot like a memory corruption in your code. Maybe valgrind the thing?

Yep, turns out I didn't initialize the strings in the structure I'm copying the data to. The structures are now just consistently empty when the device is unplugged. It seems like this is normal though, right?

> > I just need a simple event that runs in its own thread
> 
> threads you say? i do hope you are not passing around the memory that sd-device gives you pointers to to other threads. sd-device/sd-event/… is not thread-safe (it's threads aware though, i.e. as long as you use an object only from a single thread you are fine), and you must copy out everything you want to pass to other threads.

I read that in the documentation. I haven't added threading yet; I'm just trying to get it running the way I expect it to first (and it looks like I just did; no issues reported by valgrind).

**Comment by sonicbhoc** [comment]
I got the application running now. Thank you so much for your help. Unfortunately, I now have to restructure some more of the program I was writing to accommodate for the fact that unplugging a device returns nothing from the `sd_device_get_property_value` functions, but that shouldn't be anywhere near as painful.

**Comment by poettering** [comment]
> Yep, turns out I didn't initialize the strings in the structure I'm copying the data to. The structures are now just consistently empty when the device is unplugged. It seems like this is normal though, right?

Yes, that's correct. When a device goes away we cannot talk to it anymore. Hence most props are gone by then.
