### ISSUE TITLE
Unix socket files stay around when stopping .socket unit

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#32678]
### systemd version the issue has been seen with

255.4

### Used distribution

Fedora 40

### Linux kernel version used

6.8.7-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Unexpected behaviour you saw

Unix socket files created by .socket units are not removed when stopping the unit. This is relatively harmless, as restarting the unit will just re-create it. But it's clutter, and confusing ("huh, the socket is there!?"). Moreover, in our rather more complex situation the socket is owned by a `DynamicUser=true`, and thus is owned by some random anonymous user ID after stopping. Again, not breaking anything as restarting the socket unit fixes the ownership as well.

### Steps to reproduce the problem

Create a trivial socket unit:
```
cat <<EOF > /run/systemd/system/test.socket
[Socket]
ListenStream=/run/test.sock
SocketMode=0600
EOF
cat <<EOF > /run/systemd/system/test.service 
[Service]
Type=oneshot
ExecStart=/bin/true
EOF
```

Start it:
```
systemctl daemon-reload
systemctl start test.socket
ls -l /run/test.sock
```

That shows 
```
srw-------. 1 root root 0 May  7 07:59 /run/test.sock
```
as expected. Stop it again:
```
systemctl stop test.socket
```

Now the socket file `/run/test.sock` still exists. The socket is dead, of course:
```
# curl --unix-socket /run/test.sock http://nohost
curl: (7) Failed to connect to nohost port 80 after 0 ms: Couldn't connect to server
```

**Comment by poettering** [comment]
Set RemoveOnStop=?

**Comment by martinpitt** [comment]
Hah, there's an option for everything, sorry for missing that :see_no_evil: Thanks @poettering !
