### ISSUE TITLE
Document that sd_unref() does not necessarily free a "default" bus, even if no part of the program explicitly refs it, due to queued messages

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#327]
I stumbled on a memory leakage while integrating gmain with sd-bus but I think the problem can happen without gmain. The problem is due to the fact that we do not know if sd-bus is busy when we are disconnecting from the sd-event. 

```
sd_bus_default_system(&bus) // After this call, ref count is 2
sd_event_default(&event)
sd_bus_attach_event(bus, event, SD_EVENT_PRIORITY_NORMAL);
sd_bus_detach_event(bus);
sd_bus_unref (bus); // Ref count for bus got stuck at 1 due to unsent message
```

One propose I have is calling a callback function when we are about to cleanup the sd-bus. In fact maybe similar callback function when we are about to clean up sd-event so we can propagate the cleanup to the higher level callers like `g_source_destroy`.

Am I missing something?

**Comment by daurnimator** [comment]
I too have had this issue.
Associating some sort of cleanup callback with a slot would be great.

**Comment by poettering** [comment]
Hmmm. So the thing is that after queuing a message and unreffing the bus you might later come back and reacquire the bus and then want to write out the queued message. I think it should actually be an OK thing to do: acquire bus + enqueue + unref bus and then expect that the msg is queued and written as soon as somebody dispatches the bus object some time later.

This is unexpected of course. And I figure we should really document the behavour.

The right approach to cover for this logic nicely is to explicilty call sd_bus_close() at the end of your program or sd_bus_flush() wherever appropriate.

**Comment by utezduyar** [comment]
Seems like `bus_reset_queues(bus);` is the magic in `sd_bus_close()`. @poettering do you want me to document this?

**Comment by poettering** [comment]
@utezduyar would be happy to take a patch for that.

**Comment by poettering** [comment]
@daurnimator i'd be willing to take a patch that adds a destroy callback logic to slots, I'd be happy to take it. But I think that should be discussed in a separate issue

**Comment by utezduyar** [comment]
I think there is still a leak. Prior to these calls, my application is issuing sync and async calls. 

```
sd_bus_flush();
sd_bus_detach_event();
sd_bus_unref();
```

This sequence of calls should drop all the references to the bus and force bus to clean itself. But, I noticed the `rqueue` is getting bigger and I noticed that messages are REPLY messages to a previous async call. Then I tried to figure out how these REPLY messages ended up in the rqueue. There are 2 ways, one of them is the `io_callback` in which case we process the message. Other one is `sd_bus_call` where we put the message in the `rqueue` but never get a chance to process it since we are detaching the event loop.

How can we solve this?
- Should we also process the rqueue messages in sd_bus_flush()?

**Comment by poettering** [comment]
Hmm, so, in systemd's own tool we not only use sd_bus_flush(), but sd_bus_close() which resets the queues. I figure that's what you should use too:
1. sd_bus_flush(); /\* write unwritten messages */
2. sd_bus_close(); /\* disconnect and discard unread messages */
3. sd_bus_unref(); /\* drop reference to bus object */

These three steps are neatly packed into _cleanup_bus_close_unref_()... 

I figure we should either add a new call sd_bus_unref_close() which does the three steps above, or start exporting the gcc cleanup help behind _cleanup_bus_close_unref_() as API, or even both.

As first step I think I would be happy to take a patch that adds sd_bus_unref_close() to the API.

**Comment by poettering** [comment]
I prepped a patch for this now in #485. Please have a look.

**Comment by utezduyar** [comment]
Applications can freely use `sd_bus_close` but I believe libraries cannot. I mean, they cannot obtain the bus with `sd_bus_default_system` and then close with `sd_bus_close`.

In that case each library has to have their own connection to the bus with `sd_bus_open_system`.

Am I missing something?

**Comment by dvdhrm** [comment]
Libraries should never care for this. They either must take the bus passed by the application, or they must open their own. But the must never use the default bus! This is global state and thus not available to libraries. In sd-bus it is really just a convenience helper for _applications_, but we explicitly provide an API to avoid this global state.

Edit: ..and if the application passes the default bus to a library, the library must not call close(), but always leave that to the application.

**Comment by utezduyar** [comment]
I don't really agree that libraries are not allowed to use the API to get the default connection. It could be that application is a gdbus applicaiton linking to a sd-bus library. Then all the sudden, bunch of applications need to be changed to pass the default connection. 

It is of course Ok, if the library opens its own connection and makes sure to clean up after itself but that means we will have per library dbus connections. Isn't it more expensive that way?

I am not saying we should do the same but if we look at gdbus, they have an API to give you the default bus, `g_bus_get_sync` without any restriction weather libraries can use it or not.

**Comment by dvdhrm** [comment]
I did not say that applications are not allowed to use the default-bus API. I said 'libraries'! And I stand by that.

We really don't want global state in libraries. If glib does that, ok, then they have to deal with the side-effects. We don't want that.

If you write a library that needs dbus-access, then you should require an sd_bus object passed to your constructor. Optionally, if that bus is NULL, you simply create your own one. But never use sd_bus_default() from a library.

**Comment by utezduyar** [comment]
I have fixed my typo. s/application/library.

**Comment by utezduyar** [comment]
Are we really keeping a global state or sharing a singleton resource in the library?

**Comment by dvdhrm** [comment]
A singleton is global state.

**Comment by utezduyar** [comment]
I gave it another thought and I think you are right that the right way of implementing a library would be by passing the sd-bus to it.

Now I know what to do. My library has to open its own connection to bus and I can suck up the tiny overhead of having extra bus connection per library. It is not an option for me to change my library's API.

But, do you really believe people will follow your paradigm and use the API right way, or people will blast us with questions asking why they cannot use the 'default' connections from the library. If you do believe though, we better document it very nicely and make it very clear about which API libraries are allowed to use.

**Comment by dvdhrm** [comment]
I don't believe people will do what we think is "the right thing". But that's fine. We cannot force them to. So yes, we should document this clearly.

**Comment by utezduyar** [comment]
Seems like what I have been after is sharing a connection with other objects and when time comes just leaving the connection. In that case, doesn't matter if I am using the default connection or any other connection.

We can cancel everything with the slots but cleaning must happen manually. Say I have a ref to the connection (shared with other people) to the bus and I make 10 async calls with slots. Say I decided to leave the bus. In that case I have to make sure all 10 slots are cleaned up before I can exit. Since we keep the references of slots in the sd-bus, I wish we had a marker or something so we can group slots and do the cleanups easily. Or, is this something API users should suck up?

**Comment by poettering** [comment]
I actually think it's fine if libraries use the default bus connection object of a thread. But they should be aware of the consequences, and document that they do what they do, so that the callers know that they have to flush/close the bus.

Or in other words: it's OK to use the default bus logic in libraries as long as the library is written under the assumption that the caller uses sd-bus too, and life-cycles its connection properly. Because the life-cycle is the duty of the main program, not the library.

We should probably document this somewhere...

**Comment by poettering** [comment]
I added more documentation around this in #556. If that's applied, this should really settle the issue.

**Comment by dvdhrm** [comment]
I strongly disagree that libraries are free to use TLVs (which we do for the default-bus). I also dislike hard-coding thread-awareness into libraries. 

I honestly don't see why `sd_bus_default*()` is any better than storing your bus object in your context / manager object. Sure, you get rid of one single context you pass around, but that's how we always designed our applications _and_ libraries.

Where's the problem of requiring an application to pass an `sd_bus*` pointer to the constructor of your library context? It's easy to debug, easy to follow and does not introduce any hidden dependencies. It is immediately clear that the library does not own the bus, but the application does.

It's not like we save thousands of lines of code..

But... eh... maybe this is just personal taste. As long as global state stays optional in our libraries, I don't mind it much.

Closing the issue now, as the original issue is solved.
