### ISSUE TITLE
coredumpctl: add `-n` switch for limiting max number of entries shown

### ISSUE THREAD

**Issue by pmattern** [systemd/systemd#3271]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### Description

The output of `coredumpctl list` cannot be restricted based upon timestamps or number of core dumps. This can be pretty inconvenient e. g. on systems which have been installed long ago like rolling release distributions when it comes to getting an overview of core dumps which have taken place in the not too distant past.

IMO it would be pretty helpful to have an additional option like `-n #` listing the last `#` core dumps and something similar to switch `--since` of `journalctl`.

**Comment by lucaswerkmeister** [comment]
Since v233, `coredumpctl` supports `--since`, `--until` and `--reverse` just like `journalctl`. However, a `-n` option still doesn’t exist.
