### ISSUE TITLE
journalctl: option '--full' only working if combined with distinct other options

### ISSUE THREAD

**Issue by pmattern** [systemd/systemd#3272]
### Submission type
- [x ] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229 on Arch Linux and Debian testing. Can also be seen running 222 on Fedora 23 and 210 on openSUSE Leap 42.1. All versions as provided by the respective distribution.
### Used distribution

(see systemd version)
### Expected behaviour you didn't see

Option `--full` of `journalctl` should have its expected impact on the output no matter whether or not it's combined with other options.
### Unexpected behaviour you saw

The effect of option `--full` can only be seen if it's combined with particular other options. E. g. it does work if combined with `--follow` (`# journalctl --follow --full`) but doesn't if combined with `-b0` or no other option at all.
In case the current behaviour should be the expected one - which wouldn't make any sense, IMO - a note should be added to section `--no-full, --full, -l` of `man 1 journalctl`.
### Steps to reproduce the problem

Invoke `journalctl` as depicted above and look at the output.
### Additional notes

The effect I'm having in mind is long lines getting wrapped.
Lines not fitting in the horizontal space that's available don't get wrapped here, no matter if any of those options `--[no]-full` or `-l` is used or not. Rather, they are kept as one single lengthy line which has to be viewed by e. g. using the horizontal arrow keys which isn't exactly convenient.

The section about those options in `man 1 journalctl` seems a bit odd.
I failed to look up a verb `el[l]ipsize` in dictionaries. The difference between "old" and new option is mentioned in a way I'd consider rather meaningless and not so helpful.

**Comment by poettering** [comment]
That's really just "less" being invoked there. If you don't want "less" to be invoked use "--no-pager". If you want journalctl to invoke "less" with different options, then use `$SYSTEMD_LESS` and set a different set of options. The default for `$SYSTEMD_LESS` is `FRSXMK`. If you drop `S` from it, you should get the behaviour your want.

Note that this is actually documented at the top of the journalctl man page:

>  The output is paged through less by default, and long lines are "truncated" to screen width. The hidden part can be viewed by using the left-arrow and right-arrow keys. Paging can be disabled; see the --no-pager option and the "Environment" section below.

And the "Environment" section documents `$SYSTEMD_LESS` and its default.

Closing, as there's nothing to fix here.

**Comment by archiecobbs** [comment]
This bug is an almost perfect example of what pisses people off about systemd.

> The default for $SYSTEMD_LESS is FRSXMK.

_Why??_

Why should there be any "default" other than nothing?

Systemd here is imposing its own opinion/policy on the best default behavior for `less` (chopping long lines), which is different from the normal default behavior for `less` (wrapping long lines), so now everyone has to go out of their way to find the obscure systemd knob that will make our pagers go back to the normal behavior.

What if one day I came by your house while you were away and painted it orange, and then when you complained, I said, "Stop complaining! All you have to do is go down to city hall and fill out a form and they'll fix it"?

**Comment by poettering** [comment]
@archiecobbs why? because we think it's useful. We copied the behaviour from git's autopaging btw.

**Comment by archiecobbs** [comment]
@poettering apologies for the rant.

First of all, my git (version 2.26.2) doesn't do that... it always wraps lines. On my system `env | grep -E 'LESS|GIT|PAGE'` returns nothing, so this appears to be the default behavior.

In fact (on my system at least) _every other tool_ that does paging wraps long lines; `systemd` is the only one that truncates them. In fact I had no idea `less` had that option until I ran `systemctl status --full`.

So it's just comes across as yet another weird oddity in `systemd`. I'm not anti-systemd, but I do sometimes wonder why, in the ongoing PR battle, it seems to so often needlessly shoot itself in the foot.

And please also take a look at your statement "we think it's useful". I think this goes to the heart of the problem: a feature being useful in your opinion is a great reason to add it to `systemd` itself, but it's not a valid reason to override how a completely different and well-established tool like `less` behaves.

In any case, not expecting you to agree here, just trying to explain my reaction/opinion.

**Comment by archiecobbs** [comment]
FWIW, here's a related question/discussion on unix.stackexchange.com:

https://unix.stackexchange.com/questions/229188/journalctl-how-to-prevent-text-from-truncating-in-terminal
