### ISSUE TITLE
setuid on polkit

### ISSUE THREAD

**Issue by dbergloev** [systemd/systemd#32757]
### systemd version the issue has been seen with

256

### Used distribution

Debian Testing

### Linux kernel version used

6.6.15

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Since `run0` was introduced as a replacement for `sudo` on the grounds that `setuid` is a security risk, I expected this to work on a system with `setuid` disabled. 

### Unexpected behaviour you saw

It seams that polkit depends on `setuid` and thereby `run0` will depend on and use it indirectly. This would mean that the whole idea of `run0` is mot, which I hope is not the case. I like the idea and have never really been a big fan of the setuid concept. But in order to be a valid replacement for the `setuid` method, it needs to work on systems with this "feature" disabled. Otherwise there is no reason for it to exist. 

### Steps to reproduce the problem

1. Install version 256, or just use `systemd-run` directly. 
2. Setup polkit rule to allow a group to elevate it's privileges.
3. Mount `/` with the `nosuid` option.
4. Try invoking `run0` as a normal user in the allowed group.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
polkit-agent-helper-1: needs to be setuid root
Error: Incorrect permissions on /usr/lib/polkit-1/polkit-agent-helper-1 (needs to be setuid root)
==== AUTHENTICATION FAILED ====
Failed to start transient service unit: Access denied
```

**Comment by arvidjaar** [comment]
> ```shell
> polkit-agent-helper-1: needs to be setuid root
> ```

How is it systemd problem? Should not it be reported to polkit project?

Unless you suggest replacing polkit with completely different implementation.

**Comment by dbergloev** [comment]
> How is it systemd problem? 

For starters the claim that is made `One key difference: it's *not* in fact SUID`. Well yes it is when you drag dependencies into it that depends on it. When invoking `run0` the `setuid` is required and it will not work with it disabled. 

 > Should not it be reported to polkit project?

Why? Polkit never claimed to be a non-setuid tool and I am pretty sure that this is intentional. 

 > Unless you suggest replacing polkit with completely different implementation.

Depends. `systemd-run` has other advantages that I find even more useful than the `setuid` claim, but if you want to advertise something, you best make sure that your claims are valid. In this case the `KEY` argument is that `setuid` is a security risk and `run0` fixes this by not being depended on it, which is false. 

Maybe I am missing something, maybe there are other ways to configure it? I just know that if I disable `setuid`, then `systemd-run` stops working. This does not allign with the claim that `run0` is an alternative to `setuid` tools like `sudo`.

**Comment by YHNdnzj** [comment]
This was brought up in the original issue discussing about the potential implementation of `run0`: https://github.com/systemd/systemd/issues/29199#issuecomment-1864616020.

But still, this is not _our bug_. I do agree that statements like "setuid can be fully disabled with run0" are pretty misleading, but that kind of advertisement never appeared in the _systemd codebase_.

**Comment by dbergloev** [comment]
@YHNdnzj  
> but that kind of advertisement never appeared in the systemd codebase

[run0.xml](https://github.com/systemd/systemd/blob/v256-rc1/man/run0.xml)

 > No SetUID/SetGID file access bit functionality is used for the implementation.

Kind of a gray area in this statement as it's technically correct, depending on how you look at the concept if "implementation". I would still argue that it's misleading as most will and have assumed that `setuid` is never a part of the equation. 

Especially when combined with the next part:

> Altogether this should provide a safer and more robust alternative to the sudo mechanism, in particular in OS environments where SetUID/SetGID support is not available

Which firmly states that this can operate without `setuid` and is one of the `key` areas where it enhances security, among other things.

Again, I like `systemd-run` and do believe it's a much cleaner, correct and safer way _(in other areas)_ of doing this. But the key focus everywhere, including it's own docs is the `setuid` topic, which is simply wrong, so long as it requires dependencies that cannot operate without the use of it.

**Comment by bluca** [comment]
Bring this to the polkit tracker as an RFE, there's nothing that can be done here. Also note that unlike sudo, polkit's suid binary will not process and run untrusted user payloads, so it's a very, very different situation

**Comment by bluca** [comment]
In fact as pointed out by Mike there's already an RFE that provides two possible solutions, so you can start working on that immediately if you want to: https://gitlab.freedesktop.org/polkit/polkit/-/issues/168

**Comment by dbergloev** [comment]
I think you have the wrong idea here. 

1. I am not saying that the problem lies with `setuid` being used by polkit. I am saying that the docs and general information being thrown around that this is a non-setuid solution is wrong. 
2. If we are talking about the security issues with `setuid`, there is no differenc between `sudo` and `polkit` no mater how long they operate or what tasks they provide. The issue with `setuid` is the fact that it allows ANY program to run with highest privileges with the only safeguard being a single bit flag.

Once you launch a root shell, whether this be with `sudo` or `run0`, that shell is there to stay. Security wise there is no difference. But by having a way to elevate privileges without the need for `setuid` you can completely eliminate it from a system and that is where the security would be enhanced.

**Comment by bluca** [comment]
Once again, you are wasting your time, arguing on this bug tracker is not going to achieve anything, you'd be better off spending the time to implement the linked polkit RFE instead

**Comment by MaxHearnden** [comment]
The polkit project has also migrated over to github, the new RFE is at https://github.com/polkit-org/polkit/issues/169

**Comment by nl255** [comment]
> Bring this to the polkit tracker as an RFE, there's nothing that can be done here. Also note that unlike sudo, polkit's suid binary will not process and run untrusted user payloads, so it's a very, very different situation

Would it not be possible to have systemd provide it's own suid helper or even something like systemd-policytoolbox to replace polkit completely since they don't really seem interested in eliminating the setuid requirement?

**Comment by bluca** [comment]
No, we very much do not want to reimplement polkit, please do the work and submit a PR on the polkit repository instead if you want this to be solved

**Comment by dbergloev** [comment]
It's funny how people keep misunderstand the main issue. Yes it could be awesome to rid the OS of setuid, but this is so integrated into most tools, I do not see this happening anytime soon. Currently you will have something break if you disable it, and not just polkit. 

This is a documentation issue mainly, but I am tired of trying to explain it so I will instead provide [This Link](https://github.com/dbergloev/runas/blob/main/README.md)

Again, I see many benefits of what this is attempting to do, but the current state makes little sense in other areas and the documentation is wrong.

**Comment by bluca** [comment]
> It's funny how people keep misunderstand the main issue.

No, it is you who are misunderstood. There is a huge difference between a setuid program that is invoked by untrusted code, and a setuid program that is invoked exclusively by a trusted component, with no untrusted data. The polkit agent is invoked by polkit, with well-defined data passed back and forth, and it is not called by individual users, and it is not used to chain to untrusted, external executables, like sudo and doas are doing. So while of course it would be ideal to have a system that is completely devoid of setuid binaries, not having them in the user execution path is already a gigantic step forward, and making perfect the enemy of good is counter productive.
