### ISSUE TITLE
systemd.path: DirectoryNotEmpty doesn't trigger for files starting with .

### ISSUE THREAD

**Issue by antifuchs** [systemd/systemd#32751]
### systemd version the issue has been seen with

255

### Used distribution

NixOS 23.11

### Linux kernel version used

6.6.30

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I have a systemd.path defined with a clause `DirectoryNotEmpty=/data/transfers/ready` - when a regular file with any name at all gets created in the directory, a transfer should be triggered. I was expecting files matching any glob pattern, visible or hidden, to trigger the `trigger-transfer.service` to be started.

### Unexpected behaviour you saw

I do see the `trigger-transfer.service` being started for regular files starting with any character that isn't the `.` - but "hidden" / "dot" files like `.foo` inside the directory do not start the service.

### Steps to reproduce the problem

1. Make a unit like the following:
```systemd
# /etc/systemd/system/trigger-transfer.path
[Path]
DirectoryNotEmpty=/data/transfers/ready
Unit=trigger-transfer.service

[Install]
WantedBy=multi-user.target
```
2. Create a oneshot unit named `trigger-transfer.service` (not shown)
3. Run `touch /data/transfers/ready/foo` - the service gets started
4. Run `touch /data/transfers/ready/.foo` - the service does not get started.

**Comment by YHNdnzj** [comment]
This is intended behavior, and it's consistent with `ConditionDirectoryNotEmpty=`: https://github.com/systemd/systemd/issues/23220.

But such behavior is not documented, which is something we should fix.

**Comment by antifuchs** [comment]
Ah, that makes sense. Is there a way to opt into hidden files triggering a start? (Documented or undocumented...)
