### ISSUE TITLE
ukify-generated efi file not recognized by bootctl and kernel-install

### ISSUE THREAD

**Issue by equaeghe** [systemd/systemd#32774]
### systemd version the issue has been seen with

255.4

### Used distribution

Gentoo

### Linux kernel version used

6.6.30-gentoo

### CPU architectures issue was seen on

x86_64

### Component

bootctl, kernel-install, systemd-boot

### Expected behaviour you didn't see

My ukify-generated efi files are not recognized by `bootctl` and `kernel-install`. Namely

- `bootctl list` shows details about them
- `bootctl unlink` works
- `kernel-install remove` works

### Unexpected behaviour you saw

- Most invocations of `bootctl` and `kernel-install` show an error/warning in yellow for each of my ukis, which looks as follows:
      
      Parsed PE file '/boot/EFI/Linux/<uki filename>.efi' is not a UKI.

- The output of `bootctl list` for my ukis is listed as `(reported/absent)`:

        type: Reported by Boot Loader
       title: <uki filename>.efi (reported/absent)
          id: <uki filename>.efi
      source: /sys/firmware/efi/efivars/LoaderEntries-<some uuid>

- `bootctl unlink` does not work, i.e., the selected uki is not unlinked/removed (autocompletion of kernels works, no error message shown)
- `kernel-install remove` does not work, i.e., no uki can be selected using autocomplete

### Steps to reproduce the problem

- configure kernel (particularities: no initrd, kernel command line options embedded in-kernel)
- `make`
- `make modules_install && make install`
- reboot into new kernel (no problem, systemd-boot works as expected)
- do any of the actions involving `bootctl` or `kernel-install` mentioned above

**Comment by poettering** [comment]
we consider kernels UKIs (in context of sd-boot and its tools) that carry at least: .kernel, .osrel, .initrd. Do your kernels have that?

**Comment by equaeghe** [comment]
> we consider kernels UKIs (in context of sd-boot and its tools) that carry at least: .kernel, .osrel, .initrd. Do your kernels have that?

There is no initrd. Having one seems like a strange requirement; in my 20 year's experience running linux installations (desktop, laptop, VPS), I've never needed and used one (I realize most people do use one). The generated UKIs boot fine.

Obviously, I can't expect `bootctl` to say anything sensible about an initrd resource that isn't there, but that seems quite unrelated to the management of UKIs with `bootctl unlink` and `kernel-install remove`. Even most of the output of `bootctl list` should be unaffected. _Would it be possible to deal with the lack of of an .initrd resource in a more refined manner?_ (Bailing out only if and when an `.initrd` is really required, otherwise producing some ‘.initrd resource missing’ output instead of the actual output that would be generated when an initrd would be present.) It would make sd-boot and its tools more widely applicable.

Possibly related/relevant:

- https://github.com/uapi-group/specifications/blob/main/specs/unified_kernel_image.md (no `.initrd` required)
- https://github.com/uapi-group/specifications/pull/103

**Comment by yuwata** [comment]
-> #32855
