### ISSUE TITLE
systemd: change default namespaces

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#32795]
### Component

systemd

### Is your feature request related to a problem? Please describe

When using vms and containers it is kinda annoying to have all of the guests interfaces and bridges within the hosts network namespace. Not only does it clutter the output of e.g. "ip addr" but also adds a lot of work to avoid services and network managers from tinkering with them (and breaking the network connectivity of the guests).

The easiest "fix" for this would be being able to change the default network namespace of systemd to something else and only start manually configured services (e.g. openvswitch and libvirt in my case) within the original root network namespace.

This also increases security:
* It prevents later connected network devices from showing up in the host (LAN turtle based attacks)
* It allows a corporate vpn tunnel to be established before any application is able to access the network (including accidentally)
* host applications and services cannot accidentally tamper with guest traffic and interfaces (no complex configuration to exclude these interfaces; e.g. listening on all interfaces will be restricted to the actual host ones and automatically exclude all of the plumbing)

### Describe the solution you'd like

Systemd-init should be able to use a different/isolated default network namespace for all services (except one or two specific user configured ones) in a separate network namespace (nsenter itself into a clean one before starting services, similar to `PrivateNetwork=true` on a single service unit but for systemd-init).
This way all interfaces regardless of when they're going to be attached (e.g. docking stations or usb-to-lan) will only be visible within the namespace of openvswitch.

This also allows systemd-networkd to be more cleanly separated from these interfaces (it will only see the interfaces it is intended to see and not also the guest interfaces of e.g. libvirt for attaching to openvswitch).

(the issue of handling connecting/disconnecting to wifi networks shall be excluded here for now, esp. as systemd-networkd also outsourced this part too, so it is probably outside of the scope of systemd currently anyway. For now it can be considered to be "outsourced" to another software within the outer network namespace.)

An example startup:
1. systemd-boot creates a private network namespace (only the lo interface exists).
2. systemd-boot starts systemd-init within the newly created private network namespace.
3. systemd-init starts services (boots the host)
4. systemd-init reaches the point where it starts the openvswitch and libvirt service which have been configured by the user to run in the outer namespace 
5. openvswitch configures its virtual switch
6. libvirt starts VMs and thereby causes the guest network interfaces to be created and joined to the openvswitch
7. something will create a network interface within systemd-inits network namespace aka something like "ip link set someVirtualIf netns inner_ns" is called within the outer namespace.
8. systemd-udevd will detect a new interface having been created ("someVirtualIf") and trigger systemd-networkd
9. systemd-networkd will configure someVirtualIf as usual

### Describe alternatives you've considered

1. try injecting a `PrivateNetwork=true` into systemd-boot before it starts the regular systemd-init.
2. modify systemd-boot to have it nsenter into a clean network namespace before starting the normal systemd-init within it.
3. have systemd-boot start a single systemd-nspawn vm instead of continuing normally (current host would then be within nspawn) and have some slimed down "os" with only openvswitch and libvirt outside.
4. putting all physical interfaces and openvswitch into a separate namespace => causes issues on boot as interfaces will first be within the wrong namespace and generally complicates network setup because of being detected as "up" too soon.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by bluca** [comment]
You can already add top-level drop-ins with settings that apply to all units by default unless explicitly set, so this is already implemented:

https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#:~:text=Units%20also%20support%20a%20top%2Dlevel%20drop%2Din%20with

**Comment by agowa** [comment]
@bluca then it's a docks issue because I read that page and re-read it just now and I still don't get how it works without creating a dropin file for each and every single service.
