### ISSUE TITLE
hostname set-hostname failed: Could not set property: Access denied

### ISSUE THREAD

**Issue by Syx5290** [systemd/systemd#32803]
### systemd version the issue has been seen with

root@kylin10:/etc# systemctl --version systemd 245 (245.4-4kylin3.11k33) +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

### Used distribution

Ubuntu 20.04

### Linux kernel version used

5.4.18-63.52-e2000-rc17-generic

### CPU architectures issue was seen on

aarch64

### Component

journalctl

### Expected behaviour you didn't see

root@kylin10:/etc# hostnamectl set-hostname test

### Unexpected behaviour you saw

root@kylin10:/etc# hostnamectl set-hostname test
Could not set property: Access denied
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname kylin10
Could not set property: Access denied
root@kylin10:/etc#

### Steps to reproduce the problem

The first time setting a different name did not work, it worked on the second attempt.
root@kylin10:/etc# hostnamectl set-hostname test
Could not set property: Access denied
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname test
root@kylin10:/etc# hostnamectl set-hostname kylin10
Could not set property: Access denied
root@kylin10:/etc#

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@kylin10:/etc/selinux# journalctl -f -u systemd-hostnamed
-- Logs begin at Thu 1970-01-01 08:00:06 CST. --
5月 14 16:23:48 test systemd-hostnamed[872266]: Failed to write static host name: Permission denied
5月 14 16:24:18 test systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:28:41 test systemd[1]: Starting Hostname Service...
5月 14 16:28:42 test systemd[1]: Started Hostname Service.
5月 14 16:28:42 test systemd-hostnamed[874612]: Failed to write static host name: Permission denied
5月 14 16:29:12 test systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:29:31 test systemd[1]: Starting Hostname Service...
5月 14 16:29:32 test systemd[1]: Started Hostname Service.
5月 14 16:29:32 kylin10 systemd-hostnamed[875067]: Changed host name to 'kylin10'
5月 14 16:30:02 kylin10 systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:38:08 kylin10 systemd[1]: Starting Hostname Service...
5月 14 16:38:09 kylin10 systemd[1]: Started Hostname Service.
5月 14 16:38:09 ceaedge1000-4661715392531405 systemd-hostnamed[879351]: Failed to write static host name: Permission denied
5月 14 16:38:09 ceaedge1000-4661715392531405 systemd-hostnamed[879351]: Changed host name to 'ceaedge1000-4661715392531405'
5月 14 16:38:39 ceaedge1000-4661715392531405 systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:39:15 ceaedge1000-4661715392531405 systemd[1]: Starting Hostname Service...
5月 14 16:39:15 ceaedge1000-4661715392531405 systemd[1]: Started Hostname Service.
5月 14 16:39:15 ceaedge1000-4661715392531405 systemd-hostnamed[879940]: Failed to write static host name: Permission denied
5月 14 16:39:45 ceaedge1000-4661715392531405 systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:54:01 ceaedge1000-4661715392531405 systemd[1]: Starting Hostname Service...
5月 14 16:54:01 ceaedge1000-4661715392531405 systemd[1]: Started Hostname Service.
5月 14 16:54:01 ceaedge1000-4661715392531405 systemd-hostnamed[886558]: Failed to write static host name: Permission denied
5月 14 16:54:52 ceaedge1000-4661715392531405 systemd[1]: systemd-hostnamed.service: Succeeded.
5月 14 16:54:58 ceaedge1000-4661715392531405 systemd[1]: Starting Hostname Service...
5月 14 16:54:58 ceaedge1000-4661715392531405 systemd[1]: Started Hostname Service.
5月 14 16:54:58 kylin10 systemd-hostnamed[887035]: Changed host name to 'kylin10'
5月 14 16:55:07 ceaedge1000-4661715392531405 systemd-hostnamed[887035]: Failed to write static host name: Permission denied
5月 14 16:55:14 kylin10 systemd-hostnamed[887035]: Failed to write static host name: Permission denied
5月 14 16:55:19 test systemd-hostnamed[887035]: Failed to write static host name: Permission denied
5月 14 16:55:35 ceaedge1000-4661715392531405 systemd-hostnamed[887035]: Failed to write static host name: Permission denied
5月 14 16:55:48 test systemd-hostnamed[887035]: Failed to write static host name: Permission denied
```

**Comment by xuegege5290** [comment]
root@kylin10:/etc# hostnamectl status
   Static hostname: test
Transient hostname: kylin10
         Icon name: computer
        Machine ID: 2538324fcbdc45768c09a59c1047a90e
           Boot ID: e37483bab8174fd68095d0f2870acd08
            Kernel: Linux 5.4.18-63.52-e2000-rc17-generic
      Architecture: arm64

**Comment by yuwata** [comment]
Sorry, v245 is too old here. Please contact to the downstream, or try to reproduce the issue with a recent release or the current git HEAD. Closing.
