### ISSUE TITLE
systemd-networkd defined bridge in no-carrier state

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#32831]
### systemd version the issue has been seen with

systemd 255 (255.6-1.fc40)

### Used distribution

Fedora 40

### Linux kernel version used

6.8.9-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd, systemd-nspawn

### Expected behaviour you didn't see

I use a custom configuration for my systemd-nspawn containers, that creates bridges with static IP addresses.
My configurations seem to completley fail on the most recend Fedora release, my nspawn containers get no networking.

When creating a br0 minimal-testing bridge interface using `systemd-networkd`, the bridge interface does not get a carrier even when configured - as far as i can tell - correctly. So this issue seems to persists on various configurations.

### Unexpected behaviour you saw

Systemd-networkd defined bridge beeing in no-carrier DOWN state.

And the main issue for me, nspawn containers configured to use a bridge get no network connection at all. Instead of enslaved, they get degraded operational state.

### Steps to reproduce the problem

1. Create the configuration files in `/run/systemd/network`.
2. Reload `systemd` configurations.
3. Restart `systemd-networkd`.
4. Verify the bridge interface status.

### /run/systemd/network/br0.netdev
```ini
[NetDev]
Name=br0
Kind=bridge
```

### /run/systemd/network/br0.network
```ini
[Match]
Name=br0

[Network]
IPMasquerade=ipv4
Address=10.60.1.1/24
ConfigureWithoutCarrier=yes
```

### /run/systemd/network/dummy0.netdev
```ini
[NetDev]
Name=dummy0
Kind=dummy
```

### /run/systemd/network/dummy0.network
```ini
[Match]
Name=dummy0

[Network]
Address=192.0.2.1/24
```

### /run/systemd/network/br0.link
```ini
[Match]
Name=br0

[Network]
Bridge=dummy0
```

## Apply the Configuration

1. Reload systemd configurations:
   ```sh
   systemctl daemon-reload
   ```

2. Restart systemd-networkd service:
   ```sh
   systemctl restart systemd-networkd
   ```

3. Bring up the interfaces manually if necessary:
   ```sh
   ip link set br0 up
   ip link set dummy0 up
   ```

4. Verify the status of the bridge interface:
   ```sh
   ip link show br0
   ```

## Expected Behavior

The bridge interface `br0` should come up and have a carrier, indicating it is operational.

## Actual Behavior

The bridge interface `br0` shows `NO-CARRIER` and remains in the `DOWN` state.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@p2:/run/systemd/network# ip addr
...
3: 10.60.0.x: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether e2:56:21:32:cf:ab brd ff:ff:ff:ff:ff:ff
    inet 10.60.0.1/24 brd 10.60.0.255 scope global 10.60.0.x
       valid_lft forever preferred_lft forever
6: 60-0-2@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b2:1a:81:f8:5b:8f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b01a:81ff:fef8:5b8f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
7: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 4e:78:95:9a:e5:55 brd ff:ff:ff:ff:ff:ff
    inet 10.60.1.1/24 brd 10.60.1.255 scope global br0
       valid_lft forever preferred_lft forever
8: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether c6:0d:0f:d1:95:75 brd ff:ff:ff:ff:ff:ff
    inet 192.0.2.1/24 brd 192.0.2.255 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::c40d:fff:fed1:9575/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever

root@p2:/run/systemd/network# networkctl
IDX LINK        TYPE     OPERATIONAL SETUP     
  1 lo          loopback carrier     unmanaged
  2 enp7s0      ether    routable    configured
  3 10.60.0.x   bridge   no-carrier  configured
  5 tun-hostnet none     routable    unmanaged
  6 60-0-2      ether    degraded    unmanaged
  7 br0         bridge   no-carrier  configured
  8 dummy0      ether    routable    configured

root@p2:/run/systemd/network# networkctl status
● Interfaces: 1, 5, 6, 3, 7, 8, 2
       State: routable                               
Online state: partial                                
     Address: 5.9.208.167 on enp7s0
              10.60.0.1 on 10.60.0.x
              10.15.60.1 on tun-hostnet
              10.60.1.1 on br0
              192.0.2.1 on dummy0
              fe80::9e6b:ff:fe2f:460c on enp7s0
              fe80::2101:d908:e0ae:c8e on tun-hostnet
              fe80::b01a:81ff:fef8:5b8f on 60-0-2
              fe80::c40d:fff:fed1:9575 on dummy0
     Gateway: 5.9.208.161 on enp7s0
         DNS: 185.12.64.1
              185.12.64.2
```

**Comment by LaKing** [comment]
```
May 15 04:09:18 p2.d250.hu systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: 10.60.0.x: Configuring with /run/systemd/network/br-10.60.0.x.network.
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: br0: Configuring with /run/systemd/network/br0.network.
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: dummy0: Configuring with /run/systemd/network/dummy0.network.
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: br0: Link UP
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: dummy0: Link UP
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: dummy0: Gained carrier
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: enp7s0: DHCPv4 address 5.9.208.167/28, gateway 5.9.208.161 acquired from 188.40.24.199
May 15 04:09:18 p2.d250.hu systemd-networkd[15063]: dummy0: Gained IPv6LL
May 15 04:09:18 p2.d250.hu systemd[1]: Finished systemd-networkd-wait-online.service - Wait for Network to be Configured.
```

**Comment by LaKing** [comment]
I think this issue started to develop itself years ago, and escalated now.
https://github.com/systemd/systemd/issues/9252#issuecomment-808710185

On previous versions/other instances that got upgraded over the years, I've seen this happening but after a couple of container restarts i got them somehow working.

This is now a new installation of fedora 40, and I simply can not get it to work - even with the workarounds mantioned on that thread.

**Comment by yuwata** [comment]
(Off topic: you do not need `systemctl daemon-reload` when only .network and/or .netdev files are modified. These are only used for systemd-networkd, but `daemon-reload` is for PID1.)

**Comment by yuwata** [comment]
> ### /run/systemd/network/br0.link
> 
> ```ini
> [Match]
> Name=br0
> 
> [Network]
> Bridge=dummy0
> ```

What? This should be misconfiguration. `Bridge=br0` should be in .network for `dummy0`.

**Comment by LaKing** [comment]
@yuwata Sorry, tried to create a minimal reproduction configuration with some help from chatGPT. 
I think I have corrected it now.

```
for f in *; do echo -e "\n$(pwd)/$f\n" && cat $f; done

/run/systemd/network/br0.netdev

[NetDev]
Name=br0
Kind=bridge
/run/systemd/network/br0.network

[Match]
Name=br0

[Network]
IPMasquerade=ipv4
Address=10.60.1.1/24
ConfigureWithoutCarrier=yes

/run/systemd/network/br-10.60.0.x.netdev

## srvctl generated
[NetDev]
Name=10.60.0.x
Kind=bridge

#MACAddress=e2:56:21:32:cf:ab
/run/systemd/network/br-10.60.0.x.network

## srvctl generated
[Match]
Name=10.60.0.x

[Network]
IPMasquerade=ipv4
Address=10.60.0.1/24
ConfigureWithoutCarrier=yes

#[Link]
#ActivationPolicy=always-up

/run/systemd/network/dummy0.netdev

[NetDev]
Name=dummy0
Kind=dummy

/run/systemd/network/dummy0.network

[Match]
Name=dummy0

[Network]
Bridge=dummy0
Address=10.60.1.2/2
```
`ip addr`

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 9c:6b:00:2f:46:0c brd ff:ff:ff:ff:ff:ff
    inet 5.9.208.167/28 metric 1024 brd 5.9.208.175 scope global dynamic enp7s0
       valid_lft 42921sec preferred_lft 42921sec
    inet6 fe80::9e6b:ff:fe2f:460c/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
3: 10.60.0.x: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether e2:56:21:32:cf:ab brd ff:ff:ff:ff:ff:ff
    inet 10.60.0.1/24 brd 10.60.0.255 scope global 10.60.0.x
       valid_lft forever preferred_lft forever
5: tun-hostnet: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.15.60.1/24 scope global tun-hostnet
       valid_lft forever preferred_lft forever
    inet6 fe80::2101:d908:e0ae:c8e/64 scope link stable-privacy proto kernel_ll 
       valid_lft forever preferred_lft forever
6: 60-0-2@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b2:1a:81:f8:5b:8f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b01a:81ff:fef8:5b8f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
7: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 4e:78:95:9a:e5:55 brd ff:ff:ff:ff:ff:ff
    inet 10.60.1.1/24 brd 10.60.1.255 scope global br0
       valid_lft forever preferred_lft forever
8: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether c6:0d:0f:d1:95:75 brd ff:ff:ff:ff:ff:ff
    inet 10.60.1.2/24 brd 10.60.1.255 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::c40d:fff:fed1:9575/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```
Pinging with the `ping -I dummy0 10.60.1.1` just hangs.

What I'm trying to do is to have a minimal config for a bridge and an interface connected to it to test the bridge for connectivity, so it can be reproduced. The 10.60.0.x interface is my actual bridge ofr the nspawn containers.

**Comment by arvidjaar** [comment]
> /run/systemd/network/dummy0.network
> 
> [Match]
> Name=dummy0
> 
> [Network]
> Bridge=dummy0
> Address=10.60.1.2/2

Interface that is "plugged into" bridge cannot have IP address.


> 7: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
>     link/ether 4e:78:95:9a:e5:55 brd ff:ff:ff:ff:ff:ff
>     inet 10.60.1.1/24 brd 10.60.1.255 scope global br0
>        valid_lft forever preferred_lft forever
> 8: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/ether c6:0d:0f:d1:95:75 brd ff:ff:ff:ff:ff:ff
>     inet 10.60.1.2/24 brd 10.60.1.255 scope global dummy0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::c40d:fff:fed1:9575/64 scope link proto kernel_ll 
>        valid_lft forever preferred_lft forever

`dummy0` is not added to any bridge, `br0` does not have any interfaces so it is `DOWN`. Bridge cannot have carrier until it has  at least one slave interface with carrier.

The only question to systemd is how it interprets this contradictory `dummy0.network`.

> chatGPT

Oh.

**Comment by LaKing** [comment]
Oh sorry, I overlooked this, it was late. ...

Okay, I changed the dummy interface to Bridge br0 then to 10.60.0.x and was able to get both bridges up with the dummy interface.
After that, the nspawn containers attached to those bridges already UP, communicate fluently over the virtual network. ...

The strange thing is, now I'm unable to reproduce the original problem.
Even with the dummy deleted, now the bridges with the containers get connected without any problems.
Also, newly created bridges get up now with the containers connected, and without the dummy.
Even after reboots, .. it is like if the original problem never existed.

I will test on my other systems. ...

@arvidjaar what would be the recommended way to test a bridge with a simple interface that is "plugged into" a bridge, and has an IP address. What might bring me closer to debug the problem is to narrow down the problem, and for that i would like to create a bridge and and something attached to it that can ping the bridge, without running an nspawn container.
Goal would be to find out if this is somewhere in networkd or in nspawn / be it in my configs or somwhere else.

**Comment by yuwata** [comment]
OK, then please discuss further in our Matrix channel if necessary. Closing.

**Comment by TGKx** [comment]
If you want to get a bridge without connected interfaces working under systemd 255+ you can try adding "MACAddress=none" to the [NetDev] section of your .netdev file.

From the docs:

MACAddress=
           Specifies the MAC address to use for the device, or takes the special value "none". When "none", systemd-networkd does not request the MAC address for the device, and the kernel will assign a random MAC address. For "tun", "tap", or "l2tp" devices, the MACAddress= setting in the [NetDev] section is not supported and will be ignored. Please specify it in the [Link] section of the corresponding systemd.network(5) file. If this option is not set, "vlan" device inherits the MAC address of the master interface. For other kind of netdevs, if this option is not set, then the MAC address is generated based on the interface name and the machine-id(5).

Note, even if "none" is specified, systemd-udevd will assign the persistent MAC address for the device, as 99-default.link has MACAddressPolicy=persistent. So, it is also necessary to create a custom .link file for the device, if the MAC address assignment is not desired.
