### ISSUE TITLE
User sessions take longer to log out with systemd 256

### ISSUE THREAD

**Issue by jelly** [systemd/systemd#32845]
### systemd version the issue has been seen with

256~rc2

### Used distribution

Arch Linux && Fedora Rawhide

### Linux kernel version used

6.8.9-arch1-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

In Cockpit we allow admins to terminate a users session via a button which calls `loginctl terminate-user $username`. We hide this button by detecting if a user is no longer logged in by watching `/var/run/utmp` and then calling `w -h` to determine which users are logged in.

Our test now fails as waiting for the button to change to disabled takes longer then our timeout (15 seconds). I tried bumping this to 60 seconds but then the test still fails. 

While waiting on the test I can see that `loginctl list-sessions` keeps a manager session around for a while for the admin user.

### Steps to reproduce the problem

I tried to reproduce this with an ssh session but did not succeed. So I tried to reproduce what our test does, while having two root terminals open watching changes on /var/run/utmp and one watching `w -h`.

When I log in to Cockpit I get a session as expected:
```
[root@archlinux ~]# loginctl list-sessions
SESSION  UID USER  SEAT LEADER CLASS         TTY         IDLE SINCE
      1    0 root  -    433    user          pts/0       no   -
     11 1000 admin -    857    user          web console no   -
     12 1000 admin -    863    manager       -           no   -
      2    0 root  -    439    manager-early -           no   -
      6    0 root  -    551    user          pts/2       no   -
```

Now I setup a watcher for changes on utmp
```
inotifywait -m /var/run/utmp | while read -r _dir _action file; do date; echo "changed"; done    
```
And watch the logged in session:
```
watch -n 1 "w -h"
```

After I logout I see:
```
Setting up watches.
Watches established.
Wed May 15 01:43:54 PM UTC 2024
changed
```

```
Every 1.0s: w -h                                                                                                                        archlinux: Wed May 15 13:43:59 2024

root               13:34    9:51   0.00s  0.11s /usr/lib/systemd/systemd --user
root               13:34    9:51   0.00s  0.71s sshd: root@pts/0
root               13:36    9:51   0.00s  0.88s sshd: root@pts/2
admin              13:41    9:51   0.00s  0.10s /usr/lib/systemd/systemd --user
```

After a while the manager session goes away:
```
Every 1.0s: w -h                                                                                                                        archlinux: Wed May 15 13:44:34 2024

root               13:34   10:26   0.00s  0.11s /usr/lib/systemd/systemd --user
root               13:34   10:26   0.00s  0.71s sshd: root@pts/0
root               13:36   10:26   0.00s  0.88s sshd: root@pts/2
```

Alternatively watching loginctl sessions
Utmp changes:
```
changed
Wed May 15 01:45:27 PM UTC 2024
```

But list-sessions takes a while longer to clean up.
```
Every 1.0s: loginctl list-sessions                                                                                                      archlinux: Wed May 15 13:45:32 2024

SESSION  UID USER  SEAT LEADER CLASS         TTY         IDLE SINCE
      1    0 root  -    433    user          pts/0       no   -
     13 1000 admin -    1243   user          web console no   -
     14 1000 admin -    1249   manager       -           no   -
      2    0 root  -    439    manager-early -           no   -
      6    0 root  -    551    user          pts/2       no   -
```

```
Every 1.0s: loginctl list-sessions                                                                                                      archlinux: Wed May 15 13:45:43 2024

SESSION  UID USER  SEAT LEADER CLASS         TTY   IDLE SINCE
      1    0 root  -    433    user          pts/0 no   -
     14 1000 admin -    1249   manager       -     no   -
      2    0 root  -    439    manager-early -     no   -
      6    0 root  -    551    user          pts/2 no   -

4 sessions listed.
```

This reproducer makes it clear that we have created a race condition. Where we depend on utmp to change after or slightly before the session is gone in `w -h`.

@bluca noted that utmp support is optional and not y2038 compatible. So should we move to listening to logind1's SessionRemoved/SessionNew signals?

Trying the reproducer while watching `busctl monitor`, I noticed it does seem to be a viable alternative although the session is removed twice, once for the user and once for manager.

```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=1362  Timestamp="Wed 2024-05-15 13:56:37.835118 UTC"
  Sender=:1.5  Path=/org/freedesktop/login1  Interface=org.freedesktop.login1.Manager  Member=SessionRemoved
  UniqueName=:1.5
  MESSAGE "so" {
          STRING "22";
          OBJECT_PATH "/org/freedesktop/login1/session/_322";
  };
```

```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=1426  Timestamp="Wed 2024-05-15 13:56:48.001086 UTC"
  Sender=:1.5  Path=/org/freedesktop/login1  Interface=org.freedesktop.login1.Manager  Member=SessionRemoved
  UniqueName=:1.5
  MESSAGE "so" {
          STRING "23";
          OBJECT_PATH "/org/freedesktop/login1/session/_323";
  };
```

**Comment by poettering** [comment]
The per-user systemd instance stays around for some time after the user logged out, and eventually exits. This has been that way for a long time. Wha's new in v256 though is that this per-user systemd instance is now properly tracked in logind, as a special session of type "manager" (or "manager-early" in case you are root).

So my guess is that simply surfaces something that previously wasn't visible so much.

And yeah, do not use utmp anymore. Not in 2024

**Comment by poettering** [comment]
So in other words, you are so far really doing it wrong here, utmp only tracks sessions, but not all per-user code running. Thus, this really should be reworked to watch sessions properly, and yes, that means watching logind's dbus signals.

**Comment by jelly** [comment]
Thanks for the quick feedback, I'll propose moving away from watching `utmp` and switch to monitoring sessions over dbus.
