### ISSUE TITLE
systemd-nspawn --setenv fails when passing multiple variables and not specifying values 

### ISSUE THREAD

**Issue by chrooti** [systemd/systemd#32876]
### systemd version the issue has been seen with

255.6

### Used distribution

Arch Linux

### Linux kernel version used

6.8.9

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

The variables are fetched from the environment and set to their corresponding value.
E.g. given 

```bash
A=1
B=2
C=3
```

I get an nspawn container with A set to 1, B set to 2 and C set to 3.

### Unexpected behaviour you saw

"Cannot assign environment variable A,B,C"
Systemd is probably trying to parse A,B,C as a single variable

### Steps to reproduce the problem

systemd-nspawn -D my-nspawn-path --setenv=A,B,C /bin/sh

**Comment by yuwata** [comment]
Please use `--setenv=A --setenv=B --setenv=C`.
