### ISSUE TITLE
RFE: Allow cpu.rt_runtime_us to be set

### ISSUE THREAD

**Issue by qantourisc** [systemd/systemd#329]
As far as I understand it's just not supported. If correct, just close this ticket.
I mainly created this as a form of documentation/format statement for other people running into this issue.

Possible workaround for those affected:
- echo 950000 > /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.rt_runtime_us (or user.slice depending upon)
- Get a kernel without CONFIG_RT_GROUP_SCHED

For people affected and want to read more about it:
http://lists.freedesktop.org/archives/systemd-devel/2013-July/011679.html :  "As discussed earlier, the low-level cgroup configuration options ControlGroup=, ControlGroupModify=, ControlGroupPersistent=, ControlGroupAttribute= have been removed. Please use high-level attribute settings instead as well as slice units."
However I could not find any replacement for rt_runtime_us.

http://www.freedesktop.org/wiki/Software/systemd/MyServiceCantGetRealtime/ : Document is outdated as the above link indicates.

**Comment by poettering** [comment]
I am not sure this can be supported in any sane way since the propagation and summing rules are so weird. I generally encourage everyone to disable rt group scheduling in the kerbel these days.

**Comment by poettering** [comment]
Also see https://github.com/systemd/systemd/pull/553 regarding the details.
