### ISSUE TITLE
mkosi: machine ID in initrd and host are different??

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#32908]
There are two journal directories.
```
May 18 04:03:30 journalctl[1421]: Considering root directory '/run/log/journal'.
May 18 04:03:30 journalctl[1421]: Root directory /run/log/journal added.
May 18 04:03:30 journalctl[1421]: Considering directory '/run/log/journal/349ddf49b1a6401384f5251832e4f9b1'.
May 18 04:03:30 journalctl[1421]: Directory /run/log/journal/349ddf49b1a6401384f5251832e4f9b1 added.
May 18 04:03:30 journalctl[1421]: Journal effective settings seal=no keyed_hash=yes compress=ZSTD compress_threshold_bytes=8B
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system@de81673f8b204dfba911ee124c434239-0000000000000001-000618aaffaf7c1d.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system@de81673f8b204dfba911ee124c434239-0000000000000bff-000618aaffbb04a9.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system@de81673f8b204dfba911ee124c434239-00000000000021e7-000618aaffc88618.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system@de81673f8b204dfba911ee124c434239-00000000000030b8-000618aaffd30e38.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system@de81673f8b204dfba911ee124c434239-0000000000003d92-000618aaffdb6594.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/349ddf49b1a6401384f5251832e4f9b1/system.journal added.
May 18 04:03:30 journalctl[1421]: Considering directory '/run/log/journal/608c83a147c141fdbe19a7c4722f1ca7'.
May 18 04:03:30 journalctl[1421]: Directory /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7 added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-000000000000d2b8-000618ab00e8a1f7.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-000000000000de5d-000618ab01075b49.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-000000000000f20c-000618ab0117261e.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-00000000000105b4-000618ab0124115f.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-000000000001172d-000618ab01370fc9.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-0000000000012388-000618ab0145621f.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-0000000000012ed8-000618ab0153fb1f.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-0000000000013c21-000618ab016f4db2.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-00000000000151c1-000618ab017cef28.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-00000000000166ab-000618ab018b1465.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-00000000000173a5-000618ab019b91b4.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-0000000000017f88-000618ab01b3f905.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system@de81673f8b204dfba911ee124c434239-00000000000193c6-000618ab01bf6209.journal added.
May 18 04:03:30 journalctl[1421]: File /run/log/journal/608c83a147c141fdbe19a7c4722f1ca7/system.journal added.
```
If that's intentional, feel free to close. cc @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
We always remove the machine ID from the image, so this seems like it would be a problem in systemd.

**Comment by poettering** [comment]
This is actually the common case in environments where the initrd is generically built: it's not parameterized and hence comes up with a different machine ID each time.

This is a fundamental different I see between switch-root and soft-reboot btw: i think switch-root should expect the machine ID to change, and soft-reboot should expect the machine ID to not change. i.e. the former is about changing from one OS to another. While the latter is about cycling the same OS.

that is a relatively weak rule i believe however, i.e. it should be OK (and maybe even good) to propagate the machine ID from initrd to host (and vice versa) if we can. And for transient systems it should probably even be ok to change the machine ID on soft reboots i guess.

If we wanted to make sure that initrd and host carry the same initrds i think we need to do two things:

1. via env var or cred propagate initrd machine ID to host. The host should then use this info or not. Typically it would use it if no machine ID is written to /etc/ yet, and otherwise would stick to the data from there.

2. automatically generate an encrypted credential and place it in the ESP for the machine ID via a kernel-install plugin.

If we have both in place, then this would mean we'd be able to have the same machine IDs persistently in both worlds.

**Comment by septatrix** [comment]
> If we wanted to make sure that initrd and host carry the same initrds i think we need to do two things:
> 
>     1. via env var or cred propagate initrd machine ID to host. The host should then use this info or not. Typically it would use it if no machine ID is written to /etc/ yet, and otherwise would stick to the data from there.
> 
>     2. automatically generate an encrypted credential and place it in the ESP for the machine ID via a kernel-install plugin.
> 
> 
> If we have both in place, then this would mean we'd be able to have the same machine IDs persistently in both worlds.

How exactly would the latter work? If that machine-id gets picked up by all OSes it would conflict with the machine-id matching logic from  the DSP/gpt-generator logic for /var partitions.

**Comment by NekkoDroid** [comment]
> How exactly would the latter work? If that machine-id gets picked up by all OSes it would conflict with the machine-id matching logic from the DSP/gpt-generator logic for /var partitions.

`var` in general is a mess, as you can't have multiple mutable `root` partitions so no `/usr/`-only images and with imaged `root` partitions you'd need to include `machine-id` anyway, as the entire partition is read-only.

**Comment by septatrix** [comment]
> > How exactly would the latter work? If that machine-id gets picked up by all OSes it would conflict with the machine-id matching logic from the DSP/gpt-generator logic for /var partitions.
> 
> `var` in general is a mess, as you can't have multiple mutable `root` partitions so no multiple `/usr/`-only images and with imaged `root` partitions you'd need to include `machine-id` anyway, as the entire partition is read-only.

This might be a bit improved by https://github.com/uapi-group/specifications/pull/117, and I also opened https://github.com/uapi-group/specifications/issues/121
