### ISSUE TITLE
pkg/opensuse submodule has switched to sha256 and can no longer be used from sha1 parent

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#32956]
```
‣ Running sync script /home/runner/work/systemd/systemd/mkosi.images/system/mkosi.sync…
Submodule 'pkg/opensuse' (https://src.opensuse.org/rpm/systemd.git) registered for path 'pkg/opensuse'
Cloning into '/work/src/pkg/opensuse'...
fatal: couldn't find remote ref acdb1cd8c5594f66299cc9f8d30d075277eef49b
fatal: Fetched in submodule path 'pkg/opensuse', but it did not contain acdb1cd8c5594f66299cc9f8d30d075277eef49b. Direct fetching of that commit failed.
‣ "/work/sync final" returned non-zero exit code 128.
FAILED: . 
```

The HEAD ref at https://src.opensuse.org/rpm/systemd is now `28c9bef337dd47c88adc1d948cedfdc79c788e2955f17a534bd76da6419722dd`. This requires a repository to have `repositoryformatversion = 1` _and_ `objectformat = sha256`, but we cannot do the latter as our repository is still sha1 (and every other module too), and git seems unable to handle this mixed mode, and refuses to stage such a change for commit from the parent.

@Werkov I imagine this was an intentional switch and there's no going back. Do you happen to have a clone/fork around that is still in the old format, that we could push somewhere and pin to? That way we can at least keep the SUSE CI job going. Otherwise we will have to remove it.

**Comment by Werkov** [comment]
Yeah, this switch to sha256 was intentional. sha1 repo cannot have sha256 submodules. I'm not aware of a sha1 format clone. My local builds are not working neither :angry:. I'm looking into options of reconstructing a sha1 format repo. ([translation tables](https://git-scm.com/docs/hash-function-transition) seem to be still "music of the future").

**Comment by bluca** [comment]
Found a fork that still uses SHA1 and seems up to date: https://code.opensuse.org/package/systemd so I'll switch to that
