### ISSUE TITLE
Disabling non-existent service causes all services to claim to need daemon-reload

### ISSUE THREAD

**Issue by po5857** [systemd/systemd#32959]
### systemd version the issue has been seen with

systemd-255.6-1.fc40.x86_64

### Used distribution

Fedora 40

### Linux kernel version used

6.8.9-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Disabling a non-existent service should not make all other services believe a daemon-reload is required

### Unexpected behaviour you saw

Disabling a non-existent service makes all other services believe a daemon-reload is required

### Steps to reproduce the problem

1) validate that no daemon-reload is required for a service
2) disable a non-existent service
3) see now that all services claim a daemon-reload is needed

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[root@home ~]# systemctl status ntpd
○ ntpd.service - Network Time Service
...
[root@home ~]# systemctl disable asdfasdfasdf
Failed to disable unit: Unit file asdfasdfasdf.service does not exist.
[root@home ~]# systemctl status ntpd
Warning: The unit file, source configuration file or drop-ins of ntpd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
○ ntpd.service - Network Time Service
...
[root@home ~]# systemctl status sshd
Warning: The unit file, source configuration file or drop-ins of sshd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● sshd.service - OpenSSH server daemon
```

**Comment by YHNdnzj** [comment]
This should already be fixed by https://github.com/systemd/systemd/pull/32610.

**Comment by po5857** [comment]
Thanks.  I don't see those commits pulled into systemd-stable at this point.  Will they be, and thus we should look for them in 255.7?

**Comment by bobhy** [comment]
Sounds like this bug is affecting ubuntu-pro users.  https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/2055239
Any plan for releasing the fix, so ubuntu can roll it out to them?
