### ISSUE TITLE
[networkd][IPv6] Do not change system-wide addrgenmode setting and add support to it

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#3296]
### Submission type
- [X] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

Apart from having a temporary address, the kernel also allows users to set a IPv6 address, which is used ["as a secret to generate IPv6 addresses for link-local addresses and autoconfigured ones"](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt), through the `stable_secret` sysctl:

```
[tom@localhost ~]$ cat /etc/sysctl.d/ipv6.conf 
net.ipv6.conf.default.stable_secret=897d:e5b8:6622:aa03:acd5:6a5a:d476:f711
net.ipv6.conf.default.use_tempaddr=1

[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
...
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet6 2404:c805:e00:5500:e9e1:fc3c:b936:6849/64 scope global temporary dynamic 
       valid_lft 1058sec preferred_lft 1058sec
    inet6 2404:c805:e00:5500:98dd:5173:8054:f7b5/64 scope global mngtmpaddr dynamic flags 800 
       valid_lft 1058sec preferred_lft 1058sec
    inet6 fe80::ff06:6cd0:7ef2:480/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```

_IMHO networkd should use the sysctl (if set) to generate randomized stable addresses just like when the kernel is handling the RA._

_Or at least, it should not change the system-wide behaviour, AND also have similar feature implemented in its own way (i.e. having options in `.network` files)._
### In case of bug report: Unexpected behaviour you saw

When networkd is started, it suppresses the using of `stable_secret` (equivalent to have `ip link set DEVICE addrgenmode eui64` run):

```
[tom@localhost ~]$ ip a
...
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86137sec preferred_lft 86137sec
    inet6 2404:c805:e00:5500:7d13:6ad5:e2e0:1760/64 scope global temporary dynamic 
       valid_lft 1630sec preferred_lft 1630sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 1630sec preferred_lft 1630sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever
```
### In case of bug report: Steps to reproduce the problem

This shows that it is not only a behaviour within networkd; instead the system-wide behaviour is changed once networkd is started:

```
[tom@localhost ~]$ sudo systemctl stop systemd-networkd.socket
[tom@localhost ~]$ sudo systemctl stop systemd-networkd
[tom@localhost ~]$ sudo ip l set enp3s0 down
[tom@localhost ~]$ sudo sysctl net.ipv6.conf.enp3s0.accept_ra=1
net.ipv6.conf.enp3s0.accept_ra = 1
[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
...
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86063sec preferred_lft 86063sec
    inet6 2404:c805:e00:5500:7d13:6ad5:e2e0:1760/64 scope global temporary dynamic 
       valid_lft 1555sec preferred_lft 1555sec
    inet6 2404:c805:e00:5500:ae22:bff:fe29:e60c/64 scope global mngtmpaddr dynamic 
       valid_lft 1555sec preferred_lft 1555sec
    inet6 fe80::ae22:bff:fe29:e60c/64 scope link 
       valid_lft forever preferred_lft forever

[tom@localhost ~]$ sudo ip l set enp3s0 down
[tom@localhost ~]$ sudo ip l set enp3s0 addrgenmode stable_secret
[tom@localhost ~]$ sudo ip l set enp3s0 up

[tom@localhost ~]$ ip a
...
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.110/24 brd 192.168.1.255 scope global dynamic enp3s0
       valid_lft 86018sec preferred_lft 86018sec
    inet6 2404:c805:e00:5500:7d13:6ad5:e2e0:1760/64 scope global temporary dynamic 
       valid_lft 1511sec preferred_lft 1511sec
    inet6 2404:c805:e00:5500:98dd:5173:8054:f7b5/64 scope global mngtmpaddr dynamic flags 800 
       valid_lft 1511sec preferred_lft 1511sec
    inet6 fe80::ff06:6cd0:7ef2:480/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```

To avoid any confusion, I am not talking about the `accept_ra` sysctl (which networkd will ALWAYS set to 0, to avoid both the kernel and itself handling the RA I guess), but as you can see, I have to run `ip l set enp3s0 addrgenmode stable_secret` once after networkd is stopped, only then will the kernel use `stable_secret` to generate the "stable" (global AND link-local) IPv6 addresses.

**Comment by teg** [comment]
We should abosuletly support the stable secret interface feature in networkd. However, after discussing this with the kernel people, we agreed that this should be done fully inside networkd, and not by hooking into the kernel feature (which was meant as a fallback when no network management was available on a system).

Until that is done, we should of course not get in the way of interfaces we do not manage. Is that what you mean by a global change? Or do you mean that once you stop networkd, you need to manually reset an inerface that networkd used to manage? I think the latter is acceptable, we do not want to support managing the same interface from networkd as well as sysctl/NM/ip(8), so if you want to manage an interface yourself, you better not configure networkd to manage it too.

**Comment by tomty89** [comment]
When I said global I meant I need to reset the `addrgenmode` to `stable_secret` after I stopped networkd. I guess it is acceptable (I mean, I need to revert `accept_ra` manually as well, so...), but does it need to be changed in the first place though? Since networkd does not rely on `accept_ra`, is it affected at all by the attribute when it handles the RA and configure IPv6 addresses on its own?

**Comment by teg** [comment]
@tomty89, yeah, if we leave accept_ra on, then the kernel will handle the RA as well as us, and we'll be fighting over the same interface. So I think we do need to switch that off for interfaces we are managing (but obviously not for anything we are not in charge of).
