### ISSUE TITLE
Wrap log section in issue template with `<details>`

### ISSUE THREAD

**Issue by septatrix** [systemd/systemd#32984]
### Component

other

### Is your feature request related to a problem? Please describe

It is often convenient to have to log directly available inside the issue. Creating a gist for it is more effort and it is unclear what exactly constitutes a "long" log and what is reasonable to inline inside of an issue. However, at a certain length it is annoying to scroll past the log section.

### Describe the solution you'd like

Wrap the log section with a HTML detail+summary tag. These are allowed by Github and supported in basically every browser (except IE 11 though it should just be rendered as a div there).

### Describe alternatives you've considered

Start telling people that everything larger than x lines should land in a gist

**Comment by bluca** [comment]
The template is here: https://github.com/systemd/systemd/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml please send a PR to add this

**Comment by septatrix** [comment]
While github does allows them inside markdown I was apparently a bit to quick with my conclusion as there does not seem to be any way to use them inside an issue template. See https://github.com/orgs/community/discussions/34785

I will follow that and provide a PR once that is actually possible
