### ISSUE TITLE
bootctl fails when operating on non-partitioned block device

### ISSUE THREAD

**Issue by septatrix** [systemd/systemd#32983]
### systemd version the issue has been seen with

255.6-1.fc40.x86_64

### Used distribution

Fedora 40

### Linux kernel version used

6.8.9-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl list --root=/run/media/septatrix/ESP --esp-path=/` where `.../ESP` is a mounted EFI partition should list the installed boot loader entries,

### Unexpected behaviour you saw

When invoked without root permission the command exits with the error: `loop0: Failed to get device property: No such file or directory`.
With root permissions the command exits with the error: `File system "/dev/loop0" is not located on a partitioned block device.`

### Steps to reproduce the problem

1. Obtain a disk image of an ESP partition (for example by generating the default mkosi image with `--split-artifacts=true`),
2. create a loop device of said partition using `udisksctl loop-setup --read-only -f foobar.esp.raw`,
3. mount said loop device using `udisksctl mount --block-device /dev/loop0`, and finally
4. run `bootctl list --root=/run/media/septatrix/ESP --esp-path=/` (with or without sudo to see both of the above errors).

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Without sudo:
Failed to read $container of PID 1, ignoring: Permission denied
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
loop0: Failed to get device property: No such file or directory


With sudo:
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
File system "/dev/loop0" is not located on a partitioned block device.
```

**Comment by poettering** [comment]
yeah, the tool validates that the backing block device is a valid partition block device with the right GPT partition type for ESPs. Which it isn't in your case, you do not have any partitions, as you seem to attach the ESP fs directly to a block device. Such an fs is not a valid ESP after all, unles you first copy the fs into a properly tagged partition. 

if you want to turn off these checks use SYSTEMD_RELAX_ESP_CHECKS=1 env var, as per docs, see https://systemd.io/ENVIRONMENT
