### ISSUE TITLE
systemd-cryptenroll cannot find PKCS#11 HSM URI

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#32989]
### systemd version the issue has been seen with

252 ((252.17-1~deb12u1+rpi1))

### Used distribution

Debian

### Linux kernel version used

6.6.20+rpt-rpi-v8

### CPU architectures issue was seen on

None

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

successfully enrolling PKCS#11 token

### Unexpected behaviour you saw

Specified PKCS#11 token with URI 'pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=cert' not found.

### Steps to reproduce the problem

I am trying to use a smartcard HSM as a LUKS key on a raspberry pi 4. A private key and certificate is stored in the HSM. I could see the token URI using below command
`p11tool --provider=/usr/lib/opensc-pkcs11.so --list-tokens`

`p11tool --provider=/usr/lib/opensc-pkcs11.so --outfile=/tmp/p11_output_hsm --login --list-all pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=cert`

The `p11_output_hsm` contains

```
Object 0:
        URL: pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=private
        Type: Private key (RSA-2048)
        Label: luks_test
        Flags: CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE;
        ID: 01

Object 1:
        URL: pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=public
        Type: Public key (RSA-2048)
        Label: luks_test
        ID: 01

Object 2:
        URL: pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=cert
        Type: X.509 Certificate (RSA-2048)
        Expires: Thu May 22 17:00:40 2025
        Label: luks_test
        ID: 01
```

Copied the URI from above command and tried to enroll it using 
`sudo systemd-cryptenroll --pkcs11-token-uri="pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=cert" /dev/mmcblk0p2`

This results in 
```
Specified PKCS#11 token with URI 'pkcs11:model=PKCS%2315;manufacturer=unknown;serial=0000;token=JavaCard%20isoApplet%20%28User%20PIN%29;id=%01;object=luks_test;type=cert' not found.
```
Also tried adding `SYSTEMD_LOG_LEVEL=debug` but response is same.

Can anyone please let me know what is the issue here and how to resolve it?

Thanks in advance.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
