### ISSUE TITLE
`systemctl set-property --runtime systemd-journald ExecStart=meow` does not work

### ISSUE THREAD

**Issue by lf-** [systemd/systemd#32982]
### systemd version the issue has been seen with

255

### Used distribution

NixOS unstable

### Linux kernel version used

6.6.30

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

`systemctl set-property` should work on ExecStart. I would expect to be able to set any property, as if I were doing systemctl edit, but automatically.

### Unexpected behaviour you saw

`systemctl set-property` claims that it is an unsupported property, and the manual page does not say that it is some highly constrained set of properties that are actually supported.

### Steps to reproduce the problem

```
~ » sudo systemctl set-property --runtime systemd-journald ExecStart=meow
Failed to set unit properties on systemd-journald.service: Cannot set property ExecStart, or unknown property.
```

This seems suspiciously like the responsible code, and it seems suspiciously like this is some code duplication at work:
https://github.com/systemd/systemd/blob/677e6c14b199c1fa637b7c4c8cae39c31213a79d/src/core/dbus-cgroup.c#L1100-L1106

**Comment by bluca** [comment]
The set-property stuff is intentionally for resource configuration changes

**Comment by YHNdnzj** [comment]
Note that with systemd v256 you can use the following to create a drop-in non-interactively:

```bash
$ systemctl edit --stdin systemd-journald.service <<EOF
[Service]
ExecStart=
ExecStart=...
EOF
```

**Comment by lf-** [comment]
> No. `set-property` is meant to work with properties that can be applied to running units, and those properties only. Please use `systemctl edit` if you want to change "static" settings.
> 
> Not a bug, closing.

```
       set-property UNIT PROPERTY=VALUE...
           Set the specified unit properties at runtime where this is supported. This allows changing configuration parameter
           properties such as resource control settings at runtime. Not all properties may be changed at runtime, but many resource
           control settings (primarily those in systemd.resource-control(5)) may. The changes are applied immediately, and stored on
           disk for future boots, unless --runtime is passed, in which case the settings only apply until the next reboot. The
           syntax of the property assignment follows closely the syntax of assignments in unit files.
```

I understand that the documentation does say this if you know that this is already what it does, but it absolutely fails to convey that that is the case if you don't already know that this is just for resource changes.

It should say something about "this only works for properties that can be changed *without restarting the unit*". To me, "at runtime" could mean either while the *entire system* is live, which is what `--runtime` means, or when the unit is live, and I would tend to read the first one way more than the second one.

So the docs are misleading, even if this is working as intended.

**Comment by Qyriad** [comment]
If this behavior is intended then this is definitely at least a docs issue
