### ISSUE TITLE
systemd-bootchart: The .SVG is truncated if --per-cpu is used

### ISSUE THREAD

**Issue by gmacario** [systemd/systemd#330]
If `systemd-bootchart` is run using the `--per-cpu` option on a multi-cpu host, the resulting .svg file when displayed on a browser is truncated at the end and does not show all the processes.

**Comment by xnox** [comment]
I have a patch for this in clear linux. Let me push this.

**Comment by zonque** [comment]
@xnox, thanks! Does that solve your issue, @gmacario?

**Comment by gmacario** [comment]
@zonque: Yes - apart the additional fix for small scales which I would suggest to leave as a separate PR since it does not work properly in my configuration.

Please see my comment in https://github.com/systemd/systemd/pull/332
