### ISSUE TITLE
User manager not started for lingering users upon reboot

### ISSUE THREAD

**Issue by iddpd** [systemd/systemd#33005]
### systemd version the issue has been seen with

256~rc3

### Used distribution

Debian GNU/Linux trixie/sid

### Linux kernel version used

6.8.9-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

To have user@<UID>.service automatically started on boot for any user with lingering configured.

### Unexpected behaviour you saw

Title.

### Steps to reproduce the problem

Enable lingering for any user and reboot.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# loginctl user-status 1000
[redacted] (1000)
  Since: Fri 2024-05-24 12:36:29 UTC; 3min 3s ago
  State: lingering
 Linger: yes
   Unit: user-1000.slice

May 24 12:36:29 [redacted] systemd[1]: Created slice user-1000.slice - User Slice of UID 1000.
# systemctl status user-runtime-dir@1000.service 
● user-runtime-dir@1000.service - User Runtime Directory /run/user/1000
     Loaded: loaded (/usr/lib/systemd/system/user-runtime-dir@.service; static)
     Active: active (exited) since Fri 2024-05-24 12:36:29 UTC; 3min 35s ago
 Invocation: c9e92173eb9f4e8dbec6266ba11a040b
       Docs: man:user@.service(5)
    Process: 683 ExecStart=/usr/lib/systemd/systemd-user-runtime-dir start 1000 (code=exited, status=0/SUCCESS)
   Main PID: 683 (code=exited, status=0/SUCCESS)

May 24 12:36:29 [redacted] systemd[1]: Starting user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
May 24 12:36:29 [redacted] systemd[1]: Finished user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.
# systemctl status user@1000.service 
○ user@1000.service - User Manager for UID 1000
     Loaded: loaded (/usr/lib/systemd/system/user@.service; static)
    Drop-In: /usr/lib/systemd/system/user@.service.d
             └─10-login-barrier.conf
     Active: inactive (dead)
       Docs: man:user@.service(5)
```

**Comment by poettering** [comment]
Can you provide relevant log of such a boot where this fails?

**Comment by iddpd** [comment]
[boot.txt](https://github.com/systemd/systemd/files/15453501/boot.txt)

The user@UID.service doesn't really fail to start (I can start it manually just fine), it's just that systemd doesn't make an attempt to start it on boot despite lingering being enabled.
