### ISSUE TITLE
Lenovo Z500 F6 Toggle Touchpad Non Functional

### ISSUE THREAD

**Issue by njlittle** [systemd/systemd#33029]
### systemd version the issue has been seen with

255.4

### Used distribution

Gentoo

### Linux kernel version used

6.1.41

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

F6 key toggles touchpad on/off

### Unexpected behaviour you saw

F6 key doesn't toggle, dmesg reports:

```
atkbd serio0: Unknown key pressed (translated set 2, code 0xf3 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e073 <keycode>' to make it known.
atkbd serio0: Unknown key released (translated set 2, code 0xf3 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e073 <keycode>' to make it known.
```

### Steps to reproduce the problem

Always reproducible until:

```
evdev:atkbd:dmi:bvn*:bvr*:svnLENOVO*:pn*5931*:pvr*
 KEYBOARD_KEY_f3=f21                                    # Fn+F6 (toggle touchpad)
```

is added to /usr/lib/udev/hwdb.d/60-keyboard.hwdb

**Comment by yuwata** [comment]
Could you submit the change as a PR?

**Comment by njlittle** [comment]
Sure thing, created PR #33039
