### ISSUE TITLE
[RFE][networkd][resolved][IPv6] Add support for RDNSS and DNSSL (RFC 6106)

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#3303]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux

The title pretty much says it  all. Especially when networkd supresses the kernel-side Router Announcement soliciting and deals with RA on its own, it should have the support of getting DNS information from the RA added (in addition to the support of DHCPv6).

FWIW, (the unmaintained) rdnssd (distributed with ndisc6) does not work along with networkd due to the suppression.

**Comment by teg** [comment]
I would merge patches for this.

**Comment by tomty89** [comment]
Duplicate of #1079.
