### ISSUE TITLE
Inhibit watchdog while a debugger is attached to the process

### ISSUE THREAD

**Issue by Zamundaaa** [systemd/systemd#33080]
### Component

systemd

### Is your feature request related to a problem? Please describe

When I attach gdb to kwin_wayland, interrupt the process and after 15s+ continue, the watchdog stops the process because it hasn't responded in 15s (the configured watchdog timeout). This makes debugging very annoying

### Describe the solution you'd like

The watchdog should either be inhibited as long as a debugger is attached to the process, or at least while the process is stopped by the debugger

### The systemd version you checked that didn't have the feature you are asking for

255.6

**Comment by bluca** [comment]
This is something the debugger should do, we can't really know this is happening. For example from gdb you can call `p (int)sd_notify(0, "WATCHDOG_USEC=0")` and that will stop it the watchdog from ticking. You should file RFEs for the debuggers you care about - they can check if the `WATCHDOG_USEC=` env var is set in the process being debugged, and if it is and > 0 it means it's running in a service with the watchdog enabled. Then they can send that WATCHDOG_USEC=0 message when attaching, and when detaching reset it back to the original value that was in the env var.

**Comment by Zamundaaa** [comment]
Thanks, I'll do that!
