### ISSUE TITLE
Intermittent failures when setting up namespaces in early started services

### ISSUE THREAD

**Issue by codekipper** [systemd/systemd#33127]
### systemd version the issue has been seen with

255.4

### Used distribution

yocto scarthgap

### Linux kernel version used

6.1.55

### CPU architectures issue was seen on

arm

### Component

systemd

### Unexpected behaviour you saw

[ ERR     ] (kmod): Failed to mount /run/systemd/propagate/kmod-static-nodes.service to /run/systemd/mount-rootfs/run/systemd/incoming: No such file or directory
[ ERR     ] (kmod): kmod-static-nodes.service: Failed to set up mount namespacing: /run/systemd/incoming: No such file or directory
[ NOTICE  ] systemd: kmod-static-nodes.service: Main process exited, code=exited, status=226/NAMESPACE
[ WARNING ] systemd: kmod-static-nodes.service: Failed with result 'exit-code'.
[ ERR     ] systemd: Failed to start Create List of Static Device Nodes.

On slower devices in our product profile we have noticed the occasional issue at startup of a few services that are started early on. This was not seen in 254.4 from which we've just upgraded from. It looks very similar to #29690 and was also seen when I tested with the latest release candidate(v256-rc3). 
I have a test which reboots our device and then checks for failed services. Within 200 runs, I would see this issue.
TIA,
CK

**Comment by bluca** [comment]
Please provide debug-level logs

**Comment by codekipper** [comment]
Unfortunately after adding debugging I was unable to reproduce the issue after over a 1000 runs.

**Comment by bluca** [comment]
Ok thanks, given it's unreproducible and there are no logs there's nothing we can do, closing, if you manage to reproduce and gather logs please reopen

**Comment by arianvp** [comment]
I'm running into this issue with *late* running services. It happened once today across 3 instances in our fleet of servers around the same time.  just after boot.

```
Jul 15 11:01:28 X (app-auth)[2460]: Failed to mount /run/credentials/gha-slot-mercury-intranet-0.service to /run/systemd/mount-rootfs/secrets: No such file or directory
Jul 15 11:01:28 X (app-auth)[2460]: gha-slot-mercury-intranet-0.service: Failed to set up mount namespacing: /secrets: No such file or directory
Jul 15 11:01:28 X systemd[1]: gha-slot-mercury-intranet-0.service: Control process exited, code=exited, status=226/NAMESPACE
```

The interesting part is that we have a `BindPaths=%d:/secrets` in our systemd service that mounts credentials in a stable path..

```
[Service]
BindPaths=%d:/secrets
```

Don't have much information except for "It happened; and it looks really weird."

**Comment by codekipper** [comment]
I've not seen the issue since [cherry-picking](https://github.com/systemd/systemd/commit/c3f0f6f8bd812fee4b2ab658a5cc9ac9167d387d) into my build. It's since been added to systemd-stable.

**Comment by hugo303** [comment]
A probable cause for this bug could be https://sourceware.org/bugzilla/show_bug.cgi?id=32214 . The patch fixes the problem on our devices.

**Comment by codekipper** [comment]
> A probable cause for this bug could be https://sourceware.org/bugzilla/show_bug.cgi?id=32214 . The patch fixes the problem on our devices.

We saw a similar issue with the latest yocto build which was resolved by the change mentioned in bug report https://sourceware.org/git/?p=glibc.git;a=commit;h=5f62cf88c4530c11904482775b7582bd7f6d80d2
As I couldn't reproduce it with the previous yocto release and the same systemd version then I was pretty convinced that systemd wasn't at fault.
