### ISSUE TITLE
Any non-empty `AmbientCapabilities` causes user service to fail (regression in v255)

### ISSUE THREAD

**Issue by one-d-wide** [systemd/systemd#33167]
### System information
Affected Systemd version: 255 (v254 works as expected).
Linux kernel versions used: 6.1.63, 6.6.32 (the bug manifests on both).
Component: `systemd --user`.

### Expected behaviour you didn't see

User service starting normally with non-zero `AmbientCapabilities`, given that required capabilities are assigned to non-root `systemd --user` process.

### Unexpected behaviour you saw

Service unit fails with error: `Failed to apply ambient capabilities (before UID change): Operation not permitted`. A program specified in `ExecStart` parameter isn't started.

### Steps to reproduce the problem

```sh
$ systemd-run --user --pipe --collect --wait -p AmbientCapabilities=CAP_WAKE_ALARM -- capsh --print
Running as unit: run-uX.service
...
$ journalctl -e
Thu Jan  1 12:00:00 host systemd[20]: Started /run/current-system/sw/bin/capsh --current --print.
Thu Jan  1 12:00:00 host (capsh)[30]: run-uX.service: Failed to apply ambient capabilities (before UID change): Operation not permitted
Thu Jan  1 12:00:00 host systemd[20]: run-uX.service: Main process exited, code=exited, status=218/CAPABILITIES
Thu Jan  1 12:00:00 host systemd[20]: run-uX.service: Failed with result 'exit-code'.
$ pscap -p 20
ppid  pid  uid   command  capabilities  
1     20   user  systemd  wake_alarm    +
```

Note: wake_alarm capability is passed to `systemd --user` by default, starting from systemd v254.

### Probable cause

Any `systemd` instance not running as root [unsets](https://github.com/systemd/systemd/blame/a173292ffa3b0219fd9ff77bdc90f00e8feef7af/src/core/main.c#L3136) all ambient capabilities on startup in order to restrict their accidental leaking. Ambient capabilities are preserved across an `execv(2)` and are the only way to inherit capabilities for non-root users, see `capabilities(7)`.

It is possible to drop and restore an ambient capabilities after via `prctl(2)` syscall. This is done in systemd using [`capability_ambient_set_apply`](https://github.com/systemd/systemd/blame/9619fdc102f1eda8e0a9d5a3ddc8c9d34bf79d26/src/basic/capability-util.c#L108). Though the restore process is only possible if a capability is found in both permitted and inheritable sets, i.e. if a user process didn't crossed `execve` without the abmient capability sat beforehand.

This was the case in v254. The daemon process was only forked, hence all the capabilities were preserved, and executor was residing in the same binary. However in v255 the executor code was moved into separate `systemd-executor` binary and the usual logic to restore ambient capabilities appeared past the `execve` boundary, that stripped all the necessary capabilities and caused the bug.

### Probable solution

Move the logic restoring requested ambient capabilities to prior the execve boundary in `sd-executor`, thus ensuring normal propagation of requested capabilities.

<details>
<summary>Dirty ad-hoc test</summary>

Executing the procedure above in `gdb` seems to resolve the issue in without touhing ambient capabilities in the main `systemd --user` process.

```gdb
$ gdb -p 20
(gdb) set follow-fork-mode child
(gdb) break execve
(gdb) # prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_IS_SET, CAP_WAKE_ALARM, 0, 0) == 0
(gdb) print ((int(*)())prctl)(47, 1, 35, 0, 0)
$1 = 0
(gdb) continue
(gdb) # invoke `systemd-run` as described in [Steps to reproduce the problem]
Breakpoint 1, ... in execve () ...
(gdb) print ((int(*)())prctl)(47, 2, 35, 0, 0)
$2= 0
(gdb) # prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_RAISE, CAP_WAKE_ALARM, 0, 0) == 0
(gdb) continue
...
(gdb) # invoked `systemd-run` should execute sucessfully
```

</details>

**Comment by yuwata** [comment]
Discussion has been already started in #32937.
