### ISSUE TITLE
Add support for configuring VRF devices thru networkd

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#3316]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu

May you please add support for configuring VRF devices thru networkd?

For referance on how this is currently done with iproute2 see: https://www.kernel.org/doc/Documentation/networking/vrf.txt

**Comment by halvors** [comment]
What's the status on this?

**Comment by halvors** [comment]
Seems like this is added, shouldn't this be closed then?

**Comment by poettering** [comment]
Indeed. Fixed in v231. Closing.
