### ISSUE TITLE
DynamicUser fine control with new access rules

### ISSUE THREAD

**Issue by Anuskuss** [systemd/systemd#33188]
### Component

systemd

### Is your feature request related to a problem? Please describe

`DynamicUser` is powerful but too complicated for my use case. I just want the security benefits without having to go through hoops to make it all work. That's why I proposing the idea to specifiy rules that would allow one to access specific files.

### Describe the solution you'd like

```ini
[Service]
DynamicUser=true
ReadAccess=/var/www/html/status.html /var/www/html/status.css
ReadWriteAccess=/etc/myconfig.conf 
```

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by bluca** [comment]
Already implemented, use StateDirectory= and friends https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory=

**Comment by Anuskuss** [comment]
Those are the hoops I was talking about. I don't need any of those, I just need R/W access to one file in the `/var/www/html` directory so I can show a status message. How would one even do that currently? `RuntimeDirectory` + `WorkingDirectory` + `ExecStartPre` to `ln` the file, then `stat` the `RuntimeDirectory` directory to `chown` the file? Show me a better way (I can't modify the program).

**Comment by bluca** [comment]
Modify the program to use one of those, or do not use this setting

**Comment by Anuskuss** [comment]
I think that my proposal is useful and that you should reopen this. Like I said I wanna remove almost all permissions from this closed source program (especially as it's no longer maintained) and just give it write access to one single file.

**Comment by bluca** [comment]
That is not how ephemeral users work. Files owned by random IDs cannot be left around carelessly, for obvious reasons, and they have to be carefully managed. Hence, either change the program to use those settings, or simply don't use this, as it does not fit with the use case.

**Comment by Anuskuss** [comment]
> Files owned by random IDs cannot be left around carelessly

What does this even mean? I want to give (root) access to a file that already exists. And the files should be opened either readonly or readwrite, so no shenanigans like symlinking to `/etc/shadow` or setting the setuid bit.

> or simply don't use this,

Okay, I understand that you don't find this useful. But can you at least keep the issue open for more comments? Maybe someone else will think it is.
