### ISSUE TITLE
RFC: DynamicUser fine control with access rules

### ISSUE THREAD

**Issue by Anuskuss** [systemd/systemd#33203]
### Is your feature request related to a problem? Please describe

`DynamicUser` is powerful but too complicated for my use case. I just want the security benefits without having to go through hoops to make it all work. That's why I proposing the idea to specifiy rules that would allow one to access specific files.

### Describe the solution you'd like

```ini
[Service]
DynamicUser=true
ReadAccess=/etc/myconfig.conf
ReadWriteAccess=/var/www/html/status.html /var/www/html/status.css
```

### Describe alternatives you've considered

I know that `RuntimeDirectory` exists but that doesn't work for me. I just need access to a globally writable file so I can show some information. I can certainly make the read work (e.g. `ExecStartPre=+`) but the write is impossible, even when I write a pre-script that changes the owner to the dynamic user (and the file is 777).

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by bluca** [comment]
Duplicate of https://github.com/systemd/systemd/issues/33188
