### ISSUE TITLE
Redundant client-identifier DHCP Server and client DUID assignment with B.A.T.M.A.N mesh

### ISSUE THREAD

**Issue by pclass-isolated** [systemd/systemd#33267]
### systemd version the issue has been seen with

250.5+

### Used distribution

Custom Yocto Linux Build

### Linux kernel version used

5.15.32+g9d7d040bf936

### CPU architectures issue was seen on

aarch64

### Component

networkctl

### Expected behaviour you didn't see

1 DHCP Client identifier for each B.A.T.M.A.N mesh client would be that client's MAC Address. There would be no redundant entries for the same B.A.T.M.A.N client.

For example, with 'networkctl status bat0' I would see this:
```
Offered DHCP leases: 10.10.10.13 (to a6:d2:9c:dc:0c:61)
                                   10.10.10.12 (to 5a:e6:01:27:06:0c)
```

### Unexpected behaviour you saw

I have 1 B.A.T.M.A.N 'Gateway', using systemd-networkd to act as the DHCP server for the 'bat0' interface. When 2 clients successfully associate with the B.A.T.M.A.N mesh network, also using systemd-networkd to configure as DHCP clients, they eventually display multiple 'offered DHCP leases' for the each client. The strange part is that initially, the networkctl output shows only 2 leases for the 2 clients with mac addresses only. After some amount of time (~5 minutes), the same networkctl output shows multiple leases and IP addresses representing each client independently.

For example, with 'networkctl status bat0' I would initially see this for two connected clients, soon after they connect:
```
networkctl status bat0
● 6: bat0
                     Link File: n/a
                  Network File: /etc/systemd/network/bat0.network
                          Type: ether
                         State: routable (configured)
                  Online state: online
                        Driver: B.A.T.M.A.N. advanced
              Hardware Address: 5a:48:43:5a:9e:67
                           MTU: 1500 (min: 68, max: 1500)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
                       Address: 10.10.10.1
                                169.254.237.68
                                fe80::5848:43ff:fe5a:9e67
                                fe80::6be2:e711:1e49:ba1c
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111cab9d2f97547dea0000
           Offered DHCP leases: 10.10.10.10 (to c6:c1:e6:c9:1f:a8)
                                              10.10.10.11 (to 7e:0b:ae:34:93:ca)

Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Link UP
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Gained carrier
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Gained IPv6LL
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: netdev exists, using existing without changing its parameters
Jun 10 17:31:44 mesh-gw systemd-networkd[760]: bat0: DHCPv6 lease lost
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: netdev ready
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Link UP
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Gained carrier
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Gained IPv6LL
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: netdev exists, using existing without changing its parameters
```

Several minutes after this, I see the following (notice the 10.10.10.14 and 10.10.10.10 - the DUID has similarities to the mac address):

```
networkctl status bat0
● 6: bat0
                     Link File: n/a
                  Network File: /etc/systemd/network/bat0.network
                          Type: ether
                         State: routable (configured)
                  Online state: online
                        Driver: B.A.T.M.A.N. advanced
              Hardware Address: 5a:48:43:5a:9e:67
                           MTU: 1500 (min: 68, max: 1500)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
                       Address: 10.10.10.1
                                169.254.237.68
                                fe80::5848:43ff:fe5a:9e67
                                fe80::6be2:e711:1e49:ba1c
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111cab9d2f97547dea0000
           Offered DHCP leases: 10.10.10.12 (to IAID:0xae3493ca/DUID)
                                10.10.10.10 (to c6:c1:e6:c9:1f:a8)
                                10.10.10.14 (to IAID:0xe6c91fa8/DUID)
                                10.10.10.11 (to 7e:0b:ae:34:93:ca)

Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Link UP
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Gained carrier
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: Gained IPv6LL
Jun 10 17:31:39 mesh-gw systemd-networkd[760]: bat0: netdev exists, using existing without changing its parameters
Jun 10 17:31:44 mesh-gw systemd-networkd[760]: bat0: DHCPv6 lease lost
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: netdev ready
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Link UP
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Gained carrier
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: Gained IPv6LL
Jun 10 17:31:45 mesh-gw systemd-networkd[899]: bat0: netdev exists, using existing without changing its parameters
```

I expect the DHCP server to assign the mesh clients a single IP Address based on their Mac Address. I do not want them to be assigned an IP based on IAID/DUID. For this, the docs say to use ClientIdentifier=mac, which I have done. The problem is that I see multiple IP Addresses assigned to my clients, some based on the mac address, and some apparently based on the DUID.

I expect to only ever see the 2 IP addresses, mapped to the 2 mac addresses of these B.A.T.M.A.N clients, and not the DUID entries as well and 2 more IP addresses.

### Steps to reproduce the problem

Configure 3 Linux machines, each with a B.A.T.M.A.N capable wifi device, and configured them as follows with systemd-networkd.

The bat0.network file on the master looks like this:

```
root@mesh-master:/etc/systemd/network# cat bat0.network
[Match]
Name=bat0

[Network]
Address=10.10.10.1/24
DHCPServer=true

[DHCPV4]
DUIDType=link-layer
ClientIdentifier=mac

[DHCPServer]
PoolOffset=10
PoolSize=8
EmitsDNS=yes
DNS=8.8.8.8
EmitNTP=yes
NTP=10.10.10.1
```

Configure both clients to look like this:

```
root@mesh-client:~# cat /etc/systemd/network/bat0.network
[Match]
Name=bat0

[Network]
DHCP=ipv4

[DHCP]
ClientIdentifier=mac
```

The master also has the following bat0.netdev file:

```
root@mesh-client:~# cat /etc/systemd/network/bat0.netdev
[NetDev]
Name=bat0
Kind=batadv

[BatmanAdvanced]
GatewayMode=server
RoutingAlgorithm=batman-v
OriginatorIntervalSec=5
```

The clients have this bat0.netdev file:

```
root@mesh-client:~# cat /etc/systemd/network/bat0.netdev
[NetDev]
Name=bat0
Kind=batadv

[BatmanAdvanced]
GatewayMode=client
RoutingAlgorithm=batman-v
OriginatorIntervalSec=5
```

Setup wpa_supplicant on all three devices to utilize the Wi-Fi interface in the mesh configuration:

```
root@mesh-client:~# cat wpa_supplicant-mesh.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=adm

user_mpm=1
network={
    ssid="MyMeshSSID"
    mode=5
    frequency=2412
    key_mgmt=SAE
    psk="mymeshpassword"
}

```

All three device should connect, and the mac address will be mapped to a single IP address initially. After some time on the order of 5-10 minutes, there will be a second IP address mapped to the same client device with a DUID.

**Comment by poettering** [comment]
First of all, please only report issues with current systemd versions here, i.e. v255. 

But secondly, are you sure your peers aren't running two DHCP clients? i..e. one that picks that DUID and the other which does not?
