### ISSUE TITLE
udev_device_get_parent() crash when upgrading from 255.7 to 256

### ISSUE THREAD

**Issue by heitbaum** [systemd/systemd#33292]
https://github.com/systemd/systemd/blob/21f51d877fefd380c7ea388d579f1cc7dc19b226/src/libudev/libudev-device.c#L407

```
Jun 12 11:20:21 nuc12 kodi.sh[3601]: Assertion 'udev_device' failed at src/libudev/libudev-device.c:407, function udev_device_get_parent(). Aborting.
Jun 12 11:20:22 nuc12 kodi.sh[3550]: Aborted (core dumped)
```

https://github.com/Pulse-Eight/libcec/issues/658

**Comment by heitbaum** [comment]
I quick hack to libcec to “workaround” the regression allowed the code to pass this section only to caused a subsequent assert in a different source code.
```
-    pdev = udev_device_get_parent(udev_device_get_parent(dev));
+    pdev = udev_device_get_parent(dev);
+    if (pdev)
+      pdev = udev_device_get_parent(pdev); 
```
https://github.com/xbmc/xbmc/blob/0f7f6ac821a31b0360e8563b98b2d435a8c98d80/xbmc/platform/linux/peripherals/PeripheralBusUSBLibUdev.cpp#L111

**Comment by yuwata** [comment]
I guess, you build systemd with developer mode (it is the default). Please build with `-Dmode=release`.

**Comment by yuwata** [comment]
And, the assertion itself is expected, though previously it was logged in LOG_DEBUG, and not critical.
Please rewrite the code something like you already commented in the above.

**Comment by yuwata** [comment]
Closing as it is expected.

**Comment by heitbaum** [comment]
> Closing as it is expected.

Thanks, I have raised the PRs in both Kodi and Libcec.
