### ISSUE TITLE
GitHub Release Notes contains weird TYPO: `CHANGES WITH v2⁸`

### ISSUE THREAD

**Issue by jamacku** [systemd/systemd#33310]
### systemd version the issue has been seen with

256

### CPU architectures issue was seen on

None

### Component

other

### Unexpected behaviour you saw

[GitHub Release Notes](https://github.com/systemd/systemd/releases/tag/v256) for `v256` contains weird TYPO:

![Screenshot from 2024-06-14 08-09-31](https://github.com/systemd/systemd/assets/2879818/7940c605-706c-42fa-ada1-4a9b3f6fb2fd)

### Steps to reproduce the problem

Not sure if this was caused by user error or CI/CD bug.

**Comment by yuwata** [comment]
2^8 = 256.

**Comment by jamacku** [comment]
Thanks, @yuwata. I haven't thought about this.
