### ISSUE TITLE
Use SetCredentialEncrypted in user service

### ISSUE THREAD

**Issue by smlx** [systemd/systemd#33318]
### Component

systemd

### Is your feature request related to a problem? Please describe

I generated an encrypted credential for my user service as described in the `systemd-creds` manpage.

```
$ (echo '[Service]' && systemd-creds encrypt --user --name=aws.conf /tmp/aws.creds -p -) | tee ~/.config/systemd/user/restic.service.d/credenti
als.conf
[Service]
SetCredentialEncrypted=aws.conf: \
        VbntHThZTUOoMZ0uuzMqxiAAAAABAAAADAAAABAAAADZQdpofknyef7ttg8AAAAABwAAA \
        AAAAADB0+6hIXXE3jQ2forWQtSk0uPMyYoV2FJn5DNw/4ZxaJHg8ktzEA/TJqFp2HvAXF \
        12lyUZZZ/N1wMvmzVmbiISCulhi2L42DrMcDfvSWi5TNf2FAqh1cSMqrIxfl5E4I4AiKH \
        qIm8jW47FX4X627fD4e/Zbfqdd6TuCAj5CNtYgM3oWihDwfi9talH3ofwdung02IzwBDL \
        rzEZJTQpa8AS
```

However when I run the service I get a series of errors related to credentials:

```
Jun 14 16:07:57 thinky1 (sh)[1960282]: Failed to determine local credential key: Permission denied
Jun 14 16:07:57 thinky1 (sh)[1960282]: restic.service: Failed to set up credentials: Permission denied
Jun 14 16:07:57 thinky1 (sh)[1960282]: restic.service: Failed at step CREDENTIALS spawning sh: Permission denied
```

### Describe the solution you'd like

Ideally `SetCredentialEncrypted` in user services would work.

I saw [this comment](https://github.com/systemd/systemd/pull/30968#issuecomment-1916931594) in #30968 so am I correct that the use of `SetCredentialEncrypted` in user services is just not supported yet? I didn't find any other documentation suggesting that this configuration is not supported.

### Describe alternatives you've considered

An alternative would be to run a system service with a `User=` param, but being able to use encrypted credentials in user services would be ideal for usability.

### The systemd version you checked that didn't have the feature you are asking for

256-rc4

**Comment by smlx** [comment]
Yes, it seems to be.
![screenshot_2024-06-18-104030](https://github.com/systemd/systemd/assets/861778/f9ef402b-b729-46ab-b337-d8987d9097e2)

**Comment by hermann-o** [comment]
Same here on ubuntu 24.10. Attached some debug output

_$ **systemd-creds --user encrypt plaintext.txt /tmp/quux.cred --name waldo**
_$ Oct 31 15:38:35 u2410 systemd[1]: Started systemd-creds@12-3707-1000.service - Credential Encryption/Decryption (PID 3707/UID 1000).
Oct 31 15:38:35 u2410 systemd-creds[3708]: Credential secret file '/var/lib/systemd/credential.secret' is not located on encrypted media, using anyway.
Oct 31 15:38:35 u2410 systemd[1]: systemd-creds@12-3707-1000.service: Deactivated successfully.

_$ **systemd-run --user -p LoadCredentialEncrypted=waldo:/tmp/quux.cred /usr/bin/echo moo**
Running as unit: run-r5fcc8a14546f43b598508331593f87da.service; invocation ID: 97f46f6ae6f941fa900de007ed161465
_$ Oct 31 15:38:53 u2410 systemd[1291]: Bus private-bus-connection: changing state UNSET → OPENING
Oct 31 15:38:53 u2410 systemd[1291]: sd-bus: starting bus private-bus-connection on fds 8/8 (socket:[24251], socket:[24251])...
Oct 31 15:38:53 u2410 systemd[1291]: Bus private-bus-connection: changing state OPENING → AUTHENTICATING
Oct 31 15:38:53 u2410 systemd[1291]: Accepting direct incoming connection from 3712 (systemd-run) [n/a]
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1 iface=org.freedesktop.systemd1.Manager
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/job iface=org.freedesktop.systemd1.Job
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Unit
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Automount
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Device
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Mount
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Path
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Scope
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Service
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Slice
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Socket
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Swap
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Target
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/systemd1/unit iface=org.freedesktop.systemd1.Timer
Oct 31 15:38:53 u2410 systemd[1291]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Oct 31 15:38:53 u2410 systemd[1291]: Accepted new private connection.
Oct 31 15:38:53 u2410 systemd[1291]: Bus private-bus-connection: changing state AUTHENTICATING → RUNNING
Oct 31 15:38:53 u2410 systemd[1291]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartTransientUnit  cookie=1 reply_cookie=0 signature=ssa(sv)a(sa(sv)) error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Trying to acquire polkit authentication for 'org.freedesktop.systemd1.manage-units'.
**Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Failed to load configuration: No such file or directory**
Oct 31 15:38:53 u2410 systemd[1291]: home.mount: Failed to load configuration: No such file or directory
Oct 31 15:38:53 u2410 systemd[1291]: home-armin.mount: Failed to load configuration: No such file or directory
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Trying to enqueue job run-r5fcc8a14546f43b598508331593f87da.service/start/fail
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Installed new job run-r5fcc8a14546f43b598508331593f87da.service/start as 238
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Enqueued job run-r5fcc8a14546f43b598508331593f87da.service/start as 238
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=1 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=2 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=3 reply_cookie=1 signature=o error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=4 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=5 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/_2d_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/_2d_2emount interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/shutdown_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/basic_2etarget interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/app_2eslice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: home.mount: Collecting.
Oct 31 15:38:53 u2410 systemd[1291]: home-armin.mount: Collecting.
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=11 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=12 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Will spawn child (service_enter_start): /usr/bin/echo
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Passing 0 fds to service
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: About to execute: /usr/bin/echo moo
Oct 31 15:38:53 u2410 systemd[1291]: Serializing sd-executor-state to memfd.
Oct 31 15:38:53 u2410 systemd[1291]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Forked /usr/bin/echo as 3713 (via CLONE_INTO_CGROUP)
Oct 31 15:38:53 u2410 systemd[1291]: Closing set fd 42 (socket:[10622])
Oct 31 15:38:53 u2410 systemd[1291]: Closing set fd 43 (socket:[10620])
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Changed dead -> running
Oct 31 15:38:53 u2410 systemd[1291]: Failed to connect to /run/systemd/oom/io.systemd.ManagedOOM: No such file or directory
Oct 31 15:38:53 u2410 systemd[1291]: systemd-oomd varlink unix socket not found, skipping user manager varlink setup
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Job 238 run-r5fcc8a14546f43b598508331593f87da.service/start finished, result=done
Oct 31 15:38:53 u2410 systemd[1291]: Started run-r5fcc8a14546f43b598508331593f87da.service - /usr/bin/echo moo.
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=15 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=16 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=17 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=19 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/run_2dr5fcc8a14546f43b598508331593f87da_2eservice interface=org.freedesktop.DBus.Properties member=Get  cookie=2 reply_cookie=0 signature=ss error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Sent message type=method_return sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=20 reply_cookie=2 signature=v error-name=n/a error-message=n/a
Oct 31 15:38:53 u2410 systemd[1291]: Bus private-bus-connection: changing state RUNNING → CLOSING
Oct 31 15:38:53 u2410 systemd[1291]: Bus private-bus-connection: changing state CLOSING → CLOSED
Oct 31 15:38:53 u2410 systemd[1291]: Got disconnect on private connection.
Oct 31 15:38:53 u2410 (echo)[3713]: Skipping PR_SET_MM, as we don't have privileges.
Oct 31 15:38:53 u2410 (echo)[3713]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 31 15:38:53 u2410 (echo)[3713]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to fork off '(sd-mkdcreds)': Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to open superblock context for 'tmpfs': Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to open superblock context for tmpfs: Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Mounting ramfs (ramfs) on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700")...
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to mount ramfs (type ramfs) on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700"): Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to open superblock context for tmpfs: Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Mounting tmpfs (tmpfs) on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700,nr_inodes=1024,size=1048576")...
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to mount tmpfs (type tmpfs) on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_NOSUID|MS_NODEV|MS_NOEXEC "mode=0700,nr_inodes=1024,size=1048576"): Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Bind-mounting /run/user/1000/credentials/run-r5fcc8a14546f43b598508331593f87da.service on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_BIND|MS_REC "")...
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to mount /run/user/1000/credentials/run-r5fcc8a14546f43b598508331593f87da.service (type n/a) on /run/user/1000/systemd/temporary-credentials/run-r5fcc8a14546f43b598508331593f87da.service (MS_BIND|MS_REC ""): Operation not permitted
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to open /var/lib/systemd/credential.secret: Permission denied
Oct 31 15:38:53 u2410 (echo)[3713]: Failed to determine local credential key: Permission denied
Oct 31 15:38:53 u2410 (echo)[3713]: run-r5fcc8a14546f43b598508331593f87da.service: Failed to set up credentials: Permission denied
Oct 31 15:38:53 u2410 (echo)[3713]: run-r5fcc8a14546f43b598508331593f87da.service: Failed at step CREDENTIALS spawning /usr/bin/echo: Permission denied
Oct 31 15:38:53 u2410 systemd[1291]: Received SIGCHLD from PID 3713 ((echo)).
Oct 31 15:38:53 u2410 systemd[1291]: Child 3713 ((echo)) died (code=exited, status=243/CREDENTIALS)
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Child 3713 belongs to run-r5fcc8a14546f43b598508331593f87da.service.
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Main process exited, code=exited, status=243/CREDENTIALS
Oct 31 15:38:53 u2410 systemd[1291]: run-r5fcc8a14546f43b598508331593f87da.service: Failed with result 'exit-code'.
Oct 31 15:38:53 u2410 systemd[1291

**Comment by smlx** [comment]
After some more debugging I think I can see what is going wrong here. The `systemd --user` process is trying to perform the decryption and failing. Instead I guess it should be handing off decryption to the PID 1 `systemd` process? Because obviously `systemd --user` cannot access the TPM device or the `credential.secret` file.
