### ISSUE TITLE
Predictable network interface name changed in an unpredictable way after GPU change

### ISSUE THREAD

**Issue by kord1e** [systemd/systemd#33347]
### Component

systemd, systemd-udevd

### Is your feature request related to a problem? Please describe

I changed my GPU from Nvidia to AMD. Everything else in the computer stayed the same.

As a result, the ethernet interface name was changed from enp5s0 to enp7s0 on Arch Linux.

This caused a lot of confusion at first as I don't use Networkmanager or any GUI tool to manage the network and it took a while to realize what had happened. DHCP client was configured to work on enp5s0 and it was now failing.

On QubesOS this problem caused the network VM to fail to start because the device identifier of the network controller was changed and the old identifier was used to attach the controller to the network VM. This is not related to systemd but this is the root cause of the problem with systemd too - for some reason changing the GPU changed the device identifiers of other devices.

### Describe the solution you'd like

Not sure. 

### Describe alternatives you've considered

The old style of naming (eth0, eth1 etc) would have prevented the problem in this case but it's understandable why the new scheme was developed. 

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by rpigott** [comment]
Maybe https://systemd.io/PREDICTABLE_INTERFACE_NAMES/ can answer your question?

Seems like everything is behaving as designed here. If it isn't useful to you, maybe disable it?

**Comment by poettering** [comment]
This is not actionable to us. We rely on the supposedly stable firmware metadata, but if the firmware renumbers things if you have major PCI topology changes we cannot do anything about that, and this will propagate down into our names.

Sorry, but there's really nothing we can do about it, we consume firmware data, and if firmware is not making it as stable as it should we can't do anything about it.

**Comment by poettering** [comment]
Or in other words, please complain to your board vendor!
