### ISSUE TITLE
Make systemctl is-failed without further arguments into something that checks whether there are any failed units on the system (kinda like `systemctl is-system-running` == failed)

### ISSUE THREAD

**Issue by MalloZup** [systemd/systemd#3335]
### Submission type
- [x ] Bug report
### systemd version the issue has been seen with

> Version: 210-83.2, : 228-103.12, 222.14fc23
### Used distribution
- Opensuse/sles. 
- Fedora 23
### In case of bug report: Expected behaviour you didn't see

> systemctl --failed should return a retcode !=0 when a unit failed
### In case of bug report: Unexpected behaviour you saw

```
systemctl --failed ; echo "RETCODE: $?"
UNIT            LOAD   ACTIVE SUB    DESCRIPTION
apache2.service loaded failed failed The Apache Webserver

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
RETCODE: 0

```
### In case of bug report: Steps to reproduce the problem

> run sytemctl --failed with a failed units.

**Comment by evverx** [comment]
> systemctl --failed should return a retcode !=0 when a unit failed

But why?

Try [`is-system-running`](https://www.freedesktop.org/software/systemd/man/systemctl.html#is-system-running)

> Checks whether the system is operational. This returns success (exit code 0) when the system is fully up and running, specifically not in startup, shutdown or maintenance mode, and with no failed services. Failure is returned otherwise (exit code non-zero). In addition, the current state is printed in a short string to standard output, see the table below.

**Comment by MalloZup** [comment]
Hi @evverx,

thx for anser.! :)
i need this for testing. 

I didn't know , `is-system-running` ,  i think from the syntax/name i wouldn't  think it in a relation with service failures. but ok look's nice.

Honestly o would like the systemctl --failed with retcode, because i can focus on services, and not the whole nices features that `is-system-runnig` offer

**Comment by evverx** [comment]
So, try [`is-failed`](https://www.freedesktop.org/software/systemd/man/systemctl.html#is-failed%20PATTERN...)

> Check whether any of the specified units are in a "failed" state. Returns an exit code 0 if at least one has failed, non-zero otherwise. Unless --quiet is specified, this will also print the current unit state to standard output.

``` sh
$ systemctl --failed --no-pager --no-legend
fail.service loaded failed failed fail.service

$ systemctl is-failed '*' -q
$ echo $?
0

$ sudo systemctl reset-failed

$ systemctl is-failed '*' -q
$ echo $?
1
```

**Comment by MalloZup** [comment]
@evverx ,

ok it works nice this for me. it's a good compromise. we can take the issue open, if you see this enchantment, otherwise thanks a lot for the good support

**Comment by poettering** [comment]
Note that "--failed" is deprecated in newer systemd versions, please use "systemctl --state=failed" now. And yeah, "systemctl is-system-running" is what you want.

I figure it wouldn't hurt turning "systemctl is-failed" with no further arguments into a way to query whether there are any system services that failed around. Will now convert this issue into an RFE for that. I hope that makes sense.
