### ISSUE TITLE
User session fails `Failed to create session: Invalid session class manager`

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#33403]
### systemd version the issue has been seen with

256

### Used distribution

archlinux

### Linux kernel version used

6.9.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

`systemctl --user` fails with `Connection refused`: 
```
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/xxx/bus"}, 21) = -1 ECONNREFUSED (Connection refused
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd[1]: Starting User Manager for UID xxx...
(systemd)[899484]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[xxx] ruser=[<unknown>] rhost=[<unknown>]
(systemd)[899484]: pam_unix(systemd-user:session): session opened for user xxx(uid=xxx) by xxx(uid=0)
(systemd)[899484]: pam_systemd(systemd-user:session): Failed to create session: Invalid session class manager
systemd[899484]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
systemd[1]: user@xxx.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by YHNdnzj** [comment]
Did you restart logind / your system after updating to v256?

**Comment by SjonHortensius** [comment]
> Did you restart logind / your system after updating to v256?

yes - I restarted the machine
