### ISSUE TITLE
RFE: ProvisionInitrdPath: initramfs resource provisioning hint

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [systemd/systemd#3340]
### Submission type
- [ ] Bug report
- [x ] Request for enhancement (RFE)
### proposed new service unit entry: ProvisionInitrdPath

1) there is an established convention, when

```
 ConditionPathExists=/etc/initrd-release 
```

is used to indicate a service which is to run only inside initramfs

2) there are precedents for auto provisioning of initramfs systemd dependencies via `Requires`, `ExecStart`, etc:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/initcpio-install-systemd?h=packages/systemd#n48

```
        case $key in
            Requires|OnFailure)
                # only add hard dependencies (not Wants)
                map add_systemd_unit "${values[@]}"
                ;;
            Exec*)
                # don't add binaries unless they are required
                if [[ ${values[0]:0:1} != '-' ]]; then
                    add_binary "${values[0]}"
                fi
                ;;
        esac
```

3) this RFE is request to introduce a new systemd entry `ProvisionInitrdPath`
which could be used as a hint for the initramfs builder (dracut, mkinitcpio, ...)

4) use case: for configuration management, it would be easier to have both the binary and the related
resource specified in single place / context, for example:

```
ExecStart=/bin/hello
ProvisionInitrdPath=/etc/hello
ConditionPathExists=/etc/hello
ConditionPathExists=/etc/initrd-release 
```

**Comment by Andrei-Pozolotin** [comment]
see also https://bugs.archlinux.org/task/49460

**Comment by evverx** [comment]
Maybe, I'm missing something. But why not `X-ProvisionInitrdPath`?

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description

> Unit files may contain additional options on top of those listed here. If systemd encounters an unknown option, it will write a warning log message but continue loading the unit. If an option or section name is prefixed with X-, it is ignored completely by systemd. Options within an ignored section do not need the prefix. Applications may use this to include additional information in the unit files.

**Comment by Andrei-Pozolotin** [comment]
@evverx Evgeny  you are right, except I can not make variable substitution to work:

```
[Service]
Environment=SHELL_DIR=/etc/mkinitcpio.d
[X-SystemdTool]
ProvisionInitrdPath=${SHELL_DIR}/shell.sh # <--------- here
```

now what am I missing? :-)

**Comment by poettering** [comment]
@Andrei-Pozolotin env var substitution is only supported on ExecXYZ= lines. See the manpage of those.

Anyway, "X-" is really what you should be using here, hence closing this.

**Comment by Andrei-Pozolotin** [comment]
ok, that will work too. thanks.
