### ISSUE TITLE
user@.service is now required for a login session

### ISSUE THREAD

**Issue by Earnestly** [systemd/systemd#33405]
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.9.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

loginctl, systemd-logind

### Expected behaviour you didn't see

I don't personally use `systemd --user` and have masked `user@1000.service` for a number of years.

This situation used to work quite well as I was able to log in using `/bin/login` and establish login session as listed by `loginctl`, with appropriate permissions/ACLs, `XDG_RUNTIME_DIR` configured, etc.

### Unexpected behaviour you saw

However since 256 after logging in I see no sessions via `loginctl` which breaks a few tools and prevents starting an xserver as my user lacks sufficient permission on `/dev/dri/cardN`.

### Steps to reproduce the problem

* `systemctl mask user@1000.service`
* Attempt to log in via `login`

**Comment by poettering** [comment]
Please provide logs that show the problem, otherwise this is not actionable.

**Comment by Earnestly** [comment]
Yes, fair point. I had thought there weren't any useful logs and wanted to ask if I needed to increase verbosity somewhere but looking I find this:

```
Jun 19 09:27:26 teapot login[591]: pam_systemd_home(login:auth): New sd-bus connection (system-bus-pam-systemd-home-591) opened.
Jun 19 09:27:26 teapot dbus-broker-launch[480]: Activation request for 'org.freedesktop.home1' failed: The systemd unit 'dbus-org.freedesktop.home1.service' could not be found.
Jun 19 09:27:28 teapot login[591]: pam_unix(login:session): session opened for user earnest(uid=1000) by earnest(uid=0)
Jun 19 09:27:28 teapot login[591]: pam_systemd(login:session): New sd-bus connection (system-bus-pam-systemd-591) opened.
Jun 19 09:27:28 teapot systemd[1]: Created slice User Slice of UID 1000.
Jun 19 09:27:28 teapot systemd[1]: Starting User Runtime Directory /run/user/1000...
Jun 19 09:27:28 teapot systemd-logind[485]: Failed to start session scope session-1.scope: Unit user@1000.service is masked.
Jun 19 09:27:28 teapot login[591]: pam_systemd(login:session): Failed to create session: Unit user@1000.service is masked.
Jun 19 09:27:28 teapot login[591]: LOGIN ON tty1 BY earnest
Jun 19 09:27:28 teapot systemd[1]: Finished User Runtime Directory /run/user/1000.
Jun 19 09:27:38 teapot systemd[1]: Stopping User Runtime Directory /run/user/1000...
Jun 19 09:27:39 teapot systemd[1]: run-user-1000.mount: Deactivated successfully.
Jun 19 09:27:39 teapot systemd[1]: user-runtime-dir@1000.service: Deactivated successfully.
Jun 19 09:27:39 teapot systemd[1]: Stopped User Runtime Directory /run/user/1000.
Jun 19 09:27:39 teapot systemd[1]: Removed slice User Slice of UID 1000.
Jun 19 09:27:47 teapot systemd[1]: systemd-hostnamed.service: Deactivated successfully.
```

I don't mind providing more information or running in any specific debug modes if you would like more detail; just throw commands at me and I'll see what I can do.

**Comment by YHNdnzj** [comment]
Hmm, right. The behavior was changed in 52bcc872b, and now `Requires=` is used for `user@.service`.

**Comment by Kangie** [comment]
Is this actually a regression? The commit message seems to indicate that this was intentional:

> logind-session: use Requires= for user{,-runtime-dir}@.service
>
> Since we do require these basic user services, let's make
> the dependency stronger.

Is this a docs issue?
