### ISSUE TITLE
run0: Error message should be more explicit when polkit is missing

### ISSUE THREAD

**Issue by ShaftInc** [systemd/systemd#33418]
### Component

other

### Is your feature request related to a problem? Please describe

The new `run0` utility relies on `polkit` for authentification.

`polkit` may not be installed automatically alongside systemd (eg. on Debian Trixie/sid as of version 256-1.1).

In such case, the error message returned by `run0` seems too generic. Eg. on Debian Trixie:

```
$ run0 ls /tmp
Failed to start transient service unit: Access denied
```

### Describe the solution you'd like

`run0` should test for `polkit` presence and inform users of its absence, eg.

```
$ run0 ls /tmp
Failed to start transient service unit: polkit is missing, cannot perform authentification
```

or something equivalent :)

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by mauri870** [comment]
Thanks for opening this issue! I faced the same problem on Arch Linux.

Debugging this, it seems that we are not handling execve errors here, so it just fails silently:

https://github.com/systemd/systemd/blob/11a66a95eca64e57a682142e9f44fa99c7dfdaf3/src/shared/exec-util.c#L611-L612
