### ISSUE TITLE
networkd: since v256 IPv6Forwarding doesn't forward any packets

### ISSUE THREAD

**Issue by freswa** [systemd/systemd#33414]
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.9.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When `IPv6Forwarding=` is set to `yes` on all devices, the machine forwards IPv6 packets.

### Unexpected behaviour you saw

The machine dropped all the packets unless `/proc/sys/net/ipv6/conf/all/forwarding` was set to 1.

### Steps to reproduce the problem

1. Set `IPv6Forwarding=yes` on some or all interfaces.
2. See no packets going through
3. Set `echo 1 | tee /proc/sys/net/ipv6/conf/all/forwarding`
4. See packets going through

**Comment by IlyaMZP** [comment]
I can confirm this, after update to systemd-256 (and 256.1) ipv6 forwarding stopped working.
Here are the configs for the WAN and LAN interfaces I use. I replaced IPForward=yes to IPv4Forwarding=yes and IPv6Forwarding=yes after updating to 256.
```[Match]
Name=end0

[Network]
Description=WAN Interface
LinkLocalAddressing=ipv6
IPv6AcceptRA=yes
DHCP=yes
IPv4Forwarding=yes
IPv6Forwarding=yes

[DHCPv4]
Hostname=router
UseHostname=no
UseDNS=yes
UseNTP=no
UseSIP=no
UseRoutes=no
UseGateway=yes

[IPv6AcceptRA]
UseDNS=no
DHCPv6Client=yes
```

```[Match]
Name=enp1s0

[Link]
RequiredForOnline=no

[Network]
Description=LAN Interface
Address=10.0.0.1/24
DHCPServer=yes
IPv6SendRA=yes
IPv6AcceptRA=no
DHCPv6PrefixDelegation=yes
IPMasquerade=ipv4
LinkLocalAddressing=ipv6
IPv6DuplicateAddressDetection=1

[DHCPServer]
PoolOffset=20
PoolSize=150
EmitDNS=yes
DNS=8.8.8.8

[IPv6SendRA]
EmitDNS=yes
EmitDomains=no

[DHCPPrefixDelegation]
UplinkInterface=end0
SubnetId=0x1
Announce=yes
```

**Comment by freswa** [comment]
The implementation for `IPv4Forwarding` and `IPv6Forwarding` seems to have similar behavior. It sets `/proc/sys/net/ipv<4/6>/conf/<ifname>/forwarding` to `1`. While this is the correct behavior for IPv4, It's not for IPv6. From the kernel docs:
```
/proc/sys/net/ipv6/* Variables:
[...]
conf/all/forwarding - BOOLEAN
	Enable global IPv6 forwarding between all interfaces.

	IPv4 and IPv6 work differently here; e.g. netfilter must be used
	to control which interfaces may forward packets and which not.

	This also sets all interfaces' Host/Router setting
	'forwarding' to the specified value.  See below for details.

	This referred to as global forwarding.

[...]

conf/interface/*:
	Change special settings per interface.

	The functional behaviour for certain settings is different
	depending on whether local forwarding is enabled or not.

[...]


forwarding - INTEGER
	Configure interface-specific Host/Router behaviour.

	Note: It is recommended to have the same setting on all
	interfaces; mixed router/host scenarios are rather uncommon.

	Possible values are:
		0 Forwarding disabled
		1 Forwarding enabled

	FALSE (0):

	By default, Host behaviour is assumed.  This means:

	1. IsRouter flag is not set in Neighbour Advertisements.
	2. If accept_ra is TRUE (default), transmit Router
	   Solicitations.
	3. If accept_ra is TRUE (default), accept Router
	   Advertisements (and do autoconfiguration).
	4. If accept_redirects is TRUE (default), accept Redirects.

	TRUE (1):

	If local forwarding is enabled, Router behaviour is assumed.
	This means exactly the reverse from the above:

	1. IsRouter flag is set in Neighbour Advertisements.
	2. Router Solicitations are not sent unless accept_ra is 2.
	3. Router Advertisements are ignored unless accept_ra is 2.
	4. Redirects are ignored.

	Default: 0 (disabled) if global forwarding is disabled (default),
		 otherwise 1 (enabled).
```

Which means we have to enable global forwarding whenever a single interface has `IPv6Forwarding` set afaiu.

**Comment by yuwata** [comment]
Please use `IPv6Forwarding=yes` in networkd.conf, rather than .network file, it controls `/proc/sys/net/ipv6/conf/all/forwarding`.
This is not a bug in networkd, but how the kernel designed, or at most, a bug in the kernel.

**Comment by YHNdnzj** [comment]
> Please use `IPv6Forwarding=yes` in networkd.conf, rather than .network file, it controls `/proc/sys/net/ipv6/conf/all/forwarding`. This is not a bug in networkd, but how the kernel designed, or at most, a bug in the kernel.

Yet it would be very confusing to users in this case? I think this at the minimum deserves proper documentation on our side. Also, on top of that we should enable global forwarding in kernel if the global `IPv6Forward=` is not set, but one interface enables forwarding. Then, disable the per-interface forwarding for all other interfaces.

Currently, the behavior is completely broken. We claim that `IPMasquerade=yes` would imply `IPv4/v6Forward`, yet without enabling it globally that could not work.

**Comment by yuwata** [comment]
First of all, why `/proc/sys/net/ipv6/conf/all/forwarding` needs to be enabled? I cannot find anything special for the sysctl value. It seems to simply enable IPv6 forwarding for all interfaces.

**Comment by yuwata** [comment]
Ah, `ip6_forward()`...

**Comment by yuwata** [comment]
OK. I will update documentation.

**Comment by larsch** [comment]
> First of all, why `/proc/sys/net/ipv6/conf/all/forwarding` needs to be enabled? I cannot find anything special for the sysctl value. It seems to simply enable IPv6 forwarding for all interfaces.

https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch11s02.html

Per-device enabling of IPv6 forwarding is not a thing. `IPv6Forwarding=true` for a single interface does not do what you probably think. `/proc/sys/net/ipv6/all/forwarding` needs to be 1 for any forwarding to take place. `/proc/sys/net/ipv6/all/<interface>/forwarding`  does not enable/disable forwarding, but changes between router and host mode, affecting behaviour of NA/RA/etc, not whether packets are forwarded.

E.g. here, setting all/forwarding=1 and eth0/forwarding=0, it still happily forwards IPv6.

This appears to me to be a regression in systemd 256 with the change to IPForward= (and implied setting from IPv6SendRA)

**Comment by larsch** [comment]
> First of all, why `/proc/sys/net/ipv6/conf/all/forwarding` needs to be enabled? I cannot find anything special for the sysctl value. It seems to simply enable IPv6 forwarding for all interfaces. 

https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch11s02.html

Per-device enabling/disabling of IPv6 forwarding is not a thing. `IPv6Forwarding=true` for a single interface does not do what you probably think. `/proc/sys/net/ipv6/all/forwarding` needs to be 1 for any forwarding to take place. `/proc/sys/net/ipv6/all/<interface>/forwarding`  does not enable/disable forwarding, but changes between router and host mode, affecting behaviour of NA/RA/etc, not whether packets are forwarded. This is very different from `net/ipv4/ip_forward` behaviour.

E.g. here, setting all/forwarding=1 and eth0/forwarding=0, it still happily forwards IPv6.

This appears to me to be a regression in systemd 256 with the change to `IPForward=` (and implied setting from IPv6SendRA), since it used to be enabled by default via `IPv6SendRA=true`.

The suggested changed to the documentation are still not entirely correct, as you cannot disable forwarding on a single interface even when enabled globally. This can only be done with netfilter.

**Comment by bbx0** [comment]
I came across this issue as my WireGuard tunnel stopped working for IPv6 when the uplink is configured with DHCP.

The chain of events as far I understand it:

- IP Forwarding behavior changed with systemd 256
- `IPMasquerade=both` no longer enables IP Forward for IPv6 and `IPv6Forwarding=yes` has to be set manually to enable it globally first.
- Setting `IPv6Forwarding=yes` causes implicitly `IPv6AcceptRA` to default to `false`, which in turn renders a `DHCP=yes` directive ineffective for IPv6. `IPv6AcceptRA=yes` has to be set manually to start the DHCPv6 Client on the uplink interface.
 
This is a minimal config to restore the old behavior:
```systemd
# /etc/systemd/networkd.conf.d/90-forward.conf
[Network]
# As of systemd 256 IPv6 Forwarding is not enabled by the `IPMasquerade=both` option on the wg0.network interface.
# https://github.com/systemd/systemd/issues/33414#issuecomment-2185268106
IPv4Forwarding=yes
IPv6Forwarding=yes

# /etc/systemd/network/en.network
# Uplink interface configured with DHCP
[Match]
Name=en*
[Network]
DHCP=yes
# IPv6 Forwarding disables IPv6AcceptRA by default. Re-enable it for the DHCPv6 client.
IPv6AcceptRA=yes
```

**Comment by sfan5** [comment]
As far as I can tell this affects IPv4 equally. I noticed that nspawn containers started with `--network-veth` would no longer have working internet access unless I manually set `net.ipv4.ip_forward=1`.
`/usr/lib/systemd/network/80-container-ve.network` has `IPMasquerade=both`, which used to imply and enable forwarding.

If this is intentional that would be quite confusing from an user perspective.

**Comment by andrejpodzimek** [comment]
Apropos, is it expected that `lo` will be getting `net.ipv6.conf.lo.forwarding = 1` (!) (and also the counterpart for IPv4), and that this cannot be switched off using a configuration file like this one?

```ini
[Match]
Name=lo

[Network]
IPv6Forwarding=no  # No effect!
IPv4Forwarding=no  # No effect!
```

Sure, `lo` won’t route anywhere, because `::1` is not exactly globally routable, but still … seeing forwarding switched *on* on that interface raises a red flag in an admin’s mind, like _“is all the clear text frontend-to-backend traffic on `lo` safe?”_.

This entire setup is weird, indeed, especially in the way it treats IPv6 and IPv4 differently.

**Comment by arvidjaar** [comment]
> `lo` won’t route anywhere

IPv6 per-interface `forwarding` sysctl has nothing to do with routing. If you find it weird, complaint to kernel folks. Having `net.ipv6.conf.lo.forwarding = 1` makes sense - what would you want it to send Router Solicitation messages?

**Comment by andrejpodzimek** [comment]
> IPv6 per-interface `forwarding` sysctl has nothing to do with routing.

It does have a lot to do with routing, because L2 and L3 are quite inseparably intertwined. According to [the documentation](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt), _“configure interface-specific Host/Router behaviour”_ is what it ought to be doing.

> Having `net.ipv6.conf.lo.forwarding = 1` makes sense - what would you want it to send Router Solicitation messages?

The exact opposite. `accept_ra` should be disabled, so too should be `ucast_solicit` and (of course) `forwarding`. (Despite the fact that “enabling” any of that on `lo` is ineffective and meaningless.)

What I would _want_ at the very least is for the configuration snippet [mentioned above](https://github.com/systemd/systemd/issues/33414#issuecomment-2427926844) to be honored rather than (logged but) ignored.

**Comment by cooperlees** [comment]
I'm late to the party here,. but I just upgraded from 255 in Ubuntu 24.10 to 257.4 in 25.04 and I think I've hit this issue. The kernel is `6.14.0-15-generic`.

So I've applied the workarounds talked bout in this thread but have not been successful getting IPv6 forwarding to work. 

I set the IPv on each `.network` file I want forwarding (but I read it only effects RAs etc.) and made a global setting via /etc/systemd/networkd.conf.d/forwarding.conf

```
[Network]
IPv4Forwarding=yes
IPv6Forwarding=yes
```

This is confirm loaded via `sudo systemd-analyze cat-config /etc/systemd/networkd.conf` but I am still unable to forward IPv6. IPv4 is working fine.

As expected if i ping interfaces on my router from a directly connected host with global and site loca IPv6 it works, but if I try to route anything, I see the packet ingress with `tcpdump` but never egress anywhere. sysctls als look right:

```
cooper@home1:~$ sudo sysctl -a | grep ipv[46].*forward.*1
net.ipv4.conf.all.forwarding = 1
net.ipv4.conf.astound.forwarding = 1
net.ipv4.conf.att.forwarding = 1
net.ipv4.conf.br-f90c578ba969.forwarding = 1
net.ipv4.conf.default.forwarding = 1
net.ipv4.conf.docker0.forwarding = 1
net.ipv4.conf.eno3.forwarding = 1
net.ipv4.conf.eno4.forwarding = 1
net.ipv4.conf.ens2f0.forwarding = 1
net.ipv4.conf.ens2f1.forwarding = 1
net.ipv4.conf.lo.forwarding = 1
net.ipv4.conf.veth05625ce.forwarding = 1
net.ipv4.conf.veth0634a57.forwarding = 1
net.ipv4.conf.veth0feda6f.forwarding = 1
net.ipv4.conf.veth24f246c.forwarding = 1
net.ipv4.conf.veth36d1116.forwarding = 1
net.ipv4.conf.veth4d45f1d.forwarding = 1
net.ipv4.conf.veth5312b4a.forwarding = 1
net.ipv4.conf.veth7815db3.forwarding = 1
net.ipv4.conf.veth86ced53.forwarding = 1
net.ipv4.conf.veth8d2a0ab.forwarding = 1
net.ipv4.conf.veth987c2d0.forwarding = 1
net.ipv4.conf.vethd0b44b4.forwarding = 1
net.ipv4.conf.vethd1fb47a.forwarding = 1
net.ipv4.conf.vetheec4ffc.forwarding = 1
net.ipv4.conf.vethfec54d7.forwarding = 1
net.ipv4.conf.vlan69.forwarding = 1
net.ipv4.conf.vlan70.forwarding = 1
net.ipv4.conf.wg0.forwarding = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward_update_priority = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.astound.forwarding = 1
net.ipv6.conf.att.forwarding = 1
net.ipv6.conf.br-f90c578ba969.forwarding = 1
net.ipv6.conf.default.forwarding = 1
net.ipv6.conf.docker0.forwarding = 1
net.ipv6.conf.eno3.forwarding = 1
net.ipv6.conf.eno4.forwarding = 1
net.ipv6.conf.ens2f0.forwarding = 1
net.ipv6.conf.ens2f1.forwarding = 1
net.ipv6.conf.lo.forwarding = 1
net.ipv6.conf.veth05625ce.forwarding = 1
net.ipv6.conf.veth0634a57.forwarding = 1
net.ipv6.conf.veth0feda6f.forwarding = 1
net.ipv6.conf.veth24f246c.forwarding = 1
net.ipv6.conf.veth36d1116.forwarding = 1
net.ipv6.conf.veth4d45f1d.forwarding = 1
net.ipv6.conf.veth5312b4a.forwarding = 1
net.ipv6.conf.veth7815db3.forwarding = 1
net.ipv6.conf.veth86ced53.forwarding = 1
net.ipv6.conf.veth8d2a0ab.forwarding = 1
net.ipv6.conf.veth987c2d0.forwarding = 1
net.ipv6.conf.vethd0b44b4.forwarding = 1
net.ipv6.conf.vethd1fb47a.forwarding = 1
net.ipv6.conf.vetheec4ffc.forwarding = 1
net.ipv6.conf.vethfec54d7.forwarding = 1
net.ipv6.conf.vlan69.forwarding = 1
net.ipv6.conf.vlan70.forwarding = 1
net.ipv6.conf.wg0.forwarding = 1
```

All the veths are dual stacked docker containers ... Any ideas on what to try?
