### ISSUE TITLE
udevd races with itself over flocks

### ISSUE THREAD

**Issue by mvollmer** [systemd/systemd#3343]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

master, bbed3b8efdff7
### Used distribution

Fedora 24
### In case of bug report: Unexpected behaviour you saw

udevd tries to take a LOCK_SH flock when processing a block device, and it also tries to take a LOCK_EX flock when synthesizing a change event for devices watched via inotify.

These locks happen in separate processes and can interfere with each other.  The shared lock taken by the rule processing can cause a BLKRRPART to be skipped, and the exclusive lock taken by the inotify processing can cause rules to be skipped.

I have never seen the exclusive lock prevent rule processing.  That lock is taken only for a very short time around a single BLKRRPART ioctl.  It looks super unlikely that the exclusive lock might ever cause a rule to be skipped, but it probably has happened out there a couple of times and people never figured out what was going on.

I do see the shared lock preventing the BLKRRPART ioctl very often.  Skipping the BLKRRPART ioctl is harmless (and even a good thing IMO), but skipping it only sometimes and doing it at other times increases the shittyness of the OS.

Here is a edited strace log for a case when the shared lock prevents the BLKRRPART ioctl:

```[pid  6590] open("/dev/sda", O_RDONLY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC) = 7
[pid  6590] flock(7, LOCK_SH|LOCK_NB)   = 0
[...]
[pid   838] open("/dev/sda", O_RDONLY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC) = 14
[pid   838] flock(14, LOCK_EX|LOCK_NB)  = -1 EAGAIN (Resource temporarily unavailable)
[pid   838] close(14)                   = 0
[...]
[pid  6590] close(7)                    = 0

```
```

**Comment by msekletar** [comment]
Hmm, isn't this happening because some external program ignores shared lock taken by worker and writes to the device anyway?

As for your concern about skipping rules processing. I think that this can't happen because if device just showed up then there is no inotify watch in place so rules should be processed. As for change events, well those are generated by udev itself, strictly after exclusive lock was already released.

**Comment by mvollmer** [comment]
> Hmm, isn't this happening because some external program ignores shared lock taken by worker and writes to the device anyway?

The external program that produces the strace excerpt was `parted mkpart`.  As far as I know, it doesn't take locks.  Should it?

> As for your concern about skipping rules processing. I think that this can't happen because if device just showed up then there is no inotify watch in place so rules should be processed. As for change events, well those are generated by udev itself, strictly after exclusive lock was already released.

There might be other sources of "change" events, and if the inotify events come quickly enough, the rule processing triggered by a previous one might overlap the inotity processing of the next one, but of course there will be final "change" event eventually that doesn't overlap with anything.  So, yeah, I agree.

**Comment by poettering** [comment]
Hmm, looking at the code, if we can't take the lock of if the ioctl fails we'll fallback to synthesizing a change event on the device, which should keep us covered for all eventualities, no? If you so will the ioctl approach is just a trick to make this quicker if we can by letting the kernel to synthesize this all by itself

**Comment by poettering** [comment]
> The external program that produces the strace excerpt was `parted mkpart`. As far as I know, it doesn't take locks. Should it?

Yes, it should. See https://systemd.io/BLOCK_DEVICE_LOCKING

**Comment by poettering** [comment]
> Hmm, looking at the code, if we can't take the lock of if the ioctl fails we'll fallback to synthesizing a change event on the device, which should keep us covered for all eventualities, no? If you so will the ioctl approach is just a trick to make this quicker if we can by letting the kernel to synthesize this all by itself

Let's close this, since I am pretty sure this works correctly already, see above. If it doesn't please report back and we can reopen this.
