### ISSUE TITLE
Do not add the BSOD (Blue Screen Of Death) to SystemD / Linux.

### ISSUE THREAD

**Issue by ncorbuk** [systemd/systemd#33442]
### Component

other

### Is your feature request related to a problem? Please describe

Experiencing a BSOD (Blue Screen Of Death) on Linux is something I’d rather avoid, and I believe many others feel the same way. After all, we already have log files available for diagnosing system freezes or crashes, which are relatively rare on Linux. During a kernel panic, there’s little you can do anyway, so having a BSOD appear with an error message during a forced reset isn’t particularly helpful. It would be beneficial to provide users with the option to enable or disable this feature. 

Systemd has been a topic of debate in the Linux community, and some users worry that it might negatively impact the system. Additionally, there’s concern about new Linux users, often referred to as ‘noobs’ or ‘normies,’ coming from Windows. These users may inadvertently push for changes that make Linux more similar to Windows, which could be frustrating for long-time Linux enthusiasts.

However, it’s essential to recognize that Linux has a rich history and a diverse user base. While some people prefer the simplicity of Windows, others appreciate the flexibility and control that Linux offers. Log files and troubleshooting tools are available, making it relatively straightforward to diagnose and address issues.

Rather than assuming that everyone should use Linux, we should celebrate the diversity of operating systems. Linux isn’t for everyone, and that’s okay. It’s essential to educate users about their options and encourage respectful discussions about the pros and cons of different platforms.

Could we refrain from attempting to ‘normie-fy’ Linux unnecessarily? The Linux community doesn’t want Linux to resemble Windows. Frankly, we don’t need everyone to use Linux. The proposed BSOD (Blue Screen of Death) would only benefit those who might be better suited for Windows. No offense intended.

### Describe the solution you'd like

Please refrain from adding the Blue Screen of Death (BSOD) to SystemD.

### Describe alternatives you've considered

If you decide to include it, make it an option that users can toggle on or off, with the default setting being ‘off’.

**Comment by yuwata** [comment]
You can always disable the feature.
