### ISSUE TITLE
run0 Allows execution on host container from container

### ISSUE THREAD

**Issue by xavloose** [systemd/systemd#33455]
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.9.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

run0 inside of a toolbox rootless container to execute the command with elevated privileges inside the container

### Unexpected behaviour you saw

invoking run0 inside a toolbox container executed the command on the host OS instead of the container.

### Steps to reproduce the problem

Base Arch Linux Install
Install toolbox and podman with rootless containers

I am an administrator on the Host OS so I don't believe this demonstrates a privilege escalation issue at this time. 

```shell
toolbox create
toolbox enter

# Install a package that doesn't exist in base.
# This also created unexpected behavior with pacman as it encountered issues I didn't expect to occur but I realize now it's most likely related to this. It appeared to work though
run0 pacman -Syu --noconfirm && run0 pacman -S --noconfirm 

clang
#zsh: command not found: clang

# Leave toolbox
exit
clang
#clang: error: no input files
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
This was done using toolbox but I don't believe it is a toolbox issue. As far as I understand I should be operating in a cgroup that should not allow this. I don't think run0 should have allowed me to execute code with elevated privileges on the host os from any sort of container.

I could not reproduce this easily with generic rootless containers. I believe it is related to how toolbox will bind certain aspects of the host os.

I wasn't sure if this fell under security issues doctrine of reporting since I couldn't demonstrate privilege escalation with it. This does suggest a potential vector of an attack though so I think it should be addressed.
```

**Comment by YHNdnzj** [comment]
Well, I've never used the said `toolbox` utility and have no idea about what the purpose/security guarantees it has, but it simply binds the host's system bus into the container: https://github.com/containers/toolbox/blob/cb6eee85ef88a0dc8694707d29737f61fa0ac330/toolbox#L1102. `systemd-run`/`run0` starts new processes by calling `StartTransientUnit()` dbus method, hence as long as you're connecting to the system bus of the host, you obviously can invoke processes outside of container/namespace.

Please consult the `toolbox` people for their security model and whether this is considered a problem. There's nothing actionable on systemd's side. Closing.
