### ISSUE TITLE
testsuite: test-dns-packet fails on sparc64 with bus error (unaligned access)

### ISSUE THREAD

**Issue by glaubitz** [systemd/systemd#3346]
Hi!

The testsuite crashes on sparc64 at test-dns-packet with a bus error which means an unaligned access:

root@deb4g:~/systemd# ./test-dns-packet 
============== /root/systemd/src/resolve/test-data/_443._tcp.fedoraproject.org.pkts ==============
_443._tcp.fedoraproject.org IN NSEC aarch64pkgs.fedoraproject.org ( RRSIG NSEC TLSA )
Bus error
root@deb4g:~/systemd#

With the help of gdb, the issue is tracked down to:

root@deb4g:~/systemd# gdb ./test-dns-packet
GNU gdb (Debian 7.10-1+b1) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "sparc64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test-dns-packet...done.
(gdb) run
Starting program: /root/systemd/test-dns-packet 
BFD: /usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/32/5145ec18ef1f1729dd9480cb374706fb208225.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/32/5145ec18ef1f1729dd9480cb374706fb208225.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/32/5145ec18ef1f1729dd9480cb374706fb208225.debug" has no build-id, file skipped
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/sparc64-linux-gnu/libthread_db.so.1".
BFD: /usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug" has no build-id, file skipped
============== /root/systemd/src/resolve/test-data/_443._tcp.fedoraproject.org.pkts ==============
_443._tcp.fedoraproject.org IN NSEC aarch64pkgs.fedoraproject.org ( RRSIG NSEC TLSA )

Program received signal SIGBUS, Bus error.
0x0000010000007500 in test_packet_from_file (filename=0x10000184010 "/root/systemd/src/resolve/test-data/_443._tcp.fedoraproject.org.pkts", canonical=false)
    at src/resolve/test-dns-packet.c:59
59                  packet_size = le64toh( _(uint64_t_)(data + offset) );
(gdb) bt
#0  0x0000010000007500 in test_packet_from_file (filename=0x10000184010 "/root/systemd/src/resolve/test-data/_443._tcp.fedoraproject.org.pkts",

```
canonical=false) at src/resolve/test-dns-packet.c:59
```
#1  0x0000010000007cbc in main (argc=1, argv=0x7fefffff688) at src/resolve/test-dns-packet.c:106

(gdb)

**Comment by poettering** [comment]
Fixed by #3360 I presume. Closing.
