### ISSUE TITLE
testsuite: test-dhcp-server fails on sparc64 with bus error (unaligned access)

### ISSUE THREAD

**Issue by glaubitz** [systemd/systemd#3347]
Running test-dhcp-server on sparc64 results in a bus error (unaligned access):

root@deb4g:~/systemd# ./test-dhcp-server 
Assertion '!server->event' failed at src/libsystemd-network/sd-dhcp-server.c:215, function sd_dhcp_server_attach_event(). Ignoring.
Assertion '!server->event' failed at src/libsystemd-network/sd-dhcp-server.c:215, function sd_dhcp_server_attach_event(). Ignoring.
Assertion 'server->address != htobe32(INADDR_ANY)' failed at src/libsystemd-network/sd-dhcp-server.c:1016, function sd_dhcp_server_start(). Ignoring.
Assertion 'address->s_addr != INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:47, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'prefixlen <= 32' failed at src/libsystemd-network/sd-dhcp-server.c:48, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'server->address == INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:49, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'address->s_addr != INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:47, function sd_dhcp_server_configure_pool(). Ignoring.
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
Assertion '!server->receive_message' failed at src/libsystemd-network/sd-dhcp-server.c:1013, function sd_dhcp_server_start(). Ignoring.
DHCP SERVER: STOPPED
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: REQUEST (rebinding/renewing) (0x12345678)
DHCP SERVER: REQUEST (init-reboot) (0x12345678)
DHCP SERVER: NAK (0x12345678)
Bus error
root@deb4g:~/systemd#

With the help of gdb, this can be tracked down to:

root@deb4g:~/systemd# gdb ./test-dhcp-server 
GNU gdb (Debian 7.10-1+b1) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "sparc64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test-dhcp-server...done.
(gdb) run
Starting program: /root/systemd/test-dhcp-server 
BFD: /usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/4a/2be3888dfebbf721816e4df21fa6546ccf8e59.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/ed/63d2926f7520f092ee384e19ca24b97dd9a576.debug" has no build-id, file skipped
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/sparc64-linux-gnu/libthread_db.so.1".
BFD: /usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug: unable to initialize decompress status for section .debug_aranges
warning: File "/usr/lib/debug/.build-id/12/90c8994b140089995829701b1a6e56d9e138f5.debug" has no build-id, file skipped
Assertion '!server->event' failed at src/libsystemd-network/sd-dhcp-server.c:215, function sd_dhcp_server_attach_event(). Ignoring.
Assertion '!server->event' failed at src/libsystemd-network/sd-dhcp-server.c:215, function sd_dhcp_server_attach_event(). Ignoring.
Assertion 'server->address != htobe32(INADDR_ANY)' failed at src/libsystemd-network/sd-dhcp-server.c:1016, function sd_dhcp_server_start(). Ignoring.
Assertion 'address->s_addr != INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:47, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'prefixlen <= 32' failed at src/libsystemd-network/sd-dhcp-server.c:48, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'server->address == INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:49, function sd_dhcp_server_configure_pool(). Ignoring.
Assertion 'address->s_addr != INADDR_ANY' failed at src/libsystemd-network/sd-dhcp-server.c:47, function sd_dhcp_server_configure_pool(). Ignoring.
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
Assertion '!server->receive_message' failed at src/libsystemd-network/sd-dhcp-server.c:1013, function sd_dhcp_server_start(). Ignoring.
DHCP SERVER: STOPPED
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
DHCP SERVER: UNREF
DHCP SERVER: STOPPED
DHCP SERVER: STARTED
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: DISCOVER (0x12345678)
DHCP SERVER: OFFER (0x12345678)
DHCP SERVER: REQUEST (rebinding/renewing) (0x12345678)
DHCP SERVER: REQUEST (init-reboot) (0x12345678)
DHCP SERVER: NAK (0x12345678)

Program received signal SIGBUS, Bus error.
0x000001000000c410 in parse_request (code=54 '6', len=4 '\004', option=0x7fefffff20a, userdata=0x10000184730) at src/libsystemd-network/sd-dhcp-server.c:617
617                         req->server_id = _(be32_t_)option;
(gdb) bt
#0  0x000001000000c410 in parse_request (code=54 '6', len=4 '\004', option=0x7fefffff20a, userdata=0x10000184730)

```
at src/libsystemd-network/sd-dhcp-server.c:617
```
#1  0x0000010000010eb8 in parse_options (options=0x7fefffff1ff "5\001\003\062\004\177", buflen=25, overload=0x7feffffeeb9 "",

```
message_type=0x7feffffeeba "\003", error_message=0x7feffffeec0, cb=0x1000000c298 <parse_request>, userdata=0x10000184730)
at src/libsystemd-network/dhcp-option.c:210
```
#2  0x0000010000011020 in dhcp_option_parse (message=0x7fefffff10f, len=25, cb=0x1000000c298 <parse_request>, userdata=0x10000184730,

```
_error_message=0x7feffffefd8) at src/libsystemd-network/dhcp-option.c:238
```
#3  0x000001000000cb18 in dhcp_server_handle_message (server=0x100001822c0, message=0x7fefffff10f, length=265) at src/libsystemd-network/sd-dhcp-server.c:724
#4  0x0000010000007e10 in test_message_handler () at src/libsystemd-network/test-dhcp-server.c:172
#5  0x0000010000008be8 in main (argc=1, argv=0x7fefffff688) at src/libsystemd-network/test-dhcp-server.c:257

(gdb)

**Comment by keszybz** [comment]
Closing if favour of #3346.

**Comment by glaubitz** [comment]
But #3346 and #3347 are not the same issue. One is a crash in _test-dhcp-server_ and one in _test-dns-packet_. Shouldn't these remain as two separate issues or do you already know they are the result of a bug in a common component?
