### ISSUE TITLE
 IPv6 Compliance RFC4861: Default Router Switch (Hosts Only) [v6LC.2.2.11] - Incorrect nexthop

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [systemd/systemd#33470]
### systemd version the issue has been seen with

256 and 257~devel-g6efab8c

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-35-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

#### IPv6 Conformance Test v6LC.2.2.11: Default Router Switch (Hosts Only).
**Purpose**: Verify that a host maintains at least two routers in its Default Router List and will switch routers when the router in use fails.

#### Network Configuration
```
            TN2
             |
    +--------+--------+
    |                 |
   TR1               TR2
    |                 |
    +----+-------+----+
         |       |
        TN1     HUT
```

| Step | Action | Expected Behaviour of HUT |
|--------|--------|--------|
| 1. | TR1 sends RA `Src=TR1-LLA, Prefix=TN1's Global Prefix, Reachable=10s` | |
| 2. | 5s elapse then TN2 sends Echo request to HUT.| HUT sends NS `target=TR1-LLA` (i.e. who owns `TR1-LLA`?) |
| 3. | TR1 sends NA in response to NS from HUT| |
| 4. | TR2 sends RA `Src=TR2-LLA, Prefix=TN1's Global Prefix, Reachable=10s` | |
| 5. | TN2 sends Echo request to HUT every 3s for 30s. | HUT sends Echo replies to TR1's LLA until reachable time expires. On expiry, the HUT should send 3 NS to TR1's LLA. |
| 6. | TR1 does not respond to NS from HUT. | HUT selects TR2 from its Default Router list. The HUT sends NS's to TR2's LLA. |

### Unexpected behaviour you saw

In Step 5, the HUT does not send an Echo reply via TR1, but incorrectly sends a NS for TR2.

In summary, the state of the neighbor cache entries (NCE) for TR1 and TR2 should dictate the routing decision.  At Step 5, the NCE is:

| Neighbor | State |
|----|----|
| TR1 | REACHABLE |
| TR2 | INCOMPLETE |

In an extract from [RFC4861 6.3.6](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.6):

     The policy for selecting routers from the Default Router List is as
     follows:

     1) Routers that are reachable or probably reachable (i.e., in any
        state other than INCOMPLETE) SHOULD be preferred over routers
        whose reachability is unknown or suspect (i.e., in the
        INCOMPLETE state, or for which no Neighbor Cache entry exists).
        Further implementation hints on default router selection when
        multiple equivalent routers are available are discussed in
        [[LD-SHRE](https://datatracker.ietf.org/doc/html/rfc4861#ref-LD-SHRE)].

When this test fails, the protocol summary is:

| Time (s) | Protocol Exchange |
|----|----|
| **0.0** | TR1 sends RA (reachable time=10s) |
| **5.0** | TN2 sends echo request via TR1, HUT sends NS for TR1, TR1 sends NA (a REACHABLE NCE is created for TR1), HUT sends echo reply via TR1 |
| **5.1** | TR2 sends RA (reachable time=10s) |
| **8.0** | TN2 sends echo request via TR1 (an INCOMPLETE NCE is created for TR2), HUT sends NS for INCOMPLETE TR2 (instead of replying to REACHABLE TR1) |

This violates [RFC4861 6.3.6](https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.6), bullet 1.

> **NOTE**: While the routing decisions are made in the kernel, this problem does not show up when networkd is disabled and sysctl `accept_ra=2`, i.e. it succeeds when the kernel processes the RA for the default routers. I'm yet to identify the exact cause, but my suspicion is on how networkd creates the default routes.  A side-by-side comparison of watching the routing table is interesting:

Monitoring the routing table with this command and comparing kernel-processing with networkd-processing:
```
$ old="xxx"; while :; do out=$(ip -6 r show dev enp0s9); new=$(echo "$out" | sed 's/expires.*sec //'); [ "$new" != "$old" ] && date +"%F %T.%N:%n""${out}%n"; old="$new"; sleep 0.1; done
```
> NOTE: The output from this command was not displaying ECMP routes due to: [Bug in iproute2](https://bugs.launchpad.net/ubuntu/+source/iproute2/+bug/2070412) fixed by [netdev](https://marc.info/?l=linux-netdev&m=171976458316116&w=2)

The main difference is highlighted in the table below. We can see the kernel shows a route for TR2 (... :1061). <strike>Meanwhile, networkd does not show that route, despite the log indicating the route should have been created. (I'm left wondering if this is a timing issue with networkd running as a user process compared to ther kernel's near-real-time behavior). [This will be the subject of futher investigation].</strike>[The routes were not being displayed because of the bug in iproute2!]

| Native kernel (accept_ra=2) | Networkd (accept_ra=0) |
|----|----|
| 2024-06-25 13:58:14.799160751:<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:00:14.146552856:<br>2001:2:0:1000::/64 proto kernel metric 256 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 44sec hoplimit 64 pref medium<br><br>2024-06-25 14:00:19.180667134:<br>2001:2:0:1000::/64 proto kernel metric 256 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 39sec hoplimit 64 pref medium<br>**default via fe80::200:10ff:fe10:1061 proto ra metric 1024 expires 44sec hoplimit 64 pref medium**<br><br>2024-06-25 14:00:46.764607577:<br>fe80::/64 proto kernel metric 256 pref medium<br> | 2024-06-25 14:05:40.236621759:<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:32:59.593132559:<br>2001:2:0:1000::/64 proto ra metric 1024 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br>default via fe80::200:10ff:fe10:1060 proto ra metric 1024 expires 44sec pref medium<br><br>2024-06-25 14:33:04.658694269:<br>2001:2:0:1000::/64 proto ra metric 1024 expires 65534sec pref medium<br>fe80::/64 proto kernel metric 256 pref medium<br><br>2024-06-25 14:33:12.140417989:<br>fe80::/64 proto kernel metric 256 pref medium<br> |

### Steps to reproduce the problem

[v6LC_2_2_11-Networkd-Fail.zip](https://github.com/user-attachments/files/15964978/v6LC_2_2_11-Networkd-Fail.zip)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
enp0s9: NDISC: Received Router Advertisement from fe80::200:10ff:fe10:1060: flags=0x00(none), preference=medium, lifetime=45s
enp0s9: NDISC: Invoking callback for 'router' event.
enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '10000'
No change in value '10000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: State changed: configured -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=46 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting,configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting,configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=47 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: NDISC: Received Neighbor Advertisement from fe80::200:10ff:fe10:1060: Router=yes, Solicited=yes, Override=no
enp0s9: NDISC: Invoking callback for 'neighbor' event.
enp0s9: NDISC: Received Router Advertisement from fe80::200:10ff:fe10:1061: flags=0x00(none), preference=medium, lifetime=45s
enp0s9: NDISC: Invoking callback for 'router' event.

###########################################################################################
# Requested this 2nd default route, but it does NOT show up in the routing table. Why???  #
###########################################################################################

enp0s9: Requesting NDisc route (n/a): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a

###########################################################################################

Setting '/proc/sys/net/ipv6/neigh/enp0s9/base_reachable_time_ms' to '10000'
No change in value '10000', suppressing write
Setting '/proc/sys/net/ipv6/neigh/enp0s9/retrans_time_ms' to '1000'
No change in value '1000', suppressing write
Setting '/proc/sys/net/ipv6/conf/enp0s9/hop_limit' to '64'
No change in value '64', suppressing write
enp0s9: Requesting NDisc route (configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Requesting NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Setting SLAAC addresses and router.
enp0s9: State changed: configured -> configuring
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=48 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: Configuring NDisc route (requesting): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc route (requesting,configuring,configured): dst: 2001:2:0:1000::/64, src: n/a, gw: n/a, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Configuring NDisc address (requesting,configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: Received new NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1061, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: Received remembered NDisc route (configured): dst: n/a, src: n/a, gw: fe80::200:10ff:fe10:1060, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: global, type: unicast, flags: n/a
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: ndisc_check_ready(): SLAAC addresses and routes are not set.
enp0s9: Received updated NDisc address (configured): 2001:2:0:1000:a00:27ff:fe5f:f72d/64 (valid for 18h 12min 14s, preferred for 18h 12min 14s), flags: manage-temporary-address,no-prefixroute, scope: global
enp0s9: link_check_ready(): dynamic addressing protocols are enabled but none of them finished yet.
enp0s9: SLAAC addresses and routes set.
enp0s9: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
enp0s9: State changed: configuring -> configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_34 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=49 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

**Comment by LiveFreeAndRoam** [comment]
I am drilling in on the creation of the two default routes.  I have simplified the protocol exchange to be just two packets:

1. TR1 (src_address 1060) sends RA
2. TR2 (src_address 1061) sends RA

### Native kernel (accept_ra=2)
```
$ ip -6 r
2001:2:0:1000::/64 dev enp0s9 proto kernel metric 256 expires 65531sec pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default via fe80::200:10ff:fe10:1060 dev enp0s9 proto ra metric 1024 expires 595sec hoplimit 64 pref medium
default via fe80::200:10ff:fe10:1061 dev enp0s9 proto ra metric 1024 expires 596sec hoplimit 64 pref medium
```
> NOTE: While two default routes are created when receiving the two RAs, I am not able to manually create a second default static route. The second one returns `RTNETLINK answers: File exists`.

### Networkd (accept_ra=0)
```
# NOTE: Do not use "ip -6 r show dev enp0s9" - it hides information!!!
$ ip -6 r
2001:2:0:1000::/64 dev enp0s9 proto ra metric 1024 expires 65531sec pref medium
fe80::/64 dev enp0s3 proto kernel metric 256 pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default proto ra metric 1024 expires 595sec pref medium
	nexthop via fe80::200:10ff:fe10:1060 dev enp0s9 weight 1 
	nexthop via fe80::200:10ff:fe10:1061 dev enp0s9 weight 1 
```
> Aside: [Bug in iproute2](https://bugs.launchpad.net/ubuntu/+source/iproute2/+bug/2070412)

Make the HUT's NCE REACHABLE for TR1.  This is done by issuing an `Echo Request`.  When the HUT responds with a NS ("Who owns TR1?"), TR1 send its NA.  Confirm the state with:

```
$ ip -6 n
fe80::200:10ff:fe10:1060 dev enp0s9 lladdr 00:00:10:10:10:60 router REACHABLE 
fe80::200:10ff:fe10:1061 dev enp0s9 FAILED 
```

The next time the host receives an echo request, it must reply using TR1 as the nexthop.  However, in this state, it responds with a NS ("Who owns TR2").


Questions:
1. I tried to manually create multiple default routes, but the 2nd one returns an error. How to create multiple default routes manually?
2. How does networkd create these two routes? Is it possible to change the way the routes are created so they match the behavior of the native kernel?
3. Is this a kernel bug? Shouldn't the kernel still determine the preferred route based on the NCE?

**Comment by LiveFreeAndRoam** [comment]
I'm currently pursuing this as a kernel bug.  I have raised a defect in [Ubuntu launchpad](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2071397) as well as the [Linux Kernel netdev](https://marc.info/?l=linux-netdev&m=171953240705042&w=2) mailing list.

I would still like to understand how networkd is able to create a single `default route` with two `nexthop` entries, compared to the kernel creating one `default route` for each RA that it receives.

FWIW, I tried to emulate the kernel behavior by manually creating two `default routes`, but the 2nd route always returns an `EEXISTS` error, even though the `nexthop` is unique per route.

**Comment by Gigadoc2** [comment]
I don't think this is a kernel bug, at least not in the way you describe it: In the networkd case we see a ECMP-route, so the kernel is instructed to use both nexthops at the same time (in some round-robin fashion), which is different from the case where there are two independent routes (where the kernel seems to do the right thing if I get your description).

So I think the issue here is the multipath-route being created in the first place, instead of having the two separate routes as you see them in the `accept_ra=2` case. This seems related to https://github.com/systemd/systemd/issues/21781 ?

**Comment by LiveFreeAndRoam** [comment]
@Gigadoc2, color me "impressed" 😊. You found a 2.5 year old case that closely relates to this one (#21781). Wow.

I agree that if networkd created a separate default route for each router, then this would work.

It still leaves me wondering about whether this is a kernel bug...  For instance, is there any reason why each nexthop in an ECMP would be exempt from checking the NCE for REACHABILITY? By not checking REACHABILITY, communication between endpoints breaks down, as it did in this case.

Also, the proposed workaround from #21781 didn't work for me. I'm not really sure why it ever worked; was it just a side-effect?  For instance, I reconfigured with:

```
[IPv6AcceptRA]
RouteMetric=2048
```

When I fired a couple RAs at my HUT, I still saw ECMPs being configured (except now they had a metric of 2048), eg.

```
$ ip -6 r
2001:2:0:1000::/64 dev enp0s9 proto ra metric 2048 expires 65533sec hoplimit 64 pref medium
fe80::/64 dev enp0s3 proto kernel metric 256 pref medium
fe80::/64 dev enp0s9 proto kernel metric 256 pref medium
default proto ra metric 2048 expires 593sec hoplimit 64 pref medium
        nexthop via fe80::200:10ff:fe10:1060 dev enp0s9 weight 1 
        nexthop via fe80::200:10ff:fe10:1061 dev enp0s9 weight 1 
```

**Comment by LiveFreeAndRoam** [comment]
I should emphasize, this test passes intermittently. Once it starts passing, it's hard to make it fail (until the next reboot, at least). So there must be some sticky state. I have not found a reliable method that always causes it to pass.

**Comment by Gigadoc2** [comment]
> @Gigadoc2, color me "impressed" 😊. You found a 2.5 year old case that closely relates to this one (#21781). Wow.

Thanks, I just happened to have done some experiments with Linux ECMP some years ago, which lead me to the right search terms I guess :sweat_smile: 

> It still leaves me wondering about whether this is a kernel bug... For instance, is there any reason why each nexthop in an ECMP would be exempt from checking the NCE for REACHABILITY? By not checking REACHABILITY, communication between endpoints breaks down, as it did in this case.

I don't know what is customary in the networking world outside of Linux, but I don't think the Linux routing layer involves itself much with actual reachability. Router Advertisements are a bit of an interesting case, as the kernel can also handle them all by itself, but for other routing protocols it is always the userspace checking reachability and installing or removing rules accordingly. E.g. if you run BGP, the kernel does not by itself remove or ignore routes with unreachable nexthops, the BGP daemon does it.

From a kernel view, this happened: An userspace program tells the kernel to do _equal cost_ multipath routing, so the kernel obliges and distributes the packets over both nexthops, no matter the current neighbor cache. And at the very least it makes sense for the kernel to try and get both nexthops `REACHABLE` again, otherwise it would not be much of an ECMP route? Technically, I also think the routing decision just happens before neighbor discovery even comes into play?

> Also, the proposed workaround from #21781 didn't work for me. I'm not really sure why it ever worked; was it just a side-effect? For instance, I reconfigured with [...]

In #21781 the routers were reachable on different (ethernet) interfaces, which is different from your scenario: They had configured two different metrics on the different interfaces, which eliminates the _equal cost_ path. In your test there is only one interface, so only one metric, so it is equal cost again (just a different cost, but in absence of alternative paths that doesn't change anything).

**Comment by LiveFreeAndRoam** [comment]
Thanks for the additional comments @Gigadoc2. ECMP is new to me and I'm learning a lot along the way.

On this topic, it seems the only way to bring networkd into IPv6 Compliance is for it to create two separate default route entires (one for each gateway), the same way the kernel does.

I'm exploring that option, but there are few impediments...
1. `networkd` doesn't support a method to do that
2. I can't manually test my hypothesis because `iproute2` returns EEXISTS when creating a 2nd default route (albeit to different gateway)
    a. When I run a modified `iproute2` (removing the exclisivity flag NLM_F_EXCL) the kernel creates ECMP rather than a 2nd default route. I'm continuing to dig into this.

More observations...

The output from `iproute2` is misleading. It shows an expiry time in the header of the ECMP routes, which suggests both ECMPs are being goverened by the same expiry time. However, my testing proves that is not the case. Both ECMPs expire according to their respective expirations.

E.g. imagine a host receives an RA with lifetime=10s from TR1, and then 5 seconds later receives an RA with lifetime=10s from TR2. `iproute2` displays them as:
```
$ ip -6 route
default proto ra metric 2048 expires 6sec pref medium
        nexthop via fe80::200:10ff:fe10:1061 dev enp0s9 weight 1 
        nexthop via fe80::200:10ff:fe10:1060 dev enp0s9 weight 1 
```

From the output, you would be forgiven for thinking that both paths will expire in 6 seconds. However, they expire according to their own lifetimes (TR2 will expire 5s after TR1, since that's when they were received).  I see this as another ECMP bug in `iproute2`.

It feels like there's a lot more to unravel here.

**Comment by LiveFreeAndRoam** [comment]
After reading through the iproute2 source and kernel source that processes the RTM_GETROUTE [ip6_fib.c:inet6_dump_fib()](https://github.com/nxp-real-time-edge-sw/real-time-edge-linux/blob/linux_6.1.55/net/ipv6/ip6_fib.c#L619), it seems the kernel does not store an expiry timer with the `nexthop`.  So now, I'm thinking `networkd` must be managing the timers for each `nexthop`. I'll turn my attention back toward it.

**Comment by LiveFreeAndRoam** [comment]
For completeness, this is the systemd-networkd patch that uses the kernel patch described in my previous message.

```
SRCBRANCH = "main"
SRCREV = "ba490e2281a4b62be7989ac1abc578f95a2f6032"
SRC_URI = "git://github.com/systemd/systemd.git;protocol=https;branch=${SRCBRANCH}"
```

```
From 17337e29216e4bfdeb19e56395f673a38d26da8b Mon Sep 17 00:00:00 2001
From: Matt Muggeridge <Matt.Muggeridge@hpe.com>
Date: Tue, 16 Jul 2024 23:05:27 -0500
Subject: [PATCH] New RTM_F_RA_ROUTER flag for Netlink Route Message

A Netlink user-level network manager, such as systemd-networkd, may set
the RTM_F_RA_ROUTER flag in the Netlink RTM_NEWROUTE rtmsg. When set,
the kernel sets RTF_RA_ROUTER in the fib6_config fc_flags. This causes a
default route to be created in the same way as if the kernel processed
the RA, via rt6add_dflt_router().

This is needed by user-level network managers, like systemd-networkd,
that prefer to do the RA processing themselves. ie. they disable the
kernel's RA processing by setting net.ipv6.conf.<intf>.accept_ra=0.

Without this flag, when there are mutliple default routers, the kernel
creates a single default route with ECMP nexthops. With ECMP nexthops,
the kernel routing algorithm ignores REACHABILITY information. As such,
if one of the default routers is unresponsive, with a Neighbor Cache
entry of INCOMPLETE, then it can still be selected as the nexthop for
outgoing packets. This results in an inability to communicate with
remote hosts, even though one of the default routers remains REACHABLE.
This violates RFC4861 6.3.6 bullet 1.

Extract from RFC4861 6.3.6 bullet 1:
     1) Routers that are reachable or probably reachable (i.e., in any
        state other than INCOMPLETE) SHOULD be preferred over routers
        whose reachability is unknown or suspect (i.e., in the
        INCOMPLETE state, or for which no Neighbor Cache entry exists).
        Further implementation hints on default router selection when
        multiple equivalent routers are available are discussed in

This fixes the IPv6 Logo conformance test v6LC_2_2_11, and others that
test witth multiple default routers.  Also see issue #33470:

#33470: IPv6 Compliance RFC4861: Default Router Switch (Hosts Only)
 [v6LC.2.2.11] - Incorrect nexthop
---
 src/basic/linux/rtnetlink.h  | 1 +
 src/network/networkd-route.c | 6 +++++-
 2 files changed, 6 insertions(+), 1 deletion(-)

diff --git a/src/basic/linux/rtnetlink.h b/src/basic/linux/rtnetlink.h
index 3b687d20c9..9d80926316 100644
--- a/src/basic/linux/rtnetlink.h
+++ b/src/basic/linux/rtnetlink.h
@@ -336,6 +336,7 @@ enum rt_scope_t {
 #define RTM_F_FIB_MATCH	        0x2000	/* return full fib lookup match */
 #define RTM_F_OFFLOAD		0x4000	/* route is offloaded */
 #define RTM_F_TRAP		0x8000	/* route is trapping packets */
+#define RTM_F_RA_ROUTER		0x10000	/* route is a default route from RA */
 #define RTM_F_OFFLOAD_FAILED	0x20000000 /* route offload failed, this value
 					    * is chosen to avoid conflicts with
 					    * other flags defined in
diff --git a/src/network/networkd-route.c b/src/network/networkd-route.c
index a4c56f1bbd..50407286d0 100644
--- a/src/network/networkd-route.c
+++ b/src/network/networkd-route.c
@@ -449,6 +449,7 @@ static void log_route_debug(const Route *route, const char *str, Manager *manage
 
 static int route_set_netlink_message(const Route *route, sd_netlink_message *m) {
         int r;
+        unsigned int ra_router_flag = 0;
 
         assert(route);
         assert(m);
@@ -486,7 +487,10 @@ static int route_set_netlink_message(const Route *route, sd_netlink_message *m)
         if (r < 0)
                 return r;
 
-        r = sd_rtnl_message_route_set_flags(m, route->flags & ~RTNH_COMPARE_MASK);
+        if (route->family == AF_INET6 && !in_addr_is_set(route->family, &route->dst))
+                ra_router_flag = RTM_F_RA_ROUTER; // IPv6 default route from RA
+
+        r = sd_rtnl_message_route_set_flags(m, (ra_router_flag | route->flags) & ~RTNH_COMPARE_MASK);
         if (r < 0)
                 return r;
 
```

**Comment by yuwata** [comment]
@LiveFreeAndRoam Nice!

> For completeness, this is the systemd-networkd patch that uses the kernel patch described in my previous message.

Please set the flag in `ndisc_router_process_default()`, rather than `route_set_netlink_message()`

**Comment by yuwata** [comment]
BTW, the suggested way in https://lore.kernel.org/netdev/ZytjEINNRmtpadr_@shredder/ is also OK, as a workaround.

**Comment by yuwata** [comment]
> BTW, the suggested way in https://lore.kernel.org/netdev/ZytjEINNRmtpadr_@shredder/ is also OK, at least as a workaround.

Note, I am working on this way.
