### ISSUE TITLE
systemd 256 user instance not working on WSL.

### ISSUE THREAD

**Issue by Hill-98** [systemd/systemd#33483]
### systemd version the issue has been seen with

256.1

### Used distribution

ArchLinux (WSL)

### Linux kernel version used

5.15.153.1-microsoft-standard-WSL2

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

It should work fine when I use `systemctl --user xxxx` command.

### Unexpected behaviour you saw

When I use the `systemctl --user xxxx` command, I get the following error: `Failed to connect to bus: No such file or directory`.

### Additional program output to the terminal or log subsystem illustrating the issue

I updated the Arch WSL packages to the latest version a few days ago, in which systemd was upgraded from 255.6 to 256.1, and then the `systemctl --user xxxx` command no longer worked.

It seems that the systemd user instance did not start normally.

**Comment by poettering** [comment]
Please contact WSL for help about this, this is a downstrea problem, not an upstream one.
