### ISSUE TITLE
IOAccounting values not reported correctly in systemctl status

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#33482]
### systemd version the issue has been seen with

256.1-1-arch-g34ba18b

### Used distribution

Arch-Testing

### Linux kernel version used

6.9.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

```
systemctl show systemd-journald.service -p IOReadBytes -p IOWriteBytes
IOReadBytes=7393280
IOWriteBytes=15613952
```
should return the correct number of read/written io bytes, as reported in the `io.stat` cgroup file.

### Unexpected behaviour you saw

```
$ systemctl show systemd-journald.service -p IOReadBytes -p IOWriteBytes
IOReadBytes=0
IOWriteBytes=0

$ cat /sys/fs/cgroup/system.slice/systemd-journald.service/io.stat 
8:0 rbytes=16728064 wbytes=0 rios=350 wios=2 dbytes=0 dios=0
254:0 rbytes=16728064 wbytes=7294976 rios=350 wios=816 dbytes=0 dios=0
```

### Steps to reproduce the problem

setup system.conf for default IO accounting
```
[Manager]
DefaultCPUAccounting=yes
DefaultIOAccounting=yes
DefaultBlockIOAccounting=yes
DefaultIPAccounting=yes
DefaultLimitCORE=infinity
```

**Comment by YHNdnzj** [comment]
Could you please try #33258?

**Comment by ElvishJerricco** [comment]
@YHNdnzj That appears to solve this issue for me.
