### ISSUE TITLE
RFE: support %h for ExecStart

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#3349]
```
> systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

distrobution: arch linux

when building user services ExecStart=%h/path/to/bin complains about not having an absolute path.
expected it to resolve %h to the absolute path. instead I have to hardcode the path which isn't terribly useful.

**Comment by evverx** [comment]
Similar to #3061

**Comment by poettering** [comment]
Let's track this in #3061 and close this instance.

**Comment by rektide** [comment]
Been working around lack of %h by calling /usr/bin/env everywhere, but doesn't feel great (having to set SyslogIdentifier= isn't fun). And it still presupposes that you've figured out how to setup PATH in your user session. It'd be really appreciated by user session folks if they had an effective way to share ~/ based scripts among themselves; currently requires manual intervention for each and every user, and that's slowing down user session adoption.
