### ISSUE TITLE
Boot counting not working if unsuffixed config exists

### ISSUE THREAD

**Issue by SuibianP** [systemd/systemd#33504]
### systemd version the issue has been seen with

256.1-1-arch-g34ba18b^

### Used distribution

EndeavourOS Gemini 2024.04.20

### Linux kernel version used

6.9.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

kernel-install, systemd-boot

### Expected behaviour you didn't see

`systemd-bless-boot good` should remove counter suffix from config, even when counter-suffixed `foo+m-n.conf` and plain `foo.conf` are both present in `ESP/loader/entries/`.

### Unexpected behaviour you saw

`systemd-bless-boot good` does nothing ("Operation already executed before, not doing anything."), resulting in a successfully booted entry being marked as bad.

### Steps to reproduce the problem

1. Prepare a system without boot counting
2. `echo 3 > /etc/kernel/tries`
3. Reinstall kernel, e.g. `pacman -S linux`
4. Reboot multiple times; observe the entry attempts decreasing and finally marked bad, despite boot success

### Additional program output to the terminal or log subsystem illustrating the issue

```console
# /usr/lib/systemd/systemd-bless-boot status
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Reading EFI variable /sys/firmware/efi/efivars/LoaderBootCountPath-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Directory "/boot" is not the root of the file system.
Using /efi as boot loader drop-in search path.
Booted file: /loader/entries/575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1+0-4.conf
The same modified for 'good': /loader/entries/575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1.conf
The same modified for 'bad':  /loader/entries/575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1+0-4.conf
Tries left: 0
Tries done: 4
indeterminate
# /usr/lib/systemd/systemd-bless-boot good
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Reading EFI variable /sys/firmware/efi/efivars/LoaderBootCountPath-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Directory "/boot" is not the root of the file system.
Using /efi as boot loader drop-in search path.
Operation already executed before, not doing anything.
# tree /efi /boot
/efi
├── 575d8b8c9d854c169ade7d6ddb5ccb12
│   └── 6.9.6-arch1-1
│       ├── initrd
│       ├── initrd-fallback
│       └── linux
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   ├── Linux
│   └── systemd
│       └── systemd-bootx64.efi
└── loader
    ├── entries
    │   ├── 575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1+0-4.conf
    │   ├── 575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1.conf
    │   ├── 575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1-fallback+3.conf
    │   └── 575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1-fallback.conf
    ├── entries.srel
    ├── loader.conf
    └── random-seed
/boot
└── intel-ucode.img

10 directories, 13 files
# cat /etc/kernel/tries 
3
# iconv -f UCS2 /sys/firmware/efi/efivars/LoaderBootCountPath-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f | tr '\0' '\n'

\loader\entries\575d8b8c9d854c169ade7d6ddb5ccb12-6.9.6-arch1-1+0-4.conf
```

**Comment by Cornelicorn** [comment]
Also affected by this, in our case not kernel reinstalls, but DKMS modules being updated, which is especially annoying, because it will drop you down to a lower version after rebooting multiple times.
