### ISSUE TITLE
systemctl: prolong daemon-reload method call timeout to be longer than generator timeout

### ISSUE THREAD

**Issue by xiangzhai** [systemd/systemd#3353]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ArchLinux Linux iSOFT 4.6.0-1-ARCH #1 SMP PREEMPT Mon May 16 20:36:53 CEST 2016 x86_64 GNU/Linux
### In case of bug report: Expected behaviour you didn't see

> $ systemctl enable service exited normally very quickly!
### In case of bug report: Unexpected behaviour you saw

> $ systemctl enable service timeout

**Comment by tkarls** [comment]
+1

I just got this on an arch linux machine too.

```
sudo systemctl enable nginx
Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.
Failed to execute operation: Connection timed out

```

Although, I  seem to have version 229

```
systemctl --version
systemd 229
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by WhitleyStriber** [comment]
Receiving this as well. Just ran a pacman Syu on my Arch machine and I can't enable cronie.service

```
sudo systemctl enable cronie
Failed to execute operation: Connection timed out
```

The command looks as if it goes through if you remove sudo. GNOME prompts me for my root password twice and does in fact enable the service.

**Comment by evverx** [comment]
@xiangzhai , @andrewtramutolo , what is the output of `strace -p 1`? `pause()`?

**Comment by tomty89** [comment]
It has something to do with lvm2 2.02.153-1 and 2.02.154-1. Not sure about 2.02.152-1. Downgrading to 2.02.150-1 helps.

It seems to be because of `lvm2-lvmetad.socket`. If I boot with `/usr/lib/systemd/system/sysinit.target.wants/lvm2-lvmetad.socket` removed, **or**, boot with `lvm2-lvmetad.service` enabled, the issue is gone.

```
[tom@localhost ~]$ systemctl status lvm2-lvmetad.socket
● lvm2-lvmetad.socket - LVM2 metadata daemon socket
   Loaded: loaded (/usr/lib/systemd/system/lvm2-lvmetad.socket; static; vendor preset: disabled)
   Active: active (listening) since Fri 2016-05-27 13:22:28 HKT; 11s ago
     Docs: man:lvmetad(8)
   Listen: /run/lvm/lvmetad.socket (Stream)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[tom@localhost ~]$ systemctl status lvm2-lvmetad
● lvm2-lvmetad.service - LVM2 metadata daemon
   Loaded: loaded (/usr/lib/systemd/system/lvm2-lvmetad.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:lvmetad(8)
[tom@localhost ~]$ sudo systemctl disable systemd-timesyncd
Removed /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
Failed to reload daemon: Connection timed out
[tom@localhost ~]$ 
```

```
[tom@localhost ~]$ systemctl status lvm2-lvmetad.socket
● lvm2-lvmetad.socket - LVM2 metadata daemon socket
   Loaded: loaded (/usr/lib/systemd/system/lvm2-lvmetad.socket; static; vendor preset: disabled)
   Active: active (running) since Fri 2016-05-27 13:25:33 HKT; 20s ago
     Docs: man:lvmetad(8)
   Listen: /run/lvm/lvmetad.socket (Stream)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[tom@localhost ~]$ systemctl status lvm2-lvmetad
● lvm2-lvmetad.service - LVM2 metadata daemon
   Loaded: loaded (/usr/lib/systemd/system/lvm2-lvmetad.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-05-27 13:25:33 HKT; 22s ago
     Docs: man:lvmetad(8)
 Main PID: 145 (lvmetad)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/lvm2-lvmetad.service
           └─145 /usr/bin/lvmetad -f

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[tom@localhost ~]$ sudo systemctl disable systemd-timesyncd
Removed /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
[tom@localhost ~]$ 
```

Btw it does not particularly has anything with to do with systemd 230. systemd 229 also suffers from this issue.

**Comment by pid1** [comment]
I can confirm this behavior, including the workaround @andrewtramutolo noted.

**Comment by WhitleyStriber** [comment]
This morning, I did a pacman update and lvm2 was upgraded from 2.02.150 to 2.02.153 on my laptop. This in fact, did break it again.

`[2016-05-26 10:21] [ALPM] upgraded lvm2 (2.02.150-1 -> 2.02.153-1)
`
Here was the stance command @evverx Forgive me if I'm doing this command wrong. Are you looking for the PPID for systemd or cronie? 

```
$ strace -p 1
strace: attach: ptrace(PTRACE_ATTACH, ...): Operation not permitted
$ sudo strace -p 1 
strace: Process 1 attached
epoll_wait(4, [{EPOLLIN, {u32=3141283744, u64=93904011276192}}], 114, -1) = 1
clock_gettime(CLOCK_BOOTTIME, {2702, 910643788}) = 0
recvmsg(105, {msg_name(0)=NULL, msg_iov(1)=[{"WATCHDOG=1", 4096}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=192, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 10
open("/proc/192/cgroup", O_RDONLY|O_CLOEXEC) = 19
fstat(19, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(19, "9:pids:/system.slice/systemd-jou"..., 1024) = 221
close(19)                               = 0
epoll_wait(4, [{EPOLLIN, {u32=3141283744, u64=93904011276192}}], 114, -1) = 1
clock_gettime(CLOCK_BOOTTIME, {2704, 410445829}) = 0
recvmsg(105, {msg_name(0)=NULL, msg_iov(1)=[{"WATCHDOG=1", 4096}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=234, uid=0, gid=0}}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 10
open("/proc/234/cgroup", O_RDONLY|O_CLOEXEC) = 19
fstat(19, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(19, "9:pids:/system.slice/systemd-ude"..., 1024) = 212
close(19)                               = 0
timerfd_settime(15, TFD_TIMER_ABSTIME, {it_interval={0, 0}, it_value={2797, 160135000}}, NULL) = 0
epoll_wait(4, 
```

**Comment by evverx** [comment]
@AphexPinecone 

> Are you looking for the PPID for systemd or cronie?

I'm looking for the PID for `systemd`

@AphexPinecone , @tomty89 , could you upgrade to `2.02.153-1` and provide the output of:

```
systemctl daemon-reload &
strace -p 1
```

I want to understand what is `systemd` waiting for

**Comment by WhitleyStriber** [comment]
@evverx 

```
$ systemctl daemon-reload
Failed to execute operation: Connection timed out
```

```
$ sudo systemctl daemon-reload
Failed to execute operation: Connection timed out
```

```
$ strace: Process 679 attached
epoll_wait(4, [{EPOLLIN, {u32=2731689344, u64=94565026645376}}], 28, -1) = 1
clock_gettime(CLOCK_BOOTTIME, {100, 284913636}) = 0
read(5, "\21\0\0\0\0\0\0\0\1\0\0\0\2\4\0\0\350\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
open("/proc/1026/comm", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(17, "gnome-control-c\n", 1024)     = 16
close(17)                               = 0
read(5, 0x7ffcc1db7e60, 128)            = -1 EAGAIN (Resource temporarily unavailable)
waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1026, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
open("/proc/1026/comm", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(17, "gnome-control-c\n", 1024)     = 16
close(17)                               = 0
open("/proc/1026/cgroup", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(17, "9:cpu,cpuacct:/\n8:devices:/\n7:me"..., 1024) = 110
close(17)                               = 0
waitid(P_PID, 1026, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1026, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WEXITED, NULL) = 0
waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
epoll_wait(4, [{EPOLLIN, {u32=2731689344, u64=94565026645376}}], 28, -1) = 1
clock_gettime(CLOCK_BOOTTIME, {100, 566073258}) = 0
read(5, "\21\0\0\0\0\0\0\0\1\0\0\0\n\4\0\0\350\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
open("/proc/1034/comm", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(17, "epiphany-search\n", 1024)     = 16
close(17)                               = 0
read(5, 0x7ffcc1db7e60, 128)            = -1 EAGAIN (Resource temporarily unavailable)
waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1034, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
open("/proc/1034/comm", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(17, "epiphany-search\n", 1024)     = 16
close(17)                               = 0
open("/proc/1034/cgroup", O_RDONLY|O_CLOEXEC) = 17
fstat(17, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(17, "9:cpu,cpuacct:/\n8:devices:/\n7:me"..., 1024) = 110
close(17)                               = 0
waitid(P_PID, 1034, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1034, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WEXITED, NULL) = 0
waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
epoll_wait(4, 
```

I am now able to do
`sudo systemctl enable cronie.service & systemctl daemon-reload`
with no problems. I'm only able to do that command after I input 
`sudo systemctl enable cronie.service`
in a terminal.

**Comment by co60ca** [comment]
This occurred for me as well on 
`systemd 229`

With:
`Linux *** 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux`

My server was on for 70+ days with a few updates without restart. Not sure if that contributes.

Additionally I have `lvm2-lvmetad.socket` active. Restart fixes everything. Haven't seen it since.

**Comment by evverx** [comment]
Well, I've reproduced:

``` sh
root@archlinux:~# systemctl stop lvm2-lvmetad.service
Warning: Stopping lvm2-lvmetad.service, but it can still be activated by:
  lvm2-lvmetad.socket

root@archlinux:~# systemctl daemon-reload &
[1] 393

root@archlinux:~# strace -p 1
strace: Process 1 attached
waitid(P_PID, 395, ^Cstrace: Process 1 detached
 <detached ...>

root@archlinux:~# strace -p 395
strace: Process 395 attached
waitid(P_PID, 396, ^Cstrace: Process 395 detached
 <detached ...>

root@archlinux:~# strace -p 396
strace: Process 396 attached
read(4, ^Cstrace: Process 396 detached
 <detached ...>
root@archlinux:~# ps u 396
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       396  0.0  0.1  30244  3208 ?        S    11:13   0:00 /usr/lib/systemd/system-generators/lvm2-activation-generator /run/systemd/generator /run/systemd/generator.early

root@archlinux:~# lsof -p 396
...
lvm2-acti 396 root    4u  unix 0xffff88007bd31680      0t0  10881 type=STREAM

root@archlinux:~# strace -p 396
strace: Process 396 attached
read(4,
```
- `systemd` reloads
- `systemd` runs `lvm2-activation-generator`
- `lvm2-activation-generator` blocks on IO
- `systemd` waits ~= 90s (`DEFAULT_TIMEOUT_USEC`)

So, this is an `lvm2-activation-generator` issue.

BTW:
`core/systemd 229-3 [installed]`
`core/lvm2 2.02.153-1 (base) [installed]`

Minimal reproducer: https://gist.github.com/evverx/34d17ba0741aefa1bed620bc78dbc420#file-systemd-waits-generator-waits-socket-waits-systemd-sh

**Comment by poettering** [comment]
Somebody please contaxt the lvm people. As documented generators should under no circumstances sync on any IPC. if they do they are broken.

That said we should really prolong the daemon-reload method call timeout so that it is longer than the generator timeout, so that we get better discoverability of this issue. Will rename issue accordingly.

**Comment by FadeMind** [comment]
Downgrade `lvm2` to point release 2.02.150-1 via `downgrade` tool and reboot temporary solved issue on Arch Linux.

**Comment by ahocquet** [comment]
Same issue here on archlinux, fixed by downgrading lvm2.

**Comment by monochromec** [comment]
LVM2 fix worked for me on Alarm boxes (both v5 and v7) as well, so this is a cross-platform issue. Hopefully this gets fixed soon.

**Comment by evverx** [comment]
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1334063

Fix: https://git.fedorahosted.org/cgit/lvm2.git/commit/scripts/lvm2_activation_generator_systemd_red_hat.c?id=591ef307b30c2d828b2a0c59918203f970974bbb

[WHATS_NEW](https://git.fedorahosted.org/cgit/lvm2.git/commit/WHATS_NEW?id=e694e0896bd4d320f5d5017411763583698b28dc):

> -  Fix lvm2-activation-generator to read lvm.conf without full command setup.

**Comment by xiangzhai** [comment]
Hi @evverx I am glad to see that you found the reason why systemd timeout, I hangout these days, so without providing strace info ;-P

**Comment by tomty89** [comment]
@evverx For the record, the upstream fix does not seem to work (unless something went wrong with the build process of the lvm2 package in Arch). Someone else reported the same as well: https://bugs.archlinux.org/task/49483

**Comment by evverx** [comment]
@tomty89 , well, [lvm2 2.02.154-2](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/lvm2&id=16401f140ac351f4c1fdf9e7278228d5d146dc8c) contains [fix](https://git.fedorahosted.org/cgit/lvm2.git/commit/scripts/lvm2_activation_generator_systemd_red_hat.c?id=591ef307b30c2d828b2a0c59918203f970974bbb). But doesn't contain [that commit](https://git.fedorahosted.org/cgit/lvm2.git/commit/?id=7fd4119d24eee55323e888dd78c70257d7c97a15). So, this fix doesn't work.

**Comment by alexellis** [comment]
Exactly the same error on ArchLinuxARM. I just did a pacman -Syu and am wishing I hadn't. Not sure I even have old packages in /var/cache/pacman/pkg... so how can I revert?

**Comment by torincb** [comment]
Exactly the same issue here on Arch Linux (AMD64) with systemd v229, lvm v2.02.153..

**Comment by eworm-de** [comment]
Fixed with lvm2 2.02.154-3 in [testing].

**Comment by felipepiovezan** [comment]
lvm2-2.02.154-3 fixed the issue for me (Arch)

**Comment by monochromec** [comment]
lvm2-2.02.154-3  also fixes the issue on Alarm (both v5 and v7 SoCs).
