### ISSUE TITLE
Allow PKCS11 tokens with multiple certificates to be used with systemd-cryptenroll / systemd-cryptsetup

### ISSUE THREAD

**Issue by dominicschaub** [systemd/systemd#33549]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

Currently, systemd-cryptenroll can only be used with PCKS11 tokens containing a single RSA key pair (confirmed by reviewing the source code). However, in many use cases, smart cards will contain multiple key pairs corresponding to different security uses. There is no technical reason for this limitation. Indeed, I have previously rolled my own set of scripts for smart card-based LUKS key enrollment and unlocking, and those scripts allowed the selection of the desired key.

### Describe the solution you'd like

1) For systemd-cryptenroll: allow the specification of the certificate's _complete_ URI, not just that of the token on which it resides.
2) I haven't looked under the hood to inspect the data stuffed into JSON token(s) in the LUK header, but I would guess that the key label is absent. Stuff the key label into the JSON token so that the correct key can be identified during unlocking. 
3) For LUKS unlocking, add functionality that finds the required key on the smart card.

### Describe alternatives you've considered

1) Acquire a separate smart card dedicated to LUKS unlocking (not ideal)
2) Continue to use my homebrew smart card LUKS scripts and manually plop required dependencies into the initramfs, adding fragility to the initramfs regeneration process (not ideal). A fully functional systemd solution would be much cleaner.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by dominicschaub** [comment]
Mistake on my end - it looks like a full object specification works fine.

**Comment by dominicschaub** [comment]
Mistake on my end - it looks like a full object specification works fine.

**Comment by glennmorris** [comment]
I've just run into this myself (also in version 255), and wonder why this was closed. Does it work in some later version?

I found the 255 behaviour rather confusing:

- Have a PCKS11 token with a single key (a Yubikey, slot 9d)
- systemd-cryptenroll works, and the key unlocks the LUKS partition
- Some time later, happen to add another key (to slot 9a)
- Now the key does not unlock LUKS. There is no visible prompt at boot, just a fallback to the passphrase after the configured timeout.
- Post boot, systemctl status 'systemd-cryptsetup@luks...' shows "Security token not present for unlocking volume", but this message was not visible at boot
- Try to repeat the enrollment, using 'systemd-cryptenroll --wipe-slot=pkcs11', followed by 'systemd-cryptenroll --pkcs11-token-uri=auto'. This fails with "Configured URI matches multiple certificates, refusing."
- Find this bug report, and realise I had to delete the key from 9a.

**Comment by ifisen94** [comment]
I also wonder why this was closed, because in 256.12-1.fc41 this issue still persists.

I have a PKCS#11 token with multiple certificates and systemd-cryptenroll detects it with no issues, but fails with the message "Configured URI matches multiple certificates, refusing." when I try to enroll one of them.
