### ISSUE TITLE
with the zh_CN.gb18030 encoding set, timedatectl reports an error: Failed to print table: Invalid argument.

### ISSUE THREAD

**Issue by YoruStar** [systemd/systemd#33542]
### systemd version the issue has been seen with

255

### Used distribution

Fedora

### Linux kernel version used

kernel-5.1

### CPU architectures issue was seen on

x86_64

### Component

timedatectl

### Expected behaviour you didn't see

$ export LANG=zh_CN.gb18030
$ timedatectl
               Local time: 六 2024-06-29 15:16:08 CST
           Universal time: 六 2024-06-29 07:16:08 UTC
                 RTC time: 六 2024-06-29 07:16:08
                Time zone: Asia/Shanghai (CST, +0800)

### Unexpected behaviour you saw

$ export LANG=zh_CN.gb18030
$ timedatectl
Failed to print table: Invalid argument

### Steps to reproduce the problem

$ export LANG=zh_CN.gb18030
$ timedatectl

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
In older versions of systemd, timedatectl command could work properly when zh_CN.gb18030 encoding was set. 
However, since the modification in https://github.com/systemd/systemd/commit/cf57766d792f15d5bc1c14ebb423db3cb74f105b, the timedatectl command uses `table_print` instead of `printf`, which causes the lack of support for double-byte encoding.
```

**Comment by YHNdnzj** [comment]
Sorry, but UTF-8 is the established charset in Linux world. Why would you use gb18030 in the first place?

**Comment by YoruStar** [comment]
> Sorry, but UTF-8 is the established charset in Linux world. Why would you use gb18030 in the first place?

I have a special Linux environment here, and in order to adapt to some older applications, I have to use gb-18030. 

By the way, in older versions of systemd, the timedatectl command works normally in any double-byte encoding environment. The problem only occurred after the introduction of the [cf57766d792f15d5bc1c14ebb423db3cb74f105b](https://github.com/systemd/systemd/commit/cf57766d792f15d5bc1c14ebb423db3cb74f105b) patch.

**Comment by YHNdnzj** [comment]
> By the way, in older versions of systemd, the timedatectl command works normally in any double-byte encoding environment. The problem only occurred after the introduction of the [cf57766d792f15d5bc1c14ebb423db3cb74f105b](https://github.com/systemd/systemd/commit/cf57766d792f15d5bc1c14ebb423db3cb74f105b) patch.

That's exactly because `format-table.c` correctly honors utf8 character width (`utf8_console_width` and friends), while the previous implementation of `timedatectl` didn't. Sorry, but we have no intention to support other charsets. Closing.
