### ISSUE TITLE
Feature request: hooks for `enable` and `disable`

### ISSUE THREAD

**Issue by EvanCarroll** [systemd/systemd#33561]
### Component

systemctl

### Is your feature request related to a problem? Please describe

I am making a monitoring service that will monitor daemons. These daemons are all packaged with systemd. I do not want to change my behavior when the daemons are stopped, and started. I want to monitor daemons started by enabled systemd services regardless of whether or not they're up at a specific time. However, I do want to alter the behavior when the daemons are disabled or enabled. When the daemon is disabled, I want to stop monitoring it. When it is enabled, I want to start monitoring it.

### Describe the solution you'd like

It would be nice if in the unit file representing an exec-trigger for service had the ability to do something like this,

```
[Service]
Hook=disable, enable
ExecHook=/bin/sh -c "echo hello world"
Type=hook
```

**Comment by poettering** [comment]
Sorry, but no, we are not going to execute external code on enable/disable. No way.

I don't get this though. You already have Also= and UpheldBy= in [Install] which looks like it should cover already what you want to do. if you wonder how, please contact the systemd mailing list.
