### ISSUE TITLE
timers not started for timer files on fstab mounted filesystems

### ISSUE THREAD

**Issue by wolfgangrupprecht** [systemd/systemd#33563]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.9.6-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

This is the output when /usr/local/ is an ordinary directory tree in the rootfs.

<code>
# systemctl list-timers --all
NEXT                            LEFT LAST                              PASSED UNIT                           ACTIVATES                       
Mon 2024-07-01 19:05:42 PDT     8min Mon 2024-07-01 18:50:56 PDT     6min ago checkin.timer                  checkin.service
Mon 2024-07-01 19:58:13 PDT  1h 1min Mon 2024-07-01 18:50:56 PDT     6min ago wsrcc-ddns.timer               wsrcc-ddns.service
Mon 2024-07-01 20:05:30 PDT  1h 8min Mon 2024-07-01 18:50:56 PDT     6min ago dnf-makecache.timer            dnf-makecache.service
Mon 2024-07-01 23:45:00 PDT 4h 47min Mon 2024-07-01 00:58:14 PDT 1h 51min ago backup-to-rsync-snapshot.timer backup-to-rsync-snapshot.service
Tue 2024-07-02 00:00:00 PDT  5h 2min Mon 2024-07-01 00:58:14 PDT 1h 51min ago logrotate.timer                logrotate.service
Tue 2024-07-02 00:00:00 PDT  5h 2min Mon 2024-07-01 00:58:14 PDT 1h 51min ago unbound-anchor.timer           unbound-anchor.service
Tue 2024-07-02 00:37:55 PDT 5h 40min Mon 2024-07-01 00:58:14 PDT 1h 51min ago plocate-updatedb.timer         plocate-updatedb.service
Tue 2024-07-02 15:12:53 PDT      20h Sat 2024-06-29 17:48:37 PDT 3h 44min ago systemd-tmpfiles-clean.timer   systemd-tmpfiles-clean.service
Sun 2024-07-07 01:00:00 PDT   5 days Sun 2024-06-30 02:29:21 PDT  3h 8min ago raid-check.timer               raid-check.service
Mon 2024-07-08 01:32:16 PDT   6 days Mon 2024-07-01 00:58:14 PDT 1h 51min ago fstrim.timer                   fstrim.service

10 timers listed.
</code>
### Unexpected behaviour you saw

This is the output when /usr/local/ is an fstab mounted filesystem that is automatically mounted after boot.

<code>
# systemctl list-timers --all
NEXT                            LEFT LAST                        PASSED UNIT                           ACTIVATES                       
Mon 2024-07-01 19:12:56 PDT    14min -                                - systemd-tmpfiles-clean.timer   systemd-tmpfiles-clean.service
Mon 2024-07-01 19:46:10 PDT    47min -                                - dnf-makecache.timer            dnf-makecache.service
Tue 2024-07-02 00:00:00 PDT  5h 1min Mon 2024-07-01 00:58:14 PDT      - logrotate.timer                logrotate.service
Tue 2024-07-02 00:00:00 PDT  5h 1min Mon 2024-07-01 00:58:14 PDT      - unbound-anchor.timer           unbound-anchor.service
Tue 2024-07-02 00:16:58 PDT 5h 18min Mon 2024-07-01 00:58:14 PDT      - plocate-updatedb.timer         plocate-updatedb.service
Sun 2024-07-07 01:00:00 PDT   5 days Sun 2024-06-30 02:29:21 PDT      - raid-check.timer               raid-check.service
Mon 2024-07-08 00:09:46 PDT   6 days Mon 2024-07-01 00:58:14 PDT      - fstrim.timer                   fstrim.service
-                                  - -                                - backup-to-rsync-snapshot.timer backup-to-rsync-snapshot.service
-                                  - -                                - checkin.timer                  checkin.service
-                                  - -                                - wsrcc-ddns.timer               wsrcc-ddns.service

10 timers listed.
</code>
### Steps to reproduce the problem

Add some units and timers to /usr/local/lib/systemd/system/ .  Run systemctl list-timers --all .  Save the output. Create a fresh filesystem and copy /usr/local into it.   Move the original out of the way.  This is important.  Files under /usr/local must not exist at early boot time.  Add the new filesystem to /etc/fstab to be mounted.  Reboot.   Run systemctl list-timers --all again.  Note that the timers added above show up as inactive now.
</code>

**Comment by dtardon** [comment]
I bet that these timers have been enabled (therefore there are symlinks in /etc/systemd) and that their `LoadState=` is `not-found` (run `systemctl show -P LoadState UNIT-NAME` or `systemctl list-units --all *.timer` and check the `LOAD` column). That means that systemd knows the names, but that's about it, because the symlinks were broken when it loaded units.

IOW, there is no bug there. Either mount `/usr/local` in initrd, or ensure that `systemctl daemon-reload` is called after `/usr/local` has been mounted and that the timers are wanted by a suitable target (something that hasn't been started at that point yet. I.e., `timers.target` is _not_ suitable).

**Comment by wolfgangrupprecht** [comment]
Both daemon-reload and daemon-reexec have no effect.

<code>
[root@capsicum ~]# systemctl show -P LoadState wsrcc-ddns.timer
loaded
[root@capsicum ~]# systemctl list-units --all *.timer
  UNIT                           LOAD   ACTIVE   SUB     DESCRIPTION                                     
  backup-to-rsync-snapshot.timer loaded inactive dead    wsrcc: daily backup of ext4 and vfat partitions
  checkin.timer                  loaded inactive dead    WSRCC: track location of portable assets
  dnf-makecache.timer            loaded active   waiting dnf makecache --timer
  fstrim.timer                   loaded active   waiting Discard unused filesystem blocks once a week
  logrotate.timer                loaded active   waiting Daily rotation of log files
  plocate-updatedb.timer         loaded active   waiting Update the plocate database daily
  raid-check.timer               loaded active   waiting Weekly RAID setup health check
  systemd-tmpfiles-clean.timer   loaded active   waiting Daily Cleanup of Temporary Directories
  unbound-anchor.timer           loaded active   waiting daily update of the root trust anchor for DNSSEC
  wsrcc-ddns.timer               loaded inactive dead    wsrcc: update our public dns A and AAAA records

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

10 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
[root@capsicum ~]# systemctl daemon-reload
[root@capsicum ~]# systemctl list-units --all *.timer
  UNIT                           LOAD   ACTIVE   SUB     DESCRIPTION                                     
  backup-to-rsync-snapshot.timer loaded inactive dead    wsrcc: daily backup of ext4 and vfat partitions
  checkin.timer                  loaded inactive dead    WSRCC: track location of portable assets
  dnf-makecache.timer            loaded active   waiting dnf makecache --timer
  fstrim.timer                   loaded active   waiting Discard unused filesystem blocks once a week
  logrotate.timer                loaded active   waiting Daily rotation of log files
  plocate-updatedb.timer         loaded active   waiting Update the plocate database daily
  raid-check.timer               loaded active   waiting Weekly RAID setup health check
  systemd-tmpfiles-clean.timer   loaded active   waiting Daily Cleanup of Temporary Directories
  unbound-anchor.timer           loaded active   waiting daily update of the root trust anchor for DNSSEC
  wsrcc-ddns.timer               loaded inactive dead    wsrcc: update our public dns A and AAAA records

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

10 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
[root@capsicum ~]# 
[root@capsicum ~]# systemctl daemon-reexec
[root@capsicum ~]# systemctl list-units --all *.timer
  UNIT                           LOAD   ACTIVE   SUB     DESCRIPTION                                     
  backup-to-rsync-snapshot.timer loaded inactive dead    wsrcc: daily backup of ext4 and vfat partitions
  checkin.timer                  loaded inactive dead    WSRCC: track location of portable assets
  dnf-makecache.timer            loaded active   waiting dnf makecache --timer
  fstrim.timer                   loaded active   waiting Discard unused filesystem blocks once a week
  logrotate.timer                loaded active   waiting Daily rotation of log files
  plocate-updatedb.timer         loaded active   waiting Update the plocate database daily
  raid-check.timer               loaded active   waiting Weekly RAID setup health check
  systemd-tmpfiles-clean.timer   loaded active   waiting Daily Cleanup of Temporary Directories
  unbound-anchor.timer           loaded active   waiting daily update of the root trust anchor for DNSSEC
  wsrcc-ddns.timer               loaded inactive dead    wsrcc: update our public dns A and AAAA records

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

10 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
[root@capsicum ~]# 
</code>

**Comment by YHNdnzj** [comment]
Sorry, but having a separate `/usr/local/` is not supported. Refer to https://github.com/systemd/systemd/pull/33233 for more details.
