### ISSUE TITLE
systemd-cryptsetup failing to unlock with TPM sometimes

### ISSUE THREAD

**Issue by hirak99** [systemd/systemd#33571]
### systemd version the issue has been seen with

256.1

### Used distribution

Arch

### Linux kernel version used

6.9.7-arch1-1

### CPU architectures issue was seen on

None

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

I have already enrolled TPM2 password -

`sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=1+7+12+14 /dev/sdX`

System should boot without asking for password.

### Unexpected behaviour you saw

Since updating Arch yesterday, I see systemd to not unlock automatically on some boots.

Instead, it asks for me to type in the password which works.

When it doesn't work, I see the following in journal -

```
Jul 02 23:23:15 archlinux systemd-cryptsetup[258]: Failed to unseal secret using TPM2: Operation not permitted
```

Wiping and re-enrolling makes it work for the next few boots.

### Steps to reproduce the problem

Have not pinpointed the reason yet.

However, rebooting a few times causes the issue to get back.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Line from journal log -


Jul 02 07:34:03 archlinux systemd-cryptsetup[259]: Failed to unseal secret using TPM2: Operation not permitted
```
```

**Comment by poettering** [comment]
you locked against a bunch of PCRs, i.e. 1+7+12+14. hence anything that is measured into those will mean you cannot unlock your tpm anymore.

figure out what you want: don't lock against those PCRs if you want to allow changes to those resources. Or lock against them but then don't make changes to those resources.

(i.e. no firmware upgrades, no selinux policy updates and so on)

**Comment by hirak99** [comment]
The choice of the PCRs was deliberate, and had no issues so far. Mostly if I changed the commandline, I needed to re-enroll the key; or if I ever changed my RAM etc. - and that is as expected.

It's been working for a few years; but since the last update day before yesterday, I've seen it fail a few times.

Is there any command line to test and find out which PCR is failing when it fails?

**Comment by polarina** [comment]
Many firmwares measure the BootOption EFI variables into PCR 1. The same firmwares also meddle with the boot options for your "convenience", for example, when it detects a USB stick during boot.

What does the TCG eventlog for PCR 1 show before and after the failure?

**Comment by hirak99** [comment]
Thanks, TCG eventlog is a good pointer. Let me check if it falls again. 

I've rebooted a few times, and it hasn't failed. 

If it's convenient, we can close this issue - since I'm the only one who reported it. And I'll reopen if it fails, also try to find a way to reproduce if it does before reopening.

**Comment by hirak99** [comment]
I have not seen this happen since the day I reported it. Closing it now, unsure what caused it a few times, but if it doesn't recur it's not a problem.
