### ISSUE TITLE
Consider moving default configuration from /usr/lib to /usr/share

### ISSUE THREAD

**Issue by jedenastka** [systemd/systemd#33585]
### Component

journalctl, systemd, systemd-portabled, systemd-sysctl, systemd-sysusers, systemd-tmpfiles, other

### Is your feature request related to a problem? Please describe

The [FHS document for `/usr/lib`](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s06.html) states:

> /usr/lib includes object files and libraries. [21] On some systems, it may also include internal binaries that are not intended to be executed directly by users or shell scripts. [22]
> [...]
> [21] Miscellaneous architecture-independent application-specific static files and subdirectories must be placed in /usr/share.

Looking at [`/usr/share`](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html), we find:

> The /usr/share hierarchy is for all read-only architecture independent data files. [30]

systemd however, seems to store the default, immutable configuration files in `/usr/lib`, not `/usr/share`. Both of these locations seem somewhat similar in purpose, but based on the FHS, `/usr/share` seems more apt for static configuration (it even uses the word "must", which is a strong word for sure).

From experience, it is also how many different notable programs use these directories. I was certainly surprised to learn that the unit files live in `/usr/lib/systemd/system`, not `/usr/share/systemd/system` - they are just plain text configs, after all, and those are either `/etc` or `/usr/share`!

### Describe the solution you'd like

Move directories such as `/usr/lib/systemd/system` to a respective place in `/usr/share`, possibly leaving a symlink behind. I imagine this is not a simple task, as this location is probably referenced in a lot of places.

### Describe alternatives you've considered

Do nothing. In any way, I am merely asking to consider doing this. It doesn't seem like an outright wrong choice not to, though surely a confusing one. Possibly provide an explanation for why `/usr/lib` was chosen in some way.

### The systemd version you checked that didn't have the feature you are asking for

256.1

**Comment by poettering** [comment]
No. /usr/share/ is for stuff that has shared ownership, i.e. where multiple packages have equal footing in owning resources inside of it.

We use /usr/lib/systemd/ for all resources that are exclusively by systemd.

This has been discussed many many times over the years (decade!), really no need to reopen this can of worms.

We even documented the logic behind this here:

https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html

You can read that man page as an FHS update if you want, given that the FHS is basically unmaintaned since a decade.

**Comment by jedenastka** [comment]
Oh, sorry. I was trying to search GitHub issues for this, but it churned *thousands* of irrelevant results. Thanks for the response, probably should've asked this on IRC first.
