### ISSUE TITLE
resolved: Parse nameserver addresses with zone indices

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#3359]
Resolved currently fails to parse IPv6 addresses with a zone index:

`Failed to parse DNS server address 'fe80::c256:27ff:febb:12f%wlp3s0', ignoring.`

These can get written by NetworkManager when received through SLAAC.

**Comment by poettering** [comment]
parse from where? `/etc/resolv.conf`?

**Comment by heftig** [comment]
Yes, `resolv.conf`.
