### ISSUE TITLE
Resume from suspend-to-disk fails on a LUKS encrypted swap since systemd 253 till now

### ISSUE THREAD

**Issue by nachordez** [systemd/systemd#33601]
### systemd version the issue has been seen with

256

### Used distribution

Manjaro (up to date)

### Linux kernel version used

6.9.5-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

As before 253.
-You hibernate
-You start computer
-You introduce LUKS password
-System resumes the hibernated session

### Unexpected behaviour you saw

From 253 till now
-You hibernate
-You start computer
-You introduce LUKS password
-there is a journal notice about errors on disk while fsck is working (as if not found the resume file or swap partition, and so no integrity on FS)
-new session is opened, and saved one is lost.

### Steps to reproduce the problem

Nothing special:
-You close session by hibernating
-You start computer
-You instroduce LUKS password when asked for it

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
There is a previous report (on previous systemd version) made by me on manjaro forums, wich can be also consulted, with nice explanation, on this link: https://forum.manjaro.org/t/hibernation-failing-just-booting-without-recovering-previous-state/154205
Also there is INXI information, and journalctl entries.

Kernel: 6.9.5-1-MANJARO  (but happens with all other kernels)

Manjaro, stable, up to date

lsblk:
NAME                  MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
nvme0n1               259:0    0 476,9G  0 disk  
├─nvme0n1p1           259:1    0   300M  0 part  /boot/efi
├─nvme0n1p2           259:2    0 459,7G  0 part  
│ └─luks-95fc649b-53b3-4137-813b-69f906456198
│                     254:0    0 459,7G  0 crypt /
└─nvme0n1p3           259:3    0    17G  0 part  
  └─luks-e4419e8b-5200-43f2-9f1f-8f886ee1616a
                      254:1    0    17G  0 crypt [SWAP]

INXI output: https://gist.github.com/nachordez/e976f62afa66c33e50ccd5fe8feac07c

Journalctl outputs (hibernation time and booting time): https://gist.github.com/nachordez/4d58b6dce5fd1d170b994ad7fe11e0ae

HOOKS=(base udev block encrypt lvm2 autodetect microcode modconf kms keyboard keymap consolefont mdadm_udev filesystems fsck)

grub.cfg: https://gist.github.com/nachordez/1179c6597f208f728f3b97b5bdfcf369

Please, ask for anything you need.
```

**Comment by YHNdnzj** [comment]
> HOOKS=(base udev block encrypt lvm2 autodetect microcode modconf kms keyboard keymap consolefont mdadm_udev filesystems fsck)

`resume` mkinitcpio hook is required in order to initiate resume from hibernation in initramfs. Please refer to https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Configure_the_initramfs for details.

Not a systemd issue, closing.
