### ISSUE TITLE
systemd  warning:  eth1: found matching network '00-test-eth1.network', based on potentially unpredictable interface name.

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#33616]
### systemd version the issue has been seen with

255

### Linux kernel version used

GNU/Linux

### CPU architectures issue was seen on

arm

### Component

systemd

### Expected behaviour you didn't see

I have registered two interfaces with systemd-networkd and dont want to see these warning messages from systemd

I wanted to know why systemd-networkd throw these warning messages

### Unexpected behaviour you saw

I have registered two interfaces with systemd-networkd and noticed below warning messages from systemd

systemd-networkd[239]: eth0: found matching network '/etc/systemd/network/00-test-eth0.network', based on potentially unpredictable interface name.

systemd-networkd[239]: eth1: found matching network '/etc/systemd/network/00-test-eth1.network', based on potentially unpredictable interface name.

### Steps to reproduce the problem

Noticed these warning systemd-networkd warning messages after restart of systemd-networkd

**Comment by raviteja-b** [comment]
> So you probably match against the name eth0 in your /etc/systemd/network/00-test-eth0.network config file. But eth0/eth1 are not stable names, they will be assigned non-deterministcally depending on probing error. networkd just tells you about this fact.
> 
> But note that this is a support question, please contact the systemd ML message for thise, do not misuse this bug and feature tracker for that. thank you.


Here is Name populated in systemd config file
[Match]
Name=eth0

what's wrong with this name??


sure next time onwards, I will contact systemd ML message for any questions

**Comment by poettering** [comment]
> what's wrong with this name??

bus/driver probing order is generally not stable. Thus, you might sometimes get an interface named eth0 that is named eth1 on the next boot, and so on.

read this: https://systemd.io/PREDICTABLE_INTERFACE_NAMES
