### ISSUE TITLE
Fix Multilaser ul154 key toggle touchpad button

### ISSUE THREAD

**Issue by drosdeck** [systemd/systemd#33628]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-15-amd64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Fn+F2 in my device was to be able to toggle (on-off) touchpad.

### Unexpected behaviour you saw

The pressing of the key wasn't responding

### Steps to reproduce the problem

Press Fn+F2

**Comment by YHNdnzj** [comment]
Please submit a PR.
