### ISSUE TITLE
systemd path unit will auto activate proc-fs-nfsd.mount when set DirectoryNotEmpty = /proc/fs/nfsd

### ISSUE THREAD

**Issue by chen1195585098** [systemd/systemd#33635]
### systemd version the issue has been seen with

255

### Used distribution

Centos

### Linux kernel version used

5.10.134-14.xxx.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

when I start path_test.path likes below, the proc-fs-nfsd.mount will be automatically activated.
```
[Unit]
Description = monitor /proc/fs/nfsd dir to check if nfs-server is ready

[Path]
DirectoryNotEmpty = /proc/fs/nfsd/
Unit = path_test.service

[Install]
WantedBy = multi-user.target
```

### Unexpected behaviour you saw

This path Unit should not affect proc-fs-nfsd.mount.

I am not sure if it is a bug or a feature.

### Steps to reproduce the problem

- Write a systemd path unit like this:
```
[Unit]
Description = monitor /proc/fs/nfsd dir to check if nfs-server is ready

[Path]
DirectoryNotEmpty = /proc/fs/nfsd/
Unit = path_test.service

[Install]
WantedBy = multi-user.target
```
, where `path_test.service` just show the files of target directory.
- Start this unit, and then check by `systemctl status proc-fs-nfsd.mount`. Also, `mount|grep nfsd' says something.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nothing.
```

**Comment by chen1195585098** [comment]
Hi, it seems that systemd always add the dependency on proc-fs-nfsd.mount unit, when I monitor /proc/fs/nfsd/. So, proc-fs-nfsd.mount will be activated before I run `systemctl start path_test.path`.

Is there any OPTION to `remove` this dependency? I have tried `DefaultDependencies=no`, but this didn't work.

**Comment by poettering** [comment]
I am not sure I follow? to see if that dir is empty that dir needs to be mounted, obviously? how would it otherwise detect the contents of that dir?

i really don't get what the point of this report is? what am i not getting?

**Comment by chen1195585098** [comment]
> I am not sure I follow? to see if that dir is empty that dir needs to be mounted, obviously? how would it otherwise detect the contents of that dir?
> 
> i really don't get what the point of this report is? what am i not getting?

Thanks for you reply,I have checked the relevant procedures in the past few days，and you are right, it should be mounted first.

In fact, I am just wondering if there is a method to check whether a mountpoint is ready or not? Can I get a notify when a systemd.mount unit is activated?
