### ISSUE TITLE
Partial turn of mode for services

### ISSUE THREAD

**Issue by nintyfan** [systemd/systemd#33642]
### Component

systemd

### Is your feature request related to a problem? Please describe

Currently, it could took long to turn of or reboot computer, because there exist service dependencies. But, in some cases, there nothing uses some services, which normally will be shutdown afterward. For example - desktop normally requires networking, but currently no app uses networking.

### Describe the solution you'd like

Solution is to send signal to each services, at beginning of shutdown/reboot process, telling system will be going to shutdown. If service do not be used by anything, it could free some of resources, like flush logs to persistent storage, save configuration, etc. Service do not shutdown already.
When something needs to use service prepared to shutdown, it could set flag it does not prepared to shutdown yet and allow  to establish connection, handling request, etc.

When service would be shutdown in normal cases, so queue went to step, it should be turn off, service would see if flag I told pefore is set and:
1) If flag telling service is not prepared to shutdown is set, normal shutdown process occur, so service will save logs, save config, etc.
2) If flag is not set, then service do fast shutdown

This could made shutdown/reboot faster, I think, but I am not good developer and do not known systemd internals, sorry.

### Describe alternatives you've considered

No alternatives was taking in mind.

**Comment by poettering** [comment]
There's already a signal that is sent when shutdown is initiated: PrepareForShutdown from logind. It's documented and so on, but I doubt many services really bother with it.
