### ISSUE TITLE
If /dev/console is /dev/ttyS0, don't agressively ellipsize service starting messages

### ISSUE THREAD

**Issue by n3rdopolis** [systemd/systemd#33647]
### Component

systemd, systemd-journald

### Is your feature request related to a problem? Please describe

Recent versions of Plymouth read the boot message from /dev/console and now have its own terminal emulator that can display them instead of relying on the VT to display them when the user hits ESC

This allows users to see system messages pretty well

One thing I am noticing though is that when the console is /dev/ttyS0, (because there is no /dev/tty0) the default width or something seems to be smaller

There is a lot of lines like

`[ OK ] Started plymouth-start.ser…e - Show Plymouth Boot Screen.`   

Where the messages newer versions of Plymouth on systems that still have VTs don't have these shortened lines

### Describe the solution you'd like

Something that allows the full service name to be shown to the userspace when booting, (but obviously not break compatibility with true serial devices that log from serial devices)

### Describe alternatives you've considered

Does something like `stty` need to be set on /dev/ttyS0 upon each boot to adjust the serial console width?

**Comment by YHNdnzj** [comment]
>  the default width or something seems to be smaller

Hmm, why not make plymouth properly set up terminal width then?

**Comment by n3rdopolis** [comment]
That could be possible, I would need to figure out to do `stty cols`  
And does systemd check the terminal width each line? or on startup? I tried grepping to see how the ellipsies works. I guess I also want to ask if the width is actually hard coded or not for serial consoles

**Comment by n3rdopolis** [comment]
I answered my questions with some testing, seems it is dynamic, and changing number of columns with a test service, and newer lines are no longer ellipsized. I will see if I can do it correctly in Plymouth

**Comment by poettering** [comment]
I am a bit confused. What does /dev/ttyS0 have to do with Plymouth? /dev/ttyS0 is a serial terminal, RS232. But plymouth is this graphical boot splash? These things are generally orthogonal. What am I not getting?

**Comment by n3rdopolis** [comment]
Plymouth reads the boot messages out of /dev/console , and in recent versions, it shows the lines logged to /dev/console if the user hits ESC. Older versions, when you hit ESC fall back to showing the VT, but now it can display what gets logged on its own.  

On kernels without VTs, /dev/console defaults to /dev/ttyS0, and it seems like it defaults to a terminal width of 80 columns. This will result in future users with VT-less kernels seeing many boot messages that are ellipsized much more agressively, service names are cut short with the Unicode ellipsis character

**Comment by poettering** [comment]
are you sure you mean /dev/ttyS0? That's good old RS232!

I really don't get what plymouth has to do with rs232?

**Comment by n3rdopolis** [comment]
Yes, /dev/ttyS0 is /sys/class/tty/console/active when there is no /dev/tty0 
![image](https://github.com/systemd/systemd/assets/6219356/835f7947-c4aa-4f5f-9b01-85682284237c)

Plymouth reads boot messages from whatever `/sys/class/tty/console/active` happens to be. 

And some messages are kind of shorter than they could be
![image](https://github.com/systemd/systemd/assets/6219356/dbf5194b-6d6c-47e0-b2cc-e1ec9f9c4f69)
because of
![image](https://github.com/systemd/systemd/assets/6219356/9252cd2f-a2c4-46ea-8747-58ee6e1de84a)

**Comment by n3rdopolis** [comment]
@poettering OK so the `status_vprintf` messages getting abridged to 80 chars only seems to happen when something is _plugged into the serial port_. I am sorry about the confusion there.

So while I guess Plymouth, in theory, could send that IOCTL to resize /dev/console's dimensions to force it to print larger lines (and set it back afterwards), this only seems to be a thing when /dev/ttyS0 _actually has something plugged into it_. I am thinking though that if a device is plugged into /dev/ttyS0, users might not want the window size messed with just to get longer log lines...

In my case, the "device" I had "plugged in" to the serial port was QEMU's console, which is usually there by default. However, I think I encountered something else though.

That is, when the kernel console is /dev/ttyS0, and there is nothing plugged into /dev/ttyS0, systemd doesn't appear to be logging to /dev/console. I don't see all the `[ OK ] Starting Service` lines. Just lines out of /dev/kmsg. I double checked too, Plymouth is still able to read from /dev/console, the lines I cat into it appear on Plymouth's terminal emulator...

**Comment by poettering** [comment]
> Which, now that you brought that up, I decided to see what happens on real hardware where I don't have anything connected to the serial port, and it turns out I only see the messages that get logged to /dev/kmsg on real hardware. (I don't see the `status_vprintf` messages at ALL on real hardware)

Well, of course, if you have no tty that /dev/console could point to then you have no /dev/console, and thus no status output. That's pretty much expected. If you want that output, consider enabling the VT.

> @poettering OK so the `status_vprintf` messages getting abridged to 80 chars only seems to happen when something is _plugged into the serial port_. I am sorry about the confusion there.

The status output takes into account the dimensions reported on the tty it prints stuff to. For a VT those dimensions are derived from the screen size, as one would expect. For serial ports the dimensions are unknown and the kernel defaults them to 80x25 because it has to set them to something.

> So while I guess Plymouth, in theory, could send that IOCTL to resize /dev/console's dimensions to force it to print larger lines (and set it back afterwards), this only seems to be a thing when /dev/ttyS0 _actually has something plugged into it_. I am thinking though that if a device is plugged into /dev/ttyS0, users might not want the window size messed with just to get longer log lines...

Well, we honour what is set. If you don't like what is set, change it?

> In my case, the "device" I had "plugged in" to the serial port was QEMU's console, which is usually there by default. However, I think I encountered something else though.
> 
> That is, when the kernel console is /dev/ttyS0, and there is nothing plugged into /dev/ttyS0, systemd doesn't appear to be logging to /dev/console. I don't see all the `[ OK ] Starting Service` lines. Just lines out of /dev/kmsg. I double checked too, Plymouth is still able to read from /dev/console, the lines I cat into it appear on Plymouth's terminal emulator...

"Plymouth reads from /dev/console"? I don't think it does. I think it might take it over, and make it point to a pty it allocates and then read from the pty peer.

systemd will open /dev/console before each status output, and close it right after. Hence if /dev/console works at all you should get your output. Note that at least once upon a time, plymouth was explicitly turning off systemd's status output, by sending it a signal. MAybe that code ist still around?

**Comment by n3rdopolis** [comment]
I think I have the solution, and I get the nice status messages again on Plymouth, without VTs, and without anything on /dev/ttyS0! (I probably should rename this issue maybe?)
![image](https://github.com/systemd/systemd/assets/6219356/13ae21a2-7ddb-44f5-87a1-0ff9c03cdcdd)




It looks like the open_terminal() function was failing to open the file descriptor for /dev/console, not sure why, maybe it is something with the 3rd argument.

But also, it would have failed anyway as it seems like in this case /dev/console is not always a tty, so it would have failed later on anyway.
![image](https://github.com/systemd/systemd/assets/6219356/2fc9c828-5d01-4a5c-b90e-6ebf6dde2fa8)


Anyway, this change fixes it for me
https://github.com/systemd/systemd/pull/33690

**Comment by n3rdopolis** [comment]
@poettering Based on the fact that I was overlooking the ttynull driver in the kernel, and when the console is ttynull, and when the kernel console is ttynull, service names are ellipsized, I think this is good to close
