### ISSUE TITLE
Systemd deletes the PID file when a service error occurs

### ISSUE THREAD

**Issue by Chihaya-Yuka** [systemd/systemd#33657]
### systemd version the issue has been seen with

v219

### Used distribution

CentOS 7

### Linux kernel version used

5.4.265-1.el7.elrepo.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I want to start a service with a profile as shown below.
```Only Text
[Unit]
Description=awaya
After=

[Service]
Type=forking
User=users
Group=users
PIDFile=/usr/bin/python3.6m
ExecStart=/awaya/awaya/main.py
ExecReload=
ExecStop=
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

### Unexpected behaviour you saw

Systemd removed my PIDFile.

In my opinion, systemd should not delete any service files even if there is an error in the service.

### Steps to reproduce the problem

1. Create a service according to the preceding configuration.
2. Service started, 217 error observed. The PID file is then deleted.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
● awaya.service - awaya
   Loaded: loaded (/usr/lib/systemd/system/awaya.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2024-07-08 18:05:04 CST; 7s ago
  Process: 6080 ExecStart=/awaya/awaya/main.py (code=exited, status=217/USER)

Jul 08 18:05:04 rainyun-szmpbvl0 systemd[1]: Starting awaya...
Jul 08 18:05:04 rainyun-szmpbvl0 systemd[1]: awaya.service: control process exited, code=exited status=217
Jul 08 18:05:04 rainyun-szmpbvl0 systemd[1]: Failed to start awaya.
Jul 08 18:05:04 rainyun-szmpbvl0 systemd[1]: Unit awaya.service entered failed state.
Jul 08 18:05:04 rainyun-szmpbvl0 systemd[1]: awaya.service failed.
```

**Comment by poettering** [comment]
if you specify PIDFile= in a unit file, then we'll remove it when the service goes down (error or not) if it still exists.

This is explicitly documented btw, just check the systemd.service(5) man page.

If you don't want this, don't use PIDFile=?

(it's an obsolete concept anyway, from sysvinit time. Modern daemons do not use that)
