### ISSUE TITLE
`systemd-analyze verify` doesn't handle template units properly

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#33681]
### systemd version the issue has been seen with

256.1

### Used distribution

NixOS 24.11pre

### Linux kernel version used

6.6.36

### CPU architectures issue was seen on

aarch64

### Component

systemd-analyze

### Expected behaviour you didn't see

`systemd-analyze verify` shouldn't fail verifying `systemd-growfs@.service`

### Unexpected behaviour you saw

```
$ systemd-analyze verify  /usr/lib/systemd/system/systemd-growfs@.service 
systemd-growfs@i.service: Failed to create systemd-growfs@i.service/start: Unit i.mount not found.
```

Note that it does work if you fill in the template:

```
$ systemd-analyze verify  /etc/systemd/system/systemd-growfs@-.service
```

### Steps to reproduce the problem

```
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Grow File System on %f
Documentation=man:systemd-growfs@.service(8)

DefaultDependencies=no
BindsTo=%i.mount
After=systemd-repart.service %i.mount
Conflicts=shutdown.target
```

**Comment by lovette** [comment]
Would this issue apply to generated service files or should I not expect analyze to work on generated services? Reason being, I'm now using podman Quadlets which uses a generator to create service files for containers and my hand made timer units that reference a container service no longer validate. I can't tell if this is a bug or not. The timers do trigger the container service successfully.

	% systemd-analyze verify /etc/systemd/system/task-*
	task-exim-logrotate.service: Failed to create task-exim-logrotate.service/start: Unit podman-exim.service not found.

	% systemd-analyze verify podman-exim.service
	Unit podman-exim.service not found.

	% systemctl status podman-exim.service
	podman-exim.service - Podman container: exim
	Loaded: loaded (/etc/containers/systemd/podman-exim.container; generated)
	Active: active (running) since Wed 2024-08-14 17:37:26 UTC; 8min ago
	...

	% systemctl daemon-reload

	% systemd-analyze verify podman-exim.service
	Unit podman-exim.service not found.

	% systemctl --version
	systemd 252 (252-32.el9_4)

	% cat /etc/os-release 
	NAME="Rocky Linux"
	VERSION="9.4 (Blue Onyx)"
	...

**Comment by yuwata** [comment]
@arianvp Waiting in #34017.

@lovette Your comment is unrelated to the original issue. And I cannot follow what you want to do. And you use slightly old release. Please reproduce the issue with a recent release of systemd (v256 or current git HEAD) and open a new issue page, or contact to your downstream.

**Comment by yuwata** [comment]
@arianvp 
As commented https://github.com/systemd/systemd/pull/34017#discussion_r1720762038, please specify a hint for instance name in such case, as you already found.

So, the reported issue is not a bug.
