### ISSUE TITLE
Allow NIC bonding on PXE network booted machines

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#33694]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

If you boot a machine over the network (with its root filesystem on NFS), and you've configured systemd-networkd to set up a bonded network interface, then the machine hangs during boot and drops off the network.

The problem is that in order to create the `bond0` network interface, the physical interfaces are shut down as they are added to `bond0`.  Then, when systemd-networkd tries to read the `.network` file to configure an IP address on `bond0`, the system freezes because the file is being read off the NFS server, but the physical network interfaces are down so all filesystem reads hang until the NFS server returns.

Thus `bond0` never gets configured, so the root filesystem never returns, and the machine remains disconnected from the network and frozen.

### Describe the solution you'd like

It would be nice if systemd-networkd read all its configuration files into memory before it started making any changes, so that between starting and finishing network configuration, no disk access is required.

### Describe alternatives you've considered

1. Copying systemd-networkd and the network configuration into the initramfs makes applying distro updates difficult.
2. Copying the networkd configuration into a RAM disk like /tmp could work, but I am not sure how you would hook this into the boot process to copy the files before networkd runs, and how to point networkd at the files in their new location (and prevent it from trying to read files in any other folder that might hang too).
3. I am not sure if you can bypass networkd altogether and set up the bonded interface from the kernel command line, but perhaps that could be a workaround too.

### The systemd version you checked that didn't have the feature you are asking for

256.2

**Comment by Malvineous** [comment]
I have come up with a hacky workaround, in case this doesn't get fixed and someone else encounters it.

The workaround is to configure the `bond0` interface as normal, but omit the boot NIC from it (which may mean it's a bond with only one member).  Configure it to have the same IP address as the boot NIC.

When the system boots like this, both the boot NIC and the `bond0` interface will have the same IP, which means you can then take down the boot NIC and add it to `bond0` manually, without losing network connectivity or the root filesystem freezing, as traffic just goes through `bond0` instead (because it has the same IP address).  I did this with a systemd service so it would happen automatically just after startup:

```
[Unit]
Description=Add boot NIC to bonded interface
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot

# Set working directory to something off the NFS root, in case there is a momentary outage
WorkingDirectory=/sys

# Just to be safe
ExecStartPre=sleep 10
# Take down the boot interface (NFS root then runs off bond0 with the other NIC)
ExecStartPre=ip link set eth0 down
# Delete the boot IPs
ExecStartPre=ip addr flush dev eth0
# Add the boot interface to the bond0 bond, which brings it back up again
ExecStart=/bin/sh -c 'echo "+eth0" > /sys/class/net/bond0/bonding/slaves'

Restart=never

[Install]
WantedBy=multi-user.target
```

**Comment by yuwata** [comment]
> It would be nice if systemd-networkd read all its configuration files into memory before it started making any changes

networkd already does like that.

In general, setting up a bond interface after mounting NFS is a terrible idea, and easily causes system hang.

Instead, setting up bond and physical interfaces in initrd phase, then mount NFS root.

systemd-network-generator.service supports `bond=` kernel command line option. Please try to use it.

**Comment by Malvineous** [comment]
Thanks for the hint, I never realised you could configure the bond interface from the command line.  I won't be able to test this for a little while so I'll close this issue assuming it works, and reopen if I run into any issues.

Thanks again!
