### ISSUE TITLE
systemd not honoring /etc/udev/rules.d/80-net-setup-link.rules

### ISSUE THREAD

**Issue by valeech** [systemd/systemd#3369]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Linux rpitc-fd061ded 4.4.9-v7+ #2 SMP Thu May 19 22:35:10 EDT 2016 armv7l GNU/Linux
### In case of bug report: Expected behaviour you didn't see

ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules should disable persistent interface naming
### In case of bug report: Unexpected behaviour you saw

network interface name still set as enx[mac-addr]
### In case of bug report: Steps to reproduce the problem

ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules
reboot
ifconfig

**Comment by grawity** [comment]
What you're disabling is not the interface naming, but the processing of `.link` files. (Which, by the way, do more than persistent naming.) The "enx&lt;mac&gt;" names, however, aren't set by a `.link` file (which actually _has never used_ MAC-based names by default) &ndash; they're set by a [custom rule](https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/extra/rules/73-usb-net-by-mac.rules) that Debian/Ubuntu packages contain; it's installed as `73-usb-net-by-mac.rules`.

If you have systemd [229-6](https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=b3e7c6ee792d22c05c03625e749c43a9738efa95), use `net.ifnames=0` in the kernel command line; otherwise mask Debian's `73-usb-net-by-mac.rules` file instead.

**Comment by valeech** [comment]
Interesting. I was running systemd version 228 and just upgraded to 230 this morning. Prior to the upgrade, I followed [this](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) to get the interface name back to eth0.

After the upgrade this morning, the /etc/udev/rules.d/80-net-setup-link.rules is still in place but the interface name is different. I'll review your links and see what I can find.

I noticed in your links that these are USB rules for network interfaces. Does that make a difference since my interfaces are not USB?

**Comment by grawity** [comment]
I dunno, ARM systems might be just weird enough to connect built-in Ethernet ports through internal USB... What does `udevadm info /sys/class/net/eth0` show for the interface?

Are you building your own packages of 230? You haven't mentioned which distribution you're using, so I'm _guessing_ Debian.

**Comment by valeech** [comment]
It looks like they do connect through USB. Here's output from `udevadm info -a /sys/class/net/enxb827eb7daed5`

```
looking at device '/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1:1.0/net/enxb827eb7daed5':
    KERNEL=="enxb827eb7daed5"
    SUBSYSTEM=="net"
    DRIVER==""
    ATTR{addr_assign_type}=="0"
    ATTR{addr_len}=="6"
    ATTR{address}=="b8:27:eb:7d:ae:d5"
    ATTR{broadcast}=="ff:ff:ff:ff:ff:ff"
    ATTR{carrier}=="1"
    ATTR{carrier_changes}=="2"
    ATTR{dev_id}=="0x0"
    ATTR{dev_port}=="0"
    ATTR{dormant}=="0"
    ATTR{duplex}=="full"
    ATTR{flags}=="0x1003"
    ATTR{gro_flush_timeout}=="0"
    ATTR{ifalias}==""
    ATTR{ifindex}=="2"
    ATTR{iflink}=="2"
    ATTR{link_mode}=="0"
    ATTR{mtu}=="1500"
    ATTR{name_assign_type}=="4"
    ATTR{netdev_group}=="0"
    ATTR{operstate}=="up"
    ATTR{proto_down}=="0"
    ATTR{speed}=="100"
    ATTR{tx_queue_len}=="1000"
    ATTR{type}=="1"
```

I am using RPiTC which is built from rasbpian, a debian variant. I install with apt from the package repositories.

**Comment by poettering** [comment]
So. Dou you have that debian 73-usb-... rules file? If you mask it do you get the behaviour you want?

**Comment by valeech** [comment]
It ended up being a bad installation via apt. The rules files were missing. All is good now.
