### ISSUE TITLE
Add an IP address for the interface, but do not automatically add a local route

### ISSUE THREAD

**Issue by stm32repo** [systemd/systemd#33708]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

When I add an ipv4 address for an interface, systemd (or the kernel) automatically adds the local route to the local table
```
[Address]
Address=172.20.179.178/30
```

**ip route sh table local**
`local 172.20.179.178 dev veth0 proto kernel scope host src 172.20.179.178`

### Describe the solution you'd like

I want to disable this behavior and add a local route myself but to a different table
```
[Route]
Destination=172.20.179.178
PreferredSource=172.20.179.178
Scope=host
Table=main
Protocol=kernel
Type=local
```

### Describe alternatives you've considered

`ip route del local 172.20.179.178 dev veth0 proto kernel scope host src 172.20.179.178 table local`
`ip route add local 172.20.179.178 dev veth0 proto kernel scope host src 172.20.179.178 table main`
I need this behavior when working with VRF

### The systemd version you checked that didn't have the feature you are asking for

systemd 252 (252.26-1~deb12u2)

**Comment by poettering** [comment]
Check the man page. AddPrefixRoute=no
