### ISSUE TITLE
Huge memory consumption when iterating systemd journal with sd_journal_next()

### ISSUE THREAD

**Issue by maxaxelrod83** [systemd/systemd#33744]
### systemd version the issue has been seen with

250 (250.5+)

### Used distribution

custom embedded linux

### Linux kernel version used

5.15.118

### CPU architectures issue was seen on

arm

### Component

systemd-journald

### Expected behaviour you didn't see

When iterating through the journal using sd_journal_next() and sd_journal_wait(), as demonstrated in the official example on the man page (e.g., here https://manpages.debian.org/testing/libsystemd-dev/sd_journal_wait.3.en.html see EXAMPLES section), the RAM memory consumption does not grow forever.

### Unexpected behaviour you saw

When iterating through the journal using sd_journal_next() and sd_journal_wait(), as demonstrated in the official example on the man page (e.g., here https://manpages.debian.org/testing/libsystemd-dev/sd_journal_wait.3.en.html see EXAMPLES section), the RAM memory consumption of the application increases up to 250MB within 20 minutes.

We suspect that the primary cause of this issue is the rapidly growing shared memory (SHR) component of the RAM footprint, as indicated by the output of the top command:
```
top - 11:18:02 up 17:35,  2 users,  load average: 0.92, 1.31, 1.77
Tasks: 152 total,   3 running, 149 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.5 us, 10.5 sy,  0.0 ni, 68.8 id, 11.2 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    996.4 total,     91.0 free,    103.1 used,    802.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    864.7 avail Mem 

 PID  USER   VIRT    RES    SHR     S    %CPU  %MEM  COMMAND                                                                                                          
 3120 root   527012  251704 251196  S     0.0  24.7  journal-forward                                                                                                  
 309  root   125760  92008  91116   S     0.0   9.0  systemd-journal 
```

### Steps to reproduce the problem

Compile and run the following example, and observe memory consumption of the application. Example is taken from https://manpages.debian.org/testing/libsystemd-dev/sd_journal_wait.3.en.html, see EXAMPLES section.

```
/* SPDX-License-Identifier: MIT-0 */
#include <errno.h>
#include <stdio.h>
#include <systemd/sd-journal.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    errno = -r;
    fprintf(stderr, "Failed to open journal: %m\n");
    return 1;
  }

  for (;;)  
  {
    const void *d;
    size_t l;
    r = sd_journal_next(j);
    if (r < 0) {
      errno = -r;
      fprintf(stderr, "Failed to iterate to next entry: %m\n");
      break;
    }
 
   if (r == 0) {
      /* Reached the end, let's wait for changes, and try again */
      r = sd_journal_wait(j, (uint64_t) -1);
      if (r < 0) {
        errno = -r;
        fprintf(stderr, "Failed to wait for changes: %m\n");
        break;
      }

      continue;
    }

    r = sd_journal_get_data(j, "MESSAGE", &d, &l);
    if (r < 0) {
      errno = -r;
      fprintf(stderr, "Failed to read message field: %m\n");
      continue;
    }

    printf("%.*s\n", (int) l, (const char*) d);

  } // for end

  sd_journal_close(j);

  return 0;
}
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
~# systemctl status journal-forwarder
* journal-forwarder.service - journal-forwarder
     Loaded: loaded (8;;file://lib/systemd/system/journal-forwarder.service/lib/systemd/system/journal-forwarder.service8;;; enabled; vendor preset: enabled)8;;
     Active: active (running) since Fri 2022-04-29 10:52:57 UTC; 20min ago
   Main PID: 3120 (journal-forward)
     Memory: 266.4M
        CPU: 51.136s
     CGroup: /system.slice/journal-forwarder.service
             `- 3120 /usr/bin/journal-forwarder
```
```

**Comment by DaanDeMeyer** [comment]
[Canned reply follows]

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by DaanDeMeyer** [comment]
If you can reproduce this issue on a more recent systemd release we can reopen the bug

**Comment by vcaputo** [comment]
what issue, there is no issue, the journals are accessed with mmap, @maxaxelrod83 already noticed the memory is nearly all accounted for as SHR - file-backed shared mappings.

**Comment by maxaxelrod83** [comment]
@vcaputo do I understand correctly that you see in the growing SHR no issue? If I do, why is it so?

The problems from our point is the fact, that SHR contributes to RES memory (and as a result to the overall memory consumption of the application), see the output of `systemctl status journal-forwarder`. From Linux point of view, the memory consumption of the application grows continuously. Do I miss something?

**Comment by maxaxelrod83** [comment]
Dear community! 

We found some workaround to cause shared memory regions to be unmapped periodically. We see, that if we periodically close and reopen the journal handle, it releases the memory. Of course, we need to maintain the state and so on, but the major problem is "solved". 

The question, maybe the systemd library provides a direct API to unmap the not used shared memory regions explicitly?
Is there a known alternative API within systemd to achieve the same effect?

**Comment by vcaputo** [comment]
> @vcaputo do I understand correctly that you see in the growing SHR not an issue? If I do, why is it so?
> 
> The problems from our point is the fact, that SHR contributes to RES memory (and as a result to the overall memory consumption of the application), see the output of `systemctl status journal-forwarder`. From Linux point of view, the memory consumption of the application grows continuously and this is bad.
> 
> Why it is bad? If I let our application running without systemd memory limit, it gets to 700MB (from 1GB that we have) and the board makes reset. We saw, that the application can run with systemd memory limit of 20MB for a long time, but we are afraid of OOK being called at some point.
> 
> I am talking about this memory limits:
> 
> ```
> MemoryAccounting=true
> MemoryHigh=10M
> MemoryMax=20M
> ```
> 
> Do I miss something?

Yes, you miss something.

The SHR mem is coming from file-backed shared memory mappings of the journal files.  It's "shared" with the filesystem, when the system needs memory it treats these shared pages as reclaimable because there's a filesystem backing them.

Nothing to see here, move along.
