### ISSUE TITLE
Please change home directory of system users from '/' to '/nonexistent' or something else

### ISSUE THREAD

**Issue by wolfsage** [systemd/systemd#33743]
### Component

systemd-sysusers

### Is your feature request related to a problem? Please describe

systemd sets a bunch of users' home directory to '/'.

What this means is if you remove the systemd user for some reason using userdel and ask userdel to clean up the home directory (`userdel -r -f`), you effectively rm -rf '/' and break your system.

### Describe the solution you'd like

If there is no practical reason for the user's home directories to be '/', perhaps they could be '/nonexistent' instead, similar to how other things are configured. This would be safer for users.

### Describe alternatives you've considered

I've also submitted a ticket to the shadow-maint project to see if they'll consider not performing home dir removal if the home directory is '/', but I don't know if that change will be accepted.

**Comment by alejandro-colomar** [comment]
+1  (just adding myself to CC)

**Comment by poettering** [comment]
Uh, first of all, deleting users doesn't really work on UNIX, because you cannot find all files owned by said users.

But frankly, this *really* is just a bug in userdel. Deleting the whole root fs just because a user has its home dir set to root is just completely nuts. 

System users you generally don't log into, hence they don't have any home dir, hence we set the home dir to / because we have nothing better. I am not convinced we should reference an invalid dir here, just to work around a limitation of shadow-utils on an operation you really shouldn't do anyway.

**Comment by NekkoDroid** [comment]
> hence we set the home dir to / because we have nothing better

Maybe doing something [similar as with](https://github.com/systemd/systemd/blob/v256/NEWS#L526-L528) sshd would work? Setting it to `/usr/share/empty.user/`?

**Comment by dtardon** [comment]
IMHO `userdel` should refuse to remove the home dir. for _system_ users (`SYS_UID_MIN` to `SYS_UID_MAX` in `/etc/login.defs`). Or at least require an explicit confirmation.

**Comment by poettering** [comment]
I think it really should check if the homedirnis actually owned by the user in question. If not, stay away.

**Comment by alejandro-colomar** [comment]
> I think it really should check if the homedirnis actually owned by the user in question. If not, stay away.

Hmmmm, this sounds reasonable.  Would you mind reporting a bug?
<https://github.com/shadow-maint/shadow/issues/new/choose>

**Comment by poettering** [comment]
> > 
> 
> Maybe doing something [similar as with sshd](https://github.com/systemd/systemd/blob/v256/NEWS#L526-L528) would work? Setting it to `/usr/share/empty.user/`?

That actually has different reasons, they user that for chroot stuff, and they do it differently on each distro.

**Comment by alejandro-colomar** [comment]
> > > 
> > 
> > 
> > Maybe doing something [similar as with sshd](https://github.com/systemd/systemd/blob/v256/NEWS#L526-L528) would work? Setting it to `/usr/share/empty.user/`?
> 
> That actually has different reasons, they user that for chroot stuff, and they do it differently on each distro.

Can you please explain a little bit how that is used.  Is that dir used as a homedir for any users?  If so, it could be an example of a homedir that must not be removed while removing the user, which would justify your request that userdel(8) checks the owner.

**Comment by poettering** [comment]
> Can you please explain a little bit how that is used. Is that dir used as a homedir for any users? If so, it could be an example of a homedir that must not be removed while removing the user, which would justify your request that userdel(8) checks the owner.

Removing users is icky, it's really broken on UNIX.

For details how that ssh dir is used, inquire the ssh project. I am not an ssh guy, but from reading the code i seems to chroot() into that if privsep is enabled. 

Anyway, let's close this, it's pretty clear this is not a systemd issue, but something shadow-utils should really fix. Please report the issue there.
