### ISSUE TITLE
Support for creating symlinks in `repart.d` configs

### ISSUE THREAD

**Issue by NekkoDroid** [systemd/systemd#33756]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

Creating a read-only root partition that is only used to mount other partitions needs to have the compatibility symlinks for at least `/bin` and `/lib` ontop of just the dirs that are used for mounting. Currently this can only be done either by copying the files from somewhere or mounting the partition read-write and creating them after the fact.

Therefor it would be nice to have a way to create such symlinks in the configuration.

### Describe the solution you'd like

```ini
[Partition]
...
MakeSymlink=<location>:<target>
MakeSymlink=/bin:usr/bin
MakeSymlink=/etc/os-release:../usr/lib/os-release
```

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by DaanDeMeyer** [comment]
Makes total sense, should be trivial to implement (same as `MakeDirectories=` basically, happy to review a PR.

**Comment by NekkoDroid** [comment]
I assume this is safe to close with https://github.com/systemd/systemd/pull/34377
