### ISSUE TITLE
`mkosi` and bisectability

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#33759]
It was discussed in https://github.com/systemd/systemd/issues/23785#issuecomment-2211829054 and it isn't bisectable currently because it isn't stable generally but it would be great if it was possible to do that in the future.

I also considered just building images with systemd snapshots and store them somewhere (though it has its downsides) but it turns out images I built a month ago fail to boot with the latest mkosi too:
```sh
# python3 -Werror -Xdev -m mkosi --release=40 -E SANITIZERS=address,undefined  boot -n
‣ The '@' specifier is deprecated, please use Images instead of @Images
‣ Unknown setting Images
```

**Comment by DaanDeMeyer** [comment]
@evverx So you actually kind of can do bisecting already currently, but you need to make sure you use the fixed commit of mkosi that is known to work with the current commit of systemd. We record this commit in .github/workflows/mkosi.yml. You can grep it out from there, check it out in the mkosi repository and then run the build.

**Comment by evverx** [comment]
It should probably more or less work with prebuilt images but the problem with that is that the environment changes because of GIT_COMMIT in `mkosi.conf` too. I'm not sure how to fully "freeze" the environment and go back and forth to install different snapshots of systemd to the same distribution with the same set of packages.

**Comment by DaanDeMeyer** [comment]
@evverx I don't think this is possible. We change `GIT_COMMIT` precisely because we need various fixes that are made to the packaging specs, we can't assume the build will still work without being on that exact commit. To get a "frozen" environment, I would recommend defining your own image outside of the systemd repository and only using mkosi in the systemd repository to build distribution packages which you then install in your own image using the `PackageDirectories=` option.

Running `mkosi -t none` will output a set of distribution packages in `build/mkosi.output` without doing anything else.

**Comment by evverx** [comment]
> I don't think this is possible

It's possible by building and reinstalling systemd inside images built by mkosi and rebooting them. It isn't exactly convenient but it more or less works.

> To get a "frozen" environment, I would recommend defining your own image outside of the systemd repository and only using mkosi in the systemd repository to build distribution packages which you then install in your own image using the PackageDirectories= option

I don't need mkosi for that. I think the bash framework should be easier for me to maintain downstream  than to keep track of all the moving parts that are irrelevant in terms of testing systemd itself.

I'll experiment with it a bit more to see if it's possible to cover my use cases with mkosi at all. If not I'll close the issue.

**Comment by DaanDeMeyer** [comment]
> > I don't think this is possible
> 
> It's possible by building and reinstalling systemd inside images built by mkosi and rebooting them. It isn't exactly convenient but it more or less works.

We support this natively actually. If the `RuntimeBuildSources` setting is enabled (it's enabled by default), the source and build directories are mounted to /work/src and /work/build in any container or virtual machine booted with mkosi. You can then run one of the following:

```
mkosi -t none && mkosi ssh dnf upgrade --disablerepo="*" "/work/build/*.rpm" # CentOS/Fedora
mkosi -t none && mkosi ssh apt install --reinstall "/work/build/*.deb" # Debian/Ubuntu
mkosi -t none && mkosi ssh pacman -U "/work/build/*.pkg.tar" # Arch Linux
mkosi -t none && mkosi ssh zypper install --allow-unsigned-rpm "/work/build/*.rpm" # OpenSUSE
```

in another terminal on the host to build new distribution packages and install them into the virtual machine or container without having to rebuild the image itself.

> > To get a "frozen" environment, I would recommend defining your own image outside of the systemd repository and only using mkosi in the systemd repository to build distribution packages which you then install in your own image using the PackageDirectories= option
> 
> I don't need mkosi for that. I think the bash framework should be easier for me to maintain downstream than to keep track of all the moving parts that are irrelevant in terms of testing systemd itself.
> 
> I'll experiment with it a bit more to see if it's possible to cover my use cases with mkosi at all. If not I'll close the issue.

I definitely want to make this a little more stable in the long running but I'm still trying to find the ideal setup myself.

**Comment by evverx** [comment]
I think I tried RuntimeBuildSources but when systemd is downgraded it can conflict with the other packages and it all goes sideways. It could be I screwed something up though so I'll try again.

**Comment by evverx** [comment]
I don't think I'm going to use mkosi for those purposes so I'll go ahead and close the issue as no planned.

> defining your own image outside of the systemd repository 

Agreed. When systemd components are turned off and replaced or things are linked statically to make some things work it's kind of cumbersome to fight distro packages where those things aren't expected so I don't think it's possible to rely on the upstream infrastructure even with mkosi.
