### ISSUE TITLE
Garbled characters displayed when shutting down

### ISSUE THREAD

**Issue by kindusmithkindu** [systemd/systemd#33757]
### systemd version the issue has been seen with

255.4-1ubuntu8.2

### Used distribution

Linux Mint

### Linux kernel version used

6.10

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Shut down and press the esc key. The screen does not display normal codes.

### Unexpected behaviour you saw

I using Linux Mint22 beta，Whenever I shut down and press the esc key, systemd displays square-like garbled characters on the screen. I don’t know how to deal with it, because the old version of systemd does not have this problem.

### Steps to reproduce the problem

Every time you shut down, press the esc key

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Only displayed when exiting the cinnamon desktop environment
```

**Comment by poettering** [comment]
I have no idea what cinnnamon is, but this really isn't systemd's issue, we are not involved in boot splash stuff or restoring from boot splash. Please contact your distro for help on this, they'll have to deal with this first, and will then elevate this issue if there is one, to the right project (which my guess is plymouth or so).

Closing
