### ISSUE TITLE
Boot hangs due to systemd-networkd-wait-online.service 

### ISSUE THREAD

**Issue by welldonewisher** [systemd/systemd#33760]
### systemd version the issue has been seen with

257

### Used distribution

Debian Bullseye

### Linux kernel version used

5.10.0-26-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd-wait-online

### Unexpected behaviour you saw

systemd-networkd-wait-online.service hung forever.  If it had dependencies on network being up etc, it ideally should have gotten it as it was before I compiled and installed systemd (as Debian/what ever linux uses to bring it up used to do - sorry I only use basic linux commands for my work, which is application-focused and doesn't care what linux does to get me internet/wifi connections) and hence the above service should have been up.

I did saw hints in forums which seemed to indicate that Linux flavors such as Debian doesn't use systemd in favor of something else and by default disabled in later kernel versions.  But I need systemd as I have to work with an older linux kernel v4.4.31 for which Debian doesn't disable it at that time.

I also read a blog which strongly recommended not to unmask/mask (whatever removes that service file) and disable systemd services, as he learnt long back that it was a mistake doing so, even it is suggested by many reddit forums.

I have already asked debian forums and Lenovo support about support for systemd and booting successfully older kernels respectively.  Now my intention here is that, please let me know if systemd should be disabled for 5.10.0-26-amd64 and enabled for v4.4.31.  For the latter case, I assume that the alternate for systemd is not available for that kernel version in Debian.

Also note my Lenovo doesn't have ethernet port or adapter and only wifi adapter.  And ip show after the systemd compile and install now only gives output of the loopback (lo).  So basically, after doing the systemd compilation, I ended up with a non-functional Linux machine.  Kindly advise so I can take the next step.

### Steps to reproduce the problem

Compile and install using meson and ninja as per the docs in systemd README.md.  Reboot.

**Comment by poettering** [comment]
This service's only purpose is to delay boot until the network is online. It's generally only pulled into the boot process if you have something defined that really needs the network up (for example an nfs/smb share listed in /etc/fstab, that is required for boot to proceed).

By default that service is not part of the boot process. And yes, if it hangs your boot if you have no network then it kinda did its service properly.

Anyway, please figure out how it became part of your boot process. But that's really not a question to discuss here, systemd's bug and RFE tracker. Please contact yout downstream distro for help.

THere is no systemd 257 release btw.

**Comment by 4piu** [comment]
In my case, I am using netplan with systemd-networkd. I added the `optional: true` to all the interfaces, then it no longer hangs at boot.

**Comment by yuwata** [comment]
Note, we already introduced systemd-networkd-wait-online@.service (template version) that waits only specific interface.
That may be useful e.g. for laptops that do not have ethernet cables on boot, but whose wireless connection is fine.

**Comment by welldonewisher** [comment]
Too late.  I am focused on the latest tech and no longer interested in your Unix piece of shit.  But your inefficiency has been conveyed to the DoD.  I can't tag Linus, but I will see even if it is required.
