### ISSUE TITLE
Add ability to save core dumps in a different location than "/var/lib/systemd/coredump"

### ISSUE THREAD

**Issue by kapa2512** [systemd/systemd#33771]
### Component

systemd-coredump

### Is your feature request related to a problem? Please describe

I have a system where "/var/lib/systemd/coredump" is only 16MB in size. 
Dump size for some of my services running, are more than 50MB, so I cannot store them properly in the "/var/lib/systemd/coredump"  path. 
In my system I have other locations where I can use more space - e.g. /tmp - 200MB or /var/emmc - 3GB.
I would like to have the ability to change the default  "/var/lib/systemd/coredump" path to some different directory e.g. /tmp/coredump. 

### Describe the solution you'd like

New setting/parameter in the /etc/systemd/coredump.conf file that allows me to change default location, where dumps are stored.

### Describe alternatives you've considered

As an alternative I consider mouting/linking "/var/lib/systemd/coredump" to a different disc/partition. Not sure if this is possible I need to verify that, but anyway new setting in the coredump.conf file would be more clean solution.

### The systemd version you checked that didn't have the feature you are asking for

255.4

**Comment by bluca** [comment]
Sorry but this was asked many times, and the answer is always the same: just use a symlink or a bind mount.

**Comment by poettering** [comment]
WE consider the path API, hence, if you want to redirect it somewhere else, by all means do so, but do it on the fs level via symlink or bind mounts.

**Comment by kapa2512** [comment]
I created symlink in /var/lib/systemd directory:
`root@hgx:/var/lib/systemd# ls -l /var/lib/systemd/ | grep coredump
lrwxrwxrwx    1 root     root            14 Aug 27 17:02 coredump -> /tmp/coredump/
`
It points to /tmp/coredump directory:
`root@hgx:/tmp# ls -l /tmp | grep coredump
drwxrwxrwx    2 root     root            40 Aug 27 17:04 coredump`

But now core dumps are not created at all. I am only seeing such logs from systemd:
`Aug 27 17:08:42 hgx systemd[20374]: systemd-coredump@4-20368-0.service: Failed to set up special execution directory in /var/lib: Not a directory
Aug 27 17:08:42 hgx systemd[20374]: systemd-coredump@4-20368-0.service: Failed at step STATE_DIRECTORY spawning /lib/systemd/systemd-coredump: Not a directory
`
Do you know what I am doing wrong?

**Comment by kapa2512** [comment]
Can you please point me to some example how to correctly setup symlink or bind mount with systemd-coredump? Both I cannot configure properly

**Comment by bluca** [comment]
systemd-coredump has PrivateTmp=yes so it won't see your host's /tmp by default. You need to add a drop-in (`systemctl edit systemd-coredump@.service`) and add `BindPaths=/tmp/coredump` and then do a daemon-reload. Then the symlink to /tmp/coredump will work.

**Comment by Spongman** [comment]
> Sorry but this was asked many times

perhaps some guidance in coredump.conf might reduce the number of duplicate tickets?

i'm still confused as to what's required here. originally it was 'no we're not going to add an option, just use symlinks'. now symlinks aren't sufficient? is it bind-mounts? or BindPaths?

imagine just adding a config options to set the path 🤦
