### ISSUE TITLE
CODEOWNERs to prevent sloppy merges

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#33799]
I'm sorry but looking at https://github.com/systemd/systemd/pull/32991 I think it's time to add CODEOWNERs and require approval from owners before merging anything. I'm not exactly sure what the point of those "reviews" is.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by keszybz** [comment]
Sorry, but we're not going to do this.  "Codeowners" is a mechanism to divide code into fiefdoms. One of the strengths of the development process of systemd has been the fact that anyone and everyone can review requests. Both people who are formally attached to the project and those who are not. We fluidly change who reviews what, requiring very superficial review for trival and obvious patches, all the way up to having discussions over multiple months over the most complicated patches. And it's very usual for different reviewers to concentrate on different facets: one person may review the architecture, another the style, and the third English grammar. Those formalized systems of ownership and checks are inherently not flexible enough. If somebody is active in a given area, other reviewers know about this and will ask that person for review when appropriate.

We will occasionally mess up and merge a patch that is buggy. That's annoying, but also unavoidable and easily corrected.

**Comment by evverx** [comment]
> One of the strengths of the development process of systemd has been the fact that anyone and everyone can review requests

Agreed. Though the idea behind CODEOWNERS (as I saw it) was to limit the ability to merge PRs only. They could still be reviewed by anyone.

> Those formalized systems of ownership and checks are inherently not flexible enough

Agreed.

Either way I agree with the reasoning.
