### ISSUE TITLE
User credential cannot be decrypted by user manager instance

### ISSUE THREAD

**Issue by sammko** [systemd/systemd#33796]
### systemd version the issue has been seen with

256.2

### Used distribution

Arch

### Linux kernel version used

6.9.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Systemd user instance can decrypt user scoped credential.

### Unexpected behaviour you saw

It cannot, failing to access the TPM.

### Steps to reproduce the problem

```
$ echo secret > secret.txt
$ systemd-creds --user -H encrypt secret.txt secret.cred
$ systemd-creds --user decrypt secret.cred
secret

$ systemd-run --user -P --wait -p LoadCredentialEncrypted=secret.cred:$(pwd)/secret.cred -- systemd-creds list
Running as unit: run-u0.service
ERROR:tcti:src/tss2-tcti/tcti-device.c:451:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: Permission denied
Finished with result: exit-code
Main processes terminated with: code=exited, status=243/CREDENTIALS
Service runtime: 7ms
```

It seems that `systemd-creds` uses a different approach to decryption (uses io.systemd.Credentials API) than the user manager instance which appears to try and do it itself? How can it access the `/var/lib/systemd/credential.secret` file in the first place then? Anyway I used `-H encrypt` so the TPM should not be required. The result is the same without `-H`.

**Comment by dschemp** [comment]
Same issue here.
Trying to force the usage of the TPM when encrypting with the `-T` option throws another error which seems to disallow the use of TPM (alone?) in user mode:
```
$ echo -n hunter2 | systemd-creds encrypt --user -T - foobar.cred
Selected key not available in --uid= scoped mode, refusing.
```
---
Side note: Same error appears when trying to encrypt with `--with-key=null`. As far as I understand the man page / docs, only decryption should be disallowed with this option (this is probably pointless for 99.9% of cases but nonetheless)

**Comment by Ruttie2006** [comment]
Is this issue supposed to be fixed?
This issue is closed, the associated pull request is merged, and a release has been made since, but I'm still encountering this issue on `systemd 257 (257.8-2-arch)`.
```
$ echo "Test" | systemd-creds --user -H --name secrets encrypt - ~/secrets
$ systemd-creds decrypt --name secrets --user ~/secrets
Test
$ systemd-run --user -P --wait -p LoadCredentialEncrypted=secrets:~/secrets systemd-creds cat secrets
Running as unit: run-p10391-i10392.service
ERROR:tcti:src/tss2-tcti/tcti-device.c:455:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: Permission denied 
Finished with result: exit-code
Main processes terminated with: code=exited, status=243/CREDENTIALS
Service runtime: 24ms
CPU time consumed: 9ms
Memory peak: 1.7M (swap: 0B)
```

**Comment by markhawkes** [comment]
I believe the fix to this issue was introduced in release [258](https://github.com/systemd/systemd/releases/tag/v258).
It's broken in Ubuntu 25.10 because that uses systemd 257.9, and broken in Debian 13/trixie which uses systemd 257.7.
I just installed a Debian 14/forky container, running systemd 259, and the issue is certainly fixed there.
