### ISSUE TITLE
journalctl option to show journal log since last activation attempt / failure / run only

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#33794]
### Component

journalctl

### Is your feature request related to a problem? Please describe

I wanted to have a global on-failure handler that sends me an e-mail for every failed systemd unit. That is possible.

The handler script should send the journal log for the failed invocation. Only for the failed invocation. Not any earlier log.

### Describe the solution you'd like

A command to show the journal log since the last activation attempt only. Something like:

    journalctl --activation 1 -u unit-name.service

(Similar to the already existing, helpful `--boot`.)

### Describe alternatives you've considered

A scripted solution.

(Pseudo code. Not functional.)

    journalctl -u <unit-name> --since "$(systemctl show -p ActiveEnterTimestamp <unit-name> | cut -d= -f2)"

But I guess that is more fragile.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by arvidjaar** [comment]
Cannot you use
```
journalctl _SYSTEMD_INVOCATION_ID=...
```

**Comment by adrelanos** [comment]
No. Because how would I get the _SYSTEMD_INVOCATION_ID? Requires fragile scripting. Also time-of-check to time-of-use (TOCTOU) issue.
