### ISSUE TITLE
Timezones PST/PDT/MST are not working

### ISSUE THREAD

**Issue by yaitskov** [systemd/systemd#33801]
### systemd version the issue has been seen with

255

### Used distribution

rUbuntu 24.04 LTS

### Linux kernel version used

6.8.0-38-generic

### CPU architectures issue was seen on

x86_64

### Component

timedatectl

### Expected behaviour you didn't see

datetimectl should handle time zones PDT/PST, but it doesn't recognize them.
Meanwhile MST and EST are working. So behavior at least is not consistent.

### Unexpected behaviour you saw

```
~$ sudo timedatectl set-timezone PST
Failed to set time zone: Invalid or not installed time zone 'PST'
~$ sudo timedatectl set-timezone PDT
Failed to set time zone: Invalid or not installed time zone 'PDT'
~$ sudo timedatectl set-timezone MST

```

**Comment by arvidjaar** [comment]
> `datetimectl`

Do you mean `timedatectl`?

> should handle time zones PDT/PST

It handles zones, for which definitions are provided by your distribution. There is no **zone** definitions for `PST` or `PDT`. There are zone definitions for `EST` or `MST`. If you think time zone database also *should* include explicit zone definitions for `PST` or `PDT` - you need to contact time zone database maintainers.

https://www.iana.org/time-zones

**Comment by poettering** [comment]
use "timedatectl list-timezones" for a list of defined time zones. PST, MD, MST are not among them.

This is not a naming choice of ours, but by the venerable tzdata package.
