### ISSUE TITLE
mDNS queriers can't discover services advertised by resolved on the same machine

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#33815]
### systemd version the issue has been seen with

364a0ba2d4d05ec378f84fc56c2d7fb856d40184

### Used distribution

Fedora 40

### Linux kernel version used

6.9.9-200.fc40.x86_64

### CPU architectures issue was seen on

None

### Component

systemd-resolved

### Expected behaviour you didn't see

mDNS queriers like `mquery` can't discover services advertised by resolved on the same machine

(they can discover services advertised by avahi on the same machine though)

### Unexpected behaviour you saw

`mquery` sends its queries from port 5353. resolved receives them
```sh
Jul 22 23:22:08 H systemd-resolved[6851]: Received mdns UDP packet of size 46, ifindex=2, ttl=1, fragsize=0, sender=10.0.2.15, destination=224.0.0.251        
Jul 22 23:22:09 H systemd-resolved[6851]: Received mdns UDP packet of size 46, ifindex=2, ttl=1, fragsize=0, sender=10.0.2.15, destination=224.0.0.251        
Jul 22 23:22:11 H systemd-resolved[6851]: Received mdns UDP packet of size 46, ifindex=2, ttl=1, fragsize=0, sender=10.0.2.15, destination=224.0.0.251   
```
but they are ignored.

It's the part of https://github.com/systemd/systemd/issues/32990 that hasn't been addressed in https://github.com/systemd/systemd/pull/32991.

### Steps to reproduce the problem

```sh
# publish a service
$ sudo busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager RegisterService "sssqqqaa{say}" boop boop _qotd._tcp 123 0 0 0

# make sure it's there
$ resolvectl --legend=no --service-txt=no --service-address=no service boop._qotd._tcp.local
boop._qotd._tcp.local: H.local:123 [priority=0, weight=0]
                       (boop/_qotd._tcp/local)

# run mquery from https://github.com/troglobit/mdnsd
# it can't discover boop._qotd._tcp.local advertised by resolved
$ mquery 
Querying for _services._dns-sd._udp.local. type 12 ... press Ctrl-C to stop
...
```

**Comment by evverx** [comment]
I don't use resolved so it isn't relevant to me.

**Comment by YHNdnzj** [comment]
Hmm? If the problem exists we should still resolve them.

**Comment by evverx** [comment]
Makes sense. Though it makes it harder for me to track those things internally but I guess I can close it downstream only and unsubscribe from all those issues here.

**Comment by evverx** [comment]
It was originally reported in https://github.com/systemd/systemd/issues/32990 and that issue was reopened so I think this issue can be closed after all.

I'll keep https://github.com/systemd/systemd/issues/33806 and https://github.com/systemd/systemd/issues/34416 open if anyone else is interested in keeping track of that stuff.
