### ISSUE TITLE
EFI handover protocol allocates too little memory for the kernel image

### ISSUE THREAD

**Issue by ardbiesheuvel** [systemd/systemd#33816]
### systemd version the issue has been seen with

255

### CPU architectures issue was seen on

None

### Component

systemd-boot, systemd-stub

### Expected behaviour you didn't see

A bzImage is a PE/COFF image that describes its memory footprint in the file header. This footprint consists of initialized data, which is copied from the file, and uninitialized data (BSS) which should be cleared by the loader. A loader should allocate enough memory to cover the entire footprint, copy the file contents to the base of this allocation, and zero the rest.

### Unexpected behaviour you saw

As far as I can tell (apologies if I got this wrong but from the source it is not 100% clear to me which code is used by systemd-boot and which by systemd-stub), the allocation created in `linux_exec_efi_handover ()` is based on the file size not the in-memory size. This means that statically allocated buffers in BSS are a) not cleared, and b) may overlap with unrelated adjacent allocations.

**Comment by bluca** [comment]
> As far as I can tell (apologies if I got this wrong but from the source it is not 100% clear to me which code is used by systemd-boot and which by systemd-stub), the allocation created in linux_exec_efi_handover () is based on the file size not the in-memory size. This means that statically allocated buffers in BSS are a) not cleared, and b) may overlap with unrelated adjacent allocations.

Yep that looks like the case indeed (and yes it's in the stub) - fortunately it's only the case for the legacy handover protocol, but still, we should fix this

**Comment by bluca** [comment]
@ardbiesheuvel is it sufficient to check the SizeOfUninitializedData field in the PE header? If so, it seems to be hard coded to 0 in https://github.com/torvalds/linux/blob/master/arch/x86/boot/header.S#L84 - or are there other fields/headers to consider as well?

**Comment by ardbiesheuvel** [comment]
> @ardbiesheuvel is it sufficient to check the SizeOfUninitializedData field in the PE header? If so, it seems to be hard coded to 0 in https://github.com/torvalds/linux/blob/master/arch/x86/boot/header.S#L84 - or are there other fields/headers to consider as well?

That field lacks an unambiguous definition in the PE/COFF spec, as there could be multiple sections with uninitialized data and sections that are partially initialized, and it is not clear how this field should convey that information, or how it is even useful to do so.

Better to use SizeOfImage, which appears to hold the expected value in most PE/COFF images that I dealt with, including ones built by the ELF-to-PE/COFF converter in Tianocore and the native Windows toolchains.

SizeOfImage covers the entire image, including the header, and should be aligned to the section alignment, so it can be used directly to size the allocation. Note that loading the PE/COFF image correctly would require every section header to be taken into account, and the difference between file size and memory size to be zeroed. However, given that this code deals with Linux x86 bzImages only, I think using SizeOfImage in the allocation and wiping the memory that is not covered by the file data should be sufficient, as only the last section in the file has a larger memory size than file size.

**Comment by bluca** [comment]
Ok thanks, this seems to work for me: https://github.com/systemd/systemd/pull/33882

**Comment by ardbiesheuvel** [comment]
> Ok thanks, this seems to work for me: #33882

Looks correct to me.
