### ISSUE TITLE
Wrong polkit policy checked when adding an inhibitor lock that blocks multiple actions 

### ISSUE THREAD

**Issue by iro-miya** [systemd/systemd#33834]
### systemd version the issue has been seen with

256

### Used distribution

Arch

### Linux kernel version used

6.9.9-hardened1-1-hardened

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

As the documentation on inhibitor locks says:

> Taking inhibitor locks is a privileged operation. Depending on the action org.freedesktop.login1.inhibit-block-shutdown, org.freedesktop.login1.inhibit-delay-shutdown, org.freedesktop.login1.inhibit-block-sleep, org.freedesktop.login1.inhibit-delay-sleep, org.freedesktop.login1.inhibit-block-idle, org.freedesktop.login1.inhibit-handle-power-key, org.freedesktop.login1.inhibit-handle-suspend-key, org.freedesktop.login1.inhibit-handle-hibernate-key,org.freedesktop.login1.inhibit-handle-lid-switch.
> - https://systemd.io/INHIBITOR_LOCKS/#miscellanea

One would think that when creating an inhibitor lock that blocks multiple things, it would check each of those permission first. You wouldn't expect it to only check one, and especially not one that is completely unrelated, and yet...

### Unexpected behaviour you saw

No matter what you wanna block, if you are trying to block multiple things, only a single action is checked: `org.freedesktop.login1.inhibit-handle-lid-switch`. Even if that's not what you're blocking. The actions you do wanna block never get checked, ever.

### Steps to reproduce the problem

1. Set up Polkit logging, for instance with this method: https://wiki.archlinux.org/title/Polkit#Debugging/logging
2. Run `systemd-inhibit --what=shutdown:sleep sleep 2s`, "what" can be anything as long as there are multiple values
3. Check `journalctl -u polkit`, look at the end, you see that the only thing that got checked was `org.freedesktop.login1.inhibit-handle-lid-switch` (logs attached below)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Jul 24 22:02:53 ralsei polkitd[3920]: action=[Action id='org.freedesktop.login1.inhibit-handle-lid-switch']
Jul 24 22:02:53 ralsei polkitd[3920]: subject=[Subject pid=9989 user='miya' groups=wheel,miya,miya seat=null session=null system_unit='user@1000.service' no_new_privileges=false local=true active=true]
```

**Comment by iro-miya** [comment]
I actually think I found the problem in the code, but I am not a C developer, this is just my guess and I have no idea how to fix it.

This is the section that's determining what policy to check for, from https://github.com/systemd/systemd/blob/v256-stable/src/login/logind-dbus.c#L3555-L3562

```c
w == INHIBIT_SHUTDOWN             ? (mm == INHIBIT_BLOCK ? "org.freedesktop.login1.inhibit-block-shutdown" : "org.freedesktop.login1.inhibit-delay-shutdown") :
w == INHIBIT_SLEEP                ? (mm == INHIBIT_BLOCK ? "org.freedesktop.login1.inhibit-block-sleep"    : "org.freedesktop.login1.inhibit-delay-sleep") :
w == INHIBIT_IDLE                 ? "org.freedesktop.login1.inhibit-block-idle" :
w == INHIBIT_HANDLE_POWER_KEY     ? "org.freedesktop.login1.inhibit-handle-power-key" :
w == INHIBIT_HANDLE_SUSPEND_KEY   ? "org.freedesktop.login1.inhibit-handle-suspend-key" :
w == INHIBIT_HANDLE_REBOOT_KEY    ? "org.freedesktop.login1.inhibit-handle-reboot-key" :
w == INHIBIT_HANDLE_HIBERNATE_KEY ? "org.freedesktop.login1.inhibit-handle-hibernate-key" :
"org.freedesktop.login1.inhibit-handle-lid-switch",
```

So this is like a switch on the `w` variable, which contains the things that the hook will block. This does not seem to take into consideration that `w` can represent multiple things.

It seems `w` is an `int` where each bit is one possible action to block, as evidenced by [the way it's generated in `inhibit_what_from_string`](https://github.com/systemd/systemd/blob/v256-stable/src/login/logind-inhibit.c#L506-L523). The part that determines what policy to check for doesn't take that into consideration, so it always falls back to `org.freedesktop.login1.inhibit-handle-lid-switch`

**Comment by bluca** [comment]
Good catch, this is well and truly borken
