### ISSUE TITLE
systemctl start 100+ ceph-osd@.service lead to hang

### ISSUE THREAD

**Issue by chaidisheng** [systemd/systemd#33831]
### systemd version the issue has been seen with

249

### Used distribution

openeuler

### Linux kernel version used

5.10.0-136.69.0.149.oe2203sp1.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

(1) systemd version: systemd 249 (v249-64.oe2203sp1)
+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB -ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=legacy

systemctl start 100+ ceph-osd@.service successfully

### Unexpected behaviour you saw

(1) current question: systemctl start 100+ ceph-osd@.service lead to hang; 
(2) NetworkManager rsyslog etc service of dbus is dead;

### Steps to reproduce the problem

systemctl start 100+ ceph-osd@.service

**Comment by YHNdnzj** [comment]
Sorry, but this is the upstream bug tracker for systemd, and only the latest two versions are supported here, namely v255 and v256. Please contact your distro for support of older versions.

**Comment by chaidisheng** [comment]
systemd 249 Job manager is exists BUG?@YHNdnzj

**Comment by chaidisheng** [comment]
> Sorry, but this is the upstream bug tracker for systemd, and only the latest two versions are supported here, namely v255 and v256. Please contact your distro for support of older versions.

where systemd 249 vs 255 or 256 job manager is different ?
