### ISSUE TITLE
timedatectl via script / alias ?

### ISSUE THREAD

**Issue by mocallins** [systemd/systemd#33844]
I'm trying to set the time via an alias in tcsh, but i can't get the timedatectl command to perform it correctly.
Is there some issue with timedatectl accepting the arguments from the command line, other than manually ?

**Comment by YHNdnzj** [comment]
Sorry, but this is the systemd bug tracker, rather than a support forum. Please turn to our [mailing list](https://lists.freedesktop.org/mailman/listinfo/systemd-devel) for questions/seeking of suggestions. Closing.
