### ISSUE TITLE
`udevadm info --attribute-walk --json` support

### ISSUE THREAD

**Issue by ArXen42** [systemd/systemd#33852]
### Component

udevadm

### Is your feature request related to a problem? Please describe

- `--json` option works for `udevadm info` command
- `--json` option is ignored when used together with `--attribute-walk`

`udevadm info --attribute-walk --json=...`  will always output human-readable text since `print_device_chain` does not currently implement json output.

### Describe the solution you'd like

`udevadm info --attribute-walk --json=...` command outputting device chain in JSON format for easier scripting.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by yuwata** [comment]
Waiting in #33942.

**Comment by ArXen42** [comment]
That was fast, thanks!
