### ISSUE TITLE
How Offline System Updates script install packages?

### ISSUE THREAD

**Issue by xiangzhai** [systemd/systemd#3386]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ArchLinux
### In case of bug report: Expected behaviour you didn't see

> I have read the [Implementing Offline System Updates](https://www.freedesktop.org/software/systemd/man/systemd.offline-updates.html), but I have no idea how update script install (RPM or DEB or whatever) packages, the implementation document is lack of the details about the workflow of install update packages.

PS: My colleague and I implemented a [System Update workflow](https://github.com/isoft-linux/isoft-update-client/blob/master/daemon/README) but systemd-logind Inhibit is not able to forbit command line reboot or poweroff, so if someone explained the workflow about update script install packages, systemd.offline-updates is better choice for us ;-)
### In case of bug report: Unexpected behaviour you saw

> Systemd went into system-update.target, then could not exit, if symlink /system-update
### In case of bug report: Steps to reproduce the problem

> 1. mkdir /var/lib/system-update
>    1. cp some packages (will update system components) into /var/lib/system-update
>    2. symlink /system-update, then reboot
>    3. systemd went into system-update.target, could not exit

**Comment by poettering** [comment]
This is a bug and feature request tracker, please don't misuse it as a support forum. Please direct questions and requests for help to a more appropriate forum, such as the systemd mailing list. Thanks for understanding.

**Comment by xiangzhai** [comment]
I am sorry that I misunderstood the meaning of **_issue**_, I will not make the same mistake any more! but it is better for me to read the source code about system-update-generator or Offline System Updates relevance at first, perhaps I could find the answer by myself ;-P https://github.com/isoft-linux/isoft-update-client/blob/master/daemon/README.md 

Thanks for your immediate reply again! and welcome to Beijing again for GNOME Asia summit ;-)
