### ISSUE TITLE
credentials isolation - please explain

### ISSUE THREAD

**Issue by kjonca** [systemd/systemd#33860]
### systemd version the issue has been seen with

256

### Used distribution

Debian Sid

### Linux kernel version used

6.9.7-amd64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Other services will not be able to read credential

### Unexpected behaviour you saw

Services and host can read decrypted credential

### Steps to reproduce the problem

This is described in:
https://lists.freedesktop.org/archives/systemd-devel/2024-July/050490.html

**Comment by YHNdnzj** [comment]
Sorry, but this isn't a support forum. Please stick with the mailing list if you're only seeking for help.

And this is expected behavior. Credentials are visible outside of mount namespace for privileged processes.

**Comment by YHNdnzj** [comment]
> So what is the benefit of credentials over good old env variables, or config files?

LoadCredential= can be used to load config files with locked down permissions into e.g. services running under `User=` or `DynamicUser=`. Also creds can originate from UKI addons/kernel cmdline/... and get passed down into the service.

For privileged processes there's really no reason to lock creds down. root can nsenter any process anyways, and exposing them makes things more inspectable.
