### ISSUE TITLE
[Feature Request] Fallback DNS Server for resolvectl

### ISSUE THREAD

**Issue by BlackLotus** [systemd/systemd#33865]
### Component

resolvectl

### Is your feature request related to a problem? Please describe

When my main DNS Server is down for whatever reason (server reboot, routing problems, ...) my DNS requests will not be resolved.

### Describe the solution you'd like

I would similar to how `dig something` would resolve when two nameservers were entered. Try the first one 3 times and then fallback to the second nameserver.   
If the main DNS server does not respond it could be marked as deteriorated and be tried only once after that for every request until it resolves again. The state could be captured in `resolvectl status` as well and there could be statistics `resolvectl statistics` that capture how often this happens. 

 Problem will be naming the feature since FallbackDNS already exists.

### Describe alternatives you've considered

In theory I could use a modified resolve.conf or I could use dnsmasq instead.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by BlackLotus** [comment]
This doesn't seem to work for me. I specifically defined quad9 as a Fallback DNS, but I was sure it had to do something else since it never resolved even when the server failed.
This is why I understood the fallback DNS Server as only being used when DHCP doesn't supply a DNS Server...
Here is the config I have (replaced my private DNS address)
```
FallbackDNS=$mydnsip#brainfuck 9.9.9.10#quad9
```
I was pretty sure this should work that it first tries my private DNS and then quad9 if it fails.

**Comment by BlackLotus** [comment]
Here more debugging information
```
[root@GearBox ~]# resolvectl 
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
Fallback DNS Servers: $myserverip#brainfuck 9.9.9.10#quad9 $myserverip

Link 2 (homebond0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: fd18:6f13:9ca1::1
       DNS Servers: 10.0.0.1 fd18:6f13:9ca1::1 2a02:908:e841:a400:10:18ff:fe9b:5c64

Link 4 (wifi0)
    Current Scopes: none
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 10 (dellmonitor0)
    Current Scopes: none
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

When I do `resolvectl query google.de` it never finishes

**Comment by poettering** [comment]
> This doesn't seem to work for me. I specifically defined quad9 as a Fallback DNS, but I was sure it had to do something else since it never resolved even when the server failed.

that's a misunderstanding. The fallback dns servers are only used if no other dns configuraiton is available. See docs. if dns server configuration *is* available, but the servers do not respond the fallback servers will not be considered.

just specify your servers as regular servers, add as many as you wish. they'll be tried in a round robin fashion, whenever one doesn't respond.
