### ISSUE TITLE
Default credstore for user services

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#33887]
### Is your feature request related to a problem? Please describe

From https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html

> If no matching system credential is found, the directories /etc/credstore/, /run/credstore/ and /usr/lib/credstore/ are searched for files under the credential's name — which hence are recommended locations for credential data on disk. If LoadCredentialEncrypted= is used /run/credstore.encrypted/, /etc/credstore.encrypted/, and /usr/lib/credstore.encrypted/ are searched as well.

Shouldn't there be a similar fallback/default directory to store creds intended for use in user services ?

### Describe the solution you'd like

maybe `.config/credstore(.encrypted)` or `.config/systemd/credstore(.encrypted)`

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by YHNdnzj** [comment]
(I originally raised this in https://github.com/systemd/systemd/pull/30968#pullrequestreview-1845344536)

**Comment by CMCDragonkai** [comment]
What are the directory paths for per-user encrypted credentials? For system level we have `/etc/credstore.encrypted`. What is it for users?

**Comment by CMCDragonkai** [comment]
Is it?

```
~/.config/systemd/credstore.encrypted/​
~/.local/share/systemd/credstore.encrypted/​
```
