### ISSUE TITLE
tmpfiles.d/systemd.conf.in missing entry for /run/log/journal/system.journal?

### ISSUE THREAD

**Issue by nanouck** [systemd/systemd#33894]
### systemd version the issue has been seen with

241

### Used distribution

debian buster

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

/run/log/journal/system.journal is owned by root:systemd-journal at first boot

### Unexpected behaviour you saw

-rw-r----- 1 root root 8388608 Aug  1 09:59 /run/log/journal/system.journal

### Steps to reproduce the problem

first boot of azure VM instance
create an account in systemd-journal group
```
useradd --system --user-group --groups systemd-journal --no-create-home --shell /sbin/nologin otelcol-contrib && su -s /bin/bash -c 'journalctl -e' otelcol-contrib
No journal files were opened due to insufficient permissions.
```

**Comment by bluca** [comment]
The entry is there:

https://github.com/systemd/systemd/blob/a8bc75089d8ecca60fa616670086c322c99b8aa5/tmpfiles.d/systemd.conf.in#L25

If it's missing on your image, which is based on a very very old release, you can simply add it yourself under /etc/tmpfiles.d/

**Comment by nanouck** [comment]
hi @bluca correct me, but this line does not manage /run/log/journal/system.journal but /run/log/journal/<machine id>/ folder.

I will double check on debian 12, however fyi, on debian 10 (version 241)  `/run/log/journal/system.journal` is not a link to `/run/log/journal/<machine id>/system.journal`

However we'get got a workaround: `systemctl restart systemd-journald`
