### ISSUE TITLE
Ellipsized localectl lines

### ISSUE THREAD

**Issue by morenathan** [systemd/systemd#33906]
### Component

other

### Is your feature request related to a problem? Please describe

When any string in _"localectl status"_ grows longer than the screen it will ellipsize the output. The option for _"localectl --no-pager status"_ does not affect the output in any way. Finally, the option of _"-l"_ that is used by systemctl does not work.

What does work is to pipe the status output into less, i.e. _"localectl | less"_, which will allow you to see all content from the status.

### Describe the solution you'd like

Implement the _"-l"_ option and remove _"--no-pager"_ since it is useless in this scenario. The _"-l"_ option show be the implied output option along with _"status"_.

### Describe alternatives you've considered

Creating an alias for localectl: `alias='localectl | less -F`

This method loses the formatting of course without a more complex setup.

### The systemd version you checked that didn't have the feature you are asking for

256.4

**Comment by yuwata** [comment]
Hm? `localectl status` is typically shows only few short lines. Could you provide the result of the command ?

**Comment by morenathan** [comment]
`~: localectl
System Locale: LANG=en_US.UTF-8
    VC Keymap: us2
   X11 Layout: us
    X11 Model: pc104
  X11 Options: lv2:lsgt_switch,lvl3:ralt_switch,caps:ctrl_modifier,shift:breaks_caps,eurosign:2,mod_led,misc:typo,shift:both_c…
~:`

**Comment by yuwata** [comment]
Thanks.

**Comment by yuwata** [comment]
-> #33908.
