### ISSUE TITLE
nspawn/systemd create /lib64 -> /usr/lib/<arch tuple> symlink instead of /lib64 -> /usr/lib64

### ISSUE THREAD

**Issue by zeha** [systemd/systemd#33919]
### systemd version the issue has been seen with

256

### Used distribution

Debian 12

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

systemd-nspawn creates a /lib64 symlink in the `-D` directory. It does this by calling `base_filesystem_create` which has opinions about the filesystem layout on Fedora (see comments in that function). However, this is unconditionally applied for any OS.

### Steps to reproduce the problem

- Create an aarch64 OS image that does not have `/lib64`. Example: Debian sid.
- Run systemd-nspawn on it.
- Observe you now have a `/lib64` symlink

If you picked an old enough Debian, upgrading `base-files` will now fail because of the invalid `/lib64` symlink.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
/* aarch64 ELF ABI actually says dynamic loader is in /lib/, but Fedora puts it in /lib64/ anyway and
         * just symlinks /lib/ld-linux-aarch64.so.1 to ../lib64/ld-linux-aarch64.so.1. For this to work
         * correctly, /lib64/ must be symlinked to /usr/lib64/. */
```

**Comment by zeha** [comment]
Note that this causes downstream bugs like http://bugs.debian.org/1076491

**Comment by bluca** [comment]
There are two issues here:

1) base-files gained a very zealous check that enforces that /foo is a symlink to /usr/foo and nothing else - this wasn't there before, while our handling of base filesystem has been there for years
2) our base filesystem handling prefers creating symlinks to multiarch subdirectories, and it seems that it should instead prefer /lib64 -> /usr/lib64 (I am still attempting to confirm this)

**Comment by zeha** [comment]
At least on Debian the /libXXX dirs are not arch-specific. Their existence is an artifact of the installed packages, but if you must support an OS image lacking them, the currently correct set is:

- /lib64 -> /usr/lib64
- /lib32 -> /usr/lib32
- /libo32 -> /usr/libo32
- /libx32 -> /usr/libx32

I don't know if on other OS'es this is arch specific. I somehow doubt it.

**Comment by zeha** [comment]
I'll note that this is a perfectly valid setup of an aarch64 system:

```
lrwxrwxrwx 1 root root      7 30. Mär 18:06 /lib -> usr/lib/
lrwxrwxrwx 1 root root      9  3. Aug 17:18 /lib64 -> usr/lib64/
lrwxrwxrwx 1 root root     36 30. Apr 23:07 /lib64/ld.so.1 -> /lib/mips64el-linux-gnuabi64/ld.so.1
lrwxrwxrwx 1 root root     39 30. Apr 23:07 /lib/ld-linux-aarch64.so.1 -> aarch64-linux-gnu/ld-linux-aarch64.so.1
lrwxrwxrwx 1 root root     24 30. Apr 23:07 /lib/ld.so.1 -> mipsel-linux-gnu/ld.so.1
lrwxrwxrwx 1 root root     10  3. Aug 17:18 /libo32 -> usr/libo32/
-rwxr-xr-x 1 root root 211092 30. Apr 23:07 /libo32/ld.so.1
```
