### ISSUE TITLE
DHCPv6-PD catch-all route should be configurable

### ISSUE THREAD

**Issue by n12c** [systemd/systemd#33929]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

I use DHCPv6-PD with networkd on my home gateway. My ISP delegates a /56, and I use several /64s as described in systemd.network(5).

I have set up a simple stateful firewall using `ip6tables`, which admits only return traffic from the internet:

```
*filter
:FORWARD DROP
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lan -j ACCEPT
```

This works for assigned subnets only. For example, if `SubnetId=0` is assigned to my LAN, then the unsolicited traffic to this /64 is dropped as expected. If I have not assigned `SubnetId=1` on the other hand, unsolicited traffic to this /64 is not dropped silently but instead generates a destination unreachable ICMP error.

### Describe the solution you'd like

After some investigation I understood that this was the action of the "catch-all" route created by networkd:

```
unreachable 2001:db8::/56 dev lo proto dhcp metric 1024 pref medium
```

The purpose of which is explained by https://github.com/systemd/systemd/issues/21101#issuecomment-1040318173. Because the routing decision is made before the `FORWARD` chain of the `filter` table is traversed, the firewall has no role in this at all. This came as a surprise.

I suggest one of the following changes:

* The type of the catch-all route should change to `blackhole`.
* The type should be configurable, and the default should be `blackhole`.
* The type should be configurable, but the default should stay `unreachable`.
* The documentation should be improved to point out that a conventional firewall using the `filter` table will not be effective in producing a configuration that is silent to unsolicited traffic.

### Describe alternatives you've considered

A workaround is to drop traffic to unassigned address space using the `mangle` table:

```
*mangle
-A PREROUTING -m addrtype --dst-type UNREACHABLE -j DROP
```

This works but it takes an unreasonable leap of insight to realize that it is necessary and discover its form.

### The systemd version you checked that didn't have the feature you are asking for

256.4

**Comment by yuwata** [comment]
How about the following syntax?
```
[DHCPv6]
DelegatedPrefixRouteType=(no|unreachable|prohibit|blackhole|throw)
```
Defaults to unreachable.

**Comment by n12c** [comment]
There should be less focus on implementation details and more on the functional outcome.

The existence of a catch-all route, that it has a type in the kernel sense, and what that type is are details. There are other ways to realize the RFC requirement, such as iptables, nftables, or BPF.

The salient part to the administrator is the outward network behaviour, namely the disposition of traffic to unassigned address space. Accordingly, I would go for something like:

```
[DHCPPrefixDelegation]
UnassignedSubnetPolicy=(reject|drop)
```

The word `Subnet` is consistent with `SubnetId` and the words `Policy`, `reject` and `drop` make reference to analogous firewall concepts.

Configuration options that admit the non-terminal disposition of this traffic (such as `no`, presumably) seem to violate a `MUST` RFC requirement and would be harmful as described in https://github.com/systemd/systemd/issues/21101#issuecomment-1040318173. I have omitted this option.

**Comment by yuwata** [comment]
-> #33929.

We already have `Type=` to `[Route]` section. So, I think it is OK to expose further 'implementation detail'. But anyway, further suggestions are welcome, of course.
