### ISSUE TITLE
Make global DNSOverTLS=yes decay to opportunistic when applied to per-link servers

### ISSUE THREAD

**Issue by ZLima12** [systemd/systemd#33927]
### Component

systemd-networkd, systemd-resolved

### Is your feature request related to a problem? Please describe

Currently, setting the global `DNSOverTLS` option to `yes` causes per-link DNS servers to default to this value. I don't believe that such a generalization is useful, considering that:
1. Many (if not most) networks will have a local resolver advertised through DHCP, which will almost certainly not support DoT.
2. ~~For networks that do advertise a public resolver which supports DoT, there is no way for the SNI to be specified.~~ There is currently no support for the DHCP option which specifies the SNI. #30952 would implement this, but I can't imagine that many networks are using this option.

The practical effect of this is that links on the networks mentioned in point 1 will not by default have working resolvers. `DNSOverTLS=no` or `DNSOverTLS=opportunistic` must be explicitly specified in the `.network` file for each of these cases.

### Describe the solution you'd like

I suggest that `no` (disable DoT entirely) and `opportunistic` should be the only possible default values for per-link servers. For links where DoT must always be used, `DNSOverTLS=yes` along with `DNS=1.2.3.4#resolver.example.com` must be explicitly specified in the corresponding `.network` file.

The behavior of setting the global `DNSOverTLS` option to `no` or `opportunistic` shall remain the same. When it is set to `yes`, links that do not have a per-link value specified shall be assigned `opportunistic`, whereas they previously would have been assigned `yes`.

### Describe alternatives you've considered

1. Allow the situation to remain as-is. As mentioned earlier, this means setting `DNSOverTLS=no` or `DNSOverTLS=opportunistic` for many networks. This is rather tedious.
2. Add a separate global option (e.g. `LinkDNSOverTLS`), decoupling the link default from the global default.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by rpigott** [comment]
> For networks that do advertise a public resolver which supports DoT, there is no way for the SNI to be specified.

There is a DHCP option for this, which is implemented in the DHCP client by https://github.com/systemd/systemd/pull/30952.
