### ISSUE TITLE
struct dm_target_msg has a flexible array member, it should not appear in the middle of another struct.

### ISSUE THREAD

**Issue by crrodriguez** [systemd/systemd#33936]
https://github.com/systemd/systemd/blob/bd5b586ad036ee70856d2a350924eea1193df379/src/shared/dm-util.c#L13-L17

It is unspecified what happens if an struct containing a flexible array appears in the middle of another struct, it must appear at the end.. until now GCC tolerates this code, current versions have a warning -Wflex-array-member-not-at-end to singal this is a deprecated extension

**Comment by bluca** [comment]
Could you please send a PR to fix it?
