### ISSUE TITLE
networkd: Redundant Home IPv6 routers sending different priority RAs not respected - can we add ability to add a floating gateway address

### ISSUE THREAD

**Issue by cooperlees** [systemd/systemd#33966]
### systemd version the issue has been seen with

systemd 255 (255.4-1ubuntu8.2)

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.9.12-060912-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

I'm attempting to get my backup router to send LOW priority RAs so that I only use it for IPv6 default route (gateway) when my primary fails. Right now I get HIGH priority from both routers even when I have `LOW` set.

I'd like to do achieve active/passive routers via the two following ways:
- RA preference being sent correctly
- Being able to specify a floating address I have via `keepalived` (that being fe80::1) in the RAs ...

I am also happy for other config suggestions. There is a chance I am misconfiguring here, so please say so if that's the case (even better for me no bug to fix!)

### Unexpected behaviour you saw

HIGH priority RAs and RAs being "reflected" ... these I don't understand. See included tcpdumps from my fedora box connected to same Layer 2 (VLAN) broadcast domain.

ECMP default routes I don't want:
```
cooper@cooper-fedora-MJ0J8MTZ:~$ ip -6 route
2600:1700:3040:13e0::/64 dev enp1s0 proto ra metric 100 pref medium
2600:1700:3040:13e2::/64 dev enp1s0 proto ra metric 100 pref medium
fd00:1::/64 dev enp1s0 proto ra metric 100 pref medium
fd0a:a1f3:2145:924d::/64 dev enp1s0 proto ra metric 100 pref medium
fd5e:14e3:5baa::/64 via fe80::87a:f567:7eeb:9850 dev enp1s0 proto ra metric 100 pref medium
fe80::/64 dev enp1s0 proto kernel metric 1024 pref medium
default proto ra metric 20100 pref low
	nexthop via fe80::3 dev enp1s0 weight 1 
	nexthop via fe80::2 dev enp1s0 weight 1
```

RAs from each router:
```
cooper@cooper-fedora-MJ0J8MTZ:~$ sudo tcpdump -n -nn -i enp1s0 'ip6[40] = 134' -v

# home1 - Should be HIGH priority
09:25:02.302528 IP6 (flowlabel 0x7433b, hlim 255, next-header ICMPv6 (58) payload length: 104) fe80::2 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 104
	hop limit 0, Flags [other stateful], pref high, router lifetime 30s, reachable time 0ms, retrans timer 0ms
	  source link-address option (1), length 8 (1): ac:1f:6b:6f:0d:97
	  prefix info option (3), length 32 (4): 2600:1700:3040:13e2::/64, Flags [onlink, auto], valid time 2789s, pref. time 1800s
	  rdnss option (25), length 24 (3):  lifetime 600s, addr: fd00:68::69
	  dnssl option (31), length 24 (3):  lifetime 600s, domain(s): cooperlees.com.

# home2 - Shouldn't be HIGH priority, as LOW priority is set
09:24:58.961822 IP6 (flowlabel 0xfa67a, hlim 255, next-header ICMPv6 (58) payload length: 104) fe80::3 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 104
	hop limit 0, Flags [other stateful], pref low, router lifetime 30s, reachable time 0ms, retrans timer 0ms
	  source link-address option (1), length 8 (1): 00:e0:67:20:1f:c9
	  prefix info option (3), length 32 (4): fd00:1::/64, Flags [onlink, auto], valid time 3600s, pref. time 1800s
	  rdnss option (25), length 24 (3):  lifetime 600s, addr: fd00:70::69
	  dnssl option (31), length 24 (3):  lifetime 600s, domain(s): cooperlees.com.
```

### Steps to reproduce the problem

You just need two routers doing DHCPv6-PD and both sending RAs. Even when I try stop sending RAs from the second box they do not stop (don't know if this is another bug or some part of the standard I don't understand).

# Home1 network unit
```
cooper@home1:/etc/systemd/network$ cat 71-vlan69.network 
[Match]
Name=vlan69

[Network]
Description=Main user VLAN
DHCP=no
Address=10.6.9.2/24
Address=fd00:1::2/64
Address=fe80::2/64
DHCPServer=no
IPForward=yes
DHCPv6PrefixDelegation=yes
IPv6AcceptRA=no
IPv6SendRA=yes
LLDP=yes
EmitLLDP=nearest-bridge

[DHCPPrefixDelegation]
UplinkInterface=att

[IPv6SendRA]
Managed=no
RouterLifetimeSec=30
RouterPreference=high
OtherInformation=yes
EmitDNS=yes
DNS=fd00:68::69
EmitDomains=yes
Domains=cooperlees.com
DNSLifetimeSec=600
```

# Home2 network unit
```
cooper@home2:/etc/systemd/network$ sudo cat 71-vlan69.network 
[Match]
Name=vlan69

[Network]
Description=Main user VLAN
DHCP=no
Address=10.6.9.3/24
Address=fd00:1::3/64
Address=fe80::3/64
DNS=8.8.8.8
DNS=8.8.4.4
DHCPServer=no
IPForward=yes
IPv6SendRA=yes
IPv6AcceptRA=no
LLDP=yes
EmitLLDP=nearest-bridge

# Floating Static routes - metric higher than DHCP learnt default from ISP
[Route]
Destination=0.0.0.0/0
Gateway=10.6.9.2
Metric=1069

[IPv6Prefix]
Prefix=fd00:1::/64
Assign=no

[IPv6SendRA]
Managed=no
OtherInformation=yes
RouterLifetimeSec=30
RouterPreference=low
EmitDNS=yes
DNS=fd00:70::69
EmitDomains=yes
Domains=cooperlees.com
DNSLifetimeSec=600
UplinkInterface=he-tunnel
```

## Logical layout
![image](https://github.com/user-attachments/assets/b4a840b2-de22-4de6-a651-687ab7423fc2)

I have attached a network diagram. Let me know any more information that would be helpful.

**Comment by cooperlees** [comment]
O, the TCP dump does show the backup RA actually having the preference of LOW, so maybe NetworkManger on my Fedora box ignores that flag?

That said, would we be open to allowing me to have the RAs advertise a custom gateway address? For me that would be `fe80::1` ... then I can have keepalived fail it over when it makes sense ...

**Comment by yuwata** [comment]
You can also use [IPv6RoutePrefix] to advertise custom routes.

Anyway, this is a bug in NetworkManager and others. Closing.
