### ISSUE TITLE
Log messages - when a still-running unit is "stopped" or "killed", a reason must be given

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#33969]
### Component

systemd

### Is your feature request related to a problem? Please describe

Properly running units are "stopped" or "killed" for no apparent reason.

When a still-running unit is mysteriously "stopped" or "killed" during boot, and then immediately "started", there is no apparent method for determining *why* that unit was stopped or killed.

Note - in the cases of interest here, the unit process *has not* exited, and *is still running*.  systemd appears to be "hallucinating" stop, kill, and restart commands.

The units have "Restart=no".  Why would they appear to go through a "restart"?

This "mystery stop" only appears during initial system start.

### Describe the solution you'd like

When a unit is "killed" as a consequence of a signal, what was the source of that signal?!
When a still-running unit is "stopped" for no apparent reason, *why* was the unit stopped?  *What* is "stopping" the unit?!

Add a log message, or add to the log message, the source of any signal, of the source of the mechanism which is "stopping" a running unit.  Was there a "stop" command?  Was there a "restart" command?  Did the process exit?  Was there a BindsTo= or a ConditionPathExists= event?  Was there a signal?  From where?

### Describe alternatives you've considered

Tried adding and changing ordering dependencies, both using systemd unit Before= and After=, and by delaying the unit Start using ExecStartPre= shell commands - no help.

When the unit process is *still running*, there is no way to ask the unit "Why did you stop?"

When the unit "starts" again, the "status" log is erased and rewritten.

### The systemd version you checked that didn't have the feature you are asking for

256.4

**Comment by polarina** [comment]
For what it's worth, I've had systemd do many unintuitive things during boot like you've described. Turns out the culprit was the `systemctl isolate` functionality, which of course the boot process does a lot. It takes a bit of an effort to grok its consequences.

**Comment by dtardon** [comment]
> Properly running units are "stopped" or "killed" for no apparent reason.
> 
> When a still-running unit is mysteriously "stopped" or "killed" during boot, and then immediately "started", there is no apparent method for determining _why_ that unit was stopped or killed.
> 
> Note - in the cases of interest here, the unit process _has not_ exited, and _is still running_. systemd appears to be "hallucinating" stop, kill, and restart commands.
> 
> The units have "Restart=no". Why would they appear to go through a "restart"?
> 
> This "mystery stop" only appears during initial system start.

I doubt it very much there's any "mystery" there. I'm pretty sure what you describe is the transition from initrd to the real system. All units that have been running in the initrd are stopped at that point (they _have to_ be, because the initrd is a _different_ system).

**Comment by dtardon** [comment]
> For what it's worth, I've had systemd do many unintuitive things during boot like you've described. Turns out the culprit was the `systemctl isolate` functionality, which of course the boot process does a lot.

That's not true. `isolate` is done _exactly once_ during a typical boot, at transition from initrd. (Unless you have third-party units that run `systemctl isolate` on their own.)

**Comment by thx1111** [comment]
> @dtardon - I'm pretty sure what you describe is the transition from initrd to the real system.

No.  The processes that are being killed are setting-up my network interfaces.  They are not at all part of initrd.

On the other hand, the units do have:
```
After= sys-subsystem-net-devices-%i.device
BindsTo= sys-subsystem-net-devices-%i.device
ConditionPathExists= /sys/class/net/%i
```
If anything in the `systemd` boot process were to twiddle the network interface "devices" or the "path", if the interface were to "disappear" momentarily, then this could cause problems.

Still, I don't see any reason that the "Stop" log messages shouldn't be more specific about their reason to have been triggered.

**Comment by poettering** [comment]
not sure i follow. we generate logs which should clearly explain what is going on? are you saying a service you started and then stopped didn't actually get stopped and there were no log generated about that?

**Comment by thx1111** [comment]
No, no.

There are two units, in this case, which are started as a consequence of:
```
After= sys-subsystem-net-devices-%i.device
BindsTo= sys-subsystem-net-devices-%i.device
ConditionPathExists= /sys/class/net/%i
```
after the appearance of the device, enp6s0, an ethernet interface.  The two units start-up and run just as they should, without any problems.

And then, *for no apparent reason*, one unit is "killed":
```
Aug 08 13:12:38 topaz systemd[1]: sit1@enp6s0.service: Control process exited, code=killed, status=15/TERM
```
and the other unit is "stopped":
```
Aug 08 13:13:10 topaz systemd[1]: Stopping WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0...
```
Subsequently, immediately after, the units are automatically "restarted":
```
Aug 08 13:12:38 topaz systemd[1]: Starting Tunnel Interface "sit1" through Physical Interface enp6s0...
...
Aug 08 13:13:40 topaz systemd[1]: Stopped WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0.
Aug 08 13:13:40 topaz systemd[1]: Starting WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0...
```
Of course, this "killing", "stopping", and "restarting" is a useless waste of time.  But, *why* is it happening?  The systemd log messages do *not* say *why* the the units were "killed" or "stopped".  They just *are*.

That is one problem, the failure to mention the source of the action in the log messages.

Another possible problem would be *if* the ethernet interface, enp6s0 here, were to "mysteriously disappear" for a moment, as might be perceived by systemd itself, considering the conditions BindsTo= and ConditionPathExists=:
```
BindsTo= sys-subsystem-net-devices-%i.device
ConditionPathExists= /sys/class/net/%i
```
then systemd might determine that the units should be "killed" or "stopped".   But that is only conjecture.  And it does not seem to explain why the unit sit1@enp6s0.service would be "killed" instead of simply "stopped".

**Comment by poettering** [comment]
If systemd kills them it will log about that. But frankly anything can kill them, and the kernel simply doesn't tell us what did. Maybe some of your own scripts are causing this? Some cronjob or so? Config reload?

Hence, this isn't actually actionable to us, we are just the messengers here, basically, react on what is happening.

You can probably use bpf to figure out what precisely is causing this.

Anyway, systemd appears not to blame here, and there's nothing to do for us, hence closing.

**Comment by poettering** [comment]
> It is _systemd_ which is "stopping" the service unit [dhcp6c-enp4s0@.service](mailto:dhcp6c-enp4s0@.service).

systemd stops units whose main process dies generally. i.e. there are two ways a unit can get stopped: because systemd asks it to, or because itself exits (possibly on request of somebody else).

systemd certainly has an idea why it stops something. debug logs will tell you.

**Comment by thx1111** [comment]
Well, accepting your supposition for the moment, that systemd "certainly has an idea why it stops something", and that "debug logs will tell you", then, given the sequence of systemd log messages for this unit, using `journalctl -ab -p7`:
```
Aug 21 12:29:52 topaz systemd[1]: Starting WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0...
...
Aug 21 12:29:54 topaz dhcp6c[1073]: client6_recvreply: got an expected reply, sleeping.
...
Aug 21 12:29:56 topaz systemd[1]: Started WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0.
...
Aug 21 12:30:32 topaz systemd[1]: Startup finished in 15.259s (kernel) + 1min 11.793s (userspace) = 1min 27.052s.
Aug 21 12:30:32 topaz systemd[1]: Stopping WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0...
...
Aug 21 12:31:05 topaz dhcp6c[1073]: dhcp6_remove_event: removing an event on enp6s0, state=RELEASE
Aug 21 12:31:05 topaz dhcp6c[1073]: check_exit: exiting
Aug 21 12:31:05 topaz systemd[1]: dhcp6c-enp4s0@enp6s0.service: Deactivated successfully.
Aug 21 12:31:05 topaz systemd[1]: Stopped WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0.
Aug 21 12:31:05 topaz systemd[1]: Starting WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0...
...
Aug 21 12:31:06 topaz dhcp6c[1459]: client6_recvreply: got an expected reply, sleeping.
Aug 21 12:31:07 topaz systemd[1]: Started WIDE-DHCPv6 dhcp6c with PD Subnet on enp4s0 and NA on interface enp6s0.
```
please explain *where* in the log messages systemd is disclosing *why* it has "Deactivated successfully" this unit. 

What is the reason?  What is the trigger source?

There certainly is no "systemctl stop" being sent anywhere from userspace or from other systemd units.

**Comment by poettering** [comment]
turn on debug log. "systemd-analyze log-level debug". it will then tell you in a lot more detail. As I mentioned before.

**Comment by thx1111** [comment]
"As I mentioned before."  Not really.  And `systemd-analyze log-level debug` is useless *after* boot.  Apparently, the correct mechanism is setting `systemd.log_level=debug` on the kernel command line, or setting `LogLevel=debug` in "/etc/systemd/system.conf".  I'll give that a try.

Annoyingly, the documentation requires the reader to make - mostly obvious - inferences.  systemd-system.conf(5)  only says "See systemd(1) for details."  And systemd(1) says "See systemd-system.conf(5) for more information.", without actually making any mention of "/etc/systemd/system.conf" under the section "OPTIONS".    systemd(1)  does mention "(In particular, "key=value" assignments on the kernel command line are turned into environment variables for PID 1).", but rather indirectly, and only parenthetically, under the "ENVIRONMENT" section.  Understanding the four and a half different ways to configure systemd is sort of an Easter Egg Hunt.

**Comment by thx1111** [comment]
See also now https://github.com/systemd/systemd/issues/31884
