### ISSUE TITLE
CPUAffinity can not be set on slices.

### ISSUE THREAD

**Issue by Firstyear** [systemd/systemd#33977]
### systemd version the issue has been seen with

systemd-255.8-1.1.x86_64

### Used distribution

OpenSUSE Tumbleweed

### Linux kernel version used

6.9.9-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Systemd should be able to set CPUAffinity in Slices.

### Unexpected behaviour you saw

CPUAffinity can be set in systemd.conf.

### Steps to reproduce the problem

Set CPUAffinity in /etc/systemd/system.conf.d/affinity.conf

Then attempt to set CPUaffinity in user.slice or machine.slice.

https://www.freedesktop.org/software/systemd/man/latest/systemd-system.conf.html#CPUAffinity=

https://www.freedesktop.org/software/systemd/man/latest/systemd.slice.html

"""
See [systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#) for the common options of all unit configuration files. The common configuration items are configured in the generic [Unit] and [Install] sections. The slice specific configuration options are configured in the [Slice] section. Currently, only generic resource control settings as described in [systemd.resource-control(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#) are allowed.
"""

Neither systemd.unit or systemd.resource-control allow "CPUAffinity".

**Comment by YHNdnzj** [comment]
> Neither systemd.unit or systemd.resource-control allow "CPUAffinity".

`slice` units are simply cgroup hierarchy representation, which don't contain processes, while `CPUAffinity=` is process-specific. The `CPUAffinity=` setting in `system.conf` applies to pid1, i.e. a specific process. Sorry, but there is no cgroup-wide equivalent of this option, hence this cannot be supported. Closing.
