### ISSUE TITLE
nspawn empties iproute2 routing rule table

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#33974]
### systemd version the issue has been seen with

256

### Used distribution

openSUSE.org Tumbleweed 20240807

### Linux kernel version used

6.10.3-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

Keep the list of packet routing rules intact.

### Unexpected behaviour you saw

```
# ip ru add fwmark 1
# ip ru l
0:      from all lookup local
32765:  from all fwmark 0x1 lookup main
32766:  from all lookup main
32767:  from all lookup default
# machinectl start motenda; sleep 1; ip ru l
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default
```

### Steps to reproduce the problem

Establish this networkd configuration:
```
# ls -al /etc/systemd/network/
total 0
drwxr-xr-x  2 root root  37 Aug 10 10:27 .
drwxr-xr-x 16 root root 298 Jul 24 15:49 ..
lrwxrwxrwx  1 root root   9 Aug 10 09:05 80-container-ve.network -> /dev/null
```
Establish this nspawn configuration:
```
# ls -l /etc/systemd/nspawn/
total 4
-rw-r--r-- 1 root root 56 Aug 10 10:26 motenda.nspawn
# cat motenda.nspawn 
[Exec]
Boot=on

[Network]
Private=on
VirtualEthernet=on
```
Launch:
```
machinectl start motenda
```

(When I comment out VirtualEthernet=on, the issue disappears and rules stay intact when starting the container.)

**Comment by yuwata** [comment]
- Is it new in v256 (or a recent release)?
- nspawn does not handle routing rule. Is networkd enabled on the host side?
- If networkd is used, please try to generate debugging logs of networkd and provide them. You can generate debugging logs by creating a drop-in with `sudo systemctl edit systemd-networkd.service`:
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
and restarting systemd-networkd.

**Comment by yuwata** [comment]
Ah, if networkd is used, routing rules need to be created with a .network file, or set `ManageForeignRoutingPolicyRules=no` in networkd.conf.
