### ISSUE TITLE
sysv-generator sets indefinite timeout

### ISSUE THREAD

**Issue by emilfihlman** [systemd/systemd#3398]
### Submission type
- [X] Request for enhancement (RFE)
### Used distribution

> Debian Jessie
### Description

> A start job is running for LSB: raise network interfaces [ x seconds / no limit ] 
> is something that should not happen. However, while everyone should strive for sane default configs (the problem mentioned is due to dhclient -6 and Debian apparently) systemd could prevent issues like this from rendering the system unusable by including a global upper limit to all timeout(s), especially for TimeoutStart\* and variations.

**Comment by martinpitt** [comment]
The sysv-generator deliberately sets `TimeoutSec=0` for init.d scripts, as they don't declare sane timeouts by themselves. This reproduces the behaviour of SysV init and is IMHO correct.

Indeed the better solution would be to add proper systemd units to packages (like it happened for this particular problem in Debian, ifupdown has a native unit in Debian testing/unstable).

So from my POV this should be closed as "wontfix".

**Comment by poettering** [comment]
Yeah, we have to mimic SysV behaviour for SysV services. If you want timeouts use native unit files. Closing.
