### ISSUE TITLE
VLAN interface is not behaving as expected when main interface is renamed

### ISSUE THREAD

**Issue by sshedi** [systemd/systemd#33988]
### systemd version the issue has been seen with

255.10

### Used distribution

PhotonOS

### Linux kernel version used

6.1.83

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

VLAN interface should be hooked to the interface as specified in network files.

### Unexpected behaviour you saw

VLAN interface is hooked to wrong interface.

### Steps to reproduce the problem

1. Add two additional interfaces eth1 and eth2

2. Rename eth1 to sub1, create files for creating subinterface sub1.vl101, restart systemd-networkd:

`ip link set dev eth1 down && ip link set dev eth1 name sub1`

```
cat > /etc/systemd/network/50-sub1-nc.network <<EOF
[Match]
MACAddress=00:50:56:b2:f1:03

[Network]
DHCP=no
IPv6AcceptRA=no
VLAN=sub1.vl101
EOF
```

```
cat > /etc/systemd/network/50-sub1.vl101-nc.netdev <<EOF
[NetDev]
Kind=vlan
Name=sub1.vl101

[VLAN]
Id=101
EOF
```

3. Restart systemd-networkd:
```
chmod 644 /etc/systemd/network/50-sub*
systemctl restart systemd-networkd
```

4. ip -d link show | awk '/^[0-9]+: /{iface=substr($2, 1, index($2, ":")-1)} /vlan protocol 802.1Q/{print iface, $5}'
sub1.vl101@sub1 101.  ---> create sub-interface sub1.vl101 under sub1, succeed

5. Now rename sub1 to sub, re-create its network config files for creating subinterface sub.vl101
 ```
ip link set dev sub1 down && ip link set dev sub1 name sub
rm /etc/systemd/network/50-sub*
```

6. Create corresponding network files

```
cat > /etc/systemd/network/50-sub-nc.network <<EOF
[Match]
MACAddress=00:50:56:b2:f1:03

[Network]
DHCP=no
IPv6AcceptRA=no
VLAN=sub.vl101
EOF
```

```
cat > /etc/systemd/network/50-sub.vl101-nc.netdev <<EOF
[NetDev]
Kind=vlan
Name=sub.vl101

[VLAN]
Id=101
EOF
```

7. Rename eth2 to sub1, create files for creating subinterface sub1.vl101:

`ip link set dev eth2 down && ip link set dev eth2 name sub1`

```
cat > /etc/systemd/network/50-sub1-nc.network <<EOF
[Match]
MACAddress=00:50:56:b2:99:96

[Network]
DHCP=no
IPv6AcceptRA=no
VLAN=sub1.vl101
EOF
```

```
cat > /etc/systemd/network/50-sub1.vl101-nc.netdev <<EOF
[NetDev]
Kind=vlan
Name=sub1.vl101

[VLAN]
Id=101
EOF
```

8. Restart networkd
```
chmod 644 /etc/systemd/network/50-sub*
systemctl restart systemd-networkd
```

9. Verify that corresponding vlan interfaces are created for each interface according to network files.
```
ip -d link show | awk '/^[0-9]+: /{iface=substr($2, 1, index($2, ":")-1)} /vlan protocol 802.1Q/{print iface, $5}'
```
sub1.vl101@sub 101 -------> Only `sub1.vl101@sub` is created and it is still hooked to eht1/sub1 which should have been hooked to sub.

**Comment by sshedi** [comment]
PS:
I also used,
```
[Match]
Name=<iface-name>
```
in network files but the behaviour remained same.

**Comment by yuwata** [comment]
networkd does not remove nor rename vlan interfaces. So, sub1.vl101 needs to be manually removed when the main interface sub1 is renamed to sub.
