### ISSUE TITLE
systemd-logind StopIdleSessionSec option does seem to conflict with any command that take longer time than specifed

### ISSUE THREAD

**Issue by Arima-Sempai** [systemd/systemd#33981]
### systemd version the issue has been seen with

239

### Used distribution

rocky8.10

### Linux kernel version used

kernel-5.10

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

the process should continue working because its crucial/and not running in background and the session is not idle

### Unexpected behaviour you saw

if a process(doesn't accept an input) takes a longer time than specified by the timeout, the whole session is terminated (regardless if the process produce an output)

### Steps to reproduce the problem

a simple way to reproduce, after adding StopIdleSessionSec option to logind configuration and restarting, do a simple while loop like this: 
while true; do date; sleep 1; done

**Comment by poettering** [comment]
the idle state must be reported to logind by your desktop environment. My educated guess is that your's doesn't. 

Also systemd 239 is *waaay* too old to be tracked here, and the issue submission form should really have made that clear.

**Comment by Arima-Sempai** [comment]
systemd 239 is the version on rocky 8.10, where i am encountering the issue, do u have any potential solutions i can use in my case

**Comment by poettering** [comment]
"rocky" is a distro afaik, not a desktop environment.

**Comment by Arima-Sempai** [comment]
so i am encountering this issue when using rocky on a vm, do u think that could be the reason?

**Comment by dtardon** [comment]
> so i am encountering this issue when using rocky on a vm, do u think that could be the reason?

No, it's not. It's exactly the same on Fedora 40 with current systemd master. The problem isn't in the observed behavior, but in your expectations. If `StopIdleSessionSec=` is set, `logind` stops the session--the _whole_ session--when the system is idle for that time or longer, but it's not `logind` that specifies what "idle" means. That's determined by the desktop env., or, in case of a console session, by the kernel. We're talking about _user_ sessions, hence the logical way is to check for any kind of _input_ from the user. That a command line tool writes swathes of output to the terminal or that a browser runs some JS that causes its window to blink periodically is completely irrelevant, as it doesn't come _from the user_.

**Comment by Arima-Sempai** [comment]
thanks everyone, this clears it for me
