### ISSUE TITLE
Autosuspend incorrecty enabled for USB keyboards

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#340]
After moving systemd 221 to Arch's stable repos (previously provided systemd v219), we are seeing reports that USB keyboards do not behave as expected. This seems to be caused by a power management change in commit 64713f92528e8443b7ff2ce3ec0394920a751fb1.

So far, problems have been reported for the following keyboard models:
- Ryos MK Pro: Backlight turing off after about 5 seconds of inactivity. [1]
- Kinesis Advantage: Stops working after a few seconds. [2]
- SteelSeries Apex: Turns off after a few seconds; needs 3-5 seconds to resume on key press. [3]

[1] https://bugs.archlinux.org/task/45427
[2] https://bbs.archlinux.org/viewtopic.php?id=198972
[3] https://bbs.archlinux.org/viewtopic.php?id=198999

**Comment by martinpitt** [comment]
Thanks for digging this out! I thought my Kinesis keyboard got broken and ordered a new one, only to find out that the new one doesn't work as well. I'm not sure whether we should start collecting a blacklist of keyboards which don't work with USB autosuspend, or rather a whitelist? Or revert this wholesale?

**Comment by foutrelis** [comment]
Perhaps @mjg59 can suggest what the proper course of action might be (as the author of commit 64713f92528e8443b7ff2ce3ec0394920a751fb1).

**Comment by wuxb45** [comment]
@foutrelis The problem of Kinesis keyboards is fixed after reverting the commit. Thanks.

**Comment by gregkh** [comment]
We can not do autosuspend by default for keyboards, we have to have a whitelist.  That's what another major operating system does because keyboards are broken in this aspect.

**Comment by kaysievers** [comment]
Let's remove all the rules. They caused more problems than they ever solved. Things should be sorted out in the kernel, or if impossible, someone should start a project maintaining such a whitelist. It is not udev's job.

  https://github.com/systemd/systemd/pull/353

**Comment by grossws** [comment]
Have same problem on Kinesis Advantage and Das Keyboard Professional keyboards on ArchLinux after upgrading systemd parts from 219 to 221.

**Comment by kaysievers** [comment]
Merged: https://github.com/systemd/systemd/pull/353

**Comment by dillongreen** [comment]
My Logitech diNovo Edge stopped working as well, worked at bootup, then after 4 seconds of inactivity it stopped recognizing any keystrokes whatsoever, only swinging back from the dead after holding down a key for about 10 seconds and then spitting a few lines of that character on the screen... same again after a few seconds of inactivity...

After upgrading udev on my Debian box to `221-1` all is back to normal again. Debian bug report to be found here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789723
