### ISSUE TITLE
Setting Nice and CPUSchedulingPolicy in a service ignores the niceness

### ISSUE THREAD

**Issue by popsUlfr** [systemd/systemd#34006]
### systemd version the issue has been seen with

256.4

### Used distribution

Arch Linux

### Linux kernel version used

6.10.4-zen2-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

Hello,

I noticed that putting the `CPUSchedulingPolicy` directive in a service seems to not apply the `Nice` directive.

`/etc/systemd/system/mytest.service`:
```ini
[Unit]
Description=mytest

[Service]
ExecStart=bash -c 'while true ; do sleep 5 ; done'
Nice=19
CPUSchedulingPolicy=batch
```

```sh
sudo systemctl daemon-reload
sudo systemctl start mytest.service
schedtool $(systemctl show --property MainPID --value mytest.service)
```
```
PID 435544: PRIO   0, POLICY B: SCHED_BATCH   , NICE   0, AFFINITY 0xffffff
```

I expected to have a nice value of 19.

If I remove the `CPUSchedulingPolicy` directive, the niceness is applied:

```sh
schedtool $(systemctl show --property MainPID --value mytest.service)
```
```
PID 437187: PRIO   0, POLICY N: SCHED_NORMAL  , NICE  19, AFFINITY 0xffffff
```

### Unexpected behaviour you saw

Adding the `CPUSchedulingPolicy` directive to a service file seems to nullify the `Nice` directive:

`/etc/systemd/system/mytest.service`:
```ini
[Unit]
Description=mytest

[Service]
ExecStart=bash -c 'while true ; do sleep 5 ; done'
Nice=19
CPUSchedulingPolicy=batch
```

```sh
sudo systemctl daemon-reload
sudo systemctl start mytest.service
schedtool $(systemctl show --property MainPID --value mytest.service)
```
```
PID 435544: PRIO   0, POLICY B: SCHED_BATCH   , NICE   0, AFFINITY 0xffffff
```

### Steps to reproduce the problem

1. Write or add to a service file the `Nice` and `CPUSchedulingPolicy` directives.
2. Start the service.
3. Notice that the niceness is not applied.

**Comment by YHNdnzj** [comment]
Should be fixed by https://github.com/systemd/systemd/pull/33968.

**Comment by popsUlfr** [comment]
Ah, thank you and sorry that I missed the pull request.
