### ISSUE TITLE
[RFE]GUI firstboot and useradd user

### ISSUE THREAD

**Issue by xiangzhai** [systemd/systemd#3401]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ArchLinux
### In case of bug report: Expected behaviour you didn't see

> systemd-firstboot is very cool! just like Mac OS X's Firstboot to setup locale, timezone (but without useradd user) after installed OS. it is helpful for genernal (or newbie) Linux user if provided GUI and simple user management. my colleague developed **_another**_ firstboot in Qt:

![firstboot1](https://cloud.githubusercontent.com/assets/851100/15669107/2a6a25ae-2751-11e6-8fcc-81bd5e29eb84.png)

![firstboot2](https://cloud.githubusercontent.com/assets/851100/15669115/33fb4d64-2751-11e6-94f7-0450a91419fd.png)

![firstboot3](https://cloud.githubusercontent.com/assets/851100/15669118/3df175fa-2751-11e6-9908-a5cb4a0d2f80.png)

We really really really want to join systemd-firstboot development, just like [kscreen-osd](https://github.com/KDE/kscreen/tree/osd) with Redhat engineer, please give us some advice, thanks a lot!

Regards,
Leslie Zhai

**Comment by shibumi** [comment]
I don't think that systemd should include a GUI for systemd-firstboot. But please tell us more about the "useradd for non-root user".

But you can ship an own package that provide a GUI for systemd-firstboot.

**Comment by xiangzhai** [comment]
sorry for my poor English ;-P useradd user, what I mean, is simple user management, for example, via [AccountsService](https://www.freedesktop.org/wiki/Software/AccountsService/)

yes, my colleague developed the same function stuff: [firstboot-qt](https://github.com/isoft-linux/firstboot-qt) for Linux newbie user, start own firstboot service `After=systemd-user-sessions.service plymouth-quit.service` to run the Qt frontend under X11 with [plymouth smooth transition](https://wiki.archlinux.org/index.php/plymouth#Smooth_transition)

it is able to (duplicated with systemd-firstboot) configure locale, keyboard layout, timezone, hostname, root passwd, simple user management (but systemd not provided): useradd user and whether or not autostart.

we just do not want to do the duplicate stuff if systemd provided such very cool feature ;-)

**Comment by poettering** [comment]
I think writing such a tool is great, but I am not convinced this should take place in systemd itself. That's a great project to do outside of systemd. Of course, please make sure of the systemd-firstboot code as you like it's free software after all, to build a graphical replacement.

Sorry, but I hop this makes sense!

**Comment by xiangzhai** [comment]
Thanks for your reply indeed ;-)
