### ISSUE TITLE
error when running systemctl suspend on sxhkd

### ISSUE THREAD

**Issue by nitrogenxx** [systemd/systemd#34016]
### systemd version the issue has been seen with

256.1-1

### Used distribution

archlinux

### Linux kernel version used

6.6.35-2-lts

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

when I'm using the command
`$systemctl suspend` on the terminal it execute properly without any error as it should be..

but

when I'm putting this command `$systemctl suspend` in the `sxhkdrc` .. example :
`~/.config/sxhkd/sxhkdrc`
```
  super + F3
  systemctl suspend
```

and running `sxhkd` on terminal .. example :
`$sxhkd -c ~/.config/sxhkd/sxhkdrc `
then press the key `super + F3`

------------- or/and ---------------

when I'm running this command `$setsid systemctl suspend` directly on terminal 

then I'm having this error on the terminal
`Error creating textual authentication agent: Error opening current controlling terminal for the process (\/dev/tty'): No such device or address (polkit-error-quark, 0)`

however after the error my system still goes into sleep mode as it should be.

why I'm having this error when running this `$systemctl suspend` command using `sxhkd` and why I'm not having error when running this command directly on terminal ??
and
why im having same error message when running `$setsid systemctl suspend` command on terminal  ??
how to resolve the issue ?

I would greatly appreciate your help or any insight possible. pink heart emoji

### Unexpected behaviour you saw

already mentioned in above message

### Steps to reproduce the problem

already mentioned in above message

**Comment by yuwata** [comment]
That should be come from when trying to invoke polkit agent. Try `--no-ask-password` option.

**Comment by nitrogenxx** [comment]
> That should be come from when trying to invoke polkit agent. Try `--no-ask-password` option.

uhh. that is interesting.. that seems to work correctly.. thanks !!
but its triggering lots of questions into my mind

1. what about security..  if `--no-ask-password` is available then why systemctl ask for password.. it can be easily bypass security with this flag.. I'm curious about it's functionality and use case 

2. why I'm having this error when running this `$systemctl suspend` command using `sxhkd` but not having that error when running this command directly on terminal ??

3. same goes with this command `$setsid systemctl suspend` when running directly on terminal then having same error as well ??



![zza](https://github.com/user-attachments/assets/c5e32efe-c57d-49d4-bb2b-8e49660bb154)

**Comment by YHNdnzj** [comment]
Sorry, but this is not a `systemctl` nor a systemd issue. Your GUI environment lacks a polkit agent, hence `systemctl` would try to spawn a tty agent, which certainly can't work if there is no tty to begin with. Please refer to https://wiki.archlinux.org/title/Polkit#Authentication_agents for details.

**Comment by YHNdnzj** [comment]
> what about security.. if --no-ask-password is available then why systemctl ask for password.. it can be easily bypass security with this flag.. I'm curious about it's functionality and use case

`systemctl` would always try to open polkit agent, but not all actions actually need it. `systemctl suspend` requires no privilege for active local sessions.
