### ISSUE TITLE
Add a PublicKeyFile option to WireGuardPeer sections in networkd .netdev files

### ISSUE THREAD

**Issue by Ambr051us** [systemd/systemd#34012]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

Having to copy public keys into .netdev files for wireguard peers is tedious, and requires comments for maintaining readability

### Describe the solution you'd like

Add a PublicKeyFile option to the WireGuardPeer section, just like the PrivateKeyFile option is already there in the WireGuard section (and the PreSharedKeyFile option in the WireGuardPeer section as well). This would allow .netdev files to be more readable, arguably more elegant (all keys referenced by a file path, rather than having secrets as files but public keys entered raw), and require very little effort, considering that reading keys from files is already supported for other types of WireGuard keys.

### Describe alternatives you've considered

Annotating configs with comments technically solves the readability issue, but it's still tedious. Generating .netdev files with an external script is also an option, but that would go against the "simple and elegant" config that my recommendation would enable.

**Comment by YHNdnzj** [comment]
Note that `PublicKey=` already supports the same format for reading from credentials as `PrivateKey=`, using the `@` prefix.

**Comment by yuwata** [comment]
-> #34013.

**Comment by Ambr051us** [comment]
@YHNdnzj I'm aware of the credential store, but as a hobbyist I'd still prefer plain files
@yuwata Wow, that's what I call a quick response, thanks :D
