### ISSUE TITLE
Reconsider incompatible IP forwarding changes in v256, affects systemd-nspawn

### ISSUE THREAD

**Issue by sfan5** [systemd/systemd#34010]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

the problem: `systemd-nspawn --network-veth` no longer provides working internet access to containers (#33004)
This was documented in #33018 and considered solved.

I am a bit puzzled by this decision.
systemd goes to a bunch of effort to provide an out-of-the box configuration for networking inside/outside nspawn containers, complete with automatically configured NAT rules. And now it's okay that users are left with a setup that looks like it should work but doesn't?
Not to mention that the UX of this is **awful**. It takes some careful investigation of the relevant `.network` file as well as reading `systemd.network(5)` to discover the intended fix.

Worth noting that the `NEWS` entry talks about routing configuration and such with no mention of nspawn.

### Describe the solution you'd like

I don't see an obvious solution besides reverting #31423 (functionally or literally).

ideas:
* document in `systemd-nspawn(1)` that `--network-veth` is **broken by default** and requires further configuration
* remove `IPMasquerade` from `80-container-ve.network` to make it obvious that manual configuration is required

### Describe alternatives you've considered

Ignore the fact that this causes user frustration.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by yuwata** [comment]
-> #34014.

**Comment by sfan5** [comment]
Much appreciated, thanks.
