### ISSUE TITLE
Update Slovenian (sl) translation from translate.fedoraproject.org

### ISSUE THREAD

**Issue by filmsi** [systemd/systemd#34027]
### Describe the solution you'd like

Slovenian translation has been updated and completed by the Slovenian GNOME l10n Team.
Please merge the updated po file from translate.fedoraproject.org:
https://translate.fedoraproject.org/projects/fprintd/fprintd/sl/
Thank you.

**Comment by yuwata** [comment]
fprintd is not a project of systemd.

**Comment by filmsi** [comment]
Sorry, the link was wrong, as I handled several finished translations.
Please reopen, here is the proper link as a proof:
https://translate.fedoraproject.org/projects/systemd/main/sl/

Else I will create a new issue.

**Comment by filmsi** [comment]
OK, I will now create a new issue and I will gladly add you to it.

**Comment by filmsi** [comment]
Here is the new issue:
https://github.com/systemd/systemd/issues/34028
