### ISSUE TITLE
systemd-backlight failed due to hardware is not ready

### ISSUE THREAD

**Issue by Kxuan** [systemd/systemd#34031]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu Core 22.04

### Linux kernel version used

5.15.0-1033-mtk

### CPU architectures issue was seen on

aarch64

### Component

other

### Expected behaviour you didn't see

systemd-backlight started and successfully restored the value of brightness of backlight device.

### Unexpected behaviour you saw

systemd-backlight failed:
```
Aug 19 03:55:00 ubuntu systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:1c008000.dsi0.0...
Aug 19 03:55:00 ubuntu systemd-backlight[1811]: 1c008000.dsi0.0: Failed to write system 'brightness' attribute: Invalid argument
Aug 19 03:55:00 ubuntu systemd[1]: systemd-backlight@backlight:1c008000.dsi0.0.service: Main process exited, code=exited, status=1/FAILURE
Aug 19 03:55:00 ubuntu systemd[1]: systemd-backlight@backlight:1c008000.dsi0.0.service: Failed with result 'exit-code'.
Aug 19 03:55:00 ubuntu systemd[1]: Failed to start Load/Save Screen Backlight Brightness of backlight:1c008000.dsi0.0.
```

### Steps to reproduce the problem

1. boot linux kernel
2. systemd-backlight@.service started during the kernel modules loading.
   More specifically, the kernel module `panel_startek_kd070fhfid015` is loaded before kernel module `mediatek_drm_hdmi`, and service `systemd-backlight@backlight:1c008000.dsi0.0.service` is started before kernel module `mediatek_drm_hdmi` is loaded.

After some investigation, this is what I learned was the cause of the problem.

1. Both kernel module `panel_startek_kd070fhfid015` and `mediatek_drm_hdmi` are loaded because of device-tree. They can complete their initialization work in any order.
2. The backlight device `backlight:1c008000.dsi0.0` is registered by kernel module `panel_startek_kd070fhfid015`.
   But `panel_startek_kd070fhfid015` **indirectly** requires kernel module `mediatek_drm_hdmi` to change the brightness. It will return `-EINVAL` before `mediatek_drm_hdmi` finish its initialization when userspace try to write to `brightness` .
3. Due to udev rules, `systemd-backlight@backlight:$name.service` will be started right after backlight device been registered.
  https://github.com/systemd/systemd/blob/4cf7a676af9a79ff418227d8ff488dfca6f243ab/rules.d/99-systemd.rules.in#L78

So there may be a problem, that is, systemd-backlight tries to change the brightness before the kernel module `mediatek_drm_hdmi` finish its initialization. This will cause the systemd-backlight service to fail.

I wonder if systemd team could add a retry in [systemd-backlight@.service](https://github.com/systemd/systemd/blob/4cf7a676af9a79ff418227d8ff488dfca6f243ab/units/systemd-backlight%40.service.in) to solve this problem.
```
[Service]
Restart=on-failure
RestartSec=1
```

**Comment by yuwata** [comment]
> 2\. The backlight device `backlight:1c008000.dsi0.0` is registered by kernel module `panel_startek_kd070fhfid015`.
>         But `panel_startek_kd070fhfid015` **indirectly** requires kernel module `mediatek_drm_hdmi` to change the brightness.

That sounds kernel driver issue. Could you report the issue to the driver maintainer?

**Comment by poettering** [comment]
Yeah, this is a driver issue. Also 249 is ancient, and we tweaked the backlight tool a bit since then.

**Comment by tommyyl-chen** [comment]
The 1c008000.dsi0.0.service is created during panel probe, however, it is not available for control until the panel is prepared.
That is, there is a time gap between panel probe and panel prepare. If systemd attempts to control the backlight during the gap, failing is inevitable.
 
The time gap length is somehow affected by the entire display probe, including the mtk hdmi probing. After the display probe, the panel prepares.
 
As a result, since there is a time gap between panel probe and panel prepare, causing backlight control to fail, we would suggest systemd to retry on failure.

**Comment by yuwata** [comment]
Please try to create a drop-in config for the unit that adds After= and Wants= with the module.
