### ISSUE TITLE
Command for convenient installation of unit files `systemctl install unit.thing`

### ISSUE THREAD

**Issue by gerelef** [systemd/systemd#34035]
### Component

systemctl

### Is your feature request related to a problem? Please describe

Regularly, when poking around w/ different services, a unit file will have to be installed before enabling & starting the service, either as user or as system, in the appropriate path for each one. 

Afterwards, `daemon-reload` will have to run, in order for the new unit file to be detected.
This is a semi-error-prone process, and this FR is purely convenience.

### Describe the solution you'd like

I propose the introduction of two new commands:
- systemctl install [--user] `./path/to/my-unit@.thing` -> this will automatically move `my-unit` file to the standard system (or --user) path & `daemon-reload` so that the new unit file is recognized.

There is no need for an equivalent uninstall command; if an administrator needs a service to not run, they can just stop, disable & mask the `thing`.

This proposal aligns with the purpose of convenience commands like `systemctl edit unit.thing`.

### Describe alternatives you've considered

Custom wrapper scripts that obviously go against the standard CLI, relying on an external script to automate this process via some sort of `./systemctl-install.sh`. Not the ideal solution.

**Comment by YHNdnzj** [comment]
> Regularly, when poking around w/ different services, a unit file will have to be installed before enabling & starting the service

Well, that's not really the case. `systemctl enable` would happily accept a path to a unit file, and would create symlinks under systemd unit search path and reload manager.

**Comment by gerelef** [comment]
> Well, that's not really the case. `systemctl enable` would happily accept a path to a unit file, and would create symlinks under systemd unit search path and reload manager.

Good point, thanks! I was unaware of that actually; that is, indeed, pretty convenient. 
May I ask then, the original purpose of `~/.config/systemd/user/` (and the equivalent for system) services?

**Comment by YHNdnzj** [comment]
> May I ask then, the original purpose of `~/.config/systemd/user/` (and the equivalent for system) services?

You can still directly place units in there, and that's where the override units installed by `systemctl edit --full` reside too.

**Comment by gerelef** [comment]
Alright, thanks!
