### ISSUE TITLE
fstab-generator incorrectly handles "root=gpt-auto" which actually belongs to gpt-auto-generator

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#3404]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian Testing
### In case of bug report: Expected behaviour you didn't see

> N/A
### In case of bug report: Unexpected behaviour you saw

> Thanks to some recent patches to dracut ([^0](https://github.com/dracutdevs/dracut/commit/016613c774baf3d30c6425a65ead05d8b55d6279) and [^1](https://github.com/dracutdevs/dracut/commit/d4efc0aeeecc470d9a267b7f3c130f472488905c)), it is now actually possible to boot without a 
> `root=` argument. However, booting with the special value `root=gpt-auto` [^2](https://github.com/systemd/systemd/blob/v230/src/gpt-auto-generator/gpt-auto-generator.c#L928) doesn't work
> because this assignment is incorrectly interpreted by fstab-generator, creating a mount unit under
> `/run/systemd/generator`, thereby overriding the correct mount unit created by gpt-auto-generator
> under `/run/systemd/generator.late`. You can see more details here:
> 
> ![Screenshot](https://cloud.githubusercontent.com/assets/8996356/15672387/9f71b25c-2730-11e6-85cb-fba36d677240.png)
> 
> The problem seems to be, that fstab-generator considers all `root=foo` assignments as
> meant for it [^3](https://github.com/systemd/systemd/blob/v230/src/fstab-generator/fstab-generator.c#L603), which is incorrect. A solution might be to modify the mentioned check like this:
> `} else if (streq(key, "root") && value && !streq(value, "gpt-auto")) {`
### In case of bug report: Steps to reproduce the problem

> 1. Set up a system with UEFI and proper GPT partition types (required for gpt-auto-generator to
>    work)
> 2. Get the latest version of dracut from git(hub)
> 3. Verify that booting without a `root=` argument works
> 4. Try booting with `root=gpt-auto`

**Comment by poettering** [comment]
Yeah, we should fix that. That said, it should work if you drop root= entirely from the kernel cmdline, no?

**Comment by AlexanderKurtz** [comment]
Yes, without any `root=` argument, booting works with dracut from git.
