### ISSUE TITLE
Fail to parse DNS server added by router advertisement

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#3405]
Hi,

On my network, the DNS are advertised by RA and the the following like is added in /etc/resolv.conf by networkmanager:

nameserver fe80::c03f:eff:fe7d:3002%wlp3s0

But apparently resolved is not happy with this:

> systemd-resolved[31763]: Failed to parse DNS server address 'fe80::c03f:eff:fe7d:3002%wlp3s0', ignoring.

**Comment by wlhlm** [comment]
Duplicate of #3359.
