### ISSUE TITLE
systemd-bootchart: IO and CPU utilization graph have no data

### ISSUE THREAD

**Issue by gmacario** [systemd/systemd#341]
Release v220 of systemd-bootchart does not properly display contents inside the following panels
- IO utilization  - read
- IO utilization - write
- CPU[overall] utilization
- CPU[overall] wait

v219 worked fine.

**Comment by gmacario** [comment]
I did some "git bisect" and if I am not mistaken it looks like the bug was introduced by commit 1f2ecb0393bf071fcd476300e0b3f94726b01b15 by @zonque:

> 1f2ecb0 bootchart: kill a bunch of global variables

The previous commit affecting src/bootchart

> f917813 bootchart: clean up sysfd and proc handling

seems to behave correctly.

**Comment by gmacario** [comment]
I added some debugging messages inside `src/bootchart/svg.c`, function `static void svg_cpu_bar`, and it looks like that the loop inside `LIST_FOREACH_BEFORE(link, sampledata, head)` is never executed.

**Comment by zonque** [comment]
Ops, sorry about that. I did a number of basic tests for obvious regressions back then, but didn't spot anything. But admittedly, I'm not a heavy user of this tool myself.

Could you spot what exactly is needed to fix the code and bring the original behavior back? Happy to take a patch. I'll also look for a solution myself, but that might not be immediate.

**Comment by gmacario** [comment]
> Could you spot what exactly is needed to fix the code and bring the original behavior back?

I did some inspection of https://github.com/systemd/systemd/commit/1f2ecb0393bf071fcd476300e0b3f94726b01b15 but still could not find the exact root cause.
I suspect some side effect due to replacing global variables with local vars.

> Happy to take a patch

Will be happy to provide one, too :-)

Unfortunately as the project I am currently working on is still on a pre-v220 systemd, at the moment the bug is not (yet) hunting us so I am not sure when I will have some time for this as well.

**Comment by gmacario** [comment]
Hello @zonque,

FYI: I just submitted PR https://github.com/systemd/systemd/pull/385 with a quick fix to issue https://github.com/systemd/systemd/issues/341.

I cannot understand why Semaphore build fails, though...

**Comment by zonque** [comment]
Thanks! Such CI build failures are likely related to force-pushed branches. Did you do that?
Semaphore should be able to cope with that, but we've seen such effects before.

**Comment by gmacario** [comment]
Fix via commit ae87a4a9291e7277b9fe08c97345166118f98623
