### ISSUE TITLE
Implement resolvconf -p

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#34112]
### Component

resolvectl

### Is your feature request related to a problem? Please describe

resolvectl has a compat interface for resolvconf, the de-facto standard for dns configuration management before sd-resolved. The following excerpts from [resolvconf.8](https://man.archlinux.org/man/resolvconf.8) describe its notion of "private" interfaces:

> resolvconf can mark an interfaces resolv.conf as private.  This means that the name servers listed in that resolv.conf are only used for queries against the domain/search listed in the same file.  This only works when a  local  resolver other than libc is installed.  See resolvconf.conf(5) for how to configure resolvconf to use a local name server and how to remove the private marking.
> [...]
>  **-p** Marks the interface resolv.conf as private.

So far, **-p** has been omitted from the compat implementation of resolvconf in sd-resolved, but it seems to me it could be beneficially mapped to the sd-resolved concept of a default route.

### Describe the solution you'd like

Implement resolvconf -p such that it marks the interface as DefaultRoute=no.

### Describe alternatives you've considered

Use the native resolvectl interface.

### The systemd version you checked that didn't have the feature you are asking for

256.5

**Comment by yuwata** [comment]
FYI, openresolv controlls with `-p` whether acquired DNS servers will be used or not:
https://github.com/NetworkConfiguration/openresolv/blob/dba13c383986487abd393d3f3f126938df52f52e/resolvconf.in#L237-L239

**Comment by yuwata** [comment]
-> #34114.
