### ISSUE TITLE
namespace coredump stacktrace generator needs fixes.

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#34130]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

tracker bug for the post-merge issues found in #33675

**Comment by bluca** [comment]
I will make sure to click reopen myself so that it doesn't

**Comment by poettering** [comment]
the pidfd protocol thing touches protocol, should be included in rc

**Comment by bluca** [comment]
> the pidfd protocol thing touches protocol, should be included in rc

@msekletar are you able to work on this?

**Comment by msekletar** [comment]
> @msekletar are you able to work on this?

I will look into it now.

**Comment by bluca** [comment]
Thanks!

**Comment by msekletar** [comment]
> I am looking into it already, I found more to fix.

OK, I will stop working on it then.
