### ISSUE TITLE
Here is a fix for ALPS DualPoint TouchPad jitter (on Dell Latitude E7440)

### ISSUE THREAD

**Issue by Actarus25** [systemd/systemd#34133]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 24.04 LTS

### Linux kernel version used

6.8.0-41-generic

### CPU architectures issue was seen on

x86_64

### Component

hardware database files

### Expected behaviour you didn't see

Touchpad scrolling is normal and stable. 
Pointer is not jittery. 

### Unexpected behaviour you saw

Touchpad scrolling is jumping and jittery. It's sometimes hard to read a web page. 
Pointer is sometimes jittery. 

### Steps to reproduce the problem

On a laptop Dell Latitude E7440. 
Fresh install of Ubuntu 24.04 (Wayland). 
Read a web page and scroll it with the touchpad. 
Scrolling is jittery and jumping, it's sometimes hard to read a webage. 

Following https://wayland.freedesktop.org/libinput/doc/latest/touchpad-jitter.html
It is fixed using the command: 
sudo libinput measure fuzz --fuzz=28
Which says: 
"Your hwdb override file is in /etc/udev/hwdb.d/99-touchpad-fuzz-override.hwdb"
"Then submit a pull request for this hwdb entry to systemd at http://github.com/systemd/systemd"

So then: 
cat /etc/udev/hwdb.d/99-touchpad-fuzz-override.hwdb
Gives: 
# File generated by libinput measure fuzz

# DellInc. AlpsPS/2 ALPS DualPoint TouchPad
evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:*:svnDellInc.*:pnLatitudeE7440*:
 EVDEV_ABS_00=:::28
 EVDEV_ABS_01=:::28
 EVDEV_ABS_35=:::28
 EVDEV_ABS_36=:::28

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Other informations (do not hesitate to ask for more): 

baptiste@baptiste-Latitude-E7440:~$ lsb_release -d
No LSB modules are available.
Description:	Ubuntu 24.04 LTS

uname -r
6.8.0-41-generic

baptiste@baptiste-Latitude-E7440:~$ echo $XDG_SESSION_TYPE
wayland

baptiste@baptiste-Latitude-E7440:~$ libinput --version
1.25.0

baptiste@baptiste-Latitude-E7440:~$ systemd --version
systemd 255 (255.4-1ubuntu8.2)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

baptiste@baptiste-Latitude-E7440:~$ cat /sys/class/dmi/id/modalias
dmi:bvnDellInc.:bvrA28:bd06/13/2019:br65.28:svnDellInc.:pnLatitudeE7440:pvr00:rvnDellInc.:rn0HCH70:rvr:cvnDellInc.:ct9:cvr:sku05CB:

libinput quirks list /dev/input/event6
ModelALPSSerialTouchpad=1
```

**Comment by yuwata** [comment]
Please submit the change as a PR.

**Comment by Actarus25** [comment]
Without the markdown formating, 
cat /etc/udev/hwdb.d/99-touchpad-fuzz-override.hwdb
looks like:  
 File generated by libinput measure fuzz

 DellInc. AlpsPS/2 ALPS DualPoint TouchPad
evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:*:svnDellInc.*:pnLatitudeE7440*:
 EVDEV_ABS_00=:::28
 EVDEV_ABS_01=:::28
 EVDEV_ABS_35=:::28
 EVDEV_ABS_36=:::28

**Comment by Actarus25** [comment]
Thanks for your comment. I tried to submit a Pull Request. Sorry, but it seems quiet complicated to me. 
I don't code myself, except a few simple bash scripts... 
I searched and no Pull Request is related to this quirk for now. 
Do I need to install git on my machine? (It's a laptop I use for work). 
What file do I need to modify? Something like hwdb.something? 
I would like to contribute but I don't really know the way to do this. I could try if it is the only way.

**Comment by yuwata** [comment]
Not familiar, but nowadays you can edit files through GitHub web interface, maybe codespace. See e.g. https://docs.github.com/en/codespaces/overview
Try to fork the main systemd branch and open hwdb.d/60-evdev.hwdb with codespace and add the entry you mentioned in the above.
If it does not work, of course you can still use traditional way, i.e. install git, clone git repository, change the file, commit, and push.

**Comment by yuwata** [comment]
I opened #34181.

**Comment by Actarus25** [comment]
Thanks for the help, Yuwata. I was busy these days and about to try what you said. I see that I would not have done as good as you guys did. Thanks everyone to make things work. 
Apart from that, I was wondering if the fix should apply only for this model of laptop, for Dell laptops or for every laptop model using an "AlpsPS/2 Alps Dualpoint Touchpad"

**Comment by yuwata** [comment]
> Thanks for the help, Yuwata. I was busy these days and about to try what you said. I see that I would not have done as good as you guys did. Thanks everyone to make things work.

👍

> Apart from that, I was wondering if the fix should apply only for this model of laptop, for Dell laptops or for every laptop model using an "AlpsPS/2 Alps Dualpoint Touchpad"

Model specific entry should be safe, unless we know the same setting can be really applied to all models.

**Comment by AmanullahShah** [comment]
Thanks, this worked perfectly on fedora on dell m4800 with same touchpad with 40 value, cursor was jumping around a lot not usable at all.
