### ISSUE TITLE
RFE: systemd.exec: extends permissions parameters for new use cases

### ISSUE THREAD

**Issue by alban** [systemd/systemd#3414]
This issue is capturing the messages from [the mailing list](https://lists.freedesktop.org/archives/systemd-devel/2016-May/036777.html).
#### Context

[systemd.service](https://www.freedesktop.org/software/systemd/man/systemd.service.html) can execute commands through:
- [ExecStart=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=)
- [ExecStartPre=, ExecStartPost=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=)
- [ExecStop=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStop=)
- [ExecStopPost=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStopPost=)
- ExecFail (soon! see https://github.com/systemd/systemd/issues/3184 and https://github.com/coreos/rkt/issues/2506)

The different commands can be executed in different environments (see [systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html)):
- [User=, Group=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#User=)
- [RootDirectory=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RootDirectory=)
- [RootDirectoryStartOnly=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#RootDirectoryStartOnly=)
- etc.
#### Limitations of the current parameters

Thoses options to change the execution environment are not really granular: normally, all commands run with the same user/group and in the same chroot. There is [PermissionsStartOnly](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PermissionsStartOnly=) and [RootDirectoryStartOnly](https://www.freedesktop.org/software/systemd/man/systemd.service.html#RootDirectoryStartOnly=) but it is not granular enough for the following use cases:
#### Use case: rkt fetch as unprivileged user

@philips [comments](https://lists.freedesktop.org/archives/systemd-devel/2016-May/036777.html): 

> The rkt container engine wants to run with different permissions pre-start
> and start. In pre-start it needs to fetch/download the container image
> which is an unprivileged operation. In start it needs admin level
> permissions to start the container stage1 (e.g. systemd-nspawn) and mount
> the root overlayfs.
> 
> One way of accomplishing this is:
> 
> ExecStartPre=/usr/bin/su rktfetchuser -c /usr/bin/rkt fetch
> quay.io/coreos/etcd blah blah
> ExecStart=/usr/bin/rkt run $(COREOS_VERSIONS_ETCD_FULL) blah blah
#### Use case: rkt's stage1: ExecStartPre and ExecStartPost with different uids

rkt's stage1 would need more flexible rights: we would need to specify uid/gids for ExecStartPre and ExecStartPost:

https://github.com/appc/spec/issues/58
https://github.com/coreos/rkt/issues/1495
#### Use case: ExecFail (aka diagexec for rkt)

The future option "ExecFail" (#3184) would need to run as root and without being chrooted at all.

https://github.com/systemd/systemd/issues/3184
https://github.com/coreos/rkt/issues/2506

/cc @davidstrauss @poettering @philips @n0rad

**Comment by poettering** [comment]
So, if the executoin context varies widely then I'd always say: use two differnt unit files. That said, I think permitting per-Exec line to disable/enable the permissions stuff would make sense. Specifically I think we could add a new special prefix char to ExecFoo= lines, which have the effect of running something with full privileges. For example, we could use `!` for that. Example:

```
[Service]
ExecStartPre=/bin/foo
ExecStart=!/bin/bar
User=piep
```

That would then have the effect that /bin/foo is run as user `piep`, but /bin/bar is run with full privileges. `PermissionsStartOnly=` would then become essentially redundant.

This would mean we'd have three "magic" characters:
- `!` → run with full privileges
- `-` → ignore failure
- `@` → allow argv[0] specification

Not sure if this would be sufficient for your rkt usecase?

**Comment by alban** [comment]
@poettering It sounds good in general.

To be clear what "full privileges" means, the magic character `!` would run the command as if the following options were set:
- `User=root`
- `Group=root`
- `SupplementaryGroups=`

But no other changes in `RootDirectory=` or `ReadOnlyDirectories=` or similar, right?  I am not sure whether `SecureBits=` or `SystemCallFilter=` should be considered in `!`.

For the "rkt fetch as unprivileged user" use case, that would be:

```
ExecStartPre=/usr/bin/rkt fetch image
ExecStart=!/usr/bin/rkt run image
User=rktfetchuser
Group=rkt
```

That would not help with the "ExecStartPre and ExecStartPost with different uids" use case, but for this use case, we are writing the .service files programmatically, so forcing rkt to write two different unit files would not impact the user experience... it will be more complex code in rkt though.

And for the "ExecFail (aka diagexec for rkt)" use case... could we have a forth magic character:
- `^` run without chrooting in the [RootDirectory=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RootDirectory=), and without applying options like `ReadOnlyDirectories=`, `ProtectSystem=` or `MountFlags=`.

Then, we would write:

```
RootDirectory=/opt/stage2/nginx
ExecStart=/bin/nginx
ExecFail=/bin/diagexec --root=/opt/stage2/nginx/ --bin=/opt/stage2/nginx/bin/nginx
MountFlags=slave
```

Of course, `^` would not need to be in the same PR as `!`. I just want to check if we agree on the logic.

**Comment by poettering** [comment]
I think the "!" character should cover all security related settings, including caps and syscall filters and stuff. And yes, adding "^" or so, to cover the chroot case makes sense too.

**Comment by poettering** [comment]
I figure this may be closed now since #3493 has been merged.

**Comment by mbiebl** [comment]
I know I'm a bit late with my feedback, but I'd like to bring it up anyways, since we haven't made a release yet with that feature.

I find it a bit confusing that the ! character means different things int different contexts.
We already use it for Condition to negate the checks. 
Personally I would prefer if we used a different symbol then ! to mark Exec\* lines with elevated privileges. 
One suggestion would be +, which would somehow reflect the idea of additional privileges better I think.

**Comment by poettering** [comment]
@mbiebl see #3797.
