### ISSUE TITLE
error with "users"

### ISSUE THREAD

**Issue by zef126** [systemd/systemd#34170]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.2.1-PRoot-Distro

### CPU architectures issue was seen on

aarch64

### Expected behaviour you didn't see

No errors

### Unexpected behaviour you saw

The errors on 
![IMG_20240829_124511](https://github.com/user-attachments/assets/693c5638-c017-42de-a919-dbefcc388762)
the image!

### Steps to reproduce the problem

Install Ubuntu on tremux with proot-distro
Install systemd
(Try to update)
See error

**Comment by poettering** [comment]
Looks like a distro issue. They seem to install files owned by "journald" user, before creating that user.

That's not an upstream systemd issue. contact your distro instead.

**Comment by zef126** [comment]
Okay, I'm sorry!
