### ISSUE TITLE
systemd-sysv-generator is setting an unconfigurable 5min timeout to my script

### ISSUE THREAD

**Issue by Harridrone** [systemd/systemd#34178]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.15.0-119-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysv-generator

### Expected behaviour you didn't see

My init script should have an unlimited timeout value  

### Unexpected behaviour you saw

My init script was given a timeout value of 5min after being converted by the sysv-generator causing it to fail when my script took more than 5 minutes to launch. 

When I [looked into the code](https://github.com/systemd/systemd/blame/main/src/sysv-generator/sysv-generator.c#L165) it appears as if this 5min timeout is "intentional", but it's contradictory to what was discussed in [this issue]( https://github.com/systemd/systemd/issues/3398)

### Steps to reproduce the problem

Create an init script which requires more than 5 minutes to start, attempt to start the service

**Comment by yuwata** [comment]
The behavior is since 95ed3294c632f5606327149f10cef1eb34422862 (v214), and moreover, sysv-generator is deprecated, and will be removed. I do not think we should restore the ancient timeout behavior.
Please create a native .service unit with suitable timeout value.
Closing.
