### ISSUE TITLE
Remove default value from 'dns-servers=' meson build option

### ISSUE THREAD

**Issue by Shamar** [systemd/systemd#34184]
### systemd version the issue has been seen with

254

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

No personal data leaks towards US surveillance firms by default.

### Unexpected behaviour you saw

vanilla systemd (compiled without customized parameters documented in https://github.com/systemd/systemd/blob/main/docs/DISTRO_PORTING.md) connects to Google (and Cloudflare) for ntp, dns requests and so on...

this is going on [for years](https://github.com/systemd/systemd/commit/1d1cb1683e978510ba8f08042ab6b86923c7b7ba), causing hard-to-identify personal data leaks for users and serious GDPR violations for employers and service providers during the years after the Schrems II sentence and the invalidation of Privacy Shield.

### Steps to reproduce the problem

make and install systemd without a custom configuration, log packets with pcap and you'll see requests towards one or more of these IP (depending on the network configurations) 1.1.1.1, 8.8.8.8, 1.0.0.1, 8.8.4.4, 2606:4700:4700::1111, 2001:4860:4860::8888, 2606:4700:4700::1001, 2001:4860:4860::8844

**Comment by Shamar** [comment]
Are you arguing that nobody should build and run systemd on their own?
AFAIK it's one of the basic freedoms granted by the [licenses](https://github.com/systemd/systemd/tree/main/LICENSES). Maybe I'm missing something about this?

In fact, these days there are several companies building systemd from sources for security reasons.

> Also, it only does this when you have no other DNS config.

Sure, and this is a very good reason to simply **not** include a working fallback.

This way, the people building systemd from source will not get a very hard to detect personal data leak, but a plain error. An even better approach would be to make the build fail if the constants have not be defined.

**Comment by poettering** [comment]
I am arguing that not everyone subscribes to your political views, and we made it very easy to pick a set of fallbcak dns servers or turn them off. Building systemd is not something for folks who aren't technically versed, hence making a choice on this after reading up on this I think is not too much to ask for.

Please just accept that we disagree on this.

Also this discussion was had before, really no need to rehash everything again and again and again.

**Comment by Shamar** [comment]
> I am arguing that not everyone subscribes to your political views

Actually it as a technical issue: **the build should fail** if the user forgot to specify some fundamental constants instead of picking values that could lead (and has already led) to law violations in several countries.

> Also this discussion was had before, really no need to rehash everything again and again and again.

Could you please share some references to the previous discussions? I looked for them among the issues and on the web in general without luck.

**Comment by poettering** [comment]
Let me google that for you!

here for example:

https://github.com/systemd/systemd/issues/494

and various other places.

Sorry, but i don't have time for this. It's really not that hard to find this.

**Comment by Shamar** [comment]
Ok, so this is a [9 years-old issue](https://github.com/systemd/systemd/issues/494)

Can you please explain your reasoning about the advantages of hard-coding Google and Cloudflare IPs as fallbacks instead (for example) list them as FallbackDNS in [the sample configuration](https://github.com/systemd/systemd/blob/main/src/resolve/resolved.conf.in#L25) (also in (https://github.com/systemd/systemd/blob/main/src/resolve/resolv.conf#L3))?

Also, how does one completely disable the FallbackDNS feature?
Is defining `FallbackDNS=` to the empty string in the resolv.conf enough to disable the feature or it would enable the Google and Claudflare DNS instead?
I've tried to give a look [to the code](https://github.com/systemd/systemd/blob/main/src/resolve/resolvectl.c) and [to the documentation](https://www.freedesktop.org/software/systemd/man/latest/resolved.conf.html#FallbackDNS=) (that omit to mention Google and Cloudflare as members of "compiled-in list of DNS servers") but I wasn't able to find a response.

Maybe we could at least agree that the use of such problematic defaults (at least for non-US citizens) should be clearly declared in the documentation? And maybe it should also clearly explain how to totally disable the FallbackDNS feature?

**Comment by bluca** [comment]
> Is defining FallbackDNS= to the empty string in the resolv.conf enough to disable the feature

Yes, as with all our config options having something, even an empty value, overrides the built-in defaults

**Comment by poettering** [comment]
> Can you please explain your reasoning about the advantages of hard-coding Google and Cloudflare IPs as fallbacks instead (for example) list them as FallbackDNS in [the sample configuration](https://github.com/systemd/systemd/blob/main/src/resolve/resolved.conf.in#L25) (also in [/src/resolve/resolv.conf](https://github.com/systemd/systemd/blob/main/src/resolve/resolv.conf#L3))?
> I've read the issues linked and I couldn't find an answer.

Quoting my comment in #494:

> We generally try to make our code work so that it works fine even without any configuration in /etc being around. As such resolved should come with compiled-in settings that make things work as last resort.

Still true, there's value in things just working, if no better config is available.

Seriously, *everything* you brought up here has been discussed to death already, and answered from our side. Please do not waste our time. Learn to google things, it's all there.
