### ISSUE TITLE
Overriding PIDFile does still trigger warning message

### ISSUE THREAD

**Issue by dg-nvm** [systemd/systemd#34191]
### systemd version the issue has been seen with

252

### Used distribution

Amazon Linux 2023.4.20240611

### Linux kernel version used

6.1.92-99.174.amzn2023.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

There should be no warning in log about PIDFile updating to /run/ when override is done

### Unexpected behaviour you saw

Message in journal:

systemd[1]: /usr/lib/systemd/system/fluentd.service:19: PIDFile= references a path below legacy directory /var/run/, updating /var/run/fluent...

### Steps to reproduce the problem

1. Issue `systemctl edit fluentd.service`
2. Add:

```
[Service]
# Fixing the PID to be in new place
PIDFile=/run/fluent/fluentd.pid
```
3. `systemctl daemon-reload`
4. `systemctl restart fluentd.service`

**Comment by poettering** [comment]
We generate these warnings whenever we parse a line that uses the legacy paths. I think that's the right approach here, as this is supposed to be a gentle way for upstreams to fix their unit files properly.

In most cases you can safely ignore these warnings btw, they are really just there to get upstreams to fix their unit files, that's all.
