### ISSUE TITLE
Expand tilde in `ExecStart` etc. for user services

### ISSUE THREAD

**Issue by rkitover** [systemd/systemd#34197]
### Component

systemd

### Feature Request

I think it would be nice if directives like `ExecStart` in user services would expand `~/` paths for the beginning of tokens.

The justification being that these are user services and users may expect such paths to work in this context.

No offense taken if you believe that this should not be supported.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by poettering** [comment]
That's a shell construct. I am not convinced we should rebuild a shell here.

You can achieve the same by just writing `${HOME}` instead of `~` in ExecStart= though, which doesn't sound too bad, does it.

hence, let's close this, we already should cover this well enough.

**Comment by yuwata** [comment]
Or, `%h` can be used. See https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Specifiers .

**Comment by rkitover** [comment]
I did not know that was supported, that is reasonable, thank you. I still think basic tilde expansion would be a nice thing to have, but that's ok.

Thank you for your work on making Linux a modern OS!
