### ISSUE TITLE
systemd-ssh-* documentation issues

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#34199]
### systemd version the issue has been seen with

256

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Hey.

https://github.com/systemd/systemd/blob/3722db214bf201d3c539d60c8d17c29fc3806730/man/systemd-ssh-proxy.xml#L61

Should probably read just `/etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf`. Could provide a patch if it helps.

https://github.com/systemd/systemd/blob/3722db214bf201d3c539d60c8d17c29fc3806730/man/systemd-ssh-generator.xml#L68

The manpage referenced there does not seem to exist?!

Cheers,
Chris.

**Comment by yuwata** [comment]
Please submit as a PR. Thank you!

**Comment by yuwata** [comment]
> Should probably read just `/etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf`. Could provide a patch if it helps.
> 
> https://github.com/systemd/systemd/blob/3722db214bf201d3c539d60c8d17c29fc3806730/man/systemd-ssh-generator.xml#L68

systemd.system-credentials, so unnecessary 'd'.

**Comment by calestyo** [comment]
Here you go! :-)
