### ISSUE TITLE
[RFE] An option to make timer run only once

### ISSUE THREAD

**Issue by Hi-Angel** [systemd/systemd#34222]
### Component

systemd-run

### Is your feature request related to a problem? Please describe

Discussed [on the ML previously](https://lists.freedesktop.org/archives/systemd-devel/2024-August/050690.html).

There's a [popular usecase of human-readably scheduling a command for later](https://askubuntu.com/q/339298/266507#conveniently-schedule-a-command-to-run-later). There are multiple non-systemd solutions, but they generally involve running a 3rd party service, such as `atd` for `at`.

This functional is provided by systemd though, e.g.:

```bash
systemd-run --user --on-calendar=12:10 systemctl suspend
```

There's just one problem: from now on this command will be running daily, unless you modify the time to include the date. But not only systemd doesn't allow syntax `--on-calendar="today 12:10"`, even if it did that would be prone to mistakes when a user has time 21:32 and they think "I'm gonna schedule a command for today at 00:07", but that isn't actually "today" but "tomorrow".

### Describe the solution you'd like

One possible solution might be an option like `--timer-run-once` for `systemd-run`. Or it may be a timer property `RunOnce` defaulting to `false`, and then a user would've to pass `--timer-property=RunOnce=true`.

Another potential solution might be implementing a calendar syntax so the combination `today 00:05` would work. However, as mentioned above I think it might be prone to mistakes, because colloquially word "today" is used for timespan before one went to sleep. Which might include e.g. 02:00 even though technically it is "tomorrow". Not saying people shouldn't be more careful, but a `RunOnce` would avoid such problem completely.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by AdrianVovk** [comment]
or we just use "today" in the colloquial sense. Any time you put that follows it will happen within the next 24 hours so I don't think it's a bad idea.

So if you schedule something for "today 02:00" it'll happen the next time the clock strikes 02:00 - which might be that same day if scheduled before 02:00, or might be the next day if scheduled after.

**Comment by martinetd** [comment]
Changing the meaning of today is a slippery slope, since that differs from tools like `date` and user will then wonder what `tomorrow` means, and `02:00 tomorrow` is ambiguous in the common sense (in my opinion)

It's also more restrictive than once as that won't allow things like scheduling for e.g. `Fri 14:00` for next Friday 2PM


otoh `--timer-run-once` is a mouthful to type, but something shorter like `--once` might be confusing with later expansions of the command, naming is always difficult.. having the "once" keyword be part of the calendar description might be more flexible? That could be used in real units too to auto-stop after one run, and it's not hard to type `--on-calendar="02:00 once"`

**Comment by Werkov** [comment]
There is `OnActive=` timer scheduling, available also under `systemd-run --on-active= ...`.
Does it solve the problem? Or is this about relative vs absolute timespec?

**Comment by Hi-Angel** [comment]
> There is `OnActive=` timer scheduling, available also under `systemd-run --on-active= ...`. Does it solve the problem? Or is this about relative vs absolute timespec?

I don't think it does, unless I'm missing something. When I execute a `systemd-run --user --on-calendar=21:25 --on-active=1 echo hi` and wait for timer to get triggered, and then look at `systemctl list-timers --user` I see that it says that the timer will be triggered again in 23 hours.

**Comment by Werkov** [comment]
You can use the option alone
`systemd-run --on-active=1h echo hi` (will print the message in 1 hour (modulo timer accuracy)) after finishing both (temporary) units are collected.

**Comment by Hi-Angel** [comment]
> You can use the option alone `systemd-run --on-active=1h echo hi` (will print the message in 1 hour (modulo timer accuracy)) after finishing both (temporary) units are collected.

Ah, so, like, same as `sleep 1h && systemd-run …`? I think it's inconvenient to use because you have to calculate the time offset.

**Comment by Werkov** [comment]
I see, absolute is preferred.
(FTR, `systemctl --when` (works for very specific cases though).)

**Comment by poettering** [comment]
I guess this RFE is a special case of #22818. Closing this one
