### ISSUE TITLE
Using systemd-networkd with TI switchdev switch

### ISSUE THREAD

**Issue by matthoe** [systemd/systemd#34247]
I'm using a chip from TI which contains a hardware switch. The switch driver uses the switchdev interface. So the switch can be configured via the bridge device.

The TI documentation has the requirement for the switch ports to be UP before joining the bridge.

"Port’s netdev devices have to be in UP state before joining the bridge"

[TI CPSW](https://software-dl.ti.com/jacinto7/esd/processor-sdk-linux-j721s2/latest/exports/docs/linux/Foundational_Components/Kernel/Kernel_Drivers/Network/CPSWng-Native-Ethernet.html#switch-mode)

Can this somehow be configured with systemd-networkd?

Currently, my switch ports go UP after joining the bridge. This leads to a wrong configuration. This can be obsevered in the latest systemd release and older version as well.

**Comment by yuwata** [comment]
> "Port’s netdev devices have to be in UP state before joining the bridge"

Is this switchdev specific? Or, general restriction?

**Comment by matthoe** [comment]
It seems specific to the TI driver implementation. Although, I don't have
any other HW to test this theory.


Yu Watanabe ***@***.***> schrieb am Mi., 4. Sept. 2024, 09:00:

**Comment by yuwata** [comment]
> Currently, my switch ports go UP after joining the bridge. This leads to a wrong configuration.

Could you elaborate more? What kind of issue do you observe?

Please provide corresponding .network and .netdev files. Also provide debugging logs of networkd, which can be generated by creating the following drop-in config with `sudo systemctl edit systemd-networkd.service`:
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by poettering** [comment]
are this drivers all upstream drivers? and that requirement of having those interfaces up, is that a generic requirement of the bridge/switchdev subsystem?

**Comment by matthoe** [comment]
Thanks, I updated my post with new names and a new log file.

**Comment by matthoe** [comment]
Here's a log file with the mentioned recovery at the end.

[journalctl_recoverd.txt](https://github.com/user-attachments/files/16904365/journalctl_recoverd.txt)

**Comment by matthoe** [comment]
Coming back to my original question:

"Is it possible to define the moment an interface is brought UP?"

Since this issue is labeled as "bug", I assume it's not possible do this in systemd-networkd at the moment.

Is it possible this could be implemented?

**Comment by yuwata** [comment]
> Coming back to my original question:
> 
> "Is it possible to define the moment an interface is brought UP?"

No, at least currently.

> Since this issue is labeled as "bug", I assume it's not possible do this in systemd-networkd at the moment.
> 
> Is it possible this could be implemented?

Theoretically, yes. But I am not sure we should do that. At first, I'd like to know if this is a bug in the driver or firmware.

**Comment by yuwata** [comment]
Could you provide the result of `udevadm info /sys/class/net/IFNAME` and `networkctl status IFNAME` ?
I'd like to know the driver name of the physical interface.

**Comment by yuwata** [comment]
Waiting in #34438. Please try the patch.
