### ISSUE TITLE
systemd-nspawn: /dev/net/tun permission take over

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#34243]
### systemd version the issue has been seen with

256.5-1

### Used distribution

Arch Linux

### Linux kernel version used

6.10.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

0 crw-rw-rw- 1 root root 10, 200 Sep  3 21:10 /dev/net/tun

### Unexpected behaviour you saw

0 crw-rw-rw- 1 vu-container-0 vg-container-0 10, 200 Sep  3 21:10 /dev/net/tun

Everytime you start a container the /`dev/net/tun` device got the permission of the unprivileged user (root) from container. But you have to manual `chown root: /dev/net/tun` to make /dev/net/tun work for example with qemu. This does **not** happen for example with other device like `/dev/dri/card0`

### Steps to reproduce the problem

Create nspawn file: /etc/systemd/nspawn/container.nspawn

```
[Exec]
Ephemeral=on
Boot=yes

NoNewPrivileges=yes
PrivateUsers=pick
Hostname=container

[Network]
Private=yes
VirtualEthernet=yes
```

Start via `systemctl start systemd-nspawn@container`

**Comment by yuwata** [comment]
Hm? I cannot reproduce the issue:
```
$ sudo systemd-nspawn -U -xD / --network-veth --boot --no-new-privileges=yes
(snip)
# ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Sep  5 14:32 /dev/net/tun
```

**Comment by yuwata** [comment]
Ah, when mknod() fails, then we bind-mount, and chown the node...

**Comment by yuwata** [comment]
But, why mknod fails??

**Comment by migrgh** [comment]
Thanks you both.

But i just want to notice that there could be more:

I build 256.5-1 with just the fix [patch](https://github.com/systemd/systemd/commit/efedb6b0f3cff37950112fd37cb750c16d599bc7.patch). 

now i can't start the container at all the error:
`
Sep 07 00:01:05 archlinux systemd-nspawn[1918]: mknod(/var/lib/machines/.#machine.container251c661064d76378/dev/net/tun) failed: Operation not permitted`

Better i just wait for new release or take time to build from git before open a new issue.

**Comment by yuwata** [comment]
Still I have no idea why mknod() fails in your case.
Do you start the container through systemd-nspawn@.service ? If so, could you try to invoke systemd-nspawn manually ?

**Comment by migrgh** [comment]
Yes i'm run "doas systemctl start systemd-nspawn@mpv"

```
[Exec]
Ephemeral=on
Boot=yes

NoNewPrivileges=yes
PrivateUsers=pick
Hostname=mpv

[Files]
Bind=/home/user/.config/mpv:/home/user/.config/mpv:idmap

Bind=/var/run/user/1000/wayland-1:/home/user/xdg/wayland-1:idmap
Bind=/var/run/user/1000/pulse/native:/home/user/xdg/pulseaudio

Bind=/dev/dri/card0:/dev/dri/card0
Bind=/dev/dri/renderD128:/dev/dri/renderD128

Bind=/home/user/share:/home/user/share:idmap
BindReadOnly=/mnt/samba:/mnt/samba

[Network]
Private=yes
VirtualEthernet=yes
```

Try to convert to cmdline and it works without mknod error with [fix](https://github.com/systemd/systemd/commit/efedb6b0f3cff37950112fd37cb750c16d599bc7.patch)

```
doas systemd-nspawn \
--ephemeral \
--boot \
--no-new-privileges=yes \
--private-users=pick \
--hostname=mpv \
--bind=/home/user/.config/mpv:/home/user/.config/mpv:idmap \
--bind=/var/run/user/1000/wayland-1:/home/user/xdg/wayland-1:idmap \
--bind=/var/run/user/1000/pulse/native:/home/user/xdg/pulseaudio:idmap \
--bind=/dev/dri/card0:/dev/dri/card0 \
--bind=/dev/dri/renderD128:/dev/dri/renderD128 \
--bind=/home/user/share:/home/user/share \
--bind-ro=/mnt/samba:/mnt/samba\
--private-network \
--network-veth \
-D /var/lib/machines/mpv
```

There is also `/etc/systemd/system/systemd-nspawn@mpv.service.d/override.conf` to allow gpu.

```
[Service]
DeviceAllow=
DeviceAllow=/dev/dri/card0
DeviceAllow=/dev/dri/renderD128
```

Do the `DeviceAllow=` only apply card0 and renderD128 disallow mknod? Else i have no idea why this happen. All this is very time consuming and i hope we could figure it out.

**Comment by migrgh** [comment]
Okay had some more time and if i add `DeviceAllow=/dev/net/tun` to override.conf it works with the fix. But i don't know why i have to add it now and not in the past. Again thank you for fixing the bug and this is now just a config error sorry for the confusion.

**Comment by yuwata** [comment]
As you can see, systemd-nspawn@.service has DeviceAllow= for /dev/net/tun, https://github.com/systemd/systemd/blob/411d8c72ecc31f1e7ecfa70b40e7766093aa14b2/units/systemd-nspawn%40.service.in#L37, but you disabled by setting an empty string to DeviceAllow=, thus the predefined settings are cleared.
Please try to drop the line `DeviceAllow=` with an empty string.

**Comment by migrgh** [comment]
yes indeed remove the line `DeviceAllow=` and now it works as expected. i thought i have to add it to allow more Devices, anyway. thank you !
