### ISSUE TITLE
Setting '--seed=random' in systemd-repart always produces the same PTUUID in every partition table/run

### ISSUE THREAD

**Issue by nadiia-dubchak** [systemd/systemd#34257]
### systemd version the issue has been seen with

255

### Used distribution

[Azure Linux 2.0 and 3.0](https://github.com/microsoft/AzureLinux)

### CPU architectures issue was seen on

None

### Component

systemd-repart

### Expected behaviour you didn't see

Per documentation on systemd-repart [here](https://www.man7.org/linux/man-pages/man8/systemd-repart.8.html): "If the machine ID cannot be read (or the user passes --seed=random, see below) the seed is generated randomly instead, so that the partition UUIDs are also effectively random." Thus, in our codebase, while partitioning a series of empty disks, we set "--seed=random" while making the call to systemd-repart on each disk path.

We expected to see each disk partitioned via systemd-repart in this manner to have unique UUIDs assigned to it, including the partition table UUID, PTUUID. When we have multiple disks in the system, it is crucial that each disk has a unique randomized PTUUID assigned to it, so that we're able to differentiate between the two.

### Unexpected behaviour you saw

However, we've discovered that setting "--seed=random" results in every disk being assigned the same single PTUUID. This behavior logically goes against the idea of a UUID since each UUID is no longer unique and thus, is a bug. Please find a screenshot of the lsblk output attached below, with all three disks being assigned the same PTUUID, a8dbca6f77a6f85c0c67b653758a89287c689962de1fdeeee5cd0507b17f5a82.

![Screenshot 2024-09-04 140644 (2)](https://github.com/user-attachments/assets/b50c17d4-9a77-473d-a943-54f70ab63a82)

To understand the origin of the bug, our team has reviewed the source code for system-repart, and found the following bug. In the logic [here](https://github.com/systemd/systemd/blob/main/src/partition/repart.c), context_read_seed() calls sd_id128_randomize() to generate a random seed, if the user has set "--seed=random" OR if the logic failed to parse the UUID provided or to retrieve the machine ID. However, context_read_seed() is called [inside of the main function run() on line 8337](https://github.com/systemd/systemd/blob/7560a5393a7d8708f35d956d50934014f5595478/src/partition/repart.c#L8337). On the other hand, derive_uuid() is the function that actually uses the assigned value of "context->seed," which is the seed value, to generate a new UUID for the partition/disk using the hashing function. But derive_uuid() is being called inside of function context_load_partition_table(), which in turn, is called [inside of run() on line 8332](https://github.com/systemd/systemd/blob/7560a5393a7d8708f35d956d50934014f5595478/src/partition/repart.c#L8332C1-L8332C59), BEFORE context_read_seed() is called. This means that arg_seed is still set to SD_ID128_NULL when the hashing logic is called, which means that instead of generating a unique randomized UUID every time, the logic generates the same UUID. This single UUID can be reproduced in the following way:

```
$ printf '%s' "disk-uuid" | openssl sha256 -hex -mac HMAC -macopt hexkey:"00000000000000000000000000000000"
SHA256(stdin)= a8dbca6f77a6f85c0c67b653758a89287c689962de1fdeeee5cd0507b17f5a82
```

### Steps to reproduce the problem

1. Create multiple disks on the system and make them available for partitioning,
2. Run "systemd-repart" command on each disk path, while setting "--seed=random",
3. Inspect the disks' PTUUID via lsblk, e.g., to confirm that each disk has been assigned the same PTUUID.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #34261.
