### ISSUE TITLE
RFE: systemctl --user flag is a usability misfeature

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#34253]
### Component

systemctl

### Is your feature request related to a problem? Please describe

Let me preface this with I consider this a very low importance ask but I feel like it needs to be mentioned after a decade of personally using systemd heavily.

The vast majority, personally I don't think i've ever encountered it, of the time the distinction between a user service and a system service from a users usage of systemctl does not exist.

I'm not advocating for the removal of the the flag itself, I believe being able to be explicit *is* important. I'm asserting requiring the explicitness of users day to day is a nuisance. This includes when training new individuals about systemctl and having to explain that yes, its a uniquely named service, but its user scoped so you have to add this flag because systemctl requires it.

### Describe the solution you'd like

the fact systemctl* expect users to flag every user scoped command is a nuisance. systemctl is perfectly capable of determining which scope any given service is under, and if needed request privileged escalation**. strictly speaking it doesn't even need make a determination about scope it can just assume user if non-root, and if not found then try the system scope.

\* same issue plagues journalctl,
** I will also note the privilege escalation dialogue could use some finessing as well, it certainly should not be asking me which user to use when the current user is capable, but i suspect this is unrelated to systemd directly and its delegated to another dbus service.

```
[foo@localhost ~]$ systemctl reboot
==== AUTHENTICATING FOR org.freedesktop.login1.reboot ====
Authentication is required to reboot the system.
Multiple identities can be used for authentication:
 1.  foo
 2.  bar
 3.  bazz
Choose identity to authenticate as (1-3):
```

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by poettering** [comment]
> the fact systemctl* expect users to flag every user scoped command is a nuisance. systemctl is perfectly capable of determining which scope any given service is under

Not it cannot do that. Many services exists under all scopes. For example dbus.service is generally available once on the system, and once for each user. And there are various others like that.

I am not convinced that "searching" for a service among accessible scopes would really be a good idea, since we might end up on the wrong scope then. It adds a fuzziness to things where there shouldn't be fuzziness, after all the distinction between scopes is mostly about privilege separation, and hence automatically suppressing that separation kinda spoils the whole concept. 

> ** I will also note the privilege escalation dialogue could use some finessing as well, it certainly should not be asking me which user to use when the current user is capable, but i suspect this is unrelated to systemd directly and its delegated to another dbus service.

That's a polkit thing. The prompt is shown by polkit's tty agent. Please file an issue to the PK package about that.

**Comment by james-lawrence** [comment]
disagree that it can't do it. it absolutely *can* do it. the privilege separation isn't an issue since users are asked prior to mutating a system service for non-root users. there is very little downside here, the ambiguity of the scope exists today. changing the implementation behavior doesn't change this fact.

the worst case is as you mentioned a user restart a service in their session which is hardly the end of the world. in fact using the user session assumption i'd be willing to wager it'd be fairly safe. as an example I just restarted dbus for both my user and the system. the user session logged me out. the system service required a manual restart. defaulting to the user session is actually safer ;)

 lets break down the situations and their outcomes for a non-root (but with sudo privs) user:

1. service exists only in the user scope. service is mutated as requested. :heavy_check_mark: better user experience
2. service exists only in the system scope. user would be prompted by polkit, no change from today. :wavy_dash: no change.
3. service exists in both scopes. implementation detail on how to resolve. there are 4 options here:
- maintain current behavior and prompt to authorize the interaction with the system service. :wavy_dash: no change.
- assume the user scope since they're not running as root. :grey_question: I'm willing to bet this is a better user experience because my non-empirical guess the number of times people interaction with services like dbus manually is incredibly rare comparatively to general user services.
- warn about the ambiguity / bail out. :grey_question: I'm willing to claim this is a better user experience than status quo because it informs the user about the fact the command is ambiguous vs blindly making an assumption one way or the other.

> since we might end up on the wrong scope then

ending up in the wrong scope is already an issue today. as evidenced by the fact at least *one* person (me ;)) finds this behavior a nuisance. if its not ambiguous wtf is systemctl telling me that a service doesn't exist, or just assuming the less safe option of restart a system service? at least in the ambiguous case there is a reason for systemctls behavior. where as right now the --user flag is mostly just unnecessary ceremony. since it only helps in the ambiguous case.

I don't particularly care about the implementation decision made for how systemctl presents the ambiguous situation to the user. plenty of fine options that can be done there. I'm sure you can come up with a few other ideas as well;

**Comment by poettering** [comment]
> disagree that it can't do it. it absolutely _can_ do it. the privilege separation isn't an issue since users are asked prior to mutating a system service for non-root users.

Nope, we do not ask the user. PK might, depending on the configured policy. And the policy might vary drastically locally.

**Comment by dtardon** [comment]
> I'm willing to claim this is a better user experience than status quo because it informs the user about the fact the command is ambiguous vs blindly making an assumption one way or the other.

But `systemctl` is not "blindly making an assumption". It connects to specified and _predictable_ `systemd` instance. It's your proposal that introduces ambiguity and guessing. And IMHO _predictable_ is the most important part--there's no place for guessing in system management software.

Also, you're too focused on your narrow use case. For example, what do you propose to do about `systemctl` verbs that don't take a unit: `daemon-reload`, `daemon-reexec`, `status`, `show` etc.? To change their behavior would mean a compatibility break (and a break of gadzillion of scripts). To not change it would mean inconsistency ("I don't need to specify `--user`, but sometimes I do").

**Comment by poettering** [comment]
Anyway, I dont think we should do this. The ambiguities this creates are problems, given the scope differences are about security really. Hence, let's close this. 

Sorry, but I guess we have to disagree on this.

**Comment by james-lawrence** [comment]
disagree away but the assertion its anymore ambiguous than the current behavior is logically flawed. 🤷
