### ISSUE TITLE
Misleading error message on 'systemctl status nonexistent-unit.service'

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#3425]
On the current master, commit e33a06a1eb7406ece8e35f6346ba0ea208c11cf1 introduced a new error message when running systemctl. The message is wrong, even in the commit message the examples show that.

From the commit message:

```
$ ./systemctl show --property Id this.is.rubbish; echo $?
Can't display property this.is.rubbish. Unit this.is.rubbish.service does not
```

The property is _Id_, not this.is.rubbish. The first sentence of the error message should be there only if I'm trying to show properties (or maybe shouldn't be there at all).

The commit also breaks systemctl status, which now shows the same misleading error message:

```
$ ./systemctl status i-dont-exist
Can't display property i-dont-exist. Unit i-dont-exist.service does not exist.
```

**Comment by ssahani** [comment]
PR https://github.com/systemd/systemd/pull/3411

**Comment by jsynacek** [comment]
That PR is still missing a fix for the broken message.

**Comment by poettering** [comment]
Yeah, the PR looks unrelated to the issue here. And the message is still borked.

**Comment by ssahani** [comment]
How about '

``````
Failed to display non-existent property this.is.rubbish.
``` ?
``````

**Comment by jsynacek** [comment]
The point is that the part of the message talking about the property just shouldn't be there when all you ask for is status. It should be there only when you want to show properties and they don't exist.
