### ISSUE TITLE
systemd-homed allow user to update his own config without admin

### ISSUE THREAD

**Issue by GreenYun** [systemd/systemd#34268]
### Component

homectl

### Is your feature request related to a problem? Please describe

Current homectl allows user to do limited thing. If one wants to change his own default shell, he must ask the admin for help.

Looking at `chsh`, it can just update the default shell as it had been `setuid`.

### Describe the solution you'd like

Users should be free to update their home area.

### The systemd version you checked that didn't have the feature you are asking for

256.5-1-arch

**Comment by AdrianVovk** [comment]
A fix for this is already pending in https://github.com/systemd/systemd/pull/31153
