### ISSUE TITLE
In the event_is_blocked function for determining device blocking conditions, if two network devices have the same devpath, their ifindex should be further checked for equality instead of directly blocking the event

### ISSUE THREAD

**Issue by YoruStar** [systemd/systemd#34260]
### Component

systemd-udevd

### Is your feature request related to a problem? Please describe

In my business environment, I discovered a special type of network device where all the network interfaces are located under the same directory:
```
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens1
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens2
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens3
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens4
```
With net.ifnames=1 set in the kernel command line, and our custom rules executing some time-consuming scheduled tasks for network devices, the operating system startup has significantly slowed down. The specific process is as follows:
- Network interface A comes online, is renamed from `eth1` to `ens1`, and begins executing time-consuming tasks.
- Network interface B comes online. Since the `eth1` interface name was released by network interface A, network interface B takes the `eth1` name. At this point, network interfaces B and A have the same devpath, causing the event for network interface B to wait until the event for network interface A is completed before it can be processed.

### Describe the solution you'd like

It is precisely because network interface events have to be processed serially that my system startup has become slow. Although this is due to the special hardware devices and our own business requirements, I still think that systemd could be optimized to handle this better:

In the `event_is_blocked` function, if two devices have the same `devpath`, further check if their `ifindex `is the same. If the `ifindex `is different, do not block their events.

### The systemd version you checked that didn't have the feature you are asking for

systemd-255

**Comment by yuwata** [comment]
An ancient udevd has such logic. But I changed for some reason. I am diving into the logs.

**Comment by poettering** [comment]
you should *never* do time-consuming stuff from udev rules? instead pull in a service via SYSTEMD_WANTS prop, and then run them there.

udev aggressively kills slow worker processes, hence if you do time consuming stuff in udev rules you have a pretty unstable system anyway.

**Comment by yuwata** [comment]
Note, the logic was changed by baa461fc05934d02ece3abd7666c144549c695cf (v242).

**Comment by yuwata** [comment]
And yeah, please use SYSTEMD_WANTS.

**Comment by syyhao1994** [comment]
```
In the event_is_blocked function, if two devices have the same devpath, further check if their ifindex is the same. If the ifindex is different, do not block their events.
```
I think what he want to say is that the devices have the same devpath maybe should not be blocked as they don't have the same ifindex as the net devices he mentioned

```
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens1
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens2
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens3
/sys/devices/pci0000:80/0000:80:10.0/0000:85:00.0/net/ens4
```

**Comment by yuwata** [comment]
@syyhao1994 Yes, I understand. But, as said, udevd older than v242 has such optimization, but we intentionally dropped that. As it causes issues like #6514.

So, sorry, but we cannot accept such suggestion. Please use SYSTEMD_WANTS.

Closing.
