### ISSUE TITLE
systemd-resolved fails for misconfiggured CNMAES with DNSSEC validation failed: no-signature

### ISSUE THREAD

**Issue by sergedroz** [systemd/systemd#34269]
### systemd version the issue has been seen with

255.10

### Used distribution

Fedora 40

### Linux kernel version used

6.10.7-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

A CNAME should not have any other records, i.e. 

exmple.com CNAME bla.example.com
example.com MX mx.example.com

is technically wrong.  However
 > resolvectl query  exmple.com 
 exmple.com : resolve call failed: DNSSEC validation failed: no-signature

is not correct either. 

### Unexpected behaviour you saw

Just accept the result, it's not a security issue, or at leas print a proper error message.

### Steps to reproduce the problem

resolvectl query genevadialogue.ch (Issue on 5.9.2024).

**Comment by rpigott** [comment]
Duplicate of #31484.
