### ISSUE TITLE
Noticed journal flooded with systemd-timesyncd traces 

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#34262]
### systemd version the issue has been seen with

255

### Used distribution

GNU/Linux

### Linux kernel version used

6.1.37-c9c2d51

### CPU architectures issue was seen on

aarch64

### Component

systemd-timesync

### Expected behaviour you didn't see

these systemd-timesyncd traces flooding on journal, how to avoid these traces from systemd-timesyncd
systemd-timesyncd[262]: Network configuration changed, trying to establish connection.

### Unexpected behaviour you saw

dont want to see these traces flooding journal
systemd-timesyncd[262]: Network configuration changed, trying to establish connection.

### Steps to reproduce the problem

I see journal keeps flooding with these traces.

**Comment by yuwata** [comment]
-> #34278.

**Comment by raviteja-b** [comment]
@yuwata is there any workaround or configuration setting which can avoid these journals ??

**Comment by yuwata** [comment]
You can kill log messages equal or higher than LOG_INFO by creating the following dropin with `sudo systemctl edit systemd-timesyncd.service`:
```
# /etc/systemd/system/systemd-timesyncd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=notice
```
