### ISSUE TITLE
block devices disapearing during a short period of time

### ISSUE THREAD

**Issue by fmore-xyz** [systemd/systemd#3427]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> all

Hi,

After creating a new partition table on a disk my prog is doing a ioctl(BLKRRPART) to inform the kernel about this change. I can then access to the partition block device nodes.

But after closing the disk device, the device nodes disappear and re-appear (shortly after).

That's quite unexpected and seems due to udevd that issues automagically a ioctl(BLKRRPART) when my prog closed the device.

Why does udevd do this ? I'm failing to see the point.

IMO that just makes the dance around the block device handling even more racy.

Thanks.

**Comment by poettering** [comment]
Sincr years udev has not been involved with creating or removing device nodes. That's done by the kernel itself via devtmpfs. Udev only applies access modes/ownerships/acls to them and maintains metadata for them.

Please contact the kernel folks about this as they are the ones creating/removing the device nodes.

**Comment by fmore-xyz** [comment]
But udev issues a ioctl(BLKRRPART) automagically when my prog closes the block device.

I don't see the point of doing that, specially since I have to take care of this case too.

**Comment by poettering** [comment]
yeah, udev does that to handle things like "dd" onto a device properly. You can take a BSD lock on the device node to block udev from doing this.

**Comment by fmore-xyz** [comment]
well how am I donig that if my prog is a shell script ?

and IMHO udev shouldn't do that on the back of the user, specially since most partitioning tool already issue the ioctl and don't expect another one to be issued at almost random time. That's quite ugly.

For dd hackers, they have partprobe but they already know...

**Comment by fmore-xyz** [comment]
BTW isn't this behavior just breaking simple code like this:

 sfdisk -xxx /dev/sda && mkfs /dev/sda1

Normally when sfdisk exits successfully, the partition it's just created must have a node in /dev (devtmpfs).

Now that udev issues BLKRRPART at any time between the 2 calls, the device might be missing when mkfs tries to open it.

**Comment by vcaputo** [comment]
@fmoreau how about inserting an `udevadm settle` between the `sfdisk` and `mkfs`?

**Comment by fmore-xyz** [comment]
@vcaputo I dont see how "udevadm settle" could help here since the BLKRRPART issued by udevd is totally asynchronous.

Also previous this change, nothing was required to access /dev/sda1 safely (if devtmpfs was used).

**Comment by vcaputo** [comment]
@fmoreau see https://bugs.freedesktop.org/show_bug.cgi?id=20813#c4

**Comment by fmore-xyz** [comment]
@vcaputo what's the link supposed to show ?

@poettering could you show how "sfdisk -xxx /dev/sda && mkfs /dev/sda1" can be modified to work  ?

**Comment by a3f** [comment]
Sorry to ping old threads, but for the record if someone lands here via search engine:
```
if [ $# -eq 0 ]; then
  exec flock "$0" /dev/sda --flocked
fi

# Lock is held here and udev won't issue BLKRRPART until exit
sfdisk -xxx /dev/sda
mkfs /dev/sda1
```
