### ISSUE TITLE
Typo *_VIOALTION

### ISSUE THREAD

**Issue by darkblaze69** [systemd/systemd#34274]
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.11.0-rc5-1-mainline

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Probably a wrong usage or at least a typo:

```
$ grep -nri VIOALTION .
./src/basic/linux/if_link.h:1717:	PORT_VDP_RESPONSE_VTID_VERSION_VIOALTION,
```

A similar correct spelling is used:

`
./src/basic/linux/if_link.h:1716:	PORT_VDP_RESPONSE_VTID_VIOLATION,
`

### Unexpected behaviour you saw

Don't know the effect

### Steps to reproduce the problem

Don't know the effect

**Comment by YHNdnzj** [comment]
Headers under basic/linux/ are imported from linux kernel source as-is. Please report any problem to kernel instead.
