### ISSUE TITLE
Enhance os-release to include codename

### ISSUE THREAD

**Issue by bdrung** [systemd/systemd#3429]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

Disclaimer: I am reporting this request against systemd, because os-release.5 man page is shipped by the systemd 229 package on Ubuntu.

Please enhance the os-release specification to include an optional CODENAME parameter. This parameter identifies the code name of the release. Example: "CODENAME=jessie" for Debian 8 and "CODENAME=xenial" for Ubuntu 16.04.

Side note: Ubuntu 16.04 already ships "UBUNTU_CODENAME=xenial" in /etc/os-release

**Comment by poettering** [comment]
well, this appears to be a concept specific to one distro, hence using a distro-specific field appears OK to me. That said, I'd probably be willing to merge a patch for this, if it comes from the Ubuntu folks. @martinpitt?

**Comment by martinpitt** [comment]
It's actually two distros (Ubuntu inherited the codename approach from Debian, where these are things like "unstable", "testing", "wheezy", "squeeze", etc. I have a déjà vu feeling that I've seen this request like three times already :-).

We currently use `UBUNTU-CODENAME=...`, but I wouldn't mind changing that to just `CODENAME=`.

Note that @bdrung is a well-known Debian and Ubuntu developer. @bdrung, since I'm swamped recently, do you want to have a go at this, I'll review/refine, and once we're both happy we present it to Lennart? Thanks!

**Comment by bdrung** [comment]
@martinpitt: Yes, that's a good plan. I'll try to come up with a patch next week.

Side note: A codename parameter would be useful for salt, which provides a oscodename grain and uses /etc/os-release (or lsb_release if it is installed).

**Comment by bdrung** [comment]
Note: Also lsb_release has a --codename option.

**Comment by johannbg** [comment]
What's the usecase/justification for adding an separated "codename" field for this as opposed to just use the version field for this as other distributions are doing?

**Comment by johannbg** [comment]
For Debian it would be 
VERSION="Jessie"
VERSION_ID=8

And for Ubuntu it would be
VERSION="Xenial"
VERSION_ID=16.04
So I fail to see the usecase/justification hence I have to ask what is Debian/Ubuntu using these fields for?

**Comment by bdrung** [comment]
If we would use VERSION for the codename, the version number would be missing. On Ubuntu, the codename is used while the development and the version number after the release. But the codename is still part of the apt sources and therefore is needed to be known.

On Ubuntu, the full codename is adjective plus animal name, but only the adjective is used for the apt sources:

```
VERSION="16.04 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
```

VERSION can be used for displaying the version and VERSION_CODENAME for script that needs to know the codename.
