### ISSUE TITLE
Random order of nameserver entries in /run/systemd/resolve/resolv.conf

### ISSUE THREAD

**Issue by jernst** [systemd/systemd#343]
We might be able to debate whether this is a bug or a feature, but for me it is a bug, so I file it.

Without further settings, `/run/systemd/resolve/resolv.conf` contains these settings in apparently random order. I don't know what causes the reordering, but every time I look, the order seems to be different:

```
nameserver 2001:4860:4860::8844
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
# Too many DNS servers configured, the following entries may be ignored.
nameserver 8.8.8.8
```

I'm using this on an ipv4-only network, which means that half of the time, name resolution attempts ipv6 first, with the corresponding long timeouts. I have no issue with the defaults being both ipv4 and ipv6, but the sequence should not be random.

**Comment by poettering** [comment]
Which systemd version are you using? You are probably using 219 and are thus missing 822db23cfa98a9fbc48f41e11caafb6f1017e052. Please uprade to 220 at least.

**Comment by jernst** [comment]
Ah. Thanks.
