### ISSUE TITLE
boot: Exit boot services failed

### ISSUE THREAD

**Issue by anonymix007** [systemd/systemd#34308]
### systemd version the issue has been seen with

256.5

### Used distribution

Arch Linux ARM (EndeavourOS)

### Linux kernel version used

6.11.0-rc6-3-x1e-g1e503208bf0f

### CPU architectures issue was seen on

aarch64

### Component

systemd-boot

### Expected behaviour you didn't see

Bootable system

### Unexpected behaviour you saw

```
EFI stub: ERROR: Exit boot services failed
```
"Normal" boot:
![image](https://github.com/user-attachments/assets/a4af6bf1-9599-4919-b6ad-c92a141a82e0)
UKI:
![image](https://github.com/user-attachments/assets/68f97609-4b94-4753-b620-4ca39cc74200)
(Lines before `EFI stub: Booting Linux kernel...` are printed for debug purposes for #34158)

### Steps to reproduce the problem

1. Turn on the laptop
2. Don't touch anything, just wait for it to boot
3. See the error

I can more or less reliably boot UKI from systemd-boot selection menu, however, "normal" boot (vmlinux) just doesn't work.

**Comment by YHNdnzj** [comment]
> EFI stub: ERROR: Exit boot services failed

This error is emitted by the [kernel EFI stub](https://elixir.bootlin.com/linux/v6.10.8/source/drivers/firmware/efi/libstub/fdt.c#L331), not by sd-stub. What makes you think that this is a systemd bug?

**Comment by anonymix007** [comment]
Actually, with the "normal" boot sd-stub isn't even ran, so it's not really about sd-stub, but rather about sd-boot.
In general, this can be firmware, kernel or systemd issue. However, given the fact that it doesn't happen with grub (USB boot) and only happens if I don't interrupt sd-boot, I'd assume this is about systemd.
