### ISSUE TITLE
Secure boot auto enrollment stopped working at some point

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#34316]
### systemd version the issue has been seen with

254-256

### Used distribution

Fedora 39-41

### Linux kernel version used

N/A

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Secure boot auto enrollment works as expected

### Unexpected behaviour you saw

Secure boot auto enrollment fails to enroll the platform key:

```
Enrolling secure boot keys from directory: \loader\keys\auto
Failed to write PK secure boot variable: Security violation
```

### Steps to reproduce the problem

```
mkosi -d fedora -r rawhide -p kernel-core -p systemd -p udev -p systemd-boot --secure-boot --secure-boot-auto-enroll=yes -f qemu
```

This could also be a bug in mkosi, but I haven't the slightest clue how to narrow this down. If EDK2 would tell why it rejected the key that would help but I have no idea how to make it do that. @kraxel Any ideas on how we can debug this?

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Enrolling secure boot keys from directory: \loader\keys\auto
Failed to write PK secure boot variable: Security violation
```

**Comment by DaanDeMeyer** [comment]
This is using the following EDK2 firmware description on Fedora 40:

```
➜  particleos git:(main) ✗ cat /usr/share/qemu/firmware/40-edk2-ovmf-4m-qcow2-x64-sb.json
{
    "description": "OVMF with SB+SMM, empty varstore",
    "interface-types": [
        "uefi"
    ],
    "mapping": {
        "device": "flash",
        "mode" : "split",
        "executable": {
            "filename": "/usr/share/edk2/ovmf/OVMF_CODE_4M.secboot.qcow2",
            "format": "qcow2"
        },
        "nvram-template": {
            "filename": "/usr/share/edk2/ovmf/OVMF_VARS_4M.qcow2",
            "format": "qcow2"
        }
    },
    "targets": [
        {
            "architecture": "x86_64",
            "machines": [
                "pc-q35-*"
            ]
        }
    ],
    "features": [
        "acpi-s3",
        "requires-smm",
        "secure-boot",
        "verbose-dynamic"
    ],
    "tags": [

    ]
}
```

**Comment by DaanDeMeyer** [comment]
The firmware debug log doesn't contain anything useful:

```
Tcg2HashLogExtendEvent - Success
MeasureBootPolicyVariable - Success
ValidateSetVariable - Variable (8BE4DF61-93CA-11D2-AA0D-00E098032B8C:PK) returning Success.
ValidateSetVariable - Variable (4A67B082-0A4C-41CF-B6C7-440B29BB8C4F:LoaderEntries) returning Success.
VirtioSerialIoGetControl:136: Control 0x0
VirtioSerialIoRead:206: WriteFlush 89
```

**Comment by YHNdnzj** [comment]
This works perfectly on my laptop (bare metal), hence I doubt it is a systemd issue.

**Comment by bluca** [comment]
Enrolling secure boot keys from directory: \loader\keys\auto
Failed to write PK secure boot variable: Security violation

This sounds like the fw Is not in setup mode?

**Comment by DaanDeMeyer** [comment]
> Enrolling secure boot keys from directory: \loader\keys\auto Failed to write PK secure boot variable: Security violation
> 
> This sounds like the fw Is not in setup mode?

It is I double checked that

**Comment by bluca** [comment]
Very strange, no idea then

**Comment by DaanDeMeyer** [comment]
I've narrowed it down to `sbsigntools`. If I switch to efitools in mkosi the enrollment works. I'll close the issue here since it's a mkosi issue and not a systemd one

**Comment by DaanDeMeyer** [comment]
Bisected down to this in gnu-efi:

```
commit 189200d0b0f6fff473d302880d9569f45d4d8c4d
Author: Callum Farmer <gmbr3@opensuse.org>
Date:   Sat Apr 8 19:43:42 2023 +0100

    Make WCHAR and CHAR16 identical
    
    And actually use wchar_t
    gnu-efi already uses L string literals which are of type
    wchar_t
    
    Signed-off-by: Callum Farmer <gmbr3@opensuse.org>
```

Fixed by reverting that commit or building sbsigntools with `-fshort-wchar`
