### ISSUE TITLE
run0 misbehaves if shell is Fish

### ISSUE THREAD

**Issue by schuelermine** [systemd/systemd#34320]
### systemd version the issue has been seen with

256.4

### Used distribution

NixOS unstable

### Linux kernel version used

6.10.6

### CPU architectures issue was seen on

x86_64

### Component

systemd-run, other

### Expected behaviour you didn't see

No error messages on shell startup during `run0` invocation

### Unexpected behaviour you saw

```
/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash: line 1: env: command not found
set: Tried to change the read-only variable 'PWD'
set: Tried to change the read-only variable 'SHLVL'
/nix/store/i6p9a03zfm3kpvk1m8xvdm27ils6dq64-set-environment: line 15: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/nix/store/i6p9a03zfm3kpvk1m8xvdm27ils6dq64-set-environment: line 18: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/nix/store/i6p9a03zfm3kpvk1m8xvdm27ils6dq64-set-environment: line 21: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/nix/store/i6p9a03zfm3kpvk1m8xvdm27ils6dq64-set-environment: line 24: warning: setlocale: LC_TIME: cannot change locale (en_GB.UTF-8): No such file or directory
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@nailbox-on-buggeryyacht /h/anselmschueler# 
```

Note that the messages about locale also occur when starting Bash, and I assume they are not systemd’s fault, but something with NixOS being weird.

### Steps to reproduce the problem

- `# chsh $(which fish)`
- `$ run0`

**Comment by NickCao** [comment]
I think the problem is with run0 messing with PATH, under it the PATH only contains systemd itself.

**Comment by NickCao** [comment]
`run0 --setenv=PATH` works as expected.

**Comment by NickCao** [comment]
Another workaround/solution: set `programs.fish.enable = true;` so that `/etc/fish/nixos-env-preinit.fish` is populated and sets PATH (and other variables) correctly.

**Comment by schuelermine** [comment]
I see. So it is the Fish config file expecting some environment variables to exist already.
