### ISSUE TITLE
Bind interface option for systemd-resolved

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#34329]
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

I often use VPN and it's not exactly stable, so whenever it (temporarily) goes down, name resolution stops working completely because all the traffic goes into the VPN tunnel.

### Describe the solution you'd like

Bind interface or IP address could solve the issue, as name resolution traffic could use the stable default connection.

### Describe alternatives you've considered

None that I can think of.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
i don't understand what you are trying to say? what is "bind interface option" supposed to mean?

DNS traffic goes to the interface you define your DNS settings on. If you don't want your traffic to go onto the VPN, then attach your DNS settings to your "default connection" instead (or in addition to).

**Comment by birdie-github** [comment]
> i don't understand what you are trying to say? what is "bind interface option" supposed to mean?

`bind=interface` or `bind=ip_address` (or `listen`)

> DNS traffic goes to the interface you define your DNS settings on. If you don't want your traffic to go onto the VPN, then attach your DNS settings to your "default connection" instead (or in addition to).

DNS traffic as far as I can see always uses the default network interface which may change if you're using VPN. I want to be able to tell resolved to use a user defined network interface.

This is NOT the question of the upstream DNS server.

This is the question of routing DNS traffic.

**Comment by poettering** [comment]
> `bind=interface` or `bind=ip_address` (or `listen`)

That doesn't clarify much?

"listening" is really about accepting incoming connections? i.e. not typically done when doing dns lookups? it gets more confusing here...

> This is the question of **routing** DNS traffic.

Then assign the DNS servers to the right interfaces, resolved supports that, NM can do that too. And make sure all traffic you want routed to teh default connection is placed there via a routing domain.

Anyway, this is not a really the right place to discuss this. Please contact https://lists.freedesktop.org/mailman/listinfo/systemd-devel for this, as the functionality you appear to be looking for (but it's not entirely clear to me) is already there, hence what you are looking for is just a fix for some misconfiguration. but that's a support thing, not something to cover in this bug and feature tracker. hence clsoing.

**Comment by birdie-github** [comment]
I'm using the Quad and Google DNS servers which are always in the WAN thus I cannot "assign" them to anything.

Looks like I will continue to struggle with DNS resolution given your response.

There are no "simple" solutions for routing just DNS traffic in Linux either. One could use nftables + iproute2 but that's quite complicated.

**Comment by birdie-github** [comment]
@poettering 

I'm not sure how this feature request is "misfiled".

It's filed against `systemd-resolved` and the issue concerns it. This daemon has no options for routing traffic.

**Comment by YHNdnzj** [comment]
As mentioned, resolved already supports using specific interface for outgoing requests. If this is about routing all requests to an interface, just set `Domains=~.` on it?

**Comment by poettering** [comment]
> I'm using the Quad and Google DNS servers which are always in the WAN thus I cannot "assign" them to anything.

In resolved DNS servers are generally assigned to an interface (there's a compat mode for globally configured DNS, but it's not what this is designed for). Thus, if you assign your VPN DNS to the VPN interfaces, and your other DNS servers to your WAN interface, the right things should happen.



> @poettering
> 
> I'm not sure how this feature request is "misfiled".
> 
> It's filed against `systemd-resolved` and the issue concerns it. This daemon has no options for routing traffic.

There is no bug here, or feature request. Your usecase seems to be perfectly well covered already, but simply not configured properly, which makes this a support case. Hence, please contact the systemd mailing list, this issue tracker is the wrong place for support cases, the mailing list however is. Hence "misfiled".

> It's filed against `systemd-resolved` and the issue concerns it. This daemon has no options for routing traffic.

Of course it has: the interface you attach the DNS server to is the interface that is used for routing.
