### ISSUE TITLE
docs: org.freedesktop.timesync1 manpage is missing

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#34352]
### Component

systemd-timesync

### Problem

I was looking for the documentation for the `org.freedesktop.timedate1` D-Bus interface and couldn't find its manpage online: https://www.freedesktop.org/software/systemd/man/256/index.html

It looks like the corresponding `man/org.freedesktop.timesync1.xml` does not actually exist, yet.
(And sorry I don't have time to write one from scratch, but I can help proofreading/reviewing a PR.)

### Checked systemd version

256.6 (and `main` too)

**Comment by yuwata** [comment]
-> #34353.

**Comment by lucab** [comment]
@yuwata thanks for the quick PR!
