### ISSUE TITLE
systemd shows error after update

### ISSUE THREAD

**Issue by vcpd1** [systemd/systemd#34357]
### systemd version the issue has been seen with

systemd-256.6-1

### Used distribution

Arch Linux

### Linux kernel version used

6.10.9-zen1-2-zen

### CPU architectures issue was seen on

x86_64

### Component

journalctl, systemd

### Expected behaviour you didn't see

No error at post-transaction hook output

### Unexpected behaviour you saw

After updating via `$ sudo pacman -Syu`, systemd package shows me an error:
```
Cannot set file attributes for '/var/log/journal', maybe due to incompatibility in specified attributes, previous=0x00000004, current=0x00000004, expected=0x00800004, ignoring.
Cannot set file attributes for '/var/log/journal/c28d5ddc7ad647d584992f79cdcaf32c', maybe due to incompatibility in specified attributes, previous=0x00000004, current=0x00000004, expected=0x00800004, ignoring.
Cannot set file attributes for '/var/log/journal/remote', maybe due to incompatibility in specified attributes, previous=0x00000004, current=0x00000004, expected=0x00800004, ignoring.
```

### Steps to reproduce the problem

- Install/update systemd-256.6-1 via `$ sudo pacman -Syu systemd`
- Latest linux-zen kernel from official Arch Linux repo
- Have this packages installed:

> $ pacman -Q | grep systemd          
> lib32-systemd 256.6-1
> systemd 256.6-1
> systemd-libs 256.6-1
> systemd-sysvcompat 256.6-1
> systemd-ukify 256.6-1

- System has btrfs, with LVM and LUKS encryption:
```
- NAME                     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
zram0                    253:0    0     4G  0 disk  [SWAP]
nvme0n1                  259:0    0 953,9G  0 disk  
├─nvme0n1p1              259:1    0     1G  0 part  /boot
└─nvme0n1p2              259:2    0 952,9G  0 part  
  └─cryptlvm             254:0    0 952,9G  0 crypt 
    └─ArchinstallVg-root 254:1    0 912,8G  0 lvm   /var/log
                                                    /home
                                                    /var/cache/pacman/pkg
                                                    /.snapshots
                                                    /

```
- Secure Boot enabled and configured via sbctl as well as tpm2 via tpm2-tss

**Comment by yuwata** [comment]
As explained in the log, your filesystem does not support an attribute, I guess NOCOW. And as said, that can be ignored. Also, there is nothing we can do.
