### ISSUE TITLE
systemd-confext does not preserve nested bind mounts

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#34365]
### systemd version the issue has been seen with

256

### Used distribution

Fedora Rawhide

### Linux kernel version used

N/A

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

When booting a /usr only system with a confext for /etc, /etc/machine-id is initialized after the system finishes booting up.

### Unexpected behaviour you saw

When booting a /usr only system with a confext for /etc, /etc/machine-id still contains "uninitialized" after the system finishes booting up. 

```
#  ~ systemctl status systemd-machine-id-commit
○ systemd-machine-id-commit.service - Save Transient machine-id to Disk
     Loaded: loaded (/usr/lib/systemd/system/systemd-machine-id-commit.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
  Condition: start condition unmet at Wed 2024-09-11 12:52:28 CEST; 14min ago
             └─ ConditionPathIsMountPoint=/etc/machine-id was not met
       Docs: man:systemd-machine-id-commit.service(8)
```

This happens because pid 1 makes /etc/machine-id a mount from /run/machine-id and confext puts an overlayfs on top of /etc which hides all nested bind mounts, causing systemd-machine-id-commit to never run.

We probably want to mount over all existing nested mounts to the new overlayfs.

### Steps to reproduce the problem

Boot a /usr only system in first boot mode with a confext for /etc in /usr/lib/confexts.

**Comment by poettering** [comment]
Fixed by ddbddebe0cc5edcf3d0fbc82ba5850e45925e8ae I guess. Closing
