### ISSUE TITLE
systemd.netdev does not allow to configure the host interface for a sit tunnel

### ISSUE THREAD

**Issue by klaernie** [systemd/systemd#3437]
### Submission type
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 229
### Used distribution

> Debian testing
### Description

Due to a outage on my DSL I have to resort to an UMTS uplink to gain internet connectivity for my network. My UMTS provider sadly does not allow making ingress connections, so I have to resort to drastic measures to connect my home network with a proper public IP (v4 and v6).

I have a vserver running in a datacenter, that has a spare public IPv4 address, that I routed via OpenVPN to my server at home (the machine running systemd in question). This way I have an interface `tun1` configured with my public IPv4. This is, while technically fully debatable, working fine.

To now connect my tunnelbroker.net IPv6 tunnel I went on with adjusting my `/etc/systemd/network/50-he-tunnel.netdev`:

```
[NetDev]
Name=he-ipv6
Kind=sit
MTUBytes=1480

[Tunnel]
Local=178.77.94.49
Remote=216.66.86.114
TTL=255
```

While this works fine if I am running with my internal IPv4 (`Local=172.16.0.253`) when running via my regular uplink, it does not work when running with my crooked workaround. I can create the device manually using a modified version of the script hurricane electric provides as configuration example. Notice the `dev tun1` part of the tunnel creation.

```
ip tunnel add he-ipv6 mode sit remote 216.66.86.114 local 178.77.94.49 ttl 255 dev tun1
ip link set he-ipv6 up
ip addr add 2001:470:6c:15a::2/64 dev he-ipv6
ip route add ::/0 dev he-ipv6
```

This creates an interface that is listening for the encapsulated traffic on the public IPv4 assigned to `tun1`:

```
hive(pts/4)[master!] /etc/openvpn % ip addr show he-ipv6
24: he-ipv6@tun1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1
```

In comparison the configuration created by networkd shows that the interface is bound to `br0`:

```
hive(pts/4)[master!] /etc/openvpn % ip addr show he-ipv6
23: he-ipv6@br0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1
```

I reread the `systemd.netdev` manpage multiple times, but did not find any option that would alter networkd's behaviour. Am I overlooking something or is this not intended to work?

Thanks, Andre

**Comment by poettering** [comment]
@ssahani something for you?

**Comment by tomty89** [comment]
@klaernie Are you missing something here or am I? Apparently you have a _.network_ file like this:

```
[Match]
Name=br0
[Network]
Tunnel=he-ipv6
```

so `he-ipv6@br0` would have been created?

If you want `he-ipv6@tun1`, you should have this instead:

```
[Match]
Name=tun1
[Network]
Tunnel=he-ipv6
```

See Example 6 in [systemd.network(5)](https://www.freedesktop.org/software/systemd/man/systemd.network.html).

**Comment by ssahani** [comment]
From the output it looks to me same conf suggested by @tomty89 . Just to be sure could you paste your confs please.

**Comment by klaernie** [comment]
sorry for the late reply, I actually missed that the `.network` file triggers the tunnel creation, so it was fixed by using `tun1.network` for this.
