### ISSUE TITLE
Incorrect SELinux label for `/usr` when using sysexts

### ISSUE THREAD

**Issue by travier** [systemd/systemd#34387]
### systemd version the issue has been seen with

systemd-256.5-1.fc41.x86_64

### Used distribution

Fedora 41

### Linux kernel version used

6.11.0-0.rc5.43.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysext

### Expected behaviour you didn't see

Merging sysexts should not impact the SELinux label of `/usr`.

### Unexpected behaviour you saw

On a Fedora CoreOS 41 system, I added a sysext and merged it. The resulting `/usr` mount is incorrectly labeled:

```
# ls -alhZ /usr/
total 76K
drwxr-xr-x.  1 root root unconfined_u:object_r:user_tmp_t:s0   60 Sep 12 10:48 .
drwxr-xr-x. 12 root root system_u:object_r:root_t:s0         4.0K Jan  1  1970 ..
drwxr-xr-x.  2 root root unconfined_u:object_r:user_tmp_t:s0   80 Sep 12 10:48 .systemd-sysext
drwxr-xr-x.  1 root root system_u:object_r:bin_t:s0            48 Aug 29 18:23 bin
drwxr-xr-x. 86 root root system_u:object_r:etc_t:s0          4.0K Jan  1  1970 etc
drwxr-xr-x.  2 root root system_u:object_r:usr_t:s0            27 Jan  1  1970 games
drwxr-xr-x.  2 root root system_u:object_r:usr_t:s0            27 Jan  1  1970 include
drwxr-xr-x.  1 root root system_u:object_r:lib_t:s0            58 Sep 12 09:39 lib
drwxr-xr-x. 42 root root system_u:object_r:lib_t:s0           20K Jan  1  1970 lib64
drwxr-xr-x. 30 root root system_u:object_r:bin_t:s0          1.9K Jan  1  1970 libexec
lrwxrwxrwx.  1 root root system_u:object_r:usr_t:s0            15 Jan  1  1970 local -> ../var/usrlocal
drwxr-xr-x.  2 root root system_u:object_r:bin_t:s0          9.6K Jan  1  1970 sbin
drwxr-xr-x. 87 root root system_u:object_r:usr_t:s0          1.7K Jan  1  1970 share
drwxr-xr-x.  4 root root system_u:object_r:usr_t:s0            63 Jan  1  1970 src
lrwxrwxrwx.  1 root root system_u:object_r:usr_t:s0            10 Jan  1  1970 tmp -> ../var/tmp
```

From my understanding of the code, it looks like systemd-sysexts creates `/run/systemd/sysext` (https://github.com/systemd/systemd/blob/main/src/sysext/sysext.c#L1805) and then sets up / merges sysext mounts form there (https://github.com/systemd/systemd/blob/main/src/sysext/sysext.c#L1497).

Thus it's likely that the SELinux contexts from there "leaks" to the final `/usr` mount.

The SELinux context matches the one in `/run/user/0/systemd/`:
```
# ls -alhdZ /run/user/0/systemd/
drwxr-xr-x. 5 root root unconfined_u:object_r:user_tmp_t:s0 140 Sep 12 10:27 /run/user/0/systemd/
```

### Steps to reproduce the problem

1. Boot a Fedora CoreOS 41 system. This might also be reproducible on a classic dnf Fedora 41 system but I've not checked yet.
2. Add a sysext
3. Run `systemd-sysext merge`
4. Run `ls -alZ /usr`

See:
- Fedora CoreOS: https://github.com/coreos/fedora-coreos-tracker/issues/1744
- A likely previous report of this issue: https://github.com/systemd/systemd/issues/31404

**Comment by travier** [comment]
One option would be to make sure that the SELinux labels of the files/directories created during the sysexts merging process are either:
- set to the default one from the policy for the final expected paths
- or set to the ones from the current system: `chcon --reference /usr /run/systemd/sysext/usr`

**Comment by travier** [comment]
A workaround for this issue is to let the `systemd-sysext.service` merge the sysexts instead of doing it manually as it will run under a "correct" SELinux context and will thus create the `/usr` mount point with something that is readable by most processes:

```
[root@cosa-devsh ~]# systemd-sysext unmerge
Unmerged '/usr'.

[root@cosa-devsh ~]# systemd-sysext status
HIERARCHY EXTENSIONS SINCE
/opt      none       -    
/usr      none       -    

[root@cosa-devsh ~]# ls -alhZ /usr/
total 100K
drwxr-xr-x. 12 root root system_u:object_r:usr_t:s0   224 Jan  1  1970 .
drwxr-xr-x. 12 root root system_u:object_r:root_t:s0 4.0K Jan  1  1970 ..
...

[root@cosa-devsh ~]# systemctl restart systemd-sysext.service 

[root@cosa-devsh ~]# systemd-sysext status
HIERARCHY EXTENSIONS SINCE                      
/opt      none       -                          
/usr      erofs      Thu 2024-09-12 11:37:27 UTC

[root@cosa-devsh ~]# ls -alhZ /usr/
total 76K
drwxr-xr-x.  1 root root system_u:object_r:tmpfs_t:s0   60 Sep 12 11:37 .
drwxr-xr-x. 12 root root system_u:object_r:root_t:s0  4.0K Jan  1  1970 ..
drwxr-xr-x.  2 root root system_u:object_r:tmpfs_t:s0   80 Sep 12 11:37 .systemd-sysext
...
```

**Comment by bluca** [comment]
Shouldn't the policy be changed to ensure /run/systemd/sysext is created with the expected label instead?

**Comment by travier** [comment]
We can probably do that as well. I'll give it a try. Is `/run/systemd/sysext` the directory that ends up being used as `/usr`?

**Comment by bluca** [comment]
it should be `/run/systemd/sysext/overlay/usr` and `/run/systemd/sysext/overlay/opt`  and  `/run/systemd/sysext/overlay/etc`  respectively for the default hierarchies we handle

**Comment by poettering** [comment]
hmm, we do have code to apply labels based on a future path to some inode we create. I think it would make sense to use that here so that the policy can stay simple.

**Comment by thkukuk** [comment]
We run into the same problem on openSUSE MicroOS.
