### ISSUE TITLE
Allow passing arbitrary file descriptors to transient unit

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#34396]
We already have `StandardInputFileDescriptor` and friends to pass in file descriptors for 0, 1 and 2. We already have `OpenFile=` to open arbitrary files and pass those file descriptors. The final missing piece is something like `ExtraFileDescriptors=` or so that would allow passing in arbitrary file descriptors when starting a service. 

This would be a `StartTransientUnit` property that would take an array of named file descriptors that are passed to the service via sd-notify.

**Comment by poettering** [comment]
yeah, makes sense.
