### ISSUE TITLE
[journald, feature request] Add ForwardToRemoteSyslog=no|host:port directive

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#344]
I've pratical task to forward logs from systemd-based linux (OpenSUSE 13.2, systemd-210) to _remote_ syslog-server (FreeBSD), which forwards it to Zabbix. But there is a problem -  ForwardToSyslog=yes|no option in /etc/systemd/journald.conf forwards logs to installed (r-)syslog(-ng) locally. This means that I have to install (r-)syslog(-ng) in parallel to journald and then forward logs to remote (r-)syslog(-ng) from my local (r-)syslog(-ng). But there is one more problem:
///
k_mikhail@linux-mk500:~> sudo zypper in rsyslog
.....
Trouble: systemd-logger-210-25.16.1.x86_64 conflicts with namespace:otherproviders(syslog), ... rsyslog-8.4.2-3.1.x86_64
 Solution 1: remove systemd-logger-210-25.16.1.x86_64
 Solution 2: do not install rsyslog-8.4.2-3.1.x86_64

Choose the number or cancel [1/2/c](c): c
///

The same is when try to install syslog, syslog-ng.

So, I can't install (r-)syslog(-ng) locally. And have no possilibity and time to look for another distro, where journald doesn't conflict with local (r-)syslog(-ng). Possibly, the most simple way to solve this task (or to workaround) is to add ForwardToRemoteSyslog=no|host:port directive to journald.conf.

Please, conside. Thanks!

**Comment by kaysievers** [comment]
I have no idea what systemd-logger is and why it conflicts with rsyslog. Care to explain what is causing the issue on SUSE?

**Comment by kaysievers** [comment]
Seems that is just a SUSE dummy package. Whatever problem they try to solve with that package, I expect you can safely remove it. I am only guessing, better check if the installed package contains any files, I don't see any.

%package logger
Summary:        Journal only logging
Conflicts:      otherproviders(syslog)

%description logger
This package marks the installation to not use syslog but only the journal.

**Comment by hwinkel** [comment]
there was already a patch  for remote syslog forward and a activity to have a syslog forward daemon.

**Comment by kaysievers** [comment]
@hwinkel, we decided against any native syslog support. There will be no such tool in systemd, it can be provided by a different project though.
