### ISSUE TITLE
Add `fortnightly` as `systemd.time` shorthand for 2 weeks

### ISSUE THREAD

**Issue by mooreye** [systemd/systemd#34406]
### Component

systemd

### Is your feature request related to a problem? Please describe

Since `quarterly` and `semiannually` already exist, it would be nice to also add `fortnightly` which equals 2 weeks, or 14 days.

### Describe the solution you'd like

Add `fortnightly` shorthand for 2 weeks for `systemd.time` notation

### Describe alternatives you've considered

none

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by poettering** [comment]
Duplicate of #6024
