### ISSUE TITLE
systemctl list-services

### ISSUE THREAD

**Issue by skynet-gh** [systemd/systemd#34411]
### Component

systemctl

### Is your feature request related to a problem? Please describe

For consistency, I'd expect that since I can run `systemctl list-timers`, `systemctl list-sockets`, and others, that I'd be able to run `systemctl list-services`, since service units are a very common unit type.

### Describe the solution you'd like

The command `systemctl list-services` is added which lists service units. Consistent with the other `systemctl list-*` commands for other unit types.

### Describe alternatives you've considered

Currently this is done by `systemctl list-units --type=service`.

### The systemd version you checked that didn't have the feature you are asking for

255

**Comment by dtardon** [comment]
> For consistency, I'd expect that since I can run `systemctl list-timers`, `systemctl list-sockets`, and others, that I'd be able to run `systemctl list-services`, since service units are a very common unit type.

But those commands _do not_ list units of a given type. They list _artifacts_ defined by those units: sockets, timers, automounts, watched paths. The unit is just an additional piece of information in their output. IOW, they answer question like "Which paths are watched by systemd units?", not "Which `path` units are there?".

If you want to list units of type `X`, use `systemctl list-units --type=X` or `systemctl list-units *.X`.

**Comment by YHNdnzj** [comment]
Yes. We have dedicated list-* verbs for units that have additional info to show. services don't fall into that category, and list-units certainly works well enough. Closing.
