### ISSUE TITLE
machinectl enable non-unique?

### ISSUE THREAD

**Issue by andrewdunndev** [systemd/systemd#3442]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

```
[root@orolo machines]# systemctl --version
systemd 230
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
### Used distribution

```
[root@orolo machines]# uname -r
4.5.4-1-ARCH

```
### In case of bug report: Expected behaviour you didn't see

New to machinectl/systemd-nspawn, expected behavior when enabling a container is that you would get a container unique unit file. The current behavior outlined in next section. I'm trying to create several containers in `/var/lib/machines` and have them all start at boot time with different services.
### In case of bug report: Unexpected behaviour you saw

```
[root@orolo machines]# machinectl enable murmur 
Created symlink /etc/systemd/system/machines.target.wants/systemd-nspawn@murmur.service → /usr/lib/systemd/system/systemd-nspawn@.service.
```

This can't be the right behavior because when one would need to specifiy machine specific things, such as binds, they would ultiamtely be editing the symlinked `/usr/lib/systemd/system/systemd-nspawn@.service`. 

I guess I'd expect that `machinectl enable <machinename>` would create a new file based on some sort of templating where the user could then add whatever arguments (e.g. filesystem binds) that they needed.
### In case of bug report: Steps to reproduce the problem

```
cd /var/lib/machines
mkdir murmur
pacstrap -c -d murmur/ base vim bash-completion
machinectl start murmur
machinectl shell murmur
# set the root password
machinectl enable murmur
```

**Comment by poettering** [comment]
Use ".nspawn" files to configure container settings, it's much more powerful

(and if you really need to change the unit file, there are always .d/ drop-ins, which allow you to make minimal changes without replacing the unit file wholesale.)

**Comment by poettering** [comment]
See https://www.freedesktop.org/software/systemd/man/systemd.nspawn.html# for details on .nspawn files.
