### ISSUE TITLE
Networkd: `SYSTEMD_LOG_LEVEL=debug` does not provide enough information to diagnose network manager conflicts

### ISSUE THREAD

**Issue by littlebenlittle** [systemd/systemd#34436]
### systemd version the issue has been seen with

256

### Used distribution

Manjaro 24.0.8

### Linux kernel version used

6.6.47-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

With

```
# /etc/systemd/system/systemd-networkd.service.d/10-debug.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

I expect to be able to diagnose why `networkd` sets device state to "unmanaged".

### Unexpected behaviour you saw

With `journalctl -u systemd-networkd | grep enp2s0` I get

```
enp2s0: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
enp2s0: Saved original MTU 1500 (min: 68, max:9194)
enp2s0: Saved permanent hardware address: 00:00:de:ad:be:ef
enp2s0: Saved IPv6 link-local address generation mode: eui64
enp2s0: Flags change: +MULTICAST +BROADCAST
enp2s0: udev initialized link
enp2s0: Found driver: r8169
enp2s0: Link state is up-to-date
enp2s0: State changed: pending -> initialized
enp2s0: Unmanaging interface
enp2s0: State changed: initialized -> unmanaged
```

which does not indicate why device state has been set to unmanaged.

**Comment by yuwata** [comment]
When an interface enters the unmanaged state, there are only two possibilities:
- no matching .network file found for the interface,
- found a matching .network file with Unmanaged=yes.

**Comment by yuwata** [comment]
Improvement will be waiting in #34440.

**Comment by littlebenlittle** [comment]
I think the additional debug info will be helpful, thank you for near-immediate response.

Somewhat of a piggyback issue, but if those are the only two cases then this is unexpected behavior. I have

```
# /etc/systemd/network/00-wired.network
[Match]
Name=en*

[Network]
DHCP=yes
```

and `networkctl` prints

```
IDX LINK   TYPE    OPERATIONAL SETUP
  1 lo     looback carrier     unmanaged
  2 enp2s0 ether   off         unmanaged
```

**Comment by yuwata** [comment]
No log message about the .network from networkd ? Maybe permission or SELinux issue ?

**Comment by littlebenlittle** [comment]
Yep had umask 0077 for root 🤦‍. Good call.

Maybe another log message for unreadable .network files?

**Comment by yuwata** [comment]
> Yep had umask 0077 for root 🤦‍. Good call.

Yay!

> Maybe another log message for unreadable .network files?

Will be added in #34440. Thank you!
