### ISSUE TITLE
Tests fail if path to systemd repo contains spaces

### ISSUE THREAD

**Issue by Jayman2000** [systemd/systemd#34459]
### systemd version the issue has been seen with

257~devel-gd80a904

### Used distribution

Fedora 40

### Linux kernel version used

6.10.9-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

tests

### Expected behaviour you didn't see

The tests succeed regardless of what the path to the systemd repo is.

### Unexpected behaviour you saw

Six of the tests fail if the path to the systemd repo contains spaces. Specifically, these tests fail:

- systemd:udev / test-udev-spawn
- systemd:test / test-compress
- systemd:sysusers / test-sysusers
- systemd:test / test-compare-versions
- systemd:fstab / test-fstab-generator
- systemd:kernel-install / test-kernel-install

### Steps to reproduce the problem

1. Clone the systemd repo, and make sure that the path to the clone contains at least one space:

    ```bash
    git clone https://github.com/systemd/systemd 'path that contains spaces'
    ```

2. Change directory into your newly created clone:

    ```bash
    cd 'path that contains spaces'
    ```

3. Make sure that you have all the build dependencies installed.

4. Build systemd and try running its tests:

    ```bash
    meson setup build
    ninja -C build
    meson test -C build
    ```

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/Jayman2000/016e355b92bed2d25e23a847a973c86c

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #34464.
