### ISSUE TITLE
systemd doesn't see devices from udev

### ISSUE THREAD

**Issue by jeras** [systemd/systemd#3446]
### Submission type
- [ ] Bug report
### systemd version the issue has been seen with

systemd 229
### Used distribution

Ubuntu base 16.04 (armhf)
### Behaviour

FSTAB rules for VFAT did not work properly, but the issue is probably not limited to VFAT, it also seems another generated unit was corrupted in the process. Here are more details from a longer report:

First I get the next during the boot process:

```
[ TIME ] Timed out waiting for device dev-mmcblk0p1.device.
[DEPEND] Dependency failed for /opt/redpitaya.
[DEPEND] Dependency failed for Local File Systems.
[DEPEND] Dependency failed for /boot.
[DEPEND] Dependency failed for File System Check on /dev/mmcblk0p1.
[ TIME ] Timed out waiting for device dev-ttyPS0.device.
```

I tried to fix the TTY issue by following this post, there was a change but it did not help:
http://askubuntu.com/questions/76363...-tar-gz/766444

```
ln -s /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@ttyPS0.service
```

Then I enabled verbosity for systemd, and copied logs to the SD card using:

```
dmesg > dmesg.log
journalctl -xb > journalctl.log
```

And this are the relevant lines from the log:

```
$ grep ttyPS0 dmesg.log 
[    0.000000] Kernel command line: console=ttyPS0,115200 root=/dev/mmcblk0p2 ro rootfstype=ext4 earlyprintk rootwait uio_pdrv_genirq.of_id=generic-uio loglevel=7 dyndbg=file axidmatest.c +p systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M
[    0.314167] xuartps e0000000.serial: ttyPS0 at MMIO 0xe0000000 (irq = 59, base_baud = 6249999) is a xuartps
[    0.775803] console [ttyPS0] enabled
[    2.400282] systemd-getty-generator[659]: Automatically adding serial getty for /dev/ttyPS0.
[    2.777643] systemd[1]: serial-getty@ttyPS0.service: Installed new job serial-getty@ttyPS0.service/start as 63
[    2.778090] systemd[1]: getty@ttyPS0.service: Installed new job getty@ttyPS0.service/start as 59
[    2.778560] systemd[1]: dev-ttyPS0.device: Installed new job dev-ttyPS0.device/start as 65
[   92.876625] systemd[1]: dev-ttyPS0.device: Job dev-ttyPS0.device/start timed out.
[   92.876655] systemd[1]: dev-ttyPS0.device: Job dev-ttyPS0.device/start finished, result=timeout
[   92.876716] systemd[1]: Timed out waiting for device dev-ttyPS0.device.
[   92.906612] systemd[1]: serial-getty@ttyPS0.service: Job serial-getty@ttyPS0.service/start finished, result=dependency
[   92.906672] systemd[1]: Dependency failed for Serial Getty on ttyPS0.
[   92.926620] systemd[1]: serial-getty@ttyPS0.service: Job serial-getty@ttyPS0.service/start failed with result 'dependency'.
[   92.926682] systemd[1]: dev-ttyPS0.device: Job dev-ttyPS0.device/start failed with result 'timeout'.
[   93.017933] systemd[1]: getty@ttyPS0.service: Job getty@ttyPS0.service/start finished, result=canceled
[   93.017997] systemd[1]: getty@ttyPS0.service: Installed new job getty@ttyPS0.service/stop as 99
[   93.336617] systemd[1]: getty@ttyPS0.service: Job getty@ttyPS0.service/stop finished, result=done
[   93.336674] systemd[1]: Stopped Getty on ttyPS0.
```

```
$ grep mmcblk0p1 dmesg.log 
[    2.433762] systemd-fstab-generator[658]: Found entry what=/dev/mmcblk0p1 where=/boot type=vfat nofail=no noauto=no
[    2.434063] systemd-fstab-generator[658]: Found entry what=/dev/mmcblk0p1 where=/opt/redpitaya type=vfat nofail=no noauto=no
[    2.694773] systemd[1]: dev-mmcblk0p1.mount: Failed to load configuration: No such file or directory
[    2.776662] systemd[1]: systemd-fsck@dev-mmcblk0p1.service: Installed new job systemd-fsck@dev-mmcblk0p1.service/start as 12
[    2.777822] systemd[1]: dev-mmcblk0p1.device: Installed new job dev-mmcblk0p1.device/start as 15
[    2.778987] systemd[1]: dev-mmcblk0p1.mount: Collecting.
[   92.926830] systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start timed out.
[   92.926857] systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start finished, result=timeout
[   92.926910] systemd[1]: Timed out waiting for device dev-mmcblk0p1.device.
[   92.956600] systemd[1]: systemd-fsck@dev-mmcblk0p1.service: Job systemd-fsck@dev-mmcblk0p1.service/start finished, result=dependency
[   92.956658] systemd[1]: Dependency failed for File System Check on /dev/mmcblk0p1.
[   93.019633] systemd[1]: systemd-fsck@dev-mmcblk0p1.service: Job systemd-fsck@dev-mmcblk0p1.service/start failed with result 'dependency'.
[   93.036666] systemd[1]: dev-mmcblk0p1.device: Job dev-mmcblk0p1.device/start failed with result 'timeout'.
```

I can manually get network up with:

```
ip link set eth0 up
ip addr add 192.168.178.77/24 broadcast 192.168.178.255 dev eth0
ip route add default via 192.168.178.0
```

I can mount the SD card FAT partition, as the device exists:

```
# ls -la /dev/mmcblk0p1
brw------- 1 root root 179, 1 Jan  1  1970 /dev/mmcblk0p1
mount -t vfat -o umask=000 /dev/mmcblk0p1 /boot
```

And the serial console device also exists:

```
# ls -la /dev/ttyPS0
crw------- 1 root root 248, 0 Feb 11 17:27 /dev/ttyPS0
```
### How to reproduce, possible sources

For now it seems the issue was the Systemd translation of fstab into units, in fstab VFAT was mounted with options `ro,default` and it seems this created broken *.mount units, it also seems the same issue propagated to the `ttyPS0` unit.

I now wrote mount options as `default,ro` and it seems to work now, I also had to remove the `ttyPS0` symbolic link "fix?", since it caused console instability (repeated text, logouts).

It might be that `default` translates into its basic options, among them `rw`, and this conflicts with `ro` beeing defined before `default`.

**Comment by jeras** [comment]
Here is the affected fstab:
https://github.com/RedPitaya/RedPitaya/blob/release-v0.95/OS/debian/overlay/etc/fstab

I forgot to mention that there were no issues with Systemd from Debian Jessie.

**Comment by arvidjaar** [comment]
What you see is just a symptom. Systemd relies on udev to announce availability of device. Start with checking udev database (udevadm info --export-db) whether it contains entry for mmcblk0p1. Does it have SYSTEMD_READY=0 by any chance? Could you make output of udevadm available?

And, BTW, you attempt to mount the same device on two different mount points. Is it intentional?

**Comment by jeras** [comment]
Yes, mounting a device twice is intentional.

I do not think this issue has anything to do with UDEV, since everything works properly as soon as I change mount options in fstab from `ro,default` to `default,ro`.

I do not know about `SYSTEMD_READY=0` but you can see `TAGS=:systemd:`.

```
# udevadm info --export-db
...
P: /devices/soc0/amba/e0100000.sdhci/leds/mmc0::
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/leds/mmc0::
E: SUBSYSTEM=leds

P: /devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0
E: SUBSYSTEM=mmc_host

P: /devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4
E: DRIVER=mmcblk
E: MMC_NAME=NCard
E: MMC_TYPE=SD
E: MODALIAS=mmc:block
E: SUBSYSTEM=mmc

P: /devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0
N: mmcblk0
S: disk/by-id/mmc-NCard_0x21a2bdc3
S: disk/by-path/platform-e0100000.sdhci
E: DEVLINKS=/dev/disk/by-id/mmc-NCard_0x21a2bdc3 /dev/disk/by-path/platform-e0100000.sdhci
E: DEVNAME=/dev/mmcblk0
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0
E: DEVTYPE=disk
E: ID_NAME=NCard
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=6e2997fb
E: ID_PATH=platform-e0100000.sdhci
E: ID_PATH_TAG=platform-e0100000_sdhci
E: ID_SERIAL=0x21a2bdc3
E: MAJOR=179
E: MINOR=0
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=4336883

P: /devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/mmcblk0p1
N: mmcblk0p1
S: disk/by-id/mmc-NCard_0x21a2bdc3-part1
S: disk/by-path/platform-e0100000.sdhci-part1
S: disk/by-uuid/E5BA-B3BC
E: DEVLINKS=/dev/disk/by-id/mmc-NCard_0x21a2bdc3-part1 /dev/disk/by-path/platform-e0100000.sdhci-part1 /dev/disk/by-uuid/E5BA-B3BC
E: DEVNAME=/dev/mmcblk0p1
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/mmcblk0p1
E: DEVTYPE=partition
E: ID_FS_TYPE=vfat
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=E5BA-B3BC
E: ID_FS_UUID_ENC=E5BA-B3BC
E: ID_FS_VERSION=FAT16
E: ID_NAME=NCard
E: ID_PART_ENTRY_DISK=179:0
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=8192
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_SIZE=241664
E: ID_PART_ENTRY_TYPE=0xe
E: ID_PART_ENTRY_UUID=6e2997fb-01
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=6e2997fb
E: ID_PATH=platform-e0100000.sdhci
E: ID_PATH_TAG=platform-e0100000_sdhci
E: ID_SERIAL=0x21a2bdc3
E: MAJOR=179
E: MINOR=1
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=4531570

P: /devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/mmcblk0p2
N: mmcblk0p2
S: disk/by-id/mmc-NCard_0x21a2bdc3-part2
S: disk/by-path/platform-e0100000.sdhci-part2
S: disk/by-uuid/d63f442e-fa91-4878-bf40-71cbe38fed1c
E: DEVLINKS=/dev/disk/by-path/platform-e0100000.sdhci-part2 /dev/disk/by-uuid/d63f442e-fa91-4878-bf40-71cbe38fed1c /dev/disk/by-id/mmc-NCard_0x21a2bdc3-part2
E: DEVNAME=/dev/mmcblk0p2
E: DEVPATH=/devices/soc0/amba/e0100000.sdhci/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/mmcblk0p2
E: DEVTYPE=partition
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=d63f442e-fa91-4878-bf40-71cbe38fed1c
E: ID_FS_UUID_ENC=d63f442e-fa91-4878-bf40-71cbe38fed1c
E: ID_FS_VERSION=1.0
E: ID_NAME=NCard
E: ID_PART_ENTRY_DISK=179:0
E: ID_PART_ENTRY_NUMBER=2
E: ID_PART_ENTRY_OFFSET=249856
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_SIZE=6918144
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_UUID=6e2997fb-02
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=6e2997fb
E: ID_PATH=platform-e0100000.sdhci
E: ID_PATH_TAG=platform-e0100000_sdhci
E: ID_SERIAL=0x21a2bdc3
E: MAJOR=179
E: MINOR=2
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=4435774
...
```

**Comment by poettering** [comment]
Does your kernel have CONFIG_FHANDLE set? If not, set it, it should fix your issue. 

Please verify the requirements from README regarding your local system and kernel options. Thanks.

**Comment by jeras** [comment]
I am using the 4.4 kernel from Xilinx with some extra patches to devicetree code, I checked the mentioned config option and it is active:
https://github.com/Xilinx/linux-xlnx/blob/master/arch/arm/configs/xilinx_zynq_defconfig
Our additions to this configuration only disable a couple of drivers, and enable many.

```
...
-CONFIG_MARVELL_PHY=y
-CONFIG_VITESSE_PHY=y
+CONFIG_MARVELL_PHY=n
+CONFIG_VITESSE_PHY=n
...
+CONFIG_RTL_CARDS=n
...
```

I have not checked the readme file yet.

**Comment by poettering** [comment]
I appears that systemd on your system won't notice the relevant devices to appear, hence a lot of your stuff simply times out. If it's not the CONFIG_FHANDLE issue and the devices you have do carry the "systemd" tag in udev I don't really have much of a suggestion what might be the problem here. Does "systemctl" show any .device units pop up at all? If not, then it appears that systemd doesn't see any devices appear at all, and there's something wrong with the communication between udev and systemd there...

**Comment by jeras** [comment]
Hi, I will try to reproduce the issue by reverting back fstab, so I will be able to give a more detailed report.

**Comment by jeras** [comment]
I am unable to reproduce the issue now, so I will assume something else went wrong. I will close this bug now, and only reopen it if I will be able to reproduce it. Thanks for your help.

**Comment by jeras** [comment]
It seems that the cause was missing the `udev` package on the Ubuntu base 16.04 image.

I rebuild my image from scratch and the issue resurfaced, I attempted changes to fstab and to ttyPS0 unit links, but it did not help. So I went through the shell history and found `udev` was installed to get some debug tools. I installed it again on the clean system, and now devices are properly present during boot.

**Comment by ghost** [comment]
What was your process in getting udev installed? I encountered the very same issue.

Thanks!

**Comment by jeras** [comment]
apt-get -y install udev

I think nothing else was needed, at least I do not remember anything else among all the attempts to fix this.

**Comment by ghost** [comment]
You did this on the Red Pitaya I presume during the OS build process?

**Comment by jeras** [comment]
yes, it is performed by this script:
https://github.com/RedPitaya/RedPitaya/blob/master/OS/debian/ubuntu.sh

**Comment by ghost** [comment]
Thanks this fixed my issue as well. Very helpful.

**Comment by wferi** [comment]
Since this issue wasn't properly solved, I assume I hit this one today. A casual reboot ended up in emergency mode under systemd 232-19 (Debian stretch) due to

    Started udev Kernel Device Manager.
    [...]
    dev-mapper-gum\x2dswap.device: Job dev-mapper-gum\x2dswap.device/start timed out.

and similar messages for all other partitions and their dire consequences leading up to

    local-fs.target: Job local-fs.target/start failed with result 'dependency'.

In the emergency shell, `systemctl` showed only my root `.device` unit, and even that with *tentative* status. At the same time, the device links were present in `/dev/mapper`, and only `systemd-tmpfiles-setup.service` was in failed state (as far as I remember). So it seems there was some problem with the systemd-udev communication, or the LVM2 metadata daemon interfered with udev, or I don't know. A simple reboot resolved the problem, and then I rebooted this VM several times, but couldn't reproduce the issue. Unusual races are more than possible in this shared virtualization environment (mostly due to erratic disk access latencies). I saved the `journalctl` output in the emergency shell, I can provide that if needed.

**Comment by mbravorus** [comment]
Hit exact same problem today with Debian jessie (8.7), systemd package version 215-17+deb8u6

System boots as normal, times out waiting for LVM (as dev mapper or by-uuid) devices, drops into emergency shell. If allowed to continue, it mounts those devices as per fstab, but the system is in unusable state as network subsystem is not up and the only access is via IP/KVM or direct physical console

udev package is in place (exactly the same package version as systemd itself)

affected devices are present in udev db and do NOT have SYSTEMD_READY attribute at all but do have :systemd: tag

The problem was *solved* after I spotted a weird error in journalctl output saying that systemctl-udev was "unable to rename eth0 to eth2: Success". Apparently during maintenance two NICs were swapped around, thus generating conflicting records in /etc/udev/rules.d/70-presistent-net.rules

After deleting this file and rebooting everything was magically all right.

The takeaway is:
- error messages saying "unable to do X: Success" shouldn't exist albeit maybe in Windows 95
- the whole systemd<->udev communication shouldn't hang up without any explanation because of conflicting entries in udev rules, or should at the very least generate relevant errors

**Comment by duanyao** [comment]
I hit this problem too and can reproduce easily.

Hardware: Lenovo V470 laptop, Core i5 2450M, 500GB HDD
OS: Deepin Linux 15.4, AMD64
Kernel: 4.9.8-5
systemd: 231-1
udev: 231-1
Partition type: GPT, no fancy things like RAID, LVM, encryption.

/etc/fstab:
```
LABEL=SYSL	/         	ext4	rw,relatime,data=ordered,x-systemd.device-timeout=1 	0	1
LABEL=DATA	/media/DATA	ntfs-3g	defaults,x-systemd.device-timeout=20			0	0
LABEL=ROOT	/media/ROOT	ext4	rw,relatime,data=ordered,x-systemd.device-timeout=10	0	2
LABEL=ESPL	/media/ESPL	vfat	defaults,umask=0000,noauto	0	0
```

If I set `x-systemd.device-timeout` to 3(s) for `LABEL=DATA` or `LABEL=ROOT`, they would timeout during boot. The error log looks like:
```
$sudo journalctl -a | grep "ROOT\.device"

6月 01 15:17:25 duanyao-laptop systemd[1]: dev-disk-by\x2dlabel-ROOT.device: Job dev-disk-by\x2dlabel-ROOT.device/start timed out.
6月 01 15:17:25 duanyao-laptop systemd[1]: Timed out waiting for device dev-disk-by\x2dlabel-ROOT.device.
6月 01 15:17:25 duanyao-laptop systemd[1]: dev-disk-by\x2dlabel-ROOT.device: Job dev-disk-by\x2dlabel-ROOT.device/start failed with result 'timeout'.
```
If I set `x-systemd.device-timeout` to 10~20(s), the errors disappear. However, I didn't notice such long delay during boot.

It seems `x-systemd.device-timeout` has little effect on the root partition(LABEL=SYSL); it never fails.

**Comment by duanyao** [comment]
Here is a doc from SUSE on this problem, which also suggests increasing `x-systemd.device-timeout` as a workaround:
https://www.suse.com/support/kb/doc/?id=7018491

**Comment by wferi** [comment]
@duanyao, you seem describe the documented timeout behavior, not a bug. This issue is about systemd device units not appearing after an arbitrarily long time, long after udev created the corresponding device nodes/links and settled.

**Comment by duanyao** [comment]
@wferi I think the bug is: systemd gives up too quickly, before the specified `x-systemd.device-timeout` elapses. I have to specify 10~20s to avoid timeout, but have never noticed such long delay during boot. Do you know how to tell the actual time spent by systemd waiting for the devices? What is the default value of `x-systemd.device-timeout`?

**Comment by seanmccully** [comment]
I have this issue, on arch linux, 
```
Aug 21 23:44:58 smccully-xps systemd[1]: nvme0n1p1.device: Job nvme0n1p1.device/start timed out.
Aug 21 23:44:58 smccully-xps systemd[1]: Timed out waiting for device nvme0n1p1.device.
-- Subject: Unit nvme0n1p1.device has failed
```

This device is clearly mounted, yet systemd can't seem to find it.

```
/dev/mapper/root  477G  386G   91G  82% /
tmpfs             7.8G   94M  7.7G   2% /dev/shm
tmpfs             7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1    511M  139M  373M  28% /boot
tmpfs             4.0G   26M  4.0G   1% /tmp
````

**Comment by flomabe** [comment]
Same issue here after upgrade to ubuntu 16.10.

First I thought it is related to luks+lvm but not even the unencrypted boot partition (sda1) will be mounted.
"Job dev-disk-by\x2uuid-longuuid.device/start failed with result 'timout'.
In my case "udevadm info --export-db" shows that "TAG=:systemd:" is NOT set for sda1. So does that mean /lib/udev/rules.d/99-systemd.rules is not executed? Or is something else removing the tag along the way? Notebook doesn't boot anymore. I'm stuck.

**Comment by mlybarger** [comment]
I  have systemd on gentoo.  236-r5.  When booting, all devices on /etc/fstab time out after 90 seconds. 
Error messages are here:

https://paste.pound-python.org/show/052zZS9XyVcS71ZB3LvB/ 

Relevent log snippet is: 

```
Mar 25 06:41:35 thunder systemd-networkd[2900]: enp3s0: Configured
Mar 25 06:42:49 thunder systemd[1]: dev-disk-by\x2duuid-448b28d1\x2def78\x2d4978\x2db596\x2d6b890e581fe9.device: Job dev-disk-by\x2duuid-448b28d1\x2def78\x2d4978\x2db596\x2d6b890e581fe9.device/start timed out.
Mar 25 06:42:49 thunder systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-448b28d1\x2def78\x2d4978\x2db596\x2d6b890e581fe9.device.
Mar 25 06:42:49 thunder systemd[1]: Dependency failed for /mnt/media.
Mar 25 06:42:49 thunder systemd[1]: Dependency failed for Local File Systems.
Mar 25 06:42:49 thunder systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
Mar 25 06:42:49 thunder systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
Mar 25 06:42:49 thunder systemd[1]: mnt-media.mount: Job mnt-media.mount/start failed with result 'dependency'.
Mar 25 06:42:49 thunder systemd[1]: Dependency failed for File System Check on /dev/disk/by-uuid/448b28d1-ef78-4978-b596-6b890e581fe9.
Mar 25 06:42:49 thunder systemd[1]: systemd-fsck@dev-disk-by\x2duuid-448b28d1\x2def78\x2d4978\x2db596\x2d6b890e581fe9.service: Job systemd-fsck@dev-disk-by\x2duuid-448b28d1\x2def78\x2d4978\x2db596\x2d6b890e581fe9.service/start failed with result 'dependency'.

```
/etc/fstab is:
```
UUID=66fbfe7f-f386-4ddb-a86f-f58cf68e601a	/home	ext4	defaults 1 2 
UUID=40c8170f-4e52-4c38-8c8a-639c50e98f0a	/ ext4 defaults,noatime 0 1 
UUID=448b28d1-ef78-4978-b596-6b890e581fe9	/mnt/media	ext4	noatime 0 2 
UUID=6DFD-A25A	/boot	vfat	noauto,noatime	1 0 
UUID=aef1ff74-30b7-41ec-a750-b3887de02098	none	swap	sw	0 0

```
