### ISSUE TITLE
The man page should explain about libraries for the `systemd-creds has-tpm2` output

### ISSUE THREAD

**Issue by friissoren** [systemd/systemd#34477]
### Component

systemd

### Is your feature request related to a problem? Please describe

Currently the `systemd-creds` man page, for the `has-tpm2` option, leave out the explanation for the `libraries` part that it prints.
The other other ones are at least mentioned (but could probably also need a bit more explanation?).

### Describe the solution you'd like

It would be very nice if there would be a hint about having to install the `tpm2-tools` package, if the libraries are reported to be missing.
I was unable to find any documentation or help about this with general internet searching. `libraries` is so generic that it is hard to figure out how to solve the missing dependency.

**Comment by yuwata** [comment]
Note, you can see what libraries loaded by the command by
```sh
SYSTEMD_LOG_LEVEL=debug systemd-creds has-tpm2
```

**Comment by yuwata** [comment]
#34481 will make the command shows what libraries are loaded or not.

**Comment by friissoren** [comment]
Thanks for your super fast response on this request. I am quite impressed and didn't expect anyone to react so fast.

I looked through the PR and clearly it will now provide more information about the libraries, but I am not sure if that helps too much from the end-user's perspective.

For people who are not intimately familiar with the internal intricacies of systemd, knowing whether any of libtss2-esys.so.0, libtss2-rc.so.0 or libtss2-mu.so.0 is present or not, won't help with figuring out how to get those installed on the system, if they are missing.

I was hoping that there simply could be a short note added to the documentation/man page, explaining that you need to install the Debian package `tpm2-tools`, to ensure the `libraries` field ends up being marked with a `+` from the output of `systemd-creds has-tpm2`.

**Comment by yuwata** [comment]
OK. Now, required libraries are listed in the man page. Package name depends on distribution. And, I am not sure debian's package manager, but Fedora/RHEL package manager supports e.g. `sudo dnf install /usr/lib64/libtss2-esys.so.0`. So, listing libraries should be OK, I think.
