### ISSUE TITLE
test-time-util fails with tzdata-2024b

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#34471]
CentOS CI started complaining when trying to upgrade to the latest tzdata on Arch Linux (2024b-2 ATTOW):

```
# SYSTEMD_LOG_LEVEL=debug build/test-time-util
...
/* test_format_timestamp_with_tz_one(Africa/Algiers) */
Africa/Algiers: tzname[0]=CET, tzname[1]=WEST
Successfully forked off '(sd-timestamp)' as PID 20542.
Skipping PR_SET_MM, as we don't have privileges.
(sd-timestamp) succeeded.
Assertion 'parse_timestamp(xx, &y) >= 0' failed at src/test/test-time-util.c:400, function test_format_timestamp_impl(). Aborting.
Aborted (core dumped)
```

**Comment by bluca** [comment]
No this looks like a different one

**Comment by bluca** [comment]
It's strange because I can't repro that in Debian with tzdata 2024b

**Comment by bluca** [comment]
Ah you need the tzdata-legacy package installed, then it fails

**Comment by bluca** [comment]
mktime is failing with EINVAL when called with this struct tm:

```
{tm_sec = 1, tm_min = 0, tm_hour = 0, tm_mday = 1, tm_mon = 0, tm_year = 70, tm_wday = 4, tm_yday = 0, 
  tm_isdst = 0, tm_gmtoff = 3600, tm_zone = 0x55555556caf0 "WEST"}
```

**Comment by bluca** [comment]
in parse_timestamp_impl() tm starts at:

`{tm_sec = 33, tm_min = 4, tm_hour = 15, tm_mday = 22, tm_mon = 9, tm_year = 124, tm_wday = 2, tm_yday = 295, 
  tm_isdst = 0, tm_gmtoff = 3600, tm_zone = 0x55555556caf0 "WEST"}`

then after `strptime(t, "%Y-%m-%d %H:%M:%S", &tm)` (which returns `""`) it becomes:

`{tm_sec = 1, tm_min = 0, tm_hour = 0, tm_mday = 1, tm_mon = 0, tm_year = 70, tm_wday = 4, tm_yday = 0, 
  tm_isdst = 0, tm_gmtoff = 3600, tm_zone = 0x55555556caf0 "WEST"}`

which is then rejected by mktime()

**Comment by yuwata** [comment]
@mrc0mmand tzdata-2024b is also coming to CentOS 9. Could you pin 2024a ?

**Comment by eworm-de** [comment]
Hmm, the initial report mentions the `tzdata` Arch Linux package. Wondering if I am supposed to see this when building packages... To date I did not.

**Comment by bluca** [comment]
Only if you enable "slow-tests"
