### ISSUE TITLE
[RFE] Improve systemd error messages

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#3448]
In the current state, systemd error messages reported back to users are sometimes confusing to say the least. That is because we use errno, sometimes errno mapped in a funny way to dbus errors. That can result, for example, in the following:

```
# systemd-run --scope loginctl seat-status
Running scope as unit: run-u4.scope
Could not get properties: No such device or address
```

There should be a consistent way to supply custom error messages from the exact places where errors happen, maybe even a way to `append` to such messages along the way to make them more precise. Such messages could be then used for both showing to the users and for logging.

This issue is quite general and I'm pretty sure that some of the currently opened issues are subsets of this one.

**Comment by poettering** [comment]
well, please send patches. The bus calls all can return any error they want. It's just a matter of generating better errors really. We currently are simply too lazy to return friendly errors for all error conditions. I am not sure we need to have an open issue for this so, as this is hardly a "bug", it's just a very general area where we could improve...

**Comment by keszybz** [comment]
Yeah, this bug is too generic to be useful. If the error is wrong for some specific issue, open a bug for that.
