### ISSUE TITLE
Static DHCP client identifier

### ISSUE THREAD

**Issue by nfnty** [systemd/systemd#345]
The last three updates (218->219->221) have changed the DHCP client identifier causing the DHCP server to lease new IP addresses.

Is there a reasoning behind this? Is it possible to force networkd to use a manually set static client identifier?

Similar issue: https://github.com/coreos/bugs/issues/360

**Comment by poettering** [comment]
@teg?

**Comment by poettering** [comment]
OK, let's continue discussion in #394, which discusses the same thing for IPv6. Closing this one.

**Comment by teg** [comment]
Let's discuss what to do in the other issue, but just to answer your question: it is unfortunate that we ended up changing the client identifier several times, but there are no plans to change it further. I believe the progression we had was: no client identifier, MAC based, MAC based with client identifier type, predictable (MAC-independent), DHCPv6-compatible.
So now we have the same logic for doing IPv4 and IPv6 client identifiers and no plans of changing the defaults again. Let's discuss static overrides in the other issue.
