### ISSUE TITLE
systemd-cryptsetup not working

### ISSUE THREAD

**Issue by littleblack111** [systemd/systemd#34506]
### systemd version the issue has been seen with

All

### Used distribution

Arch Linux

### Linux kernel version used

6.10.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

TPM auto unlock LUKS LVM encrypted disk

### Unexpected behaviour you saw

Plymouth(or tty without plymouth) asking me for password or recovery key. log:

### Steps to reproduce the problem

1. I have enrolled the tpm chip.
2. LUKS LVM encryption

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 20 16:25:16 ArchLinux systemd-cryptsetup[1941104]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
Sep 20 16:25:16 ArchLinux systemd-cryptsetup[1941104]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df)
Sep 20 16:25:16 ArchLinux systemd-cryptsetup[1941104]: Failed to unseal secret using TPM2: State not recoverable
Sep 20 16:39:56 ArchLinux systemd-cryptsetup[1941104]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/bc526687-9deb-4078-abd1-55692022e073.
Sep 20 16:39:58 ArchLinux systemd-cryptsetup[1941104]: Cannot use device /dev/disk/by-uuid/bc526687-9deb-4078-abd1-55692022e073 which is in use (already mapped or mounted).
Sep 20 16:39:58 ArchLinux systemd-cryptsetup[1941104]: Failed to activate with specified passphrase: Device or resource busy
Sep 20 16:39:58 ArchLinux systemd[1]: systemd-cryptsetup@cryptdata.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 16:39:58 ArchLinux systemd[1]: systemd-cryptsetup@cryptdata.service: Failed with result 'exit-code'.
Sep 20 16:39:58 ArchLinux systemd[1]: Failed to start Cryptography Setup for cryptdata.
Sep 20 16:39:58 ArchLinux systemd[1]: systemd-cryptsetup@cryptdata.service: Consumed 6.775s CPU time, 1G memory peak.
```

**Comment by littleblack111** [comment]
https://github.com/systemd/systemd/issues/29861 possible related

**Comment by poettering** [comment]
> ```shell
> Sep 20 16:25:16 ArchLinux systemd-cryptsetup[1941104]: WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error
> Sep 20 16:25:16 ArchLinux systemd-cryptsetup[1941104]: ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001df)
> ```

Hmm, tpm error 0x000001df decodes like this:

```console
$ tpm2_rc_decode 0x000001df
tpm:parameter(1):integrity check failed
```

this suggests that the enrolled key doesn't actually load into the tpm. No idea why? is this a physical tpm? did you reset that tpm? did a factory reset of some other OS on it?

otherwise, this smells like a tpm/firmware bug to me?

did this ever work for you?

**Comment by littleblack111** [comment]
its a physical tpm. it works if i remove the dictionary or something(prob just wiping it, i am outside and i forgot the command, will update wen i get home). And reenroll the key. I need to echo sth to the tpm chip, then reboot. then it works for once. then it doesnt work after(unless i repeat what i just did)

**Comment by poettering** [comment]
> it works if i remove the dictionary or something(prob just wiping it, i am outside and i forgot the command, will update wen i get home). 

"remove the dictionary"? what do you mean by that? 

> And reenroll the key. I need to echo sth to the tpm chip, then reboot. then it works for once. then it doesnt work after(unless i repeat what i just did)

"echo sth to the tpm chip"? what does that mean?

**Comment by littleblack111** [comment]
here: https://bbs.archlinux.org/viewtopic.php?id=293760#:~:text=tpm2_dictionarylockout%20%2DTdevice%3A/dev/tpmrm0%20%2D%2Dsetup%2Dparameters%20%2D%2Dmax%2Dtries%3D5%20%2D%2Dclear%2Dlockout

**Comment by poettering** [comment]
hmm, so you are saying the tpm is in dictionary lockout mode? do i get this right? is it really?

**Comment by littleblack111** [comment]
im uncertain... is there any way to check?

**Comment by littleblack111** [comment]
also. for additional infomation about if my TPM chip is the issue. My desktop is Omen 45L

**Comment by littleblack111** [comment]
following https://www.reddit.com/r/Fedora/comments/szlvwd/psa_if_you_have_a_luks_encrypted_system_and_a/ worked

i forgot to replace the (part 3)(refferenced in that post) to -
