### ISSUE TITLE
journalctl --verify fails to utilize mmap cache effectively

### ISSUE THREAD

**Issue by mischief** [systemd/systemd#34516]
### systemd version the issue has been seen with

255

### Used distribution

gentoo

### Linux kernel version used

6.10.6-gentoo

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

journalctl completes efficiently without unmapping recently accessed file ranges. it should have low sys%, low page fault rate and utilize the mmap cache efficiently.

### Unexpected behaviour you saw

journalctl --verify (and likely other forms of journal access) spend tons of time calling mmap/munmap when there's multiple journal files that exceed some TBD count/size. it incurs high page fault rates and high sys% cpu.

if the data set is smaller (say after --vacuum or on single journal files), the bad behavior won't occur.

a screenshot showing high kernel time spent in memory mapping, high fault rates, repeated mmap/munmap, high sys%

![2024-09-20-182824_1920x1200_scrot](https://github.com/user-attachments/assets/5072ad2c-b3be-4c0c-b325-d83aa0369e75)

### Steps to reproduce the problem

have a large enough journal data set and run journalctl --verify, and wonder why it takes so long. check perf, strace -e %memory for repeated mmap/munmap calls, pidstat -r for page fault rate and pidstat -u for sys%.

i can reproduce this with systemd 249 on ubuntu, 255 on gentoo, and 256 on debian.

i can provide an exemplary data set if needed.

**Comment by vcaputo** [comment]
@mischief Willing to try this out? https://github.com/systemd/systemd/commit/618d387478c3cc937454ac6206fdb05bad6cc4e5

**Comment by mischief** [comment]
no dice, there's still loops in strace of the same addresses being mapped/unmapped for the same fd repeatedly. ex.

```
mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_SHARED, 104, 0) = 0x7fa3cbe00000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x4ed000) = 0x7fa3ce767000
munmap(0x7fa3cbe00000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xb98000) = 0x7fa3cc600000
munmap(0x7fa3cdf67000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xfb7000) = 0x7fa3cdf67000
munmap(0x7fa3ce767000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x642000) = 0x7fa3ce767000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_SHARED, 104, 0) = 0x7fa3cc600000
munmap(0x7fa3ce767000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x4ed000) = 0x7fa3ce767000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xb85000) = 0x7fa3cc600000
munmap(0x7fa3ce767000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x6f0000) = 0x7fa3ce767000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xb8e000) = 0x7fa3cc600000
munmap(0x7fa3ce767000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x641000) = 0x7fa3ce767000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xb98000) = 0x7fa3cc600000
munmap(0x7fa3cdf67000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_SHARED, 104, 0) = 0x7fa3cbe00000
munmap(0x7fa3ce767000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0x4ed000) = 0x7fa3ce767000
munmap(0x7fa3cbe00000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xfc5000) = 0x7fa3cdf67000
munmap(0x7fa3cc600000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xb98000) = 0x7fa3cc600000
munmap(0x7fa3cdf67000, 8388608)         = 0
mmap(NULL, 8388608, PROT_READ, MAP_SHARED, 5, 0xf9e000) = 0x7fa3cdf67000
```
