### ISSUE TITLE
[Feature request] More helpfun information in stub-resolv.conf

### ISSUE THREAD

**Issue by shodanx2** [systemd/systemd#34522]
### Is your feature request related to a problem? Please describe

Hi,
Like I'm sure many other people, my dns resolving has broken for unknown and obscure reasons.

From experience and from many online resources, the answer is of course to change /etc/resolv.conf

When you go into this file you get

```
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search .
```

The advice you get there, to run resolvectl status
Will only lead you astray
You already know, you just need to write 

    nameserver 8.8.8.8

in /etc/resolv.conf

But that doesn't work
and the command they suggest, does not help

```
resolvectl status
Global
       Protocols: +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp10s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlp11s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (enx00e04c680536)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (vmbr0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

### Describe the solution you'd like

The solution would be to include a better solution to the immediate problem of 

"my dns isn't resolving and I don't know why"

### Describe alternatives you've considered

Will re-install operating system 

### The systemd version you checked that didn't have the feature you are asking for

This question should include the command to know you installed systemd version, I don't know what version I have / systemd --version systemd 252 (252.30-1~deb12u2)

**Comment by poettering** [comment]
The file says this:

> To manage man:resolv.conf(5) in a
> # different way, replace this symlink by a static file or a different symlink.

Not sure how this can be any clearer?

**Comment by shodanx2** [comment]
I imagine that this symlink is created as part of a larger management system for the dns service, and that making this a static file will break this system (and making a static file fix will, either get auto-overwritten or break the "proper" fix)

I don't know how this system works but I would have liked to find a solution ,beyond short circuiting this system ? 


I will ask chatgpt to suggest a better text, maybe that'll work ?

Here is what it suggested

```
# This is /run/systemd/resolve/stub-resolv.conf, managed by systemd-resolved.
# Do not edit this file directly as changes will be overwritten.
# 
# If you're seeing this in /etc/resolv.conf, it's likely a symlink created by
# systemd-resolved. The local DNS resolver at 127.0.0.53 forwards queries to
# upstream DNS servers.

# QUICK FIX to get DNS working NOW:
# 1. Replace the symlink with a static DNS configuration:
#    $ sudo rm /etc/resolv.conf
#    $ sudo nano /etc/resolv.conf
#    Add these lines for Google DNS:
#    nameserver 8.8.8.8
#    nameserver 1.1.1.1
#    Save and exit.
#    (Note: This bypasses systemd-resolved. DNS settings won't update dynamically.)

# PROPER FIX for common DNS resolution issues:
# 1. Check DNS settings and network interfaces:
#    $ resolvectl status
#    Ensure the correct DNS servers are listed and that interfaces are active.
# 2. Restart systemd-resolved to refresh DNS settings:
#    $ sudo systemctl restart systemd-resolved
# 3. If DNS resolution still fails, check systemd-resolved logs for errors:
#    $ journalctl -u systemd-resolved

# The most common reason for DNS issues is misconfigured or inactive network
# interfaces, or a problem with upstream DNS servers. Verify both with the 
# commands above.

# For more details, see man:resolv.conf(5) or man:systemd-resolved.service(8).
```

Here is the full discussion 
https://chatgpt.com/share/66f135b0-2334-8005-914b-8b23c7a09fc6

Also, for my case, the fix was, because I'm using proxmox, to go into the proxmox web interface and set the host name server back from 127.0.0.53 to 8.8.8.8. I have no idea why that suddenly changed and stopped working but that fixed it for me. I don't know where exactly proxmox webui put this 8.8.8.8 but it somehow made it's way into /etc/resolv.conf

**Comment by poettering** [comment]
> I imagine that this symlink is created as part of a larger management system for the dns service, and that making this a static file will break this system (and making a static file fix will, either get auto-overwritten or break the "proper" fix)

the current resolv.conf text suggests doing this, so why would you think it would "break" things then?

**Comment by shodanx2** [comment]
Look, forget chatgpt said anything, I am not proposing a solution that's your job, coming up with a solution.

I am just telling you, 

I was confronted with a non-working computer. 
The problem was somehow systemd related
shortcircuiting the system by breaking the link worked 
That's probably not the right way to do it
I would have done it the "right way" if the stub text has been more clear on what that right was 
my problem has been "solved" with that hack for a while now

So I guess I'm going to close this issue then 
good bye !
