### ISSUE TITLE
consider dlopen'ing everything with NODELETE

### ISSUE THREAD

**Issue by crrodriguez** [systemd/systemd#34537]
### Component

other

### Is your feature request related to a problem? Please describe

Future incarnations of the dynamic linker will repurpose/improve RTLD_NODELETE to mean the linker mseal(2)s everything loaded with that flag and since the kernel does not support munseal operation it will safely prevent runtime modifications of what you loaded.

### Describe the solution you'd like

dlopen everything with RTLD_NODELETE. dlclose is anyway not completely safe under certain circumstances, the standard does not require it to do anything and is elsewhere implemented as a no-op.

### Describe alternatives you've considered

None, as this requires kernel/linker support.

**Comment by poettering** [comment]
yeah, we should do that. we never dlcose our weak deps anyway.
