### ISSUE TITLE
homectl username creation with dot in Name

### ISSUE THREAD

**Issue by mbgevers** [systemd/systemd#34536]
### systemd version the issue has been seen with

255.4

### Used distribution

Ubuntu 24.04.1

### Linux kernel version used

6.8.0-45-generic

### CPU architectures issue was seen on

x86_64

### Component

homectl

### Expected behaviour you didn't see

Adding a user with the following Syntax should create a User without Error:
homectl create foo.bar

### Unexpected behaviour you saw

User name 'foo.bar' is not valid: Invalid argument

### Steps to reproduce the problem

homectl create foo.bar

**Comment by poettering** [comment]
See https://systemd.io/USER_NAMES for our rationale in enforcing syntax limits on user names in homed.
