### ISSUE TITLE
systemd-creds cat is broken, can't read encrypted credentials

### ISSUE THREAD

**Issue by SimonPilkington** [systemd/systemd#34547]
### systemd version the issue has been seen with

main

### Used distribution

n/a

### Linux kernel version used

n/a

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

`systemd-creds cat` prints the encrypted credential.

### Unexpected behaviour you saw

`systemd-creds cat` complains:
`Unknown encryption format, or corrupted data.`

### Steps to reproduce the problem

```
mkdir /tmp/creds
echo -n "Test" | sudo systemd-creds encrypt -T - /tmp/creds/test.cred
sudo ENCRYPTED_CREDENTIALS_DIRECTORY="/tmp/creds" systemd-creds cat test.cred 
```

**Comment by SimonPilkington** [comment]
The cause is this line: https://github.com/systemd/systemd/blob/df4d09f78eed6daef508a6a0421759b3c6767256/src/creds/creds.c#L440

If encrypted == 1 this needs `READ_FULL_FILE_UNBASE64`.

**Comment by YHNdnzj** [comment]
Could you submit a PR?

**Comment by SimonPilkington** [comment]
Done. #34548
