### ISSUE TITLE
Cant Move PID into delegted cgroup

### ISSUE THREAD

**Issue by mhanafi1970** [systemd/systemd#34541]
### systemd version the issue has been seen with

239

### Used distribution

Redhat 8 

### Linux kernel version used

kernel-4.18.0-425.13.1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I have enabled cgroups v2 delegation using systemd. It works because ownership of cgroup dir (/sys/fs/cgroup/user.slice/user-UID.slice/user@UID.service) gets changed to UID. I can create a new cgroup under user@UID.service. But when I try to move a PIDinto the cgroup I get permission denied. 

I have tracked the down the issue to the ownership of
 (/sys/fs/cgroup/user.slice/user-UID.slice/cgroup.procs) If I set change the ownership to the user it works.

 

### Unexpected behaviour you saw

Buy having correct ownership of (/sys/fs/cgroup/user.slice/user-UID.slice/user@UID.service) I should be able to create new cgroups and move PIDs into it. 

### Steps to reproduce the problem

1. Create /etc/systemd/system/user@.service

[Unit]
Description=User Manager for UID %i
After=systemd-user-sessions.service
After=user-runtime-dir@%i.service
Requires=user-runtime-dir@%i.service

[Service]
User=%i
PAMName=systemd-user
Type=notify
ExecStart=-/usr/lib/systemd/systemd --user
Slice=user-%i.slice
KillMode=mixed
Delegate=yes
TasksMax=infinity
TimeoutStopSec=120s

2. login
3. create a new cgroup
   mkdir (/sys/fs/cgroup/user.slice/user-UID.slice/user@UID.service/testcgroup
4. try to move shell into it
   echo $$ > /sys/fs/cgroup/user.slice/user-UID.slice/user@UID.service/testcgroup/cgroup.procs

**Comment by poettering** [comment]
v239 is way too old to be discussed here. That's anicent.

cgroupsv2 doesn't allow you to move processes across user delegation boundaries in the cgroup tree. My educated guess is that the process you are trying to move is in the session scope of yours hence?

You can use the AttachProcessesToUnit() bus call on systemd's manager to work around this issue, which will allow such moving under various conditions, that should suffice here.
