### ISSUE TITLE
CancelScheduledShutdown() reports a shutdown was cancelled that was not cancelled

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#34554]
### systemd version the issue has been seen with

256.6-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.10.10-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

logind has a dbus method "CancelScheduledShutdown()" which I expect to cancel a shutdown.

### Unexpected behaviour you saw

When I call this method while holding a shutdown delay inhibitor lock, I get cancelled=true, but shutdown happens anyway.

### Steps to reproduce the problem

```
$ systemd-inhibit --what=shutdown --mode=delay --why=debugging sleep infinity &
$ reboot # doesn't immediately reboot b/c of above
$ busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager CancelScheduledShutdown
b true # appears to have cancelled shutdown

<wall message that shutdown was cancelled>
<reboots when max delay sec is reached>
```
```
$ journalctl -b -1 -u systemd-logind
[...]
Sep 25 17:34:58 rdtw systemd-logind[761]: The system will reboot now!
Sep 25 17:34:58 rdtw systemd-logind[761]: System shutdown has been cancelled
Sep 25 17:35:01 rdtw systemd-logind[761]: System is rebooting.
[...]
```

**Comment by dtardon** [comment]
@rpigott Could you test #34557?

**Comment by poettering** [comment]
Opening, because as per @rpigott #34557 doesn't actually fix the issue.

**Comment by yuwata** [comment]
Fix is waiting in #34684.
@rpigott Could you test the PR?

**Comment by rpigott** [comment]
Not so easily, my mkosi version no longer works to build that branch. LGTM though.

**Comment by yuwata** [comment]
> Not so easily, my mkosi version no longer works to build that branch. LGTM though.

Yeah, please update mkosi, or try to revert 963157ca78429c51feb3103828d8cc94440956f3.

**Comment by rpigott** [comment]
I rebased the changes on an older version that I could build. Works for me.
