### ISSUE TITLE
support creating dm-verity hash partition for data partition of given size, instead of actual data size

### ISSUE THREAD

**Issue by WilliButz** [systemd/systemd#34562]
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

While working with A/B-style updates for machines with a fixed storage size an issue that came up is that of choosing a sensible partition layout. That partition layout should ideally support future updates over the whole lifecycle of the machine.
The on-disk partition layout that I'm currently working with is rather simple:

|ESP|usr-verity A (hash)|usr A|usr-verity B (hash)|usr B|dm-crypt volume|
|-|-|-|-|-|-|

Note: `/` is a tmpfs
That on-disk layout is created by repart in initrd on first boot from an image that was written to disk, the initial image is structured like this:

|ESP|usr-verity|usr|
|-|-|-|

In the initial image, the `usr` partition is minimized and then grown to a configured size on first boot. The **B** partition set is created with the same sizes, and the tmp-bound dm-crypt volume uses the remaining space available on disk. The configured `usr` size is supposed to support future system updates via sysupdate with growing artifact size, limited by the partition size.

Now the issue that arises is choosing an appropriate size for the corresponding `usr-verity` hash partition.

It should amount to `(nr. of nodes in the merkle tree plus one superblock) multiplied by the block size of the hash partition`. The number of nodes in the merkle tree depends on the `VerityHashBlockSizeBytes`, `VerityDataBlockSizeBytes` and the checksum.

### Describe the solution you'd like

I imagine that such a setup would become more accessible if the size of the dm-verity hash partition was calculated by repart, based on a specified maximum size for the sibling data partition.

Then the configuration for both the initial image and the update artifacts consumed by sysupdate could look something like this:
```ini
# 10-usr-verity.conf
[Partition]
Type=usr-verity
Verity=hash
VerityMatchKey=usr
VerityDataBlockSizeBytes=4096
VerityHashBlockSizeBytes=4096
VerityMaxDataSizeBytes=100G

# 20-usr.conf
[Partition]
Type=usr
Verity=data
VerityMatchKey=usr
Minimize=best
 ```

The usr-verity partition would be sized based solely on the proposed `VerityMaxDataSizeBytes`, leaving some space to grow over the lifetime of the system if the initial sibling data partition is smaller than that specified size.

### Describe alternatives you've considered

Our current solution to this is to pre-calculate the size of the hash partition's contents ourselves.

### The systemd version you checked that didn't have the feature you are asking for

256

---

ping @DaanDeMeyer 
cc @poettering (ASG boat)

**Comment by DaanDeMeyer** [comment]
Makes total sense, I'd be able to make use of this as well.
