### ISSUE TITLE
serial-getty service should start gettys for all serial consoles specified on the kernel cmdline

### ISSUE THREAD

**Issue by jjakob** [systemd/systemd#34566]
### Component

systemd

### Is your feature request related to a problem? Please describe

I configured the kernel with multiple consoles: `console=ttyS1,115200n8 console=ttyS0,115200n8
console=tty0`
serial-getty is only started on the first serial console (in the order it is specified on the cmdline), not on the 2nd.
While the kernel itself doesn't print messages to any other but the first configured console device of the same type (e.g. regardless of how many serial consoles are configured on the cmdline, only the first will be used), systemd could use all of them to start gettys on them, to facilitate multiple management channels. In my use case, ttyS0 is the external serial port, ttyS1 is the internal iLO SOL port that can be used for remote management. I want both to have a spawned getty.

While one could manually enable getty@ttyX.service, it would be nice if one could use the cmdline for this purpose, as the kernel basically ignores any more than 1 configured consoles of the same type.

How the kernel behaves:
https://docs.kernel.org/admin-guide/serial-console.html

> The behavior is more complicated when the same device type is defined more times. In this case, there are the following two rules:
>
> 1. The output will appear only on the first device of each defined type.

### Describe the solution you'd like

serial-getty@.service should spawn a getty on all configured cmdline consoles.

### Describe alternatives you've considered

Manually enabling getty@ttyX.service for each console that is not the first one.

**Comment by poettering** [comment]
we do this already, on all serial ports listed in /sys/class/tty/console/active (which is where stuff mentioned in console= on the kernel cmdline is ultimately exposed).

Hence, we already do what you are asking for? Is this not working? What does your /sys/class/tty/console/active show?

**Comment by jjakob** [comment]
```
# cat /sys/class/tty/console/active
ttyS1 tty0
# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-6.8.12-2-pve root=ZFS=rpool/ROOT/pve-1 ro mitigations=auto,nosmt console=ttyS1,115200n8 console=ttyS0,115200n8 console=tty0 root=ZFS=rpool/ROOT/pve-1 boot=zfs quiet
```

**Comment by jjakob** [comment]
/sys/class/tty/console/active only has ttyS1, even though ttyS0 is also set in the cmdline. I think this is because of the aforementioned kernel behavior - it only uses the first configured device of the same type.

**Comment by poettering** [comment]
i am not convinced we should overload a kernel cmdline option, and then process is entirely differently than the kernel does? Right now, we follow exactly the kernel's behaviour here.

You can always instantiate additional serial gettys directly, i.e. `systemd.wants=serial-getty@ttySXYZ.service`, after all?

**Comment by poettering** [comment]
rd.systemd.wants= exists and works.

But this is not going to work for gettys. gettys are regular login prompts, not specialized early-boot recovery prompts. That's the job for sulogin, but it always operates on /dev/console only.

**Comment by poettering** [comment]
(i.e. getty will be started after systemd-user-login.service which is a later boot service, not an initrd one)
