### ISSUE TITLE
in debian trixie, Failed to listen on systemd-fsckd.socket - fsck to fsckd communication Socket.

### ISSUE THREAD

**Issue by estatistics** [systemd/systemd#34573]
### systemd version the issue has been seen with

256

### Used distribution

debian trixie

### Linux kernel version used

6.10.9-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-fsck

### Expected behaviour you didn't see

to start normally as service

### Unexpected behaviour you saw

didnt start

### Steps to reproduce the problem

No such problem before upgrading/updating all packages. I do that about per once per month or every week. in the latest upgrade this happened: 

(part of bootlog)

> 
> `[  OK  ] Finished systemd-random-seed.service - Load/Save OS Random Seed.
> [  OK  ] Finished systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.
>          Starting systemd-udevd.service - Rule-based Manager for Device Events and Files...
> [  OK  ] Started systemd-journald.service - Journal Service.
>          Starting systemd-journal-flush.service - Flush Journal to Persistent Storage...
> [  OK  ] Finished lvm2-monitor.service - Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> [  OK  ] Reached target local-fs-pre.target - Preparation for Local File Systems.
> [  OK  ] Started systemd-udevd.service - Rule-based Manager for Device Events and Files.
> [  OK  ] Finished systemd-udev-trigger.service - Coldplug All udev Devices.
>          Starting ifupdown-pre.service - Helper to synchronize boot up for ifupdown...
>          Starting plymouth-start.service - Show Plymouth Boot Screen...
> [  OK  ] Reached target tpm2.target - Trusted Platform Module.
> [  OK  ] Finished ifupdown-pre.service - Helper to synchronize boot up for ifupdown.
>          Expecting device sys-subsystem-net-devices-enp3s0.device - /sys/subsystem/net/devices/enp3s0...
> [  OK  ] Found device sys-subsystem-net-devices-enp3s0.device - RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller (Onboard Ethernet).
> [  OK  ] Started plymouth-start.service - Show Plymouth Boot Screen.
> [  OK  ] Found device dev-disk-by\x2dlabel-Projects.device - WDC_WD50NDZW-11BCSS0 Projects.
> [  OK  ] Started systemd-ask-password-plymouth.path - Forward Password Requests to Plymouth Directory Watch.
> [  OK  ] Reached target cryptsetup.target - Local Encrypted Volumes.
> [FAILED] Failed to listen on systemd-fsckd.socket - fsck to fsckd communication Socket.
> [FAILED] Failed to start apparmor.service - Load AppArmor profiles.
> [  OK  ] Listening on uuidd.socket - UUID daemon activation socket.
> [  OK  ] Reached target sockets.target - Socket Units.
> [  OK  ] Reached target basic.target - Basic System.
> [  OK  ] Started anacron.service - Run anacron jobs.
>          Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack...
>          Starting cgroupfs-mount.service - LSB: Set up cgroupfs mounts....
>          Starting dbus.service - D-Bus System Message Bus...
>          Starting e2scrub_reap.service - Remove Stale Online ext4 Metadata Check Snapshots...
>          Starting gnome-remote-desktop.service - GNOME Remote Desktop...
>          Starting grub-common.service - Record successful boot for GRUB...
>          Starting lm-sensors.service - Initialize hardware monitoring sensors...
>          Starting preload.service - LSB: Adaptive readahead daemon...
>          Starting smartmontools.service - Self Monitoring and Reporting Technology (SMART) Daemon...
>          Starting switcheroo-control.service - Switcheroo Control Proxy service...
>          Starting udisks2.service - Disk Manager...
> [  OK  ] Mounted mnt-temp_dir.mount - /mnt/temp_dir.
> [  OK  ] Started cgroupfs-mount.service - LSB: Set up cgroupfs mounts..
> [FAILED] Failed to start gnome-remote-desktop.service - GNOME Remote Desktop.
> ...

`
```

sudo systemctl status  systemd-fsckd.socket
○ systemd-fsckd.socket - fsck to fsckd communication Socket
     Loaded: loaded (/etc/systemd/system/systemd-fsckd.socket; static)
     Active: inactive (dead)
   Triggers: ● systemd-fsckd.service
       Docs: man:systemd-fsckd.service(8)
             man:systemd-fsck@.service(8)
             man:systemd-fsck-root.service(8)
     Listen: /run/systemd/fsck.progress (Stream)

Sep 28 07:01:04 eros systemd[1]: systemd-fsckd.socket: Socket service systemd-fsckd.service not loaded, refusing.
Sep 28 07:01:04 eros systemd[1]: Failed to listen on systemd-fsckd.socket - fsck to fsckd communication Socket.

```

### Additional program output to the terminal or log subsystem illustrating the issue
```
sudo systemctl enable systemd-fsckd.socket 
The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
template units). This means they are not meant to be enabled or disabled using systemctl.
 
Possible reasons for having these kinds of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/, .requires/, or .upholds/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.

```

**Comment by poettering** [comment]
I have no idea what "systemd-fsckd.socket" is. But it's not a systemd thing, despite what the name might suggest. Please contact your distro for help, check where that unit file is from. It's not from us here upstream.
