### ISSUE TITLE
systemd-resolved: sd-event: Failed to create timer event "query-timeout": Invalid argument

### ISSUE THREAD

**Issue by tehron** [systemd/systemd#34580]
### systemd version the issue has been seen with

systemd 255 (255.4-1ubuntu8.4)

### Used distribution

Ubuntu 24.04.1 LTS

### Linux kernel version used

Linux 5.4.0

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Successful DNS resolution

### Unexpected behaviour you saw

When using 127.0.0.53 as name server, name resolution does not work:
```
root@wc3:~# nslookup google.de 127.0.0.53
;; Got SERVFAIL reply from 127.0.0.53
Server:         127.0.0.53
Address:        127.0.0.53#53

** server can't find google.de: SERVFAIL
```

Same when using resolvectl:
```
root@wc3:~# resolvectl query google.de
google.de: resolve call failed: Invalid argument
```

Behavior started to show after upgrading to Ubuntu 24.04 on two systems, both VPS under Virtuozzo (OpenVZ). One system has Kernel 4.15.0, the other one Kernel 5.4.0.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@wc3:~# resolvectl query google.de
Got message type=method_call sender=:1.54 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname  cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
idn2_lookup_u8: google.de → google.de
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=4 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.53 path=n/a interface=n/a member=n/a  cookie=6 reply_cookie=4 signature=u error-name=n/a error-message=n/a
D-Bus hostname resolution request from client PID 16048 (resolvectl) with UID 0
Looking up RR for google.de IN A.
Looking up RR for google.de IN AAAA.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=5 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=6 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.53 path=n/a interface=n/a member=n/a  cookie=8 reply_cookie=6 signature=s error-name=n/a error-message=n/a
Switching to system DNS server 81.169.163.106.
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/resolve1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
sd-event: Failed to create timer event "query-timeout": Invalid argument
Freeing transaction 38720.
Freeing transaction 17675.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=8 reply_cookie=0 signature=s error-name=n/a error-message=n/a
google.de: resolve call failed: Invalid argument
root@wc3:~# Sent message type=error sender=n/a destination=:1.54 path=n/a interface=n/a member=n/a cookie=9 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Invalid argument
Failed to process message type=method_call sender=:1.54 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a: Invalid argument
Got message type=method_return sender=org.freedesktop.DBus destination=:1.53 path=n/a interface=n/a member=n/a  cookie=7 reply_cookie=5 signature=n/a error-name=n/a error-message=n/a
```

**Comment by poettering** [comment]
Very strange. Can you reproduce the issue? Any chance you can strace resolved while this happens, to see where precisely the EINVAL comes from?

**Comment by tehron** [comment]
It's 100% reproducable, rendering systemd-resolved useless.
[systemd-resolved_strace.txt](https://github.com/user-attachments/files/17194477/systemd-resolved_strace.txt)

**Comment by poettering** [comment]
Seems to be a kernel issue. For some reason CLOCK_BOOTTIME use results in EINVAL. Not sure how that could possibly happen...

Is this some weird kernel or so? Or some weird execution environment/hypervisor?

Either way, doesnt seem actionable to us. Some very basic functionality of your kernel seems to be broken, we cannot work around that and shouldnt even if we could.

Please contact your OS vendor for help, and check dmesg whether there are any comments.

**Comment by poettering** [comment]
> What puzzles me is this: It used to work in the same environment with systemd 249 (249.11-0ubuntu3.12) under Ubuntu 22.04. It failed only after upgrading to 24.04.

We used to have some wonky code in place to use CLOCK_MONOTONIC if CLOCK_BOOTTIME was unavailable. We killed that in v250 because the clock has been around for so long now (ba4e0427e955a648e24f6506d0cb92857c84b85d), i.e. since kernel 3.15.

If your kernel claims to be 5.4 and has no CLOCK_BOOTTIME thta works, then something is very very off.

Anyway, closing as this is not an upstream proble, but between your kernel and your vendor.

**Comment by qris** [comment]
This is unfortunate, it means that I can't run Ubuntu 24.04 LXC containers on my CentOS 7 host, which has kernel 3.10.0. (Well, I can run them but DNS doesn't work, so it's kind of useless). Please, please could we not remove backwards-compatibility code?
