### ISSUE TITLE
systemd-udev doesn't initialize all devices after a reload on NixOS (after a reload of udev)

### ISSUE THREAD

**Issue by AkechiShiro** [systemd/systemd#34585]
### systemd version the issue has been seen with

255.9

### Used distribution

NixOS 24.05

### Linux kernel version used

kernel 6.X

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

See for more information downstream issue : https://github.com/NixOS/nixpkgs/issues/182449

Version used on my end : /nix/store/109w24xsb42fali6vh051vd2ghiphj4s-systemd-255.9

This has been happening for awhile on previous systemd major versions.

### Unexpected behaviour you saw

The device is not initialized (note the lack of USEC_INITIALIZED):
```
P: /devices/virtual/net/wg0
L: 0
E: DEVPATH=/devices/virtual/net/wg0
E: DEVTYPE=wireguard
E: INTERFACE=wg0
E: IFINDEX=6
E: SUBSYSTEM=net
```

## Additional context

> Probably an upstream bug triggered by NixOS because it likes to reload udev.

Expected behavior
```
sudo udevadm info /sys/class/net/wg0
P: /devices/virtual/net/wg0
L: 0
E: DEVPATH=/devices/virtual/net/wg0
E: DEVTYPE=wireguard
E: INTERFACE=wg0
E: IFINDEX=6
E: SUBSYSTEM=net
E: USEC_INITIALIZED=5650399976
E: PATH=/nix/store/41pz7bsljf9nnj154vzrvand881ij31c-udev-path/bin:/nix/store/41pz7bsljf9nnj154vzrvand881ij31c-udev-path/sbin
E: ID_MM_CANDIDATE=1
E: ID_NET_LINK_FILE=/nix/store/iirqa1lqni18mcaii3g1l5s15jxwz17a-systemd-250.4/lib/systemd/network/99-default.link
E: ID_NET_NAME=wg0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/wg0
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

### Steps to reproduce the problem

- Switch to a different version of udev (or just a rebuild)
- sudo udevadm info /sys/class/net/wg0

We're currently trying to reproduce it on systemd release 256

**Comment by poettering** [comment]
no idea what you are trying to do, but note that for the udev db we generally guarantee forward compat, not backward. Hence, if you are switching back and forth between udev versions or if you are using libudev versions against the udev db that doesn't match the udev version that wrote it you voided your warranty...

Also note that "systemctl reload systemd-udevd.service" doesn't retrigger deivces, if you are suggsting that. "udevadm trigger" does that however.

In your case it simply appears that the device in question was never probed before, and hence no db entry existant yet.

**Comment by AkechiShiro** [comment]
@lorenz @neilmayhew could you elaborate more on what is exactly the issue we're facing ? taking into account the new information, that udev guarantee forward compat and not backward.

**Comment by neilmayhew** [comment]
@AkechiShiro My problem has always been that switching to a new configuration (with `nixos-rebuild switch`) wouldn't complete due to a timeout waiting for `NetworkManager-wait-online.service`.

I've had this in my `configuration.nix` since June 2023:

```nix
# See https://github.com/NixOS/nixpkgs/issues/180175
systemd.services.NetworkManager-wait-online.serviceConfig.ExecStart =
  [ "" "${pkgs.networkmanager}/bin/nm-online -q" ];
```

This simply removes the `-s` option from the default `ExecStart` configuration.

I've just taken that patch out and I was able to run `nixos-rebuild switch --upgrade` without a problem. However, it may depend on exactly what updates are being applied. I'll keep an eye out for failures and let you know if I see any.

**Comment by poettering** [comment]
So, what does this now have to do with systemd? Can we close this here?

**Comment by AkechiShiro** [comment]
I guess it can be closed.

I'll let @lorenz respond on it later, when possible, but it was believed to be an issue on udev's side and this was reported downstream as such.

I'm sorry I can't provide much more details than I've already shared, I will refrain from opening issues upstream later if I don't have all the information and knowledge on the issue.

**Comment by poettering** [comment]
ok, thanks. Let's close then. Feel free to comment here (or open a new bug, if you have more info, and nixos downstreams have strong reason to believe this is actually a systemd bug)
