### ISSUE TITLE
SELinux label for /etc/udev/hwdb.bin is etc_t instead of systemd_hwdb_etc_t after "#systemd-hwdb update"

### ISSUE THREAD

**Issue by wrabcak** [systemd/systemd#3458]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd-230
### Used distribution

> Fedora Rawhide
### In case of bug report: Expected behaviour you didn't see

>  ls -Z hwdb.bin 
> unconfined_u:object_r:systemd_hwdb_etc_t:s0 hwdb.bin
### In case of bug report: Unexpected behaviour you saw

>  ls -Z hwdb.bin 
> unconfined_u:object_r:etc_t:s0 hwdb.bin
### In case of bug report: Steps to reproduce the problem

>  rm /etc/udev/hwdb.bin
>  systemd-hwdb update
>  ls -Z /etc/udev/hwdb.bin

systemd-hwdb update doing:
Deleting /etc/udev/hwdb.bin file, then file "/etc/udev/.#hwdb.binXXXXXX" is created and after then renamed to /etc/udev/hwdb.bin
This is problem from SELinux policy point of view. I cannot create filename transtion rule for file ".#hwdb.binXXXXXX" due to non-constant name. Is it possible ti have always same name of ".#hwdb.binXXXXXX"?

**Comment by evverx** [comment]
> Is it possible ti have always same name of ".#hwdb.binXXXXXX"

I think `systemd-hwdb` should use [`label_fix`](https://github.com/systemd/systemd/blob/09541e49ebd17b41482e447dd8194942f39788c0/src/basic/label.c#L29) or so

**Comment by poettering** [comment]
yeah, label_fix appears to be the answer here. Happy to take a patch for that.

**Comment by evverx** [comment]
fix waiting in #3460

**Comment by sourcejedi** [comment]
Surely the approach with `label_fix()` races with hotplug, so we accept potential spurious SELinux denial pop-ups.  Following the original suggestion (like `passwd`) would still have allowed preventing write conflicts, using whatever unix locking construct is considered least horrifying.

Locking would also make it possible to guarantee that if two `hwdb update`s are running at the same time, the one with the older view of the conf files is not overwritten by the one with the more recent view.

**Comment by sourcejedi** [comment]
... or move `After=systemd-hwdb.service` from `systemd-udev-trigger.service` to `systemd-udev.service`.  I'll send a PR.
