### ISSUE TITLE
run0 fails to work after stty intr ^g

### ISSUE THREAD

**Issue by barry-scott** [systemd/systemd#34604]
### systemd version the issue has been seen with

256

### Used distribution

Fedora 41

### Linux kernel version used

6.11.0-63.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

run0 does not work after stty intr ^g
It prints no messages, the exit code is 130

### Steps to reproduce the problem

1. stty intr ^g
2. run0

**Comment by barry-scott** [comment]
Filed downstream as https://bugzilla.redhat.com/show_bug.cgi?id=2315867

**Comment by poettering** [comment]
why would you do this? what did you expect would happen? there are a myriad of ways to break your terminal, but why is that a systemd thing to deal with?

**Comment by barry-scott** [comment]
Lennart,

I guess this surprised you that someone should configure none-standard intr.

I run this: stty lnext ^b intr ^g
Then I can bind  Ctrl-C and Ctrl-V to copy and paste in the GUI terminal short cuts.
I find the Shift-Ctrl-C/Shift-Ctrl-V less user friendly.

Why does systemd care about which key that is bound to intr?
Is it becuase systemd needs the bindings in the pty and the terminal to match?
If so then copy the settings across.

Barry

**Comment by poettering** [comment]
> run0 does not work after stty intr ^g
> It prints no messages, the exit code is 130

Are you saying on hitting ^g it is exiting immediately?

If you ssh to some host and do your stty intr thing there, do things work correctly then?

**Comment by barry-scott** [comment]
At no time do I type Ctrl-G, here is a detailed way to reproduce.

To reproduce I installed VMs from these two .iso images:
Fedora-KDE-Live-x86_64-41_Beta-1.2.iso
Fedora-Workstation-Live-x86_64-41_Beta-1.2.iso
I accepted defaults, expect to choose UK keyboard.

Restarted Workstation install.
Completed setup adding user "barry".
Login as "barry".
Start Terminal.
Run "run0" and a GUI prompt asks for password.
Click cancel - run0 prints "Failed to start transient service unit: Access denied" and exits.
Run "stty intr ^g".
Run "run0" - it immediately exits, no messages printed, exit RC is 130
Run "stty intr ^c".
Run "run0" and a GUI prompt asks for password.

I then did the same steps after logging in to Plasma and starting Konsole.
Behaviour is identical to the Gnome Terminal session.

If I ssh into the VM that run0 will prompt in the ssh session.
`
% ssh barry@172.16.2.192
barry@172.16.2.192's password:
Last login: Wed Oct  2 10:45:32 2024 from 172.16.2.125
barry@fedora:~$ stty
speed 38400 baud; line = 0;
intr = ^G; lnext = ^B;
-brkint ixany iutf8
barry@fedora:~$ run0
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to manage system services or other units.
Authenticating as: barry
Password:
`

I cannot get run0 to fail when run under gdb.

In Gnome terminal with `stty intr ^g` I ran `gdb run0`, let gdb download debug symbols.
Then type `run` and gdb stops here:
`
Downloading source file /usr/src/debug/glibc-2.40-3.fc41.x86_64/io/../sysdeps/unix/sysv/linux/ppoll.c
0x00007ffff78f4f1b in __GI_ppoll (fds=fds@entry=0x7fffffffda70,
    nfds=nfds@entry=1, timeout=<optimized out>, sigmask=sigmask@entry=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
42	  return SYSCALL_CANCEL (ppoll_time64, fds, nfds, timeout, sigmask,
`
Then type "c" and I get the GUI prompt.

**Comment by poettering** [comment]
OK, so what you are doing is never going to work. ^G is ASCII code 7 also called BEL. run0 (and various other tools) will issue an ANSI sequence to read your terminal's background color when initializing, and that sequence contains the BEL character. i.e. we send `\x1B]11;?\x07`. The terminal then replies with its background color R/G/B values, in another ANSI sequences, which also ends in a `\x07`, i.e. BEL code.

Via `stty intr ^g` you are telling the tty driver to generate SIGINT the moment BEL is seen flowing from terminal to app. Thus, when initializing run0 will trigger a SIGINT almost immediately.

Hence, what you are doing is simply incompatible with ANSI sequences, as some of them use ^G aka ASCII 7, aka BEL as part of responses.

Sorry,

Hence, closing.

**Comment by barry-scott** [comment]
> On 25 Oct 2024, at 13:25, Lennart Poettering ***@***.***> wrote:
> 
> 
> OK, so what you are doing is never going to work. ^G is ASCII code 7 also called BEL. run0 (and various other tools) will issue an ANSI sequence to read your terminal's background color when initializing, and that sequence contains the BEL character. i.e. we send \x1B]11;?\x07. The terminal then replies with its background color R/G/B values, in another ANSI sequences, which also ends in a \x07, i.e. BEL code.
> 
That makes sense. Unless there is a way to stop the probing from a command line option.
> Via stty intr ^g you are telling the tty driver to generate SIGINT the moment BEL is seen flowing from terminal to app. Thus, when initializing run0 will trigger a SIGINT almost immediately.
> 
> Hence, what you are doing is simply incompatible with ANSI sequences, as some of them use ^G aka ASCII 7, aka BEL as part of responses.
> 
As an aside ANSI sequences originally never use control chars as terminators.
But that ship sailed a very long time ago.

Barry

**Comment by barry-scott** [comment]
You put the terminal into RAW mode at some point I think.
If you put the terminal into RAW before you probe then the Ctrl-G will not generate an SIGINT.

**Comment by poettering** [comment]
> As an aside ANSI sequences originally never use control chars as terminators. But that ship sailed a very long time ago.

OSC sequences have been defined since about always to use BEL as end terminator, since before 1989.

That said, terminal emulators allow three alternative terminators (called "ST"), one being BEL which we currently use. The other one is "\x9C" and the third one "\x1B\x5C".

I'd be willing to merge a patch that switches over any use of BEL in our tree to \x9C I guess, when it comes to ST.

**Comment by poettering** [comment]
I implemented that approach now in #34964. But do note that many other tools use the BEL delimiter for OSC, so this will fix some things for you, but plenty other programs will use BEL as ST and things will break for you still.
