### ISSUE TITLE
error: 'BTRFS_UUID_SIZE' undeclared here with kernel 4.7.0-rc1

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#3461]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd-230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> OpenMandriva Lx
### In case of bug report: Expected behaviour you didn't see

> Succesful compile
### In case of bug report: Unexpected behaviour you saw

> src/basic/btrfs-ctree.h:53:22: error: 'BTRFS_UUID_SIZE' undeclared here (not in a function)
>          uint8_t uuid[BTRFS_UUID_SIZE];
>                       ^
> In file included from src/basic/alloc-util.h:27:0,
>                  from src/basic/btrfs-util.c:38:
> src/basic/btrfs-util.c: In function 'btrfs_subvol_get_info_fd':
> src/basic/btrfs-util.c:538:35: error: expression in static assertion is not an integer
>                          assert_cc(sizeof(ri->uuid) == sizeof(ret->uuid));
### In case of bug report: Steps to reproduce the problem

> Compile systemd-230 with kernel-4.7.-rc1

Full log can be found here
http://file-store.openmandriva.org/api/v1/file_stores/23d9683103dfc6e51631d22cea9312b991a86c72.log?show=true

**Comment by evverx** [comment]
See https://github.com/systemd/systemd/pull/3391#issuecomment-222668816

**Comment by tpgxyz** [comment]
Thanks.
Ok looks like it got fixed in kernel. Closing then.
