### ISSUE TITLE
tmpfs size for `/tmp` is randomly ignored

### ISSUE THREAD

**Issue by vinc17fr** [systemd/systemd#34620]
### systemd version the issue has been seen with

256.6

### Used distribution

Debian/unstable

### Linux kernel version used

6.10.12-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

The tmpfs size from `/usr/lib/systemd/system/tmp.mount` should be honored (or if there is some reason not to honor it, one should get reproducible behavior).

### Unexpected behaviour you saw

The `size` option is randomly ignored: after some boots, I get
```
cventin:~> grep /tmp /proc/mounts
tmpfs /tmp tmpfs rw,nosuid,nodev,nr_inodes=1048576,inode64 0 0
```
(without a `size` option), and after other boots, I get something like
```
cventin:~> grep /tmp /proc/mounts
tmpfs /tmp tmpfs rw,nosuid,nodev,size=16422180k,nr_inodes=1048576,inode64 0 0
```
(with a `size` option).

### Steps to reproduce the problem

Reboot several times, and each time, do `grep /tmp /proc/mounts`. I have 3 machines, and they are all affected by this issue.

Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1083159

**Comment by vinc17fr** [comment]
I forgot to say: I do not have any local customization for the file system. In particular, `/usr/lib/systemd/system/tmp.mount` contains
```
[Mount]
What=tmpfs
Where=/tmp
Type=tmpfs
Options=mode=1777,strictatime,nosuid,nodev,size=50%%,nr_inodes=1m
```

**Comment by bluca** [comment]
Are you sure you don't have some scripts in the initramfs mounting tmp or so? Or something define in fstab? Mount units will _not_ overwrite existing mounts if they are present already, and that's by design

**Comment by vinc17fr** [comment]
I don't have any script concerning initramfs. I have the default `/etc/fstab` generated at Debian installation + some line to mount a davfs file system under my home directory, so nothing related to `/tmp`.

**Comment by bluca** [comment]
then please enable debug logging and provide the full journal for tmp.mount in a run that reproduces the issue

**Comment by vinc17fr** [comment]
`journalctl -b -u tmp.mount` gives:
```
Oct 03 12:28:22 cventin systemd[1]: tmp.mount: starting held back, waiting for: swap.target
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: ConditionPathIsSymbolicLink=!/tmp succeeded.
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: About to execute: /usr/bin/mount tmpfs /tmp -t tmpfs -o mode=1777,strictatime,nosuid,nodev,size=50%,nr_inodes=1m
Oct 03 12:28:25 cventin systemd[1]: Serializing sd-executor-state to memfd.
Oct 03 12:28:25 cventin systemd[1]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Forked /usr/bin/mount as 578 (via CLONE_INTO_CGROUP)
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Changed dead -> mounting
Oct 03 12:28:25 cventin systemd[1]: Mounting tmp.mount - Temporary Directory /tmp...
Oct 03 12:28:25 cventin (mount)[578]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 03 12:28:25 cventin (mount)[578]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Oct 03 12:28:25 cventin (mount)[578]: tmp.mount: Executing: /usr/bin/mount tmpfs /tmp -t tmpfs -o mode=1777,strictatime,nosuid,nodev,size=50%,nr_inodes=1m
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Changed mounting -> mounting-done
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Child 578 belongs to tmp.mount.
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Mount process exited, code=exited, status=0/SUCCESS (success)
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Changed mounting-done -> mounted
Oct 03 12:28:25 cventin systemd[1]: tmp.mount: Job 60 tmp.mount/start finished, result=done
Oct 03 12:28:25 cventin systemd[1]: Mounted tmp.mount - Temporary Directory /tmp.
```

I can see the `size=50%` for the `mount` command as expected (and nothing else that would suggest that it is reverted), but
```
cventin:~> grep /tmp /proc/mounts
tmpfs /tmp tmpfs rw,nosuid,nodev,nr_inodes=1048576,inode64 0 0
```

**Comment by bluca** [comment]
What's the actual size of the filesystem?

**Comment by vinc17fr** [comment]
```
cventin:~> df --human-readable /tmp
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            16G   24K   16G   1% /tmp
```
for 32 GB RAM. This seems correct here, but probably because 50% is the default, and this doesn't explain the random behavior in the actual mount options.

**Comment by bluca** [comment]
Are you sure it's not just a displaying issue? Have you tried changing the size and verifying the filesystem size?

**Comment by bluca** [comment]
/proc/mounts is managed by the kernel, so yes it seems like a display issue somewhere inside the kernel
