### ISSUE TITLE
.cmdline from a UKI profile should be appended to the shared .cmdline section instead of overriding it

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#34622]
In mkosi, we want to add support for UKI profiles by allowing users to specify ukify config files. Each ukify config file specified is translated to a UKI profile added to each UKI built by mkosi. This design keeps the integration simple, as mkosi doesn't need to add a bunch of machinery to allow users to specify UKI profiles.

The issue with this approach is that the `.cmdline` section from a UKI profile overrides the base profile. So users would have to duplicate the entire kernel command line into the UKI config file for each profile. Not only is this extremely verbose and lots of duplication, it's also impossible as parts of the command line such as the root and usr verity hashes are generated dynamically during the image build.

To make this work, mkosi would have to start parsing ukify config files and insert its own generated command line to make this work, all of which would require complex machinery that would have to be updated in tandem with ukify.

Instead of adding all this complexity to mkosi, a simpler solution would be to have `.cmdline` sections from UKI profiles append to the shared `.cmdline` section instead of overriding it. This avoids having to duplicate the entire shared `.cmdline` for each profile. It allows `.cmdline` from profiles to remain minimal, adding only a few arguments and maybe overriding a few from the shared `.cmdline` section.

**Comment by DaanDeMeyer** [comment]
I can work around this in mkosi, so we might as well stick with the current approach
