### ISSUE TITLE
udev/pid1: loopback diskseq symlinks in /run/ are created for each run and kept around until a restart cycle ends leading to inode exhaustion

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#34637]
If a unit uses a loop device for any reason, a diskseq symlink is created in /run/udev/links/ for each invocation. If a unit fails and it has Restart= set, the symlinks are all kept around until a rate limit is hit, or the unit is manually stopped, and only then they are cleared. If a unit sets StartlimitIntervalSec=0 to disable rate limiting, and always fail, eventually /run/ runs out of inodes due to the symlinks.

To reproduce:

```
mkdir /var/foo/bar -p
mksquashfs /var/foo /var/foo.raw
cat <<EOF> /etc/systemd/system/test.service
[Unit]
StartLimitIntervalSec=0
[Service]
ExecStart=false
Restart=on-failure
MountImages=/var/foo.raw:/var/foo
EOF
```

Then start the test.service and observe the number of links grow indefinitely `ls /run/udev/links | grep diskseq | wc -l`

While this happens, udevadm monitor shows a stream of:

```
UDEV  [849.134231] change   /devices/virtual/block/loop4 (block)
UDEV  [849.187554] change   /devices/virtual/block/loop4 (block)
KERNEL[849.370486] change   /devices/virtual/block/loop3 (block)
UDEV  [849.425013] change   /devices/virtual/block/loop3 (block)
KERNEL[849.448361] change   /devices/virtual/block/loop4 (block)
UDEV  [849.486913] change   /devices/virtual/block/loop4 (block)
```

udevadm info on the loop device:

```
P: /devices/virtual/block/loop0
M: loop0
R: 0
J: b7:0
U: block
T: disk
D: b 7:0
N: loop0
L: 0
S: disk/by-diskseq/478
Q: 479
E: DEVPATH=/devices/virtual/block/loop0
E: DEVNAME=/dev/loop0
E: DEVTYPE=disk
E: DISKSEQ=479
E: MAJOR=7
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=5176916
E: NVME_HOST_IFACE=none
E: SYSTEMD_READY=0
E: DEVLINKS=/dev/disk/by-diskseq/478
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

Stepping through with gdb, I pin pointed the exact moment when the new link is created, and it's when the loop_device_unref from here is called:

https://github.com/systemd/systemd/blob/598bb6fde46550ce020dd1d9853b316b766cb923/src/shared/dissect-image.c#L4040

more precisely when `d->fd` is closed here:

https://github.com/systemd/systemd/blob/598bb6fde46550ce020dd1d9853b316b766cb923/src/shared/loop-util.c#L812

It feels like we are keeping <some> reference somewhere that prevents udev from cleaning up these links while a restart cycle is ongoing

**Comment by yuwata** [comment]
Fix is waiting in #34644.
