### ISSUE TITLE
Add PrivateControlGroups= setting to service units

### ISSUE THREAD

**Issue by ryantimwilson** [systemd/systemd#34634]
### Component

systemd

### Is your feature request related to a problem? Please describe

Meta is migrating its Twine container engine to use systemd transient units for spawning containers - we already do use it in a limited way. Our current container engine currently enforces all containers use cgroup namespaces - our whole fleet is cgroup v2.

### Describe the solution you'd like

To do so, we need support for cgroup namespaces. To do so, we propose adding a PrivateControlGroups setting (similar to PrivateMounts)

This would do the following in order:
1. Unshare cgroup namespace
2. Mount a private mount of /sys/fs/cgroup (instead of bind mount from host)

On cgroup v1, this setting would be ignored.

Open question: /sys and sub-mounts are currently bind mounted from host for service units. If PrivateControlGroups is set, should we also mount private versions of /sys and all sub-mounts rather than use a bind mount?

cc @anitazha @DaanDeMeyer 

### Describe alternatives you've considered

Why not nspawn:
1. nspawn is opinionated (for good reason) on container setup. Twine containers have a variety of settings that are needed for customization of Twine containers e.g. ExtraFileDescriptors: https://github.com/systemd/systemd/pull/34556
2. nspawn is only a CLI, our Twine agent team prefers API

**Comment by poettering** [comment]
Note that we currently have fields ProtectControlGroups=, ControlGroup=, ControlGroupId=. Hence the new setting should be called PrivateControlGroups= I guess.

**Comment by poettering** [comment]
> Open question: /sys and sub-mounts are currently bind mounted from host for service units. If PrivateCgroups is set, should we also mount private versions of /sys and all sub-mounts rather than use a bind mount?

I don't see a reason to do this. (At least none related to CLONE_NEWCGROUP. There are valid ones regarding CLONE_NEWUSER and CLONE_NEWNET I guess, but I don't think CLONE_NEWCGROUP should necessarily trigger this)

**Comment by poettering** [comment]
> ###
> 
> Why not nspawn:
> 
>     1. nspawn is opinionated (for good reason) on container setup. Twine containers have a variety of settings that are needed for customization of Twine containers e.g. ExtraFileDescriptors:

So I agree with this. I think we should rework nspawn eventually to be just a different frontend for regular service management.

**Comment by ryantimwilson** [comment]
@poettering I noticed we have a ProtectControlGroups setting...it might be a bit confusing for the user to have 2 settings - ProtectControlGroups and PrivateControlGroups - control how /sys/fs/cgroup is mounted.

Another approach might be like ProtectSystem which allows yes, no, full and strict. ProtectHome also does something similar: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectHome=

So for ProtectControlGroups we could do:
1. no - /sys/fs/cgroup used from host (current behavior)
2. yes - /sys/fs/cgroup bind mounted from host read-only (current behavior)
3. private - /sys/fs/cgroup has read-write private mount within mount namespace
4. private-read-only - /sys/fs/cgroup has read-only private mount within mount namespace

This solution has the added benefit that the backend is cleaner as opposed to passing two booleans around. But we would need to migrate from boolean dbus API -> string e.g. ProtectControlGroupsEx

Let me know what you think! Fine to do 2 properties as well, we can have the two dbus properties merge into one property in execute.c

**Comment by poettering** [comment]
idea sounds good. We have been doing something similar for other PrivateXYZ= and ProectXYZ= knobs.

I'd probably find a different name for `private-read-only` though. Maybe `strict` or so?

**Comment by Werkov** [comment]
I must say I liked the conceptual distinction between Protect* and Private* directives. The former standing for the system being protected from the service, the latter meaning service has it own (restricted) view of the structures (which possibly _also_ protects the broad system). I could reason about what each directive means just by looking at a unit file without delving into manpages and reading a case breakdown for special values.

I guess I'm gonna live with the new approach. Is this the systematization that holds?

| Private*= | Protect*= | New Protect*= |
| --- | --- | --- |
| no | no | no |
| no | yes | yes |
| yes | no | private |
| yes | yes | strict |
