### ISSUE TITLE
ukify measurments do not match systemd-stub

### ISSUE THREAD

**Issue by valentindavid** [systemd/systemd#34645]
### systemd version the issue has been seen with

598bb6fde46550ce020dd1d9853b316b766cb923

### Used distribution

GNOME OS Nightly

### Linux kernel version used

6.11

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

systemd-cryptsetup can unseal with pcr 11 enrolled

### Unexpected behaviour you saw

With recent changes in between d713c131a58b4c2b46ff0edc0fea26037edb2140 and 598bb6fde46550ce020dd1d9853b316b766cb923, GNOME OS stopped booting correctly.

When re-enrolling without PCR 11, then unsealing works.
When reverting all changes in `src/ukify/`, unsealing also works.

**Comment by valentindavid** [comment]
@DaanDeMeyer You probably know what is happening here.

**Comment by DaanDeMeyer** [comment]
See my last open pr, that fixes it

**Comment by valentindavid** [comment]
I suppose it is #34628
