### ISSUE TITLE
udev silently fails to apply MACAddressPolicy=random when network-manager is running

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#3464]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> …230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> …debian testing/unstable
### In case of bug report: Expected behaviour you didn't see

> …when setting MACAddressPolicy=random in /etc/systemd/network/99-default.link, i expected the MAC address of a newly-plugged in USB ethernet device to be randomized.
### In case of bug report: Unexpected behaviour you saw

> …the MAC address of the USB ethernet device was unchanged from the stock hardware address
### In case of bug report: Steps to reproduce the problem

> …make the following /etc/systemd/network/99-default.link:

```
[Link]
NamePolicy=kernel database onboard slot path
MACAddressPolicy=random
```

do:

```
systemctl stop network-manager.service
ip link show
```

note the MAC address.  Then unplug the device, plug it back in again.  note that the MAC address changes.

then:

```
systemctl start network-manager.service
ip link show
```

unplug the device, plug it back in again.  the MAC address is always the builtin address.

fsateler suggested i try:

```
udevadm test-builtin net_setup_link /sys/class/net/$DEVICENAME
```

So i did that, and while network-manager is running, i got:

```
calling: test-builtin
=== trie on-disk ===
tool version:          230
file size:         7159849 bytes
header size             80 bytes
strings            1784033 bytes
nodes              5375736 bytes
Load module index
Found container virtualization none
timestamp of '/etc/systemd/network' changed
timestamp of '/lib/systemd/network' changed
Skipping overridden file: /lib/systemd/network/99-default.link.
Parsed configuration file /etc/systemd/network/99-default.link
Created link configuration context.
ID_NET_DRIVER=ax88179_178a
Config file /etc/systemd/network/99-default.link applies to device $DEVICENAME
Could not set Alias, MACAddress or MTU on $DEVICENAME: Device or resource busy
Could not apply link config to $DEVICENAME: Device or resource busy
Unload module index
Unloaded link configuration context.
```

without network-manager running, i see:

```
calling: test-builtin
=== trie on-disk ===
tool version:          230
file size:         7159849 bytes
header size             80 bytes
strings            1784033 bytes
nodes              5375736 bytes
Load module index
Found container virtualization none
timestamp of '/etc/systemd/network' changed
timestamp of '/lib/systemd/network' changed
Skipping overridden file: /lib/systemd/network/99-default.link.
Parsed configuration file /etc/systemd/network/99-default.link
Created link configuration context.
ID_NET_DRIVER=ax88179_178a
Config file /etc/systemd/network/99-default.link applies to device $DEVICENAME
ID_NET_LINK_FILE=/etc/systemd/network/99-default.link
Unload module index
Unloaded link configuration context.
```

but no errors show up in the journal at all during device insertion with network-manager.

Failure to set explicitly-stated device policy warrants at least an error written to the journal.  Arguably, udev should refuse to enable the device at all if the stated policy is impossible to set.  This is especially important in this case, since continuing silently might compromise the user's anonymity.

**Comment by poettering** [comment]
The kernel doesn't allow renaming network devices or changing their MAC while they are up. The .link files are applied from udev. Normally NM shouldn't take possession of a device until it has shown up in udev, and thus the MAC addresses should be in place by the time NM sees them. If NM takes possesion of the device earlier, then this would really a bug in NM, not sure what we can do about that. In this case, this is really something for the NM folks to look into.

**Comment by dkg** [comment]
On Wed 2016-06-08 12:32:16 -0400, Lennart Poettering wrote:

> The kernel doesn't allow renaming network devices or changing their
> MAC while they are up. The .link files are applied from udev.

right, that makes sense.

> Normally NM shouldn't take possession of a device until it has shown
> up in udev, and thus the MAC addresses should be in place by the time
> NM sees them.

Presumably, udev expects to see a network device first before it
announces it to the rest of the O/S.  This gives it a chance to apply
system-specified policy for the device, right?

> If NM takes possesion of the device earlier, then this would really a
> bug in NM, not sure what we can do about that.

Right, if NM usurps udev's role, then it's clearly a bug in NM.

But it may also reveal a bug in udev: if/when the system-specified
policy cannot be applied, udev should treat that as a serious error,
right?  shouldn't it be logged as a serious error to the journal?  I saw
no warnings, errors, or other useful information in:

```
systemctl status udev
```

and i only saw one udev warning from:

```
journalctl --since today --follow
```

but i think it was unrelated:

```
Jun 08 15:29:36 alice systemd-udevd[10865]: failed to execute '/lib/udev/mtp-probe' 'mtp-probe /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2 1 30': No such file or directory
```

What should udev do when an explicitly-specified system policy cannot be
implemented?

> In this case, this is really something for the NM folks to look into.

I agree that it sounds like there is a bug in NM.  I've reported it over
at:

https://bugzilla.gnome.org/show_bug.cgi?id=767420

any additional comments from udev folks there to help explain the issue
would be welcome.

But i think there is still a bug in udev here (a silent failure to apply
system policy), which can potentially put the user at risk.

Regards,

```
   --dkg
```

**Comment by dkg** [comment]
Thanks to Thomas Haller's diagnostics, over on https://bugzilla.gnome.org/show_bug.cgi?id=708820, it looks like this is actually a bug entirely on network-manager's side.   after further testing, it looks like udev is silently succeeding in randomizing the mac address as expected, but network-manager is unrandomizing it back to the permanent address.

So i'm closing this issue, thanks for the help with diagnosis.
