### ISSUE TITLE
Slow operation and 80% CPU spike in {systemd} /sbin/init when running timedatectl set-ntp 

### ISSUE THREAD

**Issue by usvi** [systemd/systemd#34659]
### systemd version the issue has been seen with

256.6

### Used distribution

TI AM33XX Yocto Kirkstone 

### Linux kernel version used

6.1.46-myproduct-2024-02-15-g1d4b5da681

### CPU architectures issue was seen on

arm

### Component

systemd

### Expected behaviour you didn't see

I would expect the time required to complete the timedatactl operation to be under one second as is on my laptop

```
root@ESLD:~# time timedatectl set-ntp true
real	0m0.405s
user	0m0.000s
sys	0m0.005s
```

### Unexpected behaviour you saw

Instead, this is what I get on my AM33XX armv7l machine:

```
root@myproduct:~# time timedatectl set-ntp true
real    0m 12.09s
user    0m 0.01s
sys     0m 0.01s
```

At the same time, CPU usage of {systemd} /sbin/init goes and stays high, I have seen spikes over 80 %:
```
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
1       0 root     S    27600  11%  83% {systemd} /sbin/init
```

### Steps to reproduce the problem

Happens always when switching timedatectl set-ntp setting from true to false or from false to true. A no-op is considerably faster, taking about < 1 second.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
root@myproduct:~# systemctl --version
systemd 256 (256.6)
+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP -LIBCRYPTSETUP_PLUGINS +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP -SYSVINIT -LIBARCHIVE
```

**Comment by usvi** [comment]
Happens also on 250.5

```
root@myproduct:~# systemd-cat --version
systemd 250 (250.5+)
+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid

root@myproduct:~# time timedatectl set-ntp true
real	0m 9.62s
user	0m 0.01s
sys	0m 0.02s
```

Interestingly, the time required on 250.5 was a bit less.

**Comment by usvi** [comment]
I'm versatile in programming but I'm not that knowledgeable with debugging systemd. If you give me pointers how get proper debug logs etc, I can check it out.

**Comment by usvi** [comment]
Btw, doing sudo su - spikes the cpu also (256.6)
```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  883     1 root     S     8572   4%  76% /usr/lib/systemd/systemd --user
```

**Comment by usvi** [comment]
And for comparison, an older release. Version 239 takes 5 seconds changing the ntp.
```
root@am335x-evm:~# uname -r
4.19.94-gbe5389fd85
root@am335x-evm:~# systemctl --version
systemd 239
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid
root@am335x-evm:~# time timedatectl set-ntp true
real    0m 5.03s
user    0m 0.01s
sys     0m 0.01s
```

**Comment by poettering** [comment]
"timedatectl set-ntp" will enable/disable a unit and ask PID 1 to reload its entire config. That is always a slow operation, in particular on slow disks or if you have a lot of units installed.

**Comment by yuwata** [comment]
Right. Not a bug. Expected behavior.

**Comment by poettering** [comment]
enabling a service changes the unit file tree in /etc/systemd/system/. i.e. that's a persistent change, that requires reloading config of PID 1 to be honoured.

starting/stopping/restarting a service does not do any of that, it's a runtime state change. And is hence much much cheaper.

Reconfiguration: potentially somewhat expensive on slow hw. Runtime change: cheap.
