### ISSUE TITLE
journalctl and systemd-journal-gateway

### ISSUE THREAD

**Issue by apengue** [systemd/systemd#3467]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 219-19.el7_2.9

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> centos 7.2.1511
### In case of bug report: Expected behaviour you didn't see

> gateway showing same entries as journalctl -a
### In case of bug report: Unexpected behaviour you saw

> gateway not showing own unit standard output and standard error
### In case of bug report: Steps to reproduce the problem

> create own unit file for a nodejs application. Add StandardOutput=journal and StandardError=journal in the unit file. Trigger some standard output and standard error lines, and see the lines either in /var/log/messages either in the journal files (check with "strings /var/log/journal/... | grep <string>") as well as with "journalctl -a|grep _string" and try to find the same on web interface.

**Comment by poettering** [comment]
We only track the two most recent systemd versions upstream. Please ask downstream for help for older versions. Thank you for understanding.
