### ISSUE TITLE
get_process_cmdline() returns truncated cmdline / replaces trailing '\0' with spaces

### ISSUE THREAD

**Issue by mcspr** [systemd/systemd#3469]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230
### Used distribution

> Debian Unstable
### In case of bug report: Expected behaviour you didn't see

For example, server running nginx:

> `ps -C nginx -o pid=,cmd=`
> 
> ```
> 5344 nginx: master process /usr/sbin/nginx
> 5345 nginx: worker process
> ```
> 
> `systemd-cgls | grep nginx`
> 
> ```
> │ ├─nginx.service
> │ │ ├─5344 nginx: master process /usr/sbin/nginx
> │ │ └─5345 nginx: worker process
> ```
### In case of bug report: Unexpected behaviour you saw

Last character in cmdline of the process gets cut

> `systemd-cgls --all | grep nginx`
> 
> ```
> │ ├─nginx.service
> │ │ ├─5344 nginx: master process /usr/sbin/ngin
> │ │ └─5345 nginx: worker proces
> ```

Because `/proc/534{3,4}/cmdline` file lacks `\0` at the end 
### In case of bug report: Steps to reproduce the problem

Simply run `nginx`, `sshd` or some other program changing cmdline at runtime. `/proc/$pid/cmdline` will either have no trailing `\0` or multiple trailing `\0` depending on how long was the original cmdline of master process.
- `systemd-cgls` would display truncated cmdline
- `journalctl -o json` for ssh service would display _CMDLINE truncated or with multiple trailing spaces

I did a bit of testing with `get_process_cmdline` (src/basic/process-util.c) using the test suite and it returns proper cmdline when `max_length=$cmdline_length (or greater)`. [I've modified](https://github.com/mcspr/systemd/commit/fc8ac4297aaf3f94e3b91a38834848977c27081d) it for `max_length=0` to use the same logic and not simply replace everything non-printable with spaces.

**Comment by poettering** [comment]
Hmm, i figure nginx rewrites its argv[] and doesn't add a trailing NUL byte, the way the kernel would do it. That's a bit dirty of nginx but I figure we should handle that nicely anyway.

**Comment by mcspr** [comment]
[This code from nginx rewrites argv](https://github.com/nginx/nginx/blob/master/src/os/unix/ngx_setproctitle.c)
[Plus, this code from util-linux login util does same thing](https://github.com/karelzak/util-linux/blob/master/lib/setproctitle.c)
Both just strcpy string into NUL padded memory

Another example with extra spaces:
`ps -C login -o pid=,cmd=`

```
1491 login -- maxim
```

`sudo journalctl -b 0 _PID=1491 -o json-pretty | grep CMDLINE`

```
"_CMDLINE" : "/bin/login --      ",
"_CMDLINE" : "login -- maxim     ",
```
