### ISSUE TITLE
polkit "actions" integration fails for paths moved from /lib to /usr/lib

### ISSUE THREAD

**Issue by wdoekes** [systemd/systemd#34712]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 24.04 (noble)

### Linux kernel version used

5.15.0-83-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-ask-password

### Expected behaviour you didn't see

According to the docs in https://github.com/systemd/systemd/blob/70516b026b7a83dbe7b8141c67f2dbe412ce24d9/docs/PASSWORD_AGENTS.md?plain=1#L43-L46 we should call /lib/systemd/systemd-reply-password. However, on Ubuntu/Noble, /lib is symlinked to /usr/lib. The binary is still there, but matching by path fails for polkitd.

When running my `polkit.addRule` function I expected to see action.id `org.freedesktop.systemd1.reply-password`.
```
$ pkexec /lib/systemd/systemd-reply-password 1 2 < /dev/null 
Got EOF while reading password.
```

### Unexpected behaviour you saw

When running my `polkit.addRule` function I saw action.id `org.freedesktop.policykit.exec`.
```
$ pkexec /lib/systemd/systemd-reply-password 1 2 < /dev/null 
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/lib/systemd/systemd-reply-password 1 2' as the super user
...
```

### Steps to reproduce the problem

Create a policykit-1 rules file `/etc/polkit-1/rules.d/systemd-reply-password.rules`:
```javascript
polkit.addRule(function(action, subject) {
    polkit.log("RULE action=" + action);
    if (action.id == "org.freedesktop.systemd1.reply-password") {
        polkit.log("RULE yes");
        return polkit.Result.YES;
    }
    return polkit.Result.NOT_HANDLED;
});
```
This shows that we don't get a `org.freedesktop.systemd1.reply-password` event.

If you follow the polkit actions, it turns out that the cause is in `/usr/share/polkit-1/actions/org.freedesktop.systemd1.policy`:
```xml
        <action id="org.freedesktop.systemd1.reply-password">
                <description gettext-domain="systemd">Send passphrase back to system</description>
                <message gettext-domain="systemd">Authentication is required to send the entered passphrase back to the system.</message>
                <defaults>
                        <allow_any>no</allow_any>
                        <allow_inactive>no</allow_inactive>
                        <allow_active>auth_admin_keep</allow_active>
                </defaults>
                <annotate key="org.freedesktop.policykit.exec.path">/usr/lib/systemd/systemd-reply-password</annotate>
        </action>
```
A call to `/usr/lib/systemd/systemd-reply-password` gets translated to `org.freedesktop.systemd1.reply-password`, but a call to `/lib/systemd/systemd-reply-password` does not.

#### Next steps

I don't think this is a systemd bug per se. But I thought you might like to know about it because it affects a large user base.

- I figure the best fix could be to have multiple annotations in the policy file. But polkit does not use more than one `org.freedesktop.policykit.exec.path`. (In fact, it uses the latest.)
- A different fix could be to have polkitd normalize the path (yes, a polkit RFE, not a systemd one).
- It appears that the action/annotation is limited to just one path. Which I find strange. (Preliminary test appears to keep the action with the earliest sorting annotation.)

Right now, I had to resort to a client fix like this:
https://github.com/ossobv/openvpn-u2f-setup/commit/80a146ebbc0888b248710fc7a90e433575724b1c#diff-14ff38dc3ad4c38a44076d06cb11bbb0fc64d30b674764dfe3e5902524adf873R358

Obviously I'd rather have it work for both paths. So adding a realpath(3) call in polkitd before checking the path [1] looks like a good move. Unless there are security implications I haven't thought of.

[1] https://github.com/polkit-org/polkit/blob/94e2b5471f8e559897a80f6dbd84f454debc0d38/src/programs/pkexec.c#L796-L799

Cheers,
Walter Doekes
OSSO B.V.

**Comment by poettering** [comment]
We do not support split /usr/ in systemd anymore, hence the old `/lib/systemd/systemd-reply-password` is simply a bug at this point. Will prep fix shortly.
