### ISSUE TITLE
`_outbound` doesn't resolve to `PreferredSource` when there are multiple IPs

### ISSUE THREAD

**Issue by okulev** [systemd/systemd#34739]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.6.54-cloud-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

`resolvectl query _outbound` to show the IP specified with `PreferredSource` in `*.network` file.

### Unexpected behaviour you saw

A different IP is shown that is also set for the interface.

### Steps to reproduce the problem

My redacted `/etc/systemd/network/50-static.network` follows:

```ini
[Network]

Address=p.q.r.s

Address=x:y::0/112
Address=x:y::1/112
Address=x:y::2/112
Address=x:y::3/112
Address=x:y::4/112
Address=x:y::5/112
Address=x:y::6/112
Address=x:y::7/112
Address=x:y::8/112
Address=x:y::9/112
Address=x:y::a/112
Address=x:y::b/112
Address=x:y::c/112
Address=x:y::d/112
Address=x:y::e/112
Address=x:y::f/112

LLMNR=no

[Route]
Gateway=p.q.r.1

[Route]
Gateway=x:y::ff
PreferredSource=x:y::0
```

`systemd-networkd` setups the following IPv6 routes:

```
# ip -6 r
x:y::/112 dev ens3 proto kernel metric 256 pref medium
fe80::/64 dev ens3 proto kernel metric 256 pref medium
default via x:y::ff dev ens3 proto static src x:y::0 metric 1024 pref medium
```

The IPv6 address visible from the outside is `x:y::0`:

```
# curl -L ipconfig.me
x:y::0
```

And now when I request my `_outbound` it wrongly prints one of the other IPv6:

```
# resolvectl query _outbound
_outbound: p.q.r.s                       -- link: ens3
           x:y::f                  -- link: ens3

-- Information acquired via protocol DNS in 4.9ms.
-- Data is authenticated: yes; Data was acquired via local or encrypted transport: yes
-- Data from: synthetic
```

I filed this report for `systemd-networkd` component because I think the problem is with the route setup above. When connect attempt for `_gateway` is made, the routing rule that is activated is `x:y::/112 dev ens3 proto kernel metric 256 pref medium` because it has lower preference value (256) than the preference value 1024 of the default route rule that has the `PreferredSource`.

A simple solution would be to include `src` in all relevant generated route rules (the `x:y::/112` one in the redacted example), instead of only in the default route rule. It's another question whether this is correct, since the `[Route]` section where `PreferredSource` is defined is specifically for the default route. On the other hand, one expects that `_outbound` includes all possible source IPs, independent of whether destination is Internet or local network.

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #34745.

**Comment by okulev** [comment]
Thank your for the quick resolution!

The probing for `_outbound` described in its documentation no longer happens when there is `PreferredSource`. Shouldn't  **systemd-resolved(8)** also be extended for the `PreferredSource` case?

**Comment by yuwata** [comment]
-> #34770.
