### ISSUE TITLE
RestartMode=direct not working as advertised with dependent services

### ISSUE THREAD

**Issue by dawagner** [systemd/systemd#34758]
### systemd version the issue has been seen with

255.12

### Used distribution

Fedora 40

### Linux kernel version used

6.10.11-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

With the following setup, inspired by the tests introduced for RestartMode=direct:

dependent.service:
```
[Unit]
Requires=succeeds-on-restart.service

[Service]
ExecStart=/bin/sh -c "while true; do sleep 3000; done"
```

succeeds-on-restart.service
```
[Service]
Type=oneshot
ExecStart=/tmp/succeeds-on-restart.sh
Restart=on-failure
RestartMode=direct
```

/tmp/succeeds-on-restart.sh:
```
#! /bin/bash

if [[ ! -f "/tmp/succeeds-on-restart.ko" ]]
then
    touch "/tmp/succeeds-on-restart.ko"
    exit 1
else
    rm "/tmp/succeeds-on-restart.ko"
    exit 0
fi
```

I expect `dependent.service` to start exactly once when calling `systemctl start dependent.service`.

### Unexpected behaviour you saw

Instead, I'm getting this:

```
Started dependent.service.
Starting succeeds-on-restart.service...
succeeds-on-restart.service: Main process exited, code=exited, status=1/FAILURE
succeeds-on-restart.service: Failed with result 'exit-code'.
succeeds-on-restart.service: Scheduled restart job, restart counter is at 1.
Stopping dependent.service...
Starting succeeds-on-restart.service...
Stopped dependent.service.
Started dependent.service.
Finished succeeds-on-restart.service.
```

**Comment by dawagner** [comment]
Thanks @YHNdnzj for working on this!

**Comment by poettering** [comment]
First of all, Requires= almost certainly should have After= as well.

**Comment by YHNdnzj** [comment]
> First of all, Requires= almost certainly should have After= as well.

So, hmm, I think `After=` would help in this particular case, but not when e.g. BindsTo= is used or when a dependent requires multiple units which has no ordering relationship. Let's say `dependent.service` has `Requires=` and `After=` `a.service b.service`, both are of `Type=oneshot` and a.service uses `RestartMode=direct` - if a.service fails, should b.service be re-activated because now dependent.service would be restarted?

**Comment by dawagner** [comment]
@poettering : I have a use-case where I have a "main" target and dependent services using either `BindsTo=` or `Wants=` and the "main" target is also `Before=` the dependent services: that ensure that, when the target stops, the services have already been stopped too. Do you think that's an anti-pattern?

I did this because I'm trying to transition away from a codebase that used transitive services started by a "main" service ; when the main service ended, it brought the dependent units down as well but the dependent units could take longer to end but since the main service was stopped, it could be started anew, starting new transitive units and they would conflict on resources still used by the previous set of transitive units. Does that make sense? I'm using `(BindsTo|Wants)=+Before=` to prevent this.
