### ISSUE TITLE
Unit peak memory reporting incorrect

### ISSUE THREAD

**Issue by lheckemann** [systemd/systemd#34754]
### systemd version the issue has been seen with

255.9

### Used distribution

NixOS 24.05

### Linux kernel version used

6.11.2

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

systemd should log peak memory usage of units to the journal correctly when they die.

### Unexpected behaviour you saw

systemd logs peak memory usage at the last point it was queried(?) from the service manager when the unit exits, even if the memory usage went higher afterwards.

### Steps to reproduce the problem

Compare the journal entries generated by the following commands:
- `systemd-run --user --scope sh -c 'head -c 500M /dev/zero | sort >/dev/null'` -- I would expect 500M peak memory usage to be logged, but no peak memory usage is logged at all
- `PAGER=cat systemd-run --user --scope sh -c 'head -c 500M /dev/zero | sort >/dev/null; systemctl --user status $$'` -- 500M peak memory usage is logged, as I would have expected from the first command
- `PAGER=cat systemd-run --user --scope sh -c 'head -c 500M /dev/zero | sort >/dev/null; systemctl --user status $$; head -c 4G /dev/zero | sort >/dev/null'` -- 500M peak memory usage is logged, but I would expect 4G

**Comment by YHNdnzj** [comment]
Already fixed in https://github.com/systemd/systemd/pull/30399. Please try v256.

**Comment by lheckemann** [comment]
I tried applying just that patch, and the reporting is still inaccurate if I don't ask for the statistics before the unit dies:
```
Oct 14 10:23:50 geruest systemd[2840]: Started /home/linus/.nix-profile/bin/sh -c "head -c 4G /dev/zero | sort >/dev/null".
Oct 14 10:23:54 geruest systemd[2840]: run-r575b1778a849403dbf687e4245dd32f0.scope: Consumed 6.138s CPU time, 3.8G memory peak, 164.4M memory swap peak.
Oct 14 10:24:07 geruest systemd[2840]: Started /home/linus/.nix-profile/bin/sh -c "head -c 4G /dev/zero | sort >/dev/null; systemctl --user status \$\$".
Oct 14 10:24:09 geruest systemd[2840]: run-r6ff06f4b08f640aeb8915ec146e3f47e.scope: Consumed 4.379s CPU time, 4.0G memory peak, 0B memory swap peak.
```
