### ISSUE TITLE
memory.swap.max == max contrary to systemctl show/expectation

### ISSUE THREAD

**Issue by tmada** [systemd/systemd#34766]
### systemd version the issue has been seen with

252

### Used distribution

Rocky 9

### Linux kernel version used

5.14.0-427.22.1.el9_4.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Swap is disabled for all decedents of lsg.slice

### Unexpected behaviour you saw

Without `DisableControllers=memory` any decedents defaulted to `memory.swap.max` == `max` and the `lsg.slice` root had `memory.swap.max` == 0

When adding `DisableControllers=memory` decedents no longer had access to the memory controller, however, `lsg.slice` root now has `memory.swap.max` set to `max`

### Steps to reproduce the problem

1. Create a slice
```cat /etc/systemd/system/lsg.slice 
Description=lsg Sliceca
Documentation=man:systemd.special(7)
DefaultDependencies=no
Before=slices.target
Requires=-.slice
After=-.slice

[Slice]
DisableControllers=memory
AllowedCPUs=8-19
AllowedMemoryNodes=1-2
MemorySwapMax=0
```
2. Assign a service unit the slice 
```[root@lsg-04.dc3 ~]# cat /etc/systemd/system/lsg@.service 
[Unit]
Description=lsg
After=...

[Service]
User=lsg
Slice=lsg.slice

WorkingDirectory=...
ExecStartPre=...
ExecStart=...

Restart=always

[Install]
WantedBy=multi-user.target
```
3. `systemctl daemon-reload`
4. `systemctl restart lsg.slice` 
5. One can observe lsg unit processes are swapping and in looking in `/sys/fs/cgroup/lsg.slice/memory.swap.max` we see `max`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# systemctl show lsg.slice |grep Swap
MemorySwapMax=0

# cat /sys/fs/cgroup/lsg.slice/memory.swap.max 
max
```

**Comment by tmada** [comment]
Wanted to note that the original title was misleading in the fact that one can write a zero to `/sys/fs/cgroup/lsg.slice/memory.swap.max ` && `swapoff ...` && `swapon -a`
and the child threads would adhere to the restriction

**Comment by poettering** [comment]
/
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
