### ISSUE TITLE
The io.systemd.MachineImage interface can't be introspected

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#34772]
### systemd version the issue has been seen with

afc5a14fcab2c31225ccecf89ed42db865ad4e1c

### Used distribution

Fedora 40

### Linux kernel version used

Linux version 6.10.12-200.fc40.x86_64

### CPU architectures issue was seen on

None

### Component

systemd-machined

### Expected behaviour you didn't see

It should be possible to discover the io.systemd.MachineImage interface automatically.

### Unexpected behaviour you saw

```sh
$ varlinkctl list-interfaces /run/systemd/machine/io.systemd.MachineImage 
io.systemd
io.systemd.Machine
org.varlink.service

$ varlinkctl introspect /run/systemd/machine/io.systemd.MachineImage io.systemd.MachineImage
Failed to issue org.varlink.service.GetInterfaceDescription() varlink call: org.varlink.service.InterfaceNotFound
```

**Comment by yuwata** [comment]
-> #34774.
