### ISSUE TITLE
systemd-ask-password prints garbage

### ISSUE THREAD

**Issue by H5117** [systemd/systemd#34785]
### systemd version the issue has been seen with

256.7

### Used distribution

Arch Linux

### Linux kernel version used

linux 6.11.3-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-ask-password

### Expected behaviour you didn't see

```
# systemd-ask-password --no-tty > /tmp/password.txt
# hexdump /tmp/password.txt
00000000  31 32 33 0a                                       |123.|
00000004
```

### Unexpected behaviour you saw

```
# systemd-ask-password --no-tty > /tmp/password.txt
# hexdump /tmp/password.txt
00000000  31 32 33 0a 70 0a                                 |123.p.|
00000006
```

### Steps to reproduce the problem

1. Write the password agent that sends a string "123\n" without terminating 0x00 to the provided socket.

According to [the specification](https://systemd.io/PASSWORD_AGENTS/) it is allowed to send passwords without 0x00:

> If you do not want to use PK ensure to acquire the necessary privileges in some other way and send a single datagram to the socket consisting of the password string either prefixed with “+” or with “-” depending on whether the password entry was successful or not. You may but don’t have to include a final NUL byte in your message.

**Comment by poettering** [comment]
i cannot reproduce this issue here.

Is it possible you have multiple passwords cached already?

Can you provide an "strace -s 500 -y -o mylogfile" log file of the `systemd-ask-password` invocation?

**Comment by H5117** [comment]
My fault, I just send extra character to the socket in my agent. Sorry for false alarm.
