### ISSUE TITLE
CREDENTIALS_DIRECTORY environment variable is unset despite LoadCredential= in ExecStop for Type=exec and Type=simple

### ISSUE THREAD

**Issue by sternenseemann** [systemd/systemd#34805]
### systemd version the issue has been seen with

256.4

### Used distribution

NixOS unstable 24.11pre9357f4f23713

### Linux kernel version used

6.1.61

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Credentials loaded via `LoadCredential` are available in `ExecStart` and `ExecStop` via `${CREDENTIALS_DIRECTORY}`.

### Unexpected behaviour you saw

`${CREDENTIALS_DIRECTORY}` was set correctly in `ExecStart`, but unset in `ExecStop`.

Interestingly, a viable workaround is to create a environment variable manually: E.g. `Environment=MY_CREDENTIAL=%d/cred` would cause `${MY_CREDENTIAL}` to be set correctly in `ExecStart` and `ExecStop`.

This may or may not be related to #32612 / #32583.

### Steps to reproduce the problem

Note that this is a regression (though I don't know (yet) between which versions exactly this broke). Originally the service I've experienced this with had `Type=simple`. With 256.4, I believe, systemd would interpret this as `Type=exec` automatically (#32612), so the reproducer uses `Type=exec`. I do not know if this used to work with `Type=exec`, but I don't see why it shouldn't.

1. Create a `reproducer.service` similar to the following. Important are the `Environment="CRED=…"` and `LoadCredential` calls. Whether `Type=exec` or `Type=simple` is used, doesn't matter in 256.4.
```
# /etc/systemd/system/reproducer.service
[Unit]
Description=Reproducer for ExecStop cred issue

[Service]
Environment="CRED=%d/cred"
Environment="LOCALE_ARCHIVE=/nix/store/d6myxy49v33ir221631mrcj9iz7myzmc-glibc-locales-2.39-52/lib/locale/locale-archive"
Environment="PATH=/nix/store/0kg70swgpg45ipcz3pr2siidq9fn6d77-coreutils-9.5/bin:/nix/store/fnq94lw19pnwdl9p8zhfrad4jmlgxlbr-findutils-4.10.0/bin:/nix/store/vsyc8jhsr4d9lm2r8yqq9n3j4i66inlj-gnugrep-3.11/bin:/nix/store/gjlh1zvckhz0qv795lnzgw2zciklbzj2-gnused-4.9/bin:/nix/store/1lbc6v5p1a3rn4rjaqnz0694xfbq8dxq-systemd-256.4/bin:/nix/store/0kg70swgpg45ipcz3pr2siidq9fn6d77-coreutils-9.5/sbin:/nix/store/fnq94lw19pnwdl9p8zhfrad4jmlgxlbr-findutils-4.10.0/sbin:/nix/store/vsyc8jhsr4d9lm2r8yqq9n3j4i66inlj-gnugrep-3.11/sbin:/nix/store/gjlh1zvckhz0qv795lnzgw2zciklbzj2-gnused-4.9/sbin:/nix/store/1lbc6v5p1a3rn4rjaqnz0694xfbq8dxq-systemd-256.4/sbin"
Environment="TZDIR=/nix/store/897xqnq52vw76991r5m80h9j91370vj9-tzdata-2024a/share/zoneinfo"
DynamicUser=true
ExecStart=:/bin/sh -c "set -u; exec echo ExecStart $CREDENTIALS_DIRECTORY/cred"
ExecStop=:/bin/sh -c "set -u; exec echo ExecStop 1 $CRED"
ExecStop=:/bin/sh -c "set -u; exec echo ExecStop 2 $CREDENTIALS_DIRECTORY/cred"
LoadCredential=cred:/etc/hostname
Type=exec

[Install]
WantedBy=multi-user.target
```
2. Start the service, you will observe `ExecStart` and the first `ExecStop` line working as expected, but the second `ExecStop` command failing:
```
Oct 17 18:34:17 ingeborg systemd[1]: Starting Reproducer for ExecStop cred issue...
Oct 17 18:34:17 ingeborg systemd[1]: Started Reproducer for ExecStop cred issue.
Oct 17 18:34:17 ingeborg sh[208880]: ExecStart /run/credentials/reproducer.service/cred
Oct 17 18:34:17 ingeborg sh[208885]: ExecStop 1 /run/credentials/reproducer.service/cred
Oct 17 18:34:17 ingeborg sh[208894]: /bin/sh: line 1: CREDENTIALS_DIRECTORY: unbound variable
Oct 17 18:34:17 ingeborg systemd[1]: reproducer.service: Control process exited, code=exited, status=127/n/a
Oct 17 18:34:17 ingeborg systemd[1]: reproducer.service: Failed with result 'exit-code'.
```

**Comment by sternenseemann** [comment]
I've also tried using `systemd-cred` instead of accessing the environment variable manually, but this made no difference.

**Comment by YHNdnzj** [comment]
> Credentials loaded via LoadCredential are available in ExecStart and ExecStop via ${CREDENTIALS_DIRECTORY}.

Hmm? We only set up creds for ExecStart*=. The current behavior is very much expected. If ExecStop= used to receive creds, it was a bug.

**Comment by YHNdnzj** [comment]
> Interestingly, a viable workaround is to create a environment variable manually: E.g. Environment=MY_CREDENTIAL=%d/cred would cause ${MY_CREDENTIAL} to be set correctly in ExecStart and ExecStop.

Note that this is merely a hack that works when the unit isn't using mount namespace. Otherwise the cred mount wouldn't exist at all in ExecStop= processes.

Sorry, but I disagree that ExecStop= should be granted cred access. Closing this hence.

**Comment by sternenseemann** [comment]
The documentation does not clearly communicate that it is only expected to be available in `ExecStart` which is a problem given that it *did* work in the past. Too bad that wrapping some services in a nice way requires credentials in `ExecStop`.

What is the reasoning for not having credentials in `ExecStop`? Is there a technical reason?
