### ISSUE TITLE
ProtectHome=tmpfs does not make /home,  /run/user and /root read-only

### ISSUE THREAD

**Issue by ryantimwilson** [systemd/systemd#34825]
### systemd version the issue has been seen with

257

### Used distribution

Centos 9 Stream

### Linux kernel version used

kernel-6.9

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

Based on the documentation, ProtectHome=tmpfs should make  /home,  /run/user and /root read-only: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectHome=

> If set to "tmpfs", temporary file systems are mounted on the three directories in read-only mode. 

### Unexpected behaviour you saw

However, the directories are mounted read-write.

### Steps to reproduce the problem

Run the following command like:
```
$ systemd-run -p ProtectHome=tmpfs --wait -t bash -c "mount | grep /run"
tmpfs on /run/user type tmpfs (rw,relatime,inode64)
```

The bug is due to the following:
1. ProtectHome=tmpfs has a static mounts table: https://github.com/systemd/systemd/blob/12e58ab18df31e8009e3cc5e55a3d4b738f9bef0/src/core/namespace.c#L190-L194
2. It is mounted via append_static_mounts()
3. However, append_static_mounts ignores all MountEntry fields except path_const, mode and ignore: https://github.com/systemd/systemd/blob/12e58ab18df31e8009e3cc5e55a3d4b738f9bef0/src/core/namespace.c#L706

As far as I can tell, this is a documentation issue since we have an integration test verifying that ProtectHome=tmpfs has a writable /home: https://github.com/systemd/systemd/blob/12e58ab18df31e8009e3cc5e55a3d4b738f9bef0/test/units/TEST-07-PID1.exec-context.sh#L58-L59

This may also be an issue for /run as well which has options it is expected to be mounted with but is not: https://github.com/systemd/systemd/blob/12e58ab18df31e8009e3cc5e55a3d4b738f9bef0/src/core/namespace.c#L135

**Comment by yuwata** [comment]
Fix is waiting in #34834.
