### ISSUE TITLE
systemd-networkd fails to drop routes & addresses on stop with `KeepConfiguration=no`

### ISSUE THREAD

**Issue by ckiee** [systemd/systemd#34837]
### systemd version the issue has been seen with

~~v255.6~~ v256 onwards, reproduces on v256.4

### Used distribution

NixOS unstable 24.11pre-git (since `a5b2fe73` up to `5633bcf`)

### Linux kernel version used

Both 6.6.54-xanmod1, 6.6.54

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

`[Network].KeepConfiguration=no` is respected and networkd drops IPv4 addresses when stopped

### Unexpected behaviour you saw

After `SYSTEMD_LOG_LEVEL=debug systemctl import-environment SYSTEMD_LOG_LEVEL && systemctl restart systemd-networkd`, networkd logs show that it is attempting to drop addresses and routes but `ip r` and `ip a` show they are still present. With `networkctl down eth0`, this does not happen.

### Steps to reproduce the problem

Run the `systemd-initrd-networkd.doFlush` NixOS test from a nixpkgs newer than 2024-07-29.

Observe [it fails](https://hydra.nixos.org/build/267693996): ([full logs](https://cache.nixos.org/log/69432jppr8pfpjp3aq0z5bs8ri9d5f84-vm-test-run-systemd-initrd-network-flush.drv))
```
[   12.832587] check-flush-start[352]:     inet 10.0.2.15/24 metric 1024 brd 10.0.2.255 scope global dynamic eth0
[   12.837278] check-flush-start[345]: Network configuration survived switch-root; flushBeforeStage2 failed
```

```
$ networkctl cat 99-ethernet-default-dhcp.network
# /etc/systemd/network/99-ethernet-default-dhcp.network
[Match]
Name=en*
Name=eth*
 
[Network]
DHCP=yes
IPv6PrivacyExtensions=kernel
KeepConfiguration=no # KeepConfiguration is set
```

### Additional program output to the terminal or log subsystem illustrating the issue

`networkctl down eth0` correctly drops address:
https://gist.github.com/ckiee/53c0bcdcedbee8f985563cf3fbb8bea0

`systemctl stop systemd-networkd` tries to drop addresses and routes but fails.
https://gist.github.com/ckiee/b30551342e3d05722916c1e34bf007fc

**Comment by ElvishJerricco** [comment]
Correction, I believe v255.6 is unaffected by this. The first known affected version seems to be v256.

**Comment by ElvishJerricco** [comment]
It looks like `address_remove_handler` is never getting called after `address_remove` while `systemd-networkd` shuts down, which is because `manager_post_handler` is never called to handle the request that was queued by `link_remove_request_add`. I think the DHCP lease is being released, but the address is not being removed from the link.

**Comment by yuwata** [comment]
Indeed... Thank you for the report. I will take a look.

**Comment by ElvishJerricco** [comment]
@yuwata Either of these patches seems to resolve the issue.

This just processes the removal queue in `manager_free` after links are taken down.

```
diff --git a/src/network/networkd-manager.c b/src/network/networkd-manager.c
index 4ec4550caf..c17bf88b23 100644
--- a/src/network/networkd-manager.c
+++ b/src/network/networkd-manager.c
@@ -624,6 +624,8 @@ Manager* manager_free(Manager *m) {
         HASHMAP_FOREACH(link, m->links_by_index)
                 (void) link_stop_engines(link, true);
 
+        (void) manager_process_remove_requests(m);
+
         m->request_queue = ordered_set_free(m->request_queue);
         m->remove_request_queue = ordered_set_free(m->remove_request_queue);
 
```

And this takes down links in an exit handler instead of in `manager_free`.

```diff
diff --git a/src/network/networkd-manager.c b/src/network/networkd-manager.c
index 4ec4550caf..98c85cd7ee 100644
--- a/src/network/networkd-manager.c
+++ b/src/network/networkd-manager.c
@@ -431,6 +431,19 @@ static int manager_post_handler(sd_event_source *s, void *userdata) {
         return 0;
 }
 
+static int manager_exit_handler(sd_event_source *s, void *userdata) {
+        Link *link;
+
+        Manager *manager = ASSERT_PTR(userdata);
+
+        HASHMAP_FOREACH(link, manager->links_by_index)
+                (void) link_stop_engines(link, true);
+
+        (void) manager_post_handler(s, userdata);
+
+        return 0;
+}
+
 static int signal_terminate_callback(sd_event_source *s, const struct signalfd_siginfo *si, void *userdata) {
         Manager *m = ASSERT_PTR(userdata);
 
@@ -508,6 +521,10 @@ int manager_setup(Manager *m) {
         if (r < 0)
                 return r;
 
+        r = sd_event_add_exit(m->event, NULL, manager_exit_handler, m);
+        if (r < 0)
+                return r;
+
         r = manager_listen_fds(m, &rtnl_fd);
         if (r < 0)
                 return r;
@@ -614,16 +631,11 @@ int manager_new(Manager **ret, bool test_mode) {
 }
 
 Manager* manager_free(Manager *m) {
-        Link *link;
-
         if (!m)
                 return NULL;
 
         free(m->state_file);
 
-        HASHMAP_FOREACH(link, m->links_by_index)
-                (void) link_stop_engines(link, true);
-
         m->request_queue = ordered_set_free(m->request_queue);
         m->remove_request_queue = ordered_set_free(m->remove_request_queue);
 
```

I'm not really sure if either of this is a desirable solution. But they do fix the problem and *I believe* don't interfere with any other functionality. Feel free to use them.

**Comment by yuwata** [comment]
@ElvishJerricco Thank you for the proposal. I submitted a patch in #34871 that fixes the issue in a similar but slightly different way. PTAL.

**Comment by ckiee** [comment]
tysm!
