### ISSUE TITLE
Rectangle-character corruption of systemd shutdown messages (screenshot)

### ISSUE THREAD

**Issue by timrichardson** [systemd/systemd#34831]
### systemd version the issue has been seen with

systemd 255 (255.4-1ubuntu8.4)

### Used distribution

Ubuntu 24.04.1 (Desktop, wayland session)

### Linux kernel version used
6.8, 6.,11 OEM kernel

### CPU architectures issue was seen on

x86_64

### Component

Unknown

### Expected behaviour you didn't see

Log messages on shutdown console are readable.

tim@black:~$ systemd --version
systemd 255 (255.4-1ubuntu8.4)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

### Unexpected behaviour you saw

Log messages on shutdown console, after escaping the "splash" are not rendered well, only affecting systemd messages. Other log messages render normally, including with color control.

boot messages (startup) are all fine.
Screen shot:
https://imgur.com/a/TFTTRMJ
![PXL_20241018_231733721](https://github.com/user-attachments/assets/b9a04cbc-d584-41dd-93ea-65441614d2ac)

### Steps to reproduce the problem

Shutdown Ubuntu from gui
Escape (ESC key) to view shutdown messages

**Comment by poettering** [comment]
this is not really a systemd issue, we are not involved in rendering text on the console. That's between the kernel and plymouth I guess, at best an integration issue.

Please contact your downstrean about this instead. There's nothing immediately actionable to us in this. Should the downstream find a real issue they'll escalate back to us.
