### ISSUE TITLE
logind: expose a CanIdle dbus property

### ISSUE THREAD

**Issue by Flowdalic** [systemd/systemd#34844]
### systemd version the issue has been seen with

256.7

### Used distribution

Gentoo

### Linux kernel version used

6.11.3-gentoo-dist

### CPU architectures issue was seen on

None

### Component

systemd-logind

### Unexpected behaviour you saw

Starting with systemd 256, the system-wide idle hint, obtained on the `orgt.freedesktop.login1` `/org/freedesktop/login1` object from `org.freedesktop.login1.Manager` does not become true. This appears to be because the manager-early session does never set the idle hint.

Here is the log output of an autosuspend system, called "sandmann", which prints the sessions:

```text
Oct 21 04:22:21 flowplex sandmann[15401]: Logind reports active sessions, returning Active
                                          Active sessions: 
                                          - 2 u:gdm s: i:false (1970-01-01T00:00:00Z) p:HashMap(Id -> [2], Scope -> [], Service -> [systemd-user], VTNr -> [0], IdleSinceHint -> [0], Timestamp -> [1729116746373169],  Class -> [manager-early])
Oct 21 04:22:21 flowplex sandmann[15401]: Logind reports the following sessions: 
                                          - 2 u:gdm s: i:false (1970-01-01T00:00:00Z) p:HashMap(Id -> [2], Scope -> [], Service -> [systemd-user], VTNr -> [0], IdleSinceHint -> [0], Timestamp -> [1729116746373169], Class -> [manager-early])
                                          - 1 u:gdm s:seat0 i:true (2024-10-16T22:17:27.534924Z) p:HashMap(Id -> [1], Scope -> [session-1.scope], Service -> [gdm-launch-environment], VTNr -> [1], IdleSinceHint -> [1729117047534924], Timestamp -> [1729116746289082],  Class -> [greeter], IdleHint -> [true])
Oct 21 04:19:21 flowplex sandmann[15401]: Sleeping for PT3M
```

As you can see, session 1 of class 'greeter' has the IdleHint set, but session 2 of class 'manager-early' has not. Therefore, the system-wide idle hint is probably also set to `false`.

This prevents the systemd-external autosuspend mechanism of sandmann from suspending the system as it believes that not all sessions are idle.

**Comment by poettering** [comment]
> As you can see, session 1 of class 'greeter' has the IdleHint set, but session 2 of class 'manager-early' has not. Therefore, the system-wide idle hint is probably also set to `false`.

that's not really it. If you look into manager_get_idle_hint() you'll see we skip over all sessions for which SESSION_CLASS_CAN_IDLE() is not true. And only "user", "user-early" and "greeter" sessions qualify for true here.

**Comment by Flowdalic** [comment]
> that's not really it. If you look into manager_get_idle_hint() you'll see we skip over all sessions for which SESSION_CLASS_CAN_IDLE() is not true. And only "user", "user-early" and "greeter" sessions qualify for true here.

You are right. Thanks. After a second look, this appears to be sandmann not coping with the non-idle sessions of the new classes.

At one point in sandmann's logic, it iterates of all sessions and considers the system not-idle if a non-idle session is found. I assume the new session classes like manager-early never set their idle hint to `true`, right? I wonder if they should default to `true`. Or, alternatively, if the "can idle" property should be exposed via dbus?

That said, I am going to change sandmann's logic to only consider SESSION_CLASS_CAN_IDLE classes when checking that all sessions are idle. So, from my side, this issue can be closed.

**Comment by poettering** [comment]
Yeah, I think we probably should expose CanIdle, it's unrealistic to expect every client to know exactly which session types know a idle concept and which ones do not.
