### ISSUE TITLE
Hibernate without manually creating a swap file

### ISSUE THREAD

**Issue by jebez1** [systemd/systemd#34866]
### Component

systemd

### Is your feature request related to a problem? Please describe

I don't wanna manually create a swap file only to hibernate then resume then delete it ( https://wiki.debian.org/Hibernation/Hibernate_Without_Swap_Partition ) .

### Describe the solution you'd like

Dynamically sized swap file(s) working for hibernation , or at least automatically create the swap file at the moment of hibernation then delete it after resuming .

Implementation in Debian ( testing ) .

### Describe alternatives you've considered

https://github.com/Tookmund/Swapspace but
N.B. If you want suspend and resume to work you will still need a static swapfile!
https://github.com/Tookmund/Swapspace/issues/31

https://github.com/nefelim4ag/systemd-swap but
Q: Can we use this to enable hibernation?
A: Nope ...

### The systemd version you checked that didn't have the feature you are asking for

256.7-2

**Comment by jebez1** [comment]
" This is already doable by hooking custom units into hibernate.target. " , can you explain ?

Otherwise I tried something but it doesn't work https://forums.debian.net/viewtopic.php?p=809744#p809744 .

**Comment by YHNdnzj** [comment]
Sorry, but the initramfs generation and such is distro-specific and out of scope of systemd upstream bugtracker. Please reach out to your distro for assistance. Let's close this here.

**Comment by anohren** [comment]
> N.B. If you want suspend and resume to work you will still need a static swapfile!
> [Tookmund/Swapspace#31](https://github.com/Tookmund/Swapspace/issues/31)

The discussion in that thread could be worth following though
