### ISSUE TITLE
connection timed out on network device

### ISSUE THREAD

**Issue by QuentinPerez** [systemd/systemd#3486]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systems 230-3

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Archlinux
### In case of bug report: Expected behaviour you didn't see

> Keep alive the connection when the rootfs is over network
### In case of bug report: Unexpected behaviour you saw

> kernel panic
### In case of bug report: Steps to reproduce the problem

> https://github.com/scaleway/image-archlinux/issues/32

**Comment by poettering** [comment]
hmm? what precisely is this about? this bug report is way to terse to make out anything. What precisely are you saying that systemd doesn't do right?

**Comment by johannbg** [comment]
@poettering if you look the linked report there in bottom, there seems to be some network related regression that takes place between systemd-229-3 ( where things work ) and systemd-230-3 ( where things fail ) on Arch but there are no usable logs on that report. 

@QuentinPerez can you provide logs which might shed light on whats actually going on?

**Comment by poettering** [comment]
Is networkd being used here and CriticalConnection= set for the network interface in question?

**Comment by QuentinPerez** [comment]
Thanks you @poettering, works with `CriticalConnection=true` 👍
