### ISSUE TITLE
user session stops right after startup

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#3487]
Not sure what changed, but X starts and pops up (along with some other services), but before you know it, the session is torn down. The logs go right from "Reached target default" to "Startup finished in 9.604s" to "Stopped target default". Is there any way to debug _why_ the default target is being stopped? Using systemd-230-2.fc25. Logs says that it was happening in 229 as well.

**Comment by mathstuf** [comment]
If I strip default.target to only Wants= a oneshot unit which sets an environment variable, it also shuts down immediately. What am I not doing to cause the target to persist?

**Comment by poettering** [comment]
Booting with "systemd.log_level=debug" will usually let you know precisely why something is done. See https://freedesktop.org/wiki/Software/systemd/Debugging/ for details.

Closing this one, as this is really a bug and RFE tracker, not a support forum, and this doesn't appear to be a bug in systemd really. Please ask for help on your distro's forums or on the systemd mailing list, which is our suppotr forum. if you are sure you found a bug in systemd and can pinpoint it, please file a new bug.

**Comment by mathstuf** [comment]
Seems SELinux related. Right around the shutdown logs, there's an AVC denial followed by some D-Bus chatter for StopUnit and then the user service starts to go down. Doing `setenforce 0` lets the session start properly.
