### ISSUE TITLE
udev rules change makes Motorola G14 phone appear as non-removable storage

### ISSUE THREAD

**Issue by gzuaps** [systemd/systemd#34873]
### systemd version the issue has been seen with

255.13 and 255.4

### Used distribution

Fedora 40

### Linux kernel version used

kernel-core-6.11.3-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

device name is correct  Motorola G14  OR Moto G14
device identified as removable storage

This is the original behaviour, this has been changed in recent releases.

### Unexpected behaviour you saw

device name is now lion
device identified as non-removable storage

### Steps to reproduce the problem

attach phone to laptop
wait for phone to appear in device popup as removable device with name Motorola G14

### Additional program output to the terminal or log subsystem illustrating the issue

Bus 003 Device 011: ID 22b8:2e76 Motorola PCS lion

**Comment by poettering** [comment]
> device name is now lion
> device identified as non-removable storage

What is this about? Where are you seeing the device name? And where does it show up as non-removable?

**Comment by yuwata** [comment]
No response. There is nothing we can do. Closing.
