### ISSUE TITLE
sd_event_set_signal_exit leaks memory when compiled without assertions

### ISSUE THREAD

**Issue by polarina** [systemd/systemd#34899]
The implementation of `sd_event_set_signal_exit` contains `assert()` statements with side-effects, namely the setting of floating and non-floating mode of the SIGINT and SIGTERM event sources.

https://github.com/systemd/systemd/blob/f7078de515efd7089266815648b6e682f800649f/src/libsystemd/sd-event/sd-event.c#L5272

When compiled with assertions disabled, the event sources remain non-floating and pin the event loop itself. A comment even warns about this danger:

https://github.com/systemd/systemd/blob/f7078de515efd7089266815648b6e682f800649f/src/libsystemd/sd-event/sd-event.c#L5263-L5265

---

On another note, these assertions trigger rather than returning `-ECHILD` when disabling the signal handlers.
```c
#include <unistd.h>
#include <stdlib.h>
#include <systemd/sd-event.h>

int main(void) {
	struct sd_event *event;
	int r = 0;

	r = sd_event_new(&event);
	if (r < 0) abort();

	r = sd_event_set_signal_exit(event, 1);
	if (r < 0) abort();

	pid_t pid = fork();
	if (pid == 0) {
		r = sd_event_set_signal_exit(event, 0);
		if (r < 0) abort();
		return 0;
	}

	sd_event_unref(event);
	return 0;
}
```
```
$ gcc -g -lsystemd -fsanitize=address,undefined signal.c -o signal && ./signal
Assertion 'sd_event_source_set_floating(e->sigint_event_source, false) >= 0' failed at src/libsystemd/sd-event/sd-event.c:5254, function sd_event_set_signal_exit(). Aborting.
```

**Comment by yuwata** [comment]
Thanks. Waiting in #34900.
