### ISSUE TITLE
Forcibly rebooting with Ctrl+Alt+Del requires too much keypressing

### ISSUE THREAD

**Issue by bjourne** [systemd/systemd#34905]
### Component

bootctl

### Is your feature request related to a problem? Please describe

You get this message after having pressed ctrl+alt+del lots of times during shutdown/reboot:
```
Forcibly rebooting: Ctrl-Alt-Del was pressed more than 7 times within 2s
```
Please require just ONE ctrl+alt+del key press to trigger reboot: 1. No one presses ctrl+alt+del by mistake (the keys are far apart). 2. Having to press ctrl+alt+del seven times in two seconds is a real accessibility nightmare for users with reduced hand dexterity.

### Describe the solution you'd like

One Ctrl+Alt+Del is enough.

### The systemd version you checked that didn't have the feature you are asking for

systemd 256 (256.7-1-arch)

**Comment by poettering** [comment]
One ctrl-alt-del results in a regular reboot. Pressing it 7 times however results in a forced, immediate reboot. That means services are not shut down cleanly, file systems not necessarily cleaned up and so on. It's an emergency operation with serious implications, and not an operation that you should just issue.

Hence i am pretty sure everything is great the way it is.
