### ISSUE TITLE
`loginctl list` commands do not respect `--output` modes at all

### ISSUE THREAD

**Issue by fiftydinar** [systemd/systemd#34901]
### systemd version the issue has been seen with

256

### Used distribution

Fedora 41

### Linux kernel version used

6.11.4-301.fc41.x86_64

### CPU architectures issue was seen on

None

### Component

loginctl

### Expected behaviour you didn't see

Output shown in json

### Unexpected behaviour you saw

Output of classic `loginctl list-users` or `loginctl list-session`

### Steps to reproduce the problem

1. Enter `loginctl list-users --output={MODE}`
    Also try `loginctl list-session --output={MODE}` 
3. See the unexpected behavior 

### Additional comment

Systemd 255 doesn't have this regression.

**Comment by YHNdnzj** [comment]
This is expected behavior. For details, please refer to the commit msg of https://github.com/systemd/systemd/pull/30958/commits/ea54517476521a35fd10790664f2525a03c582b6

**Comment by dustymabe** [comment]
Clearly this was a regression. Not saying we want to go back to the old behavior or not but:

on Fedora CoreOS `40.20241019.2.0`:

```
[core@cosa-devsh ~]$ rpm -q systemd
systemd-255.13-1.fc40.x86_64
[core@cosa-devsh ~]$ loginctl list-sessions --output=json | cat
[{"session":"1","uid":1000,"user":"core","seat":null,"tty":null,"state":"active","idle":false,"since":null},{"session":"3","uid":1000,"user":"core","seat":"seat0","tty":"tty1","state":"active","idle":false,"since":null},{"session":"4","uid":1000,"user":"core","seat":null,"tty":"ttyS0","state":"active","idle":false,"since":null}]
```

on Fedora CoreOS `41.20241027.2.0`:


```
[core@cosa-devsh ~]$ rpm -q systemd
systemd-256.7-1.fc41.x86_64
[core@cosa-devsh ~]$ loginctl list-sessions --output=json
SESSION  UID USER SEAT  LEADER CLASS   TTY   IDLE SINCE
      1 1000 core seat0 2251   user    tty1  no   -    
      2 1000 core -     2252   user    ttyS0 no   -    
      3 1000 core -     2308   manager -     no   -    
      5 1000 core -     2405   user    -     no   -    

4 sessions listed.
```

Glad it was easy enough to find this issue. I'll update our stuff to use `--json=short`.
