### ISSUE TITLE
systemd-networkd fails to reload .netdev units

### ISSUE THREAD

**Issue by polarina** [systemd/systemd#34907]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.11.4-201.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

I got a VLAN interface defined by a `.netdev` unit. I want to effectively "change" the VLAN ID by deleting and recreating the interface.

For example, a VLAN interface named `myvlan` exists. Then:
1. Modify `Id=2` to `Id=3` under the `[VLAN]` section of its `myvlan.netdev` file.
2. `networkctl delete myvlan`
3. `networkctl reload`

I would expect the VLAN interface to have been deleted, recreated, and now under VLAN ID 3.

In systemd v255 nor v256, neither happens. The VLAN interface is not recreated.
In systemd v249, both happen. The interface is recreated under VLAN ID 3.

I've not tested intermediate releases.

### Unexpected behaviour you saw

Two issues:
1. Issuing `networkctl reload` does not recreate the `myvlan` interface. By executing `touch` on the parent's `.network` file, a subsequent `networkctl reload` will however recreate the interface.
3. The recreated VLAN interface is on VLAN ID 2, when it should've been on 3.

### Steps to reproduce the problem

Basic configuration of an Ethernet device and a VLAN interface:
```ini
root@cat:/run/systemd/network# cat enp0s31f6.network 
[Match]
Name=enp0s31f6

[Network]
VLAN=myvlan
```
```ini
root@cat:/run/systemd/network# cat myvlan.netdev 
[NetDev]
Name=myvlan
Kind=vlan

[VLAN]
Id=2
```
```ini
root@cat:/run/systemd/network# ip -d l sh myvlan
5: myvlan@enp0s31f6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 30:5a:3a:45:e5:b5 brd ff:ff:ff:ff:ff:ff promiscuity 0 allmulti 0 minmtu 0 maxmtu 65535 
    vlan protocol 802.1Q id 2 <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
```

The interface `myvlan` exists exactly as expected.

Issue 1:

```ini
root@cat:/run/systemd/network# sed -i 's/Id=2/Id=3/' myvlan.netdev
root@cat:/run/systemd/network# networkctl delete myvlan
root@cat:/run/systemd/network# networkctl reload
root@cat:/run/systemd/network# ip -d l sh myvlan
Device "myvlan" does not exist.
```

Issue 2:
```ini
root@cat:/run/systemd/network# touch enp0s31f6.network
root@cat:/run/systemd/network# networkctl reload
root@cat:/run/systemd/network# ip -d l sh myvlan
6: myvlan@enp0s31f6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 30:5a:3a:45:e5:b5 brd ff:ff:ff:ff:ff:ff promiscuity 0 allmulti 0 minmtu 0 maxmtu 65535 
    vlan protocol 802.1Q id 2 <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
```

Observe how, even though `myvlan.netdev` specifies `Id=3` and the interface didn't exist before, it is created with VLAN ID 2.

**Comment by yuwata** [comment]
Hm, indeed. I will take a look.
Workaround is calling `networkctl reconfigure enp0s31f6` after `networkctl reload`.

**Comment by polarina** [comment]
> Hm, indeed. I will take a look. Workaround is calling `networkctl reconfigure enp0s31f6` after `networkctl reload`.

That recreates the interface, but still under the old, incorrect VLAN ID.

**Comment by yuwata** [comment]
Ahhhh, indeed. Bad. Then, you need to restart networkd...

**Comment by yuwata** [comment]
Waiting in #34909, though still WIP.
