### ISSUE TITLE
Provide a simple way to prevent _all_ logging to kmsg

### ISSUE THREAD

**Issue by klausman** [systemd/systemd#34912]
### Component

journalctl

### Is your feature request related to a problem? Please describe

Sortof: I would like the kmsg ring buffer (what `dmesg` displays) to only contain kernel messages (and _maybe_ serious error messages that have nowhere else to go). However, even with this in journald's config:

```
[Journal]
ForwardToKMsg=no
ForwardToConsole=no
MaxLevelKMsg=err
MaxLevelConsole=err
Audit=no
```

I still get non-error messages from systemd-related programs in kmsg:

```
systemd-ssh-generator[54902]: Binding SSH to AF_UNIX socket /run/ssh-unix-local/socket.
systemd-ssh-generator[54902]: → connect via 'ssh .host' locally
systemd-sysv-generator[54904]: SysV service '/etc/init.d/openipmi' lacks a native systemd unit file. ~ Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it safe, robust and future-proof. ! This compatibility logic is deprecated, expect removal soon. !
systemd-ssh-generator[55047]: Binding SSH to AF_UNIX socket /run/ssh-unix-local/socket.
systemd-ssh-generator[55047]: → connect via 'ssh .host' locally
systemd-ssh-generator[55105]: Binding SSH to AF_UNIX socket /run/ssh-unix-local/socket.
systemd-ssh-generator[55105]: → connect via 'ssh .host' locally
```

I do understand that these are not related to journald, so its config would not pertain to these programs (ssh-gen and sysv-gen). Still, these messages are not useful for me to land in kmsg, they may outcrowd things I am looking for there and in the case of the ssh-gen message are utterly useless to me. The sysv-gen message at least tells me something actionable, but it, too, should be in a log file, not in the arguable finite space of the kmsg ring.

### Describe the solution you'd like

Ideally:

Have one option that globally tells systemd (and related programs) to never log to kmsg except under catastrophic circumstances

But I would settle for:

A config location (ontop of the journalctl options I am already using) that tells all auxiliary systemd programs that do their own logging to never log to kmsg.

Alternatively:

Allow me to set these programs to only log actual errors or fatal messages (the ssh generator message is of no value, IMHO).

### Describe alternatives you've considered

None, since there does not seem to be an option to configure the logging behavior of the scripts. The ideal solution above would also simplify the journald part of the config, so a solution already exists, even if it is more complex than I would like.

If there _is_ a way to configure the auxiliary program's logging behavior, it should be documented in their man-pages. I do understand that the generators run very early on, and thus can't just talk to journald or syslog, but the message described above are generated (and sent to kmsg) even after the system has booted (cf. the repeated message about the sshd socket). At a minimum, 

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by poettering** [comment]
Why though? I mean, these tools log to kmsg because there's no other place they can log to (because it's early boot stuff where no logging service is around), or where they risk a deadlock if they'd talk to external services (i.e. generators run synchronously, and if they block on IPC will cause socket activation to hang → deadlock).

And christ, for those 10 lines, seems like a big ask.

Hence, not convinced at all that what you are asking for is desirable, it seems very shortsighted to turn off logging entirely, but of course, it's your right to shoot yourself in your foot.

You can probably set CapabilityBoundingSet=~CAP_SYSLOG`

**Comment by bluca** [comment]
You can silence it quite easily, add a one-line script in `/etc/systemd/system-generators/systemd-ssh-generator` with content:

`SYSTEMD_LOG_LEVEL=warning /usr/lib/systemd/system-generators/systemd-ssh-generator`
