### ISSUE TITLE
Unable to set "Local" or "Remote" to "any" or "::" for ip6tnl netdev

### ISSUE THREAD

**Issue by eest** [systemd/systemd#34930]
### systemd version the issue has been seen with

252.30-1~deb12u2

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-10-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Given
```
cat /etc/systemd/network/10-ip6tunl.netdev
[NetDev]
Name=ip6tnl0
Kind=ip6tnl

[Tunnel]
Independent=true
Local=any
Remote=any
Mode=ip6ip6
```
Followed by:
```
networkctl reload
```

Was expecting to see interface being created like so:
```
# ip -6 tun
ip6tnl0: ipv6/ipv6 remote :: local :: encaplimit 0 hoplimit inherit tclass 0x00 flowlabel 0x00000 (flowinfo 0x00000000)
```

This seemed to almost have been brought up as being the issue in https://github.com/systemd/systemd/issues/22352#issuecomment-1027326143 but seems it was not.

### Unexpected behaviour you saw

Instead this is logged in `journalctl -u systemd-networkd.service`:
```
systemd-networkd[1596033]: ip6tnl0: vti6/ip6tnl/ip6gre tunnel without a local/remote IPv6 address configured in /etc/systemd/network/10-ip6tunl.netdev. Ignoring
```

### Steps to reproduce the problem

See expected behaviour.

**Comment by eest** [comment]
I had a similar setup working for an ipip tunnel:
```
cat 10-ipip.netdev
[NetDev]
Name=tunl0
Kind=ipip

[Tunnel]
Independent=true
Local=any
Remote=any
```

together with this .network file:
```
cat 10-ipip.network
[Match]
Name=tunl0
```

for reference, the empty `.network` file seems to be needed because otherwise the tunl0 interface is left in `DOWN` state, even if configured as independent, not sure why this. Anyway this makes it feel like it should work for ip6tnl as well. Looking at the code I see that "any" leads to setting family to `AF_UNSPEC` via
https://github.com/systemd/systemd/blob/ebc64de22f84f62dc48e5d16ec5d12ca82222b74/src/network/netdev/tunnel.c#L763-L764
https://github.com/systemd/systemd/blob/ebc64de22f84f62dc48e5d16ec5d12ca82222b74/src/network/netdev/tunnel.c#L728-L740

And comparing the code for ipip and ip6tnl it seems the first one accepts AF_UNSPEC:
https://github.com/systemd/systemd/blob/ebc64de22f84f62dc48e5d16ec5d12ca82222b74/src/network/netdev/tunnel.c#L684-L687

... while the latter does not (unless specifically ip6gre):
https://github.com/systemd/systemd/blob/ebc64de22f84f62dc48e5d16ec5d12ca82222b74/src/network/netdev/tunnel.c#L694-L697

**Comment by yuwata** [comment]
Thank you for the report. I will take a look.
