### ISSUE TITLE
Strictly separate localectl set-x11-keymap and set-keymap command, or make --no-convert the default

### ISSUE THREAD

**Issue by neitsab** [systemd/systemd#34967]
### Component

other

### Is your feature request related to a problem? Please describe

I installed Arch Linux on a new machine and used `localectl set-keymap fr-latin9` to enable the use of accented characters in my decryption passphrase in the initramfs. That was before any graphical environment was installed and worked flawlessly.

Later on I installed GNOME and had to run `localectl set-x11-keyboard fr oss` from another TTY so that GDM would accept my login passphrase (which also contains accented characters).

A kernel upgrade came in and my initramfs got renegerated. On the next reboot I was unable to unlock my drive using my passphrase.

During troubleshooting I identified that `localectl set-x11-keyboard fr oss` had changed the content of my `/etc/vconsole.conf` file from

```shell
# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed
# and systemd-vconsole-setup(8). Use localectl(1) to update this file.
KEYMAP=fr-latin9
```

to

```shell
# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed
# and systemd-vconsole-setup(8). Use localectl(1) to update this file.
KEYMAP=fr
XKBLAYOUT=fr
XKBMODEL=oss
```

Effectively removing the ability for me to type accented characters in the virtual console due to the lack of support for them in `fr` keymap layout.

This can be verified on any system by running the following (here on a graphical install):

```shell
sudo localectl set-keymap fr-latin9

cat /etc/vconsole
# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed
# and systemd-vconsole-setup(8). Use localectl(1) to update this file.
KEYMAP=fr-latin9
XKBLAYOUT=fr
XKBMODEL=pc105
XKBVARIANT=latin9
XKBOPTIONS=terminate:ctrl_alt_bksp

sudo localectl set-x11-keymap fr oss             

cat /etc/vconsole.conf              
# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed
# and systemd-vconsole-setup(8). Use localectl(1) to update this file.
KEYMAP=fr
XKBLAYOUT=fr
XKBMODEL=oss
```

`XKBMODEL=pc105` and `XKBOPTIONS=terminate:ctrl_alt_bksp` were added and removed automativally, which also seems pretty inconsistent. The second one is tracked in #25312.

I had started reporting this as a bug as well, but upon reading the man page I realized this was the expected behavior when not using the `--no-convert` option.

I know the manpage documents this behaviour, but it seems incoherent to me to have two separate commands which end up doing the same thing unless an extra `--no-convert` option is added. Besides as illustrated here, the consequences can be pretty dire since the conversion done by default is unreliable.

### Describe the solution you'd like

Using `localectl set{-x11}-keymap`  should **only** change the corresponding options in `/etc/vconsole`, either virtual-console related `KEYMAP` for `set-keymap` OR `XKB{LAYOUT,MODEL,VARIANT,OPTIONS}` for `set-x11-keymap`, and leave out the option(s) set by the other command.

From my understanding this would be equivalent to making `no-convert` the default.

I hope you'll consider making `--no-convert` the default or change the two commands so that they only impact their corresponding settings.

### Describe alternatives you've considered

1. Prayer
2. Not using `localectl set{,-x11}-keymap` and only manually editing `/etc/vconsole.conf` instead.
3. Using `vconsole.keymap=` kernel parameter to override whatever unexpected changes may happen in `/etc/vconsole.conf`

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by yuwata** [comment]
Sorry, that breaks backward compatibility. Please set --no-convert in such case.
