### ISSUE TITLE
Unit with PrivateUsers=yes fails to start when user namespaces are not available

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#34983]
### systemd version the issue has been seen with

systemd-256.7-1.fc42.x86_64

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.12.0-0.rc5.20241029gite42b1a9a2557.45.fc42.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

In our documentation (man systemd.exec) we advice people to not rely solely on user namespaces for security.

> Note that the implementation of this setting might be impossible (for example if user namespaces are not available), and the  unit should be written in a way that does not solely rely on this setting for security.

Above implies that when user namespaces are disabled service which has `PrivateUsers=yes` would still run.

### Unexpected behaviour you saw

This is however not the case and when user namespacing is disabled then services with `PrivateUsers=yes` will fail to start.

### Steps to reproduce the problem

```bash
echo "user.max_user_namespaces=0" > /etc/sysctl.d/99-user-ns.conf
sysctl -p /etc/sysctl.d/99-user-ns.conf
cat > /run/systemd/system/test.service <<EOF
[Service]
ExecStart=/bin/sleep 10
PrivateUsers=yes
EOF
systemctl daemon-reload
systemctl start test.service
systemctl status test.service
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
× test.service
     Loaded: loaded (/run/systemd/system/test.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Fri 2024-11-01 13:47:10 EDT; 15ms ago
   Duration: 17ms
 Invocation: d5da3adf7c194a239959ea142709d971
    Process: 1158 ExecStart=/bin/sleep 10 (code=exited, status=217/USER)
   Main PID: 1158 (code=exited, status=217/USER)
   Mem peak: 1.2M
        CPU: 3ms

Nov 01 13:47:10 vm-10-0-187-212.hosted.upshift.rdu2.redhat.com systemd[1]: Started test.service.
Nov 01 13:47:10 vm-10-0-187-212.hosted.upshift.rdu2.redhat.com (sleep)[1158]: test.service: Failed to set up user namespacing: No space left on device
Nov 01 13:47:10 vm-10-0-187-212.hosted.upshift.rdu2.redhat.com (sleep)[1158]: test.service: Failed at step USER spawning /bin/sleep: No space left on device
Nov 01 13:47:10 vm-10-0-187-212.hosted.upshift.rdu2.redhat.com systemd[1]: test.service: Main process exited, code=exited, status=217/USER
Nov 01 13:47:10 vm-10-0-187-212.hosted.upshift.rdu2.redhat.com systemd[1]: test.service: Failed with result 'exit-code'.
```

**Comment by bluca** [comment]
> Above implies that when user namespaces are disabled service which has PrivateUsers=yes would still run.

I'm not sure - given it's a significant security downgrade, it might be better to hard fail in this case? It can always be disabled for a drop-in, if one is sure about that

**Comment by msekletar** [comment]
@poettering any opinion?

**Comment by msekletar** [comment]
@bluca @YHNdnzj should I post PR adjusting the man page then?

**Comment by bluca** [comment]
yeah more clarity in the manpages is always welcome
