### ISSUE TITLE
systemd-measure: Use TPM-shielded keys for PCR policy signing.

### ISSUE THREAD

**Issue by m00nwtchr** [systemd/systemd#34981]
### Is your feature request related to a problem? Please describe

I'd like to use the keys generated by `sbctl` both for Secure Boot signing and PCR policy signing, but because they're stored using the TPM, systemd-measure fails to parse the private key-file. (`-----BEGIN TSS2 PRIVATE KEY-----`)

### Describe the solution you'd like

Support reading of TSS private keys in systemd-measure.

### Describe alternatives you've considered

The alternative is to use separate keys, which is fine, but slightly inconvenient. (Maybe less secure because `systemd-measure` itself doesn't have TPM key storage, but I don't know if that really matters that much)

### The systemd version you checked that didn't have the feature you are asking for

256.7

**Comment by bluca** [comment]
Have you tried to use the openssl tpm engine/provider?

**Comment by m00nwtchr** [comment]
Not sure wdym, can you give me an example?

**Comment by bluca** [comment]
systemd measure supports openssl engines: https://www.freedesktop.org/software/systemd/man/latest/systemd-measure.html#--private-key=PATH/URI
there is a tpm engine: https://github.com/tpm2-software/tpm2-openssl
so you should be able to pass the sealed key, along with the appropriate parameters after having the engine installed, and it should work

**Comment by m00nwtchr** [comment]
Alright, I'll try installing it, and see if it works.

**Comment by bluca** [comment]
for older openssl there's also an engine: https://github.com/tpm2-software/tpm2-tss-engine

**Comment by m00nwtchr** [comment]
After installing `tpm2-openssl` (from Arch Linux repositories), I'm still getting `Failed to parse private key '/var/lib/sbctl/keys/PK/PK.key'.`

**Comment by DaanDeMeyer** [comment]
@m00

> After installing `tpm2-openssl` (from Arch Linux repositories), I'm still getting `Failed to parse private key '/var/lib/sbctl/keys/PK/PK.key'.`, Is there some kind of configuration in systemd-measure that can be used to set the openssl provider?

See the man page, you need the `--private-key-source` option and pass a proper URI to the `--private-key=` option. The URI is specific to the provider so not something we can help you with.

**Comment by m00nwtchr** [comment]
Ah, I see, thanks

**Comment by poettering** [comment]
This seems to be a support issue at this time, but this is a bug and feature tracker. systemd-devel is really the batter place for such discussions if there's still smething to discuss
