### ISSUE TITLE
Branch changes make it impossible to clone the source code

### ISSUE THREAD

**Issue by Francis-Wang-Q** [systemd/systemd#35027]
### systemd version the issue has been seen with

256

### Used distribution

256.7

### Linux kernel version used

4.19.98

### CPU architectures issue was seen on

arm

### Component

systemd-boot

### Expected behaviour you didn't see

Don't make changes easily. Thanks

### Unexpected behaviour you saw

Branch changes make it impossible to clone the source code.
I think this is not a wise approach, as it causes many released SDKs to be unable to be used normally, increasing maintenance costs.

### Steps to reproduce the problem

null

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
null
```

**Comment by bluca** [comment]
What do you mean by "branch changes?"

**Comment by Francis-Wang-Q** [comment]
The default branch from "master" change to "main". We had release yocto bb to customers, we have to update the patch to customer as below:
SRC_URI += "git://github.com/systemd/systemd.git;protocol=git;branch=main"

**Comment by bluca** [comment]
Yes, this happened long ago. Just don't specify a branch and the default one will be used automatically on clone, this is really not an issue.

**Comment by Francis-Wang-Q** [comment]
Yes, I know, but I do not think it is a good idea. Because the yocto fetch default from master. The define by yocto as below:
"branch": The branch(es) of the Git tree to clone. If unset, this is assumed to be "master". The number of branch parameters much match the number of name parameters.
Anyway, thank you for your reply.

Best Regards,
Francis.wang

**Comment by bluca** [comment]
Sorry but that sounds like a bug in Yocto. Please raise it with the Yocto developers, there's nothing we can do here, the default branch is set correctly on Github so a normal `git clone https://github.com/systemd/systemd.git` works just fine and clones the correct branch.
