### ISSUE TITLE
run0 permissions problem

### ISSUE THREAD

**Issue by greyltc** [systemd/systemd#35022]
### systemd version the issue has been seen with

256.7

### Used distribution

Arch Linux

### Linux kernel version used

6.11.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

I expect `run0` to be able to run a bash script that only root has the permissions required to run, just like sudo can.

### Unexpected behaviour you saw

I see "Permission denied" when trying to run a script with `run0` that only root can run. It doesn't even prompt for a password:
```
user@box:~$ echo -e '#!/usr/bin/env bash\necho hi' > /tmp/say_hi.sh
user@box:~$ chmod 0700 /tmp/say_hi.sh
user@box:~$ /tmp/say_hi.sh
hi
user@box:~$ run0 chown root /tmp/say_hi.sh
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to manage system services or other units.
Authenticating as: user
Password: 
==== AUTHENTICATION COMPLETE ====
user@box:~$ sudo /tmp/say_hi.sh
hi
user@box:~$ run0 /tmp/say_hi.sh
Failed to find executable /tmp/say_hi.sh: Permission denied
```

### Steps to reproduce the problem

see previous section

**Comment by greyltc** [comment]
A minor variation on this issue is when a directory's permissions blocks traversal by the calling user:
```
user@box:~$ mkdir /tmp/dir1
user@box:~$ echo -e '#!/usr/bin/env bash\necho hi' > /tmp/dir1/say_hi.sh
user@box:~$ chmod +x /tmp/dir1/say_hi.sh
user@box:~$ chmod 0700 /tmp/dir1
user@box:~$ /tmp/dir1/say_hi.sh 
hi
user@box:~$ run0 chown root /tmp/dir1
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to manage system services or other units.
Authenticating as: user
Password: 
==== AUTHENTICATION COMPLETE ====
user@box:~$ sudo /tmp/dir1/say_hi.sh
hi
user@box:~$ run0 /tmp/dir1/say_hi.sh
Failed to find executable /tmp/dir1/say_hi.sh: Permission denied
```

**Comment by greyltc** [comment]
Is my understanding correct that the fix here is to change the text that appears when the issue occurs?

**Comment by bluca** [comment]
no it will not fail and delegate the check to the transient unit spawning process

**Comment by greyltc** [comment]
Thank you. Will this handle `--chdir` permissions issues too?
