### ISSUE TITLE
systemd-boot 256.7 fails to boot on machines with no physical memory below 4GiB boundary

### ISSUE THREAD

**Issue by andre4ik3** [systemd/systemd#35026]
### systemd version the issue has been seen with

256.7

### Used distribution

NixOS 24.11 (unstable)

### Linux kernel version used

6.11.2-asahi

### CPU architectures issue was seen on

aarch64

### Component

systemd-boot

### Expected behaviour you didn't see

The system should boot

### Unexpected behaviour you saw

The system doesn't boot, with the following error:

```
systemd-boot: Assertion 'BS->AllocatePages(type, memory_type, n_pages, &addr) == EFI_SUCCESS' failed at ../src/boot/efi/util.h:77@xmalloc_pages, halting.
```

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/e5ed29b8-188c-420f-ab5f-adb1a40dc7a8">

### Steps to reproduce the problem

1. Have a working systemd-boot installation, for example 255.9 or prior versions
2. Update systemd-boot to be version 256.7
3. Reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```
Output of `bootctl` after rewriting BOOTAA64.efi with 255.9 (systemd-bootaa64.efi still 256.7):

System:
      Firmware: UEFI 2.100 (Das U-Boot 8228.1792)
 Firmware Arch: aa64
   Secure Boot: disabled (setup)
  TPM2 Support: no
  Measured UKI: no
  Boot into FW: not supported

Current Boot Loader:
      Product: systemd-boot 255.9
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Enroll SecureBoot keys
               ✓ Retain SHIM protocols
               ✓ Menu can be disabled
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/05f0b715-554d-4882-91f6-16ee7cfee9f4
         File: └─//EFI/BOOT/BOOTAA64.EFI

Random Seed:
 System Token: not set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/05f0b715-554d-4882-91f6-16ee7cfee9f4)
         File: ├─/EFI/systemd/systemd-bootaa64.efi (systemd-boot 256.7)
               └─/EFI/BOOT/BOOTAA64.EFI (systemd-boot 255.9)

No boot loaders listed in EFI Variables.

Boot Loader Entries:
        $BOOT: /efi (/dev/disk/by-partuuid/05f0b715-554d-4882-91f6-16ee7cfee9f4)
        token: nixos

Default Boot Loader Entry:
         type: Boot Loader Specification Type #1 (.conf)
        title: NixOS (Generation 142 NixOS Vicuna 24.11.20241104.fabad7a (Linux 6.11.2-asahi), built on 2024-11-05)
           id: nixos-generation-142.conf
       source: /efi//loader/entries/nixos-generation-142.conf
     sort-key: nixos
      version: Generation 142 NixOS Vicuna 24.11.20241104.fabad7a (Linux 6.11.2-asahi), built on 2024-11-05
   machine-id: 2b6bce95b72c4da795466c43c4968a8e
        linux: /efi//EFI/nixos/pcizc9skw890fbgmkqbqhmwrvlcq1wy0-linux-6.11.2-asahi-Image.efi
       initrd: /efi//EFI/nixos/vj368yqjrif9pbmf3506fcslgmbw2l7l-initrd-linux-6.11.2-asahi-initrd.efi
      options: init=/nix/store/gd48fq33xdzg9j265r4rfrcfxql2an4x-nixos-system-pluto-24.11.20241104.fabad7a/init boot.shell_on_fail nvme_apple.flush_interval=0 quiet loglevel=4 sys>
```

**Comment by bluca** [comment]
Did it use to work? If so could you please bisect it? None of us has this hardware so it's unlikely to be solved otherwise

**Comment by andre4ik3** [comment]
Yes, version 255.9 (the current version in NixOS 24.05 stable) and prior used to work. I will bisect for the exact commit that caused it, but it might take a while, since I have to install + reboot every time.

**Comment by DaanDeMeyer** [comment]
@andre4ik3 My educated guess is that this is caused by https://github.com/systemd/systemd/pull/34428. Can you try reverting that one first? That hopefully cuts down the bisecting effort if I guessed right.

**Comment by andre4ik3** [comment]
Yep, can confirm:

```
d64193a2a652b15db9cb9ed10c6b77a17ca46cd2 is the first bad commit
commit d64193a2a652b15db9cb9ed10c6b77a17ca46cd2 (HEAD)
Author: Daan De Meyer <daan.j.demeyer@gmail.com>
Date:   Fri Sep 13 21:37:20 2024 +0200

    boot: Make initrd_prepare() semantically equivalent to combine_initrds()
    
    Currently, trying to boot images with type 1 entries generated by mkosi
    with qemu freezes in the kernel EFI stub. I'm not going to pretend I
    understand what's going on, but when I reported a similar problem with
    UKIs, the fix was to rework the code in combine_initrds() in the stub
    to behave like it does today. It seems that same fix was never applied
    to systemd-boot's combine_initrds() function, so let's do that now to
    fix the freezes I've been seeing trying to boot images with type 1 entries
    in qemu.
    
    (cherry picked from commit f8fa4222c9ac3e74e91c64e25e9532c99559cf99)

 src/boot/efi/boot.c | 60 ++++++++++++++++++++++++++++++++++++++++++++----------------
 1 file changed, 44 insertions(+), 16 deletions(-)
```

<details>
<summary>Full bisect log</summary>
<pre>
git bisect start
# status: waiting for both good and bad commits
# bad: [7635d01869ba325b9cf450923c8f13912b7ca536] meson: bump version to 256.7
git bisect bad 7635d01869ba325b9cf450923c8f13912b7ca536
# status: waiting for good commit(s), bad commit known
# good: [34ba18b0124407403690738b46fbd6236fe65c92] logs-show: do not use _SOURCE_MONOTONIC_TIMESTAMP field
git bisect good 34ba18b0124407403690738b46fbd6236fe65c92
# good: [766af3f782299a7cbfba24a4333444ac008c17d2] Document that MemorySwapMax supports % configuration
git bisect good 766af3f782299a7cbfba24a4333444ac008c17d2
# good: [8d7eef9ee5ead7c7b47b2ad4418529ac5cf17bb3] bootctl: don't load etc/machine-info from cwd
git bisect good 8d7eef9ee5ead7c7b47b2ad4418529ac5cf17bb3
# bad: [08cf1c5ce525bcf52548a8b3713b71cda7545c20] repart: Add a log message when we're about to fsync().
git bisect bad 08cf1c5ce525bcf52548a8b3713b71cda7545c20
# good: [0d0c5bff92bfcce40a2e67dfffefa52833c2874b] mkosi: fix typo
git bisect good 0d0c5bff92bfcce40a2e67dfffefa52833c2874b
# bad: [f457acb66376b9e65c1d74458011718718c802ad] mkosi: Stop applying device groups patch on Arch
git bisect bad f457acb66376b9e65c1d74458011718718c802ad
# good: [f64ee10e4ef03ef11ff72431f15db9e98ea38550] mkosi: Add back accidentally removed .gdbinit file
git bisect good f64ee10e4ef03ef11ff72431f15db9e98ea38550
# good: [2552348da2c961ac9732614eb129228bba4d51da] portable: ensure PORTABLE_FORCE_ATTACH works even when there is a leftover unit
git bisect good 2552348da2c961ac9732614eb129228bba4d51da
# bad: [c1fd422f2c82545bd7e8240e9b906f88911c224a] mkosi: supress error messages from git
git bisect bad c1fd422f2c82545bd7e8240e9b906f88911c224a
# bad: [d64193a2a652b15db9cb9ed10c6b77a17ca46cd2] boot: Make initrd_prepare() semantically equivalent to combine_initrds()
git bisect bad d64193a2a652b15db9cb9ed10c6b77a17ca46cd2
# first bad commit: [d64193a2a652b15db9cb9ed10c6b77a17ca46cd2] boot: Make initrd_prepare() semantically equivalent to combine_initrds()
</pre>
</details>

**Comment by andre4ik3** [comment]
More specifically it's [this line of code](https://github.com/systemd/systemd/blob/d64193a2a652b15db9cb9ed10c6b77a17ca46cd2/src/boot/efi/boot.c#L2299) causing the error. I think it's due to an error in [EFI_SIZE_TO_PAGES](https://github.com/systemd/systemd/blob/d64193a2a652b15db9cb9ed10c6b77a17ca46cd2/src/boot/efi/efi.h#L183) -- it's assuming page size to always be 4 KiB? Asahi kernels have a page size of 16 KiB.

**Comment by bluca** [comment]
Is there any way to detect that at runtime?

**Comment by andre4ik3** [comment]
I don't know much stuff about EFI. Maybe.

But actually, maybe that's not the problem here -- I just changed it to be 16 KiB and the respective EFI_SIZE_TO_PAGES calculation instead of 4 KiB, rebuilt and tested, and it still halts with the same error. I'm rebuilding now again with more changes -- will update when I have found the real culprit.

**Comment by andre4ik3** [comment]
Would you accept a [revert patch](https://gist.github.com/andre4ik3/41c71a56e6d5657f7e2b4110d6f83430) of the problematic commit? I tested it on both the aarch64 laptop and an x86_64 desktop tower, both systems boot fine with this patch applied.

**Comment by poettering** [comment]
i'd prefer if we take a minute or two tryint to understand what's going on before rverting...

**Comment by andre4ik3** [comment]
Agreed, was just posting for completeness as I'm using it as a temporary solution for my machines.

**Comment by arvidjaar** [comment]
> Is there any way to detect that at runtime?

UEFI spec defines boot time `AllocatePages` as "The number of contiguous 4 KiB pages to allocate" and description of OS - firmware interface only has 4KiB alignment requirement for all platforms mentioned in the specification.

**Comment by jannau** [comment]
> Maybe it's the [hardcoded physical address of `UINT32_MAX`](https://github.com/systemd/systemd/blob/d64193a2a652b15db9cb9ed10c6b77a17ca46cd2/src/boot/efi/boot.c#L2303)? [`xmalloc_pages` takes some "`EFI_PHYSICAL_ADDRESS`"](https://github.com/systemd/systemd/blob/d64193a2a652b15db9cb9ed10c6b77a17ca46cd2/src/boot/efi/util.h#L76), but I'm not sure what to change it to. Like I said, I don't know much about EFI (or bootloaders in general).

Do I understand this correctly that it expects physical memory to be present below 4GB physical address?

If so this is plain broken on Apple silicon systems. Physical memory is mapped to start at `0x10_0000_0000` or  `0x100_0000_0000`.

**Comment by marcan** [comment]
`0x8_0000_0000` but yes. That assumption is just completely wrong, machines with no physical memory below the 4GiB boundary exist.

**Comment by mzyngier** [comment]
> 0x8_0000_0000 but yes. That assumption is just completely wrong, machines with no physical memory below the 4GiB boundary exist.

Indeed.
That's not even an Apple special, nor a new thing. My 2014 vintage AMD Seattle (aka Opteron A1100) has all its memory at 40bit.

**Comment by waltmck** [comment]
> > 0x8_0000_0000 but yes. That assumption is just completely wrong, machines with no physical memory below the 4GiB boundary exist.
> 
> Indeed. That's not even an Apple special, nor a new thing. My 2014 vintage AMD Seattle (aka Opteron A1100) has all its memory at 40bit.

Can you replicate this issue on that device?

**Comment by mzyngier** [comment]
> Can you replicate this issue on that device?

```
../src/boot/log.c:30@efi_assert: systemd-boot: Assertion 'BS->AllocatePages(type
, memory_type, n_pages, &addr) == EFI_SUCCESS' failed at ../src/boot/util.h:95@x
malloc_pages, halting.
```
This is systemd build from:

`5da7e9b208 Fix man page links broken due to incorrect volume numbers (#35122)`

**Comment by mzyngier** [comment]
And to be clear: this machine boots with EDK2 and not U-Boot and uses 4kB pages for its EFI implementation.

This crash is clearly caused by the bogus assumption that a page must be allocated within the low 4GB range, which is an x86-ism that doesn't hold on arm64.

I can easily restore some level of sanity (and a booting system) with this:

```
diff --git a/src/boot/boot.c b/src/boot/boot.c
index 87b0232860..c12f24b3a6 100644
--- a/src/boot/boot.c
+++ b/src/boot/boot.c
@@ -2473,7 +2473,7 @@ static EFI_STATUS initrd_prepare(
                 AllocateMaxAddress,
                 EfiLoaderData,
                 EFI_SIZE_TO_PAGES(size),
-                UINT32_MAX /* Below 4G boundary. */);
+                1ULL << 48);
         uint8_t *p = PHYSICAL_ADDRESS_TO_POINTER(pages.addr);
 
         STRV_FOREACH(i, entry->initrd) {
```

**Comment by andre4ik3** [comment]
@mzyngier Can you test this patch? I was just reading [EFI documentation](https://uefi.org/specs/UEFI/2.9_A/07_Services_Boot_Services.html#memory-allocation-functions) and changed out the `AllocateMaxAddress` to `AllocateAnyPages`. It works on my M1 aarch64 laptop and my desktop amd64 tower, but I'm still not sure if it will work on all systems -- there must have been a reason why it was allocating specifically below 4 GiB boundary, right? I'll test it in QEMU in a bit -- if all this works I'll make a PR and hopefully this fixes it.

> Allocation requests of Type AllocateAnyPages allocate any available range of pages that satisfies the request. On input, the address pointed to by Memory is ignored.
>
> Allocation requests of Type AllocateMaxAddress allocate any available range of pages whose uppermost address is less than or equal to the address pointed to by Memory on input.

```diff
diff --git a/src/boot/efi/boot.c b/src/boot/efi/boot.c
index ecbb4e0509..62fe454736 100644
--- a/src/boot/efi/boot.c
+++ b/src/boot/efi/boot.c
@@ -2297,10 +2297,10 @@ static EFI_STATUS initrd_prepare(
         }
 
         _cleanup_pages_ Pages pages = xmalloc_pages(
-                AllocateMaxAddress,
+                AllocateAnyPages,
                 EfiLoaderData,
                 EFI_SIZE_TO_PAGES(size),
-                UINT32_MAX /* Below 4G boundary. */);
+                0 /* Ignored. */);
         uint8_t *p = PHYSICAL_ADDRESS_TO_POINTER(pages.addr);
 
         STRV_FOREACH(i, entry->initrd) {

```

(Please make sure to have a backup of the working bootloader and a UEFI shell on a USB stick so you can replace back the working one quickly if it doesn't boot)

**Comment by mzyngier** [comment]
Yes, this works OK here.

The only reason you'd want to allocate below a specified limit I can think of is if you were doing DMA to that region *and* didn't have an IOMMU to perform the translation (or writing broken code that would ignore the need for translation).

**Comment by DaanDeMeyer** [comment]
I don't remember the reason why this was added but I would presume it has something to do with 32-bit since its specifically about allocating below 4G.

**Comment by bluca** [comment]
The "below 4G boundary" originates in the stub, precisely in this commit https://github.com/systemd/systemd/commit/845707aae23 from this PR https://github.com/systemd/systemd/pull/20789 and I can't see any explanation in the PR or any comment explaining the requirement. @poettering do you remember why you added that by any chance? And is it something we should do in sd-boot too, or is it safe to drop there?

**Comment by andre4ik3** [comment]
> I don't remember the reason why this was added but I would presume it has something to do with 32-bit since its specifically about allocating below 4G.

Hm, maybe I'm missing something but surely in that case UEFI would only allocate below the 4 GiB? So it would work the same as `AllocateAnyPages`? In any case, unfortunately I don't have any 32-bit only hardware. But, I will make sure to test my patch in 32-bit QEMU too.

> And is it something we should do in sd-boot too, or is it safe to drop there?

Yes, this is also something I am worried about -- there are other `xmalloc_pages` calls that rely on being below 4GiB boundary. Looks like like they were in a different codepath that isn't triggered on my system, but here are all the references I could find that could be potentially problematic? (I don't think the `linux_x86.c` ones are particularly concerning if x86 always has memory below 4GiB, but the `stub.c` one definitely looks like it could be problematic):

- [src/boot/stub.c line 121](https://github.com/systemd/systemd/blob/b4dc8b6415c01b814ce30d77a3430e59e1e765e5/src/boot/stub.c#L121)
- [src/boot/linux_x86.c line 168](https://github.com/systemd/systemd/blob/b4dc8b6415c01b814ce30d77a3430e59e1e765e5/src/boot/linux_x86.c#L168)
- [src/boot/linux_x86.c line 180](https://github.com/systemd/systemd/blob/b4dc8b6415c01b814ce30d77a3430e59e1e765e5/src/boot/linux_x86.c#L180)
- [src/boot/linux_x86.c line 192](https://github.com/systemd/systemd/blob/b4dc8b6415c01b814ce30d77a3430e59e1e765e5/src/boot/linux_x86.c#L192)

**Comment by bluca** [comment]
> but the `stub.c` one definitely looks like it could be problematic

Yes that's the same one I linked above

**Comment by poettering** [comment]
The below 4g stuff is required exclusively for support of the old x86 boot prototocol, which wasnt 4g safe initially. Thing is we dont do the old protocol anymore on any recent kernels though, always go through the kernels own efi entrypoint these days, where it is available. And it might even be that all kernels newer than our supported baseline now have the efi entrypoint and we can kill the old proto for good and rid us of this problem.

If we need to keep the old boot proto we can probably condition the 4g thing to x86 and otherwise not bother.

**Comment by bluca** [comment]
Ok, so as the first thing we should set 4G only for x86, as that will fix the immediate regression, as we know it's not an issue on x86, and we can safely backport it. Then we can ponder about the legacy protocol separately. Sounds good?

**Comment by maxweisspoker** [comment]
I am still hitting this on x86_64 machines with both 257.1 and 257.2  :-(

**Comment by bluca** [comment]
Are you 100% sure systemd-boot is up to date in the ESP? Check `bootctl status`

**Comment by ElvishJerricco** [comment]
We just had a NixOS user report this with 257.2: https://discourse.nixos.org/t/systemd-boot-failing-to-boot-a-nixos-warbler-system-due-to-an-efi-assertion-failure/61450

**Comment by maxweisspoker** [comment]
I am also still encountering this. I am not using systemd-boot, I am using systemd-ukify to create a uki efi image. Currently, to generate it, I have to run a docker container with systemd (and associated packages) at version 256.9. Anything higher than that still causes this error.

**Comment by ElvishJerricco** [comment]
The NixOS user's issue got a little more interesting. It works with 256.6, but it breaks with 256.7 (just like the original issue), except it only breaks for nixos-unstable, not nixos 24.11. So something changed in our kernels or initrds that trigger this bug that was introduced to systemd-boot in 256.7.

**Comment by andre4ik3** [comment]
Hm, the issue you linked seems to be on x86_64. The xmalloc_pages behaviour should be [unchanged from the previous releases on x86_64 and i386 though](https://github.com/systemd/systemd/blob/main/src/boot/util.h#L113-L118). So it will still be trying to allocate memory below 4GB on x86_64.

Maybe there is an issue where in the UKI it wasn't trying to allocate below 4GB but is now? And/or there somehow isn't enough memory to allocate below 4GB? I will work on a patch later today to temporarily remove the below 4GB thing completely just as a test, to see if it could be that. But I don't know of any such x86_64 system failing like this, so I'll need to get in contact with the original person having the issue.

Maybe in the later Nixpkgs versions the size of the kernel or initrd increased, not necessarily above 4GB, but enough so that it can't fit below 4GB e.g. because there isn't enough memory there or it isn't contiguous? Just a thought...

**Comment by poettering** [comment]
please try #36715, i think it should address your issues even on x86-64
