### ISSUE TITLE
Failed to acquire RNG data: not ready

### ISSUE THREAD

**Issue by Edd7711** [systemd/systemd#35033]
### systemd version the issue has been seen with

256.7-1

### Used distribution

Arch Linux

### Linux kernel version used

6.11.6-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

No error message after choosing the kernel

### Unexpected behaviour you saw

Error message saying: `Failed to acquire RNG data: not ready`

### Steps to reproduce the problem

1. Power on
2. Choose a kernel to boot
3. The error message shows up: `Failed to acquire RNG data: not ready`
4. Everything then loads and works fine

**Comment by Edd7711** [comment]
Just updated to v257, I'm still seeing the error message

**Comment by poettering** [comment]
Are you sure you updated the boot loader and rebooted with the updated version?

**Comment by Edd7711** [comment]
> Are you sure you updated the boot loader and rebooted with the updated version?

I did `bootctl update`, now the error isn't showing anymore. Thank you!
