### ISSUE TITLE
test_path_is_network_fs_harder fails in build environments

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#35075]
```
/* test_path_is_network_fs_harder */
src/test/test-mount-util.c:541: Assertion failed: expected "path_is_network_fs_harder("/dev")" to succeed but got the following error: Invalid argument
```

the test makes assumption about the running environment, but they are out of its control. There are no guarantees about any of the external directories or mount points or anything else in a build environment. This needs to be dropped or changed to work everywhere, under any condition.

https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=amd64&ver=257%7Erc1-2&stamp=1730977643&raw=0

Regression introduced by https://github.com/systemd/systemd/commit/d49d95df0a260aaca9a3fdd1e6ce535592a53bca

**Comment by yuwata** [comment]
Sorry, will fix soon.
