### ISSUE TITLE
BindsTo does not work for network devices

### ISSUE THREAD

**Issue by M1cha** [systemd/systemd#35079]
### systemd version the issue has been seen with

systemd-255.13-1.fc40.x86_64

### Used distribution

Fedora 40

### Linux kernel version used

6.11.3-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

`test.service` is started after the device becomes available.

### Unexpected behaviour you saw

`test.service` doesn't start.

```
# systemctl status sys-subsystem-net-devices-br99.device
● sys-subsystem-net-devices-br99.device - /sys/subsystem/net/devices/br99
     Loaded: loaded
     Active: active (plugged) since Thu 2024-11-07 15:54:37 UTC; 36s ago
     Device: /sys/devices/virtual/net/br99
```

```
# systemctl status test.service
○ test.service
     Loaded: loaded (/etc/systemd/system/test.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

`systemctl show sys-subsystem-net-devices-br99.device` also doesn't show any binding.

### Steps to reproduce the problem

- Create test.service:
```
[Unit]
BindsTo=sys-subsystem-net-devices-br99.device
After=sys-subsystem-net-devices-br99.device
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=echo started
ExecStop=echo stopped
```

- `systemctl daemon-reload`
- `ip link add name br99 type bridge`

**Comment by poettering** [comment]
Hmm? BindsTo= stops a unit if another unit goes down, but does not cause the first unit to be started if the second one shows up. This is clearly documented.

add a .device.d drop-in for your device unit and add Wants= from the .device unit to the service in question to get it started automatically. or use SYSTEMD_WANTS udev property.

Either way, this is not a bug, but more a support question, and we don't trakc support questions here. please contact systemd-devel ML instead if you have further questions
