### ISSUE TITLE
systemd-pcrlock make-policy fails with "Failed to add OR policy to TPM: tpm:parameter(1):value is out of range or is not correct for the context"

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#35097]
### systemd version the issue has been seen with

256.6

### Used distribution

NixOS unstable

### Linux kernel version used

6.6.57

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

It should create the NVIndex policy

### Unexpected behaviour you saw

it fails with 

```
WARNING:esys:src/tss2-esys/api/Esys_PolicyOR.c:286:Esys_PolicyOR_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_PolicyOR.c:100:Esys_PolicyOR() Esys Finish ErrorCode (0x000001c4) 
Failed to add OR policy to TPM: tpm:parameter(1):value is out of range or is not correct for the context
Failed to submit super PCR policy: State not recoverable

```

### Steps to reproduce the problem

Get a Framework 13, first generation,  with a Nuvoton TPM

```
systemd-pcrlock make-policy
```

### Additional program output to the terminal or log subsystem illustrating the issue

(Note: the missing event log matches are due to me using  lanzaboote instead of UKIs and it's not fully compatbile yet; but I think that's safe to ignore and irrelevant)

```sh
sudo /run/current-system/systemd/lib/systemd/systemd-pcrlock make-policy
[sudo] password for arian: 
Didn't find component '830-root-file-system' in event log, assuming system hasn't reached it yet.
Skipped 2 components after location '940-' (950-shutdown, 990-final).
Event log record 28 (PCR 4, "File: \EFI\BOOT\BOOTX64.EFI") not matching any component.
Event log record 29 (PCR 5, "systemd-boot: loader.conf") not matching any component.
Event log record 35 (PCR 9, "Linux: kernel command line") not matching any component.
Event log record 31 (PCR 11, "String: .osrel") not matching any component.
PCR 0 (platform-code) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 1 (platform-config) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 2 (external-code) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 3 (external-config) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 4 (boot-loader-code) event log contains unrecognized measurements. Removing from set of PCRs.
PCR 5 (boot-loader-config) event log contains unrecognized measurements. Removing from set of PCRs.
PCR 7 (secure-boot-policy) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 11 (kernel-boot) event log contains unrecognized measurements. Removing from set of PCRs.
PCR 12 (kernel-config) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 13 (sysexts) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 14 (shim-policy) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCR 15 (system-identity) matches event log and fully consists of recognized measurements. Including in set of PCRs.
PCRs dropped from protection mask: 4 (boot-loader-code), 5 (boot-loader-config), 11 (kernel-boot)
PCRs in protection mask: 0 (platform-code), 1 (platform-config), 2 (external-code), 3 (external-config), 7 (secure-boot-policy), 12 (kernel-config), 13 (sysexts), 14 (shim-policy), 15 (system-identity)
Predicted future PCRs in 236us.
WARNING:esys:src/tss2-esys/api/Esys_PolicyOR.c:286:Esys_PolicyOR_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_PolicyOR.c:100:Esys_PolicyOR() Esys Finish ErrorCode (0x000001c4) 
Failed to add OR policy to TPM: tpm:parameter(1):value is out of range or is not correct for the context
Failed to submit super PCR policy: State not recoverable
```

**Comment by arianvp** [comment]
A reboot fixed the problem. No idea what is going on. But it's kinda scary.

Nuvoton TPMs are one of the most-used ones on motherboards

**Comment by arianvp** [comment]
I think I found the reproducer:  It only happens when the laptop boots up after shutting down due to empty battery.

**Comment by poettering** [comment]
It probably results in a different set of measurements by the firmware. Maybe diff "systemd-pcrlock cel" of a run where this failure happens from one where everything works.

**Comment by arianvp** [comment]
Will do. It would be really cool feature is `systemd-pcrlock` could show you the diff on error though.  Shouldn't be too hard to implement given we know the "Good" version of the CEL

**Comment by arianvp** [comment]
```diff
diff --git a/bad-early.json b/good-early.json
index a703bff..9c24677 100644
--- a/bad-early.json
+++ b/good-early.json
@@ -282,25 +282,25 @@
     "event_type": "EV_POST_CODE",
     "event_data": "414350492044415441"
   }
 }
 {
   "pcr": 1,
   "recnum": 16,
   "digests": [
     {
       "hashAlg": "sha256",
-      "digest": "11faa2dd9a61c22655d46f647ee5438650c6f2e92ba2afb461905a44b1d5607d"
+      "digest": "94c3666a985b67d02d2f1afe2e363eff5bbe52324748076f0c34719ef68ecffb"
     },
     {
       "hashAlg": "sha1",
-      "digest": "8ec60b843080139eaa00b0b9aac9fb7d18ec600f"
+      "digest": "2384c9ba389185de755819f70af6605d8e23a6c0"
     }
   ],
   "content_type": "pcclient_std",
   "content": {
     "event_type": "EV_EFI_HANDOFF_TABLES",
     "event_data": "01000000000000004415fdf294972c4a992ee5bbcf20e39400109e4300000000"
   }
 }
 {
   "pcr": 1,
```

**Comment by arianvp** [comment]
I think we can close this issue as there is not much for systemd to do. However an RFC to display a diff on `pcrlock` errors might be a valuable addition

**Comment by arianvp** [comment]
Attaching the early event logs for completeness (` jq '.[] | select(.content_type != "systemd")' `)

[good-early.json](https://github.com/user-attachments/files/17746975/good-early.json)
[bad-early.json](https://github.com/user-attachments/files/17746976/bad-early.json)

**Comment by poettering** [comment]
EV_EFI_HANDOFF_TABLES protects various EFI tables passed to the boot loader. Things such as SMBIOS and so on. There are some fields in SMBIOS (such as power-on reason) that might rightfully change at every boot. Hence i guess locking down PCR 1 generaically doesn't make too much sense.

I guess you did "systemd-pcrlock lock-firmware-config", right? That causes the measurements currently seen on PCR 1 to be considered "golden", which then would cause this issue later on.

I guess we should document explicitly that on generic hw "lock-firmware-config" might cause issues like this.

So, i guess in a way this is your own fault, but because the docs didn#t make this clear.

**Comment by arianvp** [comment]
Yeh I manually locked the firmware config.  


> EV_EFI_HANDOFF_TABLES protects various EFI tables passed to the boot loader. Things such as SMBIOS and so on. There are some fields in SMBIOS (such as power-on reason) that might rightfully change at every boot. Hence i guess locking down PCR 1 generaically doesn't make too much sense.

Just for my understanding:
If you look at these two CELs, isn't it weird that the digest is different but the **event content** is the same?   The difference is in the first event for PCR1.  I thought the digest was derived from the event content.   How can it be that the only difference in these CELs are a single event with the same content but different digests?

This makes me feel like there is something buggy is going on in the TPM
