### ISSUE TITLE
Assertion 'link->state == LINK_STATE_CONFIGURING' failed

### ISSUE THREAD

**Issue by serfreeman1337** [systemd/systemd#35092]
### systemd version the issue has been seen with

257~rc1-3

### Used distribution

Debian unstable

### Linux kernel version used

6.10.2

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Unexpected behaviour you saw

systemd-networkd crashes on `networkctl reload` after changing a pppoe config.

### Steps to reproduce the problem

1. Use systemd-networkd for IPv6-PD on a PPPoE link.
/etc/systemd/network/99-ppp0.network:
    ```
    [Match]
    Name=ppp0
    Type=ppp
    
    [Link]
    ActivationPolicy=manual
    
    [Network]
    KeepConfiguration=yes
    DHCP=ipv6
    IPv6AcceptRA=yes
    
    [DHCPv6]
    WithoutRA=solicit
    UseAddress=no
    UseDNS=no
    UseNTP=no
    UseHostname=no
    UseCaptivePortal=no
    ```
3. Comment out the `WithoutRA` line.
4. `networkctl reload`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-networkd[563]: ppp0: Found matching .network file, based on potentially unpredictable interface name: /etc/systemd/network/99-ppp0.network
systemd-networkd[563]: ppp0: Reconfiguring with /etc/systemd/network/99-ppp0.network.
systemd-networkd[563]: Assertion 'link->state == LINK_STATE_CONFIGURING' failed at src/network/networkd-link.c:1093, function link_drop_unmanaged_config(). Aborting.
systemd[1]: systemd-networkd.service: Main process exited, code=killed, status=6/ABRT
systemd[1]: systemd-networkd.service: Failed with result 'signal'
```

**Comment by yuwata** [comment]
Thank you for the report. Fix is waiting in #35059.
