### ISSUE TITLE
loginctl doesn't lock text TTYs

### ISSUE THREAD

**Issue by peedy2495** [systemd/systemd#35093]
### systemd version the issue has been seen with

249.11

### Used distribution

Ubuntu 22.04

### Linux kernel version used

6.5.0-35-generic #35~22.04.1-Ubuntu

### CPU architectures issue was seen on

x86_64

### Component

loginctl

### Expected behaviour you didn't see

`sudo loginctl lock-session <ID>` have to lock the given session id

### Unexpected behaviour you saw

`sudo loginctl lock-session <ID>` doesn't work on text terminals
Neither for the current displayed session, nor from another TTY.
The return code is always success (0).

### Steps to reproduce the problem

`sudo loginctl lock-session <ID>`, where ID represents an active local text TTY.

**Comment by poettering** [comment]
Fixed a while ago:

b4f01bc1df625842c2db423b460a755c5817c1f9

Generally, this bug tracker is for issues in current upstream versions, i.v. v256 and v255 at this time. 249 is *waaaaay* too old.
