### ISSUE TITLE
Allow `[Install]` for init scripts

### ISSUE THREAD

**Issue by Anuskuss** [systemd/systemd#35090]
### Component

systemd-sysv-generator

### Is your feature request related to a problem? Please describe

Currently the services generated by `systemd-sysv-generator` ignore the `[Install]` field (e.g. `override.conf`) so all they can really do is start when the system starts (without fine-grained control).

### Describe the solution you'd like

I want to set `WantedBy` so `sub.service` gets started (in case it was inactive for whatever reason) when `main.service` starts:

```ini
[Unit]
Description=main

[Service]
ExecStart=/bin/true
RemainAfterExit=true
```

```ini
[Unit]
Description=sub
BindsTo=main.service
After=main.service

[Service]
ExecStart=/bin/sleep inf

[Install]
WantedBy=main.service
```

### Describe alternatives you've considered

My current workaround is:

```ini
[Unit]
Description=main
Wants=sub.service

[Service]
ExecStart=/bin/true
RemainAfterExit=true
```

```ini
[Unit]
Description=sub
BindsTo=main.service
After=main.service

[Service]
ExecStart=/bin/sleep inf
```

The result would be the same but the logic is suboptimal: I don't want to fill `main.service` with `sub` services that depend on it (and should be started when it is started). I'd rather have the dependencies in the actual `sub.service` itself, through `BindsTo` (start/stop with `main`) and `WantedBy` (start when `main` starts). If that's too much work for too little benefit (it's all just semantics tbf) feel free to reject.

**Comment by poettering** [comment]
> Currently the services generated by `systemd-sysv-generator` ignore the `[Install]` field (e.g. `override.conf`) so all they can really do is start when the system starts (without fine-grained control).

Hmm? i don't get this? sysv init scripts are scripts, they have no [Install] field? 

Also, it's 2026 and sysv script support is going away in v258, we are not going to add new features to it. Seriously, it's time to get rid of your sysv scripts.

**Comment by Anuskuss** [comment]
> they have no [Install] field?

Yeah but I can add it through the likes of `systemctl edit`. It's just that it's currently ignored.

> it's time to get rid of your sysv scripts

It's a Debian package so maybe the depreciation/removal of `systemd-sysv-generator` will force them to convert it to a systemd service (which is pretty easy to do to be honest).

> sysv script support is going away in v258

If that's set in stone then yeah maybe it wouldn't make sense to add this. v258 is supposed to be released mid next year right? Debian 13 will likely not pick it up then so support (for me) would probably end by 2027. So this feature would be useful for ~3 years.

I think I've found a better workaround though - I'll just add the symlink myself:
```
ln -s /run/systemd/generator.late/sub.service /etc/systemd/system/main.service.wants/sub.service
```

**Comment by poettering** [comment]
> > 
> 
> Yeah but I can add it through the likes of `systemctl edit`. It's just that it's currently ignored.

[Install] is always ignored in drop-ins. Did you edit the main unit file like that? if so, systemctl edit should have refused really: generated unit files are automatically deleted when you hit systemctl daemon-reload, and regenerated.


> It's a Debian package so maybe the depreciation/removal of `systemd-sysv-generator` will force them to convert it to a systemd service (which is pretty easy to do to be honest).

Uh, they really should clean that up.

Sorry, but [install] in sysv makes no sense at all. sysv is a compat feature, we will not extend it, we support it to the point it roughly works as it did before systemd, but not more. Just write proper unit files...

**Comment by Anuskuss** [comment]
> [Install] is always ignored in drop-ins.

That's not true. You just can't *override* `WantedBy` but you can definitely *add* more.

> Sorry, but [install] in sysv makes no sense at all.

The init system is pretty limited and I like systemd more but that doesn't mean I shouldn't be able to add some systemd-isms to it. I mean I gave you an example that makes sense, i.e. start the `sub.service` when the `main.service` starts (which is only needed because `BindsTo` doesn't do that by itself).

> sysv is a compat feature, we will not extend it

What does `enable` do anyway? It will only create the symlink without additional bookkeeping, right? So I guess my workaround (which does work by the way) is enough then. Guess I'll close this?

**Comment by arvidjaar** [comment]
> start the `sub.service` when the `main.service` starts (which is only needed because `BindsTo` doesn't do that by itself).

Are you sure? `BindsTo` is documented as being superset of `Requires` and `Requires` will request start of the dependent unit. And I can confirm this behavior. Having `A` with `BindsTo=B` will start `B` when `A` is started.

**Comment by Anuskuss** [comment]
> Having `A` with `BindsTo=B` will start `B` when `A` is started.

Yeah but I want it the opposite: `BindsTo=main.service` in `sub.service` will not start `sub.service` when `main.service` starts but `Wants=sub.service`/`Requires=sub.service` in `main.service` will. The "problem" is that `main.service` does not have a dependency on `sub.service` (logically speaking) but rather the other way around. I wished that `BindsTo` would automatically start the defining unit but since that's not a thing I'd rather have the dependency in the right location (in the `sub.service` via `WantedBy`) even if it's fundamentally the same at the end of the day.
It becomes quite error prone otherwise: I'll always have to edit `main.service` (add a `Wants` entry) everytime I want to add a new `sub` service and I run into the risk of forgetting to remove that entry once I get rid of that `sub`. Having the dependencies strictly in the `sub` prevents that.
