### ISSUE TITLE
networkctl reconfigure drops IPv4 route on a pppoe link with IPv6-PD

### ISSUE THREAD

**Issue by serfreeman1337** [systemd/systemd#35094]
### systemd version the issue has been seen with

257~rc1-4

### Used distribution

Debian unstable

### Linux kernel version used

6.10.2

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Unexpected behaviour you saw

Using `networkctl reconfigure ppp0` to release and acquire a new IPv6 prefix drops default IPv4 route via that link.

### Steps to reproduce the problem

1. Use systemd-networkd for IPv6-PD on a PPPoE link.
    /etc/systemd/network/99-ppp0.network:
    ```
    [Match]
    Name=ppp0
    Type=ppp

    [Link]
    ActivationPolicy=manual

    [Network]
    KeepConfiguration=yes
    DHCP=ipv6
    IPv6AcceptRA=yes

    [DHCPv6]
    WithoutRA=solicit
    UseAddress=no
    UseDNS=no
    UseNTP=no
    UseHostname=no
    UseCaptivePortal=no
    ```
2. `networkctl reconfigure ppp0` 
3. Observe the default IPv4 route via that interface is gone.

**Comment by yuwata** [comment]
Hm? How the route is configured? There is no IPv4 setting in the provided .network file. By default, networkd removes all unmanaged routes. If the route is configured manually or managed by other tools, then please set `ManageForeignRoutes=no` in networkd.conf .

**Comment by serfreeman1337** [comment]
The route is [configured by pppd](https://github.com/ppp-project/ppp/blob/616102e93be1c629821cafd83a89d9e6c0467033/pppd/sys-linux.c#L2239) and it's neither kernel nor static. I guess not dropping this route is a bug with 256.7 and wasn't intended. Will use `ManageForeignRoutes=no` to keep this route.
