### ISSUE TITLE
when systemd-shutdown is called twice on shutdowm, we trigger kernel cgroupfs remount warnings when handling /oldroot

### ISSUE THREAD

**Issue by jamespharvey20** [systemd/systemd#351]
Using systemd arch 221-1.

I am guessing this is similar to Issue #309, needing a suppression somewhere.

After "Reached target Shutdown.", the message appears: 'cgroup: option or name mismatch, new: 0x0 "", old: 0x4 "systemd"'

**Comment by jamespharvey20** [comment]
foutrelis explained on issue #309 that I don't have the patch for suppressing the message on boot, like I thought I did.  I can't say, then, whether this issue is already fixed by the same patch or if it requires another one.

**Comment by dvdhrm** [comment]
This is known, and is due to the re-mounting during shutdown. It's harmless and can be ignored. But maybe we should try using the correct cgroup-tree name during remounts (which might be non-trivial, though).

**Comment by poettering** [comment]
@dvdhrm remounting during shutdown? hmm, where?

**Comment by dvdhrm** [comment]
@poettering I mentioned this warning once to you. I think it was related to re-mounting it read-only (which we do generically on all mount-points during shutdown?).

Maybe this is even unrelated to systemd and just the initrd that does it (which is _not_ dracut on Arch, which is the machine in question here).

**Comment by dvdhrm** [comment]
The origin of this warning is the kernel btw. It prints it if you re-mount a cgroupfs hierarchy but don't specify "name=foobar" again.

**Comment by poettering** [comment]
I figure we should just leave our fingers off /sys/fs/cgroups when remounting everything read-only at shutdown... that should be an easy fix...

**Comment by dvdhrm** [comment]
According to the kernel-source, it should be enought to just not specify "name=" at all. It seems we currently pass an empty string?

**Comment by dvdhrm** [comment]
systemd seems to skip cgroup during shutdown. I cannot see any code that remounts it RO but passes flags. Hence, the warning should not appear. I also cannot see where initcpio in Arch does this.

No idea where that warning originates..

**Comment by poettering** [comment]
@jamespharvey20 any chance you can boot with "systemd.log_level=debug" on the kernel cmdline, then shutdown with "systemctl halt", and take a picture of the last lines you see on screen?

**Comment by medhefgo** [comment]
I looked into this once. I think the remount didn't get skipped because it ended up somewhere in /run/initramfs or /run/sysroot (not too sure) because of the root pivoting. So, I guess the checks to see if a mount should be skipped for read-only mounting does not take that into account.

**Comment by poettering** [comment]
@medhefgo which pivoting precisely? the pivoting at boot or the pivoting at shutdown?

@jamespharvey20 how precisely does your mount table look like right before you shut down?

Does the arch initrd use the pivot-back-to-initrd-at-shutdown logic at all?

**Comment by poettering** [comment]
Is it possible that it's the arch initrd on shutdown that causes the kernel msg, and not actually systemd?

**Comment by medhefgo** [comment]
In this case pivoting back to initrd at shutdown. Also, you can have Arch's mkinitcpio use either busybox or systemd. Mine ueses systemd. But afaik, it always uses systemd-shutdown directly for going back to initramfs. It auto-generates /run/initramfs at shutdown, basically just copying systemd-shutdown to /run/initramfs/shutdown and it's direct dependencies.

**Comment by poettering** [comment]
@medhefgo not following: it's systemd-shutdown that transitions back into the initrd. Are you saying the arch initrd copies the systemd-shutdown binary into /run/initramfs so that it is is actually executed twice at shutdown? What's the rationale for that? Most likely that's the source of the issue here, if this is really the case.

**Comment by Stebalien** [comment]
That's exactly what it does. /cc @falconindy

**Comment by medhefgo** [comment]
initramfs-systemd -> systemd -> mkinitcpio-generate-shutdown-ramfs.service -> systemd-shutdown -> systemd-shutdown (after pivoting back to /run/initramfs)

As in, the initramfs doesn't bother populating /run/initramfs and instead relies on mkinitcpio-generate-shutdown-ramfs.service to create a proper ramfs at shutdown time for us. And even for dracut you'd have 2 instances of systemd-shutdown, no? After all, that's the whole idea behind pivoting back to initramfs.
And the rationale for this is that it reduces code duplication. We already have a tool out there that unmounts/closes/kills stuff for us. It's called systemd-shutdown!

The reason the message pops up is that the logic does not handle the api filesystems that get pivoted into /oldroot well. I think.

**Comment by poettering** [comment]
@medhefgo dracut does not run systemd in the shutdown part, only in the startup part. Right, @haraldh?

I must say when I wrote systemd-shutdown I didn#t think of running it twice. It might need some review to check if all is good if you run it that way... For example, to not do some things twice like invoking /etc/rc.halt and stuff...

Maybe we should move towards always running systemd-shutdown from the initrd, as that does appear smarter to me. Harald?

@medhefgo how precisely does the mount table (i.e. /proc/self/mountinfo) look like between the two systemd-shutdown invocations?

**Comment by medhefgo** [comment]
Before going back to initrd:

```
16 51 0:16 / /sys rw,nosuid,nodev,noexec,relatime shared:6 - sysfs sysfs rw
17 51 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:5 - proc proc rw
18 51 0:6 / /dev rw,nosuid shared:2 - devtmpfs devtmpfs rw,size=506340k,nr_inodes=126585,mode=755
19 16 0:17 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:7 - securityfs securityfs rw
20 18 0:18 / /dev/shm rw,nosuid,nodev shared:3 - tmpfs tmpfs rw
21 18 0:13 / /dev/pts rw,nosuid,noexec,relatime shared:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
22 51 0:19 / /run rw,nosuid,nodev shared:18 - tmpfs tmpfs rw,mode=755
23 16 0:20 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:8 - tmpfs tmpfs ro,mode=755
24 23 0:21 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:9 - cgroup cgroup rw,xattr,name=systemd
25 16 0:22 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:17 - pstore pstore rw
26 23 0:23 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,blkio
27 23 0:24 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,freezer
28 23 0:25 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:12 - cgroup cgroup rw,memory
29 23 0:26 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,cpu,cpuacct
30 23 0:27 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,cpuset
31 23 0:28 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,devices
32 23 0:29 / /sys/fs/cgroup/net_cls rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,net_cls
51 0 8:1 / / rw,noatime shared:1 - ext4 /dev/sda1 rw,data=ordered
34 18 0:31 / /dev/hugepages rw,relatime shared:20 - hugetlbfs hugetlbfs rw
35 16 0:7 / /sys/kernel/debug rw,relatime shared:21 - debugfs debugfs rw
36 18 0:15 / /dev/mqueue rw,relatime shared:22 - mqueue mqueue rw
38 16 0:33 / /sys/kernel/config rw,relatime shared:24 - configfs configfs rw
```

After:

```
16 51 0:16 / /oldroot/sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
17 51 0:4 / /oldroot/proc rw,nosuid,nodev,noexec,relatime - proc proc rw
18 51 0:6 / /oldroot/dev rw,nosuid - devtmpfs devtmpfs rw,size=506340k,nr_inodes=126585,mode=755
19 16 0:17 / /oldroot/sys/kernel/security rw,nosuid,nodev,noexec,relatime - securityfs securityfs rw
20 18 0:18 / /oldroot/dev/shm rw,nosuid,nodev - tmpfs tmpfs rw
21 18 0:13 / /oldroot/dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
22 51 0:19 / /oldroot/run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755
23 16 0:20 / /oldroot/sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755
24 23 0:21 / /oldroot/sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,name=systemd
25 16 0:22 / /oldroot/sys/fs/pstore rw,nosuid,nodev,noexec,relatime - pstore pstore rw
26 23 0:23 / /oldroot/sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
27 23 0:24 / /oldroot/sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
28 23 0:25 / /oldroot/sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
29 23 0:26 / /oldroot/sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
30 23 0:27 / /oldroot/sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
31 23 0:28 / /oldroot/sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
32 23 0:29 / /oldroot/sys/fs/cgroup/net_cls rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls
51 33 8:1 / /oldroot rw,noatime - ext4 /dev/sda1 rw,data=ordered
34 18 0:31 / /oldroot/dev/hugepages rw,relatime - hugetlbfs hugetlbfs rw
35 16 0:7 / /oldroot/sys/kernel/debug rw,relatime - debugfs debugfs rw
36 18 0:15 / /oldroot/dev/mqueue rw,relatime - mqueue mqueue rw
38 16 0:33 / /oldroot/sys/kernel/config rw,relatime - configfs configfs rw
33 0 0:19 /initramfs / rw,nosuid,nodev - tmpfs tmpfs rw,mode=755
37 33 0:6 / /dev rw,nosuid - devtmpfs devtmpfs rw,size=506340k,nr_inodes=126585,mode=755
39 33 0:4 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
40 33 0:16 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
41 33 0:19 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755

```

**Comment by dacoit** [comment]
Here is 'systemctl halt' w/ systemd.log_level=debug: https://gist.github.com/dacoit/4136ac829639d445c62a 

and also 'systemctl halt' w/ both systemd.log_level=debug and debug: https://gist.github.com/dacoit/ad916a42a919f514a728
Latter seems more enlightening.

(Arch Linux)(QEMU/KVM)

**Comment by poettering** [comment]
Ah, given the mount table dumps it's somewhat clear what the issue is: the cgroup sysfs mounts in /oldroot, which we try to remount read-only on the second systemd-shutdown invocation. Now what I wondering about though is how we lose the other mount flags when remounting those dirs read-only.

I figure we didn't notice this earlier, simply because dracut does not invoke systemd-shutdown twice. I am pretty sure though that it actually should and follow what Arch is doing here.

This message is pretty much a cosmetic issue only, but we should fix it, and make sure that on the read-only spree we retain the other mount flags and don't drop them.
