### ISSUE TITLE
Can't login to some tty

### ISSUE THREAD

**Issue by Maxttier** [systemd/systemd#35118]
### systemd version the issue has been seen with

???

### Used distribution

just downloaded Manjaro

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

To work all tty

### Unexpected behaviour you saw

SESSION  UID USER    SEAT  LEADER CLASS   TTY  IDLE SINCE
      2 1000 test seat0 582    user    tty1 no   -    
      3 1000 test -     588    manager -    no   -   

### Steps to reproduce the problem

Can't use one of tty, initially tty1, not show graphic interface and  text, write some errors like on boot, with one core of processor,  now tty2 graphical interface but not respond, can't enter login and password.

**Comment by poettering** [comment]
This is the wrong place for such a bug report. Please contact your distro first, they'll then escalate this to us, if there's a systemd issue.
