### ISSUE TITLE
Improve clarity of `DefaultDependencies` documentation (current list is incomplete)

### ISSUE THREAD

**Issue by zwimer** [systemd/systemd#35139]
### Component

systemd, other

### Is your feature request related to a problem? Please describe

Right now, `systemd.target`'s documentation specifies that if `DefaultDependencies=no` is not set:
- Target units will automatically complement all configured dependencies of type Wants= or Requires= with dependencies of type After= unless DefaultDependencies=no is set in the specified units.
- Target units automatically gain Conflicts= and Before= dependencies against shutdown.target.

Later on during an example it is specified that:
> When adding dependencies to other units, it's important to check if they set DefaultDependencies=. Service units, unless they set DefaultDependencies=no, automatically get a dependency on sysinit.target. In this case, both emergency.target and systemd-networkd.service have DefaultDependencies=no, so they are suitable for use in this target, and do not pull in sysinit.target.

Source: https://www.freedesktop.org/software/systemd/man/latest/systemd.target.html

The fact that the dependency on `sysinit.target` is only ever mention in an 'example' implies to me that:
1. At the bare minimum, the list of consequences of `DefaultDependencies=no` is missing the change in the `sysinit.target` dependency
2. There might be other consequences missing from the list beyond those mentioned

### Describe the solution you'd like

It would be nice if the list starting at the quote below listed all consequences of listing `DefaultDependencies=no` (i.e. all otherwise implicitly added dependencies)
> The following dependencies are added unless DefaultDependencies=no is set:

I'm not sure if the only other dependency not added due to this flag is `sysinit.target` or if there are others (which is really why I'm making this issue) but all of them should be mentioned in this list

### Describe alternatives you've considered

If this is system dependent / non-enumerable in general, at least mention something along the lines of 'depending on the OS, other otherwise-implicitly added dependencies may not be added'. I.e. acknowledge that the list may be incomplete.

**Comment by ElvishJerricco** [comment]
The automatic dependency of services on `sysinit.target` isn't documented in `systemd.target(5)` because it's not a default dependency of *targets*, it's a default dependency of *services*. It's documented in `systemd.service(5)` as it should be.

> - Service units will have dependencies of type Requires= and After= on sysinit.target,

**Comment by zwimer** [comment]
That's a very good point; I think I confused this documentation with that of documentation for `DefaultDependencies=` in general.
