### ISSUE TITLE
networkd: there is a memory leak in nexthop_add_new

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#35164]
I'm guessing it's from https://github.com/systemd/systemd/pull/35119. I'm not sure how to reproduce it yet.

```sh
=================================================================
==573==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x7f582cad5aa3 in malloc (/usr/lib/clang/19/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so+0xd5aa3) (BuildId: 98d6f0ad935c4ea5ed3cdc909871a71680370a1>
    #1 0x56363e8a8d8d in malloc_multiply /work/build/../src/src/basic/alloc-util.h:119:16
    #2 0x56363e8a890b in nexthop_new /work/build/../src/src/network/networkd-nexthop.c:128:19
    #3 0x56363e8bc902 in nexthop_add_new /work/build/../src/src/network/networkd-nexthop.c:412:13
    #4 0x56363e8b9c3f in manager_rtnl_process_nexthop /work/build/../src/src/network/networkd-nexthop.c:1140:21
    #5 0x7f582c24f4f1 in process_match /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:314:21
    #6 0x7f582c2453ce in process_running /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:344:21
    #7 0x7f582c244f71 in sd_netlink_process /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:374:13
    #8 0x7f582c24a078 in io_callback /work/build/../src/src/libsystemd/sd-netlink/sd-netlink.c:655:13
    #9 0x7f582bea2b95 in source_dispatch /work/build/../src/src/libsystemd/sd-event/sd-event.c:4228:21
    #10 0x7f582bea0c18 in sd_event_dispatch /work/build/../src/src/libsystemd/sd-event/sd-event.c:4849:21
    #11 0x7f582bea6566 in sd_event_run /work/build/../src/src/libsystemd/sd-event/sd-event.c:4910:21
    #12 0x7f582bea74ff in sd_event_loop /work/build/../src/src/libsystemd/sd-event/sd-event.c:4931:21
    #13 0x56363e53dc8d in run /work/build/../src/src/network/networkd.c:114:13
    #14 0x56363e53ad97 in main /work/build/../src/src/network/networkd.c:121:1
    #15 0x7f582ac11247 in __libc_start_call_main (/lib64/libc.so.6+0x3247) (BuildId: 948d229348b56bdcf4e0a96d5ccd8fb175f617f0)
    #16 0x7f582ac1130a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x330a) (BuildId: 948d229348b56bdcf4e0a96d5ccd8fb175f617f0)
    #17 0x56363e53ab44 in _start (/usr/lib/systemd/systemd-networkd+0x15fb44) (BuildId: ab2c9531981cbfe2507953d7e4a50ec991e70568)
SUMMARY: AddressSanitizer: 256 byte(s) leaked in 2 allocation(s).
```

**Comment by yuwata** [comment]
@evverx Is this only happens after the interface enters the failed state? Or, can be triggered only by 'normal' operation?

**Comment by yuwata** [comment]
Please provide relevant logs around the first failure.

**Comment by evverx** [comment]
As far as I can remember when this particular memory leak was reported the interface wasn't in the failed state. When the memory leak from https://github.com/systemd/systemd/pull/35119#discussion_r1842837453 was reported the interface was in the failed state. As mentioned it's getting bigger so eventually the fuzzer should hopefully arrive at some sort of reproducer with a bunch or router advertisements it should send.

**Comment by evverx** [comment]
@yuwata I haven't gotten closer either yet. The (somewhat) good news is that it is confirmed by Valgrind
```sh
==282== HEAP SUMMARY:
==282==     in use at exit: 18,353 bytes in 49 blocks
==282==   total heap usage: 90,303 allocs, 90,254 frees, 19,566,515 bytes allocated
==282==
==282== 4,608 bytes in 36 blocks are definitely lost in loss record 8 of 9
==282==    at 0x4841866: malloc (vg_replace_malloc.c:446)
==282==    by 0x126B5D: malloc_multiply (alloc-util.h:119)
==282==    by 0x127DDF: nexthop_new (networkd-nexthop.c:128)
==282==    by 0x1293BC: nexthop_add_new (networkd-nexthop.c:412)
==282==    by 0x12D7CE: manager_rtnl_process_nexthop (networkd-nexthop.c:1140)
==282==    by 0x4CEF126: process_match (sd-netlink.c:314)
==282==    by 0x4CEF394: process_running (sd-netlink.c:344)
==282==    by 0x4CEF5FD: sd_netlink_process (sd-netlink.c:374)
==282==    by 0x4CF066B: io_callback (sd-netlink.c:655)
==282==    by 0x4C0A375: source_dispatch (sd-event.c:4228)
==282==    by 0x4C0CA0A: sd_event_dispatch (sd-event.c:4849)
==282==    by 0x4C0CF97: sd_event_run (sd-event.c:4910)
==282==
==282== LEAK SUMMARY:
==282==    definitely lost: 4,608 bytes in 36 blocks
==282==    indirectly lost: 0 bytes in 0 blocks
==282==      possibly lost: 0 bytes in 0 blocks
==282==    still reachable: 13,745 bytes in 13 blocks
==282==         suppressed: 0 bytes in 0 blocks
```
so it isn't a leak sanitizer glitch or anything like that.

**Comment by yuwata** [comment]
Thanks. What kind of message did you send to the host? I guess you torture networkd by sending random RAs or Redirect messages. No? Please give some hints.

**Comment by evverx** [comment]
The fuzzer sends all sorts of router advertisements automatically so I can't say for sure what exactly it does (until it can reproduce it reliably). Debug logs usually contain a lot of error messages like
```sh
Failed to parse NDisc option header: Bad message
host0: NDISC: Failed to parse NDisc options in router advertisement message, ignoring: Bad message
host0: ndisc_check_ready(): SLAAC addresses and routes are not set.
Failed to parse NDisc option header: Bad message
host0: NDISC: Failed to parse NDisc options in router advertisement message, ignoring: Bad message
host0: Forgetting removed NDisc route (n/a): dst: n/a, src: n/a, nexthop: 2077256765, prefsrc: n/a, table: main(254), priority: 1024, proto: ra, scope: globa>
Failed to parse NDisc option 5, ignoring: Invalid argument
host0: NDISC: Received Router Advertisement from fe80::28ce:ff:fe9c: flags=0x2c(home-agent), preference=high, lifetime=17h 2min 47s
host0: NDISC: Invoking callback for 'router' event.
Setting '/proc/sys/net/ipv6/neigh/host0/base_reachable_time_ms' to '2415919360'
host0: Failed to apply neighbor reachable time (2415919360), ignoring: Invalid argument
```
so they are huge (and off by default). I'll turn them on and try to attach stuff related to nexthops.

**Comment by yuwata** [comment]
@evverx Could you test #35267? It should not fix the memleak, but more assertions are added, so may provide more information.

**Comment by evverx** [comment]
I pointed it to that PR about an hour ago but I haven't seen any crashes yet. If anything pops up I'll add it here.

**Comment by yuwata** [comment]
Thanks. If the PR somehow fix the memleak, could you bisect the PR and find which commit fixes the memleak?

**Comment by evverx** [comment]
It doesn't fix the memleak. They still pop up from time to time with both ASan and Valgrind. No assertions are hit though.

**Comment by yuwata** [comment]
@evverx BTW, do all leaks come from `nexthop_add_new()` ? https://github.com/systemd/systemd/issues/35164#issuecomment-2488347075 Or, do you observe any other leaks?

**Comment by evverx** [comment]
The backtrace is always the same and points to `nexthop_add_new` as far as I can tell.

**Comment by evverx** [comment]
I've just pulled the PR and I think tomorrow it should be clear whether the memory leak is gone.

(FWIW Given that it's not that kind of leak where it's possible to consume all the memory reliably by just sending captive portals (or whatever) I don't think it's urgent or anything like that)

**Comment by yuwata** [comment]
@evverx Thank you for testing the patch.

Please open a new issue if you find anything.

**Comment by yuwata** [comment]
@evverx Please open a new issue with relevant logs.

**Comment by yuwata** [comment]
> (FWIW Given that it's not that kind of leak where it's possible to consume all the memory reliably by just sending captive portals (or whatever) I don't think it's urgent or anything like that)

@evverx We've introduced upper limit for number of captive portals stored in the memory. So, you observed that the upper limit does not work?

**Comment by evverx** [comment]
> So, you observed that the upper limit does not work?

No, I didn't. The limit is fine and works as expected. I was just trying to say that in terms of importance this memory leak is different from reliable memory leaks like https://github.com/systemd/systemd/issues/28277.
