### ISSUE TITLE
Option to only hibernate on battery when using suspend-then-hibernate

### ISSUE THREAD

**Issue by BBaoVanC** [systemd/systemd#35160]
### Component

systemd

### Is your feature request related to a problem? Please describe

In `/etc/systemd/sleep.conf` I have set `HibernateDelaySec` to `3h`. This is great since it stops my battery from running down very much during sleep if I leave my laptop unused for a long time. But I would also like to have it not hibernate when on AC power, because there's no risk of battery drainage there.

### Describe the solution you'd like

There should be an option in `sleep.conf`, perhaps called `HibernateOnACPower` or something, which can be used to disable the default behavior of hibernating even when on AC power. Then, if that option is changed, it should ignore the hibernate delay on AC power.

Then I think the hibernate delay should start over from the time the laptop is unplugged, so it doesn't just immediately hibernate, but I would like feedback on what other people think the exact behavior should be when unplugged from power.

### Describe alternatives you've considered

I haven't tested this, but I think this could also be done by replacing usage of HibernateDelaySec with a custom timer (using `WakeSystem=true`) that runs a script to check battery level, AC power state, and time elapsed manually. But IMO this should be integrated into systemd suspend-then-hibernate directly. 

### The systemd version you checked that didn't have the feature you are asking for

256.7

**Comment by jdholtz** [comment]
I believe this can be closed as it was added in #33846, systemd 257.
