### ISSUE TITLE
System hangs at boot on systemd-backlight with NVidia 9400M and proprietary driver

### ISSUE THREAD

**Issue by SamuelGilbert42** [systemd/systemd#3525]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230 (Other previous versions also had the issue, but I don't know with which version the issue first appeared)
### Used distribution

> Arch Linux x86_64
### In case of bug report: Expected behaviour you didn't see

> I expected the system to boot up normally and the intensity of the backlight to be restored
### In case of bug report: Unexpected behaviour you saw

> The boot process just hung there and doesn't complete.  The system (Dell Studio 14Z Laptop) doesn't respond to any keyboard input.  I tried to leave it there for more than 30 minutes, but the boot process did not complete.
### In case of bug report: Steps to reproduce the problem

> Boot the system.  Get an unresponsive system before completing the boot process.

Since the boot process is asynchronous, the initialization order changed from one boot to the next.  The message about the backlight was often one of the last ones.  I removed **/usr/lib/systemd/systemd-backlight** and the system boots every time without any problem.

The issue does not occur when the nvidia driver isn't loaded.

**Comment by poettering** [comment]
Well, if the system hangs if the proprietary nvidia driver is used, then please consider contacting the nvidia folks regarding this. We can't work around borked closed source drivers, sorry.

**Comment by ethus3h** [comment]
For what it's worth, I ran into what I think may be this same bug using Gentoo and reported it to Nvidia before finding this bug report (reference #160617-000314).

**Comment by ethus3h** [comment]
Again FWIW, I eventually worked around this by using a patched version of the 304 driver series.

Apparently GitHub doesn't support attaching patch files. Dafuq?

```
--- a/kernel/nv-linux.h
+++ b/kernel/nv-linux.h
@@ -256,6 +256,15 @@
 #include <linux/seq_file.h>
 #endif

+/*
+ * As of version 304.131, os-agp.c and os-mtrr.c still use deprecated
+ * kernel APIs for mtrr which are no longer exported since 4.3, causing
+ * the module to error out when loaded.
+ */
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,3,0)
+#undef CONFIG_MTRR
+#endif
+
 #if !defined(NV_VMWARE) && defined(CONFIG_MTRR)
 #include <asm/mtrr.h>
 #endif
```
