### ISSUE TITLE
Systemd stop my service for no reason

### ISSUE THREAD

**Issue by rain2307** [systemd/systemd#35254]
## Bug Report

1. systemd version: 
```
 systemd --version
systemd 255 (255.4-1ubuntu8.4)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

```

2. distribution: Ubuntu 24.04.1 LTS x86_64 
3. kernel: 6.8.0-40-generic 
4. cpu: x86_64
5. components: systemd
6. Expected: do not stop my service
7. Unexpected: stop my service 
8. Reproduce: create a service and start , wait 2-3 hours, it will be stopped.

-----------------

I defined a service, but it automatically stops 2-3 hours after starting without any operation on my part.

From the status, memory issues can be ruled out, and it's definitely not a CPU problem.

```
OS: Ubuntu 24.04.1 LTS x86_64 
Host: CVM 3.0 
Kernel: 6.8.0-40-generic 
```

```
● xx.service - xxx
     Loaded: loaded (/etc/xdg/systemd/user/xx.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-11-20 20:45:26 CST; 31s ago
   Main PID: 3294421 (xx)
      Tasks: 6 (limit: 1969)
     Memory: 4.5M (peak: 4.8M)
        CPU: 95ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xx.service
             └─3294421 /home/abc/xx server start
```

The following is the journalctl log.

```
Nov 20 10:23:36 VM-16-12-ubuntu systemd[3063672]: Stopping xx.service - xxx...
Nov 20 10:23:36 VM-16-12-ubuntu systemd[3063672]: Stopped xx.service - xxx.
Nov 20 10:23:36 VM-16-12-ubuntu systemd[3063672]: xx.service: Consumed 3min 49.256s CPU time.

```

Here is my service file:
```
[Unit]
Description=xxx
After=network.target

[Service]
ExecStart=/home/xxx/server start
ExecStop=/home/xxx/server stop
WorkingDirectory=/home/xxx/.cache
Restart=on-failure
RestartSec=10
Type=simple

[Install]
WantedBy=default.target
```

Why does it stop automatically? 
Are there any other methods to accurately locate the problem? 
My own logs show no exceptions.
From the logs, it appears that systemd is actively stopping my service.

**Comment by Elcoid** [comment]
Hello, I'm curious as to why this issue was closed. Was the root cause found? I'm having the same problem in a VM on Azure. In my case however, my two services are stopped exactly at the same time after months of running without issues. It happened a few times in the last year.

Information of my setup:
1. `systemd --version`
```
systemd 255 (255.4-1ubuntu8.12)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```
2. Distribution: Ubuntu 24.04.3 LTS
3. Kernel: `6.14.0-1017-azure`
4. CPU arch: x86_64
