### ISSUE TITLE
Will these directories be merged in the future?

### ISSUE THREAD

**Issue by kindusmithkindu** [systemd/systemd#35285]
### Is your feature request related to a problem? Please describe

systemd v256.7 requires merging /bin and /sbin. confuses me

### Describe the solution you'd like

I think some directories that may be merged or disappeared in the future are the /usr/bin directory. It does not need to always be the source directory of the /bin symbolic link. There will no longer be a directory like bin under /usr. Setting bin under / is enough. Also, /lib and /lib64 should be merged back into /lib since 32-bit support is gradually disappearing. /mnt and /media will also be merged into one directory. Because these two mount points are often confused, the /lost+found directory may disappear, and systemd may provide power-off data protection for the disk, so FHS 4.0 will be released in the future？

### Describe alternatives you've considered

nothing to do

### The systemd version you checked that didn't have the feature you are asking for

256.7

**Comment by AdrianVovk** [comment]
Doesn't seem like you're asking for anything specific to be changed in systemd here. So, I'll close this.
