### ISSUE TITLE
systemd-sysext: Allow for additional hierarchies

### ISSUE THREAD

**Issue by frederictobiasc** [systemd/systemd#35284]
### Component

systemd-sysext

### Is your feature request related to a problem? Please describe

Currently, systemd-sysext ignores files in hierarchies different to `/usr` and `/opt` by design.

In NixOS-like distributions, system binaries are usually shipped in  `/nix/store` and symlinked to the actual environment.

NixOS is great to build immutable appliance images. The sysext mechanism is great to augment such generic immutable appliances.

To be more useful in distributions like NixOS it would be great if there was a way to also extend the `/nix/store` in the same way it's currently done with `/usr` and `/opt`.

### Describe the solution you'd like

Either relax [parse_env_extension_hierarchies](https://github.com/systemd/systemd/blob/b7eefa1996f33f29b32bc9e5f20f4e70fa22a14a/src/shared/extension-util.c#L126) to also accept freely defined hierarchies as an environment variable
or a build option for additional hierarchies

### The systemd version you checked that didn't have the feature you are asking for

256.7

**Comment by poettering** [comment]
it might be acceptable to allow defining additional such dirs at compile time to cover for cases like this. prep a PR.

**Comment by frederictobiasc** [comment]
> There's already an env var for this, have you tried it? `SYSTEMD_SYSEXT_HIERARCHIES=`

I have now, and it works as intended :), thank you!
