### ISSUE TITLE
bootctl, systemd-logind: Failed to open '/boot//loader/entries': Remote address changed

### ISSUE THREAD

**Issue by bam80** [systemd/systemd#35293]
### systemd version the issue has been seen with

systemd 256 (256.8-1.fc41)

### Used distribution

Fedora Linux 41.20241119.0 (Silverblue)

### Linux kernel version used

6.11.8-300.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

``` 
$ bootctl list
           Boot Loader Entries:
                    type: Boot Loader Specification Type #1 (.conf)
                   title: Fedora Linux 36 (Workstation Edition) (default) (selected)
                      id: ...
                  source: /boot/efi/loader/entries/entry-token-kernel-version.conf
                 version: kernel-version
              machine-id: ...
                   linux: /entry-token/kernel-version/linux
                  initrd: /entry-token/kernel-version/initrd
                 options: root=...

                    type: Boot Loader Specification Type #2 (.efi)
...
```
### Unexpected behaviour you saw

```
$ bootctl list 
Failed to open '/boot//loader/entries': Remote address changed

$ bootctl
Failed to open '/boot//loader/entries': Remote address changed
...
```
The same error from `systemd-logind`, see below.

### Steps to reproduce the problem

transitioning to a separate /boot partition, run the `bootctl` command:
https://github.com/ostreedev/ostree/issues/1719#issuecomment-1995908624

Other report on Silverblue:
https://unix.stackexchange.com/questions/785355/persistent-systemd-logind-error-in-fedora-silverblue-failed-to-open-boot-loa

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# unrelated to the bootctl run

$ journalctl -b -u systemd-logind.service
...
ноя 19 21:04:02 host systemd-logind[918]: Failed to open '/boot//loader/entries': Remote address changed
ноя 19 21:14:09 host systemd-logind[918]: Failed to open '/boot//loader/entries': Remote address change
...
```

**Comment by yuwata** [comment]
The error code suggests that the path `/boot//loader/entries` contains symlink(s). Is it true?

**Comment by yuwata** [comment]
Not familiar with ostree or silverblue, but judging from https://github.com/ostreedev/ostree/issues/1719#issuecomment-2452143752, ostree configures /boot/loader as a symlink. systemd-boot does not accept that.

**Comment by bam80** [comment]
Well, we have to invent common solution, then :)

**Comment by bam80** [comment]
> systemd-boot does not accept that

Please note the system boots though, so maybe `systemd-boot` itself does actually accept that, but other user-mode utils (
bootctl, systemd-logind) don't?

**Comment by yuwata** [comment]
Yeah, more accurately, (at least currently,) systemd-boot may work but we do not support such setup, and other tools like bootctl or so refuses such.

**Comment by bam80** [comment]
While using symlinks might be a problem per se, this particular issue is different.

Please note the circumstances when the issue first happened:

> After transitioning to a separate /boot partition I started to see this error:

> If I return to my previous /boot placement (on btrfs subvolume), I see no such error.

https://github.com/ostreedev/ostree/issues/1719#issuecomment-1995908624

So there is _no_ issue if `/` and `/boot/` are on the same partition, even with the symlinks.

Having that, should we reopen this issue? @cgwalters
