### ISSUE TITLE
interpret I% and friends in OnCalendar

### ISSUE THREAD

**Issue by conqp** [systemd/systemd#3534]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230
### Used distribution

> Arch
### In case of bug report: Expected behaviour you didn't see

> According to https://www.freedesktop.org/software/systemd/man/systemd.unit.html Systemd.timer s are so-called units. Hence I expected them to retain the behaviour described there.
> I want to have a timer template pacman-update@.timer like so:

```
[Unit]
Description=Perform a pacman update

[Timer]
OnCalendar=%I
Persistent=true

[Install]
WantedBy=timers.target
DefaultInstance=daily
```

to be able to trigger the underlying service daily (default instance) or at some other interval, described by the instance following the @.
### In case of bug report: Unexpected behaviour you saw

> Trying to start the aforementioned unit using its default instance fails:

```
$ sudo systemctl start pacman-update@.timer
Failed to start pacman-update@.timer: Unit name pacman-update@.timer is missing the instance name.
See system logs and 'systemctl status pacman-update@.timer' for details.
```

And so does starting a specific instance:

```
$ sudo systemctl start pacman-update@daily.timer
Failed to start pacman-update@daily.timer: Unit pacman-update@daily.timer is not loaded properly: Invalid argument.
See system logs and 'systemctl status pacman-update@daily.timer' for details.
```

The journal says:

```
Failed to dump process list, ignoring: Unit pacman-update@daily.timer is not loaded properly: Invalid argument.
● pacman-update@daily.timer - Perform a pacman update
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Jun 13 12:30:11 ThinkCentre systemd[1]: [/usr/lib/systemd/system/pacman-update@.timer:5] Failed to parse calendar specification, ignoring: %I
Jun 13 12:30:11 ThinkCentre systemd[1]: pacman-update@daily.timer: Timer unit lacks value setting. Refusing.
Jun 13 12:31:11 ThinkCentre systemd[1]: [/usr/lib/systemd/system/pacman-update@.timer:5] Failed to parse calendar specification, ignoring: %I
Jun 13 12:31:11 ThinkCentre systemd[1]: pacman-update@daily.timer: Timer unit lacks value setting. Refusing.
Jun 13 12:31:17 ThinkCentre systemd[1]: [/usr/lib/systemd/system/pacman-update@.timer:5] Failed to parse calendar specification, ignoring: %I
Jun 13 12:31:17 ThinkCentre systemd[1]: pacman-update@daily.timer: Timer unit lacks value setting. Refusing.
Jun 13 12:31:27 ThinkCentre systemd[1]: [/usr/lib/systemd/system/pacman-update@.timer:5] Failed to parse calendar specification, ignoring: %I
Jun 13 12:31:27 ThinkCentre systemd[1]: pacman-update@daily.timer: Timer unit lacks value setting. Refusing.
Jun 13 12:31:27 ThinkCentre systemd[1]: [/usr/lib/systemd/system/pacman-update@.timer:5] Failed to parse calendar specification, ignoring: %I
Jun 13 12:31:27 ThinkCentre systemd[1]: pacman-update@daily.timer: Timer unit lacks value setting. Refusing.
```

The official documentation, however, does not state any kind of exception for systemd.timer units different from other systemd.units such as systemd.services from which I would expect to handle the instance placeholders according to the systemd.unit documentation.
### In case of bug report: Steps to reproduce the problem

> 1) Create the aforementioned unit as /usr/lib/systemd/system/pacman-update@.timer
> 2) Try to start it as mentioned.

**Comment by arvidjaar** [comment]
> `systemctl start pacman-update@.timer`

Template cannot be used as unit; only template instance can.

> `Failed to parse calendar specification, ignoring: %I`

Well, specifiers are not interpreted everywhere. Unfortunately there is no exhaustive reference which configuration directives interpret them. So this should be treated either as documentation bug or RFE to allow specifiers in this case.

**Comment by johannbg** [comment]
I dont think this is a bug it's misconfigured type units based on reading the wrong documentation for the type unit in question ( confusing type timers with type service ). Even where he's placing the type unit(s) is wrong. 

If he wants daily system updates he needs to a create type service unit in /etc/systemd/system something along the lines of below for arch ( Note not an arch user so adjust accordingly )
/etc/systemd/system/daily-update.service 

[Unit]
Description=Daily Automatic System Update
After=network-online.target 

[Service]
ExecStart=/usr/bin/pacman -Syuq --noconfirm

Then create type timer unit that bears the same name as the type service unit.
/etc/systemd/system/daily-update.timer

[Unit]
Description=Daily Automatic System Update

[Timer]
Unit=daily-update.service 
OnCalendar=daily

Then reload the systemd daemon to pick up those type units and start the timer

**Comment by arvidjaar** [comment]
@johannbg 

> If he wants daily

Quoting OP

> at some other interval, described by the instance following the @

So usage of specifier in `OnCalendar` was intentional.

> reading the wrong documentation

Which one? Specifiers are described in `man systemd.unit`; and `foo.timer` is most certainly a systemd unit. Please show where documentation says that specifiers cannot be used in `OnCalendar`? Or that templates cannot be used for timers for that matter?

**Comment by johannbg** [comment]
@arvidjaar the supported values for OnCalendar can be found in SYSTEMD.TIME(7) and specifier is never is stated there nor would it make sense to support it afaikt.

**Comment by conqp** [comment]
@johannbg 
"He" can safely be addressed directly.

> I dont think this is a bug it's misconfigured type units based on reading the wrong documentation for the type unit in question ( confusing type timers with type service ). Even where he's placing the type unit(s) is wrong. 

Nope. Both, services and timers are units in systemd.
Neither is the placement wrong. You can safely do it in /usr/lib/systemd/system in Arch.

I also have an appropriate service to be triggered by the timer in question:

```
$ cat /usr/lib/systemd/system/pacman-update.service
[Unit]
Description=Download pacman packages
After=network.target
ConditionPathExists=!/var/lock/pacman.update

[Service]
Type=oneshot
ExecStartPre=/usr/bin/pacman -Sc --noconfirm
ExecStart=/usr/bin/pacman -Syuw --noconfirm
```

However this has nothing to to with my problem regarding the timers.

I agree with @arvidjaar:
It should be treated then as a feature request instead. Though it might as well be a documentation bug until this is not implemented.

Neither are "supported values" to be confused with "placeholders". Placeholders may well contain the supported values mentioned in the systemd.timer documentation.

**Comment by johannbg** [comment]
@conqp administrators and end users should not be placing type units in /usr/lib/systemd/system but only in /etc/systemd/system as has been stated and discussed many times in many places and you can already define multiple time intervals in OnCalendar supporting specifier there makes no sense.

**Comment by conqp** [comment]
These units are part of a self-made package, which is installed with pacman.
It is not an only-local config.
However on some systems I want to _enable_ pacman-update@daily.timer on others pacman-update@weekly.timer or whatever calendar setting.
Otherwise I would need to write an own timer for each system doing the excat same thing just at another time.

**Comment by poettering** [comment]
%I is only interpreted in some fields, not in all. Are you asking we should support it in OnCalendar= too?

**Comment by conqp** [comment]
@poettering 
Yes. That'd be great.
