### ISSUE TITLE
Add `systemd-run --split-string=` option

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#35346]
### Component

systemd-run

### Is your feature request related to a problem? Please describe

For script shebangs, the kernel passes everything after the command as a single argument  (e.g. `#!/bin/cmd 1 2` is understood as `cmd "1 2"`). To work around this, you can instead use `/usr/bin/env --split-string cmd 1 2` to split the arguments up.

### Describe the solution you'd like

To save needing to execute `env`, and to help with other niche scripting purposes, I'd be convenient if `systemd-run` had an equivalent `--split-string=` option so the shebang could be simplified to `#!/usr/bin/systemd-run --split-string ...`.

### Describe alternatives you've considered

Continue to use `#!/usr/bin/env -S ..` in the shebang.

### The systemd version you checked that didn't have the feature you are asking for

257-rc2

**Comment by YHNdnzj** [comment]
Frankly, this seems extremely exotic to me, and IIUC the implementation requires doing option parsing against a string with "--split-string" at the beginning of exec args passed, which feels hacky.

**Comment by Winterhuman** [comment]
It is *very* niche, I will admit. I hadn't even thought about the fact that `--split-string` itself would need to be parsed. I'm not sure what other options there are for getting around the shebang's restrictions beyond adding `--split-string`, if any

**Comment by NekkoDroid** [comment]
You could make a wrapper script that simply passes the parameters unquoted to `systemd-run`:

```shell
#!/bin/sh
exec /usr/bin/systmed-run $@
```

You can then save this to something like `/usr/bin/systemd-shebang` or so and it should work as you are expecting.

---

This could in theory be another multi-call option which simply changes the parsing behaviour a bit (e.g. a wrapper for `parse_argv` that splits the args before and chain calls it [systemd-shebang.patch (untested)](https://github.com/user-attachments/files/18042814/systemd-shebang.patch))
