### ISSUE TITLE
systemctl edit and polkit clarification

### ISSUE THREAD

**Issue by kai-tub** [systemd/systemd#35344]
### Component

systemctl

### Is your feature request related to a problem? Please describe

Hey,

I am trying to move away from `sudo` and take more advantage of `polkit`.
`systemctl` usually _just works_ and asks for authentication if a user needs elevated privileges.
The only issue where this is _not true_ is when I call `systemctl edit --runtime`, for example. Then the command fails immediately with a permission issue:
`Failed to create temporary file for '/run/systemd/system/audit.service.d/override.conf': Permission denied`

I assume that `polkit` only asks for elevated privileges when it changes/touches the _system state_, yet I find it a bit surprising to see this command fail.

### Describe the solution you'd like

I would like to see some clarification on what the "recommended" way is to call `systemctl edit`.
Especially with `polkit` doing all of the work _most_ of the time and the posts related to `run0 vs sudo` I would like to better understand why `systemctl edit` also doesn't ask for permission with `polkit` to create the temporary file.

PS: I have very little knowledge about the internals, so please excuse me if this is obvious for others.

**Comment by YHNdnzj** [comment]
Well, `systemctl` usually calls a remote method via IPC (e.g. to pid1 or logind), and the actual work that requires privilege is carried out by the daemon. `polkit` cannot _grant_ the local process/client privilege, but only verifies the privilege of client for the remote daemon. Hence the model won't apply to systemctl edit, which needs to invoke an editor directly.

Sorry, but this is not something actionable for us. Closing.
