### ISSUE TITLE
CPUQuota reset with systemctl set-property set to weird percentage

### ISSUE THREAD

**Issue by nagworld9** [systemd/systemd#35355]
### systemd version the issue has been seen with

229

### Used distribution

Ubuntu 1604

### Linux kernel version used

4.15.0-1113-azure

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

when I reset the CPUQuota with systemctl set-property for service I would expect to see 

```
systemctl show walinuxagent | grep CPUQuota
CPUQuotaPerSecUSec=infinity

cat /run/systemd/system/walinuxagent.service.d/50-CPUQuota.conf 
[Service]
CPUQuota=
```

### Unexpected behaviour you saw

I was seeing weird number in both places

```
systemctl show walinuxagent | grep CPUQuota
CPUQuotaPerSecUSec=584542y 2w 2d 20h 1min 49.549568s

cat /run/systemd/system/walinuxagent.service.d/50-CPUQuota.conf 
[Service]
CPUQuota=1844674407370955%

```

### Steps to reproduce the problem

Set some CPUQuota

systemctl set-property {service} CPUQuota=20% --runtime

Later, reset the quota
systemctl set-property {service} CPUQuota= --runtime

**Comment by gitzdnex** [comment]
I have just tested this on user service
```
systemd --version
systemd 255 (255.4-1ubuntu8.4)
```

And it works correctly imho.
```
$ systemctl --user set-property eclipse CPUQuota=20% --runtime
$ systemctl --user cat eclipse
....
# /run/user/1000/systemd/user.control/eclipse.service.d/50-CPUQuota.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Service]
CPUQuota=20%
....
$systemctl --user set-property eclipse CPUQuota= --runtime
$systemctl --user cat eclipse
....
# /run/user/1000/systemd/user.control/eclipse.service.d/50-CPUQuota.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Service]
CPUQuota=
....
```
