### ISSUE TITLE
`man 7 daemon` autoconf/automake snippets should be licensed under MIT-0 among other example codes

### ISSUE THREAD

**Issue by medicalwei** [systemd/systemd#35356]
### systemd version the issue has been seen with

main (321c202)

### Used distribution

Unrelated

### Linux kernel version used

Unrelated

### CPU architectures issue was seen on

other

### Component

other

### Expected behaviour you didn't see

* This part of example code should be licensed under MIT-0 among other standalone example code in `/man`

### Unexpected behaviour you saw

* Found LGPL-2+ license in SPDX header of the document, with no special attribution of the snippets.

### Steps to reproduce the problem

1. Attempt to copy the snippets from `man 7 daemon` for a proprietary autoconf/automake project

**Comment by yuwata** [comment]
-> #35358

**Comment by medicalwei** [comment]
#35359 reverted the commit, and is waiting for the author's approval on copyright change.
