### ISSUE TITLE
cdrom_id --eject-media does not umount CD mountpoint

### ISSUE THREAD

**Issue by srakitnican** [systemd/systemd#3536]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd-222-14.fc23.x86_64

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

>  Fedora
### In case of bug report: Expected behaviour you didn't see

> By pressing hardware eject button I expect system to make necessary cleanup afterwards by removing mountpoint to a CD and similar.
### In case of bug report: Unexpected behaviour you saw

> When pressing hardware eject button "cdrom_id --eject-media" does not umount CD properly resulting in mountpoint being reused for the next CD inserted, leading to weird behavior like: CD label and mountpoint name left from previous CD and some data missing from new CD.
### In case of bug report: Steps to reproduce the problem

> Insert a CD wait for it to mount. Note the label and mountpoint. Eject the CD by pressing hardware CD/DVD ROM drive button (note the mountpoint still exist). Insert new CD and note it reusing old mountpoint and possibly some data missing.
### More info:

https://bugzilla.redhat.com/show_bug.cgi?id=1234317#c53
https://github.com/systemd/systemd/issues/1779#issuecomment-178970183

**Comment by karelzak** [comment]
BTW, would be better to call eject(1) from util-linux?

 (if I good remember udisks/gnome uses eject), it's more smart and support many scenarios...

**Comment by poettering** [comment]
I figure this issue is obsolete now, as ebc8968bc0b6fc460099041f5ae1262ca17eeb6e got merged which binds mount points to their backing cdroms and thus systemd will automatically stop them.
