### ISSUE TITLE
Unmanaged interface turns "pending" on networkd restart, blocks wait-online

### ISSUE THREAD

**Issue by antifuchs** [systemd/systemd#35371]
### systemd version the issue has been seen with

256.7

### Used distribution

NixOS nixos-unstable (rev 23e89b7da85c3640bbc2173fe04f4bd114342367)

### Linux kernel version used

6.6.60

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Restarting systemd-networkd, one interface (`tailscale0`, run by a tailscaled service unit) that was "unmanaged" state before the restart should come back in "unmanaged" state, as it was before. Furthermore, systemd-networkd-wait-online.service should recognize that all interfaces are present and accounted for in a timely fashion.

### Unexpected behaviour you saw

When restarting systemd-networkd when the systemd package changes (e.g. one of its dependencies changed, which happens about once every few weeks on nixpkgs-unstable), the tailscale0 interface (which is up before the restart and remains up after) turns into "pending" state. This blocks the `systemd-networkd-wait-online.service` unit from completing, expecting the tailscale0 interface to get settled in udev. That unit times out and my system upgrades fail.

When that happens, a `udevadm trigger --verbose --settle --action add /sys/class/net/tailscale0` fixes the issue, but this seems like a not-ideal situation. @ElvishJerricco suggested reporting this here & tagging him in, because he's about as stumped by why the interface turns unmanaged as I am.

### Steps to reproduce the problem

To start with, this is an annoying one to reproduce: I can't trigger it unless I apply a new system configuration that requires a restart of networkd, and then when the issue has been resolved using udevadm (as mentioned above), the issue stays unreproducible unless I reboot into the previous system configuration & apply the new configuration again. Anyway, here goes:

1. Have a `tailscale0` interface with the following properties:
```console
:;    networkctl status tailscale0
● 21: tailscale0
                   Link File: /nix/store/ivqjhj99firnjq7gp14qf35821viwi5m-systemd-256.7/lib/systemd/network/99-default.link
                Network File: n/a
                       State: routable (unmanaged)
                Online state: unknown
                        Type: none
                        Kind: tun
                      Driver: tun
                         MTU: 1280 (min: 68, max: 65535)
                       QDisc: fq
IPv6 Address Generation Mode: random
    Number of Queues (Tx/Rx): 1/1
            Auto negotiation: no
                      Duplex: full
                        Port: tp
[..., IPs and identifyable tailscaled logs redacted]
```
2. Run `nixos-rebuild test` on a system configuration that requires systemd-networkd (and optionally tailscaled, it doesn't seem to matter) to restart.
3. Observe that the interface is now in setup state "pending":
```console
● 20: tailscale0
                   Link File: n/a
                Network File: n/a
                       State: routable (pending)
                Online state: unknown
                        Type: none
                        Kind: tun
                         MTU: 1280 (min: 68, max: 65535)
                       QDisc: fq
[...]
```
4. When running with log level `debug`, systemd-networkd logs the following lines (full log included below):
```
Nov 26 09:51:44 leigh systemd-networkd[25120]: tailscale0: link pending udev initialization...
[...lots of lines omitted...]
Nov 26 09:51:44 leigh systemd-networkd[25120]: tailscale0: link_check_ready(): link is in pending state.
```
5. The interface will never turn `unmanaged` again, until I run `udevadm trigger --verbose --settle --action add /sys/class/net/tailscale0`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Debug output from systemd-networkd as it starts: https://gist.githubusercontent.com/antifuchs/7be51b608982403eb2f26d06cf1cf7b0/raw/9e631026305ef5dad3f4a15b2f6dc9514dfcbe72/systemd-networkd-tailscale-failure.log
```

**Comment by yuwata** [comment]
That should be a bug in nix. The symptom suggests that the udev database file under /run/udev/data/nIFINDEX for the interface is removed during applying the new nix configuration.
Not sure why the database is removed, but if it desired, then `udevadm trigger ...` is necessary to be invoked, as you already found.
So, I guess, nix accidentally removes the file, or mistakenly forgets to call udevadm. Please contact to nix's bug tracker.

**Comment by antifuchs** [comment]
Ah, yep, your analysis seems correct: During the rollout, the `systemd-udevd.service` unit gets stopped and started again at the new version, it seems. That in addition to incorrect ordering of units would definitely cause the DB to be unavailable for a nascent systemd-networkd.

Thanks for clarifying what happens there!
