### ISSUE TITLE
STDOUT_STREAMS_MAX 4096 Too many stdout streams, refusing connection - Why are we hardcoding system limits like it's 1981? 

### ISSUE THREAD

**Issue by jorhett** [systemd/systemd#35390]
### systemd version the issue has been seen with

main branch today

### Used distribution

Every

### Linux kernel version used

Every

### CPU architectures issue was seen on

None

### Component

systemd-journald

### Expected behaviour you didn't see

Ability to scope a system's resources based on the usage

### Unexpected behaviour you saw

I'm shocked to find that in 2020s we are implementing hardcoded limits in system utilities. I remember getting rid of hardcoded limits like these in Version 7 of Unix, long before SysV, BSD, or Linux existed. Why are we repeating the mistakes from decades ago?  https://github.com/systemd/systemd/blob/723069188dc6147125de4a0769a8d35d9bae6edb/src/journal/journald-stream.c#L43

I'm working now in a high-performance cluster with terabytes of RAM and hundreds of cores, but seeing many process logs get refused.  24k in just the past few hours:

```shell
$ sudo journalctl |grep 'Too many stdout streams, refusing connection' | wc -l
24291
```

I've investigated and confirmed that every one of these processes are legitimate. This node I pulled this value from hasn't exceeded 30% ram usage or 30% cpu usage in this timeframe. It could be doing a lot more work. Why is the number of streams hardcoded here ?

### Steps to reproduce the problem

Use a beefy system and give it enough work to do.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# journalctl |grep 'Too many stdout streams'
Nov 12 11:56:01 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:56:01 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:56:01 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:56:01 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:57:14 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:57:14 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:57:14 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
Nov 12 11:57:14 foo.example.com systemd-journald[2654]: Too many stdout streams, refusing connection.
```

**Comment by jorhett** [comment]
In general I think the approach systemd has taken of putting every user session in a separate slice and routing outputs through journald has been overall good. But assuming that yesterday's limits on the number of "reasonable" outputs is something that should be statically compiled into the journal seems very shortsighted.

**Comment by septatrix** [comment]
> Why are we repeating the mistakes from decades ago?

To [quote Lennart (from a PR where he raise some other limits)](https://github.com/systemd/systemd/pull/34815#issue-2596667621):

> Limits should be enforced, but not in a way real setups collide with them.

These limits exist to prevent runaway scenarios and DOS/resource exhaustion through bugs in user programs. However, if you are consistently hitting them it might be reasonable to increase those limits.

**Comment by poettering** [comment]
Precisely, we put limits on everything, as safety net. If there are realistic installations that run into the hardcoded limits we should substantially bump them. Hence, happy to raise this to 64K or so.

**Comment by yuwata** [comment]
-> #35430.

**Comment by jorhett** [comment]
I am in no way saying there should be no limits. In fact I would suggest that 4k is a reasonable default. But let it be dynamically changed, not hardcoded. This is where sysctl came from, after all 😁

**Comment by poettering** [comment]
Sorry, but I disagree. This is a safety limit only for run-away clients. If people run into this limit with valid scenarios then it should be bumped for everyone, unconditionally. It's hence not about resource management (where user-controllable knobs are appropriate in my PoV) but about a safety net for buggy software (where a hardcode knob is appropriate in my PoV).

**Comment by jorhett** [comment]
You still run into situations where a "runaway" on a desktop-class machine is lost in the noise of one of these beasts.  There isn't a single right value for both machines. All you are doing is pushing this down the road 5 more years really.
