### ISSUE TITLE
init process leaks memory from `systemctl show ...`

### ISSUE THREAD

**Issue by rfuchs** [systemd/systemd#35394]
### systemd version the issue has been seen with

257-rc2

### Used distribution

Debian Trixie & Sid

### Linux kernel version used

6.11.9

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

init process memory usage remains roughly constant

### Unexpected behaviour you saw

memory usage of init process grows ad infinitum (seen up to 27 GB)

### Steps to reproduce the problem

Service needs to be stopped, disabled, and have `SystemCallLog` configured.

* Install simple service, say `redis-server`
* `systemctl stop redis-server.service`
* `systemctl disable redis-server.service`
* `systemctl edit redis-server.service`
* Add `[Service]` `SystemCallLog=~@system-service seccomp`
* Repeat `systemctl show redis-server.service` several times

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Before:

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1  37816 26412 ?        Ss   Nov19   0:31 /sbin/init

After ~10000 invocations:

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.6 118612 106668 ?       Ss   Nov19   1:01 /sbin/init
```

**Comment by dtardon** [comment]
Hopefully fixed by https://github.com/systemd/systemd/pull/35397.

**Comment by rfuchs** [comment]
Seems to fix it, thank you
