### ISSUE TITLE
systemd-cryptsetup: not getting passphrase prompt after entering invalid FIDO2 PIN

### ISSUE THREAD

**Issue by farblos** [systemd/systemd#35393]
### systemd version the issue has been seen with

257~rc2-3

### Used distribution

Debian testing

### Linux kernel version used

6.11.9-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

I'm experiencing issues on Debian testing on Linux x86-64 since the latest upgrade of

**systemd packages 256.7-3 -> 257~rc2-3**

Unfortunately, there also was an update of

**dracut packages 103-2 -> 105-2**

at the same time, but I think the cuplrit is really `systemd-cryptsetup` here.

I have my root partition on an LVM which is protected by a FIDO2 security device and a fallback passphrase, like this:

    [~]$ sudo systemd-cryptenroll /dev/nvme0n1p3
    SLOT TYPE
       0 password
       1 fido2

With systemd 256.7-3, I had the following procedure to reach the fallback passphrase prompt:

    Please enter LUKS2 token PIN: <enter incorrect PIN here>
    Please enter security token PIN: <enter incorrect PIN here>
    Please enter passphrase for for disk ...: <enter fallback passphrase here>

and that would decrypt the LVM and continue booting.

### Unexpected behaviour you saw

With systemd 257~rc2-3, it looks like this instead:

    Please enter LUKS2 token PIN: <enter incorrect PIN here>
    [FAILED] Failed to start systemd-cryptsetup@nvme0n1p3_crypt.service - Cryptography Setup for nvme0n1p3_crypt
    [DEPEND] Dependency failed for cryptsetup.target - Local Encrypted Volumes.

Then dracut times out and enters resuce mode.

### Steps to reproduce the problem

See above.

**Comment by bluca** [comment]
There was a crash that was fixed in rc3, try again after upgrading the packages from unstable

**Comment by farblos** [comment]
Thanks.  Tried with rc3, which is better, but not completely OK.  Now I get:

```
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter security token PIN: <enter incorrect PIN here>
[FAILED] Failed to start systemd-cryptsetup@nvme0n1p3_crypt.service - Cryptography Setup for nvme0n1p3_crypt
[DEPEND] Dependency failed for cryptsetup.target - Local Encrypted Volumes.
```

Still no passphrase prompt.  Instructions welcome on how to further test here, but preferredly not in early boot, where I have little experience... Should this be reproducible with some encrypted loop-device during "normal" runtime?

**Comment by yuwata** [comment]
Could you try to boot systemd.log_level=debug and provide debugging logs of `systemd-cryptsetup@nvme0n1p3_crypt.service` and/or friends?

**Comment by farblos** [comment]
Hang on, maybe my 2nd test scenario (with rc3) was different from the 1st one (with rc2).

So currently I'm still on rc3, and with the FIDO2 key **unplugged** I get the usual behavior:

```
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter security token PIN: <enter incorrect PIN here>
Please enter passphrase for disk ...: <enter correct fallback passphrase here>
# system continues booting ...
```

However with the FIDO2 key **plugged** I get:

```
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter LUKS2 token PIN: <enter incorrect PIN here>
Please enter security token PIN: <enter incorrect PIN here>
[FAILED] Failed to start systemd-cryptsetup@nvme0n1p3_crypt.service - Cryptography Setup for nvme0n1p3_crypt
[DEPEND] Dependency failed for cryptsetup.target - Local Encrypted Volumes.
```

So this might be not a crash, but intendeded behavior.  If so, please consider this issue fixed with rc3.

Thanks.

**Comment by yuwata** [comment]
Are there any interesting logs in journal?

**Comment by keszybz** [comment]
I used the following test:
```console
truncate -s 100M /var/tmp/test.img
cryptsetup luksFormat --force-password /var/tmp/test.img
sudo build/systemd-cryptenroll --fido2-device=/dev/… /var/tmp/test.img
sudo SYSTEMD_LOG_LEVEL=debug SYSTEMD_LOG_COLOR=1 SYSTEMD_LOG_LOCATION=1 SYSTEMD_CRYPTSETUP_USE_TOKEN_MODULE=1 build/systemd-cryptsetup attach TEST /var/tmp/test.img none token-timeout=5
```

As reported in #35443, `token-timeout` seems ineffective. But afaict, it never worked or I'm misunderstanding what it's supposed to do.

As far as the scenario described in this bug, I get the password question as expected. (I let the fido2 device prompt time out. My device doesn't have `clientPin`.)

> So I think what I described [in my previous comment](https://github.com/systemd/systemd/issues/35393#issuecomment-2509726249) w.r.t. plugged and unplugged devices makes sense and everything is as it should be now.

Yeah. I think this is really fixed. If not, feel free to reopen.
