### ISSUE TITLE
kdbus breaks avahi-client service browser

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#354]
Booting a system with kdbus enabled breaks avahi-client service browser. Even the example code from avahi upstream repository ([client-browse-services.c](http://git.0pointer.net/avahi.git/plain/examples/client-browse-services.c)) does not find any services. The callback functions are not called, no idea what goes wrong.

**Comment by dvdhrm** [comment]
I suspect this is the bus-proxyd+policy that fails here. I don't have any mdns services on my network, any simple way to reproduce this?

**Comment by eworm-de** [comment]
Download and compile the example code. Even if no services are available it should print:

```
(Browser) CACHE_EXHAUSTED
(Browser) ALL_FOR_NOW
```

Just tested on a system disconnected from network.
But browse_callback() is never called.

**Comment by kaysievers** [comment]
This is on kdbus:

$ avahi-discover 
Browsing domain 'local' on -1.-1 ...
Browsing for services of type '_http._tcp' in domain 'local' on 4.0 ...
Browsing for services of type '_JB2XiOSApp._tcp' in domain 'local' on 4.0 ...
Browsing for services of type '_raop._tcp' in domain 'local' on 4.0 ...
Browsing for services of type '_spotify-connect._tcp' in domain 'local' on 4.0 ...
Found service 'GALACTICA' of type '_http._tcp' in domain 'local' on 4.0.
Found service 'iOSApp_A5DFA4' of type '_JB2XiOSApp._tcp' in domain 'local' on 4.0.
Found service '00A0DEA5DFA4@GALACTICA' of type '_raop._tcp' in domain 'local' on 4.0.
Found service 'eDMP32MB_A5DFA4' of type '_spotify-connect._tcp' in domain 'local' on 4.0.

**Comment by grawity** [comment]
Isn't this the same unicast-signal issue as in #308?

**Comment by eworm-de** [comment]
But avahi-discover is python, no?

**Comment by dvdhrm** [comment]
@grawity I'd assume that avahi installs matches just fine. If not, it needs to be fixed. What exactly are you referring to?

@eworm-de Why does it matter whether it is python or not? If you run "avahi-discover", it doesn't show anything?

**Comment by eworm-de** [comment]
avahi-discover shows at least some services, though it throws exceptions:

```
Browsing for services of type '_udisks-ssh._tcp' in domain 'local' on 3.0 ...
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/avahi-discover", line 170, in new_service_type
    b.connect_to_signal('ItemNew', self.new_service)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 544, in connect_to_signal
    dbus_interface, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 369, in connect_to_signal
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 157, in add_signal_receiver
    watch = self.watch_name_owner(bus_name, callback)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 373, in watch_name_owner
    return NameOwnerWatch(self, bus_name, callback)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 80, in __init__
    arg0=bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 160, in add_signal_receiver
    self.add_match_string(str(match))
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 398, in add_match_string
    BUS_DAEMON_IFACE, 'AddMatch', 's', (rule,))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: System.Error.EMFILE: Too many open files
```

The example C code using avahi-client library does not show anything at all.

**Comment by eworm-de** [comment]
Looks like missing match in libavahi-client is the culprit... This fixes it for me (as my application is happy with ServiceBrowser):

```
--- a/avahi-client/client.c
+++ b/avahi-client/client.c
@@ -541,6 +541,16 @@ AvahiClient *avahi_client_new(const AvahiPoll *poll_api, AvahiClientFlags flags,
     if (dbus_error_is_set(&error))
         goto fail;

+    dbus_bus_add_match(
+        client->bus,
+        "type='signal', "
+        "interface='" AVAHI_DBUS_INTERFACE_SERVICE_BROWSER "', "
+        "sender='" AVAHI_DBUS_NAME "'",
+        &error);
+
+    if (dbus_error_is_set(&error))
+        goto fail;
+
     dbus_bus_add_match (
         client->bus,
         "type='signal', "
```

Though this is not complete, we need resolver, etc...
Anybody with better knowlegs of avahi? Anybody with commit access to avahi upstream repository?

**Comment by zonque** [comment]
Yes, @poettering has.

**Comment by eworm-de** [comment]
I sent a mail upstream...
Let's see whether or not sleeping beauty wakes... :-P

http://lists.freedesktop.org/archives/avahi/2015-June/002366.html

As neither systemd nor kdbus is to blame... Closing.

**Comment by dvdhrm** [comment]
Just as a heads-up: We now support directed-signals on kdbus with bus-proxy just fine. So avahi should work with kdbus-git and systemd-git even without patching avahi.

kdbus patches should hit -next in 1 or 2 days.
