### ISSUE TITLE
timedatectl does not update /etc/timezone on Debian 12

### ISSUE THREAD

**Issue by GitGraf** [systemd/systemd#35413]
### systemd version the issue has been seen with

252 (252.31-1~deb12u1)

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-25-amd64

### CPU architectures issue was seen on

None

### Component

timedatectl

### Expected behaviour you didn't see

Changing the timezone with e.g. `timedatectl set-timezone Etc/UTC` should update `/etc/timezone`, but that file remains unchanged. This is not the case with Debian 11, where changing the timezone with timedatectl **does** update `/etc/timezone`.

### Unexpected behaviour you saw

`/etc/timezone` remains unchanged after setting the timezone with `timedatectl`.

### Steps to reproduce the problem

On a Debian 12 system, verify the current timezone:
```bash
$ timedatectl
             Local time: Fri 2024-11-29 12:57:29 UTC
         Universal time: Fri 2024-11-29 12:57:29 UTC
               RTC time: Fri 2024-11-29 12:57:29
              Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
            NTP service: n/a
        RTC in local TZ: no

```
Change the timezone to a different one using timedatectl:
```
$ timedatectl set-timezone Europe/Berlin
``` 
Verify that the timezone has changed:
```
$ timedatectl
             Local time: Fri 2024-11-29 13:56:27 CET
         Universal time: Fri 2024-11-29 12:56:27 UTC
               RTC time: Fri 2024-11-29 12:56:27
              Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
            NTP service: n/a
        RTC in local TZ: no

```
Check the contents of /etc/timezone:
```
~ $ cat /etc/timezone
Etc/UTC
```

**Comment by bluca** [comment]
/etc/timezone is a deprecated debianism, timedatectl is most definitely not supposed to touch it. Use /etc/localtime instead.

**Comment by arvidjaar** [comment]
This was dropped eleven years ago. You are late to the party.
