### ISSUE TITLE
Regression: when dbus is not around, it's no more possible to restart or shutdown the system

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#35416]
### systemd version the issue has been seen with

257-rc3

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

The sequence:

```
systemctl rescue
systemctl poweroff
```

used to shutdown the system in rescue mode until v256

### Unexpected behaviour you saw

With v257-rc3:

```
$ systemctl rescue
$ systemctl poweroff
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → CLOSED
Failed to connect to system scope bus via local transport: No such file or directory
```

### Steps to reproduce the problem

See above.

**Comment by yuwata** [comment]
Regression caused by https://github.com/systemd/systemd/pull/34686 .

**Comment by yuwata** [comment]
Regression caused by 804874d26ac73e0af07c4c5d7165c95372f03f6d (and its follow-up f2f9c199d100e0393c1909b00df4800b3ec0ca5c) .

**Comment by yuwata** [comment]
-> #35418.
