### ISSUE TITLE
systemctl requires forced merging of directories, otherwise an error will be displayed

### ISSUE THREAD

**Issue by kindusmithkindu** [systemd/systemd#35438]
### systemd version the issue has been seen with

257~rc3-1

### Used distribution

debian13

### Linux kernel version used

kernel 6.6.63

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

systemctl status cannot be displayed normally, the Tainted field of the systemctl status command displays Tainted: unmerged-bin
![2024-12-02 09-48-13屏幕截图](https://github.com/user-attachments/assets/eafe2c37-b41d-4128-bffc-7b2587a9f7b9)

### Unexpected behaviour you saw

systemctl status forces the /bin and /sbin directories to be merged, otherwise stains will be displayed, Please do not force merge directories, The advantages of splitting /bin and /usr/bin, and /sbin and /usr/sbin outweigh the disadvantages, it based on the following two points

1. First, root and ordinary users will not be able to use commands in each other's directories, which will greatly increase their security

2. If /usr is partitioned separately instead of a unified / partition, ordinary users can also use commands in /usr/bin, which increases convenience

Of course, these advantages have become impossible now with the merging of directories

### Steps to reproduce the problem

use systemctl status command

**Comment by poettering** [comment]
We are not forcing anything, we are very gently pushing distros to stop separating bin and sbin because it's an obsolete concept.

> First, root and ordinary users will not be able to use commands in each other's directories, which will greatly increase their security

That's not how security engineering work. By excluding a binary in $PATH you just make it harder to use, you can still invoke it via an absolute path.

> If /usr is partitioned separately instead of a unified / partition, ordinary users can also use commands in /usr/bin, which increases convenience

I cannot parse this.

note that We are not supporting split /usr/ systems anymore since a while, because it's entirely pointless and an even more obsolete concept.

Anyway, these are not actionable requests. Sorry.

**Comment by sir-ragna** [comment]
> We are not forcing anything, we are very gently pushing distros to stop separating bin and sbin because it's an obsolete concept.

Distributions should be able to disagree with this standpoint. If Debian doesn't want to do this, Debian should have a way to disable this warning. 

This warning serves no purpose for end-users. There should be a configuration option that the distro can set to disable it.

I don't need a pointless warning in my system to remind me that the Systemd maintainers and the Debian maintainers hold a different opinion on how the Debian project should run their project.

**Comment by poettering** [comment]
@sir-ragna downstreams an patch it out, if they like. convince debian of doing so, if you like.

**Comment by cweiske** [comment]
Related Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085370
