### ISSUE TITLE
sdb's zero padding of initrd causes measurements to fail

### ISSUE THREAD

**Issue by jirislaby** [systemd/systemd#35439]
https://github.com/systemd/systemd/blob/3f3b4959e2cb9bca1e1ed527a0692c9a8b6a18ea/src/boot/boot.c#L2498-L2504

appears to cause this downstream issue:
https://bugzilla.suse.com/show_bug.cgi?id=1233752

It looked like related to the 6.11..6.12 kernel update. But now, that appears like a pure coincidence. Instead, the initrd size likely (and its modulo-ness by 4) matters…

From https://lore.kernel.org/all/7773891b-b699-4f1d-b9ba-220c649aee9d@kernel.org/:
> Note that ovmf logged:
> Called TcgDxeHashLogExtendEvent 0 58683000 1B1E78C 5FE63C00 5E3492AA
> Data 28 B5 2F FD ... E1 29 FE 0
> 
> But initrd on disk is 1B1E78B long, not 1B1E78C. So the excessive 0 at the end above brews the mismatch. See:
>   https://bugzilla.suse.com/show_bug.cgi?id=1233752#c14
> "By adding the 0 byte I can replicate the measured digest."
> 
> So there is something aligning the initrd. kernel's libstub just uses and passes load_file2's size down to TcgDxeHashLogExtendEvent, AIUI. So it'd be sdb, ovmf or something. BTW how are sizes stored in/fetched from vfat? But well, fs/fat/ received no significant changes either. 

In particular, from https://bugzilla.suse.com/show_bug.cgi?id=1233752#c17:

> You're missing the fact that systemd-boot installs its own Load File2 protocol which the kernel then uses:
> 
> https://github.com/systemd/systemd/blob/3f3b4959e2cb9bca1e1ed527a0692c9a8b6a18ea/src/boot/initrd.c#L100-L105
> 
> This protocol currently zero pads the binary to a multiple of 4:
> 
> https://github.com/systemd/systemd/blob/3f3b4959e2cb9bca1e1ed527a0692c9a8b6a18ea/src/boot/boot.c#L2498-L2504
> 
> This was actually a measurement breaking change introduced into v257-rc1 by f8fa4222c9 ("boot: Make initrd_prepare() semantically equivalent to combine_initrds()") -- @DaanDeMeyer.

**Comment by keszybz** [comment]
@jirislaby I submitted an untested patch that I hope would fix your issue. PTAL. If you could test it, that'd great.

**Comment by bluca** [comment]
What about the UKI? Didn't @DaanDeMeyer mention that the same padding is done for the kernel? Is that padding measured?

**Comment by DaanDeMeyer** [comment]
> What about the UKI? Didn't @DaanDeMeyer mention that the same padding is done for the kernel? Is that padding measured?

It is, but it's been that way forever, so changing it now would break measurements again.

**Comment by bluca** [comment]
It's a bit dodgy that we do different things for different sections...

What about sd-measure? Are things doen coherently at least?
