### ISSUE TITLE
Remove ANSI color from filenames in bash autocomplete 

### ISSUE THREAD

**Issue by excited-bore** [systemd/systemd#35442]
### systemd version the issue has been seen with

systemd 256 (256.8-2-manjaro)

### Used distribution

Manjaro

### Linux kernel version used

linux 6.6.63-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

zsh or other shelltypes of autocompletion

### Unexpected behaviour you saw

`systemctl edit *TAB*`
![comp_ascii](https://github.com/user-attachments/assets/46ca1fc8-6d32-4d5f-a44e-f11131ff5c52)

How to fix:

in https://github.com/systemd/systemd/blob/main/shell-completion/bash/systemctl.in

```
__systemctl() {
    local mode=$1; shift 1
    SYSTEMD_COLORS=0 systemctl $mode --full --legend=no --no-pager --plain "$@" 2>/dev/null
}
```
![compe_systm](https://github.com/user-attachments/assets/285eaf27-5f50-42c1-a1bb-0415f8bbd79c)

Seems like a small misconfiguration.

**Comment by yuwata** [comment]
Please submit the proposed fix as a PR. Thank you.

**Comment by excited-bore** [comment]
There you go: https://github.com/systemd/systemd/pull/35444
