### ISSUE TITLE
Document service status codes

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#3545]
```
$ systemctl status sshd
...
Process: 6457 ExecStart=/usr/sbin/sshd $OPTIONS (code=exited, status=0/SUCCESS)
...
```

The `status=0/SUCCESS` part. There is a lot of possible status codes defined in `src/basic/exit-status.h`, but without explanation what any of those mean. Since they are presented to the user, they should be documented (in a separate section in systemd.service(5) for example).

**Comment by arvidjaar** [comment]
Status is whatever service process returned. It is outside of control and scope of systemd and cannot be documented here. By convention status 0 means success; everything else is at discretion of daemon author and can only be documented there (e.g. in sshd manual in this case).

**Comment by poettering** [comment]
@arvidjaar well, we do these translations of the number to a string in systemctl actually, and it's based on the LSB-defined exit code, plus our own. I figure we should document them somewhere, plus the fact that this is just decoration, but not necessarily right if the service program in question doesn't actually follow the LSB-defined exit codes...

**Comment by akostadinov** [comment]
Example:
```
# systemctl status systemd-rfkill
● systemd-rfkill.service - Load/Save RF Kill Switch Status
   Loaded: loaded (/usr/lib/systemd/system/systemd-rfkill.service; static; vendo
   Active: inactive (dead) since Tue 2017-07-18 13:26:30 EEST; 2h 16min ago
     Docs: man:systemd-rfkill.service(8)
  Process: 20108 ExecStart=/usr/lib/systemd/systemd-rfkill (code=exited, status=
 Main PID: 20108 (code=exited, status=0/SUCCESS)

Jul 18 13:26:25 koTak systemd[1]: Starting Load/Save RF Kill Switch Status...
Jul 18 13:26:25 koTak systemd[1]: Started Load/Save RF Kill Switch Status.
# echo $?
3
```

Exit status from `ExecStart` seems to be `0` but `systemctl status` returns `3`. How can this be explained?
