### ISSUE TITLE
Systemd CPUQuota is not working after sudo interactive login

### ISSUE THREAD

**Issue by Pleskan** [systemd/systemd#35452]
### systemd version the issue has been seen with

252.31

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-18

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Systemd cgroup's CPU quota works as documented.
No matter how user get logged in: sudo -i, ssh etc.

### Unexpected behaviour you saw

CPU Quota doesn't work if I switched to user using ` sudo -u -i `
It works only after ssh login as that user

### Steps to reproduce the problem
Looks like[ this](https://github.com/hestiacp/hestiacp/issues/4659) issue caused by the same bug as current one.

The problem is similar to [this](https://serverfault.com/questions/1161844/systemd-cpuquota-for-user-slice-not-working)  one, but there are 2 nuances.

 1. If I switch to user with `sudo -u testuser -i` then load CPU using stress utility, CPUQuota doesn't take effect.
 
 2. If I login via SSH as a `testuser`, run some intensive task and then it works as expected.

My CPUQuota config 

*/etc/systemd/system.control/user-1003.slice.d/50-CPUQuota.conf*

```
[Slice]
CPUQuota=33%
```
```
systemctl show -p DefaultCPUAccounting

DefaultCPUAccounting=yes
```

 Distribution: Debian 12 latest.
Ubuntu 22.04 also affected by this.

**Comment by gitzdnex** [comment]
As I know some change of privilege action does not move current process / or does not create new process in user cgroup which is controlled. Try to check where that new process ends in cgroup hierarchy / where is shell (eg. with `systemctl status`).

**Comment by Pleskan** [comment]
@gitzdnex 
Can you show detailed step-by-step example?
Could you replicate the issue?

**Comment by gitzdnex** [comment]
well `systemctl status` can show in which cgroup processes are. So for example if your process is running in 
`systemctl status user-1000.slice` or you can see whole cgroup tree and there find where your process is. If your process is there and cgroup has accessible its controllers (pids,cpu, memory etc) then it should work.

So for example `systemctl status user-1000.slice`
```
● user-1000.slice - User Slice of UID 1000
     Loaded: loaded
    Drop-In: /usr/lib/systemd/system/user-.slice.d
             └─10-defaults.conf
     Active: active since Wed 2024-12-04 06:03:08 CET; 3min 37s ago
       Docs: man:user@.service(5)
        CPU: 765ms
     CGroup: /user.slice/user-1000.slice
             ├─session-3.scope
             │ ├─673 su ubuntu
             │ ├─688 bash
             │ └─700 htop
             └─user@1000.service
               └─init.scope
                 ├─676 /usr/lib/systemd/systemd --user
                 └─677 "(sd-pam)"
```
You can see here, that there is htop running in that session. If your process is running in different cgroup, then you need to check that. Hopefully it is more understandable.

**Comment by Pleskan** [comment]
@gitzdnex Oke, I will test it in a while and report about the results.
Thanks!

**Comment by Pleskan** [comment]
Output of `systemctl status user-1005.slice`  logged in via SSH

**Comment by Pleskan** [comment]
Any clues on topic ?

**Comment by Pleskan** [comment]
Highly likely it's by[ design](https://github.com/hestiacp/hestiacp/issues/4659#issuecomment-2541454013)
:-(

**Comment by gitzdnex** [comment]
Well I am not sure what are you trying to do. If you will create normal service `CPUQuota=` normally works. If you want to have it by user session, you can also create user service which will be binded to systemd user instance and user will be able to start it. Btw root doing `su` should also normally start user session and then it should move processes into to that cgroup.

**Comment by Pleskan** [comment]
>If you want to have it by user session.

That's my goal.  So, it's possible to implement using user service, right?
The main point that confuses the reason assigned quotas don't work with sudo, but on the other hand they work with ssh.
Fortunately we have workaround for now, thanks!
