### ISSUE TITLE
"systemctl --user" usage together with "sudo"/"doas" should have a clearer failure message

### ISSUE THREAD

**Issue by gonX** [systemd/systemd#35467]
### Component

systemctl

### Is your feature request related to a problem? Please describe

I help with support on a userspace daemon. Users are provided with a user service file on install, but a not-insignificant amount of users ends up running the systemctl command with `doas`/`sudo`, e.g. `sudo systemctl --user start myservice`, and the error message provided does not help them directly.

The error message reads as such:
> ```
> $ sudo systemctl --user start myservice
> Failed to connect to user scope bus via local transport: No medium found
> ```

### Describe the solution you'd like

If `systemctl` is invocated with the `--user` flag _while_ also run with `doas` or `sudo` (or similar elevation executables), `systemctl` should warn the user that the command probably does not do what they expect.

If the user session is not found (ie. in cases where the error would have been shown before), the output could instead look like:

```
$ sudo systemctl --user
Failed to connect to user scope bus via local transport: No medium found
Note: systemctl --user is intended for use with user sessions, and does not need to be run as root.
```

If the user session _is_ found, such as `root` having an actual user session running, then the note should probably not be displayed.

### Describe alternatives you've considered

Straight up erroring the combination of `doas`/`sudo` and the `--user` flag, if use of `doas`/`sudo` can be detected reliably:
```
$ sudo systemctl --user
systemctl --user is intended for use with user sessions. Do not use 'sudo' or 'doas' together with 'systemctl --user'.
$
```

### The systemd version you checked that didn't have the feature you are asking for

256.9

**Comment by YHNdnzj** [comment]
This should be fixed by #34851 already. We have the logic of emitting a clear error when `$DBUS_SESSION_BUS_ADDRESS` and `$XDG_RUNTIME_DIR` are unset (which is the case when invoking systemctl --user with sudo), but there was a bug and the plain `strerror(ENOMEDIUM)` was reported.
