### ISSUE TITLE
Handle the quirky keymap change of HP Elitebook 2170p runnning coreboot

### ISSUE THREAD

**Issue by persmule** [systemd/systemd#35469]
### Component

systemd-hwdb

### Is your feature request related to a problem? Please describe

Recently [an issue report to coreboot](https://ticket.coreboot.org/issues/571) describes that HP Elitebook 2170p's keyboard scan codes under coreboot is different with those under oem firmware, regardless of the same set of EC firmware blobs are used. The scan code of backspace key of HP Elitebook 2170p under coreboot is 0x66, but https://github.com/systemd/systemd/commit/93b078c3dd40b10eed34a77d514b1db7493b17cf has `KEYBOARD_KEY_66=pickup_phone`  for general HP laptops, making the backspace key of the reporter's HP Elitebook 2170p running coreboot unusable.

I guess the EC (extended from keyboard controller) of 2170p have two mode for keyboard scan codes: default mode and oem mode. Its oem firmware may send come commands to EC to switch it to oem mode, while no command is sent on the current coreboot, so the EC remains in the default mode.

It seems that scan code switch is indeed "widespread among early Elitebooks", but the actual change on most models is very small. For example, the main difference is `KEYBOARD_KEY_df=sleep # Fn+F3` is only available under the oem firmware. Under coreboot Fn+F3 only generates scan code for F3.

The reporter also composed an https://ticket.coreboot.org/attachments/download/466/61-2170p-kb.hwdb containing all scan code of Fn-keys of HP Elitebook 2170p under coreboot, and adjusted to the default SMBIOS tables of coreboot for Elitebook 2170p. When put under `/etc/udev/hwdb.d/`, it proves to not only map the backspace key back , but alsp map most Fn-keys well, and it does not conflict with HP Elitebook 2170p under oem firmware.

### Describe the solution you'd like

The easiest solution may be to merge the hwdb piece composed by the reporter into the `60-keyboard.hwdb`, and choose a DMI string to match only HP Elitebook 2170p running coreboot, to avoid conflict with HP Elitebook 2170p running oem firmware.

### Describe alternatives you've considered

We coreboot developers could also find and implement the commands to switch scan code to "oem mode" by digging the oem firmware, but it would be hard and ineffective, as the hwdb piece composed by the reporter works quite well.

### The systemd version you checked that didn't have the feature you are asking for

257-rc1

**Comment by bluca** [comment]
> The easiest solution may be to merge the hwdb piece composed by the reporter into the 60-keyboard.hwdb, and choose a DMI string to match only HP Elitebook 2170p running coreboot, to avoid conflict with HP Elitebook 2170p running oem firmware.

Please submit this as a PR
