### ISSUE TITLE
cryptsetup does not handle TPM2_RC_PCR_CHANGED error from Esys_PolicyPCR

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#35490]
### systemd version the issue has been seen with

systemd 256.6+suse.8.g8a0ae4d90a

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.12.2-rc1-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

The system uses the TPM to open the root device successfully and without error messages.

### Unexpected behaviour you saw

There are some TPM related errors in the journal, but it successfully opens the `cr_root` device anyway:

```
Dec 04 11:34:11.434808 localhost systemd[1]: Starting Import TPM2 crendentials into the initrd...
Dec 04 11:34:11.441468 localhost systemd[1]: Starting Create System Files and Directories...
Dec 04 11:34:11.454809 localhost systemd[1]: Finished Import TPM2 crendentials into the initrd.
Dec 04 11:34:11.455365 localhost systemd[1]: Reached target Local Encrypted Volumes (Pre).
Dec 04 11:34:11.458452 localhost systemd[1]: Starting Cryptography Setup for cr_root...
Dec 04 11:34:11.476592 localhost systemd[1]: Finished Virtual Console Setup.
Dec 04 11:34:11.478059 localhost kernel: usb 1-1: new high-speed USB device number 2 using xhci_hcd
Dec 04 11:34:11.480676 localhost systemd-cryptsetup[584]: Encountered unknown /etc/crypttab option 'x-initrd.mount', ignoring.
Dec 04 11:34:11.481155 localhost systemd[1]: Finished Create System Files and Directories.
Dec 04 11:34:11.608056 localhost kernel: usb 1-1: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
Dec 04 11:34:11.608220 localhost kernel: usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=10
Dec 04 11:34:11.608332 localhost kernel: usb 1-1: Product: QEMU USB Tablet
Dec 04 11:34:11.608436 localhost kernel: usb 1-1: Manufacturer: QEMU
Dec 04 11:34:11.608537 localhost kernel: usb 1-1: SerialNumber: 28754-0000:00:06.0-1
Dec 04 11:34:11.628797 localhost kernel: usbcore: registered new interface driver usbhid
Dec 04 11:34:11.628816 localhost kernel: usbhid: USB HID core driver
Dec 04 11:34:11.654787 localhost kernel: input: QEMU QEMU USB Tablet as /devices/pci0000:00/0000:00:06.0/usb1/1-1/1-1:1.0/0003:0627:0001.0001/input/input4
Dec 04 11:34:11.654807 localhost kernel: hid-generic 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Mouse [QEMU QEMU USB Tablet] on usb-0000:00:06.0-1/input0
Dec 04 11:34:11.678937 localhost systemd-cryptsetup[584]: WARNING:esys:src/tss2-esys/api/Esys_PolicyPCR.c:288:Esys_PolicyPCR_Finish() Received TPM Error
Dec 04 11:34:11.678937 localhost systemd-cryptsetup[584]: ERROR:esys:src/tss2-esys/api/Esys_PolicyPCR.c:100:Esys_PolicyPCR() Esys Finish ErrorCode (0x00000128)
Dec 04 11:34:11.712635 localhost systemd-cryptsetup[584]: Failed to unseal secret using TPM2: State not recoverable
Dec 04 11:34:11.712676 localhost systemd-cryptsetup[584]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/07b5d866-7dd5-4f61-81c9-47c5a0392791.
Dec 04 11:34:12.411456 localhost kernel: Key type trusted registered
```

Looking at the error:

```
> tpm2_rc_decode 0x00000128
tpm:error(2.0): PCR have changed since checked
```

If `Esys_PolicyPCR` is called multiple times in a single session and some PCRs change value in between, the command will fail with `TPM_RC_PCR_CHANGED`. systemd silently handles this case for `Esys_Unseal`, but not `Esys_PolicyPCR`.

What I don't understand so far is:

1. For some reason the issue only appears with kernel 6.12 and never with 6.11
2. Even though unseal fails, cr_root is opened successfully. I guess there's another retry mechanism beyond the one for `Esys_Unseal` failures.

### Steps to reproduce the problem

openQA installs MicroOS with systemd-boot + FDE, then does a few reboots: https://openqa.opensuse.org/tests/4686360

I suspect it's reproducible by using cryptenroll with tpm2 token on a system with kernel 6.12 and rebooting a couple of times.

**Comment by jirislaby** [comment]
> For some reason the issue only appears with kernel 6.12 

In particular, any 6.12 .. 6.12.3.

> and never with 6.11

And any pre-6.12 up to 6.11.10 (ie. with all relevant 6.12 TPM changes backported).

**Comment by Vogtinator** [comment]
To reproduce the issue manually:

```
dd if=/dev/zero of=luks2 bs=1M count=128
cryptsetup luksFormat --type=luks2 luks2
losetup -f luks2
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+1+2+3+4+5+6 /dev/loop0
```

Then run

```
while systemd-cryptsetup attach cr_luks2 /dev/loop0 none tpm2-device=auto; do echo "Worked"; systemd-cryptsetup detach cr_luks2; done
```

in parallel to

```
tpm2_pcrextend 10:sha256=0000000000000000000000000000000000000000000000000000000000000000
```

Depending on the timing, it'll result in one of three errors:

a) Warning about PCR_CHANGED (0x128) is printed
b) ^ + "Failed to unseal secret using TPM2: State not recoverable"
c) ^ + asks for a passphrase instead of unlocking

**Comment by Vogtinator** [comment]
Another semi-related issue: I'm wondering whether `rc == TPM2_RC_PCR_CHANGED` is correct. FWICT the values of `TSS2_RC` are actually internal and it's necessary to use `Tss2_RC_DecodeInfo` to get to the TPM2 error code. I can't find clear documentation about this.
