### ISSUE TITLE
journalctl --output=json --setup-keys does not output json

### ISSUE THREAD

**Issue by betelgeuse** [systemd/systemd#35503]
### systemd version the issue has been seen with

v257-rc3)

### CPU architectures issue was seen on

None

### Component

journalctl

### Expected behaviour you didn't see

Output json

### Unexpected behaviour you saw

Plain text output

### Steps to reproduce the problem

```
# journalctl --output=json --setup-keys --force
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Generating seed...
Generating key pair...
Generating sealing key...

New keys have been generated for host <host_id>.

The secret sealing key has been written to the following local file.
This key file is automatically updated when the sealing key is advanced.
It should not be used on multiple hosts.

	/var/log/journal/<journal id>/fss

The sealing key is automatically changed every 15min.

Please write down the following secret verification key. It should be stored
in a safe location and should not be saved locally on disk.

	<secret_id>
```

The relevant source code here shows that output is not respected:

https://github.com/systemd/systemd/blob/59ea5e4c445f7ec80ef1800318843524cdc29a40/src/journal/journalctl-authenticate.c#L169
```

**Comment by yuwata** [comment]
-> #35507.
