### ISSUE TITLE
sd-varlink has "The systemd Project" for org.varlink.service.GetInfo hardcoded

### ISSUE THREAD

**Issue by thkukuk** [systemd/systemd#35508]
### systemd version the issue has been seen with

257 ~git20241206

### Used distribution

openSUSE MicroOS/Tumbleweed

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

`varlinkctl info` for a non-systemd application should print something about this application and project and not claim that it is a systemd project.

### Unexpected behaviour you saw

`varlinkctl info /run/rebootmgr/rebootmgrd.socket` prints:
```
  Vendor: The systemd Project
  Product: systemd (rebootmgrd)
  Version: 257~rc3 (257~devel+git20241203.67bf853b1)
      URL: https://systemd.io/
Interfaces: io.systemd
           org.openSUSE.rebootmgr
           org.varlink.service
```

Looks like `generic_method_get_info()` got forgotten to adjust when sd-varlink was made a public interface.

**Comment by poettering** [comment]
oh, indeed, that's kinda broken, we should make that overridable.
