### ISSUE TITLE
RFE: when fstab-generator is run in initrd, accept fstab entry for /sysroot as equivalent to root= kernel cmdline param

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [systemd/systemd#3551]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

230
### distribution

arch linux
### proposal

1) currently `add_sysroot_mount()`:
https://github.com/systemd/systemd/blob/master/src/fstab-generator/fstab-generator.c#L489
will only be invoked when kernel `root=` parameter is present, 
which is not a required kernel parameter when using `systemd` as `/init`:
http://unix.stackexchange.com/questions/289672/kernel-init-without-root-parameter

2) we propose to allow extra configuration sources for the `root=`, 
for example, use special entry `/sysroot` in the `/etc/fstab`
https://github.com/random-archer/mkinitcpio-systemd-tool/blob/master/fstab

```
#  <file system>        <dir>      <type>    <option>         <dump> <pass>
 /dev/mapper/root     /sysroot    ext4      defaults,ro        0     1
```

**Comment by arvidjaar** [comment]
This line will need to be added by initrd generator based on real root information, at which point initrd generator can just as well add proper mount unit.

**Comment by Andrei-Pozolotin** [comment]
1) those are 2 different configuration paths: 
- "initrd generator" deals with image archive
- "boot loader generator" deals with boot loader configuration

2) "real root" can be discovered dynamically by `/init`, 
in which case neither `root=` nor `/etc/fstab` entry will work.
so it sounds like we need some generalized `sysroot-generator` :-)

so the point is: the way `fstab-generator` handles `root=` now is no so good

**Comment by arvidjaar** [comment]
> real root" can be discovered dynamically by /init

Please explain how it can be done.

**Comment by poettering** [comment]
hmm, this is already supported, no? just list the root as / in your host fstab...

**Comment by Andrei-Pozolotin** [comment]
listing `/` in `fstab` does not work for me, and from `fstab-generator.c` it seems it can not work.

**Comment by Andrei-Pozolotin** [comment]
should clarify: issue arises from using `fstab-generator` early, in `initramfs`, before `cryptsetup`

**Comment by haraldh** [comment]
/etc/fstab in the initrd should be honored by:
https://github.com/systemd/systemd/blob/master/src/fstab-generator/fstab-generator.c#L696

So, if the "/sysroot" entry is dynamically added in the boot process, "systemctl daemon-reload" is needed. And of course initrd-root-fs.target has to be part of the initrd.

Of course "/" in the fstab does not work..

**Comment by Andrei-Pozolotin** [comment]
right. the task at hand is rather convoluted: provide an early `initramfs` utility which would "call back home to obtain cryptsetup context". nonetheless:

1) we are trying to follow your "thou shall not write a generator" commandment
https://www.freedesktop.org/software/systemd/man/systemd.generator.html
and reuse available features instead

2) for our purposes `fstab-generator` is "almost there",
and we would like to rely on current `/sysroot` convention
and related `systemd` services, targets, paths

3) essentially we are asking to provide extra configuration 
interface for `fstab-generator.c/add_sysroot_mount()` 
in addition to kernel `root=` parameter, for example:
a) by using magic `/sysroot` entry in `/etc/fstab`
b) by providing more flexible command line to `fstab-generator.c`
c) may be there is even better/simpler and more general approach

**Comment by Andrei-Pozolotin** [comment]
as of v238 the problem is reduced to the following:

https://github.com/systemd/systemd/blob/master/src/fstab-generator/fstab-generator.c
* `add_sysroot_mount` is invoked only when `root=` stanza is present in `/proc/cmdline`
* instead, it must also be invoked when `/sysroot` entry is present in `/etc/fstab`

see for example
* https://github.com/random-archer/mkinitcpio-systemd-tool/issues/10
* https://github.com/random-archer/mkinitcpio-systemd-tool/issues/12

the work around is to inject explicit unit dependency
`sysroot.mount -> initrd-root-fs.target`
for example:

file:
```
initrd-sysroot-mount.service
```

content:
```
[Unit]
ConditionPathExists=/etc/initrd-release
DefaultDependencies=no
After=sysroot.mount
BindsTo=sysroot.mount

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/bin/true

[Install]
WantedBy=initrd-root-fs.target

[X-SystemdTool]
InitrdService=enable
```
