### ISSUE TITLE
The name attribute of udev cannot rename non-network devices

### ISSUE THREAD

**Issue by kayle7c** [systemd/systemd#35581]
### Component

systemd-udevd

### Is your feature request related to a problem? Please describe

I want to implement persistent naming for block devices, but I see that UDEV does not support renaming non network devices and can only use symlinks. I want to know why name cannot be used to name non network devices. And what should I do if I want to name non network devices with 'name'

### Describe the solution you'd like

What should I do if I want to make changes in the source code to enable UDEV to support naming non network devices with 'name'

### Describe alternatives you've considered

I tried to find the part of creating device nodes in the source code and apply the name attribute in the udev rule here, but unfortunately I couldn't find the relevant code

**Comment by kayle7c** [comment]
For example, I would like to use: SUBSYSTEM=="block",ACTION=="add",ATTRS{idVendor}=="048d",ATTRS{idProduct}=="1234",NAME="sdk"， But obviously UDEV cannot support the name assignment of block devices. I understand that this operation was possible in earlier versions of UDEV. What is the reason why UDEV does not support this operation

**Comment by poettering** [comment]
The kernel generally doesn't support renaming devices, except for network interfaces. Hence this is a restriction of the kernel, not of udev.

**Comment by kayle7c** [comment]
> 内核通常不支持重命名设备，但网络接口除外。因此，这是 kernel 的限制，而不是 udev 的限制。
If I want to change the naming of block devices under/dev, for example: dev/sdb->dev/sdk， Can it be achieved through UDEV source code

**Comment by poettering** [comment]
> If I want to change the naming of block devices under/dev, for example: dev/sdb->dev/sdk， Can it be achieved through UDEV source code

No, you cannot. The kernel does not support renaming block devices.

You can apply symlinks to block devices however, which everyone does, via `SYMLINK+="…"`

**Comment by kayle7c** [comment]
> > If I want to change the naming of block devices under/dev, for example: dev/sdb->dev/sdk， Can it be achieved through UDEV source code
> 
> No, you cannot. The kernel does not support renaming block devices.
> 
> You can apply symlinks to block devices however, which everyone does, via `SYMLINK+="…"`

The problem may not lie in the kernel layer, as I have tried replacing the current UDEV with a lower version and it has been proven that renaming is feasible

**Comment by arvidjaar** [comment]
> The kernel does not support renaming block devices.

Who says about kernel?
```
tw:/dev # ll sda
brw-rw---- 1 root disk 8, 0 Dec 12 20:50 sda
tw:/dev # mv sda sdk
tw:/dev # ll sdk
brw-rw---- 1 root disk 8, 0 Dec 12 20:50 sdk
tw:/dev # findmnt .
TARGET SOURCE   FSTYPE   OPTIONS
/dev   devtmpfs devtmpfs rw,nosuid,size=4096k,nr_inodes=248003,mode=755,inode64
tw:/dev # 
```

**Comment by poettering** [comment]
Dude. That renames the device node inode, not the device. The device (as in /sys/class/block/*) wont change its name.

**Comment by kayle7c** [comment]
> Who says about kern

I have tried to do this, but the problem with it is that the “sdk” inode does not disappear when I unplug my device

**Comment by kayle7c** [comment]
> Dude. That renames the device node inode, not the device. The device (as in /sys/class/block/*) wont change its name.
Sorry, my previous expression was incorrect. Is the inode under /dev created by udev? If that's the case, then I can achieve“/dev/sdb ->/dev/sdk” by modifying udev source code, right?

**Comment by poettering** [comment]
> Sorry, my previous expression was incorrect. Is the inode under /dev created by udev? If that's the case, then I can achieve“/dev/sdb ->/dev/sdk” by modifying udev source code, right?

So first of all: no, udev does not create device node inodes. The kernel does that on its own in devtmpfs. udev just fixes up permissions, adds symlinks, maintains metadata.

And renaming device node inodes yourself is not going to help you, because the this just renames the inodes, nothing else. The device's kernel name (i.e. the subdir in /sys/class/block/) won't change name via that, it's not going to change name in /proc/diskstats and all those files and so on.

Hence again, renaming block devices is not supported on Linux, as I mentioned before.

Use symlinks, that allows man aliases, is managed by udev and generally well supported. (But of course, don't invade the kernel's namespace, that will just result in desaster, i.e. never install a symlink /dev/sdf because this will conflict with the kernel naming a device /dev/sdf).

**Comment by kayle7c** [comment]
> > Sorry, my previous expression was incorrect. Is the inode under /dev created by udev? If that's the case, then I can achieve“/dev/sdb ->/dev/sdk” by modifying udev source code, right?
> 
> So first of all: no, udev does not create device node inodes. The kernel does that on its own in devtmpfs. udev just fixes up permissions, adds symlinks, maintains metadata.
> 
> And renaming device node inodes yourself is not going to help you, because the this just renames the inodes, nothing else. The device's kernel name (i.e. the subdir in /sys/class/block/) won't change name via that, it's not going to change name in /proc/diskstats and all those files and so on.
> 
> Hence again, renaming block devices is not supported on Linux, as I mentioned before.
> 
> Use symlinks, that allows man aliases, is managed by udev and generally well supported. (But of course, don't invade the kernel's namespace, that will just result in desaster, i.e. never install a symlink /dev/sdf because this will conflict with the kernel naming a device /dev/sdf).

Okay, now I understand what's going on here. Thank you for patiently answering, I really appreciate it
