### ISSUE TITLE
systemd-coredump@.service has a hidden dep on systemd-tmpfiles, which causes deadlock at boot if systemd-tmpfiles crashes

### ISSUE THREAD

**Issue by hrgstephen** [systemd/systemd#35582]
### systemd version the issue has been seen with

systemd-257-rc3

### Linux kernel version used

linux-6.11.3

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

System entered and can login

### Unexpected behaviour you saw

System start hungs:
A start job is running for Create Volatile Files and Directories (10h 10min 10s / no limit))

### Steps to reproduce the problem

1. let systemd-tmpfiles abort when system start.
2. Systemd hungs showing: A start job is running for Create Volatile Files and Directories (10h 10min 10s / no limit))

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Dec 04 17:39:06 localhost.localdomain systemd[1]: systemd-coredump.socket: Incoming traffic
Dec 04 17:39:06 localhost.localdomain systemd[1j: var-tmp.mount: Failed to load configuration: No such file or directory
Dec 04 17:39:06
    6 localhost.localdomain systemd[1j: var.mount: Failed to load configuration: No such file or directory
Dec 04 17:39:06
    5 localhost.localdomain systemd[1]: var-lib.mount: Failed to load configuration: No such file or directory
Dec 04 17:39:06
    5 localhost.localdomain systemd[1j: var-lib-systemd.mount: Failed to load configuration: No such file or directory
Dec 04 17:39:06
     localhost.localdomain systemd[1j: var-lib-systemd-coredump.mount: Failed to load configuration: No such file or directory
Dec 04 17:39:06
    5 localhost.localdomain systemd[1]: systemd-coredump@1-3855-0.service: Trying to enqueue job systemd-coredump@1-3855-0.service/start/replace
Dec 04 17:39:06
    5 localhost.localdomain systemd[1]: systemd-coredump@1-3855-0.service: Installed new job systemd-coredump@1-3855-0.service/start as 659
Dec 04 17:39:06
     localhost.localdomain systemd[1]: systemd-coredump@1-3855-0.service: Enqueued job systemd-coredump@1-3855-0.service/start as 659
    6 localhost.localdomain systemd[1j: var-tmp.mount: collecting.
Dec 04 17:39:06
Dec 04 17:39:06
    5 localhost.localdomain systemd[1]: var.mount: Collecting.
Dec 04 17:39:06
    5 localhost.localdomain systemd[1]: var-lib.mount: Collecting.
Dec 04 17:39:06
    6 localhost.localdomain systemd[1j: var-lib-systemd.mount: Collecting.
Dec 04 17:39:06 localhost.localdomain systemd[1]: var-lib-systemd-coredump.mount: Collecting.
Dec 04 17:39:06
    6 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesk
Dec 04 17:39:06 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesk
```

**Comment by poettering** [comment]
Can you provide more comprehensive logs?

What makes you think there was an ABBA problem? systemd-tmpfiles don't actually take any locks in a blocking fashion.

From the log excerpt I see no relationship to tmpfiles stuff at all? what makes you think your issue has anything to do  with that?

**Comment by hrgstephen** [comment]
I have digged down this issue, it's because:
1. systemd-tmpfiles abort for whatever reason (there are a lot assert in systemd-tmpfiles, which assert failed will result in abort and coredump in Linux: https://linux.die.net/man/3/assert).
2. kernel sees the abort signal, and try to core dump this program (systemd-tmpfiles).
3. At this time, /proc/sys/kernel/core_pattern has been set to pipe to systemd-coredump ("|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e").
4. Kernel invokes privileged systemd-coredump with stdin (fd 0) set to pipe from kernel.
5. Privileged systemd-coredump sent message and stdin fd (fd 0) to systemd using Unix socket: /run/systemd/coredump.
6. Systemd (pid 1) receives this message, and queued service systemd-coredump (unprivileged systemd-coredump).
7. However, unprivileged systemd-coredump is never got spawn, because it has an impilict dependency on systemd-tmpfiles (See https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Implicit%20Dependencies): Similarly, units with PrivateTmp= enabled automatically get mount unit dependencies for all mounts required to access /tmp/ and /var/tmp/. They will also gain an automatic After= dependency on [systemd-tmpfiles-setup.service(8)](https://www.freedesktop.org/software/systemd/man/latest/systemd-tmpfiles-setup.service.html#)
service file of systemd-coredump:
[Service]
...
PrivateTmp=yes
...
8. Unprivileged systemd-coredump can not get running, thus kernel core dump of systemd-tmpfiles hungs, since the other end of pipe is not consumed and pipe is full:
```
crash> bt -l 511
PID: 511      TASK: ffff94a5009a4300  CPU: 1    COMMAND: "systemd-tmpfile"
 #0 [ffffab2d40703978] __schedule at ffffffff99aa1a5d
 #1 [ffffab2d407039d0] schedule at ffffffff99aa1ef6
 #2 [ffffab2d407039e8] pipe_write at ffffffff99370e5a
 #3 [ffffab2d40703a68] __kernel_write at ffffffff99364ff7
 #4 [ffffab2d40703af0] dump_emit at ffffffff993f049a
 #5 [ffffab2d40703b18] dump_user_range at ffffffff993f1328
 #6 [ffffab2d40703b48] elf_core_dump at ffffffff993eab60
 #7 [ffffab2d40703d00] do_coredump at ffffffff993f0df9
 #8 [ffffab2d40703e08] get_signal at ffffffff990fa6ac
 #9 [ffffab2d40703e88] arch_do_signal at ffffffff990214fa
#10 [ffffab2d40703f10] exit_to_user_mode_loop at ffffffff9917be4d
#11 [ffffab2d40703f30] exit_to_user_mode_prepare at ffffffff9917bf0e
#12 [ffffab2d40703f40] syscall_exit_to_user_mode at ffffffff99a99bf2
#13 [ffffab2d40703f50] entry_SYSCALL_64_after_hwframe at ffffffff99c00099
```
9. Thus and ABBA deadlock: 
- systemd-tmpfiles can not end (finish core dump by kernel) and wait for kernel coredump pipe systemd-coredump to consume or close this pipe;
- Unprivileged systemd-coredump can not get running because it waits for systemd-tmpfiles to finish running.
10. Thus systemd-tmpfiles never finish running and system boot hungs, other services depent of systemd-tmpfiles never get inovked.

**Comment by hrgstephen** [comment]
If I comment out "PrivateTmp=yes" in systemd-coredump service description file, then system boot succesfully, when system-tmpfiles abort on boot.

As far as I can see, there may be these potential solutions:
1. do not set sysctl /proc/sys/kernel/core_pattern to pipe to systemd-coredump until systemd-tmpfiles finishes.
2. or: remove PrivateTmp=yes from systemd-coredump or change to other implmentation that did not depend on systemd-tmpfiles.
3. or any better solution?

**Comment by hrgstephen** [comment]
BTW: systemd-coredump added PrivateTmp=yes in this commit: https://github.com/systemd/systemd/commit/924453c22599cc246746a0233b2f52a27ade0819
seems not a strong dependcy of PrivateTmp, though remove PrivateTmp=yes maybe not the best soultion.

**Comment by hrgstephen** [comment]
I am not sure if "PrivateTmp=disconnected" implies dependency of systemd-tmpfiles. @poettering

**Comment by poettering** [comment]
Hm, yeah, PrivateTmp=disconnected sounds like the way to go indeed.
