### ISSUE TITLE
RFE: fix compiling errors: 'CURLOPT_XFERINFODATA' and 'CURLOPT_XFERINFOFUNCTION' undeclared

### ISSUE THREAD

**Issue by huzhifeng** [systemd/systemd#3559]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd-219

I just tested with systemd-219, but it should be available for all versions

[systemd-219-19.fc22.src.rpm](https://kojipkgs.fedoraproject.org//packages/systemd/219/19.fc22/src/systemd-219-19.fc22.src.rpm) is based on [systemd-219.tar.xz](wget https://www.freedesktop.org/software/systemd/systemd-219.tar.xz)
### Used distribution

> [CentOS-7-aarch64](http://mirror.centos.org/altarch/7/isos/aarch64/CentOS-7-aarch64-Everything.iso)
### How to reproduce the issue

I observed below compilling errors related to pull-job.c and curl

> ```
> ../src/import/import-job.c: In function 'import_job_begin':
> gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -include ./config.h -DPKGSYSCONFDIR=\"/etc/systemd\" -DSYSTEM_CONFIG_UNIT_PATH=\"/etc/systemd/system\" -DSYSTEM_DATA_UNIT_PATH=\"/usr/lib/systemd/system\" -DSYSTEM_SYSVIc
> ../src/import/import-job.c:717:39: error: 'CURLOPT_XFERINFOFUNCTION' undeclared (first use in this function)
>          if (curl_easy_setopt(j->curl, CURLOPT_XFERINFOFUNCTION, import_job_progress_callback) != CURLE_OK)
>                                        ^
> ../src/import/import-job.c:717:39: note: each undeclared identifier is reported only once for each function it appears in
> gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -include ./config.h -DPKGSYSCONFDIR=\"/etc/systemd\" -DSYSTEM_CONFIG_UNIT_PATH=\"/etc/systemd/system\" -DSYSTEM_DATA_UNIT_PATH=\"/usr/lib/systemd/system\" -DSYSTEM_SYSVIc
> ../src/import/import-job.c:720:39: error: 'CURLOPT_XFERINFODATA' undeclared (first use in this function)
>          if (curl_easy_setopt(j->curl, CURLOPT_XFERINFODATA, j) != CURLE_OK)
>                                        ^
> make[2]: *** [src/import/systemd_pull-import-job.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [all-recursive] Error 1
> make: *** [all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.Ut0GZb (%build)
> 
> RPM build errors:
>   Bad exit status from /var/tmp/rpm-tmp.Ut0GZb (%build)
> ```

https://github.com/systemd/systemd/blob/master/src/import/pull-job.c#L602
https://github.com/systemd/systemd/blob/master/src/import/pull-job.c#L605
### Proposed solution

'CURLOPT_XFERINFOFUNCTION' and 'CURLOPT_XFERINFODATA' were introduced since curl 7.32.0, versions older than 7.32.0 will cause compiling error as above
[CURLOPT_XFERINFOFUNCTION explained](https://curl.haxx.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html)
[CURLOPT_XFERINFODATA explained](https://curl.haxx.se/libcurl/c/CURLOPT_XFERINFODATA.html)

There are two solutions

Solutions A:
Refer to offical example
[cURL / libcurl / API / Examples / progressfunc.c](https://curl.haxx.se/libcurl/c/progressfunc.html)

```
+#if LIBCURL_VERSION_NUM >= 0x072000
         if (curl_easy_setopt(j->curl, CURLOPT_XFERINFOFUNCTION, import_job_progress_callback) != CURLE_OK)
                 return -EIO;

         if (curl_easy_setopt(j->curl, CURLOPT_XFERINFODATA, j) != CURLE_OK)
                 return -EIO;
+#endif
```

Solutions B:
Refer to [Lua-cURLv2 patch: ifdefs to avoid compilation breakage when using old cURL](https://github.com/Lua-cURL/Lua-cURLv2/commit/1de410ef43c0cadc8b9d8ac4b9b6261d45f2af58)

```
+#ifdef CURLOPT_XFERINFOFUNCTION
         if (curl_easy_setopt(j->curl, CURLOPT_XFERINFOFUNCTION, import_job_progress_callback) != CURLE_OK)
                 return -EIO;
+#endif

+#ifdef CURLOPT_XFERINFODATA
         if (curl_easy_setopt(j->curl, CURLOPT_XFERINFODATA, j) != CURLE_OK)
                 return -EIO;
+#endif
```

**Comment by evverx** [comment]
See f0b7fc2d89c17d31

> configure.ac: bump curl dependency to 7.32.0
> We are using CURLOPT_XFERINFOFUNCTION which was added in 7.32.0.

**Comment by keszybz** [comment]
It seems that curl 7.32 is quite old. I have 7.47 on Fedora 24.

Since this is only used for informative output, it'd be reasonable to relax the dependency. I'd be happy to merge a pull request which adds the ifdefs (I think your solution B is nicer), but I don't think we're going to work on this ourselves.

**Comment by poettering** [comment]
This has been fixed already. Please do not report bugs against such old systemd versions, we only track issues in the two most recent upstream releases of systemd here.
