### ISSUE TITLE
90-loaderentry-fallback.install contains bashisms

### ISSUE THREAD

**Issue by sandboiii** [systemd/systemd#35596]
### systemd version the issue has been seen with

256-257

### Used distribution

Arch Linux

### Linux kernel version used

6.12.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

kernel-install

### Unexpected behaviour you saw

Running `reinstall-kernels` command I get the following errors:
```shell
/usr/lib/kernel/install.d/90-loaderentry-fallback.install: 32: [[: not found
/usr/lib/kernel/install.d/90-loaderentry-fallback.install: 65: [[: not found
```

Turns out `90-loaderentry-fallback.install` execution shell specified as `!/bin/sh`, but the script itself contains commands which are bashisms (i.e. specific only for bash). These are the double square brackets on the line 32 and 65:
```
[[ -f /etc/kernel-install-for-dracut.conf ]] && source /etc/kernel-install-for-dracut.conf
```
```
[[ ${NO_DRACUT_FALLBACK} == "true" ]] && exit 0
```

There are two possible solutions to solve this problem:
1. Change the script's execution shell to `!/bin/bash`
2. Rewrite these commands to be compatible with other shells

I also provided the output of the command 
```
checkbashisms /usr/lib/kernel/install.d/90-loaderentry-fallback.install
``` 
in the additional logs

### Steps to reproduce the problem

- Set default shell to `dash` (you can install `dashbinsh` from AUR on Arch Linux)
- Run `reinstall-kernels`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
possible bashism in /usr/lib/kernel/install.d/90-loaderentry-fallback.install line 32 (should be '.', not 'source'):
[[ -f /etc/kernel-install-for-dracut.conf ]] && source /etc/kernel-install-for-dracut.conf
possible bashism in /usr/lib/kernel/install.d/90-loaderentry-fallback.install line 32 (alternative test command ([[ foo ]] should be [ foo ])):
[[ -f /etc/kernel-install-for-dracut.conf ]] && source /etc/kernel-install-for-dracut.conf
possible bashism in /usr/lib/kernel/install.d/90-loaderentry-fallback.install line 65 (alternative test command ([[ foo ]] should be [ foo ])):
[[ ${NO_DRACUT_FALLBACK} == "true" ]] && exit 0
possible bashism in /usr/lib/kernel/install.d/90-loaderentry-fallback.install line 65 (should be 'b = a'):
[[ ${NO_DRACUT_FALLBACK} == "true" ]] && exit 0
```

**Comment by yuwata** [comment]
The file is not provided by systemd. Closing.

**Comment by sandboiii** [comment]
Sorry, my bad, you are right. It is the issue in `kernell-install-for-dracut`: 
https://gitlab.com/dalto.8/kernel-install-for-dracut/-/issues/4
