### ISSUE TITLE
systemd services broken after update

### ISSUE THREAD

**Issue by IAmHugh001** [systemd/systemd#35600]
### systemd version the issue has been seen with

257-1

### Used distribution

Arch

### Linux kernel version used

6.12.4-arch1-1

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

I expected after doing my updates and received the systemd updates and rebooting for Sonarr, Radarr, Prowlarr, and Flaresolverr to work as usual.

### Unexpected behaviour you saw

After the reboot for the update Sonarr, Radarr, Prowlarr, and Flaresolverr would not load their systemd services. Was presented with can't load page trying to launch Sonarr, Radarr, and Prowlarr. I did sudo systemctrl start sonarr radarr prowlarr flaresolverr and the apps still would not load. I ended up launching Timeshift and rolling the system back.

### Steps to reproduce the problem

Launch Konsole, enter topgrade, finish the updates, reboot.

**Comment by YHNdnzj** [comment]
Sorry, but this bug report doesn't come with any meaningful information. Please provide the exact errors emitted and relevant log, otherwise there's nothing actionable from our side.

**Comment by CummingCowGirl** [comment]
I wouldn't even begin to know what to add  since you can't just run any of the programs from konsol to get any output. Short of going ahead and doing the updates again and posting the Sonarr log if one is generated after reboot I honestly have no ideas.

**Comment by CummingCowGirl** [comment]
There were updates for Sonarr, Radarr, and Prowlarr today. I did those and then did the updates I rolled back yesterday and all looks good now.
