### ISSUE TITLE
Add ability to set unit specific hostname

### ISSUE THREAD

**Issue by geertj** [systemd/systemd#35623]
### Component

systemd

### Is your feature request related to a problem? Please describe

My team at AWS wants to use systemd to run multiple instances of a service, where each service requires a different host name. The instances runs as an unprivileged user using `DynamicUser=yes`. We are not using user namespaces as the instances need access to the full range of file system UIDs/GIDs.

### Describe the solution you'd like

We would like to have a setting named something like `Hostname=<hostname>`. When enabled, this setting creates a new UTS namespaces and sets the hostname to the provided argument. The setting is independent from `ProtectHostname`, but using either option will result in a new UTS namespace being created.

### Describe alternatives you've considered

As an alternative, we thought of setting the hostname as part of `ExecStart`. However, this requires UID 0 inside a new user namespace, which we don't want.

`ExecStart=unshare --map-user=root --uts bash -c "hostname foo; /usr/sbin/daemon"`

### The systemd version you checked that didn't have the feature you are asking for

257

**Comment by yuwata** [comment]
Draft PR -> #35626.
