### ISSUE TITLE
[systemd-resolve] dnssec: problem with specific subdomains

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#3562]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 230 
### Used distribution

> Arch Linux

Hello,
I have enabled dnssec in `/etc/systemd-resolved`. According to the changelog for systemd 230 dnssec is enabled on default with --allow-downgrade. Seems like this downgrading does not work for specific domains with subdomains. 

I have this issue with the following domains:

```
services.addons.mozilla.org
addons.mozilla.org
images-na.ssl-images-amazon.com
mail.google.com
```

When I try to resolve it manually I get the following:

```
% systemd-resolve images-na.ssl-images-amazon.com
images-na.ssl-images-amazon.com: resolve call failed: DNSSEC validation failed: incompatible-server
% systemd-resolve mozilla.org
mozilla.org: 63.245.215.20

-- Information acquired via protocol DNS in 478.9ms.
-- Data is authenticated: yes
% systemd-resolve addons.mozilla.org
addons.mozilla.org: resolve call failed: DNSSEC validation failed: incompatible-server
```

Normally I should get for addons.mozilla.org something similiar like this:

```
% systemd-resolve addons.mozilla.org          
addons.mozilla.org: 52.24.217.21
                    54.148.104.15
                    54.149.70.43

-- Information acquired via protocol DNS in 277.1ms.
-- Data is authenticated: no
```

**Comment by poettering** [comment]
hmm, so all these domains resolve fine here. What is the precise contents of your /etc/systemd/resolved.conf? Did you set DNSSEC=yes or DNSSEC=allow-downgrade there? The former is the "strict" mode where DNSSEC lookups will rather fail than permit downgrading. The latter is the "permissive" mode, where the lookusp will be downgraded.

The build-time option simply picks the default value for this setting. hence explicitly setting DNSSEC=yes in resolved.conf means the build-time option won't have any effect.

**Comment by shibumi** [comment]
Ah ok! Seems like I was confused a bit. I have set `DNSSEC=yes` in my `/etc/systemd/resolved.conf` because I thought I just have `yes` and `no` there. So yes with downgrade-mode and no without DNSSEC at all. Works fine now!
