### ISSUE TITLE
Unable to use `systemctl edit` to create templated, runtime, user unit

### ISSUE THREAD

**Issue by septatrix** [systemd/systemd#35632]
### systemd version the issue has been seen with

systemd-255.15-1.fc40.x86_64

### Used distribution

Fedora 40

### Linux kernel version used

6.11.11-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

Creating a templated user unit under /run with `systemctl edit` should work the same way it does for non-templated units

### Unexpected behaviour you saw

The command fails with exit code 1

### Steps to reproduce the problem

`systemctl edit --runtime --user --force --full handler@.service`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Cannot stat /proc/1/root: Permission denied
Failed to check if we're running in chroot, assuming not: Permission denied
Successfully loaded SELinux database in 2.300ms, size on heap is 362K.
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/user/1000/systemd/private...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnitFileState cookie=1 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=org.freedesktop.DBus.Error.FileNotFound error-message=No such file or directory
Failed to get UnitFileState for 'handler@.service': No such file or directory
Bus n/a: changing state RUNNING → CLOSED
```

**Comment by yuwata** [comment]
-> #35639

**Comment by yuwata** [comment]
duplicate of #32922.
