### ISSUE TITLE
Unwanted leading '\' displayed in prompt of systemd-nspawn inside run0 session

### ISSUE THREAD

**Issue by solsticedhiver** [systemd/systemd#35631]
### systemd version the issue has been seen with

257

### Used distribution

Archlinux

### Linux kernel version used

linux-6.1.120-1-lts61

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn, systemd-run

### Expected behaviour you didn't see

The prompt is correctly displayed in the container (i.e. without leading '\')

### Unexpected behaviour you saw

The prompt is displayed with a leading '\' (with no color)

### Steps to reproduce the problem

Launch a run0 session (authenticate), and then launch a systemd-nspawn container with a prompt containing '\[' as first character

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
\root@thehost:~# echo $PS1
\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
\root@thehost:~#
```

**Comment by yuwata** [comment]
-> #35640
