### ISSUE TITLE
sysupdate: Add conditions in `systemd-sysupdate.service` unit file

### ISSUE THREAD

**Issue by MoltenArmor** [systemd/systemd#35679]
### Component

systemd-sysupdate

### Is your feature request related to a problem? Please describe

I have a Debian without any sysupdate transfer definitions, and there is no `ConditionDirectoryNotEmpty=` in `systemd-sysupdate.service`, which results in `Error: code: 2 (No such file or directory)`.

### Describe the solution you'd like

I think it would be better if we add these conditions, just like `systemd-sysext.service` and `systemd-confext.service`.

```
ConditionDirectoryNotEmpty=|/etc/sysupdate.d
......
```

### The systemd version you checked that didn't have the feature you are asking for

257

**Comment by poettering** [comment]
Uh? the service is not enabled by default. Why would you enable it if have you have no definitions for itß

**Comment by MoltenArmor** [comment]
> Uh? the service is not enabled by default. Why would you enable it if have you have no definitions for itß

Well, I think that's because Debian has all units preset to be enabled by default.. So you can say that's a Debian-specific problem.

Of course we can fix this problem by just writing a preset configuration...... But I think adding these conditions might make the service more robust.

If you think it's better not to modify after evaluation, feel free to close my issue.

**Comment by poettering** [comment]
> Well, I think that's because Debian has all units preset to be enabled by default. So you can say that's a Debian-specific problem.

uh? does debian remove the preset file we ship from upstream? we ship one in presets/90-systemd.preset, and it lists many of our daemons, but certainly no systemd-sysupdate for a very good reason...

> Of course we can fix this problem by just writing a preset configuration...... But I think adding these conditions might make the service more robust.

dunno, it just hides bugs/misconfiguration.

**Comment by poettering** [comment]
anyway, let's close this, please contact debian for help on this, they shouldn't enable it by default
