### ISSUE TITLE
systemd-analyze timestamp with negative values

### ISSUE THREAD

**Issue by catiznado** [systemd/systemd#35688]
### systemd version the issue has been seen with

256.9-1

### Used distribution

Manjaro Linux

### Linux kernel version used

6.11.11-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-analyze

### Expected behaviour you didn't see

```
systemd-analyze timestamp "-3h"
  Original form: -3h
Normalized form: Thu 2024-12-19 13:51:31 -03
       (in UTC): Thu 2024-12-19 16:51:31 UTC
   UNIX seconds: @1734627091.381910
       From now: 3h 0min ago
```

### Unexpected behaviour you saw

```
systemd-analyze: invalid option -- '3'
```

### Steps to reproduce the problem

`systemd-analyze timestamp "-3h"`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
If you need more information, please let me know.
```

**Comment by septatrix** [comment]
You can use `systemd-analyze timestamp -- -3h`. The quoting is consumed by the shell so `"-3h"` and `-3h` are the same to sd-analyze. Use the double dash to signal it that everything which follows shall not be interpreted as a flag

**Comment by yuwata** [comment]
This is a kind of limitation of shell, and yeah, use `-- -3h` or so. Closing.

**Comment by catiznado** [comment]
Thanks!

**Comment by poettering** [comment]
The "--" thing is not specific to systemd-analyze, it's part of glibc's getopt() logic, and replciated by most command line parsers. Hence, this works not just here but pretty much everywhere else. For example if you want to remove two files called "f" and "-x" you can do "rm -- -f x" which is quite different from "rm -f x"...
