### ISSUE TITLE
sd-varlink: add sd_varlink_server_listen_name()

### ISSUE THREAD

**Issue by thkukuk** [systemd/systemd#35697]
### Component

other

### Is your feature request related to a problem? Please describe

I wrote a deamon which is listening to two different varlink sockets (one only accessible for root, one for all).

I activate the daemon with socket units, which define different `FileDescriptorName`.

To make use of this feature I need to clone the `sd_varlink_server_listen_auto()` function and add a new parameter to exchange the streq "varlink" if case. Which means I always need to manual sync with libsystemd changes.

### Describe the solution you'd like

It would be nice if we would have a `sd_varlink_server_listen_name()` function which takes the sd_varlink_server struct and the name of the fd as argument.
`sd_varlink_server_listen_auto` could then call this function with "sd_varlink_server_name(s, "varlink").

I could make a PR if this would be accepted.

### The systemd version you checked that didn't have the feature you are asking for

257

**Comment by poettering** [comment]
make sense.
