### ISSUE TITLE
needs to be reverted,  hwdb: Add quirk for Logitech MX Keys for Mac #35271

### ISSUE THREAD

**Issue by dkebler** [systemd/systemd#35691]
### systemd version the issue has been seen with

256.9

### Used distribution

archlinux

### Linux kernel version used

6.12.4-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

US `~ key had had been remaped to <>

### Steps to reproduce the problem

upgrade to latest  version of systemd and use a mxkeys keyboard with the defaults for English US.   

#35271 
this PR was the problem.  It solved the requester's problem but it created a big headache for me that took hours to track down.  systemd has a way to create custom keyboard mappings using `/etc/udev/hwdb.d`  so there is never a reason to include one off custom mappings within the systemd package.  Please remove this PR. 

the requester could have put this in his `/etc/udev/hwdb.d` folder.
```
# Logitech MX Keys for Mac
# evdev:input:b0003v046Dp4092*
# KEYBOARD_KEY_70035=102nd                               # '<' key
# KEYBOARD_KEY_70064=grave                               # '^' key
```

for anyone finding this issue for now I had to do this until this removed. 
```
# Logitech MX Keys for Mac
# this fixes https://github.com/systemd/systemd/pull/35271
# https://forum.manjaro.org/t/single-key-keyboard-mapping-issue-after-upgrade/172128/18
# sudo systemd-hwdb update, then reboot.
evdev:input:b0003v046Dp4092*
 KEYBOARD_KEY_70035=grave
 KEYBOARD_KEY_70064=102nd
```

I can imagine that there are hundreds of US linux users who are going to hate this PR. :)
Did you know they make different versions of the same keyboard for US and Europe?

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
udevadm info /dev/input/event5
P: /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.3/1-4.3.1/1-4.3.1:1.2/0003:046D:C52B.0003/0003:046D:4092.0004/input/input15/event5
M: event5
R: 5
U: input
D: c 13:69
N: input/event5
L: 0
S: input/by-path/pci-0000:00:14.0-usbv2-0:4.3.1:1.2-event-mouse
S: input/by-id/usb-Logitech_USB_Receiver-if02-event-mouse
S: input/by-path/pci-0000:00:14.0-usb-0:4.3.1:1.2-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.3/1-4.3.1/1-4.3.1:1.2/0003:046D:C52B.0003/0003:046D:4092.0004/input/input15/event5
E: DEVNAME=/dev/input/event5
E: MAJOR=13
E: MINOR=69
E: SUBSYSTEM=input
E: USEC_INITIALIZED=5607312
E: KEYBOARD_KEY_70035=102nd
E: KEYBOARD_KEY_70064=grave
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c52b
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=2411
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c52b
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=2411
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=02
E: ID_USB_DRIVER=usbhid
E: ID_PATH_WITH_USB_REVISION=pci-0000:00:14.0-usbv2-0:4.3.1:1.2
E: ID_PATH=pci-0000:00:14.0-usb-0:4.3.1:1.2
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_4_3_1_1_2
E: LIBINPUT_DEVICE_GROUP=3/46d/4092:usb-0000:00:14.0-4.3
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usbv2-0:4.3.1:1.2-event-mouse /dev/input/by-id/usb-Logitech_USB_Receiver-if02-event-mouse /dev/input/by-path/pci-0000:00:14.0>
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:
```

**Comment by poettering** [comment]
Oh, are you saying the kbd in question has the keys swapped both on the keycode they sent *and* on the label printed on them? if so then yes, the hwdb entry should go, switching that would be a personal preference, not a quirk.

**Comment by dkebler** [comment]
I do know they make the same keyboard for US and elsewhere and I have never seen the "elsewhere" so I can not say about the arrangement.

There might be a different id for different layouts but using this wildcard 

evdev:input:b0003v046Dp4092*

was a really bad idea as up to that point in the id there is no distinguishing.  So yea be VERY careful doing this kind of one off thing as manufacturers make variants of the same keyboard for different markets.  At least never use a wildcard.

so here is my keyboard.    I did your update and boom my `~ is spitting out <>.  even though <> is available right of M as shift , and shift .   

![2024-12-20_09-06-16](https://github.com/user-attachments/assets/18546d18-04ff-4ec5-80f2-36c949f27d8c)

**Comment by dkebler** [comment]
evtest shows this for my keyboard
`Input device ID: bus 0x3 vendor 0x46d product 0x4092 version 0x111`
I wonder what the variant layout keyboard ID is and whether the "version" is different?  If not then is no distinguishing between the two.

**Comment by yuwata** [comment]
What's the device name?

https://github.com/systemd/systemd/pull/35271#issue-2677366104
> ```
> Input driver version is 1.0.1
> Input device ID: bus 0x3 vendor 0x46d product 0x4092 version 0x111
> Input device name: "Logitech MX Keys Mac"
> ```

**Comment by yuwata** [comment]
So, it is a wireless keyboard, right? We had a similar issue previously, that a receiver is used for multiple models. I will revert the change.

**Comment by dkebler** [comment]
yes wireless, via logitech unifying dongle which supports many logitech devices.

**Comment by yuwata** [comment]
-> #35707.

**Comment by giswqs** [comment]
I just ran into the same issue. When the fix will be available through a system upgrade?

**Comment by dkebler** [comment]
@giswqs  see my initial post above I show what you can do right now to fix this for yourself.   No reason to wait for release through your distro.

**Comment by giswqs** [comment]
@dkebler The problem has been resolved after adding `/etc/udev/hwdb.d/60-keyboard.hwdb` with the following content and run `sudo systemd-hwdb update`, then reboot. Thank you. 
```
# sudo systemd-hwdb update, then reboot.
evdev:input:b0003v046Dp4092*
 KEYBOARD_KEY_70035=grave
 KEYBOARD_KEY_70064=102nd
```

**Comment by goldwern** [comment]
I created a /etc/udev/hwdb.d/90-mxkeys.hwdb like this:
```
# Logitech MX Keys S MAC Keyboard (Bluetooth)
evdev:name:MX KEYS S MAC Keyboard:*
 KEYBOARD_KEY_70035=102nd  # “< >” key → ISO slot 102 → < > | ¦
 KEYBOARD_KEY_70064=grave  # “^ °” key → KEY_GRAVE → ^ / ° under de(nodeadkeys)
```

Selecting the device by name works regardless of the bus id.
