### ISSUE TITLE
bind mount on mounted device is immediately unmounted by systemd

### ISSUE THREAD

**Issue by Snorch** [systemd/systemd#357]
One cannot bind-mount anything on loop device.

systemd-219-18.fc22.x86_64

How reproducible:

100%

Steps to Reproduce:
1. Setup loop device
   dd if=/dev/zero of=~/test.bin count=1000k
   losetup /dev/loop0 test.bin
   cfdisk /dev/loop0 # choose: new, primary, write, yes, quit
   mkfs.ext2 /dev/loop0
2. Mount it 
   mount /dev/loop0 /mnt/
3. Test
   cd /mnt; mkdir a b; touch a/test; mount --bind a b; ls -l b
   ls -l b

Actual results:
b is empty(almost immediately)

Expected results:
b contains file test

Ftrace of "mount --bind a b":

```
# tracer: function
#
#           TASK-PID    CPU#    TIMESTAMP  FUNCTION
#              | |       |          |         |
           mount-459018 [001] 87958.938386: sys_mount <-system_call_fastpath
           mount-459018 [001] 87958.938388: <stack trace>
 => ftrace_call
 => system_call_fastpath
          umount-459020 [000] 87958.941490: sys_umount <-system_call_fastpath
          umount-459020 [000] 87958.941491: <stack trace>
 => ftrace_call
 => system_call_fastpath
```

var/log/messages:
Jun 24 15:41:51 localhost umount: Executing: /bin/umount /mnt/b -n

Additional info:

I tried this patch atop of systemd-219-18.fc22.x86_64 and it fixes this problem:
http://pkgs.fedoraproject.org/cgit/systemd.git/tree/0001-Revert-core-mount-add-dependencies-to-dynamically-mo.patch?h=f22&id=9bbe0e92dc59d5a42258c729b105a7d9901eb35e

There are 2 patches intended to fix mount devices problem, but atop of systemd-219-18.fc22.x86_64 they don't fix problem for me:

mount: don't claim a device is gone from /proc/self/mountinfo before it is gone from _all_ lines
http://cgit.freedesktop.org/systemd/systemd/commit/?id=fcd8b26

mount: properly check for mounts currently in /proc/self/mountinfo
http://cgit.freedesktop.org/systemd/systemd/commit/?id=394763f6

I created also bug on fedora bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1235287

Links to this problem:
1. https://bugzilla.redhat.com/show_bug.cgi?id=1195761
2. https://bugs.gentoo.org/show_bug.cgi?id=541402
3. https://bugs.freedesktop.org/show_bug.cgi?id=89383
4. https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1444402

**Comment by poettering** [comment]
Fixed in v220 and newer. Please update. 

We don't track bugs in older and downstream packages upstream. Sorry!

**Comment by Snorch** [comment]
git describe  fcd8b266edf0df2b85079fcf7b099cd4028740e6 --contains
v220~58
git describe  394763f63c1941cafd9d3bf81e8151a2206474a7 --contains
v220~50

Those patches I tested and which don't solve my issue are in v220, and they were as far as I understand intended to fix this problem. Would you be so kind to say if there are some other patches in v220 connected to this problem?
