### ISSUE TITLE
add support in systemd-logind to ignore some input device

### ISSUE THREAD

**Issue by vvavrychuk** [systemd/systemd#35706]
### Component

systemd-logind

### Is your feature request related to a problem? Please describe

I allocate uinput input device and passthrough it to QEMU using virtio-input. I don't want this uinput device to affect my host system. But, we I send `KEY_POWER` to this uinput input device, then systemd-logind power offs my host system.

### Describe the solution you'd like

libinput has LIBINPUT_IGNORE_DEVICE udev property which I can use for Wayland to ignore specific device, see for details https://wayland.freedesktop.org/libinput/doc/latest/ignoring-devices.html

It would be great if systemd supports similiar property, such as `SYSTEMD_IGNORE_DEVICE`.

### Describe alternatives you've considered

I have achieved success by writting udev rule that resets `ID_INPUT_KEY` property, `61-uinput.rules`:
```
SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="my-name", ENV{ID_INPUT_KEY}="0"
```

But, this solution is udev execution order dependent. It has to be after `60-input-id.rules` to overwrite `ID_INPUT_KEY` assigned by `input_id` builtin and before `70-power-switch.rules` which assigns `power-switch` tag according to `ID_INPUT_KEY` property.

**Comment by yuwata** [comment]
I think it is better to use hwdb for such purpose. See 60-input-id.hwdb.

**Comment by vvavrychuk** [comment]
@yuwata I am not sure how hwdb can help. From what I see `60-input-id.hwdb` sets `ID_INPUT_KEY`, etc. based on some modalias (i.e. for specific devices). But, `input_id` assigns `ID_INPUT_KEY` if there is any `EV_KEY` event type supported by input.

I am not sure there is any other solution, since libinput/wayland already seems to be facing similiar problem and solved it by adding `LIBINPUT_IGNORE_DEVICE` property in udev with corresponding handling in libinput.

**Comment by yuwata** [comment]
Creating a custom .hwdb file for your keyboard model with `ID_INPUT_KEY=0` or `ID_INPUT_KEY=` (empty assignment), and call `systemd-hwdb update` and `udevadm trigger /dev/input/eventXX` should work, as udev calls `input_id` first, then load entries from hwdb. So, the setting in hwdb has a higher priority. See 60-input-id.rules .

**Comment by vvavrychuk** [comment]
Thank you!
