### ISSUE TITLE
systemd-localed returns old value from PropertiesChanged signal

### ISSUE THREAD

**Issue by chrisawi** [systemd/systemd#35717]
### systemd version the issue has been seen with

systemd-256.9-2.fc41.x86_64 and git main

### Used distribution

Fedora 41

### Linux kernel version used

6.12.5-200.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Setting the locale, e.g. via `localectl`, should emit a D-Bus PropertiesChanged signal containing the new value in `changed_properties`.

### Unexpected behaviour you saw

localed instead returns the old value, and it continues to return that same value for future calls until it's restarted (or it times out). Among other things, this is breaking the GNOME Settings Region panel in multi-user mode.

This is a regression that I've bisected to https://github.com/systemd/systemd/commit/018befcff6b51f8a50ca232e1984d34526037241

### Steps to reproduce the problem

* `gdbus monitor -y -d org.freedesktop.locale1`
* `localectl set-locale LC_TIME=fr_FR.UTF-8`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ sudo dbus-monitor --system 'path=/org/freedesktop/locale1'
signal time=1734809485.708661 sender=org.freedesktop.DBus -> destination=:1.4435 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.4435"
signal time=1734809485.708676 sender=org.freedesktop.DBus -> destination=:1.4435 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.4435"
method call time=1734809493.256189 sender=:1.4436 -> destination=org.freedesktop.locale1 serial=2 path=/org/freedesktop/locale1; interface=org.freedesktop.locale1; member=SetLocale
   array [
      string "LC_TIME=fr_FR.UTF-8"
   ]
   boolean true
method call time=1734809493.323125 sender=:1.101 -> destination=:1.4438 serial=87 path=/org/freedesktop/locale1; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.locale1"
method call time=1734809493.323663 sender=:1.125 -> destination=:1.4438 serial=332 path=/org/freedesktop/locale1; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.locale1"
signal time=1734809493.618171 sender=:1.4438 -> destination=(null destination) serial=8 path=/org/freedesktop/locale1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.freedesktop.locale1"
   array [
      dict entry(
         string "Locale"
         variant             array [
               string "LANG=en_US.UTF-8"
               string "LC_TIME=de_DE.UTF-8"
            ]
      )
   ]
   array [
   ]
```

**Comment by yuwata** [comment]
Thank you for the detailed report. Fix is waiting in #35775.
