### ISSUE TITLE
Recent HACKING.md update doesn't work on a freshly wiped system

### ISSUE THREAD

**Issue by avramd** [systemd/systemd#35741]
### systemd version the issue has been seen with

systemd 258 (258~devel-g88bfdcf)

### Used distribution

Debian Trixie (testing)

### Linux kernel version used

6.11.10-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Basic instructions provided should work when run on a freshly wiped build dr, in particular:
```
$ mkosi -f sandbox meson setup build
$ mkosi -f sandbox ninja -C build
$ mkosi -f sandbox build/systemctl --version
$ # mkosi -f genkey                       # Generate signing keys once. # doesn't get wiped
$ mkosi -f sandbox ninja -C build mkosi # (re-)build the OS image
```

The last step should not produce errors

### Unexpected behaviour you saw

```
$ mkosi -f sandbox ninja -C build mkosi # (re-)build the OS image
ninja: Entering directory `build'
ninja: error: unknown target 'mkosi'
```

### Steps to reproduce the problem

```
# checkout latest main (8567f1342)
$ mkosi -f sandbox meson setup --wipe build
$ mkosi -f sandbox meson setup build
$ mkosi -f sandbox ninja -C build
$ mkosi -f sandbox build/systemctl --version
$ mkosi -f sandbox ninja -C build mkosi
```

**Comment by DaanDeMeyer** [comment]
@avramd How did you install mkosi? More specifically, is it properly in your $PATH?

**Comment by avramd** [comment]
@DaanDeMeyer using the link in HACKING.md to the mksoi repo:

```
$ which mkosi
/usr/local/bin/mkosi
$ realpath `!!`
realpath `which mkosi`
/home/avram/dev/mkosi/bin/mkosi
```

**Comment by avramd** [comment]
My `mkosi` is as of Dec 14:
```
commit b39de4022086b805ebfe820120a8a9e5de0b4d62 (HEAD -> main, origin/main, origin/HEAD)
Author: mm <mm@sofa.local>
Date:   Sat Dec 14 22:42:31 2024 +0100

    man: Improve style of KernelModulesInitrd
```

**Comment by evverx** [comment]
I think `HACKING` should say
```sh
mkosi -f sandbox meson compile -C build mkosi
```
instead of
```sh
mkosi -f sandbox ninja -C build mkosi
```

**Comment by avramd** [comment]
I was just going to say exactly that, and that did work:
```
mkosi -f sandbox meson compile -C build mkosi
```
But I figured if there is a ninja version of that command it would be more consistent.

**Comment by avramd** [comment]
I'm happy to create a little PR if it helps, if someone can confirm that's the right fix, and there is no ninja equivalent that is more appropriate.

**Comment by evverx** [comment]
Personally I think it's the right documentation fix because it works and it's what the CI does (so it's likely to keep working). The ninja target is `.` as far as I can see.

**Comment by DaanDeMeyer** [comment]
@avramd mkosi has to be installed outside of `/usr` for this to work so please symlink it to ~/.local/bin and add that to $PATH.

**Comment by DaanDeMeyer** [comment]
https://github.com/systemd/systemd/pull/35742 to more clearly mention '~/.local/bin`

**Comment by avramd** [comment]
@DaanDeMeyer I'm still getting the same isssue. Do I need to redo the `--wipe`? LMK what I'm missing, here's my current relevant setup:
```
$ echo $PATH
/usr/sbin:/home/avram/.local/bin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
$ which mkosi
/home/avram/.local/bin/mkosi
$ realpath mkosi
/home/avram/dev/systemd/mkosi
$ ls -l ~/.local/bin/mkosi 
lrwxrwxrwx 1 avram avram 31 Dec 23 20:37 /home/avram/.local/bin/mkosi -> /home/avram/dev/mkosi/bin/mkosi
$ mkosi -f sandbox ninja -C build mkosi
ninja: Entering directory `build'
ninja: error: unknown target 'mkosi'
```

**Comment by avramd** [comment]
@DaanDeMeyer just in case, I tried it starting from scratch with `--wipe` and it came out the same. Also, may I ask why the `.` in front of `~/.local/bin`? Why do we want this to be hidden?

Thanks!

**Comment by NekkoDroid** [comment]
> Also, may I ask why the `.` in front of `~/.local/bin`? Why do we want this to be hidden?

That is just the "default" location for user local binaries. Since it's not something usually accessed directly (like `Documents` or `Pictures`) it was decided that putting it in a hidden directory makes the most sense.

https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/14

**Comment by avramd** [comment]
@evverx sorry to hijack this thread here, but wondering if you saw [this comment](https://github.com/systemd/systemd/pull/34888#issuecomment-2554127495) on the BOOTP PR. I've been in a bit of a holding pattern there waiting for your input.

**Comment by evverx** [comment]
@avramd I'll take a look next year probably. As far as I can remember your PR works with RFC-compliant servers (with the siaddr field) but it breaks the (non RFC-compliant) use case the original PR is supposed to address (with the server identifier option). I was hoping you could sort it out somehow and decide what to do in the meantime. Either it's off-topic here. I'll hide the two comments.

**Comment by DaanDeMeyer** [comment]
@avramd I don't know if `--wipe` is sufficient to clear the entire meson cache. Please remove the build directory manual and double check that the meson setup logs prints `Program mkosi found: YES`.

**Comment by evverx** [comment]
FWIW I tried to follow HACKING and can't get it to work either.
```
Program mkosi found: YES (/home/vagrant/.local/bin/mkosi)
```
With `meson compile` instead of `ninja` it builds the image but `mkosi boot` goes sideways with `repart` complaining about `/work/*` (though I can boot the image manually with `nspawn`)

**Comment by DaanDeMeyer** [comment]
> FWIW I tried to follow HACKING and can't get it to work either.
> ```
> Program mkosi found: YES (/home/vagrant/.local/bin/mkosi)
> ```
> With `meson compile` instead of `ninja` it builds the image but `mkosi boot` goes sideways with `repart` complaining about `/work/*` (though I can boot the image manually with `nspawn`)

This isn't useful for me to act on, please include a log so I can debug things.

**Comment by evverx** [comment]
I already destroyed the VM but I'll try to attach the logs next time.

Can you share the environment where
```sh
mkosi -f sandbox ninja -C build mkosi
```
works? It can be I'm holding it wrong.

**Comment by evverx** [comment]
Here's how `mkosi boot` fails:
```sh
...
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + /home/vagrant/systemd/build/systemd-nspawn --version
‣ + timedatectl show -p Timezone --value
‣ + openssl x509 -in /work/home/vagrant/systemd/mkosi.crt -pubkey -noout
‣ + ssh-keygen -f /dev/stdin -i -m PKCS8
‣ Acquiring lock on /home/vagrant/systemd/build/mkosi.output/image
‣ Acquired lock on /home/vagrant/systemd/build/mkosi.output/image
‣ + systemd-repart --image /work/home/vagrant/systemd/build/mkosi.output/image --no-pager --dry-run=no --offline=no --pretty=no /work/home/vagrant/systemd/build/mkosi.output/image
Failed to mount image: No such file or directory
‣ "/usr/bin/python3 -SI /home/vagrant/mkosi/mkosi/sandbox.py --proc /proc --unsetenv TMPDIR --setenv SYSTEMD_OFFLINE 1 --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/usr /usr --symlink usr/bin /bin --symlink usr/sbin /sbin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/etc/alternatives /etc/alternatives --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/etc/ld.so.cache /etc/ld.so.cache --dir /var/tmp --dir /var/log --unshare-ipc --ro-bind /home/vagrant/mkosi/mkosi/sandbox.py /sandbox.py --bind /sys /sys --bind /dev /dev --ro-bind /etc/resolv.conf /etc/resolv.conf --setenv PATH /usr/sbin:/usr/bin --bind /var/tmp/mkosi-var-tmp-13d23fbaa641476c /var/tmp --dir /tmp --dir /run --bind /home/vagrant/systemd/build/mkosi.output/image /work/home/vagrant/systemd/build/mkosi.output/image --ro-bind /home/vagrant/systemd/build /home/vagrant/systemd/build --ro-bind /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /proxy.cacert -- systemd-repart --image /work/home/vagrant/systemd/build/mkosi.output/image --no-pager --dry-run=no --offline=no --pretty=no /work/home/vagrant/systemd/build/mkosi.output/image" returned non-zero exit code 1.
Traceback (most recent call last):
  File "/home/vagrant/mkosi/mkosi/run.py", line 62, in uncaught_exception_handler
    yield
  File "/usr/lib64/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/mkosi/mkosi/__main__.py", line 36, in main
    run_verb(args, images, resources=resources)
  File "/home/vagrant/mkosi/mkosi/__init__.py", line 4816, in run_verb
    {
  File "/home/vagrant/mkosi/mkosi/__init__.py", line 3838, in run_shell
    run(
  File "/home/vagrant/mkosi/mkosi/run.py", line 150, in run
    with spawn(
         ^^^^^^
  File "/usr/lib64/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/vagrant/mkosi/mkosi/run.py", line 295, in spawn
    raise subprocess.CalledProcessError(returncode, cmdline)
subprocess.CalledProcessError: Command '['systemd-repart', '--image', '/work/home/vagrant/systemd/build/mkosi.output/image', '--no-pager', '--dry-run=no', '--offline=no', '--pretty=no', '/work/home/vagrant/systemd/build/mkosi.output/image']' returned non-zero exit status 1.
```
I can boot it with
```
systemd-nspawn -i build/mkosi.output/image -b
```

**Comment by evverx** [comment]
Either way I just blindly followed HACKING.md (and replaced `ninja` with `meson compile` because `ninja` fails with
```
ninja: error: unknown target 'mkosi'
```
).

If there is an environment where
```sh
mkosi -f sandbox meson setup build
mkosi -f sandbox ninja -C build
mkosi -f sandbox build/systemctl --version
mkosi -f sandbox ninja -C build mkosi
sudo mkosi boot
```
actually works out of the box it would be great if it was mentioned somewhere.

**Comment by DaanDeMeyer** [comment]
It seems I mistakenly assumed `ninja` and `meson compile` where equivalent but they're not, I'll push a fix to use `meson compile -C build mkosi` instead of `ninja -C build mkosi`

**Comment by DaanDeMeyer** [comment]
> Here's how `mkosi boot` fails:
> 
> ```shell
> ...
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + /home/vagrant/systemd/build/systemd-nspawn --version
> ‣ + timedatectl show -p Timezone --value
> ‣ + openssl x509 -in /work/home/vagrant/systemd/mkosi.crt -pubkey -noout
> ‣ + ssh-keygen -f /dev/stdin -i -m PKCS8
> ‣ Acquiring lock on /home/vagrant/systemd/build/mkosi.output/image
> ‣ Acquired lock on /home/vagrant/systemd/build/mkosi.output/image
> ‣ + systemd-repart --image /work/home/vagrant/systemd/build/mkosi.output/image --no-pager --dry-run=no --offline=no --pretty=no /work/home/vagrant/systemd/build/mkosi.output/image
> Failed to mount image: No such file or directory
> ‣ "/usr/bin/python3 -SI /home/vagrant/mkosi/mkosi/sandbox.py --proc /proc --unsetenv TMPDIR --setenv SYSTEMD_OFFLINE 1 --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/usr /usr --symlink usr/bin /bin --symlink usr/sbin /sbin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/etc/alternatives /etc/alternatives --ro-bind /home/vagrant/systemd/build/mkosi.output/tools/etc/ld.so.cache /etc/ld.so.cache --dir /var/tmp --dir /var/log --unshare-ipc --ro-bind /home/vagrant/mkosi/mkosi/sandbox.py /sandbox.py --bind /sys /sys --bind /dev /dev --ro-bind /etc/resolv.conf /etc/resolv.conf --setenv PATH /usr/sbin:/usr/bin --bind /var/tmp/mkosi-var-tmp-13d23fbaa641476c /var/tmp --dir /tmp --dir /run --bind /home/vagrant/systemd/build/mkosi.output/image /work/home/vagrant/systemd/build/mkosi.output/image --ro-bind /home/vagrant/systemd/build /home/vagrant/systemd/build --ro-bind /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /proxy.cacert -- systemd-repart --image /work/home/vagrant/systemd/build/mkosi.output/image --no-pager --dry-run=no --offline=no --pretty=no /work/home/vagrant/systemd/build/mkosi.output/image" returned non-zero exit code 1.
> Traceback (most recent call last):
>   File "/home/vagrant/mkosi/mkosi/run.py", line 62, in uncaught_exception_handler
>     yield
>   File "/usr/lib64/python3.12/contextlib.py", line 81, in inner
>     return func(*args, **kwds)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/vagrant/mkosi/mkosi/__main__.py", line 36, in main
>     run_verb(args, images, resources=resources)
>   File "/home/vagrant/mkosi/mkosi/__init__.py", line 4816, in run_verb
>     {
>   File "/home/vagrant/mkosi/mkosi/__init__.py", line 3838, in run_shell
>     run(
>   File "/home/vagrant/mkosi/mkosi/run.py", line 150, in run
>     with spawn(
>          ^^^^^^
>   File "/usr/lib64/python3.12/contextlib.py", line 144, in __exit__
>     next(self.gen)
>   File "/home/vagrant/mkosi/mkosi/run.py", line 295, in spawn
>     raise subprocess.CalledProcessError(returncode, cmdline)
> subprocess.CalledProcessError: Command '['systemd-repart', '--image', '/work/home/vagrant/systemd/build/mkosi.output/image', '--no-pager', '--dry-run=no', '--offline=no', '--pretty=no', '/work/home/vagrant/systemd/build/mkosi.output/image']' returned non-zero exit status 1.
> ```
> 
> I can boot it with
> 
> ```
> systemd-nspawn -i build/mkosi.output/image -b
> ```

@evverx Can you check dmesg after getting this error? This looks similar to a kernel regression we've seen in CI which has been backported to stable kernels.

**Comment by evverx** [comment]
Here's what ends up there when `mkosi boot` is run:
```sh
Dec 24 12:56:42 A kernel: loop0: detected capacity change from 0 to 18876456
Dec 24 12:56:42 A kernel:  loop0: p1 p2
Dec 24 12:56:42 A kernel: BTRFS info: 'norecovery' is for compatibility only, recommended to use 'rescue=nologreplay'
Dec 24 12:56:42 A kernel: BTRFS info: 'norecovery' is for compatibility only, recommended to use 'rescue=nologreplay'
Dec 24 12:56:42 A kernel: BTRFS error: failed to lookup block device for path /loop0p2: -2
```

**Comment by avramd** [comment]
> Either way I just blindly followed HACKING.md (and replaced `ninja` with `meson compile` because `ninja` fails with
> 
> ```
> ninja: error: unknown target 'mkosi'
> ```

Thanks for the confirmation @evverx . @DaanDeMeyer FWIW, I did try removing `build` to truly start from scratch, and got the same result.

**Comment by DaanDeMeyer** [comment]
> Here's what ends up there when `mkosi boot` is run:
> 
> ```shell
> Dec 24 12:56:42 A kernel: loop0: detected capacity change from 0 to 18876456
> Dec 24 12:56:42 A kernel:  loop0: p1 p2
> Dec 24 12:56:42 A kernel: BTRFS info: 'norecovery' is for compatibility only, recommended to use 'rescue=nologreplay'
> Dec 24 12:56:42 A kernel: BTRFS info: 'norecovery' is for compatibility only, recommended to use 'rescue=nologreplay'
> Dec 24 12:56:42 A kernel: BTRFS error: failed to lookup block device for path /loop0p2: -2
> ```

Yup, that's the same kernel issue, there's not a lot I can do here. Until someone reports that kernel bug and it gets fixed `mkosi boot` will be broken on kernels affected by that bug.

**Comment by DaanDeMeyer** [comment]
> > Either way I just blindly followed HACKING.md (and replaced `ninja` with `meson compile` because `ninja` fails with
> > ```
> > ninja: error: unknown target 'mkosi'
> > ```
> 
> Thanks for the confirmation @evverx . @DaanDeMeyer FWIW, I did try removing `build` to truly start from scratch, and got the same result.

Please use `meson compile -C build mkosi`, that should work.

**Comment by avramd** [comment]
Yes, it does. That was actually my originally reason for posting this issue was to suggest that change. However, you responded so fast that I hadn't had a chance to put that in a comment yet :-)

**Comment by evverx** [comment]
> Yup, that's the same kernel issue, there's not a lot I can do here. Until someone reports that kernel bug and it gets fixed mkosi boot will be broken on kernels affected by that bug.

Agreed. I think what I was trying to say is that stuff known to be broken shouldn't be recommended in the first place. I think it's safe to assume that what the CI does (and where it does it) can be more or less relied on and everything else is likely to be broken (or is going to be broken in the foreseeable future because it isn't tested anywhere on a regular basis).
