### ISSUE TITLE
systemd-resolved fails at boot and only works again after a restart

### ISSUE THREAD

**Issue by PoisonFrog** [systemd/systemd#35750]
### systemd version the issue has been seen with

257.1-1

### Used distribution

Arch Linux

### Linux kernel version used

6.6.67-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I boot and I expected DNS to work like it used to before I updated to version 257.

### Unexpected behaviour you saw

DNS doesn't work. When I use `resolvectl` I get these error messages:

> Failed to get link data for 4: Unknown object '/org/freedesktop/resolve1/link/_34'.
> Failed to get link data for 5: Unknown object '/org/freedesktop/resolve1/link/_35'.

It works till the next boot after I restart the service

### Steps to reproduce the problem

- Arch Linux
- LTS kernel
- latest version of systemd
- systemd-resolved stub
- network manager

**Comment by rpigott** [comment]
dup of #35654

**Comment by UffeJakobsen** [comment]
Hi,
I'm the creator of issue #35654 - the issue that this issue has been marked as a duplicate of...
In my opinion this issue describes a much simpler scenario - making it easier to debug than my issue - with that in mind I don't know if this issue should be closed - maybe this issue should be reopened and issue #35654 closed as a (complicated) duplicate ?
