### ISSUE TITLE
OT: Trying to contribute new version of `libnss-mdns`, but don't know where

### ISSUE THREAD

**Issue by ntninja** [systemd/systemd#3582]
### Submission type
- [X] Inappropriate abuse of this issue tracker to contact @poettering about an old project of this that apparently has [no real upstream](http://0pointer.de/lennart/projects/nss-mdns/)
- [x] I am sorry for doing this, but @poettering did not respond to my emails and I don't know where else to contact him about this

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### Why I'm writing

Some time ago I've written several patches for `libmdns-nss`. I'll just quote my previous e-mail messages:

> I know it's been a very long time since the last release of libnss-mdns, but 
> you still seem to be the "official" upstream for this library and I have 
> several patches that I'd like to be part of its codebase.
> These patches address three short-commings of the library, as it is today:
> - Full support for AF_UNSPEC (previous versions just treated AF_UNSPEC as if 
>   it was AF_INET) by retrieving, and returning, both IPv4 and IPv6 results in 
>   this case.
> - Obtaining/guessing IPv6 scope IDs from avahi or mdns/legacy
> - Support for the _nss_mdns_gethostbyname4_r interface:
>   This interface probably just wasn't around in 2007, but without it, neither 
>   AF_UNSPEC addresses nor IPv6 scope IDs can actually be passed to applications.
> 
> Currently I've uploaded the patches to the GIT repository [here](https://gitlab.com/alexander255/nss-mdns), but I can also submit plain old .patch-
> files, if that is preferred. The GIT repository does not contain any pre-0.10 
> history since your SVN repository is offline unfortunately.
> 
> All code was tested on Debian testing and Ubuntu 15.10.
> 
> The most obvious thing, that suddenly works, when you apply these patches, is 
> using ping6 on MDNS addresses:
> 
>    $ ping6 Alexander-VM-2.local
>    PING Alexander-VM-2.local(alexander-VM-2.local (fe80::a00:27ff:fe75:c2e1)) 
> 56 data bytes
>    64 bytes from alexander-VM-2.local (fe80::a00:27ff:fe75:c2e1%vboxnet0): 
> icmp_seq=1 ttl=64 time=0.431 ms
>    64 bytes from alexander-VM-2.local (fe80::a00:27ff:fe75:c2e1%vboxnet0): 
> icmp_seq=2 ttl=64 time=0.475 ms
>    64 bytes from alexander-VM-2.local (fe80::a00:27ff:fe75:c2e1%vboxnet0): 
> icmp_seq=3 ttl=64 time=0.529 ms
>    64 bytes from alexander-VM-2.local (fe80::a00:27ff:fe75:c2e1%vboxnet0): 
> icmp_seq=4 ttl=64 time=0.200 ms
>    ^C
>    --- Alexander-VM-2.local ping statistics ---
>    4 packets transmitted, 4 received, 0% packet loss, time 2997ms
>    rtt min/avg/max/mdev = 0.200/0.408/0.529/0.127 ms
> 
> Previously, that would have resulted in an unfriendly "connect: Invalid 
> argument" or "unknown host" error (as [documented on the internet](https://
> blogs.gentoo.org/eva/2010/12/17/things-you-didnt-known-about-ipv6-link-local-
> address/) 😉).

Source code with patches is available here: https://gitlab.com/alexander255/nss-mdns

@poettering: By all means, please feel free to point out the appropriate place to get this code reviewed and upstreamed.

**Comment by agoode** [comment]
See lathiat/avahi#64.

**Comment by agoode** [comment]
https://github.com/lathiat/nss-mdns

**Comment by poettering** [comment]
Yupp, I am a shitty maintainer for nss-mdns, and I am happy @lathiat took this over

(in the longer run I think resolved should just do mdns fully, and thus nss-resolve take over the role of nss-mdns).

Closing this, as this is misfiled here. I am happy if @lathiat maintains this instead!
