### ISSUE TITLE
RFE: `machinectl clean` is missing polkit support

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#3585]
### Submission type
- Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230 eee0a1e4
### Used distribution

> Gentoo (Kernel 4.5.0)
### In case of bug report: Expected behaviour you didn't see

> Executing `machinectl clean` as non-root user should ask for elevated privileges through polkit, but doesn't
### In case of bug report: Unexpected behaviour you saw

> Executing `machinectl clean` as non-root user simply returns `Could not clean pool: Access denied`
### In case of bug report: Steps to reproduce the problem

> Execute `machinectl clean` as non-root user
## TODO

Add polkit support to `machinectl clean` to be consistent with other `machinectl` commands such as `clone`, `start`, `remove`, etc.

**Comment by poettering** [comment]
actually, it already has the polkit hookup, but the bus policy wasn't updated for this call, and thus will already refuse invocations of the method before the polkit check could take place.

**Comment by poettering** [comment]
Fix waiting in #3596.
