### ISSUE TITLE
`SystemCallFilter=` in `systemd-machined` service unit break `machinectl`'s `login` and `shell`

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#3586]
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> 230 (eee0a1e4)
### Used distribution

> Gentoo (Kernel 4.5.0)
### In case of bug report: Expected behaviour you didn't see

> `machinectl login …` and `machinectl shell …` allowing to access a running machine/container
### In case of bug report: Unexpected behaviour you saw

> Instead of providing a login prompt/shell, both commands just return `Failed to get login PTY: Input/output error`
### In case of bug report: Steps to reproduce the problem

> Start any kind of machine/container (reproduced here with CentOS 7 and Debian 8 (Jessie) and try either `machinectl login $CONTAINER` or `machinectl shell $CONTAINER`.
### Notes

This problem can be "solved" by dropping `SystemCallFilter=` (introduced recently in 40093ce5dd4446c011377de6ec74d12a5b8a95b9 and 4e069746fe0de1f60bd1b75c113b0f40ffe86736) from the `systemd-machined` service unit

**Comment by poettering** [comment]
Fix is already waiting as part of #3572. Just needs somebody to review it and press the green button.

**Comment by poettering** [comment]
Closing, as #3572 was merged.

**Comment by eliasp** [comment]
Thanks a lot! Didn't get around to test + review it during the weekend!
