### ISSUE TITLE
systemd wants to fsck /dev/nfs for root=/dev/nfs

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#3590]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

```
root=/dev/nfs is a legacy option for the kernel to handle root on NFS.

Documentation for this kernel command line option
can be found in the kernel source tree:

Documentation/filesystems/nfs/nfsroot.txt
```

**Comment by poettering** [comment]
Fixed by #3591 which was just merged.

**Comment by mbiebl** [comment]
@haraldh We just had a downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881834 where systemd-remount-fs fails, or rather mount.nfs fails in the presence of the following fstab entry:
```
/dev/nfs           /    nfs     defaults,rw
```
with the following message:
```
Nov 12 16:19:59 raspberrypi systemd-remount-fs[123]: /bin/mount for / exited with exit status 32.
Nov 12 16:19:59 raspberrypi systemd-remount-fs[123]: mount.nfs: remote share not in 'host:dir' format
```

Should we ignore such /dev/nfs pseudo-device in systemd-remount-fs as well, or is this a bug in mount.nfs or simply a misconfiguration by the user?

**Comment by poettering** [comment]
Sounds like a bug in mount.nfs to me. For remounts mount helpers really shouldn't be bothered with the source of a mount anymore. @neilbrown, could you please comment on that?

**Comment by neilbrown** [comment]
Yes, I think that could reasonably be seen as a bug in mount.nfs.  I've sent a patch.
Thanks.

**Comment by mbiebl** [comment]
thanks @neilbrown
