### ISSUE TITLE
logind: system sleep request always exhausts the full timeout

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#360]
Starting with commit c0f32805086ff65d2905b0e3a9166d9ed6c2bc41, if there is an inhibitor lock of type "delay" (such as the one created by NetworkManager), logind will wait `InhibitDelayMaxSec` seconds before executing the requested operation.

Please note that NetworkManager's inhibitor lock disappears from `systemd-inhibit --list` right as I issue the `systemctl suspend` command. logind should be able to suspend the machine immediately and not have to exhaust the full timeout.

**Comment by poettering** [comment]
cc @zonque

**Comment by zonque** [comment]
Does zonque@418b22b fix the issue for you?

**Comment by foutrelis** [comment]
Yes, with your patch the system goes to sleep almost instantly.

I also tested while running `systemd-inhibit --what sleep --mode delay sleep 1000` in another terminal and it correctly waits `InhibitDelayMaxSec` before suspending the machine.

**Comment by zonque** [comment]
Nice, thanks. I'll send a pull request then.
