### ISSUE TITLE
journalctl -b 0 doesn't seem to work

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#3603]
Version: 230

I've mounted another linux system as I wanted to inspect the journal.
journalctl --list-boots shows

```
 -2 f2c9668240bf458a96948bb490923ba0 Di 2016-06-21 22:01:04 CEST—Di 2016-06-21 22:21:40 CEST
 -1 43f6209bfc284a7d9ef1e1f24d7721c9 Fr 2016-06-24 23:08:57 CEST—Fr 2016-06-24 23:13:18 CEST
  0 9e2ffa348b354fbc8555aa1f524214e5 So 2016-06-26 03:03:22 CEST—So 2016-06-26 03:31:00 CEST
```

Running

```
journalct -b 0
```

only gives me an "-- No entries --"

When I simply run journalctl, I see the log messages from the boot that happened on 03:31:00

**Comment by mbiebl** [comment]
Fwiw, I've also tried journalctl -b -0, but I don't get any log entries either

**Comment by mbiebl** [comment]
journalctl -b 9e2ffa348b354fbc8555aa1f524214e5 on the other hand works

**Comment by poettering** [comment]
uh oh. "journalctl -b0" shows you the data from the current boot, i.e. the stuff attached to the boot id of the system you are running on. of course if you use data from another system this will result in nothing...

**Comment by mbiebl** [comment]
Well, --list-boots seems to show the proper value for 0, don't you think we could also fix
journactl -b -0?
