### ISSUE TITLE
Could not remove directory (resource bussy) due to systemd-timesyncd daemon

### ISSUE THREAD

**Issue by nuxwin** [systemd/systemd#3604]
Morning,

We are facing a weird problem with systemd when the systemd-timesyncd service is active.

We have a service which mount some fs using our own library on reboot and mark them as private bindmounts (mount -make-private ...):

```
[Unit]
Description=Mounts i-MSCP filesystems
Before=umount.target
After=local-fs.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/perl /var/www/imscp/engine/tools/imscp-mountall start
ExecStop=/usr/bin/perl /var/www/imscp/engine/tools/imscp-mountall stop

[Install]
WantedBy=multi-user.target
```

When stopping our service, all fs are umounted (they are no longer listed in /proc/mounts). The problem is that when we try to remove a directory (mountpoint), we receive an error such as "resource busy" even if the fs has been umounted.

After some investigation it appears that the problem comes from the `systemd-timesyncd` daemon. Indeed, when we deactivate that service, the problem gone.

```
root@jessie:~# LANG=C rm -r /var/chroot/InstantSSH/shared_jail/var/www/virtual
rm: cannot remove '/var/chroot/InstantSSH/shared_jail/var/www/virtual': Device or resource busy
root@jessie:~# service systemd-timesyncd stop
root@jessie:~# LANG=C rm -r /var/chroot/InstantSSH/shared_jail/var/www/virtual
root@jessie:~#
```

Environment:

```
root@jessie:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:    8.5
Codename:   jessie
root@jessie:~# systemctl --version
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR
root@jessie:~# 
```

Thanks you.

**Comment by poettering** [comment]
well, if you mark a directory "private", then anything that creates its own namespace will get a copy of that dir, but no further propagation of that mount point will take place. timesyncd makes use of fs namespacing, due to its four service settings: 

```
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=full
ProtectHome=yes
```

hence, when timesyncd starts the host's namespace will be duplicated and if you marked it private then all mount points are pinned inside the new namespace forever, because you explicitly asked for no changes to be propagated anymore, by marking it private. Don't forget that marking something as private means you turn off mounts as well as umounts below it. 

Hence, you kinda got what you asked for here...

**Comment by poettering** [comment]
(one way out for you, if you really want the private stuff is to turn off namespacing in timesyncd and all other daemons, by disabling the settings pointed out above, but of course that will not be good for the sandbox they run in...)

**Comment by nuxwin** [comment]
@poettering 

First, I would really thank you for your answer. An answer from Leonard Poettering is always appreciated.

Well, we need set private mounts because the fs are mounted in jails, but also at other places. Thus, when we unmount an fs from a specific jail, we don't want propagate the event at other places... Maybe I don't understand the concept here.. For instance, even when we set the fs (bindmounts in fact) as slave, we get the same problem.

**Comment by poettering** [comment]
your jails should really be mounted as "slave" then...

But i really don't know how your namespacing is set up. which namespacing tool do you use? does it alter the propagation of the host's root mount?

**Comment by nuxwin** [comment]
@poettering

We have an fstab-like file which look like:

```
root@jessie:~# cat /etc/imscp/mounts/mounts.conf 
# fstab-like configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
/var/log/apache2/test.tld /var/www/virtual/test.tld/logs/test.tld none private,bind
/var/log/apache2/alias.tld /var/www/virtual/test.tld/logs/alias.tld none private,ro,bind
devpts /var/chroot/InstantSSH/shared_jail/dev/pts devpts gid=5,mode=620
proc /var/chroot/InstantSSH/shared_jail/proc proc defaults
sysfs /var/chroot/InstantSSH/shared_jail/sys sysfs defaults
/var/log/lastlog /var/chroot/InstantSSH/shared_jail/var/log/lastlog none private,bind
/var/www/virtual /var/chroot/InstantSSH/shared_jail/var/www/virtual none private,bind
root@jessie:~# 
```

This file is processed by our own library (we do not want make any change in system fstab):
- https://github.com/i-MSCP/imscp/blob/1.3.x/configs/debian/systemd/imscp_mountall.service
- https://github.com/i-MSCP/imscp/blob/1.3.x/engine/tools/imscp-mountall
- https://github.com/i-MSCP/imscp/blob/1.3.x/engine/PerlLib/iMSCP/Mount.pm

The jail are not namespaced. They are simple chroot created using makejail script.

Any idea is welcome.

**Comment by arvidjaar** [comment]
> When stopping our service, all fs are umounted (they are no longer listed in /proc/mounts). The problem is that when we try to remove a directory (mountpoint), we receive an error such as "resource busy" even if the fs has been umounted.

I cannot reproduce it. systemd sets systemd-timesyncd mount points as slaves to parent, "global" namespace; so when I unmount filesystem in global namespace it is also unmounted in systemd-timesyncd one. Something else must be going on. Please carefully check content of /proc/1/mountinfo (which is "global" namespace) and `/proc/<pid>/mountinfo`, where `<pid>` is systemd-timesyncd PID. Before timesyncd is stopped and after.

**Comment by arvidjaar** [comment]
> Before timesyncd is stopped and after.

Sorry, I meant "before filesystem is unmounted and after".

**Comment by nuxwin** [comment]
@arvidjaar 

Morning. Which distro (and codename) do you use?

**Comment by arvidjaar** [comment]
@nuxwin I used openSUSE Tumbleweed, fully up-to-date as of this morning. Test was trivial - mount /tmp/www on /tmp/jail/www (using -o bind,private), start systemd-timesyncd, unmount /tmp/jail/www, verify that it is also gone in timesyncd namespace (and I can delete /tmp/jail/www).

**Comment by russdill** [comment]
Really late followup. Is there a way to prevent a mount from showing up in systemd-timesyncd at all? I've tried marking / as private before local-fs.target gets going, but services with mount namespaces just mark / as shared in their own namespace and mount points get propagated anyway. This is really annoying when you want to unmount some filesystem, exponentially so if original namespace is gone and it is now impossible to unmount.
