### ISSUE TITLE
Systemd sends D-Bus Hello when communicating with /run/systemd/private

### ISSUE THREAD

**Issue by tmrts** [systemd/systemd#3610]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

230
### In case of bug report: Expected behaviour you didn't see

The D-Bus Hello method should only be called when a client is connecting to a bus, not when it is connecting via p2p D-Bus. Assuming systemd's private socket is not supposed to handle a full D-Bus bus.
### In case of bug report: Unexpected behaviour you saw

systemd assumes full D-Bus implementation when communicating with `/run/systemd/private` socket
in a systemd-nspawn container.
### In case of bug report: Steps to reproduce the problem

systemctl -M can connect to systemd's `/run/systemd/private` socket. It does not work though: strace reveals that systemctl calls the D-Bus Hello and strace on systemd reveals that it replies `Unknown object '/org/freedesktop/DBus'`.

/cc @alban

**Comment by poettering** [comment]
Hmm, so I am a bit confused about what you are saying. If you use "systemctl -M", then this means /run/systemd/private is _not_ used. In fact /run/systemd/private is only used when connecting to the local systemd instance, and if do it as root.

What's the precise systemctl command you are issueing where you see this effect?

I tried to reproduce this with `systemctl -M foo status --no-pager` and that works fine and /run/systemd/private is not used at all as strace proves... Please describe exactly the context where you see what you are seeing.

**Comment by alban** [comment]
The reproduction steps to produce the "Unknown object '/org/freedesktop/DBus'" error are to trick "systemctl -M rkt-xxx" to use the systemd private socket by creating a symlink "/run/dbus/system_bus_socket -> /run/systemd/private".

In rkt, we don't have dbus-daemon running in the pod, so I wanted to check if it was possible to talk to systemd's private socket directly without installing dbus-deamon inside the pod. Our only use-case for D-Bus in the pod so far is for tools on the host to talk to systemd in the pod, so adding dbus-daemon seemed overkill to me. We want to be able to ask systemd to create/start/stop/delete systemd units.

A bit more context in that comment: https://github.com/coreos/rkt/issues/1463#issuecomment-228087464

**Comment by poettering** [comment]
well, the sockets are not interchangable. i can understand why you want to use the direct socket, but just symlinking them is not sufficient, and this issue here is really not a bug.

I am not overly happy with trying to make /run/systemd/private public API btw. It's name is "private" for a reason, after all. I am particularly concerned about making this a cross-node API, so that the systemd instance inside a container can't be updated without also updating the client on the host.

I think the better approach for all of this is probably just do the full dbus bus logic in systemd itself, in a child process forked off PID 1, and get rid of dbus-daemon fully. We kinda implemented that already, in the kdbus proxy, with all the complexities of the policy and stuff, so it's mostly just a matter of resurrecting that, removing the kdbus part of it and integrating it properly.

**Comment by vcaputo** [comment]
@alban Why wouldn't you just abstract the `systemctl -M ...` invocations as a stage1-specific method and just let it communicate with the stage1 systemd daemon as usual without any symlink trickery?  The stage1 uses systemd, it should have its private control socket at the appropriate place, you just need to run its systemctl in the appropriate root relative to the stage1 systemd, no?

**Comment by alban** [comment]
@vcaputo Do you mean enter the pod namespaces and execute systemctl from within the pod? Thanks for the idea!

**Comment by vcaputo** [comment]
@alban Something like that, though I must admit when I responded above I was half asleep and didn't quite understand the spirit of what you were attempting to do.

If the intention is for the host's `systemctl` to transparently communicate with the rkt pod's systemd when using a systemd-based stage1, then I don't think my suggestion is all that helpful.

In that case it seems like the machine registration api should have a systemd control socket parameter, so the machine can register its systemd instance with the host's systemd, then the host's systemd can know where to find the nested systemd without any proxy.

However, that still has the trouble of this _private_ socket's api becoming _semi public_, at least in terms of differing versions of systemd talking to one another.  But in the case of `rkt`, if you're always deriving the stage1's systemd from the host's installed systemd, then you know the versions will be the same, except I suppose for pods which have survived a host's systemd upgrade.

I think the rules surrounding this interaction need to be firmed up before you can really make any meaningful progress.  Depending on what kind of api stability commitment there could be for the systemd private control socket, maybe some of these problems could just vanish and the host's systemctl could talk directly to the container pod1's systemd, if it just knew where to find the control socket.
