### ISSUE TITLE
systemd-nspawn --volatile and machine-id

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#3611]
seen with systemd-230 fedora rawhide

systemd-nspawn really wants to read /etc/machine-id, but it is not present in unconfigured image:

[root@notas ~]# systemd-nspawn --volatile -M my_container
Failed to read machine ID from /var/lib/machines/my_container/etc/machine-id: No such file or directory
[root@notas ~]# systemd-nspawn --volatile --uuid=6b54f61f-797f-43ed-a835-6f439fc19788 -M my_container
Failed to read machine ID from /var/lib/machines/my_container/etc/machine-id: No such file or directory

**Comment by evverx** [comment]
Seems like https://github.com/systemd/systemd/pull/490#issuecomment-171432844

`systemd-nspawn --link-journal=auto ...` is a workaround:)

**Comment by evverx** [comment]
Hm, no. This is another issue.

**Comment by evverx** [comment]
was introduced by e01ff70a77e78173

> refuses to boot containers without /etc/machine-id (OK?), and with empty /etc/machine-id (not OK).

so, we need an empty `/etc/machine-id` at least

**Comment by lnykryn** [comment]
I have not tried that but I would guess that ConditionFirstBoot= could be broken as well, since it requires empty /etc

**Comment by evverx** [comment]
@lnykryn , you're right

``` c

                /* Let's check whether /etc is already populated. We
                 * don't actually really check for that, but use
                 * /etc/machine-id as flag file. This allows container
                 * managers and installers to provision a couple of
                 * files already. If the container manager wants to
                 * provision the machine ID itself it should pass
                 * $container_uuid to PID 1. */

                empty_etc = access("/etc/machine-id", F_OK) < 0;
                if (empty_etc)
                        log_info("Running with unpopulated /etc.");
                [...]
                manager_set_first_boot(m, empty_etc);
```

``` sh
$ sudo rm /var/tmp/systemd-test.FRx1eK/nspawn-root/etc/machine-id
$ sudo touch /var/tmp/systemd-test.FRx1eK/nspawn-root/etc/machine-id
$ sudo ../../systemd-nspawn -D /var/tmp/systemd-test.FRx1eK/nspawn-root -b 3 systemd.log_level=debug
...
systemd-firstboot.service: ConditionFirstBoot=yes failed.
systemd-firstboot.service: Starting requested but condition failed. Not starting unit.
systemd-firstboot.service: Job systemd-firstboot.service/start finished, result=done
...
```
