### ISSUE TITLE
systemctl: preset-all does not handle several units correctly

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#3616]
### Submission type
- [*] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> git snapshot 0c6aeb4

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora rawhide (x86_64)
### In case of bug report: Expected behaviour you didn't see

> systemctl preset-all command does enable or remove several units.
### In case of bug report: Unexpected behaviour you saw

> systemctl preset-all command correctly handle all units.
### In case of bug report: Steps to reproduce the problem

In /etc/systemd/system-preset/00-hoge.preset, I wrote

```
enable systemd-networkd.service
enable systemd-networkd-wait-online.service
disable *
```

then,

```
# systemctl disable systemd-networkd.service systemd-networkd-wait-online.service
# systemctl preset-all
Unit syslog.service is an alias to a unit that is not present, ignoring.
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /usr/lib/systemd/system/systemd-networkd-wait-online.service.
```

As shown in above, -wait-online.service is enabled correctly, but systemd-networkd.service and .socket are not enabled by preset-all command.

Moreover, the last line 'disable *' does not work for several units, e.g.,

```
# systemctl enable mcelog.service
# systemctl preset-all
# systemctl preset mcelog.service
Removed /etc/systemd/system/multi-user.target.wants/mcelog.service.
```

I note that preset command works fine:

```
# systemctl disable systemd-networkd.service systemd-networkd-wait-online.service 
# systemctl preset systemd-networkd.service systemd-networkd-wait-online.service 
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /usr/lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /usr/lib/systemd/system/systemd-networkd.socket.
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /usr/lib/systemd/system/systemd-networkd-wait-online.service.
```

The preset files in my system are below.

```
# ls /etc/systemd/system-preset/
00-hoge.preset
# ls /usr/lib/systemd/system-preset/
85-display-manager.preset  90-default.preset  90-systemd.preset  99-default-disable.preset
```

The preset files in /usr/lib/systemd/system-preset are comes from fedora packages and I do not edit them.

**Comment by evverx** [comment]
Seems like https://github.com/systemd/systemd/issues/2513

**Comment by yuwata** [comment]
@evverx Yeah, it's seems to be duplicate, sorry.

I've tested more, then find another problem and workaround for them.

Before reporting detail, I write here the workaround.
First, in the preset file with 'disable *' at the end of it, we need to list
- units we want to enable,
- their symbolic links in systemd unit directory,
- units mentioned by 'Also=' and 'Alias=' options in the unit files we want to enable.
  Second, before run 'systemctl preset-all', we need to remove all symbolic links that will be created by 'Alias=' option in the unit files. Then, we can successfully run 'systemctl preset-all' command.

Example.
/etc/systemd/system/test1.service

```
[Unit]
Description=test service 1

[Service]
Type=oneshot
ExecStart=/usr/bin/true

[Install]
WantedBy=multi-user.target
Also=test2.service
Alias=alias1.service
```

/etc/systemd/system/test2.service

```
[Unit]
Description=test service 2

[Service]
Type=oneshot
ExecStart=/usr/bin/true

[Install]
WantedBy=multi-user.target
```

/etc/systemd/system-preset/00-preset1.preset

```
enable test1.service
enable test2.service
enable alias1.service
disable *
```

Then,

```
[root@localhost ~]# systemctl disable test1.service test2.service alias1.service
[root@localhost ~]# systemctl preset-all
Created symlink /etc/systemd/system/alias1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
[root@localhost ~]# systemctl preset-all
Failed to preset all units: Too many levels of symbolic links
[root@localhost ~]# rm /etc/systemd/system/alias1.service 
rm: remove symbolic link '/etc/systemd/system/alias1.service'? y
[root@localhost ~]# systemctl preset-all
Created symlink /etc/systemd/system/alias1.service → /etc/systemd/system/test1.service.
```

**Comment by yuwata** [comment]
So, there exist I think two problem here.

First problem is that we need to list units not only we want to enable, but also units installed by 'Also=' and 'Alias=' options. I'm not sure it should be fixed or not, but at least, it should be documented somewhere.

Second problem is that if alias units are enabled by the preset files, we need to remove the aliases before run 'systemctl preset-all' command. Otherwise, it fails with error message 'Failed to preset all units: Too many levels of symbolic links'.

**Comment by yuwata** [comment]
The second problem above seems to be related to https://github.com/systemd/systemd/issues/3010.

**Comment by keszybz** [comment]
@yuwata If you could check out the PR that would be great.

**Comment by yuwata** [comment]
The PR #3955 works fine. Thanks.

One point I notice that is if we call preset command twice, the second call do nothing. However, if we call preset-all twice, then the second call once disable Also= unit and recreate symlink of it.
So, preset and preset-all is not idempotent. But this difference makes no problem for me.

With the above example in https://github.com/systemd/systemd/issues/3616#issuecomment-233967783 now

```
# systemctl preset test1.service
Created symlink /etc/systemd/system/alias1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
# systemctl preset test1.service
# systemctl disable test1.service
Removed /etc/systemd/system/alias1.service.
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
Removed /etc/systemd/system/multi-user.target.wants/test1.service.
# systemctl preset-all
Created symlink /etc/systemd/system/alias1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
# systemctl preset-all
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
```

**Comment by keszybz** [comment]
I cannot reproduce this last issue:

```
$ sudo systemctl preset test1
$ sudo systemctl preset test1
[zbyszek@fedora-rawhide systemd-master]$ sudo systemctl disable test1
Removed /etc/systemd/system/alias1.service.
Removed /etc/systemd/system/multi-user.target.wants/test1.service.
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
$ sudo systemctl preset-all
Created symlink /etc/systemd/system/alias1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test1.service → /etc/systemd/system/test1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
$ sudo systemctl preset-all
$ sudo systemctl disable test2
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
$ sudo systemctl preset-all
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
$ sudo systemctl preset-all
$ sudo systemctl disable test2
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
$ sudo systemctl preset-all
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
$ sudo systemctl preset-all
$ sudo systemctl disable test2
Removed /etc/systemd/system/multi-user.target.wants/test2.service.
$ sudo systemctl enable test2
Created symlink /etc/systemd/system/multi-user.target.wants/test2.service → /etc/systemd/system/test2.service.
$ sudo systemctl preset-all
```

Maybe the difference could be caused by different file system iteration order for those unit files, but I don't see how.
