### ISSUE TITLE
systemctl status output truncated at worst position with default terminal size

### ISSUE THREAD

**Issue by nalimilan** [systemd/systemd#3617]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Fedora 24

---

With the standard terminal width of 80 characters, the output of `systemctl status firewalld` looks like this:

```
$ systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset
```

while the full content of the last line is:

```
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
```

I find this small detail quite misleading: I interpreted the first output as indicating that the vendor preset was `disabled`, which made me believe firewalld was now disabled by default on Fedora 24, while I simply had disabled it manually.

I'm not sure what's the best solution, but it could be a good idea to print the full path only at the end of the line, since it takes a lot of space, or to move it to a separate line. It's always good to be able to read the full output in a standard terminal screen.

**Comment by shibumi** [comment]
Hello,
Normally the output should go into a less-session if the terminal is too small for it. Was this the case?
So you can just scroll left and right.

I am not sure what's the better way to solve this. I prefer the less-session. If you don't like it you can define an alias and invoke systemctl with `systemctl --no-pager`. With the `--no-pager`-flag it should works and you should see the rest of the line in a new line.

**Comment by nalimilan** [comment]
Yes, I can scroll right to see the end of the line. But the point of my suggestion is that interesting information should be immediately visible. What about breaking the line into two lines?

**Comment by shibumi** [comment]
@nalimilan 
You can break the line into two lines with using: `systemctl --no-pager`.

![example](https://paste.archlinux.de/NZQPZ/)

**Comment by keszybz** [comment]
Yeah, this layout is unfortunate with 80 columns. We could add more newlines here, but the information about preset status isn't the most important (usually), and I don't think it's worth adding another line of output to make it always visible. Once you know that you should scroll to the right to see truncated output, it works pretty well to put the less important stuff there.

**Comment by keszybz** [comment]
OK, I'm closing this, because there's no obvious bug. If you find a way to display this that is clearly better, please post a PR.

**Comment by ykfq** [comment]
use `systemctl status kubelet --full` or `systemctl status kubelet --no-pager --full`

![image](https://user-images.githubusercontent.com/20741596/43824547-e1332db4-9b24-11e8-8c06-b83265bc006c.png)

**Comment by twokangel** [comment]
Nicely formatted output but impossible to go to when your in a proper terminal as a default?.  This is linux. Ouput first, formatting second. I dont have time for this MS/apple nonsence

**Comment by btittelbach** [comment]
apart from the fact that  `systemd-inhibit -no-page` does not change it's behavior.

It starts truncating it's output (shortening strings with ...) once you pipe it's output into grep.

That is quite unacceptable. When I am checking if something is inhibited in a script, I should have all possible information available and not have to consider if a string will get truncated when being piped into a tool, that is perfectly readable on a wide terminal.

**Comment by keszybz** [comment]
> It starts truncating it's output (shortening strings with ...) once you pipe it's output into grep.

That's a different bug.
