### ISSUE TITLE
"systemctl --user unmask $SERVICE" as a user should be able to override root's "systemctl --global mask $SERVICE"

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#3623]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230
### Used distribution

> debian
### setup:

the local administrator decides to mask the per-user service "foo":

```
root@host:~# systemctl --global mask foo.service
Created symlink /etc/systemd/user/foo.service → /dev/null.
root@host:~# 
```

which we see as a normal user as:

```
0 user@host:~$ systemctl --user status foo
Failed to dump process list, ignoring: Unit foo.service is masked.
● foo.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

3 user@host:~$ 
```
### try to unmask as a normal user:

```
0 user@host:~$ systemctl --user unmask foo
0 user@host:~$ 
```

note the return code of 0 suggests we have successfully unmasked!

but the user service is still masked:

```
0 user@host:~$ systemctl --user status foo
Failed to dump process list, ignoring: Unit foo.service is masked.
● foo.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

3 user@host:~$ 
```
### expected behavior

Since per-user decisions override system-wide decisions for user configs, I'd have expected per-user unmasking to override system-wide masking, by doing something like:

```
ln -s /usr/lib/systemd/user/foo.service .config/systemd/user/
```

And indeed, when i do that manually, i see that it's unmasked:

```
0 user@host:~$ ln -s /usr/lib/systemd/user/foo.service ~/.config/systemd/user/
0 user@host:~$ systemctl --user status foo
● foo.service - Foo Example Service
   Loaded: loaded (/usr/lib/systemd/user/foo.service; linked; vendor preset: enabled)
   Active: inactive (dead)

3 user@host:~$ 
```

And i can even start and top the per-user service directly with `systemctl --user`.

However, i can't enable it:

```
0 user@host:~$ systemctl --user enable foo
Failed to enable unit: Too many levels of symbolic links
1 user@host:~$ 
```

So i think there are two unexpected behaviors here:
- `systemctl --user unmask foo` isn't capable of overriding root's `systemctl --global mask foo`
- enabling a service which is symlinked from ~/.config/systemd/user/  to /usr/lib/systemd/user/ doesn't seem to work properly because of the "too many levels of symbolic links".

**Comment by poettering** [comment]
hmm, "masking" is quite a heavy hammer, and that's really what it is supposed to be, hence i am not fully convinced that users really should be able to unmask something masked by the admin. Of course we should generate some log message about this though.

**Comment by dkg** [comment]
On Fri 2016-07-01 20:29:46 -0400, Lennart Poettering wrote:

> hmm, "masking" is quite a heavy hammer, and that's really what it is
> supposed to be, hence i am not fully convinced that users really
> should be able to unmask something masked by the admin. Of course we
> should generate some log message about this though.

The order of preference in systemd.unit for user services is:

```
   ~/.config/systemd/user/*
   /etc/systemd/user/*
   $XDG_RUNTIME_DIR/systemd/user/*
   /run/systemd/user/*
   ~/.local/share/systemd/user/*
   /usr/lib/systemd/user/*
```

in other words, the user's preferences trump the admin's preferences by
default anyway.  And given that the user can always copy the masked >
unit file and fiddle with its name to avoid the mask, the user can
in fact override the mask.

So why not make it straightforward to do so in the expected way?

   --dkg

**Comment by keszybz** [comment]
You can always do `ln -sv /usr/lib/systemd/user/whatever.service ~/.config/systemd/user/`. But this shouldn't be too easy: if the administrator masks a unit like, there's probably a good reason for that.
I'll close this, because we have too many bugs and I think this is too much of a niche case to add support for it in systemctl.
