### ISSUE TITLE
All `test/TEST-*` are broken with libqrencode

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#3630]
See https://github.com/systemd/systemd/pull/3516#issuecomment-229499855

```
-bash-4.3# ls /usr/lib/systemd/*shared* # that's ok
/usr/lib/systemd/libsystemd-shared-230.so
/usr/lib/systemd/libsystemd-shared.la
/usr/lib/systemd/libsystemd-shared.so

-bash-4.3# journalctl -b
journalctl: error while loading shared libraries: libqrencode.so.3: cannot open shared object file: No such file or directory

-bash-4.3# systemd-nspawn -h
systemd-nspawn: error while loading shared libraries: libip4tc.so.0: cannot open shared object file: No such file or directory

-bash-4.3# ldd $(type -p journalctl)
        linux-vdso.so.1 (0x00007ffd1ff9d000)
        libsystemd-shared-230.so => /usr/lib/systemd/libsystemd-shared-230.so (0x00007fbf08a3d000)
        libqrencode.so.3 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbf0881e000)
...

-bash-4.3# ldd $(type -p systemd-nspawn)
        linux-vdso.so.1 (0x00007ffc051e1000)
        libsystemd-shared-230.so => /usr/lib/systemd/libsystemd-shared-230.so (0x00007ffb7ce7b000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007ffb7cc6f000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007ffb7ca2c000)
        libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007ffb7c7eb000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ffb7c5c3000)
        libip4tc.so.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffb7c3a7000)
...
```

So, I guess this commit breaks https://github.com/systemd/systemd/blob/master/test/test-functions#L858 or so

**Comment by martinpitt** [comment]
The "upstream" tests did run for that PR #3516 and succeeded. Also, PR #3631 includes the shared lib commits and the "upstream" tests succeeded as well. So this isn't straightforward to reproduce.

**Comment by evverx** [comment]
Indeed. The `Build-Depends` doesn't contain `libqrencode-dev`

> Build-Depends: debhelper (>= 9.20141010), dpkg-dev (>= 1.17.14), pkg-config, xsltproc, docbook-xsl, docbook-xml, m4, dh-autoreconf, automake (>= 1.11), autoconf (>= 2.63), intltool, gperf, gnu-efi [amd64 i386], libcap-dev (>= 1:2.24-9~), libpam0g-dev, libapparmor-dev (>= 2.9.0-3+exp2) <!stage1>, libidn11-dev <!stage1>, libaudit-dev <!stage1>, libdbus-1-dev (>= 1.3.2) <!nocheck>, libcryptsetup-dev (>= 2:1.6.0) <!stage1>, libselinux1-dev (>= 2.1.9), libacl1-dev, liblzma-dev, libbz2-dev <!stage1>, zlib1g-dev <!stage1> | libz-dev <!stage1>, libcurl4-gnutls-dev <!stage1> | libcurl-dev <!stage1>, libmicrohttpd-dev <!stage1>, libgnutls28-dev <!stage1>, libgcrypt20-dev, libkmod-dev (>= 15), libblkid-dev (>= 2.24), libmount-dev (>= 2.27.1), libseccomp-dev (>= 2.2.3-3~) [amd64 arm64 armel armhf i386 mips mipsel mips64 mips64el x32 powerpc ppc64el s390x], libdw-dev (>= 0.158) <!stage1>, linux-base <!nocheck>, acl <!nocheck>, python3:native, python3-lxml:native

Try

``` sh
$ sudo apt-get build-dep -y systemd
$ sudo apt-get install -y libqrencode-dev
$ git clone https://github.com/systemd/systemd clean-systemd
$ cd clean-systemd
$ ./autogen.sh c && make
$ cd test/TEST-01-BASIC
$ sudo make clean setup run
...
systemd-journal-flush.service loaded failed failed Flush Journal to Persistent Storage
ls: cannot access '/var/tmp/systemd-test.s1tJgp/journal/*/*.journal': No such file or directory
TEST RUN: Basic systemd setup [FAILED]
Makefile:10: recipe for target 'run' failed
```

**Comment by evverx** [comment]
> are broken with libqrencode

This depends on the test. 

Anyway all `inst_*`-functions don't work properly.

**Comment by fsateler** [comment]
Hmm. The autopkgtests do print some F: lines but the test succeeds (look for test-01-basic at https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160625_044957@/log.gz )

In my own attempted repro the test succeeded. I don't know why are these failures ignored. But if they are correctly ignored, then the inst functions should not stop after the first not found, as that may cause libraries to be missing in the install if they appear later in the ldd output.

**Comment by evverx** [comment]
> In my own attempted repro the test succeeded

Did you install `libqrencode-dev`? See https://github.com/systemd/systemd/issues/3630#issuecomment-229590644

> I don't know why are these failures ignored. But if they are correctly ignored

This is a bug

**Comment by fsateler** [comment]
On 30 Jun 2016 8:28 a.m., "Evgeny Vereshchagin" notifications@github.com
wrote:

> > In my own attempted repro the test succeeded
> 
> Did you install libqrencode-dev? See #3630 (comment)

No, not yet. But if the ignores are a bug then it doesn't matter (because
it would fail anyway after the test is fixed).

> > I don't know why are these failures ignored. But if they are correctly ignored
> 
> This is a bug

Then the ldd loop needs to know about RUNPATH and add the root-prefixed
paths to LD_LIBRARY_PATH, because ldd apparently cannot be told to add a
root to resolve RUNPATH. I will look into this (but may be slow due to
$work)

**Comment by fsateler** [comment]
I think this fixes it:

``` diff
diff --git a/test/test-functions b/test/test-functions
index 4583c02..f968a5e 100644
--- a/test/test-functions
+++ b/test/test-functions
@@ -131,6 +131,13 @@ run_nspawn() {
     return 0
 }

+# ldd wrapper tries to allow following the RPATHs
+run_ldd() {
+    local _bin="$1"
+    local ldpath=$(objdump -p "$_bin" 2>/dev/null | awk "/R(UN)?PATH/ { print \"$initdir\" \$2 }" | paste -sd : -)
+    LC_ALL=C LD_LIBRARY_PATH=$ldpath ldd "$_bin"
+}
+
 setup_basic_environment() {
     # create the basic filesystem layout
     setup_basic_dirs
@@ -518,7 +525,7 @@ inst_libs() {
     local _so_regex='([^ ]*/lib[^/]*/[^ ]*\.so[^ ]*)'
     local _file _line

-    LC_ALL=C ldd "$_bin" 2>/dev/null | while read _line; do
+    run_ldd "$_bin" 2>/dev/null | while read _line; do
         [[ $_line = 'not a dynamic executable' ]] && break

         if [[ $_line =~ $_so_regex ]]; then
@@ -864,7 +871,7 @@ inst_binary() {
     local _file _line
     local _so_regex='([^ ]*/lib[^/]*/[^ ]*\.so[^ ]*)'
     # I love bash!
-    LC_ALL=C ldd "$_bin" 2>/dev/null | while read _line; do
+    run_ldd "$_bin" 2>/dev/null | while read _line; do
         [[ $_line = 'not a dynamic executable' ]] && break

         if [[ $_line =~ $_so_regex ]]; then
```

Further testing when I get back to my linux laptop.

**Comment by evverx** [comment]
I think we should not set the `LD_LIBRARY_PATH` to `$initdir/RUNPATH` everywhere.
The actual problem is:

``` sh
install_missing_libraries() {
    # install possible missing libraries
    for i in $initdir/{sbin,bin}/* $initdir/lib/systemd/*; do
        inst_libs $i
    done
}
```

So, maybe we should set the `LD_LIBRARY_PATH` here. I'm not sure.

Unrelated to this issue:
we don't install dynamically loaded libraries.
For example:

```
src/locale/localed.c:        dl = dlopen("libxkbcommon.so.0", RTLD_LAZY);
```

ouch

**Comment by fsateler** [comment]
Why not everywhere? Could there be a problem?

**Comment by evverx** [comment]
That's a good question. I don't know:)

What if the output of `LD_LIBRARY_PATH=$initdir/RUNPATH ldd ...` differ from the output of `ldd ...`? Can we install the wrong file (or don't install the right file)?
