### ISSUE TITLE
systemd-boot hangs on keypress

### ISSUE THREAD

**Issue by r0l1** [systemd/systemd#3632]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 230
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Possibility to boot Windows (Dual Boot)
### In case of bug report: Unexpected behaviour you saw

> systemd-boot freezes as soon as a key is pressed
### In case of bug report: Steps to reproduce the problem

> Press a key in systemd-boot on a Razer Blade 2016

**Comment by r0l1** [comment]
I installed the rEFInd boot manager and didn't have any problems with it. Is there a possibility to obtain a log from systemd-boot? I am willing to fix this problem. Any hints where to start digging in the source code? How and where does systemd-boot handle keyboard inputs? Thanks!

**Comment by medhefgo** [comment]
Do you have a Steam Controller? I recently got one and it seems that whenever it is plugged in, systemd-boot will hang shortly after first keypress. If it's no plugged in, it works fine. Grub does not exhibit this behavior.

**Comment by r0l1** [comment]
No, there is nothing plugged into the laptop :/

**Comment by medhefgo** [comment]
I looked into the code and the culprit seems to be https://github.com/systemd/systemd/blob/master/src/boot/efi/console.c#L98

If I force the else branch to execute unconditionally, everything works fine. Seems like WaitForKeyEx is borked in my UEFI.

@kaysievers Any thoughts on this?

**Comment by r0l1** [comment]
I recompiled the systemd package and forced the else branch to execute unconditionally. Now everything works as expected! Thank you!

How should we continue to fix this upstream? What does the **TextInputEx_** define? Is there a possibility to determine faulty behaviour and force the else branch?
