### ISSUE TITLE
systemctl set-default does not override a run-time setting

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#3645]
```
$ ln -s multi-user.target /run/systemd/generator.early/default.target
$ systemctl get-default --root=/
multi-user.target
$ systemctl set-default --root=/ graphical.target
$ systemctl get-default --root=/
multi-user.target
```

I think we should at least warn...

**Comment by arvidjaar** [comment]
OTOH run-time goes away on reboot, and this is primary point in time when `default.target` is evaluated. So in a sense, it _does_ work. It is true that until reboot we get misleading output.

**Comment by keszybz** [comment]
If you understand how this is all implemented, then yeah, it's all straightforward. But `set-default`/`get-default` are for the end-user.
