### ISSUE TITLE
networkd bridge netdev creation problems

### ISSUE THREAD

**Issue by RobinMcCorkell** [systemd/systemd#3648]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux ARM (armv7h on Odroid C1+, with Linux 3.10.96-7-ARCH)
### Bug report

Creating a bridge with iproute2 (`ip link add br0 type bridge`) works as expected, and when interfaces are joined to the bridge packets are correctly switched and all network segments can communicate. Doing a similar thing with networkd:

```
[NetDev]
Name=br0
Kind=bridge
```

This results in an interface being created that is seemingly identical to the one created with iproute2, however joining any interfaces to it results in problems, where network segments cannot communicate and the bridge interface cannot receive packets. Strangely, setting the bridge to promiscuous mode fixes it partially, with the bridge being able to receive packets again (network segment communication was not tested).

In the journal, the following message is seen:

```
systemd-networkd[332]: br0: Bridge parameters could not be set: Operation not supported
```

I also tested this on x86_64, systemd 230 with Linux 4.5.7-1-ck on Arch, and could not reproduce, so it's either the older kernel or the armv7h architecture.

**Comment by ssahani** [comment]
`systemd-networkd[332]: br0: Bridge parameters could not be set: Operation not supported`

This message is shown from the callback when we try to set bridge property and it fails.
It seems like networkd is falling to set some bridge property. Could you figure out which property
Or it just bridge with no property?

**Comment by RobinMcCorkell** [comment]
I am not setting any properties on the bridge, so the defaults are in use.

**Comment by svvac** [comment]
Ran into the same issue. In my case, the kernel was denying auto-loading of the `bridge` module. Manually `modeprobe`ing it solved the issue (add it to `/etc/modules-load.d/*.conf` to load it on boot).

If you want to check if that's the issue in your case:

```
# dmesg | tail
...
[ 4092.402251] grsec: denied kernel module auto-load of bridge by uid 193
...
```

(using `Linux 4.6.5.201607312210-1-grsec` with `systemd 231` on Arch Linux)

**Comment by poettering** [comment]
@Xenopathic do you have grsec enabled in your kernel, as @svvac suggested?

**Comment by RobinMcCorkell** [comment]
No grsec: `3.10.103-2-ARCH`. No dmesg logs regarding grsec either. The `bridge` module is being loaded properly, it looks like some sort of disconnect between userspace and the kernel.

Messing around manually with the broken bridge sometimes gives this dmesg log:

```
A link change request failed with some changes committed already. Interface br0 may have been left with an inconsistent configuration, please check.
```

**Comment by poettering** [comment]
the kernel appears ancient. Any chance you can retry with something more current?

**Comment by RobinMcCorkell** [comment]
Not possible unfortunately, I'm restricted by Hardkernel's releases for the ODroid C1+. It could quite possibly be the kernel and/or something Hardkernel/AMLogic added to the kernel that has caused the issue, but it doesn't explain why creating a bridge directly with `ip link add ...` works while networkd doesn't.

**Comment by graysky2** [comment]
I am experiencing this same problem on an Odroid C2 (kernel version 3.14.79).

By contrast, on a Raspberry Pi running a newer kernel, the bridge setup works just fine.

```
Dec 21 11:29:57 droid systemd[1]: Starting Network Service...
Dec 21 11:29:58 droid systemd-networkd[232]: br0: netdev ready
Dec 21 11:29:58 droid systemd-networkd[232]: Enumeration completed
Dec 21 11:29:58 droid systemd[1]: Started Network Service.
Dec 21 11:29:58 droid systemd-networkd[232]: br0: IPv6 enabled for interface: Success
Dec 21 11:29:58 droid systemd-networkd[232]: br0: Bridge parameters could not be set: Operation not supported
Dec 21 11:29:58 droid systemd-networkd[232]: br0: Could not bring up interface: Invalid argument
Dec 21 11:29:58 droid systemd-networkd[232]: eth0: Could not join netdev: Invalid argument
Dec 21 11:29:58 droid systemd-networkd[232]: eth0: Failed
```

**Comment by poettering** [comment]
> Not possible unfortunately, I'm restricted by Hardkernel's releases for the ODroid C1+. It

Sorry, but we only support kernels newer than 3.13, see README. I am sorry this isn#t available for your device, but we don#t rally consider that a systemd problem.

Moreover, we generally don't work around kernel bugs in systemd, but instead expect people to upgrade their kernels instead. I am sorry if you cannot do that, but given that this is fixed with newer kernel versions I will close this now. Please upgrade your kernel.

**Comment by graysky2** [comment]
@poettering - This problem persists on 3.16.x series of kernels for this hardware.
```
% uname -r
3.16.57-2-ARCH
```

Requesting a reopen.

**Comment by p5n** [comment]
```
systemd-networkd[456]: brlan: netdev could not be created: Operation not supported
```
on 5.2.13-1-ARCH, armv7l

**Comment by p5n** [comment]
And then
```
Assertion 'ifindex' failed at src/network/networkd-link.c:729, function link_get(). Aborting.
```

**Comment by p5n** [comment]
Resolved it by
```
[Service]
ExecStartPre=-/bin/ifconfig brlan down
ExecStartPre=-/bin/brctl delbr brlan
```
This is really strange behaviour considering that nobody except systemd can create brlan interface.

**Comment by yuwata** [comment]
@p5n Which version of systemd do you use?

**Comment by p5n** [comment]
reproduced with
systemd 245.6-8, archlinux, x86_64.
interesting magic is that it looks like brlan does not exist before networkd starting:
```
systemd[1]: Starting Network Service...
ifconfig[437]: brlan: ERROR while getting interface flags: No such device
brctl[501]: bridge brlan doesn't exist; can't delete it
systemd-networkd[505]: brlan: netdev ready
systemd-networkd[505]: Enumeration completed
systemd[1]: Started Network Service.
```
but it helps somehow

**Comment by yuwata** [comment]
@p5n I am not sure what is your problem, but if you have any problems in networkd, please file that as a new issue with your configs and debugging logs.
