### ISSUE TITLE
RFE: support drop-in directories for .network files

### ISSUE THREAD

**Issue by Sufflope** [systemd/systemd#3655]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 229
### Used distribution

> Fedora 24

Hello,

would it be possible to have the same kind of /etc/systemd/system/_service_.d/ drop-ins to override some settings of a .network file without copying it?

Example use case: I have nspawn containers, I want them to use some DNS server but not Google's nor the uplink ones. I am, aside from that, perfectly happy with /usr/lib/systemd/network/80-container-ve.network settings.

If I add an /etc/systemd/network/80-container-ve.network I need to copy /usr/lib's one because it will be completely overriden ; if there are further improvements in /usr/lib's file I need to somehow track them and change my /etc override accordingly.

With a drop-in system I could add (e.g.) an /etc/systemd/network/80-container-ve.network.d/dns.conf file just to put the [DHCPServer] section with my custom DNS.

**Comment by poettering** [comment]
If figure supporting this should be relatively easy, it's just making use of config_parse_many() instead of config_parse().
