### ISSUE TITLE
systemd - udev rule not fired in FC24 (worked on FC23)

### ISSUE THREAD

**Issue by wiesl** [systemd/systemd#3657]
### Submission type
- [X ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd-udev-229-8.fc24.armv7hl

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

FC24
### In case of bug report: Expected behaviour you didn't see

I had the following configuration on FC23 (systemd-222-14.fc23) which worked perfectly (ARM system):

cat /etc/udev/rules.d/8-usb-modem.rules
# Huawei E169

SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10", ENV{ID_USB_INTERFACE_NUM}=="00" SYMLINK+="ttyUSB-modem-at"
SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10", ENV{ID_USB_INTERFACE_NUM}=="01" SYMLINK+="ttyUSB-modem-aux"
SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10", ENV{ID_USB_INTERFACE_NUM}=="02" SYMLINK+="ttyUSB-modem-third"

After upgrade to FC24 (systemd-udev-229-8.fc24.armv7hl) I have the problem that ttyUSB-modem-at link is not set.

lrwxrwxrwx 1 root root           7 Jul  1 18:49 ttyUSB-modem-aux -> ttyUSB2
lrwxrwxrwx 1 root root           7 Jul  1 18:49 ttyUSB-modem-third -> ttyUSB3

I tried also:
# OK:

KERNEL=="ttyUSB1", SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10" SYMLINK+="ttyUSB-modem-at"
# NOT OK:

KERNEL=="ttyUSB1", DRIVERS=="option", SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10" SYMLINK+="ttyUSB-modem-at"

So when something more specific correct filter is added it doesn't work any more (I tried several different more distinct filters):

I tried already: udevadm info --attribute-walk /dev/ttyUSB1 which looks good

First lines are:

   looking at device '/devices/platform/soc@01c00000/1c14000.usb/usb3/3-1/3-1.1/3-1.1:1.0/ttyUSB1/tty/ttyUSB1':
     KERNEL=="ttyUSB1"
     SUBSYSTEM=="tty"
     DRIVER==""

   looking at parent device '/devices/platform/soc@01c00000/1c14000.usb/usb3/3-1/3-1.1/3-1.1:1.0/ttyUSB1':
     KERNELS=="ttyUSB1"
     SUBSYSTEMS=="usb-serial"
     DRIVERS=="option1"
     ATTRS{port_number}=="0"

   looking at parent device '/devices/platform/soc@01c00000/1c14000.usb/usb3/3-1/3-1.1/3-1.1:1.0':
     KERNELS=="3-1.1:1.0"
     SUBSYSTEMS=="usb"
     DRIVERS=="option"
     ATTRS{authorized}=="1"
     ATTRS{bAlternateSetting}==" 0"
     ATTRS{bInterfaceClass}=="ff"
     ATTRS{bInterfaceNumber}=="00"
     ATTRS{bInterfaceProtocol}=="ff"
     ATTRS{bInterfaceSubClass}=="ff"
     ATTRS{bNumEndpoints}=="03"
     ATTRS{interface}=="Data Interface"
     ATTRS{supports_autosuspend}=="1"

This one looks also good:

ls -l /dev/serial/by-id/usb-ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ_HUAWEI_Mobile-if00-port0
lrwxrwxrwx 1 root root 13 Jul  1 18:49 /dev/serial/by-id/usb-ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ_HUAWEI_Mobile-if00-port0 -> ../../ttyUSB1

I don't think I did anything wrong so it looks to be a bug.

Any ideas?

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1352685
### In case of bug report: Unexpected behaviour you saw

Symlink not set
### In case of bug report: Steps to reproduce the problem

See above

**Comment by poettering** [comment]
hmm, that rule appears to miss a check for SUBSYSTEMS="usb", because otherwise it's not clear what the idVendor attribute checks relate to. The rule looks borked regarding that. Does it work if you fix that?

**Comment by wiesl** [comment]
No, it doesn't work:
SUBSYSTEMS="usb", SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10", ENV{ID_USB_INTERFACE_NUM}=="00" SYMLINK+="ttyUSB-modem-at"

**Comment by arvidjaar** [comment]
> `SUBSYSTEMS="usb"`

You comparison, not assignment.

**Comment by wiesl** [comment]
Sorry, but still not ok:
SUBSYSTEMS=="usb", SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ATTRS{product}=="HUAWEI Mobile", ATTRS{version}==" 1.10", ENV{ID_USB_INTERFACE_NUM}=="00" SYMLINK+="ttyUSB-modem-at"

**Comment by wiesl** [comment]
Bug in systemd: See https://bugzilla.redhat.com/show_bug.cgi?id=1357822
