### ISSUE TITLE
`systemctl --user enable` fails if unit file is a symlink

### ISSUE THREAD

**Issue by dpc** [systemd/systemd#3660]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

I'm not really sure if it's a bug, or unimplemented behavior.
### systemd version the issue has been seen with

Tried 230 (archlinux) and 222 (Fedora)
### Used distribution

Archlinux, Fedora
### In case of bug report: Expected behaviour you didn't see

My unit services files are actually symlinks (I'm using GNU Stow to distribute my user unit files)

```
~/.config/systemd/user > tree -alh
.
├── [  74]  default.target.wants
│   ├── [  51]  emacs-daemon.service -> /home/dpc/.config/systemd/user/emacs-daemon.service
│   └── [  48]  gpg-agent.service -> /home/dpc/.config/systemd/user/gpg-agent.service
├── [  64]  emacs-daemon.service -> ../../../dot/spacemacs/.config/systemd/user/emacs-daemon.service
└── [  57]  gpg-agent.service -> ../../../dot/gnupg/.config/systemd/user/gpg-agent.service
```

I have to create this setup manually (with `ln -s`), and it works. I had to do it manually, as `systemctl --user enable` does not seem to like the fact the unit files are symlinks.
### In case of bug report: Unexpected behaviour you saw

```
> systemctl --user enable gpg-agent.service 
Failed to execute operation: No such file or directory
```

If the service unit is a absolute symlink, `enable` will fail with: `Failed to enable unit: Too many levels of symbolic links`.

It would be nice if symlink service files would just work.

**Comment by poettering** [comment]
This is really by design. "systemctl enable" creates and removes symlinks in order to enable/disable unit _files_. By invoking "systemctl disable" you basically say "remove all symlinks from the config dir, pointing to or named by the specified name". By invoking "systemctl enable" you basically say "find the unit file for this, and add in additional symlinks listed in its [install]" section. For the latter we do not use the symlinks we might have created earlier, simply because we shouldn't use configuration to create configuration, but only the unit files themselves.

I hope that makes sense?

**Comment by dpc** [comment]
Hmmm. I thought enabled services are symlinks in one directory (in my example `~/.config/systemd/user/default.target.wants`), and all possible services are in the other (`~/.config/systemd/user/`) and this dirs are always different. So it seemed to me `systemctl` should not really care what is the type of things in "possible services" dir. But if I'm missing something here, it's fine with me. Thanks!

**Comment by poettering** [comment]
~/.config/systemd may contain both unit files and symlinks to unit files. And often does, as usually user-written unit files are placed directly in it, while symlinks are used to hook in vendor unit files.

**Comment by zachlatta** [comment]
Any way to override this?

I use https://github.com/thoughtbot/rcm to manage my dotfiles and I have a custom unit file at `~/.dotfiles/config/systemd/user/dropbox@.service` that's symlinked to `~/.config/systemd/user/dropbox@.service` through rcm.

I'm trying to enable that unit file, but getting this error. I'd really like to continue managing this using rcm and not copy the file over.

**Comment by icolwell** [comment]
I have the exact same use case as @zachlatta which is typical of any user managing their configs. I also get the same error when trying to enable the service. 
What options do we have to work around this?

I'm running `Ubuntu 16.04.2 LTS` if that helps.

**Comment by keszybz** [comment]
This has been resolved in the mean time, and we now allow symlinked units to be enabled:
```console
$ ln -s --relative ~/bar2.service ~/.config/systemd/user/ -v
'/home/zbyszek/.config/systemd/user/bar.service' -> '../../../bar.service'
$ systemctl --user enable bar.service
Created symlink /home/zbyszek/.config/systemd/user/some.target.wants/bar.service → /home/zbyszek/.config/systemd/user/../../../bar.service.
$ cp ~/bar.service  ~/bar2.service 
$ ln -s ~/bar2.service ~/.config/systemd/user/ -v
'/home/zbyszek/.config/systemd/user/bar2.service' -> '/home/zbyszek/bar2.service'
$ systemctl --user enable bar2.service
Created symlink /home/zbyszek/.config/systemd/user/some.target.wants/bar2.service → /home/zbyszek/bar2.service.
$ systemctl --user cat bar.service bar2.service
# /home/zbyszek/.config/systemd/user/../../../bar.service
[Service]
ExecStart=/bin/echo %n

[Install]
WantedBy=some.target

# /home/zbyszek/bar2.service
[Service]
ExecStart=/bin/echo %n

[Install]
WantedBy=some.target
```

I'm not sure which version exactly has those changes (it was a bunch of commits spread out over time...).

**Comment by icolwell** [comment]
Thanks for the quick reply!

I assume this was fixed quite a while ago due to the age of @poettering's comments?
Running `dpkg -s systemd | grep Version` yields `Version: 229-4ubuntu17`. I assume the 229 corresponds to the [releases](https://github.com/systemd/systemd/releases) here on github. 229 was released on the 11th of March, 2017 so this should already be fixed right?

```bash
$ dpkg -s systemd | grep Version
Version: 229-4ubuntu17
$ ln -s ~/Documents/test.service ~/.config/systemd/user/ -v
'/home/ian/.config/systemd/user/test.service' -> '/home/ian/Documents/test.service'
$ systemctl --user enable test.service
Failed to execute operation: Too many levels of symbolic links
```
The test.service is the same as your bar.service. Anything I am missing here?

**Comment by keszybz** [comment]
I think it was later than systemd-229, which was released in February
2016. f777b4345e8c57e739bda746f78757d0fb136ac7 might be the commmit.

**Comment by whnr** [comment]
@keszybz 
> This has been resolved in the mean time, and we now allow symlinked units to be enabled:

While enabling works very well. If the original is a symlink, it gets removed when disabling.

```
$ systemctl --user enable mbsync.timer
Created symlink /home/florian/.config/systemd/user/timers.target.wants/mbsync.timer → /home/florian/.dotfiles/systemd/mbsync.timer.
$ systemctl --user disable mbsync.timer
Removed /home/florian/.config/systemd/user/timers.target.wants/mbsync.timer.
Removed /home/florian/.config/systemd/user/mbsync.timer.
$ systemctl --user enable mbsync.timer
Failed to enable unit: Unit file mbsync.timer does not exist.
```
That might lead to a bit of confusion when doing this `enable > disable > enable`. The error is clear though.

**Comment by keszybz** [comment]
@whnr the docs for `link` say "The effect of this may be undone with `disable`."
So the behaviour you are reporting seems to be by design.
