### ISSUE TITLE
please provide a firewall scripts drop-in folder

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#3661]
### Submission type

Request for enhancement (RFE)
### systemd version the issue has been seen with

230
### Used distribution

Debian
### feature request

Please provide a firewall scripts drop-in folder.

I.e. please provide a folder such as `/usr/share/netfilter-persistent/plugins.d` where one can drop arbitrary scripts which will be executed early enough during the boot process in lexical order when the netfilter-persistent.service is started.

Firewall rules ought to be load before anything might issue any network traffic and there also should be a failure condition.

Implementing this in systemd would provide a sane, secure, canonical way to get firewall scripts loaded. This is better than various sysadmins and distributions coming up with custom mechanisms and getting them wrong since all of this is non-trivial.
### existing similar implementation / alternative

There already is netfilter-persistent which is attempting to do that.
- http://manpages.org/netfilter-persistent/8
- https://anonscm.debian.org/cgit/collab-maint/iptables-persistent.git/tree/systemd/netfilter-persistent.service
- https://anonscm.debian.org/cgit/collab-maint/iptables-persistent.git/tree/netfilter-persistent
- https://packages.debian.org/de/jessie/iptables-persistent

> netfilter-persistent uses a set of plugins to load, flush and save netfilter rules at boot and halt time. Plugins can be written in any suitable language and stored in /usr/share/netfilter-persistent/plugins.d 
> 
> Plugins can be written in any language and are merely executed by netfilter-persistent with a single argument. All plugins are stored in `/usr/share/netfilter-persistent/plugins.d`.
> 
> Plugins must implement the start flush and save arguments and must not rely on additional arguments for other functionality.
> Plugins must return 0 on success and any other code on failure. 

It also has a `FLUSH_ON_STOP` option, which is disabled by default.

Overall I think, that netfilter-persistent thought this through quite well and came up with a nice mechanism. However, it is not that simple to get everything right.

netfilter-persistent bug reports:
- [netfilter-persistent loads firewall rules too late](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829640)
- [netfilter-persistent systemd service does not lock the network if netfilter-persistent wrapper is failing at system bootup](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829752)

Perhaps something could be learned from netfilter-persistent and perhaps it could be upstreamed to systemd.

**Comment by poettering** [comment]
That sounds like something to implement in netfilter/iptables, not in systemd. if you want to define a firewall simply define a service, make it pull in network-pre.target and order itself before it. all network management software orders itself after it, and hence you get the right behaviour. Actually defining a firewall unit this way is clearly out of scope for us though.

This is documented briefly on the systemd.special(7) man page. Also see https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

Anyway, closing this now, as I am very sure that systemd is not the right place to define netfilter scripts. Hope this makes sense.

**Comment by adrelanos** [comment]
Thank you for your consideration and reply!

Posted a feature request against netfilter:
`please provide a firewall scripts drop-in folder`
https://bugzilla.netfilter.org/show_bug.cgi?id=1078
