### ISSUE TITLE
[bonding] there is no xmit hash called 802.3ad

### ISSUE THREAD

**Issue by pomac303** [systemd/systemd#3662]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> current git

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> any

802.3ad is not available as a transmit hashing algorithm in either the kernel or the definitions in systemd - lets not keep it in the documentation.

```
--- a/man/systemd.netdev.xml
+++ b/man/systemd.netdev.xml
@@ -808,8 +808,7 @@
           <literal>layer2</literal>,
           <literal>layer3+4</literal>,
           <literal>layer2+3</literal>,
-          <literal>encap2+3</literal>,
-          <literal>802.3ad</literal>, and
+          <literal>encap2+3</literal> and
           <literal>encap3+4</literal>.
           </para>
         </listitem>

```

**Comment by poettering** [comment]
Any chance you can file a proper PR for this? If so we can just merge it and it gets attributed to you and everything!

**Comment by poettering** [comment]
@ssahani this might be something for you, btw?

**Comment by ssahani** [comment]
Indeed PR #3666 is waiting.
