### ISSUE TITLE
networkd ignores unsolicited router advertisements

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#3663]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Debian sid

Forwarding this from https://bugs.debian.org/815793 (by Marc Haber). I'm afraid I can't say much about this 
as I don't really understand what this is about. @teg, do you?

systemd 229 seems to ignore unsolicited router advertisements. This
breaks, for example, prefix changes. And it prevents the self-healing
characteristics of lost router solicitations.

tcpdump logs this:
14:41:40.062484 7e:79:61:31:55:28 > 33:33:00:00:00:01, ethertype IPv6 (0x86dd), length 294: fe80::1 > ff02::1: ICMP6, router advertisement, length 240

ip -6 r shows this:
[10/507]mh@banana:~$ ip -6 route
2a01:238:4071:3282::/64 dev eth0  proto kernel  metric 256  pref medium
fe80::/64 dev eth0  proto kernel  metric 256  pref medium
[11/508]mh@banana:~$ 

"see, no default route"

setting accept_ra to 1 for eth0 manually (something which is no longer
possible with systemd 229 via systemd configuration) brings the system
online when the next router advertisements comes in:

[3/503]mh@banana:~$ ip -6 r
2a01:238:4071:3282::/64 dev eth0  proto kernel  metric 256  pref medium
fe80::/64 dev eth0  proto kernel  metric 256  pref medium
default via fe80::1 dev eth0  proto ra  metric 1024  expires 1791sec hoplimit 64 pref high
[4/504]mh@banana:~$

[end quote]

We currently carry a patch in Debian to revert https://github.com/systemd/systemd/commit/fe30727643a7 to go back to letting the kernel handle RAs again. Issue #2572 is already fixed, this is the second blocker, and I'll file the third in a moment.

**Comment by poettering** [comment]
the code in 230 is quite different. Can you check if it works there?

**Comment by martinpitt** [comment]
I built test packages with the upstream behaviour and asked for testing that and a debug log at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815793#33

**Comment by martinpitt** [comment]
I tried to understand/reproduce this in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815793#59 (including networkd debug log and tcpdump), with 229, 230, and 230+patch to revert to letting the kernel handle RA/ndisc. In all cases networkd picked up the unsolicited router advertisement from radvd and added the new address. So I cannot confirm the bug myself.

So I guess my test case isn't exactly what Marc saw, or the kernel/networkd behavior changed, or this is hw specific. I asked Marc about further info and testing the upstream 230 behaviour with logs.

I'll handle this in the downstream bug and close this for the time being. I'll reopen once we have a reproducer and an understanding of this.
