### ISSUE TITLE
networkd does not retry IPv6 router solicitations

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#3664]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Debian unstable

Forwarding this from https://bugs.debian.org/815884 (by Marc Haber). I'm afraid I can't say much about this 
as I don't really understand what this is about. @teg, do you?

[begin quote]

systemd 229 has taken over the code to send and accept router solicitations in IPv6. Unfortunately, it does only send a single RS immediately after the link comes up, and does not retry if no RA comes in.

Unfortunately, bigger switches do not immediately begin forwarding packets after a link was brought up but take a few seconds before the port actually enters forwarding state. On Cisco Catalyst Switches in default configuration, this typically takes 30 seconds until the port is set to spanning-tree portfast. On HP ProCurve switches, it takes 6 to 10 seconds unless LACP and STP negotiation is completed. LACP can be turned off, STP cannot.

When a system running IPv6 with systemd 229 is connected to such a switch, the system doesn't get IPv6 on startup, and it doesn't acquire IPv6 on the next regular RA because of issue #3663. This makes IPv6 completely unuseable.

With systemd 229, if one forces the switch port in the forwarding state by inserting a dumb switch between the "big" switch and the Linux system, one sees the RA sent by systemd, and IPv6 works. But one cannot possible use dumb switches just to fix systemd's shortcomings.

[end quote]

We currently carry a patch in Debian to revert https://github.com/systemd/systemd/commit/fe30727643a7 to go back to letting the kernel handle RAs again. Issue #2572 is already fixed, this is another second blocker, and issue #3663 is the third.

**Comment by poettering** [comment]
the code regarding this in 230 is quite different, could you please check things with that?

**Comment by poettering** [comment]
also, could you pleas provide some log output regarding this, for example with debugging enabled? (i.e. with SYSTEMD_LOG_LEVEL=debug set for systemd-networkd.service)? Also please provide a reproducer.

**Comment by martinpitt** [comment]
I tried to understand/reproduce this in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815884#23  (including networkd debug log and tcpdump), with 229, 230, and 230+patch to revert to letting the kernel handle RA/ndisc. In all three cases router solicitations are only being sent three times at the start of networkd, and never again. So while I _can_ confirm that networkd does not re-try router solicitations (only DHCPv6 solicitations), I _cannot_ confirm that the kernel would re-try them.

So I guess my test case isn't exactly what Marc saw, or the kernel/networkd behavior changed, or this is hw specific. I asked Marc about further info and testing the upstream 230 behaviour with logs.

**Comment by martinpitt** [comment]
I'll handle this in the downstream bug and close this for the time being. I'll reopen once we have a reproducer and an understanding of this.
