### ISSUE TITLE
Systemd - Power Management Enhancement

### ISSUE THREAD

**Issue by dmedri** [systemd/systemd#3668]
### Submission type
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 2.30
### Used distribution

> arch

Systemd, we know, it's like swiss army knife, with many tools for different contexts. It already handle poweroff/suspend, it could be useful extend pm (power-management) functionalities. Distributions made their own choices (eg. https://wiki.archlinux.org/index.php/Power_management#Power_management_with_systemd), but an uniform solutions across distributions should be helpful to users.
# Use cases

Joe has a laptop. He wants some smart utilities to track wackups and have tips for a better use of battery. PowerTop is available, but he would be happy with something more updated and systemd-ready. A shared lib with a desktop gui could help him.

Pat is a data center sysadmin. She wants lowering power consumption, tracking wackups in all running machines on the available servers. Collect stats for all machine and have a view of problems could help her.

systemd-pm?

**Comment by poettering** [comment]
I am not sure what you are suggesting this new component would do? Why would a user have to change "power management settings" anyway (for whatever that's supposed to be?)

**Comment by zdzichu** [comment]
There's `tuned` if you want to switch between different sysctls&related profiles. Various powersaving settings often have cost if increased latency or decreased throughput, that's why it's admin job to select between different tradeoffs.

**Comment by dmedri** [comment]
Dear @poettering , thanks for the questions. Trying to answer these, I gathered a series of notes and considerations for broader needs and a more generalized solution. I close this issue, to open another one in the next few days.

Thanks @zdzichu for your note.
