### ISSUE TITLE
Starting services inside tmux makes systemd forget initiator

### ISSUE THREAD

**Issue by Ekleog** [systemd/systemd#3675]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian stretch/sid
### Expected behaviour

When starting a service with `ExecStart=/usr/bin/tmux -2  new-session -d -s 'servicename' 'TERM=screen-256color /srv/servicename/start'` (in order to have easy access to the console after that), the service should be considered to be started
### Unexpected behaviour

Instead, if a tmux instance was already running, the process will be spawned by the tmux instance inside the first cgroup, the second cgroup will thus be empty, and systemd will regard the service launch as having failed.
### Steps to reproduce the problem

See "Expected behaviour".

Just in case, I believe this should be closed as WONTFIX, but wanted to let you know there would be a use case for this.

**Comment by poettering** [comment]
Well, it appears to me that what you are doing there is not really supposed to be done in a system service (as tmux manages user logins, afaik, not system services). That said, systemd is actually fine tracking services that have no running processes if you use RemainAfterExit=yes. Hence, if you set that you should get the behaviour you want.

Closing hence.
