### ISSUE TITLE
unit syntax validation command

### ISSUE THREAD

**Issue by nathwill** [systemd/systemd#3677]
it'd be great if systemd supported a unit command for validating the syntax of a specified unit (e.g. `systemctl validate blah.unit` or `systemctl check-unit blah.unit`), with 0 exit codes if the unit is well-formed, and non-zero if there are unrecognized options or invalid syntax. ideally, this could take an optional path to a unit-file (e.g. `systemctl validate -f /tmp/blah.unit`). the specific use-case i'm interested in would be for use with config management tools like chef or puppet, so units could be pre-validated before being installed/updated, and triggering restarts/reloads of potentially malformed units, but i imagine this would be useful for pre-checking manual changes as well.
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

all
### Used distribution

Fedora 24

**Comment by mbiebl** [comment]
@nathwill There is `systemd-analyze verify <FILES>`
See the corresponding man page. Is there anything missing?

**Comment by nathwill** [comment]
no, that's delightful! thanks for clearing that up, i didn't realize that systemd-analyze did anything other than profiling, and apparently my google-fu wasn't strong enough to dig it up. thanks a bunch!

**Comment by 3ronco** [comment]
Would be nice if `systemd-analyze verify ...` could be used for networkd files (*.network | *.netdev) as well.

**Comment by eMPee584** [comment]
Wouldn't it be nice if `systemd-analyze verify` came up as a hint in `systemctl status` when a bad unit file / override is at fault?
