### ISSUE TITLE
semaphore setup should be verbose

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#369]
Could V=1 be please passed to distcheck command in semaphore?

Such that test failures output log on the stdout with information about failures:

E.g. cause otherwise
https://semaphoreci.com/systemd/systemd/branches/pull-request-368/builds/1

is not very useful, as one cannot in fact poke ./test-suite.log

**Comment by zonque** [comment]
Done.

Also, I disabled the llvm/clang test for now, as we've gotten too many false positives build failures.
