### ISSUE TITLE
Propagate $TERM from PID 1 to bash prompt to make nspawn better

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#3697]
- [x] Bug report
### systemd version the issue has been seen with

> 230
### Used distribution

> Debian stretch

Steps to reproduce. Let's assume we have some chroot environment in /str with systemd (debian stretch with systemd 230 in my case). Let's also assume we work is some x terminal emulator, in my case this is konsole (sic!) from KDE. Now we type `systemd-nspawn -D /str /sbin/init`. Then we login into this container and then start some curses-based app, for example, nano. Then we exit from it.

Actual behavior. We will see that nano "ate" some output of systemd boot process. I. e. nano ate some info that was present in terminal.

Expected behavior. nano should not do this.

When I just start nano from konsole directly it doesn't eat anything.

It seems the cause is $TERM. If I type `export TERM=xterm` before running nano, everything is okey. So, systemd should propagate $TERM from PID 1 to bash prompt.

Possibly related issue: #3115.

**Comment by poettering** [comment]
I figure nspawn could pass TERM to PID 1, and the getty generator could read TERM from its PID 1 and set it for gettys started on the container's console.

**Comment by safinaskar** [comment]
It seems nspawn already passes TERM to PID 1

**Comment by poettering** [comment]
Fix waiting in #3820.
