### ISSUE TITLE
wall messages are not shown

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#3700]
Version: 230
Distro: Debian unstable

On a server where multiple users are logged in, the wall message is not shown to other users if I run
`systemctl poweroff`. Neither for locally logged in users nor users that are logged in via SSH.

To reproduce the problem, log into your system as root and remote via SSH as unprivileged user.
If you now initiate a shutdown as root, the only output you'll get for the user logged in via SSH is:

```
$ Connection to 192.168.179.69 closed by remote host.
Connection to 192.168.179.69 closed.
```

**Comment by poettering** [comment]
I am pretty sure this was addressed by 3d0ef5c7e00155bc74f6f71c34cad518a4ff56ba. Closing
