### ISSUE TITLE
[RFE] zsh completions should properly account for the --user flag

### ISSUE THREAD

**Issue by ianks** [systemd/systemd#3703]
Currently, when trying to auto-complete service files in zsh using the `--user` flag, units are not listed using the `--user` flag (`systemctl list-units --user`). This means that the completions are incorrect, and the correct completions are unavailable for `--user` service files. 

Would it be possible to have the completions properly list user units for completions?

**Comment by shibumi** [comment]
Hello,
I don't think this is a bug. For me it's working fine. Your syntax is wrong.
You have to write the `--user` flag right after `systemctl`.

Therefore the right syntax is: `systemctl --user <the usual stuff behind>`

Here is a screenshot of my zsh:
![screenshot](https://paste.archlinux.de/zGH8/)
