### ISSUE TITLE
Boot timeout while waiting for dev-mapper-vg\swap.device

### ISSUE THREAD

**Issue by stuk0v** [systemd/systemd#3704]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_

> systemctl --version
> systemd 226
> 
> Gentoo
> 
> Normally to "swapon" the /dev/mapper/vg-swap
> 
> During boot the system waits 1,5 mins to time out as it wont swapon the dev mapper swap device. The system boots without swap partition.
> When I log in, i can normally do a "swap -a" or "swapon /dev/mapper/vg-swap" without any issues.

Kernel command line from /boot/grub2/grub.cfg:
`linux  /vmlinuz-4.4.6-gentoo.old root=/dev/mapper/gentoovg-root ro single init=/usr/lib/systemd/systemd crypt_root=/dev/sda2 dolvm real_root=/dev/mapper/gentoovg-root rootfstype=ext4`

journalctl -b output:
https://bpaste.net/show/2cce4046ce4a

**Comment by poettering** [comment]
you appear to be using LVM. if so, maybe your LVM was built without proper udev rules enabled? either way, marking devices ready is a job for LVM, not systemd. Please ask the LVM maintainers of your distro for help, as we have very little expertise with LVM only.
