### ISSUE TITLE
udev - device renaming has no fall-back when kernel driver does not support naming

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#3708]
Bug report
Arch systemd 230-6

Some kernel-space device drivers fail to support predictable network  interface names.  In that event, the rules file,
 /usr/lib/udev/rules.d/80-net-setup-link.rules
will fail to set a predictable interface name, with the usual consequences.

This problem is seen with the Broadcom 44xx/47xx 10/100 PCI ethernet driver, "b44", and has been seen in the past with some wireless drivers.  See, in particular,
https://bbs.archlinux.org/viewtopic.php?pid=1251212#p1251212
Ironically, the "ssb" driver no longer seems to have this problem.

Regardless which driver might fail to provide predictable naming support, the standard rules file should provide a practical fall-back predictable naming.

To this end, referring to Tom Gundersen's suggestion cited, the following line could be added toward the end of the 80-net-setup-link.rules file:
NAME=="", ENV{ID_NET_NAME_MAC}!="", NAME="$env{ID_NET_NAME_MAC}"

Alternatively, the built-in function "net_setup_link", from "udev-builtin-net_setup_link.c", should itself provide a reliable fall-back predictable naming.

**Comment by poettering** [comment]
Let's close this, we nowadayssupport b44 bus perfectly.
