### ISSUE TITLE
Add FusionIO device (/dev/fio) persistent-storage udev rule

### ISSUE THREAD

**Issue by bwann** [systemd/systemd#3718]
### Submission type
- [X] Bug report
- [] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> CentOS 7.2.1511
### In case of bug report: Expected behaviour you didn't see

> Expected to see `/dev/disk/by-uuid` symlinks for filesystems on Fusion-IO flash cards on boot
### In case of bug report: Unexpected behaviour you saw

> Installed CentOS 7 on system with a sole Fusion-IO card as its storage device (root-on-flash). On boot, kernel enumerates `/dev/fio` devices but fails to mount the root '/' filesystem because it can't find the expected `/dev/disk/by-uuid/<uuid>` entry.

`Warning: /dev/disk/by-uuid/6b37b126-b644-4381-a4f7-07a556fcea0e does not exist`

There are valid filesystems on the flash card with labels and UUID, I can mount them by hand from the emergency shell.

```
dracut:/run/udev# blkid
/dev/fioa1: SEC_TYPE="msdos" UUID="A354-A006" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="c37bf952-68eb-4b12-a552-d6f610dcdb67"
/dev/fioa2: LABEL="/" UUID="6b37b126-b644-4381-a4f7-07a556fcea0e" TYPE="ext4" PARTLABEL="primary" PARTUUID="c4ad6293-f1cd-41ae-a112-05bce157556b"
/dev/fioa3: LABEL="/fast1" UUID="6008f2bc-3553-4428-9733-46316b7d7c1b" TYPE="xfs" PARTLABEL="primary" PARTUUID="a09e2cd0-4754-4184-bb80-0fccd764273b"
/dev/fioa4: LABEL="/fast2" UUID="4d9d808f-9c09-4597-82b6-88dc38142507" TYPE="xfs" PARTLABEL="primary" PARTUUID="708354a3-e0a6-46cd-a700-861479a0b982"
/dev/fioa5: LABEL="swap" UUID="fc8fa497-b749-4f91-b99a-f8707fe3baef" TYPE="swap" PARTLABEL="primary" PARTUUID="ab437085-c687-4db6-84e4-2515ea4c47a5"
/dev/fioa6: LABEL="/data0/" UUID="1fdb631e-d472-497b-a7e0-41fa499f6a34" TYPE="xfs" PARTLABEL="primary" PARTUUID="d95c3a65-eb61-41a2-95a5-fa67ea481c32"

dracut:/run/udev# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-4.0.9-61_xzzy2 root=UUID=6b37b126-b644-4381-a4f7-07a556fcea0e ro crashkernel=128M console=tty0 biosdevname=0 net.ifnames=0 console=ttyS1,57600
```
### In case of bug report: Steps to reproduce the problem

> On a system with a Fusion IO device, run `udevadm test $(udevadm info -q path -n /dev/fioa)`. Nothing sets up `/dev/disk/{by-uuid, by-label, by-id}` links.

Or, install CentOS 7 on a system with only a Fusion IO flash device. On first boot after installation, dies like this:

```
[   86.485934] fioinf Fusion-io ioScale 3.20TB 0000:02:00.0: Creating block device fioa: major: 252 minor: 0 sector size: 4096...
[   86.491919]  fioa: fioa1 fioa2 fioa3 fioa4 fioa5 fioa6
[   86.499531] <6>fioinf Fusion-io ioScale 3.20TB 0000:02:00.0: Attach succeeded.
[  209.248204] dracut-initqueue[519]: Warning: dracut-initqueue timeout - starting timeout scripts
[  209.762088] dracut-initqueue[519]: Warning: dracut-initqueue timeout - starting timeout scripts

dracut:/# ls -l /dev/disk/by-uuid
ls: cannot access /dev/disk/by-uuid: No such file or directory

dracut:/# ls -l /dev/disk
ls: cannot access /dev/disk: No such file or directory

dracut:/# ls -l /dev/fio*
brw-rw---- 1 root disk 252, 0 Jul 12 01:09 /dev/fioa
brw-rw---- 1 root disk 252, 1 Jul 12 01:09 /dev/fioa1
brw-rw---- 1 root disk 252, 2 Jul 12 01:09 /dev/fioa2
brw-rw---- 1 root disk 252, 3 Jul 12 01:09 /dev/fioa3
brw-rw---- 1 root disk 252, 4 Jul 12 01:09 /dev/fioa4
brw-rw---- 1 root disk 252, 5 Jul 12 01:09 /dev/fioa5
brw-rw---- 1 root disk 252, 6 Jul 12 01:09 /dev/fioa6
```

The fix seems to be just adding `fio*` to `60-persistent-storage.rules`
https://github.com/systemd/systemd/blob/master/rules/60-persistent-storage.rules#L9

Once I did this the system was able to add entries to `/dev/disk/` and boot properly.

Example:

```
KERNEL!="loop*|mmcblk*[0-9]|msblk*[0-9]|mspblk*[0-9]|fio*|nvme*|sd*|sr*|vd*|xvd**
|bcache*|cciss*|dasd*|ubd*", GOTO="persistent_storage_end"

dracut:/usr/lib/udev/rules.d# ls -l /dev/disk
ls: cannot access /dev/disk: No such file or directory

dracut:/usr/lib/udev/rules.d# udevadm trigger
calling: trigger
device-enumerator: scan all dirs
  device-enumerator: scanning /sys/bus
  device-enumerator: scanning /sys/class

dracut:/usr/lib/udev/rules.d# 
[  OK  ] Found device /dev/disk/by-uuid/6b37b126-b644-4381-a4f7-07a556fcea0e.
         Starting File System Check on /dev/...6-b644-4381-a4f7-07a556fcea0e...
[  OK  ] Started File System Check on /dev/d...126-b644-4381-a4f7-07a556fcea0e.

dracut:/usr/lib/udev/rules.d# ls -l /dev/disk/by-uuid
total 0
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 1fdb631e-d472-497b-a7e0-41fa499f6a34 -> ../../fioa6
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 4d9d808f-9c09-4597-82b6-88dc38142507 -> ../../fioa4
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 6008f2bc-3553-4428-9733-46316b7d7c1b -> ../../fioa3
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 6b37b126-b644-4381-a4f7-07a556fcea0e -> ../../fioa2
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 A354-A006 -> ../../fioa1
lrwxrwxrwx 1 root 0 11 Jul 12 23:00 fc8fa497-b749-4f91-b99a-f8707fe3baef -> ../../fioa5
```

**Comment by poettering** [comment]
is /dev/fioXYZ an upstream kernel thing?

**Comment by poettering** [comment]
If the "fio" driver is in the upstream kernel we can certainly apply the change, but please file a PR for that, thanks!

**Comment by bwann** [comment]
I believe it's a module provided by the vendor :/

**Comment by arvidjaar** [comment]
I think black/white listing should be done in separate rule and should just set UDEV_DISABLE_PERSISTENT_STORAGE_RULES_FLAG or similar now that we have it. This will allow vendors to extend white lists by shipping udev rules which is not really possible now.

Except this requires reverse logic - no persistent rules unless some flag is set. We can probably reuse the above by setting it to `0` for white list.

**Comment by poettering** [comment]
If this is a proprietary kernel module then Fusion should also ship the matching udev rules along with it, that invoke ata_id or whatever is necessary and create the appropriate symlinks.

I hope it's understandable if we don't want to ship support for that upstream. Closing.
