### ISSUE TITLE
Systemd can't enable/disable units when /etc/systemd/system doesn't exist

### ISSUE THREAD

**Issue by tmrts** [systemd/systemd#3722]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230
> _NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Coreos v1097.0.0
### In case of bug report: Expected behaviour you didn't see

When there is no `/etc/systemd/system`, enabling/disabling a service should work if it's a service systemd is running.
### In case of bug report: Unexpected behaviour you saw

> Failed to execute operation: No such file or directory

`strace` shows the fs calls to use `/etc/systemd/system` and creating the directory
solves the error.
### In case of bug report: Steps to reproduce the problem

With a system that doesn't use `/etc/systemd/system`,

> `systemctl enable <service>`

cc @alban @lucab

**Comment by poettering** [comment]
So i tried this here and it worked just fine. how does the [Install] section of your unit look like precisely? Can you provide the relevant output of "strace"?

The mkdir_parents() is definitely there, right before we try to create a symlink:

https://github.com/systemd/systemd/blob/master/src/shared/install.c#L417

**Comment by poettering** [comment]
OK, closing. I am pretty sure there's no bug like this here, the code is just too obvious. If you can provide a reproducer please reopen!
