### ISSUE TITLE
kernel-install does not recognize /boot/efi mountpoint

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#3736]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)

kernel-install and 90-loaderentry.install cannot cope with the ESP partition mounted on /boot/efi
and the systemd efi boot loader residing on the ESP cannot read from /boot in this case.

**Comment by julian-klode** [comment]
Hmm, what about bootctl and friends?

**Comment by keszybz** [comment]
bootctl and friends need fixing too. We recently discussed this and there's agreement to try to autodetect the location.

**Comment by keszybz** [comment]
(need fixing) …but not necessarily in this PR.
