### ISSUE TITLE
Who do I report this to??  startx/systemd/xinit issue

### ISSUE THREAD

**Issue by eyoung100** [systemd/systemd#3743]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### Systemd version:

> systemd version: 226-r2

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Distribution

> Gentoo
> 02:00.0 VGA compatible controller: NVIDIA Corporation GF116 - GeForce GTX 550 Ti                                                                                      (rev a1)
### In case of bug report: Expected behaviour you didn't see

> RFE: I'd like to be able to use startx to console switch with the binary NVIDIA driver.  I'd also like to use the graphical.target, but the same behaviour occurs.  I wrote a custom service, as described at: [X without Display Manager - Method 2](https://wiki.gentoo.org/wiki/X_without_Display_Manager#Method_2).  I can't add the Graphical.target, and use VT switching either
### In case of bug report: Unexpected behaviour you saw

> Why does this occur?
> Do graphical and display-manger services properly support passing VT numbers?

Not having said service causes the NVIDIA Binary Blob to lock up the screen, i.e permanent black screen, with only recovery possible being a hard reboot. 
### In case of bug report: Steps to reproduce the problem

> 1. Add ~amd64 to /etc/portage/package.use for x11-drivers/nvidia-drivers to install support for the nvidia-drm module.
>    1a. Whether Stable or unstable, the issue occurs in both cases.
> 2.  Add nvidia to the VIDEO_CARDS variable in make.conf
> 3. Install xorg-x11 using emerge.  This pulls in the nvidia-drivers.
> 4. Install twm to test, with emerge twm xterm
> 5. Using startx, Starts X, but Ctrl + Alt + Fn results in the behaviour I described above, in both the multi-user and graphical targets.
### Possible Fix

> 1. Writing the custom service is a nasty hack(the --login parameter supports only one user), but works, but only allows switching terminals once.  Switching from X to terminal works, but going back from the terminal to X the second time, still produces the behavior.
> 2. Switching to nouveau may fix this, but would severely cripple my adapter IMHO, which is why I'm using the nvidia-drm module, with in kernel DRM.

**Comment by keszybz** [comment]
Hi,

this is the kind of thing you should take up with gentoo. We (systemd developers) know very little about how systemd is packaged in gentoo, nvidia binary drivers, and the details of interaction between them in the gentoo setup.
