### ISSUE TITLE
systemd-networkd can't configure interface if dhcp server does not provide routers

### ISSUE THREAD

**Issue by Flow86** [systemd/systemd#3752]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 216, 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> yocto
### In case of bug report: Expected behaviour you didn't see

> networkctl status -a should show "routable (configured)" even if no routes have been received by dhcp server
### In case of bug report: Unexpected behaviour you saw

> systemd-networkd waits forever in state "routable (configuring)" when dhcp server does not provide routing information ("option routers") even if the interface got an valid ip address
### In case of bug report: Steps to reproduce the problem

> 1. configure a dhcp server to not send any routers (empty option routers)
> 2. try to get network "configured" via systemd-networkd
> 3. look at 'networkctl status -a'

**Comment by sitsofe** [comment]
I can confirm this issue is still present in Ubuntu 17.04's systemd 232.

**Comment by ssahani** [comment]
fix is waiting on #6886
