### ISSUE TITLE
coredumpctl not listing dumps when run as an user

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#3755]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230
### Used distribution

> Debian (unstable)
### In case of bug report: Unexpected behaviour you saw

I would expect to be able to read/dump the coredumps produced by my own UID by using coredumpctl, but somehow coredumpctl doesn't list any dumps when run as a regular user. It does when run as root.

Of relevance, is that I have

```
[Journal]
SplitMode=login
```

and

```
[Coredump]
Storage=external
```

But it looks like that the dump metadata is saved in the wrong journal with this setup?

Also, when using external storage, it would make sense to have a specific retention in days for cores. In fact, my journal retention is of several months, but I'd only want to store the actual core files for the last 48 hours only.

**Comment by poettering** [comment]
You have different retention already. for the journal configure it for MaxRetentionSec= in journald.conf. For the coredumps override the tmpfiles line for /var/lib/systemd/coredump and change the "age" column in /usr/lib/tmpfiles.d/systemd.conf.

**Comment by poettering** [comment]
Does this work if you use SplitMode=uid? Does the user get access to the journal log messages about the coredumps at least? i.e. is it just the coredump blob itself that access is not available to, or already the log message about it?

**Comment by wavexx** [comment]
Can I swap the split policy and back while still reading the old logs?

**Comment by poettering** [comment]
On Wed, 20.07.16 03:17, wavexx (notifications@github.com) wrote:

> Can I swap the split policy and back while still reading the old logs? 

Yes. "journalctl" always works the same: it shows you all logs it has
access to, regardless what the files are named or how they are split up.

**Comment by wavexx** [comment]
I just tried with SplitMode=uid and I can see the dumps.
Before I try again with SplitMode=logins, is there anything you want to explicitly test besides the log entries visibility in the journal?

**Comment by poettering** [comment]
so, you are saying with SplitMode=uid everything works fine, but with SplitMode=logins it doesn't?

That is an indication that your login sessions aren't proper login sessions. Maybe pam_systemd isn't in your PAM stack? Do you see you session showing up in "loginctl"?

**Comment by wavexx** [comment]
pam_systemd is in place and loginctl works

**Comment by wavexx** [comment]
I switched to SplitMode=login again and indeed, journalctl doesn't show systemd-coredump entries for the current user. The core file though has correct permissions (there's an acl entry).

**Comment by wavexx** [comment]
Switching back to SplitMode=uid, I noticed that indeed this might not be isolated to coredump. The standard 'logger(1)' utility didn't log properly on the user's journal, but with SplitMode=uid it does.

So it might be some session registration problem. I'm using debian unstable, but as I wrote libpam-systemd is installed and registered. loginctl shows my session correctly.

If there's anything I can try, please ask.

**Comment by poettering** [comment]
ah, ok, i remember now what the issue here is: the coredump handler invoked by the kernel is in fact _not_ part of any user session, but invoked independently of them all. That means by SplitMode=login you explicitly request that the coredump stays in the system journal and not in the user journal.

If you use SplitMode=uid this is not a problem, since the processing code for the coredump runs as the client's uid. In fact SplitMode=uid was introduced precisely to fix this issue.

Also see edc3797f7cd9e37c24e5241cac3263e7c918f732.

Closing hence, since this is really is expected behaviour.

**Comment by wavexx** [comment]
On Thu, Jul 21 2016, Lennart Poettering notifications@github.com wrote:

> ah, ok, i remember now what the issue here is: the coredump handler
> invoked by the kernel is in fact _not_ part of any user session, but
> invoked independently of them all. That means by SplitMode=login you
> explicitly request that the coredump stays in the system journal and
> not in the user journal.
> <...>
> Closing hence, since this is really is expected behaviour.

Re-reading the documentation about SplitMode, i feel the documentation
needs to be changed. This is not what I expected.

By "login", I infer that the log is split according to the availability
of a login/seat (that is: if the user has an active session for that
UID, the entry split).

However, it should make explicit that this done accordingly to the
session's context the process is running in, which makes SplitMode=login
much less useful as most background processes or daemons which are run
for the user will not be accessible for the user itself.

In fact, I expected logger(1) to work with =login, because the frontend
_is_ running in the user's session, but the server isn't.

Very confusing.

**Comment by poettering** [comment]
@wavexx i posted PR #3801 which hopefully explains this better in the man page. Please have a look!

**Comment by wavexx** [comment]
On Mon, Jul 25 2016, Lennart Poettering wrote:

> @wavexx i posted PR #3801 which hopefully explains this better in the man page. Please have a look!

Excellent explanation, thanks.
This also clarifies a lot the 'uid' mode for me.
