### ISSUE TITLE
Systemd

### ISSUE THREAD

**Issue by urbaniak** [systemd/systemd#3765]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd-229-8.fc24.x86_64
### Used distribution

Fedora 24
### In case of bug report: Expected behaviour you didn't see

Logging to stdout/stderr from process managed by systemd (gunicorn) works fine until the process forks itself and kills the old instance.

After fork systemd stops recognising the logs produced by the gunicorn as sent from gunicorn.service, but they're still in the logs.

`journalctl -f -u gunicorn.service` is empty after the process forker, but I'm still able to see logs in `journalctl -f`.

`systemctl status gunicorn` shows that the process is running, in the correct cgroup, but the last log entry is the one from process before it forked.

```
● gunicorn.service - gunicorn deamon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-07-20 13:10:25 UTC; 7min ago
  Process: 3496 ExecStop=/bin/kill $MAINPID (code=exited, status=0/SUCCESS)
  Process: 3519 ExecReload=/bin/kill -SIGUSR2 $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 3520 (gunicorn: maste)
    Tasks: 3 (limit: 512)
   CGroup: /system.slice/gunicorn-app.service
           ├─3520 gunicorn: master [app]                                                                              
           ├─3527 gunicorn: worker [app.2]                                                                            
           └─3528 gunicorn: worker [app.2]                                                                            

<cut>
Jul 20 13:10:52 xxxxxx gunicorn[3499]: Shutting down: Master
```
### In case of bug report: Steps to reproduce the problem
- run gunicorn with systemd
- log to stdout
- kill gunicorn master with HUP2, it will spawn new instance
- kill the old one
- look at the logs for gunicorn service, they're empty

I'm happy to provide more debug information, just need to know what's required.

**Comment by poettering** [comment]
This appears to be an instance of the issue tracked here:

https://bugs.freedesktop.org/show_bug.cgi?id=50184

**Comment by poettering** [comment]
Also see: https://github.com/systemd/systemd/issues/2913

Closing this one as duplicate
