### ISSUE TITLE
systemctl enable shows misleading error message if Also= mentions non-existing file

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#3766]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

230
### Used distribution

Debian

Take the following example file foo.service:

```
[Unit]
Description=test

[Service]
ExecStart=/bin/true

[Install]
WantedBy=multi-user.target
Also=bar.service
```

The bar.service does not exist. Now let's try to enable it:

```
# systemctl enable foo.service
Failed to enable unit: No such file or directory
```

First time I read this error message, I thought foo.service was somehow not found by systemctl and I was quite puzzled. The error message should specify, which unit file is missing and maybe also that it is referenced via Also=

**Comment by keszybz** [comment]
This got fixed a while ago:
```
$ sudo systemctl enable foo.service
Failed to enable unit: File bar.service: No such file or directory
```
