### ISSUE TITLE
kdbus: unable to handle kernel NULL pointer dereference

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#378]
Jun 26 01:37:55 ank kernel: BUG: unable to handle kernel NULL pointer dereference at 0000000000000018
Jun 26 01:37:55 ank kernel: IP: [<ffffffffa007c0f2>] kdbus_name_release_all+0x32/0xd0 [kdbus]
Jun 26 01:37:55 ank kernel: PGD 0 
Jun 26 01:37:55 ank kernel: Oops: 0000 [#1] SMP 
Jun 26 01:37:55 ank kernel: Modules linked in: ccm cmac rfcomm arc4 snd_hda_codec_hdmi bnep snd_hda_codec_realtek snd_hda_codec_generic iTCO_wdt iTCO_ven
Jun 26 01:37:55 ank kernel:  crc32c_intel serio_raw rtsx_pci mfd_core
Jun 26 01:37:55 ank kernel: CPU: 1 PID: 1689 Comm: systemd Tainted: G        W  OE   4.1.0-1.fc23.x86_64 #1
Jun 26 01:37:55 ank kernel: Hardware name: LENOVO 20AL00C7GE/20AL00C7GE, BIOS GIET77WW (2.27 ) 10/02/2014
Jun 26 01:37:55 ank kernel: task: ffff8801f4233160 ti: ffff8801f4204000 task.ti: ffff8801f4204000
Jun 26 01:37:55 ank kernel: RIP: 0010:[<ffffffffa007c0f2>]  [<ffffffffa007c0f2>] kdbus_name_release_all+0x32/0xd0 [kdbus]
Jun 26 01:37:55 ank kernel: RSP: 0018:ffff8801f4207998  EFLAGS: 00010202
Jun 26 01:37:55 ank kernel: RAX: 0000000000000000 RBX: ffff8801a4d06200 RCX: dead000000200200
Jun 26 01:37:55 ank kernel: RDX: 0000000000000000 RSI: ffff8801a4d06200 RDI: ffff8801a5c15800
Jun 26 01:37:55 ank kernel: RBP: ffff8801f42079b8 R08: ffff8801a4d06270 R09: ffffea0002065e80
Jun 26 01:37:55 ank kernel: R10: ffffffffa0078a78 R11: 000000000000001c R12: ffff8801a4d06370
Jun 26 01:37:55 ank kernel: R13: ffff8801a5c15800 R14: 0000000000000000 R15: ffff8801a4d06200
Jun 26 01:37:55 ank kernel: FS:  00007f78355e7900(0000) GS:ffff88021e240000(0000) knlGS:0000000000000000
Jun 26 01:37:55 ank kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jun 26 01:37:55 ank kernel: CR2: 0000000000000018 CR3: 00000001a5ccd000 CR4: 00000000001407e0
Jun 26 01:37:55 ank kernel: Stack:
Jun 26 01:37:55 ank kernel:  ffff8801a4d06238 ffff8801a4d06370 ffff8801a5c16000 ffff8801a4d06358
Jun 26 01:37:55 ank kernel:  ffff8801f4207a58 ffffffffa0072744 ffff8801f4207c50 ffff8801a5c16330
Jun 26 01:37:55 ank kernel:  ffff8801a5c15800 0000000000000001 ffff8801a5c16000 ffffffffa007bfb1
Jun 26 01:37:55 ank kernel: Call Trace:
Jun 26 01:37:55 ank kernel:  [<ffffffffa0072744>] kdbus_conn_disconnect+0x1b4/0x3d0 [kdbus]
Jun 26 01:37:55 ank kernel:  [<ffffffffa007bfb1>] ? kdbus_name_acquire+0x281/0x390 [kdbus]
Jun 26 01:37:55 ank kernel:  [<ffffffffa0073fb2>] kdbus_cmd_hello+0xa92/0xd60 [kdbus]
Jun 26 01:37:55 ank kernel:  [<ffffffffa0076fe2>] kdbus_handle_ioctl+0x312/0x640 [kdbus]
Jun 26 01:37:55 ank kernel:  [<ffffffff8123fc66>] do_vfs_ioctl+0x2c6/0x4d0
Jun 26 01:37:55 ank kernel:  [<ffffffff8123c18f>] ? putname+0x6f/0x80
Jun 26 01:37:55 ank kernel:  [<ffffffff8123fef1>] SyS_ioctl+0x81/0xa0
Jun 26 01:37:55 ank kernel:  [<ffffffff817a0f2e>] system_call_fastpath+0x12/0x71
Jun 26 01:37:55 ank kernel: Code: 89 e5 41 56 41 55 4c 8d af 00 08 00 00 41 54 53 48 89 f3 45 31 f6 4c 89 ef e8 1b 32 72 e1 f6 43 10 02 74 13 48 8b 83 a0
Jun 26 01:37:55 ank kernel: RIP  [<ffffffffa007c0f2>] kdbus_name_release_all+0x32/0xd0 [kdbus]
Jun 26 01:37:55 ank kernel:  RSP <ffff8801f4207998>
Jun 26 01:37:55 ank kernel: CR2: 0000000000000018
Jun 26 01:37:55 ank kernel: ---[ end trace 74e6cb662a9cee52 ]---

**Comment by dvdhrm** [comment]
Fixed in kdbus upstream:
https://github.com/systemd/kdbus/commit/4a4a7f03237e559025119fb7083eb1a651b29190
(sha256 subject to change)
