### ISSUE TITLE
please document template usage in obvious places

### ISSUE THREAD

**Issue by archenemies** [systemd/systemd#3791]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 320

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch
### In case of bug report: Expected behaviour you didn't see

I'm just trying to create a "template" unit file, which I've seen done in `dhcpd@eth0.service`. I ran into the following problems:
1. I didn't know that the template facility is described by the term "template". It would be better if the documentation also used other candidate terms like "argument" or "parameter" to refer to templates, so that someone who searches for "systemd service with arguments" will be more likely to find the correct section.
2. After learning that I should use the word "template" (or "instance"), I don't see templates documented in systemd.service(5), which is where I would expect to look for them. There is only one paragraph and it is under "Automatic Dependencies", not exactly an overview of templates/instances. In systemd.unit(1) there is a paragraph "Optionally, units may be instantiated from a template file at runtime.", however: both templates and instances are mentioned previous to this paragraph without having been defined, and the paragraph itself could be a bit clearer.

I would expect to see something like:

In systemd.service(5), new section before "AUTOMATIC DEPENDENCIES":

"SERVICE TEMPLATES It is possible for Systemd services to take a single argument via the service@argument syntax. Such services are called 'instantiated' or 'template' services. An example is the dhcpcd@ service which takes a network interface as a parameter. Within the service file, this parameter or 'instance name' can be accessed with the '%i' specifier. See systemd.unit(5) for more details."

In systemd.unit(5), before "Unit files may contain additional options":

"Unit files can be parameterized by a single argument called an 'instance name'. These files serve as templates for multiple services. The service name is given by appending an "@" to the unit name, followed by the instance name parameter. The unit file is interpreted as if all occurrences of the '%i' specifier had been replaced by the value of the parameter."

These are examples of what I would find to be clear documentation; I would imagine that my terminology is a bit off and that some of the wording needs to be fixed.

If you're still wondering why the existing documentation is not good enough, take a look at the key paragraph in systemd.unit(5): "Optionally, units may be instantiated from a template file at runtime. This allows creation of multiple units from a single configuration file. If systemd looks for a unit configuration file, it will first search for the literal unit name in the file system." Here I'm three sentences in, and I still don't know the key idea about template units, which is that they take arguments or parameters. In the fourth sentence, arguments are described, but in such a technical fashion as to put me to sleep: "If that yields no success and the unit name contains an "@" character, systemd will look for a unit template that shares the same name but with the instance string (i.e. the part between the "@" character and the suffix) removed." I think this paragraph should be kept, but the main idea should be introduced _before_ it, so the reader has some clue as to what he's spending his time trying to parse.

**Comment by keszybz** [comment]
All very reasonable comments ;) Any chances you could submit a patch? (It's easier to do corrections like that when you haven't already seen the text umptillion times.)

**Comment by archenemies** [comment]
Thank you, I'm glad you agree. I think I should have come up with a better issue title, though, hmm.

Well I wrote two paragraphs with suggestions where they should go, but as I said I wasn't sure of the wording. Can that be enough for someone more expert to construct a patch from?

**Comment by Vrihub** [comment]
+1 

Also, I think the `name@instance.type` syntax should be briefly explained also in the `systemctl` man page, in the `Parameter syntax` section (and maybe also with a link to the `systemd.unit` man page for further details about instancing).

`man systemctl` is one of the first pages a novice user reads, and the instancing syntax is used a couple of times throughout the page, but never really explained.
