### ISSUE TITLE
journalctl --vacuum-size outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#380]
When I execute `journalctl --vacuum-size=128M >/dev/null` I don't expect output like this:

```
Deleted archived journal /var/log/journal/....journal (128.0M).
Vacuuming done, freed 128.0M of archived journals on disk.
```

this is systemd-221

**Comment by poettering** [comment]
Well, that's how UNIX works. Log messages are written to stderr, not stdout. "Payload" data is written to stdout, but this tool doesn't have any real payload, hence it only prints something to stderr, and that's it.

If you want to turn off output to stderr, then redirect stderr with 2> too.

**Comment by SjonHortensius** [comment]
I've been reading through http://pic.plover.com/UnixReader/reader.pdf but didn't find any source for that behaviour, do you maybe have a reference for that? I actually believe what you refer to as 'log' is actually the payload; since it ````journalctl --vacuum-size=128M --boot``` doesn't output anything (except for the vacuum output originally posted). Maybe vacuuming should become a subcommand of journalctl instead of an option to clarify this? eg ```journalctl vacuum --size=128M```

**Comment by poettering** [comment]
Well, try "man stderr". It says "..., and one for printing diagnostic or error messages". The messages you mention are clearly of the "diagnostic" kind.

well, journalctl doesn't take "subcommands" (though we usually call them "verbs"), as the arguments you pass that are not switches are considered matches. And we cannot change that now. Sorry.

**Comment by Salamandar** [comment]
That's actually an issue where cron (and cronic) are checking the stderr. If it contains anything, it's assumed to be an error, and cron sends an email to the administrator.
