### ISSUE TITLE
ActiveState property with value "inactive"is not being sent out when service exits/fails

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#3807]
### Submission type
- [ x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

219

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> …
### In case of bug report: Expected behaviour you didn't see

ActiveState property with value "inactive"is not being sent out when service is killed by signal

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

kill -9 PIDOF_SERVICE and run  shell command 'dbus-monitor --system'

> …

**Comment by cdprashanth** [comment]
I am writing service monitoring app, which needs to know when the services go from active to inactive/failed.
I am subscribing to PropertiesChanged signal and watching ActiveState.
but this is not sufficient. When a service is stopped using kill/systemctl stop , i see that i get ActiveState=deactivating  changed signal  twice :one with  Substate="stop-sigterm" and another with Substate="stop-post".
As per my previous queries, I understand that only ActiveState is considered an API and we should not be looking into SubState. but I dont get ActiveState=inactive when a service is stopped.
So this seems to be a bug.
For workaround, is there any way to figure out when an service is stopped ?  As workaround, should i watch SubState ?
Thanks

**Comment by cdprashanth** [comment]
similar issue 
https://lists.freedesktop.org/archives/systemd-devel/2016-May/036767.html
https://github.com/systemd/systemd/issues/3390

I was browsing through sytemd code and my theory is that by the time properties changed signal is being prepared to be sent, service has already gone through mutiple state changes or the unit is unloaded and hence no property changeg signal is sent out.
As workaround , I am planning to watch on SubState instead of ActiveState in PropertiesChanged signal and also have ExecStopPost in service file.
I have noticied that, when a service becomes inactive  I always get SubState=stop-post (when i have ExecStopPost ).

Can anyone please comment if this is correct work-around ?

Thanks

**Comment by cdprashanth** [comment]
Hi @poettering , could  you please comment

**Comment by poettering** [comment]
This has been fixed by 0dd99f86addd1f81e24e89807b6bc4aab57d5793, also see #4095. 

Closing
