### ISSUE TITLE
kdbus: x session, logind pauses and never resumes

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#381]
- Open gnome-terminal
- type "sudo -s"
- the "enter key gets stuck" and the terminal content runs away
- the machine is unresponsive, only the power button still works to shut down

Note: sudo's pam is configured to use pam_systemd, it starts system --user for uid 0.

Jun 26 12:15:14 ank systemd[1285]: Starting Bus Names.
Jun 26 12:15:14 ank systemd[1285]: Reached target Basic System.
Jun 26 12:15:14 ank systemd[1285]: Starting Basic System.
Jun 26 12:15:14 ank systemd[1285]: Starting Console Manager and Terminal Emulator...
Jun 26 12:15:14 ank systemd[1285]: Started Console Manager and Terminal Emulator.
Jun 26 12:15:14 ank systemd[1285]: Reached target Default.
Jun 26 12:15:14 ank systemd[1285]: Startup finished in 53ms.
Jun 26 12:15:14 ank systemd[1285]: Starting Default.
Jun 26 12:15:14 ank sshd[1235]: pam_unix(sshd:session): session opened for user root by (uid=0)
Jun 26 12:15:14 ank systemd[1]: Started User Manager for UID 0.
Jun 26 12:15:33 ank systemd[595]: Starting DBUS1: org.gnome.Terminal...
Jun 26 12:15:33 ank systemd[595]: Started DBUS1: org.gnome.Terminal.
Jun 26 12:15:51 ank sudo[1501]:      kay : TTY=pts/1 ; PWD=/home/kay ; USER=root ; COMMAND=/bin/bash
Jun 26 12:15:51 ank sudo[1501]: pam_unix(sudo:session): session opened for user root by kay(uid=0)
Jun 26 12:15:51 ank systemd-logind[520]: New session c1 of user root.
Jun 26 12:15:51 ank systemd[1]: Started Session c1 of user root.
Jun 26 12:15:51 ank systemd[1]: Starting Session c1 of user root.
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:73
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:66
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:70
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:72
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:65
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:71
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:69
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:82
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 226:0
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:78
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:68
Jun 26 12:15:51 ank /usr/libexec/gdm-x-session[609]: (II) systemd-logind: got pause for 13:67
Jun 26 12:15:51 ank sudo[1501]: pam_unix(sudo:session): session opened for user root by kay(uid=0)

**Comment by dvdhrm** [comment]
Fixed in:
https://github.com/systemd/systemd/commit/0204c4bd69f694b527643ace9d434befce80085c

Ray Strode also agreed on dropping support for multiple sessions on the same VT, gdm does not use it anymore these days.
