### ISSUE TITLE
Wrong name, soname for libsystemd-shared-231.so

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#3810]
### Submission type
- [ ] Bug report
- [X ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> OpenMandriva Lx
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

A libsystemd-shared-231.so has been intorduced. Intentions are fine and needed. Problem occurs with packaging on distributions that "proctect shared object major".

For example, each library is packaged separately libfoobar1.x86_64.rpm
In case of libsystemd-shared-231.so RPM treats this as a "development" library because name and soname does not fit in old scheme libfoobar%{api}.so.%{major}.%{minor}*

Desired change will be to rename libsystemd-shared-231.so to libsystemd-shared.so.231
### In case of bug report: Steps to reproduce the problem

> …

**Comment by martinpitt** [comment]
I recommend to not package the internal library separately. For Debian and Ubuntu at least it works fine to just put it into the systemd package. Nothing else than systemd's own binaries can link against it anyway.

**Comment by martinpitt** [comment]
> Desired change will be to rename libsystemd-shared-231.so to libsystemd-shared.so.231

No, this is absolutely wrong. This is _not_ what SONAMEs do/are.

**Comment by mbiebl** [comment]
We intentionally used libtool's -release flag for libsystemd-shared to make it clear that this is not a stable interface and should _not_ be treated as public library.

**Comment by poettering** [comment]
@tpgxyz note that we place this library in a private systemd-specific subdir of $(libdir), not in $(libdir) for a reason: so that it does not appear in the usual search path. If you distro requires you to package all libs in separate RPMs, then I'd argue this doesn't apply here, as this is by all mechanisms not a public library, but just some hidden, internal resource of systemd, that doesn't appear in the search path nor is in any other way publically available.

**Comment by tpgxyz** [comment]
@poettering Thanks for a good explanation what is the purpose libsystemd-shared-231.so library. Everything is now clear. Not an issue.
