### ISSUE TITLE
MemoryDenyWriteExecute=yes fails systemd-*.services

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#3814]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 231
> +PAM +AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> OpenMandriva Lx
### In case of bug report: Unexpected behaviour you saw

systemd-*.services like journald, hostanmed etc, all those which have set MemoryDenyWriteExecute=yes fails due to

error while loading shared libraries: libgcrypt.so.20: cannot enable executable stack as shared object requires: Operation not permitted

Changing MemoryDenyWriteExecute to "no" brings system back to operational level.

Would be nice if someone with a good will help me here :)
### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
Hmm, interesting. That would suggest that your version of libgcrypt requires executable stacks. Any chance you can check whether updating gcrypt fixes that? We see no such limitation on Fedora or Ubuntu really.

**Comment by tpgxyz** [comment]
@poettering I'm running on libgcrypt-1.7.2, while fedora is on 1.6.5

I found in libgcrypt build logs..
checking whether assembler supports --noexecstack option... no

...

/usr/bin/ld: warning: ../cipher/.libs/libcipher.a(arcfour-amd64.o): missing .note.GNU-stack section implies executable stack

Looks like this is internal issue in OpenMandriva. as noexecstack.m4 in libgcrypt may not support LLVM/clang as default compiler.
