### ISSUE TITLE
systemctl daemon-reexec tty issues

### ISSUE THREAD

**Issue by userwithuid** [systemd/systemd#3842]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231, the culprit is this commit: https://github.com/systemd/systemd/commit/affd7ed1a923b0df8479cff1bd9eafb625fdaa66
### Used distribution

arch
### In case of bug report: Expected behaviour you didn't see

`systemctl daemon-reexec` (which is called automatically after a package upgrade on arch btw) should succeed without issues and without being visible
### In case of bug report: Unexpected behaviour you saw
- I noticed the problem on one machine (amdgpu gfx) with running X (startx). On reexec
1. the display becomes corrupted (only the output, triggered screenshot shows normal X, but switching tty with ctrl+alt does not seem to work)
2. have to kill X via ssh (which gets vconsole back)
3. must exit (logout) first!
4. after re-login + startx things seem to be fine again
- On another machine (intel gfx) with X, there is only a small flickering on reexec (which seems to show the vconsole) but otherwise things seemed OK?
- BUT digging a little bit deeper, I tried to do daemon-reexec from vconsole without X, on BOTH machines:
1. log in as user on tty1
2. run `sudo systemctl daemon-reexec` -> no visible error
3. run `sudo $whatever` -> sudo fails with `sudo: no tty preset and no askpass program specified`

So something still seems to be amiss regardless of X + gfx driver? But I'm at a loss at this point... :-)

All the mentioned problems go away on a patched 231 with the commit in question reversed.

Logs 231:

> systemd[1]: Reexecuting.
> systemd[1]: systemd 231 running in system mode. (...
> systemd[1]: Detected architecture x86-64.
> systemd[1]: Received SIGHUP from PID 1 (systemd).
> systemd[1]: Reloading.

Logs 231 with patch reversed:

> systemd[1]: Reexecuting.
> systemd[1]: systemd 231 running in system mode. (...
> systemd[1]: Detected architecture x86-64.

As you can see, the last two lines are missing, but no errors or anything else.
### In case of bug report: Steps to reproduce the problem

`systemctl daemon-reexec` (but only when reexec is called from an already running 231, 230->reexec->231 uses the 230 reexec code so no issue)

**Comment by keszybz** [comment]
I have observed similar corruption with systemd 231. I'm using gnome-wayland, and it looks like it crashes on daemon-reload (random patterns on screen), but cycling through the virtual terminals with ctrl-alt-Fx fixes things. Thanks for tracking this down, the commit you found seems to be a good candidate for the culprit.

We need to fix this, because daemon-reexec is (apart from manual invocations) executed as part of package update, so this will be very noticable for normal users.

@fbuihuu Thoughts? Was affd7ed fixing something, or just a general cleanup?

**Comment by martinpitt** [comment]
Also confirmed in https://bugs.debian.org/834367

**Comment by fbuihuu** [comment]
Sorry for the delay, I was on vacations...

So it looks like make_console_stdio() has bad side effect. More specifically it does a TIOCSCTTY ioctl (via acquire_terminal()) which sees to disturb the process which was using/owning the console.

@keszybz, commit affd7ed was introduced to make sure that while re-executing we're connected to the same stdios as before (when we were started by the kernel). This allows to avoid special cases during systemd initialization, the code to enable console color mode is the same for example.

Maybe we should remove make_console_stdio() entirely when re-executing (systemd binary or not) and initialize the console color mode on /dev/console explicitly and not assume that our stdios are not connected to the console ?

**Comment by poettering** [comment]
There's a PR fixing this in #3987 btw.
