### ISSUE TITLE
`systemd-networkd-wait-online -i x` doesn't wait for x to be fully configured

### ISSUE THREAD

**Issue by tchernomax** [systemd/systemd#3844]
### Submission type
- [X] Bug report
### systemd version the issue has been seen with

``` console
max@max-server % systemctl --version
systemd 231
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```
### Used distribution

Gentoo
### Expected behaviour you didn't see

`systemd-networkd-wait-online -i enp1s0` wait for enp1s0 to be fully configured.
### Unexpected behaviour you saw

``` console
max@max-server % cat /etc/systemd/network/enp1s0.network           
[Match]
Name=enp1s0

[Network]
Description=gauche
DHCP=no
Address=192.168.1.2/24
Address=2001:…::1/64
Gateway=192.168.1.1
Domains=lan
Tunnel=he-ipv6
IPv6AcceptRouterAdvertisements=false
IPv6DuplicateAddressDetection=0

max@max-server % systemctl is-enabled network-online.target                                   
static

max@max-server % systemctl show -p ExecStart systemd-networkd-wait-online.service | cat
ExecStart={ path=/usr/lib/systemd/systemd-networkd-wait-online ; argv[]=/usr/lib/systemd/systemd-networkd-wait-online -i enp1s0 ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }

max@max-server % systemctl show -p After unbound.service                               
After=basic.target network.target systemd-journald.socket system.slice sysinit.target

max@max-server % journalctl --unit=unbound.service --unit=systemd-networkd.service -b 
-- Logs begin at dim. 2016-03-13 16:04:37 CET, end at dim. 2016-07-31 16:55:20 CEST. --
juil. 31 16:40:22 max-server systemd[1]: Starting Network Service...
juil. 31 16:40:26 max-server systemd-networkd[270]: Enumeration completed
juil. 31 16:40:26 max-server systemd[1]: Started Network Service.
juil. 31 16:40:26 max-server systemd-networkd[270]: he-ipv6: netdev ready
juil. 31 16:40:26 max-server systemd-networkd[270]: enp1s0: IPv6 enabled for interface: Success
juil. 31 16:40:26 max-server systemd[1]: Starting Unbound recursive Domain Name Server...
juil. 31 16:40:26 max-server systemd-networkd[270]: lo: Configured
juil. 31 16:40:26 max-server systemd-networkd[270]: he-ipv6: IPv6 enabled for interface: Success
juil. 31 16:40:26 max-server systemd-networkd[270]: he-ipv6: Gained carrier
juil. 31 16:40:26 max-server systemd-networkd[270]: he-ipv6: Gained IPv6LL
juil. 31 16:40:26 max-server systemd-networkd[270]: he-ipv6: Configured
juil. 31 16:40:29 max-server unbound-checkconf[306]: unbound-checkconf: no errors in /etc/unbound/unbound.conf
juil. 31 16:40:29 max-server systemd[1]: Started Unbound recursive Domain Name Server.
juil. 31 16:40:29 max-server unbound[338]: [1469976029] unbound[338:0] error: can't bind socket: Cannot assign requested address for 2001:…::1
juil. 31 16:40:29 max-server unbound[338]: [1469976029] unbound[338:0] fatal error: could not open ports
juil. 31 16:40:29 max-server systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
juil. 31 16:40:29 max-server systemd[1]: unbound.service: Unit entered failed state.
juil. 31 16:40:29 max-server systemd[1]: unbound.service: Failed with result 'exit-code'.
juil. 31 16:40:29 max-server systemd-networkd[270]: enp1s0: Gained carrier
juil. 31 16:40:29 max-server systemd-networkd[270]: enp1s0: Gained IPv6LL
juil. 31 16:40:29 max-server systemd-networkd[270]: enp1s0: Configured
```

`unbound.service` is started before `systemd-networkd[270]: enp1s0: Configured`.
### Steps to reproduce the problem
- configure an interface with ipv4 and ipv6 address
- enable systemd-networkd-wait-online
- in a service that should be start after network is up: bind on ipv6 address
### Remark

Somewhat related to #2037.
That's why I tried to add `IPv6DuplicateAddressDetection=0` ; but it doesn't solve the problem.

**Comment by gdamjan** [comment]
the unbound.service needs `After=network-online.target` too

**Comment by tchernomax** [comment]
Thank for the quick answer… but that's not how I understand the [wiki](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) (maybe I am mistaken):

> Many network management solutions provide a way to unconditionally **pull in network-online.target, and thus upgrading the effect of network.target to the effect of network-online.target**.
> …
> If you use systemd-networkd you can do this by enabling systemd-networkd-wait-online.service:
>      systemctl enable systemd-networkd-wait-online.service
> …
> **Alternatively**, you can change your service that needs the network to be up, to include After=network-online.target and Wants=network-online.target.

**Comment by gdamjan** [comment]
The wiki page does seems a bit unclear.
This is better: 
https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-online.target

> network-online.target
> 
> Units that strictly require a configured network connection should pull in network-online.target (via a Wants= type dependency) and order themselves after it. This target unit is intended to pull in a service that delays further execution until the network is sufficiently set up. What precisely this requires is left to the implementation of the network managing service.
> 
> Note the distinction between this unit and network.target. This unit is an active unit (i.e. pulled in by the consumer rather than the provider of this functionality) and pulls in a service which possibly adds substantial delays to further execution. In contrast, network.target is a passive unit (i.e. pulled in by the provider of the functionality, rather than the consumer) that usually does not delay execution much. Usually, network.target is part of the boot of most systems, while network-online.target is not, except when at least one unit requires it. Also see Running Services After the Network is up for more information.
> 
> All mount units for remote network file systems automatically pull in this unit, and order themselves after it. Note that networking daemons that simply provide functionality to other hosts generally do not need to pull this in.

**Comment by tchernomax** [comment]
@gdamjan Thanks a lot ! I tried the following and it works perfectly. I close this issue.

``` console
max@max-server % systemctl show -p Wants,After unbound
Wants=nss-lookup.target network-online.target
After=network.target systemd-journald.socket network-online.target sysinit.target basic.target system.slice
max@max-server % systemctl is-enabled systemd-networkd-wait-online.service 
enabled
```

In fact I had read the man but the wiki mislead me.
Specially  the sentence:

> Many network management solutions provide a way to unconditionally pull in network-online.target, and thus upgrading the effect of network.target to the effect of network-online.target

Is there a way I can propose a patch to the wiki ?
