### ISSUE TITLE
NoNewPrivileges=yes prevents selinux process transitions

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#3845]
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

latest RHEL7/Centos7

apologies for being vague. didn't see commits related to this in last 6 months.
### Used distribution

RHEL7/Centos7
### In case of bug report: Expected behaviour you didn't see

Process transition in ps -Z init_t to mysqld_t/antivirus_t
### In case of bug report: Unexpected behaviour you saw

service process remain in init_t selinux state.

created sockets got created using the wrong label.
### In case of bug report: Steps to reproduce the problem

https://jira.mariadb.org/browse/MDEV-10404
https://jira.mariadb.org/browse/MDEV-10405

https://bugzilla.redhat.com/show_bug.cgi?id=1293493
https://bugzilla.redhat.com/show_bug.cgi?id=1292227

**Comment by evverx** [comment]
This is not a `systemd`'s bug:

```
$ sudo journalctl -b _TRANSPORT=audit -o cat | grep security_bounded_transition
SELINUX_ERR op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:antivirus_t:s0
```

https://github.com/torvalds/linux/blob/c540521bba5d2f24bd2c0417157bfaf8b85e2eee/Documentation/prctl/no_new_privs.txt#L28

> To set no_new_privs, use prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0).
> 
> Be careful, though: LSMs might also not tighten constraints on exec
> in no_new_privs mode.  (This means that setting up a general-purpose
> service launcher to set no_new_privs before execing daemons may
> interfere with LSM-based sandboxing.)

https://github.com/torvalds/linux/blob/d011a4d861ce583466a8ae72a0c8e7f51c8cba4e/security/selinux/hooks.c#L2271

> ```
>    /*
>      * The only transitions we permit under NNP or nosuid
>      * are transitions to bounded SIDs, i.e. SIDs that are
>      * guaranteed to only be allowed a subset of the permissions
>      * of the current SID.
>      */
> ```

**Comment by grooverdan** [comment]
Thanks for the explanation. Can I request that the description of https://www.freedesktop.org/software/systemd/man/systemd.exec.html be expanded somewhat.

**Comment by grooverdan** [comment]
below bug moved to #3852 

It appears setting SELinuxContext= isn't a working workaround. Not sure if this is a bug or a documentation RFE.

https://bugzilla.redhat.com/show_bug.cgi?id=1293493#c11

**Comment by evverx** [comment]
I haven't fully grasped https://github.com/torvalds/linux/commit/af63f4193f9fbbbac50fc766417d74735afd87ef yet, but the commit message says
> With this change, systemd unit files can be left unmodified from upstream.
SELinux-disabled and SELinux-enabled users will benefit from retaining any
of the systemd-provided protections.  SELinux policy will only need to
be adapted to enable the new policy capability and to allow the
new permissions between domain pairs as appropriate.

**Comment by keszybz** [comment]
This should now be fixed, in the sense that we don't need to do change anything from our side. The user needs a recent kernel (4.14 or later) and an updated policy. Fedora does that update in https://src.fedoraproject.org/rpms/selinux-policy/c/107eb82b3e182d72c7f2c7f8f03bda6dd790f441?branch=master.
