### ISSUE TITLE
NoNewPrivileges=yes applied before SELinuxContext=

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#3852]
### Submission type
- [ ] Bug report
### systemd version the issue has been seen with

master branch
### Used distribution

all
### In case of bug report: Expected behaviour you didn't see

A service starting with

NoNewPrivileges=yes
SELinuxContext=system_u:system_r:antivirus_t:s0
### In case of bug report: Unexpected behaviour you saw

https://bugzilla.redhat.com/show_bug.cgi?id=1293493#c11

NoNewPrivileges=yes
SELinuxContext=system_u:system_r:antivirus_t:s0

results in:

systemd[4464]: Failed at step EXEC spawning /usr/sbin/clamav-milter: Operation not permitted
### In case of bug report: Steps to reproduce the problem

as above.

It appear here:

https://github.com/systemd/systemd/blob/master/src/core/execute.c#L2141

That NoNewPrivileges is applied first, which according to #3845 3845 prevents a selinux context.

The selinux context is 39 lines of code later. The same effect may also occur with apparmour.

Suggest moving the NoNewPrivileges code to below the apparmour context in execute.c:execute_child.

**Comment by evverx** [comment]
We use the `setexecon`:

> setexeccon() sets the context used for the next execve(2) call.

This differs from the `setcon`:

> setcon()  sets the current security context of the process to a new value.

So, the order doesn't really matter.

See https://github.com/torvalds/linux/blob/d011a4d861ce583466a8ae72a0c8e7f51c8cba4e/security/selinux/hooks.c#L2318

``` c
        if (old_tsec->exec_sid) { /* SELinuxContext=... triggers this branch */
                new_tsec->sid = old_tsec->exec_sid;
                /* Reset exec SID on execve. */
                new_tsec->exec_sid = 0;

                /* Fail on NNP or nosuid if not an allowed transition. */
                rc = check_nnp_nosuid(bprm, old_tsec, new_tsec);

                if (rc)
                        return rc; /* -EPERM here */
        } else {
                /* Check for a default transition on this program. */
                rc = security_transition_sid(old_tsec->sid, isec->sid,
                                             SECCLASS_PROCESS, NULL,
                                             &new_tsec->sid);
                if (rc)
                        return rc;

                /*
                 * Fallback to old SID on NNP or nosuid if not an allowed
                 * transition.
                 */
                rc = check_nnp_nosuid(bprm, old_tsec, new_tsec);
                if (rc)
                        new_tsec->sid = old_tsec->sid;
        }
```

Actually, you should fix the policy: i.e. the `check_nnp_nosuid` should return `0`.

**BTW**:
[This](https://bugzilla.redhat.com/show_bug.cgi?id=1293493#c9) works fine:

```
$ sudo systemctl start clamav-milter.service
$ pgrep -a clamav
14485 /usr/sbin/clamav-milter -c /etc/mail/clamav-milter.conf --foreground=yes
$ ps -Z 14485
LABEL                             PID TTY      STAT   TIME COMMAND
system_u:system_r:init_t:s0     14485 ?        Ssl    0:00 /usr/sbin/clamav-milter -c /etc/mail/clamav-milter.conf --foreground=yes
$ sudo systemctl stop clamav-milter.service
```

```
$ cat clamav.te
policy_module(clamav, 0.0.1)

require {
        type init_t;
        type antivirus_t;
        type antivirus_exec_t;
}

typebounds init_t antivirus_t;
allow init_t antivirus_exec_t:file entrypoint;

$ sudo make -f /usr/share/selinux/devel/Makefile load
Compiling targeted clamav module
/usr/bin/checkmodule:  loading policy configuration from tmp/clamav.tmp
/usr/bin/checkmodule:  policy configuration loaded
/usr/bin/checkmodule:  writing binary representation (version 17) to tmp/clamav.mod
Creating targeted clamav.pp policy package
Loading targeted modules: clamav
rm tmp/clamav.mod.fc tmp/clamav.mod

$ sudo systemctl start clamav-milter.service
$ pgrep -a clamav
14621 /usr/sbin/clamav-milter -c /etc/mail/clamav-milter.conf --foreground=yes
$ ps -Z 14621
LABEL                             PID TTY      STAT   TIME COMMAND
system_u:system_r:antivirus_t:s0 14621 ?       Ssl    0:00 /usr/sbin/clamav-milter -c /etc/mail/clamav-milter.conf --foreground=yes
```

**Comment by evverx** [comment]
Well, we have already [documented](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SELinuxContext=) this:

> Set the SELinux security context of the executed process. If set, this will override the automated domain transition. **However, the policy still needs to authorize the transition.** ...  See setexeccon(3) for details.

I'm closing the issue
