### ISSUE TITLE
Password text prompt on boot is no more highlighted (cryptsetup)

### ISSUE THREAD

**Issue by djgera** [systemd/systemd#3853]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> v231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux (x86_64)

Now the text is mixed with the other messages, since shares the same color, is not white anymore (cryptsetup)

**Comment by poettering** [comment]
what kind of console do you have? just a plain DRM console? or something more exotic, such as serial console or so?

**Comment by djgera** [comment]
It happens in two machines:
- standard text console 80x25 of old days.
- framebuffer console provided by intel drm/kms

PS: no logos, no splash, no custom font, no decorative things, no efi, no container, no virtualization just plain text based console on standard x86 machine.

**Comment by djgera** [comment]
235 still buggy.
Here are some images...

You can see how the prompt looks if ask during bootup or manually trigger via cmd...

![img_20171027_131132408](https://user-images.githubusercontent.com/54004/32114844-fe5fa632-bb1a-11e7-8803-b67c0546fbb3.jpg)
![img_20171027_131647717](https://user-images.githubusercontent.com/54004/32114850-0292d3f0-bb1b-11e7-84b9-98158ae57125.jpg)

**Comment by djgera** [comment]
236 still buggy.

**Comment by djgera** [comment]
just as feedback: 237 bug present.

**Comment by poettering** [comment]
Fix waiting in #8184
