### ISSUE TITLE
man page for `systemd-journal-upload` doesn't describe the format

### ISSUE THREAD

**Issue by eungjun-yi** [systemd/systemd#3857]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd 231
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

The man page for `systemd-journal-upload` describes the format for upload stream of journal entries. ([Journal Export Format](https://www.freedesktop.org/wiki/Software/systemd/export/)?)
### In case of bug report: Unexpected behaviour you saw

The man page doesn't describe the format.
### In case of bug report: Steps to reproduce the problem

`man systemd-journal-upload`

**Comment by keszybz** [comment]
Indeed, the man page doesn't really describe what systemd-journal-upload reads in clear words.

(It consumes existing journal files, so the format is implicitly any journal file or files, the same as journalctl.)
