### ISSUE TITLE
systemd-nspawn --ephemeral does not include hidden files, when directory is not a subvolume

### ISSUE THREAD

**Issue by ostcar** [systemd/systemd#386]
I am using systemd 221.

When systemd-nspawn creates a new subvolume with --ephemeral, but the specified container is not a subfolume (but a normal folder in a btrfs filesystem), a new subvolume is created and all files from the container are copied. But files which start with a dot (hidden files) are excluded.

The reason for that seems to be https://github.com/systemd/systemd/blob/master/src/basic/util.h#L591 which skips hidden files. This code is used in here https://github.com/systemd/systemd/blob/master/src/basic/util.h#L591 and there (via copy_directory_fd()) here https://github.com/systemd/systemd/blob/master/src/basic/btrfs-util.c#L1138

This problem would be solved if fd_copy_directory() would use FOREACH_DIRENT_ALL instead of FOREACH_DIRENT in line 265. But I don't know which side effects this could have.

**Comment by poettering** [comment]
Yupp, FOREACH_DIRENT_ALL is the right solution. Prepped a PR now in #692.
