### ISSUE TITLE
machinectl bind does not make the new bind available to some systemd service inside the container

### ISSUE THREAD

**Issue by alban** [systemd/systemd#3860]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> tested on systemd 230 but should be the same later
### Used distribution

> Fedora-22 in a nspawn container
### In case of bug report: Steps to reproduce the problem

Preconditions:
- Distribution installed in $HOME/distro-trees/fedora-22
- Distribution installed in $HOME/distro-trees/fedora-22/fedora-tree

Enter the container:

```
sudo systemd-nspawn -D $HOME/distro-trees/fedora-22 -b
```

In the container, prepare a service that will run in a different mount namespace:

```
# cat /usr/lib/systemd/system/test01.service 
[Service]
Type=oneshot
ExecStart=/bin/cat /etc/machine-id ; /bin/sleep 600
RootDirectory=/fedora-tree/
MountFlags=shared
# systemctl start test01.service
...
```

While test01.service is initializing or running, from the host:

```
# machinectl bind fedora-22 /tmp /fedora-tree/data
```

Check whether the "data" bind mount is really available in the container:

```
# cat /proc/1/mountinfo |grep /data
```

Check whether the "data" bind mount is really available in the test01.service:

```
# cat /proc/$(pidof sleep)/mountinfo |grep /data
```
### In case of bug report: Expected behaviour you didn't see

```
# cat /proc/1/mountinfo
851 760 253:3 /alban/distro-trees/fedora-22 / rw,relatime master:31 <shared:xxx>- ext4 /dev/mapper/fedora_rainbow-home rw,seclabel,data=ordered
1041 851 0:37 / /fedora-tree/data rw master:26 - tmpfs tmpfs rw,seclabel
# cat /proc/$(pidof sleep)/mountinfo  
1024 992 253:3 /alban/distro-trees/fedora-22/fedora-tree / rw,relatime shared:392 master:<xxx>
<line with the "data" mount>
```

In the mount namespace of the test01 service, I expect to see
- the "data" mount
- the "/" mount being enslaved to the "/" of pid 1 of the container.
### In case of bug report: Unexpected behaviour you saw

```
# cat /proc/1/mountinfo
851 760 253:3 /alban/distro-trees/fedora-22 / rw,relatime master:31 - ext4 /dev/mapper/fedora_rainbow-home rw,seclabel,data=ordered
1041 851 0:37 / /fedora-tree/data rw master:26 - tmpfs tmpfs rw,seclabel
# cat /proc/$(pidof sleep)/mountinfo  
1024 992 253:3 /alban/distro-trees/fedora-22/fedora-tree / rw,relatime shared:392 master:31 - ext4 /dev/mapper/fedora_rainbow-home rw,seclabel,data=ordered
```

In the mount namespace of the test01 service, I saw
- no "data" mount at all
- the "/" mount being enslaved to a host peer group (master:31)

/cc @alepuccetti @euank @yifan-gu @tmrts @iaguis

**Comment by alban** [comment]
I can reproduce the same issue with "nspawn inside nspawn" instead of "systemd service inside nspawn": the "data" bind mount is installed in the outer container but it is not propagated to the inner container because both outer & inner mounts are enslaved to the host mounts.

But if I start the outer container with `systemd-nspawn --bind /tmp:/fedora-tree/data`, then the mount is correctly propagated to the inner container. I would like to install a bind mount with `machinectl bind` (after the container as been started) with the same semantics as `systemd-nspawn --bind`.

**Comment by alban** [comment]
I could make the propagation work with the following two changes:
- Mount / as shared in the container: https://github.com/kinvolk/systemd/commit/001628729a30486bad622acff7031940c0f929fe
- Make sure the incoming directory is _not_ shared: `mount --make-slave /run/systemd/nspawn/incoming/` (otherwise, MS_MOVE does not work, as stated in [bus_machine_method_bind_mount](https://github.com/systemd/systemd/blob/v231/src/machine/machine-dbus.c#L918)).

But I am not quite sure who has the responsibility to do that: should it be done by nspawn or by systemd in the container?

**Comment by poettering** [comment]
Hmm the MS_SHARED exclusion in containers is done since c481f78be7d2620b417e453738ae1d65b576f67e, but that commit doesn't really explain why. I think we can just drop that check, as your patch does. 

And I figure the incoming fix should be applied by setup_propagate(), since it also sets a couple of other flags.

I'd be happy to take a patch that makes the two necessary changes!

**Comment by alban** [comment]
> And I figure the incoming fix should be applied by setup_propagate()

@poettering I think that does not work: if nspawn sets up `$ROOTFS/run/systemd/nspawn/incoming` as MS_SLAVE to make it not-shared, that work will be undone later by systemd in the container by `mount_setup()` with the mount on `/` changing the propagation flags to recursive shared: because it is recursive, it will remove the "shared" flag on the "incoming" mount as well.

> since it also sets a couple of other flags.

The other flags are `MS_BIND|MS_REMOUNT|MS_RDONLY`. Those will not be unset later by systemd because changing the propagation mode does not change the readonly flag. So it is not related.

I guess I will try to do it in setup_mount() then... but only if the "incoming" directory exists.

/cc @iaguis
