### ISSUE TITLE
Requires= and After= does not work on templated instances

### ISSUE THREAD

**Issue by vishwabmc** [systemd/systemd#3862]
### Submission type

 [+] Bug report
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 225
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL -XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```
### Used distribution

This is a Yocto / OpenEmbedded project.

$ uname -a
Linux barreleye 4.4.12-openbmc-20160606-1 #1 Tue Jul 19 15:49:02 CDT 2016 armv5tejl GNU/Linux

This is for https://github.com/openbmc/linux
### In case of bug report: Expected behaviour you didn't see

I was expecting that obmc-console-ssh.socket will not start since I did not have obmc-console@ttyS40 running.. But what I rather saw was that obmc-console-ssh.socket got started and continued to Listen on the stream socket eventhough the prereq was not met.

Any 2 templated service files should recreate this issue.
### In case of bug report: Unexpected behaviour you saw

```
root@barreleye:~# systemctl list-units | grep obmc-console
obmc-console-ssh.socket     loaded active listening OpenBMC console ssh server socket

root@barreleye:~# systemctl status obmc-console-ssh.socket -l
● obmc-console-ssh.socket - OpenBMC console ssh server socket
   Loaded: loaded (/lib/systemd/system/obmc-console-ssh.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Tue 2016-08-02 07:47:58 UTC; 4h 39min ago
   Listen: 0.0.0.0:2200 (Stream)
 Accepted: 1; Connected: 0

Aug 02 07:47:58 barreleye systemd[1]: Listening on OpenBMC console ssh server socket.
```
### In case of bug report: Steps to reproduce the problem

I am just mentioning 2 files here.. but I believe any 2 templated .service files should help here.

Step #1 : Have a .service file like this.

```
root@barreleye:~# cat /lib/systemd/system/obmc-console\@.service      
[Unit]
Description=OpenBMC console daemon for %I
ConditionPathExists=/dev/%i

[Service]
ExecStart=< Add any thing >
Restart=always

[Install]
WantedBy=multi-user.target
```

Step 2 : Have a socket activation file like this on a non existing device.

```
root@barreleye:~# cat /lib/systemd/system/obmc-console-ssh.socket 
[Unit]
Description=OpenBMC console ssh server socket
Conflicts=obmc-console-ssh@ttyS40.service
Requires=obmc-console@ttyS40.service
After=obmc-console@ttyS40.service

[Socket]
ListenStream=2200
Accept=yes

[Install]
WantedBy=sockets.target
```

Step #3 : systemctl start obmc-console-ssh.socket

**Comment by poettering** [comment]
ConditionXYZ= silently skips a service if the specifieid conditoin is not met. It does not result the job starting it to be considered failed.

if you want that, use AssertXYZ= instead.

**Comment by vishwabmc** [comment]
@poettering  Thank you.
