### ISSUE TITLE
Services with ProtectHome=yes fail to start if /home is a symlink

### ISSUE THREAD

**Issue by lolomokakus** [systemd/systemd#3867]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Services with ProtectHome=yes running normally
### In case of bug report: Unexpected behaviour you saw

> Three services, namely systemd-hostnamed.service, systemd-timedated.service and systemd-timesyncd.service all suddenly refused to start with the error message "Too many levels of symbolic links" and the status 226/NAMESPACE. I assume this happened after I ran a system upgrade and systemd 231 was installed. With some help I managed to discovered the services ran when I commented out ProtectHome=yes in their .service files, and then I found out /home being a symlink was what caused the issue.
### In case of bug report: Steps to reproduce the problem

> Remove /home and link another directory to it.

**Comment by floppym** [comment]
We also have a user who ran into this on Gentoo.

https://bugs.gentoo.org/show_bug.cgi?id=590100

I believe this is a possible regression introduced in c4b41707462a74eb7008e8d12a0b4d0a0c09bff4. I think that code returns -ELOOP in this case.

CC: @alepuccetti

**Comment by poettering** [comment]
cc @alepuccetti
