### ISSUE TITLE
RFE: Scheduling directives for timers

### ISSUE THREAD

**Issue by dmedri** [systemd/systemd#3868]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

misc
### 

With many heavy concurrent .timer(s) on the same OnCalendar case, the system load could be too high with the all-at-once (default) execution. Are Before= and After= (see link: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=) available for timers? Do we need more specific directives?

**Comment by arvidjaar** [comment]
There is `RandomizedDelaySec` intended to avoid precisely this effect. Did you try it?

**Comment by poettering** [comment]
The activated services may use Before= and After= between each other, to order execution if multiple of them are queued. Moreover there's RandomizedDelaySec= to spread activation of services over a certain amount of time.

Hence I think we are pretty well covered here already. Closing.
