### ISSUE TITLE
journalctl doesn't show remote logs with 'unsupported feature' error

### ISSUE THREAD

**Issue by eungjun-yi** [systemd/systemd#3875]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd 231

(latest master at 9d565427647a874b7eda64ef0cb41ea74a96659b)
### Used distribution

Ubuntu 16.04 LTS
### In case of bug report: Expected behaviour you didn't see

journalctl shows remote logs.
### In case of bug report: Unexpected behaviour you saw

journalctl doesn't show remote logs with 'unsupported feature' error.

```
$ sudo journalctl --directory=/var/log/journal/remote _HOSTNAME=node1
Journal file /var/log/journal/remote/remote-52.78.113.210.journal uses an unsupported feature, ignoring file.
-- No entries --
```
### In case of bug report: Steps to reproduce the problem
1. On `log` host, start `systemd-journal-remote`
2. On `node1` host, configure `systemd-journal-upload` to upload logs to `log` host and start it.
3. On `log` host, query the logs from `node1`
   
   ```
   $ sudo journalctl --directory=/var/log/journal/remote _HOSTNAME=node1
   ```

**Comment by poettering** [comment]
This indicates that the remote journal uses some feature the local version does not support. Most likely this is some compression algorithm, probably XZ? You have to compile the local version with XZ version if you want it to be able to read files from a remote version that uses XZ. 

`journalctl --version` tells you whether XZ support was enabled. Run this locally, and on the remote machine, to see whether XZ support is enabled in both or neither.

**Comment by eungjun-yi** [comment]
@poettering Thanks very much! It works well after I installed the build dependencies by `sudo apt-get build-dep systemd` and rebuild it.
