### ISSUE TITLE
Could not append VLANs | Could not set bridge vlan (Operation not permitted)

### ISSUE THREAD

**Issue by vindicatorr** [systemd/systemd#3876]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> $ /usr/lib/systemd/systemd --version
> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> Aug 03 04:42:45 server.lan systemd-networkd[26007]: br0: netdev exists, using existing without changing its parameters
> ...br0: Could not append VLANs: Operation not permitted
> br0: Failed to assign VLANs to bridge port: Operation not permitted
> br0: Could not set bridge vlan: Operation not permitted
> br0: Configured
> br0: custom_eth1: Could not append VLANs: Operation not permitted
> br0: custom_eth1: Failed to assign VLANs to bridge port: Operation not permitted
> br0: custom_eth1: Could not set bridge vlan: Operation not permitted
> br0: custom_eth0: DHCPv4 address &lt;sanitized&gt; via &lt;sanitized&gt;
### In case of bug report: Steps to reproduce the problem

> Upgraded systemd on Arch Linux from 230-7 -&gt; 231-1 but just now noticed that error.

```
$ cat /etc/systemd/network/45-bridge.network 
[Match]
Name=br0

[Network]
Description="br0 - Bridge Network"
Address=192.168.#.#/24
DNS=192.168.#.#
IPv6AcceptRouterAdvertisements=false
```

```
$ cat /etc/systemd/network/50-eth1.network   
[Match]
#Name=eth1
#"Name" doesn't get used when MAC is set?
MACAddress=<sanitized>

[Network]
Description="eth1 - LAN"
Bridge=br0
IPv6AcceptRouterAdvertisements=false
```

IRC
(username's sanitized)
(user1): "maybe the kernel is too old, or lacks CONFIG_BRIDGE_VLAN_FILTERING"
(self):

```
$ cat /proc/config.gz | gunzip | grep 'CONFIG_BRIDGE_VLAN_FILTERING'
CONFIG_BRIDGE_VLAN_FILTERING=y
$ uname -a
Linux dd.lan 4.4.0+ #1 SMP PREEMPT Wed Jan 20 06:32:54 UTC 2016 armv7l GNU/Linux
```

(user2): "hm, I'm getting that on arch (testing) which has CONFIG_BRIDGE_VLAN_FILTERING=y"
(user2): "now, I wonder why I don't get it on my other arch machine"

**Comment by vindicatorr** [comment]
Amendment:
After rebooting, there were no errors, but when I restarted networkd, the errors reappeared.
However, a user on IRC says it happens to them on boot as well.

**Comment by poettering** [comment]
Hmm, the error message are generated by the brvlan code added via #3428, which afaics isn't even used in your config?

@toanju, any idea about this one?

**Comment by jamespharvey20** [comment]
[dmesg.grep.networkd.txt](https://github.com/systemd/systemd/files/400703/dmesg.grep.networkd.txt)

Seeing the same on upgrade to v231, on each boot.  For me, networking is working fine, although I haven't re-setup the VM's that would otherwise be using the bridge, so it's just this one install that's using the bridge.

Attached is output of `dmesg | grep networkd` with kernel parameters for systemd.log_level=debug,etc

```
Linux terra 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
Also with CONFIG_BRIDGE_VLAN_FILTERING=y

# cat /etc/systemd/network/br0.netdev 
[NetDev]
Name=br0
Kind=bridge
# cat /etc/systemd/network/br0.network 
[Match]
Name=br0

[Network]
DNS=8.8.8.8
DNS=8.8.4.4
Address=192.168.1.2/24
Gateway=192.168.1.1
# cat /etc/systemd/network/enp31s0.network 
[Match]
Name=enp31s0

[Network]
Bridge=br0
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp31s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP group default qlen 1000
    link/ether 00:1c:c4:17:8f:02 brd ff:ff:ff:ff:ff:ff
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9a:27:f1:c7:69:92 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::9827:f1ff:fec7:6992/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by toanju** [comment]
hm, I will check this later today

**Comment by toanju** [comment]
after having a look at this issue now, the functions to apply the bridge vlan configuratino are called for every bridge [here](https://github.com/systemd/systemd/blob/master/src/network/networkd-link.c#L2064). Its not a critical issue rather annoying, because of the printed message.

I'll prep a patch to check if the vlan_filtering flag is set.
