### ISSUE TITLE
networkd bridge support missing ability to turn on STP and/or documentation

### ISSUE THREAD

**Issue by ikelos** [systemd/systemd#3881]
As best I can tell, even though issue 1172 has been closed, there is still no way to enable STP on a bridge in systemd-231's networkd.  The only two mentions of STP are for UseBPDU= and AllowPortToBeRoot= both of which default to true, but do not themselves enable STP.  Issue 1172 requested opening a new ticket if any properties were still missing.  It's possible this is simply a documentation problem, but the source code doesn't suggest there's any support for enabled STP either.

Also, the options mentioned in 1172 do not appear to have been documented in the systemd.network man page if they were actually implemented (neither sethello, nor forward delay are mentioned by those names).

If there is already a recommended means to enable STP (even if that involves using mstpd instead) then please could the documentation be updated to indicate this.  If not, would it be possible to add these options?

**Comment by poettering** [comment]
@ssahani something for you?

**Comment by keszybz** [comment]
@ikelos see:
- https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#HelloTimeSec=
- https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#ForwardDelaySec=

**Comment by ikelos** [comment]
Thanks,

I saw those from the bug I referenced, but there wasn't any indication in
their documentation that they would turn on STP?  If those are all that's
necessary (and the additional patch that was added to close this issue
isn't) then the documentation would still need updating to include the word
STP.  It's explicitly a function of brctl to change the STP state, so doing
it as part of setting other parameters which don't even mention it in the
documentation would be counter intuitive.  I think the patch that resolved
this was the right way to go...

Mike 5:)

**Comment by keszybz** [comment]
Well, you wrote that "the options mentioned in 1172 do not appear to have been documented in the systemd.network", I was answering that.

**Comment by ikelos** [comment]
Ah sorry, my mistake.  I'd been referring to the "setstp" option mentioned in the subject line but then seemingly lost in the remaining conversation.  Thanks for the pointers, they are indeed documented but not quite what I was after.  5:)

**Comment by ikelos** [comment]
(I'd also only been looking in the systemd.network man page, not systemd.netdev.  Again, my bad, sorry.)

**Comment by NicoHood** [comment]
@ikelos sorry for abusing this comment, but you turned off notifications for your own projects. I hope this issuecomment triggers your notification inbox (sorry systemd team).

We've forked your shuffle project a long time ago and made huge improvements so far. You might want to have a look at it here: https://github.com/nims11/IPod-Shuffle-4g
I've opened a PR on your project, however you have unscubscribed from notifications there, so you've probably missed it also. It would be nice if you can give us some feedback, as you are the original author of this script :)

**Comment by gtjoseph** [comment]
I'm reopening this because for the life of me, I can't figure out how to turn on STP.
Fedora 24/25, Systemd 231, Kernel 4.8.8

The docs at https://www.freedesktop.org/software/systemd/man/systemd.netdev.html don't match the man pages for 231 so that's certainly confusing but for a simple 2 port bridge, how do I turn STP?  No bonding, no vlans, nothing.

Here's what I've got so far...
```
# 10-mlx4-1.network
[Match]
MACAddress=00:02:c9:4e:fb:0c

[Network]
Bridge=br0

[Bridge]
HairPin=false
UnicastFlood=true
UseBPDU=true
FastLeave=true
```

```
# 10-mlx4-2.network
[Match]
MACAddress=00:02:c9:4e:fb:0d

[Network]
Bridge=br0

[Bridge]
HairPin=false
UnicastFlood=true
UseBPDU=true
FastLeave=true
```

```
# 20-br0.netdev
[NetDev]
Name=br0
Kind=bridge

[Bridge]
VLANFiltering=true
MulticastSnooping=true
MulticastQuerier=true
```

```
# 30-br0.network
[Match]
Name=br0

[Network]
Address=10.0.0.245/24
```

No matter what I do, stp is still "no"
```
# brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.06daf7535913	no		ens6
							ens6d1
```
What am I missing and what happened to Priority?  It seems to have gone missing.

EDIT: Ok, After clicking through a bunch of links I wound up at the commit that adds STP.

**Comment by keszybz** [comment]
@gtjoseph It seems you need to use STP=yes.
See https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#STP=.

> What am I missing and what happened to Priority? It seems to have gone missing.

See https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#Priority=.

**Comment by gtjoseph** [comment]
Yeah unfortunately the documentation at https://www.freedesktop.org/software/systemd/man/systemd.netdev.html which shows the STP and Priority options also says "systemd 231" but STP and Priority didn't appear until 232.  That's what was confusing the hell out of me.  Ultimately I went with udev rules to turn on STP and set the priority.  When Fedora goes to 232, I'll try the netdev files again.

**Comment by keszybz** [comment]
I didn't get uploaded properly when v232 was released. I did that now.

**Comment by jojoax** [comment]
Now in v233 this bug is still alive.
